### ISSUE TITLE
`rustc --test` ignores `static:-whole-archive` link modifiers

### ISSUE THREAD

**Issue by dcsommer** [rust-lang/rust#100066]
I am attempting to use the ([now stabilized](https://github.com/rust-lang/rust/pull/93901)) [RFC 2951](https://rust-lang.github.io/rfcs/2951-native-link-modifiers.html) syntax to control how my test binary is compiled. I have created a repro at https://github.com/dcsommer/rustc-linking

```
git clone https://github.com/dcsommer/rustc-linking.git
cd rustc-linking
./run.sh
```

In `run.sh`, I tell `rustc` to link 2 static libraries, one *with* (+whole-archive) and one *without* (-whole-archive). I add a nonsense link argument so I can inspect the produced link line.

I expect to see `libbar.a` linked without whole archive.

Instead, I see both `foo` and `bar` libraries linked with --whole-archive:
```
-l static:+whole-archive=foo -l static:-whole-archive=bar
# linker line yields ...
"-Wl,-Bstatic" "-Wl,--whole-archive" "-lfoo" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "-lbar" "-Wl,--no-whole-archive"
```

This may be related to the default `+bundle` documented [here](https://rust-lang.github.io/rfcs/2951-native-link-modifiers.html#bundle). When I use nightly and specify `-bundle` it works as expected:

```
-l static:+whole-archive,-bundle=foo -l static:-whole-archive,-bundle=bar
# linker line yields ...
"-Wl,-Bstatic" "-Wl,--whole-archive" "-lfoo" "-Wl,--no-whole-archive" "-lbar"
```

However, I cannot use the nightly toolchain, so I cannot use `-bundle`, and `+bundle` seems inappropriate for a final binary crate types like cdylib, staticlib, and executables anyway.

Tested with 1.62.1 stable and 1.64 nightly.

Possibly related issues: #99429, #73632

**Comment by petrochenkov** [comment]
This is a bug introduced in https://github.com/rust-lang/rust/pull/95606.
The backward compatibility condition should look like `whole_archive == None && bundle != Some(false) && sess.opts.test` and not `bundle != Some(false) && sess.opts.test`.

**Comment by petrochenkov** [comment]
@dcsommer 
Could you submit a PR with this fix?
(We can backport it to beta if it's done in time.)

**Comment by dcsommer** [comment]
@petrochenkov Sure, I'll create a PR. I'm not sure what tests to include, however.

**Comment by petrochenkov** [comment]
You can try adding a test case with `--test` to `src\test\run-make\native-link-modifier-whole-archive\Makefile`.
One with `--test` and `-whole-archive`, and another with `--test` and without any `whole-archive` (the compatibility case).
