### ISSUE TITLE
[rustdoc] Hide impl block containing only private items by default

### ISSUE THREAD

**Issue by jhpratt** [rust-lang/rust#100001]
[Zulip thread where this was discussed](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/empty.20impl.20block/near/291286595)

cc @GuillaumeGomez

@rustbot label +A-docs +A-rustdoc-ui +C-enhancement +T-rustdoc

This is technically a regression, but it doesn't feel appropriate to label it as such.

**Comment by jyn514** [comment]
Here is an example of a block that should be hidden when `--document-private-items` is not passed:
```rust
pub struct S;

/// Some docs here
impl S {
  fn foo() {}
}
```
