### ISSUE TITLE
Rust is Beautiful

### ISSUE THREAD

**Issue by Mathspy** [rust-lang/rust#100000]
:heart: :crab: :heart: 

100,000 issues filled with love, compassion and a wholesome community. Thank you, Rust community, for being one of the most, if not straight out the most, welcoming programming communities out there. Thank you, Rust teams, for the tireless hours you spend every day on every aspect of this project. Thank you to the Rust team alumni for the many hours spent growing a plant and the humility of passing it to people you trust to continue taking care of it. Thank you everyone for RFCs, giving voice to the community, being those voices AND listening to each other.

This community has been and continue to be one of the best I have ever had the pleasure of being a part of. The language itself has many things to love and appreciate about it, from the humane error messages to giving the people the power to express high performance code without sacrificing readability for the ones to come after us. But nothing, truly nothing, takes the cake as much as the community that's building it, answering questions, helping and loving each other. Every single day.

Congratulations everyone for 100,000 issues and PRs! And thank you for being you. Because Rust is Beautiful, for having you as part of it.

To the times we spent together and the many more to come! :orange_heart:

**Comment by chop0** [comment]
shush

**Comment by Nilstrieb** [comment]
❤️ 🦀 ❤️

**Comment by RossSmyth** [comment]
❤️ 🦀 ❤️

**Comment by dconnolly** [comment]
🦀🧡🦀

**Comment by Piturnah** [comment]
💚🦀💚

<3 Rust

**Comment by LoganDark** [comment]
UwU

**Comment by lovelyyfiaaa** [comment]
I love Rust soo much!!! Happy issuee #100000 everyonee!!! 😊

**Comment by wemgl** [comment]
❤️🦀❤️

**Comment by kcubeterm** [comment]
Love you Rust

**Comment by manaskarekar** [comment]
This is one of the most welcoming communities I've seen, and rust itself is a joy to behold. Here's to many more!

**Comment by jackos** [comment]
> This community has been and continue to be one of the best I have ever had the pleasure of being a part of

It's my favourite community by a long way, I never even thought about making contributions to official language repo's before rust, I feel very welcomed in this community 😀

**Comment by moksh-mahajan** [comment]
❤️🦀❤️

**Comment by MomoLangenstein** [comment]
❤️🦀❤️

**Comment by shabane** [comment]
now I want to learn `rust`

**Comment by zonemeen** [comment]
❤️🦀❤️

**Comment by chenerg** [comment]
❤️🦀❤️

**Comment by Cyborus04** [comment]
❤️🦀❤️

**Comment by faern** [comment]
:heart::crab::heart:

**Comment by fffzlfk** [comment]
❤️🦀❤️

**Comment by Rageking8** [comment]
❤️🦀❤️

**Comment by Gary50613** [comment]
❤️🦀❤️

**Comment by amesy** [comment]
❤️🦀❤️

**Comment by LePichu** [comment]
❤️ 🦀 ❤️

**Comment by TieWay59** [comment]
❤️ 🦀 ❤️ Happy to work with such brilliant language.

**Comment by lencx** [comment]
❤️ 🦀 ❤️

**Comment by Igigog** [comment]
❤️ 🦀 ❤️

**Comment by maximousblk** [comment]
❤️ 🦀 ❤️

**Comment by marc2332** [comment]
![imagen](https://user-images.githubusercontent.com/38158676/182097240-eb6bd22f-8d75-432f-96ef-d2ae3bdd0144.png)
I Love Rust  ❤️ 🦀 ❤️

**Comment by floriantz** [comment]
❤️ 🦀 🦀 ❤️

**Comment by TheBestTvarynka** [comment]
![image](https://user-images.githubusercontent.com/43034350/182103910-3aa6e2ac-305e-4e2a-8131-6a82c8c66494.png)
❤️ 🦀 ❤️

**Comment by frengor** [comment]
❤️🦀❤️

**Comment by myname1111** [comment]
❤️🦀❤️

**Comment by Garker** [comment]
❤️🦀❤️

**Comment by Andy-Python-Programmer** [comment]
<3 rust. Lets all celebrate this moment by rewriting one piece of software in rust :trollface:.

🚀 Blazingly Fast Gang 🚀

**Comment by MarlzRana** [comment]
❤️

**Comment by JSKitty** [comment]
❤️🦀❤️

**Comment by Alishahidi** [comment]
Nice 👍🙂 ❤️❤️

**Comment by thecaralice** [comment]
♥️🦀♥️ i love this community

**Comment by SchrodingerZhu** [comment]
♥️🦀♥️

**Comment by iamonuwa** [comment]
♥️🦀♥️

**Comment by devtomio** [comment]
♥️🦀♥️ rust🚀

**Comment by mindstorm38** [comment]
🦀

**Comment by BlueskyFR** [comment]
🦀🦀🦀 🥳🎉

**Comment by Alonely0** [comment]
❤️🦀❤️

**Comment by AZProductions** [comment]
❤🦀❤

**Comment by EliasFleckenstein03** [comment]
:heart::crab::heart:

**Comment by erwanor** [comment]
❤️🦀❤️


❤️🦀❤️


❤️🦀❤️


❤️🦀❤️

**Comment by supergnaw** [comment]
> now I want to learn `rust`

I started picking up rust ironically because of memes and shitposts I was seeing, and now I unironically love it.

**Comment by TahaTesser** [comment]
❤️ 🦀 ❤️

**Comment by itsTyrion** [comment]
❤️ 🦀 ❤️
https://i.giphy.com/media/2dK0W3oUksQk0Xz8OK/giphy.webp

**Comment by ismailcherri** [comment]
❤️🦀❤️
I really love the community.. Keep it up

**Comment by RDambrosio016** [comment]
❤️🦀 crab

**Comment by FedericoSchonborn** [comment]
❤🦀❤

**Comment by Restioson** [comment]
♥ 🦀 ♥

**Comment by pwoolcoc** [comment]
❤️ 🦀 ❤️

**Comment by zitsen** [comment]
:heart: :crab: :heart:

**Comment by MarlzRana** [comment]
❤️🦀❤️

**Comment by langzime** [comment]
❤️🦀❤️

**Comment by cpea2506** [comment]
❤️🦀❤️ Yay!

**Comment by aviramha** [comment]
🤟  🦀 🤟

**Comment by nappa85** [comment]
![image](https://user-images.githubusercontent.com/7566389/182146096-fe8275e3-6315-4869-8815-09d86c443c41.png)

**Comment by baneetparmar** [comment]
❤️🦀❤️

**Comment by ignazio-castrogiovanni** [comment]
❤️🦀❤️🦀❤️

**Comment by cnuebred** [comment]
❤️🦀❤️

**Comment by itohatweb** [comment]
❤️🦀❤️

**Comment by SummonSteve** [comment]
💚🦀💚

**Comment by Monadic-Cat** [comment]
:green_heart:

**Comment by TigrRooT** [comment]
<3

**Comment by Filip-Tomasko** [comment]
❤️🔥💜

**Comment by mon-jai** [comment]
❤️🦀❤️

**Comment by manank20** [comment]
❤️🦀❤️

**Comment by awh6al** [comment]
Rust is the future

**Comment by jharrilim** [comment]
🧡🦀🧡

**Comment by Cyborus04** [comment]
Proposition to pin?

**Comment by danielyrovas** [comment]
🦀 C 🦀 R 🦀 A 🦀 B 🦀  🦀 R 🦀 A 🦀 V 🦀 E 🦀

**Comment by JasonkayZK** [comment]
❤️ 🦀 ❤️

**Comment by seanchen1991** [comment]
You beautifully summed up my sentiments of the Rust language and its community: come for the language (or sometimes the memes 😉), stay for the community ❤️

**Comment by NoComment1105** [comment]
❤️ 🦀 ❤️

**Comment by leocth** [comment]
:heart::crab::heart: May the funny crab lang live long and prosper

**Comment by abrowne2** [comment]
❤️ 🦀 ❤️

**Comment by nox** [comment]
![e4b48373c6bc74d4e61ce78042d61c5dc186f3fcr1-390-290_hq](https://user-images.githubusercontent.com/123095/182166076-20de19f4-3592-49d7-a40a-f466c6c58d00.gif)

**Comment by akabinds** [comment]
❤️🦀❤️
rust for life

**Comment by PleahMaCaka** [comment]
:heart::crab::heart:

**Comment by gemone** [comment]
:heart: :crab: :heart:

**Comment by rdrpenguin04** [comment]
❤️🦀❤️

**Comment by hapash-reguiam** [comment]
❤️♥️🦀🦀🦀🦀 ♥️♥️

**Comment by Merded** [comment]
❤️🦀❤️🦀

**Comment by Dolphin2Point1** [comment]
thanks for making funny crab language :heart: :crab:

**Comment by ijliym** [comment]
❤️❤️祝贺

**Comment by Hocuri** [comment]
❤️❤️❤️❤️   ❤️   ❤️   ❤️❤️❤️   ❤️❤️❤️❤️❤️  
❤️   ❤️  ❤️   ❤️  ❤️   ❤️    ❤️    
❤️   ❤️  ❤️   ❤️  ❤️        ❤️    
❤️   ❤️  ❤️   ❤️  ❤️        ❤️    
❤️❤️❤️❤️   ❤️   ❤️   ❤️❤️❤️     ❤️    
❤️❤️     ❤️   ❤️      ❤️    ❤️    
❤️ ❤️    ❤️   ❤️      ❤️    ❤️    
❤️  ❤️   ❤️   ❤️  ❤️   ❤️    ❤️    
❤️   ❤️   ❤️❤️❤️    ❤️❤️❤️     ❤️

**Comment by Earthcomputer** [comment]
:heart: :crab: :heart:

**Comment by MidnQP** [comment]
I'm still learning Rust. A few great 📚concepts to grasp and get better at - before I start writing supercool, clean, maintainable, blazing fast 🚀🔥 Rust code. 
❤️🦀❤️

**Comment by ElfWitch** [comment]
❤️🦀❤️
You're all the best!
❤️🦀❤️

**Comment by Jwindler** [comment]
❤️

**Comment by od0** [comment]
❤️🦀❤️

**Comment by hoangph271** [comment]
You're all beautiful...! 💕

**Comment by arrudagates** [comment]
![abc563150f48f0a8e6301b7e91027d8d.gif](https://user-images.githubusercontent.com/30242466/182192228-ef973bbb-2018-4909-89f6-92d5c65392d3.gif)

**Comment by lck** [comment]
despite the fact that I don't use rust professionally, I learned a lot just by studying it

**Comment by big-lip-bob** [comment]
:crab: In Rust we trust :crab:

**Comment by yaahc** [comment]
Thank you, as just one of a long line of contributors and community members who have made Rust what it is today, I deeply appreciate this message. In fact, I think I might just have to get it framed.

❤️🦀❤️

**Comment by Rafael-Conde** [comment]
What a time to be alive!! <3 Rust <3

Thank you to this awesome community!!!

**Comment by wojciech-cichocki** [comment]
Rust is like your girlfriend, so many people love her <3 @NorbertBodziony

**Comment by always-maap** [comment]
The future of software is bright ❤️🦀❤️

**Comment by cotneit** [comment]
❤️🦀❤️

**Comment by ramones156** [comment]
We love rust!
![image](https://user-images.githubusercontent.com/55579979/182196918-13785058-4578-4fe5-ae48-c0b48ca8d31f.png)

**Comment by Dolpheyn** [comment]
❤️🦀❤️

**Comment by Selicre** [comment]
I think it would be apt to close this issue as "wontfix". :blue_heart:

**Comment by erwanvivien** [comment]
❤️🦀❤️ aayyyyyyy everyday we rustin' 🚀

**Comment by jht5945** [comment]
I ❤️ 🦀 !

**Comment by EduRenesto** [comment]
❤️🦀❤️

**Comment by Omar-Belghaouti** [comment]
🦀❤️

**Comment by maddymakesgames** [comment]
❤️🦀❤️

**Comment by mohammadjavad948** [comment]
❤️🦀❤️

**Comment by HarryET** [comment]
❤️🦀❤️

**Comment by ma1ted** [comment]
❤️ 🦀 ❤️

**Comment by ErikKarlgren** [comment]
❤🦀🦀🦀🦀🦀❤

**Comment by parker-codes** [comment]
❤️🦀❤️

**Comment by anden3** [comment]
❤️ 🦀 ❤️

**Comment by nico-abram** [comment]
❤️ 🦀 ❤️
Long live rust

**Comment by J-TAG** [comment]
❤️🦀❤️

**Comment by Milo123459** [comment]
❤️🦀❤️

**Comment by pxp9** [comment]
heartcrabheart

**Comment by sam20908** [comment]
I LOVE RUST ❤️

**Comment by sinaomrani** [comment]
(\\/) (♡,,,,♡) (\\/)

**Comment by JuanMarchetto** [comment]
❤️🦀!

**Comment by arijit79** [comment]
Congratulations 🎉🎉🎉🎉 Rust 🦀 for #100000 issue

**Comment by 01mf02** [comment]
:heart: :crab: :heart:

**Comment by hydrogenbond007** [comment]
Even though I am just starting to learn rust, already feels like family.

**Comment by tguichaoua** [comment]
❤🦀❤

**Comment by janogale** [comment]
Congratulations 🎉🎉🎉🎉 Rust 🦀community 💖

**Comment by HoomanOnEarth** [comment]
nice, time to learn rust

**Comment by MoskalykA** [comment]
❤🦀❤

**Comment by Oreoezi** [comment]
Congrats on the milestone 🦀♥️
ᕙ(ಠ ਊ ಠ)ᕗ

**Comment by SorenSaket** [comment]
🦀🦀🦀🥰😍

**Comment by typeable-nickname** [comment]
![](https://github.githubassets.com/images/icons/emoji/unicode/1f980.png)

![](https://github.githubassets.com/images/icons/emoji/unicode/1f980.png)

![](https://github.githubassets.com/images/icons/emoji/unicode/1f980.png)

![](https://github.githubassets.com/images/icons/emoji/unicode/2665.png)

**Comment by Phinner** [comment]
🦀 Blazingly fast, as always 🦀

**Comment by pxp9** [comment]
This issue will be close with Love

**Comment by tonyalaribe** [comment]
Congrats to the rust community.  Sending rusty hugs 🤗🤗🤗❤️❤️❤️❤️🦀🦀🦀🦀🦀
![download](https://user-images.githubusercontent.com/6564482/182235051-c8b0c729-1814-4b05-b5f7-ce2346031878.jpeg)

**Comment by lectromoe** [comment]
<img src="https://user-images.githubusercontent.com/72769566/174778672-94dcc92e-59ac-48c1-9cf6-71870482feb2.png" width="50" align="center"> ❤️

**Comment by danielsn** [comment]
![image](https://user-images.githubusercontent.com/4389518/182236350-e43a3879-0f73-4761-9d75-66c50367027b.png)

Kani sharing the ❤️

**Comment by KBone12** [comment]
:heart: :crab: :heart:

**Comment by xolve** [comment]
I 🦀 rust.

**Comment by BurnyBoi** [comment]
![floppa-vibing-big-floppa-vibing](https://user-images.githubusercontent.com/41203525/182244880-560088d3-8141-4a65-8fb7-7cc3e2d445ee.gif)

**Comment by JelNiSlaw** [comment]
🦀

**Comment by OdedShimoni** [comment]
❤️🦀❤️

**Comment by evant** [comment]
:heart: :crab: :heart:

**Comment by ByteDream** [comment]
♥️🦀♥️

**Comment by CodeDead** [comment]
🦀🦀🦀

**Comment by dwisiswant0** [comment]
![#](https://giphy.com/gifs/crab-rave-dance-party-2dK0W3oUksQk0Xz8OK)

**Comment by nehalch** [comment]
❤️🦀❤️

**Comment by BD103** [comment]
❤️🦀❤️

**Comment by SpeedyCraftah** [comment]
rust is ok i guess

**Comment by jonasohland** [comment]
♥️🦀♥️

**Comment by joseluis** [comment]
![ferris is pure love](https://user-images.githubusercontent.com/5832068/182263022-088febd2-f0c3-4e26-9c4d-4074e2c4fa52.png)

**Comment by darah3ng** [comment]
This is very wholesome. 💪 

Gonna add learning Rust to my list.

**Comment by Mercen-Lee** [comment]
❤️🦀❤️

**Comment by uvd** [comment]
❤️ 🦀 ❤️

**Comment by bigmarselo** [comment]
> ❤️ 🦀 ❤️
> 
> 100,000 issues filled with love, compassion and a wholesome community. Thank you, Rust community, for being one of the most, if not straight out the most, welcoming programming communities out there. Thank you, Rust teams, for the tireless hours you spend every day on every aspect of this project. Thank you to the Rust team alumni for the many hours spent growing a plant and the humility of passing it to people you trust to continue taking care of it. Thank you everyone for RFCs, giving voice to the community, being those voices AND listening to each other.
> 
> This community has been and continue to be one of the best I have ever had the pleasure of being a part of. The language itself has many things to love and appreciate about it, from the humane error messages to giving the people the power to express high performance code without sacrificing readability for the ones to come after us. But nothing, truly nothing, takes the cake as much as the community that's building it, answering questions, helping and loving each other. Every single day.
> 
> Congratulations everyone for 100,000 issues and PRs! And thank you for being you. Because Rust is Beautiful, for having you as part of it.
> 
> To the times we spent together and the many more to come! 🧡

🦀❤️❤️

**Comment by bigmarselo** [comment]
❤️🦀

**Comment by withlin** [comment]
❤️ 🦀 ❤️

**Comment by ix0rai** [comment]
:heart: :crab: :heart:

**Comment by Toursslivers** [comment]
❤️ 🦀 ❤️

**Comment by iutx** [comment]
❤️ 🦀 ❤️

**Comment by NlCEDAY** [comment]
❤️ 🦀 ❤️

**Comment by Coordinate-Cat** [comment]
❤️ 🦀 ❤️

**Comment by Borber** [comment]
❤️ 🦀 ❤️

**Comment by sav** [comment]
heart crab heart

**Comment by bigwhite** [comment]
I am confused about how 100000 came about. the total count of issues(open+closed) is less than 5w. could someone tell me the reason.

<img width="582" alt="image" src="https://user-images.githubusercontent.com/419088/182275253-9e120551-0406-410d-8d82-f5cef71b502f.png">

**Comment by HTG-YT** [comment]
> I am confused about how 100000 came about. the total count of issues(open+closed) is less than 5w. could someone tell me the reason.
> 
> 
> 
> <img width="582" alt="image" src="https://user-images.githubusercontent.com/419088/182275253-9e120551-0406-410d-8d82-f5cef71b502f.png">
> 
> 

That number is Issues + PRs...

**Comment by bigwhite** [comment]
> > I am confused about how 100000 came about. the total count of issues(open+closed) is less than 5w. could someone tell me the reason.
> > <img alt="image" width="582" src="https://user-images.githubusercontent.com/419088/182275253-9e120551-0406-410d-8d82-f5cef71b502f.png">
> 
> That number is Issues + PRs...

get it. thank you!

**Comment by JasonShin** [comment]
Thanks for this great programming language

**Comment by jdobbin-hsahealthplan** [comment]
❤️ 🦀 ❤️

**Comment by JoshDobbin** [comment]
❤️ 🦀 ❤️

**Comment by naj1n** [comment]
❤️🦀️❤️

**Comment by Skenvy** [comment]
I forgot that linking it would pop up here, but I'm borrowing "❤️🦀️❤️" for what will be my first Rust project because this is just so wholesome.

**Comment by parkerqueen** [comment]
❤️🦀❤️

**Comment by BlueStaggo** [comment]
❤🦀❤
Rust deserves to be the most loved programming language!

**Comment by MultisampledNight** [comment]
Awesome, consistent, comfortable, verbose if needed and sensible language, package manager, build system and community. :purple_heart::crab::purple_heart:

**Comment by lunandd** [comment]
🦀 <33

**Comment by pikhosh** [comment]
❤️ 🦀 ❤️

**Comment by ajansari95** [comment]
🦀💚

**Comment by Sculas** [comment]
❤️🦀❤️

**Comment by Powerbored** [comment]
I work with a team of Java developers and this certainly is an issue 😅

**Comment by avelino** [comment]
Congrats 🎉🎈🍾

**Comment by cshif** [comment]
🦀️ 💖

**Comment by marcospb19** [comment]
:heart::crab::heart:

**Comment by alphaolomi** [comment]
❤🦀❤

**Comment by arnavbhatt288** [comment]
My wife's boyfriend liked this. :heart::crab::heart:

**Comment by huhlig** [comment]
❤️🦀❤️

**Comment by iago-lito** [comment]
:heart: :crab: :heart:

**Comment by Lisenaaaa** [comment]
yooo epic!

:heart: :crab: :heart:

**Comment by BasToTheMax** [comment]
I never used rust, mostly because I am using Javascript for frontend, but this is still a very good milestone! Keep it up!
👍😉

**Comment by Jint3x** [comment]
❤️ 🦀 ❤️

**Comment by cnheider** [comment]
🎉

**Comment by BRAVO68WEB** [comment]
Great Language. Happy to Rust Lang and the Community

**Comment by djpiper28** [comment]
I'm NeW, CaN SoMeOnE tElL mE HoW tO mAlLoC iN rUsT?

**Comment by princessmortix** [comment]
I don't personally use Rust but happy 100000-issue-day. 💖🦀💖

**Comment by lack-io** [comment]
❤🦀❤

**Comment by WormPatch** [comment]
crab

**Comment by Ilqjx** [comment]
❤️ 🦀 ❤️

**Comment by csjiabin** [comment]
❤️ 🦀 ❤️

**Comment by khoover** [comment]
> I'm NeW, CaN SoMeOnE tElL mE HoW tO mAlLoC iN rUsT?

Sure.

```rust
let foo: Box<[u8; std::mem::size_of::<Bar>()]> = Box::default();
let bar: *mut Bar = unsafe {
  let mut foo: Box<Bar> = std::mem::transmute(foo);
  &mut *foo
};
```

**Comment by PatrickShaw** [comment]
❤️🦀❤️

**Comment by l1npengtul** [comment]
:heart: :crab: :heart:

**Comment by AlanDeLosky** [comment]
🎉 🎉 🎉

**Comment by jenra-uwu** [comment]
:heart: :crab: :heart:

**Comment by reez12g** [comment]
❤️ 🦀 ❤️

**Comment by unknowntrojan** [comment]
❤️ 🦀 ❤️

**Comment by metalwhale** [comment]
❤️ 🦀 ❤️

**Comment by Purpzie** [comment]
❤️ 🦀 ❤️

**Comment by djpiper28** [comment]
> > I'm NeW, CaN SoMeOnE tElL mE HoW tO mAlLoC iN rUsT?
> 
> Sure.
> 
> ```rust
> let foo: Box<[u8; std::mem::size_of::<Bar>()]> = Box::default();
> let bar: *mut Bar = unsafe {
>   let mut foo: Box<Bar> = std::mem::transmute(foo);
>   &mut *foo
> };
> ```

Thanks now I can make an array with a length unknown at compile time

**Comment by Ph0enixKM** [comment]
❤️🦀❤️

**Comment by cor** [comment]
❤️🦀❤️

**Comment by duplexsystem** [comment]
❤️🦀❤️

**Comment by dotneet** [comment]
❤️🦀❤️

**Comment by anupj** [comment]
❤️ 🦀 ❤️

**Comment by y3ll0wlife** [comment]
❤️ 🦀 ❤️

**Comment by piedoom** [comment]
❤️ 🦀 ❤️

**Comment by not-matthias** [comment]
❤️🦀❤️

**Comment by cr0wg4n** [comment]
🦀❤️

**Comment by couleurm** [comment]
wouldve sucked if you prepared this message only for you not getting the 100kth, happy you did though

**Comment by meisme-dev** [comment]
❤️ 🦀 ❤️

**Comment by jijothic** [comment]
❤️ 🦀 ❤️

**Comment by betseg** [comment]
notabug wontfix

**Comment by Kvicii** [comment]
❤️ 🦀 ❤️

**Comment by 0atman** [comment]
I had someone tell me this about their experience with Rust, and it was so beautiful I made it into a video :heart_on_fire:  https://www.youtube.com/watch?v=ZFDqh3slQfU

**Comment by Omar-Belghaouti** [comment]
So is this issue gonna be fixed or what?

**Comment by michaelgrigoryan25** [comment]
Much love to Rust from Armenia 🇦🇲💖🦀

![rust goes brr](https://user-images.githubusercontent.com/56165400/183494124-44f238cc-7700-4e17-87fd-5b2b62ac911b.png)

( sorry for my design skills :-) )

**Comment by ImajinDevon** [comment]
🦀🦀🦀

**Comment by Mathspy** [comment]
It's been more than a week, closing this now to remove clutter from issue tracker, but feel free to keep posting your messages of appreciation for the community! ❤️ 

Until #200000 and beyond ❤️

**Comment by selectiveduplicate** [comment]
To be honest, it took me three attempts to get "into" Rust. Third time was the charm, and I'm still having so much fun learning and writing it (not professionally, but hopefully, that day will come, hopefully...).

Rust got me into systems programming, and I still can't believe I was able to build my first "significant' project in it. I also managed to contribute to This Week in Rust a bit. It was all because of this wonderfully welcoming and inclusive community, the friendly feedback from the compiler, and many other things in between and around Rust.

So thank you. I appreciate you all. ✨

**Comment by schmaenjael** [comment]
:heart: :crab: :heart:

**Comment by griffi-gh** [comment]
Love this community, Hi from Ukraine!

**Comment by plazmoid** [comment]
Love this community, hi from Russia!

**Comment by meisme-dev** [comment]
Love this community, hi from Egypt!

**Comment by HZzz2** [comment]
🦀🦀🦀

**Comment by leo848** [comment]
🏳️‍🌈❤️🦀❤️🏳️‍🌈

**Comment by Sporky073189ImSpecial** [comment]
Meh email ***@***.***

**Comment by Sporky073189ImSpecial** [comment]
huh?

**Comment by Staninna** [comment]
❤️🦀❤️

**Comment by anas-elgarhy** [comment]
:heart::crab::heart:

**Comment by arihantbansal** [comment]
♥️🦀♥️

**Comment by albertlarsan68** [comment]
❤️ 🦀 ❤️ 🇫🇷

**Comment by Filip-Tomasko** [comment]
I recently had to start doing some stuff with C++ due to uni, and it made more appreciate Rust so much more. Thanks, Rust <3

**Comment by vKxni** [comment]
Its not bad, tho elixir is the on top of concurrency ;)

**Comment by alexey-milovidov** [comment]
This appeared to be the most loved issue on GitHub: https://twitter.com/tylerhannan/status/1625544709262262304

**Comment by TheBotlyNoob** [comment]
:crab::heart::crab:

**Comment by KittyBorgX** [comment]
🦀❤️🦀

**Comment by omdxp** [comment]
Rust Foundation is not Beautiful

**Comment by ArhanChaudhary** [comment]
<img width="759" alt="paint" src="https://github.com/rust-lang/rust/assets/57512390/c10e91a0-87ce-458e-8449-90246096fc52">
