### ISSUE TITLE
rustdoc "* -> vec" (documented example for search in type signature) yields error

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#100078]
In its help, rustdoc says I can use "* -> vec" to search by type signature. But when I actually run exactly that search query, rustdoc [says](https://doc.rust-lang.org/nightly/std/?search=*%20-%3E%20vec)

> Query parser error: "Unexpected `*`".

Cc @rust-lang/rustdoc

**Comment by camelid** [comment]
Hmm, I think it uses the syntax `-> vec` instead (though we've discussed switching to `* -> vec`, which I prefer). I'll open a PR.

cc @GuillaumeGomez

**Comment by RalfJung** [comment]
Yeah `-> vec` works.

This looks like a fairly recent regression, [it still works in 1.61](https://doc.rust-lang.org/1.61.0/std/?search=*%20-%3E%20vec).

**Comment by camelid** [comment]
It could be that the old query parser just ignored the `*`. A new one was implemented recently that's strict about syntax.
