### ISSUE TITLE
treat intrinsics entirely as an implementation detail of specialized modules

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#10008]
Exposing all of the intrinsics in one module is much more convenient than ad hoc `extern` blocks all over the standard library, but is very annoying for users of low-level Rust. It would be much nicer to treat intrinsics as part of the library API, and expose them in relevant modules. The fact that the API may be an intrinsic and not a library defined function is an implementation detail. Safe intrinsics should not be exposed as both an `unsafe` function and a safe wrapper.

Example: https://github.com/thestinger/rust-core/blob/master/core/f64.rs

**Comment by brson** [comment]
Intrinsics are feature gated, the intrinsics module is unstable with no current plans to stabilize. I believe the current situation is fine.
