### ISSUE TITLE
Stable Rust erroneously suggests GAT to fix missing lifetime in associated type

### ISSUE THREAD

**Issue by jdahlstrom** [rust-lang/rust#100027]
Given the following code ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=90a31f5f0c164d4a9e03e7d99c0fac2f)):

```rust
trait Foo {
    type Bar;
}

struct Baz;

impl Foo for Baz {
    type Bar = &i32;
}

```

The output on stable 1.62.1 is:

```
error[E0106]: missing lifetime specifier
 --> src/lib.rs:8:16
  |
8 |     type Bar = &i32;
  |                ^ expected named lifetime parameter
  |
help: consider introducing a named lifetime parameter
  |
8 |     type Bar<'a> = &'a i32;
  |             ++++    ++
```

If I do what the compiler says, I (reasonably) get 

```
error[E0658]: generic associated types are unstable
```

and

```
error[E0195]: lifetime parameters or bounds on type `Bar` do not match the trait declaration
```

Interestingly, on nightly the error message is more along the lines of what I'd expect to see on stable:

```
error[E0637]: `&` without an explicit lifetime name cannot be used here
 --> src/lib.rs:8:16
  |
8 |     type Bar = &i32;
  |                ^ explicit lifetime name needed here
```

Based on a quick bisect on rust.godbolt.org, the hint to add a lifetime parameter (a regression) was introduced in 1.42.

**Comment by jdahlstrom** [comment]
Looks like a semi-duplicate of #75547, feel free to close in that case.

**Comment by fmease** [comment]
Triage: Current output:

```
error: in the trait associated type is declared without lifetime parameters, so using a borrowed type for them requires that lifetime to come from the implemented type
 --> src/lib.rs:8:16
  |
8 |     type Bar = &i32;
  |                ^ this lifetime must come from the implemented type
```

We have a test for this already: `tests/ui/impl-header-lifetime-elision/assoc-type.rs`.

Closing as fixed.
