### ISSUE TITLE
For const variable declaration, if type is left dangling, also suggest type

### ISSUE THREAD

**Issue by Rageking8** [rust-lang/rust#100146]
Given the following code:

```rust
fn main() {
    const b: = 123;
}
```

The current output is:

```
   Compiling playground v0.0.1 (/playground)
error: expected type, found `=`
 --> src/main.rs:2:14
  |
2 |     const b: = 123;
  |              ^ expected type

error: could not compile `playground` due to previous error
```

Since the compiler suggests the type needed for the following:

```rust
fn main() {
    const b = 123;
}
```
```
   Compiling playground v0.0.1 (/playground)
error: missing type for `const` item
 --> src/main.rs:2:11
  |
2 |     const b = 123;
  |           ^ help: provide a type for the constant: `b: i32`

error: could not compile `playground` due to previous error
```

The output ideally should also suggest the type if its left dangling.

**Comment by compiler-errors** [comment]
cc @WaffleLapkin who knows how to do this since he worked on that `typeof` PR i think

**Comment by WaffleLapkin** [comment]
> The output ideally should also suggest the type if its left dangling.

@Rageking8 what you've meant by a type that's left dangling?

**Comment by Rageking8** [comment]
Basically just that the colon is included but no type is specified

**Comment by chenyukang** [comment]
This is because if we have colon, the parser will try to parse a type, then error will trigger.
If we don't have colon, parser will try to insert a place hold:

```rust
const a = 123
=>
const a: _ = 123
```
Then type checker will enrich the type messages.

**Comment by chenyukang** [comment]
@WaffleLapkin 
I have a branch in local could fix this issue.
But it also break another testcase with wrong syntax, but I think this testcase is far from normal one.
Do you mind I send a PR for this?

**Comment by WaffleLapkin** [comment]
@chenyukang oh, I've had a fix too, oops 😅 

I've opened a PR already: https://github.com/rust-lang/rust/pull/100168, but feel free to open a PR as well, if you think your approach might be better.

**Comment by chenyukang** [comment]
> @chenyukang oh, I've had a fix too, oops 😅
> 
> I've opened a PR already: #100168, but feel free to open a PR as well, if you think your approach might be better.

My fix is shorter, but seems a little bit hacky 😁
FYI: https://github.com/chenyukang/rust/commit/344042927bef524ee87d34a9f625593cc9c1aaac
