### ISSUE TITLE
Suggest invalid expression when use `public`

### ISSUE THREAD

**Issue by TheAwiteb** [rust-lang/rust#100165]
When writing `public let some = 3;` it will suggest `pub let some = 3;` and I think nothing should be suggested before it is validated.
> Note: 
The statement to be suggested must be checked if it is true or not, if true it is suggested and if not it is not.

The issue from: https://github.com/rust-lang/rust/pull/99903

[Given the following code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021):

```rust
fn main() {
    public let some = 3;
}
```

The current output is:

```
   Compiling playground v0.0.1 (/playground)
error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found keyword `let`
 --> src/main.rs:2:12
  |
2 |     public let some = 3;
  |            ^^^ expected one of 8 possible tokens
  |
help: write `pub` instead of `public` to make the item public
  |
2 |     pub let some = 3;
  |     ~~~

error: could not compile `playground` due to previous error
```

Ideally the output should look like:

```
   Compiling playground v0.0.1 (/playground)
error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found keyword `let`
 --> src/main.rs:2:12
  |
2 |     public let some = 3;
  |            ^^^ expected one of 8 possible tokens

error: could not compile `playground` due to previous error
```

**Comment by gimbles** [comment]
Oh dear, I didn't think of that while making the PR. 😅

A possible solution could be checking if the current token is for initializing an item? Like, struct/enum/macro, etc.

**Comment by TheAwiteb** [comment]
> A possible solution could be checking if the current token is for initializing an item? Like, struct/enum/macro, etc.

I wrote this solution, but I don't know if I can use it in rust It is currently building 😁

```rust
let is_valid_stmt: bool = syn::parse_str::<syn::Stmt>("pub let some = 3;")
    .is_ok(); // false
```

**Comment by TheAwiteb** [comment]
I can't work on the problem unfortunately, whoever will assign it to him you can solve it this way

```rust
can_be_public = ["enum", "struct", "fn", "extern", "trait"];
if can_be_public.contains(&self.token.as_str()) {
    // ...
}
```

The block
https://github.com/rust-lang/rust/blob/affe0d3a00e92fa7885e3f5d2c5073fde432d154/compiler/rustc_parse/src/parser/diagnostics.rs#L605-L614

**Comment by chenyukang** [comment]
Trying to add a method in token:

```rust
    /// Returns `true` if the token the start of a item 
    pub fn can_begin_item(&self) -> bool {
        self.is_keyword(kw::Use)
        || self.is_keyword(kw::Fn)
        || self.is_keyword(kw::Extern)
        || self.is_keyword(kw::Crate)
        || self.is_keyword(kw::Mod)
        || self.is_keyword(kw::Const)
        || self.is_keyword(kw::Static)
        || self.is_keyword(kw::Trait)
        || self.is_keyword(kw::Impl)
        || self.is_keyword(kw::Mod)
        || self.is_keyword(kw::Type)
        || self.is_keyword(kw::Enum)
        || self.is_keyword(kw::Struct)
        || self.is_keyword(kw::Union)
    }

```

And add a check:
```rust
 if self.prev_token.is_ident_named(sym::public) && self.token.can_begin_item() {
            err.span_suggestion_short(
                self.prev_token.span,
                "write `pub` instead of `public` to make the item public",
                "pub",
                appl,
            );
        }
```

Any other better idea? @gimbles

**Comment by gimbles** [comment]
1. This could be the `macro` keyword, as well.
2. That looks *alright*, ideally the repeated block could be prevented using a macro? I'm afraid that might slightly overengineer it, though. 😂
