### ISSUE TITLE
Trait methods with bounds on `Self` are shown on types that do not fulfill those bounds

### ISSUE THREAD

**Issue by notriddle** [rust-lang/rust#100176]
### Location

https://doc.rust-lang.org/std/collections/hash_map/struct.Keys.html#method.rev

### Summary

Found in [this topic] on URLO.

It shows the method `Iterator::rev` on the page for `hash_map::Keys`. This is misleading, because you can't actually call that method, because `Keys: !DoubleEndedIterator`.

[this topic]: https://users.rust-lang.org/t/cannot-understand-this-error-hashmap-rev/79421/4?u=notriddle

**Comment by chenyukang** [comment]
The same issue with [partition_in_place](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.partition_in_place) and [rposition](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.rposition).

@notriddle do you know how to exclude these options from hash_map? I'm still digging with it, if hash_map has this kind of issue, other data structures maybe have similar kind of issue.

I think we need to check the trait bounds when generating the doc.

**Comment by compiler-errors** [comment]
For the record I was working on this, sorry for not claiming this... Anyways, let me know if you don't get around to this. Seems like you've claimed a few issues in the past hours @chenyukang.

**Comment by chenyukang** [comment]
> For the record I was working on this, sorry for not claiming this... Anyways, let me know if you don't get around to this, and I'll pick it back up 😸 . Seems like you've claimed a few issues in the past hours @chenyukang, so not sure which ones you've gotten started with.

I haven't started this one, released it, please go ahead.
It's funny and also helpful to learn some Rust internals, starting with some trivial fixes 😁

**Comment by compiler-errors** [comment]
Thank you @chenyukang. Sorry for the mistake, and I am excited for you to get involved more in the compiler :)

@rustbot claim

**Comment by compiler-errors** [comment]
This is a dupe of #80481

**Comment by compiler-errors** [comment]
Uh, sorry, actually not a dupe. That's impl level, this is method level. I think there were legitimate concerns with hiding whole impls in that other issue. Reopening this, andf I'll probably solve this first.
