### ISSUE TITLE
SSL error when using cargo add in WSL

### ISSUE THREAD

**Issue by Loga-Shanmugam** [rust-lang/rust#100133]
I am using rust in WSL 1. When I try to use cargo add <package name>, its throwing SSL certificate error. I am behind a corporate firewall, and I tried everything including specifying CA cert path. Below is my git config file.

![image](https://user-images.githubusercontent.com/63439362/182769208-0b0aaacd-47c3-4a30-b90f-3461f1288127.png)
 
Whenever I run cargo add its throwing the below error.

![image](https://user-images.githubusercontent.com/63439362/182769456-0cb7ee6a-82da-45f6-a1c6-2d787b955b71.png)

**However if I use " git clone  https://github.com/rust-lang/crates.io-index ", I am able to fetch crates.io-index file.**

Suggestions to fix this would be helpful. Thanks.

**Comment by clubby789** [comment]
This issue should probably be moved to the Cargo repo

**Comment by jyn514** [comment]
I'm going to close this — libgit doesn't behave exactly the same way as `git` would (https://github.com/rust-lang/cargo/issues/636), but the diagnostic suggests a correct workaround.
