### ISSUE TITLE
RUST_LOG environment variable isn't read

### ISSUE THREAD

**Issue by lxk1170** [rust-lang/rust#100145]
I tried this:

```shell
> RUST_LOG=space_trucker=debug && cargo run --profile=dev --features bevy/dynamic
```

I expected to see the same output as:
```shell
> RUST_LOG=space_trucker=debug cargo run --profile=dev --features bevy/dynamic
...
2022-08-04T14:51:20.824031Z DEBUG space_trucker::planets: attracting
2022-08-04T14:51:20.824034Z DEBUG space_trucker::planets: attracting
2022-08-04T14:51:20.824036Z DEBUG space_trucker::planets: attracting
2022-08-04T14:51:20.824039Z DEBUG space_trucker::planets: attracting
```
Instead I received no debug logs.

### Meta

`rustc --version --verbose`:
```
rustc 1.62.1 (e092d0b6b 2022-07-16)
binary: rustc
commit-hash: e092d0b6b43f2de967af0887873151bb1c0b18d3
commit-date: 2022-07-16
host: x86_64-apple-darwin
release: 1.62.1
LLVM version: 14.0.5
```

<p>
Accepting environment variables both ways is the standard these days.
</p>

**Comment by SNCPlay42** [comment]
>Accepting environment variables both ways is the standard these days. 

I don't know what you mean by this. With the `&&` in between, shells (or bash at least) simply don't pass the variable to external processes:

```
$ A=b bash -c 'echo ${A-not set}'
b
$ A=b && bash -c 'echo ${A-not set}'
not set
```

**Comment by RalfJung** [comment]
Yeah, that's just now how shells work, sorry.
```
VAR=val command
```
is syntax for "run this command with `VAR=val` in the environment.
But
```
VAR=val
command
```
means something completely different: it sets `VAR=val` as a *shell variable*, but that is by default *not* exported to the environment of programs invoked later. If that's what you want, you need to do
```
export VAR=val
command
```
