### ISSUE TITLE
Don't build Miri tool by default

### ISSUE THREAD

**Issue by Nilstrieb** [rust-lang/rust#100139]
When setting `extended = true` in the `config.toml`, bootstrap also builds all the tools, including Miri. Since Miri doesn't always build, this can cause problems like in #100134. There is another option to only build a set of tools using `tools = []` (this doesn't contain "miri" in the example form, which is a little odd, it should probably be added there as well).

`rust-demangler` is already excluded by default (unless profiling is enabled), so I think it would make sense to disable Miri by default as well (unless there's some good reason to not do it).

**Comment by RalfJung** [comment]
This is already implemented for stable/beta builds:

https://github.com/rust-lang/rust/blob/339509494dabe8c8df14b591cd8761c6ce8ddfe7/src/bootstrap/tool.rs#L807-L809

I guess we could extend this to *all* builds, but then I am not sure if CI would still build these tools.

**Comment by jyn514** [comment]
I don't think this is the right fix, see https://github.com/rust-lang/rust/issues/100134#issuecomment-1248179340.
