### ISSUE TITLE
Backtrace has no information on older Windows Server

### ISSUE THREAD

**Issue by albinocordeiro** [rust-lang/rust#100149]
I tried this code:

```rust
 panic!("TEST PANIC LOGGING");
```
And made sure RUST_BACKTRACE=1 in the environment.

I expected to see in the logs: "
 thread 'unnamed' panicked at 'TEST PANIC LOGGING':  ...src\some.rs:169
   0: [Relevant stack info here]
   1: [Relevant stack info here]
   2: [Relevant stack info here]
   3: [Relevant stack info here] ...
 "

Instead, the following shows on the logs: "
thread 'unnamed' panicked at 'TEST PANIC LOGGING': ...src\some.rs:169
   0: update
   1: update
   2: update
   3: update
   4: update
   5: update
   6: update
   7: update
   8: update
   9: update
  10: update
  11: update
  12: update
  13: update
  14: update
  15: update
  16: update
  17: update
  18: update
  19: update
  20: update
  21: update
  22: update
  23: update
  24: update
  25: BaseThreadInitThunk
  26: RtlUserThreadStart
"
NOTE: I don't see this issue on my Windows 10 Pro laptop, only on a work Windows Server 2016 on AWS.
### Meta

I had the exact same behavior with rust version 1.62.1 stable and version 1.64.0 nightly.

```
$ rustc --version --verbose
rustc 1.64.0-nightly (1b57946a4 2022-08-03)
binary: rustc
commit-hash: 1b57946a405d5b2a87e612335db033edb2c3427f
commit-date: 2022-08-03
host: x86_64-pc-windows-msvc
release: 1.64.0-nightly
LLVM version: 14.0.6

```

</p>
</details>

**Comment by albinocordeiro** [comment]
I'm sorry guys. It's not really an issue. I forgot to copy over the pdb file.

**Comment by wesleywiser** [comment]
Thanks for following up @albinocordeiro!
