### ISSUE TITLE
support async drop trait

### ISSUE THREAD

**Issue by b23r0** [rust-lang/rust#100280]
hope to support async drop soon

```rs
impl AsyncDrop for MyType {
    async fn drop(&mut self) {
        ...
    }
}
```

Specifically as described here

https://rust-lang.github.io/async-fundamentals-initiative/roadmap/async_drop.html

**Comment by compiler-errors** [comment]
Thanks for the issue, but until there's need for a tracking issue, I'm gonna close this. Feel free to message the async working group on Zulip if you'd like to know more how to get involved!
