### ISSUE TITLE
Universal function call syntax for `Vec::contains` does not work.

### ISSUE THREAD

**Issue by porky11** [rust-lang/rust#100227]
```rust
fn test() {
    let vec = Vec::new();
    vec.contains(&0); // works
    Vec::contains(&vec, &0); // doesn't work
}
```
### Meta

`rustc --version --verbose`:
```
rustc 1.62.1 (e092d0b6b 2022-07-16)
binary: rustc
commit-hash: e092d0b6b43f2de967af0887873151bb1c0b18d3
commit-date: 2022-07-16
host: x86_64-unknown-linux-gnu
release: 1.62.1
LLVM version: 14.0.5
```

**Comment by gimbles** [comment]
Can you elaborate on *how* it doesn't work?

**Comment by Nilstrieb** [comment]
`contains` is not a method on `Vec<T>`, but on slices. You can use method call syntax here because `.` goes through `Deref`, and `Vec<T>` derefs to `&[T]`.
https://doc.rust-lang.org/std/primitive.slice.html#method.contains

**Comment by Nilstrieb** [comment]
```rust
error[E0599]: no function or associated item named `contains` found for struct `Vec<_, _>` in the current scope
 --> src/lib.rs:4:10
  |
4 |     Vec::contains(&vec, &0); // doesn't work
  |          ^^^^^^^^ function or associated item not found in `Vec<_, _>`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `playground` due to previous error
```
But the error is definitely not good here and could be improved to say there the methods does exist on something that the type derefs to.

**Comment by porky11** [comment]
> `contains` is not a method on `Vec<T>`, but on slices.

You are right, I've been stupid

**Comment by Nilstrieb** [comment]
Would you like opening an issue for the diagnostic? A hint telling that the method exists on a deref.

**Comment by Nilstrieb** [comment]
I've opened an issue.
