### ISSUE TITLE
Get rid of the distinction between `method` and `function` in rustdoc JSON output

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#100259]
Rust has no concept of methods. Distinguishing between these makes no sense and is an artifact of how rustdoc represents these internally - consider for example the ambiguous case
```rust
pub struct Foo {}

impl Foo {
    pub fn bar() {}
}
``` 
We should remove this distinction before the format is stabilized.

cc @obi1kenobi @CraftSpider @camelid

**Comment by obi1kenobi** [comment]
The one thing I'd be careful about is consistency of terminology and intuition between the Rust book and rustdoc. [The Rust book mentions methods](https://doc.rust-lang.org/book/ch05-03-method-syntax.html) as a kind of associated function, even though this is merely a human-made distinction and is not observed at layers below "human reading the code."

I'm completely in favor of not distinguishing between them in rustdoc and having the `function` kind cover both. I'd just suggest that we make sure the rustdoc JSON docs prominently state that in the JSON output, there's no difference between methods, non-method associated functions, and free functions.

**Comment by jyn514** [comment]
> there's no difference between methods, non-method associated functions, and free functions.

I think we distinguish associated items by adding a `parent` field or something like that?

But yeah documenting that the `kind` is the same for all 3 seems fine.
