### ISSUE TITLE
Docs regression on crate teloxide-0.10.1

### ISSUE THREAD

**Issue by notriddle** [rust-lang/rust#100204]
# Behavior, describe in zulip thread

https://docs.rs/teloxide/0.10.1/teloxide/struct.Bot.html has an inherent impl block, but it is not shown. https://docs.rs/teloxide/0.10.0/teloxide/struct.Bot.html (which was built with an earlier version of rustdoc) shows it.

# Regression information

searched nightlies: from nightly-2022-08-03 to nightly-2022-08-04
regressed nightly: nightly-2022-08-04
searched commit range: https://github.com/rust-lang/rust/compare/4493a0f4724c0bae1436242d76cccc9c0a287b80...1b57946a405d5b2a87e612335db033edb2c3427f
regressed commit: https://github.com/rust-lang/rust/commit/7308c22c6a8d77e82187e290e1f7459870e48d12

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.4</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --prompt --script=/teloxide/run.sh --start=2022-08-03 --end=2022-08-04 --test-dir=/teloxide/ 
```

run.sh:

```bash
#!/bin/sh
cargo doc
```
</details>

**Comment by Mark-Simulacrum** [comment]
@notriddle it sounds like the regression here was introduced in https://github.com/rust-lang/rust/pull/99738, which was backported to 1.63 beta (releasing in <1 week). Is that right?

If so, I assume that we should review + backport #100207 into 1.63 and 1.64, correct?

**Comment by Mark-Simulacrum** [comment]
On the other hand, it looks like #99738 was a stable/stable regression, so it may make sense to back out the backport of that PR instead -- it makes me a little nervous that we already encountered one regression introduced by it (i.e., this issue); we don't have a lot of time for things to bake and get reviewed.

**Comment by inquisitivecrystal** [comment]
> On the other hand, it looks like #99738 was a stable/stable regression, so it may make sense to back out the backport of that PR instead -- it makes me a little nervous that we already encountered one regression introduced by it (i.e., this issue); we don't have a lot of time for things to bake and get reviewed.

I think the main question here is whether we'd rather have docs fail entirely, or have them build but be incorrect. Personally, I really don't like having *either* of those on stable, but I'm not sure what to do about it.
