### ISSUE TITLE
Bootstrap panics when running `x fmt --check`

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#100258]
I ran `x fmt --check` and got this panic, although the rustfmt output had already been printed:

```text
If you're running `tidy`, try again with `--bless`. Or, if you just want to format code, run `./x.py fmt` instead.
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'tx.send(entry.into_path()) failed with sending on a closed channeltx.send(entry.into_path()) failed with sending on a closed channel', ', format.rsformat.rs::166166::1717

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', /Users/noahlev/.cargo/registry/src/github.com-1ecc6299db9ec823/ignore-0.4.18/src/walk.rs:1302:31
Build completed unsuccessfully in 0:00:07
```

Notably after running `x fmt`, the panic stops (and `x fmt` doesn't panic either). But reintroducing something where rustfmt will suggest changes brings the panic in `--check` back.

*See previous discussion at [this Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/bootstrap.20panics.20with.20.60x.20fmt.20--check.60).*

cc @jyn514

**Comment by jyn514** [comment]
This is a regression from https://github.com/rust-lang/rust/pull/98994. `resume_unwind` only exits the process when run from the main thread.

**Comment by jyn514** [comment]
The fix is to use `process::exit` instead.

**Comment by shourya5** [comment]
So, to be clear, the fix is to replace the detail::exit with process::exit right?

**Comment by jyn514** [comment]
@shourya5 no - within detail_exit, change resume_unwind to process::exit
