### ISSUE TITLE
why Ipv4Addr::from_str("10.255.255.255").ok().unwrap().is_broadcast() is False?

### ISSUE THREAD

**Issue by kulame** [rust-lang/rust#100393]
i got a broadcast ip 10.255.255.255

and try to call is_broadcast. it return false.

why? I understand 10.255.255.255 is a broadcast address。

**Comment by compiler-errors** [comment]
The documentation of [`Ipv4Addr::is_broadcast`](https://doc.rust-lang.org/std/net/struct.Ipv4Addr.html#method.is_broadcast) clearly state:

> Returns [`true`](https://doc.rust-lang.org/std/primitive.bool.html) if this is a broadcast address (`255.255.255.255`).
>
> A broadcast address has all octets set to `255` as defined in [IETF RFC 919](https://tools.ietf.org/html/rfc919).

**Comment by wrexbe** [comment]
@compiler-errors No, that is a valid broadcast address

https://www.rfc-editor.org/rfc/rfc917
> 2.3. Subnets and Broadcasting
>
>       Physical network
>          A destination address of all ones (255.255.255.255) causes the
>          a datagram to be sent as a broadcast on the local physical
>          network; it must not be forwarded by any gateway.
>       Specific network
> 
>          The destination address contains a valid network number; the
>          local address part is all ones (e.g., 36.255.255.255).
> 
>       Specific subnet
> 
>          The destination address contains a valid network number and a
>          valid subnet number; the host field is all ones (e.g.,
>          36.40.255.255).

https://www.rfc-editor.org/rfc/rfc919
>
> The address 255.255.255.255 denotes a broadcast on a local hardware
>    network, which must not be forwarded.  This address may be used, for
>    example, by hosts that do not know their network number and are
>    asking some server for it.
> 
>    Thus, a host on net 36, for example, may:
> 
>       - broadcast to all of its immediate neighbors by using
>         255.255.255.255
> 
>       - broadcast to all of net 36 by using 36.255.255.255

**Comment by duskmoon314** [comment]
`Ipv4Addr` only has bits for address and there is no CIDR. Thus you can't judge whether an address like `1.2.3.255` is broadcast without providing CIDR.

You may find crates like [`ipnet`](https://crates.io/crates/ipnet) helpful.

In addition, should `std` provide a method like `is_broadcast(addr: Ipv4Addr, mask_len: u8) -> bool`?
