### ISSUE TITLE
`InferCtxt::tainted_by_errors_flag` should be `Option<ErrorGuaranteed>`

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#100321]
https://github.com/rust-lang/rust/blob/5af97e8b0b9649ed14b0b4528a610ff841b6365e/compiler/rustc_infer/src/infer/mod.rs#L319

should be `Cell<Option<ErrorGuaranteed>>` to guarantee that we emit an error when that flag is set. This is already done for `tainted_by_errors` of other types in rustc. https://github.com/rust-lang/rust/blob/5af97e8b0b9649ed14b0b4528a610ff841b6365e/compiler/rustc_middle/src/ty/context.rs#L537

**Comment by chenyukang** [comment]
`tainted_by_errors_flag` renamed to `tainted_by_errors` to keep consistent.
