### ISSUE TITLE
'Free regions in optimized MIR' ICE with const generics

### ISSUE THREAD

**Issue by b-naber** [rust-lang/rust#100360]
The following throws a 'Free regions in optimized MIR' ICE on master:

### Code

```Rust
#![feature(adt_const_params)]
#![feature(generic_const_exprs)]

fn foo<const B: &'static bool>(arg: &'static bool) -> bool {
  B == arg 
}

fn main() {
  foo::<{&true}>(&false);
}
```
[backtrace.txt](https://github.com/rust-lang/rust/files/9298157/backtrace.txt)

**Comment by matthiaskrgr** [comment]
could be related to https://github.com/rust-lang/rust/issues/89851
