### ISSUE TITLE
No error on cfg as InnerAttribute

### ISSUE THREAD

**Issue by zommiommy** [rust-lang/rust#100333]
Hi!
I erroneously wrote a `cfg` attribute as an inner attribute `#![` instead of an outer attribute `#[`.

Here's a simplified example working example:
```rust
#![no_std]

#[cfg(feature="alloc")]
use core::*;

pub fn square(num: i32) -> i32 {
    num * num
}
```
and here the **problematic** example:
```rust
#![no_std]

#![cfg(feature="alloc")] // <----
use core::*;

pub fn square(num: i32) -> i32 {
    num * num
}
```
This code still compiles but the function `square` won't be present in the final binary.

Even weirder, if I cross-compile it to a target that doesn't support `std` it seems to ignore the `#![no_std]:
`cargo check --target=nvptx64-nvidia-cuda`:
```
error[E0463]: can't find crate for `std`
  |
  = note: the `nvptx64-nvidia-cuda` target may not support the standard library
  = note: `std` is required by `<unknown>` because it does not declare `#![no_std]`

error: aborting due to previous error
```

### Meta
`rustc --version --verbose`:
```
rustc 1.65.0-nightly (f03ce3096 2022-08-08)
binary: rustc
commit-hash: f03ce30962cf1b2a5158667eabae8bf6e8d1cb03
commit-date: 2022-08-08
host: x86_64-unknown-linux-gnu
release: 1.65.0-nightly
LLVM version: 14.0.6
```

Thank you for your work! And thanks to @Soveu for helping debugging this Issue.

**Comment by jyn514** [comment]
The cross compiling bit is weird, but the first half is not a bug - `#!` means the attribute belongs to the entire crate. Since the `alloc` feature isn't enabled, that means your crate is just an empty crate.

**Comment by zommiommy** [comment]
Ok, thank you! This makes sense. Sorry!
