### ISSUE TITLE
A simple guide to choosing an appropriate data structure from the stdlib

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#10033]
I ran across this guide to selecting a container from the types offered in C++'s STL:
![hnmy4](https://f.cloud.github.com/assets/865233/1390879/56d06fe0-3bf4-11e3-88f8-a2a05e27109c.png)
Something similar might be useful for navigating Rust's std and extra containers (though it doesn't necessarily need to be an image).

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#780
