### ISSUE TITLE
`rustc` hangs on a recursive function marked with `#[inline]`

### ISSUE THREAD

**Issue by yvt** [rust-lang/rust#100476]
I tried this code with `-Copt-level=3 --crate-type=lib` ([Playground](https://play.rust-lang.org/?version=nightly&mode=release&edition=2021&gist=2da6beb75894a4b1d224fda02cc7044a), [Godbolt](https://rust.godbolt.org/z/zdonjbaMz); minimized and modified from `r3_core`'s [failing code](https://github.com/r3-os/r3/blob/588c1bc35d04711137016956e0539faf2531d8bb/src/r3_core/src/utils/for_times.rs#L157-L177)):

```rust
#![feature(decl_macro)]

macro emit($($m:ident)*) {$(
    // Randomize `def_path_hash` by defining them under a module with
    // different names
    pub mod $m {
        pub trait Tr {
            type Next: Tr;
        }

        pub fn hoge<const N: usize, T: Tr>() {
            inner::<N, T>();
        }

        #[inline(always)]
        fn inner<const N: usize, T: Tr>() {
            inner::<N, T::Next>();
        }
    }
)*}

// Increase the chance of triggering the bug
emit!(
    m00 m01 m02 m03 m04 m05 m06 m07 m08 m09
    m10 m11 m12 m13 m14 m15 m16 m17 m18 m19
);
```

I expected to see this happen: Successful compilation

Instead, this happened: Compiler hangup

### Meta

`rustc --version --verbose`:
```
rustc 1.64.0-nightly (f8588549c 2022-07-18)
binary: rustc
commit-hash: f8588549c3c3d45c32b404210cada01e2a45def3
commit-date: 2022-07-18
host: aarch64-apple-darwin
release: 1.64.0-nightly
LLVM version: 14.0.6
```

<details><summary>Backtrace</summary>
<p>

Captured by a `backtrace` command in GDB: [`gdb.txt`](https://gist.github.com/yvt/ba86ff545b831fac3ef93eda74887b8c)

</p>
</details>

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23100476.20.60rustc.60.20hangs.20on.20a.20recursive.20function.20marked.20with.20.60.E2.80.A6)).

@rustbot label -I-prioritize +P-medium
