### ISSUE TITLE
portable_simd: gather_or_default compile-time error: "failed to parse bitcode for LTO module", opt-level > 0

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#100474]
I tried this code:

```rust
#![feature(portable_simd)]

use std::simd::{f32x8, usizex8};

pub fn table_lookup_exclusive_x16() {
    let table = &[0.0];
    let table_idx1 = usizex8::splat(0);

    let _sample1 = f32x8::gather_or_default(table, table_idx1);
    todo!()
}
```

Command line:

```
$ rustc lib.rs --crate-type lib -C opt-level=1
error: failed to parse bitcode for LTO module: Explicit gep type does not match pointee type of pointer operand (Producer: 'LLVM14.0.6-rust-1.65.0-nightly' Reader: 'LLVM 14.0.6-rust-1.65.0-nightly')

error: aborting due to previous error
```

I expected to see this happen: compilation succeed

Instead, this happened: the above error

`opt-level=1` or greater is required. Strangely, in this reduced case the `todo!()` is required, though in my non-reduced case I had other code there. Compiling as a lib is required - compiling as a bin succeeds.

### Meta

`rustc --version --verbose`:
```
$ rustc --version --verbose
rustc 1.65.0-nightly (f03ce3096 2022-08-08)
binary: rustc
commit-hash: f03ce30962cf1b2a5158667eabae8bf6e8d1cb03
commit-date: 2022-08-08
host: x86_64-unknown-linux-gnu
release: 1.65.0-nightly
LLVM version: 14.0.6
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace> n/a
```

</p>
</details>

**Comment by nikic** [comment]
Can't reproduce this on current nightly, probably fixed by the LLVM 15 upgrade. Can you still reproduce this?

**Comment by brson** [comment]
Cannot reproduce this on a recent nightly.
