### ISSUE TITLE
async blocks can't forward references

### ISSUE THREAD

**Issue by yancouto** [rust-lang/rust#100406]
This is the most minimal repro I could find for this issue:

```rust
use std::future::Future;
struct X;

fn repro(x: &X) -> impl Future<Output=&X> {
    async { x }
}
```

It fails to compile with the following reason: `async block may outlive the current function, but it borrows x, which is owned by the current function`

However, it should just work, and if instead I change `async { x }` to `async { &*x }` it does work, due to which I suspect Rust is extending the lifetime of the reference.

I know in this case I could fix it in a bunch of different ways, making the function `async`, using `async move`, etc., but it's still a bug, and this is a very minimal repro from which I stripped most complexity.

A small repro a bit more similar to the real case is:

```rust
use futures::*;
struct X;
struct Y;

impl Y {
    async fn fake_process(&self, _x: &X) {} 
}

async fn processed(x: Vec<&X>, y: Y) -> Vec<&X> {
    stream::iter(x).map(|x| async {
        y.fake_process(x).await;
        x
    }).buffered(3).collect().await
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.60.0-nightly (30b3f35c4 2022-02-17)
```

I can repro this issue on rust playground with stable and nightly versions.

**Comment by ChayimFriedman2** [comment]
I think this is the same as #100905 (posted later but using closures which is more common) because if I wrap the reference with non-`Copy` type it works: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a0a7e267aeaedf3089b1f4fc61b29abd.

**Comment by traviscross** [comment]
@rustbot labels +AsyncAwait-Triaged +WG-async

We reviewed this today in WG-async triage.

We agree this is a manifestation of #100905.  Let's close this and track it there.
