### ISSUE TITLE
Cannot mutate the value inside a `Mutex` created in a `const` context

### ISSUE THREAD

**Issue by orium** [rust-lang/rust#100417]
Hi.  I was trying the new `Mutex::new()` in `const` a context ([new in rust 1.63](https://blog.rust-lang.org/2022/08/11/Rust-1.63.0.html#const-mutex-rwlock-condvar-initialization)) and I'm able to mutate it's value:

I tried this code:

```rust
use std::sync::Mutex;

const VAR: Mutex<usize> = Mutex::new(0);

fn main() {
    println!("var: {}", *VAR.lock().unwrap());
    *VAR.lock().unwrap() = 3;
    println!("var: {}", *VAR.lock().unwrap());
}
```

The output is 

```text
var: 0
var: 0
```

Playground link [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9c3bd23c8c702a8fe6376a32ef43d2bb).

**Comment by andjo403** [comment]
The problem is that you try to mutate a const this creates a temporary that you mutate, if you change const to static you get the expected result.
cc https://github.com/rust-lang/rust/issues/40543

**Comment by orium** [comment]
Closing since this is the expected behavior: https://www.reddit.com/r/rust/comments/wltcf8/comment/ijvx9ym/?context=3

**Comment by riking** [comment]
Diagnostics part of issue is covered in #40543
