### ISSUE TITLE
RFC: `str` methods that accept/return byte offsets should have `byte` in the name

### ISSUE THREAD

**Issue by ben0x539** [rust-lang/rust#10044]
People shouldn't accidentally write code that works only for ascii input and 'surprisingly' fails when users input non-ascii-only text, so I figure the byte-offset methods shouldn't have the shorter names or be the more obvious choice than the char-offset methods.

So, like, `len` => `byte_len`, `slice` => `slice_bytes`,  but also `find` => `find_byte_pos` or something.

Of course all the docs already mention that offsets are given in bytes, but it doesn't always occur to me that I might even be passing the wrong kind of offset to make me look it up in the first place.

**Comment by steveklabnik** [comment]
This thread isn't the place to track this kind of thing today. Many of these methods have already undergone stabilization, and for those that haven't, that's the correct place. So I'm giving this a close. If anyone still feels strongly about this, please persue in the RFCs repo, thanks.
