### ISSUE TITLE
regression: can't compare `X` with `_` in const contexts

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#100543]
Found in [crater](https://crater-reports.s3.amazonaws.com/beta-1.64-2/index.html):

* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/gh/aharisu.navi/log.txt
   * Looking briefly into the code it's doing something pretty weird (e.g., transmutes [here](https://github.com/aharisu/navi/blob/38558dc0bb326124e273ff73d87f43f970dc4f62/src/value.rs#L11)), but at the very least this diagnostic seems unfortunate.

**Comment by compiler-errors** [comment]
searched nightlies: from nightly-2022-04-01 to nightly-2022-08-11
regressed nightly: nightly-2022-07-28
searched commit range: https://github.com/rust-lang/rust/compare/4d6d601c8a83284d6b23c253a3e2a060fd197316...2643b16468fda787470340890212591d8bc832b7
regressed commit: https://github.com/rust-lang/rust/commit/2a220937c283803bfd5d1155e4a81e6287089504

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.3</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start=2022-04-01 -- build 
```
</details>

This regressed in #99704 cc @fee1-dead

**Comment by compiler-errors** [comment]
Maybe "regressed" is better here, maybe it's a legitimate reason to fail. Haven't looked into it.

**Comment by fee1-dead** [comment]
I'm going to look into this later, but it seems like a case of wf checks requiring const bounds.

**Comment by fee1-dead** [comment]
Repro:

```rust
#[derive(PartialEq)]
struct S;

const FOO: fn(&S, &S) -> bool = S::eq;
```

**Comment by apiraino** [comment]
Just to be sure I understood: is the regression about code that should compile in the next Rust 1.64 or is that code now invalid code and the regression is just a bad diagnostic? thanks!

**Comment by fee1-dead** [comment]
@apiraino The code is valid. It should compile in the next Rust 1.64. Hope that helps.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23100543.20regression.3A.20can't.20compare.20.60X.60.20with.20.60_.60.20in.20const.20con.E2.80.A6)).

@rustbot label -I-prioritize +P-medium
