### ISSUE TITLE
regression: ICE -- no type for node

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#100541]
Picked up in [crater](https://crater-reports.s3.amazonaws.com/beta-1.64-2/index.html):

* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/reg/hdk_crud-0.5.6/log.txt
  * This crate already failed to compile in [1.63.0](https://crater-reports.s3.amazonaws.com/beta-1.64-2/1.63.0/reg/hdk_crud-0.5.6/log.txt), but now is ICE'ing (search for "internal compiler error" in the log above).

**Comment by compiler-errors** [comment]
This is fixed by #100155

**Comment by compiler-errors** [comment]
Should I backport that? Or is the fact that the code failed to compile not enough to warrant nominating it?

**Comment by Mark-Simulacrum** [comment]
I think given that we have only 1 case detected by Crater a backport doesn't seem necessary, but it's also a small PR. No strong opinion.

**Comment by compiler-errors** [comment]
I'll do it. It's very possible that people can trigger it while doing a refactor, for example.

**Comment by Mark-Simulacrum** [comment]
Yeah, I think I saw a few more cases as well (outside of just this one root regression according to Crater).

**Comment by pietroalbini** [comment]
Fix backported.
