### ISSUE TITLE
regression: delayed good path bug: trimmed_def_paths constructed

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#100542]
Picked up in [crater](https://crater-reports.s3.amazonaws.com/beta-1.64-2/index.html):

* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/gh/L1LLIAN.shorty-backend/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/gh/Niakr1s.rust_tree/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/gh/iiian.hundert/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/gh/jessaimaya.100_days_of_mogwai/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/reg/grep-index-0.0.1/log.txt

**Comment by compiler-errors** [comment]
I'm pretty certain this fixed by #99893

**Comment by compiler-errors** [comment]
I'll open a backport PR for this and nominate it

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23100542.20regression.3A.20delayed.20good.20path.20bug.3A.20trimmed_def_path.E2.80.A6)).

@rustbot label -I-prioritize +P-medium

**Comment by pietroalbini** [comment]
Fix backported.
