### ISSUE TITLE
Rust ABI is not the C ABI

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#10052]
Having a well-defined ABI is probably important eventually. Right now it's nice to think the Rust ABI is just the C ABI but it is actually not since LLVM's cdecl does not implement the complete platform-specific rules for the C ABI. If we wanted to actually define the Rust ABI as the C ABI then we would need to run our code generation through the same code paths as our native function bindings.

**Comment by steveklabnik** [comment]
Given that this would be an RFC-worthy topic these days, closing in favor of https://github.com/rust-lang/rfcs/issues/600
