### ISSUE TITLE
regression: socket type changes

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#100551]
Filing this mostly so that we're aware of scope of impact per [Crater](https://crater-reports.s3.amazonaws.com/beta-1.64-2/index.html) run and can potentially use this as a landing ground for complaints/concerns (probably should have *some* issue for that even if not this one, maybe pinned). The scope of impact is pretty depressing, but I don't think the decision by libs-api will change since this isn't new data, so we'll need to clearly communicate it (I believe already planned into release post + notes). It seems likely that we might want to invest in mechanisms to stop future breakage like this (e.g., more strict linting/errors on transmutes of std types).

introduced by PR #78802

Root (compilation) regressions:

* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/reg/ringbahn-0.0.0-experimental.3/log.txt
  * experimental crate, seems OK
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/reg/ruyi-0.1.6/log.txt
  * no reverse dependencies on crates.io, 5 years old, no patch release
* socket2
  * 0.2.4 - 3 regressions -- **no 0.2.5 released yet**
  * 0.3.x - 0.3.16 has the fix, so cargo update should be sufficient
    * 0.3.1 - 3
    * 0.3.3 - 3
    * 0.3.4 - 3
    * 0.3.5 - 4
    * 0.3.6 - 3
    * 0.3.7 - 21
    * 0.3.8 - 300
    * 0.3.9 - 127
    * 0.3.10 - 19
    * 0.3.11 - 592
    * 0.3.12 - 1259
    * 0.3.15 - 492

Test failures, which are *probably* caused by broken pointer casting in older tokio/mio/etc (haven't chased down specifically though), leading to InvalidInput / invalid argument from the kernel:

* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/gh/abbec.raccoon/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/gh/DevinR528.rust_load_balance/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/gh/bittrd.feo/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/gh/cryptobioz.dyn-livedns-gandi/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/gh/d1vyank.dht_kad_rs/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/gh/dwerner.chat-mio/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/gh/flatcar-linux.coreos-metadata/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/gh/infinyon.fluvio-socket/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/gh/j-keck.sonoff-diy/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/gh/markpritchard.khonsu/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/gh/mizukmb.esa-nippou/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/gh/mkroman.scaleway-registry-prune/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/gh/nihn.eurostartrainfinder/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/gh/photoszzt.cache_server/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/gh/rchaser53.yu/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/gh/rolftimmermans.rmq/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/gh/ssundarr3.simple-torrent/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/gh/wayofthepie.gram/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/reg/clobber-0.3.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/reg/eventsource-0.5.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/reg/fibers-0.1.13/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/reg/fibers_http_server-0.2.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/reg/fibers_rpc-0.3.4/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/reg/kiteconnect-0.2.9/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/reg/libicmp-0.1.2/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/reg/redelete-0.3.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/reg/reqwest_mock-0.7.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/reg/romio-0.3.0-alpha.10/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/reg/runeterra-game-api-0.1.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.64-2/beta-2022-08-09/reg/trello-rs-1.23.0/log.txt

**Comment by estebank** [comment]
Have we looped in the tokio/mio people already?

**Comment by Mark-Simulacrum** [comment]
I think this is all from old versions and yes, but it seems like a good idea to re-check-in, especially since bug reports directed at them aren't implausible.

**Comment by joshtriplett** [comment]
We've discussed this pretty extensively in libs-api, and we're comfortable with this change; we do need a release note here, though.

**Comment by the8472** [comment]
The PR is appropriately labeled.
