### ISSUE TITLE
Build failure with `rustc_private` crates on `aarch64-unknown-linux-gnu`

### ISSUE THREAD

**Issue by Alexendoo** [rust-lang/rust#100530]
On `aarch64-unknown-linux-gnu`, with a `rustup` provided `rustc-dev` component:

```rust
#![feature(rustc_private)]

extern crate rustc_attr;
```

errors with:

```
error: /home/alex/.rustup/toolchains/nightly-2022-08-14-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libserde_derive-6dc9fea9ed4dba80.so: cannot allocate memory in static TLS block
 --> src/lib.rs:3:1
  |
3 | extern crate rustc_attr;
  | ^^^^^^^^^^^^^^^^^^^^^^^^
```

I'll try and see if I can reproduce it with `./x.py` to test @bjorn3's suggestion: https://github.com/rust-lang/rust/pull/99944#issuecomment-1214361900

**Comment by Alexendoo** [comment]
Couldn't reproduce it with an `./x build --stage 2`,  tried with `download-ci-llvm = false` also

Does it have to be cross compiled from a different host?

**Comment by bjorn3** [comment]
Not sure what is necessary to reproduce it. In any case if you open a PR with the likely fix, I can run a try build on CI which you can then locally install to see if it fixes the issue.
