### ISSUE TITLE
`Ipv4Addr` hash regression in beta 1.64.0 and nightly

### ISSUE THREAD

**Issue by marmeladema** [rust-lang/rust#100623]
### Code

I tried this code:

```rust
use fnv::FnvHasher;
use std::hash::{Hash, Hasher};
use std::net::{IpAddr, Ipv4Addr};

fn main() {
    fn hash<T: Hash>(value: T) -> u64 {
        let mut hasher = FnvHasher::default();
        value.hash(&mut hasher);
        hasher.finish()
    }

    assert_eq!(
        hash(IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1))),
        8404365059945483277,
    );
}
```
It uses `fnv` crate version `1.0.7` but the issue should not be related to the hashing algorithm itself.

I expected to see this happen: the assertion should succeed

Instead, this happened: the assertion fails because the hash has changed value to `4241519267947859505`

### Version it worked on

It most recently worked on: Rust 1.63.0
But also worked fine prior versions like 1.62.0, 1.61.0 (haven't tested more versions)

### Version with regression

`rustc --version --verbose`:
```
rustc 1.64.0-beta.2 (fb2194acc 2022-08-14)
binary: rustc
commit-hash: fb2194acc4ee897e2e987c79fd58b263bb32db9c
commit-date: 2022-08-14
host: x86_64-unknown-linux-gnu
release: 1.64.0-beta.2
LLVM version: 14.0.6
```

@rustbot modify labels: +regression-from-stable-to-beta +regression-from-stable-to-nightly -regression-untriaged

**Comment by marmeladema** [comment]
Minimized a bit more:
```
use fnv::FnvHasher;
use std::hash::{Hash, Hasher};
use std::net::Ipv4Addr;

fn main() {
    fn hash<T: Hash>(value: T) -> u64 {
        let mut hasher = FnvHasher::default();
        value.hash(&mut hasher);
        hasher.finish()
    }

    assert_eq!(
        hash(Ipv4Addr::new(127, 0, 0, 1)),
        7785339717392670637,
    );
}
```

**Comment by aDotInTheVoid** [comment]
Rust doesn't garentee that `Hash` impl's will always pass the same values: [From the docs](https://doc.rust-lang.org/stable/std/hash/trait.Hash.html#portability)

> Additionally the data passed by most standard library types should not be considered stable between compiler versions.
>
> This means tests shouldn’t probe hard-coded hash values or data fed to a Hasher and instead should check consistency with Eq.

**Comment by marmeladema** [comment]
Understood.

Is there a viable alternative to get a stable hash for standard library types?

**Comment by Mark-Simulacrum** [comment]
If you need a stable hash (across compiler versions), you probably need to compute it yourself (i.e., with a custom trait or so).

Note that Hash also differs today across architectures, in case that's important for your use case.

**Comment by marmeladema** [comment]
> If you need a stable hash (across compiler versions), you probably need to compute it yourself (i.e., with a custom trait or so).

Ok, will do then. It's a bit unfortunate to not have a StableHash trait provided by the stdlib though

**Comment by Mark-Simulacrum** [comment]
It's a significantly wider design space (e.g., cross platform compatibility, across Rust versions, how to deal with extensibility of a type) - and I'm not aware of significant ecosystem experimentation in this area, so little prior ground to stand on.

(rustc has a stable hashing trait, but it's not what you want: not stable across compiler versions).
