### ISSUE TITLE
`RUSTFLAGS='-Z sanitizer=address'` produces linker-related errors with proc-macro dependencies

### ISSUE THREAD

**Issue by rlee287** [rust-lang/rust#100665]
Reproduction: Add `thiserror` to a new Cargo library project and copy the code below (taken from the `thiserror` example code) into the `src/lib.rs` file:

```rust
use thiserror::Error;
use std::io;

#[derive(Error, Debug)]
pub enum DataStoreError {
    #[error("data store disconnected")]
    Disconnect(#[from] io::Error),
    #[error("the data for key `{0}` is not available")]
    Redaction(String),
    #[error("invalid header (expected {expected:?}, found {found:?})")]
    InvalidHeader {
        expected: String,
        found: String,
    },
    #[error("unknown data store error")]
    Unknown,
}
```

I do not have experience with writing proc-macro crates, so I am currently unable to provide a minimal MCVE with a minimal proc-macro.

A compilation error results when building with `RUSTFLAGS='-Z sanitizer=address'`:
```
$ RUSTFLAGS='-Z sanitizer=address' cargo +nightly build
   Compiling proc-macro2 v1.0.43
   Compiling unicode-ident v1.0.3
   Compiling quote v1.0.21
   Compiling syn v1.0.99
   Compiling thiserror-impl v1.0.32
   Compiling thiserror v1.0.32
error: /[redacted path]/target/debug/deps/libthiserror_impl-0e6745f1051fa7db.so: undefined symbol: __asan_option_detect_stack_use_after_return
   --> /[redacted path]/.cargo/registry/src/github.com-1ecc6299db9ec823/thiserror-1.0.32/src/lib.rs:214:9
    |
214 | pub use thiserror_impl::*;
    |         ^^^^^^^^^^^^^^

error: could not compile `thiserror` due to previous error
```

Expected result: build completes successfully

In the larger code project in which I first encountered this behavior, I also got errors like "the name `try_from_str` is defined multiple times", which suggests some form of linker-related root cause.

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0-nightly (40336865f 2022-08-15)
binary: rustc
commit-hash: 40336865fe7d4a01139a3336639c6971647e885c
commit-date: 2022-08-15
host: x86_64-unknown-linux-gnu
release: 1.65.0-nightly
LLVM version: 15.0.0
```

Rust backtrace: N/A

**Comment by taiki-e** [comment]
You need to pass `--target` flag.

See also [documentation of `-Z sanitizer`](https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/sanitizer.html#build-scripts-and-procedural-macros):

> ### Build scripts and procedural macros
>
> Use of sanitizers together with build scripts and procedural macros is technically possible, but in almost all cases it would be best avoided. This is especially true for procedural macros which would require an instrumented version of rustic.
>
> In more practical terms when using cargo always remember to pass --target flag, so that rustflags will not be applied to build scripts and procedural macros.

**Comment by rlee287** [comment]
It does build successfully with a specified `--target`, thanks.
