### ISSUE TITLE
`cargo test` doesn't always pass `test` flag

### ISSUE THREAD

**Issue by vmarkushin** [rust-lang/rust#100716]
I tried this code:

```rust
#[cfg(not(test))]
compile_error!("error");
```
with `cargo test`

I expected to see this happen: compiles successfully 

Outputs the following:
```
error: foo
 --> src/lib.rs:2:1
  |
2 | compile_error!("foo");
  | ^^^^^^^^^^^^^^^^^^^^^
```

# Update
Explanation [here](https://doc.rust-lang.org/cargo/commands/cargo-test.html#target-selection). To run the test properly, one needs to specify the target, e.g.: `cargo test --package a --lib <test_name>`

**Comment by ehuss** [comment]
Maybe I am misunderstanding the intent, but the following:

```rust
    #[cfg(test)]
    compile_error!("foo"); // to make sure the function should be implemented
```

will unconditionally cause a compile error with `cargo test`. Can you say more about what this is trying to illustrate or what the intent is?

**Comment by vmarkushin** [comment]
Maybe it's because of how compilation works: `cargo build --features=a` is running first (which doesn't pass `test` flag), and only then runs `cargo test`

**Comment by vmarkushin** [comment]
> Maybe I am misunderstanding the intent, but the following:
> 
> ```rust
>     #[cfg(test)]
>     compile_error!("foo"); // to make sure the function should be implemented
> ```
> 
> will unconditionally cause a compile error with `cargo test`. Can you say more about what this is trying to illustrate or what the intent is?

Fixed the expected behavior

**Comment by vmarkushin** [comment]
I've figured out the issue. (see description)
