### ISSUE TITLE
Ipv4Addr can't parse perfectly valid IP address

### ISSUE THREAD

**Issue by gimbles** [rust-lang/rust#100749]
I tried this code:

```rust
"0xac.000000000000000000331.0246.174".parse::<Ipv4Addr>.unwrap()
```

I expected to see this happen: OK

Instead, this happened: It panicked and failed.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=278845b668106e1318e431ba7c81eb47

___

IP addresses can contain different representations in every chunk, the IP address is completely valid. For eg. running `ping` on it, is completely fine.
![image](https://user-images.githubusercontent.com/93856041/185603727-236c6989-550f-4592-8242-b49cbe6c3e2e.png)

**Comment by alexschrod** [comment]
This is explicitly stated not to be supported [in the docs](https://doc.rust-lang.org/std/net/struct.Ipv4Addr.html#textual-representation):
> `Ipv4Addr` provides a `FromStr` implementation. The four octets are in decimal notation, divided by `.` (this is called "dot-decimal notation"). Notably, octal numbers (which are indicated with a leading `0`) and hexadecimal numbers (which are indicated with a leading `0x`) are not allowed per IETF RFC 6943.

**Comment by gimbles** [comment]
Ah, interesting. Alright then. Closing. 👍🏻
