### ISSUE TITLE
Unclear error message on async closure

### ISSUE THREAD

**Issue by adhesivee** [rust-lang/rust#100755]
Trying to setup async closures and it took awhile to figure out what was happening.

It is when types are defined as `Box<dyn Fn() -> (dyn Future<Output = ()>)>` 
More can be seen here: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7eab934ef04fb7171121c4e4180f7f4d

The current output is:

```
12 | async fn message_unboxed(value: UnboxedAsync) {
   |                          ----- `value` has type `Box<dyn Fn() -> (dyn Future<Output = ()> + 'static)>`
13 |     // call expression requires function
14 |     value().await;
   |     ^^^^^--
   |     |
   |     call expression requires function
```

Above was apparently caused by lack of `Pin<Box<_>>` on the future. Once added it works fine (also on playground link)

Would be nice if the error was directing me to the return value of the closure.

**Comment by compiler-errors** [comment]
This has nothing to do with async specifically -- this has to do with the fact that you can't have a `Fn` trait object that returns an unsized type, like `dyn Future`. I can make the "call expression requires function" message instead say something along those lines.

**Comment by eholk** [comment]
Marking as triaged since @compiler-errors is working on it.

@rustbot label +AsyncAwait-Triaged

**Comment by compiler-errors** [comment]
This is blocked on #101100, some machinery in that PR which I'll use to make this suggestion.
