### ISSUE TITLE
error-index is slow to load and shows docs for wrong item while loading

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#100736]
Steps to reproduce:

1. In an IDE using rust-analyzer, write code with an error
2. In the resulting error message, click the link for more details of the error message.

Expected result:

Page shows the appropriate error message.

Actual result:

Page briefly shows E0001 while loading, then jumps to the correct error message:

![image](https://user-images.githubusercontent.com/220205/185517885-61c12b24-d5b7-422c-bd4b-4c36f6abf48e.png)

This is because the error index has gotten quite large. The highest error code is E0788. The total page size is 1.5 MB. The number of DOM elements is 29,342 ([browser engineers recommend < 1,500](https://web.dev/dom-size/?utm_source=lighthouse&utm_medium=lr)).

We should generate a separate page for each error message, and start linking to that, while still generating error-index.md so links from older tooling remain valid and up-to-date.

This may also help those individual pages rank more highly when someone searches for error text. Right now the page is so large that search engines don't consider it a good match even when someone searches for exact text of a specific error message.

**Comment by GuillaumeGomez** [comment]
Taking a look.
