### ISSUE TITLE
`src/tools/lint-docs` has incorrect testing stage by default

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#100739]
When `src/tools/lint-docs` tests fail, x.py outputs the following suggestion:

> To re-run these tests, run: ./x.py test --keep-stage=0 src/tools/lint-docs

However, this command doesn't work, because some documentation tests require a nightly compiler (namely `unused_allocation` lint [uses](https://github.com/rust-lang/rust/blob/6c943bad02626dddc5e5135b23c77429b6e4a063/compiler/rustc_lint/src/unused.rs#L1151) `#![feature(box_syntax)]`) so at least stage 1 compiler is required.

The default for `src/tools/lint-docs` should be changed to stage 1 as well as the suggestion should use `--keep-stage=1` I think.

**Comment by ehuss** [comment]
`./x.py test --keep-stage=0 src/tools/lint-docs` should work. Can you say more about what your config is and the complete output from the failing command?

The default stage is 1, except for "library" users, which probably aren't working on the compiler.

The `--keep-stage=0` syntax means to not rebuild the compiler. If the source is modified just to edit a comment, we don't want it to be rebuilt just for the sake of extracting those comments.

**Comment by WaffleLapkin** [comment]
For some reason I have `profile = "library"` 🤦🏻 

nevermind then
