### ISSUE TITLE
Tracking Issue for slice::reverse in const contexts

### ISSUE THREAD

**Issue by clarfonthey** [rust-lang/rust#100784]
Feature gate: `#![feature(const_reverse)]`

This is a tracking issue for usage of `slice::reverse` in const contexts.

### Public API

```rust
impl<T> [T] {
    pub const fn reverse(&mut self);
}
```

### Steps / History

- [x] Implementation: #100663
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by vilgotf** [comment]
This feature & implementation was removed in https://github.com/rust-lang/rust/commit/63e0ddbf1d820ee62892eee7a50e381d964f1dec

**Comment by RalfJung** [comment]
Indeed, this got removed in https://github.com/rust-lang/rust/pull/110393.
