### ISSUE TITLE
Bad generic error for incorrectly placed `where` clause for tuple struct

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#100790]
Given the following code: [[playground]](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4dc80bbbe0a909a632ad92055ffba8df)

```rust
struct Example
where
    (): Sized,
(usize);
```

The current output is:

```
error: expected one of `:`, `==`, or `=`, found `;`
 --> src/lib.rs:4:8
  |
4 | (usize);
  |        ^ expected one of `:`, `==`, or `=`
```

What appears to be happening is that we're trying to parse this as a unit struct (which *can* have a `where` clause), and thus trying to parse the struct tuple as a type to bound.

With a tuple visibility:

```rust
struct Example
where
    (): Sized,
(pub usize, usize);
```

```
error: expected type, found keyword `pub`
 --> src/lib.rs:4:2
  |
4 | (pub usize, usize);
  |  ^^^ expected type
```

Ideally,

- In the former case (easier?) we can notice that we parsed a tuple type and then got `;` instead of `:` (or a currently-just-for-diagnostics `=`) and then reinterpret the tuple type as a tuple struct tuple, printing a more useful error;
- In the latter case (harder?) we would likely need to backtrack when seeing a `pub` visibility marker and retry to parse as a tuple struct definition tuple in order to provide the nicer error.

**Comment by fmease** [comment]
Note that tuple struct can indeed have a where clause albeit *after* the fields not before them:

```patch
  struct Example
- where
-     (): Sized,
- (usize);
+ (usize)
+ where
+     (): Sized;
```

The proposed diagnostic should suggest to *move* the where clause.

**Comment by fmease** [comment]
Fyi, PR is up: #106537. CC @gamma-delta.
