### ISSUE TITLE
VCRUNTIME140.dll missing on target machine

### ISSUE THREAD

**Issue by juie887** [rust-lang/rust#100874]
Whenever Itry to run a program compiled in rust on a target machine, it gives me an error code saying VCRUNTIME140.dll missing. How can I avoid this without any extra installations on the target machine

**Comment by CryZe** [comment]
Look into `crt-static`: https://www.reddit.com/r/rust/comments/ekts0d/how_to_link_crt_statically_when_building_with_msvc/

**Comment by ChrisDenton** [comment]
If you just want to static link vcruntime (and not the whole CRT), [here's a crate](https://crates.io/crates/static_vcruntime) for that. It's used from a build script (`build.rs`).

Though if you do want to statically link everything then only follow the instructions at the bottom:

> In the same directory as your Cargo.toml, create a folder called `.cargo`. In that folder create the file `config.toml` and add the following:
> 
> ```toml
> [target.'cfg(all(windows, target_env = "msvc"))']
> rustflags = ["-C", "target-feature=+crt-static"]
> ```

**Comment by juie887** [comment]
Hello Chris, 
I just tried this and I get an error code when building error: linking with `link.exe` failed: exit code: 1120

How do I fix this please

**Comment by ChrisDenton** [comment]
It's a bit hard to diagnose with just that error code but you could try doing `cargo clean` before rebuilding. Btw here's two "hello world" example projects:

* [example using `.cargo/config.toml`](https://github.com/ChrisDenton/static_vcruntime/tree/crtstatic/example)
* [example with `static_vcruntime`](https://github.com/ChrisDenton/static_vcruntime/tree/main/example)

**Comment by juie887** [comment]
Hello Chris,

It gives that error code and my build fails. It says something about the
MSVC conflicting with the defaultlib:libraries is there any code I ought to
edit before building

**Comment by ChrisDenton** [comment]
Do either of the examples work for you?

**Comment by juie887** [comment]
Hi Chris,

I used the code below in my .cargo/config and when I tried installing on target pc I didn't get any runtime error but my program ceased to install. Now I'm even more confused 

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

**Comment by ChrisDenton** [comment]
It is very hard to diagnose such issues remotely and with limited information. My best guess is that a dependency of your application is set up for dynamic linking (it would explain the errors you encountered earlier). But that is just a guess. You may need to use a debugger to find out why it isn't working.

One other option is to give up trying to statically link and redistribute just the dll in the same folder as your application. You can find the redistributable dll using the "Developer Powershell" that should be in your start menu.

Type:
```ps1
Join-Path $env:VCToolsRedistDir x64\Microsoft.VC143.CRT\vcruntime140.dll
```

This will give the path to `vcruntime140.dll`. You may need to change `Microsoft.VC143.CRT` to `Microsoft.VC142.CRT` depending on your version.

**Comment by Dylan-DPC** [comment]
Closing this as it is a user-help issue

**Comment by rubo** [comment]
Similar issue here. On a freshly installed Windows Server 2022, our library fails to find `vcruntime140.dll` while there is another one -- `vcruntime140_clr0040.dll`. For testing purposes, I copied that file with the `vcruntime140.dll` name, and that fixed the issue. Is this something that can be improved in the Rust toolchain or we're sentenced to install the Visual C++ Redistributable in such cases?

**Comment by Dylan-DPC** [comment]
Sorry i meant to close this :P
