### ISSUE TITLE
Implement `From<&[T; N]>` and `From<&mut [T; N]>` for `Vec<T>` where `T: Clone`?

### ISSUE THREAD

**Issue by EFanZh** [rust-lang/rust#100880]
Currently we have [`impl From<&[T]> for Vec<T> where T: Clone`](https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#impl-From%3C%26%5BT%5D%3E) and [`impl From<&mut [T]> for Vec<T> where T: Clone`](https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#impl-From%3C%26mut%20%5BT%5D%3E), should `From<&[T; N]>` and `From<&mut [T; N]>` also be implemented for `Vec<T>` where `T: Clone`?

**Comment by vincenzopalazzo** [comment]
Can you help me with runnable code to understand why the `From<&mut [T; N]> [for Vec<T> where T: Clone` will be useful and what can be a use case for it?

@rustbot level +T-libs-api

**Comment by vincenzopalazzo** [comment]
Ah ok, maybe I understand what do you mean, currently we can do

```rust
use std::vec::Vec;

#[derive(Clone, Copy, Debug)]
struct Type;

fn main() {
    let mut array = [Type{}];
    let mut vect = vec![];
    vect.extend_from_slice(&array);
    println!("{:?}", vect);  
}
```

And your proposal is to support

```rust
use std::vec::Vec;

#[derive(Clone, Copy, Debug)]
struct Type;

fn main() {
    let mut array = [Type{}];
    let mut vect = Vec::from(&array);
    println!("{:?}", vect);
    
}
```

**Comment by EFanZh** [comment]
@vincenzopalazzo I don’t have a use case for `From<&mut [T; N]>`, adding it is just for matching `From<&mut [T]>`. I want to be able to write:

```rust
fn foo(value: Option<&[String; 2]>) -> Option<Vec<String>> {
    value.map(Vec::from)
}
```

instead of

```rust
fn foo(value: Option<&[String; 2]>) -> Option<Vec<String>> {
    value.map(<[_; 2]>::as_slice).map(Vec::from)
}
```
