### ISSUE TITLE
Improve diagnostic for missing `IndexMut: HashMap`

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#100873]
The following is invalid

```rust
let mut unique_things: HashMap<usize, bool>  = HashMap::new();
unique_things[&5] = false;
```

```
error[E0594]: cannot assign to data in an index of `HashMap<usize, bool>`
   --> src/main.rs:147:2
    |
147 |     unique_things[&5] = false;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^ cannot assign
    |
    = help: trait `IndexMut` is required to modify indexed content, but it is not implemented for `HashMap<usize, bool>`
```

Because the entry `&5` *must* exist before it can be assigned to. We should propose the use of the `Entry` APIs or `.insert` method.

_https://users.rust-lang.org/t/problematic-errormessage-indexmut-is-required-to-modify-indexed-content/80158_

**Comment by ChayimFriedman2** [comment]
The code responsible for generating this error is in compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs, but I don't feel like polluting it with detection of `HashMap` (and `BTreeMap`). Do you have a better idea?

**Comment by estebank** [comment]
It is not that uncommon for us to have weird one-off detection of types, although we do try to avoid it. Given that this is about `HashMap` and something a newcomer might reasonably attempt, I feel it is reasonable to do so. You should move the logic to its own method to avoid cluttering the happy path, though.

**Comment by estebank** [comment]
CC https://github.com/rust-lang/rust/pull/52788
