### ISSUE TITLE
std::path::Path prefix parsing in Windows is inconsistent with other OS's

### ISSUE THREAD

**Issue by ncihnegn** [rust-lang/rust#100833]
I tried this code:

```rust
Path("//tmp/abs_evil2.txt").components()
```

I expected to see this happen: 

```
RootDir, RootDir, Normal("tmp"), Normal("abs_evil2.txt")
```

Instead, this happened: 

```
Prefix(PrefixComponent { raw: "//tmp/abs_evil2.txt", parsed: UNC("tmp", "abs_evil2.txt") })
```

**Comment by ChrisDenton** [comment]
This is intentional. `Path` is an abstraction over the paths of the platform it's used on. On Unix this is a POSIX path and on Windows it's a Win32 path. So they are not expected to work the same across platform.

In this case the path `//tmp/abs_evil2.txt` is parsed as a Win32 [UNC path](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#unc-paths) on Windows. Note also that Windows normalizes `/` to `\` so `//tmp/abs_evil2.txt` is equivalent to `\\tmp\abs_evil2.txt`.

**Comment by ncihnegn** [comment]
I think it is incorrect to parse a POSIX path into a Win32 path.

A path should be parsed as UNC only if it starts with ```\\```, not when it starts with ```//```.

**Comment by Kobata** [comment]
There is no difference, as pointed out above Windows will accept either `/` or `\` mostly-equivalently[1].

It's fairly easy to see, for instance in `cmd` running something like `dir "//./C:/"` (you do need the quotes for it to think it's a path) is equivalent to `dir //./C:/` (which is *also* equivalent to `dir "C:/"` and `dir C:\`)

[1] The exception is paths that begin with *exactly* `\\?\`, using backslashes, `//?/` is also a valid path-prefix but doesn't have the special handling that the backspace-version does.

**Comment by ncihnegn** [comment]
Is there any way to force POSIX path parsing or disable UNC parsing?

**Comment by ChrisDenton** [comment]
Disabling UNC parsing wouldn't make sense, even if it were possible it's still a Windows path so `//` wouldn't be a root. What you're looking for is [`UnixPath`](https://github.com/rust-lang/rust/issues/66621) which doesn't yet exist in std. Currently you'd have to use a third party crate (or make your own).

**Comment by chipsenkbeil** [comment]
@ncihnegn @ChrisDenton I just published [typed-path](https://github.com/chipsenkbeil/typed-path) as a means to partially solve this problem by providing [`UnixPath`](https://docs.rs/typed-path/latest/typed_path/unix/type.UnixPath.html) and [`WindowsPath`](https://docs.rs/typed-path/latest/typed_path/windows/type.WindowsPath.html), in case you were interested in something like this.

**Comment by ChrisDenton** [comment]
Great! I'm closing this issue in favour of #66621 or using a crate.
