### ISSUE TITLE
Recursion limit tripped in doc but not in other profiles

### ISSUE THREAD

**Issue by TaKO8Ki** [rust-lang/rust#100991]
The diesel benchmark has been broken in some recent commit: https://perf.rust-lang.org/status.html.

ref: [zulip comment](https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance/topic/.60diesel.60.20benchmark.20broken/near/295189845)

**Comment by rylev** [comment]
The error seems to be caused https://github.com/rust-lang/rust/issues/100757 (cc @ouz-a). Curiously, this only happens in `doc`. 

Here's the error:

```
 Documenting diesel v1.4.8 (/home/rylevick/code/rustc-perf/collector/benchmarks/diesel-1.4.8)
error[E0275]: overflow evaluating the requirement `<_ as query_source::Column>::Table`
    |
    = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`diesel`)
note: required for `&expression::operators::Eq<_, _>` to implement `insertable::Insertable<_>`
   --> src/expression/operators.rs:376:21
    |
376 | impl<'a, T, Tab, U> Insertable<Tab> for &'a Eq<T, U>
```

The line where the error triggers is:

```rust
impl<'a, T, Tab, U> Insertable<Tab> for &'a Eq<T, U> // <--- HERE
where
    T: Copy,
    Eq<T, &'a U>: Insertable<Tab>,
{
    type Values = <Eq<T, &'a U> as Insertable<Tab>>::Values;

    fn values(self) -> Self::Values {
        Eq::new(self.left, &self.right).values()
    }
}
```

You can reproduce this issue by:
* cloning the rustc-perf repo
* going to diesel-1.4.8 benchmark in that repo
* installing commit `a72b0e79ba45f05b339b45034996086bf10d3c26 ` using `rustup-toolchain-install-master` 
* running `cargo +a72b0e79ba45f05b339b45034996086bf10d3c26 doc`

**Comment by ouz-a** [comment]
How can I run this via locally built rustc? @rylev

**Comment by weiznich** [comment]
https://github.com/rust-lang/rust/issues/100620 might be related as well?

**Comment by ouz-a** [comment]
That indeed looks related, so #100705 should fix this ?

**Comment by rylev** [comment]
The comment [here](https://github.com/rust-lang/rust/pull/100705#issuecomment-1226849391) also makes it look like #100705 will fix this.

**Comment by rylev** [comment]
Unfortunately, #100705 did *not* fix the issue. 

Using the build bors creates after merge 983f4daddf238d114c4adc4751c5528fc6695a5a, `cargo +983f4daddf238d114c4adc4751c5528fc6695a5a doc` leads to the same error as above. 

@ouz-a to reproduce this, you just need to clone the rustc-perf repo and cd into `collector/benchmarks/diesel-1.4.8`. Then run `rustup-toolchain-install-master 983f4daddf238d114c4adc4751c5528fc6695a5a` and `cargo +983f4daddf238d114c4adc4751c5528fc6695a5a doc`

**Comment by ouz-a** [comment]
Thanks, I will try to push a fix today.

**Comment by compiler-errors** [comment]
I'm just gonna revert my original PR that introduced this overflow until I can create a version that works with diesel, @ouz-a, given the perf regression of my "fix" and the remaining existence of this issue, so don't waste too much time on this.

**Comment by ouz-a** [comment]
I already found a fix 😅

**Comment by jyn514** [comment]
CC https://github.com/rust-lang/rust/issues/81091
