### ISSUE TITLE
Playground not working?

### ISSUE THREAD

**Issue by reez12g** [rust-lang/rust#100990]
I ran the code shown in the following image.
I received this error message.
`Response was not JSON: SyntaxError: Unexpected token '<',"<!DOCTYPE "... is not valid JSON`.

<img width="1578" alt="Screen Shot 2022-08-25 at 18 18 50" src="https://user-images.githubusercontent.com/46887885/186626750-85669ffa-f9bc-4e73-9f91-a3f7c0faed28.png">

Looking at the response to the Run request, it appears that the 504 was returned in communication via CloudFront.

Does anyone else have similar symptoms?
Please let me know if this is not the appropriate place to create this Issue.

**Comment by reez12g** [comment]
When a colleague ran it, there was no problem, so it does not seem to occur 100% of the time.

I am not sure of the situation yet, so I will temporarily close it.

**Comment by dcabanis** [comment]
I am getting the same error today (linux/win11) using both Edge and chrome. 

Unexpected token '<', "<!DOCTYPE "... is not valid JSON

Using firefox I get the error:

JSON.parse: unexpected character at line 1 column 1 of the JSON data

I never had such an issue with the tool before. Can someone look into this?

Kindly
