### ISSUE TITLE
`named_arguments_used_positionally` lint drops some formatting options

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#100992]
```rust
fn main() {
    format!("{:x}", a=1);
}
```

```
warning: named argument `a` is not used by name
 --> src/main.rs:2:21
  |
2 |     format!("{:x}", a=1);
  |              ----   ^ this named argument is referred to by position in formatting string
  |              |
  |              this formatting argument uses named argument `a` by position
  |
  = note: `#[warn(named_arguments_used_positionally)]` on by default
help: use the named argument by name to avoid ambiguity
  |
2 |     format!("{a}", a=1);
  |               ~
```

The `:x` disappears.

**Comment by m-ou-se** [comment]
I found this while refactoring `compiler/rustc_builtin_macros/src/format.rs`. Assigning to myself to fix as part of the refactor.

**Comment by TaKO8Ki** [comment]
I think this problem has already been solved in #100826.

**Comment by m-ou-se** [comment]
Ah, thanks. Yes, that fixes it.

It seems like it could've been fixed by only removing some 'special' cases in the original code, without `span_to_snippet`, but I'll do that as part of my refactor.

**Comment by m-ou-se** [comment]
That struct and that method are entirely gone after my refector, and the entire `has_formatting` will be unnecessary. :)

**Comment by TaKO8Ki** [comment]
That's great!
