### ISSUE TITLE
SPLICE API removes ending bytes

### ISSUE THREAD

**Issue by vahidmohsseni** [rust-lang/rust#101053]
I tried this code:

```rust

fn main() {
    let mut bytes = vec![0u8; 128 as usize];
    println!("bytes: {:?}, len: {}", bytes, bytes.len());

    let id = 1234u32;
    let hello = "Hello, world!".to_string();
    let port_number = 8080u16;
    let some_random_string = "Some random string".to_string();

    bytes.splice(0..4, id.to_be_bytes());
    bytes.splice(5..25, hello.as_bytes().to_vec());
    bytes.splice(25..27, port_number.to_be_bytes());
    bytes.splice(27..47, some_random_string.as_bytes().to_vec());

    println!("bytes: {:?}, len: {}", bytes, bytes.len());

}

```

As you see, I allocated 128 bytes of u8. The first print instruction shows the bytes and the size of the vector correctly (128). However, after adding data with `splice`, the size of the vector changes to 119. 
It seems that the last `splice` with `some_random_string` eliminates some bytes from the end.

`rustc --version --verbose`:
```
rustc 1.62.1 (e092d0b6b 2022-07-16)
binary: rustc
commit-hash: e092d0b6b43f2de967af0887873151bb1c0b18d3
commit-date: 2022-07-16
host: x86_64-unknown-linux-gnu
release: 1.62.1
LLVM version: 14.0.5
```

**Comment by 5225225** [comment]
some_random_string isn't 47-27=20 bytes long, is it? This is intended behavior.

See https://doc.rust-lang.org/std/vec/struct.Vec.html#method.splice

> Creates a splicing iterator that replaces the specified range in the vector with the given replace_with iterator and yields the removed items. **replace_with does not need to be the same length as range.**

If you provide an iterator that's shorter than the range, you will remove items from the list. Same for providing one that's longer than the range.

Are you perhaps looking for https://doc.rust-lang.org/std/vec/struct.Vec.html#method.copy_from_slice which will panic if they have different lengths, but will not change the length? (It's up to you to shorten the destination slice to exactly fit the source slice)

**Comment by vahidmohsseni** [comment]
Thanks for the information. It seems that I missed that part of the documentation. 

I was looking for behavior that inserts into a range of a vector same as splice but maintains the size from the source.
