### ISSUE TITLE
disable MIR inlining on beta-1.64

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#101004]
As discussed in T-compiler meeting https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-08-25/near/295236517, we are going to disable MIR inlining on beta-1.64 in order to resolve issues like #100550 and #100476 without having to do semi-risky backports.

For reference, the PR that enabled MIR inlining was PR #91743

**Comment by Mark-Simulacrum** [comment]
cc https://github.com/rust-lang/rust/issues/100550#issuecomment-1214876441 (and subsequent comments) -- it doesn't look like that was discussed prior to agreeing to do this.

**Comment by pnkfelix** [comment]
I opened a zulip thread to discuss this further: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/.28re.29debating.20disabling.20MIR-inlining.20on.201.2E64-beta.20.23101004/near/295256039

**Comment by pnkfelix** [comment]
closed by merge of #101050
