### ISSUE TITLE
UEFI targets fail to compile: "LLVM ERROR: dwo only supported with ELF and Wasm"

### ISSUE THREAD

**Issue by nicholasbishop** [rust-lang/rust#101071]
The UEFI targets (x86_64-unknown-uefi, i686-unknown-uefi, and aarch64-unknown-uefi) started failing to compile in the latest nightly when using `build-std`, failing with "LLVM ERROR: dwo only supported with ELF and Wasm".

### Code

`src/main`:

```rust
#![no_main]
#![no_std]

#[panic_handler]
fn panic_handler(_info: &core::panic::PanicInfo) -> ! {
    loop {}
}

#[export_name = "efi_main"]
pub extern "C" fn main(_h: *mut core::ffi::c_void, _st: *mut core::ffi::c_void) -> usize {
    0
}
```

`.cargo/config.toml`:
```toml
[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
```

Build:
```
$ cargo +nightly build --target x86_64-unknown-uefi
   Compiling core v0.0.0 (/var/home/nbishop/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
   Compiling rustc-std-workspace-core v1.99.0 (/var/home/nbishop/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core)
LLVM ERROR: dwo only supported with ELF and Wasm
   Compiling compiler_builtins v0.1.79
LLVM ERROR: dwo only supported with ELF and Wasm
error: could not compile `rustc-std-workspace-core`
warning: build failed, waiting for other jobs to finish...
error: could not compile `core`
LLVM ERROR: dwo only supported with ELF and Wasm
error: could not compile `compiler_builtins`
```

### `cargo-bisect-rustc` output

searched nightlies: from nightly-2022-08-25 to nightly-2022-08-27
regressed nightly: nightly-2022-08-27
searched commit range: https://github.com/rust-lang/rust/compare/7480389611f9d04bd34adf41a2b3029be4eb815e...c07a8b4e09f356c7468b69c50cac7fc5b5000b8a
regressed commit: https://github.com/rust-lang/rust/commit/450e99f93795c81c1f2d10be27fb3a98be5b0cfc

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.4</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc -- build --target x86_64-unknown-uefi 
```
</details>

CC @davidtwco since bisect pointed to https://github.com/rust-lang/rust/pull/98051

**Comment by kennystrawnmusic** [comment]
Can confirm. Definitely needs to be looked into by the team — @phil-opp can you reproduce this?

**Comment by nicholasbishop** [comment]
I see in https://github.com/rust-lang/rust/pull/98051/files#diff-e8d72f87be1eb954600ca7d27ce0fdd7360fe43e393c5bb0d73e226f11abc67d that `debuginfo_kind: DebuginfoKind::Pdb` is set in `windows_msvc_base`. I think that needs to be added in https://github.com/rust-lang/rust/blob/master/compiler/rustc_target/src/spec/uefi_msvc_base.rs, or maybe directly in `msvc_base`?

I tested this out locally by using a custom target JSON that matches `x86_64-unknown-uefi` except adds `"debuginfo-kind": "pdb"`, and that seems to fix the bug.
