### ISSUE TITLE
Works on debug build, but not on release build.

### ISSUE THREAD

**Issue by M3DZIK** [rust-lang/rust#101130]
I tried this code:

https://github.com/MedzikUser/rust-issue-101130

I expected it to work in the release build

Instead, this happened work only in debug build

About code:
This is a simple cryptography library which generates encryption key and encode text in build time.

For example, in the release build version if the key during the build is 7. Then during the runtime, key is for example, 39.
![image](https://user-images.githubusercontent.com/87065584/187086008-78565057-ee8d-497e-8113-fc2aa07e14fc.png)

The same code on debug build always have the same key

![image](https://user-images.githubusercontent.com/87065584/187086081-64eee3a6-6b05-4902-bca9-7a414f051018.png)

### Meta

`rustc --version --verbose`:
```
rustc 1.63.0 (4b91a6ea7 2022-08-08)
binary: rustc
commit-hash: 4b91a6ea7258a947e59c6522cd5898e7c0a6a88f
commit-date: 2022-08-08
host: x86_64-unknown-linux-gnu
release: 1.63.0
LLVM version: 14.0.5
```
(latest stable)

and

```
rustc 1.65.0-nightly (eaadb8947 2022-08-27)
binary: rustc
commit-hash: eaadb8947b850a025404082f6297766c4680a42a
commit-date: 2022-08-27
host: x86_64-unknown-linux-gnu
release: 1.65.0-nightly
LLVM version: 15.0.0
```
(latest nightly)

**Comment by zirconium-n** [comment]
Note: OP used a non-deterministic proc-macro to generate a const `KEY` at comptime, which is used by the main crate and another proc-macro `macro` (which is used by the main crate).

What's happening here is that, in release build, the `KEY` in `macro` is different from the `KEY` in main.

This can be reproduced with replacing OP's random proc-macro with `const-random` crate on crates.io.

**Comment by veber-alex** [comment]
[All profiles, by default, do not optimize build dependencies (build scripts, proc macros, and their dependencies).](https://doc.rust-lang.org/cargo/reference/profiles.html#build-dependencies)

In dev profile the key crate is compiled without optimizations and both the binary and the proc macro use the same artifacts, which means `KEY` is the same.
In release profile the proc macro and the binary use different artifacts of the key crate which means different `KEY`.

Adding
```toml
[profile.release.build-override]
opt-level = 3
```
to the binary crate resolves the issue.

**Comment by MedzikUser** [comment]
> Adding
> 
> ```toml
> [profile.release.build-override]
> opt-level = 3
> ```
> 
> to the binary crate resolves the issue.

Use build.rs which generates and adds a key to env also solves this problem.
