### ISSUE TITLE
Tracking Issue for slice::split_at in const context

### ISSUE THREAD

**Issue by tspiteri** [rust-lang/rust#101158]
Feature gate: `#![feature(const_slice_split_at_not_mut)]`

This is a tracking issue for usage of `slice::split_at` in const context.

### Public API

```rust
impl<T> [T] {
    pub const fn split_at(&self, mid: usize) -> (&[T], &[T]);
}
```

### Steps / History

- [x] Implementation: #100076
- [x] Final comment period (FCP): https://github.com/rust-lang/rust/issues/101158#issuecomment-1529681484
- [x] Stabilization PR: https://github.com/rust-lang/rust/pull/108273

### Unresolved Questions

- None yet.

**Comment by m-ou-se** [comment]
@rfcbot merge

cc @rust-lang/wg-const-eval
