### ISSUE TITLE
Suggest `_` in warning when match catch-all arm variable is unused

### ISSUE THREAD

**Issue by Rageking8** [rust-lang/rust#101205]
Given the following code: [link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=98cc6032446710079d5b59e4a583f797)

```rust
fn main() {
    let num = 123;
    let _x = match num {
        1 => 2,
        2 => 3,
        other => 10
    };
}
```

The current output is:

```
   Compiling playground v0.0.1 (/playground)
warning: unused variable: `other`
 --> src/main.rs:6:9
  |
6 |         other => 10
  |         ^^^^^ help: if this is intentional, prefix it with an underscore: `_other`
  |
  = note: `#[warn(unused_variables)]` on by default

warning: `playground` (bin "playground") generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 0.98s
     Running `target/debug/playground`
```

Ideally the output should suggest changing the variable in the last match arm to `_` as its slightly more idiomatic.

**Comment by estebank** [comment]
Maintaining the existing ident and only prepending `_` instead of fully replacing it can be useful for code documentation (I often leave binding names around purely to have an identifier explaining what it was). Replacing it in its entirety with `_` could remove that context.

**Comment by Rageking8** [comment]
Maybe keep the current note and just add a small "or `_`"?

**Comment by compiler-errors** [comment]
Also, correct me if I'm wrong, but doesn't replacing `_ident` with `_` change the drop behavior? I don't know if we should suggest this given that it changes semantics.

**Comment by Rageking8** [comment]
Oh, then maybe we shouldn't change the suggestion after all.
