### ISSUE TITLE
droping mutability of mutable addresses

### ISSUE THREAD

**Issue by ozkanonur** [rust-lang/rust#101277]
Since Rust provides bunch of useful macros, what about providing this one as well?

```rs
macro_rules! drop_mutability {
    ($t: ident) => { let $t = $t; };
}
```
This is useful for preventing invalid data assignment to the mutable addresses in large code blocks. If there will any data assignment happen after droping mutability, we will be informed by the compiler error without facing with logical bugs on runtime. Since no extra `drop_in_place` getting called, I suppose this macro can be called zero-cost functionality.

Example use case:
```rs
let mut x = 10;
.
.
x = 1;
drop_mutability(x); // End the mutability since there is no longer needed
.
.
.
.
.
Ok(())
```

Please let me know if this is acceptable. If so, I can prepare the PR.

**Comment by ChrisDenton** [comment]
How about:

```rust
let mut x = 10;
x = 1;
let x = x;
```

**Comment by ozkanonur** [comment]
> How about:
> 
> ```rust
> let mut x = 10;
> x = 1;
> let x = x;
> ```

Same thing.
However, reading this:
```rs
drop_mutability!([x, y, z]); // can take multiple args with better implementation
``` 
instead of
```rs
let x = x;
let y = y;
let z = z;
```
can be more clear on code reviews in my opinion.

**Comment by ChrisDenton** [comment]
I'm not trying to be facetious here I'm just not really seeing the macro as having much of an advantage? And it may be surprising in some cases:

```
let mut x = 1;
{
     ...
     drop_mutability!(x);
}
x = 2l
```

The manual method can be written in a slightly more compact way:
```rust
let (x, y, z) = (x, y, z);
```

Or maybe this for some use cases:

```rust
let (x, y, z) = {
    let mut x = 1;
    let mut y = 2;
    let mut z = 3;
    ...
    (x, y, z)
};
```
