### ISSUE TITLE
ty::type_is_sized needs to work via type_contents

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#10126]
Sub-task of #6308.

Relevant diaglogue from `#rust-internals` : https://botbot.me/mozilla/rust-internals/msg/7309210/

In short: the input `ty::type_is_sized` may not have all of the necessary bits populated yet, because one needs to look recursively up the trait inheritance hierarchy to find out if a type parameter is bounded by a trait that inherits from `Sized`.

As @nikomatsakis suggested, use the code for `type_is_sendable` or `type_needs_drop` as a model here.

**Comment by steveklabnik** [comment]
Triage: no clue.

**Comment by nikomatsakis** [comment]
This is fixed.
