### ISSUE TITLE
Odd result from Path::components on Windows

### ISSUE THREAD

**Issue by casey** [rust-lang/rust#101358]
This might be a bug, or this might just be me not understanding how Windows UNC paths work.

When I call this:

```rust
Path::new("//foo//bar//").components().collect::<Vec<Component>>()
```

I get:

```rust
[Prefix(PrefixComponent { raw: "//foo//ba", parsed: UNC("foo", "bar") }), RootDir, Normal("r")]
```

This seems very odd! The `bar` component is truncated, and `//foo/ba` is the prefix, followed by a root dir, followed a normal `r` component.

It seems like the way this path is broken into components on Windows has changed since an old release. I have a path cleaning library, [lexiclean](https://github.com/casey/lexiclean/), whose CI was passing as of April 20th. It picked up a new release between now and then, and CI is now failing.

**Comment by ChrisDenton** [comment]
This is indeed a bug. But it's also a bit of an edge case. It's not entirely obvious what the correct behaviour should be as technically speaking it's not a well formed path. The prefix is one place where Windows (sometimes) cares about the number and type of slashes.

Anyway, the old behaviour was:

```rust
[RootDir, Normal("foo"), Normal("bar")]
```

Which is also wrong (it changes the prefix type), but maybe less wrong than it currently is.

Perhaps the best we could do is:

```rust
[Prefix(PrefixComponent { raw: "//foo", parsed: UNC("foo", "") }), RootDir, Normal("bar")]
```

Which at least preserves the root.

Ideally it would be:

```rust
[Prefix(PrefixComponent { raw: "//foo//bar", parsed: UNC("foo", "bar") }), RootDir]
```

But currently we require the prefix length to be able to be recomputed from the parsed parts so this isn't currently possible.
