### ISSUE TITLE
Replace `std::io::lazy::Lazy` with `std::cell::LazyCell`?

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#101354]
Could [`std::io::lazy::Lazy`](https://github.com/rust-lang/rust/blob/7c98d2e63f732682b057c8c453b08f9e12b262e6/src/libstd/io/lazy.rs) be replaced with [`std::cell::Lazy`](https://doc.rust-lang.org/nightly/std/cell/struct.LazyCell.html)? What does the former offer that the latter doesn't already have?

**Comment by compiler-errors** [comment]
#77154

**Comment by frewsxcv** [comment]
Oh I'm linking to an old git SHA oops. It's already gone
