### ISSUE TITLE
hashbrown tests crash on wine

### ISSUE THREAD

**Issue by Amanieu** [rust-lang/rust#101474]
When running `cargo test --target x86_64-pc-windows-gnu` on a Linux system with Wine installed, the tests crash with:
```
wine: Unhandled page fault on read access to 0000000000000081 at address 00000002D4D43703 (thread 010c), starting debugger...
```

Bisecting points to https://github.com/rust-lang/rust/commit/92086258e30ae59610a1b1097d97227377db0ada, I suspect the root cause might be https://github.com/rust-lang/rust/pull/101325.

cc @ChrisDenton

**Comment by Amanieu** [comment]
I couldn't get a proper backtrace due to a different bug (in wine, not in rust) where winedbg fails to parse our debuginfo and crashes.

**Comment by ChrisDenton** [comment]
Ah, I think this is to do with the use of a pseduo-handle instead of a real handle (which is unsupported in WINE). I'll patch asap.

**Comment by glandium** [comment]
I'm observing similar crashes on whatever version of Windows Server is used on Firefox CI.

**Comment by ChrisDenton** [comment]
A fix has been posted. Just pending approval.
