### ISSUE TITLE
std library compile errors for uwp-windows-msvc targets

### ISSUE THREAD

**Issue by korejan** [rust-lang/rust#101480]
Building std library (-Zbuild-std) with nightly for uwp-windows-msvc targets has been failing with compile errors since around after 02/06/22

```rust
error[E0425]: cannot find value `reparse_tag` in this scope
   --> C:\Users\runneradmin\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys\windows\fs.rs:406:21
    |
406 |                     reparse_tag = attr_tag.ReparseTag;
    |                     ^^^^^^^^^^^ not found in this scope

```

I expected to see this happen:

Last successeful build on 02/06:

https://github.com/korejan/ALVR/runs/8154433510?check_suite_focus=true

Instead, this happened:

Lastest failed build:

https://github.com/korejan/ALVR/runs/8204519566?check_suite_focus=true#step:6:275

### Version it worked on

It most recently worked on: rustc 1.65.0-nightly (2e35f954a 2022-09-01)

### Version with regression

`rustc --version --verbose`:
```
1.65.0-nightly (b44197abb 2022-09-05)
```

### Backtrace

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by ChrisDenton** [comment]
Thanks for the report! I've submitted a fix (linked above).
