### ISSUE TITLE
Tracking Issue for const_unicode_case_lookup

### ISSUE THREAD

**Issue by mx00s** [rust-lang/rust#101400]
Feature gate: `#![feature(const_unicode_case_lookup)]`

This is a tracking issue for making `char::is_lowercase` and `char::is_uppercase` const.

### Public API

-    https://doc.rust-lang.org/nightly/core/primitive.char.html#method.is_uppercase
-    https://doc.rust-lang.org/nightly/core/primitive.char.html#method.is_lowercase

Example:

```rust
const CAPITAL_DELTA_IS_UPPERCASE: bool = 'Δ'.is_uppercase();
```

### Steps / History

- [x] Implementation: #101401
- [x] Final comment period (FCP)[^1]
- [ ] Stabilization PR: https://github.com/rust-lang/rust/pull/132948

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by DaniPopes** [comment]
This has been unstable for more than a year, and with no reported issues I think this can be stabilized.

The full API is making `char::{is_lowercase,is_uppercase}` const-stable.

**Comment by dtolnay** [comment]
From skimming the implementation PR, I am apprehensive about seeing it convert many Unicode tables from `static` to `const`. Consts are defined to behave as if their definition is copy-pasted at every use. Statics are not; they appear at most once, at a single address. See also https://github.com/rust-lang/rust/pull/82676.

I would not want to regret being forced to define Unicode tables as `const` when we later find that `static`'s semantics are more appropriate for them.

It would be good to get reassurance from a compiler perspective about whether committing to representing Unicode tables as `const` is going to be problematic.

**Comment by RalfJung** [comment]
> From skimming the implementation PR, I am apprehensive about seeing it convert many Unicode tables from static to const. Consts are defined to behave as if their definition is copy-pasted at every use. Statics are not; they appear at most once, at a single address. 

https://github.com/rust-lang/rust/pull/131641 resolves that. So I think this is ready for const-stabilization?

**Comment by dtolnay** [comment]
- https://doc.rust-lang.org/nightly/core/primitive.char.html#method.is_uppercase
- https://doc.rust-lang.org/nightly/core/primitive.char.html#method.is_lowercase

@rfcbot fcp merge

**Comment by RalfJung** [comment]
@Amanieu @BurntSushi @m-ou-se friendly FCP checkbox reminder. :)  This function is long stable, so making it const-stable should be uncontroversial.

**Comment by RalfJung** [comment]
> This looks great. Could we do the same for the other `char` methods, like `is_digit` and `is_alphabetic`?

`is_digit` is tracked at https://github.com/rust-lang/rust/issues/132241. Looks like nobody tried making `is_alphabetic` const-callable yet.
