### ISSUE TITLE
const prop missing diagnostic with unrelated changes

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#101470]
Since rustc 1.61, the following code is not giving a compile-time error:

```
fn main() {
    let xs = [10, 20, 30];
    println!("{}", xs[10]);

    let _n = xs.len();
}
```

If I uncomment the last line, the compile-time error shows up.
Is this right? I would expect the compile-time error to show up in both cases (this is what happens for rustc < 1.61).

cc @oli-obk

_Originally posted by @paolieri in https://github.com/rust-lang/rust/issues/48920#issuecomment-1237506737_

**Comment by steffahn** [comment]
@rustbot label A-lint, regression-from-stable-to-stable

For context, the “error” pre-1.61 is the deny-by-default `unconditional_panic` lint
```
error: this operation will panic at runtime
 --> <source>:3:20
  |
3 |     println!("{}", xs[10]);
  |                    ^^^^^^ index out of bounds: the length is 3 but the index is 10
  |
  = note: `#[deny(unconditional_panic)]` on by default

error: aborting due to previous error
```

Bisection points to regression in #94934.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23101470.20const.20prop.20missing.20diagnostic.20with.20unrelated.20changes)).

@rustbot label -I-prioritize +P-high T-compiler

**Comment by oli-obk** [comment]
duplicate of #98444
