### ISSUE TITLE
Bug in `#[should_panic]` `test` attribute

### ISSUE THREAD

**Issue by JustForFun88** [rust-lang/rust#101543]
I tried this code [play.rust-lang.org](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=31430a2662a4a9ce33f6415c57ea111d):

```rust
#[test]
#[should_panic = "should panic"]
fn panic_v1() {
    panic!("should panic0123456789")
}
```

I expected to see this happen:

```
note: panic did not contain expected string
      panic message: `"should panic0123456789"`,
 expected substring: `"should panic"`
```
Instead, this happened:

```
running 1 test
test panic_v1 - should panic ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

It is the same in all current stable, beta and nightly.

**Comment by colt-browning** [comment]
Well, the string "should panic0123456789" contains the substring "should panic".

**Comment by Nilstrieb** [comment]
There is no bug here, the message seems clear enough here. If you have further improvements to the output, feel free to reopen.
