### ISSUE TITLE
match ergonomics on `&&str` is weird

### ISSUE THREAD

**Issue by zjp-CN** [rust-lang/rust#101510]
```rust
    match &"123" {
        x @ "123" => println!("1: {}", type_name_of_val(&x)), // expected &&str, found &str
        x => println!("2: {}", type_name_of_val(&x)), // &&str
    };
```
is not allowed, which seems an unmentioned exception wrt [RFC2005: match-ergonomics](https://rust-lang.github.io/rfcs/2005-match-ergonomics.html). Is there a reason for it? 

BTW for slice, this is allowed:

```rust
    match &&[123, 456][..] {
        x @ [123, 456] => println!("1: {}", type_name_of_val(&x)), // &[i32] (inferred by RA), &&[i32] (output by type_name_of_val)
        x => println!("2: {}", type_name_of_val(&x)),
    };
```

I've listed some related code snippets on [the forum](https://users.rust-lang.org/t/match-ergonomics-on-str-and-type-inferred-on-its-branch) if someone is interested.

**Comment by jyn514** [comment]
I am not sure why str differs from slices here, you'd probably have to dig into the code.

That said, I don't think this is a bug as such, just a missing enhancement. I'm going to close this issue, but feel to discuss it in one of the following places:

https://discord.gg/rust-lang/
https://discord.gg/rust-lang-community/
https://users.rust-lang.org/
https://rust-lang.zulipchat.com/
