### ISSUE TITLE
Compilation on Xeon E5-2650 computer

### ISSUE THREAD

**Issue by MathieuDutSik** [rust-lang/rust#101651]
### Problem

I am trying to compile some rust code on a relatively old computer (that is "Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz").
When compiling, I get the following error: **Error: no such instruction: `shrx %rsi,%rax,%rax'**.
The rust compiler was set up with **curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
**.

I understand that the processor is now 10 years old but still, I can compile GCC on it and do plenty of useful work. So, I would appreciate it if rust supported this CPU. If that were not possible, it would be nice to have a warning beforehand about that so that the error do not show while 

### Steps

"cargo build" on some code, anything really.

### Possible Solution(s)

Two possible type of solution would be nice:
* A support by cargo of this CPU. Maye there is just some tweaks to do for LLVM as this line of CPU ought to be supported by LLVM.
* An indication that this CPU is not supported while installing cargo.

### Version

```text
cargo 1.60.0 (d1fd9fe 2022-03-01)
release: 1.60.0
commit-hash: d1fd9fe2c40a1a56af9132b5c92ab963ac7ae422
commit-date: 2022-03-01
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1m)
os: CentOS 6.6 (Final) [64-bit]
```

**Comment by ehuss** [comment]
Transferred to rust-lang/rust, as this is a compiler issue.

It looks like it is selecting the bmi2 instructions. I do no think those should normally be activated with `x86_64-unknown-linux-gnu`.  Can you make sure that there aren't any flags being set, like `-Ctarget-cpu` or `-Ctarget-feature`?  Does this happen with a simple hello-world program?

**Comment by MathieuDutSik** [comment]
Thank you for looking at this. No it does not happen with a hello-world program nor some non-trivial code llike tokio library. I will try to isolate the problem further.

**Comment by MathieuDutSik** [comment]
One example of a public code that shows the same problem is **https://github.com/jvff/ghti** with the precise error being **/home/mathieu/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/x86_64-mont-elf.S:1144: Error: no such instruction: `adcxq %rax,%r12'** (along with other bugs of course).

**Comment by workingjubilee** [comment]
This is a bug in ring. Closing.

**Comment by workingjubilee** [comment]
Repository, for reference: https://github.com/briansmith/ring

**Comment by briansmith** [comment]
> Error: no such instruction: `shrx %rsi,%rax,%rax'.
> Error: no such instruction: `adcxq %rax,%r12' 

For posterity, since somebody pointed me to this issue: shrx is a BMI2 instruction, which is relatively new. Similarly, `adcxq` is a ADX instruction, which is fairly new. *ring*'s build.rs asks the C compiler to assemble the code, which will use then use its assembler, gnu as for gcc, or llvm-as for clang. The version of the assembler being used is so old that it predates the public unveiling of these CPU instructions. The solution is to upgrade the toolchain, typically binutils.
