### ISSUE TITLE
Extend macro invocation without the `!` typo help suggestion for all user-defined macros

### ISSUE THREAD

**Issue by Rageking8** [rust-lang/rust#101659]
Given the following code: [link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=d7c319a7f8606ba49e50bfab044d86a6)

```rust
#![allow(unused)]
macro_rules! test {
    () => { 123 }
}

fn main() {
    let x = test();
}
```

The current output is:

```
Compiling playground v0.0.1 (/playground)
error[E0423]: expected function, found attribute macro `test`
 --> src/main.rs:7:13
  |
7 |     let x = test();
  |             ^^^^ not a function

For more information about this error, try `rustc --explain E0423`.
error: could not compile `playground` due to previous error
```

Ideally the output should contain a help note which suggests adding a `!` for macro invocation.

Note: if the above code snippet is changed slightly to (added `_` prefix to the macro name and invalid invocation name): [link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=1c6f4b964f1a5c5eb638377df8fdc957)
```rust
#![allow(unused)]
macro_rules! _test {
    () => { 123 }
}

fn main() {
    let x = _test();
}
```
The current output is:
```
Compiling playground v0.0.1 (/playground)
error[E0425]: cannot find function `_test` in this scope
  --> src/main.rs:16:13
   |
16 |     let x = _test();
   |             ^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `playground` due to previous error
```
Not sure if the different error message that arises from a slight change in the code is intentional or is even relevant in this issue's context. If you know why this is the case, please let me know. (Note: if this part is nonsensical please ignore it, I am very new to rust). Thanks a lot.

**Comment by compiler-errors** [comment]
> error[E0423]: expected function, found attribute macro `test`

This is because there's a built-in `#[test]` macro.

**Comment by Rageking8** [comment]
Oh, oops totally forget about that.

**Comment by compiler-errors** [comment]
No worries, but there should be no reason why we can't suggest a user-provided macro here (or at least nothing comes to mind, but maybe I will discover why and report back here).

**Comment by compiler-errors** [comment]
Actually might leave this to someone else, got a lot on my plate atm.

**Comment by gimbles** [comment]
@rustbot claim

Yummy.

**Comment by dbdr** [comment]
Using the current stable version 1.81, the compiler output is now:
```
 --> main.rs:7:13
  |
7 |     let x = test();
  |             ^^^^ not a function
  |
help: use `!` to invoke the macro
  |
7 |     let x = test!();
  |                 +
```
It seems to me the suggestion has been implemented and this issue could be closed.
