### ISSUE TITLE
Codegen: outlined function inhibits optimizations on arrays

### ISSUE THREAD

**Issue by Ben-Lichtman** [rust-lang/rust#101638]
I tried this code:

```rust
#![feature(bench_black_box)]

pub fn example() {
    // 2 arrays are allocated on the stack (1024 bytes)
    let mut a = [0u8; 512];
    outlined_memset(&mut a, 1);
    let a = a; // memcpy happens here
    takes_array(&a);
}

#[inline(never)]
pub fn outlined_memset(dest: &mut [u8], value: u8) {
	dest.fill(value);
}

pub fn takes_array(a: &[u8]) {
    std::hint::black_box(a);
}
```

I expected to see this happen:
The line `let a = a;` should be optimized away into nothing (or potentially even more could be optimized away).

Instead, this happened:
Space for a second array is allocated on the stack and a memcpy is used to move one array into the other despite them being identical

The memcpy goes away if the outlined function is allowed to inline, or if the line containing the move is removed.

[godbolt link](https://godbolt.org/z/MrM1o7MEx)

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0-nightly (1d37ed661 2022-09-09)
binary: rustc
commit-hash: 1d37ed661a6922e7a167609b8cd7eb31e972b19b
commit-date: 2022-09-09
host: x86_64-pc-windows-msvc
release: 1.65.0-nightly
LLVM version: 15.0.0
```

**Comment by Ben-Lichtman** [comment]
Here's a version that's slightly closer to the real-world scenario where I encountered this - I was transmuting a MaybeUninit array into an init array: https://godbolt.org/z/EKrz9nhz4

**Comment by Ben-Lichtman** [comment]
I believe that due to this, there is no way to turn a `[MaybeUninit<T>; N]` into a `[T; N]` without a memcpy?

**Comment by nikic** [comment]
The the second case (with MaybeUninit) the problem is a lifetime.start between the call and the memcpy, preventing call slot optimization. This should be relatively easy to support.

The first case is significantly harder, because there are writes to the memory before it is passed to the call, which call slot optimization currently doesn't support at all.

**Comment by nikic** [comment]
Upstream patch for the uninit case: https://reviews.llvm.org/D135886

**Comment by Ben-Lichtman** [comment]
Seems to be working in the compiler now, thanks again!
