### ISSUE TITLE
-Z gcc-ld=lld fails again

### ISSUE THREAD

**Issue by tschuett** [rust-lang/rust#101653]
I tried this code:

```console
RUSTFLAGS='-Z gcc-ld=lld' cargo +nightly build --release
```

I expected to see this happen: it builds my crate.

Instead, this happened: 

```console
 = note: rust-lld: error: library not found for -lcrt1.10.6.o
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Meta

`rustc --version --verbose`:
```console
rustc +nightly --version --verbose
rustc 1.65.0-nightly (1120c5e01 2022-09-08)
binary: rustc
commit-hash: 1120c5e01df508de64fe6642f22fadeb574afd6d
commit-date: 2022-09-08
host: x86_64-apple-darwin
release: 1.65.0-nightly
LLVM version: 15.0.0
```

I found in the invocation of `cc`

```console
nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/bin/gcc-ld" "-fuse-ld=lld" "--target=x86_64-apple-macosx10.7.0"
```

```console
> clang --version
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
> xcrun --sdk macosx --show-sdk-path
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk
> cc --print-target-triple
x86_64-apple-darwin21.6.0
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

See https://github.com/rust-lang/rust/pull/101504#issuecomment-1242726753.

**Comment by tschuett** [comment]
https://github.com/rust-lang/rust/pull/100200 introduced the target parameter

**Comment by lqd** [comment]
I managed to find an old x64 mac, Xcode 13 on OS 11.6.1, and can reproduce the issue there, so I'll try to look into it.

**Comment by tschuett** [comment]
```console
>  find /Applications/Xcode.app/Contents/Developer/Platforms -name crt1.10.6.o
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/crt1.10.6.o
```

There is a `crt1.10.6.o` file on my system, but it is not a library.

**Comment by lqd** [comment]
`nightly-2022-09-02` does not reproduce the issue, so it may be a different change from #100200 which landed in the following nightly

**Comment by lqd** [comment]
So removing the [`--target` argument](https://github.com/rust-lang/rust/blob/2287107588d92889d282e6cd3c1ca5df34cd34a5/compiler/rustc_codegen_ssa/src/back/link.rs#L2768-L2773) fixes it for me on the x64 machine: it manages to use `rust-lld` 15.0.0. 

On this osx/sdk/etc, clang does find `gcc-ld/ld64.lld` without the `--target` mentioned in https://github.com/rust-lang/rust/issues/97402#issuecomment-1147404520.

**Comment by Wyvern** [comment]
Any progress on it? Nightly build 2022-09-13 still reproduce the problem.
