### ISSUE TITLE
Edge case does not suggest changing invalid `public` with `pub`

### ISSUE THREAD

**Issue by Rageking8** [rust-lang/rust#101626]
Given the following code: [link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=30d2fb5d1b3b7cbfd0f9d377e0d0a11f)

```rust
mod test {
    public const X: i32 = 123;
}

fn main() {
    println!("{}", test::X);
}
```

The current output on stable 1.63.0:
```
   Compiling playground v0.0.1 (/playground)
error: expected one of `!` or `::`, found keyword `const`
 --> src/main.rs:2:12
  |
2 |     public const X: i32 = 123;
  |            ^^^^^ expected one of `!` or `::`

error: could not compile `playground` due to previous error
```

The current output on Beta version 1.64.0-beta.6 (2022-09-09 25912c09710a2de2a97b):
```
   Compiling playground v0.0.1 (/playground)
error: expected one of `!` or `::`, found keyword `const`
 --> src/main.rs:2:12
  |
2 |     public const X: i32 = 123;
  |            ^^^^^ expected one of `!` or `::`
  |
help: write `pub` instead of `public` to make the item public
  |
2 |     pub const X: i32 = 123;
  |     ~~~

error: could not compile `playground` due to previous error
```

The current output on Nightly version 1.65.0-nightly (2022-09-09 1d37ed661a6922e7a167):

```
   Compiling playground v0.0.1 (/playground)
error: expected one of `!` or `::`, found keyword `const`
 --> src/main.rs:2:12
  |
2 |     public const X: i32 = 123;
  |            ^^^^^ expected one of `!` or `::`

error: could not compile `playground` due to previous error
```

Since #99903 ( cc @gimbles ) is somewhat recent the help diagnostics improvement currently is only on beta. However, the latest nightly has regressions regarding the suggestion as shown above. Hence, the output should suggest changing `public` with `pub` as that is the desired output.

Note: base issue for improved diagnostics (`public` -> `pub`): #99653

Note: since this is technically a regression from beta to nightly, what should be the appropriate label to add? The one below this?
@rustbot label +regression-untriaged

**Comment by gimbles** [comment]
Can you please add the Rustc versions?

**Comment by gimbles** [comment]
[Note that I don't think this should have happened at all, I wrote tests for the changed diagnostic suggestions]

**Comment by Rageking8** [comment]
@gimbles I have retested the above code snippet against the current stable, beta and nightly version (I have added the version numbers above) of the compiler in the official rust playground and the regression still persist.

Not sure if this only occurs on the rust playground although I highly doubt it. Maybe you could look into this as the implementation of that diagnostics improvement is written by you. If you have any evidence that this regression issue is misinformed do let me know and I will happily close the issue. Thanks a lot.

**Comment by Rageking8** [comment]
> [Note that I don't think this should have happened at all, I wrote tests for the changed diagnostic suggestions]

Not sure if this is the cause but maybe the test you wrote in #99903 is slightly different to the above code snippet as the test uses the wrong `public` keyword in the top-level. However, the above code snippet uses the incorrect `public` keyword inside of a user-defined module. Hence, this may lead to a PR that potentially causes a regression in the recovery of `public` -> `pub` to not trip off a CI fail. Therefore, undetected.

That being said, all those are just my guess and it may be wrong.

@rustbot label +E-needs-bisection

**Comment by chenyukang** [comment]
This may related to my PR:
https://github.com/rust-lang/rust/pull/100188
