### ISSUE TITLE
Compute `shallow_lint_levels_on` by `LocalDefId` instead of `HirId`

### ISSUE THREAD

**Issue by cjgillot** [rust-lang/rust#101771]
Besides the great improvement on the incr-patched cases, there is a ~2 % regression on the incr-unchanged case.  I suspect this is due to the query overhead.  One possible solution would be to change the granularity of the `shallow_lint_levels_on` query to be per HIR-owner, instead of per HirId.  I'd like to leave this as a follow-up.

_Originally posted by @cjgillot in https://github.com/rust-lang/rust/issues/101620#issuecomment-1242689315_

**Comment by cameron1024** [comment]
@rustbot claim

I'd be keen to take this on. I'll have a look at the linked issue to see where to get started.

**Comment by cjgillot** [comment]
I'm sorry @cameron1024, I ended up having to do it myself in order to get the PR in a mergeable state.

**Comment by cjgillot** [comment]
But you are still welcome to look at the lint code and get it faster :smile:
