### ISSUE TITLE
Tracking Issue for `const_cstr_methods`

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#101719]
Feature gate: `#![feature(const_cstr_methods)]`

This is a tracking issue for `CStr` methods as `const` functions.

### Public API

```rust
// core::ffi

impl CStr {
    // feature(const_cstr_methods)
    pub const fn from_bytes_with_nul(bytes: &[u8]) -> Result<&Self, FromBytesWithNulError>;
    pub const fn to_bytes(&self) -> &[u8];
    pub const fn to_bytes_with_nul(&self) -> &[u8];
    pub const fn to_str(&self) -> Result<&str, str::Utf8Error>;
}

// Note that those methods are stable, they are only unstable as `const` fn
```

### Steps / History

- [x] Implementation: #100291
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by tgross35** [comment]
@WaffleLapkin are any of these uncontroversial enough that you'd be comfortable const stabilizing them?

For https://github.com/rust-lang/rust/pull/107429 I had to mark some of the memchr functions const stable, and the methods here largely have the same const dependencies. So, at least a subset of these could probably go const stable in the same release.

**Comment by WaffleLapkin** [comment]
@tgross35 I personally think that all of these are uncontroversial and I'd be very comfortable stabilizing them, however I do not posses the power to do so. Stabilizing library APIs is a prerogative of `T-libs-api`.

**Comment by tgross35** [comment]
Alright, I've opened  #107624

**Comment by tgross35** [comment]
@WaffleLapkin I think you can close this tracking issue if you would like, since #107624 merged. `CStr::from_ptr` was under this gate (I don't see it in this description) but moved to `const_cstr_from_ptr` with the merge, and I opened a new issue to track that #113219
