### ISSUE TITLE
The doc contents are incorrectly made bold under certain situation

### ISSUE THREAD

**Issue by cmpute** [rust-lang/rust#101743]
### Problem

This bug happens when an associated constant is generated from a generic const function. The brackets surrounding the generic parameters are interpreted as an HTML tag.

### Steps

If the documentation is like this in the code:
```rust
impl<const A: Word> Repr<A> {
    /// The base of the representation. It's exposed as an [IBig] constant.
    pub const BASE: IBig = base_as_ibig::<A>();
}
```
The documentation looks like:
![Snipaste_2022-09-12_20-17-34](https://user-images.githubusercontent.com/9154441/189780607-17d8259c-83c0-4bda-9d19-d174ef93aa1d.png)
(the text becomes a link)

<hr/>

If the documentation is
```rust
impl<const B: Word> Repr<B> {
    /// The base of the representation. It's exposed as an [IBig] constant.
    pub const BASE: IBig = base_as_ibig::<B>();

    /// Create a [Repr] instance representing value zero
    pub const fn zero() -> Self { todo!() }
}
```

The documentation looks like 
![Snipaste_2022-09-12_20-15-21](https://user-images.githubusercontent.com/9154441/189780330-5f290c85-341a-4094-ad85-8149dda45a96.png)

(it even affects the documentation of other items in the same page

### Possible Solution(s)

The generic brackets should be escaped

### Version

```text
cargo 1.63.0 (fd9c4297c 2022-07-01)
release: 1.63.0
commit-hash: fd9c4297ccbee36d39e9a79067edab0b614edb5a
commit-date: 2022-07-01
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1n)
os: Ubuntu 20.04 (focal) [64-bit]
```

**Comment by ehuss** [comment]
Transferred to rust-lang/rust as that is where rustdoc issues are tracked.

**Comment by aDotInTheVoid** [comment]
@cmpute I cannot reproduce, can you post the definition of Word, Repr, etc..

---

When I try

```rust
pub type Word = usize;
pub struct Repr<const B: usize>([i32; B]);
pub struct IBig(usize);

pub const fn base_as_ibig<const B: Word>() -> IBig {
    IBig(B)
}

impl<const B: Word> Repr<B> {
    /// The base of the representation. It's exposed as an [IBig] constant.
    pub const BASE: IBig = base_as_ibig::<B>();

    /// Create a [Repr] instance representing value zero
    pub const fn zero() -> Self { todo!() }
}
```

I get

![image](https://user-images.githubusercontent.com/28781354/190207749-2518c8d0-fcb9-47fd-b3d4-ba195b376717.png)

Which looks correct.

It's also possible that I'm on a more recent version of rustdoc, and that this has been fixed, and needs a test

```rust
rustdoc 1.65.0-nightly (1120c5e01 2022-09-08)
binary: rustdoc
commit-hash: 1120c5e01df508de64fe6642f22fadeb574afd6d
commit-date: 2022-09-08
host: x86_64-unknown-linux-gnu
release: 1.65.0-nightly
LLVM version: 15.0.0
```

**Comment by cmpute** [comment]
I tried to use nightly locally and get the same result as yours. Thanks!

Notice that your rendering output for `BASE` is 

```rust
pub const BASE: IBig = _
```

rather than my rendering:
```rust
pub const BASE: IBig = base_as_ibig::()
```

This actually avoid the problem of parsing the generic parameters `<B>` as HTML tag, so I think it's fixed in the latest version.
