### ISSUE TITLE
missing `generic_associated_types` stabilisation version?

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#101766]
```rust
#![feature(generic_associated_types)]
pub fn main() {}
````
with rustc master `rustc 1.65.0-nightly (5338f5f1d 2022-09-13)`

````
warning: the feature `generic_associated_types` has been stable since CURRENT_RUSTC_VERSION and no longer requires an attribute to enable
 --> f.rs:1:12
  |
1 | #![feature(generic_associated_types)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(stable_features)]` on by default

warning: 1 warning emitted
````
looks like the stabilisation version is borked? :sweat_smile: 
cc @jackh726

**Comment by matthiaskrgr** [comment]
Hm, it actually says it like this in the code :D
https://github.com/rust-lang/rust/pull/96709/files#diff-307e0d3a2037c11a3fa16822fbaa0fec08e57ac7d0d6e7354f6005c9482a9e26R165

**Comment by jackh726** [comment]
This is correct, but not ideal: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#updating-the-feature-gate-listing

cc @est31 maybe we want to special case this in the diagnostics

**Comment by est31** [comment]
Yeah seems I've missed correcting that lint. For GATs, the stabilization version will be adjusted very soon, in the coming days, as we are close to the release cycle. But this needs to be fixed for future stabilizations as well. Working on a PR. @rustbot label bug

**Comment by est31** [comment]
Yeah it warns correctly for lib features so only lang features are affected:

```
warning: the feature `io_read_to_string` has been stable since 1.65.0-nightly and no longer requires an attribute to enable
 --> src/main.rs:1:12
  |
1 | #![feature(io_read_to_string)]
  |            ^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(stable_features)]` on by default
```

**Comment by est31** [comment]
PR filed: #101772
