### ISSUE TITLE
Wrong dead code warning

### ISSUE THREAD

**Issue by tanchihpin0517** [rust-lang/rust#101704]
I got dead_code warning but I'm sure that code was used.
Here is some snippets of my code: 

lib.rs:
```rust
// ------------- snip ------------

pub struct MyEnv {
    pub config: Rc<Config>,
    components: Vec<Box<dyn Component>>,
}

impl MyEnv {
    pub fn new(config: Config) -> MyEnv {
        Self::init(&config);
        let mut env = MyEnv {
            config: Rc::new(config),
            components: Vec::new(),
        };
        env.components
            .push(Box::new(Python::new(Rc::clone(&env.config))));  // HERE IS DEAD CODE !!!
        env
    }
    
    // ----------- snip --------------
}
```

python.rs:
```rust
// --------- snip ----------

impl Python {
    pub fn new(config: Rc<Config>) -> Python {
        Python { config }
    }
    
    // ----------- snip -----------
}
```

The building message from calling `cargo build`:
```
➜ cargo build
   Compiling myenv v0.1.0 (/Users/tanch/workspace/myenv)
warning: associated function `new` is never used
  --> src/component/python.rs:27:12
   |
27 |     pub fn new(config: Rc<Config>) -> Python {
   |            ^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `myenv` (bin "myenv") generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 1.19s
```

Apparently Python::new is used in lib.rs, but the compiler report that as dead_code.
(If I remove Python::new, the compiling won't pass)
I guess it's a bug.

**Comment by BGR360** [comment]
Can you please link to the repository or post a new one that contains the code that gives the warning, or make a [playground](play.rust-lang.org) example that shows the warning? The snippets you gave aren't really enough for anybody to reproduce the issue.

**Comment by tanchihpin0517** [comment]
Sorry for unclear report. Here is the repository for reproduction: https://github.com/tanchihpin0517/rust_issue_report

**Comment by BGR360** [comment]
Figured it out. You've got `mod component` in both `lib.rs` and `main.rs`. So although you use `Python::new` in the `myenv` library crate, you don't use the one defined in the `component` module in the `myenv` binary crate.

**Comment by tanchihpin0517** [comment]
OH, I See! Thanks for your explanation!

**Comment by BGR360** [comment]
Wow, looks like someone had the same problem two weeks ago! https://github.com/rust-lang/rust/issues/101164
