### ISSUE TITLE
"TRUE" does not parse into boolean

### ISSUE THREAD

**Issue by djensen1997** [rust-lang/rust#101870]
# Summary of the issue

When taking input into my program, I ran into a situation where the user would pass "TRUE" into a field that I was attempting to use the .parse() method into a boolean:
```rust
fn input(value: &str) -> Result<(), MyErrorType> {
  let new_val: bool = value.parse().map_err(|_| MyErrorType{})?;
  Ok(())
}
```

when I split this specific line of code into a fresh rust project:

```rust
fn main() {
    let x: bool = "TRUE".parse().expect("NOPE");
}
```
I got the output:
```thread 'main' panicked at 'NOPE: ParseBoolError', src/main.rs:20:34```

## What I expect to happen

I would expect rust to see the string value "TRUE" and read that as a boolean with the value `true`

## What actually happens

I am getting an error return with `MyErrorType`

**Comment by CollinEMac** [comment]
It looks like Rust properly parses "true" and "false" in lowercase to a boolean but not the capitalized "TRUE" or "FALSE".

This is documented here:
https://doc.rust-lang.org/std/primitive.bool.html#examples-16

**Comment by Nilstrieb** [comment]
It's not clearly documented what exactly is and is not supposed to be parsed, but I think that the current behaviour of only parsing `true` and `false` is the best solution here, and changing the behaviour of functions like this is generally a breaking change.

For comparison, here's what a few other languages do:
- [Java](https://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html#parseBoolean(java.lang.String)): ignores case
- [Swift](https://developer.apple.com/documentation/swift/bool/init(_:)-83vgw): only `true` and `false`
- [Javascript (`JSON.parse`)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse): only `true` and `false`
- [Go](https://pkg.go.dev/strconv#ParseBool): accepts `1`, `t`, `T`, `TRUE`, `true`, `True`, `0`, `f`, `F`, `FALSE`, `false`, `False`.

**Comment by GuillaumeGomez** [comment]
I opened https://github.com/rust-lang/rust/pull/102094 which should fix this issue.
