### ISSUE TITLE
Generic unsafe traits require bounding that already exists

### ISSUE THREAD

**Issue by Threadzless** [rust-lang/rust#101879]
I tried this code:

```rust
pub struct Foo<'a, W>
where
    W: raw_window_handle::HasRawWindowHandle
{
    bar: &'a W,
}

impl<'a, W> Foo<'a, W>
where
    W: raw_window_handle::HasRawWindowHandle
{
    pub fn new(foobar: &'a W) -> Self {
        Self { bar: foobar }
    }

    pub fn use_instance( self ) -> Result<wgpu::Surface, ()> {
        let instance = wgpu::Instance::new(wgpu::Backends::GL);
        let surface = unsafe { instance.create_surface(self.bar) };
        Ok(surface)
    }
}
```

I expected this to compile, but cargo emits error E0277:

```
error[E0277]: the trait bound `W: raw_window_handle::HasRawWindowHandle` is not satisfied
    --> src/lib.rs:18:56
     |
18   |         let surface = unsafe { instance.create_surface(self.bar) };
     |                                         -------------- ^^^^^^^^ the trait `raw_window_handle::HasRawWindowHandle` is not implemented for `W`
     |                                         |
     |                                         required by a bound introduced by this call
     |
note: required by a bound in `wgpu::Instance::create_surface`
    --> /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.13.1/src/lib.rs:1757:37
     |
1757 |     pub unsafe fn create_surface<W: raw_window_handle::HasRawWindowHandle>(
     |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `wgpu::Instance::create_surface`
help: consider further restricting this bound
     |
10   |     W: raw_window_handle::HasRawWindowHandle + raw_window_handle::HasRawWindowHandle
     |                                              +++++++++++++++++++++++++++++++++++++++
```

Since the compiler is telling me to add a bound that is already present, I assume at the very least this is not the correct error message for my code. 

What I find to be notable is that this only happens under these conditions:
- Passing a generic reference of an unsafe trait (`raw_window_handle::HasRawWindowHandle`)...
- ...Into an unsafe method (`create_surface`)
- Where both the trait and method exist in separate crates from the one my code is in.

When any of these conditions were not true, no error is emitted.

### Meta
The nightly compiler produces the same error for this code

`rustc --version --verbose`:
```
rustc 1.63.0 (4b91a6ea7 2022-08-08)
binary: rustc
commit-hash: 4b91a6ea7258a947e59c6522cd5898e7c0a6a88f
commit-date: 2022-08-08
host: x86_64-unknown-linux-gnu
release: 1.63.0
LLVM version: 14.0.5
```

**Comment by Threadzless** [comment]
here are my cargo dependencies, just in case its relevant:
```rust
wgpu = "*"
raw-window-handle = "0.3.0"
```

**Comment by veber-alex** [comment]
I believe the problem here is that your crate uses version 0.3.0 of `raw-window-handle` while `wgpu` uses 0.4.0.
The compiler treats those as different crates so the bound wgpu has is really not satisfied with the constraint on your type.

It would be nice if the compiler could detect that something weird is going on and give a better error message.

**Comment by Threadzless** [comment]
@veber-alex that was indeed the issue, and changing it got rid of the error.

Hopefully a more useful error message can be added to future versions of rust, as I would never have figured this out on my own
