### ISSUE TITLE
overlong bit shifts cause undefined behaviour

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#10183]
```rust
1 >> 24353125315
```

**Comment by ruud-v-a** [comment]
Currently, the following code panics in debug mode but runs fine in release mode:

```rust
fn main() {
    let sh = 32;
    assert_eq!(0, 1_i32 << sh);
}
```
(Or [try it in the playpen](http://is.gd/EUgzLD).)

I am not sure whether this is by design or whether it is a bug, but either way, the documentation of `shl` nor the documentation of `i32` mentions this behaviour.

**Comment by steveklabnik** [comment]
The overflow RFC addresses this, and I have a bug open to reconcile all RFCs with the reference, so this will be taken care of as part of that.

**Comment by thestinger** [comment]
This is a memory safety hole in the implementation. It's an issue regardless of how the language is *intended* to work per RFCs...

**Comment by srh** [comment]
@steveklabnik How does the overflow RFC address this?

**Comment by steveklabnik** [comment]
Sorry, by 'address' I mean a decision was made, and I'll be documenting the result. Not that it's any different than today.

**Comment by thestinger** [comment]
This bug isn't asking for a change in semantics, it's filed to cover a known memory safety hole in the language. The fact that a clear solution has been specified doesn't mean the bug is fixed... pretending memory safety holes don't exist in the implementation doesn't make them go away.

**Comment by Gankro** [comment]
Agreed this issue should not be closed until UB in safe Rust does not occur.

**Comment by ben0x539** [comment]
I don't think the RFC addresses this issue at all. Under "unresolved questions", it lists "shifts by an excessive number of bits". It just proposes debug assertions and doesn't prevent undefined behavior in release builds.

**Comment by pnkfelix** [comment]
Here is a variant of @ruud-v-a 's example that assert fails (in different places) in both debug and release mode.  (It was adapted from #23551.)

```rust
fn id<T>(x: T) -> T { x }

fn main() {
    let sh = 32;
    assert_eq!(0, 1_i32 << sh);
    assert_eq!(0, 1_i32 << id(sh));
}
```

[playpen](http://is.gd/y6KT9x)

**Comment by pnkfelix** [comment]
@ben0x539 I believe the intent of the RFC is to ensure that the fallback behaviors, when reasonable, do not expose undefined behavior from LLVM.

In these cases, it seems like the fallbacks should simply mask-out the higher order bits as appropriate for each type.
