### ISSUE TITLE
integer to floating point casts can cause undefined behaviour

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#10185]
> If the value cannot fit in the floating point value, the results are undefined.

``` rust
-1u64 as f32
```

**Comment by Gankro** [comment]
I have confirmed on IRC that the intent is that it's UB only if the value is bigger than the *biggest* finite value. So this is actually not a problem in Rust unless we introduce `u128` (which can be bigger than f32's biggest finite)  or `f16`. (i128 is *still* too small)

**Comment by jonas-schievink** [comment]
> unless we introduce `u128`

This has now happened

**Comment by Gankro** [comment]
Sad

**Comment by nagisa** [comment]
We *already* have an issue for this (https://github.com/rust-lang/rust/issues/41799) which also has some code to reproduce the issue. Re-closing this as duplicate.
