### ISSUE TITLE
Tracking Issue for `feature(const_fn_trait_ref_impls)`

### ISSUE THREAD

**Issue by onestacked** [rust-lang/rust#101803]
Feature gate: `#![feature(const_fn_trait_ref_impls)]`

This is a tracking issue for the implementation of const Fn* on references of const Fn* Items.

### Public API

```rust
impl<A, F: ?Sized> const Fn*<A> for &(mut) F
    where
        F: ~const Fn*<A>;
```

### Steps / History

- [x] Implementation: #101802
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by raldone01** [comment]
This feature is awesome.
However I noticed that it works without using the feature gate at all.
I create a minimal repo to reproduce:
https://github.com/raldone01/const_fn_trait_ref_impls_feature_gate_not_required_question_mark

**Comment by fee1-dead** [comment]
These feature gates do not actually matter, as they will be insta-stable after const_trait_impl gets stable. As long as you are not able to use this without having const_trait_impl enabled, it is fine.

**Comment by RalfJung** [comment]
This got removed in https://github.com/rust-lang/rust/pull/110393
