### ISSUE TITLE
rustdoc: display problem for tooltip on error index page

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#101919]
Steps to reproduce (Chrome on Linux):

1. Visit https://doc.rust-lang.org/nightly/error_codes/E0283.html
2. Hover the (i) icon.

Results:

![image](https://user-images.githubusercontent.com/220205/190733995-54e966f3-d62e-48df-8e49-3f1601651d4d.png)

There is a little spur of black hanging below the tooltip.

cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Thanks! I'll take a look tomorrow.
