### ISSUE TITLE
Scoped threads violate 'dereferenceable for function call' requirement of references

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#101983]
Scopes threads as currently implemented are potentially unsound due to passing a reference to a function where the memory the reference points to is potentially deallocated while the function still runs.

Specifically, [this main function here](https://github.com/rust-lang/rust/blob/d13699d0be14c47e57d1c8961d7e7348d93017fc/library/std/src/thread/mod.rs#L502) takes as implicit argument its closure environment, which contains `f`. That environment might just be a reference to some memory that is allocated in the caller stack frame. However the `main` function can keep running after `their_packet` got dropped (implicitly at the end of `main`). Then the scope might end and the memory might be deallocated all while `main` is still running. If the environment is just a reference, it ends up being a newtype and we will (AFAIK) add the `dereferenceable` attribute, meaning deallocation while the function runs is actually LLVM UB.

Miri found the error in [this doc test](https://doc.rust-lang.org/nightly/std/thread/fn.scope.html), where the `a.push(4)` invalidates the `&a` reference that was passed to the forked-off threads. (`a` doesn't actually get deallocated, it just has a unique reference created to it, but deallocation is also a possibility).

To fix this properly, I think we need a language extension: we want a way to store references in a type *without* having alias guarantees for that reference. In terms of Stacked Borrows this means Stacked Borrows will stop recursing at that type during retags. In terms of the LLVM IR we generate it means we must not add `noalias` or `dereferenceable` attributes for references inside that type. We don't have such a type currently but I think it makes sense to make `ManuallyDrop` that type (or even if we add a new type for this, `ManuallyDrop` should use it). Also see [this Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/Generalizing.20MaybeUninit.2FManuallyDrop).

**Comment by thomcc** [comment]
I believe https://github.com/rust-lang/rust/pull/98517 included a fix for this.

**Comment by RalfJung** [comment]
Doesn't look like it -- the user-provided closure seems to be handled exactly the same as currently?

**Comment by thomcc** [comment]
Ah, I read too quickly and misunderstood, apologies. It solves a different potential unsoundness (one more similar to the Arc drop issue).

**Comment by RalfJung** [comment]
Yeah, it looks like an alternative fix for the `dereferenceable` part of https://github.com/rust-lang/rust/issues/98498.

**Comment by RalfJung** [comment]
While the [RFC for a proper fix is cooking](https://rust-lang.zulipchat.com/#narrow/stream/136281-t-lang.2Fwg-unsafe-code-guidelines/topic/manually_drop_maybe_dangling), I am proposing a preliminary fix in https://github.com/rust-lang/rust/pull/102589.
