### ISSUE TITLE
MSI installer is missing clippy and rustfmt

### ISSUE THREAD

**Issue by Hawk777** [rust-lang/rust#101993]
I installed Rust 1.63.0 in Windows via the MSI installer. I enabled all optional features during the installation process. However, it seems that `clippy` and `rustfmt` are not available via the MSI installer. It seems that the MSI installer is oriented at development use and not just building existing Rust code from source for deployment (otherwise it wouldn’t include RLS, which is only useful for development), so there ought to be a way to get access to `clippy` and `rustfmt` through it—and one can’t just `cargo install` them, at least not `clippy`, because `cargo install clippy` reports that `clippy` is no longer available via `crates.io`.

Sorry if this is the wrong repo to report MSI installer issues; with 190 repos in the group, it can be hard to find the right one.

**Comment by jyn514** [comment]
Hmm, there's code for clippy in `dist.rs` - not sure what's going wrong there, someone would need to investigate. https://github.com/rust-lang/rust/blob/ed3711120500157d7ad93613266e665b0d41b69a/src/bootstrap/dist.rs#L1617-L1633

Rustfmt does appear to just be omitted altogether, that should be a simple fix.

**Comment by chenyukang** [comment]
I see `rustfmt` is not called with `prepare`, but `clippy` is there:

```rust
prepare("clippy");
            for tool in &["rust-demangler", "rust-analyzer", "miri"] {
                if built_tools.contains(tool) {
                    prepare(tool);
                }
            }
            if target.ends_with("windows-gnu") {
                prepare("rust-mingw");
            }
```

**Comment by chenyukang** [comment]
have a diff from `cargo --list` between `rustup` from installation and MSI installer:

```diff
9d8
<     clippy               Checks a package to catch common mistakes and improve your Rust code.
15d13
<     fmt                  Formats all bin and lib files of the current crate using rustfmt.
25d22
<     miri
46a44
>
```

seems `miri` also missing.

**Comment by Hawk777** [comment]
Here’s a list of the files in the `bin/` subdirectory of my install directory, in case it’s relevant:
- `cargo.exe`
- `rls.exe`
- `rustc_driver-17b2400b2defcd83.dll`
- `rustc_driver-17b2400b2defcd83.pdb`
- `rustc.exe`
- `rustc_main-6addbff947989b19.pdb`
- `rustdoc.exe`
- `rust-windbg.cmd`
- `std-2e5a4fde2066d4f2.dll`
- `std-2e5a4fde2066d4f2.pdb`
- `test-2fc9b45aeebba85a.dll`
- `test-2fc9b45aeebba85a.pdb`
