### ISSUE TITLE
Optimize for energy or memory

### ISSUE THREAD

**Issue by Rudxain** [rust-lang/rust#101974]
`rustc` can only optimize for speed (time) or binary storage use, but there's no option (AFAIK) to optimize for energy or main-memory use.

Related:
- https://www.embecosm.com/services/energy-efficient-compilation
- https://github.com/llvm/llvm-project/issues/6582

**Comment by workingjubilee** [comment]
Per what Chris Lattner said:

> Almost all computer literature shows that the best way to save power (on mainstream cpus that don't have super crazy power features) is to execute code faster so that the chip can enter a low power state sooner. Faster = lower power.

If you have research that shows otherwise, I recommend starting a discussion on https://internals.rust-lang.org/

**Comment by Rudxain** [comment]
@workingjubilee The article I linked explains that some memory alignments reduces the switching frequency of transistors, therefore reducing energy use, but not necessarily being faster.

And this issue is also about memory optimization, not just energy. I know that in the majority of cases, optimizing for storage size also reduces memory footprint, but that isn't always the case
