### ISSUE TITLE
Papercut: Suggest `Default::default()` when binding isn't initialized

### ISSUE THREAD

**Issue by Patryk27** [rust-lang/rust#102087]
Given the following code:

```rust
fn main() {
    let foo: Vec<&str>;
    
    foo.push("hi!");
}
```

([playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=f14000e6c56b494f9a17aa3a1dc23b3f))

... the current output is:

```
error[E0381]: used binding `foo` isn't initialized
 --> src/main.rs:4:5
  |
2 |     let foo: Vec<&str>;
  |         --- binding declared here but left uninitialized
3 |     
4 |     foo.push("hi!");
  |     ^^^^^^^^^^^^^^^ `foo` used here but it isn't initialized
```

While this message is correct,  people (especially beginners) stumbling upon it sometimes still don't know what to do (e.g. they expect `let var: ty;` to automatically initialize `var` to `Default::default()`, as is the case in some languages).

Maybe we could extend the message to say:

```
error[E0381]: used binding `foo` isn't initialized
 --> src/main.rs:4:5
  |
2 |     let foo: Vec<&str>;
  |         --- binding declared here but left uninitialized
3 |     
4 |     foo.push("hi!");
  |     ^^^^^^^^^^^^^^^ `foo` used here but it isn't initialized
  |
help: use `=` to assign some value to `foo`
  |
2 |     let foo: Vec<&str> = something;
  |                          ~~~~~~~~~
```
... with an extra case that if `ty` is `Default`:
```
help: use `=` to assign default value to `foo`
  |
2 |     let foo: Vec<&str> = Default::default();
  |                          ~~~~~~~~~~~~~~~~~~
```

**Comment by edward-shen** [comment]
Maybe it's better to suggest `ty::default()` instead of `Default::default()`? A beginner may be confused why you can "assign" `Default` to a `ty`.

**Comment by cassaundra** [comment]
> Maybe it's better to suggest `ty::default()` instead of `Default::default()`? A beginner may be confused why you can "assign" `Default` to a `ty`.

Agree. I'm also unsure whether `Default::default` or even `ty::default` is idiomatic often enough to be worth suggesting. I'd generally rather see a specific constructor method is one in provided in most Rust code as it's more descriptive, but obviously this isn't something we can really know about on the compiler level.

**Comment by Patryk27** [comment]
> Maybe it's better to suggest `ty::default()` instead of `Default::default()`? A beginner may be confused why you can "assign" `Default` to a `ty`.

Sure, that's also nice, I think 🙂 

> but obviously this isn't something we can really know about on the compiler level. 

We kinda-sorta can, right? I think it should be possible to:
- suggest `= vec![];` if type is `Vec`,
- suggest `= Ty::default();` if type is `: Default`,
- suggest `= something` otherwise.
