### ISSUE TITLE
relating projection substs is unsound during coherence

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#102048]
```rust
// This must fail coherence.
//
// Getting this to pass was fairly difficult, so here's an explanation
// of what's happening:
//
// Normalizing projections currently tries to replace them with inference variables
// while emitting a nested `Projection` obligation. This cannot be done if the projection
// has bound variables which is the case here.
//
// So the projections stay until after normalization. When unifying two projections we
// currently treat them as if they are injective, so we **incorrectly** unify their
// substs. This means that coherence for the two impls ends up unifying `?T` and `?U`
// as it tries to unify `<?T as WithAssoc1<'a>>::Assoc` with `<?U as WithAssoc1<'a>>::Assoc`.
//
// `impl1` therefore has the projection `<?T as WithAssoc2<'a>>::Assoc` and we have the
// assumption `?T: for<'a> WithAssoc2<'a, Assoc = i32>` in the `param_env`, so we normalize
// that to `i32`. We then try to unify `i32` from `impl1` with `u32` from `impl2` which fails,
// causing coherence to consider these two impls distinct.
pub trait Trait<T> {}

pub trait WithAssoc1<'a> {
    type Assoc;
}
pub trait WithAssoc2<'a> {
    type Assoc;
}

// impl 1
impl<T, U> Trait<for<'a> fn(<T as WithAssoc1<'a>>::Assoc, <U as WithAssoc2<'a>>::Assoc)> for (T, U)
where
    T: for<'a> WithAssoc1<'a> + for<'a> WithAssoc2<'a, Assoc = i32>,
    U: for<'a> WithAssoc2<'a>,
{
}

// impl 2
impl<T, U> Trait<for<'a> fn(<U as WithAssoc1<'a>>::Assoc, u32)> for (T, U) where
    U: for<'a> WithAssoc1<'a>
{
}
```
this currently compiles even though the following crate would mean that both impls overlap:
```rust
extern crate test1;
use test1::*;

struct Ty1;
struct Ty2;

impl WithAssoc1<'_> for Ty1 {
    type Assoc = ();
}
impl WithAssoc2<'_> for Ty1 {
    type Assoc = i32;
}
impl WithAssoc1<'_> for Ty2 {
    type Assoc = ();
}
impl WithAssoc2<'_> for Ty2 {
    type Assoc = u32;
}

fn foo<T, U>()
where
    (T, U): Trait<for<'a> fn((), u32)>,
{
}

fn main() {
    foo::<Ty1, Ty2>();
}
```
however, it seems like rustc generally has issues with both of these impls, so it actually believes that none of these impls apply :grin: see also #102047 where the first impl results in an ICE.

**Comment by lcnr** [comment]
cc @rust-lang/types

**Comment by BoxyUwU** [comment]
#96912 fixes this but it'll be a while before it can be merged

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23102048.20relating.20projection.20substs.20is.20unsound.20during.20cohere.E2.80.A6)).

@rustbot label -I-prioritize +P-medium

**Comment by lcnr** [comment]
This is also wrong if only region arguments differ:
```rust
trait Trait<T> {}

trait WithAssoc<'a> {
    type Assoc;
}

impl<T: for<'a> WithAssoc<'a>> Trait<T> for for<'a> fn(<T as WithAssoc<'a>>::Assoc) {}

impl<'a, T: WithAssoc<'a>> Trait<T> for fn(<T as WithAssoc<'a>>::Assoc) {}
```

**Comment by lcnr** [comment]
what happened here? cc @rust-lang/infra @lnicola it looks like this got closed by a repeated auto merge or sth? The PR closing this issue has been reverted 🤔

**Comment by kennytm** [comment]
@lcnr  3 weeks ago this issue was closed by commit 17b322fa69eed7216dccc9f097eb68237cf62234 of #121848. The commit message contains the magic phrase "fixes #xxxx":

> ...
>
> \#\#\#\# Structurally relating aliases containing bound vars
>
> **Fixes \#102048**. In the existing solver relating ambiguous projections containing bound variables is structural. ...

So after the PR is merged this issue is closed. 



Then, 30 minutes ago, the rust-analyzer repo synchronized commits from the rust repo in rust-lang/rust-analyzer#18183, and the above #121848 PR got included as rust-lang/rust-analyzer@0fba741cafa1243d6c6edb2623340423ca4b2396. 

Since `@bors` has privilege on both repositories, GitHub somehow considers merging rust-lang/rust-analyzer@0fba741cafa1243d6c6edb2623340423ca4b2396 means this issue is fixed and thus closing the issue.

**Comment by lnicola** [comment]
Yeah, sorry, I don't know if we can avoid those, https://github.com/josh-project/josh/issues/1328.

CC @RalfJung are you doing anything special to prevent bors from closing issues left and right?

**Comment by RalfJung** [comment]
We didn't have trouble with bors closing issues yet. But that may be because Miri's issue numbers are still in the 4 digit range.

**Comment by lnicola** [comment]
This wasn't a conflict with the r-a issue numbers, it was a rust-lang/rust issue that was closed, reopened, then closed by bors because of a merge commit into r-a.

**Comment by RalfJung** [comment]
Ah, yeah that happens every now and then also when people with "close" permissions push these kinds of PRs to their forks, or things like that. It's quite annoying but not unique to josh.

IMO ideally github would entirely ignore commit messages and only look at PR descriptions, since we anyway have a PR-only workflow.

**Comment by saethlin** [comment]
Ugh, this again. Maybe I should just change my workflow so this stops happening.
