### ISSUE TITLE
rustdoc: allow fully-local favicons and logos

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#102083]
@Nemo157 pointed out at https://github.com/rust-lang/docs.rs/issues/1853#issuecomment-1252979026 that rustdoc offers two attributes, html_logo_url, and html_favicon_url, which are commonly used to embed image tags pointing to URLs on a different site than the documentation is served on:

https://doc.rust-lang.org/rustdoc/write-documentation/the-doc-attribute.html#html_logo_url
https://doc.rust-lang.org/rustdoc/write-documentation/the-doc-attribute.html#html_favicon_url

For reasons of privacy, performance, and offline access, it would be nice if this attribute could point at a file shipped with the crate itself, and copied from there into the documentation.

Proposal: if one of these attributes contains a URL that does not start with `http:`, `https:` or `/`, rustdoc should treat it as a file path relative to the crate root. Rustdoc should copy that file into the doc directory, and generate documentation that references the local file for the logo/favicon.

One downside: this means every download of the crate source for builds also has to download the logo and favicon, which are only needed for documentation.

**Comment by GuillaumeGomez** [comment]
I think this is a duplicate of https://github.com/rust-lang/rust/issues/79254 and of https://github.com/rust-lang/rust/issues/32104.

**Comment by jsha** [comment]
Indeed! Closing in favor of those.
