### ISSUE TITLE
Recover from `impl Trait` in type param bound

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#102182]
When writing `fn foo<T: impl Trait>() {}` the current error is "expected one of these tokens", without any attempt to recover the parse. It should instead be closer to:

```
error[E0404]: expected trait, found struct `S`
 --> src/lib.rs:2:11
  |
2 | fn foo<T: S>() {}
  |           ^ not a trait
```

**Comment by chenyukang** [comment]
What do you expect the suggestion from this code?

```rust
error: expected one of `(`, `+`, `,`, `::`, `<`, `=`, or `>`, found `test`
 --> bug2.rs:3:17
  |
3 | fn foo<T: hello test>() {}
  |                 ^^^^ expected one of 7 possible tokens

error: aborting due to previous error
```

here `hello` is a valid identifier, "expected one of these tokens" comes when the second identifier comes.

**Comment by estebank** [comment]
I think this case should remain as is. `impl Trait` in particular is a shame because it is a valid type for the parser, but not a valid trait, and newcomers might not yet have a mental model for the distinction. I would say, when parsing a trait, if it can't be parsed, then try to parse a type in a snapshot (like we do in other parts of the parser), and if successful, emit a targeted error (trait expected but found `{descr}` type).
