### ISSUE TITLE
`Iterator` has `#[must_use]` but `ExactSizeIterator` does not

### ISSUE THREAD

**Issue by Rua** [rust-lang/rust#102183]
When returning an iterator of an unspecified type, I like to return `impl ExactSizeIterator` when I know that the type I'm returning always implements that trait. That gives the caller more options. But I noticed that while the regular `Iterator` trait has the `#[must_use]` attribute, the `ExactSizeIterator` trait does not. This means that the caller isn't warned about ignoring the return value when they call my function. This seems like an odd oversight, so the attribute should probably be added?

The same seems to apply to other more specific iterator traits, like `DoubleEndedIterator` and `FusedIterator`.

**Comment by compiler-errors** [comment]
Probably could also achieve this by triggering `unused_must_use` on any `impl Trait` whose supertrait has `#[must_use]`. Might need lang team sign-off.
