### ISSUE TITLE
Rustdoc makes trait bounds with associated types overly verbose

### ISSUE THREAD

**Issue by JoJoJet** [rust-lang/rust#102142]
### Location

https://doc.rust-lang.org/std/future/trait.IntoFuture.html

https://doc.rust-lang.org/std/iter/trait.IntoIterator.html

### Summary

The definition of the `IntoFuture` trait looks like:

```rust
pub trait IntoFuture {
    type Output;
    type IntoFuture: Future<Output = Self::Output>;
    fn into_future(self) -> Self::IntoFuture;
}
```

Rustdoc renders this as:

```rust
pub trait IntoFuture {
    type Output;
    type IntoFuture: Future
    where
        <Self::IntoFuture as Future>::Output == Self::Output;
    fn into_future(self) -> Self::IntoFuture;
}
```

This makes the trait bound for the `IntoFuture` associated type verbose and cryptic.

**Comment by fmease** [comment]
I did a quick investigation: This reproduces on stable and nightly but only if the corresponding trait comes from an extern crate (which is the case with `std` & `core`). Thus marking this issue as
@rustbot label A-cross-crate-reexports

Minimal reproducer:

```rust
// rustc one.rs --crate-type=lib
pub trait IntoFuture {
    type Output;
    type IntoFuture: Future<Output = Self::Output>;
    fn into_future(self) -> Self::IntoFuture;
}
```

```rust
// rustdoc two.rs --extern=one=libone.rlib --edition=2021
pub use one::IntoFuture;
```

**Comment by fmease** [comment]
Highly related to / “duplicate” of #84579 although the latter is quite outdated.
