### ISSUE TITLE
rustc-driver binary is not identical for every build

### ISSUE THREAD

**Issue by sundeep-kokkonda** [rust-lang/rust#102299]
The rust build output _[[build-dir]]/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-67046b4f71f47f00.so_ is not identical for every build. I debugged the issue by comparing all the generated object files between two different builds, the object file '_[[build-dir]]/bootstrap/debug/incremental/bootstrap-22qjf7qknjduo/s-gdrx5ab0wu-1spyacv-3unuz3kev23rs/4oqq7pii1co5y8sx.o_' is different between two builds. This object file _.rodata_ section is holding the filename with path, and when the path is changed this section is getting chaged and causing final .so file to be changed.

**Below is the contents of _.rodata_ section from two build directories.**

1)
.rodata section in build directory : _build-1_
:~/rust/build-1$ objdump -s -j .rodata..L__unnamed_34 ~/rust/build-1/bootstrap/debug/incremental/bootstrap-22qjf7qknjduo/s-gdrx5ab0wu-1spyacv-3unuz3kev23rs/4oqq7pii1co5y8sx.o

/home/skokkonda/rust/build-1/bootstrap/debug/incremental/bootstrap-22qjf7qknjduo/s-gdrx5ab0wu-1spyacv-3unuz3kev23rs/4oqq7pii1co5y8sx.o:     file format elf64-x86-64

> Contents of section .rodata..L__unnamed_34:
>  0000 2f686f6d 652f736b 6f6b6b6f 6e64612f  /home/skokkonda/
>  0010 72757374 2f627569 6c642d31 2f783836  rust/**build-1**/x86
>  0020 5f36342d 756e6b6e 6f776e2d 6c696e75  _64-unknown-linu
>  0030 782d676e 752f7374 61676530 2f62696e  x-gnu/stage0/bin
>  0040 2f727573 7463                        /rustc

2)
.rodata section in build directory : _build-test_
:~/rust/build-1$ objdump -s -j .rodata..L__unnamed_34 ~/rust/build-test/bootstrap/debug/incremental/bootstrap-22qjf7qknjduo/s-gds2uitpgl-fm0ssi-193tjef7tbwwd/4oqq7pii1co5y8sx.o

/home/skokkonda/rust/build-test/bootstrap/debug/incremental/bootstrap-22qjf7qknjduo/s-gds2uitpgl-fm0ssi-193tjef7tbwwd/4oqq7pii1co5y8sx.o:     file format elf64-x86-64

> Contents of section .rodata..L__unnamed_34:
>  0000 2f686f6d 652f736b 6f6b6b6f 6e64612f  /home/skokkonda/
>  0010 72757374 2f627569 6c642d74 6573742f  rust/**build-test**/
>  0020 7838365f 36342d75 6e6b6e6f 776e2d6c  x86_64-unknown-l
>  0030 696e7578 2d676e75 2f737461 6765302f  inux-gnu/stage0/
>  0040 62696e2f 72757374 63                 bin/rustc

I tried two different builds with identical build path and then compared the binaries, those are identical.

This issue is causing a automated test failure in Yocto build enevironment. Can anyone confirm that is it a bug in rust?

**Comment by sundeep-kokkonda** [comment]
The path is autogenerated, this object file is generated during the 'stage-0' and still 'stage-1' is yet to build, so I guess in that way the build is 'incremental'? Is there any option that can avoid this?

**Comment by kpcyrd** [comment]
I think it's specifically the build path that's embedded, this is a known limitation at the moment and projects like Arch Linux that are currently doing reproducible builds use a standardized build path to reproduce their rust binaries (and the rust compiler itself).

It would be nice to have rust/cargo not embed the build path by default (that's why I've filed https://github.com/rust-lang/cargo/issues/5505) but it doesn't block the security advantages of reproducible builds.

**Comment by sundeep-kokkonda** [comment]
@kpcyrd Thanks for the info... Is there a way available to eliminate build paths in final binary? I tried a few ways with `--remap-path-prefix` & `-Z binary-dep-depinfo` options but still the path info is present in final binary and which makes builds are not reproducible.
Let me know if you know any option/change in code removes the path in final binary, so that I can make my local patch...

**Comment by kpcyrd** [comment]
This has worked for me in the past:
```
RUSTFLAGS="--remap-path-prefix=$HOME=/remap-home --remap-path-prefix=$PWD=/remap-pwd" cargo build --release --verbose
```
I had a CI job in place that uses reprotest like this: https://github.com/kpcyrd/sniffglue/blob/main/ci/reprotest.sh

**Comment by jyn514** [comment]
It sounds like this is avoidable using --remap-path-prefix, so I'm going to close this issue.

The issue tracker is not a support forum. For future questions please ask in one of these places:

https://discord.gg/rust-lang/
https://discord.gg/rust-lang-community/
https://users.rust-lang.org/
https://rust-lang.zulipchat.com/
