### ISSUE TITLE
rustdoc removes feature flag labels for re-exports

### ISSUE THREAD

**Issue by andrewbanchich** [rust-lang/rust#102250]
[`tower::service_fn`](https://docs.rs/tower/latest/tower/fn.service_fn.html), for example, says nothing about feature flags you need to enable, even though it is behind the `utils` flag. This makes it fairly confusing.

The `service_fn` in the crate root is just a reexport of [`tower::utils::service_fn`](https://docs.rs/tower/latest/tower/util/fn.service_fn.html), which *is* correctly marked as behind a feature flag.

**Comment by GuillaumeGomez** [comment]
Another re-export issue. I'll take a look at it.

**Comment by GuillaumeGomez** [comment]
Just to be sure: did you try with a more recent nightly? I fixed a similar issue in https://github.com/rust-lang/rust/pull/101006.

**Comment by andrewbanchich** [comment]
It does seem to be fixed on nightly. Thanks!
