### ISSUE TITLE
Improve diagnostics for incorrect double pointer type

### ISSUE THREAD

**Issue by Rageking8** [rust-lang/rust#102261]
Given the following code: [link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=6ef90d137a70b94d60c117306b28f079)

```rust
fn main() {
    let x: i32 = 5;
    let ptr: *const i32 = &x;
    let dptr: **const i32 = &ptr;
}
```

The current output is:

```
   Compiling playground v0.0.1 (/playground)
error: expected mut or const in raw pointer type
 --> src/main.rs:4:15
  |
4 |     let dptr: **const i32 = &ptr;
  |               ^ expected mut or const in raw pointer type
  |
  = help: use `*mut T` or `*const T` as appropriate

error: could not compile `playground` due to previous error
```

Ideally the output should suggest correct ways to specify a double pointer type (e.g. `*const *const T`)(May be able to extend for more levels of indirection if wanted), instead of a generic single pointer suggestion, which may not be what the user wants.

**Comment by compiler-errors** [comment]
I think this message is fine as it. I guess it could be slightly more specific -- saying "expected `const` or `mut` keyword in raw pointer type"
