### ISSUE TITLE
Suggest `unwrap_or_else` when a closure is passed to `unwrap_or`  instead of suggesting calling it

### ISSUE THREAD

**Issue by amrbashir** [rust-lang/rust#102320]
`rustc` should suggest `unwrap_or_else` if the argument is a closure instead of suggesting to call the closure

Given the following code:  https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=15e99f8e75edf68460c457c09e4e2fa4

```rust
fn main() {
  let x = "com.example.app";
  let y: Option<&str> = None;
  let s = y.unwrap_or(|| x.split('.').nth(1).unwrap());
}
```

The current output is:

```
error[[E0308]](https://doc.rust-lang.org/stable/error-index.html#E0308): mismatched types
 --> src/main.rs:4:23
  |
4 |   let s = y.unwrap_or(|| x.split('.').nth(1).unwrap());
  |             --------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&str`, found closure
  |             |
  |             arguments to this function are incorrect
  |
  = note: expected reference `&str`
               found closure `[closure@src/main.rs:4:23: 4:25]`
note: associated function defined here
help: use parentheses to call this closure
  |
4 |   let s = y.unwrap_or((|| x.split('.').nth(1).unwrap())());
  |                       +                               +++
```

Ideally the output should look like:

```
error[[E0308]](https://doc.rust-lang.org/stable/error-index.html#E0308): mismatched types
 --> src/main.rs:4:23
  |
4 |   let s = y.unwrap_or(|| x.split('.').nth(1).unwrap());
  |             --------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&str`, found closure
  |             |
  |             arguments to this function are incorrect
  |
  = note: expected reference `&str`
               found closure `[closure@src/main.rs:4:23: 4:25]`
note: associated function defined here
help: use "unwrap_or_else"
  |
4 |   let s = y.unwrap_or_else(|| x.split('.').nth(1).unwrap());
  |                      +++++                              
```

**Comment by compiler-errors** [comment]
This probably can be generalized if the code is written carefully enough.

**Comment by chenyukang** [comment]
> This probably can be generalized if the code is written carefully enough.

Do you mean, we should handle other types like `Result` which may use `unwrap_or` with a closure?

**Comment by amrbashir** [comment]
I know nothing about the internals of rustc diagnostics but a general way would be to check if a similar method in name accepts a closure and suggest that first, if nothing similar can be found then suggest calling the closure

**Comment by compiler-errors** [comment]
@chenyukang: I mean something more like what @amrbashir is suggesting, where you check if `{FUNCTION}_else` exists whose signature is compatible with a closure. But that requires doing a method probe, then doing some delicate logic to check argument compatibility.
