### ISSUE TITLE
Spurious additional lifetime appearing in printout of type involving HRT lifetimes

### ISSUE THREAD

**Issue by steffahn** [rust-lang/rust#102392]
“Related” to #102346, and #101280, as this, too, is about diagnostic printing of types with HRT lifetimes (unlike the former related issue, this issue is not a recent regression):
```rs
fn g(f: for<'a> fn(fn(&str, &'a str))) -> bool {
    f
}
```
```
error[E0308]: mismatched types
 --> src/lib.rs:2:5
  |
1 | fn g(f: for<'a> fn(fn(&str, &'a str))) -> bool {
  |                                           ---- expected `bool` because of return type
2 |     f
  |     ^ expected `bool`, found fn pointer
  |
  = note:    expected type `bool`
          found fn pointer `for<'a> fn(for<'b, 'a> fn(&'b str, &'a str))`
```

The way this type is displayed includes an additional superflous/confusing/wrong quantification of `'a` in the inner `for`. Correct would be `for<'a> fn(for<'b> fn(&'b str, &'a str))`, not `for<'a> fn(for<'b, 'a> fn(&'b str, &'a str))`.

cc @b-naber who is currently working on the above-mentioned “related” issues.

@rustbot label regression-from-stable-to-stable, E-needs-bisection

Regresses between 1.54 and 1.55:

1.54
```
  = note:    expected type `bool`
          found fn pointer `for<'a> fn(for<'r> fn(&'r str, &'a str))`
```
1.55
```
  = note:    expected type `bool`
          found fn pointer `for<'a> fn(for<'r, 'a> fn(&'r str, &'a str))`
```

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23102392.20Spurious.20additional.20lifetime.20appearing.20in.20printout.20.E2.80.A6)).

@rustbot label -I-prioritize +P-low

**Comment by apiraino** [comment]
Bisection seems to indicate this group of PRs
```
********************************************************************************
Regression in nightly-2021-07-23
********************************************************************************

  commit[0] 2021-07-21UTC: Auto merge of #87351 - ehuss:rollup-pga85az, r=ehuss
  commit[1] 2021-07-21UTC: Auto merge of #86946 - Aaron1011:eval-proj-obligation, r=nikomatsakis
  commit[2] 2021-07-22UTC: Auto merge of #87246 - rust-lang:placeholder-pretty, r=nikomatsakis
  commit[3] 2021-07-22UTC: Auto merge of #87250 - robojumper:87199-sized-relaxation, r=nikomatsakis
  commit[4] 2021-07-22UTC: Auto merge of #87265 - Aaron1011:hir-wf-fn, r=estebank
  commit[5] 2021-07-22UTC: Auto merge of #86619 - rylev:incr-hashing-profiling, r=wesleywiser
  commit[6] 2021-07-22UTC: Auto merge of #87366 - GuillaumeGomez:rollup-7muueab, r=GuillaumeGomez
  commit[7] 2021-07-22UTC: Auto merge of #87371 - ehuss:update-cargo, r=ehuss
  commit[8] 2021-07-22UTC: Auto merge of #86212 - pnkfelix:mainline-targetted-revert-81473-warn-write-only-fields, r=simulacrum
```

but due to the age I could not pinpoint a specific nightly.

Also, as pointed out in the previous comment at some point the diagnostic changed and decided to use another wording (`for<'a> fn(for<'b, 'a> fn(&'b str, &'a str))`) which I wonder if it's related to one of the mentioned other 2 issues

@rustbot label -E-needs-bisection

**Comment by steffahn** [comment]
Looking through this list, #87246 seems likely.
