### ISSUE TITLE
Autotool site defaults can cause autotools using dependencies to be inconsistent with Rust's configuration

### ISSUE THREAD

**Issue by sstewartgallus** [rust-lang/rust#10236]
For example, suppose I have an auto tools default configuration set up with the environment variable `CONFIG_SITE`, and the script is `test "$prefix" = NONE && prefix="$HOME/local"`. Then Rust's configuration might end up thinking `$prefix` is empty, and unset but the autotools using dependencies of Rust might think that `prefix` is set to `"$HOME/local"`.

**Comment by steveklabnik** [comment]
triage: no idea

**Comment by steveklabnik** [comment]
Traige: still no idea.

@sstewartgallus if you are still seeing this issue, please let me know, but I'm giving it a close.
