### ISSUE TITLE
Array indexed by enum cast to usize no longer has bounds check eliminated

### ISSUE THREAD

**Issue by dsekercioglu** [rust-lang/rust#102303]
Rust compiler fails to eliminate bounds check when array is indexed by an enum cast to usize
Compiler explorer: https://godbolt.org/z/4o5cqT1eK

### Code

```rust
pub enum Enum {
    A, B, C
}

pub fn func(inbounds: Enum, array: &[i16; 3]) -> i16 {
    array[inbounds as usize]
}
```
I expected the compiler to remove the bounds checks like it did previously however it failed to do so.

### Version it worked on

It most recently worked on: Rust 1.63.0

### Version with regression

```
rustc 1.64.0 (a55dd71d5 2022-09-19)
binary: rustc
commit-hash: a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52
commit-date: 2022-09-19
host: x86_64-unknown-linux-gnu
release: 1.64.0
LLVM version: 14.0.6
```

@rustbot modify labels: +regression-from-stable-to-stable -regression-untriaged

**Comment by clubby789** [comment]
Regressed in #96862

**Comment by nikic** [comment]
cc @oli-obk It looks like the necessary support code has already landed in https://github.com/rust-lang/rust/pull/98332, so this should be a simple fix now?

**Comment by oli-obk** [comment]
@Dajamante is working on it

**Comment by scottmcm** [comment]
Note that this still works:
```rust
pub fn func(inbounds: &Enum, array: &[i16; 3]) -> i16 {
    array[*inbounds as usize]
}
```

So this is also the classic "LLVM doesn't have range metadata on parameters" problem.

(When there's a load, it gets `!range` metadata `!{i8 0, i8 3}`, which LLVM can then use to remove the comparison.  But passed by value that metadata is unavailable.)

**Comment by MinusKelvin** [comment]
Should that work? `Enum` is not `Copy` so `*inbounds` is moving out of a shared reference. Or at least, that's what 1.63 says; 1.64 compiles it without any warnings. The 1.64 release notes say this about drop behavior:
> - The Drop behavior of C-like enums cast to ints has changed. These are already discouraged by a compiler warning.

But I don't see why a change in drop behavior should affect whether a value is moved or not, and of course, there is no warning.

**Comment by FCLC** [comment]
Example of the specific behavior with IR and using the load "workaround" https://godbolt.org/z/YK79ErY5r

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23102303.20Array.20indexed.20by.20enum.20cast.20to.20usize.20no.20longer.20has.20b.E2.80.A6)).

@rustbot label -I-prioritize +P-medium

**Comment by ouz-a** [comment]
@claim
