### ISSUE TITLE
Value differs between debug and release: 1.0 / ((-0.0) * black_box_zero)

### ISSUE THREAD

**Issue by jruderman** [rust-lang/rust#102402]
This code has differing behavior in debug and release ([playground](https://play.rust-lang.org/?version=nightly&mode=release&edition=2021&gist=a83dabd53487e12d9f023c9dc116e1e1)):

```rust
fn main() {
    let black_box_zero = (std::env::args().len() - 1) as f32;
    let result = 1.0 / ((-0.0) * black_box_zero);
    let expected = f32::NEG_INFINITY;
    assert_eq!(result, expected);
}
```

When compiled in debug mode (without optimizations), the program produces no output.

When compiled in release mode (with optimizations), the assertion fails:

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `-inf`,
 right: `-inf`', src/main.rs:5:5
```

(This output doesn't make sense to me: how can they be unequal, but both negative infinity?)

**Comment by jruderman** [comment]
Here's another program with similar behavior, failing only in release. Not sure if it's the same issue.

```rust
fn main() {
    let black_box_one = (std::env::args().len()) as f32;
    let result = - (black_box_one / 0.0);
    let expected = f32::NEG_INFINITY;
    assert_eq!(result, expected);
}
```

**Comment by SNCPlay42** [comment]
This function, based on the first code example, is misoptimized to unconditionally return false ([godbolt](https://rust.godbolt.org/z/9heP3PEoM)):

```rust
pub fn foo(n: usize) -> bool {
    let black_box_zero = (n - 1) as f32;
    
    let result = 1.0 / ((-0.0) * black_box_zero);

    result == std::f32::NEG_INFINITY
}
```

This was not misoptimized before rustc 1.25, which upgraded LLVM to version 6.0. This appears to be a misoptimization by LLVM (Unless there's some allowed variability to do with the signs of zeroes that I'm not aware of?)

@rustbot label A-LLVM A-floating-point I-unsound T-compiler regression-from-stable-to-stable

**Comment by nbdd0121** [comment]
This C code miscompiled under Clang as well: https://godbolt.org/z/bfqoGePW1.

Confirmed to be a LLVM bug.

**Comment by SNCPlay42** [comment]
The second example does actually appear to be different - it doesn't miscompile until rustc 1.30 ([godbolt](https://rust.godbolt.org/z/Y7dqoax1j)).

**Comment by nikic** [comment]
Upstream issue: https://github.com/llvm/llvm-project/issues/58046

**Comment by lukas-code** [comment]
possibly related: https://github.com/rust-lang/rust/issues/55131

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23102402.20Value.20differs.20between.20debug.20and.20release.3A.201.2E0.20.2F.20.28.28-0.E2.80.A6)).

@rustbot label -I-prioritize +P-high

**Comment by pnkfelix** [comment]
T-compiler P-high review

@rustbot assign @nikic

**Comment by jruderman** [comment]
Does that fix take care of the [second example](https://github.com/rust-lang/rust/issues/102402#issuecomment-1260769942)?

**Comment by jruderman** [comment]
To answer my own question: both examples are fixed for me after updating rustc nightly from (9c56d9d6f 2022-09-29) to (8ce3204af 2022-09-30)

**Comment by RalfJung** [comment]
Should we add a test for this?
