### ISSUE TITLE
Strange coverage results from `-C instrument-coverage`

### ISSUE THREAD

**Issue by Mingun** [rust-lang/rust#102477]
I do not know in what part the problem begins, so if rustc has nothing to do with it, please tell me how to check that. I'm a maintainer of [quick-xml](https://github.com/tafia/quick-xml) and I setup a [coverage](https://github.com/tafia/quick-xml/pull/391) for it and collect coverage, using `RUSTFLAGS: -C instrument-coverage`.

However, results on codecov.io looks very strange:
- many lines are marked as not covered while they contains simple doc comments even without doctests. The most striking example of a file in which there is no executable code at all, but it is all marked as not covered: https://app.codecov.io/gh/tafia/quick-xml/blob/master/src/lib.rs
- non-executable code, such as `use`s or `mod` declarations marked as not covered (in the same place)
- sometimes coverage looks like it started and ended at random lines: some examples in https://app.codecov.io/gh/tafia/quick-xml/blob/master/src/de/mod.rs
- code of module tests (i.e. in `#[cfg(test)]` modules) are also included in coverage which is unexpected, for example: https://app.codecov.io/gh/tafia/quick-xml/blob/master/src/de/mod.rs. That code should be used to _produce_ coverage, not _for_ coverage. This seriously biases the results, especially when you have more lines with tests than with code itself.

### Meta

The coverage is collected by GitHub `ubuntu-latest` runner, currently it reports Rust 1.64.0, but the issue was there since coverage was added to quick-xml, i.e. at least since 2022-05-30. The corresponding GitHub Actions file: https://github.com/tafia/quick-xml/blob/240f2049aec50876b6e13e632120b20cd60a37af/.github/workflows/rust.yml

**Comment by juntyr** [comment]
I'm also experiencing the same issues. Producing the coverage locally and using the VSCode coverage gutters extension to view it shows much cleaner coverage information. So perhaps this is an issue on codecov's end?

**Comment by Enselic** [comment]
Triage: Can the problem still be reproduced? In order to make progress on this issue there needs to be a way for others to reproduce the problem. Ideally step-by-step instructions inside of a fresh docker container from a widely used linux distro.

**Comment by juntyr** [comment]
At least in my instance the issue was solved by ensuring the coverage builds were fresh and not confused by an outdated build cache

**Comment by Enselic** [comment]
Thanks for getting back. Let's close this issue as obsolete then. If there still is a problem some other issue will be filed, if it hasn't already.
