### ISSUE TITLE
Rustdoc line number desynchronization on iPhone Safari

### ISSUE THREAD

**Issue by pali6** [rust-lang/rust#102404]
On iPhone Safari 15.1 (~~and possibly other mobile browsers, I am unable to check~~ EDIT: Android browsers do not have this issue) in the source view code lines get line wrapped which causes the line numbers to desynchronize from their lines. In some cases multi-digit line numbers also get line wrapped which causes further desynchronization, though from my checking this currently happens for docs hosted on docs.rs but not on doc.rust-lang.org/std. This issue also means that clicking on source links in documentation leads to completely unrelated code as the links are to the line numbers and not the lines themselves.

This issue does not happen on Windows browsers I tested when I manually shrink the window to be approximately as narrow as the mobile browser. I have not tested the issue with computer version of Safari.

https://doc.rust-lang.org/src/std/lib.rs.html#1-633 viewed on iPhone Safari 15.1 (note how one code line covers multiple line numbers when it wraps):
![image](https://user-images.githubusercontent.com/358431/192779986-80a7a1f1-9c9c-4d5f-86b9-84688e0d7a42.png)

https://doc.rust-lang.org/src/std/lib.rs.html#1-633 viewed on Windows Firefox 105.0.1 with similar window size (no issue here):
![image](https://user-images.githubusercontent.com/358431/192780254-de6b4109-016e-4f6d-9fd9-cb166586cf3a.png)

https://docs.rs/smallvec/latest/src/smallvec/lib.rs.html#1485 viewed on iPhone Safari 15.1 (no source code is visible because the multi-line line numbers scroll way beyond source code):
![image](https://user-images.githubusercontent.com/358431/192780827-d2364388-83f8-4014-9547-227588a3551a.png)

https://docs.rs/smallvec/latest/src/smallvec/lib.rs.html#1485 viewed on iPhone Safari 15.1 and manually scrolled to the correct line (note the incorrect line numbers that cover multiple actual code lines):
![image](https://user-images.githubusercontent.com/358431/192780967-f893c7d9-8b4b-4fad-8ab6-5371ff0cc53c.png)

https://docs.rs/smallvec/latest/src/smallvec/lib.rs.html#1485 viewed on Windows Firefox 105.0.1 with similar window size (no issue here):
![image](https://user-images.githubusercontent.com/358431/192780499-9bc121d4-c1a5-4fa2-bad5-65478c8e9e6b.png)

**Comment by GuillaumeGomez** [comment]
I don't have an iphone so I won't be able to check what's going. Does someone on the @rust-lang/rustdoc team has an iphone by any chance?

**Comment by jsha** [comment]
I've got one and will check.

**Comment by jsha** [comment]
I was unable to reproduce on iPhone 15.5. The lines don't wrap at all, which is expected behavior.

It looks like the latest iOS version is 15.7. I'm upgrading to that now. @pali6 would you mind upgrading to 15.7 as well and seeing if it still reproduces for you?

**Comment by pali6** [comment]
That indeed fixed the issue. My bad for not staying updated.

**Comment by jsha** [comment]
No worries! Thanks for taking the time.
