### ISSUE TITLE
rustfmt erases dyn*

### ISSUE THREAD

**Issue by eholk** [rust-lang/rust#102431]
While filing #102427, I noticed rustfmt erases `dyn*` from types.

Input:
```rust
#![feature(dyn_star)]
#![allow(incomplete_features)]

use std::fmt::Display;

fn make_dyn_star() -> dyn* Display {
    Box::new(42) as dyn* Display
}

fn main() {
    let x = make_dyn_star();

    println!("{x}");
}
```

Output:
```rust
#![feature(dyn_star)]
#![allow(incomplete_features)]

use std::fmt::Display;

fn make_dyn_star() -> Display {
    Box::new(42) as Display
}

fn main() {
    let x = make_dyn_star();

    println!("{x}");
}
```

Expected: The input should not have changed because it was already formatted correctly.

**Comment by mejrs** [comment]
See also https://github.com/rust-lang/rustfmt/issues/5542

**Comment by calebcartwright** [comment]
Let's close this. We do not use this repository to track work for rustfmt, similar to many of the other dev tools

**Comment by eholk** [comment]
Sounds good!
