### ISSUE TITLE
Period "." in file or #[link name causes custom extension executable instead of .exe

### ISSUE THREAD

**Issue by SecondNature** [rust-lang/rust#10255]
#[link(name = "fff.eee")
The output generates a windows executable with the extension ".eee" as opposed to "fff.eee.exe".

Adding the ".exe" manually will reduce platform independence.

Bug or feature? Implications of a change?

**Comment by steveklabnik** [comment]
GIven that crate names are identifiers, and that `#[link]` is gone, I think this issue is now moot.
