### ISSUE TITLE
Iterator trait's `find` and `position` method doesn't explain why it takes `&mut self`

### ISSUE THREAD

**Issue by avdb13** [rust-lang/rust#102501]
This method drops all the elements including the found element before the closure evaluates to `true`. I think this also applies to `find`.
Example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1171bdb225c7fd2d1b37518f27199413

**Comment by ehuss** [comment]
Transferred to rust-lang/rust as the std docs live in this repository.

As to your question, I'm not sure I fully understand it. The `find` or `position` methods need to modify the state of the iterator in order to advance them to the element they are looking for. This is true for almost all the iterator methods, so I'm not sure what kind of explanation you are looking for.

**Comment by workingjubilee** [comment]
@avdb13 The Iterator reifies the state of iteration, allowing external iteration, step by step, via `.next()`. It is not an "internal" iterator as you may have encountered, nor is it handling `Vec<u32>` as what is sometimes called an "iterable": it is a distinct entity that can _own_ data. Thus, when you give it data, which you did by calling `.into_iter()` which takes its argument by `self` as opposed to `&self` or &mut self`, thus truly moves the data into `Self::IntoIter`, and then iterated, you advanced the Iterator's state and allowed to be done with that data: the iterator has moved on and the data has moved into the abyss, as far as Rust is concerned.

If you want to avoid dropping things, consider instead borrowing:
```rust
fn main() {
    let v: Vec<u32> = vec![1,2,3,4];

    println!("{:?}", (&v).into_iter().position(|x| x == &2)); // Some(1)
    // It is common for a types to impl pub fn iter(&self) -> SomeIterator<'_, T>
    // as an iterator over &T, so another way to spell the above
    println!("{:?}", v.iter().position(|x| x == &2)); // Some(1)
    println!("{:?}", v); // [1, 2, 3, 4] with no clones required
}
```

This notion of the iterator actually consuming data allows by-value iteration of immutable data.
