### ISSUE TITLE
Tracking Issue for `const_collections_with_hasher`

### ISSUE THREAD

**Issue by aDotInTheVoid** [rust-lang/rust#102575]
Feature gate: `#![feature(const_collections_with_hasher)]`

This is a tracking issue for making [`HashMap::with_hasher`](https://doc.rust-lang.org/stable/std/collections/hash_map/struct.HashMap.html#method.with_hasher) and [`HashSet::with_hasher`](https://doc.rust-lang.org/stable/std/collections/hash_set/struct.HashSet.html#method.with_hasher) `const`.

### Public API

```rust
// std::collections
impl<K, V, S> HashMap<K, V, S> {
    pub const fn with_hasher(hash_builder: S) -> HashMap<K, V, S> { ... }
}

impl<T, S> HashSet<T, S> {
    pub const fn with_hasher(hasher: S) -> HashSet<T, S> { ... }
}
```

### Steps / History

- [x] Implementation: #102574
- [x] Final comment period (FCP)[^1]
- [ ] Stabilization PR (https://github.com/rust-lang/rust/pull/118427)

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by GoldsteinE** [comment]
What blocks this from stabilization? Can I do something to move it forward?

**Comment by aDotInTheVoid** [comment]
@GoldsteinE: see <https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html>

Main questions for stabilization are do we want to add the constraint that an empty hashmap can be const constructed (ie doesn't alloc and more). This is true for the current hashbrown design, but might not be true for other alternatives. I'm not framiliar enough with hashmap design to say.

**Comment by aDotInTheVoid** [comment]
Trying to stabilize this, I run into this error:

```
error: `hashbrown::HashMap::<K, V, S>::with_hasher` is not yet stable as a const fn
   --> library/std/src/collections/hash/map.rs:292:25
    |
292 |         HashMap { base: base::HashMap::with_hasher(hash_builder) }
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
```

This code here

https://github.com/rust-lang/rust/blob/9bd71afb90c2a6e0348cdd4a2b10a3bf39908f19/compiler/rustc_const_eval/src/transform/check_consts/check.rs#L984-L995

seems to think it's unstable, despite `hashbrown` having no stability annotations. CC @ecstatic-morse

**Comment by aDotInTheVoid** [comment]
Solved by changing the compiler to respect `rustc_allow_const_fn_unstable` here. This requires new semantics as there's no feature gate on the hashbrown side, so I said `any` will work here. Not sure if this is OK.

This also means a load of ugly things are needed to be `cfg_attr(bootstrap, ...)`ed

@rustbot claim

**Comment by zk4x** [comment]
Can we get an ETA how many years will this approximately take to stabilize? How can I speed this process? Or should I just write my own hashmap or use alloc::collections::BTreeMap? Thanks ahead for any info.

**Comment by aDotInTheVoid** [comment]
Sorry, I should have given an update to this. The FCP’s been approved, so the only thing remaining it to actually do the stabilisation. Unfortunately that’s actually tricky in this case, due to HashMap being implemented in an external crate (hashbrown), it has really painful interactions with the const-stability checker.

Those checks are currently being rewritten in #131349, so after that lands it should be possible to try again if you (or someone else) wants to work on it.

**Comment by RalfJung** [comment]
I am planning to make this possible as part of finishing my work on https://github.com/rust-lang/rust/issues/129815.

However, you won't be able to construct a `HashMap<K, V>` in `const` since that one uses randomized keys. You will have to set a non-default hasher builder.

**Comment by RalfJung** [comment]
The PR that should enable us to safely expose `const fn` from hashbrown is up now: https://github.com/rust-lang/rust/pull/132541.

(That's just the infrastructure for this, once it lands, a bit of wiring-up needs to happen in hashbrown.)

**Comment by RalfJung** [comment]
Cc @rust-lang/wg-const-eval
