### ISSUE TITLE
rustdoc JSON: struct fn missing if re-exported from private mod

### ISSUE THREAD

**Issue by Enselic** [rust-lang/rust#102583]
### Step-by-step

1. Put this in `repro.rs`:
```rust
mod private_mod {
    pub struct S;

    impl S {
        pub fn missing_from_rustdoc_json() {}
    }
}

pub use private_mod::*;
```

2. Run `rustdoc +nightly-2022-10-02 repro.rs -Zunstable-options -wjson`

3. Check if `missing_from_rustdoc_json` is in the generated JSON: `grep missing_from_rustdoc_json doc/repro.json`

### Actual result

Item is missing.

### Expected result

Item is present.

### Remarks

The item is present in the HTML version of the docs (`rustdoc +nightly-2022-10-02 repro.rs  && open doc/repro/index.html`), or in the JSON if `private_mod` is made `pub`.

@rustbot labels +A-rustdoc-json +T-rustdoc +C-bug

**Comment by GuillaumeGomez** [comment]
I have a fix for this, I'll send it in the next hours.

**Comment by GuillaumeGomez** [comment]
Opened https://github.com/rust-lang/rust/pull/103653.
