### ISSUE TITLE
The symlinks_works test is ignored on windows

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#10264]
In #10179 I added support for symlinks bindings to libuv. I could never get the `symlinks_work`, so I'm ignoring it for now to get this patch landed.

This warrants further investigation, the problem I kept seeing was that a condition was raised saying "operation not permitted".

**Comment by steveklabnik** [comment]
libuv is totally gone now, so as far as I can tell, this needs closed.

**Comment by klutzy** [comment]
@steveklabnik the test is [still at `libstd/fs.rs`](https://github.com/rust-lang/rust/blob/abf0548b5caaa389a5b29813132d2cf4c8b0f1ed/src/libstd/fs.rs#L1659). Could you reopen this?
