### ISSUE TITLE
Can't pipe stdout/stderr to the same pipe for a child process

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#10269]
This is more of a problem with the `rt::io::process` bindings rather than the `std::run` bindings (the latter needs a larger overhaul in general). The `rt::io::process` bindings currently don't expose the ability to have something like `2>&1` and then you capture the output of `&1` (redirecting stderr to stdout and then reading stdout).

A possible solution is to add another enum variant to `StdioContainer` named along the lines of `PipeTo(int)` which means that the output of this stdio slot should get redirected to the pipe which was defined at slot `int`. Perhaps an `IoError` should be raised if it doesn't reference a `CreatePipe` slot, perhaps a failure.

**Comment by steveklabnik** [comment]
cc https://github.com/rust-lang/rust/pull/22119

**Comment by aturon** [comment]
@steveklabnik This should probably go to the wishlist. With IO reform, this would be extending the ways of setting up pipes to a child process.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#871
