### ISSUE TITLE
emacs mode: ']', ')', and '}' close previous open paren/brace/bracket

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#10262]
Here is the illustrative example:

```rust
fn foo() {
    { bar('}'); }
    { bar(']'); }
    { bar(')'); }
}
```

The characters within `'` characters above are incorrectly treated by `src/etc/rust-mode.el` as closing the opening paren of the invocation of `bar`.  This confuses Emacs in a number of ways (e.g. obviously paren matching; but also the auto-indentation gets confused too, which is more annoying).

**Comment by steveklabnik** [comment]
Moved to rust-lang/rust-mode#6
