### ISSUE TITLE
+ and - keyboard shortcuts mixed up in docs page

### ISSUE THREAD

**Issue by amab8901** [rust-lang/rust#102772]
Take any page in the Rust docs, for example [this](https://doc.rust-lang.org/std/index.html). When you press the `+` or `-` keyboard shortcuts on your keyboard, they are supposed to either collapse or expand all items on the page, but not both (according to the instructions that you can find by clicking `?` on your keyboard (or on the screen).

Please make the + and - keyboard shortcuts idempotent, otherwise it would be redundant to have two buttons that do the same thing.

**Comment by GuillaumeGomez** [comment]
What do you think about this @Manishearth @jsha ?

**Comment by Manishearth** [comment]
Yeah we should do this.

**Comment by GuillaumeGomez** [comment]
I'll send a patch in the next days then.
