### ISSUE TITLE
Future-Incompatible Lint - Improve Example

### ISSUE THREAD

**Issue by amab8901** [rust-lang/rust#102743]
I was reading about future-incompatible lints on [this](https://doc.rust-lang.org/rustc/lints/index.html) page.

First of all, I struggled to reproduce the lint warning, and it would have been really educational if you provided an example of how to trigger that lint warning for future incompatibility (please add example of how I can trigger the warning showed in that section).

Second, I tried applying the `#![warn(safe_packed_borrows)]` in Rust Playground, like this:

```
#![allow(safe_packed_borrows)]
fn main() {}
```
Running the code produces, among other things, the following:
```
warning: lint `safe_packed_borrows` has been renamed to `unaligned_references`
```
So that means that you should update the "[example of what a future-incompatible looks like](https://doc.rust-lang.org/rustc/lints/index.html)", because the current example is obsolete.

**Comment by Dylan-DPC** [comment]
Closing this because in the pr (#127504) we decided it's better to leave it as is, and is a pain to keep updated and there is less benefit in having the illustrated example not be out of date.
