### ISSUE TITLE
lint `missing_doc_code_examples` is apparently missing documentation

### ISSUE THREAD

**Issue by amab8901** [rust-lang/rust#102774]
[This](https://doc.rust-lang.org/rustdoc/write-documentation/what-to-include.html) page mentions the lint `missing_doc_code_examples`, but I couldn't find it in any of these 3 [subpages](https://doc.rust-lang.org/rustc/lints/listing/index.html), i.e. 3.3.1, 3.3.2, 3.3.3. 

Please check if `missing_doc_code_examples` is a valid lint. If it's valid, then add it in the approrpate rustc doc page (3.3.1, 3.3.2 or 3.3.3). If it's not valid, then update [this](https://doc.rust-lang.org/rustdoc/write-documentation/what-to-include.html) page to no longer describe that lint as a valid lint.

**Comment by ehuss** [comment]
All rustdoc lints are on their own page in the rustdoc book. For example: https://doc.rust-lang.org/rustdoc/lints.html#missing_doc_code_examples
