### ISSUE TITLE
`async fn` in trait should require `async fn` in impl

### ISSUE THREAD

**Issue by compiler-errors** [rust-lang/rust#102745]
For now, we've decided that an `async fn() -> T` in a trait should not be satisfied by a `fn() -> Type` where `Type: Future<Output = T>` until we at least hammer out how `#[refine]` is gonna work, etc.

So let's just do a HIR check that the signatures are compatible.

**Comment by compiler-errors** [comment]
Assigning to @ComputerDruid who expressed interest in working on this.

**Comment by compiler-errors** [comment]
@rustbot assign @ComputerDruid

idk if that works, the github UI doesn't let me assign to you :stuck_out_tongue_closed_eyes:

**Comment by zirconium-n** [comment]
Should it be satisfied with `fn() -> impl Future<Output = T>` ?

**Comment by compiler-errors** [comment]
I think not for now, and certainly not without the user enabling the `return_position_impl_trait_in_trait` feature gate
