### ISSUE TITLE
Stabilize raw-dylib for non-x86

### ISSUE THREAD

**Issue by wesleywiser** [rust-lang/rust#102793]
The `raw-dylib` feature was proposed for stabilization for non-x86 targets in #99916 which the compiler team FCP'd and merged but forgot to tag `T-lang` as well. Sorry about that!

Since that PR has already been FCP'd rfcbot won't allow me to start another FCP on it so I'm creating this issue to act as T-lang's FCP. 

> This stabilizes the raw-dylib and link_ordinal features (https://github.com/rust-lang/rust/issues/58713) for non-x86 architectures (i.e., x86_64, aarch64 and thumbv7a)

[Link to stabilization report](https://github.com/rust-lang/rust/issues/58713#issuecomment-1199827352)

I'm also tagging this `I-lang-nominated` to ensure discussion of this happens prior to the next release so we can either confirm the stabilization of the feature or revert the stabilization before the next release.

**Comment by joshtriplett** [comment]
@rfcbot merge

**Comment by wesleywiser** [comment]
Since this already merged in https://github.com/rust-lang/rust/pull/99916, I'm going to go ahead and close this issue.
