### ISSUE TITLE
Explain use-case(s) of lint capping

### ISSUE THREAD

**Issue by amab8901** [rust-lang/rust#102746]
I'm reading about capping lints on [this](https://doc.rust-lang.org/rustc/lints/levels.html) page.

I understand that `--cap-lints` tag will filter out the higher-severity lints and keep only the lower-severity lints. And I also understand that Cargo automatically runs that tag on `allow` level. But what would be a high-value use case of me actually writing that tag manually? Aren't the higher-intensity lints more important than the lower-intensity lints? Why don't you filter away the lower-intensity lints instead? Would be great if you explained to me but also wrote in the documentation. Doing so will help the reader understand why reading that part of the doc would be worthwhile.

**Comment by matthiaskrgr** [comment]
If you have a crate where you absolutely do not want pattern X in its code, you can use `deny(somelint)` to make findings of that pattern a hard error, whenever someone does `cargo check` or `cargo build`.

Now if someone else wants to still build your crate without editing the code, they can work around the `deny(x)` you set downgrading the "severity" of the lint from `deny` to `warn` using `--cap lints warn`.

This is for example quite useful if someone tries to make their crate "lint-clean" by denying all lint warnings, but their code has not been updated in a year an a new rustc version finds new warnings in their code which "breaks" the build
This is case where it's handy to downgrade the lints to make building possible again without having to touch any of the code :)

**Comment by amab8901** [comment]
> If you have a crate where you absolutely do not want pattern X in its code, you can use `deny(somelint)` to make findings of that pattern a hard error, whenever someone does `cargo check` or `cargo build`.
> 
> Now if someone else wants to still build your crate without editing the code, they can work around the `deny(x)` you set downgrading the "severity" of the lint from `deny` to `warn` using `--cap lints warn`.
> 
> This is for example quite useful if someone tries to make their crate "lint-clean" by denying all lint warnings, but their code has not been updated in a year an a new rustc version finds new warnings in their code which "breaks" the build This is case where it's handy to downgrade the lints to make building possible again without having to touch any of the code :)

oh, thanks. That makes a lot of sense. So if the project compiles without errors, but it has tons of noise from warnings, you can pick one flaw in particular and focus on solving that one by elevating its lint to error-level and using `--cap-lints` to ignore the noise from the other flaws that the compiler is complaining about, so you can focus more easily on that one flaw until it's fixed. Thanks for explanation!

**Comment by Nilstrieb** [comment]
The most important use case for cap-lints are dependencies. Cargo builds all dependencies with cap-lints, so that crates can `deny(warnings)` just fine, even if new warnings are added that crates haven't fixed yet.

**Comment by Dylan-DPC** [comment]
Closing this as this is more a discussion issue than anything to be done on this
