### ISSUE TITLE
x.py fmt <file> sometimes formats other files

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#102841]
> The per-file thing does not entirely work... when I ask x.py to format library/core/src/intrinsics.rs, it also formats library/core/src/panicking.rs.

_Originally posted by @RalfJung in https://github.com/rust-lang/rust/issues/102837#issuecomment-1272521731_

**Comment by jyn514** [comment]
@RalfJung can you post the commit you were on and the diff x.py created?

**Comment by RalfJung** [comment]
I wasn't on a commit as the committed files are all formatted already. So I introduced changes in both files and then triggered RA formatting, and it ended up undoing my changes in both files.

**Comment by RalfJung** [comment]
But strangely, I cannot reproduce outside of RA... when I invoke `./x.py fmt filename` myself, it behaves as expected; when I ask it to do formatting from RA, it formats other files, too.

**Comment by RalfJung** [comment]
Oh, is it possible that RA expects the formatting to happen via stdin/stdout? I was wondering how things would work for files with `mod` statements where calling rustfmt with the filename causes it to recurse.

**Comment by RalfJung** [comment]
Yes indeed, formatting in RA happens via stdin/stdout. So the filename argument is not the problem.
