### ISSUE TITLE
Add buffer flush note to `Macro std::eprint`

### ISSUE THREAD

**Issue by JanCVanB** [rust-lang/rust#102861]
### What needs to be fixed?
I'm told that `eprint!` should often be paired with `io::stdout().flush()` just like `print!`, but the docs don't mention that.

### Page(s) Affected
https://doc.rust-lang.org/std/macro.print.html recommends buffer flushing, but https://doc.rust-lang.org/std/macro.eprint.html doesn't.

### Suggested Improvement
We should copy/paste the buffer flush note from `print!` docs to `eprint!` docs (and change `stdout` to `stderr`). (I would submit a PR to do this, but I don't understand this repo.)

**Comment by Kobzol** [comment]
Hmm, stderr is not line buffered by default, right?

```
fn main() {
    eprint!("Hello stderr");
    print!("Hello stdout");
    std::thread::sleep(std::time::Duration::from_secs(100));
}
```
prints `Hello stderr`. 

Compare https://github.com/rust-lang/rust/blob/master/library/std/src/io/stdio.rs#L840 (unbuffered) vs https://github.com/rust-lang/rust/blob/master/library/std/src/io/stdio.rs#L604 (line-buffered).

CC @albertlarsan68

**Comment by albertlarsan68** [comment]
You are right Kobzol!

Thanks for verifying.

**Comment by Dylan-DPC** [comment]
Closing this due to https://github.com/rust-lang/rust/issues/102861#issuecomment-1311700433
