### ISSUE TITLE
Confusing hexadecimal floating point numbers

### ISSUE THREAD

**Issue by porky11** [rust-lang/rust#102808]
```rust
fn main() {
    let x = -0x10_f32;
    println!("{x}");
}
```

I would expect this to be of type f32.
Or I would expect an error message, which indicates that hexadecimal numbers or numbers without dot are not valid integers.

But this just works. It's interpreted as some integer. But not hexadecimal 10 (decimal 16), but some random huge number.

And it's not really a bug. It's just a valid hexadecimal integer, since F is just a hexadecimal digit, and `_` can be written inside numbers at any place anyway.

So when writing this code instead, it should be clearer, why it just works as expected.

```rust
fn main() {
    let x = -0x10F32;
    println!("{x}");
}
```

It's just the valid hexadecimal number `10F32`.

To me this seems like type annotations in rust are totally broken. And it cannot be fixed without a breaking change.
(for example forcing some specific symbol before the type annotation, which cannot appear at other places in the number, like `1.0:f32` or `0x10:u32` or forcing hexadecimal to be uppercase)

`_f32` can mean different things.
It can be hexadecimal digits or type annotations.
It's not wrong. You could interpret the type annotation not as a generic thing, but as something specific to number literals.

But it's still very confusing, and I don't know, what to do about it.

**Comment by lukas-code** [comment]
Clippy already has a related lint that could probably be expanded:
```rust
fn main() {
    let x = 0x10_32;
    println!("{x}");
}
```
```
    Checking playground v0.0.1 (/playground)
error: mistyped literal suffix
 --> src/main.rs:2:13
  |
2 |     let x = 0x10_32;
  |             ^^^^^^^ help: did you mean to write: `0x0010_i32`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#mistyped_literal_suffixes
  = note: `#[deny(clippy::mistyped_literal_suffixes)]` on by default

error: could not compile `playground` due to previous error
```

**Comment by navh** [comment]
```rust
fn main() {
    let x = 0x10_f32;
    println!("{x}");
}
```

gives me
```
warning: digits of hex or binary literal not grouped by four
 --> src/main.rs:2:13
  |
2 |     let x = 0x10_f32;
  |             ^^^^^^^^ help: consider: `0x0001_0f32`
  |
  = note: `#[warn(clippy::unusual_byte_groupings)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unusual_byte_groupings
```
Not the `could not compile` you got. 

The suggested byte grouping `_0f32` no longer looks like looks like a type annotation, but nothing at all shows up if someone uses x = 0x10f32, they may expect it to behave the same as y=10f32.
