### ISSUE TITLE
crate fails to compile a usable binary (no executable sections, only debug)

### ISSUE THREAD

**Issue by semiviral** [rust-lang/rust#102833]
### Code

I tried this code:

https://www.github.com/semiviral/linuiz

I expected to see this happen: project compiles as expected, and a binary executable (ELF format) is output into `.hdd/root/linuiz/kernel.elf`

Instead, this happened: the compiled binary contains no `.text`, `.rodata`, `.data`, or `.bss` sections (and thus cannot be loaded).

### Version it worked on

It most recently worked on:
```
rustc 1.66.0-nightly (0ca356586 2022-10-06)
```

### Version with regression

`rustc --version --verbose`:  
```
rustc 1.66.0-nightly (8b0c05d9a 2022-10-07)
```

### Backtrace

```
N/A
```

**Comment by apiraino** [comment]
@semiviral how to reproduce? Does the entire project you link need to be cloned and crosscompiled? Would be great if you could help with a smaller reproducible and instructions. Thanks!

@rustbot label e-needs-mcve

**Comment by js2xxx** [comment]
Looks like it had a similar issue with my project: #102886.

**Comment by semiviral** [comment]
Seems to have been fixed with the latest nightly (10-15-2022). Closing this issue.
