### ISSUE TITLE
value declaration via preprocessor

### ISSUE THREAD

**Issue by ozkanonur** [rust-lang/rust#102955]
```rs
#[macro_export]
macro_rules! define {
    ($name: ident, $val: expr) => {
        macro_rules! $name {
            () => {
                $val
            };
        }
    };
}
```

If we use the macro above as following:

```rs
define!(ORIENTATION_DEFAULT, 1);
```

We will able to achieve C style reusable value declaration like:
```
#define ORIENTATION_DEFAULT 1
```

Which means .rodata section will be lighter and compiled output will be optimized at micro level.

Can we or should we have this as std macro?

**Comment by lukas-code** [comment]
Rust already does that for constant items. If you define a constant like this:
```rust
const ORIENTATION_DEFAULT: i32 = 1;
```
Then all uses of the constant will be replaced by its value and the constant will not end up in `.rodata` or any other section of the resulting binary (as long as you don't take the address of the constant).

If you also want to infer the type of the constant, like a C `#define` would, you can use it as `ORIENTATION_DEFAULT as _` or `ORIENTATION_DEFAULT.into()`

You can read more about constant items in the [standard library docs](https://doc.rust-lang.org/nightly/std/keyword.const.html) or [reference](https://doc.rust-lang.org/nightly/reference/items/constant-items.html).

**Comment by ozkanonur** [comment]
> Rust already does that for constant items. If you define a constant like this:
> 
> ```rust
> const ORIENTATION_DEFAULT: i32 = 1;
> ```
> 
> Then all uses of the constant will be replaced by its value and the constant will not end up in `.rodata` or any other section of the resulting binary (as long as you don't take the address of the constant).
> 
> If you also want to infer the type of the constant, like a C `#define` would, you can use it as `ORIENTATION_DEFAULT as _` or `ORIENTATION_DEFAULT.into()`
> 
> You can read more about constant items in the [standard library docs](https://doc.rust-lang.org/nightly/std/keyword.const.html) or [reference](https://doc.rust-lang.org/nightly/reference/items/constant-items.html).
> 
> If you actually do want the constant in the binary, you'll have to use a `static` instead and possibly declare it `pub`, `#[used]`, or `#[no_mangle]`:
> 
> ```rust
> #[no_mangle]
> static ORIENTATION_DEFAULT: i32 = 1;
> ```

I knew constants usually works like that, but I also thought in scenario like casting constant types for function parameters then it becomes a real value in .rodata. But as I can see I was wrong. Thanks for the clarification @lukas-code
