### ISSUE TITLE
Tracking Issue for `const_location_fields`

### ISSUE THREAD

**Issue by lilasta** [rust-lang/rust#102911]
Feature gate: `#![feature(const_location_fields)]`

This is a tracking issue for `core::panic::Location` methods as `const` functions.

### Public API

```rust
// core::panic::location
impl Location {
    pub const fn file(&self) -> &str;
    pub const fn line(&self) -> u32;
    pub const fn column(&self) -> u32;
}
```

### Steps / History

- [x] Implementation: #101030 
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by programmerjake** [comment]
anything needed before both this and #76156 can be stabilized?

**Comment by Dylan-DPC** [comment]
@programmerjake @lilasta doesn't seem to be any blockers here and this has sat long enough so all what's missing is someone sending the pr to stabilise it, so feel free to do so if you are interested

**Comment by Amanieu** [comment]
FCP started in #76156 which also covers this issue.
