### ISSUE TITLE
swap places F_(n-2) and F_(n-1)

### ISSUE THREAD

**Issue by amab8901** [rust-lang/rust#102925]
https://veykril.github.io/tlborm/decl-macros/macros-practical.html

It says: "the [Fibonacci sequence](https://en.wikipedia.org/wiki/Fibonacci_number) can be defined by the relation:"

And right after that it says F_(n-1), and F_(n-2). These two should swap place because F_(n-1) is greater than F_(n-2)

**Comment by compiler-errors** [comment]
@amab8901 you should open this against https://github.com/veykril/tlborm/, since that's not Rust documentation. cc @Veykril

**Comment by compiler-errors** [comment]
Anyways, filed this as Veykril/tlborm#79
