### ISSUE TITLE
ELF binary built linked against fake loader

### ISSUE THREAD

**Issue by slondr** [rust-lang/rust#102993]
hi, I'm compiling a Rust program on my ARM AArch64 machine which is running linux with a musl libc. Rust wants to compile the binary with the interpreter set as `/lib/ld-linux-aarch64.so.1` which does not exist on my system. I do have `/lib/ld-musl-aarch64.so.1` however. 

As a result when I try to execute the binary built by rust in this case I just get ENOENT. In fact when I `strace ./binary` there is only a single syscall printed, the execve on the binary itself, which returns ENOENT. This makes me sad...

Manually loading the binary (ie running `exec /lib/ld-musl-aarch64.so.1 $PWD/binary`) gets me a lot farther in the execution of my program which then crashes for other reasons, presumably my fault :) But that's out of scope for this issue.

If it helps I installed Rust via rustup.

**Comment by compiler-errors** [comment]
See #82519 I think.

**Comment by bjorn3** [comment]
What linker did you tell rustc to use for AArch64?

**Comment by slondr** [comment]
@bjorn3  I am not cross-compiling, I'm just running `cargo build`

**Comment by bjorn3** [comment]
My bad. What does `rustc -vV` show?

**Comment by slondr** [comment]
@bjorn3 Here you go:

```
rustc 1.64.0 (a55dd71d5 2022-09-19)
binary: rustc
commit-hash: a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52
commit-date: 2022-09-19
host: aarch64-unknown-linux-musl
release: 1.64.0
LLVM version: 14.0.6
```

**Comment by jyn514** [comment]
The issue tracker is not a support forum. For future questions please ask in one of these places:

https://discord.gg/rust-lang/
https://discord.gg/rust-lang-community/
https://users.rust-lang.org/
https://rust-lang.zulipchat.com/

I suspect your current issue is a problem with your default linker, not the compiler itself.

**Comment by slondr** [comment]
For the record, I only posted this issue here after discussing it in the rust matrix chat, where I was told (after some group investigation) that it looked like a bug in cargo or rustc.

**Comment by jyn514** [comment]
Ok. You can use `cargo build -v` to show the invocations, and `RUSTFLAGS=--print=link-args` to see what's being passed to the linker. I'd still suggest trying to build a normal C program and make sure that works ok before building a rust program.

**Comment by jbg** [comment]
I just hit this as well. To be clear, no cross-compiling is involved. Both host and target are `aarch64-unknown-linux-musl`.

It seems to be triggered by external C library deps that cause the binary to be dynamically linked (rather than static as would be the default for `-musl` targets). The resulting binary always has the wrong loader, and only works if the `libc6-compat` package is installed.

Here's an example of reproducing it by linking `curl`. In a clean `alpine:3.17` container, reproduce as follows:

```sh
apk add build-base curl curl-dev pkgconf
curl https://sh.rustup.rs -sSf | sh -s -- -y
. ~/.cargo/env
cargo init --bin tester
cd tester
cargo add curl
echo 'use curl::easy::Easy; fn main() { Easy::new(); }' > src/main.rs
cargo build
```

Running the resulting binary fails:
```console
# target/debug/tester
/bin/sh: target/debug/tester: not found
```

The loader is wrong:
```console
# ldd target/debug/tester
	/lib/ld-linux-aarch64.so.1 (0xffffa0b61000)
	libcurl.so.4 => /usr/lib/libcurl.so.4 (0xffffa0ace000)
	libnghttp2.so.14 => /usr/lib/libnghttp2.so.14 (0xffffa0a8d000)
	libssl.so.3 => /lib/libssl.so.3 (0xffffa09e9000)
	libcrypto.so.3 => /lib/libcrypto.so.3 (0xffffa0663000)
	libbrotlidec.so.1 => /usr/lib/libbrotlidec.so.1 (0xffffa0642000)
	libz.so.1 => /lib/libz.so.1 (0xffffa0611000)
	libc.musl-aarch64.so.1 => /lib/ld-linux-aarch64.so.1 (0xffffa0b61000)
	libbrotlicommon.so.1 => /usr/lib/libbrotlicommon.so.1 (0xffffa05e0000)

# ls /lib/ld-linux-aarch64.so.1
ls: /lib/ld-linux-aarch64.so.1: No such file or directory
```

**Comment by jyn514** [comment]
@jbg do you have the same issue in a standalone C problem that links against curl? If so, this isn't a bug in the compiler itself. If not, you may want to talk to the owners of the curl crate on crates.io, there are various flags build scripts can pass that affect how the final program is linked. You can use `cargo build -vvv curl` to see build script output.

**Comment by bjorn3** [comment]
> It seems to be triggered by external C library deps that cause the binary to be dynamically linked (rather than static as would be the default for -musl targets). The resulting binary always has the wrong loader, and only works if the libc6-compat package is installed.

Does setting `RUSTFLAGS="-Ctarget-feature=-crt-static"` fix this issue?

**Comment by jbg** [comment]
No, linking isn't broken in Alpine in general, it's only Rust that has this issue.

```
rust-builder-test:~$ cat > curl.c
#include <curl/curl.h>

int main(void) {
  CURL *curl = curl_easy_init();
  return 0;
}
rust-builder-test:~$ gcc curl.c -lcurl -o curl
rust-builder-test:~$ ldd curl
	/lib/ld-musl-aarch64.so.1 (0xffffbef04000)
	libcurl.so.4 => /usr/lib/libcurl.so.4 (0xffffbee50000)
	libc.musl-aarch64.so.1 => /lib/ld-musl-aarch64.so.1 (0xffffbef04000)
	libnghttp2.so.14 => /usr/lib/libnghttp2.so.14 (0xffffbee0f000)
	libssl.so.3 => /lib/libssl.so.3 (0xffffbed6b000)
	libcrypto.so.3 => /lib/libcrypto.so.3 (0xffffbe9e5000)
	libbrotlidec.so.1 => /usr/lib/libbrotlidec.so.1 (0xffffbe9c4000)
	libz.so.1 => /lib/libz.so.1 (0xffffbe993000)
	libbrotlicommon.so.1 => /usr/lib/libbrotlicommon.so.1 (0xffffbe962000)
```

The `curl` crate was just a convenient example. All Rust crates that dynamically link a C library seem to be affected. `curl-sys` seems to just use the `pkg-config` crate in its `build.rs` which outputs the usual `rustc-link-lib` lines.

**Comment by bjorn3** [comment]
Does `gcc -static-pie curl.c -lcurl -o curl` have the same issue as rustc? Rustc will pass `-static-pie` on MUSL unless `-Ctarget-feature=-crt-static` is used to disable static linking.

**Comment by jbg** [comment]
`curl-static` is not installed, so linking fails with `-static-pie` (and must also fail if rust passes that when linking curl?)

```
$ gcc -static-pie curl.c -lcurl -o curl
/usr/lib/gcc/aarch64-alpine-linux-musl/12.2.1/../../../../aarch64-alpine-linux-musl/bin/ld: cannot find -lcurl: No such file or directory
collect2: error: ld returned 1 exit status
```

After installing the various required static libraries and amending the command to link them, gcc still produces a binary with the correct loader:

```
$ gcc -static-pie curl.c -lcurl -lssl -lcrypto -lz -lnghttp2 -lbrotlidec -lbrotlicommon -o curl
$ ldd curl
	/lib/ld-musl-aarch64.so.1 (0xffff90fab000)
```

**Comment by jbg** [comment]
The rust linker invocation when building the above example program with the `curl` crate is:

```"cc" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/crt1.o" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/crti.o" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/crtbegin.o" "/tmp/rustcvSxskF/symbols.o" "/home/app/tester/target/debug/deps/tester-215b1acbed4714d0.23v6dd6gnzxsr0s5.rcgu.o" "/home/app/tester/target/debug/deps/tester-215b1acbed4714d0.4dt189f4dyl9j8vw.rcgu.o" "/home/app/tester/target/debug/deps/tester-215b1acbed4714d0.4gbgwgnrj8n5169z.rcgu.o" "/home/app/tester/target/debug/deps/tester-215b1acbed4714d0.61safi306wbxgy0.rcgu.o" "/home/app/tester/target/debug/deps/tester-215b1acbed4714d0.mxi8xlc1ysy99fp.rcgu.o" "/home/app/tester/target/debug/deps/tester-215b1acbed4714d0.3c9i9azmr8v9rblc.rcgu.o" "-Wl,--as-needed" "-L" "/home/app/tester/target/debug/deps" "-L" "/usr/lib" "-L" "/lib" "-L" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib" "-Wl,-Bstatic" "/home/app/tester/target/debug/deps/libcurl-2f6194c65c51f1e9.rlib" "/home/app/tester/target/debug/deps/libsocket2-0083cc04d93ebdab.rlib" "/home/app/tester/target/debug/deps/libcurl_sys-196fe6cf0eeb8504.rlib" "/home/app/tester/target/debug/deps/liblibc-a9a6a976b0a6ad02.rlib" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/libstd-ae17b16940af2365.rlib" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/libpanic_unwind-2b0142bfc7026d5f.rlib" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/libobject-7a0ca05b7d8fab32.rlib" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/libmemchr-9a064688bd82d012.rlib" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/libaddr2line-e4e5a05a96e35b9c.rlib" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/libgimli-6f278cc924fd0ba8.rlib" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/librustc_demangle-97a3515a22332f3b.rlib" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/libstd_detect-0ec64aafbef4d0f1.rlib" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/libcfg_if-b1cd2eea3d76a265.rlib" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/libhashbrown-bd335344f313ebfd.rlib" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/libminiz_oxide-45416aec543333a9.rlib" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/libadler-108cbf5f7b726a2f.rlib" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/librustc_std_workspace_alloc-1c1fe643ea1c8e21.rlib" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/libunwind-39a97ef386de6c62.rlib" "-lunwind" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/libcfg_if-7a73fff29ca7856e.rlib" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/liblibc-b944c66ee70b3134.rlib" "-lc" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/liballoc-8ea6846373ecca10.rlib" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/librustc_std_workspace_core-06b5cf25321492b2.rlib" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/libcore-7d43051c8e116420.rlib" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/libcompiler_builtins-06fe9ef48f62ded5.rlib" "-Wl,-Bdynamic" "-lcurl" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-nostartfiles" "-L" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib" "-L" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained" "-o" "/home/app/tester/target/debug/deps/tester-215b1acbed4714d0" "-Wl,--gc-sections" "-static" "-no-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/crtend.o" "/home/app/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/crtn.o"```

Guessing at the problematic bits, I was able to recreate the same issue with the `curl.c` example like this:

```
$ gcc -c -o curl.o curl.c
$ gcc -o curl curl.o -Wl,-Bdynamic -lcurl -static
$ ldd curl
	/lib/ld-linux-aarch64.so.1 (0xffffb387c000)
	libcurl.so.4 => /usr/lib/libcurl.so.4 (0xffffb37e9000)
	libc.musl-aarch64.so.1 => /lib/ld-linux-aarch64.so.1 (0xffffb387c000)
	libnghttp2.so.14 => /usr/lib/libnghttp2.so.14 (0xffffb37a8000)
	libssl.so.3 => /lib/libssl.so.3 (0xffffb3704000)
	libcrypto.so.3 => /lib/libcrypto.so.3 (0xffffb337e000)
	libbrotlidec.so.1 => /usr/lib/libbrotlidec.so.1 (0xffffb335d000)
	libz.so.1 => /lib/libz.so.1 (0xffffb332c000)
	libbrotlicommon.so.1 => /usr/lib/libbrotlicommon.so.1 (0xffffb32fb000)
```

**Comment by jbg** [comment]
FWIW, folks on #musl IRC say that rust is invoking the linker in a broken way here by using `-Bdynamic` together with `-static`. The root cause of the wrong loader is that gcc is not passing `-dynamic-linker` to `ld` and thus `ld` is using its default, but even if the loader was correct, the binary would be somewhat broken and have two copies of libc.

Maybe trying to dynamically link should be an error if the `crt-static` target feature is enabled?

**Comment by bjorn3** [comment]
That nakes sense.

> Maybe trying to dynamically link should be an error if the crt-static target feature is enabled?

At the very least it should he a warning pointing you to `-Ctarget-feature=-static-crt`. Not sure if ot should be an error. There may be targets that support this combination I guess.

**Comment by jbg** [comment]
Is it possible for the default of `crt-static` to change based on the host as well as based on the target?

I can understand the motivation for making `crt-static` the default for the `*-unknown-linux-musl` targets because they have usually been used to build self-contained static binaries, often cross-compiling from a glibc host. But when you are e.g. running Alpine and trying to build programs for the local system, it would be much more sensible for it to dynamically link libc so that dynamic linking can work as normal. The Alpine packages for rust actually patch this to remove the `crt-static` target feature from the `-musl` targets, but rustup does not.

**Comment by bjorn3** [comment]
There is an MCP to move *-musl to dynamic linking by default, but it isn't actually implemented yet and will need some care to notify everyone currently using musl for static linking. https://github.com/rust-lang/compiler-team/issues/422

**Comment by jbg** [comment]
https://github.com/rust-lang/rust/issues/59302 is relevant

**Comment by Amanieu** [comment]
The root cause seems to be here:
https://github.com/rust-lang/rust/blob/ad23942ad4079f779651983b262fa34c0beda701/compiler/rustc_codegen_ssa/src/back/link.rs#L2478-L2482

If no `kind` is specified in the `#[link]` attribute then we already attempt to link a dynamic library.

**Comment by WhyNotHugo** [comment]
Is there any reason why Rust can't link binaries dynamically by default on *-unknown-linux-musl like it does on *-unknown-linux-gnu?

It seems weird that the behaviour for one libc is different to the other, and the norm on Linux is to dynamically link libraries.

**Comment by jyn514** [comment]
@WhyNotHugo see https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/Update.20the.20existing.20musl.20targets.20to.20be.20dy.E2.80.A6.20compiler-team.23422
