### ISSUE TITLE
error: internal compiler error: unexpected panic

### ISSUE THREAD

**Issue by andydGoram** [rust-lang/rust#102969]
### Code

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by matthiaskrgr** [comment]
@andydGoram  do you have any details like the backtrace or the code/crate you were compiling?
Right now this ticket is not actionable and we'll just have to close it without further details given.

**Comment by compiler-errors** [comment]
@andydGoram please open up a new issue if you actually found an compiler panic, thanks!
