### ISSUE TITLE
Struct update behaves differently to explicitly destructuring when it comes to reborrowing

### ISSUE THREAD

**Issue by Alfred-Mountfield** [rust-lang/rust#103063]
This feels like very much an edge-case, but as you can see in [this playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b06ede397ba7665727e95e8e646bac4c), destructuring seems to reborrow elements within the struct, whereas struct updates don't.

Some members of the community discord informed me that this likely isn't a bug, so I'm reporting just in case it's something that should be covered, rather than saying it's a problem.

**Comment by jyn514** [comment]
This is not a bug. `..foo` moves `foo`, so since it's not marked Copy you can't use it again after that. `foo.quz` is a Copy type, so you're allowed to use it again after the move.
