### ISSUE TITLE
Illegal Eq derive in an enum with Option<f64>

### ISSUE THREAD

**Issue by stepantubanov** [rust-lang/rust#103157]
I tried this code:

```rust
#[derive(PartialEq, Eq)]
pub enum Value {
    Boolean(Option<bool>),
    Float(Option<f64>),
}

fn main() {
    let a = Value::Float(Some(f64::NAN));
    
    // Eq should always have a == a
    // https://doc.rust-lang.org/std/cmp/trait.Eq.html
    assert!(a == a);
}
```

I expected to see this happen: code fails to compile.
Instead, this happened: code compiles, and assertion fails.

Changing order of enum variants to make `Float` go first fixes the issue:
```
// error[E0277] the trait bound `f64: Eq` is not satisfied
#[derive(PartialEq, Eq)]
                    -- in this derive macro expansion
pub enum Value {
    Float(Option<f64>),
    Boolean(Option<bool>),
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.64.0 (a55dd71d5 2022-09-19)
binary: rustc
commit-hash: a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52
commit-date: 2022-09-19
host: aarch64-apple-darwin
release: 1.64.0
LLVM version: 14.0.6
```

It's reproducible in [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=cdd56f0d98da2afa2a89f076e3ad8ec7) in Stable, Beta and Nightly.

**Comment by Nilstrieb** [comment]
Expanding the macro yields a ```rust
impl ::core::cmp::Eq for Value {
    #[inline]
    #[doc(hidden)]
    #[no_coverage]
    fn assert_receiver_is_total_eq(&self) -> () {
        let _: ::core::cmp::AssertParamIsEq<Option<bool>>;
    }
}
```
looks like it only asserts `Eq`ness for the first field - whoops!

@rustbot claim

**Comment by Nilstrieb** [comment]
Gonna hand it over to you @fuzzypixelz as discussed on zulip
@rustbot release

**Comment by SNCPlay42** [comment]
On 1.63.0 this failed to compile, as expected ([godbolt](https://rust.godbolt.org/z/KPoGWs97c)):

```
error[E0277]: the trait bound `f64: Eq` is not satisfied
 --> <source>:4:11
  |
1 | #[derive(PartialEq, Eq)]
  |                     -- in this derive macro expansion
...
4 |     Float(Option<f64>),
  |           ^^^^^^^^^^^ the trait `Eq` is not implemented for `f64`
  |
  = help: the following other types implement trait `Eq`:
            i128
            i16
            i32
            i64
            i8
            isize
            u128
            u16
          and 4 others
  = note: required because of the requirements on the impl of `Eq` for `Option<f64>`
note: required by a bound in `AssertParamIsEq`
  = note: this error originates in the derive macro `Eq` (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error
```

@rustbot label regression-from-stable-to-stable

**Comment by Nilstrieb** [comment]
this was recently introduced when @nnethercote was doing derive optimizations.

**Comment by nnethercote** [comment]
I'll take a look today, thanks for the report.

**Comment by Nilstrieb** [comment]
Don't worry, we've found the issue already, just wanted to let you know.

**Comment by nnethercote** [comment]
See #103176 for the fix.
