### ISSUE TITLE
`std::error::Error` docs don't mention `e.downcast()` (only `downcast_{ref,mut}`)

### ISSUE THREAD

**Issue by thomcc** [rust-lang/rust#103170]
I didn't notice an issue on file for this already, feel free to dupe against it if one exists.

In https://github.com/rust-lang/rust/pull/99917 we landed support for error in core, and sadly one of the casualties was the docs got somewhat worse. Concretely, `Box<dyn Error + stuff>::downcast()` is no longer shown on the [docs page for Error](https://doc.rust-lang.org/nightly/std/error/trait.Error.html#method.request_ref), which is a bit of a bummer, since these methods do exist: https://doc.rust-lang.org/nightly/src/alloc/boxed.rs.html#2127

**Comment by jyn514** [comment]
I don't think rustdoc supports incoherent impls like this.

**Comment by thomcc** [comment]
That's unfortunate. `Error` is an important trait, and its docs are notably worse after that PR. If supporting that is too hard, it might be worth special-casing it (Failing that, manually documenting this stuff is an option I suppose).
