### ISSUE TITLE
Drop order twist of && and || chains

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#103107]
If you consider the following program:

```Rust
struct LoudDrop(&'static str);

impl Drop for LoudDrop {
    fn drop(&mut self) {
        print!("{},", self.0);
    }
}

impl LoudDrop {
    fn foo(&self) -> bool {
        true
    }
}

fn main() {
    if LoudDrop("1").foo() &&
    LoudDrop("2").foo() &&
    LoudDrop("3").foo() &&
    LoudDrop("4").foo() {}
    println!("");

    let _b = LoudDrop("1").foo() &&
    LoudDrop("2").foo() &&
    LoudDrop("3").foo() &&
    LoudDrop("4").foo();
    println!("");

    if !LoudDrop("1").foo() ||
    !LoudDrop("2").foo() ||
    !LoudDrop("3").foo() ||
    !LoudDrop("4").foo() {}
    println!("");

    let _b = !LoudDrop("1").foo() ||
    !LoudDrop("2").foo() ||
    !LoudDrop("3").foo() ||
    !LoudDrop("4").foo();
    println!("");
}
```

It will print "2,3,4,1," four times. The issue occurs on recent nightly as well as all the way back to 1.0.0. This is a bit weird IMO, and makes && and || chains non-associative. IMO it's a bug that should be fixed to print "1,2,3,4,".

IDK how much we can do about this at the current point, given backwards compatibility concerns. It might not stop programs from compiling, but programs might differ in their runtime output. There is [RFC 1857](https://github.com/rust-lang/rfcs/pull/1857) with the name "Stabilize drop order" but if you read the text, it only concerns the drop order of structs, vecs, tuples, etc. Also, after the merge, the RFC author themself made a PR to add regression tests in #43125 , and mentioned that that PR was enough for getting the RFC tested. The RFC didn't include anything about && chains. I think the language should not be interpreted too generally.

It took a long time until #100526 in which we we got some further drop order tests for "established" language constructs, while there have been many PRs with drop order tests for let-else.

Originally I've discovered this in: https://github.com/rust-lang/rust/pull/102998#discussion_r996153602 , but given that it's so visible, I'm sure that someone else has already complained about this.

Maybe one can just implement the change to "1,2,3,4," and make a crater run for it?

cc @Nilstrieb @nathanwhit

@rustbot label T-lang

**Comment by jonnius** [comment]
Just for the record, fixing this also fixed https://github.com/rust-lang/rust-clippy/issues/7965.
