### ISSUE TITLE
Implement dynamic string interpolation

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#10318]
In a perfect world, a minimal quine in Rust would look like this:

```rust
fn main(){let S="fn main(){let S={1}{0}{1};println!(S,S,'{1}')}";println!(S,S,'"')}
```

Sadly, this is impossible. Why? Because `println!` requires that the first argument not just be static; it must be a *string literal*.

There are other, non-contrived use cases for dynamic string interpolation; acrichto mentions internationalization as one example.

So what would be involved in implementing dynamic string interpolation?

acrichto mentions (https://botbot.me/mozilla/rust/msg/7556963/) that the current machinery used to parse strings for `format!` provides an interface that could be reused (`std::fmt`). But that's only part of the solution.

The first issue is that we can't guarantee type safety for dynamic interpolation (can we???), so the syntax for dynamic format strings might need to be rethought. For now we should probably assume that all arguments to dynamic string interpolation will implement `ToStr` and just ignore any format string options that aren't for positional or named arguments.

The second issue is that we can't just simply have anything like a simple `.format()` method on strings, like Python has, since we don't have variadic functions. We'd need to either do something like pass an array of trait objects:

```rust
"ab{1}d{0}".format(["e" as ~ToStr, "c" as ~ToStr]);  // gross
dyn_format!("ab{1}d{0}", "e", "c");  // maybe a little less gross
```
...or use method chaining and generics:

```rust
fn push<T: Any>(&mut self, x: T) { self.vec.push(~x as ~Any) }
"ab{1}d{0}".format().push("e").push("c").to_str()  // still kinda gross
```

(all code examples are just quick sketches, might be overlooking details (and don't worry about naming))

Any thoughts?

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#642
