### ISSUE TITLE
Create a tool to generate semantically correct tags files

### ISSUE THREAD

**Issue by chris-morgan** [rust-lang/rust#10317]
Currently we have the `TAGS.vi` and `TAGS.emacs` rules which use Exuberant Ctags and regular expressions to produce a very useful but not particularly brilliant result. Now that we have librustdoc, we can do much better, rather quickly! I want a tool (quite probably built into rustdoc, actually) which can generate semantically correct and optimally useful tags files for the Vim and Emacs standards. Doing this absolutely correctly will be a great help to developers, who will already benefit if they go to the trouble of ensuring they have the tags files loaded in their editor.

This will allow things like adding enum variants to the tags file which probably can't be done correctly at present (and no attempt is made) as I think you could have further nested parentheses inside the variant, e.g. I think `Foo((), (bar, ()))` would be valid, but it'd make a mess of a regex-based rule unless recursion could actually be managed in a nasty hacky way.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#656
