### ISSUE TITLE
Simplify --exclude syntax and make it more useful

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#103201]
I think we should have a holistic conversation about what excludes should look like. The current syntax is currently quite baroque and AFAIK @pietroalbini's CI scripts are the only ones using most of the features. Slapping git-style ignores on top seems like it will make things more confusing, not less.

That said, I agree the behavior is confusing and there's room for improvement; I'd love to get rid of the `doc::` prefixes somehow and make the various paths unambiguous.

See https://rust-lang.zulipchat.com/#narrow/stream/326414-t-infra.2Fbootstrap/topic/excludes for the discussion; this issue is just a placeholder so it doesn't get lost.

_Originally posted by @jyn514 in https://github.com/rust-lang/rust/pull/102706#pullrequestreview-1145802650_

**Comment by jyn514** [comment]
> That said, I agree the behavior is confusing and there's room for improvement; I'd love to get rid of the `doc::` prefixes somehow and make the various paths unambiguous.

I wonder if we could do this by making it so that `--exclude` only applies to the subcommand *that was run*; so for example `x test --exclude library/std` would behave the same as `x test --exclude test::library/std` today. I don't think there's a use case for `x test --exclude doc::library/std`, that will cause tests to fail anyway.

**Comment by pietroalbini** [comment]
> I don't think there's a use case for x test --exclude doc::library/std, that will cause tests to fail anyway.

So, I just checked and in Ferrocene we don't use `--exclude test::library/std` (or any `kind::` prefix) anymore after a CI refactor (linkchecker runs in a separate job than tests now), so I don't think I'm a blocker for this anymore.

The behavior you mentioned would still fix https://github.com/rust-lang/rust/issues/91794, and I don't see any extra reasoning in https://github.com/rust-lang/rust/pull/91965 that would require a `doc::` prefix when running tests.

**Comment by jyn514** [comment]
Mentoring instructions:
1. Change `is_excluded` to always return `false` if `step_description.kind != builder.config.kind`: https://github.com/rust-lang/rust/blob/390551716a5f16907e48b21934a66090fd8ef78d/src/bootstrap/builder.rs#L301
2. Remove `TaskPath` and replace all uses with `Path` directly: https://github.com/rust-lang/rust/blob/390551716a5f16907e48b21934a66090fd8ef78d/src/bootstrap/builder.rs#L139-L142
