### ISSUE TITLE
A `:` instead of a `::` in a path of a `use` item should be a recoverable parsing error

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#103269]
I tried this code:

```rust
use std::process:Command;
use std::fs:File;

fn main() { }
```

I expected to see this happen: I expected to see two diagnostic messages, telling me about the distinct parse errors on lines 1 and 2.

Instead, this happened: The first error was treated as non-recoverable, yielding this output ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=90aeabb0d8644475e2614849634206df)):

```
error: expected one of `::`, `;`, or `as`, found `:`
 --> src/main.rs:1:17
  |
1 | [use std::process:Command;](https://play.rust-lang.org/#)
  |                 ^ expected one of `::`, `;`, or `as`

error: could not compile `playground` due to previous error
```

----

I'm **assuming** recovering in the face of this parse error would be a relatively simple task, given that there is already the `:` present that should be a strong hint that someone meant to type `::`.  So I'm tagging this with labels indicating that its a good opportunity for someone who wants to acquaint themselves with the code base.

**Comment by pnkfelix** [comment]
(This needs a mentor. I am thinking that if someone doesn't pick it up by Friday, then I will see about using it as the basis for one or more instructional videos.)

**Comment by compiler-errors** [comment]
I can mentor whoever wants to work on this. See https://github.com/rust-lang/rust/blob/master/compiler/rustc_parse/src/parser/item.rs#L950 for the general area where changes need to be made, and ping me if someone needs help on Zulip.

**Comment by me-diru** [comment]
May I work on this?

**Comment by compiler-errors** [comment]
You can [claim an issue with rustbot](https://rustc-dev-guide.rust-lang.org/rustbot.html), and I recommend checking out the [rustc dev guide](https://rustc-dev-guide.rust-lang.org/contributing.html) to find out what the contribution process looks like.

**Comment by chetankokil** [comment]
@compiler-errors i would like to work on this with your help.

**Comment by fee1-dead** [comment]
This is mostly about tweaking the `eat(token::ModSep)` code such that it works with `token::Colon` as well. [src](https://doc.rust-lang.org/beta/nightly-rustc/src/rustc_parse/parser/item.rs.html#950)

However, we would also need this to be configurable in `parse_path`, as we would want to recover from `use std:process::Command` as well.

**Comment by mucinoab** [comment]
I will take a quick look into this.
@rustbot claim
