### ISSUE TITLE
Misleading documentation for str::match_indices

### ISSUE THREAD

**Issue by jruderman** [rust-lang/rust#103232]
### Location

https://doc.rust-lang.org/std/primitive.str.html#method.match_indices
### Summary

```rust
fn main() {
    let v: Vec<_> = "abababa".match_indices("aba").collect();
    assert_eq!(v, [(0, "aba"), (4, "aba")]);
}
```

**Comment by ehuss** [comment]
I'm going to close, assuming this was an unintentional duplicate of #103235. Feel free to reopen in case I misinterpreted.
