### ISSUE TITLE
Miri fails to test with tokio compilation error

### ISSUE THREAD

**Issue by SUPERCILEX** [rust-lang/rust#103273]
@RalfJung 

```console
$ ./x.py test tools/miri
```

This is the absolute unit of an error: https://pastebin.com/EakKbQw5. It's so long it doesn't even fit in github.

**Comment by SUPERCILEX** [comment]
Just noticed there's mention of serialization, so maybe I just need to run a clean?

**Comment by SUPERCILEX** [comment]
Oh yep, a clean did the trick.

**Comment by RalfJung** [comment]
Phew, happy that did it.^^
FWIW, `--stage 0` should work and save you a bunch of time.
