### ISSUE TITLE
`x.py build` no longer places `rustc` and `rustdoc` binaries into `stage2/` with config `profile = "tools"`

### ISSUE THREAD

**Issue by fmease** [rust-lang/rust#103206]
`./x.py b` with `profile = "tools"` in `config.toml` no longer places `rustc` & `rustdoc` into `build/$TARGET/stage2/bin/` but just into `build/$TARGET/ci-rustc-sysroot/bin/`.
Tested on Linux.

[Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/Where.20does.20x.2Epy.20but.20stage2.20rustdoc/near/304099796).

@rustbot label T-infra A-bootstrap A-contributor-roadblock

**Comment by jyn514** [comment]
I'm not convinced the binaries in `ci-rustc-sysroot` are actually the newly compiled binaries; I think they may just never be copied from `stage1-tools-bin` into a sysroot.

**Comment by fmease** [comment]
> I'm not convinced the binaries in ci-rustc-sysroot are actually the newly compiled binaries

I am not familiar enough with the bootstrap process to be able to confirm or dispute this.
As far as I'm concerned, I've relinked my `rustup` toolchain `stage2` to `ci-rustc-sysroot` and everything appears to work flawlessly.

**Comment by jyn514** [comment]
@fmease can you send the output of `rustc +stage2 --version` and `rustdoc +stage2 --version`?

**Comment by fmease** [comment]
Both output `rustc 1.66.0-nightly (e94827e5b 2022-10-18)`.

**Comment by jyn514** [comment]
yeah that looks like it's not actually reflecting your changes, just using the latest nightly unmodified

**Comment by fmease** [comment]
Hmm, that can't be. I am currently working on fixing #24183 and modifications to the rustdoc source code are indeed properly reflected in the compiled binaries. Maybe the version string is just wrong but my local changes *are* picked up.

**Comment by fmease** [comment]
Actually, I have a counterquestion. Can *you* reproduce this? Or is it just me and @aDotInTheVoid?
