### ISSUE TITLE
std lib compile errors for uwp-windows-msvc targets

### ISSUE THREAD

**Issue by korejan** [rust-lang/rust#103233]
Building std library (-Zbuild-std) with nightly for uwp-windows-msvc targets has been failing with compile errors since around after 17/10/22

```rust
   Compiling panic_abort v0.0.0 (C:\Users\runneradmin\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\panic_abort)
error[E0425]: cannot find function, tuple struct or tuple variant `GetConsoleMode` in module `c`
  --> C:\Users\runneradmin\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys\windows\io.rs:99:11
   |
99 |     if c::GetConsoleMode(handle, &mut out) != 0 {
   |           ^^^^^^^^^^^^^^ not found in `c`

error[E0425]: cannot find function, tuple struct or tuple variant `GetConsoleMode` in module `c`
   --> C:\Users\runneradmin\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys\windows\io.rs:112:19
    |
112 |             && c::GetConsoleMode(std_handle, &mut out) != 0
    |                   ^^^^^^^^^^^^^^ not found in `c`

```

I expected to see this happen:

Last successeful build on 16/10:

https://github.com/korejan/ALXR-nightly/actions/runs/3257338692/jobs/5348560568

Instead, this happened:

Lastest failed build:

https://github.com/korejan/ALXR-nightly/actions/runs/3277318460/jobs/5394484131

### Version it worked on

It most recently worked on: rustc 1.66.0-nightly (bf15a9e52 2022-10-14)

### Version with regression

`rustc --version --verbose`:
```
rustc 1.66.0-nightly (b8b5caee0 2022-10-16)
```

### Backtrace

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by korejan** [comment]
Hey, is anyone looking into this because ALXR ci (uwp) builds are failing for over a week. Should this issue be posted in another repo?

**Comment by thomcc** [comment]
This is the right repo, but it fell through the cracks for whatever reason. I can get to it this weekend.

**Comment by korejan** [comment]
> This is the right repo, but it fell through the cracks for whatever reason. I can get to it this weekend.

Thank you :)
