### ISSUE TITLE
-Z panic_abort_tests does not support #[bench]

### ISSUE THREAD

**Issue by tmandry** [rust-lang/rust#103261]
If we try to run a test binary built with `-Z panic-abort-tests` and that test has a function with the `#[bench]` attribute, the binary will panic with the following error:

`thread 'main' panicked at 'Cannot run dynamic test fn out-of-process', library/test/src/lib.rs:549:22`

This is because we convert `#[bench]` to a test using `DynTestFn` when not running benchmarks, but `DynTestFn` is not supported with `-Z panic-abort-tests`, because we must run tests out of process and don't have a way to pass a closure to another process.

**Comment by ehuss** [comment]
I think this may be a duplicate of #73509?

**Comment by tmandry** [comment]
Yep, thanks.
