### ISSUE TITLE
Add explanatory message for `[#must_use]` on `std::ops::Add` et al

### ISSUE THREAD

**Issue by jruderman** [rust-lang/rust#103320]
Given the following code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=9392fe010d75beaff3cc8a1208029775)):

```rust
use std::ops::Add;

fn main() {
    let mut x = 2_u32;
    x += 3;
    x.add(4);
    println!("{}", x);
}
```

The current output is:

```
warning: unused return value of `add` that must be used
 --> src/main.rs:6:5
  |
6 |     x.add(4);
  |     ^^^^^^^^^
  |
  = note: `#[warn(unused_must_use)]` on by default
```

Ideally the output should include:

```
  = note: this returns the result of the operation, without modifying the original
```

### Precedent

Many other `std` methods have this exact `must_use` message, e.g. ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=c20233d41476ec3e31400d8e052d0ff6)):

```rust
use std::path::Path;

fn f(p: &Path) { 
    p.to_str();    
}
```

which gives the warning:

```
warning: unused return value of `Path::to_str` that must be used
 --> src/lib.rs:4:5
  |
4 |     p.to_str();    
  |     ^^^^^^^^^^^
  |
  = note: this returns the result of the operation, without modifying the original
  = note: `#[warn(unused_must_use)]` on by default
```

**Comment by chenyukang** [comment]
Change this line:

https://cs.github.com/rust-lang/rust/blob/5c8bff74bc1c52bef0c79f3689bb227f51f3e82d/library/core/src/ops/arith.rs#L89

to 

```rust
 #[must_use = "this returns the result of the operation, \
                  without modifying the original"]
```

will fix it, we may add attribute value to other trait such as `Sub`, `Mul`.
I'm not sure why whether it's necessary to keep it. 
@m-ou-se How do you think about it?
