### ISSUE TITLE
search on https://doc.rust-lang.org/ not doing well

### ISSUE THREAD

**Issue by szabgab** [rust-lang/rust#103357]
I could not figure out a better place to report the issue with https://doc.rust-lang.org/  (which might be an issue on its own, to have a link from the docs to the source code)

The problem is that the search on https://doc.rust-lang.org/ does not seem to function well:

e.g. https://doc.rust-lang.org/std/index.html?search=regex returns lots of hits, none of them related to regex.

OTOH https://doc.rust-lang.org/std/index.html?search=println works quite well.

https://doc.rust-lang.org/std/index.html?search=print starts out quite well, but then also includes things that end with `::pin` and `::hint` that seem to be unrelated.

**Comment by Manishearth** [comment]
cc @rust-lang/rustdoc 

This is a rustdoc search issue


In general for the regex thing there's not much to be done since there's no regex in the stdlib (use docs.rs/regex). I suspect the unrelated ones come up due to Levenshtein distance searching (and same for pin)

Basically, rustdoc search attempts to catch typos, and that's what you're experiencing.

**Comment by jsha** [comment]
One problem here is that our acceptable Levenshtein distance is too high: we allow results with up to 3 edits (character deletion, insertion, or removal). For a query like regex, that means we allow deleting up to 3 characters to match an unreleated name like "ge". Reducing the max Levenshtein distance to 2 would go a long way towards improving these no-match cases. I think its exceedingly rare for something to be a real match at a distance of 3.

Also, we should do a better job of explaining to the user what the scope of the search is: the standard library; or a single crate; or a group of crates. Right now on no-results we show the same output, regardless of whether we're on doc.rust-lang.org or docs.rs or something else.

> No results :(
> Try on [DuckDuckGo](https://duckduckgo.com/?q=rust%20regexzv)?
>
> Or try looking in one of these:
> The [Rust Reference](https://doc.rust-lang.org/reference/index.html) for technical details about the language.
> [Rust By Example](https://doc.rust-lang.org/rust-by-example/index.html) for expository code examples.
> The [Rust Book](https://doc.rust-lang.org/book/index.html) for introductions to language features and the language itself.
> [Docs.rs](https://docs.rs/) for documentation of crates released on [crates.io](https://crates.io/).

**Comment by szabgab** [comment]
Thanks for all the responses so far!

Related to the source of the results:

As a newbie definitely, but also as an advanced user I'd probably prefer a dedicated search engine that would search in both std and crates (and maybe also in the reference and the books).
After all I don't know if a certain feature (e.g. regexes in my case) are part of what comes with Rust or a 3rd party crate.

It might be a good idea to give preference to results from std over the crates and over the books. It would be probably also good to let the user filter the search based on the source.

**Comment by fmease** [comment]
> I think the acceptable Levenshtein distance really depends on the query length.

That's what the `rustc` name resolver does (last time I checked) when it encounters unresolved identifiers. Namely:

```rust
strsim::levenshtein(other_identifier, identifier) <= std::cmp::max(identifier.len(), 3) / 3
```
