### ISSUE TITLE
Point at shadowed name binding in `you might have meant to refer to` suggestion

### ISSUE THREAD

**Issue by cjgillot** [rust-lang/rust#103358]
Makes sense, I just would rather we pointed at the ident for the item and not the whole thing.

_Originally posted by @estebank in https://github.com/rust-lang/rust/pull/103111#discussion_r1001294984_

The suggestion was introduced by #103111. The suggestion point to the definition of the suggested item. Pointing to the shadowed identifier would be more precise:
- the ident of the item in case of direct reference;
- the import in case of indirect reference.

**Comment by fee1-dead** [comment]
For this to work, either we would try to look at the `DefKind` of the `Res` as according to the [docs](https://doc.rust-lang.org/beta/nightly-rustc/rustc_hir/def/enum.Res.html#variant.Def), and then make the span point to the item name using the [`SourceMap`](https://doc.rust-lang.org/beta/nightly-rustc/rustc_span/source_map/struct.SourceMap.html) if we know how the item looks. Alternatively, we could use [`guess_head_span`](https://doc.rust-lang.org/beta/nightly-rustc/rustc_span/source_map/struct.SourceMap.html#method.guess_head_span) to make it a bit more precise. Am I missing something here? Would there be a better way to get the span of the ident of the item?

**Comment by cjgillot** [comment]
There is probably a simpler way, by storing the `Span` of the `Ident` that introduced the name in `TypoSuggestion`, and use that span instead of trying to get one from the `Res`.
