### ISSUE TITLE
Vec::capacity documentation is ambiguous

### ISSUE THREAD

**Issue by akonradi** [rust-lang/rust#103326]
### Location
Standard library documentation for `Vec::capacity` (https://doc.rust-lang.org/std/vec/struct.Vec.html#method.capacity)

### Summary
It's not clear whether the returned capacity is the _total_ capacity or _remaining_ capacity of the vector. The text and example don't seem to signal either way.

**Comment by the8472** [comment]
The top-level documentation provides context: https://doc.rust-lang.org/std/vec/struct.Vec.html#capacity-and-reallocation
