### ISSUE TITLE
Suggest fix for misplaced generic params on `fn` item

### ISSUE THREAD

**Issue by jruderman** [rust-lang/rust#103366]
Given the following code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=c43061fdd99675fe34603630cc40c25a)):

```rust
fn<T> id(x: T) -> T { x }
```

The current output is:

```
error: expected identifier, found `<`
 --> src/lib.rs:1:3
  |
1 | fn<T> id(x: T) -> T { x }
  |   ^ expected identifier
```

Ideally the output should look also include:

```
help: place the generic parameter list after the function name:
  |
1 | fn id<T>(x: T) -> T { x }
  |      ~~~
```

This is an easy mistake to make because `impl` items _do_ require the generic parameters to go immediately after the keyword.

**Comment by compiler-errors** [comment]
this probably should be generalized for the other item kinds as well (`struct`, `enum`, `trait`, and `union`), if someone is planning on implementing this.

**Comment by SpanishPear** [comment]
Would this make a good first issue to look at?

**Comment by SpanishPear** [comment]
@rustbot claim 

Let's give it a try anyways :partying_face:

**Comment by jruderman** [comment]
Here are some potentially tricky cases:

#### Complicated bounds

aka "the programmer probably should have moved some of this into a `where` clause" 

```rust
fn<'a, B: 'a + std::ops::Add<Output = u32>> f(_x: B) { }

fn main() {
    f(1_u32);
}
```

#### Generic bounds also present in the correct place

```rust
fn<T: Send> g<T>(x: T) -> T { x }
```

Here, the compiler should avoid suggesting modified code that also won't parse. Simply moving `<T: Send>` to after the function name in this case would result in `fn g<T: Send><T>`, which isn't right.

Ideally, for this specific example, it would suggest replacing the second with the first, creating `fn g<T: Send>`. But it's probably not worth the complexity to try to determine "how compatible" two generics lists are and how best to merge them.

For this case, I'd be happy enough with an error message that doesn't include a suggestion, or simply suggesting the removal of the first generics list.
