### ISSUE TITLE
Suggestion "you might have meant to call the method with the fully-qualified path" without a call

### ISSUE THREAD

**Issue by jruderman** [rust-lang/rust#103325]
Given the following code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=7a747237d87e5e7b05441c29e800f80a)):

```rust

trait Tr {
    fn use_mut(&mut self) {
    }
    fn oops() {
        let _ = use_mut;
    }
}
fn main() {}
```

The current output is:

```
error[E0425]: cannot find value `use_mut` in this scope
 --> src/main.rs:5:17
  |
5 |         let _ = use_mut;
  |                 ^^^^^^^
  |
help: you might have meant to call the method with the fully-qualified path
  |
5 |         let _ = Self::use_mut;
  |                 ~~~~~~~~~~~~~
```

It's odd for the message to say "you might have meant to call..." and then show a suggestion that does not call anything.

### Possible improvements

I'm not sure which would be best:
* When it isn't part of a call expression, change the suggestion to say "refer to the method" instead of "call the method"
* When it isn't part of a call expression, augment the suggestion to also add parens, turning it into a call expression
* When it isn't part of a call expression, don't show this message: the lack of parens might indicate that the programmer was trying to do something else entirely

Btw, there don't seem to be any tests that expect this message. It might be good to add one to ensure the common case (where it _is_ a call expression) continues to have a good error message.

**Comment by compiler-errors** [comment]
> When it isn't part of a call expression, change the suggestion to say "refer to the method" instead of "call the method"

This is the best one, imo. Adding parentheses changes the program in a way that's not the responsibility of name resolution, imo.
