### ISSUE TITLE
MSVC .msi doesn't install latest (GNU .msi does)

### ISSUE THREAD

**Issue by mdnava** [rust-lang/rust#103458]
Hello,

The offline installer is my preferred method for installing/updating. Current version of Rust is 1.64.0 but the latest MSVC .msi package has been installing rustc 1.60.0 in all new versions since April. At least that's what the --version parameter indicates.

However, if I use the GNU .msi package it does install the latest version (v1.64.0).

**Package:** https://static.rust-lang.org/dist/rust-1.64.0-x86_64-pc-windows-msvc.msi
**Installed:** Rust 1.**60**.0

**Package:** https://static.rust-lang.org/dist/rust-1.64.0-x86_64-pc-windows-gnu.msi
**Installed:** Rust 1.64.0

**Comment by ChrisDenton** [comment]
Hm, I don't usually use the msi installer but I just downloaded it from you link and it seems to be working for me?

![msi](https://user-images.githubusercontent.com/4459874/197438870-6e1384e4-767c-41ad-8124-3a9a27dfa714.png)

And `rustc --version --verbose` appears to report the correct version:

```
> (gcm rustc).Source
C:\Program Files\Rust stable MSVC 1.64\bin\rustc.exe
> rustc --version --verbose
rustc 1.64.0 (a55dd71d5 2022-09-19)
binary: rustc
commit-hash: a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52
commit-date: 2022-09-19
host: x86_64-pc-windows-msvc
release: 1.64.0
LLVM version: 14.0.6
```

Could it be that the old install isn't being updated for some reason? Or maybe just the `PATH` variable?

**Comment by mdnava** [comment]
This one was updated just yesterday using the MSVC .msi package to try it out:

![2022-10-25 01 43 06](https://user-images.githubusercontent.com/24944618/197692152-6efa0599-bee1-4b81-900f-eb3cfdc08a82.png)

**Comment by ChrisDenton** [comment]
I suspect that will encounter the same problem once you upgrade. I think the issue is that the newer installer is adding the 1.64 directory to the `PATH` environment variable but *after* the older directory. So when you run rustc the 1.60 version is always used instead of the new version. A workaround would be to manually edit the `PATH` environment variable or to uninstall old versions.

But, if I'm right, this really does sound like a bug with the installer.

**Comment by mdnava** [comment]
This is the Rust location in my PATH variable:
`%RUST_HOME%\toolchains\stable-x86_64-pc-windows-msvc\`

![2022-10-25 03 14 06](https://user-images.githubusercontent.com/24944618/197707711-d1dcdfb0-ebf4-4019-8dc8-084dba1aa193.png)

That rustc.exe returns version 1.60 even tho I updated to 1.64 version. And by "updated" I mean I removed the previous directory and installed Rust from the latest MSVC .msi package.

Note that this issue happens also with the i686 toolchain (but that one is not in PATH):
`%RUST_HOME%\toolchains\stable-i686-pc-windows-msvc\`

![2022-10-25 03 13 07](https://user-images.githubusercontent.com/24944618/197707741-b572011e-a5bf-4afa-ba60-4ae531534b85.png)

However, the GNU (also not currently on PATH) returns correctly the 1.64 version.
`%RUST_HOME%\toolchains\stable-x86_64-pc-windows-gnu\`

![2022-10-25 03 22 38](https://user-images.githubusercontent.com/24944618/197709380-a017102c-d485-4de8-9618-c7f3981ef6e8.png)

Some info about the .msi packages:

![2022-10-25 03 51 32](https://user-images.githubusercontent.com/24944618/197715451-80797f4b-4338-455f-a06f-41063ba22e43.png)

Now, I just downloaded manually (again) the MSVC .msi package (v1.64) and extracted it with this command:

`msiexec /a "rust-1.64.0-x86_64-pc-windows-msvc.msi" TARGETDIR="rust-1.64.0-x86_64-pc-windows-msvc" /qb`

And I got the right version:

![2022-10-25 04 01 52](https://user-images.githubusercontent.com/24944618/197717816-bbddb316-57e5-4878-870c-39a23a6027bf.png)

That's the same msiexec command I use to automatically update Rust with Pwsh (using Invoke-WebRequest and MSIExec).

I don't mean to make things difficult. I appreciate the availability of the MSI installers, please don't remove them (unless .zip archives are an option). I acknowledge I might be making a mistake somewhere. Or perhaps the server is returning a proxied/cached installer in some cases (Invoke-WebRequest?). But then I wonder why I have no issue with the GNU package.

Have a nice day!

**Comment by mdnava** [comment]
Ok, I just did a test and I'm 90% convinced the error is on my side.
I'm sorry to have taken some of your time. Thank you!

It's still a weird error. But not likely caused by the downloaded package.

What did I test?.. simple:

1) I used my script to again start an update to latest Rust (MSVC x64 v1.64).
2) While the update was ongoing and copied the downloaded .msi from the TEMP dir to the Desktop.
3) I tested the updated Rust toolchain (MSVC x64 v1.64) and it showed the wrong version (1.60).
4) I extracted the same .msi file used by my script to update and tested it.. The extracted files now showed the right version (1.64), and this was from the same .msi package that previously gave me the wrong 1.60 version.

I'm still a little confused though.

Have a nice day!

**Comment by mdnava** [comment]
Ok.. that 90% just became a 100% certainty it was an error on my side. The reason why it happened to the MSVC toolchain and not the GNU was only becase in the first case I was updating (an existing version) and in the second case installing (for the first time). After any future release of Rust the GNU toolchain would've behave the same way and show the wrong version of Rust.

Best regards!
