### ISSUE TITLE
Strange extra type error after missing semicolon error

### ISSUE THREAD

**Issue by jruderman** [rust-lang/rust#103425]
Given the following code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=55059b7460a49a908e086ce00bf462e2)):

```rust
fn f() -> f32 {
    3
    5.0
}

fn main() {
}
```

The current output is:

```
error: expected `;`, found `5.0`
 --> epp.rs:2:6
  |
2 |     3
  |      ^ help: add `;` here
3 |     5.0
  |     --- unexpected token

error[E0308]: mismatched types
 --> epp.rs:2:5
  |
2 |     3
  |     ^ expected `()`, found integer
```

What is this second error trying to tell me? _What_ did it expect to be unit type and why? Does it make sense for this error to be emitted despite the first error correctly identifying my problem?

**Comment by compiler-errors** [comment]
> What is this second error trying to tell me?

It's trying to tell you nothing in particular. This is a bug, due to the fact that we *eat* the `5.0` token and replace it with `;`, so the "fixed" body ends up being:

```
fn f() -> f32 {
  3
  ;
}
```

**Comment by jruderman** [comment]
That theory doesn't seem right to me, for two reasons:

* I would expect eating the `5.0` to result in a type error like "expected `f32` because of return type", but the actual error involves integer and unit.
* Repeating the missing-semi error results in repeating the type error as well, even though it's all within one function. [For example](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=de50d5b7a5ca47a6fd6025cdae2a7000):

```rust
fn f() -> f32 {
    2_u32
    3_i8
    5.0
}

fn main() {
}
```

gives two missing-semi errors and two type errors:

```
error: expected `;`, found `3_i8`
 --> src/lib.rs:2:10
  |
2 |     2_u32
  |          ^ help: add `;` here
3 |     3_i8
  |     ---- unexpected token

error: expected `;`, found `5.0`
 --> src/lib.rs:3:9
  |
3 |     3_i8
  |         ^ help: add `;` here
4 |     5.0
  |     --- unexpected token

error[E0308]: mismatched types
 --> src/lib.rs:2:5
  |
2 |     2_u32
  |     ^^^^^ expected `()`, found `u32`

error[E0308]: mismatched types
 --> src/lib.rs:3:5
  |
3 |     3_i8
  |     ^^^^ expected `()`, found `i8`
```

**Comment by compiler-errors** [comment]
@chenyukang please first understand what the AST doing on the semicolon recovery path, then once that's done, you can probably try to make it recover like: `3; 5.0` properly so it type-checks correctly.
