### ISSUE TITLE
Compiler hang with incomplete struct literal at end of file

### ISSUE THREAD

**Issue by jruderman** [rust-lang/rust#103451]
This malformed code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=92c9932ec918d7af092fa140815f3e0a)) hangs the compiler:

```rust
struct R { }

struct S {
    x: [u8; R
```

Found by fuzzing with a [modified fuzz-rustc](https://github.com/jruderman/fuzz-rustc).

### The bug's edges
* `R` must be defined as a named-field struct (not a tuple struct or unit struct), although it can have 0 fields.
* `R` must be the last token to produce the hang:
  * No opening brace (note that braces are required for literals of named-field structs)
  * No closing delimiters
  * Not even a comment

### Where it hangs
If I understand [mj.sample.txt](https://github.com/rust-lang/rust/files/9847560/mj.sample.txt) correctly, the hang occurs in LateResolutionVisitor, with `try_lookup_name_relaxed` never finishing (while calling various functions such as  `smart_resolve_context_dependent_help` and `span_to_snippet`)

### Additional example

This also hangs. I'm guessing it's the same bug.

```rust
struct R { }

fn f() {
    R
```

### Version

`rustc --version --verbose`:
```
rustc 1.66.0-nightly (6e95b6da8 2022-10-22)
binary: rustc
commit-hash: 6e95b6da885f42a4e1314595089fa4295e329d11
commit-date: 2022-10-22
host: x86_64-apple-darwin
release: 1.66.0-nightly
LLVM version: 15.0.2
```

### Regression

[Bisected](https://github.com/rust-lang/cargo-bisect-rustc) with: 
```bash
cargo-bisect-rustc --start=2022-10-03 --end=nightly-2022-10-23 --preserve --script=./timeout.sh
```

<details>
<summary>timeout.sh</summary>
<p>

```bash
#!/bin/bash

# This script is wrong in several ways:
# - It will try to kill processes that might no longer exist
# - It may leave an orphan rustc process after the bisect (because it only kills the shell, not rustc)
# But it seems to be good enough for bisection to work

killall rustc
outershell=$$
(sleep 5; kill $outershell) &
rustc src/main.rs
true
```

</p>
</details>

* regressed nightly: nightly-2022-10-21
* regressed commit: https://github.com/rust-lang/rust/commit/53728ff751df4c271d4ea565b6871057a3504fc5 (PR #103185)

@rustbot label +regression-from-stable-to-nightly +I-hang

**Comment by chenyukang** [comment]
I can not reproduce it with latest code, did I missed anything?

```console
cat@LAPTOP-V6U0QKD4:~/code/rust$ cat hang.rs
struct R { }

struct S {
    x: [u8; R
cat@LAPTOP-V6U0QKD4:~/code/rust$ rustc -vV
rustc 1.66.0-nightly (7fcf850d7 2022-10-23)
binary: rustc
commit-hash: 7fcf850d7942804990a1d2e3fe036622a0fe4c74
commit-date: 2022-10-23
host: x86_64-unknown-linux-gnu
release: 1.66.0-nightly
LLVM version: 15.0.2
cat@LAPTOP-V6U0QKD4:~/code/rust$ rustc hang.rs
error: this file contains an unclosed delimiter
 --> hang.rs:4:15
  |
3 | struct S {
  |          - unclosed delimiter
4 |     x: [u8; R
  |        -      ^
  |        |
  |        unclosed delimiter

error[E0423]: expected value, found struct `R`
 --> hang.rs:4:13
  |
1 | struct R { }
  | ------------ `R` defined here
...
4 |     x: [u8; R
  |             ^ help: use struct literal syntax instead: `R {}`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0423`.
```

**Comment by chenyukang** [comment]
Confirmed the error is only triggered by commit: `6e95b6da885f42a4e1314595089fa4295e329d11`

The root cause is I changed the edge corner case in `find_width_of_character_at_span`:

```rust
        // Ensure indexes are also not malformed.
        if start_index > end_index || end_index > source_len - 1 {
            debug!("find_width_of_character_at_span: source indexes are malformed");
            return 0;  // Previous version is  `return 1`
        }
```

We think `next_point` should won't return a span which outside of source file, so `0` is a valid one, the next_point will always return a valid span, and we get OK("") from `sm.span_to_snippet` when reaching the end of source.

So, there is a loop in previous `followed_by_brace`, which will run infinitely loop:

https://github.com/rust-lang/rust/blob/41a1cfdbaf0ec1024cee7a90309fcf3eecee83d1/compiler/rustc_resolve/src/late/diagnostics.rs#L1110

Lucky, my another PR refactored this function:
https://github.com/rust-lang/rust/commit/518d5ebc81f027d57ed61dc6443fdef528843815#diff-2c81e6d8048a31a3ce43f30181aaa037e0ad0076e7aee67792ca993f28c75ac3L1108-L1110

**Comment by jruderman** [comment]
Verif, I no longer get a hang after rollup 9be2f35a4c1ed1b04aa4a6945b64763f599259ff

Do you want to add one or two of these as tests?

**Comment by chenyukang** [comment]
This testcase seems not easy to be added:

```rust
struct R { }

struct S {
    x: [u8; R //~ ERROR this file contains an unclosed delimiter
    //~| ERROR expected value
```

If so, the trigger point will do not exist, 😂

**Comment by estebank** [comment]
> If so, the trigger point will do not exist

There's an alternative kind of annotation for patterns that should work for this case: `// error-pattern:this file contains an unclosed delimiter`
