### ISSUE TITLE
Inconsistent compile times with multidimensional arrays

### ISSUE THREAD

**Issue by infalmo** [rust-lang/rust#103477]
**UPD**: See [comment](https://github.com/rust-lang/rust/issues/103477#issuecomment-1290762143)

Compiling (rust nightly, release mode) [this](https://play.rust-lang.org/?version=nightly&mode=release&edition=2021&gist=920fc9462cdcbae9bb4712899768c8ca) takes 4x as much time as [this](https://play.rust-lang.org/?version=nightly&mode=release&edition=2021&gist=45d0059810c2d79fa71a9268ee059dd5). The only difference between the two snippets is the size of the array (20 vs 100), which is surprising, since one would expect the compilation of the bigger array to take more time.

**Comment by Mark-Simulacrum** [comment]
Seems to be equally fast either way with my local rustc.
