### ISSUE TITLE
`let (_ = 3;` causes suggestion to remove a paren that is only hypothetical

### ISSUE THREAD

**Issue by jruderman** [rust-lang/rust#103497]
Given the following code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=9a8c2017802ea327d90f59f75fe59c98)):

```rust
fn main() {
    let (_ = 3;
}
```

The current output is:

```
error: expected one of `)`, `,`, or `|`, found `=`
 --> es4.rs:2:9
  |
2 |     let (_ = 3;
  |         ^ -^
  |         | |
  |         | help: `)` may belong here
  |         unclosed delimiter

error: expected expression, found `)`
 --> es4.rs:3:1
  |
3 | }
  | ^ expected expression

warning: unnecessary parentheses around pattern
 --> es4.rs:2:9
  |
2 |     let (_ = 3;
  |         ^ ^
  |
  = note: `#[warn(unused_parens)]` on by default
help: remove these parentheses
  |
2 -     let (_ = 3;
2 +     let _ = 3;
  |
```

The final warning, "unnecessary parentheses around pattern", is sus:

* The compiler shouldn't be so sure that the parens are "unnecessary" when the compiler had to guess where the end-paren was
* In the suggestion, the second span is empty (the location at which a hypothetical end-paren might be missing) and its suggested replacement is also empty (the lack of a paren).
  * This is verifiable with `--error-format=json`.
  * The second yellow caret-arrow, appearing to point to the space after the underscore, is a visual sign that something is not quite right.
  * In rustc builds with debug_assert enables, this trips a recently-added assertion.

```
thread 'rustc' panicked at 'Span must not be empty and have no suggestion', compiler/rustc_errors/src/diagnostic.rs:570:9
```

Found by fuzzing with a [modified fuzz-rustc](https://github.com/jruderman/fuzz-rustc), combined with this very reasonable new assertion in rustc (added by @kper in #102922).

**Comment by On0n0k1** [comment]
In the second suggestion. You mentioned that the suggested location for ')' was after the underscore '_'.

Maybe, instead, this is because the location is behind the '=' operator. If the operator was '==', the checker could have kept searching. But a parentheses can't exist surrounding a '=' operation. So the guess was correct.

**Comment by jruderman** [comment]
Obsoleted by #108297. The compiler now exits early if there are unclosed delimiters.
