### ISSUE TITLE
'dlopen(null pointer)' does not work on the android

### ISSUE THREAD

**Issue by jaeminMoon** [rust-lang/rust#10356]
see rust/src/auxiliary/linkage-visibility.rs

``` rust
#[no_mangle]
pub fn foo() { bar(); }

pub fn foo2<T>() {
    fn bar2() {
        bar();
    }
    bar2();
}

#[no_mangle]
fn bar() { }

#[no_mangle]
fn baz() { }

pub fn test() {
    let lib = DynamicLibrary::open(None).unwrap();
    unsafe {
        assert!(lib.symbol::<int>("foo").is_ok());
        assert!(lib.symbol::<int>("baz").is_err());
        assert!(lib.symbol::<int>("bar").is_err());
    }
}
```

This test code is success on linux, but fail on android.

```
 failed at 'assertion failed: lib.symbol::<int>("foo").is_ok()'
```

I think `dlopen(null pointer, RTLD_LAZY)` have to return 'main program Handle', but do not run on android.

**Comment by tamird** [comment]
This is confirmed still broken on Android :(

**Comment by steveklabnik** [comment]
Triage: said test is here: https://github.com/rust-lang/rust/blob/f50dbd580f3d5d88a300da540db3c85164bfd0de/src/test/run-pass-fulldeps/auxiliary/linkage-visibility.rs

I don't see anything disabled on android by what @flaper87 suggested.

@tamird suggests this is broken on the bots, but I don't know enough about them to make the same evaluation.

**Comment by sfackler** [comment]
That's the auxiliary file - the test itself is disabled: https://github.com/rust-lang/rust/blob/f50dbd580f3d5d88a300da540db3c85164bfd0de/src/test/run-pass-fulldeps/linkage-visibility.rs#L12

**Comment by steveklabnik** [comment]
Triage: no change
