### ISSUE TITLE
Use include_bytes with optional way

### ISSUE THREAD

**Issue by cavivie** [rust-lang/rust#103566]
I'm using `include_bytes` to do compile time embedding bytes data from a file, it works fine when the file exists, but when the file doesn't exist it will prompt a compiler error instead of a warning. In my scenario, the file does not necessarily exist, but if it exists, the content of the file needs to be compiled with the program. If it does not exist, there will be additional logic processing instead of default values. So I'm going to look for a macro like `include_bytes` in rust that returns an enumeration of `Option<&'static [u8]>`, at which point I can tell if the file content exists. Not sure if the rust compiler supports this way of working now, or is there any way to do it?

Here is my code sample:
```rust
static PRIVACY_SOP_BIN: Option<&'static [u8]> = include_bytes!("./data/privacy.sop");

fn handle() {
    ...
    if let Some(bin) = PRIVACY_SOP_BIN {
        // do something for bin
    }
    ...
}
```

**Comment by jyn514** [comment]
No, this doesn't exist today.

The issue tracker is not a support forum. For future questions please ask in one of these places:

https://discord.gg/rust-lang/
https://discord.gg/rust-lang-community/
https://users.rust-lang.org/
https://rust-lang.zulipchat.com/

**Comment by cavivie** [comment]
Thanks, currently discussed at this link: https://discord.com/channels/273534239310479360/818964227783262209/1036496563272417380
