### ISSUE TITLE
Replace libstd, libcore, liballoc terminology in docs

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#103551]
There are a few places in the standard library docs that still refer to libstd, libcore, and liballoc; the modern naming for these would be `std`, `core`, and `alloc`. We should update the docs.

```
$ rg 'libcore|libstd|liballoc' build/x86_64-unknown-linux-gnu/doc/ -l | grep -v '\.rs\.html'
build/x86_64-unknown-linux-gnu/doc/std/backtrace/index.html
build/x86_64-unknown-linux-gnu/doc/std/fmt/trait.Debug.html
build/x86_64-unknown-linux-gnu/doc/std/slice/trait.Concat.html
build/x86_64-unknown-linux-gnu/doc/alloc/index.html
build/x86_64-unknown-linux-gnu/doc/alloc/fmt/trait.Debug.html
build/x86_64-unknown-linux-gnu/doc/alloc/slice/trait.Concat.html
build/x86_64-unknown-linux-gnu/doc/core/sidebar-items1.66.0.js
build/x86_64-unknown-linux-gnu/doc/core/panicking/sidebar-items1.66.0.js
build/x86_64-unknown-linux-gnu/doc/core/panicking/fn.panic.html
build/x86_64-unknown-linux-gnu/doc/search-index1.66.0.js
build/x86_64-unknown-linux-gnu/doc/core/panicking/index.html
build/x86_64-unknown-linux-gnu/doc/core/fmt/trait.Debug.html
build/x86_64-unknown-linux-gnu/doc/core/prelude/index.html
build/x86_64-unknown-linux-gnu/doc/core/index.html
```

**Comment by Mark-Simulacrum** [comment]
FWIW, I sometimes find it a lot clearer -- particularly for core -- to say "libcore". That's unambiguously a library, whereas "core" can mean a lot of things otherwise. I think in many cases this doesn't matter, but we should be careful when reviewing the resulting PR from this issue to make sure context is there, not just directly accept a search and replace.

**Comment by Rageking8** [comment]
@rustbot claim
I will try to replace those that are unambiguous.

**Comment by Rageking8** [comment]
@rustbot release-assignment
Will leave for another person
