### ISSUE TITLE
Dead link in source code browser

### ISSUE THREAD

**Issue by hellow554** [rust-lang/rust#103517]
### Location
Using [this](https://doc.rust-lang.org/nightly/src/std/sys/unix/process/process_unix.rs.html) page and then clicking on the left onto `unix/cmath.rs` will give you a 404: https://doc.rust-lang.org/nightly/src/std/sys/unix/unix/cmath.rs.html

![grafik](https://user-images.githubusercontent.com/921462/197756081-b5a9a957-ceb9-48f9-9ddd-678d78b2e5c0.png)

### Summary
Either that file should not show up in the source code list at all or it should properly redirect to the source code.

**Comment by jsha** [comment]
Possibly related: #98220

**Comment by clubby789** [comment]
The `cmath` module is declared as
```rs
#[path = "../unix/cmath.rs"] 
pub mod cmath;
```
and the actual location is https://doc.rust-lang.org/nightly/src/std/sys/unix/up/unix/cmath.rs.html.
