### ISSUE TITLE
Recover from common `if let` syntax mistakes/typos

### ISSUE THREAD

**Issue by Rageking8** [rust-lang/rust#103587]
Given the following code: [link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=56d8d05130b8a46c94a014811061b0a4)

```rust
fn main() {
    let x = Some(123);

    // #1
    if let Some(_) == x {}

    // #2
    if let x = Some(_) {}

    // #3
    if let x == Some(_) {}

    // #4
    if Some(_) = x {}
}
```

The current output is:

```
   Compiling playground v0.0.1 (/playground)
error: expected one of `=` or `|`, found `==`
 --> src/main.rs:5:20
  |
5 |     if let Some(_) == x {}
  |                    ^^ expected one of `=` or `|`

error: could not compile `playground` due to previous error
```

Ideally the output should suggest how to fix the syntax mistakes/typos for each of the above examples.
1 -> Remove extra `=`
2 -> Swap `x` and `Some(_)`
3 -> 1 and 2
4 -> Add `let`

**Comment by chenyukang** [comment]
Submit #103636 to resolve scenario `1` and `4`, because I think we are sure about the intention of developer, and there is a clear way to fix it.

For 2 and 3, there are potential way to fix.
