### ISSUE TITLE
ASCII escape codes don't render with `include_str!`

### ISSUE THREAD

**Issue by jsvcycling** [rust-lang/rust#103501]
ASCII escape codes aren't rendered correctly when using `include_str!()`.

I've tested this on both stable and nightly channels and they produce identical output. I've also tested a couple terminal emulators (Alacritty and xfce4-terminal) and again they produce identical outputs.

Code:

```rust
fn main() {
    print!(include_str!("input.txt"));
    print!("{}", include_str!("input.txt"));
    print!("\x1b[1mTEST\x1b[0m\n");
}
```

Contents of `input.txt`:

```
\x1b[1mTEST\x1b[0m

```

Output:
```
\x1b[1mTEST\x1b[0m
\x1b[1mTEST\x1b[0m
TEST
```

(The lone *TEST* correctly appears in bold).

### Meta

Stable:
```
rustc 1.64.0 (a55dd71d5 2022-09-19)
binary: rustc
commit-hash: a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52
commit-date: 2022-09-19
host: x86_64-unknown-linux-gnu
release: 1.64.0
LLVM version: 14.0.6
```

Nightly:
```
rustc 1.66.0-nightly (7fcf850d7 2022-10-23)
binary: rustc
commit-hash: 7fcf850d7942804990a1d2e3fe036622a0fe4c74
commit-date: 2022-10-23
host: x86_64-unknown-linux-gnu
release: 1.66.0-nightly
LLVM version: 15.0.2
```

**Comment by ehuss** [comment]
`include_str!` does not interpret backslash escapes. It includes the contents as-is. If you want to include escape sequences, you'll need to place the actual ASCII ESC byte in the file (instead of `\x1b`) or replace it (`.replace("\\x1b", "\x1b")`), or use one of the unescaping libraries that can be found on crates.io.

**Comment by workingjubilee** [comment]
`include_str!` is effectively like a `r#""#` literal, yeah. Working as intended.
