### ISSUE TITLE
Need to add a test for marker traits with `'static`

### ISSUE THREAD

**Issue by jackh726** [rust-lang/rust#103574]
Not sure if we have a test for the following

```rust
#![feature(marker_trait_attr)]
#[marker] trait Marker {}
impl Marker for &'static () {}
impl Marker for &'static () {}
```

and 

```rust
```rust
#![feature(marker_trait_attr)]
#[marker] trait Marker {}
impl Marker for &'_ () {}
impl Marker for &'_ () {}
```

If not, we need to add them, since they would be important for special casing `'static` during canonicalization.

**Comment by Rageking8** [comment]
I can help add this test if needed. (Did not rustbot claim so as to not remove lcnr from assignee)

**Comment by jackh726** [comment]
Sure :) would help out @lcnr if nothing else

**Comment by Rageking8** [comment]
@rustbot label +F-marker_trait_attr

In case this needs to be indexed in the future.
