### ISSUE TITLE
`#![allow(unknown_lints)]` should permit unstable lints

### ISSUE THREAD

**Issue by lopopolo** [rust-lang/rust#103698]
I maintain a crate called `iana-time-zone` which has an MSRV of 1.38 and an explicit goal of supporting all versions from that MSRV up to stable on all tier 1 platforms (and especially Debian stable).

I previously added two crate level attributes:

```rust
#![allow(unknown_lints)]
#![warn(unsafe_op_in_unsafe_fn)]
```

This set of attributes compiles on Rust 1.38.0 where the unsafe op in unsafe fn lint does not exist, but fails to compile on 1.48.0 where the lint is unstable.

I believe I can work around this by moving the warn config to `RUSTFLAGS` in CI, but then contributors lose out on the lint in their inner development loop.

I think I'd like allow unknown lints to suppress enabling unstable lints and treat them as if they are unknown (maybe only on non-nightly toolchains?).

(Apologies for the blank issue and not searching the tracker, I'm on mobile.)

**Comment by lopopolo** [comment]
@rustbot label T-compiler C-bug

(I think these are the right labels)

**Comment by lopopolo** [comment]
r? @compiler-errors

(Sorry for the direct at mention but I think I messed up by making a blank issue)

**Comment by compiler-errors** [comment]
Howdy -- `r?` is meant for PR review requests, not for issues.

Did you mean to tag me for something -- I don't recall having any context here?

**Comment by lopopolo** [comment]
Oh sorry, I just wanted to make sure someone got pinged since I use a blank issue.

**Comment by lopopolo** [comment]
Sorry for the mistakes in filing this ticket folks, I've given it another go here:

- https://github.com/rust-lang/rust/issues/103713

**Comment by fmease** [comment]
> Sorry for the mistakes in filing this ticket folks

You did absolutely nothing wrong and didn't actually need to file a new issue. Blank issues and templated ones only differ in labels and some prewritten text. Issue templates exist to speed up some workflows and to guide newcomers to write proper issues.

You can always recreate any templated issue from an already opened blank issue by updating the description or by adding a new comment containing commands like `@rustbot label +LABEL0 +LABEL1 -LABEL1` to add/remove labels.

Somebody would've seen this issue at some point in time, so no need to worry about it so much.
