### ISSUE TITLE
All consuming iterator functions 'any' and 'some' compiler bug.

### ISSUE THREAD

**Issue by rubend056** [rust-lang/rust#103669]
I tried this code:

```rust
use std::collections::{HashSet};
#[test]
fn foo() {
    let mut set = HashSet::new();
    set.insert(Some(4));
    let mut set = set.iter().map(|v|Some(55));
    set.any(|v| false);
    let set = set.map(|v|v.unwrap());
    
    let mut i=0;
    set.for_each(|v|{i+=1;});
    assert_eq!(i, 1);
}
```

I expected to see this happen: *The test to not fail*

Instead, this happened: *Test failed with left: 0, right: 1*, 

### Meta

*Test fails on rust playground with nightly/stable channel*

`rustc --version --verbose`:
```
rustc 1.66.0-nightly (a6b7274a4 2022-10-10)
binary: rustc
commit-hash: a6b7274a462829f8ef08a1ddcdcec7ac80dbf3e1
commit-date: 2022-10-10
host: x86_64-unknown-linux-gnu
release: 1.66.0-nightly
LLVM version: 15.0.2
```

<details><summary>Backtrace</summary>
<p>

```
   0: rust_begin_unwind
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/core/src/panicking.rs:65:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/core/src/panicking.rs:203:5
   4: playground::foo
             at ./src/lib.rs:12:5
   5: playground::foo::{{closure}}
             at ./src/lib.rs:3:1
   6: core::ops::function::FnOnce::call_once
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/core/src/ops/function.rs:251:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/0da281b6068a7d889ae89a9bd8991284cc9b7535/library/core/src/ops/function.rs:251:5
```

</p>
</details>

**Comment by rubend056** [comment]
Apparently the bug is caused because any borrows mutable iterable and starts iterations thorugh values. So when for_each is reached, there are no values left to go over.

A better documentation over those methods would be great. Let me know if I can submit a pull request on them then.

**Comment by the8472** [comment]
The issue here is naming

>     `let mut set = set.iter().map(|v|Some(55));`

You're no longer looking at the set but at an iterator over the set, and then you keep using that iterator.

**Comment by rubend056** [comment]
Right, but that still doesn't explain why commenting out line 7 `set.any(|v| false);` makes the test pass.

I understand **now** that when iterator has been traversed, that's it, that's why anything after line 7 set.any that uses that iterator won't really do anything. I assume it's a forwards only iterator. But it's not really highlighted in the docs, perhaps I just haven't seen it.

Thanks for the insight. I'll close the issue
