### ISSUE TITLE
rust 1.64 now uses fd-lock->rustix->flock() for bootstraping where flock() is not available on Solaris

### ISSUE THREAD

**Issue by psumbera** [rust-lang/rust#103630]
Seems that Rust now relies on fd-lock for bootstraping instead of using python code:

https://github.com/rust-lang/rust/commit/5a30316fc14ab6952ce9f925478c498c804a7b71

Solaris doesn't support flock(). Insetad more modern fcntl() interface is used.

So even when I was able to make rustix compile on Solaris (without flock() support) it doesn't help since fd-lock requires flock().

Therefore I'm not able to compile Rust 1.64.0 on Solaris now.

**Comment by jyn514** [comment]
@psumbera adding a `cfg(not(target_os = "solaris"))` to that code seems reasonable, happy to take a PR.

**Comment by jyn514** [comment]
Ah, I see. You can use those cfgs in Cargo.toml too I think. I'm surprised you get that error at compile time, is it trying to use something in libc that doesn't exist?

**Comment by psumbera** [comment]
Oh, I see that @gco has already fixed rustix Solaris build problems via https://github.com/bytecodealliance/rustix/commit/d96706a9b3d7126161af595c9c3fa40afbd1dce3 .

**Comment by jyn514** [comment]
@psumbera does that mean we just have to update `rustix` to fix this error? Happy to take a PR for that :)

**Comment by psumbera** [comment]
It's not just about updating rustix. It would still miss support for flock(). But we could try to emulate it via fcntl() then...

**Comment by jyn514** [comment]
Sure, seems reasonable :) I think you would need to modify `fd-lock` for that directly, though.

**Comment by jyn514** [comment]
You can also just disable locking for that target, we use it to prevent running in parallel by accident, but you can just be careful to only run one process of bootstrap at a time.

**Comment by zephaniahong** [comment]
@jyn514 Any help still needed here?

**Comment by jyn514** [comment]
@zephaniahong sure, but it will be hard to test your chances unless you have access to a Solaris machine ...

**Comment by zephaniahong** [comment]
I see! In that case, I'll leave it for someone else😅

**Comment by psumbera** [comment]
@jyn514 can you please have look at PR #https://github.com/rust-lang/rust/pull/108607?

**Comment by albertlarsan68** [comment]
It is on my to-do list, the only thing I see left to do is create an issue to track which platforms have locking and which haven't.
