### ISSUE TITLE
Prologue of function missing in FatLTO but present in ThinLTO

### ISSUE THREAD

**Issue by MasterAwesome** [rust-lang/rust#103619]
Compiling with branch-target-enforcement = 1(`-Zbranch-protection=bti`) on `aarch64-unknown-linux-gnu` causes different code to emitted in the prologue of the function for fat LTO and thin LTO in **debug** mode.

Baseline assembly for function add defined as follows:
```rust
#[no_mangle]
pub extern "C" fn add(left: usize, right: usize) -> usize {
    left.wrapping_add(right)
}
```

compiled into a `cdylib`.

## [DEBUG] llvm-objdump on ThinLTO
```asm
0000000000010408 <add>:
   10408: d503245f     	bti	c ; not present in FatLTO
   1040c: d10043ff     	sub	sp, sp, #16
   10410: 8b010008     	add	x8, x0, x1
   10414: f90007e8     	str	x8, [sp, #8]
   10418: 14000001     	b	0x1041c <add+0x14>
   1041c: f94007e0     	ldr	x0, [sp, #8]
   10420: 910043ff     	add	sp, sp, #16
   10424: d65f03c0     	ret
```

### [DEBUG] llvm-objdump on FatLTO
```asm
0000000000010408 <add>:
   10408: d10043ff     	sub	sp, sp, #16
   1040c: 8b010008     	add	x8, x0, x1
   10410: f90007e8     	str	x8, [sp, #8]
   10414: 14000001     	b	0x10418 <add+0x10>
   10418: f94007e0     	ldr	x0, [sp, #8]
   1041c: 910043ff     	add	sp, sp, #16
   10420: d65f03c0     	ret
```

### [RELEASE] llvm-objdump on both FatLTO and ThinLTO
```asm
0000000000010238 <add>:
   10238: d503245f     	bti	c
   1023c: 8b000020     	add	x0, x1, x0
   10240: d65f03c0     	ret
```

# rustc version with failure first occuring:
```
rustc 1.65.0-nightly (75b7e52e9 2022-08-13)
binary: rustc
commit-hash: 75b7e52e92c3b00fc891b47f5b2efdff0a2be55a
commit-date: 2022-08-13
host: x86_64-unknown-linux-gnu
release: 1.65.0-nightly
LLVM version: 15.0.0
```
# cargo-bisect-rustc
searched nightlies: from nightly-2022-08-12 to nightly-2022-08-14

regressed nightly: nightly-2022-08-13

searched commit range: https://github.com/rust-lang/rust/compare/20ffea6938b5839c390252e07940b99e3b6a889a...f22819bcce4abaff7d1246a56eec493418f9f4ee

regressed commit: https://github.com/rust-lang/rust/commit/e2b52ff73edc8b0b7c74bc28760d618187731fe8

 

<details>

<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.4</summary>

 

 

Host triple: x86_64-unknown-linux-gnu

Reproduce with:

```bash

cargo bisect-rustc --start=2022-08-12 --end=2022-08-14 --script=test.sh --target aarch64-unknown-linux-gnu

```

</details>

## Might be related to: https://github.com/rust-lang/rust/issues/102162 as reverting the same [patches](https://github.com/rust-lang/rust/issues/102162#issuecomment-1279642757) in that issue solves the problem.

**Comment by inquisitivecrystal** [comment]
@MasterAwesome Pardon, but what's the practical implication of this regression? Does it cause some sort of runtime problem, is it a code-size or performance problem, or something else? I'm afraid I can't read assembly.

**Comment by saethlin** [comment]
The `bti` instruction isn't present in the fat LTO case, even though it's explicitly requested via compiler flag. I can't really read this either, just diffing by eye and reading the comment.

The fact that the `bti` is present in release but not debug is extremely spooky. Would be good to have the opinion of an LLVM expert.

**Comment by MasterAwesome** [comment]
> @MasterAwesome Pardon, but what's the practical implication of this regression? Does it cause some sort of runtime problem, is it a code-size or performance problem, or something else? I'm afraid I can't read assembly.

The `BTI C` is required when supporting ARM64 has BTI enabled and rust function is being called from another language that's expecting the `bti c`. This could lead to a synchronous abort. Especially since rust is being used in quite low layers and init-ed from a C world. On ARM platforms this is a huge bug since when a bug occurs on release mode it makes it really hard to debug it since the debug builds are broken. 

In fact we don't know where in LLVM this is breaking yet which means even on release we could theoretically have this issue.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23103619.20Prologue.20of.20function.20missing.20in.20FatLTO.20but.20present.20.E2.80.A6)).

@rustbot label -I-prioritize +P-high

**Comment by nikic** [comment]
Not particular familiar with BTI, but if this works anything like CET I'd expect it to be an "all or nothing" thing. Your full LTO build likely contains a module that does not use BTI, so it's not possible to use CFI for anything.

Does this actually work with thin LTO and not just get automatically disabled at a higher layer due to a missing GNU property note on the object that causes this to be disabled in the full LTO case?

**Comment by nikic** [comment]
The difference between debug and release here is likely just that debug ends up using code from libstd (which presumably does not have BTI enabled, unless you're using `build-std`), while it is inlined in the release case.

So at least on the surface, I think everything works as expected here.

**Comment by MasterAwesome** [comment]
Right, but this is broken even with build-std as mentioned in the other thread as of nightly 2022-08-14.

**Comment by MasterAwesome** [comment]
Looks like on debug mode, `rustc_std_workspace_core` has branch-target-enforcement set to `0` but on release mode it's set to `1` (probably because the compiler optimized that module out).

Using `-Zbuild-std=core` sets that to `1` on debug mode and the codegen is correct.

I still think the Min of all branch-target-enforcement is a wrong approach since the application requesting it requires it which should propagate across dependent modules and rebuild if needed. With `nightly-2022-08-12` this behaviour was observed and regressed due to the patches mentioned in OP.
