### ISSUE TITLE
Recover from accidental inclusion of `if` in `let else`

### ISSUE THREAD

**Issue by Rageking8** [rust-lang/rust#103791]
Given the following code: [link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=a756c5823b0deb404c94b7e0d4aa3b5b)

```rust
fn main() {
    let x = Some(123);
    if let Some(y) = x else {
        return;
    };
}
```

The current output is:

```
   Compiling playground v0.0.1 (/playground)
error: this `if` expression is missing a block after the condition
 --> src/main.rs:3:5
  |
3 |     if let Some(y) = x else {
  |     ^^
  |
help: add a block here
 --> src/main.rs:3:23
  |
3 |     if let Some(y) = x else {
  |                       ^

error: could not compile `playground` due to previous error
```

Ideally the output should suggest removing the additional `if` keyword in front of the `let else`. This mistake can occur due to muscle memory as `if`, `if let`, `let else` and in the future `let chains` are somewhat similar syntactically. Thanks.

@rustbot label +D-confusing +F-let-else

**Comment by faptc** [comment]
I think the current suggestion is valid. 
Because one writes `let y = Some(0); if let Some(x) = y else {}` instead of
writing `if let x = y else {}`.

So the suggestion if changed maybe fall-negative.

**Comment by estebank** [comment]
We should likely *add* an alternative suggestion to remove the `if`, but keep both. I think that the current suggestion is likely going to be the more common situation, so it should still come first.

**Comment by hgrahamcs** [comment]
What would be the best way to go about adding an alternate suggestion? I'd like to try my hand at this.

What I think needs to be done is adding help text to `compiler/rustc_error_messages/locales/en-US/parser.ftl`,
add a variant to `compiler/rustc_parse/src/errors.rs IfExpressionMissingThenBlockSub`,
and then add something to `compiler/rustc_parse/src/parser/expr.rs in recover_block_from_condition` to add the alternate after the primary suggestion.

Is this a good starting point?

**Comment by estebank** [comment]
@hgrahamcs it sounds like you are in the right path.

**Comment by HintringerFabian** [comment]
I looked a bit into this issue and have already found where to add text to the `parser.ftl` and the `errors.rs` as @hgrahamcs mentioned, but i am a bit overwhelmed how and where to start in the `recover_block_from_condition` in the `expr.rs`.

Does anyone have a hint for me?

**Comment by estebank** [comment]
> but i am a bit overwhelmed how and where to start in the recover_block_from_condition in the expr.rs.

You can add `info!(?binding)` instructions in the parser to track your progress.

I'm not sure about the specifics out of the top of my head here of what type each step in the parse is, but you will have successfully parsed the `if`, the condition and then you'll encounter an `else` token when a body/block was expected. That's where the new recovery should kick in, pointing at the `if` span saying that you might want to remove it.
