### ISSUE TITLE
Fix unstable::dynamic_lib::test::test_loading_cosine on android

### ISSUE THREAD

**Issue by yichoi** [rust-lang/rust#10379]
# Update Bug

`test_loading_cosine` is being ignored on android. This issue exists to remind that it should be fixed.

This is probably related to:  #10356
# Old Report

To enable test on android bot #9120

and 

test/run-pass/linkage-visibility.rs

It looks to me that this issue is related with #10356

**Comment by steveklabnik** [comment]
Triage: this test is still disabled, and relevant issues still seem to be open. I don't have an android toolchain to test with further.

**Comment by steveklabnik** [comment]
Triage: no changes since my last comment.

**Comment by steveklabnik** [comment]
Triage: no change
