### ISSUE TITLE
x doc --json flag not working

### ISSUE THREAD

**Issue by viandoxdev** [rust-lang/rust#103816]
running 
```
./x doc library/std --json --stage 0
```
only builds the html doc, but
```
RUSTDOCFLAGS="-Zunstable-options --output-format=json" ./x doc library/std --stage 0
```
builds the json doc.

I expected the json flag to act as the documentation says (`./x doc --help`):
```
        --json          render the documentation in JSON format in addition to
                        the usual HTML format
```

### Meta

using the master branch of this repo commit 2afca78a0b03db144c5d8b9f8868feebfe096309

running with a library profile.

**Comment by jyn514** [comment]
I can't reproduce this. The files show up for me in `build/x86_64-unknown-linux-gnu/json-doc`.

**Comment by viandoxdev** [comment]
```dockerfile
FROM rust:1.64

WORKDIR /root/
RUN git clone --depth 1 https://github.com/rust-lang/rust

RUN echo "changelog-seen = 2"       > /root/rust/config.toml
RUN echo "[llvm]"                  >> /root/rust/config.toml
RUN echo "download-ci-llvm = true" >> /root/rust/config.toml

WORKDIR /root/rust

RUN /root/rust/x doc core --json --stage 0

RUN find /root/rust/build -name "core.json" | grep . || echo "not found"

```

Seems to reproduce, I could totally have overlooked a step tho

**Comment by jyn514** [comment]
Ok, I think I see the issue - `JsonDoc` and `HtmlDoc` have the same `PathSet`, and it's non-deterministic which one gets picked; for me hit happens to be JsonDoc, for you it happens to be HtmlDoc. https://github.com/rust-lang/rust/pull/102010/commits/9791b9f9826adea1078775afbaf66545b319b78d should fix it.

**Comment by jyn514** [comment]
oh no it's even simpler than that lol it's calling the wrong `ensure` function https://github.com/rust-lang/rust/blob/4c736a21ae317086871094b1671d6535be593502/src/bootstrap/doc.rs#L532
that should be JsonStd, not Std

**Comment by viandoxdev** [comment]
Should I make the PR or are you gonna do it ?

**Comment by jyn514** [comment]
If you could make a PR that would be great :)

**Comment by viandoxdev** [comment]
Made the PR but since just changing the ensure wasn't enough there's a thing I'm unsure about (tested it, worked, but could be cleaner)
