### ISSUE TITLE
const eval interpreter step limit being hit on nightly for long-running while loop

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#103814]
I tried this code ([playpen](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=85f8150632aa71f6afd230706bbb86c8)):

```rust
const _DUMMY: u8 = {
    let mut data = [0; 131072];
    let mut idx = 0;
    while idx < data.len() {
        data[idx] = idx as u8;
        idx += 1;
    }
    5
};

#[test]
fn check() { }
```

I expected to see this happen: Code compiles, test runs and passes.

Instead, this happened: Code fails to compile, due to:

```
error[[E0080]](https://doc.rust-lang.org/nightly/error-index.html#E0080): evaluation of constant value failed
 --> src/lib.rs:6:9
  |
6 |         idx += 1;
  |         ^^^^^^^^ exceeded interpreter step limit (see `#[const_eval_limit]`)

For more information about this error, try `rustc --explain E0080`.
``` 

It does not occur on stable or beta.

(To be clear: I suspect this might be a const-eval implementation artifact that we cannot readily address. But we may need to figure out how to give better guidance, since the current diagnostic is telling people to muck with an attribute that is not available without opting into a feature gate.)

### Meta

`rustc --version --verbose`:
```
Nightly channel

Build using the Nightly version: 1.67.0-nightly

(2022-10-30 77e57db384aca99444c3)
```

**Comment by pnkfelix** [comment]
See also discussion in https://github.com/rust-lang/rust/issues/93481

(if there are other issues filed for this regression, or if there's a precedent for not filing such issues for this particular regression, then my apologies. I searched and couldn't find evidence to not file it.)

**Comment by tedinski** [comment]
This apparently affects `nightly-2022-10-25` but not `nightly-2022-10-24`

**Comment by celinval** [comment]
BTW, we started seeing this issue on `nightly-2022-10-25`. This test works fine on `+nightly-2022-10-24`

**Comment by camshaft** [comment]
I was able to workaround this issue by replacing `data.len()` with `DATA_LEN`

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=4196b2135bd3c14f250f33ec5f160627

**Comment by saethlin** [comment]
I dropped the length of `data` to 120000 so that this runs on both sides of the regression. Doing the most naive benchmarking I measure a ~11% slowdown in `cargo clean && cargo check --tests` and a ~16% slowdown in `cargo miri test`.

How did this get past the compiler perf monitoring? Surely we didn't merge a PR in that time window that regressed one of the secondary benchmarks by 11%, right? Is this some workload that's just very different from `ctfe-stress`?

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23103814.20const.20eval.20interpreter.20step.20limit.20being.20hit.20on.20nigh.E2.80.A6)) (also to stimulate a wider T-compiler discussion about it)

@rustbot label -I-prioritize +P-high

**Comment by apiraino** [comment]
visiting during T-compiler meeting on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-11-17/near/310641367): followup discussion on this [Zulip stream](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/decision.20on.20.22Remove.20const.20eval.20limit.22.20.23103877)


@rustbot label -I-compiler-nominated
