### ISSUE TITLE
Error message when defining enum using struct syntax

### ISSUE THREAD

**Issue by rdfriese** [rust-lang/rust#103869]
Although I know Enums take to form of:
```rust
enum VecOrMap{
    Vec(Vec<usize>),
    Map(HashMap<String,usize>)
}
```
I sometimes find myself accidentally defining them as I would a Struct ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8d9f591838885f65ebf69ff075a3eae9)):
```rust
enum VecOrMap{
    vec: Vec<usize>,
    map: HashMap<String,usize>
}
```

The current output is:

```
   Compiling playground v0.0.1 (/playground)
error: expected one of `(`, `,`, `=`, `{`, or `}`, found `:`
 --> src/lib.rs:2:8
  |
2 |     vec: Vec<usize>,
  |        ^ expected one of `(`, `,`, `=`, `{`, or `}`

error: expected item, found `:`
 --> src/lib.rs:2:8
  |
2 |     vec: Vec<usize>,
  |        ^ expected item

error: could not compile `playground` due to 2 previous errors
```

This always takes more than a few seconds to parse and then realize my mistake. 
Is it possible to change this to something like:

```
It looks like you are trying to define an Enum using Struct syntax, change `vec: Vec<usize>` to `Vec(Vec<usize>)`
```

**Comment by BGR360** [comment]
Do you have any suggestion for how the compiler should distinguish between "trying to write an enum with struct syntax" and "trying to write a struct but used the enum keyword"?

**Comment by rdfriese** [comment]
Linking to the topic on internals where some other folks have left suggestions (https://internals.rust-lang.org/t/error-message-when-definining-enum-using-struct-syntax/17669).

Although none of those directly address your question.

My gut reaction is to assume that if the "enum" keyword is used that truly was the intention of the developer, but if it wasn't, hopefully some help message like the [following](https://internals.rust-lang.org/t/error-message-when-definining-enum-using-struct-syntax/17669/3?u=rdfriese):
```
error: expected one of `(`, `,`, `=`, `{`, or `}`, found `:`
 --> src/lib.rs:2:8
  |
2 |     vec: Vec<usize>,
  |        ^ expected one of `(`, `,`, `=`, `{`, or `}`
  |
  | help: enum variants are either `Variant(Type)` or `Variant { field: Type }`
```
Would provide enough information to trigger an "Oh wait did I really want to use an enum here?"
