### ISSUE TITLE
Tracking Issue for 3340 `exhaustive_match_output`

### ISSUE THREAD

**Issue by Xaeroxe** [rust-lang/rust#103818]
This is a tracking issue for the RFC "3340" (rust-lang/rfcs#3340).
The feature gate for the issue is `#![feature(exhaustive_match_output)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement the RFC (cc @rust-lang/XXX -- can anyone write up mentoring
      instructions?)
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

None yet

**Comment by csmoe** [comment]
Should we create this tracking issue after the rfc enters fcp stage?
It's a bit earlier now.

**Comment by Xaeroxe** [comment]
My apologies, I thought it was supposed to be created at this point.
