### ISSUE TITLE
fix to pass 7 tests in run::test and test/run-pass/rtio-processes.rs on android

### ISSUE THREAD

**Issue by yichoi** [rust-lang/rust#10380]
To enable test on android bot #9120

```
run::tests::test_finish_once
run::tests::test_finish_twice
run::tests::test_finish_with_output_once
run::tests::test_finish_with_output_twice
run::tests::test_process_output_error
run::tests::test_process_output_output
run::tests::test_process_status
```

and 

test/run-pass/rtio-processes.rs

It looks to me RtioProcess does not work properly on android.

**Comment by steveklabnik** [comment]
Triage: `rtio` is gone, but all these tests in `std::process` are still ignored for android.

**Comment by euclio** [comment]
I tried to run these tests with `./src/ci/docker/run.sh arm-android` but they all failed with `No such file or directory`, which seems suspect. Is there a better way to test. I have an android device available.
