### ISSUE TITLE
Invalid `target_arch` Cfg Resolution on M1 Mac

### ISSUE THREAD

**Issue by jafri** [rust-lang/rust#103819]
Building an application on M1 Mac using

```
    if cfg!(all(
        target_os = "macos",
        any(
            target_arch = "x86",
            target_arch = "x86_64"
        )
    ))
 ```
 
Resolves to `false` when building using `cargo build --target=x86_64-apple-darwin`
 
 target_arch inside the .rs file remains `aarch64`
 
Version:
 cargo 1.64.0 (387270bc7 2022-09-16)
 rustup 1.25.1 (2022-07-12)
 rustc 1.64.0 (a55dd71d5 2022-09-19)

**Comment by jafri** [comment]
Looks like this is just how it is: https://kazlauskas.me/entries/writing-proper-buildrs-scripts

**Comment by thomcc** [comment]
Yes, build scripts run on the host and not the target. You should use https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts.

It's a pain, yeah, but it's important that code using `#[cfg(target...)]` be able to rely on that being accurate for where it's currently running -- that code may not know it's in a build script, so it would be bad if that changed under those.

**Comment by Enselic** [comment]
Triage: Thanks for clarifications. Let's close as won't fix.
