### ISSUE TITLE
An `Internal Compiler Error` while compiling tauri

### ISSUE THREAD

**Issue by 1Kinoti** [rust-lang/rust#103959]
### Code
The error happened while compiling a newly generated [tauri](https://github.com/tauri-apps/tauri) app created with the command `cargo tauri init`
```Rust
cargo tauri dev
```

### Meta

`rustc --version --verbose`:
```
rustup 1.25.1 (bb60b1e89 2022-07-12)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` vrsion is `rustc 1.65.0 (897e37553 2022-11-02)
```

### Error output

```
thread 'rustc' panicked at 'index out of bounds: the len is 7862 but the index is 66588', /rustc/897e37553bba8b42751c67658967889d11ecd120/compiler/rustc_query_system/src/ich/hcx.rs:135:9
stack backtrace:
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```
   0:     0x7f128016dd40 - std::backtrace_rs::backtrace::libunwind::trace::h32eb3e08e874dd27
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f128016dd40 - std::backtrace_rs::backtrace::trace_unsynchronized::haa3f451d27bc11a5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f128016dd40 - std::sys_common::backtrace::_print_fmt::h5b94a01bb4289bb5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f128016dd40 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb070b7fa7e3175df
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f12801c8bfe - core::fmt::write::hd5207aebbb9a86e9
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/fmt/mod.rs:1202:17
   5:     0x7f128015e935 - std::io::Write::write_fmt::h3bd699bbd129ab8a
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/io/mod.rs:1679:15
   6:     0x7f12801709f3 - std::sys_common::backtrace::_print::h7a21be552fdf58da
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f12801709f3 - std::sys_common::backtrace::print::ha85c41fe4dd80b13
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f12801709f3 - std::panicking::default_hook::{{closure}}::h04cca40023d0eeca
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:295:22
   9:     0x7f12801706df - std::panicking::default_hook::haa3ca8c310ed5402
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:314:9
   Compiling ctor v0.1.26
  10:     0x7f128299e2e1 - rustc_driver[cfb34b1539811fe8]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f128017122d - std::panicking::rust_panic_with_hook::h7b190ce1a948faac
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:702:17
  12:     0x7f1280171087 - std::panicking::begin_panic_handler::{{closure}}::hbafbfdc3e1b97f68
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:588:13
  13:     0x7f128016e1ec - std::sys_common::backtrace::__rust_end_short_backtrace::hda93e5fef243b4c0
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7f1280170da2 - rust_begin_unwind
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
  15:     0x7f12801c57d3 - core::panicking::panic_fmt::h8d17ca1073d9a733
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
  16:     0x7f12801c5712 - core::panicking::panic_bounds_check::h8a412b863558c16a
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:84:5
  17:     0x7f128131e5f5 - <rustc_hir[f29014e7b3f8eb6c]::hir::ExprKind as rustc_data_structures[62ce3989ce8140ee]::stable_hasher::HashStable<rustc_query_system[860ed7b39cdfb46b]::ich::hcx::StableHashingContext>>::hash_stable
  18:     0x7f1281f94986 - <rustc_hir[f29014e7b3f8eb6c]::hir::BodyId as rustc_data_structures[62ce3989ce8140ee]::stable_hasher::HashStable<rustc_query_system[860ed7b39cdfb46b]::ich::hcx::StableHashingContext>>::hash_stable
  19:     0x7f1281f91484 - <rustc_hir[f29014e7b3f8eb6c]::hir::OwnerNode as rustc_data_structures[62ce3989ce8140ee]::stable_hasher::HashStable<rustc_query_system[860ed7b39cdfb46b]::ich::hcx::StableHashingContext>>::hash_stable
  20:     0x7f1281f8b393 - <rustc_ast_lowering[98f6d279767dbd94]::LoweringContext>::make_owner_info
  21:     0x7f1281f605f4 - <rustc_ast_lowering[98f6d279767dbd94]::LoweringContext>::with_hir_id_owner::<<rustc_ast_lowering[98f6d279767dbd94]::item::ItemLowerer>::with_lctx<<rustc_ast_lowering[98f6d279767dbd94]::item::ItemLowerer>::lower_item::{closure#0}>::{closure#0}>
  22:     0x7f1281f5d914 - <rustc_ast_lowering[98f6d279767dbd94]::item::ItemLowerer>::lower_node
  23:     0x7f1281f5ce38 - rustc_ast_lowering[98f6d279767dbd94]::lower_to_hir
  24:     0x7f128275375e - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::try_execute_query::<rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt, rustc_query_system[860ed7b39cdfb46b]::query::caches::ArenaCache<(), rustc_hir[f29014e7b3f8eb6c]::hir::Crate>>
  25:     0x7f1282753474 - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::get_query::<rustc_query_impl[d6191eea714bd250]::queries::hir_crate, rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt>
  26:     0x7f12814ec9e1 - <rustc_middle[a9ca1c3f9fd197cd]::hir::provide::{closure#1} as core[8c92e53db3fc2eaa]::ops::function::FnOnce<(rustc_middle[a9ca1c3f9fd197cd]::ty::context::TyCtxt, rustc_span[8f00505efff112e2]::def_id::LocalDefId)>>::call_once
  27:     0x7f12820f82e3 - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::get_query::<rustc_query_impl[d6191eea714bd250]::queries::hir_owner, rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt>
  28:     0x7f12820f7f69 - <rustc_query_impl[d6191eea714bd250]::Queries as rustc_middle[a9ca1c3f9fd197cd]::ty::query::QueryEngine>::hir_owner
  29:     0x7f12820fb339 - <rustc_middle[a9ca1c3f9fd197cd]::hir::map::Map>::get_module
  30:     0x7f128296e902 - rustc_middle[a9ca1c3f9fd197cd]::hir::map::hir_crate_items
  31:     0x7f1282781de1 - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::try_execute_query::<rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt, rustc_query_system[860ed7b39cdfb46b]::query::caches::ArenaCache<(), rustc_middle[a9ca1c3f9fd197cd]::hir::ModuleItems>>
  32:     0x7f1282781b04 - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::get_query::<rustc_query_impl[d6191eea714bd250]::queries::hir_crate_items, rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt>
  33:     0x7f1282804104 - rustc_interface[3182dd864eff9d7d]::proc_macro_decls::proc_macro_decls_static
  34:     0x7f12826d624a - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::try_execute_query::<rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt, rustc_query_system[860ed7b39cdfb46b]::query::caches::DefaultCache<(), core[8c92e53db3fc2eaa]::option::Option<rustc_span[8f00505efff112e2]::def_id::LocalDefId>>>
  35:     0x7f12826d5ea1 - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::get_query::<rustc_query_impl[d6191eea714bd250]::queries::proc_macro_decls_static, rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt>
  36:     0x7f1281d121d2 - <rustc_session[c5946fac61f8bc34]::session::Session>::time::<(), rustc_interface[3182dd864eff9d7d]::passes::analysis::{closure#0}::{closure#0}::{closure#1}>
  37:     0x7f1281d11c96 - <rustc_session[c5946fac61f8bc34]::session::Session>::time::<(), rustc_interface[3182dd864eff9d7d]::passes::analysis::{closure#0}>
  38:     0x7f1281d10c1e - rustc_interface[3182dd864eff9d7d]::passes::analysis
  39:     0x7f128276e7ed - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::try_execute_query::<rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt, rustc_query_system[860ed7b39cdfb46b]::query::caches::DefaultCache<(), core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>>
  40:     0x7f128276e517 - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::get_query::<rustc_query_impl[d6191eea714bd250]::queries::analysis, rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt>
  41:     0x7f128185a897 - <rustc_interface[3182dd864eff9d7d]::passes::QueryContext>::enter::<rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>
  42:     0x7f128184e28c - rustc_interface[3182dd864eff9d7d]::interface::create_compiler_and_run::<core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>, rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}>
  43:     0x7f128184cac1 - <scoped_tls[e395fa6e23b19669]::ScopedKey<rustc_span[8f00505efff112e2]::SessionGlobals>>::set::<rustc_interface[3182dd864eff9d7d]::interface::run_compiler<core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>, rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>
  44:     0x7f128184c7af - std[71cb4861428b0c25]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[3182dd864eff9d7d]::util::run_in_thread_pool_with_globals<rustc_interface[3182dd864eff9d7d]::interface::run_compiler<core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>, rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>
  45:     0x7f1282801d70 - <<std[71cb4861428b0c25]::thread::Builder>::spawn_unchecked_<rustc_interface[3182dd864eff9d7d]::util::run_in_thread_pool_with_globals<rustc_interface[3182dd864eff9d7d]::interface::run_compiler<core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>, rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>::{closure#1} as core[8c92e53db3fc2eaa]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  46:     0x7f128017b003 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h49f797984e2121bf
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
  47:     0x7f128017b003 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfa4f3d0ee6440e0b
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
  48:     0x7f128017b003 - std::sys::unix::thread::Thread::new::thread_start::h62ca48b42d48a8fc
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys/unix/thread.rs:108:17
  49:     0x7f1283ee4eae - start_thread
                               at /builddir/glibc-2.32/nptl/pthread_create.c:463:8
   Compiling memoffset v0.6.5
   Compiling glob v0.3.0
  50:     0x7f127ffb52ff - __GI___clone
                               at /builddir/glibc-2.32/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  51:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0 (897e37553 2022-11-02) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/897e37553bba8b42751c67658967889d11ecd120/compiler/rustc_query_system/src/query/plumbing.rs:371:11
stack backtrace:
   0:     0x7f128016dd40 - std::backtrace_rs::backtrace::libunwind::trace::h32eb3e08e874dd27
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f128016dd40 - std::backtrace_rs::backtrace::trace_unsynchronized::haa3f451d27bc11a5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f128016dd40 - std::sys_common::backtrace::_print_fmt::h5b94a01bb4289bb5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f128016dd40 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb070b7fa7e3175df
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f12801c8bfe - core::fmt::write::hd5207aebbb9a86e9
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/fmt/mod.rs:1202:17
   5:     0x7f128015e935 - std::io::Write::write_fmt::h3bd699bbd129ab8a
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/io/mod.rs:1679:15
   6:     0x7f12801709f3 - std::sys_common::backtrace::_print::h7a21be552fdf58da
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f12801709f3 - std::sys_common::backtrace::print::ha85c41fe4dd80b13
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f12801709f3 - std::panicking::default_hook::{{closure}}::h04cca40023d0eeca
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:295:22
   9:     0x7f12801706df - std::panicking::default_hook::haa3ca8c310ed5402
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:314:9
  10:     0x7f128299e2e1 - rustc_driver[cfb34b1539811fe8]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f128017122d - std::panicking::rust_panic_with_hook::h7b190ce1a948faac
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:702:17
  12:     0x7f1280171041 - std::panicking::begin_panic_handler::{{closure}}::hbafbfdc3e1b97f68
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:586:13
  13:     0x7f128016e1ec - std::sys_common::backtrace::__rust_end_short_backtrace::hda93e5fef243b4c0
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7f1280170da2 - rust_begin_unwind
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
  15:     0x7f12801c57d3 - core::panicking::panic_fmt::h8d17ca1073d9a733
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
  16:     0x7f12801c561d - core::panicking::panic::hf0565452d0d0936c
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
  17:     0x7f12827542a3 - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::try_execute_query::<rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt, rustc_query_system[860ed7b39cdfb46b]::query::caches::ArenaCache<(), rustc_hir[f29014e7b3f8eb6c]::hir::Crate>>
  18:     0x7f1282753474 - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::get_query::<rustc_query_impl[d6191eea714bd250]::queries::hir_crate, rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt>
  19:     0x7f1282965b2e - <rustc_middle[a9ca1c3f9fd197cd]::hir::provide::{closure#2} as core[8c92e53db3fc2eaa]::ops::function::FnOnce<(rustc_middle[a9ca1c3f9fd197cd]::ty::context::TyCtxt, rustc_span[8f00505efff112e2]::def_id::LocalDefId)>>::call_once
  20:     0x7f1282071425 - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::get_query::<rustc_query_impl[d6191eea714bd250]::queries::local_def_id_to_hir_id, rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt>
  21:     0x7f1282966a67 - <rustc_middle[a9ca1c3f9fd197cd]::hir::provide::{closure#7} as core[8c92e53db3fc2eaa]::ops::function::FnOnce<(rustc_middle[a9ca1c3f9fd197cd]::ty::context::TyCtxt, rustc_span[8f00505efff112e2]::def_id::DefId)>>::call_once
  22:     0x7f1281fb71b0 - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::get_query::<rustc_query_impl[d6191eea714bd250]::queries::def_span, rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt>
  23:     0x7f1281fb6de3 - <rustc_query_impl[d6191eea714bd250]::Queries as rustc_middle[a9ca1c3f9fd197cd]::ty::query::QueryEngine>::def_span
  24:     0x7f12832f1536 - <rustc_span[8f00505efff112e2]::def_id::DefId as rustc_query_impl[d6191eea714bd250]::keys::Key>::default_span
  25:     0x7f12833c7ac1 - rustc_query_impl[d6191eea714bd250]::plumbing::create_query_frame::<rustc_span[8f00505efff112e2]::def_id::LocalDefId>
  26:     0x7f12833e80e3 - <<rustc_query_impl[d6191eea714bd250]::Queries>::try_collect_active_jobs::{closure#7} as core[8c92e53db3fc2eaa]::ops::function::FnOnce<(rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt, rustc_span[8f00505efff112e2]::def_id::LocalDefId)>>::call_once
  27:     0x7f12832607d5 - <rustc_query_system[860ed7b39cdfb46b]::query::plumbing::QueryState<rustc_span[8f00505efff112e2]::def_id::LocalDefId>>::try_collect_active_jobs::<rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt>
  28:     0x7f12833e9764 - <rustc_query_impl[d6191eea714bd250]::Queries>::try_collect_active_jobs
  29:     0x7f12833dac48 - rustc_query_system[860ed7b39cdfb46b]::query::job::print_query_stack::<rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt>
  30:     0x7f1282a7b272 - rustc_interface[3182dd864eff9d7d]::interface::try_print_query_stack
  31:     0x7f12829a0b69 - rustc_driver[cfb34b1539811fe8]::report_ice
  32:     0x7f128017122d - std::panicking::rust_panic_with_hook::h7b190ce1a948faac
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:702:17
  33:     0x7f1280171087 - std::panicking::begin_panic_handler::{{closure}}::hbafbfdc3e1b97f68
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:588:13
  34:     0x7f128016e1ec - std::sys_common::backtrace::__rust_end_short_backtrace::hda93e5fef243b4c0
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18
  35:     0x7f1280170da2 - rust_begin_unwind
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
  36:     0x7f12801c57d3 - core::panicking::panic_fmt::h8d17ca1073d9a733
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
  37:     0x7f12801c5712 - core::panicking::panic_bounds_check::h8a412b863558c16a
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:84:5
  38:     0x7f128131e5f5 - <rustc_hir[f29014e7b3f8eb6c]::hir::ExprKind as rustc_data_structures[62ce3989ce8140ee]::stable_hasher::HashStable<rustc_query_system[860ed7b39cdfb46b]::ich::hcx::StableHashingContext>>::hash_stable
  39:     0x7f1281f94986 - <rustc_hir[f29014e7b3f8eb6c]::hir::BodyId as rustc_data_structures[62ce3989ce8140ee]::stable_hasher::HashStable<rustc_query_system[860ed7b39cdfb46b]::ich::hcx::StableHashingContext>>::hash_stable
  40:     0x7f1281f91484 - <rustc_hir[f29014e7b3f8eb6c]::hir::OwnerNode as rustc_data_structures[62ce3989ce8140ee]::stable_hasher::HashStable<rustc_query_system[860ed7b39cdfb46b]::ich::hcx::StableHashingContext>>::hash_stable
  41:     0x7f1281f8b393 - <rustc_ast_lowering[98f6d279767dbd94]::LoweringContext>::make_owner_info
  42:     0x7f1281f605f4 - <rustc_ast_lowering[98f6d279767dbd94]::LoweringContext>::with_hir_id_owner::<<rustc_ast_lowering[98f6d279767dbd94]::item::ItemLowerer>::with_lctx<<rustc_ast_lowering[98f6d279767dbd94]::item::ItemLowerer>::lower_item::{closure#0}>::{closure#0}>
  43:     0x7f1281f5d914 - <rustc_ast_lowering[98f6d279767dbd94]::item::ItemLowerer>::lower_node
  44:     0x7f1281f5ce38 - rustc_ast_lowering[98f6d279767dbd94]::lower_to_hir
  45:     0x7f128275375e - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::try_execute_query::<rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt, rustc_query_system[860ed7b39cdfb46b]::query::caches::ArenaCache<(), rustc_hir[f29014e7b3f8eb6c]::hir::Crate>>
  46:     0x7f1282753474 - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::get_query::<rustc_query_impl[d6191eea714bd250]::queries::hir_crate, rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt>
  47:     0x7f12814ec9e1 - <rustc_middle[a9ca1c3f9fd197cd]::hir::provide::{closure#1} as core[8c92e53db3fc2eaa]::ops::function::FnOnce<(rustc_middle[a9ca1c3f9fd197cd]::ty::context::TyCtxt, rustc_span[8f00505efff112e2]::def_id::LocalDefId)>>::call_once
  48:     0x7f12820f82e3 - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::get_query::<rustc_query_impl[d6191eea714bd250]::queries::hir_owner, rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt>
  49:     0x7f12820f7f69 - <rustc_query_impl[d6191eea714bd250]::Queries as rustc_middle[a9ca1c3f9fd197cd]::ty::query::QueryEngine>::hir_owner
  50:     0x7f12820fb339 - <rustc_middle[a9ca1c3f9fd197cd]::hir::map::Map>::get_module
  51:     0x7f128296e902 - rustc_middle[a9ca1c3f9fd197cd]::hir::map::hir_crate_items
  52:     0x7f1282781de1 - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::try_execute_query::<rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt, rustc_query_system[860ed7b39cdfb46b]::query::caches::ArenaCache<(), rustc_middle[a9ca1c3f9fd197cd]::hir::ModuleItems>>
  53:     0x7f1282781b04 - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::get_query::<rustc_query_impl[d6191eea714bd250]::queries::hir_crate_items, rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt>
  54:     0x7f1282804104 - rustc_interface[3182dd864eff9d7d]::proc_macro_decls::proc_macro_decls_static
  55:     0x7f12826d624a - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::try_execute_query::<rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt, rustc_query_system[860ed7b39cdfb46b]::query::caches::DefaultCache<(), core[8c92e53db3fc2eaa]::option::Option<rustc_span[8f00505efff112e2]::def_id::LocalDefId>>>
  56:     0x7f12826d5ea1 - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::get_query::<rustc_query_impl[d6191eea714bd250]::queries::proc_macro_decls_static, rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt>
  57:     0x7f1281d121d2 - <rustc_session[c5946fac61f8bc34]::session::Session>::time::<(), rustc_interface[3182dd864eff9d7d]::passes::analysis::{closure#0}::{closure#0}::{closure#1}>
  58:     0x7f1281d11c96 - <rustc_session[c5946fac61f8bc34]::session::Session>::time::<(), rustc_interface[3182dd864eff9d7d]::passes::analysis::{closure#0}>
  59:     0x7f1281d10c1e - rustc_interface[3182dd864eff9d7d]::passes::analysis
  60:     0x7f128276e7ed - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::try_execute_query::<rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt, rustc_query_system[860ed7b39cdfb46b]::query::caches::DefaultCache<(), core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>>
  61:     0x7f128276e517 - rustc_query_system[860ed7b39cdfb46b]::query::plumbing::get_query::<rustc_query_impl[d6191eea714bd250]::queries::analysis, rustc_query_impl[d6191eea714bd250]::plumbing::QueryCtxt>
  62:     0x7f128185a897 - <rustc_interface[3182dd864eff9d7d]::passes::QueryContext>::enter::<rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>
  63:     0x7f128184e28c - rustc_interface[3182dd864eff9d7d]::interface::create_compiler_and_run::<core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>, rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}>
  64:     0x7f128184cac1 - <scoped_tls[e395fa6e23b19669]::ScopedKey<rustc_span[8f00505efff112e2]::SessionGlobals>>::set::<rustc_interface[3182dd864eff9d7d]::interface::run_compiler<core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>, rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>
  65:     0x7f128184c7af - std[71cb4861428b0c25]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[3182dd864eff9d7d]::util::run_in_thread_pool_with_globals<rustc_interface[3182dd864eff9d7d]::interface::run_compiler<core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>, rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>
  66:     0x7f1282801d70 - <<std[71cb4861428b0c25]::thread::Builder>::spawn_unchecked_<rustc_interface[3182dd864eff9d7d]::util::run_in_thread_pool_with_globals<rustc_interface[3182dd864eff9d7d]::interface::run_compiler<core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>, rustc_driver[cfb34b1539811fe8]::run_compiler::{closure#1}>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>::{closure#0}, core[8c92e53db3fc2eaa]::result::Result<(), rustc_errors[f77a66b68db622d5]::ErrorGuaranteed>>::{closure#1} as core[8c92e53db3fc2eaa]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  67:     0x7f128017b003 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h49f797984e2121bf
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
  68:     0x7f128017b003 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfa4f3d0ee6440e0b
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
  69:     0x7f128017b003 - std::sys::unix::thread::Thread::new::thread_start::h62ca48b42d48a8fc
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys/unix/thread.rs:108:17
  70:     0x7f1283ee4eae - start_thread
                               at /builddir/glibc-2.32/nptl/pthread_create.c:463:8
  71:     0x7f127ffb52ff - __GI___clone
                               at /builddir/glibc-2.32/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  72:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0 (897e37553 2022-11-02) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
error: could not compile `brotli`

</p>
</details>

**Comment by kpreid** [comment]
Triage: Relabeling issues which don't have a runnable reproduction (as opposed to having a non-minimized one) to the new label S-needs-repro.
@rustbot label +S-needs-repro -E-needs-mcve
