### ISSUE TITLE
About last Rust release

### ISSUE THREAD

**Issue by rdwnsjjd** [rust-lang/rust#103999]
I know maybe this is not the place for this topic. But consider this as a problem that I introduce to your release and please accept it as an issue

I'm an Iranian person and of course fascinated by the Rust language! 
we have been under the heaviest US and Western sanctions for 43 years.  The voices of children suffering from diseases like eb are repeated in our ears, but we can't do anything for them because America and the West have banned the most necessary medicines for us (of course, I must inform you that today, our scientists reached this technology and we can now do this medicine and dressing for EB children! Like everything we have done so far. [read more](https://www.irna.ir/amp/84786840/) ). 
For all this time, you have said nothing about our sufferings, and of course we have no expectations. because you are influenced by your media. We were alone from the beginning, but we are strong and under all the sanctions, we also achieved our own successes and we do not need the sympathy of others. so you can see Iran's scientific, cultural and social rankings in the world in 43 years ago under heaviest sanctions [here](https://fa.m.wikipedia.org/wiki/%D8%B1%D8%AA%D8%A8%D9%87%E2%80%8C%D8%A8%D9%86%D8%AF%DB%8C%E2%80%8C%D9%87%D8%A7%DB%8C_%D8%A8%DB%8C%D9%86%E2%80%8C%D8%A7%D9%84%D9%85%D9%84%D9%84%DB%8C_%D8%A7%DB%8C%D8%B1%D8%A7%D9%86) and many other references u can search by your self without Impact of media. of course, this is not my issue and I just wanted to say that we can handle the sanctions ourselves.
but my issue is it: now that the media has caught your eye and won't let you see the reality and hear our voice, so please either continue your silence or If you are really worried about us Iranians, as you condemned Mahsa's death in this release, in your next release, condemn the cruel sanctions imposed by America and the West on Iranians. otherwise, I just as a human, despite all the attractive and excellent features of the Rust language and despite all my love for it, I can no longer continue to use it.

With all respects and thanks.

**Comment by khionu** [comment]
As a trans woman, as someone who has had to deal with some of the worst of US poverty over the course of my life (and acknowledging how privileged that makes me relative to the rest of the world), I can't agree with silence in the face of suffering. That said, I know that is a super ideological stance, and I know it does nothing for your suffering.

It's not easy figuring out what to speak out on. As you've noted, we have to work through filters of information that make it extremely hard to see the truth, never mind process enough of the truth to speak. That said, this is our problem. We as a project will need to figure out how to improve this over time. Having gotten to know more and more of the project members, I genuinely believe in the sincerity here. It's a matter of us working past the shrouds that keep us from being the allies we want to be.

We have been falling short. We will keep falling short, most likely. But we're going to keep trying to do right by our international community, by all humans.
