### ISSUE TITLE
Cargo.lock / dependency information in elf section

### ISSUE THREAD

**Issue by Firstyear** [rust-lang/rust#103907]
Hi there,

This is a feature suggestion for Rust to assist with Linux distribution and auditing. It would be useful for us to have the list of crates/dependencies that were used and their versions in an elf section of the resulting binary. This would allow auditing of vulnerabilities by tools like cargo-audit *post* compilation. 

Where this is useful is linux distributions, as the metadata in the elf can be used and extracted into the package manager allowing security teams discover and respond to potential security risks. Since this is "built into" the elf, it is good for people supplying software to a distribution since it would "just work" via compiler options/flags that could be set in the build service.

This also is useful in auditing of container images on registries like hub.docker.com as the resulting elf can be scanned and flagged indicating to the provider of the image that they need to re-vendor and update.

Alternate workarounds we could pursue are policy level requirements that all rust packages ship their Cargo.lock in packages instead. This is something that we are likely to pursue in the shortterm without this feature being present, and it's a reasonable solution in itself. Having the metadata in the elf would likely be "cleaner" and enable a broader set of possible auditing scenarioes however. 

I am quite sure this has been previously proposed, but I can't find the original issue, so please let me know.

**Comment by ehuss** [comment]
There is a proposal to add this at https://github.com/rust-lang/rfcs/pull/2801. I recommend following that.  There's also an implementation of it at https://github.com/rust-secure-code/cargo-auditable.

**Comment by Firstyear** [comment]
Thank you @ehuss ! I knew I'd seen it somewhere before :)
