### ISSUE TITLE
Allocations always assumed to succeed in optimizations

### ISSUE THREAD

**Issue by vladov3000** [rust-lang/rust#103948]
I tried this code:

```rust
#![crate_type = "lib"]
#![feature(allocator_api)]

use std::alloc::{Allocator, Layout, System};

pub fn have_mem() -> bool {
    System.allocate(Layout::from_size_align(4, 4).unwrap()).is_ok()
}
```

I expected to see this happen:
It should generate assembly that does the allocation, and checks it succeeded.

Instead, this happened:
The code is is optimized to always return true on the highest optimization level. See the following disassembly:
https://godbolt.org/z/9P3e8nnPq

### Meta

`rustc --version --verbose`:
```
rustc 1.66.0-nightly (57f097ea2 2022-10-01)
```

**Comment by RReverser** [comment]
This is basically the same as `malloc(...) != NULL` in C, which Clang also optimizes to true: https://godbolt.org/z/5cMzMo1E5

IIUC, this is a legal optimisation as long as your allocated pointer is unused for any side-effects. Checking whether it's been allocated isn't a side-effect, and can return true since in fact nothing needs to be allocated at runtime, so it "always succeeds".

OTOH if you do use the pointer somehow, e.g. `.unwrap()` to return from the function, you'll see that `.unwrap()` doesn't assume it's been allocated and produces an error branch as expected, because allocation does in fact occur at runtime: https://godbolt.org/z/nqGahhzT3

**Comment by vladov3000** [comment]
Wait, the allocation itself is a side effect? How can that be optimized out? Also, yes I stole this example from some Clang code which I thought was funky due to (imo poor) C semantics. Note: I assume this is an LLVM issue but I haven't found much discussion about it.

Assuming this optimization is ok then, how do I actually perform the allocation, do nothing with it, and check if it succeeded in rust? Do I just add an extraneous memzero() to make use of the pointer and force the compiler to keep it?

**Comment by RReverser** [comment]
> Note: I assume this is an LLVM issue but I haven't found much discussion about it.

There have been couple of discussions over years, e.g. quick search found this one, seems relevant but haven't looked deeply through it: https://lists.llvm.org/pipermail/llvm-dev/2015-April/084101.html

My TL;DR understanding is that standard allows to supply own malloc/free, and LLVM is free to "supply" one that 1) is pure and 2) always succeeds during compilation, so they can use that assumption for optimisations.

> how do I actually perform the allocation, do nothing with it, and check if it succeeded in rust

I'm not sure what's your actual usecase, but, as usual to prevent compiler from optimising values out, you can use `test::black_box` (or some of its stable alternatives): https://godbolt.org/z/dcs4WK36j

**Comment by Monadic-Cat** [comment]
I'll just add that this is mentioned on the `GlobalAlloc` safety contract, though it doesn't appear to be mentioned on the `Allocator` one.
https://doc.rust-lang.org/nightly/std/alloc/trait.GlobalAlloc.html#safety

**Comment by vladov3000** [comment]
Thank you for the clarifications - I understand this behavior is correct and expected now. Although, I am a bit disappointed, the whole pitch was that errors aren't just dispersed into the wind and that it wouldn't make &%$# optimizations like most C compilers do (though it would be pretty annoying to use Options for every alloc without some sort of Monad syntactic sugar).
