### ISSUE TITLE
fix to pass bench/shootout-k-nucleotide-pipes.rs on android

### ISSUE THREAD

**Issue by yichoi** [rust-lang/rust#10393]
To enable test on android bot #9120

It is not fininshed on android

**Comment by FlaPer87** [comment]
Triage bump: The tests are still being ignored for android.

**Comment by steveklabnik** [comment]
Triage: https://github.com/rust-lang/rust/pull/31274 removed all of `src/test/bench`, so this is no longer ignored 😛
