### ISSUE TITLE
change `mk_const` to take a ConstKind and Ty argument instead of writing out the ty::ConstS struct everywhere

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#103974]
We keep repeating this, but it adds no helpful information for readers of the call site, it's just boilerplate and noise.

Steps:

1. change https://github.com/rust-lang/rust/blob/b66cf6fe168e10dcbfed4320a5e84c0c28eee814/compiler/rustc_middle/src/ty/context.rs#L2302 to use `mk_const_internal` instead of `mk_const`. This is what generates the current `mk_const` function.
2. Create a `mk_const` function next to https://github.com/rust-lang/rust/blob/b66cf6fe168e10dcbfed4320a5e84c0c28eee814/compiler/rustc_middle/src/ty/context.rs#L2644 that takes two arguments and forwards them to a `mk_const_internal(ty::ConstS { val, kind }`
3. fix up all the `mk_const` call sites to make them stop using `ty::ConstS` and instead pass the two fields as arguments

**Comment by V0ldek** [comment]
Hey, looks like a good issue for a first-time contributor, I can take this.

@rustbot claim
