### ISSUE TITLE
how to install rust offline?

### ISSUE THREAD

**Issue by ningmingxiao** [rust-lang/rust#103910]
1.I down load  rust-1.57.0-x86_64-unknown-linux-musl.tar.gz
2.tar -xzvf rust-1.57.0-x86_64-unknown-linux-musl.tar.gz
3.cd  rust-1.57.0-x86_64-unknown-linux-musl
4.sh install.sh 
```
[root@localhost ~]# cargo
-bash: /usr/local/bin/cargo: No such file or directory
```
but   use rust-1.57.0-x86_64-unknown-linux-gnu.tar.gz work well

**Comment by clubby789** [comment]
The Musl distribution of Rust won't work on a system using GNU libc

**Comment by fee1-dead** [comment]
I think the musl target triple is linked to musl libc dynamically.

**Comment by ningmingxiao** [comment]
> The Musl distribution of Rust won't work on a system using GNU libc

I install musl-filesystem-1.2.1-1.el8.x86_64.rpm and  musl-libc-1.2.1-1.el8.x86_64.rpm  will show 
```
[root@localhost nmx]# cargo version
Error loading shared library libgcc_s.so.1: No such file or directory (needed by /usr/local/bin/cargo)
Error relocating /usr/local/bin/cargo: _Unwind_Resume: symbol not found
Error relocating /usr/local/bin/cargo: _Unwind_GetIPInfo: symbol not found
Error relocating /usr/local/bin/cargo: _Unwind_GetDataRelBase: symbol not found
Error relocating /usr/local/bin/cargo: _Unwind_GetRegionStart: symbol not found
Error relocating /usr/local/bin/cargo: _Unwind_SetGR: symbol not found
Error relocating /usr/local/bin/cargo: _Unwind_GetTextRelBase: symbol not found
Error relocating /usr/local/bin/cargo: _Unwind_DeleteException: symbol not found
Error relocating /usr/local/bin/cargo: _Unwind_RaiseException: symbol not found
Error relocating /usr/local/bin/cargo: _Unwind_GetIP: symbol not found

```

**Comment by ningmingxiao** [comment]
> CentOS uses GNU libc, so you can't use the Musl distribution. It will dynamically link against Musl libc, and likely uses Musl-specific details. You need the GNU distribution of Rust

thank you , I down load https://musl.cc/x86_64-linux-musl-cross.tgz
then tar -xzvf x86_64-linux-musl-cross.tgz  -C  /usr/local/
export  MUSL=/usr/local/x86_64-linux-musl-cross
export PATH=$PATH:$MUSL/bin
add 
```
[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
```
to  /root/.cargo/config

then cargo build --release --target x86_64-unknown-linux-musl
```
   Compiling demo v0.1.0 (/home/nmx/demo)
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-linux-musl` target may not be installed
  = help: consider downloading the target with `rustup target add x86_64-unknown-linux-musl`

error: cannot find macro `println` in this scope
 --> src/main.rs:2:5
  |
2 |     println!("Hello, world!");
  |     ^^^^^^^

error: requires `sized` lang_item

For more information about this error, try `rustc --explain E0463`.
error: could not compile `demo` due to 3 previous errors
[root@host-10-89-235-184 target]# rustup target add
error: error: The following required arguments were not provided:
    <target>...

USAGE:
    rustup target add [OPTIONS] <target>...

```
I can't use rustup target add x86_64-unknown-linux-musl offile

**Comment by Dylan-DPC** [comment]
Closing this to clean up the issue tracker. If you or anyone reading this in the future needs help you can ask in the various rust support places.

**Comment by BangrongMo** [comment]
> > CentOS uses GNU libc, so you can't use the Musl distribution. It will dynamically link against Musl libc, and likely uses Musl-specific details. You need the GNU distribution of Rust
> 
> thank you , I down load https://musl.cc/x86_64-linux-musl-cross.tgz then tar -xzvf x86_64-linux-musl-cross.tgz -C /usr/local/ export MUSL=/usr/local/x86_64-linux-musl-cross export PATH=$PATH:$MUSL/bin add
> 
> ```
> [target.x86_64-unknown-linux-musl]
> linker = "x86_64-linux-musl-gcc"
> ```
> 
> to /root/.cargo/config
> 
> then cargo build --release --target x86_64-unknown-linux-musl
> 
> ```
>    Compiling demo v0.1.0 (/home/nmx/demo)
> error[E0463]: can't find crate for `std`
>   |
>   = note: the `x86_64-unknown-linux-musl` target may not be installed
>   = help: consider downloading the target with `rustup target add x86_64-unknown-linux-musl`
> 
> error: cannot find macro `println` in this scope
>  --> src/main.rs:2:5
>   |
> 2 |     println!("Hello, world!");
>   |     ^^^^^^^
> 
> error: requires `sized` lang_item
> 
> For more information about this error, try `rustc --explain E0463`.
> error: could not compile `demo` due to 3 previous errors
> [root@host-10-89-235-184 target]# rustup target add
> error: error: The following required arguments were not provided:
>     <target>...
> 
> USAGE:
>     rustup target add [OPTIONS] <target>...
> ```
> 
> I can't use rustup target add x86_64-unknown-linux-musl offile
> 
> ```
> root@host-10-89-235-184 demo]# x86_64-linux-musl-gcc -v
> Using built-in specs.
> COLLECT_GCC=x86_64-linux-musl-gcc
> COLLECT_LTO_WRAPPER=/usr/local/x86_64-linux-musl-cross/bin/../libexec/gcc/x86_64-linux-musl/11.2.1/lto-wrapper
> Target: x86_64-linux-musl
> Configured with: ../src_gcc/configure --enable-languages=c,c++,fortran CC='gcc -static --static' CXX='g++ -static --static' FC='gfortran -static --static' CFLAGS='-g0 -O2 -fno-align-functions -fno-align-jumps -fno-align-loops -fno-align-labels -Wno-error' CXXFLAGS='-g0 -O2 -fno-align-functions -fno-align-jumps -fno-align-loops -fno-align-labels -Wno-error' FFLAGS='-g0 -O2 -fno-align-functions -fno-align-jumps -fno-align-loops -fno-align-labels -Wno-error' LDFLAGS='-s -static --static' --enable-default-pie --enable-static-pie --disable-cet --disable-bootstrap --disable-assembly --disable-werror --target=x86_64-linux-musl --prefix= --libdir=/lib --disable-multilib --with-sysroot=/x86_64-linux-musl --enable-tls --disable-libmudflap --disable-libsanitizer --disable-gnu-indirect-function --disable-libmpx --enable-initfini-array --enable-libstdcxx-time=rt --enable-deterministic-archives --enable-libstdcxx-time --enable-libquadmath --enable-libquadmath-support --disable-decimal-float --with-build-sysroot=/tmp/m1132/build/local/x86_64-linux-musl/obj_sysroot AR_FOR_TARGET=/tmp/m1132/build/local/x86_64-linux-musl/obj_binutils/binutils/ar AS_FOR_TARGET=/tmp/m1132/build/local/x86_64-linux-musl/obj_binutils/gas/as-new LD_FOR_TARGET=/tmp/m1132/build/local/x86_64-linux-musl/obj_binutils/ld/ld-new NM_FOR_TARGET=/tmp/m1132/build/local/x86_64-linux-musl/obj_binutils/binutils/nm-new OBJCOPY_FOR_TARGET=/tmp/m1132/build/local/x86_64-linux-musl/obj_binutils/binutils/objcopy OBJDUMP_FOR_TARGET=/tmp/m1132/build/local/x86_64-linux-musl/obj_binutils/binutils/objdump RANLIB_FOR_TARGET=/tmp/m1132/build/local/x86_64-linux-musl/obj_binutils/binutils/ranlib READELF_FOR_TARGET=/tmp/m1132/build/local/x86_64-linux-musl/obj_binutils/binutils/readelf STRIP_FOR_TARGET=/tmp/m1132/build/local/x86_64-linux-musl/obj_binutils/binutils/strip-new --build=x86_64-pc-linux-muslx32 --host=x86_64-pc-linux-muslx32
> Thread model: posix
> Supported LTO compression algorithms: zlib
> gcc version 11.2.1 20211120 (GCC)
> ```

your may be want to cross compilation? 
1.just download  rust-xxx-x86_64-unknown-linux-gnu.tar.xz 
2.tar -xzvf  rust-xxx-x86_64-unknown-linux-gnu.tar.xz 
3.down load https://musl.cc/x86_64-linux-musl-cross.tgz
4.tar -xzvf x86_64-linux-musl-cross.tgz -C /usr/local/
export MUSL=/usr/local/x86_64-linux-musl-cross
export PATH=$PATH:$MUSL/bin
add

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"

to /root/.cargo/config

then cargo build --release --target x86_64-unknown-linux-musl

I use fedora41 with base on glibc too，it is works

![Image](https://github.com/user-attachments/assets/0b02f42d-c0b3-46d1-bcc4-2d35d4481f66)
