### ISSUE TITLE
Tracking Issue for Hashing in const context

### ISSUE THREAD

**Issue by onestacked** [rust-lang/rust#104061]
Feature gate: `#![feature(const_hash)]`

This is a tracking issue for constructing "hashers" in const conext.

### Public API

```rust
// std::collections::hash
impl DefaultHasher {
    pub const fn new() -> DefaultHasher;
}

impl SipHasher {
    #[deprecated]
    pub const fn new() -> SipHasher;
    #[deprecated]
    pub const fn new_with_keys(key0: u64, key1: u64) -> SipHasher;
}
impl SipHasher13 {
    #[deprecated]
    pub const fn new() -> SipHasher;
    #[deprecated]
    pub const fn new_with_keys(key0: u64, key1: u64) -> SipHasher;
}
```

### Steps / History

- [x] Implementation: #104060
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by RalfJung** [comment]
Most of this feature got removed in https://github.com/rust-lang/rust/pull/110393, I updated the description to match what is left.
