### ISSUE TITLE
function type params are not checked for well-formedness

### ISSUE THREAD

**Issue by aliemjay** [rust-lang/rust#104005]
This unsound program shouldn't compile, but it does: https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=2e0af084bc8b2ec9f440a2c5dab7992f
```rust
use std::fmt::Display;

trait Displayable {
    fn display(self) -> Box<dyn Display>;
}

impl<T: Display> Displayable for (T, Option<&'static T>) {
    fn display(self) -> Box<dyn Display> {
        Box::new(self.0)
    }
}

fn extend_lt<T, U>(val: T) -> Box<dyn Display>
where
    (T, Option<U>): Displayable,
{
    Displayable::display((val, None))
}

fn main() {
    // The type parameter `U = &'static &'temporary str` is ill-formed
    // because it does not enforce `'temporary: 'static` ...
    let val = extend_lt(&String::from("blah blah blah"));
    println!("{}", val);
}
```

I was shocked discovering that. I thought `WellFormed(U)` is part of the caller bounds of  `extend_lt`.

@rustbot label C-bug T-types I-unsound A-lifetimes

**Comment by aliemjay** [comment]
So this is a MIR borrowck bug because it regressed in v1.36 when it was enabled on 2015 edition.
@rustbot label regression-from-stable-to-stable

Remarkably adding type annotation to call site
```diff
-    let val = extend_lt(&String::from("blah blah blah"));
+    let val = extend_lt::<_, &_>(&String::from("blah blah blah"));
```
makes it not compiling because user annotations are always checked for well-formedness.

**Comment by oli-obk** [comment]
cc @lcnr

**Comment by aliemjay** [comment]
A case that regressed with full NLL in v1.63 - it was rejected by the HIR borrowck:
```rust
// ... same as above
fn test<'a>() {
    let _: fn(&'a str) -> _ = extend_lt;
}
```

**Comment by aliemjay** [comment]
I'd argue that this should be rejected as well:
```rust
trait Trait<A>: Sized {
    fn call(self) {}
}

impl<T> Trait<&'static T> for T {}

fn main() {
    Trait::call(&String::new());
}
```

This is necessary to fix #98852 in a sound way. At this point we should basically WF-check all fn item substs.

**Comment by jackh726** [comment]
> This is a soundness bug that regressed fairly recently for some repros, so I think it's P-high.

https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23104005.20function.20type.20params.20are.20not.20checked.20for.20well-forme.E2.80.A6/near/308263767

**Comment by DianQK** [comment]
Hi, @aliemjay.
Are you still working on this issue? I would like to get started with MIR with this issue.

**Comment by aliemjay** [comment]
> Hi, @aliemjay.
> Are you still working on this issue? I would like to get started with MIR with this issue.

Hi,  You can claim this. There is #104098, which I was too busy to finish. You can take it over to rebase, address review comments and push for a crater run.

**Comment by DianQK** [comment]
> > Hi, @aliemjay.
> > Are you still working on this issue? I would like to get started with MIR with this issue.
> 
> Hi, You can claim this. There is #104098, which I was too busy to finish. You can take it over to rebase, address review comments and push for a crater run.

Thanks, I'll give it a try. I added a corresponding question at https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/lifetime-issue-104005 as well.
