### ISSUE TITLE
Strange indentation in libtest output

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#104092]
libtest output recently started indenting *some* but not all test results:
```
$./x.py test library/alloc --stage 0 --test-args "--format pretty" --no-doc
running 373 tests
test raw_vec::tests::allocator_param ... ok
test raw_vec::tests::reserve_does_not_overallocate ... ok
test raw_vec::tests::zst ... ok
test alloc::tests::allocate_zeroed ... ignored
test raw_vec::tests::zst_reserve_panic - should panic ... ok
test raw_vec::tests::zst_reserve_exact_panic - should panic ... ok
test alloc::tests::alloc_owned_small                         ... ok   <!----- notice this one!
test collections::binary_heap::tests::test_iter_rev_cloned_collect ... ok
[...]
test collections::linked_list::tests::test_drop ... ok
test collections::linked_list::tests::test_drop_panic ... ok
test collections::vec_deque::tests::bench_push_front_100     ... ok  <!---- and these!
test collections::vec_deque::tests::bench_push_back_100      ... ok
test collections::vec_deque::tests::bench_pop_back_100       ... ok
test collections::vec_deque::tests::bench_pop_front_100      ... ok
test collections::vec_deque::tests::test_swap_front_back_remove ... ok
test collections::vec_deque::tests::test_insert ... ok
test collections::vec_deque::tests::test_get ... ok
test collections::vec_deque::tests::test_get_mut ... ok
test collections::vec_deque::tests::bench_retain_whole_10000 ... ok
```
Seems like benchmarks are indented but regular tests are not.

**Comment by RalfJung** [comment]
Cc @thomcc any idea which change might have caused this? I think this must be fairly recent but haven't tried bisecting yet.

**Comment by m-ou-se** [comment]
Is this still reproducable?

**Comment by RalfJung** [comment]
With https://github.com/rust-lang/rust/pull/108659 this can no longer be tested using x.py, since bootstrap now does test output formatting itself.

So this now needs a little cargo project with a test and a benchmark, to check what libtest actually does.

**Comment by cuviper** [comment]
Seems like that could use context if the bench is only being run as a test, then don't pad.

The padding is desirable for benchmark output so the numeric values line up, for easier visual comparison. You could argue either way about tests -- maybe ok/FAILED would stand out even more with padded alignment.

**Comment by Enselic** [comment]
PR with regression tests and a fix (in that order): https://github.com/rust-lang/rust/pull/118548
