### ISSUE TITLE
improve documentation for `std::pin::Pin`

### ISSUE THREAD

**Issue by vincenzopalazzo** [rust-lang/rust#104107]
### Summary

As @yoshuawuyts pointed out on [Zulip stream](https://rust-lang.zulipchat.com/#narrow/stream/187312-wg-async/topic/Projecting.20Pin.3CVec.3E.20to.20Vec.3CPin.3E/near/308406868) the in struct, there is a lack of documentation on some of the methods such as `Pin::new()` and `Pin::into_inner` 

This should be relatively straight forward to document, and I can mentor someone if there is interest

**Comment by ch-iv** [comment]
I can try doing this

**Comment by vincenzopalazzo** [comment]
Fixed in https://github.com/rust-lang/rust/pull/105902
