### ISSUE TITLE
CLion IDE Debug Rust On Window 10 , Rust 1.65

### ISSUE THREAD

**Issue by kwaynet** [rust-lang/rust#104157]
### Code

```Rust
<code>

fn main() {
    println!("Hello, world!");
}
```

### Meta

`rustc --version --verbose`:
```
<version>
rust => 1.65

toolchains => stable-x86_64-pc-windows-gnu

```

### Error output

```
<output>

E:/src/demo/backend/rust/project/target/debug/project.exe
com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver$GDBCommandException: Undefined item: "UTF-8".

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by nagisa** [comment]
This doesn’t look like an ICE, and if it is the report is insufficient to tell anything about it.

For issues with JetBrains products specifically, please reach out to the vendor directly.
