### ISSUE TITLE
Add `RangeEnum` trait

### ISSUE THREAD

**Issue by orenbenkiki** [rust-lang/rust#10418]
Following the last few comments on #4926.

Add a `RangeEnum` trait for simple Enums (which implement `FromPrimitive`) to allow quick access to the total number of values, and provide an iterator over the values.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#824
