### ISSUE TITLE
Unify test code in bootstrap

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#104198]
Right now, we copy paste a bunch of code in various places and it ends up with not all test suites supporting the same arguments. See for example https://github.com/rust-lang/rust/issues/66458. We should refactor all these Steps to use the same logic for the flags to pass to cargo.

https://github.com/rust-lang/rust/blob/131ef9580815329aa3647fa84d7c74769fefbccf/src/bootstrap/test.rs#L2448-L2464 is an example of code that's repeated nearly verbatim 5+ times in test.rs. It would be nice to have a `fn test_args(cargo: &mut Cargo) {}` that we call instead of trying to keep these in sync.

_Originally posted by @jyn514 in https://github.com/rust-lang/rust/issues/72536#issuecomment-1308932797_

**Comment by pratushrai0309** [comment]
@jyn514 Can I work on this issue?

**Comment by jyn514** [comment]
Sure :)

**Comment by jyn514** [comment]
@pratushrai0309 no, sorry, I don't have more time available to work on this issue. If you have specific questions about the things I wrote in the issue description I can answer those.

**Comment by pratushrai0309** [comment]
@jyn514 So we just have to create a function test_args with the code you have linked in the comment right??

**Comment by Ezrashaw** [comment]
Not sure if @pratushrai0309 is still working on this, I'll also do some work here

@rustbot claim
