### ISSUE TITLE
`let _ = raii;` doesn't move variable

### ISSUE THREAD

**Issue by BratSinot** [rust-lang/rust#104103]
I tried this code:

```rust
struct RAII<F: FnOnce()> {
    drop_fun: Option<F>,
}

impl<F: FnOnce()> Drop for RAII<F> {
    fn drop(&mut self) {
        println!("drop: {:?}", self.drop_fun.is_some());
        if let Some(drop_fun) = self.drop_fun.take() {
            drop_fun();
        }
    }
}

fn spawn() {
    println!("0");

    let raii = RAII {
        drop_fun: Some(|| println!("drop_fun")),
    };

    println!("1");
    std::thread::spawn(move || {
        println!("2");
        //let _raii = raii;
        let _ = raii;
        println!("3");
    });

    println!("4");
}

fn main() {
    spawn();

    std::thread::sleep(std::time::Duration::from_secs(1));

    println!("5");
}
```

and it doesn't move variable as expected:
```log
0
1
4
drop: true
drop_fun
2
3
5
```

But if I write like this:
```rust
    println!("1");
    std::thread::spawn(move || {
        println!("2");
        let _raii = raii;
```
everything is work as expected:
```log
0
1
4
2
3
drop: true
drop_fun
5
```

### Meta
`rustc --version --verbose`:
```
rustc --version --verbose
rustc 1.65.0 (897e37553 2022-11-02)
binary: rustc
commit-hash: 897e37553bba8b42751c67658967889d11ecd120
commit-date: 2022-11-02
host: x86_64-apple-darwin
release: 1.65.0
LLVM version: 15.0.0
```

**Comment by ehuss** [comment]
Thanks for the report!  This is intended behavior, new to the 2021 edition of Rust called disjoint closure captures. You can read more about it in the [Edition Guide](https://doc.rust-lang.org/nightly/edition-guide/rust-2021/disjoint-capture-in-closures.html#wild-card-patterns) or this [unfinished docs](https://github.com/rust-lang/reference/blob/44f6e1e20f40dddf1b5e9aa002d5cd6e7a629663/src/types/closure.md#wild-card-patterns). Closures will only capture things that are "used", and `let _` is not considered as using the value.
