### ISSUE TITLE
Unfortunate type bound on Range

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#10414]
Range has a type bound on ToPrimitive so that it can have a size_hint. It does not need this to function, and the size_hint is just an optional nicety.

It'd be nice if there were some way to express this with the type system; this "optional" type bound makes the interface less generic (though it's not that big of a deal).

**Comment by steveklabnik** [comment]
Ranges have changed a bunch, and I can't seem to find an implementation of `ToPrimitive` on anything but primitives anymore: http://doc.rust-lang.org/nightly/std/num/trait.ToPrimitive.html

Is this issue still relevant?

**Comment by Gankro** [comment]
The (old) iter::Range is on its way out, so I think this is fine to kill.
