### ISSUE TITLE
Add 'lifetime' and 'type parameter list' fragment specifiers to macro parser.

### ISSUE THREAD

**Issue by brendanzab** [rust-lang/rust#10413]
This would make manipulating type parameter lists much easier.

**Comment by kmcallister** [comment]
Sigh, I guess this is another problem with using the not-actually-delimiters `<` and `>` for type parameters.  If they were real delimiters you could do

    `(< $($x:tt)* >) => ...`

but this will (I think) try to consume the terminating `>` as another `$x:tt` match.

There is probably a way to fix that with a recursive macro that eats one `tt` at a time, and checks for `>` first, but bleh.

**Comment by steveklabnik** [comment]
triage: not aware of any change here.

**Comment by Mark-Simulacrum** [comment]
This is now only tracking the type parameter fragments, which would definitely need an RFC. Lifetimes in macros are tracked here: https://github.com/rust-lang/rust/issues/10413. I'm going to close this since there's nothing left to be tracked in the rust-lang/rust repo for this issue.
