### ISSUE TITLE
1.65.0 fails to build on powerpc

### ISSUE THREAD

**Issue by pkubaj** [rust-lang/rust#104220]
1.64.0 built fine.
On powerpc-unknown-freebsd:
```
  = note: /usr/local/bin/ld.bfd: /wrkdirs/usr/ports/lang/rust/work/_build/powerpc-unknown-freebsd/stage0-rustc/powerpc-unknown-freebsd/release/deps/librustc_driver-95f1e4ba1a525000.so: undefined reference to `__atomic_load_8'
          /usr/local/bin/ld.bfd: /wrkdirs/usr/ports/lang/rust/work/_build/powerpc-unknown-freebsd/stage0-rustc/powerpc-unknown-freebsd/release/deps/librustc_driver-95f1e4ba1a525000.so: undefined reference to `__atomic_store_8'
          cc: error: linker command failed with exit code 1 (use -v to see invocation)
```

Probably related to LLVM upgrade.

**Comment by apiraino** [comment]
probably related to https://github.com/rust-lang/rust/issues/103949 (different compile target but seemingly same symptoms).

Assigning same priority for the time being ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23104220.201.2E65.2E0.20fails.20to.20build.20on.20powerpc)).

@rustbot label -I-prioritize +P-low

**Comment by nikic** [comment]
What does `llvm-config --system-libs` report? For cross-compiled builds we link libatomic here: https://github.com/rust-lang/rust/blob/b7b7f2716ee1655a696d3d64c3e12638d0dd19c0/compiler/rustc_llvm/build.rs#L248 But I assume you're using a native build?

**Comment by pkubaj** [comment]
```
root@powerpc-131-rust:/wrkdirs/usr/ports/lang/rust/work/_build/powerpc-unknown-freebsd/llvm/build/bin # ./llvm-config --system-libs
-lrt -lexecinfo -lpthread -lm -lz
```
FreeBSD doesn't have libatomic. LLVM is used in the base system, libatomic is GCC's component.

**Comment by pkubaj** [comment]
And yes, I build natively.

**Comment by nikic** [comment]
> FreeBSD doesn't have libatomic. LLVM is used in the base system, libatomic is GCC's component.

If FreeBSD doesn't have libatomic, what library provides atomic libcalls instead? I found https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=230888 which makes it sound like these are supposed to be provided by compiler-rt (which is super suspicious, because `__atomic` builtins must be provided by a shared object with a globally shared mutex, not a static library).

In any case, this sounds like an issue in FreeBSD, not something that can/should be addressed on the Rust/LLVM side.

**Comment by pkubaj** [comment]
Yes, compiler_rt is used. Is it possible to disable generating those atomic calls?

**Comment by pkubaj** [comment]
I succeeded to build after installing gcc, adding appriopriate -L flag to RUSTFLAGS and modifying [compiler/rustc_llvm/build.rs](https://github.com/rust-lang/rust/blob/b7b7f2716ee1655a696d3d64c3e12638d0dd19c0/compiler/rustc_llvm/build.rs#L248) to always add -latomic and -lz (that was also necessary) on powerpc (not just for crosscompiling).

**Comment by apiraino** [comment]
@pkubaj do you consider this issue as resolved? If yes, can you close it? I underatand you had to manually patch `rustc` to compile the target. Do you think that your patch would be useful for a PR upstream in rustc? 

thanks @nikic for the support
