### ISSUE TITLE
 rustc 1.67.0-nightly build core dump

### ISSUE THREAD

**Issue by luyikk** [rust-lang/rust#104238]
### Code

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.67.0-nightly (e75aab045 2022-11-09) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `for<'a, 'b, 'c, 'd, 'e, 'f, 'g, 'h, 'i, 'j, 'k> {core::future::ResumeTy, &'a actor_service::money_service::MoneyService, i32, &'b str, f64, &'c aqueue::actor::Actor<d
b::Databases>, static_def::DATABASE, &'d str, core::pin::Pin<alloc::boxed::Box<(dyn core::future::future::Future<Output = core::result::Result<core::option::Option<db::tables::table_account_money::account_money>, anyhow::Error>> +
 core::marker::Send + 'e)>>, core::pin::Pin<alloc::boxed::Box<(dyn core::future::future::Future<Output = core::result::Result<core::option::Option<db::tables::table_account_money::account_money>, anyhow::Error>> + core::marker::Se
nd + 'f)>>, (), core::result::Result<core::option::Option<db::tables::table_account_money::account_money>, anyhow::Error>, core::ops::control_flow::ControlFlow<core::result::Result<core::convert::Infallible, anyhow::Error>, core::
option::Option<db::tables::table_account_money::account_money>>, core::option::Option<db::tables::table_account_money::account_money>, db::tables::table_account_money::account_money, bool, &'g str, db::StoreMoney, core::pin::Pin<a
lloc::boxed::Box<(dyn core::future::future::Future<Output = core::result::Result<bool, anyhow::Error>> + core::marker::Send + 'h)>>, core::pin::Pin<alloc::boxed::Box<(dyn core::future::future::Future<Output = core::result::Result<bool, anyhow::Error>> + core::marker::Send + 'i)>>, &'j str, core::pin::Pin<alloc::boxed::Box<(dyn core::future::future::Future<Output = core::result::Result<bool, anyhow::Error>> + core::marker::Send + 'k)>>}: core::marker::Send`
#1 [typeck] type-checking `actor_service::money_service::<impl at src\actor_service\money_service.rs:698:1: 698:43>::change_money_gift_safe`
#2 [typeck_item_bodies] type-checking all item bodies
#3 [analysis] running analysis passes on this crate
end of query stack
thread 'rustc' panicked at 'forcing query with already existing `DepNode`                                                                                                                                                            
- query-key: Canonical { max_universe: U0, variables: [CanonicalVarInfo { kind: Region(U0) }, CanonicalVarInfo { kind: Region(U0) }, CanonicalVarInfo { kind: Region(U0) }], value: ParamEnvAnd { param_env: ParamEnv { caller_bounds:
 [Binder(OutlivesPredicate(ReLateBound(DebruijnIndex(1), BoundRegion { var: 0, kind: BrAnon(0, None) }), ReLateBound(DebruijnIndex(1), BoundRegion { var: 1, kind: BrAnon(1, None) })), []), Binder(OutlivesPredicate(ReLateBound(Debr
uijnIndex(1), BoundRegion { var: 2, kind: BrAnon(2, None) }), ReLateBound(DebruijnIndex(1), BoundRegion { var: 1, kind: BrAnon(1, None) })), []), Binder(OutlivesPredicate(aqueue::Actor<actor_service::money_service::MoneyService>, 
ReLateBound(DebruijnIndex(1), BoundRegion { var: 1, kind: BrAnon(1, None) })), [])], reveal: UserFacing, constness: NotConst }, value: Binder(TraitPredicate(<for<'a, 'b, 'c, 'd, 'e, 'f, 'g, 'h, 'i> {std::future::ResumeTy, &'a acto
r_service::money_service::MoneyService, i32, &'b str, &'c aqueue::Actor<db::Databases>, static_def::DATABASE, &'d str, std::pin::Pin<std::boxed::Box<(dyn std::future::Future<Output = std::result::Result<std::option::Option<i32>, a
nyhow::Error>> + std::marker::Send + 'e)>>, std::pin::Pin<std::boxed::Box<(dyn std::future::Future<Output = std::result::Result<std::option::Option<i32>, anyhow::Error>> + std::marker::Send + 'f)>>, (), bool, &'g str, std::pin::Pi
n<std::boxed::Box<(dyn std::future::Future<Output = std::result::Result<bool, anyhow::Error>> + std::marker::Send + 'h)>>, std::pin::Pin<std::boxed::Box<(dyn std::future::Future<Output = std::result::Result<bool, anyhow::Error>> + std::marker::Send + 'i)>>} as std::marker::Send>, polarity:Positive), []) } }
- dep-node: evaluate_obligation(1abef27f9e526b90-dc8b076abe19faf0)', /rustc/e75aab045fc476f176a58c408f6b06f0e275c6e1\compiler\rustc_query_system\src\dep_graph\graph.rs:316:9
stack backtrace:
   0:     0x7ff9e5619a42 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h492e180cd0edfa21
   1:     0x7ff9e565556b - core::fmt::write::h73bbbc93f82a9a90
   2:     0x7ff9e560c03a - <std::io::IoSlice as core::fmt::Debug>::fmt::hf363c3d500eef44b
   3:     0x7ff9e561978b - std::sys::common::alloc::realloc_fallback::ha931d80a9f1e2aeb
   4:     0x7ff9e561d0b9 - std::panicking::default_hook::h1885eb7e3c663856
   5:     0x7ff9e561cd3a - std::panicking::default_hook::h1885eb7e3c663856
   6:     0x7ff9e841a93b - rustc_driver[643a83b6c7033cdb]::describe_lints
   7:     0x7ff9e561da10 - std::panicking::rust_panic_with_hook::hfc62700855c05cab
   8:     0x7ff9e561d76d - <std::panicking::begin_panic_handler::StrPanicPayload as core::panic::BoxMeUp>::get::h55caf3990a134d8d
   9:     0x7ff9e561a74f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h492e180cd0edfa21
  10:     0x7ff9e561d430 - rust_begin_unwind
  11:     0x7ff9e568b4a5 - core::panicking::panic_fmt::h50242fef82f42242
  12:     0x7ff9e7d89e43 - <rustc_span[e822629c24459846]::def_id::DefId as rustc_serialize[26fb87643a653617]::serialize::Encodable<rustc_query_impl[4bd925c7e6f8a6b5]::on_disk_cache::CacheEncoder>>::encode
  13:     0x7ff9e7e36611 - <rustc_span[e822629c24459846]::def_id::DefId as rustc_serialize[26fb87643a653617]::serialize::Encodable<rustc_query_impl[4bd925c7e6f8a6b5]::on_disk_cache::CacheEncoder>>::encode
  14:     0x7ff9e7cf6d26 - <rustc_query_impl[4bd925c7e6f8a6b5]::Queries as rustc_middle[70ebb0efaeb7f97d]::ty::query::QueryEngine>::as_any
  15:     0x7ff9e81779c5 - <rustc_trait_selection[4232c4007f6de79e]::traits::fulfill::FulfillProcessor as rustc_data_structures[7e679284a49a1e9c]::obligation_forest::ObligationProcessor>::process_obligation
  16:     0x7ff9e81a4a3c - rustc_trait_selection[4232c4007f6de79e]::traits::project::normalize_projection_type
  17:     0x7ff9e8173ab2 - <rustc_trait_selection[4232c4007f6de79e]::traits::fulfill::FulfillmentContext as rustc_infer[4837189ade221608]::traits::engine::TraitEngine>::select_all_or_error
  18:     0x7ff9e75f5aa9 - <rustc_hir_typeck[aaefa5d142e23f85]::inherited::Inherited>::build
  19:     0x7ff9e7537c4d - <rustc_hir_typeck[aaefa5d142e23f85]::UnsafetyState>::recurse
  20:     0x7ff9e6613c58 - <rustc_const_eval[fa571badc7d0578d]::transform::check_consts::resolver::State as core[77a3798dca5521b2]::clone::Clone>::clone_from
  21:     0x7ff9e6695c45 - <&rustc_index[481d406d17e9d4f4]::vec::IndexVec<rustc_middle[70ebb0efaeb7f97d]::mir::Promoted, rustc_middle[70ebb0efaeb7f97d]::mir::Body> as rustc_serialize[26fb87643a653617]::serialize::Decodable<rustc_query_impl[4bd925c7e6f8a6b5]::on_disk_cache::CacheDecoder>>::decode
  22:     0x7ff9e7dd3be9 - <rustc_span[e822629c24459846]::def_id::DefId as rustc_serialize[26fb87643a653617]::serialize::Encodable<rustc_query_impl[4bd925c7e6f8a6b5]::on_disk_cache::CacheEncoder>>::encode
  23:     0x7ff9e7cf1ff8 - <rustc_query_impl[4bd925c7e6f8a6b5]::Queries as rustc_middle[70ebb0efaeb7f97d]::ty::query::QueryEngine>::as_any
  24:     0x7ff9e753a345 - <rustc_hir_typeck[aaefa5d142e23f85]::UnsafetyState>::recurse
  25:     0x7ff9e6314491 - <rustc_hir_typeck[aaefa5d142e23f85]::cast::CastCheck>::do_check
  26:     0x7ff9e6615a1e - <rustc_const_eval[fa571badc7d0578d]::transform::check_consts::resolver::State as core[77a3798dca5521b2]::clone::Clone>::clone_from
  27:     0x7ff9e66b975f - <&rustc_index[481d406d17e9d4f4]::vec::IndexVec<rustc_middle[70ebb0efaeb7f97d]::mir::Promoted, rustc_middle[70ebb0efaeb7f97d]::mir::Body> as rustc_serialize[26fb87643a653617]::serialize::Decodable<rustc_query_impl[4bd925c7e6f8a6b5]::on_disk_cache::CacheDecoder>>::decode
  28:     0x7ff9e679c689 - <&rustc_index[481d406d17e9d4f4]::vec::IndexVec<rustc_middle[70ebb0efaeb7f97d]::mir::Promoted, rustc_middle[70ebb0efaeb7f97d]::mir::Body> as rustc_serialize[26fb87643a653617]::serialize::Decodable<rustc_query_impl[4bd925c7e6f8a6b5]::on_disk_cache::CacheDecoder>>::decode
  29:     0x7ff9e67d3242 - <&rustc_index[481d406d17e9d4f4]::vec::IndexVec<rustc_middle[70ebb0efaeb7f97d]::mir::Promoted, rustc_middle[70ebb0efaeb7f97d]::mir::Body> as rustc_serialize[26fb87643a653617]::serialize::Decodable<rustc_query_impl[4bd925c7e6f8a6b5]::on_disk_cache::CacheDecoder>>::decode
  30:     0x7ff9e63c330a - <rustc_hir_analysis[6a1081370415fbfc]::constrained_generic_params::ParameterCollector as rustc_middle[70ebb0efaeb7f97d]::ty::visit::TypeVisitor>::visit_const
  31:     0x7ff9e636a0b3 - rustc_hir_analysis[6a1081370415fbfc]::check_crate
  32:     0x7ff9e5c52425 - rustc_interface[3a664b69b8d11fd6]::passes::analysis
  33:     0x7ff9e661550e - <rustc_const_eval[fa571badc7d0578d]::transform::check_consts::resolver::State as core[77a3798dca5521b2]::clone::Clone>::clone_from
  34:     0x7ff9e66b4009 - <&rustc_index[481d406d17e9d4f4]::vec::IndexVec<rustc_middle[70ebb0efaeb7f97d]::mir::Promoted, rustc_middle[70ebb0efaeb7f97d]::mir::Body> as rustc_serialize[26fb87643a653617]::serialize::Decodable<rustc_query_impl[4bd925c7e6f8a6b5]::on_disk_cache::CacheDecoder>>::decode
  35:     0x7ff9e678b62e - <&rustc_index[481d406d17e9d4f4]::vec::IndexVec<rustc_middle[70ebb0efaeb7f97d]::mir::Promoted, rustc_middle[70ebb0efaeb7f97d]::mir::Body> as rustc_serialize[26fb87643a653617]::serialize::Decodable<rustc_query_impl[4bd925c7e6f8a6b5]::on_disk_cache::CacheDecoder>>::decode
  36:     0x7ff9e67daf96 - <&rustc_index[481d406d17e9d4f4]::vec::IndexVec<rustc_middle[70ebb0efaeb7f97d]::mir::Promoted, rustc_middle[70ebb0efaeb7f97d]::mir::Body> as rustc_serialize[26fb87643a653617]::serialize::Decodable<rustc_query_impl[4bd925c7e6f8a6b5]::on_disk_cache::CacheDecoder>>::decode
  37:     0x7ff9e5bfbd54 - <unknown>
  38:     0x7ff9e5c0c288 - rustc_driver[643a83b6c7033cdb]::args::arg_expand_all
  39:     0x7ff9e5c280fa - <rustc_middle[70ebb0efaeb7f97d]::ty::SymbolName as core[77a3798dca5521b2]::fmt::Debug>::fmt
  40:     0x7ff9e5c0b6bd - rustc_driver[643a83b6c7033cdb]::args::arg_expand_all
  41:     0x7ff9e5bfc819 - <unknown>
  42:     0x7ff9e5bf39b0 - <unknown>
  43:     0x7ff9e562f60c - std::sys::windows::thread::Thread::new::h0c3062413e94d0e9
  44:     0x7ffad97e244d - BaseThreadInitThunk
  45:     0x7ffadaaadfb8 - RtlUserThreadStart

error: internal compiler error: unexpected panic

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by ncitron** [comment]
I think I am running into a similar error. Here is the output I get:

I am compiling [a16z/helios](https://github.com/a16z/helios) on 1.67.0-nightly 2022-11-09. It was compiling fine in a previous nightly though.

```
thread 'rustc' panicked at 'forcing query with already existing `DepNode`
- query-key: Canonical { max_universe: U0, variables: [CanonicalVarInfo { kind: Region(U0) }, CanonicalVarInfo { kind: Region(U0) }], value: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [Binder(OutlivesPredicate(ReLateBound(DebruijnIndex(1), BoundRegion { var: 0, kind: BrAnon(0, None) }), ReLateBound(DebruijnIndex(1), BoundRegion { var: 1, kind: BrAnon(1, None) })), []), Binder(OutlivesPredicate(rpc::RpcInner, ReLateBound(DebruijnIndex(1), BoundRegion { var: 1, kind: BrAnon(1, None) })), [])], reveal: UserFacing, constness: NotConst }, value: Binder(TraitPredicate(<for<'a, 'b, 'c, 'd, 'e, 'f, 'g, 'h, 'i> {std::future::ResumeTy, &'a mut execution::evm::Evm<'b, execution::rpc::http_rpc::HttpRpc>, &'c execution::types::CallOpts, &'d execution::evm::Evm<'e, execution::rpc::http_rpc::HttpRpc>, impl std::future::Future<Output = std::result::Result<std::collections::HashMap<ethers::types::H160, execution::types::Account>, eyre::Report>>, ()} as std::marker::Send>, polarity:Positive), []) } }
- dep-node: evaluate_obligation(c80e31313afcdf4e-b109970fd42acb65)', /rustc/e75aab045fc476f176a58c408f6b06f0e275c6e1/compiler/rustc_query_system/src/dep_graph/graph.rs:316:9
stack backtrace:
   0:        0x105583310 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h94a32d2f9df83178
   1:        0x1055d46bc - core::fmt::write::h9f5342444fd8ff58
   2:        0x105575f20 - std::io::Write::write_fmt::hb0abf9658f6faa60
   3:        0x105583124 - std::sys_common::backtrace::print::had44b9c680b6d498
   4:        0x105585c78 - std::panicking::default_hook::{{closure}}::h50772a0256597d2c
   5:        0x1055859d0 - std::panicking::default_hook::h14f34a205c20288c
   6:        0x10d548490 - rustc_driver[970d1b2305f31fad]::DEFAULT_HOOK::{closure#0}::{closure#0}
   7:        0x105586388 - std::panicking::rust_panic_with_hook::h74e81e9ec7ee4ca0
   8:        0x105586170 - std::panicking::begin_panic_handler::{{closure}}::hfd9759c0095752c7
   9:        0x105583778 - std::sys_common::backtrace::__rust_end_short_backtrace::he9f27248db30b051
  10:        0x105585ec4 - _rust_begin_unwind
  11:        0x105600138 - core::panicking::panic_fmt::h9456ac90605e5edc
  12:        0x110756e04 - <rustc_query_system[53830fb5bdfa6709]::dep_graph::graph::DepGraph<rustc_middle[6a8605ce0199088a]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[6a8605ce0199088a]::ty::context::TyCtxt, rustc_middle[6a8605ce0199088a]::infer::canonical::Canonical<rustc_middle[6a8605ce0199088a]::ty::ParamEnvAnd<rustc_middle[6a8605ce0199088a]::ty::Predicate>>, core[82e619e1fd4d40bd]::result::Result<rustc_middle[6a8605ce0199088a]::traits::select::EvaluationResult, rustc_middle[6a8605ce0199088a]::traits::select::OverflowError>>
  13:        0x1104dfa9c - rustc_query_system[53830fb5bdfa6709]::query::plumbing::try_execute_query::<rustc_query_impl[23b3ae9f73b01ca2]::plumbing::QueryCtxt, rustc_query_system[53830fb5bdfa6709]::query::caches::DefaultCache<rustc_middle[6a8605ce0199088a]::infer::canonical::Canonical<rustc_middle[6a8605ce0199088a]::ty::ParamEnvAnd<rustc_middle[6a8605ce0199088a]::ty::Predicate>>, core[82e619e1fd4d40bd]::result::Result<rustc_middle[6a8605ce0199088a]::traits::select::EvaluationResult, rustc_middle[6a8605ce0199088a]::traits::select::OverflowError>>>
  14:        0x1105b1550 - rustc_query_system[53830fb5bdfa6709]::query::plumbing::get_query::<rustc_query_impl[23b3ae9f73b01ca2]::queries::evaluate_obligation, rustc_query_impl[23b3ae9f73b01ca2]::plumbing::QueryCtxt>
  15:        0x110657584 - <rustc_query_impl[23b3ae9f73b01ca2]::Queries as rustc_middle[6a8605ce0199088a]::ty::query::QueryEngine>::evaluate_obligation
  16:        0x110ff0a8c - <rustc_infer[75226c4d80a577ee]::infer::InferCtxt as rustc_trait_selection[e472d6aeb29857d0]::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation
  17:        0x110ff0b74 - <rustc_infer[75226c4d80a577ee]::infer::InferCtxt as rustc_trait_selection[e472d6aeb29857d0]::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation_no_overflow
  18:        0x111035504 - <rustc_trait_selection[e472d6aeb29857d0]::traits::fulfill::FulfillProcessor>::process_trait_obligation
  19:        0x111034f58 - <rustc_trait_selection[e472d6aeb29857d0]::traits::fulfill::FulfillProcessor as rustc_data_structures[615ae6fb4c7de313]::obligation_forest::ObligationProcessor>::process_obligation
  20:        0x110fd24b4 - <rustc_data_structures[615ae6fb4c7de313]::obligation_forest::ObligationForest<rustc_trait_selection[e472d6aeb29857d0]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[e472d6aeb29857d0]::traits::fulfill::FulfillProcessor>
  21:        0x111031b30 - <rustc_trait_selection[e472d6aeb29857d0]::traits::fulfill::FulfillmentContext as rustc_infer[75226c4d80a577ee]::traits::engine::TraitEngine>::select_where_possible
  22:        0x111031a10 - <rustc_trait_selection[e472d6aeb29857d0]::traits::fulfill::FulfillmentContext as rustc_infer[75226c4d80a577ee]::traits::engine::TraitEngine>::select_all_or_error
  23:        0x10f821418 - <rustc_hir_typeck[a90a02a83d84670e]::fn_ctxt::FnCtxt>::select_all_obligations_or_error
  24:        0x10f8d4d90 - <rustc_hir_typeck[a90a02a83d84670e]::inherited::InheritedBuilder>::enter::<rustc_hir_typeck[a90a02a83d84670e]::typeck_with_fallback<rustc_hir_typeck[a90a02a83d84670e]::typeck::{closure#0}>::{closure#0}::{closure#1}, &rustc_middle[6a8605ce0199088a]::ty::context::TypeckResults>
  25:        0x10f881d24 - rustc_hir_typeck[a90a02a83d84670e]::typeck
  26:        0x110762990 - <rustc_query_system[53830fb5bdfa6709]::dep_graph::graph::DepGraph<rustc_middle[6a8605ce0199088a]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[6a8605ce0199088a]::ty::context::TyCtxt, rustc_span[6b418e3a28ee804]::def_id::LocalDefId, &rustc_middle[6a8605ce0199088a]::ty::context::TypeckResults>
  27:        0x1104fb6f0 - rustc_query_system[53830fb5bdfa6709]::query::plumbing::try_execute_query::<rustc_query_impl[23b3ae9f73b01ca2]::plumbing::QueryCtxt, rustc_query_system[53830fb5bdfa6709]::query::caches::DefaultCache<rustc_span[6b418e3a28ee804]::def_id::LocalDefId, &rustc_middle[6a8605ce0199088a]::ty::context::TypeckResults>>
  28:        0x1105c0e00 - rustc_query_system[53830fb5bdfa6709]::query::plumbing::get_query::<rustc_query_impl[23b3ae9f73b01ca2]::queries::typeck, rustc_query_impl[23b3ae9f73b01ca2]::plumbing::QueryCtxt>
  29:        0x10f8f5a24 - std[1459eb82d77d7262]::panicking::try::<(), core[82e619e1fd4d40bd]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[615ae6fb4c7de313]::sync::par_for_each_in<&[rustc_span[6b418e3a28ee804]::def_id::LocalDefId], <rustc_middle[6a8605ce0199088a]::hir::map::Map>::par_body_owners<rustc_hir_typeck[a90a02a83d84670e]::typeck_item_bodies::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>>
  30:        0x10f8f5b30 - rustc_data_structures[615ae6fb4c7de313]::sync::par_for_each_in::<&[rustc_span[6b418e3a28ee804]::def_id::LocalDefId], <rustc_middle[6a8605ce0199088a]::hir::map::Map>::par_body_owners<rustc_hir_typeck[a90a02a83d84670e]::typeck_item_bodies::{closure#0}>::{closure#0}>
  31:        0x10f881610 - rustc_hir_typeck[a90a02a83d84670e]::typeck_item_bodies
  32:        0x110791710 - <rustc_query_system[53830fb5bdfa6709]::dep_graph::graph::DepGraph<rustc_middle[6a8605ce0199088a]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[6a8605ce0199088a]::ty::context::TyCtxt, (), ()>
  33:        0x110563308 - rustc_query_system[53830fb5bdfa6709]::query::plumbing::try_execute_query::<rustc_query_impl[23b3ae9f73b01ca2]::plumbing::QueryCtxt, rustc_query_system[53830fb5bdfa6709]::query::caches::DefaultCache<(), ()>>
  34:        0x1105b0aa8 - rustc_query_system[53830fb5bdfa6709]::query::plumbing::get_query::<rustc_query_impl[23b3ae9f73b01ca2]::queries::typeck_item_bodies, rustc_query_impl[23b3ae9f73b01ca2]::plumbing::QueryCtxt>
  35:        0x10f9cb3f4 - <rustc_session[675766ca17b654ef]::session::Session>::time::<(), rustc_hir_analysis[5c80beef5d559c84]::check_crate::{closure#7}>
  36:        0x10f9818bc - rustc_hir_analysis[5c80beef5d559c84]::check_crate
  37:        0x10d5edfec - rustc_interface[c31f56b2d821f285]::passes::analysis
  38:        0x110788c8c - <rustc_query_system[53830fb5bdfa6709]::dep_graph::graph::DepGraph<rustc_middle[6a8605ce0199088a]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[6a8605ce0199088a]::ty::context::TyCtxt, (), core[82e619e1fd4d40bd]::result::Result<(), rustc_errors[18f82b42c898d543]::ErrorGuaranteed>>
  39:        0x110557e68 - rustc_query_system[53830fb5bdfa6709]::query::plumbing::try_execute_query::<rustc_query_impl[23b3ae9f73b01ca2]::plumbing::QueryCtxt, rustc_query_system[53830fb5bdfa6709]::query::caches::DefaultCache<(), core[82e619e1fd4d40bd]::result::Result<(), rustc_errors[18f82b42c898d543]::ErrorGuaranteed>>>
  40:        0x1105c120c - rustc_query_system[53830fb5bdfa6709]::query::plumbing::get_query::<rustc_query_impl[23b3ae9f73b01ca2]::queries::analysis, rustc_query_impl[23b3ae9f73b01ca2]::plumbing::QueryCtxt>
  41:        0x10d4e4bd8 - <rustc_interface[c31f56b2d821f285]::passes::QueryContext>::enter::<rustc_driver[970d1b2305f31fad]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[82e619e1fd4d40bd]::result::Result<(), rustc_errors[18f82b42c898d543]::ErrorGuaranteed>>
  42:        0x10d5212e8 - rustc_span[6b418e3a28ee804]::with_source_map::<core[82e619e1fd4d40bd]::result::Result<(), rustc_errors[18f82b42c898d543]::ErrorGuaranteed>, rustc_interface[c31f56b2d821f285]::interface::run_compiler<core[82e619e1fd4d40bd]::result::Result<(), rustc_errors[18f82b42c898d543]::ErrorGuaranteed>, rustc_driver[970d1b2305f31fad]::run_compiler::{closure#1}>::{closure#0}::{closure#1}>
  43:        0x10d51368c - <scoped_tls[d18693b2718c320b]::ScopedKey<rustc_span[6b418e3a28ee804]::SessionGlobals>>::set::<rustc_interface[c31f56b2d821f285]::interface::run_compiler<core[82e619e1fd4d40bd]::result::Result<(), rustc_errors[18f82b42c898d543]::ErrorGuaranteed>, rustc_driver[970d1b2305f31fad]::run_compiler::{closure#1}>::{closure#0}, core[82e619e1fd4d40bd]::result::Result<(), rustc_errors[18f82b42c898d543]::ErrorGuaranteed>>
  44:        0x10d4e7550 - std[1459eb82d77d7262]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[c31f56b2d821f285]::util::run_in_thread_pool_with_globals<rustc_interface[c31f56b2d821f285]::interface::run_compiler<core[82e619e1fd4d40bd]::result::Result<(), rustc_errors[18f82b42c898d543]::ErrorGuaranteed>, rustc_driver[970d1b2305f31fad]::run_compiler::{closure#1}>::{closure#0}, core[82e619e1fd4d40bd]::result::Result<(), rustc_errors[18f82b42c898d543]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[82e619e1fd4d40bd]::result::Result<(), rustc_errors[18f82b42c898d543]::ErrorGuaranteed>>
  45:        0x10d4d1538 - <<std[1459eb82d77d7262]::thread::Builder>::spawn_unchecked_<rustc_interface[c31f56b2d821f285]::util::run_in_thread_pool_with_globals<rustc_interface[c31f56b2d821f285]::interface::run_compiler<core[82e619e1fd4d40bd]::result::Result<(), rustc_errors[18f82b42c898d543]::ErrorGuaranteed>, rustc_driver[970d1b2305f31fad]::run_compiler::{closure#1}>::{closure#0}, core[82e619e1fd4d40bd]::result::Result<(), rustc_errors[18f82b42c898d543]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[82e619e1fd4d40bd]::result::Result<(), rustc_errors[18f82b42c898d543]::ErrorGuaranteed>>::{closure#1} as core[82e619e1fd4d40bd]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  46:        0x10558e3d4 - std::sys::unix::thread::Thread::new::thread_start::h1c80d77ca41832e9
  47:        0x180a5826c - __pthread_deallocate

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.67.0-nightly (e75aab045 2022-11-09) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `for<'a, 'b, 'c, 'd, 'e, 'f, 'g, 'h, 'i> {core::future::ResumeTy, &'a mut execution::evm::Evm<'b, execution::rpc::http_rpc::HttpRpc>, &'c execution::types::CallOpts, &'d execution::evm::Evm<'e, execution::rpc::http_rpc::HttpRpc>, impl core::future::future::Future<Output = core::result::Result<std::collections::hash::map::HashMap<primitive_types::H160, execution::types::Account>, eyre::Report>>, ()}: core::marker::Send`
#1 [typeck] type-checking `rpc::<impl at client/src/rpc.rs:110:1: 110:31>::estimate_gas`
#2 [typeck_item_bodies] type-checking all item bodies
#3 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `client`
```

**Comment by compiler-errors** [comment]
I'm taking a look at this.

**Comment by compiler-errors** [comment]
This is due to #103171 -- coming up with a fix.

**Comment by Xuanwo** [comment]
> This is due to #103171 -- coming up with a fix.

Hero of the day!
