### ISSUE TITLE
inline_const cannot be feature-gated

### ISSUE THREAD

**Issue by Nugine** [rust-lang/rust#104268]
I tried this code:

```rust
#[cfg(feature = "unstable")]
pub fn foo() {
    const { 1 + 1 };
}
```

I expected to see this happen: It compiles when the feature flag *unstable* is disabled.

Instead, this happened: 

```
   Compiling playground v0.0.1 (/playground)
error[E0658]: inline-const is experimental
 --> src/lib.rs:3:5
  |
3 |     const { 1 + 1 };
  |     ^^^^^
  |
  = note: see issue #76001 <https://github.com/rust-lang/rust/issues/76001> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `playground` due to previous error
```

+ https://github.com/rust-lang/rust/issues/76001

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0 (897e37553 2022-11-02)
binary: rustc
commit-hash: 897e37553bba8b42751c67658967889d11ecd120
commit-date: 2022-11-02
host: x86_64-unknown-linux-gnu
release: 1.65.0
LLVM version: 15.0.0
```

```
rustc 1.67.0-nightly (85f4f41de 2022-11-08)
binary: rustc
commit-hash: 85f4f41deb1557ca8ab228319d33003dd2f20f45
commit-date: 2022-11-08
host: x86_64-unknown-linux-gnu
release: 1.67.0-nightly
LLVM version: 15.0.4
```

**Comment by JohnTitor** [comment]
You have to use `#![feature(inline_const)]` instead of `#[cfg(feature = "unstable")]` ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=5597ff68bc2328cfb5673d1e5e7731b5)).

**Comment by Nugine** [comment]
I would like to enable `inline_const` in a stable-compatible crate when the feature flag `unstable` is set. But it cannot compile when the feature flag `unstable` is not set.

https://rust.godbolt.org/z/7rchb6PM8

```rust
#![cfg_attr(feature = "unstable", feature(inline_const))]

#[cfg(feature = "unstable")]
pub fn foo() {
    const { 1 + 1 };
}
```

**Comment by JohnTitor** [comment]
You can with ` --cfg 'feature="unstable"'`: https://rust.godbolt.org/z/e8dEjj5EP

**Comment by scottmcm** [comment]
This is expected -- the compiler still has to parse the function body, so if the parsing rules change it could break your code despite the `[cfg]`.

The usual solution is to put it in a separate file, and to `#[cfg]` the `mod`, AFAIK.

**Comment by scottmcm** [comment]
And as an aside, I proposed FCP for inline const over in #104087, so hopefully you'll soon be able to stop gating it on nightly at all 🙂
