### ISSUE TITLE
Struct update syntax produces very confusing error messages when comma before .. is missed

### ISSUE THREAD

**Issue by alice-i-cecile** [rust-lang/rust#104373]
Begin with the following working code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=fb4c4c5e78cd9c3f549cdd806e68388a

Then, delete the `,` before `..Default::default()`, resulting in:

```rust
#[derive(Default)]
struct Inner {
    a: u8,
    b: u8,
}

#[derive(Default)]
struct Outer {
    inner: Inner,
    defaulted: u8,
}

fn main(){
    Outer {
        inner: Inner {
            a: 1,
            b: 2,
        }
        ..Default::default()
    };
}
```

The current output is:

```
error[[E0308]](https://doc.rust-lang.org/stable/error-index.html#E0308): mismatched types
  --> src/main.rs:15:16
   |
15 |           inner: Inner {
   |  ________________^
16 | |             a: 1,
17 | |             b: 2,
18 | |         }
19 | |         ..Default::default()
   | |____________________________^ expected struct `Inner`, found struct `std::ops::Range`
   |
   = note: expected struct `Inner`
              found struct `std::ops::Range<Inner>`

error[[E0063]](https://doc.rust-lang.org/stable/error-index.html#E0063): missing field `defaulted` in initializer of `Outer`
  --> src/main.rs:14:5
   |
14 |     Outer {
   |     ^^^^^ missing `defaulted`
   |
help: to set the remaining fields from `Default::default()`, separate the last named field with a comma
   |
18 |         },
   |          +

Some errors have detailed explanations: E0063, E0308.
For more information about an error, try `rustc --explain E0063`.
error: could not compile `playground` due to 2 previous errors```
```

Ideally the output should explain that struct update syntax requires a comma separating the last field from the `..` notation and point to that line.

Encountered in the wild in the [Bevy community](https://discord.com/channels/691052431525675048/691052431974465548/1041396922411393114), although I run into this myself regularly when initializing structs by hand.

**Comment by compiler-errors** [comment]
> Ideally the output should explain that struct update syntax requires a comma separating the last field from the .. notation and point to that line.

This is always suggested at the bottom--how do you think that message can be improved?

**Comment by alice-i-cecile** [comment]
Swapping the order or removing the first error completely would help: the latter is much more relevant and beginners often get flustered after the first incomprehensible error message.

The other problem is that you get a copy of this error message for each missing field

In terms of text, I would try something closer to:

```
error[[E0063]](https://doc.rust-lang.org/stable/error-index.html#E0063): Missing comma: to set the remaining fields of this `Outer` object using `Default::default` add a comma after the last named field before the `..`.
  --> src/main.rs:14:5
   |
14 |     Outer {
   |
   |
18 |         }
   |     ^^^ missing comma after named item
   |          ..Default::default()
   |       }
   |          +
```
The fields aren't missing: the user has clear intent to declare them, and listing out which ones are missing won't help them solve the problem (and adds a lot of noise for complex types).

**Comment by pierwill** [comment]
Hello, I have a draft PR to address this here https://github.com/rust-lang/rust/pull/103838.
