### ISSUE TITLE
`assert_eq!()` only infers the type of an `into()` invocation if it's the *second* argument

### ISSUE THREAD

**Issue by yaymukund** [rust-lang/rust#104346]
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=a722f1455f7795cc26d02023eb1a6bb7

I tried this code:

```rust
struct Foo(u64);
impl From<Foo> for u64 {
    fn from(foo: Foo) -> Self {
        foo.0
    }
}

fn main() {
    let foo = Foo(5);
    
    // this works but...
    assert_eq!(5u64, foo.into());
    // ...this doesn't work?
    assert_eq!(foo.into(), 5u64);
}
```

I expected the code to compile and run without errors.

Instead, it errors that it cannot infer the type of `into()`. It only infers the `into()` if it's the *second* argument to `assert_eq!()`.
```
Compiling playground v0.0.1 (/playground)
error[[E0282]](https://doc.rust-lang.org/nightly/error-index.html#E0282): type annotations needed
  --> src/main.rs:14:20
   |
14 |     assert_eq!(foo.into(), 5u64);
   |                    ^^^^
   |
help: try using a fully qualified path to specify the expected types
   |
14 |     assert_eq!(<Foo as Into<T>>::into(foo), 5u64);
   |                +++++++++++++++++
```

### Meta

This is from the playground linked above:
```
Build using the Nightly version: 1.67.0-nightly
(2022-11-12 6284998a2677d7e3e842)
```

I hope this isn't a dupe— I tried searching for existing issues/asking the discord help, but couldn't find anything. Thanks for reading!

**Comment by albertlarsan68** [comment]
I found https://github.com/rust-lang/rust/issues/87931, which seems to be the same issue.

**Comment by yaymukund** [comment]
Dupe of #87931
