### ISSUE TITLE
rustdoc "source" links are not clickable

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#104313]
To reproduce, navigate to https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.Ty.html and click the the "source" link for any of the methods. Nothing at all happens when I do that. I tried Firefox and Chromium.

This seems to be a fairly recent regression.

@rust-lang/rustdoc

**Comment by GuillaumeGomez** [comment]
It's because it's under the `h4` for some reason. Let's see what changed in the last few days.

**Comment by GuillaumeGomez** [comment]
I think it's because of https://github.com/rust-lang/rust/commit/303653ef65a337b21226a52546615936225fb5af. I'll try to send a fix today.

**Comment by GuillaumeGomez** [comment]
It's because `.code-header` added a `position: relative` to have a correct positioning of the tooltip on mobile devices.
