### ISSUE TITLE
no place to add evaluatable bounds to assoc const items

### ISSUE THREAD

**Issue by psionic12** [rust-lang/rust#104400]
Example:
```
trait Foo {
    const N: usize;
    const ARRAY: [i32;Self::N];
}
```
The compiler will report an error:
```
error: unconstrained generic constant
  --> src/main.rs:38:5
   |
38 |     const ARRAY: [i32;Self::N];
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: try adding a `where` bound using this expression: `where [(); Self::N]:`
```
Honestly speaking, I don't get what the suggestion means. Is it allowed to use generic_const_exprs like this? Or the only way to do this is by writing 
```
trait Foo<const N: usize> {
    const ARRAY: [i32;N];
}
```
?

**Comment by psionic12** [comment]
Hi @fmease, do you know what's the right way to write code like 
```
trait Foo {
    const N: usize;
    const ARRAY: [i32;Self::N];
}
```
? 
I don't want to use `trait Foo<const N: usize>` since it make the code complicated to understand (in my real case), though it works.

**Comment by sgodwincs** [comment]
Not sure if a new issue is warranted, but even with `generic_const_items`, this still doesn't seem to allow the following:

```
#![feature(generic_const_exprs)]
#![feature(generic_const_items)]

trait Foo {
    const COUNT: usize;
    const ARR: [u8; Self::COUNT]
    where
        [(); Self::COUNT]:;
}

impl<T: Foo> Foo for &T {
    const COUNT: usize = T::COUNT;
    const ARR: [u8; Self::COUNT] = T::ARR
    where
        [(); T::COUNT]:,
        [(); Self::COUNT]:;
}
```

See https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=4db0add3802afa5734d4a58485a1d0f2

**Comment by fmease** [comment]
The issue you are describing is #107874 (except that the where-clause is on an impl not a trait but that is irrelevant).
