### ISSUE TITLE
Option.as_ref() possible example mistake?

### ISSUE THREAD

**Issue by remdragon** [rust-lang/rust#104476]
url: https://doc.rust-lang.org/nightly/core/option/enum.Option.html

function: as_ref()

Examples:

`Converts an Option<String> into an Option<usize>, preserving the original.`

Perhaps I'm just confused, but shouldn't that say:

`Converts an Option<String> into an Option<&str>, preserving the original.`

**Comment by ehuss** [comment]
Transferring to the rust-lang/rust repository, as that is where the standard library documentation is.

I think it is trying to illustrate the conversion from `Option<String>` → `Option<&String>` → `Option<usize>`. The text is just eliding the middle step, and explaining where it is starting from and where it is finishing.

**Comment by Velocity-** [comment]
No, that seems fine; what confuses you (or leads you to the &str conclusion)? I could follow `Option<&String>` but not `Option<&str>`. Perhaps you're thinking the `Deref<Target=str>` impl on `String` would make the `Option` contain `Option<&str>`  or such?

**Comment by remdragon** [comment]
I guess I'm extremely confused then. If I have an &Option<String>, what good does an Option<usize> do me? If I have &Some( "fubar" ), how does that translate to a usize? Is it giving me the length of the string or it's pointer in memory? Neither seems useful nor relevant to the description of "Converts from &Option<T> to Option<&T>.".

**Comment by M1ngXU** [comment]
> ~length~

memory address
