### ISSUE TITLE
rustdoc regression: no entry found for key ICE

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#104448]
* https://crater-reports.s3.amazonaws.com/beta-1.66-rustdoc-1.1/beta-2022-11-01/gh/11bthornton.discord_bot_rust/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.66-rustdoc-1.1/beta-2022-11-01/gh/3tw.kanye_quote_bot/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.66-rustdoc-1.1/beta-2022-11-01/gh/5Dev24.IndeedDotCom/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.66-rustdoc-1.1/beta-2022-11-01/gh/88IO.blogpost-rs/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.66-rustdoc-1.1/beta-2022-11-01/gh/Aidan-B1409.Muji/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.66-rustdoc-1.1/beta-2022-11-01/gh/AlePon123.SoierAI/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.66-rustdoc-1.1/beta-2022-11-01/gh/AlexanderHeim.framer/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.66-rustdoc-1.1/beta-2022-11-01/gh/AlexisTM.kirby_god_rust/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.66-rustdoc-1.1/beta-2022-11-01/gh/Allen-B1.giovanni/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.66-rustdoc-1.1/beta-2022-11-01/gh/ArtieFuzzz.siren/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.66-rustdoc-1.1/beta-2022-11-01/gh/Athou.xzibot/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.66-rustdoc-1.1/beta-2022-11-01/gh/Atte.discord-bot/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.66-rustdoc-1.1/beta-2022-11-01/gh/BSpwr.discord_crypto_sidebar_ticker/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.66-rustdoc-1.1/beta-2022-11-01/gh/Basicprogrammer10.Languge-Bot/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.66-rustdoc-1.1/beta-2022-11-01/gh/Basicprogrammer10.minecraft-discord-interface/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.66-rustdoc-1.1/beta-2022-11-01/gh/Blui42.discord_rust_bot/log.txt

(and many more, probably roughly ~400 such cases)

cc @rust-lang/rustdoc

**Comment by petrochenkov** [comment]
Yeah, the whole regression list needs to be re-cratered with https://github.com/rust-lang/rust/pull/103649 and https://github.com/rust-lang/rust/pull/104364 applied.

**Comment by Mark-Simulacrum** [comment]
Those PRs need to be beta-accepted before we can backport them, but will rerun crater after backport.

**Comment by GuillaumeGomez** [comment]
The PRs were beta accepted so maybe time for a new crater run?

**Comment by Mark-Simulacrum** [comment]
Started a new run.

**Comment by Mark-Simulacrum** [comment]
Based on latest run this is fixed on beta, closing.
