### ISSUE TITLE
Unwinding intrinsics use non-unwinding ABI

### ISSUE THREAD

**Issue by tmiasko** [rust-lang/rust#104451]
There are intrinsics like `assert_inhabited`, which can unwind, but use `rust-intrinsic` ABI that never unwinds:

https://github.com/rust-lang/rust/blob/6d651a295e0e0c331153288b10b78344a4ede20b/compiler/rustc_middle/src/ty/layout.rs#L1091-L1093

An example demonstrating the issue. The argument passed to function `f` is never dropped, when `assert_inhabited` unwinds:

```rust
#![feature(core_intrinsics)]
#![feature(never_type)]

struct NoisyDrop(&'static str);

impl Drop for NoisyDrop {
    fn drop(&mut self) {
        println!("{}", self.0);
    }
}

pub fn f<A, B>(_: A) {
    core::intrinsics::assert_inhabited::<B>()
}

fn main() {
    let _a = NoisyDrop("1");
    f::<NoisyDrop, !>(NoisyDrop("2"));
}

$ rustc a.rs && ./a
thread 'main' panicked at 'attempted to instantiate uninhabited type `!`', a.rs:13:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
1
```

**Comment by nbdd0121** [comment]
I'll work on this after #102906 is merged.

@rustbot claim

**Comment by RalfJung** [comment]
Are these intrinsics the only ones that unwind? Maybe we should just make them abort instead by calling the (fairly recent) `panic_str_nounwind`.

However, AFAIK `try` is also an intrinsic and that can unwind?

**Comment by nbdd0121** [comment]
`try` catches unwind and it does not itself unwind.

**Comment by nbdd0121** [comment]
My current idea is to change `assert_inhabited` to `is_inhabited` intrinsic, and then have a wrapper that checks the value and panic if true. But making them abort sounds like an easier alternative.

**Comment by RalfJung** [comment]
It should be a nice abort via `panic_str_nounwind` though.

I am honestly not sure why the intrinsics are panicking rather than returning a boolean... I think I tried that and it didn't work? But yeah bool-returning intrinsics sound better (less magic) ayway.

**Comment by RalfJung** [comment]
One possible reason is that in CTFE and Miri, these intrinsics will actually abort instead of panic. Getting the `if ... { panic_str_nounwind }` to work in CTFE will be a bit of work (extending the existing hacks that make regular panicking work in CTFE, or using const_eval_select) and the backtrace will be slightly worse in Miri.

So given that we want something different implementations for Miri, CTFE, and runtime, maybe going with 'call `panic_str_nounwind` instead' is the better option. (An immediate-abort-panic just didn't exist when I added these intrinsics, otherwise this is probably what I would have done from the start.)

**Comment by RalfJung** [comment]
With https://github.com/rust-lang/rust/pull/105997, I think `assert_inhabited` and friends do now indeed never unwind.

But as determined in https://github.com/rust-lang/miri/issues/2839, we still have const_eval_select, which very much *can* unwind.

**Comment by nbdd0121** [comment]
Yeah, I originally thought that we can remove all unwinding intrinsics, but unfortunately that's not true. I am working on a PR to change the ABI to be unwindable and stick `#[rustc_nounwind]` to most intrinsics.
