### ISSUE TITLE
regression: parameter may not live long enough

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#104445]
* https://crater-reports.s3.amazonaws.com/beta-1.66-1.2/beta-2022-11-01/gh/OliverEvans96.payments-engine-example/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.66-1.2/beta-2022-11-01/gh/broxus.nekoton-wasm/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.66-1.2/beta-2022-11-01/gh/lukechu10.maple-trunk-gitpod-template/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.66-1.2/beta-2022-11-01/gh/sycamore-rs.sycamore-rocket-template/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.66-1.2/beta-2022-11-01/gh/sycamore-rs.sycamore-rocket/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.66-1.2/beta-2022-11-01/gh/kyrosle.webcam-live/log.txt

```
[INFO] [stdout] error[E0309]: the parameter type `T` may not live long enough
[INFO] [stdout]    --> src/validate.rs:245:13
[INFO] [stdout]     |
[INFO] [stdout] 245 |             validate_post_dispute_for_existing_tx(post, disputed_tx, accounts, disputes)
[INFO] [stdout]     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ...so that the type `T` will meet its required lifetime bounds
[INFO] [stdout]     |
[INFO] [stdout] help: consider adding an explicit lifetime bound...
[INFO] [stdout]     |
[INFO] [stdout] 228 | pub fn validate_post_dispute<'a, 't, 'd, T: PostDispute + 't>(
[INFO] [stdout]     |                                                         ++++
[INFO] [stdout] 
[INFO] [stdout] 
```

**Comment by apiraino** [comment]
I've bisected the first and last crate in the list, both point to commit  f5193a9fcc73dc09e41a90c5a2c97fc9acc16032 -> https://github.com/rust-lang/rust/pull/95474 cc @oli-obk 

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc 2022-03-01 --preserve 
```
</details>

**Comment by apiraino** [comment]
since they're regression on existing crates, let's label them as `P-critical` out of caution to signal that we want them checked before the next stable

@rustbot label -I-prioritize +P-critical

**Comment by Mark-Simulacrum** [comment]
It doesn't look like they were noted in the PR run (unless I'm missing the relevant comment). I think given the volume of breakage it likely makes sense to move ahead, but it would be great to put up PRs to these crates.

**Comment by oli-obk** [comment]
* https://crater-reports.s3.amazonaws.com/beta-1.66-1.2/beta-2022-11-01/gh/OliverEvans96.payments-engine-example/log.txt
    * already had a fix PR https://github.com/OliverEvans96/payments-engine-example/pull/1
* https://crater-reports.s3.amazonaws.com/beta-1.66-1.2/beta-2022-11-01/gh/lukechu10.maple-trunk-gitpod-template/log.txt
    * sycamore failure
* https://crater-reports.s3.amazonaws.com/beta-1.66-1.2/beta-2022-11-01/gh/sycamore-rs.sycamore-rocket-template/log.txt
    * [fix PR](https://github.com/sycamore-rs/sycamore/pull/475) already landed
* https://crater-reports.s3.amazonaws.com/beta-1.66-1.2/beta-2022-11-01/gh/sycamore-rs.sycamore-rocket/log.txt
    * sycamore failure
* https://crater-reports.s3.amazonaws.com/beta-1.66-1.2/beta-2022-11-01/gh/kyrosle.webcam-live/log.txt
    * sycamore failure

**Comment by apiraino** [comment]
ah nice, thanks @oli-obk for the additional context :)

@rustbot label -P-critical

**Comment by Mark-Simulacrum** [comment]
This is known breakage, not release blocking, and is mentioned in release notes (https://github.com/rust-lang/rust/pull/104405/files#diff-4a00447b47c36ebd3ded77321deff288e424f4605496ee1199fc9953a20f4473R77). Resolving.
