### ISSUE TITLE
Liberal implementation of `Send`/`Sync` for `AtomicPtr` 

### ISSUE THREAD

**Issue by fakedrake** [rust-lang/rust#104408]
I was surprised to find out that we have 

```rust
unsafe impl<T> Send for AtomicPtr<T>
```

instead of 

```rust
unsafe impl<T: Send + Sync> Send for AtomicPtr<T> {}
```

and that the `AtomicPtr` methods are not marked unsafe to avoid accidentally sharing `!Send` object across threads. It doesn't seem right, am I missing something?

**Comment by jyn514** [comment]
I don't think this is a bug. At most, AtomicPtr will give you back the pointer itself; you still need to use unsafe to dereference it, and at that point the obligation is on you as the author to avoid concurrent access. If you're using AtomicPtr, you're probably doing quite strange things anyway so imposing the Send + Sync restriction seems limiting.

**Comment by saethlin** [comment]
Additionally, if anyone wants to smuggle a pointer between threads, it doesn't take any `unsafe` to cast it to a `usize` which is Send and Sync then cast back to a pointer later.
