### ISSUE TITLE
Possible codegen regression when matching against nested enums

### ISSUE THREAD

**Issue by anp** [rust-lang/rust#104519]
### Code

I tried this code (reduced from a much larger test):

```rust
fn main() {
    let output = OpenResult::Ok(());
    match output {
        OpenResult::Ok(()) => (),
        _ => unreachable!("this won't be reached"),
    }
    match output {
        OpenResult::Ok(()) => (),
        _ => unreachable!("somehow matching twice is the trick"),
    }
}

enum OpenResult {
    Ok(()),

    // we don't produce either of these variants but both are necessary to trigger the issue
    #[allow(dead_code)]
    Err(()),
    #[allow(dead_code)]
    TransportErr(TransportErr),
}

#[allow(dead_code)] // don't need to produce this to repro
#[repr(i32)]
enum TransportErr {
    UnknownMethod = -2,
}
```

([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=8a7e227fc86cc3040cc1eb97918ab2f7))

I expected to see this happen: runs with 0 exit code and no output

Instead, this happened:

```
thread 'main' panicked at 'internal error: entered unreachable code: somehow matching twice is the trick', src/main.rs:9:14
```

### Version it worked on

This code works on stable and beta, and as recently as a3c0a023611fcaf5ae3ec242d7d60e356041d25f.

### Version with regression

This reproduces with the 2022-11-16 nightly on the playground. [`cargo-bisect-rustc` suggests](https://gist.github.com/anp/dbee5d6a44c20b9ecd1e706671d400cf) this was introduced by #102872.

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

**Comment by Nilstrieb** [comment]
That looks like a real miscompilation :(
cc @mikebenfield

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23104519.20Possible.20codegen.20regression.20when.20matching.20against.20n.E2.80.A6)).

@rustbot label -I-prioritize +P-high

**Comment by mikebenfield** [comment]
I've found the problem; it is indeed an issue with my code in `codegen_get_discr`. I'll have a PR with a fix some time today.

**Comment by apiraino** [comment]
Since there is some work in progress to fix this:

@rustbot assign @mikebenfield
