### ISSUE TITLE
"unconstrained const parameter" when using `generic_const_exprs`

### ISSUE THREAD

**Issue by psionic12** [rust-lang/rust#104569]
It looks to me a bug of feature `generic_const_exprs`:
```
trait Foo {
    type Ty;
}

enum Bar {
    One,
    Two(i32),
}

struct Detail<const BAR: Bar> {}

impl Foo for Detail<{ Bar::One }> {
    type Ty = ();
}

impl<const I: i32> Foo for Detail<{ Bar::Two::<{I}> }> {
    type Ty = i32;
}
```

In this case, the compiler doesn't aware that the const parameter `I` is used in side `Bar::Two::<{I}>`, and report that
```
error[E0207]: the const parameter `I` is not constrained by the impl trait, self type, or predicates
  --> src/main.rs:19:6
   |
19 | impl<const I: i32> Foo for Detail<{ Bar::Two::<{I}> }> {
   |      ^^^^^^^^^^^^ unconstrained const parameter
   |
   = note: expressions using a const parameter must map each value to a distinct output value
   = note: proving the result of expressions other than the parameter are unique is not supported


```

**Comment by lcnr** [comment]
We currently don't treat constructors in a special way when checking whether generic parameters are constrained. This isn't really a bug but more a feature request. This is tracked in https://github.com/rust-lang/project-const-generics/issues/23 so I am closing this issue in favor of that.

We tried to add this explanation in the error message, are there ways we could improve the message to make it clearer what's going on here?
```rust
   = note: expressions using a const parameter must map each value to a distinct output value
   = note: proving the result of expressions other than the parameter are unique is not supported
```
