### ISSUE TITLE
Confusing `impl Trait` limitation

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rust#104526]
For some reason, `impl Trait` is allowed in a type's first mention but not in a `where` clause.

```rust
use core::ops::Add;

// Allowed
fn foo<T: Add<Output = impl Default>>(t: T) {}
fn bar<T: AsRef<impl Default>>(t: T) {}

// Not allowed
fn another_foo<T>(t: T)
where
    T: Add<Output = impl Default>,
{
}
fn another_bar<T>(t: T)
where
    T: AsRef<impl Default>,
{
}
```

Besides, the error message isn't very helpful.

```
`impl Trait` only allowed in function and inherent method return types, not in *****bound***** (which bound?)
```

**Comment by cjgillot** [comment]
There are 2 stages to fixing this issue. Everything happens in `rustc_ast_lowering`.

1. Make the diagnostic more explicit.  The diagnostic is named `MisplacedImplTrait`.  The term "bound" comes from the `Display` impl for `ImplTraitPosition`.
2. Allow impl-trait in where clauses. We'd need to investigate a bit why lowering marks impl-trait as disallowed in one case and not the other.

**Comment by estebank** [comment]
A wording change and an applicable suggestion to [write something like this](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=afb3adeab1e8ada4691328956d507387) would be great.

**Comment by bombless** [comment]
What does "only allowed in function and inherent method return types" actually mean?
In the [original RFC](https://github.com/rust-lang/rfcs/blob/master/text/1522-conservative-impl-trait.md), it says "may only be written within the return type of a freestanding or inherent-impl function, not in trait definitions or any non-return type position", but it is not the case now per [RFC1951](https://github.com/rust-lang/rfcs/blob/master/text/1951-expand-impl-trait.md) and [related PR](https://github.com/rust-lang/rust/pull/45918)

So I think this "inherent method return types" phrase should be removed entirely. Further more what does "only allowed in function" mean anyway?

According to [RFC1951](https://github.com/rust-lang/rfcs/blob/master/text/1951-expand-impl-trait.md#expansion-to-arguments) the main compilation error we deal with here should be "ERROR `impl Trait` not allowed within Fn trait sugar".

All RFC1522-related tests  seems to be outdated, e.g. [ui/impl-trait/where-allowed.rs](https://github.com/rust-lang/rust/blob/master/src/test/ui/impl-trait/where-allowed.rs).

I'm trying to address above-mentioned issues, so discussion above is what I have thought of so far, I'm writing it down in case I miss anythin.

**Comment by jonathanCogan** [comment]
I think that the current message means “only allowed in function [return types] and inherent method return types” but I agree that it is no longer correct because `impl Trait` is allowed in the argument position, and there are [plans](https://rust-lang.github.io/impl-trait-initiative/explainer/where_ok.html) to expand it to more locations.

**Comment by estebank** [comment]
TBH, it should suggest [adding a type param](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=45a830c27caa7eb23c938827fd96f500).

**Comment by bombless** [comment]
https://github.com/rust-lang/rust/blob/master/src/test/ui/impl-trait/where-allowed.rs#L13
we are already allowing this form, it's just inconsistent.
So suggesting adding a type param might be a regression

**Comment by c410-f3r** [comment]
Closing due to the lack of activity

**Comment by Jules-Bertholet** [comment]
This is being tracked in https://github.com/rust-lang/impl-trait-initiative/issues/15 and https://github.com/rust-lang/impl-trait-initiative/issues/16, I believe.
