### ISSUE TITLE
Arc-hyperbolic-trigonometric functions are very inaccurate

### ISSUE THREAD

**Issue by pavpanchekha** [rust-lang/rust#104548]
The functions `asinh` and `acosh` for both `f32` and `f64` are quite inaccurate, both for very large inputs (because `x * x` overflows) and, for `asinh`, for very small inputs (due to kinda-complex cancellation).

I tried this code:

```rust
fn main() {
    println!("{}", (600.0 as f64).sinh().asinh());
    println!("{}", (1e-16 as f64).sinh().asinh());
    println!("{}", (600.0 as f64).cosh().acosh());
    
    println!("{}", (60.0 as f32).sinh().asinh());
    println!("{}", (1e-8 as f32).sinh().asinh());
    println!("{}", (60.0 as f32).cosh().acosh());
}
```

This code evaluates `asinh(sinh(x))` and `acosh(cosh(x))`. Naturally I expected the output to be `x`, but instead the output is `inf` and `0`, indicating overflow and cancellation.

### Meta

I ran this in the Rust Playground on both Stable (1.65.0) and Nightly (`2022-11-16 e9493d63c2a57b91556d`).

**Comment by pavpanchekha** [comment]
The issue was originally discovered by @finnbear in https://github.com/FPBench/FPBench/pull/118.

I'm testing solutions that don't rely on `libm` in https://github.com/herbie-fp/herbie/pull/514.

**Comment by pavpanchekha** [comment]
In the two PRs above the following implementations are proposed:

```
fn asinh(x: f64) -> f64 {
	let ax = x.abs();
	let ix = 1.0 / ax;
	((ax + (ax / (f64::hypot(1.0, ix) + ix)))).ln_1p().copysign(x)
}

fn acosh(x: f64) -> f64 {
	if x < 1.0 { f64::NAN } else { (x + ((x - 1.0).sqrt() * (x + 1.0).sqrt())).ln() }
}
```

I'll file a PR once I get time to figure out how to download + build + test Rust, probably this or next week.

**Comment by pavpanchekha** [comment]
Here is the accuracy plot from Herbie for `f64::asinh`, red being the current Rust expression and green being the proposed fix:

<img width="602" alt="image" src="https://user-images.githubusercontent.com/30707/202554752-9dcb0e0d-6a4f-4763-b7f3-278bfad89b1a.png">

And here's `f64::acosh`:

<img width="611" alt="image" src="https://user-images.githubusercontent.com/30707/202554846-492bd78d-d4f9-42d1-b151-817a380b0e36.png">

The `f32` versions look similar but the problems occur at different (smaller) inputs.

**Comment by finnbear** [comment]
> I'll file a PR once I get time to figure out how to download + build + test Rust, probably this or next week.

I already have a Rust fork and the required tools to test it so, if it's ok with you, I could write the PR using your proposed implementation.
