### ISSUE TITLE
`#[track_caller]` on async fn's was previously a no-op but now produces a compiler error

### ISSUE THREAD

**Issue by anp** [rust-lang/rust#104588]
### Code

I tried [this code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=2fc5786e03284fbf498bc9e3bd976671):

```rust
#[track_caller]
async fn foo() {
    println!("{}", std::panic::Location::caller());
}


#[tokio::main]
async fn main() {
    foo().await;
}
```

I expected to see this happen: a successful build that prints `src/main.rs:3:20` (i.e. the attribute is a no-op)

Instead, this happened:

```
Compiling playground v0.0.1 (/playground)
error[[E0658]](https://doc.rust-lang.org/nightly/error-index.html#E0658): `#[track_caller]` on closures is currently unstable
 --> src/main.rs:2:16
  |
2 | async fn foo() {}
  |                ^^
  |
  = note: [see issue #87417 <https://github.com/rust-lang/rust/issues/87417>](https://github.com/rust-lang/rust/issues/87417) for more information
  = help: [add `#![feature(closure_track_caller)]`](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021#) to the crate attributes to enable
```

### Version it worked on

It most recently worked on: 1.65.0 stable

### Version with regression

playground's current nightly: `1.67.0-nightly (2022-11-17 83356b78c4ff3e7d84e9)`

I think this compilation failure was introduced by https://github.com/rust-lang/rust/pull/104219 which adds actual support for track_caller on async fn's, since it was previously a no-op.

TBH, in hindsight I think we probably should have disallowed track_caller on async fn's in the initial implementation so that we could leave room for unstable support in the future. However given that this wasn't considered, it seems like this may now be a stability regression.

**Comment by compiler-errors** [comment]
cc: @bryangarza

@anp, that's a good point. it's probably possible to make `#[track_caller]` a no-op + lint, and gate this behavior behind something else (either `closure_track_caller`, or a new feature such as `async_track_caller`).

**Comment by anp** [comment]
That makes a lot of sense as a way to resolve this. Having the ungated usage produce a warning seems like a great way to avoid confusion about a feature flag silently changing compiled behavior.

**Comment by bryangarza** [comment]
> cc: @bryangarza
> 
> > TBH, in hindsight I think we probably should have disallowed track_caller on async fn's in the initial implementation so that we could leave room for unstable support in the future.
> 
> @anp, that's a good point. it's probably possible to make `#[track_caller]` a no-op + lint against the ungated usage as a warning, and gate this behavior behind something else (either `closure_track_caller`, or a new feature such as `async_track_caller`).

Sounds good, I can put up a PR that does this. I didn't realize that the annotation was already being used on async fn's in the wild

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23104588.20.60.23.5Btrack_caller.5D.60.20on.20async.20fn's.20was.20previously.20a.20no.E2.80.A6)).

@rustbot label -I-prioritize +P-medium
