### ISSUE TITLE
rustc incorrectly classifies 13th Gen Intel CPU as goldmont

### ISSUE THREAD

**Issue by database64128** [rust-lang/rust#104579]
Running `rustc --print target-cpus` on an i9-13900K prints:

```console
Available CPUs for this target:
    native         - Select the CPU of the current host (currently goldmont).
    alderlake
    ...
```

The `goldmont` target doesn't even have AVX/AVX2 support. Does this affect codegen with `-Ctarget-cpu=native`?

**Comment by lukas-code** [comment]
This is a LLVM issue. It's fixed on the master branch with https://reviews.llvm.org/D135937, but hasn't been backported to 15.x yet.

In the meantime, you can use `-Ctarget-cpu=alderlake` as a workaround.

@rustbot label A-LLVM

**Comment by rywng** [comment]
I can still reproduce this on raptor lake cpu with latest stable rust, where LLVM merged https://github.com/llvm/llvm-project/commit/a806fc2767d74f2d052647e272dd4339bd747bf0 into v17.0.6:

```
❯ rustc --print target-cpus | grep currently
    native                  - Select the CPU of the current host (currently goldmont).
    x86-64                  - This is the default target CPU for the current build target (currently x86_64-unknown-linux-gnu).
```

`rustc -Vv`:

```
rustc 1.77.1 (7cf61ebde 2024-03-27)
binary: rustc
commit-hash: 7cf61ebde7b22796c69757901dd346d0fe70bd97
commit-date: 2024-03-27
host: x86_64-unknown-linux-gnu
release: 1.77.1
LLVM version: 17.0.6
```

**Comment by database64128** [comment]
@rywng Your `rustc` is a bit old. Upgrade to the latest stable version and try again. I'm closing this issue as it appears to have been fixed:

```console
Available CPUs for this target:
    native                  - Select the CPU of the current host (currently alderlake).
```

**Comment by database64128** [comment]
Took another look at the output, and there's `raptorlake` in the list, which should have been chosen instead of `alderlake`. Should I reopen this issue?

**Comment by workingjubilee** [comment]
there's two parts to the issue's original question:

- is it inaccurate?
- does this affect codegen?

the original answers were, I believe, "yes" and "yes".

however, for Raptor Lake, I believe the answers are "yes it is inaccurate" (strictly speaking), but "no it will not affect codegen", as the microarchitecture is effectively identical from the compiler's PoV, just with some Bigger Numbers:
- https://github.com/llvm/llvm-project/blob/0fd017ce43875283ecce55f18f721f47ba37a920/llvm/lib/Target/X86/X86.td#L1808-L1809
- https://github.com/llvm/llvm-project/blob/0fd017ce43875283ecce55f18f721f47ba37a920/clang/test/Preprocessor/predefined-arch-macros.c#L2041-L2183
