### ISSUE TITLE
[Discussion] Purpose of `PROBLEMATIC_CONSTS`

### ISSUE THREAD

**Issue by ThatOneCalculator** [rust-lang/rust#104699]
I don't see anything utterly offensive in `PROBLEMATIC_CONSTS`, why not let programmers have fun and talk about boobs in their code?

**Comment by saethlin** [comment]
What you are asking for is already the case. Tidy only applies to this repo: https://github.com/rust-lang/rust/blob/28a53cdb4695b71cb9ee39959df88542056479cd/src/tools/tidy/src/style.rs#L1

**Comment by jyn514** [comment]
This decision has already made, we don't revisit old decisions without new information.

I'm going to lock this since it has a tendency to bring out trolls.
