### ISSUE TITLE
non-defining opaque type use in defining scope

### ISSUE THREAD

**Issue by SOF3** [rust-lang/rust#104680]
I tried this code on **nightly-2022-10-21**:

```rust
#![feature(type_alias_impl_trait)]

trait Set<D: 'static> {
    type Iter<'t>: Iterator<Item = D> where Self: 't;
    fn iter_discrims(&self) -> Self::Iter<'_>;
}

impl<D: Copy + 'static> Set<D> for Vec<D> {
    type Iter<'t> = impl Iterator<Item = D> where Self: 't;
    fn iter_discrims(&self) -> Self::Iter<'_> { self[..].iter().copied() }
}
```

This should compile because the TAIT should resolve into `Copied<slice::Iter<'t, D>>`.

Instead, I get this error:

```
error: non-defining opaque type use in defining scope
  --> src/lib.rs:10:49
   |
10 |     fn iter_discrims(&self) -> Self::Iter<'_> { self[..].iter().copied() }
   |                                                 ^^^^^^^^^^^^^^^^^^^^^^^^ lifetime `'_` is part of concrete type but not used in parameter list of the `impl Trait` type alias
```

To prove that this code should compile, I simply change the TAIT to a named type:

```rs
type Iter<'t> = std::iter::Copied<std::slice::Iter<'t, D>>;
```

and this compiled.

I also tested the problematic code on **nightly-2022-10-20** (one day before) and the code compiled correctly, so there is most likely a regression within the rollup that day.

**Comment by cjgillot** [comment]
I'm tempted to classify this as a fixed bug.
Your code should not have compiled: the concrete type `std::iter::Copied<std::slice::Iter<'t, D>>` captures lifetime `'t`, but that lifetime does not appear in the bounds of `impl Iterator<Item = D>`. Per the rules of impl-trait, it should err.
Adding a `+ 't` to make `type Iter<'t> = impl Iterator<Item = D> + 't where Self: 't;` compiles fine.

Compare to:
```rust
#![feature(type_alias_impl_trait)]
type Iter<'t, D: 'static + Copy> = impl Iterator<Item = D>;
fn iter_discrims<D: 'static + Copy>(vec: &Vec<D>) -> Iter<'_, D> { vec[..].iter().copied() }
```
which fails with the same error, and gets fixed the same way.

I agree that the diagnostic may be improved though.

**Comment by SOF3** [comment]
Agreed, I didn't realize I was missing the `+ 't` there. Was briefly confused by the `where Self: 't` when I was debugging this.

**Comment by SOF3** [comment]
so is the resolution here that it is a documentation issue, or is it just a wontfix?
