### ISSUE TITLE
Rust does not normalize opaque types with escaping bound vars

### ISSUE THREAD

**Issue by compiler-errors** [rust-lang/rust#104601]
Opening this issue to record the fact that we don't normalize opaques with escaping bound vars in `Reveal::All` mode after #103509. 

I am not aware of any impacts of this on regular `rustc` compilation sessions, at least not without using TAIT in some strange ways. However, this causes rust-lang/miri#2433 to reoccur, and makes me sad theoretically, since we should be revealing all opaques during monomorphization, for example.

Fixing this is not hard (43119d643857efc366bfca527ac2dadfc3f2e906, #100980), but doing it without incurring major performance penalties (#103423) is difficult.

**Comment by RalfJung** [comment]
FWIW the Miri ICE also needs `type_alias_impl_trait`.
