### ISSUE TITLE
`extra::tempfile::TempDir` causes IoError during Drop

### ISSUE THREAD

**Issue by klutzy** [rust-lang/rust#10462]
```Rust
use std::os;
use extra::tempfile::TempDir;
fn main() {
    let temp_dir = TempDir::new("asdf").unwrap();
    os::change_dir(temp_dir.path());
}
```

```
task '<main>' failed at 'Unhandled condition: io_error:
io::IoError{kind: OtherIoError, desc: "resource busy or locked", detail: None}',
```
`TempDir` has `Drop` implementation of calling `rmdir` the dir, but it may fail (platform-dependent) if the task `change_dir`ed.
part of #10452: `run-pass/glob-std.rs`.

**Comment by alexcrichton** [comment]
Since opening the `drop` implementation of `TempDir` has been modified to respect the semantics of not panicking on drop and ignoring I/O errors, so I'm going to close this.
