### ISSUE TITLE
parser warning "`macro` is experimental" interacts badly with module-level `cfg`

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#104633]
Given code like this
```rust
#![feature(decl_macro)]
#![cfg(someflagthatisnotset)]

pub macro mymacro() {}
```
what I expect should happen is that this works fine, since the feature flag is set so the parser should accept parsing the `pub macro`, and also the file is anyway empty after `cfg` expansion. However, I get a warning instead:
```
warning: `macro` is experimental
 --> src/lib.rs:4:1
  |
4 | pub macro mymacro() {}
  | ^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: [see issue #39412 <https://github.com/rust-lang/rust/issues/39412>](https://github.com/rust-lang/rust/issues/39412) for more information
  = help: [add `#![feature(decl_macro)]`](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021#) to the crate attributes to enable
  = warning: unstable syntax can change at any point in the future, causing a hard error!
  = note: for more information, [see issue #65860 <https://github.com/rust-lang/rust/issues/65860>](https://github.com/rust-lang/rust/issues/65860)
```

It looks like the `cfg` *does* disable the feature flag, but does *not* disable parsing of the rest of the file. That is a problem, since it means it is impossible to `cfg`-out an entire file that contains experimental syntax. I thought I could fix this by ordering the `cfg` after the `feature`, but as the example shows that does not help.

This probably started happening with https://github.com/rust-lang/rust/pull/99935.
Cc @CAD97 @petrochenkov

**Comment by CAD97** [comment]
Two bits:

- Doesn't `#![feature]` have to be at the crate root?
- You can `#[cfg]` out parsing of a module, but it has to be on the `mod` statement.

`#[cfg]` are always processed after parsing, so I believe the compat warning is correct here. At least, doing this same thing with properly gated syntax causes an error. For example,

```rust
#![cfg(FALSE)]

fn test() {
    do yeet;
}
```

is a hard error for the unstable/experimental syntax. The unstable syntaxes that are only warnings when cfgd out is more an unfortunate happenstance, since this makes them at least somewhat syntax-stable. The ones uplifted to warnings by #99935 were ones crater said were essentially not being used at the time it was originally tested.

**Comment by RalfJung** [comment]
The thing is, this should work, since I *am* setting the feature gate
```rust
#![feature(yeet_expr)]
#![cfg(FALSE)]

fn test() {
    do yeet;
}
```

**Comment by petrochenkov** [comment]
@RalfJung 
This was discussed in detail in https://github.com/rust-lang/rust/issues/65860, you even participated in the discussion.

**Comment by RalfJung** [comment]
I vaguely remember some discussions, but I don't recall that this would make `cfg` gating entirely impossible...

If the parser goes over the entire file, no matter the `cfg`m then why can't it take into account all `feature`, no matter the `cfg`?

**Comment by petrochenkov** [comment]
>why can't it take into account all `feature`, no matter the `cfg`?

Ah, this part, it may be doable, yes.

**Comment by RalfJung** [comment]
If a `#![cfg]` only erased the attributes that come *after* it, that would also work. But it seems to apply "backwards in code" so there's no place to put a `feature`  that the parser would honor if there's a module/crate-level `cfg` disabling things.

**Comment by shepmaster** [comment]
I have something similar. In SNAFU, I have a number of crates that are only for testing purposes. I was experimenting with `yeet`:

**Cargo.toml**
```toml
[package]
name = "repro"
version = "0.1.0"
edition = "2021"

[dependencies]
```
**src/lib.rs**
```rust
#![cfg(test)]
#![feature(yeet_expr)]

fn x() -> Result<(), i32> {
    do yeet 0;
}
```

`cargo +nightly test` isn't happy:

```
error[E0658]: `do yeet` expression is experimental
 --> src/lib.rs:5:5
  |
5 |     do yeet 0;
  |     ^^^^^^^^^
  |
  = note: see issue #96373 <https://github.com/rust-lang/rust/issues/96373> for more information
  = help: add `#![feature(yeet_expr)]` to the crate attributes to enable
```

Is this the same case, or should I open a new issue?

**Comment by CAD97** [comment]
It's the same issue. I agree that it's reasonable to apply at least the `#![feature]` which occur before a `#![cfg]`.

If they were outer attributes,

```rust
#[feature(...)]
#[cfg(...)]
crate {
}
```

the `#[feature]` attribute would be logically evaluated before the `#[cfg]` attribute is evaluated, and thus the `#[cfg]` shouldn't suppress the effect of the `#[feature]`.

**Comment by RalfJung** [comment]
@CAD97 yes that would resolve the issue for me. :)

**Comment by RalfJung** [comment]
I guess that would technically be a breaking change since this will currently compile on stable
```rust
#![feautre(...)]
#![cfg(notathing)]
```

However, this generates an empty crate, so... doesn't seem terribly useful?

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/108221.

**Comment by petrochenkov** [comment]
It turns out stuff breaks if features are considered for fully unconfigured crates https://github.com/rust-lang/rust/pull/108221#issuecomment-1437166262.

**Comment by petrochenkov** [comment]
>the `#[feature]` attribute would be logically evaluated before the `#[cfg]` attribute is evaluated, and thus the `#[cfg]` shouldn't suppress the effect of the `#[feature]`.

This is not how it currently works in other places in the language, the attribute expansion algorithm always picks `cfg` and `cfg_attr` attributes first for expansion, and then proceeds to attribute macros and inert attributes.

I guess we could make an exception and change the order for the specific [list](https://github.com/rust-lang/rust/pull/108221#issuecomment-1435760517) of "very early" attributes, but I'm not sure it's good idea, maybe we should just leave this papercut alone.

**Comment by petrochenkov** [comment]
>maybe we should just leave this papercut alone

On the other hand it then becomes impossible to fully unconfigure a crate if it directly contains unstable syntax, which also doesn't seem right.

I'll try to implement this left-to-right amendment for a second crater run, let's see what happens.
It's a hack, but these "very early" attributes are already hacky enough due to being required before the main expansion pass.

**Comment by RalfJung** [comment]
> On the other hand it then becomes impossible to fully unconfigure a crate if it directly contains unstable syntax, which also doesn't seem right.

Yeah, that is what prompted this issue. It can be worked around (by moving all unstable syntax our of the `lib.rs` file) but that is somewhat unsatisfying. Though given backwards compatibility constraints, none of the hacks that make this possible are really satisfying either...

> I'll try to implement this left-to-right amendment for a second crater run, let's see what happens.

Sounds plausible. Another option might be to special-case *only* `feature`. AFAIK none of the other attributes cause problem with fully unconfiguring a crate?

**Comment by petrochenkov** [comment]
Next attempt - https://github.com/rust-lang/rust/pull/110141.

**Comment by RalfJung** [comment]
Hm, this had some odd fallout in miri-test-libstd, not sure what is going on there
https://github.com/rust-lang/miri-test-libstd/actions/runs/5233119090/jobs/9448362774

**Comment by RalfJung** [comment]
Okay it's mostly resolved by reordering as one would expect: https://github.com/rust-lang/rust/pull/112535.

But one strange lint remains:
```rust
warning: unknown lint: `fuzzy_provenance_casts`
   --> std_miri_test/../library/std/src/lib.rs:610:1
    |
610 | #[allow(dead_code, unused_attributes, fuzzy_provenance_casts)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: the `fuzzy_provenance_casts` lint is unstable
    = note: see issue #95228 <https://github.com/rust-lang/rust/issues/95228> for more information
    = help: add `#![feature(strict_provenance)]` to the crate attributes to enable
    = note: `#[warn(unknown_lints)]` on by default
```

@petrochenkov looks like it is processing that `allow(...)` deep inside the crate but not processing the  `feature(strict_provenance)` at the crate root?
