### ISSUE TITLE
Implement task-safe "current directory"

### ISSUE THREAD

**Issue by klutzy** [rust-lang/rust#10463]
Currently we provide `os::getcwd()`/`os::change_dir()` via OS functions ([`libc::getcwd`](http://pubs.opengroup.org/onlinepubs/009695399/functions/chdir.html) or [GetCurrentDirectory](http://msdn.microsoft.com/en-us/library/windows/desktop/aa364934%28v=vs.85%29.aspx)), but curdir information is maintained per-process, which means it is not thread-safe nor task-safe.

Here is a sample code for current dir race:
```Rust
use std::os;
use std::io;
use std::io::fs;

fn main() {
    let tmp_path = os::tmpdir();
    for i in range(0u, 20u) {
        let path = tmp_path.join(i.to_str());
        do spawn {
            io::result(|| fs::mkdir(&path, io::UserRWX));
            let _ret = os::change_dir(&path);
            let cur = os::getcwd();
            if cur != path {
                println!("expected {:s} but found {:s}",
                          path.as_str().unwrap(), cur.as_str().unwrap());
            }
        }
    }
}
```

So we must ban them and implement "current directory" using task-local storage.

**Comment by steveklabnik** [comment]
As part of IO reform, we got `current_dir`, but its implementation is `os_imp::getcwd`, so not much has changed.

**Comment by aturon** [comment]
@steveklabnik 

I think this ticket should move to the RFCs wishlist. What we wound up with in IO reform is basically exposing the system APIs, which work with process-global working directories. On the posix side at least there are `at` variants that we may want to expose eventually, but this would be a new API surface.

**Comment by l0kod** [comment]
> this would be a new API surface

It may be possible to replace most `Path` with a common trait to `Path` and `File` (e.g. [`AsIo`](https://github.com/rust-lang/rust/pull/21936#issuecomment-73378854)).
cc #21936

**Comment by alexcrichton** [comment]
I'm going to close this in favor of a future to-be-opened RFC issue, but it's unlikely that we'll do this with today's design principles of the standard library (e.g. not adding our own abstractions on top)
