### ISSUE TITLE
replace if let Some(inner) = option with if option is Some(inner)

### ISSUE THREAD

**Issue by Silentdoer** [rust-lang/rust#104798]
it is more clear

**Comment by thomcc** [comment]
I don't think this syntax is up for debate, and certainly *replacing* syntax like this is not. For new syntax, this is the wrong repository for that discussion.

If you want to make a more thorough argument for it (a one-sentence comment is unlikely to be sufficient), you could try starting a discussion on https://internals.rust-lang.org/, or filing an issue discussing it on https://github.com/rust-lang/rfcs. I don't think you'll have much luck in either case, though -- the language is probably somewhat too mature for major changes like this.

**Comment by thomcc** [comment]
I'm going to close this out -- syntax discussions sometimes get heated, and this probably isn't the right place for this one anyway, thanks.
