### ISSUE TITLE
nightly regression (2022-11-22) on rstest

### ISSUE THREAD

**Issue by baloo** [rust-lang/rust#104759]
Sorry for the badly formatted bug report here, I'm not entirely sure how to report regression on a dependency as I don't have a minimal reproduction code.

```
$ cargo +nightly-2022-11-22 build 
   Compiling rstest v0.12.0
error: `fixtures::get<'_, impl Iterator<Item = &parse::Fixture>>::{opaque#1}<'_>` does not live long enough
  --> /home/.../.cargo/registry/src/github.com-1ecc6299db9ec823/rstest-0.12.0/src/render/mod.rs:64:13
   |
64 |             TestCaseRender::new(name, attrs, (resolver, &resolver_fixtures))
   |             ^^^^^^^^^^^^^^^^^^^

error: `fixtures::get<'_, impl Iterator<Item = &parse::Fixture>>::{opaque#1}<'_>` does not live long enough
  --> /home/.../.cargo/registry/src/github.com-1ecc6299db9ec823/rstest-0.12.0/src/render/mod.rs:64:13
   |
64 |             TestCaseRender::new(name, attrs, (resolver, &resolver_fixtures))
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

it works in `nightly-2022-11-21`:
```
$ cargo +nightly-2022-11-21 build
[...]
Finished dev [optimized + debuginfo] target(s) in 27.09s
```

(problem applies with rstest master version)

**Comment by compiler-errors** [comment]
This could use a https://github.com/rust-lang/cargo-bisect-rustc bisection

**Comment by baloo** [comment]
searched nightlies: from nightly-2022-11-21 to nightly-2022-11-22
regressed nightly: nightly-2022-11-22
searched commit range: https://github.com/rust-lang/rust/compare/a28f3c88e50a77bc2a91889241248c4543854e61...b7bc90fea3b441234a84b49fdafeb75815eebbab
regressed commit: https://github.com/rust-lang/rust/commit/7fe6f36224e92db6fbde952e0b7e50863161f6ee

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.4</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start=2022-11-21 --end=2022-11-22 --preserve
```
</details>

(thanks for the suggestion! never used that tool before!)

**Comment by baloo** [comment]
Closing this in favor of #104815 which carries a reproduction example
