### ISSUE TITLE
opaque types, patterns and subtyping ICE: `IndexMap: key not found`

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#104779]
```rust
struct Inv<'a>(&'a mut &'a ());
enum Foo<T> {
    Bar,
    Var(T),
}
type Subtype = Foo<for<'a, 'b> fn(Inv<'a>, Inv<'b>)>;
type Supertype = Foo<for<'a> fn(Inv<'a>, Inv<'a>)>;

fn foo() -> impl Sized {
    loop {
        match foo() {
            Subtype::Bar => (),
            Supertype::Var(x) => {}
        }
    }
}
```
results in the following ICE:
```rust
thread '<unnamed>' panicked at 'no entry found for key', compiler/rustc_borrowck/src/region_infer/mod.rs:2196:9
```
([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=3d2ca294ec96ae43ef351732756ac9d8))

**Comment by ouz-a** [comment]
This gave error till 1.62 https://godbolt.org/z/b9M8s6vWb after that it started ICEing with different error message.

**Comment by matthiaskrgr** [comment]
This now crashes with `thread 'rustc' panicked at 'IndexMap: key not found', compiler/rustc_borrowck/src/region_infer/mod.rs:2227:9
`

**Comment by JohnTitor** [comment]
Triage: Fixed on the latest nightly, marked as E-needs-test
@rustbot labels: +E-needs-test
