### ISSUE TITLE
pre-push git hooks should avoid push remote when `test tidy --bless` failed

### ISSUE THREAD

**Issue by chenyukang** [rust-lang/rust#104718]
I met this issue several times, after I pushed code to remote PR, the CI failed because `test tidy --bless` failed.
https://github.com/rust-lang/rust/actions/runs/3524341026/jobs/5909613972

I have an investigation, we have a `pre-push` git hook setup, but seems we do not exit when `test tidy --bless` changed code format, and push will also successfully, then the CI will fail for this issue. 
https://github.com/rust-lang/rust/blob/b7463e8bdb7b039e75241dcc4ea65bbd24d5c608/src/etc/pre-push.sh#L25

I think we should keep consistent here, if there are code format issues, `git push` will fail until it's fixed.

A inconvenience with this is some developers may want to push frequently with temporary changes.

@jyn514

**Comment by jyn514** [comment]
Sounds good :) are you interested in making a PR?
