### ISSUE TITLE
`transmute::<u8, bool>()` generates bad code

### ISSUE THREAD

**Issue by ChayimFriedman2** [rust-lang/rust#104832]
```rust
pub fn bar(v: u8) -> bool {
    unsafe { std::mem::transmute(v) }
}
```
Generates (https://rust.godbolt.org/z/xzYdeffxq, note the redundant `and`):
```asm
mov     eax, edi
and     al, 1
ret
```

This is because we generate a redundant trunc/zext:

https://github.com/rust-lang/rust/blob/1dda298ad39a64e019a3511139c5b13ac0a18e54/compiler/rustc_codegen_ssa/src/mir/block.rs#L1820-L1824

```llvm-ir
define zeroext i1 @_ZN7example3bar17h1b5c1a9c0782d25bE(i8 %v) unnamed_addr #0 {
  %0 = alloca i8, align 1
  %1 = trunc i8 %v to i1
  %2 = zext i1 %1 to i8
  store i8 %2, ptr %0, align 1
  %3 = load i8, ptr %0, align 1, !range !2, !noundef !3
  %4 = trunc i8 %3 to i1
  br label %bb1

bb1:                                              ; preds = %start
  ret i1 %4
}
```

**Comment by deltragon** [comment]
This seems related to https://github.com/rust-lang/rust/issues/96140, where the transmute went the other way.
The conclusion there was:

https://github.com/rust-lang/rust/issues/96140#issuecomment-1193098943
> Yea, the only actionable thing I can see here is to remove the extra asm instructions for perf reasons or to allow follow up optimizations to trigger.
>
> I guess let's close this and if someone encounters a repro for more complex programs that have missing opts we can revisit

**Comment by ChayimFriedman2** [comment]
Yep, this is a dup.
