### ISSUE TITLE
Implement task-safe platform-indepent timezones

### ISSUE THREAD

**Issue by klutzy** [rust-lang/rust#10480]
Similar to #10463, `extern::time::at()` (which internally uses `localtime()`) currently depends on "TZ" environment variable, which causes `setenv` race.
Also its interpretation is also platform-dependent: linux libc understands `TZ=America/Los_Angeles` but Windows does not. (#10307)

We need:
- `Timezone` type whose constructor may understand common time zone strings.
- `fn localtime(&self, utc_time) -> Tm` method for `Timezone`. (This seems quite hard because it seems that there is no corresponding libc function)
- For environment timezone, we may provide `unsafe fn get_env_tz() ->  Timezone`.

I think this overlaps [datetime design](https://github.com/mozilla/rust/wiki/Lib-datetime) a bit, but anyway current implementation is "unsafe".

**Comment by frewsxcv** [comment]
The time module has moved to a separate repo https://github.com/rust-lang/time Should this Issue be moved there or is this an internal rustc component?

**Comment by klutzy** [comment]
Yes, it's moved to time crate. (`time::at()` now)

**Comment by frewsxcv** [comment]
Can this be closed then?

**Comment by Gankro** [comment]
At best, this would be an RFC issue anyway.
