### ISSUE TITLE
Error E0507 suggestion is invalid with `let else` statements

### ISSUE THREAD

**Issue by sgued** [rust-lang/rust#104838]
Given the following code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=537fe56a67206a6c8918592455e4aa0d)):

```rust
struct Testing {
    a: Option<String>
}

fn testing(a: &Testing) {
    let Some(_s) = a.a else {
        return;
    };
}
```

The current output is:

```
error[[E0507]](https://doc.rust-lang.org/nightly/error-index.html#E0507): cannot move out of `a.a` as enum variant `Some` which is behind a shared reference
 --> src/lib.rs:6:14
  |
6 |     let Some(_s) = a.a else {
  |              ^^
  |              |
  |              move occurs because `a.a.0` has type `String`, which does not implement the `Copy` trait
  |              help: consider borrowing here: `&_s`

For more information about this error, try `rustc --explain E0507`.
error: could not compile `playground` due to previous error
```

Ideally the output should look like:

```
error[[E0507]](https://doc.rust-lang.org/nightly/error-index.html#E0507): cannot move out of `a.a` as enum variant `Some` which is behind a shared reference
 --> src/lib.rs:6:14
  |
6 |     let Some(_s) = a.a else {
  |              ^^    ^^^
  |              |     |
  |              |     help: consider borrowing here: `&a.a`       
  |              |
  |              move occurs because `a.a.0` has type `String`, which does not implement the `Copy` trait


For more information about this error, try `rustc --explain E0507`.
error: could not compile `playground` due to previous error
```

An alternative would be to recommend using `ref`, but this would not be consistent with the `match` suggestion:

```rust
fn testing2(a: &Testing) {
    match a.a {
        Some(_s) => return,
        None => {}
    }
}
```

```
error[[E0507]](https://doc.rust-lang.org/nightly/error-index.html#E0507): cannot move out of `a.a` as enum variant `Some` which is behind a shared reference
  --> src/lib.rs:12:11
   |
12 |     match a.a {
   |           ^^^ help: consider borrowing here: `&a.a`
13 |         Some(_s) => return,
   |              --
   |              |
   |              data moved here
   |              move occurs because `_s` has type `String`, which does not implement the `Copy` trait
```

Tested with Nightly version: 1.67.0-nightly (2022-11-23 70f8737b2f5d3bf7d6b7)

**Comment by chenyukang** [comment]
Maybe related to https://github.com/rust-lang/rust/pull/103908, but not in name resolve phase.

**Comment by sgued** [comment]
I think it's an issue of the statement and the match span being inverted when they shouldn't [here](https://github.com/rust-lang/rust/blob/master/compiler/rustc_borrowck/src/diagnostics/move_errors.rs#L173). It seems that for `let … else` errors, `match_place` is `None` when it shouldn't.

**Comment by sgued** [comment]
Well, the bug source of the bug is [here](https://github.com/rust-lang/rust/blob/master/compiler/rustc_mir_build/src/build/matches/mod.rs#L670)

**Comment by sgued** [comment]
The missing `match_place` should probably be added [here](https://github.com/rust-lang/rust/blob/master/compiler/rustc_mir_build/src/build/block.rs#L234)

**Comment by Jerrody** [comment]
> The missing `match_place` should probably be added [here](https://github.com/rust-lang/rust/blob/master/compiler/rustc_mir_build/src/build/block.rs#L234)

@estebank 
Hey, can you fix your PR? Maybe this is a potential fix, thanks.
https://github.com/rust-lang/rust/pull/103908
