### ISSUE TITLE
Don't codegen items that are statically unreachable

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#104858]
Currently, all items in a crate are codegened, and only stripped later in a linker pass: https://github.com/rust-lang/rust/blob/6c4bda6de456460520aa450d7ed10a1b3d9fa205/compiler/rustc_monomorphize/src/partitioning/mod.rs#L201-L205 https://github.com/rust-lang/rust/blob/a24a020e6d926dffe6b472fc647978f92269504e/compiler/rustc_codegen_ssa/src/back/link.rs#L2179-L2190 This unnecessarily bloats the amount of time and memory it takes to compile a crate. We already have a `dead_code` pass; we should use its results to avoid running codegen on unreachable items.

This is a prerequisite for https://github.com/rust-lang/rust/pull/103356, but I expect it will be a large boost to compile times even if that never lands.

**Comment by scottmcm** [comment]
A potential first step would be to handle `if const { monomorphized-predicate }`, #85836.

**Comment by jyn514** [comment]
We already do this. https://github.com/rust-lang/rust/pull/104860#issuecomment-1327343916
