### ISSUE TITLE
Inexact and/or Wrong `{From,To}Primitive`

### ISSUE THREAD

**Issue by lifthrasiir** [rust-lang/rust#10481]
Motivating examples:

~~~~ {.rust}
(100_0000_0000_0000_2345u64).to_f64(); // => Some(1000000000000002244f64)
(42.5f64).to_u8(); // => Some(42u8)
(42.5e80f64).to_u8(); // => Some(0u8)
(42.5e80f64).to_i32(); // => Some(-2147483648i32)
~~~~

Note that the last two results can change depending on your optimization level. (Is it another issue?) It seems that it's due to the constant propagation across inlined function calls.

Currently we check for such cases in int to int and float to float conversion, but we don't check (and solely rely on casting) in int to float and float to int conversion. This can cause the inexact computation in two ways: unwanted truncation, and failed bound check. Four possible decisions have their pros and cons respectively, but should be decided and documented.

**Comment by bombless** [comment]
Luckily `ToPrimitive` was gone so we don't have this problem in std any more.

**Comment by arielb1** [comment]
The last of these is just a duplicatet of #10184, the others are expected behaviour.
