### ISSUE TITLE
"fishy" `skip_binder` actually ignoring bound variables

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#104825]
An `expect` there actually does panic for the `src/test/ui/generator/resume-arg-late-bound.rs` test.

I only moved this code between the files, the same comment and code pattern exists as well for normal closures:

https://github.com/rust-lang/rust/blob/e221616639fb87de9dca21e252ee8a2565ec51d0/compiler/rustc_trait_selection/src/traits/select/mod.rs#L2290

_Originally posted by @Swatinem in https://github.com/rust-lang/rust/pull/104321#discussion_r1029878199_

**Comment by compiler-errors** [comment]
I couldn't repro this failure, maybe @Swatinem was doing `.no_bound_vars().self_ty()` instead of `.self_ty().no_bound_vars()`? The ordering is important here.

**Comment by Swatinem** [comment]
I believe I did, yes.
