### ISSUE TITLE
Error parsing "since" field of deprecated attribute with nightly-2022-11-24

### ISSUE THREAD

**Issue by maxburke** [rust-lang/rust#104848]
When trying nightly-2022-11-24 I'm running into this issue:

```
error: expected `,`, found `.`
   --> /Users/max/.cargo/registry/src/github.com-1ecc6299db9ec823/geo-types-0.7.7/src/geometry/geometry_collection.rs:111:25
    |
111 | #[deprecated(since = 0.7.5, note = "Use `GeometryCollection::from(vec![geom])` instead.")]
    |                         ^ expected `,`
```

It popped up after nightly-2022-11-01, though I haven't yet bisected which day it started.

**Comment by ehuss** [comment]
This was changed as part of #104148. The compiler now validates attributes of trait impls. Updating geo-types to 0.7.8 can fix the issue.

**Comment by maxburke** [comment]
Ah, okay, I'll close the issue now.
