### ISSUE TITLE
Unstable book not getting updated

### ISSUE THREAD

**Issue by nicholasbishop** [rust-lang/rust#104919]
For example, https://github.com/rust-lang/rust/pull/103766 added a tracking issue for `error_in_core` a month ago, but the corresponding page in the unstable book still doesn't show it: https://doc.rust-lang.org/unstable-book/library-features/error-in-core.html

When I build the docs locally with `./x.py doc src/doc/unstable-book/` it shows the tracking issue properly, so I assume there's just something wrong with whatever infra is supposed to update https://doc.rust-lang.org/unstable-book.

**Comment by ehuss** [comment]
The documentation rides the trains just like the rest of Rust does. There is a separate `/nightly/` URL which has the updates from the latest nightly release: https://doc.rust-lang.org/nightly/unstable-book/library-features/error-in-core.html

Similarly there's a `/beta/` URL, and one for each specific release.

**Comment by nicholasbishop** [comment]
Oh thanks, it didn't occur to me that the unstable book would track unstable. Closing.
