### ISSUE TITLE
Redesign compiler diagnostic logging

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#10492]
The interface in `syntax::diagnostic` is super janky and causes a lot of problems with code higher up in the stack (it prevents anything from being sendable, for example). Rework it to use idiomatic traits, include a JSON output mode, and add the ability to work in #2092.

**Comment by steveklabnik** [comment]
Triage: @cmr what do you think of this today?

**Comment by cmr** [comment]
@steveklabnik I think this is still desirable, even more so for tools like Cargo to "understand" what rustc is outputting.
