### ISSUE TITLE
rustfmt / clippy component missing

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#104930]
`rustup update`
````
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2022-11-26, rust version 1.67.0-nightly (8681d4cff 2022-11-25)
info: skipping nightly which is missing installed components 'clippy', 'rustfmt'
````

It should not be possible that clippy component is missing since we are gating on it in CI..?
cc @jyn514  https://github.com/rust-lang/rust/pull/103648

**Comment by matthiaskrgr** [comment]
`rustup component list | grep "clippy\|rustfmt"`
````
clippy-x86_64-unknown-linux-gnu (installed)
rustfmt-x86_64-unknown-linux-gnu (installed)
````

**Comment by RustBlockchainEngineer** [comment]
same

**Comment by jyn514** [comment]
I think this is a rustup bug somehow, it's looking specifically for `-preview`:
```
; rustup update nightly --force
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2022-11-26, rust version 1.67.0-nightly (8681d4cff 2022-11-25)
warning: Force-skipping unavailable component 'clippy-preview-x86_64-unknown-linux-gnu'
warning: Force-skipping unavailable component 'rustfmt-preview-x86_64-unknown-linux-gnu'
```

I can back this out to give rustup time to fix it in a new release, this wasn't an urgent fix. I want to spend another few minutes investigating first though.

**Comment by ehuss** [comment]
I don't think rustup's rename system is designed to allow changing the name of a component.  https://github.com/rust-lang/rustup/pull/1549 contains more information about how and why this was done.

**Comment by jyn514** [comment]
@kinnison says I need at a minimum to keep the `rename` key for clippy-preview. I will try to test that out today but I don't have permissions for a dist-static build and it might take me a bit so I'll put up a revert in the meantime.

**Comment by Mark-Simulacrum** [comment]
I'm happy to run dev-static builds as needed, but I agree that a revert is appropriate for the time being. Please feel free to poke on Zulip if you need a quick review, etc.

I'm a little surprised our testing in https://github.com/rust-lang/rust/pull/103648 didn't catch this -- let's make sure we understand how to test it in the future.

**Comment by jyn514** [comment]
@Mark-Simulacrum what went wrong in #103648 is that `rustup component add rustfmt` worked before and after, but running `rustup component add rustfmt` before and `rustup toolchain update` after did not. I'll make sure to test that in any future PR.
