### ISSUE TITLE
Code coverage showing [derive(Debug)] as missed region

### ISSUE THREAD

**Issue by Wameuh** [rust-lang/rust#105055]
I tried this code:

```rust
#[derive(PartialEq, Debug)]
pub enum EnumCov{
    First,
    Second,
    Third,
    Fourth
}



#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_cov() {
        let one = EnumCov::First;
        let two = EnumCov::Second;
        let three = EnumCov::Third;
        let four = EnumCov::Fourth;

        assert_eq!(one, EnumCov::First);
        assert_eq!(two, EnumCov::Second);
        assert_eq!(three, EnumCov::Third);
        assert_eq!(four, EnumCov::Fourth);
    }
}
```
Running these commands to get the code coverage report
```bash
cargo llvm-cov --html
```
Same issue with `RUSTFLAGS="-C instrument-coverage" cargo test --tests` merge/report/show

I expected to see this happen: coverage 100%

Instead, this happened: Debug is shown as missed region
![image](https://user-images.githubusercontent.com/72522288/204558056-e4708209-9644-4d4c-907a-331dc421ebb4.png)

It's quite the same as https://github.com/rust-lang/rust/issues/83601 

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0 (897e37553 2022-11-02)

binary: rustc

commit-hash: 897e37553bba8b42751c67658967889d11ecd120

commit-date: 2022-11-02

host: x86_64-unknown-linux-gnu

release: 1.65.0

LLVM version: 15.0.0


```

Backtrace not applicable.

Thanks!

**Comment by ruuda** [comment]
The coverage report is correct, in the sense that `<EnumCov as Debug>::fmt` which is generated by `#[derive(Debug)]` is not executed by your test.

Being technically correct is not so helpful in the case of `Debug` though. Most of the time you _don‘t_ expect it to be covered. The impl has to be there for `assert_eq!` to be able to print the counterexample, but when the test pass, the `Debug` impl is intentionally not covered. It would be nice to have a way to exclude it from coverage.

The same applies to expressions inside `panic!`, `unreachable!`, etc. — they are not covered, but they are not intended to ever be.

**Comment by Sycrosity** [comment]
Has anyone found a "good" solution to preventing coverage from marking `#[derive(Debug)]` and `panic!` macros as uncovered? Seeing as its not an actual issue with coverage, it would still be nice to be able to mark these instances as covered.

**Comment by VladasZ** [comment]
I have exactly the same problem. Is there a way to silence this? Or do I need to add `dbg!()` call for each struct?

**Comment by ruuda** [comment]
A possible workaround when using [`grcov`](https://github.com/mozilla/grcov) is to use `--excl-line` to exclude e.g. `#\[derive\(`.
