### ISSUE TITLE
Tracking issue for `PathBuf::as_mut_os_string` and `Path::as_mut_os_str`

### ISSUE THREAD

**Issue by zertosh** [rust-lang/rust#105021]
Feature gate: `#![feature(path_as_mut_os_str)]`

This is a tracking issue for adding `PathBuf::as_mut_os_string` and `Path::as_mut_os_str` (rust-lang/libs-team#140).

### Public API

```rust
impl PathBuf {
    // ...
    pub fn as_mut_os_string(&mut self) -> &mut OsString {
        &mut self.inner
    }
    // ...
}

impl Path {
    // ...
    pub fn as_mut_os_str(&mut self) -> &mut OsStr {
        &mut self.inner
    }
    // ...
}
```

### Steps / History

- [x] Implementation: #105002
- [x] #105018: the initial example for `Path::as_mut_os_str` was contrived because one must go through `into_boxed_path` to get a `&mut Path`. A `DerefMut` impl makes it possible to demonstrate a more realistic use.
- [x] #105801
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by the8472** [comment]
That seems questionable to me. Right now we don't have any restrictions what goes into a Path, but on some future platform it might be necessary to have a validation on `Path::new` (e.g. only a restricted set of prefixes is allowed) and that can't be done if it can be freely mutated as a osstring.

**Comment by dtolnay** [comment]
On platforms that would need such a restriction, would `Path::new` have a different return type, or a different name, or would panic? In addition to `Path::new`, there's already `impl AsRef<Path> for str`, `impl AsRef<Path> for OsStr`, and probably a bunch of others that bake in the expectation that paths are arbitrary OS strings. If we're gonna be making those panic or be conditionally compiled, doing the same for `Path::as_mut_os_str` is no more complex than any of those. But it seems more likely to me that the way we would address platform-specific path restrictions would be by leaving it to the system calls to report failure on an unsupported contents of a path, or doing validation in Rust before the system call, not during PathBuf mutations.

**Comment by zertosh** [comment]
## Stabilization Report

### Implementation History

* `PathBuf::as_mut_os_string` and `Path::as_mut_os_str` implemented in #105002.
* `DerefMut for PathBuf` was implemented in #105018 to make this feature more usable.
* More realisitic doctests were added in #105801 (now possible with #105018).

### API Summary

A summary of the API is included [at the top of this tracking issue](https://github.com/rust-lang/rust/issues/105021#issue-1466768097).

### Experience Report

n/a

**Comment by zertosh** [comment]
@dtolnay, can you please start an FCP? (as per [Stabilization PR Checklist](https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html#stabilization-pr-checklist))

**Comment by dtolnay** [comment]
@rust-lang/libs-api
@rfcbot fcp merge

This stabilizes [`PathBuf::as_mut_os_string`](https://doc.rust-lang.org/nightly/std/path/struct.PathBuf.html#method.as_mut_os_string) and [`Path::as_mut_os_str`](https://doc.rust-lang.org/nightly/std/path/struct.Path.html#method.as_mut_os_str).

The point of these methods is illustrated in the documentation examples. They let you mutate the path contents in place without going through `PathBuf`'s limited mutation API (e.g. every `push` adding a separator).

```rust
path.as_mut_os_string().push("-suffix");

// equivalent to:
let mut os_string = std::mem::take(path).into_os_string();
os_string.push("-suffix");
*path = PathBuf::from(os_string);
```

Note that a [`Path::as_os_str`](https://doc.rust-lang.org/nightly/std/path/struct.Path.html#method.as_os_str) has existed since 1.0.0 to help people avoid using `AsRef<OsStr> for Path` in places that an as_ref() call might be ambiguous. Meanwhile `PathBuf::as_os_string` has not come up so far as a thing anyone wants.

**Comment by dtolnay** [comment]
I'm marking yaahc's box because she has stepped down from T-libs-api after the point that this feature got proposed for FCP.

**Comment by dtolnay** [comment]
@Amanieu or @joshtriplett or @m-ou-se?
