### ISSUE TITLE
Lifetime handling doesn't handle function pointers properly

### ISSUE THREAD

**Issue by LeoTestard** [rust-lang/rust#10501]
Let's say I've got a struct or enum containing functions (pure Rust functions, not closures, so passed by a simple pointer)

```
pub type Foo = fn(&int) -> ();

enum Baz {
    Bar(Foo)
}
```

The above code works. I can pass-around instances of Baz and call the function.
Now if I wan Baz to be copy-able, which should be possible since it only contains a pointer, and add the `#[deriving(Clone)]` attribute to it, I got a strange compiler error:

```
error: mismatched types: expected `fn(&int)` but found `fn(&int)` (expected concrete lifetime, but found bound lifetime parameter &)
test.rs:4 #[deriving(Clone)]
```

This worked perfectly well (including the deriving(Clone) attribute) while the function only took parameters by owned boxes or by-value. I only get this message since I added a borrowed parameter to the function. I don't see the problem here. If a function is simply passed by-pointer we should be able to copy this pointer.

I'm not sure this is the right title for this issue. Feel free to change it if it's miss chosen.

**Comment by steveklabnik** [comment]
Today:

```
pub type Foo = fn(&i32) -> ();

#[derive(Copy, Clone)]
enum Baz {
    Bar(Foo)
}

fn main() {}
```

error:

```
error: the trait `core::clone::Clone` is not implemented for the type `fn(&i32)`
```

/cc @rust-lang/lang , I know that recently, we changed something related to `fn` and `Clone`, but I'm not sure if this is behavior we want today. The error message is way better now, at least.

**Comment by brson** [comment]
Current error from @steveklabnik's code:

```


rustc 1.16.0 (30cf806ef 2017-03-10)
error[E0277]: the trait bound `fn(&i32): std::clone::Clone` is not satisfied
 --> <anon>:5:9
  |
5 |     Bar(Foo)
  |         ^^^^ the trait `std::clone::Clone` is not implemented for `fn(&i32)`
  |
  = help: the following implementations were found:
            <fn(A) -> Ret as std::clone::Clone>
            <extern "C" fn(A) -> Ret as std::clone::Clone>
            <extern "C" fn(A, ...) -> Ret as std::clone::Clone>
            <unsafe fn(A) -> Ret as std::clone::Clone>
          and 2 others
  = note: required by `std::clone::AssertParamIsClone`
```

**Comment by brson** [comment]
Seems to work as designed.

**Comment by eddyb** [comment]
@nikomatsakis You may want to reopen this if you feel like there is a path to making it work.
(Either by making the impls apply through some form of hopefully-sound HRTB capture or implementing `Clone` automatically for all `Copy` types, possibly through a future extension of specialization)
