### ISSUE TITLE
add built-in complex number types for C ABI compatibility

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#10500]
These are sadly not just treated as a simple `struct` on various platforms and have ABI requirements. I think support for the existing C math library is important because this isn't something we want to recreate on every platform.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#793
