### ISSUE TITLE
Test cases are disorganized

### ISSUE THREAD

**Issue by sstewartgallus** [rust-lang/rust#10507]
Rust's test cases are disorganized, and are contained in a flat directory space. They should be neatly organized into a folder hierarchy. This will make it easier to add test cases, and separate the test cases from implementation modules. Currently this sort of organization is mostly done by prefixes (block-must-not-have-result-do.rs, block-must-not-have-result-res.rs, etc...) but folders would make this a lot nicer.

**Comment by brson** [comment]
I'm closing this because this is a fairly non-specific and subjective wishlist item. If somebody decides to reorganize the test suite that may be desirable, but it needs a firm proposal and effort, and its not a pressing issue.
