### ISSUE TITLE
Tracking Issue for `file_create_new`

### ISSUE THREAD

**Issue by yjhn** [rust-lang/rust#105135]
Feature gate: `#![feature(file_create_new)]`

This is a tracking issue for [`std::fs::File::create_new(path)`](https://doc.rust-lang.org/std/fs/struct.File.html#method.create_new) function.  It is related to [RFC 1252](https://github.com/rust-lang/rfcs/pull/1252), but isn't part of the RFC.

### Public API

```rust
// std::fs

impl File 
    pub fn create_new<P: AsRef<Path>>(path: P) -> io::Result<File>
}
```

### Steps / History

- [X] Implementation: implemented in #98801
- [x] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by Nilstrieb** [comment]
This was implemented in #98801.

**Comment by joshtriplett** [comment]
This has been implemented for a while, and seems to work as advertised.

Shall we stabilize it?

@rfcbot merge

**Comment by BurntSushi** [comment]
Is this a common enough routine to need to justify its own constructor on `File`? Needing to use `OpenOptions` for a case like this seems okay to me?

**Comment by mr-bit** [comment]
`File::create` returns a file in write-only mode but `File::create_new` returns a file in read-write mode. What is the reason for this difference?

**Comment by joshtriplett** [comment]
> Is this a common enough routine to need to justify its own constructor on `File`? Needing to use `OpenOptions` for a case like this seems okay to me?

The use case for `create_new` seems at least as common as `create`, in filesystem code that I've observed. `create` is useful for "the user told me to write to a specific filename, which may or may not exist" (e.g. shell redirection or a `-o` option). `create_new` is used when writing out a file *expected* to not exist, where using `create` might introduce a bug and potentially a security vulnerability. Having only `create` and not `create_new` seems likely to steer people towards `create` even if it's not what they *should* be using, which would make such bugs more likely. Having both makes it obvious that the user needs to select the appropriate one for their use case.

**Comment by BurntSushi** [comment]
@joshtriplett I buy it! Thanks for explaining. :)

**Comment by joshtriplett** [comment]
> `File::create` returns a file in write-only mode but `File::create_new` returns a file in read-write mode. What is the reason for this difference?

`File::create` is useful for "the user asked me to write to this specific filename, which may or may not exist", such as for a user-specified output file. In that scenario, if it *does* exist, it might be write-only (e.g. a magic device file). For instance, consider `echo 1 | sudo tee /proc/sys/vm/drop_caches` on Linux: that file can be written, but *not* read, and attempting to open it read-write will return "permission denied".

That doesn't apply to `File::create_new`: it *always* makes a new file, which means it will always be an *ordinary* file, so there's no reason it needs to be write-only. And given that it doesn't *need* to be write-only, read-write is the more convenient choice.

**Comment by m-ou-se** [comment]
Thanks for those very clear explanations, @joshtriplett!
