### ISSUE TITLE
Add Rust versions of all the Rosetta Code tasks

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#10513]
See http://rosettacode.org/wiki/Reports:Tasks_not_implemented_in_Rust for the things not yet implemented.

Ideally we'd put this off until 1.0 or after, so as to not be rewriting them constantly. There's also a lot of them, and many of them are quite interesting problems (if you're not just porting versions of other ones, at least).

Suggested by @eddyb

**Comment by steveklabnik** [comment]
https://github.com/Hoverbear/rust-rosetta exists now, and has people actively working on it. It would be nice to move them in-tree maybe post 1.0, but we don't need to keep something open to track that.
