### ISSUE TITLE
regression: ~const not implemented

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#105105]
* https://crater-reports.s3.amazonaws.com/beta-1.66-rustdoc-2.1/beta-2022-11-21/gh/JLockerman.asm_sim/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.66-rustdoc-2.1/beta-2022-11-21/gh/takatori.rust-coin/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.66-rustdoc-2.1/beta-2022-11-21/reg/bnum-0.3.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.66-rustdoc-2.1/beta-2022-11-21/reg/proc-bitfield-0.2.1/log.txt

This is a regression (the code used to get documented on stable). It also seems surprising that we're leaking ~const into stable error messages (presumably a T-compiler problem).

```
[INFO] [stdout] error[E0277]: the trait bound `sundries::int64: std::convert::From<{integer}>` is not satisfied
[INFO] [stdout]    --> src/assembly.rs:107:11
[INFO] [stdout]     |
[INFO] [stdout] 107 |     r7 <- 1;
[INFO] [stdout]     |           ^ the trait `~const std::convert::From<{integer}>` is not implemented for `sundries::int64`
[INFO] [stdout]     |
[INFO] [stdout]    ::: src/sundries.rs:72:55
[INFO] [stdout]     |
[INFO] [stdout] 72  |             LoadImmediate{destination: $d, value: $s1.into()}; => $($stmt)*)
[INFO] [stdout]     |                                                       ---- required by a bound introduced by this call
[INFO] [stdout]     |
[INFO] [stdout] note: the trait `std::convert::From<{integer}>` is implemented for `sundries::int64`, but that implementation is not `const`
[INFO] [stdout]    --> src/assembly.rs:107:11
[INFO] [stdout]     |
[INFO] [stdout] 107 |     r7 <- 1;
[INFO] [stdout]     |           ^
[INFO] [stdout]     = note: required for `{integer}` to implement `~const std::convert::Into<sundries::int64>`
```

**Comment by Mark-Simulacrum** [comment]
cc @rust-lang/rustdoc

**Comment by GuillaumeGomez** [comment]
Let's maybe involve @rust-lang/compiler as I don't remember rustdoc changing something for `~const`.

**Comment by oli-obk** [comment]
I don't know how the first one (asm_sim) could possibly compile on stable. So if it now is not documenting anymore, but was before, did rustdoc change how it handles static items?

I'll need to look at the second one tomorrow.

The last two are using unstable feature gates opting into const traits, so I expect them to fail to compile with recent changes. Is rustdoc turning on all cargo features? That could explain why crates that otherwise work on stable start failing.

**Comment by Mark-Simulacrum** [comment]
Oh, interesting. It looks like crater sets RUSTC_BOOTSTRAP=1 in rustdoc crater runs (https://github.com/rust-lang/crater/blob/53db254d5729b31a657c148a69fa6fbbf8d537e8/src/runner/test.rs#L423-L425) which makes these potentially not really stable/beta regressions (i.e. they are really just nightly only regressions). I think the ones with unstable feature gates can be discounted then, though that doesn't seem to be all of the ones in this issue.

**Comment by oli-obk** [comment]
I tested all of them.

The first two don't compile on stable at all and I don't believe they ever did (but they also don't use any feature gates ?!? did someone write code and it didn't work and then they abandoned it?). It looks like rustdoc crater counts things as regressions even if the crate doesn't compile at all.

The last two are definitely using nightly via a cargo feature.
