### ISSUE TITLE
Detect `println!("{x}", x)`

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#105225]
When encountering `println!("{x}", x)` the user either meant `println!("{x}")` or `println!("{x}", x=x)`. The later is only likely in <=2018 editions, while the former is what they actually likely wanted. We should suggest it.

**Comment by tanveerraza789** [comment]
Hello, I would like to work on this issue with some guidance. 
It would be great if someone can give me a lead to start.
@rustbot claim

**Comment by estebank** [comment]
You'll want to start looking at https://github.com/rust-lang/rust/blob/71db0dd918424accf32104d8b780079105a7ac30/compiler/rustc_builtin_macros/src/format.rs#L660 and work your way backwards from there.

You should look at the unused list https://github.com/rust-lang/rust/blob/71db0dd918424accf32104d8b780079105a7ac30/compiler/rustc_builtin_macros/src/format.rs#L457 and check if the name corresponds to one of the `pieces`. If it does, then point at it.

**Comment by tanveerraza789** [comment]
Hello @estebank ,
I was trying to do the same as you told but I'm not able to check if the unused arg is present in the piece, 
I can check the currently unused arg in the closure here
https://github.com/rust-lang/rust/blob/71db0dd918424accf32104d8b780079105a7ac30/compiler/rustc_builtin_macros/src/format.rs#L461

Current unused arg is:- 

 ```rust 
args.explicit_args()[i].expr.to_ty().unwrap().kind.is_simple_path().unwrap()
```
Gives out "x" for `println!("{x}",x);`
But I'm not able to compare it to `pieces` as it contains either `String()` literal or `NextArgument()` and `NextArgument()` doesn't contain the literal it refers to.

Please correct me If I misunderstood something.
