### ISSUE TITLE
bug on massa Node

### ISSUE THREAD

**Issue by saeedaslani72** [rust-lang/rust#105326]
### Code

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by ehuss** [comment]
@saeedaslani72 Do you think you can fill in the fields for the issue report?

**Comment by workingjubilee** [comment]
if you have issues with https://github.com/massalabs/massa then please report bugs to them.
