### ISSUE TITLE
Allow generating a C header representing the exported symbols of a lib

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#10530]
For example, 

``` rust
#[crate_type="lib"];

pub struct Foo { x: i16 }

#[no_mangle]
pub extern "C" fn bar(x: u64) -> Foo { ... }

pub fn ignored() { ... } // wrong ABI
```

would correspond to

``` C
#ifndef FILENAME_H
#define FILENAME_H

#include<stdint.h>

struct Foo {
    int16_t x;
}

struct Foo bar(uint64_t);

#endif
```

so that one can call into Rust from C more easily.

(This is the inverse operation of the proposed `#[header="stdio.h"] mod stdio;` functionality for using libclang to read C headers into a form that rustc understands: https://github.com/mozilla/rust/issues/2124)

**Comment by steveklabnik** [comment]
bindgen does some of this, but `rust.h` would be nice for FFIing into Rust for sure

**Comment by ArtemGr** [comment]
Bindgen wasn't even a proper Rust crate, last time I checked, and building it on Debian was enough of a pain that I had to choose another route for my FFI needs. The wish to have this functionality in Rust is, I think, primarily a wish to have it available everywhere. It could be satisfied with bindgen working as a proper Cargo `dev-dependencies` package able to generate the Rust stubs from a C header entirely from `build.rs`.

**Comment by tomjakubowski** [comment]
I have some WIP stuff here. https://github.com/tomjakubowski/custard/tree/dev

I think last I left it, it may have been in the middle of a refactor.

**Comment by luser** [comment]
I'm sure everyone here is already aware, but the state of the art here appears to be rusty-cheddar: https://github.com/Sean1708/rusty-cheddar

**Comment by king6cong** [comment]
rusty-cheddar and rusty-binder aren't very active those days. Should this be a feature important enough for Rust to be maintained by rust-lang-nursery or such? @alexcrichton

**Comment by aturon** [comment]
Closing; this should be tackled by an external tool.
