### ISSUE TITLE
`implementation of FnOnce is not general enough` regressed into `closure/generator type that references itself`

### ISSUE THREAD

**Issue by cynecx** [rust-lang/rust#105396]
### Code

I tried this code:

```rust
use core::future::Future;

trait AsyncFn<I, R>: FnMut(I) -> Self::Fut {
    type Fut: Future<Output = R>;
}

impl<F, I, R, Fut> AsyncFn<I, R> for F
where
    Fut: Future<Output = R>,
    F: FnMut(I) -> Fut,
{
    type Fut = Fut;
}

async fn call<C, R, Fn>(mut ctx: C, mut f: Fn) -> Result<R, ()>
where
    Fn: for<'a> AsyncFn<&'a mut C, Result<R, ()>>,
{
    loop {
        match f(&mut ctx).await {
            Ok(val) => return Ok(val),
            Err(_) => continue,
        }
    }
}

fn test(ctx: &mut usize) {
    call(ctx, |ctx| async move {
        let _ctx = ctx;
        Ok(1usize)
    });
}


```

I expected to see this happen: rustc produces ``` implementation of `FnOnce` is not general enough ```

Instead, this happened: rustc produces ``` closure/generator type that references itself ```

### Version it worked on

1.65.0

### Version with regression

1.67.0-nightly (2022-12-05 e1d819583f0bf13b016b)

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

**Comment by jruderman** [comment]
Regression in nightly-2022-11-05 from 6718ea1cff98da785c10079cac1c1ecc30c12d52 (#101834, @compiler-errors, @lcnr)

<details><summary>Bisect command used</summary>

```bash
cargo-bisect-rustc --preserve --script ./shout.sh --start 2022-08-01 --end 2022-12-05
```

with this shout.sh:

```bash
! rustc --edition=2021 src/main.rs 2>&1 | grep "that references itself"
```

</details>

**Comment by compiler-errors** [comment]
I'm not sure if I'd consider this a regression. Certainly this is an interesting consequence of #101834, but we don't expect error messages to remain stable across versions.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23105396.20.60implementation.20of.20FnOnce.20is.20not.20general.20enough.60.20re.E2.80.A6)).

@rustbot label -I-prioritize +P-low
