### ISSUE TITLE
Infinite recursion crash with `use _`

### ISSUE THREAD

**Issue by jruderman** [rust-lang/rust#105353]
Found with a [modified fuzz-rustc](https://github.com/jruderman/fuzz-rustc)

### Code

```rust
use _;
use crate::*;
fn main() {}
```

### Crash

Infinite recursion between [`resolve_ident_in_module_unadjusted` and `resolve_ident_in_module_unadjusted_ext`](https://github.com/rust-lang/rust/blob/e1d819583f0bf13b016b119c1c2c43e6d3979450/compiler/rustc_resolve/src/ident.rs#L722-L1009)

[crash-report.txt](https://github.com/rust-lang/rust/files/10162882/crash-report.txt)

The base of the stack is visible when running with `RUST_MIN_STACK=100000`: [crash-report-with-small-stack.txt](https://github.com/rust-lang/rust/files/10162929/crash-report-with-small-stack.txt)

### Regression

Regression in nightly-2019-10-17, perhaps from #64623 (@matthewjasper, @petrochenkov)

### Version

```
rustc 1.67.0-nightly (e1d819583 2022-12-05)
binary: rustc
commit-hash: e1d819583f0bf13b016b119c1c2c43e6d3979450
commit-date: 2022-12-05
host: x86_64-apple-darwin
release: 1.67.0-nightly
LLVM version: 15.0.4
```

@rustbot label +I-crash +T-compiler

**Comment by bvanjoi** [comment]
I think this issue is same as  https://github.com/rust-lang/rust/issues/110164, and it had been solved, so this issue can be closed.
