### ISSUE TITLE
#102750 regresses layout size of Cow<>

### ISSUE THREAD

**Issue by emilio** [rust-lang/rust#105371]
```rust
    assert_eq!(std::mem::size_of::<std::borrow::Cow<'static, str>>(), 24);
```

Passes on stable and beta but not on Nightly.

I bisected it, results below which point to #102750:

searched nightlies: from nightly-2022-10-20 to nightly-2022-12-06
regressed nightly: nightly-2022-11-24
searched commit range: https://github.com/rust-lang/rust/compare/ff8c8dfbe66701531e3e5e335c28c544d0fbc945...70f8737b2f5d3bf7d6b784fad00b663b7ff9feda
regressed commit: https://github.com/rust-lang/rust/commit/4e0d0d757e2f1b61ec809420b006545a9f8974c0

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.5</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start 2022-10-20 
```
</details>

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

cc: @nnethercote @the8472 @wesleywiser

**Comment by the8472** [comment]
I'm working on improving the niche placement logic, #104807

**Comment by emilio** [comment]
Sure, sure, I know that, I wasn't trying to imply otherwise. I just figured that it was probably unintended given the PR that introduced it. Thanks for your work on struct layout optimizations, they're great! :)

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23105371.20.23102750.20regresses.20layout.20size.20of.20Cow.3C.3E)).

@rustbot label -I-prioritize +P-medium

**Comment by khuey** [comment]
This shipped :(
