### ISSUE TITLE
Windows edge case with set_len() (Access Denied)

### ISSUE THREAD

**Issue by tmpfs** [rust-lang/rust#105437]
I tried this code:

```rust
let mut file = OpenOptions::new().write(true).append(true).open(path.as_ref())?;
file.set_len(0)?;
```

I expected the file to be truncated to zero bytes.

Instead, on Windows 11 Home I got an "Access Denied (OsError 5)" error. The same code works fine on MacOS.

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0
```

I implemented a workaround for my use case that fixed the error:

```rust
if cfg!(target_os = "windows") {
    let _ = OpenOptions::new().write(true).truncate(true).open(&self.file_path);
} else {
    self.file.set_len(0)?;
}
```

But curious to know if this is a bug or a configuration issue on Windows.

**Comment by ChrisDenton** [comment]
See [the RFC](https://rust-lang.github.io/rfcs/1252-open-options.html#append-mode) that introduced the current form of the API.

> Append-mode is similar to write-only, but all writes always happen at the end of the file. 
> ...append is treated as a separate access mode in Rust, and if `.append(true)` is specified than `.write()` is ignored.

So I think technically speaking the Windows behaviour is correct. It should not be possible to write earlier in the file while in append mode. However, it would seem that this is only actually enforced in Windows. At least for ordinary files.

**Comment by tmpfs** [comment]
Thanks @ChrisDenton for the information. So if I understand this correctly then the correct way for me to truncate the file to zero bytes when it is in append only mode is to use the workaround for windows for all platforms as opposed to `set_len(0)`:

```rust
let _ = OpenOptions::new().write(true).truncate(true).open(&self.file_path);
```

Would that be a better approach?

**Comment by ChrisDenton** [comment]
Yes, currently truncating the file and opening in append mode should be separate steps. But maybe in the future this is something we should support properly.
