### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mahatmiarz** [rust-lang/rust#105463]
28:     0x7f1e09ae7393 - std::sys::unix::thread::Thread::new::thread_start::h08658e35bc4cca8a
                               at /rustc/01fbc5ae789fc0c7a2da71d3cd908451f175e4eb/library/std/src/sys/unix/thread.rs:108:17
  29:     0x7f1e058d2609 - start_thread
  30:     0x7f1e057f5133 - clone
  31:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.67.0-nightly (01fbc5ae7 2022-12-07) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `massa_api`

### Code

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by TaKO8Ki** [comment]
Cloud you provide your code or mcve?
