### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by sulthan1107** [rust-lang/rust#105503]
### Code

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by WaffleLapkin** [comment]
The issue doesn't provide any information about what the issue is. Have you forgotten to fill-in the info? I'm going to close this, since this is unactionable.

Feel free to reopen if you can provide more information about the "bug".
