### ISSUE TITLE
code area isn't scrollable on mobile (rustdoc)

### ISSUE THREAD

**Issue by cynecx** [rust-lang/rust#105580]
This code area isn't scrollable (horizontal scrolling):

https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html

<img width="407" alt="image" src="https://user-images.githubusercontent.com/5961244/206933746-924b4f96-ec92-4281-9bae-76fc88b28a45.png">

It seems like `contain: layout` on the `<details>` caused this. This got introduced here https://github.com/rust-lang/rust/pull/102253 (cc @jsha).

We can make this work by making the parent `<code>` behave like a block but still being inline (`inline-block`).

Something like this should fix this:

```css
pre > code {
    display: inline-block;
}
```

However, I am not quite sure whether this offsets the improvements made in https://github.com/rust-lang/rust/pull/102253.

**Comment by jsha** [comment]
Thanks for reporting this! We should definitely fix it. I'm not sure if `inline-block` is the right way to fix it, but I can poke at it and see what I find.
