### ISSUE TITLE
MIR inlining breaks Location::caller()

### ISSUE THREAD

**Issue by saethlin** [rust-lang/rust#105538]
```rust
use core::panic::Location;

#[inline]
fn nested() -> &'static Location<'static> {
    Location::caller()
}

fn main() {
    println!("{:?}", nested());
}
```

In debug mode, this prints
```
Location { file: "src/main.rs", line: 5, col: 5 }
```
But with optimizations, this prints:
```
Location { file: "src/main.rs", line: 9, col: 22 }
```
With optimizations and `-Zinline-mir=no`, this prints:
```
Location { file: "src/main.rs", line: 5, col: 5 }
```

This check in the MIR inliner is hiding this problem from the track-caller UI tests:
https://github.com/rust-lang/rust/blob/32da2305880765a4c76180086959a2d5da131565/compiler/rustc_mir_transform/src/inline.rs#L336-L344

@rustbot label +A-mir-opt +A-mir-opt-inlining

---

`rustc --version --verbose`:
```
rustc 1.68.0-nightly (dfe3fe710 2022-12-09)
binary: rustc
commit-hash: dfe3fe710181738a2cb3060c23ec5efb3c68ca09
commit-date: 2022-12-09
host: x86_64-unknown-linux-gnu
release: 1.68.0-nightly
LLVM version: 15.0.6
```

**Comment by tmiasko** [comment]
Ignoring changes in the standard library and optimization level at which MIR inliner is enabled, bisection points to #94427 cc @cjgillot.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23105538.20MIR.20inlining.20breaks.20Location.3A.3Acaller.28.29)).

@rustbot label -I-prioritize +P-medium

**Comment by tmiasko** [comment]
```rust
use std::panic::Location;

macro_rules! f {
    () => { Location::caller() }
}

#[inline(always)]
fn g() -> &'static Location<'static> {
    f!()
}

fn main() {
    println!("{:?}", g());
}
```

```console
$ rustc a.rs && ./a
Location { file: "a.rs", line: 9, col: 5 }
$ rustc a.rs -O && ./a
Location { file: "a.rs", line: 4, col: 13 }
```
