### ISSUE TITLE
Help message when importing item from wrong module is wrong

### ISSUE THREAD

**Issue by Aloso** [rust-lang/rust#105566]
Given the following code: [playground link](https://play.rust-lang.org/?version=beta&mode=debug&edition=2021&gist=f14d7f575cdc0618195986a680b216fb)

```rs
use serde::{Serialize, IgnoredAny};
```

The current output is:

```
error[E0432]: unresolved import `serde::IgnoredAny`
 --> src/lib.rs:1:24
  |
1 | use serde::{Serialize, IgnoredAny};
  |                        ^^^^^^^^^^ no `IgnoredAny` in the root
  |
help: consider importing this struct instead
  |
1 | use serde::{Serialize, serde::de::IgnoredAny;
  |                        ~~~~~~~~~~~~~~~~~~~~~~
```

The help message is wrong for two reasons:

- The closing bracket is missing
- The crate name (`serde`) is repeated in the path, so the suggested code would import `serde::serde::de::IgnoredAny` instead of `serde::de::IgnoredAny`.

Ideally the output should look like:

```
help: consider importing this struct instead
  |
1 | use serde::{Serialize, de::IgnoredAny};
  |                        ~~~~~~~~~~~~~~
```

Note that the help message was only added recently, so this bug exists only on beta and nightly at the moment.

**Comment by fmease** [comment]
Duplicate of #105373.

**Comment by Aloso** [comment]
Thanks for checking!
