### ISSUE TITLE
Name resolution issue with recursive macros

### ISSUE THREAD

**Issue by comex** [rust-lang/rust#10550]
Test case - a macro that attempts to recursively set each pattern to 5.  I suppose this could be done more easily by using `$(...)*` on the right side, but my real use case has the recursive call inside a match expression.

    #[feature(macro_rules)];

    macro_rules! set_to_5 (
        (($fst:pat), $action:stmt) => (
            {
                let $fst = 5;
                $action
            }
        );
        (($fst:pat, $($rest:pat),*), $action:stmt) => (
            {
                let $fst = 5;
                set_to_5!(($($rest),*), $action)
            }
        )
    )

    fn main() {
        let mut x = 4;
        set_to_5!((a, b), {
            x = b; // this is OK
            x = a; // this fails
        });
    }

rustc output:

    huh.rs:22:12: 22:13 error: unresolved name `a`.
    huh.rs:22         x = a;
                          ^
    huh.rs:3:0: 16:1 note: in expansion of set_to_5!
    huh.rs:13:12: 14:9 note: expansion site
    huh.rs:3:0: 16:1 note: in expansion of set_to_5!
    huh.rs:20:4: 23:7 note: expansion site
    error: aborting due to previous error
    task 'rustc' failed at 'explicit failure', /usr/src/rust/src/libsyntax/diagnostic.rs:101
    task '<main>' failed at 'explicit failure', /usr/src/rust/src/librustc/lib.rs:396

But if I substitute the --pretty expanded output, it compiles fine:

    fn main() { let mut x = 4; { let a = 5; { let b = 5; { x = b; x = a; } } }; }

I'm new to Rust, so I don't know if this is intentional fallout from macro hygiene, but I don't see why the inner definition would work but not the outer one.

**Comment by steveklabnik** [comment]
The original sample now works, so I'm gonna give this a close
