### ISSUE TITLE
x fmt should only format modified files by default

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#105688]
Since rustfmt is deterministic and idempotent, running it twice on the same file should always have the same output (if it's not both of those things, it's a bug). So we can avoid running it unless the file has changed, which should make `x fmt` without arguments much faster.

_Originally posted by @chenyukang in https://github.com/rust-lang/rust/issues/105648#issuecomment-1348656496_

**Comment by jyn514** [comment]
This will need to be careful to still rerun rustfmt when we bump its version (which happens about every 6 weeks). Maybe we can generate a `.rustfmt-all-files.stamp` file and format every if it doesn't yet exist or has the wrong version.

**Comment by albertlarsan68** [comment]
Hello,
I want to work on that.
How would the detection of modified files work ?

**Comment by albertlarsan68** [comment]
Thanks, I will start working on this !

@rustbot claim

**Comment by the8472** [comment]
> You can use git merge-base HEAD origin/master 

That assumes that the rust-lang remote is labeled as origin. I call that upstream and my fork origin.

**Comment by jyn514** [comment]
Yes, https://github.com/rust-lang/rust/pull/105058 has a more general solution.

**Comment by albertlarsan68** [comment]
PR is up at #105702
