### ISSUE TITLE
Build of GNU toolchain 1.66.0 on Windows fails on rustbuild config.rs when git is installed in MSYS

### ISSUE THREAD

**Issue by georgik** [rust-lang/rust#105696]
Problem: The build of GNU toolchain 1.66.0 on Windows is failing in the rustbuild step when it's trying to locate git (MSYS git-2.38.1-1) .

Build steps:
- install Windows, MSYS2
- install dependencies according to https://github.com/rust-lang/rust#mingw
- clone Rust 1.66.0 code
- run:

```
python3 src/bootstrap/configure.py --release-channel=nightly --enable-extended --tools=clippy,cargo,rustfmt --dist-compression-formats='xz'
python3 x.py dist --stage 2
```

Failure:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }', config.rs:863:74
```

Snippet from stack trace of rustbuild:
```
34:     0x7ff77f1114e6 - mainCRTStartup
                               at C:\M\mingw-w64-crt-git\src\build-MINGW64\C:/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt\crtexe.c:206:9
```

Workaround:
- remove MSYS2 git
```
pacman -R git
```

After removing MSYS2 git the build pass without problem. The issue was not present in 1.65.0.

**Comment by yujincheng08** [comment]
any updates?

**Comment by mati865** [comment]
As a workaround you can run `export GIT_DIR=/dev/null` before the build to disable git support.
