### ISSUE TITLE
expected expression, found `..`

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#105634]
Given the following code: 

```rust
let _ = &..;
```

The current output is:

```
error: expected expression, found `..`
 --> src/main.rs:2:14
  |
2 |     let _ = &..;
  |              ^^ expected expression
```

`..` *is* a valid expression (a [`RangeFull`](https://doc.rust-lang.org/stable/std/ops/struct.RangeFull.html) literal), so this error is misleading. It should at a minimum have a suggestion to replace with the valid version `&(..)`, and probably should just work. It also imho ideally shouldn't be a hard parser error blocking semantic passes; the parse of `&(..)` is fairly unambiguously intended, even if we decide we should still require the parenthesis.

**Comment by agluszak** [comment]
I'm interested! Where should I look first?

**Comment by CAD97** [comment]
The [rustc dev guide](https://rustc-dev-guide.rust-lang.org/contributing.html) is a good place to start. If you have some compiler development experience already, that should get you going quickly enough.

One specifically relevant section is [`-Ztreat-err-as-bug`](https://rustc-dev-guide.rust-lang.org/compiler-debugging.html#getting-a-backtrace-for-errors), which will allow you to get a backtrace for what code is emitting this error. Then it should just be a matter of threading the proper information through. The rustdoc for the compiler crates is also available online; [rustc_parse](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_parse/index.html) is likely to be where you'll need to change.

**Comment by CAD97** [comment]
For extra context, `..` is accepted in expression position at least for both `let _ = ..;`, `macro_rules! m {($x:expr) => {}} m!(..)`, and obviously `&slice[..]`, so I have absolutely no idea what makes `&..` different that it causes a parser error in this case.
