### ISSUE TITLE
Casting the same i64 and u64 integers to f32 gives different results on `i686-pc-windows-msvc` target

### ISSUE THREAD

**Issue by icedrocket** [rust-lang/rust#105626]
### I tried this code:

```rust
fn main() {
    let mut n: i64 = 0b0000000000111111111111111111111111011111111111111111111111111111;
    println!("{}, {}, {}, {}", n, n as i64 as f32, n as u64 as f32, n as u128 as f32);
    assert_ne!((n as f64) as f32, n as f32);
    assert_eq!(n as i64 as f32, n as u64 as f32);
    n = -n;
    assert_ne!((n as f64) as f32, n as f32);
    assert_eq!(n as i64 as f32, -(-n as u64 as f32));
}
```

rust-num/num-bigint#261

### I expected to see this happen:
The code prints the output below and exits successfully.
```
18014397972611071, 18014397000000000, 18014397000000000, 18014397000000000
```

### Instead, this happened:
The code prints the output below and panics.
```
18014397972611071, 18014397000000000, 18014399000000000, 18014397000000000
```

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0 (897e37553 2022-11-02)
binary: rustc
commit-hash: 897e37553bba8b42751c67658967889d11ecd120
commit-date: 2022-11-02
host: x86_64-pc-windows-msvc
release: 1.65.0
LLVM version: 15.0.0
```

**Comment by CryZe** [comment]
The problem seems to be that u64 -> f32 apparently requires some sort of lookup table and I'm guessing that lookup table is buggy in Windows's libm (?).

https://rust.godbolt.org/z/9Gccr5o1s

**Comment by CryZe** [comment]
Took me way too long, but I figured it out. The fact that FPU instructions are used means that it runs into problems with the FPU accuracy. By default the control word is set to 0x27f on Windows and 0x37f on Linux. In particular the 0x3 vs 0x2 is the precision control setting of the FPU.

> 00 = 24 bits (REAL4)
01 = Not used
10 = 53 bits (REAL8)
11 = 64 bits (REAL10) (this is the initialized state)

So on Windows it's in 53-bits mode whereas on Linux it's in 64-bits mode.

Running the following code therefore fixes the problem on Windows:

```rust
fn load_fpu_control_word(control: u16) {
    unsafe {
        asm!("fldcw [{}]", in(reg) &control, options(nostack));
    }
}

load_fpu_control_word(0x37f);
```

This probably is an LLVM bug where LLVM assumes the FPU is configured like on Linux instead of like on Windows. MSVC for example just emits a call to `__ultod3` instead, which is probably the correct thing to do instead.

**Comment by icedrocket** [comment]
I can confirm that using the above code the casting issue is resolved.

**Comment by CryZe** [comment]
The function that lowers the uint to float cast is `X86TargetLowering::LowerUINT_TO_FP` in [`X86ISelLowering.cpp`](https://github.com/llvm/llvm-project/blob/678d8946ba2ba790c4c52e96e2134ee136e30057/llvm/lib/Target/X86/X86ISelLowering.cpp). There's basically a bunch of checks to generate shorter versions if various conditions are met, but all of them fail and it has to resort to using the FPU. There actually is one case in there where they treat Windows differently, I'm guessing something similar can be done to not fall into the FPU default case.

**Comment by icedrocket** [comment]
It seems to have been fixed in 1.66.0.

**Comment by CryZe** [comment]
I don't think that's true. The asm is the same.

**Comment by icedrocket** [comment]
I tested it with different code and I was mistaken.

**Comment by icedrocket** [comment]
This issue is solved in upstream of llvm-project.

**Comment by workingjubilee** [comment]
This was patched upstream (thanks icedrocket!) but it sounds like there's an intention to revert the patch, unfortunately: https://github.com/llvm/llvm-project/issues/59787#issuecomment-1397751498

I don't know if it is more profitable to work around this on our end by emitting the relevant call?

**Comment by icedrocket** [comment]
A new fix has been commited to upstream: llvm/llvm-project@11fb09ec0afa8620bba44f374763e2ad64332e2e
Should we backport this new fix to our LLVM forks?
