### ISSUE TITLE
Rust 1.66.0 install.sh fails when --without flag is used

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust#105755]
The 1.66.0 release broke something around the `--without` flag to `install.sh`. If I download and extract <https://static.rust-lang.org/dist/rust-1.66.0-x86_64-unknown-linux-gnu.tar.gz>, and then run, say
```
./install.sh --prefix="$PWD/installed" --without=rust-analyzer
```
it errors out with
```
install: uninstalling component 'rustc'
install: uninstalling component 'rust-std-x86_64-unknown-linux-gnu'
install: creating uninstall script at /home/jongje/166/rust-1.66.0-x86_64-unknown-linux-gnu/installed/lib/rustlib/uninstall.sh
install: installing component 'rustc'
install: installing component 'rust-std-x86_64-unknown-linux-gnu'
install: installing component 'rust-docs'
install: installing component 'rust-docs-json-preview'
install: installing component 'rust-demangler-preview'
install: installing component 'cargo'
install: installing component 'rustfmt-preview'
install: installing component 'rls-preview'
install: installing component '-preview'
install: error: manifest for -preview does not exist at /home/jongje/166/rust-1.66.0-x86_64-unknown-linux-gnu/-preview/manifest.in. see logs at '/home/jongje/166/rust-1.66.0-x86_64-unknown-linux-gnu/installed/lib/rustlib/install.log'
```

The same thing happens when other components are named in `--without`. The install completes successfully when `--without` isn't used. It appears the problem is with the new `rust-docs-json-preview` component, because the install is successful with

```
./install.sh --prefix="$PWD/installed" --without=rust-docs-json-preview
```

**Comment by Mark-Simulacrum** [comment]
I think given the workaround this is P-low.

**Comment by jonhoo** [comment]
Note that the workaround doesn't work when combined with `rust-docs`, so:
```console
$ ./install.sh --prefix="$PWD/installed" --without=rust-docs,rust-docs-json-preview
install: creating uninstall script at /home/jongje/166/rust-1.66.0-x86_64-unknown-linux-gnu/installed/lib/rustlib/uninstall.sh
install: installing component 'rustc'
install: installing component 'rust-std-x86_64-unknown-linux-gnu'
install: installing component '-json-preview'
install: error: manifest for -json-preview does not exist at /home/jongje/166/rust-1.66.0-x86_64-unknown-linux-gnu/-json-preview/manifest.in. see logs at '/home/jongje/166/rust-1.66.0-x86_64-unknown-linux-gnu/installed/lib/rustlib/install.log'
```

**Comment by jonhoo** [comment]
`rust-analysis` also appears to be broken:
```console
$ ./install.sh --prefix="$PWD/installed" --without=rust-analysis
install: creating uninstall script at /home/jongje/166/rust-1.66.0-x86_64-unknown-linux-gnu/installed/lib/rustlib/uninstall.sh
install: installing component 'rustc'
install: installing component 'rust-std-x86_64-unknown-linux-gnu'
install: installing component 'rust-docs'
install: installing component 'rust-docs-json-preview'
install: installing component 'rust-demangler-preview'
install: installing component 'cargo'
install: installing component 'rustfmt-preview'
install: installing component 'rls-preview'
install: installing component 'rust-analyzer-preview'
install: installing component 'llvm-tools-preview'
install: installing component 'clippy-preview'
install: installing component '-x86_64-unknown-linux-gnu'
install: error: manifest for -x86_64-unknown-linux-gnu does not exist at /home/jongje/166/rust-1.66.0-x86_64-unknown-linux-gnu/-x86_64-unknown-linux-gnu/manifest.in. see logs at '/home/jongje/166/rust-1.66.0-x86_64-unknown-linux-gnu/installed/lib/rustlib/install.log'
```

**Comment by Mark-Simulacrum** [comment]
I think we stopped shipping rust-analysis at some point?

**Comment by JakubOnderka** [comment]
> I think given the workaround this is P-low.

I think you should reprioritize this issue as this workaround doesn't work when other components are mentioned in `--without` argument as mentioned by @jonhoo. This issue affects building our internal rust Docker image.

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/rust-installer/pull/119 is a potential fix, we'll see if we can get it reviewed.

I believe, based on looking at the code, the workaround of passing full names (e.g., rust-analyzer-preview rather than rust-analyzer) or similar should work. https://github.com/rust-lang/rust-installer/pull/119 makes that required for any effect at all.

I'm not quite sure what changed with the addition of rust-docs-json-preview, it might be mostly coincidence that this actually had an effect on your particular invocations.

**Comment by jonhoo** [comment]
Should that CR be tagged relnotes? Feels like it may be useful to call out for anyone using `--without`

**Comment by Mark-Simulacrum** [comment]
Tagged!

**Comment by khvzak** [comment]
As Rust 1.66.1 still broken, workaround:
```
--without=rust-docs-json-preview,rust-docs
```

Other components can be added just after the `rust-docs`, eg: `--without=rust-docs-json-preview,rust-docs,rls-preview,rust-analyzer-preview`

**Comment by Mark-Simulacrum** [comment]
We'll aim to backport the PR for 1.67, but we didn't include it in 1.66.1, so that's not surprising that nothing changed.
