### ISSUE TITLE
how to just only build llvm when compiler rust ?

### ISSUE THREAD

**Issue by jm-observer** [rust-lang/rust#105729]
as we know, it would take a lot of time  to compiler rust, so I wanted to build it step by step. the question is how can i only build llvm first? i try to run _./x.py run src/llvm-project_, but it prompts an error.

**Comment by Dylan-DPC** [comment]
Better to ask this question on the [rust zulip](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp) stream since it will be faster and easier than here which is mainly for bug-and-feature-tracking. Thanks
