### ISSUE TITLE
Regression in rustdoc of re-export involving namespace overlap

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#105735]
```rust
// src/lib.rs

mod thing {
    pub use core::sync::atomic::AtomicU8; // anything from a dependency, type namespace

    #[allow(non_upper_case_globals)]
    pub const AtomicU8: () = (); // value namespace
}

pub use crate::thing::AtomicU8;
```

| `cargo +nightly-2022-12-02 doc` | `cargo +nightly-2022-12-03 doc` |
|---|---|
| ![Screenshot from 2022-12-14 22-02-13](https://user-images.githubusercontent.com/1940490/207784613-3097419b-22ff-4e7b-8f68-52422c73b8fe.png) | ![Screenshot from 2022-12-14 22-02-08](https://user-images.githubusercontent.com/1940490/207784638-7079382a-361b-4bb7-a542-aa396a52e877.png) |

I believe the one on the left is what I would consider the correct rendering, and the one on the right is a regression.

The regression is in nightly-2022-12-03, specifically https://github.com/rust-lang/rust/pull/104963 according to bisect, which makes sense. Mentioning @petrochenkov @cjgillot in case an obvious cause stands out to either of you.

**Comment by petrochenkov** [comment]
>in case an obvious cause stands out to either of you.

In short, rustdoc middle-end is not written well, nothing is obvious in it, and changes that are easy and predictable in rustc may lead to entirely unpredictable consequences in rustdoc.
In this specific case I investigated the affected rustdoc code just enough to make the test suite pass.

**Comment by dtolnay** [comment]
Mentioning @GuillaumeGomez who has been recently touching many of the same files modified in #104963 (for example in #103886 and #105183).
