### ISSUE TITLE
Inconsistent spacing between constants in rustdoc

### ISSUE THREAD

**Issue by y21** [rust-lang/rust#105868]
I'm not sure if this is a bug or intended behavior, but it seems like the spacing between constants is off if the constant defines a code block.

You can see this in the stdlib documentation on various types, like [here on the type `i32`](https://doc.rust-lang.org/1.66.0/std/primitive.i32.html#associatedconstant.MIN):

![image](https://user-images.githubusercontent.com/30553356/208299384-5147e159-b8bc-4fd7-9a68-675c9c7a856c.png)

In 1.65, it looked like this ([link](https://doc.rust-lang.org/1.65.0/std/primitive.i32.html#associatedconstant.MIN)):
![image](https://user-images.githubusercontent.com/30553356/208299614-4fb1d113-9ab5-4e71-af46-3ea2dcce8d5a.png)

I can also reproduce this locally: if I run `cargo doc --open` on this code:
```rs
pub struct Foo;
impl Foo {
    /// ```rust
    /// use bug::Foo;
    /// ```
    pub const BAR: u32 = 123;
    pub const BAZ: u32 = 456;
    pub const BAZ2: u32 = 789;
}
```
This happens:

![image](https://user-images.githubusercontent.com/30553356/208299200-a0abfa3b-6697-42c4-a46c-1b9e71ba332f.png)

The constant `BAZ` has less padding than the other constants.

### Meta

```
❯ rustc --version --verbose
rustc 1.66.0-nightly (5c8bff74b 2022-10-21)
binary: rustc
commit-hash: 5c8bff74bc1c52bef0c79f3689bb227f51f3e82d
commit-date: 2022-10-21
host: x86_64-unknown-linux-gnu
release: 1.66.0-nightly
LLVM version: 15.0.2
```

**Comment by GuillaumeGomez** [comment]
It was fixed in https://github.com/rust-lang/rust/pull/103793. It's currently in beta so the problem will disappear at the next release.
