### ISSUE TITLE
add mutable concurrent containers (queues, priority queues, non-contiguous vector, hashmap)

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#10580]
I'm not sure how to handle concurrent containers in the standard library. In a 1:1 threading situation, it's best to use the native mutex and condition variable types because they're highly optimized. On Linux, they only actually need to do a system call when there's contention or consumer exhaustion because they spin a bit before waiting on `futex`.

The standard library has a form of M:N queues already, but they block on the scheduler so they aren't going to work well for 1:1 threading.

https://github.com/thestinger/rust-core/blob/master/core/concurrent.rs (blocking bounded/unbounded queues and priority queues with native synchronization primitives)

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#857
