### ISSUE TITLE
docs: weak_count returns one less pointer than expected

### ISSUE THREAD

**Issue by Ranzear** [rust-lang/rust#105887]
### Location
https://doc.rust-lang.org/std/rc/struct.Weak.html#method.weak_count
https://doc.rust-lang.org/src/alloc/rc.rs.html#2388

May also apply to:
https://doc.rust-lang.org/std/sync/struct.Weak.html#method.weak_count
https://doc.rust-lang.org/src/alloc/sync.rs.html#2036

### Summary
Please clarify that `weak_count` excludes one implicit weak pointer, the one calling the function. This results in needing to check `strong_count` as well to determine whether a return of 0 is because the Rc has been dropped or simply because there is only the single weak pointer. This applies less to Arc since there is that +/- 1 uncertainty in the value returned already.

**Comment by albertlarsan68** [comment]
As shown with https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d432a62f5306b05f692af4c6a9e17eb1, there is no discrepancy, except if this is not what you was thinking about.

**Comment by Ranzear** [comment]
Alright I must be doing something weird when cloning the weak pointer. I'll look into it a bit more.
