### ISSUE TITLE
Confusing errors for `call_method(arg_name: value)` when `value` is not a literal

### ISSUE THREAD

**Issue by asquared31415** [rust-lang/rust#105810]
Given the following code: 

[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=a403cfb4749de44ff5bd40255b68d14e)
```rust
fn uwu(val: i32) {}

fn main() {
    let x = 1_i32;
    uwu(val: x);
}
```

The current output is:

```
error[E0425]: cannot find value `val` in this scope
 --> src/main.rs:5:9
  |
5 |     uwu(val: x);
  |         ^^^ expecting a type here because of type ascription

error[E0573]: expected type, found local variable `x`
 --> src/main.rs:5:14
  |
5 |     uwu(val: x);
  |              ^ expecting a type here because of type ascription
```

Ideally the output should look like it does when `value` is a literal, like an integer, float, or string literal

```
error: invalid `struct` delimiters or `fn` call arguments
 --> src/main.rs:5:5
  |
5 |     uwu(val: x);
  |     ^^^^^^^^^^^^^^^
  |
help: if `uwu` is a struct, use braces as delimiters
  |
5 |     uwu { val: x };
  |         ~        ~
help: if `uwu` is a function, use the arguments directly
  |
5 -     uwu(val: x);
5 +     uwu(x);
  |
```

Diagnostics reproduce on all of current stable, beta, and nightly:
Stable 1.66.0
Beta 1.67.0-beta.2
Nightly 1.68.0 2022-12-15

**Comment by Nilstrieb** [comment]
No one should attempt to fix this until my PR where I remove type ascription.

**Comment by fmease** [comment]
Unblocked by #109128.

@rustbot label -S-blocked

**Comment by jieyouxu** [comment]
On beta it seems to be fixed?

```rust
error: invalid `struct` delimiters or `fn` call arguments
 --> test.rs:5:5
  |
5 |     uwu(val: x);
  |     ^^^^^^^^^^^
  |
help: if `uwu` is a struct, use braces as delimiters
  |
5 |     uwu { val: x };
  |         ~        ~
help: if `uwu` is a function, use the arguments directly
  |
5 -     uwu(val: x);
5 +     uwu(x);
  |

error: aborting due to previous error
```

```
rustc 1.71.0-beta.1 (eff24c06d 2023-05-29)
binary: rustc
commit-hash: eff24c06d8f4397802b546aa2e52450e1022fc02
commit-date: 2023-05-29
host: x86_64-unknown-linux-gnu
release: 1.71.0-beta.1
LLVM version: 16.0.4
```

**Comment by Nilstrieb** [comment]
Tests:
https://github.com/rust-lang/rust/blob/617d3d6d722c432cdcbf210e6db55c3bdeafe381/tests/ui/parser/recover-from-bad-variant.rs#L8
https://github.com/rust-lang/rust/blob/617d3d6d722c432cdcbf210e6db55c3bdeafe381/tests/ui/parser/issues/issue-111416.rs#L2
https://github.com/rust-lang/rust/blob/617d3d6d722c432cdcbf210e6db55c3bdeafe381/tests/ui/parser/issues/issue-34255-1.rs#L7
