### ISSUE TITLE
[AVR] branch on .is_some() broken and inconsistent with .unwrap_or's result

### ISSUE THREAD

**Issue by gergoerdi** [rust-lang/rust#105866]
On Nightly 2022-12-09, I am observing weird behaviour when branching on `Option<u8>::is_some`, even though a subsequent `Option<u8>::unwrap_or` seems to work as expected. 

I tried to make a convincing small reproducer for this; this code started its life as an iterator, hence the maybe weird structure.

```
fn stripe(x: u8, y: u8, mask: u8) -> Option<u8> {
    if x < 1 || x >= 5 { return None };
    if y < 1 || y >= 3 { return None };

    Some(mask)
}

fn next(x: &mut u8, y: &mut u8, mask: &mut u8) -> Option<u8> {
    if *x >= 6 {
        None
    } else {
        let result = stripe(*x, *y, *mask);

        *y += 1;
        if *y >= 4 {
            *y = 0;
            *x += 1;
            if result.is_some() { *mask <<= 1 }; // HERE
        }
        Some(result.unwrap_or(0))
    }
}
```

If I start this from `x=0; y=0; mask=1;` and send out the result of `next()` over SPI, what I observe is that `mask` never changes from `1`, as if the `if result.is_some() { *mask <<= 1 }` code never ran. Note, however, that the output is only non-0 in the positions where `result.unwrap_or` would be given a `Some` value in `result`.

```
00 00 00 00
00 01 01 00
00 01 01 00
00 01 01 00
00 01 01 00
00 00 00 00
```

If I make the shift unconditional in the `HERE` line, I get the expected output:

```
00 00 00 00
00 02 02 00
00 04 04 00
00 08 08 00
00 10 10 00
00 00 00 00
```

(of course, it is not the *desired* output, since the point would be to only shift `mask` inside the middle "rectangle").

**Comment by gergoerdi** [comment]
Interestingly, the 1D version seems to work OK:

```
fn stripe(x: u8, mask: u8) -> Option<u8> {
    if x < 1 || x >= 5 { return None };

    Some(mask)
}

fn next(x: &mut u8, mask: &mut u8) -> Option<u8> {
    if *x >= 6 {
        None
    } else {
        let result = stripe(*x, *mask);

        *x += 1;
        if result.is_some() { *mask <<= 1 };

        Some(result.unwrap_or(0))
    }
}
```

This produces the expected and desired output:

```
00 01 02 04 08 00
```
```

**Comment by Patryk27** [comment]
Oh, that's interesting - analyzing 🔍

**Comment by Patryk27** [comment]
As far as I see, this `if result.is_some() {` cannot be satisfied, because it's called only when `y >= 3` (accounting for `*y += 1;`), and `stripe()` already returns `None` for that particular condition.

it "doesn't work" when compiled for x86 as well:

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=34a6b2f9b509966aba586b71189ce2be

**Comment by gergoerdi** [comment]
> As far as I see, this `if result.is_some() {` cannot be satisfied, because it's called only when `y >= 3` (accounting for `*y += 1;`), and `stripe()` already returns `None` for that particular condition slightly_smiling_face

oh my god this is embarrassing...

**Comment by Patryk27** [comment]
😇 😄 

In this case, would you mind closing the issue? I'm trying to address the AVR-related reports for rustc and since it's not strictly a bug in the code generator, it would be nice to check it out of the list 🙂
