### ISSUE TITLE
`link.exe` path issue in Windows with rust 1.65+

### ISSUE THREAD

**Issue by ebraraktas** [rust-lang/rust#105825]
First of all, I am not sure if this is the correct repository to open this issue, it may be related to `cargo` or `rustup`.

### Code

[This repository](https://github.com/ebraraktas/rust-windows-linker-path-bug) shows how to reproduce the issue. For demo, there is [a simple github action](https://github.com/ebraraktas/rust-windows-linker-path-bug/blob/main/.github/workflows/bug_demo.yaml) which [modifies the `PATH`](https://github.com/ebraraktas/rust-windows-linker-path-bug/blob/ad39239f3d1c0f5e2c8064b0cfdb7d378ff59042/.github/workflows/bug_demo.yaml#L23) and [tries to build `proc-macro2`](https://github.com/ebraraktas/rust-windows-linker-path-bug/blob/ad39239f3d1c0f5e2c8064b0cfdb7d378ff59042/.github/workflows/bug_demo.yaml#L25). 

I expected to see this happen: With rust 1.64 and older, I can build that crate successfully, as one can see from the logs of [this run](https://github.com/ebraraktas/rust-windows-linker-path-bug/actions/runs/3594901994).

Instead, this happened: With rust 1.65+, rust fails to find correct `link.exe` after the `PATH` modification, as one can see from the logs of [this run](https://github.com/ebraraktas/rust-windows-linker-path-bug/actions/runs/3594916074). I expect it to find the correct `link.exe`, as described in [this comment](https://github.com/rust-lang/rustup/issues/1455#issuecomment-459995379).

### Version it worked on

It most recently worked on: 1.64

### Version with regression

1.65

**Comment by ChrisDenton** [comment]
I'd guess that this is likely caused the "cc" crate (which rustc uses). In the case where vcvarsall is used, cc will not try to override it and instead respect its settings. This can be a problem if the environment is further modified afterward in a breaking way.

A workaround might be to switch these two lines:

```
call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
set "PATH=C:\msys64\usr\bin;%PATH%"
```

So instead it's:

```
set "PATH=C:\msys64\usr\bin;%PATH%"
call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
```

 Or just not use vcvarsall in this case.

**Comment by ebraraktas** [comment]
@ChrisDenton thanks for quick reply. The workaround you suggested helped my issue with rust 1.65. I am not familiar with Windows at all, and your explanation makes sense. 

Can I assume that this behavior is not a regression, and previous versions were not supposed to work with `PATH` modification? If that is the case, this issue can be closed.

**Comment by ChrisDenton** [comment]
Indeed, after tracking this down further it looks like there was [a bug fix](https://github.com/rust-lang/cc-rs/commit/8858713ea1592d171f8c860ce7382a2ec5ee0a44) that corrected some broken logic. So it is now working as it was intended to.
