### ISSUE TITLE
Verify signature of start lang item

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#105963]
In https://github.com/bjorn3/rustc_codegen_cranelift/issues/1329 it was found if the signature of the start lang item is wrong, rustc with the LLVM backend will silently compile it despite the ABI mismatch. Cg_clif crashes entirely. To avoid both issues rustc should validate the signature.

**Comment by asquared31415** [comment]
@rustbot claim

I have attempted to do this in the past (and never ended up finishing it), but I was not aware of the mentioned `sigpipe: u8` argument.  Where would I find information on that?

**Comment by bjorn3** [comment]
https://github.com/rust-lang/rust/pull/97802 is the PR that added it.
