### ISSUE TITLE
[type error] when wrongly destructing boxes of ints

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#105946]
Given the following code: 

```rust
#![feature(box_syntax)]
#![feature(half_open_range_patterns_in_slices)]
fn main() {
    let [_y..] = [box 1, box 2];
}
```

The current output is:

```
error[E0425]: cannot find value `_y` in this scope
 --> 4a310255aac576a3d3d7ede99bff59ef38f2fb87.rs:4:10
  |
4 |     let [_y..] = [box 1, box 2];
  |          ^^ not found in this scope

error[E0527]: pattern requires 1 element but array has 2
 --> 4a310255aac576a3d3d7ede99bff59ef38f2fb87.rs:4:9
  |
4 |     let [_y..] = [box 1, box 2];
  |         ^^^^^^ expected 2 elements

error[E0029]: only `char` and numeric types are allowed in range patterns
 --> 4a310255aac576a3d3d7ede99bff59ef38f2fb87.rs:4:10
  |
4 |     let [_y..] = [box 1, box 2];
  |          ^^ this is of type `[type error]` but it should be `char` or numeric

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0029, E0425, E0527.
For more information about an error, try `rustc --explain E0029`.
```

We shouldn't show `[type error]` here.

**Comment by lcnr** [comment]
without `box_syntax`

```rust
#![feature(half_open_range_patterns_in_slices)]
fn main() {
    let [_y..] = [Box::new(1), Box::new(2)];
}
```

**Comment by lyming2007** [comment]
What ideal output would you suggest?  Should we remove the suggestion line like:
```
error[E0308]: mismatched types
 --> 0e1a330c6631176565a0f9d144ef565d69e68583.rs:2:9
  |
2 |     return {};
  |            ^^ expected `str`, found `()`

error[E0277]: the size for values of type `str` cannot be known at compilation time
 --> 0e1a330c6631176565a0f9d144ef565d69e68583.rs:1:15
  |
1 | fn digit() -> str {
  |               ^^^ doesn't have a size known at compile-time
2 |     return {};
  |
  = help: the trait `Sized` is not implemented for `str`
  = note: the return type of a function must have a statically known size
```

**Comment by compiler-errors** [comment]
Ideally we should be checking that the return type [is suggestable](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/trait.IsSuggestable.html#tymethod.is_suggestable).

**Comment by estebank** [comment]
I actually believe that neither the E0029 nor the E0277 should have been emitted. I would check explicitly for `ty.references_error()` and change the error to be `err.delay_as_bug()` (that way the error isn't printed out, but rustc will ICE if no other error is emitted, which should have happened).

**Comment by lyming2007** [comment]
> I actually believe that neither the E0029 nor the E0277 should have been emitted. I would check explicitly for `ty.references_error()` and change the error to be `err.delay_as_bug()` (that way the error isn't printed out, but rustc will ICE if no other error is emitted, which should have happened).

The PR https://github.com/rust-lang/rust/pull/106499 will prevent E0029 and E0277 from printing out after checking the type references.
