### ISSUE TITLE
warning: crate 'Project' should have a snake case name

### ISSUE THREAD

**Issue by RolH1992** [rust-lang/rust#105941]
Hi all,

I am a novice learning Rust. The code im running is not giving errors and im getting the output I want but the warning   'Project' should have a snake case name' comes up.

How do I resolve this and what is the importance of it?

Thanks,

**Comment by albertlarsan68** [comment]
Hello,

You should have a `Cargo.toml` file, and there is a `name` field. You should change the value of this field to a snake case name, but you can also use dashes in it. In your case it should be `project`.

**Comment by meithecatte** [comment]
Please note that the rustc issue tracker is not the place to seek help with using Rust. See [the Rust Users forum](https://users.rust-lang.org/).

**Comment by JohnTitor** [comment]
Closing in favor of @meithecatte's comment, thank you for reporting anyway!
