### ISSUE TITLE
Use of &nbsp; by rustdoc makes APIs not copyable into Rust source code

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#106098]
Suppose we have this trait:

```rust
// lib.rs

pub trait Trait {
    fn method<T>()
    where
        T: Default;
}
```

Run `cargo doc`; it renders as:

<img src="https://user-images.githubusercontent.com/1940490/209411558-d45cbceb-dde3-435a-bc6d-1af4614110d0.png" width="350">

Now let's begin writing an impl of this trait:

```rust
struct MyStruct;

impl Trait for MyStruct {
}
```

and copy in the `method` method signature directly from the documentation:

```rust
struct MyStruct;

impl Trait for MyStruct {
    fn method<T>()
    where
        T: Default {}
}
```

We get this distressing error from `cargo check`:

```console
error: unknown start of token: \u{a0}
  --> src/main.rs:11:1
   |
11 |     where
   | ^
   |
help: Unicode character ' ' (No-Break Space) looks like ' ' (Space), but it is not
   |
11 |     where
   | +

error: unknown start of token: \u{a0}
  --> src/main.rs:11:2
   |
11 |     where
   |  ^
   |
help: Unicode character ' ' (No-Break Space) looks like ' ' (Space), but it is not
   |
11 |     where
   |  +

error: unknown start of token: \u{a0}
  --> src/main.rs:11:3
   |
11 |     where
   |   ^
   |
help: Unicode character ' ' (No-Break Space) looks like ' ' (Space), but it is not
   |
11 |     where
   |   +

error: unknown start of token: \u{a0}
  --> src/main.rs:11:4
   |
11 |     where
   |    ^
   |
help: Unicode character ' ' (No-Break Space) looks like ' ' (Space), but it is not
   |
11 |     where
   |    +

error: unknown start of token: \u{a0}
  --> src/main.rs:12:1
   |
12 |         T: Default {}
   | ^
   |
help: Unicode character ' ' (No-Break Space) looks like ' ' (Space), but it is not
   |
12 |         T: Default {}
   | +

error: unknown start of token: \u{a0}
  --> src/main.rs:12:2
   |
12 |         T: Default {}
   |  ^
   |
help: Unicode character ' ' (No-Break Space) looks like ' ' (Space), but it is not
   |
12 |         T: Default {}
   |  +

error: unknown start of token: \u{a0}
  --> src/main.rs:12:3
   |
12 |         T: Default {}
   |   ^
   |
help: Unicode character ' ' (No-Break Space) looks like ' ' (Space), but it is not
   |
12 |         T: Default {}
   |   +

error: unknown start of token: \u{a0}
  --> src/main.rs:12:4
   |
12 |         T: Default {}
   |    ^
   |
help: Unicode character ' ' (No-Break Space) looks like ' ' (Space), but it is not
   |
12 |         T: Default {}
   |    +

error: unknown start of token: \u{a0}
  --> src/main.rs:12:5
   |
12 |         T: Default {}
   |     ^
   |
help: Unicode character ' ' (No-Break Space) looks like ' ' (Space), but it is not
   |
12 |         T: Default {}
   |     +

error: unknown start of token: \u{a0}
  --> src/main.rs:12:6
   |
12 |         T: Default {}
   |      ^
   |
help: Unicode character ' ' (No-Break Space) looks like ' ' (Space), but it is not
   |
12 |         T: Default {}
   |      +

error: unknown start of token: \u{a0}
  --> src/main.rs:12:7
   |
12 |         T: Default {}
   |       ^
   |
help: Unicode character ' ' (No-Break Space) looks like ' ' (Space), but it is not
   |
12 |         T: Default {}
   |       +

error: unknown start of token: \u{a0}
  --> src/main.rs:12:8
   |
12 |         T: Default {}
   |        ^
   |
help: Unicode character ' ' (No-Break Space) looks like ' ' (Space), but it is not
   |
12 |         T: Default {}
   |        +
```

Hopefully there is some other way rustdoc would be able to display the same content in a way that doesn't suffer this limitation.

Is this just as simple as using `white-space: pre;` in the CSS and then writing ordinary spaces instead of &amp;nbsp;? If so, that seems definitely worthwhile doing.

**Comment by dtolnay** [comment]
For now the best workaround I've found is to **comment out** the whole copied code using a block comment:

```rust
/*
impl Trait for MyStruct {
    fn method<T>()
    where
        T: Default {}
}
*/
```

Then run `cargo fmt` which will **delete** all the U+00A0 characters (unclear whether this behavior is a rustfmt bug):

```rust
/*
impl Trait for MyStruct {
    fn method<T>()
where
T: Default {}
}
*/
```

Then you can uncomment that code:

```rust
impl Trait for MyStruct {
    fn method<T>()
where
T: Default {}
}
```

and finally run rustfmt again to get normal spaces:

```rust
impl Trait for MyStruct {
    fn method<T>()
    where
        T: Default,
    {
    }
}
```

**Comment by est31** [comment]
The behaviour in rustdoc is pretty old, it occurs at least since 1.12 (haven't checked further back).

What *is* new though is the behaviour of Firefox to translate `&nbsp;` to `U+00A0`. They changed this recently in version 103, mentioned in the [release notes](https://www.mozilla.org/en-US/firefox/103.0/releasenotes/), and the bugzilla issue is [here](https://bugzilla.mozilla.org/show_bug.cgi?id=359303). There are years-old comments however saying that Chrome had similar behaviour.

**Comment by dtolnay** [comment]
That lines up. Yes I am using Firefox, and have been copying code from rustdoc rendered documentation for years, and don't remember it being a problem until recently.

Would it be worth triaging this as a regression, due to the recent regression in user experience, despite not being caused by a code change in rustdoc?

**Comment by est31** [comment]
> Would it be worth triaging this as a regression, due to the recent regression in user experience, despite not being caused by a code change in rustdoc?

No idea really, IIRC the main purpose of those labels is to track regressions that rustc changes caused. Chromium users had the behaviour for 4+ years, maybe even since Chromium existed, so for them this is not a regression, but been the status quo.

This doesn't mean that this isn't a rustc side bug though, copying code from generated rustdoc should work. I've done it in the past myself. I usually only copy single lines however, and don't copy the indentation, so I didn't notice this change.

**Comment by est31** [comment]
More firefox issue threads:

* https://bugzilla.mozilla.org/show_bug.cgi?id=1769534
* https://bugzilla.mozilla.org/show_bug.cgi?id=1801186 is a similar bug to this one, where people complained that copy pasting code to an SQL terminal yielded in errors (as it was expecting 0x20 spaces). This should at least resolve the issues for indentation. Not sure if rustdoc emits nbsp in other situations too.
