### ISSUE TITLE
bootstrap.py doesn't work with vendoring and CARGO_HOME environment variable

### ISSUE THREAD

**Issue by mikebenfield** [rust-lang/rust#106019]
If I specify a CARGO_HOME location and put a `config` in it and try to use vendoring, bootstrap.py now fails in `check_vendored_status` due to not having a `.cargo/config`; for some reason it ignores `CARGO_HOME`. 

See [here](https://github.com/rust-lang/rust/pull/106017) for my attempt to fix this, but that fails because `cargo_dir` cannot be removed in some cases. I don't even know why it wants to remove `cargo_dir` in the first place, so maybe someone who actually understands what this code is trying to accomplish could fix it instead of me.

**Comment by bjorn3** [comment]
As https://github.com/rust-lang/rust/pull/106017 has been rejected should this issue be kept open?

**Comment by onur-ozkan** [comment]
From #106017:

> Although I still think there's something not quite right going on here, I no longer am working on the configuration with the problem, so I'm closing.
