### ISSUE TITLE
`From<usize>` missing for u64

### ISSUE THREAD

**Issue by MavenRain** [rust-lang/rust#106050]
Why doesn't `u64` implement `From<usize>`?  The transformation is infallible.

**Comment by MavenRain** [comment]
Perhaps this should be a documentation issue, given that, since it isn't clear from what is present for the `usize` that the type is intended to be perpetually forward-looking: https://doc.rust-lang.org/std/primitive.usize.html

**Comment by xfix** [comment]
This was previously brought up in #30495. The issue is that in the future we may have 128-bit CPUs where `usize` would exceed `u64`, and `From` must not fail.

**Comment by MavenRain** [comment]
Yeah, that definitely sounds right.  Thank you guys for clarifying so quickly!
