### ISSUE TITLE
`x build -h -v` panics since #104952

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#106165]
### Code

I tried this code:

```
x build --help --verbose
```

I expected to see this happen: A list of all crates that can be built.

Instead, this happened:
```
running: /home/jyn/src/rust/rust/build/bootstrap/debug/bootstrap b -h -v
thread 'main' panicked at 'metadata missing for test: {}', lib.rs:1399:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Version it worked on

It most recently worked on: https://github.com/rust-lang/rust/commit/8ad447c4791807a096b575ccba9baec2e4ec937d

### Version with regression

88c58e3c2c097ebffac425d9e080dcb1aadf790e / https://github.com/rust-lang/rust/pull/104952

### Backtrace

<details><summary>Backtrace</summary>
<p>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e080cc5a659fb760c0bc561b722a790dad35b5e1/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/e080cc5a659fb760c0bc561b722a790dad35b5e1/library/core/src/panicking.rs:65:14
   2: bootstrap::Build::in_tree_crates::{{closure}}
             at ./src/bootstrap/lib.rs:1399:67
   3: core::option::Option<T>::unwrap_or_else
             at /rustc/e080cc5a659fb760c0bc561b722a790dad35b5e1/library/core/src/option.rs:828:21
   4: bootstrap::Build::in_tree_crates
             at ./src/bootstrap/lib.rs:1399:25
   5: bootstrap::builder::ShouldRun::crate_or_deps
             at ./src/bootstrap/builder.rs:432:22
   6: <bootstrap::compile::Std as bootstrap::builder::Step>::should_run
             at ./src/bootstrap/compile.rs:57:9
   7: bootstrap::builder::Builder::get_help
             at ./src/bootstrap/builder.rs:798:26
   8: bootstrap::flags::Flags::parse::{{closure}}
             at ./src/bootstrap/flags.rs:357:25
   9: bootstrap::flags::Flags::parse
             at ./src/bootstrap/flags.rs:558:13
  10: bootstrap::config::Config::parse_inner
             at ./src/bootstrap/config.rs:849:21
  11: bootstrap::config::Config::parse
             at ./src/bootstrap/config.rs:845:9
  12: bootstrap::main
             at ./src/bootstrap/bin/main.rs:14:18
  13: core::ops::function::FnOnce::call_once
             at /rustc/e080cc5a659fb760c0bc561b722a790dad35b5e1/library/core/src/ops/function.rs:251:5
```

</p>
</details>

**Comment by jyn514** [comment]
oh, also I changed the error message locally a bit:
```diff
diff --git a/src/bootstrap/lib.rs b/src/bootstrap/lib.rs
index f84fcd21cfc..5aff33a2fb8 100644
--- a/src/bootstrap/lib.rs
+++ b/src/bootstrap/lib.rs
@@ -1400,7 +1396,7 @@ fn in_tree_crates(&self, root: &str, target: Option<TargetSelection>) -> Vec<&Cr
         let mut list = vec![INTERNER.intern_str(root)];
         let mut visited = HashSet::new();
         while let Some(krate) = list.pop() {
-            let krate = &self.crates[&krate];
+            let krate = self.crates.get(&krate).unwrap_or_else(|| panic!("metadata missing for {krate}: {:?}", self.crates));
             ret.push(krate);
             for dep in &krate.deps {
                 if !self.crates.contains_key(dep) {
```
before that change it was
```
thread 'main' panicked at 'no entry found for key', lib.rs:1400:26
```

**Comment by jyn514** [comment]
the problem is that I changed `Build::new` to avoid running `cargo metadata` for the `setup` command, but `in_tree_crates` needs that info to print the list of paths: https://github.com/rust-lang/rust/blob/5e656baf8bc832d3b77a1e49373352b3b2685fc0/src/bootstrap/lib.rs#L566-L591

**Comment by jyn514** [comment]
I don't like the options here :/ either we start updating submodules on usage: https://github.com/rust-lang/rust/blob/fca829075fd76385ac6aa7bff957e7eebbf89ae1/src/bootstrap/flags.rs#L354-L356
or we stop showing a list of all crates on `-h -v`. both of those seem unfortunate.

once again it would be really nice if cargo didn't require all submodules to be checked out to have even the slightest bit of metadata about the workspace :/

**Comment by jyn514** [comment]
I think updating the submodules is the least hacky fix here, as much as I dislike it.

**Comment by albertlarsan68** [comment]
@jyn514

I got the panic you added in #106166 on the current master, b38a6d373cb254697411147c0e49cd2e84864258, with the command `x build --help`, after having dore `x check`. Is this related?

**Comment by jyn514** [comment]
ah yes, it needs to delay calling `Builder::get_help` unless `verbose` is true.

**Comment by jyn514** [comment]
Can you open a new issue?

**Comment by albertlarsan68** [comment]
Opened at #106313
