### ISSUE TITLE
[rustfmt] Incorrect formatting for empty `where` clause on new line

### ISSUE THREAD

**Issue by BGR360** [rust-lang/rust#106108]
When you add an empty `where` clause on the line below a function signature, `rustfmt` sends the `where` token all the way to the left of the file.

The following code demonstrates the problem ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a32663de4b2f64f6bd459d0ab6c51c80)):

```rust
// Before:

#[rustfmt::skip]
mod a {
    fn f() -> ()
    where {}

    fn f() -> ()
        where {}

    fn f()
    -> ()
    where {}

    fn f() -> ()
    where {
    }

    fn f() -> ()
    where
    {
    }

    fn f() -> 
    ()
    where
    {}
}

// After:

mod a {
    fn f() -> ()
where {
    }

    fn f() -> ()
where {
    }

    fn f() -> ()
where {
    }

    fn f() -> ()
where {
    }

    fn f() -> ()
where {
    }

    fn f() -> ()
where {
    }
}
```

The issue arises regardless of whether the function is in a module, `impl` block, or nested within another function.

The issue goes away if you do any of the following:
* Remove the return type
* Add a bound to the where clause
* Put the where clause on the same line as the function signature

@rustbot label +A-rustfmt +T-dev-tools

**Comment by matthiaskrgr** [comment]
this belongs here: https://github.com/rust-lang/rustfmt

**Comment by BGR360** [comment]
Thanks. Looks like a dupe of https://github.com/rust-lang/rustfmt/issues/5407
