### ISSUE TITLE
release notes for 1.65.0 did not mention moving Error trait into core

### ISSUE THREAD

**Issue by tspiteri** [rust-lang/rust#106122]
#99917 moved `Error` into core for 1.65.0, but it was not mentioned in the release notes.

It also is confusing that the [API doc for `core::error::Error`](https://doc.rust-lang.org/core/error/trait.Error.html) says it is since 1.0.0, when it was only in std since 1.0.0.

**Comment by CryZe** [comment]
It's not stable yet.

**Comment by tspiteri** [comment]
Oh, `core::error` is marked as experimental but `core::error::Error` is marked as stable.

**Comment by dtolnay** [comment]
Changes that are only observable to nightly are almost never covered in release notes. Something is featured in release notes when it is stabilized.

Regarding "Since" version, I don't think there is any mechanism to render a different "Since" version for the same struct in two places.
