### ISSUE TITLE
Validate `triagebot.toml` in tidy/CI

### ISSUE THREAD

**Issue by compiler-errors** [rust-lang/rust#106104]
Would've prevented #106102, which broke in #105661. 

We should at least validate the toml file is valid syntax, but ideally we'd validate more context-specific stuff.

**Comment by jyn514** [comment]
Mentoring instructions: Add a new check to tidy around here that parses `triagebot.toml` to make sure it's valid: https://github.com/rust-lang/rust/blob/17395b45b102b365e6fb19796223d190b5f2bebf/src/tools/tidy/src/lib.rs#L41-L58
See the existing tidy files for an example of how to write a tidy check.

**Comment by aadityadhruv** [comment]
Hi, I'm a new contributor here and thought of picking this as my first issue. From what I understand, a new crate (something like `triagebot.rs`) needs to be made for this issue right? Where we can parse the toml and see if it is valid.

**Comment by jyn514** [comment]
@aadityadhruv a new module, not a new crate. The module should be part of `tidy` so check runs on `x test tidy`.

**Comment by aadityadhruv** [comment]
Right, that makes sense. Thank you!

**Comment by aadityadhruv** [comment]
Hi, sorry for the late response, I was out traveling. I'm currently confused about a certain thing. Currently what I am trying to do is manually check the file for valid syntax, by going over it line by line. Is this the correct method to do this, or should I be using an already existing crate like `toml`? I would assume that extra crate dependencies aren't probably wanted.

Also, I was wondering something about Path in the check function. For this module, would I need to check/filter any paths like some other modules do? I was assuming that I will simply open path + `'tiragebot.toml'` and read that file. 

Any help is appreciated!

**Comment by jyn514** [comment]
> should I be using an already existing crate like toml?

Yes, please use toml, don't use regex or anything like that.

**Comment by ehuss** [comment]
I personally would prefer to see this implemented in triagebot itself instead of tidy. That would make it work for all repositories. It should be fairly trivial to add a handler that checks for a PR that modifies triagebot.toml and to validate it, and post a comment if it is not correct. It can even use the `Config` type to verify that the actual structure matches. Bonus points would to also use [serde-ignored](https://github.com/dtolnay/serde-ignored) to enforce that unknown fields aren't included.

**Comment by pratushrai0309** [comment]
@aadityadhruv are you still working on this?

**Comment by aadityadhruv** [comment]
Hi, yeah I'm sorry, I'm still working on it. I've been pretty busy the last couple of days, I'll get it done this week itself. Hope that's ok!

**Comment by pratushrai0309** [comment]
> Hi, yeah I'm sorry, I'm still working on it. I've been pretty busy the last couple of days, I'll get it done this week itself. Hope that's ok!

Yeah! it's alright

**Comment by aadityadhruv** [comment]
> I personally would prefer to see this implemented in triagebot itself instead of tidy. That would make it work for all repositories. It should be fairly trivial to add a handler that checks for a PR that modifies triagebot.toml and to validate it, and post a comment if it is not correct. It can even use the `Config` type to verify that the actual structure matches. Bonus points would to also use [serde-ignored](https://github.com/dtolnay/serde-ignored) to enforce that unknown fields aren't included.

Sorry for being slow with the issue, but along with being busy, I've been kinda stuck, and was unsure if I should ask for help. I am currently unsure if I should be doing work in `tidy` or the `triagebot` repository. Should I first try to get the `tidy` check working and then maybe open an issue on the `triagebot` repo?

**Comment by Jviraj** [comment]
Can we update the .github/workflows/ci.yml file to call a function from lib.rs to validate triagebot.toml when a PR is made?

**Comment by aadityadhruv** [comment]
Here is the code I had written (it does not work since I do not know what the configuration of the toml is):

```
use crate::walk::{filter_dirs, walk};
use serde::Deserialize;
use std::path::Path;

#[derive(Deserialize)]
struct Config {}

pub fn check(path: &Path, bad: &mut bool) {
    walk(path, &mut |path| filter_dirs(path), &mut |entry, contents| {
        let file = entry.path();
        let filename = file.file_name().unwrap();
        if filename != "triagebot.toml" {
            return;
        }
        let conf: Result<Config, toml::de::Error> = toml::from_str(contents);
        match conf {
            Ok(_) => {}
            Err(_err) => {
                tidy_error!(bad, "{} is an invalid toml file", file.display())
            }
        }
    });
}
```
I am unsure what would be the right next step here.

**Comment by madsravn** [comment]
Hi  @aadityadhruv . I am new here and just looking through for an issue I can get started with. So keeping that in mind, here is my idea.

If you at the [documentation for for the toml crate](https://docs.rs/toml/0.5.10/toml/#parsing-toml) there is a method where you can just parse an entire string to a `toml::Value`. This `Value` is an enum for the entire toml structure. My idea is that if you can parse the `triagebot.toml` it is correct toml and you have validated the file. 

My very short code is here:

```
use toml::Value;

fn main() {
    let input = std::fs::read_to_string("triagebot.toml").unwrap();
    let value = input.parse::<Value>().unwrap();
    println!("{value}");
}
```

I hope it helps.

**Comment by aadityadhruv** [comment]
This looks great! Thank you!

**Comment by aadityadhruv** [comment]
Here is a PR for the same: https://github.com/rust-lang/rust/pull/106559

**Comment by jyn514** [comment]
> I personally would prefer to see this implemented in triagebot itself instead of tidy. That would make it work for all repositories. It should be fairly trivial to add a handler that checks for a PR that modifies triagebot.toml and to validate it, and post a comment if it is not correct. It can even use the `Config` type to verify that the actual structure matches. Bonus points would to also use [serde-ignored](https://github.com/dtolnay/serde-ignored) to enforce that unknown fields aren't included.

👍 https://github.com/rust-lang/rust/pull/106559#issuecomment-1376519719

**Comment by BoxyUwU** [comment]
Just thought I'd drop by and say that this would have been nice to avoid #106848 :sweat_smile:

**Comment by jyn514** [comment]
Ah, that wouldn't have been caught actually - the toml syntax was valid, the file just didn't exist in the repository. Checking if the glob has at least one match seems possible.

**Comment by 0xJepsen** [comment]
I see the PR up but not sure if anyone is still working on the requested changes?

**Comment by aadityadhruv** [comment]
Yeah I'm currently working on it in the triagebot repo, I haven't opened a PR/Issue yet for it.

**Comment by meysam81** [comment]
Can someone please review this change: rust-lang/triagebot#1730
