### ISSUE TITLE
`x fmt` tries to format non-rust files

### ISSUE THREAD

**Issue by Nilstrieb** [rust-lang/rust#106261]
```
formatting modified file compiler/rustc_error_messages/locales/en-US/borrowck.ftl
error: unknown start of token: `
 --> /home/nilsh/projects/rust/compiler/rustc_error_messages/locales/en-US/borrowck.ftl:2:33
  |
2 |     cannot move a value of type `{$ty}`
  |                                 ^
  |
help: Unicode character '`' (Grave Accent) looks like ''' (Single Quote), but it is not
  |
2 |     cannot move a value of type '{$ty}`
  |                                 ~

error: unknown start of token: `
```

When there was a change in a `.ftl` or other non-rust file, bootstrap tries to format it, which makes rustfmt very sad.

cc @albertlarsan68 and @jyn514 who broke this in #105702

**Comment by jyn514** [comment]
I think we just need to filter .rs files before passing them to rustfmt.

**Comment by Nilstrieb** [comment]
This will probably be hit a lot by contributors so I'll pin it for better visibility.

**Comment by albertlarsan68** [comment]
Normally, the walker already filters for `.rs` files, per https://docs.rs/ignore/latest/ignore/struct.WalkBuilder.html. Maybe the `ignore` crate docs are not fully up to date, or I didn't understand them correctly.

**Comment by albertlarsan68** [comment]
The workaround is to run `x fmt .` (notice the dot at the end of the command).

**Comment by chenyukang** [comment]
I think if we add it like this:
```rust
ignore_fmt.add(&format!("!/{}", untracked_path)).expect(&untracked_path);
```

`ignore` will always not ignore it anymore.

**Comment by albertlarsan68** [comment]
Maybe try to put the part I added before the ignore part, maybe this makes the ignore list work again?

The thing that intrigues me the most is the face that the `.stderr` files are not ignored later by the file type filter.

**Comment by chenyukang** [comment]
For any Rust files we changed locally, our current solution will try to format it, in some scenarios we may not want to format it, such as some files in UI?

**Comment by chenyukang** [comment]
> Maybe try to put the part I added before the ignore part, maybe this makes the ignore list work again?
> 
> The thing that intrigues me the most is the face that the `.stderr` files are not ignored later by the file type filter.

Seems right, my current fix is not completed.

**Comment by jyn514** [comment]
> 

I think since you explicitly add the files to `ignore_fmt`, that overrides the types filter.

**Comment by chenyukang** [comment]
from my local lab, seems `rustfmt.toml` is still expected, I changed some files which ignored in `rustfmt.toml`, they are actually not sent to formater:

```console
cat@LAPTOP-V6U0QKD4:~/code/rust$ x fmt
Building rustbuild
   Compiling bootstrap v0.0.0 (/home/cat/code/rust/src/bootstrap)
    Finished dev [unoptimized] target(s) in 5.25s
formatting modified file library/portable-simd/crates/core_simd/src/vendor/arm.rs
formatting modified file src/bootstrap/format.rs
formatting modified file src/tools/miri/src/bin/miri.rs
really try to format: DirEntry { dent: Raw(DirEntryRaw { path: "/home/cat/code/rust/src/bootstrap/format.rs", follow_link: false, depth: 3 }), err: None }
Build completed successfully in 0:00:07
```

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23106261.20.60x.20fmt.60.20tries.20to.20format.20non-rust.20files)).

@rustbot label -I-prioritize +P-high
