### ISSUE TITLE
regression: anonymous lifetimes now unstable in impl trait

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#106338]
* https://crater-reports.s3.amazonaws.com/beta-1.67-2.4/beta-2022-12-29/reg/hltas-0.6.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.67-2.4/beta-2022-12-29/reg/monch-0.4.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.67-2.4/beta-2022-12-29/reg/hltas-0.6.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.67-2.4/beta-2022-12-29/gh/shff.paq/log.txt

cc https://github.com/rust-lang/rust/pull/104048 as possible root cause, @cjgillot

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23106338.20regression.3A.20anonymous.20lifetimes.20now.20unstable.20in.20imp.E2.80.A6)).

@rustbot label -I-prioritize +P-critical
