### ISSUE TITLE
Borrow checker error on nightly even when the type is `'static`

### ISSUE THREAD

**Issue by NobodyXu** [rust-lang/rust#106332]
Compiling the [`binstalk`](https://github.com/cargo-bins/cargo-binstall/tree/bin/minor-opt) from https://github.com/cargo-bins/cargo-binstall/pull/646 failed on nightly due to lifetime error while it works on stable.

The code in question looks like this and is in taken from [crates/binstalk/src/fetchers/gh_crate_meta.rs](https://github.com/cargo-bins/cargo-binstall/blob/bin/minor-opt/crates/binstalk/src/fetchers/gh_crate_meta.rs)

```rust
pub struct GhCrateMeta {
    client: Client,
    data: Arc<Data>,
    target_data: Arc<TargetData>,
    resolution: OnceCell<(Url, PkgFmt)>,
}

type FindTaskRes = Result<Option<(Url, PkgFmt)>, BinstallError>;

impl GhCrateMeta {
    fn launch_baseline_find_tasks<'a>(
        &'a self,
        pkg_fmt: PkgFmt,
        pkg_url: &'a str,
        repo: Option<&'a str>,
    ) -> impl Iterator<Item = impl Future<Output = FindTaskRes> + 'static> + 'a {
        todo!()
    }

    fn find(self: Arc<Self>) -> AutoAbortJoinHandle<Result<bool, BinstallError>> {
        AutoAbortJoinHandle::spawn(async move {
            // ...
            let mut handles = FuturesUnordered::new();

            // Iterate over pkg_urls to avoid String::clone.
            for pkg_url in pkg_urls {
                //             Clone iter pkg_fmts to ensure all pkg_fmts is
                //             iterated over for each pkg_url, which is
                //             basically cartesian product.
                //             |
                for pkg_fmt in pkg_fmts.clone() {
                    handles.extend(this.launch_baseline_find_tasks(pkg_fmt, &pkg_url, repo));
                }
            }

            todo!()
        })
    }
```

On nightly, this failed with:

```
error[E0597]: `pkg_url` does not live long enough
   --> crates/binstalk/src/fetchers/gh_crate_meta.rs:147:77
    |
147 |                     handles.extend(this.launch_baseline_find_tasks(pkg_fmt, &pkg_url, repo));
    |                                                                             ^^^^^^^^ borrowed value 
does not live long enough
148 |                 }
149 |             }
    |             - `pkg_url` dropped here while still borrowed
...
160 |         })
    |         - borrow might be used here, when `handles` is dropped and runs the `Drop` code for type `Fu
turesUnordered`
    |
    = note: values in a scope are dropped in the opposite order they are defined

For more information about this error, try `rustc --explain E0597`.
error: could not compile `binstalk` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `binstalk` due to previous error
```

### Meta

`rustc +nightly --version --verbose`:
```
rustc 1.68.0-nightly (ce85c9857 2022-12-30)
binary: rustc
commit-hash: ce85c98575e3016cf2007d90a85be321e592aa96
commit-date: 2022-12-30
host: aarch64-apple-darwin
release: 1.68.0-nightly
LLVM version: 15.0.6
```

**Comment by clubby789** [comment]
searched nightlies: from nightly-2022-12-06 to nightly-2022-12-10
regressed nightly: nightly-2022-12-10
searched commit range: https://github.com/rust-lang/rust/compare/7632db0e87d8adccc9a83a47795c9411b1455855...dfe3fe710181738a2cb3060c23ec5efb3c68ca09
regressed commit: https://github.com/rust-lang/rust/commit/b359ccf1b0b7b2d2c1c4932344b806e68bd053a9

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.5</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start 2022-12-6 --end 2022-12-10 
```
</details>

@rustbot labels -E-needs-bisection

**Comment by lukas-code** [comment]
searched nightlies: from nightly-2022-12-09 to nightly-2022-12-27
regressed nightly: nightly-2022-12-10
searched commit range: https://github.com/rust-lang/rust/compare/7632db0e87d8adccc9a83a47795c9411b1455855...dfe3fe710181738a2cb3060c23ec5efb3c68ca09
regressed commit: https://github.com/rust-lang/rust/commit/7701a7e7d4eed74a106f39fa64899dffd1e1025f (https://github.com/rust-lang/rust/pull/105456)

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.4</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --regress=error -- check 
```
</details>


Maybe its https://github.com/rust-lang/rust/pull/105317?

**Comment by clubby789** [comment]
Sorry, false positive in bisect
@rustbot labels +E-needs-bisection

**Comment by lqd** [comment]
You can manually bisect the PRs in that rollup, https://github.com/rust-lang/rust/pull/105456#issuecomment-1343907798 contains the list of each of their artifacts.

I'd start by looking at https://github.com/rust-lang/rust/pull/105255 though.

**Comment by lukas-code** [comment]
Yep, it's https://github.com/rust-lang/rust/pull/105255. cc @cjgillot @compiler-errors

**Comment by Mark-Simulacrum** [comment]
Possible other examples from beta crater:

* https://crater-reports.s3.amazonaws.com/beta-1.67-2.4/beta-2022-12-29/reg/paxakos-0.13.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.67-2.4/beta-2022-12-29/reg/netidx-0.12.4/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.67-2.4/beta-2022-12-29/reg/spaad_internal-0.4.0/log.txt

**Comment by NobodyXu** [comment]
Any update on this?

I've tested the code on:

```
rustc 1.68.0-nightly (659e169d3 2023-01-04)
binary: rustc
commit-hash: 659e169d37990b9c730a59a96081f2ef7afbe8f1
commit-date: 2023-01-04
host: aarch64-apple-darwin
release: 1.68.0-nightly
LLVM version: 15.0.6
```

and it still faied.

**Comment by apiraino** [comment]
@NobodyXu AFAICS your bug report has been acknowledged and has an assignee, looks like it's a regression in the beta channel ([comment](https://github.com/rust-lang/rust/issues/106332#issuecomment-1368297884)). The new stable will be out in a few weeks, might be fixed by then.

**Comment by NobodyXu** [comment]
> @NobodyXu AFAICS your bug report has been acknowledged and has an assignee, looks like it's a regression in the beta channel ([comment](https://github.com/rust-lang/rust/issues/106332#issuecomment-1368297884)). The new stable will be out in a few weeks, might be fixed by then.

Thanks, so looks like it's going to take quite some time.
I might go ahead and release `cargo-binstall` without waiting for this one.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23106332.20Borrow.20checker.20error.20on.20nightly.20even.20when.20the.20type.20.E2.80.A6)).

@rustbot label -I-prioritize +P-high
