### ISSUE TITLE
Borrow checker thinks self is not mutable, when it is.

### ISSUE THREAD

**Issue by Nordgaren** [rust-lang/rust#106325]
I am trying to extend ByteOrder + Seek, and I have two traits, right now. The first is just extending ByteOrder, and the second extends ByteOrder + Seek

```rust

pub trait BinaryReader: ReadBytesExt {
     fn read_bytes(&mut self, size: usize) -> std::io::Result<Vec<u8>> {
        let mut buf = vec![0u8; size];
        self.read_exact(&mut buf[..])?;
        Ok(buf)
    }
    
    //other methods
}

impl<R: ReadBytesExt> BinaryReader for R {}

pub trait BinaryPeeker: ReadBytesExt + Seek {
   fn peek_bytes(&mut self, size: usize, position: u64) -> std::io::Result<Vec<u8>> {
        let start = self.stream_position()?;
        self.seek(SeekFrom::Start(position))?;
        let bytes = self.read_bytes(size);
        self.seek(SeekFrom::Start(start))?;
        return bytes;
    }
    
    //other methods
}
```
For some reason, I get this error when compiling, and it only occurs on the line with read_bytes.

```
  --> src\binary_reader.rs:60:21
   |
60 |         let bytes = self.read_bytes(size);
   |                     ^^^^^^^^^^^^^^^^^^^^^ cannot borrow as mutable

```

There are two ways I can work around this, for now. One is by copying the `read_bytes` method into the other trait, which I don't really wanna do, or I found this goofy code will also work...

```rust
    fn peek_bytes(&mut self, size: usize, position: u64) -> std::io::Result<Vec<u8>> {
        let mut s = self;
        let start = s.stream_position()?;
        s.seek(SeekFrom::Start(position))?;
        let bytes = s.read_bytes(size);
        s.seek(SeekFrom::Start(start))?;
        return bytes;
    }
```

Hopefully this helps clue you in on what is going on.

Is this a bug with the borrow checker?

### Meta

`rustc --version --verbose`:
```
rustc 1.66.0 (69f9c33d7 2022-12-12)
binary: rustc
commit-hash: 69f9c33d71c871fc16ac445211281c6e7a340943
commit-date: 2022-12-12
host: x86_64-pc-windows-msvc
release: 1.66.0
LLVM version: 15.0.2
```

<details><summary>Backtrace</summary>
<p>

```
No additional info from setting the environment variable. I suspect it's because BACKTRACE doesn't deal with the borrow checker?
```

</p>
</details>

**Comment by SkiFire13** [comment]
I tried reproducing your issue in [this playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=abffe12d6a70665267eabf7cd8e33397) and this is the error I got:

```
error[[E0599]](https://doc.rust-lang.org/stable/error-index.html#E0599): the method `read_bytes` exists for mutable reference `&mut Self`, but its trait bounds were not satisfied
  --> src/lib.rs:21:26
   |
21 |         let bytes = self.read_bytes(size);
   |                          ^^^^^^^^^^
   |
note: trait bound `Self: Sized` was not satisfied
  --> src/lib.rs:15:6
   |
15 | impl<R: ReadBytesExt> BinaryReader for R {}
   |      ^                ------------     -
   |      |
   |      unsatisfied trait bound introduced here
note: trait bound `&mut Self: ReadBytesExt` was not satisfied
  --> src/lib.rs:15:9
   |
15 | impl<R: ReadBytesExt> BinaryReader for R {}
   |         ^^^^^^^^^^^^  ------------     -
   |         |
   |         unsatisfied trait bound introduced here
help: consider relaxing the type parameter's implicit `Sized` bound
   |
15 | impl<R: ?Sized + ReadBytesExt> BinaryReader for R {}
   |         ++++++++
help: consider relaxing the type parameter's implicit `Sized` bound
   |
15 | impl<R: ?Sized + ReadBytesExt> BinaryReader for R {}
   |         ++++++++
```

It doesn't complain about mutability though, but rather about a `Sized` bound (which is implied in the implementation of `BinaryReader` but not in the one of `BinaryPeeker`. The diagnostic also suggests a way to fix the issue, with other alternatives being adding a `Sized` supertrait to `BinarySeeker` or a `where Self: Sized` constraint to `peek_bytes`, although both seem non-ideal.

**Comment by clubby789** [comment]
Adding `: Sized` to your supertraits list is probably the best solution. The underlying issue is #93078

**Comment by Nordgaren** [comment]
> The underlying issue is #93078. The cleanest solution is changing your blanket impl to `impl<R: ReadBytesExt+?Sized> BinaryReader for R {}`, propagating up the `?Sized` bound from `Read` and `ReadBytesExt`
> 
> @rustbot label +A-diagnostics

That does fix it, yea. I only have to add ?Sized to the first trait. Should I add it to all of these traits, or I will encounter this again? I am new to rust, and still not entirely sure what this means, or what it means for my trait.

Thanks!
