### ISSUE TITLE
Uninitialized variables when using try trait for early return.

### ISSUE THREAD

**Issue by kagia** [rust-lang/rust#106377]
The compiler doesn't seem to be detecting early returns from the try operator when doing analysis for possibly-uninitialized variables.

I tried this code:

```rust
use std::error::Error;

fn bug() -> Result<usize, Box<dyn Error>> {
    let result;

    if 1 < 4 {
        result = 4;
    } else {
        Err("bla")?;
    }

    Ok(result)
}
```

I expected to see this happen:
The code should compile.
 - the `?` operator to desugar into an early return.
 - the compiler should see that the variable is only used when initialised.

Instead, this happened:
The code did not compile
- error[E0381]: used binding `result` is possibly-uninitialized
- adding a return statement to the error allows the code to compile

### Meta

`rustc --version --verbose`:
```
 rustc 1.68.0-nightly
```

also tested on stable:
```
rustc 1.66.0 (69f9c33d7 2022-12-12)
```

<details><summary>Backtrace</summary>
<p>

```
error[E0381]: used binding `result` is possibly-uninitialized
  --> src/main.rs:14:8
   |
6  |     let result;
   |         ------ binding declared here but left uninitialized
...
10 |     } else {
   |      ------ if the `if` condition is `false` and this `else` arm is executed, `result` is not initialized
...
14 |     Ok(result)
   |        ^^^^^^ `result` used here but it is possibly-uninitialized

For more information about this error, try `rustc --explain E0381`.
error: could not compile `branch-bug` due to previous error
```

</p>
</details>

**Comment by Nilstrieb** [comment]
Your code actually (roughly) desugars to
```rust
fn bug() -> Result<usize, Box<dyn Error>> {
    let result;

    if 1 < 4 {
        result = 4;
    } else {
        match Err("bla") {
            Ok(x) => x,
            Err(err) => return err.into(),
        }
    }

    Ok(result)
}
```
The compiler does not know that the `Err("bla")` case will always match the `Err` arm, it also has to consider that the `Ok(x)` arm may match, in which case `result` would indeed by uninitialized. We of course know that this cannot happen but when the compiler is analyzing the initializedness of variables, it cannot know that.

**Comment by kagia** [comment]
Interesting..

I was hoping since we're matching against a literal rather than an identifier, that the static initialization analysis would have enough information to identify the unreachable branch.

However I see that such optimization doesn't also happen for the `if 1 < 4 { ...}`  statement. So this is consistent behavior.

This is more of a feature request, than a bug.

Thank you @Nilstrieb
