### ISSUE TITLE
Higher kinded checks are deferred to the time of use

### ISSUE THREAD

**Issue by HKalbasi** [rust-lang/rust#106426]
In this code I will get a compiler error:
```Rust
struct F where i32: Iterator;
```
```
error[[E0277]](https://doc.rust-lang.org/stable/error-index.html#E0277): `i32` is not an iterator
 --> src/main.rs:2:20
  |
2 |     struct F where i32: Iterator;
  |                    ^^^^^^^^^^^^^ `i32` is not an iterator
  |
  = help: the trait `Iterator` is not implemented for `i32`
  = note: if you want to iterate between `start` until a value `end`, use the exclusive range syntax `start..end` or the inclusive range syntax `start..=end`
  = help: see issue #48214
```
But in this code there is no compiler error:
```
struct F where for<'a> &'a i32: 'static;
```

But if I use `F`, I will get a compiler error:
```Rust
struct F where for<'a> &'a i32: 'static;
let _x = F;
```
```
error: higher-ranked lifetime error
 --> src/main.rs:4:14
  |
4 |     let _x = F;
  |              ^
  |
  = note: could not prove `for<'a> &'a i32: 'static`

error: could not compile `playground` due to previous error
```
Which is inconsistent behavior. I think either both of them should compile, or both of them should not.

**Comment by compiler-errors** [comment]
This comment perhaps sheds some light on this inconsistency being (somewhat) intentional: https://github.com/rust-lang/rust/pull/100090#issuecomment-1229543855

**Comment by HKalbasi** [comment]
So after feature `trivial_bounds` it will become a warning for both cases?

**Comment by QuineDot** [comment]
With `trivial_bounds`, the `Iterator` case would behave similar to the higher-ranked case (able to compile the definition but not to call it due to unsatisfiable bounds).  And I believe the idea is both would warn about the unsatisfiable definition, yes.
