### ISSUE TITLE
Notable traits tooltip is underneath part of the page's text

### ISSUE THREAD

**Issue by BenJeau** [rust-lang/rust#106445]
Content of the page overlays the tooltip. Small observation, not _all_ text goes over it, e.g. the "Read more" of the `clone()` function is properly underneath the tooltip.

Here's an example at the following doc page https://doc.rust-lang.org/std/iter/struct.Zip.html, tested in Firefox, Chrome, and Safari on MacOS 13.1

<img width="993" alt="Screenshot 2023-01-03 at 8 23 35 PM" src="https://user-images.githubusercontent.com/22248828/210467799-f56d03cd-61c7-44a7-b743-c30e958eb21a.png">

**Comment by Nemo157** [comment]
This appears to be fixed already in beta, previously reported as https://github.com/rust-lang/rust/issues/102576
