### ISSUE TITLE
1.66 regression -- non-optimized compiler-builtins by default

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#106471]
We missed backporting https://github.com/rust-lang/rust/pull/103732 to 1.66, so for 1.66 only the bad behavior is still there.

If we do have a point release let's try and include the revert there.

cc @pietroalbini

**Comment by apiraino** [comment]
@Mark-Simulacrum I think this will probably land on the next stable without backport (see [zulip](https://rust-lang.zulipchat.com/#narrow/stream/241545-t-release/topic/1.2E66.2E1)). So probably I'd remove I-prioritize (or maybe close the the issue, idk).

@rustbot label -I-prioritize

**Comment by Enselic** [comment]
Triage: No objections to the proposal to close, so let's close.
