### ISSUE TITLE
Cannot use where clauses in a tuple struct 

### ISSUE THREAD

**Issue by gamma-delta** [rust-lang/rust#106439]
I tried this code:

```rust
trait MyTrait {}

struct Foo<T> where T: MyTrait, (T)
```

I expected to see this happen: It compiles and requires T to implement MyTrait

Instead, this happened: It doesn't compile

### Meta

`rustc --version --verbose`:
```
rustc 1.67.0-nightly (83356b78c 2022-11-17)
binary: rustc
commit-hash: 83356b78c4ff3e7d84e977aa6143793545967301
commit-date: 2022-11-17
host: x86_64-unknown-linux-gnu
release: 1.67.0-nightly
LLVM version: 15.0.4

```

<details><summary>"Backtrace" (compiler error)</summary>
<p>

```
error: expected one of `:`, `==`, or `=`, found `;`
 --> src/lib.rs:3:36
  |
3 | struct Foo<T> where T: MyTrait, (T);
  |                                    ^ expected one of `:`, `==`, or `=`
```
[Playground Link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d41556136ef183a9e763f051d1927ec1)

</p>
</details>

**Comment by clubby789** [comment]
The correct syntax for this is `struct Foo<T>(T) where T: MyTrait;`

**Comment by fmease** [comment]
With the label <kbd>A-diagnostics</kbd> added, this becomes a duplicate of #100790.

**Comment by gamma-delta** [comment]
Can I just say this is one of the reasons I love the Rust project? Instead of getting some blunt "you're doing it wrong" you take the time to understand why I'm doing it wrong, and how to fix it for everyone. :)

**Comment by gamma-delta** [comment]
(Oh, I guess I should close this then if it's a duplicate)
