### ISSUE TITLE
Back button doesn't work from error_codes/error-index.html

### ISSUE THREAD

**Issue by matthagan15** [rust-lang/rust#106485]
Was looking thought the doc.rust-lang.org site to see what was new and looked at the compiler error codes page. when trying to navigate back to the main site by pressing back it simply flashes "if you are not redirected please ..." and then immediately goes back to error_codes/error-index.html. Pretty easy to repro, can provide more detail if needed!

**Comment by Ezrashaw** [comment]
I've seen this before, there is a redirect from `/error-index.html` to `error_codes/error-index.html` which causes this behavior. The error index is a bit of a bodge; technically it's a `mdBook` but it also has its own helper script at `src/tools/error_index_generator/`. I'm not really sure that this is fixable, maybe we could try to remove links to the redirect but I'm not sure that would help.

**Comment by ehuss** [comment]
I think there is an easy fix here, I'll post a PR.
