### ISSUE TITLE
Error installing rust

### ISSUE THREAD

**Issue by zx9r** [rust-lang/rust#106513]
As recommended in the project README, book (https://doc.rust-lang.org/book/ch01-01-installation.html) and at https://www.rust-lang.org/tools/install

> $ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
> info: downloading installer
> curl: (23) Failure writing output to destination
> rustup: command failed: downloader https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init /tmp/tmp.Ovyar546P7/rustup-init x86_64-unknown-linux-gnu

Directory /tmp/tmp.Ovyar546P7 is created but empty

System is Ubuntu 22.04

**Comment by clubby789** [comment]
Looks like curl had an internal error trying to save the file.  Does this happen repeatedly if you rerun the command? Have you checked that you have sufficient free disk space?

**Comment by zx9r** [comment]
Yes, it happens repeatedly. It creates a new /tmp/tmp.xxx directory and leaves it empty.

More than enought free disk space, about 400 GB
