### ISSUE TITLE
A potential ambiguity concerning the alternate wording and the example usage of `HashSet::retain`.

### ISSUE THREAD

**Issue by aalekhpatel07** [rust-lang/rust#106535]
### Location

Lines 310-321 of [`std/collections/hash/set.rs`](https://doc.rust-lang.org/src/std/collections/hash/set.rs.html#310-321)

### Summary

The alternate (and presumably simpler) wording says
 > "In other words, remove all elements `e` for which `f(&e)` returns `false`."
 
but the example usage in the doc comment would've compiled just fine even if we accidentally misread/misinterpreted that as "... returns `true`" (since the count of removed and retained items are equal):
```rust
let mut set = HashSet::from([1, 2, 3, 4, 5, 6]);
set.retain(|&k| k % 2 == 0);
assert_eq!(set.len(), 3);
```

To demonstrate that exactly only the `false` elements are filtered out we could potentially change the example so that it fits better with the alternate definition:

```rust
let mut set = HashSet::from([1, 2, 3, 4, 5, 6, 7]);
set.retain(|&k| k % 2 == 0);
assert_eq!(set.len(), 3);
```

**Comment by compiler-errors** [comment]
Alternatively, since `HashSet` implements `PartialEq`, this is even more clear:

```rust
use std::collections::HashSet;

fn main() {
    let mut set = HashSet::from([1, 2, 3, 4, 5, 6]);
    set.retain(|&k| k % 2 == 0);
    assert_eq!(set, HashSet::from([2, 4, 6]));
}
```
