### ISSUE TITLE
Compiler stops autodereferencing type to resolve trait once type type implements trait with unrelated generic parameters

### ISSUE THREAD

**Issue by KevinThierauf** [rust-lang/rust#106510]
The following is a minimal code sample that showcases the present issue:

```rust
// some trait
trait SomeTrait<T> {
    fn do_stuff(&self, value: T);
}

struct Structure;

impl<T> SomeTrait<T> for Structure {
    fn do_stuff(&self, _: T) {
        println!("generic");
    }
}

// some example types
struct A;
struct B;
struct C;

// implement SomeTrait<A> on &Structure, not Structure (autoderef specialization)
impl SomeTrait<A> for &Structure {
    fn do_stuff(&self, _: A) {
        println!("specialized TraitA");
    }
}

// same as before, but for SomeTrait<C> instead of SomeTrait<A>
impl SomeTrait<C> for &Structure {
    fn do_stuff(&self, _: C) {
        println!("specialized TraitC");
    }
}

let structure = Structure;
let tmp = &structure; // tmp is &Structure
let tmp = &tmp; // tmp is &&Structure
tmp.do_stuff(A); // will call specialized TraitA version
tmp.do_stuff(C); // will call specialized TraitC version

tmp.do_stuff(B); // should call generic version, compiler error if SomeTrait<A> or SomeTrait<C> is implemented, compiles if neither definitions are provided
```

The compiler incorrectly (I believe) fails with this example. Notably, the call to ```tmp.do_stuff(B);``` is the only line that fails. If the impl of ```SomeTrait<A>``` and ```SomeTrait<C>``` are removed for &Structure, the ```tmp.do_stuff(B);``` DOES work -- the call to ```tmp.do_stuff(B);``` is not ambiguous; the impl of ```SomeTrait<A>``` and ```SomeTrait<B>``` do not apply, as the compiler notes. Instead, it appears that, once the compiler sees that a version of ```SomeTrait``` is defined (even one that does not apply) it stops the autodereferencing that would otherwise occur. The following error message explains this pretty clearly:

```
error[E0277]: the trait bound `&example::Structure: SomeTrait<B>` is not satisfied
  --> src/example.rs:79:18
   |
79 |     tmp.do_stuff(B); // should call generic version, fails if SomeTrait<A> or SomeTrait<C> is implemented
   |         -------- ^ the trait `SomeTrait<B>` is not implemented for `&example::Structure`
   |         |
   |         required by a bound introduced by this call
   |
   = help: the following other types implement trait `SomeTrait<T>`:
             <&example::Structure as SomeTrait<A>>
             <&example::Structure as SomeTrait<C>>
             <example::Structure as SomeTrait<T>>
```

The expectation is that the autoderef rules should apply here. The compiler notes that ```&Structure``` does not implement ```SomeTrait<B>```, which is true. Normally, this would mean that ```&Structure``` is dereferenced, and the compiler checks if ```SomeTrait<B>``` is implemented for ```Structure``` instead. In this case, however, this does not seem to happen. Since the compiler notes that there are definitions of ```SomeTrait``` with other generic parameters (```A``` and ```C```, but not ```B```) on ```&Structure```, it fails instead of checking the dereferenced types. As I understand it, a trait with two sets of generic parameters are two completely different traits. That is, ```SomeTrait<A>```, ```SomeTrait<B>```, and ```SomeTrait<C>``` are all different traits, and as such, the definition of ```SomeTrait<A>``` or ```SomeTrait<C>``` should not prevent autodereferencing.

In essence, I believe that this example should compile, with the final call using the ```impl<T> SomeTrait<T> for Structure``` implementation by dereferencing &Structure, instead of failing once the ```SomeTrait<A>``` and ```SomeTrait<C>``` definitions are found on ```Structure``` as they are unrelated.

### Meta
I've checked this behavior on both stable and nightly, with the same results on both versions.

`rustc --version --verbose`:
```
rustup 1.25.1 (bb60b1e89 2022-07-12)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.68.0-nightly (659e169d3 2023-01-04)
```

**Comment by compiler-errors** [comment]
I'm pretty sure this is because method selection does not take argument types into account.

When we're probing for methods, we consider both impls for `&Structure` equally, so that's why `A` and `C` both work. But since `B` is essentially shadowed by those two methods in the order of autoderef, we never consider it.

**Comment by KevinThierauf** [comment]
> I'm pretty sure this is because method selection does not take argument types into account.
> 
> When we're probing for methods, we consider both impls for `&Structure` equally, so that's why `A` and `C` both work. But since `B` is essentially shadowed by those two methods in the order of autoderef, we never consider it.

I think you're right -- I did a bit of experimenting and found an example that shows this:

```rust
trait SomeTrait<T> {
    fn do_stuff(&self, value: T);
}

struct Structure;

impl Structure {
    fn do_stuff(&self, _: B) {
    }
}

// some example types
struct A;
struct B;
struct C;

impl SomeTrait<A> for &Structure {
    fn do_stuff(&self, _: A) {
    }
}

impl SomeTrait<C> for &Structure {
    fn do_stuff(&self, _: C) {
    }
}

let structure = Structure;
let tmp = &structure; // tmp is &Structure
let tmp = &tmp; // tmp is &&Structure
tmp.do_stuff(A);
tmp.do_stuff(C);

tmp.do_stuff(B); // compiler error
```

If I understand what you're saying, the compiler sees that there is a function named ```do_stuff()``` available for ```&Structure```, and tries to call it, only after which it finds out that it is invalid. Even though there is another ```do_stuff()``` definition (under ```Structure```), the compiler does not see it since it stops autodereferencing once a function called ```do_stuff()``` is found at the current reference level (```&Structure```).

**Comment by KevinThierauf** [comment]
Talked to some people in the discord channel, and this probably isn't a bug (looking at the arguments takes place after the method is selected).
