### ISSUE TITLE
maybe expose a way to pass pre-calculated hashes along with hash table keys

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#10661]
I found this was necessarily to avoid double-hashing with a shard-based concurrent hash table like Java's `ConcurrentHashMap` as the hash needs to be calculated to pick the correct shard.

https://github.com/thestinger/rust-core/blob/master/core/concurrent.rs#L299

This could be done by hoisting out the open-addressing implementation, but it will result in it *requiring* the hashes to be stored in the table rather than it just being an implementation detail.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#794
