### ISSUE TITLE
Add an abstraction to std::io::process for dealing with error gracefully

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#10669]
A very common  pattern when dealing with subprocesses is, when they fail, to print out or log some diagnostics. Lots of code that uses `std::run` rolls their own version of this. This shouldn't live in the stdlib, I think. Ideally a really nice CLI library would live in the extra conglomerate. For now, developing it as a separate crate and then merging it into libextra temporarily would be good.

Examples that this would ideally replace:

https://github.com/huonw/multibuilder/blob/master/git.rs#L36 (and bunch elsewhere in this file)
https://github.com/huonw/multibuilder/blob/master/git.rs#L108
https://github.com/alexcrichton/rust/commit/cff13ae06af49d63219941e8429a5be8d367b1aa#diff-88c3a4f09e02361c7490165aacee98dfR41

(I'm sure many more can be found in other codebases)

**Comment by steveklabnik** [comment]
With IO reform, what is the state of this?

**Comment by cmr** [comment]
With the new `Command` and `Process`, I think this is very nice, nearly as nice as it can be!
