### ISSUE TITLE
Check Rustdoc warnings for the compiler in PR CI

### ISSUE THREAD

**Issue by Nilstrieb** [rust-lang/rust#106624]
Docs (and specially intra-doc-links) are easy to get wrong and rarely tested locally, causing many rollups to fail. We should check them in CI as well to catch mistakes early.

**Comment by jyn514** [comment]
cc https://github.com/rust-lang/rust/issues/106117

maybe linkchecker is missing some cases?

**Comment by Nilstrieb** [comment]
The most recent case I've seen was this: https://github.com/rust-lang/rust/pull/100036#issuecomment-1373458057
where broken docs broke a try build while PR CI was green (that wasn't an intra doc link though but still docs)

**Comment by jyn514** [comment]
Ah ok, this is specifically about rustdoc warnings, not broken links. That's definitely doable to do, we can shove `x doc --stage 0 compiler` into mingw-check :) it doesn't need to build the compiler at all, only check it.

**Comment by lukas-code** [comment]
> But `./x test linkchecker` already runs in PR CI

Apparently `./x test linkchecker` doesn't actually build the compiler docs (or tool docs) when the `build.compiler-docs` flag isn't set in `config.toml`. I don't know if this is a bug or a feature, but we could just set the flag for CI here:
https://github.com/rust-lang/rust/blob/002eccc7527c07a0aa89d58d5ef3c981f667b3f4/src/ci/docker/host-x86_64/x86_64-gnu-llvm-13/Dockerfile#L45-L49

**Comment by lukas-code** [comment]
> But `./x test linkchecker` already runs in PR CI

Apparently `./x test linkchecker` doesn't actually build the compiler docs (or tool docs) when the `build.compiler-docs` flag isn't set in `config.toml`. I don't know if this is a bug or a feature, but we could just set the flag for CI here:
https://github.com/rust-lang/rust/blob/002eccc7527c07a0aa89d58d5ef3c981f667b3f4/src/ci/docker/host-x86_64/x86_64-gnu-llvm-13/Dockerfile#L45-L49
