### ISSUE TITLE
Failure to Compile `rdkafka-sys` on Latest Nightly

### ISSUE THREAD

**Issue by HTG-YT** [rust-lang/rust#106663]
I tried this code:

```rust
<inclusion of the rdkafka depndency>
```

I expected to see this happen: compilation to succeed

Instead, this happened: compilation fails (see https://github.com/fede1024/rust-rdkafka/issues/532)

### Meta

`rustc --version --verbose`:
```
rustc 1.68.0-nightly (3020239de 2023-01-09)
binary: rustc
commit-hash: 3020239de947ec52677e9b4e853a6a9fc073d1f9
commit-date: 2023-01-09
host: x86_64-unknown-linux-gnu
release: 1.68.0-nightly
LLVM version: 15.0.6
```

**Comment by attila-lin** [comment]
It looks like num_enum's [issue](https://github.com/illicitonion/num_enum/issues/94)
