### ISSUE TITLE
Adding a hint on iterator type errors

### ISSUE THREAD

**Issue by petar-dambovaliev** [rust-lang/rust#106728]
rust version: `rustc 1.66.0 (69f9c33d7 2022-12-12)`

```
error[E0277]: `{float}` is not an iterator
  --> tests/core.rs:44:14
   |
44 |     for i in 0.200 {
   |              ^^^^^ `{float}` is not an iterator
```

Do you think it would be useful to add a hint here?
Something in the lines of `Did you mean for i 0..200 {`

**Comment by petar-dambovaliev** [comment]
@clubby789 i was hoping this to be my first PR to the compiler, if accepted as necessary. :D

**Comment by tdelabro** [comment]
hups sorry

**Comment by tdelabro** [comment]
I was testing the bot feature

**Comment by clubby789** [comment]
@petar-dambovaliev 
> I need some guidance as to where this code might be though...
The 'is not an iterator' message comes from the `rustc_on_unimplemented` attribute. One solution would be to add a new case to that attribute which detects literals of the form `<lhs>.<rhs>` (where both sides are numeric) and suggests the iterator syntax.

**Comment by petar-dambovaliev** [comment]
> rustc_on_unimplemented

thanks!
