### ISSUE TITLE
rustdoc: macro export in doc hidden mod inlines macro on pub use

### ISSUE THREAD

**Issue by Kloenk** [rust-lang/rust#106713]
I tried this code:

```rust
#[doc(hidden)]
mod crate_macro {
    #[macro_export]
    macro_rules! vec {
        ( $( $x:expr ),* ) => {};
    }
}
pub mod prelude {
    pub use crate::vec;
}
```

I expected to see this happen: 
In the Cargo doc rendering of the prelude module `vec!` should be a reexport of `crate::vec`, as it is, if doc hidden is not set

Instead, this happened: 
`vec!` is inlined in the prelude module

### Meta

`rustc --version --verbose`:
```
rustc 1.66.1 (90743e729 2023-01-10)
```

This sounds similar to #59368 but is slightly different, as the module of the macro is hidden, and not the macro.

**Comment by GuillaumeGomez** [comment]
The reexport is not hidden so that seems like the expected behaviour to me.

**Comment by GuillaumeGomez** [comment]
Closing then.
