### ISSUE TITLE
Add a tidy check to prevent from adding a new test to `src/test`

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/rust#106724]
> The diff is huge and I cannot check on web UI, but is there a tidy check that prevents contributors from adding a test to `src/test`?
A PR modifying an existing test now has a merge conflict e.g. https://github.com/rust-lang/rust/pull/106167 but a PR adding a new test doesn't e.g. https://github.com/rust-lang/rust/pull/106660, and I'm worried if a new test is added to `src/test` by accident.

_Originally posted by @JohnTitor in https://github.com/rust-lang/rust/issues/106458#issuecomment-1378874434_

**Comment by jyn514** [comment]
Mentoring instructions: Add a new module to src/tools/tidy, then call the check from https://github.com/rust-lang/rust/blob/b22c152958eade17a71d899b29a2d39bcc77aa48/src/tools/tidy/src/main.rs#L90. See the surrounding code for examples of how tidy checks work.

**Comment by BoxyUwU** [comment]
I am confused as to why this was not a blocker for moving the tests

**Comment by jyn514** [comment]
@BoxyUwU "I didn't think of it"
