### ISSUE TITLE
Possible unexpected behaviour of overflowing detection with different `-C opt-level=``X`

### ISSUE THREAD

**Issue by wowotek** [rust-lang/rust#106768]
I tried this code with file name of `main.rs`:

  ```rust
  fn main() {
      let mut x: i8 = 0;
      loop {
          x = x + 1;
          println!("{}", x);
      }
  }
  ```

i compiled with

  ```rustc main.rs```

and

  ```rustc -C opt-level=0 main.rs```

both created the expected behaviour of overflow prevetion:

  ```
  $ ./main.exe
  1
  2
  3
  ...
  126
  127
  thread 'main' panicked at 'attempt to add with overflow', coba.rs:4:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  $
  ```

however when i compiled it with `opt-level` above `0`, the overflowed is allowed
```rustc -C -opt-level=<1, 2, 3> main.rs```
```
$ ./main.exe
1
2
3
...
126
127
-128
-127
-126
...
-2
-1
0
1
2
>>>>> endless
```

### Meta

`rustc --version --verbose`:
```
rustc 1.66.0 (69f9c33d7 2022-12-12)
binary: rustc
commit-hash: 69f9c33d71c871fc16ac445211281c6e7a340943
commit-date: 2022-12-12
host: x86_64-pc-windows-msvc
release: 1.66.0
LLVM version: 15.0.2
```

<details><summary>Backtrace</summary>
<p>

No Backtrace

</p>
</details>

**Comment by clubby789** [comment]
[Overflow checking is documented as disabled in non-debug builds](https://doc.rust-lang.org/book/ch03-02-data-types.html#integer-overflow)

**Comment by wowotek** [comment]
> [Overflow checking is documented as disabled in non-debug builds](https://doc.rust-lang.org/book/ch03-02-data-types.html#integer-overflow)

thanks for the enlightenment im closing this
