### ISSUE TITLE
-Z dump-dep-graph does not generate output

### ISSUE THREAD

**Issue by gftea** [rust-lang/rust#106736]
A simple test setup, run on WSL2 on windows 11.
```
cargo new hello
cd hello
cargo clean; cargo +nightly rustc -- -Zdump-dep-graph
```

There is no file generated in current directory, nor in the /tmp folder

**Comment by cjgillot** [comment]
You need to pass `-Zquery-dep-graph` too. We should probably add a diagnostic.

**Comment by gftea** [comment]
OK, now it works with ` cargo clean; cargo +nightly rustc  -- -Zquery-dep-graph -Zdump-dep-graph`

but, now I have below codes, the generated dep-graph does not have any info about `foo()` function. Why is that?

```rust
fn foo() {
    let x = "foo";
    println!("{}", x);
}
fn main() {
    foo();
}
```

**Comment by cjgillot** [comment]
The generated graph only records dependencies between queries. It used to have both the query name and its argument. I removed that a few months back to have much terser dumps, easier to use.

**Comment by cjgillot** [comment]
For the silliest reason: nobody implemented it :smile:.
If you want to do it, please go ahead.

**Comment by gftea** [comment]
@cjgillot after reading the codes, it seems would be better to hint the missing flag if query-dep-graph is not given.

In build_dep_graph(), `record_graph` only true when query-dep-graph is true.
```rust
pub fn build_dep_graph(...) {
    ....
    Some(DepGraph::new(
        &sess.prof,
        prev_graph,
        prev_work_products,
        encoder,
        sess.opts.unstable_opts.query_dep_graph,
        sess.opts.unstable_opts.incremental_info,
    ))
```` 

In assert_dep_graph(), would be good to hint to user if missing query-dep-graph flag.
```rust
pub fn assert_dep_graph(tcx: TyCtxt<'_>) {
    tcx.dep_graph.with_ignore(|| {
        if tcx.sess.opts.unstable_opts.dump_dep_graph {
            tcx.dep_graph.with_query(dump_graph);
        }

        if !tcx.sess.opts.unstable_opts.query_dep_graph {
            // --> Hint about the missing option ?
            return;
        }
```

**Comment by cjgillot** [comment]
Inside `build_session_options` may even be better. There are already a few diagnostics given in that function for option collisions.
