### ISSUE TITLE
Some functions in `core::sync` are annotated to only support targets with 8-bit atomic support

### ISSUE THREAD

**Issue by tomerze** [rust-lang/rust#106845]
This issue was discussed at #106795 
and at https://github.com/rust-lang/rust/pull/106796#issuecomment-1382698625

Some functions in `core::sync` are defined to only compile if the target has 8-bit atomic support. While they should be compiled for all targets with atomic support.

This can cause unnecessary compilation issues when using a custom target json. 

This can probably be solved by changing the definitions to 
```rust
#[cfg(any(
    target_has_atomic = "8",
    target_has_atomic = "16",
    target_has_atomic = "32",
    target_has_atomic = "64",
    target_has_atomic = "128",
    target_has_atomic = "ptr"
))]
```
from
```rust
#[cfg(target_has_atomic = "8")]
```

like you can see at https://github.com/vadorovsky/rust/commit/041978bde712998308203c02715f046e31bd2f47

Examples:
https://github.com/rust-lang/rust/blob/bfffe406fbcabb37b95779f2d252c4a277191e0d/library/core/src/sync/atomic.rs#L3014-L3016
https://github.com/rust-lang/rust/blob/bfffe406fbcabb37b95779f2d252c4a277191e0d/library/core/src/sync/atomic.rs#L3047-L3049
https://github.com/rust-lang/rust/blob/bfffe406fbcabb37b95779f2d252c4a277191e0d/library/core/src/sync/atomic.rs#L3133-L3135

@vadorovsky  @alessandrod

**Comment by vadorovsky** [comment]
Thanks for creating the issue! I will submit a PR soon (I'm AFK now).
