### ISSUE TITLE
Document tidy and bootstrap

### ISSUE THREAD

**Issue by albertlarsan68** [rust-lang/rust#106803]
### Location

Most of the `tidy` tool (located at `src/tools/tidy`), and most of the `bootstrap` source (located at `src/bootstrap`)

### Summary

Actually, adding a new `tidy` check means digging through existing code to find how it works.
I propose adding doc-comments to the `tidy` items, in order to get the new contributors to understand it better.
We should also do it for the `bootstrap` crate, since it is a base building block of Rust, but currently is very opaque in how it works.

### Future possibilities

We can also post the rendered docs to `doc.rust-lang.org`, but this is a later step that is being made possible by documenting the current items.

**Comment by jyn514** [comment]
> We can also post the rendered docs to `doc.rust-lang.org`, but this is a later step that is being made possible by documenting the current items.

I think we can start doing that even before writing manual documentation, the autogenerated docs from rustdoc are already quite helpful.

**Comment by Teapot4195** [comment]
Sounds good, I'll open a pr for that.
