### ISSUE TITLE
Remove spin loop in MPSC channel

### ISSUE THREAD

**Issue by albertlarsan68** [rust-lang/rust#106804]
> Separately, I think the retry loop when sending a message should be removed (like we did with the similar loop in `recv`). The reasoning is the same: we don't want to waste CPU cycles spinning when trying to write to a full channel. Instead we should just go ahead and block immediately. But this can be a separate PR.

_Originally posted by @Amanieu in https://github.com/rust-lang/rust/pull/106701#issuecomment-1381649679_

This issue has been assigned to @ibraheemdev via [this comment](https://github.com/rust-lang/rust/issues/106804#issuecomment-1396751301).

**Comment by marmeladema** [comment]
Done in https://github.com/rust-lang/rust/pull/106836 I believe
