### ISSUE TITLE
`concat!()` rejects negative number literal

### ISSUE THREAD

**Issue by johnmave126** [rust-lang/rust#106837]
I tried this code:

```rust
fn main() {
    println!("{}", concat!(-1));
}
```

I expected to see this happen: code compiles.

Since the following code compiles:
```rust
macro_rules! t {
    ($item: literal) => { stringify!($item) }
}

fn main() {
    println!("{}", t!(-1));
}
```
The macro system recognizes `-1` as a single literal in this case.

Instead, this happened:
```
error: expected a literal
 --> src/main.rs:2:28
  |
2 |     println!("{}", concat!(-1));
  |                            ^^
  |
  = note: only literals (like `"foo"`, `42` and `3.14`) can be passed to `concat!()`

error: could not compile `playground` due to previous error
```

### Meta

`rustc --version --verbose`:
Tried on playground, all channels:
Stable 1.66.1
Beta 1.67.0-beta.7 (2023-01-11 275123cf608aad2c3b48)
Nightly 1.68.0-nightly (2023-01-13 0b90256ada21c6a81b4c)

<details><summary>Backtrace</summary>
<p>

**Comment by Ezrashaw** [comment]
Hmm, this actually looks like fun to fix.

@rustbot claim
