### ISSUE TITLE
When the return type of a default trait method returns an associated type (that has a default), there's always a mismatched type error

### ISSUE THREAD

**Issue by makoConstruct** [rust-lang/rust#106968]
[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=167607d31fe299615ceb92d1d0181ab4)

```rust
#![feature(
    associated_type_defaults,
)]


pub trait Trait {
    type Res = isize;
    fn f() -> Self::Res {
        2
    }
}
```
At line of '2': `error[E0308]: mismatched types` `expected associated type, found integer`

**Comment by Nilstrieb** [comment]
This is correct, as I could write the following impl:
```rust
impl Trait for () {
  type Res = ();
}
```
Now, `Self::Res` is `()`, which is not an integer.

**Comment by makoConstruct** [comment]
Yeah, it just occurred to me that default associated types _shouldn't_ be accessible from default trait methods (broadly: the trait method might be inherited by traits where the associated type has changed and violated the assumptions that the default method made about what the type would be.)

I guess this is an error reporting problem, then. It took me like, maybe 4 hours to figure out what was actually going on. The message it gives in this situation is basically a falsehood. I'm not sure what to recommend instead. At minimum, a `note: Default trait methods cannot access associated default types. See explanation: <link to explanation>`, this note would only need to be shown in type errors concerning associated types that have defaults, coming from default trait methods.

**Comment by makoConstruct** [comment]
As to how I got into that situation: I wanted to define a default associated type that I actually didn't expect impls to ever override, because it was just a sort of convenience function of other associated types (that impls would define).

```rust
pub trait Graph<K, V, E> {
    type Index: Debug + Display;
    type Res<T> = Result<T, GraphError<Self::Index>>;
    ...
}
```

Of course, that can run into the same problem, but it happened to be that the code I had written, where the error was firing, wasn't running afoul of those problems, so it didn't occur to me that those problems existed or that it was actually about that.
