### ISSUE TITLE
Alpine Rust build images generate segfault

### ISSUE THREAD

**Issue by SamTV12345** [rust-lang/rust#106982]
As mentioned I did some testing with the alpine rust builds to generate a smaller image. It turns out that the alpine builds have a defect.
When I build my [sample](https://github.com/SamTV12345/MensaBot/tree/621c7af135839c42fc2f263733ba355cfc5b529e) application it starts without a problem with the Dockerfile_build file.
If I start the Dockerfile which uses alpine it crashes at startup with a 139 error. The same happens currently when I use the Rust nightly build. I can currently  only build successful with the Debian images. 
Unfortunately I don't get any logs when this crash happens. The docker container just crashes.

**Comment by SamTV12345** [comment]
Fixed had to add these lines in Cargo.toml

teloxide = { version = "0.12.0", features = ["macros", "rustls"] }
reqwest = {version="0.11.13", features = ["blocking", "json", "async-compression", "rustls"]}

and add this command to the Dockerfile build: RUN RUSTFLAGS='-C target-feature=-crt-static' cargo build --release

**Comment by Wilson13** [comment]
> Fixed had to add these lines in Cargo.toml
> 
> teloxide = { version = "0.12.0", features = ["macros", "rustls"] } reqwest = {version="0.11.13", features = ["blocking", "json", "async-compression", "rustls"]}
> 
> and add this command to the Dockerfile build: RUN RUSTFLAGS='-C target-feature=-crt-static' cargo build --release

Thanks, this worked for me:

> RUN RUSTFLAGS='-C target-feature=-crt-static' cargo build --release

**Comment by digitalscyther** [comment]
I can't understand why is it like that. Can someone please explain the reason?

I use docker multistage build which automatically generated by command `docker init`.

what helped me:
1. adding RUSTFLAGS flag in build line
```
...
RUN --mount=type=bind,source=src,target=src \
    --mount=type=bind,source=Cargo.toml,target=Cargo.toml \
    --mount=type=bind,source=Cargo.lock,target=Cargo.lock \
    --mount=type=cache,target=/app/target/ \
    --mount=type=cache,target=/usr/local/cargo/git/db \
    --mount=type=cache,target=/usr/local/cargo/registry/ \
RUSTFLAGS='-C target-feature=-crt-static' cargo build --locked --release && \
#cargo build --locked --release && \
cp ./target/release/$APP_NAME /bin/server
...
```

2. And in next alpine parent image I also added next line to install `libgcc` (without that i got errors)
```
...
FROM alpine:3.18 AS final

# this line
RUN apk add --no-cache libgcc
...
```

**Comment by SamTV12345** [comment]
> I can't understand why is it like that. Can someone please explain the reason?
> 
> I use docker multistage build which automatically generated by command `docker init`.
> 
> what helped me:
> 
> 1. adding RUSTFLAGS flag in build line
> 
> ```
> ...
> RUN --mount=type=bind,source=src,target=src \
>     --mount=type=bind,source=Cargo.toml,target=Cargo.toml \
>     --mount=type=bind,source=Cargo.lock,target=Cargo.lock \
>     --mount=type=cache,target=/app/target/ \
>     --mount=type=cache,target=/usr/local/cargo/git/db \
>     --mount=type=cache,target=/usr/local/cargo/registry/ \
> RUSTFLAGS='-C target-feature=-crt-static' cargo build --locked --release && \
> #cargo build --locked --release && \
> cp ./target/release/$APP_NAME /bin/server
> ...
> ```
> 
> 2. And in next alpine parent image I also added next line to install `libgcc` (without that i got errors)
> 
> ```
> ...
> FROM alpine:3.18 AS final
> 
> # next line
> RUN apk add --no-cache libgcc
> ...
> ```
Rust builds are specific to the platform. Rust uses Musl, an alternative to libgcc. Libgcc can only do dynamic builds so things like your database driver or the openssl installation are linked at runtime. If they are not there it will segfault. The advantage of alpine over an ubuntu multistage build is that it does static linking so everything needed for your app is contained in the final binary. That way you can run your binary anywhere.
