### ISSUE TITLE
return on closure call, but get: "cannot borrow `v1` as mutable because it is also borrowed as immutable"

### ISSUE THREAD

**Issue by tivrfoa** [rust-lang/rust#106974]
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=4f84983a07c3ee3ce0b0ec86717f1ec8

```rust

fn main() {
    let mut v1: [Vec<i32>; 1] = [vec![1, 2, 3]];
    
    let go = || {
        if v1[0][1] == 2 {
            println!("ok");
        }
    };
    
    loop {
        if v1.len() >= 1 {
            return go();
        }
        for i in v1.iter_mut() {
            println!("{i:?}");
        }
    }
}
```

Error:

```log
Compiling playground v0.0.1 (/playground)
error[[E0502]](https://doc.rust-lang.org/nightly/error-index.html#E0502): cannot borrow `v1` as mutable because it is also borrowed as immutable
  --> src/main.rs:15:18
   |
5  |     let go = || {
   |              -- immutable borrow occurs here
6  |         if v1[0][1] == 2 {
   |            -- first borrow occurs due to use of `v1` in closure
...
13 |             return go();
   |                    -- immutable borrow later used here
14 |         }
15 |         for i in v1.iter_mut() {
   |                  ^^^^^^^^^^^^^ mutable borrow occurs here

For more information about this error, try `rustc --explain E0502`.
error: could not compile `playground` due to previous error
```

I don't understand why there's a problem there, because it's returning on the closure call: `return go`

The error happens because it's inside `loop`. If I remove `loop` it works:

```rust

fn main() {
    let mut v1: [Vec<i32>; 1] = [vec![1, 2, 3]];
    
    let go = || {
        if v1[0][1] == 2 {
            println!("ok");
        }
    };
    
    //loop {
        if v1.len() >= 1 {
            return go();
        }
        for i in v1.iter_mut() {
            println!("{i:?}");
        }
    //}
}
```

**Comment by tivrfoa** [comment]
I guess this is not a bug, just how things work in Rust.

It seems you can't use closures if the values change after its declaration.

**Comment by clubby789** [comment]
The borrow checker does not do the kind of analysis that would recognise that `if v1.len() >= 1` is always going to be true. If you 'unroll' the loop manually:
```rs
fn main() {
    let mut v1: [Vec<i32>; 1] = [vec![1, 2, 3]];
    
    let go = || {
        if v1[0][1] == 2 {  // v1 borrowed immutably
            println!("ok");
        }
    };
    
      if v1.len() >= 1 {
          return go();   // closure may be called, borrow must last at least this long
      }
      for i in v1.iter_mut() {  // v1 borrowed mutably....
          println!("{i:?}");
      }

      if v1.len() >= 1 {
          return go();    // but again, closure may be called, so borrow must last at least this long,
                                  // so the previous immutable borrow is illegal
      }
      for i in v1.iter_mut() {
          println!("{i:?}");
      }
      [ ... ]
}
```

In the non-looped version, the immutable borrow from `go` ends after the first `if` block so the mutable borrow is legal.

**Comment by tivrfoa** [comment]
> The borrow checker does not do the kind of analysis that would recognise that `if v1.len() >= 1` is always going to be true. If you 'unroll' the loop manually:
> 
> ```rust
> fn main() {
>     let mut v1: [Vec<i32>; 1] = [vec![1, 2, 3]];
>     
>     let go = || {
>         if v1[0][1] == 2 {  // v1 borrowed immutably
>             println!("ok");
>         }
>     };
>     
>       if v1.len() >= 1 {
>           return go();   // closure may be called, borrow must last at least this long
>       }
>       for i in v1.iter_mut() {  // v1 borrowed mutably....
>           println!("{i:?}");
>       }
> 
>       if v1.len() >= 1 {
>           return go();    // but again, closure may be called, so borrow must last at least this long,
>                                   // so the previous immutable borrow is illegal
>       }
>       for i in v1.iter_mut() {
>           println!("{i:?}");
>       }
>       [ ... ]
> }
> ```
> 
> In the non-looped version, the immutable borrow from `go` ends after the first `if` block so the mutable borrow is legal.

Thank you!

I don't know how to remove the label "C-bug" :)

**Comment by Isopod** [comment]
FYI, you can fix this by moving the declaration of the closure into the loop:

```rust

fn main() {
    let mut v1: [Vec<i32>; 1] = [vec![1, 2, 3]];

    loop {
        let go = || {
            if v1[0][1] == 2 {
                println!("ok");
            }
        };
        
        if v1.len() >= 1 {
            return go();
        }
        for i in v1.iter_mut() {
            println!("{i:?}");
        }
    }
}
```

As far as I understand, closures are basically structs internally. So the declaration of the closure creates a borrow that lasts as long as the variable `go` is alive, i.e. until the end of the function.

It’s actually more surprising that your version *without* the loop does *not* trip the borrow checker: I think this is because the compiler has some logic to detect early returns. It probably realizes that the variable `go` is never used after the first `if`, so it places the implicit `drop(go)` before the start of the `for` loop rather than at the end of the scope. Then there is no conflict.
