### ISSUE TITLE
`x.py fmt` is extremely noisy

### ISSUE THREAD

**Issue by mejrs** [rust-lang/rust#106920]
Today I synchronized my local version of the rust repo, made a few changes and formatted. 

This prints:
```
Building rustbuild
formatting modified file compiler/rustc_abi/src/lib.rs
formatting modified file compiler/rustc_ast/src/ast.rs
formatting modified file compiler/rustc_ast/src/ast_traits.rs
formatting modified file compiler/rustc_ast/src/attr/mod.rs

/* 35k lines omitted for brevity */

formatting modified file tests/ui/zero-sized/zero-sized-binary-heap-push.rs
formatting modified file tests/ui/zero-sized/zero-sized-btreemap-insert.rs
formatting modified file tests/ui/zero-sized/zero-sized-linkedlist-push.rs
formatting modified file tests/ui/zero-sized/zero-sized-tuple-struct.rs
Build completed successfully in 0:00:05
```

**Comment by albertlarsan68** [comment]
This is a known issue, it means that you have a remote to the rust-lang repo that is outdated.
The 35k lines likely means that it is at least behind the test move.
Does running `git fetch upstream` (replace `upstream` with the remote name if different) fixes it ?

**Comment by chenyukang** [comment]
Maybe we should remove these logs?

**Comment by albertlarsan68** [comment]
There is the same problem if you created lots of file in the formatted directories, but did not track them in git:
It will print the name of all of these.

**Comment by jyn514** [comment]
I think we should avoid printing the names of the files if there are more than 10 (or whatever number). That would avoid all similar issues.

**Comment by zephaniahong** [comment]
@shourya5 Hi! May I know if you're still working on this issue?
