### ISSUE TITLE
`rustdoc --version --verbose` no longer displays commit hashes + date since beta 1.67

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#107094]
stable is fine:
`~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustdoc --version --verbose`
````
rustdoc 1.66.1 (90743e729 2023-01-10)
binary: rustdoc
commit-hash: 90743e7298aca107ddaa0c202a4d3604e29bfeb6
commit-date: 2023-01-10
host: x86_64-unknown-linux-gnu
release: 1.66.1
LLVM version: 15.0.2
````
but beta and nightly are no longer showing commit-hash and commit-date information:
`~/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/bin/rustdoc --version --verbose`
````
rustdoc 1.67.0-beta.8 (7a9ae0ce6 2023-01-14)
binary: rustdoc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.67.0-beta.8
LLVM version: 15.0.6
````

` ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustdoc --version --verbose`
````
rustdoc 1.68.0-nightly (333ee6c46 2023-01-18)
binary: rustdoc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.68.0-nightly
LLVM version: 15.0.6
````

**Comment by matthiaskrgr** [comment]
it's weird because the info is still displayed correctly in the very first oneliner-summary, but if there was some tool that reads the data by looking at `commit-hash` or `commit-date` we still should display the right thing.

**Comment by ehuss** [comment]
This appears to have been introduced by #104184. The issue is that the macro uses CFG_VER_DATE/CFG_VER_HASH which is only set when compiling rustc.

One option is to try to share some code with `rustc_cargo_env`.  Another option is to go the other way and get rustc to share some code with `prepare_tool_cargo`.

**Comment by jyn514** [comment]
Mentoring instructions: set https://github.com/rust-lang/rust/blob/4e163af1e5c6300ebf04a0e70a44ab0f379898e5/src/bootstrap/compile.rs#L792-L794 in https://github.com/rust-lang/rust/blob/7c3f0d6f30eeefa58170012df10008736ac89755/src/bootstrap/tool.rs#L235

(Maybe we should try to unify those functions so they don't duplicate so much code and problems like this don't happen in the future?)

**Comment by jyn514** [comment]
I think it should be possible to write a run-make test ensuring this works properly.

**Comment by anth0nyleung** [comment]
Hi @zephaniahong! im starting my journey of contributing to Rust, i found this issue a good starter for myself, do you think you would be open to let me take this chance to get familiar with the code base?

**Comment by zephaniahong** [comment]
@anth0nyleung Hey! Go for it!🤗

**Comment by zephaniahong** [comment]
Alternatively, you could check out #108111. I THINK that might be more straightforward. But I'll let you decide(:

**Comment by anth0nyleung** [comment]
I tried doing this change in tool.rs 

```
diff --git a/src/bootstrap/tool.rs b/src/bootstrap/tool.rs
index ca5f500f93b..6788151f806 100644
--- a/src/bootstrap/tool.rs
+++ b/src/bootstrap/tool.rs
@@ -286,6 +286,9 @@ pub fn prepare_tool_cargo(
     if let Some(date) = info.commit_date() {
         cargo.env("CFG_COMMIT_DATE", date);
     }
+    if let Some(ver_date) = info.commit_date() {
+        cargo.env("CFG_VER_DATE", ver_date);
+    }
     if !features.is_empty() {
         cargo.arg("--features").arg(&features.join(", "));
     }
```

Then i did a `./x.py build` and tried running this command `rustdoc --version --verbose` on the stage2 rustodc
```
$> ./build/aarch64-apple-darwin/stage2/bin/rustdoc --version --verbose
rustdoc 1.69.0-dev
binary: rustdoc
commit-hash: unknown
commit-date: unknown
host: aarch64-apple-darwin
release: 1.69.0-dev
LLVM version: 15.0.7
```
But it appears that the commit-hash and commit-date is still unknown. Im wondering if the issue is that `builder.config.ignore_git` is passed as true in `GitInfo::new()`

```
let info = GitInfo::new(builder.config.ignore_git, &dir);
```

This is my first time making changes and testing in this project, please feel free to correct me if im testing / building in the wrong way.

**Comment by jyn514** [comment]
@anth0nyleung I'd suggest changing https://github.com/rust-lang/rust/blob/ae5473c9699eaf1998c414e0a8884383bb9ddcc3/compiler/rustc_driver_impl/src/lib.rs#L702-L705 to use `env!` instead of `option_env` so it's easier to tell when these variables are unset.

**Comment by duckymirror** [comment]
@anth0nyleung Are you still (interested in) working on this issue? I'd like to claim it otherwise.

**Comment by anth0nyleung** [comment]
@duckymirror please go ahead and claim it!
