### ISSUE TITLE
`./configure --set changelog-seen=2` doesn't work

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#107049]
```
; ./configure --set changelog-seen=2
configure: processing command line
configure: 
configure: changelog-seen       := 2
configure: build.configure-args := ['--set', 'changelog-seen=2']
Traceback (most recent call last):
  File "/Users/jyn/src/rust/./src/bootstrap/configure.py", line 465, in <module>
    raise RuntimeError("config key {} not in sections".format(section_key))
RuntimeError: config key changelog-seen not in sections
```

The problem is that the configure script assumes that all keys are in a section and there are no top-level keys. This forces people to use `printf` instead: https://github.com/rust-lang/rust/blob/37c1d6dc09e97a7d707977c7cceeb0685df1776a/README.md#L89-L96

We should make it possible to set top-level keys through `configure`, both `changelog-seen` and `profile`. We should also update the line in the readme linked above to suggest `./configure` instead of printf.

**Comment by jyn514** [comment]
Mentoring instructions: look around https://github.com/rust-lang/rust/blob/37c1d6dc09e97a7d707977c7cceeb0685df1776a/src/bootstrap/configure.py#L462-L471
I think the fix would be something like `if section_config is None: # special-casing for top-level keys`.

**Comment by shourya5** [comment]
@claim

**Comment by shourya5** [comment]
In the configure.py, from where exactly do we get the top-level keys? from the set function?

**Comment by jyn514** [comment]
> In the configure.py, from where exactly do we get the top-level keys? from the set function?

I'm not sure off the top of my head. How could you find out that information?

**Comment by lionellloh** [comment]
@shourya5 Hi are you still working on this?

**Comment by zephaniahong** [comment]
@jyn514 do you think it's okay to unassign @shourya5 ? 
This issue is blocking #107050 as well.

**Comment by zephaniahong** [comment]
@lionellloh Since there's no response from the assignee, I think you can take the issue. Are you still keen on working on this issue?

**Comment by lionellloh** [comment]
Yup I am interested! @claim

**Comment by lionellloh** [comment]
Hi @zephaniahong and @jyn514, thanks for mentoring! 

 > I think the fix would be something like if section_config is None: # special-casing for top-level keys. 
 
 Assuming I run `./configure --set changelog-seen=2`, I think `section_config` will be 2. So I am not sure if this path would work. 

It seems like the first blocker is that `sections` does not contain `changelog-seen` or `profile` as keys. Should the approach be to expand `sections` with those keys? Or should we just allow `changelog-seen` / `profile` as special cases? 

Finally, I am a little confused what top-level keys mean - do they exclusively refer to [`changelog-seen`, `profile`] ? Are there more?

**Comment by lionellloh** [comment]
I am able to expand `sections: dict` when parsing to include `profile` and `changelog-seen` but I realise I may either have to make changes to `def configure_section()` or write a new method. 

Before I do that, I would like to understand how the configure script is commonly used. Could you give me some sample commands, say if I want to modify the `skip-rebuild` field of llvm?

**Comment by lionellloh** [comment]
Shall we refactor the 2 top level keys under a `[general` section? this makes the parsing logic more consistent and unwieldy lol

**Comment by zephaniahong** [comment]
> Finally, I am a little confused what top-level keys mean - do they exclusively refer to [`changelog-seen`, `profile`] ? Are there more? 
> 

Top level keys are keys without any header like `[rust]` or `[llvm]` etc. 
you can take a look at `config.toml.example` for a complete example of what a configuration could look like. I think that would resolve most, if not all of your queries(: 

Hope this helps!

**Comment by zephaniahong** [comment]
> I am able to expand `sections: dict` when parsing to include `profile` and `changelog-seen` but I realise I may either have to make changes to `def configure_section()` or write a new method.
> 
> Before I do that, I would like to understand how the configure script is commonly used. Could you give me some sample commands, say if I want to modify the `skip-rebuild` field of llvm?

try running `./configure --help`

**Comment by lionellloh** [comment]
Got it, thanks @zephaniahong. I put up a PR. This is kinda my first PR so would appreciate all the tips and advice!
