### ISSUE TITLE
Backport patch to fix build failure to 1.67.0

### ISSUE THREAD

**Issue by paulmenzel** [rust-lang/rust#107032]
As asked about in the discussion of https://github.com/rust-lang/rust/pull/105901, I am creating this issue, so it can be discussed in the compiler team triage. (@oli-obk)

**Comment by apiraino** [comment]
T-compiler meeting discussed ([on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202023-01-19/near/322312117)): #105901 was beta nominated and approved so it will end in 1.67.0

I think I can also close this issue - hope it's fine!

@rustbot label -I-compiler-nominated
