### ISSUE TITLE
possible to accomodate alternate doc-comment style?

### ISSUE THREAD

**Issue by klebz** [rust-lang/rust#107066]
hi folks! I was wondering whether it would be agreeable to support a certain edge case formatting for doc comments as follows:

In the codebases I write, I like to do this:

<img width="663" alt="Screen Shot 2023-01-18 at 2 45 13 AM" src="https://user-images.githubusercontent.com/92199902/213112998-cca5abbc-e617-4789-bd5a-ea496931b2bf.png">

Specifically, I am referring to the left margin vertical pipe.

/**
 |   doc comment body
 |
 | 
 */

I do this because I think it is a bit easier to read, and because, to me, it looks better in my editor.

I find that the left margin pipe character `|` lets my eyes lock in on doc comments more easily when I encounter them in the code.

Anyway, most of my codebases look like this.  I like to be able to use this particular formatting when I write code.

I am reluctant to change these usages, though I find they complicate the automatic documentation generated into docs.rs.  

What happens on docs.rs is that, without a special case, these pipe characters get interspersed with the actual documentation. 

I am wondering if, for example, it would be reasonable/agreeable for me/us to *special case* the formatting code which is involved in generating the documentation.

What I am considering is that we can *check* whether the doc comment has this particular left margin all the way down.  If so, during the doc comment generation, we can *remove* the whole left margin pipe, leaving just the interior documentation comment as desired.

I think it should probably not be too much of an issue, or cause any undesired behavior elsewhere.

What do you think? Is this straightforward? Would you accept a pull request for this, if I could figure out how to do it?

Is there anything else I should consider? Perhaps, once implemented, there could be a way to activate this feature explicitly, so that it is not the default behavior.

**Comment by Nemo157** [comment]
@syphar you can ping me if an issue needs moving, I have permissions in both

**Comment by Nemo157** [comment]
I don't know if it's documented anywhere (with a quick skim I don't see `/**` syntax being mentioned at all in the rustdoc book), but there is existing support for stripping leading `*` for the common standard:

```rust
/**
 * Network Address
 */
pub struct NetAddr;
```

I'm doubtful there would be much support for adding another alternative to this, `/**` doc-comments are rarely used and IIRC there have been quite a few bugs related to this stripping already.

**Comment by GuillaumeGomez** [comment]
It would at least to go through an RFC for sure in any case.

Another possibility would be to put your documentation into markdown files and include them using `#[doc = include_str!("path/to/file")]` but not sure it would fill your need.

**Comment by klebz** [comment]
Thanks, all, for the ideas and help.

I did not know about the * left hand margin token -- thanks for the tip!

I feel 95% sure the best thing to do is just use * on the left hand margin instead of the |

At the same time, it is an involved change to do this manually everywhere across these codebases.  It is not prohibitively difficult, but also not trivial.

The easiest way to do it is to write a program to do it.

At any rate, I am wondering quite frankly whether I should bother creating a request to support the pipe (or any other margin token).  What do you think? 

I would not be offended if any of you found this change trivial.  I myself find it somewhat trivial.  

However, it is also probably just as much work for me to write a program to correct the previous usages as it is to write the RFC and update.

Maybe this functionality would be welcome/useful to some of you -- in this case, the benefits of choosing the latter course of action and submitting an RFC may be worth it.

What do you think?

**Comment by GuillaumeGomez** [comment]
To be honest, I think it's very unlikely that such a change would be accepted.

**Comment by klebz** [comment]
i agree.  thank you all for the help.  I consider it closed. 🌿
