### ISSUE TITLE
`./configure` should set `profile = "user"` by default

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#107050]
This is part of https://jyn.dev/2023/01/12/Bootstrapping-Rust-in-2023.html that's not a breaking change. Setting `profile = "user"` will be useful regardless of the rest of the changes mentioned there, since it will let us change the global defaults in bootstrap without impacting distros as much.

This is blocked on https://github.com/rust-lang/rust/issues/107049. Note that `./configure --set profile=x` should override the default of `user`.

I would like to also set `download-ci-rustc = false` in `src/bootstrap/defaults/config.user.toml` at the same time.

**Comment by reez12g** [comment]
Is this an Issue that should be tackled after #107049 is completed?

**Comment by jyn514** [comment]
Yes, fixing this requires fixing the other first.

**Comment by lionellloh** [comment]
@reez12g Hey Rento, are you still interested in working on this? I was working on issue 107049, and I think this is a natural extension of it. Would you might if I take over this issue? Otherwise, no pressure!

**Comment by reez12g** [comment]
@lionellloh 
I was still going to work on it, but if you can do it as a natural extension of your work, you are welcome to do it!

**Comment by lionellloh** [comment]
> @lionellloh I was still going to work on it, but if you can do it as a natural extension of your work, you are welcome to do it!

Cool, thanks for your understanding. I will put a PR after https://github.com/rust-lang/rust/pull/108229 is merged in. 

@rustbot claim

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/pull/108229 has been merged :)

**Comment by lionellloh** [comment]
@jyn514 

> I would like to also set download-ci-rustc = false in src/bootstrap/defaults/config.user.toml at the same time.

Is `download-ci-rustc` under `[build]` or `[llvm]`

**Comment by jyn514** [comment]
@lionellloh I actually ended up making that change myself in https://github.com/rust-lang/rust/pull/108625, sorry.
