### ISSUE TITLE
Add T: ?Sized to mem::align_of

### ISSUE THREAD

**Issue by overlookmotel** [rust-lang/rust#107008]
This is a repeat of #50948.

That issue was closed due to "this bound is still necessary until we've sorted out the custom DST traits". But that was in  2018, so I wondered if this blocker still persists?

**Comment by Nilstrieb** [comment]
rust-lang/rfcs#3319 is relevant here and would allow replacing it with `T: ?Sized + Aligned`.

This would still not allow `align_of::<dyn Debug>`, which is fundamentally unsolvable.

**Comment by overlookmotel** [comment]
Thanks very much for coming back so swiftly. I wasn't aware that this was currently in motion.

Shall I leave this issue open for when/if `Aligned` trait is implemented?

**Comment by Dylan-DPC** [comment]
When the RFC is accepted, a tracking issue will be created which will track the progress of it. So we don't need to keep this issue open as it will likely be forgotten that it exists in future, so I am closing this.
