### ISSUE TITLE
target 'aarch64-linux-android' not found in channel

### ISSUE THREAD

**Issue by octavei** [rust-lang/rust#107075]
andriod 13
termux

command:
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

error info:
```
Current installation options:


   default host triple: aarch64-linux-android
     default toolchain: stable (default)
               profile: default
  modify PATH variable: yes

1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
>1

info: profile set to 'default'
info: default host triple is aarch64-linux-android
info: syncing channel updates for 'stable-aarch64-linux-android'
info: latest update on 2023-01-10, rust version 1.66.1 (90743e729 2023-01-10)
error: target 'aarch64-linux-android' not found in channel.  Perhaps check https://doc.rust-lang.org/nightly/rustc/platform-support.html for available targets
~ $ rustup target add aarch64-linux-android

```

**Comment by ehuss** [comment]
Pre-compiled Rust installations or only available for a subset of platforms. Those are outlined in https://doc.rust-lang.org/nightly/rustc/platform-support.html. As indicated there, `aarch64-linux-android` does not provide the compiler or tooling. It only supports cross compiling from another host.

**Comment by octavei** [comment]
> Pre-compiled Rust installations or only available for a subset of platforms. Those are outlined in https://doc.rust-lang.org/nightly/rustc/platform-support.html. As indicated there, `aarch64-linux-android` does not provide the compiler or tooling. It only supports cross compiling from another host.

thx
