### ISSUE TITLE
ICE reporting link template not working.

### ISSUE THREAD

**Issue by recmo** [rust-lang/rust#107145]
### Code

```Rust
(any code triggering ICE)
```

### Current output

```Shell
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
```

### Desired output

```Shell
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?assignees=&labels=C-bug%2CI-ICE%2CT-compiler&template=ice.yaml&title=%5BICE%5D%3A+
```

### Rationale and extra context

The provided link opens an empty issue and does not set the template (as the url would suggest).

**Comment by albertlarsan68** [comment]
Cc #106831

**Comment by ehuss** [comment]
cc @estebank

**Comment by Nilstrieb** [comment]
#106898 brings it back

**Comment by estebank** [comment]
Apologies, I've had to leave suddenly and am going to be unavailable for a another couple of weeks. I would appreciate it if someone could follow up on this. I've moved to merge my PR, but I'd feel more comfortable if someone kept an eye out for further problems here. Apologies for introducing these growing pains.

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/pull/106898 was merged. I think it might make sense to open an issue for following up here, but I don't think we need to keep this issue open.
