### ISSUE TITLE
`#[doc(hidden)]` causes type's traits to disappear from rustdoc JSON built with `--document-hidden-items`

### ISSUE THREAD

**Issue by obi1kenobi** [rust-lang/rust#107278]
Affected crate: `toml_edit`, at path `crates/toml_edit` in repo https://github.com/toml-rs/toml
Commit: d86370fc5e8777e532de457cb6569feeae6429f0
Building rustdoc JSON with `RUSTDOCFLAGS="-Z unstable-options --document-private-items --document-hidden-items --output-format=json"`

Consider the following type from `crates/toml_edit/src/easy/value.rs` in that commit:
```rust
#[doc(hidden)]
#[deprecated(since = "0.18.0", note = "Replaced with `toml::Value`")]
#[derive(PartialEq, Clone, Debug, serde::Serialize)]
#[serde(untagged)]
pub enum Value {
    // < omitted >
}
```

I expected to see this happen: the rustdoc JSON should state that `PartialEq, Clone, Debug, Send, Sync, Unpin` etc. are all implemented for that type.

Instead, this happened: none of those traits are listed as implemented for that type.

Deleting `#[doc(hidden)]` and rebuilding the rustdoc JSON causes all the missing trait impls to be present again.

### Meta

`rustc --version --verbose`:
```
rustc 1.66.1 (90743e729 2023-01-10)
binary: rustc
commit-hash: 90743e7298aca107ddaa0c202a4d3604e29bfeb6
commit-date: 2023-01-10
host: x86_64-unknown-linux-gnu
release: 1.66.1
LLVM version: 15.0.2
```

The same bug is present on nightly:
```
rustc 1.69.0-nightly (c8e6a9e8b 2023-01-23)
binary: rustc
commit-hash: c8e6a9e8b6251bbc8276cb78cabe1998deecbed7
commit-date: 2023-01-23
host: x86_64-unknown-linux-gnu
release: 1.69.0-nightly
LLVM version: 15.0.7
```

The bug was first spotted by @epage who filed [a bug report](https://github.com/obi1kenobi/cargo-semver-checks/discussions/296#discussioncomment-4742719) on `cargo-semver-checks` for incorrectly reporting that types stopped being `Send / Sync / Debug / Clone` etc. Of course we now know this was because those traits were genuinely not present in the underlying rustdoc JSON file.

Thanks for all the awesome work you've been doing! It's been absolutely fundamental for `cargo-semver-checks`.

**Comment by GuillaumeGomez** [comment]
It should be fixed with https://github.com/rust-lang/rust/pull/107000.

**Comment by aDotInTheVoid** [comment]
MCVE:

```rust
// compile-flags: --document-private-items --document-hidden-items

pub trait TheTrait {}

#[doc(hidden)]
struct Value {}

impl TheTrait for Value {}
```

Produces (On d6f0642827e21a088b0130c84857d84f5433301d)

```json
      "inner": {
        "bounds": [],
        "generics": {"params": [], "where_predicates": []},
        "implementations": [],
        "is_auto": false,
        "is_unsafe": false,
        "items": []
      },
      "kind": "trait",
      "links": {},
      "name": "TheTrait"
    },
    "0:4:1582": {
      "crate_id": 0,
      "docs": null,
      "id": "0:4:1582",
      "inner": {
        "generics": {"params": [], "where_predicates": []},
        "impls": [],
        "kind": {"plain": {"fields": [], "fields_stripped": false}}
      },
      "kind": "struct",
      "links": {},
      "name": "Value"
    },
```

**Comment by its-the-shrimp** [comment]
This is fixed & works just fine as of today

**Comment by obi1kenobi** [comment]
It would be great to make sure we have a regression test case for this
before closing the issue, since this is a correctness concern for
cargo-semver-checks that would be very difficult to debug if it reoccurs.

**Comment by its-the-shrimp** [comment]
Absolutely, that's what I've done in #128836
