### ISSUE TITLE
codegen generates vtables for a variable's supertype when unsizing sometimes

### ISSUE THREAD

**Issue by Rattenkrieg** [rust-lang/rust#107205]
I was putting `&`'s here and there to make my program compile as beginners supposed to do and finally ended with:

```
  = note: Undefined symbols for architecture arm64:
            "core::ptr::drop_in_place$LT$fn$LP$$RF$$u5b$i64$u5d$$RP$$u20$.$GT$$u20$i64$GT$::h8f1379e9ceec7fb5", referenced from:
                l___unnamed_1 in wyas-3cfa3c0d2101b65b.6xaszv4ay9i42ky.rcgu.o
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
To assure myself that this is unrelated to native/rosetta mess I've ran this in docker and in [rust playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=ea5473b749dd86ba767cc9acbd2f8be5) with the same outcome.
```
  = note: /usr/bin/ld: /playground/target/release/deps/playground-7e94a1292993c003.playground.0627c30c-cgu.0.rcgu.o:(.data.rel.ro..L__unnamed_3+0x0): undefined reference to `core::ptr::drop_in_place<fn(&[i64]) -> i64>'
          /usr/bin/ld: /playground/target/release/deps/playground-7e94a1292993c003: hidden symbol `_ZN4core3ptr66drop_in_place$LT$fn$LP$$RF$$u5b$i64$u5d$$RP$$u20$.$GT$$u20$i64$GT$17h8581d5a4605118bdE' isn't defined
          /usr/bin/ld: final link failed: bad value
```

This particular code breaks the linker
```rust
struct Wrapper(fn(val: &[i64]) -> i64);

impl Debug for Wrapper {
    fn fmt<'a>(&'a self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_tuple("Wrapper").field(&self.0 as &fn(&'a [i64]) -> i64).finish()
    }
}

fn main() {
    println!("{:?}", Wrapper(useful));
}
```
I've come up with that since deriving `Debug` or implementing it manually like that 
```rust
impl Debug for Wrapper {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_tuple("Wrapper").field(&self.0).finish()
    }
}
```
leads to following type/borrow check error:
> implementation of `Debug` is not general enough

Expected behavior: program prints
> Wrapper(address)

Actual behavior: *see above*

`rustc --version --verbose`:
```
rustc 1.66.1 (90743e729 2023-01-10)
binary: rustc
commit-hash: 90743e7298aca107ddaa0c202a4d3604e29bfeb6
commit-date: 2023-01-10
host: aarch64-apple-darwin
release: 1.66.1
LLVM version: 15.0.2
```

I've tried both beta `1.67.0-beta.9` and nightly `1.68.0-nighlty` at rust playground and both are failing during linking.

----------------
***Edit***

I've bruteforced working program 😂  :
```rust
impl Debug for Wrapper {
    fn fmt<'a>(&'a self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_tuple("Wrapper").field(&(self.0 as fn(&'a [i64]) -> i64)).finish()
    }
}
```

**Comment by erikdesjardins** [comment]
This might be the simplest code sample\* I've seen cause a link error. Bravo!

Marginally reduced: https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=e4cd76a3ddf3068e0d71ea19247915a9

<sup>\* aside from obviously broken code, `#[link_name]`, etc., which is cheating :)</sup>

**Comment by Nilstrieb** [comment]
The following reproduction reproduces on stable but not on nightly:

```rust
use std::fmt;

pub struct Wrapper(for<'b> fn(&'b ()));

impl fmt::Debug for Wrapper {
    fn fmt<'a>(&'a self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let dyn_debug: &dyn fmt::Debug = &self.0 as &fn(&'static ());
        fmt::Debug::fmt(&dyn_debug, f)
    }
}

fn useful(_: &()) {}

fn main() {
    println!("{:?}", Wrapper(useful));
}
```


searched nightlies: from nightly-2023-02-01 to nightly-2023-03-16
regressed nightly: nightly-2023-02-17
searched commit range: https://github.com/rust-lang/rust/compare/2d14db321b043ffc579a7461464c88d7e3f54f83...9a7cc6c32f1a690f86827e4724bcda85e506ef35
regressed commit: https://github.com/rust-lang/rust/commit/639377ed737b25830ec44dc6acf93467c980316a

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.5</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc 2023-02-01 --end 2023-03-16 --access github --regress success
```
</details>

Bisection points at a new optimization, so I guess the problematic code is simply optimized away. Using `-Zmir-opt-level=0` to stop the opt makes it appear again even on nightly.

**Comment by BoxyUwU** [comment]
Here is a code snippet that segfaults on stable because of this bug:
```rust
#![allow(coherence_leak_check)]

struct Foo<T: 'static>(T);

fn useful<'a>(_: &'a u8) {}

pub struct Wrapper(for<'b> fn(&'b u8));

trait GetInner {
    type Assoc;
    fn muahaha(&mut self) -> Self::Assoc;
}

impl GetInner for Foo<fn(&'static u8)> {
    type Assoc = String;
    fn muahaha(&mut self) -> String {
        panic!("cant do it boss")
    }
}

impl GetInner for Foo<for<'a> fn(&'a u8)> {
    type Assoc = [usize; 3];
    fn muahaha(&mut self) -> [usize; 3] {
        [100; 3]
    }
}

fn main() {
    let wrapper = Wrapper(useful);

    drop(Box::new(Foo(useful as fn(&'static u8))) as Box<dyn GetInner<Assoc = String>>);
    drop(Box::new(Foo(useful as fn(&u8))) as Box<dyn GetInner<Assoc = [usize; 3]>>);

    let hr_fnptr = Box::new(Foo::<for<'a> fn(&'a u8)>(wrapper.0));
    let lr_fnptr = hr_fnptr as Box<Foo<fn(&'static u8)>>;
    let mut any = lr_fnptr as Box<dyn GetInner<Assoc = String>>;

    let evil_string = any.muahaha();
    drop(evil_string);
}
```
if you remove the two statements that are `drop(Box::new(` you will get a linker error (what this issue is about), having them in this repro ensures that everything gets codegen'd to replace the linker error with calling the wrong function at runtime

**Comment by BoxyUwU** [comment]
Here is also a [super minimal repro](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4447c7e765c6b125ba42f5d11998195b), although note that it requires `-Zmir-opt-level=0` to repro (as nils pointed out previously):
```rust
pub struct Wrapper(for<'b> fn(&'b ()));

fn useful(_: &()) {}

fn main() {
    let wrapper = Wrapper(useful);
    let dyn_debug = &wrapper.0 as &fn(&'static ()) as &dyn std::fmt::Debug;
    println!("{:?}", dyn_debug);
}
```

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23107205.20Linking.20fails.20for.20program.20that.20coercing.20lifetimes.20f.E2.80.A6)).

@rustbot label -I-prioritize +P-high

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23107205.20Linking.20fails.20for.20program.20that.20coercing.20lifetimes.20f.E2.80.A6)).

@rustbot label -I-prioritize +P-critical

**Comment by lcnr** [comment]
this regressed in 1.16, the bug probably existed ever since we added the mir: https://godbolt.org/z/a3b5Er71c

**Comment by lcnr** [comment]
an even more minimal linker error happens with 

```rust
// rustc src/main.rs -Zmir-opt-level=0
const X: for<'b> fn(&'b ()) = |&()| ();
fn main() {
    let dyn_debug = &X as &fn(&'static ()) as &dyn Send;
    drop(dyn_debug)
}
```
the bug here is 

https://github.com/rust-lang/rust/issues/107205 is caused by `OperandRef` having a `TyAndLayout`. The type of which may differ from the type of the place we write the `OperandRef` into.

This causes unsoundness when we do trait solving using the type of the `OperandRef` instead of the type of the place. It means that mir typeck and codegen can disagree on which impl to choose.

https://github.com/rust-lang/rust/compare/master...lcnr:rust:operand-ref?expand=1 tries to deal with that in some locals which is enough for that minimal linker error repro but does not yet fix the unsoudness as the status quo is very worrying to me:
- we have multiple locations in the code which move an `OperandRef` "over a subtyping edge"
- we have multiple locations in the code which use the type of the `OperandRef` instead of the type of the current mir place

Going to keep looking a bit more into this and may write some mentoring instructions or will look into fixing this myself. Also, thanks @BoxyUwU for guiding me towards my current understanding here
