### ISSUE TITLE
non-inline, non-generic destructors are always external

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#10732]

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by bltavares** [comment]
Triage: is this still an issue?

I was not able to find the relevant comment on the liked source file, nor I quiet understand how to reproduce the issue.

**Comment by steveklabnik** [comment]
@bltavares same. The XXX comment is gone, so either it has been fixed or it's not being tracked anymore; it was here when I left the triage comment last time.

**Comment by Mark-Simulacrum** [comment]
Could someone take a look at this issue and decide whether this is still the case? I believe I saw a few PRs somewhat recently that may have related to this, but I'm uncertain...

**Comment by steveklabnik** [comment]
Nobody has taken a look and decided in the last year, I'm going to close, as apparently it is not important enough to look into.

**Comment by petrochenkov** [comment]
This is still an issue, AFAIK.
cc @michaelwoerister

**Comment by michaelwoerister** [comment]
I tested with the following program:
```rust

fn main() {
    let _ = abc::Foo { a: 3 };
}

mod abc {
    pub struct Foo {
        pub a: i32
    }

    impl Drop for Foo {
        fn drop(&mut self) {
            println!("{}", self.a);
        }
    }
}
```
Compiling that with `-Ccodegen-units=1` gives me the following `nm` output for the main object file:
```
0000000000000000 V DW.ref.rust_eh_personality
0000000000000000 r GCC_except_table5
0000000000000000 T main
                 U rust_eh_personality
                 U _Unwind_Resume
                 U _ZN3std2io5stdio6_print17hec111a976343fddfE
0000000000000000 T _ZN3std2rt10lang_start17h74b65d59fae44027E
0000000000000000 t _ZN3std2rt10lang_start28_$u7b$$u7b$closure$u7d$$u7d$17h6e1016afe6c0087fE
                 U _ZN3std2rt19lang_start_internal17h773ef7be57a5b9c1E
0000000000000000 t _ZN3std3sys4unix7process14process_common8ExitCode6as_i3217he0b1c768d26e474dE
0000000000000000 t _ZN4core3fmt10ArgumentV13new17h2126edd4539a51adE
                 U _ZN4core3fmt3num52_$LT$impl$u20$core..fmt..Display$u20$for$u20$i32$GT$3fmt17h46cca7c5a43b2847E
0000000000000000 t _ZN4core3fmt9Arguments16new_v1_formatted17h1e845a8967740792E
0000000000000000 t _ZN4core3ops8function6FnOnce9call_once17hbf62ddf43dd9c714E
0000000000000000 t _ZN4core3ptr13drop_in_place17h5f282f445e6f0322E
0000000000000000 t _ZN4core3ptr13drop_in_place17h94540e5e58e83d5cE
0000000000000000 t _ZN4main4main17hd31e54a560abace9E
0000000000000000 t _ZN54_$LT$$LP$$RP$$u20$as$u20$std..process..Termination$GT$6report17h86d3beb0be658bc4E
0000000000000000 t _ZN56_$LT$main..abc..Foo$u20$as$u20$core..ops..drop..Drop$GT$4drop17h70321705981a0775E
0000000000000000 t _ZN68_$LT$std..process..ExitCode$u20$as$u20$std..process..Termination$GT$6report17h424fd6aab7ac68f1E
```
It looks like the `Drop::drop` method and all `drop_in_place` instances are _internal_.

**Comment by petrochenkov** [comment]
>fn main() {

IIRC, executables internalize almost everything?
What happens if it's a library?

**Comment by michaelwoerister** [comment]
For a `staticlib` it will be internalized too. For an `rlib` it gets external linkage (like any other trait method would). But is there a way around that? How else would a downstream crate call `drop()`?
