### ISSUE TITLE
rust 1.67.0 fails to recognize thin archive

### ISSUE THREAD

**Issue by jpalus** [rust-lang/rust#107334]
### Code

Build of `Mesa 22.3.4` (enabled `rusticl`) on `Linux/aarch64` with `rust 1.67.0` fails with:

```
error: failed to add native library src/gallium/auxiliary/libgallium.a: Unsupported archive identifier
```

where:
```
$ file build/src/gallium/auxiliary/libgallium.a
build/src/gallium/auxiliary/libgallium.a: thin archive with 1344 symbol entries
```

### Version it worked on

Builds fine with `rust 1.66.0`.

### Version with regression

Stable release of `rust 1.67.0`

**Comment by karolherbst** [comment]
thanks for bringing this to my attention as well. I can confirm that I also hit the same issue.

**Comment by jpalus** [comment]
@apiraino I've already [commented](https://github.com/rust-lang/rust/pull/107360#issuecomment-1407062179) on #107360 that it does.

**Comment by apiraino** [comment]
sorry, I missed that comment. thanks

**Comment by Firstyear** [comment]
Will this issue trigger a release of 1.67.1 or will we need to apply the patches for this ourselves in distros?

**Comment by apiraino** [comment]
@Firstyear yes, a 1.67.1 is planned (see draft of [the blog post](https://github.com/rust-lang/blog.rust-lang.org/blob/4066cf543d602c51f1bf8a73ac337a2810a1e5d3/posts/2023-02-09-Rust-1.67.1.md))

**Comment by cuviper** [comment]
We did release this in 1.67.1, and 1.68.0 also got the patch added while it was in beta.
