### ISSUE TITLE
Pin::map_unchecked_mut is technically unsound?

### ISSUE THREAD

**Issue by SoniEx2** [rust-lang/rust#107371]
Since `Pin<&mut !Unpin>` (or whatever we end up using in the future - `Pin<&mut !FreezeMut>` maybe?) is special, but `&mut !Unpin` is not (which is also a problem for `Drop` but we digress), `Pin::map_unchecked_mut` is bound to cause miscompilations (see e.g. #106180). So why aren't we using raw pointers and pointer projections (aka `addr_of_mut!`) for this...?

cc @RalfJung

**Comment by SoniEx2** [comment]
Huh. So `Pin` is purely a way to expose/wrap this stuff in safe APIs?

**Comment by RalfJung** [comment]
`map_unchecked_mut` is an unsafe fn, so "unsound" isn't even a meaningful adjective to use on that function.

The purpose of using references is that it avoids having to use unsafe operations inside the closure, making it slightly more ergonomic. https://github.com/rust-lang/rust/pull/106180 would be a problem even if `map_unchecked_mut` was using raw pointers. So please explain more precisely, and with an example, what is wrong with `map_unchecked_mut`.

**Comment by SoniEx2** [comment]
Since `map_unchecked_mut` passes a bare reference (not wrapped in `Pin`) to the closure, it would be unsound to apply optimizations such as those in #106180 to the bare `&mut T`. (On the assumption that `Pin<&mut T>` would turn off those optimizations, due to being actually pinned.)

**Comment by SoniEx2** [comment]
Hmm... oh, right, `Pin` can't be special because it must be able to support third-party smart pointers, so the special bits *must* be `Box` and `&mut`. But the documentation doesn't really say much about that, and it feels implied that `Pin` is the *only* way to have "pinned data".

**Comment by RalfJung** [comment]
> We still don't fully understand Pin. Is it technically sound for unsafe code to rely on a pointer/reference being pinned without ever actually wrapping it in Pin, if said pointer/reference never escapes said unsafe code? Is Pin merely a barrier/wrapper for safe code?

That is basically the idea, yes.

> Since map_unchecked_mut passes a bare reference (not wrapped in Pin) to the closure, it would be unsound to apply optimizations such as those in https://github.com/rust-lang/rust/pull/106180 to the bare &mut T. (On the assumption that Pin<&mut T> would turn off those optimizations, due to being actually pinned.)

Oh I see. Yes that is a good question.

If the special exception applied to `Pin` and not the bare `&mut`, that would be a problem. But the PR you linked treats `&mut !Unpin` special inside and outside of `Pin`, for the exact reasons that otherwise `map_unchecked_mut` (and `get_unchecked_mut` and a bunch of other `Pin` functions) could not be used the way they are intended to. You will notice that `Pin` is not mentioned in https://github.com/rust-lang/rust/pull/106180.

So I will close this PR.
