### ISSUE TITLE
Closure with a typed function argument and top level struct constructor break in nightly

### ISSUE THREAD

**Issue by nicopap** [rust-lang/rust#107461]
### Code

I tried this code: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=7f3bdb07bcc3a0a30d2ef80cf0adfd22

```rust
let closure = |f: fn(&f32) -> f32| MyStruct { x: f(&y) };
```

This code should compile.

Instead of compiling, the compiler generates the following error:

```rust
error: anonymous enums are not supported
 --> src/main.rs:8:38
  |
8 |     let closure = |f: fn(&f32) -> f32| MyStruct { x: f(&y) };
  |                                   ---^ --------
  |
  = help: create a named `enum` and use it here instead:
          enum Name {
              Variant1(f32),
              Variant2(MyStruct),
          }

error: expected one of `!`, `(`, `,`, `::`, `<`, or `|`, found `{`
 --> src/main.rs:8:49
  |
8 |     let closure = |f: fn(&f32) -> f32| MyStruct { x: f(&y) };
  |                                                 ^ expected one of `!`, `(`, `,`, `::`, `<`, or `|`

error: could not compile `playground` due to 2 previous errors
```

### Version it worked on

It most recently worked on: (1.67)

### Version with regression

Breaks in latest nightly 1.69.0-nightly (2023-01-29 e972bc8083d5228536df)

Related:
* #106960
* #100988
*  #100741

**Comment by Nilstrieb** [comment]
Oh no, that's pretty bad.. @estebank @cjgillot 
As a workaround, creating a type alias for the function pointer type should work.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23107461.20Closure.20with.20a.20typed.20function.20argument.20and.20top.20leve.E2.80.A6)).

@rustbot label -I-prioritize +P-critical
