### ISSUE TITLE
Regression 1.66 "`some_fn::{opaque#0}<'_>` does not live long enough"

### ISSUE THREAD

**Issue by Dav1dde** [rust-lang/rust#107426]
### Code

Unfortunately I couldn't minimize it further without using a dependency (code can be executed online [here](https://www.rustexplorer.com/b)):

```rust
/*
[dependencies]
sycamore = "0.8.2"
web-sys = "0.3"

*/

use sycamore::prelude::{Scope, View, Html, DomNode, ReadSignal, GenericNode};

pub fn create_toggle_bool<'a>(cx: Scope<'a>, initial: bool) -> (&'a ReadSignal<bool>, impl Fn() + Copy + 'a) {
    // let open = sycamore::prelude::create_signal(cx, false);
    // let open_toggle = || open.set(!*open.get());
    // (open, open_toggle)
    (todo!(), || {})
}

pub fn Foo<G: Html>(cx: Scope) -> View<G> {
    let (open, open_toggle) = create_toggle_bool(cx, false);

    // Uncomment these 2 lines to make it compile (moved out of the function)
    // let open = sycamore::prelude::create_signal(cx, false);
    // let open_toggle = || open.set(!*open.get());

    let a = move |_: web_sys::Event| open_toggle();

    move || {
        let __el = DomNode::text_node("test");
        ::sycamore::generic_node::GenericNode::event(&__el, cx, "click", a);
        __el;
    };

    todo!()
}

fn main() {
}
```

* [`GenericNode`](https://github.com/sycamore-rs/sycamore/blob/0.8.2/packages/sycamore-core/src/generic_node.rs#L38)
* [`DomNode#event`](https://github.com/sycamore-rs/sycamore/blob/0.8.2/packages/sycamore-web/src/dom_node.rs#L326-L336)
* [My failed attempt to reduce it further](https://play.rust-lang.org/?version=beta&mode=debug&edition=2021&gist=6354ec84132bddbf7f89d24a32715b09)

The code compiles and runs with 1.66 but fails with 1.67:

```
error: `create_toggle_bool::{opaque#0}<'_>` does not live long enough
  --> src/main.rs:28:9
   |
28 |         ::sycamore::generic_node::GenericNode::event(&__el, cx, "click", a);
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I expect this code to still compile on 1.67

### Version it worked on

1.66

### Version with regression

1.67

```
rustc 1.67.0 (fc594f156 2023-01-24)
binary: rustc
commit-hash: fc594f15669680fa70d255faec3ca3fb507c3405
commit-date: 2023-01-24
host: x86_64-unknown-linux-gnu
release: 1.67.0
LLVM version: 15.0.6
```

**Comment by Teapot4195** [comment]
searched nightlies: from nightly-2022-09-15 to nightly-2022-10-15
regressed nightly: nightly-2022-09-26
searched commit range: https://github.com/rust-lang/rust/compare/3f83906b30798bf61513fa340524cebf6676f9db...f5193a9fcc73dc09e41a90c5a2c97fc9acc16032
regressed commit: https://github.com/rust-lang/rust/commit/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.5</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --end=2022-10-15 
```
</details>

**Comment by clubby789** [comment]
Minimized to:
```rs
use std::marker::PhantomData;
#[derive(Clone, Copy)]
pub struct Scope<'a>(&'a PhantomData<&'a mut &'a ()>);
fn event<'a, F: FnMut() + 'a>(_: Scope<'a>, _: F) {}
fn make_fn<'a>(_: Scope<'a>) -> impl Fn() + Copy + 'a {
    || {}
}

fn foo(cx: Scope) {
    let open_toggle = make_fn(cx);

    || event(cx, open_toggle);
}

fn main() {}
```
@rustbot label -E-needs-mcve

**Comment by clubby789** [comment]
> This is a **breaking change** but it is a necessary soundness fix
#95474

**Comment by Nilstrieb** [comment]
Since the crater run there found no regressions I'm gonna @oli-obk anyways but I don't think there's anything to do here.

**Comment by oli-obk** [comment]
Yea, this is expected breakage. We should improve the diagnostic though.

**Comment by Dav1dde** [comment]
Is the reduced example unsound?

I would expect `let open_toggle = make_fn(cx);` to behave the same as `let open_toggle = || {};`, is this assumption wrong?

**Comment by Nilstrieb** [comment]
The minimized example is not really unsound as in it doesn't contain UB - it doesn't do anything. But the feature that it uses is unsound. Such is the fate of a safe language, it often has "false positives".

**Comment by Dav1dde** [comment]
Thanks, but this is a bit advanced for me still, but if this is expected I can close the issue or do you want me to keep it open for better diagnostics?

**Comment by steffahn** [comment]
On my machine the original post as well as the reduced example regress in 1.66, not 1.67. Can someone confirm or deny this? If that’s true, than the title here would be misleading.

**Comment by oli-obk** [comment]
Godbolt agrees, this regressed in 1.66

**Comment by steffahn** [comment]
I only looked at this issue, because there’s been a thread on URLO on a similarly-looking issue that appears to _actually_ regress on 1.67: #107516

Mentioning it here, because it might be of interest to readers of this thread :-)

**Comment by Dav1dde** [comment]
This is weird, this only broke on my CI because it was pinned to stable (-> 1.67), my local machine was still compiling and running the code fine on 1.66. Maybe the reduced example already regressed in 1.66 but my corner case only regresses in 1.67?

**Comment by aliemjay** [comment]
This regression can indeed be mitigated (cc #108691), at least for the MCVE we have.
@rustbot label -A-diagonstics regression-from-stable-to-stable

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23107426.20Regression.201.2E66.20.22.60some_fn.3A.3A.7Bopaque.230.7D.3C'_.3E.60.20does.20not.E2.80.A6)).

@rustbot label -I-prioritize +P-medium
