### ISSUE TITLE
Projects with build scripts in deps generate too many profraws at build

### ISSUE THREAD

**Issue by xd009642** [rust-lang/rust#107447]
If you take a project with build scripts in the dependency tree such as https://github.com/CosmWasm/cw-plus and build it's tests without running them with instrument coverage turned on as so:

```
RUSTFLAGS="-Cinstrument-coverage" cargo test --no-run
```

This ends up with 244 profraw files, and they'll only contain coverage of `build.rs` files and build dependencies. I'm personally of the opinion that all these stats are useless. I imagine almost nobody is testing their build scripts, however with cargo-tarpaulin I have had people ask for build script coverage in the past... 

Either way I figured I'd raise it here as it would be nice if there was a way to disable this behaviour somehow.

**Comment by ehuss** [comment]
You can prevent instrumenting build scripts by using the `--target` flag.

**Comment by xd009642** [comment]
Target as in `--target <TRIPLE> Build for the target triple`? That's kinda curious I wouldn't expect them to interact given the help text :thinking:

**Comment by ehuss** [comment]
Yea. It is documented [here](https://doc.rust-lang.org/cargo/reference/config.html#buildrustflags) in the RUSTFLAGS docs.

**Comment by xd009642** [comment]
Fair enough, for tarpaulin I've gone with setting `LLVM_PROFILE_FILE` to `build_scripts.profraw` and deleting it, just because I know some user somewhere will be relying on RUSTFLAGS going to a build script and raise an issue if I switch to setting `--target` explicitly :smiling_face_with_tear: 

I'll close this as my query is solved :+1:
