### ISSUE TITLE
Missed optimization opportunity when trivially moving tuple of slices

### ISSUE THREAD

**Issue by recatek** [rust-lang/rust#107436]
Example code:

```rust
#[repr(C)]
pub struct ThreeSlices<'a>(&'a [u32], &'a [u32], &'a [u32]);

#[inline(always)]
pub fn should_be_no_op(val: ThreeSlices) -> ThreeSlices {
    val
}

pub fn sum_slices_1(val: ThreeSlices) -> u32 {
    sum(&val)
}

pub fn sum_slices_2(val: ThreeSlices) -> u32 {
    let val = should_be_no_op(val);
    sum(&val)
}

#[inline(never)]
pub fn sum(val: &ThreeSlices) -> u32 {
    val.0.iter().sum::<u32>() + val.1.iter().sum::<u32>() + val.2.iter().sum::<u32>()
}
```
In rustc 1.67 stable this generates a number of moves (I suppose for calling convention?) that I don't think need to be there, especially when inlining:
```
example::sum_slices_1:
        jmp     qword ptr [rip + example::sum@GOTPCREL]

example::sum_slices_2:
        sub     rsp, 56
        movups  xmm0, xmmword ptr [rdi]
        movups  xmm1, xmmword ptr [rdi + 16]
        movups  xmm2, xmmword ptr [rdi + 32]
        movaps  xmmword ptr [rsp + 32], xmm2
        movaps  xmmword ptr [rsp + 16], xmm1
        movaps  xmmword ptr [rsp], xmm0
        mov     rdi, rsp
        call    qword ptr [rip + example::sum@GOTPCREL]
        add     rsp, 56
        ret
```

See https://rust.godbolt.org/z/azs11edK8

While this is a pretty pointless example, this comes up in situations where you might want to convert a tuple of slices into a struct of slices in order to assign names to the tuple members.

**Comment by nikic** [comment]
Fixed as part of the LLVM 17 update (https://github.com/rust-lang/rust/pull/114048), needs codegen test.

**Comment by nikic** [comment]
> And I now think that preventing memcpy removal is the right, because the function may capture the argument.

Yes, the removal is only allowed in the original example, because the called function is known. It does not work with an unknown function due to missing `nocapture`.

> But rustc seems to annotate the original argument with nocapture

Note that the `nocapture` is on the by-value argument of `sum_slices_2`, not the by-reference argument of the function pointer `f`.

**Comment by nikic** [comment]
I don't think there is any missing attribution opportunity here. In your example, if `%val` is nocapture, then that does not imply anything about `%val1` being nocapture (it's a completely different object).

Even if you directly passed through the argument to the call (without intermediate memcpy to alloca), inferring nocapture is still not straightforward, because `nocapture` allows interior captures (i.e. it's possible to capture the pointer within the function, as long as it does not stay captured after the function returns).
