### ISSUE TITLE
ICE: Out of bounds when relating regions

### ISSUE THREAD

**Issue by viichi** [rust-lang/rust#107419]
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=d383ef3aefad236b54486affe9c59a27

```rust
#![feature(type_alias_impl_trait)]

use std::future::Future;
use std::io::Result;
use std::pin::Pin;

pub trait AsyncReadFrom: Sized {
    type Output<R>: Future<Output = Self>;

    fn async_read_from<R: Unpin>(r: &mut R) -> Self::Output<R>;
}

impl<T: AsyncReadFrom> AsyncReadFrom for (T,) {
    type Output<R> = impl Future<Output = Self>;

    fn async_read_from<R: Unpin>(r: &mut R) -> Self::Output<R> {
        let r = Pin::new(r);
        async move {
            while true {
                T::async_read_from(r.get_mut()).await;
            }
            loop {}
        }
    }
}
```

**Comment by clubby789** [comment]
searched nightlies: from nightly-2023-01-27 to nightly-2023-01-28
regressed nightly: nightly-2023-01-28
searched commit range: https://github.com/rust-lang/rust/compare/d7948c843de94245c794e8c63dd4301a78bb5ba3...ef982929c0b653436a6ea6892a2a839fba7c8b57
regressed commit: https://github.com/rust-lang/rust/commit/7919ef0ec5776c72dace7fec1c68551a617505ad

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.5</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start 2023-01-27 --end 2023-01-28  --regress ice 
```
</details>


@rustbot label +I-ICE +F-type_alias_impl_trait

**Comment by Nilstrieb** [comment]
Minimized it further:
```rust
use std::pin::Pin;

fn foo<Infer>(_: &mut Infer) {}

fn main() {
    let r = Pin::new(&mut ());
    foo(r.get_mut());
    foo(r.get_mut());
}
```
