### ISSUE TITLE
Tracking Issue for `BYTE_SLICE_IN_PACKED_STRUCT_WITH_DERIVE` lint

### ISSUE THREAD

**Issue by nnethercote** [rust-lang/rust#107457]
This is a tracking issue for the `BYTE_SLICE_IN_PACKED_STRUCT_WITH_DERIVE` lint, which is being added in https://github.com/rust-lang/rust/pull/104429. The lint detects cases where `derive` is used with a `packed` struct that contains a `[u8]` field.

### Example

This lint will trigger for code like this:

```rust
#[repr(packed)]
#[derive(Eq, PartialEq)]
pub struct FlexZeroSlice {
    width: u8,
    data: [u8], // triggered
}
```

At some point in the future this case will be disallowed.

See #104429 for more details, especially the [t-lang nomination](https://github.com/rust-lang/rust/pull/104429#issuecomment-1320909245).

**Comment by traviscross** [comment]
@rustbot labels +I-lang-nominated

Let's discuss whether we want to disallow this in Rust 2024.
