### ISSUE TITLE
cargo metadata fails on rust repo

### ISSUE THREAD

**Issue by parthopdas** [rust-lang/rust#107444]
I tried this code:

```ps1
cargo metadata --no-deps --format-version 1
```

I expected to see this happen: cargo to spit out the metadata for the workspace in json format 

Instead, this happened: same happens with cargo build / check.
![image](https://user-images.githubusercontent.com/2140460/215331033-3f20157d-8bd7-4e35-b7c8-aa91d30c3364.png)

Is this expected? If not I'll send a PR.

**Comment by albertlarsan68** [comment]
Hello,
It is semi-expected to not work, because there are submodules in the repo, that are not cloned by default.
Also, AFAIK interacting with the repository through cargo is not the intended way to do work, but rather using the `x.ps1` (on Windows) script present at the root of the repo. See the [rustc-dev-guide](https://rustc-dev-guide.rust-lang.org/getting-started.html) for the workflows used by this repository.

**Comment by ehuss** [comment]
Yea, you need to initialize the submodules first (`git submodule update --init`).

> AFAIK interacting with the repository through cargo is not the intended way to do work, 

It's OK to run commands like `cargo metadata` or `cargo tree`. There's also quite a few projects in the tree that work just fine with `cargo build` or `cargo run`.

**Comment by albertlarsan68** [comment]
> Yea, you need to initialize the submodules first (`git submodule update --init`).

Initializing this way is not the recommended way, because it also clones llvm, which is big. The `x` script will clone the submodules as necessary.

**Comment by ehuss** [comment]
> The `x` script will clone the submodules as necessary.

Yea, unfortunately there isn't an explicit command to just initialize the submodules. I believe `./x.py help -v` will do that, but I'm not sure if that is reliable long-term.  Personally, the presence of llvm-project doesn't bother me.

> You can't do that in the root, because there is nothing to build. The `src/tools/x` tool is an example of this kind of tool, but the majority of tools are far better used through `x`.

Cargo should work fine in the root. For example, `cargo build -p cargo`. I would say there are at least 20 projects that should work without `x`. I also regularly use cargo directly for the compiler and standard library, those only need a few environment variables set (though that is an advanced workflow). Of course some tools are best used via `x`, but I wouldn't characterize it as all of them.

**Comment by parthopdas** [comment]
ok that makes sense, it is convered in the readme as well. closing this issue.
