### ISSUE TITLE
Inherent associated type projections are incorrectly substituted

### ISSUE THREAD

**Issue by fmease** [rust-lang/rust#107468]
The following code should compile since for `Subj<(i32,)>` one has `T == i32` and thus `Subj::Un == i32`. However, the current implementation incorrectly substitutes `T` with `(i32,)` leading to a compile error after encountering the let-statement.

```rust
#![feature(inherent_associated_types)]
#![allow(incomplete_features)]

struct Subj<T>(T);

impl<T> Subj<(T,)> {
    type Un = T;
}

fn main() {
    let _: Subj::<(i32,)>::Un = 0i32;
}
```

```
error[E0308]: mismatched types
  --> src/main.rs:11:33
   |
11 |     let _: Subj::<(i32,)>::Un = 0i32;
   |            ------------------   ^^^^ expected tuple, found `i32`
   |            |
   |            expected due to this
   |
   = note: expected tuple `(i32,)`
               found type `i32`
help: use a trailing comma to create a tuple with one element
   |
11 |     let _: Subj::<(i32,)>::Un = (0i32,);
   |                                 +    ++
```

---

For comparison, the analogous program involving inherent associated *functions* successfully compiles:

```rust
struct Subj<T>(T);

impl<T: Default> Subj<(T,)> {
    fn un() -> T { T::default() }
}

fn main() {
    let _: i32 = Subj::<(i32,)>::un();
}
```

@rustbot label T-compiler requires-nightly F-inherent_associated_types
@rustbot claim

**Comment by compiler-errors** [comment]
same root cause, please add this as a test when you fix this @fmease:

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=b267739cce2e6be9f50bb4bf0c3dbd85

**Comment by fmease** [comment]
#105305 related
