### ISSUE TITLE
Implement thin archive reading for ArArchiveBuilder

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#107407]
Needs to be done before https://github.com/rust-lang/rust/pull/107360 can be reverted.

**Comment by ChrisDenton** [comment]
Tbh, I am somewhat surprised that people are using thin archives on Windows.

**Comment by bjorn3** [comment]
cc https://github.com/rust-lang/rust/issues/107162

**Comment by bjorn3** [comment]
Object now supports reading thin archives. Waiting for a release to wire it up in rustc.

**Comment by bjorn3** [comment]
https://github.com/rust-lang/rust/pull/128936 implements this.
