### ISSUE TITLE
Regression 1.67.0: Static archives have different unix permissions than before

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#107495]
Given this code:

```rust
#[no_mangle]
pub extern "C" fn foo() {}
```

I get this output from rustc:

```
$ rustc +1.66.1 foo.rs --crate-type staticlib && ls -alh libfoo.a
-rw-r--r-- 1 acrichto acrichto 22M Jan 30 16:28 libfoo.a
$ rustc +1.67.0 foo.rs --crate-type staticlib && ls -alh libfoo.a
-rw------- 1 acrichto acrichto 22M Jan 30 16:28 libfoo.a
```

The most recent archive no longer has the "read" permission bit set for group/world owners. This ended up breaking [Wasmtime's build](https://github.com/bytecodealliance/wasmtime/actions/runs/4048924720/jobs/6964738137) because our files are built in a container with a different user and aren't then readable outside of the container. There's no particular reason we do this and we can work around this, but I also suspected that the change in permissions here probably wasn't intentional.

I think this is due to https://github.com/rust-lang/rust/pull/97485 (cc @bjorn3), specifically [this line](https://github.com/rust-lang/rust/blob/001a77fac33f6560ff361ff38f661ff5f1c6bf85/compiler/rustc_codegen_ssa/src/back/archive.rs#L279). I haven't dug too deeply but my guess is that temp files specifically turn off other permission bits

**Comment by bjorn3** [comment]
https://github.com/rust-lang/rust/pull/107360 reverted back to the LLVM archive writer to fix another regression. Still I think this issuw should be kept open as a reminder to fix the new archive writer before it becomes the default again.

**Comment by jyn514** [comment]
cc https://github.com/rust-lang/rust/issues/107407, which also needs to be fixed before relanding the archive writer change. BTW @bjorn3 is there a tracking issue for that somewhere? I see the original PR linked to https://github.com/bjorn3/rustc_codegen_cranelift/issues/1155, but it hasn't been reopened.

**Comment by bjorn3** [comment]
I have kept all issues that need to be fixed before it can land again in my github notifications. There is currently no tracking issue, but feel free to open one. It did probably be a good idea to ensure no issue is forgotten about.
