### ISSUE TITLE
Suggested rust-analyzer config can't run rustfmt

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#107547]
https://github.com/rust-lang/rust/pull/107297 broke the rust-analyzer config we suggest in the dev-guide: https://rustc-dev-guide.rust-lang.org/building/suggested.html#configuring-rust-analyzer-for-rustc
```json
    "rust-analyzer.rustfmt.overrideCommand": [
        "./build/host/stage0/bin/rustfmt",
        "--edition=2021"
    ],
```
since now rustfmt is in `build/host/rustfmt/bin/rustfmt` instead of `build/host/stage0/bin/rustfmt`.

_Originally posted by @jyn514 in https://github.com/rust-lang/rust/pull/107297#discussion_r1092764740_

**Comment by zephaniahong** [comment]
Hi! Just to clarify, the idea is to change to code to match the docs?

**Comment by albertlarsan68** [comment]
I think the idea is changing the docs to match the new behavior.

**Comment by zephaniahong** [comment]
For reference: https://github.com/rust-lang/rustc-dev-guide/pull/1574

**Comment by jyn514** [comment]
I'd prefer to change the code so that we don't force all contributors to update their config.

**Comment by Mark-Simulacrum** [comment]
I suppose we could try to create a symlink from the old path to the new one? That might work, not sure.

**Comment by albertlarsan68** [comment]
Maybe add a proxy?
On Linux it might just be
```sh
#!/usr/bin/sh
exec ../rustdoc $* #FIXME make this syntax correct
```

**Comment by jyn514** [comment]
A symlink seems like a good solution to me.

**Comment by albertlarsan68** [comment]
Does the symlink still finds the correct so?

**Comment by zephaniahong** [comment]
I'll experiment adding a symlink.

**Comment by albertlarsan68** [comment]
On Windows, creating a symlink does not find the needed DLLs.
Trying to execute the symlink pops two msgbox saying that it doesn't find the `rustc_driver` and `std` DLLs.
You would need to symlink also the DLLs.
On Linux, it does find the correct SOs.

**Comment by kadiwa4** [comment]
Symlinking also works on macOS.

**Comment by jyn514** [comment]
> On Windows, creating a symlink does not find the needed DLLs. Trying to execute the symlink pops two msgbox saying that it doesn't find the `rustc_driver` and `std` DLLs. You would need to symlink also the DLLs. On Linux, it does find the correct SOs.

Ok, this is pretty messy. How about doing both:
- Add the symlink, which will work with both the old and new config on Mac and Linux
- Update the recommended config in the dev-guide, which will help contributors fix the error message on Windows

and from there we can work long-term to using the same toolchain for rustfmt and other tools, without having a time pressure.

**Comment by jyn514** [comment]
> and from there we can work long-term to using the same toolchain for rustfmt and other tools, without having a time pressure.

cc https://github.com/rust-lang/rustfmt/issues/4884, https://github.com/rust-lang/rustfmt/pull/3900

**Comment by zephaniahong** [comment]
May I get some guidance and the creation of the symlink? Do I use rust to create the symlink in `src/bootstrap/download.rs` after the rustfmt_path line or do I use a bash command? If I do use a bash command, is there a file I should be adding it to?

Thank you!

**Comment by jyn514** [comment]
@zephaniahong use https://github.com/rust-lang/rust/blob/99529b0cd2022c9002fd4f5fef119ba4ca100b81/src/bootstrap/lib.rs#L1593

**Comment by zephaniahong** [comment]
And just to confirm, I use that symlink function here?
https://github.com/rust-lang/rust/blob/11d96b59307b1702fffe871bfc2d0145d070881e/src/bootstrap/download.rs#L332-L333

**Comment by jyn514** [comment]
yes

**Comment by bjorn3** [comment]
I think it would be possible to move rustfmt back to the same sysroot as the bootstrap compiler by only taking libstd.so, librustc_middle.so and libLLVM.so from the nightly rustc component and not copying any other files like the rustc binary. Libstd.so and librustc_middle.so both contain a hash in their name unique for each rustc version. libLLVM.so should contain the rustc version, so that shouldn't conflict either.

**Comment by albertlarsan68** [comment]
Doing the same with the DLLs on Windows could also work.

**Comment by est31** [comment]
related (different error with rustfmt, but caused by the same change): #107676

**Comment by jyn514** [comment]
Hi @zephaniahong, any progress on the symlink? happy to help out if you're running into trouble :)

**Comment by zephaniahong** [comment]
Hey @jyn514 ! Thanks for reaching out! I'll be starting tomorrow and will reach out to you if/when I need help! 
Apologies for the delay!
