### ISSUE TITLE
Update MinGW Binutils to the latest version on Stable

### ISSUE THREAD

**Issue by awaken466** [rust-lang/rust#107575]
Current version of MinGW Binutils is 2.26, latest is 2.37

**Comment by nikic** [comment]
Is this on current nightly (that is after https://github.com/rust-lang/rust/pull/100178)?

**Comment by ChrisDenton** [comment]
I'm seeing 2.38 in the latest builds (and mingw at 12.2.0).

**Comment by awaken466** [comment]
> I'm seeing 2.38 in the latest builds (and mingw at 12.2.0).

check your environment path, maybe there some other mingw, rust uses mingw from environment variable

**Comment by ChrisDenton** [comment]
I was speaking of nightly. On current stable and beta it's 2.27. I think it's unlikely that newer tools will be backported to stable unless there's a specific problem that makes it a priority.

**Comment by mati865** [comment]
We shouldn't backport that upgrade, it's too risky.
The upgrade has broke raw-dylib in some cases https://github.com/rust-lang/rust/pull/107752 and who knows what else.

**Comment by riverar** [comment]
@mati865 I don't think #107752 means much for this issue. The version of dlltool used in stable (2.26) uses a temporary prefix of `getpid()` ([source](https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=binutils/dlltool.c;h=2d404d24a6624d833b5c79da5b1d6b35a5f3a924;hb=c29838e7f484e0b5714b02e7feb9a88d3a045dd2#l4236)) which isn't ideal given pid reuse is possible.

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/pull/100178 landed in 1.69, which will be stable in 12 days. I feel pretty confident a stable backport isn't warranted given the risk and the fact 1.69 is releasing so soon.

**Comment by mati865** [comment]
It's not exactly the latest version but it's fairly recent (2.38 IIRC).
