### ISSUE TITLE
Bad MIR: StorageLive on a local that was already live with opt-level=4

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#107511]
Consider this code:
```rust
fn main() {
    let mut sum = 0;
    let a = [0, 10, 20, 30];
    for i in 0..a.len() {
        sum += a[i];
    }
    println!("{sum}");
}
```
When running this in Miri with `-Zmir-opt-level=4 -O`, we get an error:
```
error: Undefined Behavior: StorageLive on a local that was already live
 --> tests/pass/loops.rs:4:9
  |
4 |     for i in 0..a.len() {
  |         ^ StorageLive on a local that was already live
  |
  = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
  = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
  = note: BACKTRACE:
  = note: inside `main` at tests/pass/loops.rs:4:9: 4:10
```
This is a fairly recent regression (ad48c109815a2e9441a7ad7796e55b8771fe01a5 was good, a322848c6b0e037c1f0209387558ecb6ab763714 is bad; commit range: https://github.com/rust-lang/rust/compare/ad48c109815a2e9441a7ad7796e55b8771fe01a5...a322848c6b0e037c1f0209387558ecb6ab763714).

Cc @rust-lang/wg-mir-opt

**Comment by RalfJung** [comment]
#106908 landed in that range, seems like the most likely culprit? Cc @cjgillot

**Comment by matthiaskrgr** [comment]
@RalfJung what does the `-O` flag do? I couldn't find it mentioned in the readme. :/

**Comment by RalfJung** [comment]
That's the regular `rustc -O`, turning on optimizations.
