### ISSUE TITLE
Consider using an embedded libm

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#10774]
For performance and consistency reasons, we might want to bundle our own libm. It further reduces our dependency on system libraries, opens the potential for LTO, and gives us something we can control and define.

A good candidate is [openlibm](https://github.com/JuliaLang/openlibm/), which has a long history.

See https://github.com/mozilla/rust/issues/5702, https://github.com/mozilla/rust/issues/1222

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#711
