### ISSUE TITLE
Create `.vscode` directory in `x.py setup`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#107703]
Right now, .vscode needs to be configured anew for each workspace and person working on the compiler. We do document the recommended settings in https://rustc-dev-guide.rust-lang.org/building/suggested.html#configuring-rust-analyzer-for-rustc, but it's annoying to have to copy-paste it each time. It would be nice if `x setup` created those files for you automatically.

Ideally we would even version the config (maybe with a stamp file so it's not in the `settings.json` file itself) and suggest rerunning `x setup` in `tidy` if the config in .vscode gets outdated.

cc https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/False.20error.20report.20for.20.60rust-analyzer.28private-field.29.60 - it might be the case that the settings vary depending on the part of the compiler you're working on? I would *really* hate for that to be the case, but having per-profile .vscode setup might be one way to make it less painful :/

**Comment by jyn514** [comment]
I also considered checking `.vscode` into git, but that doesn't allow people to modify it locally, and doesn't allow the config to be different depending on the profile.

**Comment by thomcc** [comment]
I think this is fine so long as `x setup` prompts the user asking if they want this, with options for yes/no/print, where print just dump the settings json it wants to add to stdout.

And probably if .vscode/settings.json already exists you should just always print instead of trying to modify it in-place (modifying sounds hard since that file allows comments, and i would be pretty mad if they got overwritten).

**Comment by jyn514** [comment]
👍 sounds good - we do something like that today for the pre-push hook: https://github.com/rust-lang/rust/blob/4aa6afa7f8a418a7dae5dbe4c95371d4f3bcc0e1/src/bootstrap/setup.rs#L375-L389

**Comment by jyn514** [comment]
Prior art: https://github.com/rust-lang/rust-clippy/blob/8a9860901f0ae9782ff23fb793838a16f733a60b/clippy_dev/src/setup/vscode.rs
