### ISSUE TITLE
improving error message when returning an opaque type inside an if else block

### ISSUE THREAD

**Issue by vincenzopalazzo** [rust-lang/rust#107899]
### Code

```Rust
async fn async_dummy() {}

async fn async_dummy2() {}


fn main() {
    let _ = if true {
        async_dummy()
    } else {
        async_dummy2()
    };
}
```

### Current output

```Shell
Compiling playground v0.0.1 (/playground)
error[E0308]: `if` and `else` have incompatible types
  --> src/main.rs:10:9
   |
7  |       let _ = if true {
   |  _____________-
8  | |         async_dummy()
   | |         ------------- expected because of this
9  | |     } else {
10 | |         async_dummy2()
   | |         ^^^^^^^^^^^^^^ expected opaque type, found a different opaque type
11 | |     };
   | |_____- `if` and `else` have incompatible types
```

### Rationale and extra context

We start a discussion on zulip regarding this that is available [here](https://rust-lang.zulipchat.com/#narrow/stream/187312-wg-async/topic/future.20all.20inside.20the.20if.20else.20as.20return.20value) where we noted that this suggestion is not helpful at all, but also we noted that it is difficult make a helpful suggestion in this case because there is the question that a user may ask to himself when reading the error message:

1.  What is it an opaque type?
2. `Future<Output = ()>`  is equal to `Future<Output = ()>`
3. Why two futures are not equal?a

### Anything else?

A possible solution for this can be:

- Do not try to be too smart in some corner case like this, and in this case, I would like an error like `You can not return two different futures inside an if-else block. rustc --explain ...`
- make a specific explanation on why we can not compare these two types
- In case of the future generate a note that the user may want to call await on each branch
- change the `opaque type` string into `future` string when applicable

**Comment by sladyn98** [comment]
@vincenzopalazzo Where do I add the helpful error message, a good starting point would be helpful

**Comment by vincenzopalazzo** [comment]
@sladyn98 this PR https://github.com/rust-lang/rust/pull/107902 is not helping you?

**Comment by sladyn98** [comment]
@vincenzopalazzo This is my first contribution to the compiler so I am still getting used to a bit of the codebase, I can see some functions that construct messages about future in PR https://github.com/rust-lang/rust/pull/107902, but I am not quite sure under which one would this new message come ? Sorry if the question does not make much sense, but I am still trying to understand the codebase

**Comment by sladyn98** [comment]
https://github.com/rust-lang/rust/blob/HEAD/compiler/rustc_middle/src/ty/error.rs#L95-L96 I found out that the error is being built from here and the if else block is here https://github.com/rust-lang/rust/blob/HEAD/compiler/rustc_infer/src/infer/error_reporting/mod.rs#L801

I think I can understand the flow, the IfExpression cause is generated here, from where the error is constructed

self.cause(
            error_sp,
            ObligationCauseCode::IfExpression(Box::new(IfExpressionCause {
                else_id,
                then_id,
                then_ty,
                else_ty,
                outer_span,
                opt_suggest_box_span,
            })),
        )
        
I am wondering if the async type checks would be done just before this line so that the message could be changed
```
if let Some(sp) = outer_span {
err.span_label(sp, "if and else have incompatible types");
}
```

**Comment by vincenzopalazzo** [comment]
When I was trying to run this with master I found that my https://github.com/rust-lang/rust/pull/107902 now fixed also this?

So closing as resolved, this is the error message that we want

```
➜  rust git:(macros/opaque-and-if-else) ✗ ./build/x86_64-unknown-linux-gnu/stage1/bin/rustc test.rs --edition 2021
error[E0308]: `if` and `else` have incompatible types
  --> test.rs:10:9
   |
7  |       let _ = if true {
   |  _____________-
8  | |         async_dummy()
   | |         ------------- expected because of this
9  | |     } else {
10 | |         async_dummy2()
   | |         ^^^^^^^^^^^^^^ expected future, found a different future
11 | |     };
   | |_____- `if` and `else` have incompatible types
   |
   = note: distinct uses of `impl Trait` result in different opaque types
help: consider `await`ing on both `Future`s
   |
8  ~         async_dummy().await
9  |     } else {
10 ~         async_dummy2().await
   |

error: aborting due to previous error

```
