### ISSUE TITLE
Realloc is a bit confusing

### ISSUE THREAD

**Issue by Alexevier** [rust-lang/rust#107875]
### Location

https://doc.rust-lang.org/std/alloc/trait.GlobalAlloc.html#method.realloc

### Summary

Realloc (in the trait for GlobalAlloc) is confusing in my opinion, what means the `new_size` parameter?
The size in bytes or how many times the size that is inside the layout?
In the way it is written seems to mean the bytes but it should be explicit that it means the size in bytes.

**Comment by workingjubilee** [comment]
Thank you! I added a clarification to the docs (it is in bytes).

**Comment by Alexevier** [comment]
thank you, for taking to look into this
