### ISSUE TITLE
Windows' `symlink_junction_inner` mysteriously fails

### ISSUE THREAD

**Issue by ChrisDenton** [rust-lang/rust#107884]
I think [`symlink_junction_inner`](https://github.com/rust-lang/rust/blob/a6975734632c4771edd45ef10e7d4753541d0f3a/library/std/src/sys/windows/fs.rs#L1382) sometimes isn't writing to the buffer properly which can cause the `DeviceIoControl` to fail and thus tests that use it. This function isn't great and is only used in tests. I can reproduce this consistently locally on current master but in CI most PRs seem to test ok (though [not all](https://github.com/rust-lang/rust/pull/107167)).

I've not really investigated yet but on a hunch I added the following which seems to fix it locally, I don't know why or if it's a fluke:

```diff
diff --git a/library/std/src/sys/windows/fs.rs b/library/std/src/sys/windows/fs.rs
index 37809803828..d7f1a44bdf4 100644
--- a/library/std/src/sys/windows/fs.rs
+++ b/library/std/src/sys/windows/fs.rs
@@ -1409,6 +1409,8 @@ fn symlink_junction_inner(original: &Path, junction: &Path) -> io::Result<()> {
         (*db).ReparseTargetLength = ((i - 1) * 2) as c::WORD;
         (*db).ReparseDataLength = (*db).ReparseTargetLength as c::DWORD + 12;

+        crate::hint::black_box(slice::from_raw_parts(buf, i));
+
         let mut ret = 0;
         cvt(c::DeviceIoControl(
             h as *mut _,
```

**Comment by workingjubilee** [comment]
cursed.

**Comment by ChrisDenton** [comment]
I had another quick thought and replaced the `for` loop with the `for_each` iterator function. That seems to fix it too. Some bad interaction between iterators and loops perhaps?

**Comment by ChrisDenton** [comment]
Hm, this has been the same since forever in Rust so it'd be surprising for it to suddenly break now.

Oh! But now I've woken up I realised something. We're not zeroing the structure. I can't believe I missed that! So we're likely putting random data into the reserved parameters.

**Comment by ChrisDenton** [comment]
But yes, this function is awful and should be rewritten. Good job it's only used in tests.
