### ISSUE TITLE
rustdoc: docs.rs text style error after brew install font-fira-sans

### ISSUE THREAD

**Issue by meritozh** [rust-lang/rust#107805]
### Location

after `brew install font-fira-sans`，docs.rs will render strange text. seems unicode point doesn't match?

```
brew info font-fira-sans
==> font-fira-sans: 4.202
https://mozilla.github.io/Fira/
Not installed
From: https://github.com/Homebrew/homebrew-cask-fonts/blob/HEAD/Casks/font-fira-sans.rb
==> Name
Fira Sans
==> Description
None
```

run in macOS 13.1

### Summary

before install font:
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/7543300/217584805-9bbe4161-3139-42cd-aaf4-c1cc8bef38aa.png">

after install font:
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/7543300/217584999-ac994330-59e1-4315-a29d-1131b0873fdb.png">

**Comment by Nemo157** [comment]
Can you test on a local `cargo doc --no-deps --open` too to see whether this impacts `rustdoc` or just docs.rs?

**Comment by Nemo157** [comment]
It appears that both rustdoc and docs.rs use the 4.202 version (a version mismatch wouldn't matter anyway, there's nothing weird going on [with loading the font](https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/static/css/rustdoc.css#L10)).

Another thing to test would be using Fira Sans in something like TextEdit to check if homebrew is just installing a broken file somehow.

**Comment by meritozh** [comment]
@Nemo157 strange, I cannot reproduce this issue. close it, will reopen if I encounter it again
