### ISSUE TITLE
blob/master/RELEASES.md has not been updated

### ISSUE THREAD

**Issue by winksaville** [rust-lang/rust#107859]
The latest release is 1.67.1 as can be seen on [blob/stable/RELEASES.md](https://github.com/rust-lang/rust/blob/stable/RELEASES.md), but the master branch has not been updated and is showing 1.67.0 [blob/master/RELEASES.md](https://github.com/rust-lang/rust/blob/master/RELEASES.md).

**Comment by jyn514** [comment]
cc @cuviper, I think https://github.com/rust-lang/rust/pull/107743/commits/30e7b0510a023e4ee39f97f6650242d9aaeec8e0 needs to be cherry picked to beta and nightly as well (minus the change to src/version)

**Comment by cuviper** [comment]
See #107861.

**Comment by cuviper** [comment]
Yes, I think there's a bot that will pick that up from master.
