### ISSUE TITLE
Type parameters on statics

### ISSUE THREAD

**Issue by bjz** [rust-lang/rust#10798]
Would this be possible?

~~~rust
pub enum Reply<V, StopReason> {
    Reply(V),
    Stop(StopReason),
}

pub static Continue<StopReason>: Reply<(), StopReason> = Reply(());
~~~

I guess it would be less useful than the [C++14 proposal](http://isocpp.org/files/papers/N3651.pdf) seeing as our constexprs are currently so limited.

**Comment by alexcrichton** [comment]
Issues of this kind now belong in the RFC repo, so closing.

**Comment by mbrubeck** [comment]
Similar to https://github.com/rust-lang/rfcs/issues/2130
