### ISSUE TITLE
`src/tools/x` doesn't work on old checkouts of the compiler

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#107907]
Since https://github.com/rust-lang/rust/pull/105844, src/tools/x unconditionally looks for the shell scripts when running. That's good in most cases because it avoids having to run python. However, on old checkouts the shell scripts don't exist and it needs to fall back to using python.

cc @albertlarsan68, do you have time to fix this?

**Comment by albertlarsan68** [comment]
@rustbot claim
If it can wait for the weekend to pass, then yes.
Anyone, feel free to claim of you can do it in the weekend

**Comment by zephaniahong** [comment]
@albertlarsan68 i could help! Could you give me some pointers on what needs to be done?

**Comment by albertlarsan68** [comment]
What you should do is re-add the code that was removed in #105844, using it when the shell scripts are not found, but x.py is.
You could even add an env var that forces the use of python, but that's a later step.

**Comment by zephaniahong** [comment]
I see! Okay I'll give this a shot! But I may need more time than just the weekends. If it's urgent then feel free to take it away from me😅
@rustbot claim

**Comment by jyn514** [comment]
> You could even add an env var that forces the use of python, but that's a later step.

I don't think this is necessary, there shouldn't be any functionality that's available in python but not shell.

**Comment by albertlarsan68** [comment]
It is future-proofing for when python does get used only when building bootstrap, and the shell scripts won't be able to call python

**Comment by jyn514** [comment]
That can be done with a function argument so it's not exposed to users.

**Comment by albertlarsan68** [comment]
Yes, it can work like this.

**Comment by zephaniahong** [comment]
Hi @jyn514 ! Currently working on this. Could you list out the steps needed to replicate this issue so I could get a bit more context on the problem? 

Thank you!

**Comment by jyn514** [comment]
@zephaniahong install it from a current version of the repository, then check out any commit from before https://github.com/rust-lang/rust/commit/c16b969f1d4ae9882181e4af2155e57fc061f6f8 and run `x --help`. It will says "x.py not found" even though it exists in the repository.

**Comment by jyn514** [comment]
Err sorry, that was the commit that changes src/tools/x - you want the commit that initially added the ./x and x.ps1 scripts.

**Comment by zephaniahong** [comment]
Okay! Is there a smart way of looking for that particular commit?

**Comment by albertlarsan68** [comment]
One reason may be because they work on a pr that started before this commit, and that (miraculously) didn't conflict.

Another reason would have been because the work was done on stable/beta, but I think the scripts are now on stable (correct me if I'm wrong)
