### ISSUE TITLE
Cargo doc spuriously links to random enum variant fields instead of marking links broken

### ISSUE THREAD

**Issue by tnull** [rust-lang/rust#107903]
### Problem

In https://github.com/lightningdevkit/rust-lightning/pull/2027 we stumbled across a bug in `cargo doc`, as it checking for broken links didn't work for a now renamed field that is also present in another `enum` variant.

### Steps

A minimal example is this, which doesn't fail, but should:
```Rust
#![deny(broken_intra_doc_links)]

/// Referring to [`TestEnum::Variant1::field_name`]
pub enum TestEnum {
	Variant1 {},
	Variant2 {
		field_name: u64,
	}
}
```

If `TestEnum::Variant1::field_name` is present the docs indeed link to the right variant. If it is missing, `cargo doc` gladly makes the `TestEnum::Variant1::field_name` link point to `TestEnum::Variant2::field_name`, without throwing an error.

### Version
```
> cargo --version
cargo 1.65.0 (4bc8f24d3 2022-10-20)
```

**Comment by ehuss** [comment]
Transferred to rust-lang/rust, as rustdoc issues are tracked here.

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/blob/3574b1a69aebccbafc49096257317bb322c67025/src/librustdoc/passes/collect_intra_doc_links.rs#L341 probably needs to consider `variant_name`, not just `variant_field_name` and `path`.

**Comment by jyn514** [comment]
https://doc.rust-lang.org/stable/nightly-rustc/rustc_middle/ty/adt/struct.AdtDef.html#method.variant_with_id is likely what you want and from there you can iterate `variant.fields`.
