### ISSUE TITLE
rustdoc regression: intra-doc-links not working in proc-macro crate since nightly-2023-02-12

### ISSUE THREAD

**Issue by taiki-e** [rust-lang/rust#107950]
### Code

I ran `cargo doc` with this code:

```toml
# Cargo.toml
[package]
name = "repro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
```

```rust
/// [`Unpin`]
#[proc_macro_derive(F)]
pub fn derive_(t: proc_macro::TokenStream) -> proc_macro::TokenStream {
    t
}

/// [`Unpin`]
#[proc_macro_attribute]
pub fn attr(t: proc_macro::TokenStream, _: proc_macro::TokenStream) -> proc_macro::TokenStream {
    t
}

/// [`Unpin`]
#[proc_macro]
pub fn func(t: proc_macro::TokenStream) -> proc_macro::TokenStream {
    t
}
```

I expected to see this happen: intra-doc-links work and no warning

Instead, this happened:

intra-doc-links is not working in the generated docs.

<img width="215" alt="doc" src="https://user-images.githubusercontent.com/43724913/218303490-6b405f56-4b1b-4789-ab49-4c389d36a3fe.png">

And I got broken_intra_doc_links warnings:

```
warning: unresolved link to `Unpin`
 --> src/lib.rs:1:7
  |
1 | /// [`Unpin`]
  |       ^^^^^ no item named `Unpin` in scope
  |
  = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
  = note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default

warning: unresolved link to `Unpin`
 --> src/lib.rs:7:7
  |
7 | /// [`Unpin`]
  |       ^^^^^ no item named `Unpin` in scope
  |
  = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: unresolved link to `Unpin`
  --> src/lib.rs:13:7
   |
13 | /// [`Unpin`]
   |       ^^^^^ no item named `Unpin` in scope
   |
   = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
```

### Version it worked on

It most recently worked on: nightly-2023-02-11

<img width="215" alt="doc-old" src="https://user-images.githubusercontent.com/43724913/218303625-b7b0d65b-1bea-4b77-9518-c58ea60b117a.png">

### Version with regression

`rustc --version --verbose`:
```
rustc 1.69.0-nightly (585f3eef2 2023-02-11)
binary: rustc
commit-hash: 585f3eef26f04440bca726c29193af7b4fa90e54
commit-date: 2023-02-11
host: aarch64-apple-darwin
release: 1.69.0-nightly
LLVM version: 15.0.7
```

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/107951.

**Comment by Megadash452** [comment]
This seems to still be a problem with re-exports of proc-macros, except that `cargo doc` does not give any warnings. The only intra-doc-links that work are for other macros defined by that proc-macro crate.

Using a library crate on 1.83.0, but I also noticed this on earlier versions.
