### ISSUE TITLE
lto doesn't remove useless function in panic!

### ISSUE THREAD

**Issue by bigdogs** [rust-lang/rust#108077]
Hi

When `panic=abort` and  `panic=panic_immediate_abort` is enable, as my understanding, function `get_last_err` called  in `panic!` macro should not be executed and should be removed by `lto` in the end,

```rust
#[inline(never)]
fn get_last_err() -> std::io::Result<()> {
    println!("HELLO, WORLD");
    println!("GOOD. GOOD");
    Err(std::io::Error::last_os_error())
}
fn main() {
    panic!("function is not stripped: {:?}", get_last_err());
}
```

but it remains in the final binary:
![image](https://user-images.githubusercontent.com/20614926/219004017-655956fa-d32a-40b2-a8c9-7cc865b7f906.png)

remove this functions could help to reduce binary size, after all, most users specify `panic=abort` are for smaller binary 

Cargo.toml
```
[profile.release]
panic = "abort"
lto = true
codegen-units = 1
```
build command:
```
cargo +nightly build -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --target x86_64-pc-windows-msvc --release
```

```
PS C:\Users\Admin\Working> rustc --version --verbose
rustc 1.69.0-nightly (0416b1a6f 2023-02-14)
binary: rustc
commit-hash: 0416b1a6f6d5c42696494e1a3a33580fd3f669d8
commit-date: 2023-02-14
host: x86_64-pc-windows-msvc
release: 1.69.0-nightly
LLVM version: 15.0.7
```

**Comment by bjorn3** [comment]
This is expected. panic_immediate_abort only disables formatting and printing the panic message and calling the panic handler. Arguments to panic!() are still evaluated as this happens before the function initiating the panic is called. Only this function is changed by panic_immediate_abort.

**Comment by bigdogs** [comment]
Get it.   though I think there is potential for binary optimization in this case,  the result of `get_last_error` could be marked as unused on `panic_immediate_abort`, then `get_last_error` itself can have a chance to be removed.

**Comment by bjorn3** [comment]
The result of `Error::last_os_error()` is already considered unused, but on Windows this calls `GetLastError` which is a foreign function for which the compiler doesn't know that it doesn't have any side-effects and thus doesn't consider safe to remove.
