### ISSUE TITLE
Diagnostic when Fn*-family trait bounds is missing parens could be improved

### ISSUE THREAD

**Issue by Fishrock123** [rust-lang/rust#108109]
### Code

```Rust
fn handle<F>() where F: FnOnce -> () {}
```

### Current output

```Shell
error: expected one of `(`, `+`, `,`, `::`, `<`, or `{`, found `->`
 --> src/main.rs:1:32
  |
1 | fn handle<F>() where F: FnOnce -> () {}
  |                                ^^ expected one of `(`, `+`, `,`, `::`, `<`, or `{`
```

### Desired output

```Shell
error: expected `(`, found `->`
 --> src/main.rs:1:32
  |
1 | fn handle<F>() where F: FnOnce -> () {}
  |                               ^ `Fn*`-family trait bounds must be followed by parentheses
help: try using parenthesis here:
  |
1 | fn handle<F>() where F: FnOnce() -> () {}
  |                               ^^
```

### Rationale and extra context

It feels like rustc should be able to determine that a trait followed by a `->` is a `Fn*`-family trait bound and be able to suggest this behavior. If that is too general it could just check for `Fn`, `FnOnce`, `FnMut`.

### Other cases

~~Not that i know of...~~

Very similar is if parenthesis are missing from regular `fn` declarations:
```Shell
error: expected one of `(` or `<`, found `->`
 --> src/lib.rs:3:9
  |
3 | fn main -> () {}
  |         ^^ expected one of `(` or `<`
```

### Anything else?

Also happens on nightly according to Rust Playground.

I'd like to try my hand at implementing this diagnostic, but I'll likely need a little bit of locational guidance. A naive code search show that the message is emitted by this code is the parser diagnostics, but I'm not sure if the adjustment would need to be made within that or from where it is invoked in this case.
https://github.com/rust-lang/rust/blob/c5283576ec18937d98889679a54aa8f2dee2b875/compiler/rustc_parse/src/parser/diagnostics.rs#L384-L388

----

_Edit: Updated to use the wording "`Fn*`-family trait bounds" rather than "HRTBs"._

**Comment by compiler-errors** [comment]
> but I'm not sure if the adjustment would need to be made within that or from where it is invoked in this case

Where this function is invoked. Try looking for the code that parses ["parenthesized" generics](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ast/ast/enum.GenericArgs.html#variant.Parenthesized).

**Comment by Fishrock123** [comment]
It seems this diagnostic contextually comes from `parse_fn_params()` which does this token search by `parse_paren_comma_seq()`.

As corroboration it also seems that declaring a regular `fn` without parenthesis causes a similar if more contextually understandable error:
```
error: expected one of `(` or `<`, found `->`
 --> src/lib.rs:3:9
  |
3 | fn main -> () {}
  |         ^^ expected one of `(` or `<`
```

https://github.com/rust-lang/rust/blob/9a7cc6c32f1a690f86827e4724bcda85e506ef35/compiler/rustc_parse/src/parser/item.rs#L2375-L2396

I naively _think_ that the adjustment point should probably be `parse_fn_params()` rather than `parse_paren_comma_seq()`...

However I don't understand how the output gets multiple possibilities e.g. `(` and `<` in this output:
```
3 | fn main -> () {}
  |         ^^ expected one of `(` or `<`
 ```
or the whole list of
```
expected one of `(`, `+`, `,`, `::`, `<`, or `{`
```

Since it's only calling `Parser::expect()` with `Delimiter::Parenthesis` from  `self.parse_delim_comma_seq(Delimiter::Parenthesis, f)`...

I guess this requires catching the result in `parse_fn_params` and handling this result type somehow?
```rust
pub type PErr<'a> = DiagnosticBuilder<'a, ErrorGuaranteed>;
```

**Comment by compiler-errors** [comment]
Any time you call `Parser::check`, it stashes the token type you tried probing for and it'll present that in a list whenever you get to `expected_one_of_not_found`. (Or something like that).

**Comment by compiler-errors** [comment]
Anyways, it shouldn't matter -- in the *caller* to `parse_fn_params` (when parsing `Fn ->`, you could add a check for `->` before that and handle that specifically.

**Comment by estebank** [comment]
Just chiming in to mention: in any parser change you make here *make sure you don't start accepting new code* and add tests for all combinations you can think of.
