### ISSUE TITLE
`x dist --stage 0` does not check out submodules automatically

### ISSUE THREAD

**Issue by KittyBorgX** [rust-lang/rust#108111]
I'm working on : #107956  and got `x dist --stage 0` past all errors and hit into this roadblock. 
`x dist --stage 0` build successfully when I run `git submodule update --init`: 
![image](https://user-images.githubusercontent.com/82328083/219261918-809bec73-52dc-4f6c-a86e-295a24154648.png)

Expected behavior : running `x dist --stage 0` should check out submodules automatically

**Comment by zephaniahong** [comment]
@KittyBorgX Hi! Am I right to say that I have to wait for you PR to merge before I can work on this? Reason being, I am unable to run `x dist --stage 0` without getting an error.

**Comment by KittyBorgX** [comment]
> @KittyBorgX Hi! Am I right to say that I have to wait for you PR to merge before I can work on this? Reason being, I am unable to run `x dist --stage 0` without getting an error.

Yupp. The other errors in `x dist --stage 0` should be fixed in my PR. The PR is ready, I believe. It's awaiting a rollup/merge now.
