### ISSUE TITLE
Miscompilation of libcore with -Zmir-opt-level=3

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#108166]
Compile the standard library with -Zmir-opt-level=3 and then running libcore's test suite with this version of the standard library results in several tests failing. I am seeing this on cg_clif's CI (https://github.com/bjorn3/rustc_codegen_cranelift/actions/runs/4203400456/jobs/7292743420) but I expect it to be reproducible using LLVM too.

### Meta

Last known good version: `rustc 1.69.0-nightly (065852def 2023-02-13)`

First known bad version:

```
rustc 1.69.0-nightly (9a7cc6c32 2023-02-16)
binary: rustc
commit-hash: 9a7cc6c32f1a690f86827e4724bcda85e506ef35
commit-date: 2023-02-16
host: aarch64-unknown-linux-gnu
release: 1.69.0-nightly
LLVM version: 15.0.7

```

Regression range: https://github.com/rust-lang/rust/compare/065852def...9a7cc6c32

https://github.com/rust-lang/rust/pull/107449 stands out as a changed MIR opt.

**Comment by saethlin** [comment]
Try adding `-Zmir-enable-passes=-DataflowConstProp` to your `RUSTFLAGS`. That makes the miscompiles go away for me and suggests that https://github.com/rust-lang/rust/pull/107411 is the cause.

**Comment by bjorn3** [comment]
I can confirm the miscompilation is now fixed.
