### ISSUE TITLE
rustdoc: regression: `macro_export` in `doc(hidden)` mod disappears

### ISSUE THREAD

**Issue by Nugine** [rust-lang/rust#108231]
### Code

I tried this code:

```rust
#[doc(hidden)]
pub mod __internal {
    /// Foooooo
    #[macro_export]
    macro_rules! foo {
        () => {};
    }
}
```

I expected to see this happen:
![expected.png](https://user-images.githubusercontent.com/30099658/219937118-5961ab38-6c3b-4359-af2d-fa85c9bdadf1.png)

Instead, this happened:
![happened.png](https://user-images.githubusercontent.com/30099658/219937136-97f2a263-62c3-46b7-9d25-35df36baeb85.png)

### Version it worked on

It most recently worked on: Rust 1.67.1, Rust nightly-2023-02-03

```
rustc 1.69.0-nightly (f3126500f 2023-02-02)
binary: rustc
commit-hash: f3126500f25114ba4e0ac3e76694dd45a22de56d
commit-date: 2023-02-02
host: x86_64-unknown-linux-gnu
release: 1.69.0-nightly
LLVM version: 15.0.7
```

### Version with regression

Rust nightly-2023-02-04

`rustc --version --verbose`:

```
rustc 1.69.0-nightly (658fad6c5 2023-02-03)
binary: rustc
commit-hash: 658fad6c5506f41c35b64fb1a22ceb0992697ff3
commit-date: 2023-02-03
host: x86_64-unknown-linux-gnu
release: 1.69.0-nightly
LLVM version: 15.0.7
```

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

**Comment by fmease** [comment]
Very likely regressed in #108057 (CC @GuillaumeGomez).

@rustbot label T-rustdoc

**Comment by GuillaumeGomez** [comment]
So macros should be excluded from the inheritance as well. Sending a fix.
