### ISSUE TITLE
Inherent associated functions and constants defined on function pointer types won't be found

### ISSUE THREAD

**Issue by fmease** [rust-lang/rust#108270]
Since only `core` & `std` are allowed to define functions and constants on function pointer types (like `fn()` or `for<'a> fn(&'a ()) -> bool`) and since they maybe never will, this issue is of low priority. For other primitive types like `!`, `()`, `bool` etc., inherent associated functions and constants are correctly resolved.

```rust
#![feature(rustc_attrs)]
#![rustc_coherence_is_core]

impl fn() {
    const X: () = ();
}

fn user() {
    <fn()>::X; //~ ERROR no associated item named `X` found for fn pointer `fn()` in the current scope
}
```

Note that the perma-unstable attribute `#![rustc_coherence_is_core]` is used in the reproducer which doesn't come with any language or stability guarantees. However, this issue is not about it but about the fact that `core` which uses this attribute internally and `std` (which can use `#[rustc_allow_incoherent_impl]`) would not be able to properly define associated items on those types. For the same reason, I'm not labeling this as <kbd>requires-nightly</kbd>. 

@rustbot label T-compiler A-resolve A-associated-items

**Comment by compiler-errors** [comment]
@fmease this just requires to assemble candidates for incoherent impls as well, just like method candidate assembly does?

**Comment by fmease** [comment]
@compiler-errors Note that this not about inherent associated *types* but functions & constants. So we need to modify method candidate assembly itself.

I think we just need to add `| ty::FnPtr(..)` here in `assemble_probe` haha:

https://github.com/rust-lang/rust/blob/f9216b75646cde0c4c69ae00232778a47fc893d3/compiler/rustc_hir_typeck/src/method/probe.rs#L696

I'm gonna do that later once I have access to my machine.
@rustbot claim

**Comment by compiler-errors** [comment]
@fmease oh lol, i just saw your name and thought inherent associated types. cool, good luck

**Comment by fmease** [comment]
The IAT counterpart is #106719 fyi ^^

**Comment by fmease** [comment]
See https://rust-lang.zulipchat.com/#narrow/stream/326132-t-types.2Fmeetings/topic/2023-08-07.20planning.20meeting/near/382646902
