### ISSUE TITLE
`x.py test` ignores `--no-fail-fast` in some tool testsuites.

### ISSUE THREAD

**Issue by jchecahi** [rust-lang/rust#108261]
It looks like some tool testsuites (like `clippy`'s or `rustfmt`'s) will ignore the no fail fast option. For example running `./x.py test --no-fail-fast clippy` will stop after compile-test fails, something common in big endian platforms.

If I understand correctly this seems to be because bootstrap is not passing `--no-fail-fast` to `cargo test` in every tool implementation. Currently, the flag is passed in the `Step` trait implementation of some tools (i.e. [cargo](https://github.com/rust-lang/rust/blob/824f915cbc32c0942122389274a1b6fbe2ffc51e/src/bootstrap/test.rs#L323)), right after calling `tool::prepare_tool_cargo()`. But others like mentioned clippy or rustfmt are missing it.

**Comment by jyn514** [comment]
cc https://github.com/rust-lang/rust/issues/104198
