### ISSUE TITLE
Failed to Run `rustc` to Learn About Target-Specific Information

### ISSUE THREAD

**Issue by inyourface34456** [rust-lang/rust#108343]
I was experimenting to try and see the smallest I can make rust compiled binaries, and came across the `-Zbuild-std` unstable option.  I found out how to use it and this error came up:
```
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 1)
  --- stderr
  error: unknown print request `split-debuginfo`
```

I have tried using no unstable features, and the same error appeared.  I even tried to use the default settings rather then my custom config but that did not work.

Running `rustc -vV`:
```
rustc 1.64.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.64.0
LLVM version: 14.0.6
```

`Cargo.toml`:
```toml
[package]
name = "my-project"
version = "0.1.0"
authors = ["runner"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
opt-level = "z"    
lto = true         
codegen-units = 1  
panic = "abort"     
strip = true
```

I also forgot to mention that I am doing this on [replit.com](replit.com).

**Comment by clubby789** [comment]
This option was added in 4c3cad062014253452a15574868e49328486ec02, which looks like it'll be available from version 1.67.0 onwards

**Comment by SkiFire13** [comment]
Are you sure you're not using the `rustc` from your distribution package manager?

**Comment by inyourface34456** [comment]
I did not know there is a difference.  If there is, I do not know where it is, and how to run it.  FYI, replit uses the NIXos, if you know anything about it.

**Comment by clubby789** [comment]
Uninstalling rust from your system package manager should allow you to use the rustup-provided (and up to date) version

**Comment by jyn514** [comment]
Somehow you have ended up with a mismatch between cargo's version and rust's version. I am not sure how it happened, but it's not a bug in rust itself.

The issue tracker is not a support forum. For future questions please ask in one of these places:

https://discord.gg/rust-lang/
https://discord.gg/rust-lang-community/
https://users.rust-lang.org/
https://rust-lang.zulipchat.com/

**Comment by andrewpedia** [comment]
for my case,brew uninstall rust

**Comment by Jeklah** [comment]
apt remove rustc 

fixed it for me.
