### ISSUE TITLE
Wildcard pattern not optimized in match expression

### ISSUE THREAD

**Issue by mitiko** [rust-lang/rust#108395]
The following snippet generates branches (with `-C opt-level=3`)

```rust
pub fn func1(a: u16, b: u16, v: u16) -> u16 {
    match (a == v, b == v) {
        (true, false) => 0,
        (false, true) => u16::MAX,
        _ => 1 << 15, // half
    }
}
```

whereas spelling it out to the compiler does not:

```rust
pub fn func2(a: u16, b: u16, v: u16) -> u16 {
    match (a == v, b == v) {
        (true, false) => 0,
        (false, true) => u16::MAX,
        (true, true) => 1 << 15, // half
        (false, false) => 1 << 15, // half
    }
}
```

I believe this breaks the zero cost abstraction promise.
In theory these do mean different things but for constant 16-bit integers on a modern 64-bit system they should be optimized away.

Other quirks:
- only partially spelling it out to the compiler with `(true, true) | (false, false)` still generates branches
- using guard clauses generates branchless code but with more instructions

Godbolt link: https://rust.godbolt.org/z/cWoboKM3d

**Comment by veera-sivarajan** [comment]
Looks like this is fixed now: https://rust.godbolt.org/z/G93zG8jdb
