### ISSUE TITLE
Strange \n in output of assert

### ISSUE THREAD

**Issue by safinaskar** [rust-lang/rust#108341]
I tried this code:

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=101cc1b94e74b6bcdec96994d034dbab

I see strange `\n` in the output. I don't like the output

```text
Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 0.79s
     Running `target/debug/playground`
thread 'main' panicked at 'assertion failed: 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0\n                                + 0 + 0 + 0 + 0 + 0 + 0 + 0 == 1', src/main.rs:2:5
note: [run with `RUST_BACKTRACE=1` environment variable to display a backtrace](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=101cc1b94e74b6bcdec96994d034dbab#)
```

`1.69.0-nightly (2023-02-22 fdbc4329cb781c7768ff)`

**Comment by nnethercote** [comment]
This happens because the compiler pretty-prints the expression when putting it into the assertion failure message, and it inserts a newline in there because the line is so long. Which is reasonable. But printing that newline as `\n` rather than an actual newline is a bit weird, IMO. I have filed #116548 to change this newline behaviour.

There is still an overly-large indent after the newline, which is a separate pretty-printing issue, and one I haven't addressed.

**Comment by nnethercote** [comment]
#116548 has now been merged. Here's another example:
```rust
fn very_long_function_name(x: u32) -> u32 { x }

fn main() {
    assert!(
        {
            let x = 1;
            let y = 2;
            very_long_function_name(x) + very_long_function_name(y) 
        } == 
        {
            let x = 0;
            let y = 1;
            very_long_function_name(x) + very_long_function_name(y)
        }
    );
}
```
Previously it would produce a single line of output on failure:
```text
assertion failed: {\n        let x = 1;\n        let y = 2;\n        very_long_function_name(x) + very_long_function_name(y)\n    } ==\n    {\n        let x = 0;\n        let y = 1;\n        very_long_function_name(x) + very_long_function_name(y)\n    }
```
Now it produces something much better:
```text
thread 'main' panicked at s3.rs:4:5:
assertion failed: {
        let x = 1;
        let y = 2;
        very_long_function_name(x) + very_long_function_name(y)
    } ==
    {
        let x = 0;
        let y = 1;
        very_long_function_name(x) + very_long_function_name(y)
    }
```

@safinaskar: The original example still has the weird over-indent, which is a separate pretty-printing imperfection, but the `\n` chars are gone. Are you happy to close this issue now?

**Comment by safinaskar** [comment]
Yes, I'm closing
