### ISSUE TITLE
Unsound mir-opt level 4 with loops and `.try_into().unwrap_or()`

### ISSUE THREAD

**Issue by lukas-code** [rust-lang/rust#108360]
I tried this code:

```rust
fn main() {
    for x in 0..1 {
        let mut value = 0u8;
        value = x.try_into().unwrap_or(42);
        assert_eq!(value, 0);
    }
}
```

run with

```
RUSTFLAGS=-Zmir-opt-level=4 cargo run
```

I expected to see this happen: doesn't panic

Instead, this happened:
```text
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `42`,
 right: `0`', src/main.rs:5:9
```

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0-nightly (246eae2fa 2023-02-21)
binary: rustc
commit-hash: 246eae2fab54a5139365c4e1a08c5724fb385fbf
commit-date: 2023-02-21
host: x86_64-unknown-linux-gnu
release: 1.69.0-nightly
LLVM version: 15.0.7
```

### Bisect

searched nightlies: from nightly-2023-02-16 to nightly-2023-02-22
regressed nightly: nightly-2023-02-17
searched commit range: https://github.com/rust-lang/rust/compare/2d14db321b043ffc579a7461464c88d7e3f54f83...9a7cc6c32f1a690f86827e4724bcda85e506ef35
regressed commit: https://github.com/rust-lang/rust/commit/639377ed737b25830ec44dc6acf93467c980316a -> https://github.com/rust-lang/rust/pull/107449

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.5</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --script=script.sh 
```

script.sh:
```bash
#!/bin/sh
RUSTFLAGS=-Zmir-opt-level=4 cargo run
```
</details>

@rustbot label A-mir-opt requires-nightly

**Comment by lukas-code** [comment]
another:

```rust
fn bar(x: usize) {
    assert_eq!(x, 42);
}

#[inline(always)]
fn saturating_mul(lhs: usize, rhs: usize) -> usize {
    match lhs.checked_mul(rhs) {
        Some(x) => x,
        None => usize::MAX,
    }
}

fn main() {
    bar(saturating_mul(1, 42));
}
```

```text
RUSTFLAGS='-Zmir-opt-level=3' cargo run
```

```text
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `18446744073709551615`,
 right: `42`', src/main.rs:2:5
```

**Comment by cjgillot** [comment]
Does https://github.com/rust-lang/rust/pull/108208 fix those?

**Comment by lukas-code** [comment]
Yes, looks like https://github.com/rust-lang/rust/pull/108208 fixes both of these. Feel free to close this issue or use them as test cases.
