### ISSUE TITLE
The Output should not be an association type of the FnOnce

### ISSUE THREAD

**Issue by 823984418** [rust-lang/rust#108490]
Currently, we require that the lifecycle that appears in an association type appear in a generic type.
This is to fix https://github.com/rust-lang/rust/issues/32330 .
But this because the `Output` is an associative type of the function.

------

```
trait F {
    type Output;
}
```
Except for functions, no same type can implement different lifecycle `Output`.
So the `Output` as an association type is just an error.

See https://github.com/rust-lang/rust/issues/33685#issuecomment-1445349734

**Comment by workingjubilee** [comment]
...But what exactly would we gain by making this change?

**Comment by 823984418** [comment]
> ...But what exactly would we gain by making this change?

Make it a legal statement:
```
fn a<F: for<'s> Fn() -> Vec<&'s i32>>(f: F) 
```
And don't need to be like this:
```
fn a<F: for<'s> Fn(PhantomData<&'s ()>) -> Vec<&'s i32>>(f: F)
```

**Comment by 823984418** [comment]
See https://internals.rust-lang.org/t/reopen-fnonce-why-is-output-an-associated-type/18430?u=qsh

**Comment by fmease** [comment]
The invalid bound `for<'s> Fn() -> Vec<&'s i32>` can just be expressed as `Fn() -> Vec<&'static i32>` or am I missing something? A closure that returns a vector of references that live at least as long as *any* possible lifetime that the caller can choose can only return `'static` references since without any function arguments that are of that lifetime, any other lifetime that the callee selects would simply be incorrect in general.

**Comment by 823984418** [comment]
> The invalid bound `for<'s> Fn() -> Vec<&'s i32>` can just be expressed as `Fn() -> Vec<&'static i32>` or am I missing something?

I have to admit that I am a bad example, I mean, `'s` is invariant for return type.

**Comment by 823984418** [comment]
> any other lifetime that the callee would select, would simply be incorrect in general.

I can say clear, this is wrong, the life cycle of designated by the caller is exist and reasonable.

One example is: `RR::default`
```
#[derive(Default)]
struct RR<'a, 'b> {
    r: Option<&'a mut &'b i32>,
}
```
Although it doesn't seem to make much sense, what about self-referencing life cycle?
```
#[derive(Default)]
struct RR<'a> {
    r: Option<&'a RR<'a>>,
}
```

**Comment by jyn514** [comment]
This appears to be a breaking change: https://internals.rust-lang.org/t/reopen-fnonce-why-is-output-an-associated-type/18430/8?u=jyn514

Given that, it doesn't seem strongly enough motivated to be worth changing.
