### ISSUE TITLE
Rustdoc search should allow ` ` as a separator in addition to `::`

### ISSUE THREAD

**Issue by thomcc** [rust-lang/rust#108447]
If I search `vec push` in the stdlib docs, it brings me to [this page](https://doc.rust-lang.org/std/?search=vec%20push) which currently has no results. This is unfortunate, and I hit it probably at least once a day, and may not be alone.

Searching instead for [`vec::push`](https://doc.rust-lang.org/nightly/std/?search=vec%3A%3Apush) works, but it would be nice if it were not necessary, and the delimiter could be ` ` as well.

**Comment by GuillaumeGomez** [comment]
Sounds acceptable. It'll need to go through FCP I think but otherwise I think it makes sense.
