### ISSUE TITLE
suggestion on to_some() method for rust scalar types

### ISSUE THREAD

**Issue by borngraced** [rust-lang/rust#108479]
I thought it'd be a lot nicer to have `method` that'll be able to convert `rust scalar types` to `Optional` e.g

```rust
let count = 156u32;
let some_count = count.to_some();
// some_count should be Some(count)

let foo = String::from("foo");
let some_foo = foo.to_some();
// some_foo should be Some(foo)
```
I think this brings some conveniency

**Comment by workingjubilee** [comment]
The implementation of `From<T> for Option<T>` allows you to write code like
```rust
fn unwraps_or_defaults(s: Option<String>) -> String {
    match s {
        Some(s) => s,
        None => "".into(),
    }
}

fn call() -> String {
   let foo = String::from("foo");
   let foo_or_empty = unwraps_or_defaults(foo.into());
   foo_or_empty
}
```

This is driven by type inference.

**Comment by borngraced** [comment]
> The implementation of `From<T> for Option<T>` allows you to write code like
> 
> ```rust
> fn unwraps_or_defaults(s: Option<String>) -> String {
>     match s {
>         Some(s) => s,
>         None => "".into(),
>     }
> }
> 
> fn call() -> String {
>    let foo = String::from("foo");
>    let foo_or_empty = unwraps_or_defaults(foo.into());
>    foo_or_empty
> }
> ```
> 
> This is driven by type inference.

I see thanks, but still, something very explicit enough like `.to_some()` won't be bad! 😃

**Comment by Dylan-DPC** [comment]
Closing this as there are other alternatives where this can be done easily, so there is less motivation of having this.
