### ISSUE TITLE
Want to know how box pointers work

### ISSUE THREAD

**Issue by SajeevanJSPY** [rust-lang/rust#108420]
![pointer_eq](https://user-images.githubusercontent.com/108508613/221105701-3c9e448e-e8ad-4ec0-9b2f-29168be59482.png)
I have the code here. It works well, I want to know why. because variables p1 and p2 point to the different two box pointers, Why variables **p1** and **p2** are pointing to the same pointer??

**Comment by scottmcm** [comment]
If you have questions about what your program is doing, I suggest asking in a user forum such as https://users.rust-lang.org/ or https://discord.gg/rust-lang-community -- the bug tracker isn't the place.
