### ISSUE TITLE
rustc looking for "Windows resource compiler" at wrong location

### ISSUE THREAD

**Issue by liam-clink** [rust-lang/rust#108506]
I tried building lapce-ui with the MSVC toolchain

I expected to see this happen: build success

Instead, this happened: It appears that cargo/rustc is attempting to call the Windows resource compiler from a different location than it actually is, and rc.exe is in fact on the path. Why is rustc not using the rc.exe that is on PATH?

```
(exit code: 101)
  --- stdout
  package.metadata does not exist
  Selected RC path: 'bin\x64\rc.exe'

  --- stderr
  thread 'main' panicked at 'Failed to run the Windows resource compiler (rc.exe): Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }'
```

The actual location, which is on PATH, is C:\msvc\Windows Kits\10\bin\10.0.20348.0\x64

### Meta

`rustc --version --verbose`:
```
rustc 1.67.1 (d5a82bbd2 2023-02-07)
binary: rustc
commit-hash: d5a82bbd26e1ad8b7401f6a718a9c57c96905483
commit-date: 2023-02-07
host: x86_64-pc-windows-msvc
release: 1.67.1
LLVM version: 15.0.6
```

I don't expect the backtrace to be helpful, as it's just a panic at being unable to find a binary.
<details><summary>Backtrace</summary>
<p>

```
stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:575
     1: core::panicking::panic_fmt
               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\panicking.rs:64
     2: core::result::unwrap_failed
               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\result.rs:1791
     3: core::result::Result<T,E>::expect
     4: __ImageBase
     5: core::ops::function::FnOnce::call_once
```

</p>
</details>

**Comment by PatchMixolydic** [comment]
This seems to be an issue with [`lapce-ui`'s build script](https://github.com/lapce/lapce/blob/b92c519e297826c598360ec1567e757755aa311d/lapce-ui/build.rs). As far as I know, rustc doesn't invoke rc.exe on its own.

**Comment by ChrisDenton** [comment]
Yes, rc is not found by rust itself. It's found by the `winres` crate which is used by lapce-ui's build script.

**Comment by liam-clink** [comment]
@ChrisDenton How does the script determine where to look? Did you already fix this or should I work on a fix myself?
