### ISSUE TITLE
An error "linking with `link.exe` failed: exit code: 1104" 

### ISSUE THREAD

**Issue by MuXingchui** [rust-lang/rust#108525]
I got an error: "linking with `link.exe` failed: exit code: 1104", when I compile the program with `VSCode`.
My program is Python, and I used `OpEn` to solve the NLP. The `OpEn-Optimization` builds on 'Rust'. So when I build the optimization solver, I got the error:
```bashE
error: linking with `link.exe` failed: exit code: 1104

note: Non-UTF-8 output: LINK : fatal error LNK1104: cannot open file “D:\***\mpc-trajectory-generator-master\mpc_build\mpc_navigation\tcp_iface_mpc_navigation\target\release\build\num-traits-abea29fdb848ac61\build_script_build-abea29fdb848ac61.exe”
```

Besides, my environment:
```bash
Python: 3.7.16
OpenGen: 0.6.4
Rustc: 1.67.1 (d5a82bbd2 2023-02-07)
cargo: 1.67.1 (8ecd4f20a 2023-01-10)
```
I don't know what's wrong, please help me

**Comment by ChrisDenton** [comment]
[LNK1104](https://learn.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1104?view=msvc-170) means a file cannot be read or written to. I don't know enough about OpenGen to say why that is. I think you'll need to ask OpenGen.

**Comment by MuXingchui** [comment]
> [LNK1104](https://learn.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1104?view=msvc-170) means a file cannot be read or written to. I don't know enough about OpenGen to say why that is. I think you'll need to ask OpenGen.

Thank you for your suggestion

**Comment by T-O-R-U-S** [comment]
For anyone viewing this in the future, it might be your antivirus.

**Comment by dorklord23** [comment]
> For anyone viewing this in the future, it might be your antivirus.

Indeed it is. I use Avast and only after I disabled all the real time shields I manage to compile using Tauri.

**Comment by ChrisDenton** [comment]
Thanks for the reports. It sounds like this is entirely outside of Rust's control so there's nothing to track in this issue. Unless anyone has any ideas.

**Comment by ChrisDenton** [comment]
Closing this as per above. But feel free to continue discussing this if anyone has anything to add.

**Comment by Jasonsey** [comment]
try this [solution](https://stackoverflow.com/a/50337100), it works for me

**Comment by Young-Lord** [comment]
Try `cargo clean` and see if any error showed. For me, it was because the task is still running when `cargo build` was executed. Restart VSCode works for me.
