### ISSUE TITLE
When was support for 32-bit Apple targets downgraded?

### ISSUE THREAD

**Issue by 8573** [rust-lang/rust#108556]
### Location

* https://github.com/rust-lang/rust/blob/b583ede652936887a85c54bb793251479c82d3ee/RELEASES.md
* https://blog.rust-lang.org/2020/01/03/reducing-support-for-32-bit-apple-targets.html

### Summary

The Rust [release notes](https://github.com/rust-lang/rust/blob/b583ede652936887a85c54bb793251479c82d3ee/RELEASES.md), [under the section for Rust 1.41.0](https://github.com/rust-lang/rust/blob/b583ede652936887a85c54bb793251479c82d3ee/RELEASES.md#compatibility-notes-26), say
>  1.41.0 will be the last tier 1 release for 32-bit Apple targets.

The Rust blog post ["Reducing support for 32-bit Apple targets"](https://blog.rust-lang.org/2020/01/03/reducing-support-for-32-bit-apple-targets.html) (added in https://github.com/rust-lang/blog.rust-lang.org/pull/487) said
> Rust 1.41.0 (to be released on January 30th, 2020) will be the last release with the current level of support for 32-bit Apple targets. Starting from Rust 1.42.0, those targets will be demoted to Tier 3.

It seems unlikely that (1.41.0 was the last version with these targets undemoted AND 1.42.0 was the first version with them demoted), because there was a release between them: 1.41.1.  The release notes for 1.41.1 and 1.42.0 do not mention these targets.  I would guess the targets were demoted in 1.42.0 and still supported as before in 1.41.1, making 1.41.0 not actually the last release with them undemoted.

I would like to suggest that a clarifying note be added in the release notes, the blog post, or both, noting whether 1.41.1 also supports those targets undemoted.

**Comment by workingjubilee** [comment]
Thank you for raising this question! The release notes for 1.41.0 and 1.41.0 will be amended shortly to make this clearer. I will leave the blog post as-is, as usually those are not amended significantly (it is a "product of its time").

I do not recommend using rustc 1.41.1 however if you are capable of using the latest nightlies in combination with `cargo build -Zbuild-std` on these platforms.
