### ISSUE TITLE
impl Trait lifetimes regression 1.67

### ISSUE THREAD

**Issue by aliemjay** [rust-lang/rust#108591]
Some regressions of #103491 that I previously reported in https://github.com/rust-lang/rust/issues/105826#issuecomment-1356364617, but they were missed:

```rust
struct MyTy<'a>(Vec<u8>, &'a ());

impl MyTy<'_> {
    fn one(&mut self) -> &mut impl Sized {
        &mut self.0
    }
    fn two(&mut self) -> &mut (impl Sized + 'static) {
        self.one()
        //~^ ERROR lifetime may not live long enough
    }
}
```

```rust
#![feature(type_alias_impl_trait)]
type Opaque<'a> = impl Sized;
fn define<'a>() -> Opaque<'a> {}

fn test<'a>() {
    None::<&'static Opaque<'a>>;
    //~^ ERROR lifetime may not live long enough
}
```

```rust
fn one<'a, 'b: 'b>() -> &'a impl Sized {
    &()
}
fn two<'a, 'b>() {
    one::<'a, 'b>();
    //~^ ERROR lifetime may not live long enough
}
```

I guess the way to fix this is to ignore non-captured lifetimes of opaque types here https://github.com/rust-lang/rust/blob/ca1bc7f1f6487991dd6b504d1fddbc982e6b779c/compiler/rustc_infer/src/infer/outlives/obligations.rs#L417

cc @cjgillot 

@rustbot label C-bug regression-from-stable-to-stable T-types T-compiler A-impl-trait

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23108591.20impl.20Trait.20lifetimes.20regression.201.2E67)).

@rustbot label -I-prioritize +P-high
