### ISSUE TITLE
Rust v1.61+ produces larger code on Risc-V

### ISSUE THREAD

**Issue by almindor** [rust-lang/rust#108543]
### Code

I tried to build [this code](https://github.com/riscv-rust/longan-nano/blob/328be12f4201536717a52e2e8b3fd17dc7f1959f/examples/sdcard_test.rs) with `cargo build --features sdcard --example sdcard_test --release`

NOTE: everything is for the target `riscv32imac-unknown-none-elf`

I expected to see this happen: a valid executable to be produced

Instead, this happened: link error due to insufficient flash memory

### Version it worked on

It most recently worked on: 1.60

### Version with regression

`rustc --version --verbose`:
```
rustc 1.61.0 (fe5b13d68 2022-05-18)
binary: rustc
commit-hash: fe5b13d681f25ee6474be29d748c65adcd91f69e
commit-date: 2022-05-18
host: x86_64-unknown-linux-gnu
release: 1.61.0
LLVM version: 14.0.0
```

#### Additional information
Changing the flash definition to have more memory available and comparing the resulting binaries we see these differences between artefacts produced by rust 1.60 and 1.61:

```
$ size sdcard_test_1.60_memory-cb
   text    data     bss     dec     hex filename
  64928       8   32760   97696   17da0 sdcard_test_1.60_memory-cb
$ size sdcard_test_1.61_memory-cb
   text    data     bss     dec     hex filename
  66780       8   32760   99548   184dc sdcard_test_1.61_memory-cb
```

Doing objdump for the `.test` section shows roughly 1k extra lines but nothing obviously sticking out. Using `cargo bloat` produces an interesting diff that seems to indicate almost every piece of generated code got inflated in rust v1.61 compared to v1.60

![cargo_bloat_diff](https://user-images.githubusercontent.com/1950958/221711926-30a800bc-7413-448d-8d75-5aacb88bc87a.png)

**Comment by workingjubilee** [comment]
Hmm.
Very happy to have a nice, precise start for bisecting, but just to check: 
Have you tried with rustc 1.67.1 or rustc nightly?

**Comment by almindor** [comment]
> Hmm. Very happy to have a nice, precise start for bisecting, but just to check: Have you tried with rustc 1.67.1 or rustc nightly?
> 
> ...and have you tried using `--release`?

Sorry, I mispasted the build command, we've been using `--release`. The rust versions are 1.60 (where it worked) and 1.61 (where it became sizeably bigger). I also tested 1.66 which had a similar size output as 1.61 so it seems the regression is still around.

**Comment by workingjubilee** [comment]
Cool! That clarifies things a lot. It's not unreasonable to want to be able to put a debug binary on your flash, but also it's definitely going to be less reliable in terms of codegen size...

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23108543.20Rust.20v1.2E61.2B.20produces.20larger.20code.20on.20Risc-V)).

@rustbot label -I-prioritize +P-low

**Comment by istankovic** [comment]
I think this has improved by a lot in the meantime:
```
   text    data     bss     dec     hex filename                                                        
  60252       8   20472   80732   13b5c target/riscv32imac-unknown-none-elf/release/examples/sdcard_test
```
This is with
```
rustc 1.75.0-nightly (a2f5f9691 2023-11-02)          
binary: rustc                                        
commit-hash: a2f5f9691b6ce64c1703feaf9363710dfd7a56cf
commit-date: 2023-11-02                              
host: x86_64-unknown-linux-gnu                       
release: 1.75.0-nightly                              
LLVM version: 17.0.4                                 
```
so I think we can close this one.

**Comment by almindor** [comment]
Thanks for checking back on this. Indeed it seems to have been improved!
