### ISSUE TITLE
Tracking Issue for `option_as_slice`

### ISSUE THREAD

**Issue by llogiq** [rust-lang/rust#108545]
Feature gate: `#![feature(option_as_slice)]`

This is a tracking issue for the `Option::as_slice` and `Option::as_mut_slice` methods.

The functions return an immutable or mutable slice to the value contained in the Option, if any. Otherwise an empty slice is returned.

### Public API

```rust
// core::option

impl Option {
    pub fn as_slice(&self) -> &[T] { .. }

    pub fn as_mut_slice(&mut self) -> &mut [T] { .. }
}
```

### Steps / History

- [x] Implementation: 
  - #105871
  - #108623
  - #109095
  - #109179
- [x] Final comment period (FCP)[^1]
- [x] Stabilization PR #116220

### Unresolved Questions

~~The current implementation contains an optimization which relies on the fact that layout randomization as currently implemented only applies to individual variants, never to the discriminant, and thus the offset of the `value` within `Some(value)`  is always either 0 (because of niche optimization) or would be the same if the type was `Option<MaybeUninit<T>>` instead of `Option<T>`.~~

~~Before stabilization, the implementation should be changed to either use an intrinsic to get the offset or extend the `offset_of!` macro (recently merged [RFC#3308](https://rust-lang.github.io/rfcs/3308-offset_of.html)) to cover enum variants and use that. There might also be a smaller solution (that we'd still need to check re the rules of Rust layout), which would simply be `mem::size_of::<Option<T>>() - mem::size_of::<T>()`. I can see that this works for all types I've tested it with, and indeed I'm quite sure that it will work perfectly with the current layout implementation, but I'd like someone from the types team have a look at it before actually using it in a stable API.~~

The implementation now uses an approach that's always sound (just less efficient than optimal if the hack guesses wrong).  A stabilization conversation would probably still want to discuss whether we're comfortable with shipping that approach as stable (since the implementation could be improved non-breakingly later) or we'd prefer to wait for a more principled approach (such as an extension of `offset_of!` from https://github.com/rust-lang/rfcs/pull/3308 that allows enum variants) first.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by scottmcm** [comment]
Updated the discussion in the OP now that the implementation relies on the layout estimate only for performance, not for soundness.

**Comment by llogiq** [comment]
I'll push another version using an intrinsic shortly, so we'll have performance *and* soundness.

**Comment by llogiq** [comment]
Superceded by #109179 with a more direct approach using an intrinsic instead of a hacky estimate.

**Comment by BurntSushi** [comment]
@rfcbot merge

**Comment by AnthonyMikh** [comment]
Is it a hard requirement for an empty slice to point to the same place as if `Option` was `Some`? Because the pointer part of slice just need to be non-null and sufficiently aligned, so using the address of an `Option` itself (as well as `NonNull::dangling().as_ptr()`) is always the sound approach.

**Comment by scottmcm** [comment]
> Is it a hard requirement for an empty slice to point to the same place as if `Option` was `Some`?

Well, the API doesn't *guarantee* it in the docs, so I don't think it's a *hard* requirement.

It's an important QoI detail for performance, though.  By returning the empty slice pointing at where the item *would* be, it's always returning the same pointer.  That simplifies codegen and optimizations, by not needing the extra conditional instruction.

Compare these: <https://rust.godbolt.org/z/reqcM84xz>

**Comment by llogiq** [comment]
As there were no concerns brought up so far, I'll likely push a stabilization PR later today.

**Comment by ChayimFriedman2** [comment]
This should be closed as the feature was stabilized.
