### ISSUE TITLE
`#[target_feature]` is allowed on `main`

### ISSUE THREAD

**Issue by LeSeulArtichaut** [rust-lang/rust#108645]
```rust
#[target_feature(enable = "avx2")] // no error
fn main() {}
```

This is a consequence of `#[target_feature]` being allowed on safe functions with `#![feature(target_feature_11)]`.

cc https://github.com/rust-lang/rust/issues/69098
@rustbot label T-lang T-compiler C-bug I-unsound F-target_feature_11

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23108645.20.60.23.5Btarget_feature.5D.60.20is.20allowed.20on.20.60main.60)).

@rustbot label -I-prioritize +P-critical

**Comment by joshtriplett** [comment]
Dropping P-critical because this is no longer on a train to stable, since we reverted stabilization of target_feature_11. This should be considered a blocker for stabilizing target_feature_11.
