### ISSUE TITLE
Double reexport of non-public item is not listed as reexport

### ISSUE THREAD

**Issue by Kyuuhachi** [rust-lang/rust#108679]
```rust
pub mod a {
    mod b {
        pub struct B;
    }
    pub use b::B;
    pub struct A;
}

pub use a::{A, B};
```

When running `cargo doc` with the above code, the docs list the following items:

<details><summary>Docs</summary>

### Re-exports
`pub use a::A;`

### Modules
`a`

### Structs
`B`

### Structs
`A`\
`B`
</details>

I would expect `a::B` to be listed as a reexport, not a struct. The way it is now, it looks like `foo::B` and `foo::a::B` are different types, which is not the case.

If `a::b` is made `pub`, everything looks as it's supposed to.

@rustbot label +T-rustdoc

**Comment by GuillaumeGomez** [comment]
It's the intended behaviour. Since the `b` module is private, `pub use b::B` is inlining the item into `a`.

**Comment by Kyuuhachi** [comment]
Yes, but `crate::a::B` is public, so should it really be inlined a second time?

**Comment by GuillaumeGomez** [comment]
Ok sorry I misunderstood what you meant. No, it shouldn't be inlined a second time.
