### ISSUE TITLE
Re: linux split-dwarf fails with -Clinker-plugin-lto

### ISSUE THREAD

**Issue by cavivie** [rust-lang/rust#108696]
I have reviewed the relevant bugs of rust, and I have [a similar problem](https://github.com/rust-lang/rust/issues/103932) before that. Although it has been fixed, it still doesn't work for me. I don't know what happened. Only when I comment out `split-debuginfo` or set `lto` to false can I compile it successfully.

I tried many configs, there are three samples:

```toml
[profile.release]
opt-level = "z"
lto = true
debug = false
split-debuginfo = "unpacked"
```

```toml
[profile.release]
opt-level = "z"
lto = true
debug = true
split-debuginfo = "unpacked"
```

```toml
[profile.release]
opt-level = 2
lto = true
debug = true
split-debuginfo = "unpacked"
```
### Meta

`rustc --version --verbose`:
```
rustc 1.66.0 (69f9c33d7 2022-12-12)
binary: rustc
commit-hash: 69f9c33d71c871fc16ac445211281c6e7a340943
commit-date: 2022-12-12
host: x86_64-unknown-linux-gnu
release: 1.66.0
LLVM version: 15.0.2
```

`uname -a`:
```
Linux 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
```

`cat /etc/os-release`:
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

<details><summary>Backtrace</summary>
<p>

```
cargo build --release --target x86_64-unknown-linux-gnu

error: failed to build archive: No such file or directory

error: could not compile `cfg-if` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `pin-utils` due to previous error
error: could not compile `bitflags` due to previous error
error: could not compile `pin-project-lite` due to previous error
...
error: could not compile `libc` due to previous error
error: Recipe `build` failed on line 16 with exit code 101
```

</p>
</details>

**Comment by cavivie** [comment]
![image](https://user-images.githubusercontent.com/103884097/222701168-22c7893d-a58f-4cd0-a750-49f46fa0794b.png)

**Comment by ehuss** [comment]
I believe this has already been fixed in the latest version (1.67), can you try a newer release?

**Comment by workingjubilee** [comment]
Minimized example has no repro with latest stable. Probably is, in fact, already fixed, unless there's a more complex version that is not.

**Comment by cavivie** [comment]
Thank you all very much! It works for me well now, I just forgot to close this issue🤭
