### ISSUE TITLE
Unexpected build pass with a not `Send` future

### ISSUE THREAD

**Issue by LYF1999** [rust-lang/rust#108897]
I tried this code:

```rust
use std::{future::Future, pin::Pin};

trait Handler<R> {
    type Resp;
    type Future: Future<Output = Self::Resp> + Send + 'static;
    fn call(self) -> Self::Future;
}

impl<R, F, Res, Fut> Handler<R> for F
where
    Res: 'static,
    Fut: Future<Output = Res> + Send,
    F: FnOnce() -> Fut + Send + Clone + 'static,
{
    type Resp = Res;

    type Future = Pin<Box<dyn Future<Output = Self::Resp> + Send>>;

    fn call(self) -> Self::Future {
        Box::pin(async move {
            let res = self().await;
            res
        })
    }
}

fn require_handler<H: Handler<()>>(h: H) {}

async fn handler() -> () {
    let a = &1 as *const i32;
    async {}.await;
}

fn main() {
    require_handler(handler)
}
```

I expected to see this happen:
build failed, because this future doesn't implement Send, so this function shouldn't implement `Handler`
```
error: future cannot be sent between threads safely
  --> src/main.rs:35:21
   |
35 |     require_handler(handler)
   |                     ^^^^^^^ future returned by `handler` is not `Send`
   |
   = help: within `impl Future<Output = ()>`, the trait `Send` is not implemented for `*const i32`
note: future is not `Send` as this value is used across an await
  --> src/main.rs:31:13
   |
30 |     let a = &1 as *const i32;
   |         - has type `*const i32` which is not `Send`
31 |     async {}.await;
   |             ^^^^^^ await occurs here, with `a` maybe used later
32 | }
   | - `a` is later dropped here
note: required by a bound in `require_handler`
  --> src/main.rs:27:23
   |
27 | fn require_handler<H: Handler<()>>(h: H) {}
   |                       ^^^^^^^^^^^ required by this bound in `require_handler`
```

Instead, this happened: 
build pass

### Meta

`rustc --version --verbose`:
```
rustc 1.70.0-nightly (e3dfeeaa4 2023-03-07)
binary: rustc
commit-hash: e3dfeeaa45f117281b19773d67f3f253de65cee1
commit-date: 2023-03-07
host: aarch64-apple-darwin
release: 1.70.0-nightly
LLVM version: 15.0.7
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>
cargo-bisect-rustc show the Regression in 9bb6e60d1f1360234aae90c97964c0fa5524f141    

this bug is introduced by this PR https://github.com/rust-lang/rust/pull/103695.

**Comment by LYF1999** [comment]
I think it's a very serious bug, should we revert this change? @lcnr

**Comment by lcnr** [comment]
minimized
```rust
use std::future::Future;

trait Handler {}
impl<F, Fut> Handler for F
where
    Fut: Future + Send,
    F: FnOnce() -> Fut + Send + Clone + 'static,
{}

fn require_handler<H: Handler>(h: H) {}

async fn handler() {
    let a = &1 as *const i32;
    async {}.await;
}

fn main() {
    require_handler(handler)
}
```
ah, figured out the issue https://github.com/rust-lang/rust/pull/103695/files#r1129308806

how did you catch this bug?

**Comment by LYF1999** [comment]
I try to find the minimized example of https://github.com/rust-lang/rust/issues/108847.
there is a ICE with a unsend future in this issue

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23108897.20Unexpected.20build.20pass.20with.20a.20not.20.60Send.60.20future)).

@rustbot label -I-prioritize +P-critical

**Comment by compiler-errors** [comment]
Isn't this a stable-to-beta regression since nightly just branched?

**Comment by wesleywiser** [comment]
Just to clarify since we're in the confusing week where stable & beta are discontinuous version numbers:

| Version | Has this bug | 
| - | - |
| 1.67 (current stable) | No | 
| 1.68 (stable release on Thursday) | No |
| 1.69 (beta) | Yes |
| 1.70 (nightly) | Yes |
