### ISSUE TITLE
remove `find_map_relevant_impl`

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#108895]
https://github.com/rust-lang/rust/blob/9b60e6c68ff0aabad9a0edd71898466886dbf6bb/compiler/rustc_middle/src/ty/trait_def.rs#L153-L158

This function iterates over all impls which may apply to `self_ty` and returns the first `Some`. Note that just because an impl is given to `f` it may not actually apply to the whole `trait_ref` (or deeply matches `self_ty`). Because of this it ends up being very easy to misuse. Let's go through a few incorrect uses of this function:

https://github.com/rust-lang/rust/blob/9b60e6c68ff0aabad9a0edd71898466886dbf6bb/src/librustdoc/passes/collect_intra_doc_links.rs#L738-L763

only looks at the first maybe applicable impl even if there are multiple, idk how exactly that function is used, but it should be wrong :sweat_smile: 

https://github.com/rust-lang/rust/blob/9b60e6c68ff0aabad9a0edd71898466886dbf6bb/compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs#L2195-L2197

Checks whether another trait with the same path has an impl for `self_ty`. Note that this emits the error message if 2 versions of a crate are used, but the substs implement *neither* of the traits.

https://github.com/rust-lang/rust/blob/9b60e6c68ff0aabad9a0edd71898466886dbf6bb/compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs#L1818

whatever this is doing :sweat_smile: but this should be usable to point to an impl which doesn't actually apply.

I would like to change all the uses of `find_map_relevant_impl` to instead use `for_each_relevant_impl`.

**Comment by jyn514** [comment]
Oh hi, I wrote that rustdoc code 😆 

> only looks at the first maybe applicable impl even if there are multiple, idk how exactly that function is used, but it should be wrong

What does it mean for multiple impls to be applicable? Like different generic arguments for the same generic type? That should be ok - rustdoc is just checking if these functions exist at all, not whether

**Comment by jyn514** [comment]
(*hate* mobile GitHub 😠 )

**Comment by compiler-errors** [comment]
@vincenzopalazzo are you working on this? I think I'd like to finish this unless you've already put a lot of time into this.

**Comment by vincenzopalazzo** [comment]
@compiler-errors Sorry I did not have time, so take it. Can you cc me on the PR when it is out I would like to see the code 😄
