### ISSUE TITLE
Segmentation fault in callback of nomicon's ffi chapter.

### ISSUE THREAD

**Issue by nagexiucai** [rust-lang/rust#108848]
I had tested with the [reference](https://doc.rust-lang.org/nomicon/ffi.html#callbacks-from-c-code-to-rust-functions), but met a segmentation fault.

Because the global function pointer `cb` is `NULL` when called it, though had registered it(set as `extern fn callback` in rust).

**Comment by zirconium-n** [comment]
What have you tried? If you copy pasted the code and linked properly you should see
```
I'm called from C with value 7
```

**Comment by workingjubilee** [comment]
It is important that you use the right name, also. `#[link(name = "extlib")]` means that you would have to compile and create `extlib.so` in order to link it.

**Comment by nagexiucai** [comment]
Haha~, it is solved.

```c
typedef void (*callback)(int);
// global cb
callback cb;

// parameter cb
void register(callback cb) {
    cb = cb; // XXX: the reason, rename parameter cb to _cb.
}

void call() {
    cb(9527);
}
// ...
```

But what's the relationship between `parameter cb` and `global cb`?
