### ISSUE TITLE
Enabling recursion in Visitor.visit_ty makes the compiler reject fixed-length arrays

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#10894]
It turns out that the compiler has a blank implementation of `visit_ty` (which does not recurse). The only relevant recursing is the `visit_expr` on the length of a fixed-length vector. If recursion is enabled (which I'm doing), the compiler dies all over the place because the expression doesn't have a type listed in the `tcx`.

For now I'm disabling recursion manually (to restore the old behavior), and tagging all relevant locations with this issue.

cc @nikomatsakis 
cc @pnkfelix

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/blob/a0f86de49748b472d4d189d9688b0d856c000914/src/libsyntax/visit.rs#L76 <- I _think_ this was fixed. And non of the `visit_ty` methods are blank now.

**Comment by ipetkov** [comment]
There is still a reference to this bug present in the source, namely the lint visitor: https://github.com/rust-lang/rust/blob/master/src/librustc/lint/context.rs#L645
