### ISSUE TITLE
Can't check equality of struct without their data

### ISSUE THREAD

**Issue by MahanBi** [rust-lang/rust#109027]
```rust
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, PartialOrd)]
pub struct Frame<'a> {
    pub kind: u8,
    pub content: Content<'a>
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, PartialOrd)]
#[serde(untagged)]
pub enum Content<'a> {
    Message {
        sender: &'a str, // sender friendship token
        receiver: &'a str, // receiver friendship token
        message: &'a str // message
    },
    RegisterServer,
    RegisterUser
}
```
this is my code

```rust
impl Frame<'_> {
    fn ser(mut buffer: Vec<u8>) -> Option<Self> {
        let ser = serde_json::from_slice::<Self>(buffer.as_mut_slice()).ok()?;
        match ser.kind {
            1 if ser.content == Content::Message {  }  => Some(ser),
            2 if ser.content == Content::RegisterServer => Some(ser),
            3 if ser.content == Content::RegisterUser => Some(ser),
            _ => None
        }
    }
}
```
i can't check equality of two Content::Message without their data

**Comment by cjgillot** [comment]
Could you elaborate what is the issue?

**Comment by Nilstrieb** [comment]
```diff
-            1 if ser.content == Content::Message {  }  => Some(ser),
+            1 if matches!(Content::Message { .. }, ser.content)  => Some(ser),
```
The `matches` macro is intended for this (it's just a `match` internally).

For future questions I recommend going to https://users.rust-lang.org/ or official or unoffial community discord server instead, as this issue tracker isn't a help forum.

**Comment by MahanBi** [comment]
> ```diff
> -            1 if ser.content == Content::Message {  }  => Some(ser),
> +            1 if matches!(Content::Message { .. }, ser.content)  => Some(ser),
> ```
> 
> The `matches` macro is intended for this (it's just a `match` internally).
> 
> For future questions I recommend going to https://users.rust-lang.org/ or official or unoffial community discord server instead, as this issue tracker isn't a help forum.

I tried it but it didn't work
I think that such a problem needs to be considered as a new feature

**Comment by Nilstrieb** [comment]
> I tried it but it didn't work
What do you mean with "doesn't work"? We can't really help you with that description. It does work if done correctly so we don't need a new feature for this. Could you elaborate on your problem?

**Comment by MahanBi** [comment]
error come from other thing and matches!() is working thanks
