### ISSUE TITLE
Command line is empty when using #![windows_subsystem = "windows"]

### ISSUE THREAD

**Issue by Yabgu** [rust-lang/rust#109038]
I cannot get arguments on Windows GUI app.  

I tried this code:

```rust
#![windows_subsystem = "windows"]
use winsafe;

fn main() {
    let arguments: Vec<String> = std::env::args().collect();
    dbg!(arguments);

    let commandline = winsafe::GetCommandLine();
    dbg!(commandline);
}
```

when I run "cargo run argument1 argument2" I should be able to see the arguments I am passing. It works if I remove the "windows_subsystem" attribute. Executable arguments should be available because this is how windows pass files to executables,

### Meta
`rustc --version --verbose`:
```
rustc 1.66.0 (69f9c33d7 2022-12-12)
binary: rustc
commit-hash: 69f9c33d71c871fc16ac445211281c6e7a340943
commit-date: 2022-12-12
host: x86_64-pc-windows-msvc
release: 1.66.0
LLVM version: 15.0.2
```

**Comment by workingjubilee** [comment]
cc @ChrisDenton ?

**Comment by ChrisDenton** [comment]
`#![windows_subsystem = "windows"]` creates a new GUI application with no console attached (by default). So when you try to write to stdout it fails. Currently Rust silently ignores this error, see [Windows Portability Considerations](https://doc.rust-lang.org/std/io/fn.stdout.html#note-windows-portability-considerations). 

Therefore if you need a console (for debugging or some such) then you'll need to allocate one. And to make sure the console doesn't close too quickly to be read you may want to wait at the end.

Here's a rough example:
```rust
#![windows_subsystem = "windows"]
use std::io::{self, Read};

fn console_main() {
    println!("Hello world!");
}

fn main() {
    // Quick hack to see if a console is attached to the process.
    let has_console = unsafe { GetConsoleOutputCP() != 0 };
    if !has_console {
        // Try to allocate a console.
        unsafe { AllocConsole() };
    }

    console_main();

    if console_closes_on_exit() {
        println!("Press enter to exit");
        io::stdin().bytes().next();
    }
}

fn console_closes_on_exit() -> bool {
    // A console closes once the last process exits.
    // So check if we're the only process connected to this console.
    let mut list = [0u32];
    let count = unsafe { GetConsoleProcessList(list.as_mut_ptr(), 1) };
    count == 1
}

// Ideally a crate should be used for these definitions.
extern "system" {
    fn GetConsoleOutputCP() -> u32;
    fn AllocConsole() -> i32;
    fn GetConsoleProcessList(list: *mut u32, count: u32) -> u32;
}
```

**Comment by Yabgu** [comment]
I should not need console for getting commandline. I was using this feature in many languages and every other language works as expected; For simplicity, I will share a very simple C program below:

```cpp
#include <windows.h>
#include <tchar.h>

int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow)
{
  MessageBox(NULL, GetCommandLine(), TEXT("Arguments"), MB_OK);
  return 0;
}

```
It does not matter if I compile it with -mwindows (gcc test.c -mwindows) or not, it will show me the command line either with console or without console, It always works! 

When it comes to rust, this information is lost most probably due to an incorrect calling convention being used,

Look in the call stack if I go to the lowest level the command line is still there:
![image](https://user-images.githubusercontent.com/13639182/224549585-6dafd648-8274-4765-848b-83161e31c56c.png)

the code used for this is below
```rust
#![windows_subsystem = "windows"]

fn main() {
    unsafe {
        let cmdline = windows::Win32::System::Environment::GetCommandLineW(); // returns wrong address with #![windows_subsystem = "windows"]
        // If you go to the parent stack on the debugger and call above "main" this works either way

        dbg!(cmdline); 
    }
}
```

There must be a bug in the compiler/linker, GetCommandLineW is *not* a console-only call:
 https://learn.microsoft.com/en-us/windows/win32/api/processenv/nf-processenv-getcommandlinew

**Comment by ChrisDenton** [comment]
Sorry, I was unclear. This has nothing to do with `GetCommandLineW` but with printing to stdout (which doesn't exist by default). For example, try writing to a file instead.

This writes the command line to `output.txt`
```rust
#![windows_subsystem = "windows"]
use winsafe;

use std::fs;
use std::io::{self, Write};

fn main() -> io::Result<()> {
    let mut f = fs::File::create("output.txt")?;
    let commandline = winsafe::GetCommandLine();
    f.write_all(commandline.as_bytes())?;
    Ok(())
}
```

**Comment by Yabgu** [comment]
I see why I am not getting console output. Rust GUI apps also close the console handle by default. Thank you for pointing me out,
