### ISSUE TITLE
return_position_impl_trait_in_trait lifetimes on self

### ISSUE THREAD

**Issue by gilescope** [rust-lang/rust#109016]
The following compiles:

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=b0b57210e4369ac10e2dd694644cfbaf

But if you take away `<'a>` then the code doesn't compile. It compiles if `self` rather than `&self` is used. Is this as good as it gets? Would have expected this to work without the `'a`s. (I appreicate this is work in progress, hope this helps, sorry if it's a dupe).

**Comment by cjgillot** [comment]
What do you mean "if you take away <'a>"? Where do you take those from? Which `&self` becomes `self`?

**Comment by Jules-Bertholet** [comment]
I think @gilescope means that

```rust
#![feature(async_fn_in_trait)]
#![feature(return_position_impl_trait_in_trait)]
use core::future::Future;

pub trait Trait {
    fn foo(&self) -> impl Future<Output = ()>;
}

pub struct S;

impl Trait for S {
    async fn foo(&self) -> () {}
}
```

fails to compile, while

```rust
#![feature(async_fn_in_trait)]
#![feature(return_position_impl_trait_in_trait)]
use core::future::Future;

pub trait Trait<'a> {
    fn foo(&'a self) -> impl Future<Output = ()>;
}

pub struct S;

impl<'a> Trait<'a> for S {
    async fn foo(&'a self) -> () {}
}
```

compiles fine.

**Comment by eholk** [comment]
You can also make this compile by changing the return type in the trait definition to be `-> impl Future<Output = ()> + '_`, which is basically what `async fn` desugars too.

```rust
#![feature(async_fn_in_trait)]
#![feature(return_position_impl_trait_in_trait)]
use core::future::Future;

pub trait Trait {
	fn foo(&self) -> impl Future<Output = ()> + '_;
}

pub struct S;

impl Trait for S {
	async fn foo(&self) -> () {}
}
```

**Comment by eholk** [comment]
After discussing at wg-async triage, it looks like the behavior here is correct but the error messages are unclear. In particular, it'd be good for the error message to mention `+ '_` somehow to suggest how to workaround this issue and match the `async fn` desugaring.

**Comment by compiler-errors** [comment]
Given:

```
#![feature(async_fn_in_trait)]
#![feature(return_position_impl_trait_in_trait)]

use core::future::Future;

pub trait Trait {
    fn foo(&self) -> impl Future<Output = ()>;
}

pub struct S;

impl Trait for S {
    async fn foo(&self) -> () {}
}
```

The error message is now:

```
error: return type captures more lifetimes than trait definition
  --> src/lib.rs:13:28
   |
13 |     async fn foo(&self) -> () {}
   |                  -         ^^
   |                  |
   |                  this lifetime was captured
   |
note: hidden type must only reference lifetimes captured by this impl trait
  --> src/lib.rs:7:22
   |
7  |     fn foo(&self) -> impl Future<Output = ()>;
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^
   = note: hidden type inferred to be `impl Future<Output = ()>`
```

I consider this to be sufficiently improved.

**Comment by vincenzopalazzo** [comment]
I still do not understand from the error that `+ '_` is the missing part of my not async trait

**Comment by compiler-errors** [comment]
It's not `+ '_`, it's that the lifetime is not captured. The "correct" way to capture this lifetime would be something more like...

```
trait Captures<'a> {}
impl<'a, T> Captures<'a> for T {}

pub trait Trait {
    fn foo(&self) -> impl Future<Output = ()> + Captures<'_>;
}
```

But this whole issue is not even a problem anymore, since we're changing the way that return-position impl traits capture lifetimes.
