### ISSUE TITLE
For loop optimizes out comparison in -O as of rust 1.60 through 1.68

### ISSUE THREAD

**Issue by Silvea12** [rust-lang/rust#109159]
Reproduction case: https://godbolt.org/z/nnb3oxYM9

I tried this code:
```rust
#[derive(Clone)]
pub struct OpaqueType;

extern { fn compare(value: &OpaqueType) -> u32; }

pub fn e(values: &[OpaqueType]) -> OpaqueType {
    values
        .into_iter()
        .max_by_key(|e| unsafe { compare(e) })
        .unwrap()
        .clone()
}

pub fn f(values: &[OpaqueType]) -> OpaqueType {
    let mut acc: &OpaqueType = &values[0];
    let mut accScore: u32 = unsafe { compare(acc) };

    for value in values {
        let score = unsafe { compare(value) };
        if score > accScore {
            accScore = score;
            acc = value;
        }
    }

    return acc.clone()
}
```
In the case of `e()`, all works correctly. However, with `f()`, the `if score > accScore` check is entirely compiled out. See the godbolt above for a comparison between 1.59 and 1.60 (`.LBB1_3` in both cases)

<details><summary>Relevant ASM of functional</summary>

```
.LBB1_3:
        mov     rdi, r14
        call    r15
        cmp     eax, ebp
        cmova   ebp, eax
        cmova   rbx, r14
        add     r12, -1
        jne     .LBB1_3
```
</details>

<details><summary>Relevant ASM of imperitive</summary>

```
.LBB1_3:
        mov     rdi, r14
        call    r15
        add     rbx, -1
        jne     .LBB1_3
```
</details>

Worth noting: the purpose of `unsafe` here is to just allow us not to use a black box, as we don't want it in the asm. This can be reproduced with it too, but this ensures there is no inlining.

### Meta
`rustc --version --verbose`: Cannot be provided, found in godbolt - passes in 1.59, fails in 1.60, also fails in every subsequent version including 1.68.0

Backtrace: Cannot be provided, not a crash

**Comment by nikic** [comment]
Removing the comparison is correct, because `OpaqueType` is ZST and you're taking the maximum across N times the same value, which is the same as using the first.

Your test case is probably over-reduced and you did not mean to use a ZST?

**Comment by Silvea12** [comment]
Oh! Seems you're right! Changing its signature to `pub struct OpaqueType(String);` completely fixes the issue. That was not an optimization I expected to see.

**Comment by Silvea12** [comment]
Actually, hold up. If the function underneath was to, say, increment a counter and return that counter value, so every time it is called it returns a different value, wouldn't that cause issues? This is something that is allowed in safe rust if you were to say, use a static with once_cell holding a Cell or a Mutex to allow for internal mutability. This can also happen with C libraries.

From what I understand, there is no specific requirement that safe methods be pure.

**Comment by nikic** [comment]
Uh yeah, you're right. Let me take a look.

**Comment by nikic** [comment]
Okay, the reasoning needs to be a different, but it's basically the same issue: The `accScore` doesn't actually matter, because the only thing the function returns is the element with the highest score, and that will always be `values[0]` (which is the same as `values[N]` for all N).

**Comment by Silvea12** [comment]
... Oh y'know what yeah, you're right. Returning the accScore instead does actually do the comparison. That's smart. Closing this!
