### ISSUE TITLE
build: bootstrap fails when using --enable-local-rust option

### ISSUE THREAD

**Issue by filnet** [rust-lang/rust#109103]
### Issue

Building rust with the `--enable-local-rust` option fails with a symbolic link creation error.

Reverting https://github.com/rust-lang/rust/commit/6f0fc2fd337757a02fa0d948e78638d66a46f518 fixes the issue.

### Version it worked on

It most recently worked on: Rust 1.67.1

### Version with regression

Rust 1.68.0

### Backtrace

<details><summary>Backtrace</summary>
<p>

```
thread 'main' panicked at 'symlink_dir(C:\M\mingw-w64-rust\src\MINGW64\build\host => C:\M\mingw-w64-rust\src\MINGW64\build\x86_64-pc-windows-gnu) failed with Le fichier spécifié est introuvable. (os error 2)', lib.rs:599:17
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: bootstrap::Build::new
             at C:\M\mingw-w64-rust\src\rustc-1.68.0-src\src\bootstrap\lib.rs:599:17
   3: bootstrap::main
             at C:\M\mingw-w64-rust\src\rustc-1.68.0-src\src\bootstrap\bin\main.rs:50:5
   4: core::ops::function::FnOnce::call_once
             at C:\M\mingw-w64-rust\src\rustc-1.67.1-src\library\core\src\ops\function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Build completed unsuccessfully in 0:00:32
```

</p>
</details>

**Comment by filnet** [comment]
> does this issue occur with x86_64-windows-msvc.

I am one of the maintainers of the Rust build at https://www.msys2.org/.

The upgrade from 1.67.1 to 1.68.0 broke the aarch64 build (which uses the --enable-local-rust option).
We can also reproduce it on other architectures and toolchains.

**Comment by jyn514** [comment]
I ... don't see how this could be related to --enable-local-rust? we're not modifying anything in the stage 0 directory, only in the build directory. do you still see this issue if you remove that option?

**Comment by jyn514** [comment]
oh I see, when that option is enabled bootstrap.py doesn't download the toolchain and so there's no `x86_64-pc-windows-gnu` folder yet. the correct fix is to add create_dir_all(build_triple) just after
https://github.com/rust-lang/rust/blob/8efa635b40ce6569e12f4988b7a9bcb7f3f0ed0c/src/bootstrap/lib.rs#L497

**Comment by filnet** [comment]
> I ... don't see how this could be related to --enable-local-rust? we're not modifying anything in the stage 0 directory, only in the build directory. do you still see this issue if you remove that option?

Using --enable-local-rust will skip downloading and extracting the previous Rust version.
The new code tries to create a symlink from `host` to a directory that was supposedly extracted (but was not).

There is the same issue with --local-rust-root btw.
