### ISSUE TITLE
Panic occurs when initialize dynamicly created vector 

### ISSUE THREAD

**Issue by jongwu** [rust-lang/rust#109113]
I tried this code:

```rust
use std::env;
use std::arch::asm;

fn main() {
    let mut sp: u64;
    unsafe {
        asm!("mov {0}, sp", out (reg) sp);
    }
    println!("current sp is {:x}", sp);
    if let Some(n) = get_arg() {
        println!("get parameter: {}", n);
        let mut v = vec![0, n];
        my_print(&mut v, n as usize);
    }
}

fn my_print(v: &mut [i32], n: usize) {
    println!("pointer of v is {:p}, len of v is {}", &v, &v.len());
    for i in 0..n {
        v[i] = 0;
    }
}

fn get_arg() -> Option<i32> {
    let args: Vec<String> = env::args().collect();
    if args.len() > 1 {
        let need = args[1].parse().unwrap();
        Some(need)
    } else {
        None
    }
}
```

I expected to see this happen: *run it with parameter 100 and expect it run successfully.*

Instead, this happened: *it panic with the following error:*

when build in release mode:

`current sp is fffff1bb39a0
pointer of v is 0xfffff1bb39a8
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', src/main.rs:19:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

when build in debug mode:

`current sp is fffff8be0fa0
get parameter: 100
pointer of v is 0xfffff8be0ed8, len of v is 2
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', src/main.rs:20:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

There are 2 question:
1. why allocate dynamic vector in stack? And in release mode, vector reside in function stack but debug mode not.
2. why the dynamic vector size is 2 no matter what value you give.

### Meta

`rustc --version --verbose`:
```
rustc 1.67.1 (d5a82bbd2 2023-02-07)
binary: rustc
commit-hash: d5a82bbd26e1ad8b7401f6a718a9c57c96905483
commit-date: 2023-02-07
host: aarch64-unknown-linux-gnu
release: 1.67.1
LLVM version: 15.0.6
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by SkiFire13** [comment]
> 1. why allocate dynamic vector in stack?

The vector is not allocated on the stack. You're printing the address of the reference to the vector. This is due to the `&v` in this line of code:

>     println!("pointer of v is {:p}, len of v is {}", &v, &v.len());

Try using just `v` instead of `&v` here. It's also good practice to use `v.len()` instead of `&v.len()`.

> And in release mode, vector reside in function stack but debug mode not.

It's still in the function stack, it's just that there are more values on the stack and its address is further away from sp.

> 2. why the dynamic vector size is 2 no matter what value you give.

The problem is this piece of code:

>     let mut v = vec![0, n];

This creates a `Vec` with two elements: `0` and `n`. You likely want `vec![0; n]`, which will create a `Vec` with `n` elements equal to `0`.

**Comment by jongwu** [comment]
Thanks @SkiFire13 -, it's my fault to write the this terrible code. I have no question for now and will close this.  Thanks again!
