### ISSUE TITLE
gitui compilation in termux/nethunter

### ISSUE THREAD

**Issue by vkavoun** [rust-lang/rust#109228]
└─$ cargo install gitui
    Updating crates.io index
  Installing gitui v0.22.1
    Updating crates.io index
   Compiling libc v0.2.140
   Compiling autocfg v1.1.0
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.52
   Compiling unicode-ident v1.0.8
   Compiling quote v1.0.26
   Compiling memchr v2.5.0
   Compiling syn v1.0.109
   Compiling pkg-config v0.3.26
   Compiling log v0.4.17
   Compiling bitflags v1.3.2
   Compiling serde_derive v1.0.156
   Compiling crossbeam-utils v0.8.15
   Compiling serde v1.0.156
   Compiling scopeguard v1.1.0
   Compiling version_check v0.9.4
   Compiling jobserver v0.1.26
   Compiling ahash v0.7.6
   Compiling getrandom v0.2.8
   Compiling cc v1.0.79
   Compiling memoffset v0.8.0
   Compiling once_cell v1.17.1
   Compiling tinyvec_macros v0.1.1
   Compiling aho-corasick v0.7.20
   Compiling tinyvec v1.6.0
   Compiling mio v0.8.6
   Compiling lock_api v0.4.9
   Compiling openssl-src v111.25.1+1.1.1t
   Compiling crossbeam-epoch v0.9.14
   Compiling parking_lot_core v0.9.7
   Compiling io-lifetimes v1.0.7
   Compiling signal-hook v0.3.15
   Compiling thiserror v1.0.39
   Compiling regex-syntax v0.6.28
   Compiling proc-macro-hack v0.5.20+deprecated
   Compiling unicode-normalization v0.1.22
   Compiling openssl-sys v0.9.81
   Compiling libz-sys v1.1.8
   Compiling libssh2-sys v0.2.23
   Compiling sys-info v0.9.1
   Compiling libgit2-sys v0.14.2+1.5.1
   Compiling hashbrown v0.12.3
   Compiling signal-hook-registry v1.4.1
   Compiling crossbeam-channel v0.5.7
   Compiling thiserror-impl v1.0.39
   Compiling num-traits v0.2.15
   Compiling unicode-width v0.1.10
   Compiling regex v1.7.1
   Compiling percent-encoding v2.2.0
   Compiling smallvec v1.10.0
   Compiling itoa v1.0.6
   Compiling adler v1.0.2
   Compiling crc32fast v1.3.2
   Compiling rustix v0.36.9
   Compiling same-file v1.0.6
   Compiling unicode-bidi v0.3.11
   Compiling walkdir v2.3.3
   Compiling idna v0.3.0
   Compiling miniz_oxide v0.6.2
   Compiling form_urlencoded v1.1.0
   Compiling unicode-linebreak v0.1.4
   Compiling dirs-sys v0.3.7
   Compiling inotify-sys v0.1.5
   Compiling num-integer v0.1.45
   Compiling siphasher v0.3.10
   Compiling serde_json v1.0.94
   Compiling bit-vec v0.6.3
   Compiling time-core v0.1.0
   Compiling linux-raw-sys v0.1.4
   Compiling rayon-core v1.11.0
   Compiling git-version-macro v0.3.5
   Compiling bit-set v0.5.3
   Compiling time-macros v0.2.8
   Compiling phf_shared v0.11.1
   Compiling dirs v4.0.0
   Compiling inotify v0.9.6
   Compiling parking_lot v0.12.1
   Compiling crossbeam-deque v0.8.3
   Compiling signal-hook-mio v0.2.3
   Compiling url v2.3.1
   Compiling backtrace v0.3.67
   Compiling filetime v0.2.20
   Compiling num_cpus v1.15.0
   Compiling scopetime v0.1.2
   Compiling gimli v0.27.2
   Compiling openssl-probe v0.1.5
   Compiling bugreport v0.5.0
   Compiling anyhow v1.0.69
   Compiling ryu v1.0.13
   Compiling os_str_bytes v6.4.1
   Compiling either v1.8.1
   Compiling clap_lex v0.3.2
   Compiling is-terminal v0.4.4
   Compiling notify v5.1.0
   Compiling flate2 v1.0.25
   Compiling bincode v1.3.3
error: internal compiler error: /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/compiler/rustc_infer/src/infer/outlives/env.rs:145:26: add_outlives_bounds: unexpected regions

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/compiler/rustc_errors/src/lib.rs:1644:9
stack backtrace:
   0: 0xafa0cea0 - std::backtrace_rs::backtrace::libunwind::trace::h4ca248b3029f8aa0
                       at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1: 0xafa0cea0 - std::backtrace_rs::backtrace::trace_unsynchronized::hdf8076e44bed8c39
                       at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: 0xafa0cea0 - std::sys_common::backtrace::_print_fmt::h23a84294aadd1cc2
                       at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/std/src/sys_common/backtrace.rs:65:5
   3: 0xafa0cea0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h02845744c9e13b1e
                       at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/std/src/sys_common/backtrace.rs:44:22
   4: 0xafa748c8 - core::fmt::write::he2db3ac5f8bc9232
                       at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/core/src/fmt/mod.rs:1232:17
   5: 0xafa01198 - std::io::Write::write_fmt::hd177e6112326e47c
                       at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/std/src/io/mod.rs:1684:15
   6: 0xafa0cc84 - std::sys_common::backtrace::_print::hbae87f55e995f4b2
                       at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/std/src/sys_common/backtrace.rs:47:5
   7: 0xafa0cc84 - std::sys_common::backtrace::print::he7291d273844e40a
                       at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/std/src/sys_common/backtrace.rs:34:9
   8: 0xafa0fa00 - std::panicking::default_hook::{{closure}}::hf09b7fd48fa9d290
                       at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/std/src/panicking.rs:271:22
   9: 0xafa0f6d4 - std::panicking::default_hook::h165fe20072cd91f9
                       at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/std/src/panicking.rs:290:9
  10: 0xb024cf00 - rustc_driver_impl[501fd6f0bc8023d2]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11: 0xafa1019c - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h5678d3ccf8b997ef
                       at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/alloc/src/boxed.rs:2002:9
  12: 0xafa1019c - std::panicking::rust_panic_with_hook::h4acfe9e6f13c2d09
                       at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/std/src/panicking.rs:696:13
  13: 0xb45d8b60 - std[e8b74839ceaa9bd]::panicking::begin_panic::<rustc_errors[34da18e37e7c2fc0]::ExplicitBug>::{closure#0}
  14: 0xb45d6e2c - std[e8b74839ceaa9bd]::sys_common::backtrace::__rust_end_short_backtrace::<std[e8b74839ceaa9bd]::panicking::begin_panic<rustc_errors[34da18e37e7c2fc0]::ExplicitBug>::{closure#0}, !>
  15: 0xb0183fc4 - std[e8b74839ceaa9bd]::panicking::begin_panic::<rustc_errors[34da18e37e7c2fc0]::ExplicitBug>
  16: 0xb46aea58 - std[e8b74839ceaa9bd]::panic::panic_any::<rustc_errors[34da18e37e7c2fc0]::ExplicitBug>
  17: 0xb46abfec - <rustc_errors[34da18e37e7c2fc0]::HandlerInner>::bug::<&alloc[2717dbf13523eee7]::string::String>
  18: 0xb46abbf8 - <rustc_errors[34da18e37e7c2fc0]::Handler>::bug::<&alloc[2717dbf13523eee7]::string::String>
  19: 0xb468ded0 - rustc_middle[5f754d0da48079ef]::util::bug::opt_span_bug_fmt::<rustc_span[600e88b0fdd771f4]::span_encoding::Span>::{closure#0}
  20: 0xb46890d0 - rustc_middle[5f754d0da48079ef]::ty::context::tls::with_opt::<rustc_middle[5f754d0da48079ef]::util::bug::opt_span_bug_fmt<rustc_span[600e88b0fdd771f4]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21: 0xb4689094 - rustc_middle[5f754d0da48079ef]::ty::context::tls::with_context_opt::<rustc_middle[5f754d0da48079ef]::ty::context::tls::with_opt<rustc_middle[5f754d0da48079ef]::util::bug::opt_span_bug_fmt<rustc_span[600e88b0fdd771f4]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22: 0xb468de24 - rustc_middle[5f754d0da48079ef]::util::bug::opt_span_bug_fmt::<rustc_span[600e88b0fdd771f4]::span_encoding::Span>
  23: 0xb01865c4 - rustc_middle[5f754d0da48079ef]::util::bug::bug_fmt
  24: 0xb2735e4c - <rustc_infer[e73e352ee83eaf26]::infer::outlives::env::OutlivesEnvironment>::with_bounds::<core[70e9ffeb60a3b63e]::iter::adapters::flatten::Flatten<core[70e9ffeb60a3b63e]::iter::adapters::map::Map<indexmap[aea43403f3b7b0c9]::set::IntoIter<rustc_middle[5f754d0da48079ef]::ty::Ty>, <rustc_infer[e73e352ee83eaf26]::infer::InferCtxt as rustc_trait_selection[7d4768469b236d56]::traits::outlives_bounds::InferCtxtExt>::implied_bounds_tys::{closure#0}>>>
  25: 0xb26ff024 - rustc_hir_analysis[767e05e9adc6f961]::check::compare_impl_item::compare_method_predicate_entailment
  26: 0xb26f4044 - rustc_hir_analysis[767e05e9adc6f961]::check::compare_impl_item::compare_impl_method
  27: 0xb266e174 - rustc_hir_analysis[767e05e9adc6f961]::check::check::check_impl_items_against_trait
  28: 0xb2668170 - rustc_hir_analysis[767e05e9adc6f961]::check::check::check_item_type
  29: 0xb267447c - rustc_hir_analysis[767e05e9adc6f961]::check::check::check_mod_item_types
  30: 0xb386a860 - rustc_query_system[ae5412f1d8e7fa61]::query::plumbing::try_execute_query::<rustc_query_impl[68f3e846c25d173c]::queries::check_mod_item_types, rustc_query_impl[68f3e846c25d173c]::plumbing::QueryCtxt>
  31: 0xb35845bc - <rustc_query_impl[68f3e846c25d173c]::Queries as rustc_middle[5f754d0da48079ef]::ty::query::QueryEngine>::check_mod_item_types
  32: 0xb26c0448 - <rustc_middle[5f754d0da48079ef]::hir::map::Map>::for_each_module::<rustc_hir_analysis[767e05e9adc6f961]::check_crate::{closure#6}::{closure#0}>
  33: 0xb26e44a4 - <rustc_session[c3f8a745acb97a01]::session::Session>::time::<(), rustc_hir_analysis[767e05e9adc6f961]::check_crate::{closure#6}>
  34: 0xb275b41c - rustc_hir_analysis[767e05e9adc6f961]::check_crate
  35: 0xb03a2df8 - rustc_interface[be7de4564c4ec6b4]::passes::analysis
  36: 0xb3904f2c - rustc_query_system[ae5412f1d8e7fa61]::query::plumbing::try_execute_query::<rustc_query_impl[68f3e846c25d173c]::queries::analysis, rustc_query_impl[68f3e846c25d173c]::plumbing::QueryCtxt>
  37: 0xb357a7f0 - <rustc_query_impl[68f3e846c25d173c]::Queries as rustc_middle[5f754d0da48079ef]::ty::query::QueryEngine>::analysis
  38: 0xb028d328 - <rustc_middle[5f754d0da48079ef]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[501fd6f0bc8023d2]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[70e9ffeb60a3b63e]::result::Result<(), rustc_span[600e88b0fdd771f4]::ErrorGuaranteed>>
  39: 0xb028b584 - rustc_span[600e88b0fdd771f4]::with_source_map::<core[70e9ffeb60a3b63e]::result::Result<(), rustc_span[600e88b0fdd771f4]::ErrorGuaranteed>, rustc_interface[be7de4564c4ec6b4]::interface::run_compiler<core[70e9ffeb60a3b63e]::result::Result<(), rustc_span[600e88b0fdd771f4]::ErrorGuaranteed>, rustc_driver_impl[501fd6f0bc8023d2]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  40: 0xb025e990 - std[e8b74839ceaa9bd]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[be7de4564c4ec6b4]::util::run_in_thread_pool_with_globals<rustc_interface[be7de4564c4ec6b4]::interface::run_compiler<core[70e9ffeb60a3b63e]::result::Result<(), rustc_span[600e88b0fdd771f4]::ErrorGuaranteed>, rustc_driver_impl[501fd6f0bc8023d2]::run_compiler::{closure#1}>::{closure#0}, core[70e9ffeb60a3b63e]::result::Result<(), rustc_span[600e88b0fdd771f4]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[70e9ffeb60a3b63e]::result::Result<(), rustc_span[600e88b0fdd771f4]::ErrorGuaranteed>>
  41: 0xb025fa9c - <<std[e8b74839ceaa9bd]::thread::Builder>::spawn_unchecked_<rustc_interface[be7de4564c4ec6b4]::util::run_in_thread_pool_with_globals<rustc_interface[be7de4564c4ec6b4]::interface::run_compiler<core[70e9ffeb60a3b63e]::result::Result<(), rustc_span[600e88b0fdd771f4]::ErrorGuaranteed>, rustc_driver_impl[501fd6f0bc8023d2]::run_compiler::{closure#1}>::{closure#0}, core[70e9ffeb60a3b63e]::result::Result<(), rustc_span[600e88b0fdd771f4]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[70e9ffeb60a3b63e]::result::Result<(), rustc_span[600e88b0fdd771f4]::ErrorGuaranteed>>::{closure#1} as core[70e9ffeb60a3b63e]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  42: 0xafa1a748 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h25b8a4a74c2fc135
                       at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/alloc/src/boxed.rs:1988:9
  43: 0xafa1a748 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h54d869587daadc43
                       at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/alloc/src/boxed.rs:1988:9
  44: 0xafa1a748 - std::sys::unix::thread::Thread::new::thread_start::h45eee0241067666e
                       at /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/library/std/src/sys/unix/thread.rs:108:17

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.70.0-nightly (ab654863c 2023-03-15) running on armv7-unknown-linux-gnueabihf

note: compiler flags: --crate-type lib -C opt-level=z -C linker-plugin-lto -C codegen-units=1

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [check_mod_item_types] checking item types in module `de`
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `bincode` (lib)
warning: build failed, waiting for other jobs to finish...
^C  Building [=================>       ] 159/214: time-macros, openssl-sys(build)

**Comment by Manishearth** [comment]
Filed with a more targeted issue body in https://github.com/rust-lang/rust/issues/109233
