### ISSUE TITLE
MIR inlining breaks --remap-path-prefix

### ISSUE THREAD

**Issue by saethlin** [rust-lang/rust#109289]
Apply this diff:
```diff
diff --git a/tests/codegen/remap_path_prefix/auxiliary/xcrate-generic.rs b/tests/codegen/remap_path_prefix/auxiliary/xcrate-generic.rs
index 59092dbf637..6b292dd8ff8 100644
--- a/tests/codegen/remap_path_prefix/auxiliary/xcrate-generic.rs
+++ b/tests/codegen/remap_path_prefix/auxiliary/xcrate-generic.rs
@@ -3,4 +3,5 @@
 
 #![crate_type = "lib"]
 
+#[inline]
 pub fn foo<T>() {}
```
This will break the associated codegen test, because the function `foo` will get inlined in MIR, and then there is no longer any (remapped) debuginfo for the inlined function.

**Comment by cjgillot** [comment]
I'm not sure how this is an issue. If there is no debuginfo, all of it is correctly remapped, isn't it? 
What am I missing?

**Comment by saethlin** [comment]
That's wild. I swear I tried a number of permutations that should generate debuginfo, and I couldn't induce any to pass the test.

**Comment by saethlin** [comment]
Yep. Don't know what I was doing, everything I've tried now backs up what @cjgillot says above.
