### ISSUE TITLE
Allow Passing Variable as Argument to `format!` and `format_args!`

### ISSUE THREAD

**Issue by basicfunc** [rust-lang/rust#109290]
For the follwing code, no matter what `f` is whether a `string`, `str` or `&str` it returns same error saying `error: format argument must be a string literal`.

I know it needs a string literal but I'm passing a string too, so why this is intentional?
What I could do If I want to rewrite a C code which contains `va_list`, what is same in Rust to implement `va_list`.

Currently, I'm trying to re-write this function, it looks easy in `C` as va_list allows variables to be passed as argument. But why Rust don't allow variable to passed as arguments to `format!` or `format_args!`.
I know there is `std::ffi::va_list`, but I want to do this in `Rust` way without using any foreign bindings or external dependency.

```
static void mpc_err_string_cat(char *buffer, int *pos, int *max, char const *fmt, ...) {
  int left = ((*max) - (*pos));
  va_list va;
  va_start(va, fmt);
  if (left < 0) { left = 0;}
  (*pos) += vsprintf(buffer + (*pos), fmt, va);
  va_end(va);
}
```

```
fn mpc_err_string_cat(buffer: &str, pos: &mut u8, max: &mut u8, fmt: &str, args: Arguments) {
    let mut left = *max - *pos;

    if left < 0 {
        left = 0;
    }

    let f = fmt.to_string();
    let f = format_args!(f, args);

    let mut buff = String::new();
    std::fmt::write(&mut buff, f).unwrap();
} 
```

```
--> src\lib.rs:613:18
    |
613 |     format_args!(f, args);
    |                  ^
    |
help: you might be missing a string literal to format with
    |
613 |     format_args!("{} {}", f, args);
    |                  ++++++++ 
```

Rust Version:
```
rustc 1.67.1 (d5a82bbd2 2023-02-07)
binary: rustc
commit-hash: d5a82bbd26e1ad8b7401f6a718a9c57c96905483
commit-date: 2023-02-07
host: x86_64-pc-windows-msvc
release: 1.67.1
LLVM version: 15.0.6
rust-mpc on  main [!] is 📦 v0.1.0 via C via 🐍 v3.10.10 (.env) via 🦀 v1.67.1 ❯ cargo --version -v
cargo 1.67.1 (8ecd4f20a 2023-01-10)
release: 1.67.1
commit-hash: 8ecd4f20a9efb626975ac18a016d480dc7183d9b
commit-date: 2023-01-10
host: x86_64-pc-windows-msvc
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:Schannel)
os: Windows 10.0.22621 (Windows 10 Home Single Language) [64-bit]
rust-mpc on  main [!] is 📦 v0.1.0 via C via 🐍 v3.10.10 (.env) via 🦀 v1.67.1 ❯
```

**Comment by jyn514** [comment]
This is not a bug, the compiler needs to know the format string at compile time to be type safe.

The issue tracker is not a support forum. For future questions please ask in one of these places:

https://discord.gg/rust-lang/
https://discord.gg/rust-lang-community/
https://users.rust-lang.org/
https://rust-lang.zulipchat.com/
