### ISSUE TITLE
Why does this code not compile and pass, I think it does

### ISSUE THREAD

**Issue by danielesk** [rust-lang/rust#109294]
My version of rust is `rustc 1.68.0 (2c8cc3432 2023-03-06)`
b=false or b=true, the compile time error is the same.
I can't understand how this could be the case
```rust
fn main() {
      let s = String::from("hello");
      let s2;
      let b = false;
      if b {
        s2 = s;
      }
      println!("{}", s);
}
```

**Comment by scottmcm** [comment]
This is intentional behaviour, so closing in favour of the URLO thread that the OP also opened: <https://users.rust-lang.org/t/borrow-of-moved-value-s/91068?u=scottmcm>.
