### ISSUE TITLE
CI random failure on x86_64-apple-2 InvalidInput in create_dir_all while running test/rustdoc/primitive/no_std.rs

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#109397]
CI has failed a few times with the following error on x86_64-apple-2:

```
---- [rustdoc] tests/rustdoc/primitive/no_std.rs stdout ----
thread '[rustdoc] tests/rustdoc/primitive/no_std.rs' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }', src/tools/compiletest/src/runtest.rs:130:43
```

or:

```
---- [rustdoc] src/test/rustdoc/primitive/primitive-generic-impl.rs stdout ----
thread '[rustdoc] src/test/rustdoc/primitive/primitive-generic-impl.rs' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }', src/tools/compiletest/src/runtest.rs:125:43
Some tests failed in compiletest suite=rustdoc mode=rustdoc host=x86_64-apple-darwin target=x86_64-apple-darwin
```

I don't have any immediate theories as to the cause. It is conspicuous that it almost always happens on the same test.

The particular line in question is a call to the standard `create_dir_all`: https://github.com/rust-lang/rust/blob/13b7aa4d7faafbed78d195c27f6868f6bd90c2f8/src/tools/compiletest/src/runtest.rs#L130

I don't see anything particularly unusual in the implementation: [`std::fs::create_dir_all`](https://github.com/rust-lang/rust/blob/13b7aa4d7faafbed78d195c27f6868f6bd90c2f8/library/std/src/fs.rs#L2475-L2500). The impl does a fairly standard libc call to [`mkdir`](https://github.com/rust-lang/rust/blob/13b7aa4d7faafbed78d195c27f6868f6bd90c2f8/library/std/src/sys/unix/fs.rs#L1246-L1248).  The macOS man page doesn't mention EINVAL, and I'm not sure under what circumstances that could happen with `mkdir`.

* 2022-05-26: https://github.com/rust-lang/rust/pull/97327#issuecomment-1138700773
* 2022-12-05: https://github.com/rust-lang/rust/pull/105308#issuecomment-1337806746
* 2022-12-07: https://github.com/rust-lang/rust/pull/104449#issuecomment-1341544420
* 2022-12-09: https://github.com/rust-lang/rust/pull/105448#issuecomment-1344512186
* 2022-12-14: https://github.com/rust-lang/rust/pull/105649#issuecomment-1350754752
* 2022-12-15: https://github.com/rust-lang/rust/pull/104334#issuecomment-1354101832
* 2022-12-16: https://github.com/rust-lang/rust/pull/105717#issuecomment-1355373404
* 2022-12-26: https://github.com/rust-lang/rust/pull/105817#issuecomment-1365266508
* 2022-12-26: https://github.com/rust-lang/rust/pull/106095#issuecomment-1365618661
* 2023-01-18: https://github.com/rust-lang/rust/pull/106503#issuecomment-1387371859
* 2023-01-23: https://github.com/rust-lang/rust/pull/101692#issuecomment-1401092406
* 2023-02-01: https://github.com/rust-lang/rust/pull/107504#issuecomment-1412278383
* 2023-03-13: https://github.com/rust-lang/rust/pull/107376#issuecomment-1465713994
* 2023-03-20: https://github.com/rust-lang/rust/pull/109326#issuecomment-1475120601

**Comment by jyn514** [comment]
the test in question: https://github.com/rust-lang/rust/blob/a01b4cc9f375f1b95fa8195daeea938d3d9c4c34/tests/rustdoc/primitive/no_std.rs#L1-L16

**Comment by jyn514** [comment]
Hmm, it stands out to me that this is one of the only tests where there's a directory with the same name as another test (`tests/rustdoc/primitive.rs`). Maybe mkdir returns an error if the directory already exists, and there's some race condition because the tests are run in parallel?

**Comment by ehuss** [comment]
I sort of figured out what is going on. The following is a reproduction:

```rust
fn main() {
    use std::fs::{create_dir_all, remove_dir_all};
    use std::thread::spawn;
    for _ in 0..10000 {
        let _ = remove_dir_all("rustdoc");
        let t1 = spawn(|| {
            create_dir_all("rustdoc/primitive").unwrap();
            let _ = remove_dir_all("rustdoc/primitive");
            create_dir_all("rustdoc/primitive").unwrap();
        });
        let t2 = spawn(|| {
            create_dir_all("rustdoc/primitive/no_std").unwrap();
            let _ = remove_dir_all("rustdoc/primitive/no_std");
            create_dir_all("rustdoc/primitive/no_std").unwrap();
        });
        t1.join().unwrap();
        t2.join().unwrap();
    }
}
```

Essentially two tests are trying to create and delete the same directory at the same time. For some reason, macOS returns EINVAL in that situation. I don't think this is necessarily a flaw in Rust's `create_dir_all` implementation, more in the realm of "don't do that" (or a bug in macOS itself).

I have opened #109509 to fix this for the tests.
