### ISSUE TITLE
Missed optimization when using `split_first`

### ISSUE THREAD

**Issue by xTachyon** [rust-lang/rust#109328]
Impl 1:
```rust
pub fn f(input: &mut &[u64]) -> Option<u64> {
    match input {
        [] => None,
        [first, rest @ ..] => {
            *input = rest;
            Some(*first)
        }
    }
}
```
Impl 2:
```rust
pub fn f(input: &mut &[u64]) -> Option<u64> {
    let (first, rest) = input.split_first()?;
    *input = rest;
    Some(*first)
}
```
Godbolt: https://godbolt.org/z/aasq15z7a

These functions should be equivalent, but the second function generates one more if than the first one. This also happens when using `.get(0)` and then doing the slicing manually. I expected the impls to generate the same code.

**Comment by JakobDegen** [comment]
Quoting myself on Zulip:
> I've seen this before too. The extra comparison is a null pointer check and is going to be the result of something creating a Option<&T>

**Comment by nikic** [comment]
This is a metadata preservation failure during SimplifyCFG speculation: https://llvm.godbolt.org/z/frs8o853f

Preserving `!nonnull` here used to be illegal, but thanks to https://reviews.llvm.org/D141386 we are allowed to preserve it now. Only need to drop `!noundef`.

**Comment by nikic** [comment]
Upstream patch: https://reviews.llvm.org/D146629

**Comment by nikic** [comment]
Fixed by https://github.com/rust-lang/rust/pull/114048, needs codegen test.
