### ISSUE TITLE
`-Z help` and/or the z-help.stdout test is fragile

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#109391]
The `-Z help` output is interacting in some way with `tests/rustdoc-ui/z-help.stdout` such that the whole thing is fragile.

I am consistently seeing problems where, when I rebase my PR that adds a couple `-Z` flags, a large portion of the output diverges (in terms of actual vs expected), but its *not* on the whole file, its only on the file starting from the entries that follow, e.g.
 
```
    -Z                       instrument-xray=val -- insert function instrument code for XRay-based tracing (default: no)
         Optional extra settings:
         `=always`
         `=never`
         `=ignore-loops`
         `=instruction-threshold=N`
         `=skip-entry`
         `=skip-exit`
         Multiple options can be combined with commas.
    -Z                       keep-hygiene-data=val -- keep hygiene data after analysis (default: no)
```

I would like for us to either figure out a way to make the `-Z help` output itself more stable over time (e.g. by putting limits on the lengths of the names, or not being so clever with the formatting as to force the columns to all be aligned for 100% of the entires), or I would like the z-help.stdout output to be normalized so that it doesn't have to be updated in response to whitespace changes in the output.

**Comment by pnkfelix** [comment]
@jyn514 do you think we should implement this via normalization rules embedded in the test files, e.g. 

```
// normalize-stdout-test: " +" -> " "
```

(or whatever encoding one needs to get one-or-more spaces to normalize to a single space)

Or do you think we should implement this in `compiletest` itself via some means?


My current inclination is to try to encode it into the test file itself.

**Comment by jyn514** [comment]
Yes, I'd prefer the test file itself. I don't think this needs special support from the test infra.
