### ISSUE TITLE
bootstrap: consider lowering / skipping compression when `x.py install`ing artifacts

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#109308]
Right now when doing a local `x.py install`, we first compress the artifacts with max compression ratio, just to immediately unpack them again when installing them to disk.
Making the compression level less aggressive or skipping it altogether can probably save 5-10 minutes on an x.py install.

**Comment by Mark-Simulacrum** [comment]
cc https://github.com/rust-lang/rust/pull/109124

You probably want to use the gzip'd artifacts which are less intensely compressed.

**Comment by jyn514** [comment]
tbh it seems strange that we're compressing these at all - why not put them into an uncompressed .tar archive when using `install`?

**Comment by jyn514** [comment]
or even better, copy them directly from the build directory to the install directory without going through a .tar archive first.

**Comment by onur-ozkan** [comment]
Skipping the compressions and archiving in favor of directly copying the artifacts seems like a reasonable solution for `x install`. But it requires significant changes to how we currently handle `x dist/install`.


I'm planning to do a comprehensive review on bootstrapping from all angles and make a roadmap for future development. To avoid conflicts(e.g, if we have improvement ideas on dist/install modules, implementing this might increase the technical debt which will require more effort from the team), I will postpone this task for now and re-prioritize it once we have organized the plans.
