### ISSUE TITLE
Rust / Swift / Xcode / iCloud interoperability

### ISSUE THREAD

**Issue by markusmoenig** [rust-lang/rust#109381]
The core functionality and file handling of my App is done inside Rust with a Swift / Metal layer on top to handle user input.

All works well except the access to the iCloud / Documents folder, i.e. the container returned by

```swift
var containerUrl: URL? {
  return FileManager.default.url(forUbiquityContainerIdentifier: nil)?.appendingPathComponent("Documents")
}
```

This is done in Swift and I pass the URL to the Rust library.

This container is the only one where a sandboxed Mac / iOS app has read / write access to by default, so it is hard to avoid.

It seems that code in Rust cannot correctly write to the iCloud directory because of symlinks ? If I create a directory in this container in Rust, I cannot access it. If I create a directory from Swift I can.

However as I want to be able to handle file access in my App from Rust in a cross platform way I would love to have a solution for this. 

Sorry if this is not the right place to ask / submit this.

**Comment by joboet** [comment]
`create_dir` will follow symlinks, so I doubt that that is the issue here. How do you convert the URL to a path? Because that seems like an easy place for bugs...

This issue tracker is for tracking bugs and features in the compiler and standard library, so in the future, forums like [URLO](https://users.rust-lang.org/) or [Reddit](https://www.reddit.com/r/rust/) are a better place to ask. But no worries!

**Comment by markusmoenig** [comment]
Oh sorry, ok, thanks for the answer though!

Getting the URL is a bit of a problem because I have to convert it to a C string first (Swift -> Rust). 

So on the Rust side:

```rust
let p_str = unsafe { CStr::from_ptr(p) };
if let Some(project_path) = p_str.to_str().ok() {
  let project_path = PathBuf::from(project_path);
}
```

**Comment by markusmoenig** [comment]
btw; there is a directory created from Rust, however I cannot enter / access it, thats why I had the impression that some metadata was not set correctly.

**Comment by markusmoenig** [comment]
On the Swift side the path is:

```
file:///Users/markusmoenig/Library/Mobile%20Documents/iCloud~Eldiron/Documents/
```

after converting to a C String, and the above code to get it to a PathBuf the path in Rust is:

```
/Users/markusmoenig/Library/Mobile Documents/iCloud~Eldiron/Documents/
```

So I do not think the URL is the problem ?

**Comment by markusmoenig** [comment]
Sorry, seems this had something todo with file permissions on my part....
