### ISSUE TITLE
[cleanup] `Ty::is_ref` and `Ty::is_region_ptr` are identical

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#109372]
`is_ref`:
https://github.com/rust-lang/rust/blob/da7c50c089d5db2d3ebaf227fe075bb1346bfaec/compiler/rustc_middle/src/ty/sty.rs#L1809-L1811

`is_region_ptr`:
https://github.com/rust-lang/rust/blob/da7c50c089d5db2d3ebaf227fe075bb1346bfaec/compiler/rustc_middle/src/ty/sty.rs#L1917-L1919

I don't know which name is better, but there probably shouldn't be two `is_*` helpers doing exactly the same thing.

**Comment by compiler-errors** [comment]
I prefer `is_ref`. We don't really call them "region pointers" anymore.
