### ISSUE TITLE
compiler/rustc_mir_build/src/build ignored by .gitignore

### ISSUE THREAD

**Issue by davidlattimore** [rust-lang/rust#109340]
https://github.com/rust-lang/rust/pull/106440 changed from ignoring `/build/` to ignoring `build/` which means that now if you change files under `compiler/rustc_mir_build/src/build`, you need to use `-f` when running `git add`.

```
# git add compiler/rustc_mir_build/src/build/expr/as_operand.rs
The following paths are ignored by one of your .gitignore files:
compiler/rustc_mir_build/src/build
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"
```

It looks like this is the only directory named `build` that is checked into the repository, so I guess renaming it would be an option if a suitable alternative name could be thought of.

Or perhaps there's some alternative to ignoring `build` throughout the tree? CC @jyn514

**Comment by jyn514** [comment]
fixed in https://github.com/rust-lang/rust/pull/108772
