### ISSUE TITLE
Make the BUG_REPORT_URL configurable for tools

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#109486]
Right now, `install_ice_hook` hard-codes the bug report url to `"https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md"`:
https://github.com/rust-lang/rust/blob/6502613a8199cab4cb68b08c7ddce6f210d8d69c/compiler/rustc_driver_impl/src/lib.rs#L1192

For tools, this is not correct; rustdoc at least wants `T-rustdoc` instead of `T-compiler`, and other tools want different repositories altogether. I'm opening this bug here because it's relevant to all tools, even though the original context was for clippy.

Fixing this seems a little tricky since `DEFAULT_HOOK` can't take an argument and doesn't have access to TyCtxt, but maybe we can solve this with thread-locals or something similar?

cc @rust-lang/rustdoc @rust-lang/clippy @rust-lang/miri @rust-lang/rustfmt
_Originally posted by @ingomancer in https://github.com/rust-lang/rust-clippy/issues/10529

**Comment by flip1995** [comment]
Clippy already sets its own URL, so that is already possible. However Clippy needs to do _a lot_ to do that:

https://github.com/rust-lang/rust/blob/439292bc7913399e406d9bb7e8da0f70c6317c6e/src/tools/clippy/src/driver.rs#L196-L252

Definitely worth improving the situation here.

**Comment by jyn514** [comment]
> Clippy already sets its own URL, so that is already possible. However Clippy needs to do _a lot_ to do that:

Ah hmm, looks like the original problem was a bug in rustfix:
```
after fixes were automatically applied the compiler reported errors within these files:

  * src/main.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust/issues
quoting the full output of this command we'd be very appreciative!
```
I'll open a separate issue there.
```

**Comment by jyn514** [comment]
@rust-lang/miri the way I'm implementing this requires a change to the miri subtree in rust-lang/rust. What URL would you prefer for the bug report, just https://github.com/rust-lang/miri/issues/new ?

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/pull/110989 - looks like rustfmt isn't using `install_ice_hook` today? Happy to add it, but I'll make the PR to the rust-lang/rustfmt repo instead of doing it here.

**Comment by saethlin** [comment]
In my experience, ICEs in Miri are just as often rustc bugs. I don't care if users report them in either place.

**Comment by calebcartwright** [comment]
> #110989 - looks like rustfmt isn't using `install_ice_hook` today? Happy to add it, but I'll make the PR to the rust-lang/rustfmt repo instead of doing it here.

Do you have a ballpark feel for the size of the change? FWIW I'd be okay with making the rustfmt update in tree if it's reasonably small and logically part of a batch of related in-tree changes

**Comment by jyn514** [comment]
about 3 lines of code :) most of which will be the URL itself

**Comment by calebcartwright** [comment]
> about 3 lines of code :) most of which will be the URL itself

sgtm, feel free to go ahead :+1:
