### ISSUE TITLE
#[target_feature] is allowed on #[panic_handler] with target_feature 1.1

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#109411]
This works (but it shouldn't):

```Rust
#![feature(target_feature_11)]
#![no_std]

use core::panic::PanicInfo;

#[panic_handler]
#[target_feature(enable = "avx2")]
fn panic(_info: &PanicInfo) -> ! {
    loop {}
}
```

similar to #108645 , cc #69098 (tracking issue)

@rustbot label T-lang T-compiler C-bug I-unsound F-target_feature_11

**Comment by est31** [comment]
cc @LeSeulArtichaut , author of #108651

Note that this is about the no_std panic handler, not about the `std::panic::set_hook` function. This fails as it should:

```Rust
#![feature(target_feature_11)]

use core::panic::PanicInfo;

#[target_feature(enable = "avx2")]
fn panic(_info: &PanicInfo) {
    loop {}
}

fn main() {
    std::panic::set_hook(Box::new(panic));
}
```

gives

```
error[E0277]: expected a `Fn<(&PanicInfo<'_>,)>` closure, found `for<'a, 'b> fn(&'a PanicInfo<'b>) {panic}`
  --> src/main.rs:11:26
   |
11 |     std::panic::set_hook(Box::new(panic));
   |                          ^^^^^^^^^^^^^^^ expected an `Fn<(&PanicInfo<'_>,)>` closure, found `for<'a, 'b> fn(&'a PanicInfo<'b>) {panic}`
   |
   = help: the trait `for<'a, 'b> Fn<(&'a PanicInfo<'b>,)>` is not implemented for fn item `for<'a, 'b> fn(&'a PanicInfo<'b>) {panic}`
   = note: `#[target_feature]` functions do not implement the `Fn` traits
   = note: required for the cast from `for<'a, 'b> fn(&'a PanicInfo<'b>) {panic}` to the object type `dyn for<'a, 'b> Fn(&'a PanicInfo<'b>) + Send + Sync`
```

**Comment by Nilstrieb** [comment]
ugh we really need a way to make sure that every single "this is called by rust" function gets a check...
I assume that these functions can't be unsafe, so I guess those checks are a food way to start looking and make sure to deduplicate the logic there?

**Comment by est31** [comment]
Yeah sadly we do need to make sure, not just for the constructs that we have now but also it needs to be kept in mind for the future constructs we add or stabilize.

A lot thankfully goes through either the trait system (operators or the GlobalAlloc trait used by `#[global_alloc]`) or function pointers (alloc error hook, std panic hook). Functions that you can make callable solely by setting an attribute, those are rare.

The best list of lang items I could find was in the [unstable book](https://doc.rust-lang.org/nightly/unstable-book/language-features/lang-items.html), so that would be a great start for such an exhaustive search. Thankfully most of them are unstable, but still it needs to be addressed for each of them before stabilization (if that is a target).

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23109411.20.23.5Btarget_feature.5D.20is.20allowed.20on.20.23.5Bpanic_handler.5D.20wi.E2.80.A6)).

@rustbot label -I-prioritize +P-medium
