### ISSUE TITLE
trait conflicting implement 

### ISSUE THREAD

**Issue by joey-chan** [rust-lang/rust#109518]
My code is :
```
pub trait TestTrait<T> {}

impl TestTrait<&Series> for DataFrame {}

impl <T> TestTrait<T> for DataFrame
where 
    T: NumericNative,
{}
```
here is error:
```
error[E0119]: conflicting implementations of trait `core::traits::TestTrait<&polars::prelude::Series>` for type `polars::prelude::DataFrame`
   --> src/core/traits.rs:119:1
    |
117 | impl TestTrait<&Series> for DataFrame {}
    | ------------------------------------- first implementation here
118 |
119 | impl <T> TestTrait<T> for DataFrame
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `polars::prelude::DataFrame`
```
while there is a similar implement in polars' Series, why My code can't work.
here is polars Series source code:
![WechatIMG211](https://user-images.githubusercontent.com/5937892/227138200-35deeca4-2164-4314-a078-3c89f509c9cc.jpeg)

**Comment by Nilstrieb** [comment]
You cannot implement foreign traits for foreign types.
See https://doc.rust-lang.org/reference/items/implementations.html#trait-implementation-coherence

**Comment by joey-chan** [comment]
> You cannot implement foreign traits for foreign types.
> See https://doc.rust-lang.org/reference/items/implementations.html#trait-implementation-coherence

i don't think foreign types cause the error, i just tried these code, still conflict
```
struct a;

pub trait TestTrait<T> {}

impl TestTrait<&Series> for a {}

impl <T> TestTrait<T> for a
where 
    T: NumericNative,
{}
```

**Comment by Nilstrieb** [comment]
Ah, here it's a little more complicated. Theoretically, polars could add `impl NumericNative for &Series`. If they did that, your impls would now overlap, which is not allowed. So to protect against future changes like this, your program doesn't compile.

**Comment by joey-chan** [comment]
> Ah, here it's a little more complicated. Theoretically, polars could add `impl NumericNative for &Series`. If they did that, your impls would now overlap, which is not allowed. So to protect against future changes like this, your program doesn't compile.

but impl for struct A which is define by me, didn't work yet. it's no matter with the polars.

**Comment by fee1-dead** [comment]
Closing. @joey-chan: see [this](https://www.rust-lang.org/community) for places where your questions may be better answered (for example, the Rust user forum)
