### ISSUE TITLE
Rust should suggest single quotes when expecting `char`

### ISSUE THREAD

**Issue by SergioB-dev** [rust-lang/rust#109586]
### Code

```Rust
fn convert_c_to_str(c: char) -> &str {
    match c {
        "A" => "T",
        "C" => "G",
        "T" => "A",
        "G" => "C",
        _ => c,
    }
}
```

### Current output

```Shell
error[E0308]: mismatched types
 --> src/main.rs:4:9
  |
3 |     match c {
  |           - this expression has type `char`
4 |         "A" => "T",
  |         ^^^ expected `char`, found `&str`

error[E0308]: mismatched types
 --> src/main.rs:5:9
  |
3 |     match c {
  |           - this expression has type `char`
4 |         "A" => "T",
5 |         "C" => "G",
  |         ^^^ expected `char`, found `&str`

error[E0308]: mismatched types
 --> src/main.rs:6:9
  |
3 |     match c {
  |           - this expression has type `char`
...
6 |         "T" => "A",
  |         ^^^ expected `char`, found `&str`

error[E0308]: mismatched types
 --> src/main.rs:7:9
  |
3 |     match c {
  |           - this expression has type `char`
...
```

### Desired output

```Shell
...

"Please use single quotes ('_') to generate chars"

```

### Rationale and extra context

For beginners the error message could be a lot simpler. Sometimes they just want to make a char and using single quotes instead of double quotes is not terribly obvious.

**Comment by uninumber** [comment]
> is not terribly obvious

**_Char_** is one of the _fundamental_ data types in programming languages, and as far as I know, all "mainstream" languages use a single quote to denote a character. I think the mismatched error in this situation is pretty obvious and can be seen more as a typo than a misunderstanding.

Alternatively, you can use `--explain` where more information will be provided to you. And I think `--explain` really needs a **_push._**

**Comment by clubby789** [comment]
>  and as far as I know, all "mainstream" languages use a single quote to denote a character
Both JavaScript and Python have no character type, with `"` and `'` being roughly interchangeable, so this is likely to be a common mistake for newcomers from other languages. Either way, whether it's a typo or a misunderstanding, having an IDE-applicable suggestion will help.
