### ISSUE TITLE
Use of `Self::SOME_ASSOC_CONST` inside a function-local `const` calls `Self` a "generic parameter from outer function"

### ISSUE THREAD

**Issue by thomcc** [rust-lang/rust#109596]
### Code

Playground: <https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=01d9dd114b740509a3538ce91aa2bf6a>.
```Rust
#[repr(u8)]
pub enum Foo { A, B, C }

impl Foo {
    pub const COUNT: usize = 3;
    pub fn blah() {
        const _: () = assert!(Self::COUNT < (u8::MAX as usize));
    }
}
```

A slightly more realistic (but also slightly larger) example is here: <https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=01d9dd114b740509a3538ce91aa2bf6a> (this is more or less code that I tried to emit from a macro).

### Current output

```Shell
error[E0401]: can't use generic parameters from outer function
 --> src/lib.rs:7:31
  |
4 | impl Foo {
  | ---- `Self` type implicitly declared here, by this `impl`
...
7 |         const _: () = assert!(Self::COUNT < (u8::MAX as usize));
  |                               ^^^^^^^^^^^
  |                               |
  |                               use of generic parameter from outer function
  |                               use a type here instead

For more information about this error, try `rustc --explain E0401`.
error: could not compile `playground` due to previous error
```

### Desired output

```Shell
error[...]: can't use `Self` type inside function-local `const`.
```

Or something. I don't have strong feelings.

It should probably suggest replacing `Self::COUNT` with `Foo::COUNT` though, since that's enough to fix this.

### Rationale and extra context

`Self` here is not a generic parameter from the outer function (it's the implementing type from the `impl` block, although I'm not really sure that's a particularly clear way to refer to it either). Either way, the current message is wrong and misleading.

### Anything else?

Happens on nightly (`rustc 1.70.0-nightly (8be3c2bda 2023-03-24)`) and on stable (1.68.1).

**Comment by thomcc** [comment]
Alternatively, perhaps this should work. `Self::SOME_ASSOC_CONST` is usable from other associated consts in the impl block, for example. I don't have strong feelings, though.

**Comment by compiler-errors** [comment]
> Alternatively, perhaps this should work. Self::SOME_ASSOC_CONST is usable from other associated consts at impl block level, for example. I don't have strong feelings, though.

That would require desugaring the const item into an associated const, which seems like a lot of complexity.

**Comment by thomcc** [comment]
Yeah, that seems like a lang decision anyway. And it's mostly irrelevant if the error message is improved (esp. to suggest a fix in the cases it's just "change Self to the type name").

**Comment by scottmcm** [comment]
I think it's expected that this is an error -- if the person wants to use `Self`, it needs to be `const { … }` instead of a `const` *item*.

**Comment by Ved-s** [comment]
got similar weird error today
```rust
struct Test {}

impl Test {
    pub fn static_fn() {}

    pub fn test() {
        fn nested_fn() {
            Self::static_fn();
        }
        nested_fn();
    }
}
```

```
error[E0401]: can't use generic parameters from outer function
   --> src/main.rs:985:13
    |
980 | impl Test {
    | ---- `Self` type implicitly declared here, by this `impl`
...
985 |             Self::static_fn();
    |             ^^^^^^^^^^^^^^^
    |             |
    |             use of generic parameter from outer function
    |             use a type here instead
```

I don't think `Self` is a generic parameter, should be like `use of Self from outer function`
