### ISSUE TITLE
Range<NonZeroU64> is not iterable

### ISSUE THREAD

**Issue by uaeio** [rust-lang/rust#109569]
Why isnt `Range<NonZeroU64>` iterable?

**Comment by the8472** [comment]
```rust
impl<A> Iterator for Range<A>where
    A: Step,
```

And `Step` is only implemented for this list: https://doc.rust-lang.org/std/iter/trait.Step.html#implementors

**Comment by cuviper** [comment]
There are a couple proposals for expanding `Step`:
https://github.com/rust-lang/libs-team/issues/130
https://github.com/rust-lang/libs-team/issues/189

**Comment by scottmcm** [comment]
I'll close this in favour of <https://github.com/rust-lang/libs-team/issues/130>.
