### ISSUE TITLE
Possible missing type inference in `iterator_try_reduce`

### ISSUE THREAD

**Issue by simonvarey** [rust-lang/rust#109578]
I tried this code:

```rust
#![feature(iterator_try_reduce)]

fn fallible(check: usize) -> Result<usize, &'static str> {
    if check > 10 {
        Err("Too large")
    } else {
        Ok(check)
    }
}

fn repro() -> Option<usize> {
    [1, 2, 3]
        .into_iter()
        .try_reduce(|accum, item| {
            let num = fallible(item)?;
            Ok(accum + num)
        })
        .unwrap()
}

fn main() {
    let num = repro().unwrap();
    println!("{num:?}");
}
```

I expected to see this happen: The error type `E` for the `try_reduce` method should be inferable to be `&'static str`.

Instead, this happened: error[[E0282]](https://doc.rust-lang.org/nightly/error_codes/E0282.html): type annotations needed: cannot infer type of the type parameter `E` declared on the enum `Result`

I'm not sure if this is a bug, as maybe there is a good reason why the type cannot be inferred. However, given the `?` will return a `Err(&'static str)`, no other type could be `E`, so in principle it should be possible to infer it. 

### Meta

`rustc --version --verbose`:
```
rustc 1.70.0-nightly (8be3c2bda 2023-03-24)
binary: rustc
commit-hash: 8be3c2bda6b683f87b24714ba595e8b04faef54c
commit-date: 2023-03-24
host: x86_64-pc-windows-msvc
release: 1.70.0-nightly
LLVM version: 15.0.7
```

**Comment by compiler-errors** [comment]
The `?` operator does something like:

```
/* `x?` turns into */
match x {
  Ok(ok) => ok,
  Err(err) => return Err(x.into()),
}
```

The problem here is that the `?` operator does not constrain the error type returned by `try_reduce` to *be* `&str`, but instead just requires that whatever the error type of the closure is implements `From<&str>`.

For example:

```rust
#![feature(iterator_try_reduce)]

fn fallible(check: usize) -> Result<usize, &'static str> {
    if check > 10 {
        Err("Too large")
    } else {
        Ok(check)
    }
}

fn repro() -> Option<usize> {
    [1, 2, 3]
        .into_iter()
        .try_reduce(|accum, item| {
            let num = fallible(item)?;
            Ok::<_, MyErr>(accum + num)
        })
        .unwrap()
}

#[derive(Debug)]
struct MyErr;

impl From<&str> for MyErr {
    fn from(_: &str) -> MyErr { MyErr }
}

fn main() {
    let num = repro().unwrap();
    println!("{num:?}");
}
```

Note the turbofish on the `Ok` that constrains the error type of the `try_reduce` to `MyErr`.

**Comment by simonvarey** [comment]
I understand now. I had forgot about that `?` does conversions. Thanks for the clarification @compiler-errors .
