### ISSUE TITLE
The constant core::num::ASCII_CASE_MASK is wrongly described in the doc comment.

### ISSUE THREAD

**Issue by papok** [rust-lang/rust#109508]
https://github.com/rust-lang/rust/blob/a266f11990d9544ee408e213e1eec8cc9eb032b7/library/core/src/num/mod.rs#L416-L419

Shouldn't the comment line read : /// If 6th bit set ascii is **lower** case. ?

**Comment by jyn514** [comment]
Why?

**Comment by papok** [comment]
Without further explanation I understand "set" for a bit to be set to 1. In ASCII, if the 6th bit is set to 1 then the letter coded (if the character coded is a letter) is lowercase.
