### ISSUE TITLE
Run tests for dist builds

### ISSUE THREAD

**Issue by Nilstrieb** [rust-lang/rust#109535]
We currently run tests for stage 1 and stage 2 builds (I think). So these are guaranteed to pass on tier 1 targets.

But on some targets like x86_64-unknown-linux-gnu we don't ship stage 2 builds, we ship special PGO/BOLT builds that have more optimizations. As we have recently found out in #109067 and #108978, these extra optimizations can lead to miscompilations. We currently have no way to detect this except for users on nightly (or stable as in this case) to see weird behavior. That's very bad.

To do our best to prevent dist miscompilations from shipping, we should find a way to run tests for dist toolchains on targets where extra optimizations are applied.

The dist-x86_64-linux builder is currently one of the slowest builders and running tests in there takes extra time, which would slow down our CI. Ideally we'd find a way to run these tests without impacting CI performance.

**Comment by jyn514** [comment]
> We currently run tests for stage 1 and stage 2 builds (I think)

Nope, stage 2 only.

cc https://github.com/rust-lang/rust/pull/99141, https://github.com/rust-lang/rust/pull/73964/commits/7768eaa0503e7e98eb2404fa4664297a84d72d38

**Comment by Kobzol** [comment]
I think that this can be now closed, because we do run a large part of the test suite on dist builders that perform special optimizations (PGO/LTO/BOLT): https://github.com/rust-lang/rust/pull/111495

**Comment by jyn514** [comment]
sounds good - we can open more specific issues as necessary. thanks for working on this!
