### ISSUE TITLE
member constraints leak through InferCtxt snapshots

### ISSUE THREAD

**Issue by aliemjay** [rust-lang/rust#109654]
`RegionConstraintCollector::member_constraint` doesn't register new constraints in the undo log.
https://github.com/rust-lang/rust/blob/1d5820784e442ec7e89474e2fa305440253ffaeb/compiler/rustc_infer/src/infer/region_constraints/mod.rs#L533-L554

**Comment by Enselic** [comment]
Triage: Can you please elaborate a bit on what the consequences of this is, and what problems it causes for users? A minimal reproducer would also be very nice to have.
