### ISSUE TITLE
`rust.codegen-backends` interacts confusingly with paths

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#109610]
I tried this code:
```
x build rustc_codegen_cranelift
```

I expected this to happen: Bootstrap builds cranelift, since I named it explicitly.
Instead, this happened: Nothing, since I didn't have cranelift configured in `codegen-backends`: https://github.com/rust-lang/rust/blob/ce6adccdade1ec29bff031c296c5ae0d80ab0446/src/bootstrap/compile.rs#L998-L1009

At a minimum, I would expect this to give an error or warning that I need to configure codegen-backends. It would be even nicer if we could treat `codegen-backends` as only controlling the defaults, instead of as a hard-off switch, like how `rust.compiler-docs` works. That should be possible to do by looking at the `run.paths` we're passed.

cc @bjorn3

**Comment by bjorn3** [comment]
The first element in codegen-backends is used as default backend. In addition even if the CodegenBackend step were to directly use the passed in paths, assembling the toolchain did still only add the backends in codegen-backends to the sysroot. Having path specifiers for one step affect another step doesn't feel right. For check builds I do agree this is an improvement. Although I personally actually use this behavior to have `./x.py check compiler/rustc_codegen_cranelift` build all backends, not just cranelift (by enabling all in codegen-backends) It did be nice to have a replacement for this. In addition for `./x.py build` at the very least a warning makes sense.

**Comment by jyn514** [comment]
> Having path specifiers for one step affect another step doesn't feel right.

Does it make sense to separate cg_clif and cg_gcc into different steps in that case?

cc @antoyo

**Comment by bjorn3** [comment]
That doesn't have any effect on if specifying a backend as path will add it to the sysroot.
