### ISSUE TITLE
Confusing error when trying to call non-function

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#10969]
```
render/man.rs:62:28: 62:43 error: expected function but found `&'static str`
render/man.rs:62                     let s = shortty(&item);
                                             ^~~~~~~~~~~~~~~
```

It should say something like 

```
error: cannot call non-callable `shortty`; expected function but found `T`
...
note: `shortty` declared here
```

The big thing is the pointer to the thing it thinks you're trying to call!

**Comment by frewsxcv** [comment]
Triage: The output hasn't changed much since when this was first reported.

```fish
/tmp $ echo 'fn main() { let shortty = "test"; shortty(); }' > hello.rs
/tmp $ rustc hello.rs
hello.rs:1:35: 1:44 error: expected function, found `&str`
hello.rs:1 fn main() { let shortty = "test"; shortty(); }
                                             ^~~~~~~~~
error: aborting due to previous error
```

Personally, I don't think this error message is that confusing.

> The big thing is the pointer to the thing it thinks you're trying to call!

@cmr What do you mean by this?

**Comment by jdm** [comment]
@frewsxcv @cmr means the extra note he suggested in the original report "note: `foo` declared here".

**Comment by Manishearth** [comment]
Willing to mentor this.

Relevant code: https://github.com/rust-lang/rust/blob/master/src/librustc_typeck/check/callee.rs#L231

You need to find the defid of the call expression (use `def_map` in `fcx.tcx()`), and do something similar as done [here](https://github.com/rust-lang/rust/commit/d8062a9317a3113a9d0447895a2d12899072a6c8#diff-aeb0880081a991f34aef2ab889e1fb7aR288) to point out where something was imported or defined. It might be useful to refactor that out in a `note_did_import` utility function that takes two strings and a def id or something and reports on the import or definition, whichever is local.

**Comment by Detegr** [comment]
This looks like a bug I could be able to fix, so I'll try getting something done this weekend.

**Comment by Manishearth** [comment]
Sure!

**Comment by Manishearth** [comment]
@Detegr Btw, http://manishearth.github.io/rust-internals-docs/rustc/ is a searchable set of online docs for the internals.

http://manishearth.github.io/rust-internals-docs/rustc/middle/ty/struct.ctxt.html , specifically the DefMap is what you need here.

**Comment by Manishearth** [comment]
@Detegr ignore the advice about refactoring it. We should just note that it is a local variable if it is indeed local. I don't think there's an easy way of figuring out where something was imported from.

**Comment by Detegr** [comment]
@Manishearth All right. If there is no need for refactoring, I think I have it working correctly now. I'll do a PR later today. Thanks for all the tips, they helped a lot.

**Comment by Detegr** [comment]
Turned out there are problems with some tests, I'll need to figure those out first.

**Comment by Manishearth** [comment]
No problem. Feel free to make a preliminary PR so I can start reviewing.
