### ISSUE TITLE
[aarch64] musl target failed to link rust app

### ISSUE THREAD

**Issue by Ludea** [rust-lang/rust#109699]
I have a rust app which use postgresql, mysql and sqlite lib.
Target is `aarch64-unknow-linux-musl`. 
I build successfully from alpine linux. 
When starting my app, I get `not found`
lld myapp gave some linking issue with these lib. So I have to install libs.
I restart my app, still get `not found`
ldd gave :
```
/lib/ld-linux-aarch64.so.1 (0x7fa2006000)
        libsqlite3.so.0 => /usr/lib/libsqlite3.so.0 (0x7fa1ef1000)
        libpq.so.5 => /usr/lib/libpq.so.5 (0x7fa1e90000)
        libmariadb.so.3 => /usr/lib/libmariadb.so.3 (0x7fa1e2c000)
        libc.musl-aarch64.so.1 => /lib/ld-linux-aarch64.so.1 (0x7fa2006000)
        libssl.so.3 => /lib/libssl.so.3 (0x7fa1d88000)
        libcrypto.so.3 => /lib/libcrypto.so.3 (0x7fa1a02000)
        libz.so.1 => /lib/libz.so.1 (0x7fa19d1000) 
```

I expected to see this happen: *explanation*
app working

Instead, this happened: *explanation*
app not starting

With `x86_64-unknow-linux-musl` my app start on alpine. Issue happen only on aarch64 platform.
I try both cross compil and native build from an arm64 device, still get issue

### Meta

`rustc --version --verbose`:
```
1.68.1
```

</p>
</details>

**Comment by bjorn3** [comment]
Are you using the alpine linux version of rustc or the official version? If the later you have to pass `-Ctarget-feature=-crt-static` to rustc using eg the `RUSTFLAGS` env var. `+crt-static` is incompatible with depending on dynamic libraries.

**Comment by Ludea** [comment]
I use rust:alpine3.17 docker image https://github.com/rust-lang/docker-rust

**Comment by bjorn3** [comment]
That one uses the official rustc build. So you will have to pass `-Ctarget-feature=-crt-static` to rustc.

**Comment by Ludea** [comment]
If I do that, I get
```
error: cannot produce proc-macro for `async-stream-impl v0.3.3` as the target `aarch64-unknown-linux-musl` does not support these crate types
```

**Comment by Ludea** [comment]
> Maybe try with `--target x86_64-unknown-linux-musl` added to the cargo commandline? This causes `RUSTFLAGS` to be ignored with building build scripts and proc macros.

I add  `--target aarch64-unknown-linux-musl` instead of x86_64. Building is successfull. But still get linking issue.

My full command: `CARGO_NET_GIT_FETCH_WITH_CLI=true RUSTFLAGS='-C target-feature=+crt-static' cargo build --release --verbose --target aarch64-unknown-linux-musl `

**Comment by Ludea** [comment]
> And you are running it inside alpine linux or another musl based linux distro?

I copy and run my rust app into alpine:3.17

**Comment by bjorn3** [comment]
It only says "not found" and gives no other information?

**Comment by Ludea** [comment]
> It only says "not found" and gives no other information?

right.

It's happen only on aarch64 host, x86_64 works.

I can provide a [repro ](https://hub.docker.com/layers/ludea/lucle/latest/images/sha256-991b663a12aa545c906741ea35a08be3a38641a2712ebc2025e3d634d27cb3b3?context=explore)docker image

**Comment by bjorn3** [comment]
Assuming that https://github.com/Ludea/lucle/blob/main/Dockerfile is the dockerfile you are using, I don't see sqlite, and the client libs for postgresql and mariadb getting installed in the final image. I have no clue how it did work on x86_64 if that is the issue. If that isn't the issue, I'm out of ideas. And I don't have an aarch64 system I can run docker on and qemu aarch64 emulation is way too slow, so I can't directly debug it unfortunately.

**Comment by Ludea** [comment]
Yes, it's this dockerfle

I don't install it because x86_64 image work without them. (my app works)

I had to install manually these libs into aarch64 image

**Comment by Ludea** [comment]
FYI, get another rust app build with same workflow / toolchain, and work on both hosts.

So I think issue come from either sqlite, mysql or posgresql lib.

**Comment by Ludea** [comment]
`cargo build --release --verbose ` from alpine aarch64 alpine image link to glibc instead of musl

**Comment by Ludea** [comment]
Fixed, it was a docker issue
