### ISSUE TITLE
stable Rustdoc Book suggests missing_doc_code_examples, which is unstable

### ISSUE THREAD

**Issue by peter-kehl** [rust-lang/rust#109601]
### Location

`src/doc/rustdoc/src/write-documentation/what-to-include.md` (https://doc.rust-lang.org/rustdoc/write-documentation/what-to-include.html)

### Summary

Currently, `missing_doc_code_examples` lint is implemented on `nightly` and gated with #![feature(rustdoc_missing_doc_code_examples)]. However, the lint `#![deny(missing_doc_code_examples)]` is suggested in the `stable` version of Rustdoc Book, too - but without any mention that it's a `nightly` feature. Is it likely to get stabilized soon (so Rustdoc Book could stay as is)?

Otherwise, shouldn't we document that (and create an issue to remove such a note from the Rustdoc Book once the feature becomes `stable`)? If so, I'm happy to create an issue and a PR.

Or, should this be pulled out of stable Rustdoc Book until the feature is stabilized? Is there any recommended/de-facto practice for this?
(This issue is a follow up to #109592.)

**Comment by jyn514** [comment]
`missing_doc_code_examples` in that section seems strange to me, I don't see how it relates to the rest of the section. It looks like this was present from the first commit where the "write documentation" chapter was added: https://github.com/rust-lang/rust/commit/881820aa062cb75ee02ec2d2a89a5a89074c1bd0#diff-e271d69d7408013ad53dff6ceece67373bc99f2c514cb4ca219a8f20a48e9ebc
I would personally be ok with removing it.

**Comment by camelid** [comment]
Removing the mention of `missing_doc_code_examples` makes sense to me as well. Note that it already has documentation (that notes that it's unstable) on the lints page: https://doc.rust-lang.org/rustdoc/lints.html#missing_doc_code_examples
