### ISSUE TITLE
objc2 fails to build on latets nightly

### ISSUE THREAD

**Issue by kchibisov** [rust-lang/rust#109632]
Our CI in winit started breaking on nightly recently due to inability of recent rustc nightly to build the https://github.com/madsmtm/objc2 crate, in particular you can look into https://github.com/madsmtm/objc2/issues/432 issue.

### Error

The error we get is:

```
 error[E0277]: `<<I as IvarType>::Type as InnerIvarType>::Output` is not an iterator
   --> /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.3.0-beta.3.patch-leaks.2/src/declare/ivar_forwarding_impls.rs:165:5
    |
165 |     fn nth(&mut self, n: usize) -> Option<<<Self as Deref>::Target as Iterator>::Item> {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `<<I as IvarType>::Type as InnerIvarType>::Output` is not an iterator
    |
    = help: the trait `Iterator` is not implemented for `<<I as IvarType>::Type as InnerIvarType>::Output`
note: required for `ivar::Ivar<I>` to implement `Iterator`
   --> /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.3.0-beta.3.patch-leaks.2/src/declare/ivar_forwarding_impls.rs:154:19
    |
154 | impl<I: IvarType> Iterator for Ivar<I>
    |                   ^^^^^^^^     ^^^^^^^
155 | where
156 |     <Self as Deref>::Target: Iterator,
    |                              -------- unsatisfied trait bound introduced here
help: consider further restricting the associated type
    |
165 |     fn nth(&mut self, n: usize) -> Option<<<Self as Deref>::Target as Iterator>::Item> where <<I as IvarType>::Type as InnerIvarType>::Output: Iterator {
    |                                                                                        ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

error[E0277]: `<<I as IvarType>::Type as InnerIvarType>::Output` is not an iterator
   --> /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.3.0-beta.3.patch-leaks.2/src/declare/ivar_forwarding_impls.rs:165:5
    |
165 |     fn nth(&mut self, n: usize) -> Option<<<Self as Deref>::Target as Iterator>::Item> {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `<<I as IvarType>::Type as InnerIvarType>::Output` is not an iterator
    |
    = help: the trait `Iterator` is not implemented for `<<I as IvarType>::Type as InnerIvarType>::Output`
help: consider further restricting the associated type
    |
165 |     fn nth(&mut self, n: usize) -> Option<<<Self as Deref>::Target as Iterator>::Item> where <<I as IvarType>::Type as InnerIvarType>::Output: Iterator {
    |                                                                                        ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

I expected to see this happen: it should build.

Instead, this happened: it doesn't build, see above.

### Version it worked on

It most recently worked on: rust version 1.69.0-nightly (31f858d9a 2023-02-28)

### Version with regression

`rustc --version --verbose`:
```
rust version 1.70.0-nightly (da7c50c08 2023-03-19)
```

**Comment by madsmtm** [comment]
Note in particular that it's only the overridden `fn nth` (which we override simply because `Box` does) that fails to build, and only with a bit of a complicated trait bound.

A smaller reproducer can be found in [this playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=fbdbce6d5d45155cc56dd80013efe817).

If you either remove the `fn nth` implementation, or change the `<Self as Deref>::Target` with the type it refers to, `<I::Type as InnerIvarType>::Output`, the example now builds.

**Comment by lukas-code** [comment]
searched nightlies: from nightly-2023-03-18 to nightly-2023-03-26
regressed nightly: nightly-2023-03-20
searched commit range: https://github.com/rust-lang/rust/compare/4a04d086cac54a41517d5657b59d5fe2caca2d71...da7c50c089d5db2d3ebaf227fe075bb1346bfaec
regressed commit: https://github.com/rust-lang/rust/commit/8826b68c623619161d499f8138614a0edd741bc8

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.5</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc -- check 
```
</details>

Regression in https://github.com/rust-lang/rust/pull/104100.

Looks like this is caused by this bound: https://github.com/rust-lang/rust/blob/89c2e3d3d75486e52473de3ae38f0ca6efeffef2/library/core/src/iter/traits/iterator.rs#L393

@rustbot label -E-needs-bisection

**Comment by fee1-dead** [comment]
It's not supposed to regress normal code, but if it does it is a bug. I'm going to look into this when I have time.

**Comment by lukas-code** [comment]
This seems to be a general limitation of the old trait solver and unrelated to `Destruct` specifically.

But it works with the new trait solver (`RUSTFLAGS=-Ztrait-solver=next`), so maybe we should just hold back on const iterators until the new trait solver becomes stable.

[demo](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ec52bffeeedad2f8c69c6f43a2ac78b9)

```rust
pub struct GenericType<T>(T);

pub trait Trait1 {
    type Assoc1;
}

trait Trait2 {
    type Assoc2;
}

impl<T: Trait1> Trait2 for GenericType<T> {
    type Assoc2 = T::Assoc1;
}

trait Anything {}

trait MyIterator {
    type MyItem;
    fn my_nth() where Self::MyItem: Anything;
}

impl<T: Trait1> MyIterator for GenericType<T>
where
    <Self as Trait2>::Assoc2: MyIterator,
    // <T as Trait1>::Assoc1: MyIterator, // stop-gap fix
{
    type MyItem = <<Self as Trait2>::Assoc2 as MyIterator>::MyItem;
    fn my_nth() {}
}
```

```text
Compiling playground v0.0.1 (/playground)
error[E0277]: the trait bound `<T as Trait1>::Assoc1: MyIterator` is not satisfied
  --> src/lib.rs:28:5
   |
28 |     fn my_nth() {}
   |     ^^^^^^^^^^^ the trait `MyIterator` is not implemented for `<T as Trait1>::Assoc1`
   |
note: required for `GenericType<T>` to implement `MyIterator`
  --> src/lib.rs:22:17
   |
22 | impl<T: Trait1> MyIterator for GenericType<T>
   |                 ^^^^^^^^^^     ^^^^^^^^^^^^^^
23 | where
24 |     <Self as Trait2>::Assoc2: MyIterator,
   |                               ---------- unsatisfied trait bound introduced here
help: consider further restricting the associated type
   |
28 |     fn my_nth() where <T as Trait1>::Assoc1: MyIterator {}
   |                 +++++++++++++++++++++++++++++++++++++++

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground` due to previous error
```

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23109632.20objc2.20fails.20to.20build.20on.20latets.20nightly)).

@rustbot label -I-prioritize +P-high +T-compiler
