### ISSUE TITLE
error: could not compile `syn` (lib)

### ISSUE THREAD

**Issue by RafaBlockDev** [rust-lang/rust#109715]
### Code

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by compiler-errors** [comment]
Do you mind filling out the sections above?

**Comment by compiler-errors** [comment]
Closing this. Feel free to file another issue with all the sections filed out!
