### ISSUE TITLE
regression: mismatched types

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#109747]
https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/proc-macro2-test-0.0.1/log.txt

```
[INFO] [stdout] error: mismatched function-like proc macro signature
[INFO] [stdout]  --> src/lib.rs:7:37
[INFO] [stdout]   |
[INFO] [stdout] 7 | pub fn demo(tokens: TokenStream) -> TokenStream {
[INFO] [stdout]   |                                     ^^^^^^^^^^^ found TokenStream, expected type `proc_macro::TokenStream`
[INFO] [stdout]   |
[INFO] [stdout]   = note: function-like proc macros must have a signature of `fn(TokenStream) -> TokenStream`
[INFO] [stdout] 
[INFO] [stdout] 
[INFO] [stderr] error: could not compile `proc-macro2-test` due to 3 previous errors
[INFO] [stdout] error: mismatched function-like proc macro signature
[INFO] [stdout]  --> src/lib.rs:7:21
[INFO] [stdout]   |
[INFO] [stdout] 7 | pub fn demo(tokens: TokenStream) -> TokenStream {
[INFO] [stdout]   |                     ^^^^^^^^^^^ found TokenStream, expected type `proc_macro::TokenStream`
[INFO] [stdout]   |
[INFO] [stdout]   = note: function-like proc macros must have a signature of `fn(TokenStream) -> TokenStream`
```

This code seems to have compiled fine previously -- even if this ends up not being a regression, we probably ought to call it a diagnostics bug, since the found/expected type message is pretty poor.

**Comment by compiler-errors** [comment]
I cannot reproduce this :question: Crater sometimes chokes on proc_macro2 though, right?

Also, I messed with this diagnostic recently in #109136 (though that's on nightly currently).

**Comment by Mark-Simulacrum** [comment]
Hm, interesting. It's reproduced in crater ~3 times at least, but if we can't reproduce probably fine. If there was some problem here I'd expect far more crates to be broken than just this one.

**Comment by Enselic** [comment]
Triage: I can't imagine we will ever take action here, so let's close as not reproducible. We would likely have learned by know if this problem was genuine, if it was.
