### ISSUE TITLE
Need regression test for wasm linker override=clang (108910)

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#109728]
As noted in https://github.com/rust-lang/rust/pull/108996#issuecomment-1488842234, I don't want to delay the fix further on the CI issues I was having with my regression test.

This issue is just tracking a (hopefully simple?) work item to make such a regression test, e.g. using the one from https://github.com/rust-lang/rust/pull/108996/commits/568b7221402b348fe65fd87ade2e1174b356bd74 after figuring out how to make the CI happy (see error CI posted here: https://github.com/rust-lang/rust/pull/108996#issuecomment-1473153690 )

**Comment by agaraman0** [comment]
@pnkfelix  i would like to pick this

**Comment by jyn514** [comment]
@agaraman0 go for it :) you can use `@rustbot claim` to assign yourself. See https://rustc-dev-guide.rust-lang.org/getting-started.html for more instructions.

**Comment by ndrewxie** [comment]
Full disclaimer, I'm not an experienced contributor to open source, nor will I pretend to be, so take the below with a grain of salt:

If we're just checking to see if the `link-arg=-nostartfiles` is being emitted, would it suffice to just capture the link flags (e.g. using `RUSTC_LOG=rustc_codegen_ssa::back::link=info`) and check if this option is present? That way, even if clang isn't present in the CI environment, the functionality can still be verified

Although it does seem strange that clang isn't available... Your wording of "make the CI happy" seems to imply that there's a workaround of sorts (perhaps annoying to find) - if so, could you provide a few pointers?

**Comment by jyn514** [comment]
@ndrewxie feel free to install clang on any of the CI builders, look for `apt install` in `src/ci` for examples.

**Comment by ndrewxie** [comment]
@jyn514 Oh dang I didn't expect to have the perms to do that in a CI environment. Thank you! I'll test that approach and add a test :)

**Comment by ndrewxie** [comment]
> @ndrewxie feel free to install clang on any of the CI builders, look for `apt install` in `src/ci` for examples.

Hmm, there appears to already be a script that installs clang, located in /src/ci/scripts/install-clang.sh. However, it chooses to not install it under the assumption that every system would already have clang installed and configured properly.

> Note that we don't install clang on Linux since its compiler story is just so different. Each container has its own toolchain configured appropriately already.

Would it be safe for me to apt install it anyways, or is there a risk that clang acquired from the package manager would be configured improperly and mess something up?

**Comment by jyn514** [comment]
As long as the new test passes and no other test regresses, it's probably ok. We don't have a hard dependency on the version of clang like we do for LLVM and the bootstrap compiler.

**Comment by InfRandomness** [comment]
Is this being worked on ? I'd like to give it a try

**Comment by ndrewxie** [comment]
> Is this being worked on ? I'd like to give it a try

Afaik it's not being worked on. Good luck!

**Comment by InfRandomness** [comment]
I'm not sure about the goal, after checking some stuff out
The goal would be to take the test (this test https://github.com/rust-lang/rust/commit/568b7221402b348fe65fd87ade2e1174b356bd74), and make it work by installing clang?

**Comment by jyn514** [comment]
@InfRandomness yup, that sounds right :)

**Comment by Dylan-DPC** [comment]
Closing as https://github.com/rust-lang/rust/pull/116264 resolves it
