### ISSUE TITLE
regression: no emojis in lifetime names (despite no emojis being present?)

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#109746]
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/solores-0.1.2/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/tuix_derive-0.2.0/log.txt

Not clear what the cause here is, but worth figuring out.

**Comment by ehuss** [comment]
Bisected to #108031. cc @jieyouxu / @estebank

**Comment by ehuss** [comment]
BTW, here's a minimal repro:

```rust
macro_rules! foo {
    ($tt1:tt) => {};
}

fn x() {
    foo!('me#foo);
}
```

**Comment by estebank** [comment]
Thanks for the ping! Fixing it in https://github.com/rust-lang/rust/pull/109754.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23109746.20regression.3A.20no.20emojis.20in.20lifetime.20names.20.28despite.20no.E2.80.A6)).

@rustbot label -I-prioritize +P-medium

**Comment by estebank** [comment]
Update: t-compiler decided to revert the PR that introduced the regression

**Comment by compiler-errors** [comment]
This was reverted in 1.69
