### ISSUE TITLE
regression: ICE failing to normalize

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#109743]
https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/jwiegley.motoko_parse/log.txt

```
[INFO] [stdout] error: internal compiler error: compiler/rustc_middle/src/ty/normalize_erasing_regions.rs:195:90: Failed to normalize fn() -> <impl combine::Parser<combine::easy::Stream<&str>, Output = std::string::String> as combine::Parser<combine::easy::Stream<&str>>>::PartialState {<<impl combine::Parser<combine::easy::Stream<&str>, Output = std::string::String> as combine::Parser<combine::easy::Stream<&str>>>::PartialState as std::default::Default>::default}, maybe try to call `try_normalize_erasing_regions` instead
```

**Comment by lukas-code** [comment]
searched nightlies: from nightly-2023-01-24 to nightly-2023-03-30
regressed nightly: nightly-2023-02-05
searched commit range: https://github.com/rust-lang/rust/compare/658fad6c5506f41c35b64fb1a22ceb0992697ff3...50d3ba5bcbf5c7e13d4ce068d3339710701dd603
regressed commit: https://github.com/rust-lang/rust/commit/9dee4e4c42d23b0c5afd6d8fed025181f70fbe12

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.5</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --regress=ice -- build 
```
</details>

This looks related to https://github.com/rust-lang/rust/issues/107678, but wasn't fixed by https://github.com/rust-lang/rust/pull/107688.

**Comment by lqd** [comment]
Let's notify the people involved in that bisection, it's https://github.com/rust-lang/rust/pull/107267 cc author @cjgillot and reviewer @oli-obk.

A minimization would be helpful.

**Comment by lukas-code** [comment]
This seems to have disappeared in nightly. Bisect points to https://github.com/rust-lang/rust/pull/108821. Maybe fixed by https://github.com/rust-lang/rust/pull/108750?

**Comment by lqd** [comment]
Wasn't that PR was already present in your previous bisection up to nightly-2023-03-30 ?

**Comment by lukas-code** [comment]
Ah, looks like the [MCVE](https://github.com/rust-lang/rust/issues/109743#issuecomment-1490352842) is fixed in https://github.com/rust-lang/rust/pull/108821, but not the [original code](https://github.com/jwiegley/motoko_parse/).

**Comment by lukas-code** [comment]
[new mcve](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=d9dee9a0817f180d04d2164f809b4b67)
```rust
use std::marker::PhantomData;

pub trait StreamOnce {
    type Token;
}

impl StreamOnce for &str {
    type Token = ();
}

pub trait Parser<Input: StreamOnce> {
    type PartialState: Default;
    fn parse_mode(&self, _state: &Self::PartialState) {}
    fn parse_mode_impl() {}
}

pub fn parse_bool<'a>() -> impl Parser<&'a str> {
    pub struct TokensCmp<C, Input>
    where
        Input: StreamOnce,
    {
        _cmp: C,
        _marker: PhantomData<Input>,
    }

    impl<Input, C> Parser<Input> for TokensCmp<C, Input>
    where
        C: FnMut(Input::Token),
        Input: StreamOnce,
    {
        type PartialState = ();
    }

    TokensCmp {
        _cmp: |_| (),
        _marker: PhantomData,
    }
}

pub struct ParseBool;

impl<'a> Parser<&'a str> for ParseBool
where
    &'a str: StreamOnce,
{
    type PartialState = ();

    fn parse_mode_impl() {
        parse_bool().parse_mode(&Default::default())
    }
}
```

@rustbot label -E-needs-mcve +S-bug-has-mcve
