### ISSUE TITLE
regression: cannot move out of shared reference

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#109744]
I suspect these may relate to the packed hard error, but it's not very clear what has changed here. Maybe a bisection will help. (I seem to recall a change in derive desugaring, maybe this is caused by that? It did have known regressions at the time, IIRC, though this seems like more than I recall).

* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/icu_locale_canonicalizer-0.6.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/ashkitten.roccat-tools/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/ecumene.bindgen-rust-bt-sdp/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/mars-research.binunpack-rs/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/numerodix.pcitools/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/oussama.twain/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/skreborn.bluetooth-sys/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/apache-nimble-sys-0.0.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/bluetooth-sys-0.1.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/icu_locale_canonicalizer-0.6.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/libpijul-compat-0.10.2/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/linux-usb-functionfs-sys-0.1.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/ntfs-3g-sys-0.1.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/seadawg-0.1.3/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/traildb-sys-0.6.3/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/twain-0.1.0/log.txt

**Comment by lqd** [comment]
I think it's indeed because the [packed hard error](https://github.com/rust-lang/rust/pull/102513) and [derive on packed structs](https://github.com/rust-lang/rust/pull/102513) changes both landed in 1.69.

`twain-0.1.0`, `icu_locale_canonicalizer-0.6.0`, or `mars-research.binunpack-rs`, all bisect to the latter, but the fact that they compiled on crater [since 1.62](https://github.com/rust-lang/rust/pull/95372) is likely because the deny-by-default lint was capped.

**Comment by Mark-Simulacrum** [comment]
Yep, sounds right. https://github.com/rust-lang/rust/pull/104429#issuecomment-1320909245 is the comment with explanation of the changes in derive on packed structs.

Removing prioritization, this seems like something we can just mention in relnotes as expected breakage.

**Comment by Enselic** [comment]
Triage: Not sure of this AWS mentioned in the release notes.

If it was not mentioned, it seems weird to do now.

If it was mentioned, there is no further action to take as far as I can tell.

Closing.
