### ISSUE TITLE
Bug: changes in one parameter affects another parameter while passing it from Rust to C function

### ISSUE THREAD

**Issue by Sjain-dir** [rust-lang/rust#109777]
----------------------
**Summary :** 
when i am passing 2 argument to a C function from rust, doing changes in the first parameter affects the value of the second parameter
----------------------
I tried this code in which i am just passing some values from Rust to C :
_you can also repeat this bug , code is in this repository :_ https://github.com/Sjain-dir/Bug_in_Rust

**in interface.c code** 
```C
void test1(int* i) {
    printf("in test 1 :::\n");
    printf("i pointer value is : %p\n",i);
    printf("i -> value in that addressr is : %d\n",*i);
}

void test2(char* string1, int *i) {
    printf("in test 2 :::\n");
    printf("i pointer value is : %p\n",i);
    printf("i value in that address is : %d\n",*i);
    printf("string1 value is : %s\n",string1);
}
```
In test1, i am just taking a integer pointer and returning the address and its value
in test2, i am doing the same, but i am also taking character pointer

**in main.rs** 
```rust
use std::ffi::{
    c_int,
    CString
};

#[link (name = "interface", kind = "static")]
extern "C" {
    fn test1(i : *mut c_int);
    fn test2(string1 : *mut CString, i : *mut c_int);
    //fn test2(string1 : CString, i : *mut c_int);
}

fn main() {
    trying();
}

fn trying() {
    unsafe {
        let mut string1 = CString::new("Likhe jo khat tujhe, jo teri yaad mee...........").expect("lol error in payload");
        let mut i : c_int = 69420;

        test1(&mut i);
        test2(&mut string1, &mut i);
        //test2(string1, &mut i);
    }
}
```
here i am just calling functions from C 
in trying function, i am declare a string and a int and passed its pointer to functions
and after `cargo run`
and the output is as expected :
```
in test 1 :::
i pointer value is : 0x7fff2d8fbbc4
i -> value in that address is : 69420
in test 2 :::
i pointer value is : 0x7fff2d8fbbc4
i value in that address is : 69420
string1 value is : ���FV
```
### **But : the bug is .....**
when i change do a little changes in passing CString like in `main.rs` : 
```rust
extern "C" {
    fn test1(i : *mut c_int);
    //fn test2(string1 : *mut CString, i : *mut c_int);
    fn test2(string1 : CString, i : *mut c_int);
}
```
in `trying()` function
```rust
        test1(&mut i);
        //test2(&mut string1, &mut i);
        test2(string1, &mut i);
```
So the output is : 
```
in test 1 :::
i pointer value is : 0x7fffdfbeff10
i -> value in that address is : 69420
in test 2 :::
i pointer value is : 0x31
Segmentation fault
```
test1 is running perfectly and giving expected output,
**but** in test2 output, somehow, **making changes in CString affects the output of `i` integer pointer**
this shouldn't happen as changes in the first parameter shouldn't affect the second parameter

**Comment by Teapot4195** [comment]
This is because of types, a c string is not the same as a pointer to a c string, when you changed the second function from taking a *mut cstring to a cstring. You changed the size of the parameter, the c code is still not aware of said change and therefore does not function as expected.

**Comment by wwylele** [comment]
[`CStr`'s doc](https://doc.rust-lang.org/std/ffi/struct.CStr.html) has a paragraph emphasizing it is not intended to be used as a FFI parameter, but the same was not done for [`CString`'s doc](https://doc.rust-lang.org/std/ffi/struct.CString.html). Maybe we should add that?

But in any case, for both of you program you should have got the warning against this
```
warning: `extern` block uses type `CString`, which is not FFI-safe
 --> src/main.rs:9:24
  |
9 |     fn test2(string1 : *mut CString, i : *mut c_int);
  |                        ^^^^^^^^^^^^ not FFI-safe
  |
  = help: consider adding a `#[repr(C)]` or `#[repr(transparent)]` attribute to this struct
  = note: this struct has unspecified layout
  = note: `#[warn(improper_ctypes)]` on by default
```
```
⣿
Standard Error

   Compiling playground v0.0.1 (/playground)
warning: variable does not need to be mutable
  --> src/main.rs:19:13
   |
19 |         let mut string1 = CString::new("Likhe jo khat tujhe, jo teri yaad mee...........").expect("lol error in payload");
   |             ----^^^^^^^
   |             |
   |             help: remove this `mut`
   |
   = note: `#[warn(unused_mut)]` on by default

warning: `extern` block uses type `CString`, which is not FFI-safe
 --> src/main.rs:9:24
  |
9 |     fn test2(string1 : CString, i : *mut c_int);
  |                        ^^^^^^^ not FFI-safe
  |
  = help: consider adding a `#[repr(C)]` or `#[repr(transparent)]` attribute to this struct
  = note: this struct has unspecified layout
  = note: `#[warn(improper_ctypes)]` on by default
```

**Comment by Sjain-dir** [comment]
> This is because of types, a c string is not the same as a pointer to a c string, when you changed the second function from taking a *mut cstring to a cstring. You changed the size of the parameter, the c code is still not aware of said change and therefore does not function as expected.

Ohk ohk,
Thanks you 😁

**Comment by Sjain-dir** [comment]
> [`CStr`'s doc](https://doc.rust-lang.org/std/ffi/struct.CStr.html) has a paragraph emphasizing it is not intended to be used as a FFI parameter, but the same was not done for [`CString`'s doc](https://doc.rust-lang.org/std/ffi/struct.CString.html). Maybe we should add that?
> 
> But in any case, for both of your program you should have got the warning against this
> ```
> warning: `extern` block uses type `CString`, which is not FFI-safe
>  --> src/main.rs:9:24
>   |
> 9 |     fn test2(string1 : *mut CString, i : *mut c_int);
>   |                        ^^^^^^^^^^^^ not FFI-safe
>   |
>   = help: consider adding a `#[repr(C)]` or `#[repr(transparent)]` attribute to this struct
>   = note: this struct has unspecified layout
>   = note: `#[warn(improper_ctypes)]` on by default
> ```
> ```
> warning: `extern` block uses type `CString`, which is not FFI-safe
>  --> src/main.rs:9:24
>   |
> 9 |     fn test2(string1 : CString, i : *mut c_int);
>   |                        ^^^^^^^ not FFI-safe
>   |
>   = help: consider adding a `#[repr(C)]` or `#[repr(transparent)]` attribute to this struct
>   = note: this struct has unspecified layout
>   = note: `#[warn(improper_ctypes)]` on by default
> ```

So what alternative should I use so that I can pass string from rust to c??

**Comment by Sjain-dir** [comment]
> The CString doc has an example:
> 
> ```rust
> use std::ffi::CString;
> use std::os::raw::c_char;
> 
> extern "C" {
>     fn my_printer(s: *const c_char);
> }
> 
> // We are certain that our string doesn't have 0 bytes in the middle,
> // so we can .expect()
> let c_to_print = CString::new("Hello, world!").expect("CString::new failed");
> unsafe {
>     my_printer(c_to_print.as_ptr());
> }
> ```

thank you so much bro 😁😁
