### ISSUE TITLE
The rust standalone installer for macOS aarch64 (Apple Silicon) fails to install

### ISSUE THREAD

**Issue by fenginsc** [rust-lang/rust#109877]
I downloaded the installation package on this page:
https://forge.rust-lang.org/infra/other-installation-methods.html#standalone

Download link:
https://static.rust-lang.org/dist/rust-1.68.2-aarch64-apple-darwin.pkg

Can't install, I also tried the previous version and couldn't install, I'm surprised no one found this problem, hope it can be resolved as soon as possible.

It cannot be installed on macbooks with m1 and m2 chips, but the x64 version of the intel version can be installed. I think there is a problem with the installer of the aarch64 version.

Thanks!
<img width="735" alt="Screenshot 2023-04-03 at 08 32 35" src="https://user-images.githubusercontent.com/50092603/229387928-8fff1d0c-d0da-4c5d-b27c-b7a88cfa52c0.png">

**Comment by ehuss** [comment]
Thanks for the report!  I have posted a fix in #109880.
