### ISSUE TITLE
Rename tests/ui/unique to `box`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#109878]
https://github.com/rust-lang/rust/tree/fe0b0428b89802f02a050eab72373b75709d0bce/tests/ui/unique all seem to be testing std::boxed::Box. It hasn't been called `unique` in many years, and that's now ambiguous with `ptr::Unqiue`. We should rename the test suite for clarity.

**Comment by Nilstrieb** [comment]
Most of these should be unit tests in `library/alloc`, not UI tests.

**Comment by jyn514** [comment]
No objection to that, but renaming the directory doesn't make it any harder to switch them to unit tests in the future.
