### ISSUE TITLE
rustdoc's source page is missing the horizontal scrollbar

### ISSUE THREAD

**Issue by cynecx** [rust-lang/rust#109865]
The horizontal scrollbar is missing on basically every source page.

Example: https://doc.rust-lang.org/nightly/src/core/lib.rs.html

![Peek 2023-04-02 21-50](https://user-images.githubusercontent.com/5961244/229375666-f5fad1fa-2384-40e1-801e-f015e6d3205b.gif)

**Comment by clubby789** [comment]
On Firefox, the horizontal scrollbar is visible at the bottom of the source code for me

**Comment by cynecx** [comment]
On Firefox 111 (macOS 13.2)

<img width="660" alt="image" src="https://user-images.githubusercontent.com/5961244/229575137-ecf8ee63-2829-45f2-9579-cbed01193cfa.png">

Same thing there.
