### ISSUE TITLE
Where are all the strings?

### ISSUE THREAD

**Issue by road2react** [rust-lang/rust#109826]
Rust only has the [CString](https://doc.rust-lang.org/std/ffi/struct.CString.html), for FFI
But a language with just one? We must see why
CString has limitations that are hard to see
So what’s missing? Let's analyze thee!

![image](https://user-images.githubusercontent.com/93143714/228746184-46f668cb-df8d-47e5-a959-fbe5b9263399.png)

A viola has 4 strings, with the lowest one in C
But for Rust strings there’s nothing that can be
For all G, D, and A must also be seen
To make our programming language complete!

So listen dear Rustaceans, let's rise to the task 
For our language won't reach its peak
We’ll add G, D and A with haste 
And enjoy vastly improved strings complete!

No longer just 1 type, we would wield 3 more 
The opportunities our language explores
For with 4 strings fully suited, our music can soar 
Eagerly awaiting the new notes that it will adore.

<details>
<summary></summary>
If only this could happen, we'd surely be in luck<br>
No longer just a single chord but full symphonies we've shore up<br>
These hopes alas, do not come true on this date<br>
The fools of April 1st have relinquished our fate
</details>

**Comment by PatchMixolydic** [comment]
Viola must be
mutably borrowed so we
can change its design

yet players want to tune it.
This is E0499.

**Comment by jyn514** [comment]
this was fun, thanks :)
