### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by Zhiming** [rust-lang/rust#109870]
Access to manifest at 'https://openaiapi-site.azureedge.net/public-assets/d/c7a1c745dc/manifest.json' from origin 'https://platform.openai.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by clubby789** [comment]
Has this issue been filed to the wrong repo?

**Comment by saethlin** [comment]
Honestly at this point I think it's more likely that this is a failed GPT bot
