### ISSUE TITLE
`OwningRef` is included in the compiler despite known soundness problems.

### ISSUE THREAD

**Issue by noamtashma** [rust-lang/rust#109974]
The [`OwningRef` module in rustc_data_structures](https://doc.rust-lang.org/beta/nightly-rustc/rustc_data_structures/owning_ref/index.html), which seems to be a copy of [this crate](https://docs.rs/owning_ref/latest/owning_ref/index.html) (perhaps with small additions?), has known soundness issues.

I wrote an article about the soundness problems [here](https://github.com/noamtashma/owning-ref-unsoundness).

It's used in rustc in [`MetadataRef`](https://doc.rust-lang.org/beta/nightly-rustc/rustc_data_structures/sync/type.MetadataRef.html) and related things. (I don't know if it's used anywhere else).

I don't know of any actual unsafe use of this crate in rustc, but I haven't actually tried to look for any.

IMO, in order to keep the code safe, either `owning_ref` should be replaced with something else, or otherwise, it should be updated to contain the known fixes to these soundness problems ([here](https://github.com/Kimundi/owning-ref-rs/pull/78)).

**Comment by Nilstrieb** [comment]
Great timing! #109971
