### ISSUE TITLE
Manually moving shared libraries to a multiarch libdir, eg, /usr/lib/x86_64-linux-gnu, breaks after 1.67

### ISSUE THREAD

**Issue by cheese** [rust-lang/rust#109994]
### Description

Debian deploys a multiarch schema. For Rust, `librustc_driver-*.so` and other shared libraries needed for `rustc` to run are installed to `/usr/lib/x86_64-linux-gnu` on x86_64. And `rustlib` directory is installed as `/usr/lib/rustlib`.

During Rust build, Debian just lets `x.py` install the shared libraries to `/usr/lib`, and then manually moves them to `/usr/lib/x86_64-linux-gnu`.

This works before 1.67.

But since 1.67, `rustc` will fail to find `std` crate, since `rustc` tries to find `rustlib` directory through a relative path based on `librustc_driver-*.so`. `rustc` guesses `rustlib` directory is   `/usr/lib/x86_64-linux-gnu/../lib/rustlib` aka `/usr/lib/lib/rustlib`, which does not exist.

To work around this, Ubuntu deploys a downstream [patch](https://git.launchpad.net/ubuntu/+source/rustc/tree/debian/patches/ubuntu-fix-sysroot-detection.patch?h=applied/ubuntu/lunar-devel&id=7cc6b62b69c95351eaec5c89088853aeec52d39d). But as [discussed](https://users.rust-lang.org/t/failed-to-build-rust-1-68-2-for-freedesktop-sdk-std-library-not-found/91964/8) with @bjorn3, that patch actually breaks what Rust 1.67 trying to get.

I hope Rust upstream can provide a better solution for this installation schema to work without downstream patch.

### Version it worked on

It most recently worked on: Rust 1.66.1

### Version with regression

1.67

**Comment by ozkanonur** [comment]
Thank you for the report. I can take care of it over the weekend.

-

If anyone has time, feel free taking/fixing this before the weekend.

**Comment by ozkanonur** [comment]
Just remember we have already patched sys detection for supporting multiarch systems.

Related commit https://github.com/rust-lang/rust/commit/2186358e5a124d486f55a20220f720fb8f9a0694

It's added to `1.69.0` milestone.

**Comment by cheese** [comment]
> Just remember we have already patched sys detection for supporting multiarch systems.
> 
> Related commit [2186358](https://github.com/rust-lang/rust/commit/2186358e5a124d486f55a20220f720fb8f9a0694)
> 
> It's added to `1.69.0` milestone.

Oh! The same author of the Ubuntu patch.

**Comment by ozkanonur** [comment]
> Hi, I'm experiencing the same issue when packaging 1.67 for Debian. [2186358](https://github.com/rust-lang/rust/commit/2186358e5a124d486f55a20220f720fb8f9a0694) as mentioned by @ozkanonur didn't work. The fix is behind a check `dir.ends_with(crate::config::host_triple())`, which evaluates to false because `host_triple()` is `x86_64-unknown-linux-gnu` on x86_64 and `dir` is `/usr/lib/x86_64-linux-gnu`, where Debian installs multi-arch libs for x86_64. I'm testing with a `||` clause that simply checks against `host_triple().replace("-unknown", "")`, but open to better solutions.

How did you test that patch? It's not shipped with `1.67`

**Comment by bnoctis** [comment]
> How did you test that patch? It's not shipped with `1.67`

The fix isn't shipped with 1.67, but the problematic code it's for is. I was building 1.68 with this 1.67, met this issue, cherry picked this fix, still met this issue, and figured the check evaluates to false, causing the fix to not take effect.

**Comment by ozkanonur** [comment]
> The fix isn't shipped with 1.67, but the problematic code it's for is. I was building 1.68 with this 1.67, met this issue, cherry picked this fix, still met this issue, and figured the check evaluates to false, causing the fix to not take effect.

Thank you for your feedback, I will check it this week.

**Comment by bnoctis** [comment]
A deeper look concluded my previous finding partially wrong.

In `default_from_rustc_driver_dll()`, two levels are unconditionally chopped off from the path of `librustc_driver-*.so`. On Debian it's currently installed to `/usr/lib/x86_64-linux-gnu/librustc_driver-*.so`, so after that `dir` becomes `/usr/lib`. The check I mentioned earlier will, of course, evaluate to false, because there's no more arch specific directory on the path.

The comment line "`dll` will be in one of the following two" may need to be changed to three.

**Comment by ozkanonur** [comment]
I have tested [this](https://github.com/rust-lang/rust/pull/110281/commits/a1251b157fa83accdbc39bf3ee39ce669a34f071) on Debian 11, worked just fine. It's under review progress now.

**Comment by bnoctis** [comment]
I see, thanks for the help 🥂 I'll cherry-pick that then.
