### ISSUE TITLE
Ord and PartialOrd derives do not specify ordering behavior types with multiple fields

### ISSUE THREAD

**Issue by james7132** [rust-lang/rust#109946]
### Location

Derive macros for [Ord](https://doc.rust-lang.org/std/cmp/macro.Ord.html) and [PartialOrd](https://doc.rust-lang.org/std/cmp/macro.PartialOrd.html).

### Summary

The derive macros for Ord and PartialOrd do not specify what the order of precedence it generates in the resulting implementation. This order matters, and makes reordering fields on a type with this derive a semver-incompatible breaking change.

## Examples

```rust
#[derive(PartialEq, Eq, PartialOrd, Ord)]
pub struct MyStruct {
   field_1: u32,
   field_2: i32,
}
```
Does `field_1` take precedence over `field_2` when comparing two `MyStruct`s?

```rust
#[derive(PartialEq, Eq, PartialOrd, Ord)]
pub enum MyEnum {
   Variant_1 {
     field_1: u32,
     field_2: i32,
   },
   Variant_2 {
     field_1: i32,
     field_2: u32,
   }
   Variant_3(MyStruct),
}
```
Do all `Variant_1` come before or after `Variant_2`?

**Comment by asquared31415** [comment]
The [trait docs](https://doc.rust-lang.org/std/cmp/trait.PartialOrd.html#derivable) specify the way that the derive works.  These docs should probably be duplicated on the derive macro too.
