### ISSUE TITLE
Update `Wake` example to use `pin!` macro instead of `Box::pin`

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/rust#109965]
### Location

https://doc.rust-lang.org/std/task/trait.Wake.html#examples

### Summary

The `Wake` example currently uses `Box::pin`, but now that the `pin!` macro has been stabilized in [Rust 1.68](https://blog.rust-lang.org/2023/03/09/Rust-1.68.0.html), it should probably use that instead. This should be an easy contribution for someone who wants to land a first contribution.

**Comment by AnuragNishad12** [comment]
hey can u help me from where i can fix this

**Comment by AnuragNishad12** [comment]
Can u tell me how u solve this?
@madsravn

**Comment by madsravn** [comment]
@AnuragNishad12 I have already solved this one and it is in the process of being reviewed for merging.

If you wish to solve an issue, you need to pick one that has not been assigned yet. Try looking at this: https://github.com/rust-lang/rust/issues?q=is%3Aissue+is%3Aopen+label%3AE-easy+no%3Aassignee

**Comment by AnuragNishad12** [comment]
hey @madsravn im new to open source,  i want to grow in this field .
Can i contact with u ?

**Comment by madsravn** [comment]
@AnuragNishad12 I am pretty new to this project myself, but please reach out if you have any starter-questions and then I might be able to help you out.

There is a chat on https://rust-lang.zulipchat.com/ - I am just "Mads Ravn" in there.

**Comment by AnuragNishad12** [comment]
Thanks
