### ISSUE TITLE
bootstrap: build locking doesn't work any more

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#109967]
I tried this code:

```rust
x t tidy & x t tidy
```

I expected to see this happen: Bootstrap is built, and one process runs tidy while the other says "waiting for build lock"

Instead, this happened:
```
; x t tidy & x t tidy 
[1] 34539
Building bootstrap
Building bootstrap
    Blocking waiting for file lock on build directory
    Finished dev [unoptimized] target(s) in 0.20s
    Finished dev [unoptimized] target(s) in 0.24s
Building tool tidy (stage0)
warning: creating symbolic link `/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-sysroot/lib/rustlib/src/rust` to `/Users/jyn/src/rust` failed with File exists (os error 17)
warning: creating symbolic link `/Users/jyn/src/rust/build/aarch64-apple-darwin/stage0-sysroot/lib/rustlib/rustc-src/rust` to `/Users/jyn/src/rust` failed with File exists (os error 17)
Building tool tidy (stage0)
    Finished release [optimized] target(s) in 0.98s
fmt check
    Finished release [optimized] target(s) in 1.14s
fmt check
```

### Meta

HEAD is branched from 90a9f69c80812c8694959c1f2d5c336e3300d1e2. 
```
; uname -a
Darwin jyns-MacBook-Pro 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64
```

**Comment by jyn514** [comment]
I do have a `build/lock` file, but apparently `flock` isn't working correctly?

**Comment by jyn514** [comment]
@miguelraz also ran into this on Linux. I'm starting to think locking is just completely broken.

**Comment by Ezrashaw** [comment]
I can confirm it doesn't seem to work on linux. Although it is important to note that `cargo` still correctly locks, so *most* things should de-duplicate from `cargo` anyway.

**Comment by jyn514** [comment]
No, bootstrap has its own locking issues separate from cargo because it deletes and recreates the sysroot.

**Comment by Ezrashaw** [comment]
Ahh, I'm just seeing the behaviour you saw [here](https://github.com/rust-lang/rust/issues/76661#issuecomment-706484351). At least `x t tidy` times 2 doesn't crash and burn lol.

**Comment by albertlarsan68** [comment]
Well... It may very well be #108607🤦. I see a quick fix, just move the lock guard back out of the block.
