### ISSUE TITLE
Rustdoc lists empty opaque type for async fn

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#109931]
Since beta 1.69.0 (and also in nightly), the rustdoc output has an empty opaque type listed. Take this code:

```Rust
fn main() {}
async fn foo() {}
```

Then save it as `main.rs` and do:

```
rustdoc +beta main.rs --crate-type bin --edition=2021 --document-private-items
```

There will be an empty opaque type listed, which is not clickable like the other things (probably due to being empty):

![Screenshot_20230404_114551](https://user-images.githubusercontent.com/8872119/229753955-0b136e8a-a6ec-4627-9250-dc2f251f6c00.png)

If you navigate to the `opaque..html` file manually, you get this:

![Screenshot_20230404_114451](https://user-images.githubusercontent.com/8872119/229753743-413223ee-25d6-4863-8a04-d19ac1f45c4d.png)

It also reproduces on current nightly as of filing this bug. And also for `cargo init --bin` followed by adding an async function and then `cargo +beta doc`. The option to document private items is important.

@rustbot modify labels: +regression-from-stable-to-beta -regression-untriaged +T-rustdoc

**Comment by jyn514** [comment]
cc @compiler-errors

**Comment by compiler-errors** [comment]
Not sure why I was preemptively pinged, but @GuillaumeGomez regressed this in #104889.

searched nightlies: from nightly-2022-11-01 to nightly-2023-04-04
regressed nightly: nightly-2022-12-23
searched commit range: https://github.com/rust-lang/rust/compare/b569c9dc57ee22b6ff94563af856909763dfa24b...8a97b4812a7a46bb5206487c2455b9c5bfcbd1b9
regressed commit: https://github.com/rust-lang/rust/commit/cce9e72c55994335f8d1dac892cca755b65c8f43

**Comment by compiler-errors** [comment]
Anyways I can fix this since I already looked at the code.

@rustbot claim

**Comment by GuillaumeGomez** [comment]
I wasn't but it's great if you already have a solution. :)

**Comment by eholk** [comment]
Is this fixed as of #109937, or are we waiting for the backport to beta?

**Comment by jyn514** [comment]
Let's keep this open until the beta backport happens.

**Comment by est31** [comment]
Done, not in a beta backport but the stable PR directly: #110413 . Thanks everyone!
