### ISSUE TITLE
LLVM submodule isn't checked out when building `riscv64gc-unknown-linux-musl` target

### ISSUE THREAD

**Issue by catamorphism** [rust-lang/rust#109987]
I cloned the Rust repo with the intention of building rustc for cross-compilation to the `riscv64gc-unknown-linux-musl` target. I did the following:

1. `$x.py setup` - selected the "codegen" option
2. Edited the `config.toml` file to append:

```
 [target.riscv64gc-unknown-linux-musl]
 ar = "riscv64-unknown-linux-musl-ar"
 linker = "riscv64-unknown-linux-musl-gcc"
 cc = "riscv64-unknown-linux-musl-gcc"
 cxx = "riscv64-unknown-linux-musl-g++"
 musl-root = "/home/tjc/riscv64-linux-musl-cross/riscv64-linux-musl"
```
3. ` ./x.py build --target  x86_64-unknown-linux-gnu --target riscv64gc-unknown-linux-musl`

This failed; the end of the output is as follows:

```
 Building stage1 library artifacts (x86_64-unknown-linux-gnu) 
[snip]
 Finished release [optimized] target(s) in 43.27s
Building crtbegin.o and crtend.o
running: "riscv64-unknown-linux-musl-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-march=rv64gc" "-mabi=lp64d" "-mcmodel=medany" "-std=c11" "-DCRT_HAS_INITFINI_ARRAY" "-DEH_USE_FRAME_REGISTRY" "-o" "/home/tjc/rust2/build/riscv64gc-unknown-linux-musl/native/crt/crtbegin.o" "-c" "/home/tjc/rust2/src/llvm-project/compiler-rt/lib/crt/crtbegin.c"
cargo:warning=cc1: fatal error: /home/tjc/rust2/src/llvm-project/compiler-rt/lib/crt/crtbegin.c: No such file or directory
cargo:warning=compilation terminated.
exit status: 1


error occurred: Command "riscv64-unknown-linux-musl-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-march=rv64gc" "-mabi=lp64d" "-mcmodel=medany" "-std=c11" "-DCRT_HAS_INITFINI_ARRAY" "-DEH_USE_FRAME_REGISTRY" "-o" "/home/tjc/rust2/build/riscv64gc-unknown-linux-musl/native/crt/crtbegin.o" "-c" "/home/tjc/rust2/src/llvm-project/compiler-rt/lib/crt/crtbegin.c" with args "riscv64-unknown-linux-musl-gcc" did not execute successfully (status code exit status: 1).


Build completed unsuccessfully in 0:02:32
```

After I executed `git submodule update --init` and retried the build command, the LLVM submodule was checked out and the build was able to make progress. It seems like this should be done automatically. I'm not sure if the issue is specific to this target or if it's happening with other cross-compilation targets.

**Comment by jyn514** [comment]
Hmm. This is some interaction between `download-ci-llvm=true` and cross-compiling, but I'm not sure exactly what — it *should* be a no-op unless you're building for the host.

As a workaround you can set `download-ci-llvm=false` and that should handle the submodule automatically.

**Comment by jyn514** [comment]
(Note that `download-ci-llvm=true` is implied by `profile = codegen`.)

**Comment by jyn514** [comment]
Ok, it looks like we only try to build crtbegin.o for musl targets: https://github.com/rust-lang/rust/blob/8d321f7a88f0ae27793c133390e507bf1f49125a/src/bootstrap/compile.rs#L238-L270

So I think we *would* have checked out the submodule if we were doing a full LLVM build, but because we're only building the CRT it got missed when download-ci-llvm was implemented. I think the simplest fix is to call `builder.update_submodule` at the start of `CrtBeginEnd::run`: https://github.com/rust-lang/rust/blob/f98a2718141593fbb8dbad10acc537786d748156/src/bootstrap/llvm.rs#L1077-L1097

**Comment by jyn514** [comment]
`llvm::Libunwind` looks like it also has the same bug: https://github.com/rust-lang/rust/blob/f98a2718141593fbb8dbad10acc537786d748156/src/bootstrap/llvm.rs#L1143-L1167
as well as `dist::Src`: https://github.com/rust-lang/rust/blob/f98a2718141593fbb8dbad10acc537786d748156/src/bootstrap/dist.rs#L896-L915

**Comment by KittyBorgX** [comment]
Does fixing `llvm::Libunwind` `dist::Src` also come under the scope of this issue? I'd be happy to fix that as well.

**Comment by jyn514** [comment]
@KittyBorgX sure thing, feel free to fix all three at once :)

**Comment by KittyBorgX** [comment]
@jyn514 Do I pause work on this till #110074 gets resolved? Since it's implementing the workaround you mentioned as a solution

**Comment by jyn514** [comment]
@KittyBorgX no, this fix still makes sense - not everyone is using the `codegen` profile without changes.
