### ISSUE TITLE
Unstable book uses box_syntax

### ISSUE THREAD

**Issue by Nilstrieb** [rust-lang/rust#109978]
https://github.com/rust-lang/rust/blob/4cb92cc83ac6b24d83f8a30763b276cadb8dc41d/src/doc/unstable-book/src/language-features/lang-items.md?plain=1#L19

There is no such thing as box_syntax anymore :D

**Comment by Nilstrieb** [comment]
`plugin.md` does the same.

**Comment by fee1-dead** [comment]
It probably makes sense to search across the repository (including submodules) any references to this removed feature and remove them
