### ISSUE TITLE
x86-interrupt calling convention with error code is broken on x86_64-unknown-none

### ISSUE THREAD

**Issue by SamZhang3** [rust-lang/rust#109918]
See [this godbolt link](https://godbolt.org/z/nPK5Ks3ev).

At line 177 of the generated assembly, it loads the address `rsp + 176` and passes it to the `core::fmt::ArgumentV1::new_debug` function. The offset 176 is incorrect since the data pushed to the stack in lines 166-175, the 40-byte stack frame pushed during the interrupt, and the 8-byte error code are only 128 bytes total, so the address will point to something random below the interrupt stack frame on the stack.

This does not occur if the error code argument is removed: see [godbolt](https://godbolt.org/z/Y95K75oes). Here, an additional `sub rsp, 80` instruction appears at line 175 after saving registers, and the offset used at line 177 is correct (skipping the 80 bytes plus the 72 from the 9 saved registers, for 152 bytes total).

Experimenting with custom target JSON specifications instead of x86_64-unknown-none, it appears that the bug disappears when the `"stack-probes": {"kind": "inline-or-call", ...}` part of the specification is removed.

**Comment by cuviper** [comment]
cc #40180

**Comment by Freax13** [comment]
This regression seems to have been introduced by the LLVM 16 upgrade.

---

searched nightlies: from nightly-2023-03-24 to nightly-2023-05-03
regressed nightly: nightly-2023-03-26
searched commit range: https://github.com/rust-lang/rust/compare/8be3c2bda6b683f87b24714ba595e8b04faef54c...0c61c7a978fe9f7b77a1d667c77d2202dadd1c10
regressed commit: https://github.com/rust-lang/rust/commit/0c61c7a978fe9f7b77a1d667c77d2202dadd1c10

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.5</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --script build.sh --start 2023-03-24 -vvvvv --with-src --preserve 
```
</details>

**Comment by Freax13** [comment]
This bug seems to have been present in LLVM versions earlier than 16, I'm not sure why this only surfaced now. I'm working on a patch for LLVM.
