### ISSUE TITLE
running cargo extention

### ISSUE THREAD

**Issue by Ludea** [rust-lang/rust#110046]
I tried this code:
cargo deb myapp

I expected to see this happen: *explanation*
a deb package created for my app
 
Instead, this happened: *explanation*
`/root/.cargo/bin/cargo-deb: 1: Syntax error: word unexpected (expecting ")")`.

Note: Work outside a container, doesn't work inside a container (I use https://github.com/rust-cross/rust-musl-cross), I don't know if matter

### Meta

`rustc --version --verbose`:
```
1.68.2
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by jyn514** [comment]
This is a bug in cargo-deb, not the compiler itself. The issue tracker is not a support forum. For future questions please ask in one of these places:

https://discord.gg/rust-lang/
https://discord.gg/rust-lang-community/
https://users.rust-lang.org/
https://rust-lang.zulipchat.com/
