### ISSUE TITLE
Rename `ignore-git` to `omit-git-hash`

### ISSUE THREAD

**Issue by duckymirror** [rust-lang/rust#110020]
As mentioned by @jyn514 [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/326414-t-infra.2Fbootstrap/topic/Test.20for.20.23107094/near/347478265), the `ignore-git` option of the bootstrap configuration should be renamed to `omit-git-hash` to better describe its meaning and distinguish it from `submodules = false`. It indicates that information about the current commit shouldn't be displayed when e.g. `rustdoc --version --verbose` is run. This isn't clear from the current name.

**Comment by jyn514** [comment]
I think it's rare for anyone to set this option manually, but we should update `src/bootstrap/CHANGELOG.md` at the same time we remove the option just in case.

**Comment by Mark-Simulacrum** [comment]
Do we have this by default in some profile? Otherwise, I would expect setting this to be common - it's necessary to avoid rebuilds after git commit, I think.

**Comment by duckymirror** [comment]
The default configurations don't use it, but it defaults to `channel == "dev"` if it's unset.
