### ISSUE TITLE
Comments and whitespace changing program behavior

### ISSUE THREAD

**Issue by dangeloj** [rust-lang/rust#110039]
Hello! I've run into a weird situation where changing non-code portions of my app (add a comment, change white space, etc.) change the application's behavior. It's a d3d11 app on Windows 10 (an older Dell XPS15) using nightly or stable. I've distilled everything down to a [single file 1](https://gitlab.com/jjv.dangelo/wtf-rust/-/blob/main/src/main.rs) that reproduces the issue on my machine. There are three outcomes when running cargo run (or even cargo clean && cargo run):

1. The expected scene running at approximately the target FPS;
2. The expected scene running at approximately 4 FPS;
3. A white window running at approximately the target FPS.

If I update the file in a way that causes a recompilation without actually changing the code, the behavior randomly changes. I cannot see a clear pattern as if I have it running with a stable FPS, add a comment which changes the behavior, deleting the comment doesn't reset it back to the stable state. I can reproduce it using the stable compiler as well as building in release.

I have a repo that distills down to as simple enough of an example that makes it easy to repro.

https://gitlab.com/jjv.dangelo/wtf-rust/-/blob/main/src/main.rs

I have tried:

 - `cargo clean && cargo build`;
 - Deleting Cargo.lock and letting the dependencies update;
 - Comment out different parts of the d3d11 calls;
 - Copying to another folder and running it from there;
 - Turning incremental builds on and off;
 - Distilling the issue down to a single file away from the rest of my code;

I pulled the sample app together quickly, opting to write most of it by hand to see if I could reproduce the issue. Please let me know if there's anything else that I can help provide!

### Meta

`rustc --version --verbose`:
```
rustc 1.70.0-nightly (2eaeb1eee 2023-04-05)
binary: rustc
commit-hash: 2eaeb1eee1b21772de8b935236d16ff8e03fdcf5
commit-date: 2023-04-05
host: x86_64-pc-windows-msvc
release: 1.70.0-nightly
LLVM version: 16.0.0
```
Laptop specs:
```
Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
16.0 GB (15.8 GB usable) RAM
Windows 10 Home, version 22H2, build 19045.2728
```

**Comment by jyn514** [comment]
@dangeloj the issues you've mentioned sound like they could be because of Undefined Behavior in your program - I noticed you have several unsafe calls. Do you see the same issue in the debug profile, not just the release profile?

**Comment by jyn514** [comment]
The other likely possibility is that you have some timing or race condition that makes the program nondeterministic.

**Comment by dangeloj** [comment]
@jyn514 that would make a lot of sense--I'm going to go back through and think through the aliasing issues that might be going on. Thank you!

**Comment by gimbles** [comment]
Consider MIRI to help you on your UB-finding journey

**Comment by dangeloj** [comment]
> Consider MIRI to help you on your UB-finding journey

Unfortunately, MIRI doesn't like the external calls to the `windows` crate 😄 

> error: unsupported operation: can't call foreign function `GetModuleHandleA` on OS `windows`
>       |
> 315 |     let result__ = GetModuleHandleA(lpmodulename.into().abi());
>       |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't call foreign function
> `GetModuleHandleA` on OS `windows`
>    |
>     = help: this is likely not a bug in the program; it indicates that the program performed an o
peration that the interpreter does not support

I'm still trying to reduce this sample down further to see if I can spot the place where UB might be popping up. I've also compared it with other examples online and I'm not spotting any differences. This is definitely going to be a journey :)

**Comment by dangeloj** [comment]
Well, I think I found the issue, for anybody who may be interested. I can't seem to reproduce the original issue which stemmed from the joys of programming. I decided to run `cargo clippy` to see if anything interesting would pop up. I saw this message, which didn't make sense:

```
warning: casting function pointer `mem::size_of::<cgmath::Matrix4<f32>>` to `u32`, which truncate
s the value
   --> src\main.rs:413:24
    |
413 |             ByteWidth: mem::size_of::<cgmath::Matrix4<f32>> as _,
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `mem::size_of::
<cgmath::Matrix4<f32>> as usize`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.ht
ml#fn_to_numeric_cast_with_truncation
    = note: `#[warn(clippy::fn_to_numeric_cast_with_truncation)]` on by default
```

Here's the full code:

```
let constant_buffer_desc = D3D11_BUFFER_DESC {
    ByteWidth: mem::size_of::<cgmath::Matrix4<f32>> as _,
    Usage: D3D11_USAGE_DYNAMIC,
    BindFlags: D3D11_BIND_CONSTANT_BUFFER,
    CPUAccessFlags: D3D11_CPU_ACCESS_WRITE,
    ..Default::default()
};
```

If you look closely, I was telling d3d11 that my constant buffer is the size of a function pointer--not the sizse of a 4x4 `f32` matrix. D'oh! I think this qualifies as my first "I missed a semicolon"-like issue in a long time. So,  it was UB and even a race condition--overwriting memory you don't own is a Bad Thing™.

We can definitely close this and bury it deep, deep, deep into the archives of the internet.
