### ISSUE TITLE
Miri UI tests aren't run on CI (or locally)

### ISSUE THREAD

**Issue by CraftSpider** [rust-lang/rust#110102]
# Issue

As the title says - Miri UI tests aren't run when invoked through x.py, or on CI:
https://github.com/rust-lang-ci/rust/actions/runs/4636594388/jobs/8204646214#step:26:13316

The actual issue appears to be that `compiletest.rs` in the miri directory expects *no* non-filter args to be passed to it when being run, but the args `-Z unstable-options --format json` are getting passed.

# Discovery

I was trying to test miri locally, and I ran the command `x.py test src/tools/miri --stage 2`. I expected the miri UI tests to get run, but instead, they were all always getting filtered out, despite not passing a filter. After looking into it a bit, I discovered the filter vector was always `["-Z", "unstable-options", "--format", "json"]`, and decided to check whether bors was running them.

**Comment by jyn514** [comment]
This seems ... pretty unfortunate :sweat:

cc @rust-lang/release @rust-lang/miri, I know miri is nightly only but it makes me pretty uncomfortable to be shipping tools that aren't running tests, even if rust-lang/miri is still running the tests.

**Comment by saethlin** [comment]
If my shell history is anything to go by, this is recent breakage, and `x test miri` used to run all of Miri's tests.

**Comment by oli-obk** [comment]
Yea, this is not breakage on the miri side afaict, but must be a change on the cargo or bootstrap side.

I'm fine fixing this on our side tho. I can replicate the `--` behaviour of the default test runner and adjust the wrappers in the miri repo to insert that

**Comment by CraftSpider** [comment]
For making it follow normal `--` behavior, I'm just replacing the `skip(1).filter(...)` in compiletest with `skip_while(|arg| arg != "--")` for now. I'd be willing to PR this change as a standalone if desired.

**Comment by oli-obk** [comment]
> For making it follow normal `--` behavior, I'm just replacing the `skip(1).filter(...)` in compiletest with `skip_while(|arg| arg != "--")` for now. I'd be willing to PR this change as a standalone if desired.

Thanks! That would be great

**Comment by RalfJung** [comment]
How does looking for `--` help? Looks to me like we'd have to know exactly which flags the regular test runner understands and parse them all the same way.  Which is of course ridiculous.

Can we stop bootstrap from passing wrong flags to test runners?
