### ISSUE TITLE
thread '' panicked at 'not yet implemented', C:\Users\tings.cargo\registry\src\github.com-1ecc6299db9ec823\tract-hir-0.18.4\src\ops\array\reshape.rs:133:17

### ISSUE THREAD

**Issue by tingyang01** [rust-lang/rust#110185]
Hello.
I am trying to use this C API.
I've built C API dll with rust 1.68.2 and DeepFilterNet-0.4.0.
#include
#include "deep_filter.h"
#pragma comment(lib,"WS2_32")

int main()
{
float atten_lim = 12.0;
const char* onnxPath = "models/DeepFilterNet2_onnx.tar.gz";
DFState *_dfModel = df_create(onnxPath, atten_lim);
//df_free(dfModel);
std::cout << "Hello World!\n";
}

But I am getting this error on running the execution file:
DeepFilterNet\DeepFilterNetWindows\x64\Release>DeepFilterNetWindows.exe
thread '' panicked at 'not yet implemented', C:\Users\tings.cargo\registry\src\github.com-1ecc6299db9ec823\tract-hir-0.18.4\src\ops\array\reshape.rs:133:17
stack backtrace:
0: std::panicking::begin_panic_handler
at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library\std\src\panicking.rs:575
1: core::panicking::panic_fmt
at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library\core\src\panicking.rs:64
2: core::panicking::panic
at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library\core\src\panicking.rs:111
3: tract_hir::ops::array::reshape::to_axis_ops
4: <tract_hir::ops::array::reshape::Reshape as tract_hir::ops::expandable::Expansion>::wire
5: tract_hir::ops::expandable::<impl tract_hir::infer::rules::InferenceRulesOp for alloc::boxed::Box>::to_typed
6: tract_hir::infer::rules::::to_typed
7: ZN512
$LT$tract_core..model..graph..Graph$LT$tract_hir..infer..fact..InferenceFact$C$alloc..boxed..Box$LT$dyn$u20$tract_hir..infer..ops..InferenceOp$GT$$GT$$u20$as$u20$tract_hir..infer..model..InferenceModelExt$GT$..into_typed..ToTypedTranslator$u20$a
8: tract_core::model::translator::Translate::translate_model
9: <tract_core::model::graph::Graph<tract_hir::infer::fact::InferenceFact,alloc::boxed::Box> as tract_hir::infer::model::InferenceModelExt>::into_typed
10: deepfilter::tract::DfTract::new
11: df_create
12: main
at deepfilternetwindows\deepfilternetwindows\deepfilternetwindows.cpp:13
13: invoke_main
at d:\agent_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
14: __scrt_common_main_seh
at d:\agent_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
15: BaseThreadInitThunk
16: RtlUserThreadStart
note: Some details are omitted, run with RUST_BACKTRACE=full for a verbose backtrace.

Thanks

**Comment by Nilstrieb** [comment]
This looks like a bug int the rust libraries you're using, not in the Rust language. You should report it there (I assume it's https://github.com/sonos/tract).
