### ISSUE TITLE
"Alternatively, use the pre-vendored `rustc-src` dist component" is confusing

### ISSUE THREAD

**Issue by catamorphism** [rust-lang/rust#110163]
### Code

While logged in as `root` on Linux::

1. Clone the Rust repo
2. `cd rust; ./x.py build`

### Current output

```Shell
info: looks like you're trying to run this command as root
      and so in order to preserve your $HOME this will now
      use vendored sources by default.
error: vendoring required, but vendor directory does not exist.
       Run `cargo vendor --sync ./src/tools/rust-analyzer/Cargo.toml --sync ./compiler/rustc_codegen_cranelift/Cargo.toml --sync ./src/bootstrap/Cargo.toml ` to initialize the vendor directory.
Alternatively, use the pre-vendored `rustc-src` dist component.
Traceback (most recent call last):
  File "/home/scratch/rust/./x.py", line 29, in <module>
    bootstrap.main()
  File "/home/scratch/rust/src/bootstrap/bootstrap.py", line 949, in main
    bootstrap(args)
  File "/home/scratch/rust/src/bootstrap/bootstrap.py", line 896, in bootstrap
    build.check_vendored_status()
  File "/home/scratch/rust/src/bootstrap/bootstrap.py", line 831, in check_vendored_status
    raise Exception("{} not found".format(vendor_dir))
Exception: /home/scratch/rust/vendor not found
```

### Desired output

The suggestion to run `cargo vendor` isn't helpful if you don't already have a Rust toolchain installed. That leaves: "Alternatively, use the pre-vendored `rustc-src` dist component." It's completely unclear to me what this means or how to do it. Perhaps providing a link to documentation would be useful.

**Comment by jyn514** [comment]
Oh this is very funny, `rustc-src` is what rustup calls it, which is of course completely unhelpful in this scenario where you don't have rustup and are building from source.

Mentoring instructions: https://github.com/rust-lang/rust/blob/b56fcb173bbf5ae0a52f26362639b7f2b922e7e9/src/bootstrap/bootstrap.py#L830 should link to https://forge.rust-lang.org/infra/other-installation-methods.html#source-code.

**Comment by jyn514** [comment]
Hmm, I guess for this particular scenario you might be building from a commit other than latest master as well. We do technically package it for individual commits:
```
; curl -I https://ci-artifacts.rust-lang.org/rustc-builds/dd2b19539ea4d62a150cf13d45942e58b6b44e54/rustc-nightly-src.tar.xz | head -n1
HTTP/2 200 
```
but AFAIK that isn't documented anywhere. Maybe we should add it to forge?

**Comment by MoskalykA** [comment]
hello, i'm taking the liberty of claiming this pull request, but I'd like some information. Should I propose a solution (like the curl command with the right url?) or just propose the documentation page?
