### ISSUE TITLE
LTO=thin appears broken on nightly rustc?

### ISSUE THREAD

**Issue by allight** [rust-lang/rust#110256]
When building https://github.com/alacritty/alacritty with `cargo build -r` on nightly rust the resulting binary will segfault. This does not occur when built with stable rust.

This behavior change appears to be gated by lto="thin".

### Code

I tried this code:

```sh
rustup default nightly
rustup update
git clone https://github.com/alacritty/alacritty
cd alacritty
cargo build -r
./target/release/alacritty
```

I expected to see this happen: alacritty to startup as occurs with `rustup default stable`

Instead, this happened: compiled program segfaults

### Version it worked on

   stable-x86_64-unknown-linux-gnu unchanged - rustc 1.68.2 (9eb3afe9e 2023-03-27)

### Version with regression

  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.70.0-nightly (9df3a39fb 2023-04-11)

`rustc --version --verbose`:
```
rustc 1.70.0-nightly (9df3a39fb 2023-04-11)
binary: rustc
commit-hash: 9df3a39fb30575d808e70800f9fad5362aac57a2
commit-date: 2023-04-11
host: x86_64-unknown-linux-gnu
release: 1.70.0-nightly
LLVM version: 16.0.2
```

</p>
</details>

This appears to be triggered by lto being set to "thin" in Cargo.toml 

See alacritty issues: https://github.com/alacritty/alacritty/issues/6818 and https://github.com/alacritty/alacritty/issues/6854 for investigation.

**Comment by allight** [comment]
NB This also appears to require that optimization is turned on to reproduce.

**Comment by matthiaskrgr** [comment]
Hm fun, I can reproduce this with `cargo build --release` in alacritty git on x86

**Comment by matthiaskrgr** [comment]
I tried to bisect this
````
# 04.11:  bad
# 04.08 : bad

# 04.01: bad 
# 03.27: bad  
# 03:26: bad
# 03:25: good
# 03.20: good 
````
and t looks like this regressed in nightly-2023-03-26, so probably llvm upgrade? rip :(

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23110256.20LTO.3Dthin.20appears.20broken.20on.20nightly.20rustc.3F)).

@rustbot label -I-prioritize +P-high

**Comment by DianQK** [comment]
Upstream candidate patch: [D148456](https://reviews.llvm.org/D148456).
Here is a reproduction example.

```rust
fn foo(_b: &[u8]) {}

fn main() {
    let b = Vec::<u8>::new();
    let b = std::borrow::Cow::Borrowed(&b);
    foo(&b);
}
```

```shell
rustc +nightly ./main.rs -C opt-level=1 -C panic=abort -C codegen-units=1
./main
# [1]    619598 illegal hardware instruction (core dumped)  ./main
```

If you change from `&Vec<u8>` to `&[u8]` this will work fine.
```diff
diff --git a/alacritty/src/renderer/text/atlas.rs b/alacritty/src/renderer/text/atlas.rs
index 9d4cb401..f106c8be 100644
--- a/alacritty/src/renderer/text/atlas.rs
+++ b/alacritty/src/renderer/text/atlas.rs
@@ -157,6 +157,7 @@ impl Atlas {
             // Load data into OpenGL.
             let (format, buffer) = match &glyph.buffer {
                 BitmapBuffer::Rgb(buffer) => {
+                    let buffer: &[u8] = buffer;
                     multicolor = false;
                     // Gles context doesn't allow uploading RGB data into RGBA texture, so need
                     // explicit copy.
@@ -175,6 +176,7 @@ impl Atlas {
                 },
                 BitmapBuffer::Rgba(buffer) => {
                     multicolor = true;
+                    let buffer: &[u8] = buffer;
                     (gl::RGBA, Cow::Borrowed(buffer))
                 },
             };
```
