### ISSUE TITLE
Can't unit test procedural macros

### ISSUE THREAD

**Issue by tadaHrd** [rust-lang/rust#110247]
I have this test:
```rust
mod tests {
    use crate::str2code;
    #[test]
    fn test() {
        str2code!(r#"println!("Hello, world!");"#);
    }
}
```
The `str2code` macro is a procedural macro that I made.
```rust
#[proc_macro]
pub fn str2code(input: TokenStream) -> TokenStream
```

It gives this error:
```
error: can't use a procedural macro from the same crate that defines it
  --> src\lib.rs:31:9
   |
31 |         str2code!(r#"println!("Hello, world!");"#);
   |         ^^^^^^^^
```

Why does the compiler not let me test my macros and why does this exist?

**Comment by clubby789** [comment]
Procedural macros are essentially compiler plugins, and need to be compiled before they're used. As the error says, it can't us used within the crate it's defined in. You can instead define your tests in `<project-dir>/tests/<file>.rs`

**Comment by tadaHrd** [comment]
That is kinda stupid

**Comment by clubby789** [comment]
I've opend a PR to note a suggestion for tests
