### ISSUE TITLE
On riscv64gc linux, split-debuginfo ="unpacked" caused error: A dwo section may not contain relocations 

### ISSUE THREAD

**Issue by kxxt** [rust-lang/rust#110224]
### Problem

On riscv64gc linux, split-debuginfo ="unpacked" caused error: A dwo section may not contain relocations.

- For rust > 1.64, this error occurs.
- For rust <=1.64, cargo didn't pass `-C split-debuginfo=unpacked` flag to rustc.
  - For rust 1.64, a segmentation fault happens in rustc.
  - For rust < 1.64, it builds fine

I think the behavior of rust < 1.64 is correct.

### Steps

The following steps:

```bash
cargo new failure
cd failure
echo "[profile.dev]" >> Cargo.toml
echo 'split-debuginfo = "unpacked"' >> Cargo.toml
cargo build
```

caused the following failure:

```bash
Compiling failure v0.1.0 (/root/failure)
error: A dwo section may not contain relocations

error: could not compile `failure` due to previous error
```

### Notes

Related: https://github.com/llvm/llvm-project/issues/56642

### Version

```text
cargo 1.67.1 (8ecd4f20a 2023-01-10)
release: 1.67.1
commit-hash: 8ecd4f20a9efb626975ac18a016d480dc7183d9b
commit-date: 2023-01-10
host: riscv64gc-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:OpenSSL/1.1.1q)
os: Linux [64-bit]
```

**Comment by ehuss** [comment]
Transferred to rust-lang/rust, since this looks to be a compiler issue.

**Comment by jyn514** [comment]
@ehuss https://github.com/llvm/llvm-project/issues/56642#issuecomment-1498471908 says that LLVM doesn't support this combination of flags. It's unclear to me whether it's impossible or just not implemented yet, but in the meantime, cargo should probably stop passing -C split-debuginfo to proc-macros? there's some mention of `-mrelax` in the upstream issue, I'm not sure how that's related.

**Comment by ehuss** [comment]
The report above doesn't mention proc-macros. It seems to happen for normal binaries. The following seems to fail for me:

```
rustc foo.rs -C split-debuginfo=unpacked -C debuginfo=2 --target riscv64gc-unknown-linux-gnu
```

If split-debuginfo isn't supported on this target, then rustc should report that it isn't supported (Cargo already tests for this).  I believe that is defined by the `supported_split_debuginfo` field in the target definition.

**Comment by VorpalBlade** [comment]
I'm getting the same issue with `split-debuginfo = "packed"` when cross compiling for `riscv64gc-unknown-linux-gnu`, it seems to be all values except `off` that causes issues.
