### ISSUE TITLE
str type doesn't implement Default

### ISSUE THREAD

**Issue by Jamzy01** [rust-lang/rust#110261]
I tried this code:

```rust
impl RofCompat for str {
    fn serialize(&self) -> Box<dyn crate::object_format::DataValue> {
        Box::new(DataValueString::from(self))
    }

    fn deserialize(rof_object: Box<dyn crate::object_format::DataValue>) -> Self {
        rof_object.as_string()
    }
}
```

I expected to see this compile, but my RofCompat trait relies on the type also implementing Default. 

This is the implementation I would expect, but I can't implement foreign traits on foreign types because of the chance of collisions:

```rust
impl Default for str {
    fn default() -> &'static str {
        ""
    }
}
```

What confuses me is that I previously implemented the exact same thing on the String type, which does implement Default and it worked fine, this is what leads me to believe that this is a bug.

```rust
impl RofCompat for String {
    fn serialize(&self) -> Box<dyn crate::object_format::DataValue> {
        Box::new(DataValueString::new(self.clone()))
    }

    fn deserialize(rof_object: Box<dyn crate::object_format::DataValue>) -> Self {
        rof_object.as_string()
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.66.0 (69f9c33d7 2022-12-12)
binary: rustc
commit-hash: 69f9c33d71c871fc16ac445211281c6e7a340943
commit-date: 2022-12-12
host: x86_64-pc-windows-msvc
release: 1.66.0
LLVM version: 15.0.2
```

<details><summary>Backtrace</summary>
<p>

```
the trait bound `str: Default` is not satisfied
the following other types implement trait `Default`:
  &mut str
  &str
mod.rs(7, 22): required by a bound in `RofCompat`
```

</p>
</details>

**Comment by compiler-errors** [comment]
Just noting that

```
impl Default for str {
    fn default() -> Self {
        ""
    }
}
```

This impl is not valid, because `""` is a value of type `&'static str` and not `str`.

**Comment by bindsdev** [comment]
Considering that you can't really create a value of type `str` (since it is a DST) reliably, I don't see why there would be a `Default` implementation for it. `String` is a totally different type from `str`, being a owned, heap allocated string, and can be reliably constructed. So, a sensible default for `String` would be an empty "buffer" that hasn't been allocated yet.

**Comment by Nilstrieb** [comment]
`Default`, requires `-> Self`, and we don't have unsized return types, so this impl cannot work.

**Comment by Jamzy01** [comment]
> `Default`, requires `-> Self`, and we don't have unsized return types, so this impl cannot work.
