### ISSUE TITLE
Outdated documentation for feature `lang_items`

### ISSUE THREAD

**Issue by kadiwa4** [rust-lang/rust#110274]
### Location

[`src/doc/unstable-book/src/language-features/lang-items.md`](https://github.com/rust-lang/rust/blob/master/src/doc/unstable-book/src/language-features/lang-items.md) or https://doc.rust-lang.org/unstable-book/language-features/lang-items.html

### Summary

The examples don't compile and the list of `lang` items is outdated.

Should the list at the bottom of the page still be updated? The amount of language items has grown and there's already a list [here in the source code](https://github.com/rust-lang/rust/blob/master/compiler/rustc_hir/src/lang_items.rs#L148).

**Comment by jyn514** [comment]
I think linking to the source code is better than trying to keep the list up to date, yes. We might still want to document the language items that are required for a `no_std` binary, since those are "user facing" in a way the others aren't.

**Comment by jyn514** [comment]
Ideally we could find a way to run rustdoc on the examples (as doctests) so they don't get outdated.

**Comment by kadiwa4** [comment]
The `no_std` guidance could be added to the nomicon because there's already [a page there](https://github.com/rust-lang/nomicon/blob/master/src/beneath-std.md).
