### ISSUE TITLE
in build.rs, `rustc-link-lib=hello` failed on Windows platform

### ISSUE THREAD

**Issue by wangxiaochuTHU** [rust-lang/rust#110384]
My `build.rs` cannot work any more, but it did in some earlier version (Windows Platform).
 
I tried this code in `build.rs`:
```rust
println!("cargo:rustc-link-lib=hello");
```

I expected to see this happen:   **the separator before `libhell.a` is auto-completed by '\\'**
<C:\Users\some-path-to-rustc-link-search>\libhello.a

Instead, this happened: **the separator auto-completed is '/'**
C:/GCC/MinGW-W64/12.2.0-rev3/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\dell\Documents\ProgrammingProjects\Rust\infrared_startracker_validation_rust_mixed_c\src\c\algorithm/libhello.a(kdtree.o):kdtree.c:(.text[_vsnprintf_l]+0x91): undefined reference to `__stdio_common_vsprintf'

### Meta

`rustc --version --verbose`:
```
rustc 1.71.0-nightly (5cdb7886a 2023-04-15)
binary: rustc
commit-hash: 5cdb7886a5ece816864fab177f0c266ad4dd5358
commit-date: 2023-04-15
host: x86_64-pc-windows-gnu
release: 1.71.0-nightly
LLVM version: 16.0.2
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by ChrisDenton** [comment]
It shouldn't matter if `/` is used (although it's more aesthetically pleasing if path separators are consistent).

Are you maybe trying to link a library compiled with msvc? That can be a problem if using gnu.

**Comment by wangxiaochuTHU** [comment]
Thanks for reply.
> It shouldn't matter if `/` is used (although it's more aesthetically pleasing if path separators are consistent).

Fine, great job!
Yes I can see from the build `output` file that all separators look correct (except in one line related to `clang`, which wrote `cargo:rerun-if-changed=C:\Program Files\LLVM\lib\clang\16\include/__stddef_max_align_t.h`).

But it's a little wired that the code below using `.canonicalize()` would error on Windows:
```rust
let libdir_path = PathBuf::from("src")
        .join("c")
        .join("algorithm")
        // Canonicalize the path as `rustc-link-search` requires an absolute path.
        .canonicalize()
        .expect("cannot canonicalize path");
println!("cargo:rustc-link-search={}", libdir_path.to_str().unwrap());
```
errors with (please note `\\?\` before the actual path.)
```
  --- stdout
  cargo:rustc-link-search=\\?\C:\Users\dell\Documents\ProgrammingProjects\Rust\infrared_startracker_validation_rust_mixed_c\src\c\algorithm
  cargo:rustc-link-lib=hello
  cargo:rerun-if-changed=\\?\C:\Users\dell\Documents\ProgrammingProjects\Rust\infrared_startracker_validation_rust_mixed_c\src\c\algorithm\myLib.h 
```
and I have to remove `\\?\` manually to keep the script go on.

> Are you maybe trying to link a library compiled with msvc? That can be a problem if using gnu.

No, msvc doesn't seem to help, error still exits
```
= note: Non-UTF-8 output: LINK : fatal error LNK1181: \xce\xde\xb7\xa8\xb4\xf2\xbf\xaa\xca\xe4\xc8\xeb\xce\xc4\xbc\xfe\xa1\xb0hello.lib\xa1\xb1\r\n 
```

It is strange that the same script went well on Windows several days ago but suddenly failed to build. On Linux, the almost same (because on windows I have to remove `\\?\` from the canonicalized path) build script can always work.

**Comment by ChrisDenton** [comment]
Ok, thanks for the added information. If you're using `\\?\` prefixed paths then, yes, the separator matters.

> It is strange that the same script went well on Windows several days ago but suddenly failed to build

Did you update rust recently?

**Comment by wangxiaochuTHU** [comment]
> Ok, thanks for the added information. If you're using `\\?\` prefixed paths then, yes, the separator matters.
Sorry, I think I've made a mistake and actually the script can never succeed on Windows. Thanks for the guide, I think I'd better run it on Linux only :)
