### ISSUE TITLE
The LLVM we ship in `rust-dev` doesn't match the LLVM we ship in the `rustc` component

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#110474]
I tried this code:

```rust
; rustc +stage2 --print=target-spec-json --target loongarch64-unknown-linux-gnu -Zunstable-options
```

I expected to see this happen: rustc prints the target spec successfully, because it knows it exists:
```
; rustc +stage2 --print=target-list | grep loong
loongarch64-unknown-linux-gnu
```

Instead, this happened: rustc fails to load the LLVM specification:
```
; rustc +stage2 --print=target-spec-json --target loongarch64-unknown-linux-gnu -Zunstable-options
error: could not create LLVM TargetMachine for triple: loongarch64-unknown-linux-gnu: No available targets are compatible with triple "loongarch64-unknown-linux-gnu"
```

Note that this is different from the error we emit for an unrecognized target:
```
; rustc +stage2 --print=target-spec-json --target unknown -Zunstable-options
error: Error loading target specification: Could not find specification for target "unknown". Run `rustc --print target-list` for a list of built-in targets
```

Also, this only happens for local builds, because we don't use the LLVM in the `rust-dev` component in rustup, only when building rustc from source.

... wtf ???

### Meta

HEAD is branched from ce1073ba9d894b2e351b2a85fcd39f2c99b78974

**Comment by jyn514** [comment]
cc @zhaixiaojuan @heiher, do you know what could be going wrong here?

**Comment by heiher** [comment]
@jyn514 Thank you for bringing this to my attention. It is possible that the locally builds has enabled llvm.download-ci-llvm, and that prebuilt LLVM does not support LoongArch architecture. It would be great if you could provide specific steps to reproduce. Thank you.

**Comment by jyn514** [comment]
Yes, that's exactly what's happened, I have download-ci-llvm enabled and the prebuilt LLVM differs.

Here's steps to reproduce:
```
rm config.toml  # download-ci-llvm is on by default
x build --stage 0 rustc
build/host/stage1/bin/rustc --print=target-spec-json --target loongarch64-unknown-linux-gnu -Zunstable-options
```

**Comment by jyn514** [comment]
The RustDev component builds LLVM here: https://github.com/rust-lang/rust/blob/276fa294809e914b1d04192392d256814aa5ce1a/src/bootstrap/dist.rs#L2239
but I'm not sure how that differs from the `Rustc` component? https://github.com/rust-lang/rust/blob/276fa294809e914b1d04192392d256814aa5ce1a/src/bootstrap/dist.rs#L456-L461

**Comment by heiher** [comment]
I think the difference is that the `llvm.targets` of ci-llvm does not contain LoongArch, but locally it does. Is it time to update ci-llvm?

**Comment by nikic** [comment]
Maybe need to bump download-ci-llvm-stamp to pick up the LoongArch enablement?

**Comment by jyn514** [comment]
@heiher no worries :) it updates every six weeks when we make a new release, or if the submodule is updated, but it's cached until then so it's not constantly re-uploaded on every change to bootstrap.

**Comment by jyn514** [comment]
@RalfJung we can use heuristics, but they're *only* heuristics and I wouldn't want to fail CI on them. That said, having rustbot leave a comment if you touch rustc_llvm or src/bootstrap/llvm.rs seems reasonable, so the PR author can make a judgement call but also doesn't forget about the stamp.
