### ISSUE TITLE
ICE: thread 'rustc' panicked at 'DefId(2:4314 ~ core[ecd7]::cell::Ref::'b) does not have a "def_span"'

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#110464]
cc @compiler-errors 
still crashes after https://github.com/rust-lang/rust/pull/110425 

### Code

```Rust
impl<'a, 'tcx> std::cell::Ref<'a, 'tcx> {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.71.0-nightly (31656e729 2023-04-17)
binary: rustc
commit-hash: 31656e7295ebd5f2f6597f10c011e2ac4ba3ef39
commit-date: 2023-04-17
host: x86_64-unknown-linux-gnu
release: 1.71.0-nightly
LLVM version: 16.0.2
```

### Error output

```
error[E0601]: `main` function not found in crate `treereduce`
 --> treereduce.out:1:43
  |
1 | impl<'a, 'tcx> std::cell::Ref<'a, 'tcx> {}
  |                                           ^ consider adding a `main` function to `treereduce.out`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'DefId(2:4314 ~ core[ecd7]::cell::Ref::'b) does not have a "def_span"', compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs:205:1
stack backtrace:
   0:     0x7f4ead3653c2 - std::backtrace_rs::backtrace::libunwind::trace::h12fb0181e6282928
                               at /rustc/31656e7295ebd5f2f6597f10c011e2ac4ba3ef39/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f4ead3653c2 - std::backtrace_rs::backtrace::trace_unsynchronized::hd58a23b488ab4414
                               at /rustc/31656e7295ebd5f2f6597f10c011e2ac4ba3ef39/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f4ead3653c2 - std::sys_common::backtrace::_print_fmt::h1e92ee6e175ed435
                               at /rustc/31656e7295ebd5f2f6597f10c011e2ac4ba3ef39/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f4ead3653c2 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he25ddff8a40f4065
                               at /rustc/31656e7295ebd5f2f6597f10c011e2ac4ba3ef39/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f4ead3c95df - core::fmt::write::h2334c3311cfbc09f
                               at /rustc/31656e7295ebd5f2f6597f10c011e2ac4ba3ef39/library/core/src/fmt/mod.rs:1254:17
   5:     0x7f4ead358371 - std::io::Write::write_fmt::h32ceba1e85ba39af
                               at /rustc/31656e7295ebd5f2f6597f10c011e2ac4ba3ef39/library/std/src/io/mod.rs:1698:15
   6:     0x7f4ead3651c5 - std::sys_common::backtrace::_print::headbc582bfe8f74f
                               at /rustc/31656e7295ebd5f2f6597f10c011e2ac4ba3ef39/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f4ead3651c5 - std::sys_common::backtrace::print::h9fbeedaf474e45ad
                               at /rustc/31656e7295ebd5f2f6597f10c011e2ac4ba3ef39/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f4ead367e87 - std::panicking::default_hook::{{closure}}::hff4b7a4e67c75e45
   9:     0x7f4ead367c75 - std::panicking::default_hook::h2ca9686b025551a8
                               at /rustc/31656e7295ebd5f2f6597f10c011e2ac4ba3ef39/library/std/src/panicking.rs:288:9
  10:     0x7f4eb0631d45 - <rustc_driver_impl[19ce8278adc32abb]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[ecd79567034e570c]::ops::function::FnOnce<(&core[ecd79567034e570c]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f4ead3685c5 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h97aef67d40dea969
                               at /rustc/31656e7295ebd5f2f6597f10c011e2ac4ba3ef39/library/alloc/src/boxed.rs:1987:9
  12:     0x7f4ead3685c5 - std::panicking::rust_panic_with_hook::h8edf350457ba7c57
                               at /rustc/31656e7295ebd5f2f6597f10c011e2ac4ba3ef39/library/std/src/panicking.rs:695:13
  13:     0x7f4ead368339 - std::panicking::begin_panic_handler::{{closure}}::h2bd4d1302fd9063e
                               at /rustc/31656e7295ebd5f2f6597f10c011e2ac4ba3ef39/library/std/src/panicking.rs:582:13
  14:     0x7f4ead365806 - std::sys_common::backtrace::__rust_end_short_backtrace::h30f581c97642f13f
                               at /rustc/31656e7295ebd5f2f6597f10c011e2ac4ba3ef39/library/std/src/sys_common/backtrace.rs:150:18
  15:     0x7f4ead368092 - rust_begin_unwind
                               at /rustc/31656e7295ebd5f2f6597f10c011e2ac4ba3ef39/library/std/src/panicking.rs:578:5
  16:     0x7f4ead3c5953 - core::panicking::panic_fmt::h1e15b8ac1469fe52
                               at /rustc/31656e7295ebd5f2f6597f10c011e2ac4ba3ef39/library/core/src/panicking.rs:67:14
  17:     0x7f4eb0a5e312 - rustc_metadata[572c2c8f30736a78]::rmeta::decoder::cstore_impl::provide_extern::def_span::{closure#2}
  18:     0x7f4eaf123c02 - rustc_query_system[8013f3037cfe4f42]::query::plumbing::try_execute_query::<rustc_query_impl[d100f3cda631c9d2]::queries::def_span, rustc_query_impl[d100f3cda631c9d2]::plumbing::QueryCtxt>
  19:     0x7f4eaf12208a - <rustc_query_impl[d100f3cda631c9d2]::Queries as rustc_middle[a098ebc07bc191ee]::ty::query::QueryEngine>::def_span
  20:     0x7f4eb070f924 - <&mut <rustc_hir_analysis[18d38fd7f32cb571]::structured_errors::wrong_number_of_generic_args::WrongNumberOfGenericArgs>::show_definition::{closure#0} as core[ecd79567034e570c]::ops::function::FnOnce<(&rustc_middle[a098ebc07bc191ee]::ty::generics::GenericParamDef,)>>::call_once
  21:     0x7f4eb077fd6c - <alloc[b29edc6afdbb639a]::vec::Vec<alloc[b29edc6afdbb639a]::string::String> as alloc[b29edc6afdbb639a]::vec::spec_from_iter::SpecFromIter<alloc[b29edc6afdbb639a]::string::String, core[ecd79567034e570c]::iter::adapters::map::Map<core[ecd79567034e570c]::iter::adapters::map::Map<core[ecd79567034e570c]::iter::adapters::take::Take<core[ecd79567034e570c]::iter::adapters::skip::Skip<core[ecd79567034e570c]::slice::iter::Iter<rustc_middle[a098ebc07bc191ee]::ty::generics::GenericParamDef>>>, <rustc_hir_analysis[18d38fd7f32cb571]::structured_errors::wrong_number_of_generic_args::WrongNumberOfGenericArgs>::show_definition::{closure#0}>, <rustc_hir_analysis[18d38fd7f32cb571]::structured_errors::wrong_number_of_generic_args::WrongNumberOfGenericArgs>::show_definition::{closure#1}>>>::from_iter
  22:     0x7f4eb0714480 - <rustc_hir_analysis[18d38fd7f32cb571]::structured_errors::wrong_number_of_generic_args::WrongNumberOfGenericArgs as rustc_hir_analysis[18d38fd7f32cb571]::structured_errors::StructuredDiagnostic>::diagnostic_common
  23:     0x7f4eb0715af2 - <rustc_hir_analysis[18d38fd7f32cb571]::structured_errors::wrong_number_of_generic_args::WrongNumberOfGenericArgs as rustc_hir_analysis[18d38fd7f32cb571]::structured_errors::StructuredDiagnostic>::diagnostic
  24:     0x7f4eaf47b4c4 - <dyn rustc_hir_analysis[18d38fd7f32cb571]::astconv::AstConv>::res_to_ty
  25:     0x7f4eaf46ff80 - <dyn rustc_hir_analysis[18d38fd7f32cb571]::astconv::AstConv>::ast_ty_to_ty_inner::{closure#0}
  26:     0x7f4eaf96bbe2 - rustc_hir_analysis[18d38fd7f32cb571]::collect::type_of::type_of
  27:     0x7f4eaec3040d - rustc_query_system[8013f3037cfe4f42]::query::plumbing::try_execute_query::<rustc_query_impl[d100f3cda631c9d2]::queries::type_of, rustc_query_impl[d100f3cda631c9d2]::plumbing::QueryCtxt>
  28:     0x7f4eaec2f72f - <rustc_query_impl[d100f3cda631c9d2]::Queries as rustc_middle[a098ebc07bc191ee]::ty::query::QueryEngine>::type_of
  29:     0x7f4eae9ed2fc - <rustc_hir_analysis[18d38fd7f32cb571]::collect::CollectItemTypesVisitor as rustc_hir[884f393f1859d8a7]::intravisit::Visitor>::visit_item
  30:     0x7f4eae9eb6c2 - <rustc_middle[a098ebc07bc191ee]::hir::map::Map>::visit_item_likes_in_module::<rustc_hir_analysis[18d38fd7f32cb571]::collect::CollectItemTypesVisitor>
  31:     0x7f4eae9eb5ec - rustc_hir_analysis[18d38fd7f32cb571]::collect::collect_mod_item_types
  32:     0x7f4eafc65321 - rustc_query_system[8013f3037cfe4f42]::query::plumbing::try_execute_query::<rustc_query_impl[d100f3cda631c9d2]::queries::collect_mod_item_types, rustc_query_impl[d100f3cda631c9d2]::plumbing::QueryCtxt>
  33:     0x7f4eafc64f49 - <rustc_query_impl[d100f3cda631c9d2]::Queries as rustc_middle[a098ebc07bc191ee]::ty::query::QueryEngine>::collect_mod_item_types
  34:     0x7f4eafa0467c - <rustc_middle[a098ebc07bc191ee]::hir::map::Map>::for_each_module::<rustc_hir_analysis[18d38fd7f32cb571]::check_crate::{closure#0}::{closure#0}::{closure#0}>
  35:     0x7f4eafa008cc - rustc_hir_analysis[18d38fd7f32cb571]::check_crate
  36:     0x7f4eaf9fad1d - rustc_interface[e2b40ad4e6aa2c15]::passes::analysis
  37:     0x7f4eafd9a562 - rustc_query_system[8013f3037cfe4f42]::query::plumbing::try_execute_query::<rustc_query_impl[d100f3cda631c9d2]::queries::analysis, rustc_query_impl[d100f3cda631c9d2]::plumbing::QueryCtxt>
  38:     0x7f4eafd9a270 - <rustc_query_impl[d100f3cda631c9d2]::Queries as rustc_middle[a098ebc07bc191ee]::ty::query::QueryEngine>::analysis
  39:     0x7f4eafc5e8e6 - <std[44a4f6cc0231f9b2]::thread::local::LocalKey<core[ecd79567034e570c]::cell::Cell<*const ()>>>::with::<rustc_middle[a098ebc07bc191ee]::ty::context::tls::enter_context<<rustc_middle[a098ebc07bc191ee]::ty::context::GlobalCtxt>::enter<rustc_driver_impl[19ce8278adc32abb]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[ecd79567034e570c]::result::Result<(), rustc_span[bacfd568afc27ca7]::ErrorGuaranteed>>::{closure#0}, core[ecd79567034e570c]::result::Result<(), rustc_span[bacfd568afc27ca7]::ErrorGuaranteed>>::{closure#0}, core[ecd79567034e570c]::result::Result<(), rustc_span[bacfd568afc27ca7]::ErrorGuaranteed>>
  40:     0x7f4eaf81da67 - <rustc_interface[e2b40ad4e6aa2c15]::interface::Compiler>::enter::<rustc_driver_impl[19ce8278adc32abb]::run_compiler::{closure#1}::{closure#2}, core[ecd79567034e570c]::result::Result<core[ecd79567034e570c]::option::Option<rustc_interface[e2b40ad4e6aa2c15]::queries::Linker>, rustc_span[bacfd568afc27ca7]::ErrorGuaranteed>>
  41:     0x7f4eaf817b4f - rustc_span[bacfd568afc27ca7]::set_source_map::<core[ecd79567034e570c]::result::Result<(), rustc_span[bacfd568afc27ca7]::ErrorGuaranteed>, rustc_interface[e2b40ad4e6aa2c15]::interface::run_compiler<core[ecd79567034e570c]::result::Result<(), rustc_span[bacfd568afc27ca7]::ErrorGuaranteed>, rustc_driver_impl[19ce8278adc32abb]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  42:     0x7f4eaf817768 - <scoped_tls[41028e5492da81b4]::ScopedKey<rustc_span[bacfd568afc27ca7]::SessionGlobals>>::set::<rustc_interface[e2b40ad4e6aa2c15]::interface::run_compiler<core[ecd79567034e570c]::result::Result<(), rustc_span[bacfd568afc27ca7]::ErrorGuaranteed>, rustc_driver_impl[19ce8278adc32abb]::run_compiler::{closure#1}>::{closure#0}, core[ecd79567034e570c]::result::Result<(), rustc_span[bacfd568afc27ca7]::ErrorGuaranteed>>
  43:     0x7f4eaf816d7b - std[44a4f6cc0231f9b2]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[e2b40ad4e6aa2c15]::util::run_in_thread_pool_with_globals<rustc_interface[e2b40ad4e6aa2c15]::interface::run_compiler<core[ecd79567034e570c]::result::Result<(), rustc_span[bacfd568afc27ca7]::ErrorGuaranteed>, rustc_driver_impl[19ce8278adc32abb]::run_compiler::{closure#1}>::{closure#0}, core[ecd79567034e570c]::result::Result<(), rustc_span[bacfd568afc27ca7]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[ecd79567034e570c]::result::Result<(), rustc_span[bacfd568afc27ca7]::ErrorGuaranteed>>
  44:     0x7f4eafef9161 - <<std[44a4f6cc0231f9b2]::thread::Builder>::spawn_unchecked_<rustc_interface[e2b40ad4e6aa2c15]::util::run_in_thread_pool_with_globals<rustc_interface[e2b40ad4e6aa2c15]::interface::run_compiler<core[ecd79567034e570c]::result::Result<(), rustc_span[bacfd568afc27ca7]::ErrorGuaranteed>, rustc_driver_impl[19ce8278adc32abb]::run_compiler::{closure#1}>::{closure#0}, core[ecd79567034e570c]::result::Result<(), rustc_span[bacfd568afc27ca7]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[ecd79567034e570c]::result::Result<(), rustc_span[bacfd568afc27ca7]::ErrorGuaranteed>>::{closure#1} as core[ecd79567034e570c]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  45:     0x7f4ead372a85 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf699fb692a362d4f
                               at /rustc/31656e7295ebd5f2f6597f10c011e2ac4ba3ef39/library/alloc/src/boxed.rs:1973:9
  46:     0x7f4ead372a85 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h5785a67d99b09647
                               at /rustc/31656e7295ebd5f2f6597f10c011e2ac4ba3ef39/library/alloc/src/boxed.rs:1973:9
  47:     0x7f4ead372a85 - std::sys::unix::thread::Thread::new::thread_start::hd8d3f6147809d6cf
                               at /rustc/31656e7295ebd5f2f6597f10c011e2ac4ba3ef39/library/std/src/sys/unix/thread.rs:108:17
  48:     0x7f4ead10dbb5 - <unknown>
  49:     0x7f4ead18fd90 - <unknown>
  50:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.71.0-nightly (31656e729 2023-04-17) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [def_span] looking up span for `core::cell::Ref::'b`
#1 [type_of] computing type of `<impl at treereduce.out:1:1: 1:40>`
#2 [collect_mod_item_types] collecting item types in top-level module
#3 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error

For more information about this error, try `rustc --explain E0601`.
```

</p>
</details>

**Comment by compiler-errors** [comment]
Sigh, yeah, this is just the same bug but for lifetime params. I'll fix it, shouldn't be too hard.

@rustbot claim

**Comment by yotamofek** [comment]
Hey, @compiler-errors , thanks for getting this fixed!
Unfortunately, I seem to be running into the same issue (or a very similar one) using the latest nightly, and I've not been able to create a standalone reproducer:

```
thread 'rustc' panicked at 'DefId(282:830 ~ web_ws_handlers[895f]::handler::Handler::call::{opaque#0}) does not have a "def_span"', compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs:205:1
```

<details><summary>Backtrace</summary>
<p>

stack backtrace:
   0:     0x7f2dbb878331 - std::backtrace_rs::backtrace::libunwind::trace::h8355d489046eea9f
                               at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f2dbb878331 - std::backtrace_rs::backtrace::trace_unsynchronized::h5224130277357a26
                               at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f2dbb878331 - std::sys_common::backtrace::_print_fmt::hecc97c6ada6b37c5
                               at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f2dbb878331 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha40fb82141ca69c7
                               at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f2dbb8d8f1f - core::fmt::rt::Argument::fmt::h3abab6d788a756e3
                               at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/core/src/fmt/rt.rs:138:9
   5:     0x7f2dbb8d8f1f - core::fmt::write::h0d9c37369cab45ae
                               at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f2dbb86b4a1 - std::io::Write::write_fmt::h48802cd26188edd4
                               at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/std/src/io/mod.rs:1712:15
   7:     0x7f2dbb878145 - std::sys_common::backtrace::_print::hd06dedc75707c8aa
                               at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f2dbb878145 - std::sys_common::backtrace::print::he87158405a814203
                               at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f2dbb87ac87 - std::panicking::default_hook::{{closure}}::hed443a04a4ae9143
  10:     0x7f2dbb87aa74 - std::panicking::default_hook::hcb7845fe9b5159b6
                               at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/std/src/panicking.rs:288:9
  11:     0x7f2dbeafb015 - rustc_driver_impl[738786893c5490bf]::DEFAULT_HOOK::{closure#0}::{closure#0}
  12:     0x7f2dbb87b3a7 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h1480dd017092d509
                               at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/alloc/src/boxed.rs:1976:9
  13:     0x7f2dbb87b3a7 - std::panicking::rust_panic_with_hook::he4834f7686de7b98
                               at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/std/src/panicking.rs:695:13
  14:     0x7f2dbb87b127 - std::panicking::begin_panic_handler::{{closure}}::ha2d182560a0fb060
                               at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/std/src/panicking.rs:582:13
  15:     0x7f2dbb878776 - std::sys_common::backtrace::__rust_end_short_backtrace::h2df9d74a88462a94
                               at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/std/src/sys_common/backtrace.rs:150:18
  16:     0x7f2dbb87ae92 - rust_begin_unwind
                               at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/std/src/panicking.rs:578:5
  17:     0x7f2dbb8d51c3 - core::panicking::panic_fmt::hdf51123d3e5c1099
                               at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/core/src/panicking.rs:67:14
  18:     0x7f2dbef37e82 - rustc_metadata[ae0e66a2a2c113fb]::rmeta::decoder::cstore_impl::provide_extern::def_span::{closure#2}
  19:     0x7f2dbe434f26 - rustc_metadata[ae0e66a2a2c113fb]::rmeta::decoder::cstore_impl::provide_extern::def_span
  20:     0x7f2dbd3c50ed - rustc_query_system[34a9c542073df]::query::plumbing::try_execute_query::<rustc_query_impl[5c8c89bc676e7b7e]::queries::def_span, rustc_query_impl[5c8c89bc676e7b7e]::plumbing::QueryCtxt>
  21:     0x7f2dbd3c296a - <rustc_query_impl[5c8c89bc676e7b7e]::Queries as rustc_middle[4a9d2aea1650cf38]::ty::query::QueryEngine>::def_span
  22:     0x7f2dbd0edefa - <rustc_infer[5d7b6307277651b3]::infer::InferCtxt>::infer_projection
  23:     0x7f2dbd0d890c - rustc_trait_selection[87bbd939b3c90e9c]::traits::project::normalize_projection_type
  24:     0x7f2dbd0d6365 - <rustc_trait_selection[87bbd939b3c90e9c]::traits::project::AssocTypeNormalizer as rustc_type_ir[1d3e9495482829d7]::fold::TypeFolder<rustc_middle[4a9d2aea1650cf38]::ty::context::TyCtxt>>::fold_ty
  25:     0x7f2dbdc992cc - rustc_middle[4a9d2aea1650cf38]::ty::util::fold_list::<rustc_trait_selection[87bbd939b3c90e9c]::traits::project::AssocTypeNormalizer, rustc_middle[4a9d2aea1650cf38]::ty::Ty, <&rustc_middle[4a9d2aea1650cf38]::ty::list::List<rustc_middle[4a9d2aea1650cf38]::ty::Ty> as rustc_type_ir[1d3e9495482829d7]::fold::TypeFoldable<rustc_middle[4a9d2aea1650cf38]::ty::context::TyCtxt>>::try_fold_with<rustc_trait_selection[87bbd939b3c90e9c]::traits::project::AssocTypeNormalizer>::{closure#0}>
  26:     0x7f2dbcce8c70 - <rustc_infer[5d7b6307277651b3]::infer::at::At as rustc_trait_selection[87bbd939b3c90e9c]::traits::project::NormalizeExt>::normalize::<rustc_middle[4a9d2aea1650cf38]::ty::sty::FnSig>
  27:     0x7f2dbcccd187 - <rustc_hir_typeck[e3c70be22799a2fb]::fn_ctxt::FnCtxt>::check_call
  28:     0x7f2dbd19d99a - <rustc_hir_typeck[e3c70be22799a2fb]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  29:     0x7f2dbd19dfa1 - <rustc_hir_typeck[e3c70be22799a2fb]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  30:     0x7f2dbd19dfa1 - <rustc_hir_typeck[e3c70be22799a2fb]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  31:     0x7f2dbd1f7c0a - <rustc_hir_typeck[e3c70be22799a2fb]::fn_ctxt::FnCtxt>::check_decl
  32:     0x7f2dbd1f373d - <rustc_hir_typeck[e3c70be22799a2fb]::fn_ctxt::FnCtxt>::check_block_with_expected
  33:     0x7f2dbd19df24 - <rustc_hir_typeck[e3c70be22799a2fb]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  34:     0x7f2dbd20fcce - <rustc_hir_typeck[e3c70be22799a2fb]::fn_ctxt::FnCtxt>::check_match::{closure#0}
  35:     0x7f2dbd19f460 - <rustc_hir_typeck[e3c70be22799a2fb]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  36:     0x7f2dbd1f363b - <rustc_hir_typeck[e3c70be22799a2fb]::fn_ctxt::FnCtxt>::check_block_with_expected
  37:     0x7f2dbd19df24 - <rustc_hir_typeck[e3c70be22799a2fb]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  38:     0x7f2dbd376d86 - <rustc_hir_typeck[e3c70be22799a2fb]::fn_ctxt::FnCtxt>::check_return_expr
  39:     0x7f2dbd36e51e - rustc_hir_typeck[e3c70be22799a2fb]::check::check_fn
  40:     0x7f2dbd3574ea - rustc_hir_typeck[e3c70be22799a2fb]::typeck
  41:     0x7f2dbd34c9c9 - rustc_query_system[34a9c542073df]::query::plumbing::try_execute_query::<rustc_query_impl[5c8c89bc676e7b7e]::queries::typeck, rustc_query_impl[5c8c89bc676e7b7e]::plumbing::QueryCtxt>
  42:     0x7f2dbe40905a - rustc_hir_typeck[e3c70be22799a2fb]::used_trait_imports
  43:     0x7f2dbd731aac - rustc_query_system[34a9c542073df]::query::plumbing::try_execute_query::<rustc_query_impl[5c8c89bc676e7b7e]::queries::used_trait_imports, rustc_query_impl[5c8c89bc676e7b7e]::plumbing::QueryCtxt>
  44:     0x7f2dbdf738d3 - rustc_hir_analysis[505c17fd5083e6d3]::check_crate
  45:     0x7f2dbdf666fe - rustc_interface[1da25c7cb643f6df]::passes::analysis
  46:     0x7f2dbe277cef - rustc_query_system[34a9c542073df]::query::plumbing::try_execute_query::<rustc_query_impl[5c8c89bc676e7b7e]::queries::analysis, rustc_query_impl[5c8c89bc676e7b7e]::plumbing::QueryCtxt>
  47:     0x7f2dbe277820 - <rustc_query_impl[5c8c89bc676e7b7e]::Queries as rustc_middle[4a9d2aea1650cf38]::ty::query::QueryEngine>::analysis
  48:     0x7f2dbdd1c86a - <rustc_middle[4a9d2aea1650cf38]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[738786893c5490bf]::run_compiler::{closure#1}::{closure#2}::{closure#4}, core[af2acebbc2b23591]::result::Result<(), rustc_span[8cddaddefb760954]::ErrorGuaranteed>>
  49:     0x7f2dbdd1bb6a - <rustc_interface[1da25c7cb643f6df]::interface::Compiler>::enter::<rustc_driver_impl[738786893c5490bf]::run_compiler::{closure#1}::{closure#2}, core[af2acebbc2b23591]::result::Result<core[af2acebbc2b23591]::option::Option<rustc_interface[1da25c7cb643f6df]::queries::Linker>, rustc_span[8cddaddefb760954]::ErrorGuaranteed>>
  50:     0x7f2dbdd19bc1 - rustc_span[8cddaddefb760954]::set_source_map::<core[af2acebbc2b23591]::result::Result<(), rustc_span[8cddaddefb760954]::ErrorGuaranteed>, rustc_interface[1da25c7cb643f6df]::interface::run_compiler<core[af2acebbc2b23591]::result::Result<(), rustc_span[8cddaddefb760954]::ErrorGuaranteed>, rustc_driver_impl[738786893c5490bf]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  51:     0x7f2dbdd19267 - std[b167bfecd85c8427]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[1da25c7cb643f6df]::util::run_in_thread_pool_with_globals<rustc_interface[1da25c7cb643f6df]::interface::run_compiler<core[af2acebbc2b23591]::result::Result<(), rustc_span[8cddaddefb760954]::ErrorGuaranteed>, rustc_driver_impl[738786893c5490bf]::run_compiler::{closure#1}>::{closure#0}, core[af2acebbc2b23591]::result::Result<(), rustc_span[8cddaddefb760954]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[af2acebbc2b23591]::result::Result<(), rustc_span[8cddaddefb760954]::ErrorGuaranteed>>
  52:     0x7f2dbdd18b85 - <<std[b167bfecd85c8427]::thread::Builder>::spawn_unchecked_<rustc_interface[1da25c7cb643f6df]::util::run_in_thread_pool_with_globals<rustc_interface[1da25c7cb643f6df]::interface::run_compiler<core[af2acebbc2b23591]::result::Result<(), rustc_span[8cddaddefb760954]::ErrorGuaranteed>, rustc_driver_impl[738786893c5490bf]::run_compiler::{closure#1}>::{closure#0}, core[af2acebbc2b23591]::result::Result<(), rustc_span[8cddaddefb760954]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[af2acebbc2b23591]::result::Result<(), rustc_span[8cddaddefb760954]::ErrorGuaranteed>>::{closure#1} as core[af2acebbc2b23591]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  53:     0x7f2dbb8858c5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha80838fe840f5c99
                               at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/alloc/src/boxed.rs:1962:9
  54:     0x7f2dbb8858c5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb7b8292ae0f012c1
                               at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/alloc/src/boxed.rs:1962:9
  55:     0x7f2dbb8858c5 - std::sys::unix::thread::Thread::new::thread_start::h64b218fd2c840776
                               at /rustc/87b1f891ea76713462cfc5a15137a8fe2b24ecc2/library/std/src/sys/unix/thread.rs:108:17
  56:     0x7f2dbb5d2b43 - start_thread
                               at ./nptl/pthread_create.c:442:8
  57:     0x7f2dbb664a00 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  58:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.71.0-nightly (87b1f891e 2023-04-29) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED] -C link-arg=-fuse-ld=lld

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [def_span] looking up span for `web_ws_handlers::handler::Handler::call::{opaque#0}`
#1 [typeck] type-checking `ws::spawn_request_handler`
#2 [used_trait_imports] finding used_trait_imports `ws::spawn_request_handler`
#3 [analysis] running analysis passes on this crate
end of query stack

</p>
</details> 

Sorry if this is the wrong place to be reporting this ICE, but I wasn't sure whether to file a new issue or maybe get one of the resolved issues re-opened.

Thanks you!
