### ISSUE TITLE
rustbuild: some x.py targets no longer print their dependencies being built

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#110506]
When running `x.py install` for example, x.py would previously show the build (cargo) output when building cargo during `x.py install`, but that is no longer the case. Is that intentional?

````
....
Uplifting rustc (stage1 -> stage3)
Building tool cargo (stage2 -> stage3)
Building tool cargo-credential-1password (stage2 -> stage3)
Dist cargo-1.71.0-dev-x86_64-unknown-linux-gnu
	finished in 2.176 seconds
Install cargo stage2 (Some(x86_64-unknown-linux-gnu))
````

**Comment by albertlarsan68** [comment]
It's not intentional AFAIK, but I don't see a recent PR that could have broken this off the top of my head.
Do you have a commit/timeframe where this worked correctly?

**Comment by matthiaskrgr** [comment]
Hmm I would guess it still worked last weekend?

**Comment by jyn514** [comment]
Are you sure cargo is actually being built? `stage2 -> stage3` makes me think it's using cached stage 2 artifacts.

**Comment by matthiaskrgr** [comment]
Might be 103ed0e5c800f87a27fe9c85902e8e6a3f443b52

**Comment by matthiaskrgr** [comment]
Yes, I can see rustc building cargo and its deps in htop while x.py does not print any updates :sweat_smile:

**Comment by jyn514** [comment]
oh lol that would do it

cc @weihanglo

**Comment by weihanglo** [comment]
Sounds like we do need `stream_cargo` there? I'll put it back then!

**Comment by albertlarsan68** [comment]
Is there not a `try_run` way of doing things?

**Comment by jyn514** [comment]
Yes, there's a try_run, that would be best.
