### ISSUE TITLE
Codegen regression involving `assume`/`unreachable_unchecked`

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#110551]
### Code

I tried this code:

```rust
pub fn f(a: Option<u32>) -> u32 {
    match a {
        None => {}
        Some(_) => unsafe { std::hint::unreachable_unchecked() }
    }

    a.unwrap()
}
```

I expected to see this happen: no branch instructions emitted, `unreachable_unchecked` makes an assumption that `a` is `None`, so `unwrap` should be inlined and optimized as a panic.

Instead, this happened: there is a discriminant check still emitted.

### Version it worked on

It most recently worked on: nightly-2023-03-26

### Version with regression

```
; rustc +nightly-2023-03-27 --version --verbose
rustc 1.70.0-nightly (db0cbc48d 2023-03-26)
binary: rustc
commit-hash: db0cbc48d4aaa300713a95d9b317a365a474490c
commit-date: 2023-03-26
host: aarch64-unknown-linux-gnu
release: 1.70.0-nightly
LLVM version: 16.0.0
```

## ASM diff

See godbolt: https://godbolt.org/z/5WKTY99Te

## Bisection results

Regression occurred in #106428 (cc @saethlin).

searched nightlies: from nightly-2023-03-01 to nightly-2023-04-01
regressed nightly: nightly-2023-03-27
searched commit range: https://github.com/rust-lang/rust/compare/0c61c7a978fe9f7b77a1d667c77d2202dadd1c10...db0cbc48d4aaa300713a95d9b317a365a474490c
regressed commit: https://github.com/rust-lang/rust/commit/2420bd34ba68a625840022de2a56aec228500359

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.6</summary>

Host triple: aarch64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start=2023-03-01 --end=2023-04-01 --regress=success --script=./t.sh
```
</details>

<details>
<summary>t.sh</summary>

```bash
#!/bin/sh

set -ex

rustc t.rs --crate-type=lib --emit=asm -O && cat ./t.s | grep -E "cbz\s+w0, .LBB0_2"
```

(if you want to test on `x86_64` replace `"cbz\s+w0, .LBB0_2"` with `"testl\s+%edi, %edi"`)

</details>

<details>
<summary>t.rs</summary>

```rust
pub fn f(a: Option<i32>) -> i32 {
    unsafe { if !a.is_none() { std::hint::unreachable_unchecked() } }

    return a.unwrap();
}
```

</details>

## History

@heckad originally noticed the problem and opened #110456, then @WaffleLapkin suggested that this is a compiler issue, then @bugadani [noticed](https://github.com/rust-lang/rust/pull/110456#issuecomment-1512025633) that this is a regression, then @WaffleLapkin bisected and opened this issue.

**Comment by saethlin** [comment]
> searched nightlies: from nightly-2023-03-01 to nightly-2023-04-01

The end of this regression window is over 2 weeks from now. Why?

Godbolt usually has pretty old nightlies. If I add `--emit=mir`: https://godbolt.org/z/YfxfhETfb you can see we have duplicate switch targets, which means that either this commit is broken or godbolt doesn't have it: https://github.com/rust-lang/rust/commit/2a628bd99c39b69e88b24c622e3d246dd5573353

**Comment by lqd** [comment]
godbolt seems to have `rustc 1.71.0-nightly (d0f204e4d 2023-04-16)` ?

**Comment by WaffleLapkin** [comment]
> > searched nightlies: from nightly-2023-03-01 to nightly-2023-04-01
>
> The end of this regression window is over 2 weeks from now. Why?

Because I knew that `2023-04-01` reproduces the regression, and wanted to cut some time bisecting. For reference I can reproduce the same issue with `+nightly-2023-04-19`.

**Comment by saethlin** [comment]
To be clear, separate from this issue I believe that this MIR:
```rust
    bb0: {
        _2 = discriminant(_1);           // scope 0 at t.rs:2:11: 2:12
        switchInt(move _2) -> [0: bb2, 1: bb1, otherwise: bb1]; // scope 0 at t.rs:2:5: 2:12
    }
```
is a bug.

**Comment by saethlin** [comment]
Yeah, pretty sure that is the root cause.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23110551.20Codegen.20regression.20involving.20.60assume.60.2F.60unreachable_.E2.80.A6)).

@rustbot label -I-prioritize +P-medium
