### ISSUE TITLE
Regression in non_upper_case_globals lint level attribute on associated item

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#110573]
```rust
#![deny(warnings)]

pub struct Struct;

impl Struct {
    #[allow(non_upper_case_globals)]
    pub const Const: () = ();
}
```

```console
$ cargo +nightly-2023-04-19 check
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
```

```console
$ cargo +nightly-2023-04-20 check
error: associated constant `Const` should have an upper case name
 --> src/main.rs:7:15
  |
7 |     pub const Const: () = ();
  |               ^^^^^ help: convert the identifier to upper case: `CONST`
  |
note: the lint level is defined here
 --> src/main.rs:1:9
  |
1 | #![deny(warnings)]
  |         ^^^^^^^^
  = note: `#[deny(non_upper_case_globals)]` implied by `#[deny(warnings)]`
```

I believe the old behavior from nightly-2023-04-19 is correct.

The repro has nothing to do with trait impls so I believe #110513 was not supposed to have affected it.

**Comment by dtolnay** [comment]
Bisects to #110513. @Ezrashaw @compiler-errors

**Comment by Ezrashaw** [comment]
How on earth did that happen? It was like a five-line change. :laughing:

**Comment by compiler-errors** [comment]
Probably something to do with the hygeine of the span on the `ImplItemRef` versus the `ImplItem`. @Ezrashaw if you can't fix this then ping me and I'll look at it, but we probably should fix it sooner than later.

**Comment by Ezrashaw** [comment]
I was thinking that it's because we aren't checking the lint level for each of the items *within* the impl. Just the impl itself.

**Comment by compiler-errors** [comment]
Oh, no, that's not it. You're missing a call to `with_lint_attrs` in the visitor.
