### ISSUE TITLE
`RUSTFLAGS=--verbose` causes full recompilation

### ISSUE THREAD

**Issue by catamorphism** [rust-lang/rust#110654]
Doing a full build, then repeating the command prefixed by `RUSTFLAGS=--verbose`, triggers a full recompilation.

```Shell
$ ./x.py build
Building bootstrap
    Finished dev [unoptimized] target(s) in 0.09s
Building stage0 library artifacts (x86_64-unknown-linux-gnu) 
    Finished release [optimized] target(s) in 0.12s
Building compiler artifacts (stage0 -> stage1)
    Finished release [optimized] target(s) in 0.26s
Assembling stage1 compiler
Building stage1 library artifacts (x86_64-unknown-linux-gnu) 
    Finished release [optimized] target(s) in 0.09s
Warning: no codegen-backends config matched the requested path to build a codegen backend. Help: add backend to codegen-backends in config.toml.
Build completed successfully in 0:00:00
$ RUSTFLAGS=--verbose ./x.py build
Building bootstrap
   Compiling libc v0.2.140
   Compiling memchr v2.5.0
   Compiling cfg-if v1.0.0
   Compiling typenum v1.15.0
   Compiling version_check v0.9.4
   Compiling proc-macro2 v1.0.46
   Compiling io-lifetimes v1.0.9
   Compiling cc v1.0.73
```
(etc.)

I understand the rationale for triggering a full recompilation if `RUSTFLAGS` changes, but perhaps it might be worthwhile to special-case flags like `--verbose` that don't affect how the compiler generates artifacts. Maybe I should have known, but if I'm on a platform where building Rust takes hours and I'm trying to debug an error that occurs midway through compilation, it's less than ideal to have to recompile hours' worth of unchanged code to get debug output for one particular command.

**Comment by jyn514** [comment]
I agree this is annoying, but I think https://github.com/rust-lang/cargo/issues/8716 already covers this use case pretty thoroughly so I'm going to make this as a duplicate.

**Comment by jyn514** [comment]
Oh, and fwiw in rust-lang/rust only you can set MAGIC_EXTRA_RUSTFLAGS to forcibly bypass cargo's caching logic.
