### ISSUE TITLE
MIR-inlined functions called with constants should put the constant in debug info

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#110675]
The following code calls `is_digit` with a constant radix:

https://github.com/rust-lang/rust/blob/37b22cf2d5d787106077d4f9ef3092ca80e92a1b/tests/mir-opt/issues/issue_59352.rs#L13-L16

The MIR inliner preserves a local variable that's "holding" the value

https://github.com/rust-lang/rust/blob/37b22cf2d5d787106077d4f9ef3092ca80e92a1b/tests/mir-opt/issues/issue_59352.num_to_digit.PreCodegen.after.mir#L7-L10

But it's actually dead -- nothing sets `_3` to anything, so that debug info node is useless.

(I'm working on a PR that will remove always-uninitialized debug info like that `_3`, which is how I noticed this.  So I opened this in case the debuginfo folks want this to work instead of just being dropped.)

**Comment by cjgillot** [comment]
ConstDebugInfo does the general work of uplifting to debuginfo. I have https://github.com/rust-lang/rust/pull/107404 trying to turn it by default.
