### ISSUE TITLE
Rustdoc doesn't show `repr` for a struct re-exported from another package

### ISSUE THREAD

**Issue by nicholasbishop** [rust-lang/rust#110698]
If you define a struct with an explicit `repr(...)` in one package, then `pub use` it in another package, rustdoc doesn't show the `repr` on the re-exported one.

Minimal repo showing this problem: https://github.com/nicholasbishop/pub-use-repr-doc-bug

In `pkg1` you get:
![image](https://user-images.githubusercontent.com/1023208/233800465-b7d186b9-9a98-4cb6-b5be-d3e6810dac84.png)

But in `pkg2` you get:
![image](https://user-images.githubusercontent.com/1023208/233800485-b9b4f72e-540c-41e6-a439-f3be22bce67c.png)

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0 (84c898d65 2023-04-16)
binary: rustc
commit-hash: 84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc
commit-date: 2023-04-16
host: x86_64-unknown-linux-gnu
release: 1.69.0
LLVM version: 15.0.7
```

Also tested on nightly, same result:
```
rustc 1.71.0-nightly (8bdcc62cb 2023-04-20)
binary: rustc
commit-hash: 8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc
commit-date: 2023-04-20
host: x86_64-unknown-linux-gnu
release: 1.71.0-nightly
LLVM version: 16.0.2
```

**Comment by Ezrashaw** [comment]
I suspect that this kind of metadata isn't saved to disk and therefore `rustdoc` has no idea about the existence of the attribute on foreign types.

**Comment by GuillaumeGomez** [comment]
That's a regression actually since it was there before https://github.com/rust-lang/rust/pull/98450. Fixing it.

**Comment by nicholasbishop** [comment]
Great, thanks for the quick fix!
