### ISSUE TITLE
Consider adding the absolute CFG_LIBDIR to the search paths for rustc

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#11068]
In #11045, we're probably going to start always having an absolute path for CFG_LIBDIR. This means that `librustc` has one extra location to start search for by default for the target libraries. This libdir is essentially the same thing as `self_exe_path().pop()` for *rustc*, but as #11063 noted other usage of `librustc` is hamstrung by having to specify this directory.

**Comment by steveklabnik** [comment]
Triage: unclear what the status is of this today.

**Comment by alexcrichton** [comment]
I think we've got our story pretty square here today, so closing.
