### ISSUE TITLE
[Bug Report] `std::io::BufReader::new(file).fill_buf()` only reads first 8192 bytes

### ISSUE THREAD

**Issue by kevinmatthes** [rust-lang/rust#110690]
I tried this code:

```rust
// File name:  fill_buf_bug.rs
// Compiled with command:  rustc fill_buf_bug.rs

use std::io::BufRead;

fn main() -> Result<(), Box<dyn std::error::Error>> {
  let gpl3 = std::path::PathBuf::from("/usr/share/common-licenses/GPL-3");
  let file = std::fs::File::open(gpl3)?;
  let mut binding = std::io::BufReader::new(file);
  let bytes = binding.fill_buf()?;
  let text = String::from_utf8(bytes.to_vec())?;

  println!("{}", bytes.len());
  println!("{text}");

  Ok(())
}
```

I expected to see this happen:  output similar to the following Bash command.

```bash
wc -c /usr/share/common-licenses/GPL-3 | cut -d' ' -f1 && cat /usr/share/common-licenses/GPL-3
```

Instead, this happened:

- output "8192" in the first line written to `stdout`
- Only the first 162 lines of the license text are written to `stdout` after that.
- This happens to every file with more than 8192 bytes, the GPL-3.0 license text is just an example using a common file on Linux systems.

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0 (84c898d65 2023-04-16)
binary: rustc
commit-hash: 84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc
commit-date: 2023-04-16
host: x86_64-unknown-linux-gnu
release: 1.69.0
LLVM version: 15.0.7
```

Backtrace unavailable.

**Comment by Shiva953** [comment]
Might be due to the fact that the default size of the buffer used by `std::io::BufReader` is 8192 Bytes.
We can try a larger buffer size as follows : 

```rust
use std::io::BufRead;

fn main() -> Result<(), Box<dyn std::error::Error>> {
  let gpl3 = std::path::PathBuf::from("/usr/share/common-licenses/GPL-3");
  let file = std::fs::File::open(gpl3)?;
  let mut binding = std::io::BufReader::with_capacity(16384, file); // increase buffer size to 16 KB
  let bytes = binding.fill_buf()?;
  let text = String::from_utf8(bytes.to_vec())?;

  println!("{}", bytes.len());
  println!("{text}");

  Ok(())
}
```
Hope this solves the issue.

**Comment by kevinmatthes** [comment]
Okay, thank you for your answer!  Is this behaviour documented somewhere?  I tried to find some information regarding this size limitation but I did not find anything regarding this in the standard library's documentation...  Maybe I have overlooked something?
