### ISSUE TITLE
`tests/ui/io-checks` fail locally on master

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#110794]
The `tests/ui/io-checks/inaccessbile-temp-dir.rs` test fails for me locally on the master branch (and was failing for a while now). I can of course ignore it, but it's annoying. `tests/ui/io-checks/non-ice-error-on-worker-io-fail.rs` also fails if run after/with `inaccessbile-temp-dir.rs`.

It looks like `inaccessbile-temp-dir.rs` successfully creates a temp directory even if it's parent does not exist:

<details><summary>output</summary>
<p>

```
:~/rust-b (master); git log -1 --oneline
91b61a4ad61 (HEAD -> master, upstream/master) Auto merge of #110389 - mazong1123:add-shortcut-for-grisu3, r=Mark-Simulacrum
:~/rust-b (master); ls /does-not-exist
ls: cannot access '/does-not-exist': No such file or directory
:~/rust-b (master) [2]; x t tests/ui/io-checks/inaccessbile-temp-dir.rs
Building bootstrap
    Finished dev [unoptimized] target(s) in 0.06s
Building stage0 library artifacts (aarch64-unknown-linux-gnu)
    Finished release [optimized + debuginfo] target(s) in 0.18s
Building compiler artifacts (stage0 -> stage1, aarch64-unknown-linux-gnu)
    Finished release [optimized + debuginfo] target(s) in 0.29s
Assembling stage1 compiler
Building stage1 library artifacts (aarch64-unknown-linux-gnu)
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Finished release [optimized + debuginfo] target(s) in 0.21s
Building stage0 tool compiletest (aarch64-unknown-linux-gnu)
    Finished release [optimized + debuginfo] target(s) in 0.19s
Check compiletest suite=ui mode=ui (aarch64-unknown-linux-gnu -> aarch64-unknown-linux-gnu)

running 1 tests
F

failures:

---- [ui] tests/ui/io-checks/inaccessbile-temp-dir.rs stdout ----

error: ui test compiled successfully!
status: exit status: 0
command: "/home/gh-WaffleLapkin/rust-b/build/aarch64-unknown-linux-gnu/stage1/bin/rustc" "/home/gh-WaffleLapkin/rust-b/tests/ui/io-checks/inaccessbile-temp-dir.rs" "-Zthreads=1" "--sysroot" "/home/gh-WaffleLapkin/rust-b/build/aarch64-unknown-linux-gnu/stage1" "--target=aarch64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/home/gh-WaffleLapkin/rust-b/build/aarch64-unknown-linux-gnu/test/ui/io-checks/inaccessbile-temp-dir" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/home/gh-WaffleLapkin/rust-b/build/aarch64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/home/gh-WaffleLapkin/rust-b/build/aarch64-unknown-linux-gnu/test/ui/io-checks/inaccessbile-temp-dir/auxiliary" "-Z" "temps-dir=/does-not-exist/output"
stdout: none
stderr: none



failures:
    [ui] tests/ui/io-checks/inaccessbile-temp-dir.rs

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 14869 filtered out; finished in 60.70ms

Some tests failed in compiletest suite=ui mode=ui host=aarch64-unknown-linux-gnu target=aarch64-unknown-linux-gnu
Build completed unsuccessfully in 0:00:03
:~/rust-b (master) [1]; ls /does-not-exist
output
:~/rust-b (master); 
```

</p>
</details>

This causes the failure (as the test is expected to not compile) and also creates the directory, which `non-ice-error-on-worker-io-fail.rs` then observes and also fails.

This happens for me on the [`dev-desktop-eu-1`](https://forge.rust-lang.org/infra/docs/dev-desktop.html).

cc @fee1-dead iirc you had the same problems
cc @cuviper you changed those tests at some point, so maybe you know something

**Comment by KittyBorgX** [comment]
Summing up findings from discord, This test is wrong in its entirity since it gambles on permissions. The underlying `rustc` subcommand creates the dir if you have enough permission to create in `/` so it would fail. Otherwise, the directory is never created due to insufficient user permission, so the test passes. 

To sum it up, the test passed (for me) since I did not have enough permission to create a new directory (`/does-not-exist/output`) in `/`: 
![image](https://user-images.githubusercontent.com/82328083/234278123-f76e6777-7491-4b00-ab28-8d953b9620d2.png)

**Comment by WaffleLapkin** [comment]
The test assumes that the compiler uses `create_dir` and so it must fail to create `/does-not-exist/another-dir`, but this is actually not the case:

https://github.com/rust-lang/rust/blob/999e6e5afb71d0fa6b5f67440278129aca12c67d/compiler/rustc_interface/src/passes.rs#L608-L612

The test happens to pass in the CI and for many developers because you generally can't create a directory in `/`. However this is not always the case (for example I happen to run tests in chroot).

@jyn514 suggests that the proper fix for the test would be for the test to create an inaccessible directory, basically making a `run-make` analog to `chmod 000 some-dir && rustc -Z temps-dir=some-dir/foo`

**Comment by cuviper** [comment]
> the proper fix for the test would be for the test to create an inaccessible directory, basically making a `run-make` analog to `chmod 000 some-dir && rustc -Z temps-dir=some-dir/foo`

That still doesn't work if you're the root user, but I guess that's not what you're doing in your chroot?

You could use a path like `/proc/...` where even root can't create anything, but there's no OS-agnostic path like that.

**Comment by WaffleLapkin** [comment]
> That still doesn't work if you're the root user, but I guess that's not what you're doing in your chroot?

I guess my point is that `inaccessbile-temp-dir.rs` was broken on root anyway (because root has access to `/`, same as in chroot). The explanation in the test was because of the original `non-ice-error-on-worker-io-fail.rs` test it looks like, which works because it uses `-o` which requires at least the "parent must exist".

So change `/dev/null` -> `/does-not-exist/output`
- `non-ice-error-on-worker-io-fail.rs` now works on root, but doesn't work on chroot anymore
- `inaccessbile-temp-dir.rs` does **not** work on root/chroot, but also doesn't clobber `/dev/null`

My change:
- `non-ice-error-on-worker-io-fail.rs` unchanged
- `inaccessbile-temp-dir.rs` now works in chroot

Sooo, while `inaccessbile-temp-dir.rs` fails on root, since it doesn't have global effects (clobbering `/dev/null` as it originally did), I don't think it's a big deal. IMO you are not supposed to run tests on root (but it's also bad for tests to have global effects)...

**Comment by cuviper** [comment]
Yeah, that's fair -- we don't have to support root, but it should at least do no harm.

While you're poking at that, maybe you can fix the filename spelling to "inaccessible"?

**Comment by WaffleLapkin** [comment]
Fixed the spelling, thanks.
