### ISSUE TITLE
impl Iterator fails for user defined type with IndexMut impl

### ISSUE THREAD

**Issue by rmsyn** [rust-lang/rust#110727]
I tried this code:

```rust
use std::ops::{Index, IndexMut};

pub struct A {
    pub a: [u8; 10],
}

impl A {
    pub fn iter<'a>(&'a self) -> AIter<'a> {
        self.into_iter()
    }

    pub fn iter_mut<'a>(&'a mut self) -> AIterMut<'a> {
        self.into_iter()
    }

    pub fn len(&self) -> usize {
        self.a.len()
    }
}

impl Index<usize> for A {
    type Output = u8;

    fn index(&self, id: usize) -> &Self::Output {
        &self.a[id]
    }
}

impl IndexMut<usize> for A {
    fn index_mut(&mut self, id: usize) -> &mut Self::Output {
        &mut self.a[id]
    }
}

pub struct AIter<'a> {
    id: usize,
    a: &'a A,
}

pub struct AIterMut<'a> {
    id: usize,
    a: &'a mut A,
}

impl<'a> Iterator for AIter<'a> {
    type Item = &'a u8;

    fn next(&mut self) -> Option<Self::Item> {
        let end = self.a.len();
        let id = self.id;
        if id < end {
            self.id += 1;
            Some(&self.a[id])
        } else {
            None
        }
    }
}

impl<'a> Iterator for AIterMut<'a> {
    type Item = &'a mut u8;

    fn next(&mut self) -> Option<Self::Item> {
        let end = self.a.len();
        let id = self.id;
        if id < end {
            self.id += 1;
            Some(&mut self.a[id])
        } else {
            None
        }
    }
}

impl<'a> IntoIterator for &'a A {
    type Item = &'a u8;
    type IntoIter = AIter<'a>;

    fn into_iter(self) -> Self::IntoIter {
        Self::IntoIter { id: 0, a: self }
    }
}

impl<'a> IntoIterator for &'a mut A {
    type Item = &'a mut u8;
    type IntoIter = AIterMut<'a>;

    fn into_iter(self) -> Self::IntoIter {
        Self::IntoIter { id: 0, a: self }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        let mut a = A { a: [0u8; 10] };

        for &b in a.iter() {
            assert_eq!(b, 0);
        }

        for &mut b in a.iter_mut() {
            assert_eq!(b, 0);
        }
    }
}
```

I expected to see this happen: Build successful

Instead, this happened:

```
error: lifetime may not live long enough
  --> src/lib.rs:68:13
   |
60 | impl<'a> Iterator for AIterMut<'a> {
   |      -- lifetime `'a` defined here
...
63 |     fn next(&mut self) -> Option<Self::Item> {
   |             - let's call the lifetime of this reference `'1`
...
68 |             Some(&mut self.a[id])
   |             ^^^^^^^^^^^^^^^^^^^^^ associated function was supposed to return data with lifetime `'a` but it is returning data with lifetime `'1`
```

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0 (84c898d65 2023-04-16)
binary: rustc
commit-hash: 84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc
commit-date: 2023-04-16
host: x86_64-unknown-linux-gnu
release: 1.69.0
LLVM version: 15.0.7
```

</p>
</details>

Why does the similar code for the immutable iterator work (finds the implicit lifetime correctly), but the mutable version fails lifetime resolution?

**Comment by cuviper** [comment]
> Why does the similar code for the immutable iterator work (finds the implicit lifetime correctly), but the mutable version fails lifetime resolution?

The immutable iterator is able to make a *copy* of `&'a A` with its full lifetime. You can't copy `&mut` though, so at most that case can only reborrow a lifetime no greater than the `&mut self` at hand.

Another way to look at it is that `&mut` is never allowed to alias. If you were allowed to return `&'a mut u8`, then each prior item returned would alias with `&mut self.a` as you make the operator call to index `[id]`. Remember that the `Iterator` API allows you to keep all items at once, e.g. `collect()`.

The standard library's `slice::IterMut` accomplishes this with careful (`unsafe`) pointer operations, to make sure that the iterator itself never aliases the items that were already returned. If possible, I would suggest implementing your mutable iterator as a wrapper around existing iterators like that one.

In any case, this is not a bug. If my explanation is not enough, the [users forum](https://users.rust-lang.org/) may be able to help further.

**Comment by rmsyn** [comment]
Thanks for the thorough explanation, that makes complete sense now.

I'll try to work something out by wrapping `slice::IterMut`. Just need to figure out how to do custom indexing.
