### ISSUE TITLE
cannot find -lunwind when compiling Android aarch64

### ISSUE THREAD

**Issue by tsxiaofang** [rust-lang/rust#110786]
This issue started with version 1.68，There is no problem compiling target armv7-linux-androideabi。

**Comment by Urgau** [comment]
https://blog.rust-lang.org/2023/01/09/android-ndk-update-r25.html

**Comment by jyn514** [comment]
I'm going to close this as expected and intended breakage. We cannot support old versions of the NDK indefinitely, especially not if the vendor doesn't support them anymore.

**Comment by nova2moon** [comment]
BTW - still hitting this issue, with latest NDK 29, described here: https://github.com/rust-lang/rust/pull/85806#issuecomment-2887217992    anychance someone can shed light for newbies, hard to figure how to resolve it, see that post for many (failed) attempts :)
