### ISSUE TITLE
rustbuild: x.py install: `error: manifest path .. cargo/crates/credential/cargo-credential-1password/Cargo.toml` does not exist`

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#110742]
Happened during `x.py intall`

```

Uplifting rustc (stage1 -> stage3)
Building tool cargo (stage2 -> stage3)
    Finished release [optimized + debuginfo] target(s) in 0.19s
Building tool cargo-credential-1password (stage2 -> stage3)
error: manifest path `/home/matthias/vcs/github/rust_debug_assertions/src/tools/cargo/crates/credential/cargo-credential-1password/Cargo.toml` does not exist
Dist cargo-1.71.0-dev-x86_64-unknown-linux-gnu
	finished in 2.199 seconds
Install cargo stage2 (Some(x86_64-unknown-linux-gnu))
install: uninstalling component 'cargo'
install: creating uninstall script at /home/matthias/.rustup/toolchains/local-debug-assertions/lib/rustlib/uninstall.sh
install: installing component 'cargo'

    cargo installed.
    
```

probably since https://github.com/rust-lang/rust/pull/110653 cc @weihanglo

**Comment by ehuss** [comment]
You'll need to delete the `src/tools/cargo/crates/credential` directory. There was probably a `Cargo.lock` file left behind, and git won't delete the directory automatically.

**Comment by matthiaskrgr** [comment]
Hm, there is no such directory ?! :sweat_smile: 
```
~/vcs/github/rust_debug_assertions/src/tools/cargo/crates (de80432)
at 00:22:52 ❯ ls
cargo-platform      cargo-util  mdman
cargo-test-macro    crates-io   resolver-tests
cargo-test-support  home        semver-check
```

There is a `rust_debug_assertions/src/tools/cargo/credential` though

**Comment by weihanglo** [comment]
My fault. I forgot to update https://github.com/rust-lang/rust/blob/7f94b314cead7059a71a265a8b64905ef2511796/src/bootstrap/tool.rs#L602

Will send a PR.

**Comment by matthiaskrgr** [comment]
What is most concerning to me is that this actually did not fail the entire `x.py install`, so this would/did not even break CI..? is there something we can do about that?

**Comment by weihanglo** [comment]
Run `./x.py build` in CI probably? 

I supposed to run it locally before submitting a PR. However, that was an unlucky day. Something on nightly cannot build, so I blindly pushed 🙇🏾.

**Comment by ehuss** [comment]
Oh, sorry, I misunderstood what was going on. There have been some issues with those directories being moved around, but this was different.

> What is most concerning to me is that this actually did not fail the entire `x.py install`, so this would/did not even break CI..? is there something we can do about that?

The issue here is that the credential helpers are being included on an "as available" basis. Because they are nightly and experimental, they were intentionally marked as being optional so that if they failed it wouldn't cause problems here on rust-lang/rust. Eventually, if it gets stabilized, this will need to change to make them required tools.
