### ISSUE TITLE
Potential bug in atomic codegen for riscv32imac-unknown-none-elf targets

### ISSUE THREAD

**Issue by romancardenas** [rust-lang/rust#110857]
While working with atomics on the [`hifive1` BSP](https://github.com/riscv-rust/hifive1) for embedded Rust, I found a weird situation in which a load address exception is triggered.

I tried this code (simplified version):

```rust
use core::sync::atomic::{AtomicBool, Ordering};

fn main() {
    let flag = AtomicBool::new(false);
    let res = flag.compare_exchange(false, true, Ordering::AcqRel, Ordering::Relaxed);  // throws load access fault exception
    
    assert!(res.is_ok());
}
```
No compilation errors were triggered.

I expected to see this happen: the atomic boolean successfully sets its value and the assertion does not panic.

Instead, this happened: the `compare_exchange` operation threw a load access fault exception at the CPU level.

If I substitute the code with this:
```rust
use core::sync::atomic::{AtomicBool, Ordering};

fn main() {
    let flag = AtomicBool::new(false);

    let res = !flag.load(Ordering::Acquire);
    assert!(res);
    flag.store(true, Ordering::Release);
}
```
It works as expected.

### Meta

`rustc --version --verbose`:
```
rustc 1.71.0-nightly (39c6804b9 2023-04-19)
binary: rustc
commit-hash: 39c6804b92aa202369e402525cee329556bc1db0
commit-date: 2023-04-19
host: x86_64-apple-darwin
release: 1.71.0-nightly
LLVM version: 16.0.2
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23110857.20Potential.20bug.20in.20atomic.20codegen.20for.20riscv32imac-unk.E2.80.A6)).

@rustbot label -I-prioritize +P-high

**Comment by romancardenas** [comment]
The issue was that the E310x supports all atomic operations except `lr` and `sc`. Thus, an exception was triggered whenever the code used one of these instructions. I'm closing this issue since it has nothing to do with the compiler
