### ISSUE TITLE
Unused import warning does not respect feature flagging for (not(test))

### ISSUE THREAD

**Issue by thomasmost** [rust-lang/rust#110828]
This is a bug with rustc — my current version is 1.69.0 but I don't believe it is specific to this version

I have a logging module (called "kirk"–pun intended) which uses `tracing::info!` in most cases but `println!` in test

```rust
#[cfg(not(test))]
use tracing::{error_span, info, Level};

#[macro_export]
macro_rules! kirk {
    ($($arg:tt)*) => {{
      #[cfg(test)]
      {
        println!("{}", std::format_args!($($arg)*));
      }
      #[cfg(not(test))]
      {
        info!("{}", std::format_args!($($arg)*));
      }
    }};
  }
```

I expected to see this as fully valid, lint-free Rust.

Instead, rustc logs:  `` unused imports: `Level`, `error_span`, `info` ``

... and `cargo fix` executes the recommendation, breaking the build

I'm not sure how to collect a backtrace on this (RUST_BACKTRACE doesn't seem to output anything useful with `cargo fix`)

**BUT** I checked and this behavior is also present in `nightly`

**Comment by clubby789** [comment]
In general, macros should refer to items by absolute paths, i.e. `::tracing::info!`, which should help work around this

**Comment by Nilstrieb** [comment]
This is not a bug in the compiler, everything is working as expected. `#[cfg]`ed out code is stripped out and cannot be accounted for here. Use items have to either be put into the cfged out block or be cfged as well.

**Comment by thomasmost** [comment]
oh god, duh 🤦🏼

**Comment by clubby789** [comment]
Defining a macro does not use the imports. If you actually invoked the macro, the warning would go away, although you'd have to import them in any file the macro is used. This is why imports need to either be inside the macro body, or (better) referenced directly

**Comment by thomasmost** [comment]
got it... okay thank you
