### ISSUE TITLE
Document the default for `ExitStatus`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#110863]
> @scottmcm: I think it should at least say somewhere what that default is. Having it come from a derive(Default) on a c_int feels indirect to me as well, so perhaps it would make sense to define it manually in terms of ExitCode::SUCCESS instead, say -- that would also allow putting a doc-comment on the impl.

We should document that `Default` for `ExitStatus` is "process reported successful termination", ie the result of `ExitCode::success().into()`, and, implement it that way.

_Originally posted by @ijackson in https://github.com/rust-lang/rust/issues/106425#issuecomment-1396910651_

**Comment by jyn514** [comment]
Right, it needs https://github.com/rust-lang/rust/pull/106425 to merge first.

**Comment by john-h-k** [comment]
Alright 👍 . How does documenting work for a derived trait?

**Comment by jyn514** [comment]
You'd have to remove the derive and use manual `impl Default` blocks.

**Comment by ijackson** [comment]
> You'd have to remove the derive and use manual impl Default blocks.

That ends up with the docs for what Default means lower in the rustdoc
page, next to the place where the impl and its methods appear.  It
might be better to just document it in the doc comment for the struct.

**Comment by ijackson** [comment]
> Also just to check, It's ExitCode::SUCCESS.into() right? success()
> doesn't seem to be a method and doesn't seem to be being added by
> that issue (or should I add that method?)

Sorry, I think that was me writing loosely.  Yes, I mean te constant
SUCCESS I thijnk.  You don't need to add anything.

Ian.

**Comment by ijackson** [comment]
Note #114593, which is a bit of a swamp.  I think changing the docs can be done (at the cost of adding to the set of things which the docs claim to be true but which are false on those broken platforms) but changing the implementation ("and implement it that way") is blocked.

**Comment by john-h-k** [comment]
> @rustbot claim

I’ve already got a branch with this issue fixed on it - was waiting for the previous PR to merge and it now has. For some reason I forget to claim it though

**Comment by bkaestner** [comment]
Documented as of a741a5ad16bd3f136b94b31dbff9d1c8728e2064 within 1.73 via #114864 or am I mistaken?

**Comment by john-h-k** [comment]
> @rustbot claim

It appears this has already been done - i mentioned a few comments back but I've already completed this - i was going to claim it but im awaiting an update on whether its already been finished
