### ISSUE TITLE
Implement attributes for branch weight

### ISSUE THREAD

**Issue by kvanberendonck** [rust-lang/rust#11092]
The `cold` attribute exists for functions, but one might want to put weights on branches. This could have 3 forms; `weight=N` where N is 0-1, `likely` (1) and `unlikely` (0).

LLVM understands these annotations on branches already and can use these to fine-tune assembly to reduce branch mis-predictions. By nature, these could be used extensively in the standard library.

ie

```
match leaf {
    #[likely]
    Some(x) => recurse(x),
    None => {
        // do stuff that doesn't make sense to be in a cold fn
        ...
    }
}
```

There have been cases in Haskell libraries where changing the order of ADTs can increase performance by around 20% because branches are guessed differently by the compiler.

**Comment by pmarcelll** [comment]
#36181 added `likely` and `unlikely` intrinsics.

**Comment by cyplo** [comment]
Hi ! With #36181 being merged, it there any other changes needed to close this one ? Thank you !

**Comment by aturon** [comment]
Closing for the time being due to #36181.

**Comment by Eh2406** [comment]
There is a reference to this issue in the code:

https://github.com/rust-lang/rust/blob/a86f556ee37c13047f966c35effab8b334b7de67/src/libstd/collections/hash/map.rs#L141-L143

What needs to be done to remove that comment, now that this is closed?
