### ISSUE TITLE
Make `String` a diagnostic item

### ISSUE THREAD

**Issue by bluthej** [rust-lang/rust#110949]
## Proposal

It would be nice if `String` was a diagnostic item.

## Background

I [implemented](https://github.com/rust-lang/rust-clippy/pull/10528) the `clear_with_drain` Clippy lint for `Vec`s first, and then proposed to [extend](https://github.com/rust-lang/rust-clippy/pull/10614) that to 5 other container types including `String`s. However, in the process I realized that all my container types were diagnostic items except for `String`s.

This led me to find a false negative in `collection_is_never_read`, which was also trying to check for `String`s using [`is_type_diagnostic_item`](https://github.com/rust-lang/rust-clippy/blob/990bbdc2bee264291843497cebe59f307c2ed86f/clippy_utils/src/ty.rs#L378). The current workaround is to use the lang item for `String`, which means that this type gets a special treatment. I find this a little unfortunate and would like to be able to handle all these container types in the same way 🙂 

@llogiq suggested to add a `String` diagnostic item [here](https://github.com/rust-lang/rust-clippy/issues/10572#issuecomment-1500885352) so I thought I would open the issue!

Ironically, the `String` type was the one mentioned as an example in @Manishearth's original proposal #39131, and it was again suggested in [this comment](https://github.com/rust-lang/rust/pull/39116#issuecomment-273246162). But apparently nobody needed this diagnostic item that bad!

## Pros and cons

When working on Clippy lints, one expects the ability to check for such a prominent type using `is_type_diagnostic_item`, which can lead to false negatives (like I mentioned, even though this was also due to insufficient testing).

The only downside that I can think of is that there would be two different ways to check for the `String` type, so one can wonder which one one is supposed to use.

**Comment by jyn514** [comment]
I think this should be fixed in clippy's helper library. There's no reason for an item to be both a lang item and a diagnostic item.

**Comment by bluthej** [comment]
Oh I see. Thx for the feedback, I'll close this issue and see if we can find a better workaround on the Clippy side.
