### ISSUE TITLE
`rustc -W help` doesn't list 16 valid lint names

### ISSUE THREAD

**Issue by peter-kehl** [rust-lang/rust#110977]
Both https://doc.rust-lang.org/nightly/rustc/lints/listing/index.html and https://doc.rust-lang.org/rustc/lints/listing/index.html say that we can "see this list by running `rustc -W help`". However, current `1.71.0-nightly` (and recent stable versions, too) don't list following 16 valid lint names (here listred in a regex): `implied_bounds_entailment|unstable_syntax_pre_expansion|ungated_async_fn_track_caller|special_module_name|repr_transparent_external_private_fields|opaque_hidden_inferred_bound|named_arguments_used_positionally|map_unit_fn|for_loops_over_fallibles|byte_slice_in_packed_struct_with_derive|unused_tuple_struct_fields|let_underscore_drop`.

Those lint names are valid, e.g. code like
```rust
fn _f() {
    #[allow(let_underscore_drop)]
    let _any_statement_goes = ();
}
```
does compile. I've got names of all those lints from 
- https://doc.rust-lang.org/nightly/rustc/lints/listing/allowed-by-default.html#let-underscore-drop
- https://doc.rust-lang.org/nightly/rustc/lints/listing/allowed-by-default.html#unused-tuple-struct-fields
- https://doc.rust-lang.org/nightly/rustc/lints/listing/warn-by-default.html#byte-slice-in-packed-struct-with-derive
- https://doc.rust-lang.org/nightly/rustc/lints/listing/warn-by-default.html#for-loops-over-fallibles
- https://doc.rust-lang.org/nightly/rustc/lints/listing/warn-by-default.html#map-unit-fn
- https://doc.rust-lang.org/nightly/rustc/lints/listing/warn-by-default.html#named-arguments-used-positionally
- https://doc.rust-lang.org/nightly/rustc/lints/listing/warn-by-default.html#opaque-hidden-inferred-bound
- ...
- https://doc.rust-lang.org/nightly/rustc/lints/listing/deny-by-default.html#implied-bounds-entailment

I've tried to get them listed in various toolchain versions installed through `rustup` (NOT `rustup` downloaded from Rust website, but installed from Manjaro/stable Arch Linux x64 packages), but I couldn't see it listed in any version: `rustc -W help | grep -E "implied_bounds_entailment|unstable_syntax_pre_expansion|ungated_async_fn_track_caller|special_module_name|repr_transparent_external_private_fields|opaque_hidden_inferred_bound|named_arguments_used_positionally|map_unit_fn|for_loops_over_fallibles|byte_slice_in_packed_struct_with_derive|unused_tuple_struct_fields|let_underscore_drop"`.
```bash
❯ cargo --version 
cargo 1.71.0-nightly (9e586fbd8 2023-04-25)
❯ rustup toolchain list 
stable-x86_64-unknown-linux-gnu
beta-x86_64-unknown-linux-gnu
nightly-i686-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-musl
1.45-x86_64-unknown-linux-gnu
1.52-x86_64-unknown-linux-gnu
1.63-x86_64-unknown-linux-gnu (default)
stage0
stage1
1.49.0-x86_64-unknown-linux-gnu
1.58.1-x86_64-unknown-linux-gnu
1.61.0-x86_64-unknown-linux-gnu
1.65.0-x86_64-unknown-linux-gnu
1.66.1-x86_64-unknown-linux-gnu
1.67.0-x86_64-unknown-linux-gnu
1.67.1-x86_64-unknown-linux-gnu
1.68.0-x86_64-unknown-linux-gnu
1.68.2-x86_64-unknown-linux-gnu
1.69.0-x86_64-unknown-linux-gnu
```

FYI All those lints exist in many recent Rust versions, and some older, too (for example: `1.45`). But, they (or, at least some of them) do NOT exist in some versions in-between: 1.63, 1.65.0, 1.66.1, 1.67.0, 1.67.1, 1.68.0, 1.68.2 (at least so for the mainstream x64 Linux target: `x86_64-unknown-linux-gnu`). See also https://crates.io/crates/allow#in-scope and https://crates.io/crates/allow#out-of-scope. If you happen to hear about any reason for this, please shine a light here.

Not listing those lints in `rustc -W help` wouldn't be a "big issue", except that I'm trying to bisect the earliest Rust version that introduced them. I looked at both `compiler/rustc_lint/src/lib.rs` and `compiler/rustc_lint_defs/src/builtin.rs`, but there's no version/indication. Is there any way (easier than bisecting a GIT commit and then figuring out the respective Rust version, or digging in release notes where the lints don't seem to be mentioned by name), please?

(Clippy has it beautiful: https://rust-lang.github.io/rust-clippy/index.html.)

(Purpose: To support lints appropriate to the consumer's Rust version when "aliasing" them 1:MANY with https://crates.io/crates/allow.)
Thank you in advance.

**Comment by jyn514** [comment]
I am confused. Is the bug that the lints aren't listed with `-W help` or that you want to find the version they were introduced? Fixing -Whelp won't affect old versions of the compiler.

**Comment by matthiaskrgr** [comment]
I think most (all?) of the mentioned lints were uplifted from clippy...? :thinking:

**Comment by jyn514** [comment]
actually yeah, what? I can't reproduce this, the lint shows up fine:
```
PS C:\Users\jyn\src\rust2> rustc -W help
Lint checks provided by rustc:

                                                       name  default  meaning
                                                       ----  -------  -------
                                        let-underscore-drop  allow    non-binding let on a type that implements `Drop`
```

**Comment by jyn514** [comment]
@peter-kehl you need to use `-` as a separator, not `_`

**Comment by peter-kehl** [comment]
Wow. Thank you.

Yes, it's the dash as a separator in the output of `rustc -W help` (even though the lint names, as passed to `#[allow(...)]`, contain underscores). I guess this behavior/difference can stay as-is, unless someone wants otherwise.
