### ISSUE TITLE
rustdoc: Missing method signatures in trait docs

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#111064]
https://docs.rs/parry2d/0.13.4/parry2d/bounding_volume/trait.BoundingVolume.html

![image](https://user-images.githubusercontent.com/81079/235464006-5c8215d9-52b3-4bb0-be9f-8a05948cc834.png)

![image](https://user-images.githubusercontent.com/81079/235464059-b7023de6-27b1-4630-9daf-96f0c27ef1fb.png)

I haven't attempted to really look into what's going wrong, but taking a quick glance at the source and build log on docs.rs there's nothing obviously weird jumping out to me.

### Meta

Latest version of the crate was built on docs.rs using `rustc 1.71.0-nightly (9ecda8de8 2023-04-30)` and `rustc 1.70.0-nightly (84dd17b56 2023-04-14)` and showed the issue, The first version showing the issue was 0.13.1 which was built with `rustc 1.69.0-nightly (34e6673a0 2023-02-25)` while the last version without the issue was 0.13.0 which was built with `rustc 1.68.0-nightly (afaf3e07a 2023-01-14)`

**Comment by compiler-errors** [comment]
@GuillaumeGomez I think you regressed this in #107000.

Specifically, it fails by trying to render a stripped trait item when you re-export a `doc(hidden)` trait like so:

```
#[doc(hidden)]
mod hidden {
    pub trait Foo {
        // Hello, world!
        fn test();
    }
}

pub use hidden::Foo;
```

**Comment by compiler-errors** [comment]
Specifically, this code does not respect inlining for trait items.

https://github.com/rust-lang/rust/blob/1cb63572d271855a5ccef79a3e10a8015d00f6ad/src/librustdoc/passes/strip_hidden.rs#L88-L96

**Comment by GuillaumeGomez** [comment]
Thanks for the ping @compiler-errors ! I'll fix it in the next hours.
