### ISSUE TITLE
array repeat exprs do not check the array type is well formed

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#111091]
I tried this code:

```rust
trait Foo {
    const ASSOC: [u8];
}

fn bar<T: Foo>() {
    let a = [T::ASSOC; 2];
}

fn main() {}
```

I expected to see this happen: It should not compile as the local variable `a` has type `[[u8]; 2]` which is not well formed

Instead, this happened: it compiled :grimacing: 

### Meta
`playground version`:
```
Nightly channel

Build using the Nightly version: 1.71.0-nightly

(2023-04-30 9ecda8de85ce893cc3fc)
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by asquared31415** [comment]
I am pretty sure `bar` can't be called, since `Foo` can't be implemented by any type, since the `const` has a type that's not `Sized` (maybe some nightly feature enables this?).  Is it an issue that a `trait` can have a `const` with a type that's not `Sized`?

**Comment by apiraino** [comment]
@BoxyUwU I've tried bisecting this but I can't find a previous version where compiling with `rustc` returns an error. Is this unsoundness always been there or can we bisect to previous version that it didn't?

**Comment by BoxyUwU** [comment]
I imagine its likely that this always was broken lol
