### ISSUE TITLE
Tracking Issue for const `[u8]::is_ascii` (`const_slice_is_ascii`)

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#111090]
Feature gate: `#![feature(const_slice_is_ascii)]`

This is a tracking issue for `[u8]::is_ascii` being a `const fn`.

UTF-8 checking in `const fn` stabilized back in 1.63 (#97367), but apparently somehow simpler ASCII checking was never const-ified.

### Public API

```rust
// core::slice

impl [u8] {
    const fn is_ascii(&self) -> bool;
}

// core::str

impl str {
    const fn is_ascii(&self) -> bool;
}
```

### Steps / History

- [x] Implementation: https://github.com/rust-lang/rust/pull/111222
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by scottmcm** [comment]
Hello libs-api!  This hasn't been around that long, but I'd like to nominate it for stabilization.

`str::from_utf8` has been const-stable since 1.63 (a year ago), so I'd like to also be able to use the substantially-simpler `[u8]::is_ascii` in `const` as well.

It can be implemented using only stable `const fn` support (<https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=dd32ebaa5103731de9fab0ab4057f8bc>), so this doesn't require exposing any new capabilities.

**Comment by m-ou-se** [comment]
@rfcbot merge
