### ISSUE TITLE
rustfmt gets upset when trying to format a let-else block inside a macro.

### ISSUE THREAD

**Issue by vincenzopalazzo** [rust-lang/rust#111041]
This what rustfmt produces when I run the code formatting

```rust
#[macro_export]
macro_rules! from_cstr {
    ($x:expr) => {{
        use std::ffi::CStr;
        let c_str = unsafe { CStr::from_ptr($x) };
        let Ok(c_str) = c_str.to_str() else {
                                                                                    return null!()
                                                                                };
        c_str
    }};
}
```

@rustbot label +A-fmt

**Comment by compiler-errors** [comment]
I think it's probably better to file this against the rustfmt repo itself: https://github.com/rust-lang/rustfmt

Also, it's probably useful to note that it's not just a lack of formatting, but that it adds an indentation to everything in the `else` block every time the formatter runs.

**Comment by vincenzopalazzo** [comment]
Yeah better post to rustfmt, thanks
