### ISSUE TITLE
Some shift left operations of signed integers panic in debug

### ISSUE THREAD

**Issue by autinerd** [rust-lang/rust#111079]
Hi, some shift-left operations on signed integers do panic with 'attempt to negate with overflow' when built as debug binaries.

I tried this code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a06e4fc5e6e3835be1108e6a1bb665aa

```rust
trait Test {
    fn shl2(self, rhs: Self) -> Self;
}

impl Test for i8 {
    fn shl2(self, rhs: Self) -> Self {
        self << rhs
    }
}

fn main() {
    println!("{}", -28_i8 << 5);
    println!("{}", -28_i8.shl2(5));
    println!("{}", -28_i8.wrapping_shl(5));
}
```

For reproducing the error, this is enough:
```rust
fn main() {
    println!("{}", -28_i8.wrapping_shl(5));
}
```
It seems to affect all kinds of wrapping the left shift into a function. But not all combinations of operands are affected, for example `-28_i8.wrapping_shl(6)` and `-28_i8.wrapping_shl(4)` work as intended.

I expected to see this happen:
```
-128
-128
-128
```
as it does in mode=release.

Instead, this happened:
```
thread 'main' panicked at 'attempt to negate with overflow', src/main.rs:13:20
```

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0 (84c898d65 2023-04-16)
binary: rustc
commit-hash: 84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc
commit-date: 2023-04-16
host: x86_64-unknown-linux-gnu
release: 1.69.0
LLVM version: 15.0.7
```

but it happens in the beta and nightly channels on the Rust Playground as of this date as well.

<details><summary>Backtrace</summary>
<p>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:114:5
   3: playground::main
             at ./[src/main.rs:13](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a06e4fc5e6e3835be1108e6a1bb665aa#):20
   4: core::ops::function::FnOnce::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
```

</p>
</details>

**Comment by lukas-code** [comment]
This happens due to [operator precedence](https://doc.rust-lang.org/reference/expressions.html#expression-precedence): `-28_i8 << 5` is `(-28_i8) << 5`, but `-28_i8.any_method(5)` is `-(28_i8.any_method(5))`. So in your second and third case you get `-(-128i8)`, which will trigger the overflow check in debug mode.

**Comment by jyn514** [comment]
I'm going to close this since it's not a compiler bug.
