### ISSUE TITLE
nightly build fails with: error: failed to download from `https://crates.io/api/v1/crates/opener/0.5.2/download

### ISSUE THREAD

**Issue by psumbera** [rust-lang/rust#111124]
My nightly build on Solaris failed with:

```
..
Dist rust-docs-json-nightly-x86_64-pc-solaris
        finished in 8.001 seconds
Dist rustc-nightly-x86_64-pc-solaris
        finished in 32.508 seconds
Dist rust-std-nightly-x86_64-pc-solaris
        finished in 15.460 seconds
Dist rustc-dev-nightly-x86_64-pc-solaris
        finished in 78.711 seconds
Dist rust-src-nightly
        finished in 12.209 seconds
Building tool cargo (stage1 -> stage2, x86_64-pc-solaris)
 Downloading crates ...
error: failed to download from `https://crates.io/api/v1/crates/opener/0.5.2/download`

Caused by:
  [1] Unsupported protocol (Received HTTP/0.9 when not allowed)
Building bootstrap
Build completed unsuccessfully in 1:06:34
```

**Comment by Nilstrieb** [comment]
Do you have more information about your setup? Can you try doing the request yourself on this system? I am not aware that crates.io would try to use HTTP/0.9, that makes no sense.

**Comment by psumbera** [comment]
There seems to be some redirect..
```
 wget https://crates.io/api/v1/crates/opener/0.5.2/download
--2023-05-03 03:43:51--  https://crates.io/api/v1/crates/opener/0.5.2/download
Resolving www-proxy-ams.nl.oracle.com (XXX)... x.x.x.x
Connecting to XXX (XXX)| x.x.x.x|:80... connected.
Proxy request sent, awaiting response... 302 Moved Temporarily
Location: https://static.crates.io/crates/opener/opener-0.5.2.crate [following]
--2023-05-03 03:43:54--  https://static.crates.io/crates/opener/opener-0.5.2.crate
Connecting to XXX (XXX)|x.x.x.x|:80... connected.
Proxy request sent, awaiting response... 200 OK
Length: 16345 (16K) [application/gzip]
Saving to: ‘download’

download                                    100%[========================================================================================>]  15.96K  --.-KB/s    in 0s

2023-05-03 03:43:56 (133 MB/s) - ‘download’ saved [16345/16345]

```

For `curl` I had to specify `-L` to follow redirect.

**Comment by jyn514** [comment]
Why is curl involved at all? Cargo manages its own downloads.

**Comment by psumbera** [comment]
> Why is curl involved at all? Cargo manages its own downloads.

It was just a test that it can be downloaded from the same machine.

**Comment by jyn514** [comment]
@psumbera is this happening consistently? or was it a one-off problem?

**Comment by psumbera** [comment]
> @psumbera is this happening consistently? or was it a one-off problem?

Yes, It does. I'm trying to bissect first bad commit (bad have some difficulties).

**Comment by jyn514** [comment]
cc @rust-lang/cargo - i'm not sure exactly what's going wrong here but it seems related to a change between stable and beta cargo somehow.

**Comment by weihanglo** [comment]
We've bumped `curl-sys` in current beta in rust-lang/cargo#11871. 
We've also switch to the new "all-static" feature when building cargo in f795a150fe01b68bdd62503c39fbdc9ed04a5219.

May one of them is relevant? Is possible for you to set `CARGO_HTTP_DEBUG=true` and `CARGO_LOG=cargo::ops::registry=trace` and share the output?

**Comment by psumbera** [comment]
Another try with latest sources:
```
Generating unstable book md files (x86_64-pc-solaris)
Building stage0 tool unstable-book-gen (x86_64-pc-solaris)
    Updating crates.io index
warning: spurious network error (3 tries remaining): [35] SSL connect error (OpenSSL/1.0.2zg: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol)
error: failed to get `opener` as a dependency of package `clippy_dev v0.0.1 (/builds/psumbera/rust-lang-build/src/tools/clippy/clippy_dev)`

Caused by:
  failed to query replaced source registry `crates-io`

Caused by:
  download of op/en/opener failed

Caused by:
  failed to download from `https://index.crates.io/op/en/opener`

Caused by:
  [1] Unsupported protocol (Received HTTP/0.9 when not allowed)
Building bootstrap
Build completed unsuccessfully in 0:06:43
gmake: *** [Makefile:49: dist] Error 1
```

Will try CARGO_HTTP_DEBUG thing.

**Comment by psumbera** [comment]
> May one of them is relevant? Is possible for you to set `CARGO_HTTP_DEBUG=true` and `CARGO_LOG=cargo::ops::registry=trace` and share the output?

The output looks different. And I don't see the reason of error?!

[build-log.txt](https://github.com/rust-lang/rust/files/11452497/build-log.txt)

**Comment by jyn514** [comment]
at this point i'm starting to suspect cargo itself isn't to blame and there's some miscompilation in the artifacts we distribute for Solaris

**Comment by psumbera** [comment]
> at this point i'm starting to suspect cargo itself isn't to blame and there's some miscompilation in the artifacts we distribute for Solaris

Well, if you mean `rust-std-beta-x86_64-pc-solaris.tar.xz` it's from my own previous builds. As well as all other archives. I wasn't able to combine rust-std archives provided by Rust comunity with my own Rust version (as for Solaris there is only rust-std available).

**Comment by psumbera** [comment]
I have tried to use older `cargo`:

`cp dist/2023-03-07/cargo-beta-x86_64-pc-solaris.tar.xz dist/2023-04-20/cargo-beta-x86_64-pc-solaris.tar.xz`

And the build passes now.

So I wonder what can be wrong with my beta version of `cargo`.

Note that I just remember my `cargo` version from 2023-04-20 was actually from 2023-04-17 (as there was no commit to beta branch on 2023-04-20 (and thus my script didn't create any archive then).

**Comment by weihanglo** [comment]
What would happen if you use cargo from the current beta channel and build a new project? The version may look like

```console
$ cargo -vV
cargo 1.70.0-beta.4 (ec8a8a0ca 2023-04-25)
release: 1.70.0-beta.4
commit-hash: ec8a8a0cabb0e0cadef58902470f6c7ee7868bdc
commit-date: 2023-04-25
```

**Comment by psumbera** [comment]
> What would happen if you use cargo from the current beta channel and build a new project? The version may look like

What do you exactly mean by build a new project?  `cargo new hello_world --bin` seems to work.

But when I use this cargo version:

```
cargo 1.70.0-beta.4 (ec8a8a0ca 2023-04-25)
release: 1.70.0-beta.4
commit-hash: ec8a8a0cabb0e0cadef58902470f6c7ee7868bdc
commit-date: 2023-04-25
host: x86_64-pc-solaris
libgit2: 1.6.3 (sys:0.17.0 vendored)
libcurl: 7.87.0 (sys:0.4.61+curl-8.0.1 system ssl:OpenSSL/1.0.2zg)
os: Unknown [unknown bitness]
```
for Rust build I still see:
```
error: failed to download from `https://crates.io/api/v1/crates/nom/7.1.3/download`

Caused by:
  [1] Unsupported protocol (Received HTTP/0.9 when not allowed)
```

**Comment by ehuss** [comment]
> libcurl: 7.87.0 (sys:0.4.61+curl-8.0.1 system ssl:OpenSSL/1.0.2zg)

We had some significant problems with curl 7.87 and 7.88. One of them caused this protocol error, though that was with Windows schannel. I'd recommend updating to 8.0.1, or building rust with the static-cargo option.

**Comment by psumbera** [comment]
I have tried add `--enable-cargo-native-static` to configure but my beta build fails with:
```
error: failed to run custom build command for `openssl-sys v0.9.84`

Caused by:
  process didn't exit successfully: `/builds2/psumbera/rust-lang-build/build/sparcv9-sun-solaris/stage1-tools/release/build/openssl-sys-45d07fecb7afc672/build-script-main` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=SPARCV9_SUN_SOLARIS_OPENSSL_NO_VENDOR
  SPARCV9_SUN_SOLARIS_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset

  --- stderr
  thread 'main' panicked at 'don't know how to configure OpenSSL for sparcv9-sun-solaris', /builds2/psumbera/rust-bot/home/.cargo/registry/src/github.com-eae4ba8cbf2ce1c7/openssl-src-111.25.0+1.1.1t/src/lib.rs:303:18
```
I think I will wait for Curl 8.0.0 which will be in my build environmnet in about two weeks.

**Comment by jyn514** [comment]
I'm going to close this - it doesn't look like a problem with rust itself.
