### ISSUE TITLE
x.ps1 does not fail the build

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#111136]
The [`x.ps1`](https://github.com/rust-lang/rust/blob/master/x.ps1) shell script does not return with an exit code if the build fails. The `process.ExitCode` object doesn't appear to be an integer.

cc @rust-lang/bootstrap This may be an important issue since something could potentially fail in CI without failing the build.
Noticed in CI when something funky happened. Fortunately the metrics don't get created when a test fails (I think), but there may be other situations where it isn't working correctly.

This looks like it was added in #99992.

**Comment by ChrisDenton** [comment]
This is weird. I do remember doing a fair bit of testing of that PR.

**Comment by albertlarsan68** [comment]
PowerShell is always the odd one, with it's 5+ streams and .NET integrations and structured pipelines. Honestly, it doesn't surprise me that much that PowerShell does not care about exit codes, since the way to declare an error in PowerShell is to print something to the Error stream (IIRC).

**Comment by ChrisDenton** [comment]
Oh it did work originally. But then I broke it. There's a defect when using `WaitForExit()` instead of the `-Wait` parameter where ExitCode isn't set.
