### ISSUE TITLE
tests\ui\native-library-link-flags\msvc-non-utf8-output.rs fails with lld-link as the linker

### ISSUE THREAD

**Issue by danakj** [rust-lang/rust#111256]
This test is either new or changed recently, it now fails when using -Clinker=lld-link

Example build failure on Chromium CI: https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket/8781936910784713969/+/u/package_rust/stdout

```
  diff of stderr:
  
  -	error: linking with `link.exe` failed: exit code: 1181
  +	error: linking with `C:\b\s\w\ir\cache\builder\src\third_party\rust-toolchain-intermediate\llvm-host-install\bin/lld-link` failed: exit code: 1
  2	   |
  -	   = note: LINK : fatal error LNK1181: cannot open input file 'märchenhaft.obj'
  +	   = note: lld-link: error: could not open 'märchenhaft': no such file or directory
  4	           
  5	
  6	error: aborting due to previous error
```

The test has link.exe error messages hardcoded into it, which are wrong when not using link.exe.

We can disable this test when not using link.exe but it would be much better to make the error checking more flexible or explicitly define an output for ldd-link.

How would one go about the latter?

**Comment by danakj** [comment]
cc: @ChrisDenton

Maybe the answer is since we're not using MSVC we don't care about this test, but from what I can tell this is testing how we invoke the linker, not the link.exe execution itself, in which case, it's valid to test with other linkers too?

**Comment by ChrisDenton** [comment]
Hm, yes, sorry this was only meant to test msvc itself.

It could just test whether `märchenhaft` is in the output. That might be easier. Though I'm uncertain about testing *every* linker. It's possible there's one that doesn't support unicode output (I don't know).
