### ISSUE TITLE
debugger_visualizer: files not tracked in dep-info

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#111226]
I tried this code:

```rust
#![debugger_visualizer(natvis_file = "foo.xml")]
```

along with a file named `foo.xml` in the same directory.

Compile this with cargo. Modify `foo.xml`. Try running a build again.

I expected to see this happen: Cargo rebuilds the project.

Instead, this happened: Nothing happens

The problem is that the debugger_visualizer file does not get added to the dep-info file.

### Meta

`rustc --version --verbose`:
```
rustc 1.71.0-nightly (473f916d8 2023-05-03)
binary: rustc
commit-hash: 473f916d836cc662c5bdbb0d40af9fb4678fab9e
commit-date: 2023-05-03
host: x86_64-pc-windows-msvc
release: 1.71.0-nightly
LLVM version: 16.0.2
```

**Comment by michaelwoerister** [comment]
The visualizer file does not get loaded into the SourceMap during parsing, so [write_out_deps](https://github.com/rust-lang/rust/blob/2913ad6db0f72fed5139253faed73200c7af3535/compiler/rustc_interface/src/passes.rs#L448) does not pick up on it. It's not clear yet what's the cleanest way to fix this.
