### ISSUE TITLE
Tuple struct's private field can be accessed outside the defining module

### ISSUE THREAD

**Issue by akonradi** [rust-lang/rust#111220]
I tried this code:

```rust
mod my {
    pub struct Foo(&'static str);
}

impl AsRef<str> for my::Foo {
    fn as_ref(&self) -> &str {
        let Self(s) = self;
        s
    }
}
```

I expected to see this happen: compilation should fail because the trait impl is defined outside of the module for the type but refers to its private field.

Instead, this happened: this compiled successfully

### Meta
This reproduces on the playground for stable Rust, version 1.69.0: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=20f12a0f682d8dd6530d75f1b5e7a8dd

**Comment by KittyBorgX** [comment]
Adding a main function and attempting to call the `do_evil` (playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1e96d7ddeb6f23ccfa9b99c5b27c9c77) raises the compilation error: 

![image](https://user-images.githubusercontent.com/82328083/236359618-b0242063-23bb-4111-b2a8-fb4649373644.png)

**Comment by taiki-e** [comment]
This can be reproduced with cross-crate (e.i., any other crate can access the private field). This means that all encapsulations that take advantage of the field being private can be bypassed.

```rs
// crate a
#[derive(Default)]
pub struct A(u32);
```
```rs
// crate b
pub trait B {
    fn f(&self);
}
impl B for b::A {
    fn f(&self) {
        let Self(a) = self;
        println!("{}", a);
    }
}
fn main() {
    let a = b::A::default();
    a.f();
}
```

@rustbot label +I-unsound

Also, this can be reproduced in all versions where self_struct_ctor is stable (e.i., 1.32+). https://godbolt.org/z/dWbKP3voc

---

@KittyBorgX It's a matter of how you initialize Foo. If you provide a constructor for Foo, you won't get a compile error: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3e9ec99b1aa66a2f767d61bf71cab9f2

**Comment by akonradi** [comment]
The compilation error there is caused by `Foo` not being constructible outside the module it's defined in - this is expected. If we add a `Foo::new` and call that instead, we can use `do_evil` to access the private value that should be invisible outside the module: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=711b5d6c03393361f4b894f30376d0e4

**Comment by y21** [comment]
Just for completeness, turning this into a segfault without external crates/just std:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=cd936b8cd757d76d84b7307c794bbef1

**Comment by lcnr** [comment]
this has been unsound ever since #56365 in version 1.32

https://rust.godbolt.org/z/hPzMTY435

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23111220.20Tuple.20struct's.20private.20field.20can.20be.20accessed.20outsid.E2.80.A6)).

@rustbot label -I-prioritize +P-high
