### ISSUE TITLE
Internal Compiler Error

### ISSUE THREAD

**Issue by emilybae1705** [rust-lang/rust#111328]
### Code

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by clubby789** [comment]
Can you fill in the fields of the issue with your crash details?

**Comment by richterk** [comment]
I'm thinking that emilybae1705 is running on the latest rust.  I also got an error on upgrading. 

`bash
error: internal compiler error: compiler\rustc_monomorphize\src\collector.rs:1038:9: no MIR available for DefId(26:3010 ~ wgpu_core[7a6f]::track::texture::{impl#0}::all_ordered)     

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/a77c552485a19245a266bc03c450676c666b605f\compiler\rustc_errors\src\lib.rs:1650:9
stack backtrace:
   0:     0x7ffed989636c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h23f1fb14034f4d8e
   1:     0x7ffed98cfa0b - core::fmt::write::hfafb50adbc8294ee
   2:     0x7ffed988b919 - <std::io::IoSliceMut as core::fmt::Debug>::fmt::hded8b0a634ddda67
   3:     0x7ffed989611b - std::sys::common::alloc::realloc_fallback::hff2ec9094df8683a
   4:     0x7ffed9899939 - std::panicking::default_hook::h07bec551f84a7c22
   5:     0x7ffed98995ef - std::panicking::default_hook::h07bec551f84a7c22
   6:     0x7ffeacb080a6 - rustc_driver_impl[98d1546219968491]::install_ice_hook
   7:     0x7ffed989a03b - std::panicking::rust_panic_with_hook::h60c04dabef827e6a
   8:     0x7ffeaef8f353 - <rustc_infer[80e20e2c0a6542a1]::traits::project::ProjectionCacheEntry as core[1d425356198a5fcb]::fmt::Debug>::fmt
   9:     0x7ffeaef8cdc9 - <rustc_infer[80e20e2c0a6542a1]::traits::project::ProjectionCacheEntry as core[1d425356198a5fcb]::fmt::Debug>::fmt
  10:     0x7ffeaef8cd69 - <rustc_infer[80e20e2c0a6542a1]::traits::project::ProjectionCacheEntry as core[1d425356198a5fcb]::fmt::Debug>::fmt
  11:     0x7ffeaef85720 - <rustc_infer[80e20e2c0a6542a1]::traits::project::ProjectionCacheEntry as core[1d425356198a5fcb]::fmt::Debug>::fmt
  12:     0x7ffeaef852dc - <rustc_infer[80e20e2c0a6542a1]::traits::project::ProjectionCacheEntry as core[1d425356198a5fcb]::fmt::Debug>::fmt
  13:     0x7ffeaefbcc2d - rustc_middle[ae3d3bf8b86cb44f]::util::bug::bug_fmt
  14:     0x7ffeaefbc1ed - <rustc_middle[ae3d3bf8b86cb44f]::ty::assoc::AssocItems>::find_by_name_and_kinds
  15:     0x7ffeaefbc1af - <rustc_middle[ae3d3bf8b86cb44f]::ty::assoc::AssocItems>::find_by_name_and_kinds
  16:     0x7ffeaefbcb1f - rustc_middle[ae3d3bf8b86cb44f]::util::bug::bug_fmt
  17:     0x7ffeabe1ed6a - <rustc_monomorphize[f6953b6ef87a9045]::collector::MirNeighborCollector as rustc_middle[ae3d3bf8b86cb44f]::mir::visit::Visitor>::visit_constant
  18:     0x7ffeabe15a8f - <rustc_monomorphize[f6953b6ef87a9045]::collector::MirNeighborCollector as rustc_middle[ae3d3bf8b86cb44f]::mir::visit::Visitor>::visit_operand
  19:     0x7ffeabe15ea7 - <rustc_monomorphize[f6953b6ef87a9045]::collector::MirNeighborCollector as rustc_middle[ae3d3bf8b86cb44f]::mir::visit::Visitor>::visit_operand
  20:     0x7ffeabe15ea7 - <rustc_monomorphize[f6953b6ef87a9045]::collector::MirNeighborCollector as rustc_middle[ae3d3bf8b86cb44f]::mir::visit::Visitor>::visit_operand
  21:     0x7ffeabe15ea7 - <rustc_monomorphize[f6953b6ef87a9045]::collector::MirNeighborCollector as rustc_middle[ae3d3bf8b86cb44f]::mir::visit::Visitor>::visit_operand
  22:     0x7ffeabe15ea7 - <rustc_monomorphize[f6953b6ef87a9045]::collector::MirNeighborCollector as rustc_middle[ae3d3bf8b86cb44f]::mir::visit::Visitor>::visit_operand
  23:     0x7ffeabe15ea7 - <rustc_monomorphize[f6953b6ef87a9045]::collector::MirNeighborCollector as rustc_middle[ae3d3bf8b86cb44f]::mir::visit::Visitor>::visit_operand
  24:     0x7ffeabe15ea7 - <rustc_monomorphize[f6953b6ef87a9045]::collector::MirNeighborCollector as rustc_middle[ae3d3bf8b86cb44f]::mir::visit::Visitor>::visit_operand
  25:     0x7ffeaaad2689 - <rustc_hir_analysis[8fc4af6ff1af4a81]::collect::resolve_bound_vars::BoundVarContext as rustc_hir[73f69b9cc74b8dc1]::intravisit::Visitor>::visit_trait_item  
  26:     0x7ffeaaad999f - <rustc_monomorphize[f6953b6ef87a9045]::partitioning::default::DefaultPartitioning as rustc_monomorphize[f6953b6ef87a9045]::partitioning::Partition>::merge_codegen_units
  27:     0x7ffeaaad5351 - <rustc_monomorphize[f6953b6ef87a9045]::partitioning::default::DefaultPartitioning as rustc_monomorphize[f6953b6ef87a9045]::partitioning::Partition>::merge_codegen_units
  28:     0x7ffeaae4072e - rustc_query_impl[601e9256352b9c6c]::plumbing::loadable_from_disk
  29:     0x7ffeaad0e766 - rustc_query_impl[601e9256352b9c6c]::query_system_fns
  30:     0x7ffeaa37ba70 - <rustc_codegen_llvm[38ab542ff4fd2583]::builder::Builder as rustc_codegen_ssa[8c7fe5fd3a245cd1]::traits::builder::BuilderMethods>::unchecked_umul
  31:     0x7ffeaa35eaa0 - <rustc_codegen_llvm[38ab542ff4fd2583]::LlvmCodegenBackend as rustc_codegen_ssa[8c7fe5fd3a245cd1]::traits::backend::CodegenBackend>::codegen_crate
  32:     0x7ffeaa33b907 - rustc_interface[29ac7e97af8ed434]::proc_macro_decls::provide
  33:     0x7ffeaa333f4a - rustc_interface[29ac7e97af8ed434]::passes::start_codegen
  34:     0x7ffeaa335b19 - rustc_interface[29ac7e97af8ed434]::passes::start_codegen
  35:     0x7ffeaa323be7 - <rustc_interface[29ac7e97af8ed434]::queries::Queries>::ongoing_codegen
  36:     0x7ffeaa2e971a - rustc_driver_impl[98d1546219968491]::args::arg_expand_all
  37:     0x7ffeaa30a98b - <rustc_middle[ae3d3bf8b86cb44f]::ty::SymbolName as core[1d425356198a5fcb]::fmt::Display>::fmt
  38:     0x7ffeaa2e8c59 - rustc_driver_impl[98d1546219968491]::main
  39:     0x7ffeaa309b76 - <rustc_middle[ae3d3bf8b86cb44f]::ty::SymbolName as core[1d425356198a5fcb]::fmt::Display>::fmt
  40:     0x7ffed98ad21c - std::sys::windows::thread::Thread::new::h8b419408ebd8689c
  41:     0x7fff9c34269d - BaseThreadInitThunk
  42:     0x7fff9dbaa9f8 - RtlUserThreadStart

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.71.0-nightly (a77c55248 2023-05-06) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C debuginfo=2 -C debug-assertions=on

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: could not compile `wgpu` (lib)
warning: build failed, waiting for other jobs to finish...
`

**Comment by saethlin** [comment]
@richterk That looks like the same ICE as https://github.com/rust-lang/rust/issues/111321

I'd prefer to refrain from speculation in the absence of any facts from the person who opened this issue. If the issue I linked isn't what you are running into, can you open a new issue?

**Comment by compiler-errors** [comment]
Feel free to reopen this issue with the fields filled in!
