### ISSUE TITLE
Variables not changed using restart in vscode's debug mode 

### ISSUE THREAD

**Issue by hvlxh** [rust-lang/rust#111343]
Works when stopping it and starting it again but not by restarting

https://user-images.githubusercontent.com/91016099/236775238-46cb5820-88c3-4422-9b5d-83b9253e36d8.mp4

**Comment by Nilstrieb** [comment]
Not sure whether the problem is but could you transfer this issue to the rust analyzer repository?
https://github.com/rust-lang/rust-analyzer
Might be an issue with rust analyzers debugger integration.

**Comment by Nilstrieb** [comment]
I guess you need to close it and open a new issue, possibly linking to this one.

**Comment by hvlxh** [comment]
okay
