### ISSUE TITLE
New `#[must_use]` behaviour for async methods does not apply to `Pin<Box<dyn Future<Output = ()>>>`

### ISSUE THREAD

**Issue by tropicbliss** [rust-lang/rust#111458]
Defining traits that contain methods that return such a type:

```rust
pub trait Hello {
    fn hi(&self) -> Pin<Box<dyn Future<Output = i32>>> {
        Box::pin(async { 42 })
    }
}

struct Number(i32);

impl Hello for Number {}

async fn say_hello() {
  let number = Number(42);
  number.hi().await;
}
```

The compiler should probably have warned me about not using the `Output` of the `Future`, consistent with the behaviour of async functions in Rust 1.67.0. This will also work without the need for traits but async traits is one of the most common use cases for such a type.

### Meta

`rustc --version --verbose`: 
```
rustc 1.69.0 (84c898d65 2023-04-16)
binary: rustc
commit-hash: 84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc
commit-date: 2023-04-16
host: x86_64-unknown-linux-gnu
release: 1.69.0
LLVM version: 15.0.7

Also tested on:
rustc 1.71.0-nightly (f9a6b7158 2023-05-05)
binary: rustc
commit-hash: f9a6b71580cd53dd4491d9bb6400f7ee841d9c22
commit-date: 2023-05-05
host: x86_64-unknown-linux-gnu
release: 1.71.0-nightly
LLVM version: 16.0.2
```

<details><summary>Backtrace</summary>
<p>

</p>
</details>

**Comment by eholk** [comment]
We looked at this as the wg-async triage meeting today. We agree this is a bug and that the behavior should be consistent with `#[must_use]` on `async fn` and/or `-> impl Future`.

This is also likely a good first issue for someone wanting to contribute to async.

**Comment by thosakwe** [comment]
> We looked at this as the wg-async triage meeting today. We agree this is a bug and that the behavior should be consistent with `#[must_use]` on `async fn` and/or `-> impl Future`.
> 
> This is also likely a good first issue for someone wanting to contribute to async.

Would you say this is also a good issue for a first-time contributor to Rust?

I'm not super familiar with the language, but I want to contribute to open source compilers, so I'm hoping to potentially take on this task.

**Comment by tsafacjo** [comment]
Can I take this ?

**Comment by eholk** [comment]
Either one of you (@thosakwe or @tsafacjo) are welcome to work on this! If it's your first time contributing to Rust, it might take a while to ramp up on it, but I find the best way to do that is to just do it. If you decided to have a go at it, feel free to ask any questions you have either here or in [#wg-async](https://rust-lang.zulipchat.com/#narrow/stream/187312-wg-async). I tend to watch #wg-async closer than GitHub issues, so you'll probably get a more prompt reply there.

**Comment by Dylan-DPC** [comment]
@tsafacjo this issue wasn't claimed so you are free to claim and work on it if you still are interested. Kindly comment with `@rustbot claim` to claim the issue.

**Comment by max-niederman** [comment]
This is also a very special case of #102238
