### ISSUE TITLE
remap-path-prefix: Binary is missing more than it should

### ISSUE THREAD

**Issue by JohnAZoidberg** [rust-lang/rust#111455]
I tried to build reproducible binaries for this project: https://github.com/FrameworkComputer/inputmodule-rs

Notes:

- I'm building for target `thumbv6m-none-eabi`

To do so, one of the things that I need to do, is to remove local system paths.
So I ran:

```
env \
  RUSTFLAGS="--remap-path-prefix=$$PWD=. --remap-path-prefix=$$CARGO_HOME=home --remap-path-prefix=$$HOME=home" \
  cargo build --release -p ledmatrix
```

It does indeed strip the user paths from the binary but it breaks the binary and I can't convert it to UF2 format.
When strip is enabled I see that it completely nukes the binary and reduces it to just 416K.

```
> strings target/thumbv6m-none-eabi/release/ledmatrix | grep $(whoami)
> ls -lh target/thumbv6m-none-eabi/release/ledmatrix
-rwxrwxr-x 2 zoid zoid 1.1M May 11 13:37 target/thumbv6m-none-eabi/release/ledmatrix
# With strip=true
> ls -lh target/thumbv6m-none-eabi/release/ledmatrix
-rwxrwxr-x 2 zoid zoid 416 May 11 12:58 target/thumbv6m-none-eabi/release/ledmatrix

# Same with and without strip=true
> elf2uf2-rs target/thumbv6m-none-eabi/release/ledmatrix ledmatrix.uf2
Error: "Memory segment 0x010000->0x010094 is outside of valid address range for device"
```

Without remapping the files are bigger:
```
# Regular binary without RUSTFLAGS
> ls -lh target/thumbv6m-none-eabi/release/ledmatrix
-rwxrwxr-x 2 zoid zoid 1.2M May 11 13:06 target/thumbv6m-none-eabi/release/ledmatrix
# Regular binary without RUSTFLAGS (if `strip=true`)
> ls -lh target/thumbv6m-none-eabi/release/ledmatrix
-rwxrwxr-x 2 zoid zoid 48K May 11 12:24 target/thumbv6m-none-eabi/release/ledmatrix
```

### Meta

`rustc --version --verbose`:

```
rustc 1.68.2 (9eb3afe9e 2023-03-27)
binary: rustc
commit-hash: 9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0
commit-date: 2023-03-27
host: x86_64-unknown-linux-gnu
release: 1.68.2
LLVM version: 15.0.6
```

same with 1.69.0

```
rustc 1.69.0 (84c898d65 2023-04-16)
binary: rustc
commit-hash: 84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc
commit-date: 2023-04-16
host: x86_64-unknown-linux-gnu
release: 1.69.0
LLVM version: 15.0.7
```

same with nightly 1.71.0

```
rustc 1.71.0-nightly (cba14074b 2023-05-10)
binary: rustc
commit-hash: cba14074bb4cc12bfe918eabd0d52a3999b2a461
commit-date: 2023-05-10
host: x86_64-unknown-linux-gnu
release: 1.71.0-nightly
LLVM version: 16.0.2
```

## TODO

- [ ] Create minimal example to reproduce

**Comment by JohnAZoidberg** [comment]
Sorry for the vague description. I'll try to reduce the example and see what's missing.

**Comment by SNCPlay42** [comment]
The project has a `rustflags` key in its [`.cargo/config.toml`](https://github.com/FrameworkComputer/inputmodule-rs/blob/main/.cargo/config.toml), which the `RUSTFLAGS` environment variable [will override](https://doc.rust-lang.org/cargo/reference/config.html?highlight=RUSTFLAGS#buildrustflags). If you add the arguments there to the `RUSTFLAGS` you're passing in, do you get a binary that works as expected?

**Comment by JohnAZoidberg** [comment]
You're right. That's it. If I add these arguments to `RUSTFLAGS` the build works just fine.
Thanks you very much!
