### ISSUE TITLE
regression: ImplTrait vs. Ctor expected ICE

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#111484]
https://crater-reports.s3.amazonaws.com/beta-1.70-2/beta-2023-05-08/gh/zdata-inc.kustd/log.txt

```
[INFO] [stderr] thread 'rustc' panicked at 'assertion failed: `(left == right)`
[INFO] [stderr]   left: `ImplTrait`,
[INFO] [stderr]  right: `Ctor`', compiler/rustc_metadata/src/rmeta/decoder.rs:1127:17
[INFO] [stderr] stack backtrace:
```

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23111484.20regression.3A.20ImplTrait.20vs.2E.20Ctor.20expected.20ICE)).

@rustbot label -I-prioritize +P-medium

**Comment by Mark-Simulacrum** [comment]
Closing as fixed, fix is merged and backported.
