### ISSUE TITLE
Inline asm make code to fail with LTO accross all rust channels

### ISSUE THREAD

**Issue by SyntheticBird45** [rust-lang/rust#111412]
I wanted to make a custom inline assembly implementation of getrandom, by directly calling syscall, instead of using libc. I needed to encrypt data using the aes-gcm-siv crate. Here's a minimal code reproducing the error I get on a larger codebase:

```rust
use std::arch::asm;
use aes_gcm_siv::{KeyInit, Nonce, AeadInPlace, Aes256GcmSiv};
‎
fn main() {
‎
	let mut big_data = [0u8; 2048];
	fill_random_bytes(&mut big_data);
	let mut uuid = [0u8; 16];
	let mut aes_key = [0u8; 32];
	fill_random_bytes(&mut aes_key);
	fill_random_bytes(&mut uuid);
‎
	let aes = Aes256GcmSiv::new_from_slice(&aes_key).unwrap();
	let mut nonce = [0u8; 12];
	fill_random_bytes(&mut nonce);
	let mut tag = [0u8; 16];
‎
	let tg = aes.encrypt_in_place_detached(Nonce::from_slice(&nonce), b"", &mut big_data).unwrap();
	tag.copy_from_slice(tg.as_ref());
‎
	if let Err(err) = aes.decrypt_in_place_detached(Nonce::from_slice(&nonce), b"", &mut big_data, tag.as_ref().into()) {
		println!("Error at decrypt : {}", err);
	}
}
‎
#[cfg(target_os = "linux")]
fn fill_random_bytes(buf: &mut [u8]) -> u8 {
	let res: isize;
	unsafe {
		let len = buf.len();
		let ptr = buf.as_mut_ptr();
		asm!(
			// Invoking syscall
			"syscall",
‎
			in("rax") 318,
			in("rdi") ptr,
			in("rsi") len,
			in("rdx") 0,
			lateout("rax") res,
		);
	}
	res.to_be_bytes()[0]
}
```

I expected to see this happen: With `lto="off"` the decryption works correctly.

Instead, this happened: with `lto=false|lto="thin"|lto="fat"` this return an `AEAD::error`, making the decryption unsuccessful. The error isn't decorative and the buffer isn't the decrypted data. Please note that replacing this custom implementation by the getrandom crate solve the issue : 
```rust
fn fill_random_bytes(buf: &mut [u8]) {

	getrandom::getrandom(buf).unwrap()
}
```
This make everything works normal.

### Meta

The issue persist on rust beta and nightly. Note that Nightly even fail to decrypt with lto="off".
`rustc --version --verbose`:
```
rustc 1.69.0 (84c898d65 2023-04-16)
binary: rustc
commit-hash: 84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc
commit-date: 2023-04-16
host: x86_64-unknown-linux-gnu
release: 1.69.0
LLVM version: 15.0.7
```

<details><summary>Backtrace</summary>
<p>

```
      Running `target/release/encryption-random-asm`
Error at decrypt : aead::Error
```
</p>
</details>

**Comment by taiki-e** [comment]
[`syscall`](https://www.felixcloutier.com/x86/syscall) also modifies rcx and r11, so I think you have to mark them as clobbered (i.e., `out("rcx") _, out("r11") _,`).

**Comment by SyntheticBird45** [comment]
> [`syscall`](https://www.felixcloutier.com/x86/syscall) also modifies rcx and r11, so I think you have to mark them as clobbered (i.e., `out("rcx") _, out("r11") _,`).

Thanks you this resolved the issue.
