### ISSUE TITLE
Inaccessible local modules nested in functions are documented

### ISSUE THREAD

**Issue by calebzulawski** [rust-lang/rust#111415]
Consider the following code

```rust
pub fn foo() {
    pub mod inaccessible {}
}
```

`inaccessible` is local to `foo` and inaccessible, and should not be documented.  Instead, rustdoc currently documents the module at the same level as `foo`.

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0 (84c898d65 2023-04-16)
binary: rustc
commit-hash: 84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc
commit-date: 2023-04-16
host: x86_64-apple-darwin
release: 1.69.0
LLVM version: 15.0.7
```

</details>

**Comment by compiler-errors** [comment]
cc @GuillaumeGomez does this have to do with those changes you made to item collection?

**Comment by GuillaumeGomez** [comment]
Oh. I'm at least happy to realize that I didn't break it recently. Thanks for the report. Will fix it monday.
