### ISSUE TITLE
Linking a staticlib into shared C library or executable with gcc causes considerbly larger binary than linking into a cdylib or executable with rustc

### ISSUE THREAD

**Issue by sdroege** [rust-lang/rust#111593]
See https://github.com/sdroege/rust-staticlib-bloat-test for the code. This doesn't use cargo to make the actual compiler invocations clear (the same behaviour can be observed with cargo).

With Rust 1.69 and gcc 13.1.1 on Linux x86-64 the following can be observed:

| | unstripped | stripped (`--strip-all`) |
|-|-|-|
| Rust executable (`my_test`) | 4.1MB | 315kB |
| Rust cdylib (`libstaticlib.so`) | 4.0MB | 290kB |
| gcc executable (`my_staticlib_test`) | 5.2MB (+ 27%) | 1.1MB (+ 355%) |
| gcc shared library (`libmy_staticlib_test_dylib.so`) | 5.6MB (+ 40%) |  1.5MB (+ 517%) |

The actual size comes from the enabled overflow checks (`-C debug-assertions=on`) , and thus all the panic and string formatting machinery that is included. However, this should be approximately the same code in either case so that doesn't explain the difference. (Disabling the overflow checks gives a more expected result because the function from the library compiles down to a few instructions) Also note that this compiles with `-C panic=abort` so having the assertion in an `extern "C"` function is not UB.

The question here now is what exactly the difference between both cases is, and how the `staticlib` case can be improved. Maybe this requires changes in the compiler, maybe this just requires invoking the linker differently (in which case this would be useful to add to the documentation).

**Comment by bjorn3** [comment]
For `cdylib` we use a version script to limit the exported symbols in combination with `--gc-sections` to remove unused functions. Did you pass `--gc-sections` when linking yourself?

**Comment by sdroege** [comment]
That makes a lot of sense, sorry for missing that. Passing `-Wl,--gc-sections` solves it for the executable. I guess for the shared library a version script to not re-export random Rust symbols would also fix it (will test later and update this comment).

Do you think this would be useful to add to e.g. https://doc.rust-lang.org/reference/linkage.html ?

**Comment by bjorn3** [comment]
> I guess for the shared library a version script to not re-export random Rust symbols would also fix it (will test later and update this comment).

You need both. Without the version script the linker needs to export all symbols, but without `--gc-sections` the linker won't omit unused functions even if the version script says they aren't exported.

> Do you think this would be useful to add to e.g. https://doc.rust-lang.org/reference/linkage.html ?

Yeah, could be useful to add a recommendation to pass `-Wl,--gc-sections` (and `-dead_strip` on macOS) there.

**Comment by sdroege** [comment]
> You need both. Without the version script the linker needs to export all symbols, but without `--gc-sections` the linker won't omit unused functions even if the version script says they aren't exported.

Yeah, with that it's also the same in both cases. Thanks!

I'll prepare a PR for adding a sentence about that to the docs some time later :)
