### ISSUE TITLE
"can't use generic parameters from outer function" only when in nightly

### ISSUE THREAD

**Issue by b-paul** [rust-lang/rust#111541]
### Code

I made a blank cargo project (ran `cargo init` in an empty directory), and added dependencies to my Cargo.toml like so:

```
[package]
name = "typst-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typst = { git = "https://github.com/typst/typst.git" }
typst-library = { git = "https://github.com/typst/typst.git" }
```

Originally when I went to run `RUSTFLAGS="-Z macro-backtrace" cargo build`, I was in nightly, and got a compile error `error[E0401]: can't use generic parameters from outer function` (full error below). Then, when i switched to stable, there was no error and everything built fine!

```
 > RUSTFLAGS="-Z macro-backtrace" cargo b
   Compiling hayagriva v0.3.0
   Compiling typst v0.3.0 (https://github.com/typst/typst.git#4b17c3f5)
error[E0401]: can't use generic parameters from outer function
   --> /home/bpaul/.cargo/git/checkouts/typst-6808799b0d8fdaa9/4b17c3f/src/model/content.rs:545:1
    |
545 | #[element]
    | ^^^^^^^^^^
    | |
    | use of generic parameter from outer function
    | can't use `Self` here
    | in this procedural macro expansion
    |
   ::: /home/bpaul/.cargo/git/checkouts/typst-6808799b0d8fdaa9/4b17c3f/macros/src/lib.rs:31:1
    |
31  | pub fn element(stream: BoundaryStream, item: BoundaryStream) -> BoundaryStream {
    | ------------------------------------------------------------------------------ in this expansion of `#[element]`

error[E0401]: can't use generic parameters from outer function
   --> /home/bpaul/.cargo/git/checkouts/typst-6808799b0d8fdaa9/4b17c3f/src/model/content.rs:550:1
    |
550 | #[element]
    | ^^^^^^^^^^
    | |
    | use of generic parameter from outer function
    | can't use `Self` here
    | in this procedural macro expansion
    |
   ::: /home/bpaul/.cargo/git/checkouts/typst-6808799b0d8fdaa9/4b17c3f/macros/src/lib.rs:31:1
    |
31  | pub fn element(stream: BoundaryStream, item: BoundaryStream) -> BoundaryStream {
    | ------------------------------------------------------------------------------ in this expansion of `#[element]`

error[E0401]: can't use generic parameters from outer function
   --> /home/bpaul/.cargo/git/checkouts/typst-6808799b0d8fdaa9/4b17c3f/src/model/content.rs:557:1
    |
557 | #[element(Behave)]
    | ^^^^^^^^^^^^^^^^^^
    | |
    | use of generic parameter from outer function
    | can't use `Self` here
    | in this procedural macro expansion
    |
   ::: /home/bpaul/.cargo/git/checkouts/typst-6808799b0d8fdaa9/4b17c3f/macros/src/lib.rs:31:1
    |
31  | pub fn element(stream: BoundaryStream, item: BoundaryStream) -> BoundaryStream {
    | ------------------------------------------------------------------------------ in this expansion of `#[element]`

For more information about this error, try `rustc --explain E0401`.
error: could not compile `typst` (lib) due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
```

### Version it worked on

It most recently worked on: Rust 1.69

### Version with regression

`rustc --version --verbose`:
```
rustc 1.71.0-nightly (4a59ba4d5 2023-05-12)
binary: rustc
commit-hash: 4a59ba4d54a3ec0d8ea1e82b7eeb5c8b0162de04
commit-date: 2023-05-12
host: x86_64-unknown-linux-gnu
release: 1.71.0-nightly
LLVM version: 16.0.2
```

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

**Comment by Nilstrieb** [comment]
searched nightlies: from nightly-2023-02-15 to nightly-2023-05-13
regressed nightly: nightly-2023-05-05
searched commit range: https://github.com/rust-lang/rust/compare/473f916d836cc662c5bdbb0d40af9fb4678fab9e...74c4821045c68d42bb8b8a7c998bdb5c2a72bd0d
regressed commit: https://github.com/rust-lang/rust/commit/eac35583d2ffb5ed9e564dee0822c9a244058ee0

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.6</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc 2023-02-15 --access github
```
</details>

rollup  #111174 

it didn't want to bisect the perf builds for some reason but i guess #111020 or #111103 could be at fault? haven't looked into the actual issue in detail, since it's behind a macro

@cjgillot @BoxyUwU you probably know something about this anyways even if it may not be your fault

**Comment by BoxyUwU** [comment]
its not #111103 that is generic_const_exprs only code

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23111541.20.22can't.20use.20generic.20parameters.20from.20outer.20function.22.20.E2.80.A6)).

@rustbot label -I-prioritize +P-high +T-compiler
