### ISSUE TITLE
Cannot coerce from &mut Box<[u8; 4096]> to &mut [u8]

### ISSUE THREAD

**Issue by safinaskar** [rust-lang/rust#111676]
Consider this code:
```rust
let mut a = Box::new([0u8; 4096]);
let b = &mut a;
let c: &mut [u8; 4096] = b;
let d: &mut [u8] = c;
```
It works. Now consider this:
```rust
let mut a = Box::new([0u8; 4096]);
let b = &mut a;
let d: &mut [u8] = b;
```
It doesn't work. So, it this particular case coercions are not transitive. But the reference requires them to be transitive. So, please, fix. I actually got this when writing my production code. If you want, I can show actual code to prove that this is actually needed.

rustc stable 1.69.0

**Comment by asquared31415** [comment]
```rust
    let x = Box::new([0_u8; 4096]);
    let y: &[u8] = &*x;
```

**Comment by safinaskar** [comment]
@asquared31415 , thanks! But I still thinks this is a bug, because the reference requires coercion to be transitive

**Comment by asquared31415** [comment]
[The Relevant Part of the Reference](https://doc.rust-lang.org/reference/type-coercions.html#coercion-types) specifically says

> T_1 to T_3 where T_1 coerces to T_2 and T_2 coerces to T_3 (transitive case)
> **Note that this is not fully supported yet.**

(emphasis mine)

Also part of this is an *unsizing coercion* which isn't subject to the same rules.

**Comment by jyn514** [comment]
This doesn't look like a bug and there is a simple workaround, so I'm going to close this issue.
