### ISSUE TITLE
Specify trait implementation, resolution, and coherence for 1.0

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#11166]
Niko has a grab-bag of issues over on #5527.

There are a bunch of desiderata for traits in Rust, and we won't get to all of them for 1.0.

But we do need to firm up exactly what the core semantics are (for how trait matching is done, and what the limits are for the backward-compatible core of the language), with a specification against which we can compare the implementation.

**Comment by aturon** [comment]
Nominating for removal from P-backcompat-lang. The spec/documentation side is probably covered by existing bugs; this issue should perhaps be closed.

**Comment by pnkfelix** [comment]
Assigning 1.0 milestone (specifically the writeup of the semantics -- I consider it polish).

**Comment by pnkfelix** [comment]
(I probably should have removed P-backcompat-lang from this ticket when I assigned this to 1.0 and categorized it as a polish issue.  It is *possible* that writing up the semantics will expose bugs that would necessitate a change to the language specification, but it is highly unlikely, and probably does not justify the label.)

**Comment by pnkfelix** [comment]
closing; if someone can come up with a spec, great, but we're not going to block anything ourselves to do so.
