### ISSUE TITLE
Install bootstrap fails to use configured prefix due to Tarball add_renamed_file

### ISSUE THREAD

**Issue by okeuday** [rust-lang/rust#111653]
I tried this code, due to installing from source:

https://github.com/rust-lang/rust/blob/b652d9a0fd5c5a7eeacd1ae8299166941c221230/src/bootstrap/dist.rs#L1074

with the installation commands:

    ./configure --prefix=/path/to/installation/using/a/non/root/user/rust-1.69.0 --enable-extended
    python3 ./x.py build
    python3 ./x.py install

I expected to see the installation succeed.

Instead, the installation failed when processing the cargo installation.  Only the cargo installation uses the `Tarball` `add_renamed_file` function, so the problem appears isolated to that single function call, due to the implementation of `add_renamed_file`.

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0-dev (84c898d65 2023-04-16) (built from a source tarball)
binary: rustc
commit-hash: 84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc
commit-date: 2023-04-16
host: x86_64-unknown-linux-gnu
release: 1.69.0-dev
LLVM version: 15.0.7
```

<details><summary>Backtrace</summary>
<p>

```
The output only describes the installation failing with only cargo installed.  I didn't save the output.
```

</p>
</details>

**Comment by albertlarsan68** [comment]
Seems related to #110906

**Comment by okeuday** [comment]
@albertlarsan68  Thank you for pointing-out https://github.com/rust-lang/rust/pull/110906 !  It is the same problem.  Closing this as a duplicate.

**Comment by albertlarsan68** [comment]
It is not an issue, but this PR will fix this issue. Reopening to keep track of progress.

**Comment by albertlarsan68** [comment]
@okeuday Does the PR fix the issue?
