### ISSUE TITLE
Tracking Issue for `UnsafeCell::from_mut`

### ISSUE THREAD

**Issue by JoJoJet** [rust-lang/rust#111645]
Feature gate: `#![feature(unsafe_cell_from_mut)]`

This is a tracking issue for `UnsafeCell::from_mut`, which makes it possible to convert `&mut T` to `&mut UnsafeCell<T>` in safe code.

### Public API

```rust
// core::cell

impl<T: ?Sized> UnsafeCell<T> {
    pub fn from_mut(&mut T) -> &mut Self;
}
```

### Steps / History

- [x] ACP: https://github.com/rust-lang/libs-team/issues/198
- [x] Implementation: #111654
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by JoJoJet** [comment]
For a straightforward addition like this, what's an appropriate amount of time to wait before pushing for stabilization?

**Comment by QuineDot** [comment]
This should also be added to `SyncUnsafeCell` to keep their APIs the same.

**Comment by dtolnay** [comment]
@rust-lang/libs-api:
@rfcbot fcp merge
