### ISSUE TITLE
`--print native-static-libs` of a `staticlib` crate does not print libraries linked in via `#[link]` attribute or `-l` parameters

### ISSUE THREAD

**Issue by sdroege** [rust-lang/rust#111643]
This is with Rust 1.69 but was probably always the case.

Example:

#### lib.rs

```rust
#[no_mangle]
pub extern "C" fn my_staticlib_add(left: i32, right: i32) -> i32 {
    // Obviously makes no sense but...
    unsafe {
        g_free(std::ptr::null_mut());
    }
    left + right
}

#[link(name = "glib-2.0")]
extern "C" {
    fn g_free(p: *mut ());
}
```

Compiling with

```shell
$ rustc --crate-type staticlib --print native-static-libs --edition=2018 --crate-name staticlib --emit link -o libstaticlib.a lib.rs
```

prints

```
note: Link against the following native artifacts when linking against this static library. The order and any duplication can be significant on some platforms.

note: native-static-libs: -lgcc_s -lutil -lrt -lpthread -lm -ldl -lc
```

Similarly when providing `-lglib-2.0` nothing changes. I didn't really follow how `rustc` collects the libraries but I think it's via the `native_libraries` query in `compiler/rustc_middle/src/query/mod.rs` which claims

```
    /// Look up all native libraries this crate depends on.
    /// These are assembled from the following places:
    /// - `extern` blocks (depending on their `link` attributes)
    /// - the `libs` (`-l`) option
```

so this should be included AFAIU. Also the rationale of `native-static-libs` was to provide all libraries needed to link to the resulting `staticlib`, which is not the case in the above example.

----

CC @kornelski who originally implemented this feature.

**Comment by Urgau** [comment]
It works as expected if the `#[link]` attribute is used in a dependencies.

It seems to me that the `link_staticlib` function,

https://github.com/rust-lang/rust/blob/a673ad6b5746a6256cb898edb8b888163df1872c/compiler/rustc_codegen_ssa/src/back/link.rs#L478-L484

is forgetting to add the current native libs.

Doing something like this correctly adds `-lglib-2.0` to the output (even when passed via the command line).
```rust
all_native_libs.extend_from_slice(&codegen_results.crate_info.used_libraries);
```

**Comment by bjorn3** [comment]
Yeah, I think adding `all_native_libs.extend_from_slice(&codegen_results.crate_info.used_libraries);` is the correct fix. That adds the same information as `codegen_results.crate_info.native_libraries` does for dependencies.

**Comment by kornelski** [comment]
Beware that `--print native-static-libs` is rather quirky. Originally Rust printed lines during build with information which link flags need to be added to use the static library it builds, and `--print native-static-libs` is a blunt way of redirecting these "warnings". I don't know whether omission of `#[link]` is a bug or the old warnings just weren't meant to print them.

**Comment by bjorn3** [comment]
I can't imagine it to be a deliberate omission as `--print native-static-libs` is the only way to know how to correctly link any arbitrary staticlib afaik.
