### ISSUE TITLE
Proposal for built-in async runtime.

### ISSUE THREAD

**Issue by fenginsc** [rust-lang/rust#111737]
Currently there are two main asynchronous libraries available, async-std and tokio, but asynchronous as a feature of rust language, I think there should be a built-in runtime, when the user is not satisfied with the built-in runtime can choose another runtime, but a built-in asynchronous runtime can be used out of the box, and finally can consider direct async support for the main method.
The built-in runtime also facilitates users with standalone installers to enjoy asynchronous programming without network access and without the need for networked installation dependencies.
Thanks!

**Comment by SkiFire13** [comment]
This has already been considered in the past, what are you proposing in addition to what has been discussed in e.g. https://internals.rust-lang.org/t/elementary-default-runtime/18423/19 (just to link to a recent discussion)?

**Comment by fenginsc** [comment]
My main purpose is to make rust easier to use, less difficult to use, more friendly to novices, if the syntax is designed to be too complex, you can generally introduce syntactic sugar to reduce the difficulty of use, then asynchronous functions since the language is a built-in function, but not directly support this is too strange, the current use of asynchronous functions need to install third-party asynchronous runtime dependencies, so that users can choose their own. In order to reduce the difficulty and user experience, it is better to build a standard asynchronous runtime directly, because what runtime to choose is not what a novice needs to consider, what a novice needs is to learn the language functions or syntax features first, when the built-in runtime is not powerful enough, then the user can manually switch to other third-party runtime libraries as needed, so I think a built-in runtime So I think it is necessary to build a runtime that is out-of-the-box and newbie-friendly.

**Comment by fenginsc** [comment]
> This has already been considered in the past, what are you proposing in addition to what has been discussed in e.g. https://internals.rust-lang.org/t/elementary-default-runtime/18423/19 (just to link to a recent discussion)?

I have learned that some of the current proposals, some of the practical application challenges, but of course eventually rust should include a built-in asynchronous runtime, I believe it is only a matter of time.

**Comment by workingjubilee** [comment]
The appropriate venue for this is an [API Change Proposal](https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html) or, more likely, one of the discussion forums like iRLO, if you do not have a specific proposal in mind yet. Thank you!
