### ISSUE TITLE
Tracking Issue for `BufRead::skip_until`

### ISSUE THREAD

**Issue by WilliamVenner** [rust-lang/rust#111735]
Feature gate: `#![feature(bufread_skip_until)]`

This is a tracking issue for `BufRead::skip_until`, which is similar to `BufRead::read_until` but doesn't write data to an output buffer; it simply skips past it.

This is useful when, for example, reading a binary file format but wanting to skip some data, like a NUL-terminated string.

### Public API

```rust
// trait BufRead

fn skip_until(&mut self, byte: u8) -> std::io::Result<usize>;
```

### Steps / History

- [x] Implementation: #98943 
- [x] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by IS2511** [comment]
Any updates? Just stumbled into a use-case for this and can't use nightly.

**Comment by WilliamVenner** [comment]
@rustbot ping libs

Shall we FCP?

**Comment by dtolnay** [comment]
@rust-lang/libs-api:
@rfcbot fcp merge

https://doc.rust-lang.org/nightly/std/io/trait.BufRead.html#method.skip_until
