### ISSUE TITLE
Programs with crates which parse arguments don't run in Powershel/cmd.exe on Windows

### ISSUE THREAD

**Issue by robert-dzikowski** [rust-lang/rust#111805]
I wrote simple programs that parse CLI arguments, I used clap crate and argparse crate.
When I run `cargo run` it works, but when I run executable (eg. app.exe) in Powershell and cmd.exe I get this error:
```
'app.exe' is not recognized as an internal or external command,
operable program or batch file.
```
But running app.exe in Bash (part of GIT client git-scm.com) and Cmder (cmder.app) works.
Ordinary parsing arguments programs, i.e. using std::env::args(), work in Powershell. 
OS: Windows 10.
 
I tried this code:
argparse version

```rust
extern crate argparse;
use argparse::{ArgumentParser, Store, StoreTrue};

fn main() {
    let mut verbose = false;
    let mut name = "World".to_string();
    {
        // this block limits scope of borrows by ap.refer() method
        let mut ap = ArgumentParser::new();
        ap.set_description("Greet somebody.");
        ap.refer(&mut verbose).add_option(
            &["-v", "--verbose"],
            StoreTrue,
            "Be verbose",
        );
        ap.refer(&mut name).add_option(
            &["--name"],
            Store,
            "Name for the greeting",
        );
        ap.parse_args_or_exit();
    }

    if verbose {
        println!("name is {}", name);
    }
    println!("Hello {}!", name);
//-- snip --
```

I expected to see this happen: 
*Hello World!*

Instead, this happened: 
*'app.exe' is not recognized as an internal or external command,
operable program or batch file.*

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0 (84c898d65 2023-04-16)
binary: rustc
commit-hash: 84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc
commit-date: 2023-04-16
host: x86_64-pc-windows-msvc
release: 1.69.0
LLVM version: 15.0.7
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by jyn514** [comment]
This is working with cargo run, so it's not a problem with the compiler itself (you probably need `target\debug\app.exe or something like that).

The issue tracker is not a support forum. For future questions please ask in one of these places:

https://discord.gg/rust-lang/
https://discord.gg/rust-lang-community/
https://users.rust-lang.org/
https://rust-lang.zulipchat.com/

**Comment by robert-dzikowski** [comment]
I didn't ask for support I simply reported a bug. I can run my programs in Bash or Cmder, no problem.
