### ISSUE TITLE
Bogus "non-exhaustive patterns" error with half-open range patterns on `isize`/`usize`

### ISSUE THREAD

**Issue by Jules-Bertholet** [rust-lang/rust#111859]
I tried this code:

```rust
fn test(a: usize) {
    match a {
        0.. => (),
    }
}
```

I expected to see this happen: Successful compilation, the match is exhaustive

Instead, this happened:

```
error[E0004]: non-exhaustive patterns: `_` not covered
 --> src/lib.rs:2:11
  |
2 |     match a {
  |           ^ pattern `_` not covered
  |
  = note: the matched value is of type `usize`
  = note: `usize` does not have a fixed maximum value, so a wildcard `_` is necessary to match exhaustively
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
  |
3 ~         0.. => (),
4 ~         _ => todo!(),
  |

For more information about this error, try `rustc --explain E0004`.
```

`isize` (with `..=0` and `1..` patterns) has the same issue, but the other numeric types don't.

### Meta

`rustc --version --verbose`:
```
1.71.0-nightly (2023-05-21 9d871b0617a4b3d6610b)
```

@rustbot label A-patterns A-exhaustiveness-checking

**Comment by rlidwka** [comment]
I've just ran into this issue with a code similar to this:

```rs
fn test(vec: Vec<f64>) -> &'static str {
    match vec.len() {
        2.. => "two or more items",
        1 => "one item",
        0 => "zero items",
    }
}
```

easy to work around, but the error is very much unexpected

**Comment by Nadrieril** [comment]
This is now fixed (https://github.com/rust-lang/rust/pull/116692)! You example is accepted on nightly ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=a8e776241f8ec2f8c71cd3f2be412659)) and soon will in stable.
