### ISSUE TITLE
Document additional constructs caught by the `unsafe_code` lint

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#111967]
Today, the `unsafe_code` lint documentation <https://doc.rust-lang.org/nightly/rustc/lints/listing/allowed-by-default.html#unsafe-code> only mentions that it catches `unsafe` *blocks*.

But it actually catches more than that, for example
```text
error: declaration of a `no_mangle` function
 --> src/lib.rs:3:1
  |
3 | #[no_mangle]
  | ^^^^^^^^^^^^
  |
  = note: the linker's behavior with multiple libraries exporting duplicate symbol names is undefined and Rust cannot provide guarantees when you manually override them
note: the lint level is defined here
 --> src/lib.rs:1:11
  |
1 | #![forbid(unsafe_code)]
  |           ^^^^^^^^^^^
```

It would be nice for the documentation to include examples of those other things that the lint catches because they might result in unsoundness despite the `unsafe` token not appearing in them.

**Comment by eval-exec** [comment]
Do we need to indicate `unsafe_code` will emit `no_mangle`, `export_name` and `link_section` in the `unsafe_code` lint document?
https://github.com/rust-lang/rust/blob/5783e699b3a8a2fbef7294f200c16a2614c3e7ed/compiler/rustc_lint/src/builtin.rs#L375-L410
