### ISSUE TITLE
RPIT allows defining use with invalid args

### ISSUE THREAD

**Issue by aliemjay** [rust-lang/rust#111935]
**Note**: All examples in this post was fixed in #112842. However the issue persists for lifetime arguments. See [this comment](https://github.com/rust-lang/rust/issues/111935#issuecomment-1770497883) for more.

---

The following compiles since v1.62:
```rust
fn foo<T>() -> impl Sized {
    let _: () = foo::<u8>();
}
```

While the equivalent TAIT version doesn't compile because `Opaque<u8> == u8` is not a valid defining use for `Opaque` (because it is ambiguous whether `Opaque<T> = T` or `Opaque<T> = u8`):
```rust
#![feature(type_alias_impl_trait)]

type Opaque<T> = impl Sized;
fn foo<T>() -> Opaque<T> {
    let _: () = foo::<u8>();
    //~^ ERROR expected generic type parameter, found `u8`
}
```

I believe that TAIT behavior is the correct one because it's maximally compatible with future changes. Keeping this behavior for RPIT can also result in some surprising errors:
```rust
fn foo<T>(val: T) -> impl Sized {
    let _: u8 = foo(0u8);
    val
    //~^ ERROR concrete type differs from previous defining opaque type use
}
```

This was stabilized (most likely unintentionally) in #94081. Cc @oli-obk.

See related code:
https://github.com/rust-lang/rust/blob/776f22292fb5c2cc45f029d4b754662120732a6a/compiler/rustc_borrowck/src/region_infer/opaque_types.rs#L335

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23111935.20RPIT.20allows.20defining.20use.20with.20invalid.20substs)).

@rustbot label -I-prioritize +P-high

**Comment by aliemjay** [comment]
The PR #112842 fixed this issue for type arguments. The same issue persists for lifetime arguments. 

The following snippets are examples of invalid defining uses that should not compile:
```rust
// Lt indirection is necessary to make the lifetime of the function late-bound,
// in order to bypass some other bugs.
type Lt<'lt> = Option<*mut &'lt ()>;

// PASS!
#[cfg(case1)]
fn foo<'a>(_: Lt<'a>) -> impl Sized + 'a {
    let _ret: () = foo(Lt::<'static>::None);
    // invalid defining use: Opaque<'static> := ()
}

// ICE!
#[cfg(case2)]
fn foo<'a>(_: Lt<'a>) -> impl Sized + 'a {
    let _ret: () = foo(Lt::<'_>::None);
    // invalid defining use: Opaque<'_> := ()
}

// PASS!
#[cfg(case3)]
fn foo<'a, 'b>(_: Lt<'a>, _: Lt<'b>) -> impl Sized + 'a {
    let _ret: () = foo(Lt::<'a>::None, Lt::<'a>::None);
    // invalid defining use: Opaque<'a, 'a> := ()
    // because of the use of equal lifetimes in args
}
```

**Comment by lcnr** [comment]
cc #113916
