### ISSUE TITLE
Stdlib contains a static initializer on Linux, without any way to opt out

### ISSUE THREAD

**Issue by danakj** [rust-lang/rust#111921]
The Rust stdlib has [a single static initializer](https://github.com/rust-lang/rust/blob/b08148f6a76010ea3d4e91d61245aa7aac59e4b4/library/std/src/sys/unix/args.rs#L107-L127) on the cfg `#[cfg(all(target_os = "linux", target_env = "gnu"))]`.

In general the stdlib is already avoiding static initializers, and this one is added to support interaction with glibc from inside a cdylib. Typically, args::init() is called during startup which initializes the std::env::args() data structures. But in a cdylib, there’s no startup call that gets through, whereas glibc will call the function pointer in this static initializer.

We would like to provide a mechanism to remove this static initializer, and accept that std::env::args() will be empty as a result inside a cdylib. Since Chromium (as in chrome.exe) does not use argument parsing in Rust, we are fine with the result being, and prefer, that the argument/environment are empty on Linux with glibc with the static initializer being removed if we have Rust code in a cdylib.

While this particular static initializer is not hugely problematic, it is a much better engineering position to work from if there are none at all.

Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1445935

# Static Initializers are a problem

Static initialization is known to be a problem, due to the [Static Initialization Order Fiasco](https://en.cppreference.com/w/cpp/language/siof). They also have a measurable negative impact on startup speed, even on modern computers. The Chromium project [bans static initializers](https://chromium.googlesource.com/chromium/src/+/master/docs/static_initializers.md) to avoid these problems.

Many software shops try to avoid static initializers. The Google C++ Style guide [tries to ban them](https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables) but hedges a little.

LLVM provides link-time mechanisms to override a symbol and remove static initializers, such as with [`__llvm_pgo_register_write_atexit()` in compiler-rt](https://github.com/llvm/llvm-project/commit/775c178a90d8859a5da939d738fad248fde6edcd).

# Removing the Static Initializer

We propose to add a feature `explicit-init-args-with-glibc` which defaults off, and gate the static initializer’s presence on this feature.

As well, when the feature is enabled, allow the [`args::imp::init()`](https://github.com/rust-lang/rust/blob/d5699874dc07d2dfb262d007293853f73c171f7e/library/std/src/sys/unix/args.rs#L99-L105) function to call really_init() directly. Basically, this feature disables the “linux + gnu” cfg check.

When this feature is enabled and the stdlib is linked statically into a Rust executable or Rust dylib, the init() path will be properly called, explicitly.

When statically linked into a C executable or a C shared-library, the init() path [is already not called](https://github.com/rust-lang/rust/blob/d5699874dc07d2dfb262d007293853f73c171f7e/library/std/src/rt.rs#L71-L107). When the feature is enabled, it will also not be called in Rust cdylibs, and the `std::env::args()` will not be available.

# Alternatives

A colleague suggested we could change the cfg guard in sys/unix/args.rs to be a single check like `#[cfg(use-glibc-static-initializer)]` and then have the `build.rs` file add that cfg flag when on Linux/GNU and the `explicit-init-args-with-glibc` feature is not enabled. This moves the combination of these things to a single place in `build.rs` at the cost of adding a layer of abstraction.

# Proposed Change

PR is here: https://github.com/rust-lang/rust/pull/111920

**Comment by jyn514** [comment]
Do you have a benchmark of how much overhead this static initializer adds? If it's small enough, I'm not sure this is worth the new complexity ...

**Comment by danakj** [comment]
This is not about overhead of any one initializer, it is that we explicitly want to ban _all_ static initializers rather than litigate about each one. Every library wants to add one for itself, yet we've been able to eliminate them because they are not necessary (for use cases like ours at least). It is far more straightforward to have no static initializers than "just a few" where you now have to draw lines, and we have CI tooling that prevents any static initializer from being added to the chrome binary. We could add an exception here in our CI but we know we're not alone in wanting to build binaries that are clean from static initializers as well. I hope the complexity (changing the already-existing cfg guards) is reasonable to help us achieve the goals of avoiding all static initializers in our binary.

**Comment by thomcc** [comment]
> This is not about overhead of any one initializer, it is that we explicitly want to ban all static initializers rather than litigate about each one

Right, and we're in the opposite position. That is, the issue here is not this specific[^1] static initializer. You're effectively asking us to make the policy change to "the rust runtime and standard library should not require any static initializers" (and should have feature flags that allow turning them off), which I'm not sure is something we want to agree to.

[^1]: Although note that there are others -- this is the only one on x86_64 Linux, but many aarch64 targets, and a few of the windows targets also have static initializers.

**Comment by danakj** [comment]
Yeah, we would very much like the ability to compile the stdlib without static initializers, as other upstream deps like LLVM have been willing to do. To do otherwise would make Rust significantly riskier for being accepted in Chrome. :/

I saw the Windows one and it is for compat with old versions. It seemed straightforward to remove that as well for our build configuration, if I understood correctly. I did not see the aarch64 initializers.

**Comment by chbaker0** [comment]
Is it difficult to allow cfg options to turn all (or some) off on a case-by-case basis? We want an opt-out, when reasonable, not a blanket decision to remove them all.

The one we see on Linux is only used for glibc anyway, it's not used for other libc targets.

**Comment by jyn514** [comment]
If you're building from source anyway, can you carry patches to remove the static initializers? That would be easy from a maintainability perspective so we don't have to worry about breaking your build because `explicit-init-args-with-glibc` is never tested in CI.

**Comment by thomcc** [comment]
The aarch64 initializes come from compiler-rt, when the stdlib is built with `-Ctarget-feature=+outline-atomics` (which is enabled by default). There are some plans to port that code to Rust, but it's possible we'd leave the static initializer out (which would be a pessimization on aarch64 linux). Either way, it's possible you don't need them if you're building your own stdlib, providing your own compiler-rt (or libgcc), or whatever.

I don't have terribly strong feelings here, but it's a policy change that we'll have to decide on (unless you decide to just carry patches).

**Comment by the8472** [comment]
> Is it difficult to allow cfg options to turn all (or some) off on a case-by-case basis? We want an opt-out, when reasonable, not a blanket decision to remove them all.

Currently there is no *stable* mechanism to disable features in the standard library. And asking for an unstable one is not really something you should be asking for if you want to include this in production software because we don't want to guarantee long-term availability of unstable features.

**Comment by thomcc** [comment]
I've nominated this for the libs meeting, to decide what to do here (whether that is "nothing", "handle it on a case-by-case basis", "allow turning off all static initializers for the Rust stdlib/runtime", or something else).

**Comment by danakj** [comment]
Carrying patches is more expensive, as it requires manual work in the case of conflicts, files move, etc., and thus staffing to rebase them. For us to help with fixing upstream if it ever happened to break would be much much more preferable. There's no request here for the Rust project to carry CI costs for a default-off feature. We will provide that CI in our project, effectively.

Thank you @thomcc let me know if there's anything else I can help with or provide for the discussion.

**Comment by chbaker0** [comment]
> Currently there is no stable mechanism to disable features in the standard library. And asking for an unstable one is not really something you should be asking for if you want to include this in production software because we don't want to guarantee long-term availability of unstable features.

We implicitly take on this cost by asking for such a feature. We are not suggesting you doing our work for us.

**Comment by danakj** [comment]
> Currently there is no stable mechanism to disable features in the standard library. And asking for an unstable one is not really something you should be asking for if you want to include this in production software because we don't want to guarantee long-term availability of unstable features.
> 
> The linux kernel is in a similar situation, but they're at least building their own library and indicated they do want to get off unstable features in the long time.

I can understand this position. For LK are looking for different behaviour from the stdlib, and it makes a lot of sense for them to do so.

We're not looking to build a separate `std::env::args` that does something different, we just want to break it in cases that it requires the static initializer. More simply, we're only wishing to _remove_ code.

The Rust stdlib needs the flexibility to change over time, and that means the ability to remove unstable features in the future. This case is far more narrow in scope, and there's no dependency here on behaviour behind the feature. Removing the feature and the code behind it is always available.

**Comment by cuviper** [comment]
We are generally not inclined to add more ad hoc opt-out flags. The ones we have are already a bit distasteful, and we don't have a good mechanism for managing these, nor any plan toward stability. Also, considering this particular `args` case is different (and easier) than setting a policy or feature against static initializers in general.

It seems to me that your exception process is already sufficient for handling a case-by-case basis, no?

**Comment by the8472** [comment]
Options we tossed around:

- you carry the patches on your end since ultimately [you would be responsible for maintaining them anyway](https://github.com/rust-lang/rust/issues/111921#issuecomment-1561982674). I assume that would still be less effort than going `no_std`. I believe (but have not tested) that you could apply patches to the `rust-src` component used by `-Zbuild-std`, so it wouldn't require rebuilding the entire compiler.
- maybe some linker trickery to stub out the initializer? at least this wouldn't require any source patches
- wait for/contribute to a `build-std`-on-stable future at which point we might be able to reconsider such features, perhaps at a higher level such as disabling all of `std::env`.

> To date it has been an explicit project goal to have no static initializers. 

Perhaps you could refine that policy to disallow static initializers that rely on other ones but allow those that are shallow?

**Comment by the8472** [comment]
In the long term we could also avoid the static initializer if a way to get argv would be added to glibc or the kernel. But considering backwards compatibility we would only be able to remove it once support for that becomes widespread.

**Comment by danakj** [comment]
Is it possible that we could get some sort of statement or understanding from the library team on how they will use static initializers, to help avoid the library growing them freely in the future where they can possibly be avoided?

**Comment by the8472** [comment]
With my team hat on: We currently have no explicit policy. But we're resisting this change, among other reasons, because we do not want to commit to a policy where we never use static initializers. If a feature requires them on a platform we'll likely use them. If there are alternatives we'll consider them, but for example reading `/proc/self/cmdline` was rejected due to procfs not being available in all environments.
Usually we'll try lazy or fallback approaches for problematic features, but with static initializers that doesn't seem possible since they happen at load time.

----

If stubbing/deleting the link section works out for you then we may consider less intrusive PRs in the future that keep std working (with that particular feature degraded) when the initializer is never called. This should already be the case, but I think we're not testing those circumstances.

**Comment by the8472** [comment]
> Static initialization is known to be a problem, due to the [Static Initialization Order Fiasco](https://en.cppreference.com/w/cpp/language/siof). They also have a measurable negative impact on startup speed, even on modern computers.

Since this is the underlying motivation: If these ever become a problem I think PRs that fix ordering issues or optimize performance of expensive initializers without removing them entirely also have a good chance of being accepted.

**Comment by workingjubilee** [comment]
In practice there is sufficient background antagonism towards static initializers in the Rust teams, for the obvious reasons, that the idea that we would add these to std if we felt they were anything but crushingly necessary, much less adding static initializers that depend on other initializers, sounds absurd on its face to me.

**Comment by danakj** [comment]
Thank you, these are all helpful things for us to hear.

**Comment by danakj** [comment]
Ok we are going to allowlist this initializer for now and revisit if/when we have a more concrete problem. The positions stated above give us a lot more confidence to move forward with using std in Chromuim, so thank you again.
