### ISSUE TITLE
bootstrap: Rename `profile = user` to `profile = dist`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#112074]
`config.user.toml` currently says: https://github.com/rust-lang/rust/blob/20ca24e3c59dff52f76f1566c121c134e3a9b287/src/bootstrap/defaults/config.user.toml#L1
"users" is so ambiguous as to be meaningless. What I originally intended was something like "people building from source once and installing it locally", like Gentoo users or something. I think "dist" is a much better name for this profile: it makes it more clear why CI uses the profile and it hopefully will make it easier for distros to find and understand.

cc @cuviper - you said in https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/Redesign.20bootstrap.20stages.20compiler-team.23619/near/351408631 this would be helpful, do you still think that? The only other name I can think of is something like `install` but I'm not sure that's a good description of what CI is doing with the profile.

**Comment by jyn514** [comment]
Mentoring instructions: I want to do this in a backwards compatible way, so that old config files keep working seamlessly. To do this you'll need to add a way to add aliases to profiles. Take a look around https://github.com/rust-lang/rust/blob/5e2969e7d5b98717bf681b3f0ab30ffd3595395a/src/bootstrap/config.rs#L994-L1002 and change it to treat `user` the same as `dist`. Then rename the relevant places around https://github.com/rust-lang/rust/blob/a90e7d465806ee772f726818a0e35ab9539fb8b7/src/bootstrap/setup.rs#L23
Please add a test src/bootstrap/config/tests.rs once you're done.

**Comment by AnakinSkywalkeer** [comment]
@jyn514 can i work on this

**Comment by jyn514** [comment]
@AnakinSkywalkeer you should talk to @swarnlataa - they have https://github.com/rust-lang/rust/pull/112078 open but it's broken, I'm not sure of the status.

**Comment by AnakinSkywalkeer** [comment]
> @AnakinSkywalkeer you should talk to @Swarnlataaa - they have #112078 open but it's broken, I'm not sure of the status.

oh okay

**Comment by jyn514** [comment]
this wasn't done properly https://github.com/rust-lang/rust/pull/112166#issuecomment-1574627502

**Comment by zephaniahong** [comment]
@AnakinSkywalkeer Hi! Are you planning to continue working on this issue?
