### ISSUE TITLE
merge `BorrowKind::Unique` into `BorrowKind::Mut`

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#112072]
We currently have a separate `mir::BorrowKind` for the mutable borrows for closure upvars.

`BorrowKind::Unique` is an ordinary mutable borrow, requiring its target to be invariant, needing unique access, except that the target is not necessarily required to be marked as `mut` by the user.

We should merge this into `BorrowKind::Mut`, resulting in the following setup:
```rust
enum BorrowKind {
    Shared,
    Shallow,
    Mut { kind: MutBorrowKind },
}

enum MutBorrowKind {
    Default,
    TwoPhaseBorrow,
    ClosureCapture,
}
```
It is quite worrying to me that `fn BorrowKind::mutability` simply returns `Mutability::Not` for `BorrowKind::Unique`
https://github.com/rust-lang/rust/blob/99ff5afeb8717c096a4f153896e0c3856a3934ad/compiler/rustc_middle/src/mir/mod.rs#L2030-L2035

This already caused a bug in https://github.com/rust-lang/rust/issues/112056 where we used `PlaceContext::NonMutatingUse` for unique borrows, which resulted in us getting the wrong variance, cc #112070.

**Comment by RalfJung** [comment]
Can `BorrowKind::Unique` be used to perform actual mutation of a `let` (not `let mut`) bound local, or can it only be used for mutation *through* such a local (e.g. a reference stored there)?

**Comment by lcnr** [comment]
> Can `BorrowKind::Unique` be used to perform actual mutation of a `let` (not `let mut`) bound local, or can it only be used for mutation _through_ such a local (e.g. a reference stored there)?

afaict it is only used to deal with locals whose type is `&mut x`, so `BorrowKind::Unique` only allows mutation through such a local
