### ISSUE TITLE
the docs of rustdoc get overwritten by the bootstrap docs

### ISSUE THREAD

**Issue by fmease** [rust-lang/rust#112082]
Since #111976, `bootstrap` itself gets documented. Unfortunately, the package contains a binary crate called `rustdoc` (`src/bootstrap/bin/rustdoc.rs`, *Shim which is passed to Cargo as “rustdoc” when running the bootstrap.*) which clashes with the actual `rustdoc` package (`src/librustdoc`) overwriting the latter since it gets documented last.

See for yourself: https://doc.rust-lang.org/nightly/nightly-rustc/rustdoc/index.html (this ain't *rustdoc*).

CC @jyn514 (#111976).

@rustbot label C-bug T-bootstrap A-docs A-contributor-roadblock

**Comment by jyn514** [comment]
ah, thanks! I think the fix is to pass `--lib` to cargo so it doesn't try to document the binaries, they don't have anything useful.

**Comment by jyn514** [comment]
Alternatively - maybe better? - we could rename `rustdoc.rs` to `rustdoc-shim.rs`, which seems more clear anyway.
