### ISSUE TITLE
`std::ops::Yeet` trait documentation is unhelpful (empty)

### ISSUE THREAD

**Issue by mcclure** [rust-lang/rust#112079]
### Location

https://doc.rust-lang.org/std/ops/struct.Yeet.html

### Summary

Sometimes, Rust communities mention an experimental "do yeet" syntax.

If you Google "Rust Yeet", the top hit is https://doc.rust-lang.org/std/ops/struct.Yeet.html

This page documents the "Yeet" trait, which I *interpret* as "a type which is eligible to be yeeted".

The page, however, *does not document either the Yeet trait, or what the yeet feature actually does*. There is a clear notice that it is an experimental API, but no indication of what the experimental API does or when one would enable it.

There is a brief explanation in the unstable book, which is very clear and helpful:

https://doc.rust-lang.org/beta/unstable-book/language-features/yeet-expr.html

My "expected behavior" is that the `std::ops::Yeet` docs on the official website should (1) link [the unstable book passage](https://doc.rust-lang.org/beta/unstable-book/language-features/yeet-expr.html) (2) briefly explain the relationship between the yeet feature and std::ops::Yeet

#### "Why did you file this as an issue and not a PR?"

I would be happy to make a PR, but I don't fully understand how docstrings get out of the codebase and onto doc.rust-lang.org/std. If I look at the source for the Yeet trait https://doc.rust-lang.org/src/core/ops/try_trait.rs.html#434 there appears to be a sensible one-sentence docstring explanation of my expected "(2)" (explains how Yeet relates to yeet). But that sentence doesn't appear on doc.rust-lang.org/std. So I think it would be perfect if that docstring added a link to the unstable book, but if the docstring *isn't on the website* then apparently I don't understand how to file a PR on the std website.

**Comment by the8472** [comment]
`do yeet` is contextual syntax, piggybacking on the reserved [do](https://doc.rust-lang.org/reference/keywords.html#reserved-keywords) keyword. Normally such documentation would go under the [keyword docs](https://doc.rust-lang.org/std/index.html#keywords). But it is an experimental placeholder so maybe it's not worth it to put much effort into documenting it until the syntax is finalized.

Sidenote: `Yeet<T>` is a struct, not a trait.

> There appears to be a sensible one-sentence docstring explanation of my expected "(2)" (explains how Yeet relates to yeet). But that sentence doesn't appear on doc.rust-lang.org/std

But it does? Did you have the docs collapsed perchance?

![image](https://github.com/rust-lang/rust/assets/1065730/5d9723f7-8ddf-44b5-be8a-bb69cc4050f8)
