### ISSUE TITLE
Need to re-fix Windows manifest embedding.

### ISSUE THREAD

**Issue by vadimcn** [rust-lang/rust#11207]
The previous attempt (#10878) to fix #10512 has a couple of problems:
1. Sometimes UpdateResource corrupts executables produced by binutils.   (The executable still runs, however tools like dumpbin report corrupted PE header, and gdb crashes when trying to read debug info).
2. More importantly, this approach does not work for cross-compilation, because, well, you can't call Windows API if the host system is not Windows.

**Comment by alexcrichton** [comment]
@vadimcn I'm not sure I ever really fully understood what manifests were or why we were embedding them, but given today's landscape of Rust-on-Windows does this still make sense? Is this something we should do on MSVC as well as MinGW?

**Comment by vadimcn** [comment]
Manifests are just metadata about the executable that tells Windows more about its requirements and capabilities.  One of the most frequent uses is to specify whether the program expects to run with admin privileges (otherwise Windows will try to guess - for compatibility with pre-Vista executables), but there other features beyond that.

MSVC linker will embed a default manifest by, um, default.  As for MinGW - see above.

**Comment by alexcrichton** [comment]
Ah ok, so in that case should is the MSVC manifest that's automatically embedded a well known manifest? If so then it sounds like this is still relevant for MinGW and it'd just be one of the strategies you outlined above.

**Comment by taralx** [comment]
As a note - rustup-setup was just renamed rustup-init because of this issue.

**Comment by steveklabnik** [comment]
Triage: not aware of any changes here

**Comment by jonas-schievink** [comment]
I suggest closing this in favor of https://github.com/rust-lang/rfcs/issues/721 and the [`embed_resource`](https://rawcdn.githack.com/nabijaczleweli/rust-embed-resource/doc/embed_resource/index.html) crate.

**Comment by jpoles1** [comment]
@jonas-schievink can you please elaborate on the steps required to embed a manifest using the embed_resource crate?

**Comment by jonas-schievink** [comment]
@jpoles1 I've never used it, but you can check the docs and crates that use it

**Comment by jpoles1** [comment]
@jonas-schievink I read the docs and still unsure of how to embed the manifest. Are you aware of any crates that use the library in this manner? Understand if not, and thanks for your assistance.

**Comment by jonas-schievink** [comment]
`cargo-update` (by the same author) uses it: https://github.com/nabijaczleweli/cargo-update/blob/master/build.rs

**Comment by jpoles1** [comment]
@jonas-schievink, that's perfect, thanks for the tip!

My specific use case was to programatically enable admin permissions on my .exe file, the steps I used to get this working are as follows:
1) Add the following to your cargo.toml:
```
[build-dependencies]
embed-resource = "1.3"
```
2) In your project root directory, add a file named `build.rs` with the following:
```
extern crate embed_resource;
fn main() {
    embed_resource::compile("app-name-manifest.rc");
}
```

3) In your project root directory, add a file named `app-name-manifest.rc` with the following:
```
#define RT_MANIFEST 24
1 RT_MANIFEST "app-name.exe.manifest"
```

4) In your project root directory, add a file named `app-name.exe.manifest` with the following:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
    <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
        <security>
            <requestedPrivileges>
                <requestedExecutionLevel level="requireAdministrator" uiAccess="false"/>
            </requestedPrivileges>
        </security>
    </trustInfo>
</assembly>
```

5) Build your project!

**Comment by steveklabnik** [comment]
Great! Let's close in favor of those.
