### ISSUE TITLE
Release notes have become too big to render on Github

### ISSUE THREAD

**Issue by ilyapopov** [rust-lang/rust#112114]
### Location

https://github.com/rust-lang/rust/blob/stable/RELEASES.md

### Summary

Instead of rendered markdown, it shows "This blob took too long to generate."

This page is linked from the announcement post https://blog.rust-lang.org/inside-rust/2023/05/29/1.70.0-prerelease.html so it is supposed to be human-readable.

**Comment by Nilstrieb** [comment]
thank you for the report! this is a duplicate #101714 . See also [this zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/241545-t-release/topic/Release.20blob.20too.20large/near/326406803).
