### ISSUE TITLE
Missed optimization when computing fma

### ISSUE THREAD

**Issue by icedrocket** [rust-lang/rust#112192]
It optimizes well when the fma is computed explicitly with `f32::mul_add()`, but not when it is not, like `x * y + z`.

https://godbolt.org/z/fh74x4W88

**Comment by workingjubilee** [comment]
That is a result-changing optimization, so the optimization is not permissible. Otherwise, this is a duplicate of e.g. https://github.com/rust-lang/rust/issues/21690

**Comment by workingjubilee** [comment]
And there is no LLVM bug here: we don't ask LLVM to do results-changing optimizations, so it doesn't. We would need to define this optimization as acceptable on the Rust language, first.
