### ISSUE TITLE
offset_of! accepts unsized tuple field

### ISSUE THREAD

**Issue by tmiasko** [rust-lang/rust#112186]
I tried this code:

```rust
#![feature(offset_of)]
use std::fmt::Debug;
fn main() {
    core::mem::offset_of!((u8, dyn Debug), 1);
}
```

I expected the compilation to fail since the offset cannot be statically determined. Instead, the compilation succeeds.

**Comment by scottmcm** [comment]
cc @clubby789 #112069

**Comment by clubby789** [comment]
Technically this was possible before as there were no `Sized` checks on the tuple case, but it no longer ICEs when codegenning the value.
Should
```rs
struct S<T: ?Sized> {
    a: u64,
    b: T,
}
fn main() {
    let _a = core::mem::offset_of!(S<dyn std::fmt::Debug>, a);
}
```
from the linked issue be allowed - is this a problem specific to tuples?

**Comment by est31** [comment]
> is this a problem specific to tuples?

I'd say so, yes. The example you gave fails to compile if you try to get the offset of the `b` field.

There is a missing call to `require_type_is_sized` in the match in `compiler/rustc_hir_typeck/src/expr.rs`. The arm for ADTs has it, the one for tuples doesn't.
