### ISSUE TITLE
"Regression" - some static bounds incorrectly compiled in 1.63..=1.67

### ISSUE THREAD

**Issue by QuineDot** [rust-lang/rust#112283]
### Heads-up

The example below should not compile and currently does not compile, so this is going to be low priority.

However, the example compiled for 1.63 -- 1.67 inclusive (it doesn't compile in 1.62 or in 1.68 to current).

I didn't see anything that looked relevant in the release notes, and I figure there should at least be a test somewhere, so it doesn't start compiling again.

So this issue is primarily about making sure a test exists.

### Code

[I tried this code:](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=21ee10ef400db4d5eed7f934da394216)

```rust
pub trait Trait {}

pub trait Assoc<'x> {
    type A: ?Sized;
}

impl<'x> Assoc<'x> for str { type A = &'x dyn Trait; }

pub fn assoc<T: 'static>() {}
pub fn assoc_helper<'a: 'a>() {
    assoc::< <str as Assoc<'a>>::A >();
}
```

I expected to see this happen: Inexplicably compile like it did [during some exploration months ago.](https://play.rust-lang.org/?version=beta&mode=debug&edition=2021&gist=c7bf9a2cdfc0a967711e1aea10204de0)  (Search for "this all works" for more examples with probably irrelevant variations if you're curious.)

Instead, this happened: Failed to compile, which makes more sense.

### Version it worked on

It most recently worked on: [Rust 1.67](https://godbolt.org/z/jGfEfjb1d), and also 1.63, 1.64, 1.65, and 1.66.

### Version with regression

1.68 to present.

**Comment by compiler-errors** [comment]
Oh right, forgot to click enter--

searched nightlies: from nightly-2023-01-01 to nightly-2023-06-01
regressed nightly: nightly-2023-01-10
searched commit range: https://github.com/rust-lang/rust/compare/cc47b069983292e4ee8982d5dabe6301452c5f25...3020239de947ec52677e9b4e853a6a9fc073d1f9
regressed commit: https://github.com/rust-lang/rust/commit/af58fc869910eae0ec525d49cbb6d953ea10a8c6

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.6</summary>


Host triple: aarch64-apple-darwin
Reproduce with:
```bash
cargo bisect-rustc 2023-01-01 --end 2023-06-01 --regress error
```
</details>

**Comment by QuineDot** [comment]
The tests from PR #101947 look sufficient to me, so I'm going to close this.

Thanks!
