### ISSUE TITLE
Invalid documentation path reference in rustfmt Cargo.toml

### ISSUE THREAD

**Issue by Ofenhed** [rust-lang/rust#112271]
The dependency for rustc-workspace-hack has [an explanation](https://github.com/rust-lang/rust/blob/9eee230cd0a56bfba3ce65121798d9f9f4341cdd/src/tools/rustfmt/Cargo.toml#L62-L64) that refers to a file which does not exist.

**Comment by ehuss** [comment]
Thanks for the report! It is no longer used. I'll try to follow up with some PRs, but it may take a while for them to get synced.

**Comment by Ofenhed** [comment]
That was quick 😊

**Comment by clubby789** [comment]
Has this been resolved now?

**Comment by ehuss** [comment]
I think so. Miri hasn't been synced, yet, but it should happen eventually (looks like it happens every few weeks). Since we don't have a means to really track that, I'm going to go ahead and close this since the underlying commits are done.
