### ISSUE TITLE
1.70.0: ui test failures due to "the full type name has been written to"

### ISSUE THREAD

**Issue by xry111** [rust-lang/rust#112209]
Three ui tests fail with 1.70.0 and `channel = "stable"`:

    [ui] tests/ui/mismatched_types/issue-36053-2.rs
    [ui] tests/ui/typeck/issue-31173.rs
    [ui] tests/ui/methods/method-not-found-generic-arg-elision.rs

They seem caused by the extra lines like:

    = note: the full type name has been written to '$TEST_BUILD_DIR/methods/method-not-found-generic-arg-elision/method-not-found-generic-arg-elision.long-type-9165007450593903927.txt'

Should we suppress the "full type name output" within the test suite, or am I doing something wrong?

**Comment by TimNN** [comment]
Some background:

I've attempted to fix this in https://github.com/rust-lang/rust/pull/105924 by enabling path remapping in UI tests by default.

However, that caused some usability regressions for `rustc` developers (https://github.com/rust-lang/rust/issues/109725), so now this logic only triggers on CI: https://github.com/rust-lang/rust/pull/110115

**Comment by jyn514** [comment]
i wonder if this should be an explicit config instead of being auto detected based on a CI environment variable. then we could enable it by default for the dev channel and disable it everywhere else.

**Comment by TimNN** [comment]
Having an explicit config for this sounds great. It would also mean that people with custom buildbots no longer need to spoof the CI detection logic (like e.g. Chromium does right now: https://github.com/chromium/chromium/commit/9fc3ea506f7d471c1aed19e587df7324f7583ac1).

**Comment by chenyukang** [comment]
The path remapping is removed in https://github.com/rust-lang/rust/pull/114090, I verified the test issue in the stable channel is fixed, closing this issue now.
