### ISSUE TITLE
ConstParamTy should be split into two traits

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#112221]
`ConstParamTy` is currently used to require people to opt-in to having a type used as a const parameter under `feature(adt_const_params)` as not all types are legal to have as a const parameter type. One of the restrictions impls of this trait have is that the type has `Eq, PartialEq` recursively derived. This is also something that pattern matching is interested so we should find some way of sharing the impl between `ConstParamTy` and the trait used for allowing constants to be used as patterns.

The current `ConstParamTy` trait should be split out into `trait ConstParamTy: StructuralMatch` and `trait StructuralMatch: PartialEq + StructuralPartialEq` with `StructuralMatch` also having a builtin check that all its fields are `StructuralMatch`.

It's possible that the requirements for const parameter types may end up being stricter than the requirements to use a constant as a pattern so we should have two separate traits rather than renaming `ConstParamTy` to something that makes sense in the context of pattern matching.

cc @oli-obk

**Comment by BoxyUwU** [comment]
One thing to note about this is that in order to use a type as a const param ty you would have to drive 4 traits instead of 3- `derive(Eq, PartialEq, StructuralMatch, ConstParamTy)`

**Comment by RalfJung** [comment]
I could see one reason to introduce a new trait: to replace the `search_for_structural_match_violation` test by a trait query instead.

But given that we currently use a value-aware MIR qualif to determine whether a constant can be structurally matched, I am not sure if that would have any benefits.

**Comment by BoxyUwU** [comment]
`ConstParamTy` only really cares about the type being shallowly structural eq since we recursively require all fields to be `ConstParamTy` which effectively requires it to be deep. Going to close this since I see no reason to have more traits here.
