### ISSUE TITLE
windows-sys generated WinAPI bindings break ARM platforms

### ISSUE THREAD

**Issue by bdbai** [rust-lang/rust#112265]
In https://github.com/rust-lang/rust/pull/110152 the WinAPI definitions have been replaced by windows-bindgen generated bindings. However, the [win32metadata](https://github.com/microsoft/win32metadata) project does not generate metadata for ARM32-specific items, hence the generated bindings lack a few types like `CONTEXT` and `WSADATA` on this platform. It effectively breaks `thumbv7a-*-windows-*` for Rust.

@ChrisDenton

**Comment by ChrisDenton** [comment]
Unfortunately, 32-bit ARM is not being supported by Microsoft going forward. What we could do is insert our own definitions in [the prelude](https://github.com/rust-lang/rust/blob/9eee230cd0a56bfba3ce65121798d9f9f4341cdd/src/tools/generate-windows-sys/src/main.rs#L6), copied from before the changes.

**Comment by bdbai** [comment]
Besides the issue with ARM, all UWP targets actually have problems with linkage as well. Previously the APIs forbidden on UWP are gated behind fine-grained conditional compilation flags, but it is no longer the case with generated ones. I got this when building the UWP app that links again a Rust staticlib.
![image](https://github.com/rust-lang/rust/assets/5270106/2fc13bdc-1dd4-4d3a-8245-936ae3c72019)

**Comment by ChrisDenton** [comment]
Iirc, the `Nt` functions were never gated. But we loaded them lazily (and panicked if they didn't load). This did allow UWP targets to compile. No idea if they actually ran. I'm not sure who's responsible for these targets.

**Comment by bdbai** [comment]
> Iirc, the `Nt` functions were never gated. But we loaded them lazily (and panicked if they didn't load). This did allow UWP targets to compile. No idea if they actually ran. I'm not sure who's responsible for these targets.

I think you are correct. I can reproduce the link errors with toolchain `nightly-2023-05-06`. Let me file another issue after I pinpoint the underlying problem.

**Comment by ChrisDenton** [comment]
Oh wait, as staticlib? You currently need to make sure to link all the libraries it depends on. You can get them using [`--print native-static-libs`](https://doc.rust-lang.org/rustc/command-line-arguments.html#--print-print-compiler-information).

**Comment by bdbai** [comment]
> Oh wait, as staticlib? You currently need to make sure to link all the libraries it depends on. You can get them using [`--print native-static-libs`](https://doc.rust-lang.org/rustc/command-line-arguments.html#--print-print-compiler-information).

This will fail Windows App Cert Kit tests.

![image](https://github.com/rust-lang/rust/assets/5270106/bc566172-e132-4d65-93f1-0223a50e4ca1)

**Comment by ChrisDenton** [comment]
In that case I'm surprised that lazy loading worked.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23112265.20windows-sys.20generated.20WinAPI.20bindings.20break.20ARM.20pla.E2.80.A6)).

@rustbot label -I-prioritize +P-low
