### ISSUE TITLE
`x check` checks rust-analyzer by default

### ISSUE THREAD

**Issue by Nilstrieb** [rust-lang/rust#112287]
Sometimes when changing compiler internals, I run `x check` to make sure I didn't break tools and codegen backends. This also checks rust-analyzer by default, which is not very useful, I cannot break that.

If we want to keep that, it would at least be useful to put it last so I can Ctrl-C out of it. Currently, rustfmt is checked after rust-analyzer.

**Comment by jyn514** [comment]
mentoring instructions: switch the order of these two lines:
https://github.com/rust-lang/rust/blob/dc25fbe9844f4c8bddc316685d270a49d7b159b9/src/bootstrap/builder.rs#L706-L707

**Comment by jyn514** [comment]
@Nilstrieb points out that Cargo also isn't checked by default, so for consistency it would be nice for RustAnazlyer not to be either: https://github.com/rust-lang/rust/blob/dc25fbe9844f4c8bddc316685d270a49d7b159b9/src/bootstrap/check.rs#L350
