### ISSUE TITLE
Const generic expressions in type-state-machine does not recognize same type

### ISSUE THREAD

**Issue by Byter09** [rust-lang/rust#112289]
### Code
https://gitlab.com/bit-refined/meiosis/-/blob/68c8c6f20d6171ee4a1b4cccf7196beb18060838/examples/helloworld.rs#L132

I expected to see this happen: Code compiles successfully, as it did before.

Instead, this happened:
```
error[E0308]: mismatched types
   --> examples/helloworld.rs:132:27
    |
132 |                 classic = new_evaluated.select().recombine().mutate().reinsert();
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `meiosis::::operators::mutation::combination::{impl#2}::and::{constant#0}`, found `4`
    |
    = note: expected struct `Classic<_, _, _, _, _, _, meiosis::operators::mutation::combination::Combination<_, _, _, meiosis::::operators::mutation::combination::{impl#2}::and::{constant#0}>, _>`
               found struct `Classic<_, _, _, _, _, _, meiosis::operators::mutation::combination::Combination<_, _, _, 4>, _>`
help: call `Into::into` on this expression to convert `Classic<Unevaluated<Vec<u8>>, Vec<u8>, ThreadRng, EvolveHelloWorld, StochasticAcceptance, SinglePoint, meiosis::operators::mutation::combination::Combination<Selective, Vec<u8>, ThreadRng, 4>, meiosis::termination::fitness::Fitness>` into `Classic<Unevaluated<Vec<u8>>, Vec<u8>, ThreadRng, EvolveHelloWorld, StochasticAcceptance, SinglePoint, meiosis::operators::mutation::combination::Combination<Selective, Vec<u8>, ThreadRng, meiosis::::operators::mutation::combination::{impl#2}::and::{constant#0}>, meiosis::termination::fitness::Fitness>`
    |
132 |                 classic = new_evaluated.select().recombine().mutate().reinsert().into();
    |                                                                                 +++++++
```

### Version it worked on

It most recently worked on: 1.71.0-nightly (c373194cb 2023-05-24)

### Version with regression

`rustc --version --verbose`:
```
rustc 1.72.0-nightly (398fa2187 2023-06-03)
binary: rustc
commit-hash: 398fa2187c88de46c13c142f600064483a563c86
commit-date: 2023-06-03
host: x86_64-unknown-linux-gnu
release: 1.72.0-nightly
LLVM version: 16.0.4

```

I know const generic expressions is a bit uh.. lets say volatile, but I saw https://github.com/rust-lang/rust/issues/76560#issuecomment-1475715267 and couldn't find an issue as I did not know how to formulate this.

It should be noted, that the suggestion in the error actually fixes it, however I think it is still not correct, as the resulting types _are_ the same, not requiring any `.into()`.

I am sorry that I can't provide a minimal example at this time due to the minimum amount of free time I have.

**Comment by Byter09** [comment]
It is my own crate. I'm writing an example for it. And the feature is enabled in the library.

**Comment by lcnr** [comment]
examples are considered separate crates in Rust (implicitly handled by cargo for you), so examples also need the necessary feature flags

**Comment by Byter09** [comment]
I mean it worked before though? Also I just noticed I accidentally pasted the wrong regression version above. I'll test adding the feature to the example and change the issue in a moment

**Comment by BoxyUwU** [comment]
It likely worked before because of other bugs masking the requirement to have `generic_const_expr`s enabled. This is not going to be fixed since it is not expected for code to work properly without both crates having the feature enabled. Thank you for the issue regardless.
