### ISSUE TITLE
404 link in std::fs documentation in places with "Platform Specific Behavior"

### ISSUE THREAD

**Issue by WhyNotDogie** [rust-lang/rust#112222]
### Location

All functions in std::fs with a "Platform Specific Behavior" header, as far as I know.

### Summary

At the end of the text under the header, is a hyperlink:
> [some docs]. Note that, this [may change in the future](https://doc.rust-lang.org/stable/std/fs/io#platform-specific-behavior).

This hyperlink leads to [https://doc.rust-lang.org/stable/std/fs/io#platform-specific-behavior](https://doc.rust-lang.org/stable/std/fs/io#platform-specific-behavior), which does not exist.  
  
Edit 1: It seems to only happen in VSCode. Maybe a Rust-Analyzer bug?

**Comment by wwylele** [comment]
Could you provide a concrete example? I tried a few like https://doc.rust-lang.org/stable/std/fs/fn.read_dir.html but it works fine for me

**Comment by WhyNotDogie** [comment]
> Could you provide a concrete example? I tried a few like https://doc.rust-lang.org/stable/std/fs/fn.read_dir.html but it works fine for me

See the edit.

**Comment by wwylele** [comment]
Yeah this is likely a vscode or rust analyzer bug then. The url is a relative one
```
<a href="../io/index.html#platform-specific-behavior" title="mod std::io">may change in the future</a>
```
so maybe the url decoder got it wrong

**Comment by WhyNotDogie** [comment]
might open an issue for rust-analyzer, will close here.

**Comment by WhyNotDogie** [comment]
whoops forgot to close :sweat_smile:
