### ISSUE TITLE
replace channel-based timers with a recv_timeout method

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#11223]
If it's done directly on channel types, it will be easier to use because it won't require the caller to worry about a pattern like `select`.

For the 1:1 case, this would just be a call to `pthread_cond_timedwait` after initializing the condition variable with `CLOCK_MONOTONIC` as the clock.

Windows condition variables expose a similar method taking a relative time, but there's no way to wait again for the remaining time after a spurious wake-up. If this is important, we can build the functionality on top of the win32 API or use another implementation.

For M:N threading it can either keep doing what it does now behind the scenes, or use an efficient timer/condvar contraption too.

**Comment by alexcrichton** [comment]
Channel based timers are part of `old_io` and are not coming back as part of the new I/O. I've opened [an RFC issue](https://github.com/rust-lang/rfcs/issues/962) for adding `recv_timeout` which is useful no matter what. In light of channel-based timers not coming back, though, I'm going to close this in favor of the RFC issue as it will be a backwards compatible addition.
