### ISSUE TITLE
Beta rustc warns on missing documentation for an extern crate even though the docstring is not used by rustdoc

### ISSUE THREAD

**Issue by elinorbgr** [rust-lang/rust#112308]
minimal example:

```rust
#![warn(missing_docs)]

pub extern crate alloc;
```

Running `cargo check` on this example outputs no warning on stable 1.70.0, but on either `rustc 1.71.0-beta.2 (4e8c9e8e3 2023-06-04)` or `rustc 1.72.0-nightly (101fa903b 2023-06-04)` it outputs the following warning:

```
warning: missing documentation for an extern crate
 --> src/lib.rs:5:1
  |
5 | pub extern crate alloc;
  | ^^^^^^^^^^^^^^^^^^^^^^
  |
note: the lint level is defined here
 --> src/lib.rs:3:9
  |
3 | #![warn(missing_docs)]
  |         ^^^^^^^^^^^^
```

Adding a docstring does silence the warning, but as far as I can tell this docstring is not used anywhere by rustdoc: adding it has no impact on the generated documentation.

I suppose either the warning is inadequate, or rustdoc should display that docstring.

cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Thanks for opening the issue! We have a few items where the documentation is ignored. I think for the current case, the best would be to not warn as a first step. Then we should maybe discuss whether or not we want to display documentation for these items and also how. It was suggested some time ago to create pages to list such items (by grouping them). To be discussed.

**Comment by jannic** [comment]
@GuillaumeGomez, the warning is still present in current beta ,`1.71.0-beta.6 (01b5c40dc 2023-07-08)`.
Should the fix be back-ported, or will rust 1.71.0, when released, emit this warning?

**Comment by GuillaumeGomez** [comment]
It should be backported to beta.

**Comment by jannic** [comment]
I just noticed that 1.71.0 is already in pre-release testing, https://internals.rust-lang.org/t/rust-1-71-0-pre-release-testing/19123
So it's probably too late for a backport, right? :cry:
