### ISSUE TITLE
Constification of BinaryHeap construction

### ISSUE THREAD

**Issue by terrarier2111** [rust-lang/rust#112353]
Is there any reason this isn't const yet? This should only depend on vec's construction being const which it is.

**Comment by est31** [comment]
All the other collections already have const constructors (except for the ones for which it's hard, cc #112354). So I think it makes a lot of sense to make this const as well.

There was an entire [ACP for `VecDequeue::new()`](https://github.com/rust-lang/libs-team/issues/138). I don't know if one is needed for `BinaryHeap` as well. On the other hand, the function became instantly const-stable, there was no period where it was unstably const, see #105072.

**Comment by tsemo4917** [comment]
```
impl<T: Ord> BinaryHeap<T> {
    pub fn new() -> BinaryHeap<T> {
        BinaryHeap { data: vec![] }
    }
}
```
`BinaryHeap` constructor is only depends on `Vec` constructor, and `Vec::new()` has been a const function since 1.39.0. 

Constification of BinaryHeap constructor will be helpful when a static variable is of the BinaryHeap type. 

@dtolnay

**Comment by Coekjan** [comment]
I also met this issue, trying to address it with #117316

**Comment by Coekjan** [comment]
The feature `const_binary_heap_constructor` was added to nightly.

Due to unstable feature (`allocator_api`, issue: #32838 ), this feature is not able to be stablized now.

**Comment by LGFae** [comment]
Hello, @Coekjan, according to what you said in #117316, it seems that the `new` function *could* be stabilized, even without the `allocator_api` being stable. Any news on that front?

**Comment by Coekjan** [comment]
> Hello, @Coekjan, according to what you said in #117316, it seems that the `new` function _could_ be stabilized, even without the `allocator_api` being stable. Any news on that front?

I am a little busy this week, and I will try to see how to stablize it later.

**Comment by Coekjan** [comment]
> Hello, @Coekjan, according to what you said in #117316, it seems that the `new` function _could_ be stabilized, even without the `allocator_api` being stable. Any news on that front?

See #125211 I try to place the two functions into two different features, and stablize `BinaryHeap::new`.

**Comment by jhpratt** [comment]
Nomination for discussion to stabilize. I think it's quite straightforward and has plenty of precedent.

**Comment by dtolnay** [comment]
@rust-lang/libs-api:
@rfcbot fcp merge

`const` on the already-stable constructor for BinaryHeap.

```rust
impl<T: Ord> BinaryHeap<T> {
    #[must_use]
    pub const fn new() -> Self;
}
```

**Comment by est31** [comment]
Given that #125211 has been merged, and `BinaryHeap::new` is const-stable now, this tracking issue is now only for const-stability of `BinaryHeap::new_in`.

Maybe this should be indicated at the top of the issue? Or should we make a new tracking issue?

**Comment by jhpratt** [comment]
@est31 Is there typically a tracking issue for const-stabilizing something that is itself unstable? I didn't think so, so I would actually recommend closing this.

**Comment by Coekjan** [comment]
If it is ok, let me open a new issue to track `BinaryHeap::new_in`
