### ISSUE TITLE
make `unused_lifetimes` lint warn by default

### ISSUE THREAD

**Issue by laralove143** [rust-lang/rust#112425]
the docs at https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#unused-lifetimes dont mention why its allowed by default, feels like it shouldnt be as it also says it signals a mistake or unfinished code

**Comment by matthiaskrgr** [comment]
See https://github.com/rust-lang/rust/issues/94038

**Comment by Dylan-DPC** [comment]
Closing this in favour of the tracking issue
