### ISSUE TITLE
Incorrect `Box::clone` doc

### ISSUE THREAD

**Issue by 823984418** [rust-lang/rust#112455]
The current document is

https://github.com/rust-lang/rust/blob/9c843d9fa322596c7d525c78fa89731ecf7afbfe/library/alloc/src/boxed.rs#LL1256C1-L1269C12
```
/// Returns a new box with a `clone()` of this box's contents.
///
/// # Examples
///
/// ```
/// let x = Box::new(5);
/// let y = x.clone();
///
/// // The value is the same
/// assert_eq!(x, y);
///
/// // But they are unique objects
/// assert_ne!(&*x as *const i32, &*y as *const i32);
/// ```
```

> a `clone()` of this box's contents.

But in reality, its behavior is specialized, if the content impl `Copy`, will not call `clone`.

----

What is our expected behavior, should we modify the document or remove specialization?

**Comment by the8472** [comment]
Per [RFC 1521](https://rust-lang.github.io/rfcs/1521-copy-clone-semantics.html) the library is allowed to assume it can use clone and copy interchangably, so we don't need to document this on every single `clone()` function.

Types that implement `Copy` shouldn't have a non-trivial Clone, this [is documented on Clone itself](https://doc.rust-lang.org/nightly/std/clone/trait.Clone.html#how-can-i-implement-clone).

**Comment by Neutron3529** [comment]
```
fn main(){
    let x = Box::new(5i32);
    let y = x.clone();
    assert_eq!(x, y);
    assert_ne!(&*x as *const i32, &*y as *const i32);
}
```
notice that
1. `5i32` is `Copy`.
2. `y` and `x` have different address.

Thus it is `Clone` rather than `Copy` called when the content is `Copy`.
