### ISSUE TITLE
change `DefiningAnchor::Bind` to a list of opaques

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#112453]
[`DefiningAnchor::Bind`](https://github.com/rust-lang/rust/blob/9c843d9fa322596c7d525c78fa89731ecf7afbfe/compiler/rustc_middle/src/traits/mod.rs#L1118) is used to indicate which opaque types can be defined in the current scope. This currently uses the `DefId` of the current scope and which is then used in `opaque_type_origin` to check whether a given opaque type is defined by the current item:

https://github.com/rust-lang/rust/blob/9c843d9fa322596c7d525c78fa89731ecf7afbfe/compiler/rustc_infer/src/infer/opaque_types.rs#L378-L398

To enable better caching, both directly by having the same anchor for all functions which don't define any opaque types, and indirectly, by allowing us to filter opaque types from the defining scope, we should instead change this to a list of the opaques we're defining: `&'tcx [LocalDefId]`. `opaque_type_origin` can then simply check whether the opaque type is an element of that list.

**Comment by oli-obk** [comment]
I believe this cannot be done yet. https://github.com/rust-lang/rust/pull/112652 is the first step towards being able to do it.

**Comment by lcnr** [comment]
> I believe this cannot be done yet. #112652 is the first step towards being able to do it.

why can this not be done by walking up the module tree and collecting all opaque types? :sweat_smile:

**Comment by oli-obk** [comment]
lol ok, sure, that works.

**Comment by lcnr** [comment]
this has been implemented https://doc.rust-lang.org/nightly/nightly-rustc/rustc_infer/infer/struct.InferCtxt.html#structfield.defining_opaque_types
