### ISSUE TITLE
`std::env::args` panics on rustc >= 1.69.0 in `armv7-unknown-linux-gnueabihf` with uClibc

### ISSUE THREAD

**Issue by daniestevez** [rust-lang/rust#112488]
I'm building Rust code for an embedded armv7 system that uses uClibc. I'm using the target `armv7-unknown-linux-gnueabihf`. Maybe I should use the tier 3 target [`armv7-unknown-linux-uclibceabihf`](https://doc.rust-lang.org/nightly/rustc/platform-support/armv7-unknown-linux-uclibceabihf.html), but `armv7-unknown-linux-gnueabihf` works well besides the problem I'm reporting here.

Apparently, `std::env::args` handling with `armv7-unknown-linux-gnueabihf` and uClibc is broken, but it is broken in a worse way starting in rustc 1.69.0. I'm testing the following code:

```rust
fn main() {
    println!("calling std::env::args_os()");
    let _ = std::env::args_os();
    println!("call succeeded");
    println!("std::env::args() = {:?}", std::env::args().collect::<Vec<_>>());
}
```

With rustc 1.68.2 or lower, `std::env::args` always returns an empty iterator regardless of the number of arguments that are used to run the program.

```
# RUST_BACKTRACE=1 ./test-args 0 1 2
calling std::env::args_os()
call succeeded
std::env::args() = []
```

However, starting with rustc 1.69.0, even calling `std::env::arg_os` panics.

```
# RUST_BACKTRACE=1 ./test-args 0 1 2
calling std::env::args_os()
thread 'main' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:525:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: alloc::raw_vec::capacity_overflow
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/raw_vec.rs:525:5
   3: alloc::raw_vec::RawVec<T,A>::allocate_in
   4: alloc::raw_vec::RawVec<T,A>::with_capacity_in
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/raw_vec.rs:131:9
   5: alloc::vec::Vec<T,A>::with_capacity_in
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/vec/mod.rs:676:20
   6: alloc::vec::Vec<T>::with_capacity
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/vec/mod.rs:483:9
   7: std::sys::unix::args::imp::clone
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys/unix/args.rs:145:28
   8: std::sys::unix::args::imp::args
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys/unix/args.rs:130:22
   9: std::sys::unix::args::args
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys/unix/args.rs:19:5
  10: std::env::args_os
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/env.rs:799:21
  11: test_args::main
             at /project/src/main.rs:3:13
  12: core::ops::function::FnOnce::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I think the difference is cause by https://github.com/rust-lang/rust/commit/e97203c3f893893611818997bbeb0116ded2605f. I haven't done more debugging, but this leads me to believe that somehow the atomic variable `ARGC` ends up having a negative value. Before this change, the range `(0..argc)` would be empty, causing an empty iterator to be returned always, while after this change, `Vec::with_capacity(argc as usize)` will panic because `argc as usize` will be a huge number.

**Comment by daniestevez** [comment]
If I'm reading uClibc's source correctly, the problem is that uClibc [calls `init_array` functions with no parameters](https://github.com/kraj/uClibc/blob/ca1c74d67dd115d059a875150e10b8560a9c35a8/libc/misc/internals/__uClibc_main.c#LL450C35-L450C35), whereas Rust expects `argc`, `argv`, and `envp`, which is what glibc uses.

**Comment by bjorn3** [comment]
The `.init_array` code path should only be taken for glibc: https://github.com/rust-lang/rust/blob/fd0a3313f7a64cb16533030e49a271db449368c3/library/std/src/sys/unix/args.rs#L109-L112

**Comment by daniestevez** [comment]
I guess my main point is that I'm using the target `armv7-unknown-linux-gnueabihf` rather than `armv7-unknown-linux-uclibceabihf`. Perhaps I'd have better results using `armv7-unknown-linux-uclibceabihf`, but it's somewhat inconvenient, because it's a tier 3 target and I can't install it with rustup. Maybe it's better to use `armv7-unknown-linux-musleabihf` in this case (I have no idea if this will actually work).

**Comment by bjorn3** [comment]
Yeah, trying to use `-gnu` targets with anything other than glibc is likely to give issues. Same for `-musl` targets for anything other than musl. If you are using nightly, you can use `cargo build -Zbuild-std=std --target armv7-unknown-linux-uclibceabihf` to tell cargo to compile the standard library for `armv7-unknown-linux-uclibceabihf` without having to install it using rustup.

**Comment by Nilstrieb** [comment]
Closing as this doesn't look like a bug. gnu targets are supposed to depend on glibc. `-Zbuild-std` should make it easier to get the target working as described above.
