### ISSUE TITLE
nix has a CVE reported against it, rust-lang uses vulnerable version

### ISSUE THREAD

**Issue by danakj** [rust-lang/rust#112585]
CVE reported here: https://osv.dev/vulnerability/GHSA-76w9-p8mg-j927

> An issue was discovered in the nix crate before 0.20.2, 0.21.x before 0.21.2, and 0.22.x before 0.22.2 for Rust. unistd::getgrouplist has an out-of-bounds write if a user is in more than 16 /etc/groups groups.

To resolve the issue, Rust should immediately roll nix to 0.20.2, 0.21.2 or 0.22.2.

**Comment by danakj** [comment]
This was found by a vulnerability scanner which found a nix 0.9.0 dependency through `/tools/clippy/tests/ui-cargo/multiple_crate_versions/fail/Cargo.lock`

It's not mentioned in the lock file itself, but I guess as a transitive dependency?

**Comment by Nilstrieb** [comment]
that makes no sense, the lockfile mentions all dependencies. if you figure out whats going on and update it, then feel free to send a PR bumping it (send it to rust-lang/clippy if it touches the clippy tests).

**Comment by Nilstrieb** [comment]
ah I see, it's already fixed in rust-lang/clippy

**Comment by Nilstrieb** [comment]
just needs a subtree sync which will probably happen in the next few weeks

**Comment by Nilstrieb** [comment]
gonna close it as completed
