### ISSUE TITLE
Mixed-style trait bounds for `Send` marker breaks build of dependent project

### ISSUE THREAD

**Issue by uklotzde** [rust-lang/rust#112547]
I tried this code:

Method signature in external dependency `midir`:

```rust
    pub fn connect<F, T: Send>(
        self, port: &MidiInputPort, port_name: &str, callback: F, data: T
    ) -> Result<MidiInputConnection<T>, ConnectError<MidiInput>>
        where F: FnMut(u64, &[u8], &mut T) + Send + 'static {
```

I expected to see this happen: The compiler should not distinguish between inline trait bounds and trait bounds specified in a `where` clause.

Instead, this happened: Out of the blue without installing any new Rust versions the compilation of the `midir` dependency started to fail.

```
$ cargo check
    Updating crates.io index
   Compiling libc v0.2.146
   Compiling pkg-config v0.3.27
    Checking bitflags v1.3.2
    Checking cfg-if v1.0.0
   Compiling alsa-sys v0.3.1
    Checking nix v0.24.3
    Checking alsa v0.7.0
    Checking midir v0.9.1
error[E0277]: `T` cannot be sent between threads safely
   --> /home/uk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/midir-0.9.1/src/common.rs:113:64
    |
113 |         match self.imp.connect(&port.imp, port_name, callback, data) {
    |                        -------                                 ^^^^ `T` cannot be sent between threads safely
    |                        |
    |                        required by a bound introduced by this call
    |
note: required by a bound in `backend::alsa::MidiInput::connect`
   --> /home/uk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/midir-0.9.1/src/backend/alsa/mod.rs:236:26
    |
236 |     pub fn connect<F, T: Send>(
    |                          ^^^^ required by this bound in `MidiInput::connect`
help: consider further restricting type parameter `T`
    |
112 |         where F: FnMut(u64, &[u8], &mut T) + Send + 'static, T: std::marker::Send {
    |                                                            ++++++++++++++++++++++

For more information about this error, try `rustc --explain E0277`.
error: could not compile `midir` (lib) due to previous error
```

Changing the method signature in `midir` by specifying all trait bounds in a `where` clause fixes the build error in the dependent project:

```rust
    pub fn connect<F, T>(
        self, port: &MidiInputPort, port_name: &str, callback: F, data: T
    ) -> Result<MidiInputConnection<T>, ConnectError<MidiInput>>
        where F: FnMut(u64, &[u8], &mut T) + Send + 'static, T: Send {
```

See also: https://github.com/Boddlnagg/midir/pull/133

The failure occurs when running `cargo check` on this _minimal reproducible example_ project on Fedora 38: 
[midir-build-failure.zip](https://github.com/rust-lang/rust/files/11721232/midir-build-failure.zip)

### Meta

`rustc --version --verbose`:
```
rustc 1.70.0 (90c541806 2023-05-31)
binary: rustc
commit-hash: 90c541806f23a127002de5b4038be731ba1458ca
commit-date: 2023-05-31
host: x86_64-unknown-linux-gnu
release: 1.70.0
LLVM version: 16.0.2
```

The nightly toolchain (rustc 1.72.0-nightly (37998ab50 2023-06-11)) also fails to compile the example project.

**Comment by flosse** [comment]
> The failure occurs when running `cargo check` on this _minimal reproducible example_ project on Fedora 38: [midir-build-failure.zip](https://github.com/rust-lang/rust/files/11721232/midir-build-failure.zip)

:thinking:  It works without issues on my system (NixOS 23.05.):

`rustc --version --verbose`:

```
rustc 1.70.0 (90c541806 2023-05-31)
binary: rustc
commit-hash: 90c541806f23a127002de5b4038be731ba1458ca
commit-date: 2023-05-31
host: x86_64-unknown-linux-gnu
release: 1.70.0
LLVM version: 16.0.2
```

**Comment by uklotzde** [comment]
Closing, because the bug could only be reproduced with my compromised(?) `.cargo` directory.

It is still worrisome not to understand why and how this happened. I can no longer trust the outcome and artifacts of a build after this experience.
