### ISSUE TITLE
Allow struct expressions for non_exhaustive structs if using update syntax

### ISSUE THREAD

**Issue by Flying-Toast** [rust-lang/rust#112592]
Defining a `non_exhaustive` struct like so:
```rust
#[derive(Default)]
#[non_exhaustive]
pub struct Foo {
    pub a: i32,
    pub b: char,
}
```

And using it from another crate like so:
```rust
let _ = Foo {
    a: 2,
    ..Default::default()
};
```

triggers `error[E0639]: cannot create non-exhaustive struct using struct expression`.

Struct expressions for non_exhaustive structs should be allowed iff they use record update syntax, which would ensure that a valid value of the struct (with all fields initialized) already exists.

**Comment by Flying-Toast** [comment]
I'd like to take a stab at implementing this, if it is a change that would be accepted.

**Comment by compiler-errors** [comment]
Some previous discussion, maybe could use some more searching but this is the first one I could find: https://internals.rust-lang.org/t/allow-fru-syntax-on-non-exhaustive-structs/12800

**Comment by Jules-Bertholet** [comment]
https://github.com/rust-lang/lang-team/issues/143

-----

@rustbot label C-feature-request

**Comment by Flying-Toast** [comment]
Ah sorry, I see this has already been discussed before. I'll close this issue to avoid clogging the issue tracker.
