### ISSUE TITLE
Couldn't open docs using LibreWolf (Firefox derivative)

### ISSUE THREAD

**Issue by Konglomneshued** [rust-lang/rust#112536]
I'm using LibreWolf, which is a derivative of Firefox, and I have it set as my default browser for my OS.  I built docs for my starter project and it was unable to open them automatically, I will have to do it manually.

![image](https://github.com/rust-lang/rust/assets/94726665/1f4f52d8-c48e-413f-a5ae-91bf9bc69173)

**Comment by workingjubilee** [comment]
@Konglomneshued Are you *sure* you have it set as your default browser? cargo will read `$BROWSER` if not otherwise configured.

**Comment by Konglomneshued** [comment]
That's odd.  I have it set in XFCE but the variable has not changed from Firefox.  I'll change it and try again.

**Comment by Konglomneshued** [comment]
That worked, thank you.
