### ISSUE TITLE
Miscompilation on i686-pc-windows-msvc with Fat LTO

### ISSUE THREAD

**Issue by kdy1** [rust-lang/rust#112576]
I tried this code:

https://github.com/swc-project/swc/blob/275db1baec0046c15e35456c268295c5e7a42517/crates/swc_ecma_codegen/src/lib.rs#L2435-L2463

(May not be exact, just a guess based on the test failure)

I expected to see this happen: Binaries behave identically regardless of CPU arch.

Instead, this happened: CI for publishing action failed.

### Meta

I'm trying to enable LTO for release builds of [swc](https://swc.rs), with https://github.com/swc-project/swc/pull/7509. But it seems like `rustc` miscompiles on some platforms if I enable LTO.

Full log: https://github.com/swc-project/swc/actions/runs/5212808850/jobs/9406918334?pr=7509

`rustc --version --verbose`:
```
rustc 1.70.0-nightly (da7c50c08 2023-03-19)
binary: rustc
commit-hash: da7c50c089d5db2d3ebaf227fe075bb1346bfaec
commit-date: 2023-03-19
host: aarch64-apple-darwin
release: 1.70.0-nightly
LLVM version: 15.0.7
```

**Comment by Nilstrieb** [comment]
may or may not be related to #109114
it would be nice to have a more minimal example to rule out undefined behavior in SWC

**Comment by kdy1** [comment]
@lqd Do you mean I should use `-Zdylib-lto` if I want to enable the fat LTO?

**Comment by Nilstrieb** [comment]
no, but that flag is known to be broken already

**Comment by lqd** [comment]
> @lqd Do you mean I should use `-Zdylib-lto` if I want to enable the fat LTO?

No, it's an internal flag (basically only intended for rustc to use) that has known issues on windows. 

I meant that:
- this issue is unlikely to be related to https://github.com/rust-lang/rust/issues/109114 because of that
- unless I'm missing something, this issue is also probably unrelated to ThinLTO since your PR enabled fat LTO

**Comment by apiraino** [comment]
@kdy1 are you still affected by this issue? Can you provide an update or close - if it's the case? Thanks

**Comment by kpreid** [comment]
Relabeling issues which don't have a runnable reproduction (as opposed to not having a minimized one) to the new label S-needs-repro.
@rustbot label +S-needs-repro -E-needs-mcve

**Comment by kdy1** [comment]
Closing as I don't have time to create a minimal repro
