### ISSUE TITLE
install default rust, all log shows that it's 1.70, but run rustc --version show 1.69

### ISSUE THREAD

**Issue by luckyfish0826** [rust-lang/rust#112690]
system: ubuntu
command: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

log says:
stable-x86_64-unknown-linux-gnu installed - rustc 1.70.0 (90c541806 2023-05-31)

yet run rustc --version show: 
info: latest update on 2023-04-20, rust version 1.69.0 (84c898d65 2023-04-16)

use rustup update command did not nothing.

I found this problem because I encountered error msg: Unknown flag: --experimental_allow_proto3_optional

Any one can help?

**Comment by bjorn3** [comment]
Do you have another rustc installation outside of rustup? What does `which rustc` show?

**Comment by luckyfish0826** [comment]
> 
Hi bjorn, thanks.
type: which rustc   
outcome:  /home/company_name/.cargo/bin/rustc

and I cd into that folder, rustc -V produces 1.70 instead of 1.69, really strange.

**Comment by bjorn3** [comment]
And `rustup show`?

**Comment by luckyfish0826** [comment]
I might found the problem. It's because in the currently folder, we have a file named "rust-toolchain.toml "
and: 
cat rust-toolchain.toml 
it says:

`[toolchain]
channel = "1.69.0"
components = ["rustfmt", "clippy"]`

I'll try to changed it to 1.70, see if it's all right.

**Comment by bjorn3** [comment]
Right, `rust-toolchain.toml` will take precedence over the user default toolchain. You can use something like `cargo +1.70 build` to override `rust-toolchain.toml` for a single cargo invocation, or edit `rust-toolchain.toml` if you want to keep using a different version for the project.

**Comment by jyn514** [comment]
I'm glad you figured this out.

The issue tracker is not a support forum. For future questions please ask in one of these places:

https://discord.gg/rust-lang/
https://discord.gg/rust-lang-community/
https://users.rust-lang.org/
https://rust-lang.zulipchat.com/
