### ISSUE TITLE
bootstrap: Allow configuring the opt-level, not just debug vs release

### ISSUE THREAD

**Issue by Nilstrieb** [rust-lang/rust#112678]
It would be nice if we could speed up stage1 library builds by building it with less opts and no debuginfo.

@jyn514 had the idea to control this with something like `rust.stage1.opt-level`

**Comment by jyn514** [comment]
i'm going to make a separate more broad issue for `rust.stage1` - i'll repurpose this to just be for `rust.opt-level` (which is a lot simpler to add)

**Comment by jyn514** [comment]
mentoring instructions: add this option to the `config::Rust` struct, then around https://github.com/rust-lang/rust/blob/dcf3571c513a29a60a5061ce84c3c618cf5e4cd5/src/bootstrap/builder.rs#L1679, set `cargo.env(profile_var("OPT_LEVEL"), config.opt_level)`

**Comment by Mark-Simulacrum** [comment]
Can we confirm before we land this support that this is actually a significant win in practice? I recall historically having issues with optimize = false equivalents where the net effect is broken _and_ slower tests - I would prefer to avoid landing support we don't want to actually support :)

**Comment by jyn514** [comment]
@Mark-Simulacrum this is especially useful in combination with #112679 - optimizing only rustc and not std should be a speedup even if we include the time taken for tests.

**Comment by Kobzol** [comment]
Maybe we should just generalize the `optimize` config value to a number/boolean, instead of adding a new attribute?
