### ISSUE TITLE
A Issue about borrowed check

### ISSUE THREAD

**Issue by chiyu-svg** [rust-lang/rust#112649]
I get a Issue about borrowed check, as  follows code

```rust
fn remove_node(&mut self, val: i32) {
        let mut current_node = &mut self.head;
        while let Some(node) = current_node {
            if node.val == val {  
                *current_node = node.next.take();
                break;
            } else {
                current_node = &mut node.next;
            }
        }
    }
```
I get a error message("`*crruent_node` is assigned to here but it was already borrowed  borrow later used here").  if remove else block code or if block code, i will don't get error. I don't know why. 

these all code: 
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=58e05f4797ae720a69b8a126626db43a

**Comment by jyn514** [comment]
The issue tracker is not a support forum. For future questions please ask in one of these places:

https://discord.gg/rust-lang/
https://discord.gg/rust-lang-community/
https://users.rust-lang.org/
https://rust-lang.zulipchat.com/
