### ISSUE TITLE
document that std::fmt uses ROUND_HALF_EVEN

### ISSUE THREAD

**Issue by Krappa322** [rust-lang/rust#112742]
I tried this code:

```rust
    println!("{:.0}", 10.5f64);
```

I expected to see this happen: It prints 11

Instead, this happened: It prints 10

As far as I am able to find 10.5 has a perfect (lossless) representation in f64-space so it does not seem to be because of floating point error to me.

If I put in 9.5 instead it does work as expected (it prints 10), which is weird because that also has a perfect representation as f64. Is it applying a round_ties_even() kind of logic? If it is then I would expect this to be documented e.g. under https://doc.rust-lang.org/std/fmt/#precision

### Meta
I've been using rust playground, rust version 1.70.0

**Comment by zredb** [comment]
I tested it on Playground and it is indeed related to Odd and Even
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&code=fn+main%28%29+%7B%0A++++%2F%2F+rust+%E6%8E%A8%E6%96%AD%E5%87%BAx%E7%9A%84%E7%B1%BB%E5%9E%8B%0A++++println%21%28%22%7B%3A.0%7D%22%2C+12.5f64%29%3B%0A++++println%21%28%22%7B%3A.0%7D%22%2C+11.5f64%29%3B%0A++++println%21%28%22%7B%3A.0%7D%22%2C+10.5f64%29%3B%0A++++println%21%28%22%7B%3A.0%7D%22%2C+9.5f64%29%3B%0A++++println%21%28%22%7B%3A.0%7D%22%2C+8.5f64%29%3B%0A++++println%21%28%22%7B%3A.0%7D%22%2C+7.5f64%29%3B%0A%7D%0A

**Comment by quixoticaxis** [comment]
Is it a bug though? Ties to even seems to be the [recommended default of IEEE754 for floating point](https://en.m.wikipedia.org/wiki/Rounding#Rounding_half_to_even).

**Comment by quixoticaxis** [comment]
As a side-note: IMHO, duplicating the description of floating point math to the documentation of Rust formatting facilities looks like an overkill as there are numerous quircks.

**Comment by Krappa322** [comment]
`printf` seems to do the same thing as well:
```
    long double num = 10.5;
    printf("%.0llf %.0llf\n", num, round(num));
```
outputs "10 11" in godbolt with both gcc and clang. Could be dependent on the libc implementation though of course. I can't find anything in C documentation that mentions the rounding strategy either

**Comment by Krappa322** [comment]
In any case I would say it's quite unexpected both for rust and for c that calling round() produces a different result than printing the number with a precision of zero. It really does seem worth mentioning in documentation

**Comment by Krappa322** [comment]
Looks like someone has already done the research for us and found out that it's inconsistent in C and in tons of other languages as well, not only between languages but also between platforms using the same language. For example, it says that MSVC does rounding away from zero
https://www.exploringbinary.com/inconsistent-rounding-of-printed-floating-point-numbers/

(see also https://stackoverflow.com/questions/10357192/printf-rounding-behavior-for-doubles - that's how I found that article)

**Comment by Krappa322** [comment]
And also https://sourceware.org/bugzilla/show_bug.cgi?id=4943

**Comment by eval-exec** [comment]
I found this:
```rust
	println!("{:.1}", 3.33f64);   // 3.3
	println!("{:.1}", -3.33f64);  // -3.3
	println!("{:.1}", -3.55f64);  // 3.5
	println!("{:.1}", 4.54f64);   // 4.5
	println!("{:.1}", 4.55f64);   // 4.5
	println!("{:.1}", 4.56f64);   // 4.6

```

**Comment by eval-exec** [comment]
https://github.com/rust-lang/rust/blob/aa9837ba29d88d0748e2599e46403f333a629836/library/core/tests/fmt/float.rs#L28-L85

**Comment by asquared31415** [comment]
`4.55f64` cannot be represented exactly, and is actually `4.54999999999999982236431605997`
on the other hand `.5`, `.75`, and `.125` *can* be represented exactly at these magnitudes, since those are reciprocals of powers of 2, and these numbers are rather small.

**Comment by ehuss** [comment]
I'm going to close as I believe this is resolved by https://github.com/rust-lang/rust/pull/120967. Please let us know if this should be kept open.
