### ISSUE TITLE
Improve display of type kind in search results

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#112721]
In #110688, the type kind was added before the type name. However, having a visual distinction would make the reading better. Something making the text bold could work maybe? To be discussed.

**Comment by junderw** [comment]
Suggestion:

- Make the type kind the same color as the item itself
- Make the type kind bold

---

I wasn't aware that the colors in the search results corresponded to a type kind, so making the type kind the same color would help cement that in the viewers mind.

**Comment by dns2utf8** [comment]
I would prefer the kind of item be a specific icon with the alt text shown on hover

**Comment by GuillaumeGomez** [comment]
Just for your information, @poliorcetics opened https://github.com/rust-lang/rust/pull/112720. I think it's a nice improvement of the current situation.

> I would prefer the kind of item be a specific icon with the alt text shown on hover

I'm not sure it's a good idea to ask users to remember more symbols to make UI shorter.

**Comment by dns2utf8** [comment]
That is a good point

**Comment by poliorcetics** [comment]
> Make the type kind the same color as the item itself

I experimented with that in my PR and it's way too distracting imo.

I ended up on using the same grey for all item kinds to make it less eye catching

**Comment by GuillaumeGomez** [comment]
Fixed by https://github.com/rust-lang/rust/pull/112720.
