### ISSUE TITLE
x.py setup dist says it uses src/bootstrap/defaults/config.dist.toml, which does not exist

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#112846]
Just like the title says, I did `x.py setup` and selected "dist", which claims it inherits its settings from a file that does not actually exist.

**Comment by pnkfelix** [comment]
Oh and even better, when you then do `x.py dist` in the resulting directory that has that `config.toml` generated via `x.py setup dist`, you get this error:

```
% time ../x.py  dist
Traceback (most recent call last):
  File "/media/pnkfelix/Rust/rust.git/objdir-beta/../x.py", line 50, in <module>
    bootstrap.main()
  File "/media/pnkfelix/Rust/rust.git/src/bootstrap/bootstrap.py", line 1094, in main
    bootstrap(args)
  File "/media/pnkfelix/Rust/rust.git/src/bootstrap/bootstrap.py", line 1030, in bootstrap
    with open(include_path) as included_toml:
FileNotFoundError: [Errno 2] No such file or directory: '/media/pnkfelix/Rust/rust.git/src/bootstrap/defaults/config.dist.toml'
```

**Comment by pnkfelix** [comment]
(Should we have a check at the time when we generate the `config.toml`  ensuring that the referenced settings file exists? And if it doesn't ... abort the attempt to generate `config.toml` in the first place?  This seems like a somewhat unfortunate scneario to get into. The main other options I can imagine are 1. to issue an error when the file denoted by `profile = "xxx" doesn't exist, at the time when we are invoking `x.py` with an incoherent `config.toml`, or 2.  to "just" issue a warning when the file denoted by `profile = "xxx"` doesn't exist, but otherwise continue with the given `config.toml` as it stands.)

**Comment by albertlarsan68** [comment]
Yep, it is a direct consequence. I think we should revert this PR, it seems to be causing more harm than good.
