### ISSUE TITLE
Create libabc-rs (and possibly xyz program) as a sample library

### ISSUE THREAD

**Issue by uzytkownik** [rust-lang/rust#11286]
It might be my bias but one of the problems I struggled mostly so far while I am trying to learn ruby and write library is the little details how to write library. The issues so far were for example:

 - What's the proper structure (should <code>lib.rs</code> be in top directory or <code>src/<name>/</code>?)
 - Where test.rs should be (main directory? <code>src/<name>/</code>)?
 - How to build documentation?
 - What are the policies of annoucement of new libraries?

While some documentation exists it tend to be widespread and sometimes outdated (it might be on third party sites and be say about rust 0.6).

In Linux world there is [libabc project](http://0pointer.de/blog/projects/libabc.html) which includes a basic sample projects showing how things are supposed to be done. While many details are not applicable to rust it'd be nice to have something like that kept in sync with rust.

**Comment by steveklabnik** [comment]
We do this in the book now, and in the cargo guide.
