### ISSUE TITLE
many feature flags results in poor overflow behavior

### ISSUE THREAD

**Issue by cdmistman** [rust-lang/rust#112880]
see <https://docs.rs/tower-http/latest/tower_http/index.html#enums>

<img width="1728" alt="image" src="https://github.com/rust-lang/docs.rs/assets/23486351/4a694c75-b385-447e-931a-77eda70eee9b">

- Arc 0.108.1 (39609)
- MacOS 13.2.1 (22D68)

**Comment by Nemo157** [comment]
Actually, rather than #104991 this made me realise there's another issue around how we deal with inlined re-exports, opened #112881 for that.

**Comment by GuillaumeGomez** [comment]
It's also kinda related to https://github.com/rust-lang/rust/issues/87957.
