### ISSUE TITLE
Tuples containing references no longer pass PartialEq bounds check for all lifetimes of the other reference

### ISSUE THREAD

**Issue by smwoj** [rust-lang/rust#112895]
### Code

I tried this code:

```rust
trait T {
    type Key<'a>: for<'b> PartialEq<Self::Key<'b>>
    where
        Self: 'a;
}

impl T for () {
    type Key<'a> = (&'a str, u32);
}
```

It used to compile on 1.69, so I expected it to compile under 1.70, but it failed with the following error
```
error: implementation of `PartialEq` is not general enough
 --> src/lib.rs:8:20
  |
8 |     type Key<'a> = (&'a str, u32);
  |                    ^^^^^^^^^^^^^^ implementation of `PartialEq` is not general enough
  |
  = note: `(&'a str, u32)` must implement `PartialEq<(&'0 str, u32)>`, for any lifetime `'0`...
  = note: ...but it actually implements `PartialEq`
```

The same happens for structs that contain a reference and derive `PartialEq`.

([godbolt link](https://godbolt.org/z/Mn8a9sPon))

### Version it worked on

1.69

### Version with regression

1.70

`rustc --version --verbose`:
```
rustc 1.70.0 (90c541806 2023-05-31)
binary: rustc
commit-hash: 90c541806f23a127002de5b4038be731ba1458ca
commit-date: 2023-05-31
host: x86_64-unknown-linux-gnu
release: 1.70.0
LLVM version: 16.0.2
```

@rustbot modify labels: +regression-from-stable-to-stable -regression-untriaged

**Comment by compiler-errors** [comment]
searched nightlies: from nightly-2023-03-01 to nightly-2023-06-21
regressed nightly: nightly-2023-03-29
searched commit range: https://github.com/rust-lang/rust/compare/2036fdd24f77d607dcfaa24c48fbe85d3f785823...478cbb42b730ba4739351b72ce2aa928e78e2f81
regressed commit: https://github.com/rust-lang/rust/commit/478cbb42b730ba4739351b72ce2aa928e78e2f81

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.5</summary>


Host triple: aarch64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start=2023-03-01 
```
</details>

----

This probably regressed in #109470.

**Comment by compiler-errors** [comment]
I don't know if this predicate should have held in the first place 🤔 

```
fn test<'a>() where (&'a str, u32): for<'b> PartialEq<(&'b str, u32)> {}

fn main() {
    test();
}
```

I *think* code demonstrates that `(&str, u32): for<'b> PartialEq<(&'b str, u32)>` doesn't hold -- the lifetimes have to be equal as a consequence of the `PartialEq` implementation for tuples

**Comment by compiler-errors** [comment]
The previous code is possibly unsound:

```
trait Lengthen<T> {
    fn lengthen(self) -> T;
}

impl<'a> Lengthen<&'a str> for &'a str {
    fn lengthen(self) -> &'a str { self }
}

trait Gat {
    type Gat<'a>: for<'b> Lengthen<Self::Gat<'b>>;

    fn lengthen(s: Self::Gat<'_>) -> Self::Gat<'static> {
        s.lengthen()
    }
}

impl Gat for () {
    type Gat<'a> = &'a str;
}

fn main() {
    let s = "hello, garbage".to_string();
    let borrow: &'static str = <() as Gat>::lengthen(&s);
    drop(s);

    println!("{borrow}");
}
```

**Comment by lcnr** [comment]
I think there are two actionable steps there:
- to fix this concrete breakage, and because it is strictly more powerful, we can try to change the `PartialEq` impls in `core` to `impl<T, U> PartialEq<(T,)> for (U,) where U: PartialEq<T>` as stated by @BoxyUwU. this may worsen inference but feels generally worthwhile to me.
- https://github.com/rust-lang/rust/pull/109470 does not mention that it fixes an unsoundness, we should add the example by @compiler-errors as a test

**Comment by compiler-errors** [comment]
(1.) is not feasible, I think. See the crater results for https://github.com/rust-lang/rust/pull/112899

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23112895.20Tuples.20containing.20references.20no.20longer.20pass.20Partial.E2.80.A6)).

@rustbot label -I-prioritize +P-medium

**Comment by workingjubilee** [comment]
Breaking code via breaking inference is, strictly speaking, a permitted breakage.
Of course, breaking unsound code is, in a greater sense, also permitted breakage.

**Comment by smwoj** [comment]
> I think there are two actionable steps there:
> 
> to fix this concrete breakage, and because it is strictly more powerful, we can try to change the PartialEq impls in core to impl<T, U> PartialEq<(T,)> for (U,) where U: PartialEq<T> as stated by @BoxyUwU. this may worsen inference but feels generally worthwhile to me.
> (...)

> (1.) is not feasible, I think. See the crater results for https://github.com/rust-lang/rust/pull/112899

Is there a way to measure the impact of that crater run on the ecosystemt? Breakage in serde or chrono would be surely a more serious problem than a breakage in a toy application and with untrained eye I can't tell if the breakage is disastrous or just a little beyond acceptable.

Improving the `PartialEq` implementation for tuples strikes me as a "right thing to do" for the standard library. If we can't have it now, would it be possible to change it in a new edition? It would be sad if we were stuck forever with the current implementation when a strictly more powerful one exists.

**Comment by workingjubilee** [comment]
The stdlib's implementations are largely unrelated to the edition mechanism: the editions mostly introduce syntactic changes, not library changes, with the one blurriness being with macros which interact with syntax.

What really needs to improve is the algorithm for deducing types, then it would be easier for the stdlib to carry more powerful implementations without fear of breaking inference.
