### ISSUE TITLE
Add support for visionOS (Tier 3)

### ISSUE THREAD

**Issue by conradev** [rust-lang/rust#112930]
The visionOS SDK was just released and it contains two new platforms, `xros` and `xrsimulator`, which need their own Rust targets. Specifically, I believe these new targets would be desirable:

- `aarch64-apple-xros`
- `aarch64-apple-xros-sim`
- `x86_64-apple-xros-sim`

I would propose starting these out as Tier 3 for now. I wanted to create this issue for tracking, but I might work on this if no one beats me to it

**Comment by compiler-errors** [comment]
Is there an [MCP](https://forge.rust-lang.org/compiler/mcp.html) filed for this? If not, you should do that first.

The compiler repo has examples of other add-new-tier-3-support MCPs under the [accepted MCPs](https://github.com/rust-lang/compiler-team/issues?q=is%3Aissue+is%3Aclosed+label%3Amajor-change-accepted+) label.

**Comment by conradev** [comment]
https://github.com/rust-lang/compiler-team/issues/642

**Comment by conradev** [comment]
Work is being tracked here: https://github.com/rust-lang/rust/pull/121419
