### ISSUE TITLE
`core` sometimes is resolved when not defined

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#112924]
The following two snippets:

```rust
#![crate_type = "lib"]
use core::option::Option;
```
```rust
#![crate_type = "lib"]
const _: core::option::Option<u32> = None;
```

I expected both of them to either compile, or not.

Instead, only the `const` one compiles, while the `use` one doesn't:
```
error[E0433]: failed to resolve: maybe a missing crate `core`?
 --> ./x.rs:2:5
  |
2 | use core::option::Option;
  |     ^^^^ maybe a missing crate `core`?
  |
  = help: consider adding `extern crate core` to use the `core` crate
```

Note that the `core` crate is not defined in either test, as can be seen by using `-Zunpretty=hir`:
```rust
#![crate_type = "lib"]
#[prelude_import]
use ::std::prelude::rust_2015::*;
#[macro_use]
extern crate std;
use core::option::Option;
```
```rust
#![crate_type = "lib"]
#[prelude_import]
use ::std::prelude::rust_2015::*;
#[macro_use]
extern crate std;
const _: core::option::Option<()> = None;
```

Similarly to a `const`, `impl core::iter::Iterator for ... { ... }`, `fn f() { core::option::Option::Some(()) }`, `fn f() -> core::option::Option<()> { None }` and others work. The only thing I could find to issue an error is a `use`.

Edition note:
- non-`use`
  - On 2015 `core::option::Option` will work, but both `::core::...` and `crate::core::...` will error
  - On 2018 and 2021 `core::option::Option` and `::core::...` will work, but `crate::` will error
- `use`
  - On 2015 none of `core::...`, `::core::...` and `crate::core` work
  - On 2018 and 2021 only `core::...` and `::core::....` works, while  `crate::core` doesn't

Given all of that it seems that
1. `core` is in the [extern prelude](https://doc.rust-lang.org/stable/reference/names/preludes.html#extern-prelude) (as documented), but
2. `core` is not present at the crate root, but
3. **Everything that is not a `use` can access stuff from extern prelude**

This is very confusing to say the least.

I'd expect any of the following outcomes:
1. `core` is both in the extern prelude _and_ crate root, anything can refer to it (IMO the best option)
2. `core` is neither in the extern prelude _nor_ in the crate root, nothing can refer to it

But not what we currently have...

### Meta

`rustc --version --verbose`:
```
rustc 1.72.0-nightly (065a1f5df 2023-06-21)
binary: rustc
commit-hash: 065a1f5df9c2f1d93269e4d25a2acabbddb0db8d
commit-date: 2023-06-21
host: aarch64-unknown-linux-gnu
release: 1.72.0-nightly
LLVM version: 16.0.5
```

**Comment by petrochenkov** [comment]
I tried to change 2015 behavior to be more uniform with modern editions in https://github.com/rust-lang/rust/pull/57745, but in the end the decision was to just keep legacy things frozen.

**Comment by WaffleLapkin** [comment]
Oh, I noticed an error in my post, I thought `use core...` doesn't work on edition >= 2018, but it actually *does* work. Yeah, then the edition >= 2018 looks sane.
