### ISSUE TITLE
Fix Ferris's gender in compiler error

### ISSUE THREAD

**Issue by JorgeCepeda** [rust-lang/rust#112975]
Using 🦀 may print an error reading "try using their name", as "their" means multiple, more than one, and since it is a singular crab, the correct gender should be "it".

**Comment by matthiaskrgr** [comment]
I think this falls into the second example: https://www.merriam-webster.com/dictionary/their

2: his or her : [his](https://www.merriam-webster.com/dictionary/his), [her](https://www.merriam-webster.com/dictionary/her), [its](https://www.merriam-webster.com/dictionary/its)
—used with an indefinite third person singular antecedent

>anyone in their senses
>— W. H. Auden

**Comment by JorgeCepeda** [comment]
Singular "they" is not used with animals

**Comment by 0atman** [comment]
I think it's used with ferris because we've humanised them! Like how pet owners won't use 'it' for their pet, they'll always use s/he.
"it" feels too impersonal, perhaps.

**Comment by juntyr** [comment]
According to rustacean, Ferris uses any pronouns and he/she/they/it are all ok (https://www.rustacean.net). Ferris' creator, Karen Rustad Tölva, further specified that he, she, or they suit Ferris best (https://www.rustacean.net/assets/ferris-pronouns.png). So using they for Ferris seems like a good default choice, though rotating through a variety of pronouns would also be an option.
