### ISSUE TITLE
Stable MIR's thread local not properly handled on unwind

### ISSUE THREAD

**Issue by programmerjake** [rust-lang/rust#112940]
https://github.com/rust-lang/rust/blob/7f74ae57e8e24e87b7177af43db6ec0e8262cd5d/compiler/rustc_smir/src/stable_mir/mod.rs#L113-L114

`TLV` is left set to a dangling pointer if `f` unwinds. This is unsound because a later call to `with` will use that dangling pointer. There is a similar issue with `with` and unwinding.

since you're on the Stable MIR cc list:
cc @oli-obk, @celinval

**Comment by programmerjake** [comment]
if you can add it as a dependency, using [scoped-tls](https://github.com/alexcrichton/scoped-tls) would probably be better than rolling your own version.

**Comment by oli-obk** [comment]
> using [scoped-tls](https://github.com/alexcrichton/scoped-tls)

Yea, that makes sense. I think we should look into using it for the `tls` module, too, which is how we get a `TyCtxt` within the compiler itself
