### ISSUE TITLE
from_base64 fails when str ends with `=\n`

### ISSUE THREAD

**Issue by zokier** [rust-lang/rust#11308]
Demonstration/testcase: https://gist.github.com/zokier/8254831

I'm thinking that in [here](https://github.com/mozilla/rust/blob/master/src/libextra/base64.rs#L222) should be a check for newlines to allow a single trailing newline.

On a related note it might be better to escape the invalid character in the error message, so that in cases of non-printable characters (like newlines) the message would be clearer.

**Comment by alexcrichton** [comment]
cc @nick29581, can this move to rust-lang/rustc-serialize?
