### ISSUE TITLE
ICE: `'no saved object file in work product', compiler\rustc_codegen_ssa\src\back\write.rs:895:45`

### ISSUE THREAD

**Issue by nikunjitaliya2** [rust-lang/rust#113092]
### Code

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
<version>
```
  Downloaded lock_api v0.4.9
  Downloaded kuchiki v0.8.1
  Downloaded json-patch v0.2.7
  Downloaded html5ever v0.25.2
  Downloaded dunce v1.0.3
  Downloaded autocfg v1.1.0
  Downloaded fxhash v0.2.1
  Downloaded cssparser-macros v0.6.0
  Downloaded webview2-com-sys v0.19.0
  Downloaded windows v0.37.0
  Downloaded windows-metadata v0.39.0
  Downloaded infer v0.7.0
  Downloaded windows v0.44.0
  Downloaded windows v0.39.0
  Downloaded 216 crates (89.5 MB) in 28.46s (largest was `windows` at 14.1 MB)
   Compiling tracker v0.0.0 (D:\Nikunj Italiya\EOM\eom-tracker\src-tauri)
thread 'copy LTO artifacts for lr88xwr831csap3' panicked at 'no saved object file in work product', /rustc/90c541806f23a127002de5b4038be731ba1458ca\compiler\rustc_codegen_ssa\src\back\write.rs:895:45
stack backtrace:
thread 'copy LTO artifacts for fn1kuhgx6l6pcvs' panicked at 'no saved object file in work product', /rustc/90c541806f23a127002de5b4038be731ba1458ca\compiler\rustc_codegen_ssa\src\back\write.rs:895:45
   0:     0x7ffc412b6c02 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he4dbe7f5385cd1e2
   1:     0x7ffc412f4f5b - core::fmt::write::h72b30843329f2c20
   2:     0x7ffc412abe6a - <std::io::IoSliceMut as core::fmt::Debug>::fmt::h44d7f217ec8c08a4
   3:     0x7ffc412b694b - std::sys::common::alloc::realloc_fallback::h25dd000eefb1a25f
   4:     0x7ffc412ba2da - std::panicking::default_hook::h8d2d551f7739f430
   5:     0x7ffc412b9f40 - std::panicking::default_hook::h8d2d551f7739f430
   6:     0x7ffbf4b2f02e - rustc_driver_impl[39e757d53880b308]::describe_lints
   7:     0x7ffc412babef - std::panicking::rust_panic_with_hook::h2561aa68cd5abc10
   8:     0x7ffc412ba94e - <std::panicking::begin_panic_handler::StrPanicPayload as core::panic::BoxMeUp>::get::hcac4dd4b6ea7d20c
   9:     0x7ffc412b78a9 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he4dbe7f5385cd1e2
  10:     0x7ffc412ba660 - rust_begin_unwind
  11:     0x7ffc41329165 - core::panicking::panic_fmt::he37b281957295da9
  12:     0x7ffc41329122 - core::option::expect_failed::h6e973b078d349f38
  13:     0x7ffbf23de85e - <rustc_codegen_llvm[63bb3427bc0dbc23]::ModuleLlvm as core[bcfc2130cb4e43e7]::ops::drop::Drop>::drop
  14:     0x7ffbf23f71ad - <rustc_codegen_llvm[63bb3427bc0dbc23]::llvm_::ffi::Type>::i8p_llcx
  15:     0x7ffbf23f815d - <rustc_codegen_llvm[63bb3427bc0dbc23]::llvm_::ffi::Type>::i8p_llcx
  16:     0x7ffc412ccaac - std::sys::windows::thread::Thread::new::h911abb68de5d2aa0
  17:     0x7ffcb82326ad - BaseThreadInitThunk
  18:     0x7ffcb9cca9f8 - RtlUserThreadStart

stack backtrace:
   0:     0x7ffc412b6c02 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he4dbe7f5385cd1e2
   1:     0x7ffc412f4f5b - core::fmt::write::h72b30843329f2c20
   2:     0x7ffc412abe6a - <std::io::IoSliceMut as core::fmt::Debug>::fmt::h44d7f217ec8c08a4
   3:     0x7ffc412b694b - std::sys::common::alloc::realloc_fallback::h25dd000eefb1a25f
   4:     0x7ffc412ba2da - std::panicking::default_hook::h8d2d551f7739f430
   5:     0x7ffc412b9f40 - std::panicking::default_hook::h8d2d551f7739f430
   6:     0x7ffbf4b2f02e - rustc_driver_impl[39e757d53880b308]::describe_lints
   7:     0x7ffc412babef - std::panicking::rust_panic_with_hook::h2561aa68cd5abc10
   8:     0x7ffc412ba94e - <std::panicking::begin_panic_handler::StrPanicPayload as core::panic::BoxMeUp>::get::hcac4dd4b6ea7d20c
   9:     0x7ffc412b78a9 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he4dbe7f5385cd1e2
  10:     0x7ffc412ba660 - rust_begin_unwind
  11:     0x7ffc41329165 - core::panicking::panic_fmt::he37b281957295da9
  12:     0x7ffc41329122 - core::option::expect_failed::h6e973b078d349f38
  13:     0x7ffbf23de85e - <rustc_codegen_llvm[63bb3427bc0dbc23]::ModuleLlvm as core[bcfc2130cb4e43e7]::ops::drop::Drop>::drop
  14:     0x7ffbf23f71ad - <rustc_codegen_llvm[63bb3427bc0dbc23]::llvm_::ffi::Type>::i8p_llcx
  15:     0x7ffbf23f815d - <rustc_codegen_llvm[63bb3427bc0dbc23]::llvm_::ffi::Type>::i8p_llcx
  16:     0x7ffc412ccaac - std::sys::windows::thread::Thread::new::h911abb68de5d2aa0
  17:     0x7ffcb82326ad - BaseThreadInitThunk
  18:     0x7ffcb9cca9f8 - RtlUserThreadStart

error: the compiler unexpectedly panicked. this is a bug.
error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.70.0 (90c541806 2023-05-31) running on x86_64-pc-windows-msvc

note: rustc 1.70.0 (90c541806 2023-05-31) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
query stack during panic:
end of query stack
thread '<unnamed>' panicked at '/rustc/90c541806f23a127002de5b4038be731ba1458ca\compiler\rustc_codegen_ssa\src\back\write.rs:1535:21: worker thread panicked', compiler\rustc_middle\src\util\bug.rs:36:26
stack backtrace:
   0:     0x7ffc412b6c02 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he4dbe7f5385cd1e2
   1:     0x7ffc412f4f5b - core::fmt::write::h72b30843329f2c20
   2:     0x7ffc412abe6a - <std::io::IoSliceMut as core::fmt::Debug>::fmt::h44d7f217ec8c08a4
   3:     0x7ffc412b694b - std::sys::common::alloc::realloc_fallback::h25dd000eefb1a25f
   4:     0x7ffc412ba2da - std::panicking::default_hook::h8d2d551f7739f430
   5:     0x7ffc412b9f40 - std::panicking::default_hook::h8d2d551f7739f430
   6:     0x7ffbf4b2f02e - rustc_driver_impl[39e757d53880b308]::describe_lints
   7:     0x7ffc412babef - std::panicking::rust_panic_with_hook::h2561aa68cd5abc10
   8:     0x7ffbf700350f - <rustc_infer[e6ccf410446393ba]::infer::opaque_types::table::OpaqueTypeStorage as core[bcfc2130cb4e43e7]::fmt::Debug>::fmt
   9:     0x7ffbf70032f9 - <rustc_infer[e6ccf410446393ba]::infer::opaque_types::table::OpaqueTypeStorage as core[bcfc2130cb4e43e7]::fmt::Debug>::fmt
  10:     0x7ffbf708c32a - <rustc_middle[298b6ec0f969779]::ty::print::pretty::ForceTrimmedGuard as core[bcfc2130cb4e43e7]::ops::drop::Drop>::drop
  11:     0x7ffbf70a1886 - rustc_middle[298b6ec0f969779]::util::bug::bug_fmt
  12:     0x7ffbf709fd3d - <rustc_middle[298b6ec0f969779]::ty::consts::int::ScalarInt as core[bcfc2130cb4e43e7]::fmt::Display>::fmt
  13:     0x7ffbf709fce4 - <rustc_middle[298b6ec0f969779]::ty::consts::int::ScalarInt as core[bcfc2130cb4e43e7]::fmt::Display>::fmt
  14:     0x7ffbf70a17e8 - rustc_middle[298b6ec0f969779]::util::bug::bug_fmt
  15:     0x7ffbf70a1765 - rustc_middle[298b6ec0f969779]::util::bug::bug_fmt
  16:     0x7ffbf23f5535 - <rustc_codegen_llvm[63bb3427bc0dbc23]::llvm_::ffi::Type>::i8p_llcx
  17:     0x7ffbf24404e4 - <rustc_codegen_llvm[63bb3427bc0dbc23]::back::archive::LlvmArchiveBuilderBuilder as rustc_codegen_ssa[9281276ceab4cff9]::back::archive::ArchiveBuilderBuilder>::new_archive_builder
  18:     0x7ffbf23f7d47 - <rustc_codegen_llvm[63bb3427bc0dbc23]::llvm_::ffi::Type>::i8p_llcx
  19:     0x7ffc412ccaac - std::sys::windows::thread::Thread::new::h911abb68de5d2aa0
  20:     0x7ffcb82326ad - BaseThreadInitThunk
  21:     0x7ffcb9cca9f8 - RtlUserThreadStart

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.70.0 (90c541806 2023-05-31) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread 'rustc' panicked at '/rustc/90c541806f23a127002de5b4038be731ba1458ca\compiler\rustc_codegen_ssa\src\back\write.rs:1893:17: panic during codegen/LLVM phase', compiler\rustc_middle\src\util\bug.rs:36:26
stack backtrace:
   0:     0x7ffc412b6c02 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he4dbe7f5385cd1e2
   1:     0x7ffc412f4f5b - core::fmt::write::h72b30843329f2c20
   2:     0x7ffc412abe6a - <std::io::IoSliceMut as core::fmt::Debug>::fmt::h44d7f217ec8c08a4
   3:     0x7ffc412b694b - std::sys::common::alloc::realloc_fallback::h25dd000eefb1a25f
   4:     0x7ffc412ba2da - std::panicking::default_hook::h8d2d551f7739f430
   5:     0x7ffc412b9f40 - std::panicking::default_hook::h8d2d551f7739f430
   6:     0x7ffbf4b2f02e - rustc_driver_impl[39e757d53880b308]::describe_lints
   7:     0x7ffc412babef - std::panicking::rust_panic_with_hook::h2561aa68cd5abc10
   8:     0x7ffbf700350f - <rustc_infer[e6ccf410446393ba]::infer::opaque_types::table::OpaqueTypeStorage as core[bcfc2130cb4e43e7]::fmt::Debug>::fmt
   9:     0x7ffbf70032f9 - <rustc_infer[e6ccf410446393ba]::infer::opaque_types::table::OpaqueTypeStorage as core[bcfc2130cb4e43e7]::fmt::Debug>::fmt
  10:     0x7ffbf708c32a - <rustc_middle[298b6ec0f969779]::ty::print::pretty::ForceTrimmedGuard as core[bcfc2130cb4e43e7]::ops::drop::Drop>::drop
  11:     0x7ffbf70a1886 - rustc_middle[298b6ec0f969779]::util::bug::bug_fmt
  12:     0x7ffbf709fd3d - <rustc_middle[298b6ec0f969779]::ty::consts::int::ScalarInt as core[bcfc2130cb4e43e7]::fmt::Display>::fmt
  13:     0x7ffbf709fce4 - <rustc_middle[298b6ec0f969779]::ty::consts::int::ScalarInt as core[bcfc2130cb4e43e7]::fmt::Display>::fmt
  14:     0x7ffbf70a17e8 - rustc_middle[298b6ec0f969779]::util::bug::bug_fmt
  15:     0x7ffbf70a1765 - rustc_middle[298b6ec0f969779]::util::bug::bug_fmt
  16:     0x7ffbf2410bea - rustc_codegen_llvm[63bb3427bc0dbc23]::llvm_::set_value_name
  17:     0x7ffbf23ed1eb - <windows[45a232a25c91861c]::Windows::Win32::Security::TOKEN_SOURCE as core[bcfc2130cb4e43e7]::clone::Clone>::clone
  18:     0x7ffbf23dbf97 - <rustc_codegen_llvm[63bb3427bc0dbc23]::LlvmCodegenBackend as rustc_codegen_ssa[9281276ceab4cff9]::traits::backend::CodegenBackend>::join_codegen
  19:     0x7ffbf23a24d4 - <rustc_interface[2aa0624475714241]::queries::Linker>::link
  20:     0x7ffbf23637cf - rustc_driver_impl[39e757d53880b308]::args::arg_expand_all
  21:     0x7ffbf23589d0 - rustc_driver_impl[39e757d53880b308]::main
  22:     0x7ffbf2364d43 - rustc_driver_impl[39e757d53880b308]::args::arg_expand_all
  23:     0x7ffc412ccaac - std::sys::windows::thread::Thread::new::h911abb68de5d2aa0
  24:     0x7ffcb82326ad - BaseThreadInitThunk
  25:     0x7ffcb9cca9f8 - RtlUserThreadStart

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.70.0 (90c541806 2023-05-31) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `tracker` (bin "tracker")

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by clubby789** [comment]
Can you provide a link or an example to reproduce this issue?

**Comment by nikunjitaliya2** [comment]
> Can you provide a link or an example to reproduce this issue?

i have this problem in tauri while start tauri

**Comment by Nilstrieb** [comment]
closing as a duplicate of #109879 since this doesnt have any extra info.
