### ISSUE TITLE
Crate name found in `--extern` gets suggested verbatim on unresolved import

### ISSUE THREAD

**Issue by fmease** [rust-lang/rust#113035]
Given the code in file `user.rs` as shown below:

```rs
use a_great_crate::item;
```

rustc outputs the following when invoked via `rustc user.rs --crate-type=lib --edition=2021 --extern=a-great-crate=liba_great_crate.rlib`:

```
error[E0432]: unresolved import `a_great_crate`
 --> user.rs:1:5
  |
1 | use a_great_crate::item;
  |     ^^^^^^^^^^^^^ use of undeclared crate or module `a_great_crate`
  |
help: there is a crate or module with a similar name
  |
1 | use a-great-crate::item;
  |     ~~~~~~~~~~~~~

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
```

While ideally, in this specific case it should either suggest nothing of if feasible suggest changing the `--extern` flag to `--extern=a_great_crate=liba_great_crate.rlib` (the latter is probably <kbd>P-low</kbd>). I did actually get confused by the suggestion when I originally faced it.

In fact, rustc suggests whatever garbage you put in the flag (e.g. on `rustc … '--extern=a&-gre?t#crate=xxx'`). In these cases it shouldn't consider the name at all (I realize though that this might be a case of *garbage in, garbage out*).

@rustbot label T-compiler A-diagnostics A-suggestion-diagnostics D-invalid-suggestion

**Comment by est31** [comment]
Rustc could in fact issue an error if an invalid identifier is passed as extern name, because there is no way this identifier can be used by the program anyways (outside of the `force` option on `--extern` added by #109421 there is no use case). The only issue with that is that it's going to be a breaking change so needs to be phased in gradually. Alternatively, one could just issue a warning lint.

**Comment by fmease** [comment]
Sounds even better! For some reason that didn't come to my mind when opening this issue

**Comment by est31** [comment]
I've filed an [MCP](https://github.com/rust-lang/compiler-team/issues/650) ([zulip](https://rust-lang.zulipchat.com/#narrow/stream/233931-xxx/topic/Disallow.20non-identifier-valid.20--extern.20cr.E2.80.A6.20compiler-team.23650)).

**Comment by est31** [comment]
MCP is accepted now. Now, one could file a pull request. It should be pretty simple.

**Comment by est31** [comment]
A low-level check would be to use [rustc_lexer::is_ident](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_lexer/fn.is_ident.html). Of course, if you have any better ideas, write me.

**Comment by fmease** [comment]
I'm sorry for not getting back to you. There's [`validate_crate_name`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_session/output/fn.validate_crate_name.html) which I plan on using if possible. Hoping to send a PR soon-ish, couldn't be as active in the project in the last few weeks as I wanted.

**Comment by est31** [comment]
@fmease no pressure! I'm in a similar situation in fact. Thanks for the heads up. Yeah, `validate_crate_name` looks like a good candidate, definitely worth to explore it. I think in addition the `is_ident` check would still help, as `validate_crate_name` does not reject names starting with numbers. But we can discuss details when you send the PR.
