### ISSUE TITLE
explain what an item is when invalid code is placed at the module-level

### ISSUE THREAD

**Issue by dawnofmidnight** [rust-lang/rust#113110]
Right now, it can be somewhat confusing what an item is when one gets an error like the one below. Most people who see this error likely don't know enough about Rust to know what an item is, making it fairly unhelpful. The `let` example does have a better error (although notably not for `let mut`), but that's only one particular case.

### Code

```Rust
5
```

### Current output

```
error: expected item, found `5`
 --> src/lib.rs:1:1
  |
1 | 5
  | ^ expected item
```

### Desired output

```
error: expected item, found `5`
 --> src/main.rs:1:1
  |
1 | 5
  | ^ expected item
  | 
  | help: items are things that can appear in a module. for example:
  |     - global variables: `const`, `static`
  |     - types and traits: `struct`, `enum`, `trait`,
  |     - functions: `fn`, `async fn`
  |     - implementations: `impl`
  |     - module definitions and uses: `mod`, `use`
  | 
  | for a full list of possible items see https://doc.rust-lang.org/reference/items.html.
```

The above "desired output" is not an exhaustive list. In particular, it doesn't include macros which expand to items, attributes, doc comments, `unsafe`, `extern`, and a number of other potentially relevant things. I'm not sure just how exhaustive this list should be, as it's a long one and preferably shouldn't overwhelm the reader.

Another consideration is whether a list is useful at all. There are a lot of things, and especially if one is making a mistake like this, it is entirely possible that they would not know what many of the things on this list are. A link to the reference is included here, but again, the reference isn't exactly an introductory resource that one reads to learn the language.

### Other cases

```Rust
error: expected item, found keyword `let`
 --> src/lib.rs:1:1
  |
1 | let x = 5;
  | ^^^ consider using `const` or `static` instead of `let` for global variables
```

### Anything else?

Other similar issues:

- #61764: This issue is relevant, but particularly for let bindings.
- #92615: This is also relevant, and the title is somewhat more general, but the description focuses on let bindings again, hence why a new issue was created.

**Comment by konnorandrews** [comment]
```rs
error: expected item, found `5`
 --> src/main.rs:1:1
  |
1 | 5
  | ^ expected item
  | 
  | help: For example, the following can appear here, at the root of a module:
  |     - global variables: `const`, `static`
  |     - types and traits: `struct`, `enum`, `trait`
  |     - functions: `fn`, `async fn`
  |     - implementations: `impl`
  |     - module definitions and uses: `mod`, `use`
  | 
  | For a full list of possible items see https://doc.rust-lang.org/reference/items.html.
```
Here is one trying to rely less on terms but still providing the same information about the context.

**Comment by sam0x17** [comment]
This is great. Originally it was suggested that we just list example items, but this doesn't help users _understand_ what the list means. My original comment was "lists don't help much if you don't know how they are generated". So it is of course better to give a concise but formally correct definition of what an item is: an item is anything that can appear in the top level of a module.

Another benefit I see is that a lot of beginner rust users don't have a good concept of how modules work yet, and many don't even fully realize that each .rs file _is_ a module, and this error message could be the first hint they get that "oh, I'm in a module right now!"

**Comment by Nilstrieb** [comment]
your desired output is too verbose imo. a diagnostic like this needs to be concise enough to make sure that it doesn't take away space from other diagnostics for people who already know what am item is. maybe it could get a separate error code with a `help` explicitly linking to the error code page which could explain it in detail?

**Comment by sam0x17** [comment]
I think it could simply be "expected item, found `5`. An item is anything that can appear in the top level of a module, including [list here]."

**Comment by workingjubilee** [comment]
These suggestions overcalibrate on "improving" the current diagnostic, but the current diagnostic is bad, as it merely states "what is wrong?", even with an improvement. I believe this would be improved much more by focusing on the goal instead.

Either the user needs to either correct a stray typo, OR they need to separate from a mental model carried over from languages which allow expressions at the top level. These lead to two very different suggestions. In one case, saying anything but "delete this?" is noise. In the other case, we don't necessarily care to explain what an "item" is, because we _actually_ want to get the user to put their code inside a const, static, or fn.

**Comment by gurry** [comment]
How about providing just the link for brevity: 
```
error: expected item, found `5`
 --> src/main.rs:1:1
  |
1 | 5
  | ^ expected item
  | 
  | help: items are things that can appear at the root of a module. 
  | For a full list of items see https://doc.rust-lang.org/reference/items.html.
```

**Comment by workingjubilee** [comment]
A link seems much more reasonable, yes.

**Comment by gurry** [comment]
> How about providing just the link for brevity:
> 
> ```
> error: expected item, found `5`
>  --> src/main.rs:1:1
>   |
> 1 | 5
>   | ^ expected item
>   | 
>   | help: items are things that can appear at the root of a module. 
>   | For a full list of items see https://doc.rust-lang.org/reference/items.html.
> ```

I've opened a PR #115473 implementing this. Please take a look everyone.
