### ISSUE TITLE
source links in std are not relative

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#113101]
They all target `doc.rust-lang.org/nightly`, which isn't great.

**Comment by GuillaumeGomez** [comment]
Turns out it's because when you do `doc std`, it only documents `std` and none of its dependencies.

**Comment by ChrisDenton** [comment]
Does `doc library` fix that?

**Comment by GuillaumeGomez** [comment]
Yes. But why was it changed in the first place?

**Comment by GuillaumeGomez** [comment]
Found the commit: https://github.com/rust-lang/rust/commit/c28ee603c8ddc2f171bee4ba02336fb6a3479010
