### ISSUE TITLE
rlibs change when modifying comments, even after stripped

### ISSUE THREAD

**Issue by erickt** [rust-lang/rust#113136]
I work on Fuchsia, which uses GN and ninja as our build system for our operating system. Our build is set up such that we treat tests in libraries as a separate build target from non-test `.rlib` libraries. One nice thing about ninja is that it can prune downstream targets from being rebuilt if the outputs of a parent target do not change.

Unfortunately we're not able to take advantage of this optimization in many cases. It seems minor changes can cause rlib files to change. The simplest example of this is that we can modify a `//` comment and get a different rlib, even if we remove debuginfo  with `debug = "false"`, `split-debuginfo = "packed"`, or `strip = "symbols"`.

Here's a simple example with `rustc 1.72.0-nightly (36fb58e43 2023-06-26)` on linux:

Cargo.toml:

```toml
[package]
name = "foo"
version = "0.1.0"
authors = ["Erick Tryzelaar <etryzelaar@google.com>"]
edition = "2021"

[profile.release]
debug = false
split-debuginfo = "packed"
strip = "symbols"
```

```rust
// hello
pub fn hello() {}
```

When built, it produces this file:

```
% cargo build --release
% shasum target/release/libfoo.rlib
0a0f76f3ec8c9a2c930c768b3cd08e841affbf97  target/release/libfoo.rlib
% ls -l target/release/libfoo.rlib
-rw-r----- 2 etryzelaar primarygroup 4098 Jun 28 19:09 target/release/libfoo.rlib
```

If the comment is changed from `hello` to `jello` with:

```rust
// jello
pub fn hello() {}
```

Then we get different contents:

```
% cargo build --release
% shasum target/release/libfoo.rlib
0a8a7ca5b08e002a090401b7350cdef2643c93ac  target/release/libfoo.rlib
% ls -l target/release/libfoo.rlib
-rw-r----- 2 etryzelaar primarygroup 4098 Jun 28 19:11 target/release/libfoo.rlib
```

We've got a [tool for comparing binary files](https://cs.opensource.google/fuchsia/fuchsia/+/main:build/rbe/detail-diff.sh), which points out these differences:

```
% ~/fuchsia/build/rbe/detail-diff.sh target-hello/release/libfoo.rlib target-jello/release/libfoo.rlib
objdump-diff (first 25 lines):
diff -u <(../fuchsia/prebuilt/third_party/clang/linux-x64/bin/llvm-objdump --full-contents target-hello/release/libfoo.rlib) <(../fuchsia/prebuilt/third_party/clang/linux-x64/bin/llvm-objdump --full-contents target-jello/release/libfoo.rlib)
--- target-hello/release/libfoo.rlib.llvm-objdump.local	2023-06-28 19:18:05.470115470 +0000
+++ target-hello/release/libfoo.rlib.llvm-objdump.remote	2023-06-28 19:18:05.478115455 +0000
@@ -128,8 +128,8 @@
  0790 ffff0000 302f7573 722f6c6f 63616c2f  ....0/usr/local/
  07a0 676f6f67 6c652f68 6f6d652f 65747279  google/home/etry
  07b0 7a656c61 61722f66 6f6f2f73 72632f6c  zelaar/foo/src/l
- 07c0 69622e72 73c10020 ce2eecd1 4ebd6c65  ib.rs.. ....N.le
- 07d0 d70b92e0 70bf2a49 00000000 00000000  ....p.*I........
+ 07c0 69622e72 73c10020 56c9a6a4 5cd468f0  ib.rs.. V...\.h.
+ 07d0 66124daa a02c612c 00000000 00000000  f.M..,a,........
  07e0 00000000 00000000 001b0201 00090000  ................
  07f0 16bb94bd 5ae78b93 9f31b209 643a15d2  ....Z....1..d:..
  0800 00009207 00000018 7838365f 36342d75  ........x86_64-u

readelf-diff (first 25 lines):
diff -u <(../fuchsia/prebuilt/third_party/clang/linux-x64/bin/llvm-readelf -a target-hello/release/libfoo.rlib) <(../fuchsia/prebuilt/third_party/clang/linux-x64/bin/llvm-readelf -a target-jello/release/libfoo.rlib)

dwarfdump-diff (first 25 lines):
diff -u <(../fuchsia/prebuilt/third_party/clang/linux-x64/bin/llvm-dwarfdump -a target-hello/release/libfoo.rlib) <(../fuchsia/prebuilt/third_party/clang/linux-x64/bin/llvm-dwarfdump -a target-jello/release/libfoo.rlib)

nm-diff (first 25 lines):
target-hello/release/libfoo.rlib:lib.rmeta: no symbols
target-hello/release/libfoo.rlib:lib.rmeta: no symbols
diff -u <(../fuchsia/prebuilt/third_party/clang/linux-x64/bin/llvm-nm target-hello/release/libfoo.rlib) <(../fuchsia/prebuilt/third_party/clang/linux-x64/bin/llvm-nm target-jello/release/libfoo.rlib)

strings-diff (first 25 lines):
diff -u <(strings target-hello/release/libfoo.rlib) <(strings target-jello/release/libfoo.rlib)
```

This also seems to be the case when modifying code that should be compiled out, such as `#[test]` functions. For example:

```rust
#[test]
fn test() {
    let _ = "hello";
}
```

and:

```rust
#[test]
fn test() {
    let _ = "jello";
}
```

These produce different `.rlib` files. `detail-diff.sh` finds these differences:

```
objdump-diff (first 25 lines):
diff -u <(../fuchsia/prebuilt/third_party/clang/linux-x64/bin/llvm-objdump --full-contents target-hello/release/libfoo.rlib) <(../fuchsia/prebuilt/third_party/clang/linux-x64/bin/llvm-objdump --full-contents target-jello/release/libfoo.rlib)
--- target-hello/release/libfoo.rlib.llvm-objdump.local	2023-06-28 19:32:00.776593094 +0000
+++ target-hello/release/libfoo.rlib.llvm-objdump.remote	2023-06-28 19:32:00.780593087 +0000
@@ -109,7 +109,7 @@
  0660 722f6c6f 63616c2f 676f6f67 6c652f68  r/local/google/h
  0670 6f6d652f 65747279 7a656c61 61722f66  ome/etryzelaar/f
  0680 6f6f2f73 72632f6c 69622e72 73c10020  oo/src/lib.rs..
- 0690 dcf60446 36620cc7 fc10fd8d 301a1519  ...F6b......0...
+ 0690 8bcbe7f6 ee4044a5 cf14ce0a 528dfb78  .....@D.....R..x
  06a0 00000000 00000000 00000000 00000000  ................
  06b0 002b0401 00080c15 000016bb 94bd5ae7  .+............Z.
  06c0 8b939f31 b209643a 15d20000 5a060000  ...1..d:....Z...

readelf-diff (first 25 lines):
diff -u <(../fuchsia/prebuilt/third_party/clang/linux-x64/bin/llvm-readelf -a target-hello/release/libfoo.rlib) <(../fuchsia/prebuilt/third_party/clang/linux-x64/bin/llvm-readelf -a target-jello/release/libfoo.rlib)

dwarfdump-diff (first 25 lines):
diff -u <(../fuchsia/prebuilt/third_party/clang/linux-x64/bin/llvm-dwarfdump -a target-hello/release/libfoo.rlib) <(../fuchsia/prebuilt/third_party/clang/linux-x64/bin/llvm-dwarfdump -a target-jello/release/libfoo.rlib)

nm-diff (first 25 lines):
target-hello/release/libfoo.rlib:lib.rmeta: no symbols
target-hello/release/libfoo.rlib:lib.rmeta: no symbols
diff -u <(../fuchsia/prebuilt/third_party/clang/linux-x64/bin/llvm-nm target-hello/release/libfoo.rlib) <(../fuchsia/prebuilt/third_party/clang/linux-x64/bin/llvm-nm target-jello/release/libfoo.rlib)

strings-diff (first 25 lines):
diff -u <(strings target-hello/release/libfoo.rlib) <(strings target-jello/release/libfoo.rlib)
```

While this doesn't change the behavior of any of our code, figuring out a way to make these two files be the same could really speed up our builds, and I'm guessing other build systems that prune work based off content, like bazel (I don't think it'd help cargo though, since I don't believe it prunes work based off content).

### Meta

`rustc --version --verbose`:
```
rustc 1.72.0-nightly (36fb58e43 2023-06-26)
```

**Comment by jyn514** [comment]
hmm. i am not aware of toolcji

**Comment by jyn514** [comment]
hmm. i am not aware of tooling for comparing the contents of .rlib files. i think at one point @bjorn3 had a script for the comparing the metadata? not sure where to find it, though.

**Comment by bjorn3** [comment]
It is expected that rlibs change on whitespace only changes. The crate metadata contains source offsets for basically everything. In addition the crate hash which is used to determine if a dependency was changed and thus the current crate needs recompilation has the full source code as one of it's inputs. And finally panic messages contain line and column numbers even with debuginfo stripped.

**Comment by bjorn3** [comment]
> hmm. i am not aware of tooling for comparing the contents of .rlib files. i think at one point @bjorn3 had a script for the comparing the metadata? not sure where to find it, though.

https://github.com/bjorn3/rust_read_rlib It is pretty outdated though.

**Comment by saethlin** [comment]
The rlib change that is observed here is the md5 hash that we encode for all source files. Source files are "normalized" before they are hashed, but all that does is remove the BOM if one exists and turn Windows line endings into Unix line endings.

I figured this out by hacking up `FileEncoder` so that it panics right after it has written the bytes in question in the issue description. Not pretty, but it worked.

I don't think there's anything else to do here? This is not a bug according to rustc.

**Comment by erickt** [comment]
Yeah, thanks everyone for digging into this. I'll close the ticket.
