### ISSUE TITLE
Rust compiler & cargo issues with installation outside of default path

### ISSUE THREAD

**Issue by JojoFR1** [rust-lang/rust#113193]
I'm on **Windows 11**, I don't have administration privilege and I'm not using the default path for space reason.

When I was installing the latest stable Rust compiler, I wanted it to be installed in the `D:` Drive instead of the default path. I changed the value of `RUSTUP_HOME` and `CARHO_HOME` to a custom folder in the `D:` Drive but when I try installing the compiler it output an error of linking:

```
error: could not create link from 'D:\Tools\rust\bin\rustup.exe' to 'D:\Tools\rust\bin\rust-analyzer.exe'
```

In the folder their is only a `bin/rustup.exe`.

The only solution was to use the default value, wait for it to install then move it but it's not really practical and it's slow.

---

When using my method to install the compiler, I tried executing this command `rustup update` it tell me warnings and an error, then deleting `rustc.exe` which render Rust compiler unusable:

```
warning: tool `rust-analyzer` is already installed, remove it from `D:\Tools\rust\bin`, then run `rustup update` to have rustup manage this tool.
warning: tool `rustfmt` is already installed, remove it from `D:\Tools\rust\bin`, then run `rustup update` to have rustup manage this tool.
warning: tool `cargo-fmt` is already installed, remove it from `D:\Tools\rust\bin`, then run `rustup update` to have rustup manage this tool.
error: could not create link from 'D:\Tools\rust\bin\rustup.exe' to 'D:\Tools\rust\bin\rustc.exe'
```

---

This also seem to cause problem with cargo because when trying to install a dependency it always tell me an error occurred (I don't have a specific exemple, I will reinstall everything to show it later).

**Comment by ChrisDenton** [comment]
What filesystem is your `D` drive? It sounds like it might be fat32, which is currently unsupported.

Btw, I think this issue should be moved to the [rustup repository](https://github.com/rust-lang/rustup) as it's to do with a rustup managed toolchain.

**Comment by JojoFR1** [comment]
It's an exfat

I will move the issue, thanks
