### ISSUE TITLE
CI podman detection is not fully reliable

### ISSUE THREAD

**Issue by Nilstrieb** [rust-lang/rust#113129]
podman is (by design) not fully compatible with docker when it comes to user permissions. Therefore, `./src/ci/docker/run.sh` needs to look behind the `docker` curtain to figure out whether it's actually podman and opt out of the user isolation.

https://github.com/rust-lang/rust/blob/eb76764ea412b36f670564f5d58c317cec8fa496/src/ci/docker/run.sh#L219-L226

With ubuntus docker podman compat package this works fine, because there `docker --version` prints something containing podman. But if you symlink `docker` to `podman` (something NixOS does if you set up docker-podman compat) then `docker --version` actually prints `docker version 4.5.0`. Podman outsmarts CI's detection.

I'm not sure about the ideal way to fix this, but `docker system --help` contains "manage podman" for me, so do whatever you want with this information.

**Comment by Nilstrieb** [comment]
cc @cuviper who added this code

**Comment by cuviper** [comment]
On Fedora, `podman-docker`'s `/usr/bin/docker` is a quick shell script to `exec /usr/bin/podman`. So that process will have a podman `argv[0]`, whereas a symlink will still look like docker. I'm guessing that's what `--version` is echoing.

Maybe `docker version` is a better choice? That gives me:

```
$ docker version
Client:       Podman Engine
Version:      4.5.1
API Version:  4.5.1
Go Version:   go1.20.4
Built:        Fri May 26 10:58:48 2023
OS/Arch:      linux/amd64
```
