### ISSUE TITLE
link to the rustc-dev-guide on cycle errors

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#113184]
right now, new contributors to the compiler can be easily confused by the cycle error - queries are not common in other production compilers (that i know of) and i think it would make it a lot easier to understand if we linked to the docs: https://rustc-dev-guide.rust-lang.org/overview.html#queries / https://rustc-dev-guide.rust-lang.org/query.html

the error reporting has changed a bit since i last looked at it, but i think https://github.com/rust-lang/rust/blob/a7838d8bd7e7e1e25a843de74340284832c5e3ac/compiler/rustc_query_system/src/error.rs#L46-L60 is the right place.

cc @jieyouxu

**Comment by zaneduffield** [comment]
Hi @jyn514, is it normal to link to developer docs in compiler error reporting? Maybe it would be suitable to have this information in the output of `rustc --explain E0391`? The current output only shows an example of a cyclic trait dependency.

**Comment by jyn514** [comment]
@zaneduffield the cycle error is unlike other errors in that it's much more likely to trigger it by accident while working on the compiler itself.

i don't mind adding info to --explain but i think we should do that in addition to an inline link, not instead of.

**Comment by RickleAndMortimer** [comment]
Hey everyone, I have a patch that adds the links in the --explain error code and compiler error. Is it alright if I submit a PR or are we still deciding on a approach currently?

**Comment by jyn514** [comment]
@RickleAndMortimer a PR would be great, thanks!
