### ISSUE TITLE
Implementation of From on Rc incorrectly refers to Arc

### ISSUE THREAD

**Issue by claytonwramsey** [rust-lang/rust#113131]
### Location

The documentation of [`impl From<CString> for Rc<CStr>`](https://doc.rust-lang.org/std/rc/struct.Rc.html#impl-From%3CCString%3E-for-Rc%3CCStr%3E) writes the following:

> Converts a [CString](https://doc.rust-lang.org/std/ffi/struct.CString.html) into an [Rc](https://doc.rust-lang.org/std/rc/struct.Rc.html)<[CStr](https://doc.rust-lang.org/std/ffi/struct.CStr.html)> by moving the [CString](https://doc.rust-lang.org/std/ffi/struct.CString.html) data into a new [Arc](https://doc.rust-lang.org/std/sync/struct.Arc.html) buffer.

### Summary

A quick peek at the implementation of `From<CString> for Rc<CStr` shows that it uses an `Rc` as the backing allocation, not an `Arc`. My guess is that this documentation was copy-pasted from the implementation on `Arc` and never edited.

The correct revision (if I understand the implementation correctly) would be to substitute `Arc` for `Rc` in the documentation.

**Comment by tgross35** [comment]
A PR would be welcome if you're interested!

**Comment by claytonwramsey** [comment]
Sure. I’m on vacation right now, but will get on it when I get back :).
