### ISSUE TITLE
bootstrap: `rustc-args` is only passed to compiletest, not unit tests

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#113178]
https://github.com/rust-lang/rust/blob/5122e88b35dbf4e959d6ca2cfca4c5ed0a105203/src/bootstrap/test.rs#L1586

cc https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Running.20tests.20in.20debug.20mode.20with.20debug.20symbols.3F/near/361025470

We should either pass this flag consistently or rip it out entirely; having it work only sometimes makes it an attractive nuisance.

### Meta

HEAD is 330727467b8fdf2c43b95095a0efae7012c4f83b

**Comment by jyn514** [comment]
we should at least set them in `prepare_cargo_test`, probably through RUSTFLAGS since cargo doesn't allow setting them directly? https://github.com/rust-lang/rust/blob/5122e88b35dbf4e959d6ca2cfca4c5ed0a105203/src/bootstrap/test.rs#L2247

**Comment by chenyukang** [comment]
seems we have handled rustc-args for `compiletest` at here?

https://github.com/rust-lang/rust/blob/5122e88b35dbf4e959d6ca2cfca4c5ed0a105203/src/bootstrap/test.rs#L1595-L1607
