### ISSUE TITLE
rustc 1.70 silently removes function 

### ISSUE THREAD

**Issue by tommythorn** [rust-lang/rust#113268]
(This has been reproduced on both x86 and RISC-V)

I prepared https://github.com/tommythorn/rustc-codegen-issue to complain about the redundant stores, but it was suggested to me that using `[u64; 65]` instead would fix it.  Instead I got no code at all in the output!?

```rust
pub struct State {
    b: [u64; 65],
    c: u64,
    d: u64,
    e: u64,
}

impl State {
    pub fn compute(&mut self, n: usize) -> u64 {
        let mut f = 0;

        for _ in 0..n {
            let p = self.d.trailing_zeros() as usize;
            self.d &= self.d - 1;
            f |= 1 << p;
            self.c -= 1 << p;
            self.e += self.b[p];
        }

        f
    }
}

#[no_mangle]
pub extern "C" fn interesting(s: &mut State, n: usize) -> u64 {
    s.compute(n)
}
```

I expected to see this happen: when I run `rustc -O --crate-type lib src/lib.rs;objdump -d liblib.rlib`
I expect to find an "interesting" function in the resulting `liblib.rlib` that I can link with, but I only get
```
0000000000000000 <_ZN3lib5State7compute17h1250dcbc58a55f14E>:
   0:   48 85 f6                test   %rsi,%rsi
   3:   74 38                   je     3d <_ZN3lib5State7compute17h1250dcbc58a55f14E+0x3d>
   5:   41 57                   push   %r15
...
```

However, if I change the `b: [u64; 65],` back to `b: [u64; 64],` I get
```
Disassembly of section .text.interesting:

0000000000000000 <interesting>:
   0:   50                      push   %rax
   1:   48 85 f6                test   %rsi,%rsi
...
```

as expected.

### Meta

Nightly reproduces the bug as well.

`rustc --version --verbose`:
```
rustc --version --verbose
rustc 1.70.0 (90c541806 2023-05-31)
binary: rustc
commit-hash: 90c541806f23a127002de5b4038be731ba1458ca
commit-date: 2023-05-31
host: riscv64gc-unknown-linux-gnu
release: 1.70.0
LLVM version: 16.0.2

```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by Jules-Bertholet** [comment]
I don't believe the `.rlib` format is stable/documented?

**Comment by tommythorn** [comment]
Thanks, changing it to `--crate-type lib` and looking at `liblib.a` makes things sane again.

Not A Bug
