### ISSUE TITLE
Unable to use Command::spawn with unallocated console

### ISSUE THREAD

**Issue by ktwrd** [rust-lang/rust#113277]
I'm currently trying to run an executable on Windows with Rust Nightly `1.72.0-nightly (5b377cece 2023-06-30)`. It works when the console is allocated with `winapi::um::wincon::AttachConsole` but whenever the console has been unallocated with `winapi::um::wincon::FreeConsole` it's unable to spawn new processes. Here is the following code that I'm using to spawn the process.

```rust
use std::process::Command;

fn test() {
    // this is called somewhere else in the program.
    winapi::um::wincon::FreeConsole();

    let current_pwd: String = std::env::current_dir().unwrap().into_os_string().into_string().unwrap();
    println!("Using pwd {loc}");
    let cmd_pre = Command::new("test.exe".to_string()).current_dir(current_pwd).spawn();
    if let Err(e) = cmd_pre
	{
        println!("Failed to launch embedded application. {:#?}", e);
        return;
    }

    let mut cmd_unwr = cmd_pre.unwrap();
    println!("PID {}", cmd_unwr.id());

    if let Err(e) = cmd_unwr.wait() {
        println!("Failed to run embedded application, exited with code {:#?}", e);
        return;
    }
    println!("Done!");
}
```

When I try and run the process, this is the following error I get;
```
Os {
    code: 50,
    kind: Uncategorized,
    message: "The request is not supported.",
}
```

**Comment by ChrisDenton** [comment]
Hm, when freeing a console stdin, stdout and stderr are not reset to null. So they may contain either invalid or reused handle values. [`Command::stdin`](https://doc.rust-lang.org/std/process/struct.Command.html#method.stdin) defaults to "inherit" so it tries to use these handles and fails.

I'd suggest using [`SetStdHandle`](https://learn.microsoft.com/en-us/windows/console/setstdhandle) to set all the freed handles to null and see if that fixes it.

**Comment by ktwrd** [comment]
I'll see if that works tomorrow since I've finished work for the day (in UTC+08:00 timezone)

**Comment by workingjubilee** [comment]
@ChrisDenton Is there any chance we can anticipate this via checking the stdio handles? I don't think _handling_ it would be automatically desirable, but it might allow returning more sophisticated errors.

**Comment by ChrisDenton** [comment]
Not really. We could add extra context to the error message but that might end up being much worse if we guess the wrong reason for it. More generally speaking, a fundamental assumption of the standard library is that handles aren't closed out from underneath it which is why doing so is considered `unsafe` (see also `File`).

**Comment by ktwrd** [comment]
I set the standard input with the following code and it seems to have worked with no errors;
```rust
use windows::Win32::{Foundation::HANDLE, System::Console};
use windows::Win32::System::Console::STD_INPUT_HANDLE;
pub fn hide_console_window() {
    unsafe {
        winapi::um::wincon::FreeConsole();
        let null_ptr = std::ptr::null_mut() as *const u8 as isize;
        Console::SetStdHandle(STD_INPUT_HANDLE, HANDLE(null_ptr));
    }
}
```

**Comment by ChrisDenton** [comment]
Great!
