### ISSUE TITLE
regression: no rules expected the token `:`

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#113236]
* https://crater-reports.s3.amazonaws.com/beta-1.71-4/beta-2023-06-25/gh/allan-silva.pratical-rust-macro/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.71-4/beta-2023-06-25/reg/preftool-dirs-0.2.0/log.txt

```
[INFO] [stdout] error: no rules expected the token `:`
[INFO] [stdout]   --> src/main.rs:6:57
[INFO] [stdout]    |
[INFO] [stdout] 6  |             const MEM_SIZE: usize = count_expr!($($inits:expr),+);
[INFO] [stdout]    |                                                         ^ no rules expected this token in macro call
[INFO] [stdout] ...
[INFO] [stdout] 70 | macro_rules! count_expr {
[INFO] [stdout]    | ----------------------- when calling this macro
[INFO] [stdout] ...
[INFO] [stdout] 77 |     let fib = recurrence![a[n]: u64 = 0, 1; a[n-1] + a[n-2]];
[INFO] [stdout]    |               ---------------------------------------------- in this macro invocation
[INFO] [stdout]    |
[INFO] [stdout] note: while trying to match meta-variable `$e:expr`
[INFO] [stdout]   --> src/main.rs:72:6
[INFO] [stdout]    |
[INFO] [stdout] 72 |     ($e:expr) => (1);
[INFO] [stdout]    |      ^^^^^^^
[INFO] [stdout]    = note: this error originates in the macro `recurrence` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by Nilstrieb** [comment]
They messed up their macro and are accidentally passing a type ascription to the `count_expr` macro. Looks like the type ascription is deleted before it could be feature gated (looks like type ascription was using the old style compat-hazard feature gating?). There's nothing to do here, this should have never compiled on stable.
The easy fix is
```diff
- [INFO] [stdout] 6  |             const MEM_SIZE: usize = count_expr!($($inits:expr),+);
+ [INFO] [stdout] 6  |             const MEM_SIZE: usize = count_expr!($($inits),+);
```

**Comment by Nilstrieb** [comment]
`preftool-dirs` looks abandoned and the repo link is dead, it has very few downloads. practical-rust-macro looks like a learning repository (that also hits `semicolon_in_expressions_from_macros` :D), so nothing important.

**Comment by apiraino** [comment]
can we perhaps close this one? cc @Mark-Simulacrum (ref. previous comments)
