### ISSUE TITLE
Probably a borrow issue

### ISSUE THREAD

**Issue by Kepler-22b** [rust-lang/rust#113267]
```rust

struct Parser {
   //...
    v_idx   : HashMap<i64, HashSet<u64>>
  //...
}

impl Parser {

#[inline]
    fn safe_v_idx(&mut self, lit : &i64) -> &mut HashSet<u64> {

        if let Some(set) =
            self.v_idx.get_mut(lit)
        {
            return set;
        }

        self.v_idx.insert(*lit, HashSet::new());

        // Do something else here
        
        panic!("Unknown error");
    }

}
```

I expected to see this happen:

In line "32" the first mutable borrow is returned if "get_mut()" doesn't fail.
If the borrow fails, the following line should proceed as though I hadn't ever tried to 
call v_idx.get_mut().

I'm new here, so perhaps I am wrong.

Instead, this happened:

error[E0499]: cannot borrow `self.v_idx` as mutable more than once at a time
  --> src/parser.rs:38:9
   |
29 |     fn safe_v_idx(&mut self, lit : &i64) -> &mut HashSet<u64> {
   |                   - let's call the lifetime of this reference `'1`
...
32 |             self.v_idx.get_mut(lit)
   |             ----------------------- first mutable borrow occurs here
33 |         {
34 |             return set;
   |                    --- returning this value requires that `self.v_idx` is borrowed for `'1`
...
38 |         self.v_idx.insert(*lit, HashSet::new());
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ second mutable borrow occurs here

rustc 1.70.0 (90c541806 2023-05-31)
binary: rustc
commit-hash: 90c541806f23a127002de5b4038be731ba1458ca
commit-date: 2023-05-31
host: x86_64-unknown-linux-gnu
release: 1.70.0
LLVM version: 16.0.2

**Comment by compiler-errors** [comment]
This is one of the borrow checker limitations that should be fixed by polonius.

**Comment by Kepler-22b** [comment]
Okay, glad to know it is being fixed
