### ISSUE TITLE
Put `needs-triage` label on every new issue

### ISSUE THREAD

**Issue by Nilstrieb** [rust-lang/rust#113261]
The GitHub issue for https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/make.20untriaged.20issues.20explicit so I can nominate it for the teams.

I've noticed that we have many issues inside rust-lang/rust that are completely untriaged with no interactivity. I don't believe that this is due to lack of time, but simply due to lack of organization. I propose that every new issue gets the `needs-triage` label. Then, members can see the issues with that label and triage them. That includes labeling the issues and maybe replying to them if there's a specific request, for example answering a question or asking for a reproduction. Ideally triage is done by someone with knowledge in the issue's area but that's of course not a hard requirement. The person can then just remove the label. The label can also be settable via rustbot so anyone can do this.

I'm confident that we'd have enough time to triage all issues with that labeling system (I would certainly participate, as I've been doing for a while now).

I'm not entirely sure about the best process for deciding this. The reception on Zulip was positive, but I want to make sure that everyone here is on aware and on board. Given the shared team ownership of this repo I'm going to nominate this issue for the three major teams, compiler, libs and rustdoc (rustdoc doesn't have a nomination label apparently, so I'll just @rust-lang/rustdoc here :D) . If they all agree with the change, we can implement it (by using the triagebot feature I added: https://github.com/rust-lang/triagebot/pull/1708).

**Comment by jyn514** [comment]
cc @rust-lang/bootstrap

**Comment by m-ou-se** [comment]
Sounds good. Libs team is on board.

**Comment by GuillaumeGomez** [comment]
:+1:

**Comment by apiraino** [comment]
Discussed in T-compiler meeting on Zulip [notes](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202023-07-06/near/372921575)): looks like a really good idea.

@rustbot label -I-compiler-nominated

**Comment by Nilstrieb** [comment]
it's working! #113486

**Comment by fmease** [comment]
I think we shouldn't add <kbd>needs-triage</kbd> if it's a tracking issue. What do you think? I think this can be accomplished by

```diff
  [autolabel."needs-triage"]
  new_issue = true
+ exclude_labels = [
+     "C-tracking-issue",
+ ]
```

**Comment by Nilstrieb** [comment]
sounds good
