### ISSUE TITLE
regression: c"..." are experimental

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#113235]
Not clear to me whether this is expected -- I don't see much in the way of commentary on the RFC, and I thought we had reserved these literals previously, but perhaps that reservation was incomplete?

https://crater-reports.s3.amazonaws.com/beta-1.71-4/beta-2023-06-25/gh/noc7c9.pyfection/log.txt

**Comment by fmease** [comment]
`c"…"` inside macro calls (with macro matches like `c$e:expr`) should definitely continue to compile in editions 2015 and 2018. Those prefixes are only reserved in edition 2021 and onward.

Reproducer compiles successfully on stable in editions 2015 and 2018 but fails to compile on beta and nightly:

```rs
macro_rules! m { (c$e:expr) => {}; }

fn main() { m!(c"hello"); }
```

```
error: no rules expected the token `c"hello"`
 --> src/main.rs:3:16
  |
1 | macro_rules! m { (c$e:expr) => {}; }
  | -------------- when calling this macro
2 |
3 | fn main() { m!(c"hello"); }
  |                ^^^^^^^^ no rules expected this token in macro call
  |
note: while trying to match `c`
 --> src/main.rs:1:19
  |
1 | macro_rules! m { (c$e:expr) => {}; }
  |                   ^

error[[E0658]](https://doc.rust-lang.org/beta/error_codes/E0658.html): `c".."` literals are experimental
 --> src/main.rs:3:16
  |
3 | fn main() { m!(c"hello"); }
  |                ^^^^^^^^
  |
  = note: [see issue #105723 <https://github.com/rust-lang/rust/issues/105723>](https://github.com/rust-lang/rust/issues/105723) for more information
```

@rustbot label S-has-mcve

**Comment by fmease** [comment]
This would be easy to fix if we had access to the edition in `rustc_lexer` but I don't know if it's acceptable to pass it to `Cursor`.
Alternatively, we can unravel `CStr` and `CStrRaw` literals into two tokens (`Str` `StrRaw` and `Ident`) after the fact in `rustc_parse::lexer` where we have access to the edition, although that's a bit messier I guess.

**Comment by hameerabbasi** [comment]
Assigning P-medium since this is only a warning, and only valid for older editions of Rust.

@rustbot label -I-prioritize +P-medium

**Comment by fmease** [comment]
> since this is only a warning

@hameerabbasi It's not a warning but a hard error. [noc7c9/pyfection](github.com/noc7c9/pyfection) no longer compiles due to this bug. rustc lexes the crate differently than before.

**Comment by hameerabbasi** [comment]
@fmease Do you recommend `P-high`? Feel free to change the label if so.

**Comment by fmease** [comment]
I guess the priority is fine, I just wanted to set the record straight :)

**Comment by fmease** [comment]
Without doing a bisection, I can tell you that this regressed in #108801 when `rustc_lexer/src/lib.rs` was modified.

**Comment by compiler-errors** [comment]
Let's at least revert the lexer changes until @fee1-dead or someone else can fix this in a way that's compatible with the pre-2021 editions @fmease, do you want to do that, or shall I?

**Comment by fmease** [comment]
Just reverting the lexer change & keeping everything else related to `c_str_literals`? I can do that within this hour when I find the time.

@rustbot claim

**Comment by compiler-errors** [comment]
To be clear, all the existing cstring tests would break, so you'll have to mark some of the tests as `// known-bug: ###` and open an issue tracking that functionality getting added. That'll make it so someone knows to pick it up and fix it 😸

**Comment by fmease** [comment]
Slightly unrelated, but I've noticed that the GitHub label and should be renamed from <kbd>F-c_str_literal</kbd> to  <kbd>F-c_str_literals</kbd> and its description needs to be updated, too (see https://github.com/rust-lang/rust/blob/master/compiler/rustc_feature/src/active.rs for the source of thruth).

**Comment by fmease** [comment]
This is now on beta and can be closed, right?

**Comment by nagisa** [comment]
Correct, we have an issue tracking reimplementation at https://github.com/rust-lang/rust/issues/113333
