### ISSUE TITLE
Suggest `x build library` for a custom toolchain that fails to load `core` 

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#113222]
### Code

```Rust
x build std --target x86_64-unknown-linux-gnu
cd ../example
cargo +stage1 build --target i686-unknown-linux-gnu
```

### Current output

```Shell
error[E0463]: can't find crate for `core`
  = help: consider downloading the target with `rustup target add i686-unknown-linux-gnu`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`
```

### Desired output

```Shell
error[E0463]: can't find crate for `core`
  = help: consider adding the standard library to the sysroot with `x build library --target i686-unknown-linux-gnu`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`
```

### Rationale and extra context

`rustup` doesn't manage targets and components for custom toolchains. We can detect in rustc that this is a custom toolchain by checking `env!("CFG_RELEASE_CHANNEL") == "dev"` and changing the `help` output if so.

### Anything else?

cc https://discord.com/channels/442252698964721669/1124482842051747860

**Comment by Nilstrieb** [comment]
This had to be reverted because it broke UI tests with channel=dev. #113288
