### ISSUE TITLE
perf regression between nightly 2023-06-28 and 2023-07-01

### ISSUE THREAD

**Issue by Dirbaio** [rust-lang/rust#113372]
There's some performance regression between `nightly-2023-06-28` and `nightly-2023-07-01`.

Compilation times for my company's firmware project went from **13s** on `nightly-2023-06-28` to **1m 43s** on `nightly-2023-07-01`. This is for "change a single line, then build", not for a cold build. 

The project is a single rather big crate making extensive use of async and AFIT, and TAIT through the `#[embassy_executor::task]` macro to place futures in `static`s. Unfortunately it's not open source. I also haven't been able to isolate the regression to a single bad pattern of code causing it. It seems all async code contributes to the slowness: as I remove code compilation gets faster, and it seems linearly proportional.

I've taken flamegraphs with `-Zself-profile`. The extra time is spent in `codegen_module` -> `fn_abi_of_instance` -> `deduced_param_attrs` -> `is_freeze_raw` -> `evaluate_obligation`

`nightly-2023-06-28`, 13s:  [flamegraph](https://github.com/rust-lang/rust/assets/1247578/cfa30068-6df4-416f-b5a3-e84a159ef6d6)
`nightly-2023-07-01`, 1m 43s: [flamegraph](https://github.com/rust-lang/rust/assets/1247578/a84a0c30-a18b-4f3e-8492-c6f84db3e4f3)

I do have [one open-source project](https://github.com/embassy-rs/ekv) which also seems affected by the regression, but not as egregiously. To reproduce, `cd examples/nrf; cargo build --release`.

3 attempts of "change 1 line then build":
`nightly-2023-06-28`: 2.51s 2.85s 3.51s. [flamegraph](https://github.com/rust-lang/rust/assets/1247578/9c8f5e37-9169-4c89-a703-6d43ef3062c9)
`nightly-2023-07-01`: 4.22s 4.10s 4.09s. [flamegraph](https://github.com/rust-lang/rust/assets/1247578/34d1d1fe-a403-482f-a0c5-6fbd1c582fb8)

`fn_abi_of_instance` takes 14% of the time in the new nightly, but barely none in the old one. So it seems it's the same issue. 

Also unfortunately `nightly-2023-06-29` and `nightly-2023-06-30` have an unrelated (?) bug which makes compilation fail with bogus "impl ?Sized is not a Future" errors, which is #113155 (introduced in #98867, fixed in #113165). I don't think that's the cause of the perf regression, but it prevents bisecting it (it just points me to #98867. Scripting the bisect to fail only on timeout would probably point to #113165, though I haven't tried)

**Comment by compiler-errors** [comment]
It's probably #113108.

Do you have really deeply nested futures? It's probably that.

**Comment by Dirbaio** [comment]
> Do you have really deeply nested futures?

Yes, I do.

**Comment by compiler-errors** [comment]
Even if it is #113108, I don't really know what I can do about this situation without at least being able to see some shared code. 

For the record -- that PR doesn't just introduce a regression for no good reason, it fixes *real* codegen errors that are due to the fact that we weren't actually revealing opaque types during codegen even though we should. The problem is that you've probably got extremely deep futures that were hiding behind the (accidental) type erasure of opaque types, and now that we're revealing them, we're doing more work when checking auto traits like [`Freeze`](https://github.com/rust-lang/rust/blob/e4cd1610067501fa4d347eba7b18f77137dbbf48/library/core/src/marker.rs#L873).

But that's just my conjecture for the cause of the regression.

**Comment by compiler-errors** [comment]
You may be able to mitigate this regression by introducing boxing in cases where you know that the futures are gonna be super deep, though it's sometimes kinda random where you'd have to introduce it.

**Comment by Dirbaio** [comment]
is the `ekv` repro I've linked above not big enough? I've tried to see if I can cook up some artificial example that bloats compile times more, unsuccessfully so far. I'll keep trying.

And yeah I can't Box :(

**Comment by compiler-errors** [comment]
Oh, sorry, didn't see the link. Just saw "company code" and stopped reading :sweat:

**Comment by Dirbaio** [comment]
Okay, I found a pattern of death: https://github.com/embassy-rs/ekv/commit/53918ac060f1c6bd7822c01c1806a0009b2d550f

with `nightly-2023-06-28` it builds fine in 2.5s.
with `nightly-2023-07-01` it hangs and eats all my RAM.

**Comment by compiler-errors** [comment]
Interesting. I'll look at that PR and see if there's anything that can be done to optimize the post-mono trait solving to be less unfriendly to large futures, but I will note that creating arbitrarily large futures eventually will cause the compiler to slow down...

What I'd really like to understand is how a real-world program ends up with such large futures that this regression becomes meaningful -- but I understand how that may be hard to summarize without sharing too much info about private code 😶

**Comment by Dirbaio** [comment]
I don't think I'm doing anything particularly cursed, just writing async code :sweat_smile: 

The deepest future I have in my firmware is this I think (removing the code for it made the biggest difference in the compile time):

- top level task with a loop handling incoming network requests
- Some request header is parsed from the socket with a "request ID", a switch is done on it.
- One of the request IDs is a "config update", which requires...
- Parsing a stream of key+value from the socket, writing it to `ekv`.
- `ekv` itself has quite a bit of layers with complex logic (transaction, record, file, page, then a Flash async trait. you can see that in that repo)
- flash access goes through a Mutex because other parts of the system can use other flash partitions concurrently
- flash is implemented using more async in the HAL

so yeah that can easily be 30 nested futures :sweat:. 

It's not particularly cursed though! it's straightforward code that you could also write blocking, just with `async` and `.await` in the right places. I don't go out of my way to write things as state machines manually and then wrap them with async to reduce futures depth. I don't want to, I'm using async to not have to do that.

**Comment by compiler-errors** [comment]
Makes sense. I'll see what I can do about it.

**Comment by compiler-errors** [comment]
@KittyBorgX: that tag is usually used to track PRs that are perf regressions with the internal perf testing suite (rust-timer). We have another tag for issues like this: I-slow.

**Comment by lqd** [comment]
@compiler-errors I-compiletime (I-slow is for performance of generated code)

**Comment by compiler-errors** [comment]
Corrected!

**Comment by KittyBorgX** [comment]
> @KittyBorgX: that tag is usually used to track PRs that are perf regressions with the internal perf testing suite (rust-timer). We have another tag for issues like this: I-slow.

Ah my bad 😅 I'm still new to this and I'm learning haha :)

**Comment by compiler-errors** [comment]
@Dirbaio: I haven't been able to get around to this yet, but since y'all are using AFIT, I'm not gonna consider this a regression that needs to be reverted on beta or anything like that since you're presumably just pinned to the nightly right before this regression.

If I haven't gotten to it in another week or so, please ping me so I may reconsider reverting the PR that I regressed this in, but just trying to make sure I understand and am able to set a reasonable timeline for this fix.

**Comment by Dirbaio** [comment]
Thanks for the update. If there's anything I can do to help please let me know. For example, would it help if I minimized it to a self-contained .rs file using no libs?

**Comment by compiler-errors** [comment]
That would certainly be cool if you could.

**Comment by ForsakenHarmony** [comment]
Hmm, I'm also having issues, also using futures with embassy, but for me, it's the performance of the compiled code.

My update cycle goes from ~15ms to ~18ms.

The codebase is pretty small, but you might need an rp2040 to reproduce it. (actually it seems to affect both the program running on the host and on the microcontroller).

Repo: https://github.com/ForsakenHarmony/serial-ws2812

**Comment by compiler-errors** [comment]
@Dirbaio I'm free enough to look at this again -- how do I reproduce that ekv example? Just a `cargo build`? I don't see a hang, but maybe I'm missing a feature flag or something?

**Comment by Dirbaio** [comment]
I can confirm #114948 fixes the issue! It fixes all the hang repros found, and also the regression on the project I originally found it in (company code)

"change one line" build times on company code:

- nightly-2023-06-28: 17s-20s
- nightly-2023-08-16: 1m 43s
- PR [#114948](https://github.com/rust-lang/rust/issues/114948): 22s-24s

**Comment by Dirbaio** [comment]
:partying_face: 

thank you @compiler-errors !
