### ISSUE TITLE
Testing SnoozeThis (please ignore)

### ISSUE THREAD

**Issue by Jille** [rust-lang/rust#113338]
Hey there. We were asked to integrate [SnoozeThis](https://www.snoozethis.com/) with rustbot. I want to do some testing, so I'm creating this issue for that. Sorry for the spam.

**Comment by jyn514** [comment]
please use a different repository for testing.

**Comment by Jille** [comment]
Sure, any suggestion? It does need to have rustbot installed.

**Comment by jyn514** [comment]
rustbot is open source, you can install it on any repository you own: https://github.com/rust-lang/triagebot#running-triagebot
