### ISSUE TITLE
error[E0635]: unknown feature `proc_macro_span_shrink`

### ISSUE THREAD

**Issue by cacilhas** [rust-lang/rust#113300]
```
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> $HOME/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.59/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |
```

Just trying to use some popular crates, like `thiserror` and `structopt`. It’s crashing in nightly 0.72.

**Comment by Nilstrieb** [comment]
Thanks for the report. Sew #113152, you need to update proc_macro2.

**Comment by Nilstrieb** [comment]
> Thanks for the report. See #113152, you need to update proc_macro2.
