### ISSUE TITLE
Implement copy_iter() for vectors

### ISSUE THREAD

**Issue by mitsuhiko** [rust-lang/rust#11340]
Currently I find myself having to unreference items very often to when combining iterators.  eg: doing this

```rust
let x = bytes!("foo");
x.iter().map(|&x| x).something_here()
```

In some cases you can use `.move_iter()` but that does not work unless you actually want to consume that container.

I wonder if we should have a `.copy_iter()` and `.copy_rev_iter()` that makes copies instead.  This would especially be useful for working with `[u8]`s.  For strings we have `.chars()` which yield the integers directly.  When working on parsers it's not uncommon to do this via iterators at the moment.  However this works widely different for strings and `[u8]`s because of that.  A `.copy_iter()` would bring parity.

**Comment by alexcrichton** [comment]
Since opened, we now have a new iterator adapter, `.cloned()`, which I believe is basically what this issue is requested, so closing as fixed.
