### ISSUE TITLE
Collection of issues blocked on apfloat situation

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#113409]
apfloat is in a [bit of a situation](https://github.com/rust-lang/rust/issues/55993) and has been for a long time. I'd like to have a central list of things to get back to and fix once that situation is resolved; that is the purpose of this issue.

- https://github.com/rust-lang/rust/issues/100233
- https://github.com/rust-lang/rust/issues/102403
- https://github.com/rust-lang/rust/issues/113407

**Comment by eddyb** [comment]
I posted a longer update to https://github.com/rust-lang/rust/issues/55993#issuecomment-1633772225 regarding the progress with the whole `rustc_apfloat` situation, but of note for this issues is that the WIP repo already has 2/3 issues listed here fixed (and the last one has a known fix, just requires further advancing the port closer to the present day).
