### ISSUE TITLE
Rustdoc doesn't always show feature-gated types

### ISSUE THREAD

**Issue by cdmistman** [rust-lang/rust#113499]
[miette](https://docs.rs/miette/5.9.0/miette/index.html) has several types that are feature-gated, such as [`GraphicalReportHandler`](https://docs.rs/miette/5.9.0/miette/struct.GraphicalReportHandler.html), which aren't shown as feature-gated in documentation.

I expected this:
<img width="1022" alt="Screenshot 2023-07-09 at 12 20 18 AM" src="https://github.com/rust-lang/rust/assets/23486351/799bfa9c-28fb-4c00-ab81-c4a5eba6e30f">

to contain a box saying `fancy-no-backtrace` next to the `GraphicalReportHandler` link as shown eg in this screenshot from the [tokio docs](https://docs.rs/tokio/1.29.1/tokio/)
<img width="1022" alt="Screenshot 2023-07-09 at 12 21 40 AM" src="https://github.com/rust-lang/rust/assets/23486351/a4fe1794-b423-45c2-9a3a-b6e5d41a2a34">

**Comment by Nilstrieb** [comment]
Tokio does this using an unstable feature called `doc_cfg`.

**Comment by GuillaumeGomez** [comment]
I'm waiting for help to finish the [RFC](https://github.com/GuillaumeGomez/rfcs/pull/2). In the meantime, you can use `doc_auto_cfg` feature so it's filled automatically.

**Comment by GuillaumeGomez** [comment]
Tracking issue is https://github.com/rust-lang/rust/issues/43781. Closing then.
