### ISSUE TITLE
error[E0152]: duplicate lang item in crate

### ISSUE THREAD

**Issue by Alef-gabriel** [rust-lang/rust#113494]
Compiler error when I'm build.

cargo version: 1.72.0-nightly
rustc version: 1.72.0-nightly

`error: could not compile `libc` (lib)`

**Comment by jieyouxu** [comment]
Do you have more context? What are you trying to build? OS version?

**Comment by Alef-gabriel** [comment]
@jieyouxu `cargo build` on rust code base, I'm run the configuration scripts, but nothing.
OS version: linux 5.15.0-76-generic

**Comment by Nilstrieb** [comment]
can you share your code? we can't really help without something to look at

**Comment by Alef-gabriel** [comment]
@Nilstrieb  yes, is the rust code-base, I'm trying to contribute, I've run the configuration script but nothing

**Comment by Nilstrieb** [comment]
Ah, this repository. Can you show all the commands you've run?

**Comment by Alef-gabriel** [comment]
`./configure`
`./x.py build && ./x.py install`

`cargo build`

**Comment by Nilstrieb** [comment]
This repository is not intended to be `cargo build`t. In general, `cargo` should never be invoked directly, only `x.py` should be used.

**Comment by Alef-gabriel** [comment]
Its is too slow, but thank you for help
