### ISSUE TITLE
Lifetime should be invariant WRT associated type?

### ISSUE THREAD

**Issue by dhardy** [rust-lang/rust#113537]
I believe the lifetime of a type should be invariant with respect to that of (trait) associated types?

At any rate, this compiles:
```rust
use std::marker::PhantomData as PD;

trait Trait {}

struct A<T>(Box<dyn Fn(T) -> ()>);
impl<T> Trait for A<T> {}

struct B<C>(Box<dyn Trait, PD<C>);

fn foo<'a>() {
    let a = A(Box::new(move |_: &()| ()));
    let _b: B<&'a ()> = B(Box::new(a), PD);
}
```
but this does not:
```rust
trait Trait {
    type T;
}

struct A<T>(Box<dyn Fn(T) -> ()>);
impl<T> Trait for A<T> {
    type T = T;
}

struct B<C>(Box<dyn Trait<T = C>>);

fn foo<'a>() {
    let a = A(Box::new(move |_: &()| ()));
    let _b: B<&'a ()> = B(Box::new(a));
    // err: ^^^^^^^^^ type annotation requires that `'a` must outlive `'static`
}
```
(The only differences are the addition of assoc. `type T` to `Trait` in the latter, and the use of `PhantomData` to avoid "unused type error" in the former.)

One can "solve" the latter by reducing the lifetime of `B`, but I don't believe this should be necessary:
```rust
struct B<'a, C>(Box<dyn Trait<T = C> + 'a>);
```

I think one of two things must be going on:
1. Lifetime analysis bug
2. The lifetime of `A<T>` where `<A<T> as Trait>::T = T` cannot exceed the lifetime of `T`. But why not, and if so can we relax this restriction?

**Comment by aliemjay** [comment]
> The lifetime of A<T> where <A<T> as Trait>::T = T cannot exceed the lifetime of T. But why not, and if so can we relax this restriction?

The RFC 1214 explicitly dictates that outlive relations are syntactic for ADTs and dynamic types, so that `dyn Fn(T): 'static` holds if and only if  `T: 'static`. Changing this would break the following:
```rust
fn is_static<T: 'static>() {}
fn test(_: &'static dyn Fn(T)) {
    is_static::<T>;
}
```

**Comment by dhardy** [comment]
Thanks; it seems clear in retrospect that a `dyn Trait` cannot out-live its associated data type. I need GATs for that, but I need object-safe GATs which are not a thing yet.
