### ISSUE TITLE
native::start should get a more accurate estimate of the stack bounds

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#11359]
It currently just assumes that it's always 2MB.

This logic was added by #11360.

**Comment by steveklabnik** [comment]
`native::start` is now totally gone, so I believe this is now irrelevant.

**Comment by jshs** [comment]
The stack size of the main thread is still estimated in [std::rt](https://github.com/rust-lang/rust/blob/cf636c233dfeef5abf0de8fb35e23c0a161810d2/src/libstd/rt/mod.rs#L78-L81), so I think the issue remains relevant.

**Comment by pnkfelix** [comment]
reopening: the code in question is still just guessing, AFAICT, and appears to be triggering an overflow (or underflow) panic on the branch with arithmetic overflow checking: http://buildbot.rust-lang.org/builders/auto-linux-32-opt/builds/3910/steps/test/logs/stdio

**Comment by steveklabnik** [comment]
Triage: the FIXME comment is now gone, and I don't know the internals well enough to determine if this is something that's still relevant. I think the removal of morestack would make this go away?

**Comment by alexcrichton** [comment]
Ah yeah this is long since gone
