### ISSUE TITLE
bootstrap: sanity check install prefix and sysconfdir

### ISSUE THREAD

**Issue by cuviper** [rust-lang/rust#113580]
In the followup discussion on #110906, we discovered that their original problem was because they had chosen a path under their home directory for `[install] prefix`, but they had not changed the default `sysconfdir = "/etc"`. So most things installed fine, but they didn't have permission to write `/etc/bash_completion.d/cargo`.

Bootstrap could sanity check this when starting an install, seeing that `prefix` is writable by the current user but the absolute `sysconfdir` is not. (A relative `sysconfdir` goes under `prefix`, which should be fine.) This should also take `DESTDIR` into account  as a further prefix on all installation paths.

**Comment by LJason77** [comment]
I have just updated to version 1.71.0, and now I'm receiving the terminal warning: 
`~/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/etc/bash_completion.d/cargo: No such file or directory`

In my previous setup, I added the line `source $(rustc --print sysroot)/etc/bash_completion.d/cargo` to my `~/.bashrc` file.

**Comment by cuviper** [comment]
@LJason77 yeah, #110906 made that effectively `$sysroot/src/etc`. That was reverted in #113579, and now proposed for stable and beta backports. So you could add `src/` for now, but it will be going back to the way it was.
