### ISSUE TITLE
function `is_copy_modulo_regions` from `rustc_middle::ty::Ty` panick on reference type (nightly)

### ISSUE THREAD

**Issue by fanbaoAA** [rust-lang/rust#113632]
I'm trying to use this function `is_copy_modulo_regions` from `rustc_middle::ty::Ty`. It can be found in the documentation at https://doc.rust-lang.org/stable/nightly-rustc/rustc_middle/ty/struct.Ty.html#method.is_copy_modulo_regions. I try to check whether values of a type `T` are moved or copied when referenced, as described in the document. It worked with `String`, `usize`. But when the type is a reference type or contains a reference type, the program panicked. 
For example,  for `(&String,String)`, it panicked as
```
thread 'rustc' panicked at '`<(&std::string::String, std::string::String) as std::marker::Copy>` has escaping bound vars, so it cannot be wrapped in a dummy binder.', compiler/rustc_trait_selection/src/traits/mod.rs:130:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: could not compile `test-crate` (lib)

Caused by:
  process didn't exit successfully: `CARGO=/home/fanbao/.rustup/toolchains/nightly-2023-04-12-x86_64-unknown-linux-gnu/bin/cargo CARGO_CRATE_NAME=test_crate CARGO_MANIFEST_DIR=/mnt/f/FP/rustviz/print/test-crate CARGO_PKG_AUTHORS='' CARGO_PKG_DESCRIPTION='' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE='' CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=test-crate CARGO_PKG_README='' CARGO_PKG_REPOSITORY='' CARGO_PKG_RUST_VERSION='' CARGO_PKG_VERSION=0.1.0 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=1 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION_PRE='' CARGO_PRIMARY_PACKAGE=1 LD_LIBRARY_PATH='/mnt/f/FP/rustviz/print/test-crate/target/plugin-nightly-2023-04-12/debug/deps:/home/fanbao/.rustup/toolchains/nightly-2023-04-12-x86_64-unknown-linux-gnu/lib:/home/fanbao/.rustup/toolchains/nightly-2023-04-12-x86_64-unknown-linux-gnu/lib' /home/fanbao/.cargo/bin/print-all-items-driver rustc --crate-name test_crate --edition=2021 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=120 --crate-type lib --emit=dep-info,metadata -C embed-bitcode=no -C debuginfo=2 -C metadata=4c182b5b49824176 -C extra-filename=-4c182b5b49824176 --out-dir /mnt/f/FP/rustviz/print/test-crate/target/plugin-nightly-2023-04-12/debug/deps -C incremental=/mnt/f/FP/rustviz/print/test-crate/target/plugin-nightly-2023-04-12/debug/incremental -L dependency=/mnt/f/FP/rustviz/print/test-crate/target/plugin-nightly-2023-04-12/debug/deps` (exit status: 101)
```
I wonder if the function is designed not to work with reference type or it's a bug.

**Comment by compiler-errors** [comment]
I think this is a bug in how the `is_copy_modulo_regions` function is being used in the code that you're writing. You need to make sure that you're keeping proper track of [`Binder`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.Binder.html)s.

Given that this isn't really a rustc bug, I'm gonna close the issue. I recommend opening up a thread on [Zulip's `t-compiler/help`](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp) stream, and please share as much code as you can.
