### ISSUE TITLE
 undefined reference to `memfd_create

### ISSUE THREAD

**Issue by codearun** [rust-lang/rust#113680]
/root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nix-0.26.2/src/sys/memfd.rs:56: undefined reference to `memfd_create
error: could not compile `bpfd` (bin "bpfd") due to previous error

Attempting to compile bpfd using cargo and rust using a centos7 container.

**Comment by Nilstrieb** [comment]
`memfd_create` was only added in glibc 2.27. Your glibc version must be older than that. If bpfd relies on that function there's nothing you can do other than trying to patch it to not use it.

**Comment by workingjubilee** [comment]
See https://github.com/lucab/libsystemd-rs/pull/144

Unfortunately we cannot meaningfully assist with ecosystem crates beyond our control.

**Comment by workingjubilee** [comment]
For reference:
- CentOS Linux is an EOL distribution. CentOS 8 was the last version. CentOS 7 was initially released in 2014, CentOS 8 in 2019, and there will be no CentOS 9.
- "CentOS Stream" is not quite the same thing, nor is Alma Linux 9, or Rocky Linux 9, or whatever other RHEL-likes now exist, though for many, one of the above is a good alternative.
- As not everyone wishes to change to CentOS Stream or similar distros, yet CentOS was in some ways the "free" version of RHEL, CentOS was very popular, and its death has left a lot of "stranded" users with no clear upgrade path forward. This makes support requests for CentOS in particular are very common.
- From the Rust perspective, there is also absolutely effectively nothing we can do to help CentOS 7 users, in practice, aside from suggest they try another distro: Our kernel minimum requires at least CentOS 8.

**Comment by workingjubilee** [comment]
@codearun This is not due to the Rust standard library. I linked the problematic dependency: the libsystemd crate. You need to search the entire transitive dependency graph of crates.
