### ISSUE TITLE
Why isn't the `unsafe` keyword necessary for custom MIR?

### ISSUE THREAD

**Issue by extf33** [rust-lang/rust#113664]
Why isn't the `unsafe` keyword necessary for [custom MIR](https://doc.rust-lang.org/std/intrinsics/mir/index.html)?
It seems like using custom MIR can potentially introduce memory-related bugs and even trigger internal compiler errors(ICE).

**Comment by compiler-errors** [comment]
I also don't think that this needs `unsafe`. There are plenty of internal features that may be used in unsound ways that are either unnecessarily inconveniencing or actually impossible to mark with `unsafe` -- the documentation for custom MIR states that it is meant for testing only, and #108955 will make sure that folks acknowledge that they're using an internal feature, as well.

**Comment by compiler-errors** [comment]
Since this has to do with an internal-only feature, I don't think this needs to be tracked. Feel free to reopen it if y'all disagree.

**Comment by lukas-code** [comment]
I think we should wait for https://github.com/rust-lang/rfcs/pull/3325 and then make the `custom_mir` attribute unsafe, similar to `no_mangle`.

**Comment by workingjubilee** [comment]
As long as macros are involved, no Rust code requires the visible presence of the `unsafe` keyword, as [plutonium](https://docs.rs/plutonium/latest/plutonium/) demonstrates. :angel:
