### ISSUE TITLE
Internal Compiler Error when changing type of field in enum variant

### ISSUE THREAD

**Issue by mpeter50** [rust-lang/rust#113635]
### Explanation

To trigger the error, first run `cargo build` with the included code, then change the type of `first_string` to TestStruct, and rerun the build command.

There was a Github error while submitting the issue, so I moved the backtrace and the error log to a gist.

### Code

```Rust
use serde::Deserialize;

fn main() {
    let variant: MyEnum = serde_json::from_str("some_string").unwrap();
}

#[derive(Deserialize, Debug)]
#[serde(untagged)]
enum MyEnum {
    Variant1 { my_string: String },
    Variant2 { first_string: String, second_string: String }
}

#[derive(Deserialize, Debug)]
struct TestStruct;

#[derive(Deserialize, Debug)]
struct TestStruct2;
```

### Meta

`rustc --version --verbose`:
```
rustc 1.70.0 (90c541806 2023-05-31)
binary: rustc
commit-hash: 90c541806f23a127002de5b4038be731ba1458ca
commit-date: 2023-05-31
host: x86_64-pc-windows-msvc
release: 1.70.0
LLVM version: 16.0.2
```

### Error output and backtrace

See this gist: https://gist.github.com/mpeter50/8a27609ff1378c60ea663127d2cd2cf7

**Comment by saethlin** [comment]
I can reproduce the ICE on stable but not nightly. It is possible that this has been fixed, but even if the underlying issue hasn't been fixed, this example isn't actionable.

Thank you for the report. This is a great issue, and I wish we got more like it.
