### ISSUE TITLE
clippy, rustfmt missing from master toolchain

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#113713]
`$ rustup-toolchain-install-master -f  -c rustc-dev llvm-tools rust-src clippy rustfmt`

```
fetching master commit hash...
detecting the channel of the `bef6ff618f17398775e9d8cd23a6f47d983869dc` toolchain...
downloading <https://ci-artifacts.rust-lang.org/rustc-builds/bef6ff618f17398775e9d8cd23a6f47d983869dc/rustc-nightly-x86_64-unknown-linux-gnu.tar.xz>...
75.13 MB / 75.13 MB [===================================================================================================================================================================================] 100.00 % 6.67 MB/s
downloading <https://ci-artifacts.rust-lang.org/rustc-builds/bef6ff618f17398775e9d8cd23a6f47d983869dc/rustc-dev-nightly-x86_64-unknown-linux-gnu.tar.xz>...
101.82 MB / 101.82 MB [=================================================================================================================================================================================] 100.00 % 6.37 MB/s
downloading <https://ci-artifacts.rust-lang.org/rustc-builds/bef6ff618f17398775e9d8cd23a6f47d983869dc/llvm-tools-nightly-x86_64-unknown-linux-gnu.tar.xz>...
42.90 MB / 42.90 MB [===================================================================================================================================================================================] 100.00 % 5.91 MB/s
downloading <https://ci-artifacts.rust-lang.org/rustc-builds/bef6ff618f17398775e9d8cd23a6f47d983869dc/rust-src-nightly.tar.xz>...
2.55 MB / 2.55 MB [=====================================================================================================================================================================================] 100.00 % 2.36 MB/s
downloading <https://ci-artifacts.rust-lang.org/rustc-builds/bef6ff618f17398775e9d8cd23a6f47d983869dc/clippy-nightly-x86_64-unknown-linux-gnu.tar.xz>...
error: missing component `clippy` on toolchain `bef6ff618f17398775e9d8cd23a6f47d983869dc` on channel `nightly` for target `x86_64-unknown-linux-gnu`
```

**Comment by matthiaskrgr** [comment]
Weird, so this error started happening somewhere in the  last ~24 hours I guess, but when I install the "master" toolchain of a few days ago (where we shipped a nightly that did include clippy), RTIM also can't find the clippy component... :thinking:

**Comment by matthiaskrgr** [comment]
rustfmt is also affected

`wget https://ci-artifacts.rust-lang.org/rustc-builds/bef6ff618f17398775e9d8cd23a6f47d983869dc/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.xz`

`wget https://ci-artifacts.rust-lang.org/rustc-builds/bef6ff618f17398775e9d8cd23a6f47d983869dc/clippy-nightly-x86_64-unknown-linux-gnu.tar.xz`

=> 404

**Comment by RalfJung** [comment]
> Weird, so this error started happening somewhere in the last ~24 hours I guess, but when I install the "master" toolchain of a few days ago (where we shipped a nightly that did include clippy), RTIM also can't find the clippy component... 

In 33a2c2487ac5d9927830ea4c1844335c6b9f77db it [can find clippy](https://github.com/rust-lang/miri/actions/runs/5551080497/jobs/10136833276). Which commit did you try?

**Comment by RalfJung** [comment]
Cc @rust-lang/infra (since this seems fairly critical)

**Comment by Kobzol** [comment]
A try build was merged into master, and basically no artifacts were uploaded from that merge commit (https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Cannot.20get.20rust-dev-nightly.20from.20ci-artifacts.2Erust-lang.2Eorg).

**Comment by Nilstrieb** [comment]
Approving a PR while a try build is running has some very unintended consequences.

**Comment by matthiaskrgr** [comment]
>A try build was merged into master,

well its only the 5th time or so that that has happened >.<

**Comment by jyn514** [comment]
this was fixed: https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/.E2.9C.94.20Cannot.20get.20rust-dev-nightly.20from.20ci-artifacts.2Erust-lang.2E.2E.2E
