### ISSUE TITLE
bootstrap PGO artifact copies broken

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#113784]
It looks like at least the old Python script hardcoded the channel as "nightly", which won't work on beta and stable branches.

https://github.com/rust-lang/rust/pull/113540/commits/27ff8191989ff67c9e07f062d42a6ca1d1e42720 fixed this for last week's promotion from master -> beta, but it won't work on beta -> stable as that has yet another format.

We probably want to mirror the logic here: https://github.com/rust-lang/promote-release/blob/348f02569e3aff02187e90bbf532e63ccf62a268/src/main.rs#L451-L458, specifically the version part.

I think we'll want to land a commit on beta with the fix targeting stable, and a separate one on master -- given we just rewrote the script to Rust I'm not sure trying to backport something makes much sense. If the beta commit is tricky for some reason, we can skip that and just hardcode the version when running the next beta -> stable promotion.

cc @Kobzol -- maybe you can help work on this.

**Comment by Kobzol** [comment]
Maybe the simplest solution would just be to look up these files by their prefix? (We can also ignore the tests for beta/stable releases, but it probably is highly valuable to run these tests for them).

**Comment by Mark-Simulacrum** [comment]
I think the above two PRs should have fixed this.
