### ISSUE TITLE
rustc --emit=dep-info also includes rustdoc requirements without --cfg=doc

### ISSUE THREAD

**Issue by danakj** [rust-lang/rust#113839]
The #[doc] attribute can be used to generate rustdoc from a file:
```rs
#[doc = include_str!("README.md")]
fn foo() {}

fn main() {
    foo()
}
```

However when compiling this code, rustc also reads the md file even though it is not part of its output. This means that bots compiling crates need to bring in the .md files to compile even though they could be avoided.

Is it possible that `include_str!` inside the `#[doc] macro`, which won't be expanded to anything during compilation (right?) could be dropped, thus avoiding this file from appearing in `rustc --emit=dep-info` as well when not compiling with `--cfg=doc`?

**Comment by bjorn3** [comment]
For public items the documentation will end up in the crate metadata to allow rustdoc to read it in case of `#[doc(inline)]`. For private items this also used to happen, but was removed a while back as optimization. Depending on macro expansion order it may also be possible for macros to read the result of the `include_str!()`, but I don't knkw if it is possible for this expansion to happen before user defined macros run. It may be possible to ignore the dep but I can imagine it would be messy as we don't know if an item is public or not (and thus needs the docs embedded in the crate metadata) until after macro expansion. Also `#[doc = compile_error!()]` still has to be expanded for private items resulting in an error.

**Comment by danakj** [comment]
Ah, thanks. Going in the metadata means it is needed so I think this is a non-starter. Thanks for the feedback!
