### ISSUE TITLE
Add non-panicking variants of `Steal` methods

### ISSUE THREAD

**Issue by momvart** [rust-lang/rust#113809]
It would be better if we had probing variants of methods in `rust_data_structures::steal::Steal`. Currently, there's no way to check if the value is already stolen and should not be even asked to be borrowed again.

And by non-panicking variants I mean `try_*` functions.

**Comment by BoxyUwU** [comment]
Why do we want this? It does not seem obviously like a good idea.

**Comment by momvart** [comment]
The implementation may look as follows.
```rust
impl<T> Steal<T> {
    pub fn new(value: T) -> Self {
        Steal { value: RwLock::new(Some(value)) }
    }

    #[track_caller]
    pub fn try_borrow(&self) -> Option<MappedReadGuard<'_, T>> {
        // This try_borrow should be also added.
        let borrow = self.value.try_borrow()?;
        if borrow.is_none() {
            None
        } else {
            Some(ReadGuard::map(borrow, |opt| opt.as_ref().unwrap()))
        }
    }

    #[track_caller]
    pub fn borrow(&self) -> MappedReadGuard<'_, T> {
        self.try_borrow().unwrap_or(|| { 
            panic!("attempted to read from stolen value: {}", std::any::type_name::<T>())
        })
    }

    #[track_caller]
    pub fn try_get_mut(&mut self) -> Option<&mut T> {
        self.value.get_mut().as_mut()
    }

    #[track_caller]
    pub fn get_mut(&mut self) -> &mut T {
        self.try_get_mut().expect("attempt to read from stolen value")
    }

    #[track_caller]
    pub fn try_steal(&self) -> Option<T> {
        let value_ref = &mut *self.value.try_write()?;
        value_ref.take()
    }

    #[track_caller]
    pub fn steal(&self) -> T {
        let value_ref = &mut *self.value.try_write().expect("stealing value which is locked");
        let value = value_ref.take();
        value.expect("attempt to steal from stolen value")
    }
}
```

**Comment by momvart** [comment]
> Why do we want this? It does not seem obviously like a good idea.

I agree and probably it doesn't have a use case in the compiler itself. However, I'm working on a MIR body transformer that at some points may query the body that is currently under transformation. Just examining and skipping accessing the stolen value is enough in my case.

**Comment by momvart** [comment]
Actually nevermind. I was fetching an already optimized MIR which should not happen. `Steal` is supposed to host a short-living object so as you said it's not a good idea to have such methods.
