### ISSUE TITLE
possible bug in vtable formation

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#113840]
While working on #112355 I _think_ I found a bug. Given this program:

```rust
#![feature(rustc_attrs)]

#[rustc_dump_vtable]
pub trait What: Send + Sync {
    fn a(&self) {}
}

impl What for () {}

fn main() {
    (&() as &dyn What).a();
}
```
rustc outputs the following vtable layout:
```
 [
    MetadataDropInPlace,
    MetadataSize,
    MetadataAlign,
    TraitVPtr(<() as Sync>),
    Method(<() as What>::a),
]
```

Which is surprising, because `TraitVPtr(<() as Sync>)` is unnecessary — `Send` does not have any methods, so `Sync` vtable can be inlined...

I think we should be smarter here:
https://github.com/rust-lang/rust/blob/cb882fa998571e8a7ec1c06bb5d9dd9bc3423629/compiler/rustc_trait_selection/src/traits/vtable.rs#L143-L144

(for the record, I'm pretty sure this happens in practice, I've found this with [`log::Log`](https://docs.rs/log/0.4.19/log/trait.Log.html))

_Originally posted by @WaffleLapkin in https://github.com/rust-lang/rust/issues/65991#issuecomment-1587598244_

**Comment by crlf0710** [comment]
sorry been slow a little recently... This is a nice improvement.
