### ISSUE TITLE
Setting #![windows_subsystem = "windows"], processes will not be spawned under Windows server 2008 SYSTEM privileges.

### ISSUE THREAD

**Issue by b1nhack** [rust-lang/rust#113851]
I tried this code:

```rust
#![windows_subsystem = "windows"]

use std::process;

fn main() {
    process::Command::new("notepad.exe").spawn().unwrap();
}
```

I expected to see this happen: 
Setting **#![windows_subsystem = "windows"]**, processes will not be spawned under Windows server 2008 SYSTEM privileges.

### Meta

`rustc --version --verbose`:
```
rustc 1.70.0 (90c541806 2023-05-31)
binary: rustc
commit-hash: 90c541806f23a127002de5b4038be731ba1458ca
commit-date: 2023-05-31
host: x86_64-pc-windows-msvc
release: 1.70.0
LLVM version: 16.0.2
```

<details><summary>Backtrace</summary>
<p>

```
Because of the specification of #![windows_subsystem = "windows"], so I can't see the backtrace
```

</p>
</details>

**Comment by b1nhack** [comment]
> What processes do you expect to not be spawned?

everyting

**Comment by bjorn3** [comment]
I don't understand the issue you are having. Please give a concrete example of a process that shouldn't have started.

**Comment by bjorn3** [comment]
If you run your program with SYSTEM privileges and your program then runs `notepad.exe`, it is expected that `notepad.exe` will also run with SYSTEM privileges. Programs inherit the privileges level of their parent by default.

If you don't run your program with SYSTEM privileges and yet `notepad.exe` somehow runs with SYSTEM privileges, that is not a bug in rust, but one in Windows. It shouldn't be possible for an unprivileged user to run arbitrary programs with the highest possible privilege level.

**Comment by b1nhack** [comment]
No, I mean only under Windows Server 2008, and running with SYSTEM privileges.

**Comment by b1nhack** [comment]
```
#![windows_subsystem = "windows"]

use std::process;

fn main() {
    process::Command::new("notepad.exe").spawn().unwrap();
}
```

This code is compiled into a binary program (*.exe).
**Note: MSVC toolchain needs to specify "-C", "target-feature=+crt-static" flag to be compatible with Windows server 2008.**
The compiled exe, under Windows server 2008 with administrator privileges can normally spawn a notepad.exe process.

Using processhacker runas a cmd.exe with SYSTEM privileges, executing the compiled exe in a cmd with SYSTEM privileges will not spawn a notepad.exe process.
And this problem only occurs if you specify #![windows_subsystem = "windows"].

**Comment by ChrisDenton** [comment]
Have you tried nightly rust?

**Comment by b1nhack** [comment]
Not yet

**Comment by workingjubilee** [comment]
Note: Windows 2008 is based on Windows Vista which is out of our support range, unless you mean Windows 2008 R2, which is based on Windows 7 and is currently considered a "best effort" support target. These are also End of Support for Microsoft as well, unfortunately.

**Comment by b1nhack** [comment]
I am referring to Windows Server 2008 R2, after my testing, Windows 10 does not have this issue.

**Comment by workingjubilee** [comment]
Then this issue will be "fixed" in ~7 months by https://github.com/rust-lang/compiler-team/issues/651

**Comment by jieyouxu** [comment]
Triage: no longer relevant because https://github.com/rust-lang/compiler-team/issues/651.
