### ISSUE TITLE
red/green color in diffs can get offset from actually changed characters

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#113817]
### Code

```Rust
pub fn stuff(&foo: ()) {}
```

### Current output

```Shell
error[E0308]: mismatched types
 --> src/main.rs:1:14
  |
1 | pub fn stuff(&foo: ()) {}
  |              ^^^^  -- expected due to this
  |              |
  |              expected `()`, found `&_`
  |
  = note: expected unit type `()`
             found reference `&_`
help: to take parameter `foo` by reference, move `&` to the type
  |
1 - pub fn stuff(&foo: ()) {}
1 + pub fn stuff(foo: &()) {}
  |
```

### Rationale and extra context

![image](https://github.com/rust-lang/rust/assets/332036/6a8376c8-439e-42de-acae-79299fa9a879)

as you can see the `(` is green, but the `&` before it should be.

**Comment by matthiaskrgr** [comment]
Related: https://github.com/rust-lang/rust-clippy/issues/10582

**Comment by Urgau** [comment]
I'm not reproducing the issue on either master (a161ab00dbf660dd587ee42a8c855bac94047ddb), nightly (*2023-07-17*) or stable (*1.71*).

![image](https://github.com/rust-lang/rust/assets/3616612/c5ffcb59-5713-431d-8ff6-3d9c6098ab17)

**Comment by oli-obk** [comment]
Oops. I should have included the rustc version and checked with the latest.
