### ISSUE TITLE
Improve help for const-able values used in array initialization

### ISSUE THREAD

**Issue by alexschrod** [rust-lang/rust#113912]
### Code

```Rust
fn main() {
    let x = [None::<String>(); 10];
}
```

### Current output

```Shell
error[E0277]: the trait bound `String: Copy` is not satisfied
 --> src/main.rs:2:14
  |
2 |     let x = [None::<String>; 10];
  |              ^^^^^^^^^^^^^^ the trait `Copy` is not implemented for `String`
  |
  = note: required for `Option<String>` to implement `Copy`
  = note: the `Copy` trait is required because this value will be copied for each element of the array
```

### Desired output

```Shell
error[E0277]: the trait bound `String: Copy` is not satisfied
 --> src/main.rs:2:14
  |
2 |     let x = [None::<String>; 10];
  |              ^^^^^^^^^^^^^^ the trait `Copy` is not implemented for `String`
  |
  = note: required for `Option<String>` to implement `Copy`
  = note: the `Copy` trait is required because this value will be copied for each element of the array
  = help: consider creating a new `const` item and initializing it with the value to be used in the repeat position, like `const VAL: Type = value;` and `let x = [VAL; 42];`
```

### Rationale and extra context

I'm basing this suggestion on two things. One, that if you follow it, the code compiles:
```rs
fn main() {
    const NONE: Option<String> = None;
    let x = [NONE; 10];
}
```
and two, that the diagnostic help you get when you try to use a `const fn` in the repeat position suggests something very similar, see "other cases." It would require the compiler to know that a value that is attempted to be repeated is `const`able though, which I don't know whether it can, but I figured I'd suggest this, and you can reject it if it isn't possible to do.

Alternatively, the help text could say something like "*if the value can be made `const`*, consider creating [...]"

### Other cases

I was inspired to make this issue based on the output you get when you try to use a `const fn` as an array initializer. For instance, the code

```Rust
fn main() {
    let x = [none::<String>(); 10];
}

const fn none<T>() -> Option<T> {
    None
}
```
produces the output
```
error[E0277]: the trait bound `String: Copy` is not satisfied
 --> src/main.rs:2:14
  |
2 |     let x = [none::<String>(); 10];
  |              ^^^^^^^^^^^^^^^^ the trait `Copy` is not implemented for `String`
  |
  = note: required for `Option<String>` to implement `Copy`
  = note: the `Copy` trait is required because this value will be copied for each element of the array
  = help: consider creating a new `const` item and initializing it with the result of the function call to be used in the repeat position, like `const VAL: Type = const_fn();` and `let x = [VAL; 42];`
```

**Comment by AnuragNishad12** [comment]
hey @alexschrod why im getting this error message all over my github repository 
![photo_6183691714766682578_w](https://github.com/rust-lang/rust/assets/124987038/9e325db8-5eef-41fe-ae93-6e66db08633a)
whenever i commit some changes,  The  first changes i able to create pull request but after some other changes im not able to do that why im getting these error 
![photo_6183691714766682577_w](https://github.com/rust-lang/rust/assets/124987038/f524c95b-467b-4708-a9da-5a1a42193ce5)
Please help

**Comment by lcnr** [comment]
@AnuragNishad12 I don't think your comment is related to this issue? If this is an issue you've encountered while trying to fix this issue, please reach out on [zulip](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp) instead.
