### ISSUE TITLE
`./x.py test` panics

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#113963]
```
$ ./x.py test
Building bootstrap
    Finished dev [unoptimized] target(s) in 0.18s
thread 'main' panicked at 'fs::read_dir(builder.src.join(&relative_path).join("redirects")) failed with No such file or directory (os error 2)', doc.rs:228:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Build completed unsuccessfully in 0:00:01
```
This might not be a valid request (I have to tell it what to test), but surely it shouldn't just result in such an obscure panic.

Cc @rust-lang/bootstrap

**Comment by chenyukang** [comment]
you don't have dir `src/doc/book/redirects`?

**Comment by ozkanonur** [comment]
it doesn't exists until fetching the submodule

**Comment by RalfJung** [comment]
Seems like I don't have that submodule checked out; I don't work on the book so it's not needed (and I keep the checked-out submodules to a minimum to avoid having to update them all the time).

**Comment by chenyukang** [comment]
I reprocued it in local, without 

```
submodules = false
```

in config.toml, `x.py test` will fail like this.

**Comment by ozkanonur** [comment]
I can fix it tomorrow, feel free to work on it if you want to fix it earlier.

**Comment by chenyukang** [comment]
@ozkanonur by the way, do you know why we use those `panic!` for `compiletest` here?

https://github.com/rust-lang/rust/blob/548978f1d025e9b937cdedabe3a86da70789dbdc/src/tools/compiletest/src/lib.rs#L165

**Comment by ozkanonur** [comment]
> @ozkanonur by the way, do you know why we use those `panic!` for `compiletest` here?
> 
> https://github.com/rust-lang/rust/blob/548978f1d025e9b937cdedabe3a86da70789dbdc/src/tools/compiletest/src/lib.rs#L165

Not particularly, I am not so familiar with the compiletest code. Probably we panic there so the compiletest runner process can handle(being able to understand compiletest was failed) that.

**Comment by ozkanonur** [comment]
The fix shouldn't make any changes on the compiletest side. We just need to avoid using submodules instead of assuming that they exist.

**Comment by chenyukang** [comment]
Yes, that's another issue, I just met it today.
