### ISSUE TITLE
Doc feature banners won't show up when re-exporting items with wildcard

### ISSUE THREAD

**Issue by rodrigocfd** [rust-lang/rust#113982]
### Problem

I'm building a big library crate, composed of multiple sub-crates. These sub-crates are gated through [Cargo features](https://doc.rust-lang.org/cargo/reference/features.html), so the user can choose what to import.

My goal is to have "fruits" and "colors" feature banners in the docs, for each item, like this:

![banners](https://github.com/rust-lang/cargo/assets/1283868/e088467e-7eae-4a3e-874e-9110d48a5672)

However, I'm only achieving this by manually declaring each member of each sub-crate:

```rust
#[cfg(feature = "colors")]
pub use colors::{
    blue,
    red,
    white,
};

#[cfg(feature = "fruits")]
pub use fruits::{
    banana,
    grape,
};
```

There will be hundreds of declarations, so this is very error-prone. When using wildcards to the declare the members, the feature banners won't show up:

![no-banners](https://github.com/rust-lang/cargo/assets/1283868/8e5c21ec-d362-48bd-87c3-a6a0690f2d3a)

```rust
#[cfg(feature = "colors")]
pub use colors::*;

#[cfg(feature = "fruits")]
pub use fruits::*;
```

Is this a bug or am I missing something?

Minimal reproducible example:

* https://github.com/rodrigocfd/big-lib

### Steps

1. Generate the docs with:

```
RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features --no-deps -p big-lib
```

### Version

```text
cargo 1.71.0 (cfd3bbd8f 2023-06-08)
release: 1.71.0
commit-hash: cfd3bbd8fe4fd92074dfad04b7eb9a923646839f
commit-date: 2023-06-08
host: x86_64-pc-windows-msvc
libgit2: 1.6.4 (sys:0.17.1 vendored)
libcurl: 8.0.1-DEV (sys:0.4.61+curl-8.0.1 vendored ssl:Schannel)
os: Windows 10.0.19045 (Windows 10 Pro) [64-bit]
```

**Comment by ehuss** [comment]
Transferred to rust-lang/rust, since this is likely an issue for rustdoc, which is tracked here.

**Comment by GuillaumeGomez** [comment]
I confirm this is a bug. Working on a fix.

**Comment by GuillaumeGomez** [comment]
One question though. Why did you put both `cfg` and `cfg_attr` for the same `cfg`:

```rust
#[cfg(feature = "colors")]
#[cfg_attr(docsrs, cfg(feature = "colors"))]
pub use colors::*;
```

Unless I'm missing something, it's supposed to be exactly the same so with `--cfg docsrs` you will have `cfg(feature = "colors")` twice.

**Comment by rodrigocfd** [comment]
> One question though. Why did you put both `cfg` and `cfg_attr` for the same `cfg`

You're right, it's redundant. It's a leftover from all the combinations I tried (I really tried *everything* possible).

Fixed.

**Comment by rodrigocfd** [comment]
Confirmed working in nightly.

Thank you, @GuillaumeGomez.
