### ISSUE TITLE
macro_rules! body errors for Mutex<?Sized>

### ISSUE THREAD

**Issue by pdamianik** [rust-lang/rust#113909]
| Channel | stable | nightly |
|--------------|----------|------------|
| rustc version | `rustc 1.71.0 (8ede3aae2 2023-07-12)` | `rustc 1.73.0-nightly (399b06823 2023-07-20)`

When using a [`Mutex`](https://doc.rust-lang.org/stable/std/sync/struct.Mutex.html) containg an unsized value like `dyn FnMut() + Send + 'static` inside of a macro_rules! body rustc complains about the unsized value needing to be either share referenced or boxed:

```rust
macro_rules! test {
    ($type:ident) => (
        struct Test {
            foo: ::std::sync::Mutex<dyn FnMut(&$type) + Send + 'static>,
        }
    )
}
```

![image](https://github.com/rust-lang/rust/assets/39028343/e018464a-6f0b-42cd-a2fe-b0da337af40c)

But the [`Mutex`](https://doc.rust-lang.org/stable/std/sync/struct.Mutex.html) opts out of the Sized bound for its contained value and should therefore be just as usable in this case. Outside of the macro_rules! body the compiler allows this to happen:

```rust
struct Test {
    foo: Mutex<dyn FnMut(&Bar) + Send + 'static>,
}
```

**Comment by wwylele** [comment]
I cannot reproduce the error with your simple example https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=79c96c7af628118b2278f04a235b40c2

If I guess it, your full code has more members after the Mutex member. Any unsized T will also make Mutex<T> unsized, which makes it only legal as the last member of any struct (plus also making that struct unsized).
