### ISSUE TITLE
ICE: `'attempted to read from stolen value: rustc_middle::mir::Body', compiler/rustc_mir_transform/src/ffi_unwind_calls.rs:50:78`

### ISSUE THREAD

**Issue by TicoTiger14** [rust-lang/rust#113919]
### Code

```Rust
<code>
### Meta
<!--
If you're using the stable version of the compiler, you should also check if the
bug also exists in the beta or nightly versions.
-->

`rustc --version --verbose`:
```
<version>
```

### Error output

```
<output>

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by TicoTiger14** [comment]
Please DISREGARD last comment.
The compiler printed this at the end of the bug report:

note: rustc 1.68.2 (9eb3afe9e 2023-03-27) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

**Comment by clubby789** [comment]
Are you able to provide a minimal reproducible example? And does this occur on the current stable Rust version (1.71.0) or beta/nightly?

**Comment by TicoTiger14** [comment]
For the first time this happened, I had to restart my work laptop and it did not happen the next time I compiled.  However, it just happened again compiling the same code base. The end of the error report contains the following which was displayed for both instances:
-------
query stack during panic:
#0 [has_ffi_unwind_calls] checking if `procedures::hac_bit_calibration::get_failure_cases` contains FFI-unwind calls
end of query stack
--------
I did not try any other version of Rust but would it be worth my time to try version 1.71.0 ??

**Comment by TicoTiger14** [comment]
I just reported another incident on your website, same code base and same issue.  I did not try version 1.71.0 of Rust, would it be worth it to update my installed version of Rust and try it ?  Is the new version backwards compatible ?

**Comment by saethlin** [comment]
> Is the new version backwards compatible ?

Every new version of Rust is supposed to be backwards-compatible. Yes it is worth it to try the latest stable.

**Comment by TicoTiger14** [comment]
On Friday before the workday ended, I upgraded Rust to 1.71.0 but this compiler bug still appeared.
