### ISSUE TITLE
Feature Request: BufferedReader function for reading without returning delimeter

### ISSUE THREAD

**Issue by WebeWizard** [rust-lang/rust#11404]
I keep running into situations where I need to read (BufferedReader) from a list of comma separated values or newline separated values and then storing the result.  Should I have to trim off the delimiter every time?  I feel like this is a common enough use case to be included in libstd.

```Rust
//reading until newline and trimming off the newline chars.
//probably a better way to do this.
let tempvalue = lineIter.next().unwrap().to_str();
let length = tempvalue.len();
let value = tempvalue.as_slice().slice_to( length - 2 );
```

**Comment by steveklabnik** [comment]
We're now using the RFC process to deal with standard library changes, and indeed, the IO RFC is currently active. If anyone still cares about this, that's the right place to get involved.
