### ISSUE TITLE
Cannot use Macros in Trait Bodies

### ISSUE THREAD

**Issue by mitsuhiko** [rust-lang/rust#11403]
I would have expected this to work,  but it does not:

```rust
#[feature(macro_rules)];

macro_rules! test {
    () => {
        fn foo();
    }
}

trait Foo {
    test!()
}
```

Currently fails with this error:

```
test.rs:10:4: 10:8 error: unexpected token: `test`
test.rs:10     test!()
               ^~~~
task 'rustc' failed at 'explicit failure', /Users/mitsuhiko/Development/rust/src/libsyntax/diagnostic.rs:76
task '<main>' failed at 'explicit failure', /Users/mitsuhiko/Development/rust/src/librustc/lib.rs:441
```

**Comment by steveklabnik** [comment]
Triage: no change, other than removing the macro_rules.

I don't believe that we're planning on improving the current macro_rules at all, instead focusing on the next-gen macro system. Also, this feels like this would require an RFC. so closing.
