### ISSUE TITLE
memory consumption unpredictible

### ISSUE THREAD

**Issue by soloturn** [rust-lang/rust#114037]
when compiling software like cosmic-epoch:
https://github.com/pop-os/cosmic-epoch

on a laptop with 8GB and default settings, rust toolchain fails when linking the binaries, as no memory is left. there is an option to only use 1 of the 4 cores, but this is a setting for both, compiling and linking. 

would be cool if by default, the rust toolchain would be aware how much memory there is and use all the threads for compile, but restrict itself to a max memory for linking.

**Comment by saethlin** [comment]
The title says memory consumption is unpredictable, but the issue says memory consumption is quite predictable. Which is it?

I'd like to reproduce the memory usage in question. How would I do that? I tried to run `just` in a clone of the linked repo and I see this:
```
mkdir -p build
/home/ben/.cargo/bin/just cosmic-settings/build-release
error: Justfile does not contain recipe `build-release`.
error: Recipe `build` failed on line 7 with exit code 1
```

**Comment by soloturn** [comment]
@saethlin, with unpredictable i ment: cannot say in advance that it uses so much memory, and does not restrict itself to the memory in the system. but you are absolutely right, running it a second time uses again more than 8GB.

would what is mentioned in the readme work for you?
```
git clone --recurse-submodules https://github.com/pop-os/cosmic-epoch
cd cosmic-epoch
just sysext
```

if you are on arch linux the following works for me, sometimes:
```
$ git clone https://aur.archlinux.org/package_name.git
CARGO_BUILD_JOBS=1 CARGO_REgistries_CRATES_IO_PROTOCOL=sparse makepkg
```
the PKGBUILD file specifies how this is run: when using 4 build jobs as the processor would allow by default, linking uses all the time more than 8gb.

**Comment by saethlin** [comment]
Hm, I can't reproduce 8 GB peak memory usage, I consistently only see 2.8 GB. I'm on Arch, running `/usr/bin/time -v makepkg` for the PKGBUILD you linked.

**Comment by soloturn** [comment]
at some point it arrives at building 3 binaries at once, and then it runs out of memory. it would be nice to allow compiling with multiple jobs, but not for linking:

```
$ CARGO_BUILD_JOBS=3 CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse makepkg

   Compiling cosmic-applet-notifications v0.1.0 (/home/src/tmp/cosmic-epoch-git/src/cosmic-epoch/cosmic-applets/cosmic-applet-notifications)
   Compiling cosmic-app-list v0.1.0 (/home/src/tmp/cosmic-epoch-git/src/cosmic-epoch/cosmic-applets/cosmic-app-list)
   Compiling cosmic-applet-network v0.1.0 (/home/src/tmp/cosmic-epoch-git/src/cosmic-epoch/cosmic-applets/cosmic-applet-network)
    Building [=======================> ] 619/630: cosmic-applet-network(bin), cosmic-app-list(bin), cosmic-applet-notifications(bin)                   
```

**Comment by soloturn** [comment]
@saethlin cosmic desktop now got split up into single components, entry point is:
https://aur.archlinux.org/packages/cosmic-session-git

for me it fell over with out of memory when building the dependent [cosmic-applets](https://aur.archlinux.org/packages/cosmic-applets-git), on 2024.07.21. am leaving the ticket closed, as it was one time.
