### ISSUE TITLE
The speed is unstable when using `powi()` with   `for`  loop. Is this a compiler optimization problem?

### ISSUE THREAD

**Issue by thermalogic** [rust-lang/rust#114232]
I tried this code:

```rust
#![allow(warnings)]
use std::time::Instant;

fn product_powers(p: f64, T: f64) -> f64 {
    const IJn: [(i32, i32, f64); 43] = [
        (1, 0, -0.17731742473213E-02),
        (1, 1, -0.17834862292358E-01),
        (1, 2, -0.45996013696365E-01),
        (1, 3, -0.57581259083432E-01),
        (1, 6, -0.5032527872793E-01),
        (2, 1, -0.33032641670203E-04),
        (2, 2, -0.18948987516315E-03),
        (2, 4, -0.39392777243355E-02),
        (2, 7, -0.43797295650573E-01),
        (2, 36, -2.6674547914087E-05),
        (3, 0, 0.20481737692309E-07),
        (3, 1, 0.43870667284435E-06),
        (3, 3, -0.3227767723857E-04),
        (3, 6, -0.15033924542148E-02),
        (3, 35, -0.040668253562649),
        (4, 1, -7.8847309559367E-10),
        (4, 2, 1.2790717852285E-08),
        (4, 3, 4.8225372718507E-07),
        (5, 7, 2.2922076337661E-06),
        (6, 3, -1.6714766451061E-11),
        (6, 16, -2.1171472321355E-03),
        (6, 35, -23.895741934104),
        (7, 0, -5.905956432427E-18),
        (7, 11, -1.2621808899101E-06),
        (7, 25, -0.038946842435739),
        (8, 8, 1.1256211360459E-11),
        (8, 36, -8.2311340897998),
        (9, 13, 1.9809712802088E-08),
        (10, 4, 1.0406965210174E-19),
        (10, 10, -1.0234747095929E-13),
        (10, 14, -1.0018179379511E-09),
        (16, 29, -8.0882908646985E-11),
        (16, 50, 0.10693031879409),
        (18, 57, -0.33662250574171),
        (20, 20, 8.9185845355421E-25),
        (20, 35, 3.0629316876232E-13),
        (20, 48, -4.2002467698208E-06),
        (21, 21, -5.9056029685639E-26),
        (22, 53, 3.7826947613457E-06),
        (23, 39, -1.2768608934681E-15),
        (24, 26, 7.3087610595061E-29),
        (24, 40, 5.5414715350778E-17),
        (24, 58, -9.436970724121E-07),
    ];
   
    let tau: f64 = 540.0 / T - 0.5;
    let pi: f64 = p;
    let mut result: f64 = 0.0;
    //let steps: [(usize, usize); 1] = [(0, 43)];
    let steps: [(usize, usize); 2] = [(0, 19),(19,43)];
    for m in 0..steps.len() {
        for k in steps[m].0..steps[m].1 {
            result += IJn[k].2 * pi.powi(IJn[k].0) * tau.powi(IJn[k].1);
            
        }
    }
    result
}

fn main() {
    let T = 300.0;
    let p = 0.0035;
    let value: f64 = product_powers(p, T);
    let now = Instant::now();
    for _ in 0..100000u128 {
        std::hint::black_box(product_powers(p, T));
    }
    let elapsed_time = now.elapsed();
    println!(
        "\t value= {} \n\t\t value Running times {:?}",
        value, elapsed_time
    );  
}
```
 In the above code, we can calculate the value of polynomial with ` IJn: [(i32, i32, f64); 43]`  in  the follow two ways：

* `let steps: [(usize, usize); 1] = [(0, 43)];`
* ` let steps: [(usize, usize); 2] = [(0, 19),(19,43)];`

We expected the computing times are the almost same in the  two ways, but we got the amazing difference.

* `let steps: [(usize, usize); 1] = [(0, 43)];` 

```
PS D:\IF97\IF97-Rust\powi_bug> cargo run -r
    Finished release [optimized] target(s) in 0.01s
     Running `target\release\powi_bug.exe`
         value= -0.0016769829198340514 
                 value Running times 214.1523ms
```
* ` let steps: [(usize, usize); 2] = [(0, 19),(19,43)];`
```
PS D:\IF97\IF97-Rust\powi_bug> cargo run -r
   Compiling powi_bug v0.1.0 (D:\IF97\IF97-Rust\powi_bug)
    Finished release [optimized] target(s) in 0.36s
     Running `target\release\powi_bug.exe`
         value= -0.0016769829198340514 
                 value Running times 58.2µs
```
The speed of  `let steps: [(usize, usize); 1] = [(0, 43)];`  is very slow, the speed of ` let steps: [(usize, usize); 2] = [(0, 19),(19,43)];` is very fast.

The speed of `powi()` with `for` loop  is unstable, 

 Is this a compiler optimization problem?

The problem is that we have no way of knowing how the compiler will optimize.
 
It may cause problems for engineering and scientific computing programming.

### Meta

```
rustc 1.71.0 (8ede3aae2 2023-07-12)
host: x86_64-pc-windows-msvc
release: 1.71.0
LLVM version: 16.0.5
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by ChrisDenton** [comment]
Hm, doing something 100000 times should be ~100000 times slower than doing it once, no? You've got `black_box` in the loop so it can't "cheat" by optimizing across iterations.

**Comment by thermalogic** [comment]
> Hm, doing something 100000 times should be ~100000 times slower than doing it once, no? You've got `black_box` in the loop so it can't "cheat" by optimizing across iterations.

Thanks!

 No matter what times, 1000,10000 or 100000, using `black_box` in the loop or not, the computing time is always greater than 

43*the computing time of ``` result+= e.2 * pi.powi(e.0) *tau.powi(e.1);```

But if we use the following coefficients and exponents, we got the expected speed.

The speed performance of  powi() function is abnormal and unstable.

```rust
const IJn: [(i32, i32, f64); 20] = [
        (0, 0, -238.72489924521),
        (0, 1, 404.21188637945),
        (0, 2, 113.49746881718),
        (0, 6, -5.8457616048039),
        (0, 22, -1.528548241314E-04),
        (0, 32, -1.0866707695377E-06),
        (1, 0, -13.391744872602),
        (1, 1, 43.211039183559),
        (1, 2, -54.010067170506),
        (1, 3, 30.535892203916),
        (1, 4, -6.5964749423638),
        (1, 10, 9.3965400878363E-03),
        (1, 32, 1.157364750534E-07),
        (2, 10, -2.5858641282073E-05),
        (2, 32, -4.0644363084799E-09),
        (3, 10, 6.6456186191635E-08),
        (3, 32, 8.0670734103027E-11),
        (4, 32, -9.3477771213947E-13),
        (5, 32, 5.8265442020601E-15),
        (6, 32, -1.5020185953503E-17),
    ];
```
By the way, no matter what coefficients and exponents are, we always get the stable speed performance with [the fast integer power methods based on the shortest addition chain](https://github.com/thermalogic/IF97) .

**Comment by ChrisDenton** [comment]
Oh sorry, I misunderstood your initial question.

**Comment by quaternic** [comment]
The code you've included only measures one time interval. You should also provide the measurements you are comparing to, and how you derived them, so that others could reproduce the issue.

It's also not clear what you claim to be a bug. To my knowledge the language provides no guarantees for how long the evaluation of some expression takes. In particular, a simpler computation may well be optimized better than a complex computation.

Your product_powers functions looks like its performance would be heavily affected by whether LLVM decides to fully unroll that loop.

**Comment by thermalogic** [comment]
>Your product_powers functions looks like its performance would be heavily affected by whether LLVM decides to fully unroll that loop.

There is the simple experiment to test the speed performance of powi() function without the `for` loop, only one sentence by one sentence. 
```rust
use std::time::Instant;

fn product_powers(p: f64, T: f64) -> f64 {
    const IJn: [(i32, i32, f64); 43] = [
        (1, 0, -0.17731742473213E-02),
        (1, 1, -0.17834862292358E-01),
         ...
        (24, 40, 5.5414715350778E-17),
        (24, 58, -9.436970724121E-07),
    ];

    let tau: f64 = 540.0 / T - 0.5;
    let pi: f64 = p;
    let mut result: f64 = 0.0;
    let mut k:usize=0;
    result += IJn[0].2 * pi.powi( IJn[0].0) * tau.powi( IJn[0].1);
    k+=1;
    result += IJn[k].2 * pi.powi( IJn[k].0) * tau.powi( IJn[k].1);
    ....
    k+=1;
    result += IJn[k].2 * pi.powi( IJn[k].0) * tau.powi( IJn[k].1);
    k+=1;
    result += IJn[k].2 * pi.powi( IJn[k].0) * tau.powi( IJn[k].1);
    result
}
```
We got the fast speed performance using powi()
```
PS D:\IF97\IF97-Rust\powi_bug\src> cargo run -r
    Finished release [optimized] target(s) in 0.00s
     Running `D:\IF97\IF97-Rust\powi_bug\target\release\powi_bug.exe`
         value = -0.0016769829198340514
                 value Running  60.6µs
````

But,using ```for```  loop,   

```
PS D:\IF97\IF97-Rust\powi_bug\src> cargo run -r
   Compiling powi_bug v0.1.0 (D:\IF97\IF97-Rust\powi_bug)
    Finished release [optimized] target(s) in 0.31s
     Running `D:\IF97\IF97-Rust\powi_bug\target\release\powi_bug.exe`
         value = -0.0016769829198340514
                 value Running  162.556ms
```

The speed with the ```for``` loop is to much lower than without any optimization of one sentence by one sentence. 

Theoretically, whether unrolling or not, the computing speed should not be lower than without any optimization?

If the speed performance of ```powi()``` with ```for``` loop is unstable, it can have a negative impact on engineering and scientific computing.

**Comment by the8472** [comment]
For starters, try  `for e in &IJn`, otherwise it copies the whole array into an owning iterator which needs to copy the whole array from the const onto the stack.

**Comment by the8472** [comment]
> Theoretically, whether unrolling or not, the computing speed should not be lower than without any optimization?

Unrolling means llvm will know exactly which value is used on each iteration, which allows it to optimize the individual invocation further. In your example (after inlining) it would know all of e, pi, tau at that point which means it could evaluate it at compile time.

Which is exactly what happens: https://rust.godbolt.org/z/qTqPe74s9

So this is an artifact of your benchmark.
