### ISSUE TITLE
feat: double dot operator in if statement

### ISSUE THREAD

**Issue by wiiznokes** [rust-lang/rust#114271]
rust offers the possibility to match only certain elements of a struct, using .. pattern:
```rust
match event {
            Event::Keyboard(keyboard::Event::KeyPressed { key_code: keyboard::KeyCode::Escape, .. }) => { },
            _ => { }
}
```
but this don't work in if statement:
```rust
if event == Event::Keyboard(keyboard::Event::KeyPressed { key_code: keyboard::KeyCode::Escape, .. }) {
}
```

**Comment by compiler-errors** [comment]
I don't think this is possible. 

In a match statement, the `Event::Keyboard(..)` is a pattern, but in the if statement, the right-hand side of the `==` needs to be a *value*. It's not possible to create a value of `Event::KeyPressed` if some of its fields are elided.

**Comment by workingjubilee** [comment]
The example given is spelled instead like:
```rust
if let Event::Keyboard(keyboard::Event::KeyPressed {
    key_code: keyboard::KeyCode::Escape,
    ..
}) = event
{
    // code
};
```


Please feel free to open an RFC if the described pattern-matching construct isn't enough, however!

**Comment by wiiznokes** [comment]
> I don't think this is possible.
> 
> In a match statement, the Event::Keyboard(..) is a pattern, but in the if statement, the right-hand side of the == needs to be a value. It's not possible to create a value of Event::KeyPressed if some of its fields are elided.

that make sense, somehow, we can't just type:
```rust
match event {
            Event::Keyboard(keyboard::Event::KeyPressed { keyboard::KeyCode::Escape, .. }) => { },
            _ => { }
}
```
by skiping initialisation of `key_code`. And it seems fair that we can't declare variable inside a `==` patern.
