### ISSUE TITLE
Inconsistent behavior across platform of split-debuginfo

### ISSUE THREAD

**Issue by roblabla** [rust-lang/rust#114215]
Setting up a release profile with stripped binaries and split debuginfo is made very complicated due to subtle differences in how `debug`, `strip` and `split-debuginfo` interact with eachother across platforms. In particular, in the following setup:

```rust
[profile.release]
split-debuginfo = "packed"
strip = "symbols"
debug = "limited"
```

Then when targetting linux/macos, a `.dwp`/`.dSYM` debug information file will be generated, while when targeting windows, no debug information file can be found. In particular, no `.pdb` file is created.

This seems to stem from how the flags propagate to linker invocation:

- On windows, [the `debuginfo` function](https://github.com/rust-lang/rust/blob/a04e649c09183b35ac0309266468c037396b6b88/compiler/rustc_codegen_ssa/src/back/linker.rs#L909) of rustc_codegen_ssa only takes `strip` into account when choosing how to generate the debug information. If it's set to any value other than None, it will not generate any debuginfo whatsoever, regardless of the value of `split-debuginfo`.
- On macos/linux, it's [`rustc_codegen_ssa::back::link_natively`](https://github.com/rust-lang/rust/blob/a04e649c09183b35ac0309266468c037396b6b88/compiler/rustc_codegen_ssa/src/back/link.rs#L987) that's responsible both for splitting debuginfo and stripping. A `.dSYM`/`.dwp` file will be created only if `debug` is set to a value other than 0, and `split-debuginfo` is set to packed. Stripping is, crucially, not a part of the equation.

I believe the behavior with the windows should be adjusted to match what is done on macos/linux. In particular, if `split-debuginfo` is set to `packed` and strip is set to `symbols`, then a `pdb` file should be generated.

### Meta

`rustc --version --verbose`:
```
rustc 1.71.0 (8ede3aae2 2023-07-12)
binary: rustc
commit-hash: 8ede3aae28fe6e4d52b38157d7bfe0d3bceef225
commit-date: 2023-07-12
host: aarch64-apple-darwin
release: 1.71.0
LLVM version: 16.0.5
```

**Comment by icedrocket** [comment]
As far as I'm concerned, `strip` should only remove debug information contained in the executable, not a separate debug file.

What I find strange is that in most environments, the `debuginfo` flag is ignored. The decision on whether or not to generate debug information is mostly being made by the `strip` flag alone.

**Comment by icedrocket** [comment]
As far as I'm concerned, `strip` should only remove debug information contained in the executable, not a separate debug file.

What I find strange is that most environments ignore the `debuginfo` flag: even if I pass the `-Cdebuginfo=none` option to rustc, the debug file is always generated. The decision on whether or not to generate debug information is mostly being determined by the `strip` flag alone. Is there any reason for this?

**Comment by segevfiner** [comment]
I believe `split-debuginfo = "unpacked"` is also effected by such inconsistencies. Would be nice to have consistent behavior. And possibly a `strip` flag that produces both an unstripped and stripped binary, though that's a separate feature.
