### ISSUE TITLE
CI: use `--filter=tree:0` for git clone of repos in CI?

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#114233]
I was working on clippy ci and came across  https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/

which sped up the clone noticeably.

Maybe we could use `--filter=tree:0` in bootstrap on ci?

Some numbers on my local machine (~7 mbs download)

`git clone --filter=tree:0 https://github.com/rust-lang/rust/   ; cd rust   ; git checkout ac747a8`
27 seconds

`git clone --depth=1`: note that this will not check out the particular commit you want
8 seconds

`git clone --depth=2000` hoping that the commit we want is just somewhere in there
3 minutes 22 seconds

`git clone` (full clone) 
2minutes 44 seconds

**Comment by Nilstrieb** [comment]
it already uses `--depth 2` (because bootstrap is buggy with `--depth 1` :D)
https://github.com/rust-lang/rust/blob/4c9ac1e93b43389890d0d77eeb479b79da62da25/.github/workflows/ci.yml#L70-L72

**Comment by matthiaskrgr** [comment]
Ah I was mostly thinking about submodules hence the bootstrap tag :sweat_smile:

**Comment by ehuss** [comment]
CI already uses parallel fetch and `--depth 1` with a sha1-in-want to fetch submodules with just a specific commit: https://github.com/rust-lang/rust/blob/483ef5f4d8de1a8ef0d9a2771b7a4a45f9846721/src/ci/scripts/checkout-submodules.sh#L63. It used to use github's src archive downloads in some cases, but we ran into errors on GitHub's side too often, so it is disabled (the speed difference was only a few seconds). It currently takes about 17s to check them all out.
