### ISSUE TITLE
Tracking Issue for `char::MIN`

### ISSUE THREAD

**Issue by clarfonthey** [rust-lang/rust#114298]
Feature gate: `#![feature(char_min)]`

This is a tracking issue for `char::MIN`. 

### Public API

```rust
impl char {
    pub const MIN: char = '\0';
}
```

### Steps / History

- [x] API change proposal (ACP)[^1]: rust-lang/libs-team#252
- [x] Implementation: #114299
- [ ] Final comment period (FCP)[^2]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html
[^2]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by Monadic-Cat** [comment]
Hey, this looks like it shouldn't be blocked by anything.

Would libs-api mind starting an FCP?

**Comment by dtolnay** [comment]
@rust-lang/libs-api:
@rfcbot fcp merge
