### ISSUE TITLE
rustc recommends removing desired str method instead of adding .to_owned()

### ISSUE THREAD

**Issue by GinoMan** [rust-lang/rust#114329]
### Summary

When you have a function that returns a String but add `.trim()` to the return value to remove extraneous whitespace, you have a type error because `.trim()` returns a `&str`. But the suggestion is not to add `.to_owned()` or `to_string()` to fix the problem but to remove the trimming behavior entirely even if that is exactly what the programmer intended.

When using cargo run, it additionally fails to show the line containing .trim() in the suggested change.

### Lint Name

error[E0308]: mismatched types

### Reproducer

I tried this code:

```rust
use std::io::stdin;

fn get_name() -> String {
	let mut your_name = String::new();
	stdin()
		.read_line(&mut your_name)
		.expect("Failed to read the line for some reason");
	your_name
		.trim()
}

fn main() {
	println!("Hello, What is your name? ");
	let your_name = get_name();
	println!("Hello, {}", your_name)
}
```

I saw this happen:

```
    Checking treehouse v0.1.0 (C:\Users\OpenM\Code\Projects\Rust\treehouse)
error[E0308]: mismatched types
 --> src\main.rs:8:2
  |
3 |   fn get_name() -> String {
  |                    ------ expected `std::string::String` because of return type
...
8 | /     your_name
9 | |         .trim()
  | |_______________^ expected `String`, found `&str`
  |
help: try removing the method call
  |
8 -     your_name
9 -         .trim()
8 +     your_name
  |

For more information about this error, try `rustc --explain E0308`.
error: could not compile `treehouse` (bin "treehouse") due to previous error
```

I expected to see this happen:

```
    Checking treehouse v0.1.0 (C:\Users\OpenM\Code\Projects\Rust\treehouse)
error[E0308]: mismatched types
 --> src\main.rs:8:2
  |
3 |   fn get_name() -> String {
  |                    ------ expected `std::string::String` because of return type
...
8 | /     your_name
9 | |         .trim()
  | |_______________^ expected `String`, found `&str`
  |
help: add .to_owned() to return a String instead of a &str
  |
8 -     your_name
9 -         .trim()
8 +     your_name
9 +         .trim().to_owned()
  |

For more information about this error, try `rustc --explain E0308`.
error: could not compile `treehouse` (bin "treehouse") due to previous error
```

### Version

```text
rustc 1.68.0 (2c8cc3432 2023-03-06)
binary: rustc
commit-hash: 2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74
commit-date: 2023-03-06
host: x86_64-pc-windows-msvc
release: 1.68.0
LLVM version: 15.0.6
```

**Comment by compiler-errors** [comment]
This suggestion should only be applied for methods that have no "side-effects" -- things like `ast_str`, `as_ptr`, etc.

**Comment by gurry** [comment]
> This suggestion should only be applied for methods that have no "side-effects" -- things like `ast_str`, `as_ptr`, etc.

How do you determine whether the method has "side-effects" or not?

Sorry if this is a stupid question. I'm an absolute newbie to rustc development, but would be keen to start on this issue.

**Comment by compiler-errors** [comment]
No, that's a fine question. The way I would do it is probably just hard-code a set of known methods. Like... `[sym::as_str, sym::as_ptr, sym::to_string]` etc.

**Comment by gurry** [comment]
Thanks :) That's what I was thinking as well.

Is it okay if I claim this issue?

**Comment by gurry** [comment]
As per my analysis the fix can go into the following `if` condition in the `suggest_remove_last_method_call()` method: https://github.com/rust-lang/rust/blob/fca59ab5f0e7df7d816bed77a32abc0045ebe80b/compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs#L253-L255 

We can add an extra check here for methods with side effects. 

After the change the condition may look like this:

```rust
 if let hir::ExprKind::MethodCall(hir::PathSegment { ident: method, .. }, recv_expr, &[], _) = expr.kind &&
            let Some(recv_ty) = self.typeck_results.borrow().expr_ty_opt(recv_expr) &&
            self.can_coerce(recv_ty, expected) &&
            self.last_call_has_no_side_effects(expr) {
           }
```
where the `last_call_has_no_side_effects()` method could be as follows:
```rust
last_call_has_no_side_effects(expr: &hir::Expr<'tcx>) -> bool {
    if (/* expr value is &str && 
        expected type is String &&
        the last called method is in [sym::as_str, sym::as_ptr, sym::to_string...] */) {
         true
    } else {
        false
    }
}
```
As a result of this change, `suggest_remove_last_method_call()` will return `false` in the situation reported in the bug and the control will eventually get to the `suggest_deref_ref_or_into()` method which should automatically suggest a conversion using `to_string()`.

With regard to tests, we could enhance this test to verify our case: https://github.com/rust-lang/rust/blob/fca59ab5f0e7df7d816bed77a32abc0045ebe80b/tests/ui/typeck/assign-non-lval-needs-deref.rs . 

We could also enhance this test: https://github.com/rust-lang/rust/blob/fca59ab5f0e7df7d816bed77a32abc0045ebe80b/tests/ui/suggestions/issue-105494.rs

Or we could write completely new tests.

What are your thoughts @compiler-errors?

**Comment by GinoMan** [comment]
> While filtering on a set of hard-coded method symbols may work for `String`, it's not a scalable solution. What we need is a general way to tell whether _any_ given method on _any_ given type could have side effects or not. Since achieving something like that would be non-trivial, I don't think we have a good solution here.
> 
> Perhaps a conservative, but likely unacceptable, option is to never suggest removal of methods. Then at least the suggestions in this context will always be correct although not necessarily most natural.

I personally think that would be the best solution. I don't really care that it's suggesting I fix the code, I care that it suggests I fix it by removing a method at all that the programmer likely intended to call. Though I get that a lot of people learn Rust by letting the compiler teach them. I'm in the same boat as a learner myself. Still, seems kinda silly for the compiler to be like "Oh, you want trimming? No! The type doesn't match. Remove the trim and just deal with the spaces." when "to_owned()" handily fixes the problem. Maybe the compiler can tell you how to convert when the solution is as simple as "to_owned()"?
