### ISSUE TITLE
return_type_notation vs return_position_impl_trait_in_trait marking return type Send on functions with arguments does not compile

### ISSUE THREAD

**Issue by softstream-link** [rust-lang/rust#114381]
**Issue** 
I understand that async traits MVP is supposed to get stabilized in 2023 and I have looked at a couple of current recommendations specifically on how to deal with marking return type of Future as Send for spanned tasks within generic functions. I understand that both of the suggestions will be part of MVP later this year. However, I have run into a problem making one of those examples to work. 

a) Failed Example uses `return_type_notation` feature gate

-  [Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f7b7006ad3b4a33db9709e20577c0841)
-  ERROR: **error: return type notation is not allowed for functions that have type parameters**

b) Working Example uses `return_position_impl_trait_in_trait` feature gate
- [Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=b19ff43404810edb617c70c80ade8730)

I am running on nightly 2023-06-27 due to latest nightly having an issue with proc-macro2 compilation
```
rustup default nightly-2023-06-27
```

**Question:**
Does `return_type_notation` has an inherent limitation which does not appear to be mentioned in the [MVP blog](https://blog.rust-lang.org/inside-rust/2023/05/03/stabilizing-async-fn-in-trait.html) or I am missing a trick to get it to work?

**Additional background:** 

I am researching a general purpose stock exchange connector, think [FIX](https://en.wikipedia.org/wiki/Financial_Information_eXchange) protocol but with binary wire serializer ex: [SoupBin](https://www.nasdaq.com/docs/SoupBinTCP%204.0.pdf) that can establish and maintain connectivity, heartbeats, etc to an arbitrary stock exchange. The idea is to use generics, traits, and data model to wire a client and  service socket that can speak in terms of protocol specific message struct's instead of byte slices and because there are many proprietary protocols it would make sense to be able to wire them by just changing the data model via generics and have a single/generic implementation of the networking layer that works across all exchanges.

The general description of the problem is I need to hand over control to the ProtocolInitHandler, one of the arguments during wiring, to send and recv a few admin messages inside the spawned task and before the application level service/recv loop kicks in, this handler is supposed to establish heartbeat handshake and check login information.

**Comment by compiler-errors** [comment]
This is not a bug. Return type notation is extremely experimental, incomplete, and intentionally does not support functions that have type parameters.
