### ISSUE TITLE
A meaningless register will be substituted in `asm!` macro

### ISSUE THREAD

**Issue by xmh0511** [rust-lang/rust#114357]
````rust
fn main() {
    let mut expect = 1;
    let mut new = 1;
	let mut b = vec![1,3];
    let mut save = b.as_mut_ptr();
    unsafe {
        asm!(
            "mov rax, rcx",
            "lock cmpxchg [{save}],{new}",
            "mov rcx, rax",
             save = in(reg) save,
             new = in(reg) new,
             inout("rcx") expect
        );
    };
    println!("aaa == {expect}");
}
use std::{arch::asm, vec};

````
In this example, `save` may be substituted with `rax` by the compiler, which does not make sense because `cmpxchg` need to compare the first operand with `rax` that is pre-seted with the value of `expect`. The compiler substituted `rax` for `save` just make the program has exceptions per https://www.felixcloutier.com/x86/cmpxchg

**Comment by PatchMixolydic** [comment]
I'm not too familiar with `asm!`, but I think `rax` has to be explicitly marked as clobbered using `out("rax") _`:

```diff
        asm!(
            "mov rax, rcx",
            "lock cmpxchg [{save}],{new}",
            "mov rcx, rax",
             save = in(reg) save,
             new = in(reg) new,
-            inout("rcx") expect
+            inout("rcx") expect,
+            out("rax") _,
        );
```

[Rust by Example](https://doc.rust-lang.org/nightly/rust-by-example/unsafe/asm.html#clobbered-registers) seems to have more information on the subject.

**Comment by talchas** [comment]
PatchMixolydic is correct here, and there's an even simpler solution of directly telling rust/llvm to use rax:  ```rust
        asm!(
            "lock cmpxchg [{save}],{new}",
             save = in(reg) save,
             new = in(reg) new,
             inout("rax") expect
        );
 ```
