### ISSUE TITLE
Cannot build Rust 1.71.1 with 1.71.0

### ISSUE THREAD

**Issue by heftig** [rust-lang/rust#114444]
Apparently Rust 1.71.0 added a check that only allows it to be built with the exact same version of Rust, or a Rust that's one minor release older.

However, this also makes it impossible to build Rust 1.71.1 with a Rust that's one micro release older (1.71.0).

```
Unexpected rustc version: 1.71.0, we should use 1.70.x/1.71.1 to build source with 1.71.1
```

Is this really what was wanted? It makes it quite hard for us (Arch Linux) to build micro upgrades.

**Comment by Mark-Simulacrum** [comment]
No, this isn't intended. We should permit building with the previous release for point releases (minor and patch).

**Comment by ehuss** [comment]
#114440 is open to fix this.

**Comment by kaniini** [comment]
#114440 has been merged I guess this can be closed?

**Comment by bjorn3** [comment]
Nominated your PR for beta backporting in case 1.72 gets a patch release too.

**Comment by Mark-Simulacrum** [comment]
1.72 is still in beta, so this'll get backported to that before the release.

**Comment by cuviper** [comment]
#114440 was backported in #114748.
