### ISSUE TITLE
`std::process::Command` Terminal execution command never returns?

### ISSUE THREAD

**Issue by dierbei** [rust-lang/rust#114460]
Creating an OCI Bundle
```shell
# create the top most bundle directory
mkdir /mycontainer
cd /mycontainer

# create the rootfs directory
mkdir rootfs

# export busybox via Docker into the rootfs directory
docker export $(docker create busybox) | tar -C rootfs -xvf -
```

I tried this code:

```rust
let mut binding = Command::new("runc");
let child = binding
    .arg("--log-format")
    .arg("json")
    .arg("create")
    .arg("-b")
    .arg("/mycontainer")
    .arg("example")
    .stdout(Stdio::piped())
    .stderr(Stdio::piped())
    .spawn()
    .unwrap();
let result = child.wait_with_output().expect("");
```

I expected to see this happen: *explanation*

![image](https://github.com/rust-lang/rust/assets/52097565/74398766-4bf3-4c42-95af-d2e45af2d352)

The hope is to perform some operations after creating.
It seems that no results have been returned.

### Meta

`rustc --version --verbose`:
```
rustc 1.73.0-nightly (474709a9a 2023-08-03)
binary: rustc
commit-hash: 474709a9a2a74a8bcf0055fadb335d0ca0d2d939
commit-date: 2023-08-03
host: x86_64-unknown-linux-gnu
release: 1.73.0-nightly
LLVM version: 16.0.5
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by dierbei** [comment]
@SpBills Yes, my purpose is to collect the stdout and stderr of the child process.

In fact, the more confusing part is that it can be created by executing commands directly on the shell terminal.

But the Rust program is blocking, which confuses me a lot.

For example, after I execute the following command on the command line, it will not block.
```shell
root@ecsHyNL:~/golang/test-rnc# runc --log-format json create -b /mycontainer example
root@ecsHyNL:~/golang/test-rnc#
```

**Comment by SpBills** [comment]
> @SpBills Yes, my purpose is to collect the stdout and stderr of the child process.
> 
> In fact, the more confusing part is that it can be created by executing commands directly on the shell terminal.
> 
> But the Rust program is blocking, which confuses me a lot.
> 
> For example, after I execute the following command on the command line, it will not block.
> 
> ```shell
> root@ecsHyNL:~/golang/test-rnc# runc --log-format json create -b /mycontainer example
> root@ecsHyNL:~/golang/test-rnc#
> ```

Huh, that's weird. I am going to give you the benefit of the doubt that you are running the command in the same environment that you are running the Rust program too.

I do get a feeling it has something to do with env variables though, as programmatic container problems often are.

After doing some testing, it looks like `Command::new` automatically inherits the parent environment. However, due to setuid, it probably has some permissions issues. Can you try `chmod u+s <file_path>` on your file?

**Comment by dierbei** [comment]
@SpBills Thanks for the suggestion, I also think it's a problem with the container.

I tried the following steps to run the rust program, still the same problem.

![image](https://github.com/rust-lang/rust/assets/52097565/af25ea86-cd60-46a3-94c8-bc1ff6896080)

I haven't thought of a solution so far.
