### ISSUE TITLE
Regression when using `#[expect(unused)]` more than once in an impl block

### ISSUE THREAD

**Issue by chinedufn** [rust-lang/rust#114416]
At some point between `rustc` `nightly-2023-03-05` (works) and `nightly-2023-07-01` (does not work) the following stopped compiling:

```rust
#![deny(warnings)]

struct X;
impl X {
    #[expect(unused)]
    fn unused();

    // This is failing with `warning: this lint expectation is unfulfilled`.
    // Only the first `#[expect(unused)]` in an impl block works as expected.
    #[expect(unused)]
    fn unused2();
}

fn main() {
    let _ = X;
}
```
```sh
RUSTFLAGS="-D warnings" cargo check
```

I have not bisected for the exact commit that broke this.

I have only tried to reproduce this error using `#[expect(unused)]`. It's possible that this is also broken for other lints.

PR: https://github.com/rust-lang/rust/pull/114417

**Comment by fmease** [comment]
Without properly double-checking this, I'm certain that this regressed in #110277 (merged April 14) which condensed multiple `dead_code` diagnostics triggered by methods into a single one for readability meddling with the affairs of `lint_reasons`.

I don't know how `lint_reasons` is implemented but if it only considers the first primary span of a (buffered) lint diagnostic, then one fix will be changing the relevant part of the code to consider *all* primary spans.

@rustbot label T-compiler A-lints F-lint_reasons
