### ISSUE TITLE
Error(((

### ISSUE THREAD

**Issue by WiktorKazmerchuk** [rust-lang/rust#114530]
### Code

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by Nilstrieb** [comment]
Do you have the backtrace and reproduction code? There's nothing we can do without it.
