### ISSUE TITLE
Full paths in type-based search don't work

### ISSUE THREAD

**Issue by notriddle** [rust-lang/rust#114522]
While searching [`vec -> usize`] works, [`vec::vec -> usize`] doesn't.

[`vec -> usize`]: https://doc.rust-lang.org/1.71.1/std/?search=vec%20-%3E%20usize
[`vec::vec -> usize`]: https://doc.rust-lang.org/1.71.1/std/?search=vec%3A%3Avec%20-%3E%20usize

**Comment by GuillaumeGomez** [comment]
Taking a look.
