### ISSUE TITLE
RISC-V Codegen Problem with type information

### ISSUE THREAD

**Issue by coastalwhite** [rust-lang/rust#114508]
Codegen for `riscv64gc-unknown-linux-gnu` sends wrong type information to LLVM.

When I compile on godbolt.org with the following flags.

[GodBolt Link](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:rust,selection:(endColumn:19,endLineNumber:2,positionColumn:19,positionLineNumber:2,selectionStartColumn:19,selectionStartLineNumber:2,startColumn:19,startLineNumber:2),source:'pub+fn+max(a:+u32+,+b:+u32)+-%3E+u32+%7B%0A++++u32::max(a,+b)%0A%7D'),l:'5',n:'0',o:'Rust+source+%231',t:'0')),k:49.165541155755804,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:r1710,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:rust,libs:!(),options:'--target%3Driscv64gc-unknown-linux-gnu+-C+target-feature%3D%2Bzbb+-C+opt-level%3D3',overrides:!(),selection:(endColumn:12,endLineNumber:5,positionColumn:1,positionLineNumber:1,selectionStartColumn:12,selectionStartLineNumber:5,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+rustc+1.71.0+(Editor+%231)',t:'0')),k:50.834458844244224,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

```
--target=riscv64gc-unknown-linux-gnu -C target-feature=+zbb -C opt-level=3
```

I tried this code:

```rust
fn max(a: u32, b: u32) -> u32 {
    u32::max(a, b)
}
```

It outputs:

```asm
example::max:
        sext.w  a1, a1
        sext.w  a0, a0
        maxu    a0, a0, a1
        ret
```

It definitely does not need to sign extend `a0` or `a1` and in fact, when we inspect the LLVM IR, it seems to assume that the numbers are `i32`s instead of `u32`s. Is this a problem with Rust's codegen output?

LLVM IR:
```
; example::max
define noundef i32 @example::max(i32 noundef %a, i32 noundef %b) unnamed_addr personality ptr @rust_eh_personality {
start:
  %.0.sroa.speculated.i = tail call i32 @llvm.umax.i32(i32 %a, i32 %b)
  ret i32 %.0.sroa.speculated.i
}

declare noundef signext i32 @rust_eh_personality(i32 noundef signext, i32 noundef signext, i64 noundef, ptr noundef, ptr noundef) unnamed_addr #1

declare i32 @llvm.umax.i32(i32, i32) #2
```

Properly optimized code would be:

```asm
example::max:
        maxu    a0, a0, a1
        ret
```

**Comment by Urgau** [comment]
> when we inspect the LLVM IR, it seems to assume that the numbers are i32s instead of u32s. Is this a problem with Rust's codegen output?

[LLVM integers](https://llvm.org/docs/LangRef.html#integer-type) types do not differentiate between signed or unsigned integers. It's the operation (ie the intrinsic) that makes the differentiation and [`llvm.umax.*`](https://llvm.org/docs/LangRef.html#llvm-umax-intrinsic) is the unsigned max variant:
> Return the smaller of %a and %b comparing the values as **unsigned integers**

It's seems to me that it's a problem with the RISC-V LLVM backend.

@rustbot labels: +A-LLVM +A-codegen +O-riscv +T-compiler -needs-triage

**Comment by rakicaleksandar1999** [comment]
According to the [documentation](https://riscv.org/wp-content/uploads/2017/05/riscv-spec-v2.2.pdf), for RV64, the registers are 64 bits wide. The arguments of the `@llvm.umax.i32` intrinsic are 32 bits wide, and the higher 32 bits of the registers `a0` and `a1` are practically unknown. The `maxu` instruction probably uses all of the 64 bits of the registers, so it is necessary to ensure that the higher 32 bits of the 64 bits wide registers have appropriate values, I would say.

**Comment by nikic** [comment]
The problem here is that we don't set `signext`/`zeroext` attributes on the arguments with the Rust ABI. signext *is* set when using `extern "C"` (as it is an ABI requirement there). It probably makes sense to set them for the Rust ABI as well, for this target.

**Comment by workingjubilee** [comment]
cc @kito-cheng @michaelmaitland @robin-randhawa-sifive Please triage and/or address this issue.

**Comment by michaelmaitland** [comment]
I don't think there is a problem here.

I think this statement is incorrect.

> Properly optimized code would be:
> ```
> example::max:
>       maxu    a0, a0, a1
>       ret
>```

As @rakicaleksandar1999 points out, on RV64, the registers are 64 bits wide. The `maxu` instruction considers the entire 64bit register size in its calculation. Therefore, we need the sign extends. On RISC-V, some instructions have `w` variants which allow us to consider only the lower 32 bits. There is no `w` variant of the `maxu` instruction.

I think we should be able to close this issue.

**Comment by SpriteOvO** [comment]
C++ can also be compiled into just one `maxu`.

https://godbolt.org/z/x9dv5v1h3

```cpp
uint32_t max(uint32_t x, uint32_t y) {
    return std::max(x, y);
}
```

```asm
max(unsigned int, unsigned int):
        maxu    a0,a0,a1
        ret
```

**Comment by michaelmaitland** [comment]
Can rust generate `signext` or `zeroext` on the function arguments? https://godbolt.org/z/8x9dodeMq

I think this should fix the problem.

**Comment by topperc** [comment]
> The problem here is that we don't set `signext`/`zeroext` attributes on the arguments with the Rust ABI. signext _is_ set when using `extern "C"` (as it is an ABI requirement there). It probably makes sense to set them for the Rust ABI as well, for this target.

@nikic where is the distinction made?

**Comment by workingjubilee** [comment]
All of the relevant code _should_ be in
- `rustc_target/src/abi/mod.rs`
- `rustc_target/src/abi/call/riscv.rs`

But if it's not it may be somewhere in:
- `rustc_abi`
- `rustc_codegen_llvm`
- `rustc_codegen_ssa`

And rustc will indeed generate `signext` if we attach that `ArgExtension`:
```
rustc_codegen_llvm/src/abi.rs
66:        ArgExtension::Sext => attrs.push(llvm::AttributeKind::SExt.create_attr(cx.llcx)),
```

**Comment by topperc** [comment]
After staring at the code a bit longer. I think the RISC-V specific code only runs via `adjust_for_foreign_abi` which is called from `fn_abi_adjust_for_abi` when the ABI isn't rust. I see there's already an X86 specific change in `fn_abi_adjust_for_abi`. Do we need to add one for RISC-V there?

**Comment by workingjubilee** [comment]
> After staring at the code a bit longer. I think the RISC-V specific code only runs via `adjust_for_foreign_abi` which is called from `fn_abi_adjust_for_abi` when the ABI isn't rust. I see there's already an X86 specific change in `fn_abi_adjust_for_abi`. Do we need to add one for RISC-V there?

Probably so!

Unless this is expected to be generally profitable, in which case we could give doing it on all platforms a go.

**Comment by michaelmaitland** [comment]
One option to fix is to add the extension in `rustc_target/src/abi/call/riscv.rs` like we do in `rustc_target/src/abi/call/loongarch.rs::extend_integer_width`.

**Comment by topperc** [comment]
> One option to fix is to add the extension in `rustc_target/src/abi/call/riscv.rs` like we do in `rustc_target/src/abi/call/loongarch.rs::extend_integer_width`.
> 
> Edit: it looks like we tried to but didn't?

Wasn't the loongarch.rs code copied from riscv.rs?

**Comment by topperc** [comment]
> > After staring at the code a bit longer. I think the RISC-V specific code only runs via `adjust_for_foreign_abi` which is called from `fn_abi_adjust_for_abi` when the ABI isn't rust. I see there's already an X86 specific change in `fn_abi_adjust_for_abi`. Do we need to add one for RISC-V there?
> 
> Probably so!
> 
> Unless this is expected to be generally profitable, in which case we could give doing it on all platforms a go.

Is not generally profitable. It's a RISC-V-ism that was also copied to LoongArch. They are the only 2 in tree targets in LLVM that don't have i32 as a legal type.

**Comment by workingjubilee** [comment]
We should probably introduce a similar fn named something like `adjust_for_rust_abi` to make it obvious that you should apply architecture-specific modifiers to the Rust ABI as well for optimization purposes (instead of mere compliance).
