### ISSUE TITLE
Typo in RefCell's section (immutable -> mutable)

### ISSUE THREAD

**Issue by somename-123** [rust-lang/rust#114555]
### Location

https://doc.rust-lang.org/std/cell/index.html#refcellt

An immutable reference to a ``RefCell``’s inner value (``&T``) can be obtained with borrow, and a mutable borrow (``&mut T``) can be obtained with ``borrow_mut``. When these functions are called, they first verify that Rust’s borrow rules will be satisfied: **any number of \*immutable\* borrows are allowed or a \*single immutable\* borrow is allowed, but never both**. If a borrow is attempted that would violate these rules, the thread will panic.

### Summary

any number of immutable borrows are allowed or a single mutable (``immutable -> mutable``) borrow is allowed, but never both

**Comment by compiler-errors** [comment]
This was fixed in #112206.
