### ISSUE TITLE
Potential typo in suggestion of E0689

### ISSUE THREAD

**Issue by sunmy2019** [rust-lang/rust#114683]
This line looks like a typo to me, should it be `f64`?

_Originally posted by @sunmy2019 in https://github.com/rust-lang/rust/pull/94963#discussion_r1289520712_

Currently, it affects line 1684.
https://github.com/rust-lang/rust/blob/832db2fcee27ee1079608ac78f82b7c14394e89b/compiler/rustc_hir_typeck/src/method/suggest.rs#L1676-L1686

**Comment by compiler-errors** [comment]
Yeah, this could be fixed.

**Comment by compiler-errors** [comment]
Ideally a test should also be crafted that shows that this missing `f64` affects an error message or something.
