### ISSUE TITLE
pthread_attr_union uses wrong types on wasi preview1 with threads

### ISSUE THREAD

**Issue by programmerjake** [rust-lang/rust#114608]
https://github.com/rust-lang/rust/blob/5697f1620de6bede6f575b51b01509d8c07830cf/library/std/src/sys/wasi/thread.rs#L19-L26

the type which should have its size compared is `c_long`, not `c_int`:

[wasi-libc's code linked in comment above](https://github.com/WebAssembly/wasi-libc/blob/a6f871343313220b76009827ed0153586361c0d5/libc-top-half/musl/include/alltypes.h.in#L108):

```c
TYPEDEF struct { union { int __i[sizeof(long)==8?14:9]; volatile int __vi[sizeof(long)==8?14:9]; unsigned long __s[sizeof(long)==8?7:9]; } __u; } pthread_attr_t;
```

since you made the commit, cc @g0djan

**Comment by g0djan** [comment]
Hey you're right, I opened a PR with a fix
