### ISSUE TITLE
RPIT hidden types can be ill-formed

### ISSUE THREAD

**Issue by aliemjay** [rust-lang/rust#114728]
The following UB shouldn't compile:
```rust
type Static<'a> = &'static &'a ();
trait Extend<'a> {
    fn extend(self, _: &'a str) -> &'static str;
}
impl<'a> Extend<'a> for Static<'a> {
    fn extend(self, s: &'a str) -> &'static str {
        s
    }
}
fn boom<'a>(arg: Static<'_>) -> impl Extend<'a> {
    arg
}
fn main() {
    let y = boom(&&()).extend(&String::from("temporary"));
    println!("{}", y);
}
```
This regressed in v1.61. I guess it is #94081.

Discovered when investigating #114572.

**Comment by lqd** [comment]
It does indeed bisect to `nightly-2022-03-31` which contains #94081:

- #95448
- #95455
- #94081
- #95466
- #95241
- #94963
- #95458
- #95425

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23114728.20RPIT.20hidden.20types.20can.20be.20ill-formed)).

@rustbot label -I-prioritize +P-critical

**Comment by apiraino** [comment]
Downgrading priority as per compiler meeting ([notes](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202023-09-21/near/392337417))
