### ISSUE TITLE
unordered console output

### ISSUE THREAD

**Issue by Leandrys-Osorio** [rust-lang/rust#114747]
I tried this code:

~~~
 1 -   // vars
 2 -   let mut guess = String::new();
 3 -
 4 -   print!("Guess the number!");
 5 -
 6 -   // take user input
 7 -   println!("Please, input your guess ");
 8 -
 9 -   io::stdin()
10 -      .read_line(&mut guess)
11 -      .expect("failed to read line :(");
12 -
13 -   println!("You guessed: {}!", guess);
~~~

I expected to see this process:

~~~
Guess the number!
Please input your guess:  18
You guessed 18!
~~~

Instead, the process is weird, i have done this exercise in another programming languages and i have never seen this order:
~~~
1 - Guess the number!
2 - 18
3 - Please, input your guess You guessed: 18
4 - !
~~~

### Meta

`rustc --version --verbose`:
```
rustc 1.71.1 (eb26296b5 2023-08-03)
binary: rustc
commit-hash: eb26296b556cef10fb713a38f3d16b9886080f26
commit-date: 2023-08-03
host: x86_64-unknown-linux-gnu
release: 1.71.1
LLVM version: 16.0.5
```

<p>
I'm a novice using rust, but i consider it is not correct, this may help others novices.
</p>
</details>

**Comment by workingjubilee** [comment]
@Leandrys-Osorio On the same platform, I get the following output:

```
./example
Guess the number!Please, input your guess 
18
You guessed: 18
!
```

The detail here is that the buffer is only flushed by `println!`, not `print!`.
Are you sure your output is what you are seeing? What glibc/kernel version are you on? It may be doing odd things due to the buffer not being flushed.

**Comment by Leandrys-Osorio** [comment]
Sorry, I don't understand to much but I wonder you want this information:

Libc = "0.2.147"

About kernel(I suppose it's my Linux kernel) = 6.2.6

And I'm sure about the output... I have copied the text snippets, and check your exclamation mark, would it be at the next line of the variable value? (check your output)

**Comment by workingjubilee** [comment]
glibc is a file on your system, usually it is located at `/usr/lib/libc.so.6` so if you put that into your terminal it will tell you its version.

My output is exactly copied from my terminal.

**Comment by workingjubilee** [comment]
Are you using a different shell, like the one in VS Code, or emacs, or zsh or fish or nushell?

**Comment by workingjubilee** [comment]
Basically, if you can type `env` and paste the results (if there is any information in there you don't want to share, you can delete it just fine) that would help a lot.

**Comment by SkiFire13** [comment]
> 1 -   // vars
>  2 -   let mut guess = String::new();
>  3 -
>  4 -   print!("Guess the number!");
>  5 -
>  6 -   // take user input
>  7 -   println!("Please, input your guess ");
>  8 -
>  9 -   io::stdin()
> 10 -      .read_line(&mut guess)
> 11 -      .expect("failed to read line :(");
> 12 -
> 13 -   println!("You guessed: {}!", guess);

Are you sure this is the code you're actually executing? The output you got would be expected lines 4-7 were:

```
4 -   println!("Guess the number!");
5 -
6 -   // take user input
7 -   print!("Please, input your guess ");
```

Notice the swapping of `println` and `print`.

In this case it's expected that the second `print` would not be shown immediately because it doesn't end a line, and stdout is line buffered by default, meaning only full lines are sent to the terminal to be shown. `print` doesn't end a line, so it gets buffered until `println!("You guessed: {}!", guess);` gets executed and ends that line.

This happens for performance reasons, but you can control this behaviour by inserting a manual "flush" to stdout (i.e. sending whatever is in the buffer to it immediately) right after the `print!("Please, input your guess ");`, by doing:

```rs
print!("Please, input your guess ");

// `flush` is a method of the `std::io::Write` trait, so bring it into scope.
use std::io::Write;
std::io::stdout().flush().expect("Couldn't flush to stdout");
```

**Comment by Leandrys-Osorio** [comment]
> 

i only found this with "whereis" command:

**Comment by Leandrys-Osorio** [comment]
do you consider that for the use of a simple print i need to use this? sorry but i consider it is a bug, i have never seen any lang that can not show the output correctly, the best part is it ask for the user entry and later show the placeholder... sorry i don't understand it

**Comment by saethlin** [comment]
The Rust issue tracker is not a support forum. Rust has an official forum: https://users.rust-lang.org/ a subreddit: https://www.reddit.com/r/rust/ a community Discord: https://discord.com/invite/rust-lang-community and an official Discord: https://discord.com/invite/rust-lang. Those are all better places to seek help in using Rust than the issue tracker.

The code you posted in this issue description does not reproduce the problem. I can say that with total certainty because it doesn't compile, and therefore it is very tempting to explain what you are reporting here as incorrect transcription of what's in your editor or pasting an old version of your code. This program _does_ produce the behavior you reported, but using different code:
```rust
use std::io;
use std::io::Read;

fn main() {
    // vars
    let mut guess = String::new();

    println!("Guess the number!");

    // take user input
    print!("Please, input your guess ");

    io::stdin()
        .read_line(&mut guess)
        .expect("failed to read line :(");

    println!("You guessed: {}!", guess);
}
```
I suggest you double-check that you have code that reproduces the behavior you find problematic, then start a conversation at any of the alternative venues I suggested. You will almost certainly find them more responsive.

**Comment by Leandrys-Osorio** [comment]
I do not consider it professional to treat a person who is trying to help in a certain way with what little they know, if I made this contribution it is because at least I have worked with other languages ​​and I know that this is not a normal way out since it is not correct that first ask for the user input and after the input is entered the "enter a number" message is displayed, but don't worry even if your way of responding to my innocent intention to help is bad I don't plan to take it much more than an answer .  If I wanted help from someone to tell me how to write code easily I would have asked anywhere since a console program is something that anyone can understand.

> The Rust issue tracker is not a support forum. Rust has an official forum: https://users.rust-lang.org/ a subreddit: https://www.reddit.com/r/rust/ a community Discord: https://discord.com/invite/rust-lang-community and an official Discord: https://discord.com/invite/rust-lang. Those are all better places to seek help in using Rust than the issue tracker.
> 
> The code you posted in this issue description does not reproduce the problem. I can say that with total certainty because it doesn't compile, and therefore it is very tempting to explain what you are reporting here as incorrect transcription of what's in your editor or pasting an old version of your code. This program _does_ produce the behavior you reported, but using different code:
> 
> ```rust
> use std::io;
> use std::io::Read;
> 
> fn main() {
>     // vars
>     let mut guess = String::new();
> 
>     println!("Guess the number!");
> 
>     // take user input
>     print!("Please, input your guess ");
> 
>     io::stdin()
>         .read_line(&mut guess)
>         .expect("failed to read line :(");
> 
>     println!("You guessed: {}!", guess);
> }
> ```
> 
> I suggest you double-check that you have code that reproduces the behavior you find problematic, then start a conversation at any of the alternative venues I suggested. You will almost certainly find them more responsive.

I do not consider it professional to treat a person who is trying to help in a certain way with what little they know, if I made this contribution it is because at least I have worked with other languages ​​and I know that this is not a normal way out since it is not correct that first ask for the user input and after the input is entered the "enter a number" message is displayed, but don't worry even if your way of responding to my innocent intention to help is bad I don't plan to take it much more than an answer .  If I wanted help from someone to tell me how to write code easily I would have asked anywhere since a console program is something that anyone can understand.

**Comment by workingjubilee** [comment]
@Leandrys-Osorio There are very few explanations for your problem, either
1. you were not reporting the code you actually used
2. the terminal/shell you were outputting to was modifying the output somehow
3. somehow, you were using a glibc with a broken `write` and `flush` implementation
4. the kernel, which handles write requests, was broken somehow

...note that I listed these in order of _decreasing_ probability.

We are not trying to be rude, but it can be very challenging to sort out a problem if you modify the reported code in **any way**. Nonetheless, I benignly assumed that your added line numbers could be removed, and that imports could be added, and everything could be wrapped in `fn main() {}`, and I *could not reproduce your report* with the code thus modified to compile. So I assumed that you were telling the truth, and I started to ask about your shell or libc or kernel.

We have also mentioned write-flushing. You say a console program is something anyone can understand, but many people are not aware of streams, buffers, and flushing. Thus they do not necessarily understand the documentation for [print!](https://doc.rust-lang.org/std/macro.print.html) and [println!](https://doc.rust-lang.org/std/macro.println.html).

Rust quite deliberately offers fairly low-level control of many things, including printing. You mention you have not encountered any difficulty with other programming languages, but most languages deliberately obfuscate and remove control of what is actually quite a complex process.

**Comment by SkiFire13** [comment]
Looks like this was discussed extensively in #23818

**Comment by Leandrys-Osorio** [comment]
> @Leandrys-Osorio There are very few explanations for your problem, either
> 
>     1. you were not reporting the code you actually used
> 
>     2. the terminal/shell you were outputting to was modifying the output somehow
> 
>     3. somehow, you were using a glibc with a broken `write` and `flush` implementation
> 
>     4. the kernel, which handles write requests, was broken somehow
> 
> 
> ...note that I listed these in order of _decreasing_ probability.
> 
> We are not trying to be rude, but it can be very challenging to sort out a problem if you modify the reported code in **any way**. Nonetheless, I benignly assumed that your added line numbers could be removed, and that imports could be added, and everything could be wrapped in `fn main() {}`, and I _could not reproduce your report_ with the code thus modified to compile. So I assumed that you were telling the truth, and I started to ask about your shell or libc or kernel.
> 
> We have also mentioned write-flushing. You say a console program is something anyone can understand, but many people are not aware of streams, buffers, and flushing. Thus they do not necessarily understand the documentation for [print!](https://doc.rust-lang.org/std/macro.print.html) and [println!](https://doc.rust-lang.org/std/macro.println.html).
> 
> Rust quite deliberately offers fairly low-level control of many things, including printing. You mention you have not encountered any difficulty with other programming languages, but most languages deliberately obfuscate and remove control of what is actually quite a complex process.

Thank you very much, at least although I don't think you're exactly right, your answer seems a bit nicer, thanks again for assuming that the numbers in front of the code is just a placeholder put on purpose, obviously no code can compile having numbers in front of it.  In any case, my concern was that it asked me to enter the data first and then it showed the text asking me to enter the data.  But I am not one to tell you whether to believe my report or not.  Thank you again and have a great day
