### ISSUE TITLE
Cannot reach root items in doctests

### ISSUE THREAD

**Issue by nvzqz** [rust-lang/rust#114733]
I tried [this code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ac3589da4b7b75485789ccd71b86e370):

```rust
/// Via `crate`:
///
/// ```
/// const VALUE: i32 = 0;
///
/// mod inner {
///     use crate::VALUE;
/// }
/// ```
///
/// Via `super`:
///
/// ```
/// const VALUE: i32 = 0;
///
/// mod inner {
///     use super::VALUE;
/// }
/// ```
fn test() {}
```

I expected to see this happen: the test successfully compiles.

Instead, this happened: the test fails to compile with:

```
---- src/lib.rs - test_super (line 13) stdout ----
error[E0432]: unresolved import `super::VALUE`
 --> src/lib.rs:17:9
  |
6 |     use super::VALUE;
  |         ^^^^^^^^^^^^ no `VALUE` in the root

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
Couldn't compile the test.
---- src/lib.rs - test_super (line 3) stdout ----
error[E0432]: unresolved import `crate::VALUE`
 --> src/lib.rs:7:9
  |
6 |     use crate::VALUE;
  |         ^^^^^^^^^^^^ no `VALUE` in the root

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
Couldn't compile the test.

failures:
    src/lib.rs - test_super (line 13)
    src/lib.rs - test_super (line 3)
```

### Meta

`rustc --version --verbose`:
```
rustc 1.71.1 (eb26296b5 2023-08-03)
binary: rustc
commit-hash: eb26296b556cef10fb713a38f3d16b9886080f26
commit-date: 2023-08-03
host: aarch64-apple-darwin
release: 1.71.1
LLVM version: 16.0.5
```

**Comment by ehuss** [comment]
Thanks for the report!  This is expected behavior. When a doctest does not contain a `main` function, all contents are wrapped inside a `main` function. Thus your first example looks something like:

```rust
fn main() {
    const VALUE: i32 = 0;

    mod inner {
        use crate::VALUE;
    }
}
```

where `VALUE` is not defined in the root. The solution is to add `fn main() {}` at the bottom of the doctest.

More information can be found in the documentation here: https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html#pre-processing-examples

**Comment by nvzqz** [comment]
Thanks! I was wondering to myself "this seems like such a fundamental thing, why has nobody has run into this?". Turns out I totally forgot about the implicit `fn main` 😅
