### ISSUE TITLE
Mutable access without mutable reference

### ISSUE THREAD

**Issue by DevNulPavel** [rust-lang/rust#114769]
Hello, i've seen this code:

```rust
async fn send_command(stream: Arc<std::net::TcpStream>, cmd: SocketCmd) -> Result<SmartSocket, String> {
    let socket = send_command(&stream, cmd)?;

    Ok(Self {
        description: socket.description,
        power_consumption: socket.power_consumption,
        on: socket.on,
        stream,
    })
}

fn send_command(mut stream: &std::net::TcpStream, cmd: SocketCmd) -> CmdError {
    if let SocketCmd::On | SocketCmd::Off = cmd {
        stream.write_all(cmd.into()).map_err(|e| e.to_string())?;
    }

    info(stream)
}
```

As you can see, there is no mutable reference for `Arc`'s inner variable, but if i add `mut` before `stream` variable (making mutable reference, not reference on mut variable) - it compiles without problems.

But it looks like compiler should not coerce `mut stream: &std::net::TcpStream` to `stream: &mut std::net::TcpStream`

Signature of `write_all` takes mutable reference:
```
fn write_all(&mut self, mut buf: &[u8]) -> Result<()>
```

Function `send_command` is `async`, but `TcpStream` is synchronous because it is small GUI learning project. It is not mistake.

### Meta

`rustc --version --verbose`:
```
rustc 1.71.1 (eb26296b5 2023-08-03)
binary: rustc
commit-hash: eb26296b556cef10fb713a38f3d16b9886080f26
commit-date: 2023-08-03
host: aarch64-apple-darwin
release: 1.71.1
LLVM version: 16.0.5
```

**Comment by erikdesjardins** [comment]
`Write` is [implemented](https://doc.rust-lang.org/stable/std/net/struct.TcpStream.html#impl-Write-for-%26TcpStream) on `&TcpStream`, so your code ends up calling `write_all` on `&mut &TcpStream`.

**Comment by DevNulPavel** [comment]
It looks like `Write` must be implemented just for `TcpStream`, not for `&TcpStream`. So single mutable access will be for `TcpStream` then.

**Comment by erikdesjardins** [comment]
> It looks like Write must be implemented just for TcpStream, not for &TcpStream.

Can you elaborate?

Do you want `impl Write for &TcpStream` to be removed? (We can't remove a stable implementation, that would be a breaking change.)

**Comment by DevNulPavel** [comment]
I'm just thinking about initial idea of implementing `Write` for reference type, not about library changes
