### ISSUE TITLE
Wide raw pointer casts let me assert marker trait bounds but not lifetime bounds

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#114798]
The following code compiles just fine:
```rust
trait Trait {}

fn assert_send(ptr: *mut dyn Trait) -> *mut (dyn Trait + Send) {
    ptr as _
}
```
This basically unsafely asserts that our underlying type is actually `Send`.

However, strangely, the following code is rejected:
```rust
fn assert_static<'a>(ptr: *mut (dyn Trait + 'a)) -> *mut (dyn Trait + 'static) {
    ptr as _
}
```
This does basically the same as the above, it unsafely assertions that our underlying type satisfies the `'static` bound. So I would expect both of these to be accepted. But somehow the borrow checker is getting in the way and says something about variance:
```
error: lifetime may not live long enough
 --> src/lib.rs:8:5
  |
7 | fn assert_static<'a>(ptr: *mut (dyn Trait + 'a)) -> *mut (dyn Trait + 'static) {
  |                  -- lifetime `'a` defined here
8 |     ptr as _
  |     ^^^^^^^^ returning this value requires that `'a` must outlive `'static`
  |
  = note: requirement occurs because of a mutable pointer to `dyn Trait`
  = note: mutable pointers are invariant over their type parameter
  = help: see <https://doc.rust-lang.org/nomicon/subtyping.html> for more information about variance
help: consider changing the trait object's explicit `'static` bound to the lifetime of argument `ptr`
  |
7 | fn assert_static<'a>(ptr: *mut (dyn Trait + 'a)) -> *mut (dyn Trait + 'a) {
  |                                                                       ~~
help: alternatively, add an explicit `'static` bound to this reference
  |
7 | fn assert_static<'a>(ptr: *mut (dyn Trait + 'static)) -> *mut (dyn Trait + 'static) {
  |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~
```
To work around this, one has to use a `transmute`, and that's always a bad sign. This even happens [in the standard library](https://github.com/rust-lang/rust/blob/852bf4e51bf260550cd1a280d2146f1c0641b1e8/library/std/src/thread/mod.rs#L565-L567).

Cc @rust-lang/types

**Comment by lcnr** [comment]
I expect the following to happen here:

- the cast works in HIR typeck
- during MIR building, we throw out identity casts. This looks at the types returned by HIR typeck which have erased regions
- this means the MIR used by borrowck doesn't have cast

I think this should be fixable :thinking:

**Comment by lukas-code** [comment]
related: https://github.com/rust-lang/rust/issues/113257

**Comment by RalfJung** [comment]
Oh interesting, so this fails even when the pointers are not wide -- yes that definitely looks like a bug to me.

Closing as a duplicate of https://github.com/rust-lang/rust/issues/113257.
