### ISSUE TITLE
TAIT: concrete type differs from previous defining opaque type use at the same location

### ISSUE THREAD

**Issue by xxchan** [rust-lang/rust#114727]
"previous use here" seems to be the same location as the error?

```rust
error: concrete type differs from previous defining opaque type use
   --> src/storage/src/table/batch_table/storage_table.rs:505:9
    |
505 |         Ok(iter)
    |         ^^^^^^^^ expected `StorageTableInnerIter<S, SD>`, got `impl Stream<Item = std::result::Result<(Vec<u8>, OwnedRow), error::StorageError>> + 'static`
    |
note: previous use here
   --> src/storage/src/table/batch_table/storage_table.rs:412:54
    |
412 |       ) -> StorageResult<StorageTableInnerIter<S, SD>> {
    |  ______________________________________________________^
413 | |         let cache_policy = match (
414 | |             encoded_key_range.start_bound(),
415 | |             encoded_key_range.end_bound(),
...   |
505 | |         Ok(iter)
506 | |     }
    | |_____^

warning: `risingwave_storage` (lib) generated 1 warning
```

Note: tested latest `2023-08-11`, and reports same error.

Tested on this commit https://github.com/risingwavelabs/risingwave/commit/9d3e587b0aeb2b0f4236953b6015a6f1b864c1bf

```
cargo build -p risingwave_storage
```
(Sorry for not having a minimal example yet)

---

Bisect rustc and found the regression commit:

searched nightlies: from nightly-2023-06-16 to nightly-2023-07-08
regressed nightly: nightly-2023-06-18
searched commit range: https://github.com/rust-lang/rust/compare/6bba061467f7c2cab04b262b95eb67bf89265587...3b2073f0762cff4d3d625bb10017e0ce4e7abe50
regressed commit: https://github.com/rust-lang/rust/commit/0cc541e4b2eb957e71490cf44df1ac09f6d18132

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.6</summary>

Host triple: aarch64-apple-darwin
Reproduce with:
```bash
cargo bisect-rustc --start 2023-06-16 --end 2023-07-08 -- build -p risingwave_storage 
```
</details>

---

Source code here

https://github.com/risingwavelabs/risingwave/blob/tygg-bump-toolchain-20230728/src/storage/src/table/batch_table/storage_table.rs#L386-L388

https://github.com/risingwavelabs/risingwave/blob/9d3e587b0aeb2b0f4236953b6015a6f1b864c1bf/src/storage/src/table/batch_table/storage_table.rs#L404-L504

**Comment by compiler-errors** [comment]
I believe this is the same issue as #114909, so it should be fixed as #114914
