### ISSUE TITLE
  error[E0583]: file not found for module `sys`   

### ISSUE THREAD

**Issue by istommao** [rust-lang/rust#114832]
error[E0583]: file not found for module `sys`
  
cargo 1.73.0-nightly (7e9de3f4e 2023-08-13)
rustc 1.73.0-nightly (180dffba1 2023-08-14)

<img width="1468" alt="image" src="https://github.com/rust-lang/rust/assets/5070879/ead70921-3ebd-41dd-a78e-7aa50ed0283f">

**Comment by saethlin** [comment]
What are you trying to compile, and how are you trying to compile it?

**Comment by istommao** [comment]
> What are you trying to compile, and how are you trying to compile it?


substrate node template project, cargo build then report this issue
https://github.com/Generative-Labs/Substrate-HotStuff

feat/hotstuff branch

**Comment by vimalkuriensam** [comment]
Any update on this? I'm facing the same issue @istommao

**Comment by vimalkuriensam** [comment]
Any update on this? I am facing the same issue @istommao
