### ISSUE TITLE
Wrong memory layout drawing in Vec's documentation?

### ISSUE THREAD

**Issue by dennisorlando** [rust-lang/rust#114806]
### Location

https://doc.rust-lang.org/std/vec/struct.Vec.html

### Summary

Hi, does this image have the capacity and the length inverted?
![image](https://github.com/rust-lang/rust/assets/47061464/f906b4db-74d6-41a1-ad35-e1b2dfe91fbf)

Context: I'm fiddling with unsafe pointer arithmetics with this code, which does the opposite of the shown scheme:
```rust
let pixels_pointer = std::mem::transmute::<*const Vec<Pixel>, *mut usize>(pointer);
std::ptr::write::<usize>(pixels_pointer.offset(1), 2); // changes the capacity
std::ptr::write::<usize>(pixels_pointer.offset(2), 2); //changes the length
println!("New length and capacity: {}, {}", 
```

**Comment by ChrisDenton** [comment]
The exact layout of `Vec` is an implementation detail and not something that can be relied upon.

**Comment by the8472** [comment]
Use [from_raw_parts](https://doc.rust-lang.org/nightly/std/vec/struct.Vec.html#method.from_raw_parts) and [into_raw_parts](https://doc.rust-lang.org/nightly/std/vec/struct.Vec.html#method.into_raw_parts) to take apart a Vec. Well, the latter is unstable but the implementation can be reproduced with public methods.

**Comment by scottmcm** [comment]
Directly under that picture it says

> Note: the ABI is not stable and Vec makes no guarantees about its memory layout (including the order of fields).

So I'm going to close this, seeing as how there's already a note there that this is illustrative, not normative.
