### ISSUE TITLE
higher-ranked lifetime error

### ISSUE THREAD

**Issue by asquared31415** [rust-lang/rust#114866]
### Code

```Rust
fn assert_all<F, T>(_f: F)
where
    F: FnMut(&String) -> T,
{
}

fn id(x: &String) -> &String {
    x
}

fn main() {
    assert_all::<_, &String>(id);
}
```
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=459ad1e3e4f5951d344bfe3448119343)

### Current output

```Shell
error: higher-ranked lifetime error
  --> src/main.rs:12:5
   |
12 |     assert_all::<_, &String>(id);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^
```

### Rationale and extra context

Found while minimizing #114849.  The turbofish is crucial to reproducing this error, otherwise compilation fails as seen in that issue.

I don't know enough to say what the error *should* be, but it shouldn't be this.

**Comment by jackh726** [comment]
I'm going to work on this (but going to use it as an example for a talk, so may take ~a month)
