### ISSUE TITLE
Add information about cargo-pgo to the Profile-Guided Optimization documentation

### ISSUE THREAD

**Issue by zamazan4ik** [rust-lang/rust#114995]
### Location

https://doc.rust-lang.org/rustc/profile-guided-optimization.html

### Summary

I think would be nice to mention [cargo-pgo](https://github.com/Kobzol/cargo-pgo) in the Rustc Profile-Guided Optimization documentation. With `cargo-pgo` it's much easier to apply PGO to the Rust programs (I did it many times). I suggest adding the information about `cargo-pgo` to the mentioned above page. Even if this project does not belong directly to Rustc or Cargo - it's still worth mentioning.

@Kobzol - ping you as the `cargo-pgo` author.

P.S. I am creating the issue here since not sure where it should go. Maybe we want to mention `cargo-pgo` in the Cargo book as well.

**Comment by meysam81** [comment]
I don't know if this is already approved, but in case it is, here's my effort for a chance of contribution.

**Comment by Kobzol** [comment]
Well, I would of course like it to be mentioned in the docs :) I'm not sure what's the policy on linking to community maintained Cargo subcommands though (if there is any).
