### ISSUE TITLE
Regression of TAIT with generics

### ISSUE THREAD

**Issue by xxchan** [rust-lang/rust#114909]
I tried this code:

```rust
#![feature(type_alias_impl_trait)]

struct Foo;

impl Trait for Foo {}
pub trait Trait {}

pub type TAIT<T> = impl Trait;

async fn foo<T>() -> TAIT<T> {
    Foo
}
```

It failed with a confusing error message. (error: concrete type differs from previous defining opaque type use, at the same location)

```rust
error: concrete type differs from previous defining opaque type use
  --> src/main.rs:11:5
   |
11 |     Foo
   |     ^^^ expected `TAIT<T>`, got `Foo`
   |
note: previous use here
  --> src/main.rs:10:30
   |
10 |   async fn foo<T>() -> TAIT<T> {
   |  ______________________________^
11 | |     Foo
12 | | }
   | |_^
```

---

I'm trying to minimize https://github.com/rust-lang/rust/issues/114727, and found the problem.

`nightly-2023-06-17` compiles, but `nightly-2023-06-18` fails. Although not 100% sure, I think it's caused by the same problem as #114727 (regression caused by https://github.com/rust-lang/rust/pull/108860)

**Comment by xxchan** [comment]
cc @oli-obk

**Comment by compiler-errors** [comment]
I can work on this, and then I can test if it fixes the other issue too.
