### ISSUE TITLE
Better compiler errors when trying to return a mismatching type?

### ISSUE THREAD

**Issue by Vdevelasco** [rust-lang/rust#114916]
This has happened to me a couple of times, I've added a match expression and forgot a semicolon. The compiler correctly guesses that it's a possibility that this is the case, however I think it would be even more useful if it told explicitly in which function the return statement is failing. This is mainly a suggestion for improving speed while debugging as that might be the intended return value. Maybe adding not only the line where the semicolon should be but also where the function is declared? A humble suggestion from someone who is is still learning the language. Please let me know if that could cause trouble.

**Comment by compiler-errors** [comment]
Can you give an example, preferably a link to https://play.rust-lang.org, that describes a minimized version of what code you were confused about?

**Comment by estebank** [comment]
@Vdevelasco please feel free to reopen this ticket with more information on what you're currently seeing and what you would like to see. For now, I will close it as we do not have enough context for us to act on it.
