### ISSUE TITLE
Incorrect handling of trait associated type

### ISSUE THREAD

**Issue by xlc** [rust-lang/rust#114926]
I tried this code:

https://github.com/xlc/trait-bug

I expected to see this happen: compiles

Instead, this happened: 

```
   Checking foo v0.1.0 (/Users/xiliangchen/projects/acala/trait-bug/foo)
error[E0119]: conflicting implementations of trait `From<Foo>` for type `Foo`
  --> foo/src/lib.rs:11:1
   |
11 | impl From<<baz::Baz as ::baz::BazTrait>::BazType> for Foo {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: conflicting implementation in crate `core`:
           - impl<T> From<T> for T;

For more information about this error, try `rustc --explain E0119`.
error: could not compile `foo` (lib) due to previous error
```

### Meta

`rustc --version --verbose`:
```
rustc 1.73.0-nightly (07438b092 2023-08-16)
binary: rustc
commit-hash: 07438b0928c6691d6ee734a5a77823ec143be94d
commit-date: 2023-08-16
host: aarch64-apple-darwin
release: 1.73.0-nightly
LLVM version: 17.0.0
```

Note that the code will compile if all the types are in a single crate.

**Comment by eval-exec** [comment]
May this related? https://stackoverflow.com/questions/37347311/how-is-there-a-conflicting-implementation-of-from-when-using-a-generic-type

**Comment by xlc** [comment]
Not exactly. `<baz::Baz as ::baz::BazTrait>::BazType>` is a concrete type that is always `u32`. Also the code compiles if `baz::Baz` is defined in the same crate.

**Comment by xlc** [comment]
Dup of https://github.com/rust-lang/rust/issues/51445
