### ISSUE TITLE
Function pointer signature containing `&mut T` should work in const context

### ISSUE THREAD

**Issue by nayeemrmn** [rust-lang/rust#114994]
Proposing to extract this from #57349.

The following examples shouldn't error:
```rust
const fn get_some_fn() -> fn(&mut String) {
  String::clear
}

const fn use_const_fn(_f: fn(&mut String)) {
  ()
}

const fn some_const_fn() {
  let _f: fn(&mut String) = String::clear;
}

// mutable references are not allowed in constant functions      x3
```

While this has been considered part of #57349 for a while, it's also been acknowledged as a bug and suggested by @RalfJung to address separately ahead of stabilizing `const_mut_refs`. Indeed it's surprising for users that this would count as handling a mutable reference in const contexts.

See:
https://github.com/rust-lang/rust/issues/57349#issuecomment-1266769993
https://github.com/rust-lang/rust/issues/57349#issuecomment-1684898459

**Comment by RalfJung** [comment]
Cc @rust-lang/wg-const-eval 

Fixing this requires changing [this logic](https://github.com/rust-lang/rust/blob/6ac5b3dc6088c1b85aff318e876beba6333ee542/compiler/rustc_const_eval/src/transform/check_consts/check.rs#L349) to skip traversing things inside function pointers. I'm not sure what the best way to achieve that is.

**Comment by kaffarell** [comment]
Is there any reason returning a function trait object (e.g. `dyn Fn`, `dyn FnOnce`, etc.) does not work? It works with the `const_mut_refs` feature, but IMO it should have been pulled out like the function pointers. For example this does not compile:
```rust
fn something(_s: &mut String) {
}

const fn unwrap_cool() -> &'static dyn Fn(&mut String) {
    &something
}
```

**Comment by RalfJung** [comment]
We didn't exhaustively look through all cases that we can exempt here.

Anyway, `const_mut_refs` is on the [path to stabilization](https://github.com/rust-lang/rust/pull/129195), so this question will be moot soon. :)
