### ISSUE TITLE
Nightly Rust suggests `.as_ref()` on the left-hand side of the assignment

### ISSUE THREAD

**Issue by GoldsteinE** [rust-lang/rust#114925]
### Code

```Rust
struct Lol {
    x: Option<String>,
}

fn lmao(lol: &mut Lol, x: Option<&String>) {
    lol.x = x.clone();
}
```

### Current output

```
error[E0308]: mismatched types
 --> src/lib.rs:6:13
  |
6 |     lol.x = x.clone();
  |     -----   ^^^^^^^^^ expected `Option<String>`, found `Option<&String>`
  |     |
  |     expected due to the type of this binding
  |
  = note: expected enum `Option<String>`
             found enum `Option<&String>`
help: use `Option::as_ref` to convert `Option<String>` to `Option<&String>`
  |
6 |     lol.x.as_ref() = x.clone();
  |          +++++++++

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` (lib) due to previous error
```

### Desired output

```
error[E0308]: mismatched types
 --> src/lib.rs:6:13
  |
6 |     lol.x = x.clone();
  |     -----   ^^^^^^^^^ expected `Option<String>`, found `Option<&String>`
  |     |
  |     expected due to the type of this binding
  |
  = note: expected enum `Option<String>`
             found enum `Option<&String>`
help: use `Option::cloned` to clone the value inside the `Option`
  |
6 |     lol.x = x.clone().cloned();
  |                      +++++++++

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` (lib) due to previous error
```

### Rationale and extra context

Playground link: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=6f5723a2dea54642823935b3683d3480

### Anything else?

That’s a regression from stable to nightly. Playground’s stable (1.71.1) gives the desired output, but playground’s nightly (1.73.0-nightly (2023-08-16 07438b0928c6691d6ee7)) does not.

**Comment by GoldsteinE** [comment]
It’s not present in beta, so the left bound of the bisection is 1.72.0-beta.8 (2023-08-12 598a0a3cb36343e08bc6). I’ll try to run it later today.

**Comment by Urgau** [comment]
The regression most probably comes from https://github.com/rust-lang/rust/pull/114052

**Comment by apiraino** [comment]
I'm trying to bisect but cargo cargo-bisect dies on me :/ So far, I'm also seeing commit 18fa7b9104aad0cbaba6d9aff8e19d6b96eedcef as probably culprit so #114052 seems to make sense 

cc: @clubby789

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23114925.20Nightly.20Rust.20suggests.20.60.2Eas_ref.28.29.60.20on.20the.20left-hand.20.E2.80.A6)).

@rustbot label -I-prioritize +P-medium -E-needs-bisection
