### ISSUE TITLE
#[start] maybe not behaving as expected for x86_64-unknown-none

### ISSUE THREAD

**Issue by tsatke** [rust-lang/rust#115072]
I tried to compile this code for `x86_64-unknown-none`:

```rust
#![feature(start)]
#![no_std]
#![no_main]

#[start]
pub fn my_start(x:isize, y:*const *const u8) -> isize {
    loop {}
}

// panic handler omitted
```

I expected to see this happen: 

The resulting elf file should have a `.text` section and an entry point, that actually points to code in the loaded elf image.

Instead, this happened:

No `.text` section, entry point is 0 and doesn't point to instructions.

I only get the `.text` and an actually executable image with the following code:

```rust
#![no_std]
#![no_main]

#[no_mangle]
pub fn _start() {
    loop {}
}

#[start]
pub fn my_start(x:isize, y:*const *const u8) -> isize {
    loop {}
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.74.0-nightly (5c6a7e71c 2023-08-20)
binary: rustc
commit-hash: 5c6a7e71cd66705c31c9af94077901a220f0870c
commit-date: 2023-08-20
host: aarch64-apple-darwin
release: 1.74.0-nightly
LLVM version: 17.0.0
```

Either I don't understand what `#[start]` should actually do, or maybe it doesn't behave as expected on `x86_64-unknown-none`? I don't get any linker errors, warnings or similar, I just can't load and execute the elf file when using `#[start]`, but it works without any issues when using the above code with `#[no_mangle]`.

### Additional Info
I'm using no extra linker or compiler flags, no custom stuff besides `bindeps` in my `.cargo/config.toml`, no custom link script or anything.
I build with `cargo build --target x86_64-unknown-none` and that's it.

**Comment by bstrie** [comment]
Is the behavior here inconsistent with the documentation on the following page? https://doc.rust-lang.org/nightly/rustc/platform-support/x86_64-unknown-none.html

**Comment by tsatke** [comment]
@bstrie yes, however I think the only relevant part is

> This target generates binaries in the ELF format. Any alternate formats or special considerations for binary layout will require linker options or linker scripts.

And that doesn't explicitly cover executables. The generated binary is marked a PIE (position independent executable), but it is not executable.

**Comment by bjorn3** [comment]
`#[start]` doesn't have an effect when `#![no_main]` is used. `#[start]` defines which function the compiler generated `main` function should call. `#![no_main]` causes the compiler to not generate a `main` function at all. There is no way to define the ELF entry point to be anything other than the default `_start` other than using something like `-Clink-args="-e main"` to directly tell the linker about it. In most cases it is not possible for the ELF entry point to directly point to a Rust or C function as for example the stack wouldn't be set up yet. Instead the expectation is that a CRT object defines `_start` and calls `main` after setting up everything necessary to safely call into Rust or C. Normally this CRT object is part of the libc you use, but for x86_64-unknown-none you have to provide it yourself as there is no libc.

**Comment by tsatke** [comment]
Understood, thanks for the explanation!
