### ISSUE TITLE
Stabilizing panic_immediate_abort

### ISSUE THREAD

**Issue by mwcampbell** [rust-lang/rust#115022]
Forgive me if there's already a tracking issue for this, but I haven't been able to find one. I see that the build script for the precompiled serde_derive binary uses this feature (and thus a nightly toolchain), so there's clearly demand for it. How can we users help get it stabilized?

**Comment by ChrisDenton** [comment]
serde_derive is using the `build-std` feature. See: https://github.com/serde-rs/serde/blob/bfcd44704f847ac5a9f3072e102e803b5ebbef31/precompiled/build.sh#L12-L14

This is where the standard library is rebuilt instead of using the pre-built rlibs. It is unlikely that build-std is going to be stabilized any time soon but if you'd like to help out or track its progress then see https://github.com/rust-lang/wg-cargo-std-aware/issues

**Comment by ChrisDenton** [comment]
That said, I would ask why you want it stabilized? There may be other designs that may achieve your goals.

For example, I have previously discussed with some devs that I'd love a way to turn off std backtraces and that whole machinery. Perhaps a rustc flag like `-C backtrace=off`, or maybe an attribute similar to `global_alloc` that allows plugging in your own backtrace stuff (which could just be a empty function). But I need to get round to writing up a proposal and figuring out the details.

**Comment by mwcampbell** [comment]
A way to override the panic handler while still using std, as one can override the global allocator, would be good enough for me.

**Comment by bjorn3** [comment]
This can't be stabilized without also stabilizing rebuilding the standard library in the first place, which still has basic issues like trying to compile with `panic = "abort"` on a panic=unwind target being broken.

**Comment by ChrisDenton** [comment]
Closing this as I think stabilizing build-std features are better tracked as part of that effort. Happy to reopen if people disagree.

**Comment by ruuda** [comment]
Is there an issue I can subscribe to for staying up to date with the stabilization effort? I was able to find that build-std is part of https://github.com/rust-lang/wg-cargo-std-aware, but I don’t see an issue about `panic_immediate_abort` there.
