### ISSUE TITLE
LLVM 18 breakage: `failed to get bitcode from object file` after LLVM 6b539f5eb8e

### ISSUE THREAD

**Issue by durin42** [rust-lang/rust#115069]
Filing this to keep track of llvm/llvm-project@6b539f5eb8ef1d3a3c87873caa2dbd5147e1adbd breaking `tests/codegen/lto-removes-invokes.rs` and `tests/codegen/sanitizer/sanitizer-recover.rs#MSAN-RECOVER-LTO`, both with the message `error: failed to get bitcode from object file for LTO (Bitcode section not found in object file)`. 

In https://reviews.llvm.org/D152973#4520240 it sounds like we should already have an idea of what to do here, but I also have the vague notion it might not be a quick fix, so I'm opening a bug that I can refer the handful of Rust-at-HEAD/LLVM-at-HEAD users to until we get this resolved.

**Comment by nikic** [comment]
Can be closed as https://github.com/rust-lang/rust/pull/115641 has landed?

**Comment by durin42** [comment]
Yep! Thanks!
