### ISSUE TITLE
platform support has sparc-unknown-none-elf on the wrong tier

### ISSUE THREAD

**Issue by jonathanpallant** [rust-lang/rust#115063]
https://doc.rust-lang.org/nightly/rustc/platform-support.html lists sparc-unknown-none-elf as Tier 2, but it's Tier 3 as you don't build libcore for it.

My bad - no idea how I managed to put it in the wrong table. It's not even alphabetically in the right place.

**Comment by jonathanpallant** [comment]
paging @workingjubilee. Sorry!

**Comment by workingjubilee** [comment]
lmao whoops.
