### ISSUE TITLE
Add a rustdoc commandline parameter to disable generation of source code pages

### ISSUE THREAD

**Issue by sdroege** [rust-lang/rust#115060]
Kind of related to https://github.com/rust-lang/rust/issues/67804 and the [`html_no_source`](https://doc.rust-lang.org/nightly/rustdoc/write-documentation/the-doc-attribute.html#html_no_source) attribute.

The behaviour would be the same as the latter but wouldn't require any source code changes. My use-case here is to generate docs on the CI and reduce the size (400MB just for docs for each version is a bit much), but if people want to generate docs locally they should still be able to get the source code pages if they want.

@GuillaumeGomez suggested to create an issue for this.

**Comment by GuillaumeGomez** [comment]
To reduce the global documentation size, I suggested in https://github.com/rust-lang/rust/issues/112379 to group items that don't have impls by kinds. Would require an RFC though.

In any case, I think it's a good idea to add an option to have this done in the command line.
