### ISSUE TITLE
std::fs::copy doesn't work on windows 11

### ISSUE THREAD

**Issue by AllenDang** [rust-lang/rust#115132]
I tried this code:

```rust
fn main() -> std::io::Result<()> {
    let current_dir = std::env::current_exe()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf();
    std::fs::copy(
        current_dir
            .join("patches")
            .join("patch")
            .join("replace.txt"),
        current_dir.join("test").join("replace.txt"),
    )?;

    Ok(())
}
```

I expected to see this happen: the "./patches/path/replace.txt" is copied to "./test/replace.txt".

Instead, this happened: error occurred with "cannot find file".

I've tested both on macOS and windows, on macOS it works as expected, on windows 11 it always failed.

### Meta

macOS compiler
`rustc --version --verbose`:
```
rustc 1.71.1 (eb26296b5 2023-08-03)
binary: rustc
commit-hash: eb26296b556cef10fb713a38f3d16b9886080f26
commit-date: 2023-08-03
host: aarch64-apple-darwin
release: 1.71.1
LLVM version: 16.0.5
```

windows compiler
```
rustc 1.71.1 (eb26296b5 2023-08-03)
binary: rustc
commit-hash: eb26296b556cef10fb713a38f3d16b9886080f26
commit-date: 2023-08-03
host: aarch64-pc-windows-msvc
release: 1.71.1
LLVM version: 16.0.5
```

**Comment by AllenDang** [comment]
Here is the test data with windows executable built with `--release`.

[test.zip](https://github.com/rust-lang/rust/files/12419677/test.zip)

**Comment by ChrisDenton** [comment]
I'm seeing files like `replace.txt.txt`?

**Comment by AllenDang** [comment]
Oh my!!! I hate windows's hidden ext feature! I'm so stupid!
