### ISSUE TITLE
Cannot write ICE files to disk on Windows hosts

### ISSUE THREAD

**Issue by Enet4** [rust-lang/rust#115180]
While investigating the ICE in #115179, I saw that every `rustc` attempt at writing the ICE details to a file (first implemented in #108714) would fail on my Windows machine with error messages of this kind:

```none
warning: the ICE couldn't be written to `C:\Users\User\Dev\dicom-rs\rustc-ice-2023-08-24T17:31:34.9401158Z-146952.txt`: The filename, directory name, or volume label syntax is incorrect. (os error 123)
```

The timestamp format used for the file name separates time components with colons, and Windows is generally finicky about having colons in file names since it is already employed as the drive unit delimiter.

Could there be a change in the file name format for better compatibility, at least when running rustc on a Windows host?

### Meta

`rustc --version --verbose`:
```
rustc 1.74.0-nightly (249595b75 2023-08-23)
binary: rustc
commit-hash: 249595b7523fc07a99c1adee90b1947739ca0e5b
commit-date: 2023-08-23
host: x86_64-pc-windows-msvc
release: 1.74.0-nightly
LLVM version: 17.0.0
```
</p>
</details>

**Comment by Fulgen301** [comment]
> since it is already employed as the drive unit delimiter.

[And for NTFS alternate data streams.](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-fscc/c54dec26-1551-4d3a-a0ea-4fa40f848eb3)

**Comment by matthiaskrgr** [comment]
cc @estebank

**Comment by estebank** [comment]
Yes, we can change the format.
