### ISSUE TITLE
Missing tracking information on generated dlls for windows

### ISSUE THREAD

**Issue by jmecosta** [rust-lang/rust#115161]
Hi,

as u can see the dlls generated by #[no_mangle] on windows contains no version information
<img width="269" alt="image" src="https://github.com/rust-lang/rust/assets/1041352/94d9e625-c05c-4810-96bf-384bafcd541a">

Im having trouble clients of this library to accept it as it is. I dont want to include the version in the name because i want to do in place replacements of the DLL since the APIs are compatible.

Is there a general way of doing this? 

thanks

**Comment by bjorn3** [comment]
Are you using the dylib or cdylib crate type? If the dylib type you can't do in place replacements as the rust abi is unstable. If the cdylib crate type you can provided that the exported C ABI stays compatible just like in C and C++.

The version identifier comes from the manifest embedded in the .exe/.dll file. Rustc doesn't generate any manifest. You can generate one yourself and link it using eg the [embed-manifest](https://docs.rs/embed-manifest/latest/embed_manifest/) crate. Specifically [`ManifestBuilder::version()`](https://docs.rs/embed-manifest/latest/embed_manifest/manifest/struct.ManifestBuilder.html#method.version) allows setting the version to be put in the manifest.

You can use env vars like `CARGO_PKG_VERSION` to read information like the version from the `Cargo.toml` file: https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates

**Comment by jmecosta** [comment]
hi,

thanks for the reply, im using crate-type = ["cdylib"] and yes that the idea.

for the embed-manifest, apparently requires a bin section in the toml file, which in my case its a shared dll doesnt apply. So it doesnt work. Also the doc, i could find a way to configure it to bypass bin.

Ive found a good alternative, which was what i was hoping to find. https://github.com/nabijaczleweli/rust-embed-resource, this is more approximate to how windows vc++ handles versions of dlls, so you can simply create a resource.rc file containing the the version elements you require.

But anything thanks for the tip. 
regards
