### ISSUE TITLE
On method chain expression failure, look for missing method in earlier segments of the chain

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#115222]
### Code

```Rust
struct A;
struct B;
struct C;
struct D;

impl A {
    fn b(&self) -> B { B }
}
impl B {
    fn c(&self) -> C { C }
    fn foo(&self) {}
}
impl C {
    fn d(&self) -> D { D }
}
impl D {
    fn e(&self) {}
}

fn main() {
    A.b().c().d().foo();
}
```

### Current output

```Shell
error[E0599]: no method named `foo` found for struct `D` in the current scope
  --> src/main.rs:21:19
   |
4  | struct D;
   | -------- method `foo` not found for this struct
...
21 |     A.b().c().d().foo();
   |                   ^^^ method not found in `D`
```

### Desired output

```Shell
error[E0599]: no method named `foo` found for struct `D` in the current scope
  --> src/main.rs:21:19
   |
2  | struct B;
   | -------- method `foo` found for this struct
3  | struct C;
4  | struct D;
   | -------- method `foo` not found for this struct
...
21 |     A.b().c().d().foo();
   |     -----         ^^^ method not found in `D`
   |     |
   |     method `foo` available after this method call
```

### Anything else?

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=5d27c80570db4a4005f5ff3d4ea94e0e

**Comment by estebank** [comment]
Hi @iSwapna! There are two things at play here: typeck which you just found and the HIR (high level intermediate representation) which holds the "hydrated AST", a fancy way of saying "every component bit of code with syntax desugaring applied and access to their type information so far". So what you want to do is look at 468 `if let SelfSource::MethodCall(rcvr_expr) = source {` and use that `rcvr_expr` to go up the method chain (the receiver is `foo` in `foo.bar()`, if you have `foo.bar().baz()` you'll have a `MethodCall(receiver: foo.bar(), path_segment: baz, args: [])`). You can look at https://github.com/rust-lang/rust/blob/9f48a8544799c65a597302886d5143456fcb340f/compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs#L3731 for an example of us doing exactly this. The main difference will be that instead of creating new "obligations" and calling `can_eq` we'll be looking at the`expr_ty_adjusted_opt` for each receiver and then call `probe_for_name` with the method name that failed on each of those receivers (like we do in `note_derefed_ty_has_method`). Do not hesitate to ask more questions!

**Comment by iSwapna** [comment]
I am playing with `err.span_note` in the first instance to understand how to adjust it to generate the correct `type`. But looks like I need to use a different level of diagnostic message to display the first part of expected output:

```
 | -------- method `foo` found for this struct
 ```
 
 How do I do that?

**Comment by iSwapna** [comment]
Opened a PR as suggested by @oli-obk here: https://github.com/rust-lang/rust/pull/115229

**Comment by Dylan-DPC** [comment]
Current output: 
```
   |
4  | struct D;
   | -------- method `foo` not found for this struct
...
21 |     A.b().c().d().foo();
   |       ---         ^^^ method not found in `D`
   |       |
   |       method `foo` is available on `&B`

```

So this should be good enough to consider as resolved
