### ISSUE TITLE
Add information about PGO and BOLT effects on Rustc performance to the documentation

### ISSUE THREAD

**Issue by zamazan4ik** [rust-lang/rust#115251]
### Location

Don't know the right place for this information - needs to be clarified.

### Summary

The official Rustc distribution is not the only Rustc binary version, which is used by Rust users. E.g. there are provided by multiple OS packages (like Fedora `rust` [package](https://src.fedoraproject.org/rpms/rust)) or even built in-house Rustc version (due to some not-so-rare specific security requirements).

According to the great @Kobzol [work](https://kobzol.github.io/rust/cargo/2023/07/28/rust-cargo-pgo.html), PGO and LLVM BOLT helps a lot with optimizing Rustc performance. We need to document somewhere the PGO and BOLT benefits for `rustc` performance and a guide - how these optimizations could be applied to `rustc` if a user/maintainer wants to build `rustc` on their own.

Here are the examples of PGO mentions in the documentation for other projects:
* GCC: Official [docs](https://gcc.gnu.org/install/build.html), section "Building with profile feedback" (even AutoFDO build is supported)
* Clang: https://llvm.org/docs/HowToBuildWithPGO.html
* ClickHouse: https://clickhouse.com/docs/en/operations/optimizing-performance/profile-guided-optimization
* Databend: https://databend.rs/doc/contributing/pgo
* Vector: https://vector.dev/docs/administration/tuning/pgo/
* Nebula: https://docs.nebula-graph.io/3.5.0/8.service-tuning/enable_autofdo_for_nebulagraph/

I didn't find a place where to put this information, so we can discuss it here. If there is no dedicated place and we don't want to create it - maybe a README would be a good place (since it already has build instructions)?

**Comment by Kobzol** [comment]
That's a good idea, this could potentially live in the rustc dev guide.

Some companies that build their own rustc (e.g. Google) are using their own setup, but it might still be worth it to document this for others that don't want to expend too much effort and get the PGO/BOLT benefits more easily.

It's worth noting that this will probably come with some maintenance cost to us. The PGO/BOLT setup is currently quite hardcoded for usage in our CI, and generalizing it for arbitrary rustc build environments might take some work (and further maintenance).

**Comment by zamazan4ik** [comment]
> It's worth noting that this will probably come with some maintenance cost to us. The PGO/BOLT setup is currently quite hardcoded for usage in our CI, and generalizing it for arbitrary rustc build environments might take some work (and further maintenance).

Good point. I think we can start with something with a lighter maintenance cost like it's described in the corresponding Clang [docs](https://llvm.org/docs/HowToBuildWithPGO.html) about PGO. Later we will be able to provide additional UX improvements for building `rustc` with PGO e.g. with a friendly `make pgoandboltbuild` like it's done in GCC.

**Comment by Kobzol** [comment]
https://github.com/rust-lang/rustc-dev-guide/pull/1787

**Comment by Kobzol** [comment]
Do you consider [this](https://rustc-dev-guide.rust-lang.org/building/optimized-build.html) to be enough information for this issue to be closed? :)

**Comment by zamazan4ik** [comment]
Yeah, that's perfect documentation! Thanks a lot!
