### ISSUE TITLE
mips64-unknown-linux-gnuabi64 for Rust 1.72 is missing in rustup

### ISSUE THREAD

**Issue by eduardosm** [rust-lang/rust#115218]
mips64-unknown-linux-gnuabi64 target for Rust 1.72 is missing in rustup, producing the following error while trying to update:

```
error: component 'rust-std' for target 'mips64-unknown-linux-gnuabi64' is unavailable for download for channel 'stable'
error: If you don't need the component, you could try a minimal installation with:
error: 
error:     rustup toolchain add stable --profile minimal
```

This target [is listed as tier 2](https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-2-with-host-tools), was available in Rust 1.71 and it is not mentioned in [Rust 1.72 release notes](https://github.com/rust-lang/rust/releases/tag/1.72.0) as being downgraded.

**Comment by Urgau** [comment]
It was decided the downgrade them to Tier 3 in https://github.com/rust-lang/compiler-team/issues/648

The documentation should have been updated but unfortunately it seems to have been forgotten. If you want to update it it should be in [`src/doc/rustc/src/platform-support.md`](https://github.com/rust-lang/rust/blob/master/src/doc/rustc/src/platform-support.md).

@rustbot label -needs-triage +O-mips +A-docs
cc @workingjubilee (as the MCP and PR author)

**Comment by CryZe** [comment]
The release notes also are not updated.

**Comment by workingjubilee** [comment]
Apologies, I had been told that the intent was to run the standard library build on the release day-of until it was formally downgraded and did not realize that was with an "only once" clause, so it fell through the cracks amongst other recent excitement.

**Comment by eduardosm** [comment]
I will open a PR to fix the platform support documentation. I will not do anything with release notes because I'm not sure how that should be handled.
