### ISSUE TITLE
Tracking Issue for `Literal::byte_character`

### ISSUE THREAD

**Issue by Emilgardis** [rust-lang/rust#115268]
Feature gate: `#![feature(proc_macro_byte_character)]`

This is a tracking issue for `Literal::byte_character`, enabling the creation of a `Literal` with `LitKind::Byte`, representing `b'a'`.

### Public API

```rust
impl Literal {
    pub fn byte_character(byte: u8) -> Literal;
}
```

### Steps / History

- [x] Implementation: #112711
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by dtolnay** [comment]
@rust-lang/libs-api:
@rfcbot fcp merge

Previously available alternatives for forming a byte literal:

- `Literal::u8_suffixed(byte)` constructs a literal like `97u8`

- `format!("b'\\x{:02x}'", byte).parse::<Literal>().unwrap()` constructs a literal like `b'\x61'`

- `format!("b'{}'", [byte].escape_ascii()).parse::<Literal>().unwrap()` constructs a literal like `b'a'`

This feature adds `Literal::byte_character(byte)` which is equivalent to the third alternative, as it is most often the one you want but is fairly challenging to come up with on your own.

**Comment by mdolberg** [comment]
If you get these error and you're running nightly versions
channel = "nightly" just type: rustup install nightly 
to make sure you have the latest corrected version
