### ISSUE TITLE
`invalid_from_utf8_unchecked` does not fail for include_bytes!

### ISSUE THREAD

**Issue by dev-ardi** [rust-lang/rust#115208]
This code should fail if invalid.txt contains invalid UTF-8.
```rs
let str = include_bytes!("../invalid.txt");
let str = unsafe { std::str::from_utf8_unchecked(str) };
```
This should fail as the byte sequence is known at compile time!

**Comment by ShE3py** [comment]
Isn't this the purpose of [`include_str!()`](https://doc.rust-lang.org/std/macro.include_str.html) ? I think Clippy should deny [`include_bytes!()`](https://doc.rust-lang.org/std/macro.include_bytes.html) on text files, as [`str::as_bytes()`](https://doc.rust-lang.org/std/primitive.str.html#method.as_bytes) is a no-op.

**Comment by dev-ardi** [comment]
> Isn't this the purpose of [`include_str!()`](https://doc.rust-lang.org/std/macro.include_str.html)?

That's not the point. A literal sequence of bytes known at compile time should fail if invalid utf8 is found, no matter how it's loaded.

> I think Clippy should deny [`include_bytes!()`](https://doc.rust-lang.org/std/macro.include_bytes.html) on text files, as [`str::as_bytes()`](https://doc.rust-lang.org/std/primitive.str.html#method.as_bytes) is a no-op.

What's a text file?
