### ISSUE TITLE
Adding `#[derive()]` changes blob import semantics

### ISSUE THREAD

**Issue by danielhenrymantilla** [rust-lang/rust#115377]
![image](https://github.com/rust-lang/rust/assets/9920355/885545b7-4506-4f44-8f0b-a1a108876c14)

I tried this code:

```rust
use module::*;
mod module {
    pub enum B {}
    impl B { pub const ASSOC: bool = true; } // used to distinguish the `B`s
}

#[derive()]
pub enum B {}
impl B { pub const ASSOC: bool = false; }

fn main() {
    let it = {
        use self::*;
        B::ASSOC
    };
    assert_eq!(
        it,
        {
            use self::*;
            B::ASSOC
        },
    );
}
```

I expected to see this happen: the assertion passing, since `{ use self::*; B::ASSOC }` should have a consistent value/meaning within `main`'s `fn body` where no other items are defined.

Instead, this happened: **the assertion fails!**

### Meta

[This regressed in `1.52.0`](https://rust.godbolt.org/z/6q9v7b87s)

### Extra comments

  - The key element playing a role here, beyond the blob imports, is the **`#[derive()]` slapped onto `B`**. This seems to allow for the blob-imported `module::B` to somehow gain priority over the clearly-defined `crate::B` type within `fn main`'s blob import.

  - I did not expect the "moving of `{ use self::*; B::ASSOC }` block" to alter this quirk (I was initially writing the MRE as `assert_eq!(B::ASSSOC, { use … })` when I ran into this extra bug).

  - ~~Could https://github.com/rust-lang/rust/pull/112086/ be relevant? cc @petrochenkov~~

  - Initially discovered [on Discord by user `@kyuuhachi`](https://discord.com/channels/442252698964721669/443150878111694848/1146395878391816202)

@rustbot modify labels: +regression-from-stable-to-stable

**Comment by petrochenkov** [comment]
It's not related to https://github.com/rust-lang/rust/pull/112086, it's related to https://github.com/rust-lang/rust/issues/56593 and friends.

It's gradually being fixed in https://github.com/rust-lang/rust/pull/113099 and follow up PRs.
Most of the difficulty in fixing this comes from avoiding breakage, it's massive if everything just starts working correctly.
