### ISSUE TITLE
#115296 broke include_bytes! on paths with untrustworthy metadata

### ISSUE THREAD

**Issue by saethlin** [rust-lang/rust#115458]
In https://github.com/rust-lang/rust/pull/115296 this diff is subtly broken:
```diff
-    fn read_binary_file(&self, path: &Path) -> io::Result<Vec<u8>> {
-        fs::read(path)
+    fn read_binary_file(&self, path: &Path) -> io::Result<Lrc<[u8]>> {
+        let mut file = fs::File::open(path)?;
+        let len = file.metadata()?.len();

+        let mut bytes = Lrc::new_uninit_slice(len as usize);
+        let mut buf = BorrowedBuf::from(Lrc::get_mut(&mut bytes).unwrap());
+        file.read_buf_exact(buf.unfilled())?;
+        // SAFETY: If the read_buf_exact call returns Ok(()), then we have
+        // read len bytes and initialized the buffer.
+        Ok(unsafe { bytes.assume_init() })
```
because it trusts that the size of the file returned by `File::metadata` is trustworthy, and it does not need to be. The correct implementation is to call `read` until EOF is reached.

This can be observed by trying to `include_bytes!("/dev/random")` (just be sure to use the resultant `const`).

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23115458.20.23115296.20broke.20include_bytes!.20on.20paths.20with.20untrustw.E2.80.A6)).

@rustbot label -I-prioritize +P-high
