### ISSUE TITLE
The generator should internally receive a value first and then pass a value.

### ISSUE THREAD

**Issue by timongh** [rust-lang/rust#115479]
I think there is a problem with the current yield syntax.

This is because the resume method passes in a parameter and then receives a value. So responsively, inside the generator, it should receive a value before generating a value.

However, the current yield does the opposite.

I can give you a usage scenario:

Suppose I want to use a generator to implement a generic tree traversal algorithm in first order.
The generator generates the next item in the traversal algorithm one at a time, and each time resume is called, it needs to be passed all the children of the last generated node.
The first time it is called, the root node is passed.

The example code is as follows([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=254aaa1845e92435d2c5145d9f661cf4)):

```rust
#![allow(unused)]
#![feature(generator_trait)]

use core::ops::Generator;
use core::ops::GeneratorState::*;
use core::pin::Pin;

struct Node(Vec<Node>);

fn main() {
    // build tree
    let node3 = Node(vec![]);
    let node4 = Node(vec![]);
    let node5 = Node(vec![]);
    let node6 = Node(vec![]);
    let node1 = Node(vec![node3, node4]);
    let node2 = Node(vec![node5, node6]);
    let node0 = Node(vec![node1, node2]);

    let mut gen: Pin<Box<dyn Generator<Vec<Node>, Yield = Node, Return = ()>>> = todo!();
    let Yielded(got_node0) = gen.as_mut().resume(vec![node0]) else { panic!() };
    let Yielded(got_node1) = gen.as_mut().resume(got_node0.0) else { panic!() };
    let Yielded(got_node3) = gen.as_mut().resume(got_node1.0) else { panic!() };
    let Yielded(got_node4) = gen.as_mut().resume(got_node3.0) else { panic!() };
    let Yielded(got_node2) = gen.as_mut().resume(got_node4.0) else { panic!() };
    let Yielded(got_node5) = gen.as_mut().resume(got_node2.0) else { panic!() };
    let Yielded(got_node6) = gen.as_mut().resume(got_node5.0) else { panic!() };
    let Complete(_) = gen.as_mut().resume(got_node6.0) else { panic!() };
}
```

Such a generator cannot be implemented directly using the existing generator syntax. Because `yield` forces me to pass a value first, and the value passed in from resume is only available next time.

**Comment by zachs18** [comment]
> The generator should internally receive a value first and then pass a value.

The closure-like generator syntax allows having an argument to the generator that is the first `Resume` value passed (IIUC if an argument is not present, then the generator's `Resume` type is implicitly `()`)

Thus If I am understanding you correctly, what you want can be written similar to the below ([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=0d2fa4866e797e98d4e44d5cbcb592de)) (modulo traversal order): 
```rs
let mut to_process = VecDeque::new();
let mut gen = Box::pin(move |nodes: Vec<Node>| {
    to_process.extend(nodes);
    while let Some(node) = to_process.pop_front() {
        let new_nodes = yield node;
        to_process.extend(new_nodes);
    }
});
```

**Comment by timongh** [comment]
Thanks, that's what I wanted.
