### ISSUE TITLE
`PatField` and `ExprField` produce no warning for `#[doc(...)]` attribute

### ISSUE THREAD

**Issue by gurry** [rust-lang/rust#115462]
### Code

```Rust
struct X {
    foo: i32,
}

#[allow(unused_variables)] // Not necessary for reproducing. Just to suppress an unrelated warning
fn main() {
    let X {
        #[doc(alias = "PatFieldAlias")]
        foo
    } = X {
        foo: 123
    };

    let _ = X {
        #[doc(alias = "ExprFieldAlias")]
        foo: 123,
    };
}
```

### Current output

```Shell
No output (compilation succeeds without warning)
```

### Desired output

```Shell
warning: unused doc comment
   |
14 |       let X {
15 |           #[doc(alias = "PatFieldAlias")]
   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16 | /         foo
17 | |     } = X {
18 | |         foo: 123
19 | |     };
   | |______- rustdoc does not generate documentation for pattern fields
   |
   = help: use `//` for a plain comment
   = note: `#[warn(unused_doc_comments)]` on by default

warning: unused doc comment
   |
22 |       let _ = X {
23 |           #[doc(alias = "ExprFieldAlias")]
   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
24 | /         foo: 123,
25 | |     };
   | |______- rustdoc does not generate documentation for expression fields
   |
   = help: use `//` for a plain comment
   = note: `#[warn(unused_doc_comments)]` on by default
```

### Rationale and extra context

The same warning is produced at other places like statements, expressions, functions etc. For completeness and consistency it should be produced for pattern and expression fields too.

### Anything else?

rustc 1.74.0-nightly (35e416303 2023-09-01)
binary: rustc
commit-hash: 35e416303e6591a71ef6a91e006c602d2def3968
commit-date: 2023-09-01
host: x86_64-pc-windows-msvc
release: 1.74.0-nightly
LLVM version: 17.0.0

rustc version older than 1.74.0 may ICE on this code. The ICE was fixed in 1.74.0

**Comment by gurry** [comment]
The reason these warnings are not produced is because the lint infrastructure currently exposes no hooks for `PatField` and `ExprField`, i.e. there are no `check_pat_field` and `check_expr_field` methods on `EarlyLintPass` (or `LateLintPass` for that matter). 

To fix the issue, these methods may have to be added here:
https://github.com/rust-lang/rust/blob/f9ba43ce147707fb90d038983789d8e57451eb6d/compiler/rustc_lint/src/passes.rs#L140
and then invoked from here:
https://github.com/rust-lang/rust/blob/f9ba43ce147707fb90d038983789d8e57451eb6d/compiler/rustc_lint/src/early.rs#L113-L117
and here:
https://github.com/rust-lang/rust/blob/f9ba43ce147707fb90d038983789d8e57451eb6d/compiler/rustc_lint/src/early.rs#L131-L135

**Comment by compiler-errors** [comment]
> Alternatively, we can emit the warning from the already existing check_pat and check_expr methods of EarlyLintPass and not bother with the above changes at all.

Yeah, I would expect this is the best way of doing it.
