### ISSUE TITLE
float break while makes it infinite 

### ISSUE THREAD

**Issue by Kivooeo** [rust-lang/rust#115432]
I tried this code:

```rust
fn main() {
    let mut x: f32 = 16700000.0;
    while x < 17000010.0 {
        x += 1.0;
        print!("{x}\n");
    }
    return;
}
```

I expected to see this happen: its just gonna increasing until value get greater than value in while condition

Instead, this happened: this just stuck on `16777216` value 

### Meta

`rustc --version --verbose`:
```
rustc 1.70.0 (90c541806 2023-05-31)
binary: rustc
commit-hash: 90c541806f23a127002de5b4038be731ba1458ca
commit-date: 2023-05-31
host: x86_64-pc-windows-msvc
release: 1.70.0
LLVM version: 16.0.2
```

**Comment by Brezak** [comment]
This isn't a rust issue but a floating point issue. What's happening is that you are trying to add 1 to 16777216 but the next representable f32 value is 16777218. So the expression result gets rounded towards zero and you're left with 16777216.

**Comment by the8472** [comment]
You might want something like `x = max(x + 1.0, x.next_up())`

**Comment by Kivooeo** [comment]
ыщ рфк
