### ISSUE TITLE
riscv64gc-unknown-linux-gnu `extern "C"` ABI violates repr(transparent) on unions

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#115481]
The types `(i32, f32)` and `MaybeUninit<T>` do not have the same ABI, as demonstrated by this testcase:
```rust
#![feature(rustc_attrs)]

type T = (i32, f32);

#[rustc_abi(debug)]
extern "C" fn test1(_x: T) {}

#[rustc_abi(debug)]
extern "C" fn test2(_x: std::mem::MaybeUninit<T>) {}

fn main() {}
```
The first is
```
                   mode: Cast(
                       CastTarget {
                           prefix: [
                               Some(
                                   Reg {
                                       kind: Integer,
                                       size: Size(4 bytes),
                                   },
                               ),
                               None,
                               None,
                               None,
                               None,
                               None,
                               None,
                               None,
                           ],
                           rest: Uniform {
                               unit: Reg {
                                   kind: Float,
                                   size: Size(4 bytes),
                               },
                               total: Size(4 bytes),
                           },
                           attrs: ArgAttributes {
                               regular: (empty),
                               arg_ext: None,
                               pointee_size: Size(0 bytes),
                               pointee_align: None,
                           },
                       },
                       false,
                   ),
```
The second is
```
                   mode: Cast(
                       CastTarget {
                           prefix: [
                               None,
                               None,
                               None,
                               None,
                               None,
                               None,
                               None,
                               None,
                           ],
                           rest: Uniform {
                               unit: Reg {
                                   kind: Integer,
                                   size: Size(8 bytes),
                               },
                               total: Size(8 bytes),
                           },
                           attrs: ArgAttributes {
                               regular: (empty),
                               arg_ext: None,
                               pointee_size: Size(0 bytes),
                               pointee_align: None,
                           },
                       },
                       false,
                   ),
```

Not sure whom to ping for RISC-V issues.

**Comment by RalfJung** [comment]
I think the fix will have to be to treat repr(transparent) unions specially somewhere around here

https://github.com/rust-lang/rust/blob/1bd043098e05839afb557bd7a2858cb09a4054ca/compiler/rustc_target/src/abi/call/riscv.rs#L90-L94

**Comment by RalfJung** [comment]
Cc @msizanoen1

**Comment by msizanoen1** [comment]
@RalfJung I'm afraid that the semantics of `#[repr(transparent)]` on unions are not clearly defined enough to figure out exactly how they should be specially treated (which variant should be used? etc.). Can you ping other people who have more knowledge on this?

**Comment by RalfJung** [comment]
I have no idea who would know anything about RISC-V calling conventions. :shrug: and no other ABI is failing this test.

Basically, when the ABI description says "unions do X", then this should only apply to repr(C) and repr(Rust) unions. A repr(transparent) union must be treated exactly like it non-ZST field.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23115481.20riscv64gc-unknown-linux-gnu.20.60extern.20.22C.22.60.20ABI.20violat.E2.80.A6)).

@rustbot label -I-prioritize +P-medium

**Comment by tgross35** [comment]
I haven't seen the Rust representation before - is the example saying that `T` is splitting the values into float and integer registers and passing them, whereas `MaybeUninit<T>` is treating the whole thing as an bigger opaque integer?

If so then based on section 18.2 here, I think the first one would be correct, assuming Rust doesn't ever make its tuples opaque https://riscv.org/wp-content/uploads/2015/01/riscv-calling.pdf

@programmerjake helped me with something RISC-V at some point so may know where to look. Or deferring to clang https://clang.godbolt.org/z/rrv5x3eYx

**Comment by RalfJung** [comment]
I honestly don't know what that `PassMode::Cast` means, it is sadly entirely undocumented. But I know it must be the same for the types to be ABI-compatible.

https://github.com/rust-lang/rust/pull/115499 has been opened to fix this issue.

**Comment by tgross35** [comment]
@RalfJung now that this is fixed, is there a CI test to catch regressions?

**Comment by RalfJung** [comment]
There is a test in `tests/ui/abi/compatibility.rs` but we don't run tests for riscv, since it's a tier 2 target.

**Comment by RalfJung** [comment]
Also see https://github.com/rust-lang/rust/issues/115609 for another ABI issue that affects riscv (and more).

**Comment by tgross35** [comment]
Are tier 2 tests run once before release or anything like that? It seems like at least a subset of tests (this one) are important enough that we should raise a red flag if we brake them somehow

**Comment by RalfJung** [comment]
I'm not aware of any process like that. Part of the point of being tier 2 is not to burden all contributors with keeping the target working, is it? If we do want to accept that burden, we could consider running something like `./x.py test codegen && ./x.py test ui --test-args abi` for tier 2 targets.

But having this discussion in a closed issue makes little sense. Do you want to open a new issue on Zulip thread for discussing tier 2 target test coverage?

**Comment by RalfJung** [comment]
Inspired by https://github.com/rust-lang/rust/pull/116004 I found a way to have a test for this: https://github.com/rust-lang/rust/pull/116030.

**Comment by tgross35** [comment]
Awesome! Thanks for the update here
