### ISSUE TITLE
`std` docs has `equivalent` methods in the search index that lead nowhere

### ISSUE THREAD

**Issue by Alexendoo** [rust-lang/rust#115480]
I was checking if `std` exposed [`hashbrown::Equivalent`](https://docs.rs/hashbrown/latest/hashbrown/trait.Equivalent.html) and found these seemingly non existent methods

https://doc.rust-lang.org/std/index.html?search=equivalent

**Comment by zachs18** [comment]
It looks like the search results are present on [1.71.0's docs](https://doc.rust-lang.org/1.71.0/std/index.html?search=equivalent), but not on [1.70.0's docs](https://doc.rust-lang.org/1.70.0/std/index.html?search=equivalent)

**Comment by Alexendoo** [comment]
Seems that's when std's hashbrown was upgraded to [the version](https://github.com/rust-lang/hashbrown/blob/master/CHANGELOG.md#v0131---2022-11-10) that added the `Equivalent` trait - https://github.com/rust-lang/rust/pull/111306
