### ISSUE TITLE
`#[allow(private_bounds)]` does not work when applied directly to the "bad" item.

### ISSUE THREAD

**Issue by TimNN** [rust-lang/rust#115475]
I tried this code:

```rust
#[allow(private_bounds)]
pub trait Foo: FooImpl {}

trait FooImpl {}
```

I expected to see this happen: The `private_bounds` lint is allowed.

Instead, this happened: The `private_bounds` lint still triggers.

(Applying `#[allow(private_bounds)]` to the entire module works).

(I'm assuming that this is unintentional, thus reporting as a "bug". If this behavior is intentional, consider this a feature request to change it).

### Meta

Latest playground nightly:
```
1.74.0-nightly (2023-09-01 35e416303e6591a71ef6)
```

**Comment by compiler-errors** [comment]
The problem here is that the lint is associated with the private item, not the item which names it in its bounds:

```
pub trait Foo: FooImpl {}

#[allow(private_bounds)]
trait FooImpl {}
```

**Comment by petrochenkov** [comment]
cc @Bryanskiy
