### ISSUE TITLE
Iterator::position() does not return the index position when used with rev()

### ISSUE THREAD

**Issue by dfoley-sherbrooke** [rust-lang/rust#115576]
Iterator::position() returns the number of iterations to find the true predicate, so it fails to return the index position when used with rev()

I tried this code:

```rust
let some_vec = vec![1,2,3];
let pos = some_vec.iter().rev().position(|value| *value == 3).unwrap();
assert_eq!(pos, 2);  // fails, pos is 0
```

I expected to see this happen:

Since documentation tells that it `Searches for an element in an iterator, returning its index`, I would expect it returns the index. The easy change then is that I would expect the documentation to say what it really does, or have a line about the fact it does not return index if use with rev()

Instead, this happened: 

It returns the number of iteration to reach a true predicate. Which is inconsistent with the documentation.

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0-nightly (5e37043d6 2023-01-22)
binary: rustc
commit-hash: 5e37043d63bfe2f3be8fa5a05b07d6c0dad5775d
commit-date: 2023-01-22
host: x86_64-unknown-linux-gnu
release: 1.69.0-nightly
LLVM version: 15.0.7
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by cuviper** [comment]
It returns the index as seen coming out of the iterator, regardless of whatever the underlying source may be. `Rev` is kind of a red herring, because you could have a similar kind of mismatched expectation if you `filter` items first, or `flatten`, or any other kind of transformation that doesn't map directly to the original source indices.

**Comment by dfoley-sherbrooke** [comment]
The code is fine, and it all makes sense when you consider that rev is like
if one is working with a new list with items in reverse. My concern is that
I think for many readers, it is very easy to interpret that rev is not like
working on a new list, but perhaps just a different way to traverse a list.
This mental model may come from the fact that when using a for loop
construct, reversing the order of iteration is not modifying the list and
its index. Perhaps a hint could be added by modifying the doc:

Searches for an element in an iterator, returning its index.
`position()` takes a closure that returns `true` or `false`. It applies
this closure to each element of the iterator, and if one of them returns
`true`, then `position()` returns [`Some(index)`], *where index is the
number of iterations*.

**Comment by the8472** [comment]
> . My concern is that I think for many readers, it is very easy to interpret that rev is not like working on a new list

`Rev`, like `Filter`, `Skip` and so on is an [adapter](https://doc.rust-lang.org/nightly/std/iter/index.html#adapters). It is a separate, new type. Iterator methods do not modify the behavior of an iterator, they create new iterators that encapsulate the old ones and bring their own semantics. This is not specific to `Rev`.

**Comment by dfoley-sherbrooke** [comment]
This is a good explanation. It is part of general rust knowledge that rev()
is an adapter. You can close the bug report if you see fit.
