### ISSUE TITLE
Format Macro Named Argument Example is Confusing

### ISSUE THREAD

**Issue by thisisscotts** [rust-lang/rust#115551]
### Location

https://doc.rust-lang.org/std/macro.format.html#examples

### Summary

I was sent here from the [Rust website tracker](https://github.com/rust-lang/www.rust-lang.org/issues/1862). Please advise if I am posting in the wrong area.

### What needs to be fixed?
format! macro documentation could be improved by changing one of the examples to be more obvious to new users.

### Suggested Improvement
Change the example 
```format!("x = {}, y = {y}", 10, y = 30);```
to
```format!("x = {}, y = {z}", 10, z = 30);```

Additionally, assert! could be used to demonstrate final string values:
```format!("test");
let greeting = format!("hello {}", "world!");
assert!(greeting=="hello world!");
let xy = format!("x = {}, y = {z}", 10, z = 30);
assert!(xy=="x = 10, y = 30");
let (a, b) = (1, 2);
let ab = format!("{a} + {b} = 3");
assert!(ab=="1 + 2 = 3");
```

**Comment by ShE3py** [comment]
Something like
```rs
assert_eq!(format!("x = {}, y = {val}", 10, val = 30), "x = 10, y = 30");
```
?

@rustbot claim

**Comment by thisisscotts** [comment]
@ShE3py I think the use of "val" certainly makes it more obvious than my suggestion to use "z". Your suggestion would also do it in one line... I guess the question is whether you would prefer to make it more obvious (readable) by splitting it into two lines. 

This is my first contribution to Rust in any form, so I'm happy to go with your suggestion.

**Comment by thisisscotts** [comment]
Thanks all!
