### ISSUE TITLE
default binary size increase due to ice dumps logic

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#115610]
#108714 slightly increased default binary size (checked on x86_64-pc-windows-msvc), the reason is now code https://github.com/rust-lang/rust/blob/a0c28cd9dc99d9acb015d06f6b27c640adad3550/library/std/src/panicking.rs#L304-L308 unconditionally includes File::open (~ 2kb out of 130) and friends. can be tracked back by new imports of `CreateFileW`, `GetFullPathNameW` for `rustc empty.rs -Copt-level=3 -Cdebuginfo=0 -Clto=yes -Ccodegen-units=1 -Cpanic=abort --edition=2018` where `empty.rs` is `fn main(){}`

_Originally posted by @klensy in https://github.com/rust-lang/rust/issues/108714#issuecomment-1708542486_

**Comment by oli-obk** [comment]
cc @estebank

**Comment by cuviper** [comment]
cc @rust-lang/libs -- I'm surprised that #108714 didn't include any libs review in the first place, having modified the default panic hook. Maybe `rustc` ought to be registering its own panic hook instead?
