### ISSUE TITLE
`File::create` fails on hidden files on Windows

### ISSUE THREAD

**Issue by ChrisDenton** [rust-lang/rust#115745]
Reported on discord, using `OpenOptions::new().write(true).create(true).truncate(true).open(&path)` will fail on Windows if the file is hidden. This also affects methods like `File::create` or `fs::write` that open the file the same way.

The reason for this is that we use `CREATE_ALWAYS`, which has [strange behaviour](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilew#files):

> If `CREATE_ALWAYS` and `FILE_ATTRIBUTE_NORMAL` are specified, `CreateFile` fails and sets the last error to `ERROR_ACCESS_DENIED` if the file exists and has the `FILE_ATTRIBUTE_HIDDEN` or `FILE_ATTRIBUTE_SYSTEM` attribute. To avoid the error, specify the same attributes as the existing file.

So to make it work the caller needs to match the requested attributes to the existing attributes at the time of opening.

## Possible solution

It was suggested we could instead use `OPEN_ALWAYS` and then manually truncate the file using [`SetFileInformationByHandle`](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setfileinformationbyhandle) to set the [`FILE_ALLOCATION_INFO`](https://learn.microsoft.com/en-us/windows/win32/api/winbase/ns-winbase-file_allocation_info) to zero.

**Comment by bjorn3** [comment]
Manually truncating would require also clearing the alternate data streams too, right? And it would presumably stop erroring if another process still has the file open and instead corrupt the file fron the view of the other process.

**Comment by ChrisDenton** [comment]
No? The proposed solution would work the same was as `TRUNCATE_EXISTING` in the case where the file already exists. Which we use for `.write(true).truncate(true)`.

**Comment by bjorn3** [comment]
Right, got confused with `create_new`.
