### ISSUE TITLE
Search is broken on nightly rustdoc

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#115729]
Both of the following are broken (in Firefox and Chromium):
https://doc.rust-lang.org/nightly/std/?&search=Vec
https://doc.rust-lang.org/nightly/nightly-rustc/?search=Place

That seems like complete failure of search on current nightly?
Cc @rust-lang/rustdoc

**Comment by Nemo157** [comment]
Not search specifically, loading JS fails

```
GET https://doc.rust-lang.org/nightly/static.files/main-ef3a2de404864b0b.js
[HTTP/2 404 Not Found 407ms]
```

Opening some recent docs on docs.rs this file loads fine, so it's something to do with the deployment to doc.rust-lang.org not rustdoc itself.

**Comment by RalfJung** [comment]
In that case Cc @rust-lang/infra

**Comment by Mark-Simulacrum** [comment]
Both links are working for me now -- @Nemo157 / @RalfJung can you confirm whether this is fixed for you too?

**Comment by bjorn3** [comment]
Was broken for me and is now fixed.

**Comment by bjorn3** [comment]
It is broken for me right now. I think I confused the nightly docs with the beta docs, which do still work.

**Comment by RalfJung** [comment]
The links in the OP both work for me right now.

**Comment by bjorn3** [comment]
Works for me too now.
