### ISSUE TITLE
Vec(Deque)::truncate documentation says 'greater' when it should say 'greater or equal'

### ISSUE THREAD

**Issue by jplatte** [rust-lang/rust#115784]
### Location

https://doc.rust-lang.org/std/vec/struct.Vec.html#method.truncate

### Summary

The documentation currently says

> If `len` is greater than the vector’s current length, this has no effect.

But it also doesn't have an effect if the two lengths are equal, so I think it should say "greater or equal to the vector's current length".

**Comment by chenyukang** [comment]
yes, there is a trivial difference between `> len` and `= len`,
https://github.com/rust-lang/rust/pull/78884

but it's an internal implementation issue, I think we should update the doc since they are same from the user's view.
