### ISSUE TITLE
Deallocation of 37.3 G takes 10 minutes

### ISSUE THREAD

**Issue by safinaskar** [rust-lang/rust#115814]
Consider this code:
```rust
fn main() {
    println!("{:?} Started", std::time::SystemTime::now());
    {
        const N: usize = 1_000_000_000;
        let mut v = Vec::with_capacity(N);
        for _ in 0..N {
            v.push(Box::new(0u8));
        }
        println!("{:?} Allocated", std::time::SystemTime::now());
    }
    println!("{:?} Deallocated", std::time::SystemTime::now());
}
```
I did run this program (in release mode) and got this result:
```text
SystemTime { tv_sec: 1694601371, tv_nsec: 605646669 } Started
SystemTime { tv_sec: 1694601583, tv_nsec: 11269536 } Allocated
SystemTime { tv_sec: 1694602223, tv_nsec: 300034665 } Deallocated
```
As you can see, allocation took 3.5 minutes, but deallocation took 10 minutes.
Here is output of `free -h` before running of program:
```text
              total        used        free      shared  buff/cache   available
Mem:            31G         13G         16G        168M        1.4G         17G
Swap:          163G         37G        126G
```
Peak allocated memory by the program (as reported by htop) is 37.3 G. It is more than amount of physical memory (31 G).

In this point you may say: "Okay, your program eats more than you have physical memory available. Of course, your program will be slow. Why you think this is a bug?" I think this is a bug, because deallocating takes a lot more time than allocating (3.5 minutes vs 10 minutes).

I report this not for fun. The code above is reduced test case from my actual production code base. In my actual code my program reads a lot of data from files and then processes them. I noticed that actual execution takes several minutes, but deallocation takes a lot more.

`rustc --version`: `rustc 1.73.0-nightly (076887268 2023-08-17)`.

Debian Linux Stretch x86_64

**Comment by vacuus** [comment]
There's only so much Rust can do on this front. If your actual code puts that much stress on the allocator, you'll probably have to use different memory access patterns.

**Comment by Mark-Simulacrum** [comment]
We don't ship any particular allocator on any platform at this point, so I don't think there's anything we can do - this compiles to malloc/free calls from glibc on this target triple. So, you could try to report this to glibc, or try switching to a different allocator.
