### ISSUE TITLE
StructuralEq trait docs are outdated

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#115881]
The StructuralEq trait docs are saying
```rust
/// In a more ideal world, we could check that requirement by just checking that
/// the given type implements both the `StructuralPartialEq` trait *and*
/// the `Eq` trait. However, you can have ADTs that *do* `derive(PartialEq, Eq)`,
/// and be a case that we want the compiler to accept, and yet the constant's
/// type fails to implement `Eq`.
///
/// Namely, a case like this:
///
/// ```rust
/// #[derive(PartialEq, Eq)]
/// struct Wrap<X>(X);
///
/// fn higher_order(_: &()) { }
///
/// const CFN: Wrap<fn(&())> = Wrap(higher_order);
///
/// fn main() {
///     match CFN {
///         CFN => {}
///         _ => {}
///     }
/// }
/// ```
///
/// (The problem in the above code is that `Wrap<fn(&())>` does not implement
/// `PartialEq`, nor `Eq`, because `for<'a> fn(&'a _)` does not implement those
/// traits.)
///
/// Therefore, we cannot rely on naive check for `StructuralPartialEq` and
/// mere `Eq`.
```

However, with the `FnPtr` trait, `fn(&())` *does* implement `Eq` and `PartialEq`.

Is the `StructuralEq` trait still necessary? `Eq` has no methods, so if `PartialEq` is structural then there's no way that `Eq` is not, right?

**Comment by RalfJung** [comment]
Cc @rust-lang/types

**Comment by RalfJung** [comment]
Also I don't think the current consensus is that we should check matched constants to be `Eq`. https://github.com/rust-lang/rust/pull/84045 got rejected, which is a fairly clear sign that `PartialEq` is sufficient for matching and everything else can be handled with lints.

So I don't think `StructuralEq` still serves any purpose.

**Comment by nikomatsakis** [comment]
I would be very happy to settle this story once and for all. I still feel a bit confused about our plan here, though I recall thinking @RalfJung that your proposals made sense to me.

**Comment by RalfJung** [comment]
I think my prior proposals don't entirely work any more with things like https://github.com/rust-lang/rust/pull/67343 or [code like this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=fff275a98d5c7da3b7ccd065acd02cb8) -- we have really honed in on StructuralPartialEq being a shallow property, not a statement about being able to create valtrees. We also have `ConstParamTy` as a separate trait now; I think that might be closer to what I originally imagined.

Also see [this Zulip thread I just started](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/matching.20and.20.60Eq.60/near/391366382).
