### ISSUE TITLE
#[inline] attribute causes #[allow(...)] to not work

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#115823]
Given [this code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2258b8d7b9ec201094eee65fe8f6a509):

```rust
pub struct A {
    pub x: u32,
}

pub fn foo(y: u32) -> A {
    A {
        #[allow(unused_comparisons)]
        x: if y < 0 { 1 } else { 2 },
    }
}
```

no warnings, as expected, are generated:

```
$ rustc foo.rs --crate-type lib
```

Given [this code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a2f73ee2def1ce69746c6dfe5ca3cf60) (note the addition of `#[inline]`) however:

```rust
pub struct A {
    pub x: u32,
}

#[inline]
pub fn foo(y: u32) -> A {
    A {
        #[allow(unused_comparisons)]
        x: if y < 0 { 1 } else { 2 },
    }
}
```

a warning is generated:

```
$ rustc foo.rs --crate-type lib
warning: comparison is useless due to type limits
 --> foo.rs:9:15
  |
9 |         x: if y < 0 { 1 } else { 2 },
  |               ^^^^^
  |
  = note: `#[warn(unused_comparisons)]` on by default

warning: 1 warning emitted
```

**Comment by saethlin** [comment]
I think any attribute will reproduce this behavior. `#[deny(unsafe_code)]` as well as `#[allow(dead_code)]` seem to do the trick.
