### ISSUE TITLE
MutexGuard's lifetime should same as the inner data

### ISSUE THREAD

**Issue by Sword-Destiny** [rust-lang/rust#115837]
look this code
```rust
pub struct UserLock {
    pub userid: u32,
    pub lock: bool,
}

static mut G_LIST: Mutex<Vec<UserLock>> = Mutex::new(Vec::new());

pub fn get_user_lock(userid: u32) -> &'static UserLock {
    unsafe {
        let list = G_LIST.lock().unwrap();
        for userlock in list.iter() {
            if userlock.userid == userid {
                return userlock;
            }
        }

        // some other code
    }
}
```

get compiler error

```txt
error[E0515]: cannot return value referencing local variable `list`
   --> src/database.rs:429:24
    |
427 |         for userlock in list.iter() {
    |                         ----------- `list` is borrowed here
428 |             if userlock.userid == userid {
429 |                 return userlock;
    |                        ^^^^^^^^ returns a value referencing data owned by the current function
```

I think this is wrong.
Because, G_LIST is global variable, it's lifetime should be 'static, the MutexGuard of the list should have the same lifetime.

Maybe someone will say: the reference of global variable will be invalid if other thread changed the global variable or deleted some item from the list.
But if I make sure I just insert item into the list, never delete or modify the item. How can I make the compiler accept my code.

Use a unsafe block? No, it's not work.

**Comment by Sword-Destiny** [comment]
I finally use a very strange way to protect my list with mutex, like C-language
```
/// each user have a Database file
pub struct UseridFileLock {
    /// userid
    pub userid: u32,
    /// file lock
    pub mtx: Mutex<u32>,
}

/// save all the userid filelocks
static mut G_USERFILE_LOCK_LIST: Vec<UseridFileLock> = Vec::new();
/// protect G_USERFILE_LOCK_LIST
static G_LIST_LOCK: Mutex<u32> = Mutex::new(0);

/// if userid exists, return reference, or create a new lock, insert into list and return reference
pub fn get_filelock_by_userid<'a>(userid: u32) -> &'a UseridFileLock {
    let _lock = G_LIST_LOCK.lock().unwrap();
    // SAFETY: We just push item into G_LIST, never remove item or modify item,
    // so return a reference of G_LIST item is safe.
    unsafe {
        for f in G_USERFILE_LOCK_LIST.iter() {
            if f.userid == userid {
                return f;
            }
        }
        let nf = UseridFileLock { userid, mtx: Mutex::new(userid) };
        G_USERFILE_LOCK_LIST.push(nf);
        &G_USERFILE_LOCK_LIST[G_USERFILE_LOCK_LIST.len() - 1]
    }
}
```
I think we need a way to write the code more rustful.

**Comment by SkiFire13** [comment]
> Because, G_LIST is global variable, it's lifetime should be 'static, the MutexGuard of the list should have the same lifetime.

A `MutexGuard` is a local variable, it is **not** `'static`. The data is borrowing from the guard, which is not static, because when the guard is dropped you can no longer assume the data will stay the same (e.g. someone else might take the lock and change it, doesn't matter if the variable is local or global).

> But if I make sure I just insert item into the list, never delete or modify the item. How can I make the compiler accept my code.

Even inserting new items into the list can make older ones invalid because the vector may need to reallocate, thus changing the location of all the existing items.

If the list is only populated once at the start of your program then you may use `OnceLock`.

If instead new items may be added later on but never removed you could store `&'static UserLock` in your `Vec` and create them using `Box::leak`.

Neither solution needs `unsafe` or `static mut`.

**Comment by Sword-Destiny** [comment]
> > Because, G_LIST is global variable, it's lifetime should be 'static, the MutexGuard of the list should have the same lifetime.
> 
> A `MutexGuard` is a local variable, it is **not** `'static`. The data is borrowing from the guard, which is not static, because when the guard is dropped you can no longer assume the data will stay the same (e.g. someone else might take the lock and change it, doesn't matter if the variable is local or global).
> 
> > But if I make sure I just insert item into the list, never delete or modify the item. How can I make the compiler accept my code.
> 
> Even inserting new items into the list can make older ones invalid because the vector may need to reallocate, thus changing the location of all the existing items.
> 
> If the list is only populated once at the start of your program then you may use `OnceLock`.
> 
> If instead new items may be added later on but never removed you could store `&'static UserLock` in your `Vec` and create them using `Box::leak`.
> 
> Neither solution needs `unsafe` or `static mut`.

thanks a lot, I ignored reallocate

**Comment by Sword-Destiny** [comment]
> > Because, G_LIST is global variable, it's lifetime should be 'static, the MutexGuard of the list should have the same lifetime.
> 
> A `MutexGuard` is a local variable, it is **not** `'static`. The data is borrowing from the guard, which is not static, because when the guard is dropped you can no longer assume the data will stay the same (e.g. someone else might take the lock and change it, doesn't matter if the variable is local or global).
> 
> > But if I make sure I just insert item into the list, never delete or modify the item. How can I make the compiler accept my code.
> 
> Even inserting new items into the list can make older ones invalid because the vector may need to reallocate, thus changing the location of all the existing items.
> 
> If the list is only populated once at the start of your program then you may use `OnceLock`.
> 
> If instead new items may be added later on but never removed you could store `&'static UserLock` in your `Vec` and create them using `Box::leak`.
> 
> Neither solution needs `unsafe` or `static mut`.

this is very nice with no unsafe，thanks a lot
```rust
/// save all the userid filelocks
static G_USERFILE_LOCK_LIST: Mutex<Vec<&'static UseridFileLock>> = Mutex::new(Vec::new());

/// if userid exists, return reference, or create a new lock, insert into list and return reference
pub fn get_filelock_by_userid<'a>(userid: u32) -> &'static UseridFileLock {
    let mut list = G_USERFILE_LOCK_LIST.lock().unwrap();
    for f in list.iter() {
        if f.userid == userid {
            return *f;
        }
    }
    let nf = Box::new(UseridFileLock { userid, mtx: Mutex::new(userid) });
    // SAFETY: We just push item into G_USERFILE_LOCK_LIST, never remove item or modify item,
    // so return a reference of leak item is safe.
    let nf: &'static UseridFileLock = Box::leak(nf);
    list.push(nf);
    list[list.len() - 1]
}
```
