### ISSUE TITLE
Add debug logging output to Sender

### ISSUE THREAD

**Issue by larsbergstrom** [rust-lang/rust#11582]
It would be great if we could get logging output from channels so that `send` would do something like:

sending message MSG from task TASK

And any call to `recv` would do

received message MSG in task TASK

In Servo, we frequently need to debug race conditions and deadlocks or just explain what happens when e.g. we get a mouse click in the window. Having this debugging info would greatly help (and let us build visualization tools on top of the output).

**Comment by steveklabnik** [comment]
Triage: no change that I'm aware of.

@larsbergstrom do you still feel this pain?

**Comment by larsbergstrom** [comment]
So we feel the pain a bit less after the removal of green threads, because there's always a stack backtrace above the thread.

That said, we have these concurrency problems ALL the time, leading to huge numbers of intermittents in Servo. I suspect, though, that the right solution is for us to be using https://github.com/mozilla/rr to debug these issues in Servo, though, rather than broken printf-debugging. If we want that, we can always (at least on linux) use some cheesy gdb-automation breakpoints to spit out messages similar to the ones @alexcrichton is suggesting, without bloating the stdlib.

**Comment by apasel422** [comment]
We could take the approach @alexcrichton described, but use specialization to log the actual values when `T: Debug`.

**Comment by steveklabnik** [comment]
Triage: with no comments in years, I don't think this is likely to happen. I'm going to give it a close. If anyone strongly desires this, please let me know, and we can re-open.
