### ISSUE TITLE
PROBLEMATIC_CONSTS is problematic

### ISSUE THREAD

**Issue by threewordphrase** [rust-lang/rust#115899]
PROBLEMATIC_CONSTS is Anglophone-centric and is therefore itself problematic. Opening this issue to start a conversation about how to address this.

https://github.com/rust-lang/rust/blob/d0ea1d767925d53b2230e2ba81197821514781f0/src/tools/tidy/src/style.rs#L60

**Comment by oli-obk** [comment]
Moderator note: Locking and closing this issue. If you feel like there is something actually addressable here, please don't hesitate to message me on zulip so we can figure out how to constructively start a discussion.
