### ISSUE TITLE
Execution is being deferred unexpectedly

### ISSUE THREAD

**Issue by dio-gh** [rust-lang/rust#115856]
Inspired by Raymond Chen's [recent blogpost](https://devblogs.microsoft.com/oldnewthing/20230911-00/?p=108749), and seeing someone in a related discussion on Reddit trying this same thing, I attempted to run the following code on Windows:

```rust
use std::env;
use std::fs;

fn main() {
    println!("deleting: {}", env::current_exe().unwrap().display());
    fs::remove_file(env::current_exe().unwrap());
    println!("ding");
}
```

(Replacing the contents of `src/main.rs` after issuing a mere `cargo init`.)

**I expected to see this happen:** two lines being printed and `remove_file()` not succeeding in silence, as on Windows it is not possible to delete yourself. 

**Instead, this happened:** it succeeds once but never again, and not for the reasons you may be thinking. Specifically, if I place a breakpoint on the line where I issue the `remove_file()`, I can do two things:

- quit and launch the generated executable manually (`target/debug/testapp.exe`), but not before making a copy of it,
- check the hashes of the generated executable (`target/debug/testapp.exe`) as well as of the executable in the artifact cache  (`target/debug/deps/testapp.exe`), and then resume execution.

If I take route 1, I can now try restoring the executable by placing the previous copy back where it came from. One small problem: this copy will now never work the way the original did (it will never delete itself).

If I take route 2, I will see that a line later the executable has been deleted, and then "ding" being printed to the terminal. Except if I try to restore the executable from the artifact cache (having confirmed the hashes match), once again, the executable will never work again.

Further shenanigans observed:

- copying the entirety of `target` to somewhere else and running either executables from it won't work
- moving the entirety of `target` to somewhere else and running either executables from it WILL work
- moving only one of the executables and running it WILL work
- copying one of the executables away somewhere and running it won't work
- deleting one of the executables makes the other one not work

To me this suggests two behaviors:

- somehow something knows that a given executable already deleted itself and won't let it do it again
- somehow execution is deferred to the other executable, enabling it to do the impossible, and delete the main one as if it deleted itself

Using Process Monitor, I was only able to see the main executable ever running. When the deletion worked, `SetDispositionInformationEx()`, that `DeleteFileW()` eventually ends up calling deeper inside Windows, would return `SUCCESS`. When not, it would return `CANNOT DELETE`. Under no circumstances should the former ever be possible, supposedly.

### Meta

`rustc --version --verbose`:
```
rustc 1.74.0-nightly (8142a319e 2023-09-13)
binary: rustc
commit-hash: 8142a319ed5c1d1f96e5a1881a6546e463b77c8f
commit-date: 2023-09-13
host: x86_64-pc-windows-msvc
release: 1.74.0-nightly
LLVM version: 17.0.0
```

<details><summary>Backtrace</summary>
<p>

```
{"reason":"compiler-message","package_id":"testapp 0.1.0 (path+file:///C:/Users/WDAGUtilityAccount/Desktop/testapp)","manifest_path":"C:\\Users\\WDAGUtilityAccount\\Desktop\\testapp\\Cargo.toml","target":{"kind":["bin"],"crate_types":["bin"],"name":"testapp","src_path":"C:\\Users\\WDAGUtilityAccount\\Desktop\\testapp\\src\\main.rs","edition":"2021","doc":true,"doctest":false,"test":true},"message":{"rendered":"warning: unused `Result` that must be used\n --> src\\main.rs:6:5\n  |\n6 |     fs::remove_file(env::current_exe().unwrap());\n  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  |\n  = note: this `Result` may be an `Err` variant, which should be handled\n  = note: `#[warn(unused_must_use)]` on by default\nhelp: use `let _ = ...` to ignore the resulting value\n  |\n6 |     let _ = fs::remove_file(env::current_exe().unwrap());\n  |     +++++++\n\n","children":[{"children":[],"code":null,"level":"note","message":"this `Result` may be an `Err` variant, which should be handled","rendered":null,"spans":[]},{"children":[],"code":null,"level":"note","message":"`#[warn(unused_must_use)]` on by default","rendered":null,"spans":[]},{"children":[],"code":null,"level":"help","message":"use `let _ = ...` to ignore the resulting value","rendered":null,"spans":[{"byte_end":113,"byte_start":113,"column_end":5,"column_start":5,"expansion":null,"file_name":"src\\main.rs","is_primary":true,"label":null,"line_end":6,"line_start":6,"suggested_replacement":"let _ = ","suggestion_applicability":"MaybeIncorrect","text":[{"highlight_end":5,"highlight_start":5,"text":"    fs::remove_file(env::current_exe().unwrap());"}]}]}],"code":{"code":"unused_must_use","explanation":null},"level":"warning","message":"unused `Result` that must be used","spans":[{"byte_end":157,"byte_start":113,"column_end":49,"column_start":5,"expansion":null,"file_name":"src\\main.rs","is_primary":true,"label":null,"line_end":6,"line_start":6,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":49,"highlight_start":5,"text":"    fs::remove_file(env::current_exe().unwrap());"}]}]}}
{"reason":"compiler-message","package_id":"testapp 0.1.0 (path+file:///C:/Users/WDAGUtilityAccount/Desktop/testapp)","manifest_path":"C:\\Users\\WDAGUtilityAccount\\Desktop\\testapp\\Cargo.toml","target":{"kind":["bin"],"crate_types":["bin"],"name":"testapp","src_path":"C:\\Users\\WDAGUtilityAccount\\Desktop\\testapp\\src\\main.rs","edition":"2021","doc":true,"doctest":false,"test":true},"message":{"rendered":"warning: 1 warning emitted\n\n","children":[],"code":null,"level":"warning","message":"1 warning emitted","spans":[]}}
{"reason":"compiler-artifact","package_id":"testapp 0.1.0 (path+file:///C:/Users/WDAGUtilityAccount/Desktop/testapp)","manifest_path":"C:\\Users\\WDAGUtilityAccount\\Desktop\\testapp\\Cargo.toml","target":{"kind":["bin"],"crate_types":["bin"],"name":"testapp","src_path":"C:\\Users\\WDAGUtilityAccount\\Desktop\\testapp\\src\\main.rs","edition":"2021","doc":true,"doctest":false,"test":true},"profile":{"opt_level":"0","debuginfo":2,"debug_assertions":true,"overflow_checks":true,"test":false},"features":[],"filenames":["C:\\Users\\WDAGUtilityAccount\\Desktop\\testapp\\target\\debug\\testapp.exe","C:\\Users\\WDAGUtilityAccount\\Desktop\\testapp\\target\\debug\\testapp.pdb"],"executable":"C:\\Users\\WDAGUtilityAccount\\Desktop\\testapp\\target\\debug\\testapp.exe","fresh":true}
{"reason":"build-finished","success":true}
```

</p>
</details>

**Environment:** Windows 11 Pro 22H2 (build 22621.2283). The data above is from a reproduction inside Windows Sandbox, but the behavior matches outside of the sandbox also, was just to ensure a clean environment.

**Comment by ChrisDenton** [comment]
I believe you're simply observing OS behaviour (which has changed a bit over the versions). Files can have multiple paths to the same underlying file. These are called "hard links". The lock held by the OS when running an executable will allow you rename or remove hard links all you like but it won't let you remove the last link to the file.

**Comment by dio-gh** [comment]
This indeed explains all of my observations, thank you. Confirmed it by checking with `fsutil hardlink list <path/to/file>`. Apologies for missing this, I didn't check for hard link count. Closing as not an issue.
