### ISSUE TITLE
Decision: semantics of the `#[expect]` attribute

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#115980]
This issue is spun out from #54503 to serve as the decision issue for a specific question. The question is what the 'mental model' for the `expect` attribute should be. Two proposed options:

1. The expectation is fulfilled, if a #[warn] attribute in the same location would cause a diagnostic to be emitted. The suppression of this diagnostic fulfills the expectation. ([src](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/Expect.20attribute.20mental.20model/near/341522535)) (Current implementation in rustc)
2. The expectation is fulfilled if removing the `#[expect]` attribute would cause the warning to be emitted. ([src](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/Expect.20attribute.20mental.20model/near/354082551))

@xfrednet created a [list of use cases](https://hackmd.io/@xFrednet/expect-attr-use-cases) to help with the discussion of these two models; they found both models work equally well, except for [use case 4](https://hackmd.io/@xFrednet/expect-attr-use-cases#Use-case-4-Suppress-lints-from-CI) which would only be possible with the first model.

**Comment by tgross35** [comment]
Mind clarifying the title to reference the lint attribute, to not confuse it with `.expect()`?

**Comment by RalfJung** [comment]
It also wouldn't hurt clarifying where the two semantics differ. I think they only differ in case the lint is allowed, in which case option 2 would always cause an error on `expect` since there's nothing being linted? So, option 1 is like having an implicit `warn(lint)` together with the `expect(lint)`?

**Comment by xFrednet** [comment]
* Option 1 acts like a new lint level. The lint level at the outer scope doesn't matter, since it's overwritten by the new "expect" lint level.
* Option 2 acts like a try-and-catch block and the lint level is not affected.

You already mentioned the difference, when it comes to the lint being allowed in the outer scope. The semantics also change, how inner lint levels are handled. Let's take this example:

```rust
#![allow(unused)]

#[expect(unused_variables)]
fn foo() {
    #[warn(unused_variables)]
    let bar = "Marker is cool";
}
```

* Option 1 acts like a new lint level, for the function `foo`. The `#[warn]` overwrites the lint level for the `let`-statement. This causes the `unused_variables` lint for `bar` to be emitted and the lint expectation for `foo` to be unfulfilled
* Option 2 acts like a try-and-catch block. The `unused_variables` lint emission from `bar` would be suppressed by the lint expectation of `foo`. In this case, no warning would be emitted.

This is one of the examples, why I favor option 1. In this example, I would expect to get a warning for `bar`, since it states `#[warn]` above it.

**Comment by RalfJung** [comment]
With option 2 your example would also error I think? Removing `expect` doesn't cause any change in output behavior (we get a warning either way). Ergo the expectation is unfulfilled and we should get an error.

**Comment by xFrednet** [comment]
> With option 2 your example would also error I think?

This is the difference, between the semantic models.
* Option 1 acts as a new lint level, which can be changed like any other one.
* Option 2 will suppress any warn or error lint emission in the marked scope. So from my understanding: No, it would not error, since this option suppresses the warn emission. ([Zulip Discussion](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/Expect.20attribute.20mental.20model/near/354079078) for reference, where the model comes from).

**Comment by RalfJung** [comment]
Option 2 got described as "The expectation is fulfilled if removing the #[expect] attribute would cause the warning to be emitted". Under that specification, clear your example would error, since removing the expect attribute would *not* cause anything to happen, it would be a complete NOP.

**Comment by xFrednet** [comment]
> Clearly your example would error

This was my intuition as well, but during the lang meeting and discussion on Zulip, I understood the other model as stated above.

The `#[warn]` attribute would "create" a lint emission, which would be suppressed by the `#[expect]` attribute. If you return the `#[expect]` attribute, you would get the lint emission. This maps to how @tmandry described the second option: "The expectation is fulfilled if removing the #[expect] attribute would cause the warning to be emitted."

**Comment by RalfJung** [comment]
> This maps to how @tmandry described the second option: "The expectation is fulfilled if removing the #[expect] attribute would cause the warning to be emitted."

No, for me this doesn't map. You described two distinct options:
- option 2a: The expectation is fulfilled if removing the #[expect] attribute would cause the warning to be emitted. IOW: with the attribute, there is no warning; without it, there is a warning. It's basically an `allow` that also checks that it actually allowed something.
- option 2b: The expectation is fulfilled if a warning is emitted inside the scope of the attribute (and then that warning is suppressed).

Those are not the same semantics, they behave different on your [example](https://github.com/rust-lang/rust/issues/115980#issuecomment-1726636175) above. Looks like t-lang was considering 2b during the Zulip discussion, but the summary posted above to me sounds like option 2a.

**Comment by xFrednet** [comment]
During the meeting, I believe we discussed option 1 and option 2b. For option 2 (regardless of 2a or 2b) it was hard to find a short "one sentence" explanation of the semantics. The one in the issue description came from @tmandry. I guess it's the best to wait on a response from himm which option he meant.

**Comment by nikomatsakis** [comment]
OK, I'm having a hard time following all of this. Let me try to restate the "options" as precisely as I can.

## Examples

Here are some examples

**Allowed-Outside**

```
#![allow(unused_variables)]
#[expect(unused_variables)]
fn foo() {
    let x;
```

## Options

**Option 1:** expect-must-supress-a-lint

Consider the same program, but with `#[expect(lint)]` changed to `#[warn(lint)]`. If this would result in a lint being printed, then the program compiles successfully (and no lint is printed).

This means that..

**Comment by nikomatsakis** [comment]
@RalfJung @xFrednet please review the above 👆 -- does it make sense to you?

**Comment by RalfJung** [comment]
Yes that makes sense, thanks.

I think the semantics I expected from expect before delving into this discussion are option 1.

Option 2b means many EXPECT can become fulfilled by a single lint being emitted. That seems very non-intuitive to me. But I also didn't really consider nesting `#[expect]` in the first place...

**Comment by nikomatsakis** [comment]
@xFrednet Yes. I think you are correct, I made some mistakes. Here is how I defined Option 2b (annotated):

> If (a) `stack_level(stack)` is WARN|DENY, and (b) there is at least one `EXPECT` on the stack, then mark all `EXPECTs` on the stack at a time as fulfilled and suppress the warning.

On this basis, I agree with your results for Option 2b. Allowed-Outside and Allowed-Inside ❌, because part a (`stack_stack=WARN|DENY`) is not fulfilled -- the stack-level is ALLOW. Warn-Inside is ✅ because we would get a warning and an EXPECT is on the stack, so it is fulfilled.

**Comment by tmandry** [comment]
Reviewing the comments here, I agree that Option 1 is the most reasonable overall.

There is a use case I had in mind that essentially does want to act more like a try/catch, which would be overriding a warn attribute on some inner code you don't control (like a macro expansion). But that doesn't seem to come up in practice, and if it did it would best be serviced with a different attribute (or compiler flag).

@rfcbot reviewed

**Comment by riking** [comment]
Has anyone discussed what the behavior with renamed and removed lints will be?

One fairly straightforward possibility is to 🟡 renamed_and_removed_lints and turn it into a `#[expect(warnings)]` wildcard expect.

**Comment by traviscross** [comment]
@rustbot labels -I-lang-nominated

This is now in FCP, so we can unnominate this.

**Comment by xFrednet** [comment]
> Has anyone discussed what the behavior with renamed and removed lints will be?
> 
> One fairly straightforward possibility is to 🟡 renamed_and_removed_lints and turn it into a `#[expect(warnings)]` wildcard expect.
>
> ~@riking [Comment](https://github.com/rust-lang/rust/issues/115980#issuecomment-1910680142)

Turning it into a wildcard `#[expect(warnings)]` would seem weird to me. The implementation tries to behave as similar to other lint attributes as possible. This means that only the lint level of known lints is effected. Unknown lints, trigger the `unknown_lints` lint and are then ignored. Here is an example ([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=b0f1dbc01681475b7415a8b7671154af)):

```rs
#![feature(lint_reasons)]

#[expect(
    unused_mut,
//  ^^^^^^^^^^
//  This creates an expectation which is fulfilled.
//  Nothing is emitted for this one.
    duck_and_such,
//  ^^^^^^^^^^^^^
//  This is an unknown lint for Rust 1.77. The
//  `unknown_lints` lint is emitted, but no expectation
//  is created.
    unused_variables,
//  ^^^^^^^^^^^^^^^^
//  This creates an expectation that is unfulfilled, since
//  all variables are used. Therefore, `unfulfilled_lint_expectations`
//  is emitted for this lint.
)]
fn main() {
    let mut x = 10;
    println!("{x}");
}

```

**Comment by ehuss** [comment]
> Has anyone discussed what the behavior with renamed and removed lints will be?

To clarify, the behavior for renamed lints is that the old lint name still works as-if you used the new lint name, plus it will fire `renamed_and_removed_lints`.

Removed lints will fire `renamed_and_removed_lints`, which I would think is a sufficient indicator to the user to go figure out what they need to do.
