### ISSUE TITLE
unknown unstable option: `ignore-directory-in-diagnostics-source-blocks`

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#115977]
When I run `./x.py test` locally, I get errors:

```
---- [ui] tests/ui-fulldeps/session-diagnostic/invalid-variable.rs stdout ----

error: test compilation failed although it shouldn't!
[..]
--- stderr -------------------------------
error: unknown unstable option: `ignore-directory-in-diagnostics-source-blocks`
------------------------------------------
```

(Same for 27 ui-fulldeps tests in total.)

I assume this happened after https://github.com/rust-lang/rust/pull/115869. cc @pietroalbini

**Comment by m-ou-se** [comment]
Yup, it works fine with `./x.py test --stage=2` here.

**Comment by compiler-errors** [comment]
#114482 #114102

I think we should just test `ui-fulldeps --stage=1` in CI to make sure this doesn't keep happening. See the description of #114102 to understand why ui-fulldeps actually builds with stage0, which means that modifications to the UI test code adding new flags need to make sure they're properly gating their code.

**Comment by compiler-errors** [comment]
Either that, or we need something like `-Zignore-missing-flags` and pass that just to the ui-fulldeps suite on stage1. That seems more like a hack though :s

**Comment by Mark-Simulacrum** [comment]
@compiler-errors https://github.com/rust-lang/rust/blob/master/src/ci/docker/host-x86_64/x86_64-gnu-llvm-15/script.sh#L6 should be pretty easy to extend with a --stage=1 for ui-fulldeps.

**Comment by compiler-errors** [comment]
Cool, will do when I get home.
