### ISSUE TITLE
Unhelpful message when not using value from a loop break

### ISSUE THREAD

**Issue by not-holar** [rust-lang/rust#115905]
### Code

```Rust
loop {
    break Some(1);
}
```

### Current output

```Shell
error[E0308]: mismatched types
  --> src\main.rs:24:15
   |
24 |         break Some(1);
   |               ^^^^^^^ expected `()`, found `Option<{integer}>`
   |
   = note: expected unit type `()`
                   found enum `Option<{integer}>`

error: aborting due to previous error
```

### Desired output

```Shell
loop value is never used so
break expected unit type `()`
              found enum `Option<{integer}>`
```

### Rationale and extra context

It might not be too hard to figure what the issue is in such a simple example as the above, but when you have multiple levels of nesting with complex layered types, this can quickly become a source of frustration as it sends you on a wild chase of misdirection.

**Comment by darklyspaced** [comment]
i don't really see this as something that needs to be changed. adding the clause about how the loop's value is never used just seems to needlessly complicate things more for me.
