### ISSUE TITLE
`wrapping_rem` methods should document panic-on-zero

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/rust#116063]
### Location

All [`wrapping_rem` methods](https://doc.rust-lang.org/std/?search=wrapping_rem).

### Summary

As reported in https://github.com/yoshuawuyts/futures-concurrency/issues/156, when calling the `wrapping_rem` functions with a value of `0`, a panic is triggered. The documentation of the `wrapping_rem` method should include a `# panic` section making note of this.

## Example

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ad6cddf6a62fc0be982be8fec7799ba7)

```rust
100usize.wrapping_rem(0);
```
```text
thread 'main' panicked at 'attempt to calculate the remainder with a divisor of zero',
```

**Comment by Colonial-Dev** [comment]
It seems that this is correctly documented for the signed integer types, but *not* the unsigned ones.
