### ISSUE TITLE
Add operations for easy arithmetic that panics on overflow

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#116064]
See the ACP at https://github.com/rust-lang/libs-team/issues/270. The ACP has been seconded so it seems like the next step is implementation. This should be fairly easy to do, just following the patterns established by the existing methods and adjusting them to panic on overflow.

**Comment by shelovesmox** [comment]
Is this issue still persistent/available to pick up?

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/pull/116090 is implementing this, it's just waiting for review.

**Comment by eduardosm** [comment]
With https://github.com/rust-lang/rust/pull/116090 merged and https://github.com/rust-lang/rust/issues/118260 as tracking issue, this could be closed.

**Comment by RalfJung** [comment]
Great :)
