### ISSUE TITLE
Fixed value in "struct" should not require manual type addressing

### ISSUE THREAD

**Issue by Kawaxte** [rust-lang/rust#116051]
When creating a `struct` with a set value, like here:
```rs
pub struct Colour(u32);

impl Colour {
    pub const BLACK: u32 = 0x000000;
    pub const WHITE: u32 = 0xFFFFFF;
}
```

It should NOT require the user to manually address the types for the constants when the ``struct`` has pre-defined the type of value.

If written as:
```rs
pub struct Colour(u32);

impl Colour {
    pub const BLACK = 0x000000;
    pub const WHITE = 0xFFFFFF;
}
```

The compiler will complain that the types have not been defined, despite the ``struct`` having the value set already. The compiler should already know the value after having been set in ``struct``.

**Comment by Kawaxte** [comment]
> Associated consts can have entirely unrelated types. For example
> 
> ```rust
> pub struct Colour(u32);
> 
> impl Colour {
>     pub const IS_COLOUR: bool = true;
> }
> ```

While that part I can understand, wouldn't it make sense for the ``struct`` to know what value has been given as a parameter so 1hat it chould check if any variables in the ``impl`` have values that match said parameter's type?

**Comment by saethlin** [comment]
> wouldn't it make sense for the `struct` to know what value has been given as a parameter so 1hat it chould check if any variables in the `impl` have values that match said parameter's type?

No. In your example:
```rust
pub struct Colour(u32);

impl Colour {
    pub const BLACK = 0x000000;
    pub const WHITE = 0xFFFFFF;
}
```
the associated consts `BLACK` and `WHITE` are being initialized with an `i32`. The default type of numeric literals is already a common tripping hazard, so my preference here (as with most places) is to be explicit.

If you want to propose a new feature you should write an RFC, or write a pre-RFC and post it somewhere like https://internals.rust-lang.org/. The rust-lang/rust issue tracker just isn't a good place to discuss something you want as a new feature, even if it's a really good idea.
