### ISSUE TITLE
`todo!` documentation should mention optional format arguments

### ISSUE THREAD

**Issue by Marcono1234** [rust-lang/rust#116130]
### Location

https://doc.rust-lang.org/std/macro.todo.html

### Summary

The documentation of the `todo!` macro currently does not mention at all that it also accepts optional format arguments, for example:
```rust
todo!("with {}", 1);
```

Other macros like `unimplemented!` at least have the following sentence under "Panics":
> Like `panic!`, this macro has a second form for displaying custom values.

So maybe it would be good to do the following?
- [ ] Update the "Panics" section to be similar to https://doc.rust-lang.org/std/macro.unimplemented.html#panics
- [ ] Extend / adjust example to also show usage of custom message

**Comment by Colonial-Dev** [comment]
Any [opinions](https://github.com/Colonial-Dev/rust/commit/4e6c744d2ddfd118df1dae336f963bb1cde41150)?

I mostly drew from the docs for `unimplemented!`, and I also took the liberty of cleaning up some of the formatting/typography.

**Comment by Marcono1234** [comment]
Thanks! To me this looks good, but I don't know what the maintainers think.
