### ISSUE TITLE
"auto trait" syntax gets accepted on stable in cfg-disabled code

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#116121]
The following code builds on stable without even a warning:
```rust
#[cfg(any())]
auto trait Foo {}
```
That is surprising since there was some effort recently to start ensuring that unstable syntax does not "leak" into stable Rust, so I expected at least a future-compatibility warning. (See e.g. https://github.com/rust-lang/rust/pull/99935)

Cc @petrochenkov  @CAD97

**Comment by Nilstrieb** [comment]
from the code I'd expect a warning:
https://github.com/rust-lang/rust/blob/44bd31c2163c944dbf061f52418900b11e1b707c/compiler/rustc_ast_passes/src/feature_gate.rs#L45

**Comment by Nilstrieb** [comment]
ah no, auto traits don't use that gating:
https://github.com/rust-lang/rust/blob/44bd31c2163c944dbf061f52418900b11e1b707c/compiler/rustc_ast_passes/src/feature_gate.rs#L301

When parsing an auto trait in the parser, we need to gate it's span and then in the feature gating pass gate it too. This will look similar to, for example, trait_alias.

**Comment by CAD97** [comment]
#99935 was just for syntax which was previously attempted to reverse stabilization and had the gating code there but disabled. Now that the plumbing exists, using that as a template to add this syntax to the warning should be fairly straightforward.

It might make sense to go ahead and crater immediately making this a hard feature gate, though.

**Comment by Nilstrieb** [comment]
I can already tell you of one regression, the [PyO3 crate](https://github.com/PyO3/pyo3/blob/673c45aac34441253778645edb5d21411f4a4c80/src/marker.rs#L261). We should do the feature gating normally and worry about making it an error later. Once it's a warning, people adding uses get warnings and we should be fine.

**Comment by Nilstrieb** [comment]
A bit unrelated, but I think it would be useful to have docs somewhere that show how to resolve this issue if you have the feature behind a cfg, the easiest solution being a macro_rules macro.
```rust
#[cfg(feature = "nightly")]
macro_rules! define {
  ($($tt:tt)*) => { $($tt)* }
}
#[cfg(not(feature = "nightly"))]
macro_rules! define {
  ($($tt:tt)*) => {}
}

define! { pub auto trait Uwu {} }
```
But that doesn't have to be fixed here.

**Comment by JuiceDrinker** [comment]
I'd like to claim this issue but I'm not sure where to start. Could someone help me understand how to investigate this?
