### ISSUE TITLE
Rust does not specify IEEE 754 rounding mode for signed zero

### ISSUE THREAD

**Issue by orlp** [rust-lang/rust#116339]
### Location

https://doc.rust-lang.org/std/primitive.f32.html

### Summary

The Rust documentation on `f32` states (emphasis mine):

> When the number resulting from a primitive operation (addition, subtraction, multiplication, or division) on this type **is not exactly representable** as f32, it is rounded according to the roundTiesToEven direction defined in IEEE 754-2008. 

However, this does not specify the behavior for `-0.0f32 + 0.0f32`. This value is exactly representable, the issue is in fact that it is representable in *two ways*. According to the IEEE754-2019 standard the behavior should be:

> When the sum of two operands with opposite signs (or the difference of two operands with like signs) is exactly zero, the sign of that sum (or difference) shall be +0 under all rounding-direction attributes except roundTowardNegative; under that attribute, the sign of an exact zero sum (or difference) shall be -0.

In other words, the behavior depends on the rounding mode. We should specify that in this scenario we also follow the roundTiesToEven rounding mode, that is, the result of `-0.0f32 + 0.0f32` should be `0.0f32`.

**Comment by thomcc** [comment]
IMO this is just a docs bug, where we were overly strict by specifying that the rounding mode only matters when the result "is not exactly representable". Patches should be welcome.

**Comment by orlp** [comment]
I agree, there is no reasonable world in which we'll use a different behavior for signed zero than what IEEE 754 prescribes for roundTiesToEven. What would better wording be?

**Comment by thomcc** [comment]
Something along the lines of "is not exactly representable as a unique f32" perhaps?

**Comment by orlp** [comment]
@thomcc I made a PR with an alternate wording I like. It simply drops any condition on rounding, simply stating we use the roundTiesToEven rounding mode, and clarifying what happens with sums.
