### ISSUE TITLE
linking with lld causes product sigsegv on ubuntu 22.04

### ISSUE THREAD

**Issue by LaoLittle** [rust-lang/rust#116504]
I tried this code:

```rust
fn main() {
    println!("Hello, world!");
}

```

I expected to see this happen: `exit code 0`

Instead, this happened: `exit code 139 (interrupted by signal 11: SIGSEGV)`

### Meta

`rustc --version --verbose`:
```
rustc 1.72.1 (d5c2e9c34 2023-09-13)
binary: rustc
commit-hash: d5c2e9c342b358556da91d61ed4133f6f50fc0c3
commit-date: 2023-09-13
host: x86_64-unknown-linux-gnu
release: 1.72.1
LLVM version: 16.0.5
```

`ld.lld --version`:
```
Ubuntu LLD 14.0.0 (compatible with GNU linkers)
```

`cat /proc/version`:

---
<pre><font color="#444444">───────┬────────────────────────────────────────────────────────────────────────</font>
       <font color="#444444">│ </font>File: <b>/proc/version</b>
<font color="#444444">───────┼────────────────────────────────────────────────────────────────────────</font>
<font color="#444444">   1</font>   <font color="#444444">│</font> <font color="#F8F8F2">Linux version 6.2.0-34-generic (buildd@bos03-amd64-059) (x86_64-linux-g</font>
<font color="#444444">    </font>   <font color="#444444">│</font> <font color="#F8F8F2">nu-gcc-11 (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils f</font>
<font color="#444444">    </font>   <font color="#444444">│</font> <font color="#F8F8F2">or Ubuntu) 2.38) #34~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 13:1</font>
<font color="#444444">    </font>   <font color="#444444">│</font> <font color="#F8F8F2">2:03 UTC 2</font>
<font color="#444444">───────┴────────────────────────────────────────────────────────────────────────</font>

</pre>
---

`.cargo/config.toml`: 

```tom[target.x86_64-unknown-linux-gnu]
linker = "lld"
rustflags = [
  "-Lnative=/usr/lib",
  "-Lnative=/usr/lib64",
  "-Lnative=/usr/lib/x86_64-linux-gnu",
  "-Lnative=/usr/lib/gcc/x86_64-linux-gnu/12"
]

```

<details><summary>Backtrace</summary>
<p>

```
Breakpoint 1: where = lld-test`rust_panic + 4 at panicking.rs:755:25, address = 0x00000000000321b4
(lldb) bt
* thread #1, name = 'lld-test, stop reason = signal SIGSEGV: address access protected (fault address: 0x7f6ecbba6000)
  * frame #0: 0x00007f6ecbba6000 lld-test
(lldb) disas
->  0x7f6ecbba6000: jg     0x7f6ecbba6047
```

</p>
</details>

**Comment by saethlin** [comment]
```
  "-Lnative=/usr/lib/gcc/x86_64-linux-gnu/12"
```
In my attempt to reproduce this crash, I realized that this directory does not exist in my Ubuntu 22.04 Docker image. I have gcc 11.4.0. How did you come to have gcc 12?

**Comment by LaoLittle** [comment]
> ```
>   "-Lnative=/usr/lib/gcc/x86_64-linux-gnu/12"
> ```
> 
> In my attempt to reproduce this crash, I realized that this directory does not exist in my Ubuntu 22.04 Docker image. I have gcc 11.4.0, and your `/proc/version` says the distro was built with gcc 11. How did you come to have gcc 12?

```
gcc-12 --version
gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

and if i linking with gcc11 libs, it sigsegv too

**Comment by LaoLittle** [comment]
https://raw.githubusercontent.com/LaoLittle/rust-lang-rust-issues-116504/main/lld-test

**Comment by saethlin** [comment]
I have no idea what that file is. It doesn't have anything that I recognize as an entrypoint; no `_start`, no `main`, no `lang_start`.

If you want to use LLD with Cargo, use this config
```toml
[build]
rustflags = ["-Clink-arg=-fuse-ld=lld"]
```

**Comment by LaoLittle** [comment]
> I have no idea what that file is. It doesn't have anything that I recognize as an entrypoint; no `_start`, no `main`, no `lang_start`.
> 
> If you want to use LLD with Cargo, use this config
> 
> ```toml
> [build]
> rustflags = ["-Clink-arg=-fuse-ld=lld"]
> ```

Thanks, and I think this issue is the same as https://stackoverflow.com/questions/57812916/how-do-i-change-the-default-rustc-cargo-linker
