### ISSUE TITLE
bootstrap sets `-Zunstable-options` on "check" but not "build", leading to build script reruns

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#116538]
When working on Miri I noticed "portable-atomics" gets rebuilt every time I switch between a check-build and actutally running tests. This boils down to `RUSTFLAGS` being different between the two invocations: in check builds it contains `-Zunstable-options` but in test builds it does not.

**Comment by RalfJung** [comment]
Cc @rust-lang/bootstrap

**Comment by onur-ozkan** [comment]
HEAD: 7cc997d3733707d65017e212e28b22822df24719

![image](https://github.com/rust-lang/rust/assets/39852038/685b5e70-ede7-4441-bdd5-d64b756fff0e)

Seems working fine here.

**Comment by RalfJung** [comment]
I'll have to try if I can till reproduce. But note that I mentioned "test build" above, so this would be `./x.py check miri` vs `./x.py test --stage 0 miri`.

**Comment by RalfJung** [comment]
Yeah I can still reproduce the problems with those invocations. (It's not the latest master but recent enough: 3089c315b1b0cc75aa7c593615fc53390747c248.) Sorry for not giving the exact commands in the issue description.

**Comment by onur-ozkan** [comment]
> gets rebuilt every time I switch between a check-build and actutally running tests

I missed the tests part, sorry.

I just reproduce it too. I will be working on it by the coming week.

@rustbot claim
