### ISSUE TITLE
wrong exit code after ICE

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#116659]
found while checking https://github.com/rust-lang/rust/issues/116658  with
```
rustc 1.75.0-nightly (c1691db36 2023-10-11)
binary: rustc
commit-hash: c1691db366c0f2e2341c60377c248ca2d9335076
commit-date: 2023-10-11
host: x86_64-unknown-linux-gnu
release: 1.75.0-nightly
LLVM version: 17.0.2
```
When you run the snipped above with `--edition`, rustc panics, but the exit status is `1` as if there was just a normal compiler error, instead of a `101`.

This tripped up automatic ice-reduction that relies on a somewhat familiar exit code when the program crashes :sweat_smile:

**Comment by Nilstrieb** [comment]
https://github.com/rust-lang/rust/blob/ab5c841a1f3c09edc5ea07722519627c960aed17/compiler/rustc_query_system/src/query/plumbing.rs#L355

is the problematic line here that turns ICEs into "normal" fatal errors that call exit(1)

though actually at least with the non parallel compiler i'm very surprised that we're ending up in a query in the first place after panicking.

**Comment by matthiaskrgr** [comment]
It seems that current stable does correctly exit with `101`  here...

I bisected the exit code 101 -> exit code 1   change with a crashing file and got to

Regression in nightly-2023-08-31
Regression in 59a8294849358a878a72358aa6d5fe5b9d312867

#115144  cc @Zoxc  / @compiler-errors

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23116659.20wrong.20exit.20code.20after.20ICE)).

@rustbot label -I-prioritize +P-medium
