### ISSUE TITLE
Rust Vec::push is not O(1)?

### ISSUE THREAD

**Issue by vlovich** [rust-lang/rust#116646]
Let me preface and say this problem is super weird & doesn't make sense to me. I'm hoping I didn't make some stupid mistake in the benchmark code (I tried to account & make sure there's no realloc happening on `push`).

I tried this code:

```rust
use criterion::{criterion_group, criterion_main, BenchmarkId, Criterion};

fn vec_push(c: &mut Criterion) {
    let mut group = c.benchmark_group("Vec::push");
    group.throughput(criterion::Throughput::Elements(1));
    for preexisting in [0, 10, 100, 10_000, 1_000_000, 10_000_000] {
        group.bench_with_input(BenchmarkId::new("", preexisting as u64), &(), |b, _| {
            let mut vec = vec![0; preexisting];
            vec.push(0);
            b.iter_batched(
                || {
                    let mut cloned = vec.clone();
                    cloned.pop();
                    cloned
                },
                |mut vec| vec.push(0),
                if preexisting > 10_000 {
                    criterion::BatchSize::LargeInput
                } else {
                    criterion::BatchSize::SmallInput
                },
            );
        });
    }
    group.finish();
}

criterion_group!(benches, vec_push);
criterion_main!(benches);
```

I expected to see the time to insert 1 element to be constant regardless of the number of elements currently in the Vector.

Instead, Criterion reports that the time to insert 1 element is dependent on the number of elements in the Vec. This is strange because the implementation within Vec itself looks fine & O(1). I haven't checked assembly so maybe there's something weird there? 

### Meta
Reproduced on stable & nightly. Also it looks like nightly has regressed even further from what's in stable (20% when no elements, 40% when 10M elements). Benchmarks run with `taskset -c 0`. CPU is 13900 with 64GiB. I don't think this would be a problem with Criterion because even if the iter loop is "too hot", you'd expect Criterion to report the same numbers regardless of the number of elements. Similarly, the numbers reported are really slow per iteration and well outside the documented overhead of `iter_batched`.

```
rustc --version --verbose
rustc 1.72.0 (5680fa18f 2023-08-23)
binary: rustc
commit-hash: 5680fa18feaa87f3ff04063800aec256c3d4b4be
commit-date: 2023-08-23
host: x86_64-unknown-linux-gnu
release: 1.72.0
LLVM version: 16.0.5
```

```
rustc 1.74.0-nightly (203c57dbe 2023-09-17)
binary: rustc
commit-hash: 203c57dbe20aee67eaa8f7be45d1e4ef0b274109
commit-date: 2023-09-17
host: x86_64-unknown-linux-gnu
release: 1.74.0-nightly
LLVM version: 17.0.0
```

Stable:
```
Vec::push//0            time:   [5.3399 ns 5.5640 ns 5.6200 ns]
                        thrpt:  [177.93 Melem/s 179.73 Melem/s 187.27 Melem/s]
Vec::push//10           time:   [11.922 ns 12.330 ns 12.432 ns]
                        thrpt:  [80.440 Melem/s 81.105 Melem/s 83.882 Melem/s]
Vec::push//100          time:   [23.692 ns 24.662 ns 24.904 ns]
                        thrpt:  [40.153 Melem/s 40.548 Melem/s 42.209 Melem/s]
Vec::push//10000        time:   [1.0292 µs 1.0293 µs 1.0297 µs]
                        thrpt:  [971.13 Kelem/s 971.56 Kelem/s 971.66 Kelem/s]
Vec::push//1000000      time:   [108.25 ns 108.68 ns 110.39 ns]
                        thrpt:  [9.0591 Melem/s 9.2017 Melem/s 9.2380 Melem/s]
Vec::push//10000000     time:   [30.593 µs 30.917 µs 30.998 µs]
                        thrpt:  [32.261 Kelem/s 32.345 Kelem/s 32.687 Kelem/s]
```

Nightly:
```
Vec::push//0            time:   [5.3404 ns 5.4387 ns 5.4633 ns]
                        thrpt:  [183.04 Melem/s 183.87 Melem/s 187.25 Melem/s]
Vec::push//10           time:   [11.780 ns 12.303 ns 12.433 ns]
                        thrpt:  [80.430 Melem/s 81.284 Melem/s 84.889 Melem/s]
Vec::push//100          time:   [23.554 ns 23.610 ns 23.836 ns]
                        thrpt:  [41.953 Melem/s 42.355 Melem/s 42.456 Melem/s]
Vec::push//10000        time:   [799.14 ns 816.91 ns 821.36 ns]
                        thrpt:  [1.2175 Melem/s 1.2241 Melem/s 1.2513 Melem/s]
Vec::push//1000000      time:   [128.04 ns 128.82 ns 131.94 ns]
                        thrpt:  [7.5793 Melem/s 7.7628 Melem/s 7.8100 Melem/s]
Vec::push//10000000     time:   [56.094 µs 57.005 µs 57.233 µs]
                        thrpt:  [17.473 Kelem/s 17.542 Kelem/s 17.827 Kelem/s]
```

**Comment by vlovich** [comment]
Oh hmm... I think this may be a criterion issue. A simpler std::time::Instant benchmark reports O(1) behavior.

**Comment by mohe2015** [comment]
I don't know exactly but isn't Vex::push *amortized* O(1) but at some point it runs out if capacity and needs to allocate a larger piece of memory and copy all elements over?

**Comment by vlovich** [comment]
Sure, but that allocate + copy is what amortized refers to. If you want to understand why triggering a resize is still O(1), Dan Lemire recently posted an example using `std::string` https://lemire.me/blog/2023/10/23/appending-to-an-stdstring-character-by-character-how-does-the-capacity-grow/:

> Generally speaking, you find that this incremental doubling approach costs you no more than 2N units of work to construct a string of size N, after rounding N up to a power of two.  In computer science parlance, the complexity is linear. Insertion in a dynamic array with capacity that is expanded by a constant factor ensures that inserting an element is constant time (amortized)

Basically if you have an exponential growth factor, you have O(1) amortized insertion. If you replace the above criterion code with a custom_bench function returning the duration, it yields correct results. Thus it stands to reason the problem is either within Criterion or how the criterion benchmark is written above.
