### ISSUE TITLE
E0277 should use short paths when possible

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#116616]
Type errors (and others) use `tcx.short_ty_string` and similar to write types that are too long to disk, so the cli output is easier to read. Trait bound errors do not do that.

https://twitter.com/ceccon_me/status/1707741832824734186

**Comment by fracek** [comment]
I created [a small repo to reproduce this error message](https://github.com/fracek/async-error-repro). What was not visible in the tweet but that you will see when you build the repo, is that the types in the error notes are even longer. That's a shame because hidden in that noise the compiler gives the solution to the error (pin).

**Comment by Vedaant-Rajoo** [comment]
@fracek You can just create a gist with the error generating logic line highlighted. Much more helpful?

**Comment by fracek** [comment]
I can give more context too. I was implementing a K8s operator using `kube`. 

I start by creating a [Controller](https://docs.rs/kube/latest/kube/runtime/struct.Controller.html) and then running it with `.run`. This returns a [a stream with a relatively complex type](https://docs.rs/kube/latest/kube/runtime/struct.Controller.html#method.run).

```rs
type ReconcileItem<K> = Result<(ObjectRef<K>, Action), controller::Error<MyError, watcher::Error>>;

async fn create_controller(
    client: Client,
) -> Result<impl Stream<Item = ReconcileItem<Pod>>, MyError> {
    let pods = Api::<Pod>::all(client.clone());
    let context = Context { client };

    let controller = Controller::new(pods, watcher::Config::default()).run(
        reconcile,
        error_policy,
        context.into(),
    );

    Ok(controller)
}
```

That stream yields an item every time the reconcile loops reconciles an item or returns an error. For testing, I iterate over the stream to check that it reconciles items the way I expect.

```rs
    let mut controller = create_controller(client).await?;
    while let Some(_item) = controller.try_next().await? { // <-- this line generates the error
    }
```

[This is the error I get compiling that piece of code](https://gist.github.com/fracek/ba6c4d962bf259b2e7a4ad8cd5fa40f9).

The solution is to pin the stream returned by `create_controller`.

**Comment by Milo123459** [comment]
how would i go about solving this?

@rustbot claim

**Comment by estebank** [comment]
@Milo123459 you can look at how we do it here

https://github.com/rust-lang/rust/blob/94bc9c737ea97d56f9b4076553ac37c05c1e3931/compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs#L3000-L3001

You have to do the same thing but at the very least in the places we print out types to string here:

https://github.com/rust-lang/rust/blob/8d92c996caa8fa1c3e504be5049742b8e6403f67/compiler/rustc_trait_selection/src/traits/error_reporting/type_err_ctxt_ext.rs#L420-L478

**Comment by Vedaant-Rajoo** [comment]
You also need to ensure that the type-shortening is conditional, based on whether the user wants verbose output or not (similar to the existing logic for type errors).

**Comment by estebank** [comment]
@Vedaant-Rajoo `short_ty_string` already checks whether `write_long_types_to_disk` is enabled or not before shortening.

**Comment by Milo123459** [comment]
hi, working on: https://github.com/rust-lang/rust/issues/116616 just confused about how to implement this logic:
```rs
                let msg = format!(
                    "required for `{self_ty}` to implement `{}`",
                    parent_trait_pred.print_modifiers_and_trait_path()
                );
```
into:
```rs
                        let (post_message, pre_message, type_def) = self
                            .get_parent_trait_ref(obligation.cause.code())
                            .map(|(t, s)| {
                                (
                                    format!(" in `{t}`"),
                                    format!("within `{t}`, "),
                                    s.map(|s| (format!("within this `{t}`"), s)),
                                )
                            })
                            .unwrap_or_default();
```

by the looks:
```rs
let trait_predicate = self.resolve_vars_if_possible(trait_predicate);
```
is the same as `parent_trait_pred` and i can call the method on it, but in the formatting (that returns a tuple) im not sure how to call those functions (as t is a string, and calling the function returns a string and pathbuf. in the closure `.map(|(t, s)| {` should i just ignore `t`? or is that a bad approach?
