### ISSUE TITLE
Weird `<const host: bool = true>` generics popping in beta docs

### ISSUE THREAD

**Issue by a1phyr** [rust-lang/rust#116629]
Examples include:
- https://doc.rust-lang.org/beta/core/ptr/struct.NonNull.html#method.dangling
- https://doc.rust-lang.org/nightly/core/cell/struct.OnceCell.html#method.new
- Most of https://doc.rust-lang.org/nightly/core/net/struct.Ipv6Addr.html

This is probably related to the recent addition of `#[rustc_host]`.

![image](https://github.com/rust-lang/rust/assets/47725341/217bcfbd-26aa-46ad-a539-26917a945da5)

**Comment by GuillaumeGomez** [comment]
Thanks for opening this issue! I'll take a look as soon as I can.

**Comment by a1phyr** [comment]
Fixed by #116670 and #116856
