### ISSUE TITLE
Compilation time regression in 1.73 when building the fundsp crate

### ISSUE THREAD

**Issue by irh** [rust-lang/rust#116797]
`1.73` introduced a regression in compilation time when building the [fundsp](https://github.com/SamiPerttu/fundsp) crate. 

Previously, I could expect a clean build of the crate to take ~22s. Now, compilation hangs for several minutes, I haven't left it running longer than that.

I bisected to #114611, and 8378487f2796571da288ac54a4696bd67c0933b8 appears to be the commit that introduces the slowdown. Reverting the commit on the latest master brings `fundsp` build times back to normal.

**Comment by saethlin** [comment]
I think this is the same root cause as https://github.com/rust-lang/rust/issues/116624 and https://github.com/rust-lang/rust/issues/116780.

**Comment by Nilstrieb** [comment]
@nnethercote

**Comment by nnethercote** [comment]
> I think this is the same root cause as #116624 and #116780.

It is the same as #116780. It is *not* the same as #116624, which is slow even in 1.72.

**Comment by nnethercote** [comment]
Good news: #116826 will fix the regression.

Even better news: on my machine this crate took 3m13s to compile. After removing the 3rd and 4th commits from #114611, it dropped to 22s. After reinstating the 4th commit (because the 3rd commit was the problem) it dropped to 9s :)

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23116797.20Compilation.20time.20regression.20in.201.2E73.20when.20building.20t.E2.80.A6)).

@rustbot label -I-prioritize +P-high

@irh in the next day a new nightly with a fix should be out. If you have a chance, feel free to test it and confirm if it fixes for you too. thanks for reporting the issue.

**Comment by irh** [comment]
@apiraino I tested it on master, and can confirm it's fixed.

@nnethercote Thanks for taking a look at this so quickly! I also get the 9s build time, very nice 🥳
