### ISSUE TITLE
Endless Compilation when Successive Calling to  `map`

### ISSUE THREAD

**Issue by iamanonymouscs** [rust-lang/rust#116780]
`cat hang.rs`

```rust
#![crate_type = "lib"]
#[no_mangle]
pub fn get_len() -> usize {
    [1, 2, 3].iter(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map().collect::<Vec<_>>().len()
}
```

I expected to see this happen: *The compiler compiles successfully or outputs an error message.*

Instead, this happened: *The code, as provided below, appears to encounter a hang*

### Command
`rustc  -C opt-level=0  hang.rs`

### Meta

`rustc --version --verbose`:
```
rustc 1.73.0 (cc66ad468 2023-10-03)
binary: rustc
commit-hash: cc66ad468955717ab92600c770da8c1601a4ff33
commit-date: 2023-10-03
host: x86_64-unknown-linux-gnu
release: 1.73.0
LLVM version: 17.0.2
```
The same problem is reproduced on the nightly version(2023-10-15;`42b1224e9eb37177f608d3f6a6f2be2ee13902e4`)

<details><summary>Backtrace</summary>
<p>

```
error[E0061]: this method takes 0 arguments but 1 argument was supplied
 --> hang.rs:4:15
  |
4 |     [1, 2, 3].iter(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| x).map(|x| ...
  |               ^^^^ -----
  |                    |
  |                    unexpected argument of type `[closure@hang.rs:4:20: 4:23]`
  |                    help: remove the extra argument
  |
note: method defined here
 --> /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/slice/mod.rs:1001:12
```

</p>
</details>

**Comment by DaniPopes** [comment]
searched nightlies: from nightly-2023-08-01 to nightly-2023-10-16
regressed nightly: nightly-2023-08-19
searched commit range: https://github.com/rust-lang/rust/compare/07688726805d5db0a4bca445a6651d09708041ea...d06ca0ffaf4ac72732665f99dd9ad962194cd0b3
regressed commit: https://github.com/rust-lang/rust/commit/a1e1dba9cc40a90409bccb8b19e359c4bdf573e5

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.7</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start 2023-08-01 --timeout 2 
```
</details>

#114611 cc @nnethercote
