### ISSUE TITLE
SocketAddrV6 Ord and Eq disagree with each other

### ISSUE THREAD

**Issue by ds84182** [rust-lang/rust#116711]
I tried this code:

https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=5c3bc19334a7cf61d10517e874f8cf0b

I expected to see this happen: `Equals, true`

Instead, this happened: `Equals, false`

### Meta
yeah so SocketAddr behaves differently in a HashMap vs BTreeMap. Not only is this surprising but it also conflicts with the documentation for Ord & PartialOrd.

**Comment by whentze** [comment]
This is caused by `Eq` being derived but `Ord` being manually implemented for `SocketAddrV6`, with the Order impl only taking into account address and port, ignoring flowinfo and scope_id.
