### ISSUE TITLE
`-Z unpretty=expanded` leads to invalid syntax for unicode escapes in format strings

### ISSUE THREAD

**Issue by narpfel** [rust-lang/rust#116799]
I tried this code ([Godbolt link](https://godbolt.org/z/1TWG65ded)):

```rust
pub fn main() {
    println!("\x1B[1mHello, world!\x1B[0m");
    println!("\u{1B}[1mHello, world!\u{1B}[0m");
    println!("{}", "\x1B[1mHello, world!\x1B[0m");
}
```

I expected to see this happen: When running `rustc -Z unpretty=expanded`, the format string literals for the first two `println!`s should remain valid string literals.

Instead, this happened: This code is generated:
```rust
use ::std::prelude::rust_2015::*;
extern crate std;
pub fn main() {
    {
        ::std::io::_print(format_args!("\u{{1b}}[1mHello, world!\u{{1b}}[0m\n"));
    };
    {
        ::std::io::_print(format_args!("\u{{1b}}[1mHello, world!\u{{1b}}[0m\n"));
    };
    {
        ::std::io::_print(format_args!("{0}\n",
                "\x1B[1mHello, world!\x1B[0m"));
    };
}
```
Note the double `{{` and `}}` in the `\u` escapes.

The escape sequences in the last `println!` are correctly preserved.

This is annoying because it makes it impossible to run `rustfmt` on the macro-expanded source, which is helpful when trying to read macro-generated code.

### Meta

`rustc --version --verbose`:
```
rustc 1.75.0-nightly (42b1224e9 2023-10-15)
binary: rustc
commit-hash: 42b1224e9eb37177f608d3f6a6f2be2ee13902e4
commit-date: 2023-10-15
host: x86_64-unknown-linux-gnu
release: 1.75.0-nightly
LLVM version: 17.0.2
```

**Comment by Nilstrieb** [comment]
I haven't looked at it, but this is probably going wrong somewhere in `compiler/rustc_ast_pretty` when printing `FormatArgs`.

**Comment by narpfel** [comment]
Looks like you’re right:
https://github.com/rust-lang/rust/blob/e7bdc5f9f869219e8d20060b42a09ea10a837851/compiler/rustc_ast_pretty/src/pprust/state/expr.rs#L687-L692
As I understand this, it duplicates curlies regardless of whether they’re part of an escape sequence.
