### ISSUE TITLE
uncaptured lifetimes required to live as long as the opaque type

### ISSUE THREAD

**Issue by aliemjay** [rust-lang/rust#116794]
The following valid code stopped compiling since v1.67, most likely due to #103491:
```rust
fn opaque<'a: 'a>(_: &'a str) -> *mut impl Sized {
    &mut ()
}

fn main() {
    let x = opaque(&String::new()); //~ ERROR temporary value dropped while borrowed
    drop(x);
}
```

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23116794.20uncaptured.20lifetimes.20required.20to.20live.20as.20long.20as.20th.E2.80.A6)).

@rustbot label -I-prioritize +P-medium
