### ISSUE TITLE
Trait bounds of associated types in `where` clauses result in unsatisfied requeriments

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rust#116749]
Feel free to close if duplicated.

```rust
pub trait Foo<TY> {
    type FooAssociatedTy;
}

pub trait Bar {
    type BarAssociatedTy;
    
    fn send<T>()
    where
        T: Foo<Self::BarAssociatedTy>,
        T::FooAssociatedTy: Send;
}

impl Bar for () {
    type BarAssociatedTy = ();

    fn send<T>()
    where
        T: Foo<()>,
        T::FooAssociatedTy: Send,
    {
    }
}
```

Taking aside the errors, a diagnostic suggests adding a weird `T: Foo<()> + Foo<()>` bound.

Things that will make everything compile:

* Remove `T::FooAssociatedTy: Send` (https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=e67dbf2eb726ee22d3470f2a082b1980)
* Remove `TY` (https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=3b8275f7670e6a82dc9cd459815e66a9)
* Remove `type BarAssociatedTy` (https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=745e08b27876ac261ad2bf9178b2cc79)

**Comment by fmease** [comment]
Fixed in the next solver (`-Ztrait-solver=next`).
Very similar to #41118, #108933 and #116377.

**Comment by c410-f3r** [comment]
Thanks! :)

**Comment by lcnr** [comment]
closing as dup of #41118, see the explanation in https://github.com/rust-lang/rust/issues/41118#issuecomment-1808003426
