### ISSUE TITLE
rustfmt: Empty where clause is unindented to line start

### ISSUE THREAD

**Issue by jdahlstrom** [rust-lang/rust#116860]
Consider this code:

```rust
mod foo {
    fn foo() -> i32
    where 
    {
    }
}

```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=72cf8595307210bcd3ed153874ed5ac3))

I expected rustfmt to remove the  empty `where` clause, as it does in other cases:
```rust
mod foo {
    fn foo() -> i32 {}
}
```
Instead, it was formatted as:
```rust
mod foo {
    fn foo() -> i32 
where {
    }
}
```
The `where` is unindented to column zero no matter how deep down the function is. This also occurs if the where clause content is commented out, which can happen when testing things out:
```rust
mod foo {
    fn foo() -> i32 {
    where 
        // i32: Copy + Eq
    {
    }
}
```
becomes
```rust
mod foo {
    fn foo() -> i32 {
where 
        // i32: Copy + Eq
    {
    }
}
```
If the `where` is on the same line as the rest of the function signature, it's not dropped to its own line, but is not removed either.

If the function has no specified return type, rustdoc eats the empty `where` which I assume is the intended behavior:
```rust
mod foo {
    fn foo() 
    where {
    }
}
```
becomes
```rust
mod foo {
    fn foo() {
    }
}
```

`rustdoc --version --verbose`:
```
% rustdoc --version --verbose
rustdoc 1.73.0 (cc66ad468 2023-10-03)
binary: rustdoc
commit-hash: cc66ad468955717ab92600c770da8c1601a4ff33
commit-date: 2023-10-03
host: aarch64-apple-darwin
release: 1.73.0
LLVM version: 17.0.2
```

**Comment by compiler-errors** [comment]
This should be filed on the rustfmt repo, I think

**Comment by jdahlstrom** [comment]
Oops, sorry! I confused librustdoc and rustfmt.
