### ISSUE TITLE
regression when relating two opaque types in canonical queries

### ISSUE THREAD

**Issue by aliemjay** [rust-lang/rust#116877]
Each revision of this test is an ICE in 1.75.0-nightly (2023-10-17 09df6108c84fdec40004):
```rust
// revisions: sized clone

#[cfg(sized)] fn rpit() -> impl Sized {}
#[cfg(clone)] fn rpit() -> impl Clone {}

fn same_output<Out>(_: impl Fn() -> Out, _: impl Fn() -> Out) {}

pub fn foo() -> impl Sized {
    same_output(rpit, foo);
    same_output(foo, rpit);
    rpit()
}
```

Both revisions have a somewhat convoluted history best shown in a table form:

|   | `sized` | `clone`
|---|---|---|
| stable 1.73 | PASS :ok: | ICE :ice_cube: 
| #114586 (1.74.0-beta) | PASS :ok: | PASS :ok:
| #116530 (1.75.0-nightly)| ICE :ice_cube:  | ICE :ice_cube:

While it may seem like #116530 is the culprit, I'd argue that the PR #114586 introduced an incomplete fix that I don't believe we should commit to in stable. Additionally, reverting #114586 while keeping #116530 would fix `sized` version as well as an other regression https://github.com/rust-lang/rust/pull/114586#issuecomment-1751967321, making it the right choice in my opinion.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23116877.20regression.20when.20relating.20two.20opaque.20types.20in.20canoni.E2.80.A6)).

@rustbot label -I-prioritize +P-critical

**Comment by aliemjay** [comment]
#116879 was backported to beta; `clone` revision of the test above no longer passes in beta and `sized` revision is no longer an ICE in nightly.
