### ISSUE TITLE
Document that null is 0

### ISSUE THREAD

**Issue by joshlf** [rust-lang/rust#116895]
This has come up in two places recently: https://github.com/rust-lang/rust/pull/115333#issuecomment-1767199388 and https://github.com/rust-lang/rust/pull/116675#discussion_r1357784439.

We should do the following:
- On `ptr::null()`, document that `ptr::null()` is equivalent to `0usize as *const _`
- Either before or after it lands, update the text in [#116675](https://github.com/rust-lang/rust/pull/116675) to document that "allocated objects" cannot contain the 0 address (alternatively, if that PR lands with text that says that an allocated object cannot contain the "null" address, update the text to mention that null is equal to 0)

Are there other places we should update too?

cc @the8472 @tmandry @RalfJung

**Comment by Nilstrieb** [comment]
there was some discussion in https://rust-lang.zulipchat.com/#narrow/stream/136281-t-opsem/topic/Null.20vs.200

**Comment by RalfJung** [comment]
> document that ptr::null() is equivalent to 0usize as *const _

Int-to-ptr casts are terrible, I'd rather not do that. In fact these two are not equivalent for Miri (but that might be a Miri limitations, int2ptr is just hard or impossible to handle precisely for a tool like Miri).

We should say that it returns a pointer whose address is 0, but we shouldn't commit to which provenance it has.

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/pull/116988 adds the docs for this.
