### ISSUE TITLE
The seemingly contradictory `#[repr(Rust, C)]` is allowed

### ISSUE THREAD

**Issue by fmease** [rust-lang/rust#116825]
`#[repr(Rust)]` is already on beta and will soon hit stable.

I just found out that `#[repr(C, Rust)]` successfully compiles while I expected it to error due to contradictory representations.

~~Further, I wonder if `#[repr(Rust, transparent)]` should be allowed? Currently it errors with [E0692](https://doc.rust-lang.org/error_codes/E0692.html), *transparent struct cannot have other repr hints*.~~ (see err's response)

**Comment by compiler-errors** [comment]
Seems pretty obvious we should have exactly one repr, and only allow repr modifiers like `packed` afterwards. `(Rust, transparent)` seems like it's asking for two things.

**Comment by marmeladema** [comment]
Should a C-struct be able to contain a Rust-struct ?
Currently the compiler is happy about this kind of construct too: https://play.rust-lang.org/?version=beta&mode=debug&edition=2021&gist=0588a57ac361ed85664914d86cb14060

If not, it might deserve it's own issue?

**Comment by workingjubilee** [comment]
That seems kosher to me? It might not be if
```rust
#[repr(C)]
pub struct ReprC(ReprRust, ReprRust);
```
But that's a different matter and has more to do with defining tuples in C being unclear.

**Comment by fmease** [comment]
Fixed in #116829 and backported in #117005. Closing as completed.
