### ISSUE TITLE
Equivalent to Python atexit functionality

### ISSUE THREAD

**Issue by bmurphy1976** [rust-lang/rust#11695]
I can't always guarantee that users are going to properly use a library (calling init methods, cleanup methods, etc.).

Occasionally things die horribly and you want to provide stronger guarantees about when things fail.  

Is there a way to hook up to an exit signal of sorts to execute code when a program exits regardless of the exit mechanism?  Something like Python atexit?

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#712
