### ISSUE TITLE
please update src/stage0.json for beta channel

### ISSUE THREAD

**Issue by stefson** [rust-lang/rust#116991]
hi, 

beta channel still uses beta rust-std+rustc to compile the branch, as per src/stage0: 

```
  "compiler": {
    "date": "2023-08-22",
    "version": "beta"
  },
```
Can you please update this to stable-1.73.0? I run my own custom target, and am unable to beta test for rust-1.74.0 at the moment. 

thanks

**Comment by ehuss** [comment]
This will be completed by #117005.

**Comment by ChrisDenton** [comment]
closing this as per the above comment
