### ISSUE TITLE
schroedingers `instrument-coverage`

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#116980]
It seems that we have both `-Zinstrument-coverage=val` and `-Cinstrument-coverage=val` at the same time, since its already stabilized I guess we could remove the corresponding `-Z`flag?

**Comment by Zalathar** [comment]
It looks like the stabilization PR (#90128) deliberately left in the `-Z` flag to ease migration for people who were already using coverage.

Given that it's now been stable for almost 2 years, and the `-C` flag supports the unstable values (via `-Zunstable-options`) I can't imagine anyone would object too loudly to its removal now.

**Comment by Zalathar** [comment]
Note that the same thing was also done when stabilizing `-Csymbol-mangling-version=v0` at around the same time, so that flag is probably in the same boat.

**Comment by Zalathar** [comment]
Also it looks like the stabilization PR also wired up `-Zinstrument-coverage` to issue a deprecation warning on use.
