### ISSUE TITLE
Code written in fn_ptr_trait is optimized away

### ISSUE THREAD

**Issue by cathaysia** [rust-lang/rust#116937]
rustc version:

> rustc 1.73.0-nightly (500647fd8 2023-07-27)

I'm currently writing ffi related code. Some of the codes use function pointers from the C language. There are a small number of function pointers that need to be judged to be null pointers, so I used fn_ptr_trait to get the function address. This works fine in debug mode. However, in release mode all relevant code is optimized away. How can I stop this behavior?

**Comment by cathaysia** [comment]
and I get this: 
![image](https://github.com/rust-lang/rust/assets/42114817/d8bc652d-c28f-4f4e-a023-02f806a681e0)

**Comment by Urgau** [comment]
As the the [`incorrect_fn_null_checks` lint](https://doc.rust-lang.org/rustc/lints/listing/warn-by-default.html#useless-ptr-null-checks)¹ is saying function pointers cannot **ever** be null. It's [**UB**](https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html) for them to be null.

To make them nullable follows what the lint is saying and wrapped your fn pointer into an `Option` like this:
```diff,rust
- extern "C" { fn get_fn() -> extern "C" fn() -> i8; }
+ extern "C" { fn get_fn() -> Option<extern "C" fn() -> i8>; }
```

¹ *was renamed to `useless_ptr_null_checks` in a newer version*

@rustbot labels -needs-triage -C-bug

**Comment by asquared31415** [comment]
And relatedly, the code that runs if they are null would only run if UB occurred, so the optimizer is deleting it all in the name of speed.

**Comment by cathaysia** [comment]
Currently I have bypassed this problem with read_volatile. If rs is not going to "fix" this problem, it would be nice to add proper documentation to the addr() function to guide users to other methods.

**Comment by cathaysia** [comment]
ref: https://github.com/rust-lang/rust/issues/40913
It looks like I have some misunderstanding about Option<Fn>. It failed the last time I used it, I need to retest it tomorrow.

**Comment by Urgau** [comment]
You only have to express the `Option<extern "C" fn(...) -> ...` in the Rust signature as C allows function pointer to be nullable.

> Currently I have bypassed this problem with read_volatile.

This is still UB. `rustc`/`LLVM` might not be able to optimize it away now but it certainly can and could do it in the future. `Option` in the signature is the only way to make it sound.

> In fact, the "Option" mentioned in lint is not available, because cbindgen cannot work with such a signature, it will generate an Option_xxx type in function signature, but Option does not exist in C.

This seems to be a bug to me. That should be reported to the `cbindgen` project.
