### ISSUE TITLE
rustc --test -l static=somelib.a links with --whole-archive

### ISSUE THREAD

**Issue by xclaesse** [rust-lang/rust#116910]
Originally reported as https://github.com/rust-lang/rust/issues/116900, but the actual bug affects every libraries and platforms.

`rustc --test -l static:+verbatim=libsomelib.a` generates the linker command `-Wl,--whole-archive -l:libsomelib.a -Wl,--no-whole-archive`. Without `--test` it correctly doesn't link whole archive.

It is expected to link whole archive only if passing `+whole-archive` modifier.

**Comment by Nilstrieb** [comment]
@petrochenkov @lqd @bjorn3 or whoever wants to look at linkage troubles today

**Comment by bjorn3** [comment]
Looks like it is a back compat hack: https://github.com/rust-lang/rust/blob/a01382dbea73c1442de1cf180333c273f82f710b/compiler/rustc_codegen_ssa/src/back/link.rs#L2471-L2478

**Comment by xclaesse** [comment]
Not sure to understand why tests are special, but it's intentional from https://github.com/rust-lang/rust/pull/95606 indeed. Feels like a bad workaround for missing +whole-archive modifiers in some projects?

**Comment by bjorn3** [comment]
My reading from the code comment is that you can't aren't allowed to use `+whole-archive` for tests of rlib crates at all, not that some projects are missing it.

**Comment by xclaesse** [comment]
> you  aren't allowed to use `+whole-archive` for tests of rlib crates at all

Why is that not allowed? That would be the root issue then?

**Comment by bjorn3** [comment]
It seems like `+bundle` and `+whole-archive` are not compatible with each other for rlibs. Someone else may know better why this is the case. It's been a while since I last looked at this code.

**Comment by petrochenkov** [comment]
The `+bundle,+whole-archive` combination was recently stabilized in https://github.com/rust-lang/rust/pull/113301 so it may be possible to remove this hack now.
We'll just need to run crater, send fixes to affected crates, and all that stuff.

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/128400.
