### ISSUE TITLE
cross-crate inlining breaks compare of functions passed between crates

### ISSUE THREAD

**Issue by AzazKamaz** [rust-lang/rust#117047]
This code panics when compiled with #116505 with cross-crate inlining being turned on:

```rust
// src/main.rs
use lib;
fn main() { lib::verify(lib::create()); }
```
```rust
// src/lib.rs
fn inner() {}
pub fn create() -> fn() { inner }
pub fn verify(value: fn()) { assert_eq!(value, inner as fn()) }
```
```toml
# Cargo.toml
[package]
name = "lib"
version = "0.1.0"
edition = "2021"
```

`cargo +nightly-2023-10-18 run --release` - ok
`cargo +nightly-2023-10-19 run --release` - panics
`cargo +nightly-2023-10-19 run` - ok (`opt-level = 2` `incremental = false` to panic)

It is clearly caused by #116505 because:
- it is ok on ca89f732ec0f910fc92111a45dd7e6829baa9d4b but panics on 5d5edf0248d967baa6ac5cbea09b91c7c9947942
- it requires `opt-level = 2`, `incremental = false` and not `-Zcross-crate-inline-threshold=0` (feature to be enabled)

Ways to fix this minimal example:
- make `create()` `inline(never)` - probably this is not a root cause fix
- set `-Zcross-crate-inline-threshold=0`

Originally I found this problem in [Embassy](https://github.com/embassy-rs/embassy/blob/e70c531d3d28565b6926d99d8e977c4df6c13c60/embassy-executor/src/raw/waker.rs#L42) (embedded framework using async). They are using such a comparison to ensure that passed `Waker` was created by the Embassy executor. In Embassy it is possible to fix it by either:
- making `from_task()` `inline(never)`
- or making `VTABLE` `static`

### Meta

`rustc +nightly --version --verbose` (bug still here):
```
rustc 1.75.0-nightly (1c05d50c8 2023-10-21)
binary: rustc
commit-hash: 1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07
commit-date: 2023-10-21
host: aarch64-apple-darwin
release: 1.75.0-nightly
LLVM version: 17.0.3
```

<details><summary>Precise versions (just skip, too much extra info)</summary>
<p>

#### rustup build - ok
```
rustc 1.75.0-nightly (09df6108c 2023-10-17)
binary: rustc
commit-hash: 09df6108c84fdec400043d99d9ee232336fd5a9f
commit-date: 2023-10-17
host: aarch64-apple-darwin
release: 1.75.0-nightly
LLVM version: 17.0.2
```
#### custom build - ok
```
rustc 1.75.0-nightly (ca89f732e 2023-10-18)
binary: rustc
commit-hash: ca89f732ec0f910fc92111a45dd7e6829baa9d4b
commit-date: 2023-10-18
host: aarch64-apple-darwin
release: 1.75.0-nightly
LLVM version: 17.0.3
```
#### custom build - panics
```
rustc 1.75.0-nightly (5d5edf024 2023-10-18)
binary: rustc
commit-hash: 5d5edf0248d967baa6ac5cbea09b91c7c9947942
commit-date: 2023-10-18
host: aarch64-apple-darwin
release: 1.75.0-nightly
LLVM version: 17.0.3
```
#### rustup build - panics
```
rustc 1.75.0-nightly (0039d739d 2023-10-18)
binary: rustc
commit-hash: 0039d739d40a076334e111488946441378d11cd7
commit-date: 2023-10-18
host: aarch64-apple-darwin
release: 1.75.0-nightly
LLVM version: 17.0.3
```

</p>
</details>

<details><summary>Backtrace</summary>
<p>

```
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: lib::verify
```

</p>
</details>

<details><summary>Example more like in Embassy</summary>
<p>

```rust
// src/lib.rs
#![feature(waker_getters)]

use core::task::{RawWaker, RawWakerVTable, Waker};

const VTABLE: RawWakerVTable = RawWakerVTable::new(clone, wake, wake, drop);

unsafe fn clone(p: *const ()) -> RawWaker { RawWaker::new(p, &VTABLE) }
unsafe fn wake(_: *const ()) {}
unsafe fn drop(_: *const ()) {}

pub fn create() -> Waker {
    unsafe { Waker::from_raw(clone(core::ptr::null())) }
}

pub fn verify(waker: Waker) {
    assert_eq!(waker.as_raw().vtable(), &VTABLE);
}
```

</p>
</details>

**Comment by AzazKamaz** [comment]
This may be related to https://github.com/rust-lang/unsafe-code-guidelines/issues/239 but here are some points on this case:
- it also panics with `codegen-units = 1`
- `PartialEq` for `RawWakerVTable` makes no sense?

**Comment by asquared31415** [comment]
https://github.com/rust-lang/miri/issues/2882#issuecomment-1539775637
> Basically Rust makes no guarantees at all when it comes to fn ptr equality: the 'same' function can have multiple addresses (e.g. if it is called from multiple codegen units / crates, leading to multiple monomorphizations) and different functions can have the same address.

This probably isn't a bug, but deserves some extra docs and maybe a lint.

**Comment by AzazKamaz** [comment]
Agree, it's not a bug, but it really does look like one without a lint when it breaks in release..
With such a description of what happens we can I guess construct a valid fix to original code:
```rust
// src/lib.rs
static INNER: fn() = inner;
fn inner() {}
pub fn create() -> fn() { INNER }
pub fn verify(value: fn()) { assert_eq!(value, INNER) }
```

In this code we are using `static` global variable so any access to `inner()` address happens from single place and we can actually compare such a pointers. (`static` variables are guaranteed to have a single fixed location in memory as stated [in the first edition of the book](https://github.com/rust-lang/book/blob/fc4274d906bfcc526d2a19aba25f44bfaecd877a/first-edition/src/const-and-static.md#static) and [in the actual one](https://github.com/rust-lang/book/blob/3dca2fc50b922a8efb94903b9fee8bb42ab48f38/src/ch19-01-unsafe-rust.md#accessing-or-modifying-a-mutable-static-variable))

On the other hand, making `create()` `inline(never)` isn't really a valid fix since it is about inlining and doesn't ensure/guarantee that the function will exists only once in the memory

**Comment by AzazKamaz** [comment]
As for a possible place to document such a thing I see [Advanced Functions and Closures](https://github.com/rust-lang/book/blob/3dca2fc50b922a8efb94903b9fee8bb42ab48f38/src/ch19-05-advanced-functions-and-closures.md#function-pointers) section of the book and I guess [Items/Functions](https://github.com/rust-lang/reference/blob/16fd3c06d9e558dae2d52000818274ae70c9e90a/src/items/functions.md) page of the reference

**Comment by DCNick3** [comment]
By briefly looking at LLVM IR (`RUSTFLAGS="--emit llvm-ir" cargo +nightly-2023-10-19 rustc --release`, look inside `target/release/deps`) what seems to be happening:

1. `create` is inlined from the lib to the bin crate
2. this inlining also copies the definition of `inner` to the bin crate
3. now you have two copies of `inner` and are trying to compare pointers to them

This seems reasonable, albeit a bit surprising

**Comment by DCNick3** [comment]
One way to stop this surprising behavior might be to not inline functions that take address of other functions? Might be too strict though, forfeiting inlining just because somebody _might_ want to compare function pointers doesn't seem reasonable

**Comment by AzazKamaz** [comment]
Another way to stop this behavior is to not inline functions when their addresses are taken and only inline in case of call. This is more complex I guess but seems more reasonable, there is no point to inline function that is called by address (because it needs to be separate) or to duplicate (it will be the same)

**Comment by DCNick3** [comment]
That's completely fair, I don't know that much about rustc, so my suggestions were more like guesses how I thought this could potentially be implemented. Thanks for taking time to point out _why_ is this infeasible, it's definitely helpful

For the problem at hand though, I guess this just means that we shouldn't rely on function address, which hasn't been true already. Just that there's now more optimizations that can trigger this.

**Comment by RalfJung** [comment]
Do we have an issue tracking "function pointer comparison is non-deterministic", with the goal of having better docs and lints? Basically the fn ptr equivalent of https://github.com/rust-lang/rust/issues/117717, https://github.com/rust-lang/rust/issues/69757, https://github.com/rust-lang/rust/issues/99388.

**Comment by RalfJung** [comment]
Would you consider this to be fixed by https://github.com/rust-lang/rust/pull/120880? That adds a note on the `fn` type docs indicating that comparing function pointers is unreliable. This is hard to find, but I'm also not sure what would be a better place.

**Comment by DCNick3** [comment]
Maybe also add a similar note to `RawWakerVTable`? Otherwise, seems good to me

**Comment by RalfJung** [comment]
Oh you mean, because it has `fn` ptr fields? Hm yeah fair, I do wonder why that type implements `PartialEq` to begin with...

**Comment by DCNick3** [comment]
Yeah, this is how the issue has started: embassy [compares](https://github.com/embassy-rs/embassy/blob/edb3989b577a15bed3d0434f25edc20b6f24bf52/embassy-executor/src/raw/waker.rs#L42) `RawWakerVTable` from a waker to check if belongs to its own executor.

AFAIU, what it does now is still not guaranteed to work, but replacing `const` by `static` stopped the duplicated vtables from appearing in different compilation units.
