### ISSUE TITLE
regression: inference conflicts due to new From imps on Vec<T>

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#117054]
This breaks many libraries that depend on the `tui` crate (see method: https://docs.rs/tui/latest/tui/layout/struct.Layout.html#method.constraints).

```
[INFO] [stdout] error[E0283]: type annotations needed
[INFO] [stdout]   --> src/app/app_parts.rs:18:14
[INFO] [stdout]    |
[INFO] [stdout] 18 |             .constraints(vec![Constraint::Percentage(15), Constraint::Percentage(85)].as_ref())
[INFO] [stdout]    |              ^^^^^^^^^^^                                                              ------ type must be known at this point
[INFO] [stdout]    |              |
[INFO] [stdout]    |              cannot infer type of the type parameter `C` declared on the method `constraints`
[INFO] [stdout]    |
[INFO] [stdout]    = note: multiple `impl`s satisfying `Vec<Constraint>: AsRef<_>` found in the `alloc` crate:
[INFO] [stdout]            - impl<T, A> AsRef<Vec<T, A>> for Vec<T, A>
[INFO] [stdout]              where A: Allocator;
[INFO] [stdout]            - impl<T, A> AsRef<[T]> for Vec<T, A>
[INFO] [stdout]              where A: Allocator;
[INFO] [stdout] help: consider specifying the generic argument
[INFO] [stdout]    |
[INFO] [stdout] 18 |             .constraints::<&T>(vec![Constraint::Percentage(15), Constraint::Percentage(85)].as_ref())
[INFO] [stdout]    |                         ++++++
[INFO] [stdout] 
[INFO] [stdout] 
[INFO] [stdout] error: aborting due to previous error
```

Added in https://github.com/rust-lang/rust/pull/111278.

Around 69 errors likely attributable to this were detected in Crater:

Due to the tui method calls:

* https://crater-reports.s3.amazonaws.com/beta-1.74-4/beta-2023-10-21/gh/777moneymaker.tarnished/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.74-4/beta-2023-10-21/gh/AlmightyFloppyFish.rust-discord-tui/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.74-4/beta-2023-10-21/gh/AsyncEgg.wordle_clone/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.74-4/beta-2023-10-21/gh/Bharadwaja-rao-D.Deadlines-tui/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.74-4/beta-2023-10-21/gh/Julien-R44.fast-ssh/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.74-4/beta-2023-10-21/gh/Krakaw.TOTP/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.74-4/beta-2023-10-21/gh/Kuba429.hangman-tui-rs/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.74-4/beta-2023-10-21/gh/Nooo37.mampf/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.74-4/beta-2023-10-21/gh/NordicHPC.jobgraph/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.74-4/beta-2023-10-21/gh/Phoeenix05.rust-console-pokemon/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.74-4/beta-2023-10-21/gh/Strange-Knoll.ratatui-buttons/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.74-4/beta-2023-10-21/gh/T-Marenk.blue-gear/log.txt
* etc (see https://crater-reports.s3.amazonaws.com/beta-1.74-4/index.html E0283 under root results for more)

Other cases:

* https://crater-reports.s3.amazonaws.com/beta-1.74-4/beta-2023-10-21/gh/gskachkov.houdini-css-wasm/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.74-4/beta-2023-10-21/gh/tomnis.aoc21/log.txt

**Comment by apiraino** [comment]
Added in https://github.com/rust-lang/rust/pull/111278 cc @EFanZh

**Comment by Amanieu** [comment]
We discussed this in the t-libs meeting. We consider this to be acceptable inference breakage due to overly-generic code. We should however add a compatibility note in the release notes.

**Comment by Mark-Simulacrum** [comment]
Closing - we have a pending comments on the relnotes PR.
