### ISSUE TITLE
mention rust_panic in default panic! message

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#11704]
Rust developers are developers.  Many will be used to using a debugger.  Lets tell them straight up from the `panic!` message how they can hook up their debugger without having to know anything about rust's name mangling algorithm.

**Comment by ranma42** [comment]
Used as workaround in #30625, but still discovered from other people instead of documentation.
#30625. Mentioning `rust_panic` in the panic message and possibly in the documentation for `panic!` might be a good idea. If nobody is already doing this, I will :)
