### ISSUE TITLE
multiple parsing options: `const` considered as a potential identifier in macro_rules pattern 

### ISSUE THREAD

**Issue by d34db4b3** [rust-lang/rust#117099]
I was playing around with `macro_rules` and I stumbled upon a strange behavior.
I'm not sure if this is a bug or if I misunderstood something.

I tried this code:

```rust
macro_rules! a {
    (struct $x:ident
        <
            $($generics:ident),* $(,)?
            $(const $consts:ident: consts_types:ty),* $(,)?
        > {
            $($body_data:tt)*
        }) => {
        struct $x<
            $($generics),*,
            $(const $consts: consts_types),*
        > {
            $($body_data)*
        }
    };
}

fn main() {
    a! {
        struct A<A, const N: usize> {
            a: [A; N],
        }
    }
}

```

I expected this to compile fine and be expanded to the following code:

```rust
fn main() {
    struct A<A, const N: usize> {
        a: [A; N],
    }
}
```

Instead, I got this compiler error:
```
error: local ambiguity when calling macro `a`: multiple parsing options: built-in NTs ident ('generics') or 1 other option.
  --> src/main.rs:20:21
   |
20 |         struct A<A, const N: usize> {
   |                     ^^^^^

error: could not compile `sandbox` (bin "sandbox") due to previous error
```

### Meta

I would have not expected a conflict here as the problematic "identifier" is `const` which is not a valid identifier according to <https://doc.rust-lang.org/reference/identifiers.html>

> Identifiers may not be a [strict](https://doc.rust-lang.org/reference/keywords.html#strict-keywords) or [reserved](https://doc.rust-lang.org/reference/keywords.html#reserved-keywords) keyword without the r# prefix described below in [raw identifiers](https://doc.rust-lang.org/reference/identifiers.html#raw-identifiers).

This happens both on stable and nightly.
```
~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc --version --verbose
rustc 1.73.0 (cc66ad468 2023-10-03)
binary: rustc
commit-hash: cc66ad468955717ab92600c770da8c1601a4ff33
commit-date: 2023-10-03
host: x86_64-unknown-linux-gnu
release: 1.73.0
LLVM version: 17.0.2
```
```
$ ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --version --verbose
rustc 1.75.0-nightly (1c05d50c8 2023-10-21)
binary: rustc
commit-hash: 1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07
commit-date: 2023-10-21
host: x86_64-unknown-linux-gnu
release: 1.75.0-nightly
LLVM version: 17.0.3
```

**Comment by compiler-errors** [comment]
Yeah, `const` and other keywords counts as an ident for the purposes of macros.

See rust-lang/rfcs#772, #27899

**Comment by compiler-errors** [comment]
Also the reference notes that `ident` matches an [IDENTIFIER_OR_KEYWORD](https://doc.rust-lang.org/beta/reference/identifiers.html) or [RAW_IDENTIFIER](https://doc.rust-lang.org/beta/reference/identifiers.html)

https://doc.rust-lang.org/beta/reference/macros-by-example.html#metavariables

**Comment by d34db4b3** [comment]
Indeed, do you think we should make it clearer in the documentation? Because I had a deep (not deep enough it seems) at the various references you sent and it did not seem clear to me. `IDENTIFIER_OR_KEYWORD` put me in doubt but I will try to PR the documentation of [macros-by-example](https://doc.rust-lang.org/beta/reference/macros-by-example.html#metavariables).

**Comment by d34db4b3** [comment]
Do we have a workaround for now ?
