### ISSUE TITLE
regression: parsing change in allow()?

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#117058]
https://crater-reports.s3.amazonaws.com/beta-1.74-4/beta-2023-10-21/gh/ken-matsui.diagonal-loop/log.txt

```
[INFO] [stdout] error: expected one of `(`, `,`, `::`, or `=`, found `-`
[INFO] [stdout]   --> src/dim2.rs:28:36
[INFO] [stdout]    |
[INFO] [stdout] 28 |         #[allow(clippy::collapsible-else-if)]
[INFO] [stdout]    |                                    ^ expected one of `(`, `,`, `::`, or `=`
```

**Comment by Nilstrieb** [comment]
searched nightlies: from nightly-2023-08-01 to nightly-2023-10-10
regressed nightly: nightly-2023-09-15
searched commit range: https://github.com/rust-lang/rust/compare/8142a319ed5c1d1f96e5a1881a6546e463b77c8f...ca2b74f1ae5075d62e223c0a91574a1fc3f51c7c
regressed commit: https://github.com/rust-lang/rust/commit/dac91a82e146d89fefe94dcbb53cd6c2662e354f

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.6</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc 2023-08-01 --end 2023-10-10 --access github --regress error 
```
</details>

this bisection may look pretty nonsensical, but I did manually confirm that nightly-2023-09-14 worked and nightly-2023-09-16 didn't. I am surprised that this ever parsed, and given that there's only a single random repo that regressed, and the regressing code is a mistake, I don't think this is a problematic regression. @matthewjasper anyways.

**Comment by Mark-Simulacrum** [comment]
Agreed that we don't necessarily need a fix, but we should try to make sure that this is indeed limited to this one case (i.e., it's not some broader incompatibility that may have gone uncaught in Crater)

**Comment by matthewjasper** [comment]
The change here is that AST validation is now checking that the attribute is valid. Some other cases:

```rust
fn allow_if() {
    #[allow(two-words)]
    if true {} else {}
    #[allow(two-words)]
    (1);
    #[allow(two-words)]
    match 1 { _ => {} }
    #[allow(two-words)]
    while false {}
}
```
