### ISSUE TITLE
regression: no variant found in current scope

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#117053]
https://crater-reports.s3.amazonaws.com/beta-1.74-4/beta-2023-10-21/reg/race-client-0.2.2/log.txt

```
[INFO] [stdout] error[E0599]: no variant or associated item named `new_for_answer` found for enum `race_core::types::SecretShare` in the current scope
[INFO] [stdout]    --> src/lib.rs:160:42
[INFO] [stdout]     |
[INFO] [stdout] 160 |                 shares.push(SecretShare::new_for_answer(
[INFO] [stdout]     |                                          ^^^^^^^^^^^^^^ variant or associated item not found in `SecretShare`
```

**Comment by Nilstrieb** [comment]
searched nightlies: from nightly-2023-08-01 to nightly-2023-10-20
regressed nightly: nightly-2023-09-14
searched commit range: https://github.com/rust-lang/rust/compare/d9c8274fb7e2c9087c27a87bf4d85bf1d78cd1e0...8142a319ed5c1d1f96e5a1881a6546e463b77c8f
regressed commit: https://github.com/rust-lang/rust/commit/735bb7e5df185cc24e56533abd0bbab510931f6f

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.6</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc 2023-08-01 --end 2023-10-20 --access github --regress error 
```
</details>

@bvanjoi @petrochenkov

**Comment by bvanjoi** [comment]
reduced: 

```rs
mod api {
    pub mod types {
        pub mod common {
            pub enum S {}
            impl S {
                pub fn a() {}
            }
        }

        pub use common::S;
    }
}

mod c {
    pub mod types {
        mod common {
            pub use crate::api::types::*;
            #[derive(Debug)]
            pub enum S {}
            impl S {
                pub fn b() {}
            }
        }

        pub use common::*;
    }
}

use c::types::S;

fn main() {
    S::a();
}
```

This fix appears to be as expected. it's strange that the regression test doesn't reflect this.

**Comment by bvanjoi** [comment]
This issue can be resolved once https://github.com/RACE-Game/race/pull/11 gets merged.
