### ISSUE TITLE
regression: cfg_match resolution ambiguity

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#117057]
In:

* https://crater-reports.s3.amazonaws.com/beta-1.74-4/beta-2023-10-21/reg/maybe-dangling-0.1.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.74-4/beta-2023-10-21/reg/cfg-match-0.2.1/log.txt

```
[INFO] [stdout] error[E0658]: use of unstable library feature 'cfg_match'
[INFO] [stdout]   --> src/maybe_dangling.rs:65:1
[INFO] [stdout]    |
[INFO] [stdout] 65 | crate::cfg_match! {
[INFO] [stdout]    | ^^^^^^^^^^^^^^^^
[INFO] [stdout]    |
[INFO] [stdout]    = note: see issue #115585 <https://github.com/rust-lang/rust/issues/115585> for more information
[INFO] [stdout] 
[INFO] [stdout] 
[INFO] [stdout] error: no rules expected the token `feature`
[INFO] [stdout]   --> src/maybe_dangling.rs:66:5
[INFO] [stdout]    |
[INFO] [stdout] 66 |     feature = "nightly-dropck_eyepatch" => {
[INFO] [stdout]    |     ^^^^^^^ no rules expected this token in macro call
[INFO] [stdout]    |
[INFO] [stdout] note: while trying to match `cfg`
[INFO] [stdout]   --> /rustc/489647f984b2b3a5ee6b2a0d46a527c8d926ceae/library/core/src/macros/mod.rs:358:11
[INFO] [stdout] 
[INFO] [stdout] 
[INFO] [stdout] error[E0659]: `cfg_match` is ambiguous
[INFO] [stdout]   --> src/lib.rs:42:5
[INFO] [stdout]    |
[INFO] [stdout] 42 | use cfg_match;
[INFO] [stdout]    |     ^^^^^^^^^ ambiguous name
[INFO] [stdout]    |
[INFO] [stdout]    = note: ambiguous because of a conflict between a macro-expanded name and a less macro-expanded name from outer scope during import or macro resolution
[INFO] [stdout]    = note: `cfg_match` could refer to a macro from prelude
```

**Comment by Nilstrieb** [comment]
@crlf0710

**Comment by Nilstrieb** [comment]
mean to ping @c410-f3r instead 😅

**Comment by c410-f3r** [comment]
The macro was originally named `match_cfg`  to avoid this situation (https://github.com/rust-lang/rust/pull/115416).

I don't know if it is possible to solve this issue in the compiler so I will just revert the changes.

**Comment by Nilstrieb** [comment]
cc @petrochenkov, maybe you have ideas

**Comment by Nilstrieb** [comment]
the problem is that this adds it to the prelude. maybe there's a way to add it somewhere where it doesn't get added to the prelude? for example by making it a macro 2.0. @c410-f3r

**Comment by c410-f3r** [comment]
Looks like a good short-term solution. Preferably, it would be nice to have prelude support with a different name or an acceptable breakage.

**Comment by petrochenkov** [comment]
> cc @petrochenkov, maybe you have ideas

https://github.com/rust-lang/rust/issues/82775#issuecomment-1103168321

**Comment by danielhenrymantilla** [comment]
FWIW, I can take care of fixing `maybe_dangling` too, if that makes things simpler. I don't know about the eponymous `::cfg_match` crate, however.

  - The funny thing is that I am working around the current issue by renaming `cfg_match` as `match_cfg` 🙃, so if this were to become the decision here please let me know so that I pick some third name 😄
