### ISSUE TITLE
Diagnostic doesn't align properly in span where line number increases by one digit

### ISSUE THREAD

**Issue by ktt3ja** [rust-lang/rust#11715]
For example, in this case there should be two spaces between `8` and `fn` instead of one.

```rust
test2.rs:8:1: 12:2 warning: code is never used: `foo`, #[warn(dead_code)] on by default
test2.rs:8 fn foo() {
test2.rs:9 
test2.rs:10 
test2.rs:11 
test2.rs:12 }
```

**Comment by tbelaire** [comment]
I'm going to poke around with this.

**Comment by tbelaire** [comment]
How would you actually get a test to look for this, since compile-fail doesn't seem quite right.

Also, what happens if #3533 goes through?  That'll require undoing these changes...
