### ISSUE TITLE
`std::path::Path::file_name` unfortunate naming

### ISSUE THREAD

**Issue by petar-dambovaliev** [rust-lang/rust#117130]
Is it me or the name of this function does not describe what it does?
According to the documentation and the logic in the body of the function,
it is possible for it to return a directory name, which is not a file name, as the function name suggests.
Actually, the first line in the comment doc block gets it right.
The function should be named `final_component`, `last_component` or something of that sort.

```rust
    /// Returns the final component of the `Path`, if there is one.
    ///
    /// If the path is a normal file, this is the file name. If it's the path of a directory, this
    /// is the directory name.
    pub fn file_name(&self) -> Option<&OsStr>
```

**Comment by ChrisDenton** [comment]
Changing the name would be a breaking change. We could deprecate it and create a new function but that would be a lot of churn for not much gain. Note also that "file" can in fact be used as a category that includes directories too, which is why "non-directory file" is a common term.

**Comment by jdahlstrom** [comment]
FWIW, both C++ (`std::filesystem::path`) and Java (`java.nio.Path`) call the final component of a path the "file name".

**Comment by ChrisDenton** [comment]
I think that's a good enough reason to close this. These sorts of high-churn changes should not be made lightly and the fact that "file name" is commonly used by other standard libraries is a good argument for us doing the same.

**Comment by petar-dambovaliev** [comment]
> FWIW, both C++ (`std::filesystem::path`) and Java (`java.nio.Path`) call the final component of a path the "file name".

I don't think C++ and Java APIs is something we should model our APIs by.
I think, file name is just to generic of a term and in practice, people generally don't refer to folders as files.
But as you mentioned, it might be too much trouble for everybody else for having a bit nicer name.
So closing it was probably the right decision.
