### ISSUE TITLE
Windows go use cgo call rust staticlib error

### ISSUE THREAD

**Issue by diwuwudi123** [rust-lang/rust#117121]
rustc 1.69.0 (84c898d65 2023-04-16)
go  1.23.0
mingw x86_64-w64-mingw32  8.3.0
target  x86_64-pc-windows-gnu
demo: https://github.com/diwuwudi123/rust-cgo/tree/master

`
use std::fs;

#[no_mangle]
pub extern "C" fn hello_world() {

    let test = fs::read("./test.txt").unwrap();

    println!("Hello, {}", String::from_utf8(test).unwrap());
}
`

very simple piece of code,
It's like rust reads a file and outputs it.
then go use cgo call rust staticlib 
it is very stable on the Linux platform
but there are some problems on the Windows platform:

C:/Strawberry/c/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/xxx/Desktop/code/rust-cgo/build/windows/libtest.a(std-4208b5b050761eab.std.d3105bbe-cgu.0.rcgu.o): in function `std::sys::windows::net::last_error':
/rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\sys\windows/net.rs:63: undefined reference to `WSAGetLastError'
C:/Strawberry/c/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/xxx/Desktop/code/rust-cgo/build/windows/libtest.a(std-4208b5b050761eab.std.d3105bbe-cgu.0.rcgu.o): in function `std::sys_common::net::UdpSocket::socket_addr::{{closure}}':
/rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\sys_common/net.rs:530: undefined reference to `getsockname'
C:/Strawberry/c/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/xxx/Desktop/code/rust-cgo/build/windows/libtest.a(std-4208b5b050761eab.std.d3105bbe-cgu.0.rcgu.o): in function `std::sys::windows::net::last_error':
/rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\sys\windows/net.rs:63: undefined reference to `WSAGetLastError'
collect2.exe: error: ld returned 1 exit status

**Comment by Urgau** [comment]
You should use [`rustc --print=native-static-libs`](https://doc.rust-lang.org/rustc/command-line-arguments.html#--print-print-compiler-information) to get the list of all linker arguments to use when linking with a Rust static library.

**Comment by diwuwudi123** [comment]
> You should use [`rustc --print=native-static-libs`](https://doc.rust-lang.org/rustc/command-line-arguments.html#--print-print-compiler-information) to get the list of all linker arguments to use when linking with a Rust static library.

oh  thank you so much, I didn't realize that Linux has no dependencies, but Windows does have so many.
I added the -lws2_32 -lbcrypt -luserenv dependencies to the LDFLAGS and it worked.
