### ISSUE TITLE
Don't show the same help multiple times for object safety violations

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#117186]
#116401 made it so that we report all object safety violations at the same time. However, it also results in a redundant note:

https://github.com/rust-lang/rust/pull/116401/files#diff-ea89a7ba6273e575f66679f7c4a10297572773dc805cc27eb6398f7c12527ab8R16

We should not add the same note multiple times.

**Comment by matthiaskrgr** [comment]
Can we add a debug assertion for duplicate identical help messages? (sorta like we do for "Span must not be empty and have no suggestion" or "Suggestion may not have overlapping parts" ?

**Comment by WaffleLapkin** [comment]
@matthiaskrgr I guess we could, but I think there are _multiple_ diagnostics that currently do this, so we'll have to fix them first.

**Comment by matthiaskrgr** [comment]
Did not find tooo much...
inside `tests`: 
```
for i in `git ls-files | grep \.stderr` ; do ; cat $i | uniq -cd ; done
```
