### ISSUE TITLE
for loop do nothing

### ISSUE THREAD

**Issue by zdu-strong** [rust-lang/rust#117273]
I tried this code:

![image](https://github.com/rust-lang/rust/assets/48673442/15cbd456-3cab-457b-bb79-56e89de9456b)

I expected to see this happen: throw exception or print number

Instead, this happened: do nothing

### Meta

`rustc --version --verbose`:

![image](https://github.com/rust-lang/rust/assets/48673442/16535f44-0a92-48f7-a0d1-ab861f632b1d)

**Comment by mohe2015** [comment]
Did you potentially forget to save your file?

**Comment by zdu-strong** [comment]
> Did you potentially forget to save your file?

I confirm I saved.

**Comment by mohe2015** [comment]
> > Did you potentially forget to save your file?
> 
> I confirm I saved.

There's a White dot right beneath the filename at the top which means unsaved changes. Is to gone and you reran afterwards?

**Comment by zdu-strong** [comment]
My Repository: https://github.com/zdu-strong/Rust-Project-Test

**Comment by zdu-strong** [comment]
> > > Did you potentially forget to save your file?
> > 
> > 
> > I confirm I saved.
> 
> There's a White dot right beneath the filename at the top which means unsaved changes. Is to gone and you reran afterwards?

I really saved it

**Comment by mohe2015** [comment]
I can't check right now but please run in debug mode. I think you produce an integer overflow and I think in release mode the behavior is unspecified then. And in this case it skips the loop

**Comment by mohe2015** [comment]
Alternatively there is a flag for cargo toml to enable overflow checks in release mode.

**Comment by lengyijun** [comment]
Because async is lazy
BTW, please ask in zulip or https://users.rust-lang.org/

**Comment by krtab** [comment]
Hi,

Welcome to rust's issue tracker.

The behavior is correct. In release mode, overflowing wraps around. Your 1000 * 1000 * 1000 * 1000 is equal to -727379968  because the default integer is `i32` and the loop is empty.

```rust
#[tokio::main]
async fn main() {
    println!("Hello, world!");
    dbg!("{}",1000 * 1000 * 1000 * 1000 );

    for i in 1_u64..1000 * 1000 * 1000 * 1000 {
        println!("{}", i)
    }
}
```

does what you want.

In the future, please bring these questions to https://users.rust-lang.org/ or Discord, thanks.

**Comment by zdu-strong** [comment]
> Alternatively there is a flag for cargo toml to enable overflow checks in release mode.

Good news, adding “overflow-checks = true” in Cargo.toml solved my problem.
Thanks.
