### ISSUE TITLE
rustdoc sidebar links are broken

### ISSUE THREAD

**Issue by epage** [rust-lang/rust#117290]
Browse [`toml_edit::visit` for v0.20.6](https://docs.rs/toml_edit/0.20.6/toml_edit/visit/index.html)

I expected to see this happen: Click on module links in side bar, they work

Instead, this happened: Click on module links in side bar and they don't work

### Meta

`rustc --version --verbose`:
```
rustc 1.75.0-nightly (aa1a71e9e 2023-10-26)
```

See https://docs.rs/crate/toml_edit/0.20.6/builds/951451

**Comment by BatmanAoD** [comment]
I notice that the URLs seem to be concatenating the chosen ToC item with whatever item the user is currently looking at.
