### ISSUE TITLE
[rustc] Compiler failed to compile code

### ISSUE THREAD

**Issue by howard0su** [rust-lang/rust#117230]
I tried this code:

```rust
#[derive(Debug)]
enum EnumA {
    type_a,
    type_b(i32),
}

fn func(i: i32) {
    let s = match i {
        1 => Some(func1),
        2 => Some(func2),
        _ => None
    };
    println!("{:?}", s.unwrap()(i));
}

fn func1(i: i32) -> EnumA {
    EnumA::type_a
}

fn func2(i: i32) -> EnumA {
    EnumA::type_b(i)
}
```

I expected to see this code can compile.
Instead, this happened: 
error[E0308]: `match` arms have incompatible types
```
             "b" => Some(func2),
                   ^^^^^^^^^^^ expected `Option<fn(i32) -> EnumA {func1}>`, found `Option<fn(i32) -> EnumA {func2}>`
```
If I add explicit type def for s, the code can compile.

### Meta

`rustc --version --verbose`:
```
rustc 1.73.0 (cc66ad468 2023-10-03)
binary: rustc
commit-hash: cc66ad468955717ab92600c770da8c1601a4ff33
commit-date: 2023-10-03
host: x86_64-pc-windows-msvc
release: 1.73.0
LLVM version: 17.0.2
```

</p>
</details>

**Comment by Jules-Bertholet** [comment]
This is expected; `func1` and `func2` have distinct [function item types](https://doc.rust-lang.org/reference/types/function-item.html). As the linked reference document explains, you need to coerce them to function pointers.

@rustbot label -C-bug

**Comment by howard0su** [comment]
@Jules-Bertholet thank you for your explanation.
