### ISSUE TITLE
Tracking Issue for ARM CRC32 intrinsics

### ISSUE THREAD

**Issue by Amanieu** [rust-lang/rust#117215]
Feature gate: `#![feature(stdarch_arm_crc32)]`

This is a tracking issue CRC32 intrinsics on ARM and AArch64.

### Public API

```rust
// core::arch::{arm,aarch64}

pub unsafe fn __crc32b(crc: u32, data: u8) -> u32;
pub unsafe fn __crc32cb(crc: u32, data: u8) -> u32;
pub unsafe fn __crc32h(crc: u32, data: u16) -> u32;
pub unsafe fn __crc32ch(crc: u32, data: u16) -> u32;
pub unsafe fn __crc32w(crc: u32, data: u32) -> u32;
pub unsafe fn __crc32cw(crc: u32, data: u32) -> u32;

// core::arch::aarch64

pub unsafe fn __crc32d(crc: u32, data: u64) -> u32;
pub unsafe fn __crc32cd(crc: u32, data: u64) -> u32;
```

### Steps / History

- [ ] Implementation: #...
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by Amanieu** [comment]
These intrinsics are documented as part of the ARM C language extensions.

@rfcbot fcp merge

**Comment by tgross35** [comment]
I was thinking this could be closed since most of these are now stable, but `__crc32d` `__crc32cd` don't show up in `core::arch::aarch64` for some reason.

**Comment by Amanieu** [comment]
Yes, the 32-bit intrinsics are tracked separately in #125085.

The docs issue is fixed by https://github.com/rust-lang/stdarch/pull/1653.
