### ISSUE TITLE
failed while formatting fluent string `codegen_ssa_apple_sdk_error_sdk_path`

### ISSUE THREAD

**Issue by wenxiongluo** [rust-lang/rust#117201]
### Code

```Rust
<code>
```
cargo build --target  aarch64-apple-ios --release

### Meta

`rustc --version --verbose`:
```
<version>
```
rustc 1.68.2 (9eb3afe9e 2023-03-27)
binary: rustc
commit-hash: 9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0
commit-date: 2023-03-27
host: x86_64-apple-darwin
release: 1.68.2
LLVM version: 15.0.6

### Error output

```
<output>
```
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: failed while formatting fluent string `codegen_ssa_apple_sdk_error_sdk_path`: 
argument `error` exists but was not referenced correctly
help: try using `{$error}` instead
', compiler/rustc_errors/src/emitter.rs:1391:84

```
<backtrace>
```
stack backtrace:
   0:        0x10d1016e6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h47bed05ceb7970ee
   1:        0x10d15efca - core::fmt::write::hefd823d99333384a
   2:        0x10d0f3eac - std::io::Write::write_fmt::hb978956bb1b85e2b
   3:        0x10d1014ca - std::sys_common::backtrace::print::hc9e298c4664da113
   4:        0x10d1048c3 - std::panicking::default_hook::{{closure}}::hb97411d6e916e1d2
   5:        0x10d104618 - std::panicking::default_hook::hc3ac81176817192f
   6:        0x116d21d8a - rustc_driver[38920cb2344860e2]::DEFAULT_HOOK::{closure#0}::{closure#0}
   7:        0x10d1050b9 - std::panicking::rust_panic_with_hook::hc11209fa2686218a
   8:        0x10d104e54 - std::panicking::begin_panic_handler::{{closure}}::h5bad1bd665ab68a6
   9:        0x10d101b88 - std::sys_common::backtrace::__rust_end_short_backtrace::h6f4efa73918edf57
  10:        0x10d104b1d - _rust_begin_unwind
  11:        0x10d18b5e3 - core::panicking::panic_fmt::hb5474ac70e328787
  12:        0x10d18ba75 - core::result::unwrap_failed::h0d8a1201e19fe76f
  13:        0x116d7dd35 - <rustc_errors[112d18aeec5719f8]::emitter::EmitterWriter>::emit_message_default::{closure#0}
  14:        0x116d7e60f - <rustc_errors[112d18aeec5719f8]::emitter::EmitterWriter>::emit_messages_default
  15:        0x116d731ff - <rustc_errors[112d18aeec5719f8]::emitter::EmitterWriter as rustc_errors[112d18aeec5719f8]::emitter::Emitter>::emit_diagnostic
  16:        0x116d5c68e - <rustc_errors[112d18aeec5719f8]::json::Diagnostic>::from_errors_diagnostic
  17:        0x116d5aff2 - <rustc_errors[112d18aeec5719f8]::json::JsonEmitter as rustc_errors[112d18aeec5719f8]::emitter::Emitter>::emit_diagnostic
  18:        0x116d52128 - <rustc_errors[112d18aeec5719f8]::HandlerInner>::emit_diagnostic::{closure#2}
  19:        0x116d5193a - <rustc_errors[112d18aeec5719f8]::HandlerInner>::emit_diagnostic
  20:        0x116d4d7f9 - <rustc_errors[112d18aeec5719f8]::ErrorGuaranteed as rustc_errors[112d18aeec5719f8]::diagnostic_builder::EmissionGuarantee>::diagnostic_builder_emit_producing_guarantee
  21:        0x116aad899 - <rustc_session[d7fa5f284918d396]::parse::ParseSess>::emit_err::<rustc_codegen_ssa[d3f4f59abe434366]::errors::AppleSdkRootError>
  22:        0x116a7d03c - rustc_codegen_ssa[d3f4f59abe434366]::back::link::linker_with_args
  23:        0x116a6f30e - rustc_codegen_ssa[d3f4f59abe434366]::back::link::link_natively
  24:        0x116a6bd29 - rustc_codegen_ssa[d3f4f59abe434366]::back::link::link_binary
  25:        0x116a1db06 - <rustc_codegen_llvm[38beeae3b58912bb]::LlvmCodegenBackend as rustc_codegen_ssa[d3f4f59abe434366]::traits::backend::CodegenBackend>::link
  26:        0x1174ae7e1 - <rustc_interface[d2d1d1fbee7644ce]::queries::Linker>::link
  27:        0x116d0fbe3 - rustc_span[abe350e59e28df37]::with_source_map::<core[fd5e363bb4760a86]::result::Result<(), rustc_errors[112d18aeec5719f8]::ErrorGuaranteed>, rustc_interface[d2d1d1fbee7644ce]::interface::run_compiler<core[fd5e363bb4760a86]::result::Result<(), rustc_errors[112d18aeec5719f8]::ErrorGuaranteed>, rustc_driver[38920cb2344860e2]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  28:        0x116cba3e5 - std[963c226d0575182f]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[d2d1d1fbee7644ce]::util::run_in_thread_pool_with_globals<rustc_interface[d2d1d1fbee7644ce]::interface::run_compiler<core[fd5e363bb4760a86]::result::Result<(), rustc_errors[112d18aeec5719f8]::ErrorGuaranteed>, rustc_driver[38920cb2344860e2]::run_compiler::{closure#1}>::{closure#0}, core[fd5e363bb4760a86]::result::Result<(), rustc_errors[112d18aeec5719f8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[fd5e363bb4760a86]::result::Result<(), rustc_errors[112d18aeec5719f8]::ErrorGuaranteed>>
  29:        0x116c99385 - <<std[963c226d0575182f]::thread::Builder>::spawn_unchecked_<rustc_interface[d2d1d1fbee7644ce]::util::run_in_thread_pool_with_globals<rustc_interface[d2d1d1fbee7644ce]::interface::run_compiler<core[fd5e363bb4760a86]::result::Result<(), rustc_errors[112d18aeec5719f8]::ErrorGuaranteed>, rustc_driver[38920cb2344860e2]::run_compiler::{closure#1}>::{closure#0}, core[fd5e363bb4760a86]::result::Result<(), rustc_errors[112d18aeec5719f8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[fd5e363bb4760a86]::result::Result<(), rustc_errors[112d18aeec5719f8]::ErrorGuaranteed>>::{closure#1} as core[fd5e363bb4760a86]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  30:        0x10d10e5a7 - std::sys::unix::thread::Thread::new::thread_start::had0599fead9033cd
  31:     0x7ff81a4441d3 - __pthread_start

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.2 (9eb3afe9e 2023-03-27) running on x86_64-apple-darwin

note: compiler flags: --crate-type cdylib -C opt-level=3 -C embed-bitcode=no

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack

</p>
</details>

**Comment by Nilstrieb** [comment]
Fixing this doesn't require reproducing it. Search for the mentioned message and also check https://rustc-dev-guide.rust-lang.org/diagnostics/translation.html.

**Comment by Rajveer100** [comment]
@Nilstrieb 
Could you briefly describe the issue, I have found the call-site.

**Comment by Rajveer100** [comment]
Quite interestingly, the `{$error}` is in place, with no typos, although I noticed that the fields are in an `enum` just for this particular diagnosis (i.e, `codegen_ssa_apple_sdk_error_sdk_path),` rest all are structs, for other kinds of `error` messages. Could that be the cause?

**Comment by Nilstrieb** [comment]
Ohhhh, I just realized, this issue is for an old version of the compiler, and on the mentioned commit, the message was like this:

> `codegen_ssa_apple_sdk_error_sdk_path = failed to get {$sdk_name} SDK path: {error}`

which is of course wrong. But it has been fixed already. Sorry for misleading you^^, I hope you can find something else to work on.

Closing this issue as it's already fixed, thank you for the report anyways @wenxiongluo! Next time, try reproducting problems on the latest nightly or at least stable version before opening an issue if possible.
