### ISSUE TITLE
[UR] local storage inside function

### ISSUE THREAD

**Issue by nicolasboulay** [rust-lang/rust#11726]
It could be great to have local storage that are unique by function call site (like Lustre does).

This reduce the need for dynamique memory and it's much easier than doing it by hand. This is also great for real time application, or application that refuse dynamic memory (for security, safety or speed reason).

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#795
