### ISSUE TITLE
Trait implementations order random

### ISSUE THREAD

**Issue by bend-n** [rust-lang/rust#117391]
### Location

[`foreign-impls`](https://docs.rs/fimg/0.4.21/fimg/pixels/blending/trait.Blend.html#foreign-impls)

### Summary

Displeasing order, 
![image](https://github.com/rust-lang/rust/assets/70787919/ca9a36e2-abe1-458e-a128-dfe07c5993a1)
Expect sorted, or source order.

@GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
I'll take a look in the next days.
