### ISSUE TITLE
cranelift component broken?

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#117366]
`rustc 1.75.0-nightly (e5cfc5547 2023-10-28)`

According to `rustup  component list`, I have `rustc-codegen-cranelift-x86_64-unknown-linux-gnu (installed)`

But when I try to build something with it:
`RUSTFLAGS="-Zcodegen-backend=cranelift" ~/.cargo/bin/cargo +nightly build`
I get:
```
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/home/matthias/.cargo/bin/sccache /home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc - --crate-name ___ --print=file-names -Zcodegen-backend=cranelift --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 1)
  --- stderr
  error: failed to find a `codegen-backends` folder in the sysroot candidates:
         * /home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu
         * /home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu
```

inside `~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu`, there is indeed no such folder

```
~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu
at 21:49:08 ❯ ls
bin  etc  lib  libexec  share
```

looks like the component is slightly borked? cc @bjorn3

**Comment by bjorn3** [comment]
https://github.com/rust-lang/rust/pull/117328 will fix this. Basically there were two issues:

* The `CODEGEN_BACKENDS` env var wasn't passed into the docker container, so cg_clif didn't actually get built.
* The `dist::CodegenBackend` step didn't check if the codegen backend was enabled and would produce an empty component if not.

This PR fixed both issues. It should land tomorrow, so the nightly after that should be fine.

**Comment by matthiaskrgr** [comment]
its working!! :tada: :rocket: :rocket:
