### ISSUE TITLE
Suggest updating the compiler

### ISSUE THREAD

**Issue by CryZe** [rust-lang/rust#117318]
### Code

On an older compiler:
```Rust
fn main() {
  1u32.div_ceil(5);
}
```

### Current output

```Shell
error[E0658]: use of unstable library feature 'int_roundings'
  --> src\lib.rs:38:14
   |
38 |         1u32.div_ceil(5);
   |              ^^^^^^^^
   |
   = note: see issue #88581 <https://github.com/rust-lang/rust/issues/88581> for more information
```

### Desired output

```Shell
error[E0658]: use of unstable library feature 'int_roundings'
  --> src\lib.rs:38:14
   |
38 |         1u32.div_ceil(5);
   |              ^^^^^^^^
   |
   = note: see issue #88581 <https://github.com/rust-lang/rust/issues/88581> for more information
   = note: if you are on an old compiler version you may need to update your compiler
```

### Rationale and extra context

Throughout all my time with Rust I've heard from multiple people (who may be less experienced) on various occasions that after pulling the latest commit, that my Rust code is accidentally using unstable features. Every single time they didn't know that the problem isn't that I used unstable features, but that those features stabilized in the meantime and that they need to update their compiler version.

Maybe the compiler could even check based on the date if a new version of the compiler should be out and only emit that note then.

**Comment by matthiaskrgr** [comment]
Wouldn't that require that `1.73.0` knows that a feature has actually been stabilized in `1.75.0` for example?

**Comment by Nilstrieb** [comment]
That's why the message should be a suggestion with "if you're on an older compiler". We cannot know what's stable in the future, but making the suggestion doesn't hurt and seems like a good idea.

**Comment by ketsuban** [comment]
It might be worth checking the system time and only printing this message if the current version was built more than (say) six weeks ago. That's enough time for one release train to arrive.

**Comment by George-lewis** [comment]
Hi all, this issue seems to have stalled? I hope no one minds if I make an attempt. I'll claim this and open a PR shortly

**Comment by Ekleog** [comment]
Considering #119088 landed, I think this could be closed? :)

**Comment by workingjubilee** [comment]
Agreed.
