### ISSUE TITLE
How to set custom linker with `build.rs`

### ISSUE THREAD

**Issue by southorange0929** [rust-lang/rust#117384]
I try to build a cdylib with rust for openharmony. And i followed this doc: https://doc.rust-lang.org/rustc/platform-support/openharmony.html.

There are three ways to set custom linker.

1. `set linker with config.toml`    
    it works.
2. set linker with env like `export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_OHOS_LINKER=path/scripts/aarch64-unknown-linux-ohos-clang.sh`    
    it works.
3. set linker with `build.rs`    
```rs
  let custom_linker = format!(
    "{}={}/scripts/aarch64-unknown-linux-ohos-clang.sh",
    "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_OHOS_LINKER",
    current_dir.display()
  );
  println!("cargo:rustc-env={}", custom_linker);
```

And try to build with command: `cargo +nightly build --target aarch64-unknown-linux-ohos -Z build-std`

Solution 1 & 2 will find right library,but solution 3 is wrong.

Error is wrong `-L` options:
<img width="1464" alt="image" src="https://github.com/rust-lang/rust/assets/32590310/dc2ac626-5a5d-443d-918f-ed059c5c3001">

Success with `-L` options:
<img width="1367" alt="image" src="https://github.com/rust-lang/rust/assets/32590310/bd1f3e91-ff93-437b-8703-2b457f9622f4">

Any suggestions? Thanks.

**Comment by Nilstrieb** [comment]
rustc-env passes the env to rustc, not cargo. cargo processes that var. You need to pass a rust-arg, -Clinker=LINKER

**Comment by bjorn3** [comment]
I would suggest putting the linker config in `.cargo/config.toml` instead of `build.rs`.

**Comment by southorange0929** [comment]
Thanks a lot,but it's so bad that `rustc-flags` not support -C
