### ISSUE TITLE
Feature: Adding contributors section to the README.md file.

### ISSUE THREAD

**Issue by Kalyanimhala** [rust-lang/rust#117326]
### Location

Readme.md file 
![contributors](https://github.com/rust-lang/rust/assets/147402107/4c48e546-21f0-4a64-a3f9-a5b139bd9fce)

### Summary

There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.

**Comment by Kalyanimhala** [comment]
@barosl  Kindly assign me this issue, I want to work on it. Thank You!!

**Comment by Nilstrieb** [comment]
We have https://thanks.rust-lang.org/ already.

**Comment by fmease** [comment]
Closing as not planned for the same reason as #116544.
