### ISSUE TITLE
TAIT: empty match on TAIT confuses typeck

### ISSUE THREAD

**Issue by Nadrieril** [rust-lang/rust#117413]
I tried this code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=2ac211ebe1388c4816239cdbbef750a9)):

```rust
#![feature(type_alias_impl_trait)]
#![allow(unconditional_recursion)]

#[derive(Copy, Clone)]
enum Void {}

mod match_wildcard {
    type X = impl Copy; // ok
    fn empty_opaque(x: super::Void) -> X {
        match empty_opaque(x) {
            _ => {}
        }
        x
    }
}

mod empty_match {
    type X = impl Copy;
    //~^ ERROR unconstrained opaque type
    fn empty_opaque(x: super::Void) -> X {
        match empty_opaque(x) {}
        x
    }
}
```

Somehow in the second case we think that `X` is unconstrained even though it doesn't seem to contain more or less type information than the first case. Note also that this does not error if I use RPIT instead.

**Comment by oli-obk** [comment]
I think in the second example mir building doesn't generate code for the trailing expression because it's statically known as dead code. But I thought we were keeping around the typeck types nowadays, and typeck should be the same for both functions

**Comment by Nadrieril** [comment]
I don't think that's it, same error if I put the match in a branch ([updated playground link with more variations](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=e7a33de41ce53ab9dc4081f904cec0b0)):
```rust
type X = impl Copy;
//~^ ERROR unconstrained opaque type
fn empty_opaque(x: super::Void) -> X {
    if false {
        match empty_opaque(x) {}
        //~^ ERROR non-empty
    }
    x
}
```

**Comment by Nadrieril** [comment]
In fact this doesn't need an empty type at all:
```rust
type X = impl Copy;
//~^ ERROR unconstrained opaque type
fn empty_opaque() -> X {
    if false {
        match empty_opaque() {}
        //~^ ERROR non-empty
    }
    0u8
}
```

**Comment by compiler-errors** [comment]
I think we're generating bogus MIR or THIR because of that empty match --

```
fn empty_opaque() -> {type error} {
    let mut _0: {type error};

    bb0: {
        unreachable;
    }
}
```

Are you sure the bug doesn't exist on the THIR/MIR building side, @Nadrieril?

**Comment by Nadrieril** [comment]
Oh I'm sure of nothing 😄 I just assumed an unreachable in a `if false` branch would not affect anything else

**Comment by compiler-errors** [comment]
So:

https://github.com/rust-lang/rust/blob/e6e931dda5fffbae0fd87c5b1af753cc95556880/compiler/rustc_mir_build/src/build/mod.rs#L58-L60

If there's a match error, we end up constructing a failure MIR body. This will prevent us from inferring the opaque later on. This is because nothing in HIR actually constrains the TAIT either.

Let me see if I can cook up a quick fix.
