### ISSUE TITLE
Creating poor man's compile-time option

### ISSUE THREAD

**Issue by JohnScience** [rust-lang/rust#117477]
I'm trying to create a `CTOption` type, which is meant to be a compile time-option.

```rust
#[repr(transparent)]
pub struct CTOption<T, const IS_SOME_VAL: bool>(MaybeUninit<T>);
```

Naturally, it has to be able to run the destructor of the inner value at compile time.

How can I make it happen?

I already [implemented](https://github.com/JohnScience/ctoption/blob/master/src/lib.rs) most important methods on `CTOption` but presence of `Drop` implementation in such cases

```rust
const fn do_one_thing() {}
const fn do_another_thing() {}

const fn extra_cleanup<T, const IS_SOME_VAL: bool>(opt: CTOption<T, IS_SOME_VAL>)
{
    match IS_SOME_VAL {
        true => do_one_thing(),
        false => do_another_thing(),
    }
}
```

 doesn't let the type to be used as a parameter for a function because of the following error:

```
[`error[E0493]: destructor of CTOption<T, IS_SOME_VAL> cannot be evaluated at compile-time`][E0493]. This
happens because [`CTOption`] has a custom implementation of [`Drop`] trait and custom implementations
cannot be evaluated at compile-time.
```

[Link to the error](https://doc.rust-lang.org/error_codes/E0493.html).

I want my `CTOption` to be `~const Drop` with approximately such implementation, which already compiles but prevents the values of this type to be used as arguments for const functions.

```rust
// adding const before Drop does nothing
impl<T, const IS_SOME_VAL: bool> Drop for CTOption<T, IS_SOME_VAL> {
    fn drop(&mut self) {
        if IS_SOME_VAL {
            unsafe { self.0.assume_init_drop() }
        }
    }
}
```

I learned that there's `std::market::Destruct`, but it isn't exactly what I need.

I can make the situation simpler with `#![feature(const_precise_live_drops)]` by reducing `CTOption<T, iS_SOME_VAL>` to either `T` or `()` but I still will get

```
destructor of `T` cannot be evaluated at compile-time
the destructor for this type cannot be evaluated in constant functions
```

for the value of type `T: ~const std::marker::Destruct`. I can make it sort of work with `std::mem::forget` but such solutions sounds wrong and impractical in the code of the library users.

**Comment by ChrisDenton** [comment]
Hi, the issue tracker is not a good place for help questions. You might like to try the [Users forum](https://users.rust-lang.org/) or the [Official Discord](https://discord.gg/rust-lang/)

**Comment by JohnScience** [comment]
> Hi, the issue tracker is not a good place for help questions. You might like to try the [Users forum](https://users.rust-lang.org/) or the [Official Discord](https://discord.gg/rust-lang/)

I thought it was fine enough because this particular case is about pushing the limits of compile time evaluation and is stopped by language features.

**Comment by ChrisDenton** [comment]
Yes, discussion around language features is better suited to other forums (the [Internals forum](https://internals.rust-lang.org/) or [Zulip](https://rust-lang.zulipchat.com/) may also be of interest if you want to help guide language development).
