### ISSUE TITLE
`doc.rust-lang.org/nightly/nightly-rustc` links are broken

### ISSUE THREAD

**Issue by smoelius** [rust-lang/rust#117452]
Links with the above prefix are not resolving. Is this a temporary problem, or have `nightly` docs been deprecated?

I ask because, for all of the urls I have tried, the corresponding `std` and `beta` versions resolve.

Example url causing a problem: https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/mir/enum.MirPhase.html

Taken from here: https://github.com/rust-lang/rust/blob/22b27120b990aa9ca851819ce95149385da7954d/library/core/src/intrinsics/mir.rs#L48

**Comment by ChrisDenton** [comment]
#117430
