### ISSUE TITLE
Rustdoc Json Test Suite: Avoid using `#![no_core]`

### ISSUE THREAD

**Issue by aDotInTheVoid** [rust-lang/rust#117487]
Many tests in `tests/rustdoc-json` use `#![feature(no_core)]` `#![no_core]`. This significantly reduces the size of the generates JSON, and makes the tests easier to write.

However it also means the tests now rely on the unstable (and undocumented) contract between `core` and `rustc`. This means that unreleated rustc changes can cause these tests to fail, as they usually only contain the subset of lang-items needed to make the tests pass.

We don't want rustdoc-json tests to create unnessessary work for people working on rustc, who may not be framiliar with how the tests work, and deffinatly don't want to be interupted by our flakey tests.

Eg: https://github.com/rust-lang/rust/pull/117213/files#diff-9e25fc2f875153412739ef3cdf1267fc82c6f2743f0d7ee8dba65671d24cb3caR4-R7

Therefor, we should remove usages of `#![no_core]` in `tests/rustdoc-json`. Some of them will be unavoidable if we're trying to test `core` specific behaviour (eg inherent impls on primitives), but we should limit `#![no_core]` to cases where it's strictly nessessary.

**Comment by GuillaumeGomez** [comment]
We could at least keep `#![no_std]` though. Still not as `no_core` but better than not having it.
