### ISSUE TITLE
Auto traits are not implemented for extern types

### ISSUE THREAD

**Issue by eggyal** [rust-lang/rust#117573]
I tried this code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=255de2403a8fe06399e5ae5c1beb9340)):

```rust
#![feature(auto_traits, extern_types)]

auto trait Valid {}

extern {
    type ExternType;
}

fn must_be_valid(_: &(impl ?Sized + Valid)) {}

fn extern_type_is_valid(extern_type: &ExternType) {
    must_be_valid( extern_type );
}
```

I expected the auto trait to be implemented for the extern type and the code to compile.  Instead, it appears that the auto trait is not implemented:

<pre>
error<a href="https://doc.rust-lang.org/nightly/error_codes/E0277.html">[E0277]</a>: the trait bound `ExternType: Valid` is not satisfied
  --> src/lib.rs:12:20
   |
12 |     must_be_valid( extern_type );
   |     -------------  ^^^^^^^^^^^ the trait `Valid` is not implemented for `ExternType`
   |     |
   |     required by a bound introduced by this call
   |
note: required by a bound in `must_be_valid`
  --> src/lib.rs:9:37
   |
9  | fn must_be_valid(_: &(impl ?Sized + Valid)) {}
   |                                     ^^^^^ required by this bound in `must_be_valid`

For more information about this error, try `rustc --explain E0277`.
</pre>

**Comment by compiler-errors** [comment]
I consider this expected behavior.

Why would an auto trait be implemented here? Auto traits are only implemented when we can structurally decompose that type and test if that auto trait is implemented for those components -- that's why `dyn Trait` doesn't automatically implement auto traits.

**Comment by eggyal** [comment]
Hm, `PhantomData` implements auto traits even though there's nothing to structurally decompose?  Perhaps it's expected behaviour for `extern` types, but it surprised me and I couldn't find the expected behaviour specified one way or the other.  Maybe something for T-lang to consider?

**Comment by compiler-errors** [comment]
See https://github.com/rust-lang/rust/issues/43467#issuecomment-1207257995
