### ISSUE TITLE
Tutorial docs improvement metabug

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#11755]
Our tutorial(s) have problems.

This is a metabug to collect those issues together.

(A metabug seems especially appropriate when it comes to the manual and the tutorials, since someone fixing one problem in a document may be in a good position to fix other related problems, so cross-referencing here seems good.)

Do try to restrict the scope of this metabug to either pure documentation issues or to file organization / naming issues.  (I.e. tooling for automatic testing or doc extraction is not part of the scope of this metabug.)

**Comment by tshepang** [comment]
@steveklabnik no one objects :)
