### ISSUE TITLE
SpiderMonkey trace hook generation

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#11757]
Servo needs to be able to automatically generate trace hooks for SpiderMonkey. I don't know any details.

@pnkfelix @pcwalton 

This doesn't matter for 1.0 for us but they need it soon. Nominating.

**Comment by FlaPer87** [comment]
Triage bump: I dunno the details here so, @jdm friendly ping: Do you have any info about this bug? Is it still relevant?

**Comment by jdm** [comment]
I don't think leaving this open is particularly useful. We'll file issues about specific problems or ways that Rust could improve the experience when we come across them.

**Comment by FlaPer87** [comment]
@jdm thanks :)
