### ISSUE TITLE
Recent nightly causes `[E0308]: mismatched types`

### ISSUE THREAD

**Issue by nyurik** [rust-lang/rust#117598]
This code is a subset of the sqlx crate code that is no longer compiling on the nightly (nightly change was very recent, it was working fine a few versions ago). Matching bug in sqlx crate - https://github.com/launchbadge/sqlx/issues/2855

```rust
trait Database: for<'r> HasValueRef<'r, Database = Self> {}

trait HasValueRef<'r> {
    type Database: Database;
}

struct Any;

impl Database for Any {}

impl<'r> HasValueRef<'r> for Any {
    type Database = Any;
}
```

I expected to see this happen: *code compiles*

Instead, this happened: *code fails to compile using +nightly*

### Meta

Version that compiles fine: `rustc --version`:

```
rustc 1.73.0
```

Version that fails to compile: `rustc +nightly --version --verbose`

```
rustc 1.75.0-nightly (4b85902b4 2023-11-04)
binary: rustc
commit-hash: 4b85902b438f791c5bfcb6b1c5b476d5b88e2bef
commit-date: 2023-11-04
host: x86_64-unknown-linux-gnu
release: 1.75.0-nightly
LLVM version: 17.0.4
```

<details><summary>`cargo +nightly build` results</summary>
<p>

```
✦ ❯ cargo +nightly build
   Compiling mydemo v0.1.0 (...)
error[E0308]: mismatched types
  --> src/bin/main.rs:12:21
   |
12 |     type Database = Any;
   |                     ^^^ lifetime mismatch
   |
   = note: expected associated type `<Any as HasValueRef<'r>>::Database`
              found associated type `<Any as HasValueRef<'r>>::Database`
note: the required lifetime does not necessarily outlive the lifetime `'r` as defined here
  --> src/bin/main.rs:11:6
   |
11 | impl<'r> HasValueRef<'r> for Any {
   |      ^^
note: the lifetime requirement is introduced here
  --> src/bin/main.rs:4:20
   |
4  |     type Database: Database;
   |                    ^^^^^^^^

error[E0308]: mismatched types
  --> src/bin/main.rs:12:21
   |
12 |     type Database = Any;
   |                     ^^^ lifetime mismatch
   |
   = note: expected associated type `<Any as HasValueRef<'r>>::Database`
              found associated type `<Any as HasValueRef<'r>>::Database`
note: the lifetime `'r` as defined here doesn't meet the lifetime requirements
  --> src/bin/main.rs:11:6
   |
11 | impl<'r> HasValueRef<'r> for Any {
   |      ^^
note: the lifetime requirement is introduced here
  --> src/bin/main.rs:4:20
   |
4  |     type Database: Database;
   |                    ^^^^^^^^
```

</p>
</details>

**Comment by HTGAzureX1212** [comment]
I ran a rustc bisection and came to the following conclusion:

searched nightlies: from nightly-2023-11-03 to nightly-2023-11-05
regressed nightly: nightly-2023-11-04
searched commit range: https://github.com/rust-lang/rust/compare/a2f5f9691b6ce64c1703feaf9363710dfd7a56cf...1bb6553b967b69eed9ed8147e78b4f65cfc48e11
regressed commit: https://github.com/rust-lang/rust/commit/2520ca8566e596b10b0a163d31d9ce216876fafc

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.7</summary>


Host triple: x86_64-pc-windows-msvc
Reproduce with:
```bash
cargo bisect-rustc --end=2023-11-05
```
</details>

**Comment by HTGAzureX1212** [comment]
The commit corresponds to this PR: https://github.com/rust-lang/rust/pull/117131
cc @compiler-errors

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23117598.20Recent.20nightly.20causes.20.60.5BE0308.5D.3A.20mismatched.20types.60)).

@rustbot label -I-prioritize +P-critical
