### ISSUE TITLE
Use our new syntax extension loading machinery to remove the hardcoded macros in libsyntax

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#11763]
```
< bstrie_remorse> now that we have loadable syntax extensions, are we actually
                  using them for e.g. println! or are we still hardcoding those
                  into libsyntax?
<@acrichto> not yet
<@acrichto> not yet using them
<@acrichto> I don't think there's a blocker for using them though
```
We've got a lot of syntax extensions hardcoded into src/libsyntax/ext. That shouldn't be necessary anymore. Fix this terrible hack!

**Comment by steveklabnik** [comment]
While this situation isn't perfect, @sfackler has moved the macros out of libsyntax and into libstd.

**Comment by steveklabnik** [comment]
Triage: I am not aware of any more changes on this front.

**Comment by bstrie** [comment]
I'm content to close this now, what's left is just cleanup work.
