### ISSUE TITLE
Tracking Issue for `duration_abs_diff`

### ISSUE THREAD

**Issue by elomatreb** [rust-lang/rust#117618]
Feature gate: `#![feature(duration_abs_diff)]`

This is a tracking issue for the `Duration::abs_diff` method.

ACP: https://github.com/rust-lang/libs-team/issues/291

I haven't contributed to Rust before so I hope this is the right approach.

### Public API

```rust
impl Duration {
    pub const fn abs_diff(self, other: Duration) -> Duration;
}
```

### Steps / History

- [x] Implementation: #117619
- [x] Final comment period (FCP)[^1]
- [x] Stabilization PR: #127128

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by elomatreb** [comment]
# Stabilization report

## Implementation history

 - Implementation was added in #117619, no changes since.

## API summary

Very simple:
```rs
impl Duration {
    pub fn abs_diff(self, other: Duration) -> Duration;
}
```

## Experience report

I've been using this method in a private project with nightly since it was initially merged. Not immediately aware of any public uses, but since it's fairly niche that doesn't surprise me a lot.

**Comment by BurntSushi** [comment]
@rfcbot fcp merge

**Comment by elomatreb** [comment]
I'll make the PR later today.
