### ISSUE TITLE
New "lifetime bound not satisfied" error on associated type

### ISSUE THREAD

**Issue by laurmaedje** [rust-lang/rust#117664]
### Code

I tried this code:

```rust
pub struct Foo<'a> {
    // We need to override the constraint's lifetime here so that `Tracked` is
    // covariant over the constraint.
    _tracked: Tracked<'a, Self, <Foo<'static> as Validate>::Constraint>,
}

impl<'a> Validate for Foo<'a> {
    type Constraint = Constraint;
}

pub trait Validate {
    type Constraint;
}

pub struct Constraint;

pub struct Tracked<'a, T, C = <T as Validate>::Constraint>
where
    T: Validate + ?Sized,
{
    pub value: &'a T,
    pub constraint: Option<&'a C>,
}
```

I expected to see this happen: Compiles.

Instead, this happened: Fails with:
```
error[E0478]: lifetime bound not satisfied
 --> src/lib.rs:9:5
  |
9 |     type Constraint = Constraint;
  |     ^^^^^^^^^^^^^^^
  |
note: lifetime parameter instantiated with the lifetime `'a` as defined here
 --> src/lib.rs:8:6
  |
8 | impl<'a> Validate for Foo<'a> {
  |      ^^
  = note: but lifetime parameter must outlive the static lifetime

For more information about this error, try `rustc --explain E0478`.
```

The whole setup with the default type parameter that is overridden is required to get `Tracked` to be covariant over the constraint. The code above is a minimal extract from a usage of [`comemo`](https://crates.io/crates/comemo) in [`typst`](http://github.com/typst/typst). Linked issue: https://github.com/typst/typst/issues/2600 

See also this discussion on Zulip for how this setup came to be in the first place: https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/.E2.9C.94.20Variance.20with.20associated.20types

### Version it worked on

It most recently worked on:

```
rustc 1.73.0 (cc66ad468 2023-10-03)
binary: rustc
commit-hash: cc66ad468955717ab92600c770da8c1601a4ff33
commit-date: 2023-10-03
host: aarch64-apple-darwin
release: 1.73.0
LLVM version: 17.0.2
```

### Version with regression

```
rustc 1.75.0-nightly (189d6c71f 2023-11-06)
binary: rustc
commit-hash: 189d6c71f3bb6c52113b5639a80839791974fd22
commit-date: 2023-11-06
host: aarch64-apple-darwin
release: 1.75.0-nightly
LLVM version: 17.0.4
```

**Comment by lqd** [comment]
I believe this is some other fallout from #117131, like #117598, and that it will be fixed by #117542 which should land real soon.

**Comment by Jules-Bertholet** [comment]
@rustbot label -regression-untriaged regression-from-stable-to-nightly

@compiler-errors

**Comment by Finchiedev** [comment]
With #117542 merged, I believe this issue has been resolved? I am no longer able to reproduce the error on the latest nightly (`rustc 1.75.0-nightly (edf0b1db0 2023-11-10)`)

**Comment by apiraino** [comment]
@laurmaedje can you confirm [the above comment](https://github.com/rust-lang/rust/issues/117664#issuecomment-1806878355)? That is, is this issue fixed for you, too? Thanks

**Comment by laurmaedje** [comment]
Yes, it's resolved for me. Thanks!
