### ISSUE TITLE
`-Zthreads` changes compiled binary

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#117635]
````
rustc 1.75.0-nightly (e1fcecb1b 2023-11-06)
binary: rustc
commit-hash: e1fcecb1b9930f109a8c1cf2b690e03483a41289
commit-date: 2023-11-06
host: x86_64-unknown-linux-gnu
release: 1.75.0-nightly
LLVM version: 17.0.4
````
reproducible with both `cargo` and `oxipng`

1) `cargo build --release`
=> `1816	target/release/oxipng` (`du -sk`)
2) `RUSTFLAGS="-Zthreads=1"  cargo build --release`
=> `1692	target/release/oxipng`

seems that Zthreads on/off has an effect on the generated binary :thinking:

**Comment by saethlin** [comment]
I cannot reproduce this with `oxipng`. I get exactly the same binary with or without `-Zthreads=1`.

**Comment by lqd** [comment]
@matthiaskrgr do you have global flags / cargo configs, that would be turned off when manually overriding `RUSTFLAGS` in your second example ?

**Comment by matthiaskrgr** [comment]
OOoh yes,  I totally forgot I had RUSTFLAGS="-march=native" exported via my bash rc. :D

**Comment by matthiaskrgr** [comment]
I was already wondering why I could not reproduce this when calling rustc via a script (where RUSTFLAGS is always overridden...) lol

Sorry for the noise :D

**Comment by lqd** [comment]
[my disappointment is immeasurable and my day is ruined](https://github.com/rust-lang/rust/pull/117246#issuecomment-1781736402) :3
