### ISSUE TITLE
Scratch issue for wg-async checkboxes

### ISSUE THREAD

**Issue by eholk** [rust-lang/rust#117687]
I'm using this issue to see if rfcbot can add checkboxes for wg-async. It's not a real issue and I'll close it soon. Please ignore!

**Comment by eholk** [comment]
@rfcbot fcp merge

**Comment by compiler-errors** [comment]
I'm pretty sure that rfcbot only handles labels that start with T-

**Comment by eholk** [comment]
Yeah, it seems like this didn't work. I'll go ahead and close this.
