### ISSUE TITLE
Incorrect doc links in `src/cmp.rs` lead to invalid hyperlinks in `rust-analyzer`

### ISSUE THREAD

**Issue by ariasanovsky** [rust-lang/rust#117666]
# Incorrect doc links in `src/cmp.rs` lead to invalid hyperlinks in `rust-analyzer`

## Errors in `rust` source code

- [`PartialEq#derivable`](https://github.com/rust-lang/rust/blob/4e0fb98a5c41be1227845219b81ab147708fd99a/library/core/src/cmp.rs#L245) should be `trait.PartialEq#derivable`
- [`Ord#derivable`](https://github.com/rust-lang/rust/blob/4e0fb98a5c41be1227845219b81ab147708fd99a/library/core/src/cmp.rs#L888) should be `trait.Ord#derivable`
- [`PartialOrd`](https://github.com/rust-lang/rust/blob/4e0fb98a5c41be1227845219b81ab147708fd99a/library/core/src/cmp.rs#L1178) should be `trait.PartialOrd#derivable`

## Links to invalid hyperlinks in `https://doc.rust-lang.org/`

- `PartialEq`: https://doc.rust-lang.org/nightly/src/core/cmp.rs.html#245
- `Ord`: https://doc.rust-lang.org/nightly/src/core/cmp.rs.html#888
- `PartialOrd`: https://doc.rust-lang.org/nightly/src/core/cmp.rs.html#1178

## Incorrect links in `rust-analyzer` provides a link to a nonexistent website

![screenshot of `rust-analyzer` providing an invalid link](https://github.com/rust-lang/rust-analyzer/assets/14944402/106c6d73-ff38-4f37-8df2-7c6485fb27e4)

- https://doc.rust-lang.org/nightly/core/cmp/PartialEq#derivable (incorrect)
- https://doc.rust-lang.org/nightly/core/cmp/trait.PartialEq.html#derivable (correct)
  - has `trait` before `.PartialEq`

## Related Issues in `rust-analyzer`
- https://github.com/rust-lang/rust-analyzer/issues/15835

**Comment by ehuss** [comment]
Transferred to rust-lang/rust since this isn't part of the reference. However, looking more closely, this appears to be an issue with rust-analyzer. Can you re-open your issue over at https://github.com/rust-lang/rust-analyzer/issues/?

**Comment by ariasanovsky** [comment]
> Transferred to rust-lang/rust since this isn't part of the reference.

Thanks! I agree.

> However, looking more closely, this appears to be an issue with rust-analyzer. Can you re-open your issue over at https://github.com/rust-lang/rust-analyzer/issues/?

I decided to submit here since the typo occurs in `library/core/src/cmp.rs`. `rust-analyzer` just shows the bad hyperlink generated. If you still think it should move, I'll replicate it there.

**Comment by ehuss** [comment]
Rustdoc does processing on links (called [intra-doc links](https://doc.rust-lang.org/nightly/rustdoc/write-documentation/linking-to-items-by-name.html)), where a link like `PartialEq` will get rewritten to the correct link (like `trait.PartialEq.html`), using Rust name resolution. It looks like rust-analyzer either doesn't do that, or is missing the logic for these particular cases. I'm not familiar with how rust-analyzer is processing the documentation, so I can't say anything about it. The links are correct when processed via rustdoc (like in https://doc.rust-lang.org/std/cmp/derive.PartialEq.html).
