### ISSUE TITLE
Nightly 65e297d1e 2023-11-03 fails to infer auto traits

### ISSUE THREAD

**Issue by adamreichold** [rust-lang/rust#117602]
The type `aho_corasick::AhoCorack` is not inferred to be `Send + Sync` by the above mentioned nightly release, c.f. https://github.com/quickwit-oss/tantivy/actions/runs/6759263517/job/18371750242?pr=2239 Using the stable, the code compiles with out issue.

EDIT: It seems to be related to GAT, i.e. a more minimal reproducer is:

```rust
trait SomethingSomething: Send {}

struct Wrapper<T> {
    something: Box<dyn SomethingSomething>,
    other: T,
}

trait HasSend {
    type IsSend<T: Send>: Send;
}

impl<T> HasSend for Wrapper<T> {
    type IsSend<S: Send> = Wrapper<S>;
}
```

which similarly fails on nightly and builds on stable.

<details>
<summary>More details</summary>

```console
> rustc --crate-type=lib nightly-auto-trait.rs 
error[E0277]: `(dyn SomethingSomething + 'static)` cannot be sent between threads safely
   --> nightly-auto-trait.rs:13:28
    |
13  |     type IsSend<S: Send> = Wrapper<S>;
    |                            ^^^^^^^^^^ `(dyn SomethingSomething + 'static)` cannot be sent between threads safely
    |
    = help: the trait `Send` is not implemented for `(dyn SomethingSomething + 'static)`
    = note: required for `Unique<(dyn SomethingSomething + 'static)>` to implement `Send`
note: required because it appears within the type `Box<dyn SomethingSomething>`
   --> /home/adam/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:195:12
    |
195 | pub struct Box<
    |            ^^^
note: required because it appears within the type `Wrapper<S>`
   --> nightly-auto-trait.rs:3:8
    |
3   | struct Wrapper<T> {
    |        ^^^^^^^
note: required by a bound in `HasSend::IsSend`
   --> nightly-auto-trait.rs:9:27
    |
9   |     type IsSend<T: Send>: Send;
    |                           ^^^^ required by this bound in `HasSend::IsSend`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
```

on the above-mentioned nightly version whereas stable is happy

```console
> rustc +stable --crate-type=lib nightly-auto-trait.rs 
warning: fields `something` and `other` are never read
 --> nightly-auto-trait.rs:4:5
  |
3 | struct Wrapper<T> {
  |        ------- fields in this struct
4 |     something: Box<dyn SomethingSomething>,
  |     ^^^^^^^^^
5 |     other: T,
  |     ^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: 1 warning emitted
```

Simply asserting that `Wrapper` is `Send + Sync` via e.g. `fn is_send_sync<T: Send + Sync>(_: T) {}` works on stable and nightly.

</details>

**Comment by lqd** [comment]
The reproducer wouldn't compile on stable though?

**Comment by adamreichold** [comment]
> The reproducer wouldn't compile on stable though?

Sorry, I must have messed something up when trying to whittle it down as the reproducer I start with definitely did compile on stable. Will try to trace my steps backwards.

**Comment by adamreichold** [comment]
And using

```rust

struct Wrapper<T> {
    something: Box<dyn SomethingSomething>,
    other: T,
}
```

instead of

```rust
struct Wrapper<T> {
    something: &'static dyn SomethingSomething,
    other: T,
}
```

makes it compile on stable. (I wanted to avoid `Box` to avoid the standard library but indeed `Box` is closer to the original code in question.)

I updated the reproducer in the OP accordingly.

**Comment by lqd** [comment]
Great, thank you.

So I believe this to be a different manifestation of #117598 from #117131 cc @compiler-errors

**Comment by ivmarkov** [comment]
Stumbled on this separately in my own code. The simplest reproduction I was able to come up with is
```rust
pub trait Foo {
    type Gat<F>: Send;
}

pub struct Bar;

impl Foo for Bar {
    type Gat<F> = Box<dyn FnOnce() + Send + 'static>;
}
```

Removing `F` makes it compile on nightly as well. Putting a `Send` bound on `F` does not help.
