### ISSUE TITLE
Implement some garbage collector

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#11778]
I don't see any issue about just getting garbage collection working, which it increasingly looks like we want to have done for 1.0. Nominating.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#679
