### ISSUE TITLE
placement box

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#11779]
I don't see an issue for our new heap construction syntax. Nominating.

**Comment by aturon** [comment]
We do not necessarily need to *implement* this for 1.0-beta, but we need to at least decide on what our 1.0 story will be before then. Nominating for -beta.

**Comment by pnkfelix** [comment]
Filing as 1.0-beta to ensure we make a decision about what backwards compatibility story is here

**Comment by jroesch** [comment]
cc me

**Comment by nikomatsakis** [comment]
Assigning to felix as he's been working on this.

**Comment by pnkfelix** [comment]
see https://github.com/rust-lang/rfcs/pull/809

**Comment by pnkfelix** [comment]
removing from 1.0 milestone.  (`box` will be unstable for 1.0)

**Comment by steveklabnik** [comment]
this issue has been superceded by https://github.com/rust-lang/rust/issues/27779 as far as I can tell, let me know if it should still be open for some reason.
