### ISSUE TITLE
Can get access to private struct field out of `impl` block

### ISSUE THREAD

**Issue by jacksonn97** [rust-lang/rust#117746]
I have struct definition:
```
// src/draw.rs: line 37
pub struct App {    
    field: Mutex<Field>,
    should_exit: AtomicBool,
    pause: AtomicBool,
    maxgen: AtomicU64,
    upd_timeout: AtomicU64,
    frames: AtomicU16,
}
```

But I can directly access for all these private fields out of `impl` block multiple times:
```
// --snip--
// src/draw.rs: line 201
    let mut field = arc_ticks.field.lock().unwrap();

// --snip--
// src/draw.rs: line 293
    KeyCode::Char('j') => a.upd_timeout.store(del.prev(), Ordering::Relaxed),
    KeyCode::Char('k') => a.upd_timeout.store(del.next(), Ordering::Relaxed),
    KeyCode::Char('q') => a.should_exit.store(true, Ordering::Relaxed),
```
I don't get the compile error, although I have to
(code compile and I get binary)

[Full code](https://github.com/jacksonn97/life_the_game/blob/a717c64a1b84dc0df55c3d67640f86a47f40c763/src/draw.rs)

**Comment by aDotInTheVoid** [comment]
Struct field visibility is module based, not impl-based: https://doc.rust-lang.org/rust-by-example/mod/struct_visibility.html

If you want to hide access to the fields, place the struct in its own module, eg:

```rust
mod app {
    pub struct App {
        x: i32
    }
    
    fn this_works(app: &App) -> i32 {
        app.x
    }
}

fn this_doesnt(app: &app::App) -> i32 {
    app.x
}
```

```

error[E0616]: field `x` of struct `App` is private
  --> src/lib.rs:12:9
   |
12 |     app.x
   |         ^ private field

For more information about this error, try `rustc --explain E0616`.
```

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e258de77058f945e55ac1ac85fc46570)
