### ISSUE TITLE
StorageLive of live local when building tokio with -Zcross-crate-inline-threshold=always + high MIR inlining threshold

### ISSUE THREAD

**Issue by saethlin** [rust-lang/rust#117733]
Reproduces with https://github.com/tokio-rs/tokio on commit `19d96c067410e30da29978be3513824645902a84`

```
cd tokio/tokio
RUSTFLAGS="-Ztreat-err-as-bug -Zcross-crate-inline-threshold=always -Zinline-mir-hint-threshold=10000 -Zinline-mir-threshold=10000" cargo b --release --features sync
```

```
error: internal compiler error: broken MIR in Item(DefId(0:1070 ~ tokio[56a2]::sync::broadcast::{impl#14}::blocking_recv)) (after phase change to runtime-optimized) at bb140[16]:
                                StorageLive(_326) which already has storage here
    --> tokio/src/sync/broadcast.rs:1255:13
     |
1255 |         fut.await
     |             ^^^^^
```

Remove `-Ztreat-err-as-bug`  and add `-Zvalidate-mir` to get a _lot_ of ICEs like this:
[rustc-ice-2023-11-09T01_05_17-2728619.txt](https://github.com/rust-lang/rust/files/13302693/rustc-ice-2023-11-09T01_05_17-2728619.txt)

**Comment by RalfJung** [comment]
So, looks like we should either allow StorageLive on an already live local, or we need to ensure that all locals are explicitly marked StorageDead before returning. No idea how realistic it is to achieve the latter.

Cc @cjgillot @matthewjasper
