### ISSUE TITLE
Some tests are incorrectly skipped for macOS CI

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/rust#117721]
CI specifies these two jobs for x86_64-apple-darwin:

https://github.com/rust-lang/rust/blob/341efb10174bdd22912aae487917c9213255b20f/src/ci/github-actions/ci.yml#L528-L544

Note these two lines (with padding I've added):

```
./x.py --stage 2 test --skip tests/ui --skip tests/rustdoc --skip tests/run-make-fulldeps 
./x.py --stage 2 test        tests/ui        tests/rustdoc        tests/run-make-fulldeps 
```

It appears that the intent was for the first job to run a subset of the tests and the second job to run the complementary subset. However, it seems that `--skip` performs a **substring match** while the list of directories is an **exact match**. This means that the tests in `rustdoc-js`, `rustdoc-json`, and `rustdoc-ui` are never run on macOS CI — they are excluded by `--skip` and never explicitly added back. 

Surprisingly, it seems that tests in `rustdoc-js-std` *are* run. That seems like a secondary bug as it isn't behaving the same.

**Comment by shepmaster** [comment]
My suggestion would be to have another flag that performs the same substring match. For example, using `--only` as the option:

```
./x.py --stage 2 test --skip tests/ui --skip tests/rustdoc --skip tests/run-make-fulldeps 
./x.py --stage 2 test --only tests/ui --only tests/rustdoc --only tests/run-make-fulldeps 
```

**Comment by onur-ozkan** [comment]
If you don't want `--skip` to match as a SUBSTRING, you can use the --exact flag with `x`.

e.g., `x --stage 2 tests/rustdoc-js --skip tests/rustdoc --force-rerun -- --exact`

Does this help?

**Comment by onur-ozkan** [comment]
> If you don't want `--skip` to match as a SUBSTRING, you can use the --exact flag with `x`.
> 
> e.g., `x --stage 2 tests/rustdoc-js --skip tests/rustdoc --force-rerun -- --exact`
> 
> Does this help?

This should work fine, feel free to re-open the issue if it doesn't help.

**Comment by madsmtm** [comment]
We need to actually _do_ this in our CI IMO before the issue should be closed.

**Comment by onur-ozkan** [comment]
> We need to actually _do_ this in our CI IMO before the issue should be closed.

Yeah, makes sense.
