### ISSUE TITLE
`self: &Box<Self>` produces confusing error due to failure to spot elided lifetime

### ISSUE THREAD

**Issue by adetaylor** [rust-lang/rust#117715]
### Code

```Rust
struct Concrete(u32);

impl Concrete {
    fn m(self: &std::boxed::Box<Self>) -> &u32 {
        &self.0
    }
}
```

### Current output

```Shell
error[E0106]: missing lifetime specifier
 --> src/lib.rs:4:43
  |
4 |     fn m(self: &std::boxed::Box<Self>) -> &u32 {
  |                ----------------------     ^ expected named lifetime parameter
  |
  = help: this function's return type contains a borrowed value, but the signature does not say which `self` it is borrowed from
help: consider introducing a named lifetime parameter
  |
4 |     fn m<'a>(self: &'a std::boxed::Box<Self>) -> &'a u32 {
  |         ++++        ++                            ++

For more information about this error, try `rustc --explain E0106`.
error: could not compile `playground` (lib) due to previous error
```

### Desired output

```Shell
Ideally, rustc recognizes the elided lifetime in the `self` parameter and uses that.

Alternatively, "the signature does not say which `self` it is borrowed from" is reworded to more accurately describe the error.
```

### Anything else?

```rust
fn n(self: &std::boxed::Box<Self>, _other: &u32) -> &u32 {
    &self.0
}
```

results in an error where rustc assumes we're returning the `_other` parameter, which presumably results from the same failure to spot a lifetime attached to `self`.

This issue was identified during discussion about a new Rust [RFC, here](https://github.com/rust-lang/rfcs/pull/3519#discussion_r1381792163).

I suspect this is caused by something within `find_lifetime_for_self` which isn't aware of the need to support things like `Box` as a `self` type: I haven't spotted the bug yet, I thought it was more important to get it reported properly first.

**Comment by RalfJung** [comment]
Yeah that definitely seems wrong.

Cc @rust-lang/types ? not sure who's in charge of lifetime elision

**Comment by adetaylor** [comment]
Some analysis/proposals.

### How `find_lifetime_for_self` currently works

Visits the type.
Recurses inwards, finding all references.
For each reference, if the referent is a "self type", consider the lifetime of that reference. ("Self type" means implicit `self` or a type which resolves to `Self` (specifically, either `Res::SelfTyParam` or `Res::SelfTyAlias`)
If exactly one such lifetime is found, that's the one which gets used.

### Why this isn't good enough

This doesn't work for `&Box<Self>` because the referent is not the `Self` type itself.

### What we could do

Options:

1. Simply retrieve _all_ the lifetimes from any type which contains `Self` anywhere. Since we only elide lifetimes if there's exactly one, there's no risk of ambiguity here - we'll simply require folks to specify a lifetime in this case. However this _would_ be a backwards incompatible change. This currently works: `self: &Box<&Self>`. That feels bad, but it's a fact. We would no longer elide those lifetimes.
2. Change the definition of "is self type" to recurse further into the type, to confirm that (a) there's `Self` somewhere in there, and (b) there's no direct reference to `self` in there.

### What I think we should do

I think that depends on the Rust community's attitude to backwards compatibility. Should we maintain compatibility and continue to elide lifetimes on `&Boxed<&Self>`? If so, we do option 2. If we're OK breaking compatibility there, we should do option 1.

However, first of all I'll try option 1 and run rustc's unit tests to see if the above analysis is right.

**Comment by RalfJung** [comment]
> Simply retrieve all the lifetimes from any type which contains `Self` anywhere. 

That makes no sense to me. Elision treats the `self` argument special, not the `Self` type.

**Comment by adetaylor** [comment]
> Elision treats the self argument special, not the Self type.

All the code I'm talking about is only ever applied to the `self` parameter.

**Comment by RalfJung** [comment]
Oh I see, thanks for clarifying. I would say we should check the entire type for lifetimes, yes. That is the receiver type. We should not have accepted `&Boxed<&Self>`.

I am still confused, though. We currently *entirely ignore* the outer lifetime of the argument. In `fn n(self: &std::boxed::Box<Self>, other: &u32) -> &u32`, the return type gets the *second* argument's lifetime. Somehow the traversal seems to skip the things surrounding `Self` entirely not just in order to resolve an ambiguity of the return type lifetime, but even when determining whether there is such an ambiguity in the first place?

So, this must be a breaking change anyway since `fn n(self: &std::boxed::Box<Self>, other: &u32) -> &u32` should either be rejected or use the `self` lifetime, but definitely should not use the `other` lifetime.

**Comment by adetaylor** [comment]
In the case of `&Box<&Self>`, it's ignoring the outer `&` because it currently only considers lifetimes which are directly applied to the `Self` itself, i.e. the inner lifetime.

I'll have a crack at option 1 and see what breaks in the unit tests. I'm sure I'll learn something!

**Comment by adetaylor** [comment]
The sort of fix I think we need is [something like this](https://github.com/rust-lang/rust/pull/117967), however, it's not quite right yet and lots of the existing elision tests fail (plus I haven't pulled the most recent rustc code for ages, so it's out of date). Parking it here because I'm unlikely to get time to work on it for a few days at least.

**Comment by adetaylor** [comment]
The simple option doesn't pass tests here due to a test called `ref-assoc.rs` which contains:

```rust
trait Trait {
    type AssocType;
}

struct Struct { }

impl Trait for Struct {
    type AssocType = Self;
}

impl Struct {
    fn ref_AssocType(self: &<Struct as Trait>::AssocType, f: &u32) -> &u32 {
        f
    }
}
```
(there are some other similar tests too)

Previously, this worked because `&<Struct as Trait>::AssocType` did not have the `&` directly next to `Self`, so `self` was not considered a valid `self` for elision purposes.

If we search the whole type hierarchy for `Self` and search the whole hierarchy for `&` then we'll suddenly consider `self` valid for elision purposes, and this test will fail.

So the question is, can we be sure that the `Self` here in this associated type really is the `Self` of the method receiver? I think we probably _can_, and therefore we should alter this test to fit the desired behavior.

There are also some `FIXME`s hanging around here, such as [this one](https://github.com/rust-lang/rust/blob/2f8d81f9dbac6b8df982199f69da04a4c8357227/tests/ui/self/elision/ref-alias.rs#L14).

(Again all this code only applies to the first parameter).

**Comment by RalfJung** [comment]
IMO that test is clearly buggy, the lifetime of the return value is ambiguous. It should either fail because the lifetime is ambiguous or fail because it uses the `self` lifetime and then the return expression has the wrong type.

We might want to do a transition here where we first warn that such code will be rejected in the future, before we start rejecting it. Would be good to get a crater run to tell us how common this pattern is.

Cc @rust-lang/types for more input.

**Comment by lcnr** [comment]
I agree that the current behavior of `self: &Box<ConcreteSelf>` is a bug in our lifetime elision impl. I would also like to go with approach 1, but would wait for a crater run with that approach to gauge the impact.

**Comment by adetaylor** [comment]
I've marked https://github.com/rust-lang/rust/pull/117967 as ready for review. It goes with approach 1.
