### ISSUE TITLE
Doubts about Method `get_or_insert`?

### ISSUE THREAD

**Issue by esscool** [rust-lang/rust#117837]
I tried this code:

```rust
use std::cell::RefCell;

pub struct Cache {
    list: Vec<Vec<String>>,
}

thread_local! {
    static GLOBAL_CACHES:RefCell<Cache> = const { RefCell::new(Cache { list: vec![] }) };
}

/// The first way to cache strings, it works. ✅
pub fn cache_1(msg: &'static str) {
    let msg = msg.to_string();
    GLOBAL_CACHES.with_borrow_mut(|caches| {
        if let Some(last) = caches.list.last_mut() {
            last.push(msg);
        } else {
            caches.list.push(vec![msg]);
        }
    });
}

/// The second way of caching strings, that didn't work. ❌
pub fn cache_2(msg: &'static str) {
    let msg = msg.to_string();
    GLOBAL_CACHES.with_borrow_mut(|caches| {
        // `get_or_insert` is this a bug? 🤒
        caches.list.last_mut().get_or_insert(&mut vec![]).push(msg);
    });
}

#[test]
fn test_cache_1() {
    cache_1("hello!");
    cache_1("hello!");
    assert_eq!(GLOBAL_CACHES.with_borrow(|cache| cache.list.len()), 1);
}

#[test]
fn test_cache_2() {
    cache_2("hello!");
    cache_2("hello!");
    assert_eq!(GLOBAL_CACHES.with_borrow(|cache| cache.list.len()), 1);
}

```

I expected to see this happen: *cache.list.len()==1*

Instead, the `cache_2` happened: *cache.list.len()==0*

### Meta

`rustc --version --verbose`:
```
binary: rustc
commit-hash: cc66ad468955717ab92600c770da8c1601a4ff33
commit-date: 2023-10-03
host: x86_64-apple-darwin
release: 1.73.0
LLVM version: 17.0.2
```

<details><summary>`RUST_BACKTRACE=1 cargo test` Backtrace</summary>
<p>

```
running 2 tests
test test_cache_1 ... ok
test test_cache_2 ... FAILED

failures:

---- test_cache_2 stdout ----
thread 'test_cache_2' panicked at src/lib.rs:43:5:
assertion `left == right` failed
  left: 0
 right: 1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:229:5
   4: bug_get_or_insert::test_cache_2
             at ./src/lib.rs:43:5
   5: bug_get_or_insert::test_cache_2::{{closure}}
             at ./src/lib.rs:40:19
   6: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    test_cache_2

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s
```

</p>
</details>

Test on [Rust Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&code=use+std%3A%3Acell%3A%3ARefCell%3B%0A%0Apub+struct+Cache+%7B%0A++++list%3A+Vec%3CVec%3CString%3E%3E%2C%0A%7D%0A%0Athread_local%21+%7B%0A++++static+GLOBAL_CACHES%3ARefCell%3CCache%3E+%3D+const+%7B+RefCell%3A%3Anew%28Cache+%7B+list%3A+vec%21%5B%5D+%7D%29+%7D%3B%0A%7D%0A%0A%2F%2F%2F+The+first+way+to+cache+strings%2C+it+works.+%E2%9C%85%0Apub+fn+cache_1%28msg%3A+%26%27static+str%29+%7B%0A++++let+msg+%3D+msg.to_string%28%29%3B%0A++++GLOBAL_CACHES.with_borrow_mut%28%7Ccaches%7C+%7B%0A++++++++if+let+Some%28last%29+%3D+caches.list.last_mut%28%29+%7B%0A++++++++++++last.push%28msg%29%3B%0A++++++++%7D+else+%7B%0A++++++++++++caches.list.push%28vec%21%5Bmsg%5D%29%3B%0A++++++++%7D%0A++++%7D%29%3B%0A%7D%0A%0A%2F%2F%2F+The+second+way+of+caching+strings%2C+that+didn%27t+work.+%E2%9D%8C%0Apub+fn+cache_2%28msg%3A+%26%27static+str%29+%7B%0A++++let+msg+%3D+msg.to_string%28%29%3B%0A++++GLOBAL_CACHES.with_borrow_mut%28%7Ccaches%7C+%7B%0A++++++++%2F%2F+%60get_or_insert%60+is+this+a+bug%3F+%F0%9F%A4%92%0A++++++++caches.list.last_mut%28%29.get_or_insert%28%26mut+vec%21%5B%5D%29.push%28msg%29%3B%0A++++%7D%29%3B%0A%7D%0A%0A%23%5Btest%5D%0Afn+test_cache_1%28%29+%7B%0A++++cache_1%28%22hello%21%22%29%3B%0A++++cache_1%28%22hello%21%22%29%3B%0A++++assert_eq%21%28GLOBAL_CACHES.with_borrow%28%7Ccache%7C+cache.list.len%28%29%29%2C+1%29%3B%0A%7D%0A%0A%23%5Btest%5D%0Afn+test_cache_2%28%29+%7B%0A++++cache_2%28%22hello%21%22%29%3B%0A++++cache_2%28%22hello%21%22%29%3B%0A++++assert_eq%21%28GLOBAL_CACHES.with_borrow%28%7Ccache%7C+cache.list.len%28%29%29%2C+1%29%3B%0A%7D%0A)

**Comment by ehuss** [comment]
The `Option` returned by `last_mut` is a value unto itself. It is not directly tied to the last element of the `Vec` (the `None` has no relationship to the `Vec`, it is a local value). When the value is `None`, and you call `get_or_insert` on `None`, that only replaces the `None` with a `Some(&mut Vec)`, it doesn't then also push that onto the end of the `Vec`. Only when `last_mut` returns `Some` does that value inside the `Some` have a relationship with the `Vec`.

I suspect your first example is the correct way to handle it.

In the future, questions like these are usually better asked on a user forum, such as https://users.rust-lang.org/.

**Comment by esscool** [comment]
@ehuss I am learning rust thanks for the clarification. It's kind of a counter-intuitive question for me. Made me think it was a mistake.
If there is lint, just say that it is not recommended to use this way...

Or a little description of this in the method documentation could help more people like me.

I can edit relevant documents to submit, do you think it is necessary?
