### ISSUE TITLE
For a typo `let_some_variable =`, suggest `let some_variable =` instead of `let let_some_variable =`

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/rust#117894]
### Code

```Rust
fn main() {
    let_some_variable = 6;
}
```

### Current output

```Shell
error[E0425]: cannot find value `let_some_variable` in this scope
 --> src/main.rs:2:5
  |
2 |     let_some_variable = 6;
  |     ^^^^^^^^^^^^^^^^^
  |
help: you might have meant to introduce a new binding
  |
2 |     let let_some_variable = 6;
  |     +++
```

### Desired output

```Shell
error[E0425]: cannot find value `let_some_variable` in this scope
 --> src/main.rs:2:5
  |
2 |     let_some_variable = 6;
  |     ^^^^^^^^^^^^^^^^^
  |
help: you might have meant to introduce a new binding
  |
2 |     let some_variable = 6;
  |        +
```

### Rationale and extra context

I accidentally typoed an underscore instead of a space between `let` and the name of the new variable I was trying to declare. If a binding isn't found, and it starts with `let_` (or frankly `letsome_variable`, if you forget/miss the space completely), it seems like it would be more likely to suggest `let ` (`let` plus a space) rather than the current suggestion of an additional `let `.

### Anything else?

[@estebank said I should file this ❤️ ](https://hachyderm.io/@ekuber/111405360507141151)

**Comment by Young-Flash** [comment]
interesting, I'd like to have a try. but might not solve it quicklly casuze I am new to rustc
