### ISSUE TITLE
TAIT decision on "may define implies must define"

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#117861]
Nominating for T-lang to decide whether to adopt the following restriction for the stabilization of TAIT:

> At least until the new trait solver is stabilized, any item that is allowed to define the hidden type of some opaque type *must* define the hidden type of that opaque type.

If adopted, we would call this the "may define implies must define" restriction.

**For the purposes of this question, please set aside how we know whether an item is allowed to define the hidden type; this question is invariant to the details of that.**

This restriction leaves space for the new trait solver.  That solver will consider more uses of the opaque type to be defining and it will implement lazy normalization.  Given this, items that may define the hidden type but do not present the potential for differences between the old and new solver that we would prefer to avoid so as to ease the stabilization of the new trait solver.

With this restriction, TAIT becomes roughly equivalent to RPIT with respect to many of the relevant challenges.

The effect of this restriction would be to reject the following code:

```rust
#![feature(type_alias_impl_trait)]

type Tait = impl Sized;
fn define() -> Tait {} // Defines the hidden type.
fn passthrough(x: Tait) -> Tait { // Allowed to define but does not.
    // ~^ ERROR Any item that may define a hidden type must define that hidden type.
    x
}
```

Please set aside how we know that `define` and `passthrough` are both allowed to define the hidden type of the opaque.  There are many ways that could be notated, and that question is orthogonal to this restriction.

Whether or not this restriction could be lifted later is a question of what is possible under the new trait solver and of what other rules we might decide to adopt that may make this more or less possible.  Adopting this restriction now does not in and of itself close the door to possibly permitting this later.

This rule was described and proposed in the 2023-11-08 T-lang Mini-TAIT design meeting ([minutes](https://hackmd.io/CDj92gZdTzilDWORdKhLQA)): rust-lang/lang-team#233.

## Related

- https://github.com/rust-lang/trait-system-refactor-initiative/issues/32
- https://github.com/rust-lang/trait-system-refactor-initiative/issues/40
- https://github.com/rust-lang/trait-system-refactor-initiative/issues/69
- https://github.com/rust-lang/trait-system-refactor-initiative/issues/74

**Comment by oli-obk** [comment]
I'm going to overrule any language concerns due to critical implementation concerns, which thoroughly puts this into T-types territory. T-lang can still review this and give advice or opinions when they get to this issue.

**Comment by oli-obk** [comment]
Implementation update:

During my work on https://github.com/rust-lang/rust/pull/121796 and subsequently https://github.com/rust-lang/rust/pull/122077, i realized that the keys of `TypeckResults::concrete_opaque_types` mostly correspond to `opaque_types_defined_by` (they are a subset), but it would require less checks (and thus have fewer potential causes of inconsistencies and thus bugs) if we had just a single table.

**Comment by oli-obk** [comment]
@rfcbot merge

**Comment by jackh726** [comment]
What's the decision here? To adopt to rule as stated in the OP?

**Comment by lcnr** [comment]
in case somebody wants to look at the cases where non-defining uses in the defining scope cause issues[^1]:
- https://github.com/rust-lang/trait-system-refactor-initiative/issues/74
- https://github.com/rust-lang/trait-system-refactor-initiative/issues/69
- https://github.com/rust-lang/trait-system-refactor-initiative/issues/40
- https://github.com/rust-lang/trait-system-refactor-initiative/issues/32 (you can't prove auto trait bounds for opaques in their defining scope without defining them)

[^1]: *i mostly opened these issues to avoid forgetting about them myself, they lack a lot of background info*

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by oli-obk** [comment]
Actually, need to finish the impl that actually enforces this
