### ISSUE TITLE
Rustc does not recognize ustatus as a valid riscv system register

### ISSUE THREAD

**Issue by zflcs** [rust-lang/rust#117826]
```rust
#[no_mangle]
pub fn rust_main(hart_id: usize) -> ! {

    unsafe { asm!("csrr t0, usstatus"); }
    loop {   }
}
```

```text
error: operand must be a valid system register name or an integer in the range [0, 4095]
   --> src/main.rs:144:20
    |
144 |     unsafe { asm!("csrr t0, usstatus"); }
    |                    ^
```

**Comment by zflcs** [comment]
Sorry, the `usstatus` in the code is an error when typing. But after modifying it to `ustatus` is still the same error.

**Comment by asquared31415** [comment]
It appears that the `ustatus` register is an extension, and it's possible that LLVM does not know that name.  Can you use the integer value instead?

**Comment by zflcs** [comment]
> It appears that the `ustatus` register is an extension, and it's possible that LLVM does not know that name. Can you use the integer value instead?

When I use the integer value, it's ok. One month ago, I can directly use `ustatus` in the `inline_asm`, but today I try it and failed. And in some embedded platform, there are only `Machine` and `Supervisor` modes, I think rust should support this usage.

**Comment by bjorn3** [comment]
LLVM is responsible for turning inline asm into machine code. I can find `sstatus` in the LLVM source: https://github.com/llvm/llvm-project/blob/f575d792c6467234076f860fe7eecced620d3aae/llvm/lib/Target/RISCV/RISCVSystemOperands.td#L122, but `ustatus` was removed in https://github.com/llvm/llvm-project/commit/f0c36dc964a808438c0ef717f1998754c721543f for the following reason:

https://reviews.llvm.org/D149278

> These are from the N extension (User-Level Interrupts) which did not make it into 1.12 of the Privileged Specification.

**Comment by zflcs** [comment]
> LLVM is responsible for turning inline asm into machine code. I can find `sstatus` in the LLVM source: https://github.com/llvm/llvm-project/blob/f575d792c6467234076f860fe7eecced620d3aae/llvm/lib/Target/RISCV/RISCVSystemOperands.td#L122, but `ustatus` was removed in [llvm/llvm-project@f0c36dc](https://github.com/llvm/llvm-project/commit/f0c36dc964a808438c0ef717f1998754c721543f) for the following reason:
> 
> https://reviews.llvm.org/D149278
> 
> > These are from the N extension (User-Level Interrupts) which did not make it into 1.12 of the Privileged Specification.

Thanks, I got it.
