### ISSUE TITLE
Can't implement methods for an imported struct type without using global path

### ISSUE THREAD

**Issue by nham** [rust-lang/rust#11798]
This  does not work:

    use foo::Bar;

    fn main() {
        impl Bar {
            fn boop(&self) -> bool {
                true
            }
        }

        let y = Bar {y: 8};
        println!("{}", y.boop());
    }

    mod foo {
        pub struct Bar {
            y: int,
        }
    }

It results in:

    module_name_used_type.rs:10:13: 10:16 error: `Bar` does not name a structure
    module_name_used_type.rs:10     let y = Bar {y: 8};
                                            ^~~
Changing "impl Bar" to "impl ::foo::Bar" on line 3 does work, however. Is this the intended behavior?

**Comment by steveklabnik** [comment]
This now has a real error message:

```
hello.rs:4:10: 4:13 error: inherent implementations are not allowed for types not defined in the current module
hello.rs:4     impl Bar {
                    ^~~
error: aborting due to previous error

```

**Comment by steveklabnik** [comment]
And yes, as the error says, this is expected.
