### ISSUE TITLE
bootstrap: fingerprinting is broken somehow

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#117983]
I noticed that 2 subsequent `x.py check` runs would recheck a bunch of tools even with no code change in between :/

repro:
inside git repo, run
````
RUSTFLAGS="" RUSTC_WRAPPER=""  ./x.py check
RUSTFLAGS="" RUSTC_WRAPPER=""  ./x.py check
````
the second run will not finish immediately but recheck some stuff for some reason.

**Comment by matthiaskrgr** [comment]
Since we just updated bootstrap, this might as well be a cargo bug of some sort.

**Comment by onur-ozkan** [comment]
#117850 fixes this.
