### ISSUE TITLE
Rustdoc warning blocks (admonitions) do not render nested markdown

### ISSUE THREAD

**Issue by tgross35** [rust-lang/rust#117904]
I tried this code:

```rust
struct Foo {
    /// Metadata required to regenerate an encryption key.
    ///
    /// Both this metadata and a connection to the Tang server are needed to regenerate the
    /// key for use with encryption. This data can be stored in JSON form.
    ///
    /// **WARNING1**
    ///
    /// <div class="warning">**WARNING2** _italic_ normal</div>
    pub meta: KeyMeta,
}
```

I expected to see this happen: *explanation*

The text within the div should be rendered like markdown

Instead, this happened: *explanation*

![image](https://github.com/rust-lang/rust/assets/13724985/e5f3414e-2e75-4a8b-afe8-d1c504d8135f)

### Meta

`rustc --version --verbose`:
```
rustc 1.75.0-nightly (31bc7e2c4 2023-10-30)
binary: rustc
commit-hash: 31bc7e2c47e82798a392c770611975a6883132c8
commit-date: 2023-10-30
host: x86_64-unknown-linux-gnu
release: 1.75.0-nightly
LLVM version: 17.0.3
```

@rustbot label +T-rustdoc +A-rustdoc-ui

**Comment by tgross35** [comment]
It is possible that this is the expected behavior since I think markdown just ignores everything in HTML tags. It would just be unfortunate to need to resort to HTML for formatting in admonitions.

**Comment by Urgau** [comment]
I think this is expected, even with GitHub Markdown processor doesn't render inline Markdown. However if you put new lines after and before the divs, it works.

Try this:
```diff,rust
 struct Foo {
     /// Metadata required to regenerate an encryption key.
     ///
     /// Both this metadata and a connection to the Tang server are needed to regenerate the
     /// key for use with encryption. This data can be stored in JSON form.
     ///
     /// **WARNING1**
     ///
-    /// <div class="warning">**WARNING2** _italic_ normal</div>
+    /// <div class="warning">
+    ///
+    /// **WARNING2** _italic_ normal
+    ///
+    /// </div>
     pub meta: KeyMeta,
 }
```

**Comment by fmease** [comment]
I'm inclined to close this as works-as-intended or wontfix. However, we could add a chapter to the [rustdoc book](https://doc.rust-lang.org/rustdoc/index.html) documenting some common (heh) pitfalls of CommonMark.
