### ISSUE TITLE
Add support for specifying external libraries by filename

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#11802]
Some libraries have multiple filenames:

```
set(ZLIB_NAMES z zlib zdll zlib1 zlibd zlibd1)
```

There is currently no way to tell rustc that `#[link(name = "z")]` should be satisfied by `zlib1.dll`.

**Comment by steveklabnik** [comment]
triage: nothing has changed with `link` in a while.

**Comment by steveklabnik** [comment]
Triage: no change here. That said, I would expect that maybe this is something that should be going through Cargo and build scripts, rather than modifying `link`?

**Comment by nagisa** [comment]
This seems fairly close to being closed. The need is satisfied by the build scripts, which is the generally accepted way to do complex linking decisions.

**Comment by Dylan-DPC** [comment]
Closing this as it can be done by build scripts. Thanks
