### ISSUE TITLE
`const_trait` does not work on latest nightly toolchain

### ISSUE THREAD

**Issue by lictex** [rust-lang/rust#118092]
i ve got some compilation errors around the `static_assertions::const_assert_eq!` recently.  after some investigation they seem to be caused by the rustc.  repro:
```rust
#![feature(const_trait_impl)]

pub struct A;

#[const_trait]
pub trait B {
    fn test() -> usize;
}
impl const B for A {
    fn test() -> usize {
        0
    }
}

fn main() {
    const _: usize = A::test();
}
```

the code above compiles on `nightly-2023-08-08` but not on `nightly-2023-08-09` & `nightly`:
```
error[E0015]: cannot call non-const fn `<A as B>::test` in constants
  --> src/main.rs:16:22
   |
16 |     const _: usize = A::test();
   |                      ^^^^^^^^^
   |
   = note: calls in constants are limited to constant functions, tuple structs and tuple variants

For more information about this error, try `rustc --explain E0015`.
```

while this is an unstable feature, i didn t find any info about this change, is this expected?

**Comment by fmease** [comment]
You need to also enable the feature `effects`. Currently there's a rewrite happening for const trait impls.

**Comment by lictex** [comment]
ok that works thanks!
