### ISSUE TITLE
Bootstrap sometimes fails to build miri because of "nightly" feature confusion

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#118129]
Step to reproduce:
```
rm build/host/stage0* -rf
./x.py check library/std compiler/rustc src/tools/miri
```
Now Miri fails to build with >1800 errors. The first ones are:
```
error[E0464]: multiple candidates for `rmeta` dependency `rustc_ast` found
  --> src/tools/miri/src/lib.rs:53:1
   |
53 | extern crate rustc_ast;
   | ^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: candidate #1: /home/r/src/rust/rustc.2/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_ast-11854d11a3563889.rmeta
   = note: candidate #2: /home/r/src/rust/rustc.2/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_ast-feb80e66ce1c74d4.rmeta

error[E0464]: multiple candidates for `rmeta` dependency `rustc_const_eval` found
  --> src/tools/miri/src/lib.rs:54:1
   |
54 | extern crate rustc_const_eval;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: candidate #1: /home/r/src/rust/rustc.2/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_const_eval-078a7b0d61866866.rmeta
   = note: candidate #2: /home/r/src/rust/rustc.2/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_const_eval-2fa8de12acbc8979.rmeta

error[E0464]: multiple candidates for `rmeta` dependency `rustc_data_structures` found
  --> src/tools/miri/src/lib.rs:55:1
   |
55 | extern crate rustc_data_structures;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: candidate #1: /home/r/src/rust/rustc.2/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_data_structures-93605ddb6ab78ed8.rmeta
   = note: candidate #2: /home/r/src/rust/rustc.2/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_data_structures-e65a21da042ec502.rmeta

error[E0464]: multiple candidates for `rmeta` dependency `rustc_errors` found
  --> src/tools/miri/src/lib.rs:56:1
   |
56 | extern crate rustc_errors;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: candidate #1: /home/r/src/rust/rustc.2/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_errors-792f00940afc5752.rmeta
   = note: candidate #2: /home/r/src/rust/rustc.2/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_errors-ddd5d12697277ea9.rmeta

error[E0464]: multiple candidates for `rmeta` dependency `rustc_hir` found
  --> src/tools/miri/src/lib.rs:57:1
   |
57 | extern crate rustc_hir;
   | ^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: candidate #1: /home/r/src/rust/rustc.2/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_hir-37bcaf20f0254cb3.rmeta
   = note: candidate #2: /home/r/src/rust/rustc.2/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_hir-6f8ad5718a5b342e.rmeta
```

However, if I now run `./x.py check miri`, everything is fine. `rm build/host/stage0* -rf && ./x.py check miri` is also fine. Something about explicitly giving the three paths to build is throwing bootstrap off. And even more strangely, the same sequence of commands worked fine before https://github.com/rust-lang/rust/pull/116828.

Cc @rust-lang/bootstrap

**Comment by onur-ozkan** [comment]
`compiler/rustc_index_macros` should be compiled with its default feature `nightly`. However, in `rustc_index`, this feature disabled by default. When compiling these specific paths (library/std compiler/rustc src/tools/miri), `rustc_index_macros` is not built with its default feature. A quick workaround for your case would be to run `x check library/std compiler/rustc compiler/rustc_index_macros src/tools/miri`.

**Comment by RalfJung** [comment]
FWIW I cannot reproduce the problem any more. Has this been fixed?

**Comment by RalfJung** [comment]
Actually never mind the issue still exists

**Comment by RalfJung** [comment]
@onur-ozkan 
> However, in rustc_index, this feature disabled by default. 

I don't understand this explanation. Looking at the Cargo.toml, we have
```
rustc_index_macros = { path = "../rustc_index_macros", default-features = false }
```
and
```
[features]
# tidy-alphabetical-start
default = ["nightly"]
nightly = [
    "dep:rustc_serialize",
    "dep:rustc_macros",
    "rustc_index_macros/nightly",
]
rustc_randomized_layouts = []
# tidy-alphabetical-end
```
So by default, we do enable `rustc_index_macros/nightly`.

Why does adding `compiler/rustc_index_macros` even make any difference here? This is all quite strange to me.

**Comment by RalfJung** [comment]
Cc @compiler-errors

**Comment by compiler-errors** [comment]
what am i being ccd for

**Comment by RalfJung** [comment]
@compiler-errors you wrote some of the commits adding this "nightly" feature everywhere (e.g. https://github.com/rust-lang/rust/commit/4506681e2f53e17df0d74cd230948dc40f7d0e8d). Somehow that is causing issues with building Miri. I don't understand how this nightly feature is being enabled/disabled where, so I figured maybe you can help.

**Comment by RalfJung** [comment]
I think I found another work-around: `./x check library compiler miri` also works. It's just `compiler/rustc` that causes problems. I have no idea why...

**Comment by compiler-errors** [comment]
not totally sure, but sounds like a bootstrap issue 🤔

**Comment by onur-ozkan** [comment]
It's more of a cargo thing (I am not sure if this is an expected behaviour or not). When `default-features = false` is set, cargo can't propagate "nightly" feature which is a default feature for `compiler/rustc_index_macros/Cargo.toml` but disabled with `default-features = false` in `compiler/rustc_index/Cargo.toml`.


See https://github.com/rust-lang/rust/pull/134526 for the fix.

cc @rust-lang/cargo
