### ISSUE TITLE
Dead code lint should include unused default trait methods in the unused chain

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/rust#118139]
### Code

```Rust
enum Category {
    Dead,
    Used,
}

trait Demo {
    fn this_is_unused(&self) -> Category {
        Category::Dead
    }
}

fn main() {
    let _c = Category::Used;
}
```

### Current output

```
warning: variant `Dead` is never constructed
 --> src/main.rs:2:5
  |
1 | enum Category {
  |      -------- variant in this enum
2 |     Dead,
  |     ^^^^
  |
  = note: `#[warn(dead_code)]` on by default
```

### Desired output

(in addition to the existing output)

```
warning: method `Demo::this_is_unused` is never used
 --> src/lib.rs:LL:CC
  |
L |     fn this_is_unused(&self) -> Category {
  |        ^^^^^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default
```

### Rationale and extra context

When I encountered this lint, I deleted the enum variant, but then got a compiler error as the variant was used within the trait's method. Nowhere did the compiler let me know that it's because the trait's method was unused.

### Anything else?

It appears that trait methods are never _reported_ as dead code — this example has no warnings:

```rust
trait Demo {
    fn unused_1(&self);
    fn unused_2(&self) {}
}
```

However, I assume something is analyzing to see that the function is unused because otherwise the enum variant couldn't be transitively marked as unused.

**Comment by Urgau** [comment]
Apparently, not warning on trait items is known and explicit.

https://github.com/rust-lang/rust/blob/2f8d81f9dbac6b8df982199f69da04a4c8357227/compiler/rustc_passes/src/dead.rs#L1044

**Comment by shepmaster** [comment]
> not warning on trait items is [...] explicit.

I half expected that to be the case. I have two parallel thoughts:

1. Well, why not? I *want* to know about (non-public) traits and trait methods that I'm not using.
2. If there *is* some good reason to not warn about dead trait methods, could we enhance the current message to mention them? For example, "variant `Dead` is never constructed. It's used in <this trait method> which is also unused"

**Comment by shepmaster** [comment]
#41883 is the issue about making traits / trait methods detected by the dead code lint.
