### ISSUE TITLE
no method named `si_pid` found for struct `siginfo_t` for armv7-unknown-linux-uclibceabihf

### ISSUE THREAD

**Issue by asomers** [rust-lang/rust#118190]
I tried this code:

```rust
fn main() {
    println!("Hello, world!");
}
```
```
cargo check -Zbuild-std --target armv7-unknown-linux-uclibceabihf
```

I expected to see this happen: it should work

Instead, this happened: the build fails like this:
```
error[E0599]: no method named `si_pid` found for struct `siginfo_t` in the current scope
   --> /localhome/somers/.rustup/toolchains/nightly-x86_64-unknown-freebsd/lib/rustlib/src/rust/library/std/src/sys/unix/process/process_unix.rs:879:33
    |
879 |             if unsafe { siginfo.si_pid() } == 0 {
    |                                 ^^^^^^ method not found in `siginfo_t`

error[E0599]: no method named `si_status` found for struct `siginfo_t` in the current scope
   --> /localhome/somers/.rustup/toolchains/nightly-x86_64-unknown-freebsd/lib/rustlib/src/rust/library/std/src/sys/unix/process/process_unix.rs:917:39
    |
917 |         let status = unsafe { siginfo.si_status() };
    |                                       ^^^^^^^^^ method not found in `siginfo_t`

For more information about this error, try `rustc --explain E0599`.
```

### Meta
`rustc --version --verbose`:
```
rustc 1.76.0-nightly (2f8d81f9d 2023-11-21)
binary: rustc
commit-hash: 2f8d81f9dbac6b8df982199f69da04a4c8357227
commit-date: 2023-11-21
host: x86_64-unknown-freebsd
release: 1.76.0-nightly
LLVM version: 17.0.5
```

**Comment by the8472** [comment]
I'm assuming that the linux kernel on that target still uses pretty much the same signal structure as most other ones so this is probably a libc issue that it lacks those accessors.

**Comment by asomers** [comment]
Probably, but it's a problem in the libc that's bundled with std, not the standalone crate.  And since std itself doesn't compile, it's hard to bisect the standalone crate.

**Comment by the8472** [comment]
Bisecting shouldn't be needed, the uses in std were added in #117957.

**Comment by SteveLauC** [comment]
More context: `nightly-2023-11-19` should be the first version of toolchain that is affected

**Comment by jieyouxu** [comment]
Hi, since rust-lang/libc#3529 is merged, is this still an issue?

**Comment by asomers** [comment]
@jieyouxu that only fixes the problem in the libc crate.  libc is vendored within the standard library, so it's necessary to update the vendored version.

**Comment by operutka** [comment]
@jieyouxu it's been merged into `rust-lang/libc:main` but the latest `libc` release `0.2.153` still does not contain it.

**Comment by operutka** [comment]
I believe this issue has been fixed in libc v0.2.156.

**Comment by SteveLauC** [comment]
> Build failure for armv7-unknown-linux-uclibceabihf nix-rust/nix#2200

Let me give it a test on the NIx side.

**Comment by SteveLauC** [comment]
> jieyouxu

Yeah, tested on the Nix side, https://github.com/nix-rust/nix/pull/2487, I think this issue can be closed now.

**Comment by asomers** [comment]
Closing, since @SteveLauC confirmed it to be fixed.
