### ISSUE TITLE
[rustdoc] Add support for --output-format markdown

### ISSUE THREAD

**Issue by kellytk** [rust-lang/rust#118170]
I would like to peruse docs on systems lacking web browsers. Although possibly not quite as nice of an experience as HTML format, markdown format, or an other format optimized for browserless environments, would be sufficient.

**Comment by kellytk** [comment]
@GuillaumeGomez No, as the intended use is by human and not machine. A terminal-rendered markdown file, using tools such as https://github.com/charmbracelet/glow, is similar to a page in a book, whereas reading through JSON is comparatively noisy with syntax.

**Comment by GuillaumeGomez** [comment]
What I meant was that instead of rustdoc to add a new output format to maintain, maybe it was possible to use the JSON output format to generate something more useable for your use case?

**Comment by kellytk** [comment]
I suppose I could, however I think this functionality should come stock.

Every system in use for writing Rust _supports_ markdown for example, as it can be comfortably used directly and without rendering, yet not every system in use for writing Rust has a web browser installed.
