### ISSUE TITLE
ICE when doing `unpretty=stable-mir` (minimized test case)

### ISSUE THREAD

**Issue by the-shank** [rust-lang/rust#118176]
ICE when trying to emit stable-mir. 

The minimized test is just a simple cargo project with a single `lib.rs` file.:

```rust
// lib.rs
fn foo(){
    let mut c = vec![1,2,3];
}
```

Command used:

`RUST_BACKTRACE=full cargo rustc -- -Z unpretty=stable-mir`

Host Information:
- ArchLinux with latest updates
- Rust 1.76 nightly

The generated stacktrace file is attached.
[rustc-ice-2023-11-22T17_03_55-15620.txt](https://github.com/rust-lang/rust/files/13442565/rustc-ice-2023-11-22T17_03_55-15620.txt)

Please let me know if any other information is required.

**Comment by matthiaskrgr** [comment]
There are a bunch of `unimplemented!()`s  in the code since its still work in progress

**Comment by the-shank** [comment]
My bad. Am closing this, since this is already known.
