### ISSUE TITLE
rustdoc: How to render struct variants with no visible fields?

### ISSUE THREAD

**Issue by Kyuuhachi** [rust-lang/rust#118195]
While working on #118192, I noticed that struct variants with no (visible) fields look kinda awkward.
```rust
pub enum MyEnum {
	/// A variant with no fields
	A {},
	/// A variant with hidden fields
	B { #[doc(hidden)] a: u8 },
}
```

![rendering of the above code snippet](https://github.com/rust-lang/rust/assets/1547062/ba5679d5-bfff-4ff4-bd09-16f3a478a267)

The Fields heading takes a lot of space without adding particularly much to the content. The easiest solution would be to just remove the heading, but that would show no indication that there exist private fields. The same issue exists in top-level structs as well, but there it is mitigated by having the definition in the code block just above, while for enums there can be a sizeable distance between the two.

Any thoughts? Am I just overthinking the whole thing?

**Comment by GuillaumeGomez** [comment]
No this is a very good point. If there are no fields, we shouldn't add the "Fields" heading. Sending a fix.
