### ISSUE TITLE
rustc_middle: `ImmTy`'s `Display` implementation adds a weird-looking suffix to special floating point values.

### ISSUE THREAD

**Issue by eduardosm** [rust-lang/rust#118221]
When printing an `ImmTy` that contains an special floating point value such as infinity or NaN, it will add an `f32` or `f64` suffix, making it look like `Inff32` or `NaNf32`, which does not look very pretty.

First observed in https://github.com/rust-lang/miri/pull/3185#discussion_r1403735283.

**Comment by RalfJung** [comment]
This should probably be `Inf_f32` or so instead.

The code for that is here:
https://github.com/rust-lang/rust/blob/15f21562e627cb37e74d5e27f22eafc76cf4ec01/compiler/rustc_middle/src/ty/print/pretty.rs#L1479-L1484
