### ISSUE TITLE
Where is the source code of the `#[must_use]` attribute procedural macro?

### ISSUE THREAD

**Issue by jymchng** [rust-lang/rust#118254]
As titled, I have been searching it but wouldn't find it!

**Comment by fmease** [comment]
It's an *inert* attribute, there's no corresponding proc macro. It doesn't get expanded but just stays as-is allowing the compiler to handle items annotated with it specially.

**Comment by compiler-errors** [comment]
Yeah, it's built-in in the compiler. See [`compiler/rustc_lint/src/unused.rs`](https://github.com/rust-lang/rust/blob/master/compiler/rustc_lint/src/unused.rs) in the compiler.

If you have further questions, please feel free to open an issue on the [rust-lang zulip](https://github.com/rust-lang/rust/blob/master/compiler/rustc_lint/src/unused.rs).
