### ISSUE TITLE
C call Rust can not get arguments

### ISSUE THREAD

**Issue by Sword-Destiny** [rust-lang/rust#118355]
I have a C program call Rust program by function execve("./rust_test", argv, env).
When I read argv in Rust main function by std::env::args(),

I get this message:

```text
thread 'main' panicked at library/alloc/src/raw_vec.rs:534:5:
capacity overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

the target: cross compile aarch64-unknown-linux-gnu

**Comment by saethlin** [comment]
Perhaps we can treat this as a bug if you provide a way to reproduce the problem. Can you provide enough code to observe the problem?

**Comment by Sword-Destiny** [comment]
> Perhaps we can treat this as a bug if you provide a way to reproduce the problem. Can you provide enough code to observe the problem?

this error is caused by cross compile glibc and musl.
If compiled with aarch64-unknown-linux-gnu target and and Run on a musl-based embedded system, this panic will happen when call std::env::args().collect(). Most of the interfaces is compatible between musl and gllibc, the command line arguments is one of the incompatible.

**Comment by bjorn3** [comment]
If you link against musl, you have to use the aarch64-unknown-linux-musl target.

**Comment by Sword-Destiny** [comment]
> If you link against musl, you have to use the aarch64-unknown-linux-musl target.

I know this, but some problems here: #118400 , so I tried to use glibc, most of the programs work. I finally succeed to change to musl today.

**Comment by Sword-Destiny** [comment]
closed
