### ISSUE TITLE
Why option -C link-self-contained is not supported on this target aarch64-unknown-linux-gnu

### ISSUE THREAD

**Issue by Sword-Destiny** [rust-lang/rust#118354]
I want to cross compile, and I need to link my self startfiles/endfiles

**Comment by petrochenkov** [comment]
`-C link-self-contained` is only supported for targets that ship crt objects as a part of Rust distribution.
`aarch64-unknown-linux-gnu` doesn't ship those objects, it relies on C compiler finding them.

If you want to pass custom crt objects then passing `-nostartfiles` and the crt object paths to C compiler (used as linker) with `-C link-arg` should work.

**Comment by Sword-Destiny** [comment]
> `-C link-self-contained` is only supported for targets that ship crt objects as a part of Rust distribution. `aarch64-unknown-linux-gnu` doesn't ship those objects, it relies on C compiler finding them.
> 
> If you want to pass custom crt objects then passing `-nostartfiles` and the crt object paths to C compiler (used as linker) with `-C link-arg` should work.

OK
