### ISSUE TITLE
error: Unrecognized option: 'diagnostic-width' When trying cargo install in IntelliJ Terminal

### ISSUE THREAD

**Issue by Toasterson** [rust-lang/rust#118385]
I tried to install several binaries with cargo install while working from the Terminal Emulator in IntelliJ IDE(Java).

And I get the following error on every package on different steps.
```sh
error: Unrecognized option: 'diagnostic-width'

error: could not compile `atoi` (lib)
error: failed to compile `sea-orm-cli v0.12.6`
```

To install a crate I had to switch to Alacritty. 

Googleing the error reveals it is related to the Terminal emulation. It could be that the compiling PTY is leaking things into the finished binary and thus could cause strange errors.

### Meta
`rustc --version --verbose`:
```
rustc 1.74.0 (79e9716c9 2023-11-13)
```

**Comment by Aitem** [comment]
The same problem
stable-aarch64-unknown-linux-gnu  rustc 1.74.0 (79e9716c9 2023-11-13)

**Comment by saethlin** [comment]
@Aitem That doesn't look related.

@Toasterson What rustc version were you trying to install when you got that error? `--diagnostic-width` was only added in 1.64, which was a fair bit ago but recent enough that you may have had a default toolchain that doesn't support it.

**Comment by Toasterson** [comment]
> @Toasterson What rustc version were you trying to install when you got that error? `--diagnostic-width` was only added in 1.64, which was a fair bit ago but recent enough that you may have had a default toolchain that doesn't support it.

1.74 as I said it works with Alacritty but breaks inside Jetbrains IDE. From the sources I can summize that the Jetbrains IDE terminal does not expose certain properties the functions associated to diagnostic-width try to read from the Terminal/PTY

**Comment by Aitem** [comment]
@Toasterson Can you run `cargo build --verbose` from IntelliJ Terminal ?

**Comment by tomeronen** [comment]
Hello, getting the same error after updating rustc 
`rustc 1.75.0 (82e1608df 2023-12-21)`

```
error: Unrecognized option: 'diagnostic-width'
error: could not compile `atoi` (lib)
```

Running through mac m1 terminal.

Did somebody also had this error and was able to solve it?

**Comment by Toasterson** [comment]
Can you try the same Command in iTerm2 or Alacritty? I think it's the terminal emulator.

**Comment by tomeronen** [comment]
Getting the same error both in iTerm2 and Alacritty 😵‍💫

**Comment by tomeronen** [comment]
Update: uninstalled rust, and then installed it again through brew. And then all was good in the world. Still not sure what caused this.

**Comment by darosior** [comment]
I've hit this error on version 1.75.0. Upgrading to 1.77.2 didn't solve it. Simply setting `RUSTUP_TOOLCHAIN=stable` did, for some reason.
