### ISSUE TITLE
Confusing when using an undefined variable in keyword 'match'

### ISSUE THREAD

**Issue by OrzOvo** [rust-lang/rust#118357]
### Code

```Rust
use tracing::{info};

fn main() {
    tracing_subscriber::fmt()
        .with_file(false)
        .with_target(false)
        .with_thread_ids(true)
        .with_thread_names(true)
        .compact()
        .init();

    println!("Hello, world!");
    let index = 1;
    match index {
        AAAA => {
            info!("why");
        },
        _ => {
            info!("what!");
        }
    }
```

### Current output

```Shell
Hello, world!
2023-11-27T07:55:03.469636Z  INFO main ThreadId(01) why
```

### Desired output

```Shell
the 'AAAA' is not a declared variable.I think the compiler would tell me the error, but it work will, It does confuse me really.
```

### Anything else?

cargo 1.70.0 (ec8a8a0ca 2023-04-25)

**Comment by Urgau** [comment]
`AAAA` is a new variable, not one from the context.

In your example there are two warnings that help you detect such mistakes:
```text
warning: unreachable pattern
  --> src/main.rs:25:9
   |
22 |         AAAA => {
   |         ---- matches any value
...
25 |         _ => {
   |         ^ unreachable pattern
   |
   = note: `#[warn(unreachable_patterns)]` on by default

warning: unused variable: `AAAA`
  --> src/main.rs:22:9
   |
22 |         AAAA => {
   |         ^^^^ help: if this is intentional, prefix it with an underscore: `_AAAA`
   |
   = note: `#[warn(unused_variables)]` on by default
```

**Comment by OrzOvo** [comment]
> `AAAA` is a new variable, not one from the context.
> 
> In your example there are two warnings that help you detect such mistakes:
> 
> ```
> warning: unreachable pattern
>   --> src/main.rs:25:9
>    |
> 22 |         AAAA => {
>    |         ---- matches any value
> ...
> 25 |         _ => {
>    |         ^ unreachable pattern
>    |
>    = note: `#[warn(unreachable_patterns)]` on by default
> 
> warning: unused variable: `AAAA`
>   --> src/main.rs:22:9
>    |
> 22 |         AAAA => {
>    |         ^^^^ help: if this is intentional, prefix it with an underscore: `_AAAA`
>    |
>    = note: `#[warn(unused_variables)]` on by default
> ```

What is your Cargo version? Maybe my Cargo version too old so it can not give me any suggestion.
