### ISSUE TITLE
`x86_64-pc-windows-msvc` float `trunc` NaN edge case only in debug builds

### ISSUE THREAD

**Issue by WilliamVenner** [rust-lang/rust#118388]
```rust
fn main() {
    println!("{}", f32::from_bits(-6291456_i32 as u32).trunc().to_bits() as i32);
    println!("{}", f64::from_bits(-4503599625273344_i64 as u64).trunc().to_bits() as i64);
}
```

On all the platforms I tried, including `i686-pc-windows-msvc`, in debug builds and release builds, the above code prints `-2097152 -2251799811588096`, but on `x86_64-pc-windows-msvc` debug builds specifically, it prints `-6291456 -4503599625273344`

### Meta

`rustc --version --verbose`
```
rustc 1.74.0 (79e9716c9 2023-11-13)
binary: rustc
commit-hash: 79e9716c980570bfd1f666e3b16ac583f0168962
commit-date: 2023-11-13
host: x86_64-pc-windows-msvc
release: 1.74.0
LLVM version: 17.0.4
```

**Comment by Jules-Bertholet** [comment]
Rust (and LLVM) do not guarantee that floating-point operations will give a particular NaN representation. See https://github.com/RalfJung/rfcs/blob/float-semantics/text/0000-float-semantics.md#reference-level-explanation, https://llvm.org/docs/LangRef.html#behavior-of-floating-point-nan-values

@rustbot label -C-bug C-discussion A-floating-point

**Comment by workingjubilee** [comment]
Working as intended.
