### ISSUE TITLE
Tracking Issue for XXX

### ISSUE THREAD

**Issue by Playmore00** [rust-lang/rust#118440]
Feature gate: `#![feature(...)]`

This is a tracking issue for ...

### Public API

```rust
// core::magic

pub struct Magic;

impl Magic {
    pub fn magic(self);
}
```

### Steps / History

- [x] Implementation: #...
- [x] Final comment period (FCP)[^1]
- [x] Stabilization PR

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by clubby789** [comment]
Was this opened by mistake?
