### ISSUE TITLE
aarch64-unknown-linux-musl use -lunwind, but my embedded system has no unwind

### ISSUE THREAD

**Issue by Sword-Destiny** [rust-lang/rust#118400]
I got error when cross compile aarch64-unknown-linux-musl target。

```text
          ld.lld: error: unable to find library -lunwind
          clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
```

my embedded system have no unwind lib

**Comment by Sword-Destiny** [comment]
I set panic = "abort" in Cargo.toml, why still -lunwind exists?

**Comment by Sword-Destiny** [comment]
the aarch64-unknown-linux-musl target use crt-static=true as default.
to avoid this error, We can add -Ctarget-feature=-crt-static in rustflags

**Comment by Ragnt** [comment]
This is still a problem. You currently cannot build static libraries for musl targets unless you have a custom toolchain that includes libunwind.
