### ISSUE TITLE
Every iteration will accidently break a non-related static mut variable on embedded device

### ISSUE THREAD

**Issue by Eplankton** [rust-lang/rust#118407]
I have a static mut variable call `READY_LIST`, and if I write any `for x in XXX` in my code, the `READY_LIST` will be changed, whatever `XXX` is `for i in 0..100` or `for page in PAGE_POOL`.
```
pub const PAGE_SIZE: usize = 128;
pub const MAX_TASKS: usize = 2;

#[repr(C)]
#[derive(Clone, Copy)]
pub struct Page {
    raw: [u32; PAGE_SIZE],
    used: bool,
}

mod KernelGlobal {
    use super::{Page, MAX_TASKS, PAGE_SIZE};

    pub static mut PAGE_POOL: [Page; MAX_TASKS] = [Page {
        raw: [0; PAGE_SIZE],
        used: false,
    }; MAX_TASKS];
}

use KernelGlobal::PAGE_POOL;

impl Page {
    pub fn alloc(lk: &LinkedList) -> *mut Page {
        let pl = unsafe { &mut PAGE_POOL }; // I tried to watch how it can be changed even if it's not accessible

        for i in 0..MAX_TASKS { // Crash the READY_LIST
            let page = &mut pl[i];
            if !page.used {
                (*page).used = true;
                return page;
            }
        }
        core::ptr::null_mut()

        // for p in unsafe { &mut PAGE_POOL } {
        //     if !p.used {
        //         p.used = true;
        //         return p;
        //     }
        // }
        // core::ptr::null_mut()

        // unsafe {
        //     return &mut PAGE_POOL[0] as *mut Page;
        // }
    }
}

#[repr(C)]
pub struct Node {
    prev: *mut Node,
    next: *mut Node,
}

impl Node {
    fn new() -> Node {
        let mut node = Node {
            prev: core::ptr::null_mut(),
            next: core::ptr::null_mut(),
        };
        node.prev = &mut node;
        node.next = &mut node;
        node
    }
}

#[repr(C)]
pub struct LinkedList {
    head: Node,
    cnt: usize,
}

impl LinkedList {
    pub fn new() -> Self {
        Self {
            head: Node::new(),
            cnt: 0,
        }
    }

    pub fn init(&mut self) -> &mut Self {
        *self = Self::new();
        &mut (*self)
    }

    pub fn insert(&mut self, node: *mut Node, pos: *mut Node) {
        unsafe {
            (*node).next = pos;
            (*node).prev = (*pos).prev;
            (*(*pos).prev).next = node;
            (*pos).prev = node;
            self.cnt += 1;
        }
    }

    pub fn add(&mut self, node: *mut Node) {
        let pos = &mut self.head as *mut Node;
        self.insert(node, pos);
    }
}

#[repr(C)]
pub struct Tcb {
    pub node: Node,
    pub pgptr: *mut Page,
}

impl Tcb {
    pub fn new() -> Self {
        Self {
            pgptr: core::ptr::null_mut(),
            node: Node::new(),
        }
    }

    pub fn set_pg(&mut self, ptr: *mut Page) {
        self.pgptr = ptr;
    }

    pub fn set_xPSR(&mut self, val: u32) {
        if !self.pgptr.is_null() {
            unsafe {
                (*self.pgptr).raw[PAGE_SIZE - 1] = val;
            }
        } else {
            panic!();
        }
    }
}

pub static mut READY_LIST: LinkedList = LinkedList {
    head: Node {
        prev: core::ptr::null_mut(),
        next: core::ptr::null_mut(),
    },
    cnt: 0,
};

pub mod Scheduler {
    use super::READY_LIST;

    pub fn ready_list() -> &'static mut super::LinkedList {
        unsafe { &mut READY_LIST }
    }
}

```

**Comment by clubby789** [comment]
Can you provide a minimal runnable example that demonstrates the issue?
I can see some potential issues here:
```rs
    fn new() -> Node {
        let mut node = Node {
            prev: core::ptr::null_mut(),
            next: core::ptr::null_mut(),
        };
        node.prev = &mut node;
        node.next = &mut node;
        node
    }
```
This sets `node` to point at itself, but once the function returns `node` will have moved so the pointers will be dangling.
```rs
    pub fn ready_list() -> &'static mut super::LinkedList {
        unsafe { &mut READY_LIST }
    }
```
This function allows taking multiple `&mut` references simultaneously to the same location which is UB.

**Comment by Eplankton** [comment]
> Can you provide a minimal runnable example that demonstrates the issue? I can see some potential issues here:
> 
> ```rust
> fn new() -> Node {
>   let mut node = Node {
>     prev: core::ptr::null_mut(),
>     next: core::ptr::null_mut(),
>   };
>   node.prev = &mut node;
>   node.next = &mut node;
>   node
> }
> ```
> 
> This sets `node` to point at itself, but once the function returns `node` will have moved so the pointers will be dangling.
> 
> ```rust
> pub fn ready_list() -> &'static mut super::LinkedList {
>   unsafe { &mut READY_LIST }
> }
> ```
> 
> This function allows taking multiple `&mut` references simultaneously to the same location which is UB.

I found how thing's broken: the width of pointer makes no sense on target=armv7, under that platform it should be as 32-bit width, however when I try ` let size = core::mem::size_of::<*mut i32>();`, I got a size = 8  bytes = 64-bit
![屏幕截图(156)](https://github.com/rust-lang/rust/assets/86543401/492c505b-4d9a-4973-9bbd-c97fdea3c20b)

**Comment by Eplankton** [comment]
> > Can you provide a minimal runnable example that demonstrates the issue? I can see some potential issues here:
> > ```rust
> > fn new() -> Node {
> >   let mut node = Node {
> >     prev: core::ptr::null_mut(),
> >     next: core::ptr::null_mut(),
> >   };
> >   node.prev = &mut node;
> >   node.next = &mut node;
> >   node
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This sets `node` to point at itself, but once the function returns `node` will have moved so the pointers will be dangling.
> > ```rust
> > pub fn ready_list() -> &'static mut super::LinkedList {
> >   unsafe { &mut READY_LIST }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This function allows taking multiple `&mut` references simultaneously to the same location which is UB.
> 
> I found how thing's broken: the width of pointer makes no sense on target=armv7, under that platform it should be as 32-bit width, however when I try ` let size = core::mem::size_of::<*mut i32>();`, I got a size = 8 bytes = 64-bit ![屏幕截图(156)](https://private-user-images.githubusercontent.com/86543401/286569058-492c505b-4d9a-4973-9bbd-c97fdea3c20b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNTU3ODUsIm5iZiI6MTcwMTI1NTQ4NSwicGF0aCI6Ii84NjU0MzQwMS8yODY1NjkwNTgtNDkyYzUwNWItNGQ5YS00OTczLTliYmQtYzk3ZmRlYTNjMjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDEwNTgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMzkxYjU1MzY4NDFmMzEyMjNjNTU0NWIzOGMyYTNmMWIwMTc4YjdkNjAxNjk1MWVmZmU2ZWEyMWYzZWRlN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NH89Kg8MIHLAqjVS7-VlOnKopH4IZsGuy_8C7SntdJI)

And also for `usize`:
![屏幕截图(156)](https://github.com/rust-lang/rust/assets/86543401/75732c17-e181-4b31-92da-2214e8dd64af)

**Comment by clubby789** [comment]
That size hint is likely from the architecture of your own machine the editor is running in rather than your intended target

**Comment by workingjubilee** [comment]
Please report rust-analyzer bugs to the rust-analyzer repo.

Otherwise, as discussed, your code is unsound, unfortunately. I recommend using [miri](https://github.com/rust-lang/miri) to help you evaluate `unsafe` code. It cannot detect all errors but it detects many common ones.

In the absence of a clear issue, I am closing this.
