### ISSUE TITLE
Perf regression with rustc at f562931 (nightly-2023-10-13)

### ISSUE THREAD

**Issue by cloneable** [rust-lang/rust#118451]
Today I noticed that when running the rust benchmark in [github.com/jinyus/related_post_gen](https://github.com/jinyus/related_post_gen/tree/main/rust) with latest nightly it showed a regression from 11.5ms to 13.3ms compared to stable and beta. `cargo bisect-rustc` pointed me to `nightly-2023-10-13` and to commit f562931 in particular. (No slowdown in parent commit 9d1e4b7.)

That commit looks harmless, so I assume something else in the toolchain changed or the way rustc is built maybe?

**Comment by cloneable** [comment]
I diff'ed objdumps (headers + disasm) and couldn't find anything. No different or extra instruction. File sizes are the same. Must be some alignment issue again. It's just very strange that it happens consistently from nightly-2023-01-13 on and consistently not before.

Feel free to close this, if you feel it's not worth investigating further.

**Comment by saethlin** [comment]
I fiddled with this a bunch and sometimes when I compile the program I get a binary that's a bit slower. I agree that this looks like an alignment issue. One would think this is reproducible from build to build but it doesn't seem to be. I've gotten toolchains before and after that commit to produce the regression from 11 to 13 ms.

**Comment by cloneable** [comment]
Thanks for checking!

> I've gotten toolchains before and after that commit to produce the regression from 11 to 13 ms.

Sorry, you're saying that you see both numbers before and after nightly-2023-10-13? I'm sorry I should have tried more builds then. To me it was consistent, but could have been coincidence.

**Comment by saethlin** [comment]
Yeah, I saw the faster and slower version before and after 2023-10-13. I was running the binaries a hundred times, and each binary always seemed consistent. But sometimes when I would `cargo clean && cargo build --release` I'd end up with a new binary that was slower.

**Comment by cloneable** [comment]
You're right. There are plenty of builds after 10-13 producing 11ms binaries. However, I cannot reproduce it between clean+build when using the same build. It's either always 11ms or 13ms. I even tried removing and reinstalling the toolchains. No effect. Do you happen to remember which build yielded binaries with both numbers and how often they varied?

I tested 2023-10-10..=2023-10-20, each with clean+build several times.

10,11,12,14,16,18,19: consistently good (11ms)
13,15,17,20: consistently bad (13ms)

If you have a bit more time for this, could you check if you can confirm (some of) these?

**Comment by cloneable** [comment]
When moving the `println!` to the end `main` all listed builds produce binaries with 11ms.

**Comment by cloneable** [comment]
I think this can be closed, though there's still some weirdness going on. rustc or llvm should not cause such a or any regression from moving an independent statement. :shrug:
