### ISSUE TITLE
Missing stability badge for some methods in rustdoc

### ISSUE THREAD

**Issue by Kobzol** [rust-lang/rust#118439]
Some functions in the documentation generated by `rustdoc` (e.g. [this one](https://doc.rust-lang.org/std/pin/struct.Pin.html#method.new)) are missing the stability badge. For this method, it should show `1.33.0`.

**Comment by GuillaumeGomez** [comment]
This is something done on purpose as you can see [here](https://github.com/rust-lang/rust/blob/e9b7bf011478aa8c19ac49afc99853a66ba04319/src/librustdoc/html/render/mod.rs#L949-L955). It was implemented in https://github.com/rust-lang/rust/pull/30686.

I'll send a draft to change this so we can discuss there whether or not we want this change.
