### ISSUE TITLE
We need fs::realpath

### ISSUE THREAD

**Issue by kballard** [rust-lang/rust#11857]
After an aborted attempt at implementing this directly (#11734), we need to investigate how to provide `fs::realpath()` correctly.

The current thinking is that for libgreen, we should defer to libuv. For libnative, on POSIX, we should use `realpath()`. On Windows, I don't know, but we should avoid writing this ourselves at all costs because there's a *lot* of complexity involved.

**Comment by aturon** [comment]
Note for posterity: look at `GetFullPathNameW` on Windows for drive-relative CWD.

**Comment by alexcrichton** [comment]
Closing in favor of https://github.com/rust-lang/rfcs/issues/939

**Comment by pornel** [comment]
For those landing from Google here:

## [realpath has been added as `fs::canonicalize`](https://doc.rust-lang.org/std/fs/fn.canonicalize.html)
