### ISSUE TITLE
Weird behaviour for borrow checker rules with type_id()

### ISSUE THREAD

**Issue by Norlock** [rust-lang/rust#118503]
I don't know if this is a bug or a feature, maybe someone with more knowledge can explain. But getting type_id() on an object will force the 'static rule but inside a function it will just work. For example this won't work:

```rust
impl WidgetBuilder for Editor {
    fn draw_widget(&mut self, anim: &mut Box<dyn ParticleAnimation>, ui: &mut Ui) {
        let type_id = anim.as_any().type_id();
       // Borrow checker will complain here about 'static lifetime for anim being borrowed already
        if let Some(widget) = self.pa_widgets.get_mut(&type_id) {
            widget(&mut self.data, anim, ui);
        } else {
            println!("widget not found");
        }
    }
}
```

But this will work:

```rust
impl WidgetBuilder for Editor {
    fn draw_widget(&mut self, anim: &mut Box<dyn ParticleAnimation>, ui: &mut Ui) {
        let type_id = get_type_id(anim.as_any());
        if let Some(widget) = self.pa_widgets.get_mut(&type_id) {
            widget(&mut self.data, anim, ui);
        } else {
            println!("widget not found");
        }
    }
}

/// Weird trick to avoid the borrow checker nonsense
fn get_type_id<T: ?Sized + Any>(s: &T) -> TypeId {
    s.type_id()
}
```
So why can't either type_id() not be constrained to 'static, or have the borrow checker complain when it's used as a function. If this is working as designed this issue can be closed. Check out code to reproduce : https://github.com/Norlock/sparticles/blob/7b61ee47efd09c82224d30bad12ea1849da93ac5/crates/sparticles_editor/src/lib.rs

Compiler messages for the first version of the code:
```shell
error[E0521]: borrowed data escapes outside of method
  --> crates/sparticles_editor/src/lib.rs:98:23
   |
96 |     fn draw_widget(&mut self, anim: &mut Box<dyn ParticleAnimation>, ui: &mut Ui) {
   |                               ----  - let's call the lifetime of this reference `'1`
   |                               |
   |                               `anim` declared here, outside of the method body
   |                               `anim` is a reference that is only valid in the method body
97 |         //let type_id = get_type_id(anim.as_any());
98 |         let type_id = anim.as_any().type_id();
   |                       ^^^^^^^^^^^^^
   |                       |
   |                       `anim` escapes the method body here
   |                       argument requires that `'1` must outlive `'static`

error[E0499]: cannot borrow `*anim` as mutable more than once at a time
   --> crates/sparticles_editor/src/lib.rs:101:36
    |
98  |         let type_id = anim.as_any().type_id();
    |                       -------------
    |                       |
    |                       first mutable borrow occurs here
    |                       argument requires that `**anim` is borrowed for `'static`
...
101 |             widget(&mut self.data, anim, ui);
    |                                    ^^^^ second mutable borrow occurs here
   ```

**Comment by lukas-code** [comment]
reduced example:

```rust
use std::any::Any;

fn check(x: &mut dyn Any) {
    let _ = x.type_id();
}
```

```text
error[E0521]: borrowed data escapes outside of function
 --> src/lib.rs:4:13
  |
3 | fn check(x: &mut dyn Any) {
  |          -  - let's call the lifetime of this reference `'1`
  |          |
  |          `x` declared here, outside of the function body
  |          `x` is a reference that is only valid in the function body
4 |     let _ = x.type_id();
  |             ^^^^^^^^^^^
  |             |
  |             `x` escapes the function body here
  |             argument requires that `'1` must outlive `'static`
```

When resolving a method call like `x.type_id()`, Rust will always try borrowing the receiver (i.e. `(&x).type_id()`) before dereferencing it (i.e. `(&*x).type_id()`). Quoting the [relevant part of the reference](https://doc.rust-lang.org/nightly/reference/expressions/method-call-expr.html):

> The first step is to build a list of candidate receiver types. Obtain these by repeatedly dereferencing the receiver expression's type, adding each type encountered to the list [...]. Then, for each candidate `T`, add `&T` and `&mut T` to the list immediately after `T`.

So in this case the list of candidates is
1. `<&'1 mut dyn Any as Any>::type_id(x)`
2. `<&'1 mut dyn Any as Any>::type_id(&x)`
3. `<&'1 mut dyn Any as Any>::type_id(&mut x)`
4. `<dyn Any as Any>::type_id(*x)`
5. `<dyn Any as Any>::type_id(&*x)`
6. `<dyn Any as Any>::type_id(&mut *x)`

The one that you want is 5, but since 2 is also a valid function call (modulo lifetimes) that one is selected, making the above example equivalent to this:

```rust
use std::any::Any;

fn check(x: &mut dyn Any) {
    // tries to return the type id of the type `&mut dyn Any` itself
    let _ = <&mut dyn Any as Any>::type_id(&x);
}
```

This will then fail borrow check, because `&'1 mut dyn Any` only implements `Any` for `'1 == 'static`.

Your workaround works by forcing a conversion from `&mut dyn Any` to `&dyn Any` before calling `.type_id()`. To do this without an extra function, you can insert a manual dereference:

```rust
let type_id = (*anim.as_any()).type_id();
```

**Comment by Norlock** [comment]
Ok thanks for the explanation + fix, interesting to know why it goes wrong. 

So can't the compiler automatically sugar this to always point to the actual type instead to dyn Any? Or are there use cases where I would like to know the type of that? 

I'll close this issue for now.

**Comment by lukas-code** [comment]
> So can't the compiler automatically sugar this to always point to the actual type instead to dyn Any? Or are there use cases where I would like to know the type of that?

Theoretically it would be possible to change the the method call semantics to prefer `(&*x).type_id()` over `(&x).type_id()` if the type of `x` is exactly `&mut dyn Any`. However that would
* be a breaking change: Fixing the the borrow error makes this compile on stable and adding such a special case would change semantics:
  ```rust
  use std::any::{Any, TypeId};
  
  fn check(x: &'static mut dyn Any) {
      assert_eq!(x.type_id(), TypeId::of::<&mut dyn Any>());
  }
  
  fn main() {
      check(&mut [] as &mut [(); 0]);
  }
  ```
* add inconsistencies to the language where Rust programmer now have to remember for which types what method call semantics apply. For example the the meaning of the following program would change if you manually substitute `T` for some special types:
  ```rust
  use std::any::{Any, TypeId};
  
  fn check<T: 'static>(x: T) -> TypeId {
      x.type_id()
  }
  ```

---

If you still want to propose a change to the language for this, the place to start a discussion would be either the [internals forum](https://internals.rust-lang.org/) or the [zulip chat](https://rust-lang.zulipchat.com/).
