### ISSUE TITLE
Suggestion to make a binding mutable could lead beginners astray

### ISSUE THREAD

**Issue by Nadrieril** [rust-lang/rust#118596]
### Code

```Rust
fn main() {
    let y = Some(0);
    if let Some(x) = y {
        x = 2;
    }
}
```

### Current output

```Shell
error[E0384]: cannot assign twice to immutable variable `x`
 --> src/main.rs:4:9
  |
3 |     if let Some(x) = y {
  |                 -
  |                 |
  |                 first assignment to `x`
  |                 help: consider making this binding mutable: `mut x`
4 |         x = 2;
  |         ^^^^^ cannot assign twice to immutable variable
```

### Desired output

```Shell
error[E0384]: cannot assign twice to immutable variable `x`
 --> src/main.rs:4:9
  |
3 |     if let Some(x) = y {
  |                 -
  |                 |
  |                 first assignment to `x`
  |                 help: consider making this binding mutable: `mut x`
  |                 help: to modify the original value, take a borrow instead: `ref mut x`
4 |         x = 2;
  |         ^^^^^ cannot assign twice to immutable variable
```

### Rationale and extra context

In the original code, it's unclear whether the intention is to modify the contents of `y` or only the copy contained in `x`. The suggestion assumes the second case, which gives:
```rust
fn main() {
    let y = Some(0);
    if let Some(mut x) = y {
        x = 2;
    }
}
```
This doesn't modify `y` yet compiles fine, which I expect could be surprising to a beginner. This meaning of `mut` is far from obvious. With the updated error message, subsequent errors guide the user to actually modifying `y`.

**Comment by eggyal** [comment]
Given that `y` was not declared `mut`, the suggestion to use `ref mut x` *alone* won't be sufficient here.  Perhaps the mutability of `y`'s binding should be considered and/or mentioned in the diagnostic.
