### ISSUE TITLE
Overflow in rustc - ops/arith.rs:346:1

### ISSUE THREAD

**Issue by jakobnissen** [rust-lang/rust#118672]
I encountered what looks to me like an internal error in `rustc` while doing Advent of Code in Rust. I used no unsafe code.

The error message is:
```
thread 'main' panicked at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/arith.rs:346:1:
attempt to multiply with overflow
```

To reproduce:
* Use this commit: https://github.com/jakobnissen/advent2023/commit/9ed8f0d820a85b27eccfb63f232dc5d3e9002133
* Get an input for day3 and store the file as `data/day03.txt`. Unfortunately, I believe AoC puzzle inputs cannot be shared legally (I might be wrong).
* Run in debug mode: `cargo run solve data 3`

The error with full stack trace I get is attached as a file.
[backtrace.txt](https://github.com/rust-lang/rust/files/13581711/backtrace.txt)

This is on the following version of Rust:
```
rustc 1.74.0 (79e9716c9 2023-11-13)
binary: rustc
commit-hash: 79e9716c980570bfd1f666e3b16ac583f0168962
commit-date: 2023-11-13
host: x86_64-unknown-linux-gnu
release: 1.74.0
LLVM version: 17.0.4
```

**Comment by the8472** [comment]
This does not look like a compiler error. It would normally print something like "error: internal compiler error: " if that were the case.

What you're seeing is the standard library catching a likely bug in your code, an [arithmetic overflow](https://en.wikipedia.org/wiki/Integer_overflow) when performing a multiplication in

```rust
            if is_star && star_neighbors.len() == 2 {
                p2 += star_neighbors.iter().fold(1, |acc, (n, _)| acc * n);
            }
```

**Comment by jakobnissen** [comment]
Dear @the8472

Is it expected that this error occurs when compiling the code, not when running it? And that the error does not point to my code, but rustc?

**Comment by the8472** [comment]
`cargo run` also executes your code, it does not merely compile it. To  build without running you want `cargo build`

**Comment by jakobnissen** [comment]
Right, my original post was imprecise. The issue also occurs when running cargo build (but not cargo build in release mode)

**Comment by jakobnissen** [comment]
Ah, now I can't reproduce it crashing when running only `cargo build`. I must have looked at the output from the wrong command before - indeed, it only exits when _running_ the code, not when compiling it.
Sorry for the noise, and thanks for the help!
