### ISSUE TITLE
Don't bias README.md towards distros

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#118627]
### Location

README.md

### Summary

Currently, the top-level readme looks something like this:

````
# THE RUST PROGRAMMING LANGUAGE

blah blah boilerplate

this readme is for users, not contributors

TABLE OF CONTENTS

read this if you are a user

HERE ARE 500 LINES ABOUT HOW DISTROS SHOULD COMPLE RUSTC FROM SRC
IT GOES ON FOR A LONG TIME
IT HAS CODE SNIPPETS AND EVERYTHING
```
./configure
```
LOOK AREN'T THESE CODE SNIPPETS SO INVITING
```
make
```

blah blah licensing
````

This makes it really easy for someone to quickly look at the readme, see that it suggests `./configure`, and run that locally. Unfortunately, that will be the wrong thing to do for 99% of contributors, because configure sets `profile = "dist"` at the top. Additionally, it's not really serving *actual* users of rust, who almost certainly don't want to compile from source (they either want to install from rustup or from their distro).

I suggest moving the vast majority of the README into a separate file, perhaps called `INSTALLING_FROM_SOURCE.md`, and making the top-level README only contain the sections preceding "Installing from source" and following "Notes". That should make it a lot more clear that it's not intended for either users or devs.

@rustbot label +E-easy +E-help-wanted

**Comment by crlf0710** [comment]
I submitted a PR to move the contents to forge. After it's merged and deployed maybe we could just link to that.

**Comment by jyn514** [comment]
hmm, ok. I worry that it will get out of date there since it won't show up with ripgrep, but it seems better than having it front and center and the readme.
