### ISSUE TITLE
rustc cannot infer Send for async block consistently with drop and braces

### ISSUE THREAD

**Issue by JakkuSakura** [rust-lang/rust#118604]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=513e1f5382511313a9a7e38a26f7d29f

I tried this code:

```rust
use std::sync::Mutex;
use std::time::Duration;

fn async_function_drop() {
    let lock = Mutex::new(vec![0]);
    tokio::spawn(async move {
        let mut guard = lock.lock().unwrap();
        guard.push(1);
        drop(guard);
        tokio::time::sleep(Duration::from_millis(100)).await;
    });
}
fn async_function_braces() {
    let lock = Mutex::new(vec![0]);
    tokio::spawn(async move {
        {
            let mut guard = lock.lock().unwrap();
            guard.push(1);
        }
        tokio::time::sleep(Duration::from_millis(100)).await;
    });
}
fn sync_function_drop() {
    let mut lock = Mutex::new(vec![0]);

    let mut guard = lock.lock().unwrap();
    guard.push(1);
    drop(guard);
    &mut lock;
}

fn sync_function_braces() {
    let mut lock = Mutex::new(vec![0]);
    {
        let mut guard = lock.lock().unwrap();
        guard.push(1);
    }
    &mut lock;
}

```

I expected to see this happen: all four functions compile

Instead, this happened: the first function gives an error, complaining: future cannot be sent between threads safely

Why I see it as an internal bug:
In sync code, `drop` has the effect of limiting the variable scope as braces(is it?)
But in async code, drop and braces are different. It might be a flaw in future analyser about Send, or is it intended to be different?

### Meta

`rustc --version --verbose`:
```
rustc 1.75.0-nightly (bf9a1c8a1 2023-10-08)
binary: rustc
commit-hash: bf9a1c8a193fc373897196321215794c8bebbeec
commit-date: 2023-10-08
host: aarch64-apple-darwin
release: 1.75.0-nightly
LLVM version: 17.0.2

```

**Comment by traviscross** [comment]
@rustbot labels +AsyncAwait-Triaged +WG-async

We reviewed this today in WG-async triage.

We believe this is identical to issue #116680, so let's track this there.
