### ISSUE TITLE
Data returned by  ``std::simd::Mask::to_array()`` differs from the one displayed by its Debug implementation

### ISSUE THREAD

**Issue by Quentindeve** [rust-lang/rust#118896]
# Problem

While using the ``portable-simd`` API from the Nightly channel (using ``#![feature(portable_simd)]``), I encountered a weird behavior which looks like a bug to me with this code:

```rust
#![feature(portable_simd)]

use std::simd::{Simd, Mask};

fn main() {
    let buff_a = b"Hello Wo";
    let buff_b = b"HellaLal";
    let buff_a: &[i8; 8] = unsafe { std::mem::transmute(buff_a) };
    let buff_b: &[i8; 8] = unsafe { std::mem::transmute(buff_b) };

    let a_vector = Simd::<_, 8>::from_slice(buff_a);
    let b_vector = Simd::<_, 8>::from_slice(buff_b);
    let mask = unsafe { !Mask::from_int_unchecked(a_vector ^ b_vector) };
    
    println!("{:?}", mask);
    println!("{:?}", mask.to_array());
}
```

# ``rustc --version`` output
rustc 1.76.0-nightly (21cce21d8 2023-12-11)

# Expected behavior
the ``Debug`` implementation of ``simd::Mask`` should give the same value as ``simd::Mask::to_array()``.

# Solution
Make the ``Debug`` implementation behave like ``Mask::to_array`` or make a new function inside the ``Mask`` implementation to return the same value as the ``Debug`` implementation. I understand the behavior of ``Mask::to_array()`` is useful for many use cases but the other behavior is interesting too.

**Comment by workingjubilee** [comment]
Your program is UB: the integers input into `Mask::from_int_unchecked` are not all 0 or -1. This is why there is a difference.

**Comment by RalfJung** [comment]
Specifically this is documented [here](https://doc.rust-lang.org/nightly/std/simd/prelude/struct.Mask.html#method.from_int_unchecked).
