### ISSUE TITLE
linking with C library changes the behavior of _Float16

### ISSUE THREAD

**Issue by usamoi** [rust-lang/rust#118813]
I tried this code:

```toml
[build-dependencies]
cc = "1.0.83"
```

```rust
// /build.rs
fn main() {
    cc::Build::new()
        .compiler("/usr/bin/clang-16")
        .file("./src/abc.c")
        .opt_level(0)
        .compile("abc");
}
```

```c
// /src/abc.c
float test() {
  _Float16 y = 114;
  float z = y;
  return z;
}
```

```rust
// /src/main.rs
extern "C" {
    fn test() -> f32;
}

fn main() {
    println!("{}", unsafe { test() });
}
```

I expected to see this happen: It prints `114`.

Instead, this happened: It prints an unknown value, `0.00017929077`, `-0.045898438` or other.

After debugging, I found both `compiler_builtins` and `libgcc` provide the symbol `__extendhfsf2`. `__extendhfsf2` is a `compiler-rt` intrinsics for casting a `_Float16` to `float`. In `compiler_builtins`, the only argument of `__extendhfsf2` is passed in a general-proposed register, However, in `libgcc`, the only argument of `__extendhfsf2` is passed in `xmm`.

related: https://github.com/llvm/llvm-project/issues/56854

### Meta

`rustc --version --verbose`:
```
rustc 1.74.1 (a28077b28 2023-12-04)
binary: rustc
commit-hash: a28077b28a02b92985b3a3faecf92813155f1ea1
commit-date: 2023-12-04
host: x86_64-unknown-linux-gnu
release: 1.74.1
LLVM version: 17.0.4
```

**Comment by Nilstrieb** [comment]
cc @Amanieu for compiler builtins shenanigans

**Comment by nikic** [comment]
We probably need to se `COMPILER_RT_HAS_FLOAT16` during our compiler-rt build.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23118813.20linking.20with.20C.20library.20changes.20the.20behavior.20of.20_Flo.E2.80.A6)).

@rustbot label -I-prioritize +P-high

**Comment by Amanieu** [comment]
> We probably need to se `COMPILER_RT_HAS_FLOAT16` during our compiler-rt build.

Yes, I think that would solve the problem. Is `_Float16` supported by Clang on all targets? Or do we need some sort of per-target allowlist?

**Comment by sagudev** [comment]
> Is `_Float16` supported by Clang on all targets? Or do we need some sort of per-target allowlist?

I looks like it's not available on all targets: https://clang.llvm.org/docs/LanguageExtensions.html#half-precision-floating-point

**Comment by tgross35** [comment]
@beetrees put up https://github.com/rust-lang/compiler-builtins/pull/593 which uses our nightly `f16` type to provide the extend/trunc symbols and should fix this. Need to double check the edge cases because the ABI (integer or float) is apparently dependent on whether SSE2 is available.

**Comment by Veykril** [comment]
Do I understand this right that this has been fixed by https://github.com/rust-lang/rust/pull/125016?
