### ISSUE TITLE
Missing coverage on `assert!(!...)` statements

### ISSUE THREAD

**Issue by EFanZh** [rust-lang/rust#118904]
I tried this code:

```rust
fn main() {
    assert!(!false);
}
```

I expected to see this happen: Run this program with [`cargo-llvm-cov`](https://crates.io/crates/cargo-llvm-cov): `cargo llvm-cov run --html`, I expect the source code should be fully covered.

Instead, this happened: The `assert!` part in the source code is not covered. But if I change `!false` to `true`, the source will be fully covered, it seems that I can’t get `assert!` to be covered as long as the argument starts with an `!` operator.

### Meta
`rustc --version --verbose`:
```
rustc 1.76.0-nightly (f967532a4 2023-12-08)
binary: rustc
commit-hash: f967532a47eb728ada44473a5c4c2eca1a45fe30
commit-date: 2023-12-08
host: x86_64-pc-windows-msvc
release: 1.76.0-nightly
LLVM version: 17.0.5
```

**Comment by matthiaskrgr** [comment]
Might be that llvm just optimizes it out as dead code. Do you see it with -Copt-level=0  ?

**Comment by EFanZh** [comment]
@matthiaskrgr: I think `cargo-llvm-cov` already uses `opt-level=0` by default. Nevertheless, I have tested using `env RUSTFLAGS='-Copt-level=0' cargo llvm-cov run --html --verbose`, and the result is the same.

**Comment by taiki-e** [comment]
This may be a similar case to https://github.com/rust-lang/rust/issues/110486. It seems that something odd is happening when the compiler gets the coverage of the code generated by the macro and maps it to the original code.

**Comment by Nilstrieb** [comment]
cc @Zalathar

**Comment by Zalathar** [comment]
I can reproduce this with `2023-12-08` but not with `2023-12-14`.

It was probably fixed by #118198.

**Comment by Nilstrieb** [comment]
Would it make sense to add a test for this specifically?

**Comment by Zalathar** [comment]
> Would it make sense to add a test for this specifically?

PR filed: #119011

**Comment by ranger-ross** [comment]
A bit late, but I re-tested this on Rust 1.80.0 and it look like #119011 fixed the issues.

I think we are good to close this issue :+1:
