### ISSUE TITLE
MIR validation ICE: Use of local which has no storage

### ISSUE THREAD

**Issue by saethlin** [rust-lang/rust#118990]
```rust
struct CompileError;

impl Drop for CompileError {
    fn drop(&mut self) {}
}

impl CompileError {
    fn throw(&self) {}
}

fn main() {
    'code: {
        break 'code;
        CompileError.throw()
    };
}
```
Build with
```
-Zvalidate-mir
```
```
error: internal compiler error: broken MIR in Item(DefId(0:9 ~ ice[5cf9]::main)) (before pass CheckPackedRef) at bb4[0]:
                                use of local _3, which has no storage here
  --> src/main.rs:15:6
   |
15 |     };
   |      ^

```
```
// MIR for `main` after built

fn main() -> () {
    let mut _0: ();
    let _1: ();
    let mut _2: &CompileError;
    let _3: CompileError;

    bb0: {
        StorageLive(_1);
        _1 = const ();
        goto -> bb3;
    }

    bb1: {
        StorageLive(_2);
        StorageLive(_3);
        _3 = CompileError;
        _2 = &_3;
        _1 = CompileError::throw(move _2) -> [return: bb2, unwind: bb6];
    }

    bb2: {
        StorageDead(_2);
        goto -> bb4;
    }

    bb3: {
        goto -> bb4;
    }

    bb4: {
        drop(_3) -> [return: bb5, unwind: bb7];
    }

    bb5: {
        StorageDead(_3);
        StorageDead(_1);
        _0 = const ();
        return;
    }

    bb6 (cleanup): {
        drop(_3) -> [return: bb7, unwind terminate(cleanup)];
    }

    bb7 (cleanup): {
        resume;
    }
}
```

**Comment by matthiaskrgr** [comment]
Regression in nightly-2022-08-26

found 6 bors merge commits in the specified range
  commit[0] 2022-08-24: Auto merge of #100963 - matthiaskrgr:rollup-pjr0lb3, r=matthiaskrgr
  commit[1] 2022-08-24: Auto merge of #99946 - tmiasko:elide-storage-makers, r=oli-obk
  commit[2] 2022-08-25: Auto merge of #100977 - JohnTitor:rollup-8hc7rxh, r=JohnTitor
  commit[3] 2022-08-25: Auto merge of #100436 - jyn514:macro-query-system, r=cjgillot
  commit[4] 2022-08-25: Auto merge of #100571 - cjgillot:mir-cost-visit, r=compiler-errors
  commit[5] 2022-08-25: Auto merge of #100911 - tmiasko:update-stdarch, r=Amanieu
ERROR: no CI builds available between addacb5878b9970ebc1665768a05cb601e7aea15 and 7480389611f9d04bd34adf41a2b3029be4eb815e within last 167 days

https://github.com/rust-lang/rust/pull/99946 looks quite suspicious cc @tmiasko
