### ISSUE TITLE
`assert_eq!` failed to compile due to the iterator item did not implement `PartialEq`

### ISSUE THREAD

**Issue by OscarTHZhang** [rust-lang/rust#118931]
I am implementing some database file iterator that iterates over the pages in the file. I am writing a unit test to validate my iterator implementation but the compiler throws this error to me:
```
error[E0277]: can't compare `page::Page` with `page::Page`
   --> src/storage/file.rs:318:9
    |
318 |         assert_eq!(None, iter.next());
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no implementation for `page::Page == page::Page`
    |
    = help: the trait `PartialEq` is not implemented for `page::Page`
    = note: required for `Option<page::Page>` to implement `PartialEq`
    = note: this error originates in the macro `assert_eq` (in Nightly builds, run with -Z macro-backtrace for more info)
```

I don't understand why it requires me to implement `PartialEq` for the iterator item, because the `iter.next()` should just give me an `Option` for me to compare with.

**Comment by OscarTHZhang** [comment]
The following assertion works, though:
```rust
assert!(iter.next().is_none());
```

**Comment by oli-obk** [comment]
The compiler does not know that you are comparing against `None`. It could know that, but that's something along the lines of pattern types. I don't think we can change anything here. We could potentially detect the situation and suggest `is_none()` instead (as you already figured out)?

**Comment by OscarTHZhang** [comment]
Thanks. I wonder if we could extend `assert_eq!` macro to include comparing enum types only in general and don't care about the inner struct implementation? Or creating a new assert macro to do this? This is potentially useful for unit testing on enum structs.

**Comment by Cerber-Ursi** [comment]
> if we could extend assert_eq! macro to include comparing enum types only in general and don't care about the inner struct implementation?

That's impossible to do in general, since `assert_eq` doesn't know anything about enum variants - it only knows whatever is directly passed to it. Even special-casing `None` is wrong, since one can have another `None` in scope, shadowing `Option::None`.

**Comment by workingjubilee** [comment]
`assert_matches!` would fix this :^)
