### ISSUE TITLE
Expose the std::sys::windows::fs::OpenOptions::security_attributes method

### ISSUE THREAD

**Issue by Adrien-Bodineau** [rust-lang/rust#118907]
For now the `std::sys::windows::fs::OpenOptions::security_attributes` method is not expose in the windows implementation of OpenOptions. This method is only used in two places `std::sys::windows::pipe.rs` and `std::sys::windows::process.rs`, in both cases it is only used to create a default security attributes.

However it would be nice to have this function exposed in OpenOptions so one can pass a specific security attribute using the `std::fs` implementations instead of having to use the `CreateFile` function directly.

would love to hear some opinions on that and if there is a reason why this is not the case, to know more about it :)

**Comment by ChrisDenton** [comment]
See [std::os::windows::fs::OpenOptionsExt](https://doc.rust-lang.org/std/os/windows/fs/trait.OpenOptionsExt.html)

**Comment by Adrien-Bodineau** [comment]
yes that is what I had in mind

**Comment by ChrisDenton** [comment]
You can propose a new public API using an [API Change Proposal](https://github.com/rust-lang/libs-team/issues/new/choose).

**Comment by jieyouxu** [comment]
As this would require an ACP over at <https://github.com/rust-lang/libs-team/>, I'm closing this issue.
