### ISSUE TITLE
`*mut` "uses" type params, but `*const` (and therefore `NonNull`) does not

### ISSUE THREAD

**Issue by eggyal** [rust-lang/rust#118976]
**Update**(fmease): See https://github.com/rust-lang/rust/issues/118976#issuecomment-1863691682 and https://github.com/rust-lang/rust/issues/118976#issuecomment-1864232472.

---

As first [mentioned on URLO](https://users.rust-lang.org/t/why-does-mut-use-its-type-parameters-but-const-does-not/103976), and demonstrated on quick [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=33dbd0606b463a89d762c48575a11355):

```rust
struct Foo<T>(*mut Self); // works
struct Bar<T>(*const Self); // error[E0392]: parameter `T` is never used
```

Is this a bug, or is there some obscure reason for it?

**Comment by Darksonn** [comment]
Note that the use of `Self` is not the problem:
```Rust
struct Foo<T>(*mut Foo<T>); // works
struct Bar<T>(*const Bar<T>); // error[E0392]: parameter `T` is never used
```

**Comment by fmease** [comment]
`*mut` is invariant over its pointee type while `*const` is covariant over it. `Foo` is invariant over `T` because invariance “overrules” bivariance (all to-be-inferred terms start out as bivariant). `Bar` is *bivariant* over `T` (i.e., `T` is “unused”) since bivariance “overrules” covariance. Sorry for the super technical explanation. I don't really see a bug :thinking:

Similar example:

```rs
struct Foo<T: 'static>(&'static Foo<T>); // works
struct Bar<T: 'static>(&'static mut Bar<T>); // errors
```

**Comment by eggyal** [comment]
Ah, thank you.  I had thought it might be variance-related and did refresh my memory with a read of the chapters on subtyping in the [reference](https://doc.rust-lang.org/reference/subtyping.html) and [nomicon](https://doc.rust-lang.org/nomicon/subtyping.html) but neither mention "bivariance" at all nor how variance relates to whether a type parameter is deemed to be "used" in a type definition.

Perhaps this is already documented somewhere that I missed, but if not maybe this is a documentation bug?

**Comment by eggyal** [comment]
Can it really be an implementation detail if its effect is user facing ?

**Comment by fmease** [comment]
Yeah, makes sense. Probably worth opening an issue over at the Reference and/or the Nomicon. It's an implementation detail insofar that rustc never mentions “bivariance” in any error messages for example and only talks about generic parameters “that must be used”.

**Comment by eggyal** [comment]
Okay, thanks again.  Will open an issue as advised.  Closing here.

**Comment by QuineDot** [comment]
In short "uses" really means "could determine variance of".

Related issues:
- https://github.com/rust-lang/rust/issues/74165
- https://github.com/rust-lang/rust/issues/92561
- https://github.com/rust-lang/rust/issues/26283
- https://github.com/rust-lang/rust/issues/53191
- https://github.com/rust-lang/rust/issues/66912
- https://github.com/rust-lang/rust/issues/105740
- https://github.com/rust-lang/rust/issues/110466

**Comment by eggyal** [comment]
Yes, that's a helpful clarification.  Perhaps that could be added into the explanation of E0392?
