### ISSUE TITLE
rustdoc: Methods on type aliases are not documented if the target type is not publicly reachable

### ISSUE THREAD

**Issue by sgued** [rust-lang/rust#119015]
I tried this code:

```rust
mod foo {
    pub struct S;
}

use foo::S;

pub type A = S;

impl Default for A {
    fn default() -> Self {
        S
    }
}

impl A {
    pub fn a(&self) {}
}
```

I expected the documentation for the type alias `A` to show the method `fn a(&self)` and the implementation  of `Default`.

Instead, the type alias does not show the method `fn a(&self)`. It does however show the implementation of `Default`.

![image](https://github.com/rust-lang/rust/assets/51865119/60a48ce0-2eff-4172-af31-07b73b51c1b1)

### Workarounds

By publicly exposing `foo::S` through `pub use foo::S`, the documentation of `fn a(&self)` on the alias is documented as I expected, but then `foo:S` is publicly reachable, which in my case is unwanted due to being an internal implementation detail.

This also works when making the `use` statement `#[doc(hidden)]`, which gets the docs to look like I expected them to.

```rust
mod foo {
    pub struct S;
}

#[doc(hidden)]
pub use foo::S;

pub type A = S;

impl Default for A {
    fn default() -> Self {
        S
    }
}

impl A {
    pub fn a(&self) {}
}
```

![image](https://github.com/rust-lang/rust/assets/51865119/27f2bd1f-2eab-47fd-a7fb-85cc7640dcd4)

### Meta

`rustc --version --verbose`:
```
cargo 1.74.1 (ecb9851af 2023-10-18)
release: 1.74.1
commit-hash: ecb9851afd3095e988daaa35a48bc7f3cb748e04
commit-date: 2023-10-18
host: x86_64-unknown-linux-gnu
libgit2: 1.7.1 (sys:0.18.0 vendored)
libcurl: 8.4.0-DEV (sys:0.4.68+curl-8.4.0 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Arch Linux [64-bit]
```

Thanks @GuillaumeGomez for helping me figure out why what I was expecting wasn't happening though it looked like it should.

**Comment by GuillaumeGomez** [comment]
I think it's ok to document an impl on a reexported if the reexported item is not doc hidden. I'll send a fix in the next dates.
