### ISSUE TITLE
Can't install for low end machines 

### ISSUE THREAD

**Issue by x64x2** [rust-lang/rust#119038]
I can't use rust on my HP notebook 540 running windows 7, there's no support for windows 7 users and this is really bad considering so many windows 7 users want to use rust ༎ຶ⁠‿⁠༎ຶ

**Comment by bjorn3** [comment]
The x86_64-pc-windows-msvc target should still support windows until rustc 1.75 with rustc 1.76 dropping support. After that you will have to switch to x86_64-win7-windows-msvc (https://github.com/rust-lang/rust/pull/118150, currently tier 3 so not available as binary release though, but I believe the intent is for it to become tier 2, which means that it is available as binary release, but is not tested as github actions doesn't support windows 7 VM's).

See also https://github.com/rust-lang/compiler-team/issues/651

**Comment by Nilstrieb** [comment]
What is the problem that stops you from using Rust?

**Comment by ChrisDenton** [comment]
There's no clear indication of what the issue was or what error was encountered so closing this as not actionable.
