### ISSUE TITLE
`non_lifetime_binders` falsely recognizes (and rejects) trait as lifetime

### ISSUE THREAD

**Issue by LastExceed** [rust-lang/rust#119067]
minimal repro:
```rust
#![allow(incomplete_features)]
#![feature(non_lifetime_binders)]

trait MyTrait1 {}

trait MyTrait2
    where for <T: MyTrait1> ():
{
    
}
```

output:
```
error: lifetime bounds cannot be used in this context
 --> src/lib.rs:7:19
  |
7 |     where for <T: MyTrait1> ():
  |                   ^^^^^^^^
```

use case:
> [[playground]](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=cf6cb68a291cd0982dd00d021df0c0f3) 
> weird example, i know. its difficult to construct a proper example that isn't overly complex

workaround:
> add the bound to all call sites that require it (e.g. add `where Human: Consume<Food>` to `foo()` in the above example)

rustc:
> 1.76.0-nightly (2023-12-17 6a62871320e262661bb1)

**Comment by fmease** [comment]
Right, this is a diagnostic bug and a current limitation of `non_lifetime_binders`.

Obviously, we should say *bounds cannot be used in this context* instead (dropping the word *lifetime*). The diagnostic has simply never been updated after `for<T>` became syntactically valid and still assumes that `for<'a: 'b>` is the only possible way for a user to sneak in a higher-ranked bound.
Note to ppl interested in fixing this: Please add a regression test for the following code, too:

```rs
#![feature(closure_lifetime_binder)]
fn main() { let _ = for<T: Trait> || {}; }
```

Secondly, higher-ranked bounds aren't supported yet. There's a draft PR, namely #115362, which is blocked on a performance run.

**Comment by cynecx** [comment]
Okay, I might have imagined things because I can reproduce this on a build from early November 🤷‍♂️.
