### ISSUE TITLE
`Vec::capacity()` docs are wrong for empty types

### ISSUE THREAD

**Issue by bsilver8192** [rust-lang/rust#119150]
### Location

https://doc.rust-lang.org/std/vec/struct.Vec.html#method.capacity

### Summary

`Vec::<Empty>::new().capacity()` is `usize::MAX` (given `enum Empty {}`), even though this vector cannot hold any elements with or without reallocating. No instances of this empty type may be created, so this vector can never hold any elements. The docs say nothing about the size of anything, they just say "elements the vector can hold".

My proposed alternative wording:
```
The vector will not reallocate to hold up to the returned number of elements.
```
That's a triple negative though, so hopefully somebody else can come up with something better.

`with_capacity` and `with_capacity_in` have similar wording that should be updated to match.

**Comment by chfogelman** [comment]
I'm not really convinced this is a problematic wording. In the case of empty types, the current wording is more like a vacuous truth than an outright falsehood. The way I see it, the vec _can_ hold that many elements, if you can create them. Pragmatically, it seems odd to make the wording more verbose and confusing just to cover the case of empty types.

**Comment by Noratrieb** [comment]
I agree, this is fine as-is and I think the current wording is clearer for inhabited types, which are generally what users care about.
