### ISSUE TITLE
`--verbose` should imply `-Z write-long-types-to-disk=no`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#119130]
see https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/uplift.20some.20-Zverbose.20calls.20and.20rename.20to.E2.80.A6.20compiler-team.23706, https://github.com/rust-lang/rust/pull/119129

`--verbose` should imply `-Z write-long-types-to-disk=no`. the code in `ty_string_with_limit` should take `--verbose` into account (apparently this affects `Ty::sort_string`, i'm not familiar with this code). writing a file to disk should suggest passing `--verbose`.

cc @estebank

@rustbot label A-diagnostics

**Comment by Rajveer100** [comment]
@yossydev 
I hadn't refreshed the page so I didn't notice you had already claimed the issue, feel free to open a PR if you have a fix.

**Comment by jyn514** [comment]
note this will be annoying to work on until https://github.com/rust-lang/rust/pull/119129 lands since currently `--verbose` isn't stored anywhere, only used directly in rustc_driver_impl

**Comment by estebank** [comment]
And it has now landed in main.

**Comment by ffmancera** [comment]
I have a patch ready that I think it might be a good candidate. I am taking the issue. @yossydev if this is a problem and you also have something ready I can drop it, is fine.

@rustbot claim
