### ISSUE TITLE
LLVM 18 issue: tests/ui/asm/inline-syntax.rs#arm broken after LLVM https://github.com/llvm/llvm-project/commit/96aca7c51701f9b3c5dd8567fcddf29492008e6d

### ISSUE THREAD

**Issue by krasimirgg** [rust-lang/rust#119120]
After https://github.com/llvm/llvm-project/commit/96aca7c51701f9b3c5dd8567fcddf29492008e6d, rustc starts emitting duplicate diagnostics while running the tests/ui/asm/inline-syntax.rs#arm test:
https://buildkite.com/llvm-project/rust-llvm-integrate-prototype/builds/24569#018c7e16-58de-4bfd-a579-6b4a83bec58d/244-1054.

Looking at the commit description, the change adapts the behavior of emitting these diagnostics to be consistent across different linking modes, but doesn't prevent the possibility for duplicated diagnostics. Seems like a quick fix would be to add `-Zdeduplicate-diagnostics` to that test.

**Comment by nikic** [comment]
Is the duplicate diagnostic an LLVM bug?

**Comment by krasimirgg** [comment]
There are two effects at play:

1. duplicated diagnostic
2. extra note for the assembly syntax is emitted

I'm not sure if the duplicated diagnostic is an LLVM bug. It's however consistent before and after this change: the first diagnostic is duplicated in both cases.

The test failure is due to the second effect: after this change, there's an extra note emitted now for the (duplicated) diagnostic. This https://github.com/rust-lang/rust/pull/119185/files illustrates the difference.
