### ISSUE TITLE
Tracking Issue for split_at_checked

### ISSUE THREAD

**Issue by mina86** [rust-lang/rust#119128]
Feature gate: `#![feature(split_at_checked)]`.

This is a tracking issue for the addition of `split_at_checked` and `split_at_mut_checked` methods to `[T]` and `str` types which are non-panicking versions of `split_at` and `split_at_mut` methods.  Rather than panicking when spit index is out of range (like `split_at` does), the methods return `None`.

### Public API

```rust
impl<T> [T] {
    pub fn split_at_checked(&self, mid: usize) -> Option<(&[T], &[T])>;
    pub fn split_at_mut_checked(&self, mid: usize) -> Option<(&[T], &[T])>;
}

impl str {
    pub fn split_at_checked(&self, mid: usize) -> Option<(&str, &str)>;
    pub fn split_at_mut_checked(&mut self, mid: usize) -> Option<(&str, &str)>;
}
```

### Steps / History

- [x] ACP: https://github.com/rust-lang/libs-team/issues/308
- [x] Implementation: https://github.com/rust-lang/rust/pull/118578
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

Name of the methods.  Some possibilities ([suggested in ACP discussion](https://github.com/rust-lang/libs-team/issues/308)):

1. `split_at_checked` and `split_at_mut_checked` — follows naming of `split_at_unchecked` and `split_at_mut_unchecked`.  Using suffix makes the names sort nicely together.
2. `checked_split_at` and `checked_split_at_mut` — follows naming convention of arithmetic types (e.g. `checked_add`).  Those new functions serve similar purpose as checked arithmetic operations.
3. `try_split_at` and `try_split_at_mut` — follows naming of various fallible methods such as `try_from`, `try_new`, `try_for_each` etc.  Shortest of the three suggestions.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by tgross35** [comment]
I wonder if the `str` method should return a `Result` since they have two failure modes - invalid char boundary and OOB of the string.

**Comment by mina86** [comment]
Personally I’d rather not complicate the interface and have the methods on slice and on str return the same kind of value. No strong feelings though.

**Comment by faern** [comment]
Thanks for pushing for this feature :heart: I really want this to land! Panic free handling of byte slices has been in a pretty bad state a long time. I came here just now because I was trying out the new `split_first_chunk` just to realize I could not make the code improvements I have been wanting a long time without also having panic free slice splitting with a runtime `mid`. `split_first_chunk` and `split_at_checked` do the same thing really, but one of them have the splitting index as a const generic.

I just tried `slice::split_first_chunk` and it does wonders to my code. Both in terms of code simplicity/readability but also to amount of potentially panic locations.

@mina86 You can check the implementation PR step in your initial comment. That's merged :partying_face:

**Comment by UserIsntAvailable** [comment]
@m-ou-se Can we get a fcp for this? `slice::split_at_{mut}_unchecked` is getting stabilized on `1.79.0`  and I think is going to be kinda akward to not also provide the safe non-panic option as well on the same release.

---

> Name of the methods. Some possibilities

For consistency with the existing methods on `slice` and `str`, it probably should be called `split_at_{mut}_checked`.

> I wonder if the `str` method should return a `Result` since they have two failure modes - invalid char boundary and OOB of the string.

IMO returning option here _should be fine_. But  `t-libs` might have something else to say about this?

**Comment by Amanieu** [comment]
We discussed this in the libs-api meeting and are happy to merge this as it is. The `_checked` suffix is consistent with the already stabilized `_unchecked` methods, and returning an `Option` is consistent with the `.get()` method.

@rfcbot fcp merge

**Comment by Stargateur** [comment]
this was related to https://github.com/rust-lang/rust/issues/90410. However this doesn't handle str case, and I would have prefer Result.

This become stable very fast Oo.
