### ISSUE TITLE
`Vec::reserve()` (etc) panic conditions don't apply to zero-sized or empty types

### ISSUE THREAD

**Issue by bsilver8192** [rust-lang/rust#119149]
### Location

https://doc.rust-lang.org/std/vec/struct.Vec.html#method.reserve (and several other methods)

### Summary

`Vec::<()>::new().capacity()` is `usize::MAX`, which is greater than `isize::MAX`. Calling `reserve(1)` on this vector does not panic, and the capacity afterwards is still greater than `isize::MAX`. The docs say this should unconditionally panic.

I would find it reasonable to rely on this documentation as part of ensuring soundness of some unsafe code interacting with `Vec`, without duplicating the assertion in my code.

This same comment is repeated on several other `Vec` methods, and the same thing applies.

For reference, #117437 and #99790 are another issue and a PR touching on this same sentence of the documentation.

**Comment by Jules-Bertholet** [comment]
The docs say (emphasis mine):

> # Panics
>
> Panics if the new capacity exceeds `isize::MAX` ***bytes***.

A `Vec::<()>` will never have more than 0 bytes of capacity, and therefore `reserve` will never panic.

**Comment by bsilver8192** [comment]
Oh you're right, I read that many times and never processed the last word. That's the only place I see which talks about "capacity" as a number of bytes instead of a number of elements, which is easy to miss IMHO.

**Comment by Nilstrieb** [comment]
Might make sense to make the`bytes` bold.

**Comment by gurry** [comment]
> Might make sense to make the`bytes` bold.

I have raised PR #119374 doing just that (except italicising it instead making it bold)
