### ISSUE TITLE
Incorrect result for `rem_euclid`

### ISSUE THREAD

**Issue by Skgland** [rust-lang/rust#119197]
I tried this code:

```rust
fn main() {
    let orig : isize = -13;
    let rhs = 20;
    
    let rem = orig.rem_euclid(20);
    let rem2 = -13isize.rem_euclid(20);
    let rem3 = -13isize.rem_euclid(rhs);
    
    
    println!("{rem}: {rem2}: {rem3}")
}
```

[Rust Playround](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2ac0dc8ad45887ff4fd989d2b6d793a1)

I expected to see this happen: Prints `7: 7: 7`

Instead, this happened: Prints `7: -13: -13`

**Comment by wwylele** [comment]
This is not a bug in rem_euclid but confusion about operator precedence. By `-13isize.rem_euclid(20);` you probably wanted to write `(-13isize).rem_euclid(20);`

**Comment by Skgland** [comment]
:facepalm: Oh, I see. That's somewhat unintuitive.
