### ISSUE TITLE
Immutability breaks when Mutex inside

### ISSUE THREAD

**Issue by yanganto** [rust-lang/rust#119177]
The data with Mutext can be modified in silence.

I tried this code:

```rust
use std::sync::Mutex;

struct S {
    pub inner: Mutex<usize>
}
impl S {
    fn silence_mut(&self) {
        // This can mutate the inner silence
        *self.inner.lock().unwrap() = 2;
        
        // This will not pass when compiling
        // *self.inner.get_mut().unwrap() = 2;
    }
}

fn main() {
    let s = S {
        inner: Mutex::new(0)
    };
        
    println!("{:?}", s.inner);  // Mutex { data: 0, poisoned: false, .. }
    s.silence_mut();
    println!("{:?}", s.inner);  // Mutex { data: 2, poisoned: false, .. }
}
```

I expected to see this happen:
The `fn silence_mut(&self)` should not be compiled, the behavior should be the same as we using `get_mut()` on an inner Mutex structure.

Instead, this happened:
The code can be built and the value is mutated.

Could the `lock` of Mutex be `pub fn lock(&mut self) -> LockResult<MutexGuard<'_, T>>`?

### Meta
This issue happened in 
- Stable version: 1.74.1
- Nightly version: 1.76.0-nightly (2023-12-20 5ac4c8a63ee305742071)

**Comment by bjorn3** [comment]
This is intentional. The term for this is interior mutability. You may want to read https://doc.rust-lang.org/stable/book/ch15-05-interior-mutability.html#refcellt-and-the-interior-mutability-pattern and ask at https://users.rust-lang.org/ if you need help understanding it.

**Comment by yanganto** [comment]
Okay, I see.  Thanks for explaining.  I thought it should not happen if no thread spawned to grab the lock.
