### ISSUE TITLE
Document ErrorKind for create_new failed due to file already exists

### ISSUE THREAD

**Issue by anatawa12** [rust-lang/rust#119244]
### Location

https://doc.rust-lang.org/std/fs/struct.OpenOptions.html#method.create_new

### Summary

With `create_new` option, we can create files if not exists and fail to create if already exists or fail with other general errors such as permission errors.

I want to retry with another file name if the failure is because file is already exists but there are no documentation about error kind in `create_new`.
I think the error kind for `create_new` failure due to file already exists is `AlreadyExists`.
I think it's better to document that in `create_new`.

**Comment by Nilstrieb** [comment]
On Unix-like targets, it uses `O_EXCL`, which is [documented](https://pubs.opengroup.org/onlinepubs/007904875/functions/open.html) to error with `EEXIST` (`AlreadyExists`). On Windows, we use [CreateFileW](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilew) with `CREATE_NEW`, which is documented to error with `ERROR_FILE_EXISTS` (`AlreadyExists`).
So this seems to be correct (everything else would also a bug, arguably).
