### ISSUE TITLE
[strict provenance] make compiler's `Term` and `GenericArg` conform

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#119217]
`Term` and `GenericArg` currently store pointers as `NonZeroUsize`, which is not ideal:

https://github.com/rust-lang/rust/blob/92ad4b433a00852341019ad592ba9dfce17e9214/compiler/rustc_middle/src/ty/generic_args.rs#L34

https://github.com/rust-lang/rust/blob/92ad4b433a00852341019ad592ba9dfce17e9214/compiler/rustc_middle/src/ty/mod.rs#L846

They should really work with `NonNull` pointers and strict provenance APIs like `.map_addr`, `.mask`, etc.

See a PR fixing a similar issue for _some_ context: #110243 (note: in that one I ended up rewriting the whole thing, I think this issue requires far less changes).

**Comment by WaffleLapkin** [comment]
(I do plan to work on this, but if you want to work on this instead — feel free to `@rustbot claim`, I can mentor you)
<sub>cc @RalfJung</sub>

**Comment by Rajveer100** [comment]
@WaffleLapkin 
Could you briefly describe `Term` and `GenericArg`, also a comprehensive insight about this issue would greatly help, although I had a look at `strict provenance` which currently is an `unstable feature`.

> If you ever want to treat something as a Real Pointer that can be Offset and Dereferenced, there must be an unbroken chain of custody from that pointer to the original allocation you are trying to access using only pointer->pointer operations.

If I understand correctly, we are building a `model` for this and aim to improve existing _implementations_ as seen in languages like C++ by making it more _strict_, and there is some discussion that `unsafe Rust` can basically do most of what C++ can and this addition might have some diverging path. 

Let me know, so I can move forward!

**Comment by fee1-dead** [comment]
Hi @Rajveer100, strict provenance means that we aren't doing pointer->int conversions and only operate through pointer types like `NonNull` suggested by OP. `Term` and `GenericArg` currently use `NonZeroUsize` which doesn't work under strict provenance. If you'd like I can work on this issue.

**Comment by Rajveer100** [comment]
Did you mean to mentor me for the same, I would be happy to learn!

**Comment by Nilstrieb** [comment]
@kamalesh0406 is already working on this issue, is this right? Let's not override other people working on it already unless they agree or it's been several weeks with no response.

**Comment by kamalesh0406** [comment]
Hi @Nilstrieb yes I am working on this issue. This is my first time contributing so it will take me sometime. I will reassign the issue to me.

**Comment by fee1-dead** [comment]
Hi @kamalesh0406: Just checking in :) Are you still working on this issue?

**Comment by kamalesh0406** [comment]
Yup I am still working on this issue :)

**Comment by fee1-dead** [comment]
Let us know if you need any help on Zulip

**Comment by WaffleLapkin** [comment]
@RalfJung with this resolved, I think rustc is free from "fuzzy provenance casts" :)

**Comment by RalfJung** [comment]
Awesome :-)
