### ISSUE TITLE
Embedding API

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#11921]
cc #11920, define a set of C-ABI functions to comprise Rust's embedding API. Not sure what all we need here, it might be pretty minimal, we at  least need to provide ways to start up and shutdown the runtime, and to enter tasks in a few different ways.

Seems like there must be an existing issue on this somewhere.

**Comment by trws** [comment]
Is this issue still relevant since the runtime is now all lazy initialized?

**Comment by steveklabnik** [comment]
I don't believe so, thanks for triaging!
