### ISSUE TITLE
Some bugs about file system on emscripten target.

### ISSUE THREAD

**Issue by TheVeryDarkness** [rust-lang/rust#119250]
I tried this code:

```rust
//! This is src/bin/metadata.rs.
//! Compiled to wasm32-unknown-emscripten.
//! My codes are in <https://github.com/TheVeryDarkness/wasm-emscripten-fs-bug>.
use std::fs::{create_dir, metadata, read_dir, write};

fn main() {
    create_dir("workspace");
    write("workspace/a.txt", "I'm a.\n").unwrap();
    write("workspace/b.txt", "This is b.\n").unwrap();
    for file in read_dir("workspace").unwrap() {
        let file = file.unwrap();
        println!("{:?}", file.path());
        let meta = file.metadata().unwrap();
        println!("{:?}", meta);
        println!("{}", meta.len());
    }
    let meta = metadata("workspace").unwrap();
    println!("{:?}", meta);
    // This seems to be the same with permission code.
    println!("{:?}", meta.file_type());
    println!("{}", meta.is_dir());
    println!("{}", meta.is_file());
    println!("{}", meta.is_symlink());
}
```

I expected to see this happen: *got correct `file_type()` and `len()`*.

Instead, this happened: *`file_type()` returns permission code, while `len()` returns created time.*.

### Meta

`rustc --version --verbose`:
```
wasm_emscripten_fs_bug % rustc +nightly --version --verbose
rustc 1.77.0-nightly (d6d7a9386 2023-12-22)
binary: rustc
commit-hash: d6d7a93866f2ffcfb51828b8859bdad760b54ce0
commit-date: 2023-12-22
host: aarch64-apple-darwin
release: 1.77.0-nightly
LLVM version: 17.0.6
```

<details><summary>Backtrace</summary>
<p>

No panic here, so there's no RUST_BACKTRACE.

</p>

Running with `RUST_BACKTRACE=1 cargo +nightly run -Zbuild-std --target wasm32-unknown-emscripten --release -vv --bin metadata`.

</details>

**Comment by Nilstrieb** [comment]
`std` just forwards from libc
https://github.com/rust-lang/rust/blob/edcbcc768a484d52deb315e7c583fe4b2ab4f25b/library/std/src/sys/unix/fs.rs#L868
https://github.com/rust-lang/rust/blob/edcbcc768a484d52deb315e7c583fe4b2ab4f25b/library/std/src/sys/unix/fs.rs#L1680

https://github.com/rust-lang/libc/blob/6424b09903dd0e5a3e25a541299da71f88bca932/src/unix/linux_like/emscripten/mod.rs#L256

`libc` seems to have some cfgs about new stat ABIs.. that seems relevant. it activates this cfg when emcc has version `>3.1.42`. what's your `emcc -dumpversion`?

**Comment by TheVeryDarkness** [comment]
@Nilstrieb Sorry, I didn't see the notification.

```
wasm_emscripten_fs_bug % emcc -dumpversion
3.1.50-git
```

I'm using emscripten installed with Homebrew, and it's usually fresh enough.

**Comment by kleisauke** [comment]
It looks like the Emscripten version parser in libc doesn't understand the `-git` suffix in version numbers.
https://github.com/rust-lang/libc/blob/98999135403524e510d4cdd357b507bf1e5c3e42/build.rs#L259-L284

I always thought this `-git` suffix would only be included for "tip-of-tree builds". It's a bit unfortunate that this also happens with the Emscripten distributed by Homebrew.

As a possible workaround for now, you can patch `emscripten-version.txt` to remove this suffix:
```console
$ emcc -dumpversion
3.1.52-git
$ cat $EMSDK/upstream/emscripten/emscripten-version.txt
3.1.52-git
$ sed -i 's/-git//' $EMSDK/upstream/emscripten/emscripten-version.txt
$ emcc -dumpversion
3.1.52
```
(on macOS, you'll probably need to change it to use `$(brew --prefix emscripten)/libexec/emscripten-version.txt` instead)

**Comment by TheVeryDarkness** [comment]
> It looks like the Emscripten version parser in libc doesn't understand the `-git` suffix in version numbers.
> https://github.com/rust-lang/libc/blob/98999135403524e510d4cdd357b507bf1e5c3e42/build.rs#L259-L284
> 
> I always thought this `-git` suffix would only be included for "tip-of-tree builds". It's a bit unfortunate that this also happens with the Emscripten distributed by Homebrew.
> 
> As a possible workaround for now, you can patch `emscripten-version.txt` to remove this suffix:
> ```console
> $ emcc -dumpversion
> 3.1.52-git
> $ cat $EMSDK/upstream/emscripten/emscripten-version.txt
> 3.1.52-git
> $ sed -i 's/-git//' $EMSDK/upstream/emscripten/emscripten-version.txt
> $ emcc -dumpversion
> 3.1.52
> ```
> (on macOS, you'll probably need to change it to use `$(brew --prefix emscripten)/libexec/emscripten-version.txt` instead)

@kleisauke Yes, it works. Thanks a lot. Would you open an issue to libc?

**Comment by kleisauke** [comment]
I just opened PR https://github.com/rust-lang/libc/pull/3498 for this.

**Comment by TheVeryDarkness** [comment]
> I just opened PR https://github.com/rust-lang/libc/pull/3498 for this.

Thanks a lot.

**Comment by TheVeryDarkness** [comment]
Well, I just heard that installing Emscripten with Homebrew is unofficial.

And there's still more problems when I run my program. Maybe I'll install Emscripten with emsdk later, and test my program again.

**Comment by TheVeryDarkness** [comment]
Thanks a lot for you all! And I have [another problem](https://github.com/rust-lang/rust/issues/119464) with strict mode in emscripten, which is not so critical.
