### ISSUE TITLE
Add a macro non-terminal for the interior of a block

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#11928]
e.g. (using the currently-invalid brace syntax from #11892)

```rust
macro_rules! spawn {
     ($b: block_internals) => {
        spawn(proc() { $b })
     }
}

spawn! {
     use foo::bar;
     fn baz() {}

     if x == 0 { bar() }
     let a = 1 + 2;
     foo();
     baz()
}
```

I don't believe this is currently possible to emulate. e.g. with `$($s: stmt);*` you have to write `fn foo() {}; if x == 0 { bar() }; ...` and without the `;` you end up with `foo() bar()` being valid (and `expr` doesn't allow for statements like `let` and `fn bar() {}`). The best solution I've found is just writing `($e: expr) => { ... }` but this requires double braces:

```rust
spawn! { foo() } // ok

spawn! { foo(); bar() } // not ok! :(

spawn! {{ foo(); bar() }} // ok :(
```

This would make sugary control-flow-y macros like `spawn` and `scope`/`finally` from https://github.com/mozilla/rust/pull/11905 more natural.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#672
