### ISSUE TITLE
Arc/Rc is creating references to uninitialized values

### ISSUE THREAD

**Issue by taiki-e** [rust-lang/rust#119241]
[addr_of_mut doc](https://doc.rust-lang.org/nightly/core/ptr/macro.addr_of_mut.html) says:

> Creating a reference with `&`/`&mut` is only allowed if the pointer is properly aligned and points to initialized data. For cases where those requirements do not hold, raw pointers should be used instead. However, `&mut expr as *mut _` creates a reference before casting it to a raw pointer, and that reference is subject to the same rules as all other references. This macro can create a raw pointer without creating a reference first.

> ```rs
> let mut uninit = MaybeUninit::<Demo>::uninit();
> // `&uninit.as_mut().field` would create a reference to an uninitialized `bool`,
> // and thus be Undefined Behavior!
> let f1_ptr = unsafe { ptr::addr_of_mut!((*uninit.as_mut_ptr()).field) };
> ```

However, some code in Arc/Rc seems to create references to uninitialized values.

For example, in the following code, `inner` is a pointer to an uninitialized `ArcInner`, but `Layout::for_value(&*inner)` creates a reference to it, and `&mut (*inner).strong` and `&mut (*inner).weak` creates references to (uninitialized) counters.

https://github.com/rust-lang/rust/blob/495203bf61efabecc2c460be38e1eb0f9952601b/library/alloc/src/sync.rs#L1825-L1836

Such codes can also be found in some other places in Arc/Rc.

https://github.com/rust-lang/rust/blob/495203bf61efabecc2c460be38e1eb0f9952601b/library/alloc/src/sync.rs#L3386
https://github.com/rust-lang/rust/blob/495203bf61efabecc2c460be38e1eb0f9952601b/library/alloc/src/sync.rs#L1866
https://github.com/rust-lang/rust/blob/495203bf61efabecc2c460be38e1eb0f9952601b/library/alloc/src/sync.rs#L1901
https://github.com/rust-lang/rust/blob/495203bf61efabecc2c460be38e1eb0f9952601b/library/alloc/src/sync.rs#L1940
https://github.com/rust-lang/rust/blob/495203bf61efabecc2c460be38e1eb0f9952601b/library/alloc/src/rc.rs#L1888-L1890
https://github.com/rust-lang/rust/blob/495203bf61efabecc2c460be38e1eb0f9952601b/library/alloc/src/rc.rs#L1921
https://github.com/rust-lang/rust/blob/495203bf61efabecc2c460be38e1eb0f9952601b/library/alloc/src/rc.rs#L1955
https://github.com/rust-lang/rust/blob/495203bf61efabecc2c460be38e1eb0f9952601b/library/alloc/src/rc.rs#L1993
https://github.com/rust-lang/rust/blob/495203bf61efabecc2c460be38e1eb0f9952601b/library/alloc/src/rc.rs#L2527

At least the following code should run into this issue because it calls `Arc::initialize_arcinner` via `<Arc<_> as From<Box<_>>::from` -> `Arc::from_box_in` -> `Arc::allocate_for_ptr_in` -> `Arc::allocate_for_layout`.

```rs
use std::{boxed::Box, sync::Arc};
let boxed: Box<str> = Box::from("abc");
let arc: Arc<str> = Arc::from(boxed);
assert_eq!("arc", &arc[..]);
```

## Solution

This can be fixed in the following ways:

- Use `Layout::for_value_raw` (unstable) instead of `Layout::for_value`.
- Use `addr_of_mut` for code creating reference to uninitialized conters (`.strong`/`.weak`).
- Use `addr_of_mut` or `new_uninit`/`new_unint_slice` for code creating reference to uninitialized data (`.data`/`.value`). (I think the latter would be clearer.)

---

cc @RalfJung: Miri doesn't seem to report this as UB, but is my understanding that this is the kind of UB that Miri does not currently support detection correct? Or is it missed or allowed for some reason?

**Comment by RalfJung** [comment]
Cc @rust-lang/opsem 

The status of reference to uninit memory is undecided. We document them as UB in the reference so that we can make this decision without code already relying on an outcome. Miri does not flag this UB because we are not sure if we really want to rule out all that code. The compiler does not actually make them UB and the standard library can rely on that, but user code cannot.

Also see discussion in
- https://github.com/rust-lang/unsafe-code-guidelines/issues/346
- https://github.com/rust-lang/unsafe-code-guidelines/issues/412
- https://github.com/rust-lang/unsafe-code-guidelines/issues/413
- https://github.com/rust-lang/unsafe-code-guidelines/issues/414
