### ISSUE TITLE
rust 2024 edition

### ISSUE THREAD

**Issue by i1kaaasra** [rust-lang/rust#119347]
where can I find rust 2024 edition roadmap ?? 

and

when the rust 2024 edition release ??

**Comment by fmease** [comment]
See https://github.com/rust-lang/rfcs/pull/3501#issuecomment-1752162988 for an answer

**Comment by fmease** [comment]
You can subscribe here: #117258

**Comment by fmease** [comment]
More frequent updates can be found here: https://rust-lang.zulipchat.com/#narrow/stream/318377-t-lang.2Froadmap-2024

**Comment by fmease** [comment]
The list of features contained in Rust 2024 is still being discussed.

**Comment by fmease** [comment]
Ah, I found a tentative roadmap: https://github.com/orgs/rust-lang/projects/43
