### ISSUE TITLE
Inliner use of storage statements is unsound

### ISSUE THREAD

**Issue by tmiasko** [rust-lang/rust#119366]
The inliner strategy for dealing with storage statements is simple. If a callee local already has some storage statements, they are preserved as is when integrating callee into the caller. There are no new storage statements for such locals.

Turns out this approach is unsound due to peculiar semantics of MIR. It is well defined to return from a function while there are still some live locals. At the same time it is undefined behaviour to execute StorageLive for already live local. Effectively inliner is obliged to end the storage for locals that are still live when callee returns, which it doesn't do at the moment.

Arguably this is more of a bug in MIR semantics, then one in the inliner https://github.com/rust-lang/unsafe-code-guidelines/issues/129#issuecomment-1806384665.

**Comment by apiraino** [comment]
hey @tmiasko would you like to first T-opsem discuss this? Maybe have this topic on a meeting and figure out a plan to fix this?

**Comment by RalfJung** [comment]
Oh, interesting catch. Cc @rust-lang/opsem 

Maybe we should just allow StorageLive on an already live local (and declare it to first implicitly free the local, and then make it live again)...
