### ISSUE TITLE
[`missing_debug_implementations`] shouldn't lint on structs with fields that does not impl `Debug`

### ISSUE THREAD

**Issue by J-ZhengLi** [rust-lang/rust#119333]
### Code

See ~~[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=bd570fa7500fbf23192d609ea1bb75ac)~~ for more detail

Edit: Perhaps this example is better? [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b61c7b511d969284f1be27bf3520914a)

```Rust
#![warn(missing_debug_implementations)]

struct Node;

pub struct Foo(Node);
```

### Current output

```Shell
warning: type does not implement `Debug`; consider adding `#[derive(Debug)]` or a manual implementation
 --> src/main.rs:6:1
  |
6 | pub struct Foo(Node);
  | ^^^^^^^^^^^^^^^^^^^^^
  |
note: the lint level is defined here
 --> src/main.rs:1:9
  |
1 | #![warn(missing_debug_implementations)]
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Desired output

```Shell
No warnings
```

### Rationale and extra context

suggestion will cause compilation failure

```Shell
error[E0277]: `Node` doesn't implement `Debug`
 --> src/main.rs:7:16
  |
6 | #[derive(Debug)]
  |          ----- in this derive macro expansion
7 | pub struct Foo(Node);
  |                ^^^^ `Node` cannot be formatted using `{:?}`
```

**Comment by alexschrod** [comment]
> warning: type does not implement `Debug`; consider adding [...] a manual implementation

I've done several of these manual implementations and would very much appreciate the warning continues to exist and suggest you do this. If you don't want `Debug` for a type, put `#[allow(missing_debug_implementations)]` on it.

**Comment by J-ZhengLi** [comment]
well, since this is not really an issue, I'm closing it now~ 😄
