### ISSUE TITLE
nightly 2023-12-25 is missing

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#119312]
`$date` `Di 26. Dez 08:43:09 CET 2023`
`  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.77.0-nightly (bf8716f1c 2023-12-24)`
Seems that nightly ..25 should have been released by now..?

**Comment by Nilstrieb** [comment]
I can install it. `rustup toolchain install nightly-2023-12-25` installs one built on 2023-12-24, `rustup toolchain install nightly-2023-12-26` installs one built on 2023-12-25. The usual off-by-one error.

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/promote-release/issues/77
