### ISSUE TITLE
dyn Upcasting for unsized generics

### ISSUE THREAD

**Issue by dhardy** [rust-lang/rust#119360]
This fails:
```rust
#![feature(coerce_unsized)]
use std::ops::CoerceUnsized;
use std::any::Any;

fn box_to_any<T: Any + ?Sized>(x: Box<T>) -> Box<dyn Any>
where
    T: CoerceUnsized<dyn Any>,
{
    x as Box<dyn Any>
}
```
with:

> error[E0277]: the size for values of type `T` cannot be known at compilation time
>
> note: required for the cast from `Box<T>` to `Box<(dyn Any + 'static)>`

[Dyn upcasting](https://github.com/rust-lang/rust/issues/65991) adds support for upcasting trait objects `dyn A` where `A: Any` to `dyn Any`, but not just *any* type (e.g. `str` cannot be cast to `dyn Any`).

For whatever reason, the bound `T: Any + ?Sized` is not enough to support the cast: `[i32]` implements `Any` (strange) yet cannot be cast to `dyn Any` (if it could this would break memory safety since the impl of `Any` returns a single `TypeId` for all `[i32]` regardless of length).

The additional `T: CoerceUnsized<dyn Any>` *looks* like it should be enough to satisfy the coercion in the method, yet it is not. It *should* be?

I guess this should be categorised as a bug in #18598, but it *could* be a bug in #65991 or even a feature request.

**Comment by dhardy** [comment]
## Motivation

Enable `Box::downcast` to be generic over all types which can support it: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=863a1a05e024c3f2d73cba48690ae551. (This would of course be breaking and a separate issue/RFC. Just wanted to add for context.)

**Comment by compiler-errors** [comment]
The correct bound is `T: Unsize<dyn Any>`

**Comment by dhardy** [comment]
Thanks
