### ISSUE TITLE
we can combine struct and enum

### ISSUE THREAD

**Issue by i1kaaasra** [rust-lang/rust#119320]
hello ... I love ....
I am new and beginner rust developer when I learn enum and struct I think we can combine struct and enum to just struct and delete enum for ever and just have struct...

**Comment by fmease** [comment]
Structs and enums are related but still conceptually distinct features. I would recommend reading up on [Chapter 5:  Structs](https://doc.rust-lang.org/stable/book/ch05-00-structs.html) and [Chapter 6: Enum](https://doc.rust-lang.org/book/ch06-00-enums.html) of the book.
It's true that [type-theoretically](https://en.wikipedia.org/wiki/Type_theory) structs are 1-variant enums (however, it would be very unwise to get rid of enums in favor of structs as you have suggested). So the following struct

```rs
struct S { f: T }
```

can be represented via

```rs
enum E { S { f: T } }
```

Except that in Rust, you would now need to use pattern matching to access the field `f` (which is now public btw) which is not as ergonomic meaning structs have reason to be in the language as a separate kind of item.

**Comment by fmease** [comment]
In the future, please consider opening a thread over at https://internals.rust-lang.org/ or rust-lang.zulipchat.com/ first for questions about language design and/or language proposals.

I also recommend you to try out support forums like Discord first. This issue tracker is mostly for bugs found in the Rust compiler.

**Comment by fmease** [comment]
Closing as invalid.
