### ISSUE TITLE
rustup is slow

### ISSUE THREAD

**Issue by erikschul** [rust-lang/rust#119496]
Running `rustup update` and `rustup target add x86_64-unknown-linux-gnu` is very slow for me.

```
info: latest update on 2023-12-28, rust version 1.75.0 (82e1608df 2023-12-21)
info: downloading component 'rust-src'
info: downloading component 'cargo'
  1.7 MiB /   7.7 MiB ( 22 %)  40.8 KiB/s in 41s ETA:  2m 29s 
```

It eventually fails. Sometimes `rustup update` works and downloads at high speed, e.g. 100Mbit+.
I suspect there's a problem with the mirrors/servers that rustup uses?
If I should take a wild guess, maybe there is DNS roundrobin load balancing, and the DNS response is then cached/pinned to a slow/unresponsive server, until the DNS cache expires.
I worry about downtime in production. There doesn't seem to be any way to choose between mirrors? Are there even any mirrors?

**Comment by Nilstrieb** [comment]
I assume your internet speed is usually faster than 40KiB/s. Has this happened before, and can you reproduce it? Or did the slowness go away? Where in the world are you, roughly?

I created a topic on Zulip where the infra team resides, let's continue the discussion there: https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/slow.20rustup.20downloads

**Comment by erikschul** [comment]
Thanks. 
Yes, for other uses, normally gigabit speeds, i.e. 50-100 megabyte/s.
Perhaps it would be useful if rustup would print which mirror it uses, for future debugging.

**Comment by takkuumi** [comment]
Here is a 1000M bandwidth mirror, which was created by a team from ByteDance. [rsproxy](https://rsproxy.cn/#getStarted)

**Comment by erikschul** [comment]
@jdno It works correctly now, but it's good to have these commands to try with if the issue occurs again. Thanks a lot!

**Comment by erikschul** [comment]
@jdno FYI, I've had similar issues before with Fastly CDN (according to ip whois), when downloading Kubernetes binaries.
From two separate networks in two different countries, so I'm not sure it's a peering issue.
https://github.com/kubernetes-sigs/downloadkubernetes/issues/508

**Comment by jdno** [comment]
Thanks for the update!

We have created a tracking issue to get a bit more visibility into the performance of the CDNs. But it's really difficult to debug from our perspective, since there are a lot of variables at play. Most importantly, the connection between the user and the closes point-of-presence (POP), whether the artifact is already in the POP's cache, and how far away the POP is from our S3 bucket if it's not. It's very hard to test this for all the different locations and ISPs in the world. 😞 

Glad to hear that it is working now!

**Comment by erikschul** [comment]
@jdno I can imagine. My only advice would be to observe if ever a download transmits at <100 kB/s. That should be unusual on most modern connections. And with multiple datapoints, it might reveal when and where it happens.

**Comment by wmorgue** [comment]
@jdno thank you.
From 160 KiB/s to 30 MiB/s

**Comment by erikschul** [comment]
@jdno Are the packages signed?
I assume using a third party mirror, such as rsproxy, is unsafe?

**Comment by JakkuSakura** [comment]
It used to work perfectly, but this happened to me suddenly today. Using the cloudfront server solves the issue.

**Comment by erikschul** [comment]
@jdno Does `rustup` verify signatures? If not, using a third party mirror like `rsproxy` could be dangerous.
(And even if it does validate signatures, a vulnerability might bypass it, for injecting malware into CICD pipelines)

**Comment by eproxus** [comment]
Can confirm that using the Cloudfront CDN works, but the default not (Fastly?). I'm in Germany on a Deutsche Telekom DSL connection (I think Deutsche Telekom are somewhat known for bad peering agreements).

**Comment by TheShiningBoots** [comment]
Yeah cloudfront is much much faster, went from 25.6kb 38MiB.

**Comment by ENCRYPTEDFOREVER** [comment]
Using cloudfront CDN solved the issue for me too

**Comment by iirekm** [comment]
What was it closed? Problem still exists.
`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y` takes about 30 minutes with a good internet connection where download speeds are normally >100 MiB/s

**Comment by erikschul** [comment]
@iirekm I've reopened, but the issue is so old by now that I doubt it'll get any attention. And there are currently 10k open issues.

So the answer is probably: prioritization.

**There is a workaround, so use it.**

Do I hate it? Absolutely. But it's free!

**Comment by kotenok2000** [comment]
It  is currently very slow, for me. It is downloading from 151.101.66.137

![Image](https://github.com/user-attachments/assets/c6fffba5-411d-48b1-ab47-4658edb4ccbf)

**Comment by erikschul** [comment]
Could this be related to VPN? Debian mirrors are sometimes extremely slow, which is related to rate limiting of the IP address. Maybe Fastly is doing the same.

**Comment by kouhe3** [comment]
![Image](https://github.com/user-attachments/assets/8d8f1729-0eda-46cd-a16a-4acd0fabd87d)

slow here. download from rsproxy .

i need to ctrl c then rerun command to fast download each file.

PS. this source is unstable, i often got 504 timeout

**Comment by Babakinha** [comment]
> You can test if this is the case by explicitly downloading from one of the two CDNs:
> 
> ```
> RUSTUP_DIST_SERVER=https://cloudfront-static.rust-lang.org rustup update
> # or
> RUSTUP_DIST_SERVER=https://fastly-static.rust-lang.org rustup update
> ```
> (Please not that the URLs are implementation details and can change in the future.)
> 
> Does one work better than the other for you?

Can confirm its a fastly issue, here in brasil at least, had the same issue, it was fast at the start, unbeareable after that, with cloudfront it just worked.
