### ISSUE TITLE
the section name in object file is not completely displayed if the --emit llvm-ir option is not added

### ISSUE THREAD

**Issue by cathy-sjh** [rust-lang/rust#119403]
I tried this code:

```rust
pub fn add(left: usize, right: usize) -> usize {
    left + right
}

fn main() {
   let x = add(1, 2);
   println!("x = {}", x);
}
```

The size of the target object file generated by the compilation command **rustc simple.rs --emit obj** and **rustc simple.rs --emit obj --emit llvm-ir** is different. To be exact, the size of the .strtab section is different.

`rustc simple.rs --emit obj` command: 
```
readelf -SW simple.o 
There are 50 section headers, starting at offset 0x1998:

Section Headers:
  [Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
 ...
  [ 1] .strtab           STRTAB          0000000000000000 001260 000734 00      0   0  1
....
  [25] .data.rel.ro..L__unnamed_1 PROGBITS        0000000000000000 000320 000030 00  WA  0   0  8
....
```

`rustc simple.rs --emit obj --emit llvm-ir` command: 
```
readelf -SW simple.o 
There are 50 section headers, starting at offset 0x1a88:

Section Headers:
  [Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
  ...
  [ 1] .strtab           STRTAB          0000000000000000 001260 000823 00      0   0  1
....
  [25] .data.rel.ro..Lvtable.0 PROGBITS        0000000000000000 000320 000030 00  WA  0   0  8
....
```

Only when the **--emit llvm-ir** compilation option is added, the section name is displayed completely in the object file, so the string table is correspondingly larger. The full name of the display sectionis sometimes important.

`rustc --version --verbose`:
```
rustc 1.74.0 (79e9716c9 2023-11-13)
binary: rustc
commit-hash: 79e9716c980570bfd1f666e3b16ac583f0168962
commit-date: 2023-11-13
host: aarch64-unknown-linux-gnu
release: 1.74.0
LLVM version: 17.0.4

```
This problem can be reproduced in both stable and nightly.

**Comment by bjorn3** [comment]
By default `-Zfewer-names=yes` is used for faster compilation. However when passing `--emit llvm-ir` or `--emit llvm-bc` or when using ASAN or MSAN `-Zfewer-names=no` is used by default to make the llvm ir more readable cq reported errors more useful.

https://github.com/rust-lang/rust/blob/fcfe05aa7538fbb18fc3baff9aabdf9a1cd14b1e/compiler/rustc_session/src/session.rs#L762-L772

**Comment by jieyouxu** [comment]
Closing this issue as intentional behavior.
