### ISSUE TITLE
rustdoc UI: "This example is not tested" popup is below sidebar

### ISSUE THREAD

**Issue by lukas-code** [rust-lang/rust#119472]
For example [here](https://doc.rust-lang.org/nightly/core/sync/atomic/struct.AtomicBool.html#method.as_ptr):

![image](https://github.com/rust-lang/rust/assets/26522220/2db87866-6a4f-471d-87c9-b5b9d1b49fde)

How it used look:

![image](https://github.com/rust-lang/rust/assets/26522220/9bebc09e-5265-4543-aaf6-93fce9218bf6)

### Meta

Happens on current nightly and beta (1.76).

@rustbot label T-rustdoc A-rustdoc-ui regression-from-stable-to-beta

**Comment by fmease** [comment]
Fixed in #119477.
Backported in #119743.
Closing as completed.
