### ISSUE TITLE
methods of re-exported private items are not placed in the search index

### ISSUE THREAD

**Issue by SiegeLord** [rust-lang/rust#11943]
E.g. take this crate:

~~~rust
#[crate_id="test"];

pub use private::Foo;

mod private
{
	pub struct Foo;
	impl Foo
	{
		pub fn test_method() {}
	}
}
~~~

After generating the documentation with it, you cannot search for the `test_method` method. This can be manually verified by grepping for it in the `doc/test/search-index.js` file.

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/16767 was merged, so i'm giving this a close.
