### ISSUE TITLE
Rust Playground not working, JSON parsing error generated

### ISSUE THREAD

**Issue by dcabanis** [rust-lang/rust#119576]
When I go the the rust-playground and run the default Hello World program, I am getting the same error today (linux/win11) using both Edge and chrome.

Unexpected token '<', "<!DOCTYPE "... is not valid JSON

Using firefox I get the error:

JSON.parse: unexpected character at line 1 column 1 of the JSON data

I never had such an issue with the tool before. Can someone look into this?

Kindly

**Comment by saethlin** [comment]
https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/playground.20incident.202024-01-04/near/411188605

> The SSL certificate for `play-1` was expired. Pretty sure that caused the proxy connection to just permanently fail.

I think everything is working again, it looks like Jake noticed the problem and fixed it about an hour and a half after you opened this issue.

**Comment by Nilstrieb** [comment]
closing this issue, tracking the issue further will be done in the zulip thread.
