### ISSUE TITLE
Unwinding on mac64 is broken with fp elim

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#11954]
We recently turned on frame pointer elimination in our LLVM codegen. This is apparently causing many problems with unwinding on mac64 platforms. This isn't quite deterministic, but some patches trigger this regularly.

For now, I'm adding an exception for mac64 platforms.

**Comment by steveklabnik** [comment]
@alexcrichton what about now? I can't find that code you linked to anymore, it would seem that `src/librustc_back/target/apple_base.rs` (which I think is the new version) mentions nothing about this.

**Comment by alexcrichton** [comment]
Ah it just [moved over here](https://github.com/rust-lang/rust/blob/9e9c83b8994fab4f69fc75838c8c856b57caa5d1/src/librustc_back/target/x86_64_apple_darwin.rs#L16) (still disabled)

**Comment by steveklabnik** [comment]
Triage: no longer disabled https://github.com/rust-lang/rust/blob/691eba1358fc3c9c7a8033314a4112d43680c128/src/librustc_back/target/i686_apple_darwin.rs
