### ISSUE TITLE
`const_trait_impl` does not keep track of closures

### ISSUE THREAD

**Issue by fmease** [rust-lang/rust#119687]
The feature `effects` doesn't track the constness of closures.
~~This currently type-checks but it shouldn't:~~
**Update**: We (*project-const-traits*) have decided that we do want the code below to compile. It still holds true that `effects` doesn't track the constness of closures yet but we now plan on removing the need for `const || {}` (and remove the whole feature `const_closures` at some point) and want to rely on effect inference to make it work. Please see [this Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/146212-t-compiler.2Fconst-eval/topic/const.20closures/near/411647758).

```rs
#![feature(effects)]
const fn f() { (|| {})() }
```

However, the following definitely shouldn't compile:

```rs
#![feature(effects)]
const fn f() { (|| println!())() }
```

Without `effects`, they get rejected early with `error[E0015]: cannot call non-const closure in constant functions`.

[See also this Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/146212-t-compiler.2Fconst-eval/topic/effects.20.26.20non-const.20closures/near/411498604).

**Comment by fmease** [comment]
cc [this other Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/146212-t-compiler.2Fconst-eval/topic/const.20closures/near/411647758).

**Comment by fmease** [comment]
@obeis Have you read [this Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/146212-t-compiler.2Fconst-eval/topic/const.20closures/near/411647758) yet? The plan has slightly changed. See also the updated issue description.

**Comment by obeis** [comment]
@fmease Yes, I checked it out.

**Comment by fee1-dead** [comment]
cc @rust-lang/project-const-traits

**Comment by fmease** [comment]
```rs
#![feature(const_trait_impl)]
const fn f() { (|| println!())() }
```

Gets correctly rejected.

Closing in favor of https://github.com/rust-lang/project-const-traits/issues/10
