### ISSUE TITLE
Cycle detected in async fn but not with -> impl Future

### ISSUE THREAD

**Issue by Ekleog** [rust-lang/rust#119727]
Here is the reproducer:
```rust
use std::future::Future;
use futures::FutureExt;

struct Object(Box<Object>);

trait Trait {
    fn iter(&self) -> impl Sized + Send + Future<Output = ()>;
}

impl Trait for Object {
    // Compiles
    #[cfg(any())]
    fn iter(&self) -> impl Sized + Send + Future<Output = ()> {
        async move {
            self.0.iter().boxed().await;
        }
    }
    
    // Does not compile
    #[cfg(all())]
    async fn iter(&self) {
        self.0.iter().boxed().await;
    }
}
```
[(playground link)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=2564aac88ec98fa41311cf2b8579ec0a)

Interestingly, if you swap the any/all, then the version with `-> impl Sized + Send + Future<Output = ()>` does compile properly.

So _something_ in `async fn` is not just desugared as `-> impl Sized + Send + Future`, but I'm not sure why that is?

Possibly related to:
- https://github.com/rust-lang/rust/issues/112175
- https://github.com/rust-lang/rust/issues/107320
- https://github.com/rust-lang/rust/issues/104343
- https://github.com/rust-lang/rust/issues/78649

**Comment by Ekleog** [comment]
Hmm just for my education, would it be possible for you to explain why the version with `-> impl Future { async move { ... } }` is expected to have a different behavior from the version with `async fn`? I'd love to understand which rules are different between the two versions, to avoid hitting this issue in the future.

(For some context, the non-reduced original issue was a struct that had basically a `Vec<Self>` member, and recursively called the functions by turning the futures into `Box<dyn Future>` to avoid the infinite type issue — and this did work with `-> impl Future { async move { ... } }` but not with `async fn`; so the obvious infinite recursion at runtime from the reproducer wasn't present then)

**Comment by traviscross** [comment]
It's not about the difference between `async fn` and `-> impl Future`, it's about the fact that in the `-> impl Future` case you explicitly added a `Send` bound.  If we remove that from the `-> impl Future` case then it fails similarly:

```rust
use core::future::Future;

struct Object(Box<Object>);

trait Trait {
    fn iter(&self) -> impl Future<Output = ()> + Send;
}

impl Trait for Object {
    fn iter(&self) -> impl Future<Output = ()> {
        //~^ ERROR cycle detected
        async move {
            Box::new(self.0.iter()).await;
        }
    }
}
```
