### ISSUE TITLE
Cannot Compile Rust in Docker Container

### ISSUE THREAD

**Issue by zhixinwen** [rust-lang/rust#119779]
I am trying to compile a project with `cargo build` on my Mac M2 laptop and it works fine.
If I try to compile it inside a linux x64 container it fails with random `can't find crate` failures.
The error for that specific crate would go away if I try again, but it would fail with some other crates.
Eventually I can get it work with multiple retries.
Not sure if it is a container issue or rust cross platform compile issue.

**Comment by clubby789** [comment]
Can you provide specific commands to reproduce this issue? It could just be an issue with Docker networking

**Comment by zhixinwen** [comment]
nvm, it turns out target cached is built in an older version of rustc and `cargo clean` would make it work.
One thing to improve is the old version error message is not printed unless I run `cargo build -v`, `cargo build` just prints not found error which is confusing.
