### ISSUE TITLE
Typo in /Cargo.toml

### ISSUE THREAD

**Issue by Kleinmarb** [rust-lang/rust#119780]
### Location

/Cargo.toml:67

### Summary

# The compiler-builtins crate cannot reference libcore, and it's own CI will |
------------------------------------------------------------------------------^------------------|
----------------------------------------------------------------------it's "its" not "it's"------|

**Comment by saethlin** [comment]
When you're editing a comment or anything on GitHub's UI, in the bar directly above the box you type in, there's a Preview button. And if it were me writing, I would put it in a code block because monospace is just easier to align things with.

**Comment by Nilstrieb** [comment]
Feel free to send in a PR fixing the typo :)

**Comment by Kleinmarb** [comment]
Ok wait i'll do that in a minute

**Comment by Kleinmarb** [comment]
I made a pull request fixing the typo, hope I did it fine since Im new to pull requests

**Comment by Nilstrieb** [comment]
You did, I approved it. Btw, you can add "fixes #119780" to your PR description so that this issue well closed automatically once the PR is merged.

**Comment by Kleinmarb** [comment]
Ok I'll do that next time thanks!
