### ISSUE TITLE
Tracking Issue for `proc_macro_c_str_literals`

### ISSUE THREAD

**Issue by novafacing** [rust-lang/rust#119750]
Feature gate: `#![feature(proc_macro_c_str_literals)]`

This is a tracking issue for C String literals in proc macros under #105723 and #118560, with an implementation in #119651.

This feature adds an API to construct a `proc_macro::Literal` C string directly.

### Public API

```rust
let lit: Literal = Literal::c_string(&CString::new("Hello, world!").unwrap());
```

### Steps / History

- [x] Implementation: #119651
- [x] Stabilization of #117472
- [ ] Final Comment Period (FCP)
- [ ] Stabilization of this API

### Unresolved Questions

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by novafacing** [comment]
`c_str_literals` have been re-stabilized, I think this can now be considered for stabilization.

**Comment by dtolnay** [comment]
@rust-lang/libs-api:
@rfcbot fcp merge

`Literal::c_string(&CString::new("Hello, world!").unwrap())` constructs the literal `c"Hello, world!"`.

C-string literals stabilized recently in Rust 1.77.
