### ISSUE TITLE
Review tests in tests/ui/numbers-arithmetic for duplicates

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#119851]
https://github.com/rust-lang/rust/pull/119432 adds extensive tests for our overflow lint; as far as I can see they subsume most of what we have in tests/ui/numbers-arithmetic, so the old tests can be deleted. Yay for having the tests nicely grouped in one file rather than spread across a dozen files!

So, once #119432 lands, we should do a review of these tests and remove duplicates.

Cc @gurry

**Comment by mj10021** [comment]
@RalfJung if there are some tests in numbers-arithmetic that are not exactly represented in the new tests, should I just add them to the new test file once its merged to clean up as much as possible?

**Comment by RalfJung** [comment]
I think that depends on whether they would fit the existing test files or not. The first step would be to determine whether there are any such tests.

**Comment by mj10021** [comment]
hey any idea when the PR will get merged? it will be a lot easier to reorganize the tests then

**Comment by RalfJung** [comment]
It's waiting on a team decision. The teams are busy so it's hard to predict when this will get to the top of their queue.

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/pull/119432 has landed, so the review and cleanup work can commence. :) @mj10021 are you still planning to take a look a this?

**Comment by mj10021** [comment]
> #119432 has landed, so the review and cleanup work can commence. :) @mj10021 are you still planning to take a look at this?

Oh, yes definitely, thanks for the update.  I'm going away for a week, so I will start today but might not be able to finish until I get back.

**Comment by RalfJung** [comment]
No worries, this is not urgent. :)
