### ISSUE TITLE
[ffi] how to change string in struct on c side? need some help : )  plz

### ISSUE THREAD

**Issue by 1369521908** [rust-lang/rust#119887]
when i get (or change) a char* in struct on c side, there is something different in rust and golang

i compile the c code to dll and call it from rust and golang (all language use the same dll)

here is my code

# c side native test (it work well)
![image](https://github.com/rust-lang/rust/assets/32727597/4eee0eb3-eb90-4085-8fbf-928346663f94)

# rust side (when i debug, crash on c side) is that something worng with my code? (learning rust btw XD)
1. code and debug point
![image](https://github.com/rust-lang/rust/assets/32727597/d707c7ff-5a4c-47dd-a3ee-d8dd1b856c9c)
![image](https://github.com/rust-lang/rust/assets/32727597/2f2aea71-24ea-43b2-be59-0f5780469500)
2. resume debug point and i get crash
![image](https://github.com/rust-lang/rust/assets/32727597/32f38a46-ddce-4c4a-bb8f-2e397c1700ea)
![image](https://github.com/rust-lang/rust/assets/32727597/8cdac02a-020e-44ad-a745-b89b05c1eb3b)

3. c side logs out
![image](https://github.com/rust-lang/rust/assets/32727597/97de3bb8-1fe3-4d80-9fbe-a8c7441f2fc1)
4. keep resume debug point until program stop(Signal: SIGSEGV (Segmentation fault))
![image](https://github.com/rust-lang/rust/assets/32727597/3af3bd26-0a99-489a-a5d8-bcf1ba66553a)

# golang side (it work well)
![image](https://github.com/rust-lang/rust/assets/32727597/7a837f26-9191-48f1-acd6-5317aee564c2)

**Comment by Nilstrieb** [comment]
Hi! The issue tracker of this repository is not the right place for questions, it's about problems with the Rust language itself.
For getting help using Rust, I recommend visiting the https://users.rust-lang.org forum instead. Alternatively, people on the official or unofficial community Discord server may also be able to help.

**Comment by 1369521908** [comment]
> Hi! The issue tracker of this repository is not the right place for questions, it's about problems with the Rust language itself. For getting help using Rust, I recommend visiting the https://users.rust-lang.org forum instead. Alternatively, people on the official or unofficial community Discord server may also be able to help.

Thankfully~

**Comment by 1369521908** [comment]
#[repr(C)]
struct RustObject {
    a: c_int,
    name: *mut c_char,
}

with #[repr(C)] on it, work well
