### ISSUE TITLE
regression: lifetime bound not satisfied

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#119874]
```
[INFO] [stdout] error[E0478]: lifetime bound not satisfied
[INFO] [stdout]   --> /opt/rustwide/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/schema_analysis-0.3.4/src/traits.rs:53:5
[INFO] [stdout]    |
[INFO] [stdout] 53 |     fn coalesce_any(&mut self, other: Box<dyn Any + 'a>) -> Option<Box<dyn Any>> {
[INFO] [stdout]    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stdout]    |
[INFO] [stdout] note: lifetime parameter instantiated with the lifetime `'a` as defined here
[INFO] [stdout]   --> /opt/rustwide/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/schema_analysis-0.3.4/src/traits.rs:52:6
[INFO] [stdout]    |
[INFO] [stdout] 52 | impl<'a, T: Coalesce + 'a> CoalesceAny for T {
[INFO] [stdout]    |      ^^
[INFO] [stdout]    = note: but lifetime parameter must outlive the static lifetime
```

https://crater-reports.s3.amazonaws.com/beta-1.76-3/beta-2024-01-09/gh/lizelive.gusteau/log.txt

**Comment by compiler-errors** [comment]
This is expected, due to the fact that the IMPLIED_BOUNDS_ENTAILEMENT lint turned into a hard error, https://github.com/rust-lang/rust/pull/117984

It was fixed in schema_analysis 0.5

**Comment by compiler-errors** [comment]
Biogarden and gdrust are also regressions from that same root cause, see referenced PRs that lcnr opened in the thread of https://github.com/rust-lang/rust/issues/105572 . gdrust seems unmaintained, so that never got a fix.

**Comment by Mark-Simulacrum** [comment]
Thanks! I filtered the 2000+ rustc-serialize reverse-deps out of the regressions but not these. I think we can close this issue then, we'll definitely call out the hard error in release notes.
