### ISSUE TITLE
regression: Invalid Type in proc macro

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#119876]
* https://crater-reports.s3.amazonaws.com/beta-1.76-3/beta-2024-01-09/gh/mattngaw.patroclus/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.76-3/beta-2024-01-09/reg/const-random-0.1.17/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.76-3/beta-2024-01-09/reg/ktls-4.0.0/log.txt
* 

```
[INFO] [stdout] error: proc-macro derive panicked
[INFO] [stdout]    --> src/position/zobrist.rs:119:34
[INFO] [stdout]     |
[INFO] [stdout] 119 |         let prbs = const_random!([u8; 6144]);
[INFO] [stdout]     |                                  ^^^^^^^^^^
[INFO] [stdout]     |
[INFO] [stdout]     = help: message: Invalid type
```

**Comment by compiler-errors** [comment]
This is another breakage in https://github.com/rust-lang/rust/issues/119875#issuecomment-1888270342

**Comment by Mark-Simulacrum** [comment]
Closing for the same reasons as https://github.com/rust-lang/rust/issues/119875#issuecomment-1898723615.
