### ISSUE TITLE
Allow specification of starting index in str::find

### ISSUE THREAD

**Issue by xales** [rust-lang/rust#11986]
The find family of string functions currently do not have a way of specifying the starting index. This makes it difficult to find the nth occurrence of something.

cc @cmr

**Comment by steveklabnik** [comment]
This is bad unicode practice, and changes to the libraries will need an RFC, so yes, closing.

**Comment by stej** [comment]
I tried to use the proposed solution, but it looks that the API changed significantly. What is the current way how to find a string starting from given index?
