### ISSUE TITLE
performance hit of 1000% - 2000% on generated code in Windows Environments

### ISSUE THREAD

**Issue by rafaga** [rust-lang/rust#119982]
I'm developing a multi platform desktop application with egui, I usually make my programming on macOS but when I Tested my code on windows in the past month, I was astonished with the fact my application was running like 10-20 times slower on windows Machines, making the application unusable.

the problem just happen when I put the code on a library and import such library on a second binary project and on Windows x86-64 with MS VC, if I copy and paste the same code on the same binary project the problem disappears.

its not happening on MacOS, and I haven't tested on Linux

just to being clear 

- I'm using `--release` flag on both machines, 
- it is running on native environments. 
- no containers, no virtualization.
- and Its the same code executing using a library and in the project locally

Thinking that the problem was on my end.
I proceeded to make the following changes.

- removed unnecessary dependencies
- remove the most part of the clone() operations
- used Arc to make some clone operations cheaper.

The code its here: https://github.com/rafaga/bugtest.git 
its a little complex to put it here because its a widget

you can run the code using the lib linking using the following command `cargo run --release --features=as_lib,puffin` 
and If you want to check how it behaves when it is linked locally use the following command `cargo run --release --features=as_file,puffin` 

I expected to see this happen: more or less the same performance on both modes

Instead, this happened: I'm experimenting a performance hit at least of 1000% on the same code

still occurring on nightly 1.77

```
rustc 1.75.0 (82e1608df 2023-12-21)
binary: rustc
commit-hash: 82e1608dfa6e0b5569232559e3d385fea5a93112
commit-date: 2023-12-21
host: x86_64-pc-windows-msvc
release: 1.75.0
LLVM version: 17.0.6
```
running as library
![imagen](https://github.com/rust-lang/rust/assets/1034690/463356bf-a48b-4b9e-a4c2-ac0b990a880d)

running as local
![imagen](https://github.com/rust-lang/rust/assets/1034690/4f0e8242-53f0-4532-a26d-0ffe5eda7570)

Append profiling for further reference
[windows.as_lib.zip](https://github.com/rust-lang/rust/files/13933766/windows.as_lib.zip)
[windows.as_local.zip](https://github.com/rust-lang/rust/files/13933767/windows.as_local.zip)

</p>
</details>

**Comment by saethlin** [comment]
Does the Windows-specific regression go away if you set `RUST_BACKTRACE=0` or otherwise disable backtrace collection?

**Comment by saethlin** [comment]
At a glance at the profiles, it seems pretty clear that something is repeatedly calling `map_init`. What makes you think this is a Rust problem and not a problem with the library you are using?

**Comment by rafaga** [comment]
Because running directly on the local project (and not as a library dependence , using the same computer) doesn't affect the performance at all

Because on macOS this performance doesn't occur. It doesn't matter if the code its executed in a library

Im running the same code and just on windows and loading as dependencies (library) has this effect

The map init is being called countiounsly because it is a windget on inmediatte mode and every action refresh everything is  how inmediate mode works

**Comment by workingjubilee** [comment]
> And in macOS this doesn't happen. doesn't matter if the code its executed in a library or locally. The map init is being called countiounsly because its a widget on immediate mode and every action refresh everything is how immediate mode works (in other words its an intended behavior )

MacOS? Are you testing the same architecture?

**Comment by rafaga** [comment]
The first test were on two machines the first a mac Intel (macBook Air 2019 retina 13") / and Windows computer HP Proobook (a reccent version), the Intel mac didn't show any significant slowdowns when testing the software, It was when I decide to test on a windows Machine (to see how was the UX) that i noticed the slowdown on windows Machines.

unfortunaly my intel mac its now defunct( dec 30th died, so I cannot test anymore). SO I don't think it is something related with CPU architecture

**Comment by workingjubilee** [comment]
There has been some off-side discussion of this and we feel like this should be brought to the attention of egui. I think this could be a bug in rustc, personally, but I think the egui contributors may be better able to diagnose the problem, unless you can find a way to repro this without egui. This is hard to minimize.

**Comment by rafaga** [comment]
this was reported previously at egui https://github.com/rust-lang/rust/issues/119982#issuecomment-1891161073 emilk said that It doesnt sees like its an egui issue

**Comment by workingjubilee** [comment]
That's the problem: even if it's "not an egui issue", it's quite probable the code that is being oddly regressed is in egui, and we need a minimization that's preferably _slightly_ less than "all of egui". But if it truly has nothing to do with egui, and the fact that these CPUs are probably different microarchitectures isn't the deciding factor, then it could be replicated without using egui.

**Comment by rafaga** [comment]
Ok, let me try If I can Isolate this evenmore (i have discarded like 96% of my code already)

**Comment by RossSmyth** [comment]
I am sorry friend, but I cannot replicate your results. My process:

1. Run `puffin_viewer --url 127.0.0.1:8585`
2. Run `cargo run --release --features=as_file,pu
[profile.zip](https://github.com/rust-lang/rust/files/13944240/profile.zip)
ffin`
3. I do not see the extreme regression you seem to see.
![image](https://github.com/rust-lang/rust/assets/18294397/3b4f6570-0d2c-49ef-be96-66ef2538f95a)

This is using Rust 1.75.0 on Windows 10 Version 10.0.19045 Build 19045 with an AMD 1700X & Nvidia 2060 Super.
[profile.zip](https://github.com/rust-lang/rust/files/13944241/profile.zip)

**Comment by RossSmyth** [comment]
Oh I misread it, it's only when it's a library you are saying that the regression occurs?

**Comment by rafaga** [comment]
run it with `cargo run --release --features=puffin,as_lib`

**Comment by RossSmyth** [comment]
Ok as a library it is definitely slower. 
![image](https://github.com/rust-lang/rust/assets/18294397/7b6ccfa4-5a18-4955-8af5-fd96d1a38120)
[lib_profile.zip](https://github.com/rust-lang/rust/files/13944342/lib_profile.zip)

One thing that I notice is that there are many [WindowEvent::CursorMoved](https://docs.rs/winit/latest/winit/event/enum.WindowEvent.html#variant.CursorMoved) winit events. While in the local version there are not. The local version uses [DeviceEvent::Motion](https://docs.rs/winit/latest/winit/event/enum.DeviceEvent.html#variant.MouseMotion)

And the local version the events are extremely fast

Local:
![image](https://github.com/rust-lang/rust/assets/18294397/d0f2136a-ce7e-429f-9a77-d29ed7f27137)

lib:
![image](https://github.com/rust-lang/rust/assets/18294397/03085a8d-fd11-41ad-998b-e1e54c141319)

I don't know enough about winit to say what this is or what it means. But it definitely isn't just the same program in a library.

**Comment by workingjubilee** [comment]
Interesting. Given both point to the same line in `eframe`, it's possible there is an optimization barrier.

**Comment by RossSmyth** [comment]
I have posted my results in the egui issue as well to see if some eyes can be put on it.

**Comment by saethlin** [comment]
If there is an optimization barrier, probably there is some cross-crate inlining that doesn't happen. Why that would only be the case in Windows is beyond me, but it should be pretty obvious in a native profiling tool that can show you which instructions the program spends its time executing. If this problem were on Linux I could pull that up in a pinch, but I don't know how to do that on Windows.

Alternatively, cross-crate inlining issues are usually fixed by setting
```
[profile.release]
lto = "fat"
```
I already tried this and it doesn't seem to have any effect, but again I have no idea what I'm doing on Windows so it wouldn't hurt for someone to check my work on that.

**Comment by workingjubilee** [comment]
Ah, that line is a macro invocation identifying a profiling target, reducing the likelihood the span is correct for identifying the problem.

Hmm. It seems very likely that something that should be tagged by the programmer with `#[inline]` is not, in fact, being tagged with `#[inline]`.

@rafaga @RossSmyth Can one of you do:
```powershell
set RUSTFLAGS="-Zcross-crate-inline-threshold=yes"
cargo run --release --features=puffin,as_lib
```

**Comment by workingjubilee** [comment]
Oh, disregard me, yes, fat LTO is also sufficient.

**Comment by RossSmyth** [comment]
In my test with fat lto it did not improve the regression. But I did not save the profile

**Comment by RossSmyth** [comment]
Ok here's an LTO profile. Still pretty high.
[lto_profile.zip](https://github.com/rust-lang/rust/files/13944757/lto_profile.zip)

![image](https://github.com/rust-lang/rust/assets/18294397/eabf7c6d-9758-4357-876d-0981bf6a3898)

**Comment by rafaga** [comment]
> Ah, that line is a macro invocation identifying a profiling target, reducing the likelihood the span is correct for identifying the problem.
> 
> Hmm. It seems very likely that something that should be tagged by the programmer with `#[inline]` is not, in fact, being tagged with `#[inline]`.
> 
> @rafaga @RossSmyth Can one of you do:
> 
> ```powershell
> set RUSTFLAGS="-Zcross-crate-inline-threshold=yes"
> cargo run --release --features=puffin,as_lib
> ```

@workingjubilee  still want to do this?

**Comment by RossSmyth** [comment]
Don't do it. It will only regress performance more.

**Comment by saethlin** [comment]
The fact that LTO has no effect makes me really doubt that this is an optimization barrier.

The `as_file` version uses `egui` through `eframe`. I see `libbug` has enabled a bunch of features for `egui` that `eframe` does not enable. Can you paste the line from `eframe`'s Cargo.toml into `libbug` and see if that corrects the discrepancy? In particular, I see this `deadlock_detection` feature which seems like it might slow things down.

**Comment by rafaga** [comment]
I tested the changes, the spedd seems to be improved maybe 40%, but it is still slow

![imagen](https://github.com/rust-lang/rust/assets/1034690/b65829fb-fa71-4d80-a526-f13c2d936803)

[windows.egui_features.zip](https://github.com/rust-lang/rust/files/13950592/windows.egui_features.zip)

**Comment by rafaga** [comment]
@saethlin @workingjubilee @RossSmyth it apparetly was resolved with @saethlin suggestions, I'm so sorry for wasting your valuable time debuggin this.
