### ISSUE TITLE
Type Check

### ISSUE THREAD

**Issue by Tahinli** [rust-lang/rust#119995]
I hope I'm in the right place.
This small code will replicate situation always. As you can see in the if x != 0 section code thinks that x is String. But as you can see I have match structure to check if I can convert String to u8 correctly, when result is "Ok", our String x is going to be overshadowed and will be u8, if our result is not okay, code just gives return so no code below it going to work. This means that only possibility to reach "if x != 0 " section is connected to being u8 for x, otherwise this code not going to work. But compiler and language server still thinks that x can be String.

I tried this code:

```rust
    let mut x = String::new();
    io::stdin().read_line(&mut x).unwrap();
    match x.trim().parse::<u8>()
        {
            Ok(value) =>
                {
                    let x:u8 = value;
                }
            Err(err_val) =>
                {
                    println!("{}", err_val);
                    return;
                }
        }

    if x != 0
        {
            println!("It's not zero");
        }
```
also this code gives same error:
```rust
    let mut x = String::new();
    io::stdin().read_line(&mut x).unwrap();
    match x.trim().parse::<u8>()
        {
            Ok(value) =>
                {
                    let x:u8 = value;
                }
            Err(err_val) =>
                {
                    let x:u8 = 0;
                    println!("{}", err_val);
                    return;
                }
        }

    if x != 0
        {
            println!("It's not zero");
        }
```

I expected to see this happen: Compiler should understand x is always u8 if it reaches the if section.

Instead, this happened: Compiler still thinks x as a String

### Meta

`rustc --version --verbose`:
```
rustc 1.75.0 (82e1608df 2023-12-21)
binary: rustc
commit-hash: 82e1608dfa6e0b5569232559e3d385fea5a93112
commit-date: 2023-12-21
host: x86_64-unknown-linux-gnu
release: 1.75.0
LLVM version: 17.0.6
```

<details><summary>Backtrace</summary>
<p>
error[E0277]: can't compare `String` with `{integer}`
  --> src/main.rs:21:10
   |
21 |     if x != 0
   |          ^^ no implementation for `String == {integer}`
   |
   = help: the trait `PartialEq<{integer}>` is not implemented for `String`
   = help: the following other types implement trait `PartialEq<Rhs>`:
             <String as PartialEq<Cow<'a, str>>>
             <String as PartialEq>
             <String as PartialEq<str>>
             <String as PartialEq<&'a str>>

For more information about this error, try `rustc --explain E0277`.
```
<backtrace>
```

</p>
</details>

**Comment by Nilstrieb** [comment]
Hi! The issue tracker of this repository is not the right place for questions, it's about problems with the Rust language itself.
For getting help using Rust, I recommend visiting the https://users.rust-lang.org forum instead. Alternatively, people on the official or unofficial community Discord server may also be able to help.

As a quick answer to your question, `x` is only shadowed _in the block where you defined the variable_, not afterwards. So in the line after your `let x: u8`, it's a `u8`, but as soon as you leave the block it refers to the outer variable again.

Btw, I can recommend using `cargo fmt` to format your code.

**Comment by Tahinli** [comment]
> Hi! The issue tracker of this repository is not the right place for questions, it's about problems with the Rust language itself. For getting help using Rust, I recommend visiting the https://users.rust-lang.org forum instead. Alternatively, people on the official or unofficial community Discord server may also be able to help.
> 
> As a quick answer to your question, `x` is only shadowed _in the block where you defined the variable_, not afterwards. So in the line after your `let x: u8`, it's a `u8`, but as soon as you leave the block it refers to the outer variable again.
> 
> Btw, I can recommend using `cargo fmt` to format your code.

Sorry I thought, I'm cleaver to find a situation that I can think better then compiler. But didn't know I was just overshadowing for local scope. Thanks for your reply.
