### ISSUE TITLE
Unexpected/wasteful handling of capacity by `vec.split_off(0)`

### ISSUE THREAD

**Issue by Zalathar** [rust-lang/rust#119913]
I was reviewing some code that uses `split_off(0)` in a loop to take the contents of a buffer, while leaving the buffer's capacity intact to be reused by subsequent iterations. When I double-checked the actual behaviour of `split_off(0)`, I was surprised to find that the vector returned by `split_off(0)` had a much larger capacity than was necessary to hold its contents.

Consider this example program: [(playground link)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=83f989373a54bab16f06f2e90325d9c6)

```rust
fn main() {
    let mut buffer = Vec::with_capacity(100);
    buffer.extend([1u8, 2u8]);
    println!("buffer capacity: {}", buffer.capacity());
    println!();
    
    let split_off_1 = buffer.split_off(1);
    println!("split_off_1 capacity: {}", split_off_1.capacity());
    println!("buffer capacity: {}", buffer.capacity());
    println!();

    let split_off_0 = buffer.split_off(0);
    println!("split_off_0 capacity: {}", split_off_0.capacity());
    println!("buffer capacity: {}", buffer.capacity());
    println!();
}
```

I expected that the `split_off_1` and `split_off_0` vectors would have similar capacities, since they each only hold one value. 

Instead, this happened:

```
buffer capacity: 100

split_off_1 capacity: 1
buffer capacity: 100

split_off_0 capacity: 100
buffer capacity: 100
```

The single-element vector produced by `split_off(1)` has a tight capacity of 1, but the single-element vector produced by `split_off(0)` has a wasteful capacity of 100, which is the same as the original vector's capacity.

(The method's documentation doesn't make any explicit promises about the capacity of the returned vector, so this isn't necessarily a *bug* per se, but it is a surprising behaviour.)

**Comment by Zalathar** [comment]
This behaviour seems to have been introduced by #76682, as an explicit optimization of the `split_at(0)` case, to avoid having to move the elements into a new allocation.

That PR notes that the new behaviour is compatible with the existing documentation, and notes some concerns about wastefully reallocating lots of capacity due to an outlier in how long the list gets, but I don't see any discussion of the capacity of the *returned* vector specifically.

At the very least, this behaviour probably deserves some warning in the docs, since the actual behaviour wastes more capacity than the “obvious” implementation would.

**Comment by Zalathar** [comment]
Looking again at the actual documentation, it says this:

> Returns a newly allocated vector containing the elements in the range `[at, len)`. After the call, the original vector will be left containing the elements `[0, at)` with its previous capacity unchanged.

If the returned vector is “newly allocated”, it's natural to assume that the new allocation would be reasonably tight, if not exact. But in the 0 case, the returned vector isn't newly allocated at all, since it steals its allocation from the existing vector.

**Comment by chenyukang** [comment]
When `at` is 0, directly return original vec as `other` here:
https://github.com/rust-lang/rust/blob/182537456bf3bbaed59a8ad9ee3a3b58cdce776d/library/alloc/src/vec/mod.rs#L2200

it's indeed a issue, but I haven't got a better solution, this change will fix the issue, but will also introduce extra copy:

```diff
         if at == 0 {
             // the new vector can take over the original buffer and avoid the copy
-            return mem::replace(
+            let mut other = mem::replace(
                 self,
                 Vec::with_capacity_in(self.capacity(), self.allocator().clone()),
             );
+            other.shrink_to(self.len());
+            return other;
         }
```

**Comment by chenyukang** [comment]
maybe we can use the strategy of `VecDeque`:
https://github.com/rust-lang/rust/blob/182537456bf3bbaed59a8ad9ee3a3b58cdce776d/library/alloc/src/collections/vec_deque/mod.rs#L1878-L1906

**Comment by Zalathar** [comment]
I think the realistic options are:

- Document the possibility of unexpected capacity/allocation behaviour when `at == 0`
- Remove the special handling for `at == 0`, and just use the same code path for `split_at(0)` and `split_at(n)`

In cases where `at` is unknown, I think it's surprising for 0 and 1 to behave very differently.

In cases where the user specifically wants the current `split_at(0)` behaviour, it may be better for the user to write `std::mem::replace` themselves.
