### ISSUE TITLE
Rust fails on the powerpc64le architecture with: thread 'main' panicked at ... called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by yurivict** [rust-lang/rust#119901]
See the failure logs:
* https://pkg-status.freebsd.org/foul2/data/132powerpc64le-quarterly/756e18783d8b/logs/git-cliff-1.4.0_1.log
* https://pkg-status.freebsd.org/foul2/data/140releng-powerpc64le-quarterly/756e18783d8b/logs/solana-1.17.9.log

rust-1.75.0
FreeBSD 13, 14

**Comment by nikic** [comment]
The unwrap is inside a build script, not rustc.

**Comment by yurivict** [comment]
I reported this to the 'ring' crate.
