### ISSUE TITLE
`allow_internal_unstable` does not work for `min_specialization`

### ISSUE THREAD

**Issue by clubby789** [rust-lang/rust#119950]
This also applies to proc macros
https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/.60SpecOptionPartialEq.60.20error

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=45d821a040bf825549fe07efa2c87572

```rs
#![allow(internal_features)]
#![feature(allow_internal_unstable)]

#[allow_internal_unstable(min_specialization)]
macro_rules! test {
    () => {
        struct T<U>(U);
        trait Tr {}
        impl<U> Tr for T<U> {}
        impl Tr for T<u8> {}
    }
}

test! {}
```
```rs
   Compiling playground v0.0.1 (/playground)
error[E0119]: conflicting implementations of trait `Tr` for type `T<u8>`
  --> src/lib.rs:10:9
   |
9  |         impl<U> Tr for T<U> {}
   |         ------------------- first implementation here
10 |         impl Tr for T<u8> {}
   |         ^^^^^^^^^^^^^^^^^ conflicting implementation for `T<u8>`
...
14 | test! {}
   | -------- in this macro invocation```

**Comment by compiler-errors** [comment]
There are probably also a bunch of other features that simply check validity with `tcx.features().feature_name` rather than checking for feature enablement a span. Would be cool to find out which ones do.

**Comment by Nilstrieb** [comment]
I would guess mst of them, all the ones that are not used in a macro in the standard library.
