### ISSUE TITLE
`.unwrap()` when expecting `fmt::Result`

### ISSUE THREAD

**Issue by uselessgoddess** [rust-lang/rust#120090]
Reading the compiler code (specifically the one responsible for mir output) I found these `.unwrap()`s where probably expected `?`.
https://github.com/rust-lang/rust/blob/6ae4cfbbb080cafea7f6be48ce47678ee057352c/compiler/rustc_middle/src/mir/pretty.rs#L1119-L1122

**Comment by clubby789** [comment]
Have you actually encountered an ICE due to this?

**Comment by uselessgoddess** [comment]
No, I just happened to find that. It's not a ICE, just a typo in the code
