### ISSUE TITLE
cast() can not cast to pointer type of unknown size

### ISSUE THREAD

**Issue by fredrik-hammar** [rust-lang/rust#120070]
When using `cast()` to cast to pointer to type of unknown size the compiler fails due to the target type being constrained as `Sized`, but casting with `as` works fine.

```rust
/// A newtype with alignment of at least `A` bytes
#[repr(C)]
pub struct Aligned<A, T>
where
    T: ?Sized,
{
    _alignment: [A; 0],
    value: T,
}

fn foo(ptr: *mut [u8]) -> *mut Aligned<u16, [u8]> {
    ptr as *mut Aligned<u16, [u8]>  // Compiles
}

fn bar(ptr: *mut [u8]) -> *mut Aligned<u16, [u8]> {
    ptr.cast() // Fails with: the size for values of type `[u8]` cannot be known at compilation time
}
```

I suggest adding `?Sized` to `U` in `cast()` signatures.

```rust
core::ptr::const_ptr
pub const fn cast<U>(self) -> *const U;
```

```rust
core::ptr::mut_ptr
pub const fn cast<U>(self) -> *mut U
```

### Meta
Tested with 1.75., 1.76.0-beta.5, 1.77.0-nightly in [Rust Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1c41b3bb7a67d002e8963437c8013c50)

**Comment by clubby789** [comment]
This isn't current possible (https://github.com/rust-lang/rust/issues/60602#issue-441192080)

**Comment by lukas-code** [comment]
> This isn't currently possible

It's not possible with `as` in a generic context, but it *is* possible with `transmute_unchecked` which AFAIK is equal to `as` for pointer-to-pointer casts.

[playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=b82373240b34f364ab17ec424e1f8b36)

**Comment by fredrik-hammar** [comment]
Thanks for the explanations! I see this is more complicated than I realized, but at least I learned something.
