### ISSUE TITLE
Raspberry Pi Zero 2 W - runs out of memory when installing rust

### ISSUE THREAD

**Issue by adzke** [rust-lang/rust#120049]
I tried this code:

```rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

```

I expected to see this happen:

Rust to be installed.

Instead, this happened:

Ran out of memory.

`rustc --version --verbose`:
```
Latest run version 64 bit
```

<details><summary>G'day rust team!
This is my first issue post ever, but i thought you would find this bug interesting. 

Using a Raspberry Pi Zero 2 W 64 bit, and install rust, you will find that after it's completed downloading, the installation will failure. It's failing due to memory related issues.

I solved this problem but increasing swap allocation on the Raspberry Pi.

Note: this doesn't failure installation on a 32 bit Raspberry Pi zero 1 w 

Thanks all!

AD

</summary>
<p>

</p>
</details>

**Comment by saethlin** [comment]
Setting `RUSTUP_IO_THREADS=1` has also helped me out of this in the past: https://github.com/rust-lang/rustup/issues/3125

I think the problem here is just that rustup's free memory calculation could use some improvement. But that's rustup issue, unfortunately.
