### ISSUE TITLE
use consistent terminology to describe moves

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#12002]
All types in Rust can be passed, assigned and returned via a shallow copy. If the type is not `Pod`, then *ownership* is moved to the destination of the copy. The source can be reinitialized and swaps are also possible. Bitwise copies of types to another location is also what vectors do via `realloc`.

Many places in the documentation, such as the the `Pod` trait and `NoPod` type currently describe this in terms of *implicit copies* This isn't a fully accurate way of describing the concept and implies that a move is performing something other than a shallow copy.

This is a continuous source of confusion on IRC, even for programmers familiar with C. It's trivial to give a C programmer the entire picture by explaining that Rust always does the same copy operation as C for passing/assigning/returning, but marks the source as moved from.

Most Rust users *do* have some concept about depth of copying and how memory works, so the explanation-by-analogy is unconvincing to them.

**Comment by steveklabnik** [comment]
"implcit copy" and "implicit copies" no longer exit, nor do the Pod and NoPod types. Therefore, I'm giving this a close. If there are specific places that this is oustdanding, let's change it, but I think all of these are currently gone.
