### ISSUE TITLE
Calling print from c++ doesn't work 

### ISSUE THREAD

**Issue by sagi21805** [rust-lang/rust#120191]
I tried this code:

```rust
#[no_mangle]
pub extern "C" fn print_array(ptr: *const c_int, len: usize){
    // Safety: We assume the pointer is valid for the specified length
    let slice = unsafe {
        std::slice::from_raw_parts(ptr as *const i32, len)
    };
    let rust_vector: Vec<i32> = slice.to_vec();
    
    for item in rust_vector{
        print!("{} ", item);
    }
}
```

```cpp
extern "C" void print_array(const int32_t* ptr, size_t len);

int main(){

    int size = 5;

    int32_t p[size] = {1, 3, 4, 54, 5};

    print_array(p, size);

}
```

I expected to see this happen: all the numbers in the pointer to print

Instead, this happened: there was no output and nothing was printed, i was able to "solve" the bug by putting a blank println!(""); at the end of the code and it seems to print everything, but without it, it printed nothing.

### Meta

`rustc --version --verbose`:
```
rustc 1.75.0 (82e1608df 2023-12-21)
binary: rustc
commit-hash: 82e1608dfa6e0b5569232559e3d385fea5a93112
commit-date: 2023-12-21
host: x86_64-unknown-linux-gnu
release: 1.75.0
LLVM version: 17.0.6

```

<details><summary>Backtrace</summary>
<p>

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
```

</p>
</details>

**Comment by the8472** [comment]
https://doc.rust-lang.org/nightly/std/macro.print.html

> Note that stdout is frequently line-buffered by default so it may be necessary to use [io::stdout().flush()](https://doc.rust-lang.org/nightly/std/io/trait.Write.html#tymethod.flush) to ensure the output is emitted immediately.
