### ISSUE TITLE
Tracking Issue for nested field access in offset_of

### ISSUE THREAD

**Issue by GKFX** [rust-lang/rust#120140]
Feature gate: `#![feature(offset_of_nested)]`

This is a tracking issue for the use of nested field access in offset_of. This is currently implemented with dot-separated fields, like in C. The original RFC for offset_of was https://github.com/rust-lang/rfcs/pull/3308.

### Public API

```rust
pub macro offset_of($Container:ty, $($fields:expr)+ $(,)?) { ... }

struct Struct {
    field: A,
}
struct A {
    a: ((u8, u8), bool),
}
const OFFSET: usize = offset_of!(Struct, field.a.0.1);
```

### Steps / History

- [x] Implementation: Included in initial offset_of implementation
- [x] Final comment period (FCP)[^1]
- [x] Stabilization PR - #128284

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by est31** [comment]
This has been split off from #106655 to get the non-nested `offset_off` macro stabilized sooner.

How the syntax for nested access should look like is still subject to discussion, especially also how it relates to enums.

Some links:

* [zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/.60offset_of!.60.20Syntax) about offset_of syntax
* [tracking issue](https://github.com/rust-lang/rust/issues/120141) for enums in `offset_of`. Contains some of the syntax discussion.
* The PR that added enum support to `offset_of` [also contains some syntax discussion](https://github.com/rust-lang/rust/pull/114208#issuecomment-1676249651).

**Comment by tgross35** [comment]
Could the top example be updated to show what `Struct` looks like?

**Comment by GKFX** [comment]
How close is this to stabilization? It looks like this is in use by the Linux kernel (https://lore.kernel.org/rust-for-linux/CAH5fLgjP98pS1wsP=YXP5Yr79Y62VF7XPKjbj+G75B3SOFt80g@mail.gmail.com/), as well as the standard library (for an enum): https://github.com/rust-lang/rust/blob/13e2d7295ea42f842e57100b6349388bfe609a11/library/core/src/option.rs#L787

Stabilizing this may restrict future changes to the offset_of parsing logic (compiler/rustc_parse/src/parser/expr.rs:1191, parse_floating_field_access). Currently this has enum variants treated the same as fields and (with parsing support only) array indexing using `[expr]` syntax.

**Comment by dingxiangfei2009** [comment]
Cross-posting stabilization report and request because the two feature gates need to stabilize together for best utility.

[Report](https://github.com/rust-lang/rust/issues/120141#issuecomment-2161507356)

cc @Darksonn @ojeda

**Comment by Amanieu** [comment]
@rfcbot fcp merge

**Comment by tmandry** [comment]
I'm unclear on whether this needs an RFC. I would defer to libs-api on that question though, since this is more a question of the syntax the macro supports than the capability it provides, and I think the syntax is more in the libs-api realm than the lang one (though it may be a bit of both).

Regarding the syntax, there is still an open question about supporting enum variants in the future. I'm personally okay with moving forward with this subset for now, especially since I can imagine a syntax I don't dislike: `offset_of!(Struct, (field.a as MyEnum::Variant).0.1)`. But I'm just documenting my thinking here for future reference; we should leave the bikeshed out of this issue if at all possible.

@rfcbot reviewed

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

I don't feel this requires an RFC. I think it is a natural extension to the existing functionality.

**Comment by pnkfelix** [comment]
@rfcbot reviewed
