### ISSUE TITLE
Inline asm! macro produces bad RISC-V assembly in release mode; possibly RVV related

### ISSUE THREAD

**Issue by silvanshade** [rust-lang/rust#120166]
The `core::arch::asm!` macro for inline assembly appears to incorrectly compile RISC-V code when compiling in `--release` mode.

I have verified this behavior with release `1.75`, `1.77`, and nightlies for most of Jan 2024.

The compiled code uses this `.cargo/config.toml`:

```toml
[build]
target = "riscv64gc-unknown-linux-gnu"

[target.riscv64gc-unknown-linux-gnu]
runner = "qemu-riscv64 -cpu rv64,v=true,vext_spec=v1.0"
linker = "clang-17"
rustflags = [
  "-C", "link-arg=-fuse-ld=lld-17",
  "-C", "link-arg=-march=rv64gcv",
  "-C", "link-arg=--target=riscv64-unknown-linux-gnu",
  "-C", "target-feature=+v",
]
```

Here is an example Rust program demonstrating the problem:

```rust
use core::arch::asm;

// Intended to load a vector of 4 x `1`s from the first four elements
// of argument array and set the last four elements of the array to
// the loaded vector. This should result in an array of 8 x `1`s.

#[no_mangle]
#[inline(never)]
unsafe fn bad(dst: *mut u32) {
    asm! {
        ".balign 4",
        "vsetivli zero, 4, e32, m1, ta, ma",
        "vle32.v v1, (a0)",
        "addi a0, a0, 16",
        "vse32.v v1, (a0)",
        clobber_abi("C"), // makes no difference
        options(nostack), // makes no difference
    }
}

fn main() {
    unsafe {
        let mut dst: [u32; 8] = [1, 1, 1, 1, 0, 0, 0, 0];
        bad(dst.as_mut_ptr());
    };
}
```

When run in debug mode with `cargo run`, the program runs correctly and exits.

When compiled and run in release mode with `cargo run --release` the program segfaults. In slightly more complex examples, it sometimes does not segfault, but still produces incorrect results.

Here is an analysis of the assembly output and an attempt to explain what is going wrong:

If we use `cargo-show-asm` and compile the code with `cargo asm --full-name --reduce-labels --simplify --everything` (this compiles for release mode by default) we get the following (comments inline and irrelevant blocks omitted):

```asm
bad:
	addi sp, sp, -16
	sd ra, 8(sp)
	#APP
	vsetivli zero, 4, e32, m1, ta, ma
	vle32.v v1, (a0)
	addi a0, a0, 16
	vse32.v v1, (a0)
	#NO_APP
	ld ra, 8(sp)
	addi sp, sp, 16
	ret

# Notice the code for initializing the array and storing
# the address in `a0` before calling `bad` seems to have
# been incorrectly optimized away.

min_riscv_inline_asm_bug::main::hd3bdf23df6954dc5:
	tail bad
```

However, if we compile this code code in debug mode with `cargo asm --dev --full-name --reduce-labels --simplify --everything` we get the following:

```asm
bad:
	addi sp, sp, -16
	sd ra, 8(sp)
	sd a0, 0(sp)
	#APP
	vsetivli zero, 4, e32, m1, ta, ma
	vle32.v v1, (a0)
	addi a0, a0, 16
	vse32.v v1, (a0)
	#NO_APP
	ld ra, 8(sp)
	addi sp, sp, 16
	ret

# Notice `a0` is initialized with the data for the
# array as expected before calling `bad`.

min_riscv_inline_asm_bug::main::h264ff82061add407:
	addi sp, sp, -64
	sd ra, 56(sp)
	li a0, 1
	sw a0, 8(sp)
	sw a0, 12(sp)
	sw a0, 16(sp)
	sw a0, 20(sp)
	li a0, 0
	sw a0, 24(sp)
	sw a0, 28(sp)
	sw a0, 32(sp)
	sw a0, 36(sp)
	addi a0, sp, 8
	sd a0, 40(sp)
	li a1, 8
	sd a1, 48(sp)
	call bad
	ld ra, 56(sp)
	addi sp, sp, 64
	ret
```

The `global_asm!` macro does not seem to have this problem. We show the same example below for comparison.

```asm
use core::arch::global_asm;

global_asm! {
    ".global good",
    "good:",
        ".balign 4",
        "vsetivli zero, 4, e32, m1, ta, ma",
        "vle32.v v1, (a0)",
        "addi a0, a0, 16",
        "vse32.v v1, (a0)",
        "ret",
}
extern "C" {
    #[no_mangle]
    fn good(dst: *mut u32);
}

fn main() {
    unsafe {
        let mut dst: [u32; 8] = [1, 1, 1, 1, 0, 0, 0, 0];
        good(dst.as_mut_ptr());
    }
}
```

First, `good` compiled with release mode (same command as before):

```asm
good:
	vsetivli zero, 4, e32, m1, ta, ma
	vle32.v v1, (a0)
	addi a0, a0, 16
	vse32.v v1, (a0)
	ret

# Unlike the release mode output for `bad`, here the
# array is properly initialized and defined before
# calling `good`. The only difference with the debug
# output (further below) is that the initialization code
# is optimized and uses RVV and vector register `v8`.

min_riscv_inline_asm_bug::main::hd3bdf23df6954dc5:
	addi sp, sp, -48
	sd ra, 40(sp)
	vsetivli zero, 4, e32, m1, ta, ma
	vmv.v.i v8, 1
	mv a0, sp
	vse32.v v8, (a0)
	sd zero, 16(sp)
	sd zero, 24(sp)
	call good@plt
	ld ra, 40(sp)
	addi sp, sp, 48
	ret
```

Finally, `good` compiled in debug mode:

```asm

good:
	vsetivli zero, 4, e32, m1, ta, ma
	vle32.v v1, (a0)
	addi a0, a0, 16
	vse32.v v1, (a0)
	ret


# The array is still initialized as expected but not
# optimized using RVV like the release mode `good`.

min_riscv_inline_asm_bug::main::h264ff82061add407:
	addi sp, sp, -64
	sd ra, 56(sp)
	li a0, 1
	sw a0, 8(sp)
	sw a0, 12(sp)
	sw a0, 16(sp)
	sw a0, 20(sp)
	li a0, 0
	sw a0, 24(sp)
	sw a0, 28(sp)
	sw a0, 32(sp)
	sw a0, 36(sp)
	addi a0, sp, 8
	sd a0, 40(sp)
	li a1, 8
	sd a1, 48(sp)
	call good@plt
	ld ra, 56(sp)
	addi sp, sp, 64
	ret
```

Possibly related: https://github.com/rust-lang/rust/issues/99359

There seems to be a problem with how `asm!` is handling the code before where function calls are made, and perhaps sometimes also incorrectly handling the prologue/epilogue for those functions.

I have mostly been trying to write RVV-related code, so most of the cases where I've encountered this problem are in that context. It may be the case that this issue is somehow specific to code that makes use of vector registers or is influenced by the relevant features for that being enabled.

I haven't seen reports of this for other architectures though so either way it seems to be RISC-V specific somehow.

```[tasklist]
### Tasks
```

**Comment by lukas-code** [comment]
All variables used by inline assembly must be explicitly passed into the inline assembly block via `in`, otherwise the optimizer will not see that they are used and optimize them out.

I do not know RISC-V assembly, but maybe something like this will work:
```rust
unsafe fn bad(dst: *mut u32) {
    asm! {
        ".balign 4",
        "vsetivli zero, 4, e32, m1, ta, ma",
        "vle32.v v1, (a0)",
        "addi a0, a0, 16",
        "vse32.v v1, (a0)",
        in("a0") dst, // <- passing the variable into the asm block here
    }
}
```

If you want to write entire functions in assembly, you need to use either `global_asm` (as you already noticed) or [naked functions](https://github.com/rust-lang/rust/issues/90957) (which are currently unstable).

**Comment by silvanshade** [comment]
Huh, not sure how I missed that for the above example.

You're right that fixing that here resolves this issue.

However, In the original code I was having problems with (which is much more complex, otherwise I would have included it directly), I did in fact have `in` placed appropriately, but I am still seeing unexpected and differences in behavior between debug and release when using `asm!` that is not present when using `global_asm!`.

I'll go ahead and close this and continue investigating until I can figure out what is going wrong.

Thanks for the response!
