### ISSUE TITLE
`mir_framework`: Problem with exports used by external tools

### ISSUE THREAD

**Issue by jubnzv** [rust-lang/rust#120130]
https://github.com/rust-lang/rust/commit/c16d3f32a489ef92e7812445ecf6dd6d5070439d has made it impossible to import some structures in `rustc_mir_framework` when implementing dataflow analyses in external tools.

When implementing `AnalysisDomain` for a custom dataflow problem, we can no longer import the `Forward` or `Backward` direction. [Here](https://github.com/paritytech/ink/blob/b05e7f213d1299e4e38552fba4d5d8c30b81fb3a/linting/extra/src/strict_balance_equality.rs#L227) is the source code of such an implementation. `Forward` is needed to set the `Direction` type of the `AnalysisDomain` trait. Previously, it [was available](https://github.com/rust-lang/rust/commit/c16d3f32a489ef92e7812445ecf6dd6d5070439d#diff-9df1d0ed501ba41308f30dad228a0406641a601edb478dda0af01943545fe1a6L26) under the `pub use` export, but for now it is [private](https://github.com/rust-lang/rust/commit/c16d3f32a489ef92e7812445ecf6dd6d5070439d#diff-9df1d0ed501ba41308f30dad228a0406641a601edb478dda0af01943545fe1a6R29).

The default implementation of the `AnalysisDomain::Direction` [is `Forward`](https://github.com/rust-lang/rust/blob/16fadb3f252bcfc5ee3f0be09472c9600a052202/compiler/rustc_mir_dataflow/src/framework/mod.rs#L99), so I can simply use the default value as a workaround. However, if I need to write a backward analysis, I must rewrite some parts of the framework in our source code because they cannot be imported.

There are other tools in the ecosystem that use that API, e.g.:
- [concrat](https://github.com/kaist-plrg/concrat/blob/64c17d4b949c647500bfecfd69a36e3a1ae6a942/src/dataflow/intra.rs#L104)
- [flowistry](https://github.com/willcrichton/flowistry/blob/3de29cb9da7505389f74c89fda28b4989f2316dd/crates/flowistry/src/infoflow/analysis.rs#L234)
- [aquascope](https://github.com/cognitive-engineering-lab/aquascope/blob/dbf32342ac15849d7697ab245b766ff46c2be617/crates/aquascope/src/analysis/permissions/utils.rs#L234)

These changes will make problems if they decide to update to the recent toolchain.

Could you please take a look at this matter? Are these changes intentional? Could we make some of the exports public again?
cc @nnethercote

**Comment by Nilstrieb** [comment]
Feel free to send in a PR to make it public again. Please add a comment on the items saying they're used by external tools.

**Comment by jubnzv** [comment]
I will double-check which of the removed imports might be beneficial for external tools and will send a PR if there are no objections.
