### ISSUE TITLE
`./x test bootstrap` shows curl progress bars

### ISSUE THREAD

**Issue by Teapot4195** [rust-lang/rust#120133]
## Steps to reproduce
1. clear the files under `build/cache/[date]` for those that aren't for your host triple.
2. clear the folders under `build` that isn't for your host triple. (e.g. `aarch64-apple-darwin` if building on `x86-64-windows-msvc`)
3. run `./x test bootstrap`
4. observe under a block of 37 tests, the curl progress bar shows up 6 times.

## Ideal solution
- When building the command for curl, possibly suppress the progress bar with `-s` in tests.
- Possibly don't download for those targets in the first place?
  - The tools being downloaded appear to be native (not cross), I can't really see a use given they can't run on a mismatched host triple.

If someone happens to know where these curl commands are being called from, that would be helpful :)

For whoever picks up this issue: I can't exactly mentor this issue but if you do need help, feel free to ping me on zulip.

Labeled easy since it doesn't look that difficult to fix.

@rustbot label +C-enhancement +E-easy

**Comment by AnmolSirola** [comment]
@Teapot4195 Can I take this issue.

**Comment by Teapot4195** [comment]
> @Teapot4195 Can I take this issue.

Sure

**Comment by Teapot4195** [comment]
Remember to claim via rustbot so other people know it's been taken :)

**Comment by onur-ozkan** [comment]
This will be fixed once #121091 is merged.

**Comment by Teapot4195** [comment]
> This will be fixed once #121091 is merged.

Yeah, I'll close as completed then
