### ISSUE TITLE
Miscompilation with -Zsanitizer=address

### ISSUE THREAD

**Issue by fintelia** [rust-lang/rust#120260]
I tried this code:

```rust
#[inline(never)]
fn unfilter(current: &mut [u8]) {
    current.iter_mut().reduce(|&mut prev, curr| {
        *curr = curr.wrapping_add(prev);
        curr
    });
}

fn main() {
    let mut data = [255, 0, 18, 243, 13, 240, 255, 0, 4];
    unfilter(&mut data);
    assert_eq!(data, [255, 255, 17, 4, 17, 1, 0, 0, 4]);
}
```

And compiled with these arguments:
```
RUSTFLAGS="-Zsanitizer=address -Clink-dead-code -C codegen-units=1" cargo +nightly run -Z build-std --target=x86_64-unknown-linux-gnu --release
```
I expected to see this happen: assertion passes like it does [on the playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=9890a1b5ebb5135fdd827c8fc667c6e8) or with `cargo run`.

Instead, this happened:
```
thread 'main' panicked at src/main.rs:12:5:
assertion `left == right` failed
  left: [255, 255, 18, 5, 0, 253, 239, 255, 4]
 right: [255, 255, 17, 4, 17, 1, 0, 0, 4]
```

### Meta

`rustc +nightly --version --verbose`:
```
rustc 1.77.0-nightly (d5fd09972 2024-01-22)
binary: rustc
commit-hash: d5fd0997291ca0135401a39dff25c8a9c13b8961
commit-date: 2024-01-22
host: x86_64-unknown-linux-gnu
release: 1.77.0-nightly
LLVM version: 17.0.6
```

**Comment by nikic** [comment]
Also reproduces without `-Z build-std`. I also tested this with `+b10e3758cdf73aa9155f6b955843731a66488b9c`, so it doesn't look like this issue has been fixed in LLVM 18.

**Comment by nikic** [comment]
opt-bisect points to:
```
BISECT: NOT running pass (2036) LoopVectorizePass on _ZN3foo8unfilter17hcdf00299b79e44ccE
```
IR for this function before and after LoopVectorize: https://gist.github.com/nikic/619764c58f3cd184326ffdd6831abc2e

**Comment by nikic** [comment]
Upstream issue: https://github.com/llvm/llvm-project/issues/79137

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23120260.20Miscompilation.20with.20-Zsanitizer.3Daddress)).

@rustbot label -I-prioritize +P-high

**Comment by nikic** [comment]
Fixed upstream by https://github.com/llvm/llvm-project/commit/cd7ea4ea657ea41b42fcbd0e6b33faa46608d18e.

**Comment by nikic** [comment]
Fixed in beta & nightly.
