### ISSUE TITLE
Pointer casts allow switching trait parameters for trait objects, which doesn’t interact soundly with trait upcasting

### ISSUE THREAD

**Issue by steffahn** [rust-lang/rust#120222]
### Pointer casts allow switching trait parameters for trait objects, which can change the set of supertraits (and thus the vtable layout), ultimately making upcasting of raw pointers quite unsound

This code reproduces a segfault, on upcoming stable Rust, starting in `1.76` (stabilization of trait object upcasting).

_Update:_ Stabilization was reverted, `1.76` stable Rust is good, the below code examples needs nightly Rust and `#⁠[feature(trait_upcasting)]` now.

```rs
#![feature(trait_upcasting)]

pub trait SupSupA {
    fn method(&self) {}
}
pub trait SupSupB {}
impl<T> SupSupA for T {}
impl<T> SupSupB for T {}

pub trait Super<T>: SupSupA + SupSupB {}

pub trait Unimplemented {}

pub trait Trait<T1, T2>: Super<T1> + Super<T2> {
    fn missing_method(&self)
    where
        T1: Unimplemented,
    {
    }
}

impl<S, T> Super<T> for S {}

impl<S, T1, T2> Trait<T1, T2> for S {}

#[inline(never)]
pub fn user1() -> &'static dyn Trait<u8, u8> {
    &()
/* VTABLE:
.L__unnamed_2:
        .quad   core::ptr::drop_in_place<()>
        .asciz  "\000\000\000\000\000\000\000\000\001\000\000\000\000\000\000"
        .quad   example::SupSupA::method
        .quad   .L__unnamed_4 // SupSupB vtable (pointer)
        .zero   8             // null pointer for missing_method
*/
}

#[inline(never)]
pub fn user2() -> &'static dyn Trait<u8, u16> {
    &()
/* VTABLE:
.L__unnamed_3:
        .quad   core::ptr::drop_in_place<()>
        .asciz  "\000\000\000\000\000\000\000\000\001\000\000\000\000\000\000"
        .quad   example::SupSupA::method
        .quad   .L__unnamed_4 // SupSupB vtable (pointer)
        .quad   .L__unnamed_5 // Super<u16> vtable (pointer)
        .zero   8             // null pointer for missing_method
*/
}

fn main() {
    let p: *const dyn Trait<u8, u8> = &();
    let p = p as *const dyn Trait<u8, u16>; // <- this is bad!
    let p = p as *const dyn Super<u16>; // <- this upcast accesses improper vtable entry
    // accessing from L__unnamed_2 the position for the 'Super<u16> vtable (pointer)',
    // thus reading 'null pointer for missing_method'
 
    let p = p as *const dyn SupSupB; // <- this upcast dereferences (null) pointer from that entry
    // to read the SupSupB vtable (pointer)
    
    // SEGFAULT

    println!("{:?}", p);
}
```
([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=d76c996f29cb1df88429a65bad61e01c), [compiler explorer](https://godbolt.org/z/61osWj6aE))

This issue exists next to #120217, but here I’ve found how the issue of overly liberal casting of raw pointers can be made into a concrete soundness issue, using no feature flags, producing an _actual_ segfault.

_Whether or now we need (to keep) two separate & somewhat similar GitHub issues can probably become clear eventually. If we don’t, we can always close one or the other._

---

Miri will already complain with a less sophisticated setup:

```rs
#![feature(trait_upcasting)]

trait Trait<T>: Super {}
trait Super {}

impl<S, T> Trait<T> for S {}
impl<S> Super for S {}

fn main() {
    let p: *const dyn Trait<u8> = &();
    let p = p as *const dyn Trait<u16>;
    let _p = p as *const dyn Super; // this is where miri complains already
}
```
([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=112fc194078a672f50c9e953142b60b0))
```
error: Undefined Behavior: upcast on a pointer whose vtable does not match its type
  --> src/main.rs:12:14
   |
12 |     let _p = p as *const dyn Super; // this is where miri complains already
   |              ^ upcast on a pointer whose vtable does not match its type
   |
   = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
   = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
   = note: BACKTRACE:
   = note: inside `main` at src/main.rs:12:14: 12:15
```

---

Three possible ways of fixing this would be to
* either make vtable layout even more regular,
  * _(and to officially allow somewhat “wrong” vtable types, also for miri, and to kill raw pointer[-like] types as `arbitrary_self_types` receiver…)_[^1]
* or to start working on limiting those pointer casts,
  * (even though [they’ve been possible since about Rust `1.2`](https://github.com/rust-lang/rust/issues/120217#issuecomment-1902831511), so some potential breakage and/or transition period, …!?)
* or to disallow upcasting raw pointers, after all.
  * (perhaps also temporarily as a quick fix before pursuing a better approach)

[^1]: my thought here is that e.g. it seems like missing methods are replaced with zeroes already, too, instead of skipped, and that pattern could be extended so that in the case of different sets of supertraits (like the `Super<u8>` == `Super<u8> + Super<u8>` vs. `Super<u8> + Super<u16>` above) could thus perhaps also avoid supertrait pointers appearing in inconsistent places between an applied trait constructor [`Trait<Args1…>` vs `Traits<Args2…>`] with different parameters

I’m marking as regression in beta as this is newly introduced unsoundness; and an approach like temporarily removing raw pointers again from our upcasting feature (assuming that’s technically possible in the first place) and/or delaying the stabilization are options, in case this soundness issue is perceived as sufficiently relevant not to be “ignored”.

@rustbot label +regression-from-stable-to-beta +F-trait_upcasting +A-coercions +A-trait-objects +I-unsound

**Comment by steffahn** [comment]
Between T-lang, T-compiler, and T-types [all 3 listed on the tracking issue], I’m not sure which (or which ones) to assign.

**Comment by Nilstrieb** [comment]
> P-critical, I do not want to stabilize a feature involving a new unsoundness

lcnr on Zulip

**Comment by RalfJung** [comment]
Yes, we should get a de-stabilization PR ASAP to avoid shipping this, and then assess the situation. Is someone working on that?

This seems like @rust-lang/lang @rust-lang/types to me; there's no bug in the compiler that I can see.

**Comment by RalfJung** [comment]
There's now a revert up at https://github.com/rust-lang/rust/pull/120233.

**Comment by lcnr** [comment]
> * either make vtable layout even more regular,
>  * _(and to officially allow somewhat “wrong” vtable types, also for miri, and to kill raw pointer[-like] types as `arbitrary_self_types` receiver…)_[^1]

I believe this to be fairly straightforward by computing the vtable layout once for a fully generic princial, e.g. reusing the same vtable layout for all instances of `for<T, U> dyn Foo<T, U>`, regardless of the actual arguments.

I still think we should revert and also try @WaffleLapkin's approach. 2 weeks is not enough time to play with any non-trivial fixes :thinking:

**Comment by wesleywiser** [comment]
Adjusting labels to reflect the reverted stabilization of the feature.

**Comment by steffahn** [comment]
And probably P-critical prioritization can go away eventually.

**Comment by lcnr** [comment]
dropping the t-types nomination. the stabilization has been reverted and we now have people working on this. While types team members may still be involved, this does not need any team input rn

**Comment by VorpalBlade** [comment]
I ran into something where trait upcasting would be the perfect fit. As such I went to look for what was blocking in the tracking PR. It seems that this is the only real blocker? If so, what is the current progress on this (if any)?

**Comment by oli-obk** [comment]
https://github.com/rust-lang/rust/pull/120248 is making progress on this

cc @WaffleLapkin

**Comment by traviscross** [comment]
This is believed to be fixed by:

- https://github.com/rust-lang/rust/pull/120248
