### ISSUE TITLE
raw-dylib is unusable with staticlib

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#120333]
STR:
- `mkdir -p foo/src; cd foo`
- Create a `Cargo.toml` file with the following content:
```
[package]
name = "foo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
windows-sys = { version = "0.52", features = ["Win32_UI_Controls"] }
```
- Create a `src/lib.rs` file with the following content:
```
#[no_mangle]
pub extern "C" fn foo() {
    use windows_sys::Win32::UI::Controls::GetMUILanguage;
    unsafe { GetMUILanguage(); }
}
```
- Compile with: `RUSTFLAGS="--cfg windows_raw_dylib --print native-static-libs" cargo build -vv --target=x86_64-pc-windows-msvc`

This will print the following at the end:
```
note: Link against the following native artifacts when linking against this static library. The order and any duplication can be significant on some platforms.

note: native-static-libs: kernel32.lib advapi32.lib bcrypt.lib kernel32.lib ntdll.lib userenv.lib ws2_32.lib kernel32.lib ws2_32.lib kernel32.lib ntdll.lib kernel32.lib msvcrt.lib
```

This obviously doesn't include anything that would be useful for the call to GetMUILanguage. Removing `--cfg windows_raw_dylib` adds `windows.0.52.0.lib` to the list (which, by the way, is also useless because that importlib is obviously not in $PATH or $LIB so one would have to look for it manually, but that's a separate issue).

This means e.g. the windows-target crate can't really default to windows_raw_dylib and drop the windows_$target dependencies even if it bumps its MSRV to 1.75 (which has support for raw-dylib for all platforms it would need it for, IIRC) (Cc: @kennykerr)

Here is a smaller reproducer (save as `foo.rs`):
```
#[link(name = "uxtheme.dll", kind = "raw-dylib", modifiers = "+verbatim")]
extern "C" {
    pub fn GetMUILanguage();
}
#[no_mangle]
pub extern "C" fn foo() {
    unsafe { GetMUILanguage(); }
}
```

Compile with: `rustc --print native-static-libs --crate-type staticlib --target=x86_64-pc-windows-msvc foo.rs`

**Comment by glandium** [comment]
What I would expect is a uxtheme.lib being created in somewhere in the target directory, and the full path to that lib being put in the native-static-libs output.

**Comment by ChrisDenton** [comment]
Hm I believe that for a staticlib the imports would end up being embedded in the lib itself?

**Comment by glandium** [comment]
Oh, you're right. The output from `llvm-readobj -a foo.lib` shows this:
```
File: uxtheme.dll
Format: COFF-import-file
Type: code
Name type: name
Symbol: __imp_GetMUILanguage
Symbol: GetMUILanguage
```

How did I miss this?
