### ISSUE TITLE
tweak temporary lifetime rules for `if` and `while` conditions

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#12033]
I think that `if` and `while` conditions should free any temporaries that occur within them (for `while` conditions it's mandatory, actually, since the condition is evaluated many times).

That is, if I write:

    if my_set().borrow().contains(&key) { ... }

the temporary returned by `borrow()` should be freed once the condition is evaluated, before entering the body of the `if`.

The same holds for `whiles`.

What makes these expressions different from other compound forms is that the conditions are evaluated to scalar booleans, and hence can never create lasting aliases that might need to be preserved.

In the case of a while, this is needed because temporaries can never outlive conditional or repeated scopes, and the condition of a while is a repeated scope.

**Comment by eddyb** [comment]
The fix in #12134 was partial, `if` with an `else` is still broken:
```rust
use std::cell::RefCell;

fn main() {
    let x = RefCell::new(0);
    if *x.borrow() == 0 {} else {} // error: `x` does not live long enough
}
```

**Comment by nikomatsakis** [comment]
Nominated. Seems clear to me that this is a bug we should fix -- the main question is whether to be concerned about backwards compatibility, and -- if so -- what to do about it.

I think this is mostly a question for @rust-lang/compiler team to decide, but I tagged this issue with T-Lang too in case @rust-lang/lang members want to weight in on whether the behavior is indeed a bug. But it seems clear that having `if` and `if/else` behave differently is bogus.

**Comment by nikomatsakis** [comment]
Consensus in the compiler team meeting was that we should just fix this and add the resulting PR to the release notes.

triage: P-medium
