### ISSUE TITLE
Implement allocators, integrate with box, smart pointers, containers

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#12038]
#### RELATED WORK

- http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2007/n2271.html
- https://github.com/bloomberg/bde/wiki/BDE-Allocator-Model

#### BLOCKING BUGS

- #4252 (?)

**Comment by steveklabnik** [comment]
Closing in favor of the RFC issue.
