### ISSUE TITLE
Division by zero -> Inf

### ISSUE THREAD

**Issue by hojner** [rust-lang/rust#120312]
I tried this code:

    println!("{}", 1 as f64 / 0 as f64);
    dbg!(1 as f64 / 0 as f64);
    println!("{}", 1 as f32 / 0 as f32);
    dbg!(1 as f32 / 0 as f32);

I expected to see this happen: Division by zero is Undefined from a mathematical perspective. Should give the result NaN. 

Instead, this happened: Gives the result Inf. But infinity is incorrect in this case. 

### Meta

`rustc --version --verbose`:
```
<version>
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by oli-obk** [comment]
This is the correct behaviour for IEEE floats, which is what most (all?) hardware uses, and which is how Rust defines its floating point types.

If you want stricter behaviour, consider using the https://crates.io/crates/typed_floats crate

**Comment by fmease** [comment]
CC [IEEE 754 standard](https://en.wikipedia.org/wiki/IEEE_754) which defines `1 / +0` to be `inf` and `1 / -0` to be `-inf`.

**Comment by hojner** [comment]
Thanks for the quick replies! I support adhering to standards, so no further questions. Will have to bring it up with the IEEE though... :)

**Comment by Scripter17** [comment]
[There are actually good reasons for this](https://youtube.com/watch?v=dQhj5RGtag0)

**Comment by hojner** [comment]
Hm, that's really interesting. Thanks for the video!
