### ISSUE TITLE
Docs feature banner will not show on top level docs when using glob export

### ISSUE THREAD

**Issue by iamsauravsharma** [rust-lang/rust#120487]
I tried this code:

```rust
#![feature(doc_cfg)]

mod a {
    #[doc(cfg(feature = "a"))]
    #[cfg(feature = "a")]
    pub struct Test1;
}

pub use a::*;
```

I expected to see this happen:
![Screenshot 2024-01-30 at 13-06-34 doc_cfg - Rust](https://github.com/rust-lang/rust/assets/38726015/8db00027-bfc6-4394-9d6a-dcc9ddb1b6d9)

Instead, this happened:
![Screenshot 2024-01-30 at 13-06-57 doc_cfg - Rust](https://github.com/rust-lang/rust/assets/38726015/8b11a2ab-633a-4385-bd9f-5781795107bf)

This is issue from `nightly-2023-12-16.` First screenshot is of `nightly-2023-12-15` and second is of `nightly-2023-12-16`

**Comment by Nemo157** [comment]
Probably https://github.com/rust-lang/rust/pull/113091, it shouldn't have affected glob re-exports but maybe did (cc @GuillaumeGomez).

**Comment by GuillaumeGomez** [comment]
Taking a look.

**Comment by GuillaumeGomez** [comment]
Same issue with a simple reexport:

```rust
mod b {
    #[doc(cfg(not(feature = "a")))]
    #[cfg(not(feature = "a"))]
    pub struct Test2;
}

pub use b::Test2;
```

**Comment by Nemo157** [comment]
That's what #113091 was meant to do, it wasn't meant to affect globs though.

**Comment by GuillaumeGomez** [comment]
I think there is another issue with how it's handled because nothing is listed on the item itself too:

![image](https://github.com/rust-lang/rust/assets/3050060/33a97d04-5ab9-40ff-adcd-06cb3d2d3f12)

**Comment by GuillaumeGomez** [comment]
Ok so it's the expected output for a non-glob reexport. I wrote the fix for glob reexports, just need to add tests.

**Comment by iamsauravsharma** [comment]
@GuillaumeGomez Latest nightly fixed the issue for `#![feature(doc_cfg)]` but it didn't fix the issue for `#![feature(doc_auto_cfg)]`.
In latest nightly below example doesn't work
```rust
#![feature(doc_auto_cfg)]

mod a {
    #[cfg(feature = "a")]
    pub struct Test1;
}

pub use a::*;
```
its last working version was also `nightly-2023-12-15`.

**Comment by GuillaumeGomez** [comment]
Noted. Sending a fix for it as well. :)

**Comment by GuillaumeGomez** [comment]
Fixed in https://github.com/rust-lang/rust/pull/120548.
