### ISSUE TITLE
Value is incorrectly considered to be borrowed accross await points

### ISSUE THREAD

**Issue by Pzixel** [rust-lang/rust#120442]
```rust
struct Baz(Box<dyn std::any::Any>);

async fn qwex() {}
async fn foo() {
    let bar = Baz(Box::new(42));
    qwex().await;
}

fn is_send<T: Send>(_: T) {}

fn main() {
    is_send(&foo());
}
```

It produces a compile-time error:
```rust
error: future cannot be shared between threads safely
  --> src/main.rs:13:13
   |
13 |     is_send(&foo());
   |             ^^^^^^ future returned by `foo` is not `Sync`
   |
   ```

This code is supposed to be send, because `bar` does not outlive `await` point

### Meta

I've checked both latest stable and nightly, problem persists on both.

**Comment by wackbyte** [comment]
`bar` is held across the await point because it has to be dropped at the end of the function:
```rs
async fn foo() {
    /* ┌ */ let bar = Baz(Box::new(42));
    /* │ */ qwex().await;
    /* └─── drop(bar); */
}
```
This can be avoided by manually dropping bar before the await point.

**Comment by Pzixel** [comment]
Right, but manual drop can be hard to write if we consider partial moves: 

```rust
pub fn baz() -> Result<String, Box<dyn std::error::Error>> {
    Ok("42".into())
}

async fn qwex(_: String) {}
async fn foo() {
    let bar = baz();
    let val = if let Ok(x) = bar { x } else { "W".into() };
    drop(bar);
    qwex(val).await;
}

fn is_send<T: Send>(_: T) {}

fn main() {
    is_send(&foo());
}
```

It can be solved manually reordering blocks to make sure lexical scopes end in proper places:

```rust
pub fn baz() -> Result<String, Box<dyn std::error::Error>> {
    Ok("42".into())
}

async fn qwex(_: String) {}
async fn foo() {
    let val = {
        let bar = baz();
        let val = if let Ok(x) = bar { x } else { "W".into() };
        val
    };
    qwex(val).await;
}

fn is_send<T: Send>(_: T) {}

fn main() {
    is_send(&foo());
}
```

It can also be surprising for users which are used to NLL features that `let bar = baz(); match bar { .. }` isn't the same as `match baz() { .. }`.

**Comment by traviscross** [comment]
@rustbot labels +AsyncAwait-Triaged +WG-async -C-bug

We reviewed this today in WG-async triage.  We agreed this is not a bug.  A related case that perhaps could be made to work is #116680.  Let's close in favor of that.
