### ISSUE TITLE
need std::io::listener for impl Listener<TcpStream, TcpAcceptor> for TcpListener

### ISSUE THREAD

**Issue by nickdesaulniers** [rust-lang/rust#12040]
In order to call listen on a TcpListener instance, I have to `use std::io::Listener`.  Same for accept.  Can these be moved into `std::io::net::tcp` ??

**Comment by alexcrichton** [comment]
This will likely be addressed by the ongoing I/O reform, for more details see some of the earlier revisions of https://github.com/rust-lang/rfcs/pull/517
