### ISSUE TITLE
Using replaceable operating system API plugins

### ISSUE THREAD

**Issue by zhuxiujia** [rust-lang/rust#120635]
Currently, I see that Mutex locks on Windows using TryAcquireSRWLockExclusive and AcquireSRWLockExclusive. The former only supports Windows 7 and above, while the latter supports Windows Vista and above. 

Using the APIs of both resulted in compatibility only with Windows 7 and not supporting Windows XP, Windows 2003, Windows 2008.  if you want run this exe will be  `can't find TryAcquireSRWLockExclusive on kernel32.dll`

see this example :

```code
fn main() {
    println!("Hello, world!");
}
```

![image](https://github.com/rust-lang/rust/assets/3481148/b471367e-02c8-4f7c-b6c0-af1a048b5ec0)

What I want to ask is why not move the API called by the operating system to a replaceable plugin, such as the toolchain toolchain in Rust,  so This is more flexible, and we can build our own toolchain that is compatible with older versions of the operating system

**Comment by AngelicosPhosphoros** [comment]
AFAIK, Rust is dropping support of Windows 8.1 soon: https://github.com/rust-lang/compiler-team/issues/651

**Comment by han1548772930** [comment]
Yes I agree too

**Comment by riking** [comment]
The rust9x and win7 targets will need to add `cfg` blocks to backfill compatibility on those old targets. The main Windows targets are now Win10+ only.

The win7 target has no changes to make with SRW locks, of course. You should get in contact with the rust9x mantainers.

**Comment by ChrisDenton** [comment]
Currently the only way to have different OS configurations is to add a new target (either in tree or out of tree, e.g. [rust9x](https://github.com/rust9x/rust)). Fully addressing this will require a few things to happen. [RFC 3379](https://github.com/rust-lang/rfcs/pull/3379) proposes a `target_os_version` config that could be used to select different function for different versions. However, std is prebuilt for each target so won't be able to make use of it on its own. The [`build-std` project goal](https://rust-lang.github.io/rust-project-goals/2025h1/build-std.html) hopes to address that. 

So closing this in favour of those efforts.
