### ISSUE TITLE
Rust compiler crashes: CARGO_CFG_TARGET_FEATURE env-var is not defined or is not UTF-8: NotPresent (project: qdrant, architecture: armv7)

### ISSUE THREAD

**Issue by yurivict** [rust-lang/rust#120637]
See [log](https://pkg-status.freebsd.org/ampere3/data/132releng-armv7-default/7036c2716ded/logs/qdrant-1.7.3_3.log).

Project: https://qdrant.tech

rust-1.75.0
FreeBSD 14.0

**Comment by bjorn3** [comment]
The answer to the todo at https://github.com/qdrant/quantization/blob/939fdb627a8edcf92fd71e3c79017156690850e9/quantization/build.rs#L9-L16 is clearly no.

This is not a compiler crash, but the build script of qdrant-quantization incorrectly assuming that `CARGO_CFG_TARGET_FEATURE` is always set. I would recommend creating an issue at https://github.com/qdrant/quantization/issues.

**Comment by yurivict** [comment]
Reported there: https://github.com/qdrant/quantization/issues/23

Thanks for your help!
