### ISSUE TITLE
Introduce Two-ended Comparison

### ISSUE THREAD

**Issue by amab8901** [rust-lang/rust#120668]
In Python, you can write two-ended comparison as `50 < x < 100`, but in Rust this simple syntax doesn't work and you instead have to write `50 < x && x < 100`. I think we should introduce the former syntax to Rust since it's more readable and concise. The implementation shouldn't be too hard since I imagine you could just tell the compiler that the former syntax is synonymous with the latter syntax.

**Comment by amab8901** [comment]
> This would need an RFC, see https://rust-lang.github.io/rfcs/lang_changes.html.

thanks! I posted an RFC :)

**Comment by fmease** [comment]
Closing then.
