### ISSUE TITLE
location / scoping of Impl

### ISSUE THREAD

**Issue by stroucki** [rust-lang/rust#120753]
Hi,

I am learning Rust via rust-book.cs.brown.edu and I think one of the examples had an Impl for a struct placed within a function. So I was thinking about where Impls can be placed, and whether they can be out of scope. I wrote up the below code (without the added scoping) and it worked. However, it still worked when I added a layer of scoping as below.

I consulted a friend who said this may warrant a warning from the compiler, and I should create an issue for it.

```rust
struct Foo {
  x: i32,
}

pub fn main() {
{ // will still work with or without this extra scope
  impl Foo {
    fn inc(&mut self) {
      self.x+=1;
    }
  }
} // extra scope

  let mut test = Foo{ x:1 };
  test.inc();
  println!("Foo: {}", test.x);
}
```
Rustc version: rustc 1.75.0 (82e1608df 2023-12-21) (built from a source tarball)

**Comment by Urgau** [comment]
See [RFC 3373: Avoid non-local definitions in functions](https://github.com/rust-lang/rfcs/blob/master/text/3373-avoid-nonlocal-definitions-in-fns.md).

It's currently being implemented in [#120393](https://www.github.com/rust-lang/rust/pull/120393).
