### ISSUE TITLE
> 📢 **This feature has a dedicated working group**, please direct comments and concerns to [the working group's repo](https://github.com/rust-lang/wg-allocators).

### ISSUE THREAD

**Issue by abc1000200** [rust-lang/rust#120774]
> 📢 **This feature has a dedicated working group**, please direct comments and concerns to [the working group's repo](https://github.com/rust-lang/wg-allocators).
> 
> The remainder of this post is no longer an accurate summary of the current state; see that dedicated working group instead.
> 
> Old content

_Originally posted by @abc1000200 in https://github.com/rust-lang/rust/issues/32838#issuecomment-1933808899_

**Comment by fmease** [comment]
Opened by mistake?
