### ISSUE TITLE
Unhelpful error message when missing the final path segment for a function call

### ISSUE THREAD

**Issue by Jarcho** [rust-lang/rust#120892]
Given an invalid call such as:

```rust
fn main() {
  foo::("foo");
}
```

The following diagnostic is issued:

```
error: expected type, found `"foo"`
 --> src/main.rs:2:9
  |
2 |   foo::("foo");
  |         ^^^^^ expected type
```

This gets much worse on multiline calls:

```rust
fn main() {
  foo::(
    bar(x, y, z),
    bar(x, y, z),
    bar(x, y, z),
    bar(x, y, z),
    bar(x, y, z),
    bar(x, y, z),
    bar(x, y, z),
    baz("test"),
  ),
}
```

Which just prints out a diagnostic nowhere near the error:

```
error: expected type, found `"test"`
  --> src/main.rs:10:13
   |
10 |         baz("test"),
   |             ^^^^^^ expected type
```

Ideally this should mention something about either missing a missing turbofish (e.g. `foo::<..>("foo")`), or a missing identifier (e.g. `foo::bar("foo")`). This would at least get the error pointing to the correct spot.

---

Latest playground nightly (2024-02-09)

**Comment by fmease** [comment]
Oh, wow, it didn't even occur to me until now that the expression `Option::(i32)::None::()` is syntactically valid >.<

**Comment by fmease** [comment]
The first case should pretty easy to fix, basically if we fail to parse a type here

https://github.com/rust-lang/rust/blob/7954c28cf932c00cd331598f189145861bf42b7c/compiler/rustc_parse/src/parser/path.rs#L375

we should first of all attach a label to the `::(` saying something akin to *while parsing this list of parenthesized type arguments starting here* and we should suggest removing the trailing path separator if the `PathStyle` is `Expr`, the parenthesized generics aren't followed by `::` and if the list of non-types we encountered can be successfully parsed as a list of expressions (using a snapshot parser).

I will mentor this.

**Comment by wutchzone** [comment]
Hello @fmease , is this issue still open for mentoring? I can see that @SummerGram already claimed the issue, but there seems to be no progress.

**Comment by SummerGram** [comment]
@wutchzone 

I read the code but no time to finish it at the moment. You can do it.
