### ISSUE TITLE
The std::any::type_name_of_val did not return the type I was expecting

### ISSUE THREAD

**Issue by Jnternet** [rust-lang/rust#120879]
I tried this code:

```rust
fn main() {
    let a = &&5;
    dbg!(any::type_name_of_val(a));
}
```

I expected to see this happen: *[explanation](any::type_name_of_val(a) = "&&i32")*

Instead, this happened: *[explanation](any::type_name_of_val(a) = "&i32")*

### Meta

`rustc --version --verbose`:
```
rustc 1.76.0 (07dca489a 2024-02-04)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: x86_64-pc-windows-gnu
release: 1.76.0
LLVM version: 17.0.6
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by kyleguarco** [comment]
`type_name_of_val` doesn't consume `T`; It takes a reference `&T`:
```rust
// Implementation located here: https://doc.rust-lang.org/beta/src/core/any.rs.html#734
pub const fn type_name_of_val<T: ?Sized>(_val: &T) -> &'static str {
    type_name::<T>()
}
```

`_val` is a `&T`. In your example, `a` is a `&&i32`, so `T` would be an `&i32`.

If you were to reference `a` in your call to `type_name_of_val`
```rust
fn main() {
    let a = &&5;
    dbg!(any::type_name_of_val(&a));
}
```
you'd get `std::any::type_name_of_val(&a) = "&&i32"`.

**Comment by compiler-errors** [comment]
Thanks for the explanation, @kyleguarco. This is not a bug indeed.
