### ISSUE TITLE
Make unwinding task-independent

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#12080]
For the sake of embedding applications it would be nice if Rust's unwinding implementation was not directly coupled to the task abstraction.

Right now unwinding is mostly just try/catch, but it also sets a flag on the task to indicate that the task is failing. It would be better if std could fulfill its unwinding obligations without involving the task.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#632
