### ISSUE TITLE
libc-test panic: `unsafe precondition(s) violated: hint::assert_unchecked must never be called when the condition is false`

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/rust#120910]
libc-test now panics since `1.78.0-nightly (d44e3b95c 2024-02-09)`.

### Code

repo: https://github.com/rust-lang/libc
example GHA run: https://github.com/rust-lang/libc/actions/runs/7852817358/job/21431727248

Not minimized yet.

```shell
gh repo clone rust-lang/libc
cd libc/libc-test
cargo test
```

### Meta

`rustc --version --verbose`:
```
rust version 1.78.0-nightly (d44e3b95c 2024-02-09)
```

### Error output

```
  thread 'main' panicked at library/core/src/panicking.rs:155:5:
  unsafe precondition(s) violated: hint::assert_unchecked must never be called when the condition is false
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  thread caused non-unwinding panic. aborting.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by asquared31415** [comment]
Probably because the condition is now being checked in debug mode even without build-std: #120594

I am inclined to say this is a bug in the code.

**Comment by asquared31415** [comment]
[this code](https://github.com/JohnTitor/garando/blob/ef91102626153ecf88274a9f272ba36127ae6847/garando_syntax/src/util/move_map.rs#L32) is incorrect, it's calling `get_unchecked` on a slice with length 0 (because the vec had its length set to 0 and is coercing to a slice).  Consider raw pointer manipulation with `vec.as_mut_ptr()` instead.

**Comment by JohnTitor** [comment]
Thanks for clarifying! Going to close as wontfix then.

**Comment by saethlin** [comment]
This is an old pattern that I rooted out of the compiler when I first worked on these checks about a year ago. We've also since stabilized `Vec::spare_capacity_mut` which is a more ergonomic way to fiddle with the region between `len` and `capacity`.
