### ISSUE TITLE
rustdoc: trait from other crate is not linked

### ISSUE THREAD

**Issue by mstange** [rust-lang/rust#120993]
On https://docs.rs/http-body-util/0.1.0/http_body_util/struct.StreamBody.html I was trying to find out what a `Stream` is.

Under "Trait Implementations", I see the following:

```
impl<S, D, E> Body for StreamBody<S> where
    S: Stream<Item = Result<Frame<D>, E>>,
    D: Buf,
```

Here it would be nice if I could click the "Stream" part in `S: Stream` and get to https://docs.rs/futures-util/0.3.14/futures_util/stream/trait.Stream.html .

**Comment by fmease** [comment]
Huh, this might be a regression and if so very likely the same regression as #120983.

**Comment by GuillaumeGomez** [comment]
Taking a look.

**Comment by GuillaumeGomez** [comment]
So the problem isn't actually rustdoc here but cargo: when there are no other deps locally present, rustdoc expects a map of URLs to know where to link for foreign items. However, in this case, this is a reexport of a foreign reexport, meaning we need to have access to a grand-child location, which we currently don't have. I'm checking with the `cargo` team to fix this issue.

**Comment by GuillaumeGomez** [comment]
I opened https://github.com/rust-lang/cargo/pull/13481, it should fix this issue.
