### ISSUE TITLE
Regression: Fail to evaluate self-referential static slices

### ISSUE THREAD

**Issue by nvzqz** [rust-lang/rust#120949]
### Code

I tried this code:

```rust
struct Value {
    values: &'static [&'static Value],
}

static VALUE: Value = Value {
    values: &[&VALUE],
};
```

I expected to see this happen: compile fine, with the `VALUE` static containing a slice that references `VALUE`.

Instead, this happened:

```
error[E0391]: cycle detected when const-evaluating + checking `VALUE`
 --> src/main.rs:6:13
  |
6 |     values: &[&VALUE],
  |             ^^^^^^^^^
  |
note: ...which requires simplifying constant for the type system `VALUE::promoted[0]`...
 --> src/main.rs:5:1
  |
5 | static VALUE: Value = Value {
  | ^^^^^^^^^^^^^^^^^^^
note: ...which requires const-evaluating + checking `VALUE::promoted[0]`...
 --> src/main.rs:5:1
  |
5 | static VALUE: Value = Value {
  | ^^^^^^^^^^^^^^^^^^^
  = note: ...which again requires const-evaluating + checking `VALUE`, completing the cycle
note: cycle used when linting top-level module
 --> src/main.rs:1:1
  |
1 | / struct Value {
2 | |     values: &'static [&'static Value],
3 | | }
4 | |
... |
8 | |
9 | | fn main() {}
  | |____________^
  = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information
```

### Version it worked on

It most recently worked on: `nightly-2024-02-10`

### Version with regression

`nightly-2024-02-11`

`rustc --version --verbose`:
```
rustc 1.78.0-nightly (6cc484351 2024-02-10)
binary: rustc
commit-hash: 6cc4843512d613f51ec81aba689180c31b0b28b6
commit-date: 2024-02-10
host: aarch64-apple-darwin
release: 1.78.0-nightly
LLVM version: 17.0.6
```

**Comment by DaniPopes** [comment]
searched nightlies: from nightly-2024-02-10 to nightly-2024-02-11
regressed nightly: nightly-2024-02-11
searched commit range: https://github.com/rust-lang/rust/compare/d44e3b95cb9d410d89cb8ab3233906a33f43756a...6cc4843512d613f51ec81aba689180c31b0b28b6
regressed commit: https://github.com/rust-lang/rust/commit/6cc4843512d613f51ec81aba689180c31b0b28b6

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.8</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc -vv --start 2024-02-10 --without-cargo -vv --script rustc -- src/lib.rs 
```
</details>

https://github.com/rust-lang/rust/pull/119614 cc @RalfJung @oli-obk

**Comment by nvzqz** [comment]
Context for how I found this: I use this technique in Divan in code generation for benchmarks of generic functions. The simple example I gave is just a minimal reproduction of the issue.

**Comment by RalfJung** [comment]
Hm, that is very strange. Not sure if there is a good way to get the backtrace of where in the code the cyclic queries are made?

My first guess is that it is the new call to `type_of` here:

https://github.com/rust-lang/rust/blob/77f8c3caea901df51ef723251a7a58b27f96bb3a/compiler/rustc_const_eval/src/interpret/validity.rs#L464-L472

But... surely we can ask for the *type* of a static while evaluating that very static, that can't be cyclic?

**Comment by RalfJung** [comment]
Ah no, probably it is related to the fact that we now recursively validate when a constant points to a static. Previously we stopped there. I guess we should not do that for promoteds.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23120949.20Regression.3A.20Fail.20to.20evaluate.20self-referential.20stati.E2.80.A6)).

@rustbot label -I-prioritize +P-high -E-needs-bisection +T-compiler
