### ISSUE TITLE
Improve wording of static_mut_ref

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#120964]
This lint currently prints
```
   = note: reference of mutable static is a hard error from 2024 edition
   = note: mutable statics can be written to by multiple threads: aliasing violations or data races will cause undefined behavior
```
The first line seems grammatically not entirely right to me. Shouldn't it say "in the 2024 edition"? And should it be "reference of" or "reference to"?

The second line doesn't quite capture the problem IMO. The issue is that the reference has lifetime `'static`, so 
- a mutable reference supposedly lives forever, so creating more than one is very dangerous and they can accidentally be used in overlapping ways
- a shared reference supposedly lives forever, so if there is ever also a mutable reference created that is very dangerous as they can accidentally be used in overlapping ways

Cc @obeis

**Comment by obeis** [comment]
Renaming the lint is not straightforward because of this PR #120676; I am not sure how it can be done.

**Comment by RalfJung** [comment]
What does that PR have to do with it?

When renaming a lint, remember to register it as a renamed lint. (Though I'm not sure if that will help with whatever issue you were running into.)

**Comment by obeis** [comment]
I need to allow both lints `static_mut_ref` and `static_mut_refs` because Bootstrap will use version 1.77 beta, and `static_mut_ref` already exists, as I understand.

What do you mean by register it as a renamed lint?

**Comment by RalfJung** [comment]
We have the `bootstrap` cfg-flag to handle such situations. So you can do something like
```rust
#[cfg_attr(bootstrap, allow(static_mut_ref))]
#[cfg_attr(not(bootstrap), allow(static_mut_refs))]
```

> What do you mean by register it as a renamed lint?

https://github.com/rust-lang/rust/blob/cf1096eb72e93eeaaed2c8117d68b5798928330b/compiler/rustc_lint/src/lib.rs#L313-L326
