### ISSUE TITLE
`polymorphic_recursion.rs` takes longer to compile

### ISSUE THREAD

**Issue by DianQK** [rust-lang/rust#120912]
### Code

I tried this code:

```rust
// skip-filecheck
// Make sure that the MIR inliner does not loop indefinitely on polymorphic recursion.
// compile-flags: --crate-type lib

// Randomize `def_path_hash` by defining them under a module with different names
macro_rules! emit {
    ($($m:ident)*) => {$(
        pub mod $m {
            pub trait Tr { type Next: Tr; }

            pub fn hoge<const N: usize, T: Tr>() {
                inner::<N, T>();
            }

            #[inline(always)]
            fn inner<const N: usize, T: Tr>()
            {
                inner::<N, T::Next>();
                inner::<N, T::Next>();
            }
        }
    )*};
}

// Increase the chance of triggering the bug
emit!(m00 m01 m02 m03 m04 m05 m06 m07 m08 m09 m10 m11 m12 m13 m14 m15 m16 m17 m18 m19);
```

https://github.com/rust-lang/rust/blob/1.76.0/tests/mir-opt/inline/polymorphic_recursion.rs

I expected to see this happen: *It compiles quickly.*

Instead, this happened: *It takes 10s to complete.*

### Version with regression

Bisected to https://github.com/rust-lang/rust/pull/120584.

cc @compiler-errors

**Comment by compiler-errors** [comment]
@DianQK: Why did you title this "is broken"? It just takes longer to compile, or is it broken some other way?

I'll look into the upcoming week.

**Comment by DianQK** [comment]
> @DianQK: Why did you title this "is broken"? It just takes longer to compile, or is it broken some other way?
> 
> I'll look into the upcoming week.

Sorry, it just takes longer to compile.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23120912.20.60polymorphic_recursion.2Ers.60.20is.20broken/near/420858239)).

@rustbot label -I-prioritize +P-medium -regression-untriaged

**Comment by Zalathar** [comment]
On my machine (Apple M2 Pro), this test normally finishes after about 30 seconds.

But if I enable `[rust] debug-assertions = true`, the compiler appears to consume 100% CPU forever.

I'm not sure whether it's actually stuck, or just taking an incredibly long time, but I've never seen it finish with debug assertions enabled.

**Comment by Zalathar** [comment]
If I apply #120942, the test finishes in about 45 seconds with debug assertions enabled.
