### ISSUE TITLE
Enabling `feature(effects)` causes const_patterns_without_partial_eq to show up

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#121076]
The following code works fine without the `effects` feature, but triggers a warning (soon to [become a hard error](https://github.com/rust-lang/rust/pull/120805)) when the feature is enabled:

```rust
#![feature(effects)]
#[derive(Eq, PartialEq)]
pub struct TypeThatIsPartialEq(u8);
pub const GREEN: TypeThatIsPartialEq = TypeThatIsPartialEq(4);

pub const fn is_green(x: TypeThatIsPartialEq) -> bool {
    match x { GREEN => true, _ => false }
}
```
[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=415cd88942231f06b9f2e79fb70da64b)

**Comment by bend-n** [comment]
i think this is a duplicate of #119398

**Comment by RalfJung** [comment]
Ah, true. Why didn't you mention on Zulip that you had filed an issue?^^ Would have saved me some work...

**Comment by bend-n** [comment]
> Ah, true. Why didn't you mention on Zulip that you had filed an issue?^^ Would have saved me some work...

i created the issue as a request on the zulip thread https://rust-lang.zulipchat.com/#narrow/stream/146212-t-compiler.2Fconst-eval/topic/match.20on.20const.20triggers.20warning.20with.20effects/near/410360676

**Comment by RalfJung** [comment]
Ah, must have forgotten that. Sorry :)
