### ISSUE TITLE
Unless Rust migrates to cc-rs 1.0.83 target aarch64-apple-ios-sim remains unusable for many projects

### ISSUE THREAD

**Issue by CodingMarkus** [rust-lang/rust#121027]
Because of this [issue](https://github.com/rust-lang/cc-rs/pull/759), Rust projects with C or assembly components cannot be built for target aarch64-apple-ios-sim. It's ridiculous that it took an entire year to fix such a tiny bug in cc to begin with but now that this bug is finally fixed and merged, Rust keeps using 1.0.79, even in its latest Beta and Nightly builds so even after waiting an entire year, none of our Rust libraries for iOS can be updated yet. This has been a total show stopper for over a year and apparently it will continue to be one.

**Comment by clubby789** [comment]
Bumping `cc-rs` until now broke bootstrapping. I believe this issue has been fixed as of a couple of days ago - once #120055 lands, I will rebase #120454 with a `cc` bump

**Comment by clubby789** [comment]
Nevermind, it's already been yanked https://github.com/rust-lang/cc-rs/issues/948 😭

**Comment by riking** [comment]
Recheck this - I think there have been multiple attempted fixes landed in cc-rs.

**Comment by madsmtm** [comment]
Rust by now uses `cc` `v1.0.92` which includes the linked fix, so I believe this issue can be closed.

**Comment by workingjubilee** [comment]
We're on cc 1.0.97 so basically just assuming this is fixed for everyone involved.

**Comment by workingjubilee** [comment]
feel free to say "the hell it aint" and reopen this or whatever
