### ISSUE TITLE
Cannot build tool build scripts with `use-lld = true` when lld is not in PATH

### ISSUE THREAD

**Issue by Nilstrieb** [rust-lang/rust#121048]
I'm using `use-lld = true` but do not have `lld` in PATH. This works well.

...except when I tried to add a tool to `src/tools` as a `bootstrap_tool` with a dep that has a build script (for example, `proc_macro2`). It will complain about `clang-16: error: invalid linker name in argument '-fuse-ld=lld'`, which implies that bootstrap is somehow messing up the PATH or something like that for tools.

**Comment by lqd** [comment]
> I'm using `use-lld = true` but do not have `lld` in PATH

Out of curiosity, what linker will be used in this situation (or are you also using `rust.lld = true`)?

**Comment by Nilstrieb** [comment]
> or are you also using `rust.lld = true`

No, I am not explicitly setting this. I would assume it uses `build/host/ci-llvm/bin/lld`

**Comment by onur-ozkan** [comment]
> I'm using use-lld = true but do not have lld in PATH. This works well.

Doesn't work for me. I can't build anything using `use-lld = true` config when `lld` is not in PATH.

**Comment by Nilstrieb** [comment]
well, i accidentally reproduced this by creating a new worktree and forgetting to copy over my nix shell and got an error complaining about lld not existing. so i have no clue what i was doing when originally hitting this, but nothing good apparently.
