### ISSUE TITLE
Rust image creation fail due to: "download of config.json failed"

### ISSUE THREAD

**Issue by MrMic** [rust-lang/rust#121143]
Hi,

When i try to buils an image for a rust App I always got this error:

`
0.544     Updating crates.io index                                                                                                                                                           
0.548 warning: spurious network error (3 tries remaining): [6] Couldn't resolve host name (Could not resolve host: index.crates.io)                                                          
1.940 warning: spurious network error (2 tries remaining): [6] Couldn't resolve host name (Could not resolve host: index.crates.io)
5.441 warning: spurious network error (1 tries remaining): [6] Couldn't resolve host name (Could not resolve host: index.crates.io)
11.94 error: failed to get `chrono` as a dependency of package `rust-web-dev v1.0.0 (/app)`
11.94 
11.94 Caused by:
11.94   failed to query replaced source registry `crates-io`
11.94 
11.94 Caused by:
11.94   download of config.json failed
11.94 
11.94 Caused by:
11.94   failed to download from `https://index.crates.io/config.json`
11.94 
11.94 Caused by:
11.94   [6] Couldn't resolve host name (Could not resolve host: index.crates.io)
------
`

Any idea to solve this? 
I am stuck and have not find any fix that works on internet.
:( 

Rgds,

**Comment by saethlin** [comment]
> Could not resolve host: index.crates.io

Cargo is trying to resolve the domain name `index.crates.io` and can't. This is a DNS issue, possibly an issue with your local network or local machine. The domain name currently resolves from where I am.

**Comment by MrMic** [comment]
Not at all! Everything is working perfectly fine on my host.
The issue is inside the container ... and indeed it is a domain 
name issue when I create the image from a rust app.
What is weird is that when I run a rust container alone from CLI and 
log into it, I can download what I want.

**Comment by saethlin** [comment]
The issue tracker is for problems or features in Rust or the tools we distribute. It sounds like you need support with using Cargo in your Docker setup, so one of these places would be a better place to get help: https://www.rust-lang.org/community
