### ISSUE TITLE
io::IoError should carry info on the invalid byte sequence on non-utf8 InvalidInput

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#12113]
If you feed in a byte stream that is almost utf-8 but has errors, a looped series of calls to  `fn read_char` will eventually return an `IoError` with `kind == InvalidResult`.

Unfortunately, the returned `IoError` does not include any information about what the bytes were that were invalid (nor does it include information like how many bytes were read from the input before the error was encountered).

It seems like it would not be that bad to change `IoError` so that its `detail` field could be an `Option<Either<~str, ~[u8]>>`, or something along those lines, so that in this scenario, the `InvalidResult` would imply that one could look at the `detail` field to determine what the byte sequence was that caused the problem (and then the client code would have the option of substituting in a different character sequence specific to the byte sequence that failed).

(Alternatively, we could change `IoErrorKind` so that the `InvalidResult` variant carried an `Option<~[u8]>`, but then the `IoErrorKind` would no longer be a C-like enum.)

I believe that this is strictly more expressive than just mapping every replacement to a single replacement character, as is done by `from_utf8_lossy` (#12062).

**Comment by steveklabnik** [comment]
With IO reform, `IoError` is being renamed, and some of it is being made private. So we'll see how this shakes out.

**Comment by steveklabnik** [comment]
Triage: too much time has passed and too much has changed, so I don't actually remember what the right thing is here. 

I _believe_ this boils down to https://github.com/rust-lang/rust/issues/27802, ie, we still haven't decided what happens when you get an invalid `char` while reading.

@rust-lang/libs, opinions?

**Comment by sfackler** [comment]
We certainly now have the ability to do this via the custom error payload you can pass into `io::Error::new`. It seems pretty reasonable to include the offending byte in that.

**Comment by pnkfelix** [comment]
I agree that this essentially could become a sub issue of #27802 ; but the discussion of that issue seems to focus on the semantics of a char iterator's interaction with an underlying byte stream (which is very important), while this issue is more of a "it would be nice if the error object that gets bubbled up actually carried enough info for a user to do recovery"

We haven't always done such a great job in this respect, IMO, so I'm trying to be explicit about it here.

**Comment by Mark-Simulacrum** [comment]
`Read::chars` has been deprecated and the functionality this asks for is primarily provided through `str::from_utf8`; I'm going to close this issue.
