### ISSUE TITLE
Document `is_val_statically_known` only supports primitives (ICE otherwise)

### ISSUE THREAD

**Issue by nyurik** [rust-lang/rust#121115]
### Location

https://github.com/rust-lang/rust/blob/ee9c7c940c07d8b67c9a6b2ec930db70dcd23a46/library/core/src/intrinsics.rs#L2521-L2570

### Summary

Per https://github.com/rust-lang/rust/pull/121064#discussion_r1488948104 comment by @Nilstrieb, `is_val_statically_known` only supports primitive types - which is not listed anywhere in the documentation.

When trying to use inside the core library on `core::fmt::Arguments`, compiler crashes #121066.

CC: @NCGThompson

**Comment by Teapot4195** [comment]
> is_val_statically_known only supports primitive types

Fixed in #120484, building on nightly will fix this crash. `is_val_statically_known` also returns false for non primitive types since that PR.

**Comment by NCGThompson** [comment]
> > is_val_statically_known only supports primitive types
> 
> Fixed in #120484, building on nightly will fix this crash. `is_val_statically_known` also returns false for non primitive types since that PR.

In my opinion, I think that is more of a reason to update documentation.

**Comment by NCGThompson** [comment]
@RalfJung In terms of provenance and Miri, what does `is_val_statically_known` do with `ptr`s? I want to explain it by stating that two code snippets are equivalent, but I don't know if it would be correct to use `ptr.addr()` or `ptr.expose_addr()`.

I think from a theoretical perspective, `ptr.addr()` would be the way to go because the address is never being turned back into a `ptr`, but I have no idea if Miri knows that.

**Comment by RalfJung** [comment]
In terms of the spec, `is_val_statically_known` just returns an arbitrary boolean, so pointer vs non-pointer doesn't really make any difference.

So it's really up to the optimizer to decide whether knowing the address but not the provenance of a pointer is sufficient to consider the value "known". I personally would say "no", but it's always okay to return `true` from this function so nothing can break if the answer becomes "yes".

**Comment by NCGThompson** [comment]
LLVM either:

* only considers the raw byte value of the pointer, or
* only considers the address of the pointer.

I'm not sure, but I'd bet on the first. The potential difference between those two possibilities is explained in the docs for `addr` and `expose_addr`. (I suspect the docs for `addr` is currently incorrect.)
