### ISSUE TITLE
Target feature optimized code in inline function gets compiled with default feature

### ISSUE THREAD

**Issue by jhorstmann** [rust-lang/rust#121290]
This is probably a misunderstanding on my side of how target features and inlining interacts, but would be interested in workarounds or opinions. My usecase is that some `inline(always)` helper method has avx512 specific optimizations, while the surrounding code is rather generic. I would like to generate specialized implementations of that generic code, including the target feature specific optimization, by wrapping it in functions with the target feature activated, and then doing runtime dispatch using `is_x86_feature_detected`.

I tried this code (https://rust.godbolt.org/z/zanYed7ej):

```rust
#![feature(avx512_target_feature)]

#[inline(always)]
fn level() -> usize {
    if cfg!(target_feature = "avx512f") {
        return 4;
    } else if cfg!(target_feature = "avx2") {
        return 3;
    } else if cfg!(target_feature = "sse4.1") {
        return 2;
    } else {
        return 1;
    }
}

#[inline(never)]
#[target_feature(enable="avx512f,avx512vl,avx512bw")]
pub unsafe fn level4() -> usize {
    level()
}

#[inline(never)]
#[target_feature(enable="avx2")]
pub unsafe fn level3() -> usize {
    level()
}

#[inline(never)]
#[target_feature(enable="sse4.1")]
pub unsafe fn level2() -> usize {
    level()
}

pub fn dispatch() -> usize {
    unsafe {
        if is_x86_feature_detected!("avx512f") {
            level4()
        } else if is_x86_feature_detected!("avx2") {
            level3()
        } else if is_x86_feature_detected!("sse4.1") {
            level2()
        } else {
            level()
        }
    }
}
```

I expected to see this happen: I was hoping that without `target-cpu` specified, the `level` function would get inlined into `level4` and return `4`.

Instead, this happened: all `leveln` functions return `1`

### Meta

`rustc --version --verbose`:
```
rustc 1.78.0-nightly (bccb9bbb4 2024-02-16)
binary: rustc
commit-hash: bccb9bbb418a30aeb332052e721beb6ebc6b1ce7
commit-date: 2024-02-16
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0
Compiler returned: 0
```

**Comment by bjorn3** [comment]
`cfg!()` is a macro, which is expanded long before codegen. As such codegen will see

```rust
#[inline(always)]
fn level() -> usize {
    if false {
        return 4;
    } else if false {
        return 3;
    } else if false {
        return 2;
    } else {
        return 1;
    }
}
```

if avx512f, avx2 and sse4.1 are not statically enabled for the entire crate. There is currently no way to get the target features enabled for a piece of code after inlining.

**Comment by the8472** [comment]
As a workaround you could pass down the architecture-specific information as a const-generic argument to the general implementation.

**Comment by jhorstmann** [comment]
Thanks, this makes sense. Inlining is not text substitution.

I will try the generic parameter route, I think I have also seen that somewhere with some kind of token or handle for the current feature set.

Closing this issue as "working as intended".
