### ISSUE TITLE
#[deriving(Show)] handles its interior fundamentally incorrectly

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#12128]
e.g.

```rust
#[deriving(Show)]
struct Foo {
    x: ~str
}

fn main() {
    println!("{}", Foo { x: ~"bar }" });
}
```

prints `Foo { x: bar } }`, but `Foo { x: ~"bar }" }` or `Foo { x: "bar }" }` would be far more reasonable.

Our `Show` differs from Haskell's (which also has `deriving (Show)`) in that `show string` puts quotes around it, while our `{}` is puts it straight inline (i.e. they're actually different operations).

Proposal: create (yet another) formatting trait `Repr` and replace `#[deriving(Show)]` with `Repr`. This would mean that `println!("{:r}", "foo")` would be printed as `"foo"` rather than just `foo` like `{}` does. I feel like this is a more accurate description of what it's doing: it's a raw representation of a type, while `{}` is meant to be more polished.

**Comment by steveklabnik** [comment]
Today, the equivalent code with `Debug` prints

```
Foo { x: "bar }" }
```
