### ISSUE TITLE
Process spawning should expose the ability to drop capabilities on linux

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#12137]
More information can be found in this comment: https://github.com/mozilla/rust/pull/12085#issuecomment-34557132

The idea is that when you attempt to drop privileges when spawning (`setuid`, `setgid` etc) you should in theory be dropping all privileges of the previous user. We're already doing some special stuff with `setgroups`, and it sounds like capabilities should also be dropped.

cc @bnoordhuis

**Comment by l0kod** [comment]
This feature should be available even outside the process spawning (i.e. post-execution).

**Comment by alexcrichton** [comment]
Closing in favor of https://github.com/rust-lang/rfcs/issues/941
