### ISSUE TITLE
.expect() doesn't give much information about the error message

### ISSUE THREAD

**Issue by Antonio225t** [rust-lang/rust#121456]
So basically in Rust's `core::Result` there is a `unwrap_failed` that `expect` calls when the result is an error.

This `unwrap_failed` looks like this:
```rust
fn unwrap_failed(msg: &str, error: &dyn fmt::Debug) -> ! {
    panic!("{msg}: {error:?}")
}
```

Because of the `:?`, this can result in some error messages not giving much information like this:
```
thread 'main' panicked at src\main.rs:432:22:
Expected date: ParseError(Invalid)
```
Don't get me wrong, `ParseError(Invalid)` is a straightforward description but when you sometimes need to actually know what the problem is it can be too much straightforward.

Because of this I am asking, can you add for example `{msg}: {error:?}\n{error}\n` so it's a cleaner look at the reason why it did panic?
Thank you very much, if this is a duplicate, I'm sorry.

**Comment by tgross35** [comment]
To be clear: are you asking that it print the `Display` representation of an error after its `Debug` representation?

This would not be possible as `expect` like `unwrap` requires the error to implement `Debug`. Adding a `Display` bound would be a breaking change.

For your own code where errors implement `Display`, you could instead do:

```rust
some_result.unwrap_or_else(|e| panic!("something bad happened!: {e}"))
```

**Comment by Antonio225t** [comment]
> This would not be possible as `expect` like `unwrap` requires the error to implement `Debug`. Adding a `Display` bound would be a breaking change.

I understand now why there is not something like this already implemented.
Also thanks for the alternate solution. ❤👍
