### ISSUE TITLE
Compiling tests for `wasm64-unknown-unknown` on latest Nightly results in linking error

### ISSUE THREAD

**Issue by newpavlov** [rust-lang/rust#121460]
Compiling any crate with `cargo test --no-run -Z build-std=std,panic_abort --target=wasm64-unknown-unknown` results in the following error: `rust-lld: error: /home/dir/.cargo/target/wasm64-unknown-unknown/debug/deps/libtest-ed35d2d81ad088d3.rlib(lib.rmeta): wasm32 object file can't be linked in wasm64 mode`.  This is a regression introduced in one of the recent NIghtly versions.

Toolchain version: cargo 1.78.0-nightly (194a60b29 2024-02-21)

**Comment by matthiaskrgr** [comment]
Probably related to https://github.com/rust-lang/rust/pull/120588 cc @alexcrichton

**Comment by alexcrichton** [comment]
Yep definitely looks like my fault, I'll work on a fix!
