### ISSUE TITLE
DefineOpaqueTypes::No in UFC `Self` resolution

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#121404]
in https://github.com/rust-lang/rust/blob/1d447a9946effc38c4b964a888ab408a3df3c246/compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs#L1452 we disable hidden type registration. I have been unable to craft a test case for this, as either the `self_ty` arg of `instantiate_value_path` is `None`, or there are no generic parameters on the self type, so it gets inference variables which end up working out fine. 

As an example:

```rust
#![feature(type_alias_impl_trait)]
struct Foo<T>(T);

impl Foo<u32> {
    fn method() {}
    fn method2(self) {}
}

type Bar = impl Sized;

fn bar() -> Bar {
    42_u32
}

impl Foo<Bar> {
    fn foo() -> Bar {
        Self::method();
        //~^ ERROR: no function or associated item named `method` found for struct `Foo<Bar>`
        Foo::<Bar>::method();
        //~^ ERROR: no function or associated item named `method` found for struct `Foo<Bar>`
        let x = Foo(bar());
        Foo::method2(x);
        let x = Self(bar());
        Self::method2(x);
        //~^ ERROR: no function or associated item named `method2` found for struct `Foo<Bar>`
        todo!()
    }
}

fn main() {}
```

the `Foo::method2(x);` works fine, none of the others do, and none of them have a `self_ty` set here either.

Wrapping the types in `<>` does not have an effect, even if the code seems to hint at that: https://github.com/rust-lang/rust/blob/1d447a9946effc38c4b964a888ab408a3df3c246/compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs#L1150

any ideas @compiler-errors 

cc https://github.com/rust-lang/rust/pull/121394

**Comment by compiler-errors** [comment]
@oli-obk: This `DefineOpaqueTypes::Yes` is unreachable until we fix the method (well, associated item) probing in `resolve_ty_and_res_fully_qualified_call`.

**Comment by oli-obk** [comment]
yay, thought so, I'll add the test with a comment that it is a bug
