### ISSUE TITLE
rustdoc should be able to reference libstd in intra-doc links in libcore

### ISSUE THREAD

**Issue by clarfonthey** [rust-lang/rust#121436]
This is something that came up in #112136.

Essentially, because we want to `#[doc(inline)]` the `CString` type in its parent module, we actually can't use hard-coded relative links and must use intra-doc links. However, we also can't do intra-doc links in libcore that reference libstd.

I think that especially since doc *tests* can reference libstd in libcore, we should also be able to intra-doc link libstd in libcore.

This also will probably enable us to get rid of the remaining hard-coded, non-intra-doc-links in libcore.

**Comment by ehuss** [comment]
Is this issue much different from #74481?
