### ISSUE TITLE
Make --crate-file-name always return one file with any kind

### ISSUE THREAD

**Issue by mitsuhiko** [rust-lang/rust#12152]
Currently the `crate-file-name` flag to the compiler can return more than one name if a build is made against a different crate type than the library defines.  For instance if the crate type is set to `lib` it will generate an rlib, even if `--crate-type=dylib` is defined.  This obviously is not a fault of the `--crate-file-name` parameter but the compiler itself in that it does not override the default crate type but append it to the list of things to build.

The reason this is frustrating is because `--crate-file-name` is very useful for building makefiles but it becomes much more complicated to manage if a target can produce more than one output file.

**Comment by alexcrichton** [comment]
https://github.com/rust-lang/rust/issues/11573 has since been resolved so I'm going to close this as fixed. Today if you want just the dylib name you can say `rustc --print filenames --crate-type dylib foo.rs`
