### ISSUE TITLE
regression: NonZero is ambiguous

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#121604]
* https://crater-reports.s3.amazonaws.com/beta-1.77-3/beta-2024-02-18/reg/common_traits-0.10.0/log.txt
  * cc @vigna / @zommiommy as authors of the crate
  * https://crater-reports.s3.amazonaws.com/beta-1.77-3/beta-2024-02-18/reg/ptr_hash-0.1.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.77-3/beta-2024-02-18/gh/RagnarGrootKoerkamp.pthash-rs/log.txt

My guess is this will be closed as expected, but should be a conscious decision.

```
[INFO] [stdout] error[E0659]: `NonZero` is ambiguous
[INFO] [stdout]    --> src/impls.rs:723:14
[INFO] [stdout]     |
[INFO] [stdout] 723 |         impl NonZero for $nzty {
[INFO] [stdout]     |              ^^^^^^^ ambiguous name
[INFO] [stdout]     |
[INFO] [stdout]     = note: ambiguous because of multiple glob imports of a name in the same module
[INFO] [stdout] note: `NonZero` could refer to the trait imported here
[INFO] [stdout]    --> src/impls.rs:1:5
[INFO] [stdout]     |
[INFO] [stdout] 1   | use crate::*;
[INFO] [stdout]     |     ^^^^^^^^
[INFO] [stdout]     = help: consider adding an explicit import of `NonZero` to disambiguate
[INFO] [stdout] note: `NonZero` could also refer to the struct imported here
[INFO] [stdout]    --> src/impls.rs:2:5
[INFO] [stdout]     |
[INFO] [stdout] 2   | use core::num::*;
[INFO] [stdout]     |     ^^^^^^^^^^^^
[INFO] [stdout]     = help: consider adding an explicit import of `NonZero` to disambiguate
```

**Comment by dtolnay** [comment]
Relevant documentation: https://doc.rust-lang.org/1.76.0/cargo/reference/semver.html#item-new

_"glob imports are a known forwards-compatibility hazard. Glob imports of items from external crates should be avoided."_

Normally, unless the breakage is extraordinarily disruptive (affecting a foundational library that is unmaintained but still widely-used) we move on and remind the author not to use glob imports.

**Comment by apiraino** [comment]
Removing prioritization since affected crates are taking care of this ([Zulip discussion](The authors of an affected crate were mentioned and already updated their code (in https://github.com/zommiommy/common_traits/commit/ab8e504d93c5e461230182141965b05dac59822c) so I think this is under control (so my understanding).

@rustbot label -I-prioritize

**Comment by jieyouxu** [comment]
Can this issue be closed if it's intentional breakage?

**Comment by apiraino** [comment]
> Can this issue be closed if it's intentional breakage?

Speaking for me personally: yes. But :slightly_smiling_face: 

I'm not sure how crater runs regressions are treated and if T-infra prefers to go through them again at a later stage and decide for a close.

**Comment by zommiommy** [comment]
Yeah, we handled the change so it's absolutely not a priority, nor a problem and thus it can be closed. 

Then, we'll deal with the glob imports, thank you!
