### ISSUE TITLE
Expose an UTF-8 checking function that returns the index of the error

### ISSUE THREAD

**Issue by Jurily** [rust-lang/rust#12168]
Use case:

- reporting the position of the error to the user

Possible candidates: 

- mark `first_non_utf8_index()` as public
- change `from_utf8{_owned}`'s return type from  `Option` to `Result<_, uint>`

Since it's possible to recover from such an error, it would also be nice if these returned all encoding errors.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#860

**Comment by aturon** [comment]
Note: this has actually been resolved.
