### ISSUE TITLE
rustdoc collapser also collapses stability annotations

### ISSUE THREAD

**Issue by Gankra** [rust-lang/rust#121772]
The stability annotations are inside the collapsible area now, so they get hidden when you collapse things. This is *probably* undesirable.

Evidently this is a regression introduced in 1.54.0.

## Reproduction Steps

tap the `[-]` in the top right (or if you had it on `[+]` you need to press it twice)
then check if you can tell which methods are unstable:
- stability visible: <https://doc.rust-lang.org/1.53.0/std/iter/trait.Iterator.html>
- stability hidden: <https://doc.rust-lang.org/1.54.0/std/iter/trait.Iterator.html>

![image](https://github.com/rust-lang/rust/assets/1136864/912ceab5-5beb-4009-87f8-d3c7e9e1e671)

**Comment by GuillaumeGomez** [comment]
Quite the old change. But I agree, it should not be foldable.
