### ISSUE TITLE
Diagnostic strips leading underscore

### ISSUE THREAD

**Issue by joshlf** [rust-lang/rust#121776]
I tried [the following code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=dd02354be92ff2bba4edc7030993cda0) on Rust 1.76.0:

```rust
enum _Foo {
    Bar
}

fn main() {
    let _ = Foo::Bar;
}
```

I got the following error:

```text
error[E0433]: failed to resolve: use of undeclared type `Foo`
 --> src/main.rs:6:13
  |
6 |     let _ = Foo::Bar;
  |             ^^^ use of undeclared type `Foo`
  |
help: an enum with a similar name exists, consider changing it
  |
1 | enum Foo {
  |      ~~~
```

Note that the suggestion has stripped the leading `_` character from the enum's name.

**Comment by jieyouxu** [comment]
Can confirm this is still present in nightly.

**Comment by GuillaumeGomez** [comment]
Sounds like fun. Taking a look.

**Comment by GuillaumeGomez** [comment]
So it is intended this way from what I can see in the source code:

```rust
// When the suggested binding change would be from `x` to `_x`, suggest changing the
// original binding definition instead. (#60164)
```

Improving the wording would be become to clear the confusion though I think.
