### ISSUE TITLE
Can Rust compile source file into wasm64  by now?

### ISSUE THREAD

**Issue by Hellosuna** [rust-lang/rust#121727]
hello.I wonder whether Rust Can  compile source file into wasm64.
when I add wasm64 target,it shows toolchain 'stable-x86_64-unknown-linux-gnu' does not contain component 'rust-std' for target 'wasm64-unknown-unknown',I see similar questions in other issues,then what can I do to solve it?

**Comment by jieyouxu** [comment]
If you check the [platform support page](https://doc.rust-lang.org/nightly/rustc/platform-support.html) `wasm64-unknown-unknown` seems to be a Tier 3 target with WIP or unknown std support. You may have to [build std yourself for that target](https://doc.rust-lang.org/cargo/reference/unstable.html#build-std) and even then, there's no guarantee that it will work.

**Comment by jieyouxu** [comment]
For these kind of questions, it's more likely for you to get an answer in the rust [URLO](https://users.rust-lang.org/)/[Discord](https://discord.gg/rust-lang) next time.

**Comment by Hellosuna** [comment]
Thanks
