### ISSUE TITLE
BTreeMap uses Global allocator in it's PhantomData even when instantiated with custom Allocator

### ISSUE THREAD

**Issue by shamatar** [rust-lang/rust#121797]
I'm referring to this particular line https://github.com/rust-lang/rust/blob/d3d145ea1cae47ad392173f890577788117da3d9/library/alloc/src/collections/btree/map.rs#L183

Even though in `no_std` environments Global as a structure exists and is defined, and it only shows up in PhantomData, the use of the structure is most likely undefined if `#[global_allocator]` attribute is never used. Yes, there will be no calls to Global as it's only a phantom, and execution will not be affected, but just seems ill-defined at least.

For completeness: compilation of code that uses `alloc::collection::BTreeMap` with custom allocator under `#![feature(btreemap_alloc)]` is not affected, and there is no sign of runtime bugs.

**Comment by shamatar** [comment]
My issue is the opposite - it should be 
```
_marker: PhantomData<crate::boxed::Box<(K, V), A>>,
```
in the PhantomData too, but not implicit
```
_marker: PhantomData<crate::boxed::Box<(K, V), Global>>,
```

**Comment by ChayimFriedman2** [comment]
I understand, but it already includes `A` for dropck, so why should it include it in the `PhantomData` too?

**Comment by shamatar** [comment]
To avoid inclusion of Global that has no logical relation to the BTreeMap instance with custom allocator

**Comment by shamatar** [comment]
If it's accepted as a bug I can quickly fix it, at least it passes tests
