### ISSUE TITLE
error: Unable to update registry `crates-io`

### ISSUE THREAD

**Issue by luislucena16** [rust-lang/rust#121791]
- I don't recognise my ssh key from github, when I do an `upload-build-bpf` why could it be?

**Comment by jieyouxu** [comment]
This issue report as it currently stands does not contain enough information to be actionable. This is also the issue tracker for the rust compiler, not cargo or GitHub.

- If you think you encountered a cargo issue, you can open an issue over at <https://github.com/rust-lang/cargo>.
- If you need help with SSH keys from GitHub, consider consulting <https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent> or contacting GitHub support.
- If you need help with `cargo build-bpf` (which is not affiliated with rust-lang), please open an issue over at <https://github.com/solana-labs/solana/tree/master>.

If you have more information pertaining to an issue affecting the rust compiler, I can re-open this issue.

**Comment by luislucena16** [comment]
hi @jieyouxu thank you for your suggestion! I have attached more information in the issue about the problem, steps and possible solution I have found. I hope this works for you!

I also did some reports where you suggested, as for GitHub I changed the SSH key to set a new one to rule out if it was that but it still doesn't work for me!

**Comment by jieyouxu** [comment]
> hi @jieyouxu thank you for your suggestion! I have attached more information in the issue about the problem, steps and possible solution I have found. I hope this works for you!
> 
> I also did some reports where you suggested, as for GitHub I changed the SSH key to set a new one to rule out if it was that but it still doesn't work for me!

Judging from the error message, you have an incorrect SSH key type. In particular, it is SHA-1 which is no longer permitted.

```
ERROR: You're using an RSA key with SHA-1, which is no longer allowed.
```

Try generating a new SSH key for GitHub that is of another type, something like ed25519. Consult the GitHub docs on generating a SSH key for specifics.

**Comment by luislucena16** [comment]
> > hi @jieyouxu thank you for your suggestion! I have attached more information in the issue about the problem, steps and possible solution I have found. I hope this works for you!
> > I also did some reports where you suggested, as for GitHub I changed the SSH key to set a new one to rule out if it was that but it still doesn't work for me!
> 
> Judging from the error message, you have an incorrect SSH key type. In particular, it is SHA-1 which is no longer permitted.
> 
> ```
> ERROR: You're using an RSA key with SHA-1, which is no longer allowed.
> ```
> 
> Try generating a new SSH key for GitHub that is of another type, something like ed25519. Consult the GitHub docs on generating a SSH key for specifics.

I am using SHA256 I have already checked and actually changed it!

**Comment by luislucena16** [comment]
hey @jieyouxu solved!! took your recommendation and changed it to `ed25519` and it worked for me! thank you so much!
