### ISSUE TITLE
`./x check library/std --target=aarch64-kmc-solid_asp3` spuriously requires binaries to be in `PATH`

### ISSUE THREAD

**Issue by ChrisDenton** [rust-lang/rust#121867]
When `./x check library/std --target=aarch64-kmc-solid_asp3` this panics with:

```rust
thread 'main' panicked at src/core/sanity.rs:58:13:


couldn't find required command: "aarch64-kmc-elf-gcc"
```

It seems it requires  `aarch64-kmc-elf-ar` and `aarch64-kmc-elf-gcc` even though that is not necessary for `check`. This can be worked around by creating empty files, marking them as executable and putting them in `PATH` because they're never actually called.

**Comment by bjorn3** [comment]
This check is done for all targets: https://github.com/rust-lang/rust/blob/2dceda4f32b97f60b122f2b32491e0267ef5cc0c/src/bootstrap/src/core/sanity.rs#L181 Note that on many targets it actually is needed even for check mode as build scripts will still compile some C code even in check mode.

**Comment by ChrisDenton** [comment]
Hm, well i did a bunch of checks on "weird" (aka tier 3?) targets and this was the only one that was a blocker for me. `x86_64-unknown-hermit`, `wasm32-unknown-unknown`, `x86_64-fortanix-unknown-sgx`, etc all worked fine.

**Comment by bjorn3** [comment]
Wasm32 is explicitly excluded from this requirement a couple lines above the linked code. For the rest of the targets it may be that they use gcc rather than target-triple-gcc as C compiler by default, thus seemingly working, but producing object files for the wrong OS. The solid target spec explicitly specifies aarch64-kmc-elf-gcc as linker.

**Comment by ChrisDenton** [comment]
But in this case they definitely aren't used. An empty file with the executable bit set definitely isn't producing any output.

**Comment by onur-ozkan** [comment]
> This can be worked around by creating empty files, marking them as executable and putting them in PATH because they're never actually called.

This seems to be more of a workaround than a proper solution (not really sure of there are any). And makes bootstrap more complicated to avoid it's own rules.

Perhaps we could make some adjustments to the target sanity check, but then there might be complications as mentioned by bjorn3:

> Note that on many targets it actually is needed even for check mode as build scripts will still compile some C code even in check mode.

**Comment by onur-ozkan** [comment]
I just remember we have `BOOTSTRAP_SKIP_TARGET_SANITY` for this. You could simply execute `BOOTSTRAP_SKIP_TARGET_SANITY=1 x check library/std --target=aarch64-kmc-solid_asp3` which should work just fine.

I need to list/document all these configurations somewhere..

**Comment by ChrisDenton** [comment]
Ah thanks. I did not know about `BOOTSTRAP_SKIP_TARGET_SANITY`. This does allow me to check all the libstd targets.
