### ISSUE TITLE
Devise a way to test spans

### ISSUE THREAD

**Issue by sanxiyn** [rust-lang/rust#12182]
There are minimal tests in libsyntax unit tests, but they are 1. nowhere near comprehensive, 2. extremely painful to read and write.

**Comment by sanxiyn** [comment]
UI test (added in #33588) can test spans now.

Still, I think UI test can't test spans not used by diagnostics. Such spans can still affect rustfmt, for example.

**Comment by steveklabnik** [comment]
Triage: not aware of any changes

**Comment by estebank** [comment]
Current status:
 - [We have a way to test spans visual output](https://github.com/rust-lang/rust/blob/master/src/libsyntax/test_snippet.rs)
 - We have a way to test the UI output for the entire test suite
 - We have a way to test the code generated from applying suggestions (`.fixed` test files when adding `// run-rustfix` to test file)

@steveklabnik @sanxiyn do you think we can close this ticket given this?

**Comment by steveklabnik** [comment]
Sounds good to me. Let's close! <3
