### ISSUE TITLE
Feature: A separate type for measuring thread time 

### ISSUE THREAD

**Issue by artech-git** [rust-lang/rust#121869]
Had this thought regarding if we can infer the time it takes for object to be executed in a given OS thread context, instead of relying on the `std::time::Instant` to obtain the time elapsed which won't take into account things such as context switch etc etc, therefore I would like to propose a thought  `ThreadTime` a type which may keep track of the time spent by itself on a given thread context excluding all the context switching mechanism..

internally it may look like so

```rust
pub struct ThreadTime { 
    duration: ThreadDuration, 
    thread: SomeThreadTypeRecorder
}
```
through this we can avoid using `ThreadLocal<T>` types directly which may wrap duration between itself, and then maybe we continue the computation, this can be especially useful if you wish to use it in the some struct where you wish to track time in precision.
and should have `!Sync` enabled, let me know is it a useful idea ?

**Comment by ChrisDenton** [comment]
Library feature requests like this are better suited as an API Change Proposal (ACP). These will be discussed by the libs team. You can create one here: https://github.com/rust-lang/libs-team/issues/new/choose

I guess some big questions to answer would be:

* Does this need to be in std rather or would it be ok to do in a crate?
* Can it be done cross-platform?

**Comment by artech-git** [comment]
Honestly @ChrisDenton I too don't have any answer for the first, but maybe having a third party crate could be amazing since lot's  of legacy crates can incorporate this directly, perhaps or might be missing some details, for the second one I believe It should be nice to have platform agnostic and a unanimous type, but if that's not possible then the scope could be limited for application part.
