### ISSUE TITLE
std::env::args should work in wasm32-unknown-emscripten staticlibs

### ISSUE THREAD

**Issue by curiousdannii** [rust-lang/rust#121883]
I have a somewhat unusual project in that I am building a staticlib in Rust, but this staticlib contains the `main` function.

I tried this code:

```rust
let args: Vec<String> = env::args().collect();
```

I expected to see this happen: for `args` to have the arguments provided to Emscripten (or at least it's default arguments, which is the program name).

Instead, this happened: `args` is 0 length.

So what I think is happening is that the unix system bindings are used, as emscripten is listed here:
https://github.com/rust-lang/rust/blob/e612d079a1102803fd2cae5dcd7f7f277e493b8e/library/std/src/sys/pal/unix/args.rs#L66

But the code which sets up `ARGV_INIT_ARRAY` doesn't run in emscripten:
https://github.com/rust-lang/rust/blob/e612d079a1102803fd2cae5dcd7f7f277e493b8e/library/std/src/sys/pal/unix/args.rs#L109-L111

I tried copying that code into my own code, but I got this error (and of course it doesn't have access to `really_init` either):

```
error: statics with a custom `#[link_section]` must be a simple list of bytes on the wasm target with no extra levels of indirection such as references
  --> remglk_capi/src/systems/emglken.rs:79:1
   |
79 | / static ARGV_INIT_ARRAY: extern "C" fn(
80 | |     std::os::raw::c_int,
81 | |     *const *const u8,
82 | |     *const *const u8,
83 | | ) = {
   | |_^
```

Pure C Emscripten projects have no issues accessing the args, so this is something that should be possible in Rust as well.

I already have some C support code in my app, so I might see if I can manually access the args and return them to Rust.

### Meta

`rustc --version --verbose`:
```
rustc 1.76.0 (07dca489a 2024-02-04)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: x86_64-unknown-linux-gnu
release: 1.76.0
LLVM version: 17.0.6

```

**Comment by bjorn3** [comment]
> I tried copying that code into my own code, but I got this error (and of course it doesn't have access to really_init either):

Even if it didn't error, it would crash at runtime as the signature for `.init_array` entries is `extern "C" fn()`, not `extern "C" fn(c_int, *const *const u8, *const *const u8)`. On native targets glibc can pass extra arguments just fine, but on wasm there is a strict function signature check for calls preventing this trick. And even on native targets glibc is the only libc which does this. Musl does not do this.

> Pure C Emscripten projects have no issues accessing the args, so this is something that should be possible in Rust as well.

If you were to compile a bin rather than a staticlib accessing the program arguments should work. For staticlib it wouldn't work on pure C emscripten libraries either as no `main` function would be called to pass the arguments too. If you still need access to arguments from a staticlib you have to manually pass the arguments to the function in the staticlib you want to call.

**Comment by curiousdannii** [comment]
Thank you for your explanation about `.init_array` - it's clear that method isn't possible with wasm. My hypothesis was wrong, but that's is okay.

-----------------

So I tried a `[[bin]]` crate, and `main` is compiled as 

```
(func $main (export "main") (type $t0) (param $p0 i32) (param $p1 i32) (result i32)
```

This matches a pure-Emscripten project when `main` is in a C staticlib and then linked into a C app:

```
(func $main (export "F") (type $t1) (param $p0 i32) (param $p1 i32) (result i32)
```

Where as when `main` is in a Rust staticlib and then linked into a C app it's

```
(func $main (export "main") (type $t11)
```

Now I might have misunderstood what you wrote, but I can't see any strong reason why it should matter to Rust if `main` is in a staticlib vs a bin, in both cases the `main` function can still be compiled with the two params.

**Comment by bjorn3** [comment]
When building a bin, the `main` function is not the `main` function you wrote, but a compiler generated shim which takes `argc` and `argv`, initializes the standard library and then calls the `your_bin::main` function you wrote. When building a staticlib, you added `#[no_mangle]` to make your own function directly be called `main`. In this case the compiler shim doesn't exist and the function signature matches exactly what you wrote (which is no `argc` and `argv` arguments) If you want those `argc` and `argv` arguments in the staticlib case you need to write `#[no_mangle]` extern "C" fn main(argc: c_int, argv: *const *const c_char) -> c_int` yourself just like you would in C (except in C it would be written as the equivalent `int main(int argc, char **argv)`.

**Comment by curiousdannii** [comment]
Ah, yes, that makes sense. And just to confirm, it works in x86_64-unknown-linux-gnu not because the shim is getting inserted, but through the `.init_array` approach?

Without `#[no_mangle]` the code is unused (and presumably DCEd). And with `#[no_mangle]` it really has to be exported as is, or else it's breaking the promise of `#[no_mangle]`. It does seem like the only option is to use that signature for `main`, and then process it manually.

Thank you so much for helping me diagnose this problem! It doesn't even seem like this is something that could be improved with better documentation because it involves such an odd intersection of factors that there's no obvious place to write about it. At least now there's this question, which someone else might find in their searches.
