### ISSUE TITLE
Way to organize modules is not possible at the root of a project

### ISSUE THREAD

**Issue by dasifefe** [rust-lang/rust#121946]
I opened this issue first on https://github.com/rust-lang/cargo/issues/13482, but I was guided to open it here. This is the issue:

### Problem

In the root of a project (`src/main.rs` / `src/lib.rs`), it is not possible to treat `main.rs` or `lib.rs` as Rust files with their own "pair" of folders that will contain submodules.

This is possible:
```
src/
    main.rs
    moduleA.rs
    moduleA/
        ...
    moduleB.rs
    moduleB/
```

This is not possible:

```
src/
    main.rs
    main/
        moduleA.rs
        moduleA/
        moduleB.rs
        moduleB/
```

Cargo will only accept accept `main.rs` or `lib.rs` having submodules if these submodules are placed side-by-side with `main.rs` or `lib.rs`. For deeper modules in the directory structure, you can organize modules in this way:

```
src/
    main.rs
    moduleA.rs <- The module*.rs can only be put side-by-side with main.rs
    moduleA/
        submodule1.rs
        submodule1/
            sub_submodule1.rs <-- However sub_submodule*.rs can be placed inside the folder of submodule*.rs.
            sub_submodule1/
        submodule2.rs
        submodule2/
    moduleB.rs
    moduleB/
```

### Proposed Solution

My solution is to allow the same arrangement to be also allowed at the root. It creates consistency across the entire project arrangement:

In a binary:
```
src/
    main/
        moduleA.rs
        moduleA/
            ...
        moduleB.rs
        moduleB/
    main.rs
```

In a library:
```
src/
    lib/
        moduleA.rs
        moduleA/
            ...
        moduleB.rs
        moduleB/
    lib.rs
```
### Minimal Reproduction of the Problem

Here: https://github.com/dasifefe/cargo-should-allow-this-structure-at-root

I made two versions:
`src_fails` is the one that fails, but I believe that this organization **should** be possible, as it is consistent with what is possible to do in the deeper nesting of a project.
`src_succeeds` is a version that compiles.

Rename any of these to `src/` and try it out.

In the version that fails, Cargo cannot find `lib/foo.rs` nor `lib/bar.rs`, because the Cargo never tries to find a folder with the same name as the root file (`main/` for a `main.rs` or `lib/` for a `lib.rs`).

This is part of the error message that we get:

```
error[E0583]: file not found for module `bar`
 --> src/lib.rs:3:1
  |
3 | mod bar; // Cargo cannot find this module, because it expects it to be side-by-side with `lib.rs` or be a folder containing `mod.rs`.
  | ^^^^^^^^
  |
  = help: to create the module `bar`, create file "src/bar.rs" or "src/bar/mod.rs"
  = note: if there is a `mod bar` elsewhere in the crate already, import it with `use crate::...` instead

error[E0583]: file not found for module `foo`
 --> src/lib.rs:6:1
  |
6 | mod foo; // Cargo cannot find this module, because it expects it to be side-by-side with `lib.rs` or be a folder containing `mod.rs`.
  | ^^^^^^^^
  |
  = help: to create the module `foo`, create file "src/foo.rs" or "src/foo/mod.rs"
  = note: if there is a `mod foo` elsewhere in the crate already, import it with `use crate::...` instead

error[E0412]: cannot find type `FooThing` in this scope
  --> src/lib.rs:10:14
   |
10 |     pub foo: FooThing,
   |              ^^^^^^^^ not found in this scope

error[E0412]: cannot find type `BarThing` in this scope
  --> src/lib.rs:11:14
   |
11 |     pub bar: BarThing,
   |              ^^^^^^^^ not found in this scope
```

The `src_succeeds/` works because I created a "dummy" module side-by-side to `lib.rs`, which `lib.rs` first imports, and then that module imports the others.

**Comment by jieyouxu** [comment]
This is definitely going to [require an RFC](https://github.com/rust-lang/rfcs), and the rustc issue tracker is not suitable for handling those. You should consider proposing this feature request in [Rust Internals](https://internals.rust-lang.org/) and/or open a topic in the [T-lang zulip stream](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang) to discuss your idea.
