### ISSUE TITLE
deadlock ice: missing thread name

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#122035]
I noticed that when parallel rustc panics due to deadlock, it would say `thread 'unnamed' panicked` instead of `thread 'rustc' panicked`.

Is this intended?

**Comment by ChrisDenton** [comment]
Hm, I did recently land [a related std change](https://github.com/rust-lang/rust/pull/121666/files) but I'm not sure if it would cause this issue. It should only affect threads that Rust doesn't create itself and in any case it switches the default name from `None` (which gets rendered as `<unnamed>`) to the OS thread name (if available). So if anything I'd have thought it would have the opposite effect.

Though maybe there's something about parallel deadlocks I'm missing.

**Comment by matthiaskrgr** [comment]
I think you're good since the problem is older than your pr :D
https://github.com/rust-lang/rust/issues/120759

**Comment by ChrisDenton** [comment]
Oh good! I mean bad, but I was dreading a very long debugging session 😆

**Comment by matthiaskrgr** [comment]
well, if you feel bored or something.... :upside_down_face:

**Comment by Nilstrieb** [comment]
Serial rustc creates a single thread called rustc. I assume parallel rustc just doesn't name its rayon threads, no debugging session ahead.

**Comment by Zoxc** [comment]
We create a new thread to look for query cycles, it's unnamed at the moment and that's where the panic happens.
