### ISSUE TITLE
typo on E0699

### ISSUE THREAD

**Issue by lmascelli** [rust-lang/rust#122085]
`error[E0699]: cannot call a method on a raw pointer with an unknown **pointee** type`

**Comment by jieyouxu** [comment]
Pointee means "the data or object referenced by a pointer", I don't think it's a typo?

**Comment by fmease** [comment]
Not a typo. Cf. Interviewer (one who interviews) <-> interviewee (one who is interviewed).

Pointer (sth. that points to sth.), pointee (sth. that is pointed at by sth.).
