### ISSUE TITLE
`x86-interrupt-abi` seems to duplicate statics, sometimes

### ISSUE THREAD

**Issue by Kyllingene** [rust-lang/rust#122127]
I'm developing a small kernel, but I uncovered a seeming issue with the `x86-interrupt` ABI and statics, and in RPLCS I was advised to share this here. In the project, I've got several interrupt handlers, and these interact with various statics, in order to pass information along; however, the interrupts and normal code are being exposed to different instances of the statics.

I have three: `WRITER`, `SCANCODE_QUEUE`, and `TIMER_COUNT`. All are in `kernel/src`; first is in `io/vga.rs`, second two in `interrupt/handlers.rs`, along with the interrupt handlers. Here are the steps to reproduce:

1. `git clone https://github.com/kyllingene/rikos`
2. `cd rikos/kernel`
3. `cargo build`
4. `nm ../target/x86_64-unknown-none/debug/libkernel.a | grep "WRITER|SCANCODE_QUEUE|TIMER_COUNT"`

My output:
```
                 U _ZN6kernel2io3vga6WRITER17h2055e0aaa786b39cE
                 U _ZN6kernel9interrupt8handlers14SCANCODE_QUEUE17h4290668693eee639E
                 U _ZN6kernel2io3vga6WRITER17h2055e0aaa786b39cE
                 U _ZN6kernel2io3vga6WRITER17h2055e0aaa786b39cE
0000000000000000 B _ZN6kernel9interrupt8handlers11TIMER_COUNT17h237aced2821850c4E
0000000000000000 B _ZN6kernel9interrupt8handlers14SCANCODE_QUEUE17h4290668693eee639E
                 U _ZN6kernel9interrupt8handlers11TIMER_COUNT17h237aced2821850c4E
0000000000000000 D _ZN6kernel2io3vga6WRITER17h2055e0aaa786b39cE
```

Given the docs on `x86-interrupt-abi` and statics, I cannot find anything detailing that statics might be duplicated, nor was this the behavior before (this kernel was made some months ago, but I'm not certain exactly when since I was not using VC then).

When I run `cargo build` in the crate root, and run the same `nm` command on `rikos/image/boot/kernel.bin` instead, I get this:

```
0000000000143358 D _ZN6kernel2io3vga6WRITER17h20cb9489244a903cE
00000000001444a0 D _ZN6kernel2io3vga6WRITER17h9de1a9d6aa729135E
00000000001525d0 b _ZN6kernel9interrupt8handlers11TIMER_COUNT17h71b16ec029ed1bdbE
0000000000152670 B _ZN6kernel9interrupt8handlers14SCANCODE_QUEUE17h223e67a2a2e9ad63E
00000000001525d8 b _ZN6kernel9interrupt8handlers14SCANCODE_QUEUE17h238c381fab57bf8aE
```

Those addresses line up with what I've observed using `core::ptr::addr_of!` debug prints, with the exception that `TIMER_COUNT` should have a second instance (at `0000000000152670`).

If this only happened post-build-script, I'd assume it was an issue with another part of my toolchain. As it is, I'm unable to come up with an MRE, but given this occurs when building `rikos/kernel` alone (which has no build script), I see nothing else this could be.

```shell
kyllingene@kyllingene ~/p/r/rikos (master)> cargo --version
cargo 1.78.0-nightly (f772ec022 2024-03-01)
kyllingene@kyllingene ~/p/r/rikos (master)> rustc --version
rustc 1.78.0-nightly (7d3702e47 2024-03-06)
```

**Comment by zachs18** [comment]
I think the problem is that you have `os` and `kernel` as separate `artifact = "staticlib"` deps, but `os` depends on `kernel`, so `kernel` is getting compiled and linked into the final binary twice when you link together `libos.a` and `libkernel.a` in your build script.

**Comment by Kyllingene** [comment]
Ah, that would make sense. Let me see what I can do to fix that. I wonder why this was never an issue in the past, though (or if I introduced `os` late enough that I never noticed it was an issue). Apologies for my misunderstanding of the `nm` output, though!

**Comment by zachs18** [comment]
> if that's the case, why does my code in kernel still reference both statics?

Presumably, it is accessing the static linked in from `libkernel.a` in functions linked in from `libkernel.a`, and it is accessing the static linked in from `libos.a` in functions linked in from `libos.a`.

Applying this patch

```patch
diff --git a/kernel/src/lib.rs b/kernel/src/lib.rs
index fe9da9c..f7f2581 100644
--- a/kernel/src/lib.rs
+++ b/kernel/src/lib.rs
@@ -27,6 +27,7 @@ static BOOT_INFO: OnceCell<BootInformation<'static>> = OnceCell::uninit();
 
 #[no_mangle]
 extern "C" fn kernel_main(multiboot_info_addr: usize) {
+    serial_println!("WRITER addr in kernel {:p}", &vga::WRITER);
     println!("initializing kernel");
     println!("loading multiboot2 info");
 
diff --git a/os/src/lib.rs b/os/src/lib.rs
index 537cc65..5f867cf 100644
--- a/os/src/lib.rs
+++ b/os/src/lib.rs
@@ -13,6 +13,7 @@ use keyboard::getch;
 use crate::keyboard::Key;
 
 fn welcome() {
+    serial_println!("WRITER addr in os {:p}", &vga::WRITER);
     vga::clear();
 
     #[cfg(debug_assertions)]
```

and running `cargo -Z bindeps test` shows that yes, the kernel and os code see different addresses for `WRITER`:

```shell
$ cargo -Zbindeps test
// snip
     Running src/test.rs (target/debug/deps/test-cb093081e295146c)
WRITER addr in kernel 0x12c780
kernel addr of TIMER_COUNT: 0x136000
WRITER addr in os 0x12d8b8
len: 0
// snip
```

Not entirely sure why `kernel_main` doesn't give a duplicated symbol error though.

**Comment by Kyllingene** [comment]
Well, thank you for your help! Since this doesn't seem to be a Rust issue, I'll close (if the duplicated symbol error not appearing is a bug, that's for another issue).
