### ISSUE TITLE
 custom toolchain Unable to compile aarch64-linux-android

### ISSUE THREAD

**Issue by androiddisk** [rust-lang/rust#122146]
```
root@5208dbdba07f:/projects/userspace/ksud# rustup  target list
error: toolchain 'ollvm-rust-1.70.0' does not support components: ollvm-rust-1.70.0 is a custom toolchain
root@5208dbdba07f:/projects/userspace/ksud# rustup  target add aarch64-linux-android
error: toolchain 'ollvm-rust-1.70.0' does not support components: ollvm-rust-1.70.0 is a custom toolchain
```

**Comment by androiddisk** [comment]
```
python3 x.py build --target x86_64-unknown-linux-gnu,aarch64-linux-android
```
thread 'main' panicked at '

couldn't find required command: "aarch64-linux-android-clang"

', sanity.rs:59:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Build completed unsuccessfully in 0:01:00

**Comment by saethlin** [comment]
Yes you cannot add components to a custom toolchain. How did you get this custom toolchain?

**Comment by androiddisk** [comment]
> Yes you cannot add components to a custom toolchain. How did you get this custom toolchain?

Compiling Android binary requires the source code of the toolchain rust-1.67, which supports such commands

**Comment by saethlin** [comment]
I do not think that is correct. Who told you that?

**Comment by androiddisk** [comment]
> I do not think that is correct. Who told you that?

After the correct configuration file indicates Android ndk, it can be successfully compiled
