### ISSUE TITLE
Bootstrap: verify that `--target` and `--host` triples are valid before starting a build

### ISSUE THREAD

**Issue by tgross35** [rust-lang/rust#122128]
I ran `./x dist --target mips64-openwrt-linux-musl --host x86_64-unknown-linux-gnu` twice with slight different typos in the `--host` argument. Unfortunately, this takes about half an hour to detect (stage2, LLVM builds) and changing the host seems to invalidate some of the build.

Bootstrap can't actually query `rustc` for the target list, but it would be great if it could verify the triple string exists somewhere in `compiler/rustc_target/src/spec/mod.rs` as a sanity check before kicking off a multistage build.

@rustbot label +T-bootstrap +E-easy  -needs-triage

**Comment by bjorn3** [comment]
The target may only exist in the compiler that will be built, so bootstrap would need to parse https://github.com/rust-lang/rust/blob/42825768b103c28b10ce0407749acb21d32abeec/compiler/rustc_target/src/spec/mod.rs#L1401-L1689 for this check. And I think it also needs to allow json target specs.

**Comment by Rajveer100** [comment]
@bjorn3 
What would be the right place to detect this, i.e, to disallow initiating the build at the beginning itself if the `--target` or `--host` triple is invalid?

**Comment by bjorn3** [comment]
Other sanity checks are done in https://github.com/rust-lang/rust/blob/master/src/bootstrap/src/core/sanity.rs

**Comment by Rajveer100** [comment]
I believe the checks are being done here:

https://github.com/rust-lang/rust/blob/703dc9ce64d9b31a239a7280d9b5f9ddd85ffed6/src/bootstrap/src/core/sanity.rs#L162

https://github.com/rust-lang/rust/blob/703dc9ce64d9b31a239a7280d9b5f9ddd85ffed6/src/bootstrap/src/core/sanity.rs#L188

Although, I am not quite sure about `!build.config.dry_run()` here?

Since there are limited number of targets, do we just create some constant structure to store this and just map if it does not have any typos?

**Comment by tgross35** [comment]
I think you found the correct locations for such a check.

> Although, I am not quite sure about `!build.config.dry_run()`?

`./x` takes a `--dry-run` flag that doesn't build anything. These checks should run even on dry run, so don't worry about that.

> Since there are limited number of targets, do we just create some constant structure to store this and just map if it does not have any typos?

You could probably just use regex to extract a target list from the file linked in https://github.com/rust-lang/rust/issues/122128#issuecomment-1985986339, then add a check that the specified hosts and targets all exist in that list.

**Comment by onur-ozkan** [comment]
> You could probably just use regex to extract a target list from the file linked in https://github.com/rust-lang/rust/issues/122128#issuecomment-1985986339, then add a check that the specified hosts and targets all exist in that list.

This approach is too straightforward; custom targets will fail from this logic.

**Comment by tgross35** [comment]
Do we have custom target info available early? If not, even a warning that something isn't in the list would be helpful here

**Comment by onur-ozkan** [comment]
> Do we have custom target info available early? If not, even a warning that something isn't in the list would be helpful here

We do. https://github.com/rust-lang/rust/issues/71009 can be a good ref to this.

Also, I don't think reading list from the compiler source file will be a good idea. Why not using someting like `rustc --print target-list`? That can give the built-in target list for the stage 0 compiler.

**Comment by Rajveer100** [comment]
@onur-ozkan 
I see this function:

https://github.com/rust-lang/rust/blob/61aeab4c9ece6b40e3941665bc9e695922e2ad25/src/librustc_back/target/mod.rs#L293

Do we just use this for the search part?

**Comment by bjorn3** [comment]
That is a 10 year old commit...

**Comment by Rajveer100** [comment]
When you say custom targets did you mean when we have some architecture (like arm) with certain properties differing from the standard definition (like target-endian, linker, etc.)?

**Comment by onur-ozkan** [comment]
> When you say custom targets did you mean when we have some architecture (say arm_64) with certain properties differing from the standard definition (like target-endian, linker, etc.)?

You can indeed do such stuff, but I wouldn't  restrict the purpose of "custom-targets" with that. There is this documentation https://docs.rust-embedded.org/embedonomicon/custom-target.html if you want to read more about it.

**Comment by Rajveer100** [comment]
As you mentioned, the regex approach wouldn't cover the custom targets that are made by the user in json format, so I currently see tests for this here:

https://github.com/rust-lang/cargo/pull/5228/files

Could you elaborate the custom target approach, I mean the only thing we have to check if the json file exists at the mentioned user path and whether each of the attributes under it are valid? 

For the default targets we just check in the static file as mentioned earlier.

**Comment by bjorn3** [comment]
For custom targets I would avoid checking if the attributes are valid. Validating them is a lot more complicated and can give false positives too when an attribute is newly introduced.

**Comment by onur-ozkan** [comment]
> Could you elaborate the custom target approach, I mean the only thing we have to check if the json file exists at the mentioned user path and whether each of the attributes under it are valid?

The logic for validating the target name can be as follows:

- First, check if the target exists in the built-in target list.
- If not, check if it's a custom target (by verifying if a target specification JSON file was provided).

If none of the above returns true, then either the user forgot to provide the target specification JSON file for the custom target or made a typo in the target name.
