### ISSUE TITLE
stage0 run-make compiletest broken 

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#122196]
`COMPILETEST_FORCE_STAGE0=1 ./x.py test --stage 0 tests/run-make` no longer works. `librun_make_support.rlib` is compiled using the bootstrap rustc wrapper which sets `--sysroot build/$HOST_TRIPLE/stage0-sysroot`, but then compiletest will compile `rmake.rs` using the sysroot of the bootstrap compiler causing it to not find the `libstd.rlib` against which `librun_make_support.rlib` is compiled.

This regressed with https://github.com/rust-lang/rust/pull/113026. (cc @jieyouxu)

**Comment by bjorn3** [comment]
See also https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/stage0.20compiletest.20broken

**Comment by jieyouxu** [comment]
From the zulip comment
> Pass the right --sysroot when compiling rmake.rs, use the bootstrap rustc wrapper in compiletest too? Or something else?

Passing the right `--sysroot` might be the least disruptive solution, but I'm not sure if this is the best solution.
