### ISSUE TITLE
`x86_64-gnu-llvm-16 ` is run on one every pr pre approval

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#122278]
Looks like every PR that is opened now triggers a `x86_64-gnu-llvm-16` run. presumably by mistake?

https://github.com/rust-lang/rust/pull/122277
![ripci](https://github.com/rust-lang/rust/assets/476013/60e496e7-7d90-477c-9b7b-8e74a40a5bdc)

**Comment by matthiaskrgr** [comment]
It just seemed weird that docs change would trigger a llvm build..??

**Comment by clubby789** [comment]
I'm pretty sure those 4 CI jobs have been run unconditionally on every PR for a long time (although 3 years ago it was LLVM 15)

**Comment by matthiaskrgr** [comment]
ah ok, closing then :+1:
