### ISSUE TITLE
x.py test --bless tidy step does not work outside of root dir

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#122202]
I tried this: In a subdirectory `root/objdir/`, after a successful build, I then did `../x.py test --stage 1 --bless`

I expected to see this happen: *The test files that need updating get updated."

Instead, this happened: *tidy panicked*

```
[...]
tidy check
thread 'ui_tests (tests)' panicked at src/tools/tidy/src/ui_tests.rs:191:77:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src/tools/tidy/src/main.rs:55:61:
called `Result::unwrap()` on an `Err` value: Any { .. }
```

I believe this is because of this code, which seems to contain an assumption that the current_dir will be the root of the source tree, which is not true in general for `x.py`:

https://github.com/rust-lang/rust/blob/74acabe9b042ea8c42862ee29aca2a8b7d333644/src/tools/tidy/src/ui_tests.rs#L187

**Comment by erer1243** [comment]
x.py in general assumes you are in the root. It's not just tidy. E.g. building from a subdir will not use the existing build artifacts in /build

**Comment by onur-ozkan** [comment]
> x.py in general assumes you are in the root.

Not really. Many people work from outside the root (including me). Path for the build directory is entirely different story and can be configured.
