### ISSUE TITLE
`x.py test mir-opt --bless` does not bless some tests

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#122292]
To reproduce, simply edit the file `tests/mir-opt/pre-codegen/checked_ops.checked_shl.PreCodegen.after.mir` and then run `x.py test mir-opt --bless`. I'd expect the file to be changed back, but actually it is left unchanged.

Interestingly, `x.py test mir-opt` does check that file. This is on a x86-64 host, and the test is marked `needs-unwind` and `only-x86_64`. `--bless` adds a bunch of extra targets to bless, seems like my default target `x86_64` with unwinding is not one of them though?

`--bless` should make sure to always bless the configuration that is tested without `--bless`.

**Comment by Nadrieril** [comment]
> --bless should make sure to always bless the configuration that is tested without --bless.

That's resolved by https://github.com/rust-lang/rust/pull/122257. It does not however resolve your issue
