### ISSUE TITLE
Regression on nightly: Cross compiling to x86_64-pc-windows-gnu fails

### ISSUE THREAD

**Issue by VorpalBlade** [rust-lang/rust#122228]
I tried this code (on Arch Linux, as well as in GitHub CI using "ubuntu-latest"):

```shell
git clone https://github.com/VorpalBlade/ini-merge.git
cd ini-merge
git checkout 0f4696241825c17faf4d63f2e19bdccabc1ccc51
cross test --target x86_64-pc-windows-gnu # This works, rustc 1.76
cross +nightly test --target x86_64-pc-windows-gnu # This fails with the error below.
```

I expected to see this happen: *explanation*
The build to work. Note that plain "build" still works, it is just "test" and "test  --no-run" that no longer works on nightly.

Instead, this happened: *explanation*
```
  = note: /usr/bin/x86_64-w64-mingw32-ld: cannot find -lsynchronization
          collect2: error: ld returned 1 exit status
```

(full log from CI run where this happened attached: [mingw-broken.txt](https://github.com/rust-lang/rust/files/14537046/mingw-broken.txt))

### Meta

`rustc --version --verbose`:
```console
$ rustc --version --verbose
rustc 1.78.0-nightly (46b180ec2 2024-03-08)
binary: rustc
commit-hash: 46b180ec2452d388c5d9c14009442e2e0beb01d7
commit-date: 2024-03-08
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0


$ cross +nightly --version --verbose
cross 0.2.5
+ cargo +nightly metadata --format-version 1
+ rustc --print sysroot
+ rustup toolchain list
[cross] warning: using newer rustc `1.78.0-nightly (46b180ec2 2024-03-08)` for the target. Current active rustc on the host is `rustc 1.76.0 (07dca489a 2024-02-04)`.
 > Update with `rustup update`
+ rustup target list --toolchain nightly-x86_64-unknown-linux-gnu
+ rustup component list --toolchain nightly-x86_64-unknown-linux-gnu
[cross] note: Falling back to `cargo` on the host.
+ cargo +nightly --version --verbose
cargo 1.78.0-nightly (a4c63fe53 2024-03-06)
release: 1.78.0-nightly
commit-hash: a4c63fe5388beaa09e5f91196c86addab0a03580
commit-date: 2024-03-06
host: x86_64-unknown-linux-gnu
libgit2: 1.7.2 (sys:0.18.2 vendored)
libcurl: 8.6.0-DEV (sys:0.4.72+curl-8.6.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Arch Linux Rolling Release [64-bit]
```

<details><summary>Backtrace</summary>
<p>

```
This doesn't seem applicable?
```

</p>
</details>

**Comment by VorpalBlade** [comment]
I don't know for sure if this is a rustc bug, a cross bug or a bug with mingw. But since the only variable I'm changing is rustc version, I'm inclined to believe it is a rustc bug.

**Comment by mati865** [comment]
It looks like a regression from https://github.com/rust-lang/rust/pull/121317.
It might be a cross bug because the library has been present in mingw-w64 and Rust's rust-mingw component for years. I'll test it later.

**Comment by VorpalBlade** [comment]
Apparently cross are treating it as their bug: https://github.com/cross-rs/cross/issues/1453

**Comment by mati865** [comment]
Great, I think there is no reason to keep this issue open.
