### ISSUE TITLE
Add support for visualization of build steps

### ISSUE THREAD

**Issue by jieyouxu** [rust-lang/rust#122336]
Context: <https://rust-lang.zulipchat.com/#narrow/stream/196385-t-compiler.2Fwg-rustc-dev-guide/topic/.5Breading.20club.5D.202023.2E02.2E26.20chapters.2022.20to.2030/near/423408022>

Could build steps be visualized? There is `--dry-run -vv` but it might be nice in graphical format like a `.dot` file. I realize that there might be *a lot* of build steps so this might not be practical or too useful.

**Comment by onur-ozkan** [comment]
It's definitely interesting, but I'm not sure if it's worth it.
