### ISSUE TITLE
Implement collect_with_capacity for Iter?

### ISSUE THREAD

**Issue by PaulDotSH** [rust-lang/rust#122348]
Hi, a simple implementation of `collect_with_capacity` would be helpful to reduce boilerplate, a simple way I am doing this in my projects is
```rust
trait CollectWithCapacity: Iterator {
    fn collect_with_capacity<T>(self, capacity: usize) -> Vec<Self::Item>
        where
            Self: Sized + Iterator<Item = T>,
    {
        let mut vec = Vec::with_capacity(capacity);
        vec.extend(self);
        vec
    }
}

impl<T: ?Sized> CollectWithCapacity for T where T: Iterator {}
```

Is there any reason something similar to this is not part of the standard library?

**Comment by workingjubilee** [comment]
@PaulDotSH I have no idea why you would implement it that way given that your API is capable of feeding in a wrong capacity to `with_capacity` that is not guaranteed to match the size of the iterator, which is a considerable deoptimization compared to allocating with the correct capacity, which is what `.collect()` will do by default.

**Comment by the8472** [comment]
> compared to allocating with the correct capacity, which is what .collect() will do by default.

Specifically the [FromIterator implementation for Vec](https://doc.rust-lang.org/nightly/std/vec/struct.Vec.html#impl-FromIterator%3CT%3E-for-Vec%3CT%3E) will use [Iterator::size_hint](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.size_hint).

**Comment by Nilstrieb** [comment]
Closing, as this information is already used. If you're not satisfied with that, I recommend checking out https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html for how to proceed.
