### ISSUE TITLE
Regression with variadic starting with nightly-2024-02-14

### ISSUE THREAD

**Issue by jeromerobert** [rust-lang/rust#122310]
### Code

I tried this code (`bug.rs`):

```rust
use std::ffi::c_int;

extern "C" {
    fn bug_c_func(foo: c_int, ...);
}

fn main() {
    let mut n1: c_int = 0;
    unsafe { bug_c_func(0, &n1); }
    assert!(n1 == 42);
    println!("OK");
}
```

Which call this C code (`bug.c`):
```C
#include <stdarg.h>

void bug_c_func(int foo, ...)
{
    va_list var_arg;
    va_start(var_arg, foo);
    int * ptr1 = va_arg(var_arg, int *);
    va_end(var_arg);
    *ptr1=42;
}
```

Compiled using this C compiler:

```
$ gcc --version
gcc (Debian 13.2.0-13) 13.2.0
```

with

```
gcc --shared bug.c -o libbug.so
```

The bug can only be reproduced with `-C opt-level=3`. I build the test with:
```
rustc -C opt-level=3 -L. -lbug bug.rs
```

I expected to see this happen:

```
OK
```

Instead, this happened:
```
thread 'main' panicked at bug.rs:10:5:
assertion failed: n1 == 42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Version it worked on

It most recently worked on `nightly-2024-02-13`:
```
rustc 1.78.0-nightly (b381d3ab2 2024-02-12)
binary: rustc
commit-hash: b381d3ab27f788f990551100c4425bb782d26d76
commit-date: 2024-02-12
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 17.0.6
```

### Version with regression

The regression can be reproduced with `nightly-2024-02-14` to `nightly-2024-03-10` (at least):

`rustc --version --verbose`:
```
rustc 1.78.0-nightly (a84bb95a1 2024-02-13)
binary: rustc
commit-hash: a84bb95a1f65bfe25038f188763a18e096a86ab2
commit-date: 2024-02-13
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0
```

**Comment by workingjubilee** [comment]
@jeromerobert Your example contains UB. You mutate an immutable variable. Using varargs does *not* change this. Please provide a reproducer that does not incur UB.

**Comment by jeromerobert** [comment]
@workingjubilee Thank you. I just tried with `mut` and updated the issue description accordingly. It does not change anything.

**Comment by jeromerobert** [comment]
ah but passing the variable as `&mut` fix it.

**Comment by workingjubilee** [comment]
Yes, your second example takes an immutable, shared reference to a mutable variable, unfortunately.

I strongly advise using [`ptr::addr_of_mut`](https://doc.rust-lang.org/std/ptr/macro.addr_of_mut.html) when producing raw pointers to things you wish to mutate, in general. It is less UB-prone for various reasons.

It _seems like_ there is nothing to fix here? Unless there was somewhere in particular you were referencing while drafting this example, I have no idea where we would even document this concern adequately that isn't stated in triplicate in more general places, combined with the age-old wisdom: varargs let you shoot yourself in the foot with ambiguous argument types, It Is Known.

**Comment by jeromerobert** [comment]
I agree. I'm closing the issue. Thank you very much for this so fast answer.

**Comment by workingjubilee** [comment]
Thank you for being understanding! Please feel free to open requests for better documentation if you do find a place in the docs regarding varargs where we could clarify something specifically about them.
