### ISSUE TITLE
Is it sound to send an Rc if you are the sole owner?

### ISSUE THREAD

**Issue by CryZe** [rust-lang/rust#122452]
I have a data structure that contains a bunch of hot single threaded code. It internally manages a bunch of `Rc<T>` where `T: Send + Sync`. It fully owns those reference counted values, they are never exposed to the outside world. The only way to interact with my data structure is through `&mut self`, i.e. only a single thread at the given time can run code that deals with those referenced values. Considering how fully contained everything is and how only a single thread at a time can interact with it, it should be sound to make this data structure both `Sync` and `Send`... at least at the moment.

I'm seeing a potential future where `Rc` uses a global thread local heap allocator that allocates and deallocates its T values on a thread local heap, which would be faster considering no synchronization inside the allocator is necessary to allocate and deallocate. If `Rc` would indeed switch to such an allocator in the future by default, then you can't ever send an `Rc` soundly from one thread to another, as it would use the wrong thread local heap allocator for deallocating the `Rc`.

What's interesting is that at least currently the documentation guarantees that the raw pointers used by `Rc<T>` (with the default allocator) must be from the global allocator, meaning that no such switch to a thread local heap allocator would be possible by default (though arguably it could be the same global allocator, just with a `fn alloc_thread_local`).

![image](https://github.com/rust-lang/rust/assets/1451630/17ebfa18-ddee-4f94-a042-f831a7d9ea7b)

Therefore I'd like to clarify whether sending an `Rc<T>` where `T: Send` is sound (and maybe that could be documented as a guarantee) or not. And if not, and the avenue for a potential thread local heap allocator is kept open, then maybe the documentation should also be adjusted to not lock us into the truly global heap allocator.

**Comment by Noratrieb** [comment]
This is an old discussion without answers, closing. Questions like this are better asked on Zulip than the issue tracker. But I suspect that the answer here is "yes".
