### ISSUE TITLE
cannot compile rust project offline using nightly toolchain

### ISSUE THREAD

**Issue by randomuygvruyv65423654** [rust-lang/rust#122413]
I'm trying to compile the redox_uefi project which requires the nightly-2023-09-07 toolchain, on an offline system. There does not appear to be any way to do this. The rustup-init binary requires an internet connection and I don't see anywhere to find the source code for this specific release to build from source. Please advise if there is another way to do this or else take this as a bug report to please include offline functionality for rustup or whatever other toolchain manager which is preferred in this case.

**Comment by oli-obk** [comment]
You can find offline installers at https://forge.rust-lang.org/infra/other-installation-methods.html#standalone

On https://www.rust-lang.org/learn/get-started you need to click "Other installation methods" to find this page

**Comment by randomuygvruyv65423654** [comment]
The installers on that page are for version 1.76.0. What I need is version nightly-2023-09-07. I finally managed to find it, but had to do a fair bit of digging. https://static.rust-lang.org/dist/2023-09-07/
