### ISSUE TITLE
document-hidden-items should show when items are hidden

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#122485]
document-private-items shows a `pub(crate)` / empty on methods, and a :lock: on types in the module interface.

We should do the same for hidden items with document-hidden-items, perhaps showing `#[doc(hidden)]` on methods and a :ghost:  in the types list.

Thoughts?

(n.b. document-hidden-items is currently `-Zunstable-options`)

**Comment by GuillaumeGomez** [comment]
I think it's a pretty good idea. :+1:
