### ISSUE TITLE
Unclear error message when using . in format string

### ISSUE THREAD

**Issue by Alon0709** [rust-lang/rust#122535]
I tried this code:

```rust
    let x = (1, 2, 3);
    println!("{x.0}",);
```

I expected to see this happen: printing of the value 1.

Instead, this happened: it gave the following error:

> invalid format string: expected `'}'`, found `'.'`
if you intended to print `{`, you can escape it using `{{`rustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20%5B0%5D?0#file%3A%2F%2F%2Fhome%2FalonPc%2FDesktop%2Fprojects%2FRustLearning%2Fvariables%2Fsrc%2Fmain.rs)

### Meta

`rustc --version --verbose`:
```
1.76.0
```

**Comment by Nilstrieb** [comment]
Only printing an identifer is supported, arbitrary expressions are not: https://rust-lang.github.io/rfcs/2795-format-args-implicit-identifiers.html

**Comment by Nilstrieb** [comment]
There's more discussion about this in https://internals.rust-lang.org/t/how-to-allow-arbitrary-expressions-in-format-strings/15812 or in many other places, it's a thing that keeps coming up.

**Comment by Nilstrieb** [comment]
The error message could be nicer, so I'll convert it into a diagnostics issue.
