### ISSUE TITLE
warn on ptr::copy with zero-sized type

### ISSUE THREAD

**Issue by LinusDikomey** [rust-lang/rust#122697]
### Code

```Rust
fn main() {
    let src = ();
    let mut dst = ();
    unsafe { std::ptr::copy(&src, &mut dst, 1) };
}
```

### Current output

```Shell
Runs fine without warnings
```

### Desired output

```Shell
Add a warning when using `ptr::copy`/`ptr::copy_nonoverlapping` with zero-sized types (especially the unit type).
```

### Rationale and extra context

This can happen easily when inter-operating with C libraries since they often use void pointers. Also, `memcpy` in C takes in void pointers so people might think the same pattern works in Rust.

### Rust Version

```Shell
rustc 1.78.0-nightly (a165f1f65 2024-03-12)
binary: rustc
commit-hash: a165f1f65015b1bd4afd2ec50700aaacf2e0c485
commit-date: 2024-03-12
host: aarch64-apple-darwin
release: 1.78.0-nightly
LLVM version: 18.1.0
```

**Comment by workingjubilee** [comment]
@LinusDikomey It is perfectly valid to copy a zero-sized type. In general, we try not to carry lints which would lint on a lot of valid code, even if the pattern seems unusual in, say, C.

`()` is not `c_void`. The following tests pass: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=96e635ab49632c8faa61d6e6362993dd

```rust
use core::{ffi, mem::size_of};

#[test]
fn c_void_is_size_1() {
    assert_eq!(size_of::<ffi::c_void>(), 1);
}

#[test]
fn c_void_is_not_unit_sized() {
    assert_ne!(size_of::<ffi::c_void>(), size_of::<()>());
}
```

If someone starts with a pointer to `c_void`, they will in fact copy the `n` bytes indicated by the final argument to `copy_nonoverlapping(src, dst, n)`, just like they would with `memcpy(dst, src, n)` (but note the argument order). Are you sure you are asking for the diagnostics you want?
