### ISSUE TITLE
Disable const-stability checking for intrinsics with fallback MIR?

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#122652]
As suggested in https://github.com/rust-lang/rust/pull/122582#discussion_r1527445673, I moved my new intrinsic to `core::intrinsics`.  But that meant I started getting a new error:

```rust
error: `typed_swap` is not yet stable as a const fn
   --> library\core\src\mem\mod.rs:731:14
    |
731 |     unsafe { intrinsics::typed_swap(x, y) }
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Is that error useful for things with fallback MIR that's already const-checked?  Could we skip it?

(Maybe doing that in the same PR that would make CTFE capable of using fallback MIR?)

cc @oli-obk

**Comment by oli-obk** [comment]
This is just stability, you can mark intrinsics as const stable without the intrinsic itself becoming stable

**Comment by RalfJung** [comment]
Your fallback body uses a const-unstable function, so this is still not an intrinsic we'd want to allow calling from stable const fn. So IMO it makes sense that you would have to write `#[rustc_const_unstable]` here, you'd have to write the same if this was a regular function.

We could consider doing something special for intrinsics where the fallback body is entirely stable. But OTOH, adding a quick `#[rustc_const_stable_intrinsic]` (with https://github.com/rust-lang/rust/pull/132492) isn't too much of a big deal either, I think.

**Comment by RalfJung** [comment]
Turns out with the new const stability checks this actually isn't that hard -- we just have to ensure that fallback bodies are recursively const-stability checked, and then we can take this into account when const-checking an intrinsic call.
