### ISSUE TITLE
Discriminant update fails to optimize

### ISSUE THREAD

**Issue by joboet** [rust-lang/rust#122600]
The following code should optimize to a single store of the new discriminant, but doesn't ([Godbolt](https://godbolt.org/z/E356rdbf7)).
```rust
enum State {
    A([u8; 753]),
    B([u8; 753]),
    //C,
}

unsafe fn update(s: *mut State) {
    let S::A(v) = s.read() else { unreachable_unchecked() };
    s.write(S::B(v));
}
```
Instead, LLVM copies the value to the stack, copies it again and then writes it back. Interestingly, LLVM optimizes this correctly if a third state without value is added.

### Meta

`rustc --version --verbose`:
```
rustc 1.78.0-nightly (c67326b06 2024-03-15)
binary: rustc
commit-hash: c67326b063bd27ed04f306ba2e372cd92e0a8751
commit-date: 2024-03-15
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0
```

**Comment by matthiaskrgr** [comment]
lol, looks like this optimizes with `-Zmir-opt=1/0` but fails to with anything equals or above 2, I think 2 or 3 is the default for `release` builds?

**Comment by clubby789** [comment]
Replacing `unreachable_unchecked` with `return` also optimizes better:
```x86asm
init:
        test    byte ptr [rdi], 1
        jne     .LBB0_2
        mov     byte ptr [rdi], 1
.LBB0_2:
        ret
```

Presumably some issue with MIR inlining

**Comment by saethlin** [comment]
The problem is not MIR inlining. This is the problem @DianQK was trying to fix in https://github.com/rust-lang/rust/pull/122282; if you write your own `unreachable_unchecked` function without a runtime check, it optimizes fine: https://godbolt.org/z/6oYqrhEs9

**Comment by DianQK** [comment]
Upstream issue: https://github.com/llvm/llvm-project/issues/85560

@rustbot claim   :p

**Comment by nikic** [comment]
Confirmed fixed by https://github.com/rust-lang/rust/pull/127513, needs codegen test.
