### ISSUE TITLE
RwLock slow since nightly-2024-02-13

### ISSUE THREAD

**Issue by mfuhr** [rust-lang/rust#122626]
### Code

I tried this code:

```rust
use std::io::{self, Write};
use std::sync::RwLock;
use std::thread;
use std::time::{Duration, Instant};

fn main() {
    let read_sleep = Duration::from_millis(1000);
    let write_sleep = Duration::from_millis(10);

    let lock = RwLock::new(0);

    thread::scope(|s| {
        s.spawn(|| loop {
            print!("acquire read lock...");
            io::stdout().flush().unwrap();
            let start = Instant::now();
            let n = lock.read().unwrap();
            let elapsed = start.elapsed();
            println!("elapsed={elapsed:?}, n={n}");
            drop(n);
            thread::sleep(read_sleep); // sleep without holding lock
        });

        loop {
            let mut n = lock.write().unwrap();
            *n += 1;
            thread::sleep(write_sleep); // sleep while holding lock
        }
    });
}
```

I expected to see this happen:

Read lock acquire times around 10ms, the amount of time that the writer thread holds the lock:

```
acquire read lock...elapsed=12.500958ms, n=1
acquire read lock...elapsed=12.530792ms, n=83
acquire read lock...elapsed=7.209959ms, n=165
acquire read lock...elapsed=10.207542ms, n=247
acquire read lock...elapsed=9.651917ms, n=329
acquire read lock...elapsed=11.431375ms, n=411
```

Instead, this happened:

Long read lock acquire times (write lock times appear to be unaffected):

```
acquire read lock...elapsed=11.705254458s, n=943
acquire read lock...elapsed=1.173358583s, n=1120
acquire read lock...elapsed=4.203342334s, n=1540
acquire read lock...elapsed=8.130360667s, n=2274
acquire read lock...elapsed=1.093665458s, n=2444
acquire read lock...elapsed=2.092220375s, n=2693
```

### Version it worked on

It most recently worked on: Rust 1.76.0, 1.77.0-beta.9, and nightly-2024-02-12

### Version with regression

Slowness started with nightly-2024-02-13 and persists in the latest nightly.

`rustc --version --verbose`:
```
rustc 1.78.0-nightly (766bdce74 2024-03-16)
binary: rustc
commit-hash: 766bdce744d531267d53ba2a3f9ffcda69fb9b17
commit-date: 2024-03-16
host: aarch64-apple-darwin
release: 1.78.0-nightly
LLVM version: 18.1.2
```

**Comment by Nilstrieb** [comment]
@joboet

**Comment by mfuhr** [comment]
Changing `lock.read()` to `lock.write()` exhibits the same slow lock acquisition.

This is a much-simplified example of a program whose writes are relatively frequent and time-consuming compared to its reads.

**Comment by Amanieu** [comment]
The new rwlock implementation prefer writers, which is generally the preferred behavior since most workloads are read-heavy and it avoids writer starvation when the reads overlap.

If your workload is so write-heavy that reads are rare then you may want to consider just using a plain mutex instead.

**Comment by Amanieu** [comment]
Actually even a mutex won't help. Your example has one thread hold a write lock for a full 10ms and then unlocks it only for a few nanoseconds. The window for readers to acquire a lock is tiny, and no new readers will acquire the lock once a writer is waiting to acquire the lock.

**Comment by mfuhr** [comment]
> The new rwlock implementation prefer writers, which is generally the preferred behavior since most workloads are read-heavy and it avoids writer starvation when the reads overlap.

Thanks; I wondered if the change was due to something like this.  This particular program has only one writer and one reader, with the writes being frequent and time-consuming and the reads infrequent.  I previously experimented with using channels instead of locks, where the reader would send a request for the data and the writer would occasionally call `try_recv()` while the data was in a consistent state and send back a clone upon receiving a request.  I saw no performance improvement with that approach but I'm now seeing why it might be preferable.  I'm also playing with [parking_lot::RwLock](https://docs.rs/parking_lot/latest/parking_lot/type.RwLock.html) which purports to avoid starvation in situations like this.

**Comment by Amanieu** [comment]
If you only have 1 reader then there is no reason to be using a rwlock: just use a mutex.

**Comment by mfuhr** [comment]
> If you only have 1 reader then there is no reason to be using a rwlock: just use a mutex.

I should have qualified my statement: the program <i>currently</i> has only one reader; it might have more in the future.

**Comment by Amanieu** [comment]
Fundamentally if you workload involve keeping a write lock held 99% of the time and only releasing it for short periods, then using a RwLock is the wrong approach. You may want to consider a different design where you have 2 copies of the data: one which can be mutated by writers and one that is "published" for use by readers. This allows readers to use a (possible stale) copy of the data without blocking on writers (except for the short period where the data is "published").

In the end, I don't think this is a bug in RwLock so much as incorrect use of it.
