### ISSUE TITLE
Coroutine state transform `check_must_not_suspend_ty` ignores allocator field of `Box`

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#122643]
This code here has a potential issue:

https://github.com/rust-lang/rust/blob/010f3944e0f0baac8d738da49772fd06acd3701b/compiler/rustc_mir_transform/src/coroutine.rs#L1967-L1977

If the Box has a custom allocator, then that will not be checked at all. So whatever `check_must_not_suspend_ty` is used for, it ignores anything stored in custom allocators.

It seems like this is just for a lint, so this is probably not critical, but I guess should still be fixed.

Cc @cjgillot -- not sure whom else to ping for coroutine state machine transform things?

**Comment by RalfJung** [comment]
Cc @compiler-errors @tmiasko  (also a regular occurrence in this file's `git log`)

**Comment by compiler-errors** [comment]
Lol sorry, I thought I had clicked enter on a comment but I must've not. Let me rewrite it.

> It seems like this is just for a lint, so this is probably not critical, but I guess should still be fixed.

Yeah, this is approximately the level of urgency you determined. This code exists for an unstable lint, `must_not_suspend`. I don't expect people to be writing `Box<T, MyAllocatorWhichShouldntBeHeldAcrossAwaitPoints>`, but technically they could.
