### ISSUE TITLE
Put "checks that detect UB" under their own flag below `debug_assertions`

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#122678]
This tracks the implementation of https://github.com/rust-lang/compiler-team/issues/725. See there for all the details.

**Comment by saethlin** [comment]
> Initially it would be unstable as `-Zub-checks`, and `cfg(ub_checks)`

https://github.com/rust-lang/rust/pull/123411 achieves this. The MCP describes a stable flag, and waiting for `cfg(overflow_checks)` to be stabilized. I do not intend to work on those, so I'm unassigning myself.

**Comment by RalfJung** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/123499.
