### ISSUE TITLE
Incorrect string handling of a file.

### ISSUE THREAD

**Issue by pramatias** [rust-lang/rust#122783]
[empack7-modus-vivendi-tinted-0ry-theme.txt](https://github.com/rust-lang/rust/files/14670321/empack7-modus-vivendi-tinted-0ry-theme.txt)

Someone can try simple to remove the last line using this code.
```rust
fn remove_last_line(file_path: &PathBuf) -> io::Result<()> {
    // Read the entire content of the file
    let file = File::open(file_path)?;
    let lines: Vec<String> = io::BufReader::new(file).lines().filter_map(|line| line.ok()).collect();

    // Remove the last line
    let mut modified_content = lines.iter().take(lines.len() - 1).map(|s| s.as_str()).collect::<Vec<&str>>().join("\n");

    // Open the file for writing
    let mut file = File::create(file_path)?;

    // Write the modified content back to the file
    file.write_all(modified_content.as_bytes())?;

    Ok(())
}

```

I expected remove_last_line to work exactly like using the head command and it works perfectly.

```rs
fn remove_last_line(file_path: &PathBuf) -> io::Result<()> {
    let output = Command::new("head")
        .args(&["-n", "-1"])
        .arg(&file_path)
        .output()?;

    if output.status.success() {
        // Write the output (except the last line) back to the file
        std::fs::write(&file_path, &output.stdout)?;
        Ok(())
    } else {
        Err(io::Error::new(io::ErrorKind::Other, "Failed to execute head command"))
    }
}
```

Instead when the string is removed, it removes more strings irrelevant to the deletion

### Meta

`rustc --version --verbose`:
```
rustc 1.76.0 (07dca489a 2024-02-04)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: x86_64-unknown-linux-gnu
release: 1.76.0
LLVM version: 17.0.6
```

</p>
</details>

**Comment by pramatias** [comment]
Also, someone can try the srgn command as a more simple way to verify:
`cat empack7-modus-vivendi-tinted-0ry-theme.txt | srgn --literal-string "^l ends here^" ""`
and just try to remove the last string. I converted the file to ASCII to be sure it's not a Unicode issue.

**Comment by clubby789** [comment]
Can you be more specific? Your code seems to work fine for me (diff below)
```diff
diff --git a/file.bak b/file
index 7da4283..88afc4e 100644
--- a/file.bak
+++ b/file
@@ -511,5 +511,4 @@ represents."
 
   (provide-theme 'empack7-modus-vivendi-tinted-0ry))
 
-;;; modus-vivendi-tinted-theme.el ends here
-l ends here
+;;; modus-vivendi-tinted-theme.el ends here
\ No newline at end of file
```
The only difference is that there is no trailing newline, which you could add manually. https://users.rust-lang.org/ might be more appropriate for debugging code issues.

**Comment by workingjubilee** [comment]
@pramatias Your problem is that you use [`slice::join`](https://doc.rust-lang.org/std/primitive.slice.html#method.join), which is documented here:

> Flattens a slice of T into a single value Self::Output, placing a given separator **between** each.

The bolding is mine. "Between each" is not "after each", so it does not add the trailing newline because you did not ask it to.

If you have a different bug report, please feel free to open a new issue.

**Comment by pramatias** [comment]
Thanks @workingjubilee for testing it. 

I installed srgn by cargo-binstall, which i didn't compile myself. That's where i discovered the bug. Then i wrote some testing code myself, the remove_last_line using BufReader, and the problem persists. 

Only when i used remove_last_line using the external command "head" the bug disappeared. That's why i reported the bug, i thought it's a Rust bug probably. 

For the moment i only tested it on Ubuntu 22.04, but i will test it further on more linux distributions, it may be the case that it's a Debian/Ubuntu bug. Of course i will try also more rust versions and nigthly, and maybe i will pinpoint exactly where the problem is.

I was stuck for almost 4 hours on that bug, so i would like that to be solved. I will open a new issue when i am successful at replicating it.

**Comment by workingjubilee** [comment]
@pramatias Based on what you have said, it is not. Please file the issue with the srgn repo.

**Comment by pramatias** [comment]
Oh right, you are saying that my BufReader implementation has a bug in it, and most probably it is the same (or similar) bug in srgn? 

That makes sense. I will report the bug to the srgn repo.

**Comment by pramatias** [comment]
@workingjubilee , sorry forgot to mention. See my previous answer.

**Comment by workingjubilee** [comment]
@pramatias I have already said everything that I am going to say.
