### ISSUE TITLE
builtin arithmetic ops should be inlined when used in a generic function

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#12279]
The basic operations on the built-in types compile to inferior code in generic functions without `--opt-level=2` for heuristic-based inlining. The library should define these operations in the same way to avoid a distinction as not inlining them only slows down compile-time and doesn't aid in debugging.

**Comment by steveklabnik** [comment]
triage: as far as I can tell, the IR for a generic and specific `a + b` are different, and so nothing has changed here.

**Comment by arielb1** [comment]
Does not *seem* to be relevant for Rust 1.3+ - could you provide an example?

**Comment by arielb1** [comment]
Actually, this is talking about:
```Rust
fn foo<T: Add>(t: T) { t + t }
fn main() { t(4u32); }
```

**Comment by jfager** [comment]
Triage:  still produces slower code without `-O` ([godbolt link](https://godbolt.org/g/emePCa)).

**Comment by rkruppe** [comment]
Triage: Still true. Smaller test program (no I/O or formatting): https://godbolt.org/g/B9t75L

**Comment by bluss** [comment]
Current impl is [here](https://doc.rust-lang.org/nightly/src/core/ops/arith.rs.html#92-98); is it really just about using inline(always) here? Any drawbacks to that?

```rust
macro_rules! add_impl {
    ($($t:ty)*) => ($(
        #[stable(feature = "rust1", since = "1.0.0")]
        impl Add for $t {
            type Output = $t;

            #[inline]
            #[rustc_inherit_overflow_checks]
            fn add(self, other: $t) -> $t { self + other }
        }

        forward_ref_binop! { impl Add, add for $t, $t }
    )*)
}
```

**Comment by Mark-Simulacrum** [comment]
Performance of compile times and run times was gathered based on #62095 but no measureable difference whether `inline(always)` is applied or not could be determined, so I'm closing this issue.
