### ISSUE TITLE
suggested fix for undeclared hrtb lifetimes in where clauses in produces error "[E0316] nested quantification of lifetimes" when specified just before the trait

### ISSUE THREAD

**Issue by polina4096** [rust-lang/rust#122714]
### Code

```Rust
trait Trait<T>
  where T: for<'a> Trait<T> + 'b { }
```

### Current output

```Shell
error[E0261]: use of undeclared lifetime name `'b`
 --> src/lib.rs:2:31
  |
2 |   where T: for<'a> Trait<T> + 'b { }
  |                               ^^ undeclared lifetime
  |
  = note: for more information on higher-ranked polymorphism, visit https://doc.rust-lang.org/nomicon/hrtb.html
help: consider making the bound lifetime-generic with a new `'b` lifetime
  |
2 |   where for<'b> T: for<'a> Trait<T> + 'b { }
  |         +++++++
help: consider introducing lifetime `'b` here
  |
1 | trait Trait<'b, T>
  |             +++
```

### Desired output

```Shell
error[E0261]: use of undeclared lifetime name `'b`
 --> src/lib.rs:2:31
  |
2 |   where T: for<'a> Trait<T> + 'b { }
  |                               ^^ undeclared lifetime
  |
  = note: for more information on higher-ranked polymorphism, visit https://doc.rust-lang.org/nomicon/hrtb.html
help: consider making the bound lifetime-generic with a new `'b` lifetime
  |
2 |   where T: for<'a, 'b> Trait<T> + 'b { }
  |                  ++++
help: consider introducing lifetime `'b` here
  |
1 | trait Trait<'b, T>
  |             +++
```

### Rationale and extra context

HRTB lifetimes can be put not only before the constrained type (`for<...> T: ...`), but also just before the constraining trait (`T: for<...> Trait ...`). When in this position, compiler suggests code which produces error "[E0316] nested quantification of lifetimes" as it ignores the existing HRTB just before the trait and only looks at constraint HRTB.

### Rust Version

```Shell
$ rustc --version --verbose
rustc 1.76.0 (07dca489a 2024-02-04)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: aarch64-apple-darwin
release: 1.76.0
LLVM version: 17.0.6
```

**Comment by surechen** [comment]
I think this should suggest :

```rust
trait Trait<'b, T>
  where T: for<'a> Trait<'b, T> + 'b { }
```

Because `'b` is bound for `T`

**Comment by polina4096** [comment]
> I think this should suggest :
> 
> ```rust
> trait Trait<'b, T>
>   where T: for<'a> Trait<'b, T> + 'b { }
> ```
> 
> Because `'b` is bound for `T`

It already does suggest that, I think

**Comment by fmease** [comment]
`where T: for<'a, 'b> Trait<T> + 'b` isn't valid either tho b/c `for<>` after `:` only universally quantifies (i.e., introduces universal parameters) for the trait ref immediately following the binder meaning `'b` in `+ 'b` is still undefined.

We should keep the preexisting `trait Trait<T, 'b>` suggestion (which does indeed lead to follow-up errors unfortunately) and maybe suggest:

```rs
- where T: for<'a> Trait<T> + 'b
+ where for<'a, 'b> T: Trait<T> + 'b
```

removing the inner binder (which might be a bit harder to do). The outer binder to the left of the `:` quantifies the entire bound.
