### ISSUE TITLE
rustdoc incorrectly evaluates and fails due to panic in zerocopy

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#122758]
This code:

```rust
extern crate zerocopy;

pub use std::cell::RefMut as LockGuard;
```

with Cargo.toml:

```
[package]
name = "test-rustdoc-bug"
version = "0.1.0"
edition = "2021"

[dependencies]
zerocopy = "0.7.32"
```

produces the following error:

```
$ RUSTDOCFLAGS="-Zunstable-options --document-hidden-items" cargo +nightly doc
 Documenting test-rustdoc-bug v0.1.0 (/Users/mark/test-rustdoc-bug)
error[E0080]: evaluation of `<std::cell::RefMut<'_, [u8]> as zerocopy::ByteSlice>::INTO_REF_INTO_MUT_ARE_SOUND` failed
    --> /Users/mark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zerocopy-0.7.32/src/lib.rs:5238:9
     |
5238 |         panic!("Ref::into_ref and Ref::into_mut are unsound when used with core::cell::RefMut; see https://github.com/google/zerocopy/issues/716")
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'Ref::into_ref and Ref::into_mut are unsound when used with core::cell::RefMut; see https://github.com/google/zerocopy/issues/716', /Users/mark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zerocopy-0.7.32/src/lib.rs:5238:9
     |
     = note: this error originates in the macro `$crate::panic::panic_2015` which comes from the expansion of the macro `panic` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0080`.
error: could not document `test-rustdoc-bug`
```

This seems to happen on all(?) of current stable (1.77), beta (1.78), and nightly (1.79, 3c85e5624 2024-03-18) but I'm suspicious that there's some kind of new breakage here in 1.78, because this broke rust-lang/rust's CI on similar code (in rustc_data_structures): https://github.com/rust-lang/rust/pull/122754#issuecomment-2008485406 while performing a bump of the bootstrap compiler from 1.77 to 1.78. This minimal example appears to reproduce across all versions. Tagging this as a regression for now despite lacking a minimal reproducer demonstrating that.

I think this is likely a bug of some kind in rustdoc regardless, because presumably it's not intentional that we should fail to document (benign-looking) code like this.

**Comment by Mark-Simulacrum** [comment]
https://github.com/Mark-Simulacrum/rust/commit/eb7c25417d7365ae9a27d1a335bafc308560f77a works locally to resolve this bug, probably by just avoiding the relevant code path in rustdoc.

**Comment by algora-pbc** [comment]
💎 **Kapple140** is offering a **$10** bounty for this issue
👉 Got a pull request resolving this? Claim the bounty by adding `@algora-pbc /claim #122758` in the PR body and joining algora.io

**Comment by GuillaumeGomez** [comment]
This is strange. Tagging the compiler team as well.

**Comment by apiraino** [comment]
I've tried bisecting this error, but results are perhaps a bit iffy. Does any of these commit ring a bell?

Regression in nightly-2023-07-19
converted 2023-07-19 to 903e279f468590fa3425f8aff7f3d61a5a873dbb
```
  commit[0] 2023-07-17: Auto merge of #89132 - Cyborus04:rc_allocator_support, r=Amanieu
  commit[1] 2023-07-18: Auto merge of #113061 - Amanieu:x86_64-ohos, r=compiler-errors
  commit[2] 2023-07-18: Auto merge of #113574 - GuillaumeGomez:rustdoc-json-strip-hidden-impl, r=aDotInTheVoid,notriddle
  commit[3] 2023-07-18: Auto merge of #113801 - compiler-errors:iter-instantiated, r=oli-obk
  commit[4] 2023-07-18: Auto merge of #113659 - ericmarkmartin:smir-refs-and-ptrs, r=spastorino
  commit[5] 2023-07-18: Auto merge of #113677 - bryangarza:unevaluated-const-ice_issue-110892, r=davidtwco
  commit[6] 2023-07-18: Auto merge of #113706 - Alexendoo:compiletest-backslash-re, r=oli-obk
  commit[7] 2023-07-18: Auto merge of #112374 - chenx97:better-mips64r6, r=jackh726
  commit[8] 2023-07-18: Auto merge of #113837 - matthiaskrgr:rollup-v4xud4s, r=matthiaskrgr
  commit[9] 2023-07-18: Auto merge of #113636 - compiler-errors:opaque-recursive-check-bad, r=oli-obk
  commit[10] 2023-07-18: Auto merge of #113841 - weihanglo:update-cargo, r=weihanglo
```

**Comment by Mark-Simulacrum** [comment]
This is hitting the 1.79 promotion too. Probably the fix in https://github.com/Mark-Simulacrum/rust/commit/eb7c25417d7365ae9a27d1a335bafc308560f77a wasn't quite enough -- that did land on master, so it's not entirely missing.

**Comment by GuillaumeGomez** [comment]
With everything going on in rustc_codegen_gcc, didn't have time to take a look yet...

**Comment by GuillaumeGomez** [comment]
Took a look at it and it seems normal. Can be reproduced with this `foo` crate as dependency (no need to have a current crate, just using `foo` as a dependency is enough):

```
[package]
name = "foo"
version = "0.1.0"
edition = "2021"
```

`src/lib.rs`:

```rust
pub const YEP: bool = if !cfg!(doc) {
    panic!("bad");
} else {
    false
};
```

The problem is that the dependencies are built with rustc before being built with rustdoc (to get crate information). So unless `zerocopy` is the final crate, this condition will always at some point be true. Problem seems to be solved in newest `zerocopy` versions so I think we can close this issue.
