### ISSUE TITLE
TAIT: closure and RPIT causes "concrete type differs from previous defining opaque type use"

### ISSUE THREAD

**Issue by Dirbaio** [rust-lang/rust#122775]
Replacing `-> impl Sized` with `-> F` in `fn spawn` makes it compile, so it feels to me the RPIT version should be accepted too.

This is minimized from the [`embassy-executor` task macro](https://github.com/embassy-rs/embassy/blob/7c2aae88da81f4ea34a4228173f474f2c05a2f28/embassy-executor-macros/src/macros/task.rs#L96-L99).

[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=bae2fe30351c6d3c7705404b2fa51849)

```rust
#![feature(type_alias_impl_trait)]

fn spawn<T, F>(future: F) -> impl Sized
where
    F: FnOnce() -> T,
{
    future
}

fn spawn_task(sender: &'static ()) -> impl Sized {
    type Tait = impl Sized + 'static;
    spawn::<Tait, _>(move || sender)
}
```

```
error: concrete type differs from previous defining opaque type use
  --> src/lib.rs:12:30
   |
12 |     spawn::<Tait, _>(move || sender)
   |                              ^^^^^^ expected `Tait`, got `&'static ()`
   |
note: previous use here
  --> src/lib.rs:12:5
   |
12 |     spawn::<Tait, _>(move || sender)
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

bisected:

searched nightlies: from nightly-2024-03-14 to nightly-2024-03-20
regressed nightly: nightly-2024-03-16
searched commit range: https://github.com/rust-lang/rust/compare/f4b771bf1fb836392e1c510a625cdc81be09c952...c67326b063bd27ed04f306ba2e372cd92e0a8751
regressed commit: https://github.com/rust-lang/rust/commit/1ca424ca436d4d4449def39723c9ec442837c370

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.8</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --preserve 
```
</details>

@rustbot label F-type-alias-impl-trait

**Comment by compiler-errors** [comment]
Strange that this is due to 1ca424c. I'll look into this :thinking:

**Comment by compiler-errors** [comment]
This started passing in b234e449443a49ab19ef6b712bf56cc65927d98f. I wonder if it's because we were erroneously defining an opaque to be equal to itself.

**Comment by oli-obk** [comment]
yea looks like it
