### ISSUE TITLE
rustbuild: LLVM is not downloaded from CI after LLVM updates

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#122787]
I tried this code:

```rust
./x build
```

`download-ci-llvm` in config.toml is not specified explicitly, the default value is used.

I expected to see this happen:
- LLVM is downloaded from CI, when LLVM version is bumped the new LLVM is downloaded from CI as well.

Instead, this happened:
- LLVM starts building from source code after an LLVM update, instead of being downloaded, unless I remove the build directory and do a fresh build, then it starts downloading from CI again.

### Meta

`rustc --version --verbose`:
```
$ ./build/x86_64-pc-windows-gnu/stage0/bin/rustc --version --verbose
rustc 1.78.0-beta.1 (efd9d2df1 2024-03-18)
binary: rustc
commit-hash: efd9d2df12b5e17fac0b4d0fb89f612ecd79f259
commit-date: 2024-03-18
host: x86_64-pc-windows-gnu
release: 1.78.0-beta.1
LLVM version: 18.1.2
```

**Comment by petrochenkov** [comment]
The `[llvm]` section in config.toml is completely empty, nothing is overridden.

**Comment by petrochenkov** [comment]
Update: LLVM is built from source only on the first build attempt, after that it is correctly downloaded from CI.

**Comment by petrochenkov** [comment]
@onur-ozkan 
This is still an issue that I observe regularly.

**Comment by onur-ozkan** [comment]
There were some issues with the change detection logic for LLVM and I think https://github.com/rust-lang/rust/pull/127463/commits/2b5a9821eb730ab2e294bc2600af8ee580421e27 should fix it. Let's see if it still happens with the next LLVM update.
