### ISSUE TITLE
Codegen regression in `Ipv6Addr` `[u16; 8]` to `[u8; 16]` conversion

### ISSUE THREAD

**Issue by paolobarbolini** [rust-lang/rust#122805]
### Code

I tried this code:

```rust
// Taken from `Ipv6Addr::new`

pub fn convert1(value: [u16; 8]) -> [u8; 16] {
    let addr16 = [
        value[0].to_be(),
        value[1].to_be(),
        value[2].to_be(),
        value[3].to_be(),
        value[4].to_be(),
        value[5].to_be(),
        value[6].to_be(),
        value[7].to_be(),
    ];
    unsafe { std::mem::transmute::<_, [u8; 16]>(addr16) }
}

pub fn convert2(value: [u16; 8]) -> [u8; 16] {
    let addr16 = value.map(|val| val.to_be());
    unsafe { std::mem::transmute::<_, [u8; 16]>(addr16) }
}
```

I expected to see this happen: *these two pieces of code produced the same assembly*

Instead, this happened: *the first version generates worse code https://rust.godbolt.org/z/qrz7Pn1a7*

### Version it worked on

It most recently worked on: 1.76

### Version with regression

`rustc --version --verbose`:
```
rustc 1.78.0-beta.1 (efd9d2df1 2024-03-18)
binary: rustc
commit-hash: efd9d2df12b5e17fac0b4d0fb89f612ecd79f259
commit-date: 2024-03-18
host: x86_64-unknown-linux-gnu
release: 1.78.0-beta.1
LLVM version: 18.1.2
```

**Comment by DianQK** [comment]
The main branch of LLVM may have been fixed: https://llvm.godbolt.org/z/WzM1dvrTb.

**Comment by workingjubilee** [comment]
This seems to become much better if one uses infallible destructuring, like so: https://rust.godbolt.org/z/csraMobE8

**Comment by workingjubilee** [comment]
Wait, I was comparing 1.76 codegen... it regresses in the beta...?

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23122805.20Codegen.20regression.20in.20.60Ipv6Addr.60.20.60.5Bu16.3B.208.5D.60.20to.20.60.5Bu8.E2.80.A6)).

@rustbot label -I-prioritize +P-medium

**Comment by DianQK** [comment]
I have bisected to https://github.com/llvm/llvm-project/commit/1e828f838cc0f15074f3dbbb04929c06ef0c9729 (https://github.com/llvm/llvm-project/pull/82279). But I'm not sure if this match the backport rules.
