### ISSUE TITLE
tidy always being rebuild with --bless

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#122834]
this works fine:
````
x.py test
x.py test
````
````
x.py test
x.py test --bless
````
this also works

```
x.py test --bless
x.py test --bless
```
this seems to rebuild tidy for the second invocation? as if `--bless` somehow modified tidy itself which then need to be rebuilt?

**Comment by workingjubilee** [comment]
It's probably due to rewriting `issues.txt` with the same data. I hadn't considered that as a serious concern.
