### ISSUE TITLE
c_char on AIX should be u8

### ISSUE THREAD

**Issue by taiki-e** [rust-lang/rust#122985]
Currently, core::ffi::c_char on AIX is i8, but AFAIK, the default of this platform is unsigned (u8).

[XL C for AIX](https://www.ibm.com/docs/en/xl-c-aix/13.1.3?topic=descriptions-qchars):

> Defaults
> -qchars=unsigned

Clang:

```console
$ clang --version
Homebrew clang version 17.0.6

$ clang -E -dM -x c /dev/null -target powerpc64-ibm-aix | grep __CHAR_        
#define __CHAR_BIT__ 8
#define __CHAR_UNSIGNED__ 1
```

Rust:

```
$ tail -2 src/lib.rs 

const C: core::ffi::c_char = 0u8;

$ cargo check -Zbuild-std=core --target powerpc64-ibm-aix
error[E0308]: mismatched types
    --> src/lib.rs:3972:30
     |
3972 | const C: core::ffi::c_char = 0u8;
     |                              ^^^ expected `i8`, found `u8`
     |
help: change the type of the numeric literal from `u8` to `i8`
     |
3972 | const C: core::ffi::c_char = 0i8;
     |                               ~~
```

cc @ecnelises @bzEq ([target maintainers](https://github.com/rust-lang/rust/blob/548e14b43963882fb758deb89e8258d9b8c2fc2a/src/doc/rustc/src/platform-support/aix.md?plain=1#L7))

### Meta

`rustc --version --verbose`:
```
rustc 1.79.0-nightly (2f090c30d 2024-03-23)
binary: rustc
commit-hash: 2f090c30ddd6b3bbe5c81c087579a5166e7c7278
commit-date: 2024-03-23
host: aarch64-apple-darwin
release: 1.79.0-nightly
LLVM version: 18.1.2
```

**Comment by taiki-e** [comment]
I opened https://github.com/rust-lang/libc/pull/3631 and https://github.com/rust-lang/rust/pull/122986 as drafts to fix this, but I want feedback from the target maintainers before undrafting/merging them.

**Comment by taiki-e** [comment]
Ideally, we could detect such a problem in CI by [checking the Clang's default](https://github.com/taiki-e/portable-atomic/blob/62676614c05d16f570c3b656030169f7c4145cab/tools/codegen/src/ffi.rs#L589-L597). However, AFAIK, most tier3 targets are not checked at all in CI at this time (https://github.com/rust-lang/rust/issues/109099), so that would need to be fixed first.

**Comment by bzEq** [comment]
Yes, we should follow clang on AIX's behavior.
