### ISSUE TITLE
Is that even legal? Trait in generics bug?

### ISSUE THREAD

**Issue by patrykstruzek** [rust-lang/rust#122901]
I tried this code:

```rust
use std::string::ToString;
const fn some_const<T: Sized, Dupa, ToString>() {

}
fn main() {

}
```

It shouldn't compile because i don't have any trait anywhere called 'Dupa'.

Instead, compiler allows me to add trait that doesn't exist.

`rustc --version --verbose`:
```
rustc 1.73.0 (cc66ad468 2023-10-03)
binary: rustc
commit-hash: cc66ad468955717ab92600c770da8c1601a4ff33
commit-date: 2023-10-03
host: x86_64-pc-windows-msvc
release: 1.73.0
LLVM version: 17.0.2
```

![obraz](https://github.com/rust-lang/rust/assets/72736082/f4e1a7c3-f812-438e-a7fd-3929cf0e5967)
![obraz](https://github.com/rust-lang/rust/assets/72736082/efa43085-c222-43b8-bbfe-d8ccdf18a8f9)

**Comment by patrykstruzek** [comment]
I have to add that when i delete first trait 'Sized' then it doesn't compile and I receive an error related with that unexisting trait 'Dupa'.

**Comment by workingjubilee** [comment]
@patrykstruzek Your syntax is wrong for trait bounds.

Your code actually describes a function with three generics, which you would find out if you tried to call this const_fn, which btw isn't necessarily guaranteed to be const-evaluated if you don't use it inside a `const ITEM: Type` or `const {}`.

Yes, it's allowed to use `PascalCase` names for generics.

```rust
use std::string::ToString;
const fn some_const<T: Sized, Dupa, ToString>() {

}
fn main() {
    some_const::<i32>()
}
```
emits this error:
```
error[E0107]: function takes 3 generic arguments but 1 generic argument was supplied
 --> src/main.rs:6:5
  |
6 |     some_const::<i32>()
  |     ^^^^^^^^^^   --- supplied 1 generic argument
  |     |
  |     expected 3 generic arguments
  |
note: function defined here, with 3 generic parameters: `T`, `Dupa`, `ToString`
 --> src/main.rs:2:10
  |
2 | const fn some_const<T: Sized, Dupa, ToString>() {
  |          ^^^^^^^^^^ -         ----  --------
help: add missing generic arguments
  |
6 |     some_const::<i32, Dupa, ToString>()
  |                     ++++++++++++++++
```

If you are new to Rust, I suggest doublechecking by asking on StackOverflow or one of the [community discords](https://discord.com/invite/rust-lang-community) first to check if you understand things correctly before filing an issue. We do encourage people to file issues if the diagnostics are confusing, even if there's "nothing wrong", but this is merely a somewhat odd not-an-error.

**Comment by patrykstruzek** [comment]
Oh yes i forgot to call this function.
