### ISSUE TITLE
Something about bootstrap stage0-sysroot broke with libLLVM

### ISSUE THREAD

**Issue by Nilstrieb** [rust-lang/rust#122913]
[backtrace CI](https://github.com/rust-lang/backtrace-rs/blob/6fa4b85b9962c3e1be8c2e5cc605cd078134152b/.github/actions/build-with-patched-std/action.yml#L44) tries to `build --stage 0 library` and then expects to find a rustc in `build/host/stage0-sysroot/bin/rustc` that can compile stuff. This appears to have worked, but does not work anymore. `build/host/stage0-sysroot/lib` only contains the `libLLVM-18-rust-1.78.0-beta.so` linker script, it does not contain the actual library.

I'm not sure how bootstrapping works with that, but uh, it does somehow!

**Comment by Nilstrieb** [comment]
Ah, `build/x86_64-unknown-linux-gnu/stage0/lib/` contains the actual libLLVM.

**Comment by Nilstrieb** [comment]
I don't know whether this is intended or accidental, but something is up. I'm going to change backtrace to use `build/host/stage0` instead, which should hopefully still work.

**Comment by Nilstrieb** [comment]
I worked around it in https://github.com/rust-lang/backtrace-rs/pull/602. It's probably the proper fix anyways. Still weird to have this, so I'll leave the issue open for you to figure out whether this is good and whether it matters.

**Comment by Nilstrieb** [comment]
Nevermind, using that doesn't appear to work correctly, I suspect that this *does* need `stage0-sysroot`. I don't really know the difference tbh so I'm happy to know what would be correct.

**Comment by onur-ozkan** [comment]
This is a recent regression from the bootstrap compiler bump PR #122754.

**Comment by ChrisDenton** [comment]
Has anyone figured out what needs to be copied where and how? The conversation seems a bit spread out over different issues/PRs so I'm wondering what the current status is?

**Comment by onur-ozkan** [comment]
Not yet, I will check it around tomorrow.

**Comment by ChrisDenton** [comment]
Thanks! No rush, I was just uncertain where things stood.
