### ISSUE TITLE
How to use new SIMD rules after 1.78

### ISSUE THREAD

**Issue by jianshu93** [rust-lang/rust#122965]
Dear Rust team,

I rely heavily on Rust stdsimd feature before v1.78 like below:
```rust
#[cfg(feature = "stdsimd")]
use packed_simd::*;


#[cfg(feature = "stdsimd")]
fn distance_l1_f32_simd(va:&[f32], vb: &[f32]) -> f32 {
    //
    let nb_lanes = 16;
    let nb_simd = va.len()/ nb_lanes;
    let simd_length = nb_simd * nb_lanes;
    //
    let dist_simd = va.chunks_exact(nb_lanes)
            .map(f32x16::from_slice_unaligned)
            .zip(vb.chunks_exact(nb_lanes).map(f32x16::from_slice_unaligned))
            .map(|(a,b)| (a - b).abs())
            .sum::<f32x16>();
    //
    let mut dist = dist_simd.sum();
    // residual
    for i in simd_length..va.len() {
        dist = dist + (va[i]- vb[i]).abs();
    }
    return dist as f32;
}  // end of distance_l1_f32_simd
```

How do I quickly port my code to allow it work for 1.78 or after, in which the stdsimd feature has been removed. I do not want to rewrite the function for each instructions like AVX2 AVS512 et.al..

Thanks,

Jianshu

**Comment by workingjubilee** [comment]
@jianshu93 You should try using
```rust
#![feature(portable_simd)]
```

The `packed_simd` crate is fairly... lightly maintained at best.

**Comment by workingjubilee** [comment]
The issue here is not a problem with rustc or the stdlib as it is a breakage in a nightly feature, it is rather due to the `packed_simd` crate not being updated to the latest. It should be transferred to that crate's issues.

**Comment by jianshu93** [comment]
hello all,

I believe the fix does not work and we have to wait for packed_simd to update to v1.78 v1.79. See the error here: https://github.com/rust-lang/packed_simd/issues/360

Is there a plan for update?

Thanks,

Jianshu
