### ISSUE TITLE
Should `core` import the 2021 prelude?

### ISSUE THREAD

**Issue by dpaoliello** [rust-lang/rust#122912]
The `core` crate currently imports the v1 prelude
https://github.com/rust-lang/rust/blob/b3df0d7e5ef5f7dbeeca3fb289c65680ad013f87/library/core/src/lib.rs#L285-L287

This recently caused an issue when updating the `portable-simd` subtree since it was using a trait that was added to the 2021 prelude: https://github.com/rust-lang/rust/pull/122905#discussion_r1536228822

Given that `core` is currently being built as 2021, should it import the 2021 prelude?

cc @workingjubilee @calebzulawski

**Comment by Nilstrieb** [comment]
sounds reasonable

**Comment by dpaoliello** [comment]
Happy to take care of this. 
Do we have a guide or docs on updating the edition that the standard library builds with? Seems like it'd be good to add this as an item to do. 

@rustbot claim
