### ISSUE TITLE
x.py: Test `cargo miri test` for doctests

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#123028]
Currently we do ensure on CI that `cargo miri test` works, but doctests are enabled as I couldn't figure out how to get this to work within bootstrap. However, that has let https://github.com/rust-lang/miri/issues/3404 slip through. So ideally we can figure out these bootstrap issues and test rustdoc inside `cargo miri test` on rustc CI.

**Comment by RalfJung** [comment]
Here's what currently happens:
```
   Doc-tests cargo-miri-test
error[E0514]: found crate `std` compiled by an incompatible version of rustc
  |
  = note: the following crate versions were found:
          crate `std` compiled by rustc 1.79.0-dev: /home/r/src/rust/rustc.3/build/x86_64-unknown-linux-gnu/miri-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-995a88566402f52a.rmeta
          crate `std` compiled by rustc 1.79.0-dev: /home/r/src/rust/rustc.3/build/x86_64-unknown-linux-gnu/miri-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-04ee359a7e2a7fe8.rmeta
  = help: please recompile that crate using this compiler (rustc 1.78.0-nightly (ef324565d 2024-02-27)) (consider running `cargo clean` first)
```

So... probably we're using the wrong rustdoc. I assume it's the bootstrap rustdoc, if that's a thing? I can't even see a rustdoc being built in the build log. We want the rustdoc that is *produced* by stage 0 here, since we are testing the Miri produced by stage 0. How do we get that?

Cc @rust-lang/bootstrap

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/miri/blob/6a72dc6d24958eeab5c7c6caf4103312a5692f45/cargo-miri/src/phases.rs#L584-L586 looks to be the reason we're running a random rustdoc here.

I suspect we'll need to thread through a custom bootstrap env variable, since IIRC there's no RUSTDOC_WRAPPER that miri can use to thread state. Alternatively it *might* work to adjust miri such that it remembers which toolchain is running earlier, but I suspect that'll be harder. As-is though it's almost certainly semi-broken for any Rust user doing something like `cargo +nightly miri test` presumably, where their default toolchain isn't nightly?

**Comment by RalfJung** [comment]
> As-is though it's almost certainly semi-broken for any Rust user doing something like cargo +nightly miri test presumably, where their default toolchain isn't nightly?

It seems to be working, AFAIK rustup ensures that nested calls use the `+`-specified toolchain. Or maybe we are just lucky...

But yes we should
- in the outermost wrapper, determine which rustdoc cargo would invoke using the same logic as cargo
- store that in a miri-private env var
- invoke that in `phase_rustdoc`

I assume however we'll also need further changes in how bootstrap invokes cargo-miri to tell it where the right rustdoc lives? Currently we're not even building rustdoc so something surely needs to change in bootstrap.

**Comment by Mark-Simulacrum** [comment]
Yeah, I'd expect that to be enough to start with at least.

Also potentially relevant: If we're already using builder.cargo somewhere in there (we should be, probably?) then that should already get mostly setup, see here: https://github.com/rust-lang/rust/blob/dda2372cf3700fcc1207ca39c0d3c6c3e90f519c/src/bootstrap/src/core/builder.rs#L1659-L1681, https://github.com/rust-lang/rust/blob/dda2372cf3700fcc1207ca39c0d3c6c3e90f519c/src/bootstrap/src/core/builder.rs#L1703-L1705

**Comment by onur-ozkan** [comment]
> I assume however we'll also need further changes in how bootstrap invokes cargo-miri to tell it where the right rustdoc lives?

We do that already:

https://github.com/rust-lang/rust/blob/dda2372cf3700fcc1207ca39c0d3c6c3e90f519c/src/bootstrap/src/core/builder.rs#L1671-L1679

> Currently we're not even building rustdoc so something surely needs to change in bootstrap.

Unless you are trying stage 0, you should be able to see rustdoc compilation in the build logs.

**Comment by RalfJung** [comment]
>  I also just saw this in the logs:

Never mind, that was for a `--stage 1` build. For stage 0 this doesn't happen. I don't think this can work though...

The staging with Miri is a bit weird; we need a stage 1 std as well for our stage 0 tests. Specifically we need a host sysroot that was built with a compiler that "is the same as" Miri, i.e. that is fully compatible. (The [comment here](https://github.com/rust-lang/rust/blob/0ec5d374fe901488c9bd73cd2162bd62daca8261/src/bootstrap/src/core/build_steps/test.rs#L590) is wrong, it's not the compiler that built Miri.) This was needed to make build scripts and proc macros work in `cargo miri test`.

**Comment by onur-ozkan** [comment]
> @onur-ozkan ah fun, so if we invoke RUSTDOC we'll actually invoke bootstrap's rustdoc wrapper. We'll have to see if having both Miri and that wrapper around will work.^^

Yes, and if you want to use the actual rustdoc without wrapper, you can invoke `RUSTDOC_REAL`. 

I tried using `RUSTDOC_REAL` env instead of plain "rustdoc" and this is the output:

```sh
   Doc-tests cargo-miri-test

running 5 tests
test src/lib.rs - make_true (line 3) ... FAILED
test src/lib.rs - make_true (line 9) - compile ... FAILED
test src/lib.rs - make_true (line 21) - compile fail ... ok
test src/lib.rs - make_true (line 15) - compile fail ... ok
test src/lib.rs - miri_only_fn (line 37) ... FAILED

failures:

---- src/lib.rs - make_true (line 3) stdout ----
error: Option 'sysroot' given more than once

Couldn't compile the test.
---- src/lib.rs - make_true (line 9) stdout ----
error: Option 'sysroot' given more than once

Couldn't compile the test.
---- src/lib.rs - miri_only_fn (line 37) stdout ----
error: Option 'sysroot' given more than once

Couldn't compile the test.

failures:
    src/lib.rs - make_true (line 3)
    src/lib.rs - make_true (line 9)
    src/lib.rs - miri_only_fn (line 37)

test result: FAILED. 2 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s
```

**Comment by RalfJung** [comment]
> I tried using RUSTDOC_REAL env instead of plain "rustdoc" and this is the output:

Yeah currently this does not work due to https://github.com/rust-lang/miri/issues/3404. But you have already come closer than I did. :)

Was that with `--stage 0` or stage 1?

> I had to manually pass RUSTDOC_REAL from the cargo miri test caller; it turns out we are not passing it by default (or it somehow gets removed later?). 

Maybe `self.doc_tests` is [not set here](https://github.com/rust-lang/rust/blob/7f1d08e575a6578c9a591f9a78ab13deb33704f8/src/bootstrap/src/core/builder.rs#L1645)?

**Comment by onur-ozkan** [comment]
> Yeah currently this does not work due to https://github.com/rust-lang/miri/issues/3404.

I guess that needs to be resolved first before we enable doctests on cargo miri test ?

> Was that with --stage 0 or stage 1?

It was stage 1.

> Maybe self.doc_tests is [not set here](https://github.com/rust-lang/rust/blob/7f1d08e575a6578c9a591f9a78ab13deb33704f8/src/bootstrap/src/core/builder.rs#L1645)?

Yeah, it seems like.

**Comment by RalfJung** [comment]
> I guess that needs to be resolved first before we enable doctests on cargo miri test ?

Yes.

> It was stage 1.

`x.py test miri --stage 0` must continue working. I don't want to always build rustc twice when working on Miri in the tree.^^

But if necessary we could enable doc-tests only for higher stages...
