### ISSUE TITLE
Add a getopt flag that consumes all remaining arguments

### ISSUE THREAD

**Issue by Jurily** [rust-lang/rust#12306]
On Unix, some programs run other programs. It is standard convention to pass along the tail of the command line unprocessed.

Examples:

```sh
bash -c command [args]
time command [args]
schedtool -e command [args]
chroot /newroot command [args]
```

**Comment by alexcrichton** [comment]
cc @nick29581, could this be migrated to https://github.com/rust-lang/getopts?
