### ISSUE TITLE
Can't ignore soft destabilization of `rustc-serialize` with `#![allow(soft_unstable)]`

### ISSUE THREAD

**Issue by pitdicker** [rust-lang/rust#123156]
In chrono we have support for `rustc-serialize` behind a feature flag.

As a workaround for #116016 I added the line:
```rust
#![cfg_attr(feature = "rustc-serialize", allow(deprecated), allow(soft_unstable))]
```
It now gives a new error:
```
error[E0658]: use of unstable library feature 'libstd_sys_internals': used by the panic! macro
  --> src/weekday.rs:33:64
   |
33 | #[cfg_attr(feature = "rustc-serialize", derive(RustcEncodable, RustcDecodable))]
   |                                                                ^^^^^^^^^^^^^^
   |
   = help: add `#![feature(libstd_sys_internals)]` to the crate attributes to enable
   = note: this compiler was built on 2024-03-27; consider upgrading it if it is out of date
   = note: this error originates in the derive macro `RustcDecodable` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0658]: use of unstable library feature 'libstd_sys_internals': used by the panic! macro
  --> src/month.rs:32:64
   |
32 | #[cfg_attr(feature = "rustc-serialize", derive(RustcEncodable, RustcDecodable))]
   |                                                                ^^^^^^^^^^^^^^
   |
   = help: add `#![feature(libstd_sys_internals)]` to the crate attributes to enable
   = note: this compiler was built on 2024-03-27; consider upgrading it if it is out of date
   = note: this error originates in the derive macro `RustcDecodable` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0658`.
error: could not compile `chrono` (lib) due to 2 previous errors; 4 warnings emitted
```

cc @jhpratt

**Comment by pitdicker** [comment]
The derived `Decodable` implementation for an enum is using `::std::rt::begin_panic`. Manually implementing `Decodable` and using `unreachable!()` is a workaround.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23123156.20Can't.20ignore.20soft.20destabilization.20of.20.60rustc-seriali.E2.80.A6)).

@rustbot label -I-prioritize +P-critical

**Comment by ehuss** [comment]
cc @jhpratt

**Comment by jhpratt** [comment]
I'm actually not sure this is a T-libs issue. I suspect it's related to `#[allow_internal_unstable]`, but I haven't had a chance to look into it yet.

**Comment by jhpratt** [comment]
I have confirmed this is an issue with the expansion of `RustcDecodable` on `enum`s and aim to have a PR up tonight. As `RustcEncodable` is a built-in macro, it is technically in T-compiler land, I believe.

@rustbot claim

**Comment by jhpratt** [comment]
PR is up, including a regression test: #123182
