### ISSUE TITLE
Why isn't the Copy trait implemented for String?

### ISSUE THREAD

**Issue by Toni-Graphics** [rust-lang/rust#123263]
Why isn't the Copy trait implemented for the type String?

I tried this code:

```rust
#[derive(Copy, Clone)]
enum MyEnum {
  abc(String),
}
```

But i got following error:
```
error[E0204]: the trait `Copy` cannot be implemented for this type
 --> src\test.rs:1:17
  |
1 | #[derive(Clone, Copy)]
  |                 ^^^^
...
w |     Abc(String),
  |           ------ this field does not implement `Copy`
  |
  = note: this error originates in the derive macro `Copy` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by workingjubilee** [comment]
@Toni-Graphics Hello, is your question answered by consulting the [String docs](https://doc.rust-lang.org/std/string/struct.String.html) or [Copy docs](https://doc.rust-lang.org/std/marker/trait.Copy.html)?

**Comment by workingjubilee** [comment]
Hm. It seems it takes quite a while for the String docs to even imply that the value might be heap-allocated and thus not possible to trivially Copy... "btw this allocates" should probably be one of the first things on it (not in detail, that's covered in Representation).

**Comment by JaniM** [comment]
@rustbot claim
First rustc contribution, so not sure of the protocol here.
I'll add a disclaimer to the documentation.

**Comment by TmLev** [comment]
I think it's safe to close now?..

**Comment by Toni-Graphics** [comment]
Yes
