### ISSUE TITLE
set `CARGO` instead of `PATH`

### ISSUE THREAD

**Issue by onur-ozkan** [rust-lang/rust#123227]
Previously, clippy was using `cargo` from `PATH`, but since https://github.com/rust-lang/rust-clippy/pull/11944, it now prioritizes checking `CARGO` first. We can now set `cargo` path into `CARGO` and avoid appending it to the `PATH` chain.

In the bootstrap, we have this piece of code https://github.com/rust-lang/rust/blob/7f1d08e575a6578c9a591f9a78ab13deb33704f8/src/bootstrap/src/core/builder.rs#L1220-L1226 which adds `cargo` into `PATH`. As indicated by the FIXME note, https://github.com/rust-lang/rust-clippy/pull/11944 wasn't merged at the time. Now that we can do so, set `CARGO` instead of `PATH` and remove the FIXME note.

**Comment by RalfJung** [comment]
There's more weird stuff going on here...

https://github.com/rust-lang/rust/blob/4797fba3b71fc44b0904ebd52603a953609a9eb6/src/bootstrap/src/core/builder.rs#L1251-L1252

On Windows, `helpers::dylib_path_var()` is PATH, so this sets the PATH and then immediately overwrites it again with a different value...?!?

**Comment by asquared31415** [comment]
Yep, sorry, absolutely no clue what that code is meant to do.  It's very likely that I copied that from somewhere else during the initial stages of "try everything and see if any of it works", or copied some part of that, and eventually modified to set `PATH`.  I have also unfortunately forgotten all of the context of the bootstrap code here, how it's meant to flow, and what it's meant to set for other programs, so I will not be of any help here :c

I will try to check my messages with jyn, who i was talking to a lot about this at the time, and trying many things at their suggestion, to see if I can find any useful history.
