### ISSUE TITLE
regression: type is now private?

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#123288]
```
[INFO] [stdout] error: type `bright_lang_lexer::SingleLineCommentToken` is private
[INFO] [stdout]   --> /opt/rustwide/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/logos-0.11.4/src/lexer.rs:13:5
[INFO] [stdout]    |
[INFO] [stdout] 13 |     source: &'source Token::Source,
[INFO] [stdout]    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ private type
```

* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/gh/theidiotmachine.bright-lang/log.txt

**Comment by Nilstrieb** [comment]
searched nightlies: from nightly-2024-02-01 to nightly-2024-03-20
regressed nightly: nightly-2024-02-10
searched commit range: https://github.com/rust-lang/rust/compare/98aa3624be70462d6a25ed5544333e3df62f4c66...d44e3b95cb9d410d89cb8ab3233906a33f43756a
regressed commit: https://github.com/rust-lang/rust/commit/e28fae52d99d7c14bf0890d1f2b13c2c34fa8932

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.8</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc github --start 2024-02-01 --end 2024-03-20 
```
</details>

probably #113671 @oli-obk

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23123288.20regression.3A.20type.20is.20now.20private.3F)).

@rustbot label -I-prioritize +P-high

**Comment by oli-obk** [comment]
MCVE

```rust
mod baz {
    struct Foo;

    pub trait Trait {
        type Assoc;
    }

    impl Trait for Foo {
        type Assoc = ();
    }

    pub struct Bar<'a, T: Trait> {
        source: &'a T::Assoc,
        //~^ ERROR: private type
    }

    pub struct Baz<'a> {
        mode: Bar<'a, Foo>,
    }
}

pub struct Struct<'a> {
    lexer: baz::Baz<'a>,
}
```
