### ISSUE TITLE
regression: trait bound is not satisfied

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#123279]
```
[INFO] [stdout] error[E0277]: the trait bound `(dyn LoopableJob + 'static): Job` is not satisfied
[INFO] [stdout]    --> src/service.rs:190:18
[INFO] [stdout]     |
[INFO] [stdout] 190 |         self.job.run_once().await
[INFO] [stdout]     |                  ^^^^^^^^ the trait `Job` is not implemented for `(dyn LoopableJob + 'static)`
[INFO] [stdout]     |
[INFO] [stdout] help: consider introducing a `where` clause, but there might be an alternative better way to express this requirement
[INFO] [stdout]     |
[INFO] [stdout] 188 | impl Job for LoopingJobService where (dyn LoopableJob + 'static): Job {
[INFO] [stdout]     |                                ++++++++++++++++++++++++++++++++++++++
```

* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/reg/app-frame-0.3.1/log.txt

**Comment by compiler-errors** [comment]
Regression in https://github.com/rust-lang-ci/rust/commit/e890bd9a6b843d993df36be5256df31bbff6aab4
The PR introducing the regression in this rollup is #120323: On E0277 be clearer about implicit `Sized` bounds on type p…

searched nightlies: from nightly-2024-01-01 to nightly-2024-03-18
regressed nightly: nightly-2024-02-06
searched commit range: https://github.com/rust-lang/rust/compare/268dbbbc4b3fd71c5f360a4d0728295252430b5b...f067fd6084d750f3797f54b71771c5dbc149726f
regressed commit: https://github.com/rust-lang/rust/commit/4d87c4ad626988ee2145c563d888dacc9ad36930

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.8</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start=2024-01-01 --end=2024-03-18 
```
</details>

This PR definitely should **not** have changed behavior :/
cc @estebank

**Comment by compiler-errors** [comment]
I'll look into what's going on with it anyways -- it at least needs a MCVE

@rustbot claim

**Comment by compiler-errors** [comment]
Implicitly reordering the `Sized` predicates as a side-effect of #120323 is the problem here.

```rust
pub trait Job: AsJob {
    fn run_once(&self);
}

impl<F: Fn()> Job for F {
    fn run_once(&self) {
        todo!()
    }
}

pub trait AsJob {
}

impl<T: Job + Sized> AsJob for T { // <----- changing this to `Sized + Job` or just `Job` will FIX it.
}

pub struct LoopingJobService {
    job: Box<dyn Job>,
}

impl Job for LoopingJobService {
    fn run_once(&self) {
        self.job.run_once()
    }
}
``` 

I assume this is because of an overflow on the `AsJob` impl that isn't cut off short by the `Sized` predicate being impossible to satisfy?

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23123279.20regression.3A.20trait.20bound.20is.20not.20satisfied)).

@rustbot label -I-prioritize +P-high

**Comment by cuviper** [comment]
#123302 was backported in #123466.
