### ISSUE TITLE
Can we stop rustc --test warning of an unused main()?

### ISSUE THREAD

**Issue by chris-morgan** [rust-lang/rust#12327]
$ echo 'fn main(){}' | rustc --test -
    <anon>:1:1: 1:12 warning: code is never used: `main`, #[warn(dead_code)] on by default
    <anon>:1 fn main(){}
             ^~~~~~~~~~~

I have put `#[cfg(not(test))]` on `main` a couple of times (though perhaps `#[allow(dead_code)]` would be better) and I have just observed another person doing it. Would it be reasonable to make the dead code lint permit `main` to be unused?

**Comment by felixc** [comment]
This issue appears to also affect the [Emacs Flycheck mode for Rust](https://github.com/flycheck/flycheck-rust). Emacs users will get Flycheck warnings saying main() is dead code. Arguably it's a bug in their end (is it?), but it's another data point to suggest it's unexpected behaviour.

**Comment by tbelaire** [comment]
It'd be also a good idea to not just use #[cfg(not(test))] on main, since that'll cause spurious import not used errors on functions that are just imported for use in main.

**Comment by daboross** [comment]
@tbelaire Using `#[cfg_attr(test, allow(dead_code))]` instead of `#[cfg(not(test))]` would fix this error without causing import not used errors. It doesn't look the best, but it does do that.

**Comment by steveklabnik** [comment]
:confetti_ball:
