### ISSUE TITLE
regression: Context changed sizes

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#123283]
```
[INFO] [stdout] error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
[INFO] [stdout]   --> fos/src/fc/future.rs:46:44
[INFO] [stdout]    |
[INFO] [stdout] 46 |                 let mut fake_cx = unsafe { std::mem::transmute(&fake_cx) };
[INFO] [stdout]    |                                            ^^^^^^^^^^^^^^^^^^^
[INFO] [stdout]    |
[INFO] [stdout]    = note: source type: `&u64` (64 bits)
[INFO] [stdout]    = note: target type: `Context<'_>` (128 bits)
```

* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/gh/Fritz179.fos/log.txt

This looks like it was probably always unstable and/or UB, but filing to make sure we dive a bit deeper.

**Comment by fmease** [comment]
Lol, someone is trying to transmute a reference to `std::task::Context`. This looks super dubious and only used to work on 64-bit machines anyway. Type size is not considered to be part of the API. This is a WONTFIX I'm pretty sure. PR #118960 “regressed” this by adding a `LocalWaker` to the `Context`.

**Comment by Mark-Simulacrum** [comment]
Sounds right to me.

**Comment by apiraino** [comment]
Does anything in our crater run config need to be tweaked to avoid this crate crashing when running the next crater run?

**Comment by Mark-Simulacrum** [comment]
No, it'll just be a build-fail to build-fail result. We ignore those.
