### ISSUE TITLE
regression: pointer functions not yet stable as const fn

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#123284]
```
[INFO] [stdout] error: `core::ptr::const_ptr::<impl *const T>::copy_to_nonoverlapping` is not yet stable as a const fn
[INFO] [stdout]    --> /opt/rustwide/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/bnum-0.8.0/src/bint/endian.rs:146:25
[INFO] [stdout]     |
[INFO] [stdout] 146 | /                         slice_ptr
[INFO] [stdout] 147 | |                             .add(i << digit::$Digit::BYTE_SHIFT)
[INFO] [stdout] 148 | |                             .copy_to_nonoverlapping(ptr, digit::$Digit::BYTES as usize);
[INFO] [stdout]     | |_______________________________________________________________________________________^
[INFO] [stdout] ...
[INFO] [stdout] 240 |   crate::macro_impl!(endian);
[INFO] [stdout]     |   -------------------------- in this macro invocation
[INFO] [stdout]     |
[INFO] [stdout]     = note: this error originates in the macro `endian` which comes from the expansion of the macro `crate::macro_impl` (in Nightly builds, run with -Z macro-backtrace for more info)
[INFO] [stdout] 
```

* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/gh/DavidCasalod.nitka/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/gh/BoydBLever.Sei-Shield-Contract/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/gh/Hypnos-Labs.fuzion_market/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/gh/Learning-Tech-Workspace.Cosmwasm-Multi-Contract/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/gh/Levana-Protocol.simple-oracle/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/gh/Megadev-OU.cosmwasm-contracts/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/gh/Nebula-Marketplace.Exchange/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/gh/Nowayyyy1.coin_f/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/gh/Reecepbcups.interchaintest-rust-example/log.txt
* [... lots of other bnum reverse-deps ...]

non-bnum cases:

* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/gh/uktamjon-komilov.axum_template/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/reg/cbfr-0.1.6/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/reg/nstd-sys-0.11.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/reg/ntcip-0.12.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/reg/redis_config-0.1.0/log.txt

**Comment by Mark-Simulacrum** [comment]
Docs indicate these aren't const-stable (e.g., https://doc.rust-lang.org/nightly/std/primitive.pointer.html#method.copy_to_nonoverlapping-1 has `const: unstable`). But this code seems to have worked before, so either (a) we aren't checking const-stability prior to 1.78 on inherent pointer methods or (b) something else fishy is going on.

**Comment by zachs18** [comment]
IIUC these were intentionally destabilized by #117905

**Comment by Mark-Simulacrum** [comment]
I see. The vast majority of the regressions seem to still be bnum (likely mostly due to Crater not bumping the lockfiles for committed lockfiles). It seems like this is pretty similar in spirit to https://github.com/rust-lang/rust/issues/123285 where we're mostly just detecting a bunch of new UB now (just via de-stabilization).

I think that means we're likely to move forward here but will want to call this out in release notes.

**Comment by RalfJung** [comment]
Closing as this was a deliberate de-stabilization. https://github.com/rust-lang/rust/issues/80697 tracks this now-again-unstable feature.
