### ISSUE TITLE
-Zscript doesn't download dependecies

### ISSUE THREAD

**Issue by sigmaSd** [rust-lang/rust#123326]
I tried the example here https://rust-lang.github.io/rfcs/3424-cargo-script.html

```rs
#!/usr/bin/env cargo

//! ```cargo
//! [dependencies]
//! clap = { version = "4.2", features = ["derive"] }
//! ```

use clap::Parser;

#[derive(Parser, Debug)]
#[clap(version)]
struct Args {
    #[clap(short, long, help = "Path to config")]
    config: Option<std::path::PathBuf>,
}

fn main() {
    let args = Args::parse();
    println!("{:?}", args);
}
```

`cargo -Zscript a.rs`  errors with `error[E0432]: unresolved import `clap``

I'm sure this used to work, but I don't know when this stopped.

rustc 1.79.0-nightly (2f090c30d 2024-03-23)

**Comment by workingjubilee** [comment]
probably should transfer to cargo?

**Comment by sigmaSd** [comment]
https://github.com/rust-lang/cargo/issues/13684
