### ISSUE TITLE
Can't use struct with reference to struct with lifetime as GAT

### ISSUE THREAD

**Issue by Supreeeme** [rust-lang/rust#123309]
```rust
trait A {
    type Gat<'a, 'b>;
}

struct R<'a>(&'a u32);
struct T<'a, 'b>(&'a R<'b>);

struct S;

impl A for S {
    type Gat<'a, 'b> = T<'a, 'b>;
}
```

The error:
```
error[E0478]: lifetime bound not satisfied
  --> src/main.rs:11:24
   |
11 |     type Gat<'a, 'b> = T<'a, 'b>;
   |                        ^^^^^^^^^
   |
note: lifetime parameter instantiated with the lifetime `'b` as defined here
  --> src/main.rs:11:18
   |
11 |     type Gat<'a, 'b> = T<'a, 'b>;
   |                  ^^
note: but lifetime parameter must outlive the lifetime `'a` as defined here
  --> src/main.rs:11:14
   |
11 |     type Gat<'a, 'b> = T<'a, 'b>;
   |              ^^
```
Adding a `where 'a: 'b` on `Gat` or `T` does not do anything.

There seems to be no way to get the compiler to accept this lifetime bound, even though it should clearly be possible, since this is constructible. 

### Meta

`rustc --version --verbose`:
```
rustc 1.77.1 (7cf61ebde 2024-03-27)
binary: rustc
commit-hash: 7cf61ebde7b22796c69757901dd346d0fe70bd97
commit-date: 2024-03-27
host: x86_64-unknown-linux-gnu
release: 1.77.1
LLVM version: 17.0.6
```

**Comment by fmease** [comment]
If you have control over the definition of trait `A`, you can just update the assoc type `Gat` in *both* the trait def and the trait impl to `type Gat<'a, 'b: 'a>...` to make it pass:

```rs
trait A {
    type Gat<'a, 'b: 'a>;
}

struct R<'a>(&'a u32);
struct T<'a, 'b>(&'a R<'b>);

struct S;

impl A for S {
    type Gat<'a, 'b: 'a> = T<'a, 'b>;
}
```

**Comment by fmease** [comment]
And if you can't change the definition of trait `A` (e.g., if it's part of a different crate or if you don't want to), well, then you simply can't assign `T<'a, 'b>` to it since they are different lifetime requirements.

**Comment by Supreeeme** [comment]
I see now, I had the requirements reversed, was trying to `'a: 'b` instead of `'b: 'a`. Sorry!

**Comment by fmease** [comment]
No problem, glad I could be of help!

In the future, please avoid using this issue tracker for general questions.
Prefer any one of these: [URLO](https://users.rust-lang.org/), [IRLO](https://internals.rust-lang.org/), [Zulip](https://rust-lang.zulipchat.com/), [Discord](https://discord.gg/rust-lang), [Reddit (unofficial)](https://www.reddit.com/r/rust).
