### ISSUE TITLE
[rustdoc] Documentation not being generated for `doc(inline)`ed re-export of a `doc(hidden)` item in another crate

### ISSUE THREAD

**Issue by AhmadAlHallak** [rust-lang/rust#123435]
Suppose we have crates a, and b (crate b being a nested crate within crate a), and we have the following in `a/b/src/lib.rs`:

```rust
#[doc(hidden)]
pub struct HiddenInCrateB;

```

and then in `a/src/lib.rs`:

```rust
/// Docs that I think should be generated for an inlined re-export of `b::DocHiddenInB` but are not
#[doc(inline)]
pub use b::HiddenInCrateB;

mod c {
    #[doc(hidden)]
    pub struct HiddenInModuleC;
}
/// Docs that are generated for an inlined re-export of `c::HiddenInModuleC`
#[doc(inline)]
pub use c::HiddenInModuleC;
```

and then run `cargo doc` and open the generated documentation for crate a we would see an entry `HiddenInModuleC` but not for `HiddenInCrateB`

I expected documentation to be generated for both `HiddenInModuleC` and `HiddenInCrateB`, or alternatively no docs being generated for either.

### Meta
`rustc --version --verbose`:
```
rustc 1.77.1 (7cf61ebde 2024-03-27)
binary: rustc
commit-hash: 7cf61ebde7b22796c69757901dd346d0fe70bd97
commit-date: 2024-03-27
host: x86_64-pc-windows-msvc
release: 1.77.1
LLVM version: 17.0.6
```

</details>

```[tasklist]
### Tasks
```

**Comment by AhmadAlHallak** [comment]
@GuillaumeGomez is this intended behavior?

**Comment by GuillaumeGomez** [comment]
Sounds like a bug. Taking a look.
