### ISSUE TITLE
requirement solver overflow involving `proptest::sugar::NamedArguments`

### ISSUE THREAD

**Issue by SohumB** [rust-lang/rust#123493]
I have a full repro in https://github.com/SohumB/proptest_sugar_rustc_overflow, but the short version is, it seems like some cases of code that _look_ like an omitted type should be inferrable:

```rust
fn _foo<Error: Debug>() {
    todo!()
}

pub fn foo() {
    _foo();
}
```

while certain dependencies, leading to `proptest`, are in the compile pathway (I could only get it to reproduce via a weird dependency chain via a workspace and a couple of public crates), can lead `rustc` to an overflow:

```
error[E0275]: overflow evaluating the requirement `proptest::sugar::NamedArguments<(_, _, _), &(..., ..., ...)>: Debug`
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`pipeline`)
  = note: required for `proptest::sugar::NamedArguments<((_, _, _), _, _), &((_, _, _), _, _)>` to implement `Debug`
  = note: 126 redundant requirements hidden
  = note: required for `NamedArguments<((((((((((..., ..., ...), ..., ...), ..., ...), ..., ...), ..., ...), ..., ...), ..., ...), ..., ...), ..., ...), ..., ...), ...>` to implement `Debug`
  = note: the full name for the type has been written to '/home/sohum/versioned/xdi/ice_repro/target/debug/deps/pipeline-00f02624ad986c54.long-type-16626873074358915367.txt'
  = note: consider using `--verbose` to print the full type name to the console
```

If the dependency chain is altered in any way that I could divine, the expected error is output:

```
error[E0283]: type annotations needed
 --> foo/src/lib.rs:9:5
  |
9 |     _foo();
  |     ^^^^ cannot infer type of the type parameter `Error` declared on the function `_foo`
  |
  = note: cannot satisfy `_: Debug`
note: required by a bound in `_foo`
 --> foo/src/lib.rs:4:16
  |
4 | fn _foo<Error: Debug>() {
  |                ^^^^^ required by this bound in `_foo`
help: consider specifying the generic argument
  |
9 |     _foo::<Error>();
  |         +++++++++
```

### Meta

I've reproduced this bug both in `nightly-2024-04-05` and in `nightly-2024-03-12`.

`rustc --version --verbose`:
```
rustc 1.79.0-nightly (385fa9d84 2024-04-04)
binary: rustc
commit-hash: 385fa9d845dd326c6bbfd58c22244215e431948a
commit-date: 2024-04-04
host: x86_64-unknown-linux-gnu
release: 1.79.0-nightly
LLVM version: 18.1.2
```

**Comment by dtolnay** [comment]
Bisects to nightly-2023-10-07. In nightly-2023-10-06, we get "the expected error" shown above.

https://github.com/rust-lang/rust/compare/cae0791da47bb01f16885eb233dcd66b0093a6e1...960754090acc9cdd2a5a57586f244c0fc712d26c

**Comment by dtolnay** [comment]
Looks like https://github.com/rust-lang/rust/pull/114811, because 94bc9c737ea97d56f9b4076553ac37c05c1e3931 reproduces the issue, but the previous commit on master (31be8cc41148983e742fea8f559aacca0f6647db) does not.

**Comment by compiler-errors** [comment]
Minimal:

```rust
trait Hello {}

struct Foo<'a, T: ?Sized>(&'a T);

impl<'a, T: ?Sized> Hello for Foo<'a, &'a T> where Foo<'a, T>: Hello {}

fn hello<T: ?Sized + Hello>() {}

fn main() {
    hello::<Foo<_>>();
}
```

**Comment by compiler-errors** [comment]
I'll put up a fix in a sec

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23123493.20requirement.20solver.20overflow.20involving.20.60proptest.3A.3Asu.E2.80.A6)).

@rustbot label -I-prioritize +P-medium
