### ISSUE TITLE
“may not” was incorrectly changed to “must not” in `FromResidual` documentation

### ISSUE THREAD

**Issue by taylordotfish** [rust-lang/rust#123566]
### Location

[Documentation for](https://doc.rust-lang.org/nightly/std/ops/trait.FromResidual.html#tymethod.from_residual) `FromResidual::from_residual`

### Summary

As part of #87445, the following part of the [documentation for](https://doc.rust-lang.org/nightly/std/ops/trait.FromResidual.html#tymethod.from_residual) `FromResidual::from_residual`:

```
/// This should be implemented consistently with the `branch` method such
/// that applying the `?` operator will get back an equivalent residual:
/// `FromResidual::from_residual(r).branch() --> ControlFlow::Break(r)`.
/// (It may not be an *identical* residual when interconversion is involved.)
```

was changed to (change in bold):

<pre><code>/// This should be implemented consistently with the `branch` method such
/// that applying the `?` operator will get back an equivalent residual:
/// `FromResidual::from_residual(r).branch() --> ControlFlow::Break(r)`.
/// (It <strong>must</strong> not be an *identical* residual when interconversion is involved.)</code></pre>

The parenthetical now appears to state that the residual is not permitted to be identical when interconversion is involved (i.e., it must be different in some way). However, I believe the intention of the original wording was to convey that the residual is not *required* to be identical when interconversion is involved, which makes more sense contextually. I believe the emphasis on the word “identical” also supports this interpretation.

I propose that “must not” be changed to “need not”, “is not required to”, “does not have to”, or similar. Even “might not”, the other alternative in #87445, would be closer.

**Comment by taylordotfish** [comment]
It looks like #123595 was created in response to this issue, but doesn't mention or link to it, which is odd considering its description contains verbatim parts of this issue's description without citation.

**Comment by GrigorenkoPV** [comment]
I guess this issue can be closed now that the (impolite) PR got merged?
