### ISSUE TITLE
Miri sometimes reports memory leak in thread-local storage on *-pc-windows-gnu

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#123583]
I've only seen this [once](https://github.com/rust-lang/rust/actions/runs/8583356399/job/23522466884), even though the test should be covered by miri-test-libstd every day:
```
  error: memory leaked: alloc26870878 (Rust heap, size: 8, align: 4), allocated here:
  Error:     --> /checkout/library/alloc/src/alloc.rs:100:9
       |
  100  |         __rust_alloc(layout.size(), layout.align())
       |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       |
       = note: BACKTRACE:
       = note: inside `realstd::alloc::alloc` at /checkout/library/alloc/src/alloc.rs:100:9: 100:52
       = note: inside `realstd::alloc::Global::alloc_impl` at /checkout/library/alloc/src/alloc.rs:183:73: 183:86
       = note: inside `<realstd::alloc::Global as core::alloc::Allocator>::allocate` at /checkout/library/alloc/src/alloc.rs:243:9: 243:39
       = note: inside `alloc_crate::alloc::exchange_malloc` at /checkout/library/alloc/src/alloc.rs:332:11: 332:34
       = note: inside `realstd::boxed::Box::<realstd::sys::thread_local::os_local::Value<u8>>::new` at /checkout/library/alloc/src/boxed.rs:218:9: 218:20
       = note: inside `realstd::thread::local_impl::Key::<u8>::try_initialize::<{closure@/checkout/library/std/src/sys/thread_local/os_local.rs:28:27: 28:34}>` at /checkout/library/std/src/sys/thread_local/os_local.rs:145:37: 145:94
       = note: inside `realstd::thread::local_impl::Key::<u8>::get::<{closure@/checkout/library/std/src/sys/thread_local/os_local.rs:28:27: 28:34}>` at /checkout/library/std/src/sys/thread_local/os_local.rs:127:18: 127:43
  note: inside `sync::reentrant_lock::current_thread_unique_ptr::X::__getit`
      --> /checkout/library/std/src/sys/thread_local/os_local.rs:28:17
       |
  11   |   pub macro thread_local_inner {
       |   ----------------------------
       |   |
       |   in this expansion of `$crate::thread::local_impl::thread_local_inner!` (#2)
       |   in this expansion of `$crate::thread::local_impl::thread_local_inner!` (#3)
  ...
  28   | /                 __KEY.get(move || {
  29   | |                     if let $crate::option::Option::Some(init) = _init {
  30   | |                         if let $crate::option::Option::Some(value) = init.take() {
  31   | |                             return value;
  ...    |
  36   | |                     __init()
  37   | |                 })
       | |__________________^
  ...
  82   |               $crate::thread::local_impl::thread_local_inner!(@key $t, $($init)*);
       |               ------------------------------------------------------------------- in this macro invocation (#3)
       |
      ::: library/std/src/sync/reentrant_lock.rs:318:5
       |
  318  |       thread_local! { static X: u8 = const { 0 } }
       |       -------------------------------------------- in this macro invocation (#1)
       |
      ::: library/std/src/thread/local.rs:183:1
       |
  183  | / macro_rules! thread_local {
  184  | |     // empty (base case for the recursion)
  185  | |     () => {};
  ...    |
  193  | |         $crate::thread::local_impl::thread_local_inner!($(#[$attr])* $vis $name, $t, const $init);
       | |         ----------------------------------------------------------------------------------------- in this macro invocation (#2)
  ...    |
  205  | |     );
  206  | | }
       | |_- in this expansion of `thread_local!` (#1)
       = note: inside `realstd::thread::LocalKey::<u8>::try_with::<{closure@library/std/src/sync/reentrant_lock.rs:319:12: 319:15}, usize>` at /checkout/library/std/src/thread/local.rs:283:32: 283:50
       = note: inside `realstd::thread::LocalKey::<u8>::with::<{closure@library/std/src/sync/reentrant_lock.rs:319:12: 319:15}, usize>` at /checkout/library/std/src/thread/local.rs:260:9: 260:25
  note: inside `sync::reentrant_lock::current_thread_unique_ptr`
      --> library/std/src/sync/reentrant_lock.rs:319:5
       |
  319  |     X.with(|x| <*const _>::addr(x))
       |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  note: inside `sync::reentrant_lock::ReentrantLock::<()>::lock`
      --> library/std/src/sync/reentrant_lock.rs:184:27
       |
  184  |         let this_thread = current_thread_unique_ptr();
       |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  note: inside `sync::reentrant_lock::tests::smoke`
      --> library/std/src/sync/reentrant_lock/tests.rs:10:17
       |
  10   |         let a = l.lock();
       |                 ^^^^^^^^
  note: inside closure
      --> library/std/src/sync/reentrant_lock/tests.rs:7:11
       |
  6    | #[test]
       | ------- in this procedural macro expansion
  7    | fn smoke() {
       |           ^
       |
      ::: /checkout/library/core/src/macros/mod.rs:1636:5
       |
  1636 |     pub macro test($item:item) {
       |     -------------- in this expansion of `#[test]`
```

Cc @joboet @m-ou-se @Amanieu

**Comment by RalfJung** [comment]
Or maybe this is caused by Miri not properly running the on-thread-exit hook on Windows? The support for that is a bit fragile as Miri does not support these magic linker sections we rely on. Instead Miri hard-codes the path to [this static](https://github.com/rust-lang/rust/blob/ad4c4f4654bf78bb51638e58a9c418afcdd6ee15/library/std/src/sys/pal/windows/thread_local_key.rs#L278-L280) and calls it. But with the test crate we may have that static twice (once in std and once in the test crate) and only one of them gets called...

However I would expect that [this logic](https://github.com/rust-lang/rust/blob/7d008267dddcda74ebdb83d3da9b3f16c7f56973/library/std/src/thread/mod.rs#L194-L210) means that the thread_local impl from the real std is used, so the one from the test crate should not matter.

Maybe we should stop using this hack and implement support for this magic linker section instead. I just don't know if there's a good way to ask the compiler for "all `static` in a particular link_section across all crates".

**Comment by RalfJung** [comment]
I tried to figure out how TLS is currently implemented on Windows, but I got lost in the dark forest that is `std::sys`.^^ I can't figure out where [this call](https://github.com/rust-lang/rust/blob/e43aef0ef9cc9d2d12c138b36fd817f7c41d0152/library/std/src/sys_common/thread_local_key.rs#L147) (`imp::create`) would go on Windows; nothing in the Windows folder declares a `create` function.

**Comment by ChrisDenton** [comment]
The Windows specific bits happen here: <https://github.com/rust-lang/rust/blob/e43aef0ef9cc9d2d12c138b36fd817f7c41d0152/library/std/src/sys/pal/windows/thread_local_key.rs>

Note though that the `StaticKey` (and related) bits aren't actually used if `#[cfg(target_thread_local)]`.

**Comment by RalfJung** [comment]
The bug was on i686-pc-windows-gnu. Not sure if that's currently `target_thread_local` or not... I think it is? Only the 32bit MSVC target is not? But I keep forgetting which one exactly it is so I may be wrong.

**Comment by RalfJung** [comment]
However I think even with `target_thread_local`, dtors are handled the same way -- via `thread::local_impl::Key::<T>::register_dtor`.

**Comment by ChrisDenton** [comment]
32-bit msvc is currently not `target_thread_local`. However, that may change soon.

`register_keyless_dtor` is used when `target_thread_local` is enabled, otherwise `register_dtor` is used. Both ultimately use the special `.CRT$XLB` linker magic.

**Comment by RalfJung** [comment]
Ah, `register_dtor` is actually `register_keyless_dtor`.
```rust
pub use super::thread_local_key::register_keyless_dtor as register_dtor;
```
This is such a maze...^^

**Comment by ChrisDenton** [comment]
You're not the first to notice that: https://github.com/rust-lang/rust/issues/110897

**Comment by RalfJung** [comment]
Okay, thanks for clarifying.

Is there an issue tracking why the windows-gnu targets can't use target_thread_local?

**Comment by mati865** [comment]
Tests inside `ui/` crash with some code that I can'it recall 😉
That could be discrepancy between our default LLVM backend which uses Windows native TLS and GNU tools which use emuTLS but I didn't dedicated enough time to it and I'm not planning currently.

**Comment by joboet** [comment]
I tried enabling native TLS in #102243, the result being access violations when running rustc. Things may have changed since then, though.

**Comment by mati865** [comment]
I've tried it multiple times over the years and the result was always the same, this time it could work if emutls is enabled as well: https://github.com/rust-lang/rust/pull/117873 but I don't have high hopes here and I think it'd still require some fixes.

**Comment by RalfJung** [comment]
So, it was not some issue with the global destructor after all. And it seems to always hit only the reentrant lock, even though that is not the only thread-local we have.

Maybe there's an actual race condition leading to occasional memory leaks here?

**Comment by RalfJung** [comment]
Minimal reproducer so far:
```rust
use std::thread;

pub(crate) fn current_thread_unique_ptr() {
    // Use a non-drop type to make sure it's still available during thread destruction.
    thread_local! { static X: u8 = const { 0 } }
    X.with(|_x| {})
}

fn main() {
    let j2 = thread::spawn(current_thread_unique_ptr);
    current_thread_unique_ptr();
    j2.join().unwrap();
}
```

The leak only occurs on the GNU targets.

**Comment by ChrisDenton** [comment]
Presumably this is due to the TLS dtor when not `has_thread_local`.

All the msvc targets currently use the `#[cfg(target_thread_local)]` code.

**Comment by RalfJung** [comment]
Meanwhile, https://github.com/rust-lang/rust/pull/124270 should work around the CI issue.

**Comment by RalfJung** [comment]
FWIW the issue reproduces with and without `const { ... }`.

**Comment by RalfJung** [comment]
Hm, that's very strange... supposedly there's `Box::new` being called here to create a Box with content `std::sys::thread_local::os_local::Value<u8>`:

https://github.com/rust-lang/rust/blob/45ca53f9d867087fdf8fa7371b9f4f8b38a01a41/library/std/src/sys/thread_local/os_local.rs#L62-L71

... there's no call to `Box` there that I can see?!?

**Comment by RalfJung** [comment]
Oh never mind, I copied the span from the closure not the stacktrace.^^

It's this Box:

https://github.com/rust-lang/rust/blob/45ca53f9d867087fdf8fa7371b9f4f8b38a01a41/library/std/src/sys/thread_local/os_local.rs#L145

**Comment by RalfJung** [comment]
One key ingredient to the leak seems to be not loading the latest value here:

https://github.com/rust-lang/rust/blob/5934aaaa973349c0ff6050e88d6a66a0fe196dda/library/std/src/sys/pal/windows/thread_local_key.rs#L314

Cc @joboet

**Comment by RalfJung** [comment]
Ah, I think I got it. :)
https://github.com/rust-lang/rust/pull/124281

**Comment by matthiaskrgr** [comment]
🏅
