### ISSUE TITLE
Rust 2015 and 2018 allow emoji in identifiers in "Unknown prefix" position

### ISSUE THREAD

**Issue by mattheww** [rust-lang/rust#123696]
In the 2015 and 2018 editions, the following compiles (with warnings):

````
macro_rules! lexes {($($_:tt)*) => {}}

lexes!(🐛#);
lexes!(🐛"foo");
lexes!(🐛'q');
lexes!(🐛'q);
````

[playground]

The 🐛 is taken as an identifier, although emoji aren't generally permitted in identifiers in any edition.

I tested with `rustc` 1.77.1.

I think the underlying problem is that `ident_or_unknown_prefix()` and `fake_ident_or_unknown_prefix()` in `rustc_lexer` distinguish "identifiers" containing emoji (as `InvalidIdent` rather than `Ident`), but don't have a way to make that distinction for `UnknownPrefix`.

[playground]: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a78fc4735ba0d3e79ff5454edbe5f7e0

**Comment by fmease** [comment]
Regression from 1.57 to 1.58 (stable to stable). Very likely in #88781, cc @estebank.
Regression from error to pass. Previous error: `unknown start of token: \u{1f41b}`.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23123696.20Rust.202015.20and.202018.20allow.20emoji.20in.20identifiers.20in.20.22U.E2.80.A6)).

@rustbot label -I-prioritize +P-low

**Comment by estebank** [comment]
@mattheww thank you for the detailed report. #123752 will fix this.
