### ISSUE TITLE
Pluggable lints (and attributes)

### ISSUE THREAD

**Issue by kballard** [rust-lang/rust#12372]
Just as we now support pluggable macros, I would love to see pluggable lints (with associated pluggable attributes). I'm thinking these lints/attributes could be scoped by the crate name, so something like

```rust
#[attribute_registrar]
pub fn attribute_registrar(registrar: |Name, Type|) {
    // register attribute names with whatever info is used
    // to determine if and how arguments are specified
    register(token::intern("myattr"), ...);
}

#[lint_registrar]
pub fn lint_registrar(register: |Name, LintExtension|) {
    register(token::intern("mylint"), ...);
}
```

when loaded as

```rust
#[feature(phase)];
#[phase(syntax)]
extern mod foo;
```

would add the attribute `#[foo::myattr]` and the lint `foo::mylint`.

The motivating reason here for me is that I believe for my rust-lua project to be safe I need to have a lint to ensure that the functions exposed to Lua do not make any Lua calls when there is a value with a destructor on the stack. To that end I want to annotate my Lua methods with `#[lua::longjmp]` and have a lint that disallows calling any `#[lua::longjmp]` method with destructors on the stack.

**Comment by steveklabnik** [comment]
Yes: https://github.com/rust-lang/rust/issues/14067
