### ISSUE TITLE
Add a check against multiple `only-` directives in the same line

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#123730]
In https://github.com/rust-lang/rust/pull/123185/commits/556b47ee1ab265442094658738cd5e1c31c97c69 I wrote
```text
//@ [OPT3LINX64] only-linux only-x86_64
```
which based on https://github.com/rust-lang/rust/pull/123185#issuecomment-2046698869 appears like it didn't run on just x64.

Assuming I'm right that this is what happened (if not, please close this) then it would be nice for the same helpful checker that tells me I did it wrong when I write `linux-only` to also tell me that I can't put multiple `only` checks on the same line.

**Comment by jieyouxu** [comment]
We are able to detect *wrong* directives on their own, because we just have a non-exhaustive list of known directives and match against that. I suppose we could just try a match against the same known directive list for `only-*` comments to point out that you cannot chain directives in the same line?

**Comment by jieyouxu** [comment]
It is reasonable, the problem is that we have *a lot* of pre-existing directives that don't take this form (and we'd have to do another massive migration pass). I'm also not sure what `ui_test` does about this.

**Comment by jieyouxu** [comment]
This would've been a less surprising directive grammar from the beginning, but of course hindsight is 20/20. I'm not sure it's worth the churn to change the grammar now.

What we can do now without churn, however, is to [explicitly document that directives are intended to be one-per-line in the dev guide](https://github.com/rust-lang/rustc-dev-guide/pull/1962) (https://github.com/rust-lang/rustc-dev-guide/pull/1962).

**Comment by Urgau** [comment]
Without changing the syntax, we could probably still error out if the sentence right after the directive is a well known directive. That way we should be able to catch `@scottmcm` mistake without massive change.

**Comment by workingjubilee** [comment]
This was done.
