### ISSUE TITLE
println not working on slice type 

### ISSUE THREAD

**Issue by Suryansh-Dey** [rust-lang/rust#123787]
the rust code:
```rust
use std::io;
fn main() {
    let mut input: String = String::new();let word_count: usize;
    io::stdin().read_line(&mut input).expect("bapree!");
    let input: &str = &input[0..(input.chars().count()-1)];
    word_count = input.chars().count();
    println!("Your input is {input} which consists {word_count} words");
}
```
input was `water`
output: ` which consists 6 words`
could you explain where "your input is {input}", went?

**Comment by SkiFire13** [comment]
You should mention your compiler version and platform. Without more informations I can imagine you are on windows and your input string ends with `\r\n`. You removed only the `\n`, leaving the `\r`. When printed in the `{input}` this moves the cursor to the start of the line and then the rest of the printed text overrides the "your input was" part.

**Comment by clubby789** [comment]
You can also use `.trim()` to remove leading and trailing whitespace from a string.

Closing as this isn't a Rust issue - https://users.rust-lang.org is a better place to ask for help with code issues
