### ISSUE TITLE
Tracking Issue for Rust 2024: rustfmt style editions

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#123799]
This is a tracking issue for support for style editions in rustfmt.  This is needed to support the Style Edition 2024 which is expected to be released with Rust 2024.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement in nightly Rust 2024.
    - https://github.com/rust-lang/rustfmt/pull/6247  
- [x] Add documentation to the [edition guide][].
    - https://github.com/rust-lang/edition-guide/pull/331 
- [x] Add formatting for new syntax to the [style guide][].
    - See the [nightly style procedure][].
- [x] Ensure ready for Rust 2024 stabilization.

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

None.

### Related

- https://github.com/rust-lang/rustfmt/pull/5933
- https://github.com/rust-lang/rustfmt/pull/5937
- https://github.com/rust-lang/rustfmt/pull/6247

cc @rust-lang/rustfmt @rust-lang/style @calebcartwright

**Comment by ytmimi** [comment]
You can also add https://github.com/rust-lang/rustfmt/pull/5933 to the implementation history

**Comment by calebcartwright** [comment]
note from today's t-style meet: use this one in the edition guide to provide additional/broader context around the style edition impacts, stability policy, etc. so that it doesn't needed to be repeated in other edition sections

**Comment by traviscross** [comment]
@rustbot labels +S-tracking-ready-for-edition

We've reviewed, and this item is now **ready** for Rust 2024.  Thanks to @calebcartwright, @ytmimi, and the rest of the rustfmt team for pushing forward this important work and making it ready for the edition.
