### ISSUE TITLE
Make bors warn about commits without issue #s

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#12373]
As @brson says below: Let's run an adapted http://github.com/jdm/highfive under bors's account.

(Original bug follows)

----

### Original title: Make bors warn about commits without issue #s

In the [meeting today](../wiki/Meeting-weekly-2014-02-18#wiki-issue-numbers-in-commits) we decided to start trying to get more issue #s on pull requests so it's more clear why things are changing.

**Comment by steveklabnik** [comment]
I'm marking this as 'lint,' even though that's a bit odd. Is this still something we want?

**Comment by nick29581** [comment]
It's not really a lint thing - we wouldn't lint for it, we would check using highfive. However, GH seems to be better at getting links to issues from commits and I haven't noticed this problem so much recently. Also, seems like changing the culture to have issues filed for every bug fix would be impossible. Closing.
