### ISSUE TITLE
Tracking Issue for Rust 2024: rustfmt use version sort

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#123800]
This is a tracking issue for the rustfmt / T-style work needed to use version sort order in Style Edition 2024.

- https://github.com/rust-lang/style-team/issues/143
- https://github.com/rust-lang/rust/pull/115046

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement in nightly Rust 2024.
  - https://github.com/rust-lang/rustfmt/pull/6284 
  - https://github.com/rust-lang/rustfmt/pull/6368
- [x] Add documentation to the [edition guide][].
   - https://github.com/rust-lang/edition-guide/pull/332
- [x] Add formatting for new syntax to the [style guide][].
    - https://github.com/rust-lang/rust/pull/115046
- [x] Ensure ready for Rust 2024 stabilization.

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

None.

### Implementation history

- https://github.com/rust-lang/rustfmt/pull/6284
- https://github.com/rust-lang/rustfmt/pull/6368
- https://github.com/rust-lang/style-team/issues/143
- https://github.com/rust-lang/rust/pull/115046
- https://github.com/rust-lang/rustfmt/issues/4381
- https://github.com/rust-lang/rustfmt/pull/3764

cc @rust-lang/rustfmt @rust-lang/style @calebcartwright

**Comment by joshtriplett** [comment]
@calebcartwright @traviscross Verifying: this is labeled `T-style` and `I-style-nominated`, but as far as I know, this is something style already reviewed, approved, and merged into the style guide. I *think* this is now exclusively a matter for the rustfmt team, right?

**Comment by traviscross** [comment]
@rustbot labels +S-tracking-ready-for-edition -I-style-nominated

We reviewed this on the edition call.  This is now **ready** for Rust 2024.

Thanks to @calebcartwright and the rest of the rustfmt team and style team for pushing this forward.
