### ISSUE TITLE
Type inference failure for `f32`

### ISSUE THREAD

**Issue by P1n3appl3** [rust-lang/rust#123824]
After [this rollup](https://github.com/rust-lang/rust/pull/123755) we started seeing the following compile failure:

```rust
fn main() {
    let x = f32::from(3.14);
}
```

```console
error[E0277]: the trait bound `f32: From<f64>` is not satisfied
  --> /tmp/repro.rs:2:13
   |
16 |     let x = f32::from(3.14);
   |             ^^^ the trait `From<f64>` is not implemented for `f32`
   |
   = help: the following other types implement trait `From<T>`:
             <f32 as From<bool>>
             <f32 as From<f16>>
             <f32 as From<i16>>
             <f32 as From<i8>>
             <f32 as From<u16>>
             <f32 as From<u8>>

error: aborting due to 1 previous error
```

I repro'd this locally on aa6a697a1c75b0aa06954136f7641706edadc2be but we have [CI that runs on every commit](https://ci.chromium.org/p/fuchsia/g/rust/console) so we're fairly sure that it started with 4435924bb62cda0131e38dd5d2bba36f9616039f. Of the changes in that rollup #122470 is the only one that seemed to touch float stuff, but I'm not sure how adding some extra impls for `f16` and `f128` would break inference in this case.

**Comment by jieyouxu** [comment]
cc @tgross35: is it possible that adding the the `From` impls for `f16`/`f128` may have caused type inference regression here?

**Comment by tgross35** [comment]
It must be, but I don't know why since https://github.com/rust-lang/rust/pull/122470/files#diff-154dff23a2c2f4fb97915229fd9c27d73293940250088020bfd2074094186ce4R171 wasn't touched. Also reproduced locally

**Comment by Nemo157** [comment]
When there is only one applicable impl it can guide inference, as soon as there are multiple it can't use those and instead goes to default-numeric-fallback which appears to be `f64` for floating point.

**Comment by workingjubilee** [comment]
Correct.

**Comment by tgross35** [comment]
Just coming to the same conclusion - the literal is getting guided to f32 on stable since that's the only type that fits the `from`, but when there are more options it gets the default float literal type of f64

```rust
fn main() {
    let a = 3.14;
    dbg!(std::any::type_name_of_val(&a)); // prints f32 on stable
    let x = f32::from(a);
}
```

**Comment by tgross35** [comment]
Race condition 😆 

<img width="497" alt="image" src="https://github.com/rust-lang/rust/assets/13724985/a3b022ad-be06-44f2-9251-78839283f60a">

**Comment by jieyouxu** [comment]
I did not remove the feature label lol (it wasn't even in the list), welldone GitHUb

**Comment by fmease** [comment]
Theoretically, type inference regressions are permitted as part of Rust's 1.0 stability guarantees.

In practice, if the regressions are too bad, the changes get reverted and are subsequently blocked indefinitely iirc.

However, we could make use of editions if the worst comes to the worst. See arrays & `IntoIterator`. I think we have something similar queued up for Rust 2024. On mobile, can't link.

**Comment by tgross35** [comment]
I put a fix up at https://github.com/rust-lang/rust/pull/123830 and opened https://github.com/rust-lang/rust/issues/123831 to further discuss what we want to do here.

Thanks @P1n3appl3 for identifying this so quick!

**Comment by tgross35** [comment]
@P1n3appl3 if you get the chance, could you link some of the places that caused this failure? It would be good to have some references for how this behavior is being relied on in the wild.

**Comment by P1n3appl3** [comment]
[This was the one](https://cs.opensource.google/fuchsia/fuchsia/+/main:src/recovery/lib/recovery-ui/src/keyboard.rs;l=111;drc=e1ed8a47e77b0ea1d6f83b93830c4e975a8a6089) that we caught it on. It's a pretty simple case (that `Coord` type is just an `f32` type alias) and seems reasonable to break on an edition boundary.

**Comment by BD103** [comment]
> @P1n3appl3 if you get the chance, could you link some of the places that caused this failure? It would be good to have some references for how this behavior is being relied on in the wild.

Hi! I'm from the Bevy project. We caught this bug with [this run](https://github.com/bevyengine/bevy/actions/runs/8656214035) too, though the error originates from the [Taffy](https://github.com/DioxusLabs/taffy) crate.

**Comment by tgross35** [comment]
Awesome, thanks for the report! I started a list at https://github.com/rust-lang/rust/issues/123831.

The fix for this was merged so should be available on the next nightly (couple of hours?).
