### ISSUE TITLE
Tracking Issue for Rust 2024: rustfmt change sort to Unicode-aware "non-lowercase before lowercase"

### ISSUE THREAD

**Issue by traviscross** [rust-lang/rust#123802]
This is a tracking issue for the rustfmt / T-style work needed to change the sort order to Unicode-aware "non-lowercase before lowercase" (from "ASCIIbetical") in Style Edition 2024.

- https://github.com/rust-lang/rustfmt/issues/5269

### About tracking issues

Tracking issues are used to record the overall progress of implementation.  They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.  A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.  Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement in nightly Rust 2024.
  - https://github.com/rust-lang/rustfmt/pull/6284 
- [x] Add documentation to the [edition guide][].
    - https://github.com/rust-lang/edition-guide/pull/332
- [x] Add formatting for new syntax to the [style guide][].
    - See the [nightly style procedure][].
- [x] Ensure ready for Rust 2024 stabilization.

[dev guide]: https://github.com/rust-lang/rustc-dev-guide
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs
[edition guide]: https://github.com/rust-lang/edition-guide
[nightly style procedure]: https://github.com/rust-lang/style-team/blob/master/nightly-style-procedure.md
[reference]: https://github.com/rust-lang/reference
[reference-instructions]: https://github.com/rust-lang/reference/blob/master/CONTRIBUTING.md
[style guide]: https://github.com/rust-lang/rust/tree/master/src/doc/style-guide

### Unresolved Questions

None.

### Implementation history

- https://github.com/rust-lang/rustfmt/pull/6284

TODO.

cc @rust-lang/rustfmt @rust-lang/style @calebcartwright

**Comment by joshtriplett** [comment]
@calebcartwright @traviscross Verifying: this is labeled `T-style` and `I-style-nominated`, but as far as I know, this is something style already reviewed, approved, and merged into the style guide. I *think* this is now exclusively a matter for the rustfmt team, right?

**Comment by calebcartwright** [comment]
> @calebcartwright @traviscross Verifying: this is labeled `T-style` and `I-style-nominated`, but as far as I know, this is something style already reviewed, approved, and merged into the style guide. I _think_ this is now exclusively a matter for the rustfmt team, right?

Sorry for the delayed response, but I'd agree.

https://github.com/rust-lang/rust/pull/115046 covered everything we wanted to do, and it's now just down to implementation.

@traviscross the only reason I could think to keep the nominated label is so that this remains as an item that gets pulled in for the weekly check-ins?

**Comment by traviscross** [comment]
That's right.  Being nominated means simply that it will come up on the agenda for discussion.  If that's not what we want, then we could unnominate.

However, perhaps we *do* want these to come up for review every week.  On the lang side, we review the priority items for the edition every week, to check in on the status, and something similar seems it may be appropriate here, especially as there is remaining non-implementation work to do for many of these items, e.g. making PRs to the edition guide describing the style (and consequently rustfmt behavior) changes.

With the edition hat on, I'd prefer these to come up every week *somewhere* until we can mark these off the list, and so if there's not a weekly rustfmt call, then the style call seems the next best place.

**Comment by traviscross** [comment]
@rustbot labels +S-tracking-ready-for-edition -I-style-nominated

We reviewed this on the edition call.  This is now **ready** for Rust 2024.

Thanks to @calebcartwright and the rest of the rustfmt team and style team for pushing this forward.
