### ISSUE TITLE
"undefined reference to `WaitOnAddress'" error with nightly toolchain nightly-2024-03-28 on Windows GNU target

### ISSUE THREAD

**Issue by eitsupi** [rust-lang/rust#123923]
From pola-rs/r-polars#1034

We changed toolchain from `nightly-2024-02-23` to `nightly-2024-03-28` and observed that the build of the Windows GNU target fails on GitHub Actions.

Perhaps it is related to #121956 because of the following error?

```log
 C:\rtools43\x86_64-w64-mingw32.static.posix\bin/ld.exe: D:/a/r-polars/r-polars/src/rust/target/x86_64-pc-windows-gnu/release/libr_polars.a(std-8f4e0be8cbff0503.std.7edf61c32d6c05d5-cgu.0.rcgu.o): in function `std::sys::pal::windows::futex::wait_on_address':

/rustc/c9f8f3438a8134a413aa5d4903e0196e44e37bbc/library\std\src\sys\pal\windows/futex.rs:55: undefined reference to `WaitOnAddress'
```

<https://github.com/pola-rs/r-polars/actions/runs/8679648656/job/23798732571?pr=1034#step:9:643>

Thanks in advance.

**Comment by ChrisDenton** [comment]
You probably need to add `-lsynchronization` to https://github.com/pola-rs/r-polars/blob/54feba10a5429f3f8d18c8d01fe08f4ecde5573e/src/Makevars.win#L9

Or somewhere like that. I'm not familiar with pola-rs. The problem is `WaitOnAddress` is in a different import library to other imported functions.

**Comment by eitsupi** [comment]
> You probably need to add `-lsynchronization` to [pola-rs/r-polars@`54feba1`/src/Makevars.win#L9](https://github.com/pola-rs/r-polars/blob/54feba10a5429f3f8d18c8d01fe08f4ecde5573e/src/Makevars.win#L9)

Thanks for your quick response, it works for me!
