### ISSUE TITLE
Separate tests from code under test in libraries

### ISSUE THREAD

**Issue by aepsil0n** [rust-lang/rust#12393]
The bug reported in #12383 made me aware of the convention that tests in non-std libraries often reside in the same file as the code under test. The privacy issue seen in that bug appears to be an immediate consequence of this convention. The convention also leads to pretty large source files that are imho difficult to handle.

Thus I would like to discuss whether this convention should be changed. To suggest a concrete alternative:

- Separate the tests into logically coherent units that focus on testing a certain functionality, each of which resides in a separate file
- Put all these test files into a dedicated test module that is flagged with one #[cfg(test)] in `lib.rs`; the test module may have substructure depending on the complexity of the library being tested

**Comment by steveklabnik** [comment]
Conventions changes go through the RFC process today, and so I'm giving this issue a close. Please open an RFC if you'd like to persue this further. Thanks.

**Comment by ofek** [comment]
@steveklabnik Was there ever an RFC? If not, is there now a standard way to separate tests?

**Comment by computersarecool** [comment]
@steveklabnik I am also interested in an answer to this.

**Comment by aepsil0n** [comment]
Seeing this popping up now again in my inbox. I never opened an RFC for this and kind of got used to it by now ;)

**Comment by mitermayer** [comment]
I truly believe that giving a better API/Option to write tests outside of the same file would be extremely beneficial for RUST language as whole. It would reduce the barrier for other adopters as well as ensure file size can be kept small without sacrificing on reducing documentation/testing.

I really would love if this issue could be reconsidered.

**Comment by ofek** [comment]
Has there been any progress on this (RFC)?
