### ISSUE TITLE
make compiletest aware whether compiler was built with debug assertions

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#123987]
I would like to be able to add tests of the form:
"rustc must crash on this file, but only if the compiler was built with debug assertions, otherwise the test shall be ignored (since it wont crash)"

**Comment by jieyouxu** [comment]
@matthiaskrgr does `//@ only-debug` do what you want? cf. https://rustc-dev-guide.rust-lang.org/tests/directives.html?highlight=ignore-debug#controlling-when-tests-are-run.

**Comment by matthiaskrgr** [comment]
````
error: detected unknown compiletest test directive `only-debug` in /home/matthias/vcs/github/rust/tests/crashes/1234.rs:2
errors encountered during EarlyProps parsing: /home/matthias/vcs/github/rust/tests/crashes/1234.rs
thread 'main' panicked at src/tools/compiletest/src/header.rs:68:13:
errors encountered during EarlyProps parsing
````
`¯\_(ツ)_/¯`

**Comment by jieyouxu** [comment]
Okay I see, historically there was a `// only-debug`, but it was never actually used in the test suite, it it's absent from the command-list allowlist. It also doesn't do what you want because that's conditional on std debug assertions.
