### ISSUE TITLE
Invalid reasoning using `negative_impls`

### ISSUE THREAD

**Issue by jflatow** [rust-lang/rust#124035]
I tried this code:

```rust
#![feature(negative_impls)]

pub trait A {}
pub trait B {}
pub trait C {}

impl<T: A> B for T {}
impl<T: B> C for T {}

pub trait G {}

impl<T: G> !A for T {} // <- compiler doesn't seem to take into account
impl<T: G> !B for T {} // <- compiler thinks there is already a positive impl, even though it only covers T: A and G: !A

impl<T: G> C for T {} // <- the end goal, which trips already on the previous error
```

I expected this to compile. I thought this was a fairly simple example, and I'm not sure how people are using negative impls at all if this doesn't work.

Instead, it produces two errors: 

```
error[E0751]: found both positive and negative implementation of trait `B`:
  --> negtrait.rs:13:1
   |
7  | impl<T: A> B for T {}
   | ------------------ positive implementation here
...
13 | impl<T: G> !B for T {}
   | ^^^^^^^^^^^^^^^^^^^ negative implementation here

error[E0119]: conflicting implementations of trait `C`
  --> negtrait.rs:15:1
   |
8  | impl<T: B> C for T {}
   | ------------------ first implementation here
...
15 | impl<T: G> C for T {}
   | ^^^^^^^^^^^^^^^^^^ conflicting implementation

error: aborting due to 2 previous errors
```

The second error makes sense given the first, but the first is surprising. I would think the compiler could recognize that these implementations cannot overlap and that this is exactly the type of thing negative impls are meant to express.

### Meta

`rustc --version --verbose`:
```
rustc --version --verbose
rustc 1.77.2 (25ef9e3d8 2024-04-09)
binary: rustc
commit-hash: 25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04
commit-date: 2024-04-09
host: aarch64-apple-darwin
release: 1.77.2
LLVM version: 17.0.6
```
</p>
</details>

**Comment by compiler-errors** [comment]
Hi -- you need to enable `#![feature(with_negative_coherence)]` to make coherence take negative impls into account.

I tested the example with that flag and it seems to work -- please open a new issue if you think there's a bug with the negative coherence feature.

**Comment by jflatow** [comment]
Thanks @compiler-errors, that works perfectly! This is my favorite type of answer 🙇‍♂️
