### ISSUE TITLE
Do not use relative path in rustc doc

### ISSUE THREAD

**Issue by mu001999** [rust-lang/rust#124028]
We have some relative links in doc, e.g., the link of `qpath_res` in the comments for `QPath`:
```rust
/// Represents an optionally `Self`-qualified value/type path or associated extension.
///
/// To resolve the path to a `DefId`, call [`qpath_res`].
///
/// [`qpath_res`]: ../../rustc_middle/ty/struct.TypeckResults.html#method.qpath_res
#[derive(Debug, Clone, Copy, HashStable_Generic)]
pub enum QPath<'hir> { ... }
```

but we will get the `Not Found` page if we click it in https://doc.rust-lang.org/stable/nightly-rustc/rustc_hir/enum.QPath.html, which is re-exported.

So I think we can fix this by two ways:
1. Don't use relative path in rustc doc
2. Don't generate new link for re-exported items, use the same links with the original definition

but for the second option, we may have private middle mods, so it may be not a solution.

**Comment by fmease** [comment]
cc #74481

**Comment by m1sk9** [comment]
I'm thinking of tackling this issue, is this Issue aimed at removing this invalid path once and for all? 
(Sorry if I'm wrong as I'm trying to contribute for the first time)

**Comment by heiseish** [comment]
Hi @danik292, just checking if you are still working on the issue? If so, apologies please ignore this. Otherwise I'm happy to take over. Thanks

**Comment by danik292** [comment]
@saethlin  take it
