### ISSUE TITLE
Resolve the nested inner macros correctly

### ISSUE THREAD

**Issue by edwardw** [rust-lang/rust#12404]
Currently, the inner macro in a nested macro invocation is not properly resolved which prevents nested macro invocation from working. If we are to support such invocation, this issue ought to be fixed.

cc #11692. #9323 is also relevant with regard to the macro scope rules in general.

---

_Example from #13876_:

The expression `println!(format!("test"))` produces the following error:

```
<anon>:18:18: 18:24 error: macro undefined: 'format'
<anon>:18         println!(format!("test"))
                           ^~~~~~
<anon>:18:18: 18:33 error: format argument must be a string literal.
<anon>:18         println!(format!("test"))
                           ^~~~~~~~~~~~~~~
error: aborting due to 2 previous errors
```

**Comment by steveklabnik** [comment]
Looks like this may be fixed:

```
hello.rs:2:14: 2:28 error: expected a literal
hello.rs:2     println!(format!("lol"));
                        ^~~~~~~~~~~~~~
```

**Comment by KalitaAlexey** [comment]
Hi @steveklabnik,

It works. Why this issue still opened?

**Comment by Mark-Simulacrum** [comment]
Yeah, I think that we've solved this.
