### ISSUE TITLE
std::env::args_os always returns an empty iterator in a musl+gcompat environment

### ISSUE THREAD

**Issue by rjsberry** [rust-lang/rust#124126]
I tried this code in Alpine Linux cross compiled to `x86_64-unknown-linux-gnu`:

```rust
use std::env;

fn main() {
    println!("{:?}", env::args_os().collect::<Vec<_>>());
}
```

For reference I ran this in a container on an M1 Macbook:

```
$ docker run --rm -it --platform linux/amd64 alpine
# apk add gcompat libgcc
```

I always see `[]` printed, even when I pass the program arguments.

I'm not sure this is an issue with the environment as the following C program works as expected:

```c
#include <stdio.h>

int main(int argc, char **argv) {
    for (int i = 0; i < argc; i++) {
        printf("%d: %s\n", i, argv[i]);
    }
}
```

### Meta

`rustc +nightly --version --verbose`:
```
rustc 1.79.0-nightly (becebb315 2024-04-17)
binary: rustc
commit-hash: becebb3158149a115cad8a402612e25436a7e37b
commit-date: 2024-04-17
host: aarch64-apple-darwin
release: 1.79.0-nightly
LLVM version: 18.1.3
```

**Comment by workingjubilee** [comment]
uh.

**Comment by ChrisDenton** [comment]
I can take a guess at why this happens. For glibc targets we assume that the arguments can be retrieved without needing to store `argc` and `argv`. However if this musl compatibility layer doesn't store them in the `.init_array` then we can't retrieve them.

**Comment by workingjubilee** [comment]
Ah yeah, it seems that behavior is a GNU extension that Rich Felker doesn't want to support?

**Comment by workingjubilee** [comment]
Does `env::args()` just not work at all on musl if we're a cdylib, then?

**Comment by bjorn3** [comment]
Correct. When libstd's start function isn't used, `env::args()` only works on Windows, macOS and Linux with Glibc. On any other target it returns an empty list.

**Comment by workingjubilee** [comment]
Apparently we already have this comment:

https://github.com/rust-lang/rust/blob/07d0d7ce3fd22e4fadd61206034af6fadcdb3e4f/library/std/src/sys/pal/unix/args.rs#L101-L107

In other words, we are already hacking around this issue for the miri emulator, and not using the fact that we are still given argv "naturally" via execve.

We should probably just unconditionally call `really_init`.

**Comment by bjorn3** [comment]
> We should probably just unconditionally call really_init.

That would fix https://github.com/rust-lang/rustc_codegen_cranelift/issues/1048 on Linux + glibc too.

**Comment by ChrisDenton** [comment]
Note that this was intentionally done https://github.com/rust-lang/rust/pull/66547 but there have been other issues https://github.com/rust-lang/rust/issues/105999

**Comment by workingjubilee** [comment]
@ChrisDenton I still think we can consider #105999 to still be fixed, as we just get a pointer to the argv, and it will be the same argv, right? Basically we'll set the atomics twice to the same value, which sounds very Working As Intended.

**Comment by workingjubilee** [comment]
> One other thought: if we initialize arguments this way, we don't *also* need to initialize them in our main function in binaries. Can you compile out that code on linux-gnu?

— *@joshtriplett in https://github.com/rust-lang/rust/pull/66547#pullrequestreview-321006514*

Well, given the remarks here seem to position this as a "wouldn't it be nice if we didn't do extra work?" and that this seems to be non-resilient in practice, as it has caused more than one open issue, I think we should be unafraid of doing a bit of extra computation.

**Comment by ChrisDenton** [comment]
I more meant that the fact that libraries mess about with (what should be) immutable memory is a safety issue so ideally we would parse it at the point where it's least likely that the are multiple threads. But people would probably complain about doing unnecessary allocating and extra work pre-main.

Just storing argc and argv should be cheap though so I'm definitely not arguing against that.

**Comment by workingjubilee** [comment]
the dilemma: strictly conforming posix programs shouldn't mutate argc and argv, but strictly conforming posix programs also shouldn't be aware of argc and argv if it isn't passed to dylibs, eh?

**Comment by joshtriplett** [comment]
Could we check, first, whether we've already had these initialized, and only call this in the unusual case where they're not initialized? That would avoid the extra work in the common case, and do the work in the unusual case.

**Comment by workingjubilee** [comment]
@joshtriplett I don't know what you mean? We aren't doing substantial extra work. The thing that costs the most in runtime startup, I expect, is having the static initializer at all, which we then don't get to make choices about whether its called. It simply is or isn't.

**Comment by joshtriplett** [comment]
@workingjubilee Nevermind: https://github.com/rust-lang/rust/pull/124447#issuecomment-2224108018
