### ISSUE TITLE
Miscompilation due to MatchBranchSimplification MIR pass mixing up discriminants

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#124150]
https://github.com/rust-lang/rust/pull/120614 introduced a miscompilation; turns out [this question](https://github.com/rust-lang/rust/pull/120614/files#r1569630661) poked at incorrect logic in the MatchBranchSimplification MIR pass.

https://github.com/rust-lang/rust/pull/124122 is a WIP patch to fix this (and also contains a testcase that currently gets miscompiled), but as a critical soundness issue this deserves tracking nonetheless.

**Comment by RalfJung** [comment]
Cc @rust-lang/wg-mir-opt

**Comment by DianQK** [comment]
> does it make sense to quickly throw up a PR disabling it to leave more time for fixing it properly and thoroughly?

I like this: https://github.com/rust-lang/rust/pull/124122#issuecomment-2065829553.
I think that disabling some transforms where miscompilation might occur is feasible in #124122.

**Comment by Nilstrieb** [comment]
yeah, could you put up a quick PR to disable it?

**Comment by DianQK** [comment]
> yeah, could you put up a quick PR to disable it, gating it behind unsound MIR opts?

I will do it today. :)

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23124150.20Miscompilation.20due.20to.20MatchBranchSimplification.20MIR.E2.80.A6)).

@rustbot label -I-prioritize +P-critical

**Comment by DianQK** [comment]
> yeah, could you put up a quick PR to disable it, gating it behind unsound MIR opts?

I've rethought this scenario, and it's appropriate to add unsound opts. Because this pass is mostly all in  #120614. :)

**Comment by Nilstrieb** [comment]
I think disabling the entire pass should have a very small impact, it's not like this is the LLVM instcombine pass :D. So that makes more sense, it's usually how we do it for less important MIR opt passes.

**Comment by DianQK** [comment]
I caused a P-critical issue for the first time. :p

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/pull/124156 landed so the soundness bug is fixes by disabling the affected optimization. Thanks @DianQK for the quick fix. :)
