### ISSUE TITLE
Allow run-make-support unit tests to be run with bootstrap command `x test src/tools/run-make-support`

### ISSUE THREAD

**Issue by jieyouxu** [rust-lang/rust#124267]
The `run-make-support` library is currently not registered/configured in bootstrap to be able to run its unit tests via `x test src/tools/run-make-support`. See https://github.com/rust-lang/rust/blob/7f2fc33da6633f5a764ddc263c769b6b2873d167/src/bootstrap/src/core/build_steps/test.rs#L731 for an example on how compiletest unit tests are ran.

I plan to get to this eventually (busy ATM), but if someone wants to try implementing this feel free to claim it.

**Comment by JoverZhang** [comment]
Thanks, I'm doing this.

@rustbot claim
