### ISSUE TITLE
Audit all concurrent types for &mut aliases

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#12429]
Followup to https://github.com/mozilla/rust/issues/11583

It is incorrect to allow `&mut` to alias in parallel. Mutable concurrent types must use interior mutability where &mut would result in aliasing.

**Comment by steveklabnik** [comment]
What do we think the status is of this today? @aturon , I'd imagine that during stability, these kinds of concerns have been addressed, yes?

**Comment by alexcrichton** [comment]
Yeah I think that all public-facing types have been audited as necessary. A lot of the internal implementation details of channels still need to be dealt with, but that can always happen at a later date!
