### ISSUE TITLE
vec not free memory.

### ISSUE THREAD

**Issue by zhangxize** [rust-lang/rust#124249]
vec not free momeny.
![vectest](https://github.com/rust-lang/rust/assets/24538563/e9f64693-83d4-4d79-a52f-b11ac6766031)
[main.zip](https://github.com/rust-lang/rust/files/15058207/main.zip)

**Comment by zhangxize** [comment]
Before the 6th attempt, the memory increased slightly and then stopped at 277M

**Comment by thynson** [comment]
It is working as intended and depends on the implementation of the memory allocator.

When a Vec is dropped, the corresponding memory is returned to the allocator, while the allocator may keep it for next allocation, instead of returning it to the OS directly.

**Comment by saethlin** [comment]
This is a common observation about heap allocators.
