### ISSUE TITLE
The compiler keeps going on Ctrl-C

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#124212]
Sometimes when things go really wrong the compiler emits a *ton* of error messages. This can actually take a while to render them all. And since somewhat recently, hitting Ctrl-C no longer interrupts that, I get a thousand error messages displayed after Ctrl-C.

I suspect this may have to do with https://github.com/rust-lang/rust/pull/111769. The Ctrl-C handler does nothing at all on the first Ctrl-C unless the compiler is in the middle of const-eval.

Cc @saethlin

**Comment by saethlin** [comment]
Do you have a reproducer? I have not run into this myself.

The implementation should also ensure that the compiler exits promptly if you hit ctrl+c again. Does it?

**Comment by matthiaskrgr** [comment]
if stuff keeps going on ctrl+c, sometimes suspending the process (ctrl+z) and then killing the terminal does the trick somehow :sweat_smile:

**Comment by RalfJung** [comment]
> Do you have a reproducer? I have not run into this myself.

Unfortunately no, I encountered this during some rustc hacking where I ended up getting well over 1k error messages in the standard library build and that turned out to be hard to cancel.

> The implementation should also ensure that the compiler exits promptly if you hit ctrl+c again. Does it?

I thought I had tried that, but I am not entirely sure.

**Comment by ChrisDenton** [comment]
Is it possibly the shell is part of the problem? If, by the time you hit ctrl-c, it's working through a large amount of output it still has buffered then it might be awhile before you see a response.

**Comment by RalfJung** [comment]
It's *possible*, sure -- but usually it reacts to Ctrl-C immediately even when there's tons of output.

**Comment by fmease** [comment]
Have you tried reverting #111769 to check if that fixes it?

**Comment by RalfJung** [comment]
No. At the time I was busy getting a PR done and now I don't have a reproducing example any more.

**Comment by bjorn3** [comment]
https://github.com/rust-lang/rust/pull/111769 only checks for ctrl-c during const eval, so if no const eval runs for an extended period of time, the ctrl-c will be silently ignored. This is not the only problem with that PR. It also caused https://github.com/rust-lang/rust/issues/124265, and shows the "compilation was interrupted" error after the prompt is already drawn by bash.

**Comment by workingjubilee** [comment]
is there a good way to make rustc loop endlessly without ever touching const eval? maybe via the trait solver? :thinking:

**Comment by fmease** [comment]
Yeah, just take any https://github.com/rust-lang/rust/labels/I-hang issue.
I can reproduce this issue with #122443 for example:

* nightly-2024-03-26 (before #111769): Exits after a single ^C
* nightly-2024-03-27 (after #111769): Requires ^C^C to exit

bjorn3's analysis checks out.

**Comment by workingjubilee** [comment]
cool!

**Comment by bjorn3** [comment]
Another case where this is observed: https://github.com/rust-lang/rust/issues/125428

IMO we should revert https://github.com/rust-lang/rust/pull/111769 or at least make the signal handler run `exit` after a short timeout.

**Comment by saethlin** [comment]
I'll post a PR that adds a timeout later today, but by all means if you feel strongly just put up a PR. The initial handler here was just added through the normal PR process, there's no reason to be more cautious on reverting or modifying it.
