### ISSUE TITLE
Debug for FilePermissions prints the mode in decimal.

### ISSUE THREAD

**Issue by youknowone** [rust-lang/rust#124226]
Conventionally, we print the mode in octal form, but Debug for FilePermissions prints the mode in decimal.

The printed form can be confusing when the output doesn’t include 8 or 9.

**Comment by Nilstrieb** [comment]
this should have been fixed on #122812, can you see the octal on nightly?

**Comment by workingjubilee** [comment]
Yeah, this is already resolved, afaik?

**Comment by youknowone** [comment]
Thank you!
