### ISSUE TITLE
im getting ban reports from someone

### ISSUE THREAD

**Issue by Harlemarkeyy** [rust-lang/rust#124291]
I tried this code:

```rust
<code>
```

I expected to see this happen: *explanation*

Instead, this happened: *explanation*

### Meta

`rustc --version --verbose`:
```
<version>
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by fmease** [comment]
Please contact the [moderation team](https://www.rust-lang.org/governance/teams/moderation) if you have any concerns & questions of this sort instead of opening GitHub issues. Thanks!
