### ISSUE TITLE
Rust Support for Pulsar

### ISSUE THREAD

**Issue by penguintheguy** [rust-lang/rust#124397]
hello people
simply, i would like to inform you about [Pulsar Edit](https://pulsar-edit.dev/) It is a community fork of Github's Atom Editor. I suggest you to bring your language server to this ide also. Please!! I have seen your old Atom's package in their repository. but that seems outdated.

**Comment by penguintheguy** [comment]
The editor supports lsp through different packages. The rust analyzer plugin of Atom worked well in past with this editor too. It would be great to see a plugin for this editor too. 


Also since the bases of Pulsar And atom are same. It wont be hard to port it (maybe).

**Comment by penguintheguy** [comment]
Im going to check it again. If it works. Then i would email the team about that. Hoping fot best!

**Comment by ChayimFriedman2** [comment]
Well, if it's easy, do it yourself :) Most of the editor plugins are out-of-tree, only the VSCode plugin is maintained in-tree.

**Comment by penguintheguy** [comment]
Well i'm a teenager studying in school. Just started with programming in rust. So its insane hard for me to do alone. However i can make a scriot which install all the dependencies. Also the pulsar's package manager is a bit buggy. Installing packages require to repeat the same command. Out of 3 times, 1 time the package succesfully installs.

**Comment by penguintheguy** [comment]
Seems like the package installs with its dependencies. Lets check it out. If i works good. Im gonna fork it. And find someone for help :)

**Comment by penguintheguy** [comment]
It works great So imma fork it now. keeping this open so someone may reply

**Comment by saethlin** [comment]
> simply, i would like to inform you about [Pulsar Edit](https://pulsar-edit.dev/)

Consider us informed.

The issue tracker is not a good place for discussing using Rust. You're not being annoying or anything like that, but posting on the issue tracker probably doesn't reach the right audience and GitHub issues have a very bad UI for discussion. There are a few places linked here: https://www.rust-lang.org/community and there are plenty of other places, but only those are officially moderated by the Rust organization.

**Comment by penguintheguy** [comment]
Okay :) my bad
