### ISSUE TITLE
Add a more precise niche information to BorroweFd OwnedFd in regards to ffi arguments

### ISSUE THREAD

**Issue by Maix0** [rust-lang/rust#124453]
### Location

[std::os::fs::BorrowedFd](https://doc.rust-lang.org/std/os/fd/struct.BorrowedFd.html) and [std::os::fs::OwnedFd](https://doc.rust-lang.org/std/os/fd/struct.OwnedFd.html)

### Summary

Currently the docs says that these two struct have a niche value (being `-1`), but the wording is a bit hard to understand when trying to see how to handle ffi-calls with such types.

The issue I had was: Is it legal (right term?) to use `Option<BorrowedFd>` as an argument to an `extern "C"` so it never construct an invalid representation of the type.

After careful reading of the doc I figured it is legal.
I think that having a simple `extern "C"` function definition in the description might help other persons with such issues.

For example something akin to 
> <Current Documentation>
> 
> As such, a function with this signature will be able to differentiate between an illegal file descriptor (`-1`) and a legal one (though it may be invalid)
> 
>```rust
>/// This function will return NULL in case of error
>extern "C" fn line_from_fd(borrowed_fd: Option<BorrowedFd<'_>>) -> *mut ffi::c_char {
>     match borrowed_fd {
>         /*The caller passed -1, so it will never be a valid file descriptor*/
>         None => std::ptr::null_mut(),
>         Some(fd) => {
>             /*do some stuff*/
>         }
>     }
>}
>```

**Comment by the8472** [comment]
The only guaranteed niche optimizations for `Option<T>` are listed in the [option module](https://doc.rust-lang.org/nightly/std/option/index.html#representation).

> and it never has the value -1

This only means it's guaranteed to never have that value (anything else would be UB). It does not make guarantees about structs containing this type.

If you want to let C pass arbitrary numbers then you should use `RawFd` and then convert it to `Option<BorrowedFd>`

**Comment by Maix0** [comment]
I see, this does confuse me since the niche isn't really useful then (at least when dealing with ffi arguments).
Is this more of an documentation thing (and rustc guaranty, since currently on stable they both have the same size.

It *would* be great if such thing could be guarantied, but atlast if it currently isn't, then my suggestion isn't relevant at the moment.

Thanks for replying though!
