### ISSUE TITLE
Regression when doc string invokes a macro which is defined within the same module

### ISSUE THREAD

**Issue by danielhenrymantilla** [rust-lang/rust#124535]
### Code

I tried this code:

```rust
mod module {
    #![doc = foo!()]

    macro_rules! foo {() => (
        ""
    )}
}
```

I expected to see this happen:

```
✅
```

Instead, this happened:

```text
error: cannot find macro `foo` in this scope
 --> src/lib.rs:2:14
  |
2 |     #![doc = foo!()]
  |              ^^^ consider moving the definition of `foo` before this call
  |
note: a macro with the same name exists, but it appears later at here
 --> src/lib.rs:4:18
  |
4 |     macro_rules! foo {
  |                  ^^^
```

### Remark

Note that this problem _still does not occur_ at the top-most level.

That is, removing `mod module {` above makes it work:

```rs
#![doc = foo!()]

macro_rules! foo {() => (
    ""
)}
```

### Version it worked on

It most recently worked on: **+nightly-2024-04-27**

### Version with regression

`rustc --version --verbose`:
```
+nightly-2024-04-28
```

___

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

**Comment by lqd** [comment]
IIUC this is also on beta 1.79 but I don't think it's in 1.78, which becomes stable on Thursday.

**Comment by danielhenrymantilla** [comment]
Good point, in three days it will become a ![label: regression-from-stable-to-beta](https://img.shields.io/github/labels/rust-lang/rust/regression-from-stable-to-beta)

**Comment by lqd** [comment]
beta 1.79 is already out IIRC?

**Comment by bjorn3** [comment]
Why did it work at all? The doc comment is defined earlier in the source order than the macro, so it shouldn't be able to see the macro.

**Comment by lqd** [comment]
This is from #124382 cc @petrochenkov

**Comment by petrochenkov** [comment]
The AST visiting order (mutable and immutable) was tweaked in https://github.com/rust-lang/rust/pull/124382, yes.
Not sure which exactly pass is responsible for the change though.

The new behavior looks correct to me, `foo` is not in scope at the doc comment's location.
I wonder how widespread this breakage is.

**Comment by petrochenkov** [comment]
Note, that name resolution for inner attributes is not well defined, and that's why non-builtin inner attributes are unstable.
```rust
#![my::attribute] // ERROR: custom inner attributes are unstable
```

For the same reasons it would be reasonable to keep `#![key = value!()]` unstable as well, but apparently nobody thought about this in time.

The situation with `#![key = value!()]` is better than with inner attributes in general though, because at least it cannot transform content of the module it's applied to into something different.
So in `mod foo { #![key = value!()] /*items*/  }` we can resolve `value` inside `mod foo` without it going from under our feet.

**Comment by petrochenkov** [comment]
I think my preference would be fixing the root module case, auditing the implementation for other possible interesting cases, and then running crater to see what code is affected.

**Comment by rami3l** [comment]
I'm encountering this very issue (with `rustdoc`, but I guess it's the same thing), but the error messages seem a bit different, so it took me quite a while to find this issue here... I'll paste my minimal repro here so that it might help someone after me:

```rs
mod foo {
  #![doc = foo!()]
  macro_rules! foo { () => { "foo" } }
  #[doc = foo!()] struct Foo;
}
```

This gives:

```console
> cargo +beta doc --all-features --document-private-items --no-deps
 Documenting foo v0.1.0 (/Users/rami3l/Downloads/foo)
error: cannot find macro `foo` in this scope
 --> src/lib.rs:2:12
  |
2 |   #![doc = foo!()]
  |            ^^^
  |
  = help: have you added the `#[macro_use]` on the module/import?

error: could not document `foo`

> rustdoc +beta --version
rustdoc 1.79.0-beta.2 (4bf9354b9 2024-05-02)

> cargo doc --all-features --document-private-items --no-deps
 Documenting foo v0.1.0 (/Users/rami3l/Downloads/foo)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.18s
   Generated /Users/rami3l/Downloads/foo/target/doc/foo/index.html

> rustdoc --version
rustdoc 1.78.0 (9b00956e5 2024-04-29)
```

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/125734.

**Comment by lqd** [comment]
Reopening to track beta backport

**Comment by Mark-Simulacrum** [comment]
Closing, backported in https://github.com/rust-lang/rust/pull/126093.

**Comment by rami3l** [comment]
Following my previous comment in https://github.com/rust-lang/rust/issues/124535#issuecomment-2092014426, I'm experiencing a very weird situation right now with my project `pacaptr`, as `cargo clippy` gives the following warning:

```rs
warning: cannot find macro `doc_self` in this scope
 --> src/pm/dnf.rs:1:10
  |
1 | #![doc = doc_self!()]
  |          ^^^^^^^^
  |
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #124535 <https://github.com/rust-lang/rust/issues/124535>
  = help: import `macro_rules` with `use` to make it callable above its definition
warning
```
_https://github.com/rami3l/pacaptr/actions/runs/11752606941/job/32744390895?pr=746_

... although I've already applied the fix in the file:

```rs
#![doc = doc_self!()]

use std::sync::LazyLock;

use async_trait::async_trait;
use indoc::indoc;
use tap::prelude::*;

use super::{NoCacheStrategy, Pm, PmHelper, PmMode, PromptStrategy, Strategy};
use crate::{config::Config, error::Result, exec::Cmd};

macro_rules! doc_self {
    () => {
        indoc! {"
            The [Dandified YUM](https://github.com/rpm-software-management/dnf).
        "}
    };
}
use doc_self;

#[doc = doc_self!()]
#[derive(Debug)]
pub struct Dnf {
    cfg: Config,
}
```
_https://github.com/rami3l/pacaptr/blob/ef093bd1ece15328992e016514e843cfe6dfacf4/src/pm/dnf.rs#L1-L25_

Should I be worried? 🤔
