### ISSUE TITLE
How can i set minos for my rust dylib on ios

### ISSUE THREAD

**Issue by cryuhy** [rust-lang/rust#124546]
i run cargo swift package -p=ios my lib
Load command 10
cmd LC_BUILD_VERSION
cmdsize 32
platform IOS
minos 17.4
sdk 17.4
ntools 1
tool LD
version 1053.12
Load command 11
cmd LC_SOURCE_VERSION
cmdsize 16
version 0.0
how can i set minos to 14

**Comment by saethlin** [comment]
You should ask the cargo-swift project: https://github.com/antoniusnaumann/cargo-swift
