### ISSUE TITLE
Doc for std contains broken links in the implementors sections

### ISSUE THREAD

**Issue by valaphee** [rust-lang/rust#124635]
https://doc.rust-lang.org/std/clone/trait.Clone.html for example lists implementations of `Clone` in `gimli`, which aren't visible anyway and the links are also broken.

**Comment by workingjubilee** [comment]
cc @rust-lang/rustdoc

**Comment by ehuss** [comment]
I believe this regressed in #121218 (@ShoyuVanilla).

**Comment by LunarLambda** [comment]
This was closed but it's still happening on current stable docs, in various traits, Debug being the one that seems the worst:

![Screenshot_20240529_080525](https://github.com/rust-lang/rust/assets/38919842/a9ce8f04-df2f-4f8d-9f3d-4abdfba4aec3)
![Screenshot_20240529_080433](https://github.com/rust-lang/rust/assets/38919842/0225ac5a-b38b-4880-ba7d-1fdb4684a643)

**Comment by ehuss** [comment]
@LunarLambda What page are you looking at? I do not see those implementations on https://doc.rust-lang.org/nightly/std/fmt/trait.Debug.html.

**Comment by LunarLambda** [comment]
stable docs, not nightly https://doc.rust-lang.org/stable/std/fmt/trait.Debug.html

**Comment by ehuss** [comment]
The stable docs are tied to the release, so we would have to make a new release to update them.

The fix for this is in 1.80, and will reach stable on July 25.

**Comment by LunarLambda** [comment]
There's no way to backport it internally? That's unfortunate. I was hoping it would land for 1.79.0 at least

**Comment by GuillaumeGomez** [comment]
Closing then.

**Comment by workingjubilee** [comment]
> There's no way to backport it internally? That's unfortunate. I was hoping it would land for 1.79.0 at least

This can in fact be beta backported.

**Comment by workingjubilee** [comment]
And it was in https://github.com/rust-lang/rust/pull/125183

**Comment by LunarLambda** [comment]
Good to know, thank you
