### ISSUE TITLE
Explain the difference between Once(Lock|Cell) and Lazy(Lock|Cell) in the docs

### ISSUE THREAD

**Issue by panstromek** [rust-lang/rust#124696]
### Location

https://doc.rust-lang.org/std/sync/struct.LazyLock.html
https://doc.rust-lang.org/std/sync/struct.OnceLock.html

https://doc.rust-lang.org/std/cell/struct.OnceCell.html
https://doc.rust-lang.org/std/cell/struct.LazyCell.html

### Summary

Today I realized these are separate types. I used the experimental `LazyLock` before without realizing I can actually use stable `OnceLock`. These types are so similar that I never realized there are two of them.

Still, I don't think I quite understand the difference and the tradeoff (e.g. is some of them faster or not?). It would be useful if the docs pages linked to each other and explained the difference.

**Comment by workingjubilee** [comment]
LazyLock is an API you can build on top of OnceLock, and is the "obvious one" to use in many cases. OnceLock permits more potential use-cases, being the more basic form, but also often is additional complication if you wanted LazyLock.

**Comment by workingjubilee** [comment]
...so it should probably say something like that, yes.
