### ISSUE TITLE
rustc built from a source tarball reports it's `nightly`

### ISSUE THREAD

**Issue by psumbera** [rust-lang/rust#124618]
On Solaris I get following:
```
rustc --version
rustc 1.77.0-nightly (aedd173a2 2024-03-17) (built from a source tarball)
```
I'm confused about `-nightly` part.

Is it expected behavior?

**Comment by ehuss** [comment]
What is the `config.toml` settings and command you used to build?

There is a setting in `config.toml` for setting the channel.

**Comment by psumbera** [comment]
I had to add `--release-channel=stable`. Which results in `channel = 'stable'` in `config.toml`. This resolved the issue.

Question is whether `channel` shouldn't be always `stable` when building from official source tarball.

**Comment by onur-ozkan** [comment]
> I had to add `--release-channel=stable`. Which results in `channel = 'stable'` in `config.toml`. This resolved the issue.
> 
> Question is whether `channel` shouldn't be always `stable` when building from official source tarball.

Currently it's not possible because we don't have any state file in the source tarballs to determine whether they are stable, beta or nightly.

**Comment by ehuss** [comment]
`src/ci/channel` should indicate what channel the source distribution is for.
