### ISSUE TITLE
Version 1.78, after compilation, prompts on Windows 7 that GetSystemTimePreciseAsFileTime is required.

### ISSUE THREAD

**Issue by enp6** [rust-lang/rust#124666]
In previous versions, I have been using cargo build --release --target=i686-pc-windows-msvc to compile a program that supports 32-bit Windows and can run on Windows 7 to 11. However, after upgrading to version 1.78, the compiled program running in the Windows 7 environment prompts with the error message: 'Unable to locate the program input point GetSystemTimePreciseAsFileTime in the dynamic link library KERNEL32.dll.'

**Comment by 12101111** [comment]
https://blog.rust-lang.org/2024/02/26/Windows-7.html

**Comment by saethlin** [comment]
See also
https://github.com/rust-lang/compiler-team/issues/651
https://github.com/rust-lang/rust/pull/118150

**Comment by saethlin** [comment]
You are trying to use a Tier 3 target, so you must use `-Zbuild-std` to build the standard library yourself.
