### ISSUE TITLE
MIR const-prop not putting `usize` into `AggregateKind::RawPtr`?

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#124792]
Discord Context: https://discord.com/channels/273534239310479360/273541522815713281/1236936970912137236

I was surprised in <https://rust.godbolt.org/z/hnMT6K4qh> to see
```rust
        _18 = const 128_usize;
        StorageLive(_24);
        _24 = _22 as *const () (PtrToPtr);
        _23 = *const [u8] from (_24, _18);
```

Because I would have expected constprop into the Aggregate, like
```rust
        StorageLive(_24);
        _24 = _22 as *const () (PtrToPtr);
        _23 = *const [u8] from (_24, const 128_usize);
```

As happened in other places, like
```rust
        _20 = Offset(_16, const 128_usize);
        StorageLive(_21);
        _21 = Sub(_13, const 128_usize);
```

`AggregateKind::RawPtr` is relatively new (#123840), so maybe it needs to be handled properly somewhere else?

**Comment by saethlin** [comment]
I think the problem is this FIXME that you added: https://github.com/rust-lang/rust/blob/8b64adc8cdf08f927d01bf9b02cc493ca5bcb5a1/compiler/rustc_mir_transform/src/gvn.rs#L930-L931

Constant propagation is done by GVN.
