### ISSUE TITLE
Sometimes 'Σ' is not handled correctly in str.to_lowercase()

### ISSUE THREAD

**Issue by Marcondiro** [rust-lang/rust#124714]
Hello,
Due to the optimization introduced with #97046, the `to_lowercase` conversion of some `str` containing the `Σ` char is incorrect.

Simple example:
```rust
fn main(){
    println!("{}", "aΣ".to_lowercase());
    println!("{}", "abcdefghijklmnopΣ".to_lowercase());
}
```
output:
```
aς
abcdefghijklmnopσ
```
The first conversion is correct while the second is not and should be `abcdefghijklmnopς`.

More generally, this happens when 'Σ' follows a `2 * USIZE_SIZE * K` number of chars
```rust
use std::mem;

const USIZE_SIZE_BY_2: usize = 2 * mem::size_of::<usize>();
const K: usize = 1;

fn main() {
    let bug_string = "a".repeat(USIZE_SIZE_BY_2 * K) + "Σ";

    println!("{}", bug_string.to_lowercase());
}
```

**Comment by jhorstmann** [comment]
@Marcondiro I tried optimizing `to_lowercase` in #123778. In that PR the whole ascii prefix is converted by an optimized loop, which probably makes the issue easier to trigger and maybe also easier to fix. Let me know if you'd like me to look into this.
