### ISSUE TITLE
Error: failed to find a `codegen-backends` folder in the sysroot candidates

### ISSUE THREAD

**Issue by ClementNerma** [rust-lang/rust#124885]
I recently installed Rust on a new system (Fedora 40, KDE edition), but Rust doesn't seem to work properly.

At times it will refuse to build (not always, only sometimes), up until today where it doesn't want to build my project anymore (source code can be found at https://github.com/ClementNerma/ReShell).

At first everything worked fine on the Terminal, but when opening VSCode with Rust-Analyzer the latter triggered the error. Now it also happens on the terminal.

Here is the error:

```
$ cargo build # same thing happens with "check" or "release"
   Compiling proc-macro2 v1.0.79
   Compiling unicode-ident v1.0.12
   Compiling libc v0.2.153
   Compiling serde v1.0.197
    Checking cfg-if v1.0.0
   Compiling autocfg v1.1.0
   Compiling syn v1.0.109
    Checking utf8parse v0.2.1
   Compiling rustix v0.38.32
    Checking equivalent v1.0.1
    Checking hashbrown v0.14.3
   Compiling signal-hook v0.3.17
error: failed to find a `codegen-backends` folder in the sysroot candidates:
       * /home/clement/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu
       * /home/clement/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu

error: could not compile `libc` (build script) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `serde` (build script) due to 1 previous error
error: could not compile `unicode-ident` (lib) due to 1 previous error
error: could not compile `proc-macro2` (build script) due to 1 previous error
error: could not compile `cfg-if` (lib) due to 1 previous error
error: could not compile `syn` (build script) due to 1 previous error
error: could not compile `rustix` (build script) due to 1 previous error
error: could not compile `autocfg` (lib) due to 1 previous error
error: could not compile `utf8parse` (lib) due to 1 previous error
error: could not compile `equivalent` (lib) due to 1 previous error
error: could not compile `signal-hook` (build script) due to 1 previous error
error: could not compile `hashbrown` (lib) due to 1 previous error
``` 

Some infos on my system:

* OS: Fedora 40, KDE edition (up-to-date)
* Kernel: 6.8.8-300.fc40.x86_64 (OS' builtin)
* Rustup: v1.27.1 (54dd3d00f 2024-04-24)
* Cargo: 1.80.0-nightly (05364cb2f 2024-05-03)
* Rustc: 1.80.0-nightly (faefc618c 2024-05-07)

This was already happening with the previous nightly. Updating didn't fix. Removing `~/.rustup` and `~/.cargo`  then reinstalling didn't fix. Manually deleting `target`  folder didn't fix.

I have no "special" configuration. OS install is fresh, I didn't perform any specific tweak on my system, I use the builtin OS kernel without any change, I run Rust natively (not inside Docker or anything), I'm on an x64 platform. I'm using the native compiler, not any special toolchain, I don't use Cranelift, I don't have custom Cargo or Rust configuration on my system.

Any idea as to what that happens? I'm very much at a loss here...

**Comment by ClementNerma** [comment]
Ok so I'm actually stupid: I forgot that I had Cranelift enabled, and was looking at the `.cargo` directory, while the actual configuration is stored in the `Cargo.toml`  file.

So I had the `codegen-backend` feature enabled at a workspace level, which is what gave me this error. Which is still pretty confusing though.

**Comment by jeermuce** [comment]
rustup component add rustc-codegen-cranelift
