### ISSUE TITLE
LLVM 19 changes debuginfo text representation breaking at least 4 tests

### ISSUE THREAD

**Issue by durin42** [rust-lang/rust#124824]
[Caught by our buildkite](https://buildkite.com/llvm-project/rust-llvm-integrate-prototype/builds/27943#018f4f7e-c290-4779-8d81-28ff7e183e4e). Looking at the commits in the breaking range, I'm pretty confident this is llvm/llvm-project@91446e2aa687ec57ad88dc0df793d0c6e694a7c9 changing things, so it's expected.

failures:
  | [codegen] tests/codegen/debuginfo-constant-locals.rs
  | [codegen] tests/codegen/debug-fndef-size.rs
  | [codegen] tests/codegen/inline-debuginfo.rs
  | [codegen] tests/codegen/sroa-fragment-debuginfo.rs
 
Hopefully we'll get to a fix for this in the near future, but the changes look like they might be irritating to handle. There's some guidance in the LLVM change which may help, but I didn't dig today.

**Comment by workingjubilee** [comment]
Fixed in #124830.
