### ISSUE TITLE
Consider pass macro invocation arguments as AST instead of TokenTree

### ISSUE THREAD

**Issue by edwardw** [rust-lang/rust#12488]
That way, more sophisticated and precise transformation can be performed against AST before being passed into macro definitions. The main use case right now would be hygiene let bindings and loop labels.

Is this doable?

cc #12262 #10607 #12338

**Comment by steveklabnik** [comment]
Yes, I think this can be closed. This would need an RFC today, and I'm not even sure it's what we would want.
