### ISSUE TITLE
Unexpected cfgs warns on quite-intentional user-cfgs

### ISSUE THREAD

**Issue by workingjubilee** [rust-lang/rust#124821]
Cargo features are not actually appropriate for all conditional compilation, as not all conditional-compilation-keys are additive. Some are in fact mutually exclusive. Cargo does not have an adequate answer for this problem yet. It is my opinion that in general, except when it is likely a typo (levenshtein 1 from an expected cfg key or key-value pair) or is an unknown _value_ for an _expected cfg key_, the Rust compiler should not be quite as judgemental of "interesting" uses of cfgs.

Because rustc complained about so many cfgs, this basically clobbered backtrace-rs with a million irrelevant warnings that almost drowned out the one or two interesting things that did need to be fixed.

There are also ecosystem crates that use the pattern of requiring users to set a cfg to enable something, to yield control to the **binary's builder**, despite being a library crate, or that use it for things that should not be resolved the same way Cargo features are.

**Comment by workingjubilee** [comment]
cc @Urgau

**Comment by workingjubilee** [comment]
To be clear a large part of my complaint here is "there are cases where this is going to produce 100 warnings and then like 10 of them are going to be really good catches but they wind up buried under the other 90".

**Comment by Nilstrieb** [comment]
The idea is to write a build scripts that emits the check cfg directives to tell rustc which ones to additionally expect.

**Comment by Urgau** [comment]
> To be clear a large part of my complaint here is "there are cases where this is going to produce 100 warnings and then like 10 of them are going to be really good catches but they wind up buried under the other 90".

That's why we have a mechanism for adding custom cfg, it's the `cargo::rustc-check-cfg` Cargo instruction.

**Comment by workingjubilee** [comment]
And if someone doesn't want a build script and doesn't want a Cargo feature?

**Comment by Urgau** [comment]
There isn't a [third option](https://blog.rust-lang.org/2024/05/06/check-cfg.html#how-to-expect-custom-cfgs-without-a-buildrs), either it's a custom cfg and so users are expected to use a `build.rs` or it's a Cargo feature and they have nothing to do.

rustc (and by extension Cargo) needs to known the expected cfgs in order to lint on the unexpected ones and since there is two "kind" of cfg, custom cfg and Cargo feature, for Cargo feature there is nothing else to do, and for the custom ones we added the `cargo::rustc-check-cfg` instruction.

**Comment by workingjubilee** [comment]
There is a third option: be more conservative about when to issue the lint.

**Comment by epage** [comment]
Should this be closed as duplicate of #124800 to consolidate the discussion?

**Comment by workingjubilee** [comment]
Yeah for some reason #124800 slipped my notice when I scanned for duplicate issues.
