### ISSUE TITLE
Some items in std doc lead to nowhere

### ISSUE THREAD

**Issue by WiktorPrzetacznik** [rust-lang/rust#124854]
### Location

For example, first item in [array trait implementations ](https://doc.rust-lang.org/std/primitive.array.html#trait-implementations)([ArrayLike](https://doc.rust-lang.org/1.78.0/gimli/read/util/trait.ArrayLike.html)).

### Summary

Broken urls of some items in standard library (e.g. ArrayLike trait implementation for array type)

**Comment by ehuss** [comment]
I believe this is a regression noted in #124635.

**Comment by workingjubilee** [comment]
Yeah, looks perfectly identical. Thanks for the report! Closing as duplicate for now.
