### ISSUE TITLE
The naming of BufReader/BufWriter and MemReader/MemWriter is confusing

### ISSUE THREAD

**Issue by mneumann** [rust-lang/rust#12498]
It is unclear that MemReader operates on an owned vector while BufReader on a borrowed vector. For the reader I think there is no difference between a MemReader and a BufReader. <code>MemReader::new(~[1u8])</code> can be replaced by <code>BufReader::new(~[1u8].as_slice())</code>. Only the MemWriter and BufWriter differ in that MemWriter can grow the buffer.

How about this naming: <code>BufReader</code>, <code>BufWriter</code>, <code>GrowableBufWriter</code>?

**Comment by aturon** [comment]
This will be resolved during [io reform](https://github.com/rust-lang/rfcs/pull/576).

**Comment by alexcrichton** [comment]
These have all been fixed with the new `Cursor` type.
