### ISSUE TITLE
println!("{}", 9.4 * 3.0)

### ISSUE THREAD

**Issue by chedongzhe** [rust-lang/rust#125056]
println!("{}", 9.4 * 3.0);
output: 28.200000000000003

**Comment by snowfoxsh** [comment]
That is the expected output. [https://docs.python.org/3/tutorial/floatingpoint.html](https://docs.python.org/3/tutorial/floatingpoint.html). This is just an issue with how floating point numbers in general work.
![image](https://github.com/rust-lang/rust/assets/72031001/744c0440-58e1-4300-9391-10301549e4ea)

**Comment by LunarLambda** [comment]
Maybe you are looking for the [precision field](https://doc.rust-lang.org/stable/std/fmt/index.html#precision):

```rs
println!("{:.2}", 9.3 * 3.0);
```

will print `27.90`.

**Comment by cuviper** [comment]
Float Exposed is also a useful reference, as it will show you that the closest `f64` (double) to 9.4 is [9.40000000000000035527](https://float.exposed/0x4022cccccccccccd) -- and even _that_ is an approximation, but you can find the exact base-10 number later on the page. So you're starting with a higher input than you wanted, and then the multiplication result comes out higher than you wanted too.

On the other hand, [3.0](https://float.exposed/0x4008000000000000) is exact.

**Comment by fmease** [comment]
Closing as works-as-intended.
