### ISSUE TITLE
tests/crashes/124436.rs is creating a `mir_dump` directory in the repo root, not the build directory

### ISSUE THREAD

**Issue by saethlin** [rust-lang/rust#125029]
https://github.com/rust-lang/rust/pull/124775 added some tests, and one of them is creating a `mir_dump` directory in the repo root, where it really shouldn't. Surely we have ways of dumping MIR to other directories for the mir-opt tests, right?

@matthiaskrgr

**Comment by compiler-errors** [comment]
Yeah this has been annoying me recently. I put up #125032.
