### ISSUE TITLE
Incomplete template in the list of allow-by-default rustc lints

### ISSUE THREAD

**Issue by schvv31n** [rust-lang/rust#125073]
### Location

https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#unstable-features

### Summary

<img width="527" alt="imagem" src="https://github.com/rust-lang/rust/assets/73731786/db93cfaf-5b48-47bf-8c10-c2cb87b6e603">

The `{{produces}}` at the bottom looks like it should've been filled with something

**Comment by ehuss** [comment]
Thanks for the report! This has already been fixed via #124001 which will be in the 1.79 release which is currently in beta (https://doc.rust-lang.org/beta/rustc/lints/listing/allowed-by-default.html#unstable-features).
