### ISSUE TITLE
Incorrect link for `BufWriter` on `std::fs::File` page

### ISSUE THREAD

**Issue by johnbchron** [rust-lang/rust#125066]
### Location

In the description of [`std::fs::File`](https://doc.rust-lang.org/stable/std/fs/struct.File.html), the first mention of `BufWriter`:
> For efficiency, consider wrapping the file in a [BufReader](https://doc.rust-lang.org/stable/std/io/struct.BufReader.html) or [BufWriter](https://doc.rust-lang.org/stable/std/io/struct.BufReader.html)...

### Summary

The `BufWriter` link points to `BufReader`. I checked the source and the destination is not explicit, so I'm not sure what's going on here. Could be a rustdoc bug.

**Comment by tbu-** [comment]
Fixed by #123086 already.

**Comment by jieyouxu** [comment]
Closing as there's already a fix implemented.
