### ISSUE TITLE
#[rustc_pass_by_value] prevents lldb from showing the information correctly

### ISSUE THREAD

**Issue by dev-ardi** [rust-lang/rust#125121]
![image](https://github.com/rust-lang/rust/assets/47633543/eb8d9d95-b29e-46b8-87ed-3a46d52d8b6d)

```rs
#![feature(rustc_attrs)]

#[rustc_pass_by_value]
#[derive(Debug, Clone)]
struct Val;

#[derive(Debug, Clone)]
enum E {
    Foo,
    Bar(Val),
}

fn main() {
    let x = E::Foo;
    let y = E::Bar(Val);
    dbg!(x, y);
}
```
As you can see x and y have the representation of `{...}`.

This makes it very hard to use a debugger in rustc.

**Comment by compiler-errors** [comment]
This seems like a rust-analyzer bug with macros.

**Comment by dev-ardi** [comment]
What does rust-analyzer have to do here? I thought that the debug representation was all lldb. In fact r-a server is stopped in that screenshot :P

**Comment by compiler-errors** [comment]
Well then it's some other aspect of IDE integration, and it doesn't have anything to do with rustc. All that `rustc_pass_by_value` does is mark it for lint purposes: 4c3e330a8c023af20beb23a3a46b5d6d77a62839.

Also, what do you mean the r-a server is stopped in that screenshot? Isn't the "2 implementations" hint a rust-analyzer feature?

**Comment by compiler-errors** [comment]
Also, if you're trying to use `rustc_pass_by_value` in your own project? That is definitely not supported.

**Comment by compiler-errors** [comment]
Also, I'm pretty certain this has nothing to do with `rustc_pass_by_value`.

I deleted the annotations on your test example, attached `CodeLLDB` for the debugger in vscode, and I'm still getting the same output you shared:

<img width="554" alt="image" src="https://github.com/rust-lang/rust/assets/3674314/f599c606-029f-4945-b50f-a5d97694d479">

From a cursory search on the internet, I don't believe Rust has very good lldb support for debug-printing its data. I'm gonna close this issue.

**Comment by dev-ardi** [comment]
This is embarrasing :D
