### ISSUE TITLE
bootstrap rustc shim: FATAL: RUSTC_STAGE was not set

### ISSUE THREAD

**Issue by MinxuanZ** [rust-lang/rust#125122]
hi ,I want to debug rustc in bootstrap. 
How to set enviroment ?
RUSTC_STAGE RUSTC_SNAPSHOT

 .\bootstrap\debug\rustc.exe -V

**Comment by onur-ozkan** [comment]
> How to set enviroment ?

The way you set up any other environment. But bootstrap binaries aren't meant to be called directly like that. You should use `x.py` instead.
