### ISSUE TITLE
regression: cycle detected when computing whether impls specialize one another

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#125197]
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/HalsekiRaika.anyid/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/HalsekiRaika.nos/log.txt

```
[INFO] [stdout] error[E0391]: cycle detected when computing whether impls specialize one another
[INFO] [stdout]   --> /opt/rustwide/workdir/src/lib.rs:54:1
[INFO] [stdout]    |
[INFO] [stdout] 54 | impl<T: Identifier> PartialEq<T> for AnyId {
[INFO] [stdout]    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stdout]    |
```

**Comment by compiler-errors** [comment]
Bisecting this...

**Comment by compiler-errors** [comment]
This bisected in https://github.com/rust-lang/rust/pull/122791. This crate is using specialization, which we don't stably support.

> This has some interactions with specialization, and so breaks a few UI tests that I don't agree should've ever worked in the first place, and also breaks a handful of crates in a way that I don't believe is a problem.

**Comment by Mark-Simulacrum** [comment]
@compiler-errors How is that not feature gated? I don't see feature gates in the repos above and presumably it built on stable in order to regress here?

**Comment by compiler-errors** [comment]
I may actually be mistaken then @Mark-Simulacrum. I thought I looked at these crates, but perhaps I was looking at the wrong one.

**Comment by compiler-errors** [comment]
I'll look back into this...

**Comment by compiler-errors** [comment]
Opened a PR for this and nominated for beta.

**Comment by apiraino** [comment]
https://github.com/rust-lang/rust/pull/126772 was merged, so can this be closed as fixed? cc @BoxyUwU

**Comment by compiler-errors** [comment]
ya this was fixed
