### ISSUE TITLE
regression: ambiguous outer attributes

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#125199]
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/DAC098.thoughts_server/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/Emilgardis.stream_alerts/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/Tricked-dev.dws/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/antoniusnaumann.dachterasse/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/cozyGalvinism.becbot-rs/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/fadiinho.manga-suku/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/folafunmi-db.rust-url-shortener-shuttle/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/grandafrato.school_event_safety/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/kaleidawave.discord-weather-bot/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/melkir.net-entreprise-scraper/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/mikeleppane.chat-app-axum/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/mre.zerocal/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/nonsensical-answers.python-rustrict/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/oddgrd.postgres-test-deploy/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/trezm.broken-deploy-example/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/reg/AskAI-0.1.0/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/reg/plow_cli-0.5.2/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/reg/varies-0.1.1/log.txt

```
[INFO] [stdout] error: ambiguous outer attributes
[INFO] [stdout]    --> src/main.rs:284:17
[INFO] [stdout]     |
[INFO] [stdout] 284 | /                 #[cfg(feature = "rustls")]
[INFO] [stdout] 285 | |                 server = server.listen_rustls(listener, ssl_builder)?;
[INFO] [stdout]     | |_____________________________________________________________________^
[INFO] [stdout]     |
```

Probably #124099 cc @davidtwco

**Comment by davidtwco** [comment]
cc @voidc as author of #124099

**Comment by riking** [comment]
This was a breaking change merged without FCP: `rustrict` doesn't appear to include any `#![feature]` as the #124099 PR description implied, so it doesn't require nightly to trigger this.

This should be reverted and changed to a future compat warning.

**Comment by apiraino** [comment]
Issue was briefly mentioned today in the t-compiler triage meeting (on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-05-30/near/441470232)).

Seems that given the timeframe leading to the next stable (2024-06-13, in 13 days), a revert would be more appropriate.

**Comment by wesleywiser** [comment]
Yeah, since `#[something] let foo = bar;` is already accepted syntax on stable, we can't change it to be an error even if most of the places in this crater are not using it correctly. I think @riking is correct and this first needs to be made into a future compatibility warning and then a hard error over an edition boundary to preserve backwards compatibility.

**Comment by Mark-Simulacrum** [comment]
Closing since fixes landed on beta/nightly: https://github.com/rust-lang/rust/pull/126093

**Comment by lqd** [comment]
This was fixed by reverting https://github.com/rust-lang/rust/pull/124099 on nightly (in #126101) and beta (in #126093).
