### ISSUE TITLE
BufWriter is happy with non-mutable Writer

### ISSUE THREAD

**Issue by daedric** [rust-lang/rust#125149]
I tried this code:

```rust
use std::{
    fs::File,
    io::{BufWriter, Write},
};

fn writer_1() {
    let f = File::create_new("writer_1").unwrap();
    // Does not compile
    // f.write("test".as_bytes()).unwrap();
    let f2 = BufWriter::new(f);

    // Does not compile, that's expected
    // f2.write("test".as_bytes()).unwrap();
}

fn writer_2() {
    let f = File::create_new("writer_2").unwrap();
    // Does not compile
    // f.write("test".as_bytes()).unwrap();

    let mut f2 = BufWriter::new(f);
    // Does compile, f is not mut so why? that's unexpected.
    f2.write("test".as_bytes()).unwrap();
}

fn writer_3() {
    let f = File::create_new("writer_3").unwrap();
    let mut f2 = BufWriter::new(&f);

    // Does compile, Why?? That's even more unexpected
    f2.write("test".as_bytes()).unwrap();
    // Does not compile
    // f.write("test".as_bytes()).unwrap();
}

pub fn main() {
    writer_1();
    writer_2();
    writer_3();
}

```

I expected to see this happen: I expected BufWriter to need a mutable File and even more so when passed as reference.

Instead, this happened: It is happy with whatever.

### Meta

`rustc --version --verbose`:
```
rustc 1.78.0 (9b00956e5 2024-04-29)
binary: rustc
commit-hash: 9b00956e56009bab2aa15d7bff10916599e3d6d6
commit-date: 2024-04-29
host: x86_64-unknown-linux-gnu
release: 1.78.0
LLVM version: 18.1.2
```

<details><summary>Backtrace</summary>
<p>

```
NA
```

</p>
</details>

**Comment by ChayimFriedman2** [comment]
That's expected. `mut` in `let mut`` is not a property a property of the object (like `&mut` vs. `&`), it's a property of the binding. If you move the value it can become mutable/immutable again. See for example:
```rust
fn main() {
    let s = String::new();
    // s.push_str("Hello!");
    let mut s2 = s;
    s2.push_str("Hello!");
}
```

**Comment by the8472** [comment]
[impl Write for &File](https://doc.rust-lang.org/nightly/std/fs/struct.File.html#impl-Write-for-%26File)

**Comment by daedric** [comment]
Yeah we finally understood with a colleague :) thanks a lot for the confirmation.

The key missing pieces was the `impl Write for &File`.
While I understand that it is convenient, this is not something that feels safe/idiomatic since the file will seek upon write or read as this allows this kind of code:

```fn writer_1() {
    let f = File::create_new("writer_1").unwrap();
    let mut f2 = BufWriter::new(&f);
    let mut f3 = BufWriter::new(&f);

    // Does not compile, that's expected
    f2.write("test".as_bytes()).unwrap();
    f3.write("test".as_bytes()).unwrap();
}
```

**Comment by the8472** [comment]
Files are shared mutable objects, more like a `Mutex<T: Read + Write + Seek>`. Even multiple processes can write to them concurrently. It requires some careful construction to make a file really exclusively owned (e.g. O_TMPFILE).
