### ISSUE TITLE
rustc can not be launched on Windows 7 x64

### ISSUE THREAD

**Issue by the-Arioch** [rust-lang/rust#125161]
I see there are still open tickets for Win7, so i think at least the compiler should work...

Label: O-windows-7

```
C:\>rustup -V
rustup 1.27.1 (54dd3d00f 2024-04-24)

C:\>rustup toolchain list
stable-x86_64-pc-windows-msvc (default)

C:\>rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  .....

stable-x86_64-pc-windows-msvc (default)
(error reading rustc version)

---------------------------
rustc.exe - Entrypoint not found: GetSystemTimePreciseAsFileTime was not found in KERNEL32.dll. 
---------------------------

C:\>rustup check
stable-x86_64-pc-windows-msvc - Up to date : 1.78.0 (9b00956e5 2024-04-29)
rustup - Up to date : 1.27.1

C:\>rustup default x86_64-win7-windows-msvc
error: toolchain 'x86_64-win7-windows-msvc' is not installed

C:\>rustup toolchain install stable-x86_64-win7-windows-msvc
error: error: invalid value 'stable-x86_64-win7-windows-msvc' for '<toolchain>..
.': invalid toolchain name: 'stable-x86_64-win7-windows-msvc'
```
So, the workaround from https://doc.rust-lang.org/rustc/platform-support/win7-windows-msvc.html does not work.

Sadly, there is no command in `rustup` to list available for download (but not installed) toolchain targets.

The `rustup which rustc` file sadly does not have standard version information (VERSION_INFO) resource, which could've been displayed without running the unrunnable program. But the folder contains files like

* rustc_driver-d6aabfacaa866160.pdb
* rustc_main-20d3d1e276300d0d.pdb
* std-49e3d1aefc00cc02.pdb

The compiler itself is

```
File: rustc.exe
  CRC-32: 15584846
     MD5: 3b435259a00a250a7c9ff595bae36e52
   SHA-1: 1dd43ded29fe77076b39609d5d7099739be3fda7
 SHA-256: e9938466ed99b08c030c3e6c092e1c259b8ec1a0e39e0a33c7530f4cd7c12c5d
 SHA-512: 0cf6a91bb17da84591aaf4766e394e208b674c155ae9a8108221687d405e1e2397918dda808095eb55676c8cbe29f5376a7087632196bcd1c7c0566ccedc5005
```

**Comment by the8472** [comment]
The [platform support document](https://doc.rust-lang.org/rustc/platform-support.html) lists x86_64-win7-windows-msvc  only as a compile *target*, not a host toolchain. I.e. you can compile _for_ windows 7 _on_ windows 10 , but not on windows 7.
You could use the last supported rust version (1.77) instead.

**Comment by the-Arioch** [comment]
i wish `rusup update` would've been smarter then...
It's idea was to have and mantain working toolset, not to break it.

```
rustup update 1.77
rustup default 1.77
rustup toolchain uninstall stable
```

seems to work now

the target https://doc.rust-lang.org/nightly/rustc/platform-support/win7-windows-msvc.html says 

> Host tools may also work, though those are not currently tested.

implying they at least do exists. Sadly rustup seems to have no idea. I wish there wouldd be some --force option to force downloading such take-or-leave tools.
Maybe one day i would seriously read into https://rustc-dev-guide.rust-lang.org/building/how-to-build-and-run.html :-)

**Comment by the8472** [comment]
No, tier3 targets are not built. Which means even if they work you'd still have to build host tools yourself rather than downloading them

**Comment by the-Arioch** [comment]
>  to build host tools 

the jargon is a problem, surely all the hardcore devs know it already, those who do write the docs not read them :-)

when i googled it there was only references to "build rust server" instead

basically it would be nice if those references to "host tools" were linked to some easy to find and similarly named article that would explain the term, give the up to date and complete list of those tools and if possible build instructions.

**Comment by cher-nov** [comment]
FYI (To Whom It May Concern):
<sup>cc https://github.com/rust-lang/rust/issues/129610</sup>

With some trial and error, I've discovered that `nightly-2024-02-25` is the last nightly toolchain build that works on Windows 7. It's somewhat between the branching dates of [1.77](https://releases.rs/docs/1.77.0/), the last version line officially supporting Windows 7 as host platform, and the [1.78.0](https://releases.rs/docs/1.78.0/) release which [dropped the compatibility](https://blog.rust-lang.org/2024/05/02/Rust-1.78.0/#compatibility-notes) altogether.

Maybe this will help someone else who hasn't been able to update their build setup yet.
