### ISSUE TITLE
#[repr(align(NNN_NNN))] forces size_of to be same as alignment for structs smaller than that value

### ISSUE THREAD

**Issue by opedroso** [rust-lang/rust#125115]
I tried this code:

```rust
#![allow(dead_code)]

#[repr(align(65_536))] // 64Kib alignment should not imply 64 Kib size
struct MemoryArena {
    memory: std::cell::UnsafeCell<[u8; 32_000]>,
}

#[repr(align(65_536))] // 64Kib alignment does not imply 64 Kib size if struct actually larger than 64 KiB
struct MemoryArena2 {
    memory1: std::cell::UnsafeCell<[u8; 32_000]>,
    memory2: std::cell::UnsafeCell<[u8; 32_000]>,
    memory3: std::cell::UnsafeCell<[u8; 32_000]>,
}
fn main() {
    // since  MemoryArena has only an array of 32Kib, that is the expected sizeof it
    let expected_size_of_memoryarena = std::mem::size_of::<std::cell::UnsafeCell<[u8; 32_000]>>();
    assert_eq!(expected_size_of_memoryarena, std::mem::size_of::<MemoryArena>(),
    "MemoryArena has only an array of 32Kib, so that is it's expected size");
    
    // alignment does not imply size if contents larger than alignment
    let expected_size_of_memoryarena2 = 3 * std::mem::size_of::<std::cell::UnsafeCell<[u8; 32_000]>>();
    assert_eq!(expected_size_of_memoryarena2, std::mem::size_of::<MemoryArena2>());
}
```

I expected to see this happen: *the alignment requirement of a struct should have no influence on its size*

Instead, this happened: *If struct being applied alignment requirement is smaller than alignment value, size_of(struct ...) returns the alignment value if and only if, the actual size of the struct is smaller than alignment; otherwise, behavior is correct*

### Meta

`rustc --version --verbose`:
```
rustc 1.78.0 (9b00956e5 2024-04-29)
binary: rustc
commit-hash: 9b00956e56009bab2aa15d7bff10916599e3d6d6
commit-date: 2024-04-29
host: x86_64-pc-windows-msvc
release: 1.78.0
LLVM version: 18.1.2

rustc +nightly --version --verbose
rustc 1.80.0-nightly (ab14f944a 2024-05-13)
binary: rustc
commit-hash: ab14f944afe4234db378ced3801e637eae6c0f30
commit-date: 2024-05-13
host: x86_64-pc-windows-msvc
release: 1.80.0-nightly
LLVM version: 18.1.4
```

<details><summary>No backtrace generated</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by tbu-** [comment]
I think this is expected behavior. E.g. `Vec<T>` or slices `&[T]` assume that elements are `mem::size_of<T>()` bytes apart. If the size wasn't changed for the struct, this couldn't be guaranteed.

See also
```rs
struct A {
    x: u64,
    y: u8,
}
```

This has size 8, even though it wouldn't need to have that just for the alignment. Size is rounded up to the next multiple of the alignment.

**Comment by zakarumych** [comment]
But why though?
What's the reason to always have tail padding?

For example in this case

```rust
#[repr(C)]
struct A {
  x: u64,
  y: u8,
}

#[repr(C)]
struct B {
  a: A,
  b: u8,
}
```

the `b` field would be placed at `16` offset, while it could be at `9`.
But in Rust `A` size is `16` due to tail padding.

**Comment by hanna-kruppe** [comment]
See https://lang-team.rust-lang.org/frequently-requested-changes.html#size--stride

**Comment by zakarumych** [comment]
So, TL;DR; is "legacy stuff"

**Comment by saethlin** [comment]
Summarizing it that way suggests we would make a different decision if we could go back in time. I am not sure we would.

**Comment by zakarumych** [comment]
No, could make different decision back then, but not anymore.
