### ISSUE TITLE
Tracking Issue for `push_str` returning `self`

### ISSUE THREAD

**Issue by hamirmahal** [rust-lang/rust#125264]
Feature gate: `#![feature(push_str_returns_self)]`

This is a tracking issue for `push_str` returning `self`.

### Public API

```rust
  pub fn push_str(&mut self, string: &str) -> &mut Self {
      self.vec.extend_from_slice(string.as_bytes());
      self
  }
```

### Steps / History

- [x] Implementation: #125265
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by hamirmahal** [comment]
# Motivation

This change would clean up functions like this.

## Without this change

```rust
fn foo(mut s: String, domain: &str) -> String {
    s = s.trim().to_string();
    s.push('@');
    s.push_str(domain);
    s
}
```

## With this change

```rust
fn foo(mut s: String, domain: &str) -> String {
    s = s.trim().to_string();
    s.push('@');
    s.push_str(domain)
}
```

**Comment by hamirmahal** [comment]
# Drawbacks

If `push_str` returns `self`, now, it'll be more difficult to change it to something else, later, like `self.len()`.

Although I will say that returning `self.len()` is worse than returning `self`, since it's trivial to get `self.len()` given `self`, but not the other way around.

**Comment by dtolnay** [comment]
Normally a tracking issue is not required for "instantly stable" changes i.e. standard library changes which do not require the user to enable a particular `#![feature(...)]` in order to use. `push_str` is not behind such a feature gate.
