### ISSUE TITLE
Empty where clauses don't have an unused warning

### ISSUE THREAD

**Issue by dev-ardi** [rust-lang/rust#125242]
```rs
fn foo() where {}
```

**Comment by mu001999** [comment]
By using rustfmt, we can get `fn foo() {}` after formatting. I think we don't need to warn more.

**Comment by dev-ardi** [comment]
Not when there's a return type: `fn foo() -> () where {}`

**Comment by mu001999** [comment]
@dev-ardi seems what we should do is to improve rustfmt, right?

**Comment by workingjubilee** [comment]
It seems this was wontfixed in #125277, so I think we can close this for now! Feel free to open issues with clippy/rustfmt/tell me I'm wrong and reopen it.
