### ISSUE TITLE
async closure syntax causes compiler error in disabled code block

### ISSUE THREAD

**Issue by conradludgate** [rust-lang/rust#125366]
I tried this code:

```rust
#[cfg_attr(feature = "foobar", features(async_fn_traits))]

#[cfg(feature = "foobar")]
fn test() {
    let x = async || {};
}
```

I expected to see this happen: program compiles on stable when "foobar" feature is not set.

Instead, this happened:

```
error[E0658]: async closures are unstable
 --> src/lib.rs:5:13
  |
5 |     let x = async || {};
  |             ^^^^^
  |
  = note: see issue #62290 <https://github.com/rust-lang/rust/issues/62290> for more information
  = help: to use an async block, remove the `||`: `async {`
```

### Meta

`rustc --version --verbose`:
```
rustc 1.78.0 (9b00956e5 2024-04-29)
binary: rustc
commit-hash: 9b00956e56009bab2aa15d7bff10916599e3d6d6
commit-date: 2024-04-29
host: aarch64-apple-darwin
release: 1.78.0
LLVM version: 18.1.2
```

**Comment by fmease** [comment]
This works as intended. Feature gates for experimental syntax extensions are intentionally run before macro expansion to prevent stable code from relying on it. We promise not to break stable code (with some exceptions ofc). Permitting experimental syntax in “`cfg`'ed out” code would hinder us to adjust or remove the syntax as stable crates could now fail with syntax errors.

**Comment by fmease** [comment]
We have some syntax extensions which still have post-expansion feature gates (which used to be default in the past iirc) like `auto_traits`. Due to the aforementioned reasons, we can't change the syntax of auto traits anymore (not easily at least).

**Comment by conradludgate** [comment]
Right. Makes sense. Found a workaround using declarative macros since they skip the parser during this phase.

Thanks!
