### ISSUE TITLE
The unexpected slowness of `core::ptr::copy` when buffer size approaches 4096

### ISSUE THREAD

**Issue by StevenJiang1110** [rust-lang/rust#125352]
These days when we test the efficiency of `core::ptr::copy` (together with `core::ptr::copy_nonoverlapping`), we witness an unexpected slowness when the buffer size approached 4096, compared with the assembly implementation with [`resp movsb`](https://www.felixcloutier.com/x86/movs:movsb:movsw:movsd:movsq) instruction (we name it as `fast_copy`). I am wondering whether the core library should provide a more efficient implememtation for `core::ptr::copy`.

```rust
pub unsafe fn fast_copy(src: *const u8, dst: *mut u8, count: usize) {
    core::arch::asm!(
        "push rcx",
        "push rsi",
        "push rdi",
        "rep movsb",
        "pop rdi",
        "pop rsi",
        "pop rcx",
        in("rcx") count,
        in("rsi") src,
        in("rdi") dst,
    );
}
```

Below are the results.

**BUFFER SIZE FROM 16 to 8192, STEP_SIZE=16**:

<img width="1016" alt="截屏2024-05-17 15 52 32" src="https://github.com/rust-lang/rust/assets/27764680/81689939-caff-4cbd-83f9-c58072eb2eea">

The red points represent the results of `ptr::copy_overlapping`, the green points represent the results of `ptr::copy`, and the blue points represent the results of `fast_copy`. As the results of `ptr::copy_overlapping` and `ptr::copy` are nearly identical, the red and green points overlap. The X-axis represents the size of the buffer, while the Y-axis represents the time taken for the copy operation.

The results are rather surprising. There is an abnormal spike when the buffer size is around 4096 for all three versions.

For buffer sizes smaller than approximately 2000, the `ptr::copy` function performs faster than `fast_copy`. But for buffer sizes below 64,  three versions seem to have the similar performance.

As the buffer size approaches 4096 but does not exceed it, `fast_copy` becomes faster than `ptr::copy`. 

For buffer sizes exceeding 4096, `fast_copy` and `ptr::copy` show similar performance.

Here is a closer look at the spike around 4096. The time taken for the copy operation is closely correlated with the buffer size.

<img width="1130" alt="截屏2024-05-17 16 13 27" src="https://github.com/rust-lang/rust/assets/27764680/6a378712-ed46-4307-9f94-c1c4da171841">

**Comment by StevenJiang1110** [comment]
Below are the code to replat the results. It is built with release mode and LTO enabled. No specific efforts were made to optimize the code size.

```rust
use core::hint::black_box;
use std::time::Instant;

use plotlib::{
    page::Page,
    repr::Plot,
    style::{PointMarker, PointStyle},
    view::ContinuousView,
};

pub unsafe fn fast_copy(src: *const u8, dst: *mut u8, count: usize) {
    core::arch::asm!(
        "push rcx",
        "push rsi",
        "push rdi",
        "rep movsb",
        "pop rdi",
        "pop rsi",
        "pop rcx",
        in("rcx") count,
        in("rsi") src,
        in("rdi") dst,
    );
}

const NUM: u64 = 100_0000;

const INIT_SIZE: usize = 16;
const MAX_SIZE: usize = 8192;
const STEP_SIZE: usize = 16;

fn main() {
    let mut res_nonoverlap = Vec::with_capacity(MAX_SIZE / STEP_SIZE);
    let mut res_copy = Vec::with_capacity(MAX_SIZE / STEP_SIZE);
    let mut res_fast_copy = Vec::with_capacity(MAX_SIZE / STEP_SIZE);

    for size in (INIT_SIZE..MAX_SIZE).step_by(STEP_SIZE) {
        let src = vec![127u8; size];
        let mut dst = vec![254u8; size];

        black_box(unsafe { core::ptr::copy_nonoverlapping(src.as_ptr(), dst.as_mut_ptr(), size) });

        // test ptr::copy_nonoverlapping

        let now = Instant::now();
        for _ in 0..NUM {
            black_box(unsafe {
                core::ptr::copy_nonoverlapping(src.as_ptr(), dst.as_mut_ptr(), size)
            });
        }
        let duration1 = now.elapsed();
        res_nonoverlap.push((size, duration1.as_nanos()));

        // test ptr::copy

        let now = Instant::now();
        for _ in 0..NUM {
            black_box(unsafe { core::ptr::copy(src.as_ptr(), dst.as_mut_ptr(), size) });
        }
        let duration2 = now.elapsed();
        res_copy.push((size, duration2.as_nanos()));

        // test fast_copy

        let now = Instant::now();
        for _ in 0..NUM {
            black_box(unsafe { fast_copy(src.as_ptr(), dst.as_mut_ptr(), size) });
        }
        let duration3 = now.elapsed();
        res_fast_copy.push((size, duration3.as_nanos()));

        println!(
            "size = {}, nonoverlap = {:?}, ptr::copy = {:?}, fast copy = {:?}",
            size, duration1, duration2, duration3
        );
    }

    draw_slot(res_nonoverlap, res_copy, res_fast_copy)
}

fn draw_slot(
    res_nonoverlap: Vec<(usize, u128)>,
    res_copy: Vec<(usize, u128)>,
    res_fast_copy: Vec<(usize, u128)>,
) {
    let y_min1 = res_nonoverlap.iter().map(|(_, y0)| *y0).min().unwrap();
    let y_max1 = res_nonoverlap.iter().map(|(_, y0)| *y0).max().unwrap();

    let y_min2 = res_copy.iter().map(|(_, y0)| *y0).min().unwrap();
    let y_max2 = res_copy.iter().map(|(_, y0)| *y0).max().unwrap();

    let y_min3 = res_fast_copy.iter().map(|(_, y0)| *y0).min().unwrap();
    let y_max3 = res_fast_copy.iter().map(|(_, y0)| *y0).max().unwrap();

    let y_min = y_min1.min(y_min2).min(y_min3);
    let y_max = y_max1.max(y_max2).max(y_max3);

    let res_nonoverlap = res_nonoverlap
        .iter()
        .map(|(x0, y0)| (*x0 as f64, *y0 as f64))
        .collect();
    let s1: Plot = Plot::new(res_nonoverlap).point_style(
        PointStyle::new()
            .marker(PointMarker::Square) 
            .colour("#FF0000")
            .size(2.0), // red
    );

    let res_copy = res_copy
        .iter()
        .map(|(x0, y0)| (*x0 as f64, *y0 as f64))
        .collect();
    let s2: Plot = Plot::new(res_copy).point_style(
        PointStyle::new()
            .marker(PointMarker::Circle) 
            .colour("#00FF00")
            .size(2.0), // green
    );

    let res_fast_copy = res_fast_copy
        .iter()
        .map(|(x0, y0)| (*x0 as f64, *y0 as f64))
        .collect();
    let s3: Plot = Plot::new(res_fast_copy).point_style(
        PointStyle::new()
            .marker(PointMarker::Circle) 
            .colour("#0000FF")
            .size(2.0), // blue
    );

    let v = ContinuousView::new()
        .add(s1)
        .add(s2)
        .add(s3)
        .x_range((INIT_SIZE - STEP_SIZE) as f64, (MAX_SIZE + 1) as f64)
        .y_range((y_min - 1) as f64, (y_max + 1) as f64)
        .x_label("the size of vector")
        .y_label("the copy time(ns)");

    Page::single(&v).save("scatter.svg").unwrap()
}
```

**Comment by jhorstmann** [comment]
LLVM has a [threshold after which its memcpy implementation switches to using `rep movsb`](https://github.com/llvm/llvm-project/blob/main/libc/src/string/memory_utils/x86_64/inline_memcpy.h#L218), but I'm not sure how this can be configured. Possibly only during llvm build time.

There is also an llvm codegen option, which can be added to `RUSTFLAGS`, that would replace all memcpy calls with inline code: `-Cllvm-args=-x86-use-fsrm-for-memcpy`. Since this avoids function call overhead it might be beneficial even for smaller copy sizes, but in my testing I did not notice any significant performance improvements by using it.

**Comment by workingjubilee** [comment]
My understanding of the semantics of `rep movsb` is that it is not a valid implementation of `ptr::copy`, only `ptr::copy_nonoverlapping`.

I suspect that LLVM has noticed the relative independence of the allocations and reasoned from there to upgrading the `ptr::copy` to `ptr::copy_nonoverlapping`.

**Comment by workingjubilee** [comment]
There does indeed seem to be something special about the number 4096! :monocle_face: For some reason aligning the allocations to 4096 makes all the benchmark differences whatsoever essentially completely disappear. I wonder why that might be?

```diff
diff --git a/src/main.rs b/src/main.rs
index 4841dd4..25a1bfe 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -25,9 +25,14 @@ pub unsafe fn fast_copy(src: *const u8, dst: *mut u8, count: usize) {
 
 const NUM: u64 = 100_0000;
 
-const INIT_SIZE: usize = 16;
-const MAX_SIZE: usize = 8192;
-const STEP_SIZE: usize = 16;
+const INIT_SIZE: usize = 1;
+const MAX_SIZE: usize = 64;
+const STEP_SIZE: usize = 1;
+
+const SCALING_FACTOR: usize = 4096;
+#[repr(align(4096))]
+#[derive(Copy, Clone)]
+struct HighAlignment([u8; SCALING_FACTOR]);
 
 fn main() {
     let mut res_nonoverlap = Vec::with_capacity(MAX_SIZE / STEP_SIZE);
@@ -35,8 +40,8 @@ fn main() {
     let mut res_fast_copy = Vec::with_capacity(MAX_SIZE / STEP_SIZE);
 
     for size in (INIT_SIZE..MAX_SIZE).step_by(STEP_SIZE) {
-        let src = vec![127u8; size];
-        let mut dst = vec![254u8; size];
+        let src = vec![HighAlignment([127u8; SCALING_FACTOR]); size];
+        let mut dst = vec![HighAlignment([254u8; SCALING_FACTOR]); size];
 
         black_box(unsafe { core::ptr::copy_nonoverlapping(src.as_ptr(), dst.as_mut_ptr(), size) });
 
@@ -64,7 +69,13 @@ fn main() {
 
         let now = Instant::now();
         for _ in 0..NUM {
-            black_box(unsafe { fast_copy(src.as_ptr(), dst.as_mut_ptr(), size) });
+            black_box(unsafe {
+                fast_copy(
+                    src.as_ptr().cast(),
+                    dst.as_mut_ptr().cast(),
+                    size * SCALING_FACTOR,
+                )
+            });
         }
         let duration3 = now.elapsed();
         res_fast_copy.push((size, duration3.as_nanos()));
```

![perfectly balanced, as all things should be](https://github.com/rust-lang/rust/assets/46493976/fd4c9e71-fd54-42d0-9adb-89a306be5955)

**Comment by the8472** [comment]
meanwhile [at AMD](https://sourceware.org/bugzilla/show_bug.cgi?id=30994)

```
size = 4064, nonoverlap = 32.791194ms, ptr::copy = 32.802577ms, fast copy = 46.480048ms
size = 4080, nonoverlap = 33.257445ms, ptr::copy = 33.253806ms, fast copy = 51.594945ms
size = 4096, nonoverlap = 33.138887ms, ptr::copy = 33.117537ms, fast copy = 1.013281281s
size = 4112, nonoverlap = 32.714889ms, ptr::copy = 32.745887ms, fast copy = 51.842878ms
size = 4128, nonoverlap = 32.954556ms, ptr::copy = 33.028588ms, fast copy = 47.028024ms
```

![scatter](https://github.com/rust-lang/rust/assets/1065730/5f75b9a6-eba5-483a-a19e-abe066d06805)

**Comment by workingjubilee** [comment]
In any case, @StevenJiang1110: to be less flippant, what you observe is essentially a feature of the `memcpy` implementation on your computer, that is probably designed to strike a balance of performance characteristics across many CPUs, happening to make a bad decision for the specific machine you were using for testing for things that are not-quite-4096 bytes. It is very hard to make a good decision, however, because of [memory pages](https://en.wikipedia.org/wiki/Page_(computer_memory)) meaning that, without alignment, a fair number of writes are likely to be on a memory page boundary.

I don't think we can do much about this.
