### ISSUE TITLE
Better error message for wrong use of modules

### ISSUE THREAD

**Issue by Valloric** [rust-lang/rust#12531]
In `test.rs`:

``` rust
mod submod;

fn main() {
  println!("{:?}", submod::foo());
}
```

In `submod.rs`:

``` rust
mod submod {
  pub fn foo() {
    ~"foo!"
  }
}
```

Running `rustc -o test test.rs` results in: 

```
test.rs:4:20: 4:31 error: unresolved name `submod::foo`.
test.rs:4   println!("{:?}", submod::foo());
                             ^~~~~~~~~~~
note: in expansion of format_args!
<std macros>:2:23: 2:77 note: expansion site
<std macros>:1:1: 1:1 note: in expansion of println!
test.rs:4:3: 4:35 note: expansion site
error: aborting due to previous error
```

Now, I know what the issue is: there's no need to wrap the contents of `submod.rs` with `mod submod {...}`, but as a Rust newbie I didn't know that and it took me a while to figure it out (and I've read the entire official tutorial and the whole manual). The error message did nothing to help me; something like  `did you mean submod::submod::foo?` (à la Clang) would have pointed me in the right direction. It would be even better if the note had something more specific to this (I'd presume) common newbie mistake of misunderstanding that a file is also implicitly a module from the perspective of other files.

Also, the official tutorial _really_ didn't help out either; it led me astray with the very first sentence from the "Files and Modules" section: 

> One important aspect of Rust's module system is that source files and modules are not the same thing.

It made me think the exact opposite ("I have to put the file's contents inside a `mod <name> {}` block.") of how Rust actually works ("Contents of `foo.rs` are inside `mod foo` from the perspective of other files.").

All of this looks trivial and obvious in retrospect, but didn't at first. We should look into removing barriers to entry for people new to Rust, and a better error message for something like this should reduce the time spent scratching one's head.

This is all using the latest Rust nightly.

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by estebank** [comment]
[Current output](https://is.gd/QlvWLi):

```
error[E0425]: cannot find function `foo` in module `submod`
 --> <anon>:8:3
  |
8 |   submod::foo();
  |   ^^^^^^^^^^^ not found in `submod`
  |
  = help: possible candidate is found in another module, you can import it into scope:
  = help:   `use submod::submod::foo;`
```

**Comment by Mark-Simulacrum** [comment]
I believe that the current output (as per the previous comment) in mentioning `submod::submod` makes this bug basically fixed; closing.
