### ISSUE TITLE
Clean out old msys2/mingw stuff in CI

### ISSUE THREAD

**Issue by workingjubilee** [rust-lang/rust#125583]
Recently we had increasing network failures due to redownloading mingw tools. The first few times this fell to the usual "retry it again", but that's really not a great solution as we were losing quite a few half-finished runs for essentially no reason. An attempt to fix it caused some struggle with rollups due to the first try at a patch not quite panning out. In other words, we could use some more attention to the windows-gnu CI setup.

Per @mati865 in https://github.com/rust-lang/rust/pull/125546#discussion_r1615213867 we have shell scripts that we run in our CI that has somewhat arcane names, as it discusses old tools we don't actually use.

@ChrisDenton intends to follow up but given all the above-mentioned network failures I wanted to make sure there was an issue for this.

[Chris thinks this was enabled](https://github.com/rust-lang/rust/pull/125546#issuecomment-2132178669) by https://github.com/rust-lang/rust/issues/121876 in part. Thanks @jieyouxu and @Oneirical!

**Comment by mati865** [comment]
> [Chris thinks this was enabled](https://github.com/rust-lang/rust/pull/125546#issuecomment-2132178669) by #121876 in part. Thanks @jieyouxu and @Oneirical!

I don't think this was the case since there are still many tests that are not ported like for an example run-make-fulldeps. Maybe GHA now include `make` on Windows by the default (or by an accident)?

Guess we'll find out soon.

**Comment by jieyouxu** [comment]
I don't know if run-make (and rmake-fulldeps) tests depend on msys2, especially as mentioned not all tests have been ported. `make` is still definitely a dependency.

**Comment by ChrisDenton** [comment]
To be clear, my hypothesis is that at least some run-make tests assumed the existence of many gnu-ish tools so the switch to recipes (even if not complete) has greatly reduced the things that need to be assumed.

**Comment by ChrisDenton** [comment]
An alternative explanation is that the comment in the file was just always wrong ;)

**Comment by ChrisDenton** [comment]
> Recently we had increasing network failures due to redownloading mingw tools

Note that this has been randomly failing for months now, basically since it was introduced. The only difference here was it failing a number of times in succession. Which might have just been a random coincidence or might not have been.

> An attempt to fix it caused some struggle with rollups due to the first try at a patch not quite panning out. In other words, we could use some more attention to the windows-gnu CI setup.

The attempt failed because I forgot to test windows-msvc. The windows-gnu part worked fine.

**Comment by workingjubilee** [comment]
> Note that this has been randomly failing for months now, basically since it was introduced.

oh lol I didn't notice.

**Comment by mati865** [comment]
> To be clear, my hypothesis is that at least some run-make tests assumed the existence of many gnu-ish tools so the switch to recipes (even if not complete) has greatly reduced the things that need to be assumed.

They always required make provided by MSYS2 and still do (albeit something else seems to provide it now). In the past they also used to depend on toolchain specific tools like nm, objdump but those were provided by the toolchain and later migrated to LLVM tools that Rust always builds anyway.

So while porting of run-make tests to Rust is fantastic it doesn't impact removal of MSYS2. If you want to know what allowed the removal you can run `which make.exe` on CI.

**Comment by ChrisDenton** [comment]
I'm not at all doubting the `make` part is still needed.

**Comment by workingjubilee** [comment]
was just trying to throw out a kudos, didn't mean to start an argument. :ferrisCluelesser:

**Comment by jieyouxu** [comment]
I [opened](https://github.com/rust-lang/rust/issues/125585) an issue to remind us that we should *eventually* document all assumed external dependecies for the test suite.

**Comment by workingjubilee** [comment]
Fixed by https://github.com/rust-lang/rust/pull/125590

**Comment by ChrisDenton** [comment]
Oh right, forgot to link them.
