### ISSUE TITLE
error: --remap-path-prefix must contain '=' between FROM and TO because path contains spaces

### ISSUE THREAD

**Issue by stereomato** [rust-lang/rust#125594]
```
Caused by:
  process didn't exit successfully: `/home/stereomato/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc - --crate-name ___ --print=file-names -Cforce-frame-pointers=yes -C target-cpu=native -C debuginfo=2 --remap-path-prefix=/home/stereomato/Documents/Software Development/Repositories/AUR/paru/src=/usr/src/debug/paru --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 1)
  --- stderr
  error: --remap-path-prefix must contain '=' between FROM and TO

```

**Comment by bjorn3** [comment]
Are you using `RUSTFLAGS` to set `--remap-path-prefix`? If so, you are actually passing two separate args `--remap-path-prefix=/home/stereomato/Documents/Software` and `Development/Repositories/AUR/paru/src=/usr/src/debug/paru` as `RUSTFLAGS` splits on whitespace. Try using `CARGO_ENCODED_RUSTFLAGS` instead which instead splits the arguments by the 0x1f (ASCII Unit Separator) character.

**Comment by bjorn3** [comment]
The package you are trying to build may be setting RUSTFLAGS to pass `--remap-path-prefix. Which package did you try to build?

**Comment by stereomato** [comment]
https://github.com/Morganamilo/paru

**Comment by bjorn3** [comment]
Looks like it originates from https://gitlab.archlinux.org/pacman/pacman/-/blob/d55b47e5512808b67bc944feb20c2bcc6c1a4c45/scripts/libmakepkg/buildenv/rust.sh.in#L34, which indeed doesn't handle spaces inside the source path. Disabling the "debug" option may help. I have no clue how to though. Never used makepkg myself.

**Comment by stereomato** [comment]
wow, how did you even find that? :thinking: I guess suggesting the change you mentioned would be a good idea right?

**Comment by bjorn3** [comment]
> wow, how did you even find that?

Once you mentioned that the error happened while compiling paru (I originally assumed that you were using paru to build something else and hit an error there), I saw the installation instructions mention makepkg. I then went to the pacman repo (which contains makepkg) and searched around a bit until searching for the literal string `remap-path-prefix` got a match at the linked location.
