### ISSUE TITLE
LazyCell, LazyLock are missing some big-picture documentation

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#125615]
These types are [stable](https://github.com/rust-lang/rust/pull/121377) now, however, the docs don't properly mention them everywhere yet:
- https://doc.rust-lang.org/nightly/std/cell/index.html lists OnceCell in the overview, but not LazyCell. The docs should also explain when I should use which of these types, as they are superficially pretty similar.
- https://doc.rust-lang.org/nightly/std/sync/index.html#higher-level-synchronization-objects lists Once and OnceLock, but not LazyLock. The same point about "when to use which type" applies. (It seems like `Once` is basically the same as `OnceLock<()>`, but I am not sure.)

Cc @rust-lang/libs-api

**Comment by RalfJung** [comment]
@workingjubilee thatnks for the PR!
The question of Once vs OnceLock seems to remain unresolved though. If Once is to OnceLock what `Mutex<()>` is to Mutex, then it should probably be considered extremely niche as one can't even safely protect any data that way?

**Comment by workingjubilee** [comment]
Yeah, I do indeed have nothing useful to say about Once, basically, because it doesn't seem very useful except as a raw implementation primitive of OnceLock. I suppose we could add a comment that soft-discourages it?

**Comment by RalfJung** [comment]
Yeah I think that would be useful.
