### ISSUE TITLE
Audit usage of `command_output` methods in rmake.rs tests

### ISSUE THREAD

**Issue by jieyouxu** [rust-lang/rust#125617]
They are typically not the semantics that's desired, i.e. they **only** provide the command output but does not assert that the command status is success. We should make sure we're not silently letting failed commands through.

Do we even want to allow `command_output` methods? It's likely less footgunny if we only provided `CommandWrapper::{run, run_fail, run_fail_assert_exit_code}` methods which perform asserts on the command exit status.

**Comment by Zalathar** [comment]
I found a case in #126231 where the existing script does want the command output, so that it can report multiple failures instead of stopping immediately on the first one.
