### ISSUE TITLE
core::slice::sort::partial_insertion_sort: Redundant call to insertion_sort_shift_right

### ISSUE THREAD

**Issue by hvenev-insait** [rust-lang/rust#125618]
In `partial_insertion_sort`, an invariant is maintained that `v[..i]` is sorted. When a non-sorted pair `v[i-1] > v[i]` is encountered, they are swapped and the last element of `v[..i]` is shifted to the left into its correct spot. Then for some reason `insertion_sort_shift_right` is called on `v[..i]`, attempting to shift `v[0]` to the right, which never does anything.

Before commit a3065a1a34fe1c0b85bdf3ff1f3d0bd470235e6b, the shift was happening on `v[i..]` (instead of `v[..i]`), attempting to shift `v[i]` to the right, which makes more sense.

**Comment by workingjubilee** [comment]
have you considered opening a PR?

**Comment by clubby789** [comment]
`partial_insertion_sort` and `insertion_sort_shift_right` don't exist any more, so  I'm going to close this - please reopen if this is issue is actually still around
