### ISSUE TITLE
Cannot write tests that need the csky backend

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#125697]
In `tests/ui/abi/compatibility.rs` we're trying to test the ABI adjustment logic of all targets. This generally works as the test is no_core and LLVM has backends for all targets available -- except it does not seem possible to test the csky target that way. Trying to add the usual `needs-llvm-components: csky` leads to an error from tidy:
```
/checkout/tests/ui/abi/compatibility.rs: revision csky specifies unknown LLVM component `csky`
```
The test passes just fine locally, so it seems like at least the downloaded LLVM has the `csky` component. I don't know why it was not added to tidy's `KNOWN_LLVM_COMPONENTS` list.

Cc @Dirreke

**Comment by workingjubilee** [comment]
cc @erikdesjardins but also I think this was just an oversight.

**Comment by RalfJung** [comment]
FWIW if one just adds this to a test it does pass on CI
```
//@revisions: csky
//@[csky] compile-flags: --target csky-unknown-linux-gnuabiv2
//@[csky] needs-llvm-components: csky
```
but of course it may just be silently ignored, hard to say whether the test actually runs... this `needs-llvm-components` stuff makes tests quite fragile. :/

**Comment by workingjubilee** [comment]
Yeah, the tidy check was added to reduce the fragility because a lot of people were giving names other than the LLVM component's name, like riscv64 instead of riscv, etc.

**Comment by RalfJung** [comment]
The remaining question then is, how sure are we that the components accepted by tidy are all available on *some* CI runner?

**Comment by RalfJung** [comment]
Also, something else must have been going on... I [disabled](https://github.com/rust-lang/rust/commit/cfb47ca5df93c82983563fa37673f7108eb94df4) this test before that sanity check was added to tidy.

Sadly the logs for [this](https://github.com/rust-lang/rust/pull/117500#issuecomment-1817776364) failure are already gone.
