### ISSUE TITLE
Unexpected float value when casted from `f32` to `f64`

### ISSUE THREAD

**Issue by comphead** [rust-lang/rust#125777]
I tried this code:

```rust
    println!("value_64: {:?}", 128.2_f32 as f64);
```

I expected to see this happen: *value_64: 128.2*

Instead, this happened: *value_64: 128.1999969482422*

### Meta

`rustc --version --verbose`:
```
Tested on 1.78 Stable, but can see this also on 1.80 nightly. Not sure about earlier versions
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by saethlin** [comment]
This is not a bug. You can see the same behavior with slightly different rounding from C:
```c
#include <stdio.h>
int main() {
    float f = 128.2;
    printf("%f\n", (double)f);
    return 0;
}
```
will print
```
128.199997
```
The lossy step is the conversion of 128.2 from base 10 to base 2. The base-2 representation has the equivalent of a repeating decimal.

**Comment by the8472** [comment]
If only we had hex and binary formatting for floats.

**Comment by saethlin** [comment]
You have the power 💪
