### ISSUE TITLE
rust stable 1.78 using 'x86_64-pc-windows-gnu' host tool to build 'thumbv7em-none-eabihf' arm bare metal target got rust-lld failed

### ISSUE THREAD

**Issue by pbl-pw** [rust-lang/rust#125809]
Failed reason is can't find 'libgcc_s_seh-1.dll' and 'libwinpthread-1.dll'
when fallback to 1.77.2 or using 'x86_64-pc-windows-msvc' host tool then every thing is ok

**Comment by mati865** [comment]
Those libraries are provided alongside other Rust binaries:
```
$ ls ~/.rustup/toolchains/stable-x86_64-pc-windows-gnu/bin/
cargo.exe*         cargo-fmt.exe*      libgcc_s_seh-1.dll*   rustc.exe*                          rustdoc.exe*  rust-gdb*     rust-lldb*
cargo-clippy.exe*  clippy-driver.exe*  libwinpthread-1.dll*  rustc_driver-35a7c4c28db0aaf0.dll*  rustfmt.exe*  rust-gdbgui*  std-a1f74822451877d1.dll*
```
Note `rust-lld` is located inside rustlib:
```
$ file ~/.rustup/toolchains/stable-x86_64-pc-windows-gnu/lib/rustlib/x86_64-pc-windows-gnu/bin/rust-lld.exe
/c/Users/mateusz/.rustup/toolchains/stable-x86_64-pc-windows-gnu/lib/rustlib/x86_64-pc-windows-gnu/bin/rust-lld.exe: PE32+ executable (console) x86-64, for MS Windows, 17 sections
```
I rust-lld should be called with PATH set to `~/.rustup/toolchains/stable-x86_64-pc-windows-gnu/bin/`, or at least used to be. Do you have an example that reproduces the problem? Hopefully, we can bisect it to easily find the problem.

**Comment by pbl-pw** [comment]
I have tested using clean rust host toolchain installed by rustinit, and just build [cortex-m-quickstart](https://github.com/rust-embedded/cortex-m-quickstart/commit/cf52e9e29e7ae49de4ac69867acb337f536a2801), then  it reproduce the problem.
note: Cargo.toml in [cortex-m-quickstart](https://github.com/rust-embedded/cortex-m-quickstart/commit/cf52e9e29e7ae49de4ac69867acb337f536a2801) need change 'package.name' and 'bin.name' before build, because they have '{{' and '}}'

**Comment by mati865** [comment]
searched nightlies: from nightly-2024-02-01 to nightly-2024-03-16
regressed nightly: nightly-2024-02-22
searched commit range: https://github.com/rust-lang/rust/compare/bb594538fc6e84213a6b8d5e165442570aa48923...3406ada96f8e16e49e947a91db3eba0db45245fa
regressed commit: https://github.com/rust-lang/rust/commit/0987e41d1ccbae7a8a55fdcde4af0ea76ebfe2d3

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.8</summary>


Host triple: x86_64-pc-windows-gnu
Reproduce with:
```bash
cargo bisect-rustc --start=1.77.0 --end=1.78.0 --target thumbv7m-none-eabi --prompt -c rust-mingw --preserve --script C:/Program Files/Git/usr/bin/bash.exe -- ./test.sh
```
</details>

Won't be as easy to debug as I hoped.
@weihanglo do you have any idea which change could case it?

**Comment by weihanglo** [comment]
If I understand correctly, when `~/.rustup/toolchains/stable-x86_64-pc-windows-gnu/bin/` is in `PATH` on Windows, it makes no difference. What the removed code path did was adding that to `PATH`. In [rustup 1.27.1](https://github.com/rust-lang/rustup/blob/stable/CHANGELOG.md#1271---2024-04-14), `RUSTUP_WINDOWS_PATH_ADD_BIN` was changed to false by default (https://github.com/rust-lang/rustup/pull/3703), so probably the rustup change is related.
 
@mati865 is it possible for you to add `RUSTUP_WINDOWS_PATH_ADD_BIN=true` and check it again?
I don't have a Windows machine available at hand :(

Also, could you check if rustc appends host tool bin to `PATH`? It [looks like it](https://github.com/rust-lang/rust/blob/a330e49593ee890f9197727a3a558b6e6b37f843/compiler/rustc_session/src/session.rs#L460-L475) but I don't particularly sure.

**Comment by weihanglo** [comment]
Would you mind sharing the output of `rustup --version` that shows the version of rustup you are using, @pbl-pw?

**Comment by mati865** [comment]
Thought it might be important to add; all my tests were made with only `~/.cargo/bin` present in PATH:
```
$ echo $PATH
/c/Users/mateusz/.cargo/bin
```

> If I understand correctly, when `~/.rustup/toolchains/stable-x86_64-pc-windows-gnu/bin/` is in `PATH` on Windows, it makes no difference.

Yes, but apparently it's not in `PATH` when tools from `~/.rustup/toolchains/stable-x86_64-pc-windows-gnu/lib/rustlib/x86_64-pc-windows-gnu/bin` are called. `$ PATH=$PATH:~/.rustup/toolchains/stable-x86_64-pc-windows-gnu/bin cargo +stable b` works fine so that sort of confirms it.

> In [rustup 1.27.1](https://github.com/rust-lang/rustup/blob/stable/CHANGELOG.md?rgh-link-date=2024-06-05T20%3A26%3A38Z#1271---2024-04-14), `RUSTUP_WINDOWS_PATH_ADD_BIN` was changed to false by default ([rust-lang/rustup#3703](https://github.com/rust-lang/rustup/pull/3703)), so probably the rustup change is related.
> 
> @mati865 is it possible for you to add `RUSTUP_WINDOWS_PATH_ADD_BIN=true` and check it again? I don't have a Windows machine available at hand :(

Adding that env makes no difference:
```
$ rustup -V
rustup 1.27.1 (54dd3d00f 2024-04-24)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.80.0-nightly (a330e4959 2024-06-04)`

$ RUSTUP_WINDOWS_PATH_ADD_BIN=true cargo +stable b
...
error: linking with `rust-lld` failed: exit code: 0xc0000135
```

> Also, could you check if rustc appends host tool bin to `PATH`? It [looks like it](https://github.com/rust-lang/rust/blob/a330e49593ee890f9197727a3a558b6e6b37f843/compiler/rustc_session/src/session.rs#L460-L475) but I am not particularly sure.

I can do some builds during the weekend.

> Also, could you check if rustc appends host tool bin to `PATH`? It [looks like it](https://github.com/rust-lang/rust/blob/a330e49593ee890f9197727a3a558b6e6b37f843/compiler/rustc_session/src/session.rs#L460-L475) but I am not particularly sure.

Judging from that code, it only adds `~/.rustup/toolchains/stable-x86_64-pc-windows-gnu/lib/rustlib/x86_64-pc-windows-gnu/bin`.

**Comment by weihanglo** [comment]
My fault. Should be `RUSTUP_WINDOWS_PATH_ADD_BIN=1` not `true`.

**Comment by mati865** [comment]
Oh, I had missed that too 😄 
`RUSTUP_WINDOWS_PATH_ADD_BIN=1 cargo +stable b` works fine.

**Comment by pbl-pw** [comment]
@weihanglo 
```
rustup --version
rustup 1.27.1 (54dd3d00f 2024-04-24)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.78.0 (9b00956e5 2024-04-29)`
```
I set RUSTUP_WINDOWS_PATH_ADD_BIN=1 then build works fine too

**Comment by pbl-pw** [comment]
@weihanglo 
```
rustup --version
rustup 1.27.1 (54dd3d00f 2024-04-24)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.78.0 (9b00956e5 2024-04-29)`
```
I set RUSTUP_WINDOWS_PATH_ADD_BIN=1 then build works fine too

**Comment by ChrisDenton** [comment]
Another option would be to add it to the end of `PATH`. So it has the lowest precedence but any necessary DLLs it provides can still be found.

**Comment by pbl-pw** [comment]
@weihanglo I guess msvc works because it's required dlls has been installed by Windows OS or MSVC build tool

**Comment by weihanglo** [comment]
@ChrisDenton are you talking about a fix in cargo or rustc?
What happens if we invoke rustc directly to cross-compile? If it also doesn't work, I feel like this should be addressed on rustc or linker invocation side.

**Comment by mati865** [comment]
Runtime libraries are located alongside rustc, so invoking it directly would work fine.
The same cannot be said about bins inside `~/.rustup/toolchains/stable-x86_64-pc-windows-gnu/lib/rustlib/x86_64-pc-windows-gnu/bin`, but is it even supported to - invoke them manually?

**Comment by ColinFinck** [comment]
I'm solving this now in my PR #128876 by shipping the required runtime DLLs along with `rust-lld.exe` too.
It must be possible to run `rust-lld.exe` without relying on any `PATH` variable being set. We already ship these runtime DLLs alongside `rustc.exe`, so doing the same for `rust-lld.exe` feels like a reasonable thing to do. This solution won't require `RUSTUP_WINDOWS_PATH_ADD_BIN` or any other modification to the `PATH` environment variable.
