### ISSUE TITLE
Bumping beta compiler can require nuking `build/` to unstuck `x`

### ISSUE THREAD

**Issue by jieyouxu** [rust-lang/rust#125804]
Hi, I've noticed that when the beta compiler is bumped, I can't run any `x` commands because build cache contains artifacts compiled by the previous beta compiler and thus `build_helper` (and anything that depends on it) fails to build.

```
gh-jieyouxu@dev-desktop-eu-1:~/rust$ ./x clean
Building bootstrap
   Compiling build_helper v0.1.0 (/home/gh-jieyouxu/rust/src/tools/build_helper)
error[E0514]: found crate `serde_derive` compiled by an incompatible version of rustc
 --> /home/gh-jieyouxu/rust/src/tools/build_helper/src/metrics.rs:1:5
  |
1 | use serde_derive::{Deserialize, Serialize};
  |     ^^^^^^^^^^^^
  |
  = note: the following crate versions were found:
          crate `serde_derive` compiled by rustc 1.79.0-beta.6 (66eb3e404 2024-05-23): /home/gh-jieyouxu/rust/build/bootstrap/debug/deps/libserde_derive-f63fc2b61cc4af2f.so
  = help: please recompile that crate using this compiler (rustc 1.79.0-beta.7 (d9e85b56e 2024-05-25)) (consider running `cargo clean` first)
```

It's easy to fix, I just `rm -rf build/`, but maybe we can automate invalidating the build cache if the beta compiler version that is used to build the build cache doesn't match with the beta compiler version that is used in the current `x` invocation?

**Comment by onur-ozkan** [comment]
Duplicated with https://github.com/rust-lang/rust/issues/125578

**Comment by jieyouxu** [comment]
Somehow I didn't find that, thanks!
