### ISSUE TITLE
Expand list of trait implementers in E0277 when calling `rustc` with `--verbose`

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#125984]
When emitting an error like the following

```
error[E0277]: the trait bound `MaybeMissing<std::string::String>: Reconcile` is not satisfied
   --> src/main.rs:3:19
    |
3   | #[derive(Hydrate, Reconcile)]
    |                   ^^^^^^^^^ the trait `Reconcile` is not implemented for `MaybeMissing<std::string::String>`, which is required by `&MaybeMissing<std::string::String>: Reconcile`
4   | struct S {
5   |     s: MaybeMissing<String>,
    |     - required by a bound introduced by this call
    |
    = help: the following other types implement trait `Reconcile`:
              bool
              i8
              i16
              i32
              i64
              u8
              u16
              u32
            and 17 others
    = note: required for `&MaybeMissing<std::string::String>` to implement `Reconcile`
note: required by a bound in `autosurgeon::reconcile::MapReconciler::put`
   --> /home/matt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/autosurgeon-0.8.3/src/reconcile.rs:114:15
    |
114 |     fn put<R: Reconcile, P: AsRef<str>>(&mut self, prop: P, value: R) -> Result<(), Self::Error>;
    |               ^^^^^^^^^ required by this bound in `MapReconciler::put`
```

Allow the `--verbose` flag (`self.tcx.sess.opts.verbose`) to print the whole list by modifying 

https://github.com/rust-lang/rust/blob/bc33782c23bc3e04eab7c85c43bbe1a108b11f80/compiler/rustc_trait_selection/src/traits/error_reporting/type_err_ctxt_ext.rs#L2075-L2085

There are other places where we limit output where we don't currently listen to this flag to expand the output. For type name shortening I believe we already do, but we should look for all of them and make the appropriate change for them too.

_Originally reported at https://users.rust-lang.org/t/how-can-i-get-a-list-of-the-and-17-others-types-in-this-compilation-error/112458_

**Comment by lengrongfu** [comment]
@estebank Hi, I am interested in this easy issue. Can I submit a PR to fix it?

**Comment by estebank** [comment]
@lengrongfu of course!

**Comment by lengrongfu** [comment]
@estebank Can you help me review this PR?
