### ISSUE TITLE
Tracking Issue for `const_binary_heap_new_in`

### ISSUE THREAD

**Issue by Coekjan** [rust-lang/rust#125961]
Feature gate: `#![feature(const_binary_heap_new_in)]`

This is a tracking issue for constification of `BinaryHeap::new_in`, which allows user to create a `BinaryHeap` in compile-time with a specific allocator.

**NOTE**: This feature depends on the unstable feature `allocator_api`

### Public API

```rust
impl<T: Ord, A: Allocator> BinaryHeap<T, A> {
    pub const fn new_in(alloc: A) -> BinaryHeap<T, A> {}
}
```

### Steps / History

- [x] Implementation: #117316
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by RalfJung** [comment]
Given that this function is still unstable, and doesn't do anything that's particularly tricky from a `const` perspective, I don't think we need a separate feature gate. So closing in favor of #32838 which tracks all the `new_in` methods. (https://github.com/rust-lang/rust/pull/133672 removes the feature gate from the code.)
