### ISSUE TITLE
run-make: do not use relative links to refer to compiler/stdlib sources, we should introduce some `CHECKOUT_ROOT` env var/helper.

### ISSUE THREAD

**Issue by jieyouxu** [rust-lang/rust#126071]
Some run-make tests refer to stdlib sources with `"../../../library/alloc/src/lib.rs"` which seems not ideal. @Kobzol suggested that we should introduce a `CHECKOUT_ROOT` helper to make this less fragile.

**Comment by bjorn3** [comment]
There is already the `S` env var for the source root.

**Comment by jieyouxu** [comment]
> There is already the `S` env var set by compiletest for the source root.

I'm actually dumb, we even already have `source_path` in the support library:

https://github.com/rust-lang/rust/blob/50297bb417dc338b475fd7cf8b706fa81df85b25/src/tools/run-make-support/src/lib.rs#L90-L92

**Comment by ChrisDenton** [comment]
That's a very descriptive environment variable name, lol
