### ISSUE TITLE
Inconsistent DEFAULT_MIN_STACK_SIZE Across Platforms Causes Unexpected Issues

### ISSUE THREAD

**Issue by namse** [rust-lang/rust#126027]
The DEFAULT_MIN_STACK_SIZE is the default stack size assigned when creating a thread. This value varies across different platforms. The issue is that there isn't enough explanation as to why these values are different, and users might not realize that the stack size can vary.

Recently, I was running existing Windows code on a WASI target, and I kept encountering font decoding failures. Since it worked correctly on Windows, I suspected WASI's instability and spent considerable time debugging. After several days, I discovered that the root cause was the stack size: WASI has a very small stack size of 4KB, while Windows has a much larger stack size of 2MB. Once I forcibly increased the thread's stack size, all issues were resolved.

I felt quite frustrated that such a simple reason caused the problem.

Although this is my personal experience, I believe that rather than setting different default stack sizes for different platforms without a compelling reason, it would be better to have a consistent stack size across all platforms in Rust.

However, I acknowledge that this suggestion might not be very effective because the required memory can vary depending on the instruction set or architecture.

I would like to discuss this matter further.

**Comment by workingjubilee** [comment]
Different platforms have different useful minimum stack sizes.

I have no idea why only 4KiB is reserved on wasi.

**Comment by workingjubilee** [comment]
This isn't an issue of "inconsistency" this is an issue of a target having an absurdly low value, period. Please open a PR to raise it.

**Comment by namse** [comment]
> Different platforms have different useful minimum stack sizes.

What are the criteria for determining that? Since I don't know, I can't tell whether the 4KB for WASI is inappropriate or not, and I also can't open a PR because I don't know the appropriate value.

**Comment by workingjubilee** [comment]
...a zillion insanely low-level minutiae like how big the registers are, mostly. an article that might help: https://ariadne.space/2021/06/25/understanding-thread-stack-sizes-and-how-alpine-is-different/

as that article explains, the smallest thread stack size of all platforms that I'm aware of, aside from the ones in our repo that only ask for 4096 bytes, is 64KiB. the current 4096 bytes boundary has caused you significant pain so it seems sensible to raise it to at least that much, then fool around and see how it works.

**Comment by workingjubilee** [comment]
I am pretty sure 4096 bytes was just picked as the "unsupported" value and platforms that initially lacked thread support, like wasm32-wasi, just inherited that value.

**Comment by namse** [comment]
I understand. The differences between the platforms are indeed huge..!

Before proceeding, I would like to hear the opinion or history from Alex Crichton, the main maintainer of the wasi target. @alexcrichton , could you please share your thoughts on this issue?

**Comment by alexcrichton** [comment]
I commented a bit on https://github.com/rust-lang/rust/pull/126059 but I've no recollection for the current value for wasi. I suspect it was a number of historical accidents that led to this, and stack sizes should definitely be larger than 4k by default on wasi. Thanks for the issue @namse!

**Comment by jtmoon79** [comment]
I linked to this Issue from StackOverflow. Perhaps someone in this thread knows how to [get default stack size at runtime](https://stackoverflow.com/questions/79924143/get-rust-default-stack-size-at-runtime)?
