### ISSUE TITLE
Rust types in FFI lint

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#12608]
Right now we have a lint mode which warns about the usage of rust types in `extern` blocks. This makes sure that by default you don't pass rust types into C functions. What we don't have is a lint going the other way which makes sure that C can't get Rust types from Rust. I believe that we need to expand the FFI lint to crawl `extern` functions as well as `extern` blocks. 

The exact types which should be allowed is a little questionable. Some things that would be *nice* to have a defined ABI/FFI for would, but may currently not be working:

* `Option<&T>` and `Option<~T>`. See #11303, but this is currently broken. Do we want to commit to this ABI and say that it's valid to use to interface with C?
* `~T` and `&T`, are these valid FFI types? The rust type system guarantees they are never null, but there's no guarantee that C handed you something that's not null.
* `&str` - should this be valid to pass in/out? This would require something along the lines of `rust.h`

To be conservative, we could *only* allow primitives (minus `int` and `uint`) plus `*T`, but this is quite limiting and makes FFI a little more difficult.

Nominating.

**Comment by mzabaluev** [comment]
To pass `&str` in and out of C you either need to use some adapter functionality like rust-lang/rfcs#494, or define the underlying structure in a C header and use that on the C side in the function/callback signatures.

**Comment by TimNN** [comment]
I think most of this has been addressed by #26583:

* `Option<&T>` is allowed (if `T` is a proper ctype)
* `&T` is allowed (if `T` is a proper ctype) 
* slices and `str` are not allowed

There is already a separate issue for checking `extern fn`'s: #19834

So I think this issue can be closed, if any of the three points above should be changed I would propose opening separate issues for them.

**Comment by alexcrichton** [comment]
Sounds good to me!
