### ISSUE TITLE
Missing optimized MIR for an item

### ISSUE THREAD

**Issue by tmiasko** [rust-lang/rust#126012]
```console
$ cat a.rs 
pub static A: fn() -> fn() = {
    #[inline(never)]
    fn f() {}
    #[inline(always)]
    || -> fn() { f }
};
$ cat b.rs
static A: fn() -> fn () = a::A;
fn main() { A()() }
$ rustc a.rs --crate-type=lib
$ rustc b.rs --extern a -L.
error: missing optimized MIR for an item in the crate `a`
  |
note: missing optimized MIR for this item (was the crate `a` compiled with `--emit=metadata`?)
 --> /.../a.rs:3:5
  |
3 |     fn f() {}
  |     ^^^^^^

error: aborting due to 1 previous error
```

Regression in c563f2ee799b285067124b516ce99f26063f8351 (#122371 cc @oli-obk @tmiasko).

@rustbot modify labels: +regression-from-stable-to-stable -regression-untriaged

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23126012.20Missing.20optimized.20MIR.20for.20an.20item)).

@rustbot label -I-prioritize +P-medium

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-06-06/near/443071818). A backport PR will be authored by the release team at the end of the current development cycle.

@rustbot label +beta-accepted
