### ISSUE TITLE
Fix memory leaks in doctests?

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#126067]
Currently a bunch of our doctests have memory leaks. For that reason, we have to disable Miri's leak checker when running doctests.

To reproduce:
```
MIRIFLAGS="-Zmiri-disable-isolation" ./x.py miri library/core library/alloc --doc
MIRIFLAGS="-Zmiri-disable-isolation" ./x.py miri library/std --doc -- --skip fs:: --skip net:: --skip process:: --skip sys::pal::
```

@rust-lang/libs how do you feel about that -- is it okay for the tests to leak, or should we fix that (by adding hidden code that deallocates things again)? Currently we don't have a good way to disable the leak checker on a per-test basis so there is a risk of accidental leaks.

**Comment by RalfJung** [comment]
One (I think somewhat typical) example of a leaky test is [this](https://doc.rust-lang.org/nightly/std/mem/union.MaybeUninit.html#out-pointers): a `Vec` is created but remains in a `MaybeUninit` so it is never dropped.

**Comment by ChrisDenton** [comment]
I've nominated for libs-api to ensure this gets discussed but feel free to un-nominate if a decision is made before a meeting.

**Comment by the8472** [comment]
> One (I think somewhat typical) example of a leaky test is [this](https://doc.rust-lang.org/nightly/std/mem/union.MaybeUninit.html#out-pointers): a `Vec` is created but remains in a `MaybeUninit` so it is never dropped.

Was that meant as an example of one that takes extra steps to unleak it? Since it calls `assume_init` which makes the vec droppable again.

The [Vec::leak](https://doc.rust-lang.org/nightly/std/vec/struct.Vec.html#method.leak) doctest is  an example that leaks.

**Comment by RalfJung** [comment]
Ah, I picked the wrong test indeed, sorry. [Here](https://doc.rust-lang.org/nightly/std/mem/union.MaybeUninit.html#method.new) is an example that leaks.

**Comment by Amanieu** [comment]
We discussed this in the libs meeting today. We would prefer to have miri check for leaks in doctests and handle the currently leaking tests by either:
- Fixing the leaks with hidden code.
- Adding a doctest attribute such as `no_leak_check` which disables leak checking just for that test.

**Comment by RalfJung** [comment]
> Adding a doctest attribute such as no_leak_check which disables leak checking just for that test.

That could be done if rustdoc allowed passing flags to Miri... but the could be only for Miri, not rustc, so not sure how to best do this. Alternatively, https://github.com/rust-lang/miri/issues/3670 would help.

**Comment by RalfJung** [comment]
This got fixed by https://github.com/rust-lang/rust/pull/127446 :)
