### ISSUE TITLE
Make Rust python scripts Py3K compatible

### ISSUE THREAD

**Issue by flaper87** [rust-lang/rust#12618]
We currently have a bunch of scripts that are not Py3K compatible. This is not a real problem, yet. However, it would be nice to have support for >=py26

**Comment by steveklabnik** [comment]
Given that we have the dependency on 2, it's not likely that this is possible.

**Comment by huonw** [comment]
A script can work with both Python 3 and Python 2; maybe it's pointless to do this while we still have to build LLVM, but if we ever have a good story around using system LLVM's it would be nice for our  scripts to be somewhat version agnostic.

**Comment by steveklabnik** [comment]
Some can, but not in the general case, right?

**Comment by sinistersnare** [comment]
Yes in the general case. Making forward compatible python code is a good idea right now.

**Comment by FlaPer87** [comment]
I think this issue should stay open. It's a nice bug for people willing to contribute to Rust (yes, not exactly rust but oh well).

That said, many systems are now moving to Py3K as the default python version, which makes this kind of more urgent. 

I'll re-open it as I might take a stab at it in the next couple of weeks.

**Comment by BigBoneDaddy** [comment]
@FlaPer87 @brson Does LLVM still only do Python 2 and not yet Python 3?

**Comment by sinistersnare** [comment]
@BigBoneDaddy, after a cursory glance, I would say they support 2, with a heavy eye towards 3.

[Here is a comment alluding to how they might be py3k compatible](https://github.com/llvm-mirror/llvm/blob/68081f41fafc13e194dfa639a3219b21c176489f/utils/lit/lit/TestRunner.py#L345-L354)

[A script that runs exclusively on 2.7](https://github.com/llvm-mirror/llvm/blob/1348f57925f17a804b46034b0471f64b615bdfab/utils/update_llc_test_checks.py)

[These build commands seem to show that Python2 is the version of choice](https://github.com/llvm-mirror/llvm/blob/4b64e72fdd4b72fd3b27fd9958431293f3e7b28a/autoconf/configure.ac#L1604)

Anyways, all of this is speculation, I would love for someone to get in touch with the LLVM guys (im sure someone hear knows one), and ask them what their stance on py3k is.

**Comment by richo** [comment]
I got as far as [making sure `make check`][0] works on python3 a while ago. afaik llvm is still broken.

[0]: https://github.com/rust-lang/rust/pull/25749

**Comment by steveklabnik** [comment]
Triage: in general, we try to keep our scripts compatible with both. Rather than a generic issue, this is going to be one that's better served by focus issues if and when we break compatibility specifically between version of Python. If you run into any, please open them up! Thanks!
