### ISSUE TITLE
Feature Request: OpenMP/TBB like Parallel For Loops

### ISSUE THREAD

**Issue by siavashserver** [rust-lang/rust#12619]
Is it possible to have some easy to use *parallel for* loops like OpenMP or Intel TBB in Rust? As far as I know their *parallel for* loops divide the range by CPU cores (or specified worker threads), then every worker thread will access a sequential stream of data in memory (better CPU cache utilization) and idle worker threads are also able to steal tasks from busy ones to balance the load (which is optional in OMP, and the default for the TBB).

Serial code:
```C++
void SerialApplyFoo( float b[], const float a[], size_t n ){
	for( size_t i=0; i<n; ++i )
		b[i] = Foo(a[i]);
}
```
Intel TBB example:
```C++
void ParallelApplyFoo (float b[], const float a[], size_t n){
	tbb::parallel_for (size_t(0), n, [=](size_t i) {
		b[i] = Foo(a[i]);
	});
}
```

OpenMP example:
```C++
void ParallelApplyFoo( float b[], const float a[], size_t n ){
	#pragma omp parallel for
	for( size_t i=0; i<n; ++i )
		b[i] = Foo(a[i]);
}
```

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#859

**Comment by JayKickliter** [comment]
For anyone who finds this issue by googling "rust OpenMP", take a look at [Rayon](https://github.com/rayon-rs/rayon).
