### ISSUE TITLE
Regression in nightly-2024-05-27

### ISSUE THREAD

**Issue by JonathanBrouwer** [rust-lang/rust#126117]
The code in my hobby project Prism compiles on stable, but not on the latest nightly.
https://github.com/JonathanBrouwer/Prism/tree/222637a80cc2bb7794d0e4f649665fdd4ca23320
Sadly the codebase is quite large and I don't really see a good way to reduce it.

I ran cargo-bisect-rustc, which got the following output: (Which is a version bump commit, which confuses me)

searched nightlies: from nightly-2024-01-01 to nightly-2024-06-07
regressed nightly: nightly-2024-03-18
searched commit range: https://github.com/rust-lang/rust/compare/766bdce744d531267d53ba2a3f9ffcda69fb9b17...eb45c844407968ea54df0d9870ebce9e3235b706
regressed commit: https://github.com/rust-lang/rust/commit/4c1b9c3e2f402efe27a24e424c9b59aa2fa5c83f

The most interesting error that is returned on nightly is:
```
error[E0391]: cycle detected when computing type of opaque `parser::parser_rule_body::parser_body_sub_annotations::{opaque#0}`
   --> prism-parser/src/parser/parser_rule_body.rs:122:6
    |
122 | ) -> impl Parser<'arn, 'grm, Cow<'arn, ActionResult<'arn, 'grm>>, E> + 'a {
    |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
note: ...which requires type-checking `parser::parser_rule_body::parser_body_sub_annotations`...
   --> prism-parser/src/parser/parser_rule_body.rs:125:27
    |
125 |             let mut res = parser_body_sub_annotations(rules, blocks, rest, expr, rule_args, vars)
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: ...which requires evaluating trait selection obligation `parser::parser_rule_body::parser_body_sub_annotations::{opaque#0}: core::marker::Unpin`...
    = note: ...which again requires computing type of opaque `parser::parser_rule_body::parser_body_sub_annotations::{opaque#0}`, completing the cycle
note: cycle used when computing type of `parser::parser_rule_body::parser_body_sub_annotations::{opaque#0}`
   --> prism-parser/src/parser/parser_rule_body.rs:122:6
    |
122 | ) -> impl Parser<'arn, 'grm, Cow<'arn, ActionResult<'arn, 'grm>>, E> + 'a {
    |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information
```
Though multiple errors are returned. The entire error log is:
https://gist.github.com/JonathanBrouwer/33d429eab435c266029b3a0828642760

**Comment by oli-obk** [comment]
probably specifically 29a630eb72ffb94c3708947afae1e948ad3cb189

**Comment by JonathanBrouwer** [comment]
I managed to reduce the example a lot.

This code still shows the same behavior:
```rust
pub trait Parser<E> {
    fn parse(&self) -> E;
}

impl<E, T: Fn() -> E> Parser<E> for T {
    fn parse(&self) -> E {
        self()
    }
}

pub fn recursive_fn<E>() -> impl Parser<E> {
    move || {
        recursive_fn().parse()
    }
}
```

**Comment by oli-obk** [comment]
oof, looks like this code will break with the new solver, too (cc @lcnr)

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23126117.20Regression.20in.20nightly-2024-05-27)).

@rustbot label -I-prioritize +P-high

**Comment by lqd** [comment]
Reopening to track beta backport
