### ISSUE TITLE
Reference to temporary variable passed as `&'static dyn` parameter compiles

### ISSUE THREAD

**Issue by ludfjig** [rust-lang/rust#126216]
I tried this code:

```rust
pub(crate) struct TestLogger {}

impl TestLogger {
    pub(crate) fn init() {
        log::set_logger(&TestLogger {}).expect("unable to setup test logger");
    }
}

impl log::Log for TestLogger {
    fn enabled(&self, _: &log::Metadata) -> bool {
        todo!()
    }

    fn log(&self, _: &log::Record) {
        todo!()
    }
	

    fn flush(&self) {
        todo!()
    }
}
```
[Rust Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=48ddbf5598b22de8f33ca51e30959e60)

I expected to see this happen: Since [log::set_logger](https://docs.rs/log/latest/log/fn.set_logger.html) takes a `&'static dyn` parameter, I wouldn't expect a reference to a temporary variable to compile, since it doesn't live long enough.

Instead, this happened: The code compiles successfully.

### Meta

`rustc --version --verbose`:
```
stable 1.78.0
```

**Comment by theemathas** [comment]
Not a bug. The temporary TestLogger is constant-promoted. The value is conceptually stored in the executable binary, like a `static`, and the reference points to that.

See https://doc.rust-lang.org/reference/destructors.html#constant-promotion

**Comment by ludfjig** [comment]
thanks, I didn't know this. Closing
