### ISSUE TITLE
Add a way to fail the process on `fail!`

### ISSUE THREAD

**Issue by larsbergstrom** [rust-lang/rust#12629]
It would be nice to have something like an environment variable or a runtime flag we could set that would cause calls to `fail!` to unconditionally terminate the entire process.

When we are running reference tests and content tests in Servo, we often want failure within a task to take down the whole process, both because our recovery could cause a "false" test success and because our failure recovery (currently) often results in a hung process.

This feature would also be very nice for easily getting a good stack backtrace from an intermittent failure - we can just do `ulimit -c unlimited`, turn on this flag, and then run the test until a core file is emitted.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#715
