### ISSUE TITLE
Make extern "rust-intrinsic" coerce to unsafe Rust functions

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#12633]
In addition to #10725, this is one of the things blocking replacing things like `cast::transmute` with intrinsics. Although they are callable like other Rust functions they cannot be assigned to normal Rust functions.

@nikomatsakis Interested in what you think.

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by steveklabnik** [comment]
I was trying to come up with some code to reproduce this, and here's what I had:

```
pub fn main() {
    unsafe {
        let copy: unsafe extern "rust-intrinsic" fn(*const i32, *mut i32, usize) = std::intrinsics::copy;
        let assign: unsafe fn(*const i32, *mut i32, usize) = std::mem::transmute(copy);
    }
}
```

This currently ICEs, and I filed #34123 with a smaller reproduction.

**Comment by brson** [comment]
Closing in favor of #34123
