### ISSUE TITLE
I am trying to create a yew app and here is what I get

### ISSUE THREAD

**Issue by MSJadoon** [rust-lang/rust#126336]
### Code

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by clubby789** [comment]
Can you provide some details of your issue? Please include code to reproduce the issue and a backtrace of the compiler error.

**Comment by clubby789** [comment]
I'm going to restore that label; can't really triage this until there are any details 😅

**Comment by bjorn3** [comment]
OP opened https://github.com/rust-lang/rust/issues/126338, which has some more details. Still not clear at all.

**Comment by ChrisDenton** [comment]
Closing this one then.
