### ISSUE TITLE
`trait Trait: Send`: upcasting from `dyn Trait` to `dyn Send` does not work

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#126313]
The following compiles:
```rust
#![feature(trait_upcasting)]
trait Super {}
trait Trait: Super {}
fn foo(x: &dyn Trait) -> &dyn Super { x }
```

while this does not:
```rust
#![feature(trait_upcasting)]
trait Super {}
trait Trait: Send {}
fn foo(x: &dyn Trait) -> &dyn Send { x }
```

cc @compiler-errors I thought we actually had a PR for that at some point :thinking: I think that's actually not the case though. It wasn't part of #119338

**Comment by compiler-errors** [comment]
I had a separate PR to upcast dropping the principal but I think I never FCPd it because I was too lazy: https://github.com/rust-lang/rust/pull/114679#issuecomment-1904644704
