### ISSUE TITLE
Replace various intrinsic wrappers with intrinsic reexports

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#12634]
Alternative strategy to #10008, depends on #10725 and #12633.

rustc spends a lot of time inlining intrinsic wrappers, and in debug mode they cause a lot of code bloat. Once intrinsics behave more like real functions we can use reexports to get rid of the wrappers.

**Comment by steveklabnik** [comment]
Triage: issue link is https://github.com/rust-lang/rfcs/blob/master/text/0008-new-intrinsics.md

**Comment by steveklabnik** [comment]
Triage: rust-intrinsic still exists

**Comment by brson** [comment]
Original RFC is dead. Issue is quite obsolete.
