### ISSUE TITLE
Bevy segfaults on some Windows systems after Rust 1.79 update

### ISSUE THREAD

**Issue by mockersf** [rust-lang/rust#126442]
The issue was first noticed in CI: https://github.com/bevyengine/bevy/actions/runs/9505180010/job/26199467296

The same job works on Rust 1.78: https://github.com/mockersf/bevy/actions/runs/9506123706/job/26202601792

A few users reported the same error, so it's not just on virtualised hardware. It's also not on all Windows machines

It seems to be triggered when rendering. Running an example from the Bevy repository that renders something reliably causes a segfault on some systems when using DirectX12. Running directly examples from wgpu don't seem to cause the crash.

A user report that it fails on nightly-2024-04-18, and works on nightly-2024-04-17

Sorry that's not much to go on, but I don't have an affected system available.

**Comment by lqd** [comment]
> A few users reported the same error, so it's not just on virtualised hardware. It's also not on all Windows machines

https://github.com/rust-lang/cargo-bisect-rustc would help locating the nightly and PR where this issue appeared.

**Comment by janhohenheim** [comment]
I'm a bit sleepy, but I'll try `cargo-bisect-rustc` now and see how far I get

**Comment by janhohenheim** [comment]
Per another user running the tools, the offending commit is https://github.com/rust-lang/rust/commit/38104f3a8838f8662ad3cccc4d7262a96bf9724

**Comment by lqd** [comment]
cc PR author @Mark-Simulacrum on that bisection

**Comment by janhohenheim** [comment]
By bisection is done and I can confirm the result. This is the output:


searched nightlies: from nightly-2024-04-17 to nightly-2024-04-18
regressed nightly: nightly-2024-04-18
searched commit range: https://github.com/rust-lang/rust/compare/1cec373f65eb76e8e4b4d1847213cf3ec6c292b6...becebb3158149a115cad8a402612e25436a7e37b
regressed commit: https://github.com/rust-lang/rust/commit/38104f3a8838f8662ad3cccc4d7262a96bf9724e

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.8</summary>


Host triple: x86_64-pc-windows-msvc
Reproduce with:
```bash
cargo bisect-rustc --end=2024-04-18 --prompt --with-src -- run --example alien_cake_addict
```
</details>

**Comment by alice-i-cecile** [comment]
The offending PR: https://github.com/rust-lang/rust/pull/123936

**Comment by workingjubilee** [comment]
If that is the offending commit, then it seems very unlikely that this has not unveiled a bug inside wgpu or whatever else is busy talking to DX12.

**Comment by workingjubilee** [comment]
Can you get a backtrace in WinDbg or whatever's fashionable?

Or can a "minimalized" repro case be produced?

**Comment by Brezak** [comment]
When looking at WinDbg the issue seems to arise [here](https://github.com/gfx-rs/wgpu/blob/d7a35ecda06742acb4cdd5a83c5b9737f375a70b/wgpu-hal/src/dx12/shader_compilation.rs#L41). wgpu-hal was converting a normal rust str into a c_char ptr and passing that across ffi to a function expecting a null terminated string. Unluckily for us this string was a empty string "". Before #123936 that meant we'd get to somewhere we can read from. After the PR we get a 0x1 pointer that will cause a segfault when read from.

**Comment by workingjubilee** [comment]
Agh, that is the classic error that I predicted [in my remarks here](https://github.com/rust-lang/rust/pull/123936#issuecomment-2167003939).

**Comment by workingjubilee** [comment]
This passes, so changing to `c""` should be fine.
```rust
#[test]
fn cstrs_dont_dangle() {
    let c_str = c"";
    assert_ne!(c_str.as_ptr(), std::ptr::NonNull::dangling().as_ptr());
}
```

However... @Brezak Are you sure that's the issue? It seems that this string was created from a `CString::new()`?

https://github.com/gfx-rs/wgpu/blob/d7a35ecda06742acb4cdd5a83c5b9737f375a70b/wgpu-hal/src/dx12/device.rs#L281-L288

**Comment by workingjubilee** [comment]
Oh, I was squinting at the wrong line it seems.

**Comment by Brezak** [comment]
I'm not at my computer right now but in the code calling said borked function there was a unwrap_or_default creating a that would get passed into the function.

**Comment by workingjubilee** [comment]
yep.

**Comment by Brezak** [comment]
For reference. The source of the `source_name`: https://github.com/gfx-rs/wgpu/blob/d7a35ecda06742acb4cdd5a83c5b9737f375a70b/wgpu-hal/src/dx12/device.rs#L262-L267

**Comment by workingjubilee** [comment]
It seems that the reason this isn't hit on the other path is that `D3DCompiler` is called pretty much directly by wgpu, whereas the `hassle_rs` bindings of the `DxcCompiler` convert strings into null terminated wide strings first.

**Comment by RalfJung** [comment]
> When looking at WinDbg the issue seems to arise [here](https://github.com/gfx-rs/wgpu/blob/d7a35ecda06742acb4cdd5a83c5b9737f375a70b/wgpu-hal/src/dx12/shader_compilation.rs#L41). wgpu-hal was converting a normal rust str into a c_char ptr and passing that across ffi to a function expecting a null terminated string. Unluckily for us this string was a empty string "". Before #123936 that meant we'd get a pointer to somewhere we can read from. After the PR we get a 0x1 pointer that will cause a segfault when read from.

So seems like previously you were lucky that the pointer was pointing to a zero byte and so the c string was considered empty -- but that was still UB since you were outside the bounds of that zero-sized allocation.
Now this OOB is detected by hardware and leads to a segfault.

`CString` can never be backed by a zero-sized allocation, so looks like `stage.module.raw_name` is created incorrectly if it has pointer value 0x1.

FWIW, using `CString::to_str()` and then accessing the trailing 0 is UB under the Stacked Borrows aliasing rules, since the 0 is outside the bounds of the `str`. To get a pointer to the entire string including the 0, you need to use `CString::as_ptr()`. It seems unlikely that that would be the issue though.

**Comment by workingjubilee** [comment]
@RalfJung Note that [`hassle_rs::DxcCompiler::compile`](https://docs.rs/hassle-rs/latest/hassle_rs/wrapper/struct.DxcCompiler.html#method.compile) is somewhat to "blame" here: its API design requests a `&str` and then "helpfully" converts this to the requisite string, allocating to do so. Thus the `compile_fxc` API implemented by wgpu matches the signature that is used by `compile_dxc`, which partially matches the signature of `DxcCompiler::compile`.

**Comment by RalfJung** [comment]
hassle_rs is providing a nice Rusty API and doing so correctly. I don't think they have to take any blame here.

wgpu tried and failed to provide the same nice Rusty API, and used an `&str` in a way that is not backed by its invariant.

(For anyone reading along, also see the discussion [here](https://github.com/gfx-rs/wgpu/pull/5812#discussion_r1639360846).)

**Comment by workingjubilee** [comment]
It _is_ a Rusty API, it's just slightly perplexing to me because the caller is holding on to a CString anyways, it seems.

**Comment by RalfJung** [comment]
This particular caller is, maybe others are not?

**Comment by workingjubilee** [comment]
Hopefully!

Actually what's more confusing, now that I look closer, is that the underlying compiler API for DXC takes a wide string... and this is the newer one? It seems like that should be the other way around, knowing Microsoft API version history, and the new one should accept a UTF-8 string, and the older one should ask for a wide string...

...oh wait, both APIs are deprecated, actually, and Microsoft is on to `IDxcCompiler3::Compile` now. Well!

**Comment by mockersf** [comment]
Thank you for the help and the investigation! It now has been fixed in wgpu, waiting for a backport and a release
