### ISSUE TITLE
cross-crate attribute macro reexport source links are broken

### ISSUE THREAD

**Issue by lolbinarycat** [rust-lang/rust#126483]
I'm not sure if this is the fault of docs.rs or rustdoc, or a bit of both, but on some reexported attribute macros the "source" link is broken, and you have to click the identifier to get to the original docs, then click source

for example, [`#[wasm_bindgen]`](https://docs.rs/wasm-bindgen/latest/wasm_bindgen/prelude/attr.wasm_bindgen.html) links to this:

https://docs.rs/wasm-bindgen-macro/0.2.92/x86_64-unknown-linux-gnu/src/wasm_bindgen_macro/lib.rs.html#9

which is a dead link.

**Comment by GuillaumeGomez** [comment]
Just checked and it seems to be working. Closing then.
