### ISSUE TITLE
Can the rust/build/x86_64-unknown-linux-gnu/stage0 directory be generated without network?

### ISSUE THREAD

**Issue by MinxuanZ** [rust-lang/rust#126589]
I try to compile and test offline，but some tests failed in src/bootstrap 
`../configure --set build.cargo=/usr/bin/cargo  --set build.rustc=/usr/bin/rustc `
`./x.py --config build/config.toml t src/bootstrap`
output:
fail :rust/build/x86_64-unknown-linux-gnu/stage0 /bin/rustc --target x86_64-unknown-linux-gnu --print target-libdir error:no such file or directory

only have stage0-std   stage0-rustc stage0-sysroot  directory

**Comment by bjorn3** [comment]
Have you enabled vendoring in config.toml? And maybe a silly question, but just to double check: Do you have a rustc installed locally at `/usr/bin/rustc`?
