### ISSUE TITLE
Two subsequent labels and unnecessary `jmp` with `opt-level=s`

### ISSUE THREAD

**Issue by mickvangelderen** [rust-lang/rust#126585]
The following code:

```rust
const fn checked_div_round(a: u64, b: u64) -> Option<u64> {
    match b {
        0 => None,
        1 => Some(a),
        // `a / b` is computable and `(a % b) * 2` can not overflow since `b >= 2`. UPDATE <- this is wrong
        b => Some(a / b + if (a % b) * 2 >= b { 1 } else { 0 }),
    }
}
```

Generates two subsequent labels and an unnecessary `jmp` instruction:

```asm
checked_div_round:
        test    rsi, rsi
        je      .LBB0_1
        cmp     rsi, 1
        je      .LBB0_3
        mov     rax, rdi
        xor     edx, edx
        div     rsi
        add     rdx, rdx
        cmp     rdx, rsi
        mov     rdi, rax
        sbb     rdi, -1
.LBB0_3:
        mov     esi, 1
        jmp     .LBB0_4   ; this jump does not seem necessary since `.LBB0_1` is empty
.LBB0_1:
.LBB0_4:
        mov     rax, rsi
        mov     rdx, rdi
        ret
```

When compiled with `-C opt-level=s` using rustc `1.79.0`.

Godbolt: https://godbolt.org/z/fhTq3ssnK

P.S. For context, I am not too familiar with asm. I did not find any similar results while searching through the rustc and llvm issue trackers for "double | subsequent | unnecessary label" or "unnecessary jmp | jump". Please let me know how I can improve the quality of my issue reporting.

**Comment by DianQK** [comment]
Here are multiple solutions to this problem. It can be resolved by directly optimizing in IR (https://github.com/llvm/llvm-project/issues/95919) or during the code generation phase (https://github.com/llvm/llvm-project/issues/95921). I believe the code generation phase is the key point, and we can use `undef` to eliminate this branch. However, I am more familiar with IR-related aspects, so let me resolve it here now.

**Comment by DianQK** [comment]
Fixed by https://github.com/llvm/llvm-project/issues/95919. 
@rustbot label +llvm-fixed-upstream

**Comment by nikic** [comment]
Confirmed fixed by https://github.com/rust-lang/rust/pull/127513, needs codegen test.

**Comment by mickvangelderen** [comment]
> I would expect this to overflow if `a > u64::MAX / 2` and `b > a` ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d9a0cf57247e2ef7e0d442fe76bb95a3))

You're right, I made a logical error.
