### ISSUE TITLE
Compiler hangs on recursive HRTB

### ISSUE THREAD

**Issue by Nadrieril** [rust-lang/rust#126519]
I tried this code:

```rust
pub trait LendingIteratorItem<'item> {
    type Item;
}

impl<'item, F> LendingIteratorItem<'item> for (F,)
where
    F: for<'a> FnMut(<Self as LendingIteratorItem<'a>>::Item),
{
    type Item = ();
}
```

On this code, rustc hangs and slowly eats all my memory. If I change `(F,)` to `F`, at least I get "overflow evaluating the requirement" before it eats all my memory. A bunch of other simplifications all error with "overflow evaluating the requirement".

### Meta

`rustc --version --verbose`:
```
rustc 1.81.0-nightly (f8e566053 2024-06-14)
binary: rustc
commit-hash: f8e566053207b4ecbcbc7a7d6ded82c43061e3da
commit-date: 2024-06-14
host: x86_64-unknown-linux-gnu
release: 1.81.0-nightly
LLVM version: 18.1.7
```

**Comment by matthiaskrgr** [comment]
is this a duplicate / code from https://github.com/rust-lang/rust/issues/108826#issuecomment-1464685164 ?

**Comment by Nadrieril** [comment]
Ah yep, looks similar
