### ISSUE TITLE
Regression in type inference between stable 1.79.0 and nightly-2024-06-19

### ISSUE THREAD

**Issue by marmeladema** [rust-lang/rust#126685]
### Code

I tried this code in nightly:

```rust
pub fn parse(bytes: &[u8]) -> String {
    std::ffi::CStr::from_bytes_until_nul(bytes)
        .unwrap()
        .to_str()
        .unwrap()
        .split('\n')
        .map(str::trim_end)
        .collect::<Box<_>>()
        .join("\n")
}
```

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=be71e0fb8185c11ac3123de70b02cee6

I expected to see this happen: it compiles successfully

Instead, this happened: 

```
error[E0282]: type annotations needed
 --> src/lib.rs:8:10
  |
8 |         .collect::<Box<_>>()
  |          ^^^^^^^ cannot infer type of the type parameter `B` declared on the method `collect`
9 |         .join("\n")
  |          ---- type must be known at this point
  |
help: consider specifying the generic argument
  |
8 |         .collect::<Vec<_>>()
  |                 ~~~~~~~~~~

For more information about this error, try `rustc --explain E0282`.
error: could not compile `playground` (lib) due to 1 previous error
```

### Version it worked on

It most recently worked on: Rust 1.79.0

### Version with regression

nightly-2024-06-19

**Comment by apiraino** [comment]
Bisection points to #99969 cc @dtolnay @calebsander 

Can this issue be considered an intended or rather an unintended behaviour?

I can reproduce in beta so I'll flip the regression labels

**Comment by calebsander** [comment]
I think this is expected. With the additional implementation of `collect()` into `Box<str>`, it's now ambiguous whether `Box<_>` means `Box<[_]>` or `Box<str>`. It's unfortunate to regress existing code that wasn't being explicit, but I think this is an acceptable cost for the additional functionality.

**Comment by marmeladema** [comment]
Fine by me. Maybe this should be announced as part of the release note to let people know?

**Comment by apiraino** [comment]
Did we announce these changes in the end? I could be wrong but I _think_ I don't see anything related in the 1.80.0 [release notes](https://github.com/rust-lang/rust/releases/tag/1.80.0), correct?

(btw, can this be closed now?)

cc @Mark-Simulacrum
