### ISSUE TITLE
std::ptr::copy_nonoverlapping failing on windows

### ISSUE THREAD

**Issue by rani-sharim** [rust-lang/rust#126687]
I have a rust program that is compiled as a dll. This dll is then loaded by a 3rd party app.

Part of the process is creating "sessions" for the 3rd party app. For that it gives you a void pointer and basically tells you "write whatever you want in here, we won't try to read it, just give it back with each subsequent call". So for simplicity, I figured out I'd just have a uint32 session id and write it to the pointer, and read it back when given (code below).

This workes fine on `1.77.0`, but crashes the 3rd party app on `1.79.0`, one what seems like a memory violation.

Writing the session id:

```
// Session type is "pub type Session = *mut ::std::os::raw::c_void;"
// pSess is defined as "pSess: *mut bindings::Session"

let session_id = session_manager.create_session()?;

debug!("Session Id: {session_id}");

let le_bytes = session_id.to_le_bytes();

unsafe {
    std::ptr::copy_nonoverlapping(le_bytes.as_ptr(), pSess as *mut u8,  le_bytes.len()); 
}
```

Reading back the session id:

```
fn decode_session_id(pSess: &bindings::Session) -> Result<SessionId, Error> {
    if pSess.is_null() {
        return Err(anyhow::Error::msg(format!("invalid session id: null")));
    }
   
    let mut session_id_buf = [0u8; size_of::<SessionId>()];
   
    debug!("decode_session_id: before copy"); // <-- I can see this log

    unsafe {
        std::ptr::copy_nonoverlapping(pSess, session_id_buf.as_mut_ptr() as *mut bindings::Session, session_id_buf.len());
    }

    debug!("decode_session_id: after copy"); // <-- when failing, never gets to this
```

### Version it worked on
It most recently worked on: 1.78.0

### Version with regression
`rustc --version --verbose`:
```
rustc 1.79.0 (129f3b996 2024-06-10)
binary: rustc
commit-hash: 129f3b9964af4d4a709d1383930ade12dfe7c081
commit-date: 2024-06-10
host: x86_64-pc-windows-msvc
release: 1.79.0
LLVM version: 18.1.7
```

**Comment by saethlin** [comment]
Based on the current contents of the issue description, my best guess is that this is UB in your code, not a compiler bug. We have had a few similar reports recently. If you can share enough code to reproduce the crash on 1.79, we can figure out what's going on here.

**Comment by ChrisDenton** [comment]
```rust
std::ptr::copy_nonoverlapping(pSess, session_id_buf.as_mut_ptr() as *mut bindings::Session, session_id_buf.len());
```

This line looks wrong. The count is the number of items, not the byte size.

**Comment by rani-sharim** [comment]
@ChrisDenton Yes, that seems to be it. Thanks!
