### ISSUE TITLE
`safe` keyword is not feature-gated

### ISSUE THREAD

**Issue by compiler-errors** [rust-lang/rust#126755]
In #126749, @ehuss reports:

Another issue appears that `safe` is not feature-gated. The following seems to build without a feature gate:

```rust
safe fn foo() {}
```

_Originally posted by @ehuss in https://github.com/rust-lang/rust/issues/126749#issuecomment-2181175095_

Tracking:

- https://github.com/rust-lang/rust/issues/123743

**Comment by compiler-errors** [comment]
this regressed in https://github.com/rust-lang/rust/pull/124482

**Comment by traviscross** [comment]
cc @spastorino

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23126755.20.60safe.60.20keyword.20is.20not.20feature-gated)).

@rustbot label -I-prioritize +P-high

**Comment by compiler-errors** [comment]
This got fixed and beta backported
