### ISSUE TITLE
`doc(inline)` overrides `doc(hidden)`, but only for crates

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#126796]
```rust
// src/lib.rs

#![doc(hidden)]

#[doc(inline)]
pub use std;

#[doc(inline)]
pub use std::marker;

#[doc(inline)]
pub use std::marker::PhantomData;
```

Expected: empty documentation, as you would get with no items in the crate, or without #\[doc(inline)\] on the items.

<p align="center"><img src="https://github.com/rust-lang/rust/assets/1940490/9a5e21af-af32-4203-9156-e9682642036d" width="80%"></p>

Actual, as of rustdoc 1.70 through current nightly: the crate `std` is shown despite #\[doc(hidden)\]. The other 2 items are correctly not shown.

<p align="center"><img src="https://github.com/rust-lang/rust/assets/1940490/c84e68c8-056d-46eb-84da-b3616a809e05" width="80%"></p>

**Comment by Indra-db** [comment]
ran into this bug as well today

**Comment by GuillaumeGomez** [comment]
Found the bug. Sending the fix.
