### ISSUE TITLE
electric bug display with seismic detector

### ISSUE THREAD

**Issue by dinahole** [rust-lang/rust#126826]
when only using the seismic dectector which should only have one draw power when explostion goes off it will incorectly show a higher draw power on battery its connected to. 
Tried this with a battery with full load on it and when explosive went off did not shut down any of the rest of the circuit so thats good only the incorrect reading on the battery which never went above 100

**Comment by workingjubilee** [comment]
@dinahole We have no connection to @Facepunch or the Rust game.
