### ISSUE TITLE
Unhelpful compiler suggestion when trying to dereference a pointer that is not `Copy`

### ISSUE THREAD

**Issue by cyrgani** [rust-lang/rust#126863]
### Code

```Rust
fn main() {
    let val = String::from("test");
    let p = std::ptr::addr_of!(val);
    unsafe {
        let inner: String = *p;
        dbg!(inner);
        std::mem::forget(val);
    }
}
```

### Current output

```Shell
error[E0507]: cannot move out of `*p` which is behind a raw pointer
 --> src/main.rs:5:29
  |
5 |         let inner: String = *p;
  |                             ^^ move occurs because `*p` has type `String`, which does not implement the `Copy` trait
  |
help: consider removing the dereference here
  |
5 -         let inner: String = *p;
5 +         let inner: String = p;
  |
help: consider cloning the value if the performance cost is acceptable
  |
5 -         let inner: String = *p;
5 +         let inner: String = p.clone();
  |

For more information about this error, try `rustc --explain E0507`.
```

### Desired output

```Shell
error[E0507]: cannot move out of `*p` which is behind a raw pointer
 --> src/main.rs:5:29
  |
5 |         let inner: String = *p;
  |                             ^^ move occurs because `*p` has type `String`, which does not implement the `Copy` trait
  |
help: consider using `ptr::read` to get the value the pointer refers to
  |
5 -         let inner: String = *p;
5 +         let inner: String = p.read();  
  |

For more information about this error, try `rustc --explain E0507`.
```

### Rationale and extra context

Cloning the pointer doesn't make sense in that situation and would cause a type mismatch error. I'm not sure whether any of the two current suggestions should be kept or removed in this case.

### Rust Version

```Shell
rustc 1.79.0 (129f3b996 2024-06-10)
binary: rustc
commit-hash: 129f3b9964af4d4a709d1383930ade12dfe7c081
commit-date: 2024-06-10
host: x86_64-unknown-linux-gnu
release: 1.79.0
LLVM version: 18.1.7
```

**Comment by workingjubilee** [comment]
Note that this works:
```rust
        let inner: String = (*p).clone();
```

It works because `(*p)` is a _place expression_ and then we attach `.clone()` to that, which then reborrows the String.

I don't think we should suggest `.read()`, which may have undesirable or unexpected effects in the case of things like types that handle backing buffers, instead of issuing a safe `.clone()` which will recreate the backing allocation correctly.

**Comment by cyrgani** [comment]
I didn't know that was possible, thanks for letting me know. I guess that the best approach would then be to change the `.clone()` suggestion accordingly as below?

```Shell
help: consider cloning the value if the performance cost is acceptable
  |
5 -         let inner: String = *p;
5 +         let inner: String = (*p).clone();
  |
```

**Comment by workingjubilee** [comment]
Correct.
Also, we could _mention_ `read` in the error for pointers, but we shouldn't _recommend_ it.

**Comment by workingjubilee** [comment]
The relevant section of diagnostic code is here https://github.com/rust-lang/rust/blob/fc555cd832ee743ff5410c35de2b0dd59ec4322e/compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs#L1299-L1327 but it will require some restructuring to account for the fact that the `ty::RawPtr` suggestion will *not* be doing things like stripping parentheses, but suggesting adding them if they don't exist.

**Comment by linyihai** [comment]
@rustbot  claim 
It looks good for me to make a try.
