### ISSUE TITLE
Bootstrap panics if lldb fails to start

### ISSUE THREAD

**Issue by ChrisDenton** [rust-lang/rust#126892]
Running `./x test tests/ui --stage 1` on Windows I get:

```
thread 'main' panicked at src\core\build_steps\test.rs:1820:40:
"lldb" "-P" failed Output { status: ExitStatus(ExitStatus(3221225781)), stdout: "", stderr: "" }
```

This seems especially unfortunate because (as far as I know) ui tests don't require lldb. It works fine if there's no lldb in `PATH` at least.

This is ultimately an LLVM issue caused by not installing/shipping its own dependencies (in this case Python310). However, bootstrap shouldn't crash here. It should be treated similarly to lldb not existing unless it is actually necessary,

**Comment by jieyouxu** [comment]
The temporary workaround is ensuring that

> you also need `python310.dll` in `PATH` otherwise bootstrap errors
