### ISSUE TITLE
Mistaken type annotation on documentation page for HashMap

### ISSUE THREAD

**Issue by acotis** [rust-lang/rust#126848]
### Location

https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.get

### Summary

On this documentation page about the HashMap type, the type signature for the `.get()` method puts type bounds on a type `K` which does not actually appear in the signature. I suspect the variable `k` should have type `K` or the type bound should simply be removed.
![image](https://github.com/rust-lang/rust/assets/6502776/577e9a5a-9f07-4129-93aa-416268f76852)

**Comment by workingjubilee** [comment]
There seems to be a K parameter in scope?

![impl<K, V, S> HashMap<K, V, S>
where
    K: Eq + Hash,
    S: BuildHasher](https://github.com/rust-lang/rust/assets/46493976/86a66f4f-d5a1-48eb-adf6-063ecab104b0)

**Comment by acotis** [comment]
Oh, I see. Okay, I didn't think to look up for a header that would bind K like that. I think this is probably a non-issue then.

**Comment by workingjubilee** [comment]
maybe it would be nice if we took advantage of the fact that we generate custom highlighting to highlight type params based on their sources.
