### ISSUE TITLE
Docs of `core::arch::x86[_64]::_mm_blendv_epi8` describes element selection backwards

### ISSUE THREAD

**Issue by abt8601** [rust-lang/rust#126935]
### Location

The documentation of `core::arch::x86::_mm_blendv_epi8` and `core::arch::x86_64::_mm_blendv_epi8` functions.

### Summary

In actual behaviour and [Intel's documentation](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm_blendv_epi8), `_mm_blendv_epi8(a, b, mask)` selects elements from `b` when the mask bit is set and from `a` otherwise. The Rust standard library documentation describes the other way around.

**Comment by mtilda** [comment]
I believe I see the problem. Working on a PR now.
