### ISSUE TITLE
Taking reference to function gets optimized to be 0x1

### ISSUE THREAD

**Issue by kbouchard-dev** [rust-lang/rust#126990]
Hello,

I had a function with a similar prototype to:
```rust
pub fn print_addr<T>(tt: &T) {
    println!("My arg is: {:p}", tt);
}
```

However, when passing a function as a reference in Rust 1.79.0+, the address gets simplified to 0x1.

I tried this code:
```rust
pub fn print_addr<T>(tt: &T) {
    println!("My arg is: {:p}", tt);
}

pub fn moo() {}

pub fn main() {
    static VAL: u8 = 0;
    let x = 0;
    print_addr(&moo);
    print_addr(&VAL);
    print_addr(&x);
}
```

I expected to see this happen:
```
My arg is: 0x5b664c53b020
My arg is: 0x5b664c53b077
My arg is: 0x7ffd0a352884
```

As under Rust 1.78 and under, this is the behaviour.

Instead, this happened:
```
My arg is: 0x1
My arg is: 0x5c61aac92093
My arg is: 0x7ffc6d0739b4
```

I am aware taking a reference to a function is the incorrect way of getting a pointer to it, however, I still feel it is wrong for the value to be 0x1.

### Meta
`rustc --version --verbose`:
```
rustc 1.79.0 (129f3b996 2024-06-10)
binary: rustc
commit-hash: 129f3b9964af4d4a709d1383930ade12dfe7c081
commit-date: 2024-06-10
host: x86_64-pc-windows-msvc
release: 1.79.0
LLVM version: 18.1.7
```

**Comment by saethlin** [comment]
> I am aware taking a reference to a function is the incorrect way of getting a pointer to it, however, I still feel it is wrong for the value to be 0x1.

Correct, this code simply does not provide a pointer to the function. It does something entirely different.

**Comment by compiler-errors** [comment]
> I am aware taking a reference to a function is the incorrect way of getting a pointer to it, however, I still feel it is wrong for the value to be 0x1.

This is because you're taking a reference of the zero-sized type (ZST) corresponding to [the function itself](https://doc.rust-lang.org/reference/types/function-item.html) -- *not* a function pointer type (`fn()`). Taking a reference to a ZST returns a reference that's dangling but valid, since dereferencing it doesn't actually read anything (since it's zero-sized).

**Comment by SkiFire13** [comment]
Also, if you still want to pass a reference to a function pointer (not that it made much sense) you would have to cast the function item to a function pointer before creating the reference. For example:

```
pub fn print_addr<T>(tt: &T) {
    println!("My arg is: {:p}", tt);
}

pub fn moo() {}

pub fn main() {
    static VAL: u8 = 0;
    let x = 0;
    print_addr(&(moo as fn()));
    print_addr(&VAL);
    print_addr(&x);
}
```

This now prints:
```
My arg is: 0x55e71196d360
My arg is: 0x55e71195e073
My arg is: 0x7fff3b9fd784
```
