### ISSUE TITLE
Tracking Issue for Missing BMI1, AVX2, SSE2, SSE4.1, SSE4a and TBM intrinsics

### ISSUE THREAD

**Issue by sayantn** [rust-lang/rust#126936]
The feature gate is `#[feature(simd_x86_updates)]`.

The Public API is 13 new intrinsics (probably overlooked in the `simd_x86` feature). See rust-lang/stdarch#1178.

 - **BMI1**
    - [`_tzcnt_u16`](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_tzcnt_u16)

 - **AVX2**
    - [`_mm_broadcastsi128_si256`](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm_broadcastsi128_si256)
    - [`_mm256_stream_load_si256`](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm256_stream_load_si256)

 - **SSE2**
    - [`_mm_loadu_si16`](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm_loadu_si16)
    - [`_mm_storeu_si16`](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm_storeu_si16)
    - [`_mm_loadu_si32`](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm_loadu_si32)
    - [`_mm_storeu_si32`](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm_storeu_si32)
    - [`_mm_storeu_si64`](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm_storeu_si64)
   
 - **SSE4.1**
    - [`_mm_stream_load_si128`](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm_stream_load_si128)

 - **SSE4a**
    - `_mm_extracti_si64`
    - `_mm_inserti_si64`

 - **TBM**
    - `_bextri_u32`
    - `_bextri_u64`

## Steps
 - [ ] Final Comment Period (FCP)
 - [ ] Stabilization PR

## Implementation History
 - rust-lang/stdarch#1594
 - rust-lang/stdarch#1607

We cannot add [`_mm_malloc`](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm_malloc) and [`_mm_free`](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm_free) as they need access to OS, but `core_arch` is a `no_std` environment.

**Comment by Amanieu** [comment]
These intrinsics were supposed to be part of a already-stabilized set, but were previously overlooked.

@rfcbot fcp merge

**Comment by RalfJung** [comment]
Oh no, more non-temporal operations... quoting from [a recent x86 memory model paper](https://dl.acm.org/doi/10.1145/3498683):

> In addition to several non-temporal store instructions, Intel-x86 architectures provide a single
non-temporal load instruction. However, as our private correspondence with the lead architect of
the Intel instruction set system architecture has revealed, the non-temporal load instruction has
been a source of implementation issues, it has not been implemented consistently, and there has
been ambiguity regarding its semantics.

Are we sure we can just pretend that those are regular loads, for the purpose of language semantics?

**Comment by RalfJung** [comment]
Thanks; I will get in touch with the authors of the paper to clarify whether the architect they spoke with was referring to non-temporal loads behaving in odd ways only for "non-standard" memory regions or also for write-back memory.

Meanwhile, would be worth warning about people using these intrinsics on non-write-back memory? Though that warning is probably better placed at whatever operation creates such memory. It's not really well-defined to access such memory with Rust operations (i.e., outside of inline assembly) anyway...
