### ISSUE TITLE
runtime error: global allocator may not use TLS on arm64 macos

### ISSUE THREAD

**Issue by MarinPostma** [rust-lang/rust#126948]
When using TLS from the global allocator on arm64 macos, I get the following fatal runtime error:
```
fatal runtime error: global allocator may not use TLS
```

This doesn't happen on x86 linux, and I can't find any mention of it anywhere. Grepping the rust repo returns nothing for that error either, so I'm not sure where it's coming from

I tried this code:

```rust
use std::alloc::{GlobalAlloc, System};

#[global_allocator]
static GLOBAL: Allocator = Allocator;

struct Allocator;

thread_local! {
    static FOO: usize = 0;
}

unsafe impl GlobalAlloc for Allocator {
    unsafe fn alloc(&self, layout: std::alloc::Layout) -> *mut u8 {
        FOO.with(|foo| {
            println!("{foo}");
        });
        System.alloc(layout)
    }

    unsafe fn dealloc(&self, ptr: *mut u8, layout: std::alloc::Layout) {
        System.dealloc(ptr, layout)
    }
}

fn main() {
    let hello = String::from("hello");
    println!("{hello}");
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.79.0 (129f3b996 2024-06-10)
binary: rustc
commit-hash: 129f3b9964af4d4a709d1383930ade12dfe7c081
commit-date: 2024-06-10
host: aarch64-apple-darwin
release: 1.79.0
LLVM version: 18.1.7
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by joboet** [comment]
The message describes the problem: the global allocator must not use `thread_local!`, as the implementation of the macro needs to allocate on most platforms.

We may in the future decide to allow this by using the system allocator here, but this is fundamentally just the tip of the iceberg: nearly every API in `std` may allocate – I'd argue that you should not use `std` at all when implementing your own global allocator.

**Comment by workingjubilee** [comment]
>  Grepping the rust repo returns nothing for that error either, 

@MarinPostma You are searching overly specifically. The first part, "fatal runtime error", is an error from `rtabort!`:

https://github.com/rust-lang/rust/blob/a299aa5df79dd8e5a1405b97ddd7b367b61eecc6/library/std/src/rt.rs#L39-L42

The second part is inside the TLS dtor registration, currently:

https://github.com/rust-lang/rust/blob/a299aa5df79dd8e5a1405b97ddd7b367b61eecc6/library/std/src/sys/thread_local/destructors/list.rs#L4-L13

**Comment by MarinPostma** [comment]
@workingjubilee that's not the one, notice the absence of "in destructor"

**Comment by ChrisDenton** [comment]
Yes, the error message has been tweaked since then but it's still the same error condition. Here's where it is on the 1.79 branch https://github.com/rust-lang/rust/blob/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys/pal/unix/thread_local_dtor.rs#L105-L109

**Comment by workingjubilee** [comment]
there are actually 5 copies of it on the 1.79 branch.

which is why the refactoring that made there be only one.

**Comment by workingjubilee** [comment]
doesn't seem to be anything to fix here, currently?
