### ISSUE TITLE
sleep should have nanosecond precision

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#12690]
This would be a backwards incompatible change to the API.

**Comment by mahkoh** [comment]
This is an implementation issue but not an implementation detail. Changing this will change the behavior of sleeping programs. The behavior is hardly even documented.

**Comment by steveklabnik** [comment]
Triage: `sleep` now takes a `Duration`, and so will grow a nanosecond precision when `Duration` does.

**Comment by alexcrichton** [comment]
Oh this is actually done, `Duration` has nanosecond precision.

**Comment by z3t0** [comment]
Hi all, just wanted to ask it seems  that sleep() does not sleep to the nanosecond precision?
