### ISSUE TITLE
Left-padding using format! does not work when using a fmt::Display as the argument

### ISSUE THREAD

**Issue by silvasch** [rust-lang/rust#127088]
I tried this code:

```rust
#[derive(Default)]
struct Location {
    line: usize,
    column: usize,
}

impl std::fmt::Display for Location {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> Result<(), std::fmt::Error> {
        write!(f, "{}:{}", self.line, self.column)
    }
}

fn main() {
    println!("{: >8}", Location::default());
    println!("{: >8}", Location::default().to_string());
}
```

I expected to see this happen: The code should print the following output:

```
     0:0
     0:0
```

Instead, the code prints:

```
0:0
     0:0
```

The `format!` macro doesn't left-pad the an argument if it is not a string.

### Meta

`rustc --version --verbose`:
```
rustc 1.79.0 (129f3b996 2024-06-10)
binary: rustc
commit-hash: 129f3b9964af4d4a709d1383930ade12dfe7c081
commit-date: 2024-06-10
host: x86_64-unknown-linux-gnu
release: 1.79.0
LLVM version: 18.1.7
```

The issue is not fixed on nightly either.

<details><summary>Backtrace</summary>
<p>

No backtrace, as there is no compiler error

</p>
</details>

**Comment by pacak** [comment]
I think that's expected. To efficiently pad - it needs to know in advance how wide the output is going to be. You should be using methods on `Formatter` to get width/alignment and implement padding on your own inside `Display` impl for `Location`.


https://doc.rust-lang.org/std/fmt/struct.Formatter.html

**Comment by silvasch** [comment]
Ok, that makes sense. Maybe this should be documented with a quick warning in https://doc.rust-lang.org/std/fmt/index.html#usage?

**Comment by pacak** [comment]
It is kind of mentioned:

> Note that alignment might not be implemented by some types. In particular, it is not generally implemented for the Debug trait.

**Comment by silvasch** [comment]
Oh yeah. Sorry, I didn't see that.
