### ISSUE TITLE
cannot run cargo because windows CMD error : "[0x7FFBC7A07FA4] ANOMALY: use of REX.w is meaningless (default operand size is 64)"

### ISSUE THREAD

**Issue by pengembaratemporer** [rust-lang/rust#127166]
Dear all,

i am newbie here, trying to compile my second rust program using cargo (being the first program was hello world, compiled using rustc).

1) my environment : in my windows11 CMD, i almost always got additional error message when running any command, the error messages are:
"[0x7FFBC7A07FA4] ANOMALY: use of REX.w is meaningless (default operand size is 64)".

2) problem : 
when i run cargo, it interpret my error messages, so cargo refuses to compile.
=====
```
C:\>cargo run
[0x7FFBC7A07FA4] ANOMALY: use of REX.w is meaningless (default operand size is 64)
[0x7FFBC7A07FA4] ANOMALY: use of REX.w is meaningless (default operand size is 64)
error: failed to parse the cfg from `rustc --print=cfg`, got:
___.exe
lib___.rlib
___.dll
___.dll
___.lib
___.dll
C:\.rustup\toolchains\stable-x86_64-pc-windows-msvc
packed
___
debug_assertions
panic="unwind"
proc_macro
target_abi=""
target_arch="x86_64"
target_endian="little"
target_env="msvc"
target_family="windows"
target_feature="cmpxchg16b"
target_feature="fxsr"
target_feature="sse"
target_feature="sse2"
target_feature="sse3"
target_has_atomic="128"
target_has_atomic="16"
target_has_atomic="32"
target_has_atomic="64"
target_has_atomic="8"
target_has_atomic="ptr"
target_os="windows"
target_pointer_width="64"
target_vendor="pc"
windows
[0x7FFBC7A07FA4] ANOMALY: use of REX.w is meaningless (default operand size is 64)


Caused by:
  failed to parse `[0x7FFBC7A07FA4] ANOMALY: use of REX.w is meaningless (default operand size is 64)` as a cfg expression: unexpected character `[` in cfg, expected parens, a comma, an identifier, or a string

C:\>
```
=====

3) i try to print cfg : 
rustc --print=cfg > rust_cfg.txt
content of rust_cfg.txt : 
=====
```
debug_assertions
panic="unwind"
target_abi=""
target_arch="x86_64"
target_endian="little"
target_env="msvc"
target_family="windows"
target_feature="cmpxchg16b"
target_feature="fxsr"
target_feature="sse"
target_feature="sse2"
target_feature="sse3"
target_has_atomic="128"
target_has_atomic="16"
target_has_atomic="32"
target_has_atomic="64"
target_has_atomic="8"
target_has_atomic="ptr"
target_os="windows"
target_pointer_width="64"
target_vendor="pc"
windows
[0x7FFBC7A07FA4] ANOMALY: use of REX.w is meaningless (default operand size is 64)
[0x7FFBC7A07FA4] ANOMALY: use of REX.w is meaningless (default operand size is 64)
```
=====

4) question : how to make cargo or rust to ignore the error message ?

thanks.

**Comment by bjorn3** [comment]
Are you on x86_64 or arm64?

**Comment by pengembaratemporer** [comment]
hi,
im on Windows X86_64.

I dont run some simulator / emulator, perhaps its coming from Antivirus which is managed by our IT admin.

Thanks.

**Comment by bjorn3** [comment]
https://github.com/microsoft/terminal/issues/6391 is another report with the exact same message. There it was caused by TrendMicro. And in https://stackoverflow.com/questions/36873664/anomaly-meaningless-rex-prefix-used it was caused by a component of AMD's graphics driver.

**Comment by pengembaratemporer** [comment]
thanks for the hints.
for the time being, can i run cargo with this error message around ?

meanwhile, i will try to follow this microsoft terminal suggestion to try our luck.

thanks.

**Comment by bjorn3** [comment]
> for the time being, can i run cargo with this error message around ?

Not easily. Whatever is emitting these messages is messing up the output of a rustc invocation that cargo parses to figure out essential information for being able to build anything at all. At best you could build your own cargo and patch it to filter out these extra messages.

**Comment by pengembaratemporer** [comment]
understood. So i need to overcome the problem then start try again from there.

Thanks.
