### ISSUE TITLE
fmt bug for tuple type access

### ISSUE THREAD

**Issue by He1pa** [rust-lang/rust#127198]
I tried this code:

```rust
fn main() {
    type Foo = ((i32, i32), i32);
    let a: Foo = ((1, 1), 1);
    let b = a.0.0;
}
```
And i used fmt(both `rust analyzer` and `cargo fmt`)

I expected to see this happen: 
```rust
fn main() {
    type Foo = ((i32, i32), i32);
    let a: Foo = ((1, 1), 1);
    let b = a.0.0;
}
```

Instead, this happened:
```rust
fn main() {
    type Foo = ((i32, i32), i32);
    let a: Foo = ((1, 1), 1);
    let b = a.0 .0;
}
```
In `a.0 .0`，There's an extra space here.
### Meta

`rustc --version --verbose`:
```
rustc 1.76.0-nightly (3a85a5cfe 2023-11-20)
binary: rustc
commit-hash: 3a85a5cfe7884f94e3cb29a606913d7989ad9b48
commit-date: 2023-11-20
host: aarch64-apple-darwin
release: 1.76.0-nightly
LLVM version: 17.0.5
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by y21** [comment]
The extra space used to be necessary in older versions of Rust where `tuple.0.0` [was a syntax error](https://godbolt.org/z/GT16nGqq3), and (to my knowledge) rustfmt generally won't change formatting later on, at least with the default `version = "One"`.

If you set `version = "Two"` in your rustfmt.toml file, it should format this without the extra space as you expect.

See https://github.com/rust-lang/rustfmt/issues/4355#issuecomment-723764276 for more context

**Comment by workingjubilee** [comment]
Duplicate with https://github.com/rust-lang/rustfmt/issues/4779
