### ISSUE TITLE
rustdoc: support for precise capturing

### ISSUE THREAD

**Issue by fmease** [rust-lang/rust#127228]
Source:

```rs
#![feature(precise_capturing)]

pub fn demo(_: &str) -> impl Sized + use<> {}
```

Current rendered output (both HIR-based and middle-based) below (issue: dropping the precise capturing arg):

```rs
pub fn demo(_: &str) -> impl Sized
```

Tracking:

- https://github.com/rust-lang/rust/issues/123432

**Comment by fmease** [comment]
I consider this issue to be **partially blocked**: Please don't try to add `use<>` support for inline-cross crate-reexports — more generally: middle-based cleaning — before I've fixed #113015 (which should happen _very_ soon!).

Note that `use<>` doesn't get preserved post-HIR IINM, so it'd be non-trivial to impl anyway.

**Comment by fmease** [comment]
Furthermore, there's some design wiggle room which we should probably discuss in a T-rustdoc meeting (I might add it to the agenda later).

Namely, with the edition differences around opaque type captures it might make sense for the rendered output to deviate from the actual source code as written by the user and provide a 'normalized view' that's edition-agnostic (e.g., always listing captures explicitly, etc. etc.).

**Comment by compiler-errors** [comment]
> Note that use<> doesn't get preserved post-HIR IINM, so it'd be non-trivial to impl anyway. To clarify, while it's possible to recover the list of captured regions from rustc_middle::ty data (via variance data: bivariant means not captured IIRC — maybe that's only true for TAITs not RPITs, haven't double-checked), it won't necessarily coincide with what the user wrote literally.

I think we could/should probably just expose it as a query which is encoded in the crate.
