### ISSUE TITLE
`Hash` implementation for `Path` ignores path separators

### ISSUE THREAD

**Issue by zanieb** [rust-lang/rust#127254]
I tried [this code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=467c0f7aedcfbfb484c9ca1ec65ff406):

```rust
use std::path::PathBuf;
use std::hash::{DefaultHasher, Hasher, Hash};

fn main() {
    let x = PathBuf::from("hello/world");
    let y = PathBuf::from("helloworld");
    
    let mut hasher = DefaultHasher::new();
    x.hash(&mut hasher);
    println!("{}", hasher.finish());

    let mut hasher = DefaultHasher::new();
    y.hash(&mut hasher);
    println!("{}", hasher.finish());
}
```

I expected to see this happen: Different hashes since these represent different paths.

Instead, this happened: The hashes are equal.

This makes sense for redundant path separators (e.g. `//`), but not for _all_ path separators.

----

I added a test case to the standard library — which fails.

```diff
diff --git a/library/std/src/path/tests.rs b/library/std/src/path/tests.rs
index 92702b395df..ed945a764c5 100644
--- a/library/std/src/path/tests.rs
+++ b/library/std/src/path/tests.rs
@@ -1566,6 +1566,13 @@ macro_rules! tc (
     relative_from: Some("bar")
     );
 
+    tc!("foo/bar", "foobar",
+    eq: false,
+    starts_with: false,
+    ends_with: false,
+    relative_from: None
+    );
+
     tc!("foo/bar/baz", "foo/bar",
     eq: false,
     starts_with: true,
```

```
---- path::tests::test_compare stdout ----
thread 'path::tests::test_compare' panicked at library/std/src/path/tests.rs:1569:5:
"foo/bar" == "foobar", expected false, got 4111386826608627770 and 4111386826608627770
```

The relevant code is probably around https://github.com/rust-lang/rust/blob/6292b2af620dbd771ebb687c3a93c69ba8f97268/library/std/src/path.rs#L3112-L3114 which last changed in https://github.com/rust-lang/rust/commit/45082b077b4991361f451701d0a9467ce123acdf. If I revert that commit, the error persists.  It looks like the relevant change is https://github.com/rust-lang/rust/commit/a083dd653af0f7f46ba6058ab51e1f9d6a2aca7d, if I revert that commit the test passes. This was the solution I opted for downstream (in https://github.com/astral-sh/ruff/pull/12159) before performing this investigation.

### Meta

I tested this on stable (1.79.0), nightly (1.81.0), and on `master` (6292b2af620dbd771ebb687c3a93c69ba8f97268).

Discovered via https://github.com/astral-sh/ruff/issues/12158

**Comment by the8472** [comment]
`Hash` is not a cryptographic hash, so it does not promise to promise a collision probability so low that practically all inputs map to distinct outputs. So if the correctness of your program relies on the absence of collisions then it's your program that's wrong, not `Hash`.

There may be some quality-of-implementation argument about avoiding collisions for data patterns that are likely to coexist.
I'm not sure if it is the case here, and even if it is it's also a matter of making such a avoidance fast. The current code is optimized for speed.

**Comment by the8472** [comment]
> I think that's a fair point, but the current implementation already goes out if its way to create equal hashes for paths like foo/./bar and foo/bar — why is foobar and foo/bar different? 

The difference is that `Hash` is a companion for `Eq`. If things compare equal then they _must_ hash the same because that's what hashmaps rely on. `foo/./bar` and `foo/bar` do compare equally because `Components` normalizes the dot away. Therefore they must hash equally, which is why Hash must spend effort on that.

Things comparing inequal does not require the Hash to be different. Instead it's only a matter of quality-of-implementation whether they produce distinct hashes, not a matter of correctness.

**Comment by zanieb** [comment]
That's a great point, thanks for clarifying. I agree this is not a "correctness" problem, but more of a practical consideration for the hashing algorithm.
