### ISSUE TITLE
`tarpaulin` and check-cfg

### ISSUE THREAD

**Issue by Urgau** [rust-lang/rust#127271]
Some of the crates I'm developing use 

```
#[cfg(not(tarpaulin))
```

as recommended here: [Ignoring Code in Files (Tarpaulin Readme)](https://github.com/xd009642/tarpaulin?tab=readme-ov-file#ignoring-code-in-files)

It seems other projects do this too: [GitHub Code Search](https://github.com/search?type=code&auto_enroll=true&q=%23%5Bcfg%28not%28tarpaulin_include%29%29%5D)

The recommended Cargo Toml section:

```
[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }
```

does not fix this.

Neither does:

```
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(not(tarpaulin_include))'] }
```

because:

```
error: invalid `--check-cfg` argument: `cfg(not(tarpaulin_include))`
  |
  = note: `not(tarpaulin_include)` is invalid
  = note: `cfg()` arguments must be simple identifiers, `any()` or `values(...)`
  = note: visit <https://doc.rust-lang.org/nightly/rustc/check-cfg.html> for more details
```

Maybe this should be done differently on tarpaulin's side, or I can just edit my build.rs. But maybe this should be supported.

_Originally posted by @barafael in https://github.com/rust-lang/rust/issues/124800#issuecomment-2205885360_

**Comment by Urgau** [comment]
@barafael I tried reproducing the issue locally but I'm unable to do so.

I created a new Cargo project added `#[cfg(not(tarpaulin_include)]` to the `add` function, then did `cargo +nightly check`, got the warning, then added the cfg to the `Cargo.toml`
```diff
[package]
name = "my_lib"
version = "0.1.0"
edition = "2021"

[dependencies]

+ [lints.rust]
+ unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }
```
and the re-did `cargo +nightly check` the warning was successfully removed.

Did you check on `beta` or `nightly`? Are the beta/nightly version update to date?
If the issue still reproduce, could you provide a reproducer code.

**Comment by taiki-e** [comment]
> Some of the crates I'm developing use
> 
> ```
> #[cfg(not(tarpaulin))
> ```

This is "tarpaulin".

> [lints.rust]
> unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }

And this adds "tarpaulin_include" , not "tarpaulin".

**Comment by barafael** [comment]
> And this adds "tarpaulin_include" , not "tarpaulin".

correct, my bad. It's #![cfg(not(tarpaulin_include))]

**Comment by barafael** [comment]
@Urgau never mind, I got confused, all works as expected. Thanks!
