### ISSUE TITLE
Compiler should automatically replace heap allocations in a loop

### ISSUE THREAD

**Issue by TS60** [rust-lang/rust#127298]
It seems that the Rust compiler does not automatically replace heap allocations in a loop that are not returned like `let mut v = Vec::new(); v.push(some_value);` by a hidden `buffer` that does `buffer.clear(); buffer.push(some_value)` instead. I think this is quite typical user code which can slow down by factor 3 or more. Thus, I assume many average programs can get optimized quite much if this pattern would get implemented automatically.

[Here](https://github.com/theodore-s-beers/feruca/pull/5/files) is an example code where I first noticed the problem, it shows the problem in detail.
I had a feeling that it should be the task of the compiler to do this optimization.

**Comment by bjorn3** [comment]
If I understand your code correctly, the loop is outside of the function that does the allocations. That means there is nowhere for rustc to store the allocation for reuse in the next call. Optimizations can't change the layout of types as the memory layout is observable, may have been observed at const eval time already and the type may be passed to separately compiled code which doesn't have the change applied. Additionally for rustc to prove that a fresh Vec and reusing an existing Vec after a clear call is equivalent is very hard.

**Comment by TS60** [comment]
Thanks for explaining the problem, I thought it would be possible to achieve this without changing the layout by guaranteeing that the `Vec::new` is always the same as the first Vec, even though that would require a custom Vec type.
Indeed, the memory growing could become problematic for specific use cases but also the factor 3.5 slowdown is problematic, I think.

At least good to know that such "simple" optimizations are impossible in Rust.
