### ISSUE TITLE
Refactor rvalue datums in trans to carry the expression id from which they originated

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#12731]
Currently in trans rvalue datums do not know the expr id from which they originated. As a result, many parts of the code must track this separately, so that if we have to add a temporary cleanup, we can select the appropriate cleanup scope (which is a function of the trans id). I've been wanting for a while to refactor things so that the `Rvalue` type carries this node-id along with it.

cc @eddyb, this kind of refactoring might interest you

**Comment by steveklabnik** [comment]
@nikomatsakis is this refactoring still relevant?

**Comment by steveklabnik** [comment]
Given that it's been a year with no update, I'm giving it a close. @nikomatsakis let me know if you think it's still relevant to keep open.

**Comment by nikomatsakis** [comment]
On Tue, Feb 02, 2016 at 10:27:23AM -0800, Steve Klabnik wrote:
> Given that it's been a year with no update, I'm giving it a close. @nikomatsakis let me know if you think it's still relevant to keep open.

Nah, MIR makes this irrelevant.
