### ISSUE TITLE
regression: borrowed data escapes outside of the method

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#127342]
* https://crater-reports.s3.amazonaws.com/beta-1.80-4/beta-2024-06-22/reg/rene-0.1.0/log.txt

```
[INFO] [stdout] error[E0521]: borrowed data escapes outside of method
[INFO] [stdout]    --> src/geometries/contour/difference.rs:377:43
[INFO] [stdout]     |
[INFO] [stdout] 363 |       fn difference(self, other: &Polygon<Scalar>) -> Self::Output {
[INFO] [stdout]     |                           -----  - let's call the lifetime of this reference `'2`
[INFO] [stdout]     |                           |
[INFO] [stdout]     |                           `other` is a reference that is only valid in the method body
[INFO] [stdout] ...
[INFO] [stdout] 377 |           let boxes_have_common_continuum = to_boxes_have_common_continuum(
[INFO] [stdout]     |  ___________________________________________^
[INFO] [stdout] 378 | |             &bounding_boxes,
[INFO] [stdout] 379 | |             &other_bounding_box,
[INFO] [stdout] 380 | |         );
[INFO] [stdout]     | |         ^
[INFO] [stdout]     | |         |
[INFO] [stdout]     | |_________`other` escapes the method body here
[INFO] [stdout]     |           argument requires that `'2` must outlive `'static`
[INFO] [stdout]     |
[INFO] [stdout] note: due to current limitations in the borrow checker, this implies a `'static` lifetime
[INFO] [stdout]    --> src/operations.rs:565:39
[INFO] [stdout]     |
[INFO] [stdout] 565 |     for<'a> &'a bounded::Box<Scalar>: Relatable,
[INFO] [stdout]     |                                       ^^^^^^^^^
```

**Comment by compiler-errors** [comment]
This is (also) https://github.com/rust-lang/rust/pull/119820, cc @lcnr (though we probably already have this listed as a regression in that one)

**Comment by apiraino** [comment]
By reading this [comment](https://github.com/rust-lang/rust/pull/119820#issuecomment-1979606237) in #119820 I infer that we accepted that change but we wanted to fix all crates regressions before the release.

I'll tentatively assign a `P-high` (if my understanding is correct).

WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23127342.20regression.3A.20borrowed.20data.20escapes.20outside.20of.20the.20me.E2.80.A6)).

@rustbot label -I-prioritize +P-high

**Comment by lqd** [comment]
> but we wanted to fix all crates regressions before the release.

This crate was indeed already fixed in https://github.com/lycantropos/rene/pull/5, and the only released crates.io version doesn't contain the fix.

**Comment by apiraino** [comment]
Note to self: I think this issue can be closed but waiting for consensus

**Comment by lcnr** [comment]
the breakage has been reverted entirely now, so regardless of the fix, this will continue to work
