### ISSUE TITLE
Consistency in file names

### ISSUE THREAD

**Issue by gu5e** [rust-lang/rust#127465]
Why does some files in the `.github` folder have the `.yaml` extension and some have the `.yml`.

**Comment by gu5e** [comment]
I'm open to renaming the files.

**Comment by the8472** [comment]
Both are valid extensions. Different authors may choose different outcomes. There does not seem any advantage to preferring one over the other.

**Comment by gu5e** [comment]
But it can get confusing sometimes, like if some is adding a new yaml file, what are they gonna choose.

**Comment by the8472** [comment]
Whatever they prefer. If they have no preference they can flip a coin. Imo it's not worth to spend much time on this.

Github does not recommend one over the other either: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#about-yaml-syntax-for-workflows
