### ISSUE TITLE
Tidy is incredibly slow

### ISSUE THREAD

**Issue by Nilstrieb** [rust-lang/rust#127453]
Running `git push` with the tidy check hook just hangs. `perf top` shows that it's doing lots of string operations:
```
 34.53%  rust-tidy         [.] alloc::str::<impl str>::to_uppercase
  12.34%  rust-tidy         [.] core::unicode::unicode_data::conversions::to_upper
  10.02%  rust-tidy         [.] alloc::string::String::push
   8.63%  libc.so.6         [.] __memcmp_avx2_movbe
```
`x test tidy` takes 97s
???

**Comment by Nilstrieb** [comment]
#127428 is at fault. that cute `to_uppercase` is NOT very efficient :D
@donno2048 @albertlarsan68 (don't worry, I'll put up a fix)

**Comment by Nilstrieb** [comment]
yeah, that array contains 2084 different elements. moving the `to_uppercase` out of the loop still takes 24s. i'm just gonna revert this commit, the regexset was made for this.

**Comment by donno2048** [comment]
I still think we should not revert the commit as it fixes issues with case alteration.

We should simply do the check on `trimmed` only if the regex test yields `True`.

**Comment by Nilstrieb** [comment]
sounds fine, feel free to do a follow-up doing that. I just wanted to get something working again quickily

**Comment by jieyouxu** [comment]
> I still think we should not revert the commit as it fixes issues with case alteration.

It's perfectly fine to revert then reland the fixes!

**Comment by Nilstrieb** [comment]
has been fixed. the new PR to make it better is open
