### ISSUE TITLE
`pub` items in binary crates should not be excluded from `dead_code` lint

### ISSUE THREAD

**Issue by alice-i-cecile** [rust-lang/rust#127497]
When adding `pub` to a binary crate, the item is excluded from `dead_code` analysis.

While this is the right behavior for libraries, it is silly (and frustrating), because binaries cannot be used as dependencies. Instead, you have to use `pub(crate)` everywhere, to ensure that dead code analysis works as planned.

### Meta

Reproduced on `rustc 1.79`

**Comment by mu001999** [comment]
Is this same to #74970?

**Comment by alice-i-cecile** [comment]
Yep, fixing that issue will resolve that.
