### ISSUE TITLE
apple-m1 detected as the native CPU for rustc on apple-m2

### ISSUE THREAD

**Issue by betelgeuse** [rust-lang/rust#127448]
I tried this command

```
$ rustc --print target-cpus | head -n 2
Available CPUs for this target:
    native          - Select the CPU of the current host (currently apple-m1).
```

I expected to see this happen: *explanation*

I ran the command on a apple-m2 Macbook Pro so that should be selected as the native cpu.

Instead, this happened: *explanation*

apple-m1 was selected

### Meta

`rustc --version --verbose`:
```
rustc 1.81.0-nightly (ed7e35f34 2024-07-06)
binary: rustc
commit-hash: ed7e35f3494045fa1194be29085fa73e2d6dab40
commit-date: 2024-07-06
host: aarch64-apple-darwin
release: 1.81.0-nightly
LLVM version: 18.1.7
```

</p>
</details>

Linking tracker [#73908](https://github.com/rust-lang/rust/issues/73908)

**Comment by ehuss** [comment]
Thanks for the report! I believe this will be fixed when we update to LLVM 19 via https://github.com/llvm/llvm-project/pull/82100 (see [schedule](https://discourse.llvm.org/t/llvm-19-release-schedule-and-planning/79828)).

**Comment by nikic** [comment]
Can somebody on M2 please confirm that this is indeed fixed on current nightly?

**Comment by lukaslueg** [comment]
```raw
$ rustup run nightly rustc --version
rustc 1.82.0-nightly (28a58f2fa 2024-07-31)
```
```raw
$ sysctl -n machdep.cpu.brand_string
Apple M3 Pro
```

```raw
$ rustup run nightly rustc --print target-cpus | head -n2
Available CPUs for this target:
    native          - Select the CPU of the current host (currently apple-m3).
```

For comparison
```raw
$ rustup run stable rustc --print target-cpus | head -n2
Available CPUs for this target:
    native          - Select the CPU of the current host (currently apple-m1).
```

**Comment by nikic** [comment]
Awesome, thanks for the confirmation!
