### ISSUE TITLE
`std::fs::remove_dir_all` fails if any of the intermediate file deletions fails with `ENOENT`

### ISSUE THREAD

**Issue by tbu-** [rust-lang/rust#127576]
https://github.com/rust-lang/rust/blob/d81987661a06ae8d49a5f014f81824c655e87768/library/std/src/sys/pal/unix/fs.rs#L2144

https://github.com/rust-lang/rust/blob/d81987661a06ae8d49a5f014f81824c655e87768/library/std/src/sys/pal/unix/fs.rs#L2156-L2159

**Comment by tgross35** [comment]
Are you suggesting that this should continue removing files if one fails, or that specifically ENOENT on a file should be considered a success?

@rustbot label +T-libs +C-bug +O-unix +A-filesystem -needs-triage

**Comment by tgross35** [comment]
Just checked what rm does when this happens (by making a lot of files and having two `rm`s race), it indeed ignores ENOENT:

```text
...
unlinkat(4, "768458", 0)                = -1 ENOENT (No such file or directory)
unlinkat(4, "768461", 0)                = 0
unlinkat(4, "768463", 0)                = -1 ENOENT (No such file or directory)
unlinkat(4, "768472", 0)                = 0
unlinkat(4, "768476", 0)                = -1 ENOENT (No such file or directory)
unlinkat(4, "768479", 0)                = -1 ENOENT (No such file or directory)
unlinkat(4, "768485", 0)                = -1 ENOENT (No such file or directory)
unlinkat(4, "768490", 0)                = -1 ENOENT (No such file or directory)
unlinkat(4, "768496", 0)                = -1 ENOENT (No such file or directory)
unlinkat(4, "768501", 0)                = 0
unlinkat(4, "768504", 0)                = 0
unlinkat(4, "768506", 0)                = 0
...
$ echo $?
0
```

So doing the same seems probably fine here, think this should be pretty easy. Ideally this should have a regression test, I'm not sure what the best way to do that is - @tbu- how did you identify or reproduce this?

@rustbot label +E-easy

**Comment by tbu-** [comment]
I looked at the code for TOCTOU issues and found this particular problem. Nothing automatable I'm afraid.

**Comment by tbu-** [comment]
> Are you suggesting that this should continue removing files if one fails but still report an error, or that specifically ENOENT on a file should be considered a success?

Specifically `ENOENT` should be considered a success.

> I assume this can happen if racing with another removal operation, not sure if there is a precedent for what to do here (rm?).

Yes, this is about racing. E.g. `std::fs::create_dir_all` also succeeds when `EEXISTS` is returned for `mkdir`.

**Comment by ChrisDenton** [comment]
This seems like it's just an implementation bug so fixes would be welcome. On Windows we do ignore not found errors when deleting files in `remove_dir_all`.
