### ISSUE TITLE
Panic in std

### ISSUE THREAD

**Issue by Trini7** [rust-lang/rust#127563]
version: nightly-2023-11-22
os: centos-7

panic:
thread '' panicked at library/std/src/sys/unix/net.rs:50:76:
called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 4, error_len: Some(1) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '' panicked at library/std/src/sys/unix/net.rs:50:76:
called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 4, error_len: Some(1) }
thread '' panicked at library/std/src/sys/unix/net.rs:50:76:
called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 4, error_len: Some(1) }
thread '' panicked at library/std/src/sys/unix/net.rs:50:76:
called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 4, error_len: Some(1) }

**Comment by bjorn3** [comment]
You are using a nightly that is over half a year old. Try using the latest nightly to see if it reproduces. If it does, please set `RUST_BACKTRACE=1` and report back the printed backtrace as well as the project on which you get this panic.

**Comment by Trini7** [comment]
Based on my testing, the latest version also has this issue.

**Comment by eggyal** [comment]
It would appear that your libc's [`gai_strerror`](https://www.man7.org/linux/man-pages/man3/gai_strerror.3p.html) function is not returning a UTF-8 encoded string (the fifth byte is invalid).

**Comment by Nilstrieb** [comment]
Can you share some of your system config, especially your locale? gai_strerror returning invalid UTF-8 is certainly not something expected by std.

**Comment by Trini7** [comment]
<img width="955" alt="image" src="https://github.com/rust-lang/rust/assets/12758600/257fb3ea-420d-4f63-a603-ec1d28724556">

**Comment by Trini7** [comment]
> Can you share some of your system config, especially your locale? gai_strerror returning invalid UTF-8 is certainly not something expected by std.

It’s a chinese locale.

**Comment by Nilstrieb** [comment]
Which Chinese locale exactly? Could you show the values of the `LC_` environment variables?

**Comment by Trini7** [comment]
Sorry, the environment is no longer available, but it seems that using unwrap in net.rs:50:76 is too risky.
