### ISSUE TITLE
Using `&raw const` instead of `&raw mut` does not offer a suggestion fix

### ISSUE THREAD

**Issue by cyrgani** [rust-lang/rust#127562]
### Code

```Rust
fn main() {
    let val = 2;
    let ptr = &raw const val;
    unsafe { *ptr = 3; }
}
```

### Current output
```
error[E0594]: cannot assign to `*ptr`, which is behind a `*const` pointer
 --> src/main.rs:4:14
  |
4 |     unsafe { *ptr = 3; }
  |              ^^^^^^^^ `ptr` is a `*const` pointer, so the data it refers to cannot be written

For more information about this error, try `rustc --explain E0594`.
```

### Desired output
```
error[E0594]: cannot assign to `*ptr`, which is behind a `*const` pointer
 --> src/main.rs:4:14
  |
4 |     unsafe { *ptr = 3; }
  |              ^^^^^^^^ `ptr` is a `*const` pointer, so the data it refers to cannot be written
  |
help: consider changing this to be a mutable pointer
  |
3 |     let ptr = &raw mut val;
  |                    ~~~

For more information about this error, try `rustc --explain E0594`.
```
### Rationale and extra context
The current error message does not include a suggestion for how to fix it.

### Rust Version

```
1.85.0-nightly (2024-12-14 0aeaa5eb22180fdf12a8)
```

### Anything else?
EDIT 1: updated since `addr_of!` and `addr_of_mut!` diagnostics are not incorrect anymore due to #127675 
EDIT 2: updated as #134224 removed the invalid suggestion

**Comment by chenyukang** [comment]
I think the current suggestion in suggest the code like this:

```rust
    let ptr = &mut val;
```

**Comment by chenyukang** [comment]
oh, the suggestion's code comes from here:

https://github.com/chenyukang/rust/blob/c8ed5c50edfd1b721c0541fa614864179251aaac/library/core/src/ptr/mod.rs#L2208

I think we should not suggest to change the library code here.

**Comment by tesuji** [comment]
I have playground link that represents the problem above: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=fee632ddd4f51a0390ac6918ef4eff96

However, when I add that code as a regression tests in `tests/ui` directory, the diagnostic suddenly changed to
```rust
error[E0594]: cannot assign to `*ptr`, which is behind a `*const` pointer
  --> $DIR/dont_suggest_raw_pointer_syntax-issue-127562.rs:9:9
   |
LL |         *ptr = 3;
   |         ^^^^^^^^ `ptr` is a `*const` pointer, so the data it refers to cannot be written
   |
help: consider specifying this binding's type
   |
LL |     let ptr: *mut i32 = std::ptr::addr_of!(val);
   |            ++++++++++
```

I don't have any ideas about this differences.

**Comment by chenyukang** [comment]
> ```rust
> binding's type
> ```

This is because when run the test UI, the span here is remaped:
https://github.com/chenyukang/rust/blob/b44a48416d06524da2ea247f1d1973d85ef514f8/compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs#L1452

so the here we get an error and didn't continue the code branch:
https://github.com/chenyukang/rust/blob/b44a48416d06524da2ea247f1d1973d85ef514f8/compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs#L1453

it's weird, maybe another issue need to be fixed.

**Comment by cyrgani** [comment]
Given that `&raw` syntax might get stabilized soon by #127679, suggesting the correct `&raw mut` syntax would become a more feasible option.

**Comment by RalfJung** [comment]
> `&mut raw const $place`

This is completely invalid syntax so just suggesting nothing instead as a first step would already be a good idea.

Suggesting anything that involves references is a really bad idea -- code that uses raw pointers should keep using raw pointers throughout with no intermediate references.

**Comment by Enselic** [comment]
With https://github.com/rust-lang/rust/pull/134244 we now at least don't  suggest invalid syntax.

But it would be even nicer to suggest changing `&raw const val` to `&raw mut val` (which when applied will then suggest changing to `let mut val`).
