### ISSUE TITLE
Opaque type constrainted by function is not seen by static item

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rust#127626]
Feel free to close if duplicated.

```rust
#![feature(type_alias_impl_trait)]

use std::future::Future;

pub struct Foo<F: Future> {
    pub fun: fn() -> F,
}

pub type BarFuture = impl Future;
pub fn bar() -> BarFuture {
    async {}
}

pub static BAZ: Option<Foo<BarFuture>> = None;
```

There can only be one `BarFuture` type, right? If so, `BarFuture` is already constrained by `pub fn bar() -> BarFuture` but for some reason `BAZ` is working in isolation ignoring previous declarations.

```txt
error: item does not constrain `BarFuture::{opaque#0}`, but has it in its signature
  --> src/lib.rs:14:12
   |
14 | pub static BAZ: Option<Foo<BarFuture>> = None;
                ^^^
```

cc @oli-obk

**Comment by oli-obk** [comment]
Yes this is expected behaviour until we get `#[defines(BarFuture)]` attributes. You can work around this by moving the definition and defining use into a helper module: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=55de04ca5a530a763b5663a9c4db07de

**Comment by c410-f3r** [comment]
Thanks @oli-obk !
