### ISSUE TITLE
Readdir iterator fails for vxworks since version 1.70 to 1.78 

### ISSUE THREAD

**Issue by biabbas** [rust-lang/rust#127756]
Here is the program that reproduces this:
```
use std::path::Path;
use std::fs;
use std::io;
fn remove_dir_all_recursive(path: &Path) -> io::Result<()> {
    println!("Read directory");
    let dirs = fs::read_dir(path)?;
    println!("Directory read {:?}",dirs);
    for child in dirs {
        println!("child {:?}",child);
        let child = child?;
        if child.file_type()?.is_dir() {
            remove_dir_all_recursive(&child.path())?;
        } else {
            fs::remove_file(&child.path())?;
        }
    }   
    fs::remove_dir(path)
}
fn main(){
    let args: Vec<String> = std::env::args().collect();
    let directory=&args[1];
    println!("Hello, world - will remove {}",directory);
    let path = Path::new(directory);
    let result = remove_dir_all_recursive(path);
    println!("Result {:?} ",result);
}
```
Output:
![image](https://github.com/user-attachments/assets/4bd07552-bc1d-47c2-b9d5-d6e50aa4eeec)

The test directory is present with child sub directories and folders. The call to readdir is successful, We get segmentation fault while trying to read child files/directories. 

Thank you for any leads.
Note: This somehow works with 1.81 nightly.

Additional test case that fails on vxworks. Traversing the directories.
```
use std::path::Path;
use std::io;
use std::fs::read_dir;

fn traverse_all_recursive(path: &Path) -> io::Result<()> {
    println!("Read directory");
    let dirs = read_dir(path)?;
    println!("Directory read {:?}",dirs);
    for child in dirs {
        println!("Child {:?}",child);
        let child = child?;
        if child.file_type()?.is_dir() {
            println!("Step Into Child Directory: {:?}", child);
            traverse_all_recursive(&child.path())?;
        } else {
           println!("File Name found: {:?}",child)
        }
    } 
    Ok(())
}
fn main(){
    let args: Vec<String> = std::env::args().collect();
    let directory=&args[1];
    println!("Hello, start traversing {}",directory);
    let path = Path::new(directory);
    let result = traverse_all_recursive(path);
    println!("Result {:?} ",result);
}
```

**Comment by workingjubilee** [comment]
no idea. could you bisect it to a specific commit?

**Comment by biabbas** [comment]
> no idea. could you bisect it to a specific commit?
I'm not sure how to do that? Should I check each commit to bisect to a single commit?
I suspect the segmentation fault is due to a type mismatch.

**Comment by compiler-errors** [comment]
> 1.77

The current stable Rust is 1.79. If this bug isn't present on that version, I don't think we fix issues that aren't the current stable release, so I think this issue should just be closed?

**Comment by workingjubilee** [comment]
@biabbas specifically I'm interested in knowing which commit *fixed* this.

@compiler-errors I agree but given that @biabbas has started looking into making sure VxWorks actually functions, and given that severity of the failing case (segfault at runtime), I think confirming that the commit in question is one we would expect to actually fix the error, or if it just is masking it, would be good. There have been large refactors of parts of `std::sys`.

**Comment by biabbas** [comment]
Bisecting it to a particular commit seems very difficult, as for each bisection, sources have to be cross-compiled. Then an example has to be created an run on VxWorks image. Thus using higher versions seems like the better choice.
