### ISSUE TITLE
Illegal instruction when casting a pointer to integer and back

### ISSUE THREAD

**Issue by al13n321** [rust-lang/rust#127708]
Simple program:
```rust
pub enum E {
    A(usize),
    B,
}

fn main() {
    let e = E::B;
    let p: *const E = &e;
    let i = p as u64;

    let p2: *const E = unsafe {std::mem::transmute(i)};
    let e2 = unsafe {&*p2};

    match e2 {
        E::B => std::hint::black_box(()),
        _ => (),
    }
}
```

I expected to see this happen: no crash.
Instead, this happened: crash.

AFAICT, this is legal: have an immutable object, take a pointer to it, cast it to usize and back, and dereference it.

With `opt-level=0` it succeeds. With `opt-level=1` and higher the `main` function gets compiled to a single `ud2` instruction, so the program crashes. Same in https://play.rust-lang.org/ in Release mode as well.

(Replacing the local variable with a `&'static` produced by `Box::leak()` doesn't help.)

### Meta

`rustc --version --verbose`:
```
rustc 1.79.0 (129f3b996 2024-06-10)
binary: rustc
commit-hash: 129f3b9964af4d4a709d1383930ade12dfe7c081
commit-date: 2024-06-10
host: x86_64-unknown-linux-gnu
release: 1.79.0
LLVM version: 18.1.7
```

Build command:
```
rustc bug.rs -o a -C opt-level=1
```

`rustc` 1.77.0 works. 1.78.0 and 1.79.0 crash. In playground, `1.81.0-nightly (2024-07-12 c6727fc9b5c64cefa726)` crashes too.

**Comment by ChrisDenton** [comment]
The trouble is the transmute:

```
let p2: *const E = unsafe {std::mem::transmute(i2)};
```

This loses provenance information. You should use an `as` cast, e.g. `i2 as *const E`. Well, ideally the strict provenance APIs would be used but those are nightly only.

**Comment by al13n321** [comment]
Thanks! I'll assume you're correct and go read about provenance.
