### ISSUE TITLE
rustdoc mangles str literal partially hidden by leading `#` in doctest

### ISSUE THREAD

**Issue by drmason13** [rust-lang/rust#127702]
I have a [minimal repo](https://github.com/drmason13/rustdoc-mangling-repro) demonstrating this bug.

A str literal containing a leading `#` is removed from the doctest visibly, but the str contains the text after the `#`:

```rust
//! let inlined = r#"
//! # this should be hidden by rustdoc
//! this is after the hidden part
//! "#;
```

In the demo repo, running `cargo test` will display something like:

```
[src/lib.rs:12:12] inlined = "\nthis should be hidden by rustdoc\nthis is after the hidden part\n"
[src/lib.rs:12:27] included = "\nthis is after the hidden part\n"
thread 'main' panicked at src/lib.rs:12:1:
assertion `left == right` failed
  left: "\nthis should be hidden by rustdoc\nthis is after the hidden part\n"
 right: "\nthis is after the hidden part\n"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

In the generated documentation, it is indeed hidden:
![cargo doc output with the line first hidden](https://github.com/drmason13/rustdoc-mangling-repro/blob/main/cargo-doc-output.png)

I expected to see this happen: the line prefixed with `#` is *both*
* removed from the str literal value within the test
* hidden from the generated docs output

Instead, this happened:
* only the ` #` is removed from the str literal
* the rest of the line after the ` #` is still included
* the generated docs nevertheless hide the full line

### Meta

`rustc --version --verbose`:
```
rustc 1.81.0-nightly (c6727fc9b 2024-07-12)
binary: rustc
commit-hash: c6727fc9b5c64cefa7263486497ee95e529bd0f8
commit-date: 2024-07-12
host: x86_64-unknown-linux-gnu
release: 1.81.0-nightly
LLVM version: 18.1.7
```
and stable too:
```
rustc 1.79.0 (129f3b996 2024-06-10)
binary: rustc
commit-hash: 129f3b9964af4d4a709d1383930ade12dfe7c081
commit-date: 2024-06-10
host: x86_64-unknown-linux-gnu
release: 1.79.0
LLVM version: 18.1.7
```

**Comment by eggyal** [comment]
Prefixing a line with `#` in a doctest generally hides it from the generated documentation while leaving it (with `#` prefix stripped) in the code that is run.

Perhaps within string literals `#` should not have any special meaning, and therefore the line would *both* appear in the generated documentation *and* be part of the string literal (including the `#` character) in the code that is run; but I can't see the logic for the behaviour you expected (line omitted from both documentation and string literal)?

**Comment by drmason13** [comment]
Oh of course you are right! 

That's my bad, **I was indeed confused**.

I think I was first surprised that the str literal was affected by the `#` at all, and then remembered that `#` was used to hide stuff and then forgot the reason was to hide _actual code that wanted executing_ so of course it is kept in the doctest.

In str literals this is often unhelpful, but I think being able to escape it is fine as a workaround.

For the cases where you *need* a long winded multiline str literal to pass a test, but want to hide it in the docs for brevity, it's worth keeping the current (correct) behaviour.

Thank you for kindly pointing that out to me. Shame, I had such a great repro of this behaving exactly as intended :D
