### ISSUE TITLE
text coloring for the println! macro

### ISSUE THREAD

**Issue by AlphaCodingPilot** [rust-lang/rust#127759]
The `println!` macro should allow colored text for console output. This would be especially useful because the best alternative I know is the [colored](https://crates.io/crates/colored) library, where you can create colored strings, which is annoying since you need an extra data type. Since `println!` is already a macro, this could be way simpler, I think. The syntax could look similar to python:
`println!("[red]this is red text [blue]this is blue text [default]this is normal text")`

**Comment by matthiaskrgr** [comment]
theres no need for libraries etc:
`eprintln!("\u{001B}[31m {}", "red") }`
see 
https://stackoverflow.com/questions/5762491/how-to-print-color-in-console-using-system-out-println
