### ISSUE TITLE
Emacs rust-mode should have its own repository

### ISSUE THREAD

**Issue by ramnes** [rust-lang/rust#12786]
Since partial cloning does not exist with git, any user interested in using and/or contributing to rust-mode have the choice between clone the whole repository for 1% of it, or directly download the file (thanks to this GitHub feature).

So, in answer to #1490, I really think that rust-mode should have its own repository, with its own contributors, issues, PR, etc. It still could be a part of this repository as a **submodule**, but I can't see the point of handling it here.

More generally, I don't understand why projects that are not part of Rust source code are in this repository.

**Comment by steveklabnik** [comment]
I am hoping to do this very soon: http://discuss.rust-lang.org/t/moving-editor-highlighting-into-their-own-repos/1395

**Comment by kmcallister** [comment]
https://github.com/rust-lang/rust-mode

**Comment by ramnes** [comment]
Awesome!
