### ISSUE TITLE
`tests/run-make/print-target-list` `--print=sysroot` check fails for experimental llvm targets

### ISSUE THREAD

**Issue by jieyouxu** [rust-lang/rust#127895]
In #127877 @Rejyr noticed `tests/run-make/print-target-list` was failing for `csky-unknown-linux-gnuabiv2` (and other experimental llvm components) on the `x86_64-gnu-llvm-17` CI builder with

```
# snip
error: could not create LLVM TargetMachine for triple: csky-unknown-linux-gnuabiv2: No available targets are compatible with triple "csky-unknown-linux-gnuabiv2"
# snip
```

#125702 (specifically https://github.com/rust-lang/rust/pull/125702#issuecomment-2136746149) it was already noticed that `tests/run-make/print-target-list` seemed to fail for `csky-unknown-linux-gnuabiv2`.

Is this expected? Or what is the expected test behavior when

```
rustc --target csky-unknown-linux-gnuabiv2 --print sysroot
```

is ran (on the `x86_64-gnu-llvm-17` CI builder)?

Or is it expected that we should skip trying to run this check for the `csky-unknown-linux-gnuabiv2` and other experimental llvm component targets?

---

Update: this is also true for experimental llvm components `avr`, `m68k`, `csky` and `xtensa`, not too sure what the correct behavior is. Currently these targets are skipped by `print-target-list`'s `--print=sysroot` check.

**Comment by Dirreke** [comment]
Is there any COMPILETEST_NEEDS_ALL_LLVM_COMPONENTS set by us for this jobs?. It seems like the same issue. I will check it later.

**Comment by Dirreke** [comment]
Well, I'm not familiar with rmake.

However, the right logic should be like: 

If `COMPILETEST_NEEDS_ALL_LLVM_COMPONENTS` is not set and `LLVM_COMPONENTS` do not have the `csky`, then we could skip it.

`COMPILETEST_NEEDS_ALL_LLVM_COMPONENTS` is set at  [src/ci/run.sh](https://github.com/rust-lang/rust/blob/4bb2f278617e5498ac9a4776d3e1268154c500c5/src/ci/run.sh#L93-L97), and it is only used at [src/tools/compiletest/src/header.rs](https://github.com/rust-lang/rust/blob/4bb2f278617e5498ac9a4776d3e1268154c500c5/src/tools/compiletest/src/header.rs#L1416-L1425) now.

**Comment by jieyouxu** [comment]
Ah thank you, that sounds about right.
