### ISSUE TITLE
lstat implementation on windows

### ISSUE THREAD

**Issue by lbonn** [rust-lang/rust#12795]
Link and symlink capabilities exist on ```win32``` platform, yet ```lstat```'s implementation is still missing.

Some fs operations need it to work properly, for example ```rmdir_recursive``` (#12573)

**Comment by steveklabnik** [comment]
```
src/libstd/sys/unix/fs2.rs:pub fn lstat(p: &Path) -> io::Result<FileAttr> {
```

Seems to exist now. :confetti_ball:
