### ISSUE TITLE
CStr::from_ptr() crashes the program with a segfault when loading a string from memory after passing it in a global_asm!() function.

### ISSUE THREAD

**Issue by 20943204920434** [rust-lang/rust#127986]
### Problem

I can't make a CStr object from a raw pointer using CStr::from_ptr() method, as it crashes causing segfault. The important thing here is that the program uses AMD64-Assembly through global_asm!() macro, but the code appears valid when compiling it using stable rust. I couldn't reproduce it without assembly.

### Code

```rust
use std::arch::global_asm;
use std::ffi::CStr;
use std::ffi::CString;

global_asm!(include_str!("parser.asm"), sym print);

extern "sysv64" { fn test(string: *mut i8, string_end: *mut i8) -> u64; }

extern "sysv64" fn print(str1: *const i8, str2: *const i8) {
    unsafe {
        println!("{}", CStr::from_ptr(str1).to_str().unwrap());
        println!("{}", CStr::from_ptr(str2).to_str().unwrap());
    }
}

fn wrapper(string: CString){
    unsafe {
        let len = string.count_bytes();
        let pointer = string.into_raw();
        test(pointer, pointer.add(len));
    }
}

fn main() {
    let string = CString::new("?akfjasf=jafkjdf&kjdjdsf=sadsfdf&jgkdfjg=sgdsgdg&asfsnfj=aflmdsa ").unwrap();
    wrapper(string);
}
```
<details>
   <summary>parser.asm contents</summary>

```asm
mask_eq: .string "================================"
mask_an: .string "&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&"
params: .octa 0x00000000000000000000000026262020
.globl test


test:

 		mov byte ptr [rdi], 0x00
		push rax
		push rsi
		push r10
		push rdx

	.lp:    inc rdi
		push rdi

		vpxor ymm0, ymm0, ymm0
		vmovdqu xmm1, [params]
		vpbroadcastb ymm4, [mask_eq]
		vpbroadcastb ymm5, [mask_an]

		vpcmpeqb ymm0, ymm4, [rdi]

		add rdi, 32
		vptest ymm0, ymm0
		jz .lp
		sub rdi, 32

		xor rax, rax
		vpmovmskb eax, ymm0
		bsf eax, eax
		add rdi, rax

		mov byte ptr [rdi], 0x00
		inc rdi
		push rdi
		vpxor ymm0, ymm0, ymm0

		sub rdi, 16
	.lp2:   add rdi, 16

		vpcmpistrm xmm1, [rdi], 0x4
		vptest xmm0, xmm0
		jz .lp2

		xor ecx, ecx
		vpextrd ecx, xmm0, 0
		bsf ecx, ecx
		add rdi, rcx
		mov dx, [rdi]
		mov byte ptr [rdi], 0x00

		mov rax, rdi
		pop rsi
		pop rdi
		push rax
		push dx
		call {}
		cmp rax, -1
		je .exit

		pop dx
		pop rdi
		cmp dl, 0x20
		jne .lp
	.exit:
		pop rdx
		pop r10
		pop rsi
		pop rax
		ret
```

</details>

This is a small program that parses the HTTP request parameters (basically looking for key=value pairs separated by an ampersand). It consists of AMD64-assembly and Rust code. The Rust part prints a key-value pair, and the assembly one does all of the work - finds the substrings, and returns the pointers, replacing '=' and '&' with '\0'. (I'm not sure if the assembler part is necessary because it works well. I checked the input of the function and the strings are just two null-terminated strings, as it is intended, but when I tried to catch the bug using rust-only code I couldn't, so I'm attaching the file)

### Version it worked on
```
rustc 1.79.0 (129f3b996 2024-06-10)
binary: rustc
commit-hash: 129f3b9964af4d4a709d1383930ade12dfe7c081
commit-date: 2024-06-10
host: x86_64-unknown-linux-gnu
release: 1.79.0
LLVM version: 18.1.7
```
```
stanislav@stanislav-83am:~/Documents/Projects/test$ rustup default stable
info: using existing install for 'stable-x86_64-unknown-linux-gnu'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.79.0 (129f3b996 2024-06-10)

stanislav@stanislav-83am:~/Documents/Projects/test$ cargo rustc -- -C relocation-model=static
      Compiling test v0.1.0 (/home/stanislav/Documents/Projects/test)
      Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.11s
stanislav@stanislav-83am:~/Documents/Projects/test$ ./target/debug/test
akfjasf
jafkjdf
kjdjdsf
sadsfdf
jgkdfjg
sgdsgdg
asfsnfj
aflmdsa

```

### Version with regression
`rustc --version --verbose`:
```
rustc 1.81.0-nightly (5affbb171 2024-07-18)
binary: rustc
commit-hash: 5affbb17153bc69a9d5d8d2faa4e399a014a211e
commit-date: 2024-07-18
host: x86_64-unknown-linux-gnu
release: 1.81.0-nightly
LLVM version: 18.1.7
```

```
stanislav@stanislav-83am:~/Documents/Projects/test$ rustup default nightly
info: using existing install for 'nightly-x86_64-unknown-linux-gnu'
info: default toolchain set to 'nightly-x86_64-unknown-linux-gnu'

  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.81.0-nightly (5affbb171 2024-07-18)

stanislav@stanislav-83am:~/Documents/Projects/test$ cargo rustc -- -C relocation-model=static
      Compiling test v0.1.0 (/home/stanislav/Documents/Projects/test)
      Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.13s
stanislav@stanislav-83am:~/Documents/Projects/test$ ./target/debug/test
Segmentation fault

```

**Comment by tgross35** [comment]
@20943204920434 would you be able to run a bisection on this to narrow it down further? You just need to run this tool https://github.com/rust-lang/cargo-bisect-rustc

This is somewhere between beta and nightly https://rust.godbolt.org/z/bEvK93aWh

**Comment by Nilstrieb** [comment]
The reproduction involves quite some complicated assembly. Would it be possible to reduce the amount of assembly to see whether it's actually a miscompilation or just UB in your code? I think there's a good chance that it's a bug in your code, but we can't know for sure if we don't have a smaller minimization.

**Comment by tgross35** [comment]
Methinks maybe something is wrong with your calling convention when you call `print`. Just trying to print the pointers within `print`. Changing it to just try to print the pointers

```rust
extern "sysv64" fn print(str1: *const i8, str2: *const i8) {
    println!("{str1:p} {str2:p}");
    // unsafe {
    //     println!("{}", CStr::from_ptr(str1).to_str().unwrap());
    //     println!("{}", CStr::from_ptr(str2).to_str().unwrap());
    // }
}
```

segfaults on both versions

**Comment by 20943204920434** [comment]
This is something very strange...

I'm trying to find the MCVE, and I could reproduce the problem, but totally randomly I found a very strange behaviour. When I push an reg64 and then pop it, the program works as intended. It looks like for some reason one pushed register helps the program to not crash (?)

This snippet compiles and works flawlessly (finds an aforementioned pair and exists)
```

.globl test
        test:
		push rbx
	        push rdi

                dec rdi
        .lp1:   inc rdi
                cmp byte ptr [rdi], 0x3D
                jne .lp1
                mov byte ptr [rdi], 0x00
                inc rdi
                push rdi

        .lp2:   inc rdi
                cmp byte ptr [rdi], 0x26
                jne .lp2
                mov byte ptr [rdi], 0x00

                pop rsi
                pop rdi
	
                call {}
		pop rbx
		ret

```
but when I compile it without push rbx/pop rbx it crashes. The register name is not important here, it worked as well with rax/rsi instead of rbx. It reminds me of windows calling convention and shadow stack, but afaik sysv64 doesn't use shadow stack.

**Comment by tgross35** [comment]
Stack alignment - I'm not sure the exact rules, but some operations (xmm) require the stack be 16-byte aligned. If your function has no registers to save, pushing anything will get the right alignment. And then you need to reset it at the end, so pop anything.

You can see the compiler do this here https://godbolt.org/z/r1obT5naP, it pushes a random register at the beginning then pops it at the end (always good to check your asm against what the compiler produces for something similar, to see if your implementation looks reasonable).

I'm going to close this since it doesn't appear to be an issue with rustc. The forum (https://users.rust-lang.org/) or the discord servers probably have some more assembly experts who can help you debug a bit more. Worst case, `some_string.split('=')` works quite well :)

**Comment by tgross35** [comment]
One other note for you @20943204920434 - [inline asm](https://doc.rust-lang.org/reference/inline-assembly.html#example) is usually more straightforward to use than `global_asm!` when experimenting because it handles some of the annoying parts (calling convention, register allocation, clobbers) for you. And makes it easier to blend some asm with some Rust.
