### ISSUE TITLE
bootstrap: `profile = "tools"` contains incompatible options.

### ISSUE THREAD

**Issue by aDotInTheVoid** [rust-lang/rust#127951]
With a `config.toml` of just:

```toml
profile = "tools"
```

rustdoc fails to build:

```
$ ./x build ./src/librustdoc/
Building bootstrap
    Finished `dev` profile [unoptimized] target(s) in 0.04s
thread 'main' panicked at src/core/config/config.rs:2705:5:
ERROR: Setting `rust.debug-logging` is incompatible with `rust.download-rustc`.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Build completed unsuccessfully in 0:00:00
```

`config.tools.toml` should be changed such that including it works.

Alternatively, bootstrap could be taught to build tools with debugging enabled, even if the `compiler/` crates don't have debug logging.

Probably due to #127322, CC @onur-ozkan

**Comment by onur-ozkan** [comment]
There is https://github.com/rust-lang/rust/pull/127913 for fixing it.

**Comment by onur-ozkan** [comment]
> There is #127913 for fixing it.

PR is merged, closing the issue.
