### ISSUE TITLE
Error when running windows .exe compiled on linux

### ISSUE THREAD

**Issue by Ztry8** [rust-lang/rust#128066]
### Code

```Rust
fn main() {
    println!("Hello, world!");
}
```

### Meta
`rustc --version --verbose`:
```
binary: rustc
commit-hash: 129f3b9964af4d4a709d1383930ade12dfe7c081
commit-date: 2024-06-10
host: x86_64-unknown-linux-gnu
release: 1.79.0
LLVM version: 18.1.7
```

`rustup show`:
```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/aslan/.rustup

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-pc-windows-gnu
x86_64-pc-windows-msvc
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.79.0 (129f3b996 2024-06-10)
```
`wine --version`:
```
wine-8.0 (Debian 8.0~repack-4)
```

### Error output
When I compiled a simple hello world program (generated by the default cargo project) to `x86_64-pc-windows-gnu` target,   
`cargo build --target x86_64-pc-windows-gnu` (the --release flag gives the same).
It compiled successfully, but when it is run under native Windows 7 on another computer   
or using wine on linux where it compiled (windows 10 installed by winecfg), it gives an error:   
(On windows 7 just a message with `bcryptprimitives.dll` not found)
```
0108:err:module:import_dll Library bcryptprimitives.dll (which is needed by L"Z:\\home\\aslan\\tesst\\target\\x86_64-pc-windows-gnu\\release\\tesst.exe") not found
0108:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\aslan\\tesst\\target\\x86_64-pc-windows-gnu\\release\\tesst.exe" failed, status c0000135
```
But it works fine on native windows 10 on another (third) computer!

**Comment by Ztry8** [comment]
My program doesn't need windows 7 or wine support (but it would be helpful), but this question may be useful to others!

**Comment by workingjubilee** [comment]
This is expected per [our docs specifying we support Windows 10](https://doc.rust-lang.org/stable/rustc/platform-support.html).

**Comment by workingjubilee** [comment]
And Wine is not an emulator, so it imperfectly emulates Windows.

**Comment by ChrisDenton** [comment]
For WINE, in this case you just need a newer version. Version 9 or newer should have the necessary APIs.
