### ISSUE TITLE
Type parameter captured inside closure may not live long enough

### ISSUE THREAD

**Issue by marmac02** [rust-lang/rust#128062]
Hello! I encountered the following behavior of the compiler when trying to initialize struct fields with closures that capture type parameter from outer scope.
```
struct S1 {
    x : Box<dyn FnOnce() -> ()>,
}

struct S2<P : FnOnce() -> ()> {
    x : P,
}

fn func_test<T>(param : T) {
    let closure : Box<dyn FnOnce() -> ()> = Box::new(move || {
        let bar : T = param;
    });
    S1 {x : closure};    //does not compile
    //S2::<Box<dyn FnOnce() -> ()>> {x : closure};  //compiles
   //let v : Vec<Box<dyn FnOnce() -> ()>> = vec![closure];  //compiles
}


fn main() {}
```
The above code does not compile when we try to create an instance of S1, with an error message that `T` may not live long enough.
There is no such issue for creating S2.

### Meta

```
rustc 1.79.0
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by SNCPlay42** [comment]
This is correct; `S1`'s field `x` is [assumed](https://doc.rust-lang.org/reference/lifetime-elision.html#default-trait-object-lifetimes) to be `dyn FnOnce() -> () + 'static`. You can add a lifetime to `S1` to override this:

```rust
struct S1<'a> {
    x : Box<dyn FnOnce() -> () + 'a>,
}
```

The compiler ought to suggest this itself, or at least add a note explaining the source of the `'static` requirement.

**Comment by marmac02** [comment]
Thank you for explaining, it makes sense. I agree that the error message could be improved.
