### ISSUE TITLE
Documentation LaTeX generation creates files that make pdflatex handle non-ASCII characters incorrectly

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#12804]
It seems our invocation of Pandoc on some files (e.g. `guide-tasks.md`) creates something equivalent to:

```latex
\documentclass{article}
\usepackage[utf8]{inputenc}
\begin{document}
π
\end{document}
```

which causes the following error

```
$ pdflatex unicode-input.tex
[...]
! Package inputenc Error: Unicode char \u8:π not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.4 π
[...]
```

The relevant section of (my) inputenc docs is:

> ###### 1.3.3 `Unicode char ⟨charcode⟩ not set up for use with LaTeX`
> 
> This is the dreaded error message that one will receive if the document contains an
> UTF-8 character that isn’t known to LaTeX. It is quite possible that the character
> looks very unsuspicious and is rendered perfectly in the editor.
>
> For example, when entering a Euro symbol from the keyboard one may receive
> this error rather than a typeset symbol. But if this happens the reason is simply
> that the document doesn’t load a font containing the Euro symbol, e.g., via the
> textcomp package. Thus LaTeX does not know how to typeset one and therefore
> responds with this error message.
>
> However, even if LaTeX can type that character in question it may not
> have been set up in which case you would need to do that yourself via
> \DeclareUnicodeCharacter. If you provide these declarations for a full font en-
> coding then please contribute that work to this package so that others can benefit
> too.

**Comment by steveklabnik** [comment]
I think since we have the preferred latex stuff in the right order, this is effectively good enough.
