### ISSUE TITLE
`tool::prepare_tool_cargo` should run `builder.ensure` automatically, based on tool mode

### ISSUE THREAD

**Issue by tgross35** [rust-lang/rust#128012]
I was somewhat thrown off by https://github.com/rust-lang/rust/pull/127510/commits/6062059ab0f9a805ae8327a80e55bc6f47330a7b#diff-675065335a90de4a4e1ac5bc0a078709f865ff2d357ba2650309f0ad8614b1d3R3531-R3549; setting `Mode::ToolStd` or some of the other `Mode::Tool*` options caused a ``can't find crate for `core` `` (and std) error. This was fixed by adding `builder.ensure(compile::Std::new(compiler, bootstrap_host));`.

Since `prepare_tool_cargo` knows the mode, it should just call `builder.ensure` itself. This manual ensure could then be removed from the rest of `build_steps/test.rs`.

**Comment by onur-ozkan** [comment]
Tools test steps usually ensure their corresponding step in `tool` module and that is usually managed by `ToolBuild` step. When you look at `ToolBuild::run`, you can see that it handles this problem: https://github.com/rust-lang/rust/blob/2e6fc425411280c658d852813de01c5157255088/src/bootstrap/src/core/build_steps/tool.rs#L71-L89

So, if you add this new tool under `tool` module with `ToolBuild`, this problem will be handled automatically.

**Comment by tgross35** [comment]
I opened this because a few other tools seem to call `builder.ensure(compile::Std::new(...))` right before `tool::prepare_tool_cargo` (`Miri`, `CompiletestTest`, `RunMakeSupport`, `CrateRustdoc`, `TierCheck`) so it seemed like a common pattern.

Are you saying that the new `TestFloatParse` could just be a `ToolBuild` step? I think I looked at that first but since it needs to both `cargo test` and `cargo run` with some args, it seemed like it was easier to just add a new step (I could easily have missed something here).

**Comment by onur-ozkan** [comment]
I think the right pattern should be having a specific build step in tool module (so we can also build it with `x build`), then ensure that in the test step.

**Comment by tgross35** [comment]
Alright, it ideally would also have a `x run` but that isn't implemented. I don't want to touch that PR now since it's pretty large and already in the queue, but I'll send a follow up after it merges and r? you.

**Comment by lucarlig** [comment]
@tgross35 still working on this?

**Comment by tgross35** [comment]
I guess this slipped my mind. All yours @lucarlig if you are interested, just comment `@rustbot claim` and it will assign you.

**Comment by lucarlig** [comment]
will try it out,
@rustbot claim

**Comment by jieyouxu** [comment]
> I opened this because a few other tools seem to call `builder.ensure(compile::Std::new(...))` right before `tool::prepare_tool_cargo` (`Miri`, `CompiletestTest`, `RunMakeSupport`, `CrateRustdoc`, `TierCheck`) so it seemed like a common pattern.

The `RunMakeSupport` one looks wrong to me *now* in that that ensure on std shouldn't be there. At the time I implemented that, I had no idea what I was doing, I just copied whatever code was around it lol.

**Comment by lucarlig** [comment]
I think this issue is not needed @onur-ozkan based on https://github.com/rust-lang/rust/pull/131855

> > I opened this because a few other tools seem to call `builder.ensure(compile::Std::new(...))` right before `tool::prepare_tool_cargo` (`Miri`, `CompiletestTest`, `RunMakeSupport`, `CrateRustdoc`, `TierCheck`) so it seemed like a common pattern.
> 
> The `RunMakeSupport` one looks wrong to me _now_ in that that ensure on std shouldn't be there. At the time I implemented that, I had no idea what I was doing, I just copied whatever code was around it lol.

regarding this maybe open a new issue @jieyouxu ?
regarding `TestFloatParse` pr is there already #131731

**Comment by jieyouxu** [comment]
> The `RunMakeSupport` one looks wrong to me _now_ in that that ensure on std shouldn't be there. At the time I implemented that, I had no idea what I was doing, I just copied whatever code was around it lol.

Hm actually no, I read it again, the `RunMakeSupport` is a test step and has special handling, nevermind.
