### ISSUE TITLE
Regression in type inferencing in 1.80.0

### ISSUE THREAD

**Issue by rylev** [rust-lang/rust#128181]
The following issue can be reproduced by compiling the [`time` crate v0.3.34](https://github.com/time-rs/time/tree/v0.3.34) with the `formatting` feature enabled. Doing so works successfully when using version 1.79.0 of the compiler but breaks with version 1.80.0:

```
error[E0282]: type annotations needed for `Box<_>`
  --> time/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++
```

**Comment by Urgau** [comment]
https://github.com/rust-lang/rust/issues/127343 and https://github.com/rust-lang/rust/issues/127343#issuecomment-2218261296

**Comment by geraldmwangi** [comment]
+1
