### ISSUE TITLE
Rustdoc: struct fields are spaced too closely

### ISSUE THREAD

**Issue by tgross35** [rust-lang/rust#128260]
Sample at https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/mir/struct.Body.html:

<img width="1066" alt="image" src="https://github.com/user-attachments/assets/6bae9d39-68d9-4da8-8016-d4399d613e49">

Headings seem too close to the paragraphs around them, enough so that paragraph breaks stand out more than field breaks.

Testing with `.structfield { padding-top: 0.8rem; padding-bottom: 0.2rem; }`, I think this makes sections stand out better:

<img width="1023" alt="image" src="https://github.com/user-attachments/assets/df077075-1e93-4c53-ac51-81a2eb2cd8a6">

**Comment by tgross35** [comment]
If somebody points me in the right direction then I can do this (unless somebody beats me to it, feel free).

**Comment by gurry** [comment]
I'm no rustdoc export but this is the template that seems to be rendering the HTML in question: https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/templates/item_union.html

It might also help to just search for "structfield" under src/librustdoc.

**Comment by tgross35** [comment]
Thanks for taking a look - aiui that is indeed where the HTML comes from, but I was less certain about the CSS. https://github.com/rust-lang/rust/blob/a526d7ce45fd2284e0e7c7556ccba2425b9d25e5/src/doc/rust.css#L188 seems like a reasonable guess, but I just wanted to double check styles aren't applied in JS or something like that (I assume themes are but maybe not structure?).
