### ISSUE TITLE
Fix call to [get|record]_sp_limit for thumb arch

### ISSUE THREAD

**Issue by bharrisau** [rust-lang/rust#12824]
Now with #12407 thumb is supported for `rust_stack_exhausted()`. This calls `get_sp_limit()` which calls the implementation in `rt/arch/arm/record_sp.S`. This code isn't supported for thumb targets though. The call should be returning `*STACK_LIMIT` for thumb.

**Comment by alexcrichton** [comment]
We've since removed these functions from the runtime, so closing.
