### ISSUE TITLE
must_use attribute

### ISSUE THREAD

**Issue by Adrien-Bodineau** [rust-lang/rust#128395]
Any reason why the `must_use` attribute is necessary ? Shouldn't all type, except `()` and `!`, be `must_use` so that function calls always trigger a warning when the return type is not used ?

**Comment by ChrisDenton** [comment]
Such questions are better answered on the user forum or chat (see https://www.rust-lang.org/community) rather than the issue tracker.

**Comment by lolbinarycat** [comment]
a lot of builder-pattern methods (like `Command::arg`) mutate the receiver and then return it.  this return value is frequently ignored.

**Comment by ChrisDenton** [comment]
Closing this in favour of the user forum thread https://users.rust-lang.org/t/must-use-attribute/115228/3
