### ISSUE TITLE
Compiler builtins missing f16/f128 symbols 

### ISSUE THREAD

**Issue by tgross35** [rust-lang/rust#128358]
Reported by @TimNN [here](https://github.com/rust-lang/rust/pull/125016#issuecomment-2256545662):

> I think something in this PR might be broken with regard to whether the f16/f128 builtins are being generated.
> 
> I have downloaded https://ci-artifacts.rust-lang.org/rustc-builds/80d8270d8488957f62fbf0df7a19dfe596be92ac/rust-std-nightly-x86_64-unknown-linux-gnu.tar.xz
> 
> And ran
> 
> ```
> llvm-nm ./rust-std-nightly-x86_64-unknown-linux-gnu/rust-std-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-7586cb84705120bb.rlib | grep __extend
> ./rust-std-nightly-x86_64-unknown-linux-gnu/rust-std-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-7586cb84705120bb.rlib:lib.rmeta: no symbols
> 0000000000000000 T _ZN17compiler_builtins5float6extend13__extendsfdf217hc5379a65d797e83bE
> 0000000000000000 W __extendsfdf2
> ```
> 
> I would have expected to see the f16 & f128 symbols there.
> 
> Running a `rustc` build in verbose mode, I see:
> 
> `/Users/logic/Projects/rustc/llvm-head/build/bootstrap/debug/rustc /Users/logic/Projects/rustc/llvm-head/build/bootstrap/debug/rustc --crate-name compiler_builtins --edition=2021 /Users/logic/.cargo/registry/src/index.crates.io-6f17d22bba15001f/compiler_builtins-0.1.114/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=145 --crate-type lib --emit=dep-info,metadata,link --cfg 'feature="compiler-builtins"' --cfg 'feature="core"' --cfg 'feature="default"' --cfg 'feature="no-f16-f128"' --cfg 'feature="rustc-dep-of-std"' --target aarch64-apple-darwin <truncated>`
> 
> Note the `--cfg 'feature="no-f16-f128"'` in there. This is on `aarch64` which means that, AFAICT, `no-f16-f128` should **not** trigger.
> 
> Commenting out
> 
> ```toml
> [target.'cfg(not(any(target_arch = "aarch64", target_arch = "x86", target_arch = "x86_64")))'.dependencies]
> compiler_builtins = { version = "0.1.114", features = ["no-f16-f128"] }
> ```
> 
> Does produce a `libcompiler_builtins.rlib` which has the f16/f128 symbols.

**Comment by tgross35** [comment]
Per @ehuss, this is related to the old resolver https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/Enabling.20features.20on.20specific.20targets/near/454918607

**Comment by TimNN** [comment]
I ran:

```
<env omitted> "/Users/logic/Projects/rustc/llvm-head/build/aarch64-apple-darwin/stage0/bin/cargo" "tree" -e features "--target" "aarch64-apple-darwin" "-Zbinary-dep-depinfo" "-v" "-v" "-v" "--features" " panic-unwind backtrace" "--manifest-path" "/Users/logic/Projects/rustc/llvm-head/library/sysroot/Cargo.toml" "-p" "alloc"
alloc v0.0.0 (/Users/logic/Projects/rustc/llvm-head/library/alloc)
├── compiler_builtins feature "default"
│   ├── compiler_builtins v0.1.114
│   │   └── rustc-std-workspace-core feature "default"
│   │       └── rustc-std-workspace-core v1.99.0 (/Users/logic/Projects/rustc/llvm-head/library/rustc-std-workspace-core)
│   │           └── core feature "default"
│   │               └── core v0.0.0 (/Users/logic/Projects/rustc/llvm-head/library/core)
│   └── compiler_builtins feature "compiler-builtins"
│       └── compiler_builtins v0.1.114 (*)
├── compiler_builtins feature "rustc-dep-of-std"
│   ├── compiler_builtins v0.1.114 (*)
│   ├── compiler_builtins feature "compiler-builtins" (*)
│   └── compiler_builtins feature "core"
│       └── compiler_builtins v0.1.114 (*)
└── core feature "default" (*)
[dev-dependencies]
├── rand feature "alloc"
│   ├── rand v0.8.5
│   │   └── rand_core feature "default"
│   │       └── rand_core v0.6.4
│   └── rand_core feature "alloc"
│       └── rand_core v0.6.4
└── rand_xorshift feature "default"
    └── rand_xorshift v0.3.0
        └── rand_core feature "default" (*)
```

So that doesn't show the feature being activated.

I also tried to set `resolve = 2`, which I think correctly made the `no-f16-f128` feature not trigger, but this fails to compile stage 0 `compiler_builtins`, because `f16.is_nan()` doesn't exist.

**Comment by tgross35** [comment]
> I also tried to set `resolve = 2`, which I think correctly made the `no-f16-f128` feature not trigger, but this fails to compile stage 0 `compiler_builtins`, because `f16.is_nan()` doesn't exist.

Oh you're kidding, that's a third PR for me blocked on https://github.com/rust-lang/rust/pull/128083 then :(. Guess if https://github.com/rust-lang/rust/pull/128359 CI fails (likely based on your comment) I will just set `no-f16-f128` on all platforms until the beta bump happens.

**Comment by TimNN** [comment]
If I override the `rustc` that compiles stage 0 and set `resolver = 2`, then for `x build --stage 1 library/std` I get a `libcompiler_builtins.rlib` that contains the f16/f128 symbols.

**Comment by tgross35** [comment]
Thanks for confirming, guess we are waiting on https://github.com/rust-lang/rust/pull/128359 and then https://github.com/rust-lang/rust/pull/128083.

**Comment by VorpalBlade** [comment]
Possibly related (so this is a regression that breaks code that compiles on stable): #128401

**Comment by TimNN** [comment]
Could we, as a quick fix on Resolver 1, move the

```toml
[target.'cfg(not(any(target_arch = "aarch64", target_arch = "x86", target_arch = "x86_64")))'.dependencies]
compiler_builtins = { version = "0.1.114", features = ["no-f16-f128"] }
```

bit into bootstrap?

**Comment by tgross35** [comment]
I was honestly thinking that maybe we should move that logic into `compiler_builtins` itself - always build unless the platform is known to have a LLVM crash or if `no-f16-f128` is enabled. Then nothing in `rust-lang/rust` should have to worry about the feature flag unless it needs to be disabled.

I'll take a look at doing this in the morning.

**Comment by tgross35** [comment]
Wound up doing the above, `compiler_builtins` now checks here https://github.com/rust-lang/compiler-builtins/blob/cc385f4802dd69175b040dcc3b907477f74bb47c/configure.rs#L52-L92 to disable the extra float types on platforms where LLVM crashes. Then we configure what to actually test in `std`, based on platforms that are known to be bug-free https://github.com/rust-lang/rust/blob/0399709cdc3c5cc22327e9f657dc7956546a0457/library/std/build.rs#L81-L186.

I think this should be resolved so I will close it. @TimNN mind double checking if you get the chance?

Reminder to self: this was about errors for missing symbols even when `f16`/`f128` were not used, not only missing symbols when building and using float math.
