### ISSUE TITLE
rustc puts mapping symbol $d before an instruction sequence on AArch64

### ISSUE THREAD

**Issue by renndong** [rust-lang/rust#128479]
I'm trying to use BOLT to optimize my Rust program, but I got a BOLT error. I reported this issue to LLVM, and @yota9 found that it was because Rust incorrectly placed mapping symbol $d before the instruction sequence (the context is [here](https://github.com/llvm/llvm-project/issues/100920#issuecomment-2258170225)).

I have a simple merge sort program:

<details>

<summary>mergeSort.rs</summary>

```rust
use std::fs::File;
use std::io::{self, BufRead};

fn merge(arr: &mut [i32], low: usize, mid: usize, high: usize) {
    let n1 = mid - low + 1;
    let n2 = high - mid;

    let mut L = vec![0; n1];
    let mut R = vec![0; n2];

    for i in 0..n1 {
        L[i] = arr[low + i];
    }
    for j in 0..n2 {
        R[j] = arr[mid + 1 + j];
    }

    let mut i = 0;
    let mut j = 0;
    let mut k = low;

    while i < n1 && j < n2 {
        if L[i] <= R[j] {
            arr[k] = L[i];
            i += 1;
        } else {
            arr[k] = R[j];
            j += 1;
        }
        k += 1;
    }

    while i < n1 {
        arr[k] = L[i];
        i += 1;
        k += 1;
    }

    while j < n2 {
        arr[k] = R[j];
        j += 1;
        k += 1;
    }
}

fn merge_sort(arr: &mut [i32], low: usize, high: usize) {
    if low < high {
        let mid = low + (high - low) / 2;

        merge_sort(arr, low, mid);
        merge_sort(arr, mid + 1, high);

        merge(arr, low, mid, high);
    }
}

fn main() -> io::Result<()> {
    const ARRAY_SIZE: usize = 100000;
    let mut data_array = vec![0; ARRAY_SIZE];

    // read random number from a file
    let file = File::open("random_array.txt")?;
    let reader = io::BufReader::new(file);

    for (i, line) in reader.lines().enumerate() {
        if i >= ARRAY_SIZE {
            break;
        }
        let num: i32 = line?.parse().unwrap();
        data_array[i] = num;
    }

    for _ in 0..1000 {
        let mut temp_array = data_array.clone();
        merge_sort(&mut temp_array, 0, ARRAY_SIZE - 1);
    }

    Ok(())
}
```

</details>

and I compile it with the command:

```bash
rustc -C link-arg=-Wl,-q -o mergeSort.rs.out mergeSort.rs
```

The symbol table is as follows, where address 3a09c to 3bf34 is a code region of a function, but three mapping symbol $d that should appear before the data region are placed in this interval. This misleads the disassembler in BOLT to distinguish data and code and prevents the function to be disassembled.

```
$ readelf -s mergeSort.rs.out | grep -E '\$(d|x)' | sort -d -k 2
  ...
  2317: 000000000003a09c     0 NOTYPE  LOCAL  DEFAULT   14 $x.7
  1242: 000000000003b7a8     0 NOTYPE  LOCAL  DEFAULT   20 $d.1740
  1193: 000000000003b7e8     0 NOTYPE  LOCAL  DEFAULT   20 $d.10
  2063: 000000000003bcc8     0 NOTYPE  LOCAL  DEFAULT   20 $d.75
  2372: 000000000003bf34     0 NOTYPE  LOCAL  DEFAULT   14 $x.5
  ...
$ readelf -s mergeSort.rs.out | grep -E '3a09c|3bf34'
  2317: 000000000003a09c     0 NOTYPE  LOCAL  DEFAULT   14 $x.7
  2372: 000000000003bf34     0 NOTYPE  LOCAL  DEFAULT   14 $x.5
  2534: 000000000003a09c  7832 FUNC    GLOBAL DEFAULT   14 _ZN11miniz_oxide[...]
  2542: 000000000003bf34   780 FUNC    GLOBAL DEFAULT   14 _ZN5adler7Adler3[...]
```

What I expect is that these three $d should not appear before the instruction sequence, i.e.

```
$ readelf -s mergeSort.rs.out | grep -E '\$(d|x)' | sort -d -k 2
...
2317: 000000000003a09c     0 NOTYPE  LOCAL  DEFAULT   14 $x.7
# no $d
2372: 000000000003bf34     0 NOTYPE  LOCAL  DEFAULT   14 $x.5
...
```

The binary I compiled is [mergeSort.rs.out.zip](https://github.com/user-attachments/files/16450380/mergeSort.rs.out.zip)

### Meta

`rustc --version --verbose`:
```
rustc 1.80.0 (051478957 2024-07-21)
binary: rustc
commit-hash: 051478957371ee0084a7c0913941d2a8c4757bb9
commit-date: 2024-07-21
host: aarch64-unknown-linux-gnu
release: 1.80.0
LLVM version: 18.1.7
```

**Comment by saethlin** [comment]
I struggle to understand how this could be anything but an LLVM bug. It's not a BOLT issue, but it looks like LLVM has generated output that BOLT doesn't understand. That's not too absurd; sometimes the left hand doesn't talk to the right hand.

**Comment by renndong** [comment]
Thanks for your reply.

I'm not familiar with the Rust compiler architecture, but I tried using Clang to compile a C++ program and reproduced this issue. It is indeed not a Rust bug, but LLVM.

BTW, this issue is a bit weird, and I haven't found the code or library that causes it. The function `_ZN11miniz_oxide7inflate4core10decompress17hec1101b6c5d04f05E` with the incorrect mapping symbol in binary is from the library `libminiz_oxide-ac2fb70497abedad.rlib`, which has the correct mapping symbols. it seems that not the wrong function lead to itself error.

Anyway, thank you again, and I will report this bug to the LLVM community.
