### ISSUE TITLE
#[pointee] attribute can be applied to anything

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#128485]
I tried this code:

```rust
#![feature(derive_smart_pointer)]

#[pointee]
fn main() {}
```

I expected to see this happen: compilation failure

Instead, this happened: compilation succeeded

### Meta

`rustc --version --verbose`:
```
1.82.0-nightly

2024-07-31 28a58f2fa7f0c46b8fab
```

cc https://github.com/rust-lang/rust/issues/123430

see https://github.com/rust-lang/rust/pull/128444 for where to fix this issue

**Comment by dingxiangfei2009** [comment]
@Brezak Oops sorry. You can continue with your PR.
