### ISSUE TITLE
Investigate if it's possible to eventually have run-make test suite not have to be run in msys2 on Windows

### ISSUE THREAD

**Issue by jieyouxu** [rust-lang/rust#128473]
At least some of them. It's very painful to have to use msys2 to run the run-make test suite.

**Comment by ChrisDenton** [comment]
Is that not the natural end result of porting to rmake?

**Comment by ChrisDenton** [comment]
I mean, the issue is that the old MakeFile approach relied on msys2 bash and a mixture of native apps and msys2 apps.

**Comment by jieyouxu** [comment]
> Is that not the natural end result of porting to rmake?

I mean, *ideally* yes that is one of the goals, I just opened this issue to remind myself that I want to take a look towards the end if there are any blockers for the test suite to be "freestanding" from msys2.

**Comment by jieyouxu** [comment]
compiletest triage: yes it is very much possible -- just get rid of the `Makefile`s :3
