### ISSUE TITLE
`-Ctarget-feature=+avx` doesn't enable `sse4.2`

### ISSUE THREAD

**Issue by calebzulawski** [rust-lang/rust#128426]
See example: https://rust.godbolt.org/z/GxMaecr4T

Adding either `sse4.2` or `crc32` works, so I believe the issue is due to the tied `crc32` feature.

This issue is present on latest master.

**Comment by RalfJung** [comment]
Seems like LLVM doesn't consider this to be an implication. I don't know enough about target features to be able to say who is right here.

Cc @nikic

**Comment by calebzulawski** [comment]
X86.td does define avx as implying sse4.2 and `-mavx` in clang enables sse4.2, I think we're getting it lost somewhere because we define sse4.2 as enabling both sse4.2 and crc32.  sse4.2 is the only x86 SIMD feature tied to another feature.

**Comment by RalfJung** [comment]
> `-mavx` in clang enables sse4.2,

Does it enable crc32 as well?

**Comment by calebzulawski** [comment]
Yes, it does: https://c.godbolt.org/z/rrd7Pvr4T

**Comment by calebzulawski** [comment]
I'd be curious to see if this is a problem with other tied features, not just sse4.2

**Comment by calebzulawski** [comment]
Looking into it a bit more, I think it's incorrect for sse4.2 to enable crc32: https://reviews.llvm.org/D105462

crc32 appears to be a special feature that enables the crc32 instruction when other vector extensions are disabled, so I don't think it's ever necessary when sse4.2 is enabled.  I think clang enables the __CRC32__ attribute if _either_ sse4.2 or crc32 are enabled.

**Comment by calebzulawski** [comment]
This also has the consequence of causing sse4.2 to not inline into avx: https://rust.godbolt.org/z/KMGnffTnY
