### ISSUE TITLE
&[1, 2, 3] should always be &'static [<generic integer>]

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#12853]
The following works:

```rust
fn foo<'a>(xs: &'a [int]) -> &'a [int] {
    if xs.len() & 1 == 0 {
        static ys: &'static [int] = &[1, 2, 3];
        ys
    } else {
        xs
    }
}
```

This should also work, but does not:

```rust
fn foo<'a>(xs: &'a [int]) -> &'a [int] {
    if xs.len() & 1 == 0 {
        &[1, 2, 3]
    } else {
        xs
    }
}
```

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#827

**Comment by thestinger** [comment]
This isn't a proposal for a language change, it's a bug report.

**Comment by steveklabnik** [comment]
We had an IRC chat about it, and it seems to me like an enhancement. Changing `&[1, 2, 3]` to go from "a reference to a stack allocated array" to "a statically allocated array" seems like a semantic change, no?

**Comment by thestinger** [comment]
The fact that the compiler is treating immutable constant expressions as stack allocations is a **bug**. There is no language change to discuss here, only an implementation improvement.
