### ISSUE TITLE
rustc got noticeably slower

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#128599]
I'm not sure what exactly causes this yet.
While fuzzing, I noticed that a run would take up to twice a as long a before, depending on the input file set.

on a smaller input set:

with  a886938671e1fde9d7271dce8ca3d6938bae9d2e
Checked 679 files in 1.28 minutes, 8.82 files/second
Timings in seconds:
Timer { rustc_time: 3023, clippy_time: 0, rustdoc_time: 0, rla_time: 0, rustfmt_time: 0, miri_time: 0, clippyfix_time: 0, rustfix_time: 0, kani_time: 0, rustc_codegen_gcc_time: 0, marker_time: 0, treesitter: 0 }

with master eefd2eac52f50176a761d20f16dcf6434ecc8831 
Checked 679 files in 1.53 minutes, 7.38 files/second
Timings in seconds:
Timer { rustc_time: 3310, clippy_time: 0, rustdoc_time: 0, rla_time: 0, rustfmt_time: 0, miri_time: 0, clippyfix_time: 0, rustfix_time: 0, kani_time: 0, rustc_codegen_gcc_time: 0, marker_time: 0, treesitter: 0 }

not sure yet what this is caused by, could be anything from cmdline parsing, a particular rustflag that adds a lot of overhead or even the printing of the backtraces etc

**Comment by matthiaskrgr** [comment]
hmm might just be a rust crash that happens very often and needs to be processed leading to increased processing time :smile:

**Comment by workingjubilee** [comment]
seems we are wontfixing this, categorizing as such to make sure no one imagines this (very edge-case) regression was actually fixed.
