### ISSUE TITLE
Add ability to search by type signature on the docs

### ISSUE THREAD

**Issue by reem** [rust-lang/rust#12866]
One of hoogle's most useful features is the ability to search by type signatures. It makes finding functions whose behavior you know but whose names you don't know much easier.

We should add this ability to the search feature in the rust docs.

**Comment by ajtulloch** [comment]
FWIW, I took a look yesterday at dumping a stylized type signature from RustDoc that Hoogle can then read in, which allows us to reuse all the fancy type search algorithms Hoogle uses (retrieval, selective generalization, canonicalization, scoring, etc).  It seems to work OK as a demo with even just a simple implementation (~200 lines in `librustdoc`, ~200 lines in Hoogle). 

![example](http://i.imgur.com/mdiCh9R.png)

https://github.com/ajtulloch/roogle has some more documentation on the approach, usage instructions, and examples (along with the Hoogle changes), and https://github.com/ajtulloch/rust has the `librustdoc` changes.

The main missing features (relative to Hoogle for Haskell) are:

- links to `doc.rust-lang.org` for search results
- more complete rustdoc integration, so all function/methods/traits/aliases are exported to Hoogle
- more precise translation of the Rust type system
  - Handling of `mut T` vs `T`
  - `&T` vs `T`
  - `T: Eq + Num` vs unbounded generics, etc.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#658
