### ISSUE TITLE
[rustdoc-json] Regression — `core.json`, `alloc.json` and `std.json` are no longer available on nightly for `rust-docs-json` component

### ISSUE THREAD

**Issue by LukeMathWalker** [rust-lang/rust#128610]
I have pinned down the regression to a specific commit, thanks to @aDotInTheVoid recommending me `cargo-bisect-rustc`.

## Output of `cargo bisect-rustc`

searched nightlies: from nightly-2024-07-28 to nightly-2024-07-30
regressed nightly: nightly-2024-07-30
searched commit range: https://github.com/rust-lang/rust/compare/2cbbe8b8bb2be672b14cf741a2f0ec24a49f3f0b...612a33f20b9b2c27380edbc4b26a01433ed114bc
regressed commit: https://github.com/rust-lang/rust/commit/56c698c71130de6fe55ba703a161405b6145b90e

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.9</summary>

Host triple: aarch64-apple-darwin
Reproduce with:
```bash
cargo bisect-rustc -c rust-docs-json --start=2024-07-28 --end=2024-07-30 --script ./regr.sh
```

`regr.sh`:

```bash
#!/bin/sh
set -ex

if [ ! -f ~/.rustup/toolchains/${RUSTUP_TOOLCHAIN}/share/doc/rust/json/core.json ]; then
    echo "File not found!"
    exit 1
fi
```

</details>

**Comment by LukeMathWalker** [comment]
Based on the commits in that rollup, I feel like https://github.com/rust-lang/rust/pull/128182 might be the culprit, but it isn't obvious to me why that might be the case (cc @onur-ozkan, @ChrisDenton, @Mark-Simulacrum)

**Comment by onur-ozkan** [comment]
Thanks for the ping, https://github.com/rust-lang/rust/pull/128631 will fix this.
