### ISSUE TITLE
Windows: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN 

### ISSUE THREAD

**Issue by altunenes** [rust-lang/rust#128642]
I get this error when running my Rust project (a simple project utilized with CUDA and Onnx runtime), but I can't get any other output about the context. Is there a convenient way for me to determine exactly where this problem is coming from, so I can fix?

os: Windows 11, latest

**Comment by clubby789** [comment]
I believe `STATUS_STACK_BUFFER_OVERRUN` can indicate an uncaught C++ exception crossing the ABI boundary into Rust. You might want to try a debugger to see where the issue occurs
Also, can you provide code for this project?

**Comment by altunenes** [comment]
thank you very much for your help!

Here is the more context: 
https://github.com/thewh1teagle/sherpa-rs/issues/8

I understand from your comment that the problem is not Rust-related but CPP related? Because `sherpa-rs` is actually linked to https://github.com/k2-fsa/sherpa-onnx.

**Comment by workingjubilee** [comment]
@altunenes Yes, unfortunately we do not correctly implement catching foreign exceptions so we typically emit a platform-dependent error as a result (formally, it's considered UB, so the fact that your program "only" explodes into flames is _good_, as much worse things could have happened).

This error in particular is Windows-speak for "something bad happened so we terminated the process very quickly". https://devblogs.microsoft.com/oldnewthing/20190108-00/?p=100655

**Comment by altunenes** [comment]
thank you so much for your time!

**Comment by thewh1teagle** [comment]
> Yes, unfortunately we do not correctly implement catching foreign exceptions so we typically emit a platform-dependent error as a result (formally, it's considered UB, so the fact that your program "only" explodes into flames is _good_, as much worse things could have happened).

Can I expect meaningful error messages from Rust when calling foreign libraries? For example, if a library fails to load a missing DLL file, how will I know the cause of the failure in the Rust call?

**Comment by workingjubilee** [comment]
@thewh1teagle There are so many factors in what you just said that I can't say anything, sorry.

I should rephrase my original statement: if an unwind proceeds from C++ into the Rust runtime, **without** a `catch_unwind`, we typically abort in a nonspecific way. If you wish to guarantee that an exception from C++ is at least translated to an abort message that notices it was caused by a foreign exception, you can use `catch_unwind`.
