### ISSUE TITLE
rustdoc generates invalid link: `url#impl-id/method.name`

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#128676]
I spotted this in [these search results](https://doc.rust-lang.org/nightly/nightly-rustc/?search=adt_def): the `TyCtxt::adt_def` result links to https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/context/struct.TyCtxt.html#impl-TyCtxt%3C'tcx%3E/method.adt_def which is not a valid link.

Cc @rust-lang/rustdoc

**Comment by camelid** [comment]
cc @notriddle -- I think these are supposed to be autoredirected in JS?
