### ISSUE TITLE
simd_shuffle cleanup: make the mask argument a vector (instead of an array)

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#128738]
Since recently, codegen always passes constants of vector type as immediates in LLVM (https://github.com/rust-lang/rust/pull/128537). This gives us a change to clean up [this hack](https://github.com/rust-lang/rust/blob/6c0b89dfac65be9a5be12f938f23098ebc36c635/compiler/rustc_codegen_ssa/src/mir/block.rs#L922-L935), where the `idx` argument of `simd_shuffle` is forced to be passed as an immediate. However, simd_shuffle for some reason actually takes an *array* as argument, not a vector, so the hack is still required to ensure that the array becomes an immediate (which then later stages of codegen convert into a vector, as that's what LLVM needs).

This is more painful than it should be because stdarch is a submodule :cry: , so we'll have to do it in stages:
- make simd_shuffle support both arrays and vectors: https://github.com/rust-lang/rust/pull/128731
- switch stdarch to use vectors: https://github.com/rust-lang/stdarch/pull/1633
- update stdarch in rustc: https://github.com/rust-lang/rust/pull/129696
- remove the array hack: https://github.com/rust-lang/rust/pull/130268

**Comment by RalfJung** [comment]
FYI @oli-obk (making the hack a bit less hacky ;)

**Comment by oli-obk** [comment]
yay.

Moving stdarch to josh first would help so many of these projects

**Comment by RalfJung** [comment]
Yeah, it would, but Amanieu had some [concerns regarding the test suite.](https://rust-lang.zulipchat.com/#narrow/stream/208962-t-libs.2Fstdarch/topic/Make.20this.20a.20subtree.20rather.20than.20a.20submodule.3F).
