### ISSUE TITLE
Improve support of using `jj` to manage `rust-lang/rust` as a collocated git repo

### ISSUE THREAD

**Issue by yaahc** [rust-lang/rust#128708]
Right now using `jj` to manage the rust-lang/rust repo locally causes `x tidy` to fail: https://github.com/rust-lang/rust/pull/128706

This is a result of [jj not yet having support for `.gitattributes`](https://github.com/martinvonz/jj/issues/53) which is responsible for adding the `crlf` character to the failing test.

While I would love to get that support added to jj upstream I'm assuming it is non-trivial and I'd like a better solution in the short term so I can continue to use `jj` while contributing to the compiler.

@jyn514 suggested I use `--exclude tests/rustdoc-ui/intra-doc/warning-crlf.rs` in the meantime which I'm fine with but I'd like a way to set this in my `config.toml` or some equivalent mechanism doesn't require manually adding this set of arguments to every invocation of `x test` I make.

**Comment by jyn514** [comment]
note this is essentially the same as https://github.com/rust-lang/rust/issues/35678

i actually would like an even more general solution, where the flags and configs are completely interchangable and you can specify either in either place, but a solution just for `exclude` seems ok too.

@rustbot label T-bootstrap A-contributor-roadblock

**Comment by yaahc** [comment]
So it turns out that `x test --exclude tests/rustdoc-ui/intra-doc/warning-crlf.rs` won't work as a short term fix even because `--exclude` does not work with tidy.

**Comment by sunshowers** [comment]
re crlf, as a source control expert I'd recommend never using any kind of autoconversion -- it is a bit of a nightmare to work with in too many cases.

Rather, I'd consider checking in the file with CRLFs, and disabling autoconversion so files are always checked out as-is.

(Another option is to effectively treat the file as binary content, e.g. use some other means of encoding the file, such as base64 or putting it in a tarball. But I don't know how practical that is)
