### ISSUE TITLE
core::fmt::Formatter does not mention write! macro

### ISSUE THREAD

**Issue by ErikMcClure** [rust-lang/rust#128713]
### Location

[Formatter::write_fmt](https://doc.rust-lang.org/beta/core/fmt/struct.Formatter.html)

### Summary

The docs for `write_fmt` in [Formatter](https://doc.rust-lang.org/beta/core/fmt/struct.Formatter.html) do not line up with the docs for `write_fmt` in the [Write trait](https://doc.rust-lang.org/std/fmt/trait.Write.html). The write trait warns you that you should be using the `write!` macro, but the method in `Formatter` doesn't. If you are implementing `core::fmt::Debug` and call `write_fmt` on the provided `Formatter` object directly, and use the wrong arguments, the rust-analyzer error will use `Formatter` docs, which will mislead the user into simply wrapping the arguments via `format_args!` instead of using a `write!` macro.

**Comment by Noratrieb** [comment]
sounds reasonable, feel free to make a PR adding it.
