### ISSUE TITLE
run-make: extract bootstrap cargo invocations to a proper `Command`

### ISSUE THREAD

**Issue by jieyouxu** [rust-lang/rust#128734]
Current bootstrap cargo incantations are nothing short of magic and are indecipherable. We should try to refactor them to proper `Command` wrappers.

```rs
let bootstrap_cargo = env_var("BOOTSTRAP_CARGO");
let mut cmd = cmd(bootstrap_cargo);
cmd.args(&[
    "build",
    "--manifest-path",
    manifest_path.to_str().unwrap(),
    "-Zbuild-std=core",
    "--target",
    &target,
])
.env("PATH", path)
.env("RUSTC", rustc)
...
```

**Comment by lolbinarycat** [comment]
any idea why these are explicitly inheriting environment variables? it's not like they call env_clear or anything...

**Comment by jieyouxu** [comment]
Sorry I didn't notice this issue, it's because at the time when I wrote run-make infra I just copied whatever the previous Makefile implementation did: it simply passed the already-available bootstrap cargo to run-make tests.

As discovered during a [beta backport](https://github.com/rust-lang/rust/pull/130569#issuecomment-2362802474) we found out that [run-make `-Z build-std` tests fail on `compiler_builtins` on older branches #130634](https://github.com/rust-lang/rust/issues/130634) because we [added some new `Cargo.lock` setup that the bootstrap cargo did not know how to handle, but which is present in a cargo that is built from sources by a stage1 rustc](https://github.com/rust-lang/rust/issues/130634#issuecomment-2364625860).

This particular issue is fixed by a combination of https://github.com/rust-lang/rust/pull/130642 and https://github.com/rust-lang/rust/pull/130739 where we properly ensuring a suitably-staged cargo in bootstrap is available, and passing a path to that cargo in compiletest (see https://github.com/rust-lang/rust/pull/130739 for details). We removed any `BOOTSTRAP_CARGO` in the test suite, run-make-support and compiletest.
