### ISSUE TITLE
regression: `pointee` is ambiguous

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#128888]
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/reg/ptr_meta-0.3.0-alpha.2/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/reg/rancor-0.1.0-alpha.9/log.txt

```
[INFO] [stdout] error[E0659]: `pointee` is ambiguous
[INFO] [stdout]    --> src/lib.rs:546:11
[INFO] [stdout]     |
[INFO] [stdout] 546 |         #[pointee]
[INFO] [stdout]     |           ^^^^^^^ ambiguous name
[INFO] [stdout]     |
[INFO] [stdout]     = note: ambiguous because of a name conflict with a builtin attribute
[INFO] [stdout]     = note: `pointee` could refer to a built-in attribute
```

#125575 cc @davidtwco @dingxiangfei2009

**Comment by lqd** [comment]
cc @dingxiangfei2009 @Darksonn

**Comment by Darksonn** [comment]
Thread on zulip: https://rust-lang.zulipchat.com/#narrow/stream/425075-rust-for-linux/topic/regression.3A.20pointee.20is.20ambiguous/near/459535999

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23128888.20regression.3A.20.60pointee.60.20is.20ambiguous)).

@rustbot label -I-prioritize +P-high
