### ISSUE TITLE
Create `Rc`/`Arc` directly from mut slice

### ISSUE THREAD

**Issue by eduardosm** [rust-lang/rust#128885]
Right now, we have
```rust
impl From<&CStr> for Rc<CStr>
impl From<&OsStr> for Rc<OsStr>
impl From<&Path> for Rc<Path>
impl From<&str> for Rc<str>
```
and their `Arc` counterparts.

Even though a mut slice can be coerced into a non-mut one, I think it would be useful to have versions that can directly take `&mut _`.

For example, to be able to do something like:

```rust
let s: Rc<str> = chr.encode_utf8(&mut [0; 4]).into(); // the trait bound `Rc<str>: From<&mut str>` is not satisfied
```

**Comment by jieyouxu** [comment]
This will need a [T-libs-api API Change Proposal (ACP)](https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html?highlight=Change%20Proposal#suitability-for-the-standard-library).

**Comment by eduardosm** [comment]
Implemented in https://github.com/rust-lang/rust/pull/129329.
