### ISSUE TITLE
regression: lifetimes cannot use keyword names

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#128897]
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/reg/with_locals-0.3.2/log.txt

```
[INFO] [stdout] error: lifetimes cannot use keyword names
[INFO] [stdout]  --> examples/main.rs:7:21
[INFO] [stdout]   |
[INFO] [stdout] 7 | fn hex (n: u32) -> &'ref dyn Display
[INFO] [stdout]   |                     ^^^^
```

[#126762](https://github.com/rust-lang/rust/pull/126762), crater run in [#126452 (comment)](https://github.com/rust-lang/rust/pull/126452#issuecomment-2179464266), accepted breakage? cc @compiler-errors

**Comment by compiler-errors** [comment]
Yep, this is known breakage. I believe @traviscross confirmed this with @danielhenrymantilla.

**Comment by traviscross** [comment]
@rustbot labels -I-prioritize

Indeed, we [accepted](https://github.com/rust-lang/rust/pull/126452#issuecomment-2179464266) this breakage.

**Comment by danielhenrymantilla** [comment]
@BoxyUwU if there is something you'd think I should/could be doing with my crate, library-wise, in this regard do tell me! 🙏

**Comment by compiler-errors** [comment]
If you'd like to update the library to stop using `'ref` then that would be the only actionable thing to do here.
