### ISSUE TITLE
regression: mismatched types (invalid pointer cast for trait objects)

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#128889]
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/reg/minfac-0.0.1/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/reg/saleae-0.1.0/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/reg/vsmtp-common-2.2.1/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/reg/vsmtp-protocol-2.2.1/log.txt

```
[INFO] [stdout] error[E0308]: mismatched types
[INFO] [stdout]   --> src/untyped.rs:26:11
[INFO] [stdout]    |
[INFO] [stdout] 26 |         &*(self.pointer as *const dyn Fn(&ServiceProvider) -> T)
[INFO] [stdout]    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `()`, found `(&ServiceProvider,)`
[INFO] [stdout]    |
[INFO] [stdout]    = note: expected trait object `dyn Fn()`
[INFO] [stdout]               found trait object `dyn for<'a> Fn(&'a ServiceProvider) -> T`
```

[#120248 (comment)](https://github.com/rust-lang/rust/pull/120248#issuecomment-1954441107) I believe is accepted breakage? cc @WaffleLapkin

**Comment by compiler-errors** [comment]
Yeah, this is known breakage I think. Or if it wasn't uncovered by the crater, I totally think we should reject it.

**Comment by WaffleLapkin** [comment]
I agree, all of this looks like code we intended to break.

The errors are unfortunately opaque though, I imagine users would have hard time figuring them out :(

**Comment by VorpalBlade** [comment]
@WaffleLapkin shouldn't this be turned into a diagnostic issue rather than closed if the error is subpar (which it looks like it is to me as well)?

**Comment by WaffleLapkin** [comment]
@VorpalBlade diagnostic issue _should_ be opened, but I have no spoons for that. Turning issues into issues for other topics is generally confusing, opening new issues is better.

**Comment by apiraino** [comment]
@VorpalBlade if you have capacity, please feel free to open such issue about diagnostic (backlinking this one). Thanks!

**Comment by VorpalBlade** [comment]
I have the capacity, but I don't have any idea what the diagnostic should be. I *don't* understand the current error message.

**Comment by riking** [comment]
The error is that someone's trying to smuggle `Fn`s of several different argument sets through a single variable of type `*const dyn Fn()` (no arguments) without a `transmute`.

**Comment by WaffleLapkin** [comment]
@apiraino @VorpalBlade I've opened https://github.com/rust-lang/rust/issues/130030 to track the diagnostic issue.
