### ISSUE TITLE
TCPListener fails/underperforms in cases with lots of new sockets (lots of users making few requests)

### ISSUE THREAD

**Issue by alshdavid** [rust-lang/rust#128856]
Hi all, I am not sure if this is the right place to discuss issues with the Rust stdlib (or if this is even an issue with the std lib) but here goes.

I've been pitching Rust as a language to adopt for use in http servers and have been running tests to build a case for that. 

In a test where many socket connections are created, I have stumbled upon perplexing results showing that http servers using the standard lib `TCPListener` have catastrophic performance when compared to other languages tested under the same conditions.

Granted, this is a test of http on top of TCPListener - however this is the most accessible/relevant form of benchmark that I have access to.

I first noticed this when testing hyper. When using `keep-alive` - the benchmark mimics "a few users making many requests". Hyper under these conditions outperforms everything. This aligns with the results of the [techempower](https://www.techempower.com/benchmarks/#section=data-r18&hw=ph&test=plaintext) benchmarks, Great!

To test a more realistic scenario, I changed the benchmark configuration so that the client disconnects and creates a new socket connection on every request - simulating "many users making few requests".

Under this configuration, all Rust http server implementations had a request failure rate of 75% while Go and Nodejs had a failure rate of 0%. The latency on the requests that succeeded were substantially worse than the Go and Nodejs cases.

I tried:
- Hyper
- Actix

Compared against 
- Go standard lib
- Nodejs standard lib

So I thought it could be Tokio or the http parsing logic so to eliminate variables, I tried
- Mayhttp
- Wrote a simple http server using `std::net::TCPListener` with a hardcoded response
- Wrote a simple http server using `tokio::net::TCPListener` with a hardcoded response
- Used jemalloc
- Used LTO on and off

Regardless of the approach, high numbers of new socket connections just performed poorly.

I asked about this in the Rust community forums and posted questions to the http library projects and in general the response has been not to put too much weight in benchmarks. I totally understand that, however when Nodejs and Go have a 0% failure rate on the same hardware and testing conditions, I am unable to make a compelling case to my team for Rust as an http server.

So I am wondering what's going on here?

Is this a skill issue/am I doing something wrong?
Is there something I can do to improve these results?
is this a problem with the Rust standard library?

Resources:
- [My question on the hyper GitHub](https://github.com/hyperium/hyper/issues/3728)
- [Benchmark results - happy case, validating previous benchmarks](https://alshdavid.github.io/rust-http-benchmarks/_reports/saved/r-1000_c-50000_keepalive-true.html)
- [Benchmark results - failure case, many sockets](https://alshdavid.github.io/rust-http-benchmarks/_reports/saved/r-500_c-10000_keepalive-false.html)
- [Sources - Tokio TCPListener directly](https://github.com/alshdavid/rust-http-benchmarks/blob/main/rust_tokio_raw/src/main.rs)
- [Sources - Hyper](https://github.com/alshdavid/rust-http-benchmarks/blob/main/rust_hyper/src/main.rs)
- [Sources - Go](https://github.com/alshdavid/rust-http-benchmarks/tree/main/go_std)
- [Sources - Nodejs](https://github.com/alshdavid/rust-http-benchmarks/blob/main/nodejs_std/index.js)

**Comment by the8472** [comment]
You already [asked this question](https://users.rust-lang.org/t/poor-performance-from-tcplistener/115005) on users.rlo. Please crosslink questions to avoid redundant work.
