### ISSUE TITLE
Vec/Str need an efficient way to shift() multi-items

### ISSUE THREAD

**Issue by liigo** [rust-lang/rust#12884]
to avoid copy/alloc/realloc memory.

in C or unsafe code, you just need to offset the `data` pointer and `len-=n`.

**Comment by steveklabnik** [comment]
Today, changes like this would require an RFC, so if you're interested in proposing these methods, you should write one up. :)

**Comment by bluss** [comment]
Vec::drain now provides this! As soon as a snapshot includes it, we can solve the fixme in the code with this issue's tag using `src.as_mut_vec().drain(..3)`.
