### ISSUE TITLE
`-Cmin-function-alignment`/`-Calign-functions` support in `rustc`

### ISSUE THREAD

**Issue by ojeda** [rust-lang/rust#128830]
i.e. the equivalents of `-fmin-function-alignment` ([GCC](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-fmin-function-alignment_003dn), Clang does not support it) / `-falign-functions` ([GCC](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-falign-functions), [Clang](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang1-falign-functions)).

For the Linux kernel, the behavior wanted is that of GCC's `-fmin-function-alignment` and Clang's `-falign-functions`, i.e. align all functions, including cold functions.

There is [`feature(fn_align)`](https://github.com/rust-lang/rust/issues/82232), but we need to do it globally.

**Comment by workingjubilee** [comment]
If a feature should be extended with a CLI flag, or at least have its interactions with such a flag considered before landing it, that should be brought up in that issue. Closing as duplicate for now.
