### ISSUE TITLE
Surprising case of UB arising from stacked borrow rules

### ISSUE THREAD

**Issue by dfoxfranke** [rust-lang/rust#128803]
This ticket arose from some toy programs I wrote while investigating the internals of the `ouroboros` crate and trying to wrap my head around what `AliasableDeref` is needed for, but the issue turned out to be more basic. Just to be sure that what I was seeing had nothing really to do with `core::ptr::Unique` or even with `NonNull`, I wrote a trivial box implementation that uses neither of these:

```rust
use std::{
    alloc::{alloc, dealloc, Layout},
    ops::{Deref, DerefMut},
};

struct MyBox<T>(*mut T);

impl<T> MyBox<T> {
    fn new(val: T) -> MyBox<T> {
        unsafe {
            let p: *mut T = alloc(Layout::new::<T>()).cast();
            assert!(!p.is_null());
            p.write(val);
            MyBox(p)
        }
    }
}

impl<T> Deref for MyBox<T> {
    type Target = T;

    fn deref(&self) -> &T {
        unsafe { self.0.as_ref().unwrap() }
    }
}

impl<T> DerefMut for MyBox<T> {
    fn deref_mut(&mut self) -> &mut T {
        unsafe { self.0.as_mut().unwrap() }
    }
}

impl<T> Drop for MyBox<T> {
    fn drop(&mut self) {
        unsafe {
            dealloc(self.0.cast(), Layout::new::<T>());
        }
    }
}
```

Now, the following program produces UB in MIRI:

```rust
fn main() {
    let mut b = MyBox::new(1);
    let p = std::ptr::addr_of_mut!(*b);
    *b = 2;
    assert_eq!( unsafe { p.read() }, 2);
}
```

```
error: Undefined Behavior: attempting a read access using <2415> at alloc1092[0x0], but that tag does not exist in the borrow stack for this location
  --> src/main.rs:45:26
   |
45 |     assert_eq!( unsafe { p.read() }, 2);
   |                          ^^^^^^^^
   |                          |
   |                          attempting a read access using <2415> at alloc1092[0x0], but that tag does not exist in the borrow stack for this location
   |                          this error occurs as part of an access at alloc1092[0x0..0x4]
   |
   = help: this indicates a potential bug in the program: it performed an invalid operation, but the Stacked Borrows rules it violated are still experimental
   = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
help: <2415> was created by a SharedReadWrite retag at offsets [0x0..0x4]
  --> src/main.rs:43:13
   |
43 |     let p = std::ptr::addr_of_mut!(*b);
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^
help: <2415> was later invalidated at offsets [0x0..0x4] by a Unique retag
  --> src/main.rs:29:18
   |
29 |         unsafe { self.0.as_mut().unwrap() }
```

But with a subtle change in how `p` is constructed, it runs cleanly:

```rust
fn main() {
    let mut b = MyBox::new(1);
    let p = b.0;
    *b = 2;
    assert_eq!( unsafe { p.read() }, 2);
}
```

The difference is that, even despite my use of `addr_of_mut!`, in the first version I'm temporarily creating a `&mut i32` returned by `deref_mut` and implicitly casting it to a `*mut i32`, rather than obtaining a `*mut i32` directly. This subtle distinction causes my pointer to be infected with stacked-borrow cooties, and become invalidated after assigning to `*b`. (Edit for clarification: it's not surprising that the reference is being created despite `addr_of_mut!`; I wasn't expecting that to do anything load-bearing, it's just how I habitually create pointers. What's surprising is that the transient existence of the reference matters at all, since it's valid).

This is quite counterintuitive, especially considering that the following practically line-for-line equivalent code is perfectly good C++:

```c++
#include <memory>
#include <cassert>

int main(void) {
    auto b = std::make_unique<int>(1);
    int *p = &*b;
    *b = 2;
    assert(*p == 2);
    return 0;
}
```

For Rust, even unsafe Rust, to contain a landmine like this seems to go very much against its philosophy, and I see it as indictment of the stacked borrow experiment, or at least the current iteration of its design.

cc @RalfJung

**Comment by saethlin** [comment]
You are just rediscovering https://github.com/rust-lang/unsafe-code-guidelines/issues/133.

**Comment by saethlin** [comment]
I don't think there's anything in this issue that is not already captured in the comments on ucg#133. So I'm going to close this and if you think you have something to add that's not already expressed on that issue, it would be much better for you to comment there.
