### ISSUE TITLE
library/std/src/sys/pal/unix/process/process_unix/tests.rs failed in odd arch

### ISSUE THREAD

**Issue by MinxuanZ** [rust-lang/rust#128816]
https://github.com/rust-lang/rust/blob/9337f7afa6fda07e60d6aa5ee88e692878446782/library/std/src/sys/pal/unix/process/process_unix/tests.rs#L26-L29

https://github.com/rust-lang/libc/blob/0e28c864c25d2e9b0ab082947445efccef213da4/src/unix/linux_like/linux/musl/b64/mips64.rs#L586-L589

https://github.com/rust-lang/libc/blob/0e28c864c25d2e9b0ab082947445efccef213da4/src/unix/linux_like/linux/gnu/b64/sparc64/mod.rs#L330-L333

I gusse In mips and sparc arch ,signal 19 is SIGPWR and SIGCONT

**Comment by workingjubilee** [comment]
Please feel free to PR using the libc constants into that test!
