### ISSUE TITLE
regression: linking with `cc` failed

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#128894]
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/gh/ecumene.discord_spin/log.txt

**Comment by bjorn3** [comment]
Looks like this crate is depending on two different version of wit-bindgen-rust. Both should define the same unmangled symbol, and as such a linker error is expected.

```
[INFO] [stderr]    Compiling wit-bindgen-rust v0.1.0 (https://github.com/bytecodealliance/wit-bindgen?rev=e9c7c0a3405845cecd3fe06f3c20ab413302fc73#e9c7c0a3)
[INFO] [stderr]    Compiling wit-bindgen-rust v0.1.0 (https://github.com/bytecodealliance/wit-bindgen?rev=2f46ce4cc072107153da0cefe15bdc69aa5b84d0#2f46ce4c)
```

**Comment by apiraino** [comment]
Is this crate in a shape to still be relevant to our crater runs? :thinking: 

I see a slew of warnings when trying to compile it from clean slate (i.e. installing the needed toolchains)

**Comment by bjorn3** [comment]
It also depends on an outdated wit-bindgen version which I'm not sure will work with current component model implementations.
