### ISSUE TITLE
Calling last() on Vec panics even though Vec contains elements

### ISSUE THREAD

**Issue by GregoryMJohn** [rust-lang/rust#128931]
Here is a snippet of code from a project I've been working on:

```
assert!(!self.head_stack.is_empty());

while !matches!(
    self.head_stack.last().unwrap().op,
    Op::Call | Op::Tuple | Op::Expr | Op::Block
) {
    self.reduce()
}
```
which should call reduce() on self in the while loop if self.head_stack isn't empty. The weird thing is that the assert is successful, but the unwrap panics on a None. I can't figure out why the Vec would suddenly be empty on the next line after the assert, as this is just single threaded code. I'm using the latest stable compiler version (1.8.0 I think).

Here's a backtrace: 
`thread 'main' panicked at src/parser.rs:238:60:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:146:5
   3: core::option::unwrap_failed
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/option.rs:1985:5
   4: core::option::Option<T>::unwrap
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/option.rs:935:21
   5: fomorian::parser::Parser::parse_line
             at ./src/parser.rs:238:10
   6: fomorian::parser::Parser::parse
             at ./src/parser.rs:80:17
   7: fomorian::compiler::compile_obj
             at ./src/compiler.rs:33:2
   8: fomorian::main
             at ./src/bin/fomorian.rs:8:2
   9: core::ops::function::FnOnce::call_once
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:250:5`

**Comment by y21** [comment]
Does `self.reduce()` remove elements from `self.head_stack`? That could lead to an empty vec on the next iteration.

**Comment by GregoryMJohn** [comment]
> Does `self.reduce()` remove elements from `self.head_stack`? That could lead to an empty vec on the next iteration when the loop condition is checked again.

It does! I don't know why, but I had assumed it was panicking on the first iteration. But now that you mention it, it makes perfect sense. Thanks!
