### ISSUE TITLE
compiletest: we should not allow revision names that collide with builtin cfg names

### ISSUE THREAD

**Issue by jieyouxu** [rust-lang/rust#128964]
Example: https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/error.3A.20unexpected.20.60--cfg.20windows.60.20flag/near/459869068

```
--- stderr -------------------------------
error: unexpected `--cfg windows` flag
  |
  = note: config `windows` is only supposed to be controlled by `--target`
  = note: manually setting a built-in cfg can and does create incoherent behaviors
  = note: `#[deny(explicit_builtin_cfgs_in_flags)]` on by default

error: aborting due to 1 previous error
```

compiletest will try to set a `--cfg <revision_name>` that matches the revision name, but this goes poorly if the `<revision_name>` collides with a builtin cfg. Builtin cfgs can be found at https://github.com/rust-lang/rust/blob/c9bd03cb724e13cca96ad320733046cbdb16fbbe/compiler/rustc_session/src/config/cfg.rs#L90, but we should also deny `test` revision name because it has special meaning `cfg(test)`.

**Comment by Urgau** [comment]
This could (and should IMO) be accomplished using the (currently unstable) [`--print=check-cfg` option](https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/print-check-cfg.html), which list all the well known cfgs.

**Comment by heysujal** [comment]
Hi, I would like to work on this issue and will be going through the contribution docs. I don't have prior experience using Rust.
