### ISSUE TITLE
vec.reverse() deletes elements

### ISSUE THREAD

**Issue by Cr0a3** [rust-lang/rust#128940]
I tried this code:

```rust
let mut res = vec![];

if registry.backend.currStackOffsetForLocalVars != 0 || registry.backend.stackSafe {
    res.push( Instr::with1(Mnemonic::Push, Operand::Reg(x64Reg::Rbp.boxed())) );
    res.push( Instr::with2(Mnemonic::Mov, Operand::Reg(x64Reg::Rbp.boxed()), Operand::Reg(x64Reg::Rsp.boxed())) );
    res.push( Instr::with2(Mnemonic::Sub, Operand::Reg(x64Reg::Rsp.boxed()), Operand::Imm(16)) );
}

for backuped in &registry.backend.saveRegister {
    res.push( Instr::with1(Mnemonic::Push, Operand::Reg(backuped.boxed())) )
}

res.reverse();

res
```
(here's the entire file: https://github.com/Cr0a3/ygen/blob/main/src/Target/x64/ir.rs#L383-L397)

I expected to see that my output of my programm (the other systems just work fine I tested each invidually) would be:
```
// made using Ygen v0.1.1
// by Cr0a3

section .text

global add
add:
	push rbp
        mov rbp, rsp
        sub rsp, 16
	push rcx
	mov edx, [ rbp  ]
	mov ecx, [ rbp - -4 ]
	call 4
	add rsp, 16
	pop rbp
	ret
global extern
```

Instead, this happened:
```
// made using Ygen v0.1.1
// by Cr0a3

section .text

global add
add:
	sub rsp, 16
	push rcx
	mov edx, [ rbp  ]
	mov ecx, [ rbp - -4 ]
	call 4
	add rsp, 16
	pop rbp
	ret
global extern
```

Which means the two first vector elements got deleted

### Meta

`rustc --version --verbose`:
```
rustc 1.79.0 (129f3b996 2024-06-10)
binary: rustc
commit-hash: 129f3b9964af4d4a709d1383930ade12dfe7c081
commit-date: 2024-06-10
host: x86_64-pc-windows-msvc
release: 1.79.0
LLVM version: 18.1.7
```

</p>
</details>

**Comment by ChrisDenton** [comment]
Try adding a `dbg!` statement both before and after the `reverse` call.

**Comment by workingjubilee** [comment]
@Cr0a3 Hi! Can you include either
- the *full program*, not a *library*, as a library is not an executable
- the failing library test

**Comment by workingjubilee** [comment]
Until then I cannot replicate the problem:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b1bb935660ac46705d9bbde37e72d8db

**Comment by workingjubilee** [comment]
@Cr0a3 I am assuming you closed this because you found a bug in your program that instead explains the omission. My condolences, and please feel free to report any new bugs you find in the stdlib... with reproduction instructions.

**Comment by Cr0a3** [comment]
Yes a bit embarrassing. Thank you for your help and time. Next time I will really check all my systems. Sorry 😔

**Comment by Cr0a3** [comment]
I maybe found one other bug. But I need to test first if it's my fault. (Sometimes when overwriting files other old texts are just left behind, or it's just some visual glitch because my laptop is so slow)

**Comment by workingjubilee** [comment]
Writing to files is very touchy, especially if you wind up doing any concurrency. Many of std's APIs fail to provide very strong guarantees about writing to files because we _can't_, certainly not in a cross-platform way. I strongly recommend, when overwriting files, if you aren't absolutely sure that the overwriting is correct, to use the "rename-transaction" style: write a new file with a unique name (use a UUID or something in its filename), then rename it over the old file. There are better ways, but that is the approach that works on most systems.
