### ISSUE TITLE
regression: adding a def'n for node-id NodeId(597) and def kind AnonConst but a previous def'n exists

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#128901]
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/gh/JustFiesta.carMaintenance/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/gh/NasreddinHodja.rams/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/gh/ascii-dresden.ascii-prepaid-system/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/gh/georgebarwood.RustWeb2/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/gh/glaubervictor.rust-graphql-mongodb/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/gh/lawliet89.himitsu/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/gh/logan-smith.api-exercise/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/gh/newpavlov.rustrush-crypto-workshop/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/gh/purpleprotocol.purplecoin_cli/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/gh/styrowolf.encryptor/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/reg/file_endec-1.0.1/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/reg/libpasta-0.1.2/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/reg/purplecoincli-0.1.6/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/reg/rustdb-axum-example-0.3.3/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/reg/flatbox_render-0.1.0/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/reg/flatbox_egui-0.1.0/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/reg/flatbox_systems-0.1.0/log.txt

```
[INFO] [stderr] thread 'rustc' panicked at compiler/rustc_ast_lowering/src/lib.rs:503:9:
[INFO] [stderr] adding a def'n for node-id NodeId(597) and def kind AnonConst but a previous def'n exists: DefKey { parent: Some(DefIndex(57)), disambiguated_data: DisambiguatedDefPathData { data: AnonConst, disambiguator: 0 } }
[INFO] [stderr] stack backtrace:
[INFO] [stderr]    0:     0x7f847c87e3a5 - std::backtrace_rs::backtrace::libunwind::trace::hec2dc58314f3b5ff
[INFO] [stderr]                                at /rustc/08328a323ecd80b443a8fcc72c6b1071f48e233f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
[INFO] [stderr]    1:     0x7f847c87e3a5 - std::backtrace_rs::backtrace::trace_unsynchronized::h331ee0b0169d7b05
[INFO] [stderr]                                at /rustc/08328a323ecd80b443a8fcc72c6b1071f48e233f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
```

duplicate of #128016

**Comment by jieyouxu** [comment]
cc https://github.com/rust-lang/rust/pull/128760, included in https://github.com/rust-lang/rust/pull/129033

**Comment by lqd** [comment]
Meh, no need for the milestone, it's equally confusing: initially seen on 1.81, but reverted as mentioned above.

**Comment by apiraino** [comment]
I'm going to close this since #129033 has been merged
