### ISSUE TITLE
Outdated docs claim that `#[repr(transparent)]` on empty structs is not permitted

### ISSUE THREAD

**Issue by scovich** [rust-lang/rust#129029]
This code compiles:

```rust
#[repr(transparent)] struct Foo {}
```

Going by the docs for [`#[repr(transparent)]`](https://doc.rust-lang.org/nomicon/other-reprs.html#reprtransparent):
> `#[repr(transparent)]` can only be used on a struct or single-variant enum that has a single non-zero-sized field (there may be additional zero-sized fields). The effect is that the layout and ABI of the whole struct/enum is guaranteed to be the same as that one field.

... it seems like the compiler should reject that code, with diagnostics similar to those it emits for an [empty transparent enum](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0e714ff278e6910f8a6d519aa654b6be):
```
error[E0084]: unsupported representation for zero-variant enum
 --> src/lib.rs:2:1
  |
2 | #[repr(transparent)] enum E {}
  | ^^^^^^^^^^^^^^^^^^^^ ------ zero-variant enum

error[E0731]: transparent enum needs exactly one variant, but has 0
 --> src/lib.rs:2:22
  |
2 | #[repr(transparent)] enum E {}
  |                      ^^^^^^ needs exactly one variant, but has 0

Some errors have detailed explanations: E0084, E0731.
```

**Comment by compiler-errors** [comment]
This regressed somewhere in 1.55

**Comment by compiler-errors** [comment]
This is intentional: https://github.com/rust-lang/rust/pull/86279

**Comment by compiler-errors** [comment]
Notably, the difference between empty (variantless) enums and empty (fieldless) structs are that the former are *uninhabited*. Fieldless structs just have 0 size.

**Comment by compiler-errors** [comment]
Actually, is the reference out of date? The reference says:

> The transparent representation can only be used on a [struct](https://doc.rust-lang.org/reference/items/structs.html) or an [enum](https://doc.rust-lang.org/reference/items/enumerations.html) with a single variant that has:
>     * a single field with non-zero size, and
>     * any number of fields with size 0 and alignment 1

**Comment by compiler-errors** [comment]
We should update the reference anyways to note this change in rules. I still don't consider this to be a bug according to these rules: 

https://github.com/rust-lang/rust/issues/77841#issuecomment-716575747

**Comment by scovich** [comment]
Yes, reading the RFC, there is no bug, but the stale documentation needs to be fixed so people are not misled.
