### ISSUE TITLE
`missing_fragment_specifier` points at the wrong span if followed by another metavariable

### ISSUE THREAD

**Issue by tgross35** [rust-lang/rust#129077]
This:

```rust
macro_rules! foo {
    ($bar) => {};
    ($baz $qux:ident) => {};
}
```

Produces:

```text
error: missing fragment specifier
 --> src/lib.rs:2:6
  |
2 |     ($bar) => {};
  |      ^^^^

...

error: missing fragment specifier
 --> src/lib.rs:3:11
  |
3 |     ($baz $qux:ident) => {};
  |           ^
```

Notice for the second pattern, the diagnostic points at `$qux` rather than `$baz`. `$qux` is not a problem here, the span should look similar to `$bar`.

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=11ae576f5ce6e77fbad782f6c013ba76

Tested on both 1.80 and the 2024-08-13 nightly. This affects the new diagnostic that applies to e2024 added in https://github.com/rust-lang/rust/pull/128006, as well as the existing lint (I noticed it looking at the reports in https://github.com/rust-lang/rust/pull/128425).

**Comment by tgross35** [comment]
It seems like the span at https://github.com/tgross35/rust/blob/2b78d920964e1d70927bcd208529bda0e11120d0/compiler/rustc_expand/src/mbe/macro_check.rs#L268 must be wrong, which probably means this shows up other places.

**Comment by fmease** [comment]
Duplicate of #95463.

**Comment by tgross35** [comment]
Ah yup, thanks.
