### ISSUE TITLE
`if let` not possible in short-hand syntax?

### ISSUE THREAD

**Issue by abzr1** [rust-lang/rust#129004]
This code doesn't work as I expected:

```rs
fn main() {
    let x: Option<i32> = None;

    let y = if let _ = x {
        1
    } else {
        2
    };
}
```

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b6b55e27cbe381ea3918eb4a188c99d9)

I get the error:

```rs
warning: irrefutable `if let` pattern
 --> src/main.rs:4:16
  |
4 |     let y = if let z = x {
  |                ^^^^^^^^^
  |
  = note: this pattern will always match, so the `if let` is useless
  = help: consider replacing the `if let` with a `let`
  = note: `#[warn(irrefutable_let_patterns)]` on by default
```

I expected `y` to be assigned the value `2`. Am I doing something wrong?

**Comment by Noratrieb** [comment]
why do you expect `y` to be `2`? the pattern `let _ = x` always matches, so it enters the true path, resulting in `1` (as the warning tells you). is there anything that could be improved in the warning message to make that clearer?

**Comment by abzr1** [comment]
@Noratrieb apologies, I am returning to Rust after a while with Swift and got confused with how `if let` works. What I should have written is `if let Some(_) = x` and it now works.
