### ISSUE TITLE
Expand the unsafe & low-level guide to cover static mut, more #[no_std], modern `asm!`

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#12905]
The [unsafe & low-level code guide](http://static.rust-lang.org/doc/master/guide-unsafe.html) added in https://github.com/mozilla/rust/pull/12887 should cover:

- [ ] `transmute`/casting
- [ ] the `Unsafe` type (for inner mutability)
- [ ] the relevance of the various kinds (i.e. `Sync` etc.), and when to apply the types in `std::kinds::marker` to ensure safety
- [ ] `static mut`, including atomics and static mutexes
- [ ] `#[no_std]` in more detail: I don't know enough about the correct compilation flags, and symbols required, so that section is rather loose on detail
- [ ] the `asm!` syntax described isn't 100% up-to-date; I took it from the description in the 0.6 release notes, and there have been extensions and improvements since that was written.

**Comment by steveklabnik** [comment]
Okay, so at this point:

-    transmute/casting - covered in the casting chapter
-   the Unsafe type (for inner mutability) - would be nice to have in a guide, but api docs work too
-    the relevance of the various kinds - same
-    static mut, including atomics and static mutexes - covered in the statics chapter, could beef up atomics/mutexes though
-    #[no_std] in more detail: - has its own chapter
-    the asm! syntax - has its own chapter.

as such, I'm going to give this a close. Adding a "building unsafe abstractions safely" chapter would be nice for Effective Rust, but I'm not leaving tickets open for possible chapters right now.
