### ISSUE TITLE
`./configure --help` should print `--disable-docs` instead of `--enable-docs`

### ISSUE THREAD

**Issue by dilyanpalauzov** [rust-lang/rust#129146]
With rust 1.80 ./configure --help prints:
```
        --enable-docs                  build standard library documentation 
```
This means, that by default the standard librarly documentation is not built, but with this option it can be turned on.

However, config.example.toml contains
```
# Whether to build documentation by default. If false, rustdoc and
# friends will still be compiled but they will not be used to generate any
# documentation.
#
# You can still build documentation when this is disabled by explicitly passing paths,
# e.g. `x doc library`.
#docs = true
```
For me the last line means, that by default the documentation is build.  Indeed, `./configure --disable-docs` puts in config.toml: `docs = false`.

* Change the output of `./configure --help` from `--enable-docs` to `--disable-docs` to indicate what actions users should take in order to deviate from the default.

**Comment by saksham-agarwal-dev** [comment]
` 
    print('')
    print('This configure script is a thin configuration shim over the true')
    print('configuration system, `config.toml`. You can explore the comments')
    print('in `config.example.toml` next to this configure script to see')
    print('more information about what each option is. Additionally you can')
    print('pass `--set` as an argument to set arbitrary key/value pairs')
    print('in the TOML configuration if desired')
    print('')
    print('Also note that all options which take `--enable` can similarly')
    print('be passed with `--disable-foo` to forcibly disable the option')
`

Right after printing the --enable-docs, there is also this disclaimer. 

I am a first-time contributor to Rust.
Should I add some conditional logic for checking what the default value for that option is and printing --enable-{} or --disable-{} based on that default?

Thanks for the guidance.

**Comment by arin-r** [comment]
> Should I add some conditional logic for checking what the default value for that option is and printing --enable-{} or --disable-{} based on that default?

I believe default option for building docs is true, that is, documentation is built by default.

**Comment by saksham-agarwal-dev** [comment]
Hi, I got that.
My question was whether should I add some conditional logic to check if the default value for any given option is true or false.
Right now, the script doesn't care if something is enabled or disabled by default, it only prints --enable-{option}. 

I am thinking we need to somehow get the default values for each option and print --enable or --disable accordingly.

**Comment by saksham-agarwal-dev** [comment]
https://github.com/rust-lang/rust/pull/130125

**Comment by onur-ozkan** [comment]
> Change the output of ./configure --help from --enable-docs to --disable-docs to indicate what actions users should take in order to deviate from the default.

This will still be a problem in the future. I'm sure there are other unsynced flags in `configure --help`. We should probably change how we write the helper docs. Instead of printing `enable-$option`, we should make it clearer that users can control options with `enable` and `disable`.

**Comment by dilyanpalauzov** [comment]
> Instead of printing enable-$option, we should make it clearer that users can control options with enable and disable.

`--help` should indicate what is the default and how to change it.  Currently it does not say what the default is.

**Comment by onur-ozkan** [comment]
> --help should indicate what is the default and how to change it.

What makes you think that?

**Comment by dilyanpalauzov** [comment]
All `--help` output of autoconf, etc. should work in similar way.  As the output is short, for each option there should be indication what the default is (static, auto=or depends on parameters discovered while running the configure-script).  And it should indicate how to change the default.  Obviously there is no point to pass parameters, which trigger anyway the default behaviour and the output of `--help` should suggest only how to deviate from the defaults, not how to keep the defaults.

**Comment by onur-ozkan** [comment]
`configure` is nothing like `autoconf`. It's just a wrapper for [this python script](https://github.com/rust-lang/rust/blob/4ae36d906f7f509e63aaa7ea99fdbefd1463eb96/src/bootstrap/configure.py) and most default (as some of them defined in config profiles) values are managed by the rust side bootstrap. We can't display default values in the `configure` script because it's a different program and it's not possible until we remove the python programs and handle everything from single program (which is our plan). Until then, I think [this](https://github.com/rust-lang/rust/issues/129146#issuecomment-2365819931) should be useful enough.

**Comment by jieyouxu** [comment]
Fixed by https://github.com/rust-lang/rust/pull/131117.

**Comment by dilyanpalauzov** [comment]
The problem report here is, that `--help` does not indicate, if a feature is by default on or off.  In turn it does not show how to deviate from the default (and suppress information how to enforce the default).

https://github.com/rust-lang/rust/pull/131117 is not a fix to the problem addressed here. If you are not willing to show on `--help` what the defaults are, if no parameters are passed, is a different story.

I wrote an article on whether to print `--enable-M` or `--disable-M` on `--help` : https://ab.bapha.be/posts/help-output/.

**Comment by onur-ozkan** [comment]
This is not a valid issue anymore, please open another one if you think `--help` behaviour should be different.
