### ISSUE TITLE
Include miri in config.example.toml[build] # tools=

### ISSUE THREAD

**Issue by dilyanpalauzov** [rust-lang/rust#129171]
In the past, the default tools=[...] in config.toml included Miri.  The default of building Miri was removed at https://github.com/rust-lang/rust/issues/100134 and https://github.com/rust-lang/rust/pull/102028.  The latter is called “Do not build Miri by default”, and as it changes 1211 files obviously I do not follow what exactly it does.

In any case, as in rustc-1.80.1-src.tar.xz:config.example.toml[build] # tools = [ "cargo", "clippy", "rustdoc", "rustfmt", "rust-analyzer", "rust-analyzer-proc-macro-srv", "analysis", "src", "rust-demangler",  # if profiler = true] 

does not include miri, my understanding is that 

> $ ../configure  --enable-optimize-llvm --enable-extended --llvm-root=/usr/local --enable-profiler --enable-llvm-link-shared --enable-sanitizers --enable-local-rust --disable-docs --target=x86_64-unknown-linux-gnu

and 

> $ ../configure  --enable-optimize-llvm --enable-extended --llvm-root=/usr/local --enable-profiler --enable-llvm-link-shared --enable-sanitizers --enable-local-rust --disable-docs --target=x86_64-unknown-linux-gnu --tools=cargo,clippy,rustdoc,rustfmt,rust-analyzer,analysis,src,rust-demangler

should produce identical result (except for rust-analyzer-proc-macro-srv).  But the first `./configure` does lead to installing Miri, while the second skips installing Miri.

As my observation is that now Miri is built by default (is part of the implicit tools=[…]), in config.example.toml tools= should indclude miri.

To be precise the first ./configure I ran against  rustc-1.79.0-src.tar.xz and the second against rustc-1.80.1-src.tar.xz.

**Comment by saethlin** [comment]
> The default of building Miri was removed at https://github.com/rust-lang/rust/issues/100134 and https://github.com/rust-lang/rust/pull/102028

That PR shipped with Rust 1.66 so I'm not sure why you are linking it when you seem to be intending to report a change from Rust 1.79 to Rust 1.80.

**Comment by dilyanpalauzov** [comment]
I am not reporting a changbe between 1.79 and 1.80.

I am saying that old Rust versions built Miri by default (miri was in the implicit tools=[]), then it was removed from tools=[], and now miri is again in the implicit tools=[], but not in config.example.toml:tools=[...]

**Comment by RalfJung** [comment]
> Miri was removed at https://github.com/rust-lang/rust/issues/100134 and https://github.com/rust-lang/rust/pull/102028. The latter is called “Do not build Miri by default”

The latter is called "Make miri a subtree instead of a submodule", which should give you an idea of why it changes so many files. ;)

> I am saying that old Rust versions built Miri by default (miri was in the implicit tools=[]), then it was removed from tools=[], and now miri is again in the implicit tools=[], but not in config.example.toml:tools=[...]

Cc @rust-lang/bootstrap ; I don't know if this was a deliberate change or not or how the implicit "tools" array is even computed. Miri is a nightly-only tool so we probably do not want it to be built implicitly on stable.

**Comment by onur-ozkan** [comment]
> Cc @rust-lang/bootstrap ; I don't know if this was a deliberate change or not or how the implicit "tools" array is even computed. Miri is a nightly-only tool so we probably do not want it to be built implicitly on stable.

For dev/nightly channels, we simply build every tool by default:

https://github.com/rust-lang/rust/blob/f04f6ca36d2439375d20a98be013384afbab0782/src/bootstrap/src/core/build_steps/tool.rs#L1029-L1042

If channel isn't dev/nightly, we only build tools are are marked as `stable=true` [here](https://github.com/rust-lang/rust/blob/f04f6ca36d2439375d20a98be013384afbab0782/src/bootstrap/src/core/build_steps/tool.rs#L1096-L1106) and (although cargo-miri is) Miri isn't one of them.

**Comment by RalfJung** [comment]
Okay so if the sample config.toml is supposed to show the default it should show both of these, presumably?

**Comment by onur-ozkan** [comment]
> Okay so if the sample config.toml is supposed to show the default it should show both of these, presumably?

Done that in #129243 (https://github.com/rust-lang/rust/pull/129243/commits/a629a0bd436464de036dbbfd53211c1b67ea89a3)
