### ISSUE TITLE
Add `f16` and `f128` to `tests/ui/consts/const-float-bits-conv.rs`

### ISSUE THREAD

**Issue by tgross35** [rust-lang/rust#129163]
This file is only `f32` and `f64`: https://github.com/rust-lang/rust/blob/a73bc4a131d94eba633c4c572a28e0bf94a67530/tests/ui/consts/const-float-bits-conv.rs, but we should add the other float types to this test.

The change should wait for https://github.com/rust-lang/rust/pull/128598 since that changes some of these semantics (this PR is almost merged).

There are probably a handful of tests that only check `f32` and `f64` but could use updates with the new types.

**Comment by rezwanahmedsami** [comment]
Okay will do that

**Comment by tgross35** [comment]
FYI you can comment `@rustbot claim` to assign yourself an issue
