### ISSUE TITLE
add support for OpenSearch to rustdoc

### ISSUE THREAD

**Issue by lolbinarycat** [rust-lang/rust#129180]
this would mainly be useful for searching the standard library directly from the browser search bar without waiting for the site to load first, but it could also be used for common crates like serde, or multi-crate documentation pages (eg. the nightly-rustc documentation)

**Comment by workingjubilee** [comment]
Duplicate with https://github.com/rust-lang/rust/issues/24899 which describes why this is probably *not* happening: our "search engine" is client-side JS and an index delivered on page load.
