### ISSUE TITLE
Rustdoc should show [src] link for methods

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#12932]
Test case:

``` rust
#[crate_id="foo"];
pub struct Foo;

impl Foo {
    #[unstable] pub fn foo(&self) {}
}
```

**Comment by steveklabnik** [comment]
Triage: no src link on methods as of today.

**Comment by birkenfeld** [comment]
We have [src] for impls now. Is that enough?

**Comment by SimonSapin** [comment]
@birkenfeld Did this just land? I can’t find these links in https://doc.rust-lang.org/std/ Is it only trait impls on inherent as well?

In any case it’s an improvement, but some `impl` blocks are very large and source links on individual methods would still be useful in my opinion.

**Comment by birkenfeld** [comment]
@SimonSapin yep, it was merged recently: https://github.com/rust-lang/rust/pull/33382 and works for both kinds of impls. It should be visible in the nightly docs already. There appear to be some problems with linking to impls pulled from `core` to `std`, I planned to investigate if that's fixable later.

**Comment by QuietMisdreavus** [comment]
I've opened #43509 to fix this.
