### ISSUE TITLE
Option::get_or_insert(_with) incorrectly documented as experimental

### ISSUE THREAD

**Issue by iamthad** [rust-lang/rust#129326]
### Location

Documentation of [`std::option::Option`](https://static.rust-lang.org/doc/master/std/option/enum.Option.html).

### Summary

The documentation for [`get_or_insert`](https://static.rust-lang.org/doc/master/std/option/enum.Option.html#method.get_or_insert) and [`get_or_insert_with`](https://static.rust-lang.org/doc/master/std/option/enum.Option.html#method.get_or_insert_with) lists them as nightly-only experimental APIs under the `option_entry` feature, but that feature was stabilized in 1.20.0 according to #39288

**Comment by cyrgani** [comment]
That documentation page appears to be horribly out of date, the current page hosting the documentation shows it als stable: [`get_or_insert_with`](https://doc.rust-lang.org/std/option/enum.Option.html#method.get_or_insert_with).

**Comment by iamthad** [comment]
My mistake; I saw `rust-lang.org` in the URL and thought I was in the right place.
