### ISSUE TITLE
Tracking Issue for `ptr::fn_addr_eq`

### ISSUE THREAD

**Issue by Urgau** [rust-lang/rust#129322]
Feature gate: `#![feature(ptr_fn_addr_eq)]`

This is a tracking issue for `std::ptr::fn_addr_eq`

> Compares the *addresses* of the two function pointers for equality.

### Public API

```rust
// core::ptr

/// Compares the *addresses* of the two function pointers for equality.
///
/// Function pointers comparisons can have surprising results since
/// they are never guaranteed to be unique and could vary between different
/// code generation units. Furthermore, different functions could have the
/// same address after being merged together.
///
/// This is the same as `f == g` but using this function makes clear
/// that you are aware of these potentially surprising semantics.
pub fn fn_addr_eq<T: FnPtr, U: FnPtr>(f: T, g: U) -> bool {
    f.addr() == g.addr()
}
```

### Steps / History

- [X] ACP: https://github.com/rust-lang/libs-team/issues/323
- [x] Implementation: #129323 and #131457
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by Urgau** [comment]
T-lang as [started an FCP](https://github.com/rust-lang/rust/pull/118833#issuecomment-2417493418) for adding a lint against function pointer comparisons and would like to use this method `ptr::fn_addr_eq` [as recommendation to suppress the lint and hang documentation about caveats](https://github.com/rust-lang/rust/pull/118833#issuecomment-2417496864).

## Stabilization Report

### Implementation History

 - https://github.com/rust-lang/rust/pull/129323
 - https://github.com/rust-lang/rust/pull/131457 *(waiting on review, but I don't prevent FCP)*

### API Summary

```rust
// core::ptr

/// Compares the *addresses* of the two function pointers for equality.
///
/// Function pointers comparisons can have surprising results since
/// they are never guaranteed to be unique and could vary between different
/// code generation units. Furthermore, different functions could have the
/// same address after being merged together.
///
/// This is the same as `f == g` but using this function makes clear
/// that you are aware of these potentially surprising semantics.
pub fn fn_addr_eq<T: FnPtr, U: FnPtr>(f: T, g: U) -> bool {
    f.addr() == g.addr()
}
```

### The [`std::marker::FnPtr`](https://doc.rust-lang.org/std/marker/trait.FnPtr.html) bound

The `FnPtr` marker trait is not stable and would be not stabilized by this FCP, but this commits us to having such trait (even in this unstable form).

-----

cc @rust-lang/lang *(regarding the `FnPtr` bound)*
cc @rust-lang/libs-api

**Comment by dtolnay** [comment]
@rfcbot fcp merge

**Comment by traviscross** [comment]
@rfcbot reviewed

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by traviscross** [comment]
@rustbot labels -I-lang-nominated

We discussed this in triage today.  We've now unanimously checked off on the lang side.  We appreciate @rust-lang/libs-api for moving this forward in support of the pending lang work.
