### ISSUE TITLE
`#[naked]` attribute excludes use of `#[repr(align(N))]`

### ISSUE THREAD

**Issue by erin-desu** [rust-lang/rust#129412]
I tried this code:

```rust
#[repr(align(4))]
#[naked]
extern "C" fn handle_trap_entry() -> !
{ … }
```

I expected to see this happen:
Code compiling just fine

Instead, this happened:
```rs
error[E0736]: attribute incompatible with `#[naked]`
  --> kernel/src/arch/riscv64/trap.rs:30:1
   |
30 | #[repr(align(4))]
   | ^^^^^^^^^^^^^^^^^ the `repr` attribute is incompatible with `#[naked]`
31 | #[naked]
   | -------- function marked with `#[naked]` here
```

### Meta

`rustc --version --verbose`:
```
rustc 1.82.0-nightly (a32d4a0e8 2024-08-21)
binary: rustc
commit-hash: a32d4a0e822a29a6682e08b75a8df4c29c7fa9f1
commit-date: 2024-08-21
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 19.1.0
```

It is a regression, as this was originally supported (last tried on):
```
rustc 1.81.0-nightly (6be96e386 2024-07-09)
binary: rustc
commit-hash: 6be96e3865c4e59028fd50396f7a46c3498ce91d
commit-date: 2024-07-09
host: x86_64-unknown-linux-gnu
release: 1.81.0-nightly
LLVM version: 18.1.7
```

<details><summary>Backtrace</summary>
<p>
N/A
</p>
</details>

**Comment by workingjubilee** [comment]
huh, wild. did it actually have the desired codegen properties?

**Comment by jdonszelmann** [comment]
this combines two unstable features, repr on functions (#82232) and naked functions (#90957), but the fix should be easy by adding it to [this allowlist](https://github.com/rust-lang/rust/blob/0f6e1ae67854c3c44726e8376144c16b465fe7c6/compiler/rustc_passes/src/check_attr.rs#L496C15-L496C25)

**Comment by jdonszelmann** [comment]
(I just wrote a test for it, if it works I'll make a PR if that's okay)

**Comment by folkertdev** [comment]
some context: https://github.com/rust-lang/rust/pull/127853 introduced the allowlist, and this attribute was left out because we were unsure if it would come up. Clearly it has, so this seems fine to allow.
