### ISSUE TITLE
Debugging rust compiler with lldb, unable to display variables

### ISSUE THREAD

**Issue by jianghupt** [rust-lang/rust#129440]
I compiled https://github.com/rust-lang/rust/
./x.py build --stage2 .
And set
[rust]
debug=true
[llvm]
assertins=true

Then I debugged it through lldb, and the command :fr v did not display the variables

How should I make lldb display the variables

![image](https://github.com/user-attachments/assets/fa5e9af9-53de-425a-9959-4b435142a0ad)

**Comment by saethlin** [comment]
Honestly, you shouldn't. 

If you want the kind of debugging your get from a debug build, you need to set 
```
[rust]
optimize = 0

```
But please read this paragraph: https://github.com/rust-lang/rust/blob/b5723af3457b9cd3795eeb97e9af2d34964854f2/config.example.toml#L460

**Comment by jianghupt** [comment]
> Honestly, you shouldn't.
> 
> If you want the kind of debugging your get from a debug build, you need to set
> 
> ```
> [rust]
> optimize = 0
> ```
> 
> But please read this paragraph:
> 
> https://github.com/rust-lang/rust/blob/b5723af3457b9cd3795eeb97e9af2d34964854f2/config.example.toml#L460

I tried it, but the variable still cannot be printed.
[rust]
optimize = false

**Comment by khuey** [comment]
debug = true isn't really sufficient for an interactive debugging experience. You need debuginfo-level = 2 (the default with debug = true is debuginfo-level = 1) to get variable information.

**Comment by jianghupt** [comment]
> debug = true isn't really sufficient for an interactive debugging experience. You need debuginfo-level = 2 (the default with debug = true is debuginfo-level = 1) to get variable information.

thank you, you are right
