### ISSUE TITLE
"rustc unexpectedly overflowed its stack!" during cargo test

### ISSUE THREAD

**Issue by merehap** [rust-lang/rust#129423]
In my personal project, I modified a new type struct called Type to be a two-variant enum instead: https://github.com/merehap/splitbits/commit/5fde25b5a8ba5a0819214609ce19edeefc312746 . Then I fixed compile failures as suggested by rust analyzer. Then I ran cargo test on the command line.

I expected to the project to compile without issue (or have some compile failure).

Instead, rustc overflowed its stack, with the following console output:

sean@pop-os:~/projects/splitbits$ cargo test
   Compiling serde v1.0.203
   Compiling proc-macro2 v1.0.86
   Compiling unicode-ident v1.0.12
   Compiling equivalent v1.0.1
   Compiling hashbrown v0.14.5
   Compiling winnow v0.6.13
   Compiling serde_json v1.0.120
   Compiling itoa v1.0.11
   Compiling ryu v1.0.18
   Compiling either v1.12.0
   Compiling trybuild v1.0.96
   Compiling glob v0.3.1
   Compiling termcolor v1.4.1
   Compiling ux v0.1.6
   Compiling itertools v0.13.0
   Compiling quote v1.0.36
   Compiling indexmap v2.2.6
   Compiling syn v2.0.67
   Compiling serde_spanned v0.6.6
   Compiling toml_datetime v0.6.6
   Compiling toml_edit v0.22.14
   Compiling serde_derive v1.0.203
   Compiling splitbits v0.1.0 (/home/sean/projects/splitbits)
   Compiling toml v0.8.14
error: rustc interrupted by SIGSEGV, printing backtrace

/home/sean/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-095ee26d08b6d198.so(+0x356f6e3)[0x7ba91ab6f6e3]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7ba917242520]
/home/sean/projects/splitbits/target/debug/deps/libsplitbits-f1a8d56ff231edb3.so(+0xe7837)[0x7ba905ae7837]
/home/sean/projects/splitbits/target/debug/deps/libsplitbits-f1a8d56ff231edb3.so(+0xeabe5)[0x7ba905aeabe5]

### cycle encountered after 4 frames with period 5
/home/sean/projects/splitbits/target/debug/deps/libsplitbits-f1a8d56ff231edb3.so(+0xeabf3)[0x7ba905aeabf3]
/home/sean/projects/splitbits/target/debug/deps/libsplitbits-f1a8d56ff231edb3.so(+0xeabf3)[0x7ba905aeabf3]
/home/sean/projects/splitbits/target/debug/deps/libsplitbits-f1a8d56ff231edb3.so(+0xeabf3)[0x7ba905aeabf3]
/home/sean/projects/splitbits/target/debug/deps/libsplitbits-f1a8d56ff231edb3.so(+0xeabf3)[0x7ba905aeabf3]
/home/sean/projects/splitbits/target/debug/deps/libsplitbits-f1a8d56ff231edb3.so(+0xeabf3)[0x7ba905aeabf3]
### recursed 50 times

/home/sean/projects/splitbits/target/debug/deps/libsplitbits-f1a8d56ff231edb3.so(+0xeabf3)[0x7ba905aeabf3]
/home/sean/projects/splitbits/target/debug/deps/libsplitbits-f1a8d56ff231edb3.so(+0xeabf3)[0x7ba905aeabf3]

note: rustc unexpectedly overflowed its stack! this is a bug
note: maximum backtrace depth reached, frames may have been lost
note: we would appreciate a report at https://github.com/rust-lang/rust
help: you can increase rustc's stack size by setting RUST_MIN_STACK=16777216
error: could not compile `splitbits` (test "test")

Caused by:
  process didn't exit successfully: `/home/sean/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name test --edition=2021 tests/test.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=134 --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 --test --check-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values())' -C metadata=da39772aaf680b49 -C extra-filename=-da39772aaf680b49 --out-dir /home/sean/projects/splitbits/target/debug/deps -C incremental=/home/sean/projects/splitbits/target/debug/incremental -L dependency=/home/sean/projects/splitbits/target/debug/deps --extern itertools=/home/sean/projects/splitbits/target/debug/deps/libitertools-0705115692c33851.rlib --extern proc_macro2=/home/sean/projects/splitbits/target/debug/deps/libproc_macro2-52583c9ef2175a87.rlib --extern quote=/home/sean/projects/splitbits/target/debug/deps/libquote-83347e5ed53269c1.rlib --extern splitbits=/home/sean/projects/splitbits/target/debug/deps/libsplitbits-f1a8d56ff231edb3.so --extern syn=/home/sean/projects/splitbits/target/debug/deps/libsyn-4109bebd718be2ee.rlib --extern trybuild=/home/sean/projects/splitbits/target/debug/deps/libtrybuild-a91c6202ed503e89.rlib --extern ux=/home/sean/projects/splitbits/target/debug/deps/libux-a5eaf436c8e4971d.rlib` (signal: 11, SIGSEGV: invalid memory reference)

sean@pop-os:~/projects/splitbits$ rustc --version --verbose
rustc 1.82.0-nightly (a32d4a0e8 2024-08-21)
binary: rustc
commit-hash: a32d4a0e822a29a6682e08b75a8df4c29c7fa9f1
commit-date: 2024-08-21
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 19.1.0

This issue persists after cargo clean is run.

When I first filed this issue, I thought it had to do with a rust analyzer upgrade that I had just performed, but it appears that was a red herring and this is entirely caused by my code change.

I'll try to narrow the repro code change down to be smaller within the context of my project, but I don't think I'll manage to create a separate stand-alone project that provides a minimal repro case. The project is a proc macro crate, which could somehow be relevant. There is otherwise no magic going on in the linked code change.

**Comment by saethlin** [comment]
I think this is infinite recursion inside your proc macro and not a compiler bug.

At a glance, it's often hard to tell the difference between a buggy proc macro crashing and the compiler being buggy, because proc macros are compiled to native code then loaded into the compiler process and executed without any sandboxing.

**Comment by saethlin** [comment]
```rust
    pub fn ux(len: u8) -> Type {
        match len {
            0 => panic!(),
            1..=128 => Type::ux(len.try_into().unwrap()),
            129..=u8::MAX => panic!("Integers larger than u128 are not supported."),
        }
    }
```
I think this is the bug.

**Comment by merehap** [comment]
Thanks [saethlin](https://github.com/saethlin) for the explanation, and sorry I didn't get a chance to investigate before you found the bug in my code.

This error message is still incorrect and wastes the time of rustc users and rustc developers (such as yourself):

> note: rustc unexpectedly overflowed its stack! this is a bug
> note: maximum backtrace depth reached, frames may have been lost
> note: we would appreciate a report at https://github.com/rust-lang/rust

Could you re-open this ticket so that it can be used to fix the error message? Or is even a minimal tweak to the error message to mention that it might be a proc macro bug instead of a compiler bug going to kick off a time-consuming project due to the lack of sandboxing you mentioned? If the error message could be tweaked to mention proc macros, it seems like that wouldn't add confusion for cases where it isn't a proc macro bug.

If you deem it acceptable to re-open the ticket, I will modify the title and summary accordingly.
