### ISSUE TITLE
Cow from HashMap

### ISSUE THREAD

**Issue by lasantosr** [rust-lang/rust#129580]
The std lib have different `From` implementations for `Cow`, but none of them is valid for `HashMap`.

**Comment by lasantosr** [comment]
There are `From` implementation from various vector-like structs to Cow [here](https://github.com/rust-lang/rust/blob/master/library/alloc/src/vec/cow.rs) but there's nothing similar for HashMap.

**Comment by lolbinarycat** [comment]
HashMap does not have a borrowed form.

we have `String` and `&str`, `Vec`, and `[T]`, but hashmaps always exist on the heap.

you can still put a hashmap in a cow, but this seems incredibly niche:

```rust
use std::borrow::Cow;
use std::collections::HashMap;
fn main() {
    let map_inner = HashMap::new();
    let the_map: Cow<'_, HashMap<u8, bool>> = Cow::Borrowed(&map_inner);
}
```

**Comment by lasantosr** [comment]
Ohh I see, thanks for the clarification.

We could still benefit from a blanket implementation for `T` and `&T` into `Cow::Owned` and `Cow::Borrowed` when specialization reaches stable, in order to keep current specialized implementations.
