### ISSUE TITLE
trying to cross-compile with the stage 0 compiler completes "successfully" but does nothing

### ISSUE THREAD

**Issue by lolbinarycat** [rust-lang/rust#129586]
`./x build --target x86_64-unknown-linux-none --stage 0 library/core/`

is this because bootstrap assumes every cross compilation will specify at least stage1?

**Comment by onur-ozkan** [comment]
Did you check `build/host/stage0-std` directory? The build output should be there inside another directory named `x86_64-unknown-linux-none`.

**Comment by lolbinarycat** [comment]
huh.

it should probably print the paths of the artifact they produce, since it's not at all obvious..

**Comment by onur-ozkan** [comment]
Closing the issue as it's not accurate.
