### ISSUE TITLE
handle std features with a new option in `config.toml`

### ISSUE THREAD

**Issue by onur-ozkan** [rust-lang/rust#129599]
Currently there are multiple ways to enable `std` features during bootstrap, which can be confusing to newcomers on this project.

To simplify this, add a new option under the `rustc` section in the `config.toml`, and handle it in the following function:

https://github.com/rust-lang/rust/blob/697d9530d78aeba31458cadfc338adb2aea90bee/src/bootstrap/src/lib.rs#L646

@rustbot label +E-easy +E-mentor +E-help-wanted +T-bootstrap

**Comment by shrirambalaji** [comment]
@onur-ozkan I'd like to pick this up, haven't contributed to rustc before so might need some mentoring

**Comment by onur-ozkan** [comment]
> @onur-ozkan I'd like to pick this up

You can [claim the issue](https://rustc-dev-guide.rust-lang.org/rustbot.html?highlight=claim#issue-claiming) by using rustbot.

> haven't contributed to rustc before so might need some mentoring

Feel free to ask [me](https://rust-lang.zulipchat.com/#user/461362) any questions on Zulip, or ping me here under the issue or an open PR.

**Comment by onur-ozkan** [comment]
Done by #131315.
