### ISSUE TITLE
TcpListener::bind alwary success though specific port already occupied

### ISSUE THREAD

**Issue by swq123459** [rust-lang/rust#129602]

**Comment by the8472** [comment]
Please provide steps to reproduce or an overview over the bound sockets after this happens. There are enough complications about multiple network interfaces, IP addresses etc. that it's not obvious what could be the issue here.

**Comment by swq123459** [comment]
The following example can reproduce this issue, this program can still running though i see this addr was already occupied
![image](https://github.com/user-attachments/assets/8bfdfdfe-e389-4ab5-9f59-9d36cecf4f72)

**Comment by swq123459** [comment]
When i impl this example by golang (or another programming language)， it can not work in port-occupied situation
```
	listener, err := net.Listen("tcp", "0.0.0.0:35628")
	if err != nil {
		fmt.Println("Error creating listener:", err)
		os.Exit(1)
	}
	defer listener.Close()
```

**Comment by ctz** [comment]
For me, your example fails as expected with:

```
Error: Os { code: 98, kind: AddrInUse, message: "Address already in use" }
```

**Comment by swq123459** [comment]
> For me, your example fails as expected with:
> 
> ```
> Error: Os { code: 98, kind: AddrInUse, message: "Address already in use" }
> ```
> 
> strace (or equivalent on whatever platform we're talking about) output would be informative.

When i run this example to `occupy` this addr, another example can no use this address and raise the above error ( which is expected), but when this addr was occupied by another (no example code) process (like ssh 127.0.0.1:22 or even port `127.0.0.1:1` ), this addr can be use by this example (wire)
