### ISSUE TITLE
`make clean` should delete the tmp directory

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#12966]
I just had a bug where `make check` failed at run-pass/linkage2.rs. Deleting the tmp directory solved the problem, but `make clean` did not. I assume `make clean` should delete that sort of thing.

**Comment by FlaPer87** [comment]
Triage bump, bug is still valid.

**Comment by tbelaire** [comment]
I don't understand why it didn't.

mk/clean.mk
```
 38 clean: clean-misc $(CLEAN_STAGE_RULES)
 39 
 40 clean-misc:
 41     @$(call E, cleaning)
 ...
 45     $(Q)rm -Rf tmp/*
```

So `make clean` does `rm -Rf tmp/*`. Perhaps it needs to delete the directory too?

Can I get more detailed steps on how to reproduce this bug, so I can tell if deleting `tmp/` instead of `tmp/*` fixes it?

**Comment by steveklabnik** [comment]
I agree with @tbelaire , it would seem like the rules are very straightforward here, and if I run `make clean`, I do get a `rm -Rf tmp/*`. @nrc or @FlaPer87 , can you give any way to reproduce this?

**Comment by brson** [comment]
Ancient bug. Closing.
