### ISSUE TITLE
rustdoc: copy code button obscures scraped example expand button

### ISSUE THREAD

**Issue by willcrichton** [rust-lang/rust#129763]
Rustdoc's copy code button introduced in 9946a68 conflicts with the UI for interacting with scraped code examples. I noticed this in the wild in Bevy's documentation: https://docs.rs/bevy/0.14.1/bevy/app/struct.App.html#scraped-examples-1

In the upper right corner is a button for expanding a snipper:

<img width="963" alt="Screenshot 2024-08-29 at 2 46 10 PM" src="https://github.com/user-attachments/assets/1f9b0879-393c-4daf-8029-7e495407978c">

But hovering over the snippet shows the copy code button, obscuring the expand button:

<img width="974" alt="Screenshot 2024-08-29 at 2 46 24 PM" src="https://github.com/user-attachments/assets/dee92cc3-78a9-46c2-a9ce-9fef050dd1ba">

cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Arf indeed. I think code unification will be needed for this feature with the other code blocks to prevent such regressions in the future. Gonna send a fix.

**Comment by GuillaumeGomez** [comment]
I decided to integrate the buttons with the existing code examples. For now it looks like this:

![image](https://github.com/user-attachments/assets/c8475945-dcc3-4c25-8d7d-1659f85301c8)

**Comment by willcrichton** [comment]
That looks great! Do the buttons have the same behavior where they only appear when you hover over the snippet?

**Comment by GuillaumeGomez** [comment]
Yes! I'm also planning to only generate them if they don't already exist on hover like the copy button (it is only created after you first hovered the code example), it'll reduce the HTML size quite a lot. I also simplified the HTML a bit (again, smaller). I almost didn't change anything in the scraped example JS code, which is quite nice. I expected more changes to be needed. Well done!
