### ISSUE TITLE
Doc for stringify!

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#12977]
Where's the documentation for `stringify!`? It doesn't seem to be in the [doc for `std::macros`](http://static.rust-lang.org/doc/master/std/macros/index.html) -- probably because it's not in that module (not sure where it is though)

Could some documentation on this be added somewhere?

**Comment by steveklabnik** [comment]
There are now docs, though with rustdoc bugs, sometimes macro dosc disappear.
