### ISSUE TITLE
`./x.py test compiler/rustc_abi` no longer works

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust#129727]
This regressed with https://github.com/rust-lang/rust/pull/128722
Running `./x.py test compiler/rustc_abi` (as well as for most other compiler crates) no longer works, resulting in an error similar to the following:
```
error: none of the selected packages contains these features: jemalloc, llvm, max_level_info, rustc_use_parallel_compiler
```

**Comment by Veykril** [comment]
Fixing this will be troublesome https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/.60parallel_compiler.60.20or.20.60rustc_use_parallel_compiler.60

**Comment by Veykril** [comment]
Whoops, I did not mean to close this with that PR (and I can't reopen it for some reason) this is still an issue

**Comment by GrigorenkoPV** [comment]
#131093 may be a duplicate of this

**Comment by Veykril** [comment]
https://github.com/rust-lang/rust/pull/132282 removed all of the problematic cfgs/features so this now works again 🎉
