### ISSUE TITLE
`#[unstable]` accepts an already-stable language feature

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#129814]
This should probably not be accepted:
```rust
#![feature(staged_api)]
#![stable(feature = "rust_test", since = "1.0.0")]

#[unstable(feature = "arbitrary_enum_discriminant", issue = "42")]
#[rustc_const_unstable(feature = "arbitrary_enum_discriminant", issue = "42")]
const fn my_fun() {}

fn main() {}
```
`arbitrary_enum_discriminant` is already stable, so having an unstable function under this feature makes no sense.

**Comment by CastilloDel** [comment]
Should we also reject features that don't exist? Right now, this test would fail (because it would compile without problems)
```rust
//@ check-fail

#![feature(staged_api)]
#![stable(feature = "rust_test", since = "1.0.0")]

#[unstable(feature = "name_of_a_feature_that_does_not_exist", issue = "42")]
const fn my_fun() {}

fn main() {}
```

**Comment by RalfJung** [comment]
"unstable" attributes is how library features come into existence. So yes we should accept features that do not yet exist.
