### ISSUE TITLE
Update release notes for 1.82.0 to include the tier 2 status for the `wasm32-wasip2` target

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#129997]
The Rust 1.81.0 release notes originally had a note that the `wasm32-wasip2` target was moved to tier 2. This was because https://github.com/rust-lang/rust/pull/126967 made it into Rust 1.81 and claims that `wasm32-wasip2` is tier 2. Alas there was a bug in that PR which ended up being fixed in https://github.com/rust-lang/rust/pull/127867 which did not make Rust 1.81. This means that Rust 1.81 did not actually include tier 2 status for `wasm32-wasip2` in the sense that you could `rustup target add` the target.

The blog post release notes have [been updated](https://github.com/rust-lang/blog.rust-lang.org/pull/1397) to no longer mention this feature of 1.81 and the release notes on the master branch additionally [have been updated as well](https://github.com/rust-lang/rust/pull/129995).

In talking with @pietroalbini he recommended I open an issue to track the release notes for 1.82 and I'm told there are mythical and mysterious labels he'll apply to track everything accordingly. I'll also be here to help answer questions if any arise too!

**Comment by stefnotch** [comment]
Rust 1.82.0 got released (yay) Can this post be published now? I'd love to see wasm32-wasip2 get a bit more attention.

**Comment by ChrisDenton** [comment]
Probably it'd be better to wait at least a day or two so it's not competing for attention with the release announcement.
