### ISSUE TITLE
`TcpStream::set_nonblocking` docs mention non-existent methods

### ISSUE THREAD

**Issue by Imberflur** [rust-lang/rust#129903]
### Location

https://github.com/rust-lang/rust/blob/a4601859ae3875732797873612d424976d9e3dd0/library/std/src/net/tcp.rs#L564

### Summary

The docs mention:
> This will result in `read`, `write`, `recv` and `send` operations becoming nonblocking

However, I can't find any `recv` or `send` methods on `TcpStream` (nor in the traits it implements). Do these operations refer to something else?

**Comment by bjorn3** [comment]
It is likely referring to the underlying syscalls on UNIX systems.

**Comment by the8472** [comment]
[BSD socket APIs](https://en.wikipedia.org/wiki/Berkeley_sockets) are defined in POSIX, [also referenced in various networking RFCs](https://www.rfc-editor.org/rfc/rfc6317.html#section-4). Windows also adopted it. So it's pretty much the universal API describing how to interact with various kinds of network sockets.

But at least `read` does appear in the documentation.
https://doc.rust-lang.org/nightly/std/net/struct.TcpStream.html#method.read-1

**Comment by Imberflur** [comment]
> It is likely referring to the underlying syscalls on UNIX systems.

Oh I see. Thank you for helping with my confusion. I'm happy to close this then (but also fine with keeping it open if it seems worth clarifying this in docs).

**Comment by rufevean** [comment]
do we just have to add comments to clarfiy better or is there any docs file that we have to change too?
