### ISSUE TITLE
driftsort implementation uses an out-of-range literal on 16-bit targets

### ISSUE THREAD

**Issue by saethlin** [rust-lang/rust#129910]
Run
```
cargo +nightly miri setup --target avr-unknown-gnu-atmega328
```
Or
```
x check library/core --target avr-unknown-gnu-atmega328
```
And you'll get this diagnostic (cargo miri setup makes it a warning, lol):
```
error: literal out of range for `usize`
  --> core/src/slice/sort/stable/mod.rs:62:41
   |
62 |     const MAX_FULL_ALLOC_BYTES: usize = 8_000_000; // 8MB
   |                                         ^^^^^^^^^
   |
   = note: the literal `8_000_000` does not fit into the type `usize` whose range is `0..=65535`
   = note: `#[deny(overflowing_literals)]` on by default
```

I don't know what effect this has at runtime but it can't be good.

**Comment by workingjubilee** [comment]
It's worse than one might think, because many AVR targets have only 2KiB of SRAM, which means that this line is literally impossible:
```rust
    // For small inputs 4KiB of stack storage suffices, which allows us to avoid
    // calling the (de-)allocator. Benchmarks showed this was quite beneficial.
    let mut stack_buf = AlignedStorage::<T, 4096>::new();
```

**Comment by workingjubilee** [comment]
these targets should probably use some of the code in https://github.com/rust-lang/rust/pull/129587 with perhaps a few more tweaks.

**Comment by Voultapher** [comment]
Good to know, 16-bit wasn't something we had in mind, in terms of less standard targets, we did test big endian with miri.

I agree with @workingjubilee the code in https://github.com/rust-lang/rust/pull/129587 would be a better fit for such targets. What kind of tweaks did you have in mind?

**Comment by Voultapher** [comment]
There are other places in driftsort and ipnsort that use stack arrays, e.g:

https://github.com/rust-lang/rust/blob/d6c8169c186ab16a3404cd0d0866674018e8a19e/library/core/src/slice/sort/shared/smallsort.rs#L327

They are all size bound to <= 4KiB through various means, but still a poor fit for tiny chips.

**Comment by orlp** [comment]
> these targets should probably use some of the code in #129587 with perhaps a few more tweaks.

I think that's necessary, I don't believe driftsort could ever meaningfully run on machines this small.

**Comment by workingjubilee** [comment]
>  What kind of tweaks did you have in mind?

You already figured it out: dropping all the stack arrays to the absolute minimum.

Note that you are not obligated to fix these targets, as usual.

**Comment by Voultapher** [comment]
I think it should be a single additional `cfg_if` in the impl, so I don't mind doing it.

**Comment by RalfJung** [comment]
> (cargo miri setup makes it a warning, lol)

Yeah, we'd get CI failures way too often if we errored on warnings for tier 3 targets.

**Comment by RalfJung** [comment]
Related: https://github.com/rust-lang/rust/issues/130818

**Comment by saethlin** [comment]
> Yeah, we'd get CI failures way too often if we errored on warnings for tier 3 targets.

Who is using Tier 3 targets in CI?

**Comment by RalfJung** [comment]
Miri is, by running a test with `avr.json`.

We should probably change that.

**Comment by Voultapher** [comment]
Thinking a bit more about it, is there any scenario where you'd compile Rust for 16-bit targets and *don't* want to use `optimize_for_size`? Independent of sort. I'd think that such targets are always binary-size limited and welcome any reduction of it.
