### ISSUE TITLE
where is the 1.81.0 release?

### ISSUE THREAD

**Issue by ognevny** [rust-lang/rust#129990]
maybe the worst way to ask this, but on github only 1.80.1 appeared today and 1.81.0 isn't avialable in https://static.rust-lang.org. why?

**Comment by Urgau** [comment]
It has simply not yet been released.

Be patient, the day has just begun in some parts of the world.

**Comment by Urgau** [comment]
As for 1.80.1 appearing so late in GitHub release page, is just because we forgot to put up the release notes in master, https://github.com/rust-lang/rust/pull/129930.
