### ISSUE TITLE
Tracking Issue for const_str_as_mut

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#130086]
Feature gate: `#![feature(const_str_as_mut)]`

This is a tracking issue for const mutable `str` accessors:
```rust
impl str {
    pub const unsafe fn as_bytes_mut(&mut self) -> &mut [u8];
    pub const fn as_mut_ptr(&mut self) -> *mut u8;
}
```

### Steps / History

- [x] Implementation: https://github.com/rust-lang/rust/pull/130046
- [ ] Final comment period (FCP)[^1]
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

[^1]: https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html

**Comment by dtolnay** [comment]
@rfcbot fcp merge

`const` for these already-stable functions:

- https://doc.rust-lang.org/nightly/core/primitive.str.html#method.as_bytes_mut
- https://doc.rust-lang.org/nightly/core/primitive.str.html#method.as_mut_ptr
