### ISSUE TITLE
`use<>` bounds ("precise capture") require all type parameters to be listed

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#130031]
The current implementation of precise capture requires that `use<>` bounds include all type parameters in scope. This is a temporary limitation that should be lifted. Example:

```rust
#![allow(warnings)]

fn main() {
    let mut data = vec![1, 2, 3];
    let mut i = indices(&data);
    data.push(4);
    i.next();
}

fn indices<T>(
    slice: &[T],
) -> impl Iterator<Item = usize> + use<> {
    0 .. slice.len()
}
```

This code should compile, but it current gives an error ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b5a00260b648f8c7ce0949a3bab6af99)):

```
error: `impl Trait` must mention all type parameters in scope in `use<...>`
  --> src/main.rs:12:6
   |
10 | fn indices<T>(
   |            - type parameter is implicitly captured by this `impl Trait`
11 |     slice: &[T],
12 | ) -> impl Iterator<Item = usize> + use<> {
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: currently, all type parameters are required to be mentioned in the precise captures list
```

**Comment by compiler-errors** [comment]
There are certainly some cases where it will be impossible to "fix" this, though. I expect that all non-method type and const parameters will always need to be captured for RPITITs to be sound. We should probably explore which parameters are obligatory to capture in what scenarios.

**Comment by nikomatsakis** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/130043

**Comment by theemathas** [comment]
I think that this example code is not very good, since changing the `use<>` to `use<T>` causes the code to compile.

**Comment by compiler-errors** [comment]
@theemathas: The whole point of the example is to return an opaque that does not capture `T`. This has observable side-effects.
