### ISSUE TITLE
Why rustc supports more targets than the underlaying LLVM?

### ISSUE THREAD

**Issue by dilyanpalauzov** [rust-lang/rust#130083]
I have compiled LLVM 18.1.8 with 

> cmake -GNinja -DCLANG_INCLUDE_TESTS=OFF -DLLVM_ENABLE_EH=ON -DLLVM_ENABLE_RTTI=ON -DLLVM_ENABLE_Z3_SOLVER=ON -DLLVM_ENABLE_PROJECTS="bolt;clang;clang-tools-extra;lld;lldb;mlir;polly;compiler-rt" -DLLVM_TARGETS_TO_BUILD="X86;WebAssembly" -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DLLVM_BINUTILS_INCDIR=/usr/local/include -DLLVM_INCLUDE_TESTS=OFF ../llvm-project-18.1.8.src/llvm

and it supports these targets:
```
# llc --version  
LLVM (http://llvm.org/):
  LLVM version 18.1.8
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: nocona

  Registered Targets:
    wasm32 - WebAssembly 32-bit
    wasm64 - WebAssembly 64-bit
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
```
As next I have compiled rust 1.81 with

> ../configure  --enable-optimize-llvm --enable-extended --llvm-root=/usr/local --enable-profiler --enable-llvm-link-shared --enable-sanitizers --enable-local-rust --disable-docs --target=x86_64-unknown-linux-gnu

It produces the attached [config.toml](https://github.com/user-attachments/files/16919318/config.toml.txt).

As the resulting rustc uses LLVM from the system, and thus supports wasm and x86 only, I expect that rustc will also support only these targets. But
```
$ rustc --print target-list
aarch64-apple-darwin
aarch64-apple-ios
aarch64-apple-ios-macabi
aarch64-apple-ios-sim
…
arm-linux-androideabi
arm-unknown-linux-gnueabi
…
arm-unknown-linux-gnueabihf
arm-unknown-linux-musleabi
…
armv7-linux-androideabi
armv7-sony-vita-newlibeabihf
…
mips-unknown-linux-gnu
mips-unknown-linux-musl
…
s390x-unknown-linux-gnu
s390x-unknown-linux-musl
sparc-unknown-linux-gnu
sparc-unknown-none-elf
…
wasm32-unknown-emscripten
wasm32-unknown-unknown
wasm32-wasi
wasm32-wasip1
wasm32-wasip1-threads
wasm32-wasip2
wasm64-unknown-unknown
x86_64-apple-darwin
x86_64-apple-ios
x86_64-apple-ios-macabi
x86_64-apple-tvos
x86_64-apple-watchos-sim
x86_64-fortanix-unknown-sgx
x86_64-fuchsia
x86_64-linux-android
x86_64-pc-nto-qnx710
x86_64-pc-solaris
x86_64-pc-windows-gnu
x86_64-pc-windows-gnullvm
x86_64-pc-windows-msvc
x86_64-unikraft-linux-musl
x86_64-unknown-dragonfly
x86_64-unknown-freebsd
x86_64-unknown-fuchsia
x86_64-unknown-haiku
x86_64-unknown-hermit
x86_64-unknown-illumos
x86_64-unknown-l4re-uclibc
x86_64-unknown-linux-gnu
x86_64-unknown-linux-gnux32
x86_64-unknown-linux-musl
x86_64-unknown-linux-none
x86_64-unknown-linux-ohos
x86_64-unknown-netbsd
x86_64-unknown-none
x86_64-unknown-openbsd
x86_64-unknown-redox
x86_64-unknown-uefi
x86_64-uwp-windows-gnu
x86_64-uwp-windows-msvc
x86_64-win7-windows-msvc
x86_64-wrs-vxworks
x86_64h-apple-darwin
xtensa-esp32-espidf
…
```
In total 247 targets.  Why does rustc pretend to support more targets, than the underlaying LLVM?

**Comment by saethlin** [comment]
rustc does not necessarily use LLVM. It can dynamically load other backends with `-Zcodegen-backend` and just run the frontend with `--emit=metadata`, which is how `cargo check` works.

**Comment by ChrisDenton** [comment]
It should also be noted that rust target names are not necessarily the same as llvm target names. And many targets may simply be variations on another target (e.g. different CPU features or environment or OS).

**Comment by dilyanpalauzov** [comment]
Thanks for the clarifications!

How should I compile rustc, so that `rustc --print target-list` does not emit aarch64-apple-ios-sim, arm-linux-androideabi, arm-unknown-linux-musleabi, armv7-linux-androideabi, mips-unknown-linux-musl, s390x-unknown-linux-gnu…?

**Comment by workingjubilee** [comment]
@dilyanpalauzov Why do you wish to remove this support? Having to compile LLVM *at all* is the vast majority of the space expense of LLVM, additional targets are only a tiny amount at most.

**Comment by workingjubilee** [comment]
However, I believe the answer is "we don't support this use-case".

**Comment by dilyanpalauzov** [comment]
I want to exclude the MIPS, ARM, … targets from Rustc, so that compiling rustc itself is faster and does not include features I will never ever use.  As mentioned above, the MIPS and ARM targets are not provided by the LLVM on the system.

**Comment by workingjubilee** [comment]
> I want to exclude the MIPS, ARM, … targets from Rustc, so that compiling rustc itself is faster and does not include features I will never ever use. As mentioned above, the MIPS and ARM targets are not provided by the LLVM on the system.

If this is for your personal system, and you feel comfortable modifying how software is compiled in fairly arbitrary fashions that may be outside the spec of how that software is intended to be used, then I do not see why you cannot simply modify the list by patching rustc yourself?

**Comment by jieyouxu** [comment]
Yeah, I don't think this is a supported use case for `--print target-list`, but as mentioned you can patch rustc to avoid emitting those targets if you want to.

**Comment by saethlin** [comment]
> I want to exclude the MIPS, ARM, … targets from Rustc, so that compiling rustc itself is faster

Nearly all of the compiler is target-independent and doesn't care about architecture. It's not like there are modules that you could skip compiling if you don't want ARM support. We don't support the option you want because it would be pointless.

**Comment by dilyanpalauzov** [comment]
Ok, closing.
