### ISSUE TITLE
`#[deprecated]` on use statements is silently ignored

### ISSUE THREAD

**Issue by cyrgani** [rust-lang/rust#130029]
The following code gives no deprecation warning on `use other_crate::Thing;` but also no `useless_deprecated` error:
```rust
mod other_crate {
    pub mod module {
        pub struct Thing;
    }

    #[deprecated(note = "use the explicit path")]
    pub use module::*;
}

use other_crate::Thing;
```
I think it would make sense to allow deprecation of use statements, but if there's a reason not to allow this, then `useless_deprecated` should be emitted.

**Comment by kadiwa4** [comment]
This is tracked in #30827 and #84584 already.

**Comment by cyrgani** [comment]
Closing this as a duplicate, then.
