### ISSUE TITLE
x.py refers to skip-build, which is missing from config.example.toml

### ISSUE THREAD

**Issue by dilyanpalauzov** [rust-lang/rust#130039]
rustc-1.81.0-src/x.py --help prints
```
     --llvm-skip-rebuild <VALUE>
          whether rebuilding llvm should be skipped, overriding `skip-rebuld` in config.toml
          
          [possible values: true, false]
```
This suggests, that config.example.toml has a skip-rebuild parameter.  But it does not.

https://github.com/rust-lang/rust/issues/71119 suggests to skip rebuilding LLVM by  calling `./configure --llvm-root=<path>`.

* Either reword the above output, or add `skip-rebuild` in config,example.toml.

**Comment by dilyanpalauzov** [comment]
It really says `skip-rebuld` and not `skip-rebuild` and both are missing from config.example.toml.

**Comment by onur-ozkan** [comment]
This `--llvm-skip-rebuild` flag is no longer used anywhere, and we don't support that `skip-rebuild` option in `config.toml`.

Mentoring instructions: remove the `llvm_skip_rebuild` from bootstrap, then run `x.py test tidy --bless` to update the [shell completion files](https://github.com/rust-lang/rust/tree/370168787bd6f2ed26788a51af97166d868e0609/src/etc/completions).
