### ISSUE TITLE
[discussion] `ErrorKind::CrossesDevices` from `io_error_more`

### ISSUE THREAD

**Issue by GrigorenkoPV** [rust-lang/rust#130191]
@rustbot label C-discussion

Main tracking issue: #86442

## Background

The [`io_error_more` feature](https://github.com/rust-lang/rust/issues/86442) introduced 21 new variants into [`ErrorKind`](https://doc.rust-lang.org/nightly/std/io/enum.ErrorKind.html). They were [FCP'd back in December 2022](https://github.com/rust-lang/rust/issues/86442#issuecomment-1368082102), but there appeared to be quite a lot of disagreement about 4 of the added variants, so the stabilization (#106375) got stalled for over twenty months. Thankfully, the 17 uncontroversial variants got stabilized in #128316, so now we just need to iron out a satisfactory design for the remaining 4 variants, and then they can be stabilized too.

In order to not block any of the remaining variants on each other and to not intertwine the discussions, I've created 4 separate issues, which summarize the concerns & suggestions voiced up until this point and can serve as a place for further discussion.

-  `FilesystemLoop`:  #130188
-  `FilesystemQuotaExceeded`: #130190
-  `CrossesDevices`: you are here
-  `InvalidFilename`: #130192

# `CrossesDevices`

Currently corresponds to `EXDEV` on Unix and `ERROR_NOT_SAME_DEVICE` on Windows. (https://github.com/rust-lang/rust/issues/86442#issuecomment-1235763183)

Current docs description:

> Cross-device or cross-filesystem (hard) link or rename.

## `NotSameDevice`

> I think `NotSameDevice` is a better name than `CrossesDevices`. For me, it expresses its meaning more clearly. FWIW, the Linux man page also uses the word "same" to describe `EXDEV`: `oldpath and newpath are not on the same mounted filesystem`.
>
> Also, I find `NotSameDevice` to be stylistically more consistent with the other existing and proposed error identifiers.

_Originally posted by kalcutter in https://github.com/rust-lang/rust/issues/86442#issuecomment-1367069051_
            
> Would you also consider `NotSameDevice` instead of `CrossesDevices`?

_Originally posted by kalcutter in https://github.com/rust-lang/rust/issues/106375#issuecomment-1371554608_

> I personally don't think we should rename `CrossesDevices`.

_Originally posted by Josh Triplett in https://github.com/rust-lang/rust/issues/106375#issuecomment-1371870620_

**Comment by dtolnay** [comment]
@rfcbot fcp merge

I propose stabilizing `CrossesDevices` if there are 2 other team members on board. As of https://github.com/rust-lang/rust/pull/106375#issuecomment-1371870620, Josh prefers this name.

Alternatively, if 2 other team members prefer a rename to `NotSameDevice`, I propose stabilizing `NotSameDevice`.

**Comment by joshtriplett** [comment]
Checked my box for `CrossesDevices`.

**Comment by joshtriplett** [comment]
Ping @Amanieu @BurntSushi @m-ou-se

**Comment by GrigorenkoPV** [comment]
Stabilized in #130209, closing.
