### ISSUE TITLE
Document that leading blocks are never expressions

### ISSUE THREAD

**Issue by comex** [rust-lang/rust#13012]
## Updated description

The fact that leading blocks are never expressions needs to be documented in the language reference both in the grammar section and likely elsewhere to make it known

## Original description

> Can't use operators on unsafe { }

```
/tmp/test.rs:2:18: 2:19 error: unexpected token: `+`
/tmp/test.rs:2     unsafe { 1 } + 1;
                                ^
```

You need parentheses:

    (unsafe { 1 }) + 1;

but it doesn't seem like that should be necessary.

**Comment by steveklabnik** [comment]
Traige: still not clear exactly with what to do for an "I expected this to work but it doesn't," so I'm giving this a close. It's not scalable to put every kind of quesiton like this in the docs, and I don't see people asking about this very often. If it becomes a problem, we can try to figure something out eventually.
