### ISSUE TITLE
Outdated master branch detection doesn't work with worktrees

### ISSUE THREAD

**Issue by Noratrieb** [rust-lang/rust#130111]
When running any bootstrap command, it complains that it can't figure out whether my master branch is outdated.
Of course it does, as it just YOLOs into `.git`, which is just a file and not a directory for worktrees:
https://github.com/rust-lang/rust/blob/adf8d168af9334a8bf940824fcf4207d01e05ae5/src/tools/build_helper/src/git.rs#L177

it should probably not do that (i don't have a suggestion on what to do instead)

regressed by #129584 @lolbinarycat @albertlarsan68

**Comment by lolbinarycat** [comment]
> it should probably not do that (i don't have a suggestion on what to do instead)

i would say adding a bit of error handling that checks if it's in a worktree doesn't sound too hard.

there's two options from there:
1. never emit the warning in a worktree.  this is basically trivial, but if someone does 100% of their work in a worktree, they may end up with an outdated upstream and not know it
2. fall b
