### ISSUE TITLE
rustc overwrites input file when it has no extension

### ISSUE THREAD

**Issue by comex** [rust-lang/rust#13019]
```
% echo 'fn main() {}' > test
% rustc test
% ./test # input has been replaced with the output binary
```

Tested on OS X, af9368452d8578af219713b34f7e3be4bd085186.  Not that it makes sense to write Rust files with no extension, but if you do, rustc should not overwrite the input file by default.

**Comment by steveklabnik** [comment]
Triage: this still happens today.

**Comment by frewsxcv** [comment]
This still happens

```
coreyf@frewbook-pro /tmp> cat hi
fn main() {}
coreyf@frewbook-pro /tmp> file hi
hi: ASCII text
coreyf@frewbook-pro /tmp> rustc hi
coreyf@frewbook-pro /tmp> file hi
hi: Mach-O 64-bit executable x86_64
```

**Comment by jonas-schievink** [comment]
We just had 2 new Rust learners hit this...

**Comment by cyplo** [comment]
It's still an issue with rustc 1.18.0-nightly (28a742997 2017-04-13)

**Comment by varkor** [comment]
@estebank: I have a fix for this, based on your patch — are you happy for me to submit it, or would you like to finish it off?

**Comment by estebank** [comment]
@varkor feel free to go ahead and submit the PR. Thank you for picking this up!
