### ISSUE TITLE
The time of creating Vec with `vec!` macro is not linear with the vec size

### ISSUE THREAD

**Issue by StevenJiang1110** [rust-lang/rust#130181]
During the development of the [Asterinas kernel project](https://github.com/asterinas/asterinas), we observed that the time taken to create a `Vec` is not linear with respect to its size, particularly as the size approaches approximately 45,000. Since Asterinas employs its own heap allocator, which is based on a buddy allocator, I am uncertain whether the issue originates from our custom heap allocator or the Vec implementation itself.

To investigate further, I conducted a test using Rust's standard heap allocator. The results appear to be similar.

So I do another test on the heap allocator of Rust std. And the result seems similar. 

# Test Details

Operating System: ubuntu 22.04
CPU: Intel(R) Xeon(R) Gold 6342 CPU @ 2.80GHz
rust version: rustc 1.81.0-nightly (d8a38b000 2024-06-19)

Creating a `Vec` using `vec!`, with sizes ranging from 256 to 65,536, in step size 256:

![vec_macro](https://github.com/user-attachments/assets/a505a3bd-7c0f-4518-a205-dad37ab87b33)

The graph shows a marked increase in time as the Vec size moves from around 45,000 to approximately 55,000. I wonder if this is a reasonable outcome.

<details><summary>Below are the code to replay the result</summary>
<p>

The following code can be run with
```sh
cargo add plotlib
cargo run --release
```

```rust
use std::time::Instant;

use plotlib::{
    page::Page,
    repr::Plot,
    style::{PointMarker, PointStyle},
    view::ContinuousView,
};

const START: usize = 256;
const END: usize = 65536;
const STEP_SIZE: usize = 256;

fn main() {
    let res: Vec<_> = (START..=END)
        .step_by(STEP_SIZE)
        .map(|i| {
            println!("calling `vec![0u8; {}]`", i);
            let nanoseconds = test_operation(|| {
                let mut v = vec![123u8; i];
                black_box(&mut v);
                drop(v)
            });
            (i, nanoseconds)
        })
        .collect();
    draw_slot(res);
}

fn test_operation(op: impl Fn()) -> u128 {
    const REPETITION: usize = 3;
    const ITERATION: u32 = 1_000_000;

    let mut res = Vec::with_capacity(REPETITION);
    for _ in 0..REPETITION {
        let star_time = Instant::now();
        for _ in 0..ITERATION {
            core::hint::black_box(op());
        }
        let consumed_time = star_time.elapsed();
        let avg_time = (consumed_time).checked_div(ITERATION).unwrap();
        res.push(avg_time);
    }

    println!("time consuming: `{:?}`", res);
    println!();
    res[1].as_nanos()
}

/// Avoids compiler optimizing creating vec away
fn black_box(v: &mut [u8]) {
    core::hint::black_box({
        v[1] = v[100];
        assert_eq!(v[2], v[99]);
    });
}

fn draw_slot(res: Vec<(usize, u128)>) {
    let y_min = res.iter().map(|(_, y0)| *y0).min().unwrap();
    let y_max = res.iter().map(|(_, y0)| *y0).max().unwrap();

    let res = res
        .iter()
        .map(|(x0, y0)| (*x0 as f64, *y0 as f64))
        .collect();
    let s1: Plot = Plot::new(res).point_style(
        PointStyle::new()
            .marker(PointMarker::Circle)
            .colour("#FF0000")
            .size(2.0), // red
    );

    let v = ContinuousView::new()
        .add(s1)
        .x_range((START - STEP_SIZE) as f64, (END + STEP_SIZE) as f64)
        .y_range((y_min - 1) as f64, (y_max + 1) as f64)
        .x_label("the size of vector")
        .y_label("the vec creating time(ns)");

    Page::single(&v).save("scatter.svg").unwrap()
}


```

</p>
</details>

**Comment by the8472** [comment]
That CPU has 48KiB of L1d cache. I assume L2 can't sustain the same write bandwidth.

**Comment by workingjubilee** [comment]
@StevenJiang1110 Might I recommend a copy of Computer Architecture: A Quantitative Approach? The 5th edition, Section B, answers most of your questions about the memory hierarchy. [Your previous issue](https://github.com/rust-lang/rust/issues/125352) featured you discovering [memory pages](https://en.wikipedia.org/wiki/Page_(computer_memory)) exist, and this one appears to be you discovering [L1 caches](https://en.wikipedia.org/wiki/CPU_cache) exist. While we are happy to answer a question here and there, it seems you probably could benefit from examining such a comprehensive reference.

**Comment by StevenJiang1110** [comment]
> That CPU has 48KiB of L1d cache. I assume L2 can't sustain the same write bandwidth, though it might also be other things like TLB misses or something... you should run this under `perf stat` or intel vtune and figure out which performance counter gets worse

Thanks for your advice! I exmine the perf result It seems the L1 cache miss rate grows very fast when the vec size grows around 48K. This should account for my issue.
