### ISSUE TITLE
`#[expect(unused_must_use)]` does not work when applied directly to statement

### ISSUE THREAD

**Issue by AnthonyMikh** [rust-lang/rust#130142]
I tried this code:

```rust
#[must_use]
pub fn important() -> i32 {
    42
}

pub fn foo() {
    #[expect(unused_must_use)]
    important();
}
```

I expected `#[expect]` to catch `unused_must_use` lint and suppress it, as it should. Instead, compiler issues a diagnostic _both_ about unused `#[must_use]` value _and_ unfulfilled lint expectation:

```
warning: unused return value of `important` that must be used
 --> src/lib.rs:8:5
  |
8 |     important();
  |     ^^^^^^^^^^^
  |
  = note: `#[warn(unused_must_use)]` on by default
help: use `let _ = ...` to ignore the resulting value
  |
8 |     let _ = important();
  |     +++++++

warning: this lint expectation is unfulfilled
 --> src/lib.rs:7:14
  |
7 |     #[expect(unused_must_use)]
  |              ^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unfulfilled_lint_expectations)]` on by default
```

It does work as expected though if `#[expect]` is applied to function.

### Meta

I used the latest stable (Rust 1.81), but it is reproducible both on latest beta (2024-09-04 c7c49f44a7bb561dd931) and latest nightly (2024-09-05 9c01301c52df5d2d7b6f).

@rustbot labels: +F-lint_reasons, +A-diagnostics

**Comment by cjgillot** [comment]
Your investigation is accurate, and the fix is simple: visit the statement node when building lint levels. 

Do you mind making such a pr ? 

I don't think we need any special adjustment for `expect` cases, duplicated attributes are already taken into account, but a test won't hurt.

**Comment by gurry** [comment]
> Your investigation is accurate, and the fix is simple: visit the statement node when building lint levels. 
> 
> Do you mind making such a pr ? 
> 
> I don't think we need any special adjustment for `expect` cases, duplicated attributes are already taken into account, but a test won't hurt. 

Thanks @cjgillot . 

Yes, I'll put together a PR. My only concern is if all we do is add the level at `Stmt`, although it will work perfectly for `allow`, `deny` etc., in the case of `expect` we will end up with an unfulfilled expectation on the `Expr` node which will appear to the user as a warning.

But anyway let me have a go and see what happens.

**Comment by gurry** [comment]
Opened draft PR #130293 that adds the lint on `Stmt`. It does suffer from the extra warning problem.
