### ISSUE TITLE
x.py fmt: logic for "which files changed" is broken when there are no changes

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#130147]
When I run `./x.py fmt` in a clean checkout, I get the following:
```
fmt: formatted 5534 modified files
```
If I now change a single file manually, it says instead:
```
fmt: formatted modified file library/core/src/ptr/mod.rs
```

Cc @rust-lang/bootstrap

**Comment by ibilalkayy** [comment]
I modified the same `mod.rs` file and got this kind of result.

I want to know what is the problem that you want to solve. I didn't understand from this issue that you raised.

![erro](https://github.com/user-attachments/assets/e7e03ac4-11d2-434f-9441-a4e64d945a9e)

**Comment by RalfJung** [comment]
> I want to know what is the problem that you want to solve

- Put your repo into a state where it is entirely in sync with upstream master
- run `./x.py fmt`

That should only format the files that changed, which is 0 files. Instead if formats >5000 files.

**Comment by ibilalkayy** [comment]
I have synced with the upstream master but it showing me all the files.

![again](https://github.com/user-attachments/assets/5972e9e1-33cb-4974-8167-f3e5e80a09f3)

**Comment by Kobzol** [comment]
(Note that this issue is not fixed yet, it needs https://github.com/rust-lang/rust/pull/130161 to be merged first).

**Comment by ibilalkayy** [comment]
Thank you, for letting me know!
