### ISSUE TITLE
[discussion] `ErrorKind::FilesystemQuotaExceeded` from `io_error_more`

### ISSUE THREAD

**Issue by GrigorenkoPV** [rust-lang/rust#130190]
@rustbot label C-discussion

Main tracking issue: #86442

## Background

The [`io_error_more` feature](https://github.com/rust-lang/rust/issues/86442) introduced 21 new variants into [`ErrorKind`](https://doc.rust-lang.org/nightly/std/io/enum.ErrorKind.html). They were [FCP'd back in December 2022](https://github.com/rust-lang/rust/issues/86442#issuecomment-1368082102), but there appeared to be quite a lot of disagreement about 4 of the added variants, so the stabilization (#106375) got stalled for over twenty months. Thankfully, the 17 uncontroversial variants got stabilized in #128316, so now we just need to iron out a satisfactory design for the remaining 4 variants, and then they can be stabilized too.

In order to not block any of the remaining variants on each other and to not intertwine the discussions, I've created 4 separate issues, which summarize the concerns & suggestions voiced up until this point and can serve as a place for further discussion.

-  `FilesystemLoop`:  #130188
-  `FilesystemQuotaExceeded`: you are here
-  `CrossesDevices`: #130191
-  `InvalidFilename`: #130192

# `FilesystemQuotaExceeded`

Currently corresponds to `EDQUOT` on Unix and `ERROR_DISK_QUOTA_EXCEEDED` on Windows. (https://github.com/rust-lang/rust/issues/86442#issuecomment-1235763183). As well as `WSAEDQUOT` on Windows (#130206).

Current docs description:

> Filesystem quota was exceeded.

## Drop "Filesystem" from the name

> Can `FilesystemQuotaExceeded` be renamed `QuotaExceeded`? AFAIK Linux has no other quota error and `EDQUOT` is also used generically (not only for filesystem quotas). A few other uses are visible here: https://elixir.bootlin.com/linux/v4.5/ident/EDQUOT. The comment in `errno.h` simply describes it as "Quota exceeded".

_Originally posted by kalcutter in https://github.com/rust-lang/rust/issues/86442#issuecomment-1367072434_
            
> With my libs-api hat on: :+1: for renaming `FilesystemQuotaExceeded` to `QuotaExceeded`, as OSes may use it for other kinds of quotas.

_Originally posted by Josh Triplett in https://github.com/rust-lang/rust/issues/106375#issuecomment-1371870620_

> I am not quite so sure about [keeping "Filesystem" in the name of] `FilesystemQuotaExceeded` but again I think APIs in std won't produce this error other than for filesystem operations.

_Originally posted by Ian Jackson in https://github.com/rust-lang/rust/issues/106375#issuecomment-1372131054_

Seemingly a consensus.

## ~Also map `WSAEDQUOT` on Windows~

Done in #130206.

<details>

<summary>Old description</summary>

> There is also the winsock error `WSAEDQUOT`. Shouldn't that be mapped [...] to `QuotaExceeded`?

_Originally posted by kalcutter in https://github.com/rust-lang/rust/issues/106375#issuecomment-1372413484_
            
> Yes, I think so.  I'm not sure why we overlooked that.  Generally I would expect that a `WSAE` error should be mapped the same way as the correspondingly named `E` error on Unix.  I think I tired to do that.  Are there other omissions?

_Originally posted by Ian Jackson in https://github.com/rust-lang/rust/issues/106375#issuecomment-1372422167_

A consensus.

</details>

**Comment by joshtriplett** [comment]
Ping @Amanieu @BurntSushi @m-ou-se

**Comment by GrigorenkoPV** [comment]
Stabilized in #130254, closing.
