### ISSUE TITLE
Why does `Duration::from_millis` and `Duration::as_millis` take different integer sizes? (u64 vs u128)

### ISSUE THREAD

**Issue by OscarTHZhang** [rust-lang/rust#130286]
Shouldn't the API be consistent with either using u64 or u128 for both, not one for u64 and one for u128

**Comment by workingjubilee** [comment]
`Duration::from_millis` landed in 1.3, `Duration::as_millis` landed in 1.33, and changing either would be pointlessly breaking, now.

**Comment by workingjubilee** [comment]
If you do wish to propose an API modification that somehow gets around "changing it would be breaking", I suggest opening it at https://github.com/rust-lang/libs-team/issues
