### ISSUE TITLE
Incorrect "function is never used" for function only used in a const assertion

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#130213]
### Code

```Rust
const fn black_box<T>(x: T) -> T { x }

const _: () = {
    assert!(black_box(5) == 5);
};
```

### Current output

```Shell
warning: function `black_box` is never used
 --> src/lib.rs:1:10
  |
1 | const fn black_box<T>(x: T) -> T { x }
  |          ^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default
```

### Desired output

```Shell
(none)
```

### Rationale and extra context

The function is used in a const assertion -- that can have a side-effect so it should be considered a "use".

### Rust Version

```Shell
Current nightly
```

**Comment by CastilloDel** [comment]
Hey! I would like to tackle this. Could you give some pointers on where to look? I'm still unfamiliar with the codebase.

@rustbot claim

**Comment by RalfJung** [comment]
Sorry, I got no idea. Maybe try the t-compiler/help stream on Zulip.

**Comment by zachs18** [comment]
Related https://github.com/rust-lang/rust/issues/118424

**Comment by RalfJung** [comment]
Ah indeed, this is a duplicate.
