### ISSUE TITLE
build_helper isn't documented in the rustc internal docs

### ISSUE THREAD

**Issue by lolbinarycat** [rust-lang/rust#130355]
### Location

https://doc.rust-lang.org/nightly/nightly-rustc

### Summary

the `build_helper` crate is not documented.  this makes working on things like bootstrap more difficult.  it is not used by the compiler directly, but neither is `run_make_support`, which is documented.

**Comment by jieyouxu** [comment]
This needs a doc step in bootstrap, previously Chris (I think?) added doc step for run_make_support which is why that exists.
