### ISSUE TITLE
WebAssembly calling convention impl incorrectly uses make_indirect_byval()

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#130442]
It should use `make_indirect()` instead. It seems like LLVM ignores `sarg` on WebAssembly, so it happens to work out fine in the end with the LLVM backend at least, but it is still incorrect per https://github.com/WebAssembly/tool-conventions/blob/main/BasicCABI.md.

For those unaware the difference between the two is that `make_indirect()` will pass a pointer to the argument somewhere, while `make_indirect_byval()` is supposed to store the argument at a fixed location on the stack.

**Comment by workingjubilee** [comment]
> For those unaware the difference between the two is that make_indirect() will pass a pointer to the argument somewhere, while make_indirect_byval() is supposed to store the argument at a fixed location on the stack.

So one is `pass_by_pointer` and the one is `pass_by_stack_location`?

**Comment by bjorn3** [comment]
Yes. The former sets the pass mode to `PassMode::Indirect { on_stack: false, ... }` while the latter sets it to `PassMode::Indirect { on_stack: true, ... }`. I believe the `on_stack` field used to be called `byval` too, but I changed it a couple of years ago as `byval` is pretty confusing.
