### ISSUE TITLE
rustdoc reports issues against `lib.rs` rather than an `include_str!`'d file

### ISSUE THREAD

**Issue by fasterthanlime** [rust-lang/rust#130470]
The repro repository has everything: https://github.com/fasterthanlime/readme-md-error-reporting

Expected behavior is that the diagnostics have: ` --> README.md:7:16`, but they currently have ` --> src/lib.rs:7:16`.

**Comment by fasterthanlime** [comment]
cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Thanks for opening the issue! I'm surprised since it's an issue that was supposed to be fixed in https://github.com/rust-lang/rust/pull/123204. Just to confirm: which rustc version do you use?

**Comment by fasterthanlime** [comment]
This happened with 1.81 most likely — I would take the few secs to check but I’m on a phone right now.

**Comment by fasterthanlime** [comment]
I can confirm this does fix my repro:

![Image](https://github.com/user-attachments/assets/f962761a-5328-44b8-bf5c-792699f8637c)

Would you like a separate issue for the part where it says `src/../README.md` when really it could normalize the path and just say `README.md` ?

**Comment by GuillaumeGomez** [comment]
Yes please!

**Comment by fasterthanlime** [comment]
> Yes please!

@GuillaumeGomez filed as https://github.com/rust-lang/rust/issues/130626

**Comment by GuillaumeGomez** [comment]
Thanks! Gonna take a look in the next days if someone else didn't do it before then.
