### ISSUE TITLE
Update FreeBSD build

### ISSUE THREAD

**Issue by devnexen** [rust-lang/rust#130465]
Actually a docker build to compile freebsd component binaries is used, for the 12.x versions. Problem is when we want to update in order to build for a more recent version, we fall into a [conundrum](https://github.com/rust-lang/rust/pull/120869#issuecomment-2094979404). Ideally , instead, using Cirrus to build FreeBSD binaries would be more straightforward or how do we update the toolchain used to build rustc ?

**Comment by jieyouxu** [comment]
@devnexen you may want to get in touch with T-infra on zulip (https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra) to discuss this.

**Comment by devnexen** [comment]
Problem solved with [this commit](https://github.com/rust-lang/rust/commit/1239c81c145d2bfb96f32856f377cd741d5c7256).
