### ISSUE TITLE
`-Z randomize-layout` compiler flag is not documented in the unstable book

### ISSUE THREAD

**Issue by fasterthanlime** [rust-lang/rust#130462]
### Location

https://doc.rust-lang.org/nightly/unstable-book/compiler-flags.html

### Summary

I expected to find a page for `-Z randomize-layout`, as described in https://github.com/rust-lang/rust/issues/106764, but I didn't find any.

**Comment by ChrisDenton** [comment]
A meta note is that we need to do a better job of making sure unstable flags are documented. This isn't the first time this has happened and I suspect there are a number of other unintentionally undocumented flags.

Ideally we'd have CI check for it but I understand that may be more complex than it sounds.
