### ISSUE TITLE
Improve borrow checking error in cases where `+ use<>` could be used

### ISSUE THREAD

**Issue by tmandry** [rust-lang/rust#130545]
> I'm not sure if anyone has raised this, but maybe [this error reporting could be improved](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=7362fef0e0f2d48ab4ff368c6e00b402) to also say "consider adding `+ use<>` rather than just complaining about an immutable borrow?
> 
> 
> 
> ```rust
> 
> error[E0502]: cannot borrow `data` as mutable because it is also borrowed as immutable
> 
>  --> src/main.rs:6:5
>   |
> 5 |     let mut i = indices(&data);
>   |                         ----- immutable borrow occurs here
> 6 |     data.push(4);
>   |     ^^^^^^^^^^^^ mutable borrow occurs here
> 7 |     i.next();
>   |     - immutable borrow later used here
> ```
> 
> 
> 
> Instead,
> 
> 
> 
> ```rust
> 
> error[E0502]: cannot borrow `data` as mutable because it is also borrowed as immutable
> 
>  --> src/main.rs:6:5
>   |
> 5 |     let mut i = indices(&data);
>   |                         ----- immutable borrow occurs here
> 6 |     data.push(4);
>   |     ^^^^^^^^^^^^ mutable borrow occurs here
> 7 |     i.next();
>   |     - immutable borrow later used here
> 
> 10 | fn indices<T>(
> 11 |     slice: &[T],
> 12 | ) -> impl Iterator<Item = usize> + use<> {
>   |                                     ----- `impl Trait` must mention all type parameters in scope in `use<...>`
> ``` 

 _Originally posted by @bsodmike in [#125836](https://github.com/rust-lang/rust/issues/125836#issuecomment-2336620825)_

**Comment by bsodmike** [comment]
Thanks for picking this up :)

**Comment by compiler-errors** [comment]
@bsodmike: The link you shared is broken. Could you share the sample of code you provided?

**Comment by compiler-errors** [comment]
nvm, I manually extracted it out of gist:

```
#![allow(warnings)]

fn main() {
    let mut data = vec![1, 2, 3];
    let mut i = indices(&data);
    data.push(4);
    i.next();
}

fn indices<T>(
    slice: &[T],
) -> impl Iterator<Item = usize> {
    0 .. slice.len()
}
```

**Comment by bsodmike** [comment]
> nvm, I manually extracted it out of gist:
> 
> ```
> #![allow(warnings)]
> 
> fn main() {
>     let mut data = vec![1, 2, 3];
>     let mut i = indices(&data);
>     data.push(4);
>     i.next();
> }
> 
> fn indices<T>(
>     slice: &[T],
> ) -> impl Iterator<Item = usize> {
>     0 .. slice.len()
> }
> ```

Sorry. The Rust playground is having a day off. Excellent!
