### ISSUE TITLE
language server seems not recognize print macro identifier

### ISSUE THREAD

**Issue by loynoir** [rust-lang/rust#130504]
language server seems not recognize print macro identifier

## actual

rename in rs

```rust
    let foo: i32 = 42;
    eprintln!("value={foo}");
```

```rust
    let bar: i32 = 42;
    eprintln!("value={foo}");
```

## expected

rename in ts

```ts
let foo = 42
console.log(`value=${foo}`)
```

```ts
let bar = 42
console.log(`value=${bar}`)
```

**Comment by fmease** [comment]
Are you using rust-analyzer? If so, could you double-check that you have a recent version installed?
https://github.com/rust-lang/rust-analyzer/issues/11260 should've been fixed already by https://github.com/rust-lang/rust-analyzer/pull/16027 back in December of 2023.

As an aside, in the future please report issues specific to rust-analyzer over at  https://github.com/rust-lang/rust-analyzer/ if that's indeed the language server you are using.

**Comment by loynoir** [comment]
Oh, it works in  `channel = "1.80.0"`, not works in `channel = "nightly-2024-08-28"`

**Comment by loynoir** [comment]
> As an aside, in the future please report issues specific to rust-analyzer over at https://github.com/rust-lang/rust-analyzer/ if that's indeed the language server you are using.
