### ISSUE TITLE
Tracking Issue for `const_char_encode_utf8`

### ISSUE THREAD

**Issue by bjoernager** [rust-lang/rust#130512]
Feature gate: `#![feature(const_char_encode_utf8)]`

This is a tracking issue for supporting `char::encode_utf8` in const scenarios.

### Public API

```rust
impl char {
    pub const fn encode_utf8(self, dst: &mut [u8]) -> &mut str;
}
```

### Steps / History

- [x] Implementation: #130511
- [x] Address diagnostics: #130611 
- [x] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by dtolnay** [comment]
@rfcbot fcp merge

`const` for https://doc.rust-lang.org/nightly/core/primitive.char.html#method.encode_utf8

**Comment by BurntSushi** [comment]
I'll note that in the [implementation PR](https://github.com/rust-lang/rust/pull/130511/files), making this const seems to require making the panic error message worse (even in the case where `encode_utf8` isn't used in a `const` context) and also introducing more uses of `unsafe`. I'm not especially happy about that.

**Comment by bjoernager** [comment]
The use of unsafe code cannot be avoided as long as slice indexes aren't const-friendly (AFAIK). But I would argue that this use is properly documented and (relatively) invulnerable to UB, although I am open to other views on this.

@RalfJung has also noted that `core::intrinsics::const_eval_select` could be used to regain full diagnostics in non-const calls – a feature which I would be more than happy trying to implement.

**Comment by RalfJung** [comment]
We could have a safe "const fn subslice" that does the bounds check and then uses unsafe from_raw_parts. That would avoid introducing new unsafe reasoning in encode_utf8 itself.

**Comment by bjoernager** [comment]
#130611 resolves the diagnostics question. Can this be added without conflicting with the FCP?

**Comment by BurntSushi** [comment]
@bjoernager Yeah that should be fine. Thank you! I appreciate that. :-)

**Comment by RalfJung** [comment]
Plesse add a FIXME(const-hack) next to the const-eval-select to document that it should be removed again in the future, when possible.

**Comment by bjoernager** [comment]
Done. :)

**Comment by bjoernager** [comment]
Am I supposed to draft a stabilisation PR or is that outside my domain?

**Comment by RalfJung** [comment]
If you want to then yes you can draft a stabilization PR. :)  Please link it to this issue and mention that it must only land once FCP has completed.

**Comment by bjoernager** [comment]
#131463 stabilises this.
