### ISSUE TITLE
regression: unsafe precondition(s) violated: Layout::from_sign_align_unchecked requires...

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#130579]
- https://crater-reports.s3.amazonaws.com/beta-1.82-1/beta-2024-09-05/gh/LeonineKing1199.minivec/log.txt
  - https://crater-reports.s3.amazonaws.com/beta-1.82-1/beta-2024-09-05/gh/RArbore.weakc/log.txt
  - https://crater-reports.s3.amazonaws.com/beta-1.82-1/beta-2024-09-05/reg/griddle-0.5.2/log.txt
  - https://crater-reports.s3.amazonaws.com/beta-1.82-1/beta-2024-09-05/reg/tinyset-0.4.15/log.txt

```
[INFO] [stderr] unsafe precondition(s) violated: Layout::from_size_align_unchecked requires that align is a power of 2 and the rounded-up allocation size does not exceed isize::MAX
[INFO] [stdout] test test_split_off ... ok
[INFO] [stderr] stack backtrace:
[INFO] [stderr]    0:     0x5c23fa0b008a - std::backtrace_rs::backtrace::libunwind::trace::h9ce576133d3ff57c
[INFO] [stderr]                                at /rustc/c7c49f44a7bb561dd9317e14908a1e50fa478ce5/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
[INFO] [stderr]    1:     0x5c23fa0b008a - std::backtrace_rs::backtrace::trace_unsynchronized::h77316b33bca73147
[INFO] [stderr]                                at /rustc/c7c49f44a7bb561dd9317e14908a1e50fa478ce5/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
[INFO] [stderr]    2:     0x5c23fa0b008a - std::sys::backtrace::_print_fmt::haa182cb1ad45bc9f
[INFO] [stderr]                                at /rustc/c7c49f44a7bb561dd9317e14908a1e50fa478ce5/library/std/src/sys/backtrace.rs:66:9
[INFO] [stderr]    3:     0x5c23fa0b008a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::ha95eeb186e57c055
[INFO] [stderr]                                at /rustc/c7c49f44a7bb561dd9317e14908a1e50fa478ce5/library/std/src/sys/backtrace.rs:39:26
```

note: if the relevant team already accepted this breakage then this issue can be closed

**Comment by saethlin** [comment]
Triage:
`minivec` has an off-by-one in a test that's testing for OOM behavior, it tries to make a layout for isize::MAX+1 bytes
`weakc` tries to do `Layout::from_size_align_unchecked(0, 0)`. The docs identify alignment being nonzero as a precondition.
`griddle` is poking the soundness hole in hashbrown that was fixed in https://github.com/rust-lang/hashbrown/pull/268
`tinyset` has basically the same off-by-one as `minivec`

I'll file issues later.

**Comment by saethlin** [comment]
Issues filed. Not going to bother the author of weakc; the project already doesn't build on stable due to other UB that crater has suppressed with `--cap-lints=warn`.
