### ISSUE TITLE
#[deriving] should copy lint attributes from the original item

### ISSUE THREAD

**Issue by lifthrasiir** [rust-lang/rust#13054]
Otherwise it can be very annoying to use lint-affected items selectively. For example, the following code tries to use an unstable item `X` from a stable item `A`, but boilerplates generated from `#[deriving(Clone)]` do not have `#[allow(unstable)]` attached, so it fails to compile. Currently the only way available is to manually add `impl`s with the proper lint attributes.

```rust
#[deny(unstable)];

#[allow(unstable)]
#[unstable]
#[deriving(Clone)]
struct X;

#[allow(unstable)]
#[deriving(Clone)]
struct A { x: X }

fn main() { }
```

**Comment by petrochenkov** [comment]
It was resolved by https://github.com/rust-lang/rust/pull/29152
