### ISSUE TITLE
regression: linking with `cc` failed

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#130581]
- https://crater-reports.s3.amazonaws.com/beta-1.82-1/beta-2024-09-05/reg/dilithium-raw-0.1.0/log.txt
  - https://crater-reports.s3.amazonaws.com/beta-1.82-1/beta-2024-09-05/reg/voro_rs-0.3.0/log.txt
  - https://crater-reports.s3.amazonaws.com/beta-1.82-1/beta-2024-09-05/reg/pqcrypto-newhope-0.1.2/log.txt
  - https://crater-reports.s3.amazonaws.com/beta-1.82-1/beta-2024-09-05/reg/woff-0.3.3/log.txt
  - https://crater-reports.s3.amazonaws.com/beta-1.82-1/beta-2024-09-05/reg/mountpoint-s3-crt-sys-0.8.0/log.txt
  - https://crater-reports.s3.amazonaws.com/beta-1.82-1/beta-2024-09-05/reg/pblib-rs-0.1.0/log.txt
  - https://crater-reports.s3.amazonaws.com/beta-1.82-1/beta-2024-09-05/reg/libwebp-sys-0.9.6/log.txt
  - https://crater-reports.s3.amazonaws.com/beta-1.82-1/beta-2024-09-05/reg/nostrdb-0.3.4/log.txt
  - https://crater-reports.s3.amazonaws.com/beta-1.82-1/beta-2024-09-05/reg/kangarootwelve_xkcp-0.1.5/log.txt
  - https://crater-reports.s3.amazonaws.com/beta-1.82-1/beta-2024-09-05/reg/ion-c-sys-0.4.17/log.txt

there was far more than just these listed crates that had linker errors. It seems like significantly more than prior crater runs which is odd

**Comment by ChrisDenton** [comment]
cc @NobodyXu in case you have any ideas

**Comment by saethlin** [comment]
Something very fishy is going on here. `libwebp-sys` is small, well-maintained and has quite a few downloads, so I'm looking into that.

`cargo +beta build --tests` fails as crater indicates. I've tried every nightly in 2024-08-XX and 2024-09-XX and all of them can build the crate's tests.

**Comment by saethlin** [comment]
I also cannot reproduce these linker errors using a toolchain that I've built from the beta branch.

**Comment by saethlin** [comment]
Ah! My confusion is because nightly now uses lld by default, which is a good little linker and takes care of you even if you give it a confusing argument order.

**Comment by saethlin** [comment]
Bisects to https://github.com/rust-lang/rust/pull/128400

A crater run was done in that PR but the results were ignored because of the same confusion I ran into above https://github.com/rust-lang/rust/pull/128400#issuecomment-2278764127

**Comment by apiraino** [comment]
As discussed on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23130581.20regression.3A.20linking.20with.20.60cc.60.20failed/near/471553985) is there any actionable here, or can this issue be closed? #128400 was noted in the release notes (unsure if this is enough tho)

**Comment by lqd** [comment]
cc @petrochenkov
