### ISSUE TITLE
improve error msg on inner attr after extern crate et al.

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#13059]
I never remember that inner attributes have to come up above everything else, even extern crate declarations.  The error messages one gets when forgetting this could be improved, e.g. to suggest to the user that if they meant to write an inner attribute, that it needs to appear before other declarations/items.

Consider this code:
```rust
// #[allow(deprecated_owned_vector)]; // <- This one will work

extern crate collections;

// this one yields semi-obcure error msg
#[allow(deprecated_owned_vector)];

pub fn main() { }
```

Here's the error message I get:
```
% rustc /tmp/demo.rs
/tmp/demo.rs:6:34: 6:35 error: expected item but found `;`
/tmp/demo.rs:6 #[allow(deprecated_owned_vector)];
                                                ^
%
```

**Comment by steveklabnik** [comment]
Triage: this error is still the same.

**Comment by Manishearth** [comment]
This has been fixed

```
test.rs:6:3: 6:4 error: an inner attribute is not permitted in this context
test.rs:6 #![allow(deprecated_owned_vector)]
            ^
test.rs:6:3: 6:4 help: place inner attribute at the top of the module or block
error: aborting due to previous error
```

(the semicolon syntax doesn't work anymore)
