### ISSUE TITLE
Clarification on performance improvements in `std::fs::read_to_string` for Windows

### ISSUE THREAD

**Issue by fiveseven-lambda** [rust-lang/rust#130600]
### Location

Function `read_to_string` in `std::fs`
https://doc.rust-lang.org/stable/std/fs/fn.read_to_string.html

### Summary

The current documentation for `std::fs::read_to_string` states that it is a convenience function for `File::open` and `std::io::Read::read_to_string`, providing fewer imports and no intermediate variables. However, after the recent pull request #110655, it seems that `std::fs::read_to_string` has received performance improvements specifically for Windows, addressing issues that `File::open` and `std::io::Read::read_to_string` still face on this platform.

This implies that using `std::fs::read_to_string` is not just a matter of convenience, but may also result in better performance on Windows compared to manually combining `File::open` and `std::io::Read::read_to_string`. 

I believe this performance improvement should be mentioned in the documentation, especially for developers targeting Windows, as the current documentation only emphasizes the convenience aspect without mentioning the performance benefits.

**Suggested change**:
Add a note to the documentation of `std::fs::read_to_string`, clarifying that due to recent improvements in pull request #110655, it offers better performance on Windows than manually using `File::open` and `std::io::Read::read_to_string`.

Thank you for your consideration!

**Comment by workingjubilee** [comment]
PRs welcome!

**Comment by the8472** [comment]
> it seems that std::fs::read_to_string has received performance improvements specifically for Windows, addressing issues that File::open and std::io::Read::read_to_string still face on this platform.

This should not be the case. The read-loop limits the buffer size passed to the underlying reader regardless of whether you use `fs::read_to_string` or `Read::read_to_string`

https://github.com/rust-lang/rust/blob/1a5a2240bc1b8cf0bcce7acb946c78d6493a4fd3/library/std/src/io/mod.rs#L501-L514

**Comment by fiveseven-lambda** [comment]
But the `size_hint` is not passed to `default_read_to_string` when you call `std::io::Read::read_to_string`. Since the trait `std::io::Read` doesn't have any method like `.size_hint()` on `std::iter::Iterator`, we cannot know the file size in advance.
https://github.com/rust-lang/rust/blob/1a5a2240bc1b8cf0bcce7acb946c78d6493a4fd3/library/std/src/io/mod.rs#L903-L906

**Comment by the8472** [comment]
#110650 was not about allocation, it was about a too-large buffer getting passed to the windows API.
For `fs::read_to_string` this is solved by passing a size-hint which allocates the right buffer, so it won't be too-large (added by #110655).
For `Read::read_to_string` this is solved by the heuristics that I linked that apply when no size-hint is passed (added by #118222).

**Comment by fiveseven-lambda** [comment]
Thank you for pointing that out, and I apologize for not noticing the changes introduced in #118222 earlier.
It seems I had a major misunderstanding regarding the performance issue. I really appreciate you taking the time to explain it.
At this point, I no longer feel the need to propose any changes to the documentation.

**Comment by fiveseven-lambda** [comment]
@workingjubilee so I'm sorry for the confusion. I will close both the issue and the PR.

**Comment by the8472** [comment]
Hrrm, looking at it again, the heuristics don't apply optimally.

Usually file io APIs will fill the whole buffer so no short reads will occur, which means it will stay in the doubling regime for a while, which avoids excessive initialization costs. But when it hits EOF there'll be one short read. And since we can't distinguish from short reads and EOF we have do one more read to figure that out. At that point the full buffer will be passed because the heuristics think no initialization happens (since we only check the initialization done via `BorrowedBuf`, not whatever windows is doing).

There should be ways to improve this.

**Comment by the8472** [comment]
Thanks for bringing it to our attention, there appears to be room for improvement after all!

**Comment by fiveseven-lambda** [comment]
Hmm, this is becoming a bit difficult for me to follow. Should we close this issue and PR, and instead create a new one focused on performance improvements?

**Comment by the8472** [comment]
Yes, I think that would be good. My idea would be deferring the  `max_read_size = usize::MAX;` until we got two consecutive short reads without excess BorrowedBuf initialization. There probably are other ways to achieve the same results though.

If you like you can take a stab at it, otherwise I will.

**Comment by the8472** [comment]
@ChrisDenton btw, did you observe what windows is doing? Is it zeroing the buffers in the kernel? If that is the case we could check this in a test by writing some sentinel bytes at the end of a large buffer and check if the survive a trip through the read_to_end API.

**Comment by ChrisDenton** [comment]
Iirc it's aggressively locking every page in the buffer. Which can matter if the buffer is large but the read is relatively small.

**Comment by fiveseven-lambda** [comment]
It seems difficult for me to touch the source code.

**Comment by the8472** [comment]
PR #130670

**Comment by CAD97** [comment]
> But the `size_hint` is not passed to `default_read_to_string` when you call `std::io::Read::read_to_string`.

This is incorrect. The heuristics never apply in this case, as `<&File as Read>::read_to_end` does not use the default implementation and does supply the metadata-derived expected read size. The only optimization that `fs::read_to_string` has is that it can use the size from the file metadata directly and doesn't need to retrieve the current seek position of the file handle.

https://github.com/rust-lang/rust/blob/28364822410af31bba5c8adac19cbbfcb9b48717/library/std/src/fs.rs#L830-L835
