### ISSUE TITLE
FromRawFd is missing a safety section

### ISSUE THREAD

**Issue by lolbinarycat** [rust-lang/rust#130647]
### Location

https://doc.rust-lang.org/std/os/fd/trait.FromRawFd.html#tymethod.from_raw_fd

### Summary

the usage of `unsafe` implies there is some unchecked precondition(s) that must be true to prevent UB, but there is no documentation saying what this precondition might be.

this means there's basically no way to know if you are using this interface soundly.

**Comment by PatchMixolydic** [comment]
[There appears to be a safety section on my end](https://doc.rust-lang.org/std/os/fd/trait.FromRawFd.html#safety):

> # Safety
> The `fd` passed in must be an [owned file descriptor](https://doc.rust-lang.org/std/io/index.html#io-safety); in particular, it must be open.

**Comment by Noratrieb** [comment]
yeah, looks like you overlooked that one
