### ISSUE TITLE
rustdoc: First line of documentation on collapsed impl blocks should be visible

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust#130612]
There exists a technique to make a type's methods more organized, by putting them in separate impl blocks.
This also helps with the organization of the documentation. Makes the various methods much easier to overview and discover.
For an example, take a look at what egui is doing with its `Ui` type: https://docs.rs/egui/latest/egui/struct.Ui.html
![Image](https://github.com/user-attachments/assets/97161111-14dc-4824-a9a2-2dbe0deb032f)

However, if we collapse all the impl blocks, the documentation becomes much harder to overview.

![Image](https://github.com/user-attachments/assets/d353858c-2663-4885-b3dc-9a3f1fefd9d2)

Rustdoc could help the user out here by displaying the first line of the documentation for each collapsed impl block.

Concept art cobbled together in GIMP:
![Image](https://github.com/user-attachments/assets/95f0fcdd-0f56-4d69-bbae-10a85bcb5c9e)

Moreover, there should be an easy way to collapse all impl blocks for easy overview.
Currently, all impl blocks have to be collapsed manually one-by-one. The "collapse all docs" button ignores impl blocks.

**Comment by emilk** [comment]
Nice idea - maybe something for @GuillaumeGomez? :)

**Comment by GuillaumeGomez** [comment]
The idea sounds nice. Will need to talk about it with the rest of the team.

**Comment by GuillaumeGomez** [comment]
We just discussed it in [rustdoc meeting](https://rust-lang.zulipchat.com/#narrow/stream/393423-t-rustdoc.2Fmeetings/topic/2024-10-14/near/476841048) and all present members agreed that it was a good idea. We will (hopefully I will have some time next week) try to implement it in the near future.

**Comment by GuillaumeGomez** [comment]
Implementation done. Cleaning up and then time to open the PR.
