### ISSUE TITLE
Tracking Issue for `const_char_encode_utf16`

### ISSUE THREAD

**Issue by bjoernager** [rust-lang/rust#130660]
Feature gate: `#![feature(const_char_encode_utf16)]`

This is a tracking issue for supporting `char::encode_utf16` in const scenarios.

### Public API

```rust
impl char {
    pub const fn encode_utf16(self, dst: &mut [u16]) -> &mut [u16];
}
```

### Steps / History

- [x] Implementation: #130659
- [x] Final comment period (FCP)
- [ ] Stabilization PR: #132153

### Unresolved Questions

- None yet.

**Comment by bjoernager** [comment]
I don't think `char::decode_utf16` currently can be implemented as const due to its dependence on `IntoIterator`.

**Comment by dtolnay** [comment]
@rfcbot fcp merge

Enabled by the recent stabilization of `&mut` in const (https://github.com/rust-lang/rust/pull/129195).

**Comment by bjoernager** [comment]
Stabilised by #132153.
