### ISSUE TITLE
run-make `-Zbuild-std` tests fail on `compiler_builtins` on older branches

### ISSUE THREAD

**Issue by cuviper** [rust-lang/rust#130634]
I tried: merging backports on 1.82-beta (#130569)

I expected to see this happen: Test successful

Instead, this happened: The job `dist-various-1` failed!

```
failures:
    [run-make] tests/run-make/compiler-builtins
    [run-make] tests/run-make/thumb-none-cortex-m
```

Both tests use `-Zbuild-std` and failed to build `compiler_builtins v0.1.126`:

```
error[E0433]: failed to resolve: could not find `naked_asm` in `arch`
##[error]  --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/compiler_builtins-0.1.126/src/arm.rs:26:21
   |
26 |         core::arch::naked_asm!(
   |                     ^^^^^^^^^ could not find `naked_asm` in `arch`

error[E0433]: failed to resolve: could not find `naked_asm` in `arch`
##[error]  --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/compiler_builtins-0.1.126/src/arm.rs:39:21
   |
39 |         core::arch::naked_asm!(
   |                     ^^^^^^^^^ could not find `naked_asm` in `arch`

error[E0433]: failed to resolve: could not find `naked_asm` in `arch`
##[error]  --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/compiler_builtins-0.1.126/src/arm.rs:54:21
   |
54 |         core::arch::naked_asm!(
   |                     ^^^^^^^^^ could not find `naked_asm` in `arch`

error[E0433]: failed to resolve: could not find `naked_asm` in `arch`
##[error]  --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/compiler_builtins-0.1.126/src/arm.rs:66:21
   |
66 |         core::arch::naked_asm!(
   |                     ^^^^^^^^^ could not find `naked_asm` in `arch`
```

Note that beta's `library/Cargo.lock` only has `compiler_builtins v0.1.123`, so it appears cargo isn't heeding that with `-Zbuild-std`.

`arch::naked_asm!` was added in #130146 and started being used in rust-lang/compiler-builtins#686 for 0.1.126.

To unblock beta, I'm going to add `//@ only-nightly` to those tests, as suggested on my PR, especially since `-Zbuild-std` is unstable anyway. This particular failure shouldn't be an issue when the current nightlies are promoted to the next beta, but we should think about this kind of failure mode in the long term too.

**Comment by workingjubilee** [comment]
We should probably add a test using the beta compiler to the `compiler_builtins` CI.

**Comment by workingjubilee** [comment]
We could also add running the beta compiler with `-Zbuild-std` to rust-lang/rust's CI?

**Comment by cuviper** [comment]
I think this kind of thing would also be an issue once we get to the stable promotion. I don't know if `compiler_builtins` wants to promise any kind of MSRV, but really I would have expected the library lock file to be used.

**Comment by saethlin** [comment]
I'm very surprised there isn't a lockfile being used here. Does -Zbuild-std not use one automatically? Should be modify the tests to cp in the one from library/Cargo.lock?

**Comment by workingjubilee** [comment]
well at least now libstd has its own lockfile, so that makes things easier.

**Comment by cuviper** [comment]
Those run-make tests are using stage0 cargo, which is 1.81.0 on the beta branch, and @weihanglo [pointed out](https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/-Zbuild-std.20doesn't.20know.20where.20the.20library.20Cargo.2Elock.20is/near/471831549) that this version doesn't have the logic to find the relatively new `library/Cargo.lock`.

Maybe run-make should always use the current stage's cargo as a prereq? (i.e. the same stage as `rustc`)

**Comment by saethlin** [comment]
> Maybe run-make should always use the current stage's cargo as a prereq? (i.e. the same stage as `rustc`)

Definitely. I thought using bootstrap cargo was sus when I wrote that but I had already spent a lot of time trying to get any cargo to run.

**Comment by jieyouxu** [comment]
> Maybe run-make should always use the current stage's cargo as a prereq?

Yes, I probably should've done that even if bootstrap cargo somehow worked
