### ISSUE TITLE
std::fs::read_dir returns ENOSYS on wasm32-wasip1

### ISSUE THREAD

**Issue by Timmmm** [rust-lang/rust#130699]
I'm using the `wasm32-wasip1` target to compile this code:

    std::fs::read_dir(path)?

Which I then run with Node 20.

<details>

```
import { WASI } from "node:wasi";
import { readFile } from "node:fs/promises";
import { join } from "node:path";

async function main() {
	const wasm = await WebAssembly.compile(
		await readFile(join(__dirname, "server.wasm")),
	);
	const wasi = new WASI({
		env: {
			RUST_BACKTRACE: "1",
		},
		// This option is mandatory.
		version: "preview1",
		preopens: {
			"/": "/",
			"a:/": "a:/",
			"b:/": "b:/",
			"c:/": "c:/",
			"d:/": "d:/",
			"e:/": "e:/",
...
		},
	});
	const instance = await WebAssembly.instantiate(wasm, <WebAssembly.Imports>wasi.getImportObject());

	wasi.start(instance);
}

main();
```
</details>

It gives this error, which I believe corresponds to `ENOSYS`.

```
Err(Os { code: 52, kind: Unsupported, message: "Function not implemented" })
```

Does anyone know why this doesn't work? I can think of at least a few possibilities but it's really difficult to know given such an uninformative error message:

1. WASI Preview 1 simply doesn't support listing directories
2. wasi-libc hasn't implemented the C->WASI libc functions necessary
3. Rust itself hasn't implemented the Rust->C `sys` functions necessary
4. Node's WASI runtime hasn't implemented something necessary for this

**Comment by bjorn3** [comment]
Looks like Node doesn't support fd_readdir on Windows yet: https://github.com/nodejs/node/blob/2cec716c48cea816dcd5bf4997ae3cdf1fe4cd90/deps/uvwasi/src/uvwasi.c#L1537

**Comment by Timmmm** [comment]
Ah good sleuthing! [This seems to be the issue.](https://github.com/nodejs/uvwasi/issues/11)

I've got to say it seems weird to bother with WASI at all if you aren't going to at least support the most popular desktop OS... Hopefully it's just a TODO rather than "WASI designers pretty much copied POSIX".

**Comment by Timmmm** [comment]
I guess I'll close this anyway since it seems to be a Node issue rather than a Rust one.

**Comment by bjorn3** [comment]
Wasmtime and several other standalone wasm engines support the entirety of wasi on Windows just fine. It is just Node's wasi impl that has problems with Windows.
