### ISSUE TITLE
cargo build error with compile thread-id

### ISSUE THREAD

**Issue by Macdot3** [rust-lang/rust#130636]
### Code

git clone https://github.com/nanoporetech/modkit.git
cd modkit
cargo install --path .

### Affected release channels

- [ ] Previous Stable
- [x] Current Stable
- [ ] Current Beta
- [ ] Current Nightly

### Rust Version

rustc 1.81.0 (eeb90cda1 2024-09-04)
binary: rustc
commit-hash: eeb90cda1969383f56a2637cbd3037bdf598841c
commit-date: 2024-09-04
host: x86_64-unknown-linux-gnu
release: 1.81.0
LLVM version: 18.1.7

### Current error output

Compiling thread-id v4.2.2
error: Unrecognized option: 'json'
error: could not compile `thread-id` (lib)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `mod_kit v0.4.0 (https://github.com/nanoporetech/modkit.git#49b7bcc3)`, intermediate artifacts can be found at `/tmp/cargo-install5qAd56`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

### Backtrace

a

**Comment by saethlin** [comment]
I cannot reproduce any build error from the provided instructions. Can you run that command with `-v` added and share the full command that fails?

**Comment by Macdot3** [comment]
After running these commands separately:

```
git clone https://github.com/nanoporetech/modkit.git
cd modkit
cargo -v install --path .
```
start compiling many libraries until encountering the error you see:

```
Compiling ordered-float v3.9.2
     Running `rustc --crate-name ordered_float --edition=2021 /home/marco/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ordered-float-3.9.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=120 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="default"' --cfg 'feature="std"' --check-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values("arbitrary", "bytemuck", "default", "proptest", "rand", "randtest", "rkyv", "rkyv_16", "rkyv_32", "rkyv_64", "rkyv_ck", "schemars", "serde", "speedy", "std"))' -C metadata=ff3e7e8010c59ed6 -C extra-filename=-ff3e7e8010c59ed6 --out-dir /home/marco/modkit/target/release/deps -C strip=debuginfo -L dependency=/home/marco/modkit/target/release/deps --extern num_traits=/home/marco/modkit/target/release/deps/libnum_traits-69cffc49c0a01a12.rmeta --cap-lints allow`
   Compiling thread-id v4.2.2
     Running `rustc --crate-name thread_id --edition=2015 /home/marco/.cargo/registry/src/index.crates.io-6f17d22bba15001f/thread-id-4.2.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=120 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --check-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values())' -C metadata=748a40c10979012d -C extra-filename=-748a40c10979012d --out-dir /home/marco/modkit/target/release/deps -C strip=debuginfo -L dependency=/home/marco/modkit/target/release/deps --extern libc=/home/marco/modkit/target/release/deps/liblibc-f8558ac8830a0895.rmeta --cap-lints allow`
error: Unrecognized option: 'json'

error: could not compile `thread-id` (lib)

Caused by:
  process didn't exit successfully: `rustc --crate-name thread_id --edition=2015 /home/marco/.cargo/registry/src/index.crates.io-6f17d22bba15001f/thread-id-4.2.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=120 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --check-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values())' -C metadata=748a40c10979012d -C extra-filename=-748a40c10979012d --out-dir /home/marco/modkit/target/release/deps -C strip=debuginfo -L dependency=/home/marco/modkit/target/release/deps --extern libc=/home/marco/modkit/target/release/deps/liblibc-f8558ac8830a0895.rmeta --cap-lints allow` (exit status: 1)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `mod_kit v0.4.0 (/home/marco/modkit)`, intermediate artifacts can be found at `/home/marco/modkit/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```
I followed the instructions from the nanopore github page for the tool. I installed the cargo version 1.80.1 locally because with rust it installed a previous version that did not correspond to that of rustc. Even with cargo version 1.75, it gave the same error.
How can I solve it? thank you so much for your help.

**Comment by Noratrieb** [comment]
it seems like something is wrong with your rustc setup and it's somehow using an old version of rustc. how did you install rustc and cargo, where are they located, and what's the output of `rustc --vV` and `cargo -vV`?

**Comment by Macdot3** [comment]
Here you the outputs: 

```
rustc 1.81.0 (eeb90cda1 2024-09-04)
binary: rustc
commit-hash: eeb90cda1969383f56a2637cbd3037bdf598841c
commit-date: 2024-09-04
host: x86_64-unknown-linux-gnu
release: 1.81.0
LLVM version: 18.1.7

cargo 1.80.1 (376290515 2024-07-16)
release: 1.80.1
commit-hash: 37629051518c3df9ac2c1744589362a02ecafa99
commit-date: 2024-07-16
host: x86_64-unknown-linux-gnu
libgit2: 1.7.2 (sys:0.18.3 vendored)
libcurl: 8.6.0-DEV (sys:0.4.72+curl-8.6.0 vendored ssl:OpenSSL/1.1.1w)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Ubuntu 22.4.0 (jammy) [64-bit]

/home/marco/.cargo/bin/rustc
/home/marco/.cargo/bin/cargo
```

**Comment by Noratrieb** [comment]
I would suggest deleting every version of Rust you have installed (including `rustup self uninstall`) and installing a single version from scratch again (with the install script, or another way if you prefer). It looks like something got quite confused by your setup of installing it through rustup and also through the installer manually.

**Comment by saethlin** [comment]
That cargo 1.75.0 may have been from Ubuntu. I strongly advise against attempting to install rust/rustc/cargo from Ubuntu, if you haven't already you should `apt purge cargo` and `apt purge rust` for good measure. While it is technically possible to use the toolchain that Ubuntu ships, it is way more trouble than it is worth.

**Comment by Macdot3** [comment]
Thank you very much @Noratrieb and @saethlin, I’ve solved it!` sudo apt purge` removed everything, but somehow, maybe during various installations, I had an old version of Cargo in `/usr/local/bin` that I hadn’t removed and which I’ve now deleted. Everything is working now, and I managed to use the tool. Thank you very much for your support, let's rust again!
