### ISSUE TITLE
compiletest: crashes tests should mention `COMPILETEST_VERBOSE_CRASHES` if no longer crashes

### ISSUE THREAD

**Issue by jieyouxu** [rust-lang/rust#130776]
E.g. if a test doesn't have a `main` fn it can prevent the test from ICEing because ICEing codepath might not yet be reached before compilation is aborted. In this case, the stderr should be printed to help the person figure out that "I forgor to annotate crate type" is the cause.

**Comment by matthiaskrgr** [comment]
you can set `COMPILETEST_VERBOSE_CRASHES` env var which should print stdout, stderr and exit code

**Comment by jieyouxu** [comment]
Oh right, good point, I forgor this existed. We should add (I'll do this later unless you want to work on it):

- Mention of this env var in the panic message for when the crashes test no longer crash.
- Mention of this env var in rustc-dev-guide
