### ISSUE TITLE
align(64) consumes high amounts of RAM on some targets

### ISSUE THREAD

**Issue by daladim** [rust-lang/rust#130700]
Hi, I noticed that builds of [argon2](https://github.com/RustCrypto/password-hashes/tree/master/argon2) (a password-hashing crate) for Raspberry Pis consume a lot of RAM (there are [multiple](https://github.com/RustCrypto/password-hashes/issues/478) [related](https://github.com/RustCrypto/password-hashes/issues/486) [issues](https://github.com/RustCrypto/password-hashes/issues/526)).

This is a minimal reproducer I could create. The key seems to be the `#[repr(align(64))]`

```rust
#[derive(Clone)]
#[repr(align(64))]  // there is no issue if you remove this line
pub struct Block([u64; 128]);

fn main() {
    for _i in 1..20 {
        let mut blocks = vec![Block([0u64; 128]); 19456];
        println!("just a way to consume the value: {}", blocks.get_mut(0).unwrap().0[1]);

        // A way to visualise the issue
        use memory_stats::memory_stats;
        let stats = memory_stats().unwrap();
        println!("physical memory: {:.2} M", stats.physical_mem as f32 / 1_000_000.0);
    }
}
```

You'll need `cargo add memory-stats` to build.

On most platforms (aarch64 Ubuntu, ARM macOS, x86_64 Ubuntu), this consumes around 20 MiB.
On a Rapsberry Pi board (e.g. Raspi 3 or Raspi 5) using Rapsberry Pi OS (12 Bookworm) and rustc 1.81.0 stable, this consumes more and more memory for the first few iterations, then finally stabilizes at a few hundreds of MiB (on a Raspberry Pi, that's not negligible!).
The same issue happens on a recent nightly compiler.

Example run:
```
user@raspi:~/src/large_ram $ cargo run --release
    Finished `release` profile [optimized] target(s) in 0.01s
     Running `/home/user/cargo_target/release/large_ram`
just a way to consume the value: 0
physical memory: 21.84 M
just a way to consume the value: 0
physical memory: 21.82 M
just a way to consume the value: 0
physical memory: 41.75 M
just a way to consume the value: 0
physical memory: 61.67 M
just a way to consume the value: 0
physical memory: 81.59 M
just a way to consume the value: 0
physical memory: 101.52 M
just a way to consume the value: 0
physical memory: 121.44 M
just a way to consume the value: 0
physical memory: 141.36 M
just a way to consume the value: 0
physical memory: 161.28 M
just a way to consume the value: 0
physical memory: 161.28 M
just a way to consume the value: 0
physical memory: 161.28 M
just a way to consume the value: 0
physical memory: 161.28 M
just a way to consume the value: 0
physical memory: 161.28 M
just a way to consume the value: 0
physical memory: 161.28 M
just a way to consume the value: 0
physical memory: 161.28 M
just a way to consume the value: 0
physical memory: 161.28 M
just a way to consume the value: 0
physical memory: 161.28 M
just a way to consume the value: 0
physical memory: 161.28 M
just a way to consume the value: 0
physical memory: 161.28 M
```

### Meta

```
$ rustc --version --verbose
rustc 1.81.0 (eeb90cda1 2024-09-04)
binary: rustc
commit-hash: eeb90cda1969383f56a2637cbd3037bdf598841c
commit-date: 2024-09-04
host: aarch64-unknown-linux-gnu
release: 1.81.0
LLVM version: 18.1.7
```

I'm afraid I'm not knowledgeable enough about the Rust allocator to be able to troubleshoot further.

This is my first report for the Rust compiler, let me know if I'm not at the right place.

Thanks!

**Comment by bjorn3** [comment]
Rust uses the system allocator. In this case the posix_align function of libc.

**Comment by saethlin** [comment]
As was pointed out in the issues you linked, this is a deliberate property of the system memory allocator. You're welcome to try reporting this upstream to Raspberry Pi OS or glibc, but they will probably want a reproducer written in C.
