### ISSUE TITLE
Non-operational Rust Pontoon Test OAuth-application involved in sign-in on pontoon.rust-lang.org

### ISSUE THREAD

**Issue by Ricky-Tigg** [rust-lang/rust#130872]
Hello. Sign-in on _pontoon.rust-lang.org_, which is currently only possible though the _Rust Pontoon Test_ OAuth-application owned by _rust-pontoon-trial_ linked to GitHub, fails, revealing then an umproper setting. Unlike stated in the message triggered by the failure, no fix has been coming soon.

**Comment by jieyouxu** [comment]
cc https://rust-lang.zulipchat.com/#narrow/stream/336883-i18n/topic/.23100717.20diag.20translation/near/472701978
cc https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/pontoon.20for.20.23100717
cc https://rust-lang.zulipchat.com/#narrow/stream/336883-i18n/topic/pontoon.20and.20next.20steps

**Comment by jieyouxu** [comment]
This is tracked by T-infra at https://github.com/rust-lang/infra-team/issues/91.

**Comment by Noratrieb** [comment]
i don't think anyone from infra will see this, but I don't see a point in keeping it open and don't think it's worth bothering them to ask
