### ISSUE TITLE
building cargo breaks build-cache for other tools

### ISSUE THREAD

**Issue by jieyouxu** [rust-lang/rust#130980]
After https://github.com/rust-lang/rust/pull/130739 I noticed that whenever I modify `run-make` tests (on Windows), stage 1 cargo gets unnecessary rebuilt which also triggers rebuilds for other tools like stage 0 rustdoc. I'm pretty sure something in my implementation is wrong w.r.t. to properly caching, but I didn't invest time in figuring out *why* yet, hence opening this bug to track it.

The build sequence is something like stage 0 std -> stage 1 rustc -> stage 1 std -> stage 1 tool cargo -> stage 0 compiletest / run-make-support / rustdoc.

Example repro steps:
- Run `./x test run-make --stage 1` -> make sure stage 1 cargo is already built.
- Modify a `tests/run-make` rmake.rs test.
- Observe that stage 1 cargo gets rebuilt even though I didn't modify it.

**Comment by jieyouxu** [comment]
EDIT: **oh**, is it because in run-make-support or rustdoc we use `prepare_tool_cargo` or something that is a *different* staged cargo compared to the one we built with stage 1 rustc...

**Comment by jieyouxu** [comment]
Actually unassigning because I don't know how to cleanly fix this just yet.

**Comment by onur-ozkan** [comment]
> Example repro steps:
>
> Run ./x test run-make --stage 1 -> make sure stage 1 cargo is already built.
> Modify a tests/run-make rmake.rs test.
> Observe that stage 1 cargo gets rebuilt even though I didn't modify it.

Running `./x test run-make --stage 1` twice is enough to reproduce cargo rebuild issue. Probably some rustflags invalidating the build cache.

**Comment by jieyouxu** [comment]
Reopening because we need to revert #131060.
