### ISSUE TITLE
rustdoc: toolbar redesign no longer properly handles shortening of long crate names in search dropdown

### ISSUE THREAD

**Issue by steffahn** [rust-lang/rust#130993]
Last time I contributed to the design of the crate selection, which was merged with the following PR
* #100374

I made sure to test the handling of long crate names.

<details><summary>[CLICK TO EXPAND comparison screenshots with the <b>old</b> design]</summary>

Old Design:
![Image](https://github.com/user-attachments/assets/38f372f2-c911-4fee-9f05-906689cb648a)
What happens with a long crate name:
![Image](https://github.com/user-attachments/assets/f94f49c5-a898-416a-906b-b6fd62e20991)

</details>

With the new design
* #129545

the behavior seems a lot worse now:

<details><summary>[CLICK TO EXPAND comparison screenshots with the <b>new</b> design]</summary>

New Design:
![Image](https://github.com/user-attachments/assets/9cf08de8-69f3-4665-8e34-ada9db6a3b62)
What happens with a long crate name:
![Image](https://github.com/user-attachments/assets/f0a22ab4-6c03-49cc-a9a2-b51e91af594c)

</details>

(Refer to the last screenshot above for the following description.)

In particular, I’m noticing that the button grows too large, shifts down a little but for some reason, and then pushes the Settings/Help/Summary control elements off-screen.

I don’t recall off the top of my head the specific HTML/CSS foo that used made this work in the first place, but possible it’s a relatively simple fix.

cc @GuillaumeGomez, @notriddle

**Comment by GuillaumeGomez** [comment]
Good catch! Want to send a fix? Otherwise I'll likely do it tomorrow or monday.

**Comment by steffahn** [comment]
@GuillaumeGomez I don’t think I have too much motivation to get into learning how to use the testing framework this time around, either.

“allow edits by maintainers” is turned on in #131002, so feel free to take over the step of adding appropriate changes to the tests there, and/or point out test failures that are uncovering any *actual* issues with the PR, which I’d be happy to address.

**Comment by GuillaumeGomez** [comment]
No problem, thanks for writing the fix. I'll put together the testing part tomorrow.
