### ISSUE TITLE
Runaway builds on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [rust-lang/rust#130905]
We are getting runaway builds, see this [sample build log](https://pkg-status.freebsd.org/beefy22/data/140amd64-default/7deb3fde758a/logs/veryl-0.13.0.log).

Project: https://github.com/veryl-lang/veryl

rust-1.81.0 and earlier

**Comment by workingjubilee** [comment]
what's a "runaway build"?

**Comment by workingjubilee** [comment]
I glanced at the log and it didn't really explain to me what the problem was. What does "runaway build" mean? Did the build compile an artificial intelligence that started devising and emitting malware in an attempt to achieve privilege escalation and thereby run away from the build server?

**Comment by xacrimon** [comment]
Seems like a duplicate of https://github.com/rust-lang/rust/issues/129776

**Comment by workingjubilee** [comment]
Ah, thank you. Closing as duplicate then!

**Comment by yurivict** [comment]
Runaway means no output in 2 hours.
