### ISSUE TITLE
`NestedMetaItem` would be better named as `MetaItemInner`

### ISSUE THREAD

**Issue by Urgau** [rust-lang/rust#131087]
> An aside: `NestedMetaItem` would be better named as `MetaItemInner`, to match the grammar.

_Originally posted by @nnethercote in https://github.com/rust-lang/rust/pull/131034#discussion_r1781999888_

**Comment by codemountains** [comment]
Hi. I'm also interested in this issue as the first time for contribution to rust!

@rustbot claim

**Comment by nnethercote** [comment]
@codemountains: when you create the pull request, feel free to write "r? @nnethercote" to request review from me.
