### ISSUE TITLE
TotalEq shouldn't need to have the secret method just for #[deriving]

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#13101]
The `assert_receiver_is_total_eq` method is purely so that `#[deriving]` can enforce that all the contained types are `TotalEq`. It currently exists because the `#[deriving]` infrastructure makes it much much much easier to work with a method on a trait than with anything else.

Preferably `#[deriving]` would be refactored to allow creating a non trait function along the lines of

``` rust
#[deriving(TotalEq)]
struct Foo<T> {
     x: int,
     y: T
}

// expands to

impl<T: TotalEq> TotalEq for Foo<T> {}

impl<T: TotalEq> Foo<T> {
     #[allow(dead_code)]
     fn assert_Foo_is_total_eq(&self) {
         fn total_eq<T: TotalEq>(_: &T) {}

         total_eq(&self.x);
         total_eq(&self.y);
     }
}
```

which would allow `TotalEq` to become just `trait TotalEq: Eq {}`.

(Placeholder issue for now.)

**Comment by steveklabnik** [comment]
It's now `Eq` but all the rest is the same.

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by petrochenkov** [comment]
I'm not sure why the restriction exists in the first place:

For `struct S(PatialEqNotEq);`

```
#[derive(PartialEq, Eq)]
struct S(PatialEqNotEq);
```
is illegal, while
```
#[derive(PartialEq)]
struct S(PatialEqNotEq);

impl Eq for S {}
```
is legal.
Is it solely a fool-proofing measure?

**Comment by petrochenkov** [comment]
>This secret method escapes into the error message when someone tries to derive(Eq) on something that isn't TotalEq. It was pretty hard to figure out what was wrong and I had to ask in #rust-internals before I managed to fix it.

The error message is improved in https://github.com/rust-lang/rust/pull/36384, but `assert_receiver_is_total_eq` still stays in place.

```
#[derive(PartialEq)]
struct NotEq;

#[derive(PartialEq, Eq)]
struct S {
	a: NotEq,
}
```
```
error[E0277]: the trait bound `NotEq: std::cmp::Eq` is not satisfied
 --> ../../test.rs:9:2
  |
9 |     a: NotEq,
  |     ^^^^^^^^ trait `NotEq: std::cmp::Eq` not satisfied
  |
  = note: required by `std::cmp::AssertParamIsEq`
```

**Comment by bluss** [comment]
The method is stable, but relatively well hidden. Is there anything that can be done about it, except removing it in "Rust 2"? It could be marked deprecated..

**Comment by Mark-Simulacrum** [comment]
Nominating for libs team discussion, perhaps we could just deprecate and eventually remove the method of it doesn't do anything? I doubt that anyone is using it in practice. Searching for it on GitHub leads me to believe that most matches are in copied versions of either libsyntax or libcore, which seems "hey, you're unstable anyway" to me.

**Comment by alexcrichton** [comment]
Discussed at libs traige and the decision was to close, we aren't going to remove these stable methods.
