### ISSUE TITLE
“Copy item path to clipboard” button gives wrong string for modules

### ISSUE THREAD

**Issue by steffahn** [rust-lang/rust#131021]
![Image](https://github.com/user-attachments/assets/97fb3c91-2f66-4a59-8bec-51655f59bbcd)

Compare e..g https://doc.rust-lang.org/1.81.0/std/boxed/index.html, where the button correctly produces `std::boxed` in the clipboard,
with https://doc.rust-lang.org/nightly/std/boxed/index.html, where it currently gives me `std::std::boxed` instead!

I would guess, this is a change that came with the redesign in #129545, though I haven’t checked to confirm that.

This only happen with modules; things like structs, macros, type synonyms… als seem to work correctly.

cc @GuillaumeGomez, @notriddle

@rustbot label +T-rustdoc +T-rustdoc-frontend +A-rustdoc-ui

**Comment by clubby789** [comment]
```js
        const path = [];
        onEachLazy(document.querySelectorAll(".rustdoc-breadcrumbs a"), a => {
            path.push(a.textContent);
        });
        path.push(document.querySelector("title").textContent.split(" ")[0]);
```
Most pages have the title `<Item> in path::to::module` - but modules don't have this, so the title of the page is just appended to `std`.
@rustbot claim
