### ISSUE TITLE
Nightly docs stable since versions are off

### ISSUE THREAD

**Issue by Alexendoo** [rust-lang/rust#131020]
![Image](https://github.com/user-attachments/assets/5d4e0442-4b2c-490b-88ec-5f10a2385b6b)

https://doc.rust-lang.org/nightly/std/boxed/struct.Box.html

![Image](https://github.com/user-attachments/assets/8e96690e-78c3-4539-952f-750ddf942171)

https://doc.rust-lang.org/nightly/std/option/enum.Option.html

**Comment by Urgau** [comment]
https://github.com/rust-lang/rust/pull/130798 maybe be relevant as is touches the displayed stability. (cc @lukas-code)
