### ISSUE TITLE
llvm-config sometimes doesn't provide the correct include directory

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#1311]
llvm-config --cxxflags looks like this for me:

```
-I/home/banderson/Dev/rust/src/llvm/include -I/home/banderson/Dev/rust/build/llvm/x86_64-unknown-linux-gnu/include  -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3 -fomit-frame-pointer -fno-exceptions -fno-rtti -fPIC -Woverloaded-virtual -Wcast-qual
```

Critically, our build depends on that first include directory, under the source tree, for rustllvm. In some environments llvm-config doesn't give us that information, probably because it isn't realizing that it's being run out of the build directory.

**Comment by steveklabnik** [comment]
Triage: same as what @reem said.

**Comment by steveklabnik** [comment]
Over a year later, my triage estimate is the same as it was last year.

**Comment by arielb1** [comment]
triage: ?

**Comment by kyrias** [comment]
Does anyone have a short example for reproducing this?

**Comment by joelgallant** [comment]
> There's a hack in mk/rustllvm.mk that adds it manually on windows. should be removed when we figure this out.

@brson with the makefiles gone, is this still an issue or should this be looked into?

**Comment by alexcrichton** [comment]
Indeed I think this is no longer relevant!
