### ISSUE TITLE
Types implementing Deref{,Mut} shouldn't have any other methods or public fields

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#13126]
For example, `sync::RwLockWriteGuard` implements `Deref` and `DerefMut`, implements the `downgrade` method, and has a public `cond` field. Since Rust doesn't have distinct `.` and `->` operators, this makes for an API that can be confusing and ambiguous.

Adding an extra layer of indirection seems like a reasonable solution. It feels a bit strange to call methods of the wrapped type on an RAII lock guard anyways:

```rust
let locked_foo: RwLock<Foo> = ...;
let mut guard = locked_foo.write();
while !guard.get().is_foo() {
    guard.cond.wait();
}
```

**Comment by bluss** [comment]
@alexcrichton is shifting the convention to static methods. I think it seems like a great idea.

Also, practice has been that some essential methods (comparison, clone etc) are shadowed by the smart pointer, while more specialized methods are not. (For example `try_unwrap` for Rc).

**Comment by huonw** [comment]
I think this is now as done (enough?) in the standard library, and is probably not really actionable anyway, due to stability. Closing.

(Don't miss https://github.com/rust-lang/rfcs/issues/279 either.)
