### ISSUE TITLE
unreachable_patterns emmitted despite the enum being tagged as non_exhaustive

### ISSUE THREAD

**Issue by lolbinarycat** [rust-lang/rust#131217]
### Code

```
#[non_exhaustive]
enum En {
    Um,
}

fn main() {
    match En::Um {
        En::Um => {},
        _ => {},
    }
}
```

### Current output

   Compiling playground v0.0.1 (/playground)
warning: unreachable pattern
 --> src/main.rs:9:9
  |
9 |         _ => {},
  |         ^
  |
  = note: `#[warn(unreachable_patterns)]` on by default

warning: `playground` (bin "playground") generated 1 warning
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.58s
     Running `target/debug/playground`

### Desired output

    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.58s
     Running `target/debug/playground`

### Rust Version

rustc 1.83.0-nightly (2bd1e894e 2024-09-26)
binary: rustc
commit-hash: 2bd1e894efde3b6be857ad345914a3b1cea51def
commit-date: 2024-09-26
host: x86_64-unknown-linux-gnu
release: 1.83.0-nightly
LLVM version: 19.1.0

**Comment by fmease** [comment]
Works as intended,`#[non_exhaustive]` only takes effect in downstream crates, not in the local crate.
