### ISSUE TITLE
Regression in rustdoc output

### ISSUE THREAD

**Issue by joshlf** [rust-lang/rust#131223]
I tried this code: https://github.com/google/zerocopy/tree/52e91319e144bf91a86b688b770d5d4e3735d9d4

I ran the following commands:

```shell
$ cargo +nightly-2024-10-01 doc
$ cargo +nightly-2024-10-02 doc
```

<details>
<summary>On 2024-10-01, this renders like this</summary>

![Image](https://github.com/user-attachments/assets/33adc63e-76b3-4370-8735-71d3b869d73f)

</details>

<details>
<summary>On 2024-10-02, this renders like this</summary>

![Image](https://github.com/user-attachments/assets/e3770f3f-f715-4573-a398-1cfcb362cd3d)

</details>

Note that the bullet points are spaced farther apart. I'm assuming this is a regression?

**Comment by jieyouxu** [comment]
> Note that the bullet points are spaced farther apart. I'm assuming this is a regression?
 
I think this is a consequence of #130933 which was intended to address #130622. GG is adding a UI regression test for the spacing in #131209 for #130622.

**Comment by GuillaumeGomez** [comment]
It's indeed something that we changed on purpose.

**Comment by GuillaumeGomez** [comment]
Little modification: the changes are improving the situation but introducing some new other issues. Talking about it currently to figure out what's the best solution.

**Comment by GuillaumeGomez** [comment]
I opened https://github.com/rust-lang/rust/pull/131257. Please don't hesitate to take a look. Hopefully I was able to improve the current situation without going back to the original issue.

**Comment by joshlf** [comment]
> I opened https://github.com/rust-lang/rust/pull/131257. Please don't hesitate to take a look. Hopefully I was able to improve the current situation without going back to the original issue.

Certainly seems better than before!
