### ISSUE TITLE
RPL example 3,5 generates bad code.

### ISSUE THREAD

**Issue by bkingboz** [rust-lang/rust#131350]
I tried this code:

``fn main() {
    for number in (1..4).rev() {
        println!("{number}!");
    }
    println!("LIFTOFF!!!");
}
3!
2!
1!
LIFTOFF!!!
```

I expected to see this happen: *explanation*

4!
3!
2!
1!
LIFTOFF!!!
Instead, this happened: Starts at 3 instead of 4.

### Meta
<!--
If you're using the stable version of the compiler, you should also check if the
bug also exists in the beta or nightly versions.
-->

`rustc --version --verbose`:
```
rustc --version
rustc 1.81.0 (eeb90cda1 2024-09-04)
binary: rustc
commit-hash: eeb90cda1969383f56a2637cbd3037bdf598841c
commit-date: 2024-09-04
host: x86_64-pc-windows-msvc
release: 1.81.0
LLVM version: 18.1.7

```

<!--
Include a backtrace in the code block by setting `RUST_BACKTRACE=1` in your
environment. E.g. `RUST_BACKTRACE=1 cargo build`.
-->
<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by Urgau** [comment]
This is expected, `1..4` is not a inclusive range, for that you would need to use `1..=4`.

See the [Range expressions](https://doc.rust-lang.org/stable/reference/expressions/range-expr.html#range-expressions) chapter on the Rust Reference for more details.

Closing as working as expected.

**Comment by bkingboz** [comment]
Thanks for the quick response!
