### ISSUE TITLE
`copy_nonoverlapping` panics on zero-sized NULL ptr copy

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#131371]
We somewhat recently declared `copy_nonoverlapping` to be legal on a NULL pointer. However, the debug assertions still reject this:

https://github.com/rust-lang/rust/blob/7caad6925314911eefe54b040d4bc5be940e8f92/library/core/src/intrinsics.rs#L3315-L3317

Other, related functions have similar problems.

Cc @saethlin

**Comment by saethlin** [comment]
We have a very incomplete test suite for these checks here: https://github.com/rust-lang/rust/tree/master/tests/ui/precondition-checks

We should probably have been adding tests for every errant way to call these.

**Comment by saethlin** [comment]
Started working on an implementation here: https://github.com/rust-lang/rust/pull/131384
