### ISSUE TITLE
Running `./x test mir-opt` rebuilds std every time

### ISSUE THREAD

**Issue by Zalathar** [rust-lang/rust#131437]
Using `profile = compiler`, running `./x test mir-opt` causes bootstrap to rebuild all of std before running the tests, even when the build cache ought to be warm from a previous `./x test mir-opt`.

Needless to say, this is not very fun when actually trying to run one or more mir-opt tests.

**Comment by Zalathar** [comment]
cc @jieyouxu

**Comment by Zalathar** [comment]
I will note that `--keep-stage-std=1` does seem to avoid the rebuild when re-running the tests.

**Comment by ChrisDenton** [comment]
Is there some way for CI to error on spurious rebuilds? I don't know what that would look like but this has happened in a few different places for different reasons so it'd be nice if there were some way to catch it early.

**Comment by jieyouxu** [comment]
Usually the spurious rebuilds happen if you try to run the same command, twice. I don't think that's very tractable for CI, but am happy to be proven wrong.

**Comment by onur-ozkan** [comment]
One mechanism for that would be to keep the rustflags logic in a single sealed module, so they can't be set externally from the individual build steps, which means they can't invalidate the build cache. Next to that approach we can add test coverage to rustflags logic.

**Comment by jieyouxu** [comment]
I opened a short-term immediate fix in https://github.com/rust-lang/rust/pull/131442, but the long term solution to prevent resurrgence of `RUSTFLAGS`-induced invalidation is a proper prevention mechanism as described above.

**Comment by jieyouxu** [comment]
Also this one actually rebuilds std *twice* if host == target (i.e. not cross-compile) because std was `ensure`'d twice with differing `RUSTFLAGS`. The double std build was the dead giveaway that fortunately makes it very easy to tell what the rebuild was caused by.
