### ISSUE TITLE
Add lint for & -> &mut transmutes

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#13146]
Doing a `&T` to `&mut T` transmute is now undefined behaviour (it needs to use the `Unsafe` type), and so there could be a lint for it.

Unfortunately, such a lint is likely to miss many such casts, but it will theoretically catch common cases like `transmute::<&Foo, &mut Foo>(self) `.

**Comment by steveklabnik** [comment]
Triage: nothing has changed, these transmutes still silently work:

```
use std::mem;

fn main() {
    let x = 5;

    let y = &x;

    let z = unsafe { mem::transmute::<&i32, &mut i32>(y) };
}
```
