### ISSUE TITLE
path attribute is silently accepted and ignored for inline mod items.

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#13156]
Consider the following program `p.rs`:

``` rust
#[path="q.rs"] mod q {
    pub fn q_main() { println!("Hello World"); }
}

fn main() { q::q_main() }
```

I don't know if this is considered a bug or a feature, but we should probably emit a warning when we encounter that useless `path` attribute attached to `q` above.

**Comment by gkoz** [comment]
Doesn't seem useless to me. The [reference](https://doc.rust-lang.org/reference.html#modules) gives this seemingly reasonable example:

> The directories and files used for loading external file modules can be influenced with the path attribute.

>```
#[path = "thread_files"]
mod thread {
    // Load the `local_data` module from `thread_files/tls.rs`
    #[path = "tls.rs"]
    mod local_data;
}
```

Now suppose you're in a build script and want to include `src/tls.rs`. Is there a better way than

```
// This module hides some optional stuff
#[cfg(foo_bar)]
#[path = ""]
mod thread {
    #[path = "src/tls.rs"]
    mod local_data;
}
```

**Comment by Mark-Simulacrum** [comment]
Yeah, to my knowledge this is expected and intentional behavior; closing.
