### ISSUE TITLE
crate name is too small

### ISSUE THREAD

**Issue by Sherlock-Holo** [rust-lang/rust#131589]
for example: 

when read https://docs.rs/futures/latest/futures/

![Image](https://github.com/user-attachments/assets/22e74ef9-1c74-46a0-acbc-9f9d89836a86)

the crate name size is big, as the crate **name**, this size is ok to hint people "the crate name is XXX"

however, when enter a module sub page, the crate name become too small

https://docs.rs/futures/latest/futures/future/index.html

![Image](https://github.com/user-attachments/assets/965d952f-fe2c-4552-950d-3988b43d38ef)

it is too small, even make me wonder if my browser is broken to render the website, so I change to firefox, but nothing changed

also we can see the up spacing is shorter than the lower spacing, tha't so strange

![Image](https://github.com/user-attachments/assets/0de48093-4515-4376-a4f0-d6f97f9717b9)

and the **source** up spacing is short, but the lower spacing is too long, even three times the length

![Image](https://github.com/user-attachments/assets/d142d198-d6e0-46d2-98b7-77d450b8ef8c)

**Comment by GuillaumeGomez** [comment]
cc @rust-lang/rustdoc-frontend
