### ISSUE TITLE
Implement a lock-free hashmap

### ISSUE THREAD

**Issue by derekchiang** [rust-lang/rust#13166]
It'd be nice to have a lock-free hashmap in the `collections` crate.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#659
