### ISSUE TITLE
Growable, bounded by `weight` channels

### ISSUE THREAD

**Issue by carllerche** [rust-lang/rust#13172]
A really useful feature would be to have a channel that was bounded by something other than message count. For example, if I am sending byte arrays through a channel, a much more interesting thing to bound on would be the size of the buffers in the queue. Many more 4 byte arrays could be queued up than 1MB arrays.

This could be implemented by having a WeightedMsg trait (or something similar) that allows specifying the (approximate) weight of a message. The default impl could just return a constant value (probably 1).

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#717
