### ISSUE TITLE
rustdoc: Impl block docs are indented more than the child items, so they appear to not apply to the whole block

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#131704]
This screenshot from #130612 exemplifies the issue:

![Image](https://github.com/user-attachments/assets/258ab38a-da9d-497e-8170-804cf442f1cc)

cc @GuillaumeGomez 
cc https://rust-lang.zulipchat.com/#narrow/stream/393423-t-rustdoc.2Fmeetings/topic/2024-10-14/near/476842302

**Comment by GuillaumeGomez** [comment]
Thanks! Gonna take a look at it tomorrow.

**Comment by GuillaumeGomez** [comment]
It's indeed a bit weird that impl items have the same left margin level as their parent. Thanks for pointing it out!
