### ISSUE TITLE
(Hosting request) Create a Radicle backup and mirror to protect your development

### ISSUE THREAD

**Issue by hardBSDk** [rust-lang/rust#131791]
[Radicle](https://radicle.xyz/) is a platform for peer-to-peer Git repositories, your repository works like a torrent where anyone can be a seeder of your code.

This will increase the download speed, add a backup and protect the project from GitHub problems.

**Comment by Noratrieb** [comment]
We don't have a need for backups like this, and we have close ties with GitHub that should ensure that operations can continue as usual. Even if that's not the case, we will be fine without Radicle. You're of course free to host your own mirrors of the repository, but I don't think Rust should host an official Radicle mirror, which looks like extra effort for the Infrastructure team to maintain and secure.
