### ISSUE TITLE
`wasm-component-ld` is installed into `*-pc-windows-gnu{,llvm}` sysroot even when it's disabled in config

### ISSUE THREAD

**Issue by ognevny** [rust-lang/rust#131773]
the config enables these tools
```TOML
tools = [
  "cargo",
  "clippy",
  "rustdoc",
  "rustfmt",
  "rust-analyzer-proc-macro-srv",
  "analysis",
  "src",
]
```
but `wasm-component-ld` is built anyway and (starting with 1.82.0) installed into target's sysroot even when there is such tool in $PATH available. `lld = false` is set explicitly

**Comment by ognevny** [comment]
update: I encountered it in https://github.com/msys2/MINGW-packages/pull/22205

**Comment by jieyouxu** [comment]
cc @onur-ozkan I think you worked on unifying llvm-tools logic, do you know if this is intentional?

**Comment by ognevny** [comment]
turns out #130034 fixed it. thanks Alex!
