### ISSUE TITLE
serve the rust-lang.org domain over https

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#13180]
I don't think there's really any need to have http for the site at all. Any non-TLS location is a chance for an attacker to send users to a malicious download.

**Comment by gsingh93** [comment]
It looks really bad when I see a big project like this that still hasn't gotten HTTPS on their website. What exactly is blocking this? It shouldn't be hard to do. If the current hosting can't provide it, it should be changed.

**Comment by frewsxcv** [comment]
Related issue: Related issue: https://github.com/rust-lang/rust/issues/13180

**Comment by DomT4** [comment]
> Related issue: #13180

#17914, presumably? :)

**Comment by frewsxcv** [comment]
Yes, thanks :)

**Comment by brson** [comment]
To do this we need to frob the nginx config to redirect www.rust-lang.org to GitHub pages, then update the DNS to point to the nginx server.

**Comment by sigmavirus24** [comment]
It'd also be pretty great if Rust became the third language in the "Good" category on https://httpswatch.com/programming#programming-languages

**Comment by gsingh93** [comment]
I don't want this to come off as aggressive, but I'm genuinely wondering why this is taking so long? This shouldn't take more than 20 minutes to set up. Setting up a MITM attack to change the download links to malicious links is trivial, not to mention not having HTTPS is just plain unprofessional.

**Comment by brson** [comment]
@gsingh93 It's taking a long time because it's not considered a high priority. @edunham has it on her todo list and I expect she'll complete it soon.

**Comment by edunham** [comment]
Status: https://www.rust-lang.org/ fixes the original issue of this ticket. http://rust-lang.org redirects to https://www.rust-lang.org. https://github.com/rust-lang/rust-www/issues/165 will handle the issues raised in the ensuing discussion.

At least we're up to "mediocre" on https://httpswatch.com/programming#programming-languages :unamused:

**Comment by gsingh93** [comment]
Yay! Nice work!

(This issue should probably be closed now.)

**Comment by tanriol** [comment]
The github's certificate is still in use for https://blog.rust-lang.org (rust-lang/blog.rust-lang.org#81).
