### ISSUE TITLE
target arm64e-apple-darwin removing functions

### ISSUE THREAD

**Issue by ds-ep** [rust-lang/rust#131811]
I tried this code:

```rust
use ctor::ctor;

#[ctor]
fn testAAAA() {
    println!("TEST123");
    panic!();
}

pub fn test123() {
    println!("TEST123");
}
```

I expected to see this happen: 
without specifying a target everything works fine (using `cargo +nightly build`)

Instead, this happened:
when i specify arm64e-apple-darwin (using: `cargo +nightly build -Z build-std --target arm64e-apple-darwin`) my function seems to be removed.

 compiling both as dylib

### Meta

`rustc --version --verbose`:
```rustc 1.81.0 (eeb90cda1 2024-09-04)
binary: rustc
commit-hash: eeb90cda1969383f56a2637cbd3037bdf598841c
commit-date: 2024-09-04
host: aarch64-apple-darwin
release: 1.81.0
LLVM version: 18.1.7
```

From aarch64-apple-darwin build in ghidra
![Image](https://github.com/user-attachments/assets/ac84ad01-dc8c-4df4-89d7-ac5fb81afe00)
whereas on the arm64e build there is no functions at all :|
![Image](https://github.com/user-attachments/assets/0cfb5ffa-9cee-4b65-a9f0-c18fe2c6bad9)

CC @arttet

**Comment by bjorn3** [comment]
This is probably https://github.com/rust-lang/rust/issues/130085. You can try linking using lld or downgrading to XCode 14 or lower. The issue I think this is only happens with the linker of XCode 15.

**Comment by ds-ep** [comment]
@bjorn3 I have xcode 16 btw, issue still exists. I tried using lld but then the output is arm64 not arm64e, and as far as im aware lld does not support arg `-arch arm64e` yet

**Comment by bjorn3** [comment]
I think your options for now are limited to downgrading to XCode 14 or trying to compile rustc against Apple's LLVM fork (https://github.com/swiftlang/llvm-project). XCode 14 should be compatible with the arm64e abi in upstream LLVM, and using Apple's LLVM fork should make rustc able to emit the new arm64e abi.

**Comment by arttet** [comment]
Hey @ds-ep,

I believe this is connected to the [issue](https://github.com/llvm/llvm-project/issues/80200).

```sh
$ clang --version
Homebrew clang version 19.1.2
Target: x86_64-apple-darwin24.0.0
Thread model: posix
InstalledDir: /usr/local/Cellar/llvm/19.1.2/bin
```

```sh
$ echo "int main() { return 0; }" > foo.c
$ clang -o llvm_foo.o -c foo.c --target=arm64e-apple-darwin
$ clang -o llvm_foo llvm_foo.o --target=arm64e-apple-darwin -fuse-ld=lld
$ file llvm_foo
llvm_foo: Mach-O 64-bit executable arm64
```

So, there are significant differences between Apple's `LLVM` and the upstream `LLVM`.

**Comment by arttet** [comment]
This is also the known [issue](https://github.com/llvm/llvm-project/issues/79543). We have to force using `XCode` 14. It seems that Apple's LLVM is not compatible with `Rust` and requires many patches.

**Comment by ds-ep** [comment]
For anyone coming across this on MacOS 15 where Xcode 14 is not compatible and will refuse to install. you can download CL tools for xcode 14 here: https://developer.apple.com/download/all/ and use that.
