### ISSUE TITLE
Bootstrap feature request: set `--jobs` in config.toml

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#131836]
To reduce RAM usage I'd like bootstrap to use fewer than all of my cores. (Many of them are efficiency cores so it's unclear that it's really so beneficial to use them all.) But currently I'd have to set `-j` on every single bootstrap invocation, which is not great. Would be nice if this could be set in the config file, like most other options can.

**Comment by jieyouxu** [comment]
#131838
