### ISSUE TITLE
rustdoc: recursive footnote not rendered correctly

### ISSUE THREAD

**Issue by Noratrieb** [rust-lang/rust#131946]
`rustdoc footnote-hell.md`

```md
# footnote-hell

Hello [^a].

[^a]: meow [^b]
[^b]: uwu [^a]

```

I expected to see this happen: all the links are correct, the backlinks are at least not completely wrong

Instead, this happened: a mess

![Image](https://github.com/user-attachments/assets/06a6d84d-1adf-4fa5-abe8-505ddbfecb20)

- The first 1 points to `#fn1`
- The second 1 points to `#b`
- The third 1 points to `#a`

The backlinks are `#fnref1` and `#fnref2` respectively, which seems correct.

### Meta

`rustc --version --verbose`:
```
rustdoc 1.84.0-nightly (3ed6e3cc6 2024-10-17)
```

**Comment by GuillaumeGomez** [comment]
That was a funny case. So the fix is simple: we need to check for footnote references in footnote definitions. I have a fix ready, sending the patch once I added tests.
