### ISSUE TITLE
Allow pointers in inline assembly `const` expressions

### ISSUE THREAD

**Issue by dingxiangfei2009** [rust-lang/rust#132012]
Quoting from `tests/ui/asm/const-refs-to-static.rs` @ 31e102c509192189be841954f38962eb3cd9e2e2

I tried this code:

```rust
use std::arch::{asm, global_asm};
use std::ptr::addr_of;

static FOO: u8 = 42;

#[no_mangle]
fn inline() {
    unsafe { asm!("{}", const addr_of!(FOO)) };
}
```

I expected to see this happen: it should compiles

Instead, this happened: `*const u8` is not allowed as an operand to inline assembly.

This would be coming useful and brings us feature-parity with `asm(" /* assembly */ " ::"i"(ptr))` from C, where `ptr` can be pointer to statics and constants.

cc @Amanieu @nbdd0121 

### Meta

`rustc --version --verbose`:
```
<version>
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by dingxiangfei2009** [comment]
I am trying a quick implementation on it.

@rustbot  claim

**Comment by dingxiangfei2009** [comment]
Thanks for pointing that out @nbdd0121 !  Is there a tracking issue for the string interpolating constraint in `asm!`? If not yet, I can create it.

**Comment by tgross35** [comment]
(adjusted the title since there isn't anything RFL-specific here)

**Comment by tgross35** [comment]
Ah - actually since https://github.com/rust-lang/rust/issues/128464 already tracks poointers in asm `const`, I think this issue can just be closed. Feel free to reopen if that isn't accurate.

> Thanks for pointing that out [@nbdd0121](https://github.com/nbdd0121) ! Is there a tracking issue for the string interpolating constraint in `asm!`? If not yet, I can create it.

I think it would be good to create this, I haven't seen one around.
