### ISSUE TITLE
Decide whether blocks inside `asm` goto should default to safe

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rust#132078]
`asm` goto requires labeled blocks, like `asm!("...", foo = label { code() });`.

We need to decide whether those labeled blocks are safe by default or whether they require explicitly writing `safe` or `unsafe`. I'm filing this issue for T-lang to decide which of those we want to go with.

Based on discussion with the Rust for Linux folks, I'm going to propose that these blocks should default to safe, and require an explicit `unsafe` if you want them to be unsafe.

I'm also going to propose that you shouldn't need nested braces if you want unsafe here: `label unsafe { dangerous_code() }` should work, rather than having to write `label { unsafe { dangerous_code() } }`.

**Comment by joshtriplett** [comment]
@rfcbot merge

**Comment by tmandry** [comment]
I don't have a strong preference on defaulting to safe vs making you pick safe vs unsafe. If we add safe blocks later in an upcoming edition we can always require explicitness in the same edition.

I like the idea of avoiding an extra set of braces.

@rfcbot reviewed

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

This makes sense to me.

The ability to have safe blocks makes sense for folks building control-flow abstractions on top of inline-assembly. I am indifferent about whether or not it is the default, but if there is to be a default, I prefer safe ("fails open", as Josh said).

**Comment by traviscross** [comment]
@rfcbot reviewed

**Comment by traviscross** [comment]
cc @Darksonn @ojeda @Amanieu

...on this now completed FCP.

**Comment by nbdd0121** [comment]
Implementation merged: #131544
