### ISSUE TITLE
LLVM 20 produces different assembly for rust/tests/assembly/riscv-soft-abi-with-float-features.rs

### ISSUE THREAD

**Issue by krasimirgg** [rust-lang/rust#132139]
After https://github.com/rust-lang/rust/pull/131807, we're seeing some test failures in our experimental rust + LLVM-at-HEAD build bot:

* https://buildkite.com/llvm-project/rust-llvm-integrate-prototype/builds/32097#0192c31f-15a1-47c2-a4c2-a946d7b089a2/951-952

It seems that here the new assembly is just `lw a0, 0(a0)`; not sure if that's OK.

https://github.com/rust-lang/rust/blob/97ae1df8aa9fa6dfd29dced18b232d25208c4111/tests/assembly/riscv-soft-abi-with-float-features.rs#L34

**Comment by jieyouxu** [comment]
cc @beetrees @workingjubilee as you may know more about the intended behavior

**Comment by hanna-kruppe** [comment]
The change seems correct to me. It loads from the same location as before and puts the same bits in return register. Both variants just load 32 bits from memory into the low half of a0 (all of the involved instructions preserve non-canonical NaNs) and sign-extend to fill the upper 32 bits of a0 (previously in the `fmv.x.w` step, now it’s part of the “integer” load `lw`).
