### ISSUE TITLE
Crater run with -Zrandomize-layout

### ISSUE THREAD

**Issue by saethlin** [rust-lang/rust#132292]

**Comment by saethlin** [comment]
@craterbot run mode=build-and-test start=stable end=stable+rustflags=-Zrandomize-layout

**Comment by jieyouxu** [comment]
@saethlin will craterbot choke on the missing space in `end=stable+rustflags=-Zrandomize-layout`?

**Comment by Noratrieb** [comment]
does crater make unstable flags on stable work?

**Comment by saethlin** [comment]
I bet no
@craterbot abort

**Comment by saethlin** [comment]
@craterbot run name=randomize-layout mode=build-and-test start=nightly-2024-10-28 end=nightly-2024-10-28+rustflags=-Zrandomize-layout

**Comment by saethlin** [comment]
@craterbot run name=randomize-layout-1 mode=build-and-test start=nightly-2024-10-28 end=nightly-2024-10-28+rustflags=-Zrandomize-layout crates=https://crater-reports.s3.amazonaws.com/randomize-layout/retry-regressed-list.txt

**Comment by saethlin** [comment]
Experiment completed.

**Comment by saethlin** [comment]
Yep! The first task would be to filter out all the size assertions.

**Comment by the8472** [comment]
Some post reminded me that Foo<T> and Foo<U> currently use the same seed, so we're not even randomizing hard enough yet. I'll look into whether that can be fixed.

**Comment by the8472** [comment]
That should be fairly easy with the current logic, but the enum caveat is a pretty big one because it'd be more like a "but-mostly-not-much-bigger" 😅

**Comment by the8472** [comment]
PR for more randomization #133088

**Comment by the8472** [comment]
That PR has landed, might be worth another run.

**Comment by saethlin** [comment]
@craterbot run name=randomize-layout-2 mode=build-and-test start=nightly-2025-01-18 end=nightly-2025-01-18+rustflags=-Zrandomize-layout

**Comment by saethlin** [comment]
@craterbot run name=randomize-layout-3 mode=build-and-test start=nightly-2025-01-18 end=nightly-2025-01-18+rustflags=-Zrandomize-layout crates=https://crater-reports.s3.amazonaws.com/randomize-layout-2/retry-regressed-list.txt

**Comment by saethlin** [comment]
At a glance, numbers look the same as https://github.com/rust-lang/rust/issues/132292#issuecomment-2466088350 within noise.

**Comment by saethlin** [comment]
No. `randomize-layout-2` is a fresh run, and `randomize-layout-3` is a re-run of the recent regressions list.

Crater spuriously reports a lot of improvements and regressions, so unless you want to fish through all of its results by hand, re-running the regressions from a run is the only way to get a small report.
