### ISSUE TITLE
'make dist' doesn't work correctly on mac

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#13224]
We use the `--exclude-vcs` flag to `tar`, which doesn't exist on Mac. I'm temorarily going to change the `dist` target to not produce tarballs on Mac to work around the problem on our nightly builders.

**Comment by steveklabnik** [comment]
triage: i don't own a mac either. @brson is this part of rust-installer now?

**Comment by frewsxcv** [comment]
I can confirm that the conditional added in d2686c7 still exists currently:

https://github.com/brson/rust/blob/1d00c545ede609b9d43fdf9f252c15da5a66dac7/mk/dist.mk#L256-L261

Considering all `--exclude-vcs` does is ignore version control related software, one potential fix for this would be to use `--exclude .git --exclude .gitmodules --exclude .gitignore` which AFAIK works with both BSD and GNU tar

**Comment by BigBoneDaddy** [comment]
@frewsxcv I like your work around

**Comment by steveklabnik** [comment]
Triage: still there today https://github.com/rust-lang/rust/blob/8f62c2920077eb5cb81323142fc5dbe6ae8813c0/mk/dist.mk#L352-L357

**Comment by alexcrichton** [comment]
Make's now gone, so closing.

(fixed in rustbulid)
