### ISSUE TITLE
regression: change in paths/CWD for rustdoc tests

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#132203]
* https://crater-reports.s3.amazonaws.com/beta-1.83-3/beta-2024-10-19/reg/better_embedded-0.4.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.83-3/beta-2024-10-19/reg/code-path-0.3.2/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.83-3/beta-2024-10-19/reg/gis_puller-0.1.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.83-3/beta-2024-10-19/reg/haproxy-config-0.4.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.83-3/beta-2024-10-19/reg/itf-0.2.4/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.83-3/beta-2024-10-19/reg/minipng-0.1.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.83-3/beta-2024-10-19/reg/stackdriver_logger-0.8.2/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.83-3/beta-2024-10-19/reg/text-to-png-0.2.0/log.txt

**Comment by ehuss** [comment]
This seems to have changed via #130582 (cc @notriddle). Reproduction:

`src/lib.rs`:
```
#![doc = include_str!("../README.md")]
```

`README.md`:
~~~
```rust
let x = include_bytes!("../examples/foo");
```
~~~

`examples/foo`: empty file

**Comment by apiraino** [comment]
Ok, removing the prioritization label as it is in `T-rustdoc` territory and it is being already nicely handled.

@rustbot label -I-prioritize

**Comment by MarijnS95** [comment]
Should this have https://github.com/rust-lang/rust/labels/regression-from-stable-to-stable, given that this regression trickled into the 1.83 release (#133824)? Or is that not added retroactively for closed issues?
