### ISSUE TITLE
regression: doctest no longer supports derive?

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#132204]
* https://crater-reports.s3.amazonaws.com/beta-1.83-3/beta-2024-10-19/reg/structdoc-0.1.4/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.83-3/beta-2024-10-19/reg/uwc-1.0.8/log.txt

**Comment by Urgau** [comment]
> - https://crater-reports.s3.amazonaws.com/beta-1.83-3/beta-2024-10-19/reg/structdoc-0.1.4/log.txt

This is expected, the (kind-of new) warn-by-default `non_local_definitions` lint is rightfully triggered here, the derive should put it's things under an unnamed const. However the crate also use `#![deny(warnings)]` so it unfortunately breaks, nothing we can do about that.

The lint is already in the language section of relnotes.

> - https://crater-reports.s3.amazonaws.com/beta-1.83-3/beta-2024-10-19/reg/uwc-1.0.8/log.txt

Different issue, looks like an issue with the arguments passed to the doctest executable. Reminds me of https://github.com/rust-lang/rust/pull/131095.

**Comment by Mark-Simulacrum** [comment]
Is this serde's derive? Has that already been fixed on newer versions of serde?

**Comment by saethlin** [comment]
> Is this serde's derive? Has that already been fixed on newer versions of serde?

Yes and yes. The crate that's failing here is locked to serde 1.0.99 which was released in 2019, and it expands to this:
```
const _IMPL_DESERIALIZE_FOR_Point: () = {
    #[allow(unknown_lints)]
    #[allow(rust_2018_idioms)]
    extern crate serde as _serde;
    #[automatically_derived]
    impl<'de> _serde::Deserialize<'de> for Point {
```
Starting in serde 1.0.113 (released in 2020) the Derive macro expands to an unnamed const:
```
const _: () = {
    #[allow(rust_2018_idioms, clippy::useless_attribute)]
    extern crate serde as _serde;
    #[automatically_derived]
    impl<'de> _serde::Deserialize<'de> for Point {
```

Since the fix has been out for 4 years and has been a `cargo update` away the whole time, I don't think there's any action needed here.

**Comment by saethlin** [comment]
If someone wants an MCVE:
```rust
#[derive(serde::Deserialize)]
struct Point {}
```
```toml
[package]
name = "scratch"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "=1.0.200", features = ["derive"] }
```

**Comment by apiraino** [comment]
Visiting this issue again. By reading the previous [comment](https://github.com/rust-lang/rust/issues/132204#issuecomment-2439846335) I think we can close this as "not as issue / accepted change".

(thanks for the triaging)
