### ISSUE TITLE
regression: attribute should be applied to struct/enum/union

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#132201]
* https://crater-reports.s3.amazonaws.com/beta-1.83-3/beta-2024-10-19/reg/list_tools-0.1.9-features/log.txt

Likely needs compat-notes, please tag relnotes if so.

**Comment by fmease** [comment]
Expected and accepted regression. See PR #129422 which is already tagged with *relnotes*.
Furthermore, [here](https://github.com/rust-lang/rust/pull/129422#issuecomment-2329252150) I already pinged the author of this crate (the code isn't hosted on GH, therefore we couldn't open a PR).
Lastly, we already have a *relnotes-tracking-issue* here: ##129576 

Closing in favor of #129958.
