### ISSUE TITLE
Addressing a Share `static mut` should be safe

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#13232]
We talked about this at the [most recent workweek](https://github.com/rust-lang/meeting-minutes/blob/master/Meeting-workweek-2014-03-03.md#staticconst), but I believe this code should compile as-is:

```rust
use std::sync::atomics;

static mut CNT: atomics::AtomicUint = atomics::INIT_ATOMIC_UINT;

fn main() {
    CNT.fetch_add(1, atomics::SeqCst);
}
```

Specifically, you should be allowed to take the address (`&`-pointer) of a `static mut`, and you should continue to need `unsafe` to take a `&mut`-pointer to a `static mut`.

**Comment by FlaPer87** [comment]
Bug fixed by 4c624865dd4c69f9f0ec8975c6225afd3094dfd4
