### ISSUE TITLE
Make "variable does not need to be mutable" fix machine applicable

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#132324]
### Code

```rs
fn foo() {
    let mut a = 0;
}
```

### Current output

```
warning: variable does not need to be mutable
 --> <anon>:2:9
  |
2 |     let mut a = 0;
  |         ----^
  |         |
  |         help: remove this `mut`
  |
  = note: `#[warn(unused_mut)]` on by default
```

### Desired output

Same except `cargo fix` can apply the suggested fix.

### Rationale and extra context

This makes it easier to cleanup machine generated code like that generated by c2rust.

### Rust Version

rustc 1.82.0 (f6e511eec 2024-10-15)
binary: rustc
commit-hash: f6e511eec7342f59a25f7c0534f1dbea00d01b14
commit-date: 2024-10-15
host: x86_64-unknown-linux-gnu
release: 1.82.0
LLVM version: 19.1.1

**Comment by jieyouxu** [comment]
E-easy for the easy cases (heh), but handling the macro cases and recursive patterns correctly (either skipping the suggestion in the intractable cases or handle a subset of cases) can get tricky.

**Comment by BLANKatGITHUB** [comment]
Can you please elaborate what to do or except here, first time contributing and want to try this issue.

**Comment by bjorn3** [comment]
The error is emitted at https://github.com/rust-lang/rust/blob/432972cae64d736b892e7a4c8b4fe7fe0e888904/compiler/rustc_borrowck/src/lib.rs#L397

Huh, according to https://github.com/rust-lang/rust/blob/432972cae64d736b892e7a4c8b4fe7fe0e888904/compiler/rustc_borrowck/src/session_diagnostics.rs#L53 the fix is already machine applicable, yet `cargo fix` didn't fix it for me.

**Comment by BLANKatGITHUB** [comment]
well I tried it on my machine and cargo fix fixed it for me.  I don't know maybe i did something wrong

**Comment by BLANKatGITHUB** [comment]
hey, I am sorry if you are busy, I was just curious about this issue .

**Comment by bjorn3** [comment]
Figured it out. `cargo fix` only applies fixes for workspace members that you explicitly specify to build, not those that are depended on by the workspace root (and thus do get their warnings shown). I had to do `cargo fix -p my_lib` for it to apply.
