### ISSUE TITLE
rustdoc: Why are this three buttons so much big?

### ISSUE THREAD

**Issue by liigo** [rust-lang/rust#132311]
# Why are this three buttons so much big?
![Image](https://github.com/user-attachments/assets/67d4b926-1167-4985-a59a-91ebb307e66e)
see https://doc.rust-lang.org/nightly/std/cell/struct.UnsafeCell.html

----

# I'm still prefer the old smaller ones:
![Image](https://github.com/user-attachments/assets/50a10748-d0cf-495f-820f-53c254c5003e)
see https://doc.rust-lang.org/stable/std/cell/struct.UnsafeCell.html

**Comment by Urgau** [comment]
cc #129545 @notriddle @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
The whole explanation is in #129545. Closing then.
