### ISSUE TITLE
Shorthand projections inside RPITITs fail to resolve

### ISSUE THREAD

**Issue by Vollbrecht** [rust-lang/rust#132372]
Recent rust nigthly version can't compile previously working code, duo to compiler not being able to find associated type inside a "async fn in trait" definition.

### Code

Compiling this code:
```rust
#![allow(async_fn_in_trait)]
pub trait foo {}

pub trait bar {
    type foo: foo;
}
pub trait baz {
    async fn boom<X: bar>() -> Result<(), X::foo>;
}
```
I expected to see this happen: In previous version up to `nightly-2024-10-28` this code compiled

Instead, this happened: It stoped compiling with the error 
```
error[E0220]: associated type `foo` not found for `X`
8 |     async fn boom<X: bar>() -> Result<(), X::foo>;
  |                                              ^^^ there is an associated type `foo` in the trait `bar`
```
### Version it worked on

`nightly-2024-10-28`

### Version with regression

`nightly-2024-10-29`

`rustc --version --verbose`:
```
rustc 1.84.0-nightly (1e4f10ba6 2024-10-29)
binary: rustc
commit-hash: 1e4f10ba6476e48a42a79b9f846a2d9366525b9e
commit-date: 2024-10-29
host: x86_64-unknown-linux-gnu
release: 1.84.0-nightly
LLVM version: 19.1.1
```

No, code just stops compiling. 

</p>
</details>

**Comment by Dirbaio** [comment]
minimized it a bit more: [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=dc56f5d6ee19f2657d121da16c66a098)

```rust
#![allow(async_fn_in_trait)]

pub trait Bar {
    type Foo;
}

pub trait Baz {
    async fn boom<X: Bar>() -> X::Foo;
}
```

**Comment by fmease** [comment]
cc @compiler-errors

**Comment by fmease** [comment]
Alt:

```rs
pub trait Bar {
    type Foo;
}

pub trait Baz {
    fn boom<X: Bar>() -> impl std::future::Future<Output = X::Foo>; //~ ERROR associated type `Foo` not found for `X`
}
```
