### ISSUE TITLE
compiletest: allow only running a test if we have a *specific* llvm major version

### ISSUE THREAD

**Issue by jieyouxu** [rust-lang/rust#132348]
`tests/codegen/try_question_mark_nop.rs` has a hack like

```
//@ revisions: NINETEEN TWENTY
//@[NINETEEN] min-llvm-version: 19
//@[NINETEEN] ignore-llvm-version: 20-99
//@[TWENTY] min-llvm-version: 20
```

we should allow the test writer to specify a `//@ only-llvm-major-version: 19` which will *only* run the test if the llvm's major version matches `19`. Instead of having to hack this by using `min-llvm-version` + `ignore-llvm-version`.

**Comment by jieyouxu** [comment]
Mentoring instructions:

- #132315 should make this easy to implement, should wait for that to reland or rebase on top of that.
- Pick a directive name, something like `only-llvm-major-version`
- Register `only-llvm-major-version` as a known directive in https://github.com/rust-lang/rust/blob/16422dbd8958179379214e8f43fdb73a06b2eada/src/tools/compiletest/src/directive-list.rs.
- Add a directive matcher in https://github.com/rust-lang/rust/blob/16422dbd8958179379214e8f43fdb73a06b2eada/src/tools/compiletest/src/header.rs#L1492. Check if their major versions match (available as `semver::Version` after ##132315).
- Add a test to check that test is correctly ignored when major versions match and ignored when they don't in https://github.com/rust-lang/rust/blob/16422dbd8958179379214e8f43fdb73a06b2eada/src/tools/compiletest/src/header/tests.rs.

**Comment by Eclips4** [comment]
> Pick a directive name, something like only-llvm-major-version

Unfortunately, we can't use `only-llvm-major-version` here, because it will be handled by the `cfg::handle_only`  instead of the `ignore_llvm`. What do you think about `exact-llvm-major-version`?

**Comment by jieyouxu** [comment]
That's fine.

**Comment by jieyouxu** [comment]
cc https://github.com/rust-lang/rustc-dev-guide/pull/2135
