### ISSUE TITLE
Proc-macro helper attributes on lifetime and const parameters fail to resolve if a built-in derive macro is present

### ISSUE THREAD

**Issue by PonasKovas** [rust-lang/rust#132561]
I was making a derive proc macro and stumbled upon this weird error, and was told on the rust discord that this might be a bug. Basically, I have a proc macro that uses a helper attribute like this:

```rust
#[proc_macro_derive(Test, attributes(test_helper))]
pub fn derive(input: TokenStream) -> TokenStream {
    ...
}
```

The `#[test_helper]` attribute is used on generics - including lifetime generics.

When I use it normally it works fine, but if I try to derive it together with another trait, such as `Clone` - it fails to compile, saying that `#[test_helper]` was not found in the scope.

```rust
#[derive(Test, Clone)]
struct MyStruct<#[test_helper] 'a> {
    inner: &'a (),
}
```

```rust
error: cannot find attribute `test_helper` in this scope
 --> src/lib.rs:3:19
  |
3 | struct MyStruct<#[test_helper] 'a> {
  |                   ^^^^^^^^^^^
```

There is no error if I put the attribute on a type generic or on a field.

`cargo expand`-ed code:

```rust
struct MyStruct<#[test_helper] 'a> {
    inner: &'a (),
}
#[automatically_derived]
impl<#[test_helper] 'a> ::core::clone::Clone for MyStruct<'a> {
    #[inline]
    fn clone(&self) -> MyStruct<'a> {
        MyStruct {
            inner: ::core::clone::Clone::clone(&self.inner),
        }
    }
}
```

[I have also made a minimal reproducible example.](https://github.com/PonasKovas/macro_helper_attribute_bug)

### Meta

`rustc --version --verbose`:
```
rustc 1.84.0-nightly (b3f75cc87 2024-11-02)
binary: rustc
commit-hash: b3f75cc872cfd306860c3ad76a239e719015f855
commit-date: 2024-11-02
host: x86_64-unknown-linux-gnu
release: 1.84.0-nightly
LLVM version: 19.1.3
```

If this is really a bug, I can try to investigate if anyone can help me and point me in the right direction.

**Comment by fmease** [comment]
Minimal:

`rustc a.rs --crate-type=proc-macro`:

```rs
extern crate proc_macro;

#[proc_macro_derive(M, attributes(x))] 
pub fn m(_: proc_macro::TokenStream) -> proc_macro::TokenStream { Default::default() }
```

`rustc b.rs --crate-type=lib --extern a -L. --edition=2021`:

```rs
#[derive(a::M, Clone)] struct S<#[x] 'a>(&'a ());
```

Not only affects lifetime parameters but also const parameters (`#[x]` won't be found on e.g. `const N: usize` either). It seems like the second derive macro (above: `Clone`) has to be a built-in macro. I could reproduce this issue with `Clone`, `PartialEq`, `Hash`, `std::marker::ConstParamTy` etc. (which are all built-in macros) but failed to reproduce with non-built-in ones (e.g., "`a::N`" (i.e., another macro from the same crate, no helpers declared), "`c::M`" (i.e., another macro from a different crate, no helpers declared)).

**Comment by PonasKovas** [comment]
It seems that the issue is that the built-in macros don't remove the attributes from lifetimes and const generics for some reason, when expanding their implementations, while they do for normal type generics.

Sounds like this should be pretty easy to fix, and I would love to contribute. The issue is probably in the [`rustc_builtin_macros`](https://github.com/rust-lang/rust/tree/master/compiler/rustc_builtin_macros) I assume, but I can't find where the attributes are being removed from the type generics of the item definition.

**Comment by fmease** [comment]
The relevant code is here: https://github.com/rust-lang/rust/blob/c682aa162b0d41e21cc6748f4fecfe01efb69d1f/compiler/rustc_builtin_macros/src/deriving/generic/mod.rs#L631-L681. As you've correctly guessed, for type parameters the attributes are effectively removed (well, a new type parameter gets created with `cx.typaram` which doesn't have any attrs) and for lifetime and const parameters, they are retained (because the original param gets cloned).

**Comment by fmease** [comment]
> If I understand correctly, normal proc macros don't even "see" the helper attributes of other macros.

I don't think that is true (bu I wish that was case)[https://github.com/rust-lang/libs-team/issues/334#issuecomment-1983349095]? How did you test this?

**Comment by fmease** [comment]
> Yes I agree, maybe there should be a list of built-in attributes that should not be removed?

Well, this all seems a bit tricky. I think you should go ahead and open a PR that removes these attributes *unconditionally*. I'll think about this some more and probably get into contact with other people to discuss this, too.

**Comment by PonasKovas** [comment]
> I don't think that is true (https://github.com/rust-lang/libs-team/issues/334#issuecomment-1983349095)? How did you test this?

Oops yeah, you're right I misunderstood. 

> Well, this all seems a bit tricky. I think you should go ahead and open a PR that removes these attributes unconditionally. I'll think about this some more and probably get into contact with other people to discuss this, too.

Ok sounds good!
