### ISSUE TITLE
[ICE]: Multiple hangs with specific compiler options

### ISSUE THREAD

**Issue by wxie7** [rust-lang/rust#132591]
### Code

EDIT: dropped not required flags

```
timeout 30 /path/to/rustc --crate-type staticlib -C link-dead-code -C debuginfo=2 -C opt-level=3 -Z mir-opt-level=3 file.rs
```

### Affected release channels

- [ ] Previous Stable
- [ ] Current Stable
- [ ] Current Beta
- [x] Current Nightly

### Rust Version

$ rustc -Vv
rustc 1.84.0-nightly (b8c8287a2 2024-11-03)
binary: rustc
commit-hash: b8c8287a229cd79604aa84c25e1235fc78cd5f2e
commit-date: 2024-11-03
host: x86_64-unknown-linux-gnu
release: 1.84.0-nightly
LLVM version: 19.1.3

### Backtrace

no backtrace

### Anything else?

The attached files contain multiple source codes that cause the compiler to hang.
[hangs.zip](https://github.com/user-attachments/files/17615126/hangs.zip)

**Comment by jieyouxu** [comment]
> `-Z unsound-mir-opts=yes`

Well...

**Comment by jieyouxu** [comment]
@wxie7 does the hang repro without `-Z unsound-mir-opts=yes`, because unsound mir-opts are, like the flag name suggests, unsound.

**Comment by jieyouxu** [comment]
And even better, does the hang repro with fewer flags?

**Comment by wxie7** [comment]
@jieyouxu Even after removing all `-Z` related flags, the compiler still hangs.

**Comment by jieyouxu** [comment]
And also, to clarify @wxie7 do they produce Internal Compiler Errors (ICE) which is usually associated with an ICE message, or do they just *hang* (i.e. don't terminate)?

**Comment by jieyouxu** [comment]
Thank you for the report, it would be even better next time if you indicated that these hangs are found via some kind of fuzzing, see the [fuzzing guidelines](https://rustc-dev-guide.rust-lang.org/fuzzing.html?highlight=fuzzing#fuzzing) in the dev-guide.

**Comment by Noratrieb** [comment]
@wxie7 -Zunsound-mir-opts mean that the opt is *known* to be broken, so testing that will not really lead to interesting results, it doesn't matter if there are gaps in the test suite for something we know is wrong anyways. we're not exactly very keen on preserving this wrong behavior :)

**Comment by jieyouxu** [comment]
(Also triage remark: we'll need to split this issue into multiple actionable individual issues, as it stands there's too many code examples that might not hang with the same flags and causes)

**Comment by wxie7** [comment]
> And also, to clarify [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/52962534?s=64&amp;v=4">@wxie7](https://github.com/wxie7) do they produce Internal Compiler Errors (ICE) which is usually associated with an ICE message, or do they just _hang_ (i.e. don't terminate)?

just hang

**Comment by jieyouxu** [comment]
Triage: @wxie7 I look a look at the example code snippets, they definitely need their individual bug reports because they are widely different:

E.g.:

- As you mentioned, some of them hang, some of them ICE, they are of different nature.
- Some of them have very early/broken/incomplete features like `#[feature(generic_associated_types_extended)]`. They definitely need their own bug reports because some of them may already be known (as bugs or known incomplete).
- Some of them use internal features like `#[feature(rustc_attrs)]` or `#[rustc_coinductive]` which are known to be internal features, and if they are misused it's not necessarily a bug cf. https://github.com/rust-lang/compiler-team/issues/620.

Yes, please kindly submit individual bug reports for them and consider what I mentioned above, thank you!

**Comment by workingjubilee** [comment]
@wxie7 Yes, please follow the rustc dev guide instructions:
> ## Please do:
>   Ensure the bug is still present on the latest nightly rustc
    Include a reasonably minimal, standalone example along with any bug report
    Include all of the information requested in the bug report template
    Search for existing reports with the same message and query stack
    Format the test case with rustfmt, if it maintains the bug
    Indicate that the bug was found by fuzzing

> ## Please don't:
>    Don't report lots of bugs that use internal features, including but not limited to custom_mir, lang_items, no_core, and rustc_attrs.
    Don't seed your fuzzer with inputs that are known to crash rustc (details below).

**Comment by jieyouxu** [comment]
To summarize what we have above, please do file individual issues. I'm closing this particular issue as it's too much of a kitchen sink and is not very actionable. Thanks!

**Comment by wxie7** [comment]
@jieyouxu Is it reasonable to add `-Z polonius=next -Z polymorphize=yes` during testing?

**Comment by jieyouxu** [comment]
@wxie7 Based on discussions in https://rust-lang.zulipchat.com/#narrow/channel/131828-t-compiler/topic/.60-Zpolymorphize.60.2F.60-Zpolonius.60.20when.20fuzzing.3F, let's avoid fuzzing with those specific flags for now.
