### ISSUE TITLE
`install::sanitize_sh(Path)` breaks paths in Windows 10

### ISSUE THREAD

**Issue by Houtamelo** [rust-lang/rust#132507]
When running `x install`, I was getting the following error:
```
Installing stage2 docs (x86_64-pc-windows-msvc)
sh: /C/Users/anton/Documents/rust_compilers/unchained/build/tmp/tarball/rust-docs/x86_64-pc-windows-msvc/rust-docs-nightly-x86_64-pc-windows-msvc/install.sh: No such file or directory
```

I found that the source of the issue was inside the function `sanitize_sh`, located in: "src/bootstrap/src/core/build_steps/install.rs":
```rust
fn sanitize_sh(path: &Path) -> String {
    let path = path.to_str().unwrap().replace('\\', "/");
    return change_drive(unc_to_lfs(&path)).unwrap_or(path);

    fn unc_to_lfs(s: &str) -> &str {
        s.strip_prefix("//?/").unwrap_or(s)
    }

    fn change_drive(s: &str) -> Option<String> {
        let mut ch = s.chars();
        let drive = ch.next().unwrap_or('C');
        if ch.next() != Some(':') {
            return None;
        }
        if ch.next() != Some('/') {
            return None;
        }
        Some(format!("/{}/{}", drive, &s[drive.len_utf8() + 2..]))
    }
}
```

`change_drive` turns paths such as "C:/user/foo" into "/C/user/foo", which makes those paths invalid, resulting in "No such file or directory" errors.

In my fork, I commented the call to `change_drive` and returned `path` directly:
```rust
let path = path.to_str().unwrap().replace('\\', "/");
return path;
```

Which fixed the issue, `x install` then ran without any problems, everything was installed correctly.

### Meta
OS: Windows 10 x64
rust-lang commit: https://github.com/rust-lang/rust/commit/ef972a346668ed4234d1a43ed4ad7ca4e9c58d51

**Comment by bjorn3** [comment]
If the shell is provided by MinGW I think `sanitize_sh` is necessary in it's entirety. Where did you get the `sh` binary that is used to run the install script from?

**Comment by Houtamelo** [comment]
> If the shell is provided by MinGW I think `sanitize_sh` is necessary in it's entirety. Where did you get the `sh` binary that is used to run the install script from?

Mine is cygwin64

**Comment by bjorn3** [comment]
Ah, it seems like cygwin expects paths in the format `/cygdrive/c/` rather than the `/c/` that mingw expects.

**Comment by onur-ozkan** [comment]
Could you check if #134023 works for you? @Houtamelo

**Comment by Houtamelo** [comment]
> Could you check if [#134023](https://github.com/rust-lang/rust/pull/134023) works for you? [@Houtamelo](https://github.com/Houtamelo)

Sadly no, I'm using Linux now.
