### ISSUE TITLE
Have bots automatically sign distributable artifacts

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#13252]
We sign releases manually right now, and don't sign nightlies. Would be better if the automation just did this for us.

**Comment by brson** [comment]
This is done. Thanks @bheesham!

**Comment by l0kod** [comment]
Great, the signatures seems to be there but without link in the [download page](http://www.rust-lang.org/install.html).

**Comment by l0kod** [comment]
The `src/etc/get-snapshot.py` should use the signatures as well.
