### ISSUE TITLE
Have bots sign snapshots

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#13254]
cc #13252. In order to have increased confidence that any given Rust hasn't been MITMed we need to go all the way to the source and sign the binary snaps.

**Comment by steveklabnik** [comment]
I believe we do this now, right @brson @edunham ? https://static.rust-lang.org/dist/staging/index.html has signatures

**Comment by alexcrichton** [comment]
Currently we just sign nightlies, not snapshots unfortunately

**Comment by steveklabnik** [comment]
Ah! Right.

**Comment by brson** [comment]
The current thinking is that we will remove snapshots entirely and move to using nightlies for bootstrapping.

**Comment by alexcrichton** [comment]
Done!

Well, snapshots are removed, so it's vacuously done
