### ISSUE TITLE
Drop python 2 support?

### ISSUE THREAD

**Issue by ChrisDenton** [rust-lang/rust#132641]
> do we really need to keep supporting python 2?

_Originally posted by @jieyouxu in https://github.com/rust-lang/rust/issues/132635#issuecomment-2457383960_

**Comment by onur-ozkan** [comment]
Supporting python 2 doesn't add extra maintenance costs for us and we will eventually migrate python parts to rust.

**Comment by jieyouxu** [comment]
> will eventually migrate python parts to rust.

Closing in favor of that.
