### ISSUE TITLE
Hang evaluating infinite loop at compile time with lint `long_running_const_eval` set to allow

### ISSUE THREAD

**Issue by wxie7** [rust-lang/rust#132669]
### Code

```rs
#![allow(long_running_const_eval)]
const FOO: () = {
    let mut i = 0;
    loop {
        fn main() {}
    }
};
fn main() {
    FOO
}
```

### Affected release channels

- [ ] Previous Stable
- [ ] Current Stable
- [ ] Current Beta
- [x] Current Nightly

### Rust Version

$ rustc -Vv
rustc 1.84.0-nightly (bc5cf994d 2024-11-05)
binary: rustc
commit-hash: bc5cf994db9fb46712cefd89f78ad7fc51f184a2
commit-date: 2024-11-05
host: x86_64-unknown-linux-gnu
release: 1.84.0-nightly
LLVM version: 19.1.3

### Backtrace

no backtrace

**Comment by fmease** [comment]
Works as intended, you've set lint long_running_const_eval from deny (default) to allow. See also https://doc.rust-lang.org/rustc/lints/listing/deny-by-default.html#long-running-const-eval.
