### ISSUE TITLE
nightly-2024-11-10 is unavailable

### ISSUE THREAD

**Issue by taiki-e** [rust-lang/rust#132838]
When trying to test the code that depends on the [change merged yesterday](https://github.com/rust-lang/rust/pull/132552), I noticed that the [toolchain is nightly-2024-11-09](https://github.com/taiki-e/atomic-maybe-uninit/actions/runs/11761419751/job/32763237407#step:5:36) which is the same as [yesterday's latest nightly](https://github.com/taiki-e/atomic-maybe-uninit/actions/runs/11752473089/job/32744153618#step:5:36).

```console
$ rustup update nightly-2024-11-10
info: syncing channel updates for 'nightly-2024-11-10-aarch64-apple-darwin'
error: no release found for 'nightly-2024-11-10'

Stack backtrace:
   0: std::backtrace::Backtrace::capture
   1: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
   2: rustup::dist::dist::try_update_from_dist_
   3: rustup::install::InstallMethod::install
   4: rustup::toolchain::distributable::DistributableToolchain::install
   5: rustup::cli::rustup_mode::update
   6: rustup::cli::rustup_mode::main
   7: rustup_init::main
   8: std::sys_common::backtrace::__rust_begin_short_backtrace
   9: _main
```

rustup-components-history also shows this nightly-2024-11-09 as "last_available".
https://github.com/rust-lang/rustup-components-history/blob/gh-pages/aarch64-apple-darwin/rustc.json#L9

If this is due to a temporary failure, it is not a problem for me as I will just wait until tomorrow, but I have opened the issue in case it is not.

cc @rust-lang/infra 

@rustbot label +T-infra

### Meta

`rustc --version --verbose`:
```
rustc 1.84.0-nightly (59cec72a5 2024-11-08)
binary: rustc
commit-hash: 59cec72a57af178767a7b8e7f624b06cc50f1087
commit-date: 2024-11-08
host: aarch64-apple-darwin
release: 1.84.0-nightly
LLVM version: 19.1.3
```

`rustup --version --verbose`:
```
rustup --version --verbose
rustup 1.27.1 (54dd3d00f 2024-04-24)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.84.0-nightly (59cec72a5 2024-11-08)`
```

**Comment by taiki-e** [comment]
nightly-2024-11-11 is available, so it appears that the problem here was temporary or has already been fixed.

**Comment by RalfJung** [comment]
This may have been caused by https://github.com/rust-lang/rust/issues/132845
