### ISSUE TITLE
#[derive(Clone)] should explicitly override `clone_from`

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#13281]
This would mean derived clone implementations can reuse the resources of interior types (especially important with types containing things like `Vec`) when cloning into an already-created instance.

Currently doing this is difficult with how `#[deriving]` works internally (needs a mutable borrow of the contents of `self`, and needs to avoid borrowing `self` for enum variants that mismatch or else the requisite `*self = other.clone()` implementation won't work).

**Comment by steveklabnik** [comment]
Triage: no change that i'm aware of.

**Comment by tbu-** [comment]
Seems like we could close this issue (see reasoning in #27939).

**Comment by dtolnay** [comment]
The reasoning in #27939 still applies as to why this should not be provided by the built-in derive(Clone). A custom derive for clone_from is provided in the [`derivative`](https://mcarton.github.io/rust-derivative/Clone.html) crate
