### ISSUE TITLE
rust_2024_incompatible_pat does not work with macros

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#132821]
I tried this code:

```rust
#![warn(rust_2024_incompatible_pat)]

pub struct S<'a>(&'a T);

pub enum T {
    A(String),
}

macro_rules! m {
    () => {
        pub fn f(x: S) {
            match x.0 {
                T::A(ref _x) => {}
            }
        }
    };
}

m! {}
```

I expected to see this happen: Should provide a machine-applicable diagnostic suggestion for [`rust_2024_incompatible_pat`](https://doc.rust-lang.org/nightly/rustc/lints/listing/allowed-by-default.html#rust-2024-incompatible-pat).

Instead, this happened: Provides a MaybeIncorrect suggestion, which prevents 2024 automatic migration.

I realize it can be tricky since the exact binding mode behavior may depend on the type, which could change based on the caller. I'd be curious how often this suggestion would actually be incorrect.

### Meta

`rustc --version --verbose`:
```
rustc 1.84.0-nightly (b91a3a056 2024-11-07)
binary: rustc
commit-hash: b91a3a05609a46f73d23e0995ae7ebb4a4f429a5
commit-date: 2024-11-07
host: aarch64-apple-darwin
release: 1.84.0-nightly
LLVM version: 19.1.3
```

**Comment by ehuss** [comment]
The part of the code related to determining the applicability is here: https://github.com/rust-lang/rust/blob/6503543d11583d1686d4989847b2afbec8d9fdba/compiler/rustc_mir_build/src/errors.rs#L996-L1001

**Comment by traviscross** [comment]
@Nadrieril: What do you think?  Certainly there's some danger in touching code in macros.  Better to leave it as is or try to touch code in the macros?

**Comment by Nadrieril** [comment]
To make the suggestion `machine-applicable`, we'd need to ensure that the suggestion is correct for all possible calls of the macro. I don't think that's a thing we can do.

**Comment by traviscross** [comment]
Sounds good.  Even if we were to decide it'd be OK to have some misses to such a machine-applicable suggestion, we'd need to crater run that, and it's probably not worth it in this case.
