### ISSUE TITLE
2024 impl_trait_overcaptures ambiguous `+`

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#132853]
I tried this code:

```rust
#![warn(impl_trait_overcaptures)]

pub fn f(x: &i32) -> &impl Clone {
    x
}
```

I expected to see this happen: Provides a valid suggestion that is `-> &(impl Clone + use<>)` with parentheses to avoid ambiguity.

Instead, this happened: Provides a suggestion that includes `&impl Clone + use<>` which fails to parse with:

```
error: ambiguous `+` in a type
 --> src/main.rs:3:23
  |
3 | pub fn f(x: &i32) -> &impl Clone + use<> {
  |                       ^^^^^^^^^^^^^^^^^^
  |
help: try adding parentheses
  |
3 | pub fn f(x: &i32) -> &(impl Clone + use<>) {
  |                       +                  +
```

### Meta

`rustc --version --verbose`:
```
rustc 1.84.0-nightly (b91a3a056 2024-11-07)
binary: rustc
commit-hash: b91a3a05609a46f73d23e0995ae7ebb4a4f429a5
commit-date: 2024-11-07
host: aarch64-apple-darwin
release: 1.84.0-nightly
LLVM version: 19.1.3
```

**Comment by ehuss** [comment]
@compiler-errors Just checking if this is still something you could look at, or how complex this might be?

**Comment by compiler-errors** [comment]
Sure, let me put up a quick fix.
