### ISSUE TITLE
Possible soundness issue allowing to compile a trait with `MyTrait: Sized` and use it as `Box<dyn MyTrait>`

### ISSUE THREAD

**Issue by yoav-lavi** [rust-lang/rust#132999]
I tried this code:

https://github.com/grafbase/grafbase/blob/broken-compilation/crates/federated-server/src/server/graph_fetch_method.rs#L24

and 

https://github.com/grafbase/grafbase/blob/broken-compilation/gateway/src/args.rs#L17

and

https://github.com/grafbase/grafbase/blob/broken-compilation/gateway/src/args/std.rs#L71

I expected to see this happen: The above code should not compile as the trait is not object safe

Instead, this happened: Rust Analyzer errored sporadically, but the project compiled successfully

### Meta
`rustc --version --verbose`:
```
rustc 1.82.0 (f6e511eec 2024-10-15)
binary: rustc
commit-hash: f6e511eec7342f59a25f7c0534f1dbea00d01b14
commit-date: 2024-10-15
host: aarch64-apple-darwin
release: 1.82.0
LLVM version: 19.1.1
```

**Comment by lqd** [comment]
Yeah the code doesn't compile, so maybe you meant to open this issue for rust-analyzer itself?

**Comment by yoav-lavi** [comment]
@lqd My mistake, had just closed the issue before you commented. I wasn't compiling the crate in question and was using that trait in another crate I was compiling, but without `dyn`.
Thanks for checking this out and sorry for the confusion!
