### ISSUE TITLE
concat_idents! is not very useful

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#13294]
It cannot access local variables due to hygiene, it can't be used to create names of a function (not where a macro can appear), and it can basically only be used to access non-hygienic things.

I believe the utility of this macro has been greatly reduced over time, and it may be time to just remove it (or feature gate it)

Nominating (it's a core built-in macro)

**Comment by cmr** [comment]
I agree with @kmcallister, it's a quite useful feature in some cases.

**Comment by steveklabnik** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/29599
