### ISSUE TITLE
Rustdoc search ranking regression in 1.82

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#133017]
Compare these two rankings:

- https://doc.rust-lang.org/1.81.0/std/?search=write
- https://doc.rust-lang.org/1.82.0/std/?search=write

In 1.81, `std::io::Write` shows up as number 5, after three functions called `write` in std::{fmt, fs, ptr} and after std::fmt::Write. These results look decent enough to me.

In 1.82, `std::io::Write` is at number 36, after things like `<std::io::Stdout as std::io::Write>::write`. I don't think there is any justification for `<std::io::Stdout as std::io::Write>::write` and `std::io::Write::write` to outrank `std::io::Write` when searching for "write".

The most recent nightly continues to be affected (https://doc.rust-lang.org/nightly/std/?search=write).

**Comment by fmease** [comment]
Marking P-critical, but feel free to downgrade to P-high.

**Comment by fmease** [comment]
I think the high-level solution would be to cease factoring in case-sensitivity when ranking search results if the search string doesn't contain any uppercase characters. Reworded, only if the input string contains some uppercase characters consider case-sensitivity when ranking. I believe I've seen that behavior in other applications. For example, for *write* the ranking should match 1.81's but for *Write* the ranking can match >1.82's.

**Comment by dtolnay** [comment]
I agree with that solution. Vim's search behaves this way under the name `smartcase`. <https://vimdoc.sourceforge.net/htmldoc/options.html#'smartcase'>
