### ISSUE TITLE
rustdoc: highlight default enum variant

### ISSUE THREAD

**Issue by H2WO4** [rust-lang/rust#133174]
### Problem

It would be convenient and help readability if enum variants marked with `#[default]` in the code would be also marked as such in the documentation.

While it is certainly possible to just use a doc comment, it would be better to have a standardized automatic solution.

### Proposed Solution

Displaying `(default)` next to the default variant would be more than sufficient.

Quick mockup of what it could look like:
![Image](https://github.com/user-attachments/assets/23c8b815-c170-4974-988c-edbb17065f2b)

Additionally, pre- or postfixing the variant with a symbol could also be a viable solution.

### Notes

A similar issue was already created [in the docs.rs repository](https://github.com/rust-lang/docs.rs/issues/2206) but closed as it should have been opened here.

This would only apply to variant using the `#[default]` attribute; manual `Default` impls would clearly be out of scope (due to the insanity of parsing the behavior of such a function).

**Comment by fmease** [comment]
This feature was FCP-closed in https://github.com/rust-lang/rust/pull/115575. Please see that PR and the linked issue for the rationale.
