### ISSUE TITLE
Unexpected panic reason when div overflow on target wasm32-unknown-unknown

### ISSUE THREAD

**Issue by nan01ab** [rust-lang/rust#133100]
### Code

```Rust
#![no_std]
#![no_main]

#[cfg(target_family = "wasm")]
#[panic_handler]
#[no_mangle]
fn wasm_panic(_info: &core::panic::PanicInfo) -> ! {
    core::arch::wasm32::unreachable()
}

#[no_mangle]
#[inline(never)]
fn check_div(y: i32, k: i32) -> i32 {
    y / k
}
```

### Current output

* When compiling with 'opt-level = 2 and lto = true':

   Calling `check_div` with args -2147483648 -1 will panic with `core::panicking::panic_const::panic_const_div_by_zero`

* If compiling with 'opt-level = 0 and lto = true', or 'opt-level = 2 and lto = false':

   Calling `check_div` with args -2147483648 -1 will panic with `core::panicking::panic_const:: panic_const_div_overflow `

The decompiled wasm code(compiling with 'opt-level = 2 and lto = true'):

```
(module $hello_world-d3d1e1992c23185d.wasm
  (type (;0;) (func))
  (type (;1;) (func (param i32 i32) (result i32)))
  (func $_ZN4core9panicking9panic_fmt17h09847671fa0d2676E (type 0)
    unreachable)
  (func $_ZN4core9panicking11panic_const23panic_const_div_by_zero17h63eb8f6bfd6901e0E (type 0)
    call $_ZN4core9panicking9panic_fmt17h09847671fa0d2676E
    unreachable)
  (func $check_div (type 1) (param i32 i32) (result i32)
    block  ;; label = @1
      block  ;; label = @2
        local.get 1
        i32.eqz
        br_if 0 (;@2;)
        local.get 0
        i32.const -2147483648
        i32.ne
        br_if 1 (;@1;)
        local.get 1
        i32.const -1
        i32.ne
        br_if 1 (;@1;)
      end
      call $_ZN4core9panicking11panic_const23panic_const_div_by_zero17h63eb8f6bfd6901e0E
      unreachable
    end
    local.get 0
    local.get 1
    i32.div_s)
  (memory (;0;) 16)
  (global $__stack_pointer (mut i32) (i32.const 1048576))
  (global (;1;) i32 (i32.const 1048576))
  (global (;2;) i32 (i32.const 1048576))
  (export "memory" (memory 0))
  (export "check_div" (func $check_div))
  (export "__data_end" (global 1))
  (export "__heap_base" (global 2)))
```

### Desired output

Calling `check_div` with args -2147483648 -1 should be panic with `core::panicking::panic_const::panic_const_div_overflow` always.

### Rust Version

```Shell
rustc --version --verbose
rustc 1.82.0 (f6e511eec 2024-10-15)
binary: rustc
commit-hash: f6e511eec7342f59a25f7c0534f1dbea00d01b14
commit-date: 2024-10-15
host: x86_64-apple-darwin
release: 1.82.0
LLVM version: 19.1.1
```

**Comment by saethlin** [comment]
> Calling `check_div` with args -2147483648 -1 should be panic with `core::panicking::panic_const::panic_const_div_overflow` always.

We don't guarantee this. The observable behavior of the program is the same regardless of which function is used by LLVM to abort the program. Information you can see with a backtrace or a debugger is not considered observable behavior (if it were, inlining would not be a legal optimization).

The optimization that's being done here is the kind of interprocedural reasoning that makes LTO so powerful. If you want breadcrumbs left in your backtraces, you usually have to do something with `hint::black_box` to discourage optimizations.
