### ISSUE TITLE
Bootstrap without creating a config.toml fails with missing rust-objcopy

### ISSUE THREAD

**Issue by wesleywiser** [rust-lang/rust#133195]
After cloning, I expected `python3 x.py test --stage 1 tests/ui` to succeed but instead I got many test failures like this one:

```
---- [ui] tests/ui/async-await/track-caller/panic-track-caller.rs#afn stdout ----

error in revision `afn`: test compilation failed although it shouldn't!
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/Users/wesley/Code/rust/build/aarch64-apple-darwin/stage1/bin/rustc" "/Users/wesley/Code/rust/tests/ui/async-await/track-caller/panic-track-caller.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/Users/wesley/.cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/Users/wesley/Code/rust/vendor" "--sysroot" "/Users/wesley/Code/rust/build/aarch64-apple-darwin/stage1" "--target=aarch64-apple-darwin" "--cfg" "afn" "--check-cfg" "cfg(FALSE,afn,cls,nofeat)" "-O" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "-C" "prefer-dynamic" "-o" "/Users/wesley/Code/rust/build/aarch64-apple-darwin/test/ui/async-await/track-caller/panic-track-caller.afn/a" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/Users/wesley/Code/rust/build/aarch64-apple-darwin/native/rust-test-helpers" "--edition=2021"
stdout: none
--- stderr -------------------------------
error: unable to run `rust-objcopy`: No such file or directory (os error 2)

error: aborting due to 1 previous error
------------------------------------------
```

However, if I create a `config.toml` by `cp config.example.toml config.toml`, then the problem goes away.

I instrumented the code here with a `println!()` and I can see that when `config.toml` exists, this block runs but when `config.toml` does not exist, it does not run:

https://github.com/rust-lang/rust/blob/b71fb5edc0217eaf8fc824a44cd7b0945e29ff4d/src/bootstrap/src/core/build_steps/compile.rs#L1980-L1988

Possibly related to #132720 cc @jieyouxu 

### Meta

Cloned rust-lang/rust at b71fb5edc0217eaf8fc824a44cd7b0945e29ff4d

Host is `aarch64-apple-darwin`

**Comment by jieyouxu** [comment]
[Only copy, rename and link llvm-objcopy if llvm tools are enabled #132720](https://github.com/rust-lang/rust/pull/132720) fixes [Shipping llvm-strip w/ a symlink breaks when bootstrap compiler doesn't contain any LLVM tools #132719](https://github.com/rust-lang/rust/issues/132719) because cg_clif doesn't have llvm bin tools in the bootstrap compiler.

That was because [bootstrap/codegen_ssa: ship llvm-strip and use it for -Cstrip #131405](https://github.com/rust-lang/rust/pull/131405) was introduced to fix [Hard-coded strip path breaks Linux -> Darwin builds #131206](https://github.com/rust-lang/rust/issues/131206).

And `strip` was hard-coded before by [Fix up setting strip = true in Cargo.toml makes build scripts fail in… #130781](https://github.com/rust-lang/rust/pull/130781) because using a random `strip` from `PATH` on macOS can mean using a broken homebrew strip (AFAIK still broken).

> If you are using binutils strip to strip arm64 macOS binaries, it does not work fine. It produces broken binaries with invalid code signature. On arm64 macOS mandates the use of code signatures, so "unsigned" binaries use an ad-hoc code signature, but binutils seems to forget to update the ad-hoc code signature when modifying binaries. This is exactly the problem https://github.com/rust-lang/rust/pull/130781 fixed by forcing XCode's strip to be used instead.
> -- https://github.com/rust-lang/rust/issues/131206#issuecomment-2393602871

**Comment by jieyouxu** [comment]
I'm not very sure what's the proper fix here... Default `config.toml`-less macOS builds to acquire CI llvm and llvm bin tools?

**Comment by jieyouxu** [comment]
Right, this is an llvm bin tool which is only really handled by the dist flow... The compile flow just *assumes* it exists which is problematic

**Comment by jieyouxu** [comment]
Right... because we hard code this to `rust-objcopy` in cg_ssa:

https://github.com/rust-lang/rust/blob/e6c1e14e5d487a90abeb5ba4dccc608521bbfb54/compiler/rustc_codegen_ssa/src/back/link.rs#L1106-L1107

**Comment by jieyouxu** [comment]
> I instrumented the code here with a println!() and I can see that when config.toml exists, this block runs but when config.toml does not exist, it does not run

Apparently without a config.toml `llvm_tools_enabled` is `false` by default
