### ISSUE TITLE
Rendered Rustc book out of sync: wasm32-wasip2 should be documented as Tier-2 target

### ISSUE THREAD

**Issue by ifsheldon** [rust-lang/rust#133206]
### Location

Hi! Today I looked up rustc book for the support of wasm32-wasip2 target. I found the website is still documenting wasm32-wasip2 as a Tier-3 target. 

![Image](https://github.com/user-attachments/assets/e2e40998-c6d6-40df-923c-74aebbb0adff)
![Image](https://github.com/user-attachments/assets/28109d6b-2d6d-47e0-ba3c-9ccdaaa12392)

And I looked up the source code.

https://github.com/rust-lang/rust/blob/e6c1e14e5d487a90abeb5ba4dccc608521bbfb54/src/doc/rustc/src/platform-support.md?plain=1#L196

The table has been updated, but the document of wasm32-wasip2 is still out of date.

https://github.com/rust-lang/rust/blob/e6c1e14e5d487a90abeb5ba4dccc608521bbfb54/src/doc/rustc/src/platform-support/wasm32-wasip2.md?plain=1#L3

These seems a bit weird to me:
* The table and the specific document for wasm32-wasip2 on the website are both out of date.
* The table in the source code is up to date, while the specific document is out of date.

This issue may also reflect some procedural issues when promoting a target? I saw https://github.com/rust-lang/rust/issues/129997 and https://github.com/rust-lang/rust/issues/129998, but they seem not to be enforcing syncs on the rustc book.

I don't know anything about the publication process of rustc book, but I think it should be at least updated when stable Rust 1.82 was announced.

### Summary

The published website of rustc book is out of date, documenting wasm32-wasip2 as a Tier-3 target. The source code of rustc book is also partially out of data and out of sync.

**Comment by alexcrichton** [comment]
My mistake, fixed in https://github.com/rust-lang/rust/pull/133213

**Comment by ifsheldon** [comment]
@alexcrichton I think the content in the document should also be updated? 

For example:
https://github.com/rust-lang/rust/blob/e6c1e14e5d487a90abeb5ba4dccc608521bbfb54/src/doc/rustc/src/platform-support/wasm32-wasip2.md?plain=1#L67

I guess (very likely) this is no longer true. I didn't dig into the differences, though.

**Comment by ifsheldon** [comment]
Besides, when will the published Rustc book website get updated? I think it should be updated when a stable release of Rust is announced, so the fixes should be "backported" to 1.82 rustc book?

**Comment by alexcrichton** [comment]
I believe that documentation about enabled features is correct, are you seeing otherwise though?

I also believe the book is updated based on releases of Rust. For example there is:

* https://doc.rust-lang.org/stable/rustc/ - updated on stable releases
* https://doc.rust-lang.org/beta/rustc/ - updated on beta releases
* https://doc.rust-lang.org/nightly/rustc/ - updated on nightly releases

(I could have outdated knowledge though)
