### ISSUE TITLE
`--enable-simd` feature is present in `wasm32-unknown-unknown` target, not enabled by `target-feature=+simd128`

### ISSUE THREAD

**Issue by dj8yfo** [rust-lang/rust#133290]
I tried this code:

https://github.com/dj8yfo/abstract-dao/tree/056f74e16fbaba84b75c49522c1176c477a975d1

```bash 
git clone https://github.com/dj8yfo/abstract-dao.git
cd abstract-dao/
git checkout origin/1.82_plus_simd128_bug
cargo build --target wasm32-unknown-unknown --release
```

I expected to see this happen: 

```bash
❯ : wasm-opt --print-features target/wasm32-unknown-unknown/release/near_abstract_dao.wasm
--enable-mutable-globals
--enable-sign-ext
--enable-reference-types
--enable-multivalue
```
In fact, this behaves as expected on previous version of `Cargo.lock` in https://github.com/dj8yfo/abstract-dao/tree/fe9d16797bf582f0ea24380c1e4ad6bdb8c97283 , 
before running `cargo update`

Instead, this happened: 
Additional `--enable-simd` feature is present in output wasm, 
which wasn't enabled with `RUSTFLAGS = "-C target-feature=+simd128"`

```bash
❯ : wasm-opt --print-features target/wasm32-unknown-unknown/release/near_abstract_dao.wasm
--enable-mutable-globals
--enable-simd
--enable-sign-ext
--enable-reference-types
--enable-multivalue
```

### Meta

Present on `rustc 1.84.0-nightly (3fee0f12e 2024-11-20)` 
and `rustc 1.83.0-beta.6 (4ff8ff0ec 2024-11-16)`
and on `rustc 1.81.0 (eeb90cda1 2024-09-04)` if moving **backwards**

`rustc --version --verbose`:
```
❯ : rustc -vV
rustc 1.82.0 (f6e511eec 2024-10-15)
binary: rustc
commit-hash: f6e511eec7342f59a25f7c0534f1dbea00d01b14
commit-date: 2024-10-15
host: x86_64-unknown-linux-gnu
release: 1.82.0
LLVM version: 19.1.1
```
this is also reproduced on `aarch64-apple-darwin` , more discussion/context is present in https://github.com/nearuaguild/abstract-dao/pull/9

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by dj8yfo** [comment]
another issue is that `RUSTFLAGS="-C link-arg=-s"` option appears to remove 
```bash
--enable-reference-types
--enable-multivalue
--enable-simd
```
from internal header in wasm, which makes `*.wasm` file an invalid format with respect to what `wasm-opt version 118` can parse , which looks like a *bug* too, 

while 
```bash
--enable-mutable-globals
--enable-sign-ext
```
stay in this header.

**Comment by dj8yfo** [comment]
on this version https://github.com/dj8yfo/abstract-dao/tree/056f74e16fbaba84b75c49522c1176c477a975d1
both 1.81 and 1.82 emit:

```nushell
❯ : wasm2wat target/wasm32-unknown-unknown/release/near_abstract_dao.wasm o+e>| grep v128.store
        v128.store align=4
        v128.store align=4
        v128.store align=4
    v128.store align=8
    v128.store offset=16 align=8
    v128.store align=1
    v128.store align=1
        v128.store align=4
```
and on https://github.com/dj8yfo/abstract-dao/tree/fe9d16797bf582f0ea24380c1e4ad6bdb8c97283 
`v128.store` aren't present

**Comment by hanna-kruppe** [comment]
It’s very likely that this is caused by one of the new/updated libraries in your lockfile, not a bug in the Rust compiler. Like instruction set extensions for physical CPU instruction sets, wasm `target_feature`s can be enabled for individual functions even if they’re not globally enabled. This is almost never correct for wasm because wasm engines validate the entire module up-front so you can’t do dynamic feature detection (the main use case for per-function target features) but library authors aren’t always aware of this. The lockfile diff is too large to pin down the culprit but you could look at the names of the functions that contain SIMD instructions, and/or update dependencies one-by-one with `cargo update foo` to narrow it down.

**Comment by hanna-kruppe** [comment]
Yes, Rust doesn't take a stance on this sort of thing. It's possible that rustc/cargo could do *something* to make this easier or less likely to happen. It's not an unreasonable request, but there's some design work that someone would have to do to turn it into a concrete feature request.

**Comment by dj8yfo** [comment]
@hanna-kruppe i'll close this then; can you take a look at https://github.com/DaniPopes/const-hex/issues/17 and confirm 
whether it's correct logic to conditionally enable this `simd128` feature and compiler problem, 
or it's incorrect logic to conditionally enable `simd128` feature and NOT a compiler problem

**Comment by hanna-kruppe** [comment]
More up-to-date and hands-on documentation for using `#[target_feature]` is found in the `std::arch` documentation. The [wasm32 submodule](https://doc.rust-lang.org/core/arch/wasm32/index.html) in particular also talks a bit about wasm-specific challenges.

**Comment by dj8yfo** [comment]
@hanna-kruppe 
well, reading your explanation and looking at doc in https://doc.rust-lang.org/core/arch/wasm32/index.html
![Image](https://github.com/user-attachments/assets/e7ea98b6-aea2-4c40-bfcc-e0992c90bc0c)

it looks like there's an issue with compiler after all, because generated wat got these SIMD instructions enabled everywhere, and not only for `const-hex` functions.

**Comment by hanna-kruppe** [comment]
I don't have a lot of time to look further into this. You may have more luck getting someone to look into it if you minimize the reproducer to a single crate and can give instructions for testing it without having to install wasm-opt.

**Comment by alecmocatta** [comment]
I'm also seeing a Cargo.lock bump triggering v128.* opcodes everywhere, presumably LLVM emitted. Will try updating again in a couple months and narrow it down if this persists.
