### ISSUE TITLE
Parsing `<<` is incorrect for closure types

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#13324]
This is a valid type signature, but it fails to parse today.

```rust
Option<<'a>||>
```

Most closure parsing was fixed in #13268, but this is the remaining bits of #11209.

Nominating because #11209 was nominated. I don't believe this should block 1.0.

**Comment by jakub-** [comment]
Hmm, this should not have been closed. I made a typo when preparing https://github.com/rust-lang/rust/pull/19780.

**Comment by goffrie** [comment]
Erm, wasn't this already closed long ago by ac1a270?

**Comment by jakub-** [comment]
@goffrie It was, my bad! Thanks. :)
