### ISSUE TITLE
Adjust `rust.download-rustc` to be not incompatible with `rust.debug-assertions` once alt rustc is built with debug assertions

### ISSUE THREAD

**Issue by jieyouxu** [rust-lang/rust#133381]
cc [Use download-rustc=false global default, if-unchanged for tools and library profiles, and make rust.debug-assertions=true inhibit downloading CI rustc #133068](https://github.com/rust-lang/rust/pull/133068).

cc [Enable debug assertions on alt builds #131077](https://github.com/rust-lang/rust/pull/131077).

**Comment by onur-ozkan** [comment]
I would just keep it as incompatible as the same problem would occur again when switching this option.

**Comment by jieyouxu** [comment]
Agreed.
