### ISSUE TITLE
const LazyLock::new strange behavior

### ISSUE THREAD

**Issue by adic3x** [rust-lang/rust#133391]
I tried this code:

```rust
const A: std::sync::LazyLock<u64> = std::sync::LazyLock::new(|| {
    println!("const");
    1337
});

static B: std::sync::LazyLock<u64> = std::sync::LazyLock::new(|| {
    println!("static");
    123
});

fn main() {
    println!("{}", *A);
    println!("{}", *A);
    
    println!("{}", *B);
    println!("{}", *B);
}
```

(playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=908596bd1831cd236ea874be4110e94b)

I expected to see this happen: const is some memory with data which may be calculated in compile time. LazyLock:::new returns LazyLock struct: simplified it is data and init flag. So I expected  in const A just this data. And and this shouldn't work because when I call deref on this data flag must be checked and if data not initialized closure must be called, result written to data and flag updated. But const isn't mutable as I understand.

Instead, this happened: const LazyLock always call closure and return new result.

I think const LazyLock have no sense, but Rust is very robust lang, so does this code must be compiled at all?

```
rustc 1.82.0 (f6e511eec 2024-10-15)
```

**Comment by cyrgani** [comment]
`const`s work by replacing each usage of `A` with `std::sync::LazyLock::new(|| {
    println!("const");
    1337
});`, so your program is equivalent to:

```rust
static B: std::sync::LazyLock<u64> = std::sync::LazyLock::new(|| {
    println!("static");
    123
});

fn main() {
    println!(
        "{}",
        *std::sync::LazyLock::new(|| {
            println!("const");
            1337
        })
    );
    println!(
        "{}",
        *std::sync::LazyLock::new(|| {
            println!("const");
            1337
        })
    );

    println!("{}", *B);
    println!("{}", *B);
}
```
which will compile but make little sense.
There is also a clippy lint warning about this:
```
warning: a `const` item should not be interior mutable
 --> src/main.rs:1:1
  |
1 | / const A: std::sync::LazyLock<u64> = std::sync::LazyLock::new(|| {
2 | |     println!("const");
3 | |     1337
4 | | });
  | |___^
  |
  = help: consider making this a static item
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#declare_interior_mutable_const
  = note: `#[warn(clippy::declare_interior_mutable_const)]` on by default
```

**Comment by lukaslueg** [comment]
You're confusing `const` and `static`. From [the docs](https://doc.rust-lang.org/std/keyword.const.html) regarding const:

> const items look remarkably similar to static items, which introduces some confusion as to which one should be used at which times. To put it simply, constants are inlined wherever they’re used, making using them identical to simply replacing the name of the const with its value. Static variables, on the other hand, point to a single location in memory, which all accesses share.

That is, the compiler makes no guarantees about `*A` and `*B` pointing to independent copies of the `LazyLock`

**Comment by adic3x** [comment]
Thanks for the clarification, I actually thought that constants worked differently. So it's isn't bug, my report must be closed.
