### ISSUE TITLE
Editor highlighting and syntax should also be packaged in the installer packages

### ISSUE THREAD

**Issue by artichokes** [rust-lang/rust#13334]
The `src/etc/{emacs, gedit, kate, vim, zsh}` folders should also be packaged. This would make it easier for package maintainers to include them.

**Comment by huonw** [comment]
This may be trickier now that the configs are in separate repos (cc https://github.com/rust-lang/rust/issues/18274#issuecomment-72432869).

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by alexcrichton** [comment]
This is a pretty old bug at this point, but all our editor integration has its own packaging/distribution mechanisms, so I'm going to close this.
