### ISSUE TITLE
RPITITs may imply unsound outlives for late-bound args in signature

### ISSUE THREAD

**Issue by compiler-errors** [rust-lang/rust#133427]
I tried this code:

```rust
use std::sync::Mutex;

static MUTEX: Mutex<Option<&'static str>> = Mutex::new(None);

trait Foo {
    fn foo<'a: 'static>(&self) -> impl Sized;
}

impl Foo for str {
    fn foo<'a: 'static>(&'a self) -> impl Sized + 'a {
        *MUTEX.lock().unwrap() = Some(self);
    }
}

fn call_foo<T: Foo + ?Sized>(s: &T) {
    s.foo();
}

fn main() {
    let s = String::from("hello, world");
    call_foo(s.as_str());
    drop(s);
    println!("> {}", MUTEX.lock().unwrap().unwrap());
}
```

I expected to see this happen: Compilation failure.

Instead, this happened: Segfault due to UAF

### Why?

See comment below.

### Meta

`rustc --version --verbose`:
```
2024-11-24
```

Not present on beta or stable.

**Comment by compiler-errors** [comment]
While it may seem from bisection that this is due to:

* #129383

It's actually only *uncovered* by that PR because it flipped the order that we listed opaque lifetimes (which changes what regions we end up remapping in the `collect_return_position_impl_trait_in_trait_tys` query). Instead, this is due to my stupidity in:

* #113182, in 473c88dfb69f95b2e8c5f71ba7f6b7b448d22dc2 ([Flip the order of binder instantiation for better diagnostics](https://github.com/rust-lang/rust/pull/113182/commits/473c88dfb69f95b2e8c5f71ba7f6b7b448d22dc2))

**Comment by compiler-errors** [comment]
Actually, here's an unsoundness that is on stable.

```rust
trait MkStatic {
    fn mk_static(self) -> &'static str;
}

impl MkStatic for &'static str {
    fn mk_static(self) -> &'static str { self }
}

trait Foo {
    fn foo<'a: 'static, 'late>(&'late self) -> impl MkStatic;
}

impl Foo for str {
    fn foo<'a: 'static>(&'a self) -> impl MkStatic {
        self
    }
}

fn call_foo<T: Foo + ?Sized>(t: &T) -> &'static str {
    t.foo().mk_static()
}

fn main() {
    let s = call_foo(String::from("hello, world").as_str());
    println!("> {s}");
}
```

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/channel/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23133427.20RPITITs.20may.20imply.20unsound.20outlives.20for.20late-bound.20a.E2.80.A6)).

@rustbot label -I-prioritize +P-high
