### ISSUE TITLE
TyCtxt::variances_of is misdocumented as applying to a generic parameter

### ISSUE THREAD

**Issue by btj** [rust-lang/rust#133494]
### Location

https://doc.rust-lang.org/beta/nightly-rustc/rustc_middle/ty/struct.TyCtxt.html#method.variances_of

### Summary

This method returns the variances of the generic parameters of the struct with the given def_id. Contrary to what the documentation suggests, when given the def_id of a generic parameter of a struct, it returns an empty slice.

**Comment by fmease** [comment]
... of the \**type* given by the `DefId` but otherwise you're right where *type* refers to ADTs and lazy type aliases.
