### ISSUE TITLE
Implicit return with block expression causes compilation to fail

### ISSUE THREAD

**Issue by FineFindus** [rust-lang/rust#133594]
I tried this code:

```rust
fn foo() -> i32 {
    1
}

fn bar() -> bool {
    { foo() } == 1
}
```

I expected to see this happen: The code should compile, as the block expression should return value returned by the function.

Instead, this happened: The compilation fails. However, when assigning the value first or using the `return` keyword, the code successfully compiles.

```rust
fn bar() -> bool {
   // both of the compile
   let val =  { foo() } == 1;
   val
   return { foo() } == 1;
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.82.0 (f6e511eec 2024-10-15)
binary: rustc
commit-hash: f6e511eec7342f59a25f7c0534f1dbea00d01b14
commit-date: 2024-10-15
host: x86_64-unknown-linux-gnu
release: 1.82.0
LLVM version: 19.1.1
```

<details><summary>Backtrace</summary>
<p>

```
error: expected expression, found `==`
 --> src/lib.rs:6:15
  |
6 |     { foo() } == 1
  |               ^^ expected expression

warning: unnecessary braces around block return value
 --> src/lib.rs:6:5
  |
6 |     { foo() } == 1
  |     ^^     ^^
  |
  = note: `#[warn(unused_braces)]` on by default
help: remove these braces
  |
6 -     { foo() } == 1
6 +     foo() == 1
  |

error[E0308]: mismatched types
 --> src/lib.rs:6:7
  |
6 |     { foo() } == 1
  |       ^^^^^- help: consider using a semicolon here: `;`
  |       |
  |       expected `()`, found `i32`

For more information about this error, try `rustc --explain E0308`.
```

</p>
</details>

**Comment by cyrgani** [comment]
Notably, `1 == { 1 }` compiles as expected, but `{ 1 } == 1` fails.

**Comment by ChayimFriedman2** [comment]
This is known and documented: https://doc.rust-lang.org/stable/reference/statements.html#expression-statements.

@rustbot label -C-bug +C-discussion

**Comment by jieyouxu** [comment]
This specific case is also known *way* back in like #28379

**Comment by jieyouxu** [comment]
This is very much intentional. Thank you for the report.
