### ISSUE TITLE
2024 edition migration seems overly eager to rewrite every `if let` into `match`

### ISSUE THREAD

**Issue by djc** [rust-lang/rust#133554]
I tried running `cargo +nightly fix --edition` against [Quinn](https://github.com/quinn-rs/quinn). It seems to rewrite a lot of instances of `if let` to `match`, without seemingly much explanation or discrimination. This makes the code harder to read/less concise in many cases. Is this really necessary for all these cases? Could it somehow be made to be more precise/discriminate?

```diff
@@ -1254,8 +1284,11 @@ impl fmt::Debug for State {
 }
 
 fn wake_stream(stream_id: StreamId, wakers: &mut FxHashMap<StreamId, Waker>) {
-    if let Some(waker) = wakers.remove(&stream_id) {
-        waker.wake();
+    match wakers.remove(&stream_id) {
+        Some(waker) => {
+            waker.wake();
+        }
+        _ => {}
     }
 }
 
```

```diff
@@ -95,8 +95,11 @@ impl Incoming {
 impl Drop for Incoming {
     fn drop(&mut self) {
         // Implicit reject, similar to Connection's implicit close
-        if let Some(state) = self.0.take() {
-            state.endpoint.refuse(state.inner);
+        match self.0.take() {
+            Some(state) => {
+                state.endpoint.refuse(state.inner);
+            }
+            _ => {}
         }
     }
 }
```

**Comment by jieyouxu** [comment]
cc @dingxiangfei2009 @traviscross (FYI)

**Comment by zh-jq-b** [comment]
As you can see in https://github.com/rust-lang/rust/issues/133529, `cargo fix --edition --workspace`  changed 282 files (1438 insertions, 1451 deletions), most of them are unneeded `if let -> match`, while manual fix only need 19 files changed, 48 insertions(+), 37 deletions(-).

**Comment by traviscross** [comment]
Thanks for the report.  The essence of this probably duplicates:

- https://github.com/rust-lang/rust/issues/133167

So let's track this there.
