### ISSUE TITLE
Stable rustc 1.82 suggests using an unstable trait

### ISSUE THREAD

**Issue by jaskij** [rust-lang/rust#133511]
### Code

```Rust
use std::collections::HashSet;
use std::hash::Hash;
use num_traits::Bounded;

fn for_each_value_with_skip<T>(skipped: &HashSet<T>, func: impl Fn(T))
where
    T: Bounded + Hash + Eq,
{
    for v in T::min_value()..T::max_value() {
        if skipped.contains(&v) {
            continue;
        }
        func(v);
    }
}
```

### Current output

```
error[E0277]: the trait bound `T: Step` is not satisfied
  --> s7-comm/src/tests/helpers.rs:11:14
   |
11 |     for v in T::min_value()..T::max_value() {
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Step` is not implemented for `T`, which is required by `std::ops::Range<T>: IntoIterator`
   |
   = note: required for `std::ops::Range<T>` to implement `Iterator`
   = note: required for `std::ops::Range<T>` to implement `IntoIterator`
help: consider further restricting this bound
   |
9  |     T: Bounded + Hash + Eq + std::iter::Step,
   |                            +++++++++++++++++
```

### Desired output

No idea what the alternative is, if it's even possible to achieve what I want using stable Rust, but a stable compiler should not suggest using unstable features.

### Other cases

```Rust

```

### Rust Version

```Shell
$ rustc --version
rustc 1.82.0 (f6e511eec 2024-10-15)
```

### Anything else?

[Rust Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d43ed2a920a6eb70218a7fcebe15b381)

**Comment by estebank** [comment]
[Further minimized](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=49b9c2fc9978d10e5bdb36aa75a0320e):

```rust
trait Bounded {
    fn min_value() -> Self;
    fn max_value() -> Self;
}

fn print_all<T>()
where
    T: Bounded,
{
    for v in T::min_value()..T::max_value() {}
}
```

**Comment by clubby789** [comment]
I was typing this comment when the above appeared, but: further _further_ minimized 😁 
```rs
pub fn demo<T>(range: std::ops::Range<T>) {
    for _ in range {}
}
```

**Comment by cuviper** [comment]
> No idea what the alternative is, if it's even possible to achieve what I want using stable Rust, but a stable compiler should not suggest using unstable features.

I don't know if the compiler could easily suggest this, but you can make your code work by adding `where Range<T>: IntoIterator<Item = T>`.

**Comment by jaskij** [comment]
thanks @cuviper , shepmaster helped me figure it out in the discord right after I made this issue

**Comment by estebank** [comment]
We currently don't suggest complex `where` clauses, only restricting type parameters or associated types. We *could* suggest `where Range<T>: IntoIterator<Item = T>` when `T` is a type parameter... I'll prototype to get a sense of how noisy that would be.
