### ISSUE TITLE
config.example.toml: use vendor directory by default when compiling from https://static.rust-lang.org/dist/rustc-1.x.y-src.tar.xz

### ISSUE THREAD

**Issue by dilyanpalauzov** [rust-lang/rust#133664]
The file https://static.rust-lang.org/dist/rustc-1.83.0-src.tar.xz — config.example.toml contains
```toml
[build]
# Indicate whether the vendored sources are used for Rust dependencies or not.
#
# Vendoring requires additional setup. We recommend using the pre-generated source tarballs if you
# want to use vendoring. See
# https://forge.rust-lang.org/infra/other-installation-methods.html#source-code.
#vendor = false

[dist]
# Whether to vendor dependencies for the dist tarball.
#vendor = if "is a tarball source" || "is a git repository" { true } else { false }
```
My reading is that the vendor/ directory from rustc-1.83.0-src.tar.xz by default is not used.  By default, this directory should be used, when compiling from the .tar file.

**Comment by dilyanpalauzov** [comment]
… or if the default is `false` then do not include the `vendor/` directory in the stable, distributed tarball.

**Comment by bjorn3** [comment]
Omitting the `vendor` directory would make it impossible to do a vendored build when you have an offline build environment. There is something to be said for using vendoring by default when building from a tarball though, although you did still need some manual configuration to set a bootstrap compiler when you want to do an offline build anyway.

**Comment by onur-ozkan** [comment]
https://github.com/rust-lang/rust/pull/133853 should handle this. It will take effect in the next nightly release after the merge, but it will take some time for it to reach into the stable release.
