### ISSUE TITLE
asm macro assumes branch & link instructions have no side effects on aarch64/macos

### ISSUE THREAD

**Issue by leddoo** [rust-lang/rust#133683]
the following code crashes when compiled with optimizations (aarch64, macos):
```rust
extern "C" fn foo() {
    println!("hey");
}

#[inline(never)]
fn bug() {
    let mut x = 0;
    if std::hint::black_box(false) {
        x = 1;
    }

    unsafe {
        std::arch::asm! {
            "blr {f}",
            f = in(reg) foo,
        }
    }

    println!("x={x}");
}

fn main() {
    bug();
}
```

the issue is that the compiler (possibly llvm) doesn't model the side effects of the `blr` instruction correctly (the same issue occurs with regular `bl`). it neither saves the volatile registers nor the link register.

to fix this, i had to add `out("...") _,` for every register that could change. (though i don't think this is a complete workaround. eg when flags are assumed to be preserved across the asm block, since you can't `out("cpsr") _` or `out("nzcv") _`.)

while it's perhaps not entirely clear what the compiler should do in this case (presence of branch and link instructions) - perhaps a custom calling convention is used - i think assuming the platform's C abi would be a good default.

however i still classify this as a bug, as the link register isn't saved either. and `bl` of course writes to that, regardless of the calling convention.

### Meta

`rustc --version --verbose`:
```
rustc 1.83.0 (90b35a623 2024-11-26)
binary: rustc
commit-hash: 90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf
commit-date: 2024-11-26
host: aarch64-apple-darwin
release: 1.83.0
LLVM version: 19.1.1
```
(i just updated to the latest version to see if this was fixed, i was on another version before)

**Comment by hanna-kruppe** [comment]
The compiler does not (and isn’t even allowed) to look at the instructions in inline assembly and guess what they’ll do. It’s the programmer’s responsibility to specify the correct clobbers and obey all other [rules for inline assembly](https://doc.rust-lang.org/stable/reference/inline-assembly.html#rules-for-inline-assembly). Note that there is a `clobber_abi` shortcut to make this easier for inline assembly that calls functions.

**Comment by leddoo** [comment]
@hanna-kruppe oh, thanks so much! i didn't know about that document. `clobber_abi("C")` is indeed exactly what i'm looking for.
