### ISSUE TITLE
AFIT does not fulfill the required lifetime, manual RPITIT does

### ISSUE THREAD

**Issue by fasterthanlime** [rust-lang/rust#133676]
(For the casual reader: "AFIT" = Async Fn In Trait, "RPITIT" = Return Position Impl Trait In Trait")

I tried this code: ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6e399c04f9b7634d2300ab31a22483e4))

```rust
use std::{borrow::Cow, future::Future};

trait Deserializer<'s> {
    fn pop(&mut self) -> impl Future<Output = Cow<'s, str>> + '_;
}

struct Works;
struct DoesNotWork;

struct Journal {
    items: Vec<Cow<'static, str>>,
}

impl<'s> Deserializer<'s> for (Journal, Works) {
    // works
    fn pop(&mut self) -> impl Future<Output = Cow<'s, str>> + '_ {
        async move { self.0.items.pop().unwrap_or_default() }
    }
}

impl<'s> Deserializer<'s> for (Journal, DoesNotWork) {
    // doesn't work
    async fn pop(&mut self) -> Cow<'s, str> {
        self.0.items.pop().unwrap_or_default()
    }
}

fn main() {
    // good luck michael! love u
}
```

I expected to see this happen: everything typechecks.

Instead, this happened: 

```
error[E0477]: the type `impl Future<Output = Cow<'s, str>>` does not fulfill the required lifetime
  --> src/main.rs:23:5
   |
23 |     async fn pop(&mut self) -> Cow<'s, str> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: type must outlive the anonymous lifetime defined here as required by this binding
  --> src/main.rs:23:18
   |
23 |     async fn pop(&mut self) -> Cow<'s, str> {
   |                  ^^^^^^^^^
```

### Minimal repro (edit: that's a different issue, see [below](https://github.com/rust-lang/rust/issues/133676#issuecomment-2509029647))

We don't need to bring AFIT into it: ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c801e7881ac7cf541c9e5289474143a3))

```rust

use std::future::Future;

fn assert_future_unit_covariant_workaround<'s>(
    f: impl Future<Output = &'static ()> + 'static,
) -> impl Future<Output = &'s ()> + 's {
    // this works
    async move { f.await }
}

fn assert_future_unit_covariant<'s>(
    f: impl Future<Output = &'static ()> + 'static,
) -> impl Future<Output = &'s ()> + 's {
    // rustc: lifetime may not live long enough
    // returning this value requries that 's must outlive 'static
    f
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.83.0 (90b35a623 2024-11-26)
binary: rustc
commit-hash: 90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf
commit-date: 2024-11-26
host: aarch64-apple-darwin
release: 1.83.0
LLVM version: 19.1.1
```

**Comment by compiler-errors** [comment]
For the record, the minimization you provided is a totally different issue than the original issue.

**Comment by compiler-errors** [comment]
I don't expect the "minimized example" to pass (trait impls are not "covariant" over their output associated types), but I'm a bit surprised the original example doesn't pass.

**Comment by compiler-errors** [comment]
Actually, this is a valid error. 

The RPIT in the trait definition (`impl Future<Output = &'s ()> + '_`) is stronger than the RPIT in the impl (`impl Future<Output = &'s ()>`) since the one in the trait definition is essentially saying "I only capture data from the `'_` lifetime in `&self`", whereas the one in the impl makes no such guarantee. 

There's no implied outlives bound between `'s` and `'_` given by the signature of the trait, so the compiler really just can't prove what it needs to.

**Comment by fasterthanlime** [comment]
> There's no implied outlives bound between `'s` and `'_` given by the signature of the trait, so the compiler really just can't prove what it needs to.

Oh, mhh so the fix I'm looking for is just this?

```rust
use std::{borrow::Cow, future::Future};

trait Deserializer<'s> {
    fn pop<'this>(&'this mut self) -> impl Future<Output = Cow<'s, str>> + 'this
    where
        's: 'this;
}

struct Works;
struct AlsoWorks;

struct Journal {
    items: Vec<Cow<'static, str>>,
}

impl<'s> Deserializer<'s> for (Journal, Works) {
    // works
    fn pop<'this>(&'this mut self) -> impl Future<Output = Cow<'s, str>> + 'this
    where
        's: 'this,
    {
        async move { self.0.items.pop().unwrap_or_default() }
    }
}

impl<'s> Deserializer<'s> for (Journal, AlsoWorks) {
    // also work
    async fn pop<'this>(&'this mut self) -> Cow<'s, str>
    where
        's: 'this,
    {
        self.0.items.pop().unwrap_or_default()
    }
}

fn main() {
    // mhhh
}
```

**Comment by compiler-errors** [comment]
If that bound makes sense in the design of your API, then sure.

**Comment by fasterthanlime** [comment]
Fantastic! Thanks for helping me get out of this one.
