### ISSUE TITLE
download-rustc fails to detect when profiler settings differ from local settings

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#133675]
See https://github.com/rust-lang/rust/pull/133499#issuecomment-2508901283 for context: the  x86_64-gnu-aux runner builds rustc without profiling support. The CI build that is downloaded via download-rustc *does* have profiling support. This means if a test relies on profiling support, it will incorrectly pass on  x86_64-gnu-aux if download-rustc is used, only to fail later on an unrelated PR when download-rustc cannot be used.

bootstrap tries to ensure that all the settings are the same between the local configuration and the prebuilt rustc, but that does not seem to fully work.

Cc @onur-ozkan

**Comment by RalfJung** [comment]
@onur-ozkan wrote
> That PR doesn't change any contig at all? I guess we are on different points, I am talking about config.toml here.

The PR doesn't change the config indeed.   x86_64-gnu-aux locally changes its config in CI. The download-rustc logic should detect that and never use the prebuilt rustc, since it as built with a different configuration than what is being locally set up.

**Comment by onur-ozkan** [comment]
Probably, this happens because we are not checking "--set" flags yet.
