### ISSUE TITLE
`cargo +nightly fix --edition` renames declarative macro arguments

### ISSUE THREAD

**Issue by marxin** [rust-lang/rust#133647]
Based on the call for testing, I tried running the conversion on [Wild linker project](https://github.com/davidlattimore/wild). I noticed there are a couple of code transforms and the code still builds and tests are green. However, 2 macro param renames are unrelated:

```diff
--- a/linker-utils/src/elf.rs
+++ b/linker-utils/src/elf.rs
@@ -1,9 +1,9 @@
-use object::read::elf::SectionHeader;
 use object::LittleEndian;
+use object::read::elf::SectionHeader;
 use std::borrow::Cow;
 
 macro_rules! const_name_by_value {
-    ($needle: expr, $( $const:ident ),*) => {
+    ($needle: expr_2021, $( $const:ident ),*) => {
         match $needle {
             $(object::elf::$const => Some(stringify!($const)),)*
             _ => None
diff --git a/wild_lib/src/error.rs b/wild_lib/src/error.rs
index a0d0949..5407c18 100644
--- a/wild_lib/src/error.rs
+++ b/wild_lib/src/error.rs
@@ -9,7 +9,7 @@ pub type Result<T = (), E = Error> = core::result::Result<T, E>;
 /// whereas a panic just gives us a function backtrace, which is less useful.
 #[macro_export]
 macro_rules! debug_assert_bail {
-    ($e:expr, $($rest:tt)*) => {
+    ($e:expr_2021, $($rest:tt)*) => {
         if cfg!(debug_assertions) && !$e {
             anyhow::bail!($($rest)*);
         }
```

Can you please take a look?

**Comment by ionicmc-rs** [comment]
This happens when you run `cargo +nightly fix --edition`? It is likely some type of compatibility thing, it isn't justified though

**Comment by hanna-kruppe** [comment]
See explanation here https://doc.rust-lang.org/nightly/edition-guide/rust-2024/macro-fragment-specifiers.html

**Comment by marxin** [comment]
> This happens when you run `cargo +nightly fix --edition`?

Yes, please.

**Comment by ionicmc-rs** [comment]
> See explanation here https://doc.rust-lang.org/nightly/edition-guide/rust-2024/macro-fragment-specifiers.html

So, it is for compatibility with const and _ expressions?

**Comment by ionicmc-rs** [comment]
> > This happens when you run `cargo +nightly fix --edition`?
> 
> Yes, please.

So your problem is that this change is not needed, and could be breaking? You should make a PR fixing this issue
# steps to fix:
- Dedect when the expr_2021 is not needed, and keep expr as is
- Dedect when it is needed and do change it

You should make an issue about the direct problem, not just stating what happens, e.g., "cargo fix +nightly --edition unneeded expr_2021 macro fragments"

**Comment by marxin** [comment]
> So your problem is that this change is not needed, and could be breaking? You should make a PR fixing this issue

Sorry for not being more precise. Now I've read the macro-fragment-specifier and I understand the change is needed in my codebase.
Thanks for your help.
