### ISSUE TITLE
Rustdoc hangs with diesel

### ISSUE THREAD

**Issue by weiznich** [rust-lang/rust#133616]
### Code

https://github.com/diesel-rs/diesel/commit/8939fce6651a79433d3cdc7ec69e9ec9aaafea1c

```
cargo +nightly doc --manifest-path diesel/Cargo.toml --no-deps --no-default-features
```

I expected to see this happen: Documentation is build in ~5s

Instead, this happened: Rustdoc hangs indefinitely (e.g. https://github.com/diesel-rs/diesel/actions/runs/12069072552/job/33655550946 was canceled after ~6h)

### Version it worked on

It most recently worked on: Rust 1.84 (current beta)

### Version with regression

`rustc --version --verbose`:
```
rustc 1.85.0-nightly (dff3e7ccd 2024-11-26)
binary: rustc
commit-hash: dff3e7ccd4a18958c938136c4ccdc853fcc86194
commit-date: 2024-11-26
host: x86_64-unknown-linux-gnu
release: 1.85.0-nightly
LLVM version: 19.1.4

```

I've run cargo bisect-rustc to track down the PR that causes this and that points to https://github.com/rust-lang/rust/pull/133242 (386a7c7ae22a3727c6a06633212d5a95edabdd74), so cc @lcnr 

@rustbot modify labels: +regression-from-beta-to-nightly -regression-untriaged +T-rustdoc

**Comment by lcnr** [comment]
thanks for the report and the bisection :heart: looking into it xx

**Comment by weiznich** [comment]
I can confirm that diesels documentation builds again. Thanks again for the fast fix ❤
