### ISSUE TITLE
It is recommended that threads support context transfer and automatically perform clone operations

### ISSUE THREAD

**Issue by 1057105012** [rust-lang/rust#133795]
### Code

```Rust
fn main() {
    let (sx, rx) = mpsc::channel();
    let handle = thread::spawn(move |sx, rx| {
        sx.send("hello").unwrap();
    });
    handle.join().unwrap();
}
```

It is recommended that threads support context. As shown in the figure, the context automatically performs cloning operations, which can avoid code, like this     let handle = thread::spawn(move |sx, rx| {} not sx.clone(), rx.clone()。　

This operation can be understood as opening an isolation domain. Or abstract it into a more general concept. Rust allows the creation of isolated domains. All external borrowing in the isolation domain is automatically recognized as a clone operation

**Comment by theemathas** [comment]
Something similar to this is a 2024H2 project goal.
https://rust-lang.github.io/rust-project-goals/2024h2/ergonomic-rc.html
https://github.com/rust-lang/rust-project-goals/issues/107

**Comment by fmease** [comment]
I wonder if we should close this in favor of:

- https://github.com/rust-lang/rust-project-goals/issues/107
- https://github.com/rust-lang/rfcs/pull/3680
- https://github.com/rust-lang/rfcs/pull/3512

**Comment by fmease** [comment]
Closing in favor of https://github.com/rust-lang/rust-project-goals/issues/107
