### ISSUE TITLE
Add a lint for shadowed names

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#13372]
Our shadowing behavior can be somewhat surprising, especially around method lookup. A lint (allow by default) for name shadows would be incredibly useful.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#660
