### ISSUE TITLE
rustc uses wrong build tools when compiling from MSVC

### ISSUE THREAD

**Issue by dlon** [rust-lang/rust#133794]
This is due to an issue in `cc-rs`, https://github.com/rust-lang/cc-rs/issues/1308, which is a dependency in `rustc_llvm`/`rustc_codegen_ssa`. There is a fix in progress (not yet released/merged): https://github.com/rust-lang/cc-rs/pull/1310. This is a problem as of Rust 1.83.

The issue can be reproduced by creating a cargo workspace with an empty `build.rs`, creating a new MSVC project within that workspace and running `cargo build` from within the Pre-Build Event of that MSVC project. When targeting something other than the native arch, cargo/rustc will use the wrong build tools for linking or compilation.

I can provide more details/examples if necessary.

EDIT: This should be fixed on its own once `cc` is updated.

**Comment by jieyouxu** [comment]
> Thinking about it some more, part of the problem here is that cc is both a dependency of rustc (for finding link.exe + libraries) and a tool to use in build scripts. So another option would be to have some way for rustc to disable this behaviour for rustc only. Though I've not thought through the implications of that.
>
> EDIT: Ideally there would be a way to know if Cargo is building a build script.
>
> https://github.com/rust-lang/cc-rs/pull/1201#issuecomment-2509530584

**Comment by ChrisDenton** [comment]
Note this is specifically when cross-compiling with MSBuild. It shouldn't affect anything else.
