### ISSUE TITLE
2024 reserved ## breaks some proc-macros

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#133887]
The prohibition of `##` in Rust 2024 breaks some proc-macros. For example, the [`peg`](https://docs.rs/peg/latest/peg/) makes use of `##` for calling methods:

```rust
#![warn(rust_2024_guarded_string_incompatible_syntax)]
use peg::RuleResult;

trait StrExt {
    fn ident_start(&self, pos: usize) -> RuleResult<()>;
}
impl StrExt for str {
    fn ident_start(&self, pos: usize) -> RuleResult<()> {
        let Some(ch) = self[pos..].chars().next() else {
            return RuleResult::Failed;
        };
        RuleResult::Matched(pos + ch.len_utf8(), ())
    }
}

peg::parser!(grammar parser() for str {
    pub(crate) rule simple_literal_start()
        =   [ 'A'..='Z' ] / ##ident_start()
});
```

Here this will suggest to add a space to supposedly maintain compatibility with Rust 2024:

```diff
@@ -15,5 +15,5 @@
 
 peg::parser!(grammar parser() for str {
     pub(crate) rule simple_literal_start()
-        =   [ 'A'..='Z' ] / ##ident_start()
+        =   [ 'A'..='Z' ] / # #ident_start()
 });
```

However, this breaks `peg` because the peg macro [uses Jointness](https://github.com/kevinmehall/rust-peg/blob/fc7d27f0a5c52666f645bec6ec9be001f171b411/peg-macros/tokens.rs#L167-L175) to detect the `##IDENT()` syntax. When the `##` tokens are separated, they change to have `Alone` spacing.

I don't know what we can do here, other than remove the `##` reservation in 2024, but that has other implications.

### Meta

```
rustc 1.85.0-nightly (c44b3d50f 2024-12-03)
binary: rustc
commit-hash: c44b3d50fea96a3e0417e8264c16ea21a0a3fca2
commit-date: 2024-12-03
host: aarch64-unknown-linux-gnu
release: 1.85.0-nightly
LLVM version: 19.1.4
```

Tracking:

- https://github.com/rust-lang/rust/issues/123735

**Comment by traviscross** [comment]
Looks like they added that in https://github.com/kevinmehall/rust-peg/commit/1f3418c6914edb9fc7907972a7d6f044b4510a3f, though interestingly, I'm struggling to find that feature anywhere in the documentation.

Any idea how many crates are affected?

Worst case, we could just reserve `###+` instead.

**Comment by pitaj** [comment]
I guess we should have run crater before merging the `##` version of that feature. 

Anyways, it will be pretty easy to change it to reserve `#"`, `##"`, `###` instead.

**Comment by pitaj** [comment]
#133924 removes the reservation of `##`, and instead reserves `#"`, `##"`, and `###`.

**Comment by traviscross** [comment]
See the notes on this from today's lang call here:

- https://github.com/rust-lang/rust/pull/133924#issuecomment-2537444310

**Comment by traviscross** [comment]
We discussed this in the lang call today and confirmed, in light of the very much appreciated feedback from @kevinmehall, that we're comfortable proceeding as planned with the `##` reservation.
