### ISSUE TITLE
./x.py test doesn't respect --json-output for rustc error messages

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#133855]
`./x.py check` doesn't check tests for the standard library, so I have to use `./x.py test` instead when editing tests. Because `--json-output` is not respected for `./x.py test` by bootstrap, I can't get inline error messages in my ide.

**Comment by onur-ozkan** [comment]
When you run `x test`, bootstrap runs formatting with `rustfmt` which doesn't support JSON outputs. As a workaround, you can run `x test` on a specific path to skip formatting so you can use the `--json-output` flag.

**Comment by bjorn3** [comment]
I was already doing `./x.py test library/alloc`, but it still didn't show errors as json messages.

**Comment by onur-ozkan** [comment]
That's another problem then, will check that tomorrow.

**Comment by onur-ozkan** [comment]
Should be fixed with https://github.com/rust-lang/rust/pull/133875/commits/10f12388334a71e99e83efe94365563024886abe.
