### ISSUE TITLE
compiletest output newlines are weird

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#133879]
acabb5248231987ae1f0c215208d1005a5db402d

![Image](https://github.com/user-attachments/assets/17e98f9e-3c5c-4f94-97f8-49ee0e6ce059)

**Comment by matthiaskrgr** [comment]
https://github.com/rust-lang/rust/pull/133817 seems suspicious  cc @clubby789 @jieyouxu

**Comment by fmease** [comment]
Likely missed to replace some `print!(…)` with `eprint!(…)`

**Comment by clubby789** [comment]
Ah good point. Will make a followup

**Comment by jieyouxu** [comment]
Revert PR: https://github.com/rust-lang/rust/pull/133892
