### ISSUE TITLE
Clarify `black_box()` docs when passed a unit-returning function

### ISSUE THREAD

**Issue by BD103** [rust-lang/rust#133923]
### Location

The API documentation for [`black_box()`](https://doc.rust-lang.org/stable/std/hint/fn.black_box.html).

### Summary

Please see https://github.com/rust-lang/rust-clippy/issues/12707 for more context!

I believe the API docs for `black_box()` are unclear when passed a unit-returning function. For example:

```rust
let x: () = black_box(thread::sleep(...));
```

The `black_box()` call makes the returned value treated as volatile, which is pointless because it is a zero-sized type. The above code is equivalent[^0] to just:

[^0]: Mostly equivalent. `black_box()` does prevent optimizations from `call` to `jmp` instructions, even when the function returns unit. See [Godbolt](https://godbolt.org/z/6dnhT65z7). Are there any other possible optimizations that may make this meaningful?

```rust
let x: () = thread::sleep(...);
```

This is unclear in the documentation for `black_box()`, though. The docs make it seem like the actual call to `thread::sleep(...)` will be barred from optimizations, which isn't true. As [pointed out by y21](https://github.com/rust-lang/rust-clippy/issues/12707#issuecomment-2076531747), constant-folding and other optimizations are still present:

```rust
// This...
let y = black_box(42 * 42);
// ...gets compiled to this:
let y = black_box(1764);
```

I propose that the docs be updated to mention that `black_box()` makes the value appear volatile to the compiler, and does not affect the argument passed to it.

**Comment by saethlin** [comment]
> I propose that the docs be updated to mention that `black_box()` makes the value appear volatile to the compiler, and does not affect the argument passed to it.

Those mean exactly the same thing.

But I agree that the docs should be improved, and I think an example of misuse like from y21 is probably the way to make the point that it's a normal function, not a different kind of syntax that obscures the *expression* between the parens.

**Comment by workingjubilee** [comment]
Confirming: this is a library documentation issue.
