### ISSUE TITLE
Test failures in `tests/ui/panics` on `aarch64-apple-darwin`

### ISSUE THREAD

**Issue by Zalathar** [rust-lang/rust#133997]
Using an unmodified `profile = "compiler"` build on aarch64 macOS (14.7.1), I see the following tests fail from `./x test tests/ui/panics`:

```
failures:
    [ui] tests/ui/panics/issue-47429-short-backtraces.rs
    [ui] tests/ui/panics/runtime-switch.rs
    [ui] tests/ui/panics/short-ice-remove-middle-frames-2.rs
    [ui] tests/ui/panics/short-ice-remove-middle-frames.rs
```

All of the failure diffs look something like this:

```
diff of run.stderr:

1	thread 'main' panicked at $DIR/issue-47429-short-backtraces.rs:24:5:
2	explicit panic
3	stack backtrace:
-	   0: std::panicking::begin_panic
+	   0: begin_panic<&str>
5	   1: issue_47429_short_backtraces::main
6	note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
7	


The actual run.stderr differed from the expected run.stderr.
```

I see the same failures with `--stage=1` and `--stage=2`.

---

Not sure if this is a test output normalization problem, or an actual bug.

Discussion elsewhere indicates that this might be related to #123244.

**Comment by Zalathar** [comment]
I'm seeing the same failures with all of:

```
rust.new-symbol-mangling = true
rust.new-symbol-mangling = false
# rust.new-symbol-mangling not set
```

**Comment by jieyouxu** [comment]
I cannot repro on x86_64 linux, tagging aarc64 + apple unless someone else can repro this on a different environment.

**Comment by Zalathar** [comment]
I can also confirm that for me the tests pass before #123244, and fail after it.

**Comment by jieyouxu** [comment]
#123244 added some additional normalizations, FTR

**Comment by Mark-Simulacrum** [comment]
We probably(?) need some extra normalization in the tests. The symbol in question (begin_panic) is probably found a bit differently by backtrace on this platform?

That said, we run [these tests in CI](https://github.com/rust-lang/rust/blob/master/src/ci/github-actions/jobs.yml#L404) for this platform, so it's not clear whether it's some local delta as well. Perhaps you have e.g. lld enabled or some other optimization setting that's not set in CI?

**Comment by madsmtm** [comment]
I can reproduce it on my machine too (also using macOS 14.7.1), on both Aarch64 and x86_64 (using Rosetta), so that's at least weak evidence that it's not something environment specific.

Not sure what the underlying issue is yet though.

**Comment by Zalathar** [comment]
I can make the failures go away by setting `rust.debuginfo-level = 1`, and then make them appear again by setting `rust.debuginfo-level = "line-tables-only"`, which is the compiler profile default.

That helps to explain why it doesn't show up on CI.
