### ISSUE TITLE
Typo in E0751

### ISSUE THREAD

**Issue by ionicmc-rs** [rust-lang/rust#133985]
here is E0571
```Shell
There are both a positive and negative trait implementation for the same type.

Erroneous code example:

trait MyTrait {}
impl MyTrait for i32 { }
impl !MyTrait for i32 { } // error!

Negative implementations are a promise that the trait will never be implemented for the given types. Therefore, both cannot
exists at the same time.
^^^^^^
`exist`
```
there is probably some better template to use here

**Comment by saethlin** [comment]
> there is probably some better template to use here

Nah. You've clearly communicated the problem in a way that a human can digest. That's all we need.

**Comment by ionicmc-rs** [comment]
> Nah. You've clearly communicated the problem in a way that a human can digest. That's all we need.
Well I mean it's basically just a correction, should be pretty easy to fix

**Comment by LuanOldCode** [comment]
Hi! I've already fixed the typo in the error message for E0751. The message originally said "exists" and I corrected it to "exist" to ensure proper grammar.
I’ve already pushed the changes to my fork, and the PR is ready for review.

Link: [133993](https://github.com/rust-lang/rust/pull/133993)
