### ISSUE TITLE
term: windows console handling is incomplete

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#13400]
The [Windows Console API](http://msdn.microsoft.com/en-us/library/windows/desktop/ms682073%28v=vs.85%29.aspx) is large and complex. libterm only handles using stdout as a console.

Honestly nobody cares about the windows console API. This work probably belongs in https://github.com/klutzy/rust-windows

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/term#13
