### ISSUE TITLE
Rust 1.83.0 Sync with dyn Traits Regression

### ISSUE THREAD

**Issue by IGN-Styly** [rust-lang/rust#134014]
### Code
Problematic Version: rustc 1.83.0 (90b35a623 2024-11-26)
Works on rust rustc 1.82.0 (f6e511eec 2024-10-15)

Using my [lib](https://github.com/GrandEngineering/enginelib), here's a short example causing the segfault. 
[Issue Demo](https://github.com/GrandEngineering/issue) Requires Submodule!
SegFault
```
Thread 1 "server" received signal SIGSEGV, Segmentation fault.
alloc::sync::{impl#29}::deref<dyn enginelib::event::EventHandler, alloc::alloc::Global> (self=0x555555d77db0)
    at /home/styly/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/sync.rs:2179
2179	        &self.inner().data
```
Rust 1.83 seems just leak. #128778 may be the cause but i can't seem to compile rust at all.

**Comment by compiler-errors** [comment]
What is the regression here? I don't think you mentioned what the problem actually *is*.

**Comment by IGN-Styly** [comment]
Compilation happens fine but a segfault happens, which didn't happen on previous versions.

**Comment by IGN-Styly** [comment]
@compiler-errors I Just made my [lib](https://github.com/GrandEngineering/enginelib) oss, and updated issue to have code to recreate the bug.

**Comment by apiraino** [comment]
@IGN-Styly can you please update your report adding how do you build your library. That would help in reproducing more quickly the issue. Thank you.

**Comment by jieyouxu** [comment]
More specifically, can you make your example self-contained, e.g. in a repo, so that we can confirm what we try to run is the same as what you try to run?

**Comment by IGN-Styly** [comment]
yes will do asap

**Comment by cyrgani** [comment]
Can reproduce, working on minimizing this.

@rustbot label: -S-needs-repro -S-needs-info

**Comment by cyrgani** [comment]
https://github.com/cyrgani/issue-134014 is a reduction that still keeps the original behavior of not segfaulting on 1.82 but on 1.83 and needs no external crates. However, removing the simple `println!("cursed");` line in the repro causes it to segfault on 1.82 as well.

Additionally interesting is that the original unmodified code segfaults on 1.80 and below too, but not on 1.81.

**Comment by IGN-Styly** [comment]
is it haunted?

**Comment by workingjubilee** [comment]
I am removing the regression status because based on @cyrgani's report it seems very likely that what happened here is difficult to classify as a regression.
