### ISSUE TITLE
List re-exports of a symbol in the documentation for that symbol

### ISSUE THREAD

**Issue by Meyermagic** [rust-lang/rust#13414]
I find myself accidentally re-importing things already in prelude, or using a deeper, explicit, path for something re-exported elsewhere pretty often.

When navigating the documentation via search, I'll jump directly to a sub-module or symbol, and import and use it without noticing I already have, say, std::io imported. Then I'll be using fs::File and, say, io::BufferedReader, when I could have cleaner import paths.

Overall, I think it might help new users become familiar with the standard library layout. The main downside I see is unnecessary clutter in the documentation pages, and obviously more code to maintain.

A lint might also work, although there are definitely cases where "use the shortest import path" probably isn't what you want.

**Comment by steveklabnik** [comment]
Triage: I don't think Rustdoc currently has a way of understanding a 'canonical' source for something...

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by steveklabnik** [comment]
Triage: there's been no substantial comments on this in the last four years; I don't think this is going to be implemented. Closing!
