### ISSUE TITLE
`./x test --skip` is sensitive to path separators on Windows

### ISSUE THREAD

**Issue by ChrisDenton** [rust-lang/rust#134198]
Currently the following will not skip any tests on Windows even though the test path exists

```
./x test ui --skip tests/ui/traits/fn-pointer/bare-fn-no-impl-fn-ptr-99875.rs
```

This is because of using `/` instead of `\` for the path separators. Ideally bootstrap should handle this.

Additionally it would be nice if `--skip` errored (or at least warned) if the given path didn't match anything.

**Comment by jieyouxu** [comment]
Reopening because this is a bit more tricky, as Steps may register arbitrary aliases and there is also logic that accepts matching prefix/suffixes for tests (see https://github.com/rust-lang/rust/pull/134843 for more details).

**Comment by onur-ozkan** [comment]
The fix doesn't have anything to do with aliases.

**Comment by jieyouxu** [comment]
Indeed, please disregard
