### ISSUE TITLE
Incorrect `Result` reference in `core::error`.

### ISSUE THREAD

**Issue by bjoernager** [rust-lang/rust#134169]
### Location

`core::error`

### Summary

The docs for `core::error` contain the following passage:

> The following are the primary interfaces of the error system and the responsibilities they cover:
>
> * `Result` (Propagating, Reacting)
> * The `Error` trait (Reporting)
> 
> ...

The entry for `Result` links to the docs for `core::fmt::Result` even though it should actually point to `core::result::Result`. The docs for `std::error`, however, do correctly link to `std::result::Result` in this case, despite using the same markup.

This issue is present on stable, beta, and nightly branches.

**Comment by bjoernager** [comment]
My first though was to change the link in `/library/core/src/error.md` from ```[`Result`]``` to ```[`Result`](crate::result::Result)```. Would this suffice?

**Comment by clubby789** [comment]
If that fixes the issue, please feel free to submit a PR

**Comment by clubby789** [comment]
The specific cause here, by the way, is that `core/src/error.rs` begins:
```rs
#![doc = include_str!("error.md")]
#![stable(feature = "error_in_core", since = "1.81.0")]

use crate::any::TypeId;
use crate::fmt::{Debug, Display, Formatter, Result};
```
So [`Result`] is resolved as the imported `fmt::Result`. The version in `std` does not import this, and uses the regular `Result` from the prelude

**Comment by bjoernager** [comment]
Yes, I suspected that was the case. It appears I somehow missed that `use` statement.
