### ISSUE TITLE
`error[E0310]: the parameter type 'T' may not live long enough` on `'static` type

### ISSUE THREAD

**Issue by Daniel-Aaron-Bloom** [rust-lang/rust#134362]
I tried this code:

```rust
fn foo<F: 'static>(){}

trait AlwaysStatic {
    type Output: 'static;
}

impl <T: ?Sized> AlwaysStatic for T {
    type Output = ();
}

type Alias<T> = <T as AlwaysStatic>::Output;
struct Wrapper<T>(T);
struct AssocWrapper<T>(<T as AlwaysStatic>::Output);
struct AliasWrapper<T>(Alias<T>);

fn bar<T>() {
    foo::<()>();                                    // Call with literal type, works
    foo::<<T as AlwaysStatic>::Output>();           // Call with associated type, works
    foo::<Alias<T>>();                              // Call with type alias, works
    foo::<Wrapper<<T as AlwaysStatic>::Output>>();  // Call with wrapped assoc type, works
    foo::<Wrapper<Alias<T>>>();                     // Call with wrapped type alias, works
    
    foo::<AssocWrapper<T>>();                       // Call with wrapped assoc type, fails
    foo::<AliasWrapper<T>>();                       // Call with wrapped type alias, fails
}
```

I expected to see this happen: clean compile for all cases.

Instead, this happened:
```
error[E0310]: the parameter type `T` may not live long enough
```

### Meta

`rustc --version --verbose`:
```
rustc 1.83.0 (90b35a623 2024-11-26)
binary: rustc
commit-hash: 90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf
commit-date: 2024-11-26
host: x86_64-unknown-linux-gnu
release: 1.83.0
LLVM version: 19.1.1
```

**Comment by theemathas** [comment]
I think that this is intended behavior. If a generic type parameter of a struct isn't `'static`, then the struct also isn't `'static`, regardless of whether the fields of the struct are `'static` or not.

**Comment by compiler-errors** [comment]
> That seems pretty counterintuitive being that the fields of a struct are what determine it's [Variance](https://doc.rust-lang.org/reference/subtyping.html#variance).

Variance has nothing to do with outlives like `Ty: 'lifetime`. Please refer to [RFC 1214](https://rust-lang.github.io/rfcs/1214-projections-lifetimes-and-wf.html#simple-outlives-rules) for a somewhat technical dive on how outlives works. For nominal types such as `AssocWrapper<T>` and `AliasWrapper<T>`, the following relationship holds: `Struct<T>: 'lifetime` if `T: 'lifetime`.

> Also, since you can make constants of both AssocWrapper and AliasWrapper, and the [reference doc on constants](https://doc.rust-lang.org/reference/items/constant-items.html) states that constants "must have a 'static lifetime", it implies they do have a 'static lifetime.

Those are const items, not associated consts. Associated consts definitely do not need to be `'static`.

-----

> I think that this is intended behavior. 

This is indeed intended behavior, and not something we can change in the language now.
