### ISSUE TITLE
libc::{input_absinfo, input_event} aren't available on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [rust-lang/rust#134304]
The evdev-sys-0.2.5 crate fails on FreeBSD 14.1:
```
error[E0432]: unresolved imports `libc::input_absinfo`, `libc::input_event`
 --> /wrkdirs/usr/ports/sysutils/syngesture/work/syngesture-2.0.0/cargo-crates/evdev-sys-0.2.5/src/lib.rs:6:16
  |
6 | pub use libc::{input_absinfo, input_event};
  |                ^^^^^^^^^^^^^  ^^^^^^^^^^^ no `input_event` in the root
  |                |
  |                no `input_absinfo` in the root
```

rust-1.83.0

**Comment by saethlin** [comment]
Yup.

**Comment by yurivict** [comment]
@VorpalBlade 

```libc::input_absinfo``` is documented [here](https://docs.rs/libc/latest/libc/struct.input_absinfo.html) as a general Rust feature.

Why is this issue an evdev-sys issue if this general feature is missing for FreeBSD?

**Comment by VorpalBlade** [comment]
https://docs.rs/libc/latest/x86_64-unknown-freebsd/libc/?search=input_absinfo (doing the search with the appropriate target tuple selected from the drop down a the top, it defaults to showing linux) shows that this doesn't exist on FreeBSD. From a quick Google I can't find if this is something that FreeBSD even supports. There is no man page for this on either Linux or FreeBSD. 

* If it does, then it is a libc issue and the issue belongs in https://github.com/rust-lang/libc
* if it doesn't, then it is as I suggested before it is a issue with evdev-sys, and they may or may not even support FreeBSD. 

The libc crate is just a direct mapping of functions and structures available in the underlying platform's C library, it is not a "rust feature".

**Comment by yurivict** [comment]
The ```input_absinfo``` structure exists in FreeBSD as well, see [here](https://cgit.freebsd.org/src/tree/sys/dev/evdev/input.h#n58).

Could you please add these missing structures to the Rusts's ```libc``` crate?

**Comment by VorpalBlade** [comment]
The correct place to open an issue about that would be https://github.com/rust-lang/libc
