### ISSUE TITLE
Typo in 'panic_location' lang item

### ISSUE THREAD

**Issue by ionicmc-rs** [rust-lang/rust#134347]
### Code

```Rust
#[lang = "panic_location"]
impl MyType { /* ... */ }
```

### Current output

```Shell
`panic_location` lang item must be applied to a struct
attribute should be applied to a struct, not a implementation block
```

### Desired output

```Shell
`panic_location` lang item must be applied to a struct
attribute should be applied to a struct, not an implementation block
                                              ^
```

### Other cases

```Rust

```

### Rust Version

```Shell
rustc 1.85.0-nightly (21fe748be 2024-12-11)
binary: rustc
commit-hash: 21fe748be15271ea5804e0507cd699b675efe038
commit-date: 2024-12-11
host: x86_64-unknown-linux-gnu
release: 1.85.0-nightly
LLVM version: 19.1.5
```

### Anything else?

im sorry for the person who will have to make PR about changing one letter

**Comment by naskya** [comment]
I guess the article “a” is hardcoded?

https://github.com/rust-lang/rust/blob/f2b91ccbc27cb06369aa2dd934ff219e156408a8/compiler/rustc_passes/messages.ftl#L420-L422

**Comment by Noratrieb** [comment]
Thanks for the report. As pointed out, this is not just a simple typo fix but would require additionally complexity to handle correctly.
But this is a diagnostic for lang items, which are not intended to be user-facing, so we prefer not adding additional complexity to the error messages. Therefore I'm closing this.
