### ISSUE TITLE
error: the compiler unexpectedly panicked. this is a bug.

### ISSUE THREAD

**Issue by colojayce** [rust-lang/rust#134495]
### Code

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>
[rustc-ice-2024-12-19T06_10_17-60954.txt](https://github.com/user-attachments/files/18193395/rustc-ice-2024-12-19T06_10_17-60954.txt)

**Comment by oli-obk** [comment]
Please fill in the placeholders when opening an issue.
