### ISSUE TITLE
Why does the type parameter that would be instantiated as a type whose destructor is const make the argument non-const?

### ISSUE THREAD

**Issue by xmh0511** [rust-lang/rust#134449]
````rust
const fn show<T>(t:T){}

fn main(){
    show(0);
}
````
This example won't be compiled and the compiler will complain that
```
error[E0493]: destructor of `T` cannot be evaluated at compile-time
``` 

If the parameter type `T` is changed to `i32`, the example is okay. However, it is still even not compiled when no actual call to `show` is written. Currently, it seems that the compiler cannot know what `T` would be in the context of the signature, so it conservatively assumes that `T` always has a non-const destructor. How to specify that `T` can have a const destructor?

**Comment by fmease** [comment]
On stable the options are:

* `const fn show<T: Copy>(_: T) {}`
* `const fn show<T>(_: &T)` {}

On nightly additionally:

* `const fn show<T: ~const std::marker::Destruct>(_: T) {}` which requires the experimental features `const_destruct` and `const_trait_impl`

**Comment by xmh0511** [comment]
> On stable the options are:
> 
>     * `const fn show<T: Copy>(_: T) {}`
> 
>     * `const fn show<T>(_: &T)` {}
> 
> 
> On nightly additionally:
> 
>     * `const fn show<T: ~const std::marker::Destruct>(_: T) {}` which requires the experimental features `const_destruct` and `const_trait_impl`

`const fn show<T>(_: &T) {}` changes the semantic the original example has

**Comment by fmease** [comment]
Indeed, and `Copy` is more restrictive.
