### ISSUE TITLE
Tests for rustdoc search indices

### ISSUE THREAD

**Issue by lifthrasiir** [rust-lang/rust#13444]
The generation of search index has some delicate corner cases (e.g. #11391) that will benefit from tests. We at least need equivalence tests which compare a generated search index from given file with the expected one.

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by QuietMisdreavus** [comment]
Thanks to https://github.com/rust-lang/rust/pull/47250, this exists now! Right now it's bound to the standard library's search index, but so far that's been good enough to test the problem cases we've had.
