### ISSUE TITLE
Build and test for Linux/ARM64

### ISSUE THREAD

**Issue by odidev** [rust-lang/rust#134494]
## Description  
For aarch64 platform, I have built "Rust" from source.  
## Steps   
Following STEPS (https://www.rust-lang.org/tools/install) were used for the building and installation: 
```
curl --proto '=https' --tlsv1.
sSf https://sh.rustup.rs | sh
sudo apt install rustup -y
rustup install 1.9.0
rustup default 1.9.0
```
## Outcome  
To validate that the build was successful we ran "rustc --version" command.  
All this information is also added to ARM Dashboard Software Ecosystem Dashboard for Arm (https://www.arm.com/developer-hub/ecosystem-dashboard/).

**Comment by lqd** [comment]
What is the issue you’re encountering?

**Comment by lqd** [comment]
I see you’ve opened the exact same issue in other popular projects, so I’m going to close this as spam. Rest assured we build and test for linux and aarch64.
