### ISSUE TITLE
Provides a syntax for expressing all behavioral operations with opening and closing. Such as locks, streams, temporary clients and temporary thread pools, etc., expressed by the interface Resource

### ISSUE THREAD

**Issue by 1057105012** [rust-lang/rust#134595]
### Code

```Rust
fn handle_client(client_id: usize, mut stream: TcpStream, client: Arc<Mutex<HashMap<usize, TcpStream>>>){
    let mut buffer = [0, 1024];
    loop {
        match stream.read(&mut buffer) {
            Ok(0) => {
                info!("Client {} disconnected", client_id);
                break;
            }
            Ok(n)=>{
                let data = &buffer[0..n];
                info!("Server: data received from the client: {:?}", data);
                let mut clients_guard = client.lock().unwrap();

            }
        }
    }
}
```

### Current output

```Shell
nothing
```

### Desired output

```Shell
nothing
```

### Rationale and extra context

I think this syntax is easier to understand and less likely to cause problems than the above. For example, the above lock code, if replaced with the current syntax, becomes 

```Rust
with client.lock() {

}
```
//Out of range, automatically released

Assuming there is a lock resource, the pseudo code is as follows:
lock is defined as
```Rust
impl Resource for lock{
open(){
// lock
}
close(){
// unlock
}
}

```
### Other cases

```Rust

```

### Rust Version

```Shell
rustc 1.82.0 (f6e511eec 2024-10-15)
```

**Comment by workingjubilee** [comment]
Well.

I don't really recommend repeatedly locking a mutex in a loop if you don't have to. Have you considered using a channel?

**Comment by workingjubilee** [comment]
Otherwise, we usually ask that this sort of thing go elsewhere, like say https://internals.rust-lang.org/ because it isn't an _issue_. There's nothing to _solve_ here, or even to track the evolution of, at least not yet. It does not concern the Rust repo, in other words, until the language team says they want it to happen and the compiler team says they're on board.

As such, I am closing this as non-actionable.
