### ISSUE TITLE
Binding to C library (quadmath) returns wrong results with rustc versions >v1.81.0

### ISSUE THREAD

**Issue by apelloni** [rust-lang/rust#134500]
I was using bindings to the GCC `__float128` from the quadmath library and notice that with recent version of cargo (>v1.81.0)
Some function are now broken. Here is a minimal code

<details><summary>F128.c</summary>

```c
#include <quadmath.h>
#include <stdint.h>
#include <stdio.h>
//typedef __float128 _float128;
extern int quadmath_snprintf(char *s, size_t size, const char *format, ...);

typedef union _Wrapper {
  __float128 value;
  unsigned __int128 dat;
  char dat_alt[16];
} __attribute__((aligned(16))) Wrapper;

Wrapper f64_to_f128(double a) {
  Wrapper d;
  d.value = (__float128)a;
  return d;
}

float f128_to_f32(Wrapper a) { return (float)a.value; }
double f128_to_f64(Wrapper a) { return (double)a.value; }

unsigned char gteq(Wrapper a, Wrapper b) {
  return (unsigned char)(a.value >= b.value);
}

unsigned char lteq(Wrapper a, Wrapper b) {
  return (unsigned char)(a.value <= b.value);
}
```

</details>

<details><summary>lib.rs</summary>

```rust
extern crate libc;
extern crate num_traits;

#[link(name = "F128", kind = "static")]
extern "C" {
    pub fn f64_to_f128(num: *const f64) -> F128;

    pub fn gteq(lhs: F128, rhs: F128) -> u8;
    pub fn lteq(lhs: F128, rhs: F128) -> u8;
}

#[repr(C, align(16))]
#[derive(Clone, Copy)]
pub struct F128(pub(crate) [u8; 16]);

impl F128 {
    pub fn from_f64(num: f64) -> Self {
        let f;
        unsafe {
            f = f64_to_f128(&num);
        }
        f
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn check_cmp() {
        let a = F128::from_f64(1.5);
        let b = F128::from_f64(3.0);

        let lte = unsafe { lteq(a, b) };
        let gte = unsafe { gteq(a, b) };

        assert_eq!((lte != 0, gte != 0), (true, false));
    }
}
```
</details>

<details><summary>build.rs</summary>

```rust
extern crate cc;

fn main() {
    cc::Build::new()
        .flag("-lquadmath")
        .file("src/F128.c")
        .compile("libF128.a");
   //println!(r"cargo:rustc-flags=-l quadmath");
}
```
</details>

<details><summary>Cargo.toml</summary>

```toml
[package]
name = "f128_quadmath"

[dependencies]
libc = "0.2.168"

[build-dependencies]
cc = "1.2.4"
```
</details>

### Behaviour:

- **I expected to see this happen**:  this test is supposed to pass given 1.5 < 3.0

- **Instead, this happened**:  with rust-1.81.0 and below everything works as expected. With later versions it fails.

I've also tried to link the C library created by Rust to a C code, and all the comparisons behave as expected, further pointing to a problem with the rust binding.

I also had someone try ion their Mac with `Apple M2 Pro` and it works as expected also with the latest stable version `1.83.0`

### Meta

`rustc --version --verbose`:
```
rustc 1.83.0 (90b35a623 2024-11-26)
binary: rustc
commit-hash: 90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf
commit-date: 2024-11-26
host: x86_64-unknown-linux-gnu
release: 1.83.0
LLVM version: 19.1.1
```

Tested with all the version in  `rustup show`:
```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/andrea/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
beta-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
1.81.0-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.83.0 (90b35a623 2024-11-26)
```

No backtrace ( it only reports the explicit panic from the test )

**Comment by purplesyringa** [comment]
```c
Wrapper f64_to_f128(double a) {
  Wrapper d;
  d.value = (__float128)a;
  return d;
}
```

```rust
pub fn f64_to_f128(num: *const f64) -> F128;
```

This looks wrong. Why is the argument a `double` in C and a `double*` in Rust?

**Comment by apelloni** [comment]
> Wrapper f64_to_f128(double a) {
>   Wrapper d;
>   d.value = (__float128)a;
>   return d;
> }
> pub fn f64_to_f128(num: *const f64) -> F128;
> This looks wrong. Why is the argument a `double` in C and a `double*` in Rust?

Was because I was following the notation form the rust library that I'm using (https://github.com/jkarns275/f128).
The imported values are all correct as one can check by adding to the C code for ltge together with uncommenting the line in build.rs
```C
unsigned char lteq(Wrapper a, Wrapper b) {
  size_t size = 128;
  char s[size];


  // Print problem in f128
  quadmath_snprintf(s, 128, "%.32Qg", a.value);
  printf("%s <= ", s);
  quadmath_snprintf(s, 128, "%.32Qg", b.value);
  printf("%s ? ", s);
  // Result of a<=b
  printf("%d\n", a.value <= b.value);

  //a.value = (f128)10.5;
  //b.value = (f128)3;

  // Check and compare through casting into other types
  printf("%f <= %f ? ", f128_to_f64(a), f128_to_f64(b));
  printf("%b | ", f128_to_f64(a) <= f128_to_f64(b));
  printf("%b (f64|f128)\n", a.value <= b.value);

  // Check operators
  printf("(a<=b) && (b>=a) : %d && %d\n", a.value <= b.value, b.value >= a.value);
  printf("(a>=b) && (b<=a) : %d && %d\n", a.value >= b.value, b.value <= a.value);
  printf("------------------------\n");

  return (unsigned char)(a.value <= b.value);
}
```

This shows that the numbers are indeed what one would expect but the operator `<=` and `>=` are now wrong (depending on the cargo version)

**Comment by workingjubilee** [comment]
@apelloni this is by-value: https://github.com/jkarns275/f128/blob/e60de395f0d6454c1dc546b87f06a6358425b6b6/f128_internal/src/ffi.rs#L46

**Comment by purplesyringa** [comment]
> Was because I was following the notation form the rust library that I'm using

That library defines `fn f64_to_f128(x: f64) -> f128;`. You're confusing something.

**Comment by workingjubilee** [comment]
@apelloni Your program has UB, you have misdeclared a signature. We do not detect or warn about this, because the Rust compiler understands Rust, not C. You need to be very careful to not induce UB, or you needed to use automated tools like [bindgen](https://github.com/rust-lang/rust-bindgen).

Do not use this:
```rust
#[link(name = "F128", kind = "static")]
extern "C" {
    pub fn f64_to_f128(num: *const f64) -> F128;
}
```

Instead use this:

```rust
#[link(name = "F128", kind = "static")]
unsafe extern "C" {
    pub fn f64_to_f128(num: f64) -> F128;
}
```

The addition of `unsafe` to the `extern "C"` does nothing, technically, but it makes it clear that _merely declaring the bindings_ is `unsafe`. If you get the types wrong, it's UB.

**Comment by workingjubilee** [comment]
A quick check of C99 and a few ABIs later...

@apelloni Yeah, I am pretty sure you shouldn't pun between a union and a struct like that. It may work, but I don't recommend it, as whether it does is dependent on the platform and whether all involved compilers are feeling cooperative today. You should declare a union with the same variants if you want to be sure its ABI will match.

**Comment by jieyouxu** [comment]
Closing as this is not actionable.
