### ISSUE TITLE
Integrating an input function

### ISSUE THREAD

**Issue by Obcodelab** [rust-lang/rust#134686]
Just started learning rust and noticed there isn't exactly a function that takes user input so I did this
I wanted to know if there is any downside to having something like this?
![Image](https://github.com/user-attachments/assets/1c632503-ada5-44e1-85ee-8f8d4a3931f0)

**Comment by clubby789** [comment]
A similar API was proposed [here](https://github.com/rust-lang/rfcs/pull/3196) some time ago

**Comment by jieyouxu** [comment]
For general Rust discussions (not specific to the Rust projects in this repo), consider asking on [URLO](https://users.rust-lang.org/) or in the [Community Discord](https://discord.gg/rust-lang) or on [zulip](https://rust-lang.zulipchat.com/#narrow/channel/122651-general). The rust-lang/rust issue tracker is meant for specific issues pertaining to the language, compiler, rustdoc, and other projects living in this repo, but is not meant for general Rust discussions.
