### ISSUE TITLE
x86_64 msvc: warning: rustc_llvm@0.0.0: Inherited flag "/Oy-" is not supported by the currently used CC

### ISSUE THREAD

**Issue by jieyouxu** [rust-lang/rust#134657]
On my native `x86_64-pc-windows-msvc` environment, I am observing the warnings:

```
   Compiling rustc_ast_passes v0.0.0 (X:\repos\rust\compiler\rustc_ast_passes)
   Compiling rustc_expand v0.0.0 (X:\repos\rust\compiler\rustc_expand)
   Compiling rustc_builtin_macros v0.0.0 (X:\repos\rust\compiler\rustc_builtin_macros)
warning: rustc_llvm@0.0.0: Inherited flag "/Oy-" is not supported by the currently used CC
warning: rustc_llvm@0.0.0: Inherited flag "/Oy-" is not supported by the currently used CC
warning: rustc_llvm@0.0.0: Inherited flag "/Oy-" is not supported by the currently used CC
warning: rustc_llvm@0.0.0: Inherited flag "/Oy-" is not supported by the currently used CC
warning: rustc_llvm@0.0.0: Inherited flag "/Oy-" is not supported by the currently used CC
warning: rustc_llvm@0.0.0: Inherited flag "/Oy-" is not supported by the currently used CC
   Compiling rustc_infer v0.0.0 (X:\repos\rust\compiler\rustc_infer)
   Compiling rustc_mir_dataflow v0.0.0 (X:\repos\rust\compiler\rustc_mir_dataflow)
   Compiling rustc_metadata v0.0.0 (X:\repos\rust\compiler\rustc_metadata)
   Compiling rustc_pattern_analysis v0.0.0 (X:\repos\rust\compiler\rustc_pattern_analysis)
```

This is probably related to the `cc` bumps we done recently... FYI @clubby789 :ferrisClueless: I have not tried to bisect this.

**Comment by clubby789** [comment]
Yeah these warnings come from cc trying to pass through the equivalent flags (observed while debugging the recent bump). cc probes them and emits this warning if it can't pass the flags through.

Not sure if this is necessarily something to worry about - maybe cc could provide more options to configure this behaviour

**Comment by clubby789** [comment]
> /Oy enables frame-pointer omission and /Oy- disables omission. In x64 compilers, /Oy and /Oy- are not available.

Hmm, maybe CC should be applying some more heuristics to these inherited flags

**Comment by jieyouxu** [comment]
Yeah, I just wanted to track it in case it's problematic.

**Comment by clubby789** [comment]
Oops - probably want to keep this open until it makes it into a release that we can pull in.
