### ISSUE TITLE
ARM Linux cross-compiling images are no longer available

### ISSUE THREAD

**Issue by rami3l** [rust-lang/rust#134612]
Hello from the rustup team!

Coming from [Rustup v1.28.0 release blocked by Docker pull error](https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/Rustup.20v1.2E28.2E0.20release.20blocked.20by.20Docker.20pull.20error), we've noticed that our recent release CI has failed with essentially the following errors (rustup's cross-compiling CI workflows are relying on rust's images to function correctly):

```
ERROR: failed to solve: rust-aarch64-unknown-linux-musl: failed to resolve source metadata for docker.io/library/rust-aarch64-unknown-linux-musl:latest: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

```
ERROR: failed to solve: rust-arm-unknown-linux-gnueabi: failed to resolve source metadata for docker.io/library/rust-arm-unknown-linux-gnueabi:latest: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

Looking at our [mapping](https://github.com/rust-lang/rustup/blob/730ee37e1d2cabf58b538d25b7c52524415c1761/ci/fetch-rust-docker.bash#L25-L26), these two names point to the same image in this repo:
```
  aarch64-unknown-linux-musl)      image=dist-arm-linux ;;
  arm-unknown-linux-gnueabi)       image=dist-arm-linux ;;
```

Since this issue is ARM Linux-exclusive, I'm convinced that ~~https://github.com/rust-lang/rust/pull/133809~~ https://github.com/rust-lang/rust/pull/133902 is the direct cause of this issue.

Is it possible to revert the relevant Dockerfile deletion(s) or at least keep the old Dockerfile(s) for a while? We can migrate immediately after we're granted access to ARM64 Linux CI runners (but not just yet).

Many thanks in advance! 🙇 

(cc @Kobzol)

**Comment by Urgau** [comment]
Already reverted in https://github.com/rust-lang/rust/pull/134564

**Comment by Kobzol** [comment]
I suppose that https://github.com/rust-lang/rust/pull/133902 willlo as eed arevnert?

**Comment by rami3l** [comment]
> Already reverted in [#134564](https://github.com/rust-lang/rust/pull/134564)

@Urgau Oh, probably I gave you the wrong reference number; @Kobzol was right, I guess.

**Comment by Kobzol** [comment]
https://github.com/rust-lang/rust/pull/134614
