### ISSUE TITLE
compiletest: 'known directive' check does not account for suites

### ISSUE THREAD

**Issue by clubby789** [rust-lang/rust#134739]
https://github.com/rust-lang/rust/pull/134738

A few UI tests uses 'forbid-output' despite it (currently) only working for incremental tests. This is because the known directive check doesn't account for the supported suites; this makes me suspect there might be a few more noop directives in our test suite

**Comment by jieyouxu** [comment]
It's less noop directive *in general*, it's moreso that most(?) directives are only supported for a subset of test suites. The known directive check is a very crude and stopgap way to block *new* unknown (like, at all) directives from being added, but does not try to fix the preexisting problem of a directive being unsupported in certain suites.

**Comment by jieyouxu** [comment]
Part of https://github.com/rust-lang/rust/issues/131425.

Anyway, I think we should fix this by having directive registration explicitly declare what test suites they *do* support.

**Comment by clubby789** [comment]
Closing in favour of #128058
