### ISSUE TITLE
Rustdoc regression: stable items reexported from unstable modules appear unstable

### ISSUE THREAD

**Issue by tgross35** [rust-lang/rust#134702]
Previously, stable items that are reexported from unstable modules (to stable modules) showed up as stable, which is correct because the user has a way to access them. However, since 1.83, they show up as unstable. This is accurate in one sense as they can't be stably accessed via the displayed path but is misleading because the types themselves are actually stably usable.

As an example, here is the most recent documentation from the most recent 1.83, as well as nightly https://doc.rust-lang.org/1.83.0/std/ffi/c_str/struct.FromBytesUntilNulError.html:

<img width="727" alt="Image" src="https://github.com/user-attachments/assets/de51f01d-b04c-4bca-a9f9-79774651ddb7" />

From 1.82 https://doc.rust-lang.org/1.82.0/std/ffi/c_str/struct.FromBytesUntilNulError.html: 

<img width="750" alt="Image" src="https://github.com/user-attachments/assets/877d2adf-c9a6-4f66-a870-e4e44200ef55" />

And then 1.69, before it moved modules https://doc.rust-lang.org/1.69.0/core/ffi/struct.FromBytesUntilNulError.html:

<img width="719" alt="Image" src="https://github.com/user-attachments/assets/1c5c765f-0544-439b-b1bc-c3b11ebc4624" />

There was a related issue in the near past with method signatures https://rust-lang.zulipchat.com/#narrow/channel/266220-t-rustdoc/topic/Moving.20to.20a.20module.20breaks.20stability.20indicators

**Comment by tgross35** [comment]
One related thing: even though the type can be accessed stably, copying the path via the button gives a path that is only usable with unstable e.g. `std::ffi::c_str::FromBytesUntilNulError`. It may be nice to instead provide the fully stable path for anything that falls into this category (i.e. `std::ffi::FromBytesUntilNulError`).

**Comment by GrigorenkoPV** [comment]
![Image](https://github.com/user-attachments/assets/99e86f41-a02c-4e30-8b09-083ddd1233ac)

For example, #134692 moves `Mutex` and `MutexGuard` to a new `#[unstable]` `pub mod` `std::sync::poison`.
They are then reexported with a `#[stable]` `#[doc(inline)]` `pub use` in `std::sync`.

However, a ``[`Mutex::lock`]`` link in the doc for `MutexGuard` gets resolved as `std::sync::poison::Mutex::lock` and not `std::sync::Mutex::lock` (same with `try_lock` in the screenshot above).

**Comment by notriddle** [comment]
The main `ffi` module shows the types as re-exported, instead of inlined.

https://doc.rust-lang.org/1.83.0/std/ffi/index.html#reexports

> ## Re-exports
>
> <span><pre>pub use self::c_str::[FromBytesUntilNulError](https://doc.rust-lang.org/1.83.0/std/ffi/c_str/struct.FromBytesUntilNulError.html);
> pub use self::c_str::[FromBytesWithNulError](https://doc.rust-lang.org/1.83.0/std/ffi/c_str/struct.FromBytesWithNulError.html);
> pub use self::c_str::[FromVecWithNulError](https://doc.rust-lang.org/1.83.0/std/ffi/c_str/struct.FromVecWithNulError.html);
> pub use self::c_str::[IntoStringError](https://doc.rust-lang.org/1.83.0/std/ffi/c_str/struct.IntoStringError.html);
> pub use self::c_str::[NulError](https://doc.rust-lang.org/1.83.0/std/ffi/c_str/struct.NulError.html);</pre>

To fix that, the `use` statements need marked with `#[doc(inline)]`.
