### ISSUE TITLE
Casts to `*const !` and `*mut !` are allowed

### ISSUE THREAD

**Issue by ionicmc-rs** [rust-lang/rust#134783]
I tried this code:

```rust
#![feature(never_type)]

fn main() {
    let never = &10 as *const i32 as *const !;
    let x: i32 = unsafe { *never };
    foo(x);
}
fn foo(var: i32) {
    println!("{var}");
}
```

(here another example)
```rust
fn main() {
    let x = 8 as *const !;
    println!("{x}"); 
}
```
(both have same results)

I expected to see this happen: An error about an illegal cast

Instead, this happened: the program crashed with SIGILL (illegal instruction)

### Meta

`rustc --version --verbose`:
```
rustc 1.85.0-nightly (9e136a30a 2024-12-19)
binary: rustc
commit-hash: 9e136a30a965bf4e63f03095c57df7257bf96fd6
commit-date: 2024-12-19
host: x86_64-unknown-linux-gnu
release: 1.85.0-nightly
LLVM version: 19.1.6
```

{no backtrace}

For more information, here is the output:
```sh
fish: Job 1, 'cargo run' terminated by signal SIGILL (Illegal instruction)
```

**Comment by ionicmc-rs** [comment]
i removed needs triage on accident

@rustbot label needs-triage

**Comment by hanna-kruppe** [comment]
The pointer cast isn’t illegal and doesn’t cause any Undefined Behavior (UB) or crash by itself. Your second example doesn’t compile but just printing the pointer with `{x:p}` is fine. Reading from that pointer to create a *value* of type `!` is UB, that’s what’s happening in the line `let x: i32 = unsafe { *never }` (first it creates a `!` value and then it gets coerced to `i32`). Not doing that is the programmer’s responsibility when using `unsafe`. Note that:

1. Pointer casts + dereferencing is only one of many ways to unsafely construct a value of uninhabited types. Trying to forbid this pointer cast wouldn’t help and would rule out some legitimate use cases.
2. This is not really specific to `!`, you can make the same mistake with `enum Never {}` on stable, you just have to throw in an extra `match *never {}` if you want the coercion to `i32`. 
3. There’s also countless other ways to cause UB by pointer casting and reading memory as another *inhabited* type. For example, `let x: i32 = *(&0u8 as *const u8 as *const i32);` is UB for reading out of bounds and possibly also for being unaligned.

**Comment by ionicmc-rs** [comment]
okay, so it isnt illegal on its own, and for some reason the second example compiled for me

**Comment by WaffleLapkin** [comment]
As @hanna-kruppe said, there is nothing specific to the never type here, really, and the cast itself is 100% valid.

Dereferencing pointers is `unsafe` and in your first example you are not fulfilling some of the requirements for it (namely, the pointer does not point to properly initialised value of type `!`, there is no properly initialised value of type `!`).

Closing this, since there is no bug.
