### ISSUE TITLE
add an useful `File::append()` utility

### ISSUE THREAD

**Issue by liigo** [rust-lang/rust#134755]
// open an existing or create a new file for append data.
// very useful when writing log files.
```rs
pub fn append<P: AsRef<Path>>(path: P) -> io::Result<File> {
    OpenOptions::new().append(true).create(true).open(path.as_ref())
}
```

- `open_append()` doesn't make sense, since it maybe creates new file
- `create_append()` doesn't make sense, since it maybe open existing file

Since we‘re adding [`open_buffered`](https://doc.rust-lang.org/nightly/std/fs/struct.File.html#method.open_buffered) and [`create_buffered`](https://doc.rust-lang.org/nightly/std/fs/struct.File.html#method.create_buffered), I think we also have a chance to add `File::append`. `File::options().append(true).create(true).open(path.as_ref())` is too long and requires thinking more on flags in detail.

**Comment by jieyouxu** [comment]
Hi @liigo thanks for the feature request. This is an API request, so you should instead [open an API Change Proposal (ACP)](https://github.com/rust-lang/libs-team/issues/new?assignees=&labels=api-change-proposal%2C+T-libs-api&template=api-change-proposal.md&title=%28My+API+Change+Proposal%29) at https://github.com/rust-lang/libs-team/issues.

**Comment by liigo** [comment]
@jieyouxu ACP link: https://github.com/rust-lang/libs-team/issues/512

**Comment by jieyouxu** [comment]
Thanks! I'm going to close this issue on the rust-lang/rust side in favor of https://github.com/rust-lang/libs-team/issues/512, since this is not actionable for *this* issue tracker.
