### ISSUE TITLE
`std::num::Checked{Add,Sub,Mul,Div}` should have type parameters

### ISSUE THREAD

**Issue by lifthrasiir** [rust-lang/rust#13510]
The corresponding `std::ops` traits have both the type of right hand side operand and the type of result, while `Checked*` traits do not (and always assume that both operands and result have the same type). There is no real reason to make `Checked*` traits behave differently from `std::ops` traits, and having them as is hampers advanced uses of operator overloading: for example, if the scalar type (e.g. `DateTime`) and difference type (e.g. `Duration`) are distinct from each other then the current scheme wouldn't work at all.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/num#59
