### ISSUE TITLE
Add ability for rustdoc to use custom CSS.

### ISSUE THREAD

**Issue by SiegeLord** [rust-lang/rust#13659]
Proposed API:

`--custom-css MAIN_CSS [AUX_CSS...]`

`MAIN_CSS` would be copied as `main.css` into the output directory and linked to by all the HTML files. The set of other CSS files specified by `AUX_CSS` will be copied into the output directory, but not linked to. The intention is for the `MAIN_CSS` to `@import` them (like is currently done to `normalize.css`).

Alternatively, they could all be linked in the HTML files in some specified order (the internet suggests linking is better than `@import`).

**Comment by steveklabnik** [comment]
This is already possible with `--markdown-css`.
