### ISSUE TITLE
Seed RNGs with a uniform type

### ISSUE THREAD

**Issue by SiegeLord** [rust-lang/rust#13663]
I think it would be convenient to have a uniform way to reseed all RNGs. Currently, each RNG could potentially use (and often does so in practice) a different seed type for the `SeedableRng` trait implementation. I propose that trait to have the following two methods (and an associated function) added:

~~~rust
/// Number of bits needed to completely reseed the generator
fn get_seed_size(&self) -> uint;

/// Reseeds the RNG using an array of u64's, padded with 0's if needed.
/// If more data is given than could be used, it is first reduced using a hash.
fn reseed(&mut self, &[u64]);
fn from_seed(&[u64]) -> Self;
~~~

The current methods could either be removed, or renamed to `reseed_exact` etc. It currently appears that some RNGs already do something similar to what the proposed functions do, while others (e.g. `XorShiftRng`) require the complete state.

**Comment by steveklabnik** [comment]
@huonw is planning on stabilizing rand soon, so this concern might be part of that.

**Comment by huonw** [comment]
RFC https://github.com/rust-lang/rfcs/pull/722, the current design there is to not provide `SeedableRng` in `std` and so punt this question out of the standard library to avoid having to consider it in detail for 1.0.

**Comment by cybergeek94** [comment]
@huonw @steveklabnik Should this be closed now that `rand` is out-of-tree?

**Comment by vks** [comment]
I think the issue should rather be moved there.

**Comment by steveklabnik** [comment]
filed as https://github.com/rust-lang-nursery/rand/issues/80
