### ISSUE TITLE
confusing error with 'extern crate'

### ISSUE THREAD

**Issue by comex** [rust-lang/rust#13672]
a.rs:

    #![crate_type = "dylib"]
    pub trait Foo {}

b.rs:

    mod c;
    fn main() {}

c.rs:

    extern crate a;
    use a::Foo;

Ran `rustc a.rs`, then `rustc b.rs -L.`.  The result is a confusing error:

    c.rs:2:9: 2:10 error: unresolved import. maybe a missing `extern crate a`?
    c.rs:2     use a::Foo;

rustc 0.11-pre-nightly (d35804e 2014-04-18 00:01:22 -0700)

**Comment by frewsxcv** [comment]
*visiting for triage*

The error message is slightly different now with the latest rust

```
/t/triage $ cat a.rs
#![crate_type = "dylib"]
pub trait Foo {}
```
```
/t/triage $ cat b.rs
mod c;
fn main() {}
```
```
/t/triage $ cat c.rs
extern crate a;
use a::Foo;
```
```
/t/triage $ rustc a.rs
/t/triage $ rustc b.rs -L.
c.rs:2:5: 2:6 error: unresolved import `a::Foo`. Did you mean `self::a`?
c.rs:2 use a::Foo;
           ^
error: aborting due to previous error
```
```
/t/triage $ rustc --version
rustc 1.0.0-nightly (1d00c545e 2015-01-30 19:56:34 +0000)
```

**Comment by Gankro** [comment]
Looks fixed to me.
