### ISSUE TITLE
Hidden methods still appear in trait implementation docs

### ISSUE THREAD

**Issue by chris-morgan** [rust-lang/rust#13698]
Take, for example, `TotalEq`:

``` rust
pub trait TotalEq: Eq {
    // FIXME #13101: this method is used solely by #[deriving] to
    // assert that every component of a type implements #[deriving]
    // itself, the current deriving infrastructure means doing this
    // assertion without using a method on this trait is nearly
    // impossible.
    //
    // This should never be implemented by hand.
    #[doc(hidden)]
    #[inline(always)]
    fn assert_receiver_is_total_eq(&self) {}
}
```

As is proper, [the `TotalEq` docs make no mention of this hidden method `assert_receiver_is_total_eq`](http://static.rust-lang.org/doc/master/std/cmp/trait.TotalEq.html).

But now refer to an example like [the `TotalEq` impl for `Option`](http://static.rust-lang.org/doc/master/std/option/enum.Option.html#method.assert_receiver_is_total_eq)! Lo! `assert_receiver_is_total_eq` is shown there.

It shouldn't be.

**Comment by mahkoh** [comment]
This is broken again.

**Comment by mitsuhiko** [comment]
Still happens, example down here: http://mitsuhiko.github.io/redis-rs/redis/enum.ErrorKind.html

**Comment by SimonSapin** [comment]
It looks like this is happening again in https://github.com/rust-lang/rust/pull/51147#issuecomment-392693570.

**Comment by kzys** [comment]
@SimonSapin Do you remember what was the issue on #51147? Seems `SliceIndex`'s Rustdoc no longer shows any hidden methods/traits.

https://doc.rust-lang.org/nightly/std/slice/trait.SliceIndex.html

**Comment by SimonSapin** [comment]
In #51147 we wanted to hide `SliceIndex`’s methods, but couldn’t because the impl docs had broken links (and the linkchecker wouldn’t let us land that PR).

**Comment by kzys** [comment]
I see. Hiding `get()`, `get_mut()`, `get_unchecked()`, ... and all of them?

**Comment by SimonSapin** [comment]
Yes, these methods are permanently-unstable implementation details of methods like `[T]::get`. The trait itself is only stable so that code that calls `[T]::get` can itself be generic in the same way. See discussion at https://github.com/rust-lang/rust/issues/35729#issuecomment-377784884.

**Comment by kzys** [comment]
Probably these need to strip methods that are inherited from hidden methods.

https://github.com/rust-lang/rust/blob/master/src/librustdoc/passes/strip_hidden.rs
https://github.com/rust-lang/rust/blob/master/src/librustdoc/passes/mod.rs#L191

**Comment by jrvidal** [comment]
@GuillaumeGomez I was looking into this as a way of better understanding rustdoc internals. Do you plan to tackle it?

**Comment by GuillaumeGomez** [comment]
Go ahead! I have a lot of other things to do. :)

**Comment by jrvidal** [comment]
@GuillaumeGomez suggests that making `#[doc(hidden)]` automatically hide the corresponding items in trait implementations is undesirable, since it is not reversible and the implementer could easily hide the items manually.

If that's the case, should this issue be closed?

**Comment by GuillaumeGomez** [comment]
From my point of view, it should. Let's close it now and if someone wants to debate, I'll let the comments open.
