### ISSUE TITLE
rename `std::num::Zero` and `std::num::One`

### ISSUE THREAD

**Issue by liigo** [rust-lang/rust#13699]
`std::num::Zero` means neither "the number 0"(noun) nor "zero a value"(verb).
`std::num::One` does not means "the number 1" (or once).
They are both ambiguous and confusing. There are many comments here:
https://mail.mozilla.org/pipermail/rust-dev/2014-April/009432.html

`std::num::Zero` should be renamed to `std::num::AddIdentity`,
`std::num::One` should be renamed to `std::num::MulIdentity`,
to match their original meanings.

(Or put them in a separate module: `std::num::identity::{Zero, One}`.)
(Or we remove them entirely from std.)

**Comment by steveklabnik** [comment]
This kind of change would go through the RFC process today.  Please open one if you're interested in persuing this change!

**Comment by liigo** [comment]
For ones who comes here:
At the end, `Zero` and `One` was deprecated since 1.11, with a reason 'no longer used', in https://github.com/rust-lang/rust/pull/34530. Jun, 2016.
It takes over a year to make decisions about them. CC https://github.com/rust-lang/rust/issues/27739.

**Comment by matt2xu** [comment]
> It takes over a year to make decisions about them.

I wanted to "Add my reaction" to your post, but I cannot say whether it should be :confused: or :smile: ^^
