### ISSUE TITLE
Redesign the Rust's logo

### ISSUE THREAD

**Issue by liigo** [rust-lang/rust#13719]
(I'm sorry if I get something wrong.)

The current (old) Rust's logo with a big 'R', let people sometimes think of the [R programming language][r], whose logo has a big 'R' too.

I'd like to see a new Rust logo with the essence/spirit of metal and rust (and more).

[r]: http://en.wikipedia.org/wiki/R_(programming_language)

![R-lang-logo](http://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Rlogo.png/200px-Rlogo.png "R's logo")

![rust-lang-logo](http://www.rust-lang.org/logos/rust-logo-128x128-blk-v2.png "Rust's logo")

**Comment by steveklabnik** [comment]
At this point, I'm not sure we're going to change the logo, so I'm going to give this a close. Thanks!
