### ISSUE TITLE
Cannot link to third-party Rust libraries in the same prefix `rustc` was installed to

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#13733]
I'm working on a repository for the Paludis package manager, and Rust has trouble with the standard system paths.

```
<snip for clarity>
root@jurily ~# cave contents dev-rust/sdl
/usr/lib64/libsdl-e351513a-0.3.2.so

root@jurily ~# cave contents dev-lang/rust
/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-3574b280-0.11-pre.so
/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libstd-aad93cea-0.11-pre.so
/usr/lib64/liblibc-3574b280-0.11-pre.so
/usr/lib64/libstd-aad93cea-0.11-pre.so
```

With standard invocation:

```
rustc --opt-level=3 --out-dir /var/tmp/paludis/build/dev-rust-sprocketnes-scm/work/sprocketnes-scm -L /var/tmp/paludis/build/dev-rust-sprocketnes-scm/work/sprocketnes-scm nes.rs
nes.rs:11:1: 11:18 error: can't find crate for `sdl`
nes.rs:11 extern crate sdl;
          ^~~~~~~~~~~~~~~~~
```

So then I had the wonderful idea to feed it `$LDPATH` manually:

``` sh
erustc () { # happy fun times
    OIFS="$IFS"
    IFS=":"
    local LDHACK=""
    local LDTOKENS=""
    read -a LDTOKENS <<< "${LDPATH}"
    for i in "${LDTOKENS[@]}"; do
        LDHACK="$LDHACK -L $i"
    done

    IFS="$OIFS"
    edo rustc --opt-level=3 --out-dir "${WORK}" -L "${WORK}" "${@}" ${LDHACK}
}
```

---

```
rustc --opt-level=3 --out-dir /var/tmp/paludis/build/dev-rust-sprocketnes-scm/work/sprocketnes-scm -L /var/tmp/paludis/build/dev-rust-sprocketnes-scm/work/sprocketnes-scm nes.rs -L /usr/local/lib -L /usr/lib64 -L /lib64 -L /usr/lib64/nss -L /usr/lib64/qt4 -L /usr/lib64/mysql -L /usr/lib64/xulrunner
nes.rs:1:1: 1:1 error: multiple dylib candidates for `std` found
nes.rs:1 //
         ^
nes.rs:1:1: 1:1 note: candidate #1: /usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libstd-aad93cea-0.11-pre.so
nes.rs:1 //
         ^
nes.rs:1:1: 1:1 note: candidate #2: /usr/lib64/libstd-aad93cea-0.11-pre.so
nes.rs:1 //
         ^
nes.rs:1:1: 1:1 error: multiple dylib candidates for `libc` found
nes.rs:1 //
         ^
nes.rs:1:1: 1:1 note: candidate #1: /usr/lib64/liblibc-3574b280-0.11-pre.so
nes.rs:1 //
         ^
nes.rs:1:1: 1:1 note: candidate #2: /usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-3574b280-0.11-pre.so
nes.rs:1 //
```

Lose-lose. I assume there are valid reasons for this, but it's still confusing:
1. Why are there multiple _shared_ libraries installed? If `rustc` needs its own set, wouldn't it make sense to link them statically?
2. Why can't `rustc` figure out which one to use?
3. Would it actually make a difference? They're the same version, right down to the hash.
4. If I put everything next to the "good" libstd, will it keep working? Can I count on that path to not change?

I could use a completely different directory of course, but that's an ugly workaround and would likely hurt upstream chances.

**Comment by eternaleye** [comment]
A note that may be relevant, considering the original motivation for this was an Exheres repository: Exherbo, the distro that uses that package format (package manager is Paludis), has transitioned to a multiarch setup in which each target's libraries live under `/usr/$TRIPLE/lib`, `/usr/host` is a symlink to `/usr/$HOST`, and both `/lib` and `/usr/lib` are symlinks to `/usr/host/lib` - the way `-L` works (a manner unlike `-L` in any other language/compiler I've encountered...) is deeply incompatible with such a filesystem layout.

**Comment by aidanhs** [comment]
This is biting me with a musl-enabled build of rust installed to a custom prefix.

Musl itself and musl-rust are installed in $PREFIX, but rustc does not search $PREFIX/lib for libc.a. `strace` tells me rustc checks these locations:
```
/home/aidanhs/Desktop/rust/musldist/lib/rustlib/x86_64-unknown-linux-musl/lib/libc.a
/tmp/tmp.FsbyOoqA0o/rustful/.rust/lib/x86_64-unknown-linux-musl/libc.a
/tmp/tmp.FsbyOoqA0o/rustful/lib/x86_64-unknown-linux-musl/libc.a
```

As a result, anything trying to do `#[link(name = "c", kind = "static")]` (as rust libc does for musl-rust) says "cannot find native static library c [...]". Adding a -L to rustc fails for the reasons covered in the rest of this issue.

Though in my case I think `-L` would be a hack and the 'correct' way to do it is either via LIBRARY_PATH or compiling the path in.

**Comment by martinraison** [comment]
I'm having the same issue. I can't link a C library installed in `/usr/local/lib` on OSX.

**Comment by Chuongv** [comment]
I am not sure if helps, but I had similar issues with linking a C library to `usr/local/lib`. I the approaches above, even creating a build script but had the same problems. Turns out that my mac didn't have `LIBRARY_PATH` defined. Once I had it defined as `usr/local/lib`, the `-L` was being passed correctly.

To find out if `LIBRARY_PATH` is defined do:
`echo $LIBRARY_PATH`. If it's not, run
`export LIBRARY_PATH="/usr/local/lib"`

**Comment by brson** [comment]
Assuming this is still a problem. Any updates?

**Comment by steveklabnik** [comment]
Triage: it's been over a year since the last comment asking for updates; the last real comment here is from 2015. The original reporter has deleted their GitHub account. As such, I'm going to give this a close; if anyone is still seeing this issue, please let me know and I'm happy to re-open.
