### ISSUE TITLE
Document how to implement CLike for using EnumSet

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#13752]
According to the tests, this code needed to use `collections::enum_set::EnumSet`:

```rust
    #[repr(uint)]
    enum Foo {
        A, B, C
    }

    impl CLike for Foo {
        fn to_uint(&self) -> uint {
            *self as uint
        }

        fn from_uint(v: uint) -> Foo {
            unsafe { cast::transmute(v) }
        }
    }
```

If it is indeed needed, that should be documented.

Also, it would be nice to not have to duplicate this impl for every enum type that one wants to use with `EnumSet`.

**Comment by Gankro** [comment]
EnumSet is not in std lib anymore.
