### ISSUE TITLE
Test builds should default to a different executable name

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#13760]
Packaging papercut.

``` bash
    erustc "${MAIN}" 
    # Force the output name to avoid overwriting the one we just compiled
    expecting_tests && erustc --test -o "${WORK}/test-${CID}" "${MAIN}"
```

**Comment by steveklabnik** [comment]
Triage: no change that i'm aware of.

**Comment by Mark-Simulacrum** [comment]
Is this a backwards compatible change? Technically, it's likely that people rely on the current behavior, though it isn't quite ideal.

**Comment by Mark-Simulacrum** [comment]
Closing as a backwards incompatible change -- though I think it would be desirable to change things here, it seems like too small a gain given that we'd be breaking backwards compat.
