### ISSUE TITLE
Installing Rust on Windows via the installer may lead to linking failures/conflicts

### ISSUE THREAD

**Issue by pcwiek** [rust-lang/rust#13784]
At first glance, it looks like a PATH-related mingw issue. I may be wrong though, happy investigating! :)

Steps:
1. Install mingw first (or at least something that adds `ld` to PATH), in my case it came with [Haskell 2013.2.0.0 for Windows](http://www.haskell.org/platform/download/2013.2.0.0/HaskellPlatform-2013.2.0.0-setup.exe).
2. Install [Rust from the nightly Windows installer](http://static.rust-lang.org/dist/rust-nightly-install.exe)
3. Create any Rust program ('Hello world' is sufficient) and try to compile it.
4. Witness the aftermath.

----

    F:\Rust\TestProj>rustc test.rs
    error: linking with `gcc` failed: exit code: 1
    note: gcc arguments: '-m32' '-LC:\Program Files (x86)\Rust\bin\rustlib\i686-pc-m
    ingw32\lib' '-o' 'test' 'test.o' '-lmorestack' '-shared-libgcc' '-Wl,--enable-lo
    ng-section-names' 'C:\Program Files (x86)\Rust\bin\rustlib\i686-pc-mingw32\lib\l
    ibnative-83574243-0.11-pre.rlib' 'C:\Program Files (x86)\Rust\bin\rustlib\i686-p
    c-mingw32\lib\libstd-aad93cea-0.11-pre.rlib' 'C:\Program Files (x86)\Rust\bin\ru
    stlib\i686-pc-mingw32\lib\liblibc-3574b280-0.11-pre.rlib' '-LF:\Rust\TestProj\.r
    ust' '-LF:\Rust\TestProj' '-Wl,-Bdynamic' '-lws2_32' '-lgcc_s' '-lcompiler-rt'
    note: C:/Program Files (x86)/Haskell Platform/2013.2.0.0/mingw/bin/ld.exe: Dwarf
     Error: Offset (3168) greater than or equal to .debug_abbrev size (972).
    C:\Program Files (x86)\Rust\bin\rustlib\i686-pc-mingw32\lib\libstd-aad93cea-0.11
    -pre.rlib(r-rustrt-rust_builtin.o):rust_builtin.c:(.text+0x1d0): undefined refer
    ence to `_gmtime32'
    C:/Program Files (x86)/Haskell Platform/2013.2.0.0/mingw/bin/ld.exe: Dwarf Error
    : found dwarf version '0', this reader only handles version 2, 3 and 4 informati
    on.
    C:\Program Files (x86)\Rust\bin\rustlib\i686-pc-mingw32\lib\libstd-aad93cea-0.11
    -pre.rlib(r-rustrt-rust_builtin.o):rust_builtin.c:(.text+0x230): undefined refer
    ence to `_localtime32'
    C:/Program Files (x86)/Haskell Platform/2013.2.0.0/mingw/bin/ld.exe: Dwarf Error
    : found dwarf version '20039', this reader only handles version 2, 3 and 4 infor
    mation.
    C:\Program Files (x86)\Rust\bin\rustlib\i686-pc-mingw32\lib\libstd-aad93cea-0.11
    -pre.rlib(r-rustrt-rust_builtin.o):rust_builtin.c:(.text+0x41c): undefined refer
    ence to `_mktime32'
    C:/Program Files (x86)/Haskell Platform/2013.2.0.0/mingw/bin/ld.exe: Dwarf Error
    : found dwarf version '8259', this reader only handles version 2, 3 and 4 inform
    ation.
    C:\Program Files (x86)\Rust\bin\rustlib\i686-pc-mingw32\lib\libstd-aad93cea-0.11
    -pre.rlib(r-rustrt-rust_builtin.o):rust_builtin.c:(.text+0x44c): undefined refer
    ence to `_mktime32'
    collect2: ld returned 1 exit status

    error: aborting due to previous error

**Comment by steveklabnik** [comment]
Is this still happening for people?

**Comment by vadimcn** [comment]
@pcwiek, Windows installer is standalone now, can you please verify that it fixed your problem?

**Comment by pcwiek** [comment]
@vadimcn Can't seem to reproduce the same issue anymore; seems to be fixed for me!

**Comment by steveklabnik** [comment]
Great! If it still happens for anyone else, please let me knowl

**Comment by shankar2105** [comment]
I have the same problem

   Compiling sdl2 v0.0.28 (file:///G:/Shankar/Project/Maidsafe/Rust/practise/rust-sdl2)
error: linking with `gcc` failed: exit code: 1
note: "gcc" '"-Wl,--enable-long-section-names"' '"-fno-use-linker-plugin"' '"-Wl,--nxcompat"' '"-static-libgcc"' '"-m64"' '"-L"' '"C:\\Program Files (x86)\\Rust-nightly\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib"' '"-o"' '"G:\\Shankar\\Project\\Maidsafe\\Rust\\practise\\rust-sdl2\\target\\examples\\demo.exe"' '"G:\\Shankar\\Project\\Maidsafe\\Rust\\practise\\rust-sdl2\\target\\examples\\demo.o"' '"-Wl,--gc-sections"' '"G:\\Shankar\\Project\\Maidsafe\\Rust\\practise\\rust-sdl2\\target\\libsdl2-39afa0645ddf0ae4.rlib"' '"G:\\Shankar\\Project\\Maidsafe\\Rust\\practise\\rust-sdl2\\target\\deps\\librand-1a237188f461fee5.rlib"' '"G:\\Shankar\\Project\\Maidsafe\\Rust\\practise\\rust-sdl2\\target\\deps\\libsdl2-sys-37248979ab973f09.rlib"' '"G:\\Shankar\\Project\\Maidsafe\\Rust\\practise\\rust-sdl2\\target\\deps\\liblibc-8d21de95f4de7169.rlib"' '"G:\\Shankar\\Project\\Maidsafe\\Rust\\practise\\rust-sdl2\\target\\deps\\libbitflags-518ea12e21428edd.rlib"' '"C:\\Program Files (x86)\\Rust-nightly\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd-4e7c5e5c.rlib"' '"C:\\Program Files (x86)\\Rust-nightly\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcollections-4e7c5e5c.rlib"' '"C:\\Program Files (x86)\\Rust-nightly\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\libunicode-4e7c5e5c.rlib"' '"C:\\Program Files (x86)\\Rust-nightly\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\librand-4e7c5e5c.rlib"' '"C:\\Program Files (x86)\\Rust-nightly\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\liballoc-4e7c5e5c.rlib"' '"C:\\Program Files (x86)\\Rust-nightly\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\liblibc-4e7c5e5c.rlib"' '"C:\\Program Files (x86)\\Rust-nightly\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcore-4e7c5e5c.rlib"' '"-L"' '"G:\\Shankar\\Project\\Maidsafe\\Rust\\practise\\rust-sdl2\\target"' '"-L"' '"G:\\Shankar\\Project\\Maidsafe\\Rust\\practise\\rust-sdl2\\target\\deps"' '"-L"' '"C:\\Program Files (x86)\\Rust-nightly\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib"' '"-L"' '"G:\\Shankar\\Project\\Maidsafe\\Rust\\practise\\rust-sdl2\\.rust\\bin\\x86_64-pc-windows-gnu"' '"-L"' '"G:\\Shankar\\Project\\Maidsafe\\Rust\\practise\\rust-sdl2\\bin\\x86_64-pc-windows-gnu"' '"-Wl,--whole-archive"' '"-Wl,-Bstatic"' '"-Wl,--no-whole-archive"' '"-Wl,-Bdynamic"' '"-lSDL2"' '"-lSDL2"' '"-lws2_32"' '"-luserenv"' '"-lcompiler-rt"'

**Comment by kwebi** [comment]
I use the Cygwin, and the gcc..etc were installed, because the net error, I didn't install Mingw64 successfully, 
this is my error information:
``
➜  web-app git:(master) ✗ cargo run
   Compiling web-app v0.1.0 (file:///E:/Lessons/Rust/project/web-app)
error: linking with `gcc` failed: exit code: 1
  |
  = note: "gcc" "-Wl,--enable-long-section-names" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-nostdlib" "-m64"  .......

**Comment by jesse996** [comment]
same problem,i use msys2
