### ISSUE TITLE
Cannot select on DuplexStream

### ISSUE THREAD

**Issue by polyfractal** [rust-lang/rust#13788]
It appears impossible to select over a DuplexStream channel.  Select's [handle method](https://github.com/mozilla/rust/blob/master/src/libstd/comm/select.rs#L116) only accepts Receivers, and there is no way to access the Receiver channel in a DuplexStream either.

I'd be happy to put in a PR, but I'm unsure the best course of action.  One of these needs to be done:

- Add a getter to obtain the DuplexStream's Receiver
- Make the DuplexStream struct members public

And then there is a question how the user interacts with Select.  Should there be:

- Add a new handle method which accepts DuplexStreams (`handle_duplex`?)
- Make the existing handle more generic and check type at runtime (seems like a bad idea)
- Don't change anything, make the user pass in the DuplexStream's Receiver by hand

**Comment by steveklabnik** [comment]
DuplexStream is gone, partially for this reason.
