### ISSUE TITLE
`rustc --crate-type=dylib -o name` produces `name.exe` on windows

### ISSUE THREAD

**Issue by klutzy** [rust-lang/rust#13794]
```
$ touch empty.rs
$ rustc empty.rs --crate-type=dylib -o empty
$ ls
empty.exe
empty.rs
```

It produces `empty` if crate type is rlib or staticlib.

**Comment by vadimcn** [comment]
Not sure this is wrong, actually.   This is clearly a compatibility feature for the benefit of Unix-y shell scripts.   On Unix executable files are designated by a permissions bit, but on Windows - by extension.   If Windows `ld` were to create an extension-less file, it couldn't be executed.

**Comment by steveklabnik** [comment]
This doesn't appear to happen today; at least, not with the MSVC toolchain, which is the recommended one. With no comments since 2015, including one that says this may not be a bug, I'm going to give this a close. If this is in error, please let me know!
