### ISSUE TITLE
Rustdoc render inconsistency

### ISSUE THREAD

**Issue by lifthrasiir** [rust-lang/rust#13804]
There are a number of inconsistencies in the current rustdoc renders, including:

* The method listing for structs/enums has a different look from that for traits. For example, the method heading for structs/enums is bolder than that for traits (`font-weight: 600` vs. `font-weight: 400`).
* Several non-generated headings (e.g. "Required Methods" in the trait) don't have a link to self.
* Why is the stability index rendered as `<a>` instead of `<span>`?
* Item listings in the module should have one-line descriptions, but sometimes descriptions span more than one line (e.g. [`std::kinds::marker`](http://static.rust-lang.org/doc/master/std/kinds/marker/index.html)). I suspect that's because `code` has `white-space: pre-wrap` attribute everywhere; `.docblock.short code { white-space: nowrap; }` seems to solve that (not sure).

**Comment by steveklabnik** [comment]
I believe that all of these have been addressed with @adrientetar 's PRs. Please open more issues if not!
