### ISSUE TITLE
`make install` error on Windows

### ISSUE THREAD

**Issue by mrec** [rust-lang/rust#13810]
Trying to build latest on Win7-64, on a freshly-installed MSYS. The previous `make check-fast` mostly worked, with only one failure. (See #13439 - @klutzy has already commented on that.)

    tmp/dist/rust-0.11-pre-i686-pc-mingw32/install.sh: line 387: /home/Mike/rust/tmp/dist/rust-0.11-pre-
    i686-pc-mingw32//lib/rustlib/manifest.in: No such file or directory
    install: verifying installed binaries are executable
    tmp/dist/rust-0.11-pre-i686-pc-mingw32/install.sh: line 393: /usr/local/bin/rustc: No such file or d
    irectory
    install: error: can't execute installed rustc binary. installation may be broken. if this is expecte
    d then rerun install.sh with `--disable-verify` or `make install` with `--disable-verify-install`
    /home/Mike/rust/mk/install.mk:18: recipe for target `install' failed
    make: *** [install] Error 1

Possibly relevant:

* the double slash in the `manifest.in` path
* I have a `~/rust/tmp/dist/rust-0.11-pre-i686-pc-mingw32` folder, but no `lib` under it
* I don't have a `/usr` folder at all

**Comment by steveklabnik** [comment]
How relevant is this issue today? I don't have a Windows machine...

**Comment by alexcrichton** [comment]
Our installers have changed quite a bit since this was opened, so I'm going to close this as "probably fixed"
