### ISSUE TITLE
getting Broken pipe on `--enable-debug --disable-optimize` build 

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#13824]
After the following IRC conversation: https://botbot.me/mozilla/rust/msg/13926593/

I made the following test case:

```rust
fn main() {
    let mut inp = std::io::stdin();
    println!("{}", inp.read_line());
    for _ in range(0, 100) {
        std::io::println("b")
    }
}
```

(The blocking read at the beginning was to offer me the opportunity to attach a debugger.)

I have two builds of rustc. One is build with `--enable-debug --enable-optimize`; the other with `--enable-debug --disable-optimize`. The latter build is *nondeterministically* getting a pipe broken error when piping the above program into `head`:

```
% grep CFG_CONFIGURE_ARGS ~/Dev/Mozilla/rust.git/objdir-dbgopt/config.mk 
CFG_CONFIGURE_ARGS   := --enable-debug --enable-optimize --enable-ccache --enable-clang --prefix=~/opt/rust-dbg
% grep CFG_CONFIGURE_ARGS ~/Dev/Mozilla/rust.git/objdir-dbg/config.mk 
CFG_CONFIGURE_ARGS   := --enable-debug --disable-optimize --enable-ccache --enable-clang --prefix=~/opt/rust-dbg-nopt
% ~/Dev/Mozilla/rust.git/objdir-dbgopt/x86_64-apple-darwin/stage2/bin/rustc --version
/Users/fklock/Dev/Mozilla/rust.git/objdir-dbgopt/x86_64-apple-darwin/stage2/bin/rustc 0.11-pre (7a19a82 2014-04-27 23:06:41 -0700)
host: x86_64-apple-darwin
% ~/Dev/Mozilla/rust.git/objdir-dbg/x86_64-apple-darwin/stage2/bin/rustc --version
/Users/fklock/Dev/Mozilla/rust.git/objdir-dbg/x86_64-apple-darwin/stage2/bin/rustc 0.11-pre (7a19a82 2014-04-27 23:06:41 -0700)
host: x86_64-apple-darwin
% ~/Dev/Mozilla/rust.git/objdir-dbgopt/x86_64-apple-darwin/stage2/bin/rustc /tmp/nums.rs 
% echo a | ./nums | head
Ok(a
)
b
b
b
b
b
b
b
b
% ~/Dev/Mozilla/rust.git/objdir-dbg/x86_64-apple-darwin/stage2/bin/rustc /tmp/nums.rs 
% echo a | ./nums | head
Ok(a
)
b
b
b
b
b
b
b
b
% echo a | ./nums | head
Ok(a
)
b
b
b
b
b
b
b
b
task '<main>' failed at 'failed printing to stdout: broken pipe (Broken pipe)', /Users/fklock/Dev/Mozilla/rust.git/src/libstd/io/stdio.rs:245
% 
```

**Comment by steveklabnik** [comment]
So, is this not really a bug, then?

**Comment by pnkfelix** [comment]
@steveklabnik I guess the one thing I'd like to see is what the "closest" port of the C version of this program is (where by "closest", I mean closest in the end observable semantics, excepting that I would like to eschew undefined behavior if possible).

@alexcrichton said above in an answer to one of my questions that he "would expect any user wanting to handle errors printing to stdout to use io::stdout() rather than println!" It might be nice if we actually showed what that looks like.

But having said that, I also am not sure that writing such an example need block this ticket.  So you can feel free to close.  (Or maybe if I am inspired, I'll try to write the aforementioned example.)
