### ISSUE TITLE
-ffunction-sections triggers an LLVM assert on windows

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#13846]
It's the same assert as seen by #13793. I suspect that they are related bugs, and that this is likely an upstream LLVM bug.

This is a tracking issue for this for now. I'm going to turn off -ffunction-sections for windows.

**Comment by frewsxcv** [comment]
@klutzy Are you able to reproduce those 'obscure bugs' with the latest Rust?

**Comment by vadimcn** [comment]
I re-enabled function sections on Windows in the current master branch, and it compiled and passed tests without errors.
However... I am not seeing any reductions in the size of executables.  On the contrary, my hello_world.exe has gotten bigger!   Rust nightly creates a 2.8MB file, whereas this modified version - 3.2MB.

**Comment by alexcrichton** [comment]
It is expected that `-ffunction-sections` does indeed increase the size of the resulting object *if* nothing is eliminated (lots more sections need to be described). That being said I'm pretty surprised that nothing was eliminated. Are we sure that `ld` in mingw-w64 has this implemented and working?

**Comment by vadimcn** [comment]
> It is expected that -ffunction-sections does indeed increase the size of the resulting object if nothing is eliminated (lots more sections need to be described).

I am talking about size of the final executable, not about rlib.  I thought all text/data sections get merged during linking.   Is there some residual per-section overhead?

> Are we sure that ld in mingw-w64 has this implemented and working?

Good question...  There was a [patch](http://comments.gmane.org/gmane.comp.gnu.binutils/58624) enabling `--gc-sections`, however the bug is [still open](https://sourceware.org/bugzilla/show_bug.cgi?id=11539).

**Comment by vadimcn** [comment]
... and the answer is ... [NO](http://comments.gmane.org/gmane.comp.gnu.mingw.w64.general/11101)

**Comment by alexcrichton** [comment]
>  I thought all text/data sections get merged during linking. Is there some residual per-section overhead?

Oh you may be right. I think I'm forgetting the exact specifics but what you're saying sounds right. Maybe there's a mixture of the two happening on windows?

>  ... and the answer is ... NO

:(

**Comment by brson** [comment]
Kind of a wishlist feature, so closing. We just have to remember this problem if somebody ever tries to turn -ffunction-sections on again. Reopen if you disagree.

**Comment by mati865** [comment]
FTR this feature works fine nowadays but it causes LD older than 2.32 to misalign relocations information, LLD is unaffected.
Remains disabled for now.
