### ISSUE TITLE
Trait constraints should allow anonymous lifetimes for references.

### ISSUE THREAD

**Issue by ciphergoth** [rust-lang/rust#13840]
This compiles:

```rust
fn isum<'a, I: Iterator<&'a int>>(mut it: I) -> int { it.fold(0, |a, b| a + *b) }
```
This should be the same, but doesn't compile:
```rust
fn isum<I: Iterator<&int>>(mut it: I) -> int { it.fold(0, |a, b| a + *b)}
```
The compiler complains of a "missing lifetime specifier" at the &int.

**Comment by steveklabnik** [comment]
/cc @rust-lang/lang , is this a bug? I would expect a lifetime specifier to be needed here. Updated code. Works:

```
fn isum<'a, I: Iterator<Item=&'a i32>>(it: I) -> i32 { it.fold(0, |a, b| a + *b)}
```

doesn't

```
fn isum<I: Iterator<Item=&i32>>(it: I) -> i32 { it.fold(0, |a, b| a + *b)}
```

**Comment by ciphergoth** [comment]
I had expected leaving out the lifetime to be the same as supplying an anonymous one, possibly in error.

**Comment by steveklabnik** [comment]
The only time you can leave out lifetimes is following the elision rules: https://doc.rust-lang.org/book/lifetimes.html#lifetime-elision and this signature isn't compatible with any of them.

**Comment by eddyb** [comment]
@steveklabnik In a way, this is a feature request.
Of course it doesn't work right now, this is what the issue is about.
Traits generic over lifetimes didn't work for the longest time, and their ergonomics were not improved once they were fixed to actually work.

**Comment by steveklabnik** [comment]
>  Of course it doesn't work right now, this is what the issue is about.

Well, adding more rules for elision would take an RFC these days. We don't keep feature requests in this repository.  I've moved it over: https://github.com/rust-lang/rfcs/issues/1352

**Comment by ciphergoth** [comment]
Makes sense. Thanks!

**Comment by steveklabnik** [comment]
No problem, thanks for bringing it up! Sorry I was confused about the bug/feature split.

**Comment by ciphergoth** [comment]
I think the confusion was mine, thanks for sorting it out!

**Comment by nikomatsakis** [comment]
(I personally would like this to work eventually, but we currently do not support it, so I think this is "not a bug".)
