### ISSUE TITLE
Put Code of Conduct and related policy in a more prominent location

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#13855]
Right now we have a sort of "master" policy page with a number of things in it https://github.com/mozilla/rust/wiki/Note-development-policy. This is primarily aimed at developers contributing to Rust, but the CoC in particular is an important document to the wider community and deserves to be in a more discoverable location. Not sure where.

**Comment by Stebalien** [comment]
I've forked and updated that document to better fit the proposed task (communication, then conduct, then contributing).
Draft: https://github.com/Stebalien/rust-wiki/blob/master/Note-development-policy.md
