### ISSUE TITLE
"hello world" contains Lovecraft quotes

### ISSUE THREAD

**Issue by pcwalton** [rust-lang/rust#13871]
Yes, really

**Comment by flying-sheep** [comment]
idk if this gets optimized how i imagine, but how about changing the macro so that it branches depending on the presence of a message or not.

and only if someone ever expands the macro without message, the quote-including message is hit.

this way, we can just tell people to use error messages if they want to save those 2k.

**Comment by stuartpb** [comment]
An embedded gag that only comes up when the program is frustrating the user with a catastrophic error? *[What could possibly go wrong?](https://twitter.com/stuartpb/status/508235714287259648)*

**Comment by Rotten194** [comment]
Honestly, as someone outside the Rust community, seeing this puts me off using the language. I'm a Lovecraft fan, and if this was an easter egg in the toolchain I would love it, but embedding this statically into all the binaries I ship to end users is a step too far. There's a lot of negative interpretations a snooping end-user could get from finding these quotes talking about things dying and gods in the binaries (and running `strings` on a binary isn't exactly difficult). That negative interpretation would fall on me, who they see as the developer, not the Rust team, who they probably don't even know exists.

Rust is a tool. If my table saw has a tiny inscription on the underside with the name of the engineer who designed it - that's neat, a fun homage, and overall great. If my table saw contains a tiny router that engraves that engineer's name onto every piece of wood I cut with it - not so great. It degrades the quality of the tool. While I appreciate the entertainment value of the quotes, I think moving them into a developer tool like the Rust compiler would maintain that entertainment while also not degrading the quality of Rust by inserting unwanted data in generated binaries.

**Comment by gabrielecirulli** [comment]
@Rotten194 That's an incredibly fitting analogy.

Here are a complete outsider's 2 cents: why not change `rustc` instead to display a funny (or lighthearted) quote when something goes wrong, to sort of alleviate the pain of having your compilation fail? Of course, it shouldn't get in the way of you solving the issue (or it would be even worse), but if it manages to have some "decorative" value, I think it would be a perfect middle-ground between getting rid of this easter egg entirely or moving it to a more sensible place.

**Comment by jimblandy** [comment]
"Some people have commented that the amount of noise generated by a change is inversely proportional to the complexity of the change."
- http://bikeshed.org/

**Comment by marcoms** [comment]
I am very much in favour of removing the quotes. Put the quotes somewhere where humans will read them, not machines

**Comment by lulcat** [comment]
Go and write some crap in a fork which removes them then. Great job in putting it in.. I am now gonna start using rust from this very moment just to check out these quotes. If I _remain_ in rust , however will have to do with it\s general quality for my intended work. Bloody godd***mn yanks and their Mickey Mouse laws and spaghetti jurisprudencia. So runtime aborts eh??
