### ISSUE TITLE
Consider -fno-asynchronous-unwind-tables

### ISSUE THREAD

**Issue by pcwalton** [rust-lang/rust#13889]
Apparently it helps reduce the amount of exception code generated by quite a bit.

**Comment by frewsxcv** [comment]
Should the be moved to rust-lang/rfcs?

**Comment by alexcrichton** [comment]
In clang this just [translates to `-munwind-tables`](https://github.com/llvm-mirror/clang/blob/51a1634aff2cfcf6f523a2020d34e82db1722058/lib/Driver/Tools.cpp#L3664-L3672) which [translates to `UnwindTables`](https://github.com/llvm-mirror/clang/blob/51a1634aff2cfcf6f523a2020d34e82db1722058/lib/Frontend/CompilerInvocation.cpp#L483) which later [turns into the `UWTable` LLVM attribute](https://github.com/llvm-mirror/clang/blob/51a1634aff2cfcf6f523a2020d34e82db1722058/lib/CodeGen/CodeGenModule.cpp#L783-L784). We don't apply this by default to Rust functions, so I think this is basically done.
