### ISSUE TITLE
Add UnexpectedOutput to IoErrorKind (or something similar)

### ISSUE THREAD

**Issue by carllerche** [rust-lang/rust#13882]
This would help support any higher level IO abstractions, such as parsers, or wrappers around process calls, etc...

For example, an abstraction that shims execing sub processes and handling the result could fail w/ UnexpectedOutput if the subprocess did not provide a valid result.

Another use-case, when wrapping an IO stream w/ an HTTP parser (or any higher level protocol), it would be nice to just return an IO like API, but when failing to parse, there is no good IoErrorKind to describe failing to handle the output in the abstraction.

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by Mark-Simulacrum** [comment]
`io::ErrorKind::InvalidData` has the following description:
> Data not valid for the operation were encountered.

> Unlike InvalidInput, this typically means that the operation parameters were valid, however the error was caused by malformed input data.

> For example, a function that reads a file into a string will error with InvalidData if the file's contents are not valid UTF-8.

I think this fits the described UnexpectedOutput, so can this be closed?
