### ISSUE TITLE
Rename PatUniq to PatBox and extend support to arbitrary smart pointers

### ISSUE THREAD

**Issue by pcwalton** [rust-lang/rust#13910]
Yup.

**Comment by steveklabnik** [comment]
Triage: box patterns are now feature gated.

**Comment by steveklabnik** [comment]
Triage: box patterns are still gated, but doing a `grep` of the source code:

```text
$ git grep "PatUniq"
src/grammar/parser-lalr.y:| BOX pat                                         { $$ = mk_node("PatUniq", 1, $2); }
$
```

I'm guessing this is used somewhere, but maybe under a different name or something?

**Comment by pnkfelix** [comment]
@steveklabnik I think the rename happened,  but not the extension to arbitrary box patterns

**Comment by nikomatsakis** [comment]
I think we can close this. The extension to arbitrary "smart pointers" etc feels like an RFC issue to me.
