### ISSUE TITLE
output more precise range metadata

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#13938]
It currently only has a lower and upper bound, so it loses information about gaps in the range. LLVM supports outputting the full set of information.

**Comment by steveklabnik** [comment]
Traige: unsure if this has changed, but I doubt it.

**Comment by steveklabnik** [comment]
Triage: this ticket is now almost three years old, with no other comments than my last triage. I'm going to give it a close. If anyone wants to fix this today, please feel free.
