### ISSUE TITLE
Remove/justify all `&T` to `&mut T` transmutes

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#13933]
This is undefined behaviour, and so would preferably be avoided by using `Unsafe` etc.

https://github.com/mozilla/rust/pull/13934 removed the `transmute_mut` function, replacing it with (closer to) correct code where possible & `transmute::<&_, &mut` where not possible (that code snippet is the longest sequence that means grep will find all of the calls I inserted). There's fixmes pointing to this issue too.

**Comment by steveklabnik** [comment]
I believe these are all now basically gone:

```
$ git grep "transmute::<&"
src/libstd/sys/unix/process.rs:            mem::transmute::<&ProcessConfig<K,V>,&'static ProcessConfig<K,V>>(cfg)
src/libsyntax/ast.rs:            ::std::mem::transmute::<&str,&str>(&token::get_name(*self))
src/libsyntax/parse/token.rs:            mem::transmute::<&[u8],&[u8]>(this.container_as_bytes())
src/test/run-make/mixing-deps/prog.rs:    assert_eq!(unsafe { mem::transmute::<&int, uint>(&both::foo) },

```
