### ISSUE TITLE
Unbundle all 3rd party libraries.

### ISSUE THREAD

**Issue by cicku** [rust-lang/rust#13945]
Hi,

I don't know if it's *possible* to unbundle all 3rd party libraries. I'm going to package it into Fedora, we disallow bundling in most cases. However before I try to unbundle them, I'd like to see if you are willing to see me doing this since using system libraries may cause problems and I'm not sure if you are willing to fix.

Thanks.

**Comment by alexcrichton** [comment]
The two major native libraries we depend on are LLVM and jemalloc, both of which have options to specify an external build in the configure script, so I'm going to close this.
