### ISSUE TITLE
MemoryMap does not fail the task if `munmap` fails

### ISSUE THREAD

**Issue by Jurily** [rust-lang/rust#13966]
[os.rs](https://github.com/mozilla/rust/blob/master/src/libstd/os.rs#L1135):

```rust
#[cfg(unix)]
impl Drop for MemoryMap {
    /// Unmap the mapping. Fails the task if `munmap` fails.
    fn drop(&mut self) {
        if self.len == 0 { /* workaround for dummy_stack */ return; }

        unsafe {
            // FIXME: what to do if this fails?
            let _ = libc::munmap(self.data as *c_void, self.len as libc::size_t);
        }
    }
}
```

Same for Windows. Crypto needs this guarantee to protect sensitive data.

**Comment by geraldstanje** [comment]
when will std::os::MemoryMap be stable? 

i face the following issue with MemoryMap. How can i make sure that gdb infos are correct? I compiled my app using cargo + debug...
```
let mmap = MemoryMap::new(size, mmap_opts).unwrap();
(gdb) next
42	    let data = mmap.data();
(gdb) print mmap
$1 = {data = 0xb5c00000 <error: Cannot access memory at address 0xb5c00000>, len = 8388608, kind = {{RUST$ENUM$DISR = MapFile, __0 = 0x0}, {
      RUST$ENUM$DISR = MapFile}}}
```

**Comment by alexcrichton** [comment]
As @klutzy pointed out in #25538 this has since been removed, so I'm going to close this, but it's definitely something that needs to be considered if re-adding!

**Comment by alexcrichton** [comment]
@geraldstanje it's likely that this sort of functionality would start out as an external crate on crates.io before migrating into the standard library.
