### ISSUE TITLE
Valgrind errors on regex! macro usage

### ISSUE THREAD

**Issue by KokaKiwi** [rust-lang/rust#13969]
Using `regex!` macro on Rust program cause Valgrind output many errors:

https://gist.github.com/KokaKiwi/11559159 (I don't paste it here because Valgrind output *a lot of* errors)

My `rustc` version:
```
sh-4.3$ rustc --version
rustc 0.11-pre-nightly (abdacec 2014-05-04 23:16:40 -0700)
host: x86_64-unknown-linux-gnu
```

**Comment by steveklabnik** [comment]
Regex has been moved out of tree.
