### ISSUE TITLE
ICE with static function pointer to generic instantiation of enum constructor

### ISSUE THREAD

**Issue by Kimundi** [rust-lang/rust#13972]
Testcase:
```rust
static BLOCK_ENUM_CONSTRUCTOR: fn(uint) -> Option<uint> = Some;

fn main() {}
```

Output:
```
error: internal compiler error: adt::represent_type called on non-ADT type
note: the compiler hit an unexpected failure path. this is a bug.
note: we would appreciate a bug report: http://static.rust-lang.org/doc/master/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
task 'rustc' failed at '~Any', /build/rust-git/src/rust/src/libsyntax/diagnostic.rs:155
```

**Comment by steveklabnik** [comment]
This compiles just fine today.

**Comment by eddyb** [comment]
@steveklabnik Thanks! There's a bunch of globals-related issues that @Twisol cc'd me on because of #20295 which might have fixed them, but I don't know any easy way to find them again.
@jdm There's already a test for all of these in `src/test/run-pass/const-polymorphic-paths.rs`.

**Comment by Eh2406** [comment]
There is a FIXME related to this issue,
https://github.com/rust-lang/rust/blob/master/src/test/run-pass/const-block.rs#L61
Now that the issue is closed can the FIXME be fix, or made more specific?

**Comment by eddyb** [comment]
@Eh2406 The FIXME is wrong, it has nothing to do with this issue.
