### ISSUE TITLE
rustdoc: consider running tests in a fresh temporary directory

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#13977]
Spawned off of Issue #13965.  I had a couple nice illustrative bits of code that spewed output into some files.  I didn't really think about the consequences of doing that with respect to the rustdoc workflow.

( What, doesn't everyone do their builds in an isolated build tree?  No, not everyone?  Wait, is it just me?  :) ... )

Anyway, I guess this is a feature request that either rustdoc itself or our make infrastructure should ensure that the current working directory is set to a separate workspace when rustdoc runs, and the contents of that workspace should be deleted if rustdoc terminates without an error condition.

**Comment by steveklabnik** [comment]
Triage: I am not aware of any change here.

**Comment by Mark-Simulacrum** [comment]
I believe this is fixed today: https://github.com/rust-lang/rust/blob/bc9822af2eb8f59300354fd7c9336aa1f78304a1/src/librustdoc/test.rs#L241.
