### ISSUE TITLE
Add fn skip(n: uint) with a default implementation to Reader

### ISSUE THREAD

**Issue by carllerche** [rust-lang/rust#13989]
Reader should have an extra fn that allows skipping a number of bytes. The default implementation could look something like:

```
fn skip(n: uint) { let _ = self.read(Vec::from_elem(n, 0u8); }
```

However, BufReader could implement the fn by simply updating the internal cursor. This would allow more efficient skipping w/o having to require Seek.

**Comment by steveklabnik** [comment]
@carllerche did this end up getting addressed in io reform?

**Comment by carllerche** [comment]
@steveklabnik Not yet. I think (hope) it is coming pre 1.0 though. cc @aturon

**Comment by aturon** [comment]
Nominating for 1.0-beta P-high. (Should be trivial.)

**Comment by pnkfelix** [comment]
P-high, I-needs-decision

**Comment by alexcrichton** [comment]
In today's day and age this sort of addition (to a core trait like `Read`) will require an RFC, so I'm going to close this in favor of that course of action.

**Comment by youknowone** [comment]
#53294
