### ISSUE TITLE
rustdoc could use some LD_LIBRARY_PATH handling cleanup

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#13983]
Spawned off of #13732.

Much like our `run-make` tests, rustdoc has a problem where it sometimes wants to be using the host's `LD_LIBRARY_PATH` to resolve dynamic library dependencies, and sometimes it wants to be using the target's `LD_LIBRARY_PATH`.  (This largely comes up e.g. when running the testable code blocks embedded within rustdoc documentation blocks.)

This issue is not normally exposed under normal uses of rustdoc because most people run it against a stage2 build or a rust distribution.  The problem really only arises when running the documentation against stage1.

For the `run-make` tests, PR #13753 is taking the approach of feeding in two distinct environment variables (one for the host and one for the target) and relying on tooling within the makefile select the appropriate option.  Presumably some similar approach would work for rustdoc.

(But in the short term @pnkfelix is just going to disable the incompatible uses of rustdoc for stage1 and point them at this ticket.)

**Comment by steveklabnik** [comment]
Triage: @alexcrichton did a bunch of Rustdoc work, but I don't think that it improved this area at all.

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by steveklabnik** [comment]
Triage: not aware of any changes

**Comment by jyn514** [comment]
@pnkfelix it's kind of unclear to me what this issue is about. Is there some example code I could test that depends on LD_LIBRARY_PATH? `rustdoc --test src/main.rs  --target i686-unknown-linux-gnu` works fine for me locally.

**Comment by jyn514** [comment]
I'm going to close this until it causes issues.
