### ISSUE TITLE
Type errors of the form "expected... but found..." should indicate the source of their expectation

### ISSUE THREAD

**Issue by zwarich** [rust-lang/rust#14007]
The program

``` rust
extern crate collections;
use collections::treemap::TreeMap;

fn main() {
    let mut a = TreeMap::new();
    a.insert(0, 1);
    a.insert(0, "foo");
}
```

gives the type error

```
treemap-test.rs:7:17: 7:22 error: mismatched types: expected `<generic integer #1>` but found `&'static str` (expected integral variable but found &-ptr)
treemap-test.rs:7     a.insert(0, "foo");
                                   ^~~~~
```

This error should indicate the source of the expectation that the type parameter is integral.

**Comment by steveklabnik** [comment]
Updated code:

```
use std::collections::BTreeMap;

fn main() {
    let mut a = BTreeMap::new();
    a.insert(0, 1);
    a.insert(0, "foo");
}
```

Error

```
 expected `_`,
    found `&'static str`
(expected integral variable,
    found &-ptr) [E0308]
hello.rs:6     a.insert(0, "foo");
                           ^~~~~
```

It still does not point to `insert(0, 1)`.

**Comment by rylev** [comment]
Triage: the error message has improved but still does not point to the source of the expectation [(playground)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=856bbd8205c502a349bb7b5ccebfc185).

```
error[E0308]: mismatched types
 --> src/main.rs:6:17
  |
6 |     a.insert(0, "foo");
  |                 ^^^^^ expected integer, found `&str`

error: aborting due to previous error
```

**Comment by oli-obk** [comment]
We could probably add a Map<InferTy, Span> to InferCtxt and look at it whenever we encounter an error during inference. Though we may want to look at something that also works for concrete types, showing us where the type came from for all type mismatch errors.

**Comment by eddyb** [comment]
@oli-obk That effectively already exists, and is called the "origin" of the inference variable, and is already used by diagnostics.
What might be missing is more fine-grained/details "origins" and diagnostic logic to use them.

**Comment by eddyb** [comment]
However, what's *really* lacking (and for good reasons - i.e. performance), is a "log" of unifications - you may end up with an inference variable, but have no clue as to what else it got unified with, on your way there.

IMO the way to have our cake and eat it too would be to add a generic parameter to `InferCtxt` and the typeck contexts that use it, that decides whether this is a "fast / inference-only" context, or a "slow / diagnostic-enabled" context - that way, any information used *only* for diagnostics, doesn't even have to be tracked until an error is observed (and the "fast / inference-only" typeck attempt aborted).

**Comment by estebank** [comment]
@eddyb you might be interested in looking at the giant hack in https://github.com/rust-lang/rust/pull/106400, which relies exclusively on the HIR to find the expression where an expected type was inferred.
