### ISSUE TITLE
Unused variable warning shouldn't apply to parameters of default trait implementations

### ISSUE THREAD

**Issue by zwarich** [rust-lang/rust#14027]
Currently, code like

```rust
trait Useless {
    fn foo(&self, descriptive_name: uint) { }
}

struct A;

impl Useless for A {
    fn foo(&self, descriptive_name: uint) { println!("{}", descriptive_name); }
}

fn main() {
    let a = A;
    a.foo(1);
}
```

will trigger an unused variable warning:

```
test.rs:2:19: 2:35 warning: unused variable: `descriptive_name`, #[warn(unused_variable)] on by default
test.rs:2     fn foo(&self, descriptive_name: uint) { }
                            ^~~~~~~~~~~~~~~~
```

It seems like using a descriptive name for a parameter should be allowed, even if the default implementation doesn't use the parameter at all.

**Comment by reem** [comment]
Visiting for triage.

You can always just stick `#[allow(unused_variable)]` on that function, it won't show up in the docs.

Personally, I think this is a special case and shouldn't be exempted, since you can can have exceptions to lints with `#[allow]`.

**Comment by huonw** [comment]
This is a dupe of #26487, which was closed: https://github.com/rust-lang/rust/issues/26487#issuecomment-169828205.
