### ISSUE TITLE
#[deriving(Deref)] for newtype structs

### ISSUE THREAD

**Issue by kballard** [rust-lang/rust#14047]
The deriving machinery should support `#[deriving(Deref)]` on newtype structs. Originally newtype structs could always be deref'd to return the wrapped type, and it's useful to be able to opt back into that behavior on a per-struct basis.

Deriving `Deref` should also derive `DerefMut`.

**Comment by steveklabnik** [comment]
Closing in favor of https://github.com/rust-lang/rfcs/issues/261
