### ISSUE TITLE
Clean up the macros chapter

### ISSUE THREAD

**Issue by sanxiyn** [rust-lang/rust#14058]
It would be nice to use consistent terminology for macros.

For example, in `$a:b`, [Macros Guide](http://doc.rust-lang.org/book/macros.html) calls `b` a "fragment specifier", [Reference Manual](http://doc.rust-lang.org/reference.html) calls it a "designator". Both are inscrutable, and looking at search engine hits "fragment specifier" seems to be a Rust coinage.

Dylan calls it "constraint", which seems reasonable to me. See [a section on Dylan Macro System documentation](http://opendylan.org/articles/macro-system/pattern-variables.html).

**Comment by kmcallister** [comment]
The macros chapter could use a lot of work.  I think we should find more exciting examples for everything before "Hygiene" and then rewrite the explanation around those.  I can take a shot at this before 1.0-final.

**Comment by kmcallister** [comment]
In progress as  #22393.

**Comment by kmcallister** [comment]
Landed! ^_^
