### ISSUE TITLE
json test_read_{list,object}_streaming are flaky on 32-bit

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#14064]
These tests have been seen to be flaky on 32-bit with a very obscure error:

```
---- json::tests::test_read_object_streaming stdout ----
    task 'json::tests::test_read_object_streaming' failed at 'assertion failed: `(left == right) && (right == left)` (left: `BooleanValue(true)`, right: `BooleanValue(true)`)', C:\bot\slave\auto-win-32-opt\build\src\libserialize\json.rs:3062

---- json::tests::test_read_list_streaming stdout ----
    task 'json::tests::test_read_list_streaming' failed at 'assertion failed: `(left == right) && (right == left)` (left: `BooleanValue(true)`, right: `BooleanValue(true)`)', C:\bot\slave\auto-win-32-opt\build\src\libserialize\json.rs:3062 
```

I find these error messages curious. These tests only fail on windows, and they only fail with optimization turned on. I suspect an LLVM bug here, but I haven't confirmed it. For now I'm going to ignore these tests on windows.

**Comment by frewsxcv** [comment]
*visiting for triage*

Can confirm these tests are still ignored:

* https://github.com/rust-lang/rust/blob/eaf4c5c784637f3df8bdebc6ec21dbd4bc69420a/src/libserialize/json.rs#L3602
* https://github.com/rust-lang/rust/blob/eaf4c5c784637f3df8bdebc6ec21dbd4bc69420a/src/libserialize/json.rs#L3641
* https://github.com/rust-lang/rust/blob/eaf4c5c784637f3df8bdebc6ec21dbd4bc69420a/src/libserialize/json.rs#L3725

I unfortunately don't have a 32 bit window machine to test them on though :(

**Comment by steveklabnik** [comment]
Triage: same as @frewsxcv , These are still presently ignored, but I don't have the proper machinery.

@alexcrichton , should we maybe try removing the ignore, and letting bors take a look? If it was a bug in LLVM, well, a lot has changed since 2014....

**Comment by alexcrichton** [comment]
Sure, I'd be game for unignoring them

**Comment by Mark-Simulacrum** [comment]
#36123 unignored these, so this can [probably] be closed.
