### ISSUE TITLE
rustdoc search doesn't find crate names

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#14077]
E.g. [searching for `libc`](http://static.rust-lang.org/doc/master/std/index.html?search=libc) doesn't show the `libc` crate.

**Comment by steveklabnik** [comment]
Triage: searching for libc doesn't show libc.

**Comment by mitaa** [comment]
Hmm, I deliberately removed the search-index entry in #30504 because it was [broken](https://github.com/rust-lang/rust/issues/30327).
