### ISSUE TITLE
Link to "getting started" docs from rust-lang.org

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#14146]
The windows installed from rust-lang.org installs fine, but the installed rustc doesn’t actually work unless the user installs some other stuff. It’s all explained in the wiki:
https://github.com/mozilla/rust/wiki/Using-Rust-on-Windows

… but I had to hunt for it on the wiki in order to find it. It (or the [getting started](https://github.com/mozilla/rust/wiki/Note-getting-started-developing-Rust) page that links to it) should be linked more prominently when downloading from rust-lang.org.

**Comment by steveklabnik** [comment]
Moving to the rust-lang.org repo
