### ISSUE TITLE
The basic C types should be in `libcore`

### ISSUE THREAD

**Issue by Jurily** [rust-lang/rust#14153]
`c_int` and friends are not defined by `libc`, but the [data model](http://en.wikipedia.org/wiki/LP64#64-bit_data_models) of the operating system. C compilers provide them with [macros](http://gcc.gnu.org/onlinedocs/gcc-4.9.0/cpp/Common-Predefined-Macros.html) like `__LP64__`, `__SIZEOF_INT__`.

They're needed for [syscalls](http://docs.cs.up.ac.za/programming/asm/derick_tut/syscalls.html) (i.e. writing `libc` itself) and kernel modules.

**Comment by huonw** [comment]
Core is designed for (among other things) writing OSes/freestanding code, which would make defining these in that case somewhat strange.

This change was actually proposed (and rejected) in https://github.com/rust-lang/rust/pull/29985 (see there for more discussion), so I'm closing this to match.
