### ISSUE TITLE
std::io::net::unix::UnixStream does not support abstract sockets on Linux.

### ISSUE THREAD

**Issue by canndrew** [rust-lang/rust#14194]
Currently, as far as I can tell, there is no way to connect to or listen on unix domain sockets in Linux's abstract socket namespace. I see two ways to add this support:

0:  Add functions connect_abstract and connect_abstract_timeout to UnixStream and bind_abstract to UnixListener.
1:  Create new traits AbstractStream, AbstractListener and AbstractAcceptor that mimic their Unix* counterparts and put them in either std::io::net::unix or a new module std::io::net::abstract.

I'd be happy to write a patch for this if anyone can suggest which would be the best course of action or suggest a better way to implement this.

**Comment by alexcrichton** [comment]
This will be addressed by https://github.com/rust-lang/rfcs/pull/807 by removing the `Unix*` types. If and when we add them at a future date we should be sure to allocate space in the API to support abstract sockets.

**Comment by haraldh** [comment]
Still not possible :disappointed:

**Comment by canndrew** [comment]
I guess there hasn't been enough demand for it. We could add `std::os::linux::net::{UnixListenerExt, UnixStreamExt}` traits which add `{bind_abstract, connect_abstract}` methods. Something like probably stands a good chance of getting merged into `std`.

**Comment by haraldh** [comment]
Why not remove the zero byte check for the first byte and let the OS fail?
MacOS e.g. fails with "error: No such file or directory (os error 2)" if the path starts with a zero byte.
