### ISSUE TITLE
Allow by-move binding for patterns with guards that don't reference the bindings

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#14252]
I have

~~~ .rs
match token {
    DoctypeToken(dt) if mode == Initial => ...,
    DoctypeToken(dt) => ...,

    TagToken(x) => ...,
    CommentToken(x) => ...,
    // other cases
~~~

This gives

~~~
error: cannot bind by-move into a pattern guard
~~~

In this situation it should be fine to defer the move until the guard has succeeded.

It's a bit frivolous because I could instead do

~~~ .rs
match token {
    DoctypeToken(dt) => if mode == Initial {
        ...
    } else {
        ...
    },

    TagToken(x) => ...,
    CommentToken(x) => ...,
    // other cases
~~~

But I like having all the branching in one construct, especially when I'm implementing a spec which is written that way.  And I don't want to add `mode` to the match scrutinee because none of the other cases care about it.

See also #4649.

**Comment by durka** [comment]
Triage: still annoying.

**Comment by huonw** [comment]
(Foward-)dupe of https://github.com/rust-lang/rust/issues/15287, closing.
