### ISSUE TITLE
Deriving may want to ignore marker fields

### ISSUE THREAD

**Issue by kballard** [rust-lang/rust#14268]
Marker fields are used to provide extra information about types, including opting out of `Copy`, `Send`, and `Share` bounds. However, the presence of a marker field can prevent the ability to `#[derive]` traits for that type. For example, `core::kinds::marker::NoCopy` only implements `Clone` and `Eq` (according to rustdoc; I am unsure if there are any libstd traits it implements because rustdoc doesn't show cross-crate traits). This means that any struct with a `NoCopy` field cannot e.g. derive `Show`, or `Ord`, or other useful traits.

I think the right solution here is to simply not consider the marker fields when deriving traits, with the only exception being `Clone`. Every other trait should just pretend that field doesn't exist.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#726
