### ISSUE TITLE
quote_expr!() can cause early abort

### ISSUE THREAD

**Issue by kballard** [rust-lang/rust#14282]
It seems as though using `quote_expr!()` in a syntax extension after a `span_err()` will cause rustc to abort early instead of finishing the macro expansion phase.

I hit this in my [`bytes!()` PR](https://github.com/mozilla/rust/pull/14275), where I ended up having to track whether I had an error and use `DummyResult` instead of `quote_expr!()`.

**Comment by tamird** [comment]
@kballard could you include a small reproduction snippet to help make this issue more concrete?

**Comment by kballard** [comment]
@tamird I filed this issue almost a year ago. I don't recall the circumstances surrounding it, beyond what I put in the ticket. From re-reading this, I'm pretty sure that what I was saying is that if a syntax extension uses `quote_expr!()` after having previously invoked `cx.span_err()` it aborts immediately, instead of continuing the macro expansion phase (`span_err()` usually doesn't abort the compilation until the end of the macro expansion phase; I think `quote_expr!()` is basically recursively invoking the macro expansion phase and therefore aborting after the recursive invocation ends).

**Comment by steveklabnik** [comment]
Triage: this ticket hasn't had an update in almost two years, and there's no reproduction. As such, I'm going to give it a close. If someone runs into this today and can reproduce, please let me know!
