### ISSUE TITLE
print floating point values at full precision by default

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#14339]
By rounding to a specific number of digits by default, the standard library is causing confusion. Printing to a specified precision is very useful, but it should only happen via `{:.2}` rather than by default.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#796
