### ISSUE TITLE
Inline Assembly cause segmentation fault when define label.

### ISSUE THREAD

**Issue by iseki-masaya** [rust-lang/rust#14375]
OS: OS X 10.8.5
Architecture: x86_64

```
$ rustc -v
rustc 0.11.0-pre-nightly (6291955 2014-05-19 23:41:20 -0700)
host: x86_64-apple-darwin
```

```
fn main() {
    unsafe {
        asm!("label:");
    }
}
```

This code pass the compiler but cause segmentation fault.
Inline Assembly in LLVM is called at https://github.com/mozilla/rust/blob/master/src/rustllvm/RustWrapper.cpp#l173
The description of module level inline assembly about LLVM is here(http://llvm.org/docs/LangRef.html#module-level-inline-assembly)

**Comment by alexcrichton** [comment]
This appears to have been fixed in more recent versions of LLVM (and the currently bundled one)

**Comment by freebroccolo** [comment]
@alexcrichton This doesn't seem to be fixed on OS X, or at least it's happening again. Using labels seems to cause `SIGILL` or `SIGSEGV`. Seems to be the same thing noted [here](https://github.com/rust-lang/rust/issues/16378).

**Comment by alexcrichton** [comment]
Aha I missed the OSX part of this!

**Comment by steveklabnik** [comment]
Triage: a year and a half later, I'm not sure if this is fixed, as I don't have a mac. We've upgraded LLVM a number of times....

**Comment by Mark-Simulacrum** [comment]
Verified as still broken today.

**Comment by Mark-Simulacrum** [comment]
Appears to be fixed today... E-needstest.

**Comment by Mark-Simulacrum** [comment]
This isn't actually fixed.

**Comment by Dylan-DPC** [comment]
I can reproduce this bug. Still exists

**Comment by stevecheckoway** [comment]
See https://github.com/rust-lang/rust/issues/63977#issuecomment-573353150

**Comment by Amanieu** [comment]
You should only use [local labels](https://sourceware.org/binutils/docs/as/Symbol-Names.html#Local-Labels) in inline assembly. This is stated in the documentation for the new `asm!` macro.
