### ISSUE TITLE
rustc should suggest using .to_owned() for ~str

### ISSUE THREAD

**Issue by limeburst** [rust-lang/rust#14383]
`rustc` gives

    error: mismatched types: expected `core::result::Result<int,~str>` but found `core::result::Result<<generic integer #0>,&'static str>` (expected box but found &-ptr)

for

~~~
fn example() -> Result<int, ~str> {
    match Some("") {
        Some("") => Ok(0),
        _ => Err("")
    }
}
~~~

`rustc` could suggest using `to_owned()`.

**Comment by alexcrichton** [comment]
`~str` is no longer a type and I think our bases are pretty well covered here today, so closing
