### ISSUE TITLE
Add a pass to mark doc attributes as used

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#14408]
The unused-attribute lint currently globally whitelists all doc attributes as used, even if they're placed in contexts that rustdoc would never look at (e.g. match arms). There should be a separate pass over the AST that marks the attributes in the correct contexts.

```rust
#![warn(unused_attributes)]

fn f() {
    match 10 {
        /// test
        _ => {}
    }
}
```

**Comment by steveklabnik** [comment]
Triage: no change that I'm aware of.

**Comment by steveklabnik** [comment]
Triage: same as last year

**Comment by Havvy** [comment]
Triage: There's a new lint `unused_doc_comments` that triggers in these cases. IMO, this is good enough to close the issue as fixed. cc @QuietMisdreavus for confirmation.

**Comment by QuietMisdreavus** [comment]
@Havvy When/where was this lint added? I'm not familiar with it.

**Comment by euclio** [comment]
Added in https://github.com/rust-lang/rust/pull/43009, where this case is specifically tested.

**Comment by Mark-Simulacrum** [comment]
Closing as per the above, looks like this was implemented in the unused_doc_comments lint.
