### ISSUE TITLE
Add passes to mark stability and must-use attributes as used

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#14407]
The unused-attribute lint globally whitelists stability and must-use attributes as they're only looked for on-demand. There should be another pass added to mark them used only in the correct contexts.

**Comment by steveklabnik** [comment]
Triage: no change that I'm aware of.

**Comment by steveklabnik** [comment]
Triage: still no change that I'm aware of.

**Comment by ehuss** [comment]
Closing as the unused attribute handling has been rewritten in #87739 and should now handle stability and must_use attributes.
