### ISSUE TITLE
Move unused-attribute pass after trans

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#14406]
Many attributes are not used until after trans, but the current lint pass runs before it. Those attributes are currently globally whitelisted, but this isn't a great long term solution.

**Comment by cmr** [comment]
@sfackler this would require keeping the AST and all analysis data through trans, right?

**Comment by sfackler** [comment]
That or performing the check as trans consumes the AST.

**Comment by jonas-schievink** [comment]
Looks like this could cause issues with `-Zno-trans`

**Comment by Mark-Simulacrum** [comment]
I suspect that this is superseded by https://github.com/rust-lang/rust/issues/17642. If you'd like to reopen with a specific set of attributes that should be handled, then we can do so (for example, `#[used]` is now special-cased: https://github.com/rust-lang/rust/pull/41637).
