### ISSUE TITLE
Recommend recompiling dependencies with the "incorrect triple" error

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#14412]
Sometimes when compiling something with a newer rustc, one gets the ["incorrect triple for crate"](https://github.com/mozilla/rust/blob/87ad19eb78239707f1ceed43e475c6aa052efdbc/src/librustc/metadata/loader.rs#L131) error.

This is usually fixed by recompiling its dependencies (if they were compiled on an older rustc).

We probably should add a note to this error suggesting the same. The current error isn't helpful unless one understands Rust internals.

**Comment by steveklabnik** [comment]
This error message doesn't exist anymore, but I'm not familiar enough with the compiler today to know what the updated message should be. I think that this is 

> Perhaps two different versions of crate `{}` are being used?"

but that doesn't seem exactly right...

**Comment by Mark-Simulacrum** [comment]
I believe that this is no longer strictly speaking an issue, when switching compiler versions we do a fairly good job of recompiling crates without giving errors; I'm going to close, especially as the incorrect triple error seems to no longer exist per the previous comment.
