### ISSUE TITLE
core::str::Str.as_slice() should be renamed as_str()

### ISSUE THREAD

**Issue by kballard** [rust-lang/rust#14433]
The method `as_slice()` in the `core::str::Str` trait should be renamed to `as_str()`. This avoids the name collision with `core::slice::Vector.as_slice()` for types that need to implement both `Vector` and `Str` (as I believe `Vec<Ascii>` should).

I'm filing this issue now to give a chance for anyone to suggest any reasons why this is a bad idea. Otherwise I will go ahead and make the change myself.

**Comment by steveklabnik** [comment]
Traige: this is still true today

**Comment by richo** [comment]
Offer to do it stands

**Comment by aturon** [comment]
Nominating for 1.0-beta P-backcompat-libs.

**Comment by pnkfelix** [comment]
1.0 beta, P-backcompat-libs, I-needs-decision.

**Comment by nikomatsakis** [comment]
Annoyingly, I can't assign this to @richo, but it seems he's got it under control (thanks!). So let this serve as an "assignment" :)

**Comment by richo** [comment]
\o/
