### ISSUE TITLE
Short doc url don't mention Rust version at all

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#14466]
E.g. http://doc.rust-lang.org/std/index.html

Possible solutions:
- not have the short forms
- have the version on each page
- redirect to the .../master/... or .../1.0/... (or whatever) version as appropriate

**Comment by mdinger** [comment]
I like how python labels versions at the top left and allows you to switch between them:

![python_docs](https://cloud.githubusercontent.com/assets/4156987/6099157/5d49359c-afbf-11e4-802b-9b662a103146.png)

---

Ruby also makes it prominent modifying their image:

![ruby_docs](https://cloud.githubusercontent.com/assets/4156987/6099159/628992d6-afbf-11e4-8b57-78f483cb808b.png)

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/issues/22168 is another problem that comes out of this thing.

I'm wondering if we shouldn't just axe the short URLs alltogether, or always re-write them to nightly.

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by QuietMisdreavus** [comment]
Discussion related to this happened in and around [RFC 1826](https://github.com/rust-lang/rfcs/pull/1826), so something to alleviate this is probably going to happen eventually.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this as what we should do here is not for this issue -- and I believe the tracking issue for the 1826 RFC lays this out in better detail: https://github.com/rust-lang/rust/issues/44687
