### ISSUE TITLE
Inlined documentation loses lifetime parameters on functions

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#14462]
# Updated description

Lifetime parameters on functions [are missing](http://doc.rust-lang.org/std/str/trait.Str.html#tymethod.as_slice)
# Original description

**Rustdoc inlining papercuts**

There's still some papercuts with inlined documentation:
- [ ] Lifetime parameters on functions [are missing](http://doc.rust-lang.org/std/str/trait.Str.html#tymethod.as_slice)
- [x] Implementations for traits on primitives [are missing](http://doc.rust-lang.org/std/str/trait.CharEq.html)

**Comment by tomjakubowski** [comment]
This can be closed (although we should probably add a test).

**Comment by steveklabnik** [comment]
Currently:

```
steve@warmachine:~/tmp/foo$ cat src/lib.rs 
pub fn elided(r: &i32) -> &i32 { r }
pub fn not<'a>(r: &'a i32) -> &'a i32 { r }
```

shows

![2016-03-04-125625_327x119_scrot](https://cloud.githubusercontent.com/assets/27786/13535481/79798b28-e208-11e5-908c-9fdfde2224e2.png)
![2016-03-04-125630_396x128_scrot](https://cloud.githubusercontent.com/assets/27786/13535480/7979af40-e208-11e5-91ca-7c7bb0e0d644.png)

And the original method in the example doesn't exist anymore. I think I'm treating this one as "innocent until proven guilty"

**Comment by tomjakubowski** [comment]
This issue was about inlined documentation, i.e. documentation for functions which are re-exported from another crate.  A single-crate test case doesn't suffice to close this issue.

**Comment by tomjakubowski** [comment]
Here's an example showing why this issue should still be open:

collections docs for String::from_utf8_lossy, includes the `<'a>` to declare the named lifetime:

http://doc.rust-lang.org/collections/string/struct.String.html#method.from_utf8_lossy

std docs for String::from_utf_8_lossy, doesn't include the`<'a>` to declare the named lifetime:

http://doc.rust-lang.org/std/string/struct.String.html#method.from_utf8_lossy

**Comment by steveklabnik** [comment]
Understood! Thanks for elaborating.

**Comment by Mark-Simulacrum** [comment]
Looking at collections on nightly, this appears to have regressed since beta -- even collections doesn't show the `'a` lifetime now.

**Comment by kzys** [comment]
We are fine now?

https://doc.rust-lang.org/nightly/std/string/struct.String.html#method.from_utf8_lossy

**Comment by Dylan-DPC** [comment]
This looks to be resolved. Thanks :)

**Comment by Dylan-DPC** [comment]
This one looks resolved. Thanks
