### ISSUE TITLE
No Mutable Slice type exists.

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#14484]
Currently, Rust has a core::raw::Slice type but no core::raw::MutSlice type - and the slice type has a data: *T. This forces people who want to get a *mut T into adding an additional (*T -> *mut T) cast - which may be undefined behaviour.

**Comment by steveklabnik** [comment]
Adding types to Rust requires an RFC at this point, feel free to make one if you want to see this added to Rust!
