### ISSUE TITLE
Investigate implementing an ECMA 402-based internationalization library

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#14494]
We have been told that internationalization is pretty standardized at this point on the web and many languages are starting to follow along. The authoritative spec for this is located [here](http://www.ecma-international.org/ecma-402/1.0/), and it sounds like we shouldn't deviate from that spec much (as it's what everyone is expecting).

Nominating, but I do not believe this is a 1.0 issue.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#858
