### ISSUE TITLE
Investigate implementing an l20n-based localization library

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#14495]
Part of this issue is only actionable depending on the outcome of https://github.com/rust-lang/rfcs/pull/93.

Localization is a very important feature for a language and is often a very difficult system to get right. Previous attempts with `format!` do not look like they're going to pan out, and it looks like it's possible to implement a high quality localization system purely in a library implementation.

The most likely candidate for being implemented is the [l20n](http://l20n.org/) spec. This is a new standard coming out of Mozilla for the web which is still in some development, but it has seen deployment on Firefox OS and is planned to be deployed in Firefox. Other projects such as django are also looking into implementing this spec, so there's certainly precedent.

A rust implementation of the l20n spec would be a good solution for our localization efforts, but some finesse would be required to ensure that the library is as easily usable as the JS api itself.

Nominating, but I believe that this is not necessary for 1.0

cc @zbraniecki

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#822
