### ISSUE TITLE
rustdoc should mark #[deprecated] things as such

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#14493]
For example, as of this writing, the `StrAllocating::to_owned` method is annotated with ``#[deprecated = "obsolete, use `to_string`"]``, but http://doc.rust-lang.org/std/str/trait.StrAllocating.html#method.to_owned gives no indication of that.

**Comment by steveklabnik** [comment]
while https://github.com/rust-lang/rust/issues/15468 is newer, it's already added to milestones and such, so I'm closing this as a duplicate of that.
