### ISSUE TITLE
sync confusingly defines 3 types called `Mutex`

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#14530]
There's [`sync::Mutex<T>`](http://doc.rust-lang.org/master/sync/struct.Mutex.html), [`sync::raw::Mutex`](http://doc.rust-lang.org/master/sync/raw/struct.Mutex.html) and [`sync::mutex::Mutex`](http://doc.rust-lang.org/master/sync/mutex/struct.Mutex.html). The latter two have similar signatures (no contained data) and similar but slightly different APIs. The docs don't describe the difference in detail.

This is pretty confusing (renaming and/or documenting better would be a good fix).

cc @alexcrichton

**Comment by aturon** [comment]
Addressed with `sync` overhaul.
