### ISSUE TITLE
Enforcing static linkage is impossible (and diagnosing why dynamic linking occurs is hard)

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#14543]
There are many instances where one concretely needs a statically linked executable (e.g. to avoid having to distribute a pile of Rust dynamic libraries, making deployment much simpler).

The compiler currently offers no way to request that a compiled artefact is always statically linked against Rust crates (the only option is `-C prefer-dynamic` which isn't really a guarantee either). Since there's no way to force these things, working out why the static linking defaulting failed is very hard, especially with a non-trivial number of dependencies (since the error is almost certainly one of those dependencies coming only in `.so` format).

If the compiler provided say, `-C statically-linked`, then a user can request that something is only statically linked and receive errors about exactly what is stopping this from happening, e.g. `crate syntax can only be found as a dynamic library`. Without this, the user has to search through all dependencies to find out what is breaking things.

(Case study: I was working through a problem like this with @emk on IRC. After much discussion and `ldd` wrangling, we eventually tracked it down to a library which defines a procedural macro internally along with the rest of the functionality, i.e. introducing a dependency on libsyntax. It would be much easier if we can get the compiler to tell us this straight away.)

**Comment by jamm** [comment]
After reading comments to recent topics on HN, both are about new tools, written in Rust https://news.ycombinator.com/item?id=9087108, https://news.ycombinator.com/item?id=9088805 , I got answer from @steveklabnik that it's impossible currently to create standalone binary from Rust programm.
It's pretty important for tools distribution, so please consider to spend some time on this issue.

**Comment by huonw** [comment]
It depends what you mean by standalone. Rust statically links against other Rust libraries by default, but not against the system libc (it's... not best practice to statically link against glibc, for example).

(NB. this issue is about trying to improve the ability to diagnose when a Rust library can only be found in dynamic form, causing an application to be statically linked. It's just an improvement to an existing feature, not adding a new one.)

**Comment by jamm** [comment]
ok, I'll open new one. Sorry, it was try to not create duplicate :)

**Comment by ghmlee** [comment]
@jamm which issue is the working on? I hope there will be standalone distrubtion in rust. (statically linking).

**Comment by steveklabnik** [comment]
Triage: we still don't offer this today.

**Comment by steveklabnik** [comment]
Triage: there hasn't been substantial comments here for years; we don't have any immediate plans of implementing something like this, and while it may be useful, apparently it's not super needed. Closing.
