### ISSUE TITLE
rustdoc search points to definition crate of inlined items

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#14552]
E.g. [a search for `unwrap`](http://doc.rust-lang.org/master/std/?search=unwrap) starts with

> - core::cell::RefCell::unwrap
> - core::option::Option::unwrap
> - core::result::Result::unwrap

even when the search is done in `std`.

Even weirder: the `RefCell` and `Result` unwrap from `std` are listed in the results, but `Option` is not.

**Comment by frewsxcv** [comment]
> crate of inlined items

What do you mean by this?

**Comment by alexcrichton** [comment]
I believe since this was opened [crate names are now factored into search rankings](https://github.com/rust-lang/rust/blob/aab8669ddad0432ef7279cc7f7b0b20d32785314/src/librustdoc/html/static/main.js#L295-L298), so I'm going to close this as fixed!
