### ISSUE TITLE
Please document the JSON streaming parser

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#14550]
I heard from @nical about how awesome is the streaming JSON parser. Sadly, http://doc.rust-lang.org/serialize/json/index.html does not talk about it, and even reading the source it’s not obvious how to use it.

Ideally (for me), someone magically will step up and write awesome documentation to go with this awesome parser. But if someone gives me a "brain dump" I might be willing to format it into docs.

**Comment by steveklabnik** [comment]
Serialize is now out of crate.

**Comment by tmcw** [comment]
@steveklabnik does out of tree mean that it's outside of rust core & therefore in some crate?

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rustc-serialize

**Comment by RandomInsano** [comment]
Man, I wish this'd been documented...
