### ISSUE TITLE
use gold instead of bfd on Linux if it's available

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#14560]
This is what `clang` does on Linux, by detecting the existence of `/usr/bin/ld.gold` and then using it. This can be done with `gcc` by passing `-fuse-ld=gold`. It's a much faster linker and doesn't consume as much memory, so it will reduce the compiler's peak memory consumption.

**Comment by smaudet** [comment]
Mind if I take a look at this one?

**Comment by brson** [comment]
FWIW I did an experiment today and servo in debug mode builds in 54 seconds with ld and 14 seconds with gold. I'm going to see if I can get a patch together for this.

**Comment by bstrie** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/30783
