### ISSUE TITLE
Doc landing page and the 404 page could have the library search box

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#14572]
http://doc.rust-lang.org/master/ and http://doc.rust-lang.org/master/doesntexist could hook into the javascript that runs the search on http://doc.rust-lang.org/master/std/ to all show a search box themselves.

(The 404 page could even be intelligently auto-filled based on the URL, as an additional enhancement.)

**Comment by frewsxcv** [comment]
Triage: Just checked and the "Doc landing page and the 404 page" still don't utilize the library search box

**Comment by steveklabnik** [comment]
triage: re-tagging as 'rustdoc', since we'd need it to be able to do this before adding to the docs

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by kzys** [comment]
It is possible to have a small form on https://doc.rust-lang.org/ which goes to https://doc.rust-lang.org/std/?search=vec. However the landing page is not generated by rustdoc afaik.
