### ISSUE TITLE
Inlined documentation reveals private implementors

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#14586]
For example, `NaiveSearcher` on the clone page: http://doc.rust-lang.org/std/clone/trait.Clone.html

**Comment by steveklabnik** [comment]
Triage: still a problem

**Comment by nagisa** [comment]
http://doc.rust-lang.org/stable/std/str/pattern/trait.Pattern.html links to http://doc.rust-lang.org/stable/core/str/pattern/struct.CharEqPattern.html

**Comment by fhartwig** [comment]
I'm having a go at fixing this, but I have trouble reproducing it. Does anyone have an example of this problem outside of the standard library?
