### ISSUE TITLE
rustc.exe-nightly and binaries compiled rustc.exe 0.10+MinGW-w64 4.8.1 crash on exit on 64bit Windows 7 with ConEmu

### ISSUE THREAD

**Issue by volth** [rust-lang/rust#14600]
@klutzy Yes, I used mingw-w64  downloaded from that page.
I run rustc.exe from batch file which set PATH only to MinGW-w64 and rust directories
```
PATH=C:\mingw-builds\x32-4.8.1-win32-dwarf-rev5\mingw32\bin;C:\Rust\bin
rustc.exe
```
Thr crash is reproducible even with
```
PATH=C:\Rust\bin
rustc.exe
```
because MinGW is not needed to simple run rustc.exe. 
So it does not depend on my MinGW-w64 installation.

with gdb (it looks like crash happens in post-main code):
```
......
Additional help:
    -C help             Print codegen options
    -W help             Print 'lint' options and default settings
    -Z help             Print internal options for debugging rustc


Program received signal SIGSEGV, Segmentation fault.
0x7734fc62 in ntdll!ZwMapViewOfSection () from C:\Windows\system32\ntdll.dll
(gdb)
```
It was rustc.exe from nightly build.
I have a similar crash with rust-0.10+MinGW-w64-4.8.1-compiled binaries, even with "hello world". 
rustc.exe 0.10 does not crash:
```
PATH=C:\mingw-builds\x32-4.8.1-win32-dwarf-rev5\mingw32\bin;C:\Rust-0.10\bin
rem compiles ok
rustc.exe hello.rs
rem hello.exe crashes with the same Segmentation fault.
hello.exe
```

Binaries compiled with rust-0.10+MinGW-w64-4.7.3 works ok
```
PATH=C:\mingw-builds\x32-4.7.3-win32-dwarf-rev1\mingw32\bin;C:\Rust-0.10\bin
rem ok
rustc.exe hello.rs
rem ok
hello.exe
```

**Comment by darsain** [comment]
I'm using Cmder which is a wrapper around ConEmu, and am also experiencing random crashes. Built binaries sometimes crash, sometimes run. `rustc` command works, but I remember it crashing a few times at the beginning. `cargo` command always crashes.

Rust version: rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14)

Don't have any logs to post as I've just installed rust, have no idea what I'm doing, and crashes don't produce any output but pop out the *{command}.exe has stopped working* window :)

**Comment by retep998** [comment]
Through reports from Dtgr it seems that conemu causes jemalloc to crash during `jemalloc_constructor`. Specifically this line of code: https://github.com/rust-lang/jemalloc/blob/e24a1a025a1f214e40eedafe3b9c7b1d69937922/src/jemalloc.c#L692

It appears it is trying to lock a broken critical section. As to why the critical section is broken, I don't know, but I suspect conemu is breaking something. Also, the crash was only affecting cargo and programs built by rustc, but not rustc itself.

Possibly related to #22710

**Comment by tkelman** [comment]
May want to try disabling the ConEmu injection hooks - https://code.google.com/p/conemu-maximus5/wiki/ConEmuHk

**Comment by alexcrichton** [comment]
https://github.com/rust-lang/rust/issues/29839 was recently opened which I believe is the same bug as this one, and that one's a little more specific, so I'm gonna close this in favor of that.
