### ISSUE TITLE
Is bool FFI compatible, and if so, what is it defined to be?

### ISSUE THREAD

**Issue by carllerche** [rust-lang/rust#14608]
I am unsure how bool is represented in memory and how it works with fns that have that are C ABI compatible.

Perhaps it would be worth matching what stdbool does?

**Comment by mahkoh** [comment]
This is still an issue. At the very least, there has to be a c_bool in libc.

**Comment by tomjakubowski** [comment]
Any update on this?

**Comment by eefriedman** [comment]
It should be easy to file a PR to add the line `pub type c_bool = bool;` at https://github.com/rust-lang/rust/blob/0f1e5144007b255c87c15badefc0a8b7612137b6/src/liblibc/lib.rs#L209 .  (Rust's builtin bool should behave like a C99 bool as far as I know, and I can't see any reason why that would change.)

**Comment by steveklabnik** [comment]
Closing in favor of https://github.com/rust-lang/rfcs/issues/992
