### ISSUE TITLE
Declaring extern symbols twice results in wrong undefined symbols

### ISSUE THREAD

**Issue by thchittenden** [rust-lang/rust#14617]
``` rust
#![crate_type="rlib"]

fn func1() {
    extern {
        static sym: (); 
    }

    let x = &sym;
    println!("{}", x);
}

fn func2() {
    extern {
        static sym: (); // tries to resolve as sym1
    }
    let x = &sym;
    println!("{}", x);
}

pub fn test() {
    func1();
    func2();
}   
```

If a symbol, sym, is declared in two extern blocks, the code will expect two symbols sym and sym1. Compiling the above example results in two undefined symbols: 
   45: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND sym
   46: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND sym1

**Comment by steveklabnik** [comment]
Compiling this today, I don't see either of those symbols in `nm -a`. So I suspect I'm missing something.

**Comment by thchittenden** [comment]
I just tested this against the nightly and it seems to be fixed. `sym` was the only undefined symbol in the rlib. Compiling and linking the above program against a library with `sym` defined worked as expected.

**Comment by steveklabnik** [comment]
>  I just tested this against the nightly and it seems to be fixed

Closing!
