### ISSUE TITLE
Figure out in-tree crypto story

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#14655]
We've previously made the decision not to distribute any crypto with Rust at all, but this is probably not tenable since crypto is used everywhere. My current opinion is that we should not distribute any crypto *written in Rust*, but that distributing bindings to well-regarded crypto is fine.

Figure out a strategy here, build consensus, then start implementing a robust crypto library out of tree, with the goal of merging into the main distribution someday. There are some existing efforts along these lines that should be evaluated for this purpose.

**Comment by frewsxcv** [comment]
Most people here probably already know, but for the record a Rust crypto meeting happened at Mozilla SF in December 2014. [Here's a link to the recording](https://air.mozilla.org/bay-area-rust-meetup-december-2014/)

**Comment by tarcieri** [comment]
I made a remark about this issue in my talk at Mozilla SF in December 2014 and I just wanted to clarify.

My remark was specifically that Rust should not have an in-tree crypto story, and it highlighted this issue.

This comes with some caveats. My intended point was about implementing *ciphers* in-tree, and saying I thought that was a bad idea. My analogy was to Ruby's OpenSSL extension, which is a binding to OpenSSL that is an intractable part of the standard library. There is an effort underway to rip OpenSSL out of the Ruby standard library and move it into an out-of-tree external package.

Rust has various in-tree APIs for *hash functions* (e.g. `std::hash`) and I think these are non-controversial and totally fine. In fact I think `std::hash::Hasher` is great and one of the other remarks I made in my talk is I totally want to see more traits like this.

tl;dr: hash functions are fine, but please leave encryption ciphers and public-key digital signature algorithms to out-of-tree libraries developed by crypto experts.

**Comment by ciphergoth** [comment]
Say a little more about why hash functions are an exception? Thanks!

**Comment by tarcieri** [comment]
First, there is one hash function you absolutely do want in the standard library: something like [SipHash](https://131002.net/siphash/) to use as the basis of a (hashDoS-resistant) hashing function:

http://doc.rust-lang.org/0.11.0/collections/hash/sip/fn.hash.html

Without a cryptographically secure hash function like SipHash, any time an attacker provides the data to be put into e.g. a `HashMap`, they can potentially collide the buckets the data is placed into, intentionally causing poor algorithmic performance, DoSing the application. This is hashDoS.

Having hash functions in the standard library also gets you around the bootstrapping problem of how to verify artifacts in the package manager for the language itself.

**Comment by Diggsey** [comment]
It's very easy verify that a custom hash implementation is correct, especially in rust where you don't have to worry about memory safety as much. Checking an entire protocol or cipher is much more difficult, because there are so many possible execution paths.

**Comment by thestinger** [comment]
Modern block ciphers and stream ciphers both tend to be incredibly simple, and there aren't multiple execution paths in general. It's not significantly different from hashes.

**Comment by thestinger** [comment]
@tarcieri: Having a secure random number generator for the hash seeds and other use cases means having a stream cipher implementation too.

**Comment by tarcieri** [comment]
@thestinger you need an API for getting cryptographic randomness, but you only need to use it once at the time the program starts. Once you have the key for SipHash seeded you can reuse the same key for all hashing operations globally

**Comment by ciphergoth** [comment]
Totally support SipHash. But I'm not sure I see the point of including other hash functions. Without a public key signature scheme, you can only verify hashes you already hold, which seems pretty limiting for the applications you set out.

A secure random number generator does seem desirable, but it's a very tricky proposition—it's very platform dependent, it's likely to depend on a good stream cipher and a good hash function, and if there's any platform on which you find you need to do your own entropy management you'll end up in deep water fast. I'm not sure it's a good feature to try to standardize for the 1.0 release.

**Comment by ciphergoth** [comment]
Also small terminological note: SipHash is a PRF, not a message digest function like SHA-2/Blake2.

**Comment by tarcieri** [comment]
It's not a hash function, it's a PRF? Really? Next you'll be telling me it's not a block cipher, it's a PRP :wink: I might also note it has "hash" in its name.

If you really want to get pedantic about it, it's providing a behavior a lot like a MAC (specifically keyed hashing)

**Comment by thestinger** [comment]
@ciphergoth: SipHash is useless without a seed, so the OS requirements are the same for both SipHash and a CSPRNG... the requirements are there on every platform Rust supports.

**Comment by thestinger** [comment]
@ciphergoth: A stream cipher is a CSPRNG. There's nothing else that's required. You need to retrieve an initial seed from the operating system. Re-seeding it is *optional* and can actually hurt rather than helping. Not providing a CSPRNG means that people are going to use an insecure RNG for cases where they should not... the absence of the feature is a security vulnerability in practice.

http://blog.cr.yp.to/20140205-entropy.html

**Comment by tarcieri** [comment]
@ciphergoth re: verifying artifacts, what you said is true, however even with just hash functions you can decompose the dependencies into a Merkle tree, so for example a bootstrapping tool can pull in snapshots of all of its subresources and confirm their integrity.

**Comment by ciphergoth** [comment]
If all the platforms you need to run on can provide a good seed then I take it all back, including an RNG is very desirable.

I still feel there's a very strong presumption against including things in 1.0, since if you leave something out and it was a mistake you can include it later, but if you put it in or give it the wrong API you are in big trouble. Since Rust has a good dependency management story it doesn't seem like a big problem to use that to get hold of the functions you need.

**Comment by thestinger** [comment]
> If all the platforms you need to run on can provide a good seed then I take it all back, including an RNG is very desirable.

A seed is obviously needed for SipHash to be worth anything so I don't understand the distinction you're making.

**Comment by thestinger** [comment]
> Since Rust has a good dependency management story

It really doesn't. The most that can be said is that it has one. It's awful at doing proper reproducible releases and is yet another insecure packager manager without a package signing story or proper system integration.

**Comment by tshepang** [comment]
OT: @thestinger I would be keen to read a detailed blog post by you containing all Rust-related issues you have. You notice a lot, and the one about package signing is quite interesting.

**Comment by tarcieri** [comment]
@tshepang FWIW I made an issue about that here: https://github.com/rust-lang/crates.io/issues/75

**Comment by ciphergoth** [comment]
Are you saying that the issues you raise with Crate are a reason to put things in-tree?

**Comment by tarcieri** [comment]
@ciphergoth no, I already gave my rationale for that above (see rustc bootstrap and subresource integrity)

**Comment by ciphergoth** [comment]
Can you describe the sort of scenario you're thinking of in more detail? The hash of some other resource is included in the Rust sources themselves—what sort of resource do you have in mind and at what stage is it fetched? Also note that you currently have to have Python installed to build rustc; at a pinch you could use a hash function built into Python as a bootstrapping aid. I don't yet see a compelling enough picture to overcome the leave-things-out presumption, but it's very possible you're right and I'm just not seeing the whole picture.

**Comment by tarcieri** [comment]
I was really making a more general statement about the utility. I don't have some master plan mapped out in my head.

**Comment by ciphergoth** [comment]
I think it would probably be safe to add the hash function to the sources in the same change that makes use of it.

**Comment by tarcieri** [comment]
Sure, my point wasn't that hash functions should be included right now, merely that they should be "allowed"

**Comment by ciphergoth** [comment]
Oh interesting, thanks! It's used here as part of a mangling strategy for symbols and crate names.

https://github.com/rust-lang/rust/blob/master/src/librustc_trans/back/link.rs#L75

**Comment by tarcieri** [comment]
Hmm, I see that Rust vendors a Rust implementation of ChaCha20 for use as a PRNG:

https://github.com/rust-lang/rust/blob/master/src/librand/chacha.rs

Hard to say how I feel about that. I'm curious if anyone knows if that gets exposed with the name "secure" on it anywhere, or how the key is generated?

This is all I could find on it:

https://github.com/rust-lang/rust/wiki/Lib-rand

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#766

**Comment by l0kod** [comment]
cc rust-lang/cargo#1281
