### ISSUE TITLE
Add robust unicode support (probably via ICU bindings)

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#14656]
There's been lots of talk about unicode over the years. We have little support in the core libs, but need to provide something better for serious use. Best idea now is to wrestle libicu into a Rust crate. Start out-of-tree.

**Comment by ArtemGr** [comment]
@Jurily, https://gist.github.com/ArtemGr/91e88de7e17fbc571926

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#797
