### ISSUE TITLE
Create a more robust date/time crate

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#14657]
Just clone [JodaTime](http://www.joda.org/joda-time/). Start out of tree.

**Comment by John-Nagle** [comment]
So whatever happened with providing some usable date/time functions?
"https://github.com/depp/datetime-rs" isn't packaged as a Cargo crate, so it's not importable.
"https://github.com/luisbg/rust-datetime" isn't packaged as a Cargo crate.
"https://github.com/rust-lang/rust/wiki/Lib-datetime" is discussion without any conclusions or actions.

Can we at least have an agreed internal representation of time/date, to which operations can later be added?

**Comment by cmr** [comment]
@John-Nagle https://github.com/lifthrasiir/rust-chrono

**Comment by John-Nagle** [comment]
OK, thanks. That should be mentioned at the Rust wiki.
It lacks date parsing functions. I'm writing parsing for the RFC3339 subset of ISO 8601, which is the form of timestamp found on email and RSS feeds.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#619

**Comment by John-Nagle** [comment]
It lacks date parsing functions. This is documented ("Advanced offset handling and date/time parsing is not yet supported (but is planned).") I happen to need RFC 822 date parsing ("Tue, 20 Jan 2015 17:35:20 -0800") but others may need other formats.

**Comment by lifthrasiir** [comment]
@John-Nagle If you are interested, please participate in lifthrasiir/rust-chrono#12.

**Comment by luisbg** [comment]
Sorry guys. I got very busy with interviews and a new job, and I couldn't finish my work on rust-datetime. Hopefully it can serve as a base or reference for future development in this topic.
