### ISSUE TITLE
Generic SQL bindings

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#14658]
We need a generic library for SQL with implementations for at least MySQL and PostgreSQL.

Prefer a design that has a typed AST that can be checked at compile time. I'm told [SqlAlchemy core](http://docs.sqlalchemy.org/en/rel_0_9/index.html) does this well.

cc @kmcallister

Start out of tree. This crate would ideally be distributed by cargo, not as part of the main distro.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#798
