### ISSUE TITLE
Don't distribute stage1 artifacts

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#14662]
For what I mean by "stage1 artifact", see [this comment](https://github.com/mozilla/rust/pull/14650#issuecomment-45155184). The gist of it is that we don't need to distribute things built by the stage1 compiler, only things built by the stage2 compiler.

The tricky part will be figuring out where the host stage2 artifacts go. We could place them in `$prefix/lib`, but there's a danger of pollution. We could also only place them in `$prefix/lib/rustlib/$host/lib`, but then there's a danger of the `rustc` executable not being able to load these libraries seamlessly via rpath.

Solving this should deal with #13421, #11195, and #13733

**Comment by steveklabnik** [comment]
Traige: as far as I know, this is still an issue today.

**Comment by oblitum** [comment]
cc #16029

**Comment by alexcrichton** [comment]
We've changed enough about our distribution that I don't believe this is relevant any more, so closing.
