### ISSUE TITLE
Use benchmarks to set up a website tracking rust performance

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#14661]
Like http://speed.pypy.org/. This will require someone in moco to image a physical machine and set up a new buildbot builder before it makes any progress.

**Comment by estsauver** [comment]
Hey @brson, it looks like it might be possible to build on http://huonw.github.io/isrustfastyet/mem/ . Is that sort of what you're thinking?

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#635
