### ISSUE TITLE
Result of `make doc` is confusing

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#14705]
~~~
make: Nothing to be done for `doc'.
~~~

That's because `doc` refers just to the directory of that name.  The `PHONY` docs target is named `docs`.

I don't know what exactly to do about this, but it's confusing.

**Comment by duckinator** [comment]
Adding a line to the Makefile that says `doc: docs` will make them equivalent, if that's what's wanted.

**Comment by steveklabnik** [comment]
I _think_ that should be fine. Let's see! Thank you!
