### ISSUE TITLE
Build with extern llvm fails

### ISSUE THREAD

**Issue by jauhien** [rust-lang/rust#14729]
I have this issue:

I have the last llvm from the live ebuild on Gentoo installed (it means I have compiled the last version from llvm upstream git).

I try to compile rust using this llvm with commands

```
./configure --prefix=/usr --llvm-root=/usr --enable-clang
make
```

And I have this error:

```
jauhien@zcj rust % make
cfg: build triple x86_64-unknown-linux-gnu
cfg: host triples x86_64-unknown-linux-gnu
cfg: target triples x86_64-unknown-linux-gnu
cfg: enabling more debugging (CFG_ENABLE_DEBUG)
cfg: host for x86_64-unknown-linux-gnu is x86_64
cfg: os for x86_64-unknown-linux-gnu is unknown-linux-gnu
cfg: using CC=clang (CFG_CC)
cfg: using CXX=clang++ (CFG_CXX)
cfg: no pdflatex found, deferring to xelatex
cfg: no xelatex found, deferring to lualatex
cfg: no lualatex found, disabling LaTeX docs
cfg: no pandoc found, omitting PDF and EPUB docs
cfg: no llnextgen found, omitting grammar-verification
failed to run llconfig: args = `['/usr/bin/llvm-config', '--libs', '--system-libs', 'x86', 'arm', 'mips', 'ipo', 'bitreader', 'bitwriter', 'linker', 'asmparser', 'jit', 'mcjit', 'interpreter', 'instrumentation']`
llvm-config: unknown component name: arm

make: *** [/home/jauhien/work/rust/rust/src/librustc/lib/llvmdeps.rs] Error 1
```

What can be the reason for this? Is this something bad with rust or with my setup?

I'm trying to compile the version of rust from the commit 8e9e484d7089590ce63bfe21723d7ee0c50be8f4

**Comment by steveklabnik** [comment]
Triage: is this still relevant today?

**Comment by cardoe** [comment]
@steveklabnik: I'm trying to build Rust 1.7.0 on Gentoo with the system LLVM which happens to be 3.7.1. This issue is not occurring but its failing for another reason.

**Comment by ustcscgy** [comment]
Hello everyone, I just build rust 1.10.0 on Gentoo with LLVM[-multitarget] (3.8.0-r3), without errors.

BTW, currently build rust with clang on Gentoo has another bug (already on gentoo bug tracker).

**Comment by cardoe** [comment]
Yes. I've got support in Gentoo for Rust building against the Gentoo provided LLVM for some time now. This issue can be closed.

**Comment by alexcrichton** [comment]
Yay!
