### ISSUE TITLE
Create multi-arch nightlies

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#14795]
Some people would like to be able to cross-compile from nightlies.

**Comment by huonw** [comment]
This is happening as part of the new rustup/multirust, and there's probably a better/newer bug? (Maybe @brson, @alexcrichton or @edunham knows?)

At least https://github.com/rust-lang/rust/issues/17356 is relevant.

**Comment by alexcrichton** [comment]
I also thought that there may be a newer bug but I can't seem to find it, so perhaps this can suffice!

**Comment by alexcrichton** [comment]
This is basically done with rustup now, so closing.
