### ISSUE TITLE
Re-gate on auto-win-32-nopt-c

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#14791]
I am turning off gating for the auto-win-32-nopt-c builder on buildbot. We should consider turning it back on at some point.

The builder has recently been failing in stage1 due to what I suspect is an OOM. We print no errors on OOM, but a stack trace from awhile ago pointed at an OOM in an unoptimized rustc compiling an unoptimized rustc.

**Comment by steveklabnik** [comment]
@alexcrichton whats the status of this today?

**Comment by alexcrichton** [comment]
No proress

**Comment by alexcrichton** [comment]
We've turned off all nopt-c builds, so closing.
