### ISSUE TITLE
rustdoc: parenthetical after attribute syntax breaks HTML

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#14814]
~~~ .rs
/// Declare with
/// #[foo] (my favorite attribute)
#[foo]
pub fn main() { }
~~~

produces

~~~ .html
<pre class='rust fn'>pub fn main()</pre><div class='docblock'><p>Declare with</p>

<h1 id="<a-href="my%20favorite%20attribute">foo</a>" class='section-header'><a
                           href="#<a-href="my%20favorite%20attribute">foo</a>"><a href="my%20favorite%20attribute">foo</a></a></h1>
~~~

because it parses as a Markdown link.  The right thing to do is put backtics around the attribute syntax, but this is still a really confusing failure.

It would also be an XSS vulnerability if we hosted docs generated from user contributed libraries:

~~~ .rs
/// Declare with
/// #[foo] (my favorite attribute) <script>alert(document.cookie)</script>
~~~

But the conservative solution there is to put user content on another origin (e.g. `rust-user-content.org`) which doesn't hold any credentials.

**Comment by alexcrichton** [comment]
I'm going to close this as not-a-bug as by using Markdown we're committing ourselves to one form of syntax or another, and any XSS vulnerabilities or vectors would probably be handled when we set up hosting!

**Comment by tomjakubowski** [comment]
I'd recommend that we make a very clear warning somewhere that hosting docs for arbitrary crates opens up XSS attacks and proper precautions should be taken. It's important to remember that crates.io isn't the only domain hosting rustdocs.



—

**Comment by tomjakubowski** [comment]
Er, I mean docs.rust-lang.org or whatever. Although it's conceivable that crates.io (or a sub domain) will host docs as well some day.



—

**Comment by kmcallister** [comment]
Better register `crates-user-content.io`...

**Comment by kmcallister** [comment]
> Doing this safely requires completely parsing the HTML and whitelisting tags / attributes at the AST level, then re-serializing as well-formed HTML.

fwiw I think html5ever is up to this task now.

**Comment by alexcrichton** [comment]
@tomjakubowski good idea! I've opened https://github.com/rust-lang/rust/issues/24160

**Comment by lfairy** [comment]
@kmcallister According to rust-lang/crates.io#91, some members of the community have reserved rustdoc.org and doc.rs for this purpose. So getting a domain is not a blocker.
