### ISSUE TITLE
IdentTT can't be called as a non-item macro

### ISSUE THREAD

**Issue by Ogeon** [rust-lang/rust#14817]
I have written an IdentTT syntax extension which is supposed to return a block expression and be used like this:

``` Rust
fn main() {
    let something = my_macro! something_else (...);
}
```

but this just results in `error: expected open delimiter`, pointing at the provided identifier, and changing it to

``` Rust
fn main() {
    my_macro! something_else (...);
}
```

results in `error: non-item macro in item position`.

**Comment by steveklabnik** [comment]
This example no longer compiles, because `BasicIdentMacroExpander` no longer exists. If you still think this is a bug, please post an updated example, but until we can reproduce, I'm going to give this a close.

**Comment by Ogeon** [comment]
It's not as relevant now as it was back then, since syntax extensions are staying unstable and `macro_rules!` doesn't produce `IdentTT` macros, as far as I know. I'll let it go for now.

**Comment by ptal** [comment]
Should be re-openned. Example that compiles and fails here: https://github.com/ptal/procedural-macro
Compile error is:

```
Compiling procedural_macro v0.1.0 (file:///home/ptalbot/repositories/procedural-macro)
tests/test.rs:6:3: 6:16 error: non-item macro in item position: macro_as_expr
tests/test.rs:6   macro_as_expr! e {}
                  ^~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `procedural_macro`.
```

As adviced by @nrc on IRC I am trying to solve the problem myself but need some directions.

I think the problem starts in parse/parser.rs, the comment:

 `// if it has a special ident, it's definitely an item`

is probably a false assumption, why should an IdentTT macro be an item? My proposal to solve this cleanly is to add a field `ident: Option<Ident>` to `Mac_`. Does it sound good?

**Comment by nrc** [comment]
First note: that comment doesn't quite match the code - we should remove the word "special" from the comment.

I agree that this assumption seems unnecessary. You can probably relax this here. But you will have to check some where else for this condition for IdentTT macros which expand to items but don't have a semi-colon or braces. I guess you can't do that until expansion.

I think the bulk of work will need to be done in src/libsyntax/ext/expand.rs, where there's a bunch of places which work with NormalTT but not IdentTT.

Adding an `Option<Ident>` to `Mac_` sounds like a good idea. For macros which are an Item, the ident in the Item should be `token::special_idents::invalid`.

**Comment by spinda** [comment]
For what it's worth, I ran into this today after designing an EDSL around IdentTT in the expression context. Any guidance on fixing this in the current state of the code?

**Comment by Mark-Simulacrum** [comment]
Unfortunately I don't think this bug is actionable since I can't find working examples. @spinda if you still need assistance, I think an internals.rust-lang.org thread may be the most helpful.
