### ISSUE TITLE
Automatically rollup simple PRs

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#14826]
https://github.com/graydon/bors/issues/34

**Comment by frewsxcv** [comment]
[This did get implemented in bors at some point](https://github.com/graydon/bors/pull/47), though we recently switched to homu which [also supports the rollup feature](https://github.com/barosl/homu/commit/fb216feb66bb1830d6fce65a006a109683d98c9a). This issue can be probably be closed

**Comment by Aatch** [comment]
Bors could do this for a short time and Homu can also do it.
