### ISSUE TITLE
Start speculating bors' builds

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#14825]
We've got almost all our builds on EC2 now, and upstream bors can build multiple integration branches at a time. We should be able to just double the amount of VM's in service to increase throughput.

**Comment by steveklabnik** [comment]
Triage: no changes here that i'm aware of

**Comment by alexcrichton** [comment]
Given how we're already stretching the limits of our infrastructure today, I don't think that this is gonna happen any time soon, so I'm gonna close. Always on the back of our minds though!
