### ISSUE TITLE
Confusing error message when using int as type parameter

### ISSUE THREAD

**Issue by excepttheweasel** [rust-lang/rust#14833]
Trying to use an int in the type system:

https://gist.github.com/excepttheweasel/9100eeb5d6467070db03

Gives a somewhat confusing error:
                                                                                                                                            
    q.rs:14:35: 14:37 error: expected type, found token LIT_INT_UNSUFFIXED(10i64)
    q.rs:14   type SmallU8Queue = Queue<uint, 10>;
                                              ^~

/cc @cmr

**Comment by steveklabnik** [comment]
This now says "Unexpected type, found 10." Much better!
