### ISSUE TITLE
suggest binding site when issuing "try using a local type parameter instead" err msg

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#14844]
UPDATE: [Mentoring instructions below.](https://github.com/rust-lang/rust/issues/14844#issuecomment-331316573)

--

Here is some code:

``` rust
pub trait Bar { fn m(&self); }

pub fn foo<T>() {
    struct S<T>;
    impl Bar for S<T> {
        fn m(&self) { println!("Hello World"); }
    }
    let s = S::<T>;
    s.m();
}

pub fn main() {
    foo::<int>();
}
```

Here is a transcript of a compilation attempt:

```
% rustc /tmp/bar.rs
error: can't use type parameters from outer function in the substitution of `foo::S<T>`; try using a local type parameter instead
/tmp/bar.rs:9:7: 9:10 error: type `foo::S<T>` does not implement any method in scope named `m`
/tmp/bar.rs:9     s.m();
                    ^~~
error: can't use type parameters from outer function in the substitution of `foo::S<T>`; try using a local type parameter instead
error: can't use type parameters from outer function in the substitution of `fn(&foo::S<T>)`; try using a local type parameter instead
error: can't use type parameters from outer function in the substitution of `fn(&foo::S<T>)`; try using a local type parameter instead
error: can't use type parameters from outer function in the substitution of `foo::S<T>`; try using a local type parameter instead
error: can't use type parameters from outer function in the substitution of `foo::S<T>`; try using a local type parameter instead
error: can't use type parameters from outer function in the substitution of `foo::S<T>`; try using a local type parameter instead
error: can't use type parameters from outer function in the substitution of `foo::S<T>`; try using a local type parameter instead
error: can't use type parameters from outer function in the substitution of `foo::S<T>`; try using a local type parameter instead
error: can't use type parameters from outer function in the substitution of `foo::S<T>`; try using a local type parameter instead
error: aborting due to 11 previous errors
% 
```

First off, maybe we should be aborting the compilation a little sooner rather than emitting so many seemingly redundant error messages.

Second, I was scratching my head for a little while because I was saying to myself "`T` _is_ a local type parameter".  Of course, it is not local _enough_; one needs to change the `impl Bar for S<T>` to `impl<T> Bar for S<T>`.

So, I think it would be good if the error message suggested this; e.g.:

> error: can't use type parameters from outer function in the substitution of `foo::S<T>`; try adding a local type parameter to the `impl`

or

> error: can't use type parameters from outer function in the substitution of `foo::S<T>`; try using a local type parameter like `impl<T> Bar for ...`

**Comment by oli-obk** [comment]
Same error, different situation: 

```rust

struct A<T> {
    inner: T,
}

impl<T> Iterator for A<T> {
    type Item = u8;
    fn next(&mut self) -> Option<u8> {
        fn helper(sel: &Self) -> u8 {
            unimplemented!();
        }
        Some(helper(self))
    }
}

fn main() {
}
```

yields

```
<anon>:6:24: 6:25 error: can't use type parameters from outer function; try using a local type parameter instead
<anon>:6 impl<T> Iterator for A<T> {
                                ^
<anon>:6:24: 6:25 error: use of undeclared type name `T`
<anon>:6 impl<T> Iterator for A<T> {
                                ^
```

changing the inner function to 

```rust
struct A<T> {
    inner: T,
}

impl<T> Iterator for A<T> {
    type Item = u8;
    fn next(&mut self) -> Option<u8> {
        fn helper<U>(sel: &A<U>) -> u8 {
            unimplemented!();
        }
        Some(helper(self))
    }
}

fn main() {
}
```

solves the problem

**Comment by steveklabnik** [comment]
Triage: @pnkfelix 's example now produces the same error as @oli-obk 's.

**Comment by pnkfelix** [comment]
Yes the number of errors reported is now reasonable,  but it still leads to head scratching because it doesn't make it clear that one needs a binding on the `impl` block

**Comment by estebank** [comment]
Current output:

```
error[E0401]: can't use type parameters from outer function; try using a local type parameter instead
 --> src/main.rs:5:20
  |
5 |     impl Bar for S<T> {
  |                    ^ use of type variable from outer function

error[E0392]: parameter `T` is never used
 --> src/main.rs:4:14
  |
4 |     struct S<T>;
  |              ^ unused type parameter
  |
  = help: consider removing `T` or using a marker such as `std::marker::PhantomData`
```

---

[`adjust_local_def`], when [checking the type parameters](https://github.com/rust-lang/rust/blob/17f56c549c35bb2cb316e5abff116e65277c7bb1/src/librustc_resolve/lib.rs#L3016-L3035) we should look at the current scope (I believe it is the `rib`'s scope, the `def`'s scope is the type argument) to get the span for it and point at the definition. I believe the ideal output is the following:

```
error[E0401]: can't use type parameters from outer function
  --> src/main.rs:5:20
3 | pub fn foo<T>() {
  |            - type variable from outer function
...
5 |     impl Bar for S<T> {
  |                    ^ use of type variable from outer function
note: try using a local type parameter instead
  |
5 |     impl<T> Bar for S<T> {
  |         ^^^
```

Implementing the suggestion might be slightly harder than just pointing out at the outer type parameter.

[`adjust_local_def`]: https://github.com/rust-lang/rust/blob/17f56c549c35bb2cb316e5abff116e65277c7bb1/src/librustc_resolve/lib.rs#L2943-L2948

**Comment by zilbuz** [comment]
I'll try to tacke that. @estebank Where should I contact you if I have some questions ?

**Comment by zilbuz** [comment]
So I poked around, and the `rib` variable doesn't have any span informations: its `bindings` member is empty and the `kind` member doesn't carry any additionnal informations. How should I retrieve the span?

**Comment by estebank** [comment]
@zilbuz sorry for not getting back to you yesterday. As mentioned in passing in https://github.com/rust-lang/rust/issues/47319#issuecomment-356770975, we probably should modify `ParamTy` to include its span, so that we can use it here. This will require you to modify several files to pass in the span to it and to ignore it on usages, but it should be straightforward.

You can keep updating this ticket, and once you've created a PR move the conversation there. Make sure to include "r? @estebank" in the description so that I review it.

**Comment by zilbuz** [comment]
Won't the `ParamTy` here contain the span for the `T` in `impl Bar for S<T>` (the one we already have)? I'm a bit confused about what the `ParamTy` represents here I think. Anyway I'll try to modify the `ParamTy` and get back to you in the PR.
