### ISSUE TITLE
#[plugin_registrar] is not type-checked

### ISSUE THREAD

**Issue by kimhyunkang** [rust-lang/rust#14841]
`#[plugin_registrar]` functions are not type-checked, which exposes unsafe memory content to the plugin modules. Nor are they checked for being `pub`.

I could reproduce this on the latest nightly build for x64 linux. Minimal reproducing example follows.

plugin_lib.rs :

``` rust
#![crate_id = "plugin_lib"]
#![crate_type = "dylib"]

#![feature(plugin_registrar)]

#[plugin_registrar]
pub fn plugin_registrar(f: || -> ()) {
    f()
}
```

plugin_test.rs : 

``` rust
#![feature(phase)]

#[phase(plugin)]
extern crate plugin_lib;

fn main() {
    ()
}
```

compilation:

``` sh
kimhyunkang@kanie:~/project/segfault_test$ rustc --version
rustc 0.11.0-pre-nightly (4fdc27e 2014-06-10 23:37:06 -0700)
host: x86_64-unknown-linux-gnu
kimhyunkang@kanie:~/project/segfault_test$ rustc plugin_lib.rs
kimhyunkang@kanie:~/project/segfault_test$ rustc plugin_test.rs -L .
Segmentation fault (core dumped)
```

**Comment by steveklabnik** [comment]
Updated code to reproduce:

```rust
// plugin_lib.rs
#![feature(plugin_registrar)]

#[plugin_registrar]
pub fn plugin_registrar(f: fn() -> ()) {
    f()
}
```

and

```rust
// plugin_test.rs
#![feature(plugin)]
#![plugin(plugin_lib)]

fn main() {
    ()
}
```

testing:

```bash
$ rustc plugin_lib.rs --crate-type=dylib
$ rustc plugin_test.rs -L .
Segmentation fault
$ rustc --version
rustc 1.7.0-nightly (2370d461a 2015-12-30)
```

**Comment by Mark-Simulacrum** [comment]
With `rustc 1.18.0-nightly (bbdaad0dc 2017-04-14)`, I no longer get a segmentation fault with the code in @steveklabnik's post above. Presumably fixed, closing.

**Comment by Mark-Simulacrum** [comment]
Actually, I think that was a problem with my shell, presumably... I'm not sure it segfaults, but it doesn't successfully compile `plugin_test.rs`, exits with exit code 1, and no error message.

**Comment by steveklabnik** [comment]
When this issue was opened, we weren't sure what the system for extending rust may be. Plugins are never going to be shown to end-users, and so I don't believe this is ever going to be fixed. Closing.
