### ISSUE TITLE
Incomplete tests for non-android arm & mips.

### ISSUE THREAD

**Issue by luqmana** [rust-lang/rust#14848]
`run-pass/intrinsic-alignment.rs` and `run-pass/rec-align-u64.rs` don't run on non-android arm/mips since we haven't filled in a cfg for it. So they just fail with 'no main function'.

Pretty easy to fix: determine the right values for alignment/size and fill in the values.

**Comment by steveklabnik** [comment]
Triage: it looks like `arm` may have been added, but not `mips`.

**Comment by AnthonyBroadCrawford** [comment]
@steveklabnik may I please take this?

**Comment by brson** [comment]
Looks fixed to me. Both tests now cover all hardware architectures with one path for x86 and one for every other.
