### ISSUE TITLE
Machine readable rustc output

### ISSUE THREAD

**Issue by Arcnor** [rust-lang/rust#14863]
Hi,

I'm working on IDE integration (IntelliJ IDEA) for Rust, and it will be nice to have some kind of machine readable output when compiling with `rustc`, like the `gdb/mi` interface does for debugging.

Are there any plans to do something like this?

Maybe the best option will be integrating directly with `rustc`via JNI, although I'm not sure if this is actually feasible, or if will give me any better output.

**Comment by m-bra** [comment]
Also, it would be good to have an option to check the syntax only, or even provide autocomplete proposals.

**Comment by jdm** [comment]
@m-bra: `rustc --parse-only` and #21323.
