### ISSUE TITLE
Semantic of `std::str::CharSplitsN` and `regex::RegexSplitsN` don't match.

### ISSUE THREAD

**Issue by Kimundi** [rust-lang/rust#14899]
Both implement an `Iterator` over slices of a string that is being split at a pattern, but
`std::str::CharSplitsN` splits at most `N` times, yielding `N + 1` strings; while `regex::RegexSplitsN` splits at most `N - 1` times, yielding `N` strings.

This is inconsistent and confusing, and one of them should be changed to have the semantic of the other, however it is unclear which is the better one.

**Comment by aturon** [comment]
@Kimundi I believe this should fall out of your more general API changes? Are we nearing a point where we can move forward on that?

**Comment by alexcrichton** [comment]
regexes have now moved externally, so I'm going to close this
