### ISSUE TITLE
libcollections: TrieMap is not a general Trie

### ISSUE THREAD

**Issue by reem** [rust-lang/rust#14902]
TrieMap ought to be called RadixMap, PatriciaTree, or something other than TrieMap, considering that it only works with `uint` keys.

Ideally, TrieMap would work for any valuable that is a `RandomAccessIterator<T: Eq> `, or something similar, which would make it much more useful/general.

**Comment by Gankro** [comment]
TrieMap is not part of the std lib anymore.
