### ISSUE TITLE
Consider installing HTML documentation

### ISSUE THREAD

**Issue by SiegeLord** [rust-lang/rust#14916]
The best documentation to use while programming in Rust is the one that matches the nightly/master that is installed. To that end, it'd be convenient if `install.sh` installed the HTML documentation somewhere (e.g. `${PREFIX}/share/doc/rust` for Linux). Something similar should be done for Windows.

**Comment by brson** [comment]
We're installing the documentation now. I have a todo to make the tarball installers allow selection of individual components to *not* install docs, but considering this done.

**Comment by michaelsproul** [comment]
Thanks! :smile:

**Comment by vks** [comment]
Is there an option for not installing the docs? For me it takes by far the longest when updating.
