### ISSUE TITLE
UdpSocket is missing close_{read,write}

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#14926]
These weren't added recently, and I don't think there's a fundamental reason for not offering this, so we should probably offer it.

**Comment by alexcrichton** [comment]
This is being handled by https://github.com/rust-lang/rfcs/pull/807.

**Comment by LorenVS** [comment]
I think this issue might need to be re-opened... As part of the IO reform, I believe a shutdown method was supposed to be added to UdpSocket (the docs for std::io::Shutdown mention that it should exist). However, the method doesn't exist yet, and rfc 807 appears to be closed

**Comment by alexcrichton** [comment]
Oops yes this is definitely an oversight, [I've opened a new issue](https://github.com/rust-lang/rust/issues/23194) as this isn't quite appropriate any more.
