### ISSUE TITLE
`#![no_implicit_prelude]` should only apply to the current module, not to all children

### ISSUE THREAD

**Issue by Kimundi** [rust-lang/rust#14969]
Currently, the `#![no_implicit_prelude]` attribute can be used to disable the `libstd` prelude imports for a module. However, it seems to disable them for all submodules as well, which makes no sense seeing how the prelude is just a bunch of `use` statements, and those don't propagate into child modules.

Example:

``` rust
fn a() {
    let _: Vec<usize> = vec![];
}

mod foo {
    #![no_implicit_prelude]

    fn b() {
        let _: Vec<usize> = vec![];
    }

    mod bar {
        fn c() {
            let _: Vec<usize> = vec![];
        }   
    }
}

fn main() {}
```

... which results in an error for the `bar` module as well:

```
<anon>:9:16: 9:25 error: use of undeclared type name `Vec`
<anon>:9         let _: Vec<usize> = vec![];
                        ^~~~~~~~~
<anon>:14:20: 14:29 error: use of undeclared type name `Vec`
<anon>:14             let _: Vec<usize> = vec![];
                             ^~~~~~~~~
```

As a fix, `#![no_implicit_prelude]` should be changed to only apply to the module it is applied on.

**Comment by steveklabnik** [comment]
Triage: this still works this way today.

**Comment by Nemo157** [comment]
I agree that disabling for the whole crate seems like it would be the common case (as a contra contra point it's how I want to use it :stuck_out_tongue:).

If it does get changed then it would be nice to be able to apply it as a crate attribute as well that disables the prelude throughout the crate (although, I guess that would mean not being able to apply it to just the root module, maybe it would need to be a different name for the crate only attribute?).

**Comment by Mark-Simulacrum** [comment]
From [RFC 501](https://github.com/rust-lang/rfcs/blob/master/text/0501-consistent_no_prelude_attributes.md):

> Make name and behavior of the #![no_std] and #![no_implicit_prelude] attributes consistent by renaming the latter to #![no_prelude] and having it only apply to the current module.

Once https://github.com/rust-lang/rust/issues/20561 is implemented, this will no longer be an issue, since the `#![no_prelude]` attribute will apply only to the current module. As such, this isn't tracking anything more than that is, so I'm going to close this out.
