### ISSUE TITLE
standardise whether detailed descriptions & examples of types go on the type or the module

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#14967]
E.g. [`Result`](http://doc.rust-lang.org/master/std/result/type.Result.html) is very brief, referring to the module [`std::result`](http://doc.rust-lang.org/master/std/result/), which is very extensive, and even includes a redefinition of the `Result` type!

On the other hand [`std::collections::hashmap`](http://doc.rust-lang.org/master/std/collections/hashmap/) is short, while [`HashMap`](http://doc.rust-lang.org/master/std/collections/hashmap/struct.HashMap.html) is more detailed (i'll note that these aren't precisely equivalent, since `HashSet` is in that module too). Similarly, [`Vec`](http://doc.rust-lang.org/master/std/vec/struct.Vec.html) is longer than [`std::vec`](http://doc.rust-lang.org/master/std/vec/).

**Comment by aturon** [comment]
cc me

**Comment by Gankro** [comment]
Steve's gut sounds right to me. Would especially work better if we had sane intra-links.

**Comment by Gankro** [comment]
Although doc'ing the type can be more "portable" in the face of re-exports.

**Comment by aturon** [comment]
Hm, so I'm now starting to prefer the other direction. 

Module-level docs are great for telling an overall narrative for people who are exploring, but they are not good when people are looking up a type/method etc. I guess the ideal option would be "both"? But I'm not really sure. As @Gankro says links could help...
