### ISSUE TITLE
Refactor liveness to work on the CFG and use dataflow

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#14971]
Now that @pnkfelix has landed CFG and is about to land dataflow, it's time for liveness code to be rewritten to use it. 

Currently liveness has two responsibilities:

- issuing warnings for dead writes
- checking that functions always return a value or fail

Probably liveness as a pass should go away and be moved into borrowck.

cc @zwarich

**Comment by steveklabnik** [comment]
I _think_ frontend is the right tag?

**Comment by arielb1** [comment]
This is now a part of the MIR issue.
