### ISSUE TITLE
Need to be able to load modules from user-specified paths

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#14975]
Build systems want to place generated .rs files into the *build* directory, which typically can have an arbitrary location relative to the source directory. Rust has no way to tell the compiler to load a module source file from a user-specified directory, only from statically-known directories, as in

```
#[path = "../../foo.rs"]
mod foo;
```

Both Rust and Servo incorporate generated .rs files in their build, and they both need to put those in the source directory, instead of the build directory.

**Comment by steveklabnik** [comment]
The `build.rs` feature of Cargo would seem to subsume this issue, and changing the `path` attribute would require an RFC these days, and I'm not even sure `path` is going to get that much (if any) usage now.
