### ISSUE TITLE
Bad error message on typecasting while using '<' operator

### ISSUE THREAD

**Issue by bollu** [rust-lang/rust#14995]
```
if 1 as f32 < 2.
```
prints out the error message

```
expected type, found token LIT_INT_UNSUFFIXED(2i64)
```

However, ```>```, ```==```, and ```!=```  do the right thing.

**Comment by steveklabnik** [comment]
This now says 'expected type, found 2'.

I feel like this is a dup...

**Comment by steveklabnik** [comment]
This is in fact a duplicate. https://github.com/rust-lang/rust/issues/11962#issuecomment-178739549
