### ISSUE TITLE
Operator precedence for "as" seems incorrect in the manual

### ISSUE THREAD

**Issue by simias** [rust-lang/rust#15008]
The manual in section *7.2.11.8 Operator precedence* states that "* / %" bind stronger than "as", however rustc seems to disagree:

```rust
let _a = 1. * 1 as f32;
let _b = 1. * (1 as f32);
let _c = (1. * 1) as f32;
```

Only the last expression triggers an error, the _a seems to evaluate like _b.

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/22304#issuecomment-74344075
