### ISSUE TITLE
Remove the deprecated bytes!() macro

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#15018]
The `bytes!()` macro is deprecated (see issue #15017) in favor of `b"foo"` byte literals. It should be removed at some point, preferably before 1.0.

CC @alexcrichton

**Comment by steveklabnik** [comment]
This has been removed.

**Comment by goertzenator** [comment]
Can this be brought back as "concat_bytes!" ?  Byte literals are great, but the concat part has been lost.  My use case is to append a null byte to byte literals at compile-time.  bytes! would have been great for that.  We have concat! and concat_idents!, so concat_bytes! would seem to make sense.

**Comment by SimonSapin** [comment]
Yeah, makes sense. The best way to make it happen is probably an RFC baked by a pull request.
