### ISSUE TITLE
flowgraph: extend cfg to support whole fn item rather than just a block

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#15020]
There's a fixme that landed in the dataflow-atop-cfg work: 
https://github.com/rust-lang/rust/commit/75340f41763c4166172af24c8db676c1da97910d#diff-158b34791d327b238be103c2d1867e71R195

In summary: right now there is a bit of a hack in the dataflow code to introduce definitions for all of the patterns bound by the `fn_decl` for the fn item being analyzed.

It might be much cleaner to just fold all those formals into the graph structure itself, by extending the cfg code so that, in addition to accepting a block as it does today, it also accepts a whole fn item, and then does the right thing for the bindings introduced by the `fn_decl`.

**Comment by steveklabnik** [comment]
Triage: this is a very old ticket, which is a bit in the weeds... but I read this as saying "cfg should work on fn items", which does work? It's not clear to me.

**Comment by wesleywiser** [comment]
The linked FIXME doesn't exist any more. I guess this can be closed?

**Comment by Mark-Simulacrum** [comment]
per https://github.com/rust-lang/rust/issues/51002 I'm going to close this as we're trying to kill of cfg entirely
