### ISSUE TITLE
Unicode input on windows command line does not work

### ISSUE THREAD

**Issue by retep998** [rust-lang/rust#15028]
When using stdin with my rust program run from either the windows command line or git bash, any unicode characters are turned into question marks.
So "Алло" becomes `[63, 63, 63, 63]`.
If I change the codepage of the windows command line to utf-8 via `chcp 65001`, then when I enter in any unicode characters stdin returns EndOfFile.

On the flip side, output using libgreen works fine (because libuv translates utf-8 to utf-16 and calls `WriteConsoleW`), while output using libnative produces garbage for unicode because it writes utf-8 as if it were ascii.

Using windows 8.1 x64, with 32-bit Rust nightly.

**Comment by nagisa** [comment]
@retep998 how relevant is this now?

**Comment by retep998** [comment]
@nagisa For the most part it works. However the current code still cannot cope when characters encoded using multiple codeunits are broken across a read/write boundary. Plus having the API take [u8] is hardly ideal when we should be using the new `OsStr` thing.

**Comment by retep998** [comment]
Issue subsumed by https://github.com/rust-lang/rust/issues/23344
