### ISSUE TITLE
Serialization errors can only be created from the `Encoder`/`Decoder` methods

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#15036]
There is no way for a custom generic `Decodable`/`Encodable` instance (compatible with `#[deriving]` other) to return a new error since it's completely generic, that is,

```rust
#[deriving(Decodable)]
struct Foo {
    x: Bar
}

struct Bar { y: int }

// E has to be that generic to work with the deriving above,
// but this means this impl cannot manually create new errors
// (e.g. if y is supposed to be an even number, there's no way
// to emit "error: found odd number".)
impl<E, D: Decoder<E>> Decodable<D, E> for Bar { ... }
```

It might be nice if there was a `E: Error` trait (or some such) that `deriving` used, which has some basic constructors.

**Comment by alexcrichton** [comment]
This was [fixed for `Decoder`](http://doc.rust-lang.org/rustc-serialize/rustc_serialize/trait.Decoder.html#tymethod.error) and otherwise `Encoder` is stabilized so we can't change this any more. As a result, closing.
