### ISSUE TITLE
compiler ignores second trait with the same name

### ISSUE THREAD

**Issue by volth** [rust-lang/rust#15057]
My goal is to produce JSON for InfluxDb. 
It lists the field names for a bunch of structures and then the values for each structure (example: https://archive.today/MlLPR#selection-1687.201-1687.212)
So I use two `Encodable` traits for the same type  to serialize field names and values respectively (`myjson::EncodeFieldNames` and `myjson::EncodeFieldValues` are just slightly modified copies of `Encoder` from standard JSON module):

This code does not compile, I get the same compiler error as though only first `Encodable` was specified and the second `Encodable` was not in place.
```rust
fn write<T: Encodable<myjson::EncodeFieldNames<'a>,  io::IoError> +
            Encodable<myjson::EncodeFieldValues<'a>, io::IoError>>(to_encode_object: &T) {
   println!("names ={}", myjson::EncodeFieldNames::str_encode(to_encode_object));
   println!("values={}", myjson::EncodeFieldValues::str_encode(to_encode_object));
}
```

I found a workagound. But it is not nice.
```rust
fn write<T: Encodable<myjson::EncodeFieldNames<'a>,  io::IoError>,
         Q: Encodable<myjson::EncodeFieldValues<'a>, io::IoError>>(to_encode_object: &T, the_same_object: &Q) {
   println!("names ={}", myjson::EncodeFieldNames::str_encode(to_encode_object));
   println!("values={}", myjson::EncodeFieldValues::str_encode(the_same_object));
}
```

**Comment by steveklabnik** [comment]
`Encodable` has since been moved out of tree. If this issue still exists, please re-report it there, preferably with a compile-able sample. Thanks!
