### ISSUE TITLE
Extern varargs are not properly called with structs by value

### ISSUE THREAD

**Issue by jmgrosen** [rust-lang/rust#15084]
See the IR generated here for an example: http://is.gd/NAvO6M.
```llvm
%2 = call i8* (i8*, i8*, ...)* @objc_msgSend(i8* null, i8* %0, %"struct.CGRect<[]>"* %arg, i64 15, i64 2, i64 0)
```
should be something like
```llvm
%2 = call i8* (i8*, i8*, ...)* @objc_msgSend(i8* null, i8* %0, %"struct.CGRect<[]>"* byval align 8 %arg, i64 15, i64 2, i64 0)
```
(notice the `byval align 8` added to the struct argument).

It does not appear to happen for smaller structs: http://is.gd/4IB43w

**Comment by dotdash** [comment]
The example now gets the proper call with the `byval` attribute set,
