### ISSUE TITLE
--dep-info does not quote spaces in filenames

### ISSUE THREAD

**Issue by jpakkane** [rust-lang/rust#15124]
Rust's dependency scanner fails on files containing spaces (and possibly other special characters). As an example, here's the output of --dep-info when compiling a file called "2 sharedlib/stuff.rs":

libstuff-e4d2ee75-1.0.so: 2 sharedlib/stuff.rs

This is incorrect as it claims that the target depends on non-existing files "2" and "sharedlib/stuff.rs".

**Comment by alexcrichton** [comment]
This is now currently handled by adding `\` characters where necessary, so closing.

**Comment by sanxiyn** [comment]
FYI, this was fixed when #17627 was.
