### ISSUE TITLE
Remove the core::bool module

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#15133]
This module is soon to be used for nothing more than displaying documentation for primitives. As such, it should not exist, but we need somewhere to put the primitive docs, so rustdoc may need some tweaks.

**Comment by frewsxcv** [comment]
`libcore/bool.rs` was renamed to `libstd/bool.rs` in [this pull request](https://github.com/rust-lang/rust/pull/20006)

**Comment by alexcrichton** [comment]
This was done!
