### ISSUE TITLE
Searches including trait methods link to invalid anchors

### ISSUE THREAD

**Issue by colemickens** [rust-lang/rust#15169]
For example: http://doc.rust-lang.org/collections/?search=into_ascii_lower
includes a link to: http://doc.rust-lang.org/collections/string/struct.String.html#method.into_ascii_lower

Even though that anchor isn't present on that page. It is, however, on: http://doc.rust-lang.org/std/string/struct.String.html

@huonw asked me to file this as a bug; I'm not sure how to describe the exact bug: if it is that collections::string::String appears in the results, that it's missing on the collections::string::String page, and/or that std::string::String should be in the results.

**Comment by frewsxcv** [comment]
@colemickens Can you still replicate this issue?

**Comment by alexcrichton** [comment]
I believe this was fixed in the interim as methods in the "Trait Implementations" section now all have anchors!
