### ISSUE TITLE
The "ctime" field from stat is not time of file creation.

### ISSUE THREAD

**Issue by zookoatleastauthoritycom** [rust-lang/rust#15168]
https://github.com/rust-lang/rust/blob/108b8b6dc707775bd54aeea7820e0d473f556718/src/libstd/io/fs.rs#L332 seems to be reading the 4th field of stat result and storing it as "created", but if that 4th field is coming from `stat_ctime` then this is a bug, because `stat_ctime` is not the time of file creation, but is instead the most recent time that either the content or the metadata of the file changed: https://en.wikipedia.org/wiki/Stat_%28Unix%29#ctime

**Comment by alexcrichton** [comment]
This was handled in the new `std::fs`
