### ISSUE TITLE
Skip `LintPass`es whose lints are all `Allow`

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#15161]
Since each `LintPass` declares the lints it can emit, we could speed up lint checking by skipping passes whose lints are all `Allow`.  But some passes have side effects gathering information for other parts of the compiler, and those should always run.

**Comment by steveklabnik** [comment]
Traige: no change that I'm aware of.

**Comment by sanxiyn** [comment]
This doesn't seem workable, since `LintPass` only knows about lints's default levels, and lints's actual levels can be changed by attributes.

**Comment by steveklabnik** [comment]
Triage: no changes I'm aware of.

**Comment by Mark-Simulacrum** [comment]
I don't see how this can work since the level a lint warns can change with `#[deny/warn/etc]`. As such I'm going to close this.

**Comment by sanxiyn** [comment]
This can actually work, but workable strategy is now tracked at #42511.
