### ISSUE TITLE
pretty-rpass tests work only accidentally/fragilely

### ISSUE THREAD

**Issue by jbclements** [rust-lang/rust#15189]
AFAICT, the pretty-rpass tests pretty-print files and then ensure that they type-check. I wouldn't expect this to work in general, because pretty-printing does not respect hygiene. For instance, consider this program:

``` rust
#![feature(macro_rules)]

macro_rules! third(($e:expr)=>({let x = 2; *$e.get(x)}))

fn main() {
    let x = vec!(10u,11u,12u,13u);
    let t = third!(x);
    assert_eq!(t,12u);
}
```

Pretty-printing this with `--pretty expanded` results in a program where a `let x` is wrapped around two uses of `x`, one of which is an integer and one of which is a vector. Trying to type-check this doesn't work.

This issue is not just a hypothetical one; I removed unneccessary double-underscores from the index variable "__i" introduced by the expansion of a 'for' loop, and now a bunch of pretty-rpass tests are failing for the reasons given above.

In the short term, the easiest thing to do is to reinstitute the silly underscore before the i, but this is strictly short-term; the general problem is that the pretty-rpass test pass is broken, because pretty-print doesn't respect hygiene.

The fix would be to update pretty-print to generate names by mangling based on the name and the mtwt_resolve()'d name, but my understanding is that the pretty-printer is... on the way out anyway?

For now, I'm just going to put the underscore hack back in, so that all tests pass again, but this is strictly a "hide the bug" solution.

**Comment by steveklabnik** [comment]
Triage: I'm not aware of significant changes to the pretty tests in a very long time.

**Comment by petrochenkov** [comment]
Tests are not run in `pretty-expanded` mode by default now, mostly due to #23616.
About 670 tests are manually whitelisted with `// pretty-expanded`.
This issue still exists in latent form.

**Comment by steveklabnik** [comment]
Triage: all of the `//pretty-expanded` comements are tagged with "FIXME: #23616". As such, let's close this as an effective dup of that one.
