### ISSUE TITLE
Parser mistakes macro argument for struct initialization?

### ISSUE THREAD

**Issue by hannobraun** [rust-lang/rust#15198]
When I updated to Rust master yesterday, some of my macro invocations broke in an interesting way. Here's a reduced example:
```
#![feature(macro_rules)]

macro_rules! my_macro(
	($condition:expr $action:block) => ({})
)

fn main() {
	my_macro!(0 == y {
		y = 1;
	});
}
```

```
$ rustc main.rs
main.rs:10:5: 10:6 error: expected `:` but found `=`
main.rs:10 		y = 1;
           		  ^
```

With this workaround, it compiles without errors:
```
#![feature(macro_rules)]

macro_rules! my_macro(
	($condition:expr $action:block) => ({})
)

fn main() {
	my_macro!(0 == y && true {
		y = 1;
	});
}
```

Looks to me like the parser sees "y { ..." and mistakes it for a struct initialization.

This problem occurs with commit 2f74325fcfcf0e8bc478674f996a190f6a58b20c.
Before the upgrade, it worked fine with commit db298145c702c49e5f3cc17adeafe58c8b1bbd6a.

**Comment by kmcallister** [comment]
This is an example of the problem that [RFC 550](https://github.com/rust-lang/rfcs/blob/master/text/0550-macro-future-proofing.md) was meant to prevent, which indeed it does:

```
<anon>:2:6: 2:21 error: `$condition:expr` is followed by `$action:block`, which is not allowed for `expr` fragments
<anon>:2     ($condition:expr $action:block) => ({})
              ^~~~~~~~~~~~~~~
```

The ambiguity between struct initializers and blocks is a long-standing wart of the expression grammar.  It's probably responsible for other bugs, but it should not cause macro breakage like this again thanks to RFC 550.
