### ISSUE TITLE
Rust allows uncallable methods to be defined in generic impl blocks

### ISSUE THREAD

**Issue by Dr-Emann** [rust-lang/rust#15282]
Rust allows impl blocks to be generic, even if the type is not generic. However, any methods contained in such a generic impl block must use every generic parameter, or the functions become uncallable (because the other types cannot be specified). Rust will not find any errors or warnings in such a defintion, only at the call site.

Rust should at least complain at the declaration site if all generic parameters are not used by every method. Alternatively, we could disallow generics on impl blocks that are not used as type parameters on the implementing type.
#### Example Code
```rust
struct Foo;
impl<A: std::fmt::Show, B> Foo {
 
    fn func(&mut self, a: A)
    {
        println!("{}", a);
    }
}
 
fn main() {
    let mut f = Foo;
    // uncomment the following line, program fails to compile.
    //f.func(42i); // error: cannot determine a type for this expression: unconstrained type
}
```

**Comment by steveklabnik** [comment]
Triage: still an issue.

**Comment by steveklabnik** [comment]
This kind of code isn't even legal anymore:

```
hello.rs:2:6: 2:7 error: the type parameter `A` is not constrained by the impl trait, self type, or predicates [E0207]
hello.rs:2 impl<A: std::fmt::Display, B> Foo {
                ^
hello.rs:2:28: 2:29 error: the type parameter `B` is not constrained by the impl trait, self type, or predicates [E0207]
hello.rs:2 impl<A: std::fmt::Display, B> Foo {
                                      ^
```

This would seem to be ' Alternatively, we could disallow generics on impl blocks that are not used as type parameters on the implementing type.'

Closing!
