### ISSUE TITLE
Pick over the standard libraries for types that don't (but can) implement common traits

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#15294]
... and implement/derive them.

Traits like `Eq`, `Hash`, `Ord`, `Clone` are sometimes forgotten (or have been missed, in the various library changes that have happened), and this is annoying for downstream users. To paper over the deeper issue (how to make adding these impls more natural/harder to forget), impls for all the various traits can be added to types.

List of types missing things just from a basic scan:

- many types in `collections` (only implement the `Partial` comparison traits, and pretty much none of them implement `Hash`)
- `semver::Version`
- all types in `num` are missing `Hash`
- `url::Path`, `url::UserInfo`
- `uuid::UuidVariant`, `uuid::UuidVersion`

**Comment by steveklabnik** [comment]
Given that this issue is vague, and it seems like all of the specific things mentioned here have been done, I'm giving this a close. If anyone knows of any other things that are missing, let's add them, but I don't find this ticket to be super actionable right now.
