### ISSUE TITLE
Std docs links are not all highlighted

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#15307]
[Std doc](http://doc.rust-lang.org/master/std/f32/) links should have colors to highlight that they are links:

![std2](https://cloud.githubusercontent.com/assets/4156987/3446990/3ddbe4aa-0148-11e4-809a-825f538e2c23.png)

Some [users](http://www.reddit.com/r/rust/comments/29kia3/no_ord_for_f32/cils5pz) find it difficult to know which items are links.

[EDIT] Removed sidebar circles. Never thought they needed changing.

**Comment by Manishearth** [comment]
+1 from me

**Comment by mdinger** [comment]
I'm currently playing with rustdoc. I may try to implement this once the docs are built.
