### ISSUE TITLE
Raw pointers have no 'primitive' page in rustdoc

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#15318]
E.g. there's no http://doc.rust-lang.org/master/std/uint/primitive.uint.html for `*const` or `*mut`.

**Comment by SimonSapin** [comment]
Now that the `PtrExt` and `MutPtrExt` traits were removed in favor of inherent implementations (#23104), this bug means that methods on raw pointers are not documented anywhere.

**Comment by SimonSapin** [comment]
cc @steveklabnik
