### ISSUE TITLE
serialize::json is encouraging allocating intermediate buffers

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#15317]
The `Encodable`/`Decodable` interface is designed to avoid having to allocate everything to intermediate buffers, but `json` is encouraging going via `String`. `serialize::json` has the top level `encode` function returning a `String`, and *all* the examples use `encode` directly, there's no demonstration of the good direct-to-`Writer` API.

That is, something like

```rust
println!("{}", json::encode(&x))
```
can be written a little like
```rust
encodable.encode(&mut json::Encoder::new(&mut io::stdout()))
```

If that is deemed too ugly, I think we should work on fixing the ergonomics of the good version, rather than just leaping straight to the `-> String`  ones (e.g. `json::encode(&mut io::stdout(), &x)` would be nice, and work with `json::encode(&mut some_file, &x)`, `json::encode(&mut some_tcp_stream, &x)`, etc.).

cc @aturon

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rustc-serialize#57
