### ISSUE TITLE
Rustdoc: group items by stability, rather than alphabetically

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#15345]
Rustdoc has grown a lovely new feature whereby index pages with listings of functions and types will display a color next to each item indicating whether it's experimental, unstable, stable, or deprecated. I would like to go one further: group all items according to stability, rather than just having them scattered through an alphabetic list. After grouping by stability, I would like each of the four sections to be ordered as follows:

1. Stable
2. Unstable
3. Experimental
4. Deprecated

Within each group, ordering will remain alphabetical.

Reasoning: if I'm a user, I want to prefer stable items, which means that I want to see at a glance what my stable options are. If there are no stable options, then I want to consider unstable options, then experimental options, then deprecated options, in that order. Furthermore, if I'm a library author, then I want my users to consider options in the same order: stable first, then unstable-but-up-and-coming, then deprecated last.

**Comment by alexcrichton** [comment]
I'm going to close this in favor of #21674 as our stability story has changed pretty significantly since this was opened!
