### ISSUE TITLE
Add Haiku as officially supported operating system

### ISSUE THREAD

**Issue by AdrianArroyoCalle** [rust-lang/rust#15368]
Haiku is a open source operating system based on BeOS that runs pretty fast in a POSIX environment plus BeAPI. It's licensed under the MIT license and it isn't Linux, Hurd, Solaris or something like that. At the moment Haiku has LLVM, Clang, GCC4, Python, Perl, GNU make, curl and git. Other languages also have support for Haiku like FreePascal. So it will be great if Rust runs natively on Haiku.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#799

**Comment by AdrianArroyoCalle** [comment]
Niels Sascha Reedijk is working on it http://rust-on-haiku.com/
