### ISSUE TITLE
Optimize the next-power-of-two calculation in vectors for code size

### ISSUE THREAD

**Issue by pcwalton** [rust-lang/rust#15390]
Currently it's more general than it needs to be, resulting in the next-power-of-two code appearing in lots of places due to inlining. But vec capacities are usually powers of two. I think it should be something like:

    if popcount(capacity) != 1 {
        // non-power-of-two case
        capacity_slow()
    } else {
        capacity << 1
    }

**Comment by cmr** [comment]
I'm going to close this. https://github.com/rust-lang/rust/pull/23670 moves cap calculation out of the inlined fast path entirely.
