### ISSUE TITLE
Do something better when there's a mismatch between identical-looking regions

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#15391]
It's a very common experience for rustc to tell you it couldn't unify two regions, then print out the span of those regions, only to have them look identical. Seeing enough of these can be rage-inducing.

I don't have a great concrete suggestion, but even just printing a single region and saying something like 'yeah, I know these regions look the same. sorry', might ease the pain a bit.

**Comment by steveklabnik** [comment]
Triage: unsure if this is still a problem, exactly. @brson how do you feel about this now?

**Comment by pnkfelix** [comment]
I think we still encounter this (though maybe the finer grain scopes added due to dropck have made *slightly* different scopes, and thus shifted the rage slightly).

@brson's suggestion of at least acknowledging when the spans are identical might still be a good idea for the short term.

**Comment by brson** [comment]
I haven't seen this recently, but I haven't written a lot of Rust recently.

**Comment by steveklabnik** [comment]
I'm going to close this issue for being a bit too vague. If you see something like it with some concrete code, please open a new issue so we can tackle those specific issues.
