### ISSUE TITLE
It's sorta confusing that C++'s `extern "C"` turns off mangling but ours doesn't.

### ISSUE THREAD

**Issue by ben0x539** [rust-lang/rust#15413]
For externally-visible items, maybe `extern "C"` should imply `#[no_mangle]`, or maybe a lint should suggest it? An exported `pub extern "C"` function that *isn't* callable from C code by its name seems like a pretty niche situation.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#674
