### ISSUE TITLE
Consider making Reader::lines() reuse one buffer in place

### ISSUE THREAD

**Issue by pcwalton** [rust-lang/rust#15436]
It doesn't make a lot of sense to keep allocating over and over if the app isn't going to hold onto the strings. It hurt our perf vs. Go in https://gist.github.com/alco/5d18c046094d0abb3f58#file-timings

If the user wants new strings he or she can just convert the `&str` returned into a `String`.

cc @alexcrichton

**Comment by alexcrichton** [comment]
This was handled in the new I/O reform and the new `BufRead` trait.
