### ISSUE TITLE
Unify formatting floats and f{32,64}::to_str_digits

### ISSUE THREAD

**Issue by erickt** [rust-lang/rust#15432]
cc @alexcrichton. It looks like we have a lot of duplicated code with [libcore/fmt/float.rs](https://github.com/rust-lang/rust/blob/master/src/libcore/fmt/float.rs) and [std::num::strconv::float_to_str_bytes_common](https://github.com/rust-lang/rust/blob/master/src/libstd/num/strconv.rs#L261). Can this code be merged?

**Comment by steveklabnik** [comment]
I'm not sure how this has gottne shuffled, but `to_str_digits` nor most of these modules still exist. Let me know if this refactor is still worthwhile!
