### ISSUE TITLE
Strange behavior with unused imports

### ISSUE THREAD

**Issue by zwarich** [rust-lang/rust#15449]
This program is currently accepted:

```rust
use A::B;

mod A {
    pub struct B { n: int }
    fn B() { }
}

fn main() {
}
```

but this program, which adds a use of `B()`, is not:

```rust
use A::B;

mod A {
    pub struct B { n: int }
    fn B() { }
}

fn main() {
    let _ = B();
}
```

**Comment by frewsxcv** [comment]
Just tried running this and confirm this is still an issue.

**Comment by steveklabnik** [comment]
By changing `int` to `i32`, this error persists today.

I feel like this is a duplicate of another ticket, but I cannot find it right now.

**Comment by petrochenkov** [comment]
>I feel like this is a duplicate of another ticket, but I cannot find it right now.

https://github.com/rust-lang/rust/issues/12334 and it's closed.
This "strange" behavior is intentional currently.

**Comment by steveklabnik** [comment]
Closing the .
