### ISSUE TITLE
Unify doc comment style?

### ISSUE THREAD

**Issue by alxgnon** [rust-lang/rust#15458]
The majority of the Rust codebase uses `///` style doc comments. Rarely will a file contain occurences of `/**`. I think it is safe to say that the `///` style is currently preferred. I would like to see the entire codebase subscribe to a single doc comment style.

This is a quite trivial fix for existing code, but I'd like to hear some external opinion before I make the change (or don't, depending).

**Comment by steveklabnik** [comment]
We have issues here as well as an open RFC for doc coments, so I'm gonna give this one a close.
