### ISSUE TITLE
Deprecation should be more visible in rustdoc output

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#15468]
It's currently handled like any other stability attribute, but I think we want something more explicit for the case of deprecation. For example, javadoc prints the deprecation warning both in the table of contents and the documentation for a deprecated method: http://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#resume(). We'll want to make sure that it's easily visible even on the search results page so people can avoid clicking into and using deprecated API by accident.

**Comment by pnkfelix** [comment]
not necessary for 1.0.  (also, some note that `deprecated` is for usage within the standard library, *not* for end-user crates).

P-high.

**Comment by caipre** [comment]
I'm still working on this, albeit slowly. It's not as easy (for a rust novice) as I initially suspected it might be.
