### ISSUE TITLE
Self-referential templated trait overflows the stack

### ISSUE THREAD

**Issue by lee-b** [rust-lang/rust#15477]
Compiling the following:

    trait Chromosome<C: Chromosome> {
        fn random() -> C;
    }

Causes the following output:

    task 'rustc' has overflowed its stack
    Illegal instruction

The code was an unintentional typo, and probably isn't valid, but I think the compiler should handle this a lot better, as there's no indication of what the problem is, or where it lies.  In large compilation units with complex templating etc., that could be a big roadblock.

**Comment by steveklabnik** [comment]
This still overflows the stack today.

**Comment by tamird** [comment]
No longer reproducible.
