### ISSUE TITLE
Error snake for moving out of an &-pointer is wrong sometimes

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#15479]
Minimal-ish working example:

```
use std::string::String;
struct Foo {
 a: String,
 b: String,
 // Possibly some more fields here
}
struct FooThing(Vec<Foo>);
impl FooThing {
  fn filter(&mut self, bar: &Foo) {
    let FooThing(ref buf) = self.clone(); // Oops. Shouldn't be a `ref` there
    let new_buf: Vec<Foo> = buf.move_iter().filter(|f| f.a == bar.a && f.b == bar.b).collect();
  }
}
fn main() {

}
```

The usage of `ref buf` means that `buf.move_iter` won't work, since `buf` is an &-pointer now. An error is expected.

However, the error shown is:
```
test.rs:12:53: 12:56 error: the type of this value must be known in this context
test.rs:12 	let new_buf: Vec<Foo> = buf.move_iter().filter(|f| f.a == bar.a && f.b == bar.b).collect();
           	                                                   ^~~
```

For some reason, the red caret points at `f.a`. Swapping `f.a` and `bar.a`, it still points at `f.a`. Swapping the two equality checks, it now points at `f.b`. I don't know what the difference was, but in my real-world case it was the second equality check that had the pointer on it.

The error snake goes to `buf.move_iter()` correctly if you replace `self.clone()` with `*self`.

**Comment by nham** [comment]
I made an attempt at reproducing this. Here is the updated code:

    use std::string::String;

    #[derive(Clone)]
    struct Foo {
     a: String,
     b: String,
     // Possibly some more fields here
    }

    #[derive(Clone)]
    struct FooThing(Vec<Foo>);

    impl FooThing {
        fn filter(&mut self, bar: &Foo) {
            // Oops. Shouldn't be a `ref` there
            let FooThing(ref buf) = self.clone();

            let new_buf: Vec<Foo> = buf.into_iter()
                                       .filter(|f| f.a == bar.a && f.b == bar.b)
                                       .collect();
        }
    }

    fn main() {}

This fails to compile now, but with this error:

    test_15479.rs:18:33: 18:36 error: cannot move out of borrowed content
    test_15479.rs:18         let new_buf: Vec<Foo> = buf.into_iter()
                                                     ^~~
    error: aborting due to previous error

(Version is `rustc 1.0.0-nightly (07560d233 2015-04-20) (built 2015-04-20)`)

This appears to not have the problem described above.

**Comment by steveklabnik** [comment]
The error _now_ says that `error: the trait `core::iter::FromIterator<&Foo>` is not implemented for the type `collections::vec::Vec<Foo>` [E0277]`, so I think this is basically fixed. @Manishearth , if you can come up with a different reproduction of this squiggle being wrong, let me know.
