### ISSUE TITLE
Rust should optimize away enum variants containing a Void type

### ISSUE THREAD

**Issue by erickt** [rust-lang/rust#15510]
One of the downsides of writing generic functions that may error with a `Result<T, E>` is that sometimes an implementation is guaranteed to never error. For example, the current implementation of `MemWriter` always returns a `Ok(())`, but users of `MemWriter` still have to pay for unwrapping the always-ok result.

One possibility for optimizing this unwrapping today would be to parameterize `Writer` with an error type, and let `MemWriter` use a `Void` type as it's error. Theoretically, rust should be able to tell that since it is impossible to construct a `Void` type, all branches that touch that `Void` type can be optimized away. For example, this code:

``` rust
enum Void { }

trait Writer<E> {
    fn write(&mut self, buf: &[u8]) -> Result<(), E>;
}

struct MemWriter { ... }

impl Writer<Void> for MemWriter {
    fn write(&mut self, buf: &[u8]) -> Result<(), Void> {
        self.buf.push_all(buf);
        Ok(())
    }
}
```

Could be compiled down to the equivalent of:

``` rust
impl Writer for MemWriter {
    fn write(&mut self, buf: &[u8]) -> () {
        self.buf.push_all(buf);
        ()
    }
}
```

**Comment by steveklabnik** [comment]
Triage: 

So, IIRC, the trait in question is `io::Write`, which was not parameterized over `E`, but instead through `std::io::Result`. So the thing this ticket asks for exactly is never gonna happen.

There's also been work on void types, and optimizations around them. But that's all covered elsewhere. So I'm gonna give this one a close.
