### ISSUE TITLE
DXR: no type information for destructured tuple result of enumerate call

### ISSUE THREAD

**Issue by jdm** [rust-lang/rust#15512]
The `i` and `e` variables declared at http://ncameron.org:8000/rust/source/libserialize/serialize.rs#458 don't have any type information on hover, and the use of `i` on the next line isn't even flagged as something clickable.

cc @nick29581

**Comment by steveklabnik** [comment]
Since this site doesn't exist any more, can we get some code that would reproduce this?

**Comment by jdm** [comment]
This should be tracked in https://github.com/nick29581/rust-dxr/ if anywhere.
