### ISSUE TITLE
Guide: what to do about int

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#15526]
I've been using `int` because its familiar, but it may not be the right thing to suggest. Can we get a decision here?

**Comment by alexchandel** [comment]
> Unfortunately, many programmers don't fully read/grok/remember the docs. They'll make assumptions based on other languages. Thus calling it int is a problem.

@1fish2 I disagree, programmers have IQs above 42. And if someone is writing production code in Rust, and they never learned what the base types are, there's no helping them. But the name is changing, so it's moot.

Indeed, the guide has been changed to use `i32` in its examples. Close?

**Comment by vks** [comment]
@alexchandel Just look at arbitrary Rust code on github. Most uses of `int` are wrong.

**Comment by steveklabnik** [comment]
Yes, this can be closed.

**Comment by 1fish2** [comment]
@steveklabnik Excellent. Cheers!

BTW, the Guide might want to say what `i32` means when first using it.

Is there a doc on Rust's type inference?

@alexchandel No disrespect intended for my fellow programmers. It's not about intelligence. It's about design complexity & usability, busy people, project time pressures, limited working memory, using many languages on a daily basis, and jumping to conclusions.

To take one example, I've had fellow Google engineers not know about key Java facts like precise exceptions (which enables portability but severely limits code motion optimizations), which primitives are atomic in read/write, or how to write bounded generics. How many programmers have read the language spec of the languages they use?

Back to Rust, there have been many uses of `int` and `uint` where a non-portable integer type is inappropriate such as integer shift and rotate counts, basic math operations, and binary I/O.

**Comment by alexchandel** [comment]
@vks simply untrue.

@1fish2 There's a difference between knowing "which primitives are atomic in read/write" and what *the definition of int is*

**Comment by 1fish2** [comment]
@alexchandel Yes, that was an extreme example. The point is it was a usability problem, not users' fault. Those weren't IQ 42 programmers surprised to learn via the Rust mailing list that `int` was non-portable. Nor IQ 42 programmers who selected `int` for integer shift and rotate counts, reading and writing 32-bit binary proto buffer fields, etc.
