### ISSUE TITLE
Investigate the issue of `Show` bloat

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#15548]
In rustc, many types derive `Show` purely for use with `debug!`. This may be negatively impacting compiletime, as we are generating and translating code that we really don't care about most of the time. Is this causing noticable impact, and do we want to do anything about it?

**Comment by malbarbo** [comment]
@alexcrichton I think this issue can be closed.

**Comment by alexcrichton** [comment]
Indeed!

**Comment by steveklabnik** [comment]
Blast from the past 🚀
