### ISSUE TITLE
benchmark comparisons build target

### ISSUE THREAD

**Issue by Gankro** [rust-lang/rust#15542]
It would be desirable to be able to ask the build tool something along the lines of:
      ````$ make compare-bench first=HEAD second=e2e237afc````
where ```first``` and ```second``` are basically anything that git will accept to refer to a commit. The system would build, bench, and compare the two referenced commits. Ideally it could also provide feedback on % changes and possibly statistical significance. Maybe just a binary ```insignificant``` or ```significant```, possibly even just hiding insignificant results, and reporting "no measurable difference" if all results are insignificant.

This would simplify and streamline determining if a change has meaningful performance effects. As an extreme pie-in-the-sky feature it could potentially also be integrated into the automatic Travis verification if an RTC is tagged with ```#perf``` or something. At very least it could post a comment with a before/after comparison for discussion purposes.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#727
