### ISSUE TITLE
make: rustdoc failures can leave around expected build product

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#15555]
rustdoc failures can leave around expected build product, e.g. `doc/syntax/index.html`.

This means that after the first `make` attempt fails, if you invoke `make` again, it will see the build product now in place, and will continue as if the dependency has been satisified.

This is irritating if you are trying to understand how the first error happened in the first place and want to find out e.g. what the necessary command line invocation to `rustdoc` is needed to reproduce it.

I would recommend we change the makefiles to use an analogous `stamp.syntax` infrastructure for the docs that we already use for the libraries (and then you would only touch the stamp file after `rustdoc` had finished generating its output and returned without an error).

**Comment by steveklabnik** [comment]
Triage: no change. This can still happen, as we haven't changed to using stamps.

**Comment by steveklabnik** [comment]
Triage: I _think_ rustbuild Just Fixes this. @alexcrichton ?

**Comment by alexcrichton** [comment]
Yes I think because we're now leveraging `cargo doc` this is just taken care of.
