### ISSUE TITLE
Add a way to expand only a particular macro or macros defined in a crate when pretty printing.

### ISSUE THREAD

**Issue by mcpherrinm** [rust-lang/rust#15599]
Expanding all macros like println! Can get rapidly unwieldly.  For a macro author, expanding only a particular macro or macros defined in a particular crate may be useful.

**Comment by cmr** [comment]
This would indeed be a very useful feature for debugging macros!

**Comment by wyown** [comment]
I need this too!

**Comment by steveklabnik** [comment]
Triage: no comments in two and a half years, and I'm not aware of any desire to improve `pretty`. I don't think this is likely to be fixed, and so I'm going to close. If you'd like to fix this, please let me know and we can re-open!
