### ISSUE TITLE
Plugins should be present in LD_LIBRARY_PATH in order to be used

### ISSUE THREAD

**Issue by netvl** [rust-lang/rust#15590]
Consider this code:

```rust
#![feature(phase)]

#[phase(plugin)] extern crate docopt_macros;
extern crate docopt;

fn main() {}
```

and I have `libdocopt` and `libdocopt_macros` libraries (both rlib and so) in `target/deps` dir. Now this command fails:

```
% rustc -L target/deps main.rs 
main.rs:3:18: 3:45 error: libdocopt-7d3351826ed55f12.so: cannot open shared object file: No such file or directory
main.rs:3 #[phase(plugin)] extern crate docopt_macros;
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

But this works:

```
% LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$PWD/target/deps" rustc -L target/deps main.rs
```

This is really bad. For example, cargo can't compile such packages now. I'm not sure if this is possible to fix given the latest change in rpath handling, but is there a sensible workaround? I don't think it is acceptable to tweak LD_LIBRARY_PATH just to run the compiler; moreover, this did work before the change, so it looks like a regression.

I'm using Linux x86_64, by the way.

**Comment by steveklabnik** [comment]
I am choosing option 3. I don't think we can do anything more here.
