### ISSUE TITLE
Shrink Span

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#15594]
[Span](http://doc.rust-lang.org/syntax/codemap/struct.Span.html) is how we know what source a given piece of the AST corresponds to. There are many, many Spans when compiling a crate. It is currently 16 bytes.

Since a span is always contiguous, it can be compressed by storing the base (`u32`) plus a length (`u16`). Furthermore, `expn_info` is currently occupying a full 8 bytes. It could be replaced with a `u16` index into some `expn_info` table somewhere.

**Comment by michaelwoerister** [comment]
I've tried to measure span memory consumption by doubling span size instead of setting it to zero (https://github.com/michaelwoerister/rust/tree/span-memory-bench). This way things don't break and one can test against existing codebases. Here are some numbers:
```
                 SINGLE   DOUBLE    DIFF    SPANS (% of total max memory)
LIBSYNTAX        696764   721728   24964     3.6%
LIBRUSTC        1154900  1394124  239224    20.7%
LIBRUSTC_TRANS   518424   547904   29480     5.7%
LIBRUSTC_TYPECK  446160   482856   36696     8.2%
LIBSTD           243796   260420   16624     6.8%
```
Numbers are max resident set in KB.

**Comment by llogiq** [comment]
This works out to:

                     SINGLE   DOUBLE    DIFF    SPANS (% of total max memory)
    TOTAL	3060044	3407032	346988	11,34%

**Comment by brson** [comment]
Is this still relevant? Is anybody still interested in reducing that 11% of space occupied by spans? Would reducing this number really impact compiletime meaningfully?

**Comment by michaelwoerister** [comment]
I'll just link this here for documentation: https://internals.rust-lang.org/t/rfc-compiler-refactoring-spans/1357/23 -- One possible strategy for reducing span sizes.
