### ISSUE TITLE
Add stack-measuring functionality

### ISSUE THREAD

**Issue by nnethercote** [rust-lang/rust#15600]
I've done some memory profiling of Servo (by looking at `/proc/<pid>/smaps` on Linux) and found that stack sizes can be really large:

- [stack:28150] 1136 kB
- [stack:28145] 6144 kB
- [stack:28144] 2048 kB
- [stack:28141] 8192 kB
- [stack:28139] 7944 kB
- [stack:28136] 5120 kB

These are all |Rss| values. The |Size| values (i.e. address space taken) values were even larger.

It would be nice to have language (well, library) support for measuring these within the Rust code. I don't know how it would be implemented, though.

**Comment by steveklabnik** [comment]
Seems like this has been resolved.

**Comment by nnethercote** [comment]
It hasn't been resolved. I just measured again with current Servo tip:
```
Rss:                  12 kB
Rss:                  12 kB
Rss:                8192 kB
Rss:                  48 kB
Rss:                  16 kB
Rss:                  24 kB
Rss:                  48 kB
Rss:                4096 kB
Rss:                  48 kB
Rss:                  44 kB
Rss:                4024 kB
Rss:                  44 kB
Rss:                  12 kB
Rss:                4096 kB
Rss:                  12 kB
Rss:                  24 kB
Rss:                  12 kB
Rss:                8192 kB
Rss:                  28 kB
Rss:                  28 kB
Rss:                  48 kB
Rss:                  28 kB
Rss:                4096 kB
Rss:               12128 kB
Rss:                  12 kB
Rss:                  20 kB
Rss:                  16 kB
Rss:                  16 kB
Rss:                  12 kB
Rss:                   8 kB
Rss:                   8 kB
Rss:                   8 kB
Rss:                   8 kB
Rss:                   8 kB
Rss:                   8 kB
Rss:                   8 kB
Rss:                4724 kB
```
That's over 48 MiB of stack, which is more than a third of Servo's total Rss.

**Comment by nnethercote** [comment]
Oh, I just learned that if a non-thread-stack mapping is placed adjacent to a thread stack, the two will be merged and /proc/<pid>/smaps will claim that the merged result is a thread stack. So these big numbers are bogus. Good.
