### ISSUE TITLE
Should IntoStr trait be renamed to IntoString?

### ISSUE THREAD

**Issue by jasonthompson** [rust-lang/rust#15606]
re #15493 and #15046 

-IntoStr/into_str was renamed to IntoStr/into_string. Should the trait be renamed to IntoString? 

-Also, shouldn't the file libstd/to_str.rs be renamed to libstd/to_string.rs.

I'm happy to do fix the first point--I did a quick search through src and IntoStr is only used in a few other files. But I'm not sure what kind of issues renaming the file would create.

**Comment by steveklabnik** [comment]
These traits are all gone now.
