### ISSUE TITLE
deriving codegen: fold comparisons of variants without substructure into the catch-all

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#15618]
Spawned off of https://github.com/rust-lang/rust/pull/15503#issuecomment-48228041

> I was thinking of the particular case of C-like enums on the way home today.
> 
> Those cases are covered by this (not yet implemented) optimization: I really should be letting comparisons of two enums that both have no subparts (e.g. B and D in enum E { A(int), B, C(f64), D } fall through the catch-all as well, since the catch-all will have all of the information it needs to give the answers in such cases.
> 
> Once such an optimization is in place, then for C-like enums all of the cases would just fall through to the catch-all (i.e. there would be no preceding arms).

**Comment by steveklabnik** [comment]
Triage: no idea.

**Comment by steveklabnik** [comment]
Triage: same as in 2016

**Comment by Mark-Simulacrum** [comment]
I'm going to close this -- this essentially I believe comes down to [this if](https://github.com/rust-lang/rust/blob/ed8b708c1a6bf6d94f860eeb6a6b0b442c380d7f/src/libsyntax_ext/deriving/cmp/partial_ord.rs#L64-L72) -- which I think we can't remove in a completely backwards compatible manner today. If I'm wrong then we can reopen (but it becomes a really easy bug then I suspect, so it's odd that this wasn't fixed at the time).
