### ISSUE TITLE
assert_eq!() cannot be used on Path

### ISSUE THREAD

**Issue by o11c** [rust-lang/rust#15625]
Since `Path` isn't `Show`, it can't be used. This would be useful, for when you're actually comparing some container of `Path`, such as `Option<Path>` or `Vec<Path>`.

As an alternative, I tried `.map(|p| p.display())` on both sides, but `Display` doesn't impl `PartialEq`, so it can't be used either. That means either `.as_str().unwrap()`, or just give up on the nicely printed failure and use plain `assert!`

**Comment by frewsxcv** [comment]
`Show` was recently deprecated in favor of `Debug`. [According to the current documentation](http://doc.rust-lang.org/std/path/windows/struct.Path.html#method.fmt), `Path` implements `Debug`.

![screen shot 2015-02-02 at 9 38 14 pm](https://cloud.githubusercontent.com/assets/416575/6013518/cf197b0a-ab23-11e4-84f8-4e5f82fe064c.png)

This can probably be closed.

**Comment by kmcallister** [comment]
Yep, I can use `assert_eq!` on `Path` as of rustc 1.0.0-nightly (52c74e63d 2015-01-29 22:54:19 +0000)
