### ISSUE TITLE
deriving codegen: add intrinsic to map enum instance to its variant index

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#15620]
Spawned off of https://github.com/rust-lang/rust/pull/15503#issuecomment-48228041

> The other piece of the story there would be speeding up the mapping from the value to its discriminant index. Currently I am just emitting that code in place as another match statement, but in principle that could (and should?) be replaced by a compiler intrinsic, as discussed here: https://github.com/rust-lang/rust/issues/15375#issuecomment-47994344

**Comment by pnkfelix** [comment]
do note also huon's point here: https://github.com/rust-lang/rust/issues/15375#issuecomment-47994507

**Comment by durka** [comment]
Should this still be open? What's the point of a variant index intrinsic?

**Comment by pnkfelix** [comment]
Due to huon's point from #15375 that the ordering (in terms of the value used for the discriminant) might change over time with changes to the compiler, plus the fact that the comments here indicate that the important thing is equality comparisons, not an ordering nor assignment to integer values, I am just going to close this.
