### ISSUE TITLE
Implement a multimap

### ISSUE THREAD

**Issue by treeman** [rust-lang/rust#15669]
Extensions to `treemap` and `hashmap`, with set variations. Indicated by the [wiki](https://github.com/rust-lang/rust/wiki/Containers#wanted).

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#784
