### ISSUE TITLE
antlr is losing information

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#15677]
See http://stackoverflow.com/questions/24747360/distinguishing-literal-n-vs-embedded-newline. Until there is a resolution to this, the lexer verification is ignoring the contents every token that carries data :(

**Comment by steveklabnik** [comment]
traige: no changes that i'm aware of

**Comment by nagisa** [comment]
While we still have ANTLR grammar in tree, it is outdated and we predominantly rely on the other thing we have in tree. Perhaps we should just remove ANTLR one now?

**Comment by cmr** [comment]
The ANTLR grammar was originally intended to be "pure" in the sense that it uses only language description and no code in its operation, and could easily be lifted into some formalism. This is quite at odds with how the flex and bison files operate.

**Comment by steveklabnik** [comment]
I would be okay removing ANTLR.

**Comment by Mark-Simulacrum** [comment]
ANTLR grammar is still in-tree. There is now an answer to the SO question, though, so perhaps that's significant to this discussion? It's possible the easiest answer here is to simply remove the ANTLR grammar from in-tree, possibly moving it elsewhere.

**Comment by steveklabnik** [comment]
Agreed; I'd be happy to just remove it. We're not planning on doing anything with ANTLR in the future that I know of, and if we need it, we can pull it back out of the history.
