### ISSUE TITLE
rustc cannot find librustc when installed with rustup.sh

### ISSUE THREAD

**Issue by Noctune** [rust-lang/rust#15684]
I recently installed rustc with rustup.sh on an Arch Linux x64 machine, but executing rustc after installation (no matter the parameters) results in this error:

> rustc: error while loading shared libraries: librustc-4e7c5e5c.so: cannot open shared object file: No such file or directory

This is even though `librustc-4e7c5e5c.so` can be found in both `./usr/local/lib/librustc-4e7c5e5c.so` and `./usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc-4e7c5e5c.so`.

**Comment by Gonzih** [comment]
@JohnAppleSeed- 

`set -Ux LD_LIBRARY_PATH $LD_LIBRARY_PATH:/usr/local/lib`

**Comment by eLobato** [comment]
Same issue here on Fedora 21, any reason why the script shouldn't export the path by default?

**Comment by kl4ng** [comment]
Had this issue in Fedora 21, even if I compiled rust from sources, the above fixed it.

**Comment by MaTachi** [comment]
Had the same issue on Fedora 21, both with Nightly and 1.0.0-alpha.2. Adding that line to .zshrc solved it though (I'm using zsh instead of bash).

**Comment by dumindu** [comment]
Same happens on Fedora 22 alpha

**Comment by zwippie** [comment]
Same happens on Ubuntu 14.04.2 LTS with rust 1.0.0-beta. Adding `export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib` to `.zshrc` solved it.

**Comment by maximih** [comment]
Same issue on Redhat 6.4 after installing as root user. Should we reopen this? It gives a bad impression if rust installation doesn't 'just' work.

**Comment by roelvanduijnhoven** [comment]
Also got this error after an upgrade.

**Comment by maximih** [comment]
cc @brson

**Comment by danielkza** [comment]
Got the same problem on Fedora 21. I believe installing a script into `/etc/profile.d` if it exists, correcting `LD_LIBRARY_PATH`, could work without requiring user intervention.

**Comment by wahtak** [comment]
I had the same problem in Fedora 21. I suppose a cleaner way to solve this is adding a file in `/etc/ld.so.conf.d/` wtih the content `/usr/local/lib` and running `ldconfig` afterwards.

**Comment by Keats** [comment]
Just got it on Archlinux x64 as well, adding `export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib` to my zshrc fixed it but it would be nice to have rustup working out of the box

**Comment by s-p-n** [comment]
I had this issue on Fedora 21, too. [This comment](https://github.com/rust-lang/rust/issues/15684#issuecomment-65542073) helped me solve the issue.

**Comment by chuijiaolianying** [comment]
I met this on Fedora 22, and follow steps help me resolve it.

1. $ sudo vim /etc/ld.so.conf
    add  `/usr/local/lib` in it.
2. $ sudo ldconfig 
    update the ldconfig cache.
After this, It should work now~

**Comment by dumindu** [comment]
@Noctune This should be reopen.

**Comment by Noctune** [comment]
@dumindu Alright, I'll re-open it.

**Comment by cyplo** [comment]
Hello ! 
Same issue on newest fresh Fedora 22. 
When searching for this issue I found this one as well, seems very similar: #24677
It happens when I run `curl -sSf https://static.rust-lang.org/rustup.sh | sh`

Let me know if I can help debugging this.
Excerpt from the log and then ldd showing missing libraries:
```
rustup: gpg available. signatures will be verified
rustup: downloading manifest for 'stable'
rustup: downloading toolchain for 'stable'
######################################################################## 100.0%
gpg: assuming signed data in '/home/cyryl/.rustup/dl/88582fca9f8c53945b8f/rust-1.1.0-x86_64-unknown-linux-gnu.tar.gz'
gpg: Signature made Sat 20 Jun 2015 09:36:00 CEST using RSA key ID 7B3B09DC
gpg: Good signature from "Rust Language (Tag and Release Signing Key) <rust-key@rust-lang.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 108F 6620 5EAE B0AA A8DD  5E1C 85AB 96E6 FA1B E5FE
     Subkey fingerprint: C134 66B7 E169 A085 1886  3216 5CB4 A934 7B3B 09DC
rustup: extracting installer
rustup: installing toolchain for 'stable'
[sudo] password for cyryl: 
install: uninstalling component 'rustc'
install: uninstalling component 'cargo'
install: uninstalling component 'rust-docs'
install: creating uninstall script at /usr/local/lib/rustlib/uninstall.sh
install: installing component 'rustc'
install: installing component 'cargo'
install: installing component 'rust-docs'

    Rust is ready to roll.


# vim: set noet ts=8 sts=4 sw=4:
[cyryl@localhost ~]$ rustc -V
rustc: error while loading shared libraries: librustc_driver-7d23ff90.so: cannot open shared object file: No such file or directory
[cyryl@localhost ~]$ which rustc
/usr/local/bin/rustc
[cyryl@localhost ~]$ ldd /usr/local/bin/rustc 
	linux-vdso.so.1 (0x00007ffdd93f6000)
	librustc_driver-7d23ff90.so => not found
	libstd-7d23ff90.so => not found
	libc.so.6 => /lib64/libc.so.6 (0x00007f83755fe000)
	/lib64/ld-linux-x86-64.so.2 (0x00005593d7200000)
```

**Comment by cyplo** [comment]
Seems that this is the same issue as: #26860
Comment there references rust-lang/rust-installer#30 as the main culript. It has a patch already, so probably will be fixed soon :)

**Comment by mcpherrinm** [comment]
Fixed by https://github.com/rust-lang/rust-installer/commit/c37d3747da75c280237dc2d6b925078e69555499

**Comment by cyplo** [comment]
:+1:

**Comment by dumindu** [comment]
Fixed on Fedora 22, Thanks @mcpherrinm

**Comment by steveklabnik** [comment]
With a number of people saying this is fixed, i'm giving a close.
