### ISSUE TITLE
stability lint: check stability of macro uses, check bodies at def site

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#15728]
The stability infrastructure should apply to macros in two ways:
- It should be possible to provide a stability level for a macro definition. This should trigger the lint on any use of the macro.
- The body of a macro should be linted at the _definition_ site.

Of the two, the first is much more important. But it may require additional infrastructure in the AST to track e.g. the def_id of the macro that was expanded. (Currently, the expansion span information tracks only the name and source location of the macro.)

**Comment by huonw** [comment]
cc https://github.com/rust-lang/rust/issues/17316

**Comment by steveklabnik** [comment]
Triage: i am unaware of significant changes to any of this in a long time.

**Comment by Mark-Simulacrum** [comment]
Since, for example, [`select!`](https://doc.rust-lang.org/nightly/std/macro.select.html) is unstable, I think this is at least partially fixed. I think that the second item on the list isn't done, but I'm also not entirely sure what it means.

**Comment by steveklabnik** [comment]
Triage: still no changes, but I'm also not aware of any plans to change this. Closing.

**Comment by petrochenkov** [comment]
The first item is fixed, the second item is mitigated by `#[allow_internal_unstable]`.

**Comment by Nkwenti-Severian-Ndongtsop** [comment]
so far as a junior rust developer i will feel very happy contributing to the rust ecosystem, applying my skills and knowledge of problem solving if i'm given the opportunity

Recommended by [OnlyDust](https://onlydust.com/) for outstanding experience and quality contributions.
