### ISSUE TITLE
Rename one of sync::Mutex or sync::mutex::Mutex

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#15724]
They currently have very different semantics: the former is a lock-protected container while the latter is only a lock. I just spent a few minutes very confused, looking at the docs for one of them to understand code using the other.

Combined with #15723 and libstd-as-a-facade (many items with the same name documented in different modules are in fact the same item), this really brings down the doc’s usability.

`sync::Mutex` vs `sync::mutex::Mutex` is just the example I hit today, but same-name-but-different items is a pattern we should avoid in general.

**Comment by aturon** [comment]
This issue is no longer relevant after the `sync` overhaul.
