### ISSUE TITLE
Formatter::flags/std::fmt::rt::Flag should be implemented using the bitflags! macro

### ISSUE THREAD

**Issue by SiegeLord** [rust-lang/rust#15738]
This will make it a lot simpler to use that field.

**Comment by tamird** [comment]
Depends on https://github.com/rust-lang/rust/issues/18227

**Comment by alexcrichton** [comment]
Interpreting the flags today is not stable and for now I'm going to close this in favor of the internals thread about this topic: http://internals.rust-lang.org/t/stabilising-formatter-flags/1927/2
