### ISSUE TITLE
Allow single-value enum types to have size 0

### ISSUE THREAD

**Issue by mbrubeck** [rust-lang/rust#15747]
```
enum Foo { Foo }
std::mem::size_of::<Foo>() // evaluates to 1
```

Since type `Foo` has only one value, it could have size zero.  (This is already the case for single-valued struct types like `struct Foo;`.)

Open question: If this change is made, should `Foo as uint` still evaluate to `0` in the example above?

Note: It would still be possible to force a non-zero size using `[#repr(...)]` or `enum Foo { Foo = 1 }`.

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by SimonSapin** [comment]
https://github.com/rust-lang/rust/issues/37649#issuecomment-259175327
> frewsxcv and misdreavus on IRC point out that the discriminant is already eliminated in some cases:
>
> ``` rust
> playbot: enum Foo { SingleVariant(i32) } ::std::mem::size_of::<Foo>()
> 4
> playbot: enum Foo { SingleVariant(()) } ::std::mem::size_of::<Foo>()
> 0
> playbot: enum Foo { SingleVariant{} } ::std::mem::size_of::<Foo>()
> 1
> ```

**Comment by Mark-Simulacrum** [comment]
I'm nominating for the lang team to decide -- we should confirm that we want this before compiler team implements.

**Comment by nikomatsakis** [comment]
If the enum is not `#[repr(C)]`, it seems like something that is within our rights to do. I would assume that `Foo as usize` still gives `0`, even though the discriminant is not reified.

**Comment by RReverser** [comment]
> `enum Foo { Foo = 1 }`

I'd say this doesn't have to force non-zero-size either, only `repr` should. Any discriminant can be inlined into usages just like `0` one.

**Comment by nox** [comment]
I think any univariant fieldless enum which is not `repr(Rust)` should be a ZST, because just adding a single ZST field makes the enum a ZST.
