### ISSUE TITLE
doc: C<->Rust function table

### ISSUE THREAD

**Issue by zmike** [rust-lang/rust#15753]
It would be great if there was some table for showing functional equivalencies for common functions, ie. strdup, strtol, getenv

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#779
