### ISSUE TITLE
rustc: error when both both defining and using a module should be more specific

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#15769]
Given the following setup,
```rust
use test;
mod test {}
```
rustc says
```
mod-usage.rs:1:5: 1:9 error: unresolved import (maybe you meant `test::*`?)
mod-usage.rs:1 use test;
                   ^~~~
```
I ran into this while refactoring, but I imagine newcomers getting used to the `use`/`mod` distinction (and the fact that `mod` automatically `use`s) would benefit from a message more like:
```
mod-usage.rs:1:5: 1:9 error: cannot import `test` because it was already defined:
mod-usage.rs:1 use test;
                   ^~~~ import
mod-usage.rs:2 mod test {}
                   ^~~~ definition
```

It's also a bit strange that double-imports are allowed, but the situation above isn't. [RFC PR 116](https://github.com/rust-lang/rfcs/pull/116) could help regularize things.

**Comment by FlaPer87** [comment]
This has been fixed. The current error reported is:

```
test.rs:1:5: 1:9 error: import `test` conflicts with existing submodule [E0258]
test.rs:1 use test;
              ^~~~
test.rs:2:1: 2:12 note: note conflicting module here
test.rs:2 mod test {}
          ^~~~~~~~~~~
error: aborting due to previous error
```
