### ISSUE TITLE
Writing a custom crate attribute is impossible with the current plugin system

### ISSUE THREAD

**Issue by Kimundi** [rust-lang/rust#15778]
Currently, its not possible to write a custom attribute that applies to the crate, due to the way syntax extensions and the module system works.

- This does not work because inner attributes have to go first an a module body:
```
// crate.rs
#![feature(phase)]
#[phase(plugin)]
extern crate foo;
#![foo] // ERROR: An inner attribute is not permitted in this context
```
- This does not work because the attribute gets only loaded after it got used:
```
// crate.rs
#![feature(phase)]
#![foo] // Gets ignored because the syntax extension did not yet get loaded
#[phase(plugin)]
extern crate foo;
```

# Possible solutions
- Lift the ordering restriction between items.
- Make plugins mutual recursive visible, like regular items.

**Comment by kmcallister** [comment]
Is this true for attributes in general? Or only for attributes which are themselves syntax extensions (item decorators / modifiers)?

**Comment by Kimundi** [comment]
Its true for attributes in general, its only turning into an issue if a attribute comes from a `extern crate` though.

**Comment by kmcallister** [comment]
Attributes don't come from anywhere. They're just nested key/value data that any part of the compiler can query by name.  There's no central registration of attributes.

Also, plugin loading happens after a full parse and before any syntax expansion. So I'm not sure why the order of a plugin and some attribute the plugin will later check would matter.

Can you give a specific example of something you'd like to do with crate attributes that you cannot?

For example, this plugin:

```rust
#![feature(plugin_registrar)]
#![feature(box_syntax)]

extern crate syntax;
#[macro_use] extern crate rustc;

use syntax::{ast, attr};
use rustc::lint::{Context, LintPass, LintPassObject, LintArray};
use rustc::plugin::Registry;

declare_lint!(CRATE_NOT_OKAY, Warn, "crate not marked with #![crate_okay]");

struct Pass;

impl LintPass for Pass {
    fn get_lints(&self) -> LintArray {
        lint_array!(CRATE_NOT_OKAY)
    }

    fn check_crate(&mut self, cx: &Context, krate: &ast::Crate) {
        if !attr::contains_name(&krate.attrs, "crate_okay") {
            cx.span_lint(CRATE_NOT_OKAY, krate.span,
                         "crate is not marked with #![crate_okay]");
        }
    }
}

#[plugin_registrar]
pub fn plugin_registrar(reg: &mut Registry) {
    reg.register_lint_pass(box Pass as LintPassObject);
}
```

works as expected:

```
$ cat /tmp/foo.rs
#![feature(plugin, custom_attribute)]
#![plugin(lint_for_crate)]

fn main() { }

$ rustc -C prefer-dynamic --crate-type dylib lint_for_crate.rs

$ rustc -D crate-not-okay -L . /tmp/foo.rs  
/tmp/foo.rs:1:1: 4:13 error: crate is not marked with #![crate_okay] [-D crate-not-okay]  
/tmp/foo.rs:1 #![feature(plugin, custom_attribute)]  
/tmp/foo.rs:2 #![plugin(lint_for_crate)]  
/tmp/foo.rs:3  
/tmp/foo.rs:4 fn main() { }  
error: aborting due to previous error  

$ sed -i '3i#![crate_okay]' /tmp/foo.rs
$ rustc -D crate-not-okay -L . /tmp/foo.rs  
$ echo $?
0
```

**Comment by Kimundi** [comment]
Hm, it might be that since I opened this issue the plugin system changed in a way that makes this work. I'll have to check with the code that had this issue...

**Comment by kmcallister** [comment]
I added a regression test for the original issue. Please open a new ticket if you find something that's still broken :)
