### ISSUE TITLE
CharOffsets should impl `Iterator<(char, uint)>` instead of `Iterator<(uint, char)>`

### ISSUE THREAD

**Issue by liigo** [rust-lang/rust#15798]
to match with its name, Char+Offset.

(Another option is rename `CharOffsets` to `OffsetChars`, and rename StrSlice::`char_indices` to `index_chars`.)

**Comment by steveklabnik** [comment]
CharOffsets no longer exists, was it renamed, or just removed?

**Comment by huonw** [comment]
Renamed to [`CharIndices`](http://doc.rust-lang.org/nightly/std/str/struct.CharIndices.html).

**Comment by steveklabnik** [comment]
Ah. This has been marked as stable. @aturon ?

**Comment by aturon** [comment]
I agree with @huonw that matching `enumerate` is desirable here.

I also agree that `indexed_chars` would be a reasonable substitute, but not sure if it's worth changing (and still feels slightly more awkward than the current name).

In any case, nominating for 1.0-beta P-backcompat-libs.

**Comment by pnkfelix** [comment]
closing, wont fix
