### ISSUE TITLE
Consider an AST validation function/pass to assist with debugging user-defined macros

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#15819]
There's a variety of invariants in the AST, e.g. the `Expr` in a `PatLit` should (AFAIK) be an `ExprLit`, and the  `Option<Expr>` in an `ExprIf` should be either a `ExprBlock` or `ExprIf`. It would be convenient if the compiler either had a AST validation pass run after macro expansion (could include verifying that there are no macros left in the AST), a validation function called on the resulting AST after each macro is expanded or just a series of manual functions that syntax extension authors can call on the code they generate to help debugging.

(The first two should, IMO, be opt-in, since most users won't want to be wasting the compilation time on something that _should_ never trigger if they're not writing their own macros.)

**Comment by kmcallister** [comment]
It seems like this could be a lint, although we may need a way to run it earlier in the pipeline.  That opens up the possibility of reusing some of the machinery in plugins to enforce style and code structure.  Perhaps there's a nice declarative language for describing valid and invalid AST shapes.

> The first two should, IMO, be opt-in, since most users won't want to be wasting the compilation time on something that *should* never trigger if they're not writing their own macros.

My hunch is that the compile time won't be significant, unless our invariants are *really* complex.  Converting the lint system from one pass to several dozen increased the compile time for librustc (before it was split up) by about half a second.  It's hard to do anything syntax-focused that takes significant time compared to trans and LLVM.

**Comment by steveklabnik** [comment]
Triage: I think that this solution here is HIR/MIR, @nrc?

**Comment by nrc** [comment]
This is not addressed by the HIR/MIR, but it is likely that this would be a totally different concept in an AST-less macro world. Let's see how that pans out, I guess.

**Comment by steveklabnik** [comment]
This is an interesting idea, but has gotten basically no comments in years. I don't think keeping this issue open is helpful, and so I'm going to close. If you'd like to work on fixing this, please let me know and we can re-open!
