### ISSUE TITLE
`fs::rename` behavior differs on windows

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#15836]
This program will succeed on unix but fail to succeed on windows. The unix behavior is surprising to me!

```rust
use std::io::{fs, UserRWX};

fn main() {
    fs::mkdir(&Path::new("test"), UserRWX).unwrap();
    fs::mkdir(&Path::new("test2"), UserRWX).unwrap();
    fs::rename(&Path::new("test"), &Path::new("test2")).unwrap();
}
```

**Comment by untitaker** [comment]
FWIW Python's rename fails on Windows if the destination path exists: https://docs.python.org/2/library/os.html#os.rename

**Comment by alexcrichton** [comment]
With the I/O reform having happened since this was opened, I'm going to close this as "not a bug"

**Comment by untitaker** [comment]
What is the behavior now?

**Comment by alexcrichton** [comment]
We just shell out to the system call and reexport that behavior.
