### ISSUE TITLE
no trailing `( )` error message presumes user wanted nullary enum

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#15855]
Here is some code that someone learning Rust on IRC asked about:

``` rust
pub fn factorial<T: One + PartialOrd + Add<T, T> + Sub<T, T>>(num: T) -> T {
// This works
if num == One::one() {
num
}
else {
factorial(num-One::one())*num
}

// This doesn't
// -> nullary enum variants are written with no trailing `( )` for line 13
//match num {
// One::one() => num,
// _ => factorial(num-One::one())*num
//}
}
```

The issue here is that the user didn't realize that `One::one()` is a function call rather than a constructor (or at least that's my mental model of what they were doing; its possible they did know it was a function call and don't understand how `match` works).

So the error message about nullary enum variants was confusing to them.

Since we emit this error message before we have actually done any resolve, the compiler cannot confirm whether the pattern `N()` is actually an attempt to refer to a nullary enum variant `N`, or if it is a function call.

We should consider revising the error message to not assume that the end user was talking about a nullary enum variant.  E.g. perhaps text like:

>  expected pattern but found path with trailing `( )`.
> Note: function calls are not patterns, and nullary enum variants are written with no trailing `( )`.

**Comment by steveklabnik** [comment]
Triage: Ther'es some other similar bugs about this, a better diagnostic would be good.

**Comment by matthewjasper** [comment]
Now that such enums are allowed the error message is now
```text
error[E0532]: expected tuple struct/variant, found method `One::one`
  --> <source>:23:2
   |
23 |  One::one() => num,
   |  ^^^^^^^^ not a tuple struct/variant
error: aborting due to previous error
```

**Comment by Dylan-DPC** [comment]
Closing this since the error message isn't confusing 😄
