### ISSUE TITLE
Self-calling functions; usecase: macros

### ISSUE THREAD

**Issue by justanotheranonymoususer** [rust-lang/rust#15854]
_I've created a [discussion topic](http://www.reddit.com/r/rust/comments/2ba3az/macros_writeln_and_the_semicolon/) on Reddit, but for some reason it disappeared from the Rust page, so I'm filling an issue here. If there's a better place to discuss similar suggestions, please tell me._

I was just playing with Rust on http://rustbyexample.com/, and I've accidentally discovered that writeln can be called without a semicolon.
It doesn't look like a big deal, but for a perfectionist like me, I see it as a consistency flaw, especially for (probably) the most common macro in the language.

The author of **Rust by example** explained what's going on [here](https://github.com/japaric/rust-by-example/issues/183), but that doesn't look right to me. Even C has a do-while(0) hack for this case.

[This](http://is.gd/ajFYN1) is an expanded `println!("test")`. The `match` looks very similar to the do-while(0) C hack for macros, and I think that it's the wrong way to do it, not only because it looks and feels like a hack, but also because it behaves differently than a native Rust function. For example, `println!("test") println!("test")` compiles, while `returns_unit() returns_unit()` doesn't.

My proposal: use a self-calling function, similar to what [JavaScript allows](http://stackoverflow.com/questions/592396/what-is-the-purpose-of-a-self-executing-function-in-javascript). I don't know whether it's currently possible in Rust, but if not, I think it could be a natural addition to the language. [Here's](http://is.gd/CZ7Y8u) how I expect it to look, more or less.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#728
