### ISSUE TITLE
Move checking of tests with little x-platform risk to supplemental auto bot, turn on lexer tests

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#15880]
We have tests in tree that the lexer conforms to an official grammar, but the bots are not running them yet. These tests take a long time to run, as will the impending tests of the parser. We need to do a few things to turn them on:
- Port grammar and lexer tests to rustbuild from grammar.mk
- Add a `make check-extra` in `src/bootstrap/mk/makefile.in` that runs the grammar and lexer tests. Submit PR to rust-lang/rust
- Create a Dockerfile that is capable of running the tests
- Make modifications to rust-buildbot that a new `auto-extra` builder
- Submit PR to rust-buildbot.

cc @cmr @alexcrichton

**Comment by edunham** [comment]
Help wanted: Create Docker image with all dependencies to run these tests, and take a guess at the Buildbot PR necessary to run the new image as a non-gating builder.

**Comment by alexcrichton** [comment]
Grammar bot is https://github.com/rust-lang/rust/issues/28592 and otherwise we basically have a supplemental bot running extra tests.
