### ISSUE TITLE
`Instruction does not dominate all uses` LLVM error in a pattern match with a ref pattern and dereference of a box

### ISSUE THREAD

**Issue by omasanori** [rust-lang/rust#15892]
The functions below are OK:
```rust
fn foo1(x: Option<Box<int>>) -> Option<int> {
    let res = match x {
        Some(ref v) => v.clone(),
        None => return None
    };
    Some(*res)
}
fn foo2(x: Option<Box<int>>) -> Option<int> {
    let res = match x {
        Some(ref v) => Some(*v.clone()),
        None => return None
    };
    return res;
}
```
but:
```rust
fn foo3(x: Option<Box<int>>) -> Option<int> {
    let res = match x {
        Some(ref v) => *v.clone(),
        None => return None
    };
    Some(res)
}
```
produces a LLVM ERROR. The message is:
> Instruction does not dominate all uses!
>  %8 = load i64** %2
>  %12 = bitcast i64* %8 to i8*
> LLVM ERROR: Broken function found, compilation aborted!

I'm sorry if it isn't a minimum example of this issue.

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/issues/18845 is a dup that has a smaller test case, so I'm giving this a close in favor of that.
