### ISSUE TITLE
Add default type parameters to simplify Add trait

### ISSUE THREAD

**Issue by erickt** [rust-lang/rust#15898]
@ben0x539 suggested on [/r/rust](http://www.reddit.com/r/rust/comments/2bbeqe/it_started_out_with_great_enthusiasm_but_ended_up/cj3s2sd) that the Add and related traits could be simplified for the common case when the left hand side and right hand side are the same type:

```
trait Add<RHS = Self, Result = Self> { ... }

impl<T: Add> Add for Vec2<T> { ... }
```

**Comment by steveklabnik** [comment]
`Add` has changed significantly, and while `defualt_type_params` got accepted, changing it more would require an RFC. Feel free to open an issue if it's still a pain point.

**Comment by huonw** [comment]
The changes actually included default type parameters, so I think this is solved.
