### ISSUE TITLE
Better error message for invalid octal digit

### ISSUE THREAD

**Issue by jruderman** [rust-lang/rust#15903]
fn main() {
        0o19;
    }

Gives me:

    error: expected one of `;`, `}` but found `9`

It would be better to say something like:

    error: `9` is not a valid octal digit

**Comment by steveklabnik** [comment]
Same error today.

**Comment by bombless** [comment]
I think this has been fixed by https://github.com/rust-lang/rust/pull/23872
The example code give us `error: invalid digit for a base 8 literal` for Beta.

**Comment by fhahn** [comment]
It is indeed fixed in master and there is also a testcase [src/test/parse-fail/lex-bad-octal-literal.rs](https://github.com/rust-lang/rust/blob/master/src/test/parse-fail/lex-bad-octal-literal.rs), so I think this issue can be closed.
