### ISSUE TITLE
Fixed length array type with high un-suffixed count literal incorrectly treated as negative count

### ISSUE THREAD

**Issue by kballard** [rust-lang/rust#15919]
A fixed-length array expression with a repeat count with the high bit set and no suffix is incorrectly treated as a negative count.

On a 64-bit machine:

```rust
fn main() {
    let x = [0u, ..9223372036854775808];
}
```

This results in

```
unnamed.rs:2:20: 2:39 error: expected positive integer for repeat count but found negative integer
unnamed.rs:2     let x = [0u, ..9223372036854775808];
                                ^~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
```

**Comment by bombless** [comment]
```rust
fn main() {
    let x = [0usize; 9223372036854775808];
//~^ error: the type `[usize; 9223372036854775808]` is too big for the current architecture
}
```
Seems that it is not an issue any more.

**Comment by bombless** [comment]
I'm thinking that if it behave differently on different platforms, is it making it an undefined behavior?
And I think designating an exact behavior for UB cannot possibly be a breaking change?

**Comment by kballard** [comment]
@bombless This does not make it undefined behavior. It's very much defined behavior. If it were undefined behavior, then any `usize` or `isize` literal would be undefined behavior as well, because the range of valid values is architecture-dependent.
