### ISSUE TITLE
Expose thread/task priorities

### ISSUE THREAD

**Issue by hoeppnertill** [rust-lang/rust#15927]
Trying to find an equivalent to the following C++ code,

```c++
struct sched_param p;
p.sched_priority = priority;
pthread_setschedparam(thread_, SCHED_FIFO, &p);
```
I failed to set the task priority using just exposed API.

brsons statement on IRC,
> you *can* just call the pthread functions, but you'll be creating a thread that doesn't have the runtime setup properly

leaves little doubt that an exposed API for this actually is needed.

**Comment by steveklabnik** [comment]
@alexcrichton is this still relevant with all the runtime changes?

**Comment by alexcrichton** [comment]
Yes this may still be a plausible extension to add, but it would likely start out on crates.io before moving in tree.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#819
