### ISSUE TITLE
Add a min heap option to PriorityQueue

### ISSUE THREAD

**Issue by treeman** [rust-lang/rust#15947]
Currently `PriorityQueue` defaults to a max-heap and if you want to use it as a min-heap you need to overload `Ord` and change the comparison.

But you should be able to use the default ordering and simply specify that you want a min-heap, so we can use it for types like `(uint, &str)` for example.

The simple idea would be to simply make a `new_min_heap` and a `min_heap_with_capacity` constructors.

Thoughts?

**Comment by steveklabnik** [comment]
@Gankro what's the state of this these days?

**Comment by Gankro** [comment]
collect-rs has an experimental design for Comparators. We're baking it out-of-tree for now. Should be back-compat to add later with default generics.

**Comment by heruku** [comment]
Interested in this as well.

**Comment by huonw** [comment]
There is now [a `revord` crate](https://crates.io/crates/revord), which can be used like (I believe):

```rust
extern crate revord;

let mut pq = BinaryHeap::new();

pq.push((RevOrd(1), "foo"));
pq.push((RevOrd(0), "bar"));
pq.push((RevOrd(2), "baz"));

assert_eq!(pq.pop(), (RevOrd(0), "bar"));
```

**Comment by malbarbo** [comment]
@steveklabnik Considering https://github.com/rust-lang/rust/pull/40720, maybe this can be closed?

**Comment by alexcrichton** [comment]
We discussed this during triage today and while we'd like to see this feature it'd likely be done with comparators nowadays, which would require an RFC, so we decided to close this.

**Comment by gotyaoi** [comment]
Apologies for poking an old issue, but I just ran into a situation where a min-heap would be useful. I'm currently working around it by wrapping all the elements I put on the heap in std::cmp::Reverse, but the (wrap->push), (pop->unwrap) operations feel sort of clumsy. Additionally, if I didn't have to wrap, I could construct the heap with `from(vec: Vec<T>)`, where I'm doing `from_iter` with a map right now.

@alexcrichton's last message mentioned doing this with comparators, which I assume meant redoing the BinaryHeap to use comparators for item comparison, and allowing the user to specify the comparator. I'm not sure where this is though, as I believe comparators are still in a separate crate? (https://github.com/contain-rs/compare)

Is there anything I could do to help work on this?

**Comment by sekineh** [comment]
I have a binary-heap-plus crate that is backward compatible with std’s BinaryHeap.

You might find it useful:
https://crates.io/crates/binary-heap-plus

**Comment by Lucretiel** [comment]
Is there some reason that we can't just use [std::cmp::Reverse](https://doc.rust-lang.org/std/cmp/struct.Reverse.html)? Perhaps we can extend it to implement Deref for the interior value.

**Comment by sekineh** [comment]
For min heap only support, Reverse is OK.

But there are use cases where you need to compare by arbitrary order. Of course C++ has this.

**Comment by sekineh** [comment]
Implementing Ord and friends includes a logic duplication (PartialOrd etc) and not simple enough, in my opinion.

**Comment by noelzubin** [comment]
why was this closed ? was this implemented ?
