### ISSUE TITLE
dsymutil hang when compiling Servo without optimization

### ISSUE THREAD

**Issue by metajack** [rust-lang/rust#15978]
Compiling https://github.com/servo/servo/tree/rustup-20140716 works fine on OS X, but if you add `--disable-optimize` on configure, then the build will hang in libscript. Inspecting rustc in a debugger shows that it's waiting on an external process; the process appears to be dsymutil since that is still running.

@alexcrichton suspects it's a debuginfo related bug.

**Comment by steveklabnik** [comment]
This seems to be fixed now, yeah?

**Comment by jdm** [comment]
Sounds like it.
