### ISSUE TITLE
entertaining error message on bad macro syntax

### ISSUE THREAD

**Issue by dhardy** [rust-lang/rust#15980]
UPDATE: [Mentoring instructions below.](https://github.com/rust-lang/rust/issues/15980#issuecomment-331291471)

---

Try compiling this code:

```
use std::io;

fn main(){
    let x: io::IoResult<()> = Ok(());
    match x {
        Err(ref e) if e.kind == io::EndOfFile {
            return
        }
        _ => {}
    }
}
```

I (using Rust 0.11.0) get the very misleading message:

```
$ rustc match_syntax_err.rs
match_syntax_err.rs:7:13: 7:19 error: found `return` in ident position
match_syntax_err.rs:7             return
                                  ^~~~~~
match_syntax_err.rs:8:9: 8:10 error: expected `:` but found `}`
match_syntax_err.rs:8         }
```

when actually all that's wrong is a missing `=>`. Not really a good brain teaser on a Friday evening ;)

**Comment by steveklabnik** [comment]
This error message is the same today. How awkward.

**Comment by bombless** [comment]
I guess we can summary a pattern here (missing `=>` between pattern and block) to the parsing rule that allow us to add something similar as `check_no_chained_comparison`.

I suspect another valid approach would be, don't mention the ident thing, just focus on the fact that a value is needed here (a struct literal, in fact), so we can just say "invalid struct literal, unexpected `return` here" or even simpler, "`return` not allowed inside pattern matching". At least this will warn the user that the `return` is not really inside a block.

**Comment by gchp** [comment]
On `1.10.0-nightly` this gives:

```
test.rs:5:30: 5:31 error: expected one of `.`, `=>`, `?`, or an operator, found `{`
test.rs:5         Err(ref e) if 1 == 2 {
                                       ^
error: aborting due to previous error
```

This seems accurate enough to me, the compiler is pointing out where it is expecting to find the `=>`, and mentioning it in the error message. Do we need something more specific than this?

**Comment by dhardy** [comment]
[The error I see is still pretty misleading](https://is.gd/40I4QJ)

**Comment by estebank** [comment]
Current output:

```
error: expected identifier, found keyword `return`
 --> src/main.rs:7:13
  |
7 |             return
  |             ^^^^^^
```

---

[`parse_pat`] can [parse a struct and recover from an error](https://github.com/rust-lang/rust/blob/1b55d19479eabcb5d6cbda651187c7004aa28f7f/src/libsyntax/parse/parser.rs#L3560-L3573). It should attach a secondary label pointing at the start of the struct constructor being parsed (I believe it should be `lo.to(self.prev_span)`) with a label along the lines of "while parsing the fields for this struct". This would end up looking close to this:

```
error: expected identifier, found keyword `return`
 --> src/main.rs:7:13
  |
6 |         Err(ref e) if e.kind == io::EndOfFile {
  |                                 ------------- while parsing the fields for this struct
7 |             return
  |             ^^^^^^ expected identifier, found keyword

```

[`parse_pat`]: https://github.com/rust-lang/rust/blob/1b55d19479eabcb5d6cbda651187c7004aa28f7f/src/libsyntax/parse/parser.rs#L3465
