### ISSUE TITLE
rustdoc: Struct variant fields don't have the right path in the search index

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang/rust#16017]
``` rust
#![crate_type="lib"]
#![feature(struct_variant)]

pub enum Enum {
    Bar { pub name: String }
}
```

Running rustdoc on this, and then searching for `name` yields one result, with the incorrect path `foo::Enum::Enum::name`. Because the path is wrong, the link is also broken.

**Comment by tomjakubowski** [comment]
Still broken. Updated code sample:

```rust
#![crate_type="lib"]

pub enum Enum {
    Bar { name: String }
}
```

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by tomjakubowski** [comment]
Update: still working on this, I've found a path to a solution and will submit a PR soon.
