### ISSUE TITLE
Consider returning &c_char from CString::as_ptr

### ISSUE THREAD

**Issue by Ms2ger** [rust-lang/rust#16035]
This should make it a lot harder to run into the bug mentioned in its documentation (`let p = foo.to_c_str().as_ptr();`).

**Comment by aturon** [comment]
@alexcrichton Should we repurpose this bug with the new `CString` API?

**Comment by alexcrichton** [comment]
This may be less relevant now that the API of `CString` has been pared back so much. It's much more clear that `CString::from_slice(foo).as_ptr()` is probably not going to outlive the expression thatn `foo.to_c_str().as_ptr()`, so I'd also just be fine closing this.

**Comment by Ms2ger** [comment]
From IRC today:
`<noodle> Why are these two c-pointers the same? http://is.gd/2KlvtT`
```rust
use std::ffi::CString;

fn main() {
    let a = "1";
    let b = "2";
    let a_ptr = CString::from_slice(a.as_bytes()).as_ptr();
    let b_ptr = CString::from_slice(b.as_bytes()).as_ptr();
    
    println!("{:?}", a_ptr);
    println!("{:?}", b_ptr);
}
```

**Comment by aturon** [comment]
@alexcrichton I'm not sure I agree, it seems like exactly the same pitfalls are there. I think we should consider adding a method like the one proposed in this issue.

**Comment by aturon** [comment]
Nominating for 1.0-beta (P-backcompat-libs, as it already is).

**Comment by pnkfelix** [comment]
1.0 beta, P-backcompat-libs, I-needs-decision,.

**Comment by aturon** [comment]
Decision: we want to make a change like this, but there are some other ramifications for using `CString` this way. In particular there are patterns around `Option<CString>` for representing nullable data and converting to a pointer that this would make very painful.

We want to introduce some general libraries to cover patterns like that before we make this change.

So all told, we're OK stabilzing `as_ptr` for 1.0, and then later deprecating in favor of `as_ref` when this other infrastructure is ready.

Closing as WONTFIX (for now).

**Comment by alexcrichton** [comment]
I have opened an [RFC issue](https://github.com/rust-lang/rfcs/issues/892) about this issue more broadly which may help alleviate some concerns here as well.
