### ISSUE TITLE
Comparing a `String` and a `&str` leads to a scary error

### ISSUE THREAD

**Issue by renato-zannon** [rust-lang/rust#16065]
Given that `std::os::args()` returns a `Vec<String>`, and `String`s and `&str` aren't directly comparable, I think the following pattern will be pretty common:

1. Rust newbie tries to implement a simple program (possibly her/his first) that pattern matches on a command line argument:

    ```rust
    match std::os::args()[0] {
        "something" => { /* ... */ },
        _ => { /* ... */ },
    }
    ```

1. Rust newbie gets a scary error message that talks about structs and pointers:

    ```
    mismatched types: expected `collections::string::String` but found `&'static str` (expected struct collections::string::String but found &-ptr)
    ```

1. Rust newbie gets frustrated

Is it possible to create a friendlier error message if someone tries to compare a `&str` and a `String`, possibly with a link to [the string guide](http://doc.rust-lang.org/guide-strings.html)?

**Comment by kungfumike** [comment]
Hi, if you are here from the same search that brought me here:

```rust
match  &*(collections_string_string_variable) {
  "static_string_to_match" => "static_string_or_whatever_to_return",
  _ => "default_static_string_to_return"
}
```
Yes, I have every hope of getting this into the docs or rust by example or something, but for now...

**Comment by politician** [comment]
> If you are here from the same search that brought me here...

Yup.

```Rust
fn main() {
    // using type inference
    let s = "hello, world";

    match s {
        "something" => { println!("mumbles something about types"); }
        _ => { println!("{}", s); }
    }
    
    
    // using a type annotation...
    let t : String = "foobar".to_owned();

    match &*t {
        "something" => { println!("mumbles something about types"); }
        _ => { println!("{}", s); }
    }    
}
```

**Comment by birkenfeld** [comment]
This is pretty basic material. Nothing to do for diagnostics, I think.

**Comment by arielb1** [comment]
Yeah I don't think we would ever fix this, except for the error eventually showing `String` in the path.
