### ISSUE TITLE
dataflow: collapse straight-line code to one node in cfg

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#16077]
The current cfg representation has distinct control-flow nodes at a very fine grain, leading to graphs that can look something like (graphviz DOT syntax):

```
A -> B1 -> B2 -> B3 -> D
A -> C1 -> C2 -> C3 -> C4 -> D
```

this is wasteful in dataflow because it ends up allocating a separate bitset for each individual node.  We should be able to first _reduce_ the above graph to one that collapsed the linear paths, and then apply dataflow analysis to the reduced graph.

**Comment by steveklabnik** [comment]
@pnkfelix what's the status of this today?

**Comment by steveklabnik** [comment]
I'm going to give this a close, please let me know if there's something still relevant here.
