### ISSUE TITLE
(meta) Triage old issues

### ISSUE THREAD

**Issue by reem** [rust-lang/rust#16087]
There are many old issues that have no relevance today and just were never closed. Inactive issues that have been made irrelevant should be closed.

I'd be glad to go through and do this, but I can't close issues. Who should I tag in old issues who would be responsible for this?

**Comment by alexcrichton** [comment]
Seeing how we're doing triage (I'm visiting this now), closing :)

**Comment by steveklabnik** [comment]
Hehe, yes I've been hitting this hard.
