### ISSUE TITLE
Consider building rust with Cargo

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#16091]
In #2237 it was resolved to rewrite the build system in Rust, but that never ended up happening. It was later decided that we should build Rust with rustpkg, but that also ended up not happening. As a natural continuation of said issue we should consider building Rust with Cargo.

There are certainly some difficulties in doing this, some of which I can think of are:

* If cargo isn't built as part of the build process, changing the meaning of CLI flags may be tricky (over time)
* Is cargo's configuration flexible enough to encode the bootstrapping process?
* Is going through this change worth the effort?

This is most certainly a low priority issue, I believe building servo with Cargo to be a better milestone than building Rust.

**Comment by Gankro** [comment]
@alexcrichton can you give us an update on the efforts to get this done? Some stuff flared up in the summer, but I dunno what came of it.

**Comment by jonas-schievink** [comment]
@Gankro That was #27003

I don't think all of the limitations in Cargo (whichever these were) were addressed since then. Specifically, the PR depended on rust-lang/cargo#1802.

**Comment by alexcrichton** [comment]
In addition to the links that @jonas-schievink I'm also working on this [on an external branch](https://github.com/alexcrichton/rust/tree/cargo-build). My current stance is that I would like to avoid two build systems at all costs, so the only way to land this would be to entirely obsolete the current build system, which is taking some time to do :).

**Comment by alexcrichton** [comment]
Done!

rustbuild is tracked here -- https://github.com/rust-lang/rust/issues/31590
