### ISSUE TITLE
Rustdoc could (have an option to) create a top-level index page

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#16103]
Currently rustdoc creates `doc/foo/index.html` `doc/bar/index.html` (etc.) for crates `foo`, `bar`, along with `doc/searchIndex.js`. We could provide a way to create a human readable `doc/index.html` summarising all the crates in a folder (like how the search index works).

This could even take a markdown/html file as input to provide a longer description (theoretically this may allow Rust's current `index.md` top-level file to be properly integrated into the crate docs, although this may not be desirable, which is why this functionality should be optional).

**Comment by steveklabnik** [comment]
Triage: no change. We have been discussing a Cargo feature which would let you build standalone files with Rustdoc, so I'm not sure if maybe that isn't a better approach anyway. Maybe.

**Comment by nixpulvis** [comment]
:+1:

**Comment by nixpulvis** [comment]
I'm thinking this could be solved in addition to a way for cargo to build arbitrary docs. For example.

```
<project>/
    doc/
        index.<ext>
        dir/...
        <filename>.<ext>
    src/
    ...
```

Here the `index.<ext>` will be the index page, and other files are served according to the file directory structure.

**Comment by frewsxcv** [comment]
> We have been discussing a Cargo feature which would let you build standalone files with Rustdoc

Link to the associated issue: https://github.com/rust-lang/cargo/issues/739

**Comment by steveklabnik** [comment]
Triage: no change. @rust-lang/rustdoc do we ever plan on implementing this?

**Comment by GuillaumeGomez** [comment]
That is actually a good idea! It's shame I never came across it earlier. Adding it.

**Comment by QuietMisdreavus** [comment]
Update: This was implemented in https://github.com/rust-lang/rust/pull/54543, which is currently being tested by bors.

**Comment by GuillaumeGomez** [comment]
And it has been merged so I'm closing it.
