### ISSUE TITLE
Periodic timers behave unexpectedly with 0ms duration

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#16148]
It appears that periodic timers don't send any events when given a period of 0. Although it seems useless, I would expect either to receive a flood of events or for it to be forbidden.

I intend to check in a workaround as part of https://github.com/rust-lang/rust/pull/15934 that silently sets the period to 1ms, but that shouldn't be a long-term sol'n.

Here's a test case:

```
    iotest!(fn periodic_zero() {
        let mut timer = Timer::new().unwrap();
        let rx = timer.periodic(Duration::milliseconds(0));
        rx.recv();
        rx.recv();
        rx.recv();
        rx.recv();
    })
```

**Comment by alexcrichton** [comment]
These are being removed shortly, so closing.
