### ISSUE TITLE
rustdoc: Descriptions on statics disrupt the layout

### ISSUE THREAD

**Issue by passcod** [rust-lang/rust#16150]
Using this sample source file: https://gist.github.com/passcod/748067f10d2aa4ecaa4e

Single-line description on static:

![static-doc-1](https://cloud.githubusercontent.com/assets/155787/3773052/0e67b87a-1908-11e4-9da5-95e45cfb19b6.png)

---

Multi-line:

![static-doc-2](https://cloud.githubusercontent.com/assets/155787/3773053/0e92b9d0-1908-11e4-9ab2-5e54a7b92d26.png)

---

That makes documenting statics useless at best when rendering the docs.

**Comment by alexcrichton** [comment]
The values of statics are no longer rendered, so this is now fixed!
