### ISSUE TITLE
Add a way to reset MemWriter

### ISSUE THREAD

**Issue by SiegeLord** [rust-lang/rust#16167]
MemWriter recently lost its ability to seek due to speed concerns, which removed any way of resetting/truncating it (i.e. seeking backwards). Could this be added? A possible API/implementation would be:

~~~rust
// Does nothing if new_len is greater than current length
pub fn truncate(&mut self, new_len: uint) { self.buf.truncate(new_len); }
~~~

Alternatively, perhaps a new constructor could be added which would wrap an existing `Vec` which would allow me to do this:

~~~rust
let writer = MemWriter::new();
let mut vec = writer.unwrap();
vec.truncate(new_len);
let writer = MemWriter::wrap(vec);
~~~

@erickt, I recall talking to you about this on IRC, so you may have some thoughts.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#872
