### ISSUE TITLE
rustdoc hides the sidebar

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#16174]
The sidebar is automatically hidden when the window is smallish. In the current rustdoc format, the sidebar is essential for navigation. Right now I cannot have the docs at 100% side by side with an editor. See http://pubs.opengroup.org/onlinepubs/9699919799/ for documentation that doesn't have this problem (it might have other problems but it shows that you can have a sidebar at every screen size.) You don't even have to scroll horizontally.

**Comment by steveklabnik** [comment]
Triage: still a problem.

We made the book have a hamburger menu on mobile, could probably do the same here.
