### ISSUE TITLE
rustdoc needs a way to specify HTML metadata for standalone docs

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#16178]
The HTML meta tags for descriptions and keywords are both important for SEO. For library docs we can generate this information automatically, but not for standalone docs.

I've never seen any such markdown extension, though maybe Jekyll headers can do this. We may need to invent something.

cc #12466.

**Comment by steveklabnik** [comment]
triage: no change

**Comment by edunham** [comment]
@thehydroimpulse Could you link the PR from this issue to make it easier to track?

**Comment by thehydroimpulse** [comment]
@edunham It's a really old PR. #16374

**Comment by edunham** [comment]
aww, looks like it got stalled on insufficient time for cleanup. Thanks for the link!

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by steveklabnik** [comment]
@rust-lang/rustdoc, are we interested in this feature?

**Comment by GuillaumeGomez** [comment]
I can add it.

**Comment by GuillaumeGomez** [comment]
Actually we can already add data in headers through `--html-in-header` option. Closing it then.
