### ISSUE TITLE
Method links in trait implementations are useless

### ISSUE THREAD

**Issue by SiegeLord** [rust-lang/rust#16171]
Consider this section: http://doc.rust-lang.org/std/io/struct.BufWriter.html#implementations None of the methods implemented by this type are documented, and if you click on one of their names, it merely moves the method to the top of the page.

I think the method links should go to the trait's methods, which do have documentation. Alternatively, the documentation could be inlined.

**Comment by steveklabnik** [comment]
Yes, this is for linking to the specific method. We already have issues open about documentation on traits and/or implementations, so I'm giving this a close.
