### ISSUE TITLE
sync: Inconsistant naming?

### ISSUE THREAD

**Issue by KokaKiwi** [rust-lang/rust#16214]
Just reading doc about `sync` crate, and I saw some different naming order in static values used.
- `MUTEX_INIT` in sync::mutex
- `ONCE_INIT` in sync::one
- But `INIT_ATOMIC_BOOL` / `INIT_ATOMIC_INT` / `INIT_ATOMIC_UINT` in sync::atomics

Why not `<name>_INIT` like others in the crate?

I know that's not a big issue, but it surprised me when I saw it.

**Comment by steveklabnik** [comment]
This was fixed, the atomics have the same names now.
