### ISSUE TITLE
Consider handling signals to catch hard crashes of rustc to provide nice ICE message

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#16238]
E.g. if `rustc` segfaults or `abort`s we could (try to) catch the signals to make a best-effort attempt to print an informative ICE message, like gcc:

```
$ python -c 'print ("int main(){" + "*" * (10**6) + "}")' | gcc -x c -
gcc: internal compiler error: Segmentation fault (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
```

(It's fine if this doesn't work on all platforms, since theoretically no-one will ever see it... ;) )

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by pnkfelix** [comment]
I don't know if a change along these lines would be a net benefit. At the very least, I'd want to double-check that installing such a signal handler does not cause a degradation of the experience trying to **debug** the cause of the sigsegv under gdb/lldb.

triage: P-low.

Nominating for discussion at T-compiler meeting, with intent to close.

**Comment by spastorino** [comment]
After talking with @pnkfelix during triage about this. We're inclined to close this issue due to being uncertain if having this issue open is any better. Maybe this feature needs a design meeting.

Closing but please feel free to reopen if you disagree with us :).
