### ISSUE TITLE
io::walk_dir could have a more detailed return value, to avoid extra stat calls

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#16236]
When calling `walk_dir` one often wishes to handle files and directories differently, the `walk_dir` call knows this internally (it calls `.is_dir` and `readdir` etc.) but this is not passed on to the users, and so users are forced to call `.is_dir` etc. themselves.

Maybe `walk_dir` could return a `Iterator<DirEntry>`, with (as a bikeshedable suggestion)

```rust
struct DirEntry {
    pub path: Path,
    pub stat: FileStat
}
```

(Inspired by http://legacy.python.org/dev/peps/pep-0471/ , which shows dramatic performance improvements with changes similar to this.)

**Comment by alexcrichton** [comment]
This is now implemented.
