### ISSUE TITLE
Allow destructors to be run directly on a memory location, so it is not impossible to handle location-dependent values

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#16242]
Currently, the only way for a library to run a destructor on a value is to let it fall out of scope while on the stack, that is, types wrapping raw pointers (like `Vec` and `Rc`) have to call `ptr::read` and let the resulting value drop to destroy their contents. This moves values in memory, and thus makes it literally impossible to use `Vec` or `Rc` (or any other library defined container type) for types with destructors that depend on the location of the value in memory.

This could be avoid we had a `destroy_directly(&mut T)` intrinsic that destroyed that memory location, and so what is currently written `ptr::read(x)` (or `drop(ptr::read(x))`) would be written `destroy_directly(&mut *x)` and (for types with `Drop` impls) effectively be just calling `(&mut *x).drop()`.

e.g. https://github.com/rust-lang/rust/blob/795f6ae829ab1bfd72394a5da9096e2717ec0f62/src/libcollections/vec.rs#L1539 (there's a variety of other `ptr::read`s for a similar purpose in this file, and in other low-level code).

As a real-world example, putting a series of [`std::comm::Handle`](http://doc.rust-lang.org/master/std/comm/struct.Handle.html) into a preallocated `Vec` (to satisfy the requirement that they must not move in memory after calling `.add`) will still break, because the destructors [asserts that the memory address is the same as it was](https://github.com/rust-lang/rust/blob/795f6ae829ab1bfd72394a5da9096e2717ec0f62/src/libsync/comm/select.rs#L279) and thus `Vec` moving things in memory upsets it. The value being location dependent is bad, but it seems very reasonable to just destroy things in place to allow it to mostly work (it's probably more efficient too, since I believe LLVM can't optimise away the `memcpy` out of the `Vec` in all situations).

(NB. one can currently work-around this by `box`-ing everything, because the compiler-magic of the `Box` type means its destructor destroys things in-place.)

**Comment by steveklabnik** [comment]
@huonw is this issue RFC worthy? I'd think so.

**Comment by steveklabnik** [comment]
Oh, lol, you made one. Right above.

Closing in favor of that.

**Comment by huonw** [comment]
For a slightly different thing. :smile:
