### ISSUE TITLE
Rustdoc: re-exported ffi function metadata is not preserved.

### ISSUE THREAD

**Issue by FeGs** [rust-lang/rust#16289]
`std::mem::transmute` is re-exported function of `core::intrinsics::transmute`.
Hyperlink of `core::intrinsics::transmute` is ~/ffi.transmute.html, not ~/fn.transmute.html, but source link of http://doc.rust-lang.org/std/mem/fn.transmute.html is http://doc.rust-lang.org/core/intrinsics/fn.transmute.html instead of http://doc.rust-lang.org/core/intrinsics/ffi.transmute.html

**Comment by steveklabnik** [comment]
Triage: link is still pointing to the same place.

**Comment by alexcrichton** [comment]
Fixed in #20081
