### ISSUE TITLE
libc::execv incorrect definition

### ISSUE THREAD

**Issue by carllerche** [rust-lang/rust#16290]
It should be:

```
pub unsafe fn execv(prog: *const c_char, argv: *const *const c_char) -> c_int

**Comment by steveklabnik** [comment]
Today, this is 

```
                pub fn execv(prog: *const c_char,
                             argv: *mut *const c_char) -> intptr_t;
```

so it appears that it's still wrong.

**Comment by geofft** [comment]
PR #25641 should fix this. I didn't notice this issue at the time, but I reached the same conclusions about the _actual_ const guarantees (and C's legacy problems therewith).
