### ISSUE TITLE
Export fd_set in libc or libnative

### ISSUE THREAD

**Issue by VShell** [rust-lang/rust#16297]
At present, fd_set is defined as libnative::io::c::fd_set, on both Windows and Linux. However, I can't use this, as it's not made "pub mod c" in [mod.rs](https://github.com/rust-lang/rust/blob/8bb34a3146e6ba4bc7902a85de90cf4f8064ace0/src/libnative/io/mod.rs).

I'm writing a binding from a C network-related library (libircclient) to Rust, and would like fd_set to be available without having to duplicate effort.

**Comment by steveklabnik** [comment]
Lots of stuff has changed here, and we now have

```
src/libstd/sys/unix/c.rs:    pub struct fd_set {
```
