### ISSUE TITLE
sidebars for rust documentation pages should use semantic markup

### ISSUE THREAD

**Issue by froydnj** [rust-lang/rust#16310]
Looking at, for instance, `doc/std/io/index.html` after building, I see things like (newlines added for readability):

```html
<p class='location'><a href='../index.html'>std</a></p>
<div class='block mod'>
<h2>Modules</h2>
<a class='mod ' href='../any/index.html'>any</a>
<a class='mod ' href='../ascii/index.html'>ascii</a>
...
```

The `a` elements would be much better wrapped inside a list whose elements are marked `display-style: inline` or somesuch.  In textual browsers, the aforementioned bit of markup renders as:

```
anyasciibitflagsboolc_strc_veccellcharclonecmpcollectionscommdefaultdynamic_libf32f64finallyfmtfrom_strgchashi16i32i64i8intintrinsicsioiterkindslocal_datamacrosmemnumops
optionosownedpathpreludeptrrandrawrcresultrtsimdslicestrstringsynctaskto_strtupletyu16u32u64u8uintunstableve
```

which is rather unhelpful.

**Comment by jruderman** [comment]
In addition to affecting textual browsers, it affects Google search results. I got a preview with "anyarrayatomiccellcharclonecmpconvertdefaultf32f64fmthashi16i32i64i8"
