### ISSUE TITLE
Document any supported environment variables rustc honours

### ISSUE THREAD

**Issue by Earnestly** [rust-lang/rust#16330]
I was looking for a collection of environment variables that `rustc` honours but was unable to find a definitive list.  There are a few mentions of variables such as `RUSTFLAGS`, `RUST_THREADS` and `RUST_BACKTRACE` on google but none of them are documented in [rustc(1)](https://github.com/rust-lang/rust/blob/master/man/rustc.1)

Would it be possible to add these to the manual for future reference under an `ENVIRONMENT` section much like `clang` and `gcc`?

**Comment by galsondor** [comment]
FYI: Just added #22334 (Document RUST_TEST_TASKS in the "book") in response to spurious test failures due to parallel text execution.

**Comment by steveklabnik** [comment]
Full list as of now:

```
RUST_TEST_TASKS
RUST_TEST_NOCAPTURE
RUST_ERR
RUST_LOG
RUST_BUILD_STAGE
RUST_URL
RUST_PACKAGE_NAME
RUST_PACKAGE_NAME_AND_TRIPLE
RUST_TARBALL_NAME
RUST_LOCAL_INSTALL_DIR
RUST_LOCAL_INSTALL_SCRIPT
RUST_DOWNLOAD_DIR
RUST_LOCAL_TARBALL
RUST_PATH
RUST_REGION_GRAPH_NODE
RUST_REGION_GRAPH
RUST_TARGET_PATH
RUST_MIN_STACK
RUST_BACKTRACE
RUST_OBJECT
R_RUST_TEMP_FOLDER
RUST_THREADS
RUST_TEST_STRESS
RUST_ANDROID_DUMMY_H
RUST_BENCH
RUST_HOPEFULLY_THIS_DOESNT_EXIST
RUST_NEWRT
RUST_POISON_ON_FREE
RUST_TEST_PROC_SPAWN_UNICODE
```

**Comment by steveklabnik** [comment]
(I gusess some of these are not actually env vars)
