### ISSUE TITLE
rustdoc should support --target for doc tests

### ISSUE THREAD

**Issue by metajack** [rust-lang/rust#16357]
Currently there is no way to pass arbitrary compiler flags to rustdoc. This means that I can't use rustdoc to check cross compiled libraries. For example, checking `i686-unknown-linux-gnu` from `x86_64-unknown-linux-gnu` is impossible because I can't pass `--target` to rustdoc.

I've worked around this issue for now by disabling doctests in Servo, but that is not ideal.

**Comment by alexcrichton** [comment]
Closing as rustdoc does support `--target` for generation and also https://github.com/rust-lang/rust/issues/16357#issuecomment-51676427.
