### ISSUE TITLE
rustdoc prefers dynamic linking

### ISSUE THREAD

**Issue by metajack** [rust-lang/rust#16358]
rustdoc chooses to link dynamically if rlibs are available, which can sometimes cause problems. This seems bizarre since rustc has the opposite behavior.

**Comment by larsbergstrom** [comment]
@alexcrichton FYI, @mrobinson has been running into this and it's causing us to disable rustdoc on a bunch of our modules. Is there any ETA for a fix?

**Comment by alexcrichton** [comment]
Is there a more minimal reproduction for this issue other than "cargo doc in servo" ?

**Comment by steveklabnik** [comment]
Without a reproduction, we can't fix this. @metajack let us know if you have one!

**Comment by larsbergstrom** [comment]
I'm not aware of a more minimal repro than "cargo doc in servo."
