### ISSUE TITLE
Named labels in asm!() blocks cause crashes on Mac OSX

### ISSUE THREAD

**Issue by DaGenix** [rust-lang/rust#16378]
The following code crashes on Mac OSX:

``` rust
#![feature(asm)]

fn main() {
    unsafe {
        asm!(" test:") 
    }
}
```

**Comment by steveklabnik** [comment]
Triage: this ticket is quite old, but I don't have a mac to test to see if it reproduces today.

**Comment by mark-buer** [comment]
Just tested it (using latest nightly installed via rustup).
Running the compiled program (from original post) crashes with:
```
Segmentation fault: 11
```

**Comment by etaoins** [comment]
This still occurs with nightly. Interestingly, if the LLVM IR is compiled with an external `llc`/`opt` 5.0.1  it works fine:

```shell
> cat broken.rs
#![feature(asm)]

fn main() {
    unsafe {
        asm!(" test:")
    }
    println!("HERE")
}

> rustc broken.rs; and ./broken
fish: 'and ./broken' terminated by signal SIGSEGV (Address boundary error)

> opt -O2 broken.ll | llc -O2 -o broken.s; and clang build/x86_64-apple-darwin/stage2/lib/libstd-774948d0982f7640.dylib  broken.s  -o broken
> ./broken
HERE
```

**Comment by stevecheckoway** [comment]
I gave an explanation of what's happening https://github.com/rust-lang/rust/issues/63977#issuecomment-573353150

**Comment by Amanieu** [comment]
You should only use [local labels](https://sourceware.org/binutils/docs/as/Symbol-Names.html#Local-Labels) in inline assembly. This is stated in the documentation for the new `asm!` macro.
