### ISSUE TITLE
type_limits warning should fire for operators like (<=)

### ISSUE THREAD

**Issue by bfops** [rust-lang/rust#16389]
The following appropriately generates a type_limits warning:

    pub fn main() {
        let x: u64 = 0;
        println!("is {} negative? {}", x, (x < 0));
    }

The following does not:

    pub fn main() {
        let x: u64 = 0;
        println!("is {} nonpositive? {}", x, (x <= 0));
    }

**Comment by steveklabnik** [comment]
Triage: no change. I also don't think that this lint should happen; this expression is legitimate. Maybe in Clippy? @Manishearth

**Comment by Manishearth** [comment]
https://github.com/Manishearth/rust-clippy/pull/593

**Comment by Manishearth** [comment]
Just landed as https://github.com/Manishearth/rust-clippy/wiki#absurd_unsigned_comparisons
