### ISSUE TITLE
std::io::Command Type trait conversions fail when passed a value that is already of that type

### ISSUE THREAD

**Issue by kraemahz** [rust-lang/rust#16397]
When trying to pass already created c_strs to Command::args it creates awkard errors:

```
let stuff = ["a".to_c_str(), "b".to_c_str(), "c".to_c_str()];
let mut child = Command::new("/bin/cat");
for item in stuff.iter() {
    child = child.arg(*item);
}
```
```
src/run_cat.rs:8:17: 8:33 error: failed to find an implementation of trait rustrt::c_str::ToCStr for rustrt::c_str::CString
src/run_cat.rs:8         child = child.arg(*item);
```

I also noticed that http://doc.rust-lang.org/rustrt/c_str/ and http://doc.rust-lang.org/std/c_str/index.html both define c_str implementations. Which seem to be competing with each other.

This is on rustc 0.12.0-pre-nightly (a1429bca5 2014-08-08 21:36:11 +0000)

**Comment by steveklabnik** [comment]
I'm reading this ticket as "not a bug, but it would be nice to have this implementation."

Making a change on what implements what requires an RFC now, so if you'd like to persue that change, please open an issue there. Thanks!
