### ISSUE TITLE
Continuous documentation server for rust packages

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#1642]
Similar to #1453, we can use rustpkg + rustdoc to automatically generate all documentation for all rust libraries and display them on a website. This will require a somewhat-central registry of blessed-for-CI packages (as we're no longer operating on the assumption of a central package list for the tool)

**Comment by steveklabnik** [comment]
Triage bump: closing in favor of https://github.com/rust-lang/crates.io/issues/91
