### ISSUE TITLE
Test harness should not fail!() when some tests fail

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#16430]
`src/libtest/lib.rs` currently contains [`fail!("Some tests failed")`](https://github.com/rust-lang/rust/blob/6faad3ec3aba8e9ea7c68331b7c6561890929658/src/libtest/lib.rs#L242)

This causes the output to have an extraneous line when some tests fail:
```
task '<main>' failed at 'Some tests failed', rust/src/libtest/lib.rs:242
```

This is only mildly annoying, but it gets especially noisy when the `RUST_BACKTRACE` environment variable is used since it prints an additional (and uninteresting) stack trace.

The test harness should not use `fail!()` in this case, and find some other way to make the program’s exit code be non-zero.

**Comment by steveklabnik** [comment]
Is this a backcompat issue? I'm not sure. I don't think we're making any guarantees about test being stable, are we?

**Comment by SimonSapin** [comment]
I don’t think it is, unless we’re making stability promises about the exact output of the test harness.

**Comment by SimonSapin** [comment]
Or about the API of the test harness when used directly as a library (as opposed to `rustc --test`).

**Comment by steveklabnik** [comment]
Triage: not a lot has changed, but we do have custom panic handlers, so that should help?

**Comment by alexcrichton** [comment]
Ah this was actually done in https://github.com/rust-lang/rust/commit/bfc45834c110f7f021daffefcc2290c9133d6139, so closing.
