### ISSUE TITLE
Encourage fixed-size integer

### ISSUE THREAD

**Issue by l0kod** [rust-lang/rust#16446]
The #6023 force to use a type suffix for integers. As discussed in rust-lang/rfcs#115 and #9940, the `int` and `uint` should only be used for memory-related values (e.g. length).

The documentations mostly use `i` suffix examples. It should encourage the use of fixed-size integer (e.g. `u32`) for common uses.

A more strict rule could be to remove the `u` and `i` from allowed suffixes, but to rely on full explicit typing (e.g. `: int`) when really needed.
This could be annoying for `range`-like functions but it's not that burdensome to use the explicit generic typing (e.g. `range::<uint>(0, 5)`).

**Comment by l0kod** [comment]
Other `int`/`uint` bug:
* #20288

**Comment by l0kod** [comment]
cc rust-lang/rfcs#544

**Comment by l0kod** [comment]
Another related bug:
* AngryLawyer/rust-sdl2#200

**Comment by l0kod** [comment]
Related discussions:
* [Integer types](http://discuss.rust-lang.org/t/integer-types/470)
* [If `int` has the wrong size …?](http://discuss.rust-lang.org/t/if-int-has-the-wrong-size/454)
* [A tale of two’s complement](http://discuss.rust-lang.org/t/a-tale-of-twos-complement/1062)
* [Restarting the `int/uint` Discussion](http://discuss.rust-lang.org/t/restarting-the-int-uint-discussion/1131)
* [Call for consensus, if we do want rename `int/uint`internals bikeshed](http://discuss.rust-lang.org/t/call-for-consensus-if-we-do-want-rename-int-uint/1117)

**Comment by l0kod** [comment]
Integer overflow bug:
* #17795

**Comment by huonw** [comment]
@l0kod #17795 doesn't seem to be caused by the names/sizes/conventions of integers in  Rust. At some point in the past `libc::c_uint` was precisely correct (LLVM used `unsigned int`) but then LLVM was changed to use `unsigned long long` without us realising, causing the FFI declaration to become incorrect.

**Comment by steveklabnik** [comment]
We've gone through and made a lot of changes related to this, and so I'm gonna give it a close. If we find anything else, it should also be fixed.
