### ISSUE TITLE
rustup.sh and underlying binaries authentication

### ISSUE THREAD

**Issue by l0kod** [rust-lang/rust#16442]
After the #16123, a second step should be to sign all files needed for the installation. Each Rust versions are signed in the git repository. Great! If the "rustup.sh" is included in the git repository, it will be possible to anyone to verify the script (from a git tag) before executing it.

Maybe all (including nightly) underlying binaries hashes should "inherit" from the signature like with the "snapshots.txt" hashes? The main Rust repository or a dedicated one could aggregate all hashes.

So, the guide could be improved by replacing the "curl" instruction with a "git clone + verify-tag". This add some extra MB to the download but worth it for more security to users who care.

**Comment by l0kod** [comment]
cc rust-lang/crates.io#75

**Comment by steveklabnik** [comment]
Triage: no changes I'm aware of.

**Comment by brson** [comment]
cc https://github.com/rust-lang-nursery/rustup.rs/issues/241
cc https://github.com/rust-lang-nursery/rustup.rs/issues/242

**Comment by brson** [comment]
Closing this since the specifics are pretty out of date.
