### ISSUE TITLE
lint for unused lvalue statement

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#16502]
``` rust
fn main() {
    let p = box 1i;

    let _ = p; // doesn't move
    p; // does move


    p; // error: use of moved value
}
```

```
<anon>:8:5: 8:6 error: use of moved value: `p`
<anon>:8     p;
             ^
<anon>:5:5: 5:6 note: `p` moved here because it has type `&mut int`, which is non-copyable (perhaps you meant to use clone()?)
<anon>:5     p; // does move
             ^
```

(Adapted from [this question](http://stackoverflow.com/q/25313583/1256624), using `Box` to avoid possible confusion from reborrowing of `&mut`.)

It seems strange that an unassigned useless path differs to a useless path assigned to `_`.

cc @nikomatsakis

**Comment by steveklabnik** [comment]
This is still true (and I agree, odd) today.

**Comment by steveklabnik** [comment]
Updated code:

```
#![feature(box_syntax)]

fn main() {
    let p = box 1;

    let _ = p; // doesn't move
    p; // does move


    p; // error: use of moved value
}
```

Still agree that this is pretty strange.

**Comment by nikomatsakis** [comment]
I guess this is odd. Seems like something we could address in MIR land.

**Comment by nikomatsakis** [comment]
I wonder though -- it'd be a breaking change, e.g. if `p` had a destructor.

**Comment by arielb1** [comment]
Of course, the root cause here is that `StmtSemi` evaluates its expression to an rvalue and then drops it immediately, while `match` evaluates its expression to some odd mix of lvalue and rvalue.

Having `StmtSemi` evaluate its expression to an lvalue would e.g. mean that
```Rust
    ptr::read(some_raw_ptr);
```
drops its argument at the end of the block rather than immediately, which would be a nontrivial breaking change.

**Comment by pnkfelix** [comment]
cc me

**Comment by Mark-Simulacrum** [comment]
Based on discussion above, this is a breaking change, so should be tagged with rust-2-breakage-wishlist, correct?

**Comment by nikomatsakis** [comment]
Personally I'm inclined to leave it as is and not change it.

**Comment by Mark-Simulacrum** [comment]
Nominating for lang team discussion -- I believe we should leave this as is and close.

**Comment by joshtriplett** [comment]
I think it'd be worth adding a lint for this specific case. If you have an expression statement that's a simple path, you can either eliminate it or replace it with a call to `drop`, depending on what you want.

**Comment by nikomatsakis** [comment]
General consensus: 

- we will not change the dynamic semantics here.
- seems like a very easy thing to lint for and to suggest invoking `mem::drop`, as @joshtriplett said.

**Comment by nikomatsakis** [comment]
triage: P-low

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by tmiasko** [comment]
This is covered by `path_statements` lint, together with suggestion to use `drop` when appropriate:

```rust
fn main() {
    let i = 0;
    let p = Box::new(1);
    p;
    i;
}
```

```console
warning: path statement drops value
 --> a.rs:4:5
  |
4 |     p;
  |     ^^ help: use `drop` to clarify the intent: `drop(p);`
  |
  = note: `#[warn(path_statements)]` on by default

warning: path statement with no effect
 --> a.rs:5:5
  |
5 |     i;
  |     ^^

warning: 2 warnings emitted
```
