### ISSUE TITLE
Better error message for macros with pipes as delimiters, or remove pipes as a macro delimeter

### ISSUE THREAD

**Issue by gsingh93** [rust-lang/rust#16501]
The following Rust code gives a very unclear error:

```
#![feature(macro_rules)]

macro_rules! foo (
    ($a:expr | $b:expr) => (
        $a * $b;
    );
)

fn main() {
    foo!(2u | 3);
}
```

The error is:
```
<anon>:10:15: 10:16 error: unexpected end of macro invocation
<anon>:10     foo!(2u | 3);
```

The issue is that the pipe operator is being parsed as bitwise or before a macro delimiter. I think this is a common error people could run into, and when I ran into it, it took me a while to figure out. I think there should be a better error message, or a more radical alternative is to disallow pipes to be a delimiter in macros (it's confusing for pipes to work as delimiters for only some macros). 

I'm also not sure if there's a better way to write `foo!(2u | 3)` to get the parsing to not think of the pipe as a bitwise or. If so, I'd like to know.

**Comment by steveklabnik** [comment]
Macros have undergone stabilization, so they'll need an RFC to change. If you're interested in making this happen, please open an issue on the RFC repo!

**Comment by gsingh93** [comment]
The error now looks like this:
```
test.rs:2:6: 2:13 error: `$a:expr` is followed by `|`, which is not allowed for `expr` fragments
test.rs:2     ($a:expr | $b:expr) => (
               ^~~~~~~
test.rs:8:15: 8:16 error: unexpected end of macro invocation
test.rs:8     foo!(2u | 3);
```
Which is much more clear, so this is solved anyway.
