### ISSUE TITLE
IoError is kind of archaic

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#16524]
The documentation for IoError [still says](http://doc.rust-lang.org/std/io/struct.IoError.html) `# FIXME Is something like this sufficient? It's kind of archaic`.

This is an issue to track this untagged FIXME. It should be addressed or the documentation should be updated -- I'm reporting this due to a user question about IoError on IRC.

**Comment by alexcrichton** [comment]
This is quite an old issue and `io::Error` is now stable, so closing
