### ISSUE TITLE
Rust doc's question mark shortcut does not work well with all keyboard layouts.

### ISSUE THREAD

**Issue by SBSTP** [rust-lang/rust#16572]
My keyboard layout is french canadian and the question mark shortcut does not work properly. It seems that [this](https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/static/main.js#L77) line is causing the issue. To make a question mark, I use `SHIFT+6`, so it doesn't fire one event with a `which`of 191, but two events, one with 54 (6) and one with 16 (SHIFT).

**Comment by azerupi** [comment]
I made a pull request for this #26675 there is a more recent duplicate issue #26016.
