### ISSUE TITLE
Rename SocketAddr to InetAddr

### ISSUE THREAD

**Issue by carllerche** [rust-lang/rust#16595]
SocketAddr should be an enum of all possible addresses that can be used for sockets, including unix domain sockets and any other socket flavors. What is currently named SocketAddr is really an InetAddr.

**Comment by frewsxcv** [comment]
Triage: This sounds very reasonable. I haven't been following the IO reform stuff too closely, but as far as I know, the [io::net](https://github.com/rust-lang/rfcs/blob/efb783a79c9987e678ed8e8e5ca9db0de70f512c/text/0517-io-os-reform.md#stdnet) submodule has yet to be proposed

**Comment by frewsxcv** [comment]
Relevant RFC PR: https://github.com/rust-lang/rfcs/pull/807/files

**Comment by aturon** [comment]
Hm, unfortunately this wasn't taken into account with IO reform, and seems to still be an issue. The renaming makes sense to me. Thoughts, @alexcrichton?

**Comment by aturon** [comment]
Nominating for 1.0-beta P-backcompat-libs.

**Comment by alexcrichton** [comment]
We may wish to reconsider the `socket_addr` method names on each of the socket types as well, but this renaming is fine by me.

**Comment by pnkfelix** [comment]
P-backcompat-libs, 1.0 beta

**Comment by carllerche** [comment]
I submitted an RFC PR for this change: https://github.com/rust-lang/rfcs/pull/923

**Comment by nikomatsakis** [comment]
I'm assigning this to @alexcrichton (trying to reduce the number of milestone issues with no assignee).

**Comment by alexcrichton** [comment]
Decided in https://github.com/rust-lang/rfcs/pull/923
