### ISSUE TITLE
use high entropy ASLR on 64-bit Windows

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#16593]
MinGW-w64 doesn't expose the necessary flag yet, so I'll look into adding it to their linker. It should be as easy as adding support for an extra flag there and then passing the switch from the Rust compiler.

**Comment by steveklabnik** [comment]
closing in favor of https://github.com/rust-lang/rust/issues/16514

**Comment by thestinger** [comment]
This is a separate issue from #16514.

**Comment by steveklabnik** [comment]
Triage: not sure if anything has changed here, but I don't think so.

**Comment by steveklabnik** [comment]
Triage: same as in 2016
