### ISSUE TITLE
Compile time lowercasing/etc of stringify!d idents.

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#16607]
In [this macro](https://github.com/Manishearth/servo/commit/993f411657f660e5043714b9d279dde56528db11#diff-05d7cef08c94f7613fbd86e03a101a81R28) for Servo ([PR](https://github.com/servo/servo/pull/3073)), I'm taking in an ident, using it as a method name, and later `stringify!`ing it. Unfortunately, the method name needs to be title case, but the string version needs to be lowercase. I currently get around this by using `stringify!($attr).to_ascii_lower().as_slice()` but this executes at runtime which is slightly inefficient.

Could we have variants of `stringify!` that work at compile time?

**Comment by steveklabnik** [comment]
Adding macros would require an RFC nowadays, so I'm giving this a close.

**Comment by kmcallister** [comment]
Yeah, I think this could be a plugin library.
