### ISSUE TITLE
.to_uint() and .to_int() should return None on NaN

### ISSUE THREAD

**Issue by opp11** [rust-lang/rust#16613]
Calling `.to_uint()` or `.to_int()` on an `f64` or `f32` will always return a Some value, even if they are called with NaN ([playpen link](http://is.gd/bwnPfy)):
```
   let f: f64 = Float::nan();
   let res = f.to_uint(); // <-- will be Some(0)
```
As far as I can tell this this behavior comes from the fact that `.to_int()` and `.to_uint()` is just implemented as casts [as seen here](https://github.com/rust-lang/rust/blob/d16a5cd7c4d37c947faf4661b22e994409197809/src/libcore/num/mod.rs#L935):

    fn to_int(&self) -> Option<int> { Some(*self as int) }
    ...
    fn to_uint(&self) -> Option<uint> { Some(*self as uint) }
This seems (to me at least) a bit unintuitive since you would expect the method to return None when called with invalid input - such as NaN which has no obvious conversion to a `u/int` - since the method returns an Option.

Alternatively it would nice if it was mentioned in the docs, that the methods are the same as a cast for primitive types.

EDIT:
It seems like something similar happens for [infinity](http://is.gd/SHmwss).

EDIT 2:
Updated the playpen links - thank you frewsxcv!

**Comment by frewsxcv** [comment]
This is still an issue. [I updated the playpen to compile with the latest rust](http://is.gd/bwnPfy)

**Comment by aturon** [comment]
@bjz @nikomatsakis any thoughts here?

**Comment by bjz** [comment]
I don't know. I would tend towards saying that we should let the user handle the NaN. Adding in a conditional may prevent llvm from optimizing out those annoying `unwraps` we always have to do when working with generic numbers.

In more general terms, I would love some way of generically exposing the raw `as` behavior - the `Option` return value gets really annoying some times, to the point that we [wrap it in noise-rs](https://github.com/bjz/noise-rs/blob/master/src/math.rs#L22-L26). But that's kind of separate to this issue.

**Comment by Gankro** [comment]
Should we have a suite of casts for different usecases?

**Comment by aturon** [comment]
Nominating for 1.0-beta P-backcompat-libs.

**Comment by pnkfelix** [comment]
1.0-beta, P-backcompat-libs.

**Comment by brson** [comment]
Do as the title says. Easy.

**Comment by bjz** [comment]
@brson Is this an endorsement of the change?

**Comment by aturon** [comment]
Note: we do not plan to stabilize the `ToPrimitive`/`FromPrimitive` traits (we plan to deprecate them), so this issue is likely moot for those existing methods.

triage: P-low ()

**Comment by huonw** [comment]
> we plan to deprecate them

This has happened, and the traits have now been entirely removed too. Closing.
