### ISSUE TITLE
Improve --dep-info to include crate dependencies

### ISSUE THREAD

**Issue by serpent** [rust-lang/rust#16638]
The --dep-info flag to rustc only prints out the source file(s) that make up the output crate. It does not print out any libraries though.

For an example file "a.rs" compiled into a binary crate "a", if "a.rs" has "extern crate b" and rustc statically links in "libb.rlib", I would expect dependency info to include the fact as "a: libb.rlib", so that whenever libb.rlib changes, a.rs is recompiled into a. Similarly for other crate types.

If --dep-info can not be modified, perhaps --full-dep-info will be considered.

**Comment by steveklabnik** [comment]
Triage: `--dep-info` doesn't seem to be a flag anymore, there is `--emit=dep-info`, but it doesn't print things out to stdout though.

**Comment by steveklabnik** [comment]
Triage: with no comments since this was filed, I don't think that this issue is relevant anymore. If you still want this, please open a new issue with details that are relevant to today's Rust. Thanks!
