### ISSUE TITLE
Manual: Language items are missing definitions

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#16644]
Some items at the following links are missing definitions (look for ***Needs filling in***) and they should be added:
- [ ] [Operators](http://doc.rust-lang.org/reference.html#operators)
- [ ] [Marker types](http://doc.rust-lang.org/reference.html#marker-types)

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/21535 fixed this.
