### ISSUE TITLE
Windows build instructions are inconsistent

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#16654]
There are multiple instructions for building on Windows, and they are not in agreement, as described here: http://www.reddit.com/r/rust/comments/2e62f6/compiling_rust_on_windows_aka_why_does_this_have/

**Comment by steveklabnik** [comment]
Triage:

```
20:50 < WindowsBunny> steveklabnik: We 
                      don't mention how to 
                      setup 64-bit msys2
20:50 < WindowsBunny> steveklabnik: We need 
                      to mention 
                      mingw64_shell and the 
                      x86_64 toolchain

20:51 < WindowsBunny> steveklabnik: As well 
                      as pointing out that 
                      whether you install 
                      the 32-bit or 64-bit 
                      msys2 you'll have 
                      access to both 
                      toolchains (unless 
                      your computer only 
                      allows 32-bit)

```

**Comment by klutzy** [comment]
MSYS2 still provides [posix-threaded gcc](https://github.com/rust-lang/rust/issues/16654#issuecomment-53286215). Currently `README.md` suggests to install it (`pacman -S mingw-w64-i686-toolchain`) but we have to recommend [manual mingw-w64 installation](https://github.com/rust-lang/rust/issues/16654#issuecomment-53352409).

**Comment by klutzy** [comment]
(Or if there's no performance issue it would be fine? It only affects if you link to libstdc++.)

**Comment by steveklabnik** [comment]
This contains a whole ton of stuff that I think is all addressed today. If there are more things we should update with regards to Windows build instructions, please open new issues with specifics, thank you.
