### ISSUE TITLE
Add WouldBlock error kind to IoError

### ISSUE THREAD

**Issue by carllerche** [rust-lang/rust#16666]
I'm working on a non-blocking IO lib for rust. It would be very helpful to have an error kind that clearly indicates the retry semantics of non-blocking IO.

I believe that currently EAGAIN and EWOULDBLOCK are mapped to ResourceUnavailable but that does not clearly indicate the would block / retry semantics.

**Comment by steveklabnik** [comment]
Adding stuff to the standard lib requires an RFC these days, if you still care about this, you should make sure the IO RFC takes care of it.

**Comment by steveklabnik** [comment]
nominating for backcompat-libs like all the othe rones

**Comment by aturon** [comment]
This currently maps to a `ResourceUnavailable` error (same as `EINTR` when it isn't retried internally).

**Comment by pnkfelix** [comment]
P-backcompat-libs, 1.0 beta, I-needs-decision
