### ISSUE TITLE
Adding a line break after a Trait in a template argument list breaks emacs-mode indentation

### ISSUE THREAD

**Issue by gsingh93** [rust-lang/rust#16665]
I think this is a somewhat serious bug with emacs-mode, since I can't use the tab key for indentation inside a function block in many cases.

My code ends up with a long list of traits with bounds in the template argument list, and according to the [style guide](https://aturon.github.io/style/whitespace.html#line-wrapping), I can wrap between traits. However, if I wrap between traits, identation is broken for the function. Consider the following example,
```
pub fn foo<T,
           V>() {
              // Indentation puts me here
}
```
As you can see, hitting tab inside the function idents too much. I should mention that I aligned the second template argument to match up with the first, as hitting tab there doesn't work either.

**Comment by steveklabnik** [comment]
Does this still happen today?

**Comment by gsingh93** [comment]
Indentation now looks like this:
```
pub fn foo<T,
V>() {
    // Indentation puts me here
}
```

**Comment by pnkfelix** [comment]
part of #8793

**Comment by steveklabnik** [comment]
Moved to rust-lang/rust-mode#10
