### ISSUE TITLE
Audit reference manual before 1.0

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#16676]
Shortly before 1.0 we should give some attention to the manual and make sure it's not too inaccurate nor incomplete.

----

Let's crowdsource this edit! Please check one of these sections, and leave a comment below if you've verified that it's accurate or have sent a PR fixing part:

- [x] 1 Introduction
- [x] 2 Notation
- [x] 2.1 Unicode productions
- [x] 2.2 String table productions
- [x] 3 Lexical structure
- [x] 3.1 Input format
- [x] 3.2 Special Unicode Productions
- [x] 3.2.1 Identifiers
- [x] 3.2.2 Delimiter-restricted productions
- [x] 3.3 Comments
- [x] 3.4 Whitespace
- [x] 3.5 Tokens
- [x] 3.5.1 Keywords
- [x] 3.5.2 Literals
- [x]             3.5.2.1 Examples
- [x]                 3.5.2.1.1 Characters and strings
- [x]                 3.5.2.1.2 Byte escapes
- [x]                3.5.2.1.3 Unicode escapes
- [x]                3.5.2.1.4 Numbers
- [x]                3.5.2.1.5 Suffixes
- [x]            3.5.2.2 Character and string literals
- [x]                3.5.2.2.1 Character literals
- [x]                3.5.2.2.2 String literals
- [x]                3.5.2.2.3 Character escapes
- [x]                3.5.2.2.4 Raw string literals
- [x]            3.5.2.3 Byte and byte string literals
- [x]                3.5.2.3.1 Byte literals
- [x]                3.5.2.3.2 Byte string literals
- [x]                3.5.2.3.3 Raw byte string literals
- [x]            3.5.2.4 Number literals
- [x]                3.5.2.4.1 Integer literals
- [x]                3.5.2.4.2 Floating-point literals
- [x]            3.5.2.5 Boolean literals
- [ ]        3.5.3 Symbols
- [x]    3.6 Paths
- [ ] 4 Syntax extensions
- [ ]    4.1 Macros
- [ ]        4.1.1 Macro By Example
- [ ]        4.1.2 Parsing limitations
- [x] 5 Crates and source files
- [x] 6 Items and attributes
- [x]    6.1 Items
- [x]        6.1.1 Type Parameters
- [ ]        6.1.2 Modules
- [x]            6.1.2.0.1 Extern crate declarations
- [x]            6.1.2.0.2 Use declarations
- [ ]        6.1.3 Functions
- [ ]            6.1.3.1 Generic functions
- [ ]            6.1.3.2 Unsafety
- [ ]                6.1.3.2.1 Unsafe functions
- [ ]                6.1.3.2.2 Unsafe blocks
- [ ]                6.1.3.2.3 Behavior considered undefined
- [ ]                6.1.3.2.4 Behaviour not considered unsafe
- [ ]            6.1.3.3 Diverging functions
- [ ]            6.1.3.4 Extern functions
- [x]        6.1.4 Type aliases
- [ ]        6.1.5 Structures
- [ ]        6.1.6 Enumerations
- [ ]        6.1.7 Constant items
- [ ]        6.1.8 Static items
- [ ]            6.1.8.1 Mutable statics
- [x]        6.1.9 Traits
- [ ]        6.1.10 Implementations
- [ ]        6.1.11 External blocks
- [ ]    6.2 Visibility and Privacy
- [ ]        6.2.1 Re-exporting and Visibility
- [ ]    6.3 Attributes
- [ ]        6.3.1 Crate-only attributes
- [ ]        6.3.2 Module-only attributes
- [ ]        6.3.3 Function-only attributes
- [ ]        6.3.4 Static-only attributes
- [ ]        6.3.5 FFI attributes
- [ ]        6.3.6 Macro-related attributes
- [ ]        6.3.7 Miscellaneous attributes
- [ ]        6.3.8 Conditional compilation
- [ ]       6.3.9 Lint check attributes
- [ ]       6.3.10 Language items
- [ ]        6.3.11 Inline attributes
- [ ]        6.3.12 derive
- [ ]        6.3.13 Compiler Features
- [ ] 7 Statements and expressions
- [ ]    7.1 Statements
- [ ]        7.1.1 Declaration statements
- [ ]            7.1.1.1 Item declarations
- [ ]            7.1.1.2 Variable declarations
- [ ]        7.1.2 Expression statements
- [ ]    7.2 Expressions
- [ ]        7.2.0.1 Lvalues, rvalues and temporaries
- [ ]        7.2.0.2 Moved and copied types
- [ ]        7.2.1 Literal expressions
- [ ]       7.2.2 Path expressions
- [ ]        7.2.3 Tuple expressions
- [ ]        7.2.4 Unit expressions
- [ ]        7.2.5 Structure expressions
- [ ]        7.2.6 Block expressions
- [ ]        7.2.7 Method-call expressions
- [ ]        7.2.8 Field expressions
- [ ]        7.2.9 Array expressions
- [ ]        7.2.10 Index expressions
- [ ]        7.2.11 Unary operator expressions
- [ ]        7.2.12 Binary operator expressions
- [ ]            7.2.12.1 Arithmetic operators
- [ ]            7.2.12.2 Bitwise operators
- [ ]            7.2.12.3 Lazy boolean operators
- [ ]            7.2.12.4 Comparison operators
- [ ]            7.2.12.5 Type cast expressions
- [ ]            7.2.12.6 Assignment expressions
- [ ]            7.2.12.7 Compound assignment expressions
- [ ]            7.2.12.8 Operator precedence
- [ ]        7.2.13 Grouped expressions
- [ ]        7.2.14 Call expressions
- [ ]        7.2.15 Lambda expressions
- [ ]        7.2.16 While loops
- [ ]        7.2.17 Infinite loops
- [ ]        7.2.18 Break expressions
- [ ]        7.2.19 Continue expressions
- [x]        7.2.20 For expressions
- [ ]        7.2.21 If expressions
- [ ]        7.2.22 Match expressions
- [ ]        7.2.23 If let expressions
- [ ]        7.2.24 While let loops
- [ ]        7.2.25 Return expressions
- [ ] 8 Type system
- [x]    8.1 Types
- [x]        8.1.1 Primitive types
- [x]            8.1.1.1 Machine types
- [x]            8.1.1.2 Machine-dependent integer types
- [x]        8.1.2 Textual types
- [x]        8.1.3 Tuple types
- [x]        8.1.4 Array, and Slice types
- [x]        8.1.5 Structure types
- [x]        8.1.6 Enumerated types
- [x]        8.1.7 Recursive types
- [x]        8.1.8 Pointer types
- [x]        8.1.9 Function types
- [x]        8.1.10 Closure types
- [x]        8.1.11 Object types
- [x]        8.1.12 Type parameters
- [x]        8.1.13 Self types
- [ ]  9 Special traits
- [ ]    9.1 The Copy trait
- [ ]    9.2 The Sized trait
- [ ]    9.3 The Drop trait
- [ ] 10 Memory model
- [ ]    10.0.1 Memory allocation and lifetime
- [ ]    10.0.2 Memory ownership
- [ ]    10.0.3 Variables
- [ ] 11 Linkage
- [ ] 12 Appendix: Rationales and design tradeoffs
- [ ] 13 Appendix: Influences

**Comment by aturon** [comment]
Re-nominating. Should this be on the beta milestone?

**Comment by pnkfelix** [comment]
leaving on the 1.0 milestone; this is considered polish, *after* we've finished all the backwards incompat stuff.

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/24721

**Comment by rkruppe** [comment]
Audited section 5, Crates and source files. Filed PR #24727 to fix it.

**Comment by bluss** [comment]
I'm reading 8.1, the types chapter.

**Comment by joliv** [comment]
Audited 7.2.4 (Unit expressions) and filed #24738

**Comment by mbrubeck** [comment]
Audited 3.3 (Comments).  Filed #24740 for a small clarification.  Aside from that it looks good, although I think the EBNF is a little sketchy.  (`character` is not defined anywhere, for example, and I think perhaps it needs the restriction that it can't include `*/`?)

**Comment by mbrubeck** [comment]
Audited 3.5.1 (Keywords). Filed #24742 to add two missing keywords.

**Comment by joliv** [comment]
6.1.4 (Type Aliases) looks good to me.

**Comment by tynopex** [comment]
#24753 - describe Range expressions

**Comment by jackm321** [comment]
If the unit type is no longer present, will unit-like structs be renamed to something else?

**Comment by SkylerLipthay** [comment]
Good:
* 3.5.2.1.1
* 3.5.2.1.2
* 3.5.2.1.3
* 3.5.2.1.4

Bad:
* 3.5.2.1.5

3.5.2.1 is all good once #24769 is accepted.

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/24744

**Comment by mbrubeck** [comment]
#24775 (updates to 7.2.20 and a formatting tweak to 6.3.13)

**Comment by mbrubeck** [comment]
8.1.11 (Object types) should probably mention object safety. Filed issue #24800.

**Comment by SkylerLipthay** [comment]
Good:
* 3.5.2.2 (Character and string literals)
* 3.5.2.2.1 (Character literals)
* 3.5.2.2.2 (String literals)
* 3.5.2.2.3 (Character escapes)
* 3.5.2.3.2 (Byte string literals)
* 3.5.2.3.3 (Raw byte string literals)
* 3.5.2.4 (Number literals)
* 3.5.2.4.1 (Integer literals)
* 3.5.2.4.2 (Floating-point literals)

Bad:
* 3.5.2.3.1 (Byte literals) — #24803

**Comment by rkruppe** [comment]
Good:

- 1 Introduction
- 2 Notation
- 2.1 Unicode productions
- 2.2 String table productions

Fixed in #24811:

- 3.2 Special Unicode Productions
- 3.2.1 Identifiers
- 3.2.2 Delimiter-restricted productions

**Comment by mdinger** [comment]
Note: the grammar has been removed from the reference https://github.com/rust-lang/rust/pull/24729 so related fixes should be targeted at the [grammar](https://github.com/rust-lang/rust/blob/master/src/doc/grammar.md) and not the reference. This does include the keyword table and the EBNF grammar.

**Comment by rkruppe** [comment]
@mdinger So should grammar-related prose also be removed? For example, 3.2 Special Unicode Productions does contain important information, but most of it defines productions (just not in EBNF).

**Comment by mdinger** [comment]
@rkruppe I don't know what else should move but it should definitely be decided. @steveklabnik should know or be able to direct to someone who does.

**Comment by steveklabnik** [comment]
I would think it should be moved, yeah.

**Comment by rkruppe** [comment]
Gotcha, filed PR #24825

For the task list, nothing changes. The sub-sections of 3.2 are gone and the name of 3.2 changed (to "Identifiers"), but that counts as "audited and fixed", right? ;-) Luckily the numbering of the following sections is not affected.

**Comment by rkruppe** [comment]
Files PR ... for

- 3.3 Comments
- 3.4 Whitespace

Also to be checked off:

- 3.5 Tokens (Only the introduction, not the many many subsections)
- 3.5.1 Keywords (removed by @mdinger in #24729)
- 3.5.2 Literals
- 3.5.2.1 Examples (Has no content of its own, and @SkylerLipthay took care of all subsections)

**Comment by dhardy** [comment]
Checked 3.5.2.2*; one pull request: https://github.com/rust-lang/rust/pull/24863

**Comment by carols10cents** [comment]
I audited " 6.1.2.0.1 Extern crate declarations" and made a small correction to it in #25231, it should be good now.

**Comment by badboy** [comment]
3.6 Paths: all fine ✓

**Comment by badboy** [comment]
I read:

 4 Syntax extensions
 4.1 Macros
 4.1.1 Macro By Example
 4.1.2 Parsing limitations

> …, so `( $( $i:ident ),* ; $( $j:ident ),* ) => ( $( ($i,$j) ),* )` is valid if given the argument `(a,b,c ; d,e,f)`, but not `(a,b,c ; d,e)`. The repetition walks through the choices at that layer in lockstep, so the former input transcribes to `( (a,d), (b,e), (c,f) )`.

Directly used as this in a macro fails, because it's not actually `( (a,d), (b,e), (c,f) )`, but missing the outer parentheses (http://is.gd/D09NUj).
Adding another pair works: http://is.gd/1RO4Mq
If I'm right a pair of parentheses (or curly braces) are used to seperate the block of code, but this is not mentioned in the text at all. Should it be thus added and the example adjused?

**Comment by steveklabnik** [comment]
Thanks @badboy !

I believe you are right, would you mind sending a PR?

**Comment by badboy** [comment]
Will do

**Comment by johannhof** [comment]
@steveklabnik read through some of chapter 7, wouldn't want to greenlight it yet but found what I think is a small issue and made a pr: https://github.com/rust-lang/rust/pull/25286

**Comment by bluss** [comment]
Audited as ok (will edit this comment further today):

- 3.3 Comments
- 3.4 Whitespace
- 3.5
- 3.5.1 Keywords
- 3.5.2
- 3.5.2.2 Character and string literals
- 3.5.2.2.1

**Comment by dhardy** [comment]
Since #24863 was merged, all of 3.5.2 can be marked as done (sorry bluss for letting you repeat work)

**Comment by bluss** [comment]
Well since I read the fixed version it was easy :)

**Comment by nham** [comment]
I read 6.1.9 (and part of 8.1.11) and submitted a PR: #25308

**Comment by steveklabnik** [comment]
I'm considering this closed, as both @nikomatsakis and I did a full read-over, and the community chipped in a ton as well.

Future improvements to the reference are always welcome, of course.
