### ISSUE TITLE
Add release channel automation

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#16677]
Before 1.0 we want to change the release process to have multiple parallel release channels ('nightly', 'beta', 'stable', probably). This will require a bunch of new automation.

**Comment by brson** [comment]
The automation for distribution is done, but for integration is not.

**Comment by aturon** [comment]
Nominating for beta milestone.

**Comment by pnkfelix** [comment]
assigning 1.0-beta.  (We could struggle on without it, but it makes more sense to get it deployed by that time).

**Comment by brson** [comment]
Lot's of work on this is finished. Remaining tasks are https://github.com/rust-lang/rust/issues/23756 and https://github.com/rust-lang/rust/issues/21149.

**Comment by pnkfelix** [comment]
Closing this task and letting the remaining two bugs serve as the, well, remaining work.
