### ISSUE TITLE
Develop standard training material

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#16679]
For spreading the gospel it would be nice to have a standard set of training material so that everybody who wants to teach Rust doesn't need to start from scratch. It should be based on the guide.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#778
