### ISSUE TITLE
Adding #[cfg(test)] to a macro breaks non-testing builds

### ISSUE THREAD

**Issue by gsingh93** [rust-lang/rust#16688]
The following code works when I run `rustc test.rs --test`, but fails when I run `rustc test.rs`, even though the macro is only used in a testing function.

```
#[cfg(test)]
macro_rules! foo {
    () => ({});
}

#[test]
fn test() {
    foo!();
}
```

Here is the error:

```
foo.rs:8:5: 8:8 error: macro undefined: 'foo!'
foo.rs:8     foo!();
             ^~~
error: aborting due to previous error
```

**Comment by steveklabnik** [comment]
triage: still an issue

**Comment by kmcallister** [comment]
Updated code and error.

> `#[test]` functions aren't stripped in non-test builds until after expansion

Is there a reason it's done this way? Can the cfg stripper treat `#[test]` as implying `#[cfg(test)]`, so we remove it in the cfg 1 phase?

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by Mark-Simulacrum** [comment]
The original code now compiles successfully, closing.
