### ISSUE TITLE
Inconsistent type names

### ISSUE THREAD

**Issue by sulnedinfind** [rust-lang/rust#16695]
Most of the types have CamelCase names, but not the primitive ones.
Primitive types in terms of their contracts are no different than others, but `str` is different than other primitive types.
That is inconsistent and somewhat confusing, especially when you happen to use `str::str` or `u64::u64`.
Probably, unnecessary legacy.

**Comment by steveklabnik** [comment]
Changing type names requires an RFC, but I believe this is also intentional, to differentiate built-in types from library types.

At this point in time, I don't see this changing, so I'm giving it a close. Please persue an RFC if you still feel strongly about this.
