### ISSUE TITLE
Dead code in Bitv undetected by Lint

### ISSUE THREAD

**Issue by Gankro** [rust-lang/rust#16737]
The two structs and enum found [here](http://doc.rust-lang.org/src/collections/home/rustbuild/src/rust-buildbot/slave/nightly-linux/build/src/libcollections/bitv.rs.html#98-110) appear to be private to the module, and yet are never referenced anywhere in the module.

Yet, rust builds without a complaint.

**Comment by sanxiyn** [comment]
Is this still a problem? Deriving `Clone` doesn't count as a use since #25961.

**Comment by Gankro** [comment]
SGTM
