### ISSUE TITLE
Add form feed and vertical tab escape sequence

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#16744]
For some reason '\v' and '\f' don't work.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#751
