### ISSUE TITLE
`std::num::pow`: exponent should not be a `uint`

### ISSUE THREAD

**Issue by vks** [rust-lang/rust#16755]
Right now `pow` has the following signature:

```rust
pub fn pow<T: One + Mul<T, T>>(base: T, exp: uint) -> T
```

It does not really make sense that the exponent is a pointer-sized `uint`. This makes this function unnecessarily platform-dependent.
Also, it is awkward to use with `BigInt` as an exponent. (This mainly an ergonomic issue, as a `uint` should be large enough to store any reasonable exponent.)

I think it would be better to have a signature like

```rust
pub fn pow<T: One + Mul<T, T>, U: One + Zero + Add<U, U> + Div<U,U>>(base: T, exp: U) -> T
```

(Note that `pow` currently uses some bitwise operations for efficiency, the proposed type constraints do not reflect that.)

Alternatively, to keep it simple the exponent could just be a constant-size unsigned integer (`u32` should be sufficient [1]).

[1] pow(1.1, pow(2, 32)) ~= pow(10, 177780229)

**Comment by gsingh93** [comment]
This is a valid issue that I want fixed, but it's in the wrong repo now. Could someone moves this over to https://github.com/rust-lang/num?
