### ISSUE TITLE
CString behaves strangely with regard to *const and *mut

### ISSUE THREAD

**Issue by wycats** [rust-lang/rust#16772]
In the current API, `CString::new` takes a `*const i8`, but it has a method `as_mut_ptr` which returns a `*mut i8`.

The `as_mut_ptr` method seems to violate the invariant that the `new` method is trying to impose.

Perhaps we need `CString` and `MutCString`, as well as `MutCString::to_c_string`?

**Comment by alexcrichton** [comment]
This was resolved in #20507
