### ISSUE TITLE
std::os::errno returns a different type than IoError::from_errno takes

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang/rust#16786]
`std::os::errno` returns an `int` whereas `IoError::from_errno` takes a `uint`. It's a bit irritating to have to write out `errno() as uint` every time one constructs an `IoError` from `errno`.

AIUI `errno` in C is always of (C) type `int`, so my inclination would be to change `from_errno` unless there's a good reason for it to be using `uint`.

**Comment by steveklabnik** [comment]
```
src/libstd/os.rs:pub fn errno() -> uint {
src/libstd/sys/unix/os.rs:pub fn errno() -> int {
src/libstd/sys/unix/os.rs:    fn errno_location() -> *const c_int {
src/libstd/sys/unix/os.rs:    fn errno_location() -> *const c_int {
src/libstd/sys/unix/os.rs:    fn errno_location() -> *const c_int {
src/libsrc/libstd/os.rs:pub fn errno() -> uint {
src/libstd/sys/unix/os.rs:pub fn errno() -> int {
src/libstd/sys/unix/os.rs:    fn errno_location() -> *const c_int {
src/libstd/sys/unix/os.rs:    fn errno_location() -> *const c_int {
src/libstd/sys/unix/os.rs:    fn errno_location() -> *const c_int {
src/libstd/sys/windows/os.rs:pub fn errno() -> uint {
std/sys/windows/os.rs:pub fn errno() -> uint {

```

**Comment by aturon** [comment]
This affects the stabilization of the new `std::io::Error::from_os_error`. Nominating for 1.0-beta P-backcompat-libs.

**Comment by pnkfelix** [comment]
I-needs-decision, P-high; but not 1.0 beta nor P-backcompat-libs.

(We may need to put more thought into how we track such things)

**Comment by huonw** [comment]
We no longer have `std::os:errno`, just various methods on [`io::Error`](http://doc.rust-lang.org/std/io/struct.Error.html#method.last_os_error), which all use `i32`. Closing.
