### ISSUE TITLE
Add more android slaves

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#16795]
Right now we have just one android slave, a limitation due to some ugly code in the config file. We have many more slaves for all other platforms.

**Comment by lahwran** [comment]
Android on api 21 is broken, it'd be cool to get that tested regularly. It'd also be good to get a mac-for-android build going, because that's broken as well.

**Comment by brson** [comment]
This particular bug is just to expand the number of latent EC2 buildslaves that can test Android concurrently. Right now it is artificially limited to 1 buildslave, while all other EC2 slaves can spin up multiple slaves.

We do need to test other Android configs though.
