### ISSUE TITLE
failure to spawn new tasks on OS X with `Too many open files` error

### ISSUE THREAD

**Issue by explicitcall** [rust-lang/rust#16793]
When trying to spawn several thousand tasks on OS X 10.9.4 I get this error (duplicate a few dozen times at once):

    task '<unnamed>' failed at 'could not initialize task_rng: couldn't open file (Too many open files; path=/dev/urandom; mode=open; access=read)', /opt/local/var/macports/build/_opt_mports_dports_lang_rust/rust/work/rust/src/libstd/rand/mod.rs:342

Reproducible for me with this code:

```rust

fn process_errors() {
  let path = "file.log";
  let mut file = BufferedReader::new(File::open(&Path::new(path)));
  let lines: Vec<String> = file.lines().map(|x| x.unwrap()).collect();
  let len = lines.len();
  let sharedLines = Arc::new(lines);
  let (tx, rx) = channel();

  for i in range(0, len) {
    let share = sharedLines.clone();
    let tx = tx.clone();

    spawn(proc() {
      let s = (*share)[i].as_slice();
      let decoded: ErrorJson = json::decode(s).ok().expect(format!("failed to parse line {}", s).as_slice());
      let re = regex!(r"needed string (.+) other string");
      for caps in re.captures_iter(decoded.message.as_slice()) {
        tx.send(caps.at(1).to_string());
        return;
      }

      tx.send("".to_string());
    });
  }
}
```

`file.log` contains a few thousand lines of `"\n"`-separated JSON objects.

Output of `rustc --version`:

    rustc 0.12.0-pre (5fb2dfaa2 2014-08-25 12:10:56 +0000)

**Comment by steveklabnik** [comment]
Was this using green threads or native threads?

**Comment by justinas** [comment]
Can confirm this on OS X 10.10.2, using `rustc 1.0.0-nightly (3e4be02b8 2015-03-13) (built 2015-03-13)`. Tried launchd, ulimit, sysctl workarounds mentioned here: none of them work.

The code:
```rust
use std::thread;
use std::old_io::timer::sleep;
use std::time::Duration;
fn main() {
    for i in 1..5000 {
        thread::spawn(move || {
            println!("{}", i);
            sleep(Duration::seconds(10));
        });
    }
}
```

Output:
```
1
<...>
2043
2044
2045
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(35) }', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:744
```

**Comment by alexcrichton** [comment]
I believe this has basically been fixed by switching to native threads, we're now just constrained by the normal system limits.
