### ISSUE TITLE
Using a custom logger requires set_logger in every task

### ISSUE THREAD

**Issue by seanmonstar** [rust-lang/rust#16794]
Currently, the logger is stored in TLS. It's fine to setup a logger at the start of your program, but if you use `spawn` a lot, it's cumbersome to remember in each call to setup your logger again.

I think tasks should inherit the logger from the task that spawned it, perhaps with an option to turn it off (less important).

cc #3309

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/log#21
