### ISSUE TITLE
Trailing doc comments

### ISSUE THREAD

**Issue by bharrisau** [rust-lang/rust#16816]
Not sure if this is big enough for a RFC, or if it is unwanted as it adds to the problem in #6782.

In Zinc, we have been trialling a different doc comment syntax to make marking up our struct-like macros a little nicer (https://github.com/hackndev/zinc/blob/master/ioreg/ioreg.rs#L129).

The `//=`  attaches to the previous field, such that

```
struct Foo {
  foo1: bool, //= Doc comment
  foo2: bool  //= Doc comment2
}
```

is the same as 

```
struct Foo {
  /// Doc comment
  foo1: bool,
  /// Doc comment 2
  foo2: bool
}
```

Something to consider?

**Comment by steveklabnik** [comment]
Yes, please persue an RFC if you'd still like to try to get this into Rust.
