### ISSUE TITLE
`#[cfg]` on struct field permits empty unusable struct

### ISSUE THREAD

**Issue by klutzy** [rust-lang/rust#16819]
```Rust
struct S {
    #[cfg(untrue)]
    a: int,
}

fn main() {
    let s = S;
}
```

```
<anon>:7:13: 7:14 error: `S` is a structure name, but this expression uses it like a function name
<anon>:7     let s = S;
                     ^
<anon>:7:13: 7:14 note: Did you mean to write: `S { /* fields */ }`?
<anon>:7     let s = S;
                     ^
```

Here `S { }` is suggested but it is also not allowed:

```
<anon>:7:14: 7:15 error: structure literal must either have at least one field or use functional structure update syntax
<anon>:7     let s = S{};
                      ^
```

**Comment by klutzy** [comment]
Triage: still an issue. Sub-bug of #24266.

**Comment by petrochenkov** [comment]
Note, that after https://github.com/rust-lang/rust/pull/28336 empty *tuple* structs are still disallowed, but obtainable with `#[cfg]`.
```
struct TS (
    #[cfg(untrue)]
    int,
);
```
IMO, amending https://github.com/rust-lang/rfcs/pull/218 to allow empty tuple structs would be the best solution.

**Comment by pnkfelix** [comment]
(note that  rust-lang/rfcs#218  did include [discussion](https://github.com/pnkfelix/rfcs/blob/empty-struct-with-braces-take-2/active/0000-empty-structs-with-braces.md#empty-tuple-structs) of the generalization to empty tuple structs... in short, I do not think you can directly generalize the RFC's strategy to tuple structs, though there may be some more limited generalization available.)

(I personally think the better approach here would be to explicitly disallow using `#[cfg]` attributes with tuple structs.  I.e. If you need that kind of flexibility, use a record struct.)
