### ISSUE TITLE
DPS with fat pointers

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#16829]
We can make trans code cleaner and hopefully generate better code by supporting destination passing style with fat pointers

**Comment by steveklabnik** [comment]
Triage: I'm not sure if there's been any change here.

**Comment by dotdash** [comment]
@nrc What is/was the plan here?

**Comment by nrc** [comment]
I can't remember at all. I guess this is likely to be subsumed by MIR-related trans work. Doesn't seem any point in leaving this open.
