### ISSUE TITLE
Support MSP430 architecture and target

### ISSUE THREAD

**Issue by alexchandel** [rust-lang/rust#16831]
The MSP430 architecture is a common target in embedded programming, namely TI's MSP430 microcontroller family, and should be targetable by Rust. Support for MSP430 was recently [added to LLVM](http://llvm.org/docs/doxygen/html/dir_08aa625df1bb9fc877a11230539de4c0.html), although absent LLD support the MSP430 binutils is still necessary (as for all platforms). Previously, the only way to target MSP430 was using the custom GCC toolchain.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#758
