### ISSUE TITLE
local time format error: rfc822

### ISSUE THREAD

**Issue by zengsai** [rust-lang/rust#16841]
Source Code:

```rust
extern crate time;

fn main() {
    let utc = time::now_utc();
    let local = time::now();

    println!("utc:   {}", utc.rfc822());
    println!("local: {}", local.rfc822());
}

```
Console Output:

    utc:   Fri, 29 Aug 2014 08:05:12 GMT
    local: Fri, 29 Aug 2014 16:05:12 strftime: can't understand this format Z

According to the document of this API, the correct output should be:

    utc:   Fri, 29 Aug 2014 08:05:12 GMT
    local: Fri, 29 Aug 2014 16:05:12 PST

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/time#64
