### ISSUE TITLE
Track spans and TypeTrace when relating unbound type variables in type inferencer

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#16847]
The new type inferencer in PR #15955 does not track spans as precisely as it could. When two unbound type variables are related to one another, it records the relation (subtype, supertype, equality) but does not record the _reason_ that the relation exists (i.e., the associated span and `TypeTrace`). When one of those two variables is later bound to a specific type `T`, the other will also be bound to a type `U` (derived from `T`) and `T` and `U` will be related -- but this relation will use the current span and TypeTrace, rather than the original span. The primary side-effect of this is that the output from a "cannot infer" message will be more confusing -- but given that that output is already pretty useless, I was unable to get a good example.

**Comment by steveklabnik** [comment]
@nikomatsakis is this still relevant today?

**Comment by nikomatsakis** [comment]
On Tue, Feb 02, 2016 at 10:40:33AM -0800, Steve Klabnik wrote:
> @nikomatsakis is this still relevant today?

Yes.

**Comment by steveklabnik** [comment]
Triage: not aware of any changes, but then again, I wouldn't be

**Comment by lcnr** [comment]
Given that there isn't an associated test for this issue and I don't consider it to be actionable, I am going ahead and close this.
