### ISSUE TITLE
Don't force the same type in match arms that are only evaluated for side effects or allow ; in match arms

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#16858]
```rust
match x {
    A => f(),
    B => g(),
}
```
This does not work if f and g return different types. Since the return value is discarded, this does not matter. Alternatively:
```rust
match x {
    A => f();,
    B => g();,
}
```

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#746
