### ISSUE TITLE
DST coercions do not work in slices

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#16864]
``` rust
fn main() {
    let x: &[uint] = &[1u];
    let _y = &[x, &[1, 2]];
}
```

```
<anon>:3:19: 3:26 error: mismatched types: expected `&[uint]`, found `&[uint, .. 2]` (expected vector, found vector)
<anon>:3     let _y = &[x, &[1, 2]];
                           ^~~~~~~
```

This may not be a bug, but it does mean that slices constructed like this need to have type annotations.

**Comment by steveklabnik** [comment]
Triage: this is still true. Also not sure if it's a bug. @nikomatsakis ?

**Comment by eddyb** [comment]
This is because we propagate the expected type downwards but not rightwards (from `x` to `&[1, 2]`).
We probably should do this by taking `x`'s type after applying the outer expected type on it (and repeat this for any array element, so they can each add more information for the next one).

**Comment by Mark-Simulacrum** [comment]
With the code updated, this no longer causes an error. Closing.

```rust
fn main() {
    let x: &[u32] = &[1u32];
    let _y = &[x, &[1, 2]];
}
```
