### ISSUE TITLE
Cannot perform [] DST coercions with `as`

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#16865]
```rust
fn main() {
    let _x = &[1u] as &[uint];
}
```

```
<anon>:2:14: 2:30 error: non-scalar cast: `&[uint, .. 1]` as `&[uint]`
<anon>:2     let _x = &[1u] as &[uint];
                      ^~~~~~~~~~~~~~~~
```

Because of this and #16864 the only way to go `&[T, .. n]` &rarrow; `&[T]` is via explicit type annotations on every variable (either by being passed as a function argument, or as a local).

**Comment by nham** [comment]
Seems like this might be resolved. The example successfully compiles (`rustc 1.2.0-nightly (0cc99f9cc 2015-05-17) (built 2015-05-18)`)

**Comment by nrc** [comment]
Yep, this works now.
