### ISSUE TITLE
library stabilization: allow inherent methods on primitive types

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#16862]
Currently, the only way we can provide methods for primitive types like slices it through public extension traits (like `Str`). This approach has a few downsides:

- Most important, people are tempted to use these traits for generic programming (taking `Str`-bounded types, and/or implementing `Str` on their own types), which is very much not the intention.
- It clutters the exports of several modules in core and std.
- It's harder for newcomers to understand what's going on, since it's not clear whether the type or the trait is important.

If we could allow inherent `impl` blocks for primitive types, we could avoid stabilizing these extension traits.

**Comment by aturon** [comment]
cc @japaric

**Comment by japaric** [comment]
> If we could allow inherent impl blocks for primitive types, we could avoid stabilizing these extension traits.

@aturon Could you be more specific about which traits would get replaced with inherent impls? `Int`? `Float`? (I have a rough idea of how to do this. I don't know if it would ulimately work, and it involves one lang item per primitive impl)

**Comment by reem** [comment]
This is also a backwards-compatability hazard since changing the signature of any trait method is a backwards incompatible change, even if that trait is meant to be "sealed."

**Comment by huonw** [comment]
We can "stability-seal" traits by having `#[unstable]` non-default methods on them, which means they cannot be implemented in stable code.

**Comment by aturon** [comment]
@japaric Also `StrExt`, `CharExt`, `PtrExt`.

**Comment by aturon** [comment]
@japaric oh and `SliceExt`.

This change would make the documentation much friendlier, would ease the back-compat story (as @reem points out), and help clarify the story about the numeric traits (by relegating all generics to external libraries for the time being).

**Comment by tomjakubowski** [comment]
Can this be closed? Seems like #23104 addressed this.

**Comment by alexcrichton** [comment]
Indeed!
