### ISSUE TITLE
DST leads to unintuitive errors with traits like `Int`

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#16874]
The [`Int`](http://doc.rust-lang.org/master/std/num/trait.Int.html) trait has a very similar name to the `int` primitive type, so if someone accidentally uses `Int` (e.g. forgetting that primitive types have special names/if they come from Haskell or some such) they can get confusing messages, especially now that DST allows for bare traits to be used more often, e.g.

``` rust
struct Foo { x: Int }

fn main() {}
```

gives

```
<anon>:1:17: 1:20 error: explicit lifetime bound required
<anon>:1 struct Foo { x: Int }
                         ^~~
```

which is really confusing.

I'm not really sure how we fix this, but mentioning "trait" somewhere in the message would be helpful.

**Comment by steveklabnik** [comment]
This ticket is interesting. First of all, this now actually compiles just fine:

```
trait Int {}

struct Foo { x: Int }

fn main() {}
```

just gives

```
hello.rs:3:1: 3:22 warning: struct is never used: `Foo`, #[warn(dead_code)] on by default
hello.rs:3 struct Foo { x: Int }
           ^~~~~~~~~~~~~~~~~~~~~
hello.rs:3:14: 3:20 warning: struct field is never used: `x`, #[warn(dead_code)] on by default
hello.rs:3 struct Foo { x: Int }
                        ^~~~~~
```

Second, the confusingly-named traits have been removed.

As such, I think this ticket is probably resolved. What do you think, @huonw ?

**Comment by bltavares** [comment]
Triaging:

The following code now only prompts one warning:

```rust
trait Int {}

struct Foo { x: Int }

fn main() {}
```

```
<anon>:3:1: 3:22 warning: struct is never used: `Foo`, #[warn(dead_code)] on by default
<anon>:3 struct Foo { x: Int }
         ^~~~~~~~~~~~~~~~~~~~~
```

As @steveklabnik said, it compiles just fine, as the declared `Int` trait has not lifetime parameter.
If we modify to code to introduce a new lifetime paramenter, we have a different error message which points to the missing lifetime argument.

```rust
trait Int<'a> {}

struct Foo { x: Int }

fn main() {}
```

```
<anon>:3:17: 3:20 error: wrong number of lifetime parameters: expected 1, found 0 [E0107]
<anon>:3 struct Foo { x: Int }
                         ^~~
<anon>:3:17: 3:20 help: see the detailed explanation for E0107
error: aborting due to previous error
playpen: application terminated with error code 101
```

As `Int` no longer exists, I think this issue could be closed.

**Comment by Mark-Simulacrum** [comment]
Yeah, I don't see any real problem here; closing.
