### ISSUE TITLE
StrSlice should implement ImmutableSlice

### ISSUE THREAD

**Issue by nwin** [rust-lang/rust#16899]
Although these traits share a lot of common functionality they are totally separated such that additional functionality that could be shared between them has to be implemented twice. 

An example is the “eager”-slicing as discussed on [reddit](http://www.reddit.com/r/rust/comments/2f0dnf/string_and_vec_slicing_methods_need_safe/). It would be convenient both for `&str` and `&[T]` (given it makes sense to slice strings anyway).

**Comment by steveklabnik** [comment]
Changes of this nature would require an RFC nowadays, please persue one if this is still relevant and you still feel strongly about it. Thanks!
