### ISSUE TITLE
Provide a non-failing slicing method for &[T] and &str

### ISSUE THREAD

**Issue by nwin** [rust-lang/rust#16900]
As discussed on [reddit](http://www.reddit.com/r/rust/comments/2f0dnf/string_and_vec_slicing_methods_need_safe/) it would be very convenient to have a slicing method that can't fail and returns an truncated slice instead. This is for example used in python and works well. The [implementation] is pretty trivial but since it is so convenient, it should be implemented in the std lib.

I could make a pull request with the actual implementation + comments if this functionality is desired a a good name has been chosen (I'm not sure if I like eager).

[implementation]: https://gist.github.com/nwin/259d919ca7806a1714ef

**Comment by steveklabnik** [comment]
Adding stuff to the standard library requires an RFC at this point. Please persue one if this is still important to you. Thanks!
