### ISSUE TITLE
Unused parameters not detected in recursive functions

### ISSUE THREAD

**Issue by bfops** [rust-lang/rust#16910]
The following doesn't generate a warning:

    fn foo(x: int, y: int) {
      if x > 0 {
        foo(x - 1, y);
      }
    }

    pub fn main() {
      foo(3, 0);
    }

**Comment by alexcrichton** [comment]
Currently the "unused foo" lints are fairly simple in the sense that they only pattern match for uses of a variable or not. This keeps the implementation quite readable and doesn't involve having to jump through hoops to detect a case like this. While I'm sure we could add this sort of analysis, it's somewhat questions whether it's worth the effort, so I'm going to close this for now. If it's implemented, however, feel free to make a PR!
