### ISSUE TITLE
"Explicit lifetime bound required" message should give suggestions

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#16948]
See comments on discuss:

- http://discuss.rust-lang.org/t/confused-by-lifetime-error-messages-tell-me-about-it/358/20?u=nikomatsakis
- http://discuss.rust-lang.org/t/confused-by-lifetime-error-messages-tell-me-about-it/358/22?u=nikomatsakis

Nominating for P-high, not 1.0.

**Comment by steveklabnik** [comment]
It seems that the span for one of these errors has gotten better:

           "the lifetime bound for this object type cannot be deduced \
                               from context; please supply an explicit bound");

The Discuss thread is difficult because there aren't a lot of contained examples, and we don't have an extended error explanation for this message, nor any tests that I can find?

```
$ git grep "explicit lifetime bound required"
src/librustc_typeck/astconv.rs:                  "ambiguous lifetime bound, explicit lifetime bound required");
src/librustc_typeck/diagnostics.rs:    E0227, // ambiguous lifetime bound, explicit lifetime bound required
src/librustc_typeck/diagnostics.rs:    E0228, // explicit lifetime bound required
```

**Comment by brson** [comment]
Close. Old and unloved.
