### ISSUE TITLE
Include the "periodic table" into the official docs

### ISSUE THREAD

**Issue by nodakai** [rust-lang/rust#16960]
Why don't you officially include this excellent ["periodic table of Rust types"](http://cosmic.mearie.org/2014/01/periodic-table-of-rust-types/) into, say, the top of [the pointer guide](http://doc.rust-lang.org/guide-pointers.html)?  (It's under cc-by-4.0.)

**Comment by steveklabnik** [comment]
This table is now out of date. Is this worth trying to resurrect? I still have complexity worry here.

**Comment by sinistersnare** [comment]
Regardless if it is included or not, I would love to see it updated for DST and unboxed closures to be ticked on by default (or remove the boxes because they are permanent)

**Comment by lifthrasiir** [comment]
I currently have no good idea to restructure the table, but don't mind if there is a contribution. I'll at least mark the page as outdated.

**Comment by sinistersnare** [comment]
Does the page have a source repo? Or is it only just a single html page?

**Comment by lifthrasiir** [comment]
@sinistersnare It's a single page (including the CSS).

**Comment by steveklabnik** [comment]
After thinking about this a long time, I'm not sure where it goes, I'm afraid of the perception of complexity, and so I'm going to just give this a close. Thanks.
