### ISSUE TITLE
Switch rustdoc to Common Markdown

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#16978]
Assuming this takes off it's probably best to be on the right side of history: http://standardmarkdown.com/. Probably easiest to just make hoedown conformant.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#620
