### ISSUE TITLE
libnative/io: more methods need to be backed up by keep_going()

### ISSUE THREAD

**Issue by nodakai** [rust-lang/rust#16984]
Should use `keep_going()` rather than `mkerr_libc()`

https://github.com/rust-lang/rust/blob/master/src/libnative/io/file_unix.rs#L102

```rs
    fn pwrite(&mut self, buf: &[u8], offset: u64) -> IoResult<()> {
        super::mkerr_libc(retry(|| unsafe {
            libc::pwrite(self.fd(), buf.as_ptr() as *const _,
                         buf.len() as libc::size_t, offset as libc::off_t)
        }))
    }
```

**Comment by steveklabnik** [comment]
Libnative is dead now, and lots has changed. Is this still relevant?

**Comment by nodakai** [comment]
Close this issue in favor of an ongoing discussion for RFC 517 rust-lang/rfcs#576
