### ISSUE TITLE
regionck fails to link lifetime of ref bindings in certain situations

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#16994]
The recent attempts to improve hashmap seem to have exposed a bug in regionck where it fails to link the lifetimes of ref bindings in some situations.

A mostly minimized test case is here:

```
fn cb<'a,T>(x: |(&'a uint, &'a (Vec<&'static uint>, bool))| -> T) -> T {fail!()}

fn main() {
    cb(|(k, &(ref v, b))| (*k, v.clone(), b));
}
```

This test fails to compile but (I believe) should succeed. The problem is that the lifetime of the `ref v` binding inside the callback from `map` is not "linked" (in regionck terminology) to the lifetime `'a`, and hence region inference infers a lifetime for `v` that is too small. It was not immediately obvious what the best way is to fix this -- the code around handling ref bindings seems a bit ... off in regionck, so I need to think about it some.

Perturbing the code in various ways can workaround the issue, which is bad for making minimized test cases but good for landing the hasmap patch in the meantime!

**Comment by steveklabnik** [comment]
I _think_ this is the original problem, updated to current syntax:

```rust
fn cb<'a,T>(x: Box<Fn((&'a i32, &'a (Vec<&'static i32>, bool))) -> T>) -> T {panic!()}

fn main() {
    cb(|(k, &(ref v, b))| (*k, v.clone(), b));
}
```

error:

```text
hello.rs:4:28: 4:30 error: the type of this value must be known in this context
hello.rs:4     cb(|(k, &(ref v, b))| (*k, v.clone(), b));
                                      ^~
hello.rs:4:34: 4:39 error: the type of this value must be known in this context
hello.rs:4     cb(|(k, &(ref v, b))| (*k, v.clone(), b));
                                            ^~~~~
hello.rs:4:8: 4:45 error: mismatched types:
 expected `Box<core::ops::Fn((&i32, &(collections::vec::Vec<&'static i32>, bool))) -> _ + 'static>`,
    found `[closure@hello.rs:4:8: 4:45]`
(expected box,
    found closure) [E0308]
hello.rs:4     cb(|(k, &(ref v, b))| (*k, v.clone(), b));
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
hello.rs:4:8: 4:45 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to 3 previous errors
```

**Comment by arielb1** [comment]
If you use a boxed closure, remember to box it:
```Rust
fn cb<'a,T>(x: Box<Fn((&'a i32, &'a (Vec<&'static i32>, bool))) -> T>) -> T {panic!()}

fn main() {
    cb(Box::new(|(k, &(ref v, b))| (*k, v.clone(), b)));
}
```
This runs on modern rustc.

**Comment by steveklabnik** [comment]
Ah duh. Thanks!
