### ISSUE TITLE
Code blocks wrap

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#17017]
The guide currently has code sections that wrap: http://i.gyazo.com/8c2ac3f95775dd4847b3f0aae204eaa4.png

These sections are the regular, 100 col length. Rustdoc should make the code blocks wide enough to not let this happen.

**Comment by steveklabnik** [comment]
Triage: no change. Tagging `E-easy` because this should just be a CSS change.

**Comment by steveklabnik** [comment]
http://doc.rust-lang.org/nightly/book/lifetimes.html#examples now contains an example of this, I think the original screenshot is gone now. the line

> fn frob<'a, 'b>(s: &'a str, t: &'b str) -> &str; // Expanded: Output lifetime is ambiguous

is 91 characters long, but wraps.

**Comment by marti1125** [comment]
thanks for the example @steveklabnik I am cheking that
