### ISSUE TITLE
Separate to_string method from Show

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#17031]
The biggest problem is that `impl Show for Option<T> where T: Show`  is a thing. This causes nasty issues like calling `.to_string()` on an `Option<&str>` and getting `"Some(foo)"` back. This feels wrong and leads to issues very often in my experience, especially since our *only* way to get a `String` from a `&str` right now is `.to_string()` (as opposed to the earlier `.to_owned()`, which lacked this problem).

Technically the `{}` formatter has the same problems, but that hasn't come up as an issue for me.

**Comment by SimonSapin** [comment]
I believe this is fixed by the introduction of `fmt::String`: `ToString` is implemented for `T: fmt::String` rather than `T: fmt::Show`, and `Option<_>` does not implement `fmt::String`.

**Comment by pnkfelix** [comment]
I agree with @SimonSapin ; closing
