### ISSUE TITLE
ICE compiling string-cache-macros

### ISSUE THREAD

**Issue by mikejsavage** [rust-lang/rust#17049]
Fresh phf v0.0.0 (https://github.com/sfackler/rust-phf#d7ae8800)
	Fresh encoding v0.1.0 (https://github.com/lifthrasiir/rust-encoding#35f0d70f)
	Fresh phf_mac v0.0.0 (https://github.com/sfackler/rust-phf#d7ae8800)
	Fresh lazy_static v0.1.0 (https://github.com/Kimundi/lazy-static.rs#e62a6537)
	Fresh html5ever-macros v0.0.0 (https://github.com/kmcallister/html5ever?ref=dev#fb82e53c)
	Fresh url v0.1.0 (https://github.com/servo/rust-url#d894135c)
	Fresh curl v0.0.1 (https://github.com/carllerche/curl-rust#a98f4290)
	Compiling string_cache_macros v0.0.0 (https://github.com/kmcallister/string-cache?ref=dev#dcc41870)
	Could not compile `string_cache_macros`.

	--- stdout
	task 'rustc' failed at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-linux/build/src/libsyntax/ast_util.rs:776

	stack backtrace:
	   1:     0x7fa119365ed0 - rt::backtrace::imp::write::h53108151a1c919cdOLq
	   2:     0x7fa119369070 - failure::on_fail::hce96b96ffc877504w7q
	   3:     0x7fa11d946930 - unwind::begin_unwind_inner::hab46511b32d4adddZ2d
	   4:     0x7fa11aba34b0 - unwind::begin_unwind::h8363082939923295011
	   5:     0x7fa11aba3c20 - diagnostic::Handler::bug::h3586631f64308fe6ufF
	   6:     0x7fa11dfa3bf0 - driver::session::Session::bug::h7c4efc9e6e69e371MGC
	   7:     0x7fa11e3c0160 - middle::trans::consts::const_deref::h994d1bab8c0569bccg8
	   8:     0x7fa11e3beab0 - middle::trans::consts::const_expr::hde53f8b5ba3ea703wl8
	   9:     0x7fa11e333b00 - middle::trans::base::get_item_val::hf51c1a11475b5c10ABf
	  10:     0x7fa11e38f1c0 - middle::trans::expr::trans_def::hfb492b44752d31f3mN3
	  11:     0x7fa11e385d10 - middle::trans::expr::trans_unadjusted::h5f343dfce53924b0wn3
	  12:     0x7fa11e345540 - middle::trans::expr::trans::h264fae1f71a954e6iE2
	  13:     0x7fa11e37e6c0 - middle::trans::callee::trans_args::h7ad814cf9be11da6O61
	  14:     0x7fa11e34d100 - middle::trans::callee::trans_call_inner::h1e8ce065ac7a042eOL1
	  15:     0x7fa11e379140 - middle::trans::callee::trans_method_call::h84dca6926ed068a02G1
	  16:     0x7fa11e386c40 - middle::trans::expr::trans_rvalue_dps_unadjusted::hb435d260fcbf01f8YW3
	  17:     0x7fa11e385d10 - middle::trans::expr::trans_unadjusted::h5f343dfce53924b0wn3
	  18:     0x7fa11e345540 - middle::trans::expr::trans::h264fae1f71a954e6iE2
	  19:     0x7fa11e349fa0 - middle::trans::controlflow::trans_for::h27cc5ffa9e390491KFY
	  20:     0x7fa11e3891a0 - middle::trans::expr::trans_rvalue_stmt_unadjusted::h1cdb65f7a13d5bbasR3
	  21:     0x7fa11e343fa0 - middle::trans::expr::trans_into::he76810e0b15663femA2
	  22:     0x7fa11e3443a0 - middle::trans::controlflow::trans_block::hc6e990dd6ea246cacsY
	  23:     0x7fa11e386c40 - middle::trans::expr::trans_rvalue_dps_unadjusted::hb435d260fcbf01f8YW3
	  24:     0x7fa11e343fa0 - middle::trans::expr::trans_into::he76810e0b15663femA2
	  25:     0x7fa11e4141f0 - middle::trans::_match::trans_match_inner::h042c86355422f43em3h
	  26:     0x7fa11e386c40 - middle::trans::expr::trans_rvalue_dps_unadjusted::hb435d260fcbf01f8YW3
	  27:     0x7fa11e343fa0 - middle::trans::expr::trans_into::he76810e0b15663femA2
	  28:     0x7fa11e343460 - middle::trans::controlflow::trans_stmt_semi::hdaac58c7fef10d0firY
	  29:     0x7fa11e342b40 - middle::trans::controlflow::trans_stmt::h87b829ce2fd7b6fc1mY
	  30:     0x7fa11e3443a0 - middle::trans::controlflow::trans_block::hc6e990dd6ea246cacsY
	  31:     0x7fa11e3f2170 - middle::trans::base::trans_closure::hca82336ddae206bcvEe
	  32:     0x7fa11e335620 - middle::trans::base::trans_fn::h80c61a61ef5e8177iQe
	  33:     0x7fa11e330ff0 - middle::trans::base::trans_item::h61aebb3e8aff1b7ei8e
	  34:     0x7fa11e330ff0 - middle::trans::base::trans_item::h61aebb3e8aff1b7ei8e
	  35:     0x7fa11e3fc920 - middle::trans::base::trans_crate::h1ecf6b249bfcb51cJ2f
	  36:     0x7fa11e80fb50 - driver::driver::phase_4_translate_to_llvm::hfecc798fa173c5bam7B
	  37:     0x7fa11e807780 - driver::driver::compile_input::h8608525c5b471524uJB
	  38:     0x7fa11e89b4d0 - driver::run_compiler::h69b3fcd2a164d565UyF
	  39:     0x7fa11e89b3e0 - driver::main_args::closure.141489
	  40:     0x7fa11e8adfe0 - task::TaskBuilder<S>::try_future::closure.142658
	  41:     0x7fa11e8adde0 - task::TaskBuilder<S>::spawn_internal::closure.142635
	  42:     0x7fa11dc9e530 - task::spawn_opts::closure.8397
	  43:     0x7fa11d99c660 - rust_try_inner
	  44:     0x7fa11d99c650 - rust_try
	  45:     0x7fa11d9440f0 - unwind::try::hd6387be7e7aa758afRd
	  46:     0x7fa11d943f50 - task::Task::run::hb83ab5c92810e88692c
	  47:     0x7fa11dc9e290 - task::spawn_opts::closure.8343
	  48:     0x7fa11d945a60 - thread::thread_start::hd97e8e956809086bgod
	  49:     0x7fa118703060 - start_thread
	  50:     0x7fa11d615489 - __clone
	  51:                0x0 - <unknown>

	--- stderr
	error: internal compiler error: can't dereference const of type [(&'static str,&'static str), .. 6]
	note: the compiler hit an unexpected failure path. this is a bug.
	note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
	note: run with `RUST_BACKTRACE=1` for a backtrace

	To learn more, run the command again with --verbose.

**Comment by cmr** [comment]
No longer repros.
