### ISSUE TITLE
add a low-level library for manipulating memory mappings, protection and locking

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#17047]
Rust should expose a portable implementation of the `mmap`, `mprotect` and `mlock` functionality (`VirtualAlloc`, `VirtualProtect`, `VirtualLock` on Windows). The current support for memory mapped files is *very* lacking. The low-level support should be exposed via `unsafe` functions, and then a new high-level wrapper can be written on top of it.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#786
