### ISSUE TITLE
std docs should have version info and build date somewhere

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#17058]
The std docs should list:
 - The version they were built with
 - The build date

They could be at the top or bottom of every page, or on a stand-alone page like *About* or *Help*.

This may not be important on rust-ci.org where I think they are rebuilt with every push but it seems like a good idea. It might be more useful on other sites where it isn't rebuilt for every push.

**Comment by steveklabnik** [comment]
Yes, this is basically a dup of #14466/
