### ISSUE TITLE
No rule to make target i686-unknown-linux-gnu/rt/arch/i386/morestack.o

### ISSUE THREAD

**Issue by tomaka** [rust-lang/rust#17079]
While compiling rust with Ubuntu 14.04 on a 32 bits machine with the `--llvm-root` flag:

```
...
extracting rust-stage0/bin/rustc
make: *** No rule to make target `i686-unknown-linux-gnu/rt/arch/i386/morestack.o', needed by `i686-unknown-linux-gnu/rt/libmorestack.a'.  Stop.
```

Removing `--llvm-root` fixes the problem, but I wanted to use the `--llvm-root` flag in order to use LLVM 3.3, which is the version required by emscripten.

(similar to #15228)

**Comment by steveklabnik** [comment]
Is this still a problem today?

**Comment by tomaka** [comment]
I'm probably never going to try this ever again.
