### ISSUE TITLE
ASLR breaks debugging with gdb on Windows

### ISSUE THREAD

**Issue by vadimcn** [rust-lang/rust#17098]
As of 57781c3c30babf85ee7a95f586ef5dcfb30104f8, any attempt to set a breakpoint (including the default b/p in main()) in a rust-compiled executable, results in this GDB error:

```
Cannot insert breakpoint 1.
Cannot access memory at address 0xXXXXXX
```

Both 32- and 64-bit builds seem to be affected.

**Comment by steveklabnik** [comment]
Triage: I am unsure if there are any changes here. Is this a problem with GDB specifically? What steps would we take to address this?

**Comment by steveklabnik** [comment]
Triage: with my questions unaswered since 2015, I'm going to close this. If this is still important, please give me some steps to reproduce!
