### ISSUE TITLE
Function types have no primitive page in docs

### ISSUE THREAD

**Issue by 45ujksy5l03jcvf** [rust-lang/rust#17104]
Similar to #15318 and #15654

**Comment by steveklabnik** [comment]
@alexcrichton @huonw how do I make this happen? is this another 'dummy module' thing?

**Comment by alexcrichton** [comment]
It would likely require modifying code [somewhere around here](https://github.com/rust-lang/rust/blob/master/src/librustdoc/clean/mod.rs#L1403-L1480) and adding a dummy (private) module or declaring another one as `#![doc(primitive = "fn")]`

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by QuietMisdreavus** [comment]
Adding a page for function pointers as a whole (under some general name `fn` or the like) is a small enough change, but unless i've missed something, there are no impl blocks anywhere that could be picked up for that page. It's the curse of variadic generics, but unlike arrays and tuples, there are no stock impls for function pointer types up to a certain arity. Is a nearly-empty page (save for the `doc(primitive)` block that creates the page in the first place) acceptable?

cc @rust-lang/docs: What do we want to display for documentation on function pointers as a whole? I have a short blurb that mainly just links to the `Fn*` traits, and a note that function pointers are `Copy`, so far, but do we have anything else to add?

**Comment by petrochenkov** [comment]
@QuietMisdreavus 
>unlike arrays and tuples, there are no stock impls for function pointer types up to a certain arity.

https://github.com/rust-lang/rust/blob/eba9d7f08ce5c90549ee52337aca0010ad566f0d/src/libcore/ptr.rs#L884

**Comment by QuietMisdreavus** [comment]
On second thought, i'll just upload what i have and let that discussion happen there. The PR to add this is #43529.

**Comment by QuietMisdreavus** [comment]
@petrochenkov I stand corrected. I'll start working that in, then. Thanks!
