### ISSUE TITLE
Implement the <= and >= operators via a trait that doesn't require (T, <=) to be a partial order.

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#17149]
Right now the way to get the `<=` and `>=` operators is to implement `PartialOrd`. Unfortunately there seems to be some confusion whether `T: PartialOrd` implies that `(T, <=)` is a partial order [1]. The name implies it but the documentation [2] doesn't mention it. This is especially confusing since the documentation for `Ord` [3] mentions that `(T, <=)` has to be a total order.

Either way, `PartialOrd: PartialEq` and thus implementing `<=` requires you to implement `==`. This doesn't make much sense for objects that aren't part of a partial order. For example:

- `T` is a set of operators and `<=` orders them by operator precedence.
-  More generally: `(T, ≤)` where `≤` is defined via `a ≤ b ⇔ f(a) ≼ f(b)` where `f` is some non-injective function into an ordered space.

Therefore implementing `<=` should not require implementing `==`. Instead:

```rust
/// Trait for types that form a [preorder](http://en.wikipedia.org/wiki/Preorder).
///
/// A preorder `(T, <=)` has two requirements that your implementation must follow:
///
/// - `a <= a`
/// - `a <= b` and `b <= c` implies `a <= c`
///
/// Note that, if you also implement the `==` operator, then the first requirement also
/// implies
///
/// - `a == b` implies `a <= b` and `b <= a`.
///
/// If you implement `<=` and `==`, then people might get confused by a lack of
/// antisymmetry. Consider one of the following:
///
/// - If `(T, <=)` is a partial order, implement `PartialOrd` instead.
/// - If `(T, <=)` is not a partial order, don't implement the `==` operator.
/// - Document clearly that `(T, <=)` is not antisymmetric.
trait PreOrd {
    /// This method tests `self <= other`.
    fn le(&self, other: &Self) -> bool;

    /// This method tests greater or equal to (>=).
    fn ge(&self, other: &Self) -> bool {
        other.le(self)
    }
}
```

[1] http://en.wikipedia.org/wiki/Partially_ordered_set
[2] http://doc.rust-lang.org/std/cmp/trait.PartialOrd.html
[3] http://doc.rust-lang.org/std/cmp/trait.Ord.html

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#747
