### ISSUE TITLE
Add a `-C no-gc-sections` option to rustc

### ISSUE THREAD

**Issue by jansegre** [rust-lang/rust#17141]
I have an issue when static linking to an external library on OS X 64-bit (in my case luajit) that is known to have problems when `-dead_strip` is passed to the linker due to some code being written in asm. A brief talk in the IRC lead to @cmr suggesting me to open this issue. The name `no-gc-sections` is for matching the gnu ld `--gc-sections` nomenclature.

I'm keeping it brief I can give more details if requested.
Edit: PS: I'm manually linking as temporary fix.

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by pnkfelix** [comment]
`-C link-dead-code` covers this at this point, I think.  At least, the way its implemented is that it causes the compiler to stop including `--gc-sections` in its linker invocation.

**Comment by alexcrichton** [comment]
Indeed!
