### ISSUE TITLE
Deprecate unused Encoder trait methods

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#17158]
A gang of trait methods are currently unused and should probably be deprecated and removed.

Unused methods are at least:
```
emit_enum_struct_variant
emit_enum_struct_variant_field
emit_tuple_arg
emit_tuple_struct
emit_tuple_struct_arg
```

**Comment by steveklabnik** [comment]
Encode was moved out of tree, so if this is still an issue, please persue it over at https://github.com/rust-lang/rustc-serialize
