### ISSUE TITLE
Find a way to detect API breakage.

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#17152]
Given that the current rust ecosystem tries very hard to force everyone to use semver, and given that rust code breaks the API easily, this is very important.

Some easy but surprising ways to break the API:

- Adding a field to a struct.
- Changing a struct from Copy to NoCopy (same with Send, Sync, etc.)
- Adding a variant to an enum.
- **Adding a public method to a type** (consider extension traits)
- Adding a method to a trait (consider #17151)

Therefore rustc needs to have something like this:

```
rustc --record-api out.json lib_old.rs
```
stores api information in out.json
```
rustc --compare-api out.json lib_new.rs
```
Checks if the new api is compatible with the old one.

**Comment by mahkoh** [comment]
The more common case is unwinding in unsafe code.

https://github.com/rust-lang/rust/blob/f3d71be65cccfddd232e733c11129ed53961f980/src/libcollections/vec.rs#L262

Changing the conditions under which a function can panic has to be considered a breaking change.

**Comment by mahkoh** [comment]
https://github.com/rust-lang/rfcs/pull/757 addresses

- Adding a variant to an enum.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#759

**Comment by mahkoh** [comment]
I believe this should stay here at least until it has been decided what is considered breaking the API.
