### ISSUE TITLE
No-opt bots should be built against an unoptimised/debug-enabled standard lib and helper libraries

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#17166]
AFAIK, the `nopt-t` builders do a complete bootstrap with optimisations enabled, and then build the tests without optimisations. This means the tests are built against an optimised standard library and so we don't test everything without optimisations. This will be particularly important with https://github.com/rust-lang/rust/issues/17081 since `debug_assert`s would then be off for the vast majority of testing<sup>1</sup>, this also means we aren't using jemalloc's consistency checks on the bots at all (https://github.com/rust-lang/rust/pull/17083).

Another solution would be optimised builder with these debugging settings turned up to full.

(On the other hand, it is possible that this is already the case, in which case we should probably have bots with the debugging settings turned off.)

Nominating for something (P-low, I guess? but it would be quite nice to have these extra assurances).

<sup>1</sup> Unlike general inlined code which is compiled with the optimisation level of the crate it is being included in, `debug_assert`s are currently 'removed' in macro expansion, so any internal consistency checks of generic types like `HashMap`, `Vec` are still lost.

**Comment by reem** [comment]
Visiting for triage. Confirmed with @cmr on IRC that this is still a problem (no tests are run against an unoptimized build).

**Comment by pnkfelix** [comment]
yeah to my knowledge not one of the auto-builders does a build with `--enable-debug`.  It has allowed various bugs to creep in at times (e.g. #24405, #24937)

**Comment by pnkfelix** [comment]
> yeah to my knowledge not one of the auto-builders does a build with `--enable-debug`

This is supposedly no long true; see #27010 (which has been resolved as fixed).

**Comment by alexcrichton** [comment]
We have debug assertions enabled on all bots now, so this is fixed I believe, so closing.
