### ISSUE TITLE
Consider confirming that the `TypeId`s used in a crate are unique

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#17179]
If two `TypeId`s of different types collide, we can get unsoundness, since `Any` relies on `TypeId` being unique for safe downcasts. We could have the compiler double check that any `TypeId`s it computes haven't occured before from another type.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#664
