### ISSUE TITLE
Command::detach can cause zombie processes

### ISSUE THREAD

**Issue by carllerche** [rust-lang/rust#17176]
Properly spawning a detached process requires double forking in order to avoid zombie processes:

http://www.linuxjedi.co.uk/2014/02/why-use-double-fork-to-daemonize.html

I did not see this happening in https://github.com/rust-lang/rust/blob/master/src/libnative/io/process.rs

cc @aturon @alexcrichton

**Comment by steveklabnik** [comment]
I wonder how this sorted out with the IO RFC.

**Comment by alexcrichton** [comment]
This was removed from `Command` (partly for the reasons stated here) and we should be able to add the option backwards-compatibly to `Command`. This issue specifically, however, I'm going to close as it's no longer relevant. I'm sure it will definitely come back up when re-adding the option, however!
