### ISSUE TITLE
Guide: Some Nitpicking

### ISSUE THREAD

**Issue by mitsuhiko** [rust-lang/rust#17191]
* The `ok()` documentation in the read_line example is not just inaccurate, it's misleading and wrong. `.ok()` does not abort the program, it returns an option.  Maybe it needs to have an option section before to explain that type.
* the random number code uses `%` to make random numbers.  This is a bad idea and generally guides are something people copy out of, so I would propose not bringing an antipattern into the mix.

**Comment by steveklabnik** [comment]
@huonw is going to work on stabilizing `rand`, so hopefully we can just get something in here that doesn't require the trait import.

**Comment by steveklabnik** [comment]
I'm giving this a close, finally, as it's not even sure that `rand` is staying in the introduction at this point.
