### ISSUE TITLE
heap: align > MIN_ALIGN can trigger undefined behavior

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#17207]
The non-standard jemalloc API makes dealing with this into the caller's problem.

**Comment by steveklabnik** [comment]
Triage: we have recently updated to jemallc 4.0.0, but we still may want to worry about this.

**Comment by steveklabnik** [comment]
Triage: not aware of any changes here. Tagging as "unsound" and for the libs team, as this would be their issue.

**Comment by Mark-Simulacrum** [comment]
Nominating for discussion by libs team since this is apparently unsound; so we should at least get eyes on it.

**Comment by alexcrichton** [comment]
Discussed during libs triage today, this is mostly relevant for https://github.com/rust-lang/rust/issues/32838 now and I've left [a comment on the associated PR](https://github.com/rust-lang/rust/pull/42313#issuecomment-306631285) explaining how this is relevant. This will likely get closed in time as the allocator trait lands, stabilizes, and we audit various locations in libstd.

**Comment by alexcrichton** [comment]
This was handled as part of https://github.com/rust-lang/rust/pull/42313, so closing.
