### ISSUE TITLE
104MB file must be redownloaded when rustup fails

### ISSUE THREAD

**Issue by BMintern** [rust-lang/rust#17209]
I downloaded `rustup.sh` and then ran it from the command line as a normal user. It took over 10 minutes for me to download the 104MB rust installer (I'm obviously on a slow connection), and then it failed because I didn't run it as root.

When I reran it (this time with `--prefix="$HOME/.local/usr"`), it started to *re-download* the 104 MB file (currently in progress). This is a poor experience for anyone on a slow connection, and an even worse one for someone paying for data usage.

At the least, couldn't the update script keep the installer around if it fails?

The eventual ideal (IMO) would be for the installer to be kept in some canonical location (somewhere in `~/.rust` or something?), and then for the update script to only download a binary diff.

The file is still downloading for me, BTW...

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/19927 added resumption, so I think this should be fixed.
