### ISSUE TITLE
Source lines inside of standard library macros are wrong

### ISSUE THREAD

**Issue by jdm** [rust-lang/rust#17234]
They show up as the really really unhelpful `<std macros:N>`, which is really annoying for things like asssertion failures where it would be nice to see the original source line that invoked it instead.

**Comment by steveklabnik** [comment]
Triage: I'm not aware of any changes here today.

**Comment by Mark-Simulacrum** [comment]
I believe this has since been fixed (we no longer generate the `<std macros:N>` lines, anyway). Given the lack of test case I'm going to go ahead and close.
