### ISSUE TITLE
Guide: filename mismatch in Section 2 Hello, world!

### ISSUE THREAD

**Issue by LyoNick** [rust-lang/rust#17243]
in guide.md section 2
code example should refer either to main OR hello_word 
but mixing them in a single example make no sense i.e:

$ rustc main.rs
$ ./hello_world # or hello_world.exe on Windows

either use the prev chosen name
$ ./main # or main.exe on Windows
OR
$ rustc hello_world.rs
(and change the prev chosen file name)

same mistake is repeated all over the section

**Comment by frewsxcv** [comment]
This has been addressed and can be closed

https://github.com/rust-lang/rust/blob/b565501ad8b4e371e0aca0069c3f4781bd209254/src/doc/trpl/hello-world.md

![screen shot 2015-01-25 at 1 14 39 pm](https://cloud.githubusercontent.com/assets/416575/5893322/271367da-a494-11e4-8c1f-07aac9bcecb2.png)

**Comment by alexcrichton** [comment]
Thanks @frewsxcv!
