### ISSUE TITLE
Make check_match not copy the AST

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#17253]
After https://github.com/rust-lang/rust/pull/13316 check_match is a major bottleneck in the cycle time of rustc taking 4 times more time than it did before (18-19 s vs 4.5 s).

The main problem is the static inliner which creates new AST nodes. It should be possible to make it not do that.

**Comment by steveklabnik** [comment]
This is an old bug, and the original reporter is gone, and the compiler has gone through a ton of stuff, so just closing.
