### ISSUE TITLE
need to test with more OSX versions

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#17269]
Recent changes landed that broke Rust on Mac OS 10.9 (Mavericks) and above, see https://github.com/rust-lang/rust/issues/17214

The problem is that the linker is being passed an argument that works for `gcc`, but that `clang` rejects. (Mac OS moved wholesale to `clang` in 10.9, it appears.)

Unfortunately, this breakage wasn't caught by bors. Apparently the testing infrastructure is running an older version of Mac OS and therefor using `gcc` rather than `clang`.

To avoid surprise Mac OS breakage in the future, we should make sure to test against `clang` before landing PRs.

cc @brson @kballard @pnkfelix

**Comment by steveklabnik** [comment]
Triage: no change here so far.

**Comment by pnkfelix** [comment]
@freebroccolo doesn't xcode-select change the default xcode system-wide?  I had inferred that what brson wanted was to be able to switch in a local manner. ..

(Or maybe it doesn't matter;  I don't know enough about how well our build infrastructure is virtualized for Mac hosts)

**Comment by brson** [comment]
changing xcode system wide would be sufficient *if* we limited build concurrency to 1

**Comment by freebroccolo** [comment]
@pnkfelix yes, as far as I remember it does. There may be another way to switch versions nicely that isn't system wide in this fashion but I don't know of it.

**Comment by ranma42** [comment]
The [manpage](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/xcode-select.1.html) of xcode-select suggests an alternative to `xcode-select --switch`:

> To set the path without superuser permissions or only  for  the  current  shell session, use the DEVELOPER_DIR environment variable instead

**Comment by alexcrichton** [comment]
Will make a new metabug around this soon
