### ISSUE TITLE
Run the borrow checker before the type checker

### ISSUE THREAD

**Issue by bfops** [rust-lang/rust#17261]
I haven't put too much thought into this, and it's probably not doable, but is there any way the borrow checker could run *before* the type checker?

I find on a semi-regular basis that I spend a lot of time juggling types around, only to have the borrow checker reveal some flaw in my design anyway, so I end up re-writing a bunch of code and going through a bunch of type juggling again.

**Comment by bfops** [comment]
(I'm realizing now this was probably worth throwing onto discourse. Whoops).

**Comment by steveklabnik** [comment]
Yes, that's probably a better place. Let's close this for now, then.

**Comment by nikomatsakis** [comment]
I agree it might be nice, but the borrow checker really relies on knowing types for everything to do its job.
