### ISSUE TITLE
fs::mkdir returns OtherIoError instead of PathAlreadyExists

### ISSUE THREAD

**Issue by retep998** [rust-lang/rust#17287]
When creating a directory on windows using `fs::mkdir`, if the directory already exists it returns an error where `kind` is `OtherIoError ` instead of `PathAlreadyExists` as I would expect.

**Comment by steveklabnik** [comment]
`fs::create_dir` now returns a `ErrorKind::PathAlreadyExists`, so this has been fixed. woo!
