### ISSUE TITLE
doc: Make search more prominent

### ISSUE THREAD

**Issue by treeman** [rust-lang/rust#17296]
Currently we have to click a small link under [The standard library](http://doc.rust-lang.org/#the-standard-library) to be able to search, which I do a *lot*. It should be easier to find the search function.

Perhaps a direct link or a search box at the top of <http://doc.rust-lang.org/> would be good.

**Comment by steveklabnik** [comment]
Closing as dup of https://github.com/rust-lang/rust/issues/14572
