### ISSUE TITLE
Thread crashes if Receiver is used

### ISSUE THREAD

**Issue by vhbit** [rust-lang/rust#17308]
Here is a test case:

``` rust
use std::rt::thread::Thread;

fn write_loop(rx: Receiver<uint>) {
    loop {
        match rx.recv_opt() {
            Ok(v) => println!("v {}", v),
            _ => break
        }
    }
}

fn main() {
    let (tx, rx) = channel();
    Thread::start(proc() {
        write_loop(rx);
    });
    
    tx.send(3u);
}
```

Output: `fatal runtime error:  assertion failed: !ptr.is_null()`

I guess that's because there is no `Task` associated with thread and while it is possible to create a task manually - there is no known for me way to put `Runtime` into it. 

Considering there is no direct way to guess what for this thread is created and whether it should use native runtime or not, it is reasonable. But it is still quite unexpected, so I believe there should be either a way to put runtime into it or documentation of `Receiver` should note that more clearly.

**Comment by steveklabnik** [comment]
This does not crash today:

```
use std::thread::Thread;
use std::sync::mpsc::Receiver;
use std::sync::mpsc::channel;

fn write_loop(rx: Receiver<uint>) {
    loop {
        match rx.try_recv() {
            Ok(v) => println!("v {}", v),
            _ => break
        }
    }
}

fn main() {
    let (tx, rx) = channel();
    Thread::scoped(move || {
        write_loop(rx);
    }).join();

    tx.send(3u);
}
```

Compiles and runs, though it has no output.
