### ISSUE TITLE
proper ctags support for rust

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#1731]
Currently we have basic ctags support via regex.  It'd be cool to implement a custom module, as described here:

http://ctags.sourceforge.net/EXTENDING.html

In particular, this should make it possible to extract field and variant names from type declarations.

**Comment by steveklabnik** [comment]
Given that most users are going to be using an external package for ctags, and those exist, I'm giving this a close. If more advanced ctags support for actually hacking on the compiler was important, someone would have added them by now.
