### ISSUE TITLE
macros cannot be marked with stability attributes

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#17316]

**Comment by steveklabnik** [comment]
Traige: as @pnkfelix mentions, this isn't a big deal for the standard library. Plus, stability attributes aren't currently used by any non-stdlib crates, making this a further non-issue. However, a future ecosystem stability system would have to take this into account.

**Comment by steveklabnik** [comment]
Given that this would be a concern of an RFC for the external stability system, I'm giving it a close.
