### ISSUE TITLE
Can't borrow different members of a field with overlapping lifetimes?

### ISSUE THREAD

**Issue by jasom** [rust-lang/rust#17345]
Example here:
https://gist.github.com/jasom/b4d9304c13120153534e

This worked for a long time, but at some point in the past few months stopped working in the nightlies.  Is this an itnentional change?

**Comment by steveklabnik** [comment]
@nikomatsakis is this true/correct?

**Comment by apasel422** [comment]
As far as I know, this is correct, though the error message could suggest the mutable reference solution.

**Comment by steveklabnik** [comment]
Updated code:

```
#![feature(box_syntax)]
#![feature(box_patterns)]
struct ExternalNode {
    key: i32,
    value: i32
}

fn main() {
    let mut boxed_node = box ExternalNode{ key : 1, value: 2};

    match boxed_node {
        box ExternalNode{key : ref fkey, value: ref mut val} => {
            *val+=1;
        }
    }

}
```

Yes, as far as I know, @apasel422 and @bkoropoff are correct that this is intended behavior, so giving a close.

**Comment by nikomatsakis** [comment]
I think this is ... mostly true. We did make some effort to remove the compiler's special knowledge of `box`. However, the precise desugaring of `box` patterns is a bit unclear, and I could see that the example starts working in the future (e.g., once we are doing borrow checking on MIR). But I think it's ok to close.
