### ISSUE TITLE
32-bit nightlies are not being tested

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#17344]
The OSX and Linux nightly builders are not testing the 32-bit nightlies because they're only testing the 64-bit nightlies.

The most recent 32-bit cargo builds instantly segfault, which leads me to believe that there may be codegen bugs?

**Comment by steveklabnik** [comment]
@alexcrichton @brson @edunham is this still true today?

**Comment by alexcrichton** [comment]
Yes, this is still an issue

**Comment by brson** [comment]
Whatever.
