### ISSUE TITLE
random access iterators should implement a better version of nth()

### ISSUE THREAD

**Issue by awelkie** [rust-lang/rust#17348]
Right now, the Items struct uses the default version of the `nth` method for Iterators. But this makes repeated calls to `next()`, which is unnecessary for Items. The Items struct should use it's own version that skips directly to the `n`th offset element.

**Comment by frewsxcv** [comment]
Which 'Items struct' are you referring to?

**Comment by Gankro** [comment]
This is likely in reference to what is now `std::vec::Iter`, but really it's applicable to all RandomAccessIterators. There's some mumbling of just dropping RAI as a trait for now pending better design/motivation (it's current marked as unstable iirc).

**Comment by steveklabnik** [comment]
`RandomAccessIterator` is now gone, so closing.
