### ISSUE TITLE
Create a tool for testing all cargo packages against arbitrary builds of Rust

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#17357]
Related to https://github.com/rust-lang/rust/issues/1453 but more specific. Travis is probably sufficient at this point for the purposes of general community CI, but I want even more control. In order to maintain our stability promises when making feature and API changes we will want a way to run experiments on a broad base of packages, against arbitrary revisions of Rust (e.g. *before* commiting to nightly/beta).

This does have a lot of overlap with general Travis support since cargo packages will want to be able to test against all release channels. I'm not sure whether this integrates with Travis or is a separate tool.

cc @alexcrichton @aturon @nikomatsakis

**Comment by brson** [comment]
Nominating because I want to have this working by the time we have stable builds.

**Comment by edunham** [comment]
Does Crater resolve this issue?

**Comment by alexcrichton** [comment]
I believe it does!

:confetti_ball:
