### ISSUE TITLE
manual does not document "object-methods cannot be type-generic" restriction

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#17367]
While trying to clarify a somewhat important detail about the language, I discovered that this detail was not documented in the language reference manual:

> You cannot mix dynamic dispatch with generic methods.  (This is because we implement generic methods by monomorphization, i.e. by creating separate copies of the implementation for each instantiation -- but with dynamic dispatch, we do not know a priori what all of the calls to the method will be.)

> I would link a relevant portion of the Rust manual here, but I cannot actually find documentation of this restriction.

https://mail.mozilla.org/pipermail/rust-dev/2014-September/011131.html

**Comment by steveklabnik** [comment]
I'm not sure what to actually write, do you have any suggestions? This just seems natural to me: one way does one thing, another way does another. I'm not sure how I'd call out this kind of behavior.

**Comment by steveklabnik** [comment]
We now document  dynamic and static dispatch pretty thoroughly, so I'm giving this a close.
