### ISSUE TITLE
rustc's munging of PATH environment is racy when run in parallel

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#17360]
Mentioned in https://github.com/rust-lang/rust/issues/17327, there are two places where rustc sets and resets `PATH`. Doing this means that running multiple compilations in parallel will stomp on each others' environment variables. This can happen, e.g. in rustdoc which runs tests by driving rustc directly. The proper way to set the environment for subprocesses is through the process Command type.

cc @vadimcn

**Comment by steveklabnik** [comment]
Triage: In #17327, @alexcrichton mentions this block of code: https://github.com/rust-lang/rust/blob/1661947014fc2ecbbb7a30b1604499500dcf767e/src/librustc_driver/driver.rs#L516-L522

It looks like this code still doesn't prevent adding to the path over and over again.

**Comment by alexcrichton** [comment]
I believe we've been seeing this a lot recently as #33844, which is spurious test failures from *something* being too big, and it's probably environment variables (#17327 coming back to haunt us)
