### ISSUE TITLE
from_utf8 should take BytesContainer

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#17375]
`std::str::from_utf8` takes `&[u8]` which means that you can't create a string from a `&[c_char]` in general.

Instead, from_utf8 should look like this:
```rust
pub fn from_utf8<T: BytesContainer>(v: &T) -> Option<&str>
```
Then implement BytesContainer for &[i8].

**Comment by steveklabnik** [comment]
http://doc.rust-lang.org/nightly/std/str/fn.from_utf8.html still takes a `&[u8]`, and is marked as stable, and so would need an RFC to change.
