### ISSUE TITLE
libtime locale values

### ISSUE THREAD

**Issue by saosebastiao** [rust-lang/rust#17374]
libtime currently uses what appears to be en_US.UTF8 locale definitions hardcoded into the strftime/strptime functions. 

https://github.com/rust-lang/rust/blob/master/src/libtime/lib.rs#L512-L548

These values should be derived from system-level locale definitions, such that they can be used in different locales correctly. However, I'm not sure how this would work for different operating systems/architectures. Is there a cross-platform standard practice that should guide the design of these parsing/formatting functions?

**Comment by gsingh93** [comment]
This should probably be closed or moved to https://github.com/rust-lang/time

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/time#65
