### ISSUE TITLE
enable backtraces by default and stop injecting row / col via a macro

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#17386]
The row and column aren't usually useful, because there's no context. An error pointing to `unwrap` is almost completely useless. On platforms where backtraces are already working, it should replace the current failure messages. Failure indicates a logic error (bug) and context is important for tracking it down.

An `abort` would be far more usable because it provides a whole core dump including a backtrace with all of the local variables.

Relocations from the bloated failure messages are the cause of over 50% of the time taken by `rustc` for hello world on Windows. It's much less ridiculous on other platforms, but the bloat is still a very serious performance issue in many performance critical parts of the standard libraries and in user code.

**Comment by steveklabnik** [comment]
A change of this magnitude, these days, requires an RFC. We have two competing ones open right now: https://github.com/rust-lang/rfcs/pull/2091 and https://github.com/rust-lang/rfcs/pull/2154

I'm going to close this in favor of those.
