### ISSUE TITLE
File change events.

### ISSUE THREAD

**Issue by 3Hren** [rust-lang/rust#17389]
Seems like there is no way to subscribe for filesystem changes.

For example to implement tail-like program, I need to watch over some specified file and reread it on write event.

According to [this](http://nikhilm.github.io/uvbook/filesystem.html) libuv has already wrapped common file change notification libraries, so I don't think it will consume significant amount of time to write another wrapper for that libuv functionality.

**Comment by kmcallister** [comment]
With libuv gone there is no reason for this to be in the stdlib.  There are a few file change notification libraries on crates.io already.
