### ISSUE TITLE
ICE while building rustc on FreeBSD: assertion failed: self.raw.hash != self.hashes_end

### ISSUE THREAD

**Issue by veddan** [rust-lang/rust#17391]
Building rustc on FreeBSD fail with an ICE during stage1:

    cfg: build triple x86_64-unknown-freebsd
    cfg: host triples x86_64-unknown-freebsd
    cfg: target triples x86_64-unknown-freebsd
    cfg: enabling more debugging (CFG_ENABLE_DEBUG)
    cfg: host for x86_64-unknown-freebsd is x86_64
    cfg: os for x86_64-unknown-freebsd is unknown-freebsd
    cfg: using CC=ccache clang (CFG_CC)
    cfg: using CXX=clang++ (CFG_CXX)
    cfg: disabling valgrind due to its unreliability on this platform
    cfg: no lualatex found, deferring to xelatex
    cfg: no xelatex found, deferring to pdflatex
    cfg: no pdflatex found, disabling LaTeX docs
    cfg: no pandoc found, omitting PDF and EPUB docs
    cfg: no llnextgen found, omitting grammar-verification
    rustc: x86_64-unknown-freebsd/stage0/lib/rustlib/x86_64-unknown-freebsd/lib/librustc
    task 'rustc' failed at 'assertion failed: self.raw.hash != self.hashes_end', /usr/home/rustbuild/src/rust-buildbot/slave/snap3-bsd/build/src/libstd/collections/hashmap/table.rs:743
    stack backtrace:
       1:          0x1b9ea00 - rt::backtrace::imp::write::ha5f69c9fae9548fd1Iq
       2:          0x1ba1a80 - failure::on_fail::hc7ab01eee1e04860t4q
       3:          0x1bc03c0 - unwind::begin_unwind_inner::h06474350b1d0d0e0RSd
       4:          0x1921ac0 - unwind::begin_unwind::h8803629750811694740
       5:          0x1926f20 - std..collections..hashmap..table..RawTable<ast..Name,codemap..Span>::glue_drop.44244::h99c601ec3eabf587
       6:          0x1928030 - local_data::TLDValue::new::d::h14987804644157393031
       7:          0x1bbd920 - core..option..Option<Box<collections..treemap..TreeNode<uint,local_data..TLDValue>>>::glue_drop.6521::h160d2d3587194201
       8:          0x1bbd920 - core..option..Option<Box<collections..treemap..TreeNode<uint,local_data..TLDValue>>>::glue_drop.6521::h160d2d3587194201
       9:          0x1bbe6a0 - task::Task::cleanup::closure.6628
      10:          0x1bc0f70 - rust_try_inner
      11:          0x1bc0f60 - rust_try
      12:          0x1bbe2d0 - unwind::try::h6c3c06fb2bf83c5azHd
      13:          0x1bbe140 - task::Task::run::hf4b7ebbf0af10e51RXc
      14:          0x1bbe3e0 - task::Task::cleanup::hbd385068572a3c547Zc
      15:          0x1bbe640 - task::Task::destroy::h9fca9728edc516d8HZc
      16:           0x460660 - task::spawn_opts::closure.8450
      17:          0x1bbf590 - thread::thread_start::h06464c46ccf096cb3hd
      18:        0x8025a3370 - <unknown>
      19:                0x0 - <unknown>
    error: internal compiler error: unexpected failure

`uname -a` gives `FreeBSD pcbsd 10.0-RELEASE-p15 FreeBSD 10.0-RELEASE-p15 #0: Wed Jul  9 15:46:53 UTC 2014     root@amd64-builder.pcbsd.org:/usr/obj/usr/src/sys/GENERIC  amd64`

**Comment by steveklabnik** [comment]
Does this still happen today?

**Comment by pczarn** [comment]
I'm getting the same ICE on linux, but during compiling stage2's libcore.

**Comment by pczarn** [comment]
@veddan, does this happen with system LLVM, enabled by passing `--llvm-root` to `configure`? If so, it's most likely the cause.

**Comment by veddan** [comment]
@pczarn, @steveklabnik  this no longer happens to me. A plain `./configure && gmake` produces a functioning `rustc`.

**Comment by steveklabnik** [comment]
@pczarn does this still reproduce for you?

**Comment by pczarn** [comment]
No, not since a while, even with system LLVM.

**Comment by steveklabnik** [comment]
Okay, I'm going to close then. If anyone can reproduce this, please let me know!
