### ISSUE TITLE
inner margin too small on printed web pages

### ISSUE THREAD

**Issue by RichMorin** [rust-lang/rust#17426]
I just printed out a few hundred pages of Rust documentation (eg, manual, tutorial, guides). I'm quite impressed, in general, but I was a bit annoyed by the fact that the horizontal margins are too small to allow safe punching for 3-ring binders.

Please consider adding about 0.25" to the inner margin of the printed CSS format throughout the Rust documentation offerings.  If need be, the point size could be reduced a bit so that the total amount of paper remains the same.

-r

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/21962 should have addressed this.
