### ISSUE TITLE
Android now requires PIE executables

### ISSUE THREAD

**Issue by DanAlbert** [rust-lang/rust#17437]
Android's linker no longer supports non-PIE executables: https://android-review.googlesource.com/#/c/93842/

    # Rust hello world on ToT AOSP:
    $ adb shell /data/local/tmp/hello
    error: only position independent executables (PIE) are supported.

**Comment by lahwran** [comment]
this issue should be closed, as there is a commit in that fixes it and says "closes". I'm not sure why it's not.

**Comment by lahwran** [comment]
except maybe not, because it still happens on latest rust. what gives?

**Comment by lahwran** [comment]
workaround, since it still seems to be broken: pass `-C link-args=-pie` to rustc.

**Comment by pakoito** [comment]
Can anyone please update https://github.com/rust-lang/rust-wiki-backup/blob/master/Doc-building-for-android.md to reflect this change, as the build with cargo section hack seems not to be necessary anymore

**Comment by lahwran** [comment]
That's not the actual wiki, but I'll update the wiki

**Comment by lahwran** [comment]
Except wait. where did the wiki go?

**Comment by pakoito** [comment]
My point precisely.

**Comment by lahwran** [comment]
In that case, nope. :(
