### ISSUE TITLE
Dividing by 0 is possible in statics.

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#17460]
```rust
static X: uint = 1/0;
```
compiles just fine and gives me `X=0`.
```rust
static X: [uint, ..1] = [0];
static Z: uint = X[1/0];
```
does not compile because I'm trying to divide by 0.

And that's because constant expressions get evaluated in two disconnected places depending on the operations they contain.

**Comment by pnkfelix** [comment]
Assigning P-high, not 1.0.
