### ISSUE TITLE
Weird parse error when writing a lifetime-bounded trait object in the wrong order

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#17487]
The following code
```Rust
trait Tr {}
struct S<'a>(&'a 'static+Tr);
```

gives the following weird error
```
<anon>:2:18: 2:25 error: expected type, found token LIFETIME(ast::Ident{name: ast::Name(3u32), ctxt: 0u32})
<anon>:2 struct S<'a>(&'a 'static+Tr);
```

If you write the bounds in the reverse order
```Rust
trait Tr {}
struct S<'a>(&'a Tr+'static);
```

It works.

**Comment by steveklabnik** [comment]
This now says "expected type, found 'static", which is better. I'm not sure if it's good enough though.

**Comment by steveklabnik** [comment]
It has been over a year, nobody else has mentioned this issue, and the error message, while it could be a bit better, is at least reasonable now. As such, I'm going to close this one as "wontfix".
