### ISSUE TITLE
Support the x32 ABI on Linux

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#17493]
The [x32 ABI](http://en.wikipedia.org/wiki/X32_ABI) provides the various benefits of native AMD64 mode while cutting memory use for pointers in half, for programs that don't need more than 4 GB of address space.

**Comment by steveklabnik** [comment]
Traige: no update here that I'm aware of

**Comment by steveklabnik** [comment]
Moving to the RFC repo: https://github.com/rust-lang/rfcs/issues/1339
