### ISSUE TITLE
Confusing error mentions lifetimes while problem is mutability?

### ISSUE THREAD

**Issue by wizeman** [rust-lang/rust#17526]
If I try to compile the following (useless) code:

```rust
pub struct ObjRef<'a> {
    r: &'a int
}

impl<'a> ObjRef<'a> {
    pub fn get_obj(&'a mut self) -> &'a int {
        self.r
    }
}

pub struct ObjIter<'a> {
    x: &'a int
}

impl<'a> Iterator<ObjRef<'a>> for ObjIter<'a> {
    fn next(&mut self) -> Option<ObjRef<'a>> {
        Some(ObjRef { r: self.x })
    }
}

fn test(iter: &mut ObjIter) {
    for obj_ref in iter {
        let obj = obj_ref.get_obj();
    }
}

fn main() {
}
```

... the compiler gives me this error message:
```rust
main.rs:23:19: 23:26 error: `obj_ref` does not live long enough
main.rs:23         let obj = obj_ref.get_obj();
                             ^~~~~~~
main.rs:21:29: 25:2 note: reference must be valid for the anonymous lifetime #2 defined on the block at 21:28...
main.rs:21 fn test(iter: &mut ObjIter) {
main.rs:22     for obj_ref in iter {
main.rs:23         let obj = obj_ref.get_obj();
main.rs:24     }
main.rs:25 }
main.rs:22:25: 24:6 note: ...but borrowed value is only valid for the block at 22:24
main.rs:22     for obj_ref in iter {
main.rs:23         let obj = obj_ref.get_obj();
main.rs:24     }
error: aborting due to previous error
```

However, if I remove the "mut" keyword from the following line, the code compiles fine:
```rust
    pub fn get_obj(&'a mut self) -> &'a int {
```

It took me a long time to figure this out, because my code was more complex and I thought the problem was related to how lifetimes were defined in my structures or functions, since at no point the compiler indicated that the problem could be related to mutability.

Note that if I compile this *very* similar code instead:
```rust
pub struct ObjRef<'a> {
    r: int
}

impl<'a> ObjRef<'a> {
    pub fn get_obj(&'a mut self) -> &'a int {
        &self.r
    }
}

pub struct ObjIter<'a> {
    x: &'a int
}

impl<'a> Iterator<ObjRef<'a>> for ObjIter<'a> {
    fn next(&mut self) -> Option<ObjRef<'a>> {
        Some(ObjRef { r: *self.x })
    }
}

fn test(iter: &mut ObjIter) {
    for obj_ref in iter {
        let obj = obj_ref.get_obj();
    }
}

fn main() {
}
```

... I get a much more useful error message:
```rust
main.rs:23:19: 23:26 error: cannot borrow immutable local variable `obj_ref` as mutable
main.rs:23         let obj = obj_ref.get_obj();
                             ^~~~~~~
error: aborting due to previous error
```

The only apparent main difference between the two pieces of code is that the "r" field of ObjRef is a borrowed pointer to an "int" in the first example, while it's simply an "int" in the second example.

It's also unintuitive to me (as a user) how changing implementation details of a struct and a function, i.e., changing the struct field from a borrowed int to an int, can lead to a different compiler error in an external user of the function considering that the function signature did not change.

**Comment by steveklabnik** [comment]
It seems this bug is fixed, but I'm tagging 'lifetimes' in case that example is wrong.

**Comment by steveklabnik** [comment]
It doesn't look like there's anything to do to fix this issue, so I'm giving it a close.
