### ISSUE TITLE
Confusing error message with vec!

### ISSUE THREAD

**Issue by comex** [rust-lang/rust#17522]
```
fn main() {
    let _: () = vec!(1, 2, 3);
}
```
yields:
```
<std macros>:6:9: 6:14 error: mismatched types: expected `()`, found `collections::vec::Vec<<generic integer #0>>` (expected (), found struct collections::vec::Vec)
<std macros>:6         _temp
                       ^~~~~
<std macros>:1:1: 9:2 note: in expansion of vec!
huh.rs:2:17: 2:31 note: expansion site
error: aborting due to previous error
```

Although it does give the location of the `vec!` invocation in the backtrace, the sudden appearance of `_temp` and `<std macros>` is still confusing.  It would be better if the line of code shown in the error message were my own.

**Comment by steveklabnik** [comment]
Yes, this does feel like the same thing. This is a consequence of using a macro.
