### ISSUE TITLE
"error: illegal recursive type; insert an enum or struct in the cycle, if this is desired" not very helpful

### ISSUE THREAD

**Issue by imbaczek** [rust-lang/rust#17539]
I've tried to write code that would work like this:

``` rust
let mut f = some_fn;  // many other some_fns also exist

loop {
    f = f()
}
```

To make coding some_fn and its friends easier, I wanted to create a type:

``` rust
type SomeFn = fn() -> SomeFn;
```

Unfortunately, this results in some type-theoretic error message that isn't really understandable by mere mortals:

```
<anon>:1:15: 1:29 error: illegal recursive type; insert an enum or struct in the cycle, if this is desired
<anon>:1 type SomeFn = fn() -> SomeFn;
                       ^~~~~~~~~~~~~~
```

It's not at all clear what 'the cycle' is and where to insert an enum or struct. Turns out that if you know what the compiler is talking about, the fix is simple:

``` rust
struct SomeFn(fn() -> SomeFn);

// ergonomy suffers
fn fn1() -> SomeFn { println!("1"); SomeFn(fn2) }
fn fn2() -> SomeFn { println!("2"); SomeFn(fn1) }

fn main() {
    let mut f = SomeFn(fn1);
    f = { let SomeFn(ff) = f; ff() };
    f = { let SomeFn(ff) = f; ff() };
}
```

Output:

```
1
2
```

But I was very confused by the message and tried a contraption like this instead:

``` rust
type SomeFn = fn() -> Option<SomeFn>;
```

A hint in the error message that points the programmer to the right direction would be very helpful. Ergonomy of the solution is also questionable, but at least it compiles.

**Comment by nham** [comment]
If the issue here is just a bad error message, it seems this issue is fixed. Compiling this code:

```rust
type SomeFn = fn() -> SomeFn;
fn main() {}
```

on a recent nightly (`rustc 1.1.0-nightly (4b88e8f63 2015-05-11) (built 2015-05-12)`) results in:

```
iss_17539.rs:1:23: 1:29 error: unsupported cyclic reference between types/traits detected
iss_17539.rs:1 type SomeFn = fn() -> SomeFn;
                                     ^~~~~~
note: the cycle begins when processing `SomeFn`...
note: ...which then again requires processing `SomeFn`, completing the cycle.
error: aborting due to previous error
```

**Comment by steveklabnik** [comment]
Triage: same as @nham reported. I agree that we could improve on 'processing'.

**Comment by estebank** [comment]
Current output is same as above, with new style output:

```
error[E0391]: unsupported cyclic reference between types/traits detected
 --> src/main.rs:1:23
  |
1 | type SomeFn = fn() -> SomeFn;
  |                       ^^^^^^ cyclic reference
  |
note: the cycle begins when processing `SomeFn`...
 --> src/main.rs:1:1
  |
1 | type SomeFn = fn() -> SomeFn;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = note: ...which then again requires processing `SomeFn`, completing the cycle.
```

**Comment by estebank** [comment]
[Current output](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=6597051325da4b1c992545c6897caa27):

```
error[E0391]: cycle detected when processing `SomeFn`
 --> src/main.rs:1:23
  |
1 | type SomeFn = fn() -> SomeFn;
  |                       ^^^^^^
  |
  = note: ...which again requires processing `SomeFn`, completing the cycle
```

**Comment by camelid** [comment]
I have an idea on how to improve this error. @rustbot claim
