### ISSUE TITLE
Confusing error message: dereference of &-pointer

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#17561]
This code:

```rust
fn main() {
    let bar = &5;
    foo(&*bar);
}

fn foo(x: &mut int) -> &int {
    x
}
```

Gives this error message:

```
hello.rs:3:9: 3:14 error: cannot borrow immutable dereference of `&`-pointer as mutable
hello.rs:3     foo(&*bar);
                   ^~~~~
```

This error is correct, but is really complicated. First of all, `&pointer` should probably use 'reference,' the term we've settled on for `&T`. More importantly, it's just a very dense sentence. This came up [in IRC this morning](https://botbot.me/mozilla/rust/2014-09-26/?msg=22376375&page=18).

**Comment by sanxiyn** [comment]
I have a change related to this. For the original test case, do you think this is an improvement?

```
hello.rs:3:9: 3:14 error: mismatched types: expected `&mut isize`, found `&_` (values differ in mutability)
hello.rs:3     foo(&*bar);
                   ^~~~~
```

**Comment by huonw** [comment]
@sanxiyn and I were discussing this on IRC and both of us have seen a lot of people tripped up by this, possibly even the most common beginner mistake in Rust.

**Comment by steveklabnik** [comment]
With #21424 merged, this is the error:

```
hello.rs:3:17: 3:22 error: cannot borrow immutable borrowed content as mutable
hello.rs:3             foo(&*bar);
                           ^~~~~
```

Seems good!
