### ISSUE TITLE
update the android builder's Android version

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#17578]
Android does have a working thread-local register / emulation for `#[thread_local]` but the bot does not.

Note that due to #17437 (Android now requires PIE), #17448 has to land before it can be updated.

**Comment by lahwran** [comment]
has the bot been updated? what's the status of this? how difficult would it be to update?

**Comment by tamird** [comment]
As of this writing the bots are running API 18.

**Comment by alexcrichton** [comment]
Closing, we actually ended up going back to Android API level 9 for Servo

**Comment by alexcrichton** [comment]
er, for Gecko
