### ISSUE TITLE
Compile error using re-exported empty generic struct from another crate

### ISSUE THREAD

**Issue by tomassedovic** [rust-lang/rust#17591]
I've defined a unit-like struct that is generic over one type (`Phantom<T>`) in an inner module of a library. It is then re-exported from the root module. Instantiating it within the library works fine, but trying to use it from a program that links to the library results in a compile error.

library `foo.rs`:
```
pub use inner::Phantom;

pub mod inner {
    pub struct Phantom<T>;
}
```

binary `main.rs`:
```
extern crate foo;

use foo::Phantom;

struct A;

fn main() {
    Phantom::<A>;
}
```

compile error:
```
$ rustc --crate-type lib foo.rs && rustc main.rs -L .
main.rs:8:15: 8:16 error: too many type parameters provided: expected at most 0 parameter(s), found 1 parameter(s) [E0087]
main.rs:8     Phantom::<A>;
                        ^
error: aborting due to previous error
```

For this to trigger, `foo` has to be a separate crate -- if I recreate the same module hierarchy within `main.rs`, it compiles.

If `main.rs` doesn't use the re-export, but accesses the struct directly (`use foo::inner::Phantom`) it also compiles fine.

If I add any fields to the struct, it compiles without any issues as well.

Triggered on:
```
$ rustc --version verbose
rustc 0.12.0-nightly (d64b4103d 2014-09-26 21:47:47 +0000)
binary: rustc
commit-hash: d64b4103d688f38c2e9e2daf966d50beeb383f1e
commit-date: 2014-09-26 21:47:47 +0000
host: x86_64-unknown-linux-gnu
release: 0.12.0-nightly
```

**Comment by nham** [comment]
Triage: testing this now (`rustc 1.2.0-nightly (78c4d5387 2015-05-30) (built 2015-05-31)`)
results in compilation of `foo.rs` failing:

```
lib.rs:4:24: 4:25 error: parameter `T` is never used [E0392]
lib.rs:4     pub struct Phantom<T>;
                                ^
lib.rs:4:24: 4:25 help: consider removing `T` or using a marker such as `core::marker::PhantomData`
error: aborting due to previous error
```

This appears to be consistent with [RFC 738](https://github.com/rust-lang/rfcs/blob/master/text/0738-variance.md), so it seems this issue can be closed.

**Comment by alexcrichton** [comment]
Changing this to use a tuple struct (to use the parameter) has no error, so I do believe this is indeed fixed!
