### ISSUE TITLE
rust compling

### ISSUE THREAD

**Issue by sononix** [rust-lang/rust#17608]
Any one can point me in the right direction - but I cant get past this error

link: x86_64-apple-darwin/rt/librustllvm.a
rustc: x86_64-apple-darwin/stage0/lib/rustlib/x86_64-apple-darwin/lib/librustc
error: linking with `cc` failed: exit code: 1
note: cc '-m64' '-L' '/Users/ms/CODEbase/rust/rust-0.11.0/x86_64-apple-darwin/stage0/lib/rustlib/x86_64-apple-darwin/lib' '-o' 'x86_64-apple-darwin/stage0/lib/rustlib/x86_64-apple-darwin/lib/librustc-a9826c4a-0.11.0.dylib' 'x86_64-apple-darwin/stage0/lib/rustlib/x86_64-apple-darwin/lib/rustc.o' '-lmorestack' 'x86_64-apple-darwin/stage0/lib/rustlib/x86_64-apple-darwin/lib/rustc.metadata.o' '-nodefaultlibs' '-Wl,-dead_strip' '-L' '/Users/ms/CODEbase/rust/rust-0.11.0/x86_64-apple-darwin/stage0/lib/rustlib/x86_64-apple-darwin/lib' '-lgraphviz-c1a03dc9-0.11.0'

trying to build rust but I think something is up with my setup 

My environment consists of 

$ cc -v
Apple LLVM version 6.0 (clang-600.0.51) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.3.0
Thread model: posix

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc49/4.9.1/libexec/gcc/x86_64-apple-darwin13.3.0/4.9.1/lto-wrapper
Target: x86_64-apple-darwin13.3.0
Configured with: ../configure --build=x86_64-apple-darwin13.3.0 --prefix=/usr/local/Cellar/gcc49/4.9.1 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-4.9 --with-gmp=/usr/local/opt/gmp4 --with-mpfr=/usr/local/opt/mpfr2 --with-mpc=/usr/local/opt/libmpc08 --with-cloog=/usr/local/opt/cloog018 --with-isl=/usr/local/opt/isl011 --with-system-zlib --enable-version-specific-runtime-libs --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --disable-werror --with-pkgversion='Homebrew gcc49 4.9.1 --enable-fortran' --with-bugurl=https://github.com/Homebrew/homebrew-versions/issues --enable-plugin --disable-nls --enable-multilib
Thread model: posix
gcc version 4.9.1 (Homebrew gcc49 4.9.1 --enable-fortran) 

$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc49/4.9.1/libexec/gcc/x86_64-apple-darwin13.3.0/4.9.1/lto-wrapper
Target: x86_64-apple-darwin13.3.0
Configured with: ../configure --build=x86_64-apple-darwin13.3.0 --prefix=/usr/local/Cellar/gcc49/4.9.1 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-4.9 --with-gmp=/usr/local/opt/gmp4 --with-mpfr=/usr/local/opt/mpfr2 --with-mpc=/usr/local/opt/libmpc08 --with-cloog=/usr/local/opt/cloog018 --with-isl=/usr/local/opt/isl011 --with-system-zlib --enable-version-specific-runtime-libs --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --disable-werror --with-pkgversion='Homebrew gcc49 4.9.1 --enable-fortran' --with-bugurl=https://github.com/Homebrew/homebrew-versions/issues --enable-plugin --disable-nls --enable-multilib
Thread model: posix
gcc version 4.9.1 (Homebrew gcc49 4.9.1 --enable-fortran)

**Comment by steveklabnik** [comment]
@sononix , I am sorry nobody has ever replied to this ticket. Given that it's almost exactly a year old, I'm going to give it a close, as things are different today. If you're still having build problems, please open up new ones, thank you!
