### ISSUE TITLE
ProcessExit should have method `.code() -> int`

### ISSUE THREAD

**Issue by kballard** [rust-lang/rust#17618]
When a process exits due to a signal, and that process was launched by a shell, the shell typically treats the exit status of the process to be 128 + the signal number. This is true for bash, fish, and zsh (I haven't tested other shells). Based on this, it would be convenient for `ProcessExit` to have a method

```rust
fn code(&self) -> int;
```

that replicates this behavior, in order to make it easier for programs that don't want to have to care about the distinction between a signal and a normal exit.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#787
