### ISSUE TITLE
Move syntax extensions and macros out of compiler

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#1762]
The compiler knows a lot more about syntax extensions than it ever should have. There's a danger that our syntax extensions could become hopelessly intertwined with rustc. We need to get a real plugin mechanism working before it is too late.

Depends on #458. See alse #38.

**Comment by steveklabnik** [comment]
Triage: I think @eddyb was working hard on this, but nothing has come of it yet.

**Comment by eddyb** [comment]
@steveklabnik I completely forgot about it, mostly because I'm trying to use my severely limited time working on actual features.

**Comment by steveklabnik** [comment]
Hehe, no wories, I don't blame you :smile:

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#874
