### ISSUE TITLE
Binary string literals are of type &[u8] instead of &[u8, ..n]

### ISSUE THREAD

**Issue by P1start** [rust-lang/rust#17626]
Intuitively, I would expect `b"abc"` to behave identically to `&[97, 98, 99]`, but it does not: `b"abc"` is of type `&[u8]` instead of `&[u8, ..3]` like `&[97, 98, 99]` is. Changing this to `&[u8, ..n]` would provide more flexibility, as `&[u8, ..n]` can always be converted to `&[u8]`, but not vice-versa.

Presumably this was either intentional or simply forgotten during the slice-related DST changes.

**Comment by nham** [comment]
Just bumping this to note that this still seems to be the case:

    <anon>:2:23: 2:29 error: mismatched types:
     expected `&[u8; 3]`,
        found `&'static [u8]`
    (expected array of 3 elements,
        found slice) [E0308]
    <anon>:2     let c: &[u8; 3] = b"abc";
                                   ^~~~~~

**Comment by P1start** [comment]
This is done. (See #18465.)
