### ISSUE TITLE
min_by requires Ord not PartialOrd

### ISSUE THREAD

**Issue by neunenak** [rust-lang/rust#17648]
It would be handy if Iterator::min_by required PartialOrd instead of Ord. This requirement makes it impossible to use with among other common types f32 and f64, which is annoying. I don't know if the best solution is to simply change the required trait to PartialOrd or to provide some other method min_by_partial_ord or something along those lines. The same reasoning should apply to Iterator::max_by

**Comment by kmcallister** [comment]
I agree that `on` wouldn't be too useful in Rust; I was just spelling out the alternatives.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#675
