### ISSUE TITLE
Can't annotate types as allow(ctypes)

### ISSUE THREAD

**Issue by jdm** [rust-lang/rust#17643]
For the rust-mozjs bindings, we have some types which contain borrowed pointers that we pass to C code that expects structures containing raw pointers. Manually annotating every method that takes these types is really unpleasant; it would be nice to be able to mark the types themselves so FFI methods wouldn't bother warning about them.

**Comment by steveklabnik** [comment]
Triage: no change here.

**Comment by steveklabnik** [comment]
Triage, no change I'm aware of. @jdm is this still a pain point?

**Comment by jdm** [comment]
This is no longer a paint point; I believe a rewrite at some point removed the use of borrowed pointers inside types that we pass to C code.

**Comment by Mark-Simulacrum** [comment]
I'm unable to reproduce this so going to close.
