### ISSUE TITLE
Add linter option to complain about shadowed built-in types

### ISSUE THREAD

**Issue by marijnh** [rust-lang/rust#1766]
Things like `u8` and `bool` can be shadowed now. Being able to see warnings when doing that is probably useful.

**Comment by steveklabnik** [comment]
Triage: nothing has changed. Someone asked for this on IRC a few days ago though.

**Comment by aochagavia** [comment]
This is an error now:

```
$ rustc test.rs
test.rs:6:5: 6:18 error: user-defined types or type parameters cannot shadow the
 primitive types [E0317]
test.rs:6     type u8 = ();
              ^~~~~~~~~~~~~
error: aborting due to previous error
```

**Comment by fhahn** [comment]
There is also a test testing this case: https://github.com/rust-lang/rust/blob/master/src/test/compile-fail/issue-20427.rs

**Comment by steveklabnik** [comment]
Seems good! Thank you @aochagavia and @fhahn !
