### ISSUE TITLE
Zero-sized structs should be FFI-safe

### ISSUE THREAD

**Issue by mzabaluev** [rust-lang/rust#17679]
If I get a struct by pointer from a foreign library, and I know the structure cannot safely be copied because the actual object is larger than the struct, I want to declare it as something like this:
```rust
#[repr(C)]
struct A {
    // ...
    no_copy: std::kinds::marker::NoCopy;
}
```
Now the compiler complains at use site that the struct is not foreign-function-safe.
As the markers are zero-sized, they have no bearing on the layout and no consequences for the structure data, so they, as long as any other zero-sized structures, should not waive FFS.

@thestinger suggests the same should apply to structures with one field as well, but I'm not so certain about that: there could be optimizations regarding alignment which would not be compatible with the (default) C ABI.

**Comment by pornel** [comment]
Related #20660

I'm using 0-sized structures to represent unknown C types (C's `struct foo;` without definition), so I'm hoping that pointers to such structs are OK.

**Comment by thestinger** [comment]
@pornel: Rust has truly opaque types (`enum foo {}`) so there's no need to abuse zero-size types for that.

**Comment by thestinger** [comment]
Raw pointers to *anything* are FFI safe, since they have a uniform representation.

**Comment by pornel** [comment]
@thestinger `enum foo {};` doesn't compile for me: http://is.gd/US1ObL ("expected item, found `;`").

I've been assuming `struct foo;` is more appropriate, since it supports neater syntax without `{}`.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#760
