### ISSUE TITLE
Structures containing borrowed pointers should be FFI-safe

### ISSUE THREAD

**Issue by jdm** [rust-lang/rust#17685]
SpiderMonkey takes a structure like `Handle { ptr: *const *mut JSObject }` as an argument to many functions. For the purposes of safety, Servo represents this as `Handle<'a> { ptr: &'a *mut JSObject }` instead, which is equivalent for the purposes of FFI. This causes approximately one million errors that are really annoying.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#748
