### ISSUE TITLE
std::macros::builtin doesn't document anything

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#17688]
[The rustdoc output](http://doc.rust-lang.org/std/macros/builtin/) says

> These macros do not have any corresponding definition with a `macro_rules!` macro, but are documented here.

but the docs are gone.

**Comment by steveklabnik** [comment]
Very weird.

**Comment by steveklabnik** [comment]
These all seem to be blank now?

**Comment by steveklabnik** [comment]
re-tagging as rustdoc since it's a bug in that

**Comment by sfackler** [comment]
Rustdoc now only documents macros at the crate root. The module itself should just be hidden probably.

**Comment by alexcrichton** [comment]
This has been resolved in the meantime, yay! (the module is now gone)
