### ISSUE TITLE
Strengthen GPL source offer in Windows distribution

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#17691]
When creating the Windows build, we include a ['third-party'](https://github.com/rust-lang/rust/tree/master/src/etc/third-party) directory containing materials intended to provide GPL compliance. The required source offer is written

"You can obtain a copy of the source of these libraries from the MinGW-w64 project{1}.

{1}: http://mingw-w64.sourceforge.net/"

This may not be sufficient to comply with the letter of the license since it does not indicate which source to download to recreate the mingw binaries in the distribution, and it may not be simple to figure out that information from just what is included in the distribution.

**Comment by steveklabnik** [comment]
How often do we require newer versions of mingw? Our current instructions say to install whatever the latest is.

**Comment by brson** [comment]
I have lost my passion for improving this.

**Comment by brson** [comment]
We can fix if anybody ever complains loudly.
