### ISSUE TITLE
Behavior for implemented methods not in scope

### ISSUE THREAD

**Issue by uwap** [rust-lang/rust#17699]
When trying to call a method for an object of an "unusing" (not implemented by `use`) module the compiler will throw out a compile-time error saying `type [Type] does not implemented any method in scope`. The implementation isn't in scope indeed, but I think it should try to inference it, since the object is in scope.  
Here is an example:
```rust
#![feature(globs)]

mod some_mod {
  pub struct Foo;

  pub trait Bar {
    fn foo(&self);
  }

  impl Bar for Foo {
    fn foo(&self) {
      println!("I am Foo!")
    }
  }
}

fn main() {
  //uncommenting the following line will fix the issue
  //use some_mod::*;
  let x = some_mod::Foo;
  x.foo();
}
```
I think I should be able to call x.foo() even if the implementation isn't in scope. It is in the same module as the struct though.  
When implementing the method without implementing a trait it compiles even without the `use some_mod::*;`:
```rust
mod some_mod {
  pub struct Foo;

  impl Foo {
    pub fn foo(&self) {
      println!("I am Foo!")
    }
  }
}

fn main() {
  let x = some_mod::Foo;
  x.foo();
}
```
I guess it should have the same behavior on traits.

**Comment by steveklabnik** [comment]
This is intended behavior, and so I'm going to give it a close. If you want it to attempt to automatically import the trait, that very much would need an RFC, but I'm not sure it would be accepted. That's the right venue to persue this, though.
