### ISSUE TITLE
Confusing term for loop labels in reference doc

### ISSUE THREAD

**Issue by jgallagher** [rust-lang/rust#17716]
The grammar in the reference for `loop` (http://doc.rust-lang.org/reference.html#infinite-loops) uses the word "lifetime" to describe the label, but given that "lifetime" is term that means something very different, it's a little confusing.

Additionally, judging by https://github.com/rust-lang/rust/blob/master/src/libsyntax/parse/parser.rs#L2162-L2176, for loops and while loops also support labels, but that isn't mentioned for them.

**Comment by steveklabnik** [comment]
Given that this name is currently the correct one, I'm giving this a close. If we have a specific way to improve this, we can entertain the notion, but right now, that's the name.
