### ISSUE TITLE
Improve error message when using generic static method incorrectly

### ISSUE THREAD

**Issue by isurakka** [rust-lang/rust#17712]
When trying to call a generic static method like this you get a confusing error.

Code:
```
use std::vec::Vec;

fn main() {
    let mut foo = Vec<32i>::new(); // Remove <32i> to fix
    foo.push(1i);
    println!("{}", foo[0]);
}
```

Error:
```
<anon>:4:19: 4:22 error: unresolved name `Vec`.
<anon>:4     let mut foo = Vec<32i>::new(); // Remove <32i> to fix
                           ^~~
<anon>:4:27: 4:32 error: unresolved name `new`.
<anon>:4     let mut foo = Vec<32i>::new(); // Remove <32i> to fix
                                   ^~~~~
error: aborting due to 2 previous errors
playpen: application terminated with error code 101
```
[playpen](http://play.rust-lang.org/?code=use%20std%3A%3Avec%3A%3AVec%3B%0D%0A%0D%0Afn%20main()%20%7B%0D%0A%20%20%20%20let%20mut%20foo%20%3D%20Vec%3C32i%3E%3A%3Anew()%3B%20%2F%2F%20Remove%20%3C32i%3E%20to%20fix%0D%0A%20%20%20%20foo.push(1i)%3B%0D%0A%20%20%20%20println!(%22%7B%7D%22%2C%20foo%5B0%5D)%3B%0D%0A%7D)

I'm coming from C# where you need to specify the generic type when calling a generic constructor. This was very confusing for me. I would appreciate if the error message was made more informative.

**Comment by dhardy** [comment]
A similar case:

    use std::vec::Vec;
    fn main(){
        let mut v = Vec.new();
        v.push(1);
    }

Replacing `Vec.new()` with `Vec::new()` solves the error, but the message is confusing:

    error: unresolved name `Vec`

**Comment by steveklabnik** [comment]
The error is much better now. Code:

```rust
fn main() {
    let mut foo = Vec<i32>::new(); // Remove <32i> to fix
    foo.push(1);
    println!("{}", foo[0]);
}
```

error:

```text
hello.rs:4:26: 4:33 error: chained comparison operators require parentheses
hello.rs:4         let mut foo = Vec<i32>::new(); // Remove <32i> to fix
                                    ^~~~~~~
hello.rs:4:26: 4:33 help: use `::<...>` instead of `<...>` if you meant to specify type arguments
hello.rs:4:23: 4:26 error: `Vec` is the name of a struct or struct variant, but this expression uses it like a function name [E0423]
hello.rs:4         let mut foo = Vec<i32>::new(); // Remove <32i> to fix
                                 ^~~
```

:+1:
