### ISSUE TITLE
liblibc should let you set errno

### ISSUE THREAD

**Issue by ben0x539** [rust-lang/rust#17714]
`std::os::errno()` doesn't come with a `::set_errno()` variant, but this seems like fairly important functionality for interacting with C code.

There's https://github.com/bnoordhuis/rust-errno/blob/master/errno.rs, but not shipping with support for this is sort of a curious omission that belies Rust's appropriateness for slotting into C systems.

**Comment by steveklabnik** [comment]
moving to https://github.com/rust-lang-nursery/libc/issues/47 now that this is an external crate.
