### ISSUE TITLE
Docs somewhat unclear regarding C-like enum discriminators

### ISSUE THREAD

**Issue by voithos** [rust-lang/rust#17770]
The [reference](http://doc.rust-lang.org/reference.html) states pretty clearly that the memory layout of `struct`s is undefined by default, and presumably the same thing can be said of complex enum variants.

However, for C-like enums (simple enums which correspond to some integer type), it doesn't seem to be clear whether implicit discriminators are well defined. [One resource](https://gist.github.com/brson/9dec4195a88066fa42e6#enumerations) (no longer in the actual docs, it seems) says that they _are_ well defined (starts with 0, increases by 1 for each variant). But I couldn't find any other docs that comment on this (the reference _does_ state that an enum with `#[repr(C)]` will have the default C ABI enum size - but also that enum representation in C is undefined? Is that referring to the implicit discriminators?).

In essence, can we assume that implicit discriminators start with 0 and increase by 1 per variant, or is this never an assumption we can make?

**Comment by steveklabnik** [comment]
Because I suck at reading specs, Twitter helped: https://twitter.com/jckarter/status/554769119438848000

and that's true:

> Each enumerated type shall be compatible with char, a signed integer type, or an unsigned integer type. The choice of type is implementation-defined, 108) but shall be capable of representing the values of all the members of the enumeration. 

Also:

> The expression that defines the value of an enumeration constant shall be an integer constant expression that has a value representable as an int.

and

> An enumerator with = defines its enumeration constant as the value of the constant expression. If the first enumerator has no = , the value of its enumeration constant is 0. Each subsequent enumerator with no = defines its enumeration constant as the value of the constant expression obtained by adding 1 to the value of the previous enumeration constant. (The use of enumerators with = may produce enumeration constants with values that duplicate other values in the same enumeration.) 

So yeah. We should have this in the docs.

**Comment by steveklabnik** [comment]
We now have this text, search for "Enums have a discriminant. ".
