### ISSUE TITLE
Give a better error message for missing :: before type parameters

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#17778]
```rust
fn foo<T>() { }

fn main() {
    foo<int>();
}
```

produces

```
foo.rs:4:9: 4:12 error: unresolved name `int`.
foo.rs:4     foo<int>();
                 ^~~
error: aborting due to previous error
```

because it parses as less-than and greater-than operators.  This often confuses beginners who are coming from C++ (which, by the way, has [its own version](http://www.reddit.com/r/rust/comments/2hthzq/getting_the_size_of_a_type_in_rust/ckvw9zq) of this problem).

We can probably come up with a heuristic which will flag most mistakes of this form and add a "did you mean?" note.

**Comment by alexcrichton** [comment]
This has been fixed in the interim:

```
foo.rs:4:8: 4:15 error: chained comparison operators require parentheses
foo.rs:4     foo<isize>();
                ^~~~~~~
foo.rs:4:15: 4:15 help: use `::<...>` instead of `<...>` if you meant to specify type arguments
error: aborting due to previous error
```

yay!
