### ISSUE TITLE
`core::macros::assert_eq!` should use a `match` to extend the lifetime of the args. 

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#17797]
Same as d3c831ba4a4a2284f73e4f9147aa4900cab56815

`core::macros::assert_eq!` is what you get with:
```rust
#![no_std]

#[phase(link, plugin)]
extern crate core;
```

**Comment by kmcallister** [comment]
Fixed in 73806ddd0fd91066d7b903a00a080cbadcc04311. libcore and libstd now share one definition of this macro.
