### ISSUE TITLE
Get rid of redundancy in type errors

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#17823]
```
error: mismatched types: expected `uint`, found `int` (expected uint, found int)  
```

I guess the parenthetical tells you about the outermost type constructors of the mismatch, e.g. "expected uint, found &-ptr". But in many cases it's redundant.  We should get rid of the parenthetical in cases where it's useless, and then add some explanatory text about what it's trying to tell you.

**Comment by anuragsoni** [comment]
Is anyone working on this? This behavior still happens with the 1.0 stable version. 
![test](https://cloud.githubusercontent.com/assets/5814535/8265509/1c6559b2-16ca-11e5-9db2-ce0ea4ac11cf.png)

**Comment by panyam** [comment]
hey guys is anybody working on this?  Id like to give this a go.  First time contributing to rust so wanted something simple to start off with.

**Comment by christopherdumas** [comment]
@panyam Go ahead! I don't think anybody has though about this in a while, although it might already be fixed, so you might need to make sure.

**Comment by christopherdumas** [comment]
(I did mean to work on this, but it seems it slipped my mind)

**Comment by christopherdumas** [comment]
@panyam Welcome to Rust, by the way! :confetti_ball:

**Comment by panyam** [comment]
@christopherdumas - thanks for that mate...  il give it a go.

**Comment by KalitaAlexey** [comment]
@panyam I want to fix that. Do you mind?

**Comment by KalitaAlexey** [comment]
I have the solution. Who can mentor me. I have some questions.

**Comment by jonas-schievink** [comment]
This is fixed, right?

**Comment by KalitaAlexey** [comment]
Yes.

**Comment by brson** [comment]
Thanks @KalitaAlexey <3
