### ISSUE TITLE
identify traits in libstd that should use associated lifetimes

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#17828]
as a subtask of #17307, once the associated lifetimes part of associated items is implemented, we will want to update libstd to use it.

My google doc from #17826 includes a column for associated lifetimes; I copied the link again below.

Most/all of the cases are related to slice traits, and its possible that they will just go away with other design changes.  I am not sure.

https://docs.google.com/spreadsheets/d/1Y_NAgzEK3FWcG0LjcykyKJEAibSFI3w-v-ekZ4GU8n4/edit?usp=sharing

**Comment by aturon** [comment]
Closing; due to DST, no traits in `std` actually need this.
