### ISSUE TITLE
Add "typechecking" to DynamicLib

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#17833]
We'd produce a metadata table with a `TypeId` hash for each exported symbol and check it in `DynamicLibrary::symbol`. The function will still need to be `unsafe` because there are plenty of ways to deliberately circumvent the check (collisions of the 64-bit hash, hex-editing the .so file, etc) but it will fix the poor user experience of accidental type mismatch when using plugins (in the case of rustc plugins, this is #14841).

We'll also have `DynamicLibrary::raw_symbol` which does no typecheck, gives an `*mut u8`, and can be used with non-Rust .so's.

I plan to work on this after #8157.

**Comment by alexcrichton** [comment]
This is unfortunately fairly unlikely to happen, and we're unlikely to stabilize `DynamicLibrary` as-is, so I'm going to close this as we're not tracking feature requests for various libs in this issue tracker.
