### ISSUE TITLE
Can't use [] to get slice of &mut Vec

### ISSUE THREAD

**Issue by comex** [rust-lang/rust#17831]
let val = &mut vec!(1u);
    let slice1 = val.as_slice(); // OK
    let slice2 = val[]; // error: cannot take a slice of a value with type `&mut collections::vec::Vec<uint>`

(If I `use core::ops::Slice`, `as_slice_()` works but `as_slice()` stops working.  I don't understand how that works either.)

[The RFC](https://github.com/rust-lang/rfcs/blob/master/active/0058-slice-notation.md) says "uses of this notation will auto-deref just as if they were method invocations", so I think this is a bug.

**Comment by steveklabnik** [comment]
Today, this code looks like

```
fn main() {
    let val = &mut vec!(1);
    let slice1 = val.as_slice(); // OK
    let slice2 = &val[]; // er
}
```

and compiles just fine. Note the last `&`.
