### ISSUE TITLE
`precise_time_ns` can overflow on Windows

### ISSUE THREAD

**Issue by rusty-nail2** [rust-lang/rust#17845]
The [last line](https://github.com/rust-lang/rust/blob/ff2616e847ddf913e007d715732b5669b0f22672/src/libtime/lib.rs#L188) of `precise_time_ns` uses a 64 bit multiplication that will overflow frequently.

Using floats would be the easy way out, but it would reduce precision to 53 bits.

**Comment by vadimcn** [comment]
Don't OSX and iOS have a similar problem [here](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/time.rs#L38) and [here](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/time.rs#L64)?
What is the typical value of info.numer?   [This](http://stackoverflow.com/questions/23378063/how-can-i-use-mach-absolute-time-without-overflowing) seems to suggest that is can be large, just like on Windows.

**Comment by vadimcn** [comment]
@pcwalton ^
