### ISSUE TITLE
Factor out the common code in configure script

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#17854]
Rust's configure script contains 4 years of accumulated knowledge, mostly around command line parsing and platform detection. We've copied parts of this script to Cargo's configure script, install.sh and rustup.sh. It would be nice to not duplicate this logic since the implementation of each drifts over time.

cc https://github.com/rust-lang/rust/issues/16456

**Comment by steveklabnik** [comment]
Small update: @alexcrichton 's work to build with Cargo still uses the configure script, so this will still be valid even after that lands https://github.com/alexcrichton/rust/blob/build-via-cargo/configure

No change really, otherwise.

**Comment by alexcrichton** [comment]
This script is now being trimmed down with rustbuild, so I don't think this is relevant any more
