### ISSUE TITLE
avoid having two distinct systems for copying

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#17884]
Since `Copy` doesn't result in an automatic `Clone` implementation, there are two entirely separate systems for doing copies. There are many types providing `Copy` without a corresponding `Clone` implementation and nothing enforces that `Clone` performs the same operation.

Ideally, the trait system could allow an implementation of `Clone` for `T: Copy` without introducing problematic conflicts. If that's not possible, then something else should be done to provide a system that's at least as sane as the story in C++.

**Comment by steveklabnik** [comment]
Talking with @nikomatsakis on IRC, it would seem that there are enough complications with this that we do not plan on doing it. An RFC might be able to resolve them, but probably not. If anyone feels super strongly about this, please persue one.

**Comment by bstrie** [comment]
I would like to hear more about these complications, given that this is still a pain point. Even if we don't want a blanket impl, I'm curious if simple making `#[derive(Copy)]` implicitly also imply `#[derive(Clone)]` would solve most of the problems here.
