### ISSUE TITLE
Use TLS / HSTS for the site, discourse, etc.

### ISSUE THREAD

**Issue by annevk** [rust-lang/rust#17914]
That way active attackers cannot spoof download links for software from insecure pages and credentials cannot be leaked passively from the forums.

https://wiki.whatwg.org/wiki/TLS has more reasons if those are not sufficient.

Endgame: http://hstspreload.appspot.com/

**Comment by frewsxcv** [comment]
Related issue: https://github.com/rust-lang/rust/issues/13180

**Comment by steveklabnik** [comment]
Discourse is now on https, and the earlier issue covers the site, so I'm giving this a close.

**Comment by annevk** [comment]
http://users.rust-lang.org/ does not use HSTS for me (or even redirects to HTTPS).

**Comment by annevk** [comment]
Does site include the blog and the docs?

**Comment by steveklabnik** [comment]
@annevk it does for me...

And yes, the site does include the blog and docs. The docs have HTTPs access, and the site and blog have the same root cause: github pages hosting.

**Comment by annevk** [comment]
I think it does not do a 301 or some such. When I open a fresh browser the initial load does not redirect to HTTPS.

**Comment by steveklabnik** [comment]
Which browser are you using? I'm on Firefox on linux. It still redirects for me.

(and really, this would be an upstream issue, as this change was made by requesting it from discourse /cc @brson @codinghorror)

**Comment by annevk** [comment]
Nightly on OS X. Then Safari (stable) on OS X. Now Chrome dev on OS X.

"Still redirects" is not the problem by the way, that bit works, it's the initial connection which you can only get if you clear your HSTS cache.
