### ISSUE TITLE
Build failing on linux 32-bit

### ISSUE THREAD

**Issue by ursic** [rust-lang/rust#17912]
Linux 3.2.0-4-686-pae
````
error: failed to compress bytecode from i686-unknown-linux-gnu/stage2/lib/rustlib/i686-unknown-linux-gnu/lib/rustc-4e7c5e5c.0.bc
````

**Comment by alexcrichton** [comment]
Lots of time has passed since this was opened, and we've had 32-bit builds on linux going for quite some time, so I'm going to close this since we can't seem to reproduce unfortunately.

**Comment by pnkfelix** [comment]
(could the PAE been an important part of that bug?)
