### ISSUE TITLE
Mobile site text size

### ISSUE THREAD

**Issue by libertyha** [rust-lang/rust#17926]
Hi, 

I believe there is a possible design issue on the mobile site. On the page `doc.rust-lang.org/nightly/intro.html`  (the page that appears after clicking "show me more!" on the home screen) the text is very small for a mobile site. Zooming in and scrolling sideways and then scrolling down is possible but cumbersome. I was using an IPhone 4. 

-Liberty H.A.

**Comment by iKevinY** [comment]
I can confirm that adding the viewport meta tag as @acdha suggested makes the documentation significantly more readable on mobile (iPhone 6 screenshots to round out the iOS device mentions):

![rustdoc](https://cloud.githubusercontent.com/assets/2434728/5641818/3abcd36a-95f4-11e4-863a-3fd4adb8ba81.png)

Text is kind of big in landscape, but I think it would only take a bit of CSS to fix this:

![landscape](https://cloud.githubusercontent.com/assets/2434728/5641905/d492d5e2-95f5-11e4-8062-508ee20bd16f.png)


Pretty much all "mobile-optimized" sites opt for the app-like viewport settings (where zooming is disabled altogether), so my two cents would be to go with the latter of @acdha's two examples.

**Comment by iKevinY** [comment]
This has been addressed in #21133.
