### ISSUE TITLE
Safe access to a `#[thread_local]` should be disallowed

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#17954]
Today this code compiles just fine, but it probably shouldn't:

``` rust
#![feature(thread_local)]
#[thread_local]
static FOO: uint = 3;

fn main() {
    let a = &FOO;
    spawn(proc() {
        println!("{}", a);
    });
}
```

I'm not nominating this because `thread_local` is behind a feature gate, just wanted an issue to track it.

**Comment by steveklabnik** [comment]
Updated code:

```
#![feature(thread_local)]
#[thread_local]
static FOO: usize = 3;

fn main() {
    let a = &FOO;
    let jg = std::thread::spawn(move || {
        println!("{}", a);
    });

    jg.join().unwrap();
}
```

**Comment by bltavares** [comment]
The updated code still compiles on `rustc 1.9.0-nightly (c9629d61c 2016-03-10)`, when it shouldn't.

Code used:

```rust
#![feature(thread_local)]
#[thread_local]
static FOO: usize = 3;

fn main() {
    let a = &FOO;
    let jg = std::thread::spawn(move || {
        println!("{}", a);
    });

    jg.join().unwrap();
}
```

**Comment by eddyb** [comment]
Coming back to this: I think I've come to accept the simpler solution of not giving TLS variables a specific named lifetime but rather the outermost scope of the current function.

That would require banning references from any other statics too.

**Comment by alexcrichton** [comment]
label: T-lang

**Comment by alexcrichton** [comment]
er, meant to add that as a tag...

**Comment by nikomatsakis** [comment]
Removing nomination as it doesn't seem that important to resolve this imminently. It'd be good to have a summary comment though of major points in the thread.

**Comment by nikomatsakis** [comment]
triage: P-medium

**Comment by nagisa** [comment]
## Short summary:

* Is still a problem, thread-local accesses gain the `'static` lifetime;
* Need `'task`/`'thread`/etc lifetime, which is equal to (or smaller than) lifetime of the thread which accesses the thread-local;
* `NoSend`-equivalent is not a solution, because the static may contain some internal fields of which you could still take a `'static` reference of (i.e. `Something(Cell<T>)` → `&'static Cell<T>` and send *that* reference);
* Giving the TLS data accessed the function’s outermost scope lifetime would work¹;

¹: Can’t freely use (e.g. return out of function which accesses the TLS) the reference within the thread either, though?

**Comment by Mark-Simulacrum** [comment]
So since it seems we don't want the `'thread` lifetime (judging by comments on this RFC: https://github.com/rust-lang/rfcs/pull/1705, should we close this as well? It seems we can't implement this without that RFC's thread lifetime, and as such it's not worth keeping this open. Arguably, maybe `#[thread_local]` should be deprecated and removed in favor of `thread_local!`, though I don't know the differences between the two.

**Comment by eddyb** [comment]
I still want the semantics that make thread-local accesses like function arguments: can't let them escape.
In @nagisa's list, it's the last option. IMO the only one we can be certain of soundness for (or at least it allows no more than what `thread_local!` already does) and it's fairly straight-forward to implement.
If you want you can assign to me (famous last words).

**Comment by pythonesque** [comment]
To clarify: IMO it's still important to be able to be able to use thread locals directly, since thread_local! does have significant overhead by comparison.

**Comment by nikomatsakis** [comment]
@pythonesque do you have benchmarks to back that up? IIRC, @alexcrichton gathered various numbers that seemed to suggest the opposite, but I may be mis-remembering.

**Comment by stjepang** [comment]
@nikomatsakis Can confirm that `thread_local!` is slow.

I'm implementing my own channels (similar to `std::sync::mpsc`). When selecting over multiple channels, thread locals are accessed several times. I'm timing 2 million channel selects:

* With `thread_local!`: 200 ms
* With `#[thread_local]`: 130 ms.

The difference is significant enough to be a real-world problem.

**Comment by alexcrichton** [comment]
Yes there's no debate that `thread_local!` has overhead, a [simple example](https://play.rust-lang.org/?gist=9616a817659dba2dc5e98c96c96d96ae&version=nightly) looking at the assembly and the IR will show that. What I gathered previously is that in all use cases we wanted `thread_local!` for in the standard library it had non-measurable overhead.

To actually quantify what's going on here, the `#[thread_local]` version of TLS keys [initializes itself with `None`](https://github.com/rust-lang/rust/blob/master/src/libstd/thread/local.rs#L399) and like all other `thread_local!` variables it's lazily initialized. This forces a branch on all accesses and stores of the TLS variable of "am I initialized yet?" The raw `#[thread_local]` version is obviously initialized as part of the `static`, so this check does not exist. This means that direct `#[thread_local]` will have fewer branches with it.

I do not think we should strive to stabilize `#[thread_local]`. It's *incredibly* not portable which maeks it not too useful for most software. We should strive to improve `thread_local!`. The feature to implement is for the compiler to understand whether the initialization expression is a constant expression or not. If it's a constant expression then we can bypass the `None` storage and "am I initialized checks", making it equivalent to raw `#[thread_local]`

**Comment by stjepang** [comment]
> I do not think we should strive to stabilize `#[thread_local]`. It's incredibly not portable which makes it not too useful for most software. We should strive to improve `thread_local!`. 

Ok, since `#[thread_local]` isn't going to be stabilized, its only purpose is to allow faster implementation of `thread_local!` on some platforms. Can we then fix the soundness issue by making any access to a `#[thread_local]` unsafe and call it a day?

> The feature to implement is for the compiler to understand whether the initialization expression is a constant expression or not.

I like this idea. What would it take to implement this today, or at least what would be the first step forward?

**Comment by eddyb** [comment]
> Can we then fix the soundness issue by making any access to a `#[thread_local]` unsafe and call it a day?

I'll just open a PR with my solution, it shouldn't be hard at all...

> The feature to implement is for the compiler to understand whether the initialization expression is a constant expression or not.

That's easy *in the compiler* but `thread_local!` is not implemented in the compiler.

**Comment by arielb1** [comment]
> That's easy in the compiler but `thread_local!` is not implemented in the compiler.

... But we could add an `eager_thread_local!` macro for that case.

**Comment by alexcrichton** [comment]
@stjepang yeah right now `#[thread_local]` is just an implementation detail essentially of the `thread_local!` macro. Making all access to a `#[thread_local]` static would be fine by me, although I would personally still not advocate for its stabilization, even if this bug were fixed.

As for how to implement a "const expr detection" in a macro I'm not entirely sure. We could either move the implementation into the compiler (which I'd prefer to avoid) or take @arielb1's suggestion of a new macro or a variant of the current macro's syntax.

For example we could "perverse" the meaning via: `thread_local!(const A: i32 = 3);` where `static` in the macro means "lazily initialized, but any expression valid" and `const` means "must be a constant expression". I don't think this is a good idea, but an example of what we might do.

**Comment by stjepang** [comment]
Thanks @eddyb for fixing this issue!

Can we crate a new issue for the optimization part (thread locals initialized by a constant expression should bypass the "am I initialized" check on every access)?

**Comment by eddyb** [comment]
@stjepang Sure, but I'm not sure how to do that cleanly to be honest.
