### ISSUE TITLE
ICE because uninhabited types and drop flags don't mix

### ISSUE THREAD

**Issue by ben0x539** [rust-lang/rust#17987]
enum Foo {}
    impl Drop for Foo {
        fn drop(&mut self) {}
    }
    
    fn main() {
        unsafe { std::ptr::read(&1u8 as *const u8 as *const Foo) };
    }

=> `task 'rustc' failed at 'assertion failed: type_is_zero_size(bcx.ccx(), block_ty)'`

Producing the value of the uninhabited type with `transmute` instead of `ptr::read` works "as expected". Another workaround is, of course, `#![unsafe_no_drop_flag]`. ;)

**Comment by steveklabnik** [comment]
This still ICEs for me today.

**Comment by tamird** [comment]
Still ICEs.

**Comment by steveklabnik** [comment]
This no longer ICEs as of today's nightly.
