### ISSUE TITLE
std::format! auto-dereferences pointers?

### ISSUE THREAD

**Issue by jkleint** [rust-lang/rust#17988]
Is this a 'feature?'
```
fn main() {
    let x = 5i;
    assert_eq!(format!("{}", &x), format!("{:p}", &x));
}
```
```
task '<main>' failed at 'assertion failed: `(left == right) && (right == left)` (left: `5`, right: `0x7fffba8927f8`)', format_ptr.rs:3
```

This is with `rustc 0.13.0-nightly (adb44f53d 2014-10-12 00:07:15 +0000)`.

**Comment by steveklabnik** [comment]
Given that this is intended behavior, I'm giving it a close. If you'd like to change it, please pursue an RFC, thanks!
