### ISSUE TITLE
Add less-allocating args variants

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#18021]
1)
 ```rust
fn argv() -> CVec<*mut u8>
```

2) 
```rust
fn argv() -> Vec<&'static u8>
```

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#862
