### ISSUE TITLE
Document items generated by macros

### ISSUE THREAD

**Issue by stygstra** [rust-lang/rust#18025]
It would be nice if rustdoc allowed items generated by macros to be documented. For example:

```rust
macro_rules! make_fn(
    ($name:ident) => (pub fn $name() {});
)

/// Documentation for do_nothing
make_fn!(do_nothing)
```

I'm not sure of the best way to handle macros that generate multiple items.

**Comment by alexcrichton** [comment]
This is actually more of a language-level issue than a rustdoc-level issue. Doc comments (attributes) are allowed on macro invocations (items) and the compiler does not propagate attributes down into the items expanded by macros (an artifact of today's implementation). As such rustdoc actually has no knowledge of the documentation on the macro itself.

To get rustdoc to recognize the documentation you'll need to attach a doc comment directly to the generated function, probably through the `#[doc]` attribute using the `meta` matcher in macros. This is all working as-intended currently, though, so I'm going to close this.
