### ISSUE TITLE
Bencher::iter should support per-iteration setup

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#18043]
For example, constructing a buffer that will be consumed by the iteration.  This needs to not be counted in the elapsed time, but it's hard to do that without per-iteration timing overhead.

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by dtolnay** [comment]
I would like to track this as part of https://github.com/rust-lang/rfcs/issues/816. That way we keep the standard test framework minimal while allowing libraries to develop more sophisticated custom test and benchmark frameworks with setup and teardown, knobs for number of iterations, access to statistics, control over CPU caches, etc.
