### ISSUE TITLE
StrSlice should have split_at

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#18063]
[`ImmutableSlice` has a `split_at` method](http://doc.rust-lang.org/std/slice/primitive.slice.html#method.split_at). This would probably be useful for [`StrSlice`](http://doc.rust-lang.org/std/str/trait.StrSlice.html) as well.

(It might be a good idea to share some of the other methods between `StrSlice` and `ImmutableSlice` too)

**Comment by Diggsey** [comment]
It would have to make sure not to split the string across a multi-byte codepoint.

**Comment by Manishearth** [comment]
In the context of Rust strings `n` is de facto the Unicode-safe index, not the byte index.

**Comment by Diggsey** [comment]
That would make it inconsistent with the other methods on "str", which use byte indices unless explicitly specified otherwise by the presence of "chars" in the method name.

It would also introduce a hidden complexity cost, making the string version of "split_at" be O(n) instead of O(1) - the obvious use-case of splitting a string at multiple places then becomes O(n^2), which is unnacceptable in many cases.

**Comment by Manishearth** [comment]
`split_at_char` then.

**Comment by djmally** [comment]
I'll take a look into this, if no one else is already.

**Comment by Manishearth** [comment]
Sounds good. @Gankro does this need an RfC?

**Comment by Gankro** [comment]
Uh, what are the traits called now?

**Comment by djmally** [comment]
That was going to be my next question, I think StrSlice is no longer a trait as of 1.0alpha

**Comment by djmally** [comment]
Does this still need to be done (i.e. has the trait been renamed), or should this be closed?

**Comment by steveklabnik** [comment]
http://doc.rust-lang.org/nightly/std/primitive.slice.html#method.split_at <-

**Comment by steveklabnik** [comment]
(that trait no longer exists, and this is an inherent impl now)

**Comment by bluss** [comment]
*.split_at()* on `&str` would be very useful. To be consistent it would use a byte offset though. I'd like this.

**Comment by steveklabnik** [comment]
oh whoops! slice != str slice...

**Comment by huonw** [comment]
http://doc.rust-lang.org/std/primitive.str.html#method.split_at yay!
