### ISSUE TITLE
Filter doc comments from macro input

### ISSUE THREAD

**Issue by Binero** [rust-lang/rust#18076]
This seems to be a very inconsistant issue, but I think it's related to macros. 

Here's an example of a list of comments that don't get parsed properly: 
```rust
bitflags! {
	flags Tests: Test {
    	/// Test
		static TestA = 0x80,
		// TODO: Document this.
		static TestB          = 0x40
	}
}
```
This code will error saying "no rules expected the token `/// Test`". 
http://is.gd/Zkpgvd

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/17830 was merged, so I think this has been fixed.
