### ISSUE TITLE
Possible to put/expose private type in exported/public type signature

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#18082]
### STR

``` rust
mod private {
    pub struct Struct;
}

pub mod public {
    pub struct Struct;
}

struct PrivateStruct;

pub struct Triplet {
    pub left: public::Struct,  // OK public type in exported signature
    //pub middle: PrivateStruct,  // OK private in exported signature is rejected
    //~^ error: private type in exported type signature
    pub right: private::Struct,  // BAD private type in exported signature is accepted
}
```

`rustc --crate-type=lib lib.rs` successfully compiles, but it should error with `error: private type in exported type signature` with span on `pub right: private::Struct`.

Sanity check that `private::Struct` is actually private:

``` rust
extern crate lib;

fn main() {
    let _ = lib::PrivateStruct;  //~ error: struct `PrivateStruct` is private
    let _ = lib::private::Struct;  //~ error: struct `Struct` is private
    let _ = lib::public::Struct;
}
```

Errors (as expected) with:

``` rust
sanity-check.rs:4:13: 4:31 error: struct `PrivateStruct` is private
sanity-check.rs:4     let _ = lib::PrivateStruct;  //~ error: struct `PrivateStruct` is private
                              ^~~~~~~~~~~~~~~~~~
sanity-check.rs:5:13: 5:33 error: struct `Struct` is private
sanity-check.rs:5     let _ = lib::private::Struct;  //~ error: struct `Struct` is private
                              ^~~~~~~~~~~~~~~~~~~~
error: aborting due to 2 previous errors
```
### Version

``` rust
rustc 0.13.0-dev (e4761c85b 2014-10-15 09:57:18 +0000)
```

This is supposed to be banned by [RFC #136](https://github.com/rust-lang/rfcs/blob/master/text/0136-no-privates-in-public.md)

cc @pcwalton

**Comment by steveklabnik** [comment]
Triage: linking error still occurs

**Comment by bluss** [comment]
The "private mod trick" makes this private type/trait in public signature check very optional.

```rust
mod private {
    pub struct Foo;
}
pub fn take_foo(_: private::Foo) { }
```

**Comment by steveklabnik** [comment]
Triage: linking error now goes away, and the program successfully executes.

Given the age of this issue, and that that seems to be the only bug here, I"m going to give this one a close. There has been a lot of discussion around the public-in-private lint, but this isn't the issue tracking any of that.
