### ISSUE TITLE
"use self::..." doesn't work inside of functions

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#18084]
``` rust
fn main() {
    use self::inner::A;
    mod inner {
        pub struct A;
    }
}
```

```
<anon>:2:9: 2:14 error: unresolved import `self::inner::A`. Maybe a missing `extern crate inner`?
<anon>:2     use self::inner::A;
                 ^~~~~
```

This works, so I'm assuming the issue is that `self` doesn't behave correctly inside of an anonymous module:

``` rust
fn main() {
    mod inner {
        pub struct A;
    }
    inner::A;
}
```

**Comment by steveklabnik** [comment]
triage: still true today

**Comment by crumblingstatue** [comment]
A generic solution to refer to the current scope in a use declaration would be more beneficial than an enum-specific solution to this problem.

See https://github.com/rust-lang/rfcs/issues/959

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by steveklabnik** [comment]
Triage: this still fails, but gives an error like https://github.com/rust-lang/rust/issues/54390

**Comment by petrochenkov** [comment]
There's a chance that this will be fixed by `feature(uniform_paths)` on 2018 edition.

**Comment by petrochenkov** [comment]
`self` means "current `mod`" and cannot be changed backward-compatibly, but https://github.com/rust-lang/rust/pull/55884 provides an alternative solution, on 2018 edition import paths are resolved in current scope and
```rust
fn main() {
    use inner::A;
    mod inner {
        pub struct A;
    }
}
```
"just works".
