### ISSUE TITLE
Atomic intrinsics accept all pointer types and fire assertions in llvm

### ISSUE THREAD

**Issue by ben0x539** [rust-lang/rust#18098]
The intrinsics are all just `<T>(&mut T, ...)` etc., so stuff like this is accepted by rustc but fires assertions in llvm:

    std::intrinsics::atomic_xadd(&mut 11f32, 1f32);
    std::intrinsics::atomic_xadd(&mut false, true);
    std::intrinsics::atomic_xadd(&mut main, main);

Aborts with

> atomicrmw operand must have integer type!
  %1 = atomicrmw add float* %0, float 1.000000e+00 seq_cst
 floatLLVM ERROR: Broken function found, compilation aborted!

or

> rust/src/llvm/lib/IR/Instructions.cpp:1295: void llvm::AtomicRMWInst::Init(llvm::AtomicRMWInst::BinOp, llvm::Value*, llvm::Value*, llvm::AtomicOrdering, llvm::SynchronizationScope): Assertion `getOperand(1)->getType() == cast<PointerType>(getOperand(0)->getType())->getElementType() && "Ptr must be a pointer to Val type!"' failed.
Aborted

**Comment by apasel422** [comment]
Still an issue.

**Comment by arielb1** [comment]
Not sure how much of a bug this is - intrinsics are unsafe for a reason.

**Comment by dotdash** [comment]
IMHO, this clearly is a bug. Unsafe should just mean "take care" not "we provide means that make no sense at all", and this seems tobe the latter.

**Comment by Amanieu** [comment]
This has been fixed, the intrinsics now only accept integer types. Incorrect types result in a compiler error instead of an LLVM assert.
