### ISSUE TITLE
Specify that Reader::read does not block if data is available.

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#18106]
The details of this probably depend on the Reader implementation, i.e., what does it mean that data is available.

Some examples:

- A BufferedReader will not call `read` on the contained Reader if the buffer is not empty
- If reading from a file descriptor succeeds but not enough data is returned to fill the buffer, the Reader will not attempt a second read.

If the user wants the whole buffer to be filled (unless we're at EOF), he can use the `try_fill` method which is being introduced in #18059.

**Comment by steveklabnik** [comment]
It would see that this is implementation-specific, yeah. @aturon @alexcrichton is this kind of thing something to specify? /cc https://github.com/rust-lang/rust/issues/21070

**Comment by alexcrichton** [comment]
The current documentation of `Read::read` states:

> This function does not provide any guarantees about whether it blocks waiting for data

The `Read` trait has become much more general and I believe this issue is moot now.
