### ISSUE TITLE
Make warning for having both `#[main]` and `#[start]`

### ISSUE THREAD

**Issue by klutzy** [rust-lang/rust#18115]
Since `#[start]` takes precedence over `#[main]`, `#[main]` is ignored. This may lead to surprising result.
For example, if `#[start]` exists, `rustc --test` produces executable which just runs start function rather than test runner.

It would be good if rustc emits warning if there are too many start-related attributes.

**Comment by steveklabnik** [comment]
closing as dup of https://github.com/rust-lang/rust/issues/11766
