### ISSUE TITLE
Improper instructions produced on i686-unknown-linux-gnu

### ISSUE THREAD

**Issue by alexchandel** [rust-lang/rust#18146]
When cross-compiling a minimal `no_std`/`no_main`/`no_stack_check` program for `i686-unknown-linux-gnu` on OS X 10.10, rustc inserts two anomalous instructions during machine code generation. Notice the call/pop eax just after `.Ltmp2`.

From assembly:

``` asm
ain:
    .cfi_startproc
    pushl   %ebx
.Ltmp0:
    .cfi_def_cfa_offset 8
    subl    $24, %esp
.Ltmp1:
    .cfi_def_cfa_offset 32
.Ltmp2:
    .cfi_offset %ebx, -8
    calll   .L0$pb
.L0$pb:
    popl    %eax
.Ltmp3:
    addl    $_GLOBAL_OFFSET_TABLE_+(.Ltmp3-.L0$pb), %eax
...
```

From disassembly:

``` asm
Disassembly of section .text:Disassembly of section .text.main:
main:
       0:   53                                              pushl   %ebx
       1:   83 ec 18                                        subl    $24, %esp
       4:   e8 00 00 00 00                                  calll   0
       9:   58                                              popl    %eax
       a:   81 c0 03 00 00 00                               addl    $3, %eax
...
```

~~Popping the former frame pointer would seem to destroy the stack frame.~~ Actually what is depicted above just pops an IP; however it does destroy the stack later. Note that it is never re-pushed later in the function.

Now, this is does _not_ happen when rustc instead emits LLVM IR that is separately compiled with clang. The issue occurs in larger code, and since executables produced with this issue segfault in qemu, I'm forced to compile/assemble separately with clang.

**Comment by frewsxcv** [comment]
@alexchandel Are you able to confirm if this is still an issue?

**Comment by steveklabnik** [comment]
I'm going to take that as a no. Let me know if that's wrong, @alexchandel !

**Comment by alexchandel** [comment]
@steveklabnik Just tested with `rustc -C no-stack-check -Z no-landing-pads  bones.rs --target i686-unknown-linux-gnu --emit asm` using `no_core`, still an issue.

**Comment by Mark-Simulacrum** [comment]
With the following, I don't see a popl instruction, so presumably fixed, though I'm not sure. @alexchandel Can you confirm?

`rustc -Z no-landing-pads t.rs --target i686-unknown-linux-gnu`
```rust
#![feature(no_core, lang_items)]
#![no_core]

#[lang = "sized"]
trait Sized {}
#[lang = "copy"]
trait Copy {}

pub fn other() -> u32 { return 0xFFFF; }
pub extern fn ext_other() -> u32 { return 0xAAAA; }
```

emits

```
$ objdump -d ./libt.rlib
In archive ./libt.rlib:

t.0.o:     file format elf32-i386


Disassembly of section .text._ZN1t5other17h5beca376b5805208E:

00000000 <_ZN1t5other17h5beca376b5805208E>:
   0:	b8 ff ff 00 00       	mov    $0xffff,%eax
   5:	c3                   	ret

Disassembly of section .text._ZN1t9ext_other17he734743ecfa92ce9E:

00000000 <_ZN1t9ext_other17he734743ecfa92ce9E>:
   0:	b8 aa aa 00 00       	mov    $0xaaaa,%eax
   5:	c3                   	ret
objdump: rust.metadata.bin: File format not recognized
objdump: t.0.bytecode.deflate: File format not recognized
```

**Comment by Mark-Simulacrum** [comment]
Closing, please reopen if this is still an issue.
