### ISSUE TITLE
Add a macro for "unreachable" whose meaning differs in debug and release builds 

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#18152]
In debug builds it means "I *think* we can't get here, please `fail!()` if we do", i.e. the same as the current `unreachable!()`.

In release builds it means "I *promise* we can't get here, LLVM, you are free to do absolutely anything if we can", i.e. `intrinsics::unreachable()`.

Improper use can totally break memory safety in release builds, so we should make it `unsafe`-only even in debug builds.  For the same reason I don't think the current `unreachable!()` should change meaning to this.  I don't have a great alternative name, which I think is the main obstacle with this ticket!

E-easy E-bikeshed :)

**Comment by smaudet** [comment]
Anyone mind if I take a look at this?

**Comment by kmcallister** [comment]
Perhaps it should be `debug_unreachable!()' by analogy with `debug_assert!()` and the like.  It has the same meaning of "unchecked in release builds.

**Comment by vojtechkral** [comment]
This doesn't require an RFC?

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#698
