### ISSUE TITLE
Test output shows non-existing path

### ISSUE THREAD

**Issue by cakebaker** [rust-lang/rust#18158]
I'm following the [Writing Tests](http://doc.rust-lang.org/guide.html#writing-tests) section in the guide. When I run <code>cargo test</code> for the first test (that fails as expected), the last line of the output contains a path that doesn't exist on my system:

    task '<main>' failed at 'Some tests failed', /home/rustbuild/src/rust-buildbot/slave/nightly-linux/build/src/libtest/lib.rs:243

I also don't know what the purpose of this line should be, to me as a newbie it looks redundant to:

    test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured

**Comment by steveklabnik** [comment]
Interesting, it's pointing to a path on the buildbot...

**Comment by steveklabnik** [comment]
These messages have changed in the meantime to remove the buildbot paths, so I'm giving it a close!
