### ISSUE TITLE
"as uint" works on bare constructors of non-C-like enums

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#18154]
rustc 0.13.0-dev (222ae8b9b 2014-10-18 00:47:22 +0000)

```rust
enum Tag {
    Dynamic,
    Inline(u8),
    Static,
}

#[test]
fn f() {
    assert_eq!(Inline as uint, 1);
}
```

compiles and produces

```
task 'f' failed at 'assertion failed: `(left == right) && (right == left)` (left: `140041300628448`, right: `1`)', foo.rs:9
```

I think it's casting the constructor function itself as a function pointer?  But this is *super* confusing behavior (caused a segfault in unsafe code) when I just refactored an enum to be not C-like and I want to get rid of remaining occurrences of `as uint`.

Also it doesn't warn for `as u8`, even though it's too small for a function pointer.

**Comment by bombless** [comment]
>One possible solution is restricting casts from function pointers to uint. We could just say that is not legal but it is legal to cast to a function pointer to an unsafe pointer, and then (continue to) permit unsafe pointers to cast to uints.

+1 for this, but I guess it's too late for 1.0.x

**Comment by arielb1** [comment]
The segfault is gone BTW

**Comment by steveklabnik** [comment]
Updated code:

```
enum Tag {
    Dynamic,
    Inline(u8),
    Static,
}

#[test]
fn f() {
    assert_eq!(Tag::Inline as usize, 1);
}

fn main() {}
```

Still produces the same error.

**Comment by brson** [comment]
Triage: probably impossible to fix this in a satisfying way now, but there may be mitigations. Can we decide the fate here? If we make it a lint, can somebody mentor?

**Comment by steveklabnik** [comment]
> If we make it a lint, can somebody mentor?

New lints need RFCs nowadays.

**Comment by alexcrichton** [comment]
Closed erroneously! (sorry)

**Comment by pnkfelix** [comment]
triage: P-low

**Comment by pnkfelix** [comment]
triage: P-low

**Comment by nrc** [comment]
cc @Manishearth in case he wants to add it to Clippy

**Comment by nikomatsakis** [comment]
I do think a lint is the only fix here.

**Comment by pnkfelix** [comment]
(consensus of compiler team is that this should be *some* form of lint)

**Comment by Manishearth** [comment]
https://github.com/Manishearth/rust-clippy/issues/1116

**Comment by arielb1** [comment]
closing.
