### ISSUE TITLE
Add an assert_size attribute for structs

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#18161]
`size_of` is maybe the top use case for function evaluation in static asserts, which doesn't seem like it will happen any time soon.  We can satisfy this use case with a very simple and self-contained feature, e.g.

```rust
#[assert_size(48)]
struct StringCacheEntry {
    next_in_bucket: *mut StringCacheEntry,
    hash: u64,
    ref_count: AtomicInt,
    string: String,
}
```

I think making this kind of assertion painless will help programs avoid performance regressions.

**Comment by steveklabnik** [comment]
closing in favor of https://github.com/rust-lang/rfcs/pull/591

**Comment by mahkoh** [comment]
I don't see how that RFC solves this issue.
