### ISSUE TITLE
Add a glossary to the Rust Reference

### ISSUE THREAD

**Issue by FreeFull** [rust-lang/rust#18162]
Currently, it's pretty hard to find information about specific constructs such as `type Foo = Bar;` in the Reference unless one already knows in which section, and under which subsection it would be. A glossary of keywords, attributes and other relevant things at the end of the Reference would be massively helpful in finding the information.

**Comment by steveklabnik** [comment]
I'm going to consider this as part of https://github.com/rust-lang/rust/issues/16676 , thanks.
