### ISSUE TITLE
It is not possible to assign a Duration to a const variable

### ISSUE THREAD

**Issue by carllerche** [rust-lang/rust#18166]
The struct fields are currently not pub making it impossible to assign Duration to a const variable.

Given that Duration is essentially `timespec`, it seems like it might be a good idea to make the struct fields public.

cc @aturon

**Comment by steveklabnik** [comment]
This is still true today.

**Comment by steveklabnik** [comment]
Sample program:

```
use std::time::Duration;

const MINUTE: Duration = Duration::new(60, 0);

fn main() {}
```

This is basically always going to be true until `const fn` is stable, since things are now stable, so there's not much we can really _do_ here, so I'm giving this a close.
