### ISSUE TITLE
Add a dedicated search page to Rustdoc

### ISSUE THREAD

**Issue by Gankra** [rust-lang/rust#18168]
Search is lazily loaded after the rest of the content on a given page. This makes searches, especially ones using in-browser search utilities, or jumping through search history really sluggish and unresponsive. A dedicated empty page optimized for this usecase would be _greatly_ appreciated.

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by steveklabnik** [comment]
@rust-lang/rustdoc is this a feature we plan to implement?

**Comment by GuillaumeGomez** [comment]
Isn't the search efficient enough now? If more search functionalities are wanted, we can always add them though.

**Comment by kzys** [comment]
+1 for resolving. Rustdoc is not that slow (or our machines are faster, compared to 2014).

For the standard library, [the landing page](https://doc.rust-lang.org/nightly/) now has a small search box.

**Comment by camelid** [comment]
I'm not quite sure what this issue is requesting, and it does seem like the issue is resolved now. Shall we close the issue?

**Comment by GuillaumeGomez** [comment]
Funnily enough, we will end up with something like that once our plan started with https://github.com/rust-lang/rust/pull/90630 will be done.
 So yes, closing.
