### ISSUE TITLE
Associated types in traits used as bounds are treated as type arguments

### ISSUE THREAD

**Issue by rpjohnst** [rust-lang/rust#18173]
When using a trait with an associated type as a bound on a type argument, its associated types are treated as arguments rather than as determined by the impl:

```rust
trait Foo {
    type T;
}

trait Bar<F: Foo> {
    fn bar(foo: &F);
}
```

    error: wrong number of type arguments: expected 1, found 0

http://is.gd/KPP4ka

**Comment by P1start** [comment]
Looks like this compiles now. Can this be closed?
