### ISSUE TITLE
#![no_std] seems quite difficult to use in practice

### ISSUE THREAD

**Issue by jgallagher** [rust-lang/rust#18172]
I've had a few conversations on IRC about using `#![no_std]` in Rust libraries. There are comments around (such as [here in html5ever](https://github.com/servo/html5ever/blob/cb98c0cb700835f7473a9fc09a7ee9564ef3c73e/src/lib.rs#L16-L18)) that using `#![no_std]` should be used if one wants to write a Rust library that is going to be used from other languages. It's not really clear to me how accurate that recommendation still is currently / will be at 1.0 with the changes to std that have happened over the past months; however, assuming it's still true, I think there are a couple of problems that don't seem to have easy solutions:

* It's really easy to accidentally pull in std by using another crate that links std (html5ever currently has this problem - servo/html5ever#47).
* According to [the unsafe docs](http://doc.rust-lang.org/guide-unsafe.html#avoiding-the-standard-library), a crate using `#![no_std]` needs to define a few lang_items like `stack_exhausted`. If two independently-developed crates both define the lang items, you get duplicate name errors when trying to use both simultaneously.

**Comment by steveklabnik** [comment]
This ticket isn't really actionable, and with changes to the runtime, the details are (somewhat) different overall anyway.
