### ISSUE TITLE
rust doesn't compile on ppc64le architecture

### ISSUE THREAD

**Issue by leitao** [rust-lang/rust#18189]
At the moment, rust doesn't build on ppc64le architecture. I am working to work on this port, so, I am going to use this bug as the documentation to track the progress.

At the very first moment, this is what I have:

root@debian:~/rust/pristine# ./configure
configure: looking for configure programs
configure: found cmp
configure: found mkdir
configure: found printf
configure: found cut
configure: found head
configure: found grep
configure: found xargs
configure: found cp
configure: found find
configure: found uname
configure: found date
configure: found tr
configure: found sed
configure: found file
configure: inspecting environment
configure: error: unknown CPU type: ppc64le

**Comment by sanxiyn** [comment]
Any progress?

**Comment by richo** [comment]
I can give you a trivial patch that will get this working for ppc64 with a 32 bit userland present.

I don't have access to ppc64le, a really brief skim of the docs suggests that it's unlikely to be trivial to make go, but I'm willing to see what happens if someone has a test environment.

**Comment by leitao** [comment]
HI Richo,

I can provide you a access to a ppc6le machine, if you want to try it.

Thanks
Breno

**Comment by richo** [comment]
A small followup on this, I have a shell on a ppc64le machine now.

There are some bugs in the power port that I'd like to work out before I build too much else on top, but I'll see if I can get hello world working on ppc64le over the weekend at least.

**Comment by steveklabnik** [comment]
We've made some clarifications around which architectures we support and how: https://doc.rust-lang.org/nightly/book/installing-rust.html#platform-support

As there hasn't been any movement on this in 9 months, and it's just a 'tracking issue', I'm going to give it a close. If you're working on this, please get in touch with @leitao !
