### ISSUE TITLE
Warnings in quoted & spliced code are buggy

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#18216]
I'm not sure exactly what's going on but, for example, we [missed some deprecation warnings](https://github.com/servo/html5ever/pull/49) in html5ever, which has `#![deny(warnings)]`.  I've also seen ICEs in the past.

**Comment by steveklabnik** [comment]
Is this bug still relevant?

**Comment by kmcallister** [comment]
I believe so, but I don't have clear steps to reproduce :/

**Comment by tamird** [comment]
Looks like this is not actionable. @steveklabnik close?
