### ISSUE TITLE
replace "heap" with "dynamic allocation" in the documentation

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#18226]
The documentation should be conveying the language semantics, not an *inaccurate* analogy of the implementation details.  Rust never makes use of the `dss` section (aka the heap) by default as jemalloc prefers obtaining all memory via anonymous memory mappings. Stacks are dynamic allocations coming from the same operating system API as `Box<T>` and `Rc<T>`. It's all obtained via `mmap` and `VirtualAlloc`. The classical distinction between a static call stack and a dynamic heap doesn't really exist on modern operating systems since multi-threading means stacks are dynamic memory allocations.

**Comment by tomjakubowski** [comment]
This was brought up in a discuss thread as well: http://internals.rust-lang.org/t/newcomer-to-rust-my-experience/1816/28

> On the topic of borrowing and lifetimes, a lot of people here have been talking about "systems programming". I think this is a red herring. You can perfectly well explain a lot of the core concepts WITHOUT reference to the heap or stack. Just explain it from the point of view of when resources are released or copied. People who know how this works will read between the lines. People who don't, don't need to be distracted!

**Comment by steveklabnik** [comment]
With the stack and the heap chapter, exactly what we mean in these contexts has been addressed.
