### ISSUE TITLE
`bitflags!`-generated public API has poor documentation UX

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#18227]
Say I'm at the documentation page for `std::io::fs::mkdir` and want to figure out how to call it: http://doc.rust-lang.org/std/io/fs/fn.mkdir.html. I want to figure out what the `FilePermission` type is, so I click on the link to its docs. I get sent here: http://doc.rust-lang.org/std/io/struct.FilePermission.html. Unfortunately, that page gives no indication at all of how actually initialize a `FilePermission` in a useful way. I have to somehow divine that I need to jump out to the documentation for the `io` module and scroll all the way to the bottom to the constants section: http://doc.rust-lang.org/std/io/index.html#constants to actually find some useful values to pass to `mkdir`.

Associated constants would help with this, as would sufficient compiler support to implement a robust `EnumSet`.

**Comment by steveklabnik** [comment]
Triage: the motivating example is gone, but i'm guessing the issue still persists.

**Comment by sfackler** [comment]
The bitflags macro has been pulled out to a separate crate, so this issue can probably be migrated: http://doc.rust-lang.org/rustc_bitflags/macro.bitflags!.html

**Comment by sfackler** [comment]
cc @nick29581

**Comment by steveklabnik** [comment]
http://doc.rust-lang.org/bitflags/bitflags/index.html is the new link, and yeah, this still persists. Not moving because this will still affect any user macro docs, but removing a-libs since this is really just a rustdoc issue.

**Comment by steveklabnik** [comment]
This is actually a dup of https://github.com/rust-lang/rust/issues/17616

**Comment by durka** [comment]
@steveklabnik not a dupe. The motivating example was [this](http://doc.rust-lang.org/0.11.0/std/io/struct.FilePermission.html) I guess, whereas #17616 is about rustdocking the macro itself.
