### ISSUE TITLE
allow disabling dirty page purging via an API, and consider disabling it by default

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#18236]
Ratio-based dirty page purging reduces memory usage, but results in a significant performance hit. It is already possible to disable it by exporting an environment variable, but it should be possible to toggle it or alter the ratio at runtime. It may make sense to have it disabled by default because it's not desirable in short-lived applications or those with consistent memory allocation patterns.

It's primarily desirable in large, long-lived applications with varying memory usage patterns where opting into a feature is not a big deal. The defaults should likely be optimized for programming in the small.

**Comment by bstrie** [comment]
Triage: this sounds like something that ought to be relocated to the RFCs repo.

**Comment by Mark-Simulacrum** [comment]
I presume this happens today? Could someone confirm that? It seems that this would indeed be better suited to the RFC repo as an issue...

**Comment by jonas-schievink** [comment]
There is no such API, and I don't think we're doing this automatically. `jemalloc(3)` indicates that this can be done via a call to `mallctl` (or, as the OP mentions, by setting the `MALLOC_CONF` environment variable). After global allocators are stabilized, someone could write a `jemalloc` crate that provides an API around that. I agree that this should go into the RFC repo, though.

**Comment by Mark-Simulacrum** [comment]
Closing. If someone wants to pursue this, please follow the RFC process here https://github.com/rust-lang/rfcs#before-creating-an-rfc.
