### ISSUE TITLE
Cannot get a 'static reference to an explicit memory location

### ISSUE THREAD

**Issue by simias** [rust-lang/rust#18267]
I was playing around trying to get rust to let me get a reference to an explicit memory location (in order to be able to map HW registers in a nice way for the Zinc project) and ended up with that code:

```rustc
struct S {
    some_stuff: u32,
}

const SOME_S: &'static S = unsafe { &*(0x100 as *const S) };

fn main() {
    println!("{}", SOME_S.some_stuff);
}
```

Which produces the following error:

```rustc: /build/rust-git/src/rust/src/llvm/include/llvm/Support/Casting.h:237: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::GlobalVariable; Y = llvm::Value; typename llvm::cast_retty<X, Y*>::ret_type = llvm::GlobalVariable*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.```

Casting the raw pointer in an intermediate function builds and runs fine however (assuming you have something mapped at `0x100` of course):

```rustc
struct S {
    some_stuff: u32,
}

const SOME_S: *const S = 0x100 as *const S;

pub fn get_ref<T>(t: *const T) -> &'static T {
    unsafe {
        &*t
    }
}

fn main() {
    println!("{}", get_ref(SOME_S).some_stuff);
}
```

**Comment by alexcrichton** [comment]
Updated error:

```
foo.rs:8:20: 8:26 error: internal compiler error: constant expression should not reach expr::trans_def
foo.rs:8     println!("{}", SOME_S.some_stuff);
                            ^~~~~~
note: in expansion of format_args!
<std macros>:2:25: 2:58 note: expansion site
<std macros>:1:1: 2:62 note: in expansion of print!
<std macros>:3:1: 3:54 note: expansion site
<std macros>:1:1: 3:58 note: in expansion of println!
foo.rs:8:5: 8:39 note: expansion site
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:130
```

**Comment by pmarcelll** [comment]
This fails with a regular build error on the latest nightly:
```
test.rs:5:38: 5:58 error: raw pointers cannot be dereferenced in constants [E0396]
test.rs:5 const SOME_S: &'static S = unsafe { &*(0x100 as *const S) };
                                               ^~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
```

**Comment by arielb1** [comment]
@pmarcelll 

Right. However, we may still want to make that code work somehow.

**Comment by steveklabnik** [comment]
Given that this would add a new feature, and now has a regular error, I'm going to close it in favor of an RFC. Thanks!
