### ISSUE TITLE
docs: Inaccessible/private types are shown under `Show` implementors

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#18278]
Head to [`Show`](http://doc.rust-lang.org/std/fmt/trait.Show.html) doc page. You'll see the following implementors:

- Flavor (sync::mutex)
- Failure (sync::comm::sync)

The former is a private type and the latter is inaccessible (`comm::sync` is private). These two shouldn't show in the docs.

**Comment by alexcrichton** [comment]
This may be fixed, but needs more investigation. I believe this is a dupe of #14586, however.
