### ISSUE TITLE
Gamma function

### ISSUE THREAD

**Issue by stygstra** [rust-lang/rust#18271]
It would be nice if `tgamma` and `lgamma_r` were exposed via `std::num::Float`. The foreign function definitions for both are present in `src/libstd/num/f{32,64}.rs`, but they're not exposed in the standard library.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#864

**Comment by blevin** [comment]
If anyone needs gamma in the meantime, it turns out to be pleasingly easy to invoke the C math library one:

#[link(name = "m")]
extern {
    fn tgamma(x: f64) -> f64;
}
fn gamma(x: f64) -> f64 {
    unsafe { tgamma(x) }
}

**Comment by x-ji** [comment]
Meanwhile some external libraries also provide this functionality: https://docs.rs/statrs/0.9.0/statrs/function/gamma/fn.gamma.html
