### ISSUE TITLE
Move editor support to a different repo 

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#18274]
We have an org now, might as well use it and clean up /etc.

**Comment by huonw** [comment]
Done, thanks to @steveklabnik:

- https://github.com/rust-lang/rust.vim
- https://github.com/rust-lang/nano-config
- https://github.com/rust-lang/gedit-config
- https://github.com/rust-lang/rust-mode
- https://github.com/rust-lang/kate-config
