### ISSUE TITLE
Consider renaming Mutex<T> -> MutexCell<T>

### ISSUE THREAD

**Issue by carllerche** [rust-lang/rust#18284]
This would mirror RefCell / UnsafeCell / Cell and allow non-cell mutexes to be used easier in the same module.

**Comment by reem** [comment]
fwiw I've changed my mind here, I'm not totally for the renaming but I withdraw my objection.

**Comment by alexcrichton** [comment]
With the stabilization of these types I do not believe we are going to do this renaming.
