### ISSUE TITLE
Allow implementation of Show for RadixFmt with user-defined type

### ISSUE THREAD

**Issue by jsanders** [rust-lang/rust#18301]
I'm not sure whether or not this is meant to work already. It is almost possible with:

```rust
impl fmt::Show for fmt::RadixFmt<MyType, fmt::Radix> {
    fn fmt(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
        let fmt::RadixFmt(ref x, radix) = *self;
        let base = radix.base; // This doesn't work because base is private
        // ...
    }
}
```
It doesn't seem possible to get the actual base out, due to its privacy. It used to be possible to provide a ToStrRadix implementation for a user-defined type, and it would be really nice to be able to use the `fmt::radix` method.

**Comment by steveklabnik** [comment]
I'm going to give this a close, as it's been a long time, and https://github.com/rust-lang/rust/issues/27728 is the tracking issue for such functionality now.
