### ISSUE TITLE
doc.rust-lang.org front page should have a search box

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#18300]
It should act like the search box on API pages, and we would add the various guides / references / etc. to the list of possible search results.  (And maybe the names of individual sections in the guides?)

This would remove the need for two browser bookmarks, and generally make the docs more integrated and easier to navigate.

We could move the current front page to `contents.html`.  The new front page would have just a centered, focus-on-load search box, with a few links below -- the same set as the Docs column on http://www.rust-lang.org/.

cc @steveklabnik

**Comment by steveklabnik** [comment]
This is a dup of https://github.com/rust-lang/rust/issues/14572 and so I'm closing. Would love to have it though!
