### ISSUE TITLE
out-of-stack-no-split.rs fails on Ubuntu 14.04 x86_64

### ISSUE THREAD

**Issue by Zoxc** [rust-lang/rust#18305]
The main thread stack is allocated to 74 TB when `out-of-stack-no-split.rs` is executed by with make check on Ubuntu 14.04 x86_64 (the test passes when run manually). This leads to the OOM killer killing the process for `out-of-stack-no-split.rs` and leading to a test failure. This does not happen on Arch Linux x86_64 and Debian Jessie x86_64.

This test is ignored on Linux because of this bug.

**Comment by steveklabnik** [comment]
This test no longer exists.
