### ISSUE TITLE
fix performance regressions due to statics no longer being inlined

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#18311]
https://github.com/rust-lang/rust/commit/6c18e508f10aa5bf42dc80691654b9cde2a661cd fixes *one* particularly bad instance of this, but a quick `git grep static` reveals more regressions across the standard library in places like `core::char`.

**Comment by steveklabnik** [comment]
While in theory some of this might be outstanding, it's been a year, and the compiler is undergoing a lot of work. `core::char` has no more `static` in it, and since we're actively working on performance, I think that this will just naturally resolve if it hasn't already.
