### ISSUE TITLE
ICE when #[no_mangle] function is declared multiple times with different signatures.

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#18358]
```rust
#![allow(dead_code)]

mod x {
    #[no_mangle]
    fn f() { }
}

mod y {
    #[no_mangle]
    fn f(_: i32) { }
}

fn main() { }
```
>rustc: /build/rust-git/src/rust/src/llvm/include/llvm/Support/Casting.h:237: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::Function; Y = llvm::Value; typename llvm::cast_retty<X, Y*>::ret_type = llvm::Function*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.

**Comment by steveklabnik** [comment]
This still ICEs for me today.

**Comment by klutzy** [comment]
Dup of #10883?
