### ISSUE TITLE
Unexpected failure in rustc

### ISSUE THREAD

**Issue by svatsan** [rust-lang/rust#18369]
I tried to compile a simple `hello.rs` and ran into the following - output below after turning on `RUST_BACKTRACE=1`:

	error: internal compiler error: unexpected failure
	note: the compiler hit an unexpected failure path. this is a bug.
	note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
	note: run with `RUST_BACKTRACE=1` for a backtrace
	task 'rustc' failed at 'needs a temp dir', /home/rustbuild/src/rust-buildbot/slave/dist2-linux/build/src/libcore/option.rs:315

	stack backtrace:
	   1: 0xb6a79d00 - rt::backtrace::imp::write::h71c0311871d92b33BCq
	   2: 0xb6a7cc80 - <unknown>
	   3: 0xb6dc6c50 - unwind::begin_unwind_inner::hecb213f6de4ee4abIxd
	   4: 0xb6dc68b0 - unwind::begin_unwind_fmt::h14c200c16a264a5eavd
	   5: 0xb6dc6850 - rust_begin_unwind
	   6: 0xb6e16530 - failure::fail_fmt::h767d9e1ca2333a4biqk
	   7: 0xb6f63b80 - <unknown>
	   8: 0xb6f5a2b0 - back::link::link_binary::hf1d7c6859ef3a2c6xBa
	   9: 0xb782d2f0 - driver::driver::phase_6_link_output::he5609548684fab17h2w
	  10: 0xb7824590 - driver::driver::compile_input::h665973ab72cfb8bbKww
	  11: 0xb78a89d0 - <unknown>
	  12: 0xb78a88a0 - <unknown>
	  13: 0xb6f8a8f0 - <unknown>
	  14: 0xb6f8a6e0 - <unknown>
	  15: 0xb7fc2550 - <unknown>
	  16: 0xb6dc6660 - <unknown>
	  17: 0xb6e26110 - <unknown>
	  18: 0xb6e260d0 - rust_try
	  19: 0xb6dc4780 - unwind::try::h38aefa52248da233qmd
	  20: 0xb6dc45f0 - task::Task::run::h52211e2f40072d874Bc
	  21: 0xb7fc22f0 - <unknown>
	  22: 0xb6dc5da0 - <unknown>
	  23:        0x0 - <unknown>

`hello.rs` is a simple calculator demo program found on rust-lang.org. 

	$ rustc --version
	rustc 0.12.0 (ba4081a5a 2014-10-07 13:44:41 -0700)

Please let me know if you need more information.

**Comment by steveklabnik** [comment]
Yes, I think this is a dup. Thank you for reporting!
