### ISSUE TITLE
It's not possible to create `Path`s allocation-free

### ISSUE THREAD

**Issue by heinrich5991** [rust-lang/rust#18372]
1) There is no way to create a `Path` object to pass to `File::open` statically, it's always a runtime allocation.
2) `File::open` takes a `Path` object as reference, although it only clones it afterwards.

Solutions to this would include creating a `Path` DST object (possibly combined with a `PathVec` which can grow dynamically).

**Comment by alexcrichton** [comment]
This was resolved with the new `std::fs` design via `AsPath`.

**Comment by tbu-** [comment]
@alexcrichton The first part of the issue was resolved ("no way to pass a static path object"), but the second part wasn't ("`File::open` still takes the path as reference and clones it afterwards"). Should I open a new issue for it?

**Comment by alexcrichton** [comment]
@tbu- If you'd like to, sure.
