### ISSUE TITLE
rustdoc: add the ability to copy a skeleton trait impl from a trait doc entry

### ISSUE THREAD

**Issue by bjz** [rust-lang/rust#18379]
@wycats mentioned this idea to me a while back when I was fishing for ideas about how to improve rustdoc.

The impl should have the right formatting, and have dummy method impls using the `unimplemented!` macro. Perhaps default methods could come with a comment above them saying that they do not need to be implemented.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#621
