### ISSUE TITLE
#[repr(C)] and Drop causes undefined behavior in FFI code

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#18380]
```rust
extern {
    fn f(x: *const X);
}

#[repr(C)]
struct X {
    i: i32,
}

impl Drop for X {
    fn drop(&mut self) { }
}

fn main() {
    let x = [X { i: 0 }, X { i: 0 }];
    println!("{}", std::mem::size_of_val(&x));
    unsafe { f(x.as_ptr()); }
}
```
Prints 16.

**Comment by mahkoh** [comment]
This has to be fixed before 1.0.

**Comment by pnkfelix** [comment]
nominating; we are unlikely to implement non-zeroing dynamic drop before the 1.0 release (and certainly not before the 1.0 beta).  So we probably need to address tis in some way, perhaps a lint as @huonw suggests.

Nominating for 1.0 polish.

**Comment by brson** [comment]
Adding a lint is easy.

**Comment by nikomatsakis** [comment]
This is to some extent a dup of #5016

**Comment by pnkfelix** [comment]
We won't object to someone adding a lint  (which would be temporary assuming nonzeroing drop lands eventually).

But it also wont block the release.

P-high, not 1.0.
