### ISSUE TITLE
Use minnum/maxnum LLVM instrinsics for fmin/fmax

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#18384]
http://reviews.llvm.org/rL220341

Requires an LLVM upgrade, but not worth doing one just for this purpose.

**Comment by huonw** [comment]
(Many LLVM upgrades have happened since then.)

**Comment by varkor** [comment]
Update as of last 2017: [there are still issues with optimisation of `minnum`/`maxnum`](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZSBnVAV2OUxAHIB6bgagC0AYVQAHAgIA2mAG6ZJAUgDMAESWChBAIbFgmCclHNlKgHZaCeORtFbTeZCa0AjEgT4KADAEEvvgExKYGAKAKwAQsjEFpgA%2BgQAnqKYJgr%2B/pJ4zmn%2BYSp%2BaUEhEQBmmBasmBCZpgDWsZKSMgC2sXimBMTtDA4MAJR5BT6YAB4EmMSmHgDs4X58Cx6BYeE19ebNmB6qSxlNzQB0ze2mzIclSrnpgz6LfEbOfCVTx6anrRf%2BEFogT5ekfGcv0%2BfUEymwf1ySjmt0WhRWa1iGy2Jl2jRaRy0I3eB0%2BORu3juDyeLyx71in2%2BwP%2BgOp/lBAnBkOUMN803yPj8xM6WkIfAAsu1%2BViACqYBgEX4AZTwAC9MOgZqy7s8%2BK8GvsIAx5CUAagCAgJtKdQymVKdSz5otVeriMwJVqdXqDUa%2BObJCVTUoIe6SpbYQsbViNS1HR7nYbiMaPV6fRboVbA6SRrE7Q7teG%2BPrI9HPWDvW746yFOyht48M1RJIBULReL3CUSJClYmSWr2iHmmHdVmXVHCzH83GPS2A3c%2BMxTAwtGUle23mcKZcINmJgCM3mSypx62t2WVS8O2mCN2I67fbGByVR4Txws8NfV8QDngGEi7BBQSWhN/e5HthCG5zkBW58PI2pzk%2BMwcreCx7pyY5Bim6JdhuZ79heQ5Xjed4LJO06ziW4RqmSi6Uk%2B64mtBu6lghsFts0wbHqef7nlRjIFr6OG4Q%2BrHPq%2B76mJ%2BMw/tMQh8ds4kgbMfDSdu4EojJUHwfRKkFLR3jEqqyCSFolaeLQqYlMgtAAJwAGy0BAzTMO4Ix0penzcfe14jJJfCeAcnhzm5qKeZ4LLUWOvG%2BQWtBeT52zbuFAXQkF9EjOpMFcswjzabp%2BmGShED2ZCjmXM5fAjJiyGav5fRHB22UxQMnIaSlaVTDpemiAZqb2ieuUglhTlEa2xWMSmzHlZVpjtQ6NVJWWWlNRlrWGRK6A5Q5PUFX1Y4DViEAja8ECTXVKicH0pCSFwoScKQphcJ4F2oFwABKHWySwbAooEtAXZKnA3X0x21CAShKAcgMg6DYPmSdXAACwXVd323VwF0MCAnikF9P2kHAsBIGglZ4NIZAUBAuOiPjRr2MACAEJICSkCU%2BPjMQyMQLErOeJQx1AvDpDOO0OgJFwH2kLjmwdAA8qYNPXRdWCMaYwDSNLpD4MQmDIJYcjI9zoxq7ZHCcEL7TjKd3NUAAjswEwC5wQP%2BAcQvSPLBp0KQoiqzIYvOFQauSizbMcydmBO0g9Bu7Inve%2BrlCs7E7PUAAipbxAJJctCeFDoTmeZ6TmQAHKZ0xKFD%2Bf%2BKZoS0JQ%2BAMFWWjW0dx2O8Azu0L9aNdM0gtHSdWTI5Ax1iJYqBTlwwhZuIUiyPIJjqMItj2I4qguG4SMvewdAN2dsNK3dnDHsgfAU1TNN8BAuCEE2hT0HwIh4wTSxKC3n3S63/2A8DYMf4DEMmzDl3b4jjAUZo2fpjGAiAQAsAIEYAg5BKAkzJlGegCpz6II3pwc6f9uY70vnwAA7oQBAfA94HzwJTamCQn7wxfgDIGn9P6Q04L/OGN1SA7yRkA9G9cGH%2BC3lggBnDW5yCZngIeIAoZAA%3D%3D%3D) when used for clamping on x86, which seems to be the only blocker. There's an implementation [here](https://github.com/rust-lang/rust/pull/46926) that could be merged when LLVM figures out how to optimise that case.

**Comment by nox** [comment]
`clamp01_llvm` is still worse than  `clamp01_rust`.  Is there any upstream issue on LLVM that we could refer to here?

Cc @rust-lang/wg-codegen

**Comment by nikic** [comment]
The X86 codegen issue should be fixed by https://github.com/llvm/llvm-project/commit/d87eceda0e6d5de6b2d58430a0124b6f7428695d.

**Comment by varkor** [comment]
I think the problem now is that we can't use intrinsics from libcore anymore: https://github.com/rust-lang/rust/issues/50145.

**Comment by nikic** [comment]
Relevant libcalls for minnum/maxnum: https://github.com/llvm-mirror/llvm/blob/29f026d977e01fc255284a0bb90afda1435b0e6a/include/llvm/IR/RuntimeLibcalls.def#L247-L256

**Comment by varkor** [comment]
As expected, [LLVM is now properly optimising the clamp pattern.](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZSBnVAV2OUxAHIB6bgagC0AYVQAHAgIA2mAG6ZJAUgDMAESWChBAIbFgmCclHNlKgHZaCeORtFbTeZCa0AjEgT4KADAEEvvgExKYGAKAKwAQsjEFpgA%2BgQAnqKYJgr%2B/pJ4zmn%2BYSp%2BaUEhEQBmmBasmBCZpgDWsZKSMgC2sXimBMTtDA4MAJR5BT6YAB4EmMSmHgDs4X58Cx6BYeE19ebNmB6qSxlNzQB0ze2mzIclSrnpgz6LfEbOfCVTx6anrRf%2BEFogT5ekfGcv0%2BfUEymwf1ySjmt0WhRWa1iGy2Jl2jRaRy0I3eB0%2BORu3juDyeLyx71in2%2BwP%2BgOp/lBAnBkOUMN803yPj8xM6WkIfAAsu1%2BViACqYBgEX4AZTwAC9MOgZqy7s8%2BK8GvsIAx5CUAagCAgJtKdQymVKdSz5otVeriMwJVqdXqDUa%2BObJCVTUoIe6SpbYQsbViNS1HR7nYbiMaPV6fRboVbA6SRrE7Q7teG%2BPrI9HPWDvW746yFOyht48M1RJIBULReL3CUSJClYmSWr2iHmmHdVmXVHCzH83GPS2A3c%2BMxTAwtGUle23mcKZcINmJgCM3mSypx62t2WVS8O2mCN2I67fbGByVR4Txws8NfV8QDngGEi7BBQSWhN/e5HthCG5zkBW58PI2pzk%2BMwcreCx7pyY5Bim6JdhuZ79heQ5Xjed4LJO06ziW4RqmSi6Uk%2B64mtBu6lghsFts0wbHqef7nlRjIFr6OG4Q%2BrHPq%2B76mJ%2BMw/tMQh8ds4kgbMfDSdu4EojJUHwfRKkFLR3jEqqyCSFolaeLQqYlMgtAAJwAGy0BAzTMO4Ix0penzcfe14jJJfCeAcnhzm5qKeZ4LLUWOvG%2BQWtBeT52zbuFAXQkF9EjOpMFcswjzabp%2BmGShED2ZCjmXM5fAjJiyGav5fRHB22UxQMnIaSlaVTDpemiAZqb2ieuUglhTlEa2xWMSmzHlZVpjtQ6NVJWWWlNRlrWGRK6A5Q5PUFX1Y4DViEAja8ECTXVKicH0pCSFwoScKQphcJ4F2oFwABKHWySwbAooEtAXZKnA3X0x21CAShKAcgMg6DYPmSdXAACwXVd323VwF0MCAnikF9P2kHAsBIGglZ4NIZAUBAuOiPjRr2MACAEJICSkCU%2BPjMQyMQLErOeJQx1AvDpDOO0OgJFwH2kLjmwdAA8qYNPXRdWCMaYwDSNLpD4MQmDIJYcjI9zoxq7ZHCcEL7TjKd3NUAAjswEwC5wQP%2BAcQvSPLBp0KQoiqzIYvOFQauSizbMcydmBO0g9Bu7Inve%2BrlCs7E7PUAAipbxAJJctCeFDoTmeZ6TmQAHKZ0xKFD%2Bf%2BKZoS0JQ%2BAMFWWjW0dx2O8Azu0L9aNdM0gtHSdWTI5Ax1iJYqBTlwwhZuIUiyPIJjqMItj2I4qguG4SMvewdAN2dsNK3dnDHsgfAU1TNN8BAuCEE2hT0HwIh4wTSxKC3n3S63/2A8DYMf4DEMmzDl3b4jjAUZo2fpjGAiAQAsAIEYAg5BKAkzJlGegCpz6II3pwc6f9uY70vnwAA7oQBAfA94HzwJTamCQn7wxfgDIGn9P6Q04L/OGN1SA7yRkA9G9cGH%2BC3lggBnDW5yCZngIeIAoZAA%3D%3D%3D)
