### ISSUE TITLE
Resolve obligations more carefully

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#18391]
Resolving trait obligations can be an important part of type inference. However, right now we do it in a bit of an ad-hoc way:

- Every once in a while, we eagerly resolve new obligations that haven't been attempted yet.
- If we are looking at a type variable and need more type information, we do a full resolve of all obligations. This helps in some cases.

Probably we ought to avoid resolving obligations at all until we want more type information, and then we should do it only with obligations that will help with the variable in question. I am not sure if this is as simple as scanning for obligations that reference the variable somewhere -- I think not, we probably have to construct some kind of dependence graph. What can happen otherwise is something like:

    $0 : Foo<$1>
    $1 : Bar<$2>

To decide `$2`, we need to know `$1`, but to know `$1`, we have to resolve the first obligation.

**Comment by steveklabnik** [comment]
@nikomatsakis was this closed by #18386? I can't tell.

**Comment by steveklabnik** [comment]
Triage: a year later, with still no comments, I'm going assume this one is fixed.

**Comment by nikomatsakis** [comment]
Well, it has not been fixed. However... it may be that having this issue open has no real value. Never mind, I'll re-close it. :)

(Ah, I guess I did sort of address this in my recent `ObligationForest` branch.)
