### ISSUE TITLE
Add a PeekableIter trait in standard library.

### ISSUE THREAD

**Issue by PhilLavoie** [rust-lang/rust#18401]
We already have a Peekable concrete type that makes it easy for already defined iterators to provide a peek function. I would like to suggest adding  a standard trait that defines peekable iterator's behavior: peek and is_empty and next so that users can provide their own optimized  peekable iterators, possibly avoiding the intermediate copy made by Peekable for example, but also because this:

```
fn parse< C, P: PeekableIter< C > >(iter: P) {...}
```

Looks better than

```
fn pase< C, I: Iterator< C > >(iter: Peekable< C, I >) {
  ...
 //Keep in mind that peekable returns a reference and not the actual C type.
 ...
}
```

**Comment by steveklabnik** [comment]
Additions to the standard library require an RFC these days. If you still want this, please persue one over there. Thanks!
