### ISSUE TITLE
Consider making Reader and Writer generic in their type of error

### ISSUE THREAD

**Issue by canndrew** [rust-lang/rust#18414]
`IoError` doesn't make sense for all kinds of `Reader` and `Writer`. Instead, implementors should be able to choose what they return using an associated type.

For example, the `Reader` trait would look like this:

    trait Reader {
        type Error;
        fn read(&mut self, buf: &mut [u8]) -> Result<uint, Error>;
        ...
    }

**Comment by steveklabnik** [comment]
Hey @canndrew ! You should get involved over in https://github.com/rust-lang/rfcs/pull/576 if this issue is still important to you, that's the right place to bring this up. Thank you!
