### ISSUE TITLE
Yet another attempt to refactor libstd's Duration

### ISSUE THREAD

**Issue by 1-more** [rust-lang/rust#18416]
At the moment the `Duration` type looks like

    pub struct Duraion {
        secs: i64,
        nanos: i32
    }

According to this, one can expect that maximum possible duration value is at least `i64::MAX` seconds. But in fact, the full range that i64 seconds gives us is restricted to `i64::MAX` milliseconds (see #16626 for more details). 

I offer to change the internal representation of `Duration` to

    pub struct Duraion {
        ticks: i64,  // A single tick represents 100 nanoseconds  
        nanos: i8  // to hold values from -99 to 99
    }

Some pros:

1. Internals of `struct Duraion` are not exposed. So, we are free to change them.
2. New representation is 3 bytes smaller.
3. Methods like `num_milliseconds` etc will return correct i64 values (see #16626).
4. `TimeSpan` in .NET and `Duration` in Joda-Time types do the same.

Some cons:

1. The overall range of values for `Duration` will be shorter:

  * `i64::MAX` seconds gives us 106751991167300 days. We don't use <s>need</s> it.
  * `i64::MAX` milliseconds gives us 106751991167 days. This is our current choice.
  * `i64::MAX` ticks gives us 10675199 days. The range is still long enough, who cares?

2. ?

**Comment by jooert** [comment]
Isn't this obsolete because #24920 has been merged?

**Comment by alexcrichton** [comment]
Ah yes, thanks @jooert! More design info can also be found in the associated [RFC thread](https://github.com/rust-lang/rfcs/pull/1040).
