### ISSUE TITLE
make tidy could detect empty files

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#18439]
e.g. https://github.com/rust-lang/rust/pull/18438.

**Comment by iKevinY** [comment]
I was looking to implement this, but I noticed that [`compiler-lookup-paths/native.c`](https://github.com/rust-lang/rust/blob/master/src/test/run-make/compiler-lookup-paths/native.c) appears to be intentionally empty. What categories of file should be included/excluded from this check?

**Comment by steveklabnik** [comment]
Triage: i am not aware of any changes here. The file @iKevinY mentions is still empty.

**Comment by Mark-Simulacrum** [comment]
File that is mentioned isn't empty. I think that this should be a relatively easy thing to implement. In [`src/tools/tidy/src/style.rs`](https://github.com/rust-lang/rust/blob/e40beb3af162e676e40704854dd6547ee8d4cf60/src/tools/tidy/src/style.rs), a check that `contents` are not empty should be added [here](https://github.com/rust-lang/rust/blob/e40beb3af162e676e40704854dd6547ee8d4cf60/src/tools/tidy/src/style.rs#L110). The `tidy_error` macro can be used to print out the problem. At that point, you'll need to run the tidy script (`./x.py test src/tools/tidy`), and open a PR listing any new errors uncovered by this.

Please let us know if you plan to work on this by leaving a comment here. If you need any help, please ping me in this issue or on IRC (#rust-internals on irc.mozilla.org, name is simulacrum).

**Comment by iKevinY** [comment]
I should be able to pick up this issue again.

**Comment by iKevinY** [comment]
@Mark-Simulacrum I think this can be closed now that #41935 has been merged.
