### ISSUE TITLE
methods in trait impls should override default methods

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#18446]
E.g.,

```
trait T {
    fn foo(&self) {}
}

impl<'a> T+'a {
    fn foo(&self) {}
}
```

Should be OK. (It currently gives "duplicate definition of value `foo`").

Follow up to #17750

**Comment by frewsxcv** [comment]
This compiles now. Someone apply the 'needs-test' label

**Comment by frewsxcv** [comment]
Fixed by https://github.com/rust-lang/rust/pull/40296
