### ISSUE TITLE
Unify treatment of methods and static methods

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#18450]
Since with the UFCS changes, they are basically the same thing, but handled differently in lots of places in the compiler.

**Comment by steveklabnik** [comment]
@nrc, is this ticket still valid? Any pointers to where these places would be?

**Comment by nrc** [comment]
Maybe? Probably not worth keeping it open. Not sure where those places are off the top of my head.

**Comment by Mark-Simulacrum** [comment]
This is too vague to be worth keeping open. Closing.
