### ISSUE TITLE
Implement revised coercion rules

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#18469]
Tracking issue for [RFC 401](https://github.com/rust-lang/rfcs/pull/401).

**Comment by aturon** [comment]
@nick29581 Are the back-compat parts done? If so, let's re-nominate.

**Comment by nick29581** [comment]
Yep, should no longer block

**Comment by pnkfelix** [comment]
No more back incompat stuff; just usability issues.  P-high.

**Comment by arielb1** [comment]
We have coercions on assignments:
```Rust
fn main() {
    let b = [0,1,2];
    let a : &[u8];
    let c : &[u8; 3] = &b;
    a = c; // coercion here
    println!("{:?}", a);
}
```

Will these stay?

**Comment by nrc** [comment]
@arielb1 yes

**Comment by arielb1** [comment]
@nrc 

You can involve type inference quite deeply here:
```Rust
fn unify<T>(a: T, _: T) -> T { a }
trait Confusing { fn get() -> Self; }
impl Confusing for Box<[u32]> { fn get() -> Box<[u32]> { Box::new([0]) } }
impl Confusing for Box<[u32; 3]> { fn get() -> Box<[u32; 3]> { Box::new([0,1,2]) } }

#[cfg(not(type_error))]
fn f(x: bool) -> u32 {
    let a = Confusing::get();
    let v: Box<[u32]> = Box::new([1,2,3]);
    let s = match x {
        true => unify(a, v),
        false => unify(a, Box::new([1,2,3])),
    };
    s[0]
}

#[cfg(type_error)]
fn f(x: bool) -> u32 {
    let a = Confusing::get();
    let v: Box<[u32]> = Box::new([1,2,3]);
    let s = match x {
        false => unify(a, Box::new([1,2,3])),
        true => unify(a, v), //~ ERROR mismatched types
                             //| expected `Box<[u32; 3]>`
                             //|    found `Box<[u32]>`
    };
    s[0]
}

fn main() { println!("{}", f(false)); }
```

**Comment by brson** [comment]
Triage: ancient RFC tracking bug slipping through the cracks cc@rust-lang/lang what's up?

**Comment by nrc** [comment]
Discussed at the lang meeting. I will go through the checklist to make sure it is up to date. We think it should remain p-medium since periodic check ins will be worthwhile.

**Comment by qnighy** [comment]
Looking through rust-lang/rfcs#401, #37685, #32702, #34451, and this, it seems that tuple DSTs and their coercion should be allowed but the coercion is not implemented. Am I right?

**Comment by nikomatsakis** [comment]
@qnighy I think that is correct. I'm not sure just how much implementation work would be needed, there may be random bits of the compiler that need to be updated scattered around.

**Comment by qnighy** [comment]
@nikomatsakis Thank you. I'm working on it.

**Comment by qnighy** [comment]
Another question: `PartialEq`, `Eq`, `PartialOrd`, `Ord`, `Debug`, `Hash` can be generalized to unsized tuples. Are there any RFCs referring to this possibility?

**Comment by nikomatsakis** [comment]
@qnighy not that I'm aware of; I don't think we necessarily need an RFC for such a thing though

**Comment by torkleyy** [comment]
Can I use any workaround until this is resolved? I have a custom type that I want to convert from `Foo<[u32; 10]>` to `Foo<[u32]>`. I could write a method which replaces the `PhantomData`, but I want it to work for all `Unsize`-able types.

**Comment by Centril** [comment]
@eddyb What exactly remains to be done here; could you clarify the unfinished sub-issues?

**Comment by eddyb** [comment]
@Centril I'm just referring to this comment https://github.com/rust-lang/rust/issues/18469#issuecomment-61578672 and the unchecked checkboxes in it.

**Comment by nikomatsakis** [comment]
Closing this issue -- anything from RFC 401 that isn't already implemented probably requires a fresh RFC by now, or should at least have its own issue.
