### ISSUE TITLE
Deep dead_code warning is annoying

### ISSUE THREAD

**Issue by comex** [rust-lang/rust#18472]
Currently, any code which is not reachable is considered dead and warned about, even if there are references to it from other dead code.  Thus if I implement a tree of functions/methods which call each other, but haven't yet implemented any code to actually call into it yet, every single function in the family will produce a dead code warning, not only the root functions that actually lack any textual references.  This is annoyingly verbose.  

As a comparison, Clang and GCC only produce warnings for the roots in the equivalent situation for C code.

**Comment by sanxiyn** [comment]
This is by design. I note that if you add `#[allow(dead_code)]` to the root, warnings are silenced for the entire tree. You do not need to add allow attributes to all of them.

**Comment by steveklabnik** [comment]
At this point, I believe a change to a lint like this would need an RFC. As @sanxiyn notes, this is intended behavior currently.
