### ISSUE TITLE
Program extraction from Coq

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#18496]
There are a number of interesting, proven-correct data structure implementations in Coq, e.g. https://www.lri.fr/~filliatr/puf/.  Coq programs can be extracted as [Haskell, OCaml, or Scheme](https://coq.inria.fr/refman/Reference-Manual025.html).  Because of pattern matching and other functional features, Rust is a more attractive target for extraction than most other systems languages.

Another application is to write the unsafe part of a Rust program in Coq, with a safety proof.  You can decide what safety properties to provide, within a model that can vary from the Rust machine model.  This is a lot more flexible (and a lot more work!) than the all-or-nothing nature of `unsafe`.

Because all three existing target languages use garbage collection, the extracted Rust code may need to rely heavily on reference counting.  However this is perfectly reasonable when extracting functional persistent data structures, which inevitably have non-unique ownership.

It would also be neat to embed affine types into Coq although I'm not sure what has been done or can be done here.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#667
