### ISSUE TITLE
make unwinding an optional feature

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#18511]
Crate metadata can contain a boolean specifying if the crate supports unwinding and this would be opt-in during compilation via `-C unwinding`. A crate linking against crates with unwinding enabled should *implicitly* use unwinding. Since the default is to link against the standard library, nothing will change for most users. The compiler can prevent mixing crates together with a mismatch in the unwinding setting.

**Comment by steveklabnik** [comment]
Closing in favor of https://github.com/rust-lang/rfcs/issues/471
