### ISSUE TITLE
serialize::base64 could use a Show type

### ISSUE THREAD

**Issue by seanmonstar** [rust-lang/rust#18520]
I have a string that when written to a writer, needs to be converted to base64. Currently I have to allocate a new string that is encoded, before passing it to fmt. 

I'd imagine some like `struct Base64Fmt<'a> { s: &'a str, c: Config}`.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rustc-serialize#58
