### ISSUE TITLE
More shortcut functions in crate term

### ISSUE THREAD

**Issue by derekdreery** [rust-lang/rust#18548]
Just wondering if there are plans to add some more shortcut functionality in the term crate.

I.e. currently there is fg and bg functions to change color, but no functions for clearing part of the screen, changing cursor location etc.

All the machinery is already there (for reading terminfo etc), just need to implement the functions.

I don't know if this 'core' enough for the main lib, but it's very simple (a few short functions like the fg and bg ones) and avoids having to link to libcurses etc. At the moment I implement the stuff I need as a separate custom Trait, but it feels like it belongs in the term traits.

Don't know windows so don't know how complex terminal stuff works there.

**Comment by retep998** [comment]
I'd be glad to provide the Windows implementation for any improvements.

**Comment by tomjakubowski** [comment]
This should be moved to the [`term` repo](https://github.com/rust-lang/term). cc @nick29581
