### ISSUE TITLE
site search returns duplicate results

### ISSUE THREAD

**Issue by seanjensengrey** [rust-lang/rust#18540]
This url

http://doc.rust-lang.org/core/?search=Option%3A%3Aunwrap_or_else

currently returns two identical results

A search for, "Option::unwrap_or_else" yields a direct hit.

A search for, "Option unwrap_or_else" yields no results

found during an investigation of #18498

**Comment by steveklabnik** [comment]
This URL only shows two results today, not four.

**Comment by seanjensengrey** [comment]
I am still seeing the duplicate urls in both chrome and firefox.

http://doc.rust-lang.org/core/?search=unwrap_or_else

core::option
core::result 

both duplicated (4 links)

http://doc.rust-lang.org/core/?search=Option%3A%3Aunwrap_or_else

result duplicated, (2 links)
