### ISSUE TITLE
Crate names allow hyphens

### ISSUE THREAD

**Issue by gmjosack** [rust-lang/rust#18565]
It appears that crate names support hyphens without much benefit. I don't see anywhere in the guide or reference that this is intentional and is possibly only supported accidentally as a side effect of the `as` syntax. 

Library writers that make use of this functionality put a burden on users requiring `extern crate "foo-lib" as foo_lib;` for all use and doctests that refer to crates with a hyphen have to be explicitly wrapped in `fn main` (to allow for an explicit `extern crate`) in order to properly refer to their crate.

Is this specifically supported or an accident? If the latter, can this be removed? A lot of people name their projects/repos with hyphens and `cargo` will happily create a new crate with a hyphen in the name unbeknownst to a new user that this will cause extra burden.

**Comment by steveklabnik** [comment]
The current behavior is intentional, as the 'as' syntax lets you import names that aren't identifiers. This would require an RFC to change, so I'd suggest you persue one if you care about this issue.
