### ISSUE TITLE
staticlib creates huge files

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#18569]
```rust
#![no_std]
#![feature(lang_items)]
#![crate_type = "staticlib"]

extern crate core;

#[lang = "stack_exhausted"] extern fn stack_exhausted() { }
#[lang = "eh_personality"] extern fn eh_personality() { }
#[lang = "panic_fmt"] fn panic_fmt() -> ! { loop { } }
```
This creates a 1.3MB file unsuitable for distribution. The real size should be closer to 0 bytes because there are 0 public symbols.

**Comment by alexchandel** [comment]
On the other hand, compiling a small stdlib program like
```rust 
fn main() {std::io::stdio::stdout_raw().write_all(b"Hi\n");}
```
even with `-O -C lto -C no-stack-check -Z no-landing-pads` emits a massive 292K executable on OS X, as of alpha. The equivalent C program is 4K (the smallest normal executable size on OS X) and most of that is 0's. So Rust does have a bloat problem.

 By instruction count, at least two thirds of that rust executable is jemalloc.

**Comment by alexchandel** [comment]
It seems like the allocations performed in [the lang_start](https://github.com/rust-lang/rust/blob/master/src/libstd/rt/mod.rs#L64) drag jemalloc in. There should be a way to do this without allocation right? It would shave off 200K+ from the minimal executable size.

**Comment by alexchandel** [comment]
In fact, I think it's just one allocation:
```rust
let thread: Thread = NewThread::new(Some("<main>".to_string()));
```
NewThread should be rewritten to take `&'static str` alternatively!

**Comment by rprichard** [comment]
I just opened issue #22525.  It might be related.

**Comment by alexchandel** [comment]
@rprichard My minimal stdlib program, compiled above with `rustc -C opt-level=2 -C lto -C no-stack-check -Z no-landing-pads test.rs` or `rustc -C opt-level=3 -C lto -C no-stack-check -Z no-landing-pads test.rs`, is 276kB. An improvement, but still bloated.

I also checked the instruction usage, and literally **70.6%** of the executable is jemalloc.

**Comment by vadimcn** [comment]
On Windows, at least half of the executable size appears to be due to jemalloc's debug into.
`rustc -Clto -Copt-level=3 hello.rs` gives me a 822K executable.   Adding `-Clink-args=-Wl,-strip-all` brings that down to 437K..

**Comment by alexchandel** [comment]
FYI, Rust's branch of LLVM [just](#22159) [learned](https://github.com/rust-lang/llvm/pull/37) about `je_mallocx`, so this may see some improvement. I doubt it though, since the `NewThread` is so low-level.
