### ISSUE TITLE
Add warnings to save_analysis info

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#18579]
This should log all warnings (and possibly notes too) emitted during a compiler run, probably by instrumenting the Diagnostic object. At the end of the run, it should dump the warnings using the machinery in rustc::middle::save. This will mean some extra work to preserve some state between the current run and the warnings run.

**Comment by steveklabnik** [comment]
Triage: it doesn't look like there's been any change.

**Comment by brson** [comment]
Triage: no change.

**Comment by mikhail-m1** [comment]
is it still unsolved? I'd like to work on it.

**Comment by nrc** [comment]
Hmm, given that we have JSON error messages now, I don't think we need to add this stuff to save-analysis too.
