### ISSUE TITLE
Undetected use after move

### ISSUE THREAD

**Issue by pepijndevos** [rust-lang/rust#18571]
So I was curious how Drop handles cycles, because this could lead to dangling pointers, which is why `__del__` [might not be called in Python](https://docs.python.org/2/library/gc.html#gc.garbage). And indeed the below example does not call Drop.

But `t` is moved into `u`, so why does this compile at all?

```rust
struct Test {
    a: int,
    b: Option<Box<Test>>,
}

impl Drop for Test {
    fn drop(&mut self) {
        println!("Dropping {}", self.a);
    }
}

fn stuff() {
    let mut t = Test { a: 1, b: None};
    let mut u = Test { a: 2, b: Some(box t)};    
    t.b = Some(box u);
    println!("done");
}

fn main() {
    stuff();
    println!("Hello, world!")
}
```

**Comment by pnkfelix** [comment]
While this will hopefully be fixed soon, as there is a PR up, it seems to have fallen through the cracks as a P-backcompat-lang issue that is only on the 1.0 milestone and not 1.0 beta.

Nominating for 1.0 beta.  (Also, I guess I will try to run through and find any other such overlooked issues.)

**Comment by pnkfelix** [comment]
Assigning 1.0 beta.
