### ISSUE TITLE
Strategy for stabilization non-std crates

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#18585]
For 1.0 we're only going  to stablize `std`. We need to figure out what to do with all the other crates. @alexcrichton has some ideas.

**Comment by aturon** [comment]
@alexcrichton are we ready to close this?

**Comment by alexcrichton** [comment]
While not fully taken care of, all stragglers are handled in #19260 so I'm fine with closing in favor of that. The only crates left to take care of are:

* test (`Bencher` and `black_box`)
* libc
