### ISSUE TITLE
Unify the fat pointer layouts in back::abi

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#18590]
There are three versions of these layouts for functions, traits, and slices, but the compiler relies on these being the same. We should replace them with a single layout: `fat_ptr_data` and `fat_ptr_extra` or something. While we're at it, we should probably find uses of len/length names in the DST code and replace it with something more generic.

**Comment by apasel422** [comment]
What still needs to be done here, if anything?

**Comment by brson** [comment]
Looks done.
