### ISSUE TITLE
sub-trait coercions

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#18600]
Where `trait T: U { ... }` , implictly coerce from `&T` to `&U`, etc.

See [RFC 401](https://github.com/rust-lang/rfcs/blob/master/text/0401-coercions.md).

Part of #18469

**Comment by steveklabnik** [comment]
another https://github.com/rust-lang/rust/issues/18469

**Comment by frewsxcv** [comment]
What's the status of this?

**Comment by typelist** [comment]
I think this is a duplicate of #5665 (although that bug was filed before RFC 401 was adopted).

**Comment by Mark-Simulacrum** [comment]
Going to go ahead and close in favor of #5665.

**Comment by crlf0710** [comment]
Current tracking issue for this is #65991
