### ISSUE TITLE
Update private rustc datastructures to match conventions

### ISSUE THREAD

**Issue by Gankro** [rust-lang/rust#18616]
Right now it's in a kind of zombie russian-roulette state where anything called "map" might want `find` or `get`, and there's no obvious way to know without looking it up or letting the compiler error out. I assume you guys aren't fans of that.

**Comment by steveklabnik** [comment]
Triage: I'm not sure if this work has been done or not.

**Comment by ahmedcharles** [comment]
Does anyone know what this means or what work needs to be done?

**Comment by Mark-Simulacrum** [comment]
I propose that this be closed, with more specific issues being opened if they're found.

**Comment by Mark-Simulacrum** [comment]
Closing. There's no specific information here to make keeping this worth it.
