### ISSUE TITLE
Lifetimes should be inferred in simple cases

### ISSUE THREAD

**Issue by mhart** [rust-lang/rust#18620]
Rust newbie here. This is very probably a dupe, but my GH foo failed me.

The following fails to compile:
```rust
fn my_fn<T>(items: T) where T: Iterator<&str> {
    println!("hello")
}
```
With:
```
<anon>:5:41: 5:45 error: missing lifetime specifier [E0106]
<anon>:5 fn my_fn<T>(items: T) where T: Iterator<&str> {
                                                 ^~~~
```
But it's unclear to me why the compiler can't just infer the lifetime here?

Shouldn't this be the default choice?
```rust
fn my_fn<'a, T>(items: T) where T: Iterator<&'a str> {
    println!("hello")
}
```

*Edit:* So it could also be `'static`, but I wouldn't have thought that would be the default (or encouraged) case. If you did want it to be static, then you could declare it explicitly. Similar to how variables are immutable by default (without needing an explicit declaration), yet if you want them to be mutable you declare it.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#762
