### ISSUE TITLE
Request: add prefix_sum and prefix_product to AdditiveIterator and MultipilicativeIterator

### ISSUE THREAD

**Issue by Undeterminant** [rust-lang/rust#18631]
I found myself coding these up and figured that it would make sense to have them by default.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#763
