### ISSUE TITLE
match arms differ in mutability

### ISSUE THREAD

**Issue by bfops** [rust-lang/rust#18657]
This doesn't compile (`error: match arms have incompatible types: expected &int, found &mut int (values differ in mutability)`)

    fn main() {
        let mut x: int = 1;
        let opt: Option<int> = None;
        let rx: &int =
          match opt {
            Some(_) => {
              &x
            },
            None => {
              &mut x
            },
          };
        println!("{}", *rx);
    }

But this works:

    fn main() {
      let mut x: int = 1;
        let opt: Option<int> = None;
        let rx: &int =
          match opt {
            Some(_) => {
              &x
            },
            None => {
              let y: &int = &mut x;
              y
            },
          };
        println!("{}", *rx);
    }

Should this "cast" be able to happen implicitly?

**Comment by steveklabnik** [comment]
Rust does not do this kind of implicit casting, no. It _could_ be done, but that would require an RFC to change. Please pursue one if you'd like to add this to Rust, thanks!

**Comment by bfops** [comment]
Ah turns out this has been fixed. I'm not sure which RFC touched this behavior, but the first version works now.
