### ISSUE TITLE
Attempting to clone Vec<T> for non-cloneable T returns &[T]

### ISSUE THREAD

**Issue by hannobraun** [rust-lang/rust#18651]
This code works as expected:

``` Rust
#[deriving(Clone)]
struct MyStruct;

fn main() {
    let v1: Vec<MyStruct> = Vec::new();
    let v2: Vec<MyStruct> = v1.clone();
}
```

Something odd happens when I remove `#[deriving(Clone)]`:

``` Rust
struct MyStruct;

fn main() {
    let v1: Vec<MyStruct> = Vec::new();
    let v2: Vec<MyStruct> = v1.clone();
}
```

I would expect an error message about `MyStruct` not implementing `Clone`. Instead I get this error:

```
main.rs:5:26: 5:36 error: mismatched types: expected `collections::vec::Vec<MyStruct>`, found `&[MyStruct]` (expected struct collections::vec::Vec, found &-ptr)
main.rs:5   let v2: Vec<MyStruct> = v1.clone();
                                    ^~~~~~~~~~
error: aborting due to previous error
```

This works again:

``` Rust
struct MyStruct;

fn main() {
    let v1: Vec<MyStruct> = Vec::new();
    let v2: &[MyStruct] = v1.clone();
}
```

Am I missing something here? Since `Vec::clone` is only implemented for `T: Clone`, it shouldn't be possible to call `clone` at all. Why would it return a `&[T]`?

**Comment by nham** [comment]
Visiting for triage. Attempting to compile

    struct MyStruct;

    fn main() {
        let v1: Vec<MyStruct> = Vec::new();
        let v2: Vec<MyStruct> = v1.clone();
    }

now results in:

    $ rustc --version
    rustc 1.1.0-nightly (da623844a 2015-04-25) (built 2015-04-26)
    $ rustc test_18651.rs 
    test_18651.rs:5:32: 5:39 error: type `collections::vec::Vec<MyStruct>` does not implement any method in scope named `clone`
    test_18651.rs:5     let v1: Vec<MyStruct> = v1.clone();
                                                   ^~~~~~~
    error: aborting due to previous error

So I don't see the weird issue originally reported. Is there another case for this bug or is it fixed?

**Comment by P1start** [comment]
Huh, weird. I would argue that this bug displayed the intended behaviour, and that the new behaviour is wrong. Oddly, this bug sort of works if `v1` is referenced manually, but only when the type of `v2` is explicitly declared:

```rust
struct MyStruct;

fn main() {
    let v1: Vec<MyStruct> = Vec::new();
    let v2: &[MyStruct] = (&v1).clone();
}
```

**Comment by P1start** [comment]
To be precise, it seems that auto-deref is no longer taken into account when looking for trait implementations:

```rust
trait Bar {
    fn frob(&self);
}

impl<'a, T> Bar for &'a [T] {
    fn frob(&self) {
        println!("Foo");
    }
}

fn main() {
    let x = Vec::new();
    x.frob(); // error: type `collections::vec::Vec<_>` does not implement any method in scope named `frob`
}
```

Does anyone know if this is intentional, or if an issue should be opened for it? In any case, I believe this issue should be closed—the only reason my last example worked was because `(&v1).clone()` was of type `&Vec<MyStruct>` (because of the impl of `Clone` for `&T`), which then coerced to a `&[MyStruct]` through deref coercions.

**Comment by nikomatsakis** [comment]
@P1start I think what you wanted was to implement the trait on `[T]`, not `&'a [T]`, or else use `fn(self)`, not `fn(&self)`. At some point we did have a "double auto-ref" operation to handle this case, but it was removed at some point (it was a holdover from the days before DST, when there was no alternative).

**Comment by nikomatsakis** [comment]
@P1start to spell that out a bit more, `Vec<T>` derefs to `[T]`, which can then be auto-ref'd to `&[T]`, but what your trait requires is `&&[T]`

**Comment by jooert** [comment]
Triage: As I understand this, the original error has been fixed and so this can be closed, right?

**Comment by Mark-Simulacrum** [comment]
Triage: Looks like this is [still] fixed, and can be closed.

**Comment by alexcrichton** [comment]
Yay!
