### ISSUE TITLE
Allow automatically derived Show for enums to be just the field name

### ISSUE THREAD

**Issue by mitsuhiko** [rust-lang/rust#18669]
When working with enums for error reporting it would be super useful if the default implementation of `Show` for enums could be customized so that you can skip the contained data.  For instance if you have a `MyError(SomeOtherError)` it is interesting to just get `MyError` instead of `MyError(SomeOtherError { foo: 42 })` or whatever is contained in there.

**Comment by steveklabnik** [comment]
I believe the `Display`/`Debug` split takes care of this now, as `Display` no longer has a default implementation for exactly this reason.
