### ISSUE TITLE
Empty structs should not need #[repr(C)]

### ISSUE THREAD

**Issue by cgaebel** [rust-lang/rust#18686]
In a lot of FFI code, I see patterns like:

```
struct X {}

fn some_c_function(this: *mut X);
```

where `X` is used as an opaque "black-box" object. With rust today, `X` needs a `#[repr(C)]`. That's not really necessary, and caused a bunch of noisy warnings when updating servo's rust version.

Can someone mark this bug as easy so a beginner can use it to get started?

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#750
