### ISSUE TITLE
Rustdoc: Surface trait impl doc comments in "implemented" section

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#18701]
`rust-postgres` is going to be providing more built-in implementations of `ToSql` and `FromSql` for third part libraries via Cargo features (e.g. https://github.com/sfackler/rust-postgres/commit/4f80c3296700de592d58ff841d458bb3f6cd678e). I've tagged the trait impls with a doc comment stating which feature is required to use them (https://github.com/sfackler/rust-postgres/commit/b81acaab4c0532d8477d74a118d7d1fa5155ea5f), but that comment isn't displayed by rustdoc: http://sfackler.github.io/doc/postgres/trait.ToSql.html.

**Comment by jan-hudec** [comment]
Note that the comments do appear in the “Trait implementations” section of the type's documentation. But for libraries that define new traits and implement them for existing types this is useful. The comments have to *also* appear in the “Implementors” section *trait's* documentation.

**Comment by sfackler** [comment]
This has been a persistent source of confusion for users of rust-postgres:
https://github.com/sfackler/rust-postgres/issues/121
https://github.com/sfackler/rust-postgres/issues/120
https://github.com/sfackler/rust-postgres/issues/112
https://github.com/sfackler/rust-postgres/issues/103
https://github.com/sfackler/rust-postgres/issues/102

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by Dylan-DPC** [comment]
closing this issue after a discussion with @GuillaumeGomez
