### ISSUE TITLE
Caching and other optimizations for method call resolution

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#18716]
Method call resolution takes a long time. It should not.

**Comment by steveklabnik** [comment]
Triage: unsure if this has been implemented or not.

**Comment by nikomatsakis** [comment]
No.

**Comment by ishitatsuyuki** [comment]
It has been a long time since this issue have been around. @nikomatsakis Is this still a thing we should do?

**Comment by nikomatsakis** [comment]
Hmm. I think we can go ahead and close. We've got quick reject and we're using trait evaluation, which has a cache. There is probably still more caching that could be done but it's not where I would start.
