### ISSUE TITLE
libtime::Tm::to_utc() is slow even if already utc

### ISSUE THREAD

**Issue by seanmonstar** [rust-lang/rust#18725]
`Tm.to_utc()` calls out to the runtime fn `rust_timegm` twice, once to convert to a Timespec, and a second time to convert the timespec to a new Tm with offset of 0. If a `Tm` is already UTC, this should skip both those calls.

**Comment by gsingh93** [comment]
This should probably be closed or moved to https://github.com/rust-lang/time

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/time#66
