### ISSUE TITLE
`size_hint` should be able to return a lower bound that is infinite

### ISSUE THREAD

**Issue by vks** [rust-lang/rust#18751]
Taken from the standard library:

```rust
impl<A: Add<A, A> + Clone> Iterator<A> for Counter<A> {
    [...]
    #[inline]
    fn size_hint(&self) -> (uint, Option<uint>) {
        (uint::MAX, None) // Too bad we can't specify an infinite lower bound
    }
}
```

Some iterators are infinite, `size_hint` should be able to return `(None, None)` for that. This warrants changing the type signature to `(Option<uint>, Option<uint>)`.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#677
