### ISSUE TITLE
Guide: `&mut self` `self` do not have examples

### ISSUE THREAD

**Issue by gamazeps** [rust-lang/rust#18787]
In the 'Method syntax' section, three syntaxes are mentioned: `self`, `&self`, and `&mut self`.
However only the `&self` syntax is given an example.

I think it may be usefull to give some sample code using the other syntaxes.

It should be rather easy and a good first issue if someone wants to start working on Rust :)

**Comment by steveklabnik** [comment]
There's now `&mut self` but no `self`.

**Comment by jxcl** [comment]
@steveklabnik I'd like to write a section in Method Syntax detailing `self`, `&self` and `&mut self` a bit more, with explicit examples of when you would use each of them and that reinforces the idea that if you use `self` then ownership of `self` will be transferred into that scope and will be destroyed if not returned. Thoughts?

**Comment by steveklabnik** [comment]
That'd be great.
