### ISSUE TITLE
Incorrect optimization in code fragment

### ISSUE THREAD

**Issue by nstoddard** [rust-lang/rust#18786]
I found [some code that behaves differently with optimization](http://is.gd/sOxySz). With -O0, it prints false; with any higher setting, it prints true.

Sorry about the poor variable names; this is (mostly) a translation from some Javascript code. I've tried to remove as much code as I can, but I'm sure it can still be reduced somewhat and still show the same incorrect behavior.

Edit: the old code sample linked to 'hello world' for some reason. I fixed it.

**Comment by steveklabnik** [comment]
This code sample now prints 'true' in both cases, with no panic.
