### ISSUE TITLE
Unboxed closure: infer `move` when passing an unboxed closure to Fn* + Send

### ISSUE THREAD

**Issue by carllerche** [rust-lang/rust#18799]
It would be really amazing if in the following snippet, the "move" was inferred by the fact that the closure is passed as a Fn* + Send. Aka, that move was inferred by the Send trait.

```
fn stuff<F: FnOnce() + Send>(f: F) {
}

pub fn main() {
    stuff(move |:| println!("hello"));
}
```

**Comment by huonw** [comment]
It seems this would be better suited by tying to `'static` instead of `Send`; especially given https://github.com/rust-lang/rfcs/pull/458.

**Comment by nikomatsakis** [comment]
I am not sure whether to implement this inference or not. See thoughts here: http://discuss.rust-lang.org/t/on-the-topic-of-inferring-move-closures/1438

And yes @huonw I've been assuming we would tie it to 'static, not `Send`.

**Comment by nikomatsakis** [comment]
Conclusion from the thread was "won't fix".
