### ISSUE TITLE
Erroneous multiple mutable borrows message

### ISSUE THREAD

**Issue by bfops** [rust-lang/rust#18803]
The following fails to compile:
```
pub struct GLContext;

pub struct ShaderHandle<'a>;

impl<'a> ShaderHandle<'a> {
  pub fn new<'b: 'a>(
    _gl: &'b mut GLContext,
  ) -> ShaderHandle<'a> {
    ShaderHandle
  }
}

pub struct Shaders<'a> {
  pub shaders: Vec<ShaderHandle<'a>>,
}

impl<'a> Shaders<'a> {
  pub fn new<'b: 'a> (
    gl: &'b mut GLContext,
  ) -> Shaders<'a> {
    let shaders = vec![ShaderHandle::new(gl)];
  
    Shaders {
      shaders: shaders,
    }   
  }
}

pub fn main() {
  let mut gl = GLContext;

  let x = Shaders::new(&mut gl);
  let y = Shaders::new(&mut gl);
}
```

If I inline the definition of `Shaders::new`, it compiles. If I remove the `Vec` and just store a single `ShaderHandle` in each `Shaders`, it compiles. Is this a bug, or some subtlety in borrow semantics?

**Comment by steveklabnik** [comment]
So is this a bug or not?

**Comment by nikomatsakis** [comment]
Ah, I meant to reply to @bfops, sorry about that. I think this it not a bug. Basically, this is how the type system works. That said, there might be a way to express what @bfops wanted with some cleverness. Or else it is potential fodder for future type-system extensions. @bfops maybe you can ping me on IRC and we can go over the example? Right now this is all kind of "out of cache".

**Comment by bfops** [comment]
SGTM thanks!
