### ISSUE TITLE
sort out librust_builtin placement

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#18800]
The test run-pass/sepcomp-lib-lto.rs can fail on android apparently due to the fact that a pthread shim dependency is present in libstd (as part of librust_builtin), but it stripped out early. It may be possible to work around this by moving the dependency into liballoc instead, but a more thorough examination is needed.

**Comment by steveklabnik** [comment]
Triage: this test is still ignored on android, but I don't know what `librust_builtin` is nowadays.

**Comment by huonw** [comment]
> I don't know what librust_builtin is nowadays.

[Dead](https://github.com/rust-lang/rust/pull/30175)! So I guess this can be closed, but should we check if the affected test was actually fixed?

**Comment by alexcrichton** [comment]
Yeah I think this is all taken care of, so closing.
