### ISSUE TITLE
include! macro fails if included file has top-level inner attributes

### ISSUE THREAD

**Issue by dwrensha** [rust-lang/rust#18810]
```
// test.rs

pub mod included {
    include!("test_included.rs")
}

fn main() {}
```

```
// test_included.rs

#![allow(dead_code)]

pub fn foo() {}
```

```
$ rustc test.rs
test_included.rs:3:3: 3:4 error: an inner attribute is not permitted in this context
test_included.rs:3 #![allow(dead_code)]
                     ^
error: aborting due to previous error
```

I at first thought that the problem was due to the implicit insert of the prelude in the `included` module. However, adding a `#[no_implicit_prelude]` attribute does not help.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#752

**Comment by SimonSapin** [comment]
I’ve published the plugin above as [a `mod_path` crate on crates.io](https://crates.io/crates/mod_path)
