### ISSUE TITLE
Expand macros in attributes

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#18849]
Something like this would be nice for code generation in Cargo. (See rust-lang/cargo#824.)

``` rust
#[path = concat!(env!("OUT_DIR"), "/hello.rs")]
mod foo;
```

But it currently doesn’t parse:

``` rust
a.rs:1:10: 1:16 error: unexpected token: `concat`
a.rs:1 #[path = concat!(env!("OUT_DIR"), "/hello.rs")]
                ^~~~~~
```

Can we make this work? I have a hack in https://github.com/rust-lang/rust/issues/18810#issuecomment-62450616 to work around it, but it’s ugly.

CC @alexcrichton @eddyb

**Comment by SimonSapin** [comment]
Is it possible to do this backward-compatibly after 1.0?

**Comment by huonw** [comment]
> Is it possible to do this backward-compatibly after 1.0?

Should be fine, yes.

**Comment by SirVer** [comment]
Future searchers: I stumbled on this issue as I created a generated module in `build.rs` and https://github.com/rust-lang/rust/issues/18810 contained a work around that helped me.

**Comment by Mark-Simulacrum** [comment]
Closing. If someone wants to pursue this, please follow the RFC process here https://github.com/rust-lang/rfcs#before-creating-an-rfc; the change is major enough to warrant this.

**Comment by pierzchalski** [comment]
Is anyone working on this, or is there an RFC in the pipeline? If not, I'm willing to start work on one.
CC @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
To my knowledge no one is working on this, but asking on internals.rust-lang.org is likely a good start.

**Comment by mjbshaw** [comment]
@pierzchalski Have you gotten a chance to start an RFC for this?
