### ISSUE TITLE
trans tries to clean up values created in a match arm, outside the match.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#18845]
Original testcase by @hoeppnertill (reduced from [his nock repo](https://github.com/hoeppnertill/nock/blob/41f7b85d02533c86e86e19fe8ec9c67c941de3b0/src/lib.rs)):
```rust
#![crate_type="lib"]

pub fn test(foo: bool) -> int {
    match foo {
        true => *box 0,
        false => 0
    }
}
```
```llvm
Instruction does not dominate all uses!
  %6 = bitcast i8* %5 to i64*
  %8 = bitcast i64* %6 to i8*
LLVM ERROR: Broken function found, compilation aborted!
```
The debug log reveals that a (shallow free) cleanup of the `Box<int>` rvalue is scheduled in the scope of AST node `11`, while the dereference expression itself has id `16`:
```rust
DEBUG:rustc::middle::trans::expr: deref_once(expr=expr(16: *box() 0), datum=Datum((i64*:  %7 = bitcast i8* %6 to i64*), Box<int>, RvalueExpr(Rvalue { mode: ByValue })), method_call=MethodCall { expr_id: 16, adjustment: NoAdjustment })
DEBUG:rustc::middle::trans::cleanup: temporary_scope(16) = AstScope(11)
DEBUG:rustc::middle::trans::cleanup: schedule_free_value(AstScope(11), val=(i64*:  %7 = bitcast i8* %6 to i64*), heap=HeapExchange)
DEBUG:rustc::middle::trans::cleanup: schedule_clean_in_ast_scope(cleanup_scope=11)
DEBUG:rustc::middle::trans::expr: deref_once(expr=16, method_call=MethodCall { expr_id: 16, adjustment: NoAdjustment }, result=Datum((i64*:  %7 = bitcast i8* %6 to i64*), int, RvalueExpr(Rvalue { mode: ByRef })))
```
`--pretty expanded,identified` reveals that id `11` refers to the entire function's block:
```rust
pub fn test(foo /* pat 5 */: bool) -> int {
    (match (foo /* 13 */) {
         (true /* 15 */) /* pat 14 */ =>
         (*(box() (0 /* 18 */) /* 17 */) /* 16 */),
         (false /* 20 */) /* pat 19 */ => (0 /* 21 */),
     } /* 12 */)
} /* block 11 */ /* 3 */
```

This means the cleanup of a value valid *only within* a match arm is scheduled *outside* the arm.
cc @nikomatsakis @pnkfelix

**Comment by steveklabnik** [comment]
Triage: this still ICEs.

**Comment by pnkfelix** [comment]
@eddyb can you point me/us at the micro-optimization that you mentioned above, so that I (we) can try removing it ourselves and measure the impact?

**Comment by eddyb** [comment]
@pnkfelix I only vaguely recall this issue, but I'm pretty sure I was talking about [`trans::expr::deref_owned_pointer`](https://github.com/rust-lang/rust/blob/3ef8ff1f81107b42840a695725e1a0869c163355/src/librustc_trans/trans/expr.rs#L2254-L2261).

**Comment by tamird** [comment]
triage: still ICEs.
```rust
#![feature(box_syntax)]

#![crate_type="lib"]

pub fn test(foo: bool) -> u8 {
    match foo {
        true => *box 0,
        false => 0
    }
}
```

**Comment by pnkfelix** [comment]
Indeed, it doesn't even need `box_syntax`:

```rust
pub fn test(foo: bool) -> u8 {
    match foo {
        true => *Box::new(0),
        false => 0
    }
}

fn main() {
    test(true);
}
```

Does this at least continue to ICE even if LLVM is compiled without assertions?  If not, we may want to up the priority on this ticket.
