### ISSUE TITLE
Duration: methods to extract non-integral content

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#18855]
Right now, `Duration::num_seconds` and friends return `i64` values, which means you get the number of whole seconds included in the duration. But it's often useful to get fractional values as well.

It's unclear whether the methods should simply be changed to yield `f64` values, or whether we should have separate variants.

**Comment by alexcrichton** [comment]
The `Duration` type has been redesigned since this was opened, so I'm going to close this as stale (as it basically no longer applies)
