### ISSUE TITLE
Support dylib LTO

### ISSUE THREAD

**Issue by mprobinson** [rust-lang/rust#18863]
Dylibs are currently bloated with useless library code, see #18541. This can be worked around in a platform specific manner using linker scripts, but the correct solution would be to build them with LTO.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#765
