### ISSUE TITLE
non_ascii_idents: √ -> start of token error

### ISSUE THREAD

**Issue by soltanmm** [rust-lang/rust#18871]
Code:

    #![feature(non_ascii_idents)]
    fn √() {}
    fn main() {}

Error:

    <anon>:2:4: 2:5 error: unknown start of token: \u221a
    <anon>:2 fn √() {}
                ^

Obviously not a high priority (or medium priority... or even perhaps deserving the word 'priority'), but leaving it here anyway.

**Comment by steveklabnik** [comment]
Yup!
