### ISSUE TITLE
Non-uint array indexing

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/rust#18878]
Hi

Currently, rust doesn't seem to accept non uint types as index for an array. As an example, this code doesn't compile : 

```rust
let array = [1, 2, 3, 4];
let index: u16 = 1;
let item = array[index];
```

I have to do
```rust
let item = array[index as uint];
```

Couldn't rustc automate this conversion ?

**Comment by steveklabnik** [comment]
Yes, closing in favor of the RFC
