### ISSUE TITLE
'rustc' panicked at 'Box<Any>'

### ISSUE THREAD

**Issue by abhijeetbhagat** [rust-lang/rust#18884]
I think this could be already under consideration, but anyway.
I am doing FFI with libsqlite3 and want to convert an array of C strings to an array of `&str`:
```rust
extern fn callback(vp : *mut c_void, argc: c_int, argv : *mut*mut c_char, azColName : *mut*mut c_char){
    unsafe{
        let ar = argv as *mut[&str];
    }
}
```

```
error: internal compiler error: translating unsupported cast: *mut *mut i8 (cast_pointer) -> *mut [&str] (cast_other)
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
task 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-linux/build/src/libsyntax/diagnostic.rs:175

$ rustc --version=verbose
rustc 0.13.0-nightly
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu (Ubuntu 12.04.5)
release: 0.13.0-nightly
```

**Comment by ctennis** [comment]
I'm unable to reproduce the original reported IRC using the 2015-01-08 nightly, as well as the one reporte by octplane.

The one reported by abhijeetbhagat looks to be the same as #18998.

I think this can be closed.

**Comment by WiSaGaN** [comment]
Maybe related:

> error: internal compiler error: translating unsupported cast: *const [u8] (cast_other) -> *const ctp::api::CThostFtdcDepthMarketDataField (cast_pointer)
> note: the compiler unexpectedly panicked. this is a bug.
> note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
> note: run with `RUST_BACKTRACE=1` for a backtrace
> thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:189

> stack backtrace:
>    1:     0x7f56477f9250 - sys::backtrace::write::h361f9c7ed16d6f6eUsy
>    2:     0x7f564781c950 - failure::on_fail::h69f5f434699d11ccOWF
>    3:     0x7f564777c7d0 - rt::unwind::begin_unwind_inner::hc4455d84b00b874blBF
>    4:     0x7f5644b49040 - rt::unwind::begin_unwind::h13236156776379767181
>    5:     0x7f5644b49800 - diagnostic::Handler::bug::hc53c3d6401de6d9cE0E
>    6:     0x7f5645826400 - session::Session::bug::h42ea3f524efcaf9aRdq
>    7:     0x7f56464e6480 - trans::expr::trans_imm_cast::h8e98a9c5e28cc383Yek
>    8:     0x7f56464cd4b0 - trans::expr::trans_unadjusted::h68af944f056ff4503li
>    9:     0x7f5646486890 - trans::expr::trans::h606997b5304b88c02Dh
>   10:     0x7f5646485700 - trans::expr::trans_into::h414e3b9805ba8c56yAh
>   11:     0x7f5646585380 - trans::_match::mk_binding_alloca::h3339070147255386516
>   12:     0x7f5646484da0 - trans::base::init_local::ha251460caa357b208gt
>   13:     0x7f5646485d10 - trans::controlflow::trans_block::h7b10c1348ed3099fKae
>   14:     0x7f56464ce0a0 - trans::expr::trans_rvalue_dps_unadjusted::haacbdd61b8a20a98rUi
>   15:     0x7f5646485700 - trans::expr::trans_into::h414e3b9805ba8c56yAh
>   16:     0x7f5646485d10 - trans::controlflow::trans_block::h7b10c1348ed3099fKae
>   17:     0x7f56464ce0a0 - trans::expr::trans_rvalue_dps_unadjusted::haacbdd61b8a20a98rUi
>   18:     0x7f5646485700 - trans::expr::trans_into::h414e3b9805ba8c56yAh
>   19:     0x7f564656d3f0 - trans::_match::trans_match_inner::hd81cc9cef96b0f4fKux
>   20:     0x7f56464ce0a0 - trans::expr::trans_rvalue_dps_unadjusted::haacbdd61b8a20a98rUi
>   21:     0x7f5646485700 - trans::expr::trans_into::h414e3b9805ba8c56yAh
>   22:     0x7f5646485d10 - trans::controlflow::trans_block::h7b10c1348ed3099fKae
>   23:     0x7f56464d3630 - trans::expr::trans_rvalue_stmt_unadjusted::h3be0421ccac91c8czOi
>   24:     0x7f5646485700 - trans::expr::trans_into::h414e3b9805ba8c56yAh
>   25:     0x7f5646485d10 - trans::controlflow::trans_block::h7b10c1348ed3099fKae
>   26:     0x7f5646550190 - trans::base::trans_closure::hc10b2f65a8ba3bbeq6t
>   27:     0x7f56464721c0 - trans::base::trans_fn::h2fdd5a62251c638bAhu
>   28:     0x7f564646d2a0 - trans::base::trans_item::h3d73b63127b4fa2d1Fu
>   29:     0x7f5646557360 - trans::base::trans_crate::h387d3a2ececb9513LCv
>   30:     0x7f5647df8be0 - driver::phase_4_translate_to_llvm::h1183582fed5982182Oa
>   31:     0x7f5647dd1a40 - driver::compile_input::hcb43bced2a0b021bCba
>   32:     0x7f5647ea3be0 - run_compiler::hb81cf958c2f963666ac
>   33:     0x7f5647ea2270 - thunk::F.Invoke<A, R>::invoke::h6159218808669033746
>   34:     0x7f5647ea11a0 - rt::unwind::try::try_fn::h8268217050585033268
>   35:     0x7f5647888a90 - rust_try_inner
>   36:     0x7f5647888a80 - rust_try
>   37:     0x7f5647ea1450 - thunk::F.Invoke<A, R>::invoke::h8703575304585054118
>   38:     0x7f5647808e40 - sys::thread::thread_start::h35f66aa7ce5d7277LCB
>   39:     0x7f564184b0c0 - start_thread
>   40:     0x7f56473f8fd9 - __clone
>   41:                0x0 - <unknown>




Compiler:
> rustc 1.0.0-nightly (d3732a12e 2015-02-06 23:30:17 +0000)
> binary: rustc
> commit-hash: d3732a12e896ab98aa27eaffab99a78bbaf837e4
> commit-date: 2015-02-06 23:30:17 +0000
> host: x86_64-unknown-linux-gnu
> release: 1.0.0-nightly

Envrionment:
NAME="Ubuntu"
VERSION="14.04.1 LTS, Trusty Tahr"
x86_64

**Comment by lisongmin** [comment]
Maybe related:

Caused when I build https://github.com/PistonDevelopers/conrod.git .

$ RUST_BACKTRACE=1 cargo test
   Compiling pistoncore-window v0.0.13 (https://github.com/pistondevelopers/window#711cb7a1)
   Compiling image v0.2.0-alpha.10 (https://github.com/pistondevelopers/image#28da3ad0)
   Compiling glutin v0.0.6 (https://github.com/tomaka/glutin#7154ea5c)
   Compiling pistoncore-event_loop v0.0.13 (https://github.com/PistonDevelopers/event_loop#4d619354)
   Compiling pistoncore-event v0.0.10 (https://github.com/pistondevelopers/event#4166dc0c)
   Compiling piston v0.0.7 (https://github.com/PistonDevelopers/piston/#719e4405)
   Compiling conrod v0.0.7 (file:///work/rust/conrod)
/build/rust-git/src/rust/src/libstd/sync/mutex.rs:177:37: 180:2 error: internal compiler error: debuginfo: Could not find scope info for node NodeExpr(Expr { id: 30825, node: ExprStruct(Path { span: Span { lo: BytePos(4847499), hi: BytePos(4847510), expn_id: ExpnId(4294967295) }, global: false, segments: [PathSegment { identifier: StaticMutex#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }] }, [Field { ident: Spanned { node: lock#0, span: Span { lo: BytePos(1770102), hi: BytePos(1770106), expn_id: ExpnId(4294967295) } }, expr: Expr { id: 30826, node: ExprPath(None, Path { span: Span { lo: BytePos(4847523), hi: BytePos(4847538), expn_id: ExpnId(4294967295) }, global: false, segments: [PathSegment { identifier: sys#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }, PathSegment { identifier: MUTEX_INIT#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }] }), span: Span { lo: BytePos(4847523), hi: BytePos(4847538), expn_id: ExpnId(4294967295) } }, span: Span { lo: BytePos(4847517), hi: BytePos(4847538), expn_id: ExpnId(4294967295) } }, Field { ident: Spanned { node: poison#0, span: Span { lo: BytePos(1770129), hi: BytePos(1770135), expn_id: ExpnId(4294967295) } }, expr: Expr { id: 30827, node: ExprPath(None, Path { span: Span { lo: BytePos(4847552), hi: BytePos(4847569), expn_id: ExpnId(4294967295) }, global: false, segments: [PathSegment { identifier: poison#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }, PathSegment { identifier: FLAG_INIT#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }] }), span: Span { lo: BytePos(4847552), hi: BytePos(4847569), expn_id: ExpnId(4294967295) } }, span: Span { lo: BytePos(4847544), hi: BytePos(4847569), expn_id: ExpnId(4294967295) } }], None), span: Span { lo: BytePos(4847499), hi: BytePos(4847572), expn_id: ExpnId(4294967295) } })
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /build/rust-git/src/rust/src/libsyntax/diagnostic.rs:129

stack backtrace:
   1:     0x7fd80f5b7162 - sys::backtrace::write::he39ef573dd8c3ec9OBA
   2:     0x7fd80f5dd072 - <unknown>
   3:     0x7fd80f5237b9 - rt::unwind::begin_unwind_inner::he7222b8464970b51knJ
   4:     0x7fd80cb51d9d - <unknown>
   5:     0x7fd80cb51d43 - diagnostic::SpanHandler::span_bug::hc79b73d694041197h0D
   6:     0x7fd80d40ebc3 - session::Session::span_bug::hf68bde274dd6a86aISp
   7:     0x7fd80ed89a5d - <unknown>
   8:     0x7fd80ecbb9f0 - <unknown>
   9:     0x7fd80ec7dd23 - <unknown>
  10:     0x7fd80ec7e0cd - <unknown>
  11:     0x7fd80eccf50f - <unknown>
  12:     0x7fd80eccff0c - <unknown>
  13:     0x7fd80ecbd941 - <unknown>
  14:     0x7fd80ec7e2c0 - <unknown>
  15:     0x7fd80ecef9a7 - <unknown>
  16:     0x7fd80ecf1d7d - <unknown>
  17:     0x7fd80ecd9136 - <unknown>
  18:     0x7fd80ecbf1e7 - <unknown>
  19:     0x7fd80ec7e29f - <unknown>
  20:     0x7fd80ec7ee17 - <unknown>
  21:     0x7fd80ed3b4d0 - <unknown>
  22:     0x7fd80ec6e62b - <unknown>
  23:     0x7fd80ec6f77d - <unknown>
  24:     0x7fd80eca5c8f - <unknown>
  25:     0x7fd80eca47f9 - <unknown>
  26:     0x7fd80eca2802 - <unknown>
  27:     0x7fd80ecb5882 - <unknown>
  28:     0x7fd80ecbf657 - <unknown>
  29:     0x7fd80ec7e29f - <unknown>
  30:     0x7fd80ecef9a7 - <unknown>
  31:     0x7fd80ecf1d7d - <unknown>
  32:     0x7fd80ecd9136 - <unknown>
  33:     0x7fd80ecbf1e7 - <unknown>
  34:     0x7fd80ec7e29f - <unknown>
  35:     0x7fd80ed6a46e - <unknown>
  36:     0x7fd80ec7d65d - <unknown>
  37:     0x7fd80ec7eaf2 - <unknown>
  38:     0x7fd80ed3b4d0 - <unknown>
  39:     0x7fd80ec6e62b - <unknown>
  40:     0x7fd80ec6ae39 - <unknown>
  41:     0x7fd80ec6a69c - <unknown>
  42:     0x7fd80ec6a69c - <unknown>
  43:     0x7fd80ed41a1c - trans::base::trans_crate::hc448fc5f3519e2c4GPu
  44:     0x7fd80fbcee52 - driver::phase_4_translate_to_llvm::he857f1de87b58ccdrNa
  45:     0x7fd80fbaa8c8 - driver::compile_input::h31c205a2fc532afbIba
  46:     0x7fd80fc740cd - run_compiler::hf221d94bfeef6841H5b
  47:     0x7fd80fc71d7c - <unknown>
  48:     0x7fd80fc709d0 - <unknown>
  49:     0x7fd80f640178 - <unknown>
  50:     0x7fd80f640165 - rust_try
  51:     0x7fd80fc7115b - <unknown>
  52:     0x7fd80f5ca875 - <unknown>
  53:     0x7fd80972d373 - start_thread
  54:     0x7fd80f1ab27c - __clone
  55:                0x0 - <unknown>

Envrionment:
pacman -Qi rust-git
Name           : rust-git
Version        : 1:1.0.0.alpha.2.625.g3b3bb0e-1
Description    : A safe, concurrent, practical language from Mozilla.
Architecture   : x86_64
URL            : http://www.rust-lang.org/
Licenses       : MIT  Apache
Groups         : None
Provides       : rust
Depends On     : None
Optional Deps  : rust-doc-git: language and API documentation
                 vim-rust-git: support for Vim [installed]
Required By    : cargo-git
Optional For   : vim-rust-git
Conflicts With : rust
Replaces       : None
Installed Size : 124.25 MiB
Packager       : lilac (on build machine by lilydjwg) <lilac@build.archlinuxcn.org>
Build Date     : Thu Mar 5 03:20:28 2015
Install Date   : Thu Mar 5 20:58:36 2015
Install Reason : Explicitly installed
Install Script : No
Validated By   : Signature

**Comment by gordon1992** [comment]
Another possible related instance:

===== Rustc version =====
rustc 1.0.0-nightly (ecf8c64e1 2015-03-21) (built 2015-03-21)

===== The code =====

pub fn mpi_send(buf: *const Copy, count: i32, datatype: MpiDatatype, dest: i32,
    tag: i32, comm: MpiComm) -> i32 {
    unsafe {
        let c_buf: *const c_void = buf as *const _ as *const c_void;
        let ret: i32 = MPI_Send(c_buf, count, datatype, dest, tag, comm);
        return ret;
    }
}

===== The error =====

src/lib.rs:66:36: 66:51 error: internal compiler error: cat_expr Errd
src/lib.rs:66         let c_buf: *const c_void = buf as *const _ as *const c_void;
                                                 ^~~~~~~~~~~~~~~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libsyntax/diagnostic.rs:130

stack backtrace:
   1:        0x111a565fb - sys::backtrace::write::h2e17220098832d46M7C
   2:        0x111a822d8 - panicking::on_panic::he3780cf479056283tXI
   3:        0x11199e1e9 - rt::unwind::begin_unwind_inner::hdeb6773f4dd39fdfdGI
   4:        0x11118ed3e - rt::unwind::begin_unwind::h7270265228366974791
   5:        0x11118eceb - diagnostic::SpanHandler::span_bug::h506d42fa371aa7aeDaB
   6:        0x10e97528c - session::Session::span_bug::hcc89626076ba684f2In
   7:        0x10e11170b - check::regionck::visit_expr::h93faa0c5a0532d9dlDd
   8:        0x10e118e3c - visit::walk_expr::h2204833440589324929
   9:        0x10e11022d - check::regionck::visit_expr::h93faa0c5a0532d9dlDd
  10:        0x10e112071 - check::regionck::visit_local::h9392ec2eef0721a3qAd
  11:        0x10e11921c - visit::walk_expr::h2204833440589324929
  12:        0x10e1109b3 - check::regionck::visit_expr::h93faa0c5a0532d9dlDd
  13:        0x10e10c5f5 - check::regionck::Rcx<'a, 'tcx>::visit_fn_body::hf114659b618536e3yfd
  14:        0x10e19e82a - check::check_bare_fn::h866934e1757608268hn
  15:        0x10e196650 - check::check_item::h403800fd4efc7443MAn
  16:        0x10e26e962 - check_crate::closure.35941
  17:        0x10e2695ca - check_crate::h320237bb33035d06IhC
  18:        0x10df9cff7 - driver::phase_3_run_analysis_passes::hca0b86f3ce648603sGa
  19:        0x10df838a6 - driver::compile_input::hb621269896255433Rba
  20:        0x10e044803 - run_compiler::he5fe70dcf9647a94v2b
  21:        0x10e042325 - thunk::F.Invoke<A, R>::invoke::h8037314873938684718
  22:        0x10e0416e7 - rt::unwind::try::try_fn::h17964722091517927081
  23:        0x111b06d28 - rust_try_inner
  24:        0x111b06d15 - rust_try
  25:        0x10e041a85 - thunk::F.Invoke<A, R>::invoke::h16762831891744995117
  26:        0x111a6cd8d - sys::thread::create::thread_start::h0c25ff99c8b72f012DH
  27:     0x7fff963fc267 - _pthread_body
  28:     0x7fff963fc1e4 - _pthread_start

**Comment by jimmycuadra** [comment]
Also possibly related:

### Code

https://github.com/jimmycuadra/fleet_client/tree/afcf76e41cfb27feffb5d2040c103255bcf18cd8

I couldn't figure out what the core of the issue was, apologies for the lack of real test case.

### rustc version

```
$ rustc --version --verbose
rustc 1.0.0-nightly (123a754cb 2015-03-24) (built 2015-03-25)
binary: rustc
commit-hash: 123a754cb8356d0e78837dd4e58103ad801309ff
commit-date: 2015-03-24
build-date: 2015-03-25
host: x86_64-apple-darwin
release: 1.0.0-nightly
```

### Backtrace

```
$ RUST_BACKTRACE=1 cargo build --verbose
       Fresh unicase v0.0.5
       Fresh rustc-serialize v0.3.7
       Fresh bitflags v0.1.1
       Fresh pkg-config v0.3.2
       Fresh libc v0.1.3
       Fresh gcc v0.3.3
       Fresh httparse v0.0.5
       Fresh matches v0.1.2
       Fresh log v0.3.0
       Fresh url v0.2.28
       Fresh mime v0.0.10
       Fresh num_cpus v0.1.0
       Fresh time v0.1.21
       Fresh openssl-sys v0.5.2
       Fresh openssl v0.5.2
   Compiling fleet_client v0.0.1 (file:///Users/redacted/Code/fleet_client)
     Running `rustc src/lib.rs --crate-name fleet_client --crate-type lib -g -C metadata=143a9fc319f5ec12 -C extra-filename=-143a9fc319f5ec12 --out-dir /Users/redacted/Code/fleet_client/target/debug --emit=dep-info,link -L dependency=/Users/redacted/Code/fleet_client/target/debug -L dependency=/Users/redacted/Code/fleet_client/target/debug/deps --extern rustc_serialize=/Users/redacted/Code/fleet_client/target/debug/deps/librustc_serialize-1d1586c158359402.rlib --extern hyper=/Users/redacted/Code/fleet_client/target/debug/deps/libhyper-66ff64b8b88b65f5.rlib -L native=/Users/redacted/Code/fleet_client/target/debug/build/num_cpus-676e37b6735f47f5/out -L native=/usr/lib -L native=/Users/redacted/Code/fleet_client/target/debug/build/openssl-sys-1f3a6cfa99423735/out -L native=/Users/redacted/Code/fleet_client/target/debug/build/time-4d69cc17d95288c1/out`
       Fresh cookie v0.1.16
       Fresh hyper v0.3.3
src/client.rs:44:40: 44:75 error: internal compiler error: cat_expr Errd
src/client.rs:44                         current_state: UnitStates::from_str(current_state),
                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libsyntax/diagnostic.rs:130

stack backtrace:
   1:        0x11338dea4 - sys::backtrace::write::h78053bbfb550960cgjD
   2:        0x1133b9358 - panicking::on_panic::hc4e82bbd2a46726dR8I
   3:        0x1132d676e - rt::unwind::begin_unwind_inner::h5e8e19c0097ac0cdBRI
   4:        0x112addcbe - rt::unwind::begin_unwind::h8176364159252686369
   5:        0x112addc6b - diagnostic::SpanHandler::span_bug::hdcd6dc2adc048426AaB
   6:        0x1102dbcec - session::Session::span_bug::hd2e8d90e6e32fe5bTHn
   7:        0x10fa774db - check::regionck::visit_expr::h67ec4d109373a14f2Dd
   8:        0x10fa7f099 - visit::walk_expr::h4641389526047920594
   9:        0x10fa76783 - check::regionck::visit_expr::h67ec4d109373a14f2Dd
  10:        0x10fa76783 - check::regionck::visit_expr::h67ec4d109373a14f2Dd
  11:        0x10fa723c5 - check::regionck::Rcx<'a, 'tcx>::visit_fn_body::h91b65695e5e98981fgd
  12:        0x10fa7ef02 - visit::walk_expr::h4641389526047920594
  13:        0x10fa7638d - check::regionck::visit_expr::h67ec4d109373a14f2Dd
  14:        0x10fa7eaf7 - visit::walk_expr::h4641389526047920594
  15:        0x10fa75ccf - check::regionck::visit_expr::h67ec4d109373a14f2Dd
  16:        0x10fa7eaf7 - visit::walk_expr::h4641389526047920594
  17:        0x10fa75ccf - check::regionck::visit_expr::h67ec4d109373a14f2Dd
  18:        0x10fa7eacc - visit::walk_expr::h4641389526047920594
  19:        0x10fa76c9b - check::regionck::visit_expr::h67ec4d109373a14f2Dd
  20:        0x10fa76783 - check::regionck::visit_expr::h67ec4d109373a14f2Dd
  21:        0x10fa7eecb - visit::walk_expr::h4641389526047920594
  22:        0x10fa76353 - check::regionck::visit_expr::h67ec4d109373a14f2Dd
  23:        0x10fa723c5 - check::regionck::Rcx<'a, 'tcx>::visit_fn_body::h91b65695e5e98981fgd
  24:        0x10fb032da - check::check_bare_fn::h4d8e30b5b0012b734jn
  25:        0x10fb06eef - check::check_method_body::h31690ecdf0c794faRRn
  26:        0x10faff9f3 - check::check_item::h4b4a2b730b65c17cMCn
  27:        0x10fb01432 - visit::walk_item::h173672359968486163
  28:        0x10fbd278d - check_crate::closure.35881
  29:        0x10fbcd3da - check_crate::h4e5a2f60ebec7dccblC
  30:        0x10f90b417 - driver::phase_3_run_analysis_passes::h00707ed732905e83rGa
  31:        0x10f8f1816 - driver::compile_input::h22976530edbb8120Rba
  32:        0x10f9ab313 - run_compiler::h6f6a07f7c4e7d147s2b
  33:        0x10f9a8ea5 - thunk::F.Invoke<A, R>::invoke::h5399241532089372082
  34:        0x10f9a8267 - rt::unwind::try::try_fn::h14095088624371570858
  35:        0x11343f468 - rust_try_inner
  36:        0x11343f455 - rust_try
  37:        0x10f9a8605 - thunk::F.Invoke<A, R>::invoke::h14770910994046267349
  38:        0x1133a425d - sys::thread::create::thread_start::h3a4e0027cd5d22bdqPH
  39:     0x7fff8f118267 - _pthread_body
  40:     0x7fff8f1181e4 - _pthread_start

Could not compile `fleet_client`.

Caused by:
  Process didn't exit successfully: `rustc src/lib.rs --crate-name fleet_client --crate-type lib -g -C metadata=143a9fc319f5ec12 -C extra-filename=-143a9fc319f5ec12 --out-dir /Users/redacted/Code/fleet_client/target/debug --emit=dep-info,link -L dependency=/Users/redacted/Code/fleet_client/target/debug -L dependency=/Users/redacted/Code/fleet_client/target/debug/deps --extern rustc_serialize=/Users/redacted/Code/fleet_client/target/debug/deps/librustc_serialize-1d1586c158359402.rlib --extern hyper=/Users/redacted/Code/fleet_client/target/debug/deps/libhyper-66ff64b8b88b65f5.rlib -L native=/Users/redacted/Code/fleet_client/target/debug/build/num_cpus-676e37b6735f47f5/out -L native=/usr/lib -L native=/Users/redacted/Code/fleet_client/target/debug/build/openssl-sys-1f3a6cfa99423735/out -L native=/Users/redacted/Code/fleet_client/target/debug/build/time-4d69cc17d95288c1/out` (exit code: 101)
```

**Comment by arielb1** [comment]
I think these are all fixed.
