### ISSUE TITLE
Documentation shows prototype of a function which is different from actual usage syntax

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust#18889]
http://doc.rust-lang.org/std/mem/fn.size_of.html

Displays `size_of` as:

    pub fn size_of<T>() -> uint

which I've tried to use as:

    std::mem::size_of<T>();

but to my surprise *it didn't work*. For reasons I don't quite understand the compiler accepts `std::mem::size_of::<T>()` (with extra `::`).

I bet there's a very good reason why the syntax is like that, but it's non-obvious.

I wish the documentation was very clear about this (e.g. contained usage example or a note explaining the syntax).

**Comment by steveklabnik** [comment]
I think that simply having examples of usage allevates this issue, so I'm giving it a close.
