### ISSUE TITLE
The various {str,String}::from_utf{8,16}() functions should all return a Result<>

### ISSUE THREAD

**Issue by jamesluke** [rust-lang/rust#18888]
The functions (note the return types):
```rust
collections::str::from_utf8(v: &'a [u8]) -> Option<&'a str>
collections::String::from_utf8(vec: Vec<u8>) -> Result<String, Vec<u8>>
collections::String::from_utf16(v: &[u16]) -> Option<String>
```

As you can see, String::from_utf8 is an odd one out, returning a Result rather than an Option.  I propose that all these functions return a Result, as this more closely matches the semantics of Option and Result.  Option is generally used where Some() or None are *both* valid return values.  Result is used where Ok() is a valid value and Err() means the function could not perform as desired.  The latter more closely matches common use of from_utf8 (we expect this buffer to be a utf8 string, but need to confirm it before turning it into a str or String, and something has gone wrong if it's not utf8).  Running through the rust compiler source code, it's almost exclusively used in this fashion: virtually all cases are followed immediately by a .unwrap(), panicking the task if the buffer was not utf-8.

Exactly what the Result's Err() variant should hold, I do not know.  It seems that it should return a proper FromError-style enum with a variant like UtfDecodeError, but I do now know how many different error enums we want in the standard library.  I leave it to someone else to decide what's most useful and elegant.

**Comment by steveklabnik** [comment]
This is now true.
