### ISSUE TITLE
to_source (and by extension to_tokens and quoute_*!) incorrectly flatten expression tree

### ISSUE THREAD

**Issue by dzamlo** [rust-lang/rust#18886]
When an expression tree is created with the AstBuilder methods (like expr_binary for example), transforming it into source format incorrectly flatten it.

This affect the output of ```--pretty expanded ```. It also affect the result of the to_tokens method and the result of the quote_*! macro.

I made a repository with code to demonstrate issue when using quote_expr!:
https://github.com/dzamlo/test_to_source_expr_flattening

Its possible to manually add parentheses when building the expression as a workaround:
```rust
let expr = cx.expr(DUMMY_SP, ast::ExprParen(expr));
```

The version of rust I tested with is the following:
```
rustc 0.13.0-nightly (40fb87d40 2014-11-10 23:01:57 +0000)
binary: rustc
commit-hash: 40fb87d40f681f5356af42175fc7b85da387f037
commit-date: 2014-11-10 23:01:57 +0000
host: x86_64-unknown-linux-gnu
release: 0.13.0-nightly
```

**Comment by bltavares** [comment]
Triaging:

I've updated the code to use the latest syntax for plugins and it seems to be fixed.

Running `cargo test` with the code on https://github.com/bltavares/test_to_source_expr_flattening everything passes.

@dzamlo I've sent you a pull request with the updated changes for `rustc 1.6.0-nightly (9303055f3 2015-11-19)` – https://github.com/dzamlo/test_to_source_expr_flattening/pull/1

**Comment by dzamlo** [comment]
I can confirm that this bug is resolved.
