### ISSUE TITLE
rustc t.rs -o - no longer interprets '-' as stdout

### ISSUE THREAD

**Issue by ebfe** [rust-lang/rust#18895]
`rustc --emit asm t.rs -o -` no longer writes to stdout but creates the file `-`.

I suspect this worked as expected some time back as the vim ftplugin uses this to implement :RustEmitAsm/Ir commands.

**Comment by steveklabnik** [comment]
Triage: with a `t.rs` containing `main() {}`, and the command-line above, this is still happening.

**Comment by steveklabnik** [comment]
Triage: no change since my last comment

**Comment by Mark-Simulacrum** [comment]
I think it's pretty rare that we actually want to direct output to stdout and generally most compilation will create temporary files for linking and such, so I'm going to go ahead and close this.

AFAICT, fwiw, gcc has the same behavior at least.

**Comment by duckinator** [comment]
I just ran into this problem today -- tried `rust --emit asm test.rs -o -` and it wrote it to the file `./-`.

My usual workaround when programs don't special-case that is to try using `/dev/stdout` directly &mdash; but that just results in this:

```shellsession
$ rustc --emit asm test.rs -o /dev/stdout
error: could not write output to /dev/stdout.test.7rcbfp3g-cgu.0.rcgu.s: Operation not supported

error: aborting due to previous error

$
```
