### ISSUE TITLE
Rust builds on "make uninstall"

### ISSUE THREAD

**Issue by 1sp** [rust-lang/rust#18905]
Rust seems to build even on "make uninstall" , which is quite annoying as build takes a long time to complete. 

Os : Windows 7 64 bits
build : x86_64-pc-windows-gnu
toolset : msys2 64 bits
Rust revision : 8f87538

I am attaching the make log as a gist

https://gist.github.com/1sp/2244abff65c9db812776

**Comment by steveklabnik** [comment]
Has anything changed here since this was reported?

/cc @brson

**Comment by Chuongv** [comment]
Wish I saw this before I ran `make uninstall`  :tired_face: 

I think moving forward running the uninstall script from `/usr/local/lib/rustc` should be enough to uninstall?

**Comment by taralx** [comment]
This is especially obnoxious because generally it's "sudo make uninstall" and that will mess up your build directory with a bunch of root-owned files.

**Comment by alexcrichton** [comment]
Make's now gone, so closing.
