### ISSUE TITLE
Emacs rust-mode: backward-word and backward-kill broken

### ISSUE THREAD

**Issue by fzzy** [rust-lang/rust#18923]
When I move backwards a word (M-b) or delete a word (M-d) while rust-mode and subword-mode are enabled, Emacs' text cursor will skip a snake cased subword.
I sometimes get similar problems with forward word moving as well, but not as often.
(If subword-mode is disabled, both M-f and M-b will advance whole snake cased words, which it doesn't normally do)

I'm not sure if this is just a issue with me, but this problem only occurs with rust-mode and not any other language modes, so I assume it's something with rust-mode.
I don't have any weird settings to my knowledge that should break this.

eg.

what i get
```
before M-b

pub fn mount(&self, path: &str, mount_point: &str, append_to_path: bool) {}
                                           ^

after M-b:

pub fn mount(&self, path: &str, mount_point: &str, append_to_path: bool) {}
                                ^
```

what it should do
```
before M-b

pub fn mount(&self, path: &str, mount_point: &str, append_to_path: bool) {}
                                           ^

after M-b:

pub fn mount(&self, path: &str, mount_point: &str, append_to_path: bool) {}
                                     ^
```

**Comment by pnkfelix** [comment]
part of #8793

**Comment by steveklabnik** [comment]
Moved to rust-lang/rust-mode#11
