### ISSUE TITLE
Can create `&mut` with only `&` in statics

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#18939]
This compiles fine:

```rust
#![allow(dead_code)]

static FOO: [uint, .. 2] = [0, 0];
static BAR: &'static mut [uint, .. 2] = & FOO;

fn main() {}
```

**Comment by nham** [comment]
This seems to be fixed in the current nightly. The updated code is

```rust
static FOO: [usize; 2] = [0, 0];
static BAR: &'static mut [usize; 2] = & FOO;

fn main() {}
```

It does not compile:

    test_18939.rs:2:39: 2:44 error: mismatched types:
     expected `&'static mut [usize; 2]`,
        found `&[usize; 2]`
    (values differ in mutability) [E0308]
    test_18939.rs:2 static BAR: &'static mut [usize; 2] = & FOO;
                                                          ^~~~~
    error: aborting due to previous error

`rustc` version:

    rustc 1.1.0-nightly (435622028 2015-05-04) (built 2015-05-05)

**Comment by steveklabnik** [comment]
Thanks @nham !
