### ISSUE TITLE
Add Rust syntax highlighting to the project used to highlight StackOverflow code

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#18931]
Rust code on SO right now looks pretty nasty. Most egregiously it interprets the lifetime syntax as the start of a string, yielding hilarious results.

Here's the project that SO uses to highlight code:

https://code.google.com/p/google-code-prettify/

It has no "Rust" option, so I have no idea what language SO is currently using to highlight our code. Implement proper Rust support, and once it's accepted into Prettify we'll try to contact SO to get them to update their version.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#699
