### ISSUE TITLE
Mistyping `<>` in return value for `()` could have better error message

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#18945]
This errors but doesn't point out the problem very well:

``` rust
fn fun() -> Option<int> {
    Some<7>
}
fn main(){ 
    fun();
}
```

The error:

```
<anon>:4:1: 4:2 error: unexpected token: `}`
<anon>:4 }
         ^
playpen: application terminated with error code 101
```

Better would be:

``` rust
fn fun() -> Option<int> {
    Some<7>
    //  ^~~~~~~ These should be `()` and not`<>`
}

```

**Comment by steveklabnik** [comment]
This error is much better now:

```
hello.rs:2:13: 3:2 error: chained comparison operators require parentheses
hello.rs:2         Some<7>
hello.rs:3 }
hello.rs:2:13: 3:2 help: use `::<...>` instead of `<...>` if you meant to specify type arguments
hello.rs:3:1: 3:2 error: unexpected token: `}`
hello.rs:3 }
           ^~
```

but still not as helpful as it could be.

**Comment by estebank** [comment]
Full current output:

```
error: chained comparison operators require parentheses
 --> src/main.rs:2:9
  |
2 |       Some<7>
  |  _________^
3 | | }
  | |_^
  |
  = help: use `::<...>` instead of `<...>` if you meant to specify type arguments

error: expected expression, found `}`
 --> src/main.rs:3:1
  |
3 | }
  | ^

error[E0308]: mismatched types
 --> src/main.rs:1:27
  |
1 |   fn fun() -> Option<usize> {
  |  ___________________________^
2 | |     Some<7>
3 | | }
  | |_^ expected enum `std::option::Option`, found ()
  |
  = note: expected type `std::option::Option<usize>`
             found type `()`
```

---

I believe that this ticket is asking for a generic diagnostic check to look code that seems to be setting a type argument on a `fn`, fn struct or a fn enum variant, but in `libsyntax/parser.rs` you only have access to the `Ident`, not the type information in order to limit this suggestion _only_ to fn-like types. A simple solution can be to expand the "type arguments" note to state

    or use `(...)` if you meant to specify fn arguments

**Comment by jean-lourenco** [comment]
@estebank I'd like to try and add that extra compile output that you mentioned.
I'll just need a little bit of time to figure out how to test it, as I'm fairly new to Rust and this project. I've made the change and builded the solution, but the output is still the same. (Probably using the wrong binaries to test or something)

**Comment by estebank** [comment]
It's great @jean-lourenco! Make sure you build using `./x.py build --stage 1`, and you'll find the binary in `build/x86_64-apple-darwin/stage1/bin/rustc`. You can also use `./x.py test --stage 1 src/test`, go get coffee and see if any test actually fails after your modification.

**Comment by colinmarsh19** [comment]
Is this issue still being worked on? @jean-lourenco @estebank @kennytm

**Comment by jean-lourenco** [comment]
@colinmarsh19 the lastest  suggestion by @estebank in https://github.com/rust-lang/rust/issues/18945#issuecomment-331251436 was done on https://github.com/rust-lang/rust/pull/45122.

If there're no more comments/suggestions on the issue, I think it's pretty much done.

**Comment by estebank** [comment]
Closing as I see very little to improve specific to this, other than [the span pointing at `Some<7> }`](https://play.rust-lang.org/?gist=5083806c61a19af4df1b69de8bac3474&version=nightly).
