### ISSUE TITLE
internal compiler error: adt::represent_type called on non-ADT type: &string_cache::atom::Atom in Servo

### ISSUE THREAD

**Issue by Ms2ger** [rust-lang/rust#18957]
Branch: https://github.com/Ms2ger/servo/tree/ICE-attr-prefix-atom

**Comment by tamird** [comment]
Rebased that branch in https://github.com/servo/servo/pull/5777 and could not reproduce the ICE. Suggest closing this.

**Comment by tamird** [comment]
@steveklabnik this should be good to close.

**Comment by steveklabnik** [comment]
Let me know if you need this re-opened, @Ms2ger
