### ISSUE TITLE
gdb+windows: breaking on rust_panic does not yield useful stacktrace

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#18955]
when i break on "rust_panic" i don't get a proper stacktrace. it looks like rust already started unwinding by the time it reaches the "rust_panic" function.

``` gdb
(gdb) step
task '<main>' panicked at 'called `Option::unwrap()` on a `None` value', D:\rust\src\libcore\option.rs:347

Breakpoint 1, 0x000000000048bf90 in rust_panic ()
(gdb) bt
#0  0x000000000048bf90 in rust_panic ()
#1  0x000000000048c8c1 in unwind::begin_unwind_inner::hd7e988ab0ca0dfc40Hc ()
#2  0x0000000000000008 in ?? ()
#3  0x0000000000000016 in ?? ()
#4  0x0000000040000062 in ?? ()
#5  0x0000000000000000 in ?? ()
```

to make sure that stacktraces worked in general i ran a program to a specific line and created a backtrace:

``` gdb
(gdb) bt
#0  yaruml::main () at src/main.rs:25
#1  0x000000000040dc81 in start::closure.2900 ()
#2  0x0000000000000030 in ?? ()
#3  0x0000000000000000 in ?? ()
```

I'm using

```
rustc 0.13.0-dev (07982734a 2014-11-13 12:44:42 +0100)
binary: rustc
commit-hash: 07982734a231f8ac7a77a4c22756521e1d0c2a2d
commit-date: 2014-11-13 12:44:42 +0100
host: x86_64-pc-windows-gnu
release: 0.13.0-dev
```

**Comment by steveklabnik** [comment]
@oli-obk have you tried with gdb 7.7 like @vadimcn ? I wonder if that's the difference here, maybe.

**Comment by vadimcn** [comment]
Looks like Win64 SEH is supported starting with gdb 7.7: http://www.gnu.org/software/gdb/news/

**Comment by steveklabnik** [comment]
Given that it looks like this is probably fixed upstream, and nobody has commented in a long time, I'm giving this a close. Thanks!
