### ISSUE TITLE
emacs: raw strings containing " break syntax highlighting

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang/rust#18950]
A raw string like this breaks highlighting as well as indentation (upon indenting an error about unbalanced parentheses appears):

![2014-11-14-020440_827x1005_scrot](https://cloud.githubusercontent.com/assets/667901/5044196/ab0d8438-6ba2-11e4-8c9f-d6ca1624e505.png)

In the lower split I worked around it for the following lines by ending the line with `// "`;

**Comment by steveklabnik** [comment]
Moved to rust-lang/rust-mode#12
