### ISSUE TITLE
Windows File Not Recognized?

### ISSUE THREAD

**Issue by dubcanada** [rust-lang/rust#18974]
Hello,

I am trying to build rgtk and I keep running into a problem with Rust. I keep getting an error

    error: linking with `gcc` failed: exit code: 1
    note: gcc '-Wl,--enable-long-section-names' '-fno-use-linker-plugin' '-Wl,--nxcompat' '-static-libgcc' '-m64' '-L' 'D:\Tools\Rust\bin\rustlib\x86_64-pc-windows-gnu\lib' '-o' 'D:\Tools\rgtk\examples\gtktest\target\gtktest.exe' 'D:\Tools\rgtk\examples\gtktest\target\gtktest.o' '-fno-lto' '-Wl,--gc-sections' 'D:\Tools\Rust\bin\rustlib\x86_64-pc-windows-gnu\lib\libnative-4e7c5e5c.rlib' 'D:\Tools\rgtk\examples\gtktest\target\deps\librgtk-92ce7c6df576b5bf.rlib' 'D:\Tools\Rust\bin\rustlib\x86_64-pc-windows-gnu\lib\libstd-4e7c5e5c.rlib' 'D:\Tools\Rust\bin\rustlib\x86_64-pc-windows-gnu\lib\libsync-4e7c5e5c.rlib' 'D:\Tools\Rust\bin\rustlib\x86_64-pc-windows-gnu\lib\librustrt-4e7c5e5c.rlib' 'D:\Tools\Rust\bin\rustlib\x86_64-pc-windows-gnu\lib\librand-4e7c5e5c.rlib' 'D:\Tools\Rust\bin\rustlib\x86_64-pc-windows-gnu\lib\libcollections-4e7c5e5c.rlib' 'D:\Tools\Rust\bin\rustlib\x86_64-pc-windows-gnu\lib\libunicode-4e7c5e5c.rlib' 'D:\Tools\Rust\bin\rustlib\x86_64-pc-windows-gnu\lib\liballoc-4e7c5e5c.rlib' 'D:\Tools\Rust\bin\rustlib\x86_64-pc-windows-gnu\lib\liblibc-4e7c5e5c.rlib' 'D:\Tools\Rust\bin\rustlib\x86_64-pc-windows-gnu\lib\libcore-4e7c5e5c.rlib' '-L' 'D:\Tools\rgtk\examples\gtktest\target' '-L' 'D:\Tools\rgtk\examples\gtktest\target\deps' '-L' 'D:\Tools\rgtk\examples\gtktest\target\native\rgtk-92ce7c6df576b5bf' '-L' 'D:\Tools\rgtk\examples\gtktest\.rust' '-L' 'D:\Tools\rgtk\examples\gtktest' '-Wl,--whole-archive' '-Wl,-Bstatic' '-Wl,--no-whole-archive' '-Wl,-Bdynamic' '-lglib-2.0' '-lgtk-3' '-lgio-2.0' '-lgobject-2.0' '-lgdk-3' '-lcairo' '-lws2_32' '-lcompiler-rt'
    note: D:\Tools\rgtk\examples\gtktest\target\gtktest.o: file not recognized: File format not recognized
    collect2.exe: error: ld returned 1 exit status

I can't seem to figure out what is going on. Why am I getting a linker error about `file not recognized: File format not recognized`. I don't believe this has anything to do with rgtk as it happens if I try and compile a normal Rust app as well.

Any ideas what is up?

**Comment by steveklabnik** [comment]
@dubcanada , we haven't heard from you in a while, so I'm giving this a close. If you are still having this issue, please give a shout out to @alexcrichton and @vadimcn with their quesitons, thanks!
