### ISSUE TITLE
`Result::and()` and `Result::and_then()` could be generic over `FromError` implementors

### ISSUE THREAD

**Issue by jakub-** [rust-lang/rust#18991]
The error interoperation RFC (https://github.com/rust-lang/rfcs/pull/201) did not cover adapting the current APIs such as Result to be more general purpose with regards to the new `FromError` trait.

It seems to me that the current signatures of `and` and `and_then`:
```rust
fn and<U>(self, res: Result<U, E>) -> Result<U, E>
fn and_then<U>(self, op: |T| -> Result<U, E>) -> Result<U, E>
```

could now be:
```rust
fn and<U, F: FromError<E>>(self, res: Result<U, F>) -> Result<U, F>
fn and_then<U, F: FromError<E>>(self, op: |T| -> Result<U, F>) -> Result<U, F>
```

to allow using these combinators in the same cross-boundary fashion as the `try!` macro.

This would also require a blanket implementation of `FromError<E>` for any E.

**Comment by steveklabnik** [comment]
I tried to track this down through git, but I couldn't quite figure it out. Did this end up happening or not?

**Comment by jakub-** [comment]
@steveklabnik Sadly not, busy times. :( There was a PR if anyone wants to pick this up and carry on: https://github.com/rust-lang/rust/pull/19078.

**Comment by aturon** [comment]
I'm going to close this for the time being (see [this comment](https://github.com/rust-lang/rust/pull/19078#issuecomment-63515471)). We could certainly revisit it via an RFC later on. Thanks!
