### ISSUE TITLE
rustdoc search fails to find some methods

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#19005]
The [`Float` trait](http://doc.rust-lang.org/std/num/trait.Float.html) has an `abs` method, but [searching for `abs`](http://doc.rust-lang.org/std/?search=abs) currently fails to find it.

**Comment by sfackler** [comment]
This appears to be working now, at least for the case of `Float::abs`.

**Comment by carols10cents** [comment]
Confirmed-- I can see `std::num::Float::abs` in the link posted in the description that goes to http://doc.rust-lang.org/std/?search=abs, so I think this should be closed since it's fixed already, @steveklabnik.

**Comment by alexcrichton** [comment]
Hurray for being fixed!
