### ISSUE TITLE
I'd like an efficient way to discard data from a Reader.

### ISSUE THREAD

**Issue by canndrew** [rust-lang/rust#19022]
# The problem.

Say I want to skip the next `n` bytes of input from a `Reader`. Currently, I can see two ways of doing this, neither of which are ideal. 

* Allocate a `Vec<u8>` of size `n`. Call `read` on it. Discard the `Vec<u8>`.  This has the disadvantage of doing an unnecessary allocation and unnecessary copying. Note that calling `read_exact` is equivalent to this.
* Call `read_u8` `n` times. This has this the disadvantage of doing `n` function calls, which may even translate to `n` syscalls. For any significant `n` this is going to be worse than the first option.

# The solution.

Have `Reader` expose a method `skip_exact` that skips the next `n` bytes. For some readers such as `MemReader` and `BufferedReader` this just means advancing the cursor by `n`. For some other readers this could be implemented using seek. For other readers again this method can be given a default implementation that just calls `read_exact`.

Note that I can't just call `seek(n, SeekCur)`. Not all readers implement `Seek` (socket streams for example) but all readers can be advanced from their current position by - in the worst case - just reading and throwing away data.

**Comment by aturon** [comment]
Closing as a dup of #13989
