### ISSUE TITLE
Make `str` a library type (and lang item)

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#19036]
With DST, there is no longer any reason that `str` needs to be a primitive type; it can instead be defined in the library as a newtype wrapper around `[u8]`. (It will, of course, still need to be a lang item for string literals to work).

The main visible consequence of this change would be the removal of several prelude traits in favor of inherent methods -- so it has some impact on library stabilization.

It may also be that the name could/should be revisited if it is no longer primitive.

**Comment by seanmonstar** [comment]
This is still wanted? It seemed like #19612 it was stated that the core team has changed its mind...

**Comment by aturon** [comment]
@seanmonstar Thanks for the ping. I'm going to close this issue, since it was determined that this change had more downsides than benefits.

**Comment by seanmonstar** [comment]
Was mostly curious since @brson just linked it on the discuss thread about nice-to-haves for 1.0.
