### ISSUE TITLE
mozilla/rust in buildbot

### ISSUE THREAD

**Issue by nodakai** [rust-lang/rust#19052]
Just a nitpicking...  A few references to mozilla/rust rather than rust-lang/rust still remain Rust buildbot.

![buildbot-mozilla-rust](https://cloud.githubusercontent.com/assets/90726/5080117/cd8482c6-6ef6-11e4-890a-cde83fa79410.png)

**Comment by edunham** [comment]
Yep, that was the revlink -- `git grep mozilla` in the rust-buildbot repo caught it.
