### ISSUE TITLE
rustdoc: Trait object (e.g. `impl Any`) inherent methods are not properly documented

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#19055]
### STR

``` rust
pub trait Any {}

impl<'any> Any + 'any {
    /// Returns true if the boxed type is the same as `T`
    pub fn is<T: 'static>(&self) -> bool { unimplemented!() }

    /// Returns some reference to the boxed value if it is of type `T`, or
    /// `None` if it isn't.
    pub fn downcast_ref<'a, T: 'static>(&'a self) -> Option<&'a T> { unimplemented!() }

    /// Returns some mutable reference to the boxed value if it is of type `T`, or
    /// `None` if it isn't.
    pub fn downcast_mut<'a, T: 'static>(&'a mut self) -> Option<&'a mut T> { unimplemented!() }
}
```

### Output

`Any`'s inherent methods appear in the search index:

![search](https://cloud.githubusercontent.com/assets/5018213/5080680/76a9e29e-6e91-11e4-9b56-0be941b28235.png)

But upon clicking the method, you land in the `Any` main page:

![nothing](https://cloud.githubusercontent.com/assets/5018213/5080686/8b922770-6e91-11e4-9ba1-c4e46d24b52a.png)

Where the methods don't show up

**Comment by jdm** [comment]
Now those search results take you to 404s.
