### ISSUE TITLE
Stability story of compiler flags

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#19051]
There's a pile of weird and wonderful flags for `rustc` and we should have some conscious story about them and their stability, even if it's just "they're all unstable".

**Comment by aturon** [comment]
Nominating: we need to consider whether this is essential for beta.

**Comment by pnkfelix** [comment]
Assigning 1.0-beta milestone.

**Comment by kmcallister** [comment]
cc me

**Comment by pnkfelix** [comment]
assigning to @alexcrichton (but I can take it from you if need be)

**Comment by pnkfelix** [comment]
the top-level has been cleaned up, but the sublevels of `-C` etc have not been addressed.

**Comment by pnkfelix** [comment]
reclassifying as 1.0.  (not a beta-blocker at this point.)

**Comment by cmr** [comment]
My inclination is to not make any hard promises about `rustc` compat, but try *really hard* not to break any flag that isn't behind `-h` or `-Z unstable-options`.

**Comment by rprichard** [comment]
The `--cfg` option's argument is lax (#23301), and escaping a string literal is awkward (e.g. `--cfg 'feature="mysql"'` vs `--cfg feature=mysql`).  Is this something to fix for 1.0?

**Comment by brson** [comment]
@rprichard I think #23301 can be done as a bug fix later.

**Comment by brson** [comment]
Re-triaging as P-medium. There doesn't seem much momentum to make any drastic improvements here and the bar to getting into 1.0 is pretty high.

**Comment by alexcrichton** [comment]
All compiler flags at this point are essentially stable, modulo `-Z`, which is covered by https://github.com/rust-lang/rust/issues/31847, so closing in favor of that.
