### ISSUE TITLE
32 bit Windows buildbots yield shell script syntax errors

### ISSUE THREAD

**Issue by nodakai** [rust-lang/rust#19057]
-  http://buildbot.rust-lang.org/builders/auto-win-32-opt/builds/1975 -> compile -> stdio

`/bin/sh: -c: line 0: syntax error near unexpected token ``('`

`/bin/sh: -c: line 0: ``result=""; for arch in i386; do if gcc -arch $arch -c -integrated-as /c/bot/slave/auto-win-32-nopt-t/build/src/compiler-rt/make/platform/clang_darwin_test_input.c -isysroot /c/bot/slave/auto-win-32-nopt-t/build/src/compiler-rt/SDKs/darwin -o /dev/null > /dev/null 2> /dev/null; then if c:/program files (x86)/mingw-w64/i686-4.8.1-win32-dwarf-rt_v3-rev2/mingw32/bin/../lib/gcc/i686-w64-mingw32/4.8.1/../../../../i686-w64-mingw32/bin/ld.exe -v 2>&1 | grep "configured to support" | tr ' ' '\n' | grep "^$arch$" >/dev/null 2>/dev/null; then result="$result$arch "; else printf 1>&2 "warning: clang_darwin.mk: dropping arch '$arch' from lib 'eprintf'"; printf 1>&2 " (ld does not support it)\n"; fi; else printf 1>&2 "warning: clang_darwin.mk: dropping arch '$arch' from lib 'eprintf'"; printf 1>&2 " (clang does not support it)\n"; fi; done; echo $result'`

I'm guessing this is because of `" (ld does not support it)\n"` and `" (clang does not support it)\n"`.

Go to http://buildbot.rust-lang.org/grid?branch=auto&refresh=15 and compare `auto-win-32-*` with other bots.  Only 32 bit Windows bots have this problem.

**Comment by alexcrichton** [comment]
This appears to no longer crop up, so I assume it was fixed in the interim
