### ISSUE TITLE
This DST code causes an llvm assertion failure during compilation.

### ISSUE THREAD

**Issue by canndrew** [rust-lang/rust#19064]
Trying to build this:

```rust
struct Foo(pub str);
    
impl Foo {
  fn print(&self) {
    match self {
      &Foo(ref s)  => println!("f\"{}\"", s),
    }
  }
}
    
fn main() {}
```

and I get this:

    rustc: /home/shum/src/rust/rust/src/llvm/include/llvm/Support/Casting.h:237: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::PointerType; Y = const llvm::Type; typename llvm::cast_retty<X, Y*>::ret_type = const llvm::PointerType*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.

**Comment by arielb1** [comment]
Still crashes in 1.2.0

**Comment by DanielKeep** [comment]
Still happening in 1.7.0 nightly as of now.  I believe I've managed to reduce it further to the following; changing `[()]` out for a non-DST type (like `u8`) causes the failure to go away, as does removing the `&ref`.  Also, thanks to niconii.

`day9asplode.rs`:

```rust
fn main() { if let Some(&ref _x) = Some::<&[()]>(&[]) {} }
```

```shell
[master] > rustc -vV
rustc 1.7.0-nightly (110df043b 2015-12-13)
binary: rustc
commit-hash: 110df043bf585e94764e07700576200290709859
commit-date: 2015-12-13
host: i686-pc-windows-gnu
release: 1.7.0-nightly
[master] > rustc .\src\bin\day9asplode.rs
Assertion failed!

Program: C:\Users\drk\AppData\Local\.multirust\toolchains\nightly\bin\rustc.exe File: C:/bot/slave/nightly-dist-rustc-win-gnu-32/build/src/llvm/include/llvm/Support/Casting.h, Line 237

Expression: isa<X>(Val) && "cast<Ty>() argument of incompatible type!"

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

**Comment by apasel422** [comment]
Triage: Still an issue.

**Comment by jonas-schievink** [comment]
Compiles fine with `-Zorbit`

**Comment by steveklabnik** [comment]
This no longer ICEs as of `rustc 1.11.0-nightly (0554abac6 2016-06-10)`.
