### ISSUE TITLE
mem::{size,align,min_align}_of_val should accept DSTs

### ISSUE THREAD

**Issue by P1start** [rust-lang/rust#19063]
Currently, `mem::size_of_val` and friends only support sized types, and just defer to `mem::size_of` etc.. Ideally, they would also support dynamically-sized types, in a way such that `size_of_val(&[1, 2, 3]: &[int]) == size_of::<int>() * 3`. Because this requires an actual value, they wouldn’t be able to simply defer to calling `size_of` etc. and would instead have to become intrinsic functions. I believe that this issue makes implementing pointer types that accept dynamically-sized type parameters very difficult (if not impossible) (e.g., #18248 (although I think that also might require a way of running destructors for unsized values)).

**Comment by P1start** [comment]
This is almost done now—`size_of_val` and `min_align_of_val` now accept DSTs, but `align_of_val` still doesn’t.

**Comment by eddyb** [comment]
@P1start I wonder how we should go about supporting that, as trait objects store only `min_align_of`.

**Comment by bluss** [comment]
This is fixed -- because align_of_val now is minimum alignment.
