### ISSUE TITLE
Move everything out of the wiki's "Doc" namespace and into the official documentation

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#19074]
The wiki is wanting and almost never updated, yet also highly visible. In the past we have made the wise decision to move various things out of the wiki and into dedicated spaces, such as the weekly meeting notes. We should do this for the docs as well. Go through the "Doc" namespace in the wiki, and for every article in there determine if the article is worth salvaging and if so ensure that there exists an analogous entry somewhere in the official documentation. Afterwards, delete the page from the wiki.

Note as well that there may exist pages in the wiki that belong in the official documentation, but do not live under the "Doc" namespace. Give a cursory examination of all the other articles and see if any need the same treatment.

cc @steveklabnik

**Comment by steveklabnik** [comment]
closing as dup of https://github.com/rust-lang/rust/issues/5831
