### ISSUE TITLE
Import enum variants into implementation section

### ISSUE THREAD

**Issue by vhbit** [rust-lang/rust#19099]
I think it will be quite consistent to allow use enum variants in implementation without full-qualified names like:

``` rust
enum Foo {
  Bar,
  Baz
}

impl Foo {
   fn foo(&self) {
      match self {
         &Bar => println!("bar"), // impossible now, requires &Foo::Bar
         &Baz => println!("baz"), // impossible now, requires &Foo::Baz
      }
   }
}
```

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#764
