### ISSUE TITLE
panicked at 'assertion failed: fd > 0' rust/src/librustdoc/flock.rs:117

### ISSUE THREAD

**Issue by erisfrison** [rust-lang/rust#19093]
```
task '<main>' panicked at 'assertion failed: fd > 0', /home/xxxx/Programs/rust-git/rust/src/librustdoc/flock.rs:117
/home/xxxx/Programs/rust-git/rust/mk/docs.mk:306: recipe for target 'doc/rustc/index.html' failed
make[1]: *** [doc/rustc/index.html] Error 101
make[1]: Leaving directory '/home/xxxx/Programs/rust-git/rust'
/home/xxxx/Programs/rust-git/rust/mk/install.mk:22: recipe for target 'install' failed
make: *** [install] Error 2
```

**Comment by bltavares** [comment]
Hi @erisfrison,

Could you share what OS and which command did you run?

**Comment by erisfrison** [comment]
Ok, long time ago, so I'm not entirely certain. It was probably "make install" on an Ubuntu 14.10.

Don't think it has any relevancy any more as this was one year ago and I'm not experiencing any problems with rust now. Pretty silly of me to not include any details back then.

**Comment by steveklabnik** [comment]
> Pretty silly of me to not include any details back then.

It's all good!

Since you're not affected anymore, I'll close this. Thanks!
