### ISSUE TITLE
Implement cmp and ops reform

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#19148]
Tracking issue for https://github.com/rust-lang/rfcs/pull/439

**Comment by AndyShiue** [comment]
All done?

**Comment by japaric** [comment]
@AndyShiue from the top of my head, as per the RFC the `index(&self, &Index)` method needs to take the `Index` parameter by value instead of by reference. And @nick29581 is unifying the slicing/indexing operators under the `Index` trait.

**Comment by aturon** [comment]
Nominating to move to -beta milestone.

**Comment by pnkfelix** [comment]
Assigning 1.0-beta milestone.
