### ISSUE TITLE
Remove stability and benchmark metric infrastructure

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#19145]
We generate this information and upload it and do nothing with it (and the upload causes https://github.com/rust-lang/rust/issues/19079). Let's just completely remove the code for it (including the never-used ratcheting feature, and probably the test-sharding feature as well).

**Comment by brson** [comment]
Only the stuff in tests.mk has been removed. The test crate still supports a bunch of stuff that should be removed. Here are my suggestions:

* save-metrics - remove
* ratchet-metrics - remove
* ratchet-noise-percent - remove
* test-shard - remove
* boxplot - remove
* boxplot-width - remove
* stats - remove

boxplot and stats are less obvious.

**Comment by ahmedcharles** [comment]
I'm working on removing these. It's just taking a little while to get familiar with the code.

**Comment by kmcallister** [comment]
Does this live on somewhere out-of-tree? I was using it in html5ever.
