### ISSUE TITLE
Rust C Structure alignment mismatch?

### ISSUE THREAD

**Issue by donpdonp** [rust-lang/rust#19189]
I'm trying to craft a binding from rust into mruby (sebastianedwards/rust-mruby is obsolete). In debugging a segfault in a foreign function, I get conflicting answers as to the alignment of a rust struct.

```rust
#[repr(C)]
struct MRubyValue {
  value: [u8, ..8],
  tt: MRubyType,
}
```

Printing the size and align gives
```rust
    println!("MRubyValue size {} align {}", std::mem::size_of::<MRubyValue>(),
                                            std::mem::align_of::<MRubyValue>());
=>
MRubyValue size 12 align 8
```

I found some code on the internet which supposedly prints the same information, but the alignment is different.

```rust
    let tyd =
        unsafe {
            (*std::intrinsics::get_tydesc::<T>())
        };
    println!("name: {} size: {} align: {}", tyd.name, tyd.size, tyd.align);
=>
name: MRubyValue size: 12 align: 4
```

Is this a rust problem or a misunderstanding of the output? Thanks.

**Comment by steveklabnik** [comment]
`tydesc` was  removed in https://github.com/rust-lang/rust/pull/23376, so this is moot now.
