### ISSUE TITLE
libs: generalize `as_ref`/`by_ref` adapters to use `BorrowFrom`

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#19188]
It is a pain to go from `Option<String>` to `Option<&str>`:

``` rust
opt.as_ref().map(|s| s.as_slice())
```

This could be improved by integrating the new `BorrowFrom` infrastructure, generalizing the signature of `as_ref` from

``` rust
fn as_ref(&self) -> Option<&T>
```

to

``` rust
fn as_ref<U=T>(&self) -> Option<&U> where U: BorrowFrom<T>
```

However, to avoid a regression in type inference for types that can be borrowed in multiple ways, we need default type parameters on methods (as above). See https://github.com/rust-lang/rfcs/pull/213

**Comment by apasel422** [comment]
This is now possible, though it requires the `default_type_parameter_fallback` feature gate:
```rust
#![feature(default_type_parameter_fallback)]

use Option::*;
use std::borrow::Borrow;

pub enum Option<T> {
    None,
    Some(T),
}

impl<T> Option<T> {
    pub fn as_ref<U: ?Sized = T>(&self) -> Option<&U> where T: Borrow<U> {
        match *self {
            None => None,
            Some(ref t) => Some(t.borrow()),
        }
    }
}

#[test]
fn test() {
    let opt = Some("foo".to_string());
    let _r1 = opt.as_ref(); // falls back to `Option<&String>`
    let _r2 = opt.as_ref::<str>();
}
```

**Comment by aidanhs** [comment]
On the topic of `Option<String>` to `Option<&str>`, one option is given in http://stackoverflow.com/questions/31233938/converting-from-optionstring-to-optionstr

```
use std::ops::Deref;

trait OptionDeref<T: Deref> {
    fn as_deref(&self) -> Option<&T::Target>;
}

impl<T: Deref> OptionDeref<T> for Option<T> {
    fn as_deref(&self) -> Option<&T::Target> {
        self.as_ref().map(Deref::deref)
    }
}
```

**Comment by aturon** [comment]
Needs RFC (language change)
