### ISSUE TITLE
DST: trait objects should automatically implement the trait

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#19187]
This is a [planned part](https://github.com/rust-lang/rfcs/pull/255) of DST. Example from RFC:

```rust
fn foo<Sized? T: SomeTrait>(y: &T) { ... }

fn bar(x: &SomeTrait) {
    foo(x)
}
```

should be permitted even if there is no explicit impl of `SomeTrait` for `&SomeTrait`.

**Comment by nikomatsakis** [comment]
This was implemented in https://github.com/rust-lang/rust/pull/20341
