### ISSUE TITLE
Poor error messages from `impl EnumValue`

### ISSUE THREAD

**Issue by gmorenz** [rust-lang/rust#19197]
Compiling

```rust
enum E {
    A
}

impl E::A {}
```

Results in

```
tmp.rs:5:6: 5:10 error: inherent implementations may only be implemented in the same module as the type they are implemented for
tmp.rs:5 impl E::A {}
              ^~~~
error: aborting due to previous error
```

Which doesn't seem quite right...

Compiling
```rust
trait T {}

enum E {
    A
}

impl T for E::A {}

fn main(){}
```

Results in

```
tmp.rs:7:12: 7:16 error: found value name used as a type: DefVariant(DefId { krate: 0, node: 7 }, DefId { krate: 0, node: 8 }, false)
tmp.rs:7 impl T for E::A {}
                    ^~~~
```

Which, while being correct, is printing out compiler internals for no obvious reason...

**Comment by nham** [comment]
This is still reproducible. Rust version is:

    rustc 1.1.0-nightly (435622028 2015-05-04) (built 2015-05-05)

Code is:

```rust
enum E {
    A
}

impl E::A {}

fn main() {}
```

The result is:

    test_19197.rs:5:6: 5:10 error: found value name used as a type: DefVariant(DefId { krate: 0, node: 4 }, DefId { krate: 0, node: 5 }, false) [E0248]
    test_19197.rs:5 impl E::A {}
                         ^~~~
    error: aborting due to previous error
