### ISSUE TITLE
Ensure that all dist bots contain build the same set of docs

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#19200]
As mentioned in https://github.com/rust-lang/rust/issues/16456, pandoc/latex are not pervasive and are probably not available on our mac/win builders. We're going to start installing docs and should distribute a consistent set with every platform.

I would not mind solving this by just disabling PDF's from the dist set.

**Comment by steveklabnik** [comment]
We have disabled PDF docs, so this isn't an issue anymore.
