### ISSUE TITLE
absolute path names are not correct for crates not in root namespace

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#1920]
Right now, if you get the absolute path of an item using the `ty::item_path()` function, and that item is an external crate `x`, you always get a path like `x::foo::bar` where `foo::bar` is the path to the item within the crate `x`.  This is usually right but not always, because it is possible that the crate `x` is not linked into the root namespace.

For example, you might have:

```
mod local_mod {
    use x;
    ...
}
```

in which case the right path would be `local_mod::x::foo::bar`.  

To fix this, we ought to store some valid path to the crate along with the crate metadata (preferably a shortest path [there could be more than one shortest path]).  We can then prepend this path.  The function `csearch.rs:get_item_path()` would be the primary one to change.

**Comment by steveklabnik** [comment]
@nikomatsakis , I share @cmr's lack of understanding of what the issue actually is here. And it's been a loooong time. So, without some code to reproduce, I'm giving this a close.

**Comment by cmr** [comment]
I get this now, seeing if I can repro.

**Comment by cmr** [comment]
Repro:

```
mod foo {
	extern crate core;
}

fn assert_clone<T>() where T : Clone { }

fn main() {
	assert_clone::<foo::core::atomic::AtomicBool>();
}
```

```
csguest@itl:~$ rustc foo.rs
foo.rs:8:2: 8:47 error: the trait `core::clone::Clone` is not implemented for the type `core::atomic::AtomicBool`
foo.rs:8 	assert_clone::<foo::core::atomic::AtomicBool>();
         	^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by cmr** [comment]
(note that there is a fixme in the code, as suggested by the issue description)

**Comment by steveklabnik** [comment]
:+1: :heart:

**Comment by nikomatsakis** [comment]
Another related issue here is that we have no way to take into account re-exports -- see the reference to `core`, for example, and not `std`.

**Comment by nikomatsakis** [comment]
(Handling re-exports may require some sort of annotations though.)

**Comment by nikomatsakis** [comment]
ps I remember filing this bug and can hardly believe it's still a thing. ;)

**Comment by carols10cents** [comment]
(Hi, I'm trying to [help make E-easy issues more accessible to newcomers](https://users.rust-lang.org/t/mentoring-newcomers-to-the-rust-ecosystem/3088/15?u=carols10cents) :smile_cat:)

Yup, the failing test case above [is still reproducible](http://is.gd/fMeJff), although I no longer see a fixme anywhere near [`csearch.rs:get_item_path()`](https://github.com/rust-lang/rust/blob/e82faeb65594302897223b2ca4ee6927fb54625f/src/librustc/metadata/csearch.rs#L83).

I'm not at all clear on what would need to be changed about `get_item_path` to make the test case pass though, especially with all the short variable names... @nikomatsakis could you clarify a bit, with kind of an outline of what needs to be changed? Or is this issue not really E-easy?

**Comment by nikomatsakis** [comment]
Hmm. There was an effort to fix this. Not sure why it is not handling that test case.I will investigate.

**Comment by mitaa** [comment]
There is a [compile-fail test](https://github.com/rust-lang/rust/blob/master/src/test/compile-fail/issue-1920-1.rs) for this case, so this should work, though this change is [not in stable rust yet](https://github.com/rust-lang/rust/blob/stable/src/librustc/metadata/csearch.rs#L92).

**Comment by Toby-S** [comment]
[Updated test case](https://play.rust-lang.org/?gist=c7d9f3b589d1724383d2&version=nightly):

```rust
mod foo {
    extern crate core;
}

fn assert_clone<T>() where T : Clone { }

fn main() {
    assert_clone::<foo::core::sync::atomic::AtomicBool>();
}
```

Still reproducible on the current nightly (2015-10-27)

**Comment by jonas-schievink** [comment]
But it looks correct?
```
<anon>:8:5: 8:56 error: the trait `foo::core::clone::Clone` is not implemented for the type `foo::core::sync::atomic::AtomicBool` [E0277]
<anon>:8     assert_clone::<foo::core::sync::atomic::AtomicBool>();
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The nightly is fine, stable isn't, so this looks fixed.

**Comment by nikomatsakis** [comment]
Closing as fixed, thanks!

**Comment by Toby-S** [comment]
@jonas-schievink oops sorry, you're right, this is fixed.
