### ISSUE TITLE
Prominently document that overlong bitshifts cause undefined behavior

### ISSUE THREAD

**Issue by pythonesque** [rust-lang/rust#19214]
Per #10183.  This is a soundness hole and it seems unlikely to be fixed before 1.0.   It needs to be clearly documented in the reference and elsewhere so people know that they have to write their code carefully to avoid it.  See http://www.postgresql.org/docs/9.1/static/indexes-types.html caveats on hash indexes for an example of how to document major bugs in this way.

**Comment by steveklabnik** [comment]
The overflow RFC addresses this, and I have a bug open to reconcile all RFCs with the reference, so this will be taken care of as part of that.
