### ISSUE TITLE
Add non-allocating sort function to libcore

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#19221]

**Comment by Gankro** [comment]
I started looking into this. GrailSort is a bit faster for some inputs (by the Wikisort author's own claim), but WikiSort is *considerably* better documented. As such it seems like the more promising algorithm to duplicate.

That said, it's *complex*. An optimized Wikisort involves an implementation of insertion sort, vanilla merge sort, sorting networks (with side-tables for stability), and of course the actual wikisort algorithm. All in all the impl ends up being about 900 lines of well-documented C++ code. Not insane, but not a walk in the park, either.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#790
