### ISSUE TITLE
Consider building the standard library with Cargo

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#19240]
This is distinct from #16091. Once we've hit `1.0.0`, there's no better way to dogfood that stability than have the standard library a normal part of the Cargo ecosystem. The main benefit is that cross-compiling suddenly becomes a lot easier, especially for bare-metal targets: just use the normal `--target` with `cargo`. It also means that the answer to "do I need to add a line to my `Cargo.toml`" becomes a lot easier.

Cargo would inject references to `std` etc automatically, with an opt-out flag at the package level for things such as `zinc` or operating system kernels.

Building `rustc` would become slightly more interesting, but would probably just involve juggling with the `PATH` so that Cargo is pointed at the right place.

**Comment by steveklabnik** [comment]
Traige: this is still desired, and there were even some PRs to start work on it, but it never landed.

**Comment by Gankro** [comment]
Upon rereading this more closely, I'm mostly only interested in the cited precursor, #16091

**Comment by steveklabnik** [comment]
Yes, I would imagine that we'd want to do it all, these days.

**Comment by cmr** [comment]
Yep
