### ISSUE TITLE
Generic functions can't use str's ToJson impl

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang/rust#19256]
As an example:

```rust
extern crate serialize;
use serialize::json::ToJson;

fn f<T: ToJson>(x: T) {
    println!("{}", x.to_json().to_pretty_str());
}

fn main() {
    f(123i32); // fine
    f(vec![123i32, 4, 5, 6]); // fine
    f("foo") // error: the trait `serialize::json::ToJson` is not implemented for the type `&str`
}
```

The fix is probably just as simple as adding an impl for `&str` to libserialize, but I don't know if there is a better/more general solution to this. Interestingly, calling `f` with a borrowed slice like `&[i32]` works just fine even though there is only an impl on `<T: ToJson> [T]` and not `<T: ToJson> &[T]`.

**Comment by arielb1** [comment]
libserialize is no longer a user-exposed part of Rust. Anyway, the correct way is to take the argument by reference (`fn foo<T: ToJson>(t: &T)`). The "does not allow unsized type" issue is gone.
