### ISSUE TITLE
libs: clean up enums now that namespacing has arrived

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#19253]
Now that [enums are namespaced](https://github.com/rust-lang/rfcs/pull/390), there's a fair amount of cleanup work to do in `libstd`.

In particular:

* During the rollout of the feature, variants were re-exported at the top level to minimize churn. But the new idiom is to keep these items namespaced under the enum. In most cases, these re-exports should be removed.

* Some variants included prefixes or suffixes in their names as a way to work around the lack of namespacing. These should be renamed.

A lot of this work will happen naturally during API stabilization, but it's also something that can tackled in parallel to help speed things up.

**Comment by steveklabnik** [comment]
I think this is done now, please let me know if there's anything left oustanding.
