### ISSUE TITLE
Support installing multiple release channels

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#19263]
Rust is going to have [three release channels](https://github.com/rust-lang/rfcs/pull/475): stable, beta, and nightly. Each of them has its use (that’s why they exist), so it will probably be common to have more than one of them installed at the same time on the same machine (such as a developer’s laptop).

Currently, this it is possible to install multiple rusts at different locations, and set up the `PATH` and (since the [rpath removal]) `LD_LIBRARY_PATH` environment variables to pick one of them. However this is error-prone and not very convenient.

It would be better if multiple versions could be installed in the same "prefix" (e.g. `/usr`, where the default environment variables Just Work<sup>®</sup>). Executables could have a suffix to distinguish them, for example `/usr/bin/rustc` (stable), `/usr/bin/rustc-beta` and `/usr/bin/rustc-nightly`. Other files would have to be namespaced somehow to avoid conflicts.

(Corresponding Cargo issue: https://github.com/rust-lang/cargo/issues/967)

**Comment by williamh** [comment]
Hello, 

I am a co-maintainer of rust on Gentoo.

Are there any updates on this issue? What is the appropriate way to install multiple release channels?

Thanks much,

William

**Comment by SimonSapin** [comment]
I believe the compiler itself can add support for things (though I’m not sure what exactly) to make this easier. In the meantime:

Brian has been working on https://github.com/brson/multirust , which I believe is the best we can do right now. You probably don’t want to import it as-is into the Gentoo packaging system, but you could take ideas. Specifically, it "installs" different Rust versions in different directories. (It just extracts tarballs with pre-built binaries, but I believe it’s equivalent to building with `./configure --prefix=/something`.) Then, wrapper scripts run executables from one install or another after setting up the environment, most importantly the `LD_LIBRARY_PATH` variable.

**Comment by steveklabnik** [comment]
Triage: multirust has matured significantly.

**Comment by paulp** [comment]
Here's one unfortunate case where multirust doesn't help, and other than bringing back rtool I'm not sure what will. It seems like it should be a non-negotiable requirement that one can run a program after building it without having to invoke any black magic between build and run.
```
% multirust run nightly cargo build
   Compiling regex v0.1.30
   Compiling libc v0.1.8
   Compiling log v0.3.1
   Compiling rand v0.3.8
   Compiling getopts v0.2.11
   Compiling tempfile v0.3.0
   Compiling env_logger v0.3.1
   Compiling rusti v0.0.1 (file:///l/src/rust/rusti)

% ./target/debug/rusti
dyld: Library not loaded: x86_64-apple-darwin/stage2/lib/rustlib/x86_64-apple-darwin/lib/librustc_driver-11582ce5.dylib
  Referenced from: /l/src/rust/rusti/./target/debug/rusti
  Reason: image not found
Trace/BPT trap: 5 (core dumped)

% multirust run nightly bash
% ./target/debug/rusti
rusti=>
```

**Comment by benaryorg** [comment]
@williamh Just to mention it, Gentoo deals with multiple rust installations already and names them e.g. `/usr/bin/rustc-9999` and manages a symlink using `eselect`.

So there is the overlay called rust (obviously) which contains the special versions rust-9999 (git) and rust-999 (nightly).

Would it be possible to have rust (binary named *-stable), rust-beta and rust-nightly in this repo?
Then I could manage my versions (which are updated as expected by the package manager) using eselect for the default compiler and still use rustc-beta and rustc-nightly or rustc-9999 for the other versions.

This way I could test packages much more easily.

**Comment by alexcrichton** [comment]
I believe multirust is basically our answer here, so closing, yay!

**Comment by retep998** [comment]
Now if only we had a Windows equivalent!
