### ISSUE TITLE
Publish guidelines somewhere official

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#19315]
The coding guidelines are currently hosted at @aturon's github page: http://aturon.github.io/. These should be hosted somewhere official. Requires some network setup and possibly automation since there's a build step.

**Comment by kmcallister** [comment]
Is it linked from anywhere?

**Comment by steveklabnik** [comment]
Not yet. We wanted to make them more complete first, IIRC

**Comment by edunham** [comment]
@steveklabnik Is there some metric of "done enough" that we can use to decide when it's time to link them from public places? I'd like to make sure the linking task doesn't get lost by filing an issue, but am not sure what to call it.

**Comment by steveklabnik** [comment]
That is a good question. @aturon?

**Comment by antrik** [comment]
I'd like to point out that in lack of a rendered/linked version from the "official" repository, everyone just keeps linking to http://aturon.github.io/ , which I suppose is an outdated snapshot? No matter how "unfinished" the official one is considered, having an even more unfinished version as the only one public is certainly worse.

**Comment by steveklabnik** [comment]
They're very, very close to each other, at least.
