### ISSUE TITLE
Splitting up standard libraries from the main repo

### ISSUE THREAD

**Issue by Binero** [rust-lang/rust#19314]
This is somewhat related to issue https://github.com/rust-lang/rust/issues/19240. 

By putting the standard libraries all in one seperate repository, or even each one in their own, it'd make porting rust conciderably easier. It would remove the need to work inside the rustc file tree, and it would make the build process way easier.

**Comment by kmcallister** [comment]
This is underway, e.g. [time](https://crates.io/crates/time) and [log](https://crates.io/crates/log) have moved to crates.io.  We have an ongoing goal to do this to the degree possible, so I don't think there's a specific actionable ticket here.
