### ISSUE TITLE
Rustdoc should include date and version number

### ISSUE THREAD

**Issue by jemcroft** [rust-lang/rust#19332]
Reading rust documentation online can be confusing because it may be out of date with the latest version.
The output of rustdoc should including the date and version number of the crate to help identify if the documentation is relevant.

**Comment by mdinger** [comment]
This is a dup of https://github.com/rust-lang/rust/issues/17058 which was closed as a dup of the less specific https://github.com/rust-lang/rust/issues/14466

**Comment by jemcroft** [comment]
This is still a problem. The duplicates are concerned with version/build date of the `rust::std` documentation, and the proposed solution is look at the url which encodes the version. However, the problem still exists for documentation for crates not distrubuted with rust.

**Comment by steveklabnik** [comment]
We have another bug open for that: https://github.com/rust-lang/rust/issues/24336
