### ISSUE TITLE
&[T] should implement all traits that [T] implements

### ISSUE THREAD

**Issue by nwin** [rust-lang/rust#19346]
The current implementation is very limiting if I want to create a struct that can hold an `Index<uint, u8>`. Limiting in that sense, that the structure can’t hold a `&[u8]` (only `[T]` implements `Index`). 

Example:
```rust
struct Data<C: Index<uint, u8>> {
    data: C
}

fn main() {
    let a: Data<Vec<u8>>;
    let b: Data<&[u8]>;
}
```

I can't use a reference because `Data<Vec<u8>>` would not be `Send` any more. I can't use a `Box` because then I can't use `&[u8]` any more. The only solution (I can see) is that `&[T]` has to implement `Index` and all the other traits of `[T]`.

**Comment by steveklabnik** [comment]
@rust-lang/lang , is this something we'd want to support? They're different types, no?

**Comment by nikomatsakis** [comment]
Yes, these are distinct types, and we can't make one automatically support the methods of the other in general. So @nwin you may want to consider implementing the `Index` trait on `&[T]`, as you describe. Whether that makes sense is not immediately obvious to me, the @rust-lang/libs team members probably have an opinion. Going to close this issue in the meantime.
