### ISSUE TITLE
sync::mutex::StaticMutex disappeared from public API, perhaps unintentionally?

### ISSUE THREAD

**Issue by emk** [rust-lang/rust#19379]
This seems to have been removed here, as part of the sync cleanup for #19274: 689ef2dabfa3b2b379c953e5fb68ce2c805c2231

The commit message says:

> Because this removes the `libsync` crate, it is a:
>     
> [breaking-change]
>     
> However, all uses of `libsync` should be able to reroute through
> `std::sync` and `std::comm` instead.

My [use-case for `StaticMutex` was protecting global state in C libraries](http://stackoverflow.com/questions/27065466/synchronizing-access-to-ffi-calls-in-rust-via-a-global-rwlock) in emk/rust-cld2 using code like:

```rust
extern crate sync;
use sync::mutex::{StaticMutex, MUTEX_INIT};

static LIBRARY_LOCK: StaticMutex = MUTEX_INIT;

fn access_global_resource() {
    let _ = LIBRARY_LOCK.lock();
    unsafe { call_thread_unsafe_c_api(); }
}
```

Is there a clean way to do this with guards, etc.? I suppose I could use `Once` to bootstrap my way up to a global mutex, and use that to guard `call_thread_unsafe_c_api`, but that seems a lot more complicated than using `StaticMutex`. Am I simply missing the obvious solution here?

Thank you very much for working to rationalize `sync`!

cc @bors @alexcrichton

**Comment by kmcallister** [comment]
`StaticMutex` is back in `std::sync`.  I believe there's no `StaticNativeMutex` anymore, because that's the only kind.
