### ISSUE TITLE
Add default!() macro to builtins

### ISSUE THREAD

**Issue by icorderi** [rust-lang/rust#19389]
I run into this across several files in my project, I have fields now and then on my structs that I don't care about much about and I want to initialize them to default... initialize them to default... to default.

You get the point.

I would like to suggest adding this macro to the builtins that makes using defaults slightly less painful.

```rust
macro_rules! default(
    () => (::std::default::Default::default());
)
```

**Comment by kmcallister** [comment]
`Default` is addressed in the std reforms and any further change would require an RFC.
