### ISSUE TITLE
Coercions for inner trait objects like Option<&A> → Option<&Trait>

### ISSUE THREAD

**Issue by chcokr** [rust-lang/rust#19400]
The following code doesn't compile, with the message "expected trait T but found struct A."

```Rust
trait T {}
struct A;
impl T for A {}

fn foo(a : Option<&T>) {}
foo(Some(&A));
```

I do understand that type hinting solves the problem; the following does compile:

```Rust
foo(Some::<&T>(&A));
```

So my issue was that in the first code snippet, I expected type inference between `Option<&A>` and `Option<&T>`. Is such type inference expected in a future release, or is it against the language specs? Thanks.

**Comment by arielb1** [comment]
This was fixed as part of the DST coercions work.
