### ISSUE TITLE
libstd: io::File cannot produce CR+LF texts even on Windows

### ISSUE THREAD

**Issue by nodakai** [rust-lang/rust#19403]
This is because `std::sys::fs::open()` (on Win32) is hardcoded not to pass `_O_TEXT` to MSVCRT `_open_osfhandle()` (In C, the C runtime is typically responsible for encoding the abstract "newline" character to platform-specific byte sequence.)

- https://github.com/rust-lang/rust/blob/master/src/libstd/sys/windows/fs.rs#L172
- http://msdn.microsoft.com/en-us/library/bdts1c9x.aspx `_open_osfhandle`

The symptom is, `notepad.exe` cannot correctly read text files produced by `io::File`.   It is associated to `.TXT` files on Windows by default.

To our (un?)luck, the `cmd.exe` console starts a new line with only an LF character.

Java and .NET address this issue by defining utilities to specifically handle "stream of characters/texts" in addition to those for byte stream:

- https://docs.oracle.com/javase/8/docs/api/java/io/Reader.html
- http://msdn.microsoft.com/en-us/library/system.io.textreader.aspx

**Comment by alexcrichton** [comment]
I believe this is obsolete now that we no longer use file descriptors (or `open`) but rather using a `HANDLE` in `std::fs`

**Comment by nodakai** [comment]
@alexcrichton My point is not whether Rust's `File` should use a file descriptor from MSVCRT or `HANDLE` from Win32 API and closing this issue is invalid.  Let me repeat relevant points from my original comment:

> The symptom is, `notepad.exe` cannot correctly read text files produced by `io::File`. It is associated to `.TXT` files on Windows by default.
> 
> To our (un?)luck, the `cmd.exe` console starts a new line with only an `LF` character.
> 
> Java and .NET address this issue by defining utilities to specifically handle "stream of characters/texts" in addition to those for byte stream:
> 
> * https://docs.oracle.com/javase/8/docs/api/java/io/Reader.html
> * http://msdn.microsoft.com/en-us/library/system.io.textreader.aspx

**Comment by retep998** [comment]
The point is that you want a special stream specifically for text which converts `\n` to `\r\n` on Windows?

**Comment by alexcrichton** [comment]
If this is an issue about adding a stream which deals with `\n` and `\r\n` differences (as @retep998 mentioned) then it now belongs in the RFC repo because the raw `io::File` will likely not handle it by default but would instead require a wrapper.
