### ISSUE TITLE
Doc comments to attribute conversion without syntactic sugar

### ISSUE THREAD

**Issue by l0kod** [rust-lang/rust#19420]
Like the doc [said](http://doc.rust-lang.org/reference.html#comments) and then [refute](http://doc.rust-lang.org/reference.html#miscellaneous-attributes), `/// Foo` turns into `#[doc="/// Foo"]` which is a [bug](https://github.com/rust-lang/rust/pull/18376#issuecomment-60689542). It should turns into `#[doc="Foo"]` (without the `///`). Same apply for `/** … */`.

This is an issue for macro using the `meta` matcher (cf. #13067) to insert doc into generated code.

cc #18376
cc #10642
cc #6444

**Comment by TyOverby** [comment]
Another interesting symptom is that it doesn't insert any whitespace. Everything gets run together on one line making it look like this in the docs.

```/// Sets the global velocity damping. /// /// Defaults to 1.0 (no damping). /// /// This value is the fraction of velocity a body should have after 1 /// second. A value of 0.9 would mean that each second, a body would have /// 90% of the velocity it had the previous second.```

**Comment by huonw** [comment]
I believe this is still an issue, although I'm not sure I understand why this affects the use of `meta` (this issue is a bit old, but maybe you remember, @l0kod?).

**Comment by sanmai-NL** [comment]
@steveklabnik: Should this old issue receive additional tags and/or be closed?

**Comment by steveklabnik** [comment]
yup, without more info, gonna consider this one closed. @l0kod if you still have something here, please just open a new issue with the current context, thanks!
