### ISSUE TITLE
Expose a non-allocating way to access the current task name.

### ISSUE THREAD

**Issue by reem** [rust-lang/rust#19445]
Currently, `std::task::name` allocates a new `String` for the current task name, but this is unnecessary and slow.

Note: this probably requires a `'thread` lifetime or a reference type specific to thread-local values, perhaps `struct ThreadRef<T> { nosend: NoSend, ref: &'static T }`, but I haven't really thought through all the use cases.

**Comment by steveklabnik** [comment]
And even then, `Rc` boxes its contents, so it's going to end up being heap allocated anyway. Given the constaints, I'm not sure this is possible.

**Comment by reem** [comment]
I think I have a non-allocating solution using `&'static RefCell<&'static str>` and some `!Send` impls, but it's much too complicated to be ergonomically used here. `String` is fine.
