### ISSUE TITLE
Variable name with internal double-underscore gets snake case warning, but leading/trailing does not

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#19475]
``` rust
#![allow(unused_variables)]

fn main() {
    let x__y = 0u;

    let __xy = 0u;
    let xy__ = 0u;
}
```

```
doubleunder.rs:4:9: 4:13 warning: variable `x__y` should have a snake case name such as `x_y`, #[warn(non_snake_case)] on by default
doubleunder.rs:4     let x__y = 0u;
                         ^~~~
```

It seems slightly weird that we are inconsistent.

**Comment by frewsxcv** [comment]
1.1.0 Update: The warning is still given for `x__y`

Playpen: http://is.gd/mmKJtz

**Comment by steveklabnik** [comment]
Triage: no change.

    o_____o

😉

**Comment by Mark-Simulacrum** [comment]
I think the leading `__` case is intentional, but uncertain about trailing.

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by Mark-Simulacrum** [comment]
The test case for this lint has two "don't allow two underscores" cases (https://github.com/rust-lang/rust/blob/master/src/test/ui/lint/lint-non-snake-case-functions.rs). I'm going to say that's probably enough that we don't want to just change behavior here -- in particular, it seems no one really wants this. (If they do, I would encourage them to file a PR or chime in here).

**Comment by chadaustin** [comment]
> in particular, it seems no one really wants this. (If they do, I would encourage them to file a PR or chime in here).

I suppose I will chime in! I work on firmware for a quite sophisticated chip with a bunch of memory-mapped IO and hardware-defined constants. Through a mix of hand authoring and generated Rust code, we end up with a pile of constants named things
* BOARD_SOC_CHIP_REGISTER_BLOCK__ADDR
* BOARD_SOC_CHIP_REGISTER_BLOCK__SIZE
