### ISSUE TITLE
Valgrind failure during unwinding in trans

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#19481]
I ran into a mysterious valgrind issue that I didn't have time to pin down. The problem seems to be involved with the handoff of ownership from caller to callee; valgrind reports reads of freed memory, basically. There is a "FIXME" commit that converts a fn that took `Vec<T>` to `&[T]`, avoiding the problem (in this particular case, taking a `Vec<T>` was a bit silly anyhow).

**Comment by kmcallister** [comment]
Sounds like a lurking soundness issue. Nominating to revisit this.

**Comment by pnkfelix** [comment]
P-low, not 1.0.

**Comment by pnkfelix** [comment]
(niko pushed for P-high instead)

**Comment by tamird** [comment]
What's the action item here? Revert the fixme commit and run `dst-object-from-unsized-type.rs`?

**Comment by brson** [comment]
Old issue, lots of changes since.
