### ISSUE TITLE
Add Rust support to gdb

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#19531]
[Calling functions in gdb](https://github.com/rust-lang/rust/issues/12868) among other things requires direct debugger support. We'll have to start modifying gdb.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#767
