### ISSUE TITLE
Macro Documentation Incorrect

### ISSUE THREAD

**Issue by maxsnew** [rust-lang/rust#19540]
The Reference: http://doc.rust-lang.org/reference.html#macro-by-example says that `matchers` is a valid designator, however, writing a macro that uses the designator yields an error:
```rust
#![feature(macro_rules)]
macro_rules! doesntwork(
    ($x:matchers) => ({$x})
)

fn main() {
    doesntwork!(3);
}
```
compile with `rustc` and get
```
foo.rs:7:17: 7:18 error: unsupported builtin nonterminal parser: matchers
foo.rs:7     doesntwork!(3);
```
`matcher` doesn't work either, is such a thing supported? Also the documentation on what any of the designators mean is extremely thin.

**Comment by steveklabnik** [comment]
This is no longer in the reference.
