### ISSUE TITLE
Macro Guide: Invocation syntax section doesn't describe fragment specifier used in introductory example

### ISSUE THREAD

**Issue by cdouglass** [rust-lang/rust#19554]
Section 2.0, describing invocation syntax, describes the fragment specifiers ident, expr, ty, pat, and block. It would be helpful if it mentioned path as well since that's used in the introductory example:
```rust
macro_rules! early_return(
    ($inp:expr $sp:path) => ( // invoke it like `(input_5 SpecialE)`
        match $inp {
            $sp(x) => { return x; }
            _ => {}
        }
    );
)
```

**Comment by kmcallister** [comment]
That whole section has been re-written. I linked the [complete list of fragment specifiers](http://doc.rust-lang.org/book/advanced-macros.html#syntactic-requirements) from the place where the "fragment specifier" concept is introduced.
