### ISSUE TITLE
`std::slice::BinarySearchResult` should have a method to just get the inner value

### ISSUE THREAD

**Issue by utkarshkukreti** [rust-lang/rust#19562]
[(I don't think this requires an RFC.)](https://github.com/rust-lang/rfcs#when-you-need-to-follow-this-process)

I'm using `.binary_search` method on (pre-sorted) slices to get the index where a value should be inserted to keep the slice sorted. Right now I have to write something like:

```
match slice.binary_search(...) {
    BinarySearchResult::Found(n) => n,
    BinarySearchResult::NotFound(n) => n
}
```

This should probably be a method on the `BinarySearchResult` enum.

I'd submit a pull request but I'm not sure what the method should be called.

**Comment by pyfisch** [comment]
BinarySearchResult got removed, so this is obsolete, I think.
https://github.com/rust-lang/rust/commit/67d13883f868e6b27aa00a6c69f7c748d16e1c94#diff-91f9d2237c7851d61911b0ca64792a88L1228

**Comment by utkarshkukreti** [comment]
Oh nice! It returns `Result<uint, uint>` now, which is good enough for me!
