### ISSUE TITLE
Rustdoc test failures related to automatically inserted code are very confusing

### ISSUE THREAD

**Issue by shamansir** [rust-lang/rust#19565]
In example like this:

```rust
/// ```
/// #![feature(globs)]
///
/// use std::fmt::*;
///
/// fn main() {
///    // a code...
/// }
/// ```
```

If `fn main() {}` is included, _rustdoc_ says:

```
error: an inner attribute is not permitted in this context
#![feature(globs)]
help: place inner attribute at the top of the module or block
```

If there is no `main` function, _rustdoc_ still suggests to add globs feature while it is already there:

```
error: glob import statements are experimental and possibly buggy
help: add #![feature(globs)] to the crate attributes to enable
```

`rustc -v: rustc 0.13.0-nightly (5484d6f6d 2014-12-02 00:22:00 +0000)`
`rustdoc --version: rustdoc 0.13.0-nightly (5484d6f6d 2014-12-02 00:22:00 +0000)`

**Comment by steveklabnik** [comment]
Rustdoc now compiles this example without error, both with and without main.
