### ISSUE TITLE
Can not import names brought in scope from a private import unless marked public

### ISSUE THREAD

**Issue by Kimundi** [rust-lang/rust#19572]
This fails to compile:

```
use self::b::C;

mod a {
    use super::C;
}

mod b {
    pub struct C;
}

fn main() {}
```
```
<anon>:4:9: 4:17 error: unresolved import `super::C`. There is no `C` in `???`
<anon>:4     use super::C;
                 ^~~~~~~~
```

However, if you change line 1 to `pub use self::b::C;` it works (as expected).

The current privacy rules of Rust state that any parent items are reachable to child modules, and imports are currently on the way to only be regular items, so it should work without the `pub`.

**Comment by steveklabnik** [comment]
Triage: no change. "Work"s exactly the same today.

**Comment by arielb1** [comment]
I was quite sure this was intentional (glob imports).

**Comment by steveklabnik** [comment]
Good question. @rust-lang/lang?

**Comment by Kimundi** [comment]
The current behavior seems to have been by design.

It remains confusing, and might change in the future, but that would be a RFC change rather than a bug, so closing this for now.
