### ISSUE TITLE
Provide a syntax extension to derive traits for a newtype

### ISSUE THREAD

**Issue by aochagavia** [rust-lang/rust#19597]
It would be nice to be able to do something like:

```
#[newtype_deriving(Add, Sub, Mul, Div)]
struct Centimeters(i32);
```

The current solution to this problem (implementing the traits manually), causes a lot of boilerplate and makes usage of newtypes less attractive.

If there is enough interest, I would love to submit a PR for this

cc @aturon

**Comment by kmcallister** [comment]
I think this is a good feature for a version 2 `deriving` system that isn't purely syntax-based.

**Comment by steveklabnik** [comment]
Closing in favor of https://github.com/rust-lang/rfcs/issues/261
