### ISSUE TITLE
run-pass/issue-16671 is ignored on android

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#19591]
It's blocking forever, I'm guessing because read_to_end is?

**Comment by frewsxcv** [comment]
Visiting for triage: it still appears to be ignored

https://github.com/rust-lang/rust/blob/master/src/test/run-pass/issue-16671.rs

**Comment by steveklabnik** [comment]
Triage: no change https://github.com/rust-lang/rust/blob/691eba1358fc3c9c7a8033314a4112d43680c128/src/test/run-pass/issue-16671.rs#L11-L12

**Comment by Mark-Simulacrum** [comment]
Closing. The ignore was removed in https://github.com/rust-lang/rust/pull/40777, which is odd. The MinGW toolchain update itself seems unrelated? @alexcrichton Can you recall why you removed the android ignore?
