### ISSUE TITLE
rustdoc: Optionally generate foo/index.html with foo/ links, instead of foo.html

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#19600]
Currently, rustdoc generates HTML links like `<a href="../std/index.html">` (this is from the crate index side bar.) When docs are served over HTTP(S), with most servers, `<a href="../std/">` works just as well and looks nicer. However this doesn’t work when when locally-generated docs are viewed with `file://…` URLs.

There should be an off-by-default option in rustdoc to generate the shorter links instead.

**Edit:** while we’re at it, every `foo.html` page should also be `foo/index.html` instead, so that short links are not just for pages that are already `something/index.html`.

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/16103.

**Comment by SimonSapin** [comment]
That is not the same (having a top-level index at all vs generating shorter links to existing indices), but I’m not really attached to this anymore so ¯\_(ツ)_/¯

**Comment by Mark-Simulacrum** [comment]
Yeah, I'm also not a fan of breaking `file://` viewing. Will keep closed unless someone requests otherwise.

**Comment by SimonSapin** [comment]
Yes, the suggestion was an off-by-default option.
