### ISSUE TITLE
rustdoc: provide a way to override html_root_url

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#19603]
Rustdoc generates external links for standard library items. For example, `Result` at http://servo.github.io/rust-url/url/type.ParseResult.html links to http://doc.rust-lang.org/nightly/core/result/enum.Result.html

This URL seems to be determined from [the `#[doc(html_root_url = "…")]` attribute](https://github.com/rust-lang/rust/blob/6f4c11be3b9706d1ba0e1b74b89de1478410a56f/src/libcore/lib.rs#L55) in the crate that defines the item. There is apparently no way to override it.

Servo uses a Rust version that is often behind nightly, so I’d like http://doc.servo.org/ to link to docs for the Rust version that’s actually being used. Currently, this is achieved by copying Rust docs from the snapshot to the same location as where Servo docs are being generated. As a result, the crate index side bar lists both Servo and Rust crates, and is hard to read since there are so many of them.

I’d like instead to have docs for our Rust version at a different location, maybe http://doc.servo.org/rust-snapshot/ , and have standard library items link to that. The latter requires rustdoc accepting an override to `html_root_url` of external crates.

**Comment by steveklabnik** [comment]
Triage: I am not aware of any changes in this area.
