### ISSUE TITLE
Re-enable duplicate/unused diagnostic code detection

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#19624]
It was disabled in https://github.com/rust-lang/rust/pull/19362. It'd be good to have it back one way or another.

**Comment by brson** [comment]
I'm working on a quick patch that fixes registration according to the existing design.

I agree it would probably be best to keep the metadata all in one crate. The biggest complication I see to that design is that it will be harder to statically determine whether error codes are being duplicated across crates. If we had to we could have a dynamic check when rustc starts up though.

As to whether it would be best to get rid of numbers, the downside there is that arbitrary-length strings take up a lot of room in error messages.

**Comment by brson** [comment]
I guess english-language error codes could be a potential i18n issue as well, though I'm not sure if compiler errors are ever internationalized.

**Comment by brson** [comment]
If we used a tidy script to dig out all the error codes (if they had a more distinctive syntax) then we could get rid of the giant registration list. One of the purposes of the big gigantic list of error codes was to ensure that none ever get reused, so if we got rid of the list then it would be more tempting to go back and take one of the retired codes. I'm thinking there may be room in the design for a list of retired codes that perhaps the tidy script could check as well.

**Comment by brson** [comment]
Here's my revised proposal, which is substantially similar to niko's

* Get rid of the `__diagnostic_used` and `__register_diagnostic` builtins that try to enforce sanity at compile time, as well as `__build_diagnostics_array`. All this logic will be handled through either a tidy script or normal macros.
* Change the current invocation syntax to make the error codes more distinctive, like `%E0000`, which appears nowhere in the existing source.
* Add a single file in the driver that includes three macro invocations:
    * `error_codes! { }` - basic metadata per Niko
    * `extended_errors! { }` - optional detailed information
* Add a tidy script that ensures that each of the `%ENNNN` strings is unique, that they all exist in 'error_codes'.
* Update the `span_err` etc macros to accept either the numeric codes or the descriptive codes.

**Comment by nikomatsakis** [comment]
fwiw I like the numbers in terms of presenting to end-users, I just would like to make dealing with merge conflicts easy when rebasing

**Comment by nikomatsakis** [comment]
idea that was proposed: get a random unused number?

**Comment by steveklabnik** [comment]
Triage: @jonathandturner tells me this is back on now!
