### ISSUE TITLE
Cannot generate tuple-accession-syntax through macros

### ISSUE THREAD

**Issue by quizlx** [rust-lang/rust#19630]
E.g. `mytuple.0` can't be generated by `mytuple.$num` due to rust only accepting an identifier here. And digits ofc are expressions....

Minimal Example:

```
#![feature(macro_rules)]

macro_rules! nth(
    ($n:expr,$x:ident) => ($x.$n);
)

fn main(){
    let foo = (2u, 3u, 4u);
    let bar = nth!(2, foo);
}
```

**Comment by steveklabnik** [comment]
Traige: updated code

```
macro_rules! nth(
        ($n:expr,$x:ident) => ($x.$n);
        );

fn main(){
        let foo = (2, 3, 4);
            let bar = nth!(2, foo);
}
```

Given that there's a workaround and we're not doing significant work on current macros, I'm not sure this will ever be fixed.

**Comment by bluss** [comment]
From Rust 1.12 you can use the matcher `tt` for the tuple field index and use it directly in the macro expansion, without any "as_expr" ast coercion trick, so this is now fixed. (The matcher `expr` is not allowed.)

The working macro is:

```rust
macro_rules! nth {
    ($n:tt, $x:ident) => ($x.$n);
}
```
