### ISSUE TITLE
Feature gates at the top of a file silently ignored in module context

### ISSUE THREAD

**Issue by sp3d** [rust-lang/rust#19646]
For example, create two files:

gate.rs:
```
#![feature(globs)]
#![crate_type="lib"]

use std::*;

pub fn foo()
{
	let _=os::args();
}
```

m.rs:
```
mod gate;

fn main()
{
	gate::foo()
}
```

Running `rustc m.rs` will result in complaints about the glob being used in gate.rs, but will not mention that there are ignored feature flags in the file (which are the real cause of the problem). Running `rustc gate.rs` succeeds.

It would be nice if rustc warned when it encountered feature flags or crate attributes in a context where they are ignored.

**Comment by alexcrichton** [comment]
This is now caught by the unused attribute warning, so yay!
