### ISSUE TITLE
unused_attribute lint should run after registered lints

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#19689]
I was getting an unused_attribute warning even when one of my lints was consuming the attribute (Even if done explicitly, via [`syntax::attr::mark_used`](http://doc.rust-lang.org/syntax/attr/fn.mark_used.html))

I later put a panic in the lint pass, and it turned out that the unused_attribute warning is emitted before the lint pass happens.

This can be reproduced by writing a lint pass that marks an attribute as used. Alternatively, just write one that panics. The lint is run after unused_attribute.

The builtins (at least `unused_attribute`) should probably be run last. Currently, [we run them first](https://github.com/rust-lang/rust/blob/83a44c7fa676b4e5e546ce3d4624e585f9a1e899/src/librustc/session/mod.rs#L286)

**Comment by steveklabnik** [comment]
@Manishearth you don't happen to have code handy that exhibits this behavior, do you?

**Comment by Manishearth** [comment]
The must_root plugin in Servo.

However, https://github.com/rust-lang/rust/pull/25168 obviates the need for this.
