### ISSUE TITLE
If slower than while in nested loops

### ISSUE THREAD

**Issue by paholg** [rust-lang/rust#19696]
Inside of nested `for` loops, `if` statements can be substantially slower than `while` loops that do the same thing.

Here is the simplest example that I could come up with (anything simpler, and the compiler gets rid of the loop completely). With a `while` loop, we have:
```
fn main() {
    let mut v = [1i, 1, 1];
    for _ in range(0u, 10000000000) {
        for i in range(0u, 3) {
            while v[i] > 0 { v[i] -= 1; }
        }
    }
}
```
Bulding with `cargo build --release` and running with `time` gives the output:
```
./target/release/test  11.39s user 0.00s system 100% cpu 11.390 total
```
Replacing the `while` loop with an `if` statement (which gives the same result, as the `while` only ever loops once):
```
fn main() {
    let mut v = [1i, 1, 1];
    for _ in range(0u, 10000000000) {
        for i in range(0u, 3) {
            if v[i] > 0 { v[i] -= 1; }
        }
    }
}
```
Bulding with `cargo build --release` and running with `time` gives the output:
```
./target/release/test  22.23s user 0.00s system 100% cpu 22.218 total
```
There is clearly some optimization at play here for `while` loops that could potentially be applied to `if` statements as well.

I first noticed this here: https://github.com/paholg/monte-carlo-test/blob/master/src/v1.rs in the `fix_periodic()` and `periodic_diff()` functions. I have since unwrapped the `for` loops which gave a substantial speed increase for the program (around 40-50%), which is potentially another issue, or potentially part of the same issue.

As it is a project that compares speed for similar C++ and Rust programs, I may as well mention that unwrapping the `for` loops in those functions also increased efficiency for the C++ code with g++ versions earlier than 4.8 and with clang++, and that with the unwrapped `for`, the Rust code is essentially the same speed as the C++ code.

My Rust version:
```
rustc 0.13.0-nightly (8bca470c5 2014-12-08 00:12:30 +0000)
binary: rustc
commit-hash: 8bca470c5acf13aa20022a2c462a89f72de721fc
commit-date: 2014-12-08 00:12:30 +0000
host: x86_64-unknown-linux-gnu
release: 0.13.0-nightly
```

**Comment by Aatch** [comment]
This isn't really a Rust issue, due the fact that the `while` variant give LLVM more information than the `if` variant.

Basically, it's due to LLVM knowing more about the values of various bits of memory at different points in the program. Many optimisations are based on local reasoning.

```rust
// Faster one
pub fn test_1(upper: usize) -> [isize; 3] {
    let mut v = [1is, 1, 1];
    for _ in (0us..upper) {
        for i in 0us..3 {
            while v[i] > 0 { v[i] -= 1; }
            // In order to get here, the value of v[i] *must* be <= 0,
            // Therefore we replace the above loop with
            // if v[i] > 0 { v[i] = 0; )
        }
    }

    v
}

pub fn test_2(upper: usize) -> [isize; 3] {
    let mut v = [1is, 1, 1];
    for _ in (0us..upper) {
        for i in 0us..3 {
            if v[i] > 0 { v[i] -= 1; }
            // The value isn't necessarily 0, just smaller
        }
    }

    v
}
```rust

LLVM isn't magic, and will always miss some optimisations. As far as I can tell, we're not generating anything that makes the code worse. While this case certainly demonstrates a case where LLVM could do better, I don't think this a Rust issue.
