### ISSUE TITLE
Installer for OS X Yosemite displays nonsense text

### ISSUE THREAD

**Issue by ueliem** [rust-lang/rust#19713]
Apologies if this is not the place to post issues about the installer. 

I attempted to use the installer for OS X Yosemite, and on the screen that I assume asks me for my password, a bunch of strange text characters replaced the usual message, and the buttons' text. I closed and reopened the installer but the same occurred. 
![screen shot 2014-12-10 at 2 25 19 pm](https://cloud.githubusercontent.com/assets/2715341/5382607/3aac31c6-8079-11e4-82eb-c2494d044bc5.png)

**Comment by frewsxcv** [comment]
This hasn't been reported in a while. I think we can close this for now

**Comment by alexcrichton** [comment]
Agreed
