### ISSUE TITLE
Tests for rustdoc outputs

### ISSUE THREAD

**Issue by lifthrasiir** [rust-lang/rust#19723]
We already have a heap of various rustdoc bugs, most of them are reported and verified by hand. We need a good facility to test rustdoc outputs with the expected output. For example, the "expected output" might be a set of expected files and expected set of strings to appear from each file.

A superset of #13444.

**Comment by tomjakubowski** [comment]
Since most rustdoc bugs seem to be in `clean` and `clean::inline`, it might be worth adding some unit tests for those at least. It could be tricky to produce fixture data for inlined docs though, which tend to cause the most headaches.

**Comment by alexcrichton** [comment]
With `htmldockck` this is basically done. Awesome work again @lifthrasiir!
