### ISSUE TITLE
Tracking issue for RFC 446 - ES6-style unicode escapes

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#19739]
Remove `\u203D` and `\U0001F4A9` unicode string escapes, and add [ECMAScript 6-style](https://mathiasbynens.be/notes/javascript-escapes#unicode-code-point) `\u{1F4A9}` escapes instead.

Text: https://github.com/rust-lang/rfcs/blob/master/text/0446-es6-unicode-escapes.md
RFC PR: https://github.com/rust-lang/rfcs/pull/446

Migration strategy: https://github.com/rust-lang/rfcs/blob/master/text/0446-es6-unicode-escapes.md#migration-strategy

**Comment by genbattle** [comment]
I have opened a PR [here](https://github.com/rust-lang/rust/pull/21832) to update the documentation in relation to this change.

**Comment by alexcrichton** [comment]
This has been completed.
