### ISSUE TITLE
Reference language items are out of date

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#19759]
Reference [language items](http://doc.rust-lang.org/reference.html#language-items) are out of date. The items are listed [here](https://github.com/rust-lang/rust/blob/master/src/librustc/middle/lang_items.rs#L231). Currently missing these:
```
slice
slice_mut
panic_bounds_check
panic_fmt
managed_bound
```

**Comment by Diggsey** [comment]
There are some other differences too.
- Only present in the code:
```
opaque
managed_bound
non_zero
range
range_from
range_to
full_range
```
- Only present in the reference:
```
strdup_uniq
begin_unwind
closure_exchange_malloc
fail_bounds_check
gc
malloc
free
```

(presumably _panic_bounds_check_ used to be called _fail_bounds_check_)
