### ISSUE TITLE
Document and establish compatibility guidelines for Unicode version used

### ISSUE THREAD

**Issue by lifthrasiir** [rust-lang/rust#19762]
We already have `unicode::char::UNICODE_VERSION`, but we need to guarantee that:

1. Newer version of Rust can only update to the newer version of Unicode standard (see also the [Unicode character encoding stability policy](http://www.unicode.org/policies/stability_policy.html)); and
2. Such update only occurs on the minor version or major version.

In addition, we may want to document that some `#[stable]` methods or functions can change its behavior in the backward compatible fashion: `trim` is one example (depends on the `White_Space` property). This is a rationale for the item 2 above.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#855
