### ISSUE TITLE
Broken links for viewing examples on play.rust-lang.org

### ISSUE THREAD

**Issue by IvanUkhov** [rust-lang/rust#19807]
Hello,

It seems that the play links of the examples given on [IteratorExt][1]’s page are incorrect: they all yield the same code on play.rust-lang.org, which is the code of the very first example on that page.

Regards,
Ivan

[1]: http://doc.rust-lang.org/std/iter/trait.IteratorExt.html

**Comment by kmcallister** [comment]
Fixed by #20990.
