### ISSUE TITLE
Experiment with reusing monomorphized instances across crates

### ISSUE THREAD

**Issue by marijnh** [rust-lang/rust#1980]
Currently, crates generate their own versions of all generic functions they use. They could write info about the generated functions to the metadata, and crates compiling against them could check that first, and simply link the already existing instance when possible. This is bound to reduce code output size, and thus compilation time.

**Comment by steveklabnik** [comment]
Triage: no updates

**Comment by alexcrichton** [comment]
cc @brson, do you feel your work in this area is enough to close this? It sounded like experiments were done, conclusions were reached, and we probably don't want to land it in the compiler at this time?

Plus you get to close a pre-2k bug :)

**Comment by brson** [comment]
[My report](https://internals.rust-lang.org/t/some-notes-on-reducing-monomorphizations/2459/13).

After a few weeks of on-and-off work I could not find a simple heuristic that would produce reliable wins. Switching large amounts of functions from internal to some form of external linkage causes the compilation profile to change in large, but subtle ways, and I couldn't find a scenario where the changes were consistently in favor of better compile times.

I haven't given up hope though. I think this technique still has clear applications to profile-based (de)optimization and pre-instantiation of std library functions.

I do think it's not worth keeping this open. If somebody has a breakthrough someday it'll happen. If not, nbd.

**Comment by brson** [comment]
My big headline number for this effort was that I reduced total servo debug build times by 8%. The tradeoff though was that some crates took significantly longer to build.
