### ISSUE TITLE
Using `-C codegen_units=N` while bootstrapping rust generates an LLVM assertion

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#19826]
### STR

```
$ git clone https://github.com/rust-lang/rust
$ cd rust
$ mkdir build
$ cd build
$ ../configure
$ RUSTFLAGS=-Ccodegen_units=2 make
rustc: x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc
rustc: x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand
rustc: x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunicode
rustc: x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc
rustc: /home/rustbuild/src/rust-buildbot/slave/snap3-linux/build/src/llvm/lib/IR/Constants.cpp:1609: static llvm::Constant* llvm::ConstantExpr::getPointerCast(llvm::Constant*, llvm::Type*): Assertion `S->getType()->isPtrOrPtrVectorTy() && "Invalid cast"' failed.
Aborted (core dumped)
```

### Version

444fa1b

---

Sadly, I couldn't generate a minimal script that reproduces the problem. But these seem to be the required ingredients:

- Cross crate. The linked crate must use unboxed closures.
- There must be some `#[inline]`d function in the root crate.
- And, of course, the `-C codegen_units` flag.

cc @nikomatsakis @nick29581

**Comment by tomjakubowski** [comment]
Here's an updated gist that ICEs on `rustc 1.0.0-dev (ea6f65c5f 2015-01-06 19:47:08 +0000)`:

https://gist.github.com/tomjakubowski/9c49af9cd2582c37d0e8/a056ead1b0ba5bd29fae8b709fc031ebdc49e4fd

**Comment by Aatch** [comment]
To people from the future, I'm going to add notes of my investigation here.

It looks like we're getting some oddness with types appearing to be different when using multiple codegen units. Specifically, Rust is trying to cast an unboxed closure to an identical-looking unboxed closure.

**Comment by lgvz** [comment]
Don't know how related, but the same error comes with this, too (on linux and with no flags to rustc):
```Rust
fn main() {
    let a: [u8; 2] = [97, 98];
    //if &a[0..2] == b"ab" {    // works
    if a[0..2] == *b"ab" {    // ICE
        println!("test");
    }
}
```
(rustc 1.0.0-nightly (f4f10dba2 2015-01-17 20:31:08 +0000))

**Comment by tamird** [comment]
Triage:

@lgvz's code no longer produces an error.

@tomjakubowski/@japaric's gist no longer compiles.
