### ISSUE TITLE
Add documentation for unboxed closures in reference

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#19841]
Right now, it [looks like the reference only talks about vanilla closures](https://github.com/rust-lang/rust/blob/52f7a4a351646d3837f214b5c7aec390c9b08221/src/doc/reference.md#closure-types). This will eventually need to be updated to talk about unboxed closures.

**Comment by steveklabnik** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/20137
