### ISSUE TITLE
Type inference failure when cloning

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#19855]
```rust
fn foo() -> String {
    let x = std::default::Default::default();
    drop(x.clone());
    x
}

fn main() {}
```

```
test.rs:3:10: 3:19 error: the type of this value must be known in this context
test.rs:3     drop(x.clone());
                   ^~~~~~~~~
error: aborting due to previous error
```

cc @nikomatsakis

**Comment by nikomatsakis** [comment]
This is expected behavior. When doing a method call, we must know the type *at that point in type checking*. Here, the constraint on the type of `x` only arises at the point of the return. It'd be nice to fix this but it's not on the current plans (and requires a lot of work).
