### ISSUE TITLE
Encodable trait objects

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#19874]
`<kmc>` i want a world where I can send a `Box<Encodable + FnOnce(A) -> B>` across the network and call it on the other end
`<Yurume>` kmc: with a built-in [AEAD](http://en.wikipedia.org/wiki/AEAD_block_cipher_modes_of_operation) protocol...

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#668
