### ISSUE TITLE
No unsafe slicing

### ISSUE THREAD

**Issue by cgaebel** [rust-lang/rust#19901]
There's currently no version of `slice`, `slice_from`, `slice_to`, `slice_mut`, `slice_from_mut`, `slice_to_mut`, `split_at` that doesn't bounds check.

**Comment by kmcallister** [comment]
Is this still the case? It seems like a pretty big oversight if we claim to have C-like performance.

Nominating P-high, not 1.0.

**Comment by cgaebel** [comment]
This appears to still be the case.

**Comment by pnkfelix** [comment]
P-low, not 1.0; tagging as wishlist.

**Comment by nikomatsakis** [comment]
This is easy to workaround, so it doesn't seem especially high priority, but it would be nice to have.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#708
