### ISSUE TITLE
Should `for <> Trait` be legal syntax?

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang/rust#19920]
This program is currently accepted:

```
trait Foo {}
fn foo<F: for<> Foo>(x: F) {}
impl Foo for () {}
fn main() {
    foo(());
}
```

Should it be? I don't think the bound ends up being treated any differently than `<F: Foo>`.

**Comment by kmcallister** [comment]
Yeah, those are all accepted.  Closing this as intended behavior.  I think a lint for empty type parameter lists would be reasonable, though.
