### ISSUE TITLE
std docs: methods are really difficult to discover

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#19956]
From [reddit](http://www.reddit.com/r/rust/comments/2pfpeb/how_to_write_efficient_yet_safe_string/cmwanv1), `rev()` can be called on a `CharSplits` but there is no easy way to discover this without being told.
```rust
for word in s.split(' ').rev() { ... }
```
Here's how I tried to manually find `rev()` after realizing it was there (copied from reddit):

* Std docs -> str -> StrPrelude
* click [CharSplits](http://doc.rust-lang.org/std/str/struct.CharSplits.html) in split
* click Iterator...am back where I started
* go back to CharSplits
* click DoubleEndedIterator
* Don't see it...
* ah, search rev...it's in DoubleEndedIteratorExts
* back to iterator
* click trait DoubleEndedIteratorExts

A solution would be to include the methods each trait provides on the page. Or to have the trait list it's provided methods directly.

**Comment by gsingh93** [comment]
I'd like to see this worked on before 1.0.

**Comment by tomjakubowski** [comment]
See my comment here https://github.com/rust-lang/rust/issues/19394#issuecomment-89476250

**Comment by pornel** [comment]
Similar problem: documentation for iterator types doesn't say how to create an instance of such iterator.

It's easy to stumble from search upon iterator implementation's documentation page, but these pages are useless: most methods they list are only internal iterator implementation boilerplate that isn't used directly.

e.g.

https://doc.rust-lang.org/std/slice/struct.ChunksMut.html

Doesn't tell how me to actually iterate over a thing!

1. I need to know that this page is incomplete
2. I need to know that a function I'm looking for is going to be on some other type, and I need to guess what type is that
3. Then I need to guess/find a function that returns this iterator (I guess there's `chunks_iter_mut` or something) on another page of documentation

**Comment by tomjakubowski** [comment]
That's a general problem (how do I produce something of this type, or something parametrized by this type) that I think needs a Hoogle-like solution (I'm aware of the existing GH issue).



—

**Comment by gsingh93** [comment]
The iterator problem is a bit different than the general problem, because with most other objects the methods to create them are defined the struct `impl` itself. With iterator structs, they're intended to be created by methods in other struct `impl`s, which is what makes them confusing.

**Comment by tomjakubowski** [comment]
I disagree. When working on the compiler or rustdoc, for example, you often need to get an instance of some type out of a cache stored in the private field of a context struct somewhere, usually by calling a free function. Many of my efforts in rustdoc were stymied because while I knew I needed something of type Foo (or worse, a type parametrized by Foo), I didn't have an effective way to pare down the enormous search space of rustc's free functions by their return type (grepping the source was sometimes helpful, but the point of a documentation tool is to bring stuff like that at hand.) The same problem is there for iterator structs. 



—

**Comment by gsingh93** [comment]
That is true (I ran into a similar problem with syntax extensions), but iterator structs are probably the most common case where this occurs and are more applicable to the average user. But in any case, Hoogle style search does solve this problem, and rustdoc actually supports this even though it isn't documented when pressing `?`.

**Comment by bluss** [comment]
The original bug is "fixed". Maybe this bug can be closed & file new issues for new specific problems.

[`str` docs](http://doc.rust-lang.org/nightly/std/primitive.str.html) are now all on one page, for the primitive type. [`Splits` docs](http://doc.rust-lang.org/nightly/std/str/struct.Split.html) now show `.rev()` as one of the methods.

**Comment by mdinger** [comment]
I agree. Pushing the other issues to other bugs would also be a good idea.
