### ISSUE TITLE
Mutexes are recursive on windows, but not on unix

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#19962]
This behavioral difference should factor into the stabilization of the methods on `sync::Mutex` and how we'd like to word the documentation.

For now though, this is a tracking issue as this difference in behavior was not originally intended.

cc @aturon

**Comment by mzabaluev** [comment]
Apparently [`Static`]`RwLock` is non-recursive on Unix too, and easy to deadlock:
```rust
#![allow(unstable)]

use std::sync::{StaticRwLock, RW_LOCK_INIT};

static LOCK: StaticRwLock = RW_LOCK_INIT;

fn main() {
    let _read = LOCK.read();
    let _write = LOCK.write();
}
```
