### ISSUE TITLE
ICE using parenthetical trait notation in impls 

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#19982]
The following test will ICE:

```
#![feature(unboxed_closures)]
struct Foo;
impl Fn(&int) for Foo { }
```

The workaround for now is to write:

```
impl<'a> Fn(&'a int) for Foo { }
```

It would be better if this were implicit. This seems related to lifetime elision, which also is supposed to permit elided parameters in impls.

**Comment by tamird** [comment]
Hey, this should have been closed by https://github.com/rust-lang/rust/commit/3a93bdb92c195cab90103743f11c14c837e84598! @steveklabnik would you mind?
