### ISSUE TITLE
Fresh install from nightly, error: internal compiler error: unexpected panic

### ISSUE THREAD

**Issue by agmcleod** [rust-lang/rust#19987]
I previously had 0.12 installed through homebrew. I did an uninstall, and installed rust & cargo via the shell script:

http://static.rust-lang.org/doc/master/guide.html#installing-rust

Running through the guess the numbers example, i have the following:

    use std::io;

    fn main() {
      println!("Guess the number!");

      println!("Please input your guess.");

      let input = io::stdin().read_line().ok().expect("Failed to read line");
      println!("You guessed: {}", input);
    }

And when running `rustc` on the file or using cargo run, i get the below problem:

```
rustc 0.13.0-nightly (42deaa5e4 2014-12-16 17:51:23 +0000)
binary: rustc
commit-hash: 42deaa5e42c0b8a9e305aa5de5d6953b24b77aca
commit-date: 2014-12-16 17:51:23 +0000
host: x86_64-apple-darwin
release: 0.13.0-nightly
```

Even just having this as my source code, it seems to go badly. Did something not install properly?

```
fn main() {
  println!("Hello!");
}
```

**Comment by kmcallister** [comment]
Do you still see this problem on the latest nightly? Can you re-run with the `RUST_BACKTRACE=1` environment variable to get a backtrace?

**Comment by jdm** [comment]
This looks like the regular stale metadata problem that is usually worked around by deleting old versions of the standard libraries.

**Comment by agmcleod** [comment]
I've been running fine since 1.0 alpha, and just been trying to grab nightlies every couple days. No issues. Mainly reported it since the output said to do so :)

**Comment by tamird** [comment]
@steveklabnik this looks non-actionable as well
