### ISSUE TITLE
Windows 2k8/Vista support lost since 4-Dec nightly

### ISSUE THREAD

**Issue by SteveGilham** [rust-lang/rust#19992]
Issue title updated 22-Dec following further analysis.

Some time since that nightly (rustc 0.13.0-nightly (d9c7c00b9 2014-12-04 21:33:07 +0000)), the rustc executable fails fast before emitting any console output.

Windows Mini-dump
```
Dump Summary
------------
Dump File:	rustc.exe.5260.dmp : C:\Users\Steve\AppData\Local\CrashDumps\rustc.exe.5260.dmp
Last Write Time:	18/12/2014 19:38:55
Process Name:	rustc.exe : C:\Rust\bin\rustc.exe
Process Architecture:	x86
Exception Code:	0xC0000139
Exception Information:	
Heap Information:	Present

System Information
------------------
OS Version:	6.0.6002
CLR Version(s):	

Modules
-------
Module Name	Module Path	Module Version
-----------	-----------	--------------
rustc.exe	C:\Rust\bin\rustc.exe	0.0.0.0
ntdll.dll	C:\Windows\System32\ntdll.dll	6.0.6002.18881
kernel32.dll	C:\Windows\System32\kernel32.dll	6.0.6002.19034
libgcc_s_dw2-1.dll	C:\Rust\bin\libgcc_s_dw2-1.dll	0.0.0.0
msvcrt.dll	C:\Windows\System32\msvcrt.dll	7.0.6002.18551
std-4e7c5e5c.dll	C:\Rust\bin\std-4e7c5e5c.dll	0.0.0.0
advapi32.dll	C:\Windows\System32\advapi32.dll	6.0.6002.18005
rpcrt4.dll	C:\Windows\System32\rpcrt4.dll	6.0.6002.18882
```

Error 0xC0000139 is "Entry Point Not Found" -- presumably in builds from the last week or so, a Win7 and later API call is being made at start-up as tests with the same nightly installer (‎17 ‎December ‎2014, ‏‎05:57:06) show that the self-same rustc executable will emit version details for a -v on Win7 64-bit, rather than immediately failing.

So far, I've not gotten anything else useful from the crash dump

**Comment by stej** [comment]
Ok, so is Vista support dead, or is there any hope? Currently the installer installs everything correctly, but rustc & cargo complain about compatibility issue.

**Comment by retep998** [comment]
Someone would have to be willing to write alternative versions of code that don't depend on newer APIs. Having Rust work on XP is a requirement for it to be used in Servo, so there is definitely a need for it eventually. It's just that the number of Rust developers who care about such old versions of Windows is significantly less than the already small number of Rust developers that work on the Windows side of Rust.
