### ISSUE TITLE
Macro reform (Tracking issue for RFC 453)

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#20008]
This is a tracking issue for RFC rust-lang/rfcs#453, macro reform.

**Comment by kmcallister** [comment]
Unimplemented parts of the RFC:

* Renaming on `#[macro_use] extern crate`
* Naming specific macros (and renaming?) on `#[macro_use] mod`
* `#[macro_use]` on `macro_rules!` for helper macros
* Lint for use of `$crate` in macros

I think all of these are backwards-compatible, and none of them is particularly high priority for 1.0.

**Comment by kmcallister** [comment]
Renaming on import is now #22290.

The `$crate` lint sounds pretty hard the more I think about it.  And it detects a problem that should be obvious at compile time, as soon as you try to use that macro in another crate.

The other two bullet points are things we could plausibly live without, so let's try that in the name of simplicity.
