### ISSUE TITLE
Tracking issue for splitting Show into String and Show (RFC 504)

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#20013]
https://github.com/rust-lang/rfcs/pull/504

**Comment by sfackler** [comment]
Should this be closed?

**Comment by aturon** [comment]
Yes, I think so; we'll probably want to make tweaks with whatever [conventions](https://github.com/rust-lang/rfcs/pull/565) we finalize on, but that can be a separate tracking issue.
