### ISSUE TITLE
Make suggestions for 'does not implement any method in scope'

### ISSUE THREAD

**Issue by aidanhs** [rust-lang/rust#20028]
I made this mistake just now:

```
~/rust/tclscan $ cargo test
   Compiling tclscan v0.0.1 (file:///home/ahobsons/rust/tclscan)
/home/ahobsons/rust/tclscan/src/lib.rs:120:59: 120:72 error: type `collections::vec::Vec<&str>` does not implement any method in scope named `connnect`
/home/ahobsons/rust/tclscan/src/lib.rs:120             Ok(true) => println!("DANGER: {}", token_strs.connnect(' ')),
                                                                                                     ^~~~~~~~~~~~~
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
/home/ahobsons/rust/tclscan/src/lib.rs:120:59: 120:72 error: type `collections::vec::Vec<&str>` does not implement any method in scope named `connnect`
/home/ahobsons/rust/tclscan/src/lib.rs:120             Ok(true) => println!("DANGER: {}", token_strs.connnect(' ')),
                                                                                                     ^~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `tclscan`.

To learn more, run the command again with --verbose.
```

(count the 'n's)

It'd be nice if this made the suggestion for 'connect' (like misspelling a variable does).
I had a look but can't see any existing issues for this.

**Comment by kmcallister** [comment]
This sounds *more* useful than the existing auto-correct for variable names.  Also, both of them should probably have a maximum edit distance threshold -- the hilariously wrong suggestions we get today decrease the utility of the feature as a whole.

**Comment by fitzgen** [comment]
I'm working on a patch for this.

**Comment by fitzgen** [comment]
Edit distance by itself isn't the best metric. For example, an edit distance of 3 is often *huge*: "wutang" -> "mutate" is an edit distance of 3. However, this edit-distance-3 mismatch is fairly common: "foobar" instead of "getFoobar".

However, I will start with simply making the existing infrastructure work with methods.

**Comment by fitzgen** [comment]
> Edit distance by itself isn't the best metric. For example, an edit distance of 3 is often huge: "wutang" -> "mutate" is an edit distance of 3. However, this edit-distance-3 mismatch is fairly common: "foobar" instead of "getFoobar".

FWIW, clang handles this stuff *really* well, so it would probably be insightful to see what their heuristics are.

**Comment by fitzgen** [comment]
I can't figure out exactly where function names live. When resolving functions, it pushes to `value_ribs` and `label_ribs`, but the given `FnDecl` doesn't seem to have access to names. Also, looked into the `def_map` but I think that isn't ordered by scope.

Would appreciate some pointers, thanks.

**Comment by brson** [comment]
As far as I can tell we still don't give suggestions for misspelled method names: https://is.gd/oR7fI6. This is presumably relatively easy to do, but this bug doesn't indicate how. @rust-lang/compiler can anybody give pointers on how to set up spell-check on methods and tag this `E-easy` again?

**Comment by Mark-Simulacrum** [comment]
This is basically https://github.com/rust-lang/rust/issues/30197, closing in favor of that.
