### ISSUE TITLE
Revamp documentation to talk about `std::thread`

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#20038]
Now that https://github.com/rust-lang/rust/pull/19654 has landed, Rust no longer has tasks; it has threads. There is a lot of documentation that needs to be updated to reflect the new name and API.

A starting step would be a s/task/thread/g change similar to the s/fail/panic/g change.

cc @steveklabnik

**Comment by ciphergoth** [comment]
guide-tasks.md needs to be renamed to guide-threads.md. At the moment the link on the docs index page goes to a 404.
