### ISSUE TITLE
Panic during unit tests (coerce_match)

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#20055]
Currently on bd90b93

Running on OSX

cc'ing @kballard and @barosl since I saw both of them also had this issue in #rust-internals on IRC

```
...
test [run-pass] run-pass/yield2.rs ... ok
test [run-pass] run-pass/zero-size-type-destructors.rs ... ok
test [run-pass] run-pass/yield1.rs ... ok
test [run-pass] run-pass/vector-sort-panic-safe.rs ... ok
test [run-pass] run-pass/yield.rs ... ok

using metrics ratchet: tmp/check-stage2-T-x86_64-apple-darwin-H-x86_64-apple-darwin-rpass-metrics.json
result of ratchet: 0 metrics added, 0 removed, 0 improved, 0 regressed, 0 noise
updated ratchet file

failures:

---- [run-pass] run-pass/coerce-match.rs stdout ----

error: test run failed!
status: signal: 4
command: x86_64-apple-darwin/test/run-pass/coerce-match.stage2-x86_64-apple-darwin
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------

------------------------------------------

thread '[run-pass] run-pass/coerce-match.rs' panicked at 'explicit panic', /Users/coreyf/Development/rust/src/compiletest/runtest.rs:1487



failures:
    [run-pass] run-pass/coerce-match.rs

test result: FAILED. 1745 passed; 1 failed; 27 ignored; 0 measured

thread '<main>' panicked at 'Some tests failed', /Users/coreyf/Development/rust/src/compiletest/compiletest.rs:267
make: *** [tmp/check-stage2-T-x86_64-apple-darwin-H-x86_64-apple-darwin-rpass.ok] Error 101
```

**Comment by pnkfelix** [comment]
i also see this on my mac

**Comment by nick29581** [comment]
When this is fixed, can we make sure coerce_match.rs moves to run-pass-valgrind

**Comment by jroesch** [comment]
I am now also getting a second failure:
```
test [run-pass] run-pass/zero-size-type-destructors.rs ... ok
test [run-pass] run-pass/yield1.rs ... ok
test [run-pass] run-pass/yield.rs ... ok
test [run-pass] run-pass/vector-sort-panic-safe.rs ... ok

failures:

---- [run-pass] run-pass/coerce-match-calls.rs stdout ----

error: test run failed!
status: signal: 4
command: x86_64-apple-darwin/test/run-pass/coerce-match-calls.stage2-x86_64-apple-darwin
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------

------------------------------------------

thread '[run-pass] run-pass/coerce-match-calls.rs' panicked at 'explicit panic', /Users/jroesch/Git/rust/src/compiletest/runtest.rs:1453


---- [run-pass] run-pass/coerce-match.rs stdout ----

error: test run failed!
status: signal: 4
command: x86_64-apple-darwin/test/run-pass/coerce-match.stage2-x86_64-apple-darwin
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------

------------------------------------------

thread '[run-pass] run-pass/coerce-match.rs' panicked at 'explicit panic', /Users/jroesch/Git/rust/src/compiletest/runtest.rs:1453



failures:
    [run-pass] run-pass/coerce-match-calls.rs
    [run-pass] run-pass/coerce-match.rs

test result: FAILED. 1826 passed; 2 failed; 28 ignored; 0 measured

thread '<main>' panicked at 'Some tests failed', /Users/jroesch/Git/rust/src/compiletest/compiletest.rs:269
make: *** [tmp/check-stage2-T-x86_64-apple-darwin-H-x86_64-apple-darwin-rpass.ok] Error 101
```

**Comment by pnkfelix** [comment]
@jroesch yeah I added that second test when I was investigating the first one (when I was working on stuff related to `box <expr>` syntax); the test is intended to make it clear that the issue here is not related to the `box <expr>` syntax.

**Comment by jroesch** [comment]
@pnkfelix thanks for the update. They are just a minor annoyance when running the test suite.

**Comment by pnkfelix** [comment]
Here is a reduced test case for input:
```
use std::boxed::Box;

pub fn main() {
    let _: Box<[i8]> = match true { true => Box::new([1i8, 2, 3]), false => Box::new([1i8]) };
}
```

I have compared the generated llvm-ir with and without the `-O` flag to `rustc`.  Here's something funny:

Without `-O`, we have just a single call to the jemalloc free routine `je_sdallocx`, followed immediately by a `ret void`:
```
  %18 = load i8** %__arg
  store i64 %16, i64* %__arg1
  %19 = load i64* %__arg1
  store i32 %17, i32* %__arg2
  %20 = load i32* %__arg2
  call void @je_sdallocx(i8* %18, i64 %19, i32 %20)
  ret void
```

with the `-O` flag to `rustc`, however, we get output that is quite different, with two distinct calls to ,`je_sdallocx` in series (tail calls no less), and the second seems to be being fed an `undef` value?  I am not an expert in LLVM IR, but this struck me as strange:

```
  %x.sroa.0.0..sroa_cast1.i = bitcast i8* %0 to i24*
  store i24 197121, i24* %x.sroa.0.0..sroa_cast1.i, align 1
  tail call void @je_sdallocx(i8* %0, i64 3, i32 0)
  tail call void @je_sdallocx(i8* undef, i64 1, i32 0)
  ret void
```

**Comment by pnkfelix** [comment]
Here is a result of further investigation: I do not know how valid it is to try to plug in different llvm-passes in an attempt to expose a code-generation bug, but it seemed to produce interesting information (in terms of certain combinations seeming to fall victim to the same bug).

Both of these example commands are being fed the reduced test case from the previous comment (named `coerce-match-calls2.rs`).

```
# For reference, this command produces an invalid binary,
# but minor tweaks (e.g. removing the sroa pass at the end)
# produces a binary that runs without an error.
CMD_1="rustc /tmp/coerce-match-calls2.rs \
      -C no-prepopulate-passes \
      -C passes=datalayout  \
      -C passes=notti  \
      -C passes=targetlibinfo \
      -C passes=no-aa \
      -C passes=tbaa \
      -C passes=scoped-noalias \
      -C passes=assumption-tracker \
      -C passes=basicaa \
      -C passes=ipsccp \
      -C passes=globalopt \
      -C passes=deadargelim \
      -C passes=instcombine \
      -C passes=simplifycfg \
      -C passes=basiccg \
      -C passes=prune-eh \
      -C passes=inline-cost \
      -C passes=inline \
      -C passes=functionattrs \
      -C passes=sroa \
"

# This is a reduced version of the above; it still produces a binary
# that will error in the midst of jemalloc, due pnkfelix thinks to a
# spuriously injected call to `je_sdallocx` (i.e. `free`)
CMD_2="rustc /tmp/coerce-match-calls2.rs \
      -C no-prepopulate-passes \
      -C passes=datalayout  \
      -C passes=instcombine \
      -C passes=inline \
      -C passes=sroa \
"
```

**Comment by pnkfelix** [comment]
(One can emulate the same effect on a generated .bc file via the llvm `opt` utility.  My main question at this point is if I can extract a standalone test that is independent of rust, including the libraries like jemalloc that I am linking in...)

**Comment by pnkfelix** [comment]
Ah, an interesting new detail: passing `--cfg workaround` yields a program that works, even when passing `-O`.  This means there may be some way to isolate this to something within `trans`, rather than focusing our attention on LLVM bugs.

Example with workaround:
```rust
use std::boxed::Box;

#[cfg(not(workaround))]
pub fn main() {
    let _: Box<[i8]> = match true {
        true => Box::new([1i8, 2, 3]),
        false => Box::new([1i8]),
    };
}

#[cfg(workaround)]
pub fn main() {
    let _: Box<[i8]> = match true {
        true => Box::new([1i8, 2, 3]),
        false => { Box::new([1i8]) }
    };
}
```

**Comment by pnkfelix** [comment]
I looked into this some more.  In particular, I made a `#[no_std]` test case that uses only the `core` and `libc` crates -- it would be straightforward to make it fully standalone, but I did not see a benefit in that.  The crucial thing is that this standalone test has its own "built-in" allocator (from a static array of bytes in the code), and it instruments the allocate/free calls with calls to C `printf`.

Its possible I made a mistake along the way, but there are some pretty funky things being illustrated in this test.  In particular, *without* optimizations, we do not see the erroneous call to `free` (just like in the examples above), but we *do* see an extra invocation of the `printf("Hello World 2");` call that I embedded into the code.  Super strange.

https://gist.github.com/pnkfelix/6dc4fb620c8742100598

**Comment by pnkfelix** [comment]
Another gist I have developed seems to show a case where optimizations are disabled and yet we still have a spurious `free` invocation.  This seems like a promising line of inquiry.

https://gist.github.com/pnkfelix/567213f949925ce33697

(Note that main difference between this gist and the one from the previous comment is that I introduced an extra block around the first match arm: 
```
pub fn main() {
  print0("Hello World 1\n\0");
  let _: Box<[i8]> = match true {
    true => { box_1() } // <-- this line is the main difference
    _ => box_2(),
  };
  print0("Hello World 2\n\0");
}
```

**Comment by pnkfelix** [comment]
Yay, I found a different example, a generalization of the original one, where one can observe the erroneous frees occurring even when optimizations are disabled.

https://gist.github.com/pnkfelix/2e2b73092c2fd5b38228

(This is very similar to my previous gists; the main difference is that I have added four separate match arms, each building a differently sized `Box<[u8; k]>` and then implicitly coercing it to a `Box<[u8]>`.)

The errors you get with and without `-O` are different, but they are real.  This leads me to suspect that this is a real code gen bug in Rust, not an optimization bug in LLVM.  (Although it could be that we are getting some attributes wrong on the structure we feed into LLVM.)

**Comment by pnkfelix** [comment]
And here's a variant of that same example; again, this causes an error both with and without optimizations:

```rust
// #![crate_type="lib"]

pub fn foo(box_1: fn () -> Box<[i8; 1]>,
           box_2: fn () -> Box<[i8; 2]>,
           box_3: fn () -> Box<[i8; 3]>,
           box_4: fn () -> Box<[i8; 4]>) {
    println!("Hello World 1");
    let _: Box<[i8]> = match 3 {
        1 => box_1(),
        2 => box_2(),
        3 => box_3(),
        _ => box_4(),
    };
    println!("Hello World 2");
}

pub fn main() {

    fn box_1() -> Box<[i8; 1]> { Box::new( [1i8] ) }
    fn box_2() -> Box<[i8; 2]> { Box::new( [1i8, 2] ) }
    fn box_3() -> Box<[i8; 3]> { Box::new( [1i8, 2, 3] ) }
    fn box_4() -> Box<[i8; 4]> { Box::new( [1i8, 2, 3, 4] ) }

    foo(box_1, box_2, box_3, box_4);
}
```

(The above gist has the advantage that it uses `#![no_std]` and uses an embedded allocator to track where the error arises.   But sometimes you want something that works in the playpen.)

**Comment by pnkfelix** [comment]
(The program from the previous comment also causes a core-dump in a Linux VM; Ubuntu 64-bit 14.10...)

**Comment by frewsxcv** [comment]
Awesome work @pnkfelix :sparkles:
