### ISSUE TITLE
We should rename std::hash::RandomSipHasher to something more generic

### ISSUE THREAD

**Issue by erickt** [rust-lang/rust#20050]
Right now `HashMap`s are tied to a specific algorithm implementation, `std::hash::RandomSipHasher`. While I believe SipHash is considered cryptographically secure, if it were ever to be broken it could be painful transitioning everyone into a new Hasher. Instead, I suggest we change it's name now to save us from headaches later on. Some possible names:

* DefaultHasher
* StandardHasher
* StdHasher
* RandomHasher

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rust-lang/rust/pull/20654

* `RandomSipHasher` was renamed to `std::collections::hash_map::RandomState`
* The default hasher for hash maps is now called `std::collections::hash_map::Hasher`
