### ISSUE TITLE
start / generated C main is the wrong type

### ISSUE THREAD

**Issue by comex** [rust-lang/rust#20064]
`fn lang_start(main: *const u8, argc: int, argv: *const *const u8) -> int {`

This is the signature both required for `start` fns and given to the C main wrapper function generated by `create_entry_fn` in `librustc_trans/trans/base.rs`.  But it's clearly the wrong type: `argc` and the return value should be `c_int` or `i32`, not `int`.

**Comment by brson** [comment]
I'd prefer any lang items to use rust types and for the compiler or libs to generate any potentially platform-specific code necessary to glue things together.

**Comment by tbu-** [comment]
If we have compiler glue anyway, `argc` should be `usize`.

I'm not so sure about the return type, `i32` as default go-to integer might be fine here, I however don't see justification for `isize`.

**Comment by brson** [comment]
Let's just gate it until we can think harder.

**Comment by alexcrichton** [comment]
Nominating for removal from milestone, this is now feature gated.

**Comment by pnkfelix** [comment]
Still P-high, but not 1.0 anymore since its gated.

**Comment by steveklabnik** [comment]
This issue has been superceded by https://github.com/rust-lang/rust/issues/29633, I will make note of this specific concern in that thread, since it does not seem to be mentioned there.
