### ISSUE TITLE
Ensure accepted RFCs are all in the manual and elsewhere

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#20137]
Ideally, the Reference would contain all of the semantics of the language. A big source of those semantics are RFCs, which have modified Rust over time. We need to go over every accepted RFC and ensure that it's actually documented in the language documentation proper.

Here is a check-off-able list of all of them. A bunch of them will be able to be checked off without pull request, but I want to make sure that we double check every one. 

- [ ] 0001-private-fields
- [ ] 0002-rfc-process
- [ ] 0003-attribute-usage
- [ ] 0008-new-intrinsics
- [ ] 0016-more-attributes
- [ ] 0019-opt-in-builtin-traits
- [ ] 0026-remove-priv
- [ ] 0034-bounded-type-parameters
- [ ] 0040-libstd-facade
- [ ] 0042-regexps
- [ ] 0048-traits
- [ ] 0049-match-arm-attributes
- [ ] 0050-assert
- [ ] 0059-remove-tilde
- [ ] 0060-rename-strbuf
- [ ] 0063-module-file-system-hierarchy
- [ ] 0066-better-temporary-lifetimes
- [ ] 0068-const-unsafe-pointers
- [ ] 0069-ascii-literals
- [ ] 0071-const-block-expr
- [ ] 0079-undefined-struct-layout
- [ ] 0085-pattern-macros
- [ ] 0086-plugin-registrar
- [ ] 0087-trait-bounds-with-plus
- [ ] 0089-loadable-lints
- [ ] 0090-lexical-syntax-simplification
- [ ] 0092-struct-grammar
- [ ] 0093-remove-format-intl
- [ ] 0100-partial-cmp
- [ ] 0107-pattern-guards-with-bind-by-move
- [ ] 0109-remove-crate-id
- [ ] 0111-index-traits
- [ ] 0112-remove-cross-borrowing
- [ ] 0114-closures
- [ ] 0115-rm-integer-fallback
- [ ] 0116-no-module-shadowing
- [ ] 0123-share-to-threadsafe
- [ ] 0130-box-not-special
- [ ] 0131-target-specification
- [ ] 0132-ufcs
- [ ] 0135-where
- [ ] 0136-no-privates-in-public
- [ ] 0139-remove-cross-borrowing-entirely
- [ ] 0141-lifetime-elision
- [ ] 0151-capture-by-value
- [ ] 0155-anonymous-impl-only-in-same-module
- [ ] 0160-if-let
- [ ] 0164-feature-gate-slice-pats
- [ ] 0168-mod
- [ ] 0169-use-path-as-id
- [ ] 0184-tuple-accessors
- [ ] 0192-bounds-on-object-and-generic-types
- [ ] 0194-cfg-syntax
- [ ] 0195-associated-items
- [ ] 0198-slice-notation
- [ ] 0199-ownership-variants
- [ ] 0201-error-chaining
- [ ] 0202-subslice-syntax-change
- [ ] 0212-restore-int-fallback
- [ ] 0214-while-let
- [ ] 0216-collection-views
- [ ] 0221-panic
- [ ] 0230-remove-runtime
- [ ] 0231-upvar-capture-inference
- [ ] 0234-variants-namespace
- [ ] 0235-collections-conventions
- [ ] 0236-error-conventions
- [ ] 0240-unsafe-api-location
- [ ] 0246-const-vs-static
- [ ] 0255-object-safety
- [ ] 0256-remove-refcounting-gc-of-t
- [ ] 0326-restrict-xXX-to-ascii
- [ ] 0339-statically-sized-literals
- [ ] 0341-remove-virtual-structs
- [ ] 0342-keywords
- [ ] 0344-conventions-galore
- [ ] 0356-no-module-prefixes
- [ ] 0369-num-reform
- [ ] 0378-expr-macros
- [ ] 0379-remove-reflection
- [ ] 0380-stabilize-std-fmt
- [ ] 0385-module-system-cleanup
- [ ] 0387-higher-ranked-trait-bounds
- [ ] 0390-enum-namespacing
- [ ] 0401-coercions
- [ ] 0403-cargo-build-command
- [ ] 0404-change-prefer-dynamic
- [ ] 0418-struct-variants
- [ ] 0430-finalizing-naming-conventions
- [ ] 0438-precedence-of-plus
- [ ] 0439-cmp-ops-reform
- [ ] 0445-extension-trait-conventions
- [ ] 0446-es6-unicode-escapes
- [ ] 0450-un-feature-gate-some-more-gates
- [ ] 0453-macro-reform
- [ ] 0459-disallow-shadowing
- [ ] 0461-tls-overhaul
- [ ] 0463-future-proof-literal-suffixes
- [ ] 0474-path-reform
- [ ] 0486-std-ascii-reform
- [ ] 0490-dst-syntax
- [ ] 0503-prelude-stabilization
- [ ] 0504-show-stabilization
- [ ] 0509-collections-reform-part-2
- [ ] 0520-new-array-repeat-syntax
- [ ] 0522-self-impl

**Comment by steveklabnik** [comment]
nominating for p-high, just like all 1.0 polish issues

**Comment by steveklabnik** [comment]
With the amount of stuff that's not implemented in RFCs, I don't think this approach is actually going to be useful.

**Comment by tshepang** [comment]
I think this is a great Issue to keep open, though you may want to remove 1.0 Milestone if there's too much work involved.

**Comment by tshepang** [comment]
One can always leave notes if something may be implemented in future if it's in an RFC.
