### ISSUE TITLE
Documentation example for InvariantType is strange

### ISSUE THREAD

**Issue by cgaebel** [rust-lang/rust#20147]
http://doc.rust-lang.org/std/kinds/marker/struct.InvariantType.html

It starts talking about cell for some reason. I think this was copy + pasted from InvariantLifetime and never updated.

**Comment by huonw** [comment]
`InvariantLifetime` doesn't have this example (now), and, the example only makes sense with `InvariantType` since there's no lifetimes involved in the definition of the `Cell` type. I do think the example could probably have a little more description, but I don't think it's wrong.
