### ISSUE TITLE
#[repr(...)] not allowed on c-like univariant enums

### ISSUE THREAD

**Issue by Aatch** [rust-lang/rust#20146]
This is currently an error:

```rust
#[repr(C)]
enum Foo {
    Foo
}
```

which is odd because it looks like a c-like enum. However it also looks like a univariant enum. We should specify which behaviour is correct.

More generally, should this be considered a c-like enum, or should it be a univariant enum. This affects several other aspects of the compiler.

**Comment by bluss** [comment]
Duplicate of #10292
