### ISSUE TITLE
BTreeMap's .get() doesn't show its trait bounds in rustdoc

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#20166]
BTreeMap::get and HashMap::get both use where bounds on the method, but on the BTreeMap the bounds are not visible in the documentation. The users need to see it to understand they can pass something using `BorrowFrom`.

Compare:

* http://doc.rust-lang.org/std/collections/btree_map/struct.BTreeMap.html#method.get
* http://doc.rust-lang.org/std/collections/hash_map/struct.HashMap.html#method.get

I can't find any immediate explanation from the source.

**Comment by sanxiyn** [comment]
This seems fixed. Can you confirm?

**Comment by bluss** [comment]
Indeed. Thank you for the notification!
