### ISSUE TITLE
Rustdoc not rendering some trait impls for BTreeSet and HashSet

### ISSUE THREAD

**Issue by csouth3** [rust-lang/rust#20175]
I noticed today that the rustdoc pages for BTreeSet and HashSet are both missing the sets' impls of `BitOr`, `BitAnd`, `BitXor`, and `Sub`.  The page for (for example) `BitOr` itself lists HashSet and BTreeSet as implementors (http://doc.rust-lang.org/std/ops/trait.BitOr.html, though HashSet is listed twice, I don't know what's up there either), so rustdoc is aware of the implementations, but clicking through to either set's page (e.g. http://doc.rust-lang.org/std/collections/struct.HashSet.html), the trait impls aren't there. 

I know for sure the impls for `BTreeSet` were rendered before #19448, so the fact that the impls changed from e.g. `for BTreeSet<T>` to `for &'a BTreeSet<T>` may be confusing rustdoc or something, but take that with a grain of salt, it's just a guess.

**Comment by apasel422** [comment]
This does appear to be related to the fact that the impls are for references. The `IntoIterator` impls for `&BTreeSet` and `&mut BTreeSet` (and the corresponding ones for the other collection types) have the same problem.
