### ISSUE TITLE
Type inference of a diverging function is weird

### ISSUE THREAD

**Issue by nodakai** [rust-lang/rust#20172]
These two codes compile fine:

```rust
fn main() {
    panic!();
    panic!() //  warning: unreachable expression, #[warn(unreachable_code)] on by default
}
```

```rust
fn f<R>() -> R {
    panic!()
}

fn main() {
    println!("hello");
    f()
}
```

but this does not (note the semicolon after `f()`):

```rust
fn f<R>() -> R {
    panic!()
}

fn main() {
    println!("hello");
    f(); // error: unable to infer enough type information about `_`; type annotations required
}
```

Though the Rust language reference seems to say there's an (inhabitable) type called the "bottom type," the behavior of `rustc` is almost as if the bottom type does not really exist in Rust.  These examples gave me an impression that a type equation involving a diverging function is simply discarded (otherwise `R` in the last example should correctly be inferred as the bottom type and there should be no difference between `foo();` and `panic();`,) though I'm aware `librustc/middle/infer/combine.rs` does consistency check of `FnDiverigng`...

See also rust-lang/rust#20105 which was originally filed as a complaint for not allowing this code:

```rust
fn g<F, R>(_: F) where F: Fn<(), R> {
}

fn main() {
    g(|| panic!()); // error: unable to infer enough type information about `_`; type annotations required
}
```

**Comment by arielb1** [comment]
@nodakal

The semicolon example not compiling doesn't have anything to do with bottom. `f` has type `for<T> ->T`, and there are no constraints on `T`, but without the semicolon, `T` is constrained to be `()`.
