### ISSUE TITLE
Fn item/fn pointer distinction breaks fn pointer generics

### ISSUE THREAD

**Issue by pmsanford** [rust-lang/rust#20178]
This is broken now:
```rust
fn accepts_optional_fn_ptr(_test: Option<fn(int) -> int>) {}
 
fn test_int(_: int) -> int { 0i }
 
fn main() {
    accepts_optional_fn_ptr(Some(test_int));
}
```
because it expects `Option<fn(int) -> int>` and gets `Option<fn(int) -> int {test_int}>`

This is an issue for FFI specifically because `Option<fn(...) -> ...>` is the idiomatic way (mentioned in the FFI guide) to represent C function pointers as it takes advantage of nullable pointer optimization.

I'll add that for anyone encountering this issue, an explicit cast fixes it:
```rust
accepts_optional_fn_ptr(Some(test_int as fn(int) -> int));
```

**Comment by chris-morgan** [comment]
More things are affected by this; here’s another example, one which #20415 does not appear to have fixed:

```rust
fn a() { }
fn b() { }

fn main() {
    let c = if true { a } else { b };
    c();
}
```

```text
k.rs:5:13: 5:37 error: if and else have incompatible types: expected `fn() {a}`, found `fn() {b}` (expected fn item, found a different fn item)
k.rs:5     let c = if true { a } else { b };
                   ^~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
```

Is this a separate issue? Should I file it as a new issue?

**Comment by huonw** [comment]
Separate issue please (I believe that sort of situation where the compiler has to implicitly construct some "supertype" without any type annotations is harder).

**Comment by Ryman** [comment]
@chris-morgan Did you file an additional issue for that? (Can't find one via search)
