### ISSUE TITLE
Refactor ParamBounds away completely

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#20196]
Once PR https://github.com/rust-lang/rust/pull/20159 lands, there will be only one (I believe) major remaining use of ParamBounds, which is that it is used to store the list of supertraits. We should remove `ParamBounds` completely and just use the generic predicate lists we've been working towards.

cc @jroesch

**Comment by steveklabnik** [comment]
Triage: there's no more `Parambounds`, but there is a `TyParamBounds`. Is that the same thing?

**Comment by nikomatsakis** [comment]
I think this is done.
