### ISSUE TITLE
Where clause bounds in re-exported structs clauses aren't preserved by rustdoc

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang/rust#20203]
e.g. given:

```rust
// foo.rs
pub struct Foo<A> where A: Copy;
pub struct Foo_<A: Copy>;
```

```rust
// bar.rs
extern crate foo;

pub use foo::{Foo, Foo_};
```

rustdoc will show the bound on `bar::Foo_` but not on `bar::Foo`.

**Comment by SimonSapin** [comment]
As an example of this, compare:

http://doc.rust-lang.org/std/slice/trait.SliceExt.html#tymethod.binary_search_by
http://doc.rust-lang.org/core/slice/trait.SliceExt.html#tymethod.binary_search_by
