### ISSUE TITLE
Inline assembly doesn't work with FP constraint

### ISSUE THREAD

**Issue by alexchandel** [rust-lang/rust#20213]
The following code:
```rust
pub fn log(x: f64) -> f64
{
	let out: f64;
	unsafe {
	asm!("fldln2
		fldl $1
		fyl2x" : "=t"(out) : "m"(x));}
	out
}
```

errors with the message:
```
error: couldn't allocate output register for constraint 't' at line 27
```

The constraint `t` refers to the top of the floating point stack in GCC's inline assembly, and the unsafe guide says our constraints mirror theirs.

**Comment by steveklabnik** [comment]
The chapter of the book says that we're "Like GCC and Clang" and points to the LLVM inline asm stuff, so I'm going to give this one a close.

**Comment by klutzy** [comment]
@steveklabnik This is still an issue; we currently don't do like "GCC and Clang". We do like llvm IR which is different from GCC/Clang.

For given GCC/Clang inline asm:

```C
__asm__("fldln2; fldl %1; fyl2x" : "=t"(out) : "m"(x));
```

Clang-3.7 emits the following LLVM IR:

```llvm
%2 = call double asm "fldln2; fldl $1; fyl2x",
"={st},*m,~{dirflag},~{fpsr},~{flags}"(double* %1) #2, !srcloc !1
```

where `"=t"` ([GCC x86 constraint](https://gcc.gnu.org/onlinedocs/gcc/Machine-Constraints.html#Machine-Constraints)) is converted to `"={st}`" ([LLVM IR x86 constraint](http://llvm.org/docs/LangRef.html#supported-constraint-code-list)).

Currently we simply pass `asm!()` arguments without such conversion, so only `"={st}"` works.

**Comment by alexchandel** [comment]
@steveklabnik I agree with @klutzy, this is exactly what I found confusing initially.

We could *actually* be "Like GCC and Clang" and translate `"=t"` to `"={st}"`, which is what I'd assume after reading the phrase "Like GCC and Clang", or we could say we're like LLVM IR.

**Comment by steveklabnik** [comment]
Okay, sorry for missing the boat here.

**Comment by alexchandel** [comment]
@steveklabnik nw. I don't even know whether rustc should support GCC/Clang inline assembly, though it might improve ease of use. It just felt like a papercut to find out the hard way that it doesn't.
