### ISSUE TITLE
Drop elision doesn't work with #[unsafe_no_drop_flag]

### ISSUE THREAD

**Issue by cgaebel** [rust-lang/rust#20219]
`#[unsafe_no_drop_flag]` prevents drop elision. This is especially unfortunate because most things with `Drop` impls also use `#[unsafe_no_drop_flag]`, including performance sensitive data structures like `Iobuf`s and `Vec`s.

See the following example, and note the call to `Drop` that is generated only in the `#[unsafe_no_drop_flag]` case.
# Code Tested

(build with `rustc x.rs --crate-type lib --opt-level 3 --emit llvm-ir --emit asm`)

``` rust
extern crate test;

#[unsafe_no_drop_flag]
pub struct BigAndComplicatedDestructor {
    x: [u8, ..255],
}

impl Drop for BigAndComplicatedDestructor {
    #[inline(never)]
    fn drop(&mut self) {
        if !self.x.iter().all(|&x| x == 0) {
            println!("DROP");
            test::black_box(self)
        }
    }
}

#[inline(never)]
fn f(x: BigAndComplicatedDestructor) {
    println!("1");
    drop(x)
}

pub fn look_at_me_copy(i: int, x: BigAndComplicatedDestructor) {
    f(x)
}
```
# With #[unsafe_no_drop_flag]

``` asm
__ZN15look_at_me_copy20h59e37a9f6231c17eucaE:
    .cfi_startproc
    .cfi_personality 155, _rust_eh_personality
Leh_func_begin2:
    .cfi_lsda 16, Lexception2
    leaq    -280(%rsp), %r11
    cmpq    %gs:816, %r11
    ja  LBB2_2
    movabsq $280, %r10
    movabsq $0, %r11
    callq   ___morestack
    retq
LBB2_2:
    pushq   %rbp
Ltmp18:
    .cfi_def_cfa_offset 16
Ltmp19:
    .cfi_offset %rbp, -16
    movq    %rsp, %rbp
Ltmp20:
    .cfi_def_cfa_register %rbp
    pushq   %r14
    pushq   %rbx
    subq    $256, %rsp
Ltmp21:
    .cfi_offset %rbx, -32
Ltmp22:
    .cfi_offset %r14, -24
    movq    %rsi, %rbx
    leaq    -272(%rbp), %r14
    movl    $255, %edx
    movq    %r14, %rdi
    callq   _memcpy
    xorl    %esi, %esi
    movl    $255, %edx
    movq    %rbx, %rdi
    callq   _memset
Ltmp15:
    movq    %r14, %rdi
    callq   __ZN1f20h6e40d25e2cfa92e4ibaE
Ltmp16:
    movq    %rbx, %rdi
    callq   __ZN32BigAndComplicatedDestructor.Drop4drop20h5306dcf8d3a2009fnaaE
    addq    $256, %rsp
    popq    %rbx
    popq    %r14
    popq    %rbp
    retq
```
# Without #[unsafe_no_drop_flag]

``` asm
__ZN15look_at_me_copy20h59e37a9f6231c17eucaE:
    .cfi_startproc
    .cfi_personality 155, _rust_eh_personality
Leh_func_begin2:
    .cfi_lsda 16, Lexception2
    leaq    -280(%rsp), %r11
    cmpq    %gs:816, %r11
    ja  LBB2_2
    movabsq $280, %r10
    movabsq $0, %r11
    callq   ___morestack
    retq
LBB2_2:
    pushq   %rbp
Ltmp18:
    .cfi_def_cfa_offset 16
Ltmp19:
    .cfi_offset %rbp, -16
    movq    %rsp, %rbp
Ltmp20:
    .cfi_def_cfa_register %rbp
    pushq   %r14
    pushq   %rbx
    subq    $256, %rsp
Ltmp21:
    .cfi_offset %rbx, -32
Ltmp22:
    .cfi_offset %r14, -24
    movq    %rsi, %rbx
    leaq    -272(%rbp), %r14
    movl    $256, %edx
    movq    %r14, %rdi
    callq   _memcpy
    xorl    %esi, %esi
    movl    $256, %edx
    movq    %rbx, %rdi
    callq   _memset
Ltmp15:
    movq    %r14, %rdi
    callq   __ZN1f20h6e40d25e2cfa92e4ibaE
Ltmp16:
    addq    $256, %rsp
    popq    %rbx
    popq    %r14
    popq    %rbp
    retq
```

There's another codegen bug here, too. The memset is a dead store, which llvm isn't smart enough to optimize away in either case. This leads me to believe that it still thinks the arguments are alive even though they're consumed. This function should have compiled into a `jmp`, but instead a `memcpy`, `memset`, and `drop` call are all generated.

Merry Christmas!

cc @aatch

**Comment by dotdash** [comment]
The memset isn't removed because DSE doesn't look across basic block boundaries, and the `invoke` used for the call to `f` introduces a block boundary :-/ For _this_ case, there used to be an optimization that turned `invoke` instructions with empty landing pads into calls, but that was disabled in LLVM r176827. I just sent an email to the llvm-dev list about that, because I think it might have been wrong to disable that optimization. The mail doesn't show up on the list archives yet though. Will link it here once it pops up.

**Comment by dotdash** [comment]
Had to resend the mail because I wasn't subscribed and it got lost in the spam. Here's the new one:
http://lists.cs.uiuc.edu/pipermail/llvmdev/2015-January/081016.html

**Comment by dotdash** [comment]
r176827 just got reverted in r226850. Unfortunately that's not in the 3.6 branch.

**Comment by steveklabnik** [comment]
Updated example:

```
#![feature(unsafe_no_drop_flag)]
#![feature(test)]

extern crate test;

#[unsafe_no_drop_flag]
pub struct BigAndComplicatedDestructor {
    x: [u8; 255],
}

impl Drop for BigAndComplicatedDestructor {
    #[inline(never)]
    fn drop(&mut self) {
        if !self.x.iter().all(|&x| x == 0) {
            println!("DROP");
            test::black_box(self);
        }
    }
}

#[inline(never)]
fn f(x: BigAndComplicatedDestructor) {
    println!("1");
    drop(x)
}

pub fn look_at_me_copy(i: i32, x: BigAndComplicatedDestructor) {
    f(x)
}
```

And to compile:

```
$ rustc hello.rs --crate-type lib -C opt-level=3 --emit llvm-ir --emit asm
```

I am not good enough at reading the generated output to determine the state of the bug, however.

**Comment by jonas-schievink** [comment]
Drop flags are gone, is this still relevant?

**Comment by steveklabnik** [comment]
I don't think so, even `unsafe_no_drop_flag` is gone, IIRC. Giving this a close. Please let me know if that's wrong!
