### ISSUE TITLE
Switch to mach

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#20235]
Using makefiles for testing is rather broken (for example, if you want to run a different test via `TETNAME=foo make-check-stage2-runpass`, you have to delete the runpass binary  and re-call make).

I suggest we move as much of the testing and other infrastructure out into [mach](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/mach), Mozilla's supercharged-make-in-python. Servo has already made this switch and the workflow is much smoother. The `./mach build` command can internally call `configure`/`make` (at least initially), and instead of setting environment variables for various test tweaks we can set command line flags.

If I get time I'd love to work on this, but I'd like to know if this is really wanted first :)

**Comment by christopherdumas** [comment]
Should someone start working on this?

**Comment by ranma42** [comment]
Is this superseded by #31590 (rustbuild) ?

**Comment by Manishearth** [comment]
No, mach is more of a wrapper around cargo to provide utility shortcuts

**Comment by alexcrichton** [comment]
Looking at this now, with rustbuild we're probably not going to switch to mach, so I'm going to close this.
