### ISSUE TITLE
Take care of boundaries in Step trait

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#20249]
Watch out for min/max boundaries in the Step trait.

It would be more natural for (0i8..) to produce a finite range, ending with the maximum value 127i8, than to overflow and produce an infinite iterator.  Overflow is problematic, (and if we let it stay in, users will rely on the wrap around behavior.) and the Range objects and Step traits need to handle this with care.

The current Step trait supposes that every element has a successor, which is not necessarily true.

**Comment by aturon** [comment]
This behavior was changed in a recent [stabilization PR](https://github.com/rust-lang/rust/pull/21258) to panic on overflow on debug builds (matching the anticipated overflow RFC).

**Comment by bluss** [comment]
As long as the panic checks is elided in bounded loops, the performance fallout won't matter that much.
