### ISSUE TITLE
When building on OSX, "-L" needs to set the search path for frameworks as well as libraries.

### ISSUE THREAD

**Issue by caryhaynie** [rust-lang/rust#20259]
Currently, it appears that
1) rustc disables the standard framework search path by default,
2) the only way to specify an alternative framework search path is via '-C link_args="-F <path>"' to rustc, or by using the oft derided link_args crate attribute.

This makes linking against frameworks via cargo incredibly difficult, since cargo only allows setting the "-l" and "-L" compiler flags. It would be great if rustc modified both the dylib search path *and* the framework search path when a "-L" option is passed to rustc on OSX.

**Comment by jonasp** [comment]
@alexcrichton suggested in [rust-lang/cargo/#1272](https://github.com/rust-lang/cargo/issues/1272#event-230158360) to add `-L framework=foo` which should be translated to `-F` just like `-l framework=foo` is being translated into `-framework`.
