### ISSUE TITLE
Decide what precedence `..` should have

### ISSUE THREAD

**Issue by P1start** [rust-lang/rust#20256]
Currently, `1i + 1i..1i + 1i` is parsed as `1i + (1i..(1i + 1i))`. This seems problematic. I would expect it to be parsed as `(1i + 1i)..(1i + 1i)` (to match with how the current slicing syntax behaves), or possibly as `1i + (1i..1i) + 1i`.

**Comment by nick29581** [comment]
I agree they should be parsed as `(1i + 1i)..(1i + 1i)`

**Comment by nick29581** [comment]
I think `1..2..3` should be an error rather than resolving either way, since there is not an obvious right answer

**Comment by sinistersnare** [comment]
@nick29581 could `1..2..3` work if there was a `Range<Range<int,int>, int>` implementation?

**Comment by nick29581** [comment]
@sinistersnare We could make it work in one direction or the other, but I'm not sure I'd want to - `(1..2)..3` is not too much hassle and it's a lot clearer

**Comment by sinistersnare** [comment]
Sure, makes sense :)

**Comment by dgrunwald** [comment]
So did we decide on a specific precedence level? I'd argue it should be lower than arithmetic operators (which is now fixed); but higher than comparison operators (`range == 1..2` should be valid, but currently isn't).
