### ISSUE TITLE
Unify OS-specific types' trait implementations

### ISSUE THREAD

**Issue by FlaPer87** [rust-lang/rust#20260]
There are quite few os-specific types definitions whose traits implementations are not consistent. With the work happening in OIBIT, I've tried to keep the implementations of built-in traits consistent for both `unix` and `windows`. Unfortunately, the test suite for these implementations is not unified, therefore there's a high chance that some types for `window`'s implementation may have some traits implemented, whereas the `unix`'s implementation doesn't.

In theory, we can assume that common types for these implementations should implement the same built-in types, therefore there should be tests that enforce this guarantee in a common place.

Some examples may be found in `std::sys::{unix,windows}::{pipe,mutex}`

This bug is to track the work there which impacts the `stability` of our standard library.

**Comment by samphippen** [comment]
This should be closed now right?

**Comment by FlaPer87** [comment]
@samphippen correct. Thanks!
