### ISSUE TITLE
Shifts shouldn't be tied to pointer-size integers

### ISSUE THREAD

**Issue by pcwalton** [rust-lang/rust#20288]
Let's fix this. Backwards-incompatible language/library change.

**Comment by nagisa** [comment]
Seems like this was introduced, at least in part, by https://github.com/rust-lang/rust/pull/15407.

Shifting by an arbitrary unsigned integer sounds nice.

**Comment by nagisa** [comment]
Should be fixed by https://github.com/nikomatsakis/rust/commit/d803e2241358c2907cbbd5536c0da9a5f2548fe9, which is part of  #20754.

**Comment by tbu-** [comment]
@nagisa Doesn't look like it, this commit only touches the `<<` syntax for primitive types, not their `Shl` implementation.

**Comment by nagisa** [comment]
@tbu- @nikomatsakis claims that traits are bypassed for primitive integer shifting, so I suppose the traits are there for documentation purposes. If you look at the tests added in the linked commit, shift operations should indeed support using any-sized integer as a right-hand size now.

We only need to update documentation to match the implemented behaviour.

**Comment by nikomatsakis** [comment]
Fixed in https://github.com/rust-lang/rust/pull/20754

**Comment by nikomatsakis** [comment]
Specifically https://github.com/nikomatsakis/rust/commit/20744c6b855956eb3d39f5afda332480546f9e28

**Comment by nikomatsakis** [comment]
On IRC, [simukis points out](https://botbot.me/mozilla/rust-internals/2015-01-10/?msg=29214355&page=12) that without suitable impls this is not 100% fixed, since shifts can't be as naturally used in generic code: 

```
[09:18:08] <simukis> nikomatsakis: tbu- argues that your fix doesn’t apply for, uhm, generic code
[09:18:39] <simukis> something like fn `magic(a : T) where T: Shr { a << 10i8 }`
[09:18:59] <simukis> nmatsakis: ^
[09:19:15] <simukis> nmatsakis: this is re issue you just closed
[09:20:10] <simukis> though I have no idea how that would be implemented.
[09:21:03] <nmatsakis> simukis: ah, well, he's not wrong. we should probably add more impls.
```

**Comment by nikomatsakis** [comment]
Therefore re-opening the issue, though I believe the biggest part of this issue is fixed.
