### ISSUE TITLE
Uninstalling Rust downloads the whole Rust again

### ISSUE THREAD

**Issue by sim4life** [rust-lang/rust#20283]
Running the uninstall script on Mac OS X
`curl -s https://static.rust-lang.org/rustup.sh | sudo sh -s -- --uninstall`
downloads the while ~200MB of rust sources and then uninstalls the already installed Rust binaries.
It should NOT download the rust sources in case the uninstall option is given.

**Comment by brson** [comment]
I have a todo to include an uninstall script with the installation.

**Comment by brson** [comment]
cc https://github.com/rust-lang/rust/issues/21117
