### ISSUE TITLE
Don't require parentheses when accessing nested tuple

### ISSUE THREAD

**Issue by nstoddard** [rust-lang/rust#20287]
If you have a nested tuple like this:

```let a = ((1u8, 2u8), (3u8, 4u8));```

You can't access it like this:

```println!("{}", a.1.1);```

Instead, you have to do this:

```println!("{}", (a.1).1);```

I can't think of any good reason why the former shouldn't be allowed. Maybe rustc is parsing it as the number `1.1`? It seems like it shouldn't be hard to fix, since the compiler is already able to suggest adding the parentheses.

**Comment by sffc** [comment]
Not high-priority, but it would still be nice to fix this syntax and avoid the search on how to work around it.

**Comment by petrochenkov** [comment]
@sffc 
This was actually implemented recently - https://github.com/rust-lang/rust/pull/71322.
