### ISSUE TITLE
Integrate object projection predicates into rustdoc

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#20299]
I think an object type like `Iterator<T=uint>` currently just ignores the `T=uint` bounds found in the `ExistentialBounds` struct.

**Comment by nikomatsakis** [comment]
This is particularly relevant if we move function return types to be an associated type as proposed in #20871.

**Comment by nikomatsakis** [comment]
These are ignored for where-clauses too, afaik.

**Comment by tomjakubowski** [comment]
This is sort of done, though awkwardly for re-export cases, for where clauses in #21018.

**Comment by tomjakubowski** [comment]
As for object projection predicates, this should work already for the "one crate" case, but not for re-exports (as usual!). For re-exports, we need to be able to bubble the associated type bindings up from the `Clean` impl of `ty::ExistentialBounds` all the way up to wherever the `clean::PathParameters` is constructed, so I think that `Clean` impl will need to return `(Vec<TyParamBound>, Vec<TypeBinding>)`.
