### ISSUE TITLE
Smarter integration of projection predicates into trait selection

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#20297]
The current logic that integrates projection predicates into trait selection is somewhat flawed. I made some simplifying choices:
1. For one thing, it only works if the _self type_ is a projection type, but in reality it should be able to handle any input type. Moreover, there may be multiple projection types in play.
2. Also, the integration with inference is not particularly smart. 
3. Finally, if there are where clauses that overlap with projections, we currently just choose the where clause every time, but this may influence inference or have other subtle effects.

These all feel a bit like corner cases for now and I think we can get away with leaving things as they are and later coming in with a much smarter trait selection system. It's clear that we're pushing the bounds of the current setup. Trait reform 2.0 anybody?

**Comment by jroesch** [comment]
cc me

**Comment by steveklabnik** [comment]
Triage: no idea what's going on with this, and it's very, very old. @nikomatsakis is this still relevant?

**Comment by Mark-Simulacrum** [comment]
Is this still relevant? It's a very old issue, and it seems there was some progress judging by the items in GH's log.

**Comment by nikomatsakis** [comment]
This is all still relevant but I feel this issue adds approximately zero value. Closing.
