### ISSUE TITLE
Convert `T::Foo` resolution to use where clauses, not bounds

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#20300]
Currently referencing an associated type like `T::Foo` searches the bounds on `T` rather than the full set of where clauses. This is no good.

**Comment by nikomatsakis** [comment]
Nominating and placing on 1.0 alpha milestone. Ultimately PROBABLY a nice to have, but it's really surprising that this doesn't work.

**Comment by jroesch** [comment]
cc me

**Comment by erickt** [comment]
Until this is implemented, you can also use a qualified type path `<T as Trait>::Item`:

```rust
trait Trait {
    type Item;
}

struct Foo;

impl Foo {
    fn foo1<T: Trait>(_x: T::Item) {}

    fn foo2<T>(_x: <T as Trait>::Item) where T: Trait {}
}

struct Bar;

impl Trait for Bar {
    type Item = i32;
}

fn main() {
    Foo::foo1::<Bar>(5i32);
    Foo::foo2::<Bar>(5i32);
}
```

**Comment by carllerche** [comment]
cc me

**Comment by ahmedcharles** [comment]
Would anyone mind mentoring this?

**Comment by nikomatsakis** [comment]
@ahmedcharles a fix is in progress already, actually, but it turns out to be quite a tricky problem. Much trickier than it appeared at first.

**Comment by darinmorrison** [comment]
cc me
