### ISSUE TITLE
We permit type parameters and so forth on builtin bounds

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#20302]
Example:

```
fn foo<T:Copy<U>, U>(x: T) {
}

fn main() {
}
```

I left a FIXME at the relevant part of the code.

**Comment by FlaPer87** [comment]
I can mentor...

**Comment by richo** [comment]
I'm willing to have a look if the mentor offer stands @FlaPer87

**Comment by ahmedcharles** [comment]
I already have a proposed fix, I just need to clean it up and add a test.

**Comment by FlaPer87** [comment]
@richo thanks for volunteering. The offer is still up but @ahmedcharles has been working on it. I'm happy to help with other bugs too.
