### ISSUE TITLE
Use `ast::Name` rather than `ast::Ident` for associated type names

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#20301]
We currently use idents everywhere in the front-end but convert to names in the backend. Afacit, associated type names should not be subject to hygiene (rather like a method name), and hence `Name` is a better choice.

**Comment by jonas-schievink** [comment]
This seems to be at least partially fixed, since [`ProjectionTy` uses `Name`](https://github.com/rust-lang/rust/blob/4b308b44e1d8204702f6912dda4dfc404aa2a87d/src/librustc/middle/ty/sty.rs#L409-L415).

**Comment by petrochenkov** [comment]
Yes, this can be closed, everything unhygienic outside of libsyntax uses `Name`s now

**Comment by alexcrichton** [comment]
Thanks @petrochenkov!
