### ISSUE TITLE
Assembler output when using -Z asm-comments emits long sequences of empty lines (hundreds to thousands)

### ISSUE THREAD

**Issue by sivadeilra** [rust-lang/rust#20324]
Run `rustc -Z asm-comments --emit asm ...`, and look at the generated assembly code.  It will often have very long sequences of empty lines, or lots of blocks like this:

```
	#NO_APP
	#APP

	#NO_APP
	#APP

	#NO_APP
	#APP

	#NO_APP
	#APP

	#NO_APP
	#APP

	#NO_APP
	#APP

	#NO_APP
	#APP
```

It would be best to collapse all contiguous blank lines into a single blank line, and to drop back-to-back `#NO_APP` / `#APP` markers.

**Comment by richardscottmills** [comment]
I can not reproduce this issue.  Emitted asm looks fine to me...

**Comment by istankovic** [comment]
I can't reproduce this either with a recent nightly, rustc 1.9.0-nightly (924da295c 2016-04-10).
Probably should be closed, unless there is a source code example that demonstrates the issue.
