### ISSUE TITLE
Segfault in `Hasher<SipState>::hash`

### ISSUE THREAD

**Issue by fitzgen** [rust-lang/rust#20355]
Test case is branch `sip-hasher-segault` of this repo: https://github.com/fitzgen/oxischeme/tree/sip-hasher-segfault

    $ rustc --version --verbose
    rustc --version --verbose
    rustc 0.13.0-nightly (5ba610265 2014-12-25 18:01:36 +0000)
    binary: rustc
    commit-hash: 5ba6102657a892457063d2d6a7cbb9632ce282c6
    commit-date: 2014-12-25 18:01:36 +0000
    host: x86_64-apple-darwin
    release: 0.13.0-nightly
    $ rustc -g --test src/main.rs -o target/test
    $ lldb ./target/test
    lldb ./target/test
    (lldb) target create "./target/test"
    Current executable set to './target/test' (x86_64).
    (lldb) run
    Process 8270 launched: './target/test' (x86_64)

    running 20 tests
    Process 8270 stopped
    * thread #2: tid = 0x25693, 0x0000000100008bed test`hash::sip::SipHasher.Hasher$LT$SipState$GT$::hash::h16497116303610205953 + 61, stop reason = EXC_BAD_ACCESS (code=1, address=0x3ffd9)
        frame #0: 0x0000000100008bed test`hash::sip::SipHasher.Hasher$LT$SipState$GT$::hash::h16497116303610205953 + 61
    test`hash::sip::SipHasher.Hasher$LT$SipState$GT$::hash::h16497116303610205953 + 61:
    -> 0x100008bed:  movq   (%rsi), %rsi
       0x100008bf0:  movq   -0x8(%rbp), %rdi
       0x100008bf4:  movq   0x8(%rdi), %rdx
       0x100008bf8:  movq   %rax, %rdi
    (lldb) bt
    * thread #2: tid = 0x25693, 0x0000000100008bed test`hash::sip::SipHasher.Hasher$LT$SipState$GT$::hash::h16497116303610205953 + 61, stop reason = EXC_BAD_ACCESS (code=1, address=0x3ffd9)
      * frame #0: 0x0000000100008bed test`hash::sip::SipHasher.Hasher$LT$SipState$GT$::hash::h16497116303610205953 + 61
        frame #1: 0x0000000105401810
        frame #2: 0x0000000100008ba2 test`hash::RandomSipHasher.Hasher$LT$sip..SipState$GT$::hash::h10512232733763305808 + 66
        frame #3: 0x0000000100008b0e test`collections::hash::table::make_hash::h9604696550138645665 + 62
        frame #4: 0x0000000100008abe test`collections::hash::map::HashMap$LT$K$C$$u{20}V$C$$u{20}H$GT$::make_hash::h15786379260790357760 + 62
        frame #5: 0x0000000100008963 test`collections::hash::map::HashMap$LT$K$C$$u{20}V$C$$u{20}H$GT$::insert::h6805880362953821147 + 131
        frame #6: 0x0000000100006aea test`main::environment::Environment::define(self=0x000000000003ffc1, sym=String at 0x0000000105401a50, val=0x0000000105401c38) + 218 at environment.rs:92
        frame #7: 0x0000000100018486 test`main::eval::evaluate_definition(heap=0x00000001054034e8, env=0x0000000105402d10, form=0x0000000105402ce0) + 2406 at eval.rs:195
        frame #8: 0x0000000100013f1b test`main::eval::evaluate(heap=0x00000001054034e8, env=0x0000000105402d90, form=0x0000000105402f30) + 1355 at eval.rs:79
        frame #9: 0x0000000100013909 test`main::eval::evaluate_in_global_env(heap=0x00000001054034e8, form=0x0000000105402f30) + 105 at eval.rs:38
        frame #10: 0x000000010001cd7b test`main::eval::evaluate_file(heap=0x00000001054034e8, file_path=(data_ptr = "./tests/test_eval_closures.scmsrc/heap.rsArenaPtr(, )Rooted(", length = 30)) + 1035 at <std macros>:286
        frame #11: 0x000000010002c071 test`main::eval::test_eval_closures + 129 at eval.rs:403
        frame #12: 0x0000000100087154 test`thunk::F.Invoke$LT$A$C$$u{20}R$GT$::invoke::h5218640484166224076 + 52
        frame #13: 0x0000000100091e32 test`thunk::F.Invoke$LT$A$C$$u{20}R$GT$::invoke::h13672304839710771993 + 162
        frame #14: 0x0000000100088912 test`thunk::F.Invoke$LT$A$C$$u{20}R$GT$::invoke::h15490786364890695979 + 1138
        frame #15: 0x0000000100088db0 test`rt::unwind::try::try_fn::h10439459448986358359 + 160
        frame #16: 0x000000010010a4f9 test`rust_try_inner + 9
        frame #17: 0x000000010010a4e6 test`rust_try + 6
        frame #18: 0x00000001000894ab test`thunk::F.Invoke$LT$A$C$$u{20}R$GT$::invoke::h13206639752781900349 + 1179
        frame #19: 0x0000000100106eb4 test`sys::thread::thread_start::h2cb22211a4c7d938vFw + 164
        frame #20: 0x00007fff875d3899 libsystem_pthread.dylib`_pthread_body + 138
        frame #21: 0x00007fff875d372a libsystem_pthread.dylib`_pthread_start + 137
        frame #22: 0x00007fff875d7fc9 libsystem_pthread.dylib`thread_start + 13

**Comment by pythonesque** [comment]
I probably would.  But if you can find a reproducible test case that doesn't use any unsafe code, you can always reopen it :)
