### ISSUE TITLE
rustup build fails on OS X Yosemite

### ISSUE THREAD

**Issue by bharadwaj6** [rust-lang/rust#20364]
It seems like cargo is uninstalling rust for during installation. Had previous nightly working before this installation. Here's the full trace: https://gist.github.com/bharadwaj6/e39b340fab59bdab1066 and this is the `rustup.sh` that is being used: https://gist.github.com/bharadwaj6/dd69ce6299d8e7cad8f7 

Version of `cargo` installed after installation `cargo 0.0.1-pre-nightly (e6abfbb 2014-12-30 18:14:23 +0000)`. `rustc -v` says `command not found`. I've tried it with `'/usr/local/lib'` added to `DYLD_LIBRARY_PATH` and otherwise, but same result.

**Comment by alexchandel** [comment]
So does `https://static.rust-lang.org/rustup.sh` work yet or not?

**Comment by Binero** [comment]
@alexchandel Try it, and tell us. :)

**Comment by Jurily** [comment]
It doesn't, as of 5-ish minutes ago....

**Comment by brson** [comment]
It should work now.
