### ISSUE TITLE
recursion dependent on global offset table

### ISSUE THREAD

**Issue by ragingSloth** [rust-lang/rust#20379]
While trying to use rust freestanding I found that any attempt to use recursion resulted in an error while linking. 

    main.o: In function `put':
    main.0.rs:(.text.put+0xc): undefined reference to `_GLOBAL_OFFSET_TABLE_'
    main.o: In function `r_write':
    main.0.rs:(.text.r_write+0xf): undefined reference to `_GLOBAL_OFFSET_TABLE_'

I'm not sure if this is an issue, but I can't find any way to use recursion without a global offset table. I'm compiling with `#[no_std]` and `-O --target i686-unknown-linux-gnu --crate-type lib --emit obj`, and I recieve errors when trying to link separately.

**Comment by huonw** [comment]
Do you happen to have a code example that demonstrates this?

**Comment by ragingSloth** [comment]
#[no_stack_check]
    pub fn put(head: &mut Cell, s: &str) {
        let st: &[u8] = unsafe {utils::transmute(s)};
        unsafe {r_write((head as *mut Cell), st)};
    }

    #[no_stack_check]
    unsafe fn r_write(head: *mut Cell, s: &[u8]) {
        match s {
            [x, xs..] => {
                (*head).incr();
                put_char(&*head, (x as char));
                r_write(head, xs)
            },
            _ => (),
        }
    }

**Comment by thestinger** [comment]
It's not really helpful if it doesn't compile. Rust doesn't determine any of this itself anyway - it's up to the compiler backend (LLVM) and the linker. If you don't want the `pic` or `dynamic-no-pic` relocation models then you should ask for the `static` model.

**Comment by thestinger** [comment]
I think everything is working as intended here.

**Comment by huonw** [comment]
@ragingSloth (the relocation model can be controlled via the `-C relocation-model=...` argument to rustc.)

**Comment by ragingSloth** [comment]
thanks, that fixed it, sorry to waste your time.

**Comment by huonw** [comment]
It's not a waste of time. :)
