### ISSUE TITLE
mkinstall.sh failure

### ISSUE THREAD

**Issue by d3zd3z** [rust-lang/rust#20383]
Some time between f673e9841 and 84f5ad8679, I stopped being able to run 'make install', with the following error.  I can start bisecting if that is useful, but the problem may be more obvious to someone more familiar with the build system.

    gen-installer: looking for programs
    gen-installer: 
    gen-installer: found tar
    gen-installer: found cp
    gen-installer: found rm
    gen-installer: found mkdir
    gen-installer: found echo
    gen-installer: found tr
    gen-installer: found awk
    gen-installer: 
    gen-installer: processing /mnt/language/rust/rust/src/rust-installer/gen-installer.sh args
    gen-installer: 
    gen-installer: CFG_PRODUCT_NAME     := Rust 
    gen-installer: CFG_COMPONENT_NAME   := rustc 
    gen-installer: CFG_PACKAGE_NAME     := rust-0.13.0-dev-x86_64-unknown-linu ...
    gen-installer: CFG_VERIFY_BIN       := rustc 
    gen-installer: CFG_REL_MANIFEST_DIR := rustlib 
    gen-installer: CFG_SUCCESS_MESSAGE  := Rust-is-ready-to-roll. 
    gen-installer: CFG_LEGACY_MANIFEST_DIRS := rustlib,cargo 
    gen-installer: CFG_NON_INSTALLED_PREFIXES := COPYRIGHT,LICENSE-APACHE,LICENSE-MI ...
    gen-installer: CFG_BULK_DIRS        :=  
    gen-installer: CFG_IMAGE_DIR        := tmp/dist/rust-0.13.0-dev-x86_64-unk ...
    gen-installer: CFG_WORK_DIR         := tmp/dist 
    gen-installer: CFG_OUTPUT_DIR       := dist 
    gen-installer: 
    gen-installer: validating /mnt/language/rust/rust/src/rust-installer/gen-installer.sh args
    gen-installer: 
    gen-install-script: looking for install programs
    gen-install-script: 
    gen-install-script: found sed
    gen-install-script: found chmod
    gen-install-script: found cat
    gen-install-script: 
    gen-install-script: processing /mnt/language/rust/rust/src/rust-installer/gen-install-script.sh args
    gen-install-script: 
    gen-install-script: CFG_PRODUCT_NAME     := Rust 
    gen-install-script: CFG_VERIFY_BIN       := rustc 
    gen-install-script: CFG_REL_MANIFEST_DIR := rustlib 
    gen-install-script: CFG_SUCCESS_MESSAGE  := Rust-is-ready-to-roll. 
    gen-install-script: CFG_OUTPUT_SCRIPT    := tmp/dist/rust-0.13.0-dev-x86_64-unk ...
    gen-install-script: CFG_LEGACY_MANIFEST_DIRS := rustlib,cargo 
    gen-install-script: 
    gen-install-script: validating /mnt/language/rust/rust/src/rust-installer/gen-install-script.sh args
    gen-install-script: 
    mkdir -p tmp/empty_dir
    make[1]: Leaving directory '/mnt/language/rust/rust'
    sh: ../../tmp/dist/rust-docs-0.13.0-dev-x86_64-unknown-linux-gnu/install.sh: No such file or directory
    /mnt/language/rust/rust/mk/install.mk:22: recipe for target 'install' failed

**Comment by davideagen** [comment]
I'm having the same problem

**Comment by utkarshkukreti** [comment]
Same here.

**Comment by d3zd3z** [comment]
This seems to be an issue with building vs installing the docs.  The build system will happily build without all of the tools necessary to generate the docs, but 8b3c67690c47 seems to assume they all got built, unless the user explicitly adds `--disable-docs` to the configure line.

I was able to work around this program by adding `--disable-docs` to my configure invocation.  Since I mostly read the docs online (or look directly at the source), this works OK for me.

**Comment by yeahnoob** [comment]
No "disable-docs", No "make install" at this time.

And nothing about this is expained in rust's documents, for now...

**Comment by nodakai** [comment]
I filed an issue #19698 last month so that Rust Buildbot could catch errors like this, but no one with an access to Rust Buildbot has paid an attention to it.

**Comment by tbu-** [comment]
I believe this one can be closed, it's fixed now (I had this problem before, but now it's gone).
