### ISSUE TITLE
Error of attribute without trailing item inside a function points to trailing bracket, not offending tokens

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#20397]
``` rust
fn main() { #[whoops] x }
```

```
<anon>:1:21: 1:22 error: expected item after attributes
<anon>:1 fn main() { #[whoops] x }
                             ^
```

The caret should point at the `x`, not the `]`.

**Comment by frewsxcv** [comment]
Visiting for triage: this is still an issue

[playpen link](http://is.gd/l59Ir5)

**Comment by birkenfeld** [comment]
Issue seems obsolete now that attributes on stmt/expr are allowed, if experimental.

The remaining case of "expected item after attributes" is when there is nothing afterwards, in which case the span is probably fine.

**Comment by Mark-Simulacrum** [comment]
Yeah closing as fixed; stmt/expr attributes sort of solved this indirectly.
