### ISSUE TITLE
Std doc playpen links don't all link to the correct example

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#20394]
In [Vec](http://doc.rust-lang.org/std/vec/struct.Vec.html), all the [examples](http://doc.rust-lang.org/std/vec/struct.Vec.html#examples) link to the proper example in [play.rust-lang.org](http://play.rust-lang.org). The example in [Vec::new()](http://doc.rust-lang.org/std/vec/struct.Vec.html#method.new) does not neither do any of the other methods.

They should link to the correct examples.

**Comment by steveklabnik** [comment]
Whoah, that's werid.

**Comment by kmcallister** [comment]
Fixed by #20990, I believe.
