### ISSUE TITLE
TaskPool should derive Clone

### ISSUE THREAD

**Issue by tobbebex** [rust-lang/rust#20408]
I would like to execute functions on a task pool that in turn executes more functions in the same pool. Since TaskPool is just wrapping a Sender, making it derive Clone would be a simple solution to allow for this.

**Comment by sfackler** [comment]
You can toss it in an `Arc`.

**Comment by tobbebex** [comment]
I would need to put it in a Mutex first since Sender isn't Sync. I really don´t want to pay that extra cost when Sender is already Clonable to avoid locking.

**Comment by aturon** [comment]
FWIW, I think we should consider moving `TaskPool`(which should probably be `ThreadPool`) out of `std` and into the crates.io ecosystem for the time being. I suspect we'll want to experiment and iterate with various designs, and we're not ready to stabilize it in `std` yet.

Thoughts? /cc @alexcrichton @reem

**Comment by alexcrichton** [comment]
I also agree that this should move out of the standard library. I don't think we should stabilize what we currently have.

**Comment by reem** [comment]
I think it should go elsewhere for a while, it's not really useful with the new thread semantics. I already rewrote a custom version to be an acceptor pool for hyper, fwiw.

**Comment by aturon** [comment]
@reem Is that readily available in its own crate, or otherwise easy to get at? Throw me a link? I'm going to deprecate the in tree version and would like to link to it.

**Comment by reem** [comment]
@aturon It's rather specialized to accepting, so it's not really useful as anything other than a basis for future work, but: https://github.com/hyperium/hyper/blob/master/src/server/acceptor.rs

**Comment by aturon** [comment]
Closing in favor of #22427
