### ISSUE TITLE
debuginfo: Debugger pretty printers cannot handle all enum memory layouts

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#20405]
Since @luqmana's cool [enum memory layout optimizations](https://github.com/rust-lang/rust/pull/19765) landed, GDB and LLDB pretty printers are slightly out of date, i.e. they cannot handle cases where the discriminant isn't stored at the top-level. The necessary data is already encoded in DWARF, but the pretty printers don't use it yet.

**Comment by cactorium** [comment]
Mind if I take a stab at this?

**Comment by cactorium** [comment]
Okay, so I'm having trouble figuring out how to load the pretty printers into gdb, and it doesn't seem to be documented in any of the Rust docs. Any advice you can give me? Sorry!

**Comment by michaelwoerister** [comment]
Whoops, sorry, I meant to respond to this earlier.
Assuming that you are using a current version of `rustc`, the easiest way to do that is to use the `rust-gdb` script. It will use the pretty printers coming with the `rustc` that is in your `PATH`. So, if you call...
```
LD_LIBRARY_PATH=<your-rust-directory>/x86_64-unknown-linux-gnu/stage1/lib \
PATH=<your-rust-directory>/x86_64-unknown-linux-gnu/stage1/bin:$PATH \
rust-gdb <regular gdb args>
```
... then GDB will be started with the pretty printers located in `<your-rust-directory>/x86_64-unknown-linux-gnu/stage1/lib/rustlib`. Note though that these are copies of the 'real' pretty printer source files in `src/etc`. You might want to modify the files in `stage1/lib/rustlib` for quick testing but beware of losing those modifications when rebuilding `rustc` because that will overwrite the files in `stage1/lib/rustlib` with those in `src/etc` again.

Don't hesitate to post any further questions here as they arise `:)`

**Comment by cactorium** [comment]
Ah, that is exactly what I needed! Thank you very much :)

**Comment by cactorium** [comment]
I think this can be closed now?

**Comment by alexcrichton** [comment]
Thanks @cactorium!
