### ISSUE TITLE
emacs-mode shouldn't highlight keywords in identifiers

### ISSUE THREAD

**Issue by gsingh93** [rust-lang/rust#20422]
`emacs-mode` is highlighting keywords in identifiers. An example:
```
fn fn_foo() {   
}
```
The `fn` in `fn_foo()` is highlighted when it shouldn't be.

**Comment by huonw** [comment]
cc https://github.com/rust-lang/rust/issues/8793

**Comment by swgillespie** [comment]
This should be fixed now.
