### ISSUE TITLE
Rename target_word_size

### ISSUE THREAD

**Issue by sanxiyn** [rust-lang/rust#20421]
At the moment, `target_word_size` in conditional compilation attributes actually refers to pointer size. Since word size (or register size) and pointer size are different concepts, it should be renamed.

**Comment by huonw** [comment]
Seems like `target_pointer_size` would be more appropriate.

**Comment by nagisa** [comment]
Do we want to do some transition period? I.e.

* Support both target_word_size and target_pointer_size
* Release a snapshot
* Remove the support for target_word size

**Comment by thestinger** [comment]
I doubt there are a significant number of users outside of the low-level standard libraries. Many of those are likely incorrect because they really do want the largest hardware integer type.

**Comment by nagisa** [comment]
@thestinger the problem here are not users outside, but the std itself. If we just rename the attribute to something else, the code will build with stage0 but not stage > 0 and were we to replace the use of attributes everywhere as well, libstd would not build with stage0.

**Comment by sfackler** [comment]
You don't necessarily need a period of time with support for both. You can either just stick both attributes on the types with one used at stage0 and one after, or use cfg_attr if you don't want the unused attribute warnings.

**Comment by jmesmon** [comment]
Was there a reason this didn't also adjust the json field name?

**Comment by nagisa** [comment]
@jmesmon None. You should fill a new issue about that.
