### ISSUE TITLE
Slicing_syntax not equal with method as_slice().

### ISSUE THREAD

**Issue by amosbird** [rust-lang/rust#20429]
let a = &[1i, 2, 3][]  will compile while let a = &[1i, 2, 3].as_slice() will not.

**Comment by shepmaster** [comment]
Running that code [in the playpen](http://is.gd/icmI6N), both lines fail to compile with "borrowed value does not live long enough". Perhaps you narrowed down your example code too far?

**Comment by amosbird** [comment]
@shepmaster You should comment out one of these lines to see the result I get.

**Comment by shepmaster** [comment]
@amosbird Actually, now I see only the one error for my original link. Perhaps the playpen was updated between our two comments? Maybe this is a recent change (or maybe I'm just crazy...).

**Comment by kmcallister** [comment]
The result I get right now is that `let a = &[1, 2, 3][];` compiles and `let a = &[1, 2, 3].as_slice();` doesn't.

**Comment by Aatch** [comment]
Marking this a low-priority as the `as_slice` method is currently deprecated anyway.

**Comment by steveklabnik** [comment]
Both of these syntaxes aren't needed (we removed slicing syntax and .as_slice() is deprecated) so I'm closing as it's not really relevant. Thanks!
