### ISSUE TITLE
Nightly builds don't include documentation

### ISSUE THREAD

**Issue by jimblandy** [rust-lang/rust#20435]
The build I pulled from the URL below just now didn't include documentation:
https://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz

CC: @brson, @steveklabnik

**Comment by brson** [comment]
This is a transitionary step to solving https://github.com/rust-lang/rust/issues/14916. Docs are now part of a component called 'rust-docs' (you can download as e.g. 'rust-docs-nightly-x86_64-apple-darwin.tar.gz') and will be installable once https://github.com/rust-lang/rust/issues/16456 is finished, which should be in the next few days.

**Comment by brson** [comment]
IOW, once #16456 is finished the installer called 'rust' will both contain the docs and install them.

**Comment by jimblandy** [comment]
Great - thanks. Sorry for the dup.
