### ISSUE TITLE
Teach rustup.sh about release channels

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#20453]
Right now it just pulls down the nightly tarball directly, which it knows by name. To work with arbitrary release channels it needs to download the manifest (e.g. 'channel-rust-nightly') and pull the correct installer name from it. The artifacts will not always have predictable names, particularly on the stable channel. Add a '--channel=' flag to rustup.sh.

**Comment by brson** [comment]
I'll probably do this in the next few days along with the other work I'm doing on the installer.

**Comment by steveklabnik** [comment]
@brson did this get done? I forget.

**Comment by richo** [comment]
Are the mechanics for where to find the artifacts documented somewhere? Adding the flag is easy enough, I can finish this up if pointed to where the files live.

**Comment by caipre** [comment]
@steveklabnik Looks like this should be closed: https://github.com/rust-lang/rustup/blob/404d1429dbb6aa46daf92ebf268c24a93474e136/rustup.sh#L1321
