### ISSUE TITLE
Make compiletests (run-pass, compile-fail, etc) usable for testing arbitrary rust programs

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#20458]
Custom lints and syntax extensions would benefit from some in built support for testing.

**Comment by shepmaster** [comment]
If I understand this correctly, we would be able to write our own tests that ensure that a certain piece of code should not compile? If so, [I'm in favor](http://stackoverflow.com/questions/26664770/can-i-write-tests-for-invalid-lifetimes)!.

**Comment by brson** [comment]
I'm a little unclear on what's desired here. Is support for testing that compilation fails the primary thing?

Cargo can test standalone executables already. Would adding a 'compile-fail' mode to Cargo be sufficient, or is there really a need to distribute a standalone compiletest exe?

compiletest is super-crufty (it's some of the oldest rust code in existence!) and currently tailored very specifically to rustc's in-tree needs.

**Comment by shepmaster** [comment]
For my cases, something built into Cargo that says "this line should fail to compile with this error" would be more than sufficient. I don't want to claim that's what @Manishearth wants though :smile_cat:

**Comment by Manishearth** [comment]
Well, also the matching comments with warnings would be nice.


We could also redesign the compile tests to be more similar to the `#[test]` system and provide most of the functionality it used to.

**Comment by huonw** [comment]
Is this a dupe of https://github.com/rust-lang/rust/issues/12335?

**Comment by gnzlbg** [comment]
I think something like:

```rust
#[test]   // or #[compile_test]
#[should_not_compile(expected = "compiler error message/error type")]
fn compile_test() {}
```

would be very useful, if it is integrated with cargo.

**Comment by Manishearth** [comment]
dupe of #12335
