### ISSUE TITLE
Stop using first class aggregates

### ISSUE THREAD

**Issue by dotdash** [rust-lang/rust#20450]
For small structs/enums (size <= `uint`) we currently prefer to pass them as immediate values (good) but unlike clang we don't "cast" them to an appropriately sized integer type but pass them around as first class aggregates (not so good).

While LLVM supports the usage of FCAs, the optimizations largely depend on them being torn apart again, and that doesn't always work so great. The latest issue about that was #20149 for which I opted to patch LLVM to have it handle some basic store-to-load that involves FCA.

That led to the following email, in which Chandler Carruth suggests that we move away from using FCAs as much as possible: http://lists.cs.uiuc.edu/pipermail/llvm-commits/Week-of-Mon-20141229/250758.html

AFAICT this would leave us with two choices:
 * Make all type that end up as structs or arrays in LLVM IR non-immediate

or

 * Do as clang does and convert small structs to an appropriately sized integer type when using them as SSA values

(Some) Related tickets are #20149 #16506 #13927
Cc @alexcrichton @thestinger @eddyb @erickt @Aatch @luqmana

**Comment by alexcrichton** [comment]
This is some impressive investigation @dotdash, thanks for following up on this!

**Comment by Aatch** [comment]
Hmm, I think that doing as clang does and casting is probably the best solution. I'm not 100% on what that entails precisely, but assuming it leads to better codegen all around, I'm all for it. I'll take a look at what clang produces for relevant cases.

**Comment by Aatch** [comment]
While doing what Carruth suggests is probably a good idea anyway, he has now landed two patches related to this in LLVM now: [http://reviews.llvm.org/rL225061](rL225061) & [http://reviews.llvm.org/rL225074](rL225074). It will be interesting to see if they have an affect on our code.

**Comment by dotdash** [comment]
JFYI I'm working on eliminating the FCA loads/stores, as of 15 minutes ago, it's still ICE-ing in stage 2 though. Just to avoid duplicated efforts...
