### ISSUE TITLE
Bug on non-power-of-2 SIMD vectors

### ISSUE THREAD

**Issue by simnalamburt** [rust-lang/rust#20460]
I think I found a bug with non-power-of-2 SIMD vectors. They randomly turn into zero when I store them on `Vec`

http://is.gd/LfOHbj

```rust
#[simd]
#[deriving(Show)]
struct f32x3(f32, f32, f32);

fn main() {
    let mut points = Vec::new();

    for _ in 0i..10 {
        points.push(f32x3(1.0, 1.0, 1.0));
    }

    for point in points.iter() {
        println!("{}", point);
    }
}
```

Expected result:

```
f32x3(1, 1, 1)
f32x3(1, 1, 1)
f32x3(1, 1, 1)
f32x3(1, 1, 1)
f32x3(1, 1, 1)
f32x3(1, 1, 1)
f32x3(1, 1, 1)
f32x3(1, 1, 1)
f32x3(1, 1, 1)
f32x3(1, 1, 1)
```

What we get:

```
f32x3(1, 1, 1)
f32x3(1, 1, 1)
f32x3(1, 1, 1)
f32x3(0, 0, 0)
f32x3(1, 1, 1)
f32x3(1, 1, 1)
f32x3(0, 0, 0)
f32x3(0, 0, 0)
f32x3(1, 1, 1)
f32x3(1, 1, 1)
```

Tested with:

```
rustc 0.13.0-nightly (39d740266 2015-01-01 15:51:08 +0000)
host: x86_64-apple-darwin
```

```
rustc 0.13.0-nightly (39d740266 2015-01-01 15:51:08 +0000)
host: x86_64-unknown-linux-gnu (Ubuntu 14.04.1 LTS)
```

**Comment by lifthrasiir** [comment]
http://is.gd/wRJF3h

As you can see, this is a fault of `Vec` assuming `size_of::<T>() >= min_align_of::<T>()` (while for `T = f32x3` this is 12 and 16 respectively).

**Comment by Gankro** [comment]
Ack!

**Comment by Gankro** [comment]
CC @thestinger

**Comment by simnalamburt** [comment]
I've got through [some little experiment](http://is.gd/XqzspI) and I guess there's something wrong with `size_of::<T>()` for `f32x3` and other non-power-of-2 SIMD types.

```
                    | size_of | min_align_of | align_of | size_of >= min_align_of
--------------------+---------+--------------+----------+-------------------------
 f32x3              |      12 |           16 |       16 | false
 f32x3_no_c         |      12 |           16 |       16 | false
 f32x3_no_simd      |      12 |            4 |        8 | true

                    | size_of | min_align_of | align_of | size_of >= min_align_of
--------------------+---------+--------------+----------+-------------------------
 u8                 |       1 |            1 |        1 | true
 OneByte            |       1 |            1 |        8 | true
 u16                |       2 |            2 |        2 | true
 TwoByte            |       2 |            2 |        8 | true
 (u8, u16)          |       4 |            2 |        8 | true
 (u16, u8)          |       4 |            2 |        8 | true
 ThreeByte          |       4 |            2 |        8 | true
 (u32, u8)          |       8 |            4 |        8 | true
 FiveByte           |       8 |            4 |        8 | true
```

I think now we've got 2 available options.

1.  Make `size_of T >= min_align_of T` always true even for non-power-of-2 SIMD types like `f32x3`.
2.  Make `Vec<T>` function properly even for `size_of T < min_align_of T` situation.

I'm pretty new with Rust. Someone pleaes make advise!

**Comment by Aatch** [comment]
I'm not sure what the exact behaviour *should* be. Part of the problem is that non-power-of-two SIMD types don't exist on most platforms, so it gets widened to whatever it needs to be. However, an f32x3 is still only 12 bytes of actual data.

I think that Vec should handle the case anyway. Whether the case should come up... I don't really know.

**Comment by Diggsey** [comment]
Given that sizeof (f32x3, u32) == 32, it seems like rust already adds padding for SIMD types, so it's simply size_of that's broken, and should include the padding.

At the same time, Vec<T> should probably assert that size_of T >= min_align_of T to catch any errors if in the future there are any types where their size is less than their alignment.

**Comment by Gankro** [comment]
Nominating because the required change may be a back-compat change to some primitive semantics.

**Comment by Aatch** [comment]
Actually, thinking about it some more. I believe that the current behaviour is correct. `size_of` doesn't account for padding, because padding is situation-dependent: `(i8, u64)` has 7 bytes of padding after the `i8`, but that doesn't stop `i8` from being 1 byte in size. Just because the type gets padding, doesn't mean it needs to change size.

The whole point of having a different alignment to size is to cover these kinds of cases, where the number of usable bytes is not a nice integer multiple of the alignment.

**Comment by Diggsey** [comment]
@Aatch In that situation, the extra padding is added to meet the alignment requirements of "u64", not the "i8". In the SIMD example, the extra padding is part of the SIMD type.
ie. for (f32x3, u32) there are 4 bytes of padding between the fields, even though u32 only requires alignment to 4 bytes.

Either the compiler should not add any padding and sizeof (f32x3, u32) == 16, and any accesses take care to preserve the u32 (which is certainly possible to do efficiently with SIMD) or as is more usual, the SIMD type should include it's padding.

**Comment by Diggsey** [comment]
Amusingly, `struct Test(f32x3);` has a size of 16, whereas f32x3 on it's own has a size of 12, which really shouldn't happen.

The issue is caused by size_of being implemented as a call to this function:
https://github.com/rust-lang/rust/blob/618bd5d1c550cbdaac369b01716cc009b9e4d1e7/src/librustc_trans/trans/machine.rs#L52

The comment above the function is wrong: LLVM does include padding when calculating the size of types, but only for structs (not for vectorised types), which makes that function fairly useless and definitely not the preferred option as the comment suggests. `llsize_of` should be preferred instead which always includes padding, so is at least consistent.

**Comment by huonw** [comment]
>  Nominating because the required change may be a back-compat change to some primitive semantics.


NB. `#[simd]` and `std::simd` are experimental and are highly unlikely to be stable at 1.0.

**Comment by simnalamburt** [comment]
Current `librustc` works like below:

```rust
size_of::<T>() = ceil(LLVMSizeOfTypeInBits() / 8)
min_align_of::<T>() = LLVMABIAlignmentOfType()
```

and I found that current LLVM doesn't have any guarantee between `LLVMSizeOfTypeInBits` and `LLVMABIAlignmentOfType`

For example, `LLVMSizeOfTypeInBits` and `LLVMABIAlignmentOfType` of 80-bit floating point format is `80` and `16`. I know that Rust doesn't have `f80` but if it does, `size_of::<f80>()` will be `10` and `min_align_of::<f80>()` will be `16`. Which means `Vec<f80>` would have same problem.

Now I see 2 options here

1. Make `size_of::<T>()` call `llsize_of`, not `llsize_of_real` (as @Diggsey said)
2. Make `Vec<T>` function properly even for size\_of T < min\_align\_of T situation.

###### References

- [size_of::\<T>()][1] → [llsize_of_real()][2] → [LLVMSizeOfTypeInBits()][3] → [llvm::DataLayout::getTypeSizeInBits()][4]

- [min_align_of::\<T>()][5] → align\_of() → [llalign_of_min()][6] → [LLVMABIAlignmentOfType()][7] → [llvm::DataLayout::getABITypeAlignment()][8] → [llvm::DataLayout::getAlignment()][9] → [llvm::DataLayout::getAlignmentInfo()][0]

[1]: https://github.com/rust-lang/rust/blob/master/src/librustc_trans/trans/intrinsic.rs#L311-L315
[2]: https://github.com/rust-lang/rust/blob/master/src/librustc_trans/trans/machine.rs#L52-L62
[3]: http://llvm.org/docs/doxygen/html/group__LLVMCTarget.html#gaa29cd97b498d32b9c5663574bd2659d7
[4]: https://github.com/rust-lang/llvm/blob/ec1fdb3b9d3b1fb9e1dae97a65dd3a13db9bfb23/include/llvm/IR/DataLayout.h#L521
[5]: https://github.com/rust-lang/rust/blob/master/src/librustc_trans/trans/intrinsic.rs#L316-L319
[6]: https://github.com/rust-lang/rust/blob/master/src/librustc_trans/trans/machine.rs#L107-L111
[7]: http://llvm.org/docs/doxygen/html/group__LLVMCTarget.html#ga474ae58c596b5cb5c197a3f540479135
[8]: https://github.com/rust-lang/llvm/blob/ec1fdb3b9d3b1fb9e1dae97a65dd3a13db9bfb23/lib/IR/DataLayout.cpp#L687-L689
[9]: https://github.com/rust-lang/llvm/blob/ec1fdb3b9d3b1fb9e1dae97a65dd3a13db9bfb23/lib/IR/DataLayout.cpp#L633
[0]: https://github.com/rust-lang/llvm/blob/ec1fdb3b9d3b1fb9e1dae97a65dd3a13db9bfb23/lib/IR/DataLayout.cpp#L414

**Comment by Gankro** [comment]
@huonw I meant more-so the size_of semantics, but simd semantics might also be affected.

**Comment by thestinger** [comment]
I think this is a compiler bug. There are many low-level APIs assuming that size is a multiple of the alignment...

**Comment by thestinger** [comment]
For example, C11's `aligned_alloc` function requires that `size` is a multiple of the `alignment` parameter. It's expected that the compiler will always output sane values for both (unlike `rustc` :P) so it is a sensible limitation.

**Comment by gereeter** [comment]
Unfortunately, forcing `size_of` to return a multiple of `min_align_of` would make #17027 impossible, which seems like a big missed opportunity. Perhaps there should be a `padded_size_of` function that just rounds `size_of` to the next multiple of `min_align_of`?

**Comment by Diggsey** [comment]
@greeter
You could have both size_of and padded_size_of, but for the moment, they'd both have to include padding because for struct types LLVM provides no way to get the size without padding, and for vectorised types, even size_of should include padding as #17027 can't be applied to vectorised types without masking every load/store to avoid overwriting the u32 in (f32x3, u32).

**Comment by simnalamburt** [comment]
Currently I'm testing https://github.com/simnalamburt/rust/commit/a93c1f6d032abff7a7ba2ce750326fc16eed0ca5, and it seems to cause no trouble. Please make me an advise if I'm doing something wrong.

**Comment by simnalamburt** [comment]
OK Let's do this → https://github.com/rust-lang/rust/pull/20611
