### ISSUE TITLE
fn pointer type is not Clone when containing a parameter with an unspecified lifetime

### ISSUE THREAD

**Issue by samfoo** [rust-lang/rust#20468]
The following snippet fails to compile.

``` rust
#[deriving(Clone)]
enum Thing {
    Func(fn(&str) -> String)
}

#[allow(unused_variables)]
fn a(b: &str) -> String {
    "a".to_string()
}

#[allow(unused_variables)]
fn main() {
    let f = Thing::Func(a);

    println!("Good to go!");
}
```

Yielding the error...

``` shell
<anon>:3:10: 3:28 error: the trait `core::clone::Clone` is not implemented for the type `fn(&str) -> collections::string::String`
<anon>:3     Func(fn(&str) -> String)
                  ^~~~~~~~~~~~~~~~~~
note: in expansion of #[deriving]
<anon>:1:1: 1:19 note: expansion site
```

However, it works when the argument reference is given a lifetime specifier (as below).

``` rust
#[deriving(Clone)]
enum Thing {
    Func(fn(&'static str) -> String)
}

#[allow(unused_variables)]
fn a(b: &'static str) -> String {
    "a".to_string()
}

#[allow(unused_variables)]
fn main() {
    let f = Thing::Func(a);

    println!("Good to go!");
}
```

```
Good to go!
```

Structs/enums cloneability should not rely on the lifetime of a bare function's arguments, since the argument's lifetime is relative to the function, not the struct.

Compiler version details:

``` shell
$ rustc --version --verbose
rustc 0.13.0-nightly (10d99a973 2014-12-31 21:01:42 +0000)
binary: rustc
commit-hash: 10d99a973498c5a1be6ba318210751efc1c2cf61
commit-date: 2014-12-31 21:01:42 +0000
host: x86_64-apple-darwin
release: 0.13.0-nightly
```

**Comment by fengsp** [comment]
I have got the same error, is this a bug or what? I just can not clone any function that takes a reference.

**Comment by gaudecker** [comment]
I ran into the same error.

**Comment by blaenk** [comment]
Note that if you contain types in the fn signature that are from your own crate, you can provide an explicit implementation yourself as a workaround. That doesn't solve this in the general case though, such as in the example in the first post, since neither &str nor String are from your own crate.

**Comment by steveklabnik** [comment]
Traige: new code:

```
#[derive(Clone)]
enum Thing {
    Func(fn(&str) -> String)
}

#[allow(unused_variables)]
fn a(b: &str) -> String {
    "a".to_string()
}

#[allow(unused_variables)]
fn main() {
    let f = Thing::Func(a);

    println!("Good to go!");
}
```

**Comment by nikomatsakis** [comment]
Fixed now, thanks to @scalexm's PR for https://github.com/rust-lang/rust/issues/44490. I believe there exist enough tests, so just going to close.
