### ISSUE TITLE
New orphan check makes it impossible to implement Hash<S>

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#20477]
```rust
#![feature(default_type_params)]
use std::hash::{self, Hash};

struct Foo;

impl<S> Hash<S> for Foo where S: hash::Writer {
    fn hash(&self, _: &mut S) {
    }
}

fn main() {}
```

```
test.rs:6:1: 9:2 error: type parameter `S` must also appear as a type parameter of some type defined within this crate
test.rs:6 impl<S> Hash<S> for Foo where S: hash::Writer {
test.rs:7     fn hash(&self, _: &mut S) {
test.rs:8     }
test.rs:9 }
test.rs:6:1: 9:2 note: for a limited time, you can add `#![feature(old_orphan_check)]` to your crate to disable this rule
test.rs:6 impl<S> Hash<S> for Foo where S: hash::Writer {
test.rs:7     fn hash(&self, _: &mut S) {
test.rs:8     }
test.rs:9 }
error: aborting due to previous error
```

**Comment by sfackler** [comment]
cc @nikomatsakis

**Comment by sfackler** [comment]
It also blocks things like implementations of Index where the key type is generic over `BorrowFrom` for the same reason: https://github.com/sfackler/rust-phf/blob/master/phf/src/map.rs#L57-L61

**Comment by sfackler** [comment]
It also appears to be impossible to implement `Encodable`:

```rust
/Users/sfackler/rust/uuid/src/lib.rs:480:1: 485:2 error: type parameter `T` must also appear as a type parameter of some type defined within this crate
/Users/sfackler/rust/uuid/src/lib.rs:480 impl<T: Encoder<E>, E> Encodable<T, E> for Uuid {
/Users/sfackler/rust/uuid/src/lib.rs:481     /// Encode a UUID as a hyphenated string
/Users/sfackler/rust/uuid/src/lib.rs:482     fn encode(&self, e: &mut T) -> Result<(), E> {
/Users/sfackler/rust/uuid/src/lib.rs:483         e.emit_str(self.to_hyphenated_string().as_slice())
/Users/sfackler/rust/uuid/src/lib.rs:484     }
/Users/sfackler/rust/uuid/src/lib.rs:485 }
```

**Comment by pfalabella** [comment]
the temporary impossibility to implement Hash is mentioned in the commit message: https://github.com/nikomatsakis/rust/commit/c61a0092bc236c4be4cb691fcd50ff50e91ab0d6

It says to disable the new orphan check for now, with `#![feature(old_orphan_check)]`

**Comment by reem** [comment]
Also can't write impls like:

```rust
impl<E: Error> FromError<E> for Box<Error> {
    fn from_error(e: E) -> Box<Error> {
        box e 
    } 
}
```

which is a significant ergonomics hit for the use of `try!`.

**Comment by huonw** [comment]
@reem, what is `Error` there? A trait local to that crate?

**Comment by reem** [comment]
Ah, sorry. Yes, `Error` is defined in that crate, but `FromError` is not.

**Comment by daboross** [comment]
One other error-related thing that I've found I can't do with this, though I'm not sure that there isn't another way to do it.

Something like:
```rust
impl <T> error::FromError<sync::PoisonError<T>> for InitializationError {
    fn from_error(error: sync::PoisonError<T>) -> InitializationError {
        InitializationError::Other(format!("{}",error))
    }
}
```
Where `InitializationError::Other` is just an enum state which takes a `String`. I'd like to implement `FromError` for a `PoisonError` of any type, though this doesn't currently seem possible.

**Comment by diwic** [comment]
I wanted the simplest possible way to use `try!` so here's what I did - worked until today. Not sure how to fix it, or if it is a bug in the compiler - when looking at the [relevant commit](https://github.com/nikomatsakis/rust/commit/6e68fd09edc7ed37fd76f703247b5410cd338bfe), my code seems to follow this template, so should have been okay:

    - `impl<T> Foo<T> for LocalType` -- T does not appear in Self, so it is OK

Here's the code:

    struct MyError(String);
    
    impl<T: std::fmt::Show> std::error::FromError<T> for MyError {
        fn from_error(err: T) -> MyError {
            MyError(format!("{}", err))
        }
    }

**Comment by steveklabnik** [comment]
Triage: I think this issue is basically out of date today, no? as mentioned in https://github.com/rust-lang/rust/issues/20477#issuecomment-68611853

**Comment by aturon** [comment]
Closing. This was addressed with the [covered first rule](http://smallcultfollowing.com/babysteps/blog/2015/01/14/little-orphan-impls/).
