### ISSUE TITLE
std::rand::weak_rng should return a newtype struct

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#20484]
`std::rand::weak_rng` should either be removed or return a newtype struct.

The documentation for the fuction claims:

> It returns the fastest Rng algorithm currently available in Rust

However current return type, namely `XorShiftRng` does not account for a possibility of new, faster Rng algorithms being added to the standard library. In case a faster algorithm is added it would be a breaking change to change the return type.

This is something you want to consider for std::rand stabilisation (rand stabilization (search hint)).

**Comment by huonw** [comment]
I think it also makes sense to just remove this function completely.

**Comment by nagisa** [comment]
This issue is not relevant anymore since rust has been moved out to a crate.
