### ISSUE TITLE
TypeId should be available for T: ?Sized

### ISSUE THREAD

**Issue by reem** [rust-lang/rust#20492]
`TypeId::of` requires it's parameter to be Sized, but I see no reason for this.

**Comment by Marwes** [comment]
Any work on fixing this? It seems like the impl for Any only misses the ?Sized bound but adding ?Sized to `impl<T> Any for T where T: Reflect + 'static` causes the compiler to ICE (coherence error) in `impl Any  { ... }`.

**Comment by reem** [comment]
`TypeId::of` now supports `?Sized` `T`.
