### ISSUE TITLE
`raw_pointer_deriving` lint name should be `raw_pointer_derive`

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#20498]
Due to the `#[deriving]` -> `#[derive]` switch.

Relevant bits of code:

- https://github.com/rust-lang/rust/blob/496dc4eae7de9d14cd49511a9acfbf5f11ae6c3f/src/librustc/lint/builtin.rs#L552-L620 for the actual code
- https://github.com/rust-lang/rust/blob/496dc4eae7de9d14cd49511a9acfbf5f11ae6c3f/src/librustc/lint/context.rs#L226 should have this renaming added

**Comment by csouth3** [comment]
Looks easy enough.  I could take care of this if you would like/are not doing it already.
