### ISSUE TITLE
Remove default Sized bound on trait Self param

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#20497]
Tracking https://github.com/rust-lang/rfcs/pull/546

**Comment by nikomatsakis** [comment]
Implemented in https://github.com/rust-lang/rust/pull/20341

**Comment by neon64** [comment]
The RFC talks about how 'fallout' within the standard library is minimal, but doesn't provide any information about how we are supposed to update our own code to make it work. I know that at the moment it is only a warning but in the future it will become an error so I think its important to tell people.

The RFC seems to suggest that writing `trait Foo for ?Sized { ... }` is possible but under `rustc 1.4.0-nightly (e822a18ae 2015-08-16)` that won't compile.

Would you please be able to detail how users can convert existing code?

My extremely simplified example shows the issue: http://is.gd/1gPnQP

Thanks very much if you could help with this.
