### ISSUE TITLE
`T: ?Sized` does not work in `where` clauses

### ISSUE THREAD

**Issue by P1start** [rust-lang/rust#20503]
``` rust
fn foo<T>(x: &T) where T: ?Sized {} // error: unexpected `?`
```

[The RFC states](https://github.com/rust-lang/rfcs/blob/master/text/0490-dst-syntax.md#detailed-design) that the syntax should work in `where` clauses.

**Comment by nick29581** [comment]
Note that we don't currently accept `where Sized? T`, so there is no backwards compatibility hazard here. Although we should certainly fix this, it doesn't need to be done for 1.0 (it probably should be though).

**Comment by jroesch** [comment]
@nick29581 I will poke into this.

**Comment by P1start** [comment]
There are a few edge cases here. In particular, specifying `?Sized` in a `where` clause should probably only be allowed at the type parameter’s definition site; e.g., the following probably shouldn’t be allowed:

```rust
impl<T> Foo<T> {
    fn foo(&self) where T: ?Sized { ... }
}
```

Although allowing that could potentially be useful, I suspect it would complicate the implementation and be slightly unclear anyway.

Additionally, specifying `?Sized` on an associated type is unnecessary. In general, specifying `?Sized` on anything that isn’t a type parameter is somewhat nonsensical: `where Option<T>: ?Sized` doesn’t really make much sense either.

**Comment by aochagavia** [comment]
What needs to be done in order to get this working? Is it a purely parsing issue?

**Comment by Gankro** [comment]
Triage: still a really annoying problem.

**Comment by jroesch** [comment]
@Gankro I can fix this, probably my fault anyways.

**Comment by kamalmarhubi** [comment]
This is still a bit of a wart, and tripped me up the first time I wanted to use a `?Sized` bound.

**Comment by ihrwein** [comment]
I hit this issue today.

**Comment by kamalmarhubi** [comment]
@jroesch although it was a few months ago, do you remember enough context to write a very quick summary of where changes would need to be made to fix this?

**Comment by tinyplasticgreyknight** [comment]
Just ran into this today.  Is it just a parsing problem?

**Comment by jonas-schievink** [comment]
IIRC this also needs to be handled in astconv

**Comment by jonas-schievink** [comment]
[`add_unsized_bound`](https://github.com/rust-lang/rust/blob/12b6345bc2d0cc02d81bc712682b3c77346acc15/src/librustc_typeck/collect.rs#L1692) would have to take the where-clause of the item into account, but I think the where-clause isn't available there.

**Comment by hannni** [comment]
There at least should be some better error message telling one to put ?Sized into the definition instead of the where clause.

**Comment by matthieu-m** [comment]
This is really a **papercut** issue.

While when I hit I generally remember "Oh yeah, this bug again" and promptly fixes it, it still would be a much smoother experience if I did not have to.

**Comment by petrochenkov** [comment]
I tried to fix this but have immediately drowned in philosophical questions.

`?Sized` at the moment is not a true bound, but a command - "do not implicitly add `Sized` bound".
I.e.
```
fn f<FreshParameter: ?Sized + OtherBounds1>() where ExistingType: OtherBounds2 { ... }
```
is desugared into 
```
// `Sized` bound is not implicitly added
fn f<FreshParameter: OtherBounds1>() where ExistingType: OtherBounds2 { ... }
```
and
```
fn f<FreshParameter: OtherBounds1>() where ExistingType: OtherBounds2 { ... }
```
is desugared into 
```
`Sized` bound is implicitly added
fn f<FreshParameter: Sized + OtherBounds1>() where ExistingType: OtherBounds2 { ... }
```

A few conclusions from this:
- `where` clauses don't implicitly add `Sized` bounds so the command `?Sized` don't do anything on them
- `?Sized` makes sense only when we define some new entity (like type parameter introduction or associated type definition do) and don't make sense when we require some bounds from an already existing entity.

So, how I think the fix should look:
- `TYPE: ?Trait` bounds from where clauses are internally moved on parameter definitions if and only if `TYPE` is a bare type parameter defined in the current item.
- if `TYPE` is a type parameter from one of parent items or any other arbitrary type, then error is reported.
- `where (FreshParameter): ?Sized` is a questionable case. I'd classify it as "any other arbitrary type" and report an error, but the information about parens is lost in HIR.

---

Other stuff:

1. It's not just parsing issue.

2. @matthieu-m 
    >it is not supported in a trait bounds either (eg: `trait X: ?Sized` does not work).

    traits are `?Sized` by default, so `trait X: ?Sized` doesn't make much sense. It's matter of a better error message (and the error should certainly not be reported in the parser, like now).
