### ISSUE TITLE
emacs auto-complete should be enabled by default

### ISSUE THREAD

**Issue by pcn** [rust-lang/rust#20509]
Even without specialized support for e.g. names in crates, enabling auto-complete in rust-mode should be on by default to some extent.  

I'm not a guru, but I think that there are two approaches.  

1. Either auto-complete can be active by default (where it will pop-up completions as you type) 
2. or, if that's not preferred, auto-complete functionality should be bound to some fairly common key ("Tab", or "M-/" are the most common choices from what I'm aware of) that enables completion when the cursor is in the middle of some typed text (e.g. http://cx4a.org/software/auto-complete/manual.html#Trigger_Key).

For more advanced completion stuff, is there a canonical set of places that could be searched for symbols to be completed?  I searched and found this: http://www.reddit.com/r/rust/comments/1xfjo7/ide_support/.  Is there a plan for this kind of support?

**Comment by pcn** [comment]
In irc JP-Ellis pointed out https://github.com/phildawes/racer

**Comment by nick29581** [comment]
For more on IDE plans and tooling in general, see https://gist.github.com/nick29581/a3bbf6dd1b14ce57f18c

**Comment by steveklabnik** [comment]
Moved to rust-lang/rust-mode#14
