### ISSUE TITLE
Remove the implicit binder from the FnSpace in VecPerParamSpace

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#20526]
Right now there are two region binders in `ty_fold`: `Binder<T>`, and the `FnSpace` in `VecPerParamSpace`. There should be only one: `Binder<T>`. In fact, because of the early/late system, late-bound regions from a method or what have you cannot appear in the `FnSpace` predicates, but we keep this extra binding level because of the way that `resolve_lifetime` is structured. We should remove it.

**Comment by steveklabnik** [comment]
Triage: looks like https://github.com/rust-lang/rust/pull/29463 is stuck in review, but should fix this.
