### ISSUE TITLE
from_str producing an unresolved name error

### ISSUE THREAD

**Issue by davidenglishmusic** [rust-lang/rust#20525]
I am using the following code to get an integer from a string:

    fn main() {
      let number: Option<uint> = from_str("5");
    }

In compiling, it generates the following:

test2.rs:2:30: 2:38 error: unresolved name `from_str`
test2.rs:2   let number: Option<uint> = from_str("5");
                                        ^~~~~~~~
error: aborting due to previous error

System information:
OS X 10.10.1
rustc 0.13.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-apple-darwin
release: 0.13.0-dev

Rust was installed on the eve of January 3, 2015 using brew install rust --HEAD

**Comment by jfager** [comment]
Not a bug; the FromStr trait was removed from the prelude recently, just add `use std::from_str::FromStr;` to get it back.

**Comment by steveklabnik** [comment]
That's correct. Also, parse is the preferred method instead.

**Comment by GildedHonour** [comment]
@steveklabnik , is what "parse"?

**Comment by thomasbratt** [comment]
@GildedHonour  As of 1.0 you can use this syntax:

`let value = temp.parse::<u32>();`

**Comment by steveklabnik** [comment]
@GildedHonour whoops! Sorry I missed this. @thomasbratt is correct.

**Comment by steveklabnik** [comment]
You can also `let value: u32 = temp.parse()`.
