### ISSUE TITLE
Clarify what #![no_std] is useful for

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#20537]
I’ve initially made rust-wtf8 use `#![no_std]` out of the theoretical concern that potential users (maybe html5ever) would want `#![no_std]` as well. (And because it wasn’t hard.)

But now that [the runtime was removed](https://github.com/rust-lang/rust/pull/18967), what are the real benefits of using `#![no_std]`? The html5ever source has a "This helps us make a C-friendly library." comment. @kmc, how does it help?

**Comment by kmcallister** [comment]
servo/html5ever#63 proposes to drop `#![no_std]`.  I don't think there's any need now that the runtime has been removed.

**Comment by sfackler** [comment]
I think it's still useful for libraries that want to work in environments where `std` won't work, like a kernel. It doesn't seem like `rust-wtf8` is one of those libraries, though.

**Comment by SimonSapin** [comment]
What makes std not work in a kernel?

**Comment by sfackler** [comment]
`std::thread`, `std::io::stdio`, `std::sync` minus `std::sync::atomics` at the very least.

**Comment by sfackler** [comment]
You'd probably want to avoid `box` and anything that allocates as well, since killing the entire system if the kernel runs out of memory may not be the right strategy.

**Comment by SimonSapin** [comment]
Is merely linking against libstd problematic, if these modules are not used?

**Comment by sfackler** [comment]
I think so, since you'd probably end up pulling in a dynamic dependency on glibc.

**Comment by kmcallister** [comment]
This is basically a doc bug. cc @steveklabnik

**Comment by steveklabnik** [comment]
I'm moving this thread to https://github.com/rust-lang/rfcs/issues/1005, given that it's an unstable feature.
