### ISSUE TITLE
Lifetime Markers do not exhibit proper variance used certain ways

### ISSUE THREAD

**Issue by Ericson2314** [rust-lang/rust#20533]
See http://is.gd/KdHumF . Only the third block triggers the borrow error, when presumably all three should.

**Comment by kmcallister** [comment]
Nominating.

**Comment by nikomatsakis** [comment]
Hmm, on my variance branch, I get 3 errors.

**Comment by nikomatsakis** [comment]
But on master I do not. Not sure what bug I fixed there :P
