### ISSUE TITLE
Constraints on nested associated types do not work

### ISSUE THREAD

**Issue by carllerche** [rust-lang/rust#20543]
```rust
#![feature(associated_types)]
 
pub trait Foo {
    type T;
}
 
pub trait Bar {
    type F: Foo;
}
 
pub fn stuff<B: Bar<F::T=()>>(b: B) {
}
 
pub fn main() {
}
```

**Comment by jroesch** [comment]
I played with a variation on this to see if the actual constraint checking is possible but it looks like this doesn't work either:
```
#![feature(associated_types)]

pub trait Foo {
    type T;
}

pub trait Bar {
    type F: Foo;
}

trait TyEq<A> {}
impl<A> TyEq<A> for A {}

pub fn stuff<B: Bar>(b: B) where B::F::T : TyEq<()> {
}

pub fn main() {
}
```

This works though:
```
#![feature(associated_types)]

pub trait Foo {
    type T;
}

pub trait Bar {
    type F: Foo;
}

pub trait TyEq<A> {}
impl<A> TyEq<A> for A {}

pub fn stuff<B: Bar>(b: B) where <B::F as Foo>::T : TyEq<()> {
}

pub fn main() {
}
```

At first glance it appears to be a parsing bug to me, gonna spend a few minutes seeing if I can chase it down.

**Comment by nikomatsakis** [comment]
This isn't really expected to work yet. You can typically introduce a new type variable to work around it.

**Comment by nikomatsakis** [comment]
Semi-dup of #20666

**Comment by nick29581** [comment]
Parse error, for reference:
```
foo.rs:11:25: 11:26 Fatal: expected one of `(`, `+`, `,`, `::`, or `>`, found `=`
foo.rs:11 pub fn stuff<B: Bar<F::T=()>>(b: B) {
```

**Comment by nikomatsakis** [comment]
So it's not clear that this particular syntax (`Foo<X::Y=...>`) is desired. Since the semantic problems with nested associated types are covered in #20666, we're going to close this issue as a dup for now.
