### ISSUE TITLE
Make lang items usable from libsyntax

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#20541]
Currently lang items are only available in the compiler proper, not in libsyntax. However, it is often useful to be able to use lang items for desugaring (see #20516, also range syntax which had to happen in the compiler rather than have a simple desugaring).

The solution I think, is to move the lang items code out of librustc and into libsyntax (or some other, new crate). However, lang items are based on def ids, and these do not exist as far as libsyntax is concerned (they are allocated in an early pass by librustc). Therefore to make this work, we have to change lang items to not use def ids, some how.

**Comment by steveklabnik** [comment]
Triage: one year later, as far as I know, lang items are still in `rustc_middle`.

**Comment by steveklabnik** [comment]
Triage: same as in 2016.

**Comment by bjorn3** [comment]
Fixed by https://github.com/rust-lang/rust/pull/75145
