### ISSUE TITLE
Tracking issue for Consistent no-prelude attribute (RFC 501)

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#20561]
https://github.com/rust-lang/rfcs/pull/501

**Comment by aturon** [comment]
cc @Kimundi

**Comment by bombless** [comment]
I think in theory primitive type definitions come from `std::*`.
So if `no_std` or `no_prelude` is on there should not been primitive type definitions.
And I suggest we make alias of primitive types to a place like `std::primitive_definition::*`, so we write codes below to perform as `no_std` today:
```rust
#![no_std]
use std::primitive_definition::*
```

I know this change sounds trivial but current behavior is pretty ugly, see https://github.com/rust-lang/rust/pull/22093
cc @mahkoh

**Comment by steveklabnik** [comment]
Triage: so. This RFC happened pre-1.0, yet never landed. And it seems `no_implicit_prelude` does work on stable today. So, this would have to not be a re-naming, but a deprecation + new name?

**Comment by Kimundi** [comment]
Seems there has been a patch to implement this early this year, but it bitrottet: https://github.com/rust-lang/rust/pull/32025

**Comment by pnkfelix** [comment]
@rustbot label +S-tracking-design-concerns

As noted by @petrochenkov [here](https://github.com/rust-lang/rust/pull/80427#issuecomment-752909280) and @oli-obk [here](https://github.com/rust-lang/rust/pull/80427#issuecomment-757912783), its not clear if this change is still well-motivated.

**Comment by pnkfelix** [comment]
I propose we close this until someone who can drive it comes forward and can motivate doing this at this point.

@rfcbot fcp close

**Comment by lcnr** [comment]
> I propose we close this until someone who can drive it comes forward and can motivate doing this at this point.
