### ISSUE TITLE
Implement branch prediction intrinsics

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#20579]
Branch prediction intrinsic equivalent to GCC’s `__builtin_expect` should exist. Alternatively two intrinsics `likely` and `unlikely` could be implemented.

**Comment by nagisa** [comment]
Appears to correspond to [`llvm.expect`](http://llvm.org/docs/LangRef.html#llvm-expect-intrinsic) intrinsic.

**Comment by jdm** [comment]
See #17317.

**Comment by alexcrichton** [comment]
cc @steveklabnik, could this move to the rust-lang/rfcs repo? (feature request)
