### ISSUE TITLE
`unreachable_code` lint doesn't work with unboxed closures

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#20574]
This compiles, but it shouldn't

``` rust
#![deny(unreachable_code)]

fn main() {
    let uc = |&:| panic!();
    uc();
    println!("unreachable");
}
```

This is correctly rejected

``` rust
#![deny(unreachable_code)]

fn main() {
    let bc = || -> ! panic!();
    bc();
    println!("unreachable");
}
```

version: `rustc 0.13.0-nightly (c6c786671 2015-01-04 00:50:59 +0000)`

**Comment by huonw** [comment]
AFAICT, it seems that the first closure is defaulting to have return type `()`; since `!` isn't a real type, it requires explicit annotation for the compiler to believe that you want it.

(Maybe that's the bug?)

**Comment by reem** [comment]
I think it would be quite interesting for `!` to be a "real" type. There are certain patterns that could be made more usable, such as consuming a thread to run an event loop, for instance.

**Comment by reem** [comment]
@japaric what happens if you explicitly annotate the return type of the unboxed closure to be `!`?

**Comment by japaric** [comment]
@reem 

``` rust
let uc = |&:| -> ! panic!();
uc();
```

ICEs with `internal error: entered unreachable code`

**Comment by reem** [comment]
Well, that's unfortunate. It's apparently illegal to use `!` as a type parameter for traits:

```rust
pub trait X<T> {}
pub struct Foo;
impl X<!> for Foo {}

fn main() {}
```

errors with `expected type, found !`, which likely explains why the unboxed closure expansion breaks. These all seem to just be symptoms of `!` not being a proper type when it should be.

**Comment by steveklabnik** [comment]
Triage: updated code:

```
#![deny(unreachable_code)]

fn main() {
    let uc = || panic!();
    uc();
    println!("unreachable");
}
```

and

```
#![deny(unreachable_code)]

fn main() {
    let uc = || -> ! { panic!() };
    uc();
    println!("unreachable");
}
```

The former still compiles, while the latter doesn't.

> AFAICT, it seems that the first closure is defaulting to have return type (); since ! isn't a real type, it requires explicit annotation for the compiler to believe that you want it.

This would seem to be the case. @rust-lang/lang , what are the semantics we want here?

**Comment by nikomatsakis** [comment]
We no longer support closures with `-> !` return type, so I think the lint just can't handle this case anymore (and I'm ok with that).

**Comment by pnkfelix** [comment]
(see also #14973 and https://github.com/rust-lang/rfcs/issues/1001 for related discussion of whether one would want `!` to be a first-class type of its own, and why/why not)

**Comment by steveklabnik** [comment]
Sounds good to me, thanks!

**Comment by Phlosioneer** [comment]
Should this be re-opened @nikomatsakis ? The type system can now handle `!` as a proper type, so the closure should get the `!` return type correctly now, and the lint should be able to handle that... We still have an ignored test about it: https://github.com/rust-lang/rust/blob/b1363a73ede57ae595f3a1be2bb75d308ba4f7f6/src/test/compile-fail/dead-code-closure-bang.rs#L13-L19
