### ISSUE TITLE
make: *** [x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/stamp.rustc] Error 137

### ISSUE THREAD

**Issue by sleigner** [rust-lang/rust#20577]
I got this error while compiling Nightly build (Jan 4, 2014) of Rust (x64) in Ubuntu 14.04 LTS. Here are my commands:

```
$./configure --prefix=~/local/
$make
```
(... make running for a while, then got this)

``` 
rustc: x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm
rustc: x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_back
rustc: x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc
Killed
make: *** [x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/stamp.rustc] Error 137
```

Has anyone seen this error before? Thanks!

**Comment by huonw** [comment]
How much memory does your computer have? Rust can unfortunately take 2GB (or more) to do the full bootstrap.

**Comment by sleigner** [comment]
Ahh, yes.... the machine I think has exactly 2GB and I am pretty sure the memory allocated for Rust bootstrap is less than that. I will try on the more powerful machine. Thanks for the reply!
