### ISSUE TITLE
Perhaps make orphan rules more permissive of associated types?

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#20590]
For now I'm treating associated types just like type parameters in coherence. I've given this approximately zero thought, it just seems like the conservative course, and we can always reverse it. For now it's largely a moot point since associated type references within impls don't work anyhow. Search the code for a FIXME.

**Comment by nikomatsakis** [comment]
Updated title to make it clear that this would be an extension and hence is not a particular priority right now, especially absent a convincing use case.

**Comment by lfairy** [comment]
#20400 looks like a special case of this bug.

**Comment by nikomatsakis** [comment]
Actually I think #20400 is a separate thing -- that's more about the other half of coherence, the overlap check.

**Comment by steveklabnik** [comment]
Triage: would this be an RFC now? Post 1.0, a change like this feels pretty big.

**Comment by nikomatsakis** [comment]
It's probably not as big as it sounds. Still I think we are probably doing the right thing here and afaik being conservative is causing us no problems. I'm just going to close the issue.
