### ISSUE TITLE
Remove some of the older obsolete syntax things

### ISSUE THREAD

**Issue by nick29581** [rust-lang/rust#20599]
They clutter up the parser and are confusing for new users. We should remove obsolete syntax once it is no longer useful. We should audit these during the beta period.

**Comment by sfackler** [comment]
We might just want to remove all obsolete syntax for 1.0.

**Comment by nick29581** [comment]
I would not be opposed to that

**Comment by aochagavia** [comment]
Would it be possible to make a list of things that need to be removed (e.g. enum variants, functions, etc)? That way it would be easier for others (like me) to help.

**Comment by nick29581** [comment]
I'm talking in particular about the things in https://github.com/rust-lang/rust/blob/master/src/libsyntax/parse/obsolete.rs I.e., syntax which has been removed, but still gives specific obsolete errors, rather than generic syntax errors.
