### ISSUE TITLE
Tracking issue for Prohibit unused type parameters in impls (RFC 447)

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#20598]
https://github.com/rust-lang/rfcs/pull/447

**Comment by nick29581** [comment]
Nominating for backcompat-lang

**Comment by nikomatsakis** [comment]
Almost but not entirely fixed with https://github.com/rust-lang/rust/pull/20593

**Comment by nikomatsakis** [comment]
Only thing left to do is to remove the "opt-out" provisions

**Comment by nikomatsakis** [comment]
There is also #22077 which is related

**Comment by aturon** [comment]
Closing, this is finished off!
