### ISSUE TITLE
OS X .pkg installer can't be uninstalled

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#20597]
This is pretty unfriendly. From some cursory googling I don't see an obvious easy way to make this possible.

**Comment by brson** [comment]
Nominating because of first impressions.

**Comment by inod** [comment]
Just a comment, I downloaded rust to try it out and I installed the .pkg instead of the script because on the website it says: `Recommended Version: nightly (Mac installer)`. Because the .pkg installer is encouraged, I thought it would at least come with an easy way to remove it.

**Comment by brson** [comment]
@inod It's unfortunate :(

**Comment by brson** [comment]
My current plan to fix this is to just have .pkg delegate to the tarball installer, which is thoroughly tested.

**Comment by bleibig** [comment]
It's possible to create a .pkg that does not install any files but only runs postinstall scripts by passing in `--nopayload` to `pkgbuild` (and specifying the postinstall scripts with `--scripts`). You can try that technique to make a separate uninstaller .pkg that simply runs an uninstall script, that way OS X users can uninstall rust in a way similar to how they installed it.

**Comment by brson** [comment]
Done.
