### ISSUE TITLE
Guide does not explain "extern crate"

### ISSUE THREAD

**Issue by kazagistar** [rust-lang/rust#20621]
The closest it gets is saying "And later, when you import a crate: `extern crate some_crate;`" which is not terribly clear. Nor does it explain why you are using it with "testing" later on.

**Comment by lifthrasiir** [comment]
I guess `extern crate` should be at least mentioned in the Chapter 15 (Crates and Modules).

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/blob/master/src/doc/trpl/crates-and-modules.md#importing-external-crates is now there, so this has been fixed.
