### ISSUE TITLE
Optimize enum layout

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#20638]
```rust
fn main() {
    enum X { A, B(u8, uint) }
    enum Y { A, B(uint, u8) }
    assert_eq!(std::mem::size_of::<X>(), 16);
    assert_eq!(std::mem::size_of::<Y>(), 24);
}
```

**Comment by frewsxcv** [comment]
Interestingly:

```rust
fn main() {
    enum X { A, B(u64, u32) }
    enum Y { A, B(u32, u64) }
    assert_eq!(std::mem::size_of::<X>(), 24);
    assert_eq!(std::mem::size_of::<Y>(), 16);
}
```

I don't know much about llvm, but I would maybe guess some sort of optimization is going on

**Comment by Diggsey** [comment]
@frewsxcv Those sizes are what one would expect without any kind of optimisation:
X => 1 byte discriminator + 7 bytes padding for field alignment + 8 bytes for u64 + 4 bytes for u32 + 4 bytes padding for struct alignment = 24 bytes total
Y => 1 byte discriminator + 3 bytes padding for field alignment + 4 bytes for u32 + 8 bytes for u64 = 16 bytes total

**Comment by frewsxcv** [comment]
@Diggsey Awesome, thanks for the clarification :+1: . I'm not experienced in this lower level way of thinking

**Comment by frewsxcv** [comment]
@Diggsey also, for X, 1 + 7 + 8 + 4 != 24

**Comment by frewsxcv** [comment]
Nevermind, missed that last `+ 4`

**Comment by Diggsey** [comment]
NP, you had me worried for a second there...

**Comment by huonw** [comment]
@mahkoh to be clear, are you suggesting that the compiler should reorder fields to try to make enums as small as possible?

**Comment by mahkoh** [comment]
Isn't that the point behind leaving the layout undefined?

**Comment by huonw** [comment]
I'll take that as a yes. Thanks for clarifying.

**Comment by mahkoh** [comment]
This particular enum can be optimized without reordering fields. Reordering is just one method to find an unused byte.

**Comment by kmcallister** [comment]
> Reordering is just one method to find an unused byte.

Some of which we should only do with `#[repr(packed)]`.
