### ISSUE TITLE
Tracking issue for Rename `int/uint` to `isize/usize` (RFC 544)

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#20639]
https://github.com/rust-lang/rfcs/pull/544

Specifically, `int` and `uint` should be deprecated in favor of `isize` and `usize`.

**Comment by aturon** [comment]
cc @cmr @Cloudidust

**Comment by pnkfelix** [comment]
( @huonw has a branch with much of this implemented: https://github.com/huonw/rust/tree/int-feature ; I am currently trying to shepherd that branch into a landable state )

**Comment by steveklabnik** [comment]
What actually closes this issue, is it when `int/uint` is totally gone?

**Comment by nagisa** [comment]
We have another issue to audit our uses of int/uint in (at least in parts of) the code base. https://github.com/rust-lang/rust/issues/22240

**Comment by aturon** [comment]
@steveklabnik I this we can declare this issue done; as @nagisa, we're tracking the audit/API renaming elsewhere.
