### ISSUE TITLE
rustdoc doesn't render associated type bindings

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#20646]
### STR

``` rust
#![feature(associated_types)]

pub trait Trait {
    type Output;
}

pub fn fun<T>(_: T) where T: Trait<Output=int> {}
```

### Output

![20150106122627](https://cloud.githubusercontent.com/assets/5018213/5632747/549a73d2-959f-11e4-912a-960ddd5f6b18.png)

The `T: Trait` bound should render as `T: Trait<Output=int>`

### Version

`rustc 0.13.0-nightly (c7dd3c4d6 2015-01-05 23:51:00 +0000)`

**Comment by nick29581** [comment]
Is anyone working on this?

**Comment by nick29581** [comment]
@tomjakubowski ?

**Comment by tomjakubowski** [comment]
If no one else is, I'll be working on this in a few hours along with a few other rustdoc issues,

**Comment by aturon** [comment]
@tomjakubowski FWIW, this would need to be resolved in the next couple of hours to make the alpha window. I would prioritize this bug pretty highly and try to get it in if you can!

**Comment by pnkfelix** [comment]
(cross-crate instances still need to be resolved.)

Not a beta-blocker.  Reclassifying as 1.0
