### ISSUE TITLE
mem-categorization seems to use completely bogus type for overloaded indices

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#20649]
While fixing an ICE, I noticed that mem-categorization is using the type of the collection (the self type) as the type of element:

``` rust
let element_ty = .. {
                let ref_ty = self.overloaded_method_return_ty(method_ty);
                base_cmt = self.cat_rvalue_node(elt.id(), elt.span(), ref_ty);
                let self_ty = ty::ty_fn_sig(method_ty).input(0);
                ty::assert_no_late_bound_regions(self.tcx(), &self_ty)
}
```

Unless I'm being silly, this seems pretty bogus. But I didn't want to get things mixed up so I'm leaving it for now and filing a FIXME instead. Maybe I'm just confused.

**Comment by Gankro** [comment]
@nikomatsakis any epiphanies here?

**Comment by nikomatsakis** [comment]
I forgot about this but I still think it's totally wrong. Should just fix it and see what happens, I wouldn't expect any effect.

**Comment by steveklabnik** [comment]
Triage: FIXME is still in the code.
