### ISSUE TITLE
Reference syntax for Closure type is incomplete

### ISSUE THREAD

**Issue by jsgf** [rust-lang/rust#20668]
The Reference says the syntax for a closure type is:

    closure_type := [ 'unsafe' ] [ '<' lifetime-list '>' ] '|' arg-list '|'
                [ ':' bound-list ] [ '->' type ]
    arg-list := ident ':' type | ident ':' type ',' arg-list
    ...

`arg-list` seems incomplete as it doesn't cover `|: ...|` `|&: ...|` `|&mut: ...|`

The Reference only incidentally mentions `|&: ...|` and doesn't touch any of the other forms, and doesn't describe their semantics.

**Comment by frewsxcv** [comment]
Relevant issue: https://github.com/rust-lang/rust/issues/19841

**Comment by steveklabnik** [comment]
Closing as a dup of https://github.com/rust-lang/rust/issues/19841
