### ISSUE TITLE
Make `substs()`, `input_types()`, etc on `PolyTraitRef` preserve the binding level

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#20664]
These accessors allow you to skip past the binder in a very lightweight way. This is a bad thing, since the binder is significant. We should refactor them away. While we're at it, it'd might be best if the internal field of a `Binder` was private. We would then add accesses for every `PolyFooBar` type for the fields of `FooBar`. These accessors would yield a `Binder<T>` for those fields that may contain late-bound regions. I've been moving to this model gradually, but we should finish the job.

**Comment by jroesch** [comment]
cc me, :+1:

**Comment by steveklabnik** [comment]
Traige: FIXMEs still in the code, no change.

**Comment by frewsxcv** [comment]
Triage: [FIXMEs still in the code, no change.](https://github.com/rust-lang/rust/blob/6f4ab9458a7ad06c8ce630604f533c8c0c0acef4/src/librustc/ty/sty.rs#L415-L423)
