### ISSUE TITLE
Guide chapter on Closures is inconsistent and incomplete

### ISSUE THREAD

**Issue by jsgf** [rust-lang/rust#20667]
The Guide's discussion of Closures has several problems:

It doesn't explain the |&:| syntax at all. The examples have been updated to use it, but the prose still just talks about "||". I think this is the right place to clarify what |:|, |&:| and |&mut:| mean, and perhaps how they relate to the Fn traits (which I don't really understand, which I was looking here for clarification).

The example using "twice()" uses two different syntaxes. First it says:

     fn twice<F: Fn(i32) -> i32>(x: i32, f: F) -> i32 {

but later it says

    fn twice(x: i32, f: |i32| -> i32) -> i32 {

Are these equivalent?

I understand this is still in flux, and I gather the |:| syntax is going to go away (?) or become mostly optional(?) - either way, a paragraph with a bit of explanation would be useful.

**Comment by steveklabnik** [comment]
Closing as a dup of https://github.com/rust-lang/rust/issues/19841
