### ISSUE TITLE
src/test/run-pass/html-literals.rs is ignored

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#20673]
With the new macro rules (https://github.com/rust-lang/rust/pull/20563) this test had to be ignored.

**Comment by alexcrichton** [comment]
cc @cmr

**Comment by cmr** [comment]
If this is fixed at all, it will be by integrating detailed FIRST sets into the check, but I'm not sure we *want* to support something like this with `macro_rules` (I know @nikomatsakis has opinions about this).
