### ISSUE TITLE
Exported macros break paths

### ISSUE THREAD

**Issue by lifthrasiir** [rust-lang/rust#20701]
```rust
$ cat t.rs
#[macro_export] macro_rules! foo { () => (mod foo { use super::f; pub fn ff() { f(); } }) }

$ cat s.rs
#[macro_use] extern crate t;
macro_rules! bar { () => (mod bar { use super::f; pub fn ff() { f(); } }) }
fn f() { println!("ffff"); }
foo!();
bar!();

$ rustc t.rs --crate-type lib

$ rustc s.rs --crate-type lib -L.
<t macros>:1:25: 1:30 error: expected identifier, found keyword `super`
<t macros>:1 (  ) => ( mod foo { use super :: f ; pub fn ff (  ) { f (  ) ; } } )
                                     ^~~~~
```

Macro definitions encoded to the metadata do not preserve the `ModName` identifier style, thus certain paths break down.

**Comment by kmcallister** [comment]
Nice catch. I was afraid something like this would happen...

Really a bug in pretty printing, as it doesn't preserve the ident style.  This is what we get for hacking contextual lexer information into the token stream...

**Comment by lifthrasiir** [comment]
The original example now compiles fine, but then I'm not sure about tomaka/android-rs-glue#27. @tomaka, is this issue still relevant?

**Comment by tomaka** [comment]
I didn't test myself, but @ozkriff reported that it's fixed.

**Comment by alexcrichton** [comment]
Yeah it looks like this has been fixed, yay!
