### ISSUE TITLE
Documentation link only works for first symbol if multiple identical are present

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#20700]
In case documentation page displays multiple symbols with the same name, only the first one can be linked to.

For example `fmt` on `u32` page: http://doc.rust-lang.org/std/primitive.u32.html#method.fmt

**Comment by xnil** [comment]
This deserves the E-tedious label.
I'll get to work on it, but it may not get done until tomorrow.

**Comment by xnil** [comment]
See #21967.

**Comment by l0kod** [comment]
Same for [examples links](http://doc.rust-lang.org/std/iter/trait.IteratorExt.html#examples).

**Comment by alexcrichton** [comment]
I'm going to close this in favor of #17476 as I think that's the best route to go (removing these anchors altogether and making them hyperlinks).
