### ISSUE TITLE
Improve error messages from type parameter shadowing

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#20729]
https://github.com/rust-lang/rust/pull/20728 gives the absolute minimum information about shadowed type parameters, just telling you there is one, and which it is. The span is the whole method and so is suboptimal (would be better to point to the specific problematic type parameter), and it would be nice to indicate the shadowed type parameter, similar to the shadowed lifetime warning.

**Comment by steveklabnik** [comment]
Traige: `src/test/compile-fail/shadowed-type-parameter.rs` can be used to reproduce, and the span still shows the whole name.

**Comment by estebank** [comment]
[Current output](https://is.gd/3Jp5GX):

```rust
error[E0194]: type parameter `T` shadows another type parameter of the same name
  --> <anon>:18:27
   |
15 | trait Bar<T> {
   |           - first `T` declared here
...
18 |     fn shadow_in_required<T>(&self);
   |                           ^ shadows another type parameter
```

**Comment by Mark-Simulacrum** [comment]
I believe the current output (same as in previous comment) fixes this. Marking as E-needstest, a UI test (moving src/test/compile-fail/shadowed-type-parameter.rs) would be great. I believe this is an easy task, so marking as such -- I can provide mentoring instructions as needed, let me know.
