### ISSUE TITLE
rustdoc: Inlined associated types are missing bounds

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang/rust#20727]
e.g. compare http://doc.rust-lang.org/core/ops/trait.Deref.html and http://doc.rust-lang.org/std/ops/trait.Deref.html

**Comment by tomjakubowski** [comment]
N.B. There is an out of date `FIXME(#18048)` related to this https://github.com/rust-lang/rust/blob/9f1ead8fadc56bad30dc74f5cc50d78af4fbc972/src/librustdoc/clean/mod.rs#L2384-L2385

**Comment by nick29581** [comment]
Type params seem to be missing the un-bound `?Sized` too. I assume this is the same bug, but not 100% sure. E.g., `std::ops::Index` vs `core::ops::Index`

**Comment by tomjakubowski** [comment]
Type params in general seem to be missing `?Sized`, like in:

```rust
// foo.rs
pub fn f<T: ?Sized>(_: &T) { }
```
```rust
// bar.rs
extern crate foo;

pub use foo::f;
```

I'll make a new issue.

**Comment by SimonSapin** [comment]
Possibly the same bug, but `impl` documentation on re-exported types are also missing things for associated types:

http://doc.rust-lang.org/core/slice/struct.Iter.html#implementations
> ```rust
> impl<'a, T> Index<Range<usize>> for Iter<'a, T>
>   type Output = [T]
>   fn index(&self, index: &Range<usize>) -> &[T]
> ```

http://doc.rust-lang.org/std/slice/struct.Iter.html#implementations
> ```rust
> impl<'a, T> Index<Range<usize>> for Iter<'a, T>
>   fn index(&self, index: &Range<usize>) -> &[T]
>   type Output
> ```

**Comment by tomjakubowski** [comment]
OK, I'm pretty sure that defaults will have to wait until they're actually implemented, so I've changed the issue title.

**Comment by tomjakubowski** [comment]
Since my last PR landed you can actually see all the bounds on an inlined trait's associated types! Unfortunately it's very ugly (and `: Sized` appears while `: ?Sized` doesn't, contrary to a user's expectations).

http://doc.rust-lang.org/std/ops/trait.Add.html

```rust
pub trait Add<RHS = Self> where <Self as Add<RHS>>::Output: Sized {
    type Output;
    fn add(self, rhs: RHS) -> <Self as Add<RHS>>::Output;
}
```
