### ISSUE TITLE
compile-fail/recursion.rs uses a dummy span with an expansion id of -2

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#20747]
Found whilst testing #20032

From [the test](https://github.com/rust-lang/rust/blob/master/src/test/compile-fail/recursion.rs):

```
// We also get a second error message at the top of file (dummy
// span). This is not helpful, but also kind of annoying to prevent,
// so for now just live with it, since we also get a second message
// that is more helpful.
```

This should probably be fixed. For now (when #20032 lands) I've made that test ignore command line spans.

I'll work on tracking back this span and trying to fix this.

**Comment by Manishearth** [comment]
https://github.com/nikomatsakis/rust/commit/9e4e8823c7cb553f07536ff2cbdaabdcd0dc9cc0

**Comment by nikomatsakis** [comment]
I don't understand. I know the source of that particular error, are you saying that we get another? The source of that error is that we don't pass a span into `librustc_trans::common::type_is_sized()` and thus have to gin one up.

**Comment by Manishearth** [comment]
(I'm working on this, got some ideas as to why it's happening)
