### ISSUE TITLE
Slicing syntax very unergonomic in latest nightly

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#20743]
This no longer works:
```rust
s[i+j..].to_string() // s is a &str
```
You now have to write
```rust
(&s[(i+j)..]).to_string()
```
At this point using slice_from is more ergonomic.

**Comment by mahkoh** [comment]
```
~$ rustc --version
rustc 1.0.0-dev (9f1ead8fa 2015-01-07 17:45:11 +0000)
```

**Comment by japaric** [comment]
cc @nick29581

**Comment by nick29581** [comment]
Fixed by #20720

**Comment by nick29581** [comment]
At least the precedence issue.

For everything except `str` you don't need the `(&...)`, that is a known bug. I'm not sure if there is an issue open for it (@japaric, did you find/open one?). If not let's re-open this one and rename it to make clear the `(&...)` for str thing

**Comment by alexcrichton** [comment]
I think @huonw took care of the rest in https://github.com/rust-lang/rust/pull/20744.
