### ISSUE TITLE
Refactor librustc_back to support arbitrary linkers

### ISSUE THREAD

**Issue by retep998** [rust-lang/rust#20764]
Currently `librustc_back` is hardcoded to use a certain method of linking which makes it extremely inflexible for supporting other linkers such as `link.exe`. It needs to be refactored somehow such that a flexible target spec can specify what linker implementation to use.

**Comment by huonw** [comment]
Flexible target specs are loaded at runtime in to the compiler, and don't allow implementing a trait for custom behaviour.

(It seems it may not be better to prescribe an implementation strategy.)

**Comment by retep998** [comment]
This would be fixed by #25350 which does in fact use a trait for the linker as I originally suggested.
