### ISSUE TITLE
Documentation in librustc has sentence fragment. 

### ISSUE THREAD

**Issue by estsauver** [rust-lang/rust#20762]
Line 71 of https://github.com/rust-lang/rust/blob/dc6e414e6f85293aceca3357e2466bcc4bcf425c/src/librustc/README.txt#L71 seems to trail off. 

@nikomatsakis looked like he was adding something more to the file here: https://github.com/rust-lang/rust/commit/dc6e414e6f85293aceca3357e2466bcc4bcf425c

**Comment by steveklabnik** [comment]
Merged.
