### ISSUE TITLE
Don't use "generic" as the target cpu

### ISSUE THREAD

**Issue by dotdash** [rust-lang/rust#20777]
By default, we use the "generic" target CPU, unfortunately on x86_64, this disables various features because "generic" is more like "generic x86". This disable things like some SSE usage and multibyte nops. On x86_64 we should use `x86-64` as the minimum target cpu, not sure about other archs.

To present some arbitrary numbers:
```
# target cpu "generic"
$ objdump -S libsyntax-4e7c5e5c.so | grep xmm -c
25148

# target cpu "x86-64"
$ objdump -S libsyntax-4e7c5e5c.so|grep xmm  -c
83740
```

cc @cmr

**Comment by Gankro** [comment]
@dotdash Did your PR not resolve this?

**Comment by dotdash** [comment]
It probably did for x84_64, but I'm not sure about x86 (I guess "generic"
is like i386, which seems a bit too old a target), ARM, etc.
Am 21.01.2015 23:33 schrieb "Alexis Beingessner" <notifications@github.com>:
