### ISSUE TITLE
Add an option to rustdoc to deny warnings and use it in std

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#20787]
In https://github.com/rust-lang/rust/pull/20786 I'm recommending removing this feature of rustdoc as a blanket policy. It should be optional. Perhaps something even more generic like the `-D`, `-F`, of rustc, but applicable to doc tests.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#703
