### ISSUE TITLE
Can cast an unusable value to a raw pointer

### ISSUE THREAD

**Issue by wthrowe** [rust-lang/rust#20791]
```rust
fn main() {
    let x: &i32;
    //x; // error: use of possibly uninitialized variable: `x`
    println!("{:?}", x as *const _);
}
```
This is accepted and prints `0x0` everywhere I've tested (rustc 0.13.0-dev (496dc4eae) and the playpen).  A similar access is allowed to moved values and mutably borrowed values.

I assume I should not be able to access uninitialized values without some unsafe code, although I am new to the language and might be missing something.

**Comment by Thiez** [comment]
You assumption is correct, the reference explicitly defines this as `unsafe`, see the 4th rule [here](http://doc.rust-lang.org/reference.html#behavior-considered-undefined).

**Comment by kmcallister** [comment]
Nice catch!

**Comment by nikomatsakis** [comment]
Weird. Perhaps an oversight in the EUV?

**Comment by nikomatsakis** [comment]
cc me

**Comment by kmcallister** [comment]
Still compiles successfully (I made a minor rustup edit).  Closed by mistake?

**Comment by nikomatsakis** [comment]
Um, it appears I got confused -- I added a run-pass test ;)
