### ISSUE TITLE
impl fmt::String for tuples

### ISSUE THREAD

**Issue by aepsil0n** [rust-lang/rust#20816]
This does not work:

```rust
println!("{}", ());
```

and neither does this with any tuple atm.

Or is this intentional?

**Comment by alexcrichton** [comment]
This is currently intentional, and I believe that @aturon will open an RFC soon about `Show`/`String` conventions, so stay tuned to the RFC repo!

**Comment by alexcrichton** [comment]
https://github.com/rust-lang/rfcs/pull/565 (now opened)
