### ISSUE TITLE
ICE when a supertrait bound contains a binding for a type defined in the supertrait

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#20825]
Example (reduced by @sfackler from something reported on IRC):

```rust
pub trait Subscriber {
    type Input;
}

pub trait Processor : Subscriber<Input=Self::Input> {
    type Input;
}

fn main() {}
```

**Comment by tomprogrammer** [comment]
Is that allowed syntax? As RFC 195 states ["[…] associated types/lifetimes are not in scope for the optional where clause on the trait header."](https://github.com/rust-lang/rfcs/blob/master/text/0195-associated-items.md#scoping-of-trait-and-impl-items).

I tried to express something like `trait Example: Iterator<Item=Option<Self::AssocType>> { type AssocType; }` but thought I have to wait until where clauses on associated type definitions land.

**Comment by tomprogrammer** [comment]
Nevermind, got it. Only `AssocType` is not in scope for the trait header, but `Self::AssocType` is a path to it, so it is valid syntax.

Keep up your excellent work :)

**Comment by apasel422** [comment]
The code snippet above now causes the following error:
```
foo.rs:5:40: 5:51 error: associated type `Input` not found for type parameter `Self` [E0220]
foo.rs:5 pub trait Processor : Subscriber<Input=Self::Input> {
```
Changing the `Processor` trait to:
```rust
pub trait Processor : Subscriber<Input=<Self as Processor>::Input> {
    type Input;
}
```
yields
```
foo.rs:5:40: 5:66 error: illegal recursive type; insert an enum or struct in the cycle, if this is desired [E0246]
foo.rs:5 pub trait Processor : Subscriber<Input=<Self as Processor>::Input> {
```

**Comment by Gankro** [comment]
I'd like to nominate this, I don't think we can remove old_impl_check without it.

**Comment by arielb1** [comment]
This currently reports `error: unsupported cyclic reference between types/traits detected [E0391]`
