### ISSUE TITLE
Rust 32bit does not compile on Windows 7: LLVM fails to build

### ISSUE THREAD

**Issue by AnthIste** [rust-lang/rust#20821]
## Environment

  - Fresh Windows 7 x64 installation in a VirtualBox VM
  - Clean install of build toolchain suggested by the Rust readme

## Steps to reproduce

Compile Rust according to the steps listed in the Readme (quoted for reference):

To easily build on windows we can use MSYS2:

Grab the latest MSYS2 installer and go through the installer.
Now from the MSYS2 terminal we want to install the mingw64 toolchain and the other tools we need.

    $ pacman -S mingw-w64-i686-toolchain
    $ pacman -S base-devel

With that now start mingw32_shell.bat from where you installed MSYS2 (i.e. C:\msys).

From there just navigate to where you have Rust's source code, configure and build it:

    $ ./configure
    $ make && make install

## Expected Results

Expected Rust to compile

## Actual Results

Originally the build failed during the `make llvm` stage. The most glaring issues are invalid headers (llvmconfig.h) and missing definitions (Don't have a definition for uint64_t on this platform).

Attempting this a second time there was an issue with sed:

    configure: WARNING: dlopen() not found - disabling plugin support
    sed: file ./confOAhICq/defines.sed line 55: unknown command: `['
    sed: file ./confOAhICq/defines.sed line 38: unknown command: `['
    sed: file ./confOAhICq/defines.sed line 55: unknown command: `['
    sed: file ./confOAhICq/defines.sed line 38: unknown command: `['
    sed: file ./confOAhICq/defines.sed line 55: unknown command: `['
    sed: file ./confOAhICq/defines.sed line 38: unknown command: `['
    nu/llvm/include/llvm/Config/llvm-config.h:572:2: error: #endif without #if
     #endif
      ^
A truncated start of the original log is listed here with gists of the full logs:

    In file included from E:/rust/src/llvm/include/llvm/Support/Compiler.h:18:0,
                     from E:/rust/src/llvm/include/llvm/ADT/STLExtras.h:20,
                     from E:/rust/src/llvm/include/llvm/ADT/ArrayRef.h:14,
                     from E:/rust/src/llvm/include/llvm/ADT/APInt.h:19,
                     from E:/rust/src/llvm/include/llvm/ADT/APFloat.h:20,
                     from E:/rust/src/llvm/lib/Support/APFloat.cpp:15:
    E:/rust/i686-pc-windows-gnu/llvm/include/llvm/Config/llvm-config.h:572:2: error: #endif without #if
     #endif
      ^
    In file included from E:/rust/src/llvm/include/llvm/Support/SwapByteOrder.h:18:0,
                     from E:/rust/src/llvm/include/llvm/Support/MathExtras.h:18,
                     from E:/rust/src/llvm/include/llvm/ADT/SmallVector.h:20,
                     from E:/rust/src/llvm/include/llvm/ADT/ArrayRef.h:15,
                     from E:/rust/src/llvm/include/llvm/ADT/APInt.h:19,
                     from E:/rust/src/llvm/include/llvm/ADT/APFloat.h:20,
                     from E:/rust/src/llvm/lib/Support/APFloat.cpp:15:
    E:/rust/i686-pc-windows-gnu/llvm/include/llvm/Support/DataTypes.h:78:3: error: #error "Don't have a definition for uint64_t on this platform"
     # error "Don't have a definition for uint64_t on this platform"
       ^
    E:/rust/i686-pc-windows-gnu/llvm/include/llvm/Support/DataTypes.h:573:2: error: #endif without #if
     #endif
      ^
    In file included from E:/rust/src/llvm/include/llvm/Support/Allocator.h:26:0,
                     from E:/rust/src/llvm/include/llvm/ADT/FoldingSet.h:21,
                     from E:/rust/src/llvm/lib/Support/APFloat.cpp:17:
    E:/rust/i686-pc-windows-gnu/llvm/include/llvm/Support/DataTypes.h:573:2: error: #endif without #if
     #endif
      ^

## Full Logs

  - [configure output](https://gist.github.com/AnthIste/d1c8379a638317d3ecb8)
  - [make output](https://gist.github.com/AnthIste/42ecf4763f318eed6a4b)
  - [error output](https://gist.github.com/AnthIste/e97827864ed4a54f5b97)

**Comment by AnthIste** [comment]
Compiling was also attempted using the 64bit toolchain - which means it could be an environment issue. I will do more research to try and narrow it down.

**Comment by klutzy** [comment]
Seems like `llvm-config.h` is not correctly generated. (it's in `[build-dir]/i686-pc-windows-gnu/llvm/include/llvm/Config/`) Could you check the file?

**Comment by AnthIste** [comment]
The file does not exist - there is only llvm-config.h.in. Is there any way to capture this file during the build process?

**Comment by AnthIste** [comment]
I think this is a line-ending issue. I cloned a fresh repository and then the build went fine. The original repository I used was cloned on OSX into the VM's shared drive space. So the git line-ending settings probably caused it to go wonky. Is this a legitimate issue that should be fixed? If someone has the wrong auto.crlf setting then it will most likely not work.

**Comment by steveklabnik** [comment]
It's been a year, and nobody else has reported this issue. Gonna give it a close, I'm guessing this just went away.
