### ISSUE TITLE
Crawl doc.rust-lang.org for dead links on a regular basis

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#20827]
And open tickets here via the GitHub API :)

**Comment by nagisa** [comment]
Watching out for links to different version of documentation wound be a nice plus. I always find myself ending up at 0.12 docs and wondering why nothing is working for an hour.

**Comment by kmcallister** [comment]
Perhaps using https://github.com/XMPPwocky/legend_of_link! cc @XMPPwocky

**Comment by XMPPwocky** [comment]
Legend of Link doesn't do HTTP in any way yet, but it can crawl the generated docs locally; I think adding it to the test suite would be a better way to go in general.

If there's interest in HTTP support, I could certainly add that (I guess using hyper?)

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#669
