### ISSUE TITLE
Add 'next' links to pages of TRPL book

### ISSUE THREAD

**Issue by nstoddard** [rust-lang/rust#20835]
Since the pages in the "The Basics" section are intended to be read in order, there should be a link to the next page at the bottom (and possibly also at the top) of each page. Links to the previous page might be helpful too. The chapters in the intermediate and advanced sections can be read in any order, so I'm not sure if they should have next/previous links or not.

**Comment by steveklabnik** [comment]
👍 for the Basics.

**Comment by stevencrockett** [comment]
Links would be very helpful. The menu is great for getting to specific sections quickly, but I find it slightly annoying if I just want to get to the next page, as I have to think about the name of the page I'm on before locating it in the menu.

I'd say links throughout the whole book would be helpful. While the pages in the first section are intended to be in order, the self-contained topics in the other sections have an implicit order from the way they are arranged in the menu. Without links, I also think the chapter introductions also appear a bit strange to me (too sparse) ([example](http://doc.rust-lang.org/book/intermediate.html)).

Additionally, some of the topics seem to flow anyway, such as the [Generics](http://doc.rust-lang.org/book/generics.html) section leading into [Traits](http://doc.rust-lang.org/book/traits.html). Either way, for someone like me who is excited about Rust, but has yet to dig in properly, I would want to go through all the sections if possible and read everything. I suspect there will be many more people like me as Rust approaches the 1.0 beta and final releases. In this case, links are a great convenience, while everyone still has menu navigation available to use if they so wish.

I've been playing around with markdown, but am not completely sure how to make these links look nice. Things like alignment don't seem to be possible in normal markdown, though on GitHub at least I'm able to embed some simple html. I'm not sure if this works for rustbook however.

Anyway to give an example, I've considered appending something like this to the end of each page:

---
<h6 align=right><a href="standard-input.md">next: Standard Input</a></h6>
<h6 align=right><a href="strings.md">previous: Strings</a></h6>

The specific text could change depending on the context of the page. (e.g. "next section: Intermediate Rust" or "next topic: Pointers").

It would be nice actually if this insertion and naming of links could be done programatically by rustbook. It would leave the markdown files clean for any tool that builds an ePub (see #20866), and avoids the need to keep manually changing the links if pages are reordered/added/deleted/renamed. While the summary doesn't provide information for a "next topic" style link, it certainly provides enough for the "next" and "next section" links, and rustdoc seems to use this information already to generate the menu.

For now though, I don't mind doing this manually as a temporary solution until something automated can be put into place, assuming my suggestion is good in the first place.

**Comment by steveklabnik** [comment]
> Additionally, some of the topics seem to flow anyway, 

I originally wrote it to be ordered, but now it's moving towards unordered. Next and prev really make sense for Basics, but not for the other parts.

I wouldn't mind adding them manually. While it'd be nice to have them generated by Rustbook, since I don't think that it's always appropriate, we'd have to find some notation to indicate if this needs links or not, and that's too complicated.

**Comment by steveklabnik** [comment]
With https://github.com/rust-lang/rust/pull/21494 merged this is fixed.
