### ISSUE TITLE
The example in the concurrency guide is incorrect

### ISSUE THREAD

**Issue by reem** [rust-lang/rust#20844]
The offending example is:

```rust
use std::thread::Thread;

fn main() {
    for _ in 0..10 {
        Thread::spawn(|| {
            println!("Hello World!");
        });
    }
}
```

With the new detaching thread semantics, this is incorrect since main can exit before all the detached threads have printed.

**Comment by steveklabnik** [comment]
I _think_ that this was in the intro as well.
