### ISSUE TITLE
Rename string::push_str to string::concat

### ISSUE THREAD

**Issue by SDX2000** [rust-lang/rust#20857]
Please consider renaming string::push_str() to string::concat(). Push_X() in the context of a collection means X will be added to the container as a single entity. Hence push_str() is meaningless for strings since a string can only contain characters (char != [char]). 

If it is too late to rename then consider adding a method called concat() anyway.

Also consider renaming Vec::push_all() to Vec::concat() so that the name is consistent with String::concat().

**Comment by erickt** [comment]
@SDX2000: Thanks for this! This would be probably more appropriate as a comment on the current [collections reform RFC](https://github.com/rust-lang/rfcs/pull/509), so I'm going to close this and redirect you to comment there. Generally speaking though, we already have a function [concat](http://doc.rust-lang.org/std/slice/trait.SliceConcatExt.html#tymethod.concat), so we do have some desire to not use the same name for different things. Instead, a better solution might be if we end up growing an `AddAssign` trait that we could instead write:

```rust
let mut v = String::new();
v += 'a';
v += "foo";

let mut v = Vec::new();
v += 1u8;
v += [2u8, 3, 4];
```

And not worry about the method. There is a chance we might be able to get this in for rust 1.0 if someone does the work :)
