### ISSUE TITLE
Optimize documentation layout on mobile

### ISSUE THREAD

**Issue by iKevinY** [rust-lang/rust#20850]
Considering the fact that Rust has moved into alpha and *The Rust Programming Language* has replaced the Guide, I think it would be useful to work towards creating a mobile-friendly layout for Rust's documentation. #17926 discusses the Guide, but now that the Book has replaced the Guide and brought a whole new layout that includes a sidebar, more than just a viewport fix will be needed to make it mobile-friendly. From what I can tell, there are a few "page families" that would need some tweaking (complete with fancy GitHub-powered checklist):

- [x] *The Rust Programming Language* (http://doc.rust-lang.org/book/) [#21071]
- [x] Rust Reference & Documentation (similar page styles) [#21133]
    - (http://doc.rust-lang.org/reference.html)
    - (http://doc.rust-lang.org/index.html)
- [x] API Docs (http://doc.rust-lang.org/std/index.html) [#21597]

For the Rust Reference and Rust Documentation, a viewport meta tag might be all we need to make it mobile-friendly. The API Docs actually look pretty good on mobile already (the sidebar is pushed to the bottom of the page), but the page appears to load slightly zoomed-in (another viewport fix, likely).

The Book is rendered on mobile pretty much equivalently to the way it is displayed on larger displays, but it would be ideal for the content take up the full width of the screen. This leaves the sidebar to either be placed at the bottom of the page or converted into a dropdown menu of some sort. Thoughts?

**Comment by telotortium** [comment]
Even on desktop, the content is rendered at a size slightly larger than the viewport (I hope this is the correct term, I'm not a web developer). Therefore, on all platforms, you have to scroll horizontally just a bit in order to see the right margin of the content. Is this related?

**Comment by iKevinY** [comment]
@telotortium Are there any specific pages that this occurs on? Also, what browser are you using?

**Comment by telotortium** [comment]
Any page in the Rust book, in both Chrome and Firefox mobile. It's still a problem on desktop unless the window's at least 1000px wide, which is wider than almost all phones.

It seems like neither the table of contents nor the body reflows if the window is narrowed, but the viewport of the table of contents remains a fixed width, so less space is allotted for the body.

**Comment by iKevinY** [comment]
Ah, I see what you're talking about now. The CSS for the book looks [pretty minimalist](http://doc.rust-lang.org/book/rust-book.css) at the moment, so it's not too surprising that it's not particularly responsive. I think it will be significantly easier to fix the layout of the latter 2 items in the checklist, as the Book will be a pretty large undertaking.

**Comment by steveklabnik** [comment]
Yes, it's very much just the basics. I'd love a patch.

**Comment by kmcallister** [comment]
On #20961, @Valloric posted

> [Results from Google's Mobile-Friendly Test](https://www.google.com/webmasters/tools/mobile-friendly/?utm_source=psi&utm_medium=referral&utm_campaign=uxresults&url=http%3A%2F%2Fdoc.rust-lang.org%2Fnightly%2Fbook%2Fownership.html).

**Comment by frewsxcv** [comment]
Related issue: https://github.com/rust-lang/rust/issues/16174

**Comment by iKevinY** [comment]
Google's Mobile-Friendly Test now rates all pages as mobile-friendly, so it looks like issue can be closed.

**Comment by kmcallister** [comment]
\o/ Thanks everyone who helped make this happen!
