### ISSUE TITLE
Replace libc functions with WinAPIs on Windows

### ISSUE THREAD

**Issue by klutzy** [rust-lang/rust#20861]
We use libc functions on various Windows routines, but they are just convenient wrappers of WinAPI and there's usually no critical reason to use them.

Also, the wrapper has its own runtime state so it adds additional complexity, so it's better to use WinAPI than libc functions in general.
For example, msvcrt has libc `errno` variable, but it's not Windows' native error code value ([GetLastError()](http://msdn.microsoft.com/en-us/library/windows/desktop/ms679360(v=vs.85).aspx)) therefore unrelated to `std::os::errno()`.
Another example is that msvcrt manages its own "C locale", distinct to Windows locale.

Here's some libc uses (not complete):

-   `rt/rust_builtin.c`: e.g. `gmtime`, `localtime`. (seems like they are unused now)
-   `liballoc/heap.rs` uses `malloc`, `realloc`, `free` if jemalloc is disabled. [HeapAlloc is better?](http://msdn.microsoft.com/ko-kr/library/windows/desktop/aa366533(v=vs.85).aspx)
-   `libstd/sys/windows/`: e.g. `fs.rs` uses `open_osfhandle`.

See also [Support: Win32 Equivalents for C Run-Time Functions](http://support.microsoft.com/kb/99456/EN-US).

**Comment by retep998** [comment]
I don't know why we insist on providing `malloc` for interaction with C libraries when msdn explicitly states:
>The malloc function has the disadvantage of being run-time dependent.
I feel that if users want to do FFI with C libraries they are responsible for binding the appropriate allocation methods and ensuring they work correctly. Rust should not try to guarantee that the allocator it uses is compatible with non-Rust libraries when there are a plethora of incompatible allocators and even `malloc` itself is runtime dependent.

**Comment by alexcrichton** [comment]
I believe that this has basically been done to the fullest extent possible, so yay!
