### ISSUE TITLE
Headline Level in API Doc Comments

### ISSUE THREAD

**Issue by killercup** [rust-lang/rust#20863]
The API docs seem semantically quite nice, but don't incorporate headlines in comments into their document outline. The `Vec` doc e.g. uses an `h1` for the title, `h2` for "Methods", `h3`s for impl names and `h4`s for item names. Then a comment contains an `h1` ("Examples") and the outline is ruined.

_(This is a rustdoc issue, with probably low priority. It came up in #20826.)_

One possibility to fix this is to switch to `section` and `article` tags as described by HTML5—currently, everything is a `div`. You can find some [documentation here](https://developer.mozilla.org/de/docs/Web/Guide/HTML/Sections_and_Outlines_of_an_HTML5_document). Basically, this allows markup like the following to be meaningful:

``` jade
main.content.struct
  h1 Struct std::vec::Vec
  pre.rust.struct ... code ...
  article.docblock
    h1 Examples
    // ...
  section.methods
    h1 Methods
    section.impl
      h1 impl‹T› Vec‹T›
      section.method
        h1 fn new() → Vec‹T›
        article.docblock
           p Constructs a new, empty Vec‹T›.
           h1 Examples
           // ...
      section.method
        h1 fn with_capacity(capacity: usize) → Vec‹T›
        article.docblock
           p Constructs a new, empty Vec‹T› with the specified capacity.
           h1 Examples
           // ...
```

(This syntax is [Jade](http://jade-lang.com/), it shows the outline quite niceley. I replaced some characters to prevent escaping.)

**Comment by steveklabnik** [comment]
Triage: this is still pretty messed up. See https://gsnedders.html5.org/outliner/process.py?url=http%3A%2F%2Fdoc.rust-lang.org%2Fstd%2Fvec%2F for example.

**Comment by steveklabnik** [comment]
@rust-lang/rustdoc do we ever plan on addressing this?

**Comment by killercup** [comment]
Wow, it's been two and a half years! Looking back at this, this still seems quite easily fixable by replacing a bunch of divs.

**Comment by GuillaumeGomez** [comment]
I'm afraid that the content "flow" would get out of hand: either we reduce sub-elements width or we remove the right side limit (which will end up in reducing sub-elements width in any case). Not really sure this is a good idea...

**Comment by killercup** [comment]
Huh? I don't follow, @GuillaumeGomez. This is about changing the markup, not the design?

**Comment by GuillaumeGomez** [comment]
You add indent for every new sub-item. The space limit will get reached very quickly, that's why I'm not sure this is a good idea for rustdoc.

**Comment by QuietMisdreavus** [comment]
Can't we change the style to make sub-items not add indent? This is a suggestion that should make no difference on the visual styling of the rendered HTML. Will replacing a `<div>` with a `<section>` cause that much of a problem?

**Comment by camelid** [comment]
I think this has since been fixed. E.g., "Examples" in [`Vec::as_ptr`](https://doc.rust-lang.org/nightly/std/vec/struct.Vec.html#method.as_ptr) is an h5. Please reopen if I misunderstood.
