### ISSUE TITLE
Provide wrappers over Box<Fn>

### ISSUE THREAD

**Issue by bombless** [rust-lang/rust#20878]
Something like this:
```Rust
#![feature(unboxed_closures, box_syntax)]
#![allow(unstable)]
struct Proxy<'a, Args, Ret> {
    closure: Box<Fn<Args, Ret> + 'a>
}
impl<'a, Args, Ret> Fn<Args, Ret> for Proxy<'a, Args, Ret> {
    extern "rust-call" fn call(&self, args: Args)->Ret {
        self.closure.call(args)
    }
}
impl<'a, Args, Ret> Proxy<'a, Args, Ret> {
    fn new<F: Fn<Args, Ret> + 'a>(closure: F)->Proxy<'a, Args, Ret> {
        Proxy { closure: box closure }
    }
}
fn main(){
    let celebrate = Proxy::new(|&: num: i64| {
        println!("Feels great to implement C++ std::function in {} lines.", num)
    });
    let lucy_number = Proxy::new(|&: num: i64| {
        println!("My lucky number is {}", num)
    });
    let func = if std::rand::random() { celebrate } else { lucy_number };
    func(25)
}
```
Or is it part of the plan? :p

**Comment by reem** [comment]
What's the benefit of the Proxy type over just using an `Fn` trait object directly?

**Comment by bombless** [comment]
A proxy is the same type while  arguments type and return type are the same, thus makes it possible to write a `if` while both arms are closures.
Other than `if`, `match` arms can benefit from it, too.

**Comment by reem** [comment]
@bombless You can do the same thing by using regular trait objects, like so:

```rust
#![feature(box_syntax)]
#![allow(unstable)]
fn main(){
    let celebrate: Box<Fn(i64)> = box |&: num: i64| {
        println!("Feels great to implement C++ std::function in {} lines.", num)
    };
    let lucky_number: Box<Fn(i64)> = box |&: num: i64| {
        println!("My lucky number is {}", num)
    };
    let func = if std::rand::random() { celebrate } else { lucky_number };
    func(25)
}
```

You can even avoid the type annotations in a lot of cases.

**Comment by bombless** [comment]
@reem For my experience, annotations cannot be avoided in most cases.
And you are right, I usually do things in your way. I just think offering standard proxy will make it easier to write such code.
And it seems that we will have bare trait one day and there's nothing to bother at that time ( [being able to return a bare trait from a function](http://featherweightmusings.blogspot.co.nz/2014/12/my-thoughts-on-rust-in-2015.html) ).

**Comment by Gankro** [comment]
Seems like this bug just amounts to "closures are unergonomic", then?

**Comment by reem** [comment]
"conversion to trait objects is verbose and unergonomic" probably, which I have definitely experienced.

**Comment by bombless** [comment]
@Gankro We can call it a feature, and I think the issue is the lack of relative facilities.

**Comment by bombless** [comment]
@reem Yeah maybe things will change once type inference is improved.
Is there a chance that `box`ing will be able to be done automatically according to type inference? If so then things can even become better.

**Comment by bombless** [comment]
https://github.com/rust-lang/rust/issues/18875
If I understand correctly the `Proxy` code will not compile at the next nightly build of rustc, sad story.

**Comment by bombless** [comment]
https://github.com/nikomatsakis/rust/commit/152d62387786a0bb74b51ae5b40821966b15764e#diff-0
My bad, it's just behind a unboxed_closures feature gate, as always.

**Comment by sellibitze** [comment]
It seems the proxy type thingy serves no purpose. Sometimes, a function is all you need:

```
#![feature(unboxed_closures, box_syntax)]
#![allow(unstable)]

fn anyfunc<'a, Args, Ret, F>(closure: F) -> Box<Fn<Args, Ret> + 'a>
where F: Fn<Args, Ret> + 'a {
    box closure
}

fn main(){
    let celebrate = anyfunc(|&: num: i64| {
        println!("Feels great to implement C++ std::function in {} lines.", num)
    });
    let lucy_number = anyfunc(|&: num: i64| {
        println!("My lucky number is {}", num)
    });
    let func = if std::rand::random() { celebrate } else { lucy_number };
    func(25)
}
```

It's actually similar to what you would do in C++: write a function template à la `make_shared` etc.

**Comment by alexcrichton** [comment]
I agree with @reem, @Gankro, and @sellibitze in that this may just be an issue of ergonomics as boxed trait objects/closures sound like they do what you already want. Could you open a new issue more focused on the ergonomics of boxed closures if you're concerned? Thanks!
