### ISSUE TITLE
trait lang item on a struct

### ISSUE THREAD

**Issue by apreiml** [rust-lang/rust#20875]
```
thread 'rustc' panicked at 'assertion failed: did.krate != ast::LOCAL_CRATE', /build/buildd/rust-nightly-201501100408~14f9d1f~trusty/src/librustc/middle/ty.rs:5407

stack backtrace:
   1:     0x2ae1b47dd480 - sys::backtrace::write::h62c31c8ce34639e5Jzt
   2:     0x2ae1b47ff6a0 - <unknown>
   3:     0x2ae1b476d210 - rt::unwind::begin_unwind_inner::he6cbf3e88d73f0799tz
   4:     0x2ae1b6036a70 - <unknown>
   5:     0x2ae1b63d0fd0 - middle::ty::lookup_trait_def::hdfbea244d3d6f091YK8
   6:     0x2ae1b63f2700 - middle::ty::predicates_for_trait_ref::he697e3d5878aab355L8
   7:     0x2ae1b63ca680 - middle::traits::util::Elaborator<'cx, 'tcx>.Iterator::next::h50ca4a7d9ffad3d9fiU
   8:     0x2ae1b6427160 - middle::ty::required_region_bounds::h4b25d429295ec69eKi9
   9:     0x2ae1b5138730 - <unknown>
  10:     0x2ae1b5126470 - <unknown>
  11:     0x2ae1b5176c50 - <unknown>
  12:     0x2ae1b525c500 - <unknown>
  13:     0x2ae1b5257040 - check_crate::h79cca79b16d5148023x
  14:     0x2ae1b43df660 - driver::phase_3_run_analysis_passes::h1b173e994da54b02gwa
  15:     0x2ae1b43c7fa0 - driver::compile_input::hff268245321ca983xba
  16:     0x2ae1b4497c40 - <unknown>
  17:     0x2ae1b4497aa0 - <unknown>
  18:     0x2ae1b4496820 - <unknown>
  19:     0x2ae1b48645c0 - <unknown>
  20:     0x2ae1b48645b0 - rust_try
  21:     0x2ae1b4496b10 - <unknown>
  22:     0x2ae1b47ed540 - <unknown>
  23:     0x2ae1ba30c0c0 - start_thread
  24:     0x2ae1b4df9ec9 - __clone
  25:                0x0 - <unknown>

make: *** [main.o] Error 101
```

Version (nightly from : http://ppa.launchpad.net/hansjorg/rust/ubuntu)

rustc 1.0.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.0.0-dev

I've tried to compile: https://github.com/apreiml/rustboot

**Comment by crumblingstatue** [comment]
Here is a test case:
```rust
#![no_std]

#![feature(lang_items)]
#[lang="sized"]
enum Foo<T> {Variant(T)}

fn main() {}
```

The ICE seems to happen when there is a generic enum declared as the "sized" lang item. (which of course doesn't make sense)

**Comment by zhangpf** [comment]
http://is.gd/SpIRJe
encounter the same problem.

**Comment by pnkfelix** [comment]
cc @nikomatsakis

**Comment by pnkfelix** [comment]
(actually maybe this does not really need @nikomatsakis 's attention; I suspect we could just make the code check a bit more carefully that the `Sized` lang-item matches expectations (and issue a proper error when it does not.)

**Comment by tamird** [comment]
Triage bump: still ICEs.
```rust
#![feature(no_std,lang_items)]
#![no_std]

#[lang="sized"]
struct Bar<T> {field: T}

fn main() {}
```

**Comment by bltavares** [comment]
I could not compile the latest example and I'm not sure what is causing it.
http://is.gd/O7SWvV

Removing the `lang` pragma makes it compile, but I guess that is that is a change on the semantics.

**Comment by steveklabnik** [comment]
@alexcrichton the recent changes to `no_std` probably change these samples, huh? Any ideas on how to reproduce?

**Comment by arielb1** [comment]
@steveklabnik 

Use `no_core` instead of `no_std`. However, as a rule, we don't type-check lang items (e.g. you can cause also cause an easy ICE if you add type parameters or associated items to `Sized`).

**Comment by bltavares** [comment]
Is this the same ICE?

```rust
#![feature(no_core,lang_items)]
#![no_core]

#[lang="sized"]
struct Bar<T> {field: T}

fn main() {}
```

The error message is different than the OP's error.
```
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'No def'n found for DefId { krate: 0, node: DefIndex(2) => Bar } in tcx.super_predicates', ../src/librustc/middle/ty/mod.rs:1897
```

**Comment by arielb1** [comment]
@bitavares
Sure. `lang_items` is unstable for a reason.

**Comment by bltavares** [comment]
@arielb1 Cool. I will add it to steveklabnik/glacier then.

**Comment by arielb1** [comment]
@bltavares 

It is unlikely to be fixed.

**Comment by Mark-Simulacrum** [comment]
This ICE is effectively caused by https://github.com/rust-lang/rust/issues/9307, so I'm going to close in favor of that.
