### ISSUE TITLE
Trait selection treats unboxed closure arguments as quasi-associated types

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#20872]
Currently trait selection treats unboxed closure arg/ret types as quasi-associated types. It's weird and hard to explain. It should change. I don't expect much impact although error messages might get less good; we should consider working on that.

**Comment by nikomatsakis** [comment]
prob makes sense to fix this together with #20871

**Comment by Nercury** [comment]
Can this also be a reason for #20770 (closures behaving as if they were the same, no matter the argument differences)?

**Comment by nikomatsakis** [comment]
@Nercury I think that [this comment](https://github.com/rust-lang/rust/issues/20770#issuecomment-69251499) is an accurate summary of the problem there.

**Comment by Nercury** [comment]
Ok, sorry, I am just completely lost :(

**Comment by doomsplayer** [comment]
will `call on self` error be solved by solving this issue?
e.g.
```rust
struct A;
impl Fn(isize,isize) for A {
  extern "rust-call" fn call(&self, args: (isize,isize)) {
    ....
  }
}
impl Fn(isize) for A {
  extern "rust-call" fn call(&self, args: (isize,)) {
    self(args.0, args.0) 
    // error: the type of this value must be known in this context
    // self(args.0 args.0)
    // error: cannot use call notation; the first type parameter for the function trait is neither a tuple nor unit [E0059]
  }
}
```
but UFCS is usable:
```rust
impl Fn(isize) for A {
  extern "rust-call" fn call(&self, args: (isize,)) {
    Fn::<(isize,isize)>::call(self, (args.0,args.0))
  }
}
```

**Comment by arielb1** [comment]
I don't think this is relevant today.

**Comment by steveklabnik** [comment]
Triage: Gonna trust @arielb1 and give this a close; feel free to re-open if this is wrong.
