### ISSUE TITLE
Make the tables in libunicode public

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#20884]

**Comment by nagisa** [comment]
I’m against it. Exposing the tables ties our public API to a specific Unicode version or specific way these tables are stored (e.g. we could find a more efficient way to store the data later or might want to add more data in a way incompatible to representation before). I’d much rather extend the set of functions to provide all the data we have in the tables.

**Comment by mahkoh** [comment]
How large are the tables when compiled?

**Comment by nagisa** [comment]
About 2MiB, I believe.

**Comment by mahkoh** [comment]
Duplicating this seems unacceptable. Mark them as unstable and don't reexport in libstd.
