### ISSUE TITLE
Distribute binary on Windows without libgcc_s_dw2-1.dll

### ISSUE THREAD

**Issue by caizixian** [rust-lang/rust#20908]
How to do that? Or will you add this feature?

**Comment by alexcrichton** [comment]
Could you elaborate on why you don't want this distributed? This is currently required by the rust compiler to run, and I believe we've had problems in the past about weird version mismatches between different versions of MSYS.

**Comment by caizixian** [comment]
I think just one binary file without dll is perfect. And I can just send one file to my server to deploy my web app.
With fully static build, I don't need to worry about different version of dll.

**Comment by vadimcn** [comment]
As long as you don't load any dlls that use DWARF stack unwinding in the process, you can link libgcc statically by passing `-Clink-args=-static-libgcc` to rustc.

**Comment by caizixian** [comment]
@vadimcn Thanks.
But I still wonder whether the static linking should be the default option.

**Comment by alexcrichton** [comment]
As @vadimcn we need to ship a dll for technical reasons, including the compiler supporting plugins. We also probably shouldn't be linking in a manner that precludes various operations (but allowing so still via an opt-in). As a result I'm going to close this issue.

**Comment by vadimcn** [comment]
@caizixian: this would break stack unwinding for everybody who uses dylib crates.  That would be a bad choice for default.

**Comment by vadimcn** [comment]
@caizixian: This would be a poor default choice, a it'd break stack unwinding for everybody who uses dylib crates.

**Comment by vadimcn** [comment]
@caizixian: This would be a poor default choice, a it'd break stack unwinding for everybody who uses dylib crates.
