### ISSUE TITLE
rustdoc: ?Sized bounds are missing for re-exports

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang/rust#20924]
For example:

```rust
// foo.rs
pub fn f<T: ?Sized>(_: &T) { }
```
```rust
// bar.rs
extern crate foo;

pub use foo::f;
```

The docs for `bar::f` will be missing the `?Sized` bound on T.

**Comment by tomjakubowski** [comment]
I have a fix for this but as usual, it created a whole host of new issues like `: Sized` appearing on every type parameter and the appearance of repeated bounds between the type parameter list and where clause which I'll fix up.

**Comment by kmcallister** [comment]
We have a lot of problems with things not propagating to re-exports. Perhaps we're handling re-exports in the wrong place?

**Comment by tomjakubowski** [comment]
rustdoc's normal operation is, broadly:

1. Run syntax checking, type checking, analysis, etc. on a crate.
2. Walk the crate's AST, cleaning it up as it goes into a form more palatable for rendering and caching information like trait impls.
3. Render the cleaned crate as HTML.

When it hits re-exported items though, it can't get ASTs for them, so it has to not only "inline" the document attribute for that item from the external crate but also clean an entirely different set of types (generally living in `rustc::middle::ty`), often undoing a lot of work done by the compiler to make something at least close to the original signature for the item.

I think the right, but maybe painful, thing to do would be to always build rustdocs from the compiled crate, and not from the AST, which would mean if a rustdoc feature is broken for re-exports it's also broken for "normal" items. It would also mean not re-implementing every feature twice, once for the AST and another for `ty` types.
