### ISSUE TITLE
FAQ links in error messages

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#2092]
On IRC we were discussing how, for complex errors, we ought to put a link to a FAQ in the error message.  Perhaps we could even embed the rust manual and print the relevant paragraph if you use `rustc --explain` or something.  

Some examples of errors that could benefit:

- `ret` disallowed from within sugared closure `{|| ... }`
- `;` required after a statement with non-unit type
- etc.

This of course would also entail *making* such a FAQ. :)

**Comment by steveklabnik** [comment]
This issue has been moved to the RFCs repo: rust-lang/rfcs#603
