### ISSUE TITLE
pretty identified should identify view items

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#20931]

**Comment by steveklabnik** [comment]
Can you add some more description here?

**Comment by nick29581** [comment]
pretty identified prints the node ids for nodes in the AST. Currently, it does not print them for view items, it should.

However, note that @eddyb has a PR somewhere for unifying view items with regular items which might fix this.

**Comment by goffrie** [comment]
I believe this is fixed now, thanks to the aforementioned PR, #20179.

**Comment by nrc** [comment]
Fixed!
