### ISSUE TITLE
Major compile-time perf regression in deep-vector2

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#20936]
This is an 8000-line array for stressing the compiler. I've been compiling it for several minutes now and it used to compile quickly.

**Comment by brson** [comment]
rustc 1.0.0-nightly (44a287e6e 2015-01-08 17:03:40 -0800)

**Comment by brson** [comment]
Nominating for visibility I guess.

**Comment by Aatch** [comment]
`-Z time-passes` places all of the time inside macro expansion. deep-vector, which is "only" 2000 lines spends 10 seconds in expansion. I wonder if the recent changes to macros are to blame.

**Comment by Aatch** [comment]
Just finished *trying* to compile deep-vector2, it spends about 5 minutes in expansion, then hits an LLVM assertion during trans!

**Comment by nick29581** [comment]
cc @kmcallister in case it is the macro reform stuff

**Comment by nikomatsakis** [comment]
Note that there is a `// ignore-test` annotation -- this may not be a recent regression.

**Comment by sfackler** [comment]
It was ignored when we removed `~[T]` vectors back last year. Doesn't look like an expansion regression, it's just always been slow: https://github.com/rust-lang/rust/commit/af79a5aa7da4f42fc0939a19f46fa73b894d6e9a

**Comment by pnkfelix** [comment]
moving to 1.1 milestone, leaving as P-high.

**Comment by birkenfeld** [comment]
The actual tests deep-vector.rs and deep-vector-2.rs have been removed from the tree in the meantime. Compile times are unchanged (here, 24s for deep-vector.rs).

**Comment by jonas-schievink** [comment]
I'm guessing this is also partially responsible for jonas-schievink/rustasm6502#4

**Comment by Mark-Simulacrum** [comment]
So testing these locally today, we see ~4 second expansion of deep-vector.rs and ~66 second expansion of deep-vector2.rs. Are we interested in returning these to the tree?

For reference, I retrieved them by doing the following:
```
git checkout 8ded99c0efa41a960560f8bc0f82c11ea96655d6 -- src/test/run-pass/deep-vector2.rs
```

**Comment by Mark-Simulacrum** [comment]
Expansion in both tests is now nearly instantaneous -- subsecond -- deep-vector takes 3 seconds to compile and deep-vector2 takes 10 seconds. Nominating for compiler team; if we want to readd these then doing so is E-easy, I can write up instructions.

**Comment by nikomatsakis** [comment]
How about we move the tests to perf.rust-lang.org?

**Comment by nikomatsakis** [comment]
triage: P-medium 

@Mark-Simulacrum or @arielb1  -- want to write up some mentoring instructions for adding tests to perf.rust-lang.org? Ideally, post them as a PR to the forge for future reference!

**Comment by Mark-Simulacrum** [comment]
Ah, I've filed https://github.com/rust-lang-nursery/rustc-perf-collector/issues/3 to track this over there as well but I'll leave this open for now.

This should be relatively straightforward to add. Copying https://github.com/rust-lang-nursery/rustc-perf-collector/tree/master/benchmarks/issue-32278-big-array-of-strings into a new folder for this issue seems like the right approach.

**Comment by Mark-Simulacrum** [comment]
@lqd wrote a test and I've merged it in, should go out in next deploy of perf.rlo. I'll have to edit the code some to allow introducing a test like this, but shouldn't be too hard. Will track in https://github.com/rust-lang-nursery/rustc-perf-collector/issues/3.
