### ISSUE TITLE
--pretty=expanded is too conservative on parens

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#20937]
It outputs uncompilable code
```
((y & CONT_MASK) as u32 << 6)
```

whereas it should output

```
(((y & CONT_MASK) as u32) << 6)
```

**Comment by steveklabnik** [comment]
So, I'm not sure what the original code was supposed to be here.

```
fn main() {
    y & CONT_MASK as u32 << 6;
}
```

itself fails to compile:

```
$ rustc --pretty=expanded hello.rs -Z unstable-options
hello.rs:2:29: 2:30 error: expected type, found `6`
hello.rs:2     y & CONT_MASK as u32 << 6;
                                       ^
```

**Comment by nagisa** [comment]
@steveklabnik the original code was `(((y & CONT_MASK) as u32) << 6)` (or perhaps had more parens). It now outputs properly parenthesized code, so this can be closed.
