### ISSUE TITLE
Manual impls of Foo for Foo should be illegal

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#20940]
A manual implementation of a trait for its own DST is currently legal:

```rust
trait Foo { fn gen<A>(&self) {} }

impl<'a> Foo for Foo+'a {}

fn main() {}
```

but shouldn't be. An object-safe `Foo` gives an ICE #20939, but should also be plain illegal.

**Comment by nikomatsakis** [comment]
I actually think that a manual impl for a *non-*object-safe trait is ok. It's the object-safe case that should give a better failure.

**Comment by nikomatsakis** [comment]
(The fix is presumably to modify coherence to be less focused on impls.)

**Comment by huonw** [comment]
Closing in favour of #20939 then.
