### ISSUE TITLE
the book should mention the difference between vectors and arrays.

### ISSUE THREAD

**Issue by bharadwaj6** [rust-lang/rust#20948]
I have found out that vectors are heap allocated whereas arrays are stack allocated, but this was not mentioned anywhere in the book.

**Comment by kmcallister** [comment]
Arrays are allocated directly within the containing structure.  So `Box<[u8; 3]>` is heap allocated, but `let x: [u8; 3] = ...` is stack-allocated like any `let` variable.

**Comment by bharadwaj6** [comment]
Let me summarize it here: So unless we box the array declaration, arrays would be allocated on the stack, whereas vectors would always be allocated on the heap (possibly because they are implemented as box types in `vec!`?). Correct me if I am wrong here.

**Comment by steveklabnik** [comment]
Yes.
