### ISSUE TITLE
Add an ignore function to Result to explicitly ignore it.

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#20949]

**Comment by Gankro** [comment]
Seems reasonable to me.

**Comment by bluss** [comment]
I use `.ok();` to do that. I guess that's pretty obscure code.

**Comment by alexcrichton** [comment]
Closing for reasons cited in the PR: https://github.com/rust-lang/rust/pull/21101#issuecomment-69815321

**Comment by zesterer** [comment]
Is this still potentially on the table for a future release? Seems like a useful method for `Result` to have.

**Comment by hasufell** [comment]
I don't know why this thread was closed. The comment in the PR doesn't say there definitely needs to be an RFC and it doesn't indicate this is *resolved* in any way, just that there needs to be further discussion.

**Comment by ruivieira** [comment]
Nim uses a `discard` statement for this effect: https://nim-lang.org/docs/tut1.html#procedures-discard-statement
