### ISSUE TITLE
64-bit Windows installer fails to install binaries

### ISSUE THREAD

**Issue by Fireforge** [rust-lang/rust#20950]
When using `rust-nightly-x86_64-pc-windows-gnu.exe`, the installer raises an error during installation:

![rust-install-error](https://cloud.githubusercontent.com/assets/2281867/5695941/69d10d9c-9987-11e4-9362-a76eba00a1aa.PNG)

If Ignore is selected, the same error message appears for `rustdoc.exe` and `gcc.exe`.
The 32-bit installer does not have this issues and installs properly.

Installation options selected: *Destination - C:\Rust, Full installation, Add to path - YES*
OS: *Windows 7, 64-bit*

**Comment by Gankro** [comment]
Is this still happening?

**Comment by Tobba** [comment]
It needs to be run as administrator, otherwise it fails miserably in this fashion.

**Comment by vadimcn** [comment]
@Fireforge, Windows installer was switched to not require admin rights not so long ago.   Unfortunately if you had previously had installed Rust as admin, uninstallation will fail, which is I believe what is happening above.  Please try uninstalling old nightly first via the Control Panel.   This should be a one-time operation, subsequent upgrades should work seamlessly.

**Comment by Gankro** [comment]
Sounds like this can be closed, then.
