### ISSUE TITLE
Rust Book CSS seems to be missing or incorrectly linked with the Rust version pulled using rustup.sh

### ISSUE THREAD

**Issue by mkeeler** [rust-lang/rust#20969]
I update my Rust install using rustup.sh. The html docs did get installed into /usr/local/share/doc/rust/html like I expected. Upon opening /usr/local/share/doc/rust/html/book/index.html the table of contents is displayed above the main page content instead of to the left like when I visit doc.rust-lang.org/book/index.html. I checked the html and it appears to reference rust-book.css (which I assume is responsible for putting the table of contents to the left). I then checked and rust-book.css does not exist in my /usr/local/share/doc/rust/html anywhere.

rustc 1.0.0-nightly (44a287e6e 2015-01-08 17:03:40 -0800)
binary: rustc
commit-hash: 44a287e6eb22ec3c2a687fc156813577464017f7
commit-date: 2015-01-08 17:03:40 -0800
host: x86_64-apple-darwin
release: 1.0.0-nightly

**Comment by mkeeler** [comment]
Upon adding a file /usr/local/share/doc/rust/html/book/rust-book.css with the contents of the STYLE string in src/rustbook/css.rs everything seems to work correctly now. So it would seem that however the docs are built just doesn't include the file.

**Comment by steveklabnik** [comment]
Hmm I thought @huonw fixed this

**Comment by huonw** [comment]
I did, but not in time for the 2015-01-08 nightly. Upgrading to the latest one should include it.

Thanks for filing!
