### ISSUE TITLE
following tutorial results in failed compile

### ISSUE THREAD

**Issue by lailoken503** [rust-lang/rust#20967]
First portion of the tutorial has us doing:

    extern crate semver;
    
    use semver::Version;
    
    fn main() {
        assert!(Version::parse("1.2.3") == Ok(Version {
            major: 1u,
            minor: 2u,
            patch: 3u,
            pre: vec!(),
            build: vec!(),
        }));
    
        println!("Versions compared successfully!");
    }

results in a failed compile:

    /home/clayton/rust/tutorial/hello_world/src/main.rs:7:16: 7:18 error: mismatched types: expected `u64`, found `usize` (expected u64, found usize)
    /home/clayton/rust/tutorial/hello_world/src/main.rs:7         major: 1u,
                                                                         ^~

Trying the suggested fix per compiler:

    /home/clayton/rust/tutorial/hello_world/src/main.rs:7:16: 7:19 error: mismatched types: expected `u64`, found `usize` (expected u64, found usize)
    /home/clayton/rust/tutorial/hello_world/src/main.rs:7         major: 1us,
                                                                         ^~~

However, per a post on [reddit/r/rust/](https://www.reddit.com/r/rust/comments/2s2v32/compile_error_while_doing_rust_tutorial/) it was suggested that I try u64 instead, which works.

**Comment by steveklabnik** [comment]
Yes, this should just be `u64`.

**Comment by tbu-** [comment]
You should be able to omit the integer suffix.

**Comment by lailoken503** [comment]
Tried without the prefix, it does work.

**Comment by steveklabnik** [comment]
This should be fixed by https://github.com/rust-lang/rust/pull/20895
