### ISSUE TITLE
Make the Rust Book a mobile-friendly site

### ISSUE THREAD

**Issue by Valloric** [rust-lang/rust#20961]
[Results from Google's Mobile-Friendly Test](https://www.google.com/webmasters/tools/mobile-friendly/?utm_source=psi&utm_medium=referral&utm_campaign=uxresults&url=http%3A%2F%2Fdoc.rust-lang.org%2Fnightly%2Fbook%2Fownership.html).

**Comment by huonw** [comment]
For future triage/comparison purposes, the current state is:

> Reasons this page is not mobile-friendly
> - Text too small to read
> - Links too close together
> - Mobile viewport not set

**Comment by Gankro** [comment]
@Valloric are you tackling this or just giving a heads up?

**Comment by Jojoshua** [comment]
It would also be nice if it was searchable.

**Comment by Valloric** [comment]
@Gankro Giving a heads-up. :)

**Comment by kmcallister** [comment]
Folding this into #20850.
