### ISSUE TITLE
Compiler error could suggest using an associated type for e.g. Iterator<T>

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang/rust#20977]
If you accidentally write a bound like:

``` rust
pub struct Foo<T, I: Iterator<T>> { /* ... */ }
```

The error message is:

```
err.rs:3:22: 3:33 error: wrong number of type arguments: expected 0, found 1
err.rs:3 pub struct Foo<T, I: Iterator<T>> { x: I }
                              ^~~~~~~~~~~
```

The compiler could be more helpful in these cases where a trait takes 0 arguments but has an associated type and suggest something like: `Iterator has an associated type. Did you mean: I: Iterator<Item=T>?`.

**Comment by nikomatsakis** [comment]
cc @Manishearth this could be a good place for a custom error attribute like the one you recently implemented

**Comment by Manishearth** [comment]
Ooh, this looks doable.

Unfortunately I don't see any opportunity for sharing much code here, but I can try to move some of the code out.

**Comment by frewsxcv** [comment]
Visiting for triage: nothing has changed here

[playpen link](http://is.gd/XNUtbw)

**Comment by birkenfeld** [comment]
Current situation: the original error hasn't changed, but we get a second one that complains about the missing `Item` associated type:
```
<anon>:1:25: 1:40 error: wrong number of type arguments: expected 0, found 1 [E0244]
<anon>:1 pub struct Foo { i: Box<Iterator<isize>> }
                                 ^~~~~~~~~~~~~~~
<anon>:1:25: 1:40 help: see the detailed explanation for E0244
<anon>:1:25: 1:40 error: the value of the associated type `Item` (from the trait `core::iter::Iterator`) must be specified [E0191]
<anon>:1 pub struct Foo { i: Box<Iterator<isize>> }
                                 ^~~~~~~~~~~~~~~
<anon>:1:25: 1:40 help: see the detailed explanation for E0191
```
... which should clear it up. (But probably not if the associated type has a default?)

**Comment by estebank** [comment]
`librustc_typeck/astconv.rs`, methods `create_substs_for_ast_path`, `check_type_argument_count` and `conv_object_ty_poly_trait_ref` will need to be changed to not emit both errors, but rather condense them into one:

```
error[E0191]: the value of the associated type `Item` (from the trait `std::iter::Iterator`) must be specified
 --> src/main.rs:1:25
  |
1 | pub struct Foo { i: Box<Iterator<isize>> }
  |                         ^^^^^^^^^-----^ missing associated type `Item` value, found 1 type argument instead
  |                                  |
  |                                  help: did you mean to set the associated type?: `Item = isize`

error: aborting due to previous error
```

Care should be taken when some type arguments _and_ associated items _are_ expected. In those case, it's probably better to keep the current output to avoid confusion with the tradeoff of verbosity.
