### ISSUE TITLE
Testsuite compile-fail error checking requires you to be very explicit

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#20987]
https://github.com/rust-lang/rust/pull/19870#discussion_r22771596 multi-line errors are being implemented and once enabled, a compile fail `mismatched types` error, for example, requires all 5 lines of errors to be matched.

It would be nice if you could opt out of this partially at least so you only need to match one error. It may be particularly confusing in places like [this](https://github.com/rust-lang/rust/commit/7b82a93be3798d9345cd459e251bcc571cf60a79#diff-d4fe3352687d95d42966e5d9cf386c30R13) (also below) which gives 2 errors on one line. This runs together to 10 lines of errors which must be annotated.

``` rust
fn main() { let a: bool = 1is; let b: isize = true; }
//~^ ERROR mismatched types
//~| expected `bool`
//~| found `isize`
//~| expected bool
//~| found isize
//~| ERROR mismatched types
//~| expected `isize`
//~| found `bool`
//~| expected isize
//~| found bool
```

cc @nick29581

**Comment by steveklabnik** [comment]
Triage: no changes here that I'm aware of.

**Comment by Mark-Simulacrum** [comment]
Still no changes I'm aware of, though UI tests in some cases are better for this. There has been some discussion about unifying compiler error testing, though I don't have a link. I'm not sure there's really a fix for this issue though, since checking all lines of the error is still necessary to make sure the error didn't change.

**Comment by steveklabnik** [comment]
>  I'm not sure there's really a fix for this issue though,

Given there's been two years without comment, I'm guessing that this is good enough. Closing.
