### ISSUE TITLE
Confusing language in http://doc.rust-lang.org/book/hello-world.html

### ISSUE THREAD

**Issue by mschauer** [rust-lang/rust#20993]
In "and because we aren't returning anything from this function, we've dropped THAT notation entirely" it is not clear what is referenced by "that".

**Comment by steveklabnik** [comment]
It's referring to the parentheses.  Can you think of a suggestion to improve the clarity?

**Comment by mschauer** [comment]
To the contents of the parentheses? I understood "because we arent returning anything" to point to dropping the declaration of the return type of the function after an  arrow "->".

**Comment by steveklabnik** [comment]
Yes, I meant the whole thing: `-> ()`.

**Comment by nagisa** [comment]
> These lines define a function in Rust. The main function is special: it's the beginning of every Rust program. The first line says "I'm declaring a function named main, which takes no arguments and returns nothing." If there were arguments, they would go inside the parentheses (( and )), and because we aren't returning anything from this function, we can omit the return type. We'll get to it later.
