### ISSUE TITLE
All of the old guide stubs have broken links to the new book

### ISSUE THREAD

**Issue by camjackson** [rust-lang/rust#21002]
Example: https://github.com/rust-lang/rust/blob/master/src/doc/guide-crates.md

I was going to fix them all myself, but I wasn't sure of the right change. It seems to me that all of the links that are to `book/topic.html` should be pointing to `trpl/topic.md`? Is that right?

**Comment by steveklabnik** [comment]
They link correctly when _generated_, but not when in GitHub. Can't make both work in every case, I don't think.
