### ISSUE TITLE
Write a TRPL chapter on inline assembly

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#21039]
Take what little we have on `asm!()` from "Unsafe Code", and greatly expand it.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#701
