### ISSUE TITLE
Stop using `extern crate` for plugins

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#21043]
Then we can skip linking the library and it won't be confusing.  Perhaps

```rust
#[plugin(...any metas...)] extern crate "my-lib" as foo;
```

would become

```rust
plugin!("my-lib" ...any TTs...);
```

There's no need for `as foo` because the library is not linked into the crate at all.  The common case is just

```rust
plugin!(regex_macros);
```

when the crate name is a valid identifier and there are no arguments.

This entails making the name `plugin!` special to the macro expander, since we need to locate plugins before we can load them.

**Comment by kmcallister** [comment]
`plugin!` would only be valid at module scope in the crate root.

**Comment by sfackler** [comment]
We could probably make `plugin!` a syntax extension itself by extending the API to allow extensions to load new extensions (inception!).

**Comment by XMPPwocky** [comment]
Why can't plugin! be a simple macro that expands to #[no_link] #[plugin] extern crate $name; ? Are macros not expanded until after plugins run?

**Comment by sfackler** [comment]
@XMPPwocky the idea for `plugin!` is that `#[no_link]` will no longer be a thing at all. `extern crate`'s currently overloaded to mean both "make the contents of this crate available to my program" and "load this into the compiler as a plugin".

**Comment by kmcallister** [comment]
> Are macros not expanded until after plugins run?

Correct.  Plugin loading, plugin registration, and syntax expansion happen in distinct stages.  This is needed due to the libsyntax / librustc split, and seems like a clean design generally.  But it does entail collecting plugins to load before we've done any macro expansion at all.

**Comment by nagisa** [comment]
#![plugin="regex_macros"] instead. Fits with `-Z plugin=regex_macros` or something better.

**Comment by kmcallister** [comment]
They they have to go at the top of your crate root file, but that seems acceptable and maybe even beneficial.  There's a sort of analogy with `#![feature]` enabling built-in experimental features and `#![plugin]` loading new ones.  Perhaps the syntax should be

```rust
#![plugin(regex_macros, foobar(...any metas...))]
```

which (like `#![feature]`) could also be split up as
```rust
#![plugin(regex_macros)]
#![plugin(foobar(...any metas...))]
```

It's less clear how to deal with crate names that aren't valid identifiers, but I'm fine simply disallowing that for now.

**Comment by daboross** [comment]
A syntax like `#![plugin]` might be a bit confusing though, since plugins still need to be added as cargo dependencies as well - just noting this.
