### ISSUE TITLE
Rust book isn't mobile friendly

### ISSUE THREAD

**Issue by G4MR** [rust-lang/rust#21057]
Was using my nexus 7 which uses chrome by default and the content would need to be horizontally scrolled to see parts of the content.  OperaMini looked worse as well so thought I'd bring it up.

**Comment by sfaxon** [comment]
This has been mentioned on [Ticket 20850](https://github.com/rust-lang/rust/issues/20850).

**Comment by kmcallister** [comment]
Folding this into #20850.
