### ISSUE TITLE
Unexpected behavior of mem::transmute(), [E0139]

### ISSUE THREAD

**Issue by qrlpx** [rust-lang/rust#21051]
If not relaxing this restriction, at least documenting/justifing it somewhere would be appreciated.

Codesample:
```
use std::{raw, mem};

fn add_callback<CB: FnOnce()>(cb: CB){
    unsafe {
        let closure: raw::TraitObject = mem::transmute(cb);
    }
}

fn main(){}
```
Output:
```
<anon>:5:41: 5:55 error: cannot transmute to or from a type that contains type parameters in its interior [E0139]
<anon>:5         let closure: raw::TraitObject = mem::transmute(cb);
```

Using for example ptr::read and mem::forget, we can still achieve the expected behaivor:
```
use std::{raw, ptr, mem};

fn add_callback<CB: FnOnce()>(cb: CB){
    unsafe {
        let closure: raw::TraitObject = ptr::read(&cb as *const CB as *const raw::TraitObject);
        mem::forget(cb);
    }
}

fn main(){}
```
Version:
```rustc 1.0.0-nightly (44a287e6e 2015-01-08 17:03:40 -0800)```

**Comment by Diggsey** [comment]
Surely in your example, CB could be any type which implements FnOnce - in most cases such a type will not be a trait object, and so won't have the same size and alignment as "raw::TraitObject", which is what "transmute" requires.

If you change the code to this:

    fn add_callback(cb: &FnOnce()){
        unsafe {
            let closure: raw::TraitObject = mem::transmute(cb);
        }
    }

Then 'cb' _will_ be a trait object and so the transmute will work.

**Comment by qrlpx** [comment]
Oh. Seems like I got confused by the error message (and also the switch to unboxed closures). 
Nvm then, thanks for you answer.
