### ISSUE TITLE
Can’t implement Trait for &'a Trait when Trait is 'static

### ISSUE THREAD

**Issue by chris-morgan** [rust-lang/rust#21074]
Minimal example:

```rust
trait A: 'static { }
impl<'a> A for &'a A { }
fn main() { }
```

(`&'a A` can be written `&'a (A + 'static)` with the same outcome.)

```text
<anon>:2:1: 2:25 error: declared lifetime bound not satisfied
<anon>:2 impl<'a> A for &'a A { }
         ^~~~~~~~~~~~~~~~~~~~~~~~
<anon>:2:1: 2:25 note: lifetime parameter instantiated with the lifetime 'a as defined on the impl at 2:0
<anon>:2 impl<'a> A for &'a A { }
         ^~~~~~~~~~~~~~~~~~~~~~~~
note: but lifetime parameter must outlive the static lifetime
error: aborting due to previous error
```

Sure, `A` itself must be `'static`, but that shouldn’t prevent the creation of a non-static *reference* to `A`.

**Comment by huonw** [comment]
cc @nikomatsakis, seems that the constraints may be backwards? (The compiler should be checking that `'static` outlives `'a`?)

**Comment by pnkfelix** [comment]
I am not sure this is a bug.  cc @nikomatsakis   removing nomination tag.

**Comment by huonw** [comment]
Looking at it now, I agree it's not a bug: the `'static` bound on `A` means anything you implement `A` *for* needs to satisfy `'static`, but `&'a A` does not, so the problem is writing `impl<'a> A for &'a ...`, not just writing `&'a A` itself.

**Comment by nikomatsakis** [comment]
Right, not a bug.
