### ISSUE TITLE
AdditiveIterator and MultiplicativeIterator should be implemented on all iterators with Add/Mul items

### ISSUE THREAD

**Issue by Tobba** [rust-lang/rust#21094]
Currently both AdditiveIterator and MultiplicativeIterator are implemented on specifically all iterators over the base integer types. This is strange as they could be generically implemented over all iterators with items implementing Add/Mul. Moreover, the concepts of summation and products aren't exactly limited to iterators (although these traits actually have no requirement of being implemented on iterators).

**Comment by brson** [comment]
Traits won't be stablized for 1.0

**Comment by bluss** [comment]
Needs either a Zero/Identity element or a partial function (i.e. return None if there are no elements). What's there now is very convenient albeit not generic.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#696
