### ISSUE TITLE
rustdoc should show associated types in `impl` documentation

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#21092]
For example, the `std::ops::Index` trait has an associated `Output` type. Of course, that type is potentially different for each `impl` of the trait. `impl` are documented at http://localhost/rust/std/ops/trait.Index.html#implementors , but there is apparently now way to know what is the `Output` type for a given implementation. (Other than finding the source code, which is not necessarily easy because of #15744.)

**Comment by tomjakubowski** [comment]
You should be able (for most impls at least) to follow the link for the Self type on the impl to see the associated types. I agree it would be nice to have them listed in the Trait Implementations section, though I can't think of a pleasant way to show it.

**Comment by SimonSapin** [comment]
I didn’t know that, thanks. Though there is apparently another bug for re-exported items (like in the std facade) similar to #20203:

http://doc.rust-lang.org/core/slice/struct.Iter.html#implementations
> ```rust
> impl<'a, T> Index<Range<usize>> for Iter<'a, T>
>   type Output = [T]
>   fn index(&self, index: &Range<usize>) -> &[T]
> ```

http://doc.rust-lang.org/std/slice/struct.Iter.html#implementations
> ```rust
> impl<'a, T> Index<Range<usize>> for Iter<'a, T>
>   fn index(&self, index: &Range<usize>) -> &[T]
>   type Output
> ```

**Comment by tomjakubowski** [comment]
I believe that's #20727

**Comment by tomjakubowski** [comment]
So the actual problem here is #21348. For non-inlined impls there's no issue.

**Comment by tomjakubowski** [comment]
Related to #21348 perhaps (although this is about "trait implementations" on the *trait*'s page, not the *implementor*'s.)

**Comment by alexcrichton** [comment]
This appears to have been fixed at some point, yay!

**Comment by alexcrichton** [comment]
Ah but I'll add a test for it.
