### ISSUE TITLE
libsyntax contains many uses of uint

### ISSUE THREAD

**Issue by gchp** [rust-lang/rust#21095]
I've been going through `syntax::ast` recently and found that there are still quite a few uses of `uint`. Not just the type name, but its used in a good few places in method names too.

A quick grep tells me there's 246 uses of it in `libsyntax`. Are there plans to remove/rename these uses? I'd be happy to go through it if someone isn't already on the case!

**Comment by rylev** [comment]
@pshc and I are taking a stab at this.

**Comment by alexcrichton** [comment]
Fixed in #21340
