### ISSUE TITLE
Documentation: quick reference

### ISSUE THREAD

**Issue by schuyler1d** [rust-lang/rust#21112]
Something to think about in terms of the developing suite of documentation is a quick-reference.  In python, I use this all the time:
http://rgruet.free.fr/PQR27/PQR2.7.html

Maybe this is more 'for those that live in non-IDE editors', but even as a more advanced user of python, I find it's still a very useful doc -- basically a one-pager of built-in types/syntax/structure and important standard libraries (and maybe even beyond since some important ones will be out of the std library).  

Specifically, it aims for compactness rather than complete explanations -- think of it as for someone that has read through the doc and is a beginner/mid-level experience programmer, but 'just can't remember what the method on String is, or "what's the exact command line argument?"

Not sure if it's possible to auto-generate this kind of thing -- maybe a 'combine all the docs' without the explanation strings?

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#693
