### ISSUE TITLE
Add .msi installer for windows

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#21118]
There's an in-progress PR for this https://github.com/rust-lang/rust-packaging/pull/2. Requires updated the windows vms.

Nominating because its something I'm working on.

**Comment by caizixian** [comment]
I think MSI installer is not necessary.

**Comment by Nercury** [comment]
@caizixian I would disagree - it is very good to have - requires less privileges to install!

**Comment by brson** [comment]
@caizixian My understanding is that .msi is something of a standard packaging format for windows and should be prefered to other formats.

The above referenced patch has landed but the bots are not building it yet. The VM needs to be updated to carry the needed tools, and I think more review is probably required with i mind toward sxs installation at least.

**Comment by brson** [comment]
cc @vadimcn @gentoo90

**Comment by retep998** [comment]
Using .msi also means people would be able to install Rust through the command line, which would be very useful for people trying to use continuous integration on Windows.

**Comment by brson** [comment]
More progress https://github.com/rust-lang/rust-packaging/pull/9. Need to install wix on the windows bots and adjust rust-buildbot to pass '--msi' to `package-rust` next.

**Comment by brson** [comment]
VMs updated and bots restarted to pass the `--msi` flag.

**Comment by sinistersnare** [comment]
MSI installers currently run for windows. should this be closed?

**Comment by steveklabnik** [comment]
Yes!
