### ISSUE TITLE
i18n for documentation & website

### ISSUE THREAD

**Issue by caizixian** [rust-lang/rust#21129]
Maybe we can consider puting HTML and Markdown file on the Transifex platform for foreigners to translate.
Is there any official tool to do this?
@alexcrichton @steveklabnik @brson

**Comment by steveklabnik** [comment]
We previously had some things, but they were removed, as they weren't really being used. I'm not sure if this isn't something we want to wait until post 1.0 to do.

**Comment by caizixian** [comment]
OK. Will it be released after 1.0.0 stable?

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#695
