### ISSUE TITLE
-emit dep-info doesn't work with -Z no-analysis

### ISSUE THREAD

**Issue by SiegeLord** [rust-lang/rust#21130]
The whole reason why no-analysis was added was so that --dep-info could be faster, see https://github.com/rust-lang/rust/pull/11155 .

Now, -Z no-analysis exits too early.

**Comment by SiegeLord** [comment]
This was broken by https://github.com/rust-lang/rust/pull/20917.

**Comment by nick29581** [comment]
Sorry about that, easy enough to fix, I'll have a patch tomorrow.
