### ISSUE TITLE
rustdoc: render references to associated type using short form when possible

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#21145]
Currently, rustdoc renders the `Index` trait as:

```rust
pub trait Index<Index> where Index: ?Sized {
    type Output;
    fn index(&'a self, index: &Index) -> &'a <Self as Index<Index>>::Output;
}
```

Ideally it would render as

```rust
pub trait Index<Index> where Index: ?Sized {
    type Output;
    fn index(&'a self, index: &Index) -> &'a Self::Output;
}
```

and eventually, when the scoping rules for associated items are settled, it could skip even the `Self::`

**Comment by aturon** [comment]
cc @tomjakubowski

**Comment by tomjakubowski** [comment]
Hmmm yep. We need to either pass the trait's type down when `clean`ing its methods and the types in the methods, or just tidy up any `QPath`s afterwards.

**Comment by tomjakubowski** [comment]
So this particular bug only happens for cross-crate inlined traits. But it's broken in a different way in core, where the `Self` is missing from the type entirely!

```rust
pub trait Index<Index: ?Sized> {
    type Output: ?Sized;

    fn index<'a>(&'a self, index: &Index) -> &'a Output;
}
```
