### ISSUE TITLE
`include!` is a smell and should be made obsolete for code-generating cargo packages

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#21147]
In particular, we should somehow allow using `OUT_DIR` in the `#[path]` of a `mod foo`, to allow parsing to proceed normally. Since `include!` doesn't do textual inclusion, but rather AST splicing, and is rather blind, it doesn't pass in the correct context to allow things like outer attributes to work in `include!`'d code, even if it's `mod foo { include!("foo.rs"); }`. It's conservatively correct, but conservatively obnoxious.

**Comment by huonw** [comment]
This is related to/might be fixed by https://github.com/rust-lang/rust/issues/18849 (in fact, it is the motivating example in that issue).

@alexcrichton, you may have thoughts about this, especially experience with cargo, and what cargo needs.

**Comment by steveklabnik** [comment]
Triage: regardless of its smelliness, today it's in stable, so it has to stay.

Given the lack of other discussion, I'm going to close this one.
