### ISSUE TITLE
Deprecate, then remove the ItemModifier and ItemDecorator syntax extension traits

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#21155]
In favour of the more flexible MultiItemModifer and (in the future, hopefully, see #21154) MultiItemDecorator. We should add some convenience methods to make these as ergonomic to use in the item case as the current interfaces.

**Comment by nham** [comment]
Triage bump: Seems these were deprecated about a month ago.

**Comment by steveklabnik** [comment]
Triage: this appears to be done. Closing!
