### ISSUE TITLE
Some #[derive(..)] extensions are still using method calls

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#21163]
- `PartialOrd` (`lt`, `ge`, etc methods) on enums (see `some_ordering_collapsed` in libsyntax/ext/deriving/cmp/ord.rs)
- Same issue with `Ord` (`cmp` method) and enums
- There is `write_fmt` method call in the expansion of `#[derive(Show)]`, but I don't think it's an issue.
- There are more method calls in `#[derive(Decodable, Encodable]`, but those two are deprecated. We should audit `#[derive(RustcEncodable, RustcDecodable)]` though

`Ord` and `PartialOrd` should use UFCS to avoid issues like #21160

cc @alexcrichton @apasel422

**Comment by alexcrichton** [comment]
The `write_fmt` call is fine (it's on a known structure, not a type parameter) and the `RustcEncodable` and `RustcDecodable` are along the same lines (they're done on a generic to the method), so I think they're fine.

The `Ord`/`PartialOrd` bits sound bad though!

**Comment by japaric** [comment]
On a closer look, both `Ord` and `PartialOrd` apply the method calls on the "tag" of the variants, which have type `usize` (hmm, why are we using `usize` for the tag values?). For example:

``` rust
#[derive(PartialEq, PartialOrd)]
enum Foo {
    Bar(i8),
    Baz,
}
```

The relevant bit of the expansion:

``` rust
#[inline]
fn ge(&self, __arg_0: &Foo) -> ::bool {
    match (&*self, &*__arg_0) {
        (&Foo::Bar(ref __self_0), &Foo::Bar(ref __arg_1_0)) =>
        (*__self_0) > (*__arg_1_0) ||
            !((*__arg_1_0) > (*__self_0)) && true,
        (&Foo::Baz, &Foo::Baz) => true,
        _ => {
            let __self_vi =  // has type `usize`
                match *self { Foo::Bar(..) => 0us, Foo::Baz(..) => 1us, };
            let __arg_1_vi =  // has type `usize`
                match *__arg_0 {
                    Foo::Bar(..) => 0us,
                    Foo::Baz(..) => 1us,
                };
            __self_vi.ge(&__arg_1_vi)  // <-- method call
        }
    }
}
```

So, I think we are actually safe!

**Comment by alexcrichton** [comment]
Nice catch! In that case I'm removing the nominated tag. We should probably still do this, but for now we're fine.

**Comment by apasel422** [comment]
I don't think there's anything left to be done here. `PartialOrd` and `PartialEq` expand to the operators themselves, and `Ord` uses `Ord::cmp`. `Eq`'s expansion uses non-UFCS syntax for `assert_receiver_is_total_eq`, but since `Ord: Eq`, I don't think this is an issue.
