### ISSUE TITLE
Error parsing "{expr} as {type} < {expr}"

### ISSUE THREAD

**Issue by mindless2112** [rust-lang/rust#21175]
Using the Rust 1.0 alpha (and probably current nightly builds also) following produces the error "3:30: 3:31 error: expected type, found \`1`".  That is, the first statement parses while the second statement does not.

```rust
fn main() {
    println!("{}", 0 as (i8) < 1);
    println!("{}", 0 as i8 < 1);
}
```

In at least some earlier versions of Rust, this would compile.  It is unclear if this change was intended and whether the code is expected to not compile.

**Comment by lifthrasiir** [comment]
This is because the type can be followed by type parameters: `Box::new(32u32) as Box<std::fmt::Show>` is valid.

**Comment by alexcrichton** [comment]
Yes as @lifthrasiir this was indeed intended, but thanks for the issue!
