### ISSUE TITLE
Better search for keywords and programming terms

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#21171]
There should be a good way to search the docs for a specific keyword. For example, go [the book](http://doc.rust-lang.org/book) or [reference](http://doc.rust-lang.org/reference.html) or [rustbyexample](http://rustbyexample.com/) and try to search for documentation on using the `type` keyword. I'm not sure if it exists or not. It's difficult to decide because they're so many hits.

I'm not sure how to fix this...searching programming terms on any search engine is usually awful...

**Comment by kmcallister** [comment]
That sounds great. We should have a single integrated search box for the Book, the Reference, all the API docs, and everything else.

cc @steveklabnik

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#692
