### ISSUE TITLE
Bitv/BitvSet's #[stable] mismatches collections reform RFC

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#21193]
@nikomatsakis noticed that `Bitv` and `BitvSet` are marked `#[stable]` but [collections reform 2](https://github.com/rust-lang/rfcs/blob/master/text/0509-collections-reform-part-2.md) says:

> Unstable: Bitv, BitvSet, VecMap

(Maybe there was further discussion not in the RFC, maybe not.)

cc @Gankro, @aturon

**Comment by Gankro** [comment]
Definitely an error.
