### ISSUE TITLE
Remove uses of `usize` that are not pointer-related from the `Int` trait

### ISSUE THREAD

**Issue by tbu-** [rust-lang/rust#21209]
The signatures have some integers in their signature that at least need reasoning for `usize`, but should probably be changed to a different integer type, e.g.

    fn trailing_zeros(self) -> usize;

**Comment by tbu-** [comment]
Possible pull request: https://github.com/rust-lang/rust/pull/20211. If the change like in the pull request is desired, I'll rebase it.

**Comment by steveklabnik** [comment]
Since this is just part of https://github.com/rust-lang/rust/issues/22240, i'm giving it a close.
