### ISSUE TITLE
Don't publish API docs for crates other than std on beta or stable channels

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#21219]
These crates can't be used so let's not tease people.

**Comment by brson** [comment]
Nominating. Polish issue.

**Comment by tomjakubowski** [comment]
This really puts the pressure on to fix all the cross-crate rustdoc bugs! :sweat_smile:

**Comment by brson** [comment]
cc https://github.com/rust-lang/rust/issues/21297

**Comment by pnkfelix** [comment]
closing in favor of #21297.
