### ISSUE TITLE
API docs have broken links for contents under liballoc

### ISSUE THREAD

**Issue by bombless** [rust-lang/rust#21226]
For example,
[struct Weak](http://doc.rust-lang.org/std/rc/struct.Weak.html)
[struct Rc](http://doc.rust-lang.org/std/rc/struct.Rc.html)
[struct Box](http://doc.rust-lang.org/std/boxed/struct.Box.html)
The [src] link at the top-right corner on these pages redirect to 404 page.

Other pages like [enum Option](http://doc.rust-lang.org/std/option/enum.Option.html) seems to be fine.

**Comment by bombless** [comment]
cc @steveklabnik

**Comment by steveklabnik** [comment]
I think there are other bugs open for this, but I'm not sure.

**Comment by lifthrasiir** [comment]
Duplicate of #15309, as @steveklabnik said.
