### ISSUE TITLE
compile-test fails to detect extranous errors on windows

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#21228]
the problem is in this function: https://github.com/rust-lang/rust/blob/master/src/compiletest/runtest.rs#L1009

since windows-paths contain a colon, finding the error/warning through counting colons is not the way to go.

i need this fixed, so i'm fixing it.
should i use regex or simply check if the line starts with the testfile-name, and skip those chars before counting colons?

**Comment by alexcrichton** [comment]
I believe this was fixed in https://github.com/rust-lang/rust/pull/27974
