### ISSUE TITLE
Add machine-readable dist index

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#21241]
For scripts to discover the contents of the dist archives we probably need an index in a standard markdown format. Since all of my scripts are bourne shell I'd prefer it be something more easily parsable than json, or at least if it's json that it be formatted in a way that can be grepped easily.

**Comment by nagisa** [comment]
cc me

**Comment by brson** [comment]
Should probably include a metadata version number in it for future proofing.

**Comment by Aatch** [comment]
For something this simple, JSON is probably overkill. Some delimiter-separated value is probably the best way.

**Comment by brson** [comment]
This is done.
