### ISSUE TITLE
error: internal compiler error: unexpected panic

### ISSUE THREAD

**Issue by kompass** [rust-lang/rust#21253]
Hello, I have a compiler error (possible that this is due to my code, but still a compiler bug) !

You can see here the error :

```
Compiling inb4command v0.0.1 (file:///home/nicolas/workspace/inb4command)
src/readline.rs:38:15: 38:16 error: numeric character escape is too short
src/readline.rs:38 		write(2, "\x7");
                   		            ^
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'index 2 and/or 4 in `\x7` do not lie on character boundary', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/str/mod.rs:1244


Could not compile `inb4command`.

To learn more, run the command again with --verbose.

```

You can see the failing code here :

```

use posix::termios::{termios, tcgetattr, tcsetattr, VMIN, VTIME, TCSAFLUSH, OPOST, CS8};
use posix::termios::{BRKINT, ICRNL, INPCK, ISTRIP, IXON, ECHO, ICANON, IEXTEN, ISIG};
use posix::unistd::{isatty, write};
use util::bitinv;

struct TermState {
	rawmode: bool,
	orig_state: termios,
}

impl TermState {
	fn new() -> Option<TermState> {
		if isatty(0) == 1 {
			let mut state = termios::new();
			tcgetattr(0, &mut state);
			Some(TermState {rawmode: false, orig_state: state})
		}
		else {
			None
		}
	}

	fn enable_rawmode(&self) {
		if self.rawmode == false {
			let mut raw = self.orig_state;
			raw.c_iflag &= bitinv(BRKINT | ICRNL | INPCK | ISTRIP | IXON);
			raw.c_oflag &= bitinv(OPOST);
			raw.c_cflag |= (CS8);
			raw.c_lflag &= bitinv(ECHO | ICANON | IEXTEN | ISIG);
			raw.c_cc[VMIN] = 1;
			raw.c_cc[VTIME] = 0;

			tcsetattr(0, TCSAFLUSH, &raw);
		}
	}

	fn beep(&self) {
		write(2, "\x7");
	}
}

```

Good luck for the resolution, I am at your disposal !

**Comment by kompass** [comment]
The crate posix can be found here : https://github.com/mahkoh/posix.rs

But I do not think that this is related.

**Comment by kompass** [comment]
stack backtrace:
   1:     0x7f9c2b19fed0 - sys::backtrace::write::hf251c2373d8c39658Rt
   2:     0x7f9c2b1c18b0 - failure::on_fail::h2ff2bf5f19ce9580S5z
   3:     0x7f9c2b1307b0 - rt::unwind::begin_unwind_inner::h639cf27e708a803eKKz
   4:     0x7f9c2b1312e0 - rt::unwind::begin_unwind_fmt::hb8a8939a6abb5d5chJz
   5:     0x7f9c2b1c1710 - rust_begin_unwind
   6:     0x7f9c2b20a260 - panicking::panic_fmt::h4359f3a82e34f47bvym
   7:     0x7f9c2b213c40 - str::slice_error_fail::h3baf6383ce290c077ju
   8:     0x7f9c25fa6440 - parse::char_lit::esc::h965672d04b5e5d3d0EW
   9:     0x7f9c25f5b250 - parse::char_lit::h4e0ec7364114c503TBW
  10:     0x7f9c25f5cb50 - parse::str_lit::hd73ce126073db9dehHW
  11:     0x7f9c25f5a700 - parse::parser::Parser<'a>::lit_from_token::ha49232f53bf21b20PTK
  12:     0x7f9c25f5ee50 - parse::parser::Parser<'a>::parse_lit::h4b2d7820f8311462TXK
  13:     0x7f9c25f61770 - parse::parser::Parser<'a>::parse_bottom_expr::hf64d56e417f744daXgL
  14:     0x7f9c25f66d80 - parse::parser::Parser<'a>::parse_dot_or_call_expr::h84437f1d06e5ef03UyL
  15:     0x7f9c25f69d40 - parse::parser::Parser<'a>::parse_prefix_expr::h6edb25949ecb3cd5CVL
  16:     0x7f9c25f6a6f0 - parse::parser::Parser<'a>::parse_binops::hf16ce0bccac23fc1X1L
  17:     0x7f9c25f6add0 - parse::parser::Parser<'a>::parse_assign_expr::hcfbde9faf831f16ew6L
  18:     0x7f9c25f65190 - parse::parser::Parser<'a>::parse_seq_to_before_end::h14311017354036785428
  19:     0x7f9c25f66dd0 - parse::parser::Parser<'a>::parse_dot_or_call_expr_with::h0f059e4051b42472czL
  20:     0x7f9c25f66d80 - parse::parser::Parser<'a>::parse_dot_or_call_expr::h84437f1d06e5ef03UyL
  21:     0x7f9c25f69d40 - parse::parser::Parser<'a>::parse_prefix_expr::h6edb25949ecb3cd5CVL
  22:     0x7f9c25f6a6f0 - parse::parser::Parser<'a>::parse_binops::hf16ce0bccac23fc1X1L
  23:     0x7f9c25f6add0 - parse::parser::Parser<'a>::parse_assign_expr::hcfbde9faf831f16ew6L
  24:     0x7f9c25f6cc90 - parse::parser::Parser<'a>::parse_stmt::h77197fc8f9e65ffbqOM
  25:     0x7f9c25f766d0 - parse::parser::Parser<'a>::parse_block_tail_::hfbd44ef9ad4a1cc6j0M
  26:     0x7f9c25f53e80 - parse::parser::Parser<'a>::parse_inner_attrs_and_block::h0c505f6436a47243DYM
  27:     0x7f9c25f7d340 - parse::parser::Parser<'a>::parse_method::h3ace62229d5e77fe4IN
  28:     0x7f9c25f81070 - parse::parser::Parser<'a>::parse_item_impl::h3753343a4879fb5eHQN
  29:     0x7f9c25f6ef60 - parse::parser::Parser<'a>::parse_item_or_view_item::h648d99bfbe032cccQHO
  30:     0x7f9c25f78790 - parse::parser::Parser<'a>::parse_items_and_view_items::h2500604f21bbf6dftbP
  31:     0x7f9c25f83bc0 - parse::parser::Parser<'a>::parse_mod_items::h26998e83067a973cW5N
  32:     0x7f9c25f85380 - parse::parser::Parser<'a>::eval_src_mod::ha686d078424a86430dO
  33:     0x7f9c25f6ef60 - parse::parser::Parser<'a>::parse_item_or_view_item::h648d99bfbe032cccQHO
  34:     0x7f9c25f78790 - parse::parser::Parser<'a>::parse_items_and_view_items::h2500604f21bbf6dftbP
  35:     0x7f9c25f83bc0 - parse::parser::Parser<'a>::parse_mod_items::h26998e83067a973cW5N
  36:     0x7f9c25f8f2b0 - parse::parser::Parser<'a>::parse_crate_mod::h1388f3561d86fa12PgP
  37:     0x7f9c25fa28e0 - parse::parse_crate_from_file::h437d5b500a1a3ce9XkW
  38:     0x7f9c2b7029a0 - driver::phase_1_parse_input::unboxed_closure.15014
  39:     0x7f9c2b6e2c40 - driver::phase_1_parse_input::h254b67e4ab39dfad6pa
  40:     0x7f9c2b6dfdd0 - driver::compile_input::haa1e0a1302dab243Aba
  41:     0x7f9c2b7a16c0 - run_compiler::h385e1ee7d7e284bee5b
  42:     0x7f9c2b79fe30 - thunk::F.Invoke<A, R>::invoke::h17064898529926817575
  43:     0x7f9c2b79ed90 - rt::unwind::try::try_fn::h13784017587596973898
  44:     0x7f9c2b228a60 - rust_try_inner
  45:     0x7f9c2b228a50 - rust_try
  46:     0x7f9c2b79f040 - thunk::F.Invoke<A, R>::invoke::h10896099676476614463
  47:     0x7f9c2b1af550 - sys::thread::thread_start::h9cd6def278b6034eVJw
  48:     0x7f9c25753000 - start_thread
  49:     0x7f9c2add9039 - __clone
  50:                0x0 - <unknown>

**Comment by kompass** [comment]
I don't have the bug if I replace "\x7" by "\x07" (if I fix the bug in my code, basically), but the compiler don't have to fail at this human error, I think.

**Comment by jdm** [comment]
What is the output of `rustc --version`?

**Comment by jdm** [comment]
Theoretically we have tests for this: http://mxr.mozilla.org/rust/source/src/test/compile-fail/lex-bad-char-literals.rs#22

**Comment by jdm** [comment]
The problem is the code in http://mxr.mozilla.org/rust/source/src/libsyntax/parse/mod.rs#421 which passes a length of 4 to the `esc` function, rather than the actual length of the string. The same fix should be applied to the `U` branch, too.

**Comment by svkurowski** [comment]
I can't reproduce this in current master (3e6eaeb6) and neither in 1.0.0-alpha.

    fn main() {
        println!("{}", "\x7");
    }

Output:

    main.rs:2:21: 2:22 error: numeric character escape is too short
    main.rs:2   println!("{}", "\x7");
                                                        ^
    error: aborting due to previous error

The lexer is supposed to catch problems where the escape sequence is too short (see http://mxr.mozilla.org/rust/source/src/libsyntax/parse/lexer/mod.rs#742).

@jdm should we still fix the code you linked to or just rely on the fact that the lexer should catch possible errors?

**Comment by kompass** [comment]
rustc 1.0.0-nightly (170c4399e 2015-01-14 00:41:55 +0000)

**Comment by jdm** [comment]
@kompass Can you still reproduce the problem with a more recent version of the compiler?

**Comment by nagisa** [comment]
Can’t reproduce this either. I think this can safely be closed.
