### ISSUE TITLE
In collections documentation, headings like "Use a Vec when" should link to the corresponding collection

### ISSUE THREAD

**Issue by nstoddard** [rust-lang/rust#21260]
In the collections documentation, there's a section about how to choose which collection to use, along with headings such as "Use a `Vec` when:". A couple times I've clicked those headings, hoping to be taken to the documentation for the specified collection, but instead it just scrolls so the heading at the top of the page. Is it possible for those headings to link directly to the collection's documentation (e.g. http://doc.rust-lang.org/std/vec/struct.Vec.html)?

**Comment by steveklabnik** [comment]
I'm not sure what the right thing is here. Headings are links so that you can link to them. @Gankro ?

**Comment by estsauver** [comment]
I think when @nstoddard says "headings" he means the inline code quoting. For [example](http://doc.rust-lang.org/nightly/std/collections/), 

//! To get this out of the way: you should probably just use `Vec` or `HashMap`. 

Vec and HashMap would be the things that are quoted. I don't have a clue how easy that would be.

**Comment by Gankro** [comment]
Unfortunately linking types or modules amounts to finding the URL happen to be at, and hard-coding that into the doc. Doable, but awful.

**Comment by steveklabnik** [comment]
Ah yes. That's not really do-able right now. If we did it all manually, it'd just break if we ever get it done automatically. And it's super error-prone.

So yes, while this is a weak point, there's not a ton we can do. Sorry about that!
