### ISSUE TITLE
LLVM assertion error  (llvm/lib/IR/Instructions.cpp:1086)

### ISSUE THREAD

**Issue by Ericson2314** [rust-lang/rust#21275]
Sorry, but I have no idea how to reduce this.

```shell
git clone https://github.com/RustOS-Fork-Holding-Ground/rust-net
cd rust-net/network
cargo build
```
```
Compiling rust-net-network v0.0.1 (file:///winhome/John/Code/git/rust-net/network)
rustc: /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/lib/IR/Instructions.cpp:1086: void llvm::StoreInst::AssertOK(): Assertion `getOperand(0)->getType() == cast<PointerType>(getOperand(1)->getType())->getElementType() && "Ptr must be a pointer to Val type!"' failed.
Could not compile `rust-net-network`.
```

**Comment by tomjakubowski** [comment]
Can you post the SHA of the commit when you observed this for future reference?

**Comment by Ericson2314** [comment]
Gladly, `170c4399e614fe599c3d41306b3429ca8b3b68c6`. I just had the idea of emitting byte code and then running `llc` on that, to try to get a better error message.

**Comment by Ericson2314** [comment]
No such, I was hoping rustc could produce IR (meant that, not bytecode) entirely in rustland, but alas that is not the case.

**Comment by jdm** [comment]
What's the output of `rustc --version`?

**Comment by Ericson2314** [comment]
Not sure. I know it was some nightly not more than two days old at the time, but that computer ran out of batteries and I don't have its charger with me.

On a different computer using latest rust nightly I hit the same error. That `rustc -vV` is:
```
rustc 1.0.0-nightly (ed530d7a3 2015-01-16 22:41:16 +0000)
binary: rustc
commit-hash: ed530d7a3b67989047e6fe61fe101b9d8158585f
commit-date: 2015-01-16 22:41:16 +0000
host: x86_64-unknown-linux-gnu
release: 1.0.0-nightly
```

**Comment by dotdash** [comment]
`170c4399e614fe599c3d41306b3429ca8b3b68c6` doesn't seem to be present in the repo when I use the given clone command.

I suspect this is the same issue as #22346 which is fixed by now. Can you confirm that this is fixed?

**Comment by frewsxcv** [comment]
@Ericson2314 Are you able to reproduce this issue with the latest beta Rust?

**Comment by steveklabnik** [comment]
Given that we don't have a way to reproduce this, I'm going to give it a close. If anyone can, please let me know!

**Comment by Ericson2314** [comment]
Sorry the code needs to be updated a lot to compile for post 1.0. When I get around to that, I'll report back here.
