### ISSUE TITLE
rustup: When local date is later than server date, nightly can't be downloaded

### ISSUE THREAD

**Issue by mkpankov** [rust-lang/rust#21270]
```
➜  rust git:(master) src/etc/rustup.sh --prefix=$HOME/install --save
rustup: CFG_CURL             := /usr/bin/curl (7.35.0)
rustup: CFG_TAR              := /bin/tar (1.27.1)
rustup: CFG_FILE             := /usr/bin/file (5.14)
rustup: CFG_SHA256SUM        := /usr/bin/sha256sum (256sum)
rustup: CFG_SHASUM           := /usr/bin/shasum (5.84)
rustup: 
rustup: processing src/etc/rustup.sh args
rustup: 
rustup: CFG_PREFIX           := /home/mpankov/install 
rustup: CFG_DATE             :=  
rustup: CFG_SAVE             := 1 
rustup: 
rustup: validating src/etc/rustup.sh args
rustup: 
rustup: host triple: x86_64-unknown-linux-gnu
rustup: Downloading https://static.rust-lang.org/dist/2015-01-17/rust-nightly-x86_64-unknown-linux-gnu.tar.gz to /home/mpankov/.rustup/2015-01-17/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
rustup: error: failed to download installer
```
The issue here is, I believe, that local time is later than time of where Rust is built. Considering a big part of the world is significantly to the East of main build server (up to about 12 hours of time differences), running `rustup.sh` late at night in Europe will frequenly break.

**Comment by estsauver** [comment]
Hey @mkpankov thanks for the report. 

I'll add a patch to the script to get the correct date, but in the mean time, you should be able to specify a nightly date using the date option on rustup.sh.

```
    --date=[<none>]                  use the YYYY-MM-DD nightly instead of the current nightly
```

**Comment by mkpankov** [comment]
I believe this should be closed as it was fixed

**Comment by mkpankov** [comment]
The issue repeats on latest master:

```
➜  rust git:(d6c15d9) ~/rust/src/etc/rustup.sh --prefix=$HOME/install --save                      
rustup: CFG_CURL             := /usr/bin/curl (7.35.0)
rustup: CFG_TAR              := /bin/tar (1.27.1)
rustup: CFG_FILE             := /usr/bin/file (5.14)
rustup: CFG_SHA256SUM        := /usr/bin/sha256sum (256sum)
rustup: CFG_SHASUM           := /usr/bin/shasum (5.84)
rustup: 
rustup: processing /home/mkpankov/rust/src/etc/rustup.sh args
rustup: 
rustup: CFG_PREFIX           := /home/mkpankov/install 
rustup: CFG_DATE             :=  
rustup: CFG_SAVE             := 1 
rustup: 
rustup: validating /home/mkpankov/rust/src/etc/rustup.sh args
rustup: 
rustup: host triple: x86_64-unknown-linux-gnu
rustup: Downloading https://static.rust-lang.org/dist/2015-02-04/rust-nightly-x86_64-unknown-linux-gnu.tar.gz to /home/mkpankov/.rustup/2015-02-04/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
rustup: error: failed to download installer
➜  rust git:(d6c15d9) date
Ср. февр.  4 12:01:57 MSK 2015
```

`date` reads `Wed Feb 4`, although I'm not sure Feb 4 is supposed to be ready already.

**Comment by steveklabnik** [comment]
@mkpankov , have you been seeing this lately? Also, should this be refiled against https://github.com/rust-lang/rustup ?

**Comment by mkpankov** [comment]
@steveklabnik no, I didn't, but I don't use `rustup` frequently enough now.

**Comment by steveklabnik** [comment]
Okay, I'm going to give this one a close, then. If someone else is seeing this, please let me know!

**Comment by axeoth** [comment]
I think I am having the same issue (a few minutes ago):

$ curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- --channel=nightly

Welcome to Rust.

This script will download the Rust compiler and its package manager, Cargo, and
install them to /usr/local. You may install elsewhere by running this script
with the --prefix=<path> option.

The installer will run under 'sudo' and may ask you for your password. If you do
not want the script to run 'sudo' then pass it the --disable-sudo flag.

You may uninstall later by running /usr/local/lib/rustlib/uninstall.sh,
or by running this script again with the --uninstall flag.

Continue? (y/N) y

rustup: gpg available. signatures will be verified
rustup: downloading manifest for 'nightly'
rustup: downloading toolchain for 'nightly'
######################################################################## 100,0%
curl: (22) The requested URL returned error: 416
rustup: command failed: curl -# -C - -f -O http://static-rust-lang-org.s3-website-us-west-1.amazonaws.com/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
rustup: couldn't download 'http://static-rust-lang-org.s3-website-us-west-1.amazonaws.com/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz'

And manually executing the curl line also fails:

$ curl -# -C - -f -O http://static-rust-lang-org.s3-website-us-west-1.amazonaws.com/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
######################################################################## 100,0%
curl: (22) The requested URL returned error: 416

My TZ is France. First time that I try to update in the morning. I will try again tonight.

**Comment by axeoth** [comment]
it works when I update in the evening
