### ISSUE TITLE
librustc_borrowck/borrowck/doc.rs doesn't get rendered

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#21281]
Because `mod borrowck` is private.

**Comment by nikomatsakis** [comment]
I think the consensus was that we should add some way to include `.md` files in rustdoc?

I personally think long-form documentation is super useful, so I wouldn't want to remove it from the repo, but I'd love to make a proper markdown file and not a big comment.

**Comment by steveklabnik** [comment]
Rustdoc already knows how to do `.md` files, so that wasn't the problem. I think it was that you liked the abilty to search or something?

**Comment by steveklabnik** [comment]
Regardless, I thought you _didn't_ want them to be markdown files, so if you do, then woooo :confetti_ball:

**Comment by kmcallister** [comment]
Maybe we need a "scary compiler internals" section of the book.

Actually, I read through the borrowchecker `doc.rs` the other day and it was fairly comprehensible. It definitely improved my understanding of Rust and not just of the implementation.
