### ISSUE TITLE
The Ownership guide does not clearly explain what happens when there are two or more elided lifetimes

### ISSUE THREAD

**Issue by snowe2010** [rust-lang/rust#21284]
Reading over the Ownership section in TRPL and came across the example 

    fn frob(s: &str, t: &str) -> &str;  // ILLEGAL, two inputs

As a newbie, this was very confusing. I believe the situation could be explained by simply adding another line.

    fn frob(s: &str, t: &str) -> &str;  // ILLEGAL, two inputs
    fn frob(s: &'a str, t: &'b str) -> &'? str; // Expanded: Output lifetime is unclear

I'm not sure if this is the best way to do this.

**Comment by Gankro** [comment]
This sounds like a great fix to me, (although I would add the `<'a, 'b>` to the signature for clarity). PR welcome! :smile:

**Comment by snowe2010** [comment]
I've been waiting for input on my PR for several days. Still have no response. The ? didn't compile, and so I'm not sure what to change it to. I thought this section was ignored by the compile, but it doesn't seem that way.

**Comment by bombless** [comment]
How about:
```Rust
fn frob(s: &str, t: &str) -> &str; // two inputs, failed to expand
```

**Comment by Gankro** [comment]
Oh, sorry. I didn't even parse that there was a PR referring back to this issue :sweat_smile:

**Comment by snowe2010** [comment]
@bombless That's what the original is, I was very confused by that, and I was trying to update the docs to sufficiently explain the problem with just a short bit of code. The second bit of code was much better at explaining the problem to me, as the question mark implies that the return lifetime is ambiguous.

**Comment by steveklabnik** [comment]
It's also the only place that this notation is used, which makes it
confusing.

**Comment by snowe2010** [comment]
So what should I change it to? @Gankro suggested `fn frob<'a, 'b>(s: &'a str, t: &'b str) -> &str;`

**Comment by steveklabnik** [comment]
I think that's fine
