### ISSUE TITLE
rustup: error: invalid sha256.

### ISSUE THREAD

**Issue by javalama** [rust-lang/rust#21293]
I get

rustup: error: invalid sha256.

when trying to install on OS X

**Comment by brson** [comment]
This seems to be intermittent, and happen when the cdn is syncing to s3. cc https://github.com/rust-lang/rust/issues/21239

**Comment by javalama** [comment]
How intermittent? I've been getting the error for days.

**Comment by Gankro** [comment]
Closing as effectively a dupe of #21239
