### ISSUE TITLE
`raw_pointer_derive` lint should not complain about deriving `Copy`

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#21296]
Although I find it somewhat dubious to copy a raw pointer, they *are* a `Copy` type, and the compiler suggests implementing `Copy`, and when doing so with `derive`, the compiler then complains that `Copy` is being derived with a raw pointer field!

**Comment by cmr** [comment]
cc #21272

**Comment by alexcrichton** [comment]
Fixed in #21362
