### ISSUE TITLE
Error running hello world on Win7-x64

### ISSUE THREAD

**Issue by milkman2014** [rust-lang/rust#21305]
1. on Win7-x64, installed Rust by 1.0.0-alpha 64-bit installer(included path environment).
2. In CMD run "rustc" compile successful, created a new file: main.exe.
3. Run main.exe, report an error that has stopped working.

**Comment by cybergeek94** [comment]
I think more information is necessary.

* Open CMD and run `echo %PATH%`, what does it output?
* What anti-virus are you running? (Possibly what's causing it.)
* Are you running from CMD or double-clicking the .exe?
