### ISSUE TITLE
Confusion over std::hash::Hasher and std::collections::hash_map::Hasher

### ISSUE THREAD

**Issue by danburkert** [rust-lang/rust#21307]
It is easy to confuse the `std::hash::Hasher` and `std::collections::hash_map::Hasher`, and the error message is not very helpful when importing the wrong type:

```rust
use std::collections::HashSet;
use std::hash::{Hash, Hasher};

struct MyStruct<T> {
    set: HashSet<T>
}

impl <T: Eq + Hash<Hasher>> MyStruct<T> {
}
```

results in a compile error:

```
src/lib.rs:8:20: 8:26 error: explicit lifetime bound required
src/lib.rs:8 impl <T: Eq + Hash<Hasher>> MyStruct<T> {
```

**Comment by tupshin** [comment]
I just got totally confused by this myself, and only google returning this ticket helped me.

**Comment by danburkert** [comment]
This is no longer an issue since Hash reform.
