### ISSUE TITLE
vim indent file broken with comments containing braces

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#21317]
In an impl block comment out a long function and open a line below. The cursor is now in the first column.

**Comment by mahkoh** [comment]
cc @chris-morgan @kballard

**Comment by kballard** [comment]
Can you give me an example?

**Comment by mahkoh** [comment]
It's because the it doesn't ignore comments. There is invalid syntax in the comment.

**Comment by mahkoh** [comment]
Minimal example:
```rust
impl X {
    //}

}
```

**Comment by mahkoh** [comment]
https://github.com/rust-lang/rust.vim/issues/4
