### ISSUE TITLE
Rustdoc displays negative impls for traits identically to standard impls

### ISSUE THREAD

**Issue by mkovalchik** [rust-lang/rust#21310]
When documenting negative impls for the Send and Sync traits (added by [RFC 19](https://github.com/rust-lang/rfcs/blob/master/text/0019-opt-in-builtin-traits.md)) rustdoc currently displays the negative impls identically to positive impls.

As an example, there's currently no indication that the Send impl for [MutexGuard](http://doc.rust-lang.org/std/sync/struct.MutexGuard.html) is actually opting out of the Send trait rather than adding an implementation of it.

**Comment by kmcallister** [comment]
Eek.

**Comment by sellibitze** [comment]
It seems the issue has not been solved completely. On a trait's page that lists all its implementors, it's still wrong.

**Comment by steveklabnik** [comment]
@sellibitze you mentioned http://doc.rust-lang.org/std/rc/struct.Rc.html in IRC, but I'm clearly seeing `!Send`: http://doc.rust-lang.org/std/rc/struct.Rc.html

**Comment by steveklabnik** [comment]
After further discussion, http://doc.rust-lang.org/std/marker/trait.Send.html is still not showing `!`.

**Comment by sellibitze** [comment]
Maybe the right thing to do is to just not mention Rc on trait.Send at all. Either that, or adding a '!' in there.

**Comment by Diggsey** [comment]
Or add the "!", but also show them in a separate section below.

**Comment by pnkfelix** [comment]
1.0 polish, "P-veryhigh"
