### ISSUE TITLE
Src Link in Rustdoc fails for assert_eq!

### ISSUE THREAD

**Issue by estsauver** [rust-lang/rust#21311]
Step 1: Visit http://doc.rust-lang.org/std/macro.assert_eq!.html
Step 2: Click Link [src]

Page should link to http://doc.rust-lang.org/src/core/macros.rs.html#80-93, but instead links to http://doc.rust-lang.org/src/std/%3Ccore%20macros%3E.html#1-9

Suggested label A-Docs A-Rustdoc

**Comment by steveklabnik** [comment]
Not sure this isn't a dup...

**Comment by tomjakubowski** [comment]
rustdoc has some special logic to redirect through re-exports for items, but similar logic wasn't added for "re-exported" macros after macro reform.

**Comment by Meyermagic** [comment]
Just as a note, at time of writing this problem still exists in the beta docs. Might want to cherry pick the change to beta.

**Comment by steveklabnik** [comment]
@alexcrichton what do you think, should we backport this?

**Comment by alexcrichton** [comment]
I'd be fine doing so, although I thought that the main PR fixing rustdoc made it into a master -> beta merge... Ah well, either way is fine by me!
