### ISSUE TITLE
`make tidy` output on Travis is hard to read

### ISSUE THREAD

**Issue by pshc** [rust-lang/rust#21322]
The output chock is full of NOTEs, which distract the eye from the actual problem. [example](https://travis-ci.org/rust-lang/rust/builds/47377183#L374)

I'm guessing that these NOTEs aren't really useful in Travis test builds? Would it make sense to remove them?

Potential alternate solution is to highlight the failures in red: #18826

**Comment by iKevinY** [comment]
It seems logical enough to ignore NOTEs on Travis builds, so I took a shot at it in #21369.

**Comment by iKevinY** [comment]
I think this issue is closable now that #21369 has been merged in.

**Comment by pshc** [comment]
Awesome, thanks for the quick fix!
