### ISSUE TITLE
LLVM assertion failure in llvm::InvokeInst::init

### ISSUE THREAD

**Issue by ptal** [rust-lang/rust#21321]
Assertion:

```
rustc: /home/.../rust/src/llvm/lib/IR/Instructions.cpp:550: void llvm::InvokeInst::init(llvm::Value*, llvm::BasicBlock*, llvm::BasicBlock*, llvm::ArrayRef<llvm::Value*>, const llvm::Twine&): Assertion `(i >= FTy->getNumParams() || FTy->getParamType(i) == Args[i]->getType()) && "Invoking a function with a bad signature!"' failed.
```

You can replicate this assertion with `cargo test`, the project is https://github.com/ptal/Rust.mcp/commit/a3c2747933afebdf0a0df5755a9013edf4e4989f

The test generating this failure is `newvar_test` in solver.rs

Rust version: rustc 1.0.0-dev (89c4e3792 2015-01-17 10:58:43 +0000)

**Comment by ptal** [comment]
The newest version of my code now works fine. The code has not changed much but I did not fix the compiling errors (provoked by the newest version of the rust compiler) of the earlier version to see if it still fails. So I think it's fixed, however, to be sure, we'd need to execute this particular version.

I let the decision of closing (or not) this ticket to the mainteners.

**Comment by steveklabnik** [comment]
@ptal well, it seems like nobody else has seen this issue, so I am going to give it a close. Thank you for reporting! It's nice when bugs just work themselves out...
