### ISSUE TITLE
It is surprising `let ref x: i32 = 5` has a type of `&i32`

### ISSUE THREAD

**Issue by erickt** [rust-lang/rust#21320]
While I understand how this is happening, it's a bit surprising that this works:

```rust
fn main() {
    let ref x: i32 = 5;
    let y: &i32 = x;
}
```

Instead, I would have expected this to have been written as:

```rust
fn main() {
    let ref x: &i32 = 5;
    let y: &i32 = x;
}
```

**Comment by steveklabnik** [comment]
Where is this written?

**Comment by P1start** [comment]
It’s not really that surprising if you consider that the `T` in `let pat: T = bar;` always represents the type of `bar`. (I guess that would be more obvious if it were written `let pat = bar: T;` instead…)

**Comment by erickt** [comment]
@steveklabnik: This wasn't written down anywhere, it's just a weird quirk of the `let ref` syntax. For me, I read this statement as `(let ref x): i32` instead of `let (ref x): i32`. I don't see us talk about `let ref` in the docs yet, so when we do document this, we should try to point out this behavior so it's not too surprising.

**Comment by steveklabnik** [comment]
Hmmm. Yeah, I'm slightly worried about documenting speculative incorrect syntax because ther are infinite "I thought Rust did X but insead it does Y".

Is `let ref` even useful ever?

**Comment by erickt** [comment]
I can only think of cases where I'd write `let (ref x, ref y) = ...`. Doing `let x = &...` is much cleaner.

**Comment by steveklabnik** [comment]
I'm going to give this bug a close, mostly because I'm not sure where to add in something like "I was surprised by this particular syntax".  We already discuss `let` and patterns. If someone feels strongly about this, and is willing to submit a patch, we can talk about it, but I'm not finding it particularly actionable.
