### ISSUE TITLE
VecMap::into_iter shouldn't be taking a `&mut self`

### ISSUE THREAD

**Issue by erickt** [rust-lang/rust#21328]
cc @Gankro 

I'm in the process of `IntoIter`-ifying the collections, and I've discovered that the `VecMap::into_iter` takes a `&mut self` instead of the convention of `into_*` consuming the value. It's also marked stable, even though the type itself is marked unstable. Should this instead be a candidate for the `drain` method discussed in the collection reform trait?

**Comment by Gankro** [comment]
Yeah this is just a mistake. Feel free to fix it to match conventions.

**Comment by aochagavia** [comment]
Just to be clear, the solution to this is to make `into_iter` consume the value and introduce a `drain` function (and iterator). Is this right or am I missing something?

**Comment by Gankro** [comment]
Yep!
