### ISSUE TITLE
Color differences between `found` and `expected` in errors

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#21334]
Apply coloring to highlight the differences between _found_ and _expected_ errors and which is desired. This pic is old and slightly out of date but shows what I'm interested in:
![color_error](https://cloud.githubusercontent.com/assets/4156987/5790792/28023b76-9e77-11e4-9016-24884569d619.png)

**Comment by ahmedcharles** [comment]
I looked into this. It would seem that there isn't an easy way to do this and it would probably require extending the diagnostics framework to make this work without making it seem hacky.

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by estebank** [comment]
#41205 addresses this with bolding, not coloring. It does so at the type level, not at the path segment level.

**Comment by mdinger** [comment]
That looks better than what is currently available. You might want to mark this as a possible future extension. Not having used the other, this might not even be necessary depending on how well the other works out in practice.

**Comment by estebank** [comment]
@mdinger it's been a while since the highlighting code has been in the while. Do you still miss this the coloring feature despite this?

**Comment by mdinger** [comment]
I don't have a strong opinion. I'd mark it as WFM. If someone else wants it, they can reopen.
