### ISSUE TITLE
I/O chapter in the book

### ISSUE THREAD

**Issue by coderanger** [rust-lang/rust#21338]
Probably under intermediate, but reading and writing files is super common, but hard to get a signpost on as a new user. std::io has some basic examples already, could be a nucleus for a full doc on it.

**Comment by steveklabnik** [comment]
A chapter on this would be super great, post IO reform.

**Comment by steveklabnik** [comment]
I'm not going to track feature requests for book chapters in the tracker, as it's mostly noise. I do want to do this someday, though.

**Comment by coderanger** [comment]
Maybe make a `rust-docs` repo to act as a holder to tickets?

**Comment by steveklabnik** [comment]
We have `A-wishlist` over at rust-lang/RFCs already, that might be better.
