### ISSUE TITLE
Using --enable-local-rust causes stage1 and stage2 binaries to be linked with system rust

### ISSUE THREAD

**Issue by tdaede** [rust-lang/rust#21344]
I am attempting to use a system install of rust (from binary form) as the stage0 of a local rust build. I need to do this because stage0 snapshots are not available for my architecture. When I do this using --enable-local-rust, the stage1 and stage2 rustc binaries end up being linked with system shared libraries, e.g. the original stage0 snapshot binaries. This causes them not to work due to missing symbols.

**Comment by mneumann** [comment]
I think I hit the same problem on DragonFly!

**Comment by steveklabnik** [comment]
Triage: I am not sure if anything has changed here or not. @tdaede have you still seen this recently?

**Comment by alexcrichton** [comment]
Make's now gone, so closing.
