### ISSUE TITLE
run-pass multidispatch tests trigger UAC on Windows

### ISSUE THREAD

**Issue by klutzy** [rust-lang/rust#21352]
UAC thinks it is something about patch :(
cc #10512 and #11207

**Comment by bombless** [comment]
Actually, `rustc -o _dipatch` or `rustc -o dispatch_` will trigger that UAC while `rustc -o dispatch` won't.

**Comment by ColonelJ** [comment]
I'm planning to figure out a way to fix #11207 and add proper support for manifests to Rust (I think all Windows binaries ought to have one, to enable visual styles, show application version number etc.), but as noted [here](https://github.com/rust-lang/rust/issues/11207#issuecomment-61196468) as a temporary measure for this particular problem all you need to do is set an environment variable `__COMPAT_LAYER` as `RunAsInvoker` on your machine and you'll be able to run those tests fine.

I've made a pull request #21496 for this which make the test runner set this variable so you don't have to set it globally and affect the normal running of your box w.r.t. setup.exe and friends.  Though I expect most Rust developers on Windows would be smart enough to figure out that a right click -> Run As Administrator might be required when it brings up some privilege related error!  Even so, it's better if it just compiles and passes test 'out of the box' so to speak, after you've already gone through all the faff of installing some Rust-compatible MINGW (and Python, and whatever else...) on your machine.

**Comment by bombless** [comment]
I ran `make check` today and it ran successfully except for [this bug](https://github.com/rust-lang/rust/issues/18733).
I `grep`ed "manifest" and found nothing so I don't know what commit fixed this though.
Or maybe the fix is about CFLAGS.

**Comment by klutzy** [comment]
Fixed by #21496. (Executables still don't have manifest, but it's other issue: #10512/#11207)
