### ISSUE TITLE
a boxed iterator can't use methods in the IteratorExt trait

### ISSUE THREAD

**Issue by Kroisse** [rust-lang/rust#21361]
[Example](http://is.gd/mICr2A)

```rust
let v = vec![1, 2, 3];
let boxed = Box::new(v.iter()) as Box<Iterator<Item=i32>>;
boxed.max()  // IteratorExt::max(*boxed) also fails
```

This code will be failed to compile because `boxed` holds a trait object that is unsized, and [`IteratorExt` requires the `Sized` kind][1] so `IteratorExt` can only be implemented for sized types. Like [`IteratorExt::map()`][2], many methods in `IteratorExt` consume `self`, so requiring a sized type is necessary.

Adding `impl Iterator for Box<Iterator>` (like `Reader for Box<Reader>`) might solve this problem, but I'm worrying about the confliction with autoderef.

[1]: https://github.com/rust-lang/rust/blob/master/src/libcore/iter.rs#L121
[2]: https://github.com/rust-lang/rust/blob/master/src/libcore/iter.rs#L234

**Comment by japaric** [comment]
I **think** a possible solution would be `impl Iterator for &mut Iterator`, that way `boxed.max()` would autoderef `boxed` from `Box<Iterator>` into `&mut Iterator` (because `Box` implements `DerefMut<Target=T>`) and then since `&mut Iterator` implements the `Iterator` trait, it would also implement `IteratorExt`. Let me see if that works.

**Comment by japaric** [comment]
The idea works with the old `Iterator<T>` trait:

``` rust
#![no_implicit_prelude]

use std::boxed::Box;
use std::marker::Sized;
use std::option::Option;

trait Iterator<T> {
    fn next(&mut self) -> Option<T>;
}

impl<'a, T> Iterator<T> for &'a mut (Iterator<T> + 'a) {
    fn next(&mut self) -> Option<T> {
        loop {}
    }
}

trait IteratorExt<T>: Iterator<T> + Sized {
    fn last(self) -> Option<T> {
        loop {}
    }
}

impl<I, T> IteratorExt<T> for I where I: Iterator<T> {}

fn test(mut it: Box<Iterator<u8> + 'static>) {
    it.last();  // <-- it works
}

fn main() {}
```

But I'm not quite sure how to `impl<'a> Iterator for &'a mut (Iterator + 'a)` with associated types. This gets rejected:

``` rust
impl<'a, T> Iterator for &'a mut (Iterator<Item=T> + 'a) {
//~^ error: the type parameter `T` is not constrained by the impl trait, self type, or predicates
    type Item = T;
}
```

**Comment by japaric** [comment]
I think the last `impl` should be accepted, but it's not because of a bug, so I have filed #21363.
