### ISSUE TITLE
Indentation broken in error reporting

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#21360]
```rust
fn main() {
    let mut x = 1us;
    let y = &x;
    &mut x;





}
```
```
test2.rs:10:2: 10:2 note: previous borrow ends here
test2.rs:1 fn main() {
...
test2.rs:10 }
            ^
```

**Comment by kmcallister** [comment]
Is the issue here the varying width of the line number? It'd be useful if you could give more information with your bug reports than "Foo is broken" and a block of code.

**Comment by ktt3ja** [comment]
It's duplicate of https://github.com/rust-lang/rust/issues/11715

**Comment by steveklabnik** [comment]
yes, thank you.
