### ISSUE TITLE
Type parameters that appear in a trait object assoc type bindings are considered as "not constrained"

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#21363]
### STR

``` rust
#![crate_type = "lib"]
#![no_std]

trait Iterator {
    type Item;
}

impl<'a, T> Iterator for &'a mut (Iterator<Item=T> + 'a) {
//~^ error: the type parameter `T` is not constrained by the impl trait, self type, or predicates
    type Item = T;
}
```

`T` appears in `Self` (the trait object assoc type binding) so it should be considered as constrained, and this impl should be accepted. (Also I don't how we could `impl<'a> Iterator for &'a mut (Iterator + 'a) { type Item = ??? }` without the `T` type parameter)

### Version

``` rust
rustc 1.0.0-nightly (ed530d7a3 2015-01-16 22:41:16 +0000)
```

cc @nikomatsakis

**Comment by japaric** [comment]
Also this blocks a possible solution to  #21361 (boxed iterators (trait objects) can't use the `IteratorExt` methods)

**Comment by nikomatsakis** [comment]
Problem is presumably that `walk_ty` doesn't walk the projections in trait reference

**Comment by japaric** [comment]
re #21361, I worked around the issue with `#[old_impl_check]`, so this is no longer a blocker. In fact, the PR that fixes that issue has already been r+ed.
