### ISSUE TITLE
Invalid macro fails only if used

### ISSUE THREAD

**Issue by aochagavia** [rust-lang/rust#21370]
The following code only produces an error when the macro is used. Compilation should actually fail even if the macro is never used.

```
macro_rules! test { ($wrong:t_ty) => () }

fn main() {
     //test!("hello world"); only causes an error if uncommented
}
```

**Comment by kmcallister** [comment]
Yeah, it's my plan to move more of the `macro_rules!` parsing to the definition site (see #17616). I think that would improve the situation here.

**Comment by kmcallister** [comment]
Nominating 1.0-beta, P-backcompat-lang

**Comment by pnkfelix** [comment]
1.0-beta, P-backcompat-lang.
