### ISSUE TITLE
Any ICE in metadata should suggest a clean build

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#21408]
In a suitably apologetic tone.

**Comment by plasmachannel** [comment]
I have only used bugzilla before.  How do I get assigned to this?

**Comment by kmcallister** [comment]
I think only individuals in the `rust-lang` GitHub org can be assigned.  Commenting to say that you're working on it is enough :)

**Comment by Manishearth** [comment]
(I don't think this is an easy bug. @untitaker is looking into it, though)

**Comment by arielb1** [comment]
@Manishearth 

I made the problem much harder to reach with #28702.

**Comment by jonas-schievink** [comment]
#34539 made further improvements to the metadata check, I think this can be closed now

**Comment by alexcrichton** [comment]
Indeed I believe so!
