### ISSUE TITLE
Windows dist builders hit upload exception due to locking bug in buildbot

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#21434]
There's a bug in the buildbot DirectoryUpload buildstep on windows that causes exceptions on our dist builders. This happens pretty regularly. It can be avoided by limiting slaves to 1 build at a time, but we don't want to do that on auto builders because it seems to leave them underutilized and lets them shut down to frequently (which then costs time to start up again).

**Comment by brson** [comment]
I've tried to work around this by adding dist-specific slaves that only do 1 build at a time.

**Comment by steveklabnik** [comment]
Triage: I don't know if this is still a problem or not.

**Comment by edunham** [comment]
Still real, still forcing us to 1 builder per slave on Windows.
