### ISSUE TITLE
#[derive(Copy="something")] should be rejected

### ISSUE THREAD

**Issue by aochagavia** [rust-lang/rust#21435]
This compiles:

```
#[derive(Clone="2", Show(Wrong))]
struct MyStruct;
```

Other wrong attributes:

```
#[deprecated(Very, Wrong)]
#[test="something"]
#[test(Wrong)]
#[stable(Wrong)]
#[unstable(Wrong)]
```

**Comment by aochagavia** [comment]
cc @nick29581

**Comment by nick29581** [comment]
I don't think it is intentional, the derive parser will collect arguments, and then the copy or clone impls will silently ignore them. It would be good to error or warn if we can here.

**Comment by aochagavia** [comment]
I could add a fix in https://github.com/rust-lang/rust/pull/21265. Or do you prefer that I open a new PR for that?

**Comment by nick29581** [comment]
new PR please

**Comment by nick29581** [comment]
I guess this is technically a backwards incompatible change, since it will break programs with extraneous params. Although it is also just a bug. In any case, nomintating.

**Comment by kmcallister** [comment]
I think we have this problem throughout attribute handling code and not just on `derive` :/

**Comment by aochagavia** [comment]
I have updated the code example, since it is also possible to do `#[derive(Clone(Wrong))]`

I think the problem is in [L61 and L62](https://github.com/rust-lang/rust/blob/51e28dd0c88030b8661f0c414eb0af3e09840b31/src/libsyntax/ext/deriving/mod.rs#L61). We should only accept `MetaWord` and produce errors for `MetaNameVariable` and `MetaList`.

**Comment by brson** [comment]
many cases like this in the compiler where we are not vigilent about rejecting malformed attributes.

**Comment by pnkfelix** [comment]
polish issue, where it would not be the end of the world if we did not get around to addressing it, though it would be nice if it were fixed.

Assigning 1.0, P-low.

**Comment by kmcallister** [comment]
I think people will cut us a little slack on backwards compatibility of crap like

```rust
#[derive(Clone="2", Show(Wrong))]
```

The only way I could see this mattering is if a plugin makes an ill-advised attempt to extend the `deriving` syntax.  But plugins are unstable anyway.

**Comment by aochagavia** [comment]
I have updated the list of attributes (added `#[test]`, `#[deprecated]`, `#[stable]`, `#[unstable]`)

**Comment by pnkfelix** [comment]
This appears to be fixed; closing.
