### ISSUE TITLE
Compiler panic when doing something wrong with a module

### ISSUE THREAD

**Issue by Nekloa** [rust-lang/rust#21449]
A compiler panic occurs when trying to compile this snippet of code:

```
mod MyMod{
}

fn main() {
    let myVar = MyMod{T:0u64};
}
```
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'No def'n found for DefId { krate: 0u32, node: 4u32 } in tcx.tcache', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/middle/ty.rs:5008

rustc 1.0.0-nightly (f4f10dba2 2015-01-17 20:31:08 +0000)
binary: rustc
commit-hash: f4f10dba2975b51c2d2c92157018db3ac13d4d4a
commit-date: 2015-01-17 20:31:08 +0000
host: x86_64-unknown-linux-gnu [Linux Mint Debian Edition]
release: 1.0.0-nightly

**Comment by tamird** [comment]
Triage: still ICEs.

**Comment by pmarcelll** [comment]
This gives a proper error message on nightly (I guess #17001 is related).
