### ISSUE TITLE
RwLock Typo

### ISSUE THREAD

**Issue by Jojoshua** [rust-lang/rust#21440]
fn new(t: T) -> RwLock<T>

Creates a new instance of an RwLock which is unlocked and read to go.
->
Creates a new instance of a RwLock which is unlocked and ready to go.

**Comment by Diggsey** [comment]
Depends how you pronounce RwLock, (I'm assuming the writer pronounced it "Are-Double-You-Lock")

**Comment by sfackler** [comment]
I read it as "are double yoo lock" so the current version seems fine.

**Comment by steveklabnik** [comment]
Yeah, I do too. Interesting...

**Comment by tomjakubowski** [comment]
`RwLock` comes from the compound noun "RW lock", composed of the initialism "RW" (for readers-writer) and the noun "lock," which is turned into a struct name per Rust's naming conventions.

Initialisms are pronounced by reading each letter out left-to-right so the use of "a" or "an" is determined by the pronunciation of the first letter. The pronunciation of the letter "R" starts with a vowel sound so "an" is appropriate here.

See http://english.stackexchange.com/a/1017

**Comment by Jojoshua** [comment]
The typo was read for ready.

**Comment by steveklabnik** [comment]
@Jojoshua ha! Submitting to fix, good eyes.
