### ISSUE TITLE
Is as_slice deprecated? The compiler thinks so.

### ISSUE THREAD

**Issue by John-Nagle** [rust-lang/rust#21459]
rfc822date.rs:58:37: 58:47 warning: use of unstable item: Instead of taking this bound generically, this trait will be replaced with one of slicing syntax, deref coercions, or a more generic conversion trait, #[warn(unstable)] on by default
    rfc822date.rs:58     let matches = datere.captures(s.as_slice());   // Pattern match the date
                                                         ^~~~~~~~~~

Is the compiler trying to tell me that **as_slice()** is now deprecated? The reference manual still uses it. I appreciate the warning message, but the direction Rust is going here should probably be settled before 1.0. 

Amusingly, the recent deprecation of **from_str()** results in a warning that the replacement, "parse", is *too new.*
> rfc822date.rs:64:38: 64:52 warning: use of unstable item: this method was just created, #[warn(unstable)] on by default
> rfc822date.rs:64     let dd = captures.at(2).unwrap().parse::<u32>().unwrap();

In neither case is there an obvious preferred alternative which avoids the warning.

**Comment by Gankro** [comment]
We're still hashing out the precise story here, I think. Right now I think the preferred method is `&foo[]` or `&*foo` based on preference, but `&foo` should work soon (`&foo` should coerce to `&[T]` if `foo: Deref<[T]>`).

Closing because this is just a weird consequence of use being in transient state.

CC @alexcrichton in case I'm stupid

**Comment by John-Nagle** [comment]
See the statement *"The language is feature-complete for 1.0. While we plan to make many usability improvements before the final release, all 1.0 language features are now in place and we do not expect major breaking changes to them."* which was made on January 9th on the Rust blog: 
http://blog.rust-lang.org/2015/01/09/Rust-1.0-alpha.html 

You can't have it both ways. Either the feature-complete statement made in the Rust blog is now "inoperative", or that message is a bug. Pick one.

**Comment by Gankro** [comment]
Language != stdlibs

**Comment by John-Nagle** [comment]
From the same blog entry: *The core libraries are feature-complete for 1.0. API conventions have been **firmly established**, and core functionality – basic types, traits, data structures and concurrency primitives – has all been stabilized. Here again we do not expect major breaking changes before 1.0.*

The PR team and the developers are not on the same page.

**Comment by aturon** [comment]
@John-Nagle 

We are continuing to stabilize APIs during the alpha cycle. As @Gankro said the story around this particular method has indeed been in flux. While a few relatively core methods like this one are indeed still unstable, I stand by the claim in the blog post: we have made a huge effort leading into the alpha to stabilize the core modules, but that does not mean that literally every method is `#[stable]`.

In the near future we plan to break up unstable warnings into major "feature" areas, which will make it easier to track and get feedback on such stragglers.

**Comment by John-Nagle** [comment]
OK. Now I realize that it's in flux. That wasn't the impression the blog post gave, I'm surprised that something as pervasive as String to &str has not been nailed down at this late date, though.
