### ISSUE TITLE
Better error messages for htmldocck.py

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust#21455]
When a doc test fails, the console output looks like this:
```
Traceback (most recent call last):
  File "C:/Users/Diggory/Projects/rust/src/etc/htmldocck.py", line 350, in <module>
    check(sys.argv[1], get_commands(sys.argv[2]))
  File "C:/Users/Diggory/Projects/rust/src/etc/htmldocck.py", line 343, in check
    c.cmd, c.lineno))
RuntimeError: @matches check failed at line 15
make[1]: *** [all] Error 1
```

A traceback should only be shown if there was an error in the python script itself - in this case it should only show the matches error, something like this:

```
htmldocck: @matches check failed at <file>:<line>
    "<search pattern>" did not match:
    <html>
```

**Comment by lifthrasiir** [comment]
cc me. I'm surely willing to fix that as soon as I get enough spare time.

**Comment by huonw** [comment]
@lifthrasiir did you ever get a chance to look at this? (Do you know if the situation has changed?)

**Comment by lifthrasiir** [comment]
@huonw No, also I'm not aware of any update. Looks like that I've forgotten to work on this at that time (as flt2dec was being matured); I have virtually no energy to contribute nowadays, so I probably cannot work on this right now.
