### ISSUE TITLE
Documentation of last enum item causes parse failure

### ISSUE THREAD

**Issue by dhardy** [rust-lang/rust#21467]
The following fails to compile. Removing the documentation after `B` (or replacing with a `//` comment) avoids the issue.

    enum X {
        A,   /// doc about A
        B    /// doc about B
    }
    fn main(){}

Error message:

    error: expected one of `(`, `,`, `=`, `{`, or `}`, found `/// doc about B`

**Comment by jdm** [comment]
`///` comments always refer to the item following them, not preceding them. It's possible that this could be documented better or present a better error message.

**Comment by dhardy** [comment]
I know about Doxygen's `///<` comments, but had assumed Rust was smart enough to realise about comments-on-the-same-line.

**Comment by steveklabnik** [comment]
Yes, this is expected behavior. If someone wants to add a new lint, feel free, but this is not a bug.
