### ISSUE TITLE
Compile error messages related to inferring closure types can be hard to debug

### ISSUE THREAD

**Issue by nical** [rust-lang/rust#21464]
Sample code to illustrate the issue:  http://is.gd/qzkZ5k
```
fn foo(_callback: &Fn()) {
    // ...
}

fn main() {
    let captured_var = 42;
    
    foo(&||{
        println!("{}", captured_var);
    });
}
```

error message:
```
<anon>:8:9: 10:6 error: unable to infer enough type information about `closure[<anon>:8:10: 10:6]`; type annotations required
<anon>:8     foo(&||{
<anon>:9         println!("{}", captured_var);
<anon>:10     });
```

What happens here is that captured_var's type isn't fully defined at the moment the closure is created and rustc doesn't know what type to put in the environment of the closure. It does make sense but the confusing part it can actually take a while to figure out that the issue is not with the visible part of the closure (it's signature), but with the invisible part (the environment). The error message points to the first line of the closure (the one with the "&|args| {" part which is the visible "signature" part) 
I ran into this issue with a much bigger closure, so the usage of the captured variable was much farther than the signature line pointed in the error message. Rustc does a lot of inference around the signature of closures so it encourages the developer to spend time looking there when the compiler isn't given enough info to infer the type.

My suggestion is that there should be a different error messages when the missing type information is related to the captured environment of the closure, and that this error message should have words like "captured" and "environment" in them to let the developer know that it's not about inferring the signature of the closure.

**Comment by remram44** [comment]
I don't see this error on your example anymore (code runs fine).

**Comment by steveklabnik** [comment]
Yes, this no longer errors.
