### ISSUE TITLE
Duplicate Impl/Traits with rustdoc when using "pub use foo::bar::*"

### ISSUE THREAD

**Issue by NewbiZ** [rust-lang/rust#21474]
It seems like using glob on `use` statements ends up generating twice the documentation for `Impl` and `Traits` of this `Struct`.

If I use:

    pub use foo::bar::*;

All `Impl` and `Traits` of each `Struct` in `foo::bar::*` will be duplicated in the doc.
If symbols are listed one by one it works well:

    pub use foo::bar::baz;
    pub use foo::bar::boz;

Issue can be seen when generating the doc from https://github.com/NewbiZ/rgb/tree/2d3d077120d51bdef42f2e6a83595d2b26a6e04c

If you change in `src/lib.rs`:

    pub use self::cpu::*;

by

    pub use self::cpu::Cpu;
    pub use self::cpu::Flag;

it will work.

**Comment by Gankro** [comment]
I can't seem to find a pre-existing issue for this, even though it's been around for months...

@tomjakubowski are you aware of an issue for this?

**Comment by steveklabnik** [comment]
I wonder if globs or rustdoc itself are at fault.

**Comment by Gankro** [comment]
Almost certainly Rustdoc.

It's always rustdoc's fault.

**Comment by tomjakubowski** [comment]
@Gankro I don't remember seeing an issue for this in the tracker. I also wasn't aware this was an issue, what a bizarre quirk!

Here's a minimal reproduction. Note that only the impl needs to be in the `mod`, and the globbed `pub use` is required.

```rust
pub use inner::*;

mod inner {
    impl super::Blah for super::What { }
}

pub trait Blah { }

pub struct What;
```
