### ISSUE TITLE
Enable setting rpath on install

### ISSUE THREAD

**Issue by taralx** [rust-lang/rust#21483]
For the (fairly common?) case of setting a custom prefix and nothing else, it would be useful to set rpath during install. Mac OS specifically has "install_name_tool" to manage this process. Thoughts?

(Forked from #20836.)

**Comment by brson** [comment]
I think I'm in favor. Would need to be added to [rust-installer](http://github.com/rust-lang/rust-installer) probably, which already has an optional ldconfig post-install step on linux. We've discussed [elsewhere](https://github.com/rust-lang/rust/issues/28640) that the rpaths baked into rustc on OS X are broken, and a solution would be to frob them during install.

**Comment by edunham** [comment]
It's now on by default.
