### ISSUE TITLE
Missing cleanup on escape from functional record update

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#21486]
I was playing around with #21407, and I think I found a distinct bug in FRU – if a field initialiser escapes (panics/returns/`break`s), some of the fields in the original struct get leaked.

 For example:
```Rust
struct Noisy(u32);
impl Drop for Noisy {
    fn drop(&mut self) {
        println!("splat #{}!", self.0);
    }
}

struct Foo { n0: Noisy, n1: Noisy }

fn leak() -> Foo {
    let old_foo = Foo { n0: Noisy(0), n1: Noisy(1) };
    Foo { n0: { return Foo { n0: Noisy(3), n1: Noisy(4) } }, ..old_foo } ;
}

fn main() {
    drop(leak());
}
```

This prints
```
splat #0!
splat #3!
splat #4!
```

Observe that the `Noisy(1)` is never destroyed.

**Comment by pnkfelix** [comment]
nominating, suggest 1.0 polish, P-high.

**Comment by pnkfelix** [comment]
P-high, 1.0 polish.

**Comment by pnkfelix** [comment]
This seems to have been fixed.

**Comment by pnkfelix** [comment]
i wonder if #23201 is what fixed it ... (it certainly seems like it might also have been injected by #23112 ).

**Comment by pnkfelix** [comment]
in any case, seems like the remaining work here is to add a regression test.

**Comment by pnkfelix** [comment]
(but, ooooh, there are definitely other bugs lying around in this area.... will file some tickets soonish.)
