### ISSUE TITLE
Remove prelude_import attribute

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#21490]
This attribute is applied to the prelude glob by std_inject but I don't see that it is actually used for anything. Appears to be an old workaround.

**Comment by Marwes** [comment]
Figured I might try my hand at this but it seems that the attribute is used in resolve [link](https://github.com/rust-lang/rust/blob/5d2056a7e3e52b2aec41662cfd960e0eafe8494c/src/librustc_resolve/build_reduced_graph.rs#L297-L299). Did you miss that usage or can that line of code be changed to use something else?

**Comment by D-Wagner** [comment]
I was also looking at this earlier.  Since this is automatically applied to prelude to make to force `Shadowable::Always` maybe it could just be renamed to more clearly indicate what it does?

**Comment by steveklabnik** [comment]
Can confirm what @Marwes says. it's used in `src/librustc_resolve/build_reduced_graph.rs`.

@brson, I'm going to give this a close, since it seems this was originally in error. It's behind a gate, so it's not causing any harm.
