### ISSUE TITLE
Add support for associated items when using deriving::generic::TraitDef

### ISSUE THREAD

**Issue by sectopod** [rust-lang/rust#21497]
It doesn't look like [TraitDef](http://doc.rust-lang.org/syntax/ext/deriving/generic/struct.TraitDef.html) was updated accordingly with the inception of associated types. It only has `methods` for the trait contents, while I need to use it for a trait with a type inside.

**Comment by kvark** [comment]
I'll give it a try.

**Comment by sectopod** [comment]
I fetched this code and verified that the updated Rust works for my case in gfx-rs. :+1:
