### ISSUE TITLE
"Fixed" benchmark time is out-of-date in the optimizations section of the testing guide

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#21501]
It currently says
```
test bench_xor_1000_ints ... bench:       1 ns/iter (+/- 0)
```

While running the code as written gives
```
test bench_xor_1000_ints ... bench:       131 ns/iter (+/- 3)
```

(which is correct.)

**Comment by huonw** [comment]
(On that note, the code could now be written: `let n = test::black_box(1000);` instead of having to call `black_box` separately.)

**Comment by steveklabnik** [comment]
:(
