### ISSUE TITLE
Tracking issue for std::thread::ThreadId

### ISSUE THREAD

**Issue by aldanor** [rust-lang/rust#21507]
# Update description

Tracking issue for `std::thread::ThreadId`. Points to consider when stabilizing:
- Implementation of a mutex + u64, unconditional panic if space is exhausted
- Various traits on `ThreadId`, including `Copy`
# Original report

Not sure if it can be considered as bug but it sure cripples the existing threading API (e.g., makes it harder for a thread to identify itself or store/pass its identity). 

// it could also be nice if Thread was able to return a unique integer id() (or hash itself?..).

**Comment by murarth** [comment]
I'd also like to have `Eq` implemented for `Thread`. Would a PR be accepted to this effect or would it require an RFC?

**Comment by remram44** [comment]
I'd very much like some kind of thread id, I'm pretty sure every Thread implementation around gives numeric ids (Python has a string `name` much like Rust but also offers [`Thread.ident`](https://docs.python.org/2/library/threading.html#threading.Thread.ident), "a nonzero integer").

**Comment by frewsxcv** [comment]
FYI, here's the associated issue in the RFCs repo: https://github.com/rust-lang/rfcs/issues/1435

**Comment by ticki** [comment]
I think it would be fitting to implement `Hash`, like `std::mem::Discriminant`, which doesn't expose an actual value either.

**Comment by nrc** [comment]
Just to chime in here, it would be really nice to have a proper `Debug` impl - I have a multi-threaded program I'm trying to debug and I'm trying to work out which threads are hitting a certain bit of code. Doing a println with `current::id()` would be really easy, but I can't and there isn't a nice way to get around this afaikt (will end up transmuting of course).

**Comment by frewsxcv** [comment]
There's a PR open to implement `Hash` for `ThreadId`: https://github.com/rust-lang/rust/pull/41008

**Comment by sfackler** [comment]
@nrc that seems reasonable to me. I asked the author of #41008 to add that derive as well.

**Comment by aturon** [comment]
@rust-lang/libs, thoughts on stabilization?

**Comment by alexcrichton** [comment]
@aturon some might say you could even canvas opinions through...

@rfcbot fcp merge

**Comment by dtolnay** [comment]
BTreeMap wants to know whether we could get an impl Ord for ThreadId. Are there any reasons not to have one?

**Comment by cuviper** [comment]
`Ord` is uncomfortable to me. For instance, people might observe that the IDs sort in order of creation, but do we want to promise that?

**Comment by alexcrichton** [comment]
I'd personally go either way on `Ord`, I don't mind starting out conservatively and I also wouldn't mind adding it. If we do add it I'd at least want to clearly document "you really shouldn't rely on orderings between thread ids, just that you can order them to deduplicate"

**Comment by sfackler** [comment]
I'm not super concerned about the Ord impl. We certainly don't want to promise that IDs sort in order of creation - TIDs on Unix systems wrap around pretty frequently.

**Comment by cuviper** [comment]
FWIW, in the _current_ [implementation](https://github.com/rust-lang/rust/blob/ae33d99bcd1c1f99b4605d2bb1150c590ffa3044/src/libstd/thread/mod.rs#L764-L788) it's a monotonic u64 counter, with no relationship to the OS TID at all.  So it will in fact sort in the order of creation, or the order when first seen for threads created outside of Rust.  But I still wouldn't want to promise this.

**Comment by dtolnay** [comment]
@rfcbot reviewed

**Comment by dlight** [comment]
If `ThreadId` is going to implement `Ord`, it probably makes sense to implement `Hash` too.

**Comment by sagebind** [comment]
@dlight Currently, it already implements `Hash`.

I don't see an issue with implementing `Ord`, so long as we warn in the docs that the sort order doesn't indicate anything about the `Thread`s they correspond to.

The only issue I see is if we change the implementation later down the road to use system handles, it would be difficult to provide a stable `Ord` implementation (e.g. there's no `pthread_cmp()`, only `pthread_equal()`).

**Comment by sfackler** [comment]
We wouldn't be able to implement `Hash` for system handles anyway, so I think that ship has probably sailed.

**Comment by cuviper** [comment]
System handles also aren't globally unique when threads stop and new ones start. Is that a property we want to guarantee about `ThreadId`?

**Comment by sagebind** [comment]
> We wouldn't be able to implement Hash for system handles anyway, so I think that ship has probably sailed.

That's a good point. I think that's why we chose _not_ to use system handles in the first place: it makes `ThreadId` much harder to use and less useful.

@cuviper We don't currently make such a guarantee (which should reflect in the docs), but I think we _should_ guarantee globally unique IDs. Assuming we don't plan on changing the IDs from being a custom integer. If the range of IDs becomes a problem, it is easy enough to increase the number of bits being used and maintain that guarantee.
