### ISSUE TITLE
Silent demotion of lifetime in analysis causes confusing message

### ISSUE THREAD

**Issue by dhardy** [rust-lang/rust#21508]
See [StackOverflow question](http://stackoverflow.com/questions/28089695/lifetime-of-variable-rust-match-pattern/28090230?noredirect=1#comment44557897_28090230).

Summary: the compiler accepts a trait impl function returning a `&'static str` when the trait requires only `&'a str`, `'a` being the life of the object, but then assumes the lifetime of the returned value is only `&'a str` despite direct call (not via trait).

Possible solutions I see:

1.  Do not demote the lifetime of a function when called via the object (not the trait), but keep both versions of the function (i.e. lifetime `&'static` when called via the object and lifetime `&'a` when called via the trait). This is likely confusing, so (2) may be better.
2.  Make it an error to implement a trait function with too long a lifetime.

**Comment by huonw** [comment]
cc @nikomatsakis; this is the "subtyping" rule, right?

**Comment by nikomatsakis** [comment]
Yes, this is the subtyping rule. I'm not sure whether changes are needed here, but if we were to change anything I would want to get stricter about the correspondence between the trait and impl.

**Comment by nikomatsakis** [comment]
There are other places -- notably where-clauses -- where we absolutely *cannot* require a 1-to-1 correspondence. But in method signatures we likely could. It's a bit trickier than it might sound.

**Comment by nikomatsakis** [comment]
Nominating. We have to decide what semantics we want here I guess.

**Comment by pnkfelix** [comment]
P-high, not required for 1.0.  (But we would take a patch if we happen to get one before 1.0; otherwise the current semantics is stuck).

**Comment by steveklabnik** [comment]
> But we would take a patch if we happen to get one before 1.0; otherwise the current semantics is stuck).

Well, a loooong time after 1.0, I guess this is stuck here, closing.
