### ISSUE TITLE
Can't cast FFI function to identical function type

### ISSUE THREAD

**Issue by jdm** [rust-lang/rust#21515]
Let's say you have an FFI structure containing an `Option<unsafe extern "C" fn()>`. Sometimes you want to pass a function pointer to a function you've defined in your own crate, while other times you want to pass a pointer to one defined in the original library. `Some(my_fn as unsafe extern "C" fn())` works for the first, but `Some(ff_fn)` works for the second. Additionally, `Some(ffi_fn as unsafe extern "C" fn())` triggers a non-scalar cast error. This is frustrating when it comes to code generation, since it's inconsistent.

**Comment by jdm** [comment]
```rust
extern {
    fn ffi_fn();
}

struct FFI {
    f: Option<unsafe extern fn()>,
}

fn main() {
    let _ffi1 = FFI {
        f: Some(ffi_fn as unsafe extern "C" fn()),
    };
}
```
```
godot2:servo jdm$ ./mach rustc /tmp/ffi.rs
/tmp/ffi.rs:11:17: 11:49 error: non-scalar cast: `unsafe extern "C" fn()` as `unsafe extern "C" fn()`
/tmp/ffi.rs:11         f: Some(ffi_fn as unsafe extern "C" fn()),
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by steveklabnik** [comment]
This sample now compiles. Well, it can't link to `ffi_fn`, but that's to be expected. :)
