### ISSUE TITLE
Bad lifetime error when a const needs to be static instead

### ISSUE THREAD

**Issue by dhardy** [rust-lang/rust#21513]
Why can't I borrow a static const array with static lifetime? Unless I misunderstand, the const should live long enough.

```
const A: [i32; 2] = [1, 2];
fn get_slice() -> &'static [i32] {
    &A
}
fn main() {
    let a = get_slice();
    println!("A: {}, {}", a[0], a[1]);
}
```

Compiling fails:

```
test.rs:3:6: 3:7 error: borrowed value does not live long enough
test.rs:3     &A
               ^
note: reference must be valid for the static lifetime...
test.rs:2:34: 4:2 note: ...but borrowed value is only valid for the block at 2:33
test.rs:2 fn get_slice() -> &'static [i32] {
test.rs:3     &A
test.rs:4 }
error: aborting due to previous error
```

On the other hand, this (changing the type of const `A`) works:

```
const A: &'static [i32] = &[1, 2];
fn get_slice() -> &'static [i32] {
    A
}
fn main(){
    let a = get_slice();
    println!("A: {}, {}", a[0], a[1]);
}
```

Output:

```
$ ./test 
A: 1, 2
```

**Comment by kmcallister** [comment]
aiui, `const` is a "by-value" constant, whereas `static` has an actual location in memory.  This means you can only take a slice to the latter.

Leaving this open as a diagnostics bug — the compiler should be more helpful in this case.

**Comment by steveklabnik** [comment]
Triage: yes, this code is correct, but the error could be more helpful.

**Comment by oli-obk** [comment]
triage, this is not an error anymore
