### ISSUE TITLE
suppress duplicate error messages in trait reporting

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#21528]
There are many situations in which we wind up reporting duplicate errors during trait matching and elsewhere. You can see this in many of the compile-fail tests which wind up with the same error several times. These messages often arise naturally because multiple parts of the code give rise to the same obligation, and because of type inference, which can make it hard to tell whether two trait obligations are in fact the same until it is too late. (In fact, we already silently drop two EXACT DUPLICATE obligations for various other reasons).

I think the best thing is just to add some sort of hashset and check for duplicates in `librustc::middle::traits::error_reporting` or maybe `librustc_typeck::check::vtable`. But we should do this check *after* doing full type resolution.

I am not sure whether to consider the spans. On the one hand, getting the same error for every line where it occurs is useful, and it can be confusing if you get an error from line A but not B even though they seem identical. This may lead you to think that B is somehow ok, when in fact the compiler was just helpfully suppressing a duplicate error. On the other hand, we already some amount of suppression like that, so the situation above can already arise, and perhaps being more consistent would wind up being less confusing overall.

**Comment by nikomatsakis** [comment]
Marking as mentor.

**Comment by fhahn** [comment]
Is there something left to do here? it seems like @arielb1's fix for #28098 does the thing suggested in this ticket.

**Comment by brson** [comment]
Closing per @fhahn .
