### ISSUE TITLE
`rustc -v` fails with "no input filename given"

### ISSUE THREAD

**Issue by daboross** [rust-lang/rust#21525]
I'm not sure if this is a duplicate, in the little searching I did I didn't find another issue.
```
$ rustc --version
rustc 1.0.0-nightly (29bd9a06e 2015-01-20 23:03:09 +0000)
$ rustc -v
error: no input filename given
```

**Comment by alexcrichton** [comment]
This is actually because `-v` is now the "verbose flag" where `-V` is the shorthand for `--version`. Thanks though!
