### ISSUE TITLE
Enhance / redesign the time module

### ISSUE THREAD

**Issue by boggle** [rust-lang/rust#2153]
* nanosleep (difficult on windows but doable with 100 ns solution using win32 API)
* function for the normalization of timespec values
* substraction, addition, comparison functions are needed
* hash
* support for printing times in fmt
* serialization helpers would be nice, too

**Comment by gsingh93** [comment]
This should probably be moved to https://github.com/rust-lang/time

**Comment by steveklabnik** [comment]
Agreed.
