### ISSUE TITLE
Bad error message for missing DerefMut

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#21536]
```rust
use std::ops::{Deref, DerefMut};

struct Foo(u32);

impl Deref for Foo {
    type Target = u32;
    fn deref<'a>(&'a self) -> &'a u32 { &self.0 }
}

/*
impl DerefMut for Foo {
    fn deref_mut<'a>(&'a mut self) -> &'a mut u32 { &mut self.0 }
}
*/

fn main() {
    let mut foo = Foo(3);
    *foo = 4;
}
```

gives

```
foo.rs:18:5: 18:13 error: cannot assign to immutable borrowed content
foo.rs:18     *foo = 4;
              ^~~~~~~~
```

which is not too helpful.  We shouldn't even try to borrow immutably in this case.  Or at least tag the borrow with some metadata saying `DerefMut` wasn't available, so we can print a `help:` message here.

rustc 1.0.0-dev (ed530d7a3 2015-01-16 22:41:16 +0000)

Not sure this is actually easy to fix, but I think it'd be a good beginner project to spend a little time looking into it.

**Comment by D-Wagner** [comment]
I'd like to try tackling this.

**Comment by D-Wagner** [comment]
So after a lot of reading, I was wondering if it would just be better to present a warning in situations where the compiler prefers to use DerefMut but cannot.  However, I am curious as to how one might add the metadata as @kmcallister suggested.  I haven't yet understood a clear mechanism by which this could be done.

**Comment by steveklabnik** [comment]
Triage: no changes

**Comment by nikomatsakis** [comment]
Dup of https://github.com/rust-lang/rust/issues/28419, closing in favor of that one as it has a bit more discussion.
