### ISSUE TITLE
std::os::rand::imp::is_getrandom_available atomics use is racy

### ISSUE THREAD

**Issue by talchas** [rust-lang/rust#21538]
is_getrandom_available relies on the ordering of reads and writes that use Ordering::Relaxed to prevent races, which is incorrect. The failure mode would be reading the initial false value of GETRANDOM_AVAILABLE, and thus not using getrandom(2) when it is actually available. Either GETRANDOM_CHECKED should use an acquire load and a release store, or it could just use Once.

**Comment by klutzy** [comment]
Ah! The problem is that two atomic writes can be swapped, right? I'll rewrite it with one variable with three states (notchecked / available / unavailable) anyway.

**Comment by talchas** [comment]
Yeah, that is the problem, and that would also fix it.
