### ISSUE TITLE
Follow token checking is too restrictive.

### ISSUE THREAD

**Issue by vadimcn** [rust-lang/rust#21545]
```rust
macro_rules! foo {
    ( $x:ident $(: $y:ident )* ) => ( $x $(: $y )* )
}
```

```
<anon>:2:16: 2:30 error: `$x:ident` is followed by a sequence repetition, which is not allowed for `ident` fragments
<anon>:2     ( $x:ident $(: $y:ident )* ) => ( $x $(: $y )* )
```

The [RFC](https://github.com/rust-lang/rfcs/blob/master/text/0550-macro-future-proofing.md) says that `ident` may be followed by any token, so why repetition of any tokens would be invalid?

**Comment by vadimcn** [comment]
cc @cmr

**Comment by cmr** [comment]
The follow sets are only for real tokens, not complex NTs. To extend this properly, the algorithm will need to compute the FIRST of the following token to ensure that it is a subset of the FOLLOW set for that token.

**Comment by vadimcn** [comment]
Created [PR](https://github.com/rust-lang/rfcs/pull/733) to amend the RFC.

**Comment by steveklabnik** [comment]
Traige: the RFC was pursued, so closing this.
