### ISSUE TITLE
Changing mutability causes strange lifetime errors

### ISSUE THREAD

**Issue by LeoTestard** [rust-lang/rust#21552]
This is going to be a big bug with a lot of different examples, but we came across this by discussing on an error with @kimundi on IRC, and couldn't decide if it was the same bug or different ones. So I hope someone will be able to see what's the logic in this.

So first let's look at this simple example:

```rust
struct Foo<'a> {
    r: &'a mut u32
}

impl<'a> Foo<'a> {
    fn get<'b>(&'b self) -> &'a u32 {
        &*self.r
    }
}

fn foo<'x>(foo: Foo<'x>) {
    foo.get();
}

fn main() {
    let f = Foo { r: &mut 0 };
    foo(f);
}
```

In this case when calling `vec` from `foo`, the `'a` lifetime clearly corresponds to `'x`, so the compiler should allow it to do a borrow of the integer that lasts at most `'x`. But it doesn't. Replacing `'a` by `'b` in the return type works, but looks too restrictive.

```
<anon>:7:9: 7:21 error: cannot infer an appropriate lifetime for borrow expression due to conflicting requirements
<anon>:7         &mut *self.r
                 ^~~~~~~~~~~~
<anon>:6:5: 8:6 help: consider using an explicit lifetime parameter as shown: fn get(&'a mut self) -> &'a mut u32
<anon>:6     fn get<'b>(&'b mut self) -> &'a mut u32 {
<anon>:7         &mut *self.r
<anon>:8     }
error: aborting due to previous error
```

What's really strange here is that if you remove the `mut` annotation on `r`, it works. So not only we've got a lifetime error that changes with mutability but it depends on the mutability of the contained borrow, not of the returned borrow. (Leaving the `mut`s and making `vec` take a `&'b mut self` and returns a `&'a mut u32` yields the same error.

Probably related, I originally had a case where the lifetime of `self` was defined to be the same as the lifetime parameter of the structure, like:

```rust
struct Foo<'a> {
    r: &'a mut u32
}

impl<'a> Foo<'a> {
    fn get(&'a mut self) -> &'a mut u32 {
        &mut *self.r
    }
}
```

In this case, we get a lifetime error at call site:

```
<anon>:12:5: 12:8 error: `foo` does not live long enough
<anon>:12     foo.get();
              ^~~
<anon>:11:26: 13:2 note: reference must be valid for the lifetime 'x as defined on the block at 11:25...
<anon>:11 fn foo<'x>(foo: Foo<'x>) {
<anon>:12     foo.get();
<anon>:13 }
<anon>:11:26: 13:2 note: ...but borrowed value is only valid for the block at 11:25
<anon>:11 fn foo<'x>(foo: Foo<'x>) {
<anon>:12     foo.get();
<anon>:13 }
error: aborting due to previous error
```

Here, it will work if you remove the `mut`s annotations, this time *not on the structure* but *on the function*, like this:

```rust
    fn get(&'a self) -> &'a u32 { ... } // this one works
```

We're not sure if the `mut` case should be accepted, or if both cases should be rejected (obviously with a better error mesggae... ).

I hope this issue is clear enough...
cc @kimundi, it you want to elaborate more on this.

**Comment by nikomatsakis** [comment]
I found it hard to tell what compiled and what did not, so let me just start with that:

```rust
struct Foo<'a> {
    r: &'a mut u32
}

impl<'a> Foo<'a> {
    fn get<'b>(&'b self) -> &'a u32 {
        &*self.r
    }
}

fn foo<'x>(foo: Foo<'x>) {
    foo.get();
}

fn main() {
    let f = Foo { r: &mut 0 };
    foo(f);
}
```

FAILS

**Comment by LeoTestard** [comment]
Yes, and I now think this is legit, if I understood well what you just said on IRC ?

**Comment by nikomatsakis** [comment]
```rust
struct Foo<'a> {
    r: &'a mut u32
}

impl<'a> Foo<'a> {
    fn get<'b>(&'b self) -> &'b u32 {
        &*self.r
    }
}

fn foo<'x>(foo: Foo<'x>) {
    foo.get();
}

fn main() {
    let f = Foo { r: &mut 0 };
    foo(f);
}
```
OK

**Comment by nikomatsakis** [comment]
```rust
struct Foo<'a> {
    r: &'a u32
}

impl<'a> Foo<'a> {
    fn get<'b>(&'b self) -> &'a u32 {
        &*self.r
    }
}

fn foo<'x>(foo: Foo<'x>) {
    foo.get();
}

fn main() {
    let f = Foo { r: &mut 0 };
    foo(f);
}
```
OK

**Comment by nikomatsakis** [comment]
Yes, all examples are working as I expected. :)

**Comment by LeoTestard** [comment]
Ok, but now what  about the case where the lifetime of `self` is the same as the lifetime parameter given to the struct ? Not sure why anyone would like to do this but I accidentally end up with my code looking like this, and it behaves strangely as well:

```rust
struct Foo<'a> {
    r: &'a mut u32
}

impl<'a> Foo<'a> {
    fn get(&'a mut self) -> &'a mut u32 {
        &mut *self.r
    }
}

fn foo<'x>(foo: Foo<'x>) {
    foo.get();
}

fn main() {
    let f = Foo { r: &mut 0 };
    foo(f);
}
```
NOT OK

```rust
struct Foo<'a> {
    r: &'a mut u32
}

impl<'a> Foo<'a> {
    fn get(&'a self) -> &'a u32 {
        &*self.r
    }
}

fn foo<'x>(foo: Foo<'x>) {
    foo.get();
}

fn main() {
    let f = Foo { r: &mut 0 };
    foo(f);
}
```
OK

**Comment by nikomatsakis** [comment]
```rust
struct Foo<'a> {
    r: &'a mut u32
}

impl<'a> Foo<'a> {
    fn get(&'a self) -> &'a u32 {
        &*self.r
    }
}

fn foo<'x>(foo: Foo<'x>) -> &'x int {
    foo.get() // ERROR
}

fn main() {
    let f = Foo { r: &mut 0 };
    foo(f);
}
```

**Comment by nikomatsakis** [comment]
There doesn't seem to be a bug here, closing the issue.
