### ISSUE TITLE
Debuginfo is emitted for some unreachable code, crashes

### ISSUE THREAD

**Issue by Jojoshua** [rust-lang/rust#21559]
error: internal compiler error: debuginfo::create_local_var_metadata() - Referenced variable location is not an alloca!
Test.rs:131       let take = if num_items <= split_by {
                            ^~~~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', C:\bot\slave\nightly-dist-rustc-win-64\build\src\libsyntax\diagnostic.rs:130

**Comment by steveklabnik** [comment]
Can you share the code please?

**Comment by Jojoshua** [comment]
Maybe it is a cargo issue. I was using cargo build but rustc worked

fn main(){

	return;	
	let num_items = 100;
	let mut split_by = 50;
	let mut start_at = 0;
	let mut count = 0;	
	let take = if num_items <= split_by { 
				  split_by = 1;				  
				  num_items //Take all items at once in this case
				} else {					
					num_items / split_by	// Take x number at a time						
				};	
}

**Comment by jdm** [comment]
The Cargo build adds `-g` by default, which is what triggers this.

**Comment by jdm** [comment]
What version of rustc are you using (`rustc --version`)? This looks very similar to #20312.

**Comment by Jojoshua** [comment]
I am using the latest version (installed today).

**Comment by Jojoshua** [comment]
Yes 20312 looks exactly the same.

**Comment by jdm** [comment]
cc @michaelwoerister

**Comment by michaelwoerister** [comment]
Hm, maybe the LLVM basic-blocks in the nested expressions are not marked as unreachable during trans?

**Comment by michaelwoerister** [comment]
PR #23066 which fixes this (but needs close review for unintended side-effects) is open for a while now. Nothing new on this issue otherwise.

**Comment by pmarcelll** [comment]
Seems to be fixed.

**Comment by alexcrichton** [comment]
Thanks @pmarcelll!
