### ISSUE TITLE
Warnings compiling examples in "Compound Data Types" chapter

### ISSUE THREAD

**Issue by snej** [rust-lang/rust#21566]
I'm brand new at Rust and tried compiling one of the enumeration examples in the [Compound Data Types](http://doc.rust-lang.org/book/compound-data-types.html) chapter of the book:

```
enum StringResult {
    StringOK(String),
    ErrorReason(String),
}

fn respond(greeting: &str) -> StringResult {
    if greeting == "Hello" {
        StringResult::StringOK("Good morning!".to_string())
    } else {
        StringResult::ErrorReason("I didn't understand you!".to_string())
    }
}

fn main() {
    respond("hi");
}
```

This is taken verbatim from the book, with a `main` function added so it can compile and run.

rustc (nightly build, downloaded this morning) produces warnings compiling it:

```
play.rs:8:48: 8:59 warning: use of unstable item, #[warn(unstable)] on by default
play.rs:8         StringResult::StringOK("Good morning!".to_string())
                                                         ^~~~~~~~~~~
play.rs:10:62: 10:73 warning: use of unstable item, #[warn(unstable)] on by default
play.rs:10         StringResult::ErrorReason("I didn't understand you!".to_string())
                                                                        ^~~~~~~~~~~
```

I don't know what an "unstable item" is, so this is kind of disconcerting. Can these examples be tweaked to avoid triggering warnings?

**Comment by steveklabnik** [comment]
They will after the stability story here shakes out.

**Comment by snej** [comment]
OK. Might want to add a note to the docs, then, for the sake of the newbies.

**Comment by steveklabnik** [comment]
This example no longer warns.
