### ISSUE TITLE
Localized file names and actual display names

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust#21569]
In OS X you're not supposed to display POSIX paths to users. User-facing file names are supposed to use "display name" ([`[NSFilemanager displayNameAtPath:]` and friends](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSFileManager_Class/index.html#//apple_ref/occ/instm/NSFileManager/componentsToDisplayForPath:)).

Rust's `path.display()` and [`Display` guidelines](https://github.com/rust-lang/rfcs/blob/master/text/0565-show-string-guidelines.md) sound like they're exactly for this purpose, but unfortunately `path.display()` falls short on OS X and probably can't be fixed without breaking at least some Cargo build scripts.

However, in OS X "display path" is seriously only for display and it's a one-way function:

```objc
[fm displayNameAtPath:@"/Applications"] == @"アプリケーション"; // If Japanese locale is set
[fm displayNameAtPath:@"foo:bar"] == @"foo/bar"; // Yes, Finder allows slashes in file names
```

I'd be lovely if Rust had built-in support for this and encouraged doing the right thing on OS X and other OSes that have localized paths.

Suggestions:

* Add `path.filename_localized()` and `path.components_localized()`
* Drop `path.filename_display()`
* Rename `path.display()` to `path.to_string_lossy()`, to make it clear that a code like `println!("cargo:root={}", path.display());` is slightly buggy.
* Add `format_bytes!()` to make it easier to correctly format commandline arguments with paths.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#845
