### ISSUE TITLE
rustbook: Surprised by concepts which have not yet been introduced

### ISSUE THREAD

**Issue by emiel** [rust-lang/rust#21563]
Just sharing my experience as I'm going through the new rust book. I've covered the basics chapter (2) and have just started 'intermediate' (3). The first section on strings starts talking about references and life-times which have not yet been covered. So the transition is a bit jarring. I know they will be covered later but it was a bit of a surprise.

http://doc.rust-lang.org/book/more-strings.html

**Comment by steveklabnik** [comment]
Intermediate isn't meant to be in-order, so while this is true, I'm not sure it's really actionable.

**Comment by emiel** [comment]
Looking back at http://doc.rust-lang.org/book/intermediate.html I do see now that this is mentioned. I must have glossed over it. Again, just sharing my experience.

**Comment by steveklabnik** [comment]
Yes, thanks. If this continues to be confusing, we can try to make this more prominent.
