### ISSUE TITLE
Display and Error traits are clunky

### ISSUE THREAD

**Issue by andrewrk** [rust-lang/rust#21576]
here's a diff I just made:

```diff
-impl std::error::Error for CreationError {
-    fn description(&self) -> &str {
+impl CreationError {
+    fn to_string(&self) -> &str {
         match self {
             &CreationError::OsError(ref text) => text.as_slice(),
             &CreationError::NotSupported => "Some of the requested attributes are not supported",
@@ -82,6 +82,18 @@ impl std::error::Error for CreationError {
     }
 }
 
+impl std::fmt::Display for CreationError {
+    fn fmt(&self, formatter: &mut std::fmt::Formatter) -> Result<(), std::fmt::Error> {
+        formatter.write_str(self.to_string())
+    }
+}
+
+impl std::error::Error for CreationError {
+    fn description(&self) -> &str {
+        self.to_string()
+    }
+}
+
```

Display::fmt cannot call Error::description because Error trait requires Display trait. So I end up creating yet another method, and the other two call it. Pretty clunky when I just wanted a single to_string-like method.

**Comment by huonw** [comment]
It should be possible for `Display` to call `Error`; a trait inheritance requirement `A: B + C` just means that `B` and `C` have to be implemented if `A` is implemented, it's not imposing any ordering constraints on the implementations.

**Comment by shepmaster** [comment]
I found I had to explicitly cast `self` to call `Error` methods from `Display`:

```rust
let as_err = self as &error::Error;
```

**Comment by alexcrichton** [comment]
As @huonw mentioned there's not actual ordering restriction, you can [call `description` from `fmt`](https://gist.github.com/anonymous/929aaf089ee55e7cd268). I think in this case you just need to make sure that the `Error` trait is in scope.
