### ISSUE TITLE
doc request: example how to inherit stdout/stderr in Command

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust#21570]
`std::io::Command` by default creates new stdout/stderr for the command. 

I don't see an obvious way to make it use same stdout/stderr as the parent process. Could you add an example that shows how to this?

Typically own stdout/stderr is a very desirable behavior, but in Cargo build scripts this hides output of commands and makes debugging difficult, so in that context inherited stdin/stdout is a common and useful use-case.

**Comment by steveklabnik** [comment]
holidng off until new io lands /cc @alexcrichton

**Comment by sfackler** [comment]
Here's an example while we wait for new IO: https://github.com/sfackler/rust-postgres-macros/blob/master/build.rs#L9-L11

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/22119 is the PR to merge the relevant new functionality

**Comment by steveklabnik** [comment]
It was merged! `Comand::new` says:

```
    /// * Inherit stdin/stdout/stderr for `run` or `status`, but create pipes for `output`
```

so this behavior has changed to be the default. Therefore, I'm giving this a close. Of course, I plan on adding tons of examples, but this specific one is addressed already.
