### ISSUE TITLE
Command error does not include detail about missing executable

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust#21571]
```rust
std::io::process::Command::new("bogus").spawn().unwrap();
```

> IoError { kind: FileNotFound, desc: "no such file or directory", detail: None }

That "detail: None" is disappointing. I'd like it to include at least the command name, and ideally also the current directory and `PATH` searched, so I can diagnose the problem.

**Comment by JIghtuse** [comment]
I'll try to solve this one.

**Comment by vojtechkral** [comment]
As of the new `std::process` implementation, this doesn't seem to be fixed.
@JIghtuse still interested in fixing this?

```rust
#![feature(process)]
use std::process::Command;

fn main() {
	let res = Command::new("bogus").spawn();
	match res {
		Ok(_) => println!("ok"),
		Err(err) => println!("Error: {}", err),
	}
}
```

> Error: No such file or directory (os error 2)

**Comment by JIghtuse** [comment]
Sorry for the silence.
I'm still interested in this. Actually, I found a way to add detail to error. Now I try to add needed information.

**Comment by mdibaiee** [comment]
Hey, it seems this issue hasn't had activity for a long time, I'm interested in fixing this.

I tried to find the source which this error is created at, I couldn't find the actual source, but it seems to be somewhere in `libstd/process.rs`, or `libstd/sys/unix/process.rs`, can someone help me to find the source? Thanks.

**Comment by ranma42** [comment]
The `detail` field was removed in ac77392f8ab1c201b0c927f6a2d30b632b95acda and currently 

    std::process::Command::new("bogus").spawn().unwrap();

panicks on the `Err` value

    Error { repr: Os { code: 2, message: "No such file or directory" } }

The lines at which the error value is created are https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/process.rs#L176 (unix) and https://github.com/rust-lang/rust/blob/master/src/libstd/sys/windows/process.rs#L176 (windows).

**Comment by mdibaiee** [comment]
Um, so if the `detail` field is removed, what do we have to do about this? :confused:

**Comment by JIghtuse** [comment]
Folks at IRC told me we should write separate detailed implementations of Error for unix and windows process.rs (there's no "universal" strings on that level). I have some drafts in my local git copy, but they are not working yet.

**Comment by steveklabnik** [comment]
Given that detail is gone, I'm going to give this a close. We might be able to extend these errors, but it's a more significant change now, so we'd want to discuss it more.
