### ISSUE TITLE
Associated type mismatch errors are confusing

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#21585]
For the following code:

```
fn x(x: &[u8]) -> &[u8]  {
   x[..2]
}
```

we get

```
error: type mismatch resolving `<[u8] as core::ops::Index<core::ops::RangeTo<usize>>>::Output == &[u8]`:
 expected slice,
    found &-ptr
```

Firstly, in this case, `<[u8] as core::ops::Index<core::ops::RangeTo<usize>>>::Output` resolves exactly to `[u8]`, which should have been calculated and displayed.

Secondly, some additional notes about associated types might help this error. Associated types are being used everywhere in the standard library, but the syntax is rather obscure and not something a newbie will be able to pick up.  `<[u8] as core::ops::Index<core::ops::RangeTo<usize>>>::Output` is quite an intimidating beast unless you know how associated types work.

**Comment by bluss** [comment]
Same with iterator element type mismatches. Users often see these, and they are noisy and scary!

This error:
```
error: type mismatch resolving `<core::slice::Iter<'_, i32> as core::iter::Iterator>::Item == i32`:
 expected &-ptr,
    found i32 [E0271]
```

is hairy, but it means: "You passed an iterator of &i32, I expected an iterator of i32"

cc @wycats

**Comment by steveklabnik** [comment]
This now gives a pretty good error:

```
hello.rs:2:8: 2:14 error: mismatched types:
 expected `&[u8]`,
    found `[u8]`
(expected &-ptr,
    found slice) [E0308]
hello.rs:2        x[..2]
                  ^~~~~~
```
