### ISSUE TITLE
Problem with the shift operator and the Index trait

### ISSUE THREAD

**Issue by robitex** [rust-lang/rust#21593]
If you try to compile this:

    fn main() {
        let v = vec![1_u8, 2, 3, 4, 5, 6, 7, 8, 9];
        println!("{}", test(&v));
    }

    fn test(n: &Vec<u8>) -> u8 {
        1 << n[0]
    }

the compiler's answer is:

    <anon>:7:5: 7:14 error: right-hand-side of a shift operation must have integral type, not `_`
    <anon>:7     1 << n[0]
                 ^~~~~~~~~
    error: aborting due to previous error
    playpen: application terminated with error code 101

Is it a bug?
Thank you.
R.

**Comment by shepmaster** [comment]
Accepting a slice is a workaround for now:

```rust
fn main() {
    let v = vec![1_u8, 2, 3, 4, 5, 6, 7, 8, 9];
    println!("{}", test(&v[]));
}

fn test(n: &[u8]) -> u8 {
    1 << n[0]
}
```

It looks like

**Comment by robitex** [comment]
Very elegant workaround I say...
Thank you.
R.

**Comment by steveklabnik** [comment]
This now compiles without error.
