### ISSUE TITLE
can not print a RefCell 

### ISSUE THREAD

**Issue by hartsantler** [rust-lang/rust#21594]
It is nice for debugging things to be able to simply print things, pointers, structs, etc.  Why not have RefCell printable by default?

```rust
error: the trait `core::fmt::Show` is not implemented for the type `core::cell::RefCell<A>`
```

**Comment by frewsxcv** [comment]
Worth mentioning that none of the structs in `core::cell` implement the `core::fmt::Show` trait, so if this gets approved, we should consider implementing it for all of them

**Comment by sfackler** [comment]
All types should implement `Show` (now `Debug` actually). The lack of an implementation here is just an oversight.

**Comment by alexcrichton** [comment]
You may just need to update your compiler, the current nightly [should have](https://github.com/rust-lang/rust/blob/76fbb3583174ca8856b4e149929839888f503e6b/src/libcore/fmt/mod.rs#L910-L918) this implementation.
