### ISSUE TITLE
Misleading message when attempting to call methods on a raw pointer

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rust#21596]
When trying to call a method on a raw pointer Rust compiler says there's no such method.

It would be better to say that there is such method, but the pointer has to be explicitly dereferenced first.

``` rust
let x = 8u8;
let y = &x;
let z: *const u8 = &x;
println!("{} {}", 
    y.to_string(), // OK
    z.to_string()  // Not OK
);
```

> error: type `*const u8` does not implement any method in scope named `to_string`

This is _technically correct_, but unexpected and help hint for this error suggests wrong solution. 

I've read this message as "yada yada _no such method_", so I went to check whether I've spelled the method correctly, whether I've put the method in the appropriate `impl` block, etc. — all completely irrelevant to this error.

I'd find something like that more helpful:

> error: method `to_string` requires type `u8`, but `*const u8` cannot be automatically dereferenced. hint: use `as_ref()`

**Comment by nagisa** [comment]
[Implementing traits for raw pointers is possible](http://is.gd/S1cFxH), though. The best we could do here is to add some logic in trait suggestion mechanism to check whether traits for dereferenced values exist. Something along the lines of 

```
help: std::string::ToString::to_string implemented for &u8, consider `z.as_ref()`
help: std::string::ToString::to_string implemented for u8, consider dereferencing `z`
```

Too many help messages will overwhelm messages that actually matter, though.

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by memoryruins** [comment]
Triage: the error message has improved
```
error[E0599]: no method named `to_string` found for type `*const u8` in the current scope
 --> src/main.rs:8:11
  |
8 |         z.to_string()  // Not OK
  |           ^^^^^^^^^
  |
  = note: the method `to_string` exists but the following trait bounds were not satisfied:
          `*const u8 : std::string::ToString`
```
`rustc: 1.32.0`

**Comment by estebank** [comment]
To suggest `as_ref` it would have to suggest `unsafe {z.as_ref()}.unwrap()`, which is taking the suggestions a bit far. We could add a note [about `as_ref`](https://doc.rust-lang.org/std/primitive.pointer.html#method.as_ref) though.
