### ISSUE TITLE
Version migration tool

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#2159]
It would be great to have a tool that automatically updates old Rust code for compatibility with new Rust.

We could use cargo (#1453) to automatically test which packages break between versions and whether this tool converts them correctly.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#606
