### ISSUE TITLE
write! and the like should probably require a Writer implementation

### ISSUE THREAD

**Issue by SiegeLord** [rust-lang/rust#21615]
Right now it just calls a method named `write_fmt`. This duck typing might lead to confusing error messages, and contradicts the documentation of the macro.

**Comment by alexcrichton** [comment]
Unfortunately this isn't currently possible (we tried to do this awhile ago). There are two contexts in which the `write!` macro is primarily called:

1. When using `io::Writer`
2. When using `fmt::Formatter` or `fmt::Writer`

Unfortunately these two cases call different `write_fmt` methods (different traits), so this will not necessarily be easy to resolve.

**Comment by alexcrichton** [comment]
Closing due to my previous comment, and also that this is stable now.
