### ISSUE TITLE
Back-compat risk: same label can be attached to distinct blocks in the same scope

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#21633]
The current Rust alpha allows one to attach two lifetimes with the same name to two distinct loop blocks.

This is a backwards compatibility risk for hypothesized future versions of Rust where the lifetime labels can be used in e.g. type annotations (rather than solely used for labelled break/continue statements).

Example:
```rust
fn main() {
    let d = 3;
    'a: for i in (0..d).rev() {
        println!("i: {}", i);
    }

    'a: for i in (d..d*2).rev() {
        println!("i: {}", i);
    }
}
```

**Comment by pnkfelix** [comment]
Nominating for P-backcompat-lang, 1.0 beta.

**Comment by arielb1** [comment]
isn't this just ordinary shadowing?

**Comment by pnkfelix** [comment]
@arielb1 in my opinion ordinary shadowing would be when an nested scope is labeled with the same lifetime as a scope is nested within.

I see the two scopes here as siblings, at least in terms of what we might use `'a` for in type annotations.

(Having said that, there is probably a coherent semantics that allows this based on shadowing.)

**Comment by arielb1** [comment]
The `'a`'s scope is the `for` loop's, just like the `i`.

**Comment by pnkfelix** [comment]
@arielb1 ah.  okay yes, that is another coherent semantics, I think.  Not sure if its the one I would pick, but I do not see any obvious holes in it.

**Comment by pnkfelix** [comment]
Polish issue for 1.0, P-low.

**Comment by pnkfelix** [comment]
(i spent a little while looking into this.  It may be a little tricky to do at certain phases of the compiler, because the current for-loop expansion moves the lifetime into the inside of a block, so I don't think I can meaningfully do the analysis post expansion, at least, not without knowing enough to skip over such blocks as not introducing an inner scope.)

**Comment by pnkfelix** [comment]
@nikomatsakis suggests that we strengthen this to simply disallow any duplicate labels in the body of an entire function.  That would certainly resolve my above problem.
