### ISSUE TITLE
Extend --emit dep-info to optionally list "phony" tagets for all dependencies

### ISSUE THREAD

**Issue by thepowersgang** [rust-lang/rust#21645]
When using `--emit=dep-info` in a makefile, a missing file (due to being renamed or re-factored away) will cause make to terminate the build instantly.

GCC/Clang mitigate this by using the `-MP` flag when creating dependencies, which emits extra rules of the form `dependency: ` to tell make to ignore the files if they are missing.

**Comment by steveklabnik** [comment]
Triage: not aware of any changes here.

**Comment by thepowersgang** [comment]
Duplicate of #28735, and fixed in 17419622712af44311aa7a8730e4535dff3554f5. Closing
