### ISSUE TITLE
Accessing poisoned MutexGuard is unsafe

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust#21641]
Mutex provides a way to access the data from a poisoned mutex, by handling the PoisonError case explicitly. This is unsafe, because the data contained within the mutex may be in an invalid state. For example, unsafe code which is writing to the data may panic part-way through (eg. something like CString may not yet have written the final NULL).

Under normal circumstances, the only requirement is that "Drop" is able to correctly handle any of the intermediate states resulting from a panic, which in practice is not too difficult because Drop is internal to the type, so externally all constraints are still maintained.

A nice way to fix this would be for a poisoned mutex to immediately drop the contained data. To recover a poisoned mutex, another thread must then move new data into the mutex using a method on the PoisonError. (There could be unsafe methods to bypass this restriction)

This is more consistent and safer, because all other owned data is dropped when a thread panics, so the same should apply to data contained in an owned mutex.

**Comment by sfackler** [comment]
> Under normal circumstances, the only requirement is that "Drop" is able to correctly handle any of the intermediate states resulting from a panic

Why is that the case? Many destructors can reference the type that's in an invalid state while the thread is unwinding.

**Comment by alexcrichton** [comment]
This was an explicit design decision of poisoning mutexes and being able to access the poisoned data as the unsafety here is **not** memory unsafety unless there is other already-`unsafe` code in play (which is the responsibility of the `unsafe` code, not poisoning).

Issues like this to change the standard library APIs [now belong](http://discuss.rust-lang.org/t/issue-categorization-changes/1417) in the RFC repo as well.

**Comment by Diggsey** [comment]
So to clarify: unsafe code must never panic at any point which might leave an object in an invalid state, even if the destructor to that object can handle that invalid state correctly? If that's true, it should really be documented in the section on unsafe code (which currently just advises putting using asserts liberally in unsafe code, and is a sure way to cause panics in the wrong place!).

It also seems difficult to guarantee as someone writing unsafe code, because there's no way to tell which methods might panic - that information is not even included in the documentation in most cases.
