### ISSUE TITLE
std::io::fs::Directories constructor

### ISSUE THREAD

**Issue by ArtemGr** [rust-lang/rust#21653]
A user should be able to construct `std::io::fs::Directories` in user code in order to extend the filesystem APIs. Right now `std::io::fs::Directories` has private fields and I don't see a constructor.

For example, I want to make a version of `walk_dir` which never returns a error, returning an empty `Directories` instead, in order to be able to write
```
  if last_modified (fail_free_walk_dir (...) .filter (...)) > last_modified (fail_free_walk_dir (...) .filter (...)) {...}
```
Curently I can't do that without moving the contents of the `Directories` into a temporary vector or making a new Iterator implementation, because `Directories` doesn't have a public constructor.

**Comment by GuillaumeGomez** [comment]
This is a part of the `old_io` now. You should take a look at the [new one](https://github.com/rust-lang/rust/blob/master/src/libstd/fs.rs#L637).
