### ISSUE TITLE
Emacs: rust-indent-method-chains indents beginning of line oddly

### ISSUE THREAD

**Issue by ProjectMoon** [rust-lang/rust#21650]
Trying out rust-mode in emacs, and set rust-indent-method-chains because I like me some aligned dots.

It does what it advertises, but for some reason shoves the beginning of the line (and thus the lines underneath it) over one more tab.

I'm using spaces for tabs, configured to width 4.

What I expect:

```rust
let x = thing.do_it()
             .aligned()
             .more_alignment();
```

What I get:

```rust
    let x = thing.do_it()
                 .aligned()
                 .more_alignment();
```

I am using el-get to install rust-mode so it should be pulling off the latest master.

**Comment by huonw** [comment]
cc https://github.com/rust-lang/rust/issues/8793

**Comment by steveklabnik** [comment]
Moved to rust-lang/rust-mode#13
