### ISSUE TITLE
Parsing of floats should be more permissive with regards to NaN and +/- inf syntax

### ISSUE THREAD

**Issue by dhardy** [rust-lang/rust#21652]
When parsing an f32, f64, etc., more special syntaxes for infinity and not-a-number should be expected:

    fn f64_parse(text: &str){
        match text.parse::<f64>(){
            Some(v) => println!("Parsing {} yields {}", text, v),
            None => println!("Parsing {} fails", text)
        };
    }
    fn main(){
        f64_parse("NaN");
        f64_parse("nan");
        f64_parse("NAN");
        f64_parse("-nan");
        f64_parse("inf");
        f64_parse("INF");
        f64_parse("infinity");
    }

Result:

    Parsing NaN yields NaN
    Parsing nan fails
    Parsing NAN fails
    Parsing -nan fails
    Parsing inf yields inf
    Parsing INF fails
    Parsing infinity fails

It is debatable whether the default parser should support all these syntaxes, but it would be very useful to have this functionality somewhere. Links:

*   [Boost's nonfinite_num_get](http://www.boost.org/doc/libs/1_47_0/libs/math/doc/sf_and_dist/html/math_toolkit/utils/fp_facets/reference.html#math_toolkit.utils.fp_facets.reference.facet__code__phrase_role__identifier__nonfinite_num_get__phrase___code_)

*   [C's strtof, etc.](http://en.cppreference.com/w/c/string/byte/strtof)

*   [C's printf (see notes at bottom of table)](http://en.cppreference.com/w/c/io/fprintf):
    
        The floating point conversion functions convert infinity to inf or
        infinity. Which one is used is implementation defined.
        Not-a-number is converted to nan or nan(char_sequence). Which one is
        used is implementation defined.
        The conversions F, E, G, A output INF, INFINITY, NAN instead.

I'm sure I've come across `-nan` (possibly different case) as well.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#854
