### ISSUE TITLE
Show other possible implementations in the "trait not implemented" message

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#21659]
Currently, if I try to index a `[T]` by a `u8` (`buf[1u8]`, or whatever), I'll get the error

```
test.rs:6:15: 6:19 error: the trait `core::ops::Index<u8>` is not implemented for the type `[u8]` [E0277]
test.rs:6 println!("{}",y[x])
```

It would be helpful in such a situation for a note saying that there _is_ an implementation of `Index<usize>`.

Basically: If a trait isn't found to be implemented, but a version of that trait with different type parameters is, show  some `help` messages containing the candidates. We do something like this already when one tries to call a nonexistent method on a type where bringing some trait into scope might make it work.

In this case, it should show something along the lines of:

```
test.rs:7:22: 7:22 help: the following implementations were found:
test.rs:7:22: 7:22 help: implementation #1: `Index<usize>`
``

**Comment by nikomatsakis** [comment]
I'd be willing to mentor this, though I'd not call it *easy*. Perhaps medium.

**Comment by Manishearth** [comment]
Agreed. (I can also provide some help on this if someone wants to work on it.)

**Comment by leejunseok** [comment]
I'd like to work on this, though I might need a lot of hand-holding. Hopefully, the mentor tag means this is acceptable?

**Comment by Manishearth** [comment]
Sounds good to me.

The relevant bits of code are [here](https://github.com/rust-lang/rust/blob/master/src/librustc/middle/traits/error_reporting.rs#L172), and the trait checks are done [here](https://github.com/rust-lang/rust/blob/d3732a12e896ab98aa27eaffab99a78bbaf837e4/src/librustc/middle/traits/select.rs).

You can get a [TraitRef](http://doc.rust-lang.org/rustc/middle/ty/struct.TraitRef.html) out of the predicate in the first link and then compare the self type with the trait, or something.

**Comment by nham** [comment]
@leejunseok Are you still working on this? If not, I'm interested in giving it a try.

**Comment by leejunseok** [comment]
nope, feel free

**Comment by fhahn** [comment]
@nham are you still working on this? If not, I would like to give it a try.

**Comment by nham** [comment]
Nope, go for it!
