### ISSUE TITLE
symbols versions are not mangled correctly

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#2166]
As part of #2137 and #456 we have added the crate version to every exported symbol, but not quite in the correct way.

Right now the final part of the path used for the symbol ends with `"V" + vers`, which gets passed through the mangler. The original design called for `@vers` but the `@` isn't a valid symbol on all platforms (I think?) so gets mangled to `_sbox_`, which is a bizarre way to indicate the version.

Mangling also makes any dots in the version go away so a version "0.2" symbol will end with "V02".

There is some additional discussion [here](https://mail.mozilla.org/pipermail/rust-dev/2010-December/000164.html) about how this is supposed to work that I haven't read.

**Comment by steveklabnik** [comment]
Is this issue still relevant today?

**Comment by arielb1** [comment]
This was fixed when we started hashing crate contents.
