### ISSUE TITLE
slice impl for [T; i] is repeated too much in rustdoc

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#21660]
The [slice](http://doc.rust-lang.org/std/primitive.slice.html#) page is huge. These `[T; N]` really need to be condensed at least in rustdoc somehow. This is absurd.

``` rust
impl<T> Clone for [T; 0] where T: Copy
...
impl<S, T> Hash<S> for [T; 0] where S: Hasher, S: Writer, T: Hash<S>
...
Repeats for 0...31 along with all the sub-functionality each `impl` brings
...
impl<T> Clone for [T; 32] where T: Copy
...
impl<S, T> Hash<S> for [T; 32] where S: Hasher, S: Writer, T: Hash<S>
```

**Comment by lifthrasiir** [comment]
`#[doc(hidden)]` for every impl but one and put a note on that one?

**Comment by mdinger** [comment]
Sounds good to me. 70% of that page is that type.

**Comment by huonw** [comment]
It seems like Rustdoc could just treat all `[T; ...]` as the same, by default (providing e.g. mouse-over text or a `[+]` button to give the exact lengths that are implemented).

**Comment by steveklabnik** [comment]
[pssssh, we're fine](https://downloads.haskell.org/~ghc/7.4.1/docs/html/libraries/ghc-prim-0.2.0.0/src/GHC-Tuple.html#%28%29)

**Comment by tomjakubowski** [comment]
@steveklabnik it's... beautiful

**Comment by tomjakubowski** [comment]
I think @lifthrasiir's suggestion is a good workaround for the standard docs but rustdoc could certainly stand to improve in this area.

**Comment by steveklabnik** [comment]
I don't forsee this getting fixed in rustdoc. Once we get type level integers, this will just go away, and until then, it's a bit gross, but other languages have basically the same issue.

It seems like I might be alone here, so I'll leave this open, but I'm really tempted to just close as WONTFIX.

**Comment by steveklabnik** [comment]
Triage: no comments in a year. I feel the same as I did then; this isn't really a rustdoc-level thing to fix.
