### ISSUE TITLE
Multiple different parameterisations of a trait in a bounds list conflict.

### ISSUE THREAD

**Issue by dylanede** [rust-lang/rust#21669]
With this preamble:
```
struct A;
struct B;

trait F<T> {}
```
this code does not compile:
```
fn f<T: F<A> + F<B>>() {}
```
but this does:
```
fn f<T>() where T : F<A> + F<B> {}
```

As an example of a case where this can't be worked around, consider associated types. This example does not seem to have any possible workaround:
```
trait G {
    type X : F<A> + F<B>;
}
```
This attempt at a workaround causes an ICE:
```
trait G where Self::X : F<A> + F<B> {
    type X;
}
```
and this example apparently isn't valid syntax:
```
trait G {
    type X where X : F<A> + F<B>;
}
```

**Comment by steveklabnik** [comment]
I don't know when this was fixed, but everything now compiles, no ICE, all forms. Except for that last one, which is indeed not valid.
