### ISSUE TITLE
Update rustdoc for feature staging changes

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#21674]
cc https://github.com/rust-lang/rust/pull/21248

I haven't even looked at rustdoc but it's support for stability levels is definitely bitrotted. At the least it needs to *not* display anything related to stability for non-staged-api cases (most cases).

Nominating because I'd like to fix this for 1.0.

**Comment by pnkfelix** [comment]
Polish issue for 1.0.  P-high.
