### ISSUE TITLE
"error: source trait is private" (fixed by adding `use` of *struct*)

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#21670]
My attempt to call `Any::get_type_id()` and use its return value of as an instance of `fmt::Debug` does not work without import of `std::any::TypeId` *struct*: http://doc.rust-lang.org/std/any/struct.TypeId.html

Example code:

```rust
use std::thread;
// use std::any::TypeId; // uncomment this line to make the compile work

fn main() {
    let b1 = Box::new(3u64);
    println!("hello world, b1: {:?}", b1);
    let child = thread::Thread::scoped(|| {
        let b2 = Box::new(4u64);
        println!("other thread b2: {:?}", b2);
    });
    match child.join() {
        Ok(()) => {}
        Err(ref panic_arg) => {
            if let Some(s) = panic_arg.downcast_ref::<&str>() {
                println!("whoops child died with str: {}", s);
            } else if let Some(s) = panic_arg.downcast_ref::<String>() {
                println!("whoops child died with String: {}", s);
            } else {
                let id = panic_arg.get_type_id();
                println!("whoops child died with unknown panic arg, id: {:?}", id);
            }
        }
    }
}
```

Transcript of attempt to compile:
```
<anon>:19:26: 19:49 error: source trait is private
<anon>:19                 let id = panic_arg.get_type_id();
                                   ^~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
playpen: application terminated with error code 101
```

**Comment by arielb1** [comment]
importing `std::any::Any` also works. I think the error message should at least talk about the relevant trait.

**Comment by pnkfelix** [comment]
@arielb1 but should we be worried that importing a struct fixed things here?  I am used to needing to import traits in order to be able to call their methods.  I'm not clear on why importing a struct fixed things here.

**Comment by steveklabnik** [comment]
Triage: updated code, made minimal:

```
use std::thread;
// use std::any::TypeId; // uncomment this line to make the compile work

fn main() {
    let child = thread::spawn(|| {
    });
    child.join().unwrap_err().get_type_id();
}
```

**Comment by jseyfried** [comment]
This happens because `resolve` only loads the items in an external module if this is needed for name resolutions (i.e. if the module appears as a non-final segment in a path). Since we build the set of external exports while loading external modules, unused external modules are not counted as exported, leading the privacy checker to incorrectly consider them to be private.
