### ISSUE TITLE
Use dwgrep to test DWARF debug information

### ISSUE THREAD

**Issue by sanxiyn** [rust-lang/rust#21679]
[dwgrep](http://developerblog.redhat.com/2015/01/22/querying-dwarf-for-fun-and-profit/) is a new tool written by Red Hat to query DWARF debug information. One explicit goal of the project is to support testing generation of DWARF debug information.

cc @michaelwoerister.

**Comment by jdm** [comment]
cc me

**Comment by michaelwoerister** [comment]
It certainly sounds interesting. There's also `llvm-dwarfdump` which LLVM uses for debuginfo autotests and [pyelftools](https://github.com/eliben/pyelftools) which also could be used for a similar purpose. I'd definitely like to do something like that when time permits.

**Comment by brson** [comment]
This is quite speculative. Better testing is always good, but I don't think we need to keep this wishlist item around.
