### ISSUE TITLE
move coerce_match{,_calls} and related tests into run-pass-valgrind

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#21696]
Put (copies of?) coerce_match{,_calls} and related tests into run-pass-valgrind.  Because our current testing infrastructure is not aggressive enough in checking that tests like this are actually behaving in a sound manner.

spawned off of: https://github.com/rust-lang/rust/issues/20055#issuecomment-69090732

(I did not attempt this in PR #21692 because I wanted to expedite landing the fix for the trans bug.)

**Comment by pnkfelix** [comment]
@nick29581 clarified the situation to me: even if `valgrind` is not available on a host, the tests in `run-pass-valgrind` will be run (just without `valgrind` checking them).

So  resolving this is probably just a matter of moving the tests over.

**Comment by steveklabnik** [comment]
Triage: it looks like these two tests are not yet in `src/test/run-pass-valgrind/`. This should be easy to do, though which tests exactly are "related" isn't quite clear to me.

**Comment by brson** [comment]
Triage: no news.
