### ISSUE TITLE
Document trait objects in the book

### ISSUE THREAD

**Issue by krdln** [rust-lang/rust#21707]
Trait objects seem not to be documented at all in the book, which together with their mandatory lifetime bound annotation makes them almost undiscoverable. Fortunately, there are some nice [blog posts](http://huonw.github.io/blog/2015/01/peeking-inside-trait-objects/) by @huonw, but they are unlikely for a user to stumble upon.

Also, the only occurence of 'trait object' in the reference is following sentence, which is strange:

> Likewise, supertrait methods may also be called on trait objects.

**Comment by steveklabnik** [comment]
Yes, this has been on my list a long time.
