### ISSUE TITLE
typo on the alpha book testing guide

### ISSUE THREAD

**Issue by bionicman08** [rust-lang/rust#21700]
The first code sample below The tests directory heading has a missing ! after the assert_eq.

direct link so you can see quicker.

http://doc.rust-lang.org/1.0.0-alpha/book/testing.html#the-tests-directory

**Comment by aaronraimist** [comment]
That HTML file is made from [this markdown](https://github.com/rust-lang/rust/blob/f4f10dba2975b51c2d2c92157018db3ac13d4d4a/src/doc/trpl/testing.md#the-tests-directory) right? Looks like its already in there and the docs just need to be rebuilt.

**Comment by steveklabnik** [comment]
Ah yes. That was messed up at the alpha release, but has since been fixed. See http://doc.rust-lang.org/book/testing.html#the-tests-directory
