### ISSUE TITLE
Documentation for Vec does not list `iter()` method

### ISSUE THREAD

**Issue by Swatinem** [rust-lang/rust#21728]
So rustdoc does not list the `.iter()` method on the page for Vec itself.
This might be extremely confusing for newcomers.

Actually `impl<T> Deref for Vec<T> type Target = [T]`
And `impl<T> SliceExt for [T]`
And SliceExt defines the `.iter()` method.

So this does all make sense, but I don’t think a newcomer can wrap his head around that. I spent 5 minutes looking this up myself after I introduced Rust to a group of people.

**Comment by steveklabnik** [comment]
We have an issue open already to improve rustdoc's handling of Deref, so I'm gonna give this a close.

I 100% agree with you that this is a current pain point. The beta cycle is going to be dedicated to polish, and this is high on my list. But I don't want to keep two issues open. Thank you!

**Comment by Swatinem** [comment]
This is #19190 just for reference, thanks!

**Comment by steveklabnik** [comment]
Ahh yeah, sorry, I was on mobile and forgot to link it :(

**Comment by vi** [comment]
+1, I have got stopped and fell back to IRC because of this.
