### ISSUE TITLE
llvm::StructType::getElementType: Assertion `N < NumContainedTys && "Element number out of range!"' failed.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#21721]
```rust
pub fn maybe_ptr() -> *const u8 {
    static NONE: Option<((), &'static u8)> = None;
    unsafe {
        *(&NONE as *const _ as *const *const u8)
    }
}
```
Running this in [the playpen](http://is.gd/NaIyoH) gives:
```
rustc: /build/rust-git/src/rust/src/llvm/include/llvm/IR/DerivedTypes.h:285: llvm::Type* llvm::StructType::getElementType(unsigned int) const: Assertion `N < NumContainedTys && "Element number out of range!"' failed.
Aborted (core dumped)
```
This is actually happening inside LLVM optimizations, in the `early-cse` pass (`-C opt-level=1` still triggers it). Originally found in a `memcpy` optimized into a `load`.
Reduced LLVM IR:
```llvm
target datalayout = "e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@NONE = internal constant { { {}, i8* } } zeroinitializer

define i8* @maybe_ptr() {
entry-block:
  %0 = load i8** bitcast ({ { {}, i8* } }* @NONE to i8**)
  ret i8* %0
}
```
cc @dotdash

**Comment by eddyb** [comment]
Current LLVM fork tip: rust-lang/llvm@b820135 on top of llvm-mirror/llvm@0ad623b.

**Comment by dotdash** [comment]
http://llvm.org/bugs/show_bug.cgi?id=22595

**Comment by eddyb** [comment]
Were the relevant hacks removed from the source?

**Comment by eddyb** [comment]
This needs a test, and there's also two hacks introduced by #21744, that should be reverted now that the LLVM bug is fixed (they both reference this issue).

**Comment by dotdash** [comment]
@eddyb will you take care of that?

**Comment by pczarn** [comment]
I'm still getting this failure in  #21973

**Comment by dotdash** [comment]
I guess you get that in stage0? That will need a new snapshot, so that the
stage0 compiler also uses the new LLVM
Am 26.02.2015 20:40 schrieb "Piotr Czarnecki" <notifications@github.com>:
