### ISSUE TITLE
Improve IO code

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#21732]
Relevant reddit thread: http://www.reddit.com/r/rust/comments/2u057m/testing_rusts_io_speed_vs_c/

The biggest problem in the example is that the `write` method isn't being inlined. Secondly the Writer contained in BufferedWriter is stored in an Option. Thirdly stdout_raw has non-negligible cruft that might or might not get optimized away.

The IO code is probably full of this stuff. Some improvements might require changing the interface.

After careful optimization, the Rust code runs faster than the C code.

**Comment by steveklabnik** [comment]
and HN: https://news.ycombinator.com/item?id=8962853#up_8963530
