### ISSUE TITLE
Stability levels on associated types seem to be being ignored

### ISSUE THREAD

**Issue by chris-morgan** [rust-lang/rust#21746]
In the code, associated types like `Iterator::Item` are marked `#[stable]`, but in the generated documentation they are marked as having no stability level. This appears to end up going into the stability dashboard as well; after #21745 lands, I think that almost all of the remaining unmarked items are associated types.

**Comment by brson** [comment]
Nominating. Not sure if this is a rustdoc-specific bug, but if assoc types are incorrectly handled by the compiler that would be a big gap.

**Comment by aturon** [comment]
cc me

**Comment by pnkfelix** [comment]
we need to do more analysis to know how far this bug goes before we categorize it.

**Comment by pnkfelix** [comment]
1.0, P-low.

**Comment by alexcrichton** [comment]
I believe this was fixed in the interim as I just confirmed that these are indeed being read now.
