### ISSUE TITLE
I can not find the time crate, how can i get current time using rust

### ISSUE THREAD

**Issue by FillZpp** [rust-lang/rust#21742]
I want to test the efficiency of file i/o, but i don't know how to get current time for timing.

I find [http://stackoverflow.com/questions/26593387/how-i-get-the-current-time-in-milliseconds](http://stackoverflow.com/questions/26593387/how-i-get-the-current-time-in-milliseconds), but with the latest version `rustc 1.0.0-nightly (92ff8ea52 2015-01-27 23:08:13 +0000)`, it shows `error: can't find crate for time`.

Also i search the API, but only get `std::time` and `std::old_io::timer`, neither can help me.

So how can i get time?

**Comment by bungcip** [comment]
time crate already moved to https://crates.io/crates/time
