### ISSUE TITLE
add limited timed wait to semaphore

### ISSUE THREAD

**Issue by drewcrawford** [rust-lang/rust#21741]
I think Semaphore could use timeout variants of `acquire` and `access`, besides just blocking forever.

The underlying Condvar [already has timeout support](https://github.com/rust-lang/rust/issues/17094), so it's just a matter of bubbling it up to semaphore.  Looking at [sempahore.rs](https://github.com/rust-lang/rust/blob/master/src/libstd/sync/semaphore.rs#L74), it seems like low-hanging fruit to add.

I think the biggest question is whether it should be called `acquire_timeout` and `access_timeout` (following Condvar's `wait_timeout`) or whether it should be called `try_acquire` and `try_access` (following Mutex and RwLock).

 If there's a decision rendered on the syntax, this would be a good feature for a new contributor.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#853
