### ISSUE TITLE
Bad behaviour with break in while-loop condition

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#21751]
If you put a `break` in the condition of a while-loop, the compiler code seems to exhibit undefined behaviour.

For example, in `play.rust-lang.org`, this SIGILL-s when `-O0` and prints 5 blank lines when `-O2`:

``` Rust
fn main() {
    for _ in 0..5 {
        while { break; } { println!("never"); }
        println!("?");
    }
}
```

**Comment by pnkfelix** [comment]
Seems like this may have been fixed?

Marking as needs-test.

**Comment by untitaker** [comment]
This SIGILLs for me at `rustc 1.1.0-nightly (f9e53c7f2 2015-04-24) (built 2015-04-25)`.

**Comment by pnkfelix** [comment]
indeed, removing the E-needstest label.

**Comment by pnkfelix** [comment]
Interestingly, adding explicit labels to both of the loops and then making the `break` go directly to either label exhibits entirely different behaviors -- in particular, breaking out of the `for` seems to work fine, and attempting to break out of the `while` from its own condition is statically rejected.

I wonder if this means that this is some sort of `trans` issue where it is simply guessing incorrectly for what the target of the `break` should be?  (At least, I would think that the `break` in the original code is breaking out of the `foo`-loop...)

**Comment by untitaker** [comment]
Removing the wrapping braces around `break` gives the correct behavior.

**Comment by apasel422** [comment]
Still an issue.

**Comment by leodasvacas** [comment]
Triage: The code in the OP is working fine in the playpen for Debug and Release. 

This seems fixed, however the scenario with labels described by @pnkfelix ICEs, I have opened #37353 to track that.

**Comment by nikomatsakis** [comment]
The original example does not work fine -- the `println("?")` line prints "unreachable statement", though it does indeed execute:

```
rustc 1.15.1 (021bd294c 2017-02-08)
warning: unreachable statement, #[warn(unreachable_code)] on by default
 --> <anon>:3:28
  |
3 |         while { break; } { println!("never"); }
  |                            ^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in a macro outside of the current crate

warning: unreachable statement, #[warn(unreachable_code)] on by default
 --> <anon>:4:9
  |
4 |         println!("?");
  |         ^^^^^^^^^^^^^^
  |
  = note: this error originates in a macro outside of the current crate

?
?
?
?
?

Program ended.
```

**Comment by nikomatsakis** [comment]
I'm going to close this issue in favor of #37576 which includes more examples and the official decision (that this code ought to be an error -- `break` with no label in while condition is counter-intuitive and should not be accepted).
