### ISSUE TITLE
`pub extern crate foo;` doesn't work

### ISSUE THREAD

**Issue by bvssvni** [rust-lang/rust#21757]
```Rust
pub extern crate foo;
```

vs

```Rust
extern crate "foo" as foo_lib;
pub use foo_lib as foo;
```

The second version works with [piston](https://github.com/pistondevelopers/piston) but the first one doesn't. Tested by overriding dependency locally with the [image](https://github.com/PistonDevelopers/piston-examples/tree/master/image) example in Piston.

cc @eddyb @kimundi

**Comment by sfackler** [comment]
I thought we disallowed `pub extern crate` entirely?

**Comment by Kimundi** [comment]
See https://github.com/rust-lang/rfcs/pull/385

**Comment by frewsxcv** [comment]
So should the `pub` actually have any effect? From my experiences this is still an issue (adding `pub` doesn't publicize the external crate)

**Comment by Kimundi** [comment]
It should have the effect of making the extern crate item externally reachable from the module.

**Comment by frewsxcv** [comment]
Oh, I guess that makes sense. I originally thought that adding a `pub` would make it visible *outside* the module in addition to *inside*.

It might be nice if there was a section in the docs about the `pub` prefix for `extern crate`

https://doc.rust-lang.org/stable/reference.html#extern-crate-declarations

**Comment by filsmick** [comment]
This just bit me, the `pub` should behave as expected or not compile.

**Comment by nrc** [comment]
dup of #26775
