### ISSUE TITLE
Bug in Rust book: outdated closure syntax

### ISSUE THREAD

**Issue by BitPuffin** [rust-lang/rust#21766]
http://doc.rust-lang.org/1.0.0-alpha/book/closures.html#accepting-closures-as-arguments

``` rust
fn twice<F: Fn(i32) -> i32>(x: i32, f: F) -> i32 {
    f(x) + f(x)
}
```

```
Next, let's look at how twice is defined:

fn twice(x: i32, f: |i32| -> i32) -> i32 {
```

```
Okay, let's look at the body of twice:

fn twice<F: Fn(i32) -> i32>(x: i32, f: F) -> i32 {
  f(x) + f(x)
}
```

**Comment by steveklabnik** [comment]
You're looking at the 1.0.0-alpha docs. If you look at nightly, http://doc.rust-lang.org/book/closures.html#accepting-closures-as-arguments , this has already been fixed. Thank you for reporting though!

**Comment by BitPuffin** [comment]
Ah sorry. I was wondering if that would be the case, but I figured docs are supposed to be "backported"

Cheers!

**Comment by steveklabnik** [comment]
Ahh yeah, we don't currently back port anything, as we technically haven't even had a stable release yet. =
