### ISSUE TITLE
debugging trans: initialize drop-flag byte with special pattern and check for it on drop

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#21777]
So, there are sometimes bugs in trans related to allocating stack slots for temporary values, but not properly ensuring that the slots are either always initialized or start off with the drop flag zeroed.

A way we could try to guard for such bugs would be: in debug builds, initialize the drop flag with a non-trivial bit pattern, and then check for that bit pattern when dropping the value.

I strongly suspect a check like this would have helped us track down the cause of #20055 faster.

**Comment by steveklabnik** [comment]
Triage: I'm not aware of any changes here.

**Comment by pnkfelix** [comment]
Oh I think I actually did this.

**Comment by pnkfelix** [comment]
Yeah fixed by #23535 (the `force-dropflag-checks` switch).
