### ISSUE TITLE
Emacs: '"' (double-quote char) breaks syntax highlighting

### ISSUE THREAD

**Issue by tgkokk** [rust-lang/rust#21776]
Apparently, `rust-mode` thinks that `"` starts a string (that's why in the next line `{}` is not highlighted).

![screen shot 2015-01-30 at 14 30 32](https://cloud.githubusercontent.com/assets/801854/5975686/9ddb9490-a88c-11e4-834c-4b6059a0517c.png)

**Comment by nagisa** [comment]
Report the issue against https://github.com/rust-lang/rust-mode.

**Comment by tgkokk** [comment]
Reported in rust-lang/rust-mode#1,
