### ISSUE TITLE
Wrong name used in code example in Rust reference 

### ISSUE THREAD

**Issue by dsyang** [rust-lang/rust#21770]
In the Use Declarations section of the rust reference manual (http://doc.rust-lang.org/reference.html#use-declarations),   the third code example has the following line
`//  use core::iter;      // bad:  native is not at the crate root`
I think the comment should read: 
`// bad: core is not at the crate root` or something else.  It shouldn't reference native because native isn't used anywhere in the code example.

**Comment by dsyang** [comment]
I'd be willing to submit a PR if someone could check to see if my reasoning is correct.

**Comment by steveklabnik** [comment]
When in doubt, the reference is probably wrong :wink: I have it scheduled to update during the beta period, and so I believe you are correct. A PR would be great, thanks!=

**Comment by alexcrichton** [comment]
Fixed in #21819
