### ISSUE TITLE
Rustdoc renders some deprecated symbols as unstable.

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#21789]
http://doc.rust-lang.org/std/sync/atomic/struct.AtomicInt.html is rendered as unstable while it has deprecated attribute on it.

**Comment by tomjakubowski** [comment]
It's actually got both attributes on it. I don't know how the stability stuff is supposed to sort that out.

**Comment by lfairy** [comment]
A good first step would be to give `deprecated` precedence over `unstable`.
