### ISSUE TITLE
Running the code on www.rust-lang.org doesn't work

### ISSUE THREAD

**Issue by XrXr** [rust-lang/rust#21781]
Go to www.rust-lang.org and click on run, it will show `Running...` forever.

Looking at Chrome's console, this seems to be an issue with www.rust-lang.org served over HTTP instead of HTTPS like play.rust-lang.org.

` XMLHttpRequest cannot load http://play.rust-lang.org/evaluate.json. The request was redirected to 'https://play.rust-lang.org/evaluate.json', which is disallowed for cross-origin requests that require preflight.
(index):377 Uncaught TypeError: Cannot read property 'split' of null
`

See also #13180

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rust-lang/rust-www/commit/70657587744ff07238d38b9f2cbfe4cd8a4d9a7c, but thanks!
