### ISSUE TITLE
#[feature(test)] is not ergonomic

### ISSUE THREAD

**Issue by cgaebel** [rust-lang/rust#21784]
Right now, I have code that looks like:

```rust
#[cfg(test)] extern crate test;
```

which is a pretty standard way of getting test suites enabled in a crate, while only linking to the test crate when testing.

With `#![feature(test)]` required today, I also need to add `#![allow(unused_features)]` to cover non-test builds. I also can't conditionally enable a feature in test builds only. This is pretty unergonomic.

**Comment by reem** [comment]
Use `#[cfg_attr(test, feature(test))]`. I agree that this is not the best, but at least it works.

**Comment by Zarathustra30** [comment]
Can this be closed? `test` is stable, but `unused_features` still warns when the feature is used in a different configuration.

**Comment by Stebalien** [comment]
@Zarathustra30 `#[test]` is stable but the test crate isn't. That is, the following is stable:

```rust
#[test]
fn my_test() {
}
```

However, things like benchmarking requires importing the test crate itself which isn't stable:

```rust
#[feature(test)]
extern crate test;

#[bench]
fn my_bench(b: &mut test::Bencher /* needed here */) {
}
```

**Comment by steveklabnik** [comment]
Regardless it does seem true that this is Not A  Bug, so I'm gonna give it a close.
