### ISSUE TITLE
Error and .unwrap() do not agree on traits

### ISSUE THREAD

**Issue by maurer** [rust-lang/rust#21790]
```Error``` currently requires ```Display```, while ```.unwrap()``` requires ```Debug```.

I'm unsure of what each should require, but I think they should agree so that it is possible to have code which returns ```Result<_, Box<Error>>``` (which is useful to allow try! across functions returning different types of error codes), and be able to ```.unwrap()``` the results.

**Comment by Stebalien** [comment]
There was a lengthy discussion about this towards the bottom of the RFC: https://github.com/rust-lang/rfcs/pull/565.

**Comment by aturon** [comment]
Nominating for 1.0-beta P-backcompat-libs.

(The `Error` trait isn't `#[stable]` yet, but it probably will be for 1.0).

**Comment by pnkfelix** [comment]
1.0 beta, P-backcompat-libs, I-needs-decision.
