### ISSUE TITLE
Dot operator is missing from precedence chart

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#21799]
The reference [precedence chart](http://doc.rust-lang.org/reference.html#operator-precedence) is missing the `structure.method` dot (`.`) operator.

Consensus on IRC is that it's unclear if it's this same type of operator but if it was, it'd have highest precedence. So I'm unsure whether to add it or not.

**Comment by steveklabnik** [comment]
Yes, this is not an operator in Rust.
