### ISSUE TITLE
unused_features warn by default?

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#21798]
With `unused_features` set to 'deny' by default, every time nightly stabilizes a feature your crate uses then it will break.

cc @alexcrichton
cc http://users.rust-lang.org/t/psa-important-info-about-rustcs-new-feature-staging/82/4?u=brson

**Comment by apasel422** [comment]
What still needs to be done here?

**Comment by steveklabnik** [comment]
```
hello.rs:1:12: 1:16 warning: unused or unknown feature, #[warn(unused_features)] on by default
hello.rs:1 #![feature(tail)]
                      ^~~~
```

looks like this is still here and working, so closing.
