### ISSUE TITLE
The book readme should list all documentation types

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#21796]
The [intro](http://doc.rust-lang.org/book/README.html) should state what types of documentation are available as learning resources. It should link to the [std docs](http://doc.rust-lang.org/std/index.html), the [reference](http://doc.rust-lang.org/reference.html) and to [rustbyexample](http://rustbyexample.com/) stating what each offers the learner. It is basically where everyone may start looking.

Rustbyexample isn't prominently shown on the [rust-lang.org](http://www.rust-lang.org/) page. It's there but *More examples* doesn't suggest a resource. Just more hello worlds. The intro actually has space to detail which of these resources someone is looking for.

**Comment by mdinger** [comment]
Actually, most of [All docs](http://doc.rust-lang.org/index.html) could easily go into the intro and it might not be out of place.

**Comment by steveklabnik** [comment]
The intro is an intro to the book, this information belongs on the doc index page, where it already is.
