### ISSUE TITLE
rustdoc fails finding external crates when using crate alias

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#21795]
Basic example:

Given a file `meow.rs` with the following contents:

```rust
extern crate "rustc-serialize" as foobar;
```

...executing the command:

```sh
rustdoc meow.rs
```

Results in:

```rust
meow.rs:1:1: 1:42 error: can't find crate for `foobar`
meow.rs:1 extern crate "rustc-serialize" as foobar;
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
thread '<unnamed>' panicked at 'Box<Any>', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libsyntax/diagnostic.rs:151
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "rustc failed"', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:743
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/option.rs:362
```

The issue is that it's looking for docs for the crate `foobar` (the alias) instead of the actual crate `rustc-serialize`.

**Comment by tomjakubowski** [comment]
I can't replicate this. Are you sure the `rustc-serialize` crate is in your library path? If you run:

```
$ rustc meow.rs
```

Does it compile?

I can, for example, generate docs for this just fine, because the Rust nightly ships with the `alloc` crate:

```rust
extern crate "alloc" as foobar;
```

**Comment by frewsxcv** [comment]
Nevermind. I didn't realize there was a `cargo doc` command. I thought `rustdoc` would look at the local library path. Sorry for the noise.
