### ISSUE TITLE
rustdoc: Fn trait sugar output types are broken for inlined signatures

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang/rust#21801]
For example, see: http://doc.rust-lang.org/std/collections/struct.Bitv.html#method.from_fn

```rust
fn from_fn<F>(len: usize, f: F) -> Bitv 
where F: FnMut(usize), <F as FnMut(usize)>::Output == bool
```

Should look like:

```rust
fn from_fn<F>(len: usize, f: F) -> Bitv 
where F: FnMut(usize) -> bool
```

This is because of the change to use associated types for the output.

**Comment by tomjakubowski** [comment]
Specifically, this:

https://github.com/rust-lang/rust/commit/ac94ae5883dd4efecebd9b5fece770910637b988#diff-6ad072c1ebc79b7620832915f2323d55R550

Like all "resugaring" of projection predicates, rustdoc will need to merge the `F: Fn(usize)` and `<F as FnMut(usize)>::Output == bool` bounds into one, which will likely mean an extra step when cleaning `ty::Generics`, after cleaning the individual `ty::Predicates` in the `predicates` field.

**Comment by tomjakubowski** [comment]
I can't nominate issues but I think this is crucial for 1.0 because of the pervasive use of closures in the standard library. Rendering `Fn` trait bounds this way all over `std` is not going to do Rust any PR favors.

**Comment by pnkfelix** [comment]
1.0 polish
