### ISSUE TITLE
Add method to obtain useful system hardware information

### ISSUE THREAD

**Issue by boggle** [rust-lang/rust#2181]
For implementing a new hash table, I'd like to know the size of cache lines.  In general, we probably want a way to provide technical information like that in std (or perhaps even in core).  For now, I'm just intending to add a sys info module that will have CACHE_LINE_SIZE and CACHE_LINE_BITS constants.  I found some code for this on the internet and would like to know if it is ok LICENSE-wise to put "do-what-you-want-with-it-licensed C bits" like that into rust:

http://stackoverflow.com/questions/794632/programmatically-get-the-cache-line-size

**Comment by steveklabnik** [comment]
We're making the standard library smaller and smaller these days. Unless there's a particular reason why this would have to be in the language itself, this should be a Cargo package now.
