### ISSUE TITLE
std::default::Default::default() is very default by default

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust#21810]
`::std::default::Default::default()` (or `use ::std::default::Default; Default::default()`) is long, prone to off-by-one-default mistakes, and looks silly.

I wanted to use default values to save myself typing of all the struct fields, but importing and using Default doesn't save me much typing :)

Could the path be shortened? e.g. by making a function `::std::default::default()` or adding `Default` to prelude?

**Comment by Gankro** [comment]
It has been proposed (informally) that one should be able to import a static trait method as a function. that is:

`use std::default::Default::default; default();`  

would Just Work.

See also: http://internals.rust-lang.org/t/allow-a-trailing-in-a-struct-literal-meaning-default-default/885

**Comment by alexcrichton** [comment]
Thanks for the report! I think that this issue may be more appropriately placed in a different location, however. Modifications to the prelude would require an RFC (or an issue in the RFC repo) and other general discussion about the verbosity and possible other solutions would be a good candidate for http://users.rust-lang.org/.
