### ISSUE TITLE
tests failing in Arch chrooted environment

### ISSUE THREAD

**Issue by anatol** [rust-lang/rust#21821]
I am trying to build rust package (1.0.0-alpha) on my Linux Arch build computer. I use chrooted build environment that provides clean version of root filesystem with minimum build packages required.

Some tests are failing. If I build the same package out of chroot environment then the tests are passed. Here are build/tests logs for failed run:

https://gist.github.com/anatol/a302e1dfd7f52f198b34
https://gist.github.com/anatol/4618246b70ccd9e4f222

There are several "failed to compile" error messages but there is no additional info besides it. There might be some problem with chroot/container environment.

**Comment by steveklabnik** [comment]
Triage: it's been a year. Are you still seeing this, @anatol ?

**Comment by bltavares** [comment]
Triage: I'm not able to read the gists anymore.

There is a [glacier error](https://github.com/steveklabnik/glacier/blob/master/16229.sh) tracking execution errors on chroot environments, but none for the compilation.

I was not able to acquire an chrooted Arch environment to test the compilation.

**Comment by Mark-Simulacrum** [comment]
Without more information, including unreadable gists, and the age of this issue, I'm going to close--but if someone with access to a chrooted Arch environment tests and finds this is still a problem, we'd be happy to reopen.
