### ISSUE TITLE
Doc comments are allowed on match arms

### ISSUE THREAD

**Issue by simias** [rust-lang/rust#21823]
A very minor issue but I noticed that rustc accepts to build code like this:

``` rust
fn main() {
    match () {
        /// doc
        _ => (),
    };
}
```

I would expect an error at `/// doc` since there's no item to document here.

**Comment by alexchandel** [comment]
I would expect no error, just no documentation. Does rustdoc produce anything for this?

**Comment by simias** [comment]
@alexchandel The problem is that using `///` where it doesn't make sense usually produces an error, for instance this won't compile:

```rust
fn main() {
    /// Say hello world
    println!("Hello, world!")
}
```

```
<anon>:2:5: 2:24 error: expected item after doc comment
<anon>:2     /// Say hello world
             ^~~~~~~~~~~~~~~~~~~
```

So it's not very coherent.

**Comment by sfackler** [comment]
It's parses because attributes are allowed on match arms, and `/// foo` desugars to `#[doc = "foo"]`.

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by simias** [comment]
Sounds acceptable, should I close this? It was not a huge issue to begin with.
