### ISSUE TITLE
Slight issue in book (Compound Data Types section)

### ISSUE THREAD

**Issue by budleigh** [rust-lang/rust#21829]
In one of the tuple examples in the compound data types section (beginner), the docs show that

```rust
let x = (1, 2, 3);
let y = (2, 2, 4);
```
are not equivalent tuples by saying the following:

> This will print no, because some of the values aren't equal.

To me, this implies that the following WOULD be equivalent:

```rust
let x = (1, 2, 3);
let y = (2, 1, 3);
```

because all of the *values* are the same, but the compiler says the tuples are different. Perhaps add a note about value ordering being important to tuple equivalency or show another example.

**Comment by steveklabnik** [comment]
Agreed, this should be clarified.

**Comment by mdinger** [comment]
Looks fixed by https://github.com/rust-lang/rust/pull/22007
