### ISSUE TITLE
Feature-gate #[no_std]

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#21833]
It breaks various things at the syntax layer, e.g.  #21827, #16803, #14342.  I plan to fix those before the beta but I'm not sure what other issues there are.

**Comment by sfackler** [comment]
If we feature gate this, it'd be nice to move std injection either into expansion or after it. Right now you can't do `#![cfg_attr(feature = "foo", no_std)]`, which means that crates that want to compile both in normal and `no_std` contexts have to use no_std everywhere and manually link to `std`. For example, take rust-phf: https://github.com/sfackler/rust-phf/commit/24555b19e6b54656633cc4ceac91864f14c20471.

**Comment by pnkfelix** [comment]
1.0 beta
