### ISSUE TITLE
Glob Import Bug

### ISSUE THREAD

**Issue by JustAPerson** [rust-lang/rust#21831]
While reorganizing my code, I encountered some strange errors related to glob imports. Removing either of the glob imports causes the (unrelated error) to no longer occur.

[Here is my test case](https://gist.github.com/JustAPerson/1b247f812e01572ffdc2)

```
$ rustc --version
rustc 1.0.0-nightly (c5961ad06 2015-01-28 21:49:38 +0000)
```

**Comment by sfackler** [comment]
Looks like it could be a dup of #18083

**Comment by JustAPerson** [comment]
No longer reproduces (on nightly at least, probably fixed a while ago).
