### ISSUE TITLE
Multiple *stable* iterator adaptors have useless type parameters

### ISSUE THREAD

**Issue by Tobba** [rust-lang/rust#21839]
For example
```
#[stable(feature = "rust1", since = "1.0.0")]
pub struct Peekable<T, I> where I: Iterator<Item=T> {
    iter: I,
    peeked: Option<T>,
}
```

Here the T type parameter is completely useless as it's always going to be equal to I::Item, and this is present in nearly every iterator adaptor, all which are marked **stable**.

**Comment by bluss** [comment]
Several of them would have had to change anyway to obey the new impl check rules. Don't know if the situation has changed since then (updated orphan rules again etc).
