### ISSUE TITLE
pub const items have no linker symbol

### ISSUE THREAD

**Issue by richo** [rust-lang/rust#21856]
```rust
#[no_mangle]
pub const THING: libc::c_int = 42;
```

Will not actually be exported in the resulting object. There are two obvious fixes, the first being to expand on my pub-not-exported lint to warn you that this will not work, the second being to fix the compiler to export the symbol with the appropriate value (Without altering the existing inlining behaviour, although it may give a more reasonable option for cases like trying to take the address of a `const`item).

Happy to work on either, although I would need a mentor for the second part.

**Comment by tomjakubowski** [comment]
I'm not sure what you mean by it not being exported. It might not be visible as a symbol (if you're linking from C or something), but you can certainly reference that item from another Rust crate.

**Comment by richo** [comment]
Sorry for not being clear. That's exactly what I meant, the symbol is not visible in the resulting object.

This is pretty confusing (I've been doing a lot of C(++) <-> Rust lately and I'm trying to make the compiler warn people about all the things that have tripped me up)

**Comment by kmcallister** [comment]
I think the right option is to expand the lint.  The whole difference between `const` and `static` is that the former isn't guaranteed to have a location in memory.  To a C programmer it's like a `#define` variable.

**Comment by richo** [comment]
Sounds totally reasonable. I'll expand the lint.

**Comment by tomjakubowski** [comment]
Ah, I see now. I didn't know there was a lint for `#[no_mangle]` on non-exported items. That explains a lot!
