### ISSUE TITLE
sync_channel(0) completely broken when used with Select

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#21851]
```rust
#![feature(std_misc, io)]

use std::sync::mpsc::{sync_channel, Select};
use std::old_io::timer::{sleep};
use std::time::duration::{Duration};
use std::thread::{Thread};

fn main() {
    let (snd, rcv) = sync_channel(0);

    Thread::spawn(move || {
        if snd.send(0u8).is_ok() {
            panic!();
        }
    });

    let select = Select::new();

    let mut handle = select.handle(&rcv);
    unsafe { handle.add(); }

    select.wait();

    sleep(Duration::milliseconds(1));
}
```
```
thread '<unnamed>' panicked at 'explicit panic', test4.rs:13
```
As you can see, `recv` is never called on `rcv`.

This panics because `send` checks if there is someone sleeping on the "notification" condvar in a `BlockedReceiver` variant. `Select::wait` adds such a variant to get notified when there is a sender.

**Comment by LorenVS** [comment]
At an initial glance, this code looks like it should panic, and like that is the expected behavior. The send blocks until there is a corresponding receive call, which happens because of the select call. Once the send succeeds, a panic is forced.

Am I missing something?
