### ISSUE TITLE
document `where` keyword

### ISSUE THREAD

**Issue by kraemahz** [rust-lang/rust#21859]
Inspired by a short dialog on irc:

>20:04	kraemahz	How do I tell rust the type of an iterator? `<T: Iterator<usize>>(iter: T)` and `<T: Iterator>(iter: T<usize>)` don't work
>20:05	Mutabah	kraemahz: `Iterator<Item=usize>`
>20:05	kraemahz	thanks
>20:06	Yurume	which is short for `fn foo<T: Iterator>(iter: T) where <T as Iterator>::Item == usize` afaik.

The `where` keyword is not mentioned in [Iterators](http://doc.rust-lang.org/book/iterators.html), [Generics](http://doc.rust-lang.org/book/generics.html), or [Traits](http://doc.rust-lang.org/book/traits.html) docs despite its use in base types like Iterator.

**Comment by steveklabnik** [comment]
Yup, this is on my list. Thanks for the issue.

**Comment by jroesch** [comment]
cc me
