### ISSUE TITLE
Metadata ICE on clean build

### ISSUE THREAD

**Issue by zwizwa** [rust-lang/rust#21867]
To reproduce:
https://github.com/zwizwa/lars
d0a9cae2d174c181f80a3e2716118dd59945be78 bug compiling la.elf
( make la.elf )

This is on Debian wheezy/jessie/sid cocktail.

rustc 1.0.0-nightly (1d00c545e 2015-01-30 19:56:34 +0000)
binary: rustc
commit-hash: 1d00c545ede609b9d43fdf9f252c15da5a66dac7
commit-date: 2015-01-30 19:56:34 +0000
host: x86_64-unknown-linux-gnu
release: 1.0.0-nightly

[master] tom@zoo:~/lars$ make la.elf
RUST_BACKTRACE=1 rustc la.rs -o la.elf
ERROR:rbml::reader: failed to find block with tag 7
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'explicit panic', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librbml/lib.rs:266

stack backtrace:
   1:     0x2b9353530870 - sys::backtrace::write::h26b40214a7757117H8t
   2:     0x2b9353553be0 - failure::on_fail::h7a79bf921b6662fbzkB
   3:     0x2b93534c01f0 - rt::unwind::begin_unwind_inner::hfe1c0e12f5e834cfAZA
   4:     0x2b935a46b550 - rt::unwind::begin_unwind::h13771489483523584678
   5:     0x2b935a46a2e0 - reader::get_doc::hca9c74691b431218nLa
   6:     0x2b93553feac0 - metadata::decoder::item_type::h11e3fdce04437c2aTqh
   7:     0x2b935540fa40 - metadata::decoder::get_type::h81f5136878596756uDh
   8:     0x2b93553be9b0 - metadata::csearch::get_type::h9b0725336787e95fjuk
   9:     0x2b9353fb38d0 - collect::CollectCtxt<'a, 'tcx>.AstConv<'tcx>::get_item_type_scheme::ha84927afd1cd11a416u
  10:     0x2b9353fa2550 - astconv::ast_path_to_ty::h5eef35501e32996d3It
  11:     0x2b9353fa3a40 - astconv::ast_ty_to_ty::closure.32670
  12:     0x2b9353f3d7f0 - astconv::ast_ty_to_ty::hdfd5055274123a4bN9t
  13:     0x2b9353f9c060 - vec::Vec<T>.FromIterator<T>::from_iter::h13503769950079175686
  14:     0x2b9353f99cc0 - astconv::convert_angle_bracketed_parameters::h9025012b833df2f4Vit
  15:     0x2b9353f3d260 - astconv::ast_path_substs_for_ty::hb223d380e0653eb777s
  16:     0x2b9353fa2550 - astconv::ast_path_to_ty::h5eef35501e32996d3It
  17:     0x2b9353fa3a40 - astconv::ast_ty_to_ty::closure.32670
  18:     0x2b9353f3d7f0 - astconv::ast_ty_to_ty::hdfd5055274123a4bN9t
  19:     0x2b9353f9cb70 - astconv::convert_ty_with_lifetime_elision::h6aef1296b36bbcec2mt
  20:     0x2b9353fa78d0 - astconv::ty_of_method_or_bare_fn::hfbbddbe9dd8fd2d8Dtu
  21:     0x2b9353fa7750 - astconv::ty_of_method::h90bdcfba9a641a98Zru
  22:     0x2b9353fcba40 - collect::convert_methods::ty_of_method::h37cc71cdb4ced048svv
  23:     0x2b9353fb94e0 - collect::convert::hbd254ededfa34065yyv
  24:     0x2b9353ff3670 - check_crate::closure.33797
  25:     0x2b9353ff15b0 - check_crate::hd5b0ce5ac42bd86cIEz
  26:     0x2b935311bf50 - driver::phase_3_run_analysis_passes::h3a3da09b2eae9713NFa
  27:     0x2b9353103330 - driver::compile_input::h802d2a6759ac022fBba
  28:     0x2b93531c9230 - run_compiler::h4517938d3296cfc5l9b
  29:     0x2b93531c78c0 - thunk::F.Invoke<A, R>::invoke::h5452441173088021345
  30:     0x2b93531c67f0 - rt::unwind::try::try_fn::h8490101008730471441
  31:     0x2b93535bef60 - rust_try_inner
  32:     0x2b93535bef50 - rust_try
  33:     0x2b93531c6aa0 - thunk::F.Invoke<A, R>::invoke::h13338196279056651375
  34:     0x2b93535403b0 - sys::thread::thread_start::h395b8c6815673c5cN3w
  35:     0x2b935950bfe0 - start_thread
  36:     0x2b9353b73c99 - __clone
  37:                0x0 - <unknown>

make: *** [la.elf] Error 101

http://doc.rust-lang.org/complement-bugreport.html

**Comment by kmcallister** [comment]
These ICEs in metadata are almost always caused by stale builds, and I'm afraid there's not a lot we can do to track them down at the moment.  Did you try a clean re-build of your project?

**Comment by zwizwa** [comment]
Yes. It's a single .rs file.

**Comment by kmcallister** [comment]
You tried a clean rebuild and it didn't help? What about any dependencies?

**Comment by zwizwa** [comment]
Clean install from rust nightly, no other dependencies.

**Comment by Marwes** [comment]
I think it is caused by this line
```
fn next(&'a mut self) -> Option<Iterator::Item> {
```
It comes from trying to use the associated type directly on the Iterator trait. At least this example gives the same error for me.
```
fn test() -> Iterator::Item { }

fn main() { }

```

**Comment by Marwes** [comment]
Duplicates of #21716 and #20542?

**Comment by jakerr** [comment]
I ran into this too:

```rust
extern crate serialize;
use serialize::{Decoder, Decodable};

struct A;

impl Decodable for A {
    fn decode<D>(s: &mut D) -> Result<Self, Decoder::Error>
        where D: Decoder {
    }
}

fn main() {}
```

**Comment by Munksgaard** [comment]
I also ran into this:

```rust
use std::net::{IpAddr, ToSocketAddrs};

struct Foo;

impl ToSocketAddrs for (IpAddr, Foo) {
    fn to_socket_addrs(&self) -> Result<ToSocketAddrs::Iter> {
        unimplemented!()
    }
}

fn main() {}
```

```
ERROR:rbml::reader: failed to find block with tag 7
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'explicit panic', /home/munksgaard/src/rust/src/librbml/lib.rs:265

stack backtrace:
   1:     0x7f39e1806870 - sys::backtrace::write::hc08edaab92ea5f11fmB
   2:     0x7f39e182f460 - panicking::on_panic::h0aad656adb1a5494TOK
   3:     0x7f39e1775c50 - rt::unwind::begin_unwind_inner::h2d8760d6e540a908etK
   4:     0x7f39dab90590 - rt::unwind::begin_unwind::h10945465982621760511
   5:     0x7f39dab8f2c0 - reader::get_doc::h3b375501de21dc11nLa
   6:     0x7f39dfa596a0 - metadata::decoder::item_type::h0bcc5bc8041b3f42ggk
   7:     0x7f39dfa69ce0 - metadata::decoder::get_type::hc5d4bd2cb40817bbqtk
   8:     0x7f39df8bb890 - middle::ty::lookup_item_type::h96595a9a15791cf9lx9
   9:     0x7f39e0ffd050 - collect::CollectCtxt<'a, 'tcx>.AstConv<'tcx>::get_item_type_scheme::h8fd7705c7c9341cflEw
  10:     0x7f39e0feb990 - astconv::ast_path_to_ty::hc64524103586bf24pfv
  11:     0x7f39e0fecf40 - astconv::ast_ty_to_ty::closure.34235
  12:     0x7f39e0f89b60 - astconv::ast_ty_to_ty::hd6bbaa747e382891tGv
  13:     0x7f39e0fe4f50 - vec::Vec<T>.FromIterator<T>::from_iter::h12524501346137637334
  14:     0x7f39e0fe2ca0 - astconv::convert_angle_bracketed_parameters::ha7ddd9e4ce685f360Nu
  15:     0x7f39e0f89610 - astconv::ast_path_substs_for_ty::h5130e30fa04adbe9SCu
  16:     0x7f39e0feb990 - astconv::ast_path_to_ty::hc64524103586bf24pfv
  17:     0x7f39e0fecf40 - astconv::ast_ty_to_ty::closure.34235
  18:     0x7f39e0f89b60 - astconv::ast_ty_to_ty::hd6bbaa747e382891tGv
  19:     0x7f39e0fe5d90 - astconv::convert_ty_with_lifetime_elision::he66f2874a05161cbrSu
  20:     0x7f39e0ff0fb0 - astconv::ty_of_method_or_bare_fn::h9de3b09ae5e6e9abj0v
  21:     0x7f39e0ff0e50 - astconv::ty_of_method::h3c68098a52896fbeFYv
  22:     0x7f39e101a420 - collect::convert_methods::ty_of_method::h5fbe8b18816ba236Y4w
  23:     0x7f39e10021c0 - collect::convert_item::hb0c36e790686e76e18w
  24:     0x7f39e10455c0 - check_crate::closure.35307
  25:     0x7f39e1043550 - check_crate::he30443d64908a736MxB
  26:     0x7f39e1e4cd30 - driver::phase_3_run_analysis_passes::h80f0f912fb405b32SGa
  27:     0x7f39e1e32e20 - driver::compile_input::hc45b6ab8a8a517daEba
  28:     0x7f39e1f06ed0 - run_compiler::hfa1a2ebef5d2110b5bc
  29:     0x7f39e1f05530 - thunk::F.Invoke<A, R>::invoke::h630436085354906681
  30:     0x7f39e1f04420 - rt::unwind::try::try_fn::h7425008353638106352
  31:     0x7f39e18a5f30 - rust_try_inner
  32:     0x7f39e18a5f20 - rust_try
  33:     0x7f39e1f046d0 - thunk::F.Invoke<A, R>::invoke::h15407183835454361425
  34:     0x7f39e181afa0 - sys::thread::thread_start::hdf1d4d327e894353YVF
  35:     0x7f39db8f6140 - <unknown>
  36:     0x7f39e1405bb9 - __clone
  37:                0x0 - <unknown>
```

**Comment by tamird** [comment]
Triage: no longer ICEs.
``rust
use std::net::{IpAddr, ToSocketAddrs};

struct Foo;

impl ToSocketAddrs for (IpAddr, Foo) {
    fn to_socket_addrs(&self) -> Result<ToSocketAddrs::Iter> {
        unimplemented!()
    }
}

fn main() {}
```
```shell
$ rustc main.rs
main.rs:6:41: 6:60 error: ambiguous associated type; specify the type using the syntax `<Type as std::net::addr::ToSocketAddrs>::Iter` [E0223]
main.rs:6     fn to_socket_addrs(&self) -> Result<ToSocketAddrs::Iter> {
                                                  ^~~~~~~~~~~~~~~~~~~
main.rs:6:34: 6:61 error: wrong number of type arguments: expected 2, found 1 [E0243]
main.rs:6     fn to_socket_addrs(&self) -> Result<ToSocketAddrs::Iter> {
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to 2 previous errors
```
------
```rust
extern crate serialize;
use serialize::{Decoder, Decodable};

struct A;

impl Decodable for A {
    fn decode<D>(s: &mut D) -> Result<Self, Decoder::Error>
        where D: Decoder {
    }
}

fn main() {}
```
```shell
$ rustc main.rs
main.rs:7:45: 7:59 error: ambiguous associated type; specify the type using the syntax `<Type as serialize::serialize::Decoder>::Error` [E0223]
main.rs:7     fn decode<D>(s: &mut D) -> Result<Self, Decoder::Error>
                                                      ^~~~~~~~~~~~~~
error: aborting due to previous error
```
