### ISSUE TITLE
Crate graphviz should Read as well as Write

### ISSUE THREAD

**Issue by alexchandel** [rust-lang/rust#21868]
Presently the [graphviz](http://doc.rust-lang.org/graphviz/index.html) crate can only write out dot files, and only through the blanket `GraphWalk` trait, which describes a generic directed graph. Graphviz should also have the ability to read a dot file into memory, preserving the attributes of nodes and edges. This is probably one among many features that could be added to GraphWalk, but it would be immediately useful for parsing and manipulating dot files (a task I'm attempting right now).

**Comment by steveklabnik** [comment]
Considering this crate is private to `rustc`, I'm not sure that we need to add this.

**Comment by kmcallister** [comment]
Yes. A full-featured graph library should live on crates.io, not in the compiler.

**Comment by alexchandel** [comment]
Yes, a full-featured *graphviz* library should live in crates.io, not here. But the fact is, `crate graphviz` does live here.
