### ISSUE TITLE
Tracking issue fo RFC #702: `..` syntax for FullRange

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#21879]
Nominated since removing `[]` syntax for FullRange is backwards incompatible.

**Comment by nick29581** [comment]
[RFC](https://github.com/rust-lang/rfcs/blob/master/text/0702-rangefull-expression.md)

**Comment by nick29581** [comment]
Implementation requires adding knowledge of `..` as an expression outside of slicing syntax to the parser (this is probably just moving code, we want to follow the same desugaring to `FullRange`). Then we need to convert all uses of `[]` to `[..]` (alternatively, for collections which implement deref (and assuming the deref coercions have landed) we should change `&foo[]` to `&foo` rather than `&foo[..]`), then remove `[]` as valid syntax. The last part is a breaking change.

**Comment by nick29581** [comment]
@bluss intends to implement this

**Comment by bluss** [comment]
[Latest working draft](https://github.com/bluss/rust/compare/full-range-syntax)

**Comment by bluss** [comment]
I'd like to add `..` before removing &foo[] syntax, but I don't know if we have the time for a small transition period.

**Comment by nick29581** [comment]
I think we have time for a short transition - we need to wait for a snapshot in any case in order to convert `[]` to `[..]` (for types which don't deref).

**Comment by bluss** [comment]
- [ ] Add `..` as valid syntax: PR  #21947 
- [ ] Replace all uses of `&expr[]` with `&expr[..]` or equivalent deref expression.
- [ ] Deprecate `&expr[]`
- [ ] Remove `&expr[]`

**Comment by pnkfelix** [comment]
1.0 beta

**Comment by nick29581** [comment]
@bluss - just clarifying (and I don't mean to hassle you) are you planning to work on the next steps here? (Thanks for 21947, btw!)

**Comment by blaenk** [comment]
yeah @bluss stop slacking

**Comment by bluss** [comment]
I wanted to wait for a snapshot to continue. I'm totally fine with someone else continuing, I'm not very fast and the very slow develop-compile-test cycles frustrate me on my laptop.

**Comment by blaenk** [comment]
Don't be discouraged bluss, there's still time :) You've done a great job so far.

**Comment by nikomatsakis** [comment]
One option for making immediate progress here -- presuming we're blocked on a snapshot -- is feature-gating the old syntax. Given that the new syntax is available, this would let us keep the compiler building but also steer new users in the right direction.

**Comment by nick29581** [comment]
Assigning to myself for coordination only atm.

**Comment by nikomatsakis** [comment]
I've got a PR coming up that deprecates `&foo[]`, causing it to emit a warning. It converts many but not all of the uses (sigh).

**Comment by alexcrichton** [comment]
This has since been completed!

**Comment by bluss** [comment]
:white_check_mark:
