### ISSUE TITLE
Make it possible to opt into features with no stability markers

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#21884]
Recent nightlies apparently make it impossible to use stdlib items with no stability markers. The error message even says "there is no way to use this feature", which kinda sounds like "tough to be you!". #21883 is one instance that is likely fixed in ##21745, but upgrading Servo is now blocked until #21745 lands or we backport it. Additionally, there may be other instances that we haven’t found yet, causing another cycle of fixing Rust.

Instead of making this a hard error, it’d be better to offer to opt into using such items anyway. It could be `#[feature(yes_i_promise_i_ve_filed_a_bug_about_this_but_please_let_me_carry_on_now)]` for example :)

CC @brson

**Comment by huonw** [comment]
I think a better approach would be to emit a hard error for items without a marking in crates marked `#[staged_api]`, that is, ensure that users can never see such items by making the bootstrap itself fail.

(A temporary feature along those lines would be reasonable as a stopgap if the error-early approach is hard to implement.)
