### ISSUE TITLE
`std::os::errno` incorrectly has the return type `usize`

### ISSUE THREAD

**Issue by tbu-** [rust-lang/rust#21898]

**Comment by Jormundir** [comment]
Should these kinds of small type changes include a test?

**Comment by tbu-** [comment]
@Jormundir Don't think so.

@alexcrichton I don't know who to ask for this,  but .. should the return type be newtyped?

**Comment by alexcrichton** [comment]
Currently [the plan](https://github.com/rust-lang/rfcs/blob/master/text/0517-io-os-reform.md#removed-items) for `errno` is to leave it unstable/remove it and possibly add it back in platform-specific modules. If it were a platform-specific API, then it's fine to have its own type on each platform.

I do think that eventually we will grow `struct OsError(os::$platform::errno_type)` which has nice accessor methods like `.code() -> i32` or `.message() -> &'static str` for example.

For now though, there are no concrete plans to stabilize this API or such a structure.
