### ISSUE TITLE
`Reader::push` function does not abstract its unsafe interior away properly

### ISSUE THREAD

**Issue by tbu-** [rust-lang/rust#21896]
It assumes that the implementor of the `Reader` trait does not touch the bytes passed to it in its `read` function.

**Comment by tbu-** [comment]
See also #21076.

**Comment by alexcrichton** [comment]
`old_io` is going to be deprecated and `std::io` has this problem fixed, so I'm going to close this.

**Comment by tbu-** [comment]
That's good to hear!
