### ISSUE TITLE
Vec::insert should allow pushing onto the end

### ISSUE THREAD

**Issue by leifwalsh** [rust-lang/rust#21900]
Consider this pattern:

```rs
fn find_index(a: &[i32], extra_info: T) -> Option<usize> {
    // ...
    Some(4)  // or whatever
}

fn foo() {
    let mut v = Vec::new();
    loop {
        match find_index(&v[], some_stuff) {
            Some(i) => v.insert(i, other_stuff),
            None => break,
        }
    }
}
```

In rust, this panics if `i == v.len()`, meaning that in that example we'd have to explicitly check for that case and use `v.push(other_stuff)` instead, while I think in many languages, the vector/array/list's insert method allows that case and implements it as identical to `Vec::push`.

I'd like to propose that rust's Vec do that too, and I'd be happy to write a PR if someone can point me toward the code and tests that need to be changed.

**Comment by bluss** [comment]
I was going to point to the code, but from what I read, insert already supports inserting at "one past the end", and a quick test does suggest it works.

```rust
// this passes the assertion
fn main() {
    let mut v = Vec::new();
    for i in 0..10 {
        let index = v.len();
        v.insert(index, i);
    }
    
    let mut u = Vec::new();
    for i in 0..10 {
        u.push(i)
    }
    assert_eq!(u, v);
}
```

**Comment by leifwalsh** [comment]
You're right, I must have had some other error in an earlier version of my software that I thought was this problem. Thanks for taking a look!
