### ISSUE TITLE
Feature: Repeat index in macros

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#21908]
It would be really swell if you could somehow access the index or depth of the current repeat in a macro.

Say if we are repeating with `$($x)`, then `$#x` would yield the index of the current `$x` in the sequence.

The `$#` is really not important, could be anything else really.

For example:
```rust
#[macro_export]
macro_rules! letmany {
    ($($x:ident),+) => {
        let $x = $#x;
    };
}

fn main() {
    letmany!(a, b, c);
}
```

Would expand to:
```rust
fn main() {
    let a = 0;
    let b = 1;
    let c = 2;
}
```

Thoughts?

**Comment by kballard** [comment]
As mentioned on IRC, this has already been filed as #12782 and #12916, and in both cases the decision was that this has to go through the RFC process. I filed an RFC that covered this as rust-lang/rfcs#88, which has lots of discussion, and the ultimate decision was that this is a post-1.0 feature.

If you have any feedback on this, commenting on that RFC is probably the best bet, as that's likely to be the starting point for any further discussion of this post-1.0.

**Comment by Centril** [comment]
Thanks, I'll close this issue and comment on the RFC instead.
