### ISSUE TITLE
Book should be printable

### ISSUE THREAD

**Issue by vrinek** [rust-lang/rust#21901]
Currently if you try printing [the book](http://doc.rust-lang.org/book/) it comes out blank.

There is something missing in the CSS. I am already on it and have a hunch what it might be but wanted to post it here in case someone else wants to give it a hand or even carry it further (make it pretty perhaps?).

**Comment by jroesch** [comment]
cc @steveklabnik

**Comment by frewsxcv** [comment]
@vrinek Are you trying to print a single page or the whole book?

**Comment by vrinek** [comment]
I'm only trying to print a single page for now. Sadly I have failed to find where `rust-book.css` is generated from (after deleting https://github.com/rust-lang/rust/blob/master/src/doc/trpl/rust-book.css, it kept regenerating).

The changes I want to do are showcased here: https://github.com/rust-lang/rust/blob/master/src/doc/trpl/rust-book.css.

If someone could point me to the right place where I should apply these changes, I would be grateful.

**Comment by frewsxcv** [comment]
FWIW, If I try to print a single page it doesn't show up blank

![screen shot 2015-02-04 at 3 51 21 pm](https://cloud.githubusercontent.com/assets/416575/6049463/be614456-ac85-11e4-86a4-d887705103ad.png)

That said, there's still room for improvement. What browser/OS are you using? I'm using OSX with the latest stable Firefox.

**Comment by sfackler** [comment]
It comes out pretty busted with Chrome on OSX:

![the rust programming language](https://cloud.githubusercontent.com/assets/1455697/6050036/40052c12-ac71-11e4-9f8f-aa6f994a7b53.png)

**Comment by iKevinY** [comment]
Safari on OS X acts the same way as shown in @sfackler's screenshot, so maybe it's WebKit-related?

**Comment by frewsxcv** [comment]
Even if WebKit/Blink was able to replicate my Firefox screenshot, I'd say there still needs to be better print styling defaults. For example, we probably won't need the sidebar.

**Comment by steveklabnik** [comment]
It's generated from
https://github.com/rust-lang/rust/blob/master/src/rustbook/javascript.rs

**Comment by steveklabnik** [comment]
(and we have a few other issues open about print CSS too)

**Comment by bluss** [comment]
If you try to print a longer chapter, you'll see that you get only the first page. That's more than bad styling :)

**Comment by frewsxcv** [comment]
@steveklabnik If you can easily find the other print CSS related issues, it might benefit this issue for the sake of deduplicating issues. The only I found was [this one](https://github.com/rust-lang/rust/issues/17426)

**Comment by steveklabnik** [comment]
@frewsxcv that was the one on the top of my head, maybe it's just that one

**Comment by vrinek** [comment]
@steveklabnik I bet you meant https://github.com/rust-lang/rust/blob/master/src/rustbook/css.rs (the one you linked was javascript). I'll fix it up and send a PR.

**Comment by steveklabnik** [comment]
err yes, I did. Nice catch :sweat_smile:

**Comment by vrinek** [comment]
PR ready: https://github.com/rust-lang/rust/pull/21962

**Comment by mdinger** [comment]
PR #21962 merged so this should be fixed and closable.
