### ISSUE TITLE
Switch to ec2 spot instances

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#21904]
They are much cheaper. Hopefully buildbot already supports this.

**Comment by frewsxcv** [comment]
[This buildbot manual page](http://docs.buildbot.net/latest/manual/cfg-buildslaves-ec2.html#spot-instances) would suggest that buildbot does indeed support ec2 spot instances

**Comment by steveklabnik** [comment]
Triage: unclear if we ever did this.

**Comment by jonas-schievink** [comment]
There's rust-lang/rust-buildbot#16

**Comment by alexcrichton** [comment]
Closing due to https://github.com/rust-lang/rust-buildbot/pull/16 being closed
