### ISSUE TITLE
rustdoc doesn't render argument names of reexported FFI functions

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#21917]
E.g. http://doc.rust-lang.org/nightly/std/intrinsics/fn.volatile_set_memory.html

     pub unsafe fn volatile_set_memory<T>(*mut T, u8, usize)

vs. http://doc.rust-lang.org/nightly/core/intrinsics/fn.volatile_set_memory.html

    pub unsafe fn volatile_set_memory<T>(dst: *mut T, val: u8, count: usize)

The docs refer to parameters by name, so this functionality is useful.

**Comment by tomjakubowski** [comment]
I think it's a metadata problem; `encode_method_argument_names` isn't ever called from `encode_info_for_foreign_item`.
