### ISSUE TITLE
All rust process in `top` are called `<main>`

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#21911]
I think this is fallout of #21678, and it's somewhat unfortunate :(

![https://i.imgur.com/mJyH52w.png](https://i.imgur.com/mJyH52w.png)

cc @vojtechkral

**Comment by vojtechkral** [comment]
Yup. Didn't think of that. So _don't_ set the name of the main thread I suppose?

**Comment by alexcrichton** [comment]
Yeah that may be the best option after all (sorry for recommending the opposite!)

**Comment by vojtechkral** [comment]
Okay, no problem, I'll send PR...

**Comment by alexcrichton** [comment]
Thanks!

**Comment by bluss** [comment]
Is it possible to remove the allocation from this line, and thus from all Rust programs entirely?

```rust
// src/libstd/rt/mod.rs line 96
let thread: Thread = NewThread::new(Some("<main>".to_string()));
```
