### ISSUE TITLE
Parse error types (like ParseIntError) don't seem to be available in the std namespace, just core

### ISSUE THREAD

**Issue by sellibitze** [rust-lang/rust#21929]
(judging by the API docs)

I'd like to be able to use Result<u8, ParseIntError> as a function's return type without having to use directly `core::num::ParseIntError` since this is what `parse::<u8>` apparently returns now and thus us a public facing type.

cc @alexcrichton

**Comment by alexcrichton** [comment]
Oops, sorry about that!
