### ISSUE TITLE
Lint warns of unused struct field for initialized/mem::-accessed struct

### ISSUE THREAD

**Issue by bm-w** [rust-lang/rust#21935]
I’m initializing a struct and only using it with `mem::transmute` and `mem::size_of` (in my case, its address and size are passed to OpenGL’s `BufferData`, which copies the data). Lint is throwing warnings about unused fields. Is there an explicit philosophy of “initializing is not using”, or is this overzealous linting?

Example code:

~~~{rust}
use std::mem;


struct Aa { a: u8, }

static AA: Aa = Aa { a: 0, };


fn main() {
    let address_of_static_aa: usize = unsafe { mem::transmute(&AA) };
    println!("Address of AA (static): {}", address_of_static_aa);

    let aa = Aa { a: 0, };
    let address_of_let_aa: usize = unsafe { mem::transmute(&aa) };
    println!("Address of aa (let): {}", address_of_let_aa);

    let size_of_aa: usize = mem::size_of::<Aa>();
    println!("Size of Aa: {}", size_of_aa);
}
~~~

Warning:

~~~
src/main.rs:4:13: 4:18 warning: struct field is never used: `a`, #[warn(dead_code)] on by default
src/main.rs:4 struct Aa { a: u8, }
~~~

Rust version:

~~~
rustc 1.0.0-nightly (f1398d273 2015-01-31 20:21:02 +0000)
~~~

**Comment by steveklabnik** [comment]
>  Is there an explicit philosophy of “initializing is not using”,

I believe this is accurate but I'd like someone else to weigh in.

**Comment by steveklabnik** [comment]
Since new lints have a big impact on users of rustc, the policy is that they should go through the RFC process like other user-facing changes. As such, I'm going to give this one a close, but if anyone comes across this ticket and wants this lint, consider adding it to clippy and/or writing up an RFC. Thanks!
