### ISSUE TITLE
Tracking issue for Finalize defaulted type parameters (RFC 213)

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#21939]
Tracking issue for Finalize defaulted type parameters, [RFC 213](https://github.com/rust-lang/rfcs/pull/213).

**Comment by aidanhs** [comment]
Isn't this a duplicate of #27336?

This one was created first so I guess that one would be the dupe, but that has more discussion? Though this has more issues referencing it.

**Comment by nikomatsakis** [comment]
Seems to be, a duplicate, yes.
