### ISSUE TITLE
rustdoc --test for binary projects

### ISSUE THREAD

**Issue by Blackhole16** [rust-lang/rust#21940]
I am working in a group of developers on a binary project, which we also documentate. We also build the doc via cargo doc, but I'd like to include the doc into our testing automatism. Could you please make rustdoc --test also work for binary projects, testing the examples against the binary code?

Kind Regards,
BH16

**Comment by alexcrichton** [comment]
Unfortunately this is currently not possible. `rustdoc --test` relies on the fact that it can link to a previously built copy of the code, which requires it to be a library. I'd recommend moving executable documentation into a separate library if you'd like to test it.
