### ISSUE TITLE
NonZero is not debugable in gdb (anonymous fields can't be accessed)

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#21948]
Servo recently switched to NonZero for its smart pointers. This means that our JS structs of the form

```
struct JSRef<T> {
ptr: *const T,
...
}
```

became

```
struct JSRef<T> {
ptr: NonZero<*const T>,
...
}
```

In the original system, `print ref.ptr` in `gdb` would nicely print a typed pointer (something like `(struct foo::bar::Baz<Quux>)* 0x12345` IIRC). Now, it gives us simply `{0x12345}`, and there doesn't seem to be a way to get the inner data out. This is quite annoying since we use these pointers everywhere in the DOM.

The larger issue here I guess is that anonymous fields can't be accessed as an expression in `gdb`. Perhaps naming them `.0`, `.1` explicitly would work?

cc @michaelwoerister @jdm

**Comment by michaelwoerister** [comment]
Maybe this could be solved by adding special support for NonZero in the pretty printers.

**Comment by michaelwoerister** [comment]
Tuple fields should now be accessible in the debugger via the names `__0`, `__1`, `__2`, etc. It's not as nice as `.0`, `.1`, etc, but it's the best that debuggers will let us do for the moment.

**Comment by Manishearth** [comment]
Thanks! :smile:
