### ISSUE TITLE
`&mut` field of a consumed Struct remains borrowed

### ISSUE THREAD

**Issue by zslayton** [rust-lang/rust#21956]
Hi all,

In implementing a builder for a struct I created, I encountered some very restrictive behavior in the borrow checker. It seems that if a struct holding a borrowed mutable reference is consumed, that borrow remains in effect for the duration of the program. For example:

``` rust
use std::collections::hash_map::HashMap;

pub struct Frame;

pub struct Subscription<'a>{
  subscription_name: &'a str
}

pub struct Session <'a> {
  subscriptions: HashMap<String, Subscription <'a>>
}

pub struct SubscriptionBuilder <'a> {
  pub session: &'a mut Session<'a>,
  pub frame: Frame,
  pub subscription: Subscription<'a>
}

impl <'a> Session <'a> {
  fn subscription(&'a mut self) -> SubscriptionBuilder <'a> {
    SubscriptionBuilder{
      session: self,
      frame: Frame,
      subscription: Subscription{subscription_name : "test"}
    }
  }

  fn do_nothing(&'a self){
    // Do nothing.
  }
}

impl <'a> SubscriptionBuilder <'a> {
  pub fn create(self) -> String {
    "subscription_id".to_string()
  }
}

fn main() {
    let mut session = Session{subscriptions : HashMap::new()};
    let sub_id = session.subscription().create();
    session.do_nothing();
}
```

This produces the error:

```
<anon>:42:5: 42:12 error: cannot borrow `session` as immutable because it is also borrowed as mutable
<anon>:42     session.do_nothing();
              ^~~~~~~
<anon>:41:18: 41:25 note: previous borrow of `session` occurs here; the mutable borrow prevents subsequent moves, borrows, or modification of `session` until the borrow ends
<anon>:41     let sub_id = session.subscription().create();
                           ^~~~~~~
<anon>:43:2: 43:2 note: previous borrow ends here
<anon>:39 fn main() {
<anon>:40     let mut session = Session{subscriptions : HashMap::new()};
<anon>:41     let sub_id = session.subscription().create();
<anon>:42     session.do_nothing();
<anon>:43 }
          ^
error: aborting due to previous error
playpen: application terminated with error code 101
```

You can toy with this example [in the playpen](http://is.gd/odatZ0).

I would have expected the `session` variable to be available to borrow again after the `SubscriptionBuilder` created by `session.subscription()` was consumed in `create()`. Adding an extra scope around the first two lines in main doesn't appear to help. I apologize if this is the intended behavior; I asked around on IRC and others seemed equally surprised.

Thanks!

**Comment by huonw** [comment]
This is caused by this line:

```rust
impl <'a> Session <'a> {
  fn subscription(&'a mut self) -> SubscriptionBuilder <'a> {
```

Using the `'a` like that means that the mutable borrow of self lasts for as long as the reference contained in `Session`, while the code is really wanting to just create a new borrow. This is one time where having multiple lifetimes in a type is useful, to forcibly separate a mutable borrow from data it contains.

This code compiles:

```rust
use std::collections::hash_map::HashMap;

pub struct Frame;

pub struct Subscription<'a>{
  subscription_name: &'a str
}

pub struct Session <'a> {
  subscriptions: HashMap<String, Subscription <'a>>
}

pub struct SubscriptionBuilder <'a, 'sess: 'a> {
  pub session: &'a mut Session<'sess>,
  pub frame: Frame,
  pub subscription: Subscription<'a>
}

impl <'sess> Session <'sess> {
  fn subscription<'b>(&'b mut self) -> SubscriptionBuilder <'b, 'sess> {
    SubscriptionBuilder{
      session: self,
      frame: Frame,
      subscription: Subscription{subscription_name : "test"}
    }
  }
  
  fn do_nothing(&self){
    // Do nothing.
  }
}

impl <'a, 'sess> SubscriptionBuilder <'a, 'sess> {
  pub fn create(self) -> String {
    "subscription_id".to_string()
  }
}

fn main() {
    let mut session = Session{subscriptions : HashMap::new()};
    let sub_id = session.subscription().create();
    session.do_nothing();
}
```

**Comment by huonw** [comment]
It's definitely confusing, I wonder if there's some diagnostics we could implement to improve cases like this.

**Comment by shadowmint** [comment]
Generally speaking moves can lead to strange borrow results like this, but I was surprised to see that this code in the original still didn't work:

```rust
fn main() {
    let mut session = Session{subscriptions : HashMap::new()};
    {
        let sub_id = session.subscription().create();
    }
    session.do_nothing();
}
```

ie. When once the SubscriptionBuilder goes entirely out of the block in which it is created and session is borrowed, the borrow still remains.

**Comment by zslayton** [comment]
That makes complete sense. Thanks, @huonw! I'll leave this issue open for the moment as a discussion space for the diagnostics question.

**Comment by steveklabnik** [comment]
Triage: not aware of any diagnostics changes here. Unsure what we can do, though it's not my area of speciality.

**Comment by vitiral** [comment]
I just hit as well. I had a similar structure to @zslayton except initially I had `session: &'a Session<'a>,` and I changed it to `session: &'a mut Session<'a>,`. Changint it to `mut` caused the compiler (for some reason) not be able to elide the lifetimes and I had to do a similar thing.

I think the MOST confusing thing here is this block:
```
impl <'sess> Session <'sess> {
  fn subscription<'b>(&'b mut self) -> SubscriptionBuilder <'b, 'sess> {
    SubscriptionBuilder{
      session: self,
      frame: Frame,
      subscription: Subscription{subscription_name : "test"}
    }
  }
```

You are specifying that `struct Session` has lifetime `'sess`, which makes complete sense. However, when you specify the lifetime of `self` it does **not** have the lifetime of `'sess` -- instead it has lifetime `'b`!!!

How could `self` have a lifetime other than `'sess`?? It doesn't make any sense to me -- `'self` IS a reference to `Session`, therefore it can't have any lifetime other than `'sess` (in my head). This makes no sense to me (still doesn't actually, haha).

**Comment by Mark-Simulacrum** [comment]
I don't think we can do much to improve diagnostics in this scenario; I've added the simplest case below. If anyone has suggestions as to what hint we could give to improve the situation, they'd be much appreciated.

```rust
struct A<'a> {
    s: &'a str,
}

impl<'a> A<'a> {
    fn perform_mut(&'a mut self) -> &'a str {
        self.s
    }
}

fn main() {
    let mut x = A { s: "A" };
    x.perform_mut();
    x.perform_mut();
}
```

```
error[E0499]: cannot borrow `x` as mutable more than once at a time
  --> test.rs:14:5
   |
13 |     x.perform_mut();
   |     - first mutable borrow occurs here
14 |     x.perform_mut();
   |     ^ second mutable borrow occurs here
15 | }
   | - first borrow ends here

error: aborting due to previous error(s)
```

**Comment by steveklabnik** [comment]
With no suggestions in the last year, I'm guessing that this is not likely to be fixed. If anyone has ideas, please let me know, and we can re-open!
