### ISSUE TITLE
LLVM/Clang 3.7.0 support

### ISSUE THREAD

**Issue by rayslava** [rust-lang/rust#21960]
Currently git LLVM and Clang have version 3.7.0svn which causes
```
    configure: error: bad LLVM version: 3.7.0svn, need >=3.0svn
```
during configure.

**Comment by sanxiyn** [comment]
This is intentional, see #21998. You can use `./configure --disable-llvm-version-check` if you want to try anyway.

**Comment by dotdash** [comment]
We're using a pretty up to date version of 3.7 now, so I'll close this.
