### ISSUE TITLE
uint in EnumSet instead of u64

### ISSUE THREAD

**Issue by hoeppnertill** [rust-lang/rust#21977]
`collections::enum_set::EnumSet` [currently uses `uint`][src] (not even usize) to store the flags:

```rust
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
/// A specialized set implementation to use enum types.
pub struct EnumSet<E> {
    // We must maintain the invariant that no bits are set
    // for which no variant exists
    bits: uint
}
```

I believe it should be `u64` (or `u32`), because `uint`/`usize` will lead to different behaviour and bugs for large numbers of enum variants, depending on what machine is targeted.

I would fix it myself, but I currently can't due to my 5kb/s (do not try cloning rust-lang/rust with that) connection.

[src]: https://github.com/rust-lang/rust/blob/2c05354211b04a52cc66a0b8ad8b2225eaf9e972/src/libcollections/enum_set.rs#L29

**Comment by Gankro** [comment]
EnumSet is officially migrated to https://github.com/Gankro/collect-rs/ where it has been changed to use u32.

It is not re-exported in std::collections, and is only kept in libcollections for rustc's own internal usage.

**Comment by hoeppnertill** [comment]
@Gankro: Oh, that's... interesting. I didn't stumble upon any notice of this, and I really think this defies the benefits of extracting it into collect-rs to some extent.

How is it not *common* or *useful* enough? Sure, it's not a great improvement over bitflags, and it requires an impl of CLike...
