### ISSUE TITLE
Documentation (The Book): FFI section introduces destructors without explanation

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#22002]
The "Destructors" section of the FFI chapter <http://doc.rust-lang.org/book/ffi.html#destructors> is, as far as I can tell, the first time in the book that destructors in Rust are mentioned. The short paragraph is not helpful in explaining what they are, and how they are used. When I read this section, I didn't even know Rust had destructors. Either a reference to some further explanation should be provided, or a short example given inline (mentioning at the very least the Drop trait).

**Comment by supr** [comment]
While we are at it, can we also add some more information about complex types and how to handle unions.

Thanks
