### ISSUE TITLE
Can't write default methods that depend on a bound of an associated type of their traits

### ISSUE THREAD

**Issue by renato-zannon** [rust-lang/rust#22036]
That's a mouthful! To exemplify:

```rust
trait DigitCollection: Sized {
    type Iter: Iterator<Item = u8>;
    fn digit_iter(self) -> Self::Iter;

    #[cfg(on_trait)]
    fn digit_sum(self) -> u32 {
        self.digit_iter()
            .map(|digit: u8| digit as u32)
            .fold(0, |sum, digit| sum + digit)
    }
}

#[cfg(not(on_trait))]
fn digit_sum<T: DigitCollection>(collection: T) -> u32 {
    collection.digit_iter()
        .map(|digit: u8| digit as u32)
        .fold(0, |sum, digit| sum + digit)
}

fn main() {
}
```

This doesn't compile with `--cfg on_trait`, even though it does without it. Note that the only difference between the two configurations is that the function on `not(on_trait)` is a free function instead of a default method.

With `on_trait`, this fails with:
```
trait.rs:7:14: 7:26 error: type annotations required: cannot resolve `<<Self as DigitCollection>::Iter as core::iter::Iterator>::Item == u8` [E0284]
trait.rs:7         self.digit_iter()
                        ^~~~~~~~~~~~
error: aborting due to previous error
```

Tested on `rustc 1.0.0-dev (f3573aa83 2015-02-06 05:52:20 +0000)`

**Comment by edwardw** [comment]
cc me

**Comment by mitchmindtree** [comment]
I've been running into very similar errors all day while updating my libs to the latest nightly. Here's an example of a method that works fine along with one that does not (simplest example I could come up with).

```Rust
use std::num::Float;
 
trait Foo {
    type A: Float;
    
    // This does not work.
    fn sub_a(&self, a: <Self as Foo>::A, b: <Self as Foo>::A) -> <Self as Foo>::A {
        a - b
    }
    
    // However this does.
    fn sub_b(&self, a: <Self as Foo>::A, b: <Self as Foo>::A) -> <Self as Foo>::A {
        fn sub<T: Float>(a: T, b: T) -> T { a - b }
        sub(a, b)
    }
}
 
fn main() {}
```

**Comment by nikomatsakis** [comment]
This example works now. I think this was a dup of https://github.com/rust-lang/rust/issues/21965

**Comment by mitchmindtree** [comment]
@nikomatsakis I just updated to master and I'm still running into the same error [as above](https://github.com/rust-lang/rust/issues/22036#issuecomment-73467290) - perhaps my error is a separate issue?

`rustc 1.0.0-dev (bc87efef2 2015-02-10 19:52:04 +0000)`

**Comment by mitchmindtree** [comment]
Edwardw's PR #22055 does seem to fix my issue however, perhaps it addressed something extra?

**Comment by renato-zannon** [comment]
@nikomatsakis The original issue is still present if the example on the first post is compiled with `--cfg on_trait`. I tested on `rustc 1.0.0-dev (de8bc4475 2015-02-10 09:10:37 +0000)`, which contains #21968
