### ISSUE TITLE
Strange runtime crash on x86_64-apple-darwin with simd

### ISSUE THREAD

**Issue by kballard** [rust-lang/rust#22033]
With the latest `x86_64-apple-darwin` nightly (`rustc 1.0.0-nightly (ba2f13ef0 2015-02-04 20:03:55 +0000)`), the following program crashes at runtime:

``` rust
#![feature(core)]
use std::simd::*;
use std::mem;

fn main() {
    assert_eq!(16, mem::min_align_of::<u64x2>());
    let _ = unsafe { mem::transmute::<_,(u64,u64)>(u64x2(1,2)) };
}
```

Removing the assertion fixes the crash. But the crash itself happens on the following line. LLDB tells me this is `EXC_BAD_ACCESS (code=EXC_I386_GPFLT)` occurring at

```
   0x100000f4c:  callq  0x100001ce0               ; rt::unwind::begin_unwind_fmt::h0c200fcff22cbdd4buF
   0x100000f51:  jmp    0x100000f53               ; foo::main + 515 at foo.rs:7
   0x100000f53:  movaps 0x25966(%rip), %xmm0
-> 0x100000f5a:  movaps %xmm0, -0x118(%rbp)
   0x100000f61:  addq   $0x130, %rsp
   0x100000f68:  popq   %rbp
   0x100000f69:  retq   
```

The crash does not happen under optimization.

**Comment by huonw** [comment]
It work without crashing on my x86-64 Linux system, `rustc 1.0.0-nightly (706be5ba1 2015-02-05 23:14:28 +0000)`.

**Comment by pnkfelix** [comment]
I cannot reproduce this. @kballard is it still happening for your OS X system?

**Comment by kballard** [comment]
This does not reproduce for me anymore. @pnkfelix I'm ok with closing this, unless you think it's worth trying to track down when the crash disappeared in order to figure out whether it's actually fixed or simply became harder to trigger.

**Comment by nox** [comment]
https://github.com/lifthrasiir/rust-encoding/compare/master...nox:simd

The following command segfaults in debug with this patch (but not in release):
```
cargo test --features enable-simd codec::ascii::tests::bench_encode
```

**Comment by steveklabnik** [comment]
Triage: no comments in a very long time. I'm going to give this a close. If someone can reproduce this on a stable rust today, please let me know!
