### ISSUE TITLE
internal compiler error: fictitious type [type error] in sizing_type_of()

### ISSUE THREAD

**Issue by tupshin** [rust-lang/rust#22037]
I got this while trying to implement something similar to a FromStr trait and tried to rely on a lot of inferencing when calling it. I can try to extract a standalone example if needed.

```
error: internal compiler error: fictitious type [type error] in sizing_type_of()
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with RUST_BACKTRACE=1 for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:189

stack backtrace:
   1:     0x7f5463386240 - sys::backtrace::write::h2d5b774b42a611774sy
   2:     0x7f54633a9940 - failure::on_fail::h0eb07a9d41d28278YWF
   3:     0x7f54633097c0 - rt::unwind::begin_unwind_inner::ha069250519e26ab8vBF
   4:     0x7f54606ddf80 - rt::unwind::begin_unwind::h17234541285619125450
   5:     0x7f54606de740 - diagnostic::Handler::bug::h3e3c7e6e1a97cdcf6IE
   6:     0x7f54613b8010 - session::Session::bug::hf96428a3ceac03ea7bq
   7:     0x7f54620195f0 - trans::type_of::sizing_type_of::ha8abac9e5bbd770fWUo
   8:     0x7f546214c8e0 - vec::Vec<T>.FromIterator<T>::from_iter::h13316968136440886855
   9:     0x7f546214a880 - trans::adt::mk_struct::h09dcaf4e3287b521YoI
  10:     0x7f54621479b0 - trans::adt::represent_type_uncached::h4f5217e159ccaf97HXH
  11:     0x7f5462024360 - trans::adt::represent_type::h91100186f4ea7b74hUH
  12:     0x7f54620195f0 - trans::type_of::sizing_type_of::ha8abac9e5bbd770fWUo
  13:     0x7f5462038b60 - trans::common::type_is_immediate::he7749e50fea70b7fqTk
  14:     0x7f5462098110 - trans::type_of::arg_type_of::ha7e8739dec115e12v1o
  15:     0x7f54620c8380 - trans::type_of::type_of_rust_fn::hb792311b0a44f90fHPo
  16:     0x7f54620cfdf0 - trans::base::decl_rust_fn::h0ac657e613606ac9S9r
  17:     0x7f546200b8d0 - trans::monomorphize::monomorphic_fn::closure.40309
  18:     0x7f5461fff750 - trans::monomorphize::monomorphic_fn::h823f1e98b4e6e83aQwd
  19:     0x7f546203fdf0 - trans::callee::trans_fn_ref_with_substs::hbe01e94c86fab1c8Hyg
  20:     0x7f546203e0e0 - trans::callee::trans_fn_ref::hce6aaad16d81babcQmg
  21:     0x7f5462055810 - trans::meth::trans_method_callee::hc4884f5739d91445fVy
  22:     0x7f5462054210 - trans::callee::trans_call_inner::h9432738907577341211
  23:     0x7f546205b290 - trans::expr::trans_rvalue_dps_unadjusted::h13e0f4c2f7eed4fbrUi
  24:     0x7f5462012700 - trans::expr::trans_into::hded554efed2359ffyAh
  25:     0x7f5462112350 - trans::_match::mk_binding_alloca::h18122734726657202769
  26:     0x7f5462011da0 - trans::base::init_local::h754720c4ef862f04Ygt
  27:     0x7f5462012d10 - trans::controlflow::trans_block::h7c59eb740e387008Kae
  28:     0x7f546205b290 - trans::expr::trans_rvalue_dps_unadjusted::h13e0f4c2f7eed4fbrUi
  29:     0x7f5462012700 - trans::expr::trans_into::hded554efed2359ffyAh
  30:     0x7f54620fa3c0 - trans::_match::trans_match_inner::h25d04caf88e64d1bStx
  31:     0x7f546205b290 - trans::expr::trans_rvalue_dps_unadjusted::h13e0f4c2f7eed4fbrUi
  32:     0x7f5462012700 - trans::expr::trans_into::hded554efed2359ffyAh
  33:     0x7f5462012d10 - trans::controlflow::trans_block::h7c59eb740e387008Kae
  34:     0x7f5462060820 - trans::expr::trans_rvalue_stmt_unadjusted::h191909cb42e9a7e8zOi
  35:     0x7f5462012700 - trans::expr::trans_into::hded554efed2359ffyAh
  36:     0x7f54620fa3c0 - trans::_match::trans_match_inner::h25d04caf88e64d1bStx
  37:     0x7f546205b290 - trans::expr::trans_rvalue_dps_unadjusted::h13e0f4c2f7eed4fbrUi
  38:     0x7f5462012700 - trans::expr::trans_into::hded554efed2359ffyAh
  39:     0x7f5462012d10 - trans::controlflow::trans_block::h7c59eb740e387008Kae
  40:     0x7f546205b290 - trans::expr::trans_rvalue_dps_unadjusted::h13e0f4c2f7eed4fbrUi
  41:     0x7f5462012700 - trans::expr::trans_into::hded554efed2359ffyAh
  42:     0x7f54620fa3c0 - trans::_match::trans_match_inner::h25d04caf88e64d1bStx
  43:     0x7f546205b290 - trans::expr::trans_rvalue_dps_unadjusted::h13e0f4c2f7eed4fbrUi
  44:     0x7f5462012700 - trans::expr::trans_into::hded554efed2359ffyAh
  45:     0x7f5462012d10 - trans::controlflow::trans_block::h7c59eb740e387008Kae
  46:     0x7f54620dd260 - trans::base::trans_closure::hd51332b4b14ebe7dW5t
  47:     0x7f5461fff1f0 - trans::base::trans_fn::h746e9efbc2b14f5b6gu
  48:     0x7f5461ffa2d0 - trans::base::trans_item::h8616676269d63cd8xFu
  49:     0x7f54620e4430 - trans::base::trans_crate::he650edc239d6aefahCv
  50:     0x7f5463985bd0 - driver::phase_4_translate_to_llvm::h7647c8286ab427432Oa
  51:     0x7f546395ea80 - driver::compile_input::hc24e252c6a9debbbCba
  52:     0x7f5463a30c00 - run_compiler::h07afdfea03e574126ac
  53:     0x7f5463a2f290 - thunk::F.Invoke<A, R>::invoke::h7167023940119686520
  54:     0x7f5463a2e1c0 - rt::unwind::try::try_fn::h7099284992991867290
  55:     0x7f5463415a80 - rust_try_inner
  56:     0x7f5463415a70 - rust_try
  57:     0x7f5463a2e470 - thunk::F.Invoke<A, R>::invoke::h7565834387748213469
  58:     0x7f5463395e30 - sys::thread::thread_start::h7df8ddcb97714d51VCB
  59:     0x7f545d3e20c0 - start_thread
  60:     0x7f5462f85fd9 - __clone
  61:                0x0 - <unknown>
```

**Comment by jrgold** [comment]
This ICE is also producible by trying to refer to an associated type that's never defined.

    trait A {
        type Output;
        fn a(&self) -> <Self as A>::X;
    }

is accepted by the compiler when it clearly should not be - what on earth is `A::X`? The following `impl` and code cases the same ICE.

    impl A for u32 {
        type Output = u32;
        fn a(&self) -> u32 {
            0
        }
    }

    fn main() {
        let a: u32 = 0;
        let b: u32 = a.a();
    }

Here's the stack trace:

    assoc.rs:22:18: 22:23 note: cat_expr Errd during dtor check
    assoc.rs:22     let b: u32 = a.a();
                                 ^~~~~
    assoc.rs:22:9: 22:10 warning: unused variable: `b`, #[warn(unused_variables)] on by default
    assoc.rs:22     let b: u32 = a.a();
                        ^
    error: internal compiler error: fictitious type [type error] in sizing_type_of()
    note: the compiler unexpectedly panicked. this is a bug.
    note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
    note: run with `RUST_BACKTRACE=1` for a backtrace
    thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:189

    stack backtrace:
       1:     0x7f3b0334a210 - sys::backtrace::write::h58f3688f47ea9825KlC
       2:     0x7f3b03372ac0 - panicking::on_panic::h6a53d3220988f2eebYL
       3:     0x7f3b032b3720 - rt::unwind::begin_unwind_inner::h72a0c6e103bfcdc3zCL
       4:     0x7f3b0057dde0 - rt::unwind::begin_unwind::h2955836616559227712
       5:     0x7f3b0057e5a0 - diagnostic::Handler::bug::h3ef6141b1fad14d7r5E
       6:     0x7f3b012cc2c0 - session::Session::bug::h912125adfec44a01Snt
       7:     0x7f3b01f928e0 - trans::type_of::sizing_type_of::h71ec04b972aedb71W3o
       8:     0x7f3b02058d70 - trans::base::trans_closure::h8de4dc5484c0f3bephu
       9:     0x7f3b01f77b30 - trans::base::trans_fn::h734239fd8d4c689fGsu
      10:     0x7f3b01f72d50 - trans::base::trans_item::h653e553ae00342d4zRu
      11:     0x7f3b020602e0 - trans::base::trans_crate::hffa644676f991a591Ov
      12:     0x7f3b039d14f0 - driver::phase_4_translate_to_llvm::h7bbc12961d2d7c58qPa
      13:     0x7f3b039ab2d0 - driver::compile_input::hfb1bb38c59866d0fGba
      14:     0x7f3b03a7a510 - run_compiler::hf2a7d9848e51e3b5Zbc
      15:     0x7f3b03a78e10 - thunk::F.Invoke<A, R>::invoke::h12698859262113329290
      16:     0x7f3b03a77d00 - rt::unwind::try::try_fn::h10854600533917764358
      17:     0x7f3b033df880 - rust_try_inner
      18:     0x7f3b033df870 - rust_try
      19:     0x7f3b03a78000 - thunk::F.Invoke<A, R>::invoke::h4174228679526982116
      20:     0x7f3b0335eb60 - sys::thread::thread_start::h60ae7cb39d135ef7R4G
      21:     0x7f3afd23c0c0 - start_thread
      22:     0x7f3b02f2bfd9 - __clone
      23:                0x0 - <unknown>
