### ISSUE TITLE
Range<u64> implements ExactSizeIterator

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#22047]
What does `(0..std::u64::MAX).size_hint()` return on a 32-bit build? `Range<u64>` and `Range<i64>` cannot fulfill the requirements of the ExactSizeIterator trait, and the implementations must be removed.

**Comment by bluss** [comment]
I checked the code and it turns out the impl is conditional -- only on 64-bit platforms. So that's correct and for me it turned into a different question of whether that kind of platform dependence is good. I've started a discussion [about that here.](http://internals.rust-lang.org/t/what-rate-of-importability-do-we-allow-in-libstd/1556)

**Comment by bluss** [comment]
Reopened, got some voices backing that this is a bug.

Soft solution would be to warn on using that particular impl of ExactSizeIterator for Range<u64> and i64, but I don't know if we can even do that.

Otherwise we can just remove the impls.

**Comment by lgarczyn** [comment]
I feel like is_empty and len are really missing from Range<u64>.

Maybe they should be implemented on the RangeArgument side ?
