### ISSUE TITLE
Catch PartialEq not being Object Safe

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#22040]
Silent corruption, from this [user post](http://users.rust-lang.org/t/comparing-boxed-traits-possible-bug/251)

The following code compiles and runs, but produces bogus result. PartialEq and thus Expr are not object safe, and because of that `Box<Expr>` should have been rejected.

```rust
use std::fmt::Debug;

trait Expr: Debug + PartialEq { 
    fn print_element_count(&self);
}

//#[derive(PartialEq)]
#[derive(Debug)]
struct SExpr<'x> {
    elements: Vec<Box<Expr+ 'x>>,
}

impl<'x> PartialEq for SExpr<'x> {
    fn eq(&self, other:&SExpr<'x>) -> bool {
        println!("L1: {} L2: {}", self.elements.len(), other.elements.len());
        let result = self.elements.len() == other.elements.len();

        println!("Got compare {}", result);
        return result;
    }
}

impl <'x> SExpr<'x> {
    fn new() -> SExpr<'x> { return SExpr{elements: Vec::new(),}; }
}

impl <'x> Expr for SExpr<'x> {
    fn print_element_count(&self) {
        println!("element count: {}", self.elements.len());
    }
}

fn main() {
    let a: Box<Expr> = Box::new(SExpr::new());
    let b: Box<Expr> = Box::new(SExpr::new());

    a.print_element_count();
    b.print_element_count();

    assert_eq!(a , b);
}
```

Just this is the ICE case in #18956
```rust
fn main() {
    let x: Box<PartialEq> = Box::new(1);
}
```

**Comment by bluss** [comment]
Comment: But PartialEq can be object safe, if you substitute the `Rhs` assoc type with a concrete type? But `Box<PartialEq>` and thus `Box<Expr>` must be rejected.

**Comment by pnkfelix** [comment]
1.0 beta, P-backcompat-lang.

**Comment by nikomatsakis** [comment]
Ah, I see, the problem is actually related to defaults. That is, `PartialEq` *is* object-safe, but referencing `PartialEq` in an object type by itself ought to be illegal. Hmm.

**Comment by nikomatsakis** [comment]
Never mind that last comment. I'm not 100% sure what I think is the right change here, but it is probably as simple as saying that an object-safe trait may not reference `Self` in the supertrait listing apart from in the `Self` position.

**Comment by bluss** [comment]
Thanks for fixing this niko, this is beautiful. 

>  error: the type parameter `Rhs` must be explicitly specified in an object type because its default value `Self` references the type `Self`
