### ISSUE TITLE
Atomics docs should reference the C++11 standard instead of a GCC wiki page.

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#22064]
cc @steveklabnik

**Comment by steveklabnik** [comment]
Why?

**Comment by tomjakubowski** [comment]
Some reasons include:

* The GCC wiki's content is transient and totally out of our control. Somebody could update the wiki with wrong information and mislead Rust documentation readers.
* The text of the C++11 standard is guaranteed to have a correct description of C++11 atomics, by definition.
* The pertinent sections of the standard can probably be quoted directly in our docs under fair use.

**Comment by petrochenkov** [comment]
Why 11 and not 14? With 14 our quotes will contain the latest editorial changes! :D

**Comment by steveklabnik** [comment]
Are either of those standards the definitive documentation for what we are doing? I'm not opposed to this, just trying to gain some more context here.

**Comment by tomjakubowski** [comment]
I believe so. Rust uses LLVM's atomic intrinsic functions which correspond directly to C++11's atomic operations. See [the language reference](http://llvm.org/docs/LangRef.html#memory-model-for-concurrent-operations) and a more [informal description](http://llvm.org/docs/Atomics.html).

**Comment by mahkoh** [comment]
>Why?

The GCC wiki is incomplete. I read it and then ten other websites that tried to provide an informal explanation of C++11 atomic operations before I looked at the standard itself and found a whole paragraph dedicated to my question.
