### ISSUE TITLE
Old docs should get a banner pointing to the up to date docs

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#22063]
On [reddit](http://www.reddit.com/r/rust/comments/2v2mba/how_to_use_sqrt_function_in_rust/) someone asked a question referring to [0.10 docs](http://static.rust-lang.org/doc/0.10/std/index.html). I'm not sure if they should be deleted or not but they definitely should get a huge banner stating ***THESE DOCS ARE REALLY OLD, GO [HERE](http://doc.rust-lang.org/std/index.html) FOR LATEST***.

**Comment by mdinger** [comment]
Instead of really old, could state the age in months. For these, it would be 10 months.

**Comment by steveklabnik** [comment]
I'm not sure that we can/should do this. Docs are included with Rust, once we deploy a version, it's all one cohesive thing with a hash. This changes that.

**Comment by mdinger** [comment]
Well, it won't be so much of a problem after 1.0. So maybe it doesn't matter.

**Comment by mdinger** [comment]
Could be fixed by a more prominent version number: https://github.com/rust-lang/rust/issues/14466 is handling that.
