### ISSUE TITLE
rustdoc search command

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#2207]
I want to be able to write `rustdoc search vec::each` and have rustdoc tell me the docs. It would use the following algorithm:

* Locate all the source crates (.rc files) under the current path
* Locate all the compiled crates used by those source crates
* Scan the all the found source and compiled crates for matching items/methods/variants, etc
* Generate the docs for all the matches
* Maybe provide interactive selection when there are multiple matches

Requires #2206

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#647
