### ISSUE TITLE
core documentation is missing some primitive types found in std

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang/rust#22085]
Primitive types documented in `std` but not in `core`:

* `bool` http://doc.rust-lang.org/nightly/std/primitive.bool.html
* `tuple` http://doc.rust-lang.org/nightly/std/primitive.tuple.html

cc @steveklabnik 

Related to #22084

**Comment by steveklabnik** [comment]
There's a few more of these as well.

**Comment by steveklabnik** [comment]
Oh, these aren't documented in `core`. `core` isn't going to be stable any time soon, so this isn't as high a priority as I thought.

**Comment by tomjakubowski** [comment]
It should be as straightforward as adding `#![doc(primitive = "tuple")]` to `libcore/tuple.rs`, and creating a new module `core::bool` that contains just the attribute `#![doc(primitive = "bool")]`.

Core won't be stabilized anytime soon but I think it'll still get a lot of use from the heroic embedded and toy kernel developers still running on nightlies.
