### ISSUE TITLE
Poor error message when using statics in patterns

### ISSUE THREAD

**Issue by brohee** [rust-lang/rust#22082]
It seems some constants cannot be used in match ranges, which is rather unfortunate if intended IMHO.

The following compiles without issues:

    const TEST_CONST: i32 = 7;

    fn main() {
        let n : i32 = 7;
        match n {
            TEST_CONST ... 17 => {},
            _ => {}
        }
    }

If we make the constant global, it doesn't compile anymore,

    static TEST_CONST: i32 = 7;

    fn main() {
        let n : i32 = 7;
        match n {
            TEST_CONST ... 17 => {},
            _ => {}
        }
    }

failing with the rather cryptic

    not_working_static.rs:6:9: 6:19 error: non-constant path in constant expr
    not_working_static.rs:6         TEST_CONST ... 17 => {},
                                    ^~~~~~~~~~

If we use a constant defined in another crate, as in the following example,

    use std::i32::MIN;

    fn main() {
        let n : i32 = 7;
        match n {
            std::i32::MIN ... 17 => {},
            _ => {}
        }
    }

 we get yet another error message

    not_working_imported_constant.rs:6:23: 6:26 error: expected one of `::`, `=>`, `if`, or `|`, found `...`
    not_working_imported_constant.rs:6         std::i32::MIN ... 17 => {},
                                                             ^~~

I don't know if it is intended, but if it is the error messages can likely be improved quite a bit.

    $ rustc --version --verbose
    rustc 1.0.0-nightly (ba2f13ef0 2015-02-04 20:03:55 +0000)
    binary: rustc
    commit-hash: ba2f13ef0667ce90f55ab0f1506bf5ee7b852d96
    commit-date: 2015-02-04 20:03:55 +0000
    host: x86_64-apple-darwin
    release: 1.0.0-nightly

**Comment by jakub-** [comment]
@brohee, thanks for your report!

I would say that the `static` example works as intended. Whenever you're naming a constant value, you should use `const`. `static` should only be used when the memory location of the datum is significant, which it isn't for `match` expressions.

In any case, relaxing this would require a concrete RFC to be put forward and discussed. Please take a look at the process in https://github.com/rust-lang/rfcs#what-the-process-is if you're interested in pursuing that direction.

I will leave this bug open to track the fact that absolute paths don't work with range patterns, which is what's responsible for the second example not parsing. That is certainly not intended.

**Comment by brohee** [comment]
I don't think there is much value in making static usable in range patterns, however the error message ought to be better, as static are definitely constant...

**Comment by steveklabnik** [comment]
Today, the initial example has a much better error:

```
oo.rs:6:25: 6:35 error: cannot refer to other statics by value, use the address-of operator or a constant instead [E0394]
foo.rs:6                         TEST_CONST ... 17 => {},
                                 ^~~~~~~~~~
foo.rs:6:25: 6:35 error: constants cannot refer to other statics, insert an intermediate constant instead [E0013]
foo.rs:6                         TEST_CONST ... 17 => {},
                                 ^~~~~~~~~~
foo.rs:6:25: 6:35 error: non-constant path in constant expression
foo.rs:6                         TEST_CONST ... 17 => {},
                                 ^~~~~~~~~~
```

And the example with `std` compiles. As such, I think we can give this one a close. Thanks!
