### ISSUE TITLE
Float::ldexp should use the same format as everything else

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#22098]
[`std::num::Float::ldexp`](http://doc.rust-lang.org/std/num/trait.Float.html#tymethod.ldexp) has an unusual format: it takes `x: Self` as it's first parameter where everything else in the trait takes `self`. It should take `self` as it's first parameter for consistency with everything else.

It is located in [`std::num::mod`](https://github.com/rust-lang/rust/blob/master/src/libstd/num/mod.rs#L249)

**Comment by nagisa** [comment]
+1. There are a few different things to consider here, though:

1. ldexp does not operate on any FP number per se like most other operations do, but rather constructs a new FP number from two arguments one of which happens to be FP number. This function’s signature is consistent with most other methods that construct some kind of FP number (e.g. `Float::zero()`). We might want to consider whether methods such as `next_after` shouldn’t just go ahead and take `x: Self` instead.
2. ldexp can’t currently be chained, but I see literally 0 cases where anybody would chain this function.

cc @huonw

**Comment by mdinger** [comment]
Okay, but from a consistency standpoint, it's like 1/80 for `x: self` vs `self`. It it keeps the same format, it and it's similar functions would probably be better to go at the end or beginning of the function list where they won't be so unusual.

**Comment by aturon** [comment]
Nominating for 1.0-beta P-backcompat-libs

**Comment by pnkfelix** [comment]
One should be able to call this thing as a method, one way or another.  We need to make sure *that* is resolved.

**Comment by pnkfelix** [comment]
1.0 beta, P-backcompat-libs

**Comment by aepsil0n** [comment]
I started to fix this.
