### ISSUE TITLE
Implemented Mul operator trait can't be used

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#22099]
A user provided the following test case that fails compiling at the point where the `*` operator is used.

```rust
use std::ops::Mul;

#[derive(Copy)]
pub struct S {
    a: f64
}

impl Mul<f64> for S {
    type Output = S;

    fn mul(self, scalar: f64) -> S {
        S {
            a: self.a * scalar
        }
    }
}

impl Mul<S> for f64 {
    type Output = S;

    fn mul(self, s: S) -> S {
        s.mul(self)
    }
}

fn main() {
    let s = S {a: 0f64};
    s * 5f64;
    5f64 * s; // error: mismatched types: expected `f64`, found `S`
              // (expected f64, found struct `S`) [E0308]
}
```

**Comment by mdinger** [comment]
Maybe a dup of https://github.com/rust-lang/rust/issues/19035 ?

**Comment by bluss** [comment]
I'm not sure and here's the reason: in #19035, today's coherence rules don't allow the correct trait impls to define addition/multiplication both ways.

What made me react in this bug was that the trait impls are accepted by the compilere, but the operator still doesn't work.

**Comment by Diggsey** [comment]
I don't think coherence rules prevent this: there's no way a sibling crate could contain a different implementation of `Mul<S> for f64` because it would have to import this crate to learn of S, and in doing so it would learn of this crate's implementation.

**Comment by mdinger** [comment]
Isn't this a big 1.0 problem? You can do lots of things but not math...
