### ISSUE TITLE
Stability dashboard seems to pull in things it shouldn't

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#22101]
Nothing in `rust-postgres` has been marked with any stability annotations, but the rustdoc stability summary shows it being 12% stable: http://sfackler.github.io/rust-postgres/doc/postgres/stability.html

cc @aturon

**Comment by steveklabnik** [comment]
The stability attributes aren't meant for anything but `rustc`. Doesn't mean this isn't a bug, but just sayin'.

**Comment by aturon** [comment]
@sfackler 

Currently, when you impl a trait, if you don't provide a stability marker on the impl it will default to the stability of the trait. This was a workaround for `#[derive]`, where you *cannot* provide your own stability marker.

I'm pretty sure what you're seeing here is just stable implementations for standard traits.

**Comment by aturon** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/18969
