### ISSUE TITLE
Float::abs_sub isn't working properly

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#22105]
I'm not sure what [`Float::abs_sub()`](http://doc.rust-lang.org/std/num/trait.Float.html#tymethod.abs_sub) is supposed to do but it's not working correctly.

```rust
#![feature(std_misc)]

fn main() {
    use std::num::Float;

    // Rules:    
    // - If `self < other`: `0`
    // - Otherwise `self - other`
    
    assert_eq!(3.0f64.abs_sub(5.0), 0.0); // okay
    assert_eq!(3.0f64.abs_sub(-5.0), 8.0);// okay
    
    assert_eq!(3.0f64.abs_sub(2.0), 1.0); // okay
    assert_eq!(3.0f64.abs_sub(-2.0), 5.0);// okay
    
    assert_eq!(-3.0f64.abs_sub(2.0), -1.0); // Wrong. What should this do?
    assert_eq!(-3.0f64.abs_sub(-2.0), -5.0);// Wrong. What should this do?
    
    assert_eq!(-1.0f64.abs_sub(2.0), 0.0);  // okay
    assert_eq!(-1.0f64.abs_sub(-2.0), -3.0);// Wrong. What should this do?
    
    assert_eq!(0.0f64.abs_sub(1.0), 0.0);   // okay
    assert_eq!(0.0f64.abs_sub(-1.0), 1.0);  // okay
}
```

**Comment by huonw** [comment]
These call the C function `fdim` (and variants) directly, which is described by its man page as

>     double fdim(double x, double y);
> 
> These functions return the  positive  difference,  max(x-y,0),  between their arguments.

so this behaviour seems rather confusing.

**Comment by huonw** [comment]
Oh, no, it's just an operator precedence thing: `-3.0f64.abs_sub(-2.0)` is parsed as `-(3.0f64.abs_sub(-2.0))`, not `(-3.0f64).abs_sub(-2.0)` (which is presumably the intention?).

Adding the parens makes it behave as expected:

```rust
#![feature(std_misc)]

fn main() {
    use std::num::Float;

    // Rules:    
    // - If `self < other`: `0`
    // - Otherwise `self - other`

    assert_eq!((-3.0f64).abs_sub(2.0), 0.0);
    assert_eq!((-3.0f64).abs_sub(-2.0), 0.0);
    assert_eq!((-1.0f64).abs_sub(-2.0), 1.0);
}
```

Closing as not-a-bug, but thanks for checking things so carefully!

**Comment by mdinger** [comment]
Hmm...that's a downside to using method syntax here. I can see that tripping people up often but don't see a way around it except recommending save to variables before calling the methods.

@huonw thanks!
