### ISSUE TITLE
AtomicInt Dose not impl Clone?

### ISSUE THREAD

**Issue by egmkang** [rust-lang/rust#22107]
Vec<AtomicInt> cannot compile because AtomicInt dose not impl trait Clone.

is this a bug?

**Comment by steveklabnik** [comment]
I'd think it's an oversight rather than a bug. I'd imagine it' dmake a new `AtomicInt` but with the same integer value, yeah?

**Comment by alexcrichton** [comment]
This is actually currently intentional. All loads/stores from an `AtomicInt` need to be annotated with a specified `Ordering`, and `Clone` does not allow us to do that (there are no parameters).
