### ISSUE TITLE
Null coalescing and custom operators

### ISSUE THREAD

**Issue by iluuu1994** [rust-lang/rust#22121]
A null coalescing operator would be awesome. It's quite burdensome to unwrap your `Option`s using `match` all the time. Something like this would be great:

```rust
let x = ... ?? default_value
```

`Option` is part of the standard library so I guess implementing the `??` doesn't really make sense unless there are custom operators that can be implemented inside the standard library.

I'd like to point you to the Swift implementation of custom operators here. They have solve this problem rather elegantly. There's some controversy over custom operators and them being overused in cases that don't really make sense and can be more confusing than helpful.

I'm interested in opinions on this and custom operator overloading in Rust.

This is how an implementation of a null coalescing operator could look like.

```rust
infx fn ??<T>(l: Option<T>, r: T) -> T {
	match l {
		Some(s) => s,
		None => r,
	}
}
```

Btw Rust is super awesome :D :metal:

**Comment by steveklabnik** [comment]
> Btw Rust is super awesome :D :metal:

Thanks! :)

Can you please make this issue over at rust-lang/rfcs, though, please? We're keeping all feature-request kind of things over there. You may also find some related issues, I believe there's already a proposal for a `?` operator.

**Comment by iluuu1994** [comment]
I will, thanks!

**Comment by jmwoehr** [comment]
I'm not sure if you're aware, but I think it's worth mentioning that you can get this kind of functionality through the unwrap_or function such that:

```
Some(10).unwrap_or(42) == 10
```

and

```
None.unwrap_or(42) == 42
```

Of course an operator may be more convenient.

http://doc.rust-lang.org/std/option/enum.Option.html#method.unwrap_or

**Comment by iluuu1994** [comment]
@jmwoehr That's actually pretty close to what I was looking for. Nonetheless, operator overloading could still be useful in many ways. Thanks
