### ISSUE TITLE
'src' link on std::format! macro docs is broken

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#22133]
1. Navigate to http://doc.rust-lang.org/std/macro.format!.html
2. Click `[src]`
3. Browser navigates to broken link: http://doc.rust-lang.org/src/std/%3Ccore_collections%20macros%3E.html#1-2

**Comment by steveklabnik** [comment]
I believe that this is a duplicate of https://github.com/rust-lang/rust/issues/21311

**Comment by frewsxcv** [comment]
@steveklabnik You are correct :+1:
