### ISSUE TITLE
Move metadata handling into its own crate

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#2213]
Seems like a good next candidate for breaking up rustc. Metadata will likely be needed by the libraries for dynamic loading.

**Comment by brson** [comment]
Still an obvious but hard refactor. Not sure if this issue is still useful.

**Comment by steveklabnik** [comment]
@brson yeah, I'd side on the 'ticket not actually useful' side of things. @kmcallister has a list of some things that this would be useful for, but those have individual tickets that are actually goal-focused.
