### ISSUE TITLE
Glob imports ignore private items of parent modules

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust#22145]
This shouldn't be the case, as child modules have access to the private items of parent modules.

Example:
```
pub mod foo {
    struct FooItem;
    pub mod bar {
        // use foo::FooItem; // Direct import works for both public/private
        use foo::*; // Only works if `foo::FooItem` is public
        pub fn bar_fn() {
            let _ = FooItem;
        }
    }
}

fn main() {
    foo::bar::bar_fn();
}
```

This gives the error:
```
<anon>:7:21: 7:28 error: unresolved name `FooItem`
<anon>:7             let _ = FooItem;
                             ^~~~~~~
```

**Comment by alexcrichton** [comment]
This is actually working as intended. A glob import will only import public items from another module, it will unconditionally ignore all private items. You may be interested in opening an issue in the RFC tracker to track a tweak to this behavior if you'd like to.
