### ISSUE TITLE
Linking error between a Rust binary and a Rust library with a function that contains an assertion

### ISSUE THREAD

**Issue by tomaka** [rust-lang/rust#22156]
How to reproduce:

- Clone the `vb-slice` branch of `https://github.com/tomaka/glium` (or the commit `14bb0fecdb6443afac36945956dfbbe9b70c81c4`)
- Run `cargo test`

[I'm trying](https://github.com/tomaka/glium/pull/482) to add a `VertexBufferSlice` struct which implements a method named `write`. [You can see it here](https://github.com/tomaka/glium/blob/14bb0fecdb6443afac36945956dfbbe9b70c81c4/src/vertex/buffer.rs#L291-293). Nothing fancy except that it contains an assertion.

However, when I try to call this function it in an external test (ie. a binary program that is linked to the library), I'm getting the following linking error:

> error: linking with `cc` failed: exit code: 1
> 
> note: "cc" '"-Wl,--as-needed"' '"-m64"' '"-L"' '"/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib"' '"-o"' '"/home/travis/build/tomaka/glium/target/vertex_buffer-1e2aae9fd3ad25cf"' '"/home/travis/build/tomaka/glium/target/vertex_buffer-1e2aae9fd3ad25cf.o"' '"-Wl,--whole-archive"' '"-lmorestack"' '"-Wl,--no-whole-archive"' '"-Wl,--gc-sections"' '"-pie"' '"-nodefaultlibs"' '"-L"' '"/home/travis/build/tomaka/glium/target/deps"' '"-lglium_macros-5f17c65ec5d278d1"' '"-L"' '"/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib"' '"-lrustc-4e7c5e5c"' '"-L"' '"/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib"' '"-lrbml-4e7c5e5c"' '"-L"' '"/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib"' '"-lgraphviz-4e7c5e5c"' '"/home/travis/build/tomaka/glium/target/libglium-97a51fd64d277807.rlib"' '"/home/travis/build/tomaka/glium/target/deps/libimage-09875835c1e4fda6.rlib"' '"/home/travis/build/tomaka/glium/target/deps/libnum-916609c89539ae45.rlib"' '"/home/travis/build/tomaka/glium/target/deps/libglutin-abe6f4e5d9a1c8bb.rlib"' '"/home/travis/build/tomaka/glium/target/deps/libnalgebra-5f50089564df46a9.rlib"' '"-L"' '"/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib"' '"-lrustc_llvm-4e7c5e5c"' '"-L"' '"/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib"' '"-ltest-4e7c5e5c"' '"-L"' '"/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib"' '"-lgetopts-4e7c5e5c"' '"/home/travis/build/tomaka/glium/target/deps/libcgmath-5bccc911b6378e31.rlib"' '"/home/travis/build/tomaka/glium/target/deps/librand-786334d103466ef3.rlib"' '"/home/travis/build/tomaka/glium/target/deps/librustc-serialize-db8cde5690079042.rlib"' '"/home/travis/build/tomaka/glium/target/deps/libgl_common-ec39142a57c733b7.rlib"' '"/home/travis/build/tomaka/glium/target/deps/liblibc-8d21de95f4de7169.rlib"' '"-L"' '"/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib"' '"-lflate-4e7c5e5c"' '"-L"' '"/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib"' '"-lrustc_back-4e7c5e5c"' '"-L"' '"/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib"' '"-lsyntax-4e7c5e5c"' '"-L"' '"/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib"' '"-lfmt_macros-4e7c5e5c"' '"-L"' '"/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib"' '"-lserialize-4e7c5e5c"' '"-L"' '"/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib"' '"-larena-4e7c5e5c"' '"-L"' '"/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib"' '"-lterm-4e7c5e5c"' '"-L"' '"/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib"' '"-llog-4e7c5e5c"' '"-L"' '"/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib"' '"-lstd-4e7c5e5c"' '"-L"' '"/home/travis/build/tomaka/glium/target"' '"-L"' '"/home/travis/build/tomaka/glium/target/deps"' '"-L"' '"/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib"' '"-L"' '"/home/travis/build/tomaka/glium/.rust/lib/x86_64-unknown-linux-gnu"' '"-L"' '"/home/travis/build/tomaka/glium/lib/x86_64-unknown-linux-gnu"' '"-Wl,--whole-archive"' '"-Wl,-Bstatic"' '"-Wl,--no-whole-archive"' '"-Wl,-Bdynamic"' '"-lOSMesa"' '"-lGL"' '"-lX11"' '"-lXxf86vm"' '"-lXcursor"' '"-lpthread"' '"-lrt"' '"-ldl"' '"-lm"' '"-lc"' '"-lm"' '"-ldl"' '"-lpthread"' '"-lrt"' '"-lgcc_s"' '"-lpthread"' '"-lc"' '"-lm"' '"-lcompiler-rt"'
> 
> note: /home/travis/build/tomaka/glium/target/vertex_buffer-1e2aae9fd3ad25cf.o: In function `vertex::buffer::VertexBufferSlice$LT$$u27$b$C$$u20$T$GT$::write::h17392329038169427709':
> 
> vertex_buffer.0.rs:(.text._ZN6vertex6buffer40VertexBufferSlice$LT$$u27$b$C$$u20$T$GT$5write21h17392329038169427709E+0xb1): undefined reference to `vertex::buffer::VertexBufferSlice$LT$$u27$b$C$$u20$T$GT$::write::_FILE_LINE::h990f1092ce3964981zg'
> 
> collect2: ld returned 1 exit status

Removing the assertion from the function fixes the error.

This error happens on both windows and linux. The error happens every time I compile, so it's not some sort of data race. The version is `rustc 1.0.0-nightly (74b874071 2015-02-08 00:24:03 +0000)`.

**Comment by tomaka** [comment]
I don't know who to ping for this, but to me it seems like a pretty big problem.

**Comment by nagisa** [comment]
Dupe of #20201, which is supposedly a dupe of #16734.

**Comment by tomaka** [comment]
Thanks
