### ISSUE TITLE
Document float encoding in reference

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#22152]
How floats are encoded needs documentation. I suppose it would go in [reference: floating point](http://doc.rust-lang.org/reference.html#floating-point-literals). If not there, at least somewhere.

**Comment by kmcallister** [comment]
That section is about the literal syntax specifically.

In the [section on machine types](http://doc.rust-lang.org/reference.html#machine-types) we mention:

> The machine types are the following:
>
> ...
> * The IEEE 754-2008 `binary32` and `binary64` floating-point types: `f32` and `f64`, respectively.

**Comment by mdinger** [comment]
Add a reference to it then in the literal section. Makes it easier to discover.
