### ISSUE TITLE
Should int/uint in method names also be called isize/usize?

### ISSUE THREAD

**Issue by edwardw** [rust-lang/rust#22179]
Take `FromPrimitive` for example:
```rust
pub trait FromPrimitive {
    fn from_int(n: isize) -> Option<Self>;
    fn from_uint(n: usize) -> Option<Self>;
}
```

Should them be called `from_isize` and `from_usize` respectively instead?

**Comment by Gankro** [comment]
Yes.

**Comment by alexcrichton** [comment]
This trait is still unstable, however (largely for this precise reason), and modifications will be made appropriately when the trait becomes stable. We tend to not have a tracking issue for each unstable item in the standard library, however, so I'm going to close this for now.

@Gankro is right, however, that these would be more appropriate when renamed.
