### ISSUE TITLE
fs::File::create() on Unix should use 0666 mode by default.

### ISSUE THREAD

**Issue by rodrigorc** [rust-lang/rust#22174]
Compare the output of this rust code

    fn main() {
        std::fs::File::create("test1.txt");
    }

with the C equivalent:

    int main() { fopen("test2.txt", "w"); }

or the C++ one:

    #include <fstream>
    int main() { std::ofstream f("test3.txt"); }

The output of these programs is:

    $ (compile & run)
    $ ls -l test?.txt
    -rw------- 1 rodrigo rodrigo 0 Feb 11 12:00 test1.txt
    -rw-r--r-- 1 rodrigo rodrigo 0 Feb 11 12:00 test2.txt
    -rw-r--r-- 1 rodrigo rodrigo 0 Feb 11 12:00 test3.txt

The C and C++ versions will create a file with mode 0666 (minus the umask, mine is 0022). But the Rust one is different: 0600.

Given the Principle of Least Surprise, I think that the default mode should be changed from 0600 to 0666.

**Comment by GuillaumeGomez** [comment]
There is no __direct__ equivalent in C. However, it doesn't seem a good idea to give a create function without forcing the user to give permission. I think a change on that should be done (I think I'll right a RFC to change that).

**Comment by rodrigorc** [comment]
I don't understand why you think my C code is not equivalent. `fopen()` is the most C-ish way of creating files. Maybe you are thinking of `open()` but that is the POSIX way, not the C one.

Let me cite "man 3 fopen":

> Any created files will have mode S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP | S_IROTH | S_IWOTH (0666), as modified by the process's umask value (see umask(2)).

About forcing the user to set permission (`open()` does that), but `fopen()` does just fine without any mechanism to set permissions at all. It could be a good idea anyway, but remember that in Windows the permissions work quite differently, so maybe there is no easy equivalent.

**Comment by alexcrichton** [comment]
Yes I think that this change was just carried over from the previous implementation. The relevant line to change would be [this one](https://github.com/rust-lang/rust/blob/1500df8934431dd7842827209528211ae53ded12/src/libstd/sys/unix/fs2.rs#L162) and I think it's fine to make the change.

**Comment by GuillaumeGomez** [comment]
Then I change it.

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rust-lang/rust/pull/22186
