### ISSUE TITLE
Generated code is not public with macro generated impl fn

### ISSUE THREAD

**Issue by hugoduncan** [rust-lang/rust#22176]
When generating a public fn with `impl` code, the `pub` keyword is ignored, and the resulting function is private (and raises a `dead_code` warning).

It is also not possible to move the pub keyword into the macro, as it then causes an error:

     expected one of `extern`, `fn`, or `unsafe`, found `pub`

Related issues: #4621, #11403

The workaround suggested in #4621 (generating multiple `impl` blocks) is  unsatisfactory for public impl functions, as it does not allow for documenting the function, and produces doc output with repeated `impl Type` headers for each function.

The use case for this is generating code for library bindings.

The following code reproduces the issue:
```
macro_rules! defn {
    ($n:ident) => (
        fn $n (&self) -> i32 { 1 } )
}

#[derive(Copy)]
pub struct S;

impl S {
    pub defn!(f);
}


#[cfg(test)]
mod tests {
    use super::S;

    #[test]
    fn test_f() {
        let s=S;
        assert_eq!(1, s.f());
    }
}
```

**Comment by hugoduncan** [comment]
Duplicate of #18317

**Comment by TitanThinktank** [comment]
i just got this error while trying to make a 

pub struct WebButton
{
    button: stdweb::web::Element;
}
