### ISSUE TITLE
feature-gate `unsafe_no_drop_flag`

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#22173]
As part of non-zeroing dynamic drop ([RFC 320](https://github.com/rust-lang/rfcs/pull/320)), we need to feature-gate `unsafe_no_drop_flag` so that users do not come to rely on its unstable semantics when we release 1.0.

**Comment by pnkfelix** [comment]
nominating, seems 1.0 beta to me.

**Comment by pnkfelix** [comment]
(subtask of #5016, but gets higher priority due to semantic visibility)

**Comment by SSheldon** [comment]
This feature gate doesn't seem to be required as of alpha 2. The following compiles without issue:
``` rust
#[unsafe_no_drop_flag]
struct Foo;

impl Drop for Foo {
    fn drop(&mut self) {
        println!("Dropping");
    }
}

fn main() { }
```

**Comment by pnkfelix** [comment]
it seems like PR #22364 may have accidentally have removed the gating of `unsafe_no_drop_flag`.

(That's what I deserve for not including a regression test on this.)

I think I know how to fix this.  (And I will look into making sure all of the feature-gated things have tests.)
