### ISSUE TITLE
dropck: uses of terms "superregion" and "subregion" suboptimal

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#22171]
Spawned off of: https://github.com/rust-lang/rust/pull/21022#commitcomment-9252603 , #21972

The dropck code ([RFC 769](https://github.com/rust-lang/rfcs/pull/769)) added a new `SubregionOrigin` variant for lifetime-inference errors, but the error message it reports is probably not written in terms we want to expose to our end users.

(However, this may be a moot issue since pnkfelix has most often seen the lifetime constraints added by dropck as leading to _other_ lifetime-inference errors, and so he does not actually have a test case available at the moment that illustrates this issue.)

**Comment by pnkfelix** [comment]
cc #22321

**Comment by steveklabnik** [comment]
Triage: over a year later, do you still feel this might be moot, @pnkfelix ? or a test case?

**Comment by pnkfelix** [comment]
I continue to see no instances of this diagnostic arising.

I'm thinking I might close this issue, though I might first want to confirm that the code in question is going to be completely obsoleted by NLL anyway.
