### ISSUE TITLE
Eliminate the lingering association between macro crates and plugins (docs / conventions)

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#22199]
Companion to #22198. We should be on the lookout for places in the docs that still conflate the two.  Also if we want people to rename their plugin crates (e.g. `regex_macros`) we should do that soon.

It's best to separate exported `macro_rules!` macros from a plugin crate.  When they're combined, users will end up linking all of libsyntax / librustc unless they know to use `#[no_link]`.  After #22026 you have to mention the crate in two places, anyway.

cc @steveklabnik

**Comment by kmcallister** [comment]
> When they're combined, users will end up linking all of libsyntax / librustc unless they know to use `#[no_link]`

And that only works when your exported macros don't call into any kind of "runtime" library. In that case you should have two crates no matter what, and might as well put the macros with the runtime.

**Comment by sfackler** [comment]
Would the idea be that `regex_macros` is renamed to `regex_plugin` or maybe just `regex`?

**Comment by kmcallister** [comment]
The syntax extension itself is used like an ordinary macro, but the procedure for importing the crate is totally different.  In cases where you have both procedural and MBE macros, you want to put the MBE macros with the "runtime" library and not with the plugin.  So I think the `_macros` naming for procedural macro crates should be discouraged.

I'm not totally sure about this and it deserves more thought.

**Comment by steveklabnik** [comment]
Can you give me an example of some docs that do this conflation? I'd like to make this ticket actionable so I can actually fix it :) I'm not sure what kind of language I'm looking for, and where this might be.

**Comment by kmcallister** [comment]
Yeah, sorry, I'll go looking.  I think it's something we do, but this ticket is more about double-checking.

**Comment by steveklabnik** [comment]
@kmcallister ping! did you look?

**Comment by steveklabnik** [comment]
Closing until I hear something further, but this is likely fine.
