### ISSUE TITLE
Once confident in dropck: remove `#[unsafe_destructor]` attribute

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#22196]
Spawned off of #8861, this is the last step in  [RFC #769](https://github.com/rust-lang/rfcs/pull/769), Sound Generic Drop.

Basically, once we are relatively confident that:
 * the Drop-Check rule is sound,
 * the `dropck` code is at least a sound approximation of that rule, and
 * we have audited APIs in libstd for destructor safety,

then we should remove the `#[unsafe_destructor]` attribute and all the uses of it.

**Comment by pnkfelix** [comment]
Nominating; we should decide whether we are going to do this for 1.0 beta, or if it can wait until release as a "polish issue."

**Comment by pnkfelix** [comment]
1.0 beta, P-high.

**Comment by SSheldon** [comment]
@pnkfelix, is this still slated for the 1.0 beta? `unsafe_destructor` is the last feature my library uses, and I'd love to be able to run it stable on the beta.

**Comment by pnkfelix** [comment]
@SSheldon I'm going to try, but I don't know if I'll be able to do everything necessary to unfeature gate it by the beta.  We will see, I'm reviewing the remaining tasks now.

**Comment by SSheldon** [comment]
@pnkfelix, thanks! For what it's worth, I was able to remove the `unsafe_destructor` feature in my library by moving some of the fields of my struct into a new, non-generic struct and implementing `Drop` on that instead of the generic struct: SSheldon/rust-objc@b2bd3e0. (For anyone else that runs into this, that could potentially be a workaround.)

**Comment by diwic** [comment]
If you can't unfeature gate the entire unsafe_destructor, would it be possible to only unfeature gate those Drop impls we're confident with? Like, the simple and obvious ones (for various values of "simple" and "obvious" :-) ). I suspect a majority of Drop impls would be simple and obvious.

**Comment by pnkfelix** [comment]
at this point I have a patch for the main known issue : PR #23638.

An audit of `libstd` still needs to happen, but I would be okay with doing that in between the beta release and 1.0 (and unfeature-gating `#[unsafe_destructor]` in the meantime.  I'll bring it up with the team.
