### ISSUE TITLE
It's not possible to destructure and move from boxes without introducing an additional binding

### ISSUE THREAD

**Issue by renato-zannon** [rust-lang/rust#22205]
This program compiles:

```rust
struct NonCopy;

fn main() {
    let x = Box::new((NonCopy, NonCopy));

    let pair = *x;
    let (_a, _b) = pair;
}
```

But this one does not:

```rust
struct NonCopy;

fn main() {
    let x = Box::new((NonCopy, NonCopy));
    let (_a, _b) = *x;
}
```

It fails with:

```
destr.rs:6:14: 6:16 error: use of moved value: `x`
destr.rs:6     let (_a, _b) = *x;
                        ^~
destr.rs:6:10: 6:12 note: `x` moved here (through moving `x.0`) because it has type `NonCopy`, which is moved by default
destr.rs:6     let (_a, _b) = *x;
                    ^~
destr.rs:6:10: 6:12 help: use `ref` to override
destr.rs:6     let (_a, _b) = *x;
                    ^~
error: aborting due to previous error
```

**Comment by florence** [comment]
Another oddity, that seems related:

    let x = Box::new(("","".to_string()));
    let (a,b) = *x;

works but:

    let x = Box::new(("".to_string(),""));
    let (a,b) = *x;

fails with the same "moved value" error.

**Comment by goffrie** [comment]
I believe this is the same as #16223.

**Comment by huonw** [comment]
Looks like it; thanks @goffrie (and @renato-zannon and @florence).

@florence I believe that one is because it does it in field order. `""` is a &'static str` which is `Copy`, so the `a` binding in the first one doesn't move out of `x`, and hence doesn't invalid `x` for the `b` binding.
