### ISSUE TITLE
Split up lint/builtin.rs

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#22206]
It's getting pretty big, and the code is very modular.

**Comment by huonw** [comment]
It would be neat to move as many of these into an external crate as possible, to enable faster iteration.

**Comment by richo** [comment]
It seems like this can be closed, unless I'm misinterpreting the issue to actually split each lint out into it's own crate.

**Comment by caipre** [comment]
@kmcallister / @huonw close?

**Comment by huonw** [comment]
Most lints are now defined in the `librustc_lint` crate, but they're all in [one huge file](https://github.com/rust-lang/rust/blob/9ecc9896dedb426e3f4eb3d23dfc60192fe5275f/src/librustc_lint/builtin.rs). It would make sense to break that file up (e.g. an "obvious" division would be breaking out separate modules for [the lint groups](https://github.com/rust-lang/rust/blob/9ecc9896dedb426e3f4eb3d23dfc60192fe5275f/src/librustc_lint/lib.rs#L122-L128)).

**Comment by richo** [comment]
I'm nominally interested in working on this (basically cc me)

**Comment by caipre** [comment]
@richo: Were you claiming this? Otherwise I'll start on it.

**Comment by richo** [comment]
Nope, I wanted to make sure that emails wind up in the part of my inbox that I read, but I'm probably not planning to work on it soon. Feel free!

**Comment by wesleywiser** [comment]
I've moved most of the lints out of `builtin.rs` but there's still a number of them in there. If anyone has ideas about how to deal with those, I'd be happy to work on it. Otherwise, I think this issue can be closed.
