### ISSUE TITLE
Tracking issue for RFC #572: feature gate unused attributes

### ISSUE THREAD

**Issue by nick29581** [rust-lang/rust#22203]

**Comment by nick29581** [comment]
[RFC](https://github.com/rust-lang/rfcs/blob/master/text/0572-rustc-attribute.md)

**Comment by pnkfelix** [comment]
1.0 beta, P-high.

**Comment by nick29581** [comment]
@Manishearth (the RFC author) is going to implement (also happy to mentor anyone else who wants to do it).

**Comment by Manishearth** [comment]
I've [started](https://github.com/Manishearth/rust/compare/rfc-572-forbid-attr) implementing it (mostly need to fix tests now]

**Comment by nikomatsakis** [comment]
In the meantime I opened a PR for a simple-minded feature-gate for attributes starting in `rustc_`, just to avoid undue dependency on the misc testing attributes we have. This will be superceded (or at minimum rendered superfluous) by @Manishearth's implementation, of course. (Though it doesn't hurt either.) PR is https://github.com/rust-lang/rust/pull/22336
