### ISSUE TITLE
Indicate compilation progress in a form useful to end users

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#22227]
See https://github.com/mahkoh/rest_easy. This is an essential plugin that limits the pain caused by compile times.

For 1.0.

**Comment by nagisa** [comment]
Ehh, this only relevant to very big monolithic crates, no?

**Comment by mahkoh** [comment]
I have a 3000 lines crate that takes 37 seconds to compile with trans starting after 10 seconds.

**Comment by mahkoh** [comment]
Note: Without optimization.

**Comment by kmcallister** [comment]
Seems fine as an unstable UI flag like `-Z time-passes`.  You could even do a user-level summary of time-passes, with a few phases e.g. parsing, expansion, resolve, checking, trans, opt, codegen, linking.

I would not count on anything like this getting into stable Rust 1.0.0. I don't think we should stabilize stuff like this until we have a more cohesive story for UI configuration (see #21406).

**Comment by sanxiyn** [comment]
I think we should have `--progress` option. This could show phases, and for long phases like type checking, this could even show the name of the function being checked.

**Comment by kmcallister** [comment]
+1. We can use control codes to update parts of the terminal without spewing output.

I will think about how to integrate this with `--color` and the drawing characters.

**Comment by kmcallister** [comment]
I'm imagining that rustc in whiz-bang fancy terminal mode would display progress on a single line, updated at each stage:

```
[/] Parsing
[-] Expanding macros
[\] Resolving names
[|] Checking
[+] All checks passed; generating LLVM
[+] All checks passed; optimizing
[+] All checks passed; generating machine code
[+] All checks passed; linking
[+] Compilation successful (in 0m 18s)
your-prompt$
```

And just that last "success" message will remain in your terminal buffer.

The spinner has a constant speed in wall-clock terms.  Long-running parts of rustc will call `sess.update_spinner()` now and then to keep it going.

After we pass the "rest easy" point, the spinner turns into a calming `+` and the first part of the message turns green.

**Comment by kmcallister** [comment]
For some phases it would be possible to do actual progress bars, but I don't think the results would be very satisfying.

I'd rather have Cargo or another tool generate a whole-project progress bar based on empirical measurements of how long crates took to build last time.

**Comment by kmcallister** [comment]
Fuck you @mahkoh, I did the effort to turn your shitty ticket into a real, good idea, and now you are closing it out of pure spite.

**Comment by mahkoh** [comment]
Yep, it took me one year to realize how shitty this whole project is. Imagine that effort!

**Comment by kmcallister** [comment]
Closing this in favor of #24335. Thanks for the pointless make-work.
