### ISSUE TITLE
Precisely document the behavior of public unsafe functions

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#22220]
Some unsafe functions don't have enough documentation and others say too much. E.g. String::from_raw_parts says that it will call Vec::from_raw_parts. This makes it impossible to use String::from_raw_parts from a deconstructed String unless it is also documented that String is just a Vec wrapper.

List of unsafe public functions:

- [ ] `alloc::heap                       allocate`
- [ ] `alloc::heap                       deallocate`
- [ ] `alloc::heap                       reallocate`
- [ ] `alloc::heap                       reallocate_inplace`
- [ ] `collections::btree::node          from_raw`
- [ ] `collections::btree::node          from_raw_mut`
- [ ] `collections::string               as_mut_vec`
- [ ] `collections::string               from_raw_parts`
- [ ] `collections::string               from_utf8_unchecked`
- [ ] `collections::vec                  from_raw_buf`
- [ ] `collections::vec                  from_raw_parts`
- [ ] `collections::vec                  set_len`
- [ ] `core::cell                        as_unsafe_cell`
- [ ] `core::cell                        into_inner`
- [ ] `core::mem                         copy_lifetime`
- [ ] `core::mem                         copy_mut_lifetime`
- [ ] `core::mem                         transmute_copy`
- [ ] `core::mem                         uninitialized`
- [ ] `core::mem                         zeroed`
- [ ] `core::nonzero                     new`
- [ ] `core::ptr                         offset`
- [ ] `core::ptr                         read`
- [ ] `core::ptr                         read_and_zero`
- [ ] `core::ptr                         replace`
- [ ] `core::ptr                         swap`
- [ ] `core::ptr                         write`
- [ ] `core::ptr                         zero_memory`
- [ ] `core::slice                       from_raw_buf`
- [ ] `core::slice                       from_raw_mut_buf`
- [ ] `core::str::mod                    from_c_str`
- [ ] `core::str::mod                    from_utf8_unchecked`
- [ ] `rbml::lib                         unsafe_clone`
- [ ] `rustc_llvm::diagnostic            unpack`
- [ ] `rustc_llvm::lib                   debug_loc_to_string`
- [ ] `rustc_llvm::lib                   static_link_hack_this_sucks`
- [ ] `rustc_llvm::lib                   twine_to_string`
- [ ] `std::dynamic_lib                  close`
- [ ] `std::dynamic_lib                  symbol`
- [ ] `std::ffi::c_str                   c_str_to_bytes`
- [ ] `std::ffi::c_str                   c_str_to_bytes_with_nul`
- [ ] `std::ffi::c_str                   from_vec_unchecked`
- [ ] `std::os                           pipe`
- [ ] `std::rt::args                     cleanup`
- [ ] `std::rt::args                     init`
- [ ] `std::rt::libunwind                _Unwind_RaiseException`
- [ ] `std::rt::mod                      cleanup`
- [ ] `std::rt::unwind                   register`
- [ ] `std::rt::unwind                   try`
- [ ] `std::rt::util                     report_overflow`
- [ ] `std::sync::condvar                destroy`
- [ ] `std::sync::mpsc::blocking         cast_from_uint`
- [ ] `std::sync::mpsc::blocking         cast_to_uint`
- [ ] `std::sync::mpsc::select           add`
- [ ] `std::sync::mpsc::select           remove`
- [ ] `std::sync::mpsc::spsc_queue       new`
- [ ] `std::sys::common::condvar         destroy`
- [ ] `std::sys::common::condvar         new`
- [ ] `std::sys::common::condvar         notify_all`
- [ ] `std::sys::common::condvar         notify_one`
- [ ] `std::sys::common::condvar         wait`
- [ ] `std::sys::common::condvar         wait_timeout`
- [ ] `std::sys::common::mutex           destroy`
- [ ] `std::sys::common::mutex           lock`
- [ ] `std::sys::common::mutex           new`
- [ ] `std::sys::common::mutex           try_lock`
- [ ] `std::sys::common::mutex           unlock`
- [ ] `std::sys::common::rwlock          destroy`
- [ ] `std::sys::common::rwlock          new`
- [ ] `std::sys::common::rwlock          read`
- [ ] `std::sys::common::rwlock          read_unlock`
- [ ] `std::sys::common::rwlock          try_read`
- [ ] `std::sys::common::rwlock          try_write`
- [ ] `std::sys::common::rwlock          write`
- [ ] `std::sys::common::rwlock          write_unlock`
- [ ] `std::sys::common::stack           get_sp_limit`
- [ ] `std::sys::common::stack           record_os_managed_stack_bounds`
- [ ] `std::sys::common::stack           record_rust_managed_stack_bounds`
- [ ] `std::sys::common::stack           record_sp_limit`
- [ ] `std::sys::common::thread_local    destroy`
- [ ] `std::sys::common::thread_local    get`
- [ ] `std::sys::common::thread_local    set`
- [ ] `std::sys::common::wtf8            from_u32_unchecked`
- [ ] `std::sys::common::wtf8            slice_unchecked`
- [ ] `std::sys::unix::backtrace         _Unwind_FindEnclosingFunction`
- [ ] `std::sys::unix::backtrace         _Unwind_GetIP`
- [ ] `std::sys::unix::condvar           destroy`
- [ ] `std::sys::unix::condvar           new`
- [ ] `std::sys::unix::condvar           notify_all`
- [ ] `std::sys::unix::condvar           notify_one`
- [ ] `std::sys::unix::condvar           wait`
- [ ] `std::sys::unix::condvar           wait_timeout`
- [ ] `std::sys::unix::mod               close_sock`
- [ ] `std::sys::unix::mutex             destroy`
- [ ] `std::sys::unix::mutex             lock`
- [ ] `std::sys::unix::mutex             new`
- [ ] `std::sys::unix::mutex             raw`
- [ ] `std::sys::unix::mutex             try_lock`
- [ ] `std::sys::unix::mutex             unlock`
- [ ] `std::sys::unix::os                get_env_pairs`
- [ ] `std::sys::unix::os                pipe`
- [ ] `std::sys::unix::process           kill`
- [ ] `std::sys::unix::process           killpid`
- [ ] `std::sys::unix::rwlock            destroy`
- [ ] `std::sys::unix::rwlock            new`
- [ ] `std::sys::unix::rwlock            read`
- [ ] `std::sys::unix::rwlock            read_unlock`
- [ ] `std::sys::unix::rwlock            try_read`
- [ ] `std::sys::unix::rwlock            try_write`
- [ ] `std::sys::unix::rwlock            write`
- [ ] `std::sys::unix::rwlock            write_unlock`
- [ ] `std::sys::unix::stack_overflow    cleanup`
- [ ] `std::sys::unix::stack_overflow    drop_handler`
- [ ] `std::sys::unix::stack_overflow    init`
- [ ] `std::sys::unix::stack_overflow    make_handler`
- [ ] `std::sys::unix::stack_overflow    new`
- [ ] `std::sys::unix::thread            create`
- [ ] `std::sys::unix::thread            current`
- [ ] `std::sys::unix::thread            detach`
- [ ] `std::sys::unix::thread            init`
- [ ] `std::sys::unix::thread            join`
- [ ] `std::sys::unix::thread_local      create`
- [ ] `std::sys::unix::thread_local      destroy`
- [ ] `std::sys::unix::thread_local      get`
- [ ] `std::sys::unix::thread_local      set`
- [ ] `std::sys::unix::thread            main`
- [ ] `std::sys::unix::thread            main`
- [ ] `std::sys::unix::thread            set_name`
- [ ] `std::sys::unix::thread            yield_now`
- [ ] `std::sys::windows::condvar        destroy`
- [ ] `std::sys::windows::condvar        new`
- [ ] `std::sys::windows::condvar        notify_all`
- [ ] `std::sys::windows::condvar        notify_one`
- [ ] `std::sys::windows::condvar        wait`
- [ ] `std::sys::windows::condvar        wait_timeout`
- [ ] `std::sys::windows::mod            close_sock`
- [ ] `std::sys::windows::mutex          destroy`
- [ ] `std::sys::windows::mutex          lock`
- [ ] `std::sys::windows::mutex          new`
- [ ] `std::sys::windows::mutex          raw`
- [ ] `std::sys::windows::mutex          try_lock`
- [ ] `std::sys::windows::mutex          unlock`
- [ ] `std::sys::windows::os             get_env_pairs`
- [ ] `std::sys::windows::os             pipe`
- [ ] `std::sys::windows::process        kill`
- [ ] `std::sys::windows::process        killpid`
- [ ] `std::sys::windows::rwlock         destroy`
- [ ] `std::sys::windows::rwlock         new`
- [ ] `std::sys::windows::rwlock         read`
- [ ] `std::sys::windows::rwlock         read_unlock`
- [ ] `std::sys::windows::rwlock         try_read`
- [ ] `std::sys::windows::rwlock         try_write`
- [ ] `std::sys::windows::rwlock         write`
- [ ] `std::sys::windows::rwlock         write_unlock`
- [ ] `std::sys::windows::stack_overflow cleanup`
- [ ] `std::sys::windows::stack_overflow init`
- [ ] `std::sys::windows::stack_overflow make_handler`
- [ ] `std::sys::windows::stack_overflow new`
- [ ] `std::sys::windows::thread         create`
- [ ] `std::sys::windows::thread         current`
- [ ] `std::sys::windows::thread         detach`
- [ ] `std::sys::windows::thread         init`
- [ ] `std::sys::windows::thread         join`
- [ ] `std::sys::windows::thread_local   create`
- [ ] `std::sys::windows::thread_local   destroy`
- [ ] `std::sys::windows::thread_local   get`
- [ ] `std::sys::windows::thread_local   set`
- [ ] `std::sys::windows::thread         main`
- [ ] `std::sys::windows::thread         set_name`
- [ ] `std::sys::windows::thread         yield_now`
- [ ] `std::thread_local::mod            get`
- [ ] `std::thread_local::scoped         get`
- [ ] `std::thread_local::scoped         set`

**Comment by mahkoh** [comment]
cc @steveklabnik

**Comment by huonw** [comment]
I think most imprecision has a common sense interpretation that is correct, e.g. `String::from_raw_parts` would be pretty ridiculous if it wasn't guaranteed to work with the components of a `String`.

(That's not to say we can't improve the docs of course.)

**Comment by bluss** [comment]
Some of the functions in the list aren't pub outside of the crate. First one I noticed was `collections::btree::node from_raw`.

**Comment by steveklabnik** [comment]
As the other two comments say, this list isn't very accurate. We can certainly work on the docs here, and when I come across an `unsafe` function, I try to add this stuff. But keeping an issue with this list open isn't useful, so I'm going to give it a close.
