### ISSUE TITLE
could type inference fill in the `_` in `expr as Box<_>` when expecting `Box<Trait>` ?

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#22221]
Could type inference fill in `expr as Box<_>` when expecting `Box<Trait>` ?

From what I have seen, it seems to make no attempt to use the surrounding context to fill in gaps like the `_` in `Box<_>` above.

spawned from #22086

**Comment by pnkfelix** [comment]
cc #22181

**Comment by steveklabnik** [comment]
Triage: box stuff is still up for debate.

**Comment by Mark-Simulacrum** [comment]
I'm not quite sure how to triage this, since this doesn't compile at all today. Perhaps this should be closed until `as Box<_>` becomes possible?

```
error: non-scalar cast: `i32` as `std::boxed::Box<std::fmt::Display>`
 --> test.rs:4:27
  |
4 |     let t: Box<Display> = 10 as Box<_>;
  |                           ^^^^^^^^^^^^

error: aborting due to previous error
```

**Comment by Mark-Simulacrum** [comment]
Per discussion on IRC with @aturon I'm going to close. It doesn't seem helpful to track this, since in almost all or all cases, inferring the trait would likely lead to surprising behavior, and so we probably don't want to do this anyway.
