### ISSUE TITLE
Process not Send on Windows

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#22237]
`Process` seems to implement `Send` on Unix but not Windows. cc https://www.reddit.com/r/rust/comments/2vmzmh/coremarkersend_difference_mac_vs_windows/coj4nt9

**Comment by Manishearth** [comment]
cc @pnkfelix @huon

**Comment by alexcrichton** [comment]
This is fixed in #22119 (which is to land soon and obsoletes the old `Process`)
