### ISSUE TITLE
Major LLVM passes perf regression

### ISSUE THREAD

**Issue by larsbergstrom** [rust-lang/rust#22233]
@dotdash is investigating a potential solution to this - he suspects that "might be because I dropped the PassInfo cache patches because upstream had changes of which I thought that they do the same thing"

This regression has nearly doubled Servo's build times, and is centralized in the LLVM passes, though it varies from module to module (as shown in the timing output below for our main crate):

```
After rustup:
time: 7.897     translation
  time: 0.145   llvm function passes
  time: 0.123   llvm module passes
  time: 8.162   codegen passes
  time: 0.001   codegen passes
time: 8.575     LLVM passes
  time: 1.472   running linker
time: 5.858     linking


Before rustup
time: 7.512 	translation
  time: 0.142 	llvm function passes
  time: 0.110 	llvm module passes
  time: 4.762 	codegen passes
  time: 0.001 	codegen passes
time: 5.154 	LLVM passes
  time: 1.507 	running linker
time: 6.043 	linking
```

**Comment by larsbergstrom** [comment]
It looks like this is related to LLVM assertions being enabled. A potential fix:
https://gist.github.com/dotdash/f0a26c980b7200f7a790

**Comment by Gankro** [comment]
I think you meant to ping someone else on this.

**Comment by larsbergstrom** [comment]
This is no longer a high-pri issue for Servo - we have changed to build our snapshots without LLVM assertions enabled. Thanks to @dotdash for the tip!
