### ISSUE TITLE
Tuple Struct format error expects the Struct format field

### ISSUE THREAD

**Issue by ltfschoen** [rust-lang/rust#22236]
I am learning Rust by applying code from the Rust Docs (Nightly) Book.
In [Chapter 2.8 Compound Data Types](http://doc.rust-lang.org/book/compound-data-types.html) they give sample code for Tuple Structs. The code snippet below is how I have applied Tuple Structs for learning purposes in a file called main.rs:

```
fn main() {
    try_tuple_structs();
}

/*
  Rust Tuple Structs are a hybrid data type similar to Tuple and Struct.
  Elements in Tuple Structs DO NOT have a Name, they only have a Type.
  Structs are preferred over Tuple Structs since they have actual Names for Elements.
*/

// Declare a Tuple Struct.
struct Color { i32, i32, i32 };
struct PointInWater { i32, i32, i32 };

fn try_tuple_structs() {
  let black = Color(0, 0, 0);
  let origin = Point(0, 0, 0);
}
```

When I compile with Cargo, I get the following error, which indicates that it is expecting a Struct format whereby elements of the struct have a name. I suspect I have come across this error either because of a syntax error in the official Rust Docs (Nightly) Book, or perhaps Tuple Structs are not fully supported yet?:

```
$ cargo build --verbose
   Compiling hello_world v0.0.1 (file:///Users/lukeschoen/code/rust_test)
     Running `rustc src/main.rs --crate-name hello_world --crate-type bin -g --out-dir /Users/lukeschoen/code/rust_test/target --emit=dep-info,link -L dependency=/Users/lukeschoen/code/rust_test/target -L dependency=/Users/lukeschoen/code/rust_test/target/deps`
src/main.rs:14:19: 14:20 error: expected `:`, found `,`
src/main.rs:14 struct Color { i32, i32, i32 };
                                 ^
Could not compile `hello_world`.

Caused by:
  Process didn't exit successfully: `rustc src/main.rs --crate-name hello_world --crate-type bin -g --out-dir /Users/lukeschoen/code/rust_test/target --emit=dep-info,link -L dependency=/Users/lukeschoen/code/rust_test/target -L dependency=/Users/lukeschoen/code/rust_test/target/deps` (status=101)
```

If I convert the above code snippet to use Structs instead of Tuple Structs (where elements of the struct actually have a name), the code compiles successfully:

```
fn main() {
    try_tuple_structs();
}

struct Color { 
  red: i32, 
  blue: i32, 
  green: i32
}

struct PointInWater { 
  x: i32, 
  y: i32, 
  z: i32
}

fn try_tuple_structs() {
  let black = Color { red :0, blue: 0, green: 0 };
  let origin = PointInWater { x: 0, y: 0, z: 0 };
}
```
Note: I did not include a comma after the last element in the above Structs, as I do not believe doing so is syntactically correct (even though the sample code of the Rust Docs (Nightly) Book [Chapter 2.8 Compound Data Types](http://doc.rust-lang.org/book/compound-data-types.html) does include a comma after the last element). 
Should the Rust compiler return an error or even just a warning when a comma is used after the last element in a Struct? At the moment the compiler doesn't seem to care whether it's included or not...

If you want to test the code snippets above, my code is shared in my [git commit here](https://github.com/ltfschoen/RustTest/commit/591449f7ebf6441f0d78c5609d0cb0bc5f0b17af)

My Rust Compiler and Cargo Versions setup are as follows:
* ```$ rustc --version
rustc 1.0.0-nightly (134e00be7 2015-02-09 19:01:37 +0000)```
* ```$ cargo --version
cargo 0.0.1-pre-nightly (9404539 2015-02-09 20:54:26 +0000)```

**Comment by kmcallister** [comment]
You have to use parentheses for a tuple struct, i.e.

```rust
struct Color(i32, i32, i32);
```

That seems to be what the docs show, as well.

**Comment by ltfschoen** [comment]
Thanks that works!
