### ISSUE TITLE
Purge `map(|&x| x)` et al

### ISSUE THREAD

**Issue by Gankro** [rust-lang/rust#22243]
Option and IteratorExt both have `.cloned()` which is sugar for this operation.

AKA

* `.map(|x| *x)`
* `.map(|x| x.clone())`
* `.map(|x| (*x).clone())` (yes, really)

**Comment by untitaker** [comment]
There are two or three occurrences of code like this:

    edible.iter().map(|x| TokenType::Token(x.clone()))

Should they also be replaced?

Also, [`src/doc/style/style/naming/containers.md`](https://github.com/rust-lang/rust/blob/96bea5eb72d397d30f4717ab63cc868f974d453b/src/doc/style/style/naming/containers.md) contains the same code again.

**Comment by Gankro** [comment]
It can be converted to `edible.iter().cloned().map(TokenType::Token)`. Whether that is better is a matter of taste.

**Comment by djmally** [comment]
Newbie to contributing here, mind if I take a look into fixing this?

**Comment by Gankro** [comment]
Calling this sufficiently resolved.
