### ISSUE TITLE
dlist.split_off(dlist.len()) should not panic

### ISSUE THREAD

**Issue by mbrubeck** [rust-lang/rust#22244]
Currently, `Dlist::split_off` requires its argument to be strictly less than the length of the list, which means the following function panics when passed a one-element list.  Instead, it should leave the original list unmodified and return an empty list:

```rust
fn split_head<T>(list: &mut DList<T>) -> DList<T> {
    list.split_off(1)
}
```

In contrast, `Vec::split_off` *does* allow `self.len()` as a valid argument, so the above code works as desired if you replace DList with Vec.

**Comment by Gankro** [comment]
Vec was actually like this until a few days ago when I happened to notice it and change the check. I must've mis-specified it in the RFC, or this went viral from the first mis-write.
