### ISSUE TITLE
Pathological trait lookup cache behavior

### ISSUE THREAD

**Issue by lifthrasiir** [rust-lang/rust#22255]
```rust
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum Item<'a> {
    Literal(&'a str),
    Space(&'a str),
    Error,
}

pub fn parse<'a, I>(_s: &str, _items: I) -> bool where I: Iterator<Item=Item<'a>> {
    unreachable!()
}

#[test]
fn test_parse() {
    static A: &'static [Item<'static>] = &[];
    parse("", A.iter().cloned());
    parse("", A.iter().cloned());
    // snip: repeat this line 100 times, then this will take some *minutes* to compile
    parse("", A.iter().cloned());
    parse("", A.iter().cloned());
}
```

Isolated from the [new-format](https://github.com/lifthrasiir/rust-chrono/tree/new-format) branch of [Chrono](https://github.com/lifthrasiir/rust-chrono/). The compiler repeatedly fetches new randomness from `/dev/urandom`, which is ultimately traced to `rustc::middle::traits::select::SelectionContext::candidate_from_obligation`. It is likely that the trait lookup cache change from acaad3ad675004c63f73e385f7d07153e0aceb4e is problematic (I've checked that 2015-02-06 nightly does not have this problem).

**Comment by sanxiyn** [comment]
This is a [quadratic slowdown](http://www.wolframalpha.com/input/?i=quadratic+fit+0.126+0.280+0.488+0.744+1.051+1.406+1.819+2.238+2.684+3.193+3.705+4.370+4.896+5.556+6.276). Data is for type checking from 1 to 15 calls to parse.

**Comment by jdm** [comment]
cc me

**Comment by bluss** [comment]
repeated 400 times it only takes 2 seconds to compile, so is it mostly fixed?

**Comment by arielb1** [comment]
There does not seem to be any quadratic growth here - 1000 lines takes only a second on my fast laptop.

**Comment by arielb1** [comment]
There does not seem to be any quadratic growth here - 1000 lines takes only a second on my fast laptop.
