### ISSUE TITLE
Internal Compiler Error: unexpected panic

### ISSUE THREAD

**Issue by qtigercom** [rust-lang/rust#22258]
Rust Version: rustc 1.0.0-nightly (3ef8ff1f8 2015-02-12 00:38:24 +0000)

Description: When compiling the following code with rustc

``` rust
use std::ops::{Add};

fn f<T: Add>(a: T, b: T) -> Add::Output {
    a + b
}

fn main() {
    println!("a + b is {}", f::<f32>(100f32, 200f32));
}
```

the output is:

ERROR:rbml::reader: failed to find block with tag 7
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'explicit panic', C:\bot\slave\nightly-dist-rustc-win-64\build\src\librbml\lib.rs:266

stack backtrace:
   1:         0x69bfbbeb - sys::backtrace::write::h57b621d79849130fitB
   2:         0x69c13974 - rt::unwind::register::h686925f8fa692ab9GSJ
   3:         0x69b836ef - rt::unwind::begin_unwind_inner::hc2a974b1bdaa4639YPJ
   4:           0x302da8 - reader::maybe_get_doc::h2547f886a15a227erHa
   5:           0x301d2f - reader::get_doc::hc198b8918d0de179nLa
   6:          0x1138635 - metadata::decoder::item_type::h7f6e008c4a79af18mck
   7:          0x11480d9 - metadata::decoder::get_type::h9620389d7a7d23c0Xok
   8:          0x10fb7a8 - metadata::csearch::get_type::h3af5a6a2534b2d8bCkn
   9:         0x6d605059 - collect::CollectCtxt<'a, 'tcx>.AstConv<'tcx>::get_item_type_scheme::he174d5be00f2627cMFw
  10:         0x6d5f49ab - rscope::ShiftedRscope<'r>.RegionScope::anon_regions::h0a5ed4a2d46d3aeeqlu
  11:         0x6d5f64ef - rscope::ShiftedRscope<'r>.RegionScope::anon_regions::h0a5ed4a2d46d3aeeqlu
  12:         0x6d5978bd - astconv::ast_ty_to_ty::h1dadfccc9ddb5e90VHv
  13:         0x6d5ef523 - rscope::ShiftedRscope<'r>.RegionScope::anon_regions::h0a5ed4a2d46d3aeeqlu
  14:         0x6d5fa734 - rscope::ShiftedRscope<'r>.RegionScope::anon_regions::h0a5ed4a2d46d3aeeqlu
  15:         0x6d61330f - collect::CollectCtxt<'a, 'tcx>.AstConv<'tcx>::tcx::hf449f596d422460aAFw
  16:         0x6d60a79a - collect::CollectCtxt<'a, 'tcx>.AstConv<'tcx>::get_item_type_scheme::he174d5be00f2627cMFw
  17:         0x6d643867 - check_crate::h72731a5b4298723fkrB
  18:         0x6d64131c - check_crate::h72731a5b4298723fkrB
  19:         0x70b1eb58 - driver::phase_3_run_analysis_passes::hc863f28a1bd50b11SGa
  20:         0x70b02618 - driver::compile_input::hd580d8c011d24ba3Eba
  21:         0x70bcfc4c - run_compiler::hb48a33a057cced0e5bc
  22:         0x70bcd85b - run::h3df2025cf41d43b3Ibc
  23:         0x70bcc56a - run::h3df2025cf41d43b3Ibc
  24:         0x69c4180c - rust_try
  25:         0x69c417e9 - rust_try
  26:         0x70bccbdc - run::h3df2025cf41d43b3Ibc
  27:         0x69c03ae2 - sys::tcp::TcpListener::bind::h2319ec78a0f49dc2faF
  28:         0x770f59ed - BaseThreadInitThunk

**Comment by jdm** [comment]
Same error as #21867.
