### ISSUE TITLE
`src/main.rs` is always built if it exists

### ISSUE THREAD

**Issue by bfops** [rust-lang/rust#22283]
Create three files:

Cargo.toml:

    [package]

    name = "test"
    version = "0.0.0"

    [lib]

    name = "lib"
    path = "src/lib.rs"

src/lib.rs can be empty

src/main.rs:

    arglebargle

Compiling the project gives:

    [ben@windoze8isbest8 testbed]$ cargo build
       Compiling test v0.0.0 (file:///home/ben/testbed)
    src/main.rs:1:1: 1:12 error: expected item, found `arglebargle`
    src/main.rs:1 arglebargle
                  ^~~~~~~~~~~
    Could not compile `test`.

Removing `main.rs` or moving the files out of the `src` directory causes it to build fine.

**Comment by steveklabnik** [comment]
I'm not sure that this is a bug, as I believe this is intended behavior. However, either way, it should be filed against Cargo, not Rust. https://github.com/rust-lang/cargo/

**Comment by bfops** [comment]
Oops you're right, my bad. Thanks.
