### ISSUE TITLE
No documentation for `include!` syntax extension

### ISSUE THREAD

**Issue by mbrubeck** [rust-lang/rust#22309]
`include!` does not appear in the docs for the `std` library, although similar built-in extensions like `include_string!` do appear there.

**Comment by steveklabnik** [comment]
Does this macro even exist anymore?

```
$ git grep "macro_rules\! include"
src/libstd/macros.rs:    macro_rules! include_str { ($file:expr) => ({ /* compiler built-in */ }) }
src/libstd/macros.rs:    macro_rules! include_bytes { ($file:expr) => ({ /* compiler built-in */ }) }
```

/cc @kmcallister

**Comment by kmcallister** [comment]
[Yes](https://github.com/rust-lang/rust/blob/master/src/libsyntax/ext/source_util.rs#L87-L132). You are grepping the docs where it's missing and not the actual definition, which is a procedural macro.

**Comment by kmcallister** [comment]
Related: #22621

**Comment by steveklabnik** [comment]
ahhhhh
