### ISSUE TITLE
Incorrect naming in std::failure

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#22306]
Module should be named `panicking` to match core, `on_fail` should be `on_panic`.

**Comment by iKevinY** [comment]
Took a shot at this in iKevinY/rust@1e01f7f470f1d79be710d546ab25426fcede59f9, but I wanted to verify here to make sure I even changed the correct things before opening a PR. Does this look alright? (`make check` still passes.)

**Comment by brson** [comment]
@iKevinY Yes looks right. Thanks!
