### ISSUE TITLE
Short circuit evaluation isn't listed in the reference

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#22315]
[Short circuit evaluation](https://en.wikipedia.org/wiki/Short-circuit_evaluation) isn't mentioned in the reference and should be if it's included.

**Comment by steveklabnik** [comment]
It does:

>  They differ from `|` and `&` in that the right-hand operand is only
evaluated when the left-hand operand does not already determine the result of
the expression. That is, `||` only evaluates its right-hand operand when the
left-hand operand evaluates to `false`, and `&&` only when it evaluates to
`true`.

**Comment by mdinger** [comment]
I would add the term "short circuit" to the section. Lazy may be true but I know of it as short circuit and would never find it under lazy.
