### ISSUE TITLE
dropck: track order of destruction for r-value temporaries

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#22323]
Spawned off of  #21022, #21972; see also #21657.

Tracking order of destruction for r-value temporaries would (probably) allow us to resume writing code like this from [RFC 769](https://github.com/rust-lang/rfcs/blob/master/text/0769-sound-generic-drop.md#some-temporaries-need-to-be-given-names):

``` rust
for line in old_io::stdin().lock().lines() {
    ...
}
```

which is currently disallowed because the region inference system does not know that the temporary yielded by `stdin()` will outlive the temporary from `stdin().lock()`.

(But note that it might also have fallout, potentially worse than that of #21657)

**Comment by pnkfelix** [comment]
cc #22321

**Comment by steveklabnik** [comment]
Triage: not aware of any changes here, but it's also not an area I'm super familiar with.

**Comment by pnkfelix** [comment]
I *assume* MIR and non lexical lifetimes will likely resolve this directly

**Comment by pnkfelix** [comment]
According to https://github.com/rust-lang/rust/blob/54628c8ea844956f3f4f416b82067c634eb09f7b/src/test/ui/span/issue-23338-locals-die-before-temps-of-body.nll.stderr#L1 this does not appear to be fixed by NLL.

**Comment by pnkfelix** [comment]
(which is ... okay, but a little surprising, and perhaps worth investigation *after* we've taken care of the other bigger problems in NLL.)

**Comment by pnkfelix** [comment]
I'm just going to throw in a reference to the NLL tracking issue #43234 in the hopes that we remember to look at this again later.

**Comment by pnkfelix** [comment]
I just want to make two quick notes:
 * As part of MIR-borrowck we did make a language "change" to track destruction order of locals declared in the same `let`-binding, which was something we previously treated as having an unspecified destruction order in the borrow-checker...
 * I would have thought that MIR-borrowck would have "fixed" this issue (#22323) simply by its architecture. Which is why I have comments like https://github.com/rust-lang/rust/issues/22323#issuecomment-408884715

**Comment by pnkfelix** [comment]
Putting onto the Release milestone in the hopes that this forces me to take action here.

**Comment by pnkfelix** [comment]
I investigated. NLL *does* fix the problem described in this issue.

My earlier comments regarding cases that don't work are instances of misclassification on my part; they should have been associated with #46413

**Comment by pnkfelix** [comment]
Visited for T-compiler triage. Removing NLL-fixed-by-NLL issues from the Release milestone, but continue to leave them open as issues themselves.
