### ISSUE TITLE
Responsive rustdoc output is unresponsive (literally)

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#22325]
E.g. http://tomaka.github.io/cpal/alsa-sys/index.html

Resizing two windows that show this site causes 3-5 seconds of 100% cpu usage on two cores.

Solution: Remove responsive javascript to make the site more responsive.

```js
    function resizeShortBlocks() {
        if (resizeTimeout) {
            clearTimeout(resizeTimeout);
        }
        resizeTimeout = setTimeout(function() {
            var contentWidth = $('.content').width();
            $('.docblock.short').width(function() {
                return contentWidth - 40 - $(this).prev().width();
            }).addClass('nowrap');
            $('.summary-column').width(function() {
                return contentWidth - 40 - $(this).prev().width();
            })
        }, 150);
    }
    resizeShortBlocks();
    $(window).on('resize', resizeShortBlocks);
```
But that's not all: When you load this site for the first time, it doesn't even react to any user input for 5 seconds.

**Comment by retep998** [comment]
An even worse example of this problem: https://retep998.github.io/doc/winapi/winerror/index.html
