### ISSUE TITLE
Better Error Messages for Partially Implemented Traits

### ISSUE THREAD

**Issue by eyolfson** [rust-lang/rust#22337]
Specifically, for types that have a trait implemented, but require the types they use to have the trait implemented as well. For instance, `Result`. Consider the following example:

    #[derive(Debug)]
    struct X;

    struct Y;

    fn main() {
        let x: Result<X, Y> = Ok(X);
        println!("{:?}", x);
    }

Produces the following error message:

    issue.rs:8:22: 8:23 error: the trait `core::fmt::Debug` is not implemented for the type `core::result::Result<X, Y>` [E0277]

This error message is confusing to someone beginning Rust, because according to the documentation, `Result` does implement `Debug`. In this case a clearer error message would be something like:

    issue.rs:8:22: 8:23 error: the trait `core::fmt::Debug` is not implemented for the type `core::result::Result<X, Y>` because type `Y` does not implement `core::fmt::Debug`

Perhaps the error message could be tweaked, but in this case it should clearly point to `Y` as being the problem. Of course, if `X` and `Y` don't implement `core::fmt::Debug` the error message should reflect that was well.

**Comment by nagisa** [comment]
> according to the documentation, Result does implement Debug.

Documentation clearly states there’s only `impl<T, E> Debug for Result<T, E> where T: Debug, E: Debug`, which does not apply to `Result<A, B>`∀`A, B`, which your sentence implies is the case.

**Comment by eyolfson** [comment]
I stated, for a beginner. So someone that just scans that it exists, at all. The main point is to just improve the error message to state which specific type `T` or `E` is missing an implementation of the `Debug` trait that's causing `Results` implementation of `Debug` not to exist.

**Comment by gsingh93** [comment]
Related: https://github.com/rust-lang/rust/issues/20941

**Comment by apasel422** [comment]
This is essentially fixed:
```
> rustc --version
rustc 1.3.0-nightly (e4e93196e 2015-07-14)
> rustc foo.rs 
foo.rs:8:22: 8:23 error: the trait `core::fmt::Debug` is not implemented for the type `Y` [E0277]
foo.rs:8     println!("{:?}", x);
```

**Comment by Gankro** [comment]
... which is just https://github.com/rust-lang/rust/issues/21793

**Comment by birkenfeld** [comment]
New error, but seems still fixed:
```
<anon>:8:22: 8:23 error: the trait bound `Y: std::fmt::Debug` is not satisfied [E0277]
<anon>:8     println!("{:?}", x);
                              ^
<anon>:8:22: 8:23 help: see the detailed explanation for E0277
<anon>:8:22: 8:23 note: `Y` cannot be formatted using `:?`; if it is defined in your crate, add `#[derive(Debug)]` or manually implement it
```

**Comment by arielb1** [comment]
Yeah. Fixed.
