### ISSUE TITLE
Intro of rustc in docs should mention debug/optimization

### ISSUE THREAD

**Issue by tanadeau** [rust-lang/rust#22330]
Mentions of the use of the rustc binary in the docs (such as the "Hello, World!" section in the Rust book) should mention that no optimizations are performed unless the `-O` or similar flag is given. They should also give a quick overview of the debug/optimization differences and use-cases. This distinction is often new to users coming from JIT'ed/interpreted languages.

**Comment by steveklabnik** [comment]
You can't mention every possibe aspect all at once. The introduction already takes a very long time to get to actual code, and I don't want to pollute it any further.

**Comment by tanadeau** [comment]
@steveklabnik Would you be open to an entirely new section that is referenced from the intro location? If so, I'll create that issue.

**Comment by steveklabnik** [comment]
I would like an "optimizing and debugging Rust" chapter in the book, but I'm not tracking chapter feature requests currently.
