### ISSUE TITLE
env::Args and env::ArgsOs should implement ExactSizedIterator

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#22343]
And possibly RandomAccessIterator too.

If there is no issues with implementing it, I will gladly fix up a patch for it.

cc @aturon

**Comment by nagisa** [comment]
By the way, motivation for this is the fact that we have a bunch of `os::args().len()` inside our codebase and without `ExactSizeIterator` there’s no good replacement for this.

**Comment by alexcrichton** [comment]
I'd love to have this! (hurray adding impls backwards compatibly!).

Only catch is to ensure that this is implemented for both windows and unix, otherwise it should be pretty straightforward.
