### ISSUE TITLE
Grammar tests

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#2234]
It would be nice to have confidence about what sort of grammar Rust has. One possible way we could do that:

* Extract EBNF from the manual
* Use a script to convert it to whatever format antlr wants
* Run the entire test suite through the both the rustc parser and antlr parser. Where one fails so should the other.

**Comment by steveklabnik** [comment]
Was going to move to the RFC repo, but let's see how #21452 shakes out.

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/21452 added `make check-grammar`.
