### ISSUE TITLE
0.9f32 != "0.9".parse().unwrap()

### ISSUE THREAD

**Issue by seanmonstar** [rust-lang/rust#22349]
```rust
fn main() {
    assert_eq!(0.9f32, "0.9".parse().unwrap());
}
```

**Comment by edwardw** [comment]
Hmm, it has to do with default numeric types, `0.9f64` works:
```rust
fn main() {
    assert_eq!(0.9f64, "0.9".parse().unwrap());
}
```

**Comment by shepmaster** [comment]
Is this not just [normal floating point wonkyness](http://floating-point-gui.de/)? Here's what happens if you print a hex representation of the values:

```rust
use std::mem::transmute;

fn main() {
    let lit: f32 = 0.9;
    let prs: f32 = "0.9".parse().unwrap();
    
    let lit_int: u32 = unsafe{transmute(lit)};
    let prs_int: u32 = unsafe{transmute(prs)};
    
    println!("{:x}", lit_int);
    println!("{:x}", prs_int);
}
```

outputs:

```
3f666666
3f666667
```

If you do the same for `f64`, the output is `3feccccccccccccd`.

**Comment by shepmaster** [comment]
Another example of (expected) floating point excitement:

```rust
fn main() {
    let lit: f32 = 0.9;
    let sum: f32 = 0.3 + 0.3 + 0.3;
    assert_eq!(lit, sum)
}
```

**Comment by seanmonstar** [comment]
Yea, floats are wonky. However, this means there's 2 parsing implementations. 1 the compiler uses, and 1 the stdlib uses, and they differ somehow.

**Comment by Diggsey** [comment]
Both parsers should give the representable float closest to the exact value.

**Comment by nagisa** [comment]
> However, this means there's 2 parsing implementations. 1 the compiler uses, and 1 the stdlib uses, and they differ somehow.

The compiler uses LLVM to parse literals and we can’t quite depend on LLVM for our standard library.

**Comment by steveklabnik** [comment]
Is this a dup of https://github.com/rust-lang/rust/issues/7648 ?

**Comment by seanmonstar** [comment]
@steveklabnik seems like it!
