### ISSUE TITLE
Add timestamp to generated docs with timestamp

### ISSUE THREAD

**Issue by jonalmeida** [rust-lang/rust#22345]
To let a person reading know how old the docs are, you should be able to see a timestamp (taken from system time?) when the build is completed. This should probably be visible somewhere on the bottom of every page.

A nice example from blaenk in IRC would be to add the timestamp similar to rustc:
```
rustc 1.0.0-nightly (b9ba643b7 2015-02-13 21:15:39 +0000)
```

**Comment by steveklabnik** [comment]
We used to do this, but then it went away.

**Comment by steveklabnik** [comment]
Also, you can know how old they are by the URL.

**Comment by steveklabnik** [comment]
dup of https://github.com/rust-lang/rust/issues/19332
