### ISSUE TITLE
rustdoc table formatting is claustrophobic

### ISSUE THREAD

**Issue by Gankro** [rust-lang/rust#22357]
See http://doc.rust-lang.org/std/collections/#sequences for an example. At least on Firefox (x64 linux), there's barely any space between columns.

**Comment by frewsxcv** [comment]
Just so we know what it looks like in its current state at the time of writing, here's a screenshot:

![screen shot 2015-02-15 at 12 21 08 pm](https://cloud.githubusercontent.com/assets/416575/6204125/333de218-b50d-11e4-95db-2645ea9d3e67.png)
