### ISSUE TITLE
Unknown compiler crash

### ISSUE THREAD

**Issue by chronweigle** [rust-lang/rust#22354]
When trying to build the deform crate in: https://github.com/PistonDevelopers/piston-examples
a crash occures. Im running Linux Mint 17.1 on x86_64. 

Rustc version: rustc 1.0.0-nightly (b9ba643b7 2015-02-13 21:15:39 +0000)

Backtrace:

   Compiling image v0.2.0-alpha.10 (https://github.com/pistondevelopers/image#ffbd2d5e)
   Compiling gl v0.0.8 (https://github.com/bjz/gl-rs#64d26f54)
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:129

stack backtrace:
   1:     0x7f38e9c13490 - sys::backtrace::write::h49b06c4e5fa1765dZTA
   2:     0x7f38e9c38120 - failure::on_fail::h128a61ca90111ec2JFJ
   3:     0x7f38e9b8f350 - rt::unwind::begin_unwind_inner::h142cc6242e7988934jJ
   4:     0x7f38e6eda920 - rt::unwind::begin_unwind::h16368274321953312459
   5:     0x7f38e6eda8b0 - diagnostic::SpanHandler::span_bug::hf454de422bf0e9d374E
   6:     0x7f38e7c69070 - middle::traits::error_reporting::report_fulfillment_errors::he6bf92d6cdf88febsuO
   7:     0x7f38e92b4ba0 - check::vtable::select_all_fcx_obligations_or_error::h0cb095e1ab8b5fe1oPb
   8:     0x7f38e9365a60 - check::check_bare_fn::hb66714e77e5aa536Scn
   9:     0x7f38e935d1d0 - check::check_item::h2eee3d06f38f9645lwn
  10:     0x7f38e9363750 - visit::walk_item::h2662464371015032330
  11:     0x7f38e9363750 - visit::walk_item::h2662464371015032330
  12:     0x7f38e94333d0 - check_crate::closure.35460
  13:     0x7f38e942dc30 - check_crate::h72ae1d5cae23f4bfOxB
  14:     0x7f38ea238e70 - driver::phase_3_run_analysis_passes::h0dde18f593e432c7SGa
  15:     0x7f38ea21ef60 - driver::compile_input::ha2540a3e586cc4ecEba
  16:     0x7f38ea2f2d60 - run_compiler::h15054257f14a11945bc
  17:     0x7f38ea2f13c0 - thunk::F.Invoke<A, R>::invoke::h12452595225713592450
  18:     0x7f38ea2f02b0 - rt::unwind::try::try_fn::h15446000090453491186
  19:     0x7f38e9ca4810 - rust_try_inner
  20:     0x7f38e9ca4800 - rust_try
  21:     0x7f38ea2f0560 - thunk::F.Invoke<A, R>::invoke::h7454813734411192152
  22:     0x7f38e9c23d90 - sys::thread::thread_start::h76415ad3898ce7eaaOE
  23:     0x7f38e3bb50c0 - start_thread
  24:     0x7f38e9806fd9 - __clone
  25:                0x0 - <unknown>

Build failed, waiting for other jobs to finish...

**Comment by tamird** [comment]
@chronweigle can you provide a smaller, self-contained example?

**Comment by Stebalien** [comment]
@chronweigle, can you still reproduce this?

**Comment by Mark-Simulacrum** [comment]
Going to go ahead and close since we don't have an example that is minimal enough to be viable, and there's been no response from issue author in ~2 years.
