### ISSUE TITLE
`make check-build-lexer-verifier` fails currently

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#22379]
```
cfg: version 1.0.0-dev (342ab53bf 2015-02-15 12:20:31 +0000)
cfg: build triple x86_64-apple-darwin
cfg: host triples x86_64-apple-darwin
cfg: target triples x86_64-apple-darwin
cfg: enabling more debugging (CFG_ENABLE_DEBUG)
cfg: host for x86_64-apple-darwin is x86_64
cfg: os for x86_64-apple-darwin is apple-darwin
cfg: good valgrind for x86_64-apple-darwin is
cfg: using CC=clang (CFG_CC)
cfg: using CXX=clang++ (CFG_CXX)
cfg: enabling valgrind run-pass tests (CFG_ENABLE_VALGRIND_RPASS)
cfg: valgrind-rpass command set to
cfg: no xelatex found, disabling LaTeX docs
cfg: including test rules
cfg: antlr4 not available, skipping lexer test...
/Users/coreyf/Development/rust/rust/src/grammar/verify.rs:20:5: 20:18 error: unresolved import `std::io::File`. There is no `File` in `std::io`
/Users/coreyf/Development/rust/rust/src/grammar/verify.rs:20 use std::io::File;
                                                                 ^~~~~~~~~~~~~
error: aborting due to previous error
make: *** [/Users/coreyf/Development/rust/rust//grammar/verify] Error 101
```

I'm surprised this is not causing issues because the [Makefile claims that this target should get run by Bors everytime upon check-in](https://github.com/rust-lang/rust/blob/725cc06464abda7a657780f12feaefb7f10333c6/mk/tests.mk#L188-L190)

**Comment by steveklabnik** [comment]
I am pretty sure that it doesn't actually work, and that all of this has just rotted.

**Comment by pnkfelix** [comment]
cc me

(i think there is something going wrong where only *some* host environments will actually try to run the steps associated with this target, and our buildbots are not in that set.  But I do know that I hit this problem myself when I try to emulate the buildbots and run `make check-all`.)

**Comment by steveklabnik** [comment]
Triage: on my machine:

```
$ make check-build-lexer-verifier 
cfg: version 1.11.0-dev (763f9234b 2016-06-06)
<snip>
cfg: including test rules
$ echo $?
0
```

So, it seems like this has been fixed, at least on my machine. Though as I said above, it's not like this is seeing any active development, and I don't even know if it's truly _working_, just that it returns zero. I'm not sure if this should be left open or closed, frankly...

**Comment by alexcrichton** [comment]
Make's now gone, so closing.
