### ISSUE TITLE
-C target-cpu=help won’t print anything unless compilation reaches trans

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#22380]
> target-cpu=help
>  Selects a target processor. If the value is 'help', then a list of available CPUs is printed.

```
$ rustc -C target-cpu=help
error: no input filename given
```

It works if file compiles and manages to reach trans, though.

**Comment by steveklabnik** [comment]
Triage: same issue today.

**Comment by bluss** [comment]
This is basically #30961

**Comment by nagisa** [comment]
I disagree. The linked issue is only complaining about us suggesting to use `llc` whereas here the issue is about option value working this or another way depending on whether a specific stage of compilation is reached.

**Comment by ranma42** [comment]
This is going to be affected by #31709, as it moves the initialisation of LLVM to a much earlier stage.

**Comment by xen0n** [comment]
Random triage: already fixed by #31709.

**Comment by bluss** [comment]
Thanks, this is now fixed. (The fix is in Rust 1.13 at least, may be earlier).
