### ISSUE TITLE
Reconcile ".." (range notation) and "..." (range patterns) syntax

### ISSUE THREAD

**Issue by genbattle** [rust-lang/rust#22389]
Currently Rust has both ".." and "..." for range indication in different contexts.

Range notation ".." is available throughout the language globally as the standard range notation syntax, except for in match pattern ranges. In [match patterns](http://doc.rust-lang.org/reference.html#match-expressions) "..." is used to match a range of values *inclusively* (including both of the values specifying the range). In contrast, standard range notation is inclusive of the lower bound, but exclusive of the upper bound. Match pattern notation "..." will not currently work at all in place of range notation ".." or vice versa.

It seems strange that we have two different range syntaxes, with similar meanings, yet completely mutually exclusive use-cases. From what I can guess it seems like this may be related to the use of ".." as *wildcard* syntax in match statements.

I think we should either extend both syntaxes to each others' specific use-case so they are both usable globally for any range, or abolish one of the syntaxes (probably "..."). As I have mentioned, the overlap with match wildcards might mean another syntactical change to avoid creating syntactical ambiguity. I didn't really know where to start with this as it's a sort of change that might need an RFC, so I thought I'd at least put up an issue to track it and get some feedback.

EDIT:
This would be forward-compatible if both syntaxes are extended to each others' use cases but retain their independent meanings (exclusive and inclusive ranges respectively) so doesn't **need** to be done pre-1.0.

**Comment by japaric** [comment]
This topic is currently being debated in the [discuss forums](http://internals.rust-lang.org/t/vs-for-inclusive-ranges/1539), you should join the discussion if interested!

Also, this sort of language changes belong to the [rust-lang/rfcs](https://github.com/rust-lang/rfcs) issue tracker, as they required an approved RFC before implementing them. Could you move this issue over there? We are trying to keep this issue tracker focused on actionable bugs/accepted features.

**Comment by genbattle** [comment]
Ah, I wasn't aware of the discussion in the forum, I'll move this to RFCs now, thanks!
