### ISSUE TITLE
Turn on CFG_DISABLE_DEBUG by default

### ISSUE THREAD

**Issue by pcwalton** [rust-lang/rust#22390]
There's no reason to have `debug_assert!` enabled for most of our binaries. This is probably a lot of the reason behind our benchmark problems!

I nominate for P-high.

**Comment by pnkfelix** [comment]
cc #17081

cc https://github.com/rust-lang/rfcs/pull/563

**Comment by nikomatsakis** [comment]
cc https://github.com/rust-lang/rust/issues/22492

**Comment by pnkfelix** [comment]
P-high, 1.0 polish.

**Comment by michaelwoerister** [comment]
Removed `A-debuginfo`. This is a build system issue.
