### ISSUE TITLE
Minimum android NDK version should be updated

### ISSUE THREAD

**Issue by ejjeong** [rust-lang/rust#22398]
On android NDK version before r9d, it only provided gdb 7.3.
And gdb 7.3 cannot understand DWARF4, which is generated by llvm by default.

Minimum NDK version should be updated like below (both for buildbot & wiki):
* ndk version > r10
* toolchain gcc version > gcc 4.8

For now, instead of upgrading the NDK version,
the default dwarf version will be lowered as DWARF2, like OSX.

**Comment by lahwran** [comment]
Was this fixed by ejjeong's commit?

**Comment by lahwran** [comment]
looks like it wasn't.

**Comment by ejjeong** [comment]
It's not fixed yet.

**Comment by steveklabnik** [comment]
Triage: it's unclear to me where the minimum ndk version is specified. So I can't tell if this has been fixed or not.

**Comment by lahwran** [comment]
I don't remember at this point

**Comment by alexcrichton** [comment]
Right now we actually somewhat guarantee API level 18 in the standard library (compatibility-wise), so we're probably not going to update this. CI we've got basically taken care of, so we should be good on that front.

**Comment by ejjeong** [comment]
FYI: https://github.com/rust-lang/rust-wiki-backup/blob/master/Doc-building-for-android.md
This old wiki had described that minimum ndk version is r9b.
