### ISSUE TITLE
{:?} should not escape printable characters

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#22412]
E.g. äöüß

**Comment by LukasKalbertodt** [comment]
Currently `escape_default` is called for every character... I agree that the Debug output shouldn't escape printable characters. Although I think that it should escape [C0 and C1 Control Characters](http://en.wikipedia.org/wiki/C0_and_C1_control_codes). I guess that's what the user wants.
If anyone agrees I will fix that...

**Comment by aturon** [comment]
I'm on board with this, personally. @alexcrichton, @seanmonstar?

**Comment by alexcrichton** [comment]
Sounds good to me

**Comment by seanmonstar** [comment]
Me as well. One can always print as_bytes if they need to compare with
unicode symbols that look alike.
