### ISSUE TITLE
Make OsStrExt::from_bytes a free function

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#22417]
Or make the return type &Self.

**Comment by mahkoh** [comment]
&Self won't work so a free function.

**Comment by huonw** [comment]
What's the motivation?

**Comment by mahkoh** [comment]
To use it you have to import both OsStr and OsStrExt and then write
```rust
<OsStr as OsStrExt>::from_bytes
```

**Comment by aturon** [comment]
FWIW, it works fine to write `OsStr::from_bytes(slice)`, you don't need UFCS here.

**Comment by aturon** [comment]
@alexcrichton do you have thoughts on this? Given that the direct call works, it seems to me that we should stick to the usual convention of using an associated function for a constructor like this.

**Comment by mahkoh** [comment]
>FWIW, it works fine to write OsStr::from_bytes(slice)

I thought I tested this but it works now. libstd also uses the other syntax:

```
rust/src/libstd/sys/unix$ ack "<OsStr as OsStrExt>::from_bytes" | wc -l
2
```

**Comment by alexcrichton** [comment]
> @alexcrichton do you have thoughts on this? Given that the direct call works, it seems to me that we should stick to the usual convention of using an associated function for a constructor like this.

I had personally totally forgotten that one could do `OsStr::from_bytes` without UFCS-like notation, so given that I'm totally ok with the current situation.
