### ISSUE TITLE
Field spelling correction suggests private fields

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#22421]
```rust
fn main() {
    let x: Vec<()> = vec![];
    x.pttr;
}
```

```
foo.rs:3:5: 3:11 error: attempted access of field `pttr` on type `collections::vec::Vec<()>`, but no field with that name was found  
foo.rs:3     x.pttr;
             ^~~~~~
foo.rs:3:7: 3:11 help: did you mean `ptr`?
foo.rs:3     x.pttr;  
               ^~~~
```

**Comment by kmcallister** [comment]
Maybe we should print these suggestions for in-crate structs (because you might have forgot a `pub`) but not for out-of-crate.

**Comment by ucarion** [comment]
Can I try to take care of this one?

**Comment by kmcallister** [comment]
Sounds great!

**Comment by leejunseok** [comment]
Woops, my apologies, I should have voiced my intention to work on this before I started. Incoming PR!

**Comment by oli-obk** [comment]
There is an `A-amusing` label? :D 

anyway, that bug is totally my fault, i did not even remotely think about private fields
