### ISSUE TITLE
"macro expansion ignores" error should explain why

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#22425]
afaik, it's because the context where you're using the macro (expr, item, etc.) stopped parsing before that token.  We should mention that context.

**Comment by wesleywiser** [comment]
Is this fixed? I think this was fixed the referenced pull request.

**Comment by jonas-schievink** [comment]
I'd prefer a message like `the use of X is likely invalid in this {statement, expression, pattern, ...} context`
