### ISSUE TITLE
Forbid unusable type aliases

### ISSUE THREAD

**Issue by Stebalien** [rust-lang/rust#22434]
As far as I can tell, the following type alias is unusable:
```rust
type I<'a> = &'a (Iterator + 'a);
```
This isn't a complete type because `Iterator::Item` is unspecified and isn't usable because there is no way to specify `Iterator::Item` (as far as I know) after the fact.

Personally, I feel type aliases like this should be compile time errors. I'm bringing this nitpick up now because fixing it is technically a breaking change .

**Comment by jonas-schievink** [comment]
```rust
type I<'a> = &'a (Iterator + 'a);

fn main() {}
```
now gives:
```
<anon>:1:19: 1:32 error: the value of the associated type `Item` (from the trait `core::iter::Iterator`) must be specified [E0191]
<anon>:1 type I<'a> = &'a (Iterator + 'a);
                           ^~~~~~~~~~~~~
<anon>:1:19: 1:32 help: see the detailed explanation for E0191
error: aborting due to previous error
```

So this looks fixed!
