### ISSUE TITLE
Traits inheriting from Fn don't implement Fn

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/rust#22431]
The following does not compile:

```rust
trait MyFn: Fn(usize) -> usize {}

fn call<F>(f: F) -> usize
    where F: MyFn
//    where F: Fn(usize) -> usize
{
    f(5)
}

fn main() {
    call(|a| a + 3);
}
```

The error is: 

```
error: the trait `MyFn` is not implemented for the type `[closure <anon>:11:10: 11:19]
```

However, if you swap out the where clauses, it does compile. I would have expected `MyFn`, which has `Fn` as a supertrait, to be usable in the places `Fn` is. Tested on `rustc 1.0.0-dev (342ab53bf 2015-02-15 12:20:31 +0000)`

**Comment by Centril** [comment]
Original code where the error was found:

```rust
#![feature(core)]
#![feature(std_misc)]

use std::thread::{Thread, JoinGuard};

fn callback(v: usize) -> usize { v * 2 }

trait CB: Fn(usize) -> usize + Send {}

struct S<T>
where T: CB {
    cb: T,
}

fn threaded<'a, T>(s: S<T>) -> JoinGuard<'a, usize>
where T: CB {
    Thread::scoped( move || {
        (s.cb)(1337)
    })
}

fn main() {
    if let Ok(r) = threaded( S { cb: callback } ).join() {
        println!("{}", r);
    }
}
```

**Comment by japaric** [comment]
This is correct behaviour. A supertrait means that the implemntor must also implement the subtraits, but doesn't generate any implementation by itself. I think that your example is missing a blanket `impl` to make implementors of `Fn(usize) -> usize` also implement the `MyFn` trait. The following code works:

``` rust
trait MyFn: Fn(usize) -> usize {}

// Add this blanket implementation
impl<F> MyFn for F where F: Fn(usize) -> usize {}

fn call<F>(f: F) -> usize where F: MyFn {
    f(5)
}

fn main() {
    call(|a| a + 3);
}
```

@Centril same issue, you need to add `impl<F> CB for F where F: Fn(usize) -> usize + Send {}
` to make your code work.

**Comment by shepmaster** [comment]
@japaric thanks, that makes sense to me. I think I'll close this as "programmer misunderstanding" :smile_cat:
