### ISSUE TITLE
fill in the missing rules and FIXMEs in grammar.md

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#22445]
Spawned off of #19278 

http://doc.rust-lang.org/grammar.html is an auto-generated document that claims to be the authority on Rust's grammar.  But it is quite incomplete right now.

So we should finish it.

This is meant to be a meta-bug, since I suspect it will be best to create sub-issues (or at least individual PRs) dedicated to certain sections of the grammar, rather than trying to fix it all at once.

**Comment by pnkfelix** [comment]
(I guess my intention is that we close this ticket once there are no more obviously missing rules or really bad FIXME's in grammar.md)

**Comment by steveklabnik** [comment]
Traige: there's been renewed work on a real grammar, but this is still far from done.

**Comment by steveklabnik** [comment]
Triage: grammar is being moved to the reference. closing!
