### ISSUE TITLE
Tracking issue for CStr, the dereferenced complement to CString (RFC 592)

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#22469]
https://github.com/rust-lang/rfcs/pull/592

**Comment by aturon** [comment]
cc @mzabaluev @alexcrichton 

Nominating for 1.0-beta P-backcompat-libs

**Comment by alexcrichton** [comment]
I'm taking care of this in a patch for #22470 as well.

**Comment by mahkoh** [comment]
Practically all of these functions should be #[inline]. Unless iter().position is as fast as memchr now, those uses should be replaced my memchr.
