### ISSUE TITLE
Security policy

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#22464]
There needs to be a clear policy for reporting and managing bugs that may result in security vulnerabilities. Probably this will involve a well-publicized and secure way to report them, and a private tracker.

cc https://github.com/rust-lang/rfcs/issues/882

I opened this here just to nominate it. Intended discussion to be on the RFC tracker.

**Comment by pnkfelix** [comment]
1.0 polish, "accessory infrastructural stuff that is not in code"

**Comment by pnkfelix** [comment]
Assigning to @steveklabnik who will put together a documentation or presentation summarizing our options here.

**Comment by steveklabnik** [comment]
https://www.rust-lang.org/security.html now exists, so this is fixed.

**Comment by ranma42** [comment]
@steveklabnik is the security page reachable (indirectly, but without going through github issues/PRs) from the front page? I have been looking for links to it, but I did not find any.

**Comment by steveklabnik** [comment]
It is not currently, because we needed to get the announcement list up. The list is now up, but the page has not been rebuilt. @edunham is looking into it. 

As for adding the link, it's part of the general web improvement work that's going on.
