### ISSUE TITLE
Tracking issue for Rename some of the standard collections for consistency and clarity (RFC 580)

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#22479]
https://github.com/rust-lang/rfcs/pull/580

**Comment by aturon** [comment]
cc @CloudiDust @Gankro @alexcrichton 

Nominating for 1.0-beta P-backcompat-libs. But it would be great to land this before alpha2...

**Comment by aturon** [comment]
I'm planning to implement this, but if someone else is interested, ping me on IRC.

**Comment by Gankro** [comment]
For reference:

* DList -> LinkedList
* Bitv -> BitVec
* BitvSet -> BitSet
* RingBuf -> VecDeque

Types, files, and modules should all be renamed.

**Comment by Gankro** [comment]
(bitv and bitvset are actually in a "bit" file, which shouldn't be renamed)

**Comment by pnkfelix** [comment]
1.0 beta, P-backcompat-libs.  (May be able to be closed; @alexcrichton  is looking)

**Comment by alexcrichton** [comment]
Implemented in https://github.com/rust-lang/rust/pull/22483 landed in https://github.com/rust-lang/rust/pull/22491 rolled into https://github.com/rust-lang/rust/pull/22541
