### ISSUE TITLE
Clearly distinguish errors parsing a macro definition from errors parsing the invocation

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#22472]
Right now they occur at the same stage of compilation, and look very similar owing to `macro_rules!`'s self-invoking parsing.

Related: #21370

**Comment by steveklabnik** [comment]
Triage: this ticket overall is unclear to me, or rather, I'm not sure how to come up with an example here.

**Comment by Mark-Simulacrum** [comment]
Without an example (which I can't come up with based on the description), I'm going to close this.
