### ISSUE TITLE
All running Rust programs show up as "<main>" in `top`

### ISSUE THREAD

**Issue by nnethercote** [rust-lang/rust#22476]
Here's an example line from `top` on my Linux box:
```
 2613 njn       20   0 5388028 2.579g  32984 R 462.8  8.3  14:22.37 <main>                         
```
This was annoying just now because I had `rustc` building and also Servo running, and I couldn't distinguish them easily.

**Comment by alexcrichton** [comment]
I think this should have been fixed in https://github.com/rust-lang/rust/pull/21920, what version of `rustc` were you using to compile the program in question?

**Comment by nnethercote** [comment]
> what version of rustc were you using to compile the program

Servo is currently built with snapshot 80627cd3cc4099b76cb2fb26ebe2f2f8a6c2335e of Rust.

I don't know what version of Rust current Rust tip uses to build its own stage2.

**Comment by alexcrichton** [comment]
Ah ok, that doesn't include #21920 so I'm going to close this as believed fixed. Feel free to reopen if this reproduces once you guys update rust again though!
