### ISSUE TITLE
Tracking issue for Add a generic string pattern matching API (RFC 528)

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#22477]
https://github.com/rust-lang/rfcs/pull/528

**Comment by aturon** [comment]
cc @Kimundi 

Nominating for 1.0-beta P-high.

**Comment by pnkfelix** [comment]
1.0 beta P-high

**Comment by Kimundi** [comment]
Current status: A basic implementation landed, but there is still work to do:

- remaining proposed methods need to be implemented
- former optimizations need to be reimplemented (For example, the string search is currently naive and does needless bound checks)
- some implemented things differ from the proposal
  - methods like match_indices might change their iterator type
  - the searcher traits should be namespaced to allow future replacement with HKT ones
- Usage with methods like `push` or `replace` need to be evaluated, and a potential follow up RFC written

**Comment by pnkfelix** [comment]
Remaining issues are not beta-blockers nor even 1.0 blockers.  Reclassifying as P-high, not 1.0.

**Comment by bluss** [comment]
Thanks kimundi for updating your status comment. It looks like this is as good as done — what remains is related followup.

**Comment by alexcrichton** [comment]
I'm going to close this in favor of the new tracking issue over at https://github.com/rust-lang/rust/issues/27721
