### ISSUE TITLE
Internal error looking up a definition [E0242] with where clause on type alias

### ISSUE THREAD

**Issue by nwoeanhinnogaehr** [rust-lang/rust#22471]
Trying to compile this:
```
type Foo<T> where T: Copy = Box<T>;
```
gives the following:
```
<anon>:1:22: 1:26 error: internal error looking up a definition [E0242]
<anon>:1 type Foo<T> where T: Copy = Box<T>;
                              ^~~~
```
I'm not entirely sure if this is actually legal, but regardless it seems odd that an "internal error" is exposed to the user in the same way that regular compiler errors are.

```rustc 1.0.0-nightly (b63cee4a1 2015-02-14 17:01:11 +0000)```

**Comment by nagisa** [comment]
Something completely useless, but possibly fun: the line of code responsible for this error is almost 4 years old now introduced in 48a69d2100622df88e3f1014eff00227401bf079. During all those years it survived at least 4 switches to and from `~""` strings.
