### ISSUE TITLE
Tracking issue for Get panics out of std::ffi::CString (RFC 840)

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#22470]
https://github.com/rust-lang/rfcs/pull/840

**Comment by aturon** [comment]
cc @mzabaluev @alexcrichton 

Nominating for 1.0-beta P-backcompat-libs

**Comment by mzabaluev** [comment]
Thanks for going forward with this and #22469!

Should there be any migration path where the new graceful functions are landed under temporary names, and the existing ones deprecated?

Do you plan to work on this any time soon? I could have a crack at it if this could help get it done faster.

**Comment by alexcrichton** [comment]
I plan on deprecating some of the free functions but some of the other functions will likely be lost with no replacement. I should also mention that I'm about 90% of the way there for this patch, just want to make sure we don't duplicate work :)

**Comment by mzabaluev** [comment]
@alexcrichton Great, I'll get busy with my own things then.
