### ISSUE TITLE
Reference to const that is a reference implicitly flattens

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#22481]
```rust
fn foo() -> &'static i32 {
    const F: &'static i32 = &3;
    &F
}

fn main() {
    println!("{}", foo());
}
```
This compiles and prints the right value, as does the same program with the `&` in front of `F` removed.

cc @eddyb probably related to the const rvalue promotions change.

**Comment by eddyb** [comment]
This is deref coercions. Welcome to the future :).
