### ISSUE TITLE
Change suffixes to `isize` and `usize`

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#22496]
Tracking issue for rust-lang/rfcs#573

**Comment by pnkfelix** [comment]
Reopening, apparently `us`/`is` is still being silently accepted?

Example on [playpen](http://is.gd/mIpSkK):

```rust
fn main() {
    let foo = 2us;
    println!("foo: {}", foo);
}
```

See also http://internals.rust-lang.org/t/how-did-the-is-us-suffixes-survive/1871

**Comment by pnkfelix** [comment]
Nominating: I want to figure out if a fix for this needs to be backported to beta, or to 1.0, or if we are stuck accepting it for now (or forever).

**Comment by nikomatsakis** [comment]
The problem seems to be in this commit: 54f16b818b58f6d6e81891b041fc751986e75155

**Comment by nikomatsakis** [comment]
Specifically [here](https://github.com/rust-lang/rust/commit/54f16b818b58f6d6e81891b041fc751986e75155#diff-899f995d4388dafbea87f6f67b5c7609R713).

**Comment by brson** [comment]
I'll put a patch together.
