### ISSUE TITLE
Remove ndebug and replace with compiler flags (RFC 563)

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#22492]
Tracking issue for https://github.com/rust-lang/rfcs/pull/563.

Nominating.

**Comment by pnkfelix** [comment]
P-backcompat-lang, 1.0 beta.

**Comment by nikomatsakis** [comment]
We have to figure out who is going to implement this.

cc @Aatch @alexcrichton @brson @huonw -- you guys seem like likely candidates and/or had strong opinions on the RFC thread, are any of you interested?

**Comment by alexcrichton** [comment]
I can implement this.

**Comment by rprichard** [comment]
Cargo has a [profile setting](http://doc.crates.io/manifest.html#the-[profile.*]-sections), "debug = false", that passes `--cfg ndebug` to `rustc`.  [Link to code.](https://github.com/rust-lang/cargo/blob/4f9bf542466982085decc605402ee312f4328571/src/cargo/ops/cargo_rustc/mod.rs#L610)  Should this be changed to `--cfg debug_assertions`?

**Comment by rprichard** [comment]
> Cargo has a profile setting, "debug = false", that passes --cfg ndebug to rustc. Link to code. Should this be changed to --cfg debug_assertions?

This specific change is probably wrong, but maybe Cargo should not be passing `--cfg ndebug` anymore.

**Comment by alexcrichton** [comment]
Yes I think cargo needs to grow support for this specific option as well, can you open a bug in the Cargo repo for this feature?

**Comment by rprichard** [comment]
I filed this issue, https://github.com/rust-lang/cargo/issues/1398.
