### ISSUE TITLE
rand is gone, fix the book

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#22518]
https://github.com/rust-lang/rfcs/pull/722

The Guessing Game won't work now.

**Comment by steveklabnik** [comment]
nominating for 1.0-beta

**Comment by vks** [comment]
I think the easiest fix is hard-coding a number. A proper random number generation can be implemented after cargo has been introduced.

**Comment by steveklabnik** [comment]
I actually have some bigger plans maybe, so we'll see. Nobody should tackle this ticket in the meantime, I'll be handling it.

**Comment by pnkfelix** [comment]
1.0 polish.

**Comment by steveklabnik** [comment]
Okay, I cannot rely on `rand` becoming stable, so I will be re-doing this section.
