### ISSUE TITLE
Audit #[derive]s in std for stability

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#22511]
`#[derive(Foo)]` currently just takes the stability of `Foo`, which may not be what we want for some types in `std`.

cc #22500

According to
```
$ git grep -C 5 '#\[derive' -- liballoc/ libarena/ libcollections/ libcore/ libstd/ libunicode/ | grep -C 5 '\[stable' | grep ':[0-9]\+:' | sed 's/:.*//' | sort | uniq
```
these files have a `#[derive]` attribute near a `#[stable]` one:

- [x] libcollections/ (12) @huonw https://github.com/rust-lang/rust/issues/22511#issuecomment-76663895
    - binary_heap.rs
    - bit.rs
    - btree/map.rs
    - btree/set.rs
    - dlist.rs
    - string.rs
    - vec_map.rs
- [x] libcore/ (37) @huonw https://github.com/rust-lang/rust/issues/22511#issuecomment-76666327
    - any.rs
    - atomic.rs
    - char.rs
    - cmp.rs
    - default.rs
    - fmt/mod.rs
    - fmt/rt/v1.rs
    - num/mod.rs
    - ops.rs
    - option.rs
    - result.rs
    - slice.rs
    - str/mod.rs
- [x] libcore/iter.rs (18) @huonw https://github.com/rust-lang/rust/issues/22511#issuecomment-76667134
- [x] libstd/ (10) @huonw https://github.com/rust-lang/rust/issues/22511#issuecomment-76662992
    - collections/hash/map.rs
    - collections/hash/set.rs
    - sync/mpsc/mod.rs
    - thread.rs

Replacing the `sed ...` with `wc -l` gives 77, i.e. there are approximately 77 `#[derive]`s to look at (nearly 25% of which are in core::iter, hence it being listed separately).

Comment below if you wish to handle some of these.

**Comment by huonw** [comment]
cc @aturon, @alexcrichton 

# `std`

The only dubious implementation is the `#[derive(Clone)]` for [`std::thread::Thread`](https://github.com/rust-lang/rust/blob/157614249594f187f421cd97f928e64c5ab5c1fa/src/libstd/thread.rs#L452-L457). I (very vaguely) recall that there was some discussion about changing the internals of `Thread` to not have the `Arc` (I could very easily be misremembering). This may make the `Clone` impossible in future.

**Comment by huonw** [comment]
### `collections`

All `#[derive]`s seem fine. Although there are a few cases of `Debug` not necessarily having the output we want, long term (e.g. `collections::string::FromUtf8Error` will print a whole raw `Vec<u8>` with the `[ , , , ]` syntax) but its not clear what guarantees we want to give about the precise output of `Debug` (not many, IMO).

**Comment by huonw** [comment]
### `core`

Why is `core::fmt::Arguments` `Copy`? https://github.com/rust-lang/rust/blob/157614249594f187f421cd97f928e64c5ab5c1fa/src/libcore/fmt/mod.rs#L212-L233

`RangeFull` and `RangeTo` are `Copy` but `Range` and `RangeFrom` are not.

The `Ord`ering/`PartialOrd`ering of `Option` and `Result` is inconsistent (in the sense of `Option<T>` ≅ `Result<T, ()>`): `None < Some(_)`, but `Err(_) > Ok(_)`.

**Comment by huonw** [comment]
### `core::iter`

All seems fine: they're essentially all just `#[derive(Clone)]`s.

(Although I did notice https://github.com/rust-lang/rust/issues/22950 in the process.)

**Comment by SimonSapin** [comment]
> The Ordering/PartialOrdering of Option and Result is inconsistent (in the sense of Option<T> ≅ Result<T, ()>): None < Some(_), but Err(_) > Ok(_).

Either `None < Some(_)` or `None > Some(_)` (similarly for `Result`) is arbitrary. Should they really implement `PartialOrd` at all?

**Comment by alexcrichton** [comment]
> The only dubious implementation is the #[derive(Clone)] for std::thread::Thread. I (very vaguely) recall that there was some discussion about changing the internals of Thread to not have the Arc (I could very easily be misremembering). This may make the Clone impossible in future.

Hm I feel like this was some other structure we may remove the `Arc` from. I think that this handle must fundamentally have an `Arc` as it's handed out to other threads for `park` and `unpark`. That being said we could also be more conservative for now!

> Why is core::fmt::Arguments Copy? https://github.com/rust-lang/rust/blob/157614249594f187f421cd97f928e64c5ab5c1fa/src/libcore/fmt/mod.rs#L212-L233

I believe that we used to pass the structure by reference but we now pass it by value sometimes necessitating the `Copy` bound. I would also be fine going back to passing it by reference by convention (I believe there's also an issue about the codegen of pass-by-value which is tangentially related)

> RangeFull and RangeTo are Copy but Range and RangeFrom are not.

cc #21846

**Comment by aturon** [comment]
cc me

**Comment by huonw** [comment]
> Either None < Some(_) or None > Some(_) (similarly for Result) is arbitrary. Should they really implement PartialOrd at all?

I think so: it is useful for generic code (e.g. storing things in a tree, the details of the ordering usually don't matter, as long as one exists) and `#[derive]`, e.g. one might have

```rust
#[derive(PartialOrd)]
struct Foo {
     x: T
     y: U,
     z: Option<V>
}
```

The first two fields will usually completely distinguish instances of `Foo` and the last just serves as a tie-break; being forced to write out the `impl` manually is annoying. (FWIW, Haskell's `Maybe` and `Either` both implement `Ord`.)

**Comment by SimonSapin** [comment]
It’s not quite the same as `Option`, but FWIW `None` in Python 2 is less than all other objects. In Python 3, it was changed to be non-comparable to other objects.

**Comment by aturon** [comment]
> > > The only dubious implementation is the #[derive(Clone)] for std::thread::Thread. I (very vaguely) recall that there was some discussion about changing the internals of Thread to not have the Arc (I could very easily be misremembering). This may make the Clone impossible in future.

> Hm I feel like this was some other structure we may remove the `Arc` from. I think that this handle must fundamentally have an `Arc` as it's handed out to other threads for `park` and `unpark`. That being said we could also be more conservative for now!

The `Clone` is definitely wanted here, and the `Arc` is intended -- as you say, you want to be able to hand out copies of the handle to place in data structures for use with `park` and `unpark`.

**Comment by aturon** [comment]
@huonw 

> `RangeFull` and `RangeTo` are `Copy` but `Range` and `RangeFrom` are not.

Ugh that's bad. Hopefully the [Pod/Copy RFC](https://github.com/rust-lang/rfcs/pull/936) will help us clean this up.

**Comment by cmr** [comment]
@aturon  https://github.com/rust-lang/rust/pull/21846 is related.

**Comment by aturon** [comment]
I'm going to close this as complete. Thanks for heading this up, @huonw!
