### ISSUE TITLE
(Book) Confusing placement of Pointer Best Practices

### ISSUE THREAD

**Issue by zeroem** [rust-lang/rust#22521]
In the Pointers Chapter, the section labeled ["Best Practices"](http://doc.rust-lang.org/1.0.0-alpha/book/pointers.html#best-practices) discusses the preference for reference pointers over boxed pointers before the reader is introduced to boxed pointers.

**Comment by steveklabnik** [comment]
Yes, this is intended as a psudeo-reference chapter, like all things in the 'intermediate' section.

I have larger plans for this guide, but this is correct for its current incarnation.
