### ISSUE TITLE
Some objects get zeroed when copied from, affecting original object

### ISSUE THREAD

**Issue by bvssvni** [rust-lang/rust#22536]
```
rustc 1.0.0-nightly (6c065fc8c 2015-02-17) (built 2015-02-18)
```

From https://github.com/gfx-rs/gfx-rs/issues/574

In Gfx, something happens when `*buffer` (BufferHandle) is called, which zeroes whole or parts of the original object.

This might be a compiler bug.

cc @csherratt @kvark

**Comment by kvark** [comment]
Also see the workaround by @csherratt in https://github.com/PistonDevelopers/gfx_graphics/pull/136

**Comment by kvark** [comment]
I managed to extract a standalone snippet for you:
```rust
trait Resources {
    type Buffer: Copy;
}

struct BufferHandle<R: Resources> {
    raw: <R as Resources>::Buffer,
}
impl<R: Resources> Copy for BufferHandle<R> {}

#[derive(Copy)]
enum Res {}
impl Resources for Res {
    type Buffer = u32;
}

fn main() {
    let b: BufferHandle<Res> = BufferHandle { raw: 1 };
    let c = b;
    print!("{}{}", c.raw, b.raw);
}
```

**Comment by alexcrichton** [comment]
cc @nikomatsakis, @pnkfelix, looks like an associated type bug. Thanks @kvark for the reduction!

Also nominating.

**Comment by nikomatsakis** [comment]
Will investigate.

**Comment by nikomatsakis** [comment]
And yes, thanks @kvark !

**Comment by dotdash** [comment]
https://github.com/rust-lang/rust/blob/master/src/librustc/middle/ty.rs#L3594 -- I guess if `BoundCopy` is present, that should remove `TC::NeedsDrop`?

**Comment by kvark** [comment]
I'm sorry, is there any progress on this one? We are considering switching everything to `clone()` (in gfx-rs) as a workaround, and that would be pretty inconvenient, not to mention the work wasted...

**Comment by bvssvni** [comment]
This is the only bug that blocks Piston at the moment, but it does across several projects. Is there a way I can help?

**Comment by brson** [comment]
@kvark @bvssvni No progress yet, but @pnkfelix and @nikomatsakis will solve it soon, I just know it!

**Comment by pnkfelix** [comment]
@kvark @bvssvni I have a plausible fix.  I will hopefully put up a pull request with it tomorrow.

**Comment by bvssvni** [comment]
@pnkfelix You are awesome!

**Comment by pnkfelix** [comment]
P-backcompat-lang, 1.0
