### ISSUE TITLE
Do NFKC normalization in lexer

### ISSUE THREAD

**Issue by catamorphism** [rust-lang/rust#2253]
```next_token_inner``` in the lexer has a comment saying to do NKFC normalization. I have no idea what that is, but I guess we should do it.

reference: [NFKC](http://www.unicode.org/reports/tr15/#Norm_Forms) is one of four unicode Normalization Forms.

reference: [UAX-31](http://www.unicode.org/reports/tr31/) supplies guidelines for use of normalization with identifiers.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#802
