### ISSUE TITLE
Enable MISSING_DEBUG_IMPLEMENTATIONS by default

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#22534]
>Format trait for the :? format. Useful for debugging, all types should implement this.

**Comment by sfackler** [comment]
This exists: https://github.com/rust-lang/rust/blob/master/src/librustc/lint/builtin.rs#L1611-L1615

**Comment by mahkoh** [comment]
Is there a reason that it's not enabled?

**Comment by sfackler** [comment]
See discussion here: https://github.com/rust-lang/rust/pull/21610
