### ISSUE TITLE
Should shift int/uint tests around to avoid code repetition

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#22535]
Currently within 
```rust
macro_rules! uint_module { ($T:ty) => (
```
we have, after things that do use `$T`, the pair of tests:
```
#[test]
fn test_uint_to_str_overflow() { ... }
 #[test]
fn test_uint_from_str_overflow() { ... }
```
that do not reference `$T`.

As far as I can tell, these tests do not need to be inside the macro definition.  They should live outside it, so that we will not generate code for them and redundantly run them once for every integer type variant.

**Comment by alexcrichton** [comment]
Fixed in #22658
