### ISSUE TITLE
std::collections top-level docs are out of date

### ISSUE THREAD

**Issue by Gankro** [rust-lang/rust#22550]
http://doc.rust-lang.org/std/collections/#entries in particular makes reference to old method names. Wouldn't be surprised if other parts of the docs are similarly out of date. Need to do a full pass.

**Comment by djmally** [comment]
I'd like to tackle this (and work on sorting out other modules in collections as well), but are there any particular method names that stick out in the link above? I combed through it and didn't find any, and all the sample code builds, albeit with warnings.

**Comment by djmally** [comment]
Also, very new to contributing to Rust here-- where do these pages live in the repo?

**Comment by huonw** [comment]
The top-level docs are the big `//!` comment section at the top of src/libstd/collections/mod.rs. The individual modules docs are in the various .rs files in libcollections and libstd/collections.

Feel free to ask here or on IRC (either #rust-internals or #rust-libs are appropriate channels) if you need any more help or advice! :)

**Comment by Gankro** [comment]
The issue was made in reference to the linked section referring to non-existent `set` and `take` methods (now `insert` and `remove`). Didn't do a detailed comb for anything else.

**Comment by djmally** [comment]
Changes incoming, as soon as I sort out a git issue. One other thing I noticed was that in the performance tables (http://doc.rust-lang.org/std/collections/#sequences), a number of methods are referenced that don't exist for certain collections, e.g. `LinkedList` doesn't implement `get`, `insert`, or `remove`, and `VecMap` doesn't implement `predecessor`, among other similar cases. Not really sure what the course of action should be here: should these methods be marked somehow to show that they don't exist by that name for that collection, or should there be a note stating that the names in this table may not be exact?

**Comment by Gankro** [comment]
I believe I have a quick one-liner above the table that says something to the affect of "actual methods may differ". Any methods that are missing are just "to implement".

**Comment by djmally** [comment]
I don't see anything in the section preceding the table, but I can add it in if it's not there.

**Comment by steveklabnik** [comment]
Closing since https://github.com/rust-lang/rust/pull/22973 was merged.
