### ISSUE TITLE
Specify behavior of functions taking `ToSockAddrs`

### ISSUE THREAD

**Issue by tbu-** [rust-lang/rust#22569]
Examples of such functions inclde `UdpSocket::bind` and `UdpSocket::send`. Is the first address taken, the last, are all addresses taken into consideration...

**Comment by steveklabnik** [comment]
I'm not 100% sure what this is asking, can you elaborate a bit, please?

**Comment by alexcrichton** [comment]
Functions that take `T: ToSocketAddrs` in the `std::net` module take an object which will be converted to any number of actual `SocketAddr` types. It's not currently clear what these methods do when there are multiple socket addresses that are resolved to.

For example, `TcpStream::connect` will attempt to connect to each address in turn (returning the first that succeeds), but `UdpSocket::send` will only send a datagram to the first address. Furthermore, there are questions like should `TcpListener::bind` bind to all the addresses or just one?

**Comment by steveklabnik** [comment]
Is the current behavior the correct one? IE, do we even want to make that guarantee?

**Comment by tbu-** [comment]
You could say what it does right now with a remark that it's not stabilized yet.

**Comment by steveklabnik** [comment]
I'm removing the 'docs' tag until we decide what we want to specify here.

**Comment by tbu-** [comment]
@steveklabnik Can you also remove the 'easy' tag?

**Comment by Aatch** [comment]
Is this still relevant? I don't think we change anything related in a backwards-compatible way.

**Comment by alexcrichton** [comment]
This is basically just a docs thing now, we need to be sure we specify what happens if multiple addresses are returned.

**Comment by steveklabnik** [comment]
Moving to p-high and assigning myself; i'd like to get this resolved in the next release cycle.

**Comment by frewsxcv** [comment]
Opened a PR for this: https://github.com/rust-lang/rust/pull/44209
