### ISSUE TITLE
PhantomData not behaving as advertised

### ISSUE THREAD

**Issue by dylanede** [rust-lang/rust#22579]
As far as I can tell, from the point of view of lifetimes, `PhantomData<T>` should behave identically to `T`. This is unfortunately not the case in practice.

This function causes a mismatched type error on `x`:

```
fn cast_phantom<'a, 'b, T>(x: PhantomData<&'a T>) -> PhantomData<&'b T> where 'a : 'b {
    x
}
```

Whereas this similar function does not:

```
fn cast_actual<'a, 'b, T>(x: &'a T) -> &'b T where 'a : 'b {
    x
}
```

The variance rules of lifetimes should make both functions valid.

**Comment by pnkfelix** [comment]
cc @nikomatsakis

**Comment by japaric** [comment]
Have you tried with master? AFAIK the current nightly (dfc5c0f1e `Wed Feb 18 07:50:21 2015`) doesn't include the variance PR (#22541 look for the roll-up merge of #22286) which landed on 522d09d `Thu Feb 19 13:36:59 2015`

**Comment by japaric** [comment]
I can confirm `cast_phantom` compiles with `rustc 1.0.0-dev (522d09dfe 2015-02-19) (built 2015-02-20)` (on my ARM board).

**Comment by dylanede** [comment]
@japaric Ah, I was using the playpen to check that it still behaved the same on master. I guess next time I have an issue I better actually compile from master instead. It just takes so long though.

**Comment by japaric** [comment]
FWIW, [multirust](https://github.com/brson/multirust) is now providing nightlies `(built 2015-02-20)`. It seems the playpen/playbot is still using `(built 2015-02-18)`. From what I've seen multirust always provides the newest nightlies first, whereas travis-ci and the playpen tend to lag a little behind (1-2 days).
