### ISSUE TITLE
Type inference failure iterating over a vector of tuples?

### ISSUE THREAD

**Issue by sqweek** [rust-lang/rust#22576]
Hi, ran into this one using `rustc 1.0.0-nightly (706be5ba1 2015-02-05 23:14:28 +0000)`.

I couldn't see any similar issues filed but I'm fairly new to rust so apologies if I'm missing something obvious. Here's a simple example:

```
fn main() {
	let v = Vec::<(i32, f32)>::with_capacity(2);
	v.push((1, 2.5));
	v.push((2, 7.0));
	for (a, b) in v.iter() {
		println!("a: {}  b: {}", a, b);
	}
}
```

This fails to compile with the message:

```
vectuple.rs:5:2: 8:2 error: type mismatch resolving `<core::slice::Iter<'_, (i32, f32)> as core::iter::Iterator>::Item == (_, _)`:
 expected &-ptr,
    found tuple [E0271]
vectuple.rs:5 	for (a, b) in v.iter() {
```

It seems like rustc knows that the vector has an int+float tuple, but I don't really understand the error...

**Comment by sqweek** [comment]
The equivalent index based loop compiles fine, so easy to workaround at least.

**Comment by Nemikolh** [comment]
You don't have a strict equivalence with an index based loop as you have an [extra bounds checking](http://doc.rust-lang.org/book/iterators.html).
```rust
fn main() {
    let mut v = Vec::<(i32, f32)>::with_capacity(2);
    v.push((1, 2.5));
    v.push((2, 7.0));
    for &(a, b) in v.iter() {
        println!("a: {}  b: {}", a, b);
    }
}
```

Note: Use stackoverflow for this kind of question, for more information see [CONTRIBUTING.md](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) and the [community and get help section](http://doc.rust-lang.org/#community-&-getting-help) of the documentation.

**Comment by sqweek** [comment]
Fair call, avoiding the bounds check was exactly why I was trying to use iter() :)

Sorry to waste your time, thanks very much for the correction!

**Comment by Nemikolh** [comment]
No worries ! You didn't waste my time. :)
It is just recommended to use stackoverflow whenever possible to let place in issues for compiler bugs.
Thanks for closing the issue !
