### ISSUE TITLE
Send not implemented for std::fs::read_dir

### ISSUE THREAD

**Issue by markuskobler** [rust-lang/rust#22577]
Now that the new std::fs changes #21936 have landed. I'm getting the following error with code similar to this snippet http://is.gd/6usayc
```rust
fn scan_dir(dir: &Path, pool: &TaskPool, tx: Sender<Vec<io::Result<()>>>) -> io::Result<()> {
    // Read directory outside of task pool
    let entries = try!(fs::read_dir(dir));
    pool.execute(move || {
        let mut stats = Vec::new();
        for entry in entries {
            /* ...process files... */
        }
        tx.send(stats).unwrap();
    });
    Ok(())
}
```

Error:
```rust
<anon>:27:10: 33:7 error: the trait `core::marker::Send` is not implemented for the type `*mut libc::types::common::posix88::DIR` [E0277]
          ...
<anon>:27:10: 33:7 note: `*mut libc::types::common::posix88::DIR` cannot be sent between threads safely
```

Is it really unsafe to move the read_dir results to a TaskPool?

**Comment by nagisa** [comment]
Note that the function does not build a list, but rather generates results lazily, therefore yes, sending result of fs::read_dir into a thread is not safe. 

Wrap the iterator into `Arc` or build a list before sending it to the threads with `fs::read_dir(dir).collect<Vec<_>>()`.

**Comment by markuskobler** [comment]
Thanks @nagisa that allows me to work around the issue but looking at the code its not clear, to me at least, what benefit of an Rc<PathBuf> is in https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/fs2.rs.

```
pub struct ReadDir {
    dirp: *mut libc::DIR,
    root: Rc<PathBuf>,
}

pub struct DirEntry {
    buf: Vec<u8>,
    dirent: *mut libc::dirent_t,
    root: Rc<PathBuf>,
}
```

**Comment by nagisa** [comment]
Rc only allows sharing a pointer inside the same thread. I can’t quite say now why Rc is necessary here without looking at the code, but it is an implementation detail and doesn’t help to deal with the original problem.
