### ISSUE TITLE
Documentation of Send/Sync is incomplete/outdated (also in UnsafeCell)

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#22572]
The documentation for Sync says
> Users writing their own types with interior mutability (or anything else that is not thread-safe) should use the NoSync marker type (from std::marker) to ensure that the compiler doesn't consider the user-defined type to be Sync.

However, there is no NoSync type anymore.

Send has virtually no documentation.

UnsafeCell says
> UnsafeCell<T> doesn't opt-out from any marker traits, instead, types with an UnsafeCell<T> interior are expected to opt-out from those traits themselves.

which, if I am informed correctly, is not true anymore - Send/Sync are removed automatically for anything containing an UnsafeCell.

**Comment by steveklabnik** [comment]
Which documentation is this?

**Comment by RalfJung** [comment]
<http://doc.rust-lang.org/std/marker/trait.Sync.html> and <http://doc.rust-lang.org/std/marker/trait.Send.html> and <http://doc.rust-lang.org/std/cell/struct.UnsafeCell.html>
