### ISSUE TITLE
Distribute rust-doc and compiletest binaries with the snapshot

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#22585]
make check-stage0 does not work because compiletest binary is not shipped with the snapshot. Would be also nice to have an equivalent of `make docs-stage0` which requires rust-doc being shipped too.

**Comment by kmcallister** [comment]
That'd be great for editing the standalone `.md` docs.

**Comment by steveklabnik** [comment]
Triage: no change I'm aware of.

**Comment by nagisa** [comment]
We bootstrap from nightlies now, so distributing compiletest with that is likely to be not feasible, but we do distribute rustdoc now.

**Comment by alexcrichton** [comment]
We actually no longer have snapshots, only releases, so this issue is actually no longer relevant

(and to boot this should work much more as expected with rustbuild!)
