### ISSUE TITLE
spurious "error: parameter `Self` is never used`" for trivial `trait T {}`

### ISSUE THREAD

**Issue by insaneinside** [rust-lang/rust#22598]
[Given the input](http://is.gd/GmxfTA)

```rust
trait T {}
```

rustc will complain:

```
<anon>:2:1: 2:11 error: parameter `Self` is never used
<anon>:2 trait T {}
         ^~~~~~~~~~
<anon>:2:1: 2:11 help: consider removing `Self` or using a marker such as `core::marker::PhantomFn`
<anon>:2 trait T {}
         ^~~~~~~~~~
```

This may just be a diagnostics issue, but I'll let someone more familiar with Rust make that judgement.

**Comment by alexcrichton** [comment]
This is actually intended due to a [recently merged RFC](https://github.com/rust-lang/rfcs/pull/738).

You can find some more info about this [in the RFC](https://github.com/rust-lang/rfcs/blob/master/text/0738-variance.md#designating-marker-traits) as well.

**Comment by insaneinside** [comment]
This is **still** a diagnostics error.  There *is* no parameter `Self`, so the error should explain why it thinks there is one.
As the RFC says,
> The goal is to help users as concretely as possible.

The current error message is confusing and misleading.  This does not help users.

**Comment by huonw** [comment]
Reopening for the error message.

**Comment by bluss** [comment]
I've had a useful trait stop working with this error:

```rust
pub trait Graphlike {
    type NodeId: Clone;
}
```

    error: parameter `Self` is never used

**Comment by insaneinside** [comment]
@bluss, read the RFC linked by alexcrichton: you need to use `PhantomFn`.

**Comment by shepmaster** [comment]
or better (from the docs):

```rust
use std::marker::MarkerTrait;
trait Graphlike : MarkerTrait { }
```

**Comment by apasel422** [comment]
This can be closed, as the original example now compiles without error.

**Comment by insaneinside** [comment]
@apasel422 [The playpen linked in the original post](http://is.gd/GmxfTA) does not compile.

I still think that the suggestion to "consider removing `Self`" is completely bogus and confusing.

**Comment by bluss** [comment]
It should compile in the nightly, even if playpen doesn't have that version. PhantomFn was deprecated after beta.

**Comment by insaneinside** [comment]
Huh, did I accidentally close this one?

**Comment by apasel422** [comment]
The issue no longer exists in the nightly builds.

**Comment by insaneinside** [comment]
Oh!  When did Playpen change the default version to "beta"?  But now there's a different error...
Re-closing, in any case. :)
