### ISSUE TITLE
trace_macros output should use span_note?

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#22597]

**Comment by asolove** [comment]
I am interested in improving the trace_macros output, but there is a strongly-worded note that `trace_macros` "is a nasty hack that will certainly be removed." If it's going to be around for a while, though, I might take a crack at this.

The program:

```rust
#![feature(trace_macros)]

macro_rules! double {
    ($x:expr) => (2 * $x)
}

fn main() {
    trace_macros!(true);
    println!("{}", double!(21));
}
```

currently outputs:

```
println! { "{}" , double ! ( 21 ) }
print! { concat ! ( "{}" , "\n" ) , double ! ( 21 ) }
double! { 21 }
42
```

What is the desired output? I suspect it includes showing the span of the currently-expanding macro and then showing the expansion back in the original source location?

**Comment by brson** [comment]
Triage: still could be improved, not clear how. Probably not `E-easy`.
