### ISSUE TITLE
Establish conventions for macro internals

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#22607]
We should establish conventions for how to expose the implementation details of macros as parts of the public API of a crate. Currently we have two "schemes"

* Prefix the name with `__` [example](https://github.com/rust-lang/rust/blob/master/src/libstd/thread_local/mod.rs#L47-L54)
* Liberal use of `#[doc(hidden)]` [example](https://github.com/rust-lang/rust/blob/master/src/libcollections/vec.rs#L1256-L1278)

It would be nice to standardize on the convention here as most of these internals "we'd really rather not expose". I personally like the double-underscore-prefix-plus-`#[doc(hidden)]` strategy but others may feel differently!

Nominating, this may tidy up some of our apis in std.

**Comment by brson** [comment]
I also think double underscore + doc hidden is the way to go.

This may even call for triple underscore. It's the only way to be sure.

**Comment by brson** [comment]
Actually, a random number of underscores chosen at compile time would probably be more foolproof.

**Comment by reem** [comment]
+1, since other libraries can use the same conventions.

**Comment by pnkfelix** [comment]
(wrong spot, @alexcrichton said should be RFC, closing)
