### ISSUE TITLE
Inconsistency in IteratorExt::all and ::any

### ISSUE THREAD

**Issue by Aatch** [rust-lang/rust#22617]
One of the methods takes `&mut self`, the other takes `self`, which is strange, since they are almost exactly the same code.

I'm guessing that `IteratorExt::all` should take `&mut self`, like `any` does.

**Comment by huonw** [comment]
cc @aturon

**Comment by oli-obk** [comment]
isn't this because `all` consumes the iterator completely and `any` only up to the first occurrence?

**Comment by Aatch** [comment]
@oli-obk both iterators behave the same way, `all` stops at the first `false` value, `any` stops at the first `true` value.

**Comment by aturon** [comment]
Thanks for the report, @Aatch. This was a mistake, and both should take `&mut self` precisely to clarify the consumption semantics.

This should be a trivial fix.

**Comment by aturon** [comment]
(Should be flagged 1.0-beta P-backcompat-libs)

**Comment by pnkfelix** [comment]
1.0 beta, P-backcompat-libs.
