### ISSUE TITLE
Rustdoc has broken HTML for deprecation reasons

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#22618]
See http://doc.rust-lang.org/core/marker/index.html

> ## Structs
> - \`'>ContravariantLifetime 	 Old-style marker trait. Deprecated.
> - ContravariantType 	Old-style marker trait. Deprecated.
> - \`'>CovariantLifetime 	Old-style marker trait. Deprecated.
> - CovariantType 	Old-style marker trait. Deprecated.
> - >\`'>InvariantLifetime 	Old-style marker trait. Deprecated.

It seems like the `PhantomData<&'a ()>` from the deprecation reason is being treated like HTML and causing some extra close angle brackets to appear.

**Comment by nagisa** [comment]
Fixed by https://github.com/rust-lang/rust/pull/22578
