### ISSUE TITLE
Spurious `Self` never used error whereas it is used in associated type

### ISSUE THREAD

**Issue by edwardw** [rust-lang/rust#22622]
```rust
trait Tuple {  // error: parameter `Self` is never used
    type Array: Toa<Item=Self>;
}

trait Toa {
    type Item;
    fn with_capacity(usize) -> Self;
}

fn main() {}
```

Does the usage of `Self` in associated type count? [RFC 738](https://github.com/rust-lang/rfcs/blob/master/text/0738-variance.md) doesn't say. It is an issue nonetheless IMHO.

**Comment by huonw** [comment]
cc @nikomatsakis

**Comment by nikomatsakis** [comment]
Now that traits with associated types are invariant with respect to their inputs, this example compiles fine.
