### ISSUE TITLE
Cow<T> isn't Send, even if T and <T as ToOwned>::Owned are

### ISSUE THREAD

**Issue by renato-zannon** [rust-lang/rust#22629]
The following doesn't compile, but I believe it should:

```rust
use std::borrow::{ToOwned, Cow};

fn main() {
  assert_send(Cow::Borrowed("foo"));
}

fn assert_send<T: Send>(_: T) {}
```

Error:
```
cow.rs:4:3: 4:14 error: the trait `core::marker::Send` is not implemented for the type `<str as collections::borrow::ToOwned>::Owned` [E0277]
cow.rs:4   assert_send(Cow::Borrowed("foo"));
           ^~~~~~~~~~~
cow.rs:4:3: 4:14 note: `<str as collections::borrow::ToOwned>::Owned` cannot be sent between threads safely
cow.rs:4   assert_send(Cow::Borrowed("foo"));
           ^~~~~~~~~~~
error: aborting due to previous error
```

Even though `<str as ToOwned>::Owned == String`, and `String: Send`. In fact, this compiles:
```rust
assert_send("foo");
assert_send("foo".to_owned());
```

`rustc 1.0.0-nightly (522d09dfe 2015-02-19) (built 2015-02-20)`

**Comment by japaric** [comment]
`Cow<'static, str>` should be `Send`, because the old definition that didn't use assoc types was `Send`. Probably the code that detects builtin bounds wasn't updated to handle associated types. cc @nikomatsakis @FlaPer87

**Comment by seanmonstar** [comment]
This breaks us in hyper. For now, I'll have to manually `impl Send for Request`, knowing that it's safe.,,
