### ISSUE TITLE
Consolidate docs for built-in syntax extensions

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#22621]
`concat_idents!` is useless (#13294) so skip it.

**Comment by jxcl** [comment]
Neither of the macro chapters have sections for "common macros". Should we add one? Presumably there would be quite a few of them.

**Comment by kmcallister** [comment]
There is [rustdoc](http://doc.rust-lang.org/std/index.html#macros) for the macros in std, plus some of the built-in syntax extensions.  It's not that easy to find; there used to be a `std::macros` module in the rustdoc output but no longer :(

I'm not sure exactly what should be documented where.  The built-in syntax extensions like `conact!` might deserve special mention, as they give you capabilities within `macro_rules!` that you otherwise would not have.

cc @steveklabnik

**Comment by jxcl** [comment]
I think `panic!`, `unreachable!`, `unimplemented!` and `vec!` also deserve mentions.

**Comment by mund** [comment]
I would like to take on the task of documenting all the common macros. I've started them and appreciate some input on how big the final list should be, and if every macro needs an example (or three). What about the most common one, prinln! ? Should that be in there too?

https://github.com/mund/rust/commit/a62e5e6f5081e52969bfe8a970f2b5a89bea6250

**Comment by steveklabnik** [comment]
It's not clear to me what doing this issue actually means. Moving some docs between some places?

**Comment by jxcl** [comment]
The original issue was to add several common macro definitions with examples in TRPL, which I agreed with. I'm not sure what's up with the edits.
