### ISSUE TITLE
Intermittent "Permission denied" on Windows

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#22628]
Example: http://buildbot.rust-lang.org/builders/auto-win-64-nopt-t/builds/2223

```
error: linking with `gcc` failed: exit code: 1
note: "gcc" '"-Wl,--enable-long-section-names"' '"-fno-use-linker-plugin"' '"-Wl,--nxcompat"' '"-static-libgcc"' '"-m64"' '"-L"' '"C:\\bot\\slave\\auto-win-64-nopt-t\\build\\obj\\x86_64-pc-windows-gnu\\stage2\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib"' '"-o"' '"x86_64-pc-windows-gnu\\stage2\\test\\stdtest-x86_64-pc-windows-gnu.exe"' '"x86_64-pc-windows-gnu\\stage2\\test\\stdtest-x86_64-pc-windows-gnu.o"' '"-Wl,--gc-sections"' '"C:\\bot\\slave\\auto-win-64-nopt-t\\build\\obj\\x86_64-pc-windows-gnu\\stage2\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\libtest-4e7c5e5c.rlib"' '"C:\\bot\\slave\\auto-win-64-nopt-t\\build\\obj\\x86_64-pc-windows-gnu\\stage2\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\libgetopts-4e7c5e5c.rlib"' '"C:\\bot\\slave\\auto-win-64-nopt-t\\build\\obj\\x86_64-pc-windows-gnu\\stage2\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\libterm-4e7c5e5c.rlib"' '"C:\\bot\\slave\\auto-win-64-nopt-t\\build\\obj\\x86_64-pc-windows-gnu\\stage2\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\libserialize-4e7c5e5c.rlib"' '"C:\\bot\\slave\\auto-win-64-nopt-t\\build\\obj\\x86_64-pc-windows-gnu\\stage2\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\liblog-4e7c5e5c.rlib"' '"C:\\bot\\slave\\auto-win-64-nopt-t\\build\\obj\\x86_64-pc-windows-gnu\\stage2\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd-4e7c5e5c.rlib"' '"C:\\bot\\slave\\auto-win-64-nopt-t\\build\\obj\\x86_64-pc-windows-gnu\\stage2\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcollections-4e7c5e5c.rlib"' '"C:\\bot\\slave\\auto-win-64-nopt-t\\build\\obj\\x86_64-pc-windows-gnu\\stage2\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\librand-4e7c5e5c.rlib"' '"C:\\bot\\slave\\auto-win-64-nopt-t\\build\\obj\\x86_64-pc-windows-gnu\\stage2\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\liballoc-4e7c5e5c.rlib"' '"C:\\bot\\slave\\auto-win-64-nopt-t\\build\\obj\\x86_64-pc-windows-gnu\\stage2\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\liblibc-4e7c5e5c.rlib"' '"C:\\bot\\slave\\auto-win-64-nopt-t\\build\\obj\\x86_64-pc-windows-gnu\\stage2\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\libunicode-4e7c5e5c.rlib"' '"C:\\bot\\slave\\auto-win-64-nopt-t\\build\\obj\\x86_64-pc-windows-gnu\\stage2\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcore-4e7c5e5c.rlib"' '"-L"' '"x86_64-pc-windows-gnu\\rt"' '"-L"' '"C:\\bot\\slave\\auto-win-64-nopt-t\\build\\obj\\x86_64-pc-windows-gnu\\llvm\\Release+Asserts\\lib"' '"-L"' '"C:\\bot\\slave\\auto-win-64-nopt-t\\build\\obj\\x86_64-pc-windows-gnu\\stage2\\bin\\rustlib\\x86_64-pc-windows-gnu\\lib"' '"-L"' '"C:\\bot\\slave\\auto-win-64-nopt-t\\build\\obj\\.rust\\bin\\x86_64-pc-windows-gnu"' '"-L"' '"C:\\bot\\slave\\auto-win-64-nopt-t\\build\\obj\\bin\\x86_64-pc-windows-gnu"' '"-Wl,--whole-archive"' '"-Wl,-Bstatic"' '"-Wl,--no-whole-archive"' '"-Wl,-Bdynamic"' '"-lws2_32"' '"-luserenv"' '"-lkernel32"' '"-lws2_32"' '"-luserenv"' '"-lcompiler-rt"'
note: C:/program files/mingw-w64/x86_64-4.9.1-win32-seh-rt_v3-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.1/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot open output file x86_64-pc-windows-gnu\stage2\test\stdtest-x86_64-pc-windows-gnu.exe: Permission denied
collect2.exe: error: ld returned 1 exit status
```

It doesn't seem to happen in the same place at every time, but basically an exe (usually stdtest) can't be opened for whatever reason.

cc @retep998 @klutzy

**Comment by klutzy** [comment]
I've thought it's basically [this](https://github.com/rust-lang/rust/issues/19120#issuecomment-68997957): for some reason stdtest hanged at previous test, then during the second build linker fails to open exe since it's still running.
(The comment only said run-pass tests but while investigating it I also found one some `***test` hanged.)

**Comment by klutzy** [comment]
Ping @alexcrichton: Could you dump thread/stack status of hanged process using [Process Explorer](https://technet.microsoft.com/ko-kr/sysinternals/bb896653.aspx)? [This article](http://windowsexplored.com/2011/04/28/know-the-stack-or-more-hang-analysis-using-process-explorer/) explains how to see list of threads and stack trace of each thread.

**Comment by Manishearth** [comment]
Some various failures this caused (most of these today!):

 - http://buildbot.rust-lang.org/builders/auto-win-32-nopt-t/builds/3387
 - http://buildbot.rust-lang.org/builders/auto-win-32-nopt-t/builds/3388
 - http://buildbot.rust-lang.org/builders/auto-win-64-opt/builds/2230
 - http://buildbot.rust-lang.org/builders/auto-win-64-nopt-t/builds/2222
 - http://buildbot.rust-lang.org/builders/auto-win-64-nopt-t/builds/2223
 - http://buildbot.rust-lang.org/builders/auto-win-64-nopt-t/builds/2224
 - http://buildbot.rust-lang.org/builders/auto-win-64-nopt-t/builds/2228
 - http://buildbot.rust-lang.org/builders/auto-win-64-nopt-t/builds/2229

This "intermittent" is really becoming a problem, can we prioritize this?

**Comment by Manishearth** [comment]
Seems like 99b39cc98ea03994f376b8389e4366b688334e65 should have fixed it, but it didn't.

**Comment by brson** [comment]
@Manishearth suspects https://github.com/rust-lang/rust/commit/d0de2b46e9bcca93971ef64d6ecdef872633f246 may caused the recent spike.

**Comment by brson** [comment]
I added a patch to buildbot that attempts to kill everything named stdtest before running `make check`, and changed the max builds per windows slave to 1 https://github.com/rust-lang/rust-buildbot/commit/9911005f4df1695a6f09142c02eced4ecf04a218

**Comment by brson** [comment]
This is how mariadb creates buildbot jobs https://mariadb.com/kb/en/mariadb/buildbot-setup-buildbot-setup-for-windows/

**Comment by alexcrichton** [comment]
@klutzy is [correct in the diagnosis](https://github.com/rust-lang/rust/issues/22628#issuecomment-75372764). The fact that `stdtest` hangs is pretty new to me and I haven't had the chance to investigate it much.

Note that the fix for all the tests in @klutzy's linked comment was to `join` on all threads. I had a patch to use `scoped` but it should have instead been `spawn` + `join`. @Manishearth I see a few linked commits to this issue which add calls to `sleep`, but I believe it is better solved with a `join`.

> Could you dump thread/stack status of hanged process (when this occurs again) using [Process Explorer](https://technet.microsoft.com/ko-kr/sysinternals/bb896653.aspx)? [This article](http://windowsexplored.com/2011/04/28/know-the-stack-or-more-hang-analysis-using-process-explorer/) explains how to see list of threads and stack trace of each thread.

I took a peek, and unfortunately all I could deduce was that a thread was blocked in `accept`. I was unable to get any indication of *which* `accept` it was blocked in (no symbols were available).

> and changed the max builds per windows slave to 1 https://github.com/rust-lang/rust-buildbot/commit/9911005f4df1695a6f09142c02eced4ecf04a218

@brson, why change the max builds? I'm under the impression that the error does not come from this but rather the fact that something just hangs for too long. Killing `stdtest` at the start sounds like a good idea though. Note that this was my impetus for opening #22448.

**Comment by Manishearth** [comment]
@alexcrichton We can't `join()` when the child has panicked. That's why I added a `sleep()`

**Comment by Manishearth** [comment]
@alexcrichton Max builds has to be one, we're indiscriminately killing all `stdtest` processes without knowing which build they came from. Peter is working on a job object based solution so that we don't have to do that.

**Comment by alexcrichton** [comment]
> @alexcrichton We can't `join()` when the child has panicked. That's why I added a `sleep()`

It depends how you spawned the thread. If the thread was spawned with `scoped` then it will propagate the panic but if spawned with `spawn` you will catch the panic with a `Result`.

> Max builds has to be one, we're indiscriminately killing all `stdtest` processes without knowing which build they came from

Hm ok.

**Comment by retep998** [comment]
I have created a simple Rust wrapper application that uses job objects to ensure all existing processes are completely dead.
https://github.com/retep998/dojob-rs/blob/master/src/main.rs

**Comment by Manishearth** [comment]
http://buildbot.rust-lang.org/builders/auto-win-32-nopt-t/builds/3431

```
note: C:/program files (x86)/mingw-w64/i686-4.9.1-win32-dwarf-rt_v3-rev1/mingw32/bin/../lib/gcc/i686-w64-mingw32/4.9.1/../../../../i686-w64-mingw32/bin/ld.exe: cannot open output file i686-pc-windows-gnu\test\run-pass\unwind-resource.stage2-i686-pc-windows-gnu.exe: Permission denied
```

So the diagnosis by @klutzy / @alexcrichton  is correct; this test sometimes hangs and stays alive for the next build. (Though stdtest might be a separate problem)

We need to integrate dojob somehow ... @brson ?

**Comment by alexcrichton** [comment]
@Manishearth no the fix for that problem specifically is https://github.com/rust-lang/rust/pull/22723

**Comment by Manishearth** [comment]
Yeah, I'm talking about both failures here (stdtest, and the unsafe one).

**Comment by Manishearth** [comment]
http://buildbot.rust-lang.org/builders/auto-linux-32-nopt-t/builds/3773

```
rm: cannot remove ‘i686-pc-windows-gnu/stage0/bin/rustlib/i686-pc-windows-gnu/lib/syntax-4e7c5e5c.0.o’: Device or resource busy
```

**Comment by brson** [comment]
@alexcrichton max_builds=1 because the script indiscrimanently kills anything called stdtest.

@retep998 wants me to wrap the make calls with [dojob.rs](https://github.com/retep998/dojob-rs), which should make buildbot kill the whole process tree. Seems like a good idea. I hope that would let us remove the taskkill hack.

**Comment by retep998** [comment]
Has anyone seen this issue lately since `dojob` was implemented?

**Comment by alexcrichton** [comment]
I have not, thanks @retep998!
