### ISSUE TITLE
Rust book doesn't use deref coercions

### ISSUE THREAD

**Issue by posixphreak** [rust-lang/rust#22637]
I think deref coercions make life easier and they should be documented on the book. Currently, it seems like [more-strings.md](https://github.com/rust-lang/rust/blob/2b01a37ec38db9301239f0c0abcf3c695055b0ff/src/doc/trpl/more-strings.md), [pointers.md](https://github.com/rust-lang/rust/blob/2b01a37ec38db9301239f0c0abcf3c695055b0ff/src/doc/trpl/pointers.md) and [unsafe.md](https://github.com/rust-lang/rust/blob/2b01a37ec38db9301239f0c0abcf3c695055b0ff/src/doc/trpl/unsafe.md) could use this feature. Although I'm not sure where that should be told, maybe pointers.md?

Unrelated, old guides like [guide-crates.md](https://github.com/rust-lang/rust/blob/2b01a37ec38db9301239f0c0abcf3c695055b0ff/src/doc/guide-crates.md) link to a nonexisting directory (src/doc/book) when they should actually point to src/doc/trpl

**Comment by steveklabnik** [comment]
Thanks @posixphreak ! In the future, feel free to make two issues for two unrelated things, so we can fix them in two patches if we need to.

**Comment by steveklabnik** [comment]
> old guides like guide-crates.md link to a nonexisting directory (src/doc/book) when they should actually point to src/doc/trpl

This is not actually a bug, as they're for the generated output, not the in-tree source.
