### ISSUE TITLE
ParseIntError and ParseFloatError does not allow to introspect the cause

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#22639]
The only way to introspect reason of `.parse` failure is to compare to error messages returned by description or use the following code snippet:

``` rust
let overflow = "1231123123123123".parse::<u32>().err().unwrap();
let underflow = "-1231123123123123".parse::<i32>().err().unwrap();
match "999999999999".parse::<u32>() {
    Ok(n) => println!("{}", n),
    Err(ref e) if *e == overflow => println!("Overflow"),
    Err(ref e) if *e == underflow => println!("Underflow"),
    _ => panic!("wow, no introspection, very convenience")
}
```

**Comment by alexcrichton** [comment]
Note that this was purposefully done to avoid adding extra `#[stable]` surface for now. It should be able to expose this information through an `enum` in the future, for example.

**Comment by steveklabnik** [comment]
Triage: no change here.

@rust-lang/libs is the intention still to change this to an enum of some kind in the future?

**Comment by Seeker14491** [comment]
Any reason to postpone this further?

**Comment by BurntSushi** [comment]
@Seeker14491 I don't think it's postponed. I think someone just needs to propose an API?

**Comment by phungleson** [comment]
Hey, we already have an enum `IntErrorKind`, just want to check if anything still need to be done to make it `pub`

https://github.com/rust-lang/rust/blob/fc02736d59252fe408dd6c2f7e2c4b6f229e4443/src/libcore/num/mod.rs#L2769-L2774

**Comment by gypsydave5** [comment]
I just brushed up against this issue while demoing the guessing game example from the Rust Book - seemed like an easy thing to show off matching on the error kind, but turned out not so much!

**Comment by frontsideair** [comment]
I also wanted to match `IntErrorKind::Empty` in the number game to abort on EOF, turned out to be impossible.

**Comment by sfackler** [comment]
@frontsideair you can just check if the string's empty before parsing, right?

**Comment by frontsideair** [comment]
I guess, but it was a fun exercise in pattern matching.

**Comment by dtolnay** [comment]
I see that checking for empty has come up in the context of the guessing game tutorial. Could somebody make a list of use cases from real code that needs to be able to distinguish between the following other ParseIntError cases?

- invalid digit
- number too large to fit in target type
- number too small to fit in target type

In the event that empty is the only one we ever need to introspect for, I would prefer to close this and instead recommend to check `== ""` before parsing.

**Comment by ranma42** [comment]
It can be convenient to distinguish too large/too small numbers when accepting configuration parameters that the code will later sanitize by clamping to a valid range. Specifically, they make it possible to perform saturation of the parsed value before it is passed on.

Example: the valid range of offsets is -10..+10, therefore the application stores it in an `i8`. When the value it outside of the -10..+10 range the app would like to warn the user and proceed with the nearest legitimate value.

Without the ability to discriminate if the number is too big/small, it is not possible to determine what is the nearest legitimate value.

**Comment by dtolnay** [comment]
@ranma42 do you think that use case would be solved by https://github.com/rust-lang/rfcs/issues/928?

```rust
use std::num::Saturating;

fn main() {
    let s = "-999";
    let n = match s.parse::<Saturating<i8>>()?.0 {
        std::i8::MIN ... -11 => { println!("saturating"); -10 }
        11 ... std::i8::MAX => { println!("saturating"); 10 }
        n => { println!("in range"); n }
    };
    println!("n={}", n);
}
```

**Comment by ranma42** [comment]
Yes, that use case would be covered if Rust had the ability to parse a `Saturating<i8>` (and in a convenient way, too!)

**Comment by amosbatto** [comment]
The only way I found around this problem was to do something ugly like this:
```
match my_str.parse::<i32>() {
	Ok(x) => {my_int = x;},
	Err(e) => {
		if e.to_string() == "invalid digit found in string" {
			println!("Only positive integers are allowed! \nEx: cgd 33784 346");
		}
		else if e.to_string() == "number too large to fit in target type" {
			println!("Number is too large! \nEx: cgd 33784 346");
		}
		else if e.to_string() == "number too small to fit in target type" {
			println!("Number is too small! \nEx: cgd 33784 346");
		}
		else if e.to_string() == "cannot parse integer from empty string" {
			println!("Number is empty! \nEx: cgd 33784 346");
		}
	}
}
```
What is so annoying is that `println!("{:?}", e)` shows me `ParseIntError { kind: InvalidDigit }`, but `kind` is private so I can't access it. Either `kind` should be made private or a `kind()` function should be implemented to access to.

**Comment by Clockwork-Muse** [comment]
I'm doing custom type parsing (something like this: `X+123789Y-3453`), and I'd actually like to **map** the errors into my own custom error type.  Yes, I could implement my own integer parsing, but that would defeat the purpose of _having_ a built-in integer parser.

My map would be something like this:
 - `Empty` -> `MyInvalid` (because the whole thing isn't empty, just one of the number portions)
 - `Underflow`/`Overflow` -> `MyUnderflow`/`MyOverflow` (although I'd be fine with just overflow, a la `checked_`)
 - `Invalid` -> `MyInvalid` 

....except I can't do that at the moment without resorting to @amosbatto 's trick.  It also makes testing very difficult, because I can't tell **what** error I got back (except by checking the string).

**Comment by ethanboxx** [comment]
Hello everyone. My [PR](https://github.com/rust-lang/rust/pull/55705) fixes this issue and has been merged.

Use the feature flag `#![feature(int_error_matching)]` in nightly to try it out.

**Comment by tspiteri** [comment]
If this is to be stabilized, I think that the terminology has to be improved: `IntErrorKind` uses `Underflow` to refer to negative overflow, but underflow usually means when the absolute value of a floating-point number is so small it becomes 0 (or a subnormal).

**Comment by JarrettBillingsley** [comment]
Maybe `NegOverflow`?

**Comment by getreu** [comment]
This will also solve my use case described in #39381.

**Comment by hellow554** [comment]
Can't we put a `#[non_exhaustive]` on it and make it stable? :)

**Comment by jyn514** [comment]
I would find this useful for `NonZeroUsize::from_str()` to distinguish between "0" and an invalid number.

**Comment by raleighlittles** [comment]
Stumbled upon this issue while working on [this Rustlings exercise](https://github.com/rust-lang/rustlings/blob/master/exercises/error_handling/errors2.rs), as the help text is extremely unuseful. 

Trying to compile something like this snippet:

```rust
use std::num::ParseIntError;

pub fn total_cost(item_quantity: &str) -> Result<i32, ParseIntError> {

   ...

    match qty {
        Ok(qty) => return Ok(qty * cost_per_item + processing_fee),
        Err(error) => return Err(ParseIntError{kind : InvalidDigit})
    }
}
```

Throws an error on the second arm of the match, and provides this help text:

> help: consider importing this unit variant

But then, after adding the import for that variant (`std::num::IntErrorKind::InvalidDigit`), I'm greeted with another error:

_use of unstable library feature 'int_error_matching': it can be useful to match errors when making error messages for integer parsing
  --> exercises/error_handling/errors2.rs:23:5_

Seems kind of odd that users are steered towards using features that are only available on nightly?

**Comment by Lucretiel** [comment]
Before stabilizing, would it be very complicated to additionally add the byte index where parsing failed? I can imagine that information being useful to an introspector (for example, to print a verbose rust-like arrow pointing to the exact location of the parse failure).

**Comment by ethanboxx** [comment]
> Before stabilizing, would it be very complicated to additionally add the byte index where parsing failed? I can imagine that information being useful to an introspector (for example, to print a verbose rust-like arrow pointing to the exact location of the parse failure).

Should be easy to do. I will probably open a PR with that soon so people discuss it.

**Comment by kennytm** [comment]
It has been over half a year since https://github.com/rust-lang/rust/pull/77640#pullrequestreview-511263516, and the indexing question is rejected in https://github.com/rust-lang/rust/pull/79728#pullrequestreview-633030341, so I guess we can submit another stabilization attempt? 😉

**Comment by Sol-Ell** [comment]
It seems `int_error_matching` has been stabilized, but what about float error matching? Maybe there are reasons for not to stabilize it?

**Comment by eopb** [comment]
There's currently no `float_error_matching` feature but I don't think there's anything blocking someone from making one. Someone would need to propose an API and leave it as an unstable feature for some time before stabilizing

**Comment by tisonkun** [comment]
> There's currently no `float_error_matching` feature but I don't think there's anything blocking someone from making one. Someone would need to propose an API and leave it as an unstable feature for some time before stabilizing

https://github.com/rust-lang/libs-team/issues/683

Here is an ACP and I'm glad to drive it forward.
