### ISSUE TITLE
Move "Tools" section down in the 30 minute intro

### ISSUE THREAD

**Issue by jxcl** [rust-lang/rust#22636]
If I understand correctly, the 30 minute intro is supposed to be an overview of the main features of Rust, and not a "getting started" guide. It seems to me that currently the 30 minute intro tries to be both, and TRPL is already a good "getting started" guide, so the 30 minute intro should focus on being the overview.

To this end, the 30 minute intro should open with what is most unique about Rust, namely its ownership system. Many programming languages have tooling similar to Rust's Cargo, and putting Cargo at the top of the guide hides the most unique features below the fold. In my opinion, the tooling is the thing that is least impressive about Rust, and should be at the bottom of the page.

Currently the Tools section is at the top of the page, probably because if the user wanted to follow along with the 30 minute intro, that is where they would start. I believe the assumption that a user would want to follow along from the beginning to be flawed, however. The 30 minute intro should operate under the assumption that the user has not downloaded Rust and its goal should be to convince the user to do so. Once we have convinced the user, we can point him to TRPL for a "follow along" introduction.

**Comment by kmcallister** [comment]
> Many programming languages have tooling similar to Rust's Cargo

True, but C and C++ do not.  Many people with a traditional systems background come in with the expectation that using an external library is an arduous ordeal to be attempted only when absolutely necessary.  Some of Rust's decisions look terrible from that perspective.

I mostly agree with you though.  Maybe we should cut the text down to one or two sentences.

**Comment by jxcl** [comment]
>Many people with a traditional systems background come in with the expectation that using an external library is an arduous ordeal to be avoided whenever possible.

Ah, OK.

>Maybe we should cut the section about Cargo down to one or two sentences.

I think that cutting down to one or two sentences may be overkill. Cargo is still nice, and it's still a selling point of Rust, I just think it doesn't deserve its place at the top of the intro.

**Comment by kmcallister** [comment]
Definitely. What I really meant is that we could have a few sentences at the beginning, and then a longer section later on.  Or just link to the TRPL chapter.

**Comment by jxcl** [comment]
Alright. I'm willing to make the PR on this, by the way. I'm just waiting for the go-ahead.

**Comment by kmcallister** [comment]
Awesome.  It sounds like a good change to me.  You could wait for @steveklabnik to weigh in, but it's also totally fine to submit a PR right now.  It's easier to discuss the change if we can see it in front of us, anyway.

**Comment by steveklabnik** [comment]
Thank you for the suggestion, but I'm not interested in changing this at this time. I'm on mobile, I will write more later.

**Comment by steveklabnik** [comment]
Whew! Sorry for taking a while.

Okay, so basically, there's two things at play here:

1. all of this ordering is something that's inherently subjective. And I tend to prefer it this way, for reasons. That doesn't mean that it can't be made better, and I'd discuss them at length, except for
2. I'm currently working on a redux of our introductory docs, and this whole intro might just go away, replaced by the first section of the book. And so I don't want to take up time churning and figuring stuff out with this, when it might be irrelevant soon.

If 2 doesn't come to pass, we can discuss it further. Make sense?

**Comment by kmcallister** [comment]
Sounds good to me.
