### ISSUE TITLE
std::fmt module documentation error

### ISSUE THREAD

**Issue by leonardinius** [rust-lang/rust#22646]
See http://doc.rust-lang.org/std/fmt/index.html

e.g. http://doc.rust-lang.org/src/collections/fmt.rs.html#365-369
> '0' - This is used to indicate for integer formats that the padding should both be done with a 0 character as well as be sign-aware. A format like {:08d} would yield 00000001 for the integer 1, while the same format would yield -0000001 for the integer -1. Notice that the negative version has one fewer zero than the positive version.

It seems what instead of `{:08d}`, `{:08}` is required.

E.g. (http://is.gd/oL48zO)
```rust
fn main() {
    println!("{:08d}", 10i32); 
}
```
produces 
```
<anon>:2:24: 2:29 error: unknown format trait `d`
<anon>:2     println!("{:08d}", 10i32); 
                                ^~~~~
```

**Comment by leonardinius** [comment]
I tried to search already reported issue, no luck. 
If it's something really worthy, I might try to come up with PR to fix it.

**Comment by leonardinius** [comment]
So, does it qualify for a proper PR? 

I'm new in Rust ecosystem and I thought it could be a good way to both contribute back and start smart, e.g. understand how the whole process works ... ;)

**Comment by steveklabnik** [comment]
yes, absolutely! If you have the time, that'd be great.

**Comment by steveklabnik** [comment]
You can check out https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md for full details, but basically, just make a pull request :)

**Comment by leonardinius** [comment]
Great, will do it some time during this week.

**Comment by leonardinius** [comment]
#22925 fixed the issue 

http://doc.rust-lang.org/std/fmt/#sign/#/0 seems to be updated, closing this one.
