### ISSUE TITLE
Support ARMv7 / ARMHF in rustup.sh script

### ISSUE THREAD

**Issue by carstenhag** [rust-lang/rust#22668]
Getting an unknown CPU type error while executing the script.

```
shell@c1-10-1-4-39:~$ curl -s https://static.rust-lang.org/rustup.sh | sudo sh
rustup: CFG_CURL             := /usr/bin/curl (7.35.0)
rustup: CFG_TAR              := /bin/tar (1.27.1)
rustup: CFG_FILE             := /usr/bin/file (5.14)
rustup: CFG_SHA256SUM        := /usr/bin/sha256sum (256sum)
rustup: CFG_SHASUM           := /usr/bin/shasum (5.84)
rustup: 
rustup: processing sh args
rustup: 
rustup: CFG_PREFIX           :=  
rustup: CFG_DATE             :=  
rustup: 
rustup: validating sh args
rustup: 
rustup: error: unknown CPU type: armv7l
```

```
shell@c1-10-1-4-39:~$ uname -a
Linux c1-10-1-4-39 3.17.0-119 #1 SMP Thu Nov 20 14:15:44 CET 2014 armv7l armv7l armv7l GNU/Linux
```

**Comment by japaric** [comment]
`arm-unknown-linux-gnueabi[hf]` is not an officially supported target, and there are no official nightlies for it, so `rustup.sh` simply won't work for that target.

For the time being, you can manually install [my unofficial nightlies](https://github.com/japaric/ruststrap).

We intend to provide these unofficial nightlies via `rustup` in the future, but [the details are still being worked on](http://internals.rust-lang.org/t/community-supported-build-slaves-for-2nd-tier-platforms/1528).

**Comment by Moter8** [comment]
Thanks, mainly just wanted to have this tracked somewhere!

**Comment by geraldstanje** [comment]
hi, do you support Linux 3.9.0-xilinx #1 SMP PREEMPT armv7l GNU/Linux ?

**Comment by fhahn** [comment]
I think this issue can be closed, as rustup.rs supports ARMv7 / ARMHF. I just tested it on my Raspberry Pi by installing `stable-armv7-unknown-linux-gnueabihf`.

**Comment by sanxiyn** [comment]
Fixed by rustup.rs.
