### ISSUE TITLE
rustc unexpectedly panics with (invalid) regex "(+)"

### ISSUE THREAD

**Issue by juliusikkala** [rust-lang/rust#22679]
When trying to compile `regex!(r"(+)")`, the compiler panics.

This is the code that leads to the crash:

    #![feature(plugin)]
    #![plugin(regex_macros)]
    extern crate regex;

    fn main() {
        let re = regex!(r"(+)");
    }
Valid regexes have not caused any problems.
rustc output:

    error: internal compiler error: unexpected panic
    note: the compiler unexpectedly panicked. this is a bug.
    note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
    note: run with `RUST_BACKTRACE=1` for a backtrace
    thread 'rustc' panicked at 'Tried to unwrap non-AST item: Paren(0, 1, "")', /home/julius/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.1.15/src/parse.rs:163

    Could not compile `bug`.

## Meta

`rustc --version --verbose`:

    rustc 1.0.0-nightly (522d09dfe 2015-02-19) (built 2015-02-21)
    binary: rustc
    commit-hash: 522d09dfecbeca1595f25ac58c6d0178bbd21d7d
    commit-date: 2015-02-19
    build-date: 2015-02-21
    host: x86_64-unknown-linux-gnu
    release: 1.0.0-nightly

I am using Arch Linux and rustc is installed from AUR (it downloads the binaries from 
https://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz).
Backtrace:

       1:     0x7f6461e7d210 - sys::backtrace::write::h252031bd050bf19aKlC
       2:     0x7f6461ea5ac0 - panicking::on_panic::h8a07e978260e2c7btXL
       3:     0x7f6461de6720 - rt::unwind::begin_unwind_inner::h322bcb3f35268c19RBL
       4:     0x7f6461de71f0 - rt::unwind::begin_unwind_fmt::h9448a61362cc80d2nAL
       5:     0x7f6458228fd0 - parse::BuildAst::unwrap::hb5d44cbdb15d2c10v0a
       6:     0x7f64582370e0 - parse::Parser::pop_ast::h76189779d315f940ifb
       7:     0x7f645822f010 - parse::Parser::push_repeater::h9b348b199426ad950fb
       8:     0x7f64582294e0 - parse::Parser::parse::hc4adcc34190b3a5bk3a
       9:     0x7f64582292f0 - parse::parse::hbb40bb6fc331e453H2a
      10:     0x7f6458249370 - re::Regex::new::h8c68b01aada2952bwuc
      11:     0x7f64581b8e20 - native::hf8caf7fb4b19410c2aa
      12:     0x7f64600e5dc0 - ext::base::F.TTMacroExpander::expand::h867963691209911018
      13:     0x7f645f25caa0 - ext::expand::expand_expr::closure.58776
      14:     0x7f645f25c9b0 - ext::expand::expand_expr::h4383deb4367119b5wBd
      15:     0x7f645f210eb0 - ext::expand::MacroExpander<'a, 'b>.Folder::fold_expr::h000c01cd1b3edba9zRe
      16:     0x7f645f267ff0 - fold::noop_fold_expr::closure.58825
      17:     0x7f645f2847e0 - ext::expand::expand_non_macro_stmt::closure.59045
      18:     0x7f645f2841f0 - ext::expand::expand_non_macro_stmt::closure.59043
      19:     0x7f645f283eb0 - ext::expand::expand_non_macro_stmt::h51b42cda1f47cb38sge
      20:     0x7f645f2e2920 - ext::expand::MacroExpander<'a, 'b>.Folder::fold_stmt::closure.59789
      21:     0x7f645f2b0ba0 - ext::expand::expand_block_elts::closure.59361
      22:     0x7f645f2b0820 - iter::FlatMap<I, U, F>.Iterator::next::h12199045387838857590
      23:     0x7f645f2af6b0 - vec::Vec<T>.FromIterator<T>::from_iter::h209756562474197865
      24:     0x7f645f2aee50 - ext::expand::expand_block_elts::closure.59351
      25:     0x7f645f268e20 - ext::expand::expand_block_elts::hbc921c8f419d91ab9oe
      26:     0x7f645f2aec20 - ext::expand::expand_block::h98dad051e0f0e47fpoe
      27:     0x7f645f268070 - ext::expand::MacroExpander<'a, 'b>.Folder::fold_block::hba037cd9748a0507UTe
      28:     0x7f645f268500 - ext::expand::expand_and_rename_fn_decl_and_block::h58ecb6b0c982387fnPe
      29:     0x7f645f273830 - ext::expand::expand_item_underscore::hbfa576cbe10231f502d
      30:     0x7f645f2d9620 - fold::Folder::fold_item_simple::h16347799820789526401
      31:     0x7f645f2d8ca0 - ptr::P<T>::map::h5488296407772723657
      32:     0x7f645f26bd10 - ext::expand::expand_annotatable::h81cc6e36fef572560ze
      33:     0x7f645f268fe0 - ext::expand::expand_item::h2cff22418fb19f38aZd
      34:     0x7f645f278740 - ext::expand::MacroExpander<'a, 'b>.Folder::fold_item::h8c866cfe343d78bcdSe
      35:     0x7f645f278680 - fold::noop_fold_mod::closure.58931
      36:     0x7f645f278370 - iter::FlatMap<I, U, F>.Iterator::next::h7192467770078366644
      37:     0x7f645f277d00 - vec::Vec<T>.FromIterator<T>::from_iter::h1450071030007651331
      38:     0x7f645f277b60 - fold::noop_fold_mod::h17464563872470565435
      39:     0x7f645f273830 - ext::expand::expand_item_underscore::hbfa576cbe10231f502d
      40:     0x7f645f2d9620 - fold::Folder::fold_item_simple::h16347799820789526401
      41:     0x7f645f2d8ca0 - ptr::P<T>::map::h5488296407772723657
      42:     0x7f645f26bd10 - ext::expand::expand_annotatable::h81cc6e36fef572560ze
      43:     0x7f645f268fe0 - ext::expand::expand_item::h2cff22418fb19f38aZd
      44:     0x7f645f278740 - ext::expand::MacroExpander<'a, 'b>.Folder::fold_item::h8c866cfe343d78bcdSe
      45:     0x7f645f2e4b20 - ext::expand::expand_crate::h3aa1e0ab5c8c5f8bIYe
      46:     0x7f6462535dd0 - driver::phase_2_configure_and_expand::closure.20378
      47:     0x7f64624e9c90 - driver::phase_2_configure_and_expand::hf01f6e95dfef33e33ta
      48:     0x7f64624de070 - driver::compile_input::h0c8d8120f6194473Gba
      49:     0x7f64625ad2b0 - run_compiler::heccd2f43b844857cZbc
      50:     0x7f64625abbb0 - thunk::F.Invoke<A, R>::invoke::h14556331494175157254
      51:     0x7f64625aaaa0 - rt::unwind::try::try_fn::h8181016918202193540
      52:     0x7f6461f12880 - rust_try_inner
      53:     0x7f6461f12870 - rust_try
      54:     0x7f64625aada0 - thunk::F.Invoke<A, R>::invoke::h12418455792421810631
      55:     0x7f6461e91b60 - sys::thread::thread_start::h3defdaea150d8cd693G
      56:     0x7f645bd932b0 - start_thread
      57:     0x7f6461a6f249 - __clone
      58:                0x0 - <unknown>

**Comment by goffrie** [comment]
This is a panic in the `regex_macros` plugin, not a `rustc` bug, so this bug report belongs there. However, panicking in a plugin shouldn't cause us to emit the "bug in rustc" message..

**Comment by jakub-** [comment]
I moved the issue to https://github.com/rust-lang/regex/issues/74.

@goffrie The message wording problem you described is tracked by https://github.com/rust-lang/rust/issues/15509.

Closing.
