### ISSUE TITLE
`-O -C lto` is *not* same to `-C opt-level=2 -C lto`

### ISSUE THREAD

**Issue by lifthrasiir** [rust-lang/rust#22677]
Fallout of #21191. `-C opt-level=2` sets `CodegenOptions::opt_level` but `-O` doesn't, and `-C lto` path only looks at that. Due to the fallback from LTO path, `-O -C lto` is currently same to `-C opt-level=0 -C lto` (!).

**Comment by dotdash** [comment]
Thanks for the bug report, this will be fixed by #22530

**Comment by lifthrasiir** [comment]
Ah indeed. This was a dup of #22525. Closing.
