### ISSUE TITLE
Vec docs missing 'iter'

### ISSUE THREAD

**Issue by tfogal** [rust-lang/rust#22676]
http://doc.rust-lang.org/std/vec/struct.Vec.html is missing documentation on 'iter()'.

Maybe this is in a trait that vector implements? Either way, it should still appear in this doc (or at least be linked to in this doc), as that's the logical first place someone will look.

**Comment by steveklabnik** [comment]
Vec implements Deref, and Slice, which it derefs to, implements Iter.

We already have a bug open for "Deref is confusing in the docs," so I'm going to close this one, but thank you for reporting!
