### ISSUE TITLE
The bencher should have a tool-friendly output format

### ISSUE THREAD

**Issue by mzabaluev** [rust-lang/rust#22683]
The logfiles produced by bench runs have a format that is not very friendly to simple tools like join: the type of test/result and the test path do not have stable positions if the lines are broken up into space-separated fields.

It would be nice if the test driver could produce tool-friendly output where each test produces a line of regular space-separated fields with optional freeform information:

_type_ _path_ _result_ _freeform_

Here, _type_ can be `test`, `bench`, or `ignored`. _path_ is the crate path of the test function. _result_ is a single token depending on the type (time/iter for benchmarks, `ok`|`failed`|etc. for tests, not present for ignored tests).

**Comment by steveklabnik** [comment]
We recently removed the JSON output of the benching tool, actually. And it's not to say that it's not a thing that's useful, but in an effort to stabilize, we're only committing to the minimum.

We're tracking feature requests for things like this over in the RFCs repo now, so I'm going to move it over there. Thanks!

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#895
