### ISSUE TITLE
error: no associated type `Output` defined in `core::marker::PhantomFn<()>`

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/rust#22686]
Following [the RFC](https://github.com/rust-lang/rfcs/blob/master/text/0738-variance.md):

> These traits should appear in the supertrait list. For example, the Dummy trait might be modified as follows:
```
trait Dummy<T> : PhantomFn() -> T { }
```
> As you can see, the () notation can be used with PhantomFn as well.

I wrote this code:

```rust
use std::marker::PhantomFn;
trait Dummy<T> : PhantomFn() -> T { }
fn main() {}
```

Which complains: 

> error: parenthetical notation is only stable when used with the `Fn` family of traits

So we add `#![feature(unboxed_closures)]`:

```rust
#![feature(unboxed_closures)]
use std::marker::PhantomFn;
trait Dummy<T> : PhantomFn() -> T { }
fn main() {}
```

> error: no associated type `Output` defined in `core::marker::PhantomFn<()>`

It's unclear what the next steps might be. Tested on `rustc 1.0.0-dev (2b01a37ec 2015-02-21) (built 2015-02-21)`

**Comment by Centril** [comment]
Similar also tested on: `rustc 1.0.0-nightly (522d09dfe 2015-02-19) (built 2015-02-21)`.

**Comment by edwardw** [comment]
It's supposed to be:

```rust
use std::marker::PhantomFn;
trait Dummy<T> : PhantomFn<Self, T> { }
fn main() {}
```

In this regard, rustdoc [PhantomFn](http://doc.rust-lang.org/std/marker/trait.PhantomFn.html) is more accurate.

**Comment by edwardw** [comment]
Hmm, it's supposed to be:

```rust
use std::marker::PhantomFn;
trait Dummy<T> : PhantomFn<Self, T> { }
fn main() {}
```

In this regard, rustdoc [PhantomFn](http://doc.rust-lang.org/std/marker/trait.PhantomFn.html) is more accurate.

**Comment by apasel422** [comment]
`PhantomFn` no longer exists. This issue can be closed.
