### ISSUE TITLE
macro_rules item fragment inside impl does not work

### ISSUE THREAD

**Issue by TimNN** [rust-lang/rust#22694]
Trying to use an item fragment inside of an impl doesn't work. Both `as_item!` invocations in `impl A` fail to compile with different error messages ([playpen](http://is.gd/KeZNjU)):

``` rust
macro_rules! as_item {
    ($i:item) => {$i}
}

macro_rules! without_item {
    ($name:ident) => {fn $name() {}}
}

macro_rules! without_item_self {
    ($name:ident) => {fn $name(self) {}}
}

as_item!{fn this_works() {}}
without_item!{this_also_works}

struct A;

impl A {
    as_item!{fn this_does_not() {}}
    as_item!{fn this_neither(self) {}}
    without_item!{this_works}
    without_item_self!{this_also_works}
}
```

Note that the macro invocation outside of the impl block works without problems and that everything works fine if the source of the generated ast is not an item fragment.

**Comment by steveklabnik** [comment]
Triage: no change, today.

**Comment by Mark-Simulacrum** [comment]
This now works, closing.

**Comment by TimNN** [comment]
@Mark-Simulacrum: Are you sure, this is still broken for me on `rustc 1.19.0-nightly (2d4ed8e0c 2017-05-03)`.

(Did you uncomment the two commented lines which cause the problem?)

**Comment by Mark-Simulacrum** [comment]
...No. This is what comes of trying to triage issues while nearly asleep.

**Comment by MSleepyPanda** [comment]
I've hit this today. Is there progress on this?

**Comment by durka** [comment]
cc @jseyfried

**Comment by cjgillot** [comment]
This now works.
