### ISSUE TITLE
libunicode regex consts should have the same form if possible

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#22699]
In [regex](http://doc.rust-lang.org/unicode/regex/index.html), the consts have these types:
```rust
pub static PERLD: &'static &'static [(char, char)] = ...
pub static PERLS: &'static &'static [(char, char)] = ...
pub static PERLW: &'static [(char, char)] = ...
```

They should probably be the same type but aren't for some reason. They cause this https://github.com/rust-lang/rfcs/issues/730 issue.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/regex#42

**Comment by steveklabnik** [comment]
Ugh, sorry, this is an issue with the regexes _in libunicode_, not regex in general.

**Comment by mdinger** [comment]
PERLD and it's friends seem to be gone which fixes this. What crate did they move into?
