### ISSUE TITLE
End-of-line backslash in string literal should be documented

### ISSUE THREAD

**Issue by MicahChalmer** [rust-lang/rust#22698]
Rust has a feature in non-raw string literals where a backslash right before a newline causes that newline, plus all whitespace at the beginning of the next line, to be ignored.  That makes it so that you can indent the insides of string literals without the indentation being part of the program.  For instance:

```rust
fn main() {
    println!("foo\
              bar");
}
```
prints `foobar`.

That's is a nice feature, but it appears nowhere (at least nowhere obvious that I can find from a brief search) in either in the book or the reference.

**Comment by mund** [comment]
I also added this to the Hello World Tutorial, was that a bad thing?
