### ISSUE TITLE
Standalone binaries for distribution

### ISSUE THREAD

**Issue by jamm** [rust-lang/rust#22695]
After reading comments to recent topics on HN, both are about new tools, written in Rust https://news.ycombinator.com/item?id=9087108, https://news.ycombinator.com/item?id=9088805 , I got answer from @steveklabnik that it's impossible currently to create standalone binary from Rust programm.
It's pretty important for tools distribution, so please consider to spend some time on this issue.
By "standalone" I mean ability to just publish few binaries for most popular systems, like OS X, Linux, Win, Other (1 file per OS) and users will not have to download something else.
As an option, it could be some self-extracting installer (if it's absolutely impossible to link statically all libs onto 1 executable file).

**Comment by steveklabnik** [comment]
Thanks @jamm . We try to keep the bug tracker to 'bugs only', so I'm going to give this a close. This is something that we care about, and we do have plans to make it better.

That being said, it's not "impossible currently to create a standalone binary from a Rust program." It's that glibc cannot be statically linked. Everything else can be.

**Comment by jamm** [comment]
It's enough to know that you care about it :) Hope this issue will be useful at least for future readers with same question.
