### ISSUE TITLE
Incomplete Noncharacter_Code_Point_table

### ISSUE THREAD

**Issue by dscorbett** [rust-lang/rust#22690]
I tried this code:

```rust
extern crate regex;

use regex::Regex;

fn main() {
    let re = match Regex::new(r"\p{Noncharacter_Code_Point}") {
        Ok(re) => re,
        Err(err) => panic!("{}", err),
    };
    assert_eq!(re.is_match("\u{10ffff}"), true);
}
```

The assertion should have passed, but it failed because [`Noncharacter_Code_Point_table`](https://github.com/rust-lang/rust/blob/dcc6ce2c772cb851ac35cbc2ddafcae9bf2fa9fd/src/libunicode/tables.rs#L3935-L3942) in `tables.rs` is missing the range U+10FFFE to U+10FFFF.

This is because [`re1` and `re2`](https://github.com/rust-lang/rust/blob/dcc6ce2c772cb851ac35cbc2ddafcae9bf2fa9fd/src/etc/unicode.py#L219-L220) in `load_properties` in `unicode.py` do not handle whitespace correctly. [UAX #44](http://www.unicode.org/reports/tr44/#Data_Fields) says to ignore leading and trailing spaces within a field. That means the two regexes should be `"^ *([0-9A-F]+) *; *(\w+)"` and `"^ *([0-9A-F]+)\.\.([0-9A-F]+) *; *(\w+)"`.

## Meta

`rustc --version --verbose`:
```
rustc 1.0.0-nightly (2b01a37ec 2015-02-21) (built 2015-02-22)
binary: rustc
commit-hash: 2b01a37ec38db9301239f0c0abcf3c695055b0ff
commit-date: 2015-02-21
build-date: 2015-02-22
host: x86_64-pc-windows-gnu
release: 1.0.0-nightly
```

**Comment by SimonSapin** [comment]
Triage: this can be closed. (Fixed in https://github.com/rust-lang/regex/pull/57) cc @Manishearth
