### ISSUE TITLE
Concurrency guide contains outdated code quote

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#22708]
The (new) concurrency guide says

> If we look at the code for MutexGuard, we'll see this:
> __marker: marker::NoSend,

However, that's not correct: Even the link in there points to code saying
```{rust}
impl<'a, T> !marker::Send for MutexGuard<'a, T> {}
```

(Also, the link points to a hard-coded git commit, which may or may not be a good idea.)

**Comment by steveklabnik** [comment]
> (Also, the link points to a hard-coded git commit, which may or may not be a good idea.)

The problem is, if you don't do this, then the code can drift, and it points at the wrong place.

**Comment by RalfJung** [comment]
> The problem is, if you don't do this, then the code can drift, and it points at the wrong place.

Hm, I see. An alternative may be to link to
<http://doc.rust-lang.org/std/sync/struct.MutexGuard.html>, but then
it's not immediately the source (as one has to click on the "[src]"). I
guess there are problems either way.

**Comment by steveklabnik** [comment]
This is a dup of https://github.com/rust-lang/rust/issues/23052
