### ISSUE TITLE
The `type` keyword does not support shadowing

### ISSUE THREAD

**Issue by storedbox** [rust-lang/rust#22704]
Not sure if this is a bug, but I would like it to be one so that it changes:
```rust
// Let :)
let x = 17;
...
let x = x + 32;// Good

// Type :(
struct X<T>;
...
type X = X<String>;// Error (illegal recursive type)
```

**Comment by bombless** [comment]
But bindings have order, while type definitions don't have order, they are just defined in module, no ordering there.
Try this example for shadowing:
http://is.gd/CIneLB
```rust
mod a {
    pub fn foo() {
        println!("{}", line!())
    }
    pub mod b {
        pub fn foo() {
            println!("{}", line!())
        }
    }
}
mod test1 {
    use super::a as a;
    pub fn test() {
        a::foo()
    }
}
mod test2 {
    use super::a::b as a;
    pub fn test() {
        a::foo()
    }
}
fn main() {
    test1::test();
    test2::test()
}
```

**Comment by storedbox** [comment]
> But bindings have order, while type definitions don't have order

Whoops! Should've realized that. But, what about about within a function body? The `use` keyword within a function body will overshadow any previously defined types.

Given:
```rust
mod foo {
    pub struct Bar<T1, T2> {
        t1: T1,
        t2: T2,
    }
}

struct Bar<T> {
    t: T,
}
```

You will have:

```rust
fn main() {
    let x: Bar<u8>;
    let x: Bar<u8, u8>;// Error
}
```

```rust
fn main() {
    use foo::Bar;
    let x: Bar<u8>;// Error
    let x: Bar<u8, u8>;
}
```

```rust
fn main() {
    type Bar<T1, T2> = foo::Bar<T1, T2>;// Error
}
```

If `use` can overshadow like that, shouldn't `type` be granted the same functionality when placed at the beginning of a function?

**Comment by bombless** [comment]
As I said, shadowing is not allowed if they in the same module.
So `type` can do what you want as long as they are required in different module.
```rust
mod scope_for_i32 {
    pub type Num = i32;
}
mod scope_for_u32 {
    pub type Num = u32;
}

fn main() {
    let _ :scope_for_i32::Num = 42;
    let _ :scope_for_u32::Num = 42;
}
```
