### ISSUE TITLE
Type parameters checks are inconsistent and incomplete

### ISSUE THREAD

**Issue by flaper87** [rust-lang/rust#22706]
The way we currently check type parameters is inconsistent and error prone. The code below compiles and it shouldn't.

The `resolve` phase currently ignores these checks and leaves them up to `typeck`, `collect` and `check`, which as demonstrated by bugs like this one and #20302 makes this check unsound. 

``` rust
fn is_copy<T: ::std::marker<i32>::Copy>() {}

fn main() {}
```

**Comment by steveklabnik** [comment]
Triage: this still compiles.

**Comment by Mark-Simulacrum** [comment]
Triage: Still compiles.

**Comment by Mark-Simulacrum** [comment]
Marking as E-needstest.

```
error[E0109]: type parameters are not allowed on this type
 --> test.rs:1:29
  |
1 | fn is_copy<T: ::std::marker<i32>::Copy>() {}
  |                             ^^^ type parameter not allowed

error: aborting due to previous error(s)
```
