### ISSUE TITLE
Allow `TaskPool` to execute closures without 'static

### ISSUE THREAD

**Issue by aochagavia** [rust-lang/rust#22718]
I would really like to see something like `thread::scoped`, but for `TaskPool`. Maybe we could add an `execute_scoped` function. @reem is this feasible in the current implementation of the `TaskPool`?

If it isn't, maybe a possible alternative is the creation of a `ScopedTaskPool`, which waits for all tasks to complete upon being dropped.

Are there better alternatives?

**Comment by steveklabnik** [comment]
This is a borderline feature request, but since we're going over `'static` stuff now, I'm going to leave it open.

**Comment by aochagavia** [comment]
:)

**Comment by aochagavia** [comment]
Here is a draft that I have made: https://gist.github.com/aochagavia/550049c4825a42f5bd58

**Comment by aturon** [comment]
@aochagavia We were actually hoping to move `TaskPool` out of `std` and into its own crate on crates.io. Would you be interested in helping with that process? (cc @alexcrichton)

**Comment by aochagavia** [comment]
That would be great!

**Comment by aturon** [comment]
Great! I've made a new repo:

    https://github.com/rust-lang/taskpool

and you can follow the steps here to set it up:

    https://www.mail-archive.com/rust-dev@mozilla.org/msg10923.html

which should result in a PR against the new repo.

Please cc @alexcrichton on the PR, because I am on vacation this week and may not be able to get to it.

Thanks for taking this on!

**Comment by blaenk** [comment]
enjoy your vacation man

**Comment by reem** [comment]
I guess @alexcrichton that repo should really be called `threadpool`, since it needs to be renamed anyway.

**Comment by blaenk** [comment]
agreed with reem

**Comment by reem** [comment]
Also, anyone looking into this should check out https://github.com/carllerche/syncbox/blob/master/src/util/thread_pool.rs

**Comment by alexcrichton** [comment]
cc @steveklabnik, could you move this issue to https://github.com/rust-lang/threadpool ?

**Comment by aochagavia** [comment]
Closing as I already have opened a PR at https://github.com/rust-lang/threadpool/pull/1
