### ISSUE TITLE
Different errors when casting function to integer

### ISSUE THREAD

**Issue by blackbeam** [rust-lang/rust#22717]
I found 32 bit platform related error when accidentally forgot to call function [rust-mysql-simple#13](https://github.com/blackbeam/rust-mysql-simple/issues/13)

Not platform related case appeared on playpen:
[runtime when -O0](http://is.gd/AgHfm2)

**Comment by arielb1** [comment]
For reference:
```Rust
fn t2() -> Option<u8> {
    None
}

fn main() {
    println!("{}", 0i64 < t2 as i64);
}
```
This casts the function pointer `t2` to `i64` of course. I fixed the crash as part of my RFC401 work.
