### ISSUE TITLE
Unoptimized stdtest sometimes causes jemalloc assertion error

### ISSUE THREAD

**Issue by klutzy** [rust-lang/rust#22710]
(Using Rust rev dcc6ce2c772cb851ac35cbc2ddafcae9bf2fa9fd)

```
$ ../configure --disable-optimize

...

$ stdtest-x86_64-pc-windows-gnu.exe sync::mpsc
...
<jemalloc>: C:/home/stone/rust/src/jemalloc/include/jemalloc/internal/tsd.h:502:
Failed assertion: "tsd->state == tsd_state_reincarnated"

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

Not sure if it's related to #22628 or not. Also not sure if it only occurs with no-opt option.

**Comment by steveklabnik** [comment]
Over a year later, with no comments. @klutzy are you still seeing this?

**Comment by klutzy** [comment]
Not producible. It was a supposed bug of low-level thread/network binding and I guess it had been fixed ago.
