### ISSUE TITLE
Issue in Rust docs for Ty in libsyntax

### ISSUE THREAD

**Issue by jroesch** [rust-lang/rust#22721]
This isn't a big deal but the documentation is slightly out of date for the `TyFixedLengthVec` variant of `ast::Ty`. 

Reference: http://doc.rust-lang.org/nightly/src/syntax/ast.rs.html#1247.

The comment should read: 
```
/// A fixed length array (`[T; n]`)
```

I will fix this if I have time, otherwise it is a small tweak that someone looking to contribute could make.

cc @steveklabnik

**Comment by mund** [comment]
I've taken the liberty of fixing that comment :)

https://github.com/mund/rust/commit/d9fe33522bf12ab660803f1781a646656268e637

**Comment by steveklabnik** [comment]
@mund can you open up a pull request please?

**Comment by mund** [comment]
Yep, done! 

https://github.com/rust-lang/rust/pull/22845

Is this the right way to do it?
