### ISSUE TITLE
Pretty tests sometimes fail with a missing "extern crate rustc"

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#22725]
Sometimes the pretty tests fail with "extern crate rustc" missing. This happens when I'm running `make check-stage2 -j7` without having run `make rustc-stage2` first.

I suspect the make deps for the pretty tests aren't properly set up.

**Comment by alexcrichton** [comment]
Dupe of https://github.com/rust-lang/rust/issues/22021
