### ISSUE TITLE
Projecting `<Type as Trait>::N` should check that `N` is part of `Trait`

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#22731]
spawned off of #21259 

test case
```rust
use std::default::Default;

trait Impled { fn f(&self) {} }
trait Vr: Impled {
    type Y: Default + Par<<Self as Impled>::Noexist>; fn g(&self) {}
}
trait Par<X:Default> {
    fn h(&self) -> (X, String) { (Default::default(), format!("Par::h")) }
}

struct S1;
impl Impled for S1 {}
impl Vr for S1 { type Y = (); }
impl Par<()> for () { }

fn main() {
    let y: <S1 as Vr>::Y = Default::default();
    let (_, s) = Par::h(&y);
    println!("{}", s);
}
```

The above code should be rejected by the compiler, because `<Self as Impled>::Noexist` is not a well-formed projection of an associated item.  Instead, it currently runs.

----

(This bug is not quite as bad as it might seem, since one easily runs into problems if one actually attempts to program generically with this trait and associated item, as shown in the below modification to the last three lines above.  This new program is correctly rejected by the compiler, though perhaps with messages that are ... subpar:)

```rust
fn foo<V:Vr>(v: V) {
    let y: <V as Vr>::Y = Default::default();
    let (_, s) = Par::h(&y);
    println!("{}", s);
}
fn main() {
    foo(S1);
}
```

Transcript of error output:
```
../src/test/compile-fail/issue-21259-e.rs:18:18: 18:24 error: the trait `core::marker::Sized` is not implemented for the type `<V as Impled>::Noexist` [E0277]
../src/test/compile-fail/issue-21259-e.rs:18     let (_, s) = Par::h(&y);
                                                              ^~~~~~
../src/test/compile-fail/issue-21259-e.rs:18:18: 18:24 note: `<V as Impled>::Noexist` does not have a constant size known at compile-time
../src/test/compile-fail/issue-21259-e.rs:18     let (_, s) = Par::h(&y);
                                                              ^~~~~~
../src/test/compile-fail/issue-21259-e.rs:18:18: 18:24 error: the trait `core::default::Default` is not implemented for the type `<V as Impled>::Noexist` [E0277]
../src/test/compile-fail/issue-21259-e.rs:18     let (_, s) = Par::h(&y);
                                                              ^~~~~~
error: aborting due to 2 previous errors
```

**Comment by pnkfelix** [comment]
see also #19883 , which fixed a very similar bug, but presumably did so in a much more roundabout manner than what I am attempting.

**Comment by pnkfelix** [comment]
This should be fixed by #22172.  But I want to port the regression tests over from #22759.

**Comment by bluss** [comment]
I think this is fixed, I see

```
<anon>:5:27: 5:52 error: use of undeclared associated type `Impled::Noexist`
<anon>:5     type Y: Default + Par<<Self as Impled>::Noexist>; fn g(&self) {}
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~
```

:+1:

**Comment by pnkfelix** [comment]
And at this point I do not know what regression tests my earlier comment was referencing; there are not any such tests on #22759 ...

**Comment by pnkfelix** [comment]
Hmm, maybe I meant to reference #21259 and just mistyped?  Or maybe I meant to refer to this issue itself?  Reopened so that I'll attempt to put in the corresponding tests.

**Comment by arielb1** [comment]
This is fixed & tested.
