### ISSUE TITLE
binary distribution: 'install.sh --help' doesn't work

### ISSUE THREAD

**Issue by slimsag** [rust-lang/rust#22734]
In the latest nightly from the website for Linux, running `install.sh --help` fails:

```
~/Desktop/rust-nightly-x86_64-unknown-linux-gnu$ ./install.sh --help

Usage: ./install.sh [options]

Options:

./install.sh: 254: ./install.sh: META: parameter not set
```

**Comment by steveklabnik** [comment]
Today, for me, this works. @slimsag, it's been over a year, with nobody else reporting. If you still see this today, please let me know, but I'm going to assume that it was fixed somewhere in the meantime.

**Comment by slimsag** [comment]
Yeah, I haven't used it in a few months but last I did I didn't see this issue. Sorry for the noise @steveklabnik !

I will report again if I see it.

**Comment by steveklabnik** [comment]
No worries, I would much rather have too many reports than too few.
