### ISSUE TITLE
String Slices / Literals should not be mutable 

### ISSUE THREAD

**Issue by ltfschoen** [rust-lang/rust#22733]
I am learning Rust by applying code from the Rust Docs (Nightly) Book.
In [Chapter 2.11 Strings](http://doc.rust-lang.org/book/strings.html) they explain that the &str Type of (aka String Slices / String Literals) have a fixed size and **can NOT be mutated**, whereas the String Type (aka In-Memory Strings) **can be mutated**.

Why then does Rust and Cargo allow me to declare a **mutable** variable with ```let mut``` named ```stringLiteral``` of &str Type [here](https://github.com/ltfschoen/RustTest/blob/master/src/main.rs#L129) without giving a note, error, or warning in the console that this is not allowable?

Furthermore, why does Rust and Cargo allow me to build ```$ cargo build --verbose``` and run the app ```$ ./target/hello_world```, which allows me to overwrite the initial value stored in ```stringLiteral``` [here](https://github.com/ltfschoen/RustTest/blob/master/src/main.rs#L137), but without giving a note, error, or warning in the console that this is not allowable. I have demonstrate that it has in fact been overwritten by printing its new value to the console [here][https://github.com/ltfschoen/RustTest/blob/master/src/main.rs#L139],

**Comment by steveklabnik** [comment]
This is interior vs exterior mutabiltiy.

    let mut x = "some string";
    x = "some other string"; <- legal
    x.some_mutating_method(); <- not legal

The _binding_ is what's mutable, not what the binding points to.
