### ISSUE TITLE
ICE with a simple bintree, compiler panicked

### ISSUE THREAD

**Issue by Jeschli** [rust-lang/rust#22757]
```rust
#[derive(Debug)]
enum BtNode {
    Node(u32,Box<BtNode>,Box<BtNode>),
    Leaf(u32),
}

impl BtNode {
    fn stringify(&self) -> String {
        match *self {
            BtNode::Leaf(val) => { format!("Leaf: {}",val) }
            BtNode::Node(val,ref l,ref r) => {format!("Node: {} {:?} {:?}", val,l,r) }
        }
    }
    fn setLeft(&self, Box<BtNode> left) -> &BtNode {
        match *self {
            BtNode::Leaf(val) => { }
            BtNode::Node(val,ref l,ref r) => { l = left }
        }
        return self;
    }
}

fn main() {
    let node =  Box::new( BtNode::Node( 1, Box::new(BtNode::Leaf(0)), Box::new(BtNode::Leaf(0)) )) ;
    let node2 = Box::new( BtNode::Node( 2, Box::new(BtNode::Leaf(0)), Box::new(BtNode::Leaf(0)) )) ;
    let root = Box::new( BtNode::Node( 0, node, node2 ) );
}
```

`14:26 error: internal compiler error: ident only path should have been covered already`

**Comment by rprichard** [comment]
What's your compiler's `--version` output?  I'm using `rustc 1.0.0-nightly (2b01a37ec 2015-02-21) (built 2015-02-22)`, and I instead see this error when I compile the test case:

    rprichard@ryan:~/mess$ rustc test3.rs
    test3.rs:14:23: 14:27 error: expected one of `!`, `:`, or `@`, found `left`
    test3.rs:14 fn setLeft(&self, Box left) -> &BtNode {
                                      ^~~~

(It should be `left: Box` rather than `Box left`.  Of course, the compiler shouldn't ICE, in any case.)

**Comment by Jeschli** [comment]
I know that there was some error in the code. Compiler version was
rustc 1.0.0-dev (dfc5c0f1e 2015-02-18) (built 2015-02-18)
