### ISSUE TITLE
Compiling `make check-stage1-std` takes ages

### ISSUE THREAD

**Issue by edwardw** [rust-lang/rust#22761]
The compiling stage of `make check-stage1-std` takes a very long time now. I killed it after about 10 minutes on my laptop. Observed this on top of 2890508d97af287a136ac50ffa13a1c0a3e32e4e.

**Comment by aochagavia** [comment]
I have experienced this too

**Comment by dotdash** [comment]
`time: 467.202   type checking`

probably a case of #22204

**Comment by birkenfeld** [comment]
Seems reasonable to close this in favor of the more specific issue?

**Comment by Mark-Simulacrum** [comment]
The more specific issue has now been marked `E-needstest`, so this can probably be closed.

**Comment by Mark-Simulacrum** [comment]
Closing per my above comment.
