### ISSUE TITLE
Add CBOR output to rustdoc. Write a rustdoc server.

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#22768]
The current rustdoc html output is huge (e.g. 22M for https://github.com/mahkoh/posix.rs/) and the json output is still not compact enough (3.3M.)

Add CBOR output to rustdoc and write a server that dynamically generates the requested pages from this output and handles searching.

**Comment by tomjakubowski** [comment]
Couldn't (shouldn't?) this be done out of tree? JSON can already be converted to CBOR with existing tools and I'm somewhat uneasy about distributing an entire web server implementation with Rust, even if it isn't publicly exported in the `std` crate.

**Comment by retep998** [comment]
Having to wait for rustdoc to output tens of thousands of files takes a non-trivial amount of time. Outputting to a format designed for a web server in the first place would save a significant amount of time.

**Comment by tomjakubowski** [comment]
Have you profiled rustdoc and seen that it spends significant amounts of its time on converting its output into HTML? It seems likely to me that rustdoc, like a normal `-O0` rustc invocation, spends most of its time on the analysis phase.

**Comment by huonw** [comment]
@tomjakubowski I suspect the IO overhead of creating thousands of files may be significant too.
