### ISSUE TITLE
Deprecation messages not escaped properly in documentation

### ISSUE THREAD

**Issue by mrmonday** [rust-lang/rust#22780]
For example: http://doc.rust-lang.org/collections/string/type.CowString.html

The speech marks are not escaped, leading weird things to happen with the HTML.

**Comment by steveklabnik** [comment]
Can you post a screenshot, and browser/platform? This looks fine to me?

**Comment by mrmonday** [comment]
Looks like it's already fixed! Sorry for the noise.

**Comment by steveklabnik** [comment]
No worries! I'd rather have over reporting than under reporting :)
