### ISSUE TITLE
http://doc.rust-lang.org/book/ could use a search feature.

### ISSUE THREAD

**Issue by foodhype** [rust-lang/rust#22786]

**Comment by steveklabnik** [comment]
tagging `rustbook` and `rustdoc` because this is a feature they'd need to add.

**Comment by asolove** [comment]
I *think* adding a generic concordance feature or full text search to the underlying mdBook platform is not going to produce good results for an educational book like this. For a term like `FnOnce`, the chapters that use that term the most are likely not the best first reference for someone searching for that word. 

Really good results will probably require some amount of manual effort. For `FnOnce`, for example, you'd want to have the very first reference be to the spot where it's defined and explained, then further references given to its usage in various examples or specific gotchas or comparisons to other function types. 

Unless anyone objects, I'd like to try to manually create entries for a few terms based on the existing material in the new repo. I'll post a comparison to the results those terms get when the text is run through a concordance generator. Then we can compare both the effort and the payoff of the two approaches.

**Comment by nodakai** [comment]
If it is difficult to add a search function, please consider publishing a concatenated version of the book and let us use a search function of a web browser.

**Comment by 0joshuaolson1** [comment]
Another option is pointing the user to a general search engine and restricting to the website.

**Comment by steveklabnik** [comment]
Right now, our search works offline; it'd be nice to not lose that.

**Comment by steveklabnik** [comment]
rustbook is no longer being developed, in favor of mdbook. If you'd like to see this feature, please report it to mdbook's tracker. Thanks!
