### ISSUE TITLE
have a buildbot that test compile for multiple targets

### ISSUE THREAD

**Issue by semarie** [rust-lang/rust#22794]
Having a buildbot that try to compile multiple targets could help for detect commits that would break targets without dedicated buildbots (in mind it is openbsd target, but it could apply to others, like dragonfly for example).

The purpose isn't to run a fully test suite (it isn't possible for all targets without a dedicated buildbot) but only ensure that the compilation don't break. It would at least be better than today, where you can break something without known.

It would help commiters to ensure that their PR don't break too badly uncommon targets.

**Comment by semarie** [comment]
I currently take a look at reducing the toolchain needed when cross-building some libraries.
It should be possible to build several libs without any cross-linking, by forcing building `rlib` instead of `dylib` crates.

Using this method, under openbsd I am able to build `TARGET_CRATES` of dragonfly (libc, std, flate, arena, term, serialize, getopts, collections, test, rand, log, graphviz, core, rbml, alloc, unicode, and rustc_bitflags), by passing `RUSTFLAGS_{crate}=--crate-type rlib` at `make` invocation.

**Comment by steveklabnik** [comment]
Triage: I don't believe that this is something that's been done, and I'm not sure it's something that there's plans to do.

**Comment by alexcrichton** [comment]
Given that we now have bots cross-compiling to FreeBSD and NetBSD, I think this is done :)
