### ISSUE TITLE
setlocale and var_os interaction.

### ISSUE THREAD

**Issue by dpc** [rust-lang/rust#22793]
In my ncurses program if I have two pieces of code:

1:

```
          if env::var_os("ESCDELAY").is_none() {} 
```

2:
```
         unsafe {                                                                                                                                                      
              let _ = locale::setlocale(locale::LC_ALL, b"en_US.UTF-8".as_ptr() as *const i8);                                                                          
          }  
```

If 2 is before 1, then unicode in my program breaks. If 1 is before 2 everything is fine. 

The bindings to setlocale that I use are:
```
  mod locale {
      use libc::{c_int, c_char};                                                                                                                                        
      pub const LC_ALL: c_int = 6; 
      extern "C" {
           pub fn setlocale(category: c_int, locale: *const c_char) -> *mut c_char;
      }
}
```

My guess is that `std::env` is not expecting `setlocale` changing the underlying environment or something like that. I'm not sure if it's OK, and should it be documented, but decided to let you know, as it was really confusing.

**Comment by alexcrichton** [comment]
Could you elaborate a bit more on "unicode in my program breaks"? Right now we're just passing along the return value from `getenv` and we're not attempting to interpret it as one encoding or another. If the bytes aren't value UTF-8 then the otherwise explicit conversion to `String` will fail.

**Comment by dpc** [comment]
The problem is observed as  `[00` and similar strings being printed instead of one wide character that I want to print. This kind of behavior happens when `setlocale` is not called, since 

I would expect that `env::var_os("ESCDELAY").is_none()` would not mutate anything, that's why I'm surprised about this behavior. 

I've just pushed: https://github.com/dpc/rhex/commit/f41688a9bb8fa37df50768ab35d5b24d5e293105 that works fine, and changing the code with:

```
diff --git a/src/ui/curses.rs b/src/ui/curses.rs
index 8f879a1..efe97a1 100644
--- a/src/ui/curses.rs
+++ b/src/ui/curses.rs
@@ -164,14 +164,14 @@ impl CursesUI {
             panic!("Your TERM environment variable must end with -256color, sorry, stranger from the past. It is curable. Google it, fix it, try again.");
         }
 
-        if env::var_os("ESCDELAY").is_none() {
-         //   env::set_var("ESCDELAY", "25");
-        }
 
         unsafe {
             let _ = locale::setlocale(locale::LC_ALL, b"en_US.UTF-8".as_ptr() as *const i8);
         }
 
+        if env::var_os("ESCDELAY").is_none() {
+         //   env::set_var("ESCDELAY", "25");
+        }
 
         nc::initscr();
         nc::start_color();
```

triggers the issue. As you can see the only difference is the order of this two calls.

**Comment by alexcrichton** [comment]
When you saying that the values being printed are different, how are the calls to printing connected to the call to `env::var_os`?

**Comment by dpc** [comment]
They should be not. Only `setlocale` is related.

**Comment by mahkoh** [comment]
>b"en_US.UTF-8".as_ptr() as *const i8

No null byte.

**Comment by dpc** [comment]
@mahkoh: That was it. One unsafe in my whole code, and it had to have a bug.

Thank you and sorry for taking your time. The fact that it was working fine before made my overlook it.
