### ISSUE TITLE
lifetime "parameter 'a is never used" even though it is

### ISSUE THREAD

**Issue by Byron** [rust-lang/rust#22798]
If a default type parameter requires a lifetime argument, but the actual structure does not, we will get the "parameter 'a is never used" message.

The issue can be reproduced with the following code.
```Rust
struct Foo<'a> {
    a: &'a str,
}

struct Bar<'a, T = Foo<'a>> {
    b: T,
}
```

Causing the compiler error:
```
tests/lang.rs:970:16: 970:18 error: parameter `'a` is never used
tests/lang.rs:970     struct Bar<'a, T = Foo<'a>> {
                                 ^~
tests/lang.rs:970:16: 970:18 help: consider removing `'a` or using a marker such as `core::marker::PhantomData`
tests/lang.rs:970     struct Bar<'a, T = Foo<'a>> {
```

It can be made to work as follows ...
```Rust
use std::marker::PhantomData;
struct BarWorking <'a, T = Foo<'a>> 
    where T: 'a {
    b: T,
    _m: &'a PhantomData<T>,
}
```
... yet I think if 'a is used in a Default type, it should not be thought of as unused. In my example, it is quite hard to instantiate such a structure as it uses borrowed phantom data. If `&'a` is removed, the compiler error will be back as well, so `where T: 'a` does still not qualify as usage of `'a`.

Maybe this is expected, yet I felt the need to make sure. Thanks for your understanding.

### Meta

```bash
$ rustc --version --verbose
rustc 1.0.0-nightly (522d09dfe 2015-02-19) (built 2015-02-19)
binary: rustc
commit-hash: 522d09dfecbeca1595f25ac58c6d0178bbd21d7d
commit-date: 2015-02-19
build-date: 2015-02-19
host: x86_64-apple-darwin
release: 1.0.0-nightly
```

**Comment by edwardw** [comment]
I believe this is not an issue. `Bar` in your example may very well be instantiated with a type parameter without lifetime bound in it. So indeed `'a` is not used in that case.

If you want to express "either a bare type or a reference to a type", then an enum suits you well:

```rust
enum Foo<'a, T:'a> {
    A(T),
    B(&'a T),
}

struct Bar<'a, T:'a> {
    b: Foo<'a, T>,
}

fn main() {
    let _ = Bar { b: Foo::A(10) };
    let _ = Bar { b: Foo::B(&"rust") };
}
```

**Comment by Byron** [comment]
I see - makes sense. Just because I mention `'a` in the default type, it doesn't need to be instantiated with it.
Thanks for the clarification.
