### ISSUE TITLE
Consider renaming std::os::unix -> std::os::posix

### ISSUE THREAD

**Issue by carllerche** [rust-lang/rust#22808]
I believe everything in there is covered by the posix standard. Also, Linux != Unix, so it would be more appropriate.

However, this is a minor bike shed and not the end of the world either way.

**Comment by nagisa** [comment]
`unix` also covers BSDs, and some of the exposed APIs are not necessarily based on POSIX APIs.

**Comment by carllerche** [comment]
@nagisa my main point is that `unix` doesn't technically cover Linux at all. If there are APIs that are to be shared between all the *nix OSs, they should be posix APIs. Most of the APIs that the BSDs expose that are not covered by POSIX are also not covered by darwin.

At the end of the day, does it make more sense to have specific types conditionally defined in a module, or conditionally define modules and have contained types be constant.

It may make sense to have both `std::os::posix` and `std::os::unix`.

**Comment by alexcrichton** [comment]
The design of `std::os` is planned to match what `#[cfg]` accepts. For example `#[cfg(unix)]` code can be known to import `std::os::unix::*;` and `#[cfg(target_os = "foo")]` code can import `std::os::foo::*` (as they all start to grow).

Along those lines, if we were to consider this we should also consider renaming `cfg(unix)` as well.

**Comment by aturon** [comment]
@carllerche 

A couple things:

1. As @alexcrichton said, the naming here is chosen just to match the `cfg` spec, so "unix" covers all non-Windows platforms at the moment. So the APIs here are intended to cover anything that works across all of those platforms, independently of posix.

2. For `linux` and other platforms, we intend to add more modules, again matching the `cfg` spec. So Linux-specific APIs would be `std::os::linux`, which makes it clear how platform-specific your code is.

**Comment by steveklabnik** [comment]
This is all stable now, so this can be closed.
