### ISSUE TITLE
Inconsistent visibility when importing a type alias with an impl across crates

### ISSUE THREAD

**Issue by gkoz** [rust-lang/rust#22804]
Crate `a`:
```rust
pub mod foo {
    struct X;
    pub type Foo = X;

    impl Foo {
        pub fn foo() { println!("Hello!"); }
    }
}

pub use foo::Foo;
```
Crate `b`:
```rust
extern crate a;

use a::foo;
use a::Foo;

fn main() {
    // this is valid
    foo::Foo::foo();
    // error: unresolved name `Foo::foo`
    Foo::foo();
}
```

**Comment by Kimundi** [comment]
This does not have anything to do with visibility directly, rather type aliases can not be used as modules in general. That is, `Foo::foo()` never works.

**Comment by gkoz** [comment]
@Kimundi do you mean this will not work either? It does.
```rust
pub mod foo {
    struct X;
    pub type Foo = X;

    impl Foo {
        pub fn foo() { println!("Hello!"); }
    }
}

use foo::Foo;

fn main() {
    Foo::foo();
}
```

**Comment by Kimundi** [comment]
Oh, I guess as side effect of @eddyb's recent work in that area it does now... Then it does indeed look like a visibilty bug.

Afaik type defs in general (that is, normal ones and associated types) currently leak private types to the outside, and it is not yet clear whether they should be allowed to or not, leading to such inconsistencies.

cc @nikomatsakis

**Comment by gkoz** [comment]
To be clear, I'm not trying to access any private items. It's not important that `X` is private.
But the very ability to add an impl to a type alias is rather surprising to me.

**Comment by gkoz** [comment]
D'oh! It is because of `X` being private. Okay...

**Comment by gkoz** [comment]
Actually I can't reproduce the error on the recent nightly.
