### ISSUE TITLE
rust-installer needs updating

### ISSUE THREAD

**Issue by mrmonday** [rust-lang/rust#22807]
The version of rust-installer which is currently in the repository has a sub-module which is fetched over HTTP rather than HTTPS. This is insecure, and also breaks any GitHub Page which uses Rust as a sub-module, such as BitRust (https://github.com/mrmonday/bitrust, http://bitrust.octarineparrot.com/).

**Comment by alexcrichton** [comment]
cc @brson

**Comment by mrmonday** [comment]
Pull #23763 seems to have fixed this.
