### ISSUE TITLE
Traverse interpolated TTs so we can parse them as other things

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#22819]
See discussion on #9364.

**Comment by pczarn** [comment]
> the problem is that [interpolated statements] cannot be broken apart and re-parsed after they have been parsed once.

The ability to convert token-trees ↔ AST is also needed to fix #16472.

**Comment by kmcallister** [comment]
Do we need that ability here? It's only about interpolated `tt` matches.

**Comment by jseyfried** [comment]
cc me

**Comment by jseyfried** [comment]
Fixed in #34908.
