### ISSUE TITLE
Don't accidentally parse MatchNt

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#22814]
This bit of macro from `libcore`:

```rust
( $($name:ident)+) => (
    #[stable(feature = "rust1", since = "1.0.0")]
    impl<$($name: Hash),*> Hash for ($($name,)*) {
```

was apparently parsing as a MatchNt `$name:Hash`, which breaks with my fix to #21370.

There's no need to parse MatchNt on a macro RHS, but we don't know we're on a macro RHS when we're parsing a token tree.  Probably we should get rid of MatchNt. It's a weird "composite token" and the tokenizer phase is clearly too early to spot it.  Rather we can look for the colon and fragment specifier when we parse a LHS TT into matchers.

Nominating 1.0-beta, P-backcompat-lang.

**Comment by kmcallister** [comment]
I guess it used to turn into a `SubstNt` in `TokenTree::get_tt` but that's too late on my branch.

**Comment by pnkfelix** [comment]
1.0-beta, P-backcompat-lang.

**Comment by kmcallister** [comment]
My best plan at the moment is to change the parser so it never parses `MatchNt`s, and then do a separate pass to create them from `SubstNt Colon Ident` just before parsing a `macro_rules!` LHS. It's a hack for sure. Really, we should have a separate matcher-side token tree type, or some higher level AST for matchers.  But I don't want to make huge changes all over macro parsing and transcription.

(There is already some other code that decomposes a `MatchNt` into `SubstNt Colon Ident` under some circumstances.)

**Comment by kmcallister** [comment]
The main parser won't even parse `SubstNt` at the moment, which is a [known weirdness](https://github.com/rust-lang/rust/blob/36cd65f78665b992e67ef941ee0aed6522ef1a8c/src/libsyntax/ext/quote.rs#L781-L785). Maybe that should be fixed along with this issue.

**Comment by kmcallister** [comment]
@bstrie is going to look into this.

**Comment by pnkfelix** [comment]
Provisionally reclassifying as 1.0.

@kmcallister is there a strong reason to put this back on the 1.0 beta milestone?

@bstrie is there a status update?

**Comment by kmcallister** [comment]
I'm not sure if this is actually a back-compat hazard on `master`, or just an obstacle to the refactoring that I was pursuing. I'm going to look into this more in the near future.

I agree that we can put this off until 1.0-final.

**Comment by Stebalien** [comment]
Triage: Can't reproduce. @kmcallister?

```
trait Test {}

macro_rules! test {
( $($name:ident)+) => (
    impl<$($name: Test),*> Test for ($($name,)*) {
    }
)
}

test!(A B C);

fn main() {}
```
