### ISSUE TITLE
Send/Sync transitive analysis lost in stored associated types

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#22828]
For example, this code does not compile:

```rust
trait Foo {
    type A;
    fn foo(&self) {}
}

impl Foo for usize {
    type A = usize;
}

struct Bar<T: Foo> { inner: T::A }

fn is_send<T: Send>() {}

fn main() {
    is_send::<Bar<usize>>();
}
```

```
foo.rs:15:5: 15:26 error: the trait `core::marker::Send` is not implemented for the type `<usize as Foo>::A` [E0277]
foo.rs:15     is_send::<Bar<usize>>();
              ^~~~~~~~~~~~~~~~~~~~~
foo.rs:15:5: 15:26 note: `<usize as Foo>::A` cannot be sent between threads safely
foo.rs:15     is_send::<Bar<usize>>();
              ^~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
```

cc @nikomatsakis, @pnkfelix

**Comment by pnkfelix** [comment]
I think this may be another instance of #22815

**Comment by alexcrichton** [comment]
Trusting @pnkfelix's analysis, closing in favor of #22815 but adding test case there as well.

**Comment by pnkfelix** [comment]
(it of course would be good to *confirm* that this actually is an instance of #22815 -- my initial reaction when I saw it was "they might be related ... but wait, wasn't part of the opt-in-builtin-bounds work to be able to move the special case handling of `Send` / `Sync` out into library code...?"; I've only done some rough skimming that makes me think the hypothesis remains plausible.)

**Comment by alexcrichton** [comment]
Ah either way is fine by me, I personally like fewer issues :). We can reopen once #22815 is addressed one way or another if necessary (or if you'd like to reopen now that's also fine by me!)

**Comment by pnkfelix** [comment]
@alexcrichton oh that was really just a note to myself as much as anything else, not a comment on your choice to close this ticket.  :)

**Comment by nikomatsakis** [comment]
I don't think this code uses type-contents. If it does, that is itself a bug! Either way, we should keep this open for the time being.

**Comment by FlaPer87** [comment]
cc @flaper87
