### ISSUE TITLE
#[stable], #[unstable], #[deprecated] are not errors when used non-#[staged_api] crates

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#22830]
They are ignored, but silently. It is probably better if we make them errors to give us room to build some future system with those nice names.

This compiles without a peep from rustc:

```rust
#![allow(dead_code)]

#[stable]
fn foo() {}
#[deprecated] 
struct Bar;
#[unstable]
type X = i8;

fn main() {}
```

**Comment by nagisa** [comment]
Willing to pick this up.

One thing to note, that it will 100% cause breakage outside the compiler, and possibly inside as well.

**Comment by brson** [comment]
I did it this way to avoid breakage for people who were using them. We might put in deprecation warnings for a few weeks.

**Comment by huonw** [comment]
I'm in favour of a smooth deprecation path via warnings! :)

**Comment by pnkfelix** [comment]
@alexcrichton asks whether the unused-attribute lint would catch these, or if they are unconditonally marked as used.

Either way, some sort of warning sounds good.

**Comment by pnkfelix** [comment]
1.0 polish, P-high.

**Comment by sfackler** [comment]
@pnkfelix they are unconditionally marked as used.

**Comment by brson** [comment]
Ugh, I'm wishing I had done this a lot sooner. Working on a patch for this now, but it's probably going to cause some breakage. I'll see if I can guess how much.

**Comment by brson** [comment]
Here's the list of current out-of-tree usage of stability attributes https://gist.github.com/brson/1dd62761ee8dff6cdcaa

**Comment by alexcrichton** [comment]
This was fixed and backported to beta recently, yay!
