### ISSUE TITLE
Expose thread handles in std::os::unix

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#22840]
Builder, JoinHandle, etc. don't expose the pthread handle and not all pthread functions are available.

**Comment by nagisa** [comment]
We don’t necessarily want to restrict ourselves to the terrible pthread. We might just go ahead and just use syscalls directly sometime later, which is impossible if we start exposing pthread handles now.

**Comment by mahkoh** [comment]
>We don’t necessarily want to restrict ourselves to the terrible pthread. 

Instead you restrict the user to the terrible std::thread?

**Comment by huonw** [comment]
What functionality do you need/want?

**Comment by mahkoh** [comment]
That's irrelevant.
