### ISSUE TITLE
Windows binaries aren't available across platforms.

### ISSUE THREAD

**Issue by alexchandel** [rust-lang/rust#22856]
It is difficult to obtain the Windows Rust libraries on OS X and linux. While linux/OS X binaries are available in `.tar.gz` form, and can be extracted into a temporary directory and have their `lib/rustlib/x86_64-unknown-linux-gnu/` folder manually copied to `/usr/local/lib/rustlib`, getting the equivalent Windows binaries requires installing them onto a Windows machine and manually copying the files over. This situation would be made simpler if the `rustlib` folders were independently available for all targets.

As a second, broader issue, it would be nice to be able to install multiple targets into `rustlib` using `rustup.sh`, with something like `rustup.sh --target=x86_64-apple-darwin,x86_64-unknown-linux-gnu`. This would be similar to Rust's configure script. This would make cross compilation and updating easier, since running rustup deletes any manually installed targets in `rustlib`.

**Comment by alexcrichton** [comment]
I think that you may want to look into using the tarballs we distribute instead of the nightlies. For example [`rustc-nightly-i686-pc-windows-gnu.tar.gz`](http://static.rust-lang.org/dist/rustc-nightly-i686-pc-windows-gnu.tar.gz) sounds like what you want.

**Comment by alexchandel** [comment]
@alexcrichton On a related note, I'm looking for a tarball or zip equivalent to `https://static.rust-lang.org/dist/rust-0.12.0-x86_64-w64-mingw32.exe'`.

The Windows package manager Chocolatey prefers "portable" packages over those with external installers. Sadly, neither [rust-0.12.0-x86_64-w64-mingw32.tar.gz](https://static.rust-lang.org/dist/rust-0.12.0-x86_64-w64-mingw32.tar.gz) nor [rust-nightly-x86_64-w64-mingw32.tar.gz](https://static.rust-lang.org/dist/rust-nightly-x86_64-w64-mingw32.tar.gz) exist.

And while I found the rustc nightly tarball, `https://static.rust-lang.org/dist/rustc-nightly-x86_64-pc-windows-gnu.tar.gz`, I couldn't find a cargo one, `https://static.rust-lang.org/dist/cargo-nightly-x86_64-pc-windows-gnu.tar.gz`.

**Comment by alexcrichton** [comment]
Much of our automation was added post 0.12.0, so older versions may not exist. Cargo tarballs, however, are available under `cargo-dist` instead of the `dist` folder.

**Comment by alexchandel** [comment]
Thanks! Do you think a "grand unified" rustc+cargo tarball will be made for Windows when the beta arrives (similar to the ones already for OS X and Linux)?

**Comment by alexcrichton** [comment]
At this time I don't think that there are plans for that, it's looking like we'll just create combined installers but not combined tarballs. That's not to say it's not possible though :)

cc @brson

**Comment by alexchandel** [comment]
@alexcrichton @brson Now that 1.0.0 is out, could we please have a portable version of the Windows build? Not everyone likes installers, and the [chocolatey](https://chocolatey.org) package manager project actively encourages portable distributions, with the goal of eliminating PATH clutter in Windows.

From a cursory examination of http://www.rust-lang.org/install.html, complete binary archives are only provided for Linux and Mac. In the Mac case, we provide a `.tar.gz` *even though* we also provide a `.pkg` installer. Can we do the same for Windows?
