### ISSUE TITLE
allow line numbers in rustdoc

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#22878]
In documentation it might be nice to talk about specific line numbers so RustDoc should (perhaps optionally) include them in examples. [Here](http://words.steveklabnik.com/a-new-introduction-to-rust) they are being added manually which isn't so nice. In the [book](http://doc.rust-lang.org/book/variable-bindings.html), there aren't line numbers either.

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by steveklabnik** [comment]
@rust-lang/rustdoc, do we ever plan on implementing this?

**Comment by GuillaumeGomez** [comment]
Sounds like a good idea. I'll implement it later on.
