### ISSUE TITLE
Android cross-compiler rustc build failed on mac

### ISSUE THREAD

**Issue by lahwran** [rust-lang/rust#22871]
My system:
- OSX Mavericks (10.5.9)
- XCode 6.1.1 (6A2008a)
- `gcc` is llvm-gcc
- android ndk version r10d
- android toolchain created with `android-ndk-r10d/build/tools/make-standalone-toolchain.sh --platform="android-18" --toolchain=arm-linux-androideabi-4.8 --arch=arm --install-dir="$PWD/toolchain-android-18-arm-ndk"`

here is all my make output, plus the error:

https://gist.github.com/lahwran/a36ab003c6f4cec8c189

Unfortunately I've done a git clean since then, because I was going to try some workarounds, but then I just kinda gave up. I'm pretty sure it will repro if I do the same thing again, though.

**Comment by steveklabnik** [comment]
Is this still an issue today?

**Comment by lahwran** [comment]
I don't think I'll have time to test it in the near future.

**Comment by Mark-Simulacrum** [comment]
Going to go ahead and give this a close. I'm not 100% sure, but as far as I can tell, with macOS 10.12.4, this works fine, and the r14b Android NDK. Please reopen if that's not the case.
