### ISSUE TITLE
Stop statting paths before opening them

### ISSUE THREAD

**Issue by pcwalton** [rust-lang/rust#22879]
https://github.com/rust-lang/rust/blob/master/src/libstd/fs/mod.rs#L275-L280

It's ruining my ability to write a sandbox. The `stat` syscall might be blacklisted while `open` is not. That should not prevent you from opening files!

Nominating because I believe this must be fixed before 1.0.

**Comment by pnkfelix** [comment]
1.0, P-high, needs-decision.
