### ISSUE TITLE
Rust Book Guessing Game Refers To Incorrect Option Type

### ISSUE THREAD

**Issue by trishume** [rust-lang/rust#22905]
The guessing game section of the Rust book has the line:
```rust
let input_num: Result<u32, _> = input.parse();
```

but multiple places nearby refer to unwrapping it with `.ok()` to produce an `Option`, which is never actually done in the code examples. It seems someone updated the code to directly use the `Result<u32,_>` and didn't update the surrounding text and the type error message.

This should be an easy fix but at the moment I'm a Rust newbie and I don't have a rust compiler to determine the correct type and error message.

**Comment by djmally** [comment]
I'll take a look into this. I'm a bit of a Rust newbie myself, but this seems like a pretty easy fix and I do have the tools available.

**Comment by djmally** [comment]
Submitted a PR for this as #22911. Found another problem with this part of the guide, but I'll make a separate issue for it.

**Comment by teotwaki** [comment]
@trishume Can this be closed? @djmally's fix has been applied to the documentation.
