### ISSUE TITLE
Invalid section names in Mach-O file on OS X w/ custom target spec

### ISSUE THREAD

**Issue by alexchandel** [rust-lang/rust#22915]
Despite a valid target specification for `i686-unknown-plan9`, which is intended to produce a statically linked Mach-O,

``` json
{
    "pre-link-args": ["-static"],
    "data-layout": "e-p:32:32:32-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:8-s0:32:32-f80:128:128-n8:16:32:64-S0",
    "llvm-target": "i686-apple-darwin",
    "target-endian": "little",
    "target-pointer-width": "32",
    "arch": "x86",
    "os": "plan9",
    "morestack": false,
    "dynamic_linking": false,
    "executables": true,
    "is_like_osx": true
}
```

I cannot even build libcore because rustc still tries to produce a Mach-O with invalid, ELF-like section names:

``` bash
rustc --target i686-unknown-plan9 -O -Z no-landing-pads -C no-stack-check --out-dir target/i686-unknown-plan9 libcore/lib.rs
LLVM ERROR: Global variable 'rust_metadata_core_89ea4c7b067f3bc4' has an invalid section specifier '.note.rustc': mach-o section specifier requires a segment and section separated by a comma.
make: *** [target/i686-unknown-plan9/libcore.rlib] Error 1
```

**Comment by huonw** [comment]
So, to be clear, the problem here is specifically that rustc generates invalid data for creating mach-o object files?

**Comment by nagisa** [comment]
Interesting. This call to [get_metadata_section](https://github.com/rust-lang/rust/blob/157614249594f187f421cd97f928e64c5ab5c1fa/src/librustc/metadata/loader.rs#L528) is the relevant code.

**Comment by alexchandel** [comment]
@huonw I think so, but I'm not sure where the section names (and segment names in Mach-O) get emitted. I intended `"llvm-target": "i686-apple-darwin"` and `"is_like_osx": true` to cause rustc to produce a Mach-O. Is the object format determined by rustc or by LLVM?

**Comment by steveklabnik** [comment]
Triage: no changes I'm aware of

**Comment by alexchandel** [comment]
Presently, the compiler dies with the error
```
Assertion failed: (TM.isCompatibleDataLayout(getDataLayout()) && "Can't create a MachineFunction using a Module with a " "Target-incompatible DataLayout attached\n"), function MachineFunction, file /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/llvm/lib/CodeGen/MachineFunction.cpp, line 108.
```
when given a json for `i686-unknown-plan9` with `"data-layout": "e-p:32:32:32-i1:8:8-i8:8:8-i16:16:16-i32:32:32-f32:32:32-a:0:8-n8:16:32-S0"`. This error happens even when the "data-layout" is reduced to just "e-p:32:32:32" though.

Leaving the field out altogether triggers this error:
```
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'Field data-layout in target specification is required', ../src/librustc_back/target/mod.rs:377
```

So it's unknown whether ELF sections are still produced, since those would be linker errors.

**Comment by PaulGrandperrin** [comment]
Hi, I just want to point out that it seems to me that this bug is fixed in rust beta and nightly.
You can see here that the bug was triggered on rust stable:
https://travis-ci.org/rust-fuzz/honggfuzz-rs/jobs/344493069#L120
But is now fixed on rust beta and nightly:
https://travis-ci.org/rust-fuzz/honggfuzz-rs/builds/344493067

**Comment by frewsxcv** [comment]
just confirmed this is fixed for me too! afl.rs now works on mac

**Comment by frewsxcv** [comment]
Gonna close this. If anyone else encounters this, let me know and I'll reopen
