### ISSUE TITLE
fs::DirEntry does not provide a relative path

### ISSUE THREAD

**Issue by hugoduncan** [rust-lang/rust#22926]
In some situations, e.g. copying a sub-tree, a relative path is required for an entry returned by `read_dir` or `walk_dir`.  Consider changing `path` to return a relative path, or adding a `rel_path` function to provide it if the current `path` semantics should be preserved.

The [`fs::DirEntry::path` function](http://doc.rust-lang.org/std/fs/struct.DirEntry.html#method.path) returns a full path, with the root of the `read_dir` or `walk_dir` call prepended.  Recovering a relative path form the full path seems relatively expensive (`entry.path().relative_from(root).unwrap()`), espescially since `DirEntry::path` has to explicitly join the root in the first place.

**Comment by GuillaumeGomez** [comment]
So if I understand you well, when you call `walk_dir` on "./test/sub/", you want a `relative_path` function which returns:
 * "sub/file"
 * "sub/file2"
 * "sub/dir1"
 * ...

That's it ?

**Comment by alexcrichton** [comment]
cc @steveklabnik, can you move this to the RFC repo?

**Comment by hugoduncan** [comment]
@GuillaumeGomez If I call `walk_dir` on "./test/sub/" I would like the paths "file", "file2", "dir1" from your example (assuming the files are "./test/sub/file", etc).

**Comment by GuillaumeGomez** [comment]
So just the item's name. Okay. I'll write a RFC for that then.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#934
