### ISSUE TITLE
install script fails: CFG_DESTDIR not set

### ISSUE THREAD

**Issue by erkinalp** [rust-lang/rust#22929]
I am getting this error message while installing Rust nightly build(by executing the installer script from tarball without rustup):
`./install.sh: 781: ./install.sh: CFG_DESTDIR: parameter not set`

**Comment by steveklabnik** [comment]
I am sorry that nobody responded to you in a year, @erkinalp . I cannot even find a reference in the source to `CFG_DESTDIR` anymore, so it's not even clear to me that this still a bug. If somehow, this is still happening today, please let me know, but I'm going to assume that this is stale.
