### ISSUE TITLE
unnecessary token "<-" in token definition

### ISSUE THREAD

**Issue by madmalik** [rust-lang/rust#22934]
[The LArrow](https://github.com/rust-lang/rust/blob/master/src/libsyntax/parse/token.rs#L132) is defined as a token, but serves no purpose in the language as far as i can tell. 

Maybe an oversight?

**Comment by kmcallister** [comment]
Nominating P-backcompat-lang:

```rust
macro_rules! foo {
    (<-) => ("yes");
    ($($x:tt)*) => ("no");
}

fn main() {
    println!("{}", foo!(< -));
}
```

**Comment by pnkfelix** [comment]
was used for moves!

**Comment by pnkfelix** [comment]
we're going to reserve the token for future use.

**Comment by kmcallister** [comment]
That makes sense to me. Good to know it's there on purpose :)
