### ISSUE TITLE
internal compiler error : index.end <= self.len() (built 2015-03-01)

### ISSUE THREAD

**Issue by yann-ledu** [rust-lang/rust#22968]
with rustc 1.0.0-nightly (157614249 2015-03-01) (built 2015-03-01)

```rust
use std::iter::IntoIterator::IntoIter;
fn main()
{
    let mul2 = |x:IntoIter| x.iter().map(|x| x);
}
```

**Comment by frewsxcv** [comment]
This is still an issue

```
~/Downloads $ rustc test.rs
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'assertion failed: index.end <= self.len()', /Users/rustbuild/src/rust-buildbot/slave/beta-dist-rustc-mac/build/src/libcore/slice.rs:519


~/Downloads $ rustc --version
rustc 1.0.0-beta.2 (e9080ec39 2015-04-16) (built 2015-04-16)
```

**Comment by michaelrutherford** [comment]
Still an issue in 1.0.0.
> $ cargo build
thread '<main>' panicked at 'assertion failed: index.end <= self.len()', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/slice.rs:518

> $ rustc --version
rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14)

**Comment by tksfz** [comment]
This  is  still an issue in 1.3.0-nightly:

$ rustc test.rs
[thom@xps tmp]$ rustc test.rs
error: internal compiler error: unexpected panic
thread 'rustc' panicked at 'assertion failed: index.end <= self.len()', ../src/libcore/slice.rs:544

stack backtrace:
   1:     0x7fd6c19bd5ee - sys::backtrace::write::h04a6ced565b26815Lqs
   2:     0x7fd6c19c5214 - panicking::on_panic::h521f84b604e22dfel8w
   3:     0x7fd6c198804e - rt::unwind::begin_unwind_inner::hd3dee614a0e1c16cZNw
   4:     0x7fd6c1988d7c - rt::unwind::begin_unwind_fmt::ha4ce6704c81423045Mw
   5:     0x7fd6c19c4dd6 - rust_begin_unwind
   6:     0x7fd6c1a15bb4 - panicking::panic_fmt::he89ea3094b3178e919B
   7:     0x7fd6c1a0f9dd - panicking::panic::h9e565ee21070221by8B
   8:     0x7fd6c11f8271 - astconv::finish_resolving_def_to_ty::h03670159ac2fefe7aTv
   9:     0x7fd6c11b6340 - astconv::ast_ty_to_ty::hb2c49d2cf31c029bYUv
  10:     0x7fd6c1189eed - check::closure::check_expr_closure::hbce85e7beaf0ebd52zl
  11:     0x7fd6c11d360b - check::check_expr_with_unifier::h16314096699859592584
  12:     0x7fd6c11f998b - check::check_decl_initializer::h491ede37e45bce9e84r
  13:     0x7fd6c11f9a4d - check::check_decl_local::h1c782249285c9ae3m6r
  14:     0x7fd6c11f9c79 - check::check_stmt::h48bf6ea3f412b86bf8r
  15:     0x7fd6c11a91b3 - check::check_block_with_expected::h072b2c4702c43b1cjcs
  16:     0x7fd6c118bef4 - check::check_fn::h8218f9adb3734183iQn
  17:     0x7fd6c11a35ca - check::check_bare_fn::h3c567a2d1339f838RFn
  18:     0x7fd6c11a1523 - check::check_item_body::h8e17e6521c30131ay6n
  19:     0x7fd6c11a31e4 - check::check_item_types::h62e908b1d9f74b39oDn
  20:     0x7fd6c12609b8 - check_crate::h594ee0148d251222uZC
  21:     0x7fd6c1f1dc69 - driver::phase_3_run_analysis_passes::closure.15783
  22:     0x7fd6c1f1c633 - middle::ty::ctxt<'tcx>::create_and_enter::h349256048753845929
  23:     0x7fd6c1f17a17 - driver::phase_3_run_analysis_passes::h15521018079403107052
  24:     0x7fd6c1efa266 - driver::compile_input::hbf698b02349f7ce3Tba
  25:     0x7fd6c1fd3ed3 - run_compiler::hd724b5fef3441688y7b
  26:     0x7fd6c1fd18ae - boxed::F.FnBox<A>::call_box::h6609070342514802751
  27:     0x7fd6c1fd10f9 - rt::unwind::try::try_fn::h10774555836369096370
  28:     0x7fd6c1a3ed48 - rust_try_inner
  29:     0x7fd6c1a3ed35 - rust_try
  30:     0x7fd6c19b08a7 - rt::unwind::try::inner_try::hb0d7a3eb324339ceSJw
  31:     0x7fd6c1fd130b - boxed::F.FnBox<A>::call_box::h18179817771297192954
  32:     0x7fd6c19c3e71 - sys::thread::Thread::new::thread_start::hf8c7448e27294ed0PTv
  33:     0x7fd6bb60f353 - start_thread
  34:     0x7fd6c161ebfc - __clone
  35:                0x0 - <unknown>

**Comment by tksfz** [comment]
$ rustc --version
rustc 1.3.0-nightly (bf3c979ec 2015-06-30)

**Comment by tksfz** [comment]
Btw for some reason this seems to happen only on my  Arch Linux machine, and not on  my mac.

**Comment by tksfz** [comment]
This problem has gone away for me now.  It may have been from mixing versions?  It may have  gone away  after a  `cargo  clean`.

**Comment by frewsxcv** [comment]
It is still an issue on nightly according to the playpen:

http://is.gd/OCanBI

**Comment by tksfz** [comment]
You're right.  I must have been in the wrong project.

**Comment by jhasse** [comment]
I just ran into the same assertion (with both stable 1.1 and nightly 1.3), but with different code. Would it help if I try to create another minimal working example and post it here or a new bug report? This is my backtrace:

```
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'assertion failed: index.end <= self.len()', ../src/libcore\slice.rs:544

stack backtrace:
   1:         0x61dfa535 - sys::backtrace::write::h018e42c12f269f544Cs
   2:         0x61e038ac - rt::unwind::register::hc674956c97a716df1Cw
   3:         0x61dc57ff - rt::unwind::begin_unwind_inner::h662aa5119908cf48aAw
   4:         0x61dc617a - rt::unwind::begin_unwind_fmt::h01eb13496835025cgzw
   5:         0x61e032c3 - rust_begin_unwind
   6:         0x61e200a9 - panicking::panic_fmt::hbcf25944567f207319B
   7:         0x61e1a6f1 - panicking::panic::h93271eadbe8415b7y8B
   8:           0x795d3a - check::TupleArgumentsFlag...std..clone..Clone::clone::h605dce780ccf5dc9Ljq
   9:           0x755335 - check::FnCtxt<'a, 'tcx>::require_type_meets::h798960652a04997dgZo
  10:           0x7cc037 - collect::ast..Generics.GetTypeParameterBounds<'tcx>::get_type_parameter_bounds::ha042c13c7c6692a3xmx
  11:           0x7c3034 - collect::ast..Generics.GetTypeParameterBounds<'tcx>::get_type_parameter_bounds::ha042c13c7c6692a3xmx
  12:           0x7b4d08 - collect::AstConvRequest...std..clone..Clone::clone::h63a61bfae076fcfegWw
  13:           0x7bac23 - collect::AstConvRequest...std..clone..Clone::clone::h63a61bfae076fcfegWw
  14:           0x7b0332 - collect::collect_item_types::h8bacaf0c14501822JPw
  15:           0x7fca25 - check_crate::hac17c115800a24556WC
  16:         0x7106bcfb - driver::assign_node_ids_and_map::h80779d68a0b95aa24Da
  17:         0x7106a43d - driver::assign_node_ids_and_map::h80779d68a0b95aa24Da
  18:         0x71064ca7 - driver::assign_node_ids_and_map::h80779d68a0b95aa24Da
  19:         0x71042a66 - driver::compile_input::hdea87ef255adf358Tba
  20:         0x7112dc8d - run_compiler::h898d25887739e965y7b
  21:         0x7112b915 - run::he91bab0c68724632e7b
  22:         0x7112b259 - run::he91bab0c68724632e7b
  23:         0x61e3fedc - rust_try
  24:         0x61e3feb9 - rust_try
  25:         0x61ded605 - rt::unwind::try::inner_try::h75d613e781873d5a3vw
  26:         0x7112b417 - run::he91bab0c68724632e7b
  27:         0x61e0157e - sys::process::Command::cwd::hbe09b93cabba047cukv
  28:     0x7ffd5f6a13d2 - BaseThreadInitThunk
```

`cargo clean` didn't help.

**Comment by jhasse** [comment]
Okay here it is:

```rust
extern crate glium;

use glium::DisplayBuild::Facade;

fn main() {
    let a: Facade;
}
```

Unfortunately it has something to do with glium, so I guess this doesn't help much :/

**Comment by cjcole** [comment]
May be related, not sure: https://github.com/rust-lang/rust/issues/27602 (rustc 1.2.0 (082e47636 2015-08-03))

**Comment by arielb1** [comment]
minimized:

```Rust
use std::iter::IntoIterator::IntoIter;
fn main() {
    let x: IntoIter;
}
```
