### ISSUE TITLE
Do not error for unknown attributes at stage0

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#22964]
Makes PRs like #21824 painful

**Comment by Manishearth** [comment]
(I can mentor this, btw, but please ask first, I might have finished it since this is something we need)

**Comment by Manishearth** [comment]
The relevant code is [here](https://github.com/rust-lang/rust/blob/master/src/libsyntax/feature_gate.rs#L615). The `custom_attribute` gate should be within a `#[cfg(not(stage0))]` block.

**Comment by Manishearth** [comment]
This won't work. The correct fix is to use  `#![cfg_attr(stage0, feature(custom_attribute))]` on every crate

**Comment by awlnx** [comment]
any tests needed to be ran other than compilation?

**Comment by Manishearth** [comment]
You can run `make check-stage1-cfail check-stage1 rpass` if you want. This is something that's really only going to be verified when a snapshot gets made.

An easy way to test this is to just add a `#[foo]` somewhere in the libstd, and check that it compiles at stage0 but fails at stage1

**Comment by Manishearth** [comment]
This was fixed (https://github.com/rust-lang/rust/pull/23056)
