### ISSUE TITLE
Borrow checker prohibits iterating over map-returned array

### ISSUE THREAD

**Issue by ZoomRmc** [rust-lang/rust#22962]
I'm trying to iterate over a range, return an array and iterate over its elements.
I was going to iterate over returned values as ranges, but sadly I didn't even get to that part.

This doesn't work, but to me it looks like it should:
```Rust
use std::iter::*;

fn some_arr(x: usize) -> [usize; 3] { [x, x * 2, x * 3] }

fn main() {
    let ans = (1..100).map(|x| some_arr(x)).flat_map(|x| x.iter()).count();
    println!("{}" , ans);
}
```

```
<anon>:6:58: 6:59 error: `x` does not live long enough
<anon>:6     let ans = (1..100).map(|x| some_arr(x)).flat_map(|x| x.iter()).count();
                                                                  ^
<anon>:6:15: 6:75 note: reference must be valid for the method call at 6:14...
<anon>:6     let ans = (1..100).map(|x| some_arr(x)).flat_map(|x| x.iter()).count();
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<anon>:6:58: 6:66 note: ...but borrowed value is only valid for the block at 6:57
<anon>:6     let ans = (1..100).map(|x| some_arr(x)).flat_map(|x| x.iter()).count();
                                                                  ^~~~~~~~
error: aborting due to previous error
```

Tried it on alpha.2, today's nightly and playpen.

PS: ebfull on rust IRC channel kindly suggested a hack, which is using `.collect::<Vec<_>>()` on a map and then iterating over it.

## Meta:
```
rustc 1.0.0-alpha.2 (522d09dfe 2015-02-19) (built 2015-02-19)
binary: rustc
commit-hash: 522d09dfecbeca1595f25ac58c6d0178bbd21d7d
commit-date: 2015-02-19
build-date: 2015-02-19
host: x86_64-pc-windows-gnu
release: 1.0.0-alpha.2
-----------------------------------------------------------
rustc 1.0.0-nightly (890293655 2015-02-28) (built 2015-03-01)
binary: rustc
commit-hash: 890293655251c372ea99694c0c9f0795e2663286
commit-date: 2015-02-28
build-date: 2015-03-01
host: x86_64-pc-windows-gnu
release: 1.0.0-nightly
```

**Comment by alexcrichton** [comment]
This is actually working as intended due to the fact that the argument `x` in the `flat_map` closure only lives for the duration of that closure, but the `flat_map` operation requires it to live until the later call to `.count()`. This is normally where `.into_iter` would be recommended, but unfortunately fixed-size arrays do not implement `into_iter` (unlike `Vec`, for example).

Due to this working as intneded, however, I'm going to close as not a bug. Thanks for the report though!

**Comment by ZoomRmc** [comment]
Thanks for the clarification!
I think the documentation would benefit of bringing an attention to this detail in some way.

At the moment my code looks like this:
```Rust
        (1..100).map(|x| some_arr(x)).collect::<Vec<_>>().iter()
        .flat_map(|x| x.iter().flat_map(|&x| (0..x))
        .zip( ... ).filter( ... ).count();
```
The idea is to get one big iterator to zip it to the other one.
Let's say the array elements were some big structs, wouldn't the collect().iter() bit hurt the performance?

**Comment by alexcrichton** [comment]
Yes in this case you may want to specialize the return value of `some_arr` function to either return a `Vec` directly or return your own custom iterator if performance is a concern.
