### ISSUE TITLE
Investigate activating the IRCE LLVM pass

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#22987]
["Inductive range check elimination"](http://llvm.org/docs/doxygen/html/InductiveRangeCheckElimination_8cpp_source.html) may help remove bounds checks inside loops. That said, the extra compilation time required to run the pass may not be worth it (since our iterators work well).

http://llvm.org/docs/Frontend/PerformanceTips.html

**Comment by gnzlbg** [comment]
+1

**Comment by brson** [comment]
Closing old wishlist.
