### ISSUE TITLE
Mark outdated/archived documentation as such

### ISSUE THREAD

**Issue by phaylon** [rust-lang/rust#22981]
In a different language forum where Rust was discussed, I saw a link to ·[this outdated 0.6 manual](http://static.rust-lang.org/doc/0.6/tutorial-borrowed-ptr.html).

I'd propose that old documentation receives an out-of-date marker at the top (or at the floating version marker to the right). It might also help to make these non-findable via direct google search, but I'm unsure if this would be a correct strategy.

I'm not sure if it would make sense to have the marker for all outdated information. I do believe that it would be helpful to give such a notice for at least the 0.* timeline of documentation.

**Comment by steveklabnik** [comment]
We can't really do this, as all those old docs are already out there, and aren't change-able. And, post 1.0, this will be significantly less of a problem.

One thing we can do is note the build date in the output itself, but we have a rustdoc issue open for this already, so I'm going to close this one. Thank you though!

**Comment by liigo** [comment]
I don't think they're not change-able.

**Comment by phaylon** [comment]
@steveklabnik How are they unchangeable? They are hosted on rust-lang.org.

**Comment by steveklabnik** [comment]
Many of the problematic ones are not. Plus, Rustdoc is more than just for the compiler itself. Finally, changing the previous docs would involve making a new release because the SHA of the output would change.

**Comment by phaylon** [comment]
@steveklabnik I still don't understand.

This is about old (0.6) documentation being hosted on static.rust-lang.org directly, side-by-side with more current documentation on doc.rust-lang.org, not about anything hosted elsewhere (I'm aware of the MIT situation). People are finding outdated/archived documentation on the official, canonical Rust website, and have no notice that it is very out of date.

So I'm not quite sure how SHA's or rustdoc come into this.

**Comment by huonw** [comment]
We could `sed` in a small header (e.g. a piece of javascript) or modify the existing shared JS and manually reupload the online docs. Any docs in the tarballs can/should stay as they are. (Alternatively, we just could remove the outdated docs.)
