### ISSUE TITLE
Type inference for vector of functions

### ISSUE THREAD

**Issue by yann-ledu** [rust-lang/rust#22996]
```rust
#![feature(box_syntax)]

fn main()
{
    fn h(x:i32) -> i32 {3*x};
    fn g(x:i32) -> i32 {5*x + 3};

    // That works with explicit typing
    let mut vf:Vec<Box<Fn(i32)->i32>>=vec![];
    vf.push(box h);
    vf.push(box g);

    // The following fails at the second push : type mismatch looks strange
    let mut vfnfer = vec![];
    vfnfer.push(box h);
    vfnfer.push(box g);
}
```

**Comment by edwardxie** [comment]
Box need prototype.
```
#![feature(box_syntax)]
use std::any::Any;
fn main()
{
    fn h(x:i32) -> i32 {3*x};
    fn g(x:i32) -> i32 {5*x + 3};

    // That works with explicit typing
    let mut vf:Vec<Box<Fn(i32)->i32>>=vec![];
    vf.push(box h);
    vf.push(box g);
    println!("3X={:?} 5X+3={:?}", vf[0](9), vf[1](3));

    // The following fails at the second push : type mismatch looks strange
    let mut vfnfer:Vec<Box<Any>> = vec![];
    vfnfer.push(box h);
    vfnfer.push(box g);
    println!("3X={:?} 5X+3={:?}", vf[0](9), vf[1](3));
}
```
If that's all you need..

**Comment by yann-ledu** [comment]
Ok, but I think you meant to put vnfer in the last line, and not vf, and then it doesn't work. Apparently, Any doesn't get specialized to Fn. I can just carry on putting other stuff, like boxed integers. I didn't know about Any, thanks.

**Comment by huonw** [comment]
This would require being able to infer a *unique* "coercion supertype" of a set of things: `box h` has some type `T` and `box g` has some type `U`. Seeing the two pushes, the compiler would see that the types don't match and then would have to try to compute some type that both `T` and `U` can be coerced to, e.g. for this case `Box<Fn(i32) -> i32>`. However, as @edwardxie demonstrates, the types in this case can also be coerced to `Box<Any>`, so the compiler would have to some how decide between those two trait objects, but there's not really a good way to decide that.

That is, this feature is extremely unlikely to happen, even if it could be done efficiently (I'm lead to believe that this sort of "supertype" inference is expensive/impossible-in-general), so I'm closing, but thanks for filing anyway!

NB. One can avoid a full annotation by casting one of the `box ...`'s, e.g. `vfnfer.push(box h as Box<Fn(i32) -> i32>)`.
