### ISSUE TITLE
all generic function's instance share ONE static variable??

### ISSUE THREAD

**Issue by egmkang** [rust-lang/rust#22991]
```rust
pub fn instance<T: Default>() -> &'static mut T {
  static ONCE: Once = ONCE_INIT;
  static mut ptr: *mut u8 = 0 as *mut u8;
  ONCE.call_once(|| {
    unsafe {
      let value_ptr = allocate(size_of::<T>(), 1) as *mut T;
      write(value_ptr, Default::default());
      ptr = value_ptr.offset(0) as *mut u8;

      at_exit(|| {
        deallocate(ptr, size_of::<T>(), 1);
        ptr = 0 as *mut u8;
      });        
    }            
  });            

  unsafe { &mut *(ptr.offset(0) as *mut T) }
}
```

in this sample, `instance<f32>::ONCE` and `instance<f32>::ONCE` share one Once's instance.
how could this thing happen?
if this is a feature, what's difference between writing static variables outside?

**Comment by lifthrasiir** [comment]
I'm not sure if this is an actual bug or not (possibly a doc issue), but:

> if this is a feature, what's difference between writing static variables outside?

Only the reduced visibility.

**Comment by alexcrichton** [comment]
This is actually currently working as intended. Sub-items of functions do not have access to generic parameters, leading to this implementation. For example, this is invalid:

```rust
fn foo<T>() {
    fn bar(t: T) {} // invalid
    static FOO: T = ...; // invalid
    // etc.
}
```

**Comment by bjz** [comment]
@alexcrichton Would it be possible for generic parameters to be available in sub-items in the future? It is very useful to have.

**Comment by eddyb** [comment]
@bjz Presumably associated `static` items could handle this - but it might be difficult to ensure multiple instantiations of the same associated `static`, with the same `impl` type parameters/`Self`, will always point to the same memory, even in sibling crates.

**Comment by alexcrichton** [comment]
@bjz possibly, but unfortunately it would be a backwards-incompatible change. I believe there are functions in the standard library at least which require that generic functions all get the same `static` (not an instance-per-instantiation)
