### ISSUE TITLE
Rename one of dead-code and unreachable-code lints

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#23007]

**Comment by iKevinY** [comment]
I'd like to take a shot at this. Doing a quick grep shows that `dead_code` appears a lot more frequently than `unreachable_code`, so it seems as though `unreachable-code` should be renamed. Does resolving this issue just entail converting all instances of `unreachable-code` lints into `dead-code` lints?

**Comment by pnkfelix** [comment]
subbug of #21761
