### ISSUE TITLE
make -j N fail

### ISSUE THREAD

**Issue by laijs** [rust-lang/rust#23020]
I tried to speed up the compiling via ```make -j N```, it failed and reported that some dependece didn't exist. The missing dependece files seems to be the files that would be produced if we just use the non-parallel  ```make```. It seems the Makefile does't declare the dependence well.

And sometimes it succed but false positive, the error will ocurr when ```make install```

**Comment by huonw** [comment]
What `N` did you use?

Also, it would be convenient if you could paste the log of the compilation to make diagnosing the problem easier; thanks!

**Comment by laijs** [comment]
N = 3

**Comment by pnkfelix** [comment]
cc me

**Comment by Gankro** [comment]
Isn't the syntax `make -jN` with no space?

**Comment by steveklabnik** [comment]
@Gankro iirc, either works

**Comment by shepmaster** [comment]
FWIW, I just did a `make clean && make -j7` against 3b3bb0e682c2d252e9f62dd9df5cff9552af91ad and compilation succeeded. I have noticed that if you maintain a checkout and try to just do `make -j7` after updating the code, the build will occasionally fail (~ 2-3 times over months). A `make clean` "solves" the issue.

**Comment by laijs** [comment]
it seems work now
