### ISSUE TITLE
Rustdoc memory usage needs to be improved

### ISSUE THREAD

**Issue by retep998** [rust-lang/rust#23022]
While building docs for a project which just happens to use winapi, I noticed a huge spike in memory usage.
![](http://puu.sh/glM2Q/5af5d38099.png)
The same spike does not occur for a regular build, only for building docs.

This command in particular causes the huge spike:
`rustdoc C:/msys64/home/Peter/.cargo/registry/src/github.com-1ecc6299db9ec823/winapi-0.1.14/src/lib.rs -o C:/msys64/home/Peter/wio-rs/target/doc --crate-name winapi -L dependency=C:/msys64/home/Peter/wio-rs/target/deps -L dependency=C:/msys64/home/Peter/wio-rs/target/deps --extern libc=C:/msys64/home/Peter/wio-rs/target/deps/liblibc-8d21de95f4de7169.rlib`

Surely there must be some low hanging fruit here we can use to improve memory usage.

**Comment by tomjakubowski** [comment]
If someone could provide some pointers for profiling memory usage in Rust programs I'd be more than happy to look at this, although unfortunately I probably can't look at this specific case because I don't have a Windows machine on which to build winapi!

**Comment by retep998** [comment]
Winapi theoretically can build on non Windows platforms since it doesn't actually link to anything.

**Comment by huonw** [comment]
It'd be great if someone could confirm this is still happening and/or throw [massif](http://valgrind.org/docs/manual/ms-manual.html) (or similar) at it to try to get some more details.

**Comment by retep998** [comment]
There is no longer the huge spike that was observed before.
![](http://i.imgur.com/3VpjjYg.png)
It now has a peak of about 800MB which is certainly more reasonable.

**Comment by steveklabnik** [comment]
Okay! Obviously, improving this would be good, but since the specific behavior is ogne, let's close this.

If anyone wants to improve memory usage even further, please feel free!
