### ISSUE TITLE
Add missing File stats for std::fs::Metadata

### ISSUE THREAD

**Issue by guruverse** [rust-lang/rust#23023]
Currently, the Metadata type does not support checking for other different kinds of files identified by a call to stat, like symlinks (softlinks?), block devices, and named pipes, as shown from the [std::old_io::FileType](http://doc.rust-lang.org/std/old_io/enum.FileType.html) enum and getting the file stats, like uid, gid, rdev, etc, like with [std::old_io::UnstableFileStat](http://doc.rust-lang.org/std/old_io/struct.UnstableFileStat.html).

**Comment by nagisa** [comment]
Sadly, the `std::fs` API has to be cross platform, and Windows does not expose most of the information you listed meaningfully.

You’ll have to use unix specific functions when these come around to get things like uid, gid, nlink, mode etc.

**Comment by guruverse** [comment]
Could there be a unix trait extension for exposing such stats?

**Comment by nagisa** [comment]
It is very likely there will be one. We just didn't even start working on
the platform specific apis yet.
2015/03/04 12:22 "guruverse" <notifications@github.com>:

**Comment by alexcrichton** [comment]
Thanks for the issue! I'm going to start collecting possible `std::fs` extensions into a [tracking issue in the RFC repo](https://github.com/rust-lang/rfcs/issues/939) to make sure we keep everything in one place. I made sure to include this in there though!
