### ISSUE TITLE
ICE - tried to get overflow intrinsic for non-int type

### ISSUE THREAD

**Issue by Jojoshua** [rust-lang/rust#23037]
thread 'rustc' panicked at 'tried to get overflow intrinsic for non-int type', C
:\bot\slave\nightly-dist-rustc-win-64\build\src\librustc_trans\trans\expr.rs:235
2

Here is the code

```rust
#![feature(core)]

use std::simd::i16x8;

fn main() {
    // create simd vectors
    let x = i16x8(1, 2, 3, 4,1, 2, 3, 4);
    let y = i16x8(4, 3, 2, 1,1, 2, 3, 4);

    // simd product
    let z = x * y;

    // like any struct, the simd vector can be destructured using `let`
    let i16x8(a, b, c, d,e,f,g,h) = z;

    println!("{:?}", (a, b, c, d,e,f,g,h));
}
```

**Comment by fhartwig** [comment]
I get the same error when trying to compile rust-crypto (after some fixes, see https://github.com/fhartwig/rust-crypto/tree/rustup) with the current nightly (`rustc 1.0.0-nightly (fed12499e 2015-03-03) (built 2015-03-03)`)

**Comment by dragan** [comment]
I can confirm the same error when compiling rust-crypto.

```terminal
$ rustc -v --version

  rustc 1.0.0-nightly (3b3bb0e68 2015-03-04) (built 2015-03-04)
  binary: rustc
  commit-hash: 3b3bb0e682c2d252e9f62dd9df5cff9552af91ad
  commit-date: 2015-03-04
  build-date: 2015-03-04
  host: x86_64-apple-darwin
  release: 1.0.0-nightly
```

Backtrace:

```terminal
   Compiling rustc-serialize v0.3.1
   Compiling libc v0.1.2
   Compiling gcc v0.3.1
   Compiling log v0.2.5
   Compiling rand v0.1.4
   Compiling time v0.1.19
   Compiling rust-crypto v0.2.19 (file:///Users/dragan/Code/OpenSource/RustCrypto)
thread 'rustc' panicked at 'tried to get overflow intrinsic for non-int type', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/librustc_trans/trans/expr.rs:2352

stack backtrace:
   1:        0x1113fdb52 - sys::backtrace::write::h6b0889bc971c1ad3IDA
   2:        0x11142c844 - panicking::on_panic::h0fcd1d74630df38dKsJ
   3:        0x11134ac67 - rt::unwind::begin_unwind_inner::h56b969a14fc61916gbJ
   4:        0x10de4185f - rt::unwind::begin_unwind::h5082286894643109956
   5:        0x10df219d1 - trans::expr::with_overflow_check::hd6793b92ae2aee44ylk
   6:        0x10df1ff05 - trans::expr::trans_eager_binop::h416c33bf491e0717upj
   7:        0x10df03e5f - trans::expr::trans_assign_op::hc0d59ae1da070adeDYj
   8:        0x10deec30f - trans::expr::trans_rvalue_stmt_unadjusted::h450cf67b08184907jui
   9:        0x10de96086 - trans::expr::trans_into::h4a29f680db4b3526znh
  10:        0x10de94fa0 - trans::controlflow::trans_stmt_semi::h318c4f3f34b9c533o4d
  11:        0x10de96ace - trans::controlflow::trans_block::h26a308528bb95051b5d
  12:        0x10dee8050 - trans::expr::trans_rvalue_dps_unadjusted::hca2c07ae951484c14zi
  13:        0x10de95f59 - trans::expr::trans_into::h4a29f680db4b3526znh
  14:        0x10de94fa0 - trans::controlflow::trans_stmt_semi::h318c4f3f34b9c533o4d
  15:        0x10de96ace - trans::controlflow::trans_block::h26a308528bb95051b5d
  16:        0x10dee8050 - trans::expr::trans_rvalue_dps_unadjusted::hca2c07ae951484c14zi
  17:        0x10de95f59 - trans::expr::trans_into::h4a29f680db4b3526znh
  18:        0x10df974e0 - trans::_match::trans_match_inner::he768a1b2ccde6888CIw
  19:        0x10dee7fe3 - trans::expr::trans_rvalue_dps_unadjusted::hca2c07ae951484c14zi
  20:        0x10de95f59 - trans::expr::trans_into::h4a29f680db4b3526znh
  21:        0x10de96e29 - trans::controlflow::trans_block::h26a308528bb95051b5d
  22:        0x10deebf9e - trans::expr::trans_rvalue_stmt_unadjusted::h450cf67b08184907jui
  23:        0x10de96086 - trans::expr::trans_into::h4a29f680db4b3526znh
  24:        0x10df974e0 - trans::_match::trans_match_inner::he768a1b2ccde6888CIw
  25:        0x10dee7fe3 - trans::expr::trans_rvalue_dps_unadjusted::hca2c07ae951484c14zi
  26:        0x10de95f59 - trans::expr::trans_into::h4a29f680db4b3526znh
  27:        0x10dfafd26 - trans::_match::mk_binding_alloca::h3448676421097350985
  28:        0x10de95280 - trans::base::init_local::h08a9fcff749ad013czs
  29:        0x10de96b02 - trans::controlflow::trans_block::h26a308528bb95051b5d
  30:        0x10dee8050 - trans::expr::trans_rvalue_dps_unadjusted::hca2c07ae951484c14zi
  31:        0x10de95f59 - trans::expr::trans_into::h4a29f680db4b3526znh
  32:        0x10de94fa0 - trans::controlflow::trans_stmt_semi::h318c4f3f34b9c533o4d
  33:        0x10de96ace - trans::controlflow::trans_block::h26a308528bb95051b5d
  34:        0x10df75da9 - trans::base::trans_closure::h1e78b4450eb13a03Kkt
  35:        0x10de7e645 - trans::base::trans_fn::h31c9353b85ff9dd9Dvt
  36:        0x10de7aaa6 - trans::base::trans_item::h8ce277cc13b040a3vTt
  37:        0x10de7a8a7 - trans::base::trans_item::h8ce277cc13b040a3vTt
  38:        0x10df7eecb - trans::base::trans_crate::hb69c466e59630a14GPu
  39:        0x10d8bbec7 - driver::phase_4_translate_to_llvm::he4e045cdc3897b4crNa
  40:        0x10d8977f2 - driver::compile_input::h25d96a14ec26932cIba
  41:        0x10d96972e - run_compiler::h15c3ea085a111a6fH5b
  42:        0x10d966ac7 - thunk::F.Invoke<A, R>::invoke::h11905936354613679413
  43:        0x10d96560f - rt::unwind::try::try_fn::h4025213131938170097
  44:        0x1114a9628 - rust_try_inner
  45:        0x1114a9615 - rust_try
  46:        0x10d965e48 - thunk::F.Invoke<A, R>::invoke::h13725635537516470714
  47:        0x1114150a2 - sys::thread::thread_start::h1120d6d2e105321012E
  48:     0x7fff8368d898 - _pthread_body
  49:     0x7fff8368d729 - _pthread_start
```

**Comment by parbo** [comment]
I get the same error for rust-crypto on linux (x86_64):

$ RUST_BACKTRACE=1 cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling log v0.2.5
   Compiling rustc-serialize v0.3.1
   Compiling libc v0.1.2
   Compiling gcc v0.3.1
   Compiling rand v0.1.4
   Compiling time v0.1.19
   Compiling rust-crypto v0.2.19 (file:///home/parbo/src/rust-crypto)
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'tried to get overflow intrinsic for non-int type', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_trans/trans/expr.rs:2352

stack backtrace:
   1:     0x7fa61457bf1f - sys::backtrace::write::hf79a3da4fdecb8a0OBA
   2:     0x7fa6145a6c32 - panicking::on_panic::h9f64f4c69e19f194hHJ
   3:     0x7fa6144dbeda - rt::unwind::begin_unwind_inner::h37f4496c980fe936knJ
   4:     0x7fa613b7eddc - rt::unwind::begin_unwind::h265200097513870162
   5:     0x7fa613c55ba6 - trans::expr::with_overflow_check::hb51eee44b3064a1aylk
   6:     0x7fa613c5423a - trans::expr::trans_eager_binop::hd0a96011514b6b88upj
   7:     0x7fa613c38c2a - trans::expr::trans_assign_op::h2b754fac4ce95c82DYj
   8:     0x7fa613c21e5c - trans::expr::trans_rvalue_stmt_unadjusted::ha3dc197598d6fe14jui
   9:     0x7fa613bcf510 - trans::expr::trans_into::h95c6d2681fdd2548znh
  10:     0x7fa613bce594 - trans::controlflow::trans_stmt_semi::h3c27cfa3f0150db6o4d
  11:     0x7fa613bcfed0 - trans::controlflow::trans_block::h3e86dfa8c58560e6b5d
  12:     0x7fa613c1df7e - trans::expr::trans_rvalue_dps_unadjusted::hd47de7ac66e018254zi
  13:     0x7fa613bcf3f6 - trans::expr::trans_into::h95c6d2681fdd2548znh
  14:     0x7fa613bce594 - trans::controlflow::trans_stmt_semi::h3c27cfa3f0150db6o4d
  15:     0x7fa613bcfed0 - trans::controlflow::trans_block::h3e86dfa8c58560e6b5d
  16:     0x7fa613c1df7e - trans::expr::trans_rvalue_dps_unadjusted::hd47de7ac66e018254zi
  17:     0x7fa613bcf3f6 - trans::expr::trans_into::h95c6d2681fdd2548znh
  18:     0x7fa613cc7df0 - trans::_match::trans_match_inner::hed8323987dcd430bCIw
  19:     0x7fa613c1df22 - trans::expr::trans_rvalue_dps_unadjusted::hd47de7ac66e018254zi
  20:     0x7fa613bcf3f6 - trans::expr::trans_into::h95c6d2681fdd2548znh
  21:     0x7fa613bd0227 - trans::controlflow::trans_block::h3e86dfa8c58560e6b5d
  22:     0x7fa613c21b19 - trans::expr::trans_rvalue_stmt_unadjusted::ha3dc197598d6fe14jui
  23:     0x7fa613bcf510 - trans::expr::trans_into::h95c6d2681fdd2548znh
  24:     0x7fa613cc7df0 - trans::_match::trans_match_inner::hed8323987dcd430bCIw
  25:     0x7fa613c1df22 - trans::expr::trans_rvalue_dps_unadjusted::hd47de7ac66e018254zi
  26:     0x7fa613bcf3f6 - trans::expr::trans_into::h95c6d2681fdd2548znh
  27:     0x7fa613cdf967 - trans::_match::mk_binding_alloca::h13035368140960659810
  28:     0x7fa613bce7fd - trans::base::init_local::h1e7c96bb7077440dczs
  29:     0x7fa613bcff02 - trans::controlflow::trans_block::h3e86dfa8c58560e6b5d
  30:     0x7fa613c1df7e - trans::expr::trans_rvalue_dps_unadjusted::hd47de7ac66e018254zi
  31:     0x7fa613bcf3f6 - trans::expr::trans_into::h95c6d2681fdd2548znh
  32:     0x7fa613bce594 - trans::controlflow::trans_stmt_semi::h3c27cfa3f0150db6o4d
  33:     0x7fa613bcfed0 - trans::controlflow::trans_block::h3e86dfa8c58560e6b5d
  34:     0x7fa613ca7821 - trans::base::trans_closure::hab3cc3c679d5ff23Kkt
  35:     0x7fa613bb8b08 - trans::base::trans_fn::he0569b8eb832adf9Dvt
  36:     0x7fa613bb5241 - trans::base::trans_item::h48fc370b7d259ac7vTt
  37:     0x7fa613bb5078 - trans::base::trans_item::h48fc370b7d259ac7vTt
  38:     0x7fa613cb07ec - trans::base::trans_crate::hc92be67ede893c70GPu
  39:     0x7fa614bb4e83 - driver::phase_4_translate_to_llvm::h9904f5d5fc3fb761rNa
  40:     0x7fa614b9083f - driver::compile_input::h3913ff7013f0c056Iba
  41:     0x7fa614c58cb7 - run_compiler::h28a4446bae1034e7H5b
  42:     0x7fa614c56829 - thunk::F.Invoke<A, R>::invoke::h6503055919709693733
  43:     0x7fa614c554a0 - rt::unwind::try::try_fn::h1384674024000742916
  44:     0x7fa614616de8 - rust_try_inner
  45:     0x7fa614616dd5 - rust_try
  46:     0x7fa614c55c3f - thunk::F.Invoke<A, R>::invoke::h5780663349966142752
  47:     0x7fa614591965 - sys::thread::thread_start::h4ab695857833a5dar8E
  48:     0x7fa60e3ed0a4 - start_thread
  49:     0x7fa61414ccfc - __clone
  50:                0x0 - <unknown>

Could not compile `rust-crypto`.

To learn more, run the command again with --verbose.

**Comment by GGist** [comment]
Interestingly enough I did not get this error when compiling with --cfg ndebug which is the flag that cargo adds when building in release mode. Maybe this bit of information would be useful for whoever decides to track down the bug.

Here is my compiler version as well as the error I get when compiling without the flag mentioned above:

$ rustc -v --version
rustc 1.0.0-nightly (fed12499e 2015-03-03) (built 2015-03-04)
binary: rustc
commit-hash: fed12499e7d91f9cdfba5833e34d20e8fd19b898
commit-date: 2015-03-03
build-date: 2015-03-04
host: i686-pc-windows-gnu
release: 1.0.0-nightly

$ RUST_BACKTRACE=1 cargo build
   Compiling rust-crypto v0.2.18
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/m
aster/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'tried to get overflow intrinsic for non-int type', C
:\bot\slave\nightly-dist-rustc-win-32\build\src\librustc_trans\trans\expr.rs:235
2

stack backtrace:
   1: 0x62f7fa91 - rt::unwind::register::hf961d44cecb421c3HnJ
   2: 0x62ec3b21 - rt::unwind::begin_unwind_inner::h95fef3929cdc9be86kJ
   3:  0x1283261 - back::link::build_link_meta::hf27c1d611f7552cfyfa
   4:  0x13634c8 - trans::cleanup::FunctionContext<'blk, 'tcx>.CleanupMethods<'blk, 'tcx>::schedule_free_value::h4881d8439dae6434waK
   5:  0x1361b26 - trans::cleanup::FunctionContext<'blk, 'tcx>.CleanupMethods<'blk, 'tcx>::schedule_free_value::h4881d8439dae6434waK
   6:  0x1346a88 - trans::context::CrateContext<'b, 'tcx>::get_intrinsic::hf3b9d67a5f358fbe42l
   7:  0x132f6c2 - trans::common::ExprOrMethodCall...std..cmp..PartialEq::ne::h997d21adc0a4176bfBl
   8:  0x12d8b64 - trans::cleanup::FunctionContext<'blk, 'tcx>.CleanupMethods<'blk, 'tcx>::pop_and_trans_ast_cleanup_scope::h704a2640d6c32d12MRJ
   9:  0x12d7bf1 - trans::cleanup::FunctionContext<'blk, 'tcx>.CleanupMethods<'blk, 'tcx>::push_ast_cleanup_scope::h56e56ba9c5ce4bb38HJ
  10:  0x12d95a4 - trans::cleanup::FunctionContext<'blk, 'tcx>.CleanupMethods<'blk, 'tcx>::pop_and_trans_ast_cleanup_scope::h704a2640d6c32d12MRJ
  11:  0x132b483 - trans::common::ExprOrMethodCall...std..cmp..PartialEq::ne::h997d21adc0a4176bfBl
  12:  0x12d8a21 - trans::cleanup::FunctionContext<'blk, 'tcx>.CleanupMethods<'blk, 'tcx>::pop_and_trans_ast_cleanup_scope::h704a2640d6c32d12MRJ
  13:  0x12d7bf1 - trans::cleanup::FunctionContext<'blk, 'tcx>.CleanupMethods<'blk, 'tcx>::push_ast_cleanup_scope::h56e56ba9c5ce4bb38HJ
  14:  0x12d95a4 - trans::cleanup::FunctionContext<'blk, 'tcx>.CleanupMethods<'blk, 'tcx>::pop_and_trans_ast_cleanup_scope::h704a2640d6c32d12MRJ
  15:  0x132b483 - trans::common::ExprOrMethodCall...std..cmp..PartialEq::ne::h997d21adc0a4176bfBl
  16:  0x12d8a21 - trans::cleanup::FunctionContext<'blk, 'tcx>.CleanupMethods<'blk, 'tcx>::pop_and_trans_ast_cleanup_scope::h704a2640d6c32d12MRJ
  17:  0x13d7455 - trans::cleanup::FunctionContext<'blk, 'tcx>.CleanupMethods<'blk, 'tcx>::schedule_drop_and_zero_mem::h92034a36b8e01bdaI5J
  18:  0x132b430 - trans::common::ExprOrMethodCall...std..cmp..PartialEq::ne::h997d21adc0a4176bfBl
  19:  0x12d8a21 - trans::cleanup::FunctionContext<'blk, 'tcx>.CleanupMethods<'blk, 'tcx>::pop_and_trans_ast_cleanup_scope::h704a2640d6c32d12MRJ
  20:  0x12d98fb - trans::cleanup::FunctionContext<'blk, 'tcx>.CleanupMethods<'blk, 'tcx>::pop_and_trans_ast_cleanup_scope::h704a2640d6c32d12MRJ
  21:  0x132f31e - trans::common::ExprOrMethodCall...std..cmp..PartialEq::ne::h997d21adc0a4176bfBl
  22:  0x12d8b64 - trans::cleanup::FunctionContext<'blk, 'tcx>.CleanupMethods<'blk, 'tcx>::pop_and_trans_ast_cleanup_scope::h704a2640d6c32d12MRJ
  23:  0x13d7455 - trans::cleanup::FunctionContext<'blk, 'tcx>.CleanupMethods<'blk, 'tcx>::schedule_drop_and_zero_mem::h92034a36b8e01bdaI5J
  24:  0x132b430 - trans::common::ExprOrMethodCall...std..cmp..PartialEq::ne::h997d21adc0a4176bfBl
  25:  0x12d8a21 - trans::cleanup::FunctionContext<'blk, 'tcx>.CleanupMethods<'blk, 'tcx>::pop_and_trans_ast_cleanup_scope::h704a2640d6c32d12MRJ
  26:  0x13ee5b4 - trans::_match::ReassignmentChecker.euv..Delegate<'tcx>::mutate::ha6d1de296429ca37DEw
  27:  0x12d7e36 - trans::cleanup::FunctionContext<'blk, 'tcx>.CleanupMethods<'blk, 'tcx>::push_ast_cleanup_scope::h56e56ba9c5ce4bb38HJ
  28:  0x12d95ce - trans::cleanup::FunctionContext<'blk, 'tcx>.CleanupMethods<'blk, 'tcx>::pop_and_trans_ast_cleanup_scope::h704a2640d6c32d12MRJ
  29:  0x132b483 - trans::common::ExprOrMethodCall...std..cmp..PartialEq::ne::h997d21adc0a4176bfBl
  30:  0x12d8a21 - trans::cleanup::FunctionContext<'blk, 'tcx>.CleanupMethods<'blk, 'tcx>::pop_and_trans_ast_cleanup_scope::h704a2640d6c32d12MRJ
  31:  0x12d7bf1 - trans::cleanup::FunctionContext<'blk, 'tcx>.CleanupMethods<'blk, 'tcx>::push_ast_cleanup_scope::h56e56ba9c5ce4bb38HJ
  32:  0x12d95a4 - trans::cleanup::FunctionContext<'blk, 'tcx>.CleanupMethods<'blk, 'tcx>::pop_and_trans_ast_cleanup_scope::h704a2640d6c32d12MRJ
  33:  0x13b5b23 - trans::base::FindNestedReturn.Visitor<'v>::visit_expr::h9f1860022dbd7942lRs
  34:  0x12c0cfa - trans::context::CrateContext<'b, 'tcx>::sess::hee598b5cb4d3ab0ba2l
  35:  0x12bcbec - trans::context::CrateContext<'b, 'tcx>::stats::h16c51d851e9ec2eeKdm
  36:  0x12bcd93 - trans::context::CrateContext<'b, 'tcx>::stats::h16c51d851e9ec2eeKdm
  37:  0x13be867 - trans::base::trans_crate::h5628a05b9c20115a7Pu
  38: 0x6b7e9e43 - driver::phase_4_translate_to_llvm::hcbcd36709ec10694rNa
  39: 0x6b7c2682 - driver::compile_input::h27b14912ffbdd5b6Iba
  40: 0x6b8917ee - run_compiler::h7021284f6d62ba0cF5b
  41: 0x6b88efa7 - run::ha399a085586dc2e2l5b
  42: 0x6b88dac6 - run::ha399a085586dc2e2l5b
  43: 0x62fb553c - rust_try
  44: 0x62f6ec73 - sys::tcp::TcpListener::bind::hf078d41e5f2e7ed48RE
  45: 0x75dbee1c - BaseThreadInitThunk
  46: 0x775b37eb - RtlInitializeExceptionChain

Could not compile `rust-crypto`.

To learn more, run the command again with --verbose.

**Comment by pnkfelix** [comment]
The arithmetic overflow checking is only turned on for debug builds, so I am not surprised that `--cfg ndebug` affects reproducibility here.

**Comment by pnkfelix** [comment]
(anyway, I will try to find some time to address this.  not 100% sure what our story is for mixing overflow checking with simd ... seems like simd values should be implicitly wrapping-arithmetic...)

**Comment by pnkfelix** [comment]
(also, are we really making `simd` part of just the `core` feature?  It strikes me as something that deserved a more specific feature gate, if you ask me...)

**Comment by freebroccolo** [comment]
cc me
