### ISSUE TITLE
libcore docs mention non-existing "librlibc"

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#23059]
The libcore/lib.rs file says

```
//! * `memcpy`, `memcmp`, `memset` - These are core memory routines which are
//!   often generated by LLVM. Additionally, this library can make explicit
//!   calls to these functions. Their signatures are the same as found in C.
//!   These functions are often provided by the system libc, but can also be
//!   provided by `librlibc` which is distributed with the standard rust
//!   distribution.
```

However, `find -iname "*rlibc*"` yields no result, both in the rust source folder and in the distributed tarball. So the part about this library being distributed with the standard distribution does not seem to apply anymore.

**Comment by huonw** [comment]
Nice catch! The docs should be updated to point to https://crates.io/crates/rlibc itstead.
