### ISSUE TITLE
Rustdoc improperly showing `pub use ... as` functions

### ISSUE THREAD

**Issue by theemathas** [rust-lang/rust#23054]
The documentation of [std::ptr](http://doc.rust-lang.org/nightly/std/ptr/index.html#functions) displays `copy_memory` and `copy_nonoverlapping_memory` two times each, once labelled as deprecated, and once labelled as stable.

Both the links of `copy_memory` leads to a [deprecated function](http://doc.rust-lang.org/nightly/std/ptr/fn.copy_memory.html). Hovering over the purple bar tells me that the function is renamed to `copy`, except that it doesn't seem to exist.

**Comment by steveklabnik** [comment]
```
#[stable(feature = "rust1", since = "1.0.0")]
pub use intrinsics::copy_memory as copy;

#[unstable(feature = "core")]
#[deprecated(since = "1.0.0", reason = "renamed to `copy`")]
pub fn copy_memory<T>(dst: *mut T, src: *const T, count: usize);
```

Basically, there's both of these lines. So `rustdoc` is showing that first one as `copy_memory` rather than `copy`.

**Comment by tomjakubowski** [comment]
The originally reported issue in `std::ptr` docs has since been resolved (the deprecated functions were removed, and `pub use` doesn't involve a rename anymore). I'm not sure if the underlying issue was fixed, although docs for this crate:

```rust
#![crate_type="lib"]

pub use inner::blah as testing;

mod inner {
    pub fn blah() {}
}
```

Correctly name the exported function `testing`.

**Comment by steveklabnik** [comment]
Yes, it looks like this has somehow been fixed. If not, please let us know with an updated test case, thank you!
