### ISSUE TITLE
Documentation of iterator classes could be improved

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#23064]
The documentation of iterator structs like Map <http://doc.rust-lang.org/std/iter/struct.Map.html> is not all that helpful, even when the crate doc <http://doc.rust-lang.org/std/iter/index.html> is additionally consulted. I stared at these pages for several minutes, wondering how to obtain such a map iterator, until I found <http://doc.rust-lang.org/std/iter/trait.IteratorExt.html>

I suggest to add something like this to the documentation of all the iterator structs:

Use the IteratorExt::map method to obtain instances of this iterator. The Map type itself should not usually appear explicitly in programs.

**Comment by steveklabnik** [comment]
I haven't gotten to documenting any of this yet, so I will be improving them then. Thanks!
