### ISSUE TITLE
Type inference for closures when downcasting

### ISSUE THREAD

**Issue by yann-ledu** [rust-lang/rust#23063]
```rust
#![feature(box_syntax)]
use std::any::Any;
fn main()
{
    // If the following works...
    {
        let bf:Box<Fn(_)->_> = box |x|3*x;
        let bbf:&Any = &bf;
        let bf = bbf.downcast_ref::<Box<Fn(i32)->i32>>().unwrap();
        println!("Function evaluation gives {:?}",bf(6));
    }

    // then why does the following fail?
    {
        let bf = box |x|3*x;
        let bbf:&Any = &bf;
        let bf = bbf.downcast_ref::<Box<Fn(i32)->i32>>().unwrap();
        println!("Function evaluation gives {:?}",bf(6));
    }
}
```

**Comment by japaric** [comment]
> then why does the following fail?

In the second case `bf` has type `Box<[closure]>` and is not the trait object `Box<Fn>`.

It's clearer if you consider how the desugared version look like:

``` rust
#![feature(box_syntax)]
#![feature(core)]
#![feature(unboxed_closures)]

use std::any::Any;
use std::ops::Fn;

// desugared version of `|x| 3 * x`
struct Closure;

impl Fn<(i32,)> for Closure {
    type Output = i32;

    extern "rust-call" fn call(&self, (x,): (i32,)) -> i32 {
        3 * x
    }
}

fn main()
{
    // If the following works...
    {
        let bf: Box<Fn(_)->_> = box Closure;
        let bbf: &Any = &bf;
        let bf = bbf.downcast_ref::<Box<Fn(i32)->i32>>().unwrap();
        println!("Function evaluation gives {:?}",bf(6));
    }

    // then why does the following fail?
    {
        let bf: Box<Closure> = box Closure;
        let bbf:&Any = &bf;
        let bf = bbf.downcast_ref::<Box<Fn(i32)->i32>>().unwrap();
        println!("Function evaluation gives {:?}",bf(6));
    }
}
```

In general `box || {}` won't give you a trait object, you need to explicitly coerce it to a trait object (like you did in the first case). Also `box |x| 3*x` can be coerced up to three different trait objects: `Box<Fn>`, `Box<FnMut>` or `Box<FnOnce>`, so even if the compiler could automatically do the coercion for you, it would be ambiguous in this case (three possible outcomes), and explicitly annotating the coercion would still be required.

That being said, this is not a type inference bug.

**Comment by yann-ledu** [comment]
Very helpful! So downcasting was meant to fail in the second case : if I box<Any> a box<Closure>, then even though Closure implements the Fn trait, I cannot downcast to it ? I would have had to box<Any> a box<Fn> ? Ok, so I guess I can close this.
