### ISSUE TITLE
Finalze behavior for uncaught panics in child threads

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#23078]
Currently, an uncaught panic on a child thread will result in output to that thread's panic output handle (which is currently overridable).

This may not be a desirable default, and we probably want the behavior to be more thoroughly customizable.

See [this previous RFC](https://github.com/rust-lang/rfcs/pull/519/) for some discussion on the topic, and the corresponding [RFC issue](https://github.com/rust-lang/rfcs/issues/946).

We need to make a decision here before 1.0.

**Comment by aturon** [comment]
nominate: P-backcompat-lang I-needsdecision (1.0 beta)

**Comment by aturon** [comment]
triage: P-backcompat-lang I-needsdecision (1.0 beta)

**Comment by aturon** [comment]
triage: P-backcompat-lang (1.0 beta)

**Comment by pnkfelix** [comment]
This is not going to change in time for beta.

In any case, the current behavior can be a default going-forward (it is a default we can live with), and then we can backwards compatibly add the ability to customize the behavior.

Reclassifying: not 1.0 beta, and not 1.0; P-high.

**Comment by theemathas** [comment]
Related to https://github.com/rust-lang/rust/issues/23172

**Comment by alexcrichton** [comment]
With a stable release, the introduction of panic handlers, and the introduction of panic propagation, I'm going to close this issue now.
