### ISSUE TITLE
UdpSocket::bind() accepts invalid IPv6 address

### ISSUE THREAD

**Issue by manuels** [rust-lang/rust#23076]
The IPv6 address in

    let s = UdpSocket::bind("1200::AB00:1234::2552:7777:1313:34300").unwrap();

is invalid because it includes "::" twice. However, this function call returns `Ok()`

**Comment by shepmaster** [comment]
It's also invalid because the last group has 5 digits: `34300`

**Comment by manuels** [comment]
Great, thanks guys!
