### ISSUE TITLE
dep-info includes all transitvely linked files

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#23089]
I think that the changes in #22235 mean that the `dep-info` output includes too many files now:

```
$ touch foo.rs
$ rustc foo.rs --crate-type lib --emit=dep-info
$ cat foo.d
```

[output](https://gist.githubusercontent.com/alexcrichton/3cdd08e3a5eb4d8ad733/raw/ac3a0c1909ccebfd84312fdf38195fe9e0a195d2/gistfile1.txt)

cc @michaelwoerister

**Comment by michaelwoerister** [comment]
Yes, driver::write_out_deps() probably needs to add a FileMap::is_imported() check to filter out files from other crates. I haven't had time to look into this in detail though.

On March 5, 2015 11:38:23 PM CET, Alex Crichton <notifications@github.com> wrote:
>I think that the changes in #22235 mean that the `dep-info` output
>includes too many files now:
>
>```
>$ touch foo.rs
>$ rustc foo.rs --crate-type lib --emit=dep-info
>$ cat foo.d
>```
>
>[output](https://gist.githubusercontent.com/alexcrichton/3cdd08e3a5eb4d8ad733/raw/ac3a0c1909ccebfd84312fdf38195fe9e0a195d2/gistfile1.txt)
>
>cc @michaelwoerister 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/rust-lang/rust/issues/23089

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by alexcrichton** [comment]
No worries! I did precisely that in https://github.com/rust-lang/rust/pull/23090 :)
