### ISSUE TITLE
LLVM configure doesn't like g++-4.8 anymore

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#23103]
```
checking tool compatibility... configure: error: g++|clang++|icc required but not found
configure: error: LLVM configure failed
```

I have `g++-4.8` installed. Shouldn't that be enough?

(It used to work)

**Comment by alexcrichton** [comment]
You may want to check `config.log` in the LLVM build directory, it will likely have some more detailed information.

**Comment by Manishearth** [comment]
I don't have a copy of it pre-installation of gcc, but this is what I have now:

```

configure:2015: checking for x86_64-unknown-linux-gnu-clang
configure:2042: result: ccache gcc
configure:2122: checking for C compiler version
configure:2129: ccache gcc --version >&5
```

**Comment by ryanobjc** [comment]
I also ran in to this issue.  I needed to install the 'g++' package to provide /usr/bin/g++.  Also the README instructions said g++ | clang++, so I didn't think I needed g++.

**Comment by marcusklaas** [comment]
Ran into this as well. We should probably clarify that g++ is required.

**Comment by Mark-Simulacrum** [comment]
I'm not really sure how to test this, but I feel like this is primarily a documentation problem on our side. Could someone provide a specific summary of what needs to be done here?

**Comment by seanchen1002** [comment]
you can set CC and CXX to point to your local gcc/g++.

export CC=/tool/gcc4.8.2/bin/gcc
export CXX=/tool/gcc4.8.2/bin/g++

**Comment by alexcrichton** [comment]
I think enough has changed about LLVM and building that I'm going to close this.
