### ISSUE TITLE
Compile panic when dealing with glfw

### ISSUE THREAD

**Issue by dirkson** [rust-lang/rust#23129]
Hi all!

Fresh install of rust from nightlies, fresh hello world program. Attempted to add Piston glfw ( https://github.com/PistonDevelopers/piston ) as a dependency, and had the compiler panic when trying to build glfw. Cargo told me to file a bug, so here I am!

Version:
rustc 1.0.0-nightly (b0746ff19 2015-03-05) (built 2015-03-06)

Here's the build with --verbose and backtrace:

       Fresh log v0.2.5
       Fresh libc v0.1.2
       Fresh khronos_api v0.0.5 (https://github.com/bjz/gl-rs#5867745f)
       Fresh shader_version v0.0.2 (https://github.com/PistonDevelopers/shader_version#cd02a715)
       Fresh glfw-sys v3.1.0
       Fresh quack v0.0.13 (https://github.com/PistonDevelopers/quack#6bcb6ac3)
       Fresh semver v0.1.16
       Fresh bitflags v0.1.1
       Fresh rustc-serialize v0.3.1
       Fresh gl_common v0.0.4 (https://github.com/bjz/gl-rs#5867745f)
       Fresh xml-rs v0.1.20
   Compiling glfw v0.0.5 (https://github.com/bjz/glfw-rs#2c281df9)
     Running `rustc /home/dirkson/.cargo/git/checkouts/glfw-rs-66a8b4b1793a8461/master/src/lib.rs --crate-name glfw --crate-type lib -g --cfg feature="default" --cfg feature="glfw-sys" -C metadata=f6932085bd0636a8 -C extra-filename=-f6932085bd0636a8 --out-dir /dirkson/rust/hello_world/target/deps --emit=dep-info,link -L dependency=/dirkson/rust/hello_world/target/deps -L dependency=/dirkson/rust/hello_world/target/deps --extern glfw-sys=/dirkson/rust/hello_world/target/deps/libglfw-sys-f6de7c1748a4da24.rlib --extern semver=/dirkson/rust/hello_world/target/deps/libsemver-d7f360ec5a0ce45e.rlib --extern libc=/dirkson/rust/hello_world/target/deps/liblibc-8d21de95f4de7169.rlib --extern bitflags=/dirkson/rust/hello_world/target/deps/libbitflags-518ea12e21428edd.rlib --extern log=/dirkson/rust/hello_world/target/deps/liblog-045aab9d45b4c031.rlib -Awarnings -L /dirkson/rust/hello_world/target/build/glfw-sys-f6de7c1748a4da24/out`
   Compiling pistoncore-input v0.0.5 (https://github.com/PistonDevelopers/input#3e6d11ce)
     Running `rustc /home/dirkson/.cargo/git/checkouts/input-f00de8c7e2f06034/master/src/lib.rs --crate-name input --crate-type lib -g -C metadata=9035684da0314340 -C extra-filename=-9035684da0314340 --out-dir /dirkson/rust/hello_world/target/deps --emit=dep-info,link -L dependency=/dirkson/rust/hello_world/target/deps -L dependency=/dirkson/rust/hello_world/target/deps --extern rustc-serialize=/dirkson/rust/hello_world/target/deps/librustc-serialize-2aa16a9a901fcba8.rlib --extern bitflags=/dirkson/rust/hello_world/target/deps/libbitflags-518ea12e21428edd.rlib -Awarnings`
       Fresh gl_generator v0.0.19 (https://github.com/bjz/gl-rs#5867745f)
   Compiling gl v0.0.9 (https://github.com/bjz/gl-rs#5867745f)
     Running `rustc /home/dirkson/.cargo/git/checkouts/gl-rs-5020f97825182d66/master/src/gl/build.rs --crate-name build-script-build --crate-type bin -C prefer-dynamic -g --out-dir /dirkson/rust/hello_world/target/build/gl-895707cbc184b133 --emit=dep-info,link -L dependency=/dirkson/rust/hello_world/target/deps -L dependency=/dirkson/rust/hello_world/target/deps --extern khronos_api=/dirkson/rust/hello_world/target/deps/libkhronos_api-4ca4e769faea81a4.rlib --extern gl_generator=/dirkson/rust/hello_world/target/deps/libgl_generator-c3bcfaf2d6074483.rlib -Awarnings`
/home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sync/mutex.rs:177:37: 180:2 error: internal compiler error: debuginfo: Could not find scope info for node NodeExpr(Expr { id: 58658, node: ExprStruct(Path { span: Span { lo: BytePos(4645682), hi: BytePos(4645693), expn_id: ExpnId(4294967295) }, global: false, segments: [PathSegment { identifier: StaticMutex#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }] }, [Field { ident: Spanned { node: lock#0, span: Span { lo: BytePos(1772893), hi: BytePos(1772897), expn_id: ExpnId(4294967295) } }, expr: Expr { id: 58659, node: ExprPath(None, Path { span: Span { lo: BytePos(4645706), hi: BytePos(4645721), expn_id: ExpnId(4294967295) }, global: false, segments: [PathSegment { identifier: sys#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }, PathSegment { identifier: MUTEX_INIT#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }] }), span: Span { lo: BytePos(4645706), hi: BytePos(4645721), expn_id: ExpnId(4294967295) } }, span: Span { lo: BytePos(4645700), hi: BytePos(4645721), expn_id: ExpnId(4294967295) } }, Field { ident: Spanned { node: poison#0, span: Span { lo: BytePos(1772920), hi: BytePos(1772926), expn_id: ExpnId(4294967295) } }, expr: Expr { id: 58660, node: ExprPath(None, Path { span: Span { lo: BytePos(4645735), hi: BytePos(4645752), expn_id: ExpnId(4294967295) }, global: false, segments: [PathSegment { identifier: poison#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }, PathSegment { identifier: FLAG_INIT#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }] }), span: Span { lo: BytePos(4645735), hi: BytePos(4645752), expn_id: ExpnId(4294967295) } }, span: Span { lo: BytePos(4645727), hi: BytePos(4645752), expn_id: ExpnId(4294967295) } }], None), span: Span { lo: BytePos(4645682), hi: BytePos(4645755), expn_id: ExpnId(4294967295) } })
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:129

stack backtrace:
   1:     0x7fb4108fcf6f - sys::backtrace::write::h2f046b875b210aadOBA
   2:     0x7fb410927c82 - panicking::on_panic::h792ac47fb8c07faehHJ
   3:     0x7fb41085cf2a - rt::unwind::begin_unwind_inner::hbffac672008352c8knJ
   4:     0x7fb40dc9f84d - rt::unwind::begin_unwind::h7782663023585067018
   5:     0x7fb40dc9f7f3 - diagnostic::SpanHandler::span_bug::h2cdd5e3b5b05e8f800D
   6:     0x7fb40e57fd03 - session::Session::span_bug::hae37e3dbc1cfddbalVp
   7:     0x7fb41009e6bc - trans::debuginfo::scope_metadata::h3b34d6a00870eb16ClE
   8:     0x7fb40ffb0568 - trans::debuginfo::set_source_location::h9f5b090c644fcb73vPD
   9:     0x7fb40ff64f32 - trans::expr::trans_into::h3bbb0e210c9fb401Vph
  10:     0x7fb40ff651f9 - trans::expr::trans_into::h3bbb0e210c9fb401Vph
  11:     0x7fb40ffc77df - trans::expr::trans_uniq_expr::hd6a8aea14a08d77bQmj
  12:     0x7fb40ffc844f - trans::expr::trans_unary::h35488c79f6cf1ec15ij
  13:     0x7fb40ffb296e - trans::expr::trans_unadjusted::ha9dfc6191d78ce67V6h
  14:     0x7fb40ff65507 - trans::expr::trans_into::h3bbb0e210c9fb401Vph
  15:     0x7fb40ffe5859 - trans::expr::trans_adt::h66e672e44790aeeca9i
  16:     0x7fb40ffe830f - trans::expr::trans_struct::closure.42092
  17:     0x7fb40ffd2176 - trans::expr::trans_struct::ha16472c37d95c70064i
  18:     0x7fb40ffb469d - trans::expr::trans_rvalue_dps_unadjusted::h62a8f691df1cee3cqCi
  19:     0x7fb40ff654e6 - trans::expr::trans_into::h3bbb0e210c9fb401Vph
  20:     0x7fb40ff66317 - trans::controlflow::trans_block::h4b526e186a057814x7d
  21:     0x7fb41003d3b1 - trans::base::trans_closure::h194b7ad0474e43a46mt
  22:     0x7fb40ff4e948 - trans::base::trans_fn::h5416ef5d9cea730bZxt
  23:     0x7fb40ff503e0 - trans::monomorphize::monomorphic_fn::he3c4a3a0040e5501Qud
  24:     0x7fb40ff95f9e - trans::callee::trans_fn_ref_with_substs::h85a6252d422343b2qng
  25:     0x7fb40ff9452e - trans::callee::trans_fn_ref::h7eebc758d7f24cf00bg
  26:     0x7fb40ff9197d - trans::callee::trans::h1b831ba8a404e3ach1f
  27:     0x7fb40ffa80eb - trans::callee::trans_call_inner::h15453122340747063984
  28:     0x7fb40ffb4b40 - trans::expr::trans_rvalue_dps_unadjusted::h62a8f691df1cee3cqCi
  29:     0x7fb40ff654e6 - trans::expr::trans_into::h3bbb0e210c9fb401Vph
  30:     0x7fb40ffe5859 - trans::expr::trans_adt::h66e672e44790aeeca9i
  31:     0x7fb40ffe830f - trans::expr::trans_struct::closure.42092
  32:     0x7fb40ffd2176 - trans::expr::trans_struct::ha16472c37d95c70064i
  33:     0x7fb40ffb469d - trans::expr::trans_rvalue_dps_unadjusted::h62a8f691df1cee3cqCi
  34:     0x7fb40ff654e6 - trans::expr::trans_into::h3bbb0e210c9fb401Vph
  35:     0x7fb410076df7 - trans::_match::mk_binding_alloca::h16286962064436778167
  36:     0x7fb40ff648ed - trans::base::init_local::he5827bc6a6f1a71eyBs
  37:     0x7fb40ff65ff2 - trans::controlflow::trans_block::h4b526e186a057814x7d
  38:     0x7fb41003d3b1 - trans::base::trans_closure::h194b7ad0474e43a46mt
  39:     0x7fb40ff4e948 - trans::base::trans_fn::h5416ef5d9cea730bZxt
  40:     0x7fb40ff503e0 - trans::monomorphize::monomorphic_fn::he3c4a3a0040e5501Qud
  41:     0x7fb40ff95f9e - trans::callee::trans_fn_ref_with_substs::h85a6252d422343b2qng
  42:     0x7fb40ff9452e - trans::callee::trans_fn_ref::h7eebc758d7f24cf00bg
  43:     0x7fb40ff9197d - trans::callee::trans::h1b831ba8a404e3ach1f
  44:     0x7fb40ffa80eb - trans::callee::trans_call_inner::h15453122340747063984
  45:     0x7fb40ffb4b40 - trans::expr::trans_rvalue_dps_unadjusted::h62a8f691df1cee3cqCi
  46:     0x7fb40ffb27c8 - trans::expr::trans_unadjusted::ha9dfc6191d78ce67V6h
  47:     0x7fb40ff66c48 - trans::expr::trans::h4730571ef226d1543vh
  48:     0x7fb40ffa3b43 - trans::callee::trans_args::hfa9ae7de71a462d8I3g
  49:     0x7fb40ffa8fd0 - trans::callee::trans_call_inner::h15453122340747063984
  50:     0x7fb40ffb4b40 - trans::expr::trans_rvalue_dps_unadjusted::h62a8f691df1cee3cqCi
  51:     0x7fb40ffb27c8 - trans::expr::trans_unadjusted::ha9dfc6191d78ce67V6h
  52:     0x7fb40ff66c48 - trans::expr::trans::h4730571ef226d1543vh
  53:     0x7fb40ffa3b43 - trans::callee::trans_args::hfa9ae7de71a462d8I3g
  54:     0x7fb40ffa8fd0 - trans::callee::trans_call_inner::h15453122340747063984
  55:     0x7fb40ffb4b40 - trans::expr::trans_rvalue_dps_unadjusted::h62a8f691df1cee3cqCi
  56:     0x7fb40ff654e6 - trans::expr::trans_into::h3bbb0e210c9fb401Vph
  57:     0x7fb410076df7 - trans::_match::mk_binding_alloca::h16286962064436778167
  58:     0x7fb40ff648ed - trans::base::init_local::he5827bc6a6f1a71eyBs
  59:     0x7fb40ff65ff2 - trans::controlflow::trans_block::h4b526e186a057814x7d
  60:     0x7fb40ffb40de - trans::expr::trans_rvalue_dps_unadjusted::h62a8f691df1cee3cqCi
  61:     0x7fb40ff654e6 - trans::expr::trans_into::h3bbb0e210c9fb401Vph
  62:     0x7fb41005f280 - trans::_match::trans_match_inner::h5d40a011e6b8915eYKw
  63:     0x7fb40ffb4082 - trans::expr::trans_rvalue_dps_unadjusted::h62a8f691df1cee3cqCi
  64:     0x7fb40ffb27c8 - trans::expr::trans_unadjusted::ha9dfc6191d78ce67V6h
  65:     0x7fb40ff66c48 - trans::expr::trans::h4730571ef226d1543vh
  66:     0x7fb40ff649c2 - trans::base::init_local::he5827bc6a6f1a71eyBs
  67:     0x7fb40ff65ff2 - trans::controlflow::trans_block::h4b526e186a057814x7d
  68:     0x7fb41003d3b1 - trans::base::trans_closure::h194b7ad0474e43a46mt
  69:     0x7fb40ff4e948 - trans::base::trans_fn::h5416ef5d9cea730bZxt
  70:     0x7fb40ff503e0 - trans::monomorphize::monomorphic_fn::he3c4a3a0040e5501Qud
  71:     0x7fb40ff95f9e - trans::callee::trans_fn_ref_with_substs::h85a6252d422343b2qng
  72:     0x7fb40ffadfe5 - trans::meth::trans_method_callee::h175c0aff2b6fe67998x
  73:     0x7fb40ffa9a19 - trans::callee::trans_call_inner::h18244630176801372264
  74:     0x7fb40ffb38e9 - trans::expr::trans_rvalue_dps_unadjusted::h62a8f691df1cee3cqCi
  75:     0x7fb40ff654e6 - trans::expr::trans_into::h3bbb0e210c9fb401Vph
  76:     0x7fb40ffe5859 - trans::expr::trans_adt::h66e672e44790aeeca9i
  77:     0x7fb40ffe830f - trans::expr::trans_struct::closure.42092
  78:     0x7fb40ffd2176 - trans::expr::trans_struct::ha16472c37d95c70064i
  79:     0x7fb40ffb469d - trans::expr::trans_rvalue_dps_unadjusted::h62a8f691df1cee3cqCi
  80:     0x7fb40ff654e6 - trans::expr::trans_into::h3bbb0e210c9fb401Vph
  81:     0x7fb40ff66317 - trans::controlflow::trans_block::h4b526e186a057814x7d
  82:     0x7fb41003d3b1 - trans::base::trans_closure::h194b7ad0474e43a46mt
  83:     0x7fb40ff4e948 - trans::base::trans_fn::h5416ef5d9cea730bZxt
  84:     0x7fb40ff4b081 - trans::base::trans_item::h2af153dd6f7fd52bRVt
  85:     0x7fb41004674c - trans::base::trans_crate::h5cb53f6b3e2377862Ru
  86:     0x7fb410f37613 - driver::phase_4_translate_to_llvm::h60575195b9fa298dENa
  87:     0x7fb410f1305b - driver::compile_input::h9772b425fd1776fdNba
  88:     0x7fb410fd7697 - run_compiler::h17c28dbe4dd58e3bV5b
  89:     0x7fb410fd52c9 - thunk::F.Invoke<A, R>::invoke::h3041729087284544127
  90:     0x7fb410fd3f40 - rt::unwind::try::try_fn::h11775082019993619070
  91:     0x7fb410997e38 - rust_try_inner
  92:     0x7fb410997e25 - rust_try
  93:     0x7fb410fd46df - thunk::F.Invoke<A, R>::invoke::h10556879288050829464
  94:     0x7fb4109129b5 - sys::thread::thread_start::hfe8c2cac3ec4afcdr8E
  95:     0x7fb40a7600a3 - start_thread
  96:     0x7fb4104cdccc - __clone
  97:                0x0 - <unknown>

Build failed, waiting for other jobs to finish...
Could not compile `glfw`.

Caused by:
  Process didn't exit successfully: `rustc /home/dirkson/.cargo/git/checkouts/glfw-rs-66a8b4b1793a8461/master/src/lib.rs --crate-name glfw --crate-type lib -g --cfg feature="default" --cfg feature="glfw-sys" -C metadata=f6932085bd0636a8 -C extra-filename=-f6932085bd0636a8 --out-dir /dirkson/rust/hello_world/target/deps --emit=dep-info,link -L dependency=/dirkson/rust/hello_world/target/deps -L dependency=/dirkson/rust/hello_world/target/deps --extern glfw-sys=/dirkson/rust/hello_world/target/deps/libglfw-sys-f6de7c1748a4da24.rlib --extern semver=/dirkson/rust/hello_world/target/deps/libsemver-d7f360ec5a0ce45e.rlib --extern libc=/dirkson/rust/hello_world/target/deps/liblibc-8d21de95f4de7169.rlib --extern bitflags=/dirkson/rust/hello_world/target/deps/libbitflags-518ea12e21428edd.rlib --extern log=/dirkson/rust/hello_world/target/deps/liblog-045aab9d45b4c031.rlib -Awarnings -L /dirkson/rust/hello_world/target/build/glfw-sys-f6de7c1748a4da24/out` (exit code: 101)

**Comment by jdm** [comment]
Dup of #22432.
