### ISSUE TITLE
Something (cargo? rustc?) generates a load of tmp files, and doesn't delete them

### ISSUE THREAD

**Issue by Jragonmiris** [rust-lang/rust#23130]
I've been having issues with something generating hundreds of tmp files. They're relatively small (<2 MB each), but they really pollute the src directory. I believe this has been happening on Windows (Windows 7 64-bit with msys MinGW), but I can't confirm whether or not it's been happening on Mac or Linux as well.

I noticed today when a Dropbox I was using for a quick shared toy project said it had 500-some new files in it. Here's the count:

    jragonmiris#101 $~/Dropbox/rust_shared/manager/src: ls | grep tmp | wc -l
         547

Their names all look like `tmp6fukql`.

They don't cause any compilation errors, and you can delete them really quickly with something like rm -f tmp*, but it's really non-ideal. Sorry I don't have more info, I'm trying to reproduce the problem, but I haven't figured out how to force it to happen yet.

**Comment by blindley** [comment]
It may be your editor. Or a plugin for you editor. You wouldn't happen to be using the Rust plugin for Sublime, would you? I had this same thing happening, and that was the source of it.

**Comment by kmcallister** [comment]
What are the contents of those files?

**Comment by Jragonmiris** [comment]
Yes, looking at my Dropbox while I edit, it's the Sublime plugin, sorry.

**Comment by yodaldevoid** [comment]
To help people looking for the solution to this problem, [here](https://github.com/defuz/RustAutoComplete/issues/19) is the RustAutoComplete issue.
