### ISSUE TITLE
TcpStream (and probably more std::net types) missing Debug impl

### ISSUE THREAD

**Issue by carllerche** [rust-lang/rust#23134]
It seems like these types could implement Debug (allowing structs that contain std::net values to be able to derive Debug).

cc @alexcrichton

**Comment by wesleywiser** [comment]
Hi, if it's ok, I'd like to work on this issue. I have a commit in my local repo which resolves this but I need to test it some more to be sure. Hopefully, I can open a PR with the changes later tonight.

**Comment by sfackler** [comment]
Sure!

**Comment by wesleywiser** [comment]
@sfackler Hi, I'm trying to test my changes but I'm running into an issue. `make help` says that running `make all` should result in `rustc` being in `${platform}/stage2/bin` but when I run `./rustc` from that directory, I get:

```
./rustc: symbol lookup error: ./rustc: undefined symbol: _ZN2rt10lang_start20hd326254c68b07ef5NFJE
```

Any ideas?

**Comment by sfackler** [comment]
You need to set your `LD_LIBRARY_PATH` on linux or `DYLD_LIBRARY_PATH` on osx to have it point to the right set of libraries - it should be set to `${platform}/stage2/lib`.

**Comment by wesleywiser** [comment]
Thanks, that did the trick.

I found several types in `std::net` that didn't implement `Debug`. After my changes this is what they output:

- `Shutdown`: `Read` or `Write` or `Both`
- `TcpStream`: `TcpStream { addr: Ok(127.0.0.1:1234) }`
- `TcpListener`: `TcpListener { addr: Ok(127.0.0.1:1234) }`
- `UdpSocket`: `UdpSocket { addr: Ok(127.0.0.1:1234) }`

Does that look right? Should I try to get rid of the inner `Ok`s?

**Comment by wesleywiser** [comment]
@sfackler Sorry, I think I forgot to mention you in that last comment.

**Comment by sfackler** [comment]
Ah yeah, sorry. I'd go without the `Ok` wrappers personally. It's probably also a good idea to put the file descriptor itself in the debug message as well.

**Comment by nham** [comment]
@wesleywiser Are you still working on this?

**Comment by wesleywiser** [comment]
No, I ran into some issues trying to figure out how to get at the file
descriptors.

**Comment by nham** [comment]
I've started working on this. I have a branch here: https://github.com/nham/rust/commit/6ac730accd510dd45451acd4702c6ff3be4854ff
