### ISSUE TITLE
Add a special case error for `[Range<T>; 1]`

### ISSUE THREAD

**Issue by reem** [rust-lang/rust#23141]
`[Range<T>; 1]` is usually a mistake and often the source of type errors where `Range<T>` was meant, since you get it with `[a..b]`, which is tempting from the syntax.

**Comment by Thiez** [comment]
In theory `&[0..10]` *could* be correct in a for loop...

When using this program:
```rust
fn main() {
    for r in [0..10] {
        println!("{:?}", r);
    }
}
```
the current error message appears to be 
```
error: the trait `core::iter::Iterator` is not implemented for the type `[core::ops::Range<_>; 1]
note: `[core::ops::Range<_>; 1]` is not an iterator; maybe try calling `.iter()` or a similar method
```
Surely that is understandable ("Why is the iterator in a length-1 array? Oh, better remove the `[]`").
What bothers me more is that both messages show up three times, and count as 3 errors...

**Comment by steveklabnik** [comment]
Triage: Same error, but only one time. It could be a bit better, probably.

**Comment by clarcharr** [comment]
Shouldn't this be a clippy issue?
