### ISSUE TITLE
warning: function is never used: `main`

### ISSUE THREAD

**Issue by identicalsnowflake** [rust-lang/rust#23158]
Not sure if this is somehow Cargo doing this or if it's rustc, but when I do "cargo new --bin myproject" then "cargo test", it tells me "warning: function is never used: `main`, #[warn(dead_code)] on by default"

**Comment by sfackler** [comment]
I believe this is a duplicate of #12327

**Comment by steveklabnik** [comment]
Yes, it is.

**Comment by steveklabnik** [comment]
(And I'm still interested in landing such a patch)
