### ISSUE TITLE
Thunk undocumented

### ISSUE THREAD

**Issue by vojtechkral** [rust-lang/rust#23152]
http://doc.rust-lang.org/std/thunk/index.html

What even is `Thunk`?

**Comment by sfackler** [comment]
cc @steveklabnik

**Comment by steveklabnik** [comment]
Yes, it is unstable, and so will get documentation when it becomes stable. They're for use with closures. http://en.wikipedia.org/wiki/Thunk

**Comment by eddyb** [comment]
It's [https://github.com/rust-lang/rust/blob/b8c6eb179e9e792c5470abbe2b6eeadc16f34565/src/libstd/thunk.rs#L11-L12]("temporary") (although that word has long lost its meaning, certain values of it are rather "eternal").

@nikomatsakis I thought you had a better less-than-perfect solution, using a `FnBox` trait - it's even [on crates.io](https://crates.io/crates/fn_box), why are we not using that?
Also, it would be handy to have the rationale for the removal of by-value method call handling in trait objects, in a FAQ somewhere.
Are we not certain we'll ever have a good `DerefMove` story that would support `Box<Trait>` with by-value method calls, with a completely in-library `Box` implementation?

**Comment by vojtechkral** [comment]
Ah, didn't notice the allow missing docs attrib, sorry. Okay, thanks for explanation.
