### ISSUE TITLE
Unary `-` does not check for overflow

### ISSUE THREAD

**Issue by simias** [rust-lang/rust#23154]
The following code prints `-2147483648 -2147483648`:

```rust
fn main() {
    let i = 0x80000000u32 as i32;

    println!("{} {}", i, -i);
}
```

Both `0 - i` and `i / -1` generate an overflow error but it seems the unary `-` gladly wraps around.

**Comment by alexcrichton** [comment]
I added this to the list of unimplemented overflow checks on https://github.com/rust-lang/rust/issues/22020, but thanks for the report!
