### ISSUE TITLE
Add read_full to std::io::ReadExt

### ISSUE THREAD

**Issue by tuxychandru** [rust-lang/rust#23174]
Since the `read` function of `std::io::Read` may read less than the length of the buffer passed to it, adding a function named `read_full` which calls `read` in a loop until the buffer is filled can be useful.

**Comment by mahkoh** [comment]
Needs an RFC. This was previously rejected because the EOF handling and the functions built on top of it were fucked up. This has been fixed so it might work now.

**Comment by steveklabnik** [comment]
This

1) went through the RFC process https://github.com/rust-lang/rfcs/pull/980
2) was implemented, as `read_exact` https://github.com/rust-lang/rust/issues/27585
