### ISSUE TITLE
Installer doesn't recommend to set LD_LIBRARY_PATH on f21

### ISSUE THREAD

**Issue by csoriano89** [rust-lang/rust#23193]
So the installer should recommend to modify the LD_LIBRARY_PATH or something.
Using Fedora 21.
This is the session terminal output:

carlos@localhost rust-nightly-x86_64-unknown-linux-gnu$ curl -L https://static.rust-lang.org/rustup.sh | sudo sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13083  100 13083    0     0  19665      0 --:--:-- --:--:-- --:--:-- 19644
rustup: CFG_CURL             := /bin/curl (7.37.0)
rustup: CFG_TAR              := /bin/tar (1.27.1)
rustup: CFG_FILE             := /bin/file (5.19)
rustup: CFG_SHA256SUM        := /bin/sha256sum (256sum)
rustup: CFG_SHASUM           := /bin/shasum (5.93)
rustup: 
rustup: processing sh args
rustup: 
rustup: CFG_PREFIX           :=  
rustup: CFG_DATE             :=  
rustup: 
rustup: validating sh args
rustup: 
rustup: host triple: x86_64-unknown-linux-gnu
rustup: Downloading https://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz to /tmp/tmp.8MiMWsqdDl/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  105M  100  105M    0     0  1475k      0  0:01:13  0:01:13 --:--:-- 1574k
rustup: Downloading https://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz.sha256
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   111  100   111    0     0    162      0 --:--:-- --:--:-- --:--:--   162
rustup: Verifying hash
rustup: Extracting /tmp/tmp.8MiMWsqdDl/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
install: creating uninstall script at /usr/local/lib/rustlib/uninstall.sh
install: installing component 'rustc'
install: installing component 'cargo'
install: installing component 'rust-docs'

    Rust is ready to roll.

carlos@localhost rust-nightly-x86_64-unknown-linux-gnu$ rustc --version
rustc: error while loading shared libraries: librustc_driver-4e7c5e5c.so: cannot open shared object file: No such file or directory
carlos@localhost rust-nightly-x86_64-unknown-linux-gnu$ echo $LD_LIBRARY_PATH

carlos@localhost rust-nightly-x86_64-unknown-linux-gnu$ export LD_LIBRARY_PATH=/usr/local/lib
carlos@localhost rust-nightly-x86_64-unknown-linux-gnu$ echo $LD_LIBRARY_PATH
/usr/local/lib
carlos@localhost rust-nightly-x86_64-unknown-linux-gnu$ rustc --version
rustc 1.0.0-nightly (2fc8b1e7c 2015-03-07) (built 2015-03-08)
carlos@localhost rust-nightly-x86_64-unknown-linux-gnu$

**Comment by prajwalkman** [comment]
+1

I had the same issue on ElementaryOS (Freya release)

**Comment by csoriano89** [comment]
@prajwalkman I though Debian was actually the only distro that included /usr/local/bin in the library path, since Fedora, Arch etc do not trust that.
So now seems any distro includes it? Why is not rust using  /usr/lib/ instead?

**Comment by genodeftest** [comment]
As long as rust does not provide an rpm it must not use /usr/lib/ on Fedora. Similiar policy for other distributions. /usr/local/ is often reserved for applications not installed by the default package manager.

**Comment by alexcrichton** [comment]
We've since enabled rpath by default, so closing
