### ISSUE TITLE
BufReader .consume() confuses the Reader seek point when the buffer is empty

### ISSUE THREAD

**Issue by jorisgio** [rust-lang/rust#23196]
The behavior of .consume when the buffer is empty is weird : 

```rust
let mut f = BufReader::new(Cursor::new(vec![65, 255, 42]));
f.consume(1);
let x = &mut [0; 1];
println!("{}", f.read(x).unwrap()); // prints 0
```
while : 

```rust
let mut f = BufReader::new(Cursor::new(vec![65, 255, 42]));
let x = &mut [0; 1];
f.read(x).unwrap();
f.consume(1);
println!("{}", f.read(x).unwrap()); // prints 1, x[0] is 42
```

**Comment by alexcrichton** [comment]
Currently the contract of `consume` is that you can only pass a number `>=` the number of bytes you receive from `fill_buf`. In this case the method is never being called, causing the weird behavior.

I believe this is a documentation issue as the documentation for the `consume` method is pretty curt.

**Comment by jorisgio** [comment]
Maybe adding an assert_debug to check that could be useful too ?

**Comment by tuxychandru** [comment]
@alexcrichton What's the intended use of `consume` if it must always be passed a value `>=` the return value of `fill_buf`?

**Comment by alexcrichton** [comment]
Oh sorry, I meant `<=`! The function is intended to tell the buffer how many bytes you've consumed from the return value of `fill_buf`
