### ISSUE TITLE
The online documentation no longer links to the source

### ISSUE THREAD

**Issue by Thiez** [rust-lang/rust#23192]
When visiting a page such as [stdlib](http://doc.rust-lang.org/std/) or [option](http://doc.rust-lang.org/std/option/) the link **src** (for the source code) no longer works. Instead a 404 is returned. This seems to have been broken for several days now.

**Comment by lahwran** [comment]
even before this, many but not all were broken. there may be multiple issues with this symptom.

**Comment by ipetkov** [comment]
The `[src]` links link in the form `/path/to/src/filename.rs.html` but it seems like the actual source is being placed in a location in the form `/path/to/src/filename.rs/filename.rs.html`

For example here's a link from the current docs which will 404: http://doc.rust-lang.org/src/core/option.rs.html

But the following will resolve: http://doc.rust-lang.org/src/core/option.rs/option.rs.html

**Comment by tbu-** [comment]
Really annoyed by this. :<
