### ISSUE TITLE
Stdout should be flushed on exit

### ISSUE THREAD

**Issue by tsion** [rust-lang/rust#23205]
See http://is.gd/SH4nll

This fails to print anything since `"hey"` in only written to the buffer and then never printed. Other `BufWriter`s [flush on drop](https://github.com/rust-lang/rust/blob/master/src/libstd/io/buffered.rs#L213-L221) but this isn't happening for `Stdout` at program exit.

**Comment by shepmaster** [comment]
Duplicate of #23191, which is closed in favor of #20012

**Comment by alexcrichton** [comment]
Indeed, thanks @shepmaster!
