### ISSUE TITLE
 Can't implement Copy for C style enums with negative discriminants that overflow into unspecified positive discriminants

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#23221]
```rust
fn main() { }

#[repr(C)]
#[derive(Copy)]
enum X {
    A = -1,
    B,
}
```
```
test5.rs:7:5: 7:6 error: Discriminant overflowed!
test5.rs:7     B,
               ^
```

**Comment by huonw** [comment]
Providing an explicit discriminant for the variant after the `-1` works as a workaround:

```rust
fn main() { }

#[repr(C)]
#[derive(Copy)]
enum X {
    A = -1,
    B = 0,
}
```

**Comment by mahkoh** [comment]
The same happens without repr(C) or with repr(i32).

**Comment by pnkfelix** [comment]
Also, `-2` will work.  I'll update the title.

**Comment by mahkoh** [comment]
@pnkfelix: The error message shows that it's about overflowing discriminants. There is nothing special about -1.

**Comment by pnkfelix** [comment]
@mahkoh my point is that the bug is not observed by *all* negative discriminants.

**Comment by mahkoh** [comment]
In any case the previous title was wrong because this works fine:

```rust
fn main() { }

//#[repr(C)]
enum _X {
    A = -1,
}

impl Copy for _X { }
```

**Comment by shepmaster** [comment]
@pnkfelix I think that @mahkoh's point was that this usage of `-2` does fail:

```rust
fn main() { }

#[derive(Copy)]
enum X {
    A = -2,
    B,
    C,
}
```

**Comment by pnkfelix** [comment]
cc #23897
