### ISSUE TITLE
Doc: closure confusion in the intro

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#23220]
The intro has this code example:

https://github.com/rust-lang/rust/blob/14ce607d9b96ab3c8d5564bcddd553d6f8e175c7/src/doc/intro.md#concurrency

```rust
use std::thread::Thread;

fn main() {
    let guards: Vec<_> = (0..10).map(|_| {
        Thread::scoped(|| {
            println!("Hello, world!");
        })
    }).collect();
}
```
```
7:25: 10:6 error: cannot move out of captured outer variable in an `FnMut` closure
7     Thread::scoped(move || {
8       numbers[i] += 1;
9       println!("numbers[{}] is {}", i, numbers[i]);
10     });
error: aborting due to previous error
```

> It mentions that "captured outer variable in an FnMut closure". Because we declared the closure as a moving closure, and it referred to numbers, the closure will try to take ownership of the vector.

I *think* that the `FnMut` closure the error message refers to is the argument of `map`, but the text of the intro then talks about the argument of `Thread::scoped` (which is a `FnOnce`). The move happens (or would) at the creation of the inner closure, but it’s the outer one that captures and can not be moved out of.

Whether or not my understanding is correct, this paragraph should avoid using “the closure” since there are two of them involved.

CC @steveklabnik

**Comment by steveklabnik** [comment]
I sent in a patch to fix this, unsure why GitHub didn't link. The text should be more clear now.
