### ISSUE TITLE
make check-stage1-debuginfo-lldb has mysterious failures on Mac OS X (10.9.5)

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#23227]
make check-stage1-debuginfo-lldb has mysterious failures on Mac OS X (10.9.5)

I thought it was something with my local branch for a while, but eventually I wised up and tried against master, and saw the problems there too.

The problems do not seem to occur during `make check-stage2`.  (Do the debuginfo tests play games with the load path that can be hard to get right during stage1?)

In fact, even just running the tests in parallel with trying to file this ticket seems to consistent _kill_ my Mac OS X kernel. (!)

So, okay, that sounds like an OS problem.  I will see if the problem happens as well on a more recent version of OS X, or if I simply need to upgrade this machine to Yosemite (10.9 is Mavericks).

**Comment by richo** [comment]
I've observed this on a new install, without the kernel panic (but with a lot of lldb faults that I have crashlogs for)

I'll do some digging, but can't commit to actually fixing it

**Comment by pnkfelix** [comment]
Okay, so on Yosemite, my kernel no longer dies.  Yay.

So I put the CrashReporter DialogType into "developer" mode via:
```
defaults write com.apple.CrashReporter DialogType developer
```

and this gave me some useful information about these crashes when e.g. running:
```
% make check-stage1-debuginfo-lldb TESTNAME=box.rs
```

I won't paste the entire dump here; the smoking gun to me seems to be this bit:

```
Dyld Error Message:
  Symbol not found: __ZN2rt10lang_start20h2effab90387cd25b2mJE
  Referenced from: /Users/USER/*/box.stage1-x86_64-apple-darwin
  Expected in: /Users/USER/*/libstd-4e7c5e5c.dylib
```

So yes, my guess is that the `DYLD_LIBRARY_PATH` is probably not being set up properly for a stage1 build.

**Comment by pnkfelix** [comment]
@michaelwoerister have you encountered anything like this yourself?  Have you run `make check-stage1-debuginfo-lldb` recently on a mac?  (Do you have a mac to develop on?)

**Comment by michaelwoerister** [comment]
Yes, I've run into this myself yesterday. Stage2 works fine, stage1 fails for all tests where the test-executable actually runs. This has to be kind of new since I normally always use the stage1 target while developing.

**Comment by michaelwoerister** [comment]
I'm also using OSX 10.9.5 by the way.
It really looks like something is messed up with `DYLD_LIBRARY_PATH` but it's strange that it only happens in stage1.

**Comment by pnkfelix** [comment]
It's not that strange; the makefiles do funky things that sometimes are not always written sufficiently robustly for arbitrary stageN

**Comment by barosl** [comment]
I'm getting similar errors on OS X 10.10.3. Both stage1 and stage2 are failing.

Plus changing `DialogType` to `developer` doesn't seem to emit any noticeable output... Am I doing something wrong?

**Comment by michaelwoerister** [comment]
It still works for me with stage2.

**Comment by steveklabnik** [comment]
Triage: I don't have a mac, so I don't know if this is still an issue. No comments in almost two years makes me think not, but maybe!

**Comment by Mark-Simulacrum** [comment]
`make -j8 check-stage1-debuginfo-lldb` passes for me on `Darwin macbook 16.3.0 Darwin Kernel Version 16.3.0`.

**Comment by pnkfelix** [comment]
I'm going to close this ticket; given that we've moved from makefiles to rustbuild, any issues we have are probably different than what was described here.
