### ISSUE TITLE
impl Trait for .. {} does not require a feature gate

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#23225]
I suspect that we may want more experience with this syntax before freezing it, but I may also be misremembering!

cc @nikomatsakis 
cc @FlaPer87

**Comment by alexcrichton** [comment]
triage: I-nominated

**Comment by FlaPer87** [comment]
@alexcrichton I believe you're right. I'll work on  a fix for this. Here's a test case:

```rust
use std::marker::MarkerTrait;

trait Test: MarkerTrait {}

impl Test for .. {}

fn main() {}
```

**Comment by pnkfelix** [comment]
1.0 beta, P-backcompat-lang.
