### ISSUE TITLE
Update Nuget package!

### ISSUE THREAD

**Issue by jasonwilliams200OK** [rust-lang/rust#23223]
coz its being a while: https://www.nuget.org/packages/Rust/.

> Current version: Monday, May 19 2014

**Comment by alexcrichton** [comment]
Unfortunately we are not the ones who manage that package, I would recommend trying to reach out to the maintainer there directly if you can find them!

**Comment by jasonwilliams200OK** [comment]
Thanks. Actually the author set the URL in package to this repo

@Heather, are you the owner of this package: https://www.nuget.org/packages/Rust/?

**Comment by Heather** [comment]
@jasonwilliams200OK Yes but it was useful before Rust started to provide nightly binaries, e.g. it was self-builded builds because there are was no other binaries. However I can it from time to time with nightly binaries if some people still use it.

**Comment by Heather** [comment]
@alexcrichton I will be glad to add any other people to maintainers if team want to maintain it.

**Comment by jasonwilliams200OK** [comment]
Can you point me to your repository? Also please update the "project site" URL to your repository on nuget.org.

**Comment by Heather** [comment]
@jasonwilliams200OK there is no repository for it and I've lost nuget package I used already so it should be just overrided with new version
