### ISSUE TITLE
Docs Sometimes Show Underline in Trait Implementations List

### ISSUE THREAD

**Issue by killercup** [rust-lang/rust#23230]
I was just reading [this docs page](http://doc.rust-lang.org/std/old_path/posix/struct.Path.html) and noticed that some method entries have underlines.

![std__old_path__posix__path_-_rust](https://cloud.githubusercontent.com/assets/20063/6562526/3e410732-c69a-11e4-8f23-e35336d53114.png)

It seems that these are have the class `tymethod` (what's that, by the way?), but the definition for headlines with `border-bottom` is `h4:not(.method):not(.type)`.

I'll probably submit a PR adding `.tymethod` to that list in a few minutes.

**Comment by tomjakubowski** [comment]
`TyMethod` in rustdoc is refers to just a trait method signature, which is used for required methods in traits (those that must be implemented). Default trait methods are treated as `MethodItem`. That's how rustdoc distinguishes required/default trait methods for rendering. Not saying that's necessarily what rustdoc *should* be doing, just that's what it does today. :-)

Personally I think that the `border-bottom` style should be disabled in the implementors list.

**Comment by killercup** [comment]
@tomjakubowski thanks for the explanation!

#23231 disables the border by matching `tymethod`, I guess I could also overwrite `.impl-items h4` in general.

**Comment by tomjakubowski** [comment]
@killercup I didn't read the CSS carefully. My mistake! :-)
