### ISSUE TITLE
Add example for Float::min_pos_value() method

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#23242]
[`std::num::Float`](http://doc.rust-lang.org/std/num/trait.Float.html) is missing an example for:
- [ ] [`Float::min_pos_value()`](http://doc.rust-lang.org/std/num/trait.Float.html#tymethod.min_pos_value): It's not clear what normalized could mean in this context.

**Comment by steveklabnik** [comment]
As APIs become stable, I will add documentation to them, but I'm not currently tracking API documentation on a per-call basis, especially for unstable APIs. thanks.
