### ISSUE TITLE
Add the missing examples to the int trait

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#23241]
[`std::num::Int`](http://doc.rust-lang.org/std/num/trait.Int.html) is missing examples for these methods:
- [ ] [`Int::zero()`](http://doc.rust-lang.org/std/num/trait.Int.html#tymethod.zero)
- [ ] [`Int::one()`](http://doc.rust-lang.org/std/num/trait.Int.html#tymethod.one)
- [ ] [`Int::min_value()`](http://doc.rust-lang.org/std/num/trait.Int.html#tymethod.min_value)
- [ ] [`Int::max_value()`](http://doc.rust-lang.org/std/num/trait.Int.html#tymethod.max_value)
- [ ] [`Int::saturating_add()`](http://doc.rust-lang.org/std/num/trait.Int.html#tymethod.saturating_add)
- [ ] [`Int::saturating_sub()`](http://doc.rust-lang.org/std/num/trait.Int.html#tymethod.saturating_sub)

Examples for them should be added.

**Comment by steveklabnik** [comment]
Same as the other ticket: these are currently unstable.

**Comment by mdinger** [comment]
`saturating_add()` and `saturating_sub()` are stable. This should be open.
