### ISSUE TITLE
Mention in the book that offline docs are installed

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#23244]
State in [installation](http://doc.rust-lang.org/book/installing-rust.html) that offline local docs are installed with Rust and note the location of them. This [question](http://www.reddit.com/r/rust/comments/2yiyjz/rust_book_is_there_and_offline_pdf_or_wget/) comes up often.

**Comment by mdinger** [comment]
State how to generate a PDF it it's possible unless you want to start bundling a PDF with the installation (which isn't that bad an idea). This is a secondary goal though.

**Comment by carols10cents** [comment]
It'd also be cool if the end of installation pointed this out as well, something like:

```
$ sudo ./install.sh 
install: creating uninstall script at /usr/local/lib/rustlib/uninstall.sh
install: installing component 'rustc'
install: installing component 'cargo'
install: installing component 'rust-docs'

    Rust is ready to roll.
    Offline API docs: `open /usr/local/share/doc/rust/html/std/index.html`
    Offline book: `open /usr/local/share/doc/rust/html/book/index.html`
```

**Comment by mdinger** [comment]
@brson ^^^ Isn't making the installation awesome one of the cool things you do?
