### ISSUE TITLE
configure should only download the parts of the submodules that are necessary for compilation

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#23258]
configure currently downloads the whole tree of the submodules. For llvm this seems to be over 500MB. Instead it should only download the latest snapshot that is used during compilation. Here is a bash script that does this for the current snapshots:

```bash
#!/bin/sh

function clone() {
    git clone -b $1 --depth 1 --single-branch $2 $3
}

clone rust-2014-09-20-do-not-delete https://github.com/rust-lang/hoedown.git     src/rt/hoedown
clone rust-2014-11-01-do-not-delete https://github.com/rust-lang/jemalloc.git    src/jemalloc
clone rust-2015-01-08-do-not-delete https://github.com/rust-lang/compiler-rt.git src/compiler-rt
clone rust-llvm-2015-02-19          https://github.com/rust-lang/llvm.git        src/llvm
```

**Comment by brson** [comment]
This should be a matter of adding `--depth 1` to the `git submodule update` commands.

**Comment by mahkoh** [comment]
@brson I tried this but it did not work. With just --depth 1 it failed to check out the correct branch. I also tried using the `branch` attribute and the `--remote` argument but it did not work.

```
/rust$ git submodule update --depth 1
Cloning into 'src/compiler-rt'...
remote: Counting objects: 1405, done.
remote: Compressing objects: 100% (1226/1226), done.
remote: Total 1405 (delta 289), reused 845 (delta 152), pack-reused 0
Receiving objects: 100% (1405/1405), 2.02 MiB | 552.00 KiB/s, done.
Resolving deltas: 100% (289/289), done.
Checking connectivity... done.
fatal: reference is not a tree: 58ab642c30d9f97735d5745b5d01781ee199c6ae
```

**Comment by mahkoh** [comment]
In all of these cases it seems that --depth 1 will clone from the master branch. So it might just be an issue of keeping the master branch up to date.

**Comment by fbernier** [comment]
I think [this](http://comments.gmane.org/gmane.comp.version-control.git/257047) is the feature we are looking for which has never been merged in git.
