### ISSUE TITLE
ICE when matching on DST structs.

### ISSUE THREAD

**Issue by hugoduncan** [rust-lang/rust#23261]
The following code causes 

    Assertion failed: (getOperand(0)->getType() == cast<PointerType>(getOperand(1)->getType())->getElementType() && "Ptr must be a pointer to Val type!"), function AssertOK, file /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/llvm/lib/IR/Instructions.cpp, line 1083.

```rust
use std::collections::HashMap;
use std::path::{Path, PathBuf};

#[derive(Debug)]
pub struct FileMeta;

struct S {
    h2 : HashMap<PathBuf, FileMeta>,
}

impl S {
    fn new() -> S {
        S {
            h2: HashMap::new(),
        }
    }

    fn f(&self, path: &Path) -> FileMeta {
        let m = FileMeta;
        match self.h2.get(path) {
            Some(meta) => m,
            None => m
        }
    }
}
```

Using `rustc 1.0.0-nightly (12b846ab8 2015-03-09) (built 2015-03-09)`.

**Comment by hugoduncan** [comment]
Changing the function, `f` above to the following prevents the assertion from triggering.

```rust
    fn f(&self, path: &Path) -> FileMeta {
        let m = FileMeta;
        let p = PathBuf::new(path);
        match self.h2.get(&p) {
            Some(meta) => m,
            None => m
        }
    }
```

**Comment by blaenk** [comment]
Yeah this one is ridiculous. It's been going on for a loooong while. Having to create a pathbuf kind of defeats the purpose of path. I think this should be higher priority.

btw you can make that `self.h2.get(&path.to_path_buf())`. Still dumb though.

**Comment by luqmana** [comment]
Problem seems to be with matching on DST structs. Here's a reduced test case:

```Rust
pub struct MyPath {
    inner: [u8]
}

pub fn bar(t: &MyPath) {
    match *t {
        MyPath { ref inner } => {}
    }
}

fn main() {}
```
[Playpen](http://is.gd/FjqsXi)
