### ISSUE TITLE
StrExt::splitn requires a DoubleEndedSearcher whereas StrExt::split does not

### ISSUE THREAD

**Issue by rnijveld** [rust-lang/rust#23262]
Wanting to limit your splits to a certain number suddenly requires the pattern to implement `DoubleEndedSearcher`, so the following code fragment using strings as splits fails:

```rust
fn main() {
   let v1: Vec<_> = "test::thing::test".split("::").collect();
   let v2: Vec<_> = "test::thing::test".splitn(1, "::").collect();
}
```

With:
```
<anon>:3:54: 3:63 error: type `core::str::SplitN<'_, &str>` does not implement any method in scope named `collect`
<anon>:3    let v2: Vec<_> = "test:thing:test".splitn(1, ":").collect();
                                                              ^~~~~~~~~
```

I would expect both of them to have pretty much the same requirements as for the pattern argument.

**Comment by sfackler** [comment]
At the very least, the trait bound should be placed on `splitn` as well so you get a compilation error in the right place.

**Comment by shepmaster** [comment]
@sfackler some [conversation on the PR](https://github.com/rust-lang/rust/pull/23269#issuecomment-79037367) indicates that we aren't going to add the trait bounds on the method.
