### ISSUE TITLE
Add a raw pretty printer for the metadata format

### ISSUE THREAD

**Issue by catamorphism** [rust-lang/rust#2326]
Maybe everybody else is really good at this, but I find it really frustrating to debug issues with inconsistencies (introduced by me) between the decoder and encoder. I spent several hours just now tracking down a problem that turned out to be because I was encoding a type with a tag around it, but the decoder was expecting the raw type string with no tag. If I'd had a way to dump out the EBML being encoded and decoded, this would have been easy to see. I asked someone (can't remember who) about this a while ago, and they said that pretty-printing EBML would be hard to do because there's no DTD. So, even if it would require effort, I'd really like a way to pretty-print EBML, since it seems to me like it would save debugging effort.

**Comment by steveklabnik** [comment]
Triage: no change. There have been some large changes to metadata in the last few months, but that doesn't really apply here, to my knowledge.

@lifthrasiir did you do anything related to this when you worked on reform?

**Comment by lifthrasiir** [comment]
@steveklabnik I have used an [ad-hoc decoder](https://github.com/rust-lang/rust/issues/21482#issuecomment-70963411) to analyze metadata bloat, but that's all. (Also, that decoder does not support the current metadata format, but it is not very hard to adapt.)

**Comment by arielb1** [comment]
I also have a decoder at arielb1/rtypes

**Comment by brson** [comment]
Nice to have, but I don't think we need a tracking issue.
