### ISSUE TITLE
Constructors that immediately copy a value to a pointer are not optimized; stack allocation still occurs

### ISSUE THREAD

**Issue by devyn** [rust-lang/rust#23273]
I have a little kernel project going on and I'm not really at the point where I'm ready to start porting actual Rust libraries like `liballoc` yet, so I have a little mock `Box` type instead. But I need to be able to allocate large structs, and the typical pattern is like this:

```rust
Box::new(Big::new())
```

With `opt-level=0` and `std::boxed::Box`, Rust still makes a > 8192 byte allocation on the stack (I'll include the Rust code later, but basically it's an 8192-byte struct):

```gas
    50ed:       48 81 ec 18 20 00 00    sub    $0x2018,%rsp
```

which it then goes on to clear and copy. However, with `opt-level=2` this goes away and Rust optimizes it out:

```gas
    cab6:       be 00 20 00 00          mov    $0x2000,%esi
...
    cace:       e8 fd 83 ff ff          callq  4ed0 <mmap@plt>
```

(As I understand it, `mmap` returns zeroed memory here anyway.)

So here's the problematic Rust code, then:

```rust
#![feature(core)]
#![feature(unique)]

use std::ptr::{self, Unique};

struct MyBox<T> {
    ptr: Unique<T>
}

impl<T> MyBox<T> {
    fn new(value: T) -> MyBox<T> {
        unsafe {
            let p = 0xdeadbeef as *mut T;

            ptr::write(p.as_mut().expect("out of memory"), value);

            MyBox { ptr: Unique::new(p) }
        }
    }
}

struct Big {
    array1: [u64; 512],
    array2: [u64; 512],
}

impl Big {
    fn new() -> Big {
        Big { array1: [0; 512], array2: [0; 512] }
    }
}

fn main() {
    let _b = MyBox::new(Big::new());
}
```

And this is what it ends up as at even `opt-level=3`:

```gas
    503e:       48 81 ec 00 20 00 00    sub    $0x2000,%rsp
    5045:       48 8d 1c 24             lea    (%rsp),%rbx
    5049:       31 f6                   xor    %esi,%esi
    504b:       ba 00 20 00 00          mov    $0x2000,%edx
    5050:       48 89 df                mov    %rbx,%rdi
    5053:       e8 a8 fa ff ff          callq  4b00 <memset@plt>
    5058:       bf ef be ad de          mov    $0xdeadbeef,%edi
    505d:       ba 00 20 00 00          mov    $0x2000,%edx
    5062:       48 89 de                mov    %rbx,%rsi
    5065:       e8 36 fe ff ff          callq  4ea0 <memcpy@plt>
    506a:       48 81 c4 00 20 00 00    add    $0x2000,%rsp
```

Really, it should optimize that out to a `memset` directly at `0xdeadbeef`, shouldn't it? This is a contrived example, but I'm getting the same result when calling out to my own memory allocator function.

## Meta

`rustc --version --verbose`:

```
rustc 1.0.0-nightly (12b846ab8 2015-03-09) (built 2015-03-10)
binary: rustc
commit-hash: 12b846ab80ca054d2fbfb0320d33badbd5ef0112
commit-date: 2015-03-09
build-date: 2015-03-10
host: x86_64-unknown-linux-gnu
release: 1.0.0-nightly
```

**Comment by huonw** [comment]
The currently-gated `box` syntax is designed to handle this, e.g. `box Big::new()` should do what you want.

**Comment by devyn** [comment]
Will `box` work with my custom `Box-like` type? It's in a different module; `kernel::memory::Box` instead.

**Comment by devyn** [comment]
Additionally I'm not sure if I can even do that, because I need to allocate the box at a specific memory alignment (0x1000)

**Comment by pnkfelix** [comment]
@devyn see https://github.com/rust-lang/rfcs/blob/master/text/0809-box-and-in-for-stdlib.md

you won't be able to implement your own `box` in *stable* code (not yet), but the protocol listed in the [appendix A](https://github.com/rust-lang/rfcs/blob/master/text/0809-box-and-in-for-stdlib.md#appendix-a-sample-operator-traits) should be expressive enough to both:
 1. handle your type specially, and
 2. force a particular memory alignment.

**Comment by dotdash** [comment]
FWIW, LLVM can't optimize the second example, because it relies on call slot optimization to do that, and that requires that the memcpy destination is guaranteed to not trap when being written to. 
This is of course not the case for arbitrary pointers.

**Comment by steveklabnik** [comment]
Because this is not a bug, I'm giving it a close.
