### ISSUE TITLE
docs: dead link

### ISSUE THREAD

**Issue by ryanmjacobs** [rust-lang/rust#23306]
http://doc.rust-lang.org/book/hello-world.html

Where it says, "We provide some sample configurations for various editors." It links to [CONFIGS.html](https://github.com/rust-lang/rust/tree/master/src/etc/CONFIGS.html) instead of [CONFIGS.md](https://github.com/rust-lang/rust/blob/master/src/etc/CONFIGS.md).

See the different file extensions? However, when you look at the [source file](https://raw.githubusercontent.com/rust-lang/rust/master/src/doc/trpl/hello-world.md), it has the proper link. Maybe the site hasn't been rebuilt or something?

**Comment by steveklabnik** [comment]
We have a bug open for this somewhere, but basically, it automatically translates the extension somewhere in the generation. Thanks for reporting!
