### ISSUE TITLE
Add VecDeque::into_vec and VecDeque::make_contiguous

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#23308]
VecDeque currently can't be turned into a vector and can't be modified so that as_slices returns one contiguous slice.

**Comment by mahkoh** [comment]
In general moving between VecDeque <-> Vec seems like a good idea.

**Comment by djmally** [comment]
I will take a look at this.

**Comment by mahkoh** [comment]
First you have to write an RFC.
