### ISSUE TITLE
RefCell::borrow does not pass borrow-check without a seemingly no-op let binding

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#23338]
When upgrading Rust in Servo, many usages of `RefCell::borrow` that were previously fine now cause borrow-check errors [like this](https://github.com/servo/servo/commit/7fbd43f0ad0ceab377403d7416934ee32feabc88?diff=unified#diff-016eef304e69674de212b7fbcd9330fdL678):
```
components/script/dom/xmlhttprequest.rs:678:9: 678:13 error: `self` does not live long enough
components/script/dom/xmlhttprequest.rs:678         self.status_text.borrow().clone()
                                                                               ^~~~
components/script/dom/xmlhttprequest.rs:677:39: 679:6 note: reference must be valid for the destruction scope surrounding block at 677:38...
components/script/dom/xmlhttprequest.rs:677     fn StatusText(self) -> ByteString {
components/script/dom/xmlhttprequest.rs:678         self.status_text.borrow().clone()
components/script/dom/xmlhttprequest.rs:679     }
components/script/dom/xmlhttprequest.rs:677:39: 679:6 note: ...but borrowed value is only valid for the block at 677:38
components/script/dom/xmlhttprequest.rs:677     fn StatusText(self) -> ByteString {
components/script/dom/xmlhttprequest.rs:678         self.status_text.borrow().clone()
components/script/dom/xmlhttprequest.rs:679     }
```

This error message makes no sense to me, the two blocks it talks about are the same.

This can be worked around by binding the result of `.borrow()` with `let` before using it, enough though such a change looks like a no-op:

```diff
 fn StatusText(self) -> ByteString {
-     self.status_text.borrow().clone()
+     let status_text = self.status_text.borrow();
+     status_text.clone()
}

**Comment by alexcrichton** [comment]
cc @pnkfelix

**Comment by larsbergstrom** [comment]
@SimonSapin has also mentioned that there are some cases (e.g., in our "script" crate) where even this transformation does not work.

cc @nikomatsakis

**Comment by SimonSapin** [comment]
I got stuck at some point but @jdm managed to find work arounds https://github.com/servo/servo/commit/0c12dd9007475886a642a8af8072362824fa852f

**Comment by pnkfelix** [comment]
This may be a consequence of the new scoping rules introduced in #21657.  We may attempt to address coding patterns like this by implementing #22323; but implementing that is not a 1.0-blocking issue (i.e. it may wait until after 1.0 is released, depending on other priorities).

**Comment by pnkfelix** [comment]
cc #22321

**Comment by nikomatsakis** [comment]
Standalone test case:

```rust
use std::cell::RefCell;

fn foo(x: RefCell<String>) -> String {
  x.borrow().clone()
}

fn main() { }
```

**Comment by pnkfelix** [comment]
leaving nominated tag to talk again next week, assigning to self to investigate.

**Comment by pnkfelix** [comment]
Another work-around worth noting (if only because it provides a hint at the problem here):
```rust
fn foo(x: RefCell<String>) -> String {
  let t = x.borrow().clone();
  t // this works!
}
```

I think this is an artifact of our temporary r-value rules, in particular the one that says that all temporaries for the tail expression in a block are assigned the lifetime of the *parent* of the block (that is, they can outlive the block).

**Comment by pnkfelix** [comment]
(Having said that, I *would* like to see if we can still fix this in some way.  But I no longer see this as a potential smoking gun pointing at some fundamental flaw in the system.  So I've removed the I-nominated tag.)

**Comment by pnkfelix** [comment]
Actually, according to the current dynamic semantics, fn parameters *already* are torn down after the fn body is torn down.

So it should be entirely sound (perhaps even a legitimate bug fix, not sure) to make the code-extents reflect the fact that the temporaries from the tail expression for the fn-body are destroyed before the parameters are dropped (i.e., that the parameters strictly outlive all of the r-value temporaries of the fn body).

Here is some demo code illustrating this (note also that the behavior differs if one passes `--cfg nested`, but in either case the parameters still outlive the r-value temporaries.

```rust
struct D(&'static str, u32);

impl Drop for D {
    fn drop(&mut self) {
        println!("Dropping D({}, {})", self.0, self.1);
    }
}

impl D {
    fn incr(&self, name: &'static str) -> D {
        D(name, self.1 + 1)
    }
}

#[cfg(not(nested))]
fn foo(a1: D, b1: D) -> (&'static str, D) {
    let _b2 = b1.incr(b1.0);
        let _a2 = a1.incr(a1.0);
        let b3 = b1.incr("temp1").incr(b1.0);
        println!("made b2 a2 and b3");
        ("foo_direct", b3.incr("temp2").incr(b3.0))
}

#[cfg(nested)]
fn foo(a1: D, b1: D) -> (&'static str, D) {
    let _b2 = b1.incr(b1.0);
    {
        let _a2 = a1.incr(a1.0);
        let b3 = b1.incr("temp1").incr(b1.0);
        println!("made b2 a2 and b3");
        ("foo_nested", b3.incr("temp2").incr(b3.0))
    }
}

fn main() {
    let (name, result) = foo(D("a", 1), D("b", 1));
    println!("called {}, got result D({}, {})",
             name, result.0, result.1);
}
```

**Comment by pnkfelix** [comment]
Okay, I'm pretty happy with the solution given in #24021.

**Comment by agrover** [comment]
@pnkfelix this still is present w.r.t expression blocks, though, which are pretty useful when attempting to control the length of borrows. Using workaround in https://github.com/rust-lang/rust/issues/23338#issuecomment-88974864 for now but it would be great for this to work nicely at some point, it led me to think I was going crazy :smile:
