### ISSUE TITLE
make doc/index.html shouldn’t need stage2

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#23349]
I can’t see any reason why docs can’t be built by stage1 rustdoc. This should be fixed to allow faster iteration cycles for people working on it.

**Comment by steveklabnik** [comment]
Triage: as far as I know, this is still true today. However, with rustbuild,

```
$ python src/bootstrap/bootstrap.py --stage 1 --step doc
<output>
Documenting stage1 std (x86_64-unknown-linux-gnu)
```

Given that `make` is eventually on its way out, and this is fixed in rustbuild already, and this is an old ticket with no other comments, I'm going to give it a close.
