### ISSUE TITLE
Passing arguments using the FFI overwrites the program name

### ISSUE THREAD

**Issue by Nullreff** [rust-lang/rust#23343]
I'm trying to pass arguments to a C function using the FFI.  This works just fine with regular arguments but when arguments like `--arg1` are included things get weird.  Sample code to reproduce this issue is available here: https://github.com/Nullreff/argsexample

~~~text
> uname -a
Linux carbon 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt7-1 (2015-03-01) x86_64 GNU/Linux

> gcc --version
gcc (Debian 4.9.2-10) 4.9.2

> rustc --version --verbose
rustc 1.0.0-nightly (c9b03c24e 2015-03-12) (built 2015-03-13)
binary: rustc
commit-hash: c9b03c24ec346e6405883032094f47805ef9c43e
commit-date: 2015-03-12
build-date: 2015-03-13
host: x86_64-unknown-linux-gnu
release: 1.0.0-nightly

> ./test.sh
Rust: ./main arg1 arg2 arg3 
C:    ./main arg1 arg2 arg3 

Rust: ./main --arg1 arg2 arg3 
C:    --arg1 --arg1 arg2 arg3 

Rust: ./main arg1 --arg2 arg3 
C:    --arg2 arg1 --arg2 arg3 

Rust: ./main arg1 arg2 --arg3 
C:    --arg3 arg1 arg2 --arg3 

Rust: ./main --arg1 --arg2 arg3 
C:    --arg2 --arg2 --arg2 arg3 

Rust: ./main --arg1 arg2 --arg3 
C:    --arg3 --arg3 arg2 --arg3 

Rust: ./main arg1 --arg2 --arg3 
C:    --arg3 arg1 --arg3 --arg3 

Rust: ./main --arg1 --arg2 --arg3 
C:    --arg3 --arg3 --arg3 --arg3

**Comment by alexcrichton** [comment]
The program you've linked to is actually exhibiting memory corrupting, likely leading to the oddness that you're seeing. [This line](https://github.com/Nullreff/argsexample/blob/master/main.rs#L19) is creating a `CString`, getting a pointer to it, and then deallocating the `CString` (as it is a temporary). This means that all the pointers passed to C are dangling references.

You'll probably want to create a `Vec<CString>` on the stack and then from that create a `Vec<*const c_char>`, for example:

```rust
let args = args().map(|arg| CString::new(arg).unwrap()).collect::<Vec<_>>();
let arg_ptrs = args.iter().map(|arg| arg.as_ptr()).collect::<Vec<_>>();
unsafe {
    printargs(arg_ptrs.len(), arg_ptrs.as_ptr());
}
```

More information about this footgun can be found in https://github.com/rust-lang/rust/issues/16035.

**Comment by Nullreff** [comment]
Yep, just ran it under valgrind and realized I was using after freeing, oops.  Thanks for the help your solution worked perfectly.
