### ISSUE TITLE
Can't provide non-overlapping trait impls based on assoc type trait bound

### ISSUE THREAD

**Issue by cristicbz** [rust-lang/rust#23341]
``` rust
use std::iter::IntoIterator;

trait Foo {
    fn foo(&self);
}

trait Bar {
    fn bar(&self);
}

impl<I> Foo for I
        where I: IntoIterator,
              I::Item: Bar {
    fn foo(&self) {
    }
}

impl Foo for Vec<u8> {
    fn foo(&self) {
    }
}

fn main() {}
```

fails with

```
<anon>:11:1: 16:2 error: conflicting implementations for trait `Foo` [E0119]
<anon>:11 impl<I> Foo for I
<anon>:12         where I: IntoIterator,
<anon>:13               I::Item: Bar {
<anon>:14     fn foo(&self) {
<anon>:15     }
<anon>:16 }
<anon>:18:1: 21:2 note: note conflicting implementation here
<anon>:18 impl Foo for Vec<u8> {
<anon>:19     fn foo(&self) {
<anon>:20     }
<anon>:21 }
```

See [playpen](http://is.gd/6OmhAu).

Since `u8` does not implement `Bar`, the impl-s are actually non-overlapping.

Possibly related to #20400.

**Comment by kdeeee** [comment]
still occur this error in` rustc 1.11.0 (9b21dcd6a 2016-08-15)`
error message is `conflicting implementations of trait 'Foo' for type 'std::vec::Vec<u8>'`

**Comment by dhardy** [comment]
This is causing me some problems!

https://github.com/dhardy/rand/blob/master/src/distributions/default.rs#L41

**Comment by dtolnay** [comment]
Let's continue to track this under #20400 -- the resolution will surely be the same and it's better to keep the relevant discussion in one place.
