### ISSUE TITLE
rustdoc search unbearable on small screens

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#23340]
![search](https://cloud.githubusercontent.com/assets/1882250/6641702/c97b15ec-c99f-11e4-8963-92943fe65e19.png)

**Comment by steveklabnik** [comment]
What is 'unbearable'?

**Comment by mahkoh** [comment]
rustdoc search

If you can look at that screenshot without noticing a problem then trying to explain it is a waste of time.

**Comment by wycats** [comment]
@steveklabnik Don't you agree that the existing docs would make it very hard for even an intermediate-level Rust programmer to figure out what's going on?

**Comment by wycats** [comment]
I can see at least three different issues here.

1. There are a lot of `finally`s, and it's not clear here which you should be looking at
2. The descriptions are truncated badly, so it's hard to even get a sense of where you should start looking
3. The list doesn't include information about whether each entry is a trait, struct, typedef, method, or whatever.

**Comment by steveklabnik** [comment]
I noticed #2, but didn't realize #1 or #3. This is why reports more than just "unbearable" is important, and why it's not a "waste of time" to spell out what you mean.

**Comment by mahkoh** [comment]
You saw that the documentation provided for "Finally" is "A trait for executing a..." but you didn't consider that unbearable. For your own sake I'll assume that you're kidding.

**Comment by huonw** [comment]
@mahkoh it would take you 20 seconds to write a sentence or two to make issues clearer as you file them. You have been *repeatedly* requested to do things like this. Something that is obvious to you is not obvious to everyone.

While I agree that this specific issue is reasonably clear, it would still be improved by some text and/or a link to an example search page. Doing this helps everyone else help you.

**Comment by mahkoh** [comment]
>While I agree that this specific issue is reasonably clear

It's so clear that @wycats, @steveklabnik, I, and apparently you were able to notice the problem independently without any additional explanation.

>and/or a link to an example search page

I don't see how that's better than a screenshot.

**Comment by tomjakubowski** [comment]
> It's so clear that @wycats, @steveklabnik, I, and apparently you were able to notice the problem independently without any additional explanation.

I noticed a few things that some might argue are problems and a couple things I thought were definitely problems. I had absolutely no idea which of those specifically you were reporting here because you just posted a screenshot with minimal context and expected it to be perfectly clear. People on the Internet can be many things but I've never met one who's a mind reader.

**Comment by mahkoh** [comment]
Apparently people are more interested in discussing the way the issue was posted than the issue itself. In that case it is just wasting the time of everyone involved (including myself) and I don't want that. Instead I'll try to submit a PR in the following days that fixes the issue.

**Comment by huonw** [comment]
A link makes it super easy for someone inclined to fix the issue to dive in with their browser's dev tools.

In any case, your behaviour is horrid. A clarification question was asked (i.e. there was some confusion/inclarity) and your responses were glib, disrespectful and antagonistic. Maybe you think the question is silly, but there's absolutely no reason to be vile. It would've been trivial to spend the time it took to be unpleasant to give a few dot points like @wycats did.
