### ISSUE TITLE
Always evaluate the expression in [expr; n]

### ISSUE THREAD

**Issue by dotdash** [rust-lang/rust#23354]
Currently, `[panic!(); 0]` will panic, but `let x = [panic!(); 0]` will not, because the expression is not evaluated in that case.

**Comment by rprichard** [comment]
Also, `let x = [panic!(); 2];` crashes the compiler.  Maybe it's the same issue?
```
PHINode should have one entry for each predecessor of its parent basic block!
  %4 = phi i64 [ 0, %entry-block ], [ %5, %expr_repeat ]
LLVM ERROR: Broken function found, compilation aborted!
```

**Comment by dotdash** [comment]
@rprichard Thanks for the reminder, #23365 fixes that as well.
