### ISSUE TITLE
std::prelude::v1 still references old_path and old_io

### ISSUE THREAD

**Issue by kballard** [rust-lang/rust#23377]
`std::prelude::v1` is still importing items from `std::old_path` and `std::old_io`, which are both now deprecated. The prelude should be updated to import the relevant items from `std::path` and `std::io` instead. `std::prelude::v1` is already marked stable, which seems like a mistake given that it contained these old items. We could transition to a new `std::prelude::v2`, but it seems odd to do that before Rust 1.0, so I think we should accept that it was incorrectly stabilized and modify `std::prelude::v1`.

/cc @alexcrichton

**Comment by kballard** [comment]
Since `std::prelude::v1` still re-exports `std::old_io::Writer` it turns out that you cannot use the `write!()` macro after importing `std::io::prelude::*` (or `std::io::Write`) as it results in an ambiguous call to `write_fmt()`.

**Comment by pnkfelix** [comment]
1.0 beta, P-backcompat-libs.   ( @alexcrichton says there's a PR in the queue.)
