### ISSUE TITLE
Regression test 20797 depends on /home directory

### ISSUE THREAD

**Issue by bennofs** [rust-lang/rust#23373]
The regression tests for issue #20797 needs the /home directory to be present. I hit this problem when trying to build rust master/alpha2 with Nix, which uses chroots for building where /home is not available.

Running `make check` will produce the following error if no /home directory is present:
```
executing x86_64-unknown-linux-gnu/test/run-pass/issue-20797.stage2-x86_64-unknown-linux-gnu 
------stdout------------------------------

------stderr------------------------------
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: IoError { kind: FileNotFound, desc: "couldn\'t read directory", detail: Some("no such file or directory (No such file or directory); path=/home") }', /tmp/nix-build-rustc-1.0.0-dev-g91bdf23.drv-0/rust-91bdf23/src/libcore/result.rs:744

------------------------------------------
```

It would be nice if the test suite could be run without needing /home.

**Comment by fhahn** [comment]
I think this issue was fixed in https://github.com/rust-lang/rust/commit/212e03181e422f569b6426bc08b713a9efc0d0eb .

Now the walker is not executed and the path is not accessed  any more.

**Comment by bennofs** [comment]
Looks OK. Thanks
