### ISSUE TITLE
std::io::prelude should stop renaming Seek

### ISSUE THREAD

**Issue by kballard** [rust-lang/rust#23378]
`std::io::prelude` currently re-exports `std::io::Seek` as `NewSeek`. This should be changed before 1.0, as the renaming only makes sense in light of the `old_io` migration, and `old_io` is now deprecated. `std::io::prelude` is already declared stable, but I think that was a mistake and we should just go ahead and modify it.

This is related to #23377 (`std::prelude::v1` still re-exports `std::old_io::Seek`).

/cc @alexcrichton

**Comment by pnkfelix** [comment]
1.0 beta, P-backcompat-libs. ( @alexcrichton says there's a PR in the queue.)
