### ISSUE TITLE
Readers of the docs don't know how to improve the docs

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#23388]
This issue comes way too often: readers of the docs don't know how to improve the docs. 

So let's fix this. To start the discussion, I propose the following solution:

Put a small image on a corner of each doc page yelling "Help us improve this page!". That image could link directly to the markdown or source code file, so that people can edit the file directly on github and send a pull-request without needing to fork first. This is as ergonomic as it gets, and preserves the pull-request code-review process.

A different solution would be a kind of wiki-based system for the documentation, but integrating it with rust-doc is a very large task.

**Comment by steveklabnik** [comment]
I am definitely _not_ in favor of some kind of wiki or comment system, but could see linking to GitHub.

**Comment by gnzlbg** [comment]
@steveklabnik I mentioned the wiki system as an alternative because being able to fix or improve the documentation in place is very attractive. This has worked really good for e.g. `cppreference.com`.

The main drawback of the wiki system is that dealing with spammers and reverting bad modifications takes a _huge_ amount of time. For cmake, vtk, and many others the wiki system hasn't worked out at all. 

I am not in favor of a wiki system either.

**Comment by steveklabnik** [comment]
Totally, and it's good to think of alternatives, just placing my vote. :smile:

**Comment by steveklabnik** [comment]
Today, the front page of the book links to the source, so I'm gonna close this. I don't want to link on every single page.
