### ISSUE TITLE
`by_ref` multiple applicable methods in scope

### ISSUE THREAD

**Issue by BurntSushi** [rust-lang/rust#23393]
I'm not sure if this was intended or not, but `by_ref` on `io::Cursor` is broken when both the `Read` or `Write` traits are in scope:

```rust
#![feature(io)]

use std::io::{self, Read, Write};

fn main() {
    let mut c = io::Cursor::new(b"abcdef".to_vec());
    let s = c.by_ref().chars().collect::<Result<String, _>>().unwrap(); 
    println!("{}", s);
}
```

This gives a ["multiple applicable methods in scope" error](http://is.gd/iCiLKU).

I'm working around this by using:

```rust
let s = Read::by_ref(&mut c).chars().collect::<Result<String, _>>().unwrap();
```

**Comment by alexcrichton** [comment]
This is an unfortunate (but known) deficiency of the method right now. The good news is that the implementation means that UFCS isn't even necessary, you can do:

```rust
let s = (&mut c).chars().collect::<Result<String, _>>().unwrap();
```

**Comment by steveklabnik** [comment]
Since it's not a bug, I'm giving this a close.
