### ISSUE TITLE
libc::consts::os::extra::MAP_NONRESERVE should be named MAP_NORESERVE

### ISSUE THREAD

**Issue by GBGamer** [rust-lang/rust#23408]
This is incorrect, according to the `mmap` man page.

I placed this issue on the libc repo first, because I didn't realize that libc is a core library :P

**Comment by GuillaumeGomez** [comment]
I did a PR to "fix" it. Let's see what others say about it.

**Comment by steveklabnik** [comment]
closed by https://github.com/rust-lang/rust/pull/23409
