### ISSUE TITLE
rustc panic

### ISSUE THREAD

**Issue by MarkSwanson** [rust-lang/rust#23418]
<short summary of the bug>

I tried this code:

use std::io;

fn test() {

    #[derive(Debug)]
    enum E {
        BadStatusCode { code: i32},
        IoError(io::Error)
    }
    let e1 = E::IoError(io::Error::last_os_error());
    let e = E::BadStatusCode {code: 0};
    println!("e:{:?}", e.code);

}

<I expected to see>

e:0

Instead, this happened: <explanation>

## Meta

`rustc --version --verbose`:

$ rustc --version --verbose
rustc 1.0.0-nightly (30e1f9a1c 2015-03-14) (built 2015-03-15)
binary: rustc
commit-hash: 30e1f9a1c2bf7134135800bc9afd082773defadc
commit-date: 2015-03-14
build-date: 2015-03-15
host: x86_64-apple-darwin
release: 1.0.0-nightly

$ !car
cargo build
   Compiling rust-bugms1 v0.0.1 (file:///Users/maswanso/src/external/rust-bugms1)
src/lib.rs:13:24: 13:30 error: attempted access of field `code` on type `test::E`, but no field with that name was found
src/lib.rs:13     println!("e:{:?}", e.code);
                                     ^~~~~~
note: in expansion of format_args!
<std macros>:2:43: 2:76 note: expansion site
<std macros>:1:1: 2:78 note: in expansion of println!
src/lib.rs:13:5: 13:32 note: expansion site
error: internal compiler error: ID not mapped to struct fields: enum test::E::E (id=9)
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libsyntax/diagnostic.rs:190

stack backtrace:
   1:        0x10593cd2b - sys::backtrace::write::ha860f032f06dd89afCC
   2:        0x105965b0d - panicking::on_panic::h6a18b44186bb57afDsI
   3:        0x105885a77 - rt::unwind::begin_unwind_inner::hd2534fa4a37f06f1EbI
   4:        0x105043d4e - rt::unwind::begin_unwind::h4894477901674685092
   5:        0x10504468c - diagnostic::Handler::bug::hae51981d40ecc46blgB
   6:        0x102a35e4c - middle::ty::lookup_struct_fields::h9a0c1e2e0f517a28RJ5
   7:        0x10209f60e - check::check_expr_with_unifier::suggest_field_names::h5f2000e59cbd55ebBwq
   8:        0x102072154 - check::check_expr_with_unifier::check_field::h69ce2888184f32bcvqq
   9:        0x10208d88f - check::check_expr_with_unifier::h4298816897439060846
  10:        0x10208957a - check::check_expr_with_unifier::h17404064713139209684
  11:        0x102070653 - check::check_expr_with_unifier::closure.32612
  12:        0x102079a5f - vec::Vec<T>.FromIterator<T>::from_iter::h5728053635905335577
  13:        0x102075915 - check::check_expr_with_unifier::h14779708369100304031
  14:        0x101f8b5bc - check::_match::check_match::hb4973a0390014f4fSab
  15:        0x10208d186 - check::check_expr_with_unifier::h4298816897439060846
  16:        0x102063c21 - check::check_expr_with_unifier::h3544831391636284546
  17:        0x10203a61c - check::check_argument_types::h01f4d41a36cb60e96pp
  18:        0x102036b17 - check::callee::confirm_builtin_call::he6a26f80098a0ceftam
  19:        0x1020354e3 - check::callee::check_call::haef3d250ae4d2b32V0l
  20:        0x10206125d - check::check_expr_with_unifier::h3544831391636284546
  21:        0x10203a61c - check::check_argument_types::h01f4d41a36cb60e96pp
  22:        0x102036b17 - check::callee::confirm_builtin_call::he6a26f80098a0ceftam
  23:        0x1020354e3 - check::callee::check_call::haef3d250ae4d2b32V0l
  24:        0x102092da7 - check::check_expr_with_unifier::h2091165693314502420
  25:        0x102050035 - check::check_block_with_expected::h6f13d7a87125a2baeYr
  26:        0x102032015 - check::check_fn::h77a17bd13aefe783vin
  27:        0x10204ca90 - check::check_bare_fn::hceabbc00e6b48601b8m
  28:        0x102044c8c - check::check_item::h33cadcb399ed69c3Pqn
  29:        0x10211dcd2 - check_crate::closure.35787
  30:        0x102118960 - check_crate::ha12d154f9f64ecd4O3B
  31:        0x101e46807 - driver::phase_3_run_analysis_passes::h1215c80c4b6a391fqGa
  32:        0x101e2e4d2 - driver::compile_input::hf43d1abc1c271827Rba
  33:        0x101eef113 - run_compiler::hd026487fba5e11ffx2b
  34:        0x101eeccbb - thunk::F.Invoke<A, R>::invoke::h4638332392346812264
  35:        0x101eebb7f - rt::unwind::try::try_fn::h13573825556050994607
  36:        0x1059e34a8 - rust_try_inner
  37:        0x1059e3495 - rust_try
  38:        0x101eec10c - thunk::F.Invoke<A, R>::invoke::h11626720109288632878
  39:        0x105952df2 - sys::thread::thread_start::hbdfebeda7d5c79d5sXG
  40:     0x7fff8a785898 - _pthread_body
  41:     0x7fff8a785729 - _pthread_start

Could not compile `rust-bugms1`.

**Comment by Stebalien** [comment]
I can't reproduce with rustc `1.1.0-nightly (c033d9828 2015-05-09) (built 2015-05-09)` (it fails to build but doesn't ICE).

**Comment by MarkSwanson** [comment]
Confirmed.
This no longer causes an ICE
Great!
