### ISSUE TITLE
Unboxed trait object can be stored in struct without lifetime

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#23410]
```rust
trait Foo { fn method(&self); }

struct Wrapper(Foo);

fn main() {}
```

It seems to me that this should be requiring a lifetime, e.g. `struct Wrapper<'a>(Foo + 'a);` or `struct Wrapper(Foo + 'static);`. However, it may be the intended behaviour too, nominating for clarification.

**Comment by ben0x539** [comment]
Isn't this [RFC 599](https://github.com/rust-lang/rfcs/pull/599)?

**Comment by nikomatsakis** [comment]
I agree this is RFC 599.

**Comment by pnkfelix** [comment]
not-a-bug, (as designed), closing.
