### ISSUE TITLE
SliceExt not implemented for &[u8]

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#23446]
Since SliceExt::split conflicts with BufRead::split, you have to use SliceExt::split(var, cond). But this doesn't give you auto-deref and if var == &&[u8] you get the confusing message that SliceExt is not implemented for &[u8] and you have to first notice that var is &&[u8] and then remember that SliceExt is implemented on [u8] and not &[u8].

**Comment by alexcrichton** [comment]
The purpose of the `SliceExt` trait is to provide *methods* on `&[u8]`, not to provide the ability to abstract over them. Now that [we have moved to inherent methods](https://github.com/rust-lang/rust/pull/23104) this is even more apparent. As a result this issue is also somewhat moot, so closing.
