### ISSUE TITLE
Remove `IndexMut` impl from various collections to prepare for possible `IndexSet` in the future

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#23448]
I believe we intend to eventually extend the index traits with the ability to override the `x[y] = z` syntax specifically using a trait like `IndexSet`. This would allow hashmaps to be used like `map[key] = value` and have that insert the key, unlike today where `map[key] = value` will panic if `key` is not already present.

To pave the way, the simplest thing is to remove the `IndexMut` operator from those collections where we would anticipate growing on demand.

I believe that would be `btree`, `hash_map`, and possible `vec_deque` and `vec_map`.

Thoughts?

cc @aturon @alexcrichton @Gankro

**Comment by nikomatsakis** [comment]
triage: P-backcompat-libs I-needs-decision (1.0 beta)

**Comment by nikomatsakis** [comment]
triage: P-backcompat-libs (1.0 beta)

**Comment by aturon** [comment]
I was just starting to prep a PR to resolve this by removing the impl, as you suggested. :)

**Comment by alexcrichton** [comment]
Don't we want to keep the implementation on `HashMap` for example to do something like `let a = &mut map[key]`?

**Comment by aturon** [comment]
@alexcrichton Depending on the exact way that `IndexSet` is done, it may not be possible to provide both modes of use. That is, we want to be able to write `map[key] = value` -- which we cannot today -- but it's not clear that you can do that and *also* support examples like the one you gave. In particular, that involves adjusting inference to determine whether or not a deref is in play.

For now, removing these impls will give us the most freedom when we do incorporate `IndexSet`.

**Comment by Gankro** [comment]
It seems weird to have this and insert -- insert has a return value, though. This would be a super-annoying ergonomic regression in the interim. What's the expected timeline for something like IndexSet? 1.1?

**Comment by Gankro** [comment]
Oh actually upon reflection most usages I know are Index, not IndexMut. Not as awful a regression.

**Comment by mahkoh** [comment]
>Depending on the exact way that IndexSet is done, it may not be possible to provide both modes of use.

It should be possible to move in, out, and take references with the `[]` operator. If that's not possible with the current design then the current design has to be changed instead of committing to yet another subpar design until 2.0.

**Comment by clouds56** [comment]
`IndexSet` sounds powerful and interesting, is there any RFC for it now?
