### ISSUE TITLE
Non-exhaustive if else returns ()

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#23444]
A non-exhaustive if else should not be permitted in expression position.

**Comment by huonw** [comment]
What's the motivation?

**Comment by mahkoh** [comment]
This is a `if let` bug.

```rust
fn f(x: bool, y: bool) -> i32 {
    if x {
        // lots of code here
        1
    } else if y {
        // lots of code here
        1
    }
}
```
already gives you the correct error message. But for `if let` it doesn't work.

**Comment by huonw** [comment]
Could you please add a code example about what you mean about `if let`?

**Comment by mahkoh** [comment]
```rust
fn f(x: Option<bool>, y: bool) -> i32 {
    if let Some(x) = x {
        // lots of code here
        1
    } else if y {
        // lots of code here
        1
    }
}
```

**Comment by mahkoh** [comment]
```
test5.rs:5:12: 8:6 error: if may be missing an else clause:
 expected `()`,
    found `i32`
(expected (),
    found i32) [E0308]
```
```
test5.rs:2:5: 8:6 error: mismatched types:
 expected `i32`,
    found `()`
(expected i32,
    found ()) [E0308]
```
Note the type order.

**Comment by huonw** [comment]
Thanks for that information.

It seems like the issue filed is jumping to conclusions about the best way to solve this, and maybe we could also just fix the underlying diagnostics bug(s) (i.e. make `if let` get the same sort of `else` error message)?

**Comment by mahkoh** [comment]
There is no jumping to conclusions here, just a confusion in the `if let` implementation. As I expected in the first post, `if else` is already not allowed in expression position if the type is not `()` and there is no unconditional else branch. The `if let` implementation is simply buggy.

**Comment by huonw** [comment]
The original issue didn't mention `if let` or its non-useful diagnostics which is what you latter clarified to be the motivation, so the issue *is* jumping a step or two ahead.

In any case, "disallowing `if else` in expression position" sounds like a language-grammar thing. `else`less `if`s are currently perfectly syntactically legal in expression position (useful for `match` arms). The requirement that it has type `()` is enforced by type checking, not the parser.

**Comment by mahkoh** [comment]
Trying to ruin another issue with off-topic nonsense that's not about the issue but the form of the issue, eh?

**Comment by huonw** [comment]
This isn't offtopic. I literally don't understand what the original issue is asking. My reading is that you want `let _: () = if foo {};` to be rejected, and I don't understand why that is the best way to solve poor diagnostics with `if let`.

**Comment by mahkoh** [comment]
So that's how it is.

**Comment by huonw** [comment]
I filed https://github.com/rust-lang/rust/issues/23460 about the diagnostics; thanks for noticing that.

**Comment by jakub-** [comment]
@mahkoh I would like to point out that as more of a bystander in this project myself, I often cringe when I see how passive aggressive you are when communicating with other people involved and that if I didn't know any better about this community, I could perhaps jump to a conclusion that it's generally toxic and to be stayed away from. Some other onlookers may not have the prior knowledge I have and thus get put off immediately. So I would personally request that you seriously reconsider the tone, if not on the basis of decency then at least on the basis of not actively, in my opinion, harming the project. Thanks.

**Comment by nikomatsakis** [comment]
Just my two cents: I like the type rule as is, and prefer to keep the tradition of having as many statements be expressions as possible (and I consider a unit return type for statements to be useful in various contexts, as well). Improving diagnostics is of course always valuable though.
