### ISSUE TITLE
associated type does not live long enough

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#23442]
This program fails to compile:

```rust
#![crate_type="rlib"]

use std::marker::PhantomData;

pub struct UnionedKeys<'a,K>
    where K: UnifyKey + 'a
{
    table: &'a mut UnificationTable<K>,
    root_key: K,
    stack: Vec<K>,
}

pub trait UnifyKey {
    type Value;
}

pub struct UnificationTable<K:UnifyKey> {
    values: Delegate<K>,
}

pub struct Delegate<K>(PhantomData<K>);
```

This was *supposed* to be fixed by https://github.com/rust-lang/rust/pull/22436, but apparently that fix is not working. I've been wanting to revisit the strategy there anyway, because it leads to infinite recursion in some cases and I'm not happy about it.

The error I see is:

```
/home/nmatsakis/tmp/bar.rs:5:1: 11:2 error: the associated type `<K as UnifyKey>::Value` may not live long enough [E0309]
/home/nmatsakis/tmp/bar.rs:5 pub struct UnionedKeys<'a,K>
/home/nmatsakis/tmp/bar.rs:6     where K: UnifyKey + 'a
/home/nmatsakis/tmp/bar.rs:7 {
/home/nmatsakis/tmp/bar.rs:8     table: &'a mut UnificationTable<K>,
/home/nmatsakis/tmp/bar.rs:9     root_key: K,
/home/nmatsakis/tmp/bar.rs:10     stack: Vec<K>,
                              ...
/home/nmatsakis/tmp/bar.rs:11:2: 11:2 help: consider adding an explicit lifetime bound `<K as UnifyKey>::Value: 'a`...
/home/nmatsakis/tmp/bar.rs:5:1: 11:2 note: ...so that the reference type `&'a mut UnificationTable<K>` does not outlive the data it points at
/home/nmatsakis/tmp/bar.rs:5 pub struct UnionedKeys<'a,K>
/home/nmatsakis/tmp/bar.rs:6     where K: UnifyKey + 'a
/home/nmatsakis/tmp/bar.rs:7 {
/home/nmatsakis/tmp/bar.rs:8     table: &'a mut UnificationTable<K>,
/home/nmatsakis/tmp/bar.rs:9     root_key: K,
/home/nmatsakis/tmp/bar.rs:10     stack: Vec<K>,
                              ...
```

**Comment by nikomatsakis** [comment]
The strategy I had in mind was to require that for every associated type `T` found in an impl:

    for<'a> (Self : 'a) => (T : 'a)

This allows us later to deduce that if `Self:'a`, then `T:'a`. However, I've not thought this all the way through, because I'm not 100% sure how I'm going to make use of that information. The vague idea was that when we have a requirement that `X::T : 'a`, we can possibly satisfy that if we can determine that `X : 'a`. (Note that we cannot deduce however that `X::T : 'a => X : 'a`, which might sometimes be nice.)

**Comment by nikomatsakis** [comment]
Ah, well, I can see why the original fix didn't work. Nothing in the current system allows it to deduce that `K:'a` implies `K::Value : 'a` -- but we CAN deduce that `&'a Foo<K> => K:'a and K::Value:'a`. Annoying.

**Comment by apasel422** [comment]
This appears to compile with `rustc 1.4.0-nightly (d50352419 2015-08-29)`.

**Comment by Eh2406** [comment]
There is a FIXME related to this issue,
https://github.com/rust-lang/rust/blob/master/src/libcore/convert.rs#L368
Now that the issue is closed can the FIXME be fix, or made more specific?
