### ISSUE TITLE
Lines iterator and read_line() don't recognize all unicode line endings

### ISSUE THREAD

**Issue by cessen** [rust-lang/rust#23453]
According to the documentation ([here](http://doc.rust-lang.org/std/io/trait.BufRead.html#method.read_line) and [here](http://doc.rust-lang.org/std/io/trait.BufRead.html#method.lines)) the `Lines` iterator and `read_line()` function only recognize the `U+000A` (or `LF`) codepoint as a line ending.

However, unicode has several other codepoints (and one grapheme) that are supposed to be recognized as line endings as well.  These include at least:

- `CR` `(U+000D)`
- `CR+LF` `(U+000D + U+000A)`
- `NEL` `(U+0085)`
- `LS` `(U+2028)`
- `PS` `(U+2029)`

See [Unicode Standard Annex #14](http://www.unicode.org/reports/tr14/tr14-33.html) for more details.

Is this an oversight, or an explicit design decision?  It strikes me as buggy behavior given Rust's strong unicode support throughout the rest of the standard library.

**Comment by alexcrichton** [comment]
This is currently an explicit decision, but one that wasn't necessarily advertised very widely. Note that for comparison, however, the [`str::lines` function](http://doc.rust-lang.org/std/str/trait.StrExt.html#tymethod.lines) has the same behavior.

**Comment by steveklabnik** [comment]
Given that this was explicit, i'm closing as not-a-bug.
