### ISSUE TITLE
Decide if Wrapping/WrappingOps should be in the prelude

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#23454]
The [associated RFC](https://github.com/rust-lang/rfcs/blob/master/text/0560-integer-overflow.md) does not mention these two items being in the prelude, and we should probably decide whether or not they should be there.

**Comment by alexcrichton** [comment]
triage: I-needs-decision, P-backcompat-libs (1.0 beta)

**Comment by aturon** [comment]
cc @nikomatsakis @brson @huonw

**Comment by aturon** [comment]
cc @pnkfelix

**Comment by pnkfelix** [comment]
Decision: We're not going to put these things into the prelude.

So they need to be removed from the prelude.

**Comment by alexcrichton** [comment]
Resolved in #23549
