### ISSUE TITLE
Literal overflow warnings should only apply to decimal.

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#23463]
E.g. 0x8888i16 should not warn. Similar to binary operations | and &, hexadecimal, binary, and octal literals are often used to specify the concrete representation in memory whereas decimal literals are used to represent abstract values.

@pnkfelix @nikomatsakis

**Comment by theemathas** [comment]
Also note that `-(0x8000i16)` which evaluates to `-32768` (hex: `0x8000i16`, which is the minimum value of `i16`) currently does *not* warn.

**Comment by theemathas** [comment]
cc #22020
