### ISSUE TITLE
Collection terminology is inconsistent

### ISSUE THREAD

**Issue by apasel422** [rust-lang/rust#23478]
The docs for the collections in `std` are inconsistent with their terminology. This sometimes affects argument names as well.

The maps use `key` and `value` consistently, but vary otherwise. For example, `BTreeMap` has:

- [`insert`](http://doc.rust-lang.org/std/collections/struct.BTreeMap.html#method.insert): "Inserts a __key-value pair__ from [_sic_] the map."
- [`iter`](http://doc.rust-lang.org/std/collections/struct.BTreeMap.html#method.iter): "Gets an iterator over the __entries__ of the map."
- [`len`](http://doc.rust-lang.org/std/collections/struct.BTreeMap.html#method.len): "Return the number of __elements__ in the map."

When describing the key and value together, I think we should use `key-value pair`, because `element` is vague (do the key and value _each_ count as an element?) and because `entry` is too easily confused with the `Entry` API. However, `entry` should continue to be used to refer to instances of `Entry`.

The sets also vary. In addition to uses of `element` and `value`, `BTreeSet` has ["Gets an iterator over the BTreeSet's __contents__."](http://doc.rust-lang.org/std/collections/struct.BTreeSet.html#method.iter)

Finally, in addition to uses of `element` and `value`, `BinaryHeap` has ["Returns the greatest __item__ in the binary heap, or `None` if it is empty."](http://doc.rust-lang.org/std/collections/struct.BinaryHeap.html#method.peek)

I think we should use `element` or `item` for all sets, lists, and queues, because `value` is already part of map terminology.

This will likely become easier to maintain once we get generic collection traits.

**Comment by steveklabnik** [comment]
👍

**Comment by Gankro** [comment]
> This will likely become easier to maintain once we get generic collection traits.

HA HA

HA

:cry: 

key-value pair is quite verbose. Entry makes the most sense to me in-and-of-itself, though it's a *bit* unfortunate it's overloaded by the Entry API. Especially since some people want to eventually have legit entry-iterators.

Elements is quite nice in that it works for *everything forever*. Maps, Sets, Lists, whatever. They hold elements. Done.

This shed has too many colour options for me, I'm afraid.

**Comment by steveklabnik** [comment]
> This shed has too many colour options for me, I'm afraid.

Yeah, this is my issue too, I think.

@apasel422 are you willing to maybe work up a PR and try to see how this looks with whatever way you think is best? I think saying the same thing would be useful, but I don't have strong feelings about which one we pick.

**Comment by apasel422** [comment]
@steveklabnik Sure. I agree that being consistent is more important than settling on any of the individual choices. Let me try to whip up a PR.

**Comment by steveklabnik** [comment]
@apasel422 ping! Did you give this a shot yet?

**Comment by apasel422** [comment]
No, not yet. I probably won't get around to it for a few days, so feel free
to tackle it yourself if you want.

**Comment by steveklabnik** [comment]
Exactly what I was wondering. I might, I might not, well see, thanks :)

**Comment by steveklabnik** [comment]
Since we don't have something that's clearly better, and neither of us have the time, I'm going to give this a close. If someone wants to write a patch with a particular set of colors, please weigh in here.

**Comment by tshepang** [comment]
A guideline on what to call these things would be great though. Maybe something similar Style Guidelines document, but for documenting Rust code.
