### ISSUE TITLE
debuginfo: Enable LLVM's debuginfo verifier for debuginfo auto-tests

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#23472]
LLVM supports a nifty debuginfo verification pass that checks whether the debuginfo in the IR is well-formed. This can easily be enabled via `-Cllvm-args=-verify-debug-info`.

Unfortunately, at the moment we do one thing that LLVM considers ill-formed: The debuginfo verifier expects all struct-based types (and their members) to be linked to a source file (i.e. to the file where the type is defined). Rust unfortunately contains some kinds of types where this is not possible, most prominently tuples. Consequently, most Rust code fails the verification pass.

The clean way to handle this, in my opinion, is to mark these kinds of types (tuples, `Box`, slices) with the `DW_AT_artificial` attribute, which is the DWARF way of saying "this thing is compiler generated", and then modify the LLVM debuginfo verifier so it allows artificial objects to not have an associated source location. Unfortunately, for reasons unknown to me, LLDB completely ignores some things that are marked as artificial, which would make using LLDB with Rust impossible.

Two other options I see for dealing with this:

1. Completely remove the source-location-condition from LLVM's debuginfo verifier. However, that's something that is unlikely to ever be merged upstream, which is not good.
2. Add some dummy source location like `<unknown>:0:0` to anything where we don't have a real location. I consider this kind of a hack but since source locations associated with types are rarely used in debuggers, this would go mostly unnoticed I guess. However, it would increase the size of binaries with debuginfo in them (a few bytes for every type and every field).

**Comment by sanxiyn** [comment]
What happened to this? [LLVM 3.7 Release Notes](http://llvm.org/releases/3.7.0/docs/ReleaseNotes.html) says "The debug info verifier has been merged with the main verifier". I confirmed `-verify-debug-info` is a no-op now. Given that Rust builds with LLVM 3.7 by default now, I think this issue is somehow fixed.

**Comment by michaelwoerister** [comment]
Interesting. I'll need to look into this.

**Comment by michaelwoerister** [comment]
Debuginfo verification is enabled by default, otherwise we would not get assertions like #34569.
