### ISSUE TITLE
missing symbols on linux without debugging

### ISSUE THREAD

**Issue by metajack** [rust-lang/rust#23488]
If you try to get call stacks in perf under Linux for rustc compiled binaries, they are missing unless you compile with debugging. Using Instruments.app on Mac has the symbols though, even without debugging.

**Comment by pcwalton** [comment]
Apparently this works for rustc.

This is a serious problem for Servo.

**Comment by michaelwoerister** [comment]
Can you describe in more detail what exactly you are doing and what the desired outcome should be?

**Comment by metajack** [comment]
The easiest way to reproduce this is to run some Rust release-compiled program under `perf record -g` and then hit `E` key in `perf report` to show call stacks. In debug compiled builds, the call stack symbols are present. In release builds they are meaningless addresses.

**Comment by michaelwoerister** [comment]
You could try building with `-C debuginfo=1`. That should give you enough debuginfo for call stacks but not interfere too much with optimization.

**Comment by steveklabnik** [comment]
Triage: it's been a long time. @metajack you said this was a serious problem for servo, is it still happening, or did you do @michaelwoerister 's workaround?

**Comment by metajack** [comment]
I think we've just lived with it. @pcwalton does most of his optimization work on macOS. @jdm do you know if this is still happening?

**Comment by jdm** [comment]
This is still necessary on Linux.

**Comment by jdm** [comment]
I don't believe we've ever tried the `-C debuginfo=1` workaround, however.

**Comment by Mark-Simulacrum** [comment]
I'm somewhat confused. Do we somehow include debuginfo in release builds without trying to on macOS? Or does Instruments.app have some form of integrated debuginfo generation?

**Comment by michaelwoerister** [comment]
I've used perf quite a bit lately and have had no problems. However, I don't expect it to work without `-C debuginfo=1`. Does `perf` handle C programs (compiled without debuginfo) better?

**Comment by Mark-Simulacrum** [comment]
Seems to work without -Cdebuginfo=1 today in perf, at least as far as I can tell.
