### ISSUE TITLE
Rustdoc lists functions for each stability level

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#23487]
[ptr Functions section](http://doc.rust-lang.org/std/ptr/index.html#functions)

**Comment by steveklabnik** [comment]
To be clear, the issue here is that they're being duplicated, yes? I think there's also something about these being `use .. as` too.

I think we may have an issue open for this already.

**Comment by dfockler** [comment]
This is the other issue https://github.com/rust-lang/rust/issues/23054

**Comment by alexcrichton** [comment]
When this was still a part of `std::ptr` I think that this was a duplicate of #23054, so closing in favor of that.
