### ISSUE TITLE
Unboxed closures with all Clone members should implement Clone

### ISSUE THREAD

**Issue by seanmonstar** [rust-lang/rust#23501]
Similar to https://github.com/rust-lang/rust/issues/19128

``` rust
#![feature(core, unboxed_closures)]
use std::ops::Fn;

#[derive(Clone)]
struct NotCopy;

#[derive(Clone)]
struct Derp {
    foo: NotCopy
}

impl Fn<()> for Derp {
    type Output = ();
    extern "rust-call" fn call(&self, _: ()) {
    }
}

fn with_clone<F>(_f: F) where F: Fn() + Clone {

}

fn main() {
    let foo = NotCopy;
    with_clone(Derp { foo: NotCopy }); // works
    with_clone(move || { // errors
        let _ = foo; // <- should be like Derp, accessing self.foo
    });
}
```

**Comment by bluss** [comment]
This is important for iterators -- with this we can clone most iterator pipelines. In fact, most don't even need captures at all and would be the cheapest to clone.

**Comment by withoutboats** [comment]
This would be good for situations in which one wants to box and store a closure in a small minority of cases. Would be good to be able to have something like `Cow<'a, Fn(...)>`.

**Comment by arielb1** [comment]
Sounds like an nice idea. Unfortunately it would require `Clone` to be a lang-item, but it is already half a lang-item as a supertrait to `Copy`.

**Comment by seanmonstar** [comment]
The expanded closure struct couldn't have the equivalent of 'derive(Clone)'
added to it?

**Comment by arielb1** [comment]
@seanmonstar 

`derive(Clone)` runs before upvars are known.

**Comment by oli-obk** [comment]
I think this can be closed now that we have https://github.com/rust-lang/rust/issues/44490
