### ISSUE TITLE
Rustdoc search does not find inherent methods on primitive types

### ISSUE THREAD

**Issue by theemathas** [rust-lang/rust#23511]
Searching on rustdoc for a inherent method on a primitive type (e.g. [width](http://doc.rust-lang.org/nightly/std/?search=width)) does not find it, even if it [exists](http://doc.rust-lang.org/nightly/std/primitive.char.html#method.width).

cc https://github.com/rust-lang/rust/pull/23104.

**Comment by tomjakubowski** [comment]
Probably a search index bug. The relevant code is in `rustdoc::html::render`, specifically the `fold_item` method of `impl DocFolder for Cache`, and the `build_index` function.

**Comment by aturon** [comment]
triage: I-nominated ()

Nominating for P-high, 1.0

**Comment by pnkfelix** [comment]
P-high, 1.0.

**Comment by pnkfelix** [comment]
(this is a serious usability issue for clients of the language itself.)

**Comment by nrc** [comment]
cc @cmr in case you want to take this, otherwise I'll keep it on my radar

**Comment by cmr** [comment]
@nrc I don't think I'll actually have any time for Rust in the next few weeks as my semester ends :\

**Comment by nrc** [comment]
Assigning to alex, since he is looking at rustdoc atm
