### ISSUE TITLE
Tweak how hyphens in crate names are allowed

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#23533]
* [x] remove the quote syntax from `extern crate`, require an identifier to be used instead - #23546
* [x] Prevent duplicate uploads of `foo-bar` and `foo_bar` to crates.io [change](https://github.com/rust-lang/crates.io/commit/89bc5dd46435ec08113c82266ad16464d68d4710)
* [x] Automatically translate `-` to `_` in Cargo for passing the `--extern` flag - rust-lang/cargo#1443

As an interim step, the compiler should continue to accept `extern crate "foo-bar" as ...` both in terms of quotes and in terms of matching the identifier `foo_bar` as well. This should help reduce the breakage a little.

triage: P-backcompat-lang (1.0 beta)

**Comment by alexcrichton** [comment]
Er, tracking issue for https://github.com/rust-lang/rfcs/pull/940

**Comment by apasel422** [comment]
rustdoc should also be updated to use the translated name in example code.

**Comment by jnicholls** [comment]
> As an interim step, the compiler should continue to accept extern crate "foo-bar" as ...

Based on the latest rustc, this is not working.  It is still looking for a crate named "libfoo-bar" when it should be looking for "libfoo_bar".  By changing that line to `extern crate foo_bar as ...` it works.

**Comment by alexcrichton** [comment]
Yeah I think I unfortunately botched that part of this :(, sorry about that!
