### ISSUE TITLE
Replace trivial casts with type ascription

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#23542]
There are a bunch of places in the libs and compiler where we use a trivial case where type ascription would be more appropriate. These currently require `#![allow(trivial_casts)]`. Without that we get a warning (and an error when bootstrapping). When type ascription lands these should be converted to use that. E.g., `*self as *const T` should become `*self: *const T`.

**Comment by djmally** [comment]
Do you have some examples of where this occurs in the source? I can take a look at this.

**Comment by nrc** [comment]
Not yet, I haven't landed the patch :-) We haven't landed type ascription either yet, so its not possible to do this yet. Once the two have landed (I'll try to ping this issue when they do), you can grep for `FIXME(#23542)` to find a bunch of specific places. There are also some crates with `#![allow(trivial_casts)]` at the crate root which had more problems than I wanted to deal with individually, you can remove that annotation and the compiler will tell you all the problems.

**Comment by djmally** [comment]
Oh, oops, looks like I didn't read the issue closely enough :). I'll sit tight for now and revisit this when it's ready.

**Comment by robinst** [comment]
(Blocked by #23416 then, I guess.)

**Comment by Manishearth** [comment]
Not easy, type ascription hasn't landed yet :smile:

**Comment by nrc** [comment]
Type ascription has now landed, so it might be possible to start this (although type ascription does not yet cause coercion, so maybe it can't be just yet).

Here are all the uses of trivial_casts in any case: https://dxr.mozilla.org/rust/search?q=trivial_casts&redirect=true&case=true

**Comment by Mark-Simulacrum** [comment]
It feels like based on the following we don't really use trivial casts in the compiler based on the lint allows, though there are a few instances of trivial numeric casts. I've provided a list below of what I could find as of now with a simple grep. I'm uncertain as to whether it's possible to use type ascription already, but I feel like the answer is possibly no.

```
$ rg -trust trivial_
src/libcore/iter/range.rs
65:            #[allow(trivial_numeric_casts)]
125:            #[allow(trivial_numeric_casts)]

src/librustc_typeck/check/mod.rs
1448:#[allow(trivial_numeric_casts)]

# Tests

src/test/compile-fail/liveness-unused.rs
13:#![allow(dead_code, non_camel_case_types, trivial_numeric_casts)]

src/test/compile-fail/object-safety-by-value-self.rs
15:#![allow(trivial_casts)]

src/test/run-pass/trivial_casts.rs
13:#![allow(trivial_casts, trivial_numeric_casts)]

src/test/compile-fail/trivial_casts.rs
11:// Test the trivial_casts and trivial_numeric_casts lints. For each error we also
14:#![deny(trivial_casts, trivial_numeric_casts)]
```

**Comment by sanmai-NL** [comment]
Type ascription is a nightly-only feature, right?

**Comment by Mark-Simulacrum** [comment]
Yes, it is. The tracking issue is https://github.com/rust-lang/rust/issues/23416.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this as type ascription to me isn't yet ready and won't be for a while; it also doesn't really seem like they kind of cleanup that's super helpful.
