### ISSUE TITLE
E0001 check needs improving

### ISSUE THREAD

**Issue by bombless** [rust-lang/rust#23556]
```rust
enum Foo {}
enum Bar { A }
enum Buz { A, B }
fn foo(x: Foo) {
    match x {
        _ => ()
    }
}
fn bar(x: Bar) {
    match x {
        Bar::A => { /* */ }
        _ => () //~ error: unreachable pattern [E0001]
    }
}
fn buz(x: Buz) {
    match x {
        Buz::A => { /* */ }
        Buz::B => { /* */ }
        _ => ()
    }
}
fn main() {}
```

~~Only `bar()` reports error.~~
~~I suggest `bar()` should pass E0001 check for consistency.~~
**EDIT:** only `bar` reports error here, the error from `buz` is only reported when `bar` is removed.

**Comment by jakub-** [comment]
`foo` is related too https://github.com/rust-lang/rust/issues/12609.

However, both `bar` and `baz` produce the error in the latest nightly for me. What version were you using?

**Comment by bombless** [comment]
@jakub- 
playpen http://is.gd/Aa0ti3
and
```
rustc 1.0.0-dev (31ba21228 2015-03-17) (built 2015-03-21)
binary: rustc
commit-hash: 31ba21228e0e539a665ce14ab3a176e30e57f822
commit-date: 2015-03-17
build-date: 2015-03-21
host: x86_64-pc-windows-gnu
release: 1.0.0-dev
```
It's from yesterday's master branch.

**Comment by bombless** [comment]
@jakub- 
But your suggestion may cause problem. see https://github.com/rust-lang/rfcs/pull/969#issuecomment-78460798
Do we really want to do that?

**Comment by bombless** [comment]
@jakub- 
Oh yes you are right.
My bad.

**Comment by bombless** [comment]
Sorry, my bad, `baz` triger error.
Should we report the error along with `bar`s?

The checking may still need improving, so I'm not closing it now.

**Comment by jakub-** [comment]
@bombless Both the errors for `bar` and `buz` are reported in the combined example. The formatting is a tad unfortunate so it's likely you hadn't noticed the second error at :19. :)

```
<anon>:12:9: 12:10 error: unreachable pattern [E0001]
<anon>:12         _ => ()
                  ^
<anon>:12:9: 12:10 help: pass `--explain E0001` to see a detailed explanation
<anon>:19:9: 19:10 error: unreachable pattern [E0001]
<anon>:19         _ => ()
                  ^
<anon>:19:9: 19:10 help: pass `--explain E0001` to see a detailed explanation
```

The only issue here is the one related to `foo`, for which there is an open bug already - #12609. As such, I'm going to close this. Thanks for your report and investigation!
