### ISSUE TITLE
Rustdoc heading links/ids are duplicated

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#23553]
E.g. every `Examples` heading on http://doc.rust-lang.org/nightly/std/primitive.str.html has the same id (`examples`) and all link to http://doc.rust-lang.org/nightly/std/primitive.str.html#examples . Rustdoc should adjust those internals to ensure the links are unique (e.g. `examples`, `examples-1`, `examples-2`, ...).

**Comment by nagisa** [comment]
Dupe of https://github.com/rust-lang/rust/issues/20700
