### ISSUE TITLE
Allow linking to specific impls in rustdoc

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#23552]
It is useful if one is explaining where a method/functionality comes from to be able to link the specific `impl ... for X` on the page for `X`. E.g. I'm just now writing something about string slicing, so it would be nice to be able to point to the `impl Index<Range<usize>> for str` part of http://doc.rust-lang.org/nightly/std/primitive.str.html .

**Comment by steveklabnik** [comment]
Triage: no change here

**Comment by mcarton** [comment]
:+1: This would be quite useful, I just wanted to point out to a friend why `String + &str` is possible, but there is no way to point to this particular implementation. This is especially annoying since this implementation is rather well documented.

**Comment by QuietMisdreavus** [comment]
This should be a fairly small change, so i'm opening it up to new contributors. in `src/librustdoc/html/render.rs`, there's a function called [`render_impl`] that has some code at the top that prints the impl line. The change to fix this would be to add a spot in between where it prints `i.inner_impl()` and the next print to add an anchor link that points to the `h3` right there. There's a function available called `derive_id` that you can hand a potential `id` to that will make sure you get a unique anchor for your link. Actually inserting the anchor can be done like in https://github.com/rust-lang/rust/pull/43747 so you get a nice section marker that pops up on hover.

[`render_impl`]: https://github.com/rust-lang/rust/blob/1b08e0f231cd30719c25a5992f1d9bb27ea02b61/src/librustdoc/html/render.rs#L2925

If you'd like to work on this and want help, let me know! I'm "misdreavus" on IRC. I'd love to get you acclimated to working on rustdoc.

**Comment by QuietMisdreavus** [comment]
Since https://github.com/rust-lang/rust/pull/43979 got merged, i'll close out this issue.
