### ISSUE TITLE
`BinaryHeap::drain` doesn't document its iteration order

### ISSUE THREAD

**Issue by apasel422** [rust-lang/rust#23564]
This type's other iterator-returning methods indicate that the iterator is arbitrarily ordered, but [`drain`](http://doc.rust-lang.org/std/collections/struct.BinaryHeap.html#method.drain) doesn't say either way:

> Clears the binary heap, returning an iterator over the removed elements.

**Comment by Gankro** [comment]
For reference to anyone who wants to fix this, It's the exact same order as all the others.
