### ISSUE TITLE
Rust version of `__attribute(used)__` (GCC) or `llvm.used` (LLVM).

### ISSUE THREAD

**Issue by dpc** [rust-lang/rust#23577]
There come times when rust symbols are referenced only by external assembler. It seems rustc is eager to remove them (especially with `-C lto`, even making them public does not help).

In clang and gcc there are ways to prevent it, correspondingly: `__attribute__((used))` and ` `llvm.used`

If there's a way to get the same behavior in Rust? If not, can be added?

**Comment by steveklabnik** [comment]
We do not currently.

>  If not, can be added?

It might be able to, but significant additions to Rust go through our RFC process, which is in another repository: https://github.com/rust-lang/rfcs/

If you'd like to pursue adding this feature to Rust, please open an issue up over there. Thanks!
