### ISSUE TITLE
IteratorExt::rev should be bounded by DoubleEndedIterator

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust#23587]
```rust
fn main() {
    (0..10).step_by(2).rev().next();
}
```
produces the following error:
```
error: type `core::iter::Rev<core::iter::StepBy<_, core::ops::Range<_>>>` does not implement any method in scope named `next`
```

According to @eddyb, `IteratorExt::rev` should be bounded by `DoubleEndedIterator` to prevent this.

EDIT: Updated the example to show the correct error.

**Comment by eddyb** [comment]
That's not the problematic error, this is:
```rust
error: type `core::iter::Rev<core::iter::StepBy<_, core::ops::Range<_>>>` does not implement any method in scope named `next`
(0..10).step_by(2).rev().next();
                         ^~~~~~
```

**Comment by steveklabnik** [comment]
This is basically the same as https://github.com/rust-lang/rust/issues/23588

**Comment by crumblingstatue** [comment]
> This is basically the same as #23588

They are two different issues.  Bounding IteratorExt::rev by DoubleEndedIterator won't make using rev() on the result of step_by() possible.

**Comment by steveklabnik** [comment]
Yeah, just noting the link :)
