### ISSUE TITLE
Clarify heap::allocate documentation.

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#23603]

**Comment by steveklabnik** [comment]
What needs clarification?

**Comment by nikomatsakis** [comment]
Given that `heap::allocate` is unstable, and that its semantics are likely to change as we do more work on allocators etc in the future, my feeling is that it is probably not a good investment of time to spend a lot of time documenting every particular. Is there something specific you thought should be included @mahkoh ?

**Comment by mahkoh** [comment]
>The alignment must be no larger than the largest supported page size on the platform.

 Linux supports at least 4k and 8k pages and x86_64 supports at least 4k and 2M pages. But Linux on x86_64 will be using 4k pages. It's not clear which limit this refers to.

**Comment by steveklabnik** [comment]
Yes, we will clarify these semantics as part of stabilization, and will document what we decide at that time.
