### ISSUE TITLE
private type in public interface rules do not prevent exposure of some types

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#23621]
e.g.,

```
mod B {
    pub use self::A::foo;

    mod A {
        pub struct X;
        pub fn foo(_: X) {}
    }
}
```

From outside `B`, `foo` is visible, but `X` is not.

The fix is discussed [here](https://github.com/rust-lang/rust/issues/22261#issuecomment-78204761) and in the following comments.

I guess this is technically a backwards incompatible change, but I would regard any example of it as a bug, so I would not feel bad fixing this post 1.0 (also the fix is really easy if we do break your code - just add `pub`). Still, nominating triage: I-nominated

(example by @tomaka from #23585)

**Comment by nikomatsakis** [comment]
The RFC did not try to prevent this case

**Comment by nrc** [comment]
As discussed in the RFC, we try to prevent private items in public signatures, not types which are not visible, it was decided that the latter was too difficult. So, this is not a bug. Closing.
