### ISSUE TITLE
Allow *local* mutation and assignments in pattern guards

### ISSUE THREAD

**Issue by Stebalien** [rust-lang/rust#23627]
Due to #15989, it isn't possible to assign/mutate in pattern guards. However, assignment/mutation of variables local to the pattern guard should be perfectly safe.

As reported on reddit: https://pay.reddit.com/r/rust/comments/2ztiag/cannot_mutably_borrow_in_a_pattern_guard/ by qthree:

> This code is failing: http://is.gd/cAYb5r But that's ok: http://is.gd/7pF28q

**Comment by steveklabnik** [comment]
As this would be a language change / addition, it should be in the RFC repo instead. Please make an issue at https://github.com/rust-lang/rfcs/issues/new , thanks :)

(If you don't want to for some reason, I can, but if you make it, then you'll get notification with updates)

**Comment by Stebalien** [comment]
Done (https://github.com/rust-lang/rfcs/issues/1006). I'd write an actual RFC but I realized that I have no idea how to best implement this (other than wrap pattern guards in an Fn closure and ask on LLVM to inline it...).

**Comment by steveklabnik** [comment]
super fair :)
