### ISSUE TITLE
OpenOptions::append() does not automatically select a write flag on osx.

### ISSUE THREAD

**Issue by shadowmint** [rust-lang/rust#23626]
This:

    OpenOptions::new().append(true).open(&target).ok().unwrap().write_all(...)

Errors with `Error { repr: Os(9) }` on osx, which is:

    [EBADF]            fildes is not a valid file descriptor open for writing.

This is because it is not valid to attempt to write to a file descriptor without passing one of O_RDONLY, O_WRONLY, O_RDWR.

This works:

    OpenOptions::new().write(true).append(true).open(&target).ok().unwrap().write_all(...)

This is a bug.

Append is a write operation; regardless of how the low level system is implemented, using append() or truncate() should implicitly call write() on the OpenOptions.

**Comment by GuillaumeGomez** [comment]
If no one is working on this, I take it.

**Comment by alexcrichton** [comment]
While this should be easy enough to fix, it's not 100% clear to me that it's *wrong* that `append` doesn't imply `write`. I think that this wants to be investigated a bit before making a PR to fix.

**Comment by GuillaumeGomez** [comment]
@alexcrichton: I can create a PR and we debate around it. Or do you prefer doing it here ? For me too, append does mean I wanna write from the end. Reading from the end of a file wouldn't make sense.

**Comment by alexcrichton** [comment]
Design should not happen on PRs, but rather in issues or RFCs, so I would prefer that a PR does not appear to debate the sisue on.

**Comment by GuillaumeGomez** [comment]
Ok ! But why do you think append doesn't mean write ? Do you have a case in mind where someone would want to use `append` without writing ?

**Comment by alexcrichton** [comment]
The OS API provides these two axes, and it's not clear to me that we should make it impossible to pass `O_APPEND` and `O_RDONLY`. Are we ready commit to say there are 0 use cases of this combination of flags?

**Comment by GuillaumeGomez** [comment]
Hum... I see your point... I really need to see an example of that. The possibility of its existence makes me curious. In which case someone would want to use `append` to only read ?

**Comment by alexcrichton** [comment]
I cannot personally think of a case in which it is useful, but that does not mean that one does not exist.

**Comment by GuillaumeGomez** [comment]
That's not what I meant. I can't figure a case where it could be useful neither and I'm just very curious about such a thing. Can't wait to see if someone has an example !

**Comment by shadowmint** [comment]
I've opened a SO question about this; http://stackoverflow.com/questions/29223077/is-there-any-valid-situation-where-you-would-use-o-append-and-o-rdonly

My concern here is that we're pandering to the low level implementation for no reason.

For what it's worth the low level windows implementation also defines:

```
#define GENERIC_READ 0x80000000
#define GENERIC_WRITE 0x40000000
#define GENERIC_EXECUTE 0x20000000
#define GENERIC_ALL 0x10000000
#define FILE_READ_DATA 1
#define FILE_LIST_DIRECTORY 1
#define FILE_WRITE_DATA 2
#define FILE_ADD_FILE 2
#define FILE_APPEND_DATA 4 
```

ie. They are also distinct between the append / write flags and the read / write flags.

However, as a high level OS abstraction, I maintain I can see no tangible reason to mirror these low level details. 

If you want this somehow as an RFC or a comment on the I/O RFC instead of here as a bug, I'm happy to move it, but I strongly feel this creates a poor high level rust api().

The mysterious 'error 9' when you attempt a basic operation (write to file) is terrible.

**Comment by GuillaumeGomez** [comment]
Just for the record. Yesterday, I pointed [this argument](https://botbot.me/mozilla/rust-internals/2015-03-23/?msg=34858636&page=6) on the IRC.

**Comment by steveklabnik** [comment]
This issue was brought up pre-1.0,and it's now long past 1.0. Is this the kind of change we could even make, given stability guarantees?

**Comment by alexcrichton** [comment]
This was largely settled in [RFC 1252](https://github.com/rust-lang/rfcs/blob/master/text/1252-open-options.md), so I'm going to close this.
