### ISSUE TITLE
Unable to create a range to max value, e.g. `100..256` for a `Range<u8>`

### ISSUE THREAD

**Issue by samdoshi** [rust-lang/rust#23635]
How is one supposed to create a range which includes the maximum value as it's upper bound?

E.g. if I wish to create the range 100 to 255 inclusive for a `u8`, I need use the notation `100..256`:
```rust
fn main() {
    let r: std::ops::Range<u8> = 100..256;
    println!("{:?}", r);
}
```
The output of which is:
```
100..0
```

(we do get a warning when we compile though)
```
test.rs:2:39: 2:42 warning: literal out of range for u8, #[warn(overflowing_literals)] on by default
test.rs:2     let r: std::ops::Range<u8> = 100..256;
                                                ^~~
```

I understand why this is happening based on the implementation of Range, and I'm not sure how one would fix it without changing Range to use an inclusive upper bound (even if the notation stays as is). Maybe a better warning might be of use if I can't be solved?

**Comment by GuillaumeGomez** [comment]
Even worse:

```Rust
let r: std::ops::Range<u8> = 100..(255 + 1);
```

We don't have a warning here whereas it displays:

```Shell
100..0
```

But it displays a warning in this case:

```Rust
let r: std::ops::Range<u8> = 100..(257 - 1);
```

Kinda tricky somehow haha.

**Comment by klutzy** [comment]
`range_inclusive` exists for the case, but it has been deprecated recently.
cc @alexcrichton @aturon

**Comment by aturon** [comment]
Note: `range_inclusive` isn't deprecated, just unstable.

**Comment by steveklabnik** [comment]
This issue has been superceded by https://github.com/rust-lang/rust/issues/28237, once that feature is stable, this will be possible.
