### ISSUE TITLE
UNUSED_IMPORTS symbol from rustc_lint::lint::builtin can't be found by dyld on OSX 10.10

### ISSUE THREAD

**Issue by caryhaynie** [rust-lang/rust#23643]
Trying to execute rustc after running rustup (03/23/2015) results in an abort with the following error from OSX's dynamic loader:
```
dyld: Symbol not found: __ZN4lint7builtin14UNUSED_IMPORTS20h071e37291baef8b1dIoE
  Referenced from: /usr/local/lib/librustc_lint-4e7c5e5c.dylib
  Expected in: x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/librustc-4e7c5e5c.dylib
 in /usr/local/lib/librustc_lint-4e7c5e5c.dylib
```

**Comment by hugoduncan** [comment]
I'm getting this on OSX 10.9 as well.

**Comment by richo** [comment]
Oops, this might have been me.

**Comment by caryhaynie** [comment]
It looks like https://github.com/rust-lang/rust/commit/532cd5f85a93921f74f5991db2e419c6da58b188 might be the cause, as it looks like prior to this commit, the symbol was marked public, and thus exported.

**Comment by steveklabnik** [comment]
Is this still a problem today?

**Comment by bltavares** [comment]
Triaging: is this still happening?

**Comment by caryhaynie** [comment]
I've not seen this in many months using the last couple stable releases (via multirust), so closing.
