### ISSUE TITLE
File metadata panics on data modified in far future

### ISSUE THREAD

**Issue by marcusklaas** [rust-lang/rust#23666]
Rustc version: `rustc 1.0.0-nightly (809a554fc 2015-03-23) (built 2015-03-24)`

To reproduce, run

`$ touch -d "+2000000000 years" test`

and then execute the following rust program:

    fn main() {
        PathBuf::new("test")
                .metadata()
                .unwrap()
                .modified();
    }

This produces the following panic: `thread '<main>' panicked at 'arithmetic operation overflowed', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/fs2.rs:80`

**Comment by marcusklaas** [comment]
Edit: it also fails on pre-epoch files.

    $ touch -d "-50 years" test
    $ cargo run

produces the same result.

**Comment by GuillaumeGomez** [comment]
Nice one. I'm gonna take a look (unless you're already doing it ?).

**Comment by marcusklaas** [comment]
I have only briefly looked into it. It seems no overflow is checked when reading the internal structure. What would be the desired behaviour though? Should we wrap the result in an `Option`?

Considering the result is an unsigned integer, handling dates before 1970 will be difficult. Wouldn't it make more sense to return an `i64` instead?

**Comment by GuillaumeGomez** [comment]
I'm not the better to answer these questions unfortunately. However, we shouldn't have to handle dates before 1970 normally. The only real problem would be about dates in a "far away" future and if we take an `i64` (why not an `u64` by the way ?), this should solve a part of our problem.

**Comment by marcusklaas** [comment]
It currently returns an `u64`. This covers the foreseeable future. That's not the problem. But when you read the filesystem, you can't expect all modified timestamps to be reasonable.

**Comment by GuillaumeGomez** [comment]
For what I found around (at least on Windows API), it seems they handle it with a `i64`.

**Comment by marcusklaas** [comment]
Internally? Because the return value seems to be `u64`: https://github.com/rust-lang/rust/blob/master/src/libstd/sys/windows/fs2.rs#L285

**Comment by GuillaumeGomez** [comment]
My mistake, under Windows it isn't an `i64` but two `u32` ([link](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724284%28v=vs.85%29.aspx), [example](https://msdn.microsoft.com/en-us/library/ms724926(v=vs.85).aspx)). However, under linux this is supposed to be a signed integer ([link of lstat](http://linux.die.net/man/2/lstat), [type of time_t](http://stackoverflow.com/a/471287)). So on Windows side, it is unsigned integers, on linux side this is a signed integer. Quite a choice, right ? ^^

**Comment by marcusklaas** [comment]
I guess this eliminates the `i64` return option, since windows does not even has a way of representing dates before epoch. That's reasonable for modification dates, I suppose. 

About the overflow: windows is not susceptible to integer overflow in this case, since we divide to get to milliseconds.

On unix systems, multiplication is performed to go from seconds to milliseconds: https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/fs2.rs#L80. That's where the overflow happens.

**Comment by GuillaumeGomez** [comment]
Then that's where I'll patch it.

**Comment by marcusklaas** [comment]
How, though?

**Comment by GuillaumeGomez** [comment]
By doing something like this:

```Rust
fn mktime(&self, secs: u64, nsecs: u64) -> Error<u64> {
    let d_nsecs = nsecs / 1000000;

    if (secs + d_nsecs) < u64::max / 1000 {
         Ok(secs * 1000 + d_nsecs)
    } else {
        Err(some_error_code)
    }
}
```

But maybe you see another way ?

**Comment by marcusklaas** [comment]
That's a solution, yes. But we'll have to propagate this error and that'll be a breaking change, right?

**Comment by GuillaumeGomez** [comment]
Yep...

**Comment by marcusklaas** [comment]
Alright, sounds good to me. I'd just use an `Option` since there isn't really an `io::ErrorKind` variant that fits for this kind of error..

**Comment by GuillaumeGomez** [comment]
We're speaking about it we @alexcrichton on the IRC. He's not in favor of an `Option`.

**Comment by marcusklaas** [comment]
Alright, just a suggestion :-) Thanks for picking this up Guillaume! :+1:

**Comment by GuillaumeGomez** [comment]
No problem ! Thanks to you for reporting this issue ! ;)

**Comment by GuillaumeGomez** [comment]
I confirm what I said earlier: this will be fixed "automatically" when a proper timestamp type will be created.

**Comment by alexcrichton** [comment]
Yes I think the best solution here is to hold out waiting for a full-fledged timestamp-like functionality. Returning a `u64` is one of the primary reasons this function is not yet stable, and partly because of issues like this!

**Comment by marcusklaas** [comment]
I believed this has been resolved now. The new metadata functionality is pretty sweet!
