### ISSUE TITLE
Smart asserts

### ISSUE THREAD

**Issue by jesse99** [rust-lang/rust#2367]
It would be great if when asserts failed they printed something more useful than the offending line. Currently they print something like:

```
Assertion 'x < y + bar() failed', src/foo.rs:561
```

It'd be way nicer if they printed the values of variables that they use and the results of the functions they call:

```
Assertion 'x{10} < y{2} + bar(){4} failed', src/foo.rs:561
```

**Comment by frewsxcv** [comment]
Triage bump. No change.

```
/tmp $ cat hi.rs
fn main() {
    let x = 4;
    let y = 10;
    let z = 20;

    assert!(x + y > z);
}

/tmp $ rustc hi.rs; and ./hi
thread '<main>' panicked at 'assertion failed: x + y > z', hi.rs:6

/tmp $ rustc -vV
rustc 1.0.0-nightly (2b01a37ec 2015-02-21) (built 2015-02-21)
binary: rustc
commit-hash: 2b01a37ec38db9301239f0c0abcf3c695055b0ff
commit-date: 2015-02-21
build-date: 2015-02-21
host: x86_64-apple-darwin
release: 1.0.0-nightly
```

**Comment by lifthrasiir** [comment]
We now have two independent implementations: gifnksm/power-assert-rs and manuel-woelker/rust-passert. Both unconditionally stringifies subexpressions before the conditional however, so it cannot easily replace Rust's own `assert*!` macros.

**Comment by chris-morgan** [comment]
A true replacement will work for all types, using `fmt::Debug` for appropriate types and omitting it for other types. This is something that needs something along the lines of default implementations. This is something that we may well be getting in the not-so-distant future, but until we do I don’t think progress is possible on this.

**Comment by tbu-** [comment]
Do we actually want this? It'll probably lead to huge code bloat.

**Comment by Manishearth** [comment]
This can accidentally leak sensitive information, too.

Rather, we should ensure all stdlib asserts are helpful, like in https://github.com/rust-lang/rust/pull/29984

**Comment by Ticki** [comment]
What about only adding them in debug mode?

**Comment by steveklabnik** [comment]
Triage; no change.

**Comment by aturon** [comment]
Closing in favor of out of tree solutions for now. A change to incorporate one of those into `std` probably merits an RFC at this point.
