### ISSUE TITLE
#[thread_local] causes a runtime error on Windows.

### ISSUE THREAD

**Issue by dradtke** [rust-lang/rust#23672]
Here's my test program:

```rust
#![feature(thread_local)]

#[thread_local]
static mut set_me: bool = false;

fn main() {
    unsafe { set_me = true; }
}
```

This program compiles just fine, but when run causes a dialog box to appear informing you that the application has stopped working.

My Rust version:

```
rustc 1.0.0-nightly (809a554fc 2015-03-23) (built 2015-03-24)
binary: rustc
commit-hash: 809a554fca2d0ebc2ba50077016fe282a4064752
commit-date: 2015-03-23
build-date: 2015-03-24
host: i686-pc-windows-gnu
release: 1.0.0-nightly
```

**Comment by alexcrichton** [comment]
This is unfortunately a known problem with windows and why we don't use the `#[thread_local]` attribute for thread local items. This is also one of the reasons the feature is unstable! For now you can get thread local variables via the `thread_local!` macro.
