### ISSUE TITLE
Can't use #[plugin] inside of a #[cfg] block if #[feature(plugin)] is not unconditionally enabled

### ISSUE THREAD

**Issue by reem** [rust-lang/rust#23683]
It is quite useful for stability to require a plugin for testing, e.g. stainless, but to not require the plugin feature in the main build. Right now, this doesn't work.

Repro:

``` rust
#![cfg_attr(test, feature(plugin))]

#[cfg(test)]
mod test {
    #[plugin(some_plugin)]

    ...
}
```

should compile fine in both test and non-test builds, but in fact compiles in neither.

**Comment by reem** [comment]
I now realize #[plugin] on a crate is deprecated.

**Comment by reem** [comment]
Actually this still applies to the current use of plugin.

**Comment by sfackler** [comment]
`#[plugin(..)]` only works at the crate root.

**Comment by steveklabnik** [comment]
As @sfackler says, this attribute only works at the crate root. We give a warning about it today.

As such, I'm gonna give this one a close. Thanks @reem !
