### ISSUE TITLE
TcpStream::duplicate is not implemented.

### ISSUE THREAD

**Issue by Ms2ger** [rust-lang/rust#23696]
Servo uses `old_io::TcpStream::clone`; [the RFC](https://github.com/rust-lang/rfcs/blob/master/text/0517-io-os-reform.md#tcp) claims it will be replaced by `TcpStream::duplicate`, which doesn't exist.

**Comment by GuillaumeGomez** [comment]
This [one](https://github.com/rust-lang/rust/blob/a2572885ab62512a2508868a27c22d615382174a/src/libstd/sys/common/net2.rs#L220) ?

**Comment by Ms2ger** [comment]
No, the one that somehow ended up being called `try_clone`. *sigh*

**Comment by alexcrichton** [comment]
Fixed by https://github.com/rust-lang/rfcs/pull/1013
