### ISSUE TITLE
standard library documentation links to nonexistant library

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#23705]
The home page has a `thread_local` module, linking to http://doc.rust-lang.org/nightly/std/thread_local/, which is a 404.

**Comment by steveklabnik** [comment]
tagging with 'docs' until I figure out if this is a doc issue or a rustdoc bug.

**Comment by tomjakubowski** [comment]
Well, the module exists, is documented, and no `#[doc(hidden)]` anywhere... I think this is a peculiar rustdoc bug.

Curiously, the declaration of the module is the only top-level `pub mod` declaration in `std` that has `#[macro_use]` attached. Could be related.

**Comment by daboross** [comment]
@tomjakubowski could you point me to the module? I don't seem to be seeing it in the tree at first glance. I mean thread_local! exists, but I don't see a public thread_local module in std.

**Comment by tomjakubowski** [comment]
@daboross the module was moved around recently, it's the (hidden, but public) `std::thread::__local` module at `src/libstd/thread/local.rs` now.

The new module *is* `[doc(hidden)]` now so rustdoc isn't generating links to it. There was an underlying rustdoc issue here, but evidence of it is now gone, like tears in rain. (unless you check out a tree from ~9ish days ago)
