### ISSUE TITLE
Missing size_hint overrides in some Iterators implementations

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#23708]
Some implementations of `Iterator` don’t override the `size_hint` method (and keep the conservative `(0, None)` default), but should. This includes at least:

``` rust
impl<A: Int> Iterator for StepBy<A, ::ops::Range<A>>
impl<A: Int> Iterator for ::ops::RangeFrom<A>
impl<A: Int> Iterator for RangeStepInclusive<A>
```

CC @alexcrichton

**Comment by alexcrichton** [comment]
cc @aturon, this may some day tie into `std::num` stabilization and how `Int` is going away.

**Comment by SimonSapin** [comment]
Yes, these implementations (and other) will need to change if `Int` is going away, but isn’t that orthogonal to `size_hint`?

**Comment by alexcrichton** [comment]
The bounds may change somewhat if we expect to be able to define `size_hint`, but it is largely orthogonal, yes.

**Comment by Mark-Simulacrum** [comment]
I've made a list of the things which I believe need a size_hint override:

 - [ ] [`impl<I: Iterator<Item = u8>> Iterator for DecodeUtf8<I>`](https://github.com/rust-lang/rust/blob/ebbc9ea914a1cefa48afb9cc6c9f7a14ff7c6857/src/libcore/char.rs#L767)
 - [ ] [`impl<T, Iter: Iterator<Item=Option<T>>> Iterator for Adapter<Iter>`](https://github.com/rust-lang/rust/blob/ebbc9ea914a1cefa48afb9cc6c9f7a14ff7c6857/src/libcore/option.rs#L1084)
 - [ ] [`impl<I, T, E> Iterator for ResultShunt<I, E>`](https://github.com/rust-lang/rust/blob/ebbc9ea914a1cefa48afb9cc6c9f7a14ff7c6857/src/libcore/iter/traits.rs#L780)
 - [ ] [``]()

**Comment by Phlosioneer** [comment]
`CycleIter` is used just for testing, so it's irrelevant.
There is no sensible implementation of `size_hint` for `$forward_iterator` and `$reverse_iterator`, as far as I can tell.
The rest are addressed in my PR.

I've compiled a more complete list of iterators without size_hints, and will make a new tracking issue for them.

**Comment by Phlosioneer** [comment]
New tracking issue for expanded list: #49205

**Comment by SimonSapin** [comment]
Closing for #49205.
