### ISSUE TITLE
newly stabilized std::net::lookup_host not very ergonomic to use

### ISSUE THREAD

**Issue by nwin** [rust-lang/rust#23700]
The new lookup_host method now returns  `SocketAddr`s instead of an `IpAddr`s. Unfortunately the returned  `SocketAddr` is not very useful because it defaults to port 0. Since  `SocketAddr` does not have any setters for the port I basically have to re-create every single returned value to make use of it.

`lookup_host`  should either take a port as an argument or only return IP addresses. I would prefer the latter.

**Comment by alexcrichton** [comment]
I agree that stabilizing it may have been a little hasty. I've proposed destabilizing it as part of #23711

**Comment by steveklabnik** [comment]
Since it was destabilized, I'm going to give this a close.
