### ISSUE TITLE
Static standalone library with liballoc and libcollections is missing some internal symbols

### ISSUE THREAD

**Issue by rudib** [rust-lang/rust#23717]
I'm trying to build a bare-metal embedded Rust for STM32 (ARM thumbv7m-none-eabi) library with liballoc (using feature=external_funcs) and libcollections. My simple Rust function that returns a new Vec<SomeStruct> compiles, but the final linking into the main C firmware fails.

Rust method:

```
#[no_mangle]
pub extern fn generate_some_colors(n: u32) -> Vec<Rgb> {
	let mut v = Vec::new();
	for i in 0..n {
		let c = Rgb { red: 100, green: 100, blue: 200 };
		v.push(c);
	}
	
	v
}
```

Final linking:

```
arm-none-eabi-g++ -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-move-loop-invariants -Wall -Wextra  -g3 -gdwarf-2 -T mem.ld -T libs.ld -T sections.ld -nostartfiles -Xlinker --gc-sections -L"../ldscripts" -Wl,-Map,"test1.map" --specs=nano.specs -o "test1.elf"  [...lots of STM32 libs...] ./src/main.o  C:/code/eclipse-c/test1/src-rust/rust_lib.o 
C:/code/eclipse-c/test1/src-rust/rust_lib.o: In function `generate_some_colors':
lib.0.rs:(.text.generate_some_colors+0x74): undefined reference to `vec::Vec$LT$T$GT$::push::_MSG_FILE_LINE::h359077450bf5c9eefUh'
lib.0.rs:(.text.generate_some_colors+0x78): undefined reference to `vec::Vec$LT$T$GT$::push::_MSG_FILE_LINE::h359077450bf5c9eefUh'
lib.0.rs:(.text.generate_some_colors+0x7c): undefined reference to `panicking::panic::h95d4876b84c57052LVA'
lib.0.rs:(.text.generate_some_colors+0x80): undefined reference to `oom::h3d1c751e5ef857206Ua'
```

I'm building on Windows using Rust 1.0 nightly b0aad7dd4 2015-03-22. I'm suspecting that this a bug somewhere in Rust's linker? Is it possible to include whole rlibs and let the final linking discard unneeded symbols?

**Comment by alexcrichton** [comment]
How did you compile the rust code? It looks like you passed `--emit=obj`, but that isn't pulling in upstream dependencies, so you may want to consider using `--crate-type staticlib` isntead.

**Comment by rudib** [comment]
Alex, that's right. I have ```#![crate_type="staticlib"]``` in the lib.rs, but it looks like that doesn't get taken into account. Passing it explicitly to the compiler does invoke a different compilation mode and it currently complains with ```could not find native static library `compiler-rt````, so obviously I have to compile an ARM version of that as well. Will look into it, many thanks!

**Comment by alexcrichton** [comment]
Perhaps the crate type was overridden from the command line? It's also only actually emitted if `--emit=link` (the default) is present.

If you're using the custom target specification I believe you can turn off auto-linking to `compiler-rt` as well.

**Comment by rudib** [comment]
I've added the option for it to my target spec, but it doesn't make a difference, same error message. Here's the JSON target spec:

```
{
    "arch": "arm",
    "cpu": "cortex-m3",
    "data-layout": "e-m:e-p:32:32-i1:8:32-i8:8:32-i16:16:32-i64:64-v128:64:128-a:0:32-n32-S64",
    "disable-redzone": true,
    "executables": true,
    "llvm-target": "thumbv7m-none-eabi",
    "morestack": false,
    "os": "none",
    "relocation-model": "static",
    "target-endian": "little",
    "target-pointer-width": "32",
    "no_compiler_rt" : true
} 
```

**Comment by alexcrichton** [comment]
Hm that's odd... Not entirely sure what's going on there!

**Comment by rudib** [comment]
Not a problem, I'll have some more fun with this over the weekend. Will report. Thanks for the help!

**Comment by rudib** [comment]
Some of my findings, for reference if anyone will find this thread:

I couldn't get ```no_compiler_rt``` to work with the staticlib build. I'll try to recompile the compiler with some debugging statements around there, to me it almost looks like a parsing error as the code is quite trivial around the linker's invocation.

Luckily, Rust's .rlib files are plain old libraries, so any linker will happily link them into the final executable. So, if you cross compile Rust's libcore, liballoc (with external functions feature), libunicode and libcollections, implement some methods for the memory allocator and other minor things, you can get an ARM bare-hardware Rust library that can be called from C. With working Vec and String! Compiler's runtime seems to be compatible with the one provided by GCC, so far I didn't need to compile a custom ```compiler-rt```.

I'll try to do a writeup on this once 1.0 is released, but having all the cruft of low level STM32 drivers, initializations and whatnot in C and the actual logic code in Rust looks like an incredible timesaver for embedded development.

**Comment by ekiwi** [comment]
@rudib I'm currently trying to accomplish the same thing: compile rust code into a static lib and then link it to C code for a cortex-m4 target.

I was successful in compiling my rust code to an _object file_ and then using `gcc` to link it with my c code. However, when I try to build a _static library_, I get the `could not find native static library compiler-rt` error.

Right now I'm trying to figure out how to deal with this and thus found this issue.

> I couldn't get no_compiler_rt to work with the staticlib build. I'll try to recompile the compiler with some debugging statements around there, to me it almost looks like a parsing error as the code is quite trivial around the linker's invocation.

Do you have any updates on this issue? Did you get `no_compile_rt` to work?


> so far I didn't need to compile a custom compiler-rt.

Why is this? Is there a precompiled version for cortex-m? Or did you just use `gcc` to link the object files generated by `rustc`?

The reason why I would like to use `rustc` to produce a staticlib is that I want to use `cargo` for my rust code.

**Comment by rudib** [comment]
Yeah, I just use gcc to link the Rust library and all of its dependencies (.rlib) into the final executable (firmware image). So, from Rust's side: liballoc, libcollections, libcore and libunicode. Here are the compiler commands to compile these base dependencies:
```
rustc -C opt-level=2 -Z no-landing-pads --target thumbv7m-none-eabi -g src/libcore/lib.rs --out-dir libs-arm
rustc --cfg feature=\"external_funcs\" -C opt-level=2 -Z no-landing-pads --target thumbv7m-none-eabi -g src/liballoc/lib.rs --out-dir libs-arm -L libs-arm
rustc -C opt-level=2 -Z no-landing-pads --target thumbv7m-none-eabi -g src/libunicode/lib.rs --out-dir libs-arm -L libs-arm
rustc -C opt-level=2 -Z no-landing-pads --target thumbv7m-none-eabi -g src/libcollections/lib.rs --out-dir libs-arm -L libs-arm
```

And for my final library:
```
rustc -C opt-level=2 -Z no-landing-pads --target thumbv7m-none-eabi -g --crate-type lib -L libcore-thumbv7m src/lib.rs
```

Pass all of these libraries to your final gcc build and it should find all the required symbols.

I have a slightly outdated rustc version, hopefully this stuff still works. I'm building on Windows (*gasp*) with GNU ARM plugin for Eclipse for the final build. Works perfectly fine on a STM32 F4 Discovery dev board.

I've built a little library for embedded CLI tools, I plan on doing a blog-post-style writeup with a sample project once Rust 1.0 is released. https://github.com/hashmismatch/terminal_cli.rs

**Comment by rudib** [comment]
For 1.1 nightly, I've found out that you need to compile to both .rlib and .o libs and then link .o's for your final build and .rlibs for intermediate Rust builds. Blog writeup: http://www.hashmismatch.net/2015/05/18/pragmatic-bare-metal-rust.html

**Comment by russellmcc** [comment]
I don't need to build .o libraries, and I'm on 1.1 nightly.  Are you sure you built your rlibs with the correct version of `ar`?  Using the system (non-cross) one probably won't work.

**Comment by pierzchalski** [comment]
I'm having similar issues to the original poster, in that I'm missing the same symbols (although I'm trying to fit into another build system, which might be my problem). 

I've also got a missing ```__mulodi4``` symbol in libcore that's apparently provided by compiler-rt. This is despite having ```"no-compiler-rt" = true``` set in my target spec. Yet, I can compile libcore with ```--crate-type="staticlib"```!

**Comment by madstr** [comment]
@rudib 
I am also trying to do with something similar with x86 platform and was able to re-implement most of the crypto library which runs on bare metal i386 target. Now I have been cornered and want to use Box feature, so I ended up pulling up liballoc. But when I tried to link liballoc.rlib during generation of final binary (similar to libcore) it gives errors like 
```
main.0.rs:(.text.__rust_allocate+0x10): undefined reference to `malloc'
main.0.rs:(.text.__rust_allocate+0x30): undefined reference to `posix_memalign'
dtls/build/main.o: In function `__rust_deallocate':
main.0.rs:(.text.__rust_deallocate+0x1): undefined reference to `free'
dtls/build/main.o: In function `__rust_reallocate':
main.0.rs:(.text.__rust_reallocate+0x20): undefined reference to `realloc'
main.0.rs:(.text.__rust_reallocate+0x42): undefined reference to `posix_memalign'
main.0.rs:(.text.__rust_reallocate+0x6c): undefined reference to `free'
dtls/build/main.o: In function `funcs::posix88::fcntl::open::h9ce22954c6c581ea6ab':
main.0.rs:(.text._ZN5funcs7posix885fcntl4open20h9ce22954c6c581ea6abE+0x1): undefined reference to `open'
```
Does liballoc has any dependencies?

**Comment by DemiMarie** [comment]
@madstr liballoc depends on an underlying allocator.
