### ISSUE TITLE
rename std::path::PathBuf::pop

### ISSUE THREAD

**Issue by nwin** [rust-lang/rust#23731]
`std::PathBuf::pop` is the only `pop`-method in the stdlib returning bool instead of `Option<…>`. Since it can’t return `Option<…>` without any unessesary allocation (or maybe it can?) it should be renamed. Maybe to `truncate`?

I know it’s late coming up with this now but not too late, since using new io was discouraged until recently so it was not used widely before stabilizing.

**Comment by Stebalien** [comment]
Additionally, `PathBuf::pop` is not the inverse of `PathBuf::push`.

**Comment by steveklabnik** [comment]
pop has been stabilized, so this is a wart we're just gonna have to live with.

**Comment by rnarkk** [comment]
This.

@steveklabnik Can we deprecate this use of `pop` and begin preparing to reuse it for what we all expect?

```rust
#[cfg(feature = "new-pathbuf-pop")]
pub fn pop(&mut self) -> Option<Self> { .. }

#[cfg(not(feature = "new-pathbuf-pop"))]
#[cfg_attr(
    not(feature = "new-pathbuf-pop"),
    deprecated = "We recommend you to enable "new-pathbuf-pop" feature and try new pop() method, or existing parent() method instead.")]
pub fn pop(&mut self) -> bool { .. }
```

It's ok, as @nwin suggested, to rename it to `truncate`, but I mean who's using this or would prefer over the new pop? 

```rust
#[cfg(feature = "new-pathbuf-pop")]
pub fn truncate(&mut self) -> bool { .. }
```

**Comment by peter-scholtens** [comment]
For my use case it would be handy to get the popped value and inspect it: I try to detect if a revision control tool is used for my application by inspecting the presence of a hidden directory name. However, I would also like to inspect if the user is **not** reading or writing in that hidden revision control directory itself, as this will be dangerous. Imagine a file layout like this:

```
├── my_project/
┆   ├── correct_location/
    ├── .svn/
┆       └── dangerous_location/
```
Now popping a `PathBuf` from `dangerous_location` I could test in the popped value is equal to `.svn` and emit a warning or error. Unfortunately, as mentioned earlier, `Pathbuf::pop` is **not** the inverse of `Pathbuf::push`. 

Some other remarks:

1. I agree that the current behavior of `Pathbuf::pop` is indeed better described as `truncate`. Deprecating the old `pop` and introducing a new `pop_with_value` would be nice for my use case.
2. Possibly returning a [component](https://doc.rust-lang.org/stable/std/path/enum.Component.html) is even better?
