### ISSUE TITLE
404 on collections/primitive.str.html

### ISSUE THREAD

**Issue by gmjosack** [rust-lang/rust#23735]
At the top of http://doc.rust-lang.org/nightly/collections/str/index.html there are two `str` links that point to http://doc.rust-lang.org/nightly/collections/primitive.str.html

Both of these pages have the same header docs, though the same `str` links on the latter page are broken.

**Comment by steveklabnik** [comment]
related: https://github.com/rust-lang/rust/issues/23705

**Comment by gmjosack** [comment]
This issue seems to be specifically caused because of the shared header at different levels in the tree so the relative link will only work for one of them.

**Comment by steveklabnik** [comment]
These were manual links I have since removed for exactly this reason

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/23901/files
