### ISSUE TITLE
rename std::path::PathBuf::pop

### ISSUE THREAD

**Issue by nwin** [rust-lang/rust#23730]
`std::PathBuf::pop` is the only `pop`-method in the stdlib returning bool instead of `Option<…>`. Since it can’t return `Option<…>` without any unessesary allocation it should be renamed. Maybe to `truncate`?

I know it’s late coming up with this now but I hope not too late, since using new io was discouraged until recently so it was not used widely before stabilizing.

**Comment by huonw** [comment]
Accidental double filing with https://github.com/rust-lang/rust/issues/23731?

**Comment by nwin** [comment]
Yes, some weird glitch in github.
