### ISSUE TITLE
std::io::Take should have into_inner() method

### ISSUE THREAD

**Issue by kballard** [rust-lang/rust#23755]
It seems like a reasonably obvious thing to do and would be trivial to implement. The only alternative right now is to always use `.by_ref()` before calling `.take()`, and that's not always viable (e.g. because the `io::Take` needs to be kept around without borrowing the owner of the underlying reader).

An example usage would be implementing a message-based protocol on top of a stream protocol, where the messages either have fixed-length frames or have length indicators, I might want to call `.take()` to be able to work with a single message and then `.into_inner()` when I'm done to recover the underlying reader.

**Comment by huonw** [comment]
triage: I-nominated

A lot of library types have `.into_inner` methods, but I'm not sure we've ever explicitly decided that we should do it for any adaptor type like this (e.g. should the various iterator adaptors get `.into_inner`s?), especially ones like this where `&mut`/`.by_ref` work for some/most(?) cases.

**Comment by alexcrichton** [comment]
triage: P-medium

@sfackler indicated that he was interested in making a PR for this and limiting it to the I/O adaptors for now.

**Comment by frewsxcv** [comment]
@sfackler Are you still working on this? Or can I take this?

**Comment by brson** [comment]
@frewsxcv you got it.

**Comment by frewsxcv** [comment]
Opened a PR: https://github.com/rust-lang/rust/pull/36019.

**Comment by martinhath** [comment]
Shouldn't this be closed?

**Comment by frewsxcv** [comment]
Tracking issues (like this one) stay upon until the feature has stabilized. Right now, `std::io::Take::into_inner` is still unstable.

**Comment by sfackler** [comment]
Looks like the `#[unstable]` tag isn't pointing at it though.

**Comment by frewsxcv** [comment]
Yep, was just about to ping the `#rust-libs` channel to add the label since I can't ;)

**Comment by frewsxcv** [comment]
Misread what you wrote the first time I read your comment. Added the issue number to the `#[unstable]` in https://github.com/rust-lang/rust/pull/36916.

**Comment by alexcrichton** [comment]
@rfcbot fcp merge
