### ISSUE TITLE
Regex documentation on \d possibly misleading

### ISSUE THREAD

**Issue by ucarion** [rust-lang/rust#23792]
Not sure if it's just because I don't know enough about character classes, but when I read:

```
\d          Perl character class ([0-9])
\D          Negated Perl character class ([^0-9])
```

(Source: http://doc.rust-lang.org/regex/regex/index.html#matching-one-character)

I thought this meant that `\d` would *only* match the ASCII characters 0 through 9, but in fact it'll match other Unicode digits too:

```rust
#![feature(plugin)]
#![plugin(regex_macros)]
extern crate regex;

fn main() {
    let re = regex!(r"\d");
    println!("{}", re.is_match("٩")); // prints "true"
}
```

Maybe the wording should be changed?

**Comment by killercup** [comment]
You should probably post this issue to the repository of the regex crate: https://github.com/rust-lang/regex

**Comment by ucarion** [comment]
Oops, I forgot regex had its own repo.
