### ISSUE TITLE
Error: duplicate entry

### ISSUE THREAD

**Issue by Virtlink** [rust-lang/rust#23834]
I'm using `libcore` and `liballoc` to build a freestanding kernel, and it used to work perfectly on 1.0.0-nightly (2b01a37ec 2015-02-21).

But since I updated my Rust and my `rust` submodule (including any dependencies) to the latest 1.0.0-nightly (c89de2c56 2015-03-28), I get a whole slew of these errors when building `liballoc` or anything that depends on it:

       Compiling alloc v0.0.1 (file:///home/virtlink/projects/alloctest/lib/liballoc)
    src/lib.rs:1:1: 1:1 error: duplicate entry for `const_ptr` [E0152]
    src/lib.rs:1 // Copyright 2014 The Rust Project Developers. See the COPYRIGHT
                 ^
    src/lib.rs:1:1: 1:1 error: duplicate entry for `mut_ptr` [E0152]
    src/lib.rs:1 // Copyright 2014 The Rust Project Developers. See the COPYRIGHT
                 ^
    src/lib.rs:1:1: 1:1 error: duplicate entry for `i8` [E0152]
    src/lib.rs:1 // Copyright 2014 The Rust Project Developers. See the COPYRIGHT

    ...

    src/lib.rs:1:1: 1:1 error: duplicate entry for `non_zero` [E0152]
    src/lib.rs:1 // Copyright 2014 The Rust Project Developers. See the COPYRIGHT
                 ^
    src/lib.rs:1:1: 1:1 error: duplicate entry for `debug_trait` [E0152]
    src/lib.rs:1 // Copyright 2014 The Rust Project Developers. See the COPYRIGHT
                 ^
    error: aborting due to 58 previous errors
    Could not compile `alloc`.

I symlink `libcore` and `liballoc`, and add a `Cargo.toml` for each (see below). Here's a working reproduction of the issue:

    cargo new alloctest
    cd alloctest
    mkdir -p lib/libcore
    mkdir -p lib/liballoc
    
    git submodule add https://github.com/rust-lang/rust.git lib/rust
    cd lib/rust
    git checkout c89de2c56baeb61e7cc434924dcc8bedd32b26b8

    cd ../libcore
    ln -s ../rust/src/libcore/ src
    
    cat << EOF > Cargo.toml
    [package]
    name = "core"
    version = "0.0.1"
    authors = [ "some@example.com" ]
    EOF

    cd ../liballoc
    ln -s ../rust/src/liballoc/ src
    
    cat << EOF > Cargo.toml
    [package]
    name = "alloc"
    version = "0.0.1"
    authors = [ "some@example.com" ]

    [features]
    external_funcs = []

    [dependencies.core]
    path = "../libcore"
    EOF

    cargo build

**Comment by alexcrichton** [comment]
The reproduction looks like it may have forgotten `#![no_std]` in the library itself, perhaps that was left out by accident?

**Comment by Virtlink** [comment]
These lines are present in the `lib.rs` of both `libcore` and `liballoc` when I get the errors:

    #![feature(no_std)]
    #![no_std]

It happens without changing a thing in the original source files.

**Comment by rprichard** [comment]
The reproduction failed for me:
```
./test.sh: 14: cd: can't cd to ../lib/libcore
```
The `cd ../lib/libcore` should be `cd ../libcore`, I think.  The same problem happens with `cd ../lib/liballoc` -- it should be `cd ../liballoc`.

With those two changes, I'm able to reproduce the duplicate entry errors.

**Comment by Virtlink** [comment]
@rprichard You're right. I fixed it.

**Comment by rprichard** [comment]
It looks like `rustc` is pulling in lang items from both the `libcore` you compiled and the `libcore` from the system root.  I tried setting the sysroot to an empty directory, but then the build failed, because it couldn't find `libc`.  `liballoc` needs `libc` unless `external_funcs` or `external_crate` is set.

`Cargo.toml` specifies `external_funcs`, but `cargo` does not actually pass it to `rustc`.  Here's the `cargo --verbose` output:
```
Process didn't exit successfully: `rustc src/lib.rs --crate-name alloc --crate-type lib -g -C metadata=4b6a8ab3fd4b7ba5 -C extra-filename=-4b6a8ab3fd4b7ba5 --out-dir /home/rprichard/mess/TEST/alloctest/lib/liballoc/target/debug --emit=dep-info,link -L dependency=/home/rprichard/mess/TEST/alloctest/lib/liballoc/target/debug -L dependency=/home/rprichard/mess/TEST/alloctest/lib/liballoc/target/debug/deps --extern core=/home/rprichard/mess/TEST/alloctest/lib/liballoc/target/debug/deps/libcore-fa8a124aff706daf.rlib`
```
This manifest change fixes it:

In `lib/liballoc/Cargo.toml`, replace:
```
[features]
external_funcs = []
```
with:
```
[features]
default = ["external_funcs"]
external_funcs = []
```

**Comment by Virtlink** [comment]
@rprichard Yes! Thank you! That solves it.

Is this intended behavior or a bug?

**Comment by rprichard** [comment]
Not sure; I'm fairly unfamiliar with cargo.

**Comment by steveklabnik** [comment]
@alexcrichton is this intended Cargo behavior or not?

**Comment by alexcrichton** [comment]
Yes it looks like `liballoc` [depends on `libc`](https://github.com/rust-lang/rust/blob/14192d6df5cc714e5c9a3ca70b08f2514d977be2/src/liballoc/lib.rs#L89-L90) so if you're not specifying the `external_funcs` feature then it will pull that in, which then transitively depends on the libcore in the main distribution, causing the duplicates here.

In short, I do believe this is all intended behavior!

**Comment by Virtlink** [comment]
@alexcrichton I did specify the `external_funcs` feature in `liballoc` `Cargo.toml`:

```
[package]
name = "alloc"
version = "0.0.1"
authors = [ "some@example.com" ]

[features]
external_funcs = []

[dependencies.core]
path = "../libcore"
```

Apparently it needs to be set as the default:

```
[features]
default = ["external_funcs"]
external_funcs = []
```

This wasn't the case before.
