### ISSUE TITLE
Tuple structs interact oddly with closures and lifetimes

### ISSUE THREAD

**Issue by lfairy** [rust-lang/rust#23858]
This works:

```rust
fn main() {
    let f: &(Fn(i32) -> i32) = &|x| x;
    println!("{}", f(1));
}
```

This also works:

```rust
struct Wrapper<'a> {
    inner: &'a (Fn(i32) -> i32 + 'a)
}
fn main() {
    let f = Wrapper { inner: &|x| x };
    println!("{}", (f.inner)(1));
}
```

But this causes an error:

```rust
struct Wrapper<'a>(&'a (Fn(i32) -> i32 + 'a));
fn main() {
    let f = Wrapper(&|x| x);
    println!("{}", (f.0)(1));
}
```

```
thing.rs:3:22: 3:27 error: borrowed value does not live long enough
thing.rs:3     let f = Wrapper(&|x| x);
                                ^~~~~
thing.rs:3:28: 5:2 note: reference must be valid for the block suffix following statement 0 at 3:27...
thing.rs:3     let f = Wrapper(&|x| x);
thing.rs:4     println!("{}", (f.0)(1));
thing.rs:5 }
thing.rs:3:5: 3:28 note: ...but borrowed value is only valid for the statement at 3:4
thing.rs:3     let f = Wrapper(&|x| x);
               ^~~~~~~~~~~~~~~~~~~~~~~
thing.rs:3:5: 3:28 help: consider using a `let` binding to increase its lifetime
thing.rs:3     let f = Wrapper(&|x| x);
               ^~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
```

I suspect it's because function calls (of which tuple struct constructors are a special case) are treated differently to struct literals in the borrow checker. If this is the case, should they be made consistent instead?

**Comment by arielb1** [comment]
This is how rvalue lifetimes work: an rvalue within a function call is destroyed after the statement ends, while an rvalue outside of one is destroyed at the end of the block (and struct literals are not function calls). 

For example:
```Rust
fn id<T>(t: T) -> T { t }
fn main() {
    let x = id(&2); //~ ERROR borrowed value does not live long enough
    println!("{}", x);    
    let y = &2;
    println!("{}", y); // no error
}
```

**Comment by arielb1** [comment]
Because there is no right choice regarding rvalue lifetimes, I think this should be closed.

**Comment by nikomatsakis** [comment]
Worth pointing out though that this would possibly be fixed by RFC 66, which is as yet unimplemented:

https://github.com/rust-lang/rfcs/blob/master/text/0066-better-temporary-lifetimes.md

**Comment by flying-sheep** [comment]
so how do i express this?

```rust
struct Inner<'a> { s: &'a str }

struct Outer<'a>(Inner<'a>);
```

that gives me ``parameter `'d` is never used [E0392]``

**Comment by nikomatsakis** [comment]
@flying-sheep can you provide a complete example? For example, this builds fine: http://is.gd/dWANjL

**Comment by flying-sheep** [comment]
hmm, i get that it was never used.

**Comment by nikomatsakis** [comment]
On Tue, Nov 03, 2015 at 12:47:01PM -0800, Philipp A. wrote:
> hmm, i get that it was never used.

what version of rustc are you using?

**Comment by flying-sheep** [comment]
sorry for the late answer but i can’t reproduce it now. i tried again to make it clone-free by adding lifetimes, and now it worked.
