### ISSUE TITLE
Document that IntoIterator allows for `for...in` sugar

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#23851]
http://doc.rust-lang.org/core/iter/trait.IntoIterator.html

I think we should mention somewhere in the docs for `IntoIterator` that implementing this trait allows one to write:

```rust
let my_vec = vec![1, 10, 100];
for i in my_vec { ... }
```

instead of

```rust
let my_vec = vec![1, 10, 100];
for i in my_vec.iter() { ... }
```

**Comment by FreeFull** [comment]
What about an explanation of `for x in &values` and `for x in &mut values`?

**Comment by frewsxcv** [comment]
That seems more of a conceptual, in-depth question that should probably be answered in the Book rather than API documentation

**Comment by Gankro** [comment]
@FreeFull Or would be good in the top-level Iterator or Collections docs.
