### ISSUE TITLE
Default methods in trait documentation

### ISSUE THREAD

**Issue by jooert** [rust-lang/rust#23864]
When looking at the documentation of a certain trait (e.g. http://doc.rust-lang.org/std/iter/trait.Iterator.html), I can't tell which methods have to be implemented to use this trait or which ones have a default implementation (and don't have to be provided when implementing the trait). They are just in the same section "Required Methods" (which is kind of intimidating when trying to implement an Iterator :wink:).

**Comment by mbrubeck** [comment]
This is a regression.  In old docs, the methods were separated into "Required Methods" and "Provided Methods":

http://doc.rust-lang.org/0.12.0/std/iter/trait.Iterator.html
