### ISSUE TITLE
From implies Into

### ISSUE THREAD

**Issue by TimNN** [rust-lang/rust#23889]
Currently `Into` is implemented for all types based on their `From` implementation: `impl<T, U> Into<U> for T where U: From<T> { .. }`.

This leads to confusing error messages (cc #22590):

```rs
#![feature(convert)]

pub struct A;

fn test<T: Into<u32>>(_: T) {}

fn main() {
    test(A);
}
```

```
error: the trait `core::convert::From<A>` is not implemented for the type `u32` [E0277]
```

as well as asymmetric behaviour: If you implement `From`, `Into` is also implemented, but if you implement `Into`, `From` is *not* automatically implemented.

This is a result of the fact that both traits essentially mean the same thing: convert `A` to `B`.

As such `Into` and `From` could (and maybe should) be replaced by a single trait.

At the very least the current behaviour (of implementing `Into` for types implementing `From`) should be **prominently** documented (in the module documentation and the documentation for both traits) but I think it would be preferable to have a lint which produces at least a warning if `Into` is implemented instead of `From`.

**Comment by Gankro** [comment]
Short explanation before @aturon gets around to an actually good one:

The current implementation orphan rules are assymetric with respect to Self. So there are things that can implement From but not Into, but we can *blanket* Into. So that's what we do.

**Comment by TimNN** [comment]
After the stabilisation pull request landed the only issue I have left is lacking documentation of `core::convert`, so I'm closing this in favour of #24107.
