### ISSUE TITLE
Items with 'lexical' scope have poor scoping

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#23880]
E.g., 

```
struct Foo;

impl Foo {
    fn bar(&self) {}

    fn foo(&self) {
        fn bar(x: &Foo) {}
        
        bar(self);
    }
}

fn main() {}
```

Is an error, but shouldn't be, because the `bar` method hides the locally declared `bar` function inside `foo`.

I think this is a bug, so it shouldn't be on any milestone, but nominating just in case.

**Comment by oli-obk** [comment]
It's not an error anymore: http://is.gd/CKvJn3

**Comment by nrc** [comment]
Ah curses, that isn't an error. Here's another go:

```
struct Foo<X> {
    x: Box<X>
}

impl<Bar> Foo<Bar> {
    fn foo(&self) {
        type Bar = i32;

        let _: Bar = 42;
    }
}
```

In this case the `let` statement should see the local type alias, but sees the type parameter.

**Comment by pnkfelix** [comment]
classifying as "just a bug", P-high, not 1.0.

**Comment by nikomatsakis** [comment]
triage: P-medium

This has been sitting for a while and we don't expect immediate action, though hopefully a refactoring of resolve would lead to this being fixed.
