### ISSUE TITLE
metabug: const_eval bugs from type confusion and/or overflow

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#23897]
metabug: const_eval bugs from type confusion and/or overflow

(I am collapsing these seemingly distinct categories into one, because I have observed cases where a seeming failure to catch an overflow, or signaling an overflow where none should exist, can sometimes be traced to the const-evaluator being confused about the type of the expression in question.)

**Comment by pnkfelix** [comment]
(tagging as A-typesystem since that's what @steveklabnik seems to often do, though I am currently wondering if we should actually have an A-consteval label at this point...)

**Comment by steveklabnik** [comment]
Yeah, with this many issues...

**Comment by steveklabnik** [comment]
Triage: this is a metabug, some stuff has changed, but not all of it.

**Comment by pnkfelix** [comment]
Hmm are we close to being able to close this metabug? I see almost all of the linked issues are now closed; the one remaining one is rust-lang/rfcs#1071, which is more ... philosophical...?

**Comment by pnkfelix** [comment]
Yes at this point I think https://github.com/rust-lang/rust/pull/30587 resolved all of our known issues here.
