### ISSUE TITLE
File owner/group API in new std::fs module

### ISSUE THREAD

**Issue by jnicholls** [rust-lang/rust#23892]
It appears as though the new std::fs module did not port over the abstraction of setting Ownership, like it did with setting Permissions.  std::old_io::fs::chown is the only way to do this right now, particularly on a unix system.

Are we expected to FFI this ourselves at 1.0 beta/stable?

**Comment by alexcrichton** [comment]
Thanks for the issue! This is currently covered by https://github.com/rust-lang/rfcs/issues/939 which is tracking a comprehensive look at the `std::fs` module to see how best to expand it in the future. Currently, yes, you'll need to call `chown` manually as we're not exporting a stable function for it.

**Comment by jnicholls** [comment]
Awesome, thanks for the link to the RFC (I need to get habitual about checking that first :)
