### ISSUE TITLE
tons of 404s due to sidebar-items.js

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#23900]
related to https://github.com/rust-lang/rust/issues/14515

in `src/librustdoc/html/render.rs`

```
2327         if parentlen == 0 {
2328             // there is no sidebar-items.js beyond the crate root path
2329             // FIXME maybe dynamic crate loading can be merged here
2330         } else {
```

I'm not sure if this codepath is the problem, but we have tons of 404s on `sidebar-items.js` not existing, because pages like http://doc.rust-lang.org/std/usize/index.html have `../sidebar-items.js`, which is wrong.

**Comment by nhowell** [comment]
I'm not seeing these 404s. Has it since been fixed?

Unrelated: I've noticed that the sidebar doesn't highlight the active module in the sidebar, though. (Structs, functions, et al. get highlighted when active, though). Seems like a bug to me.

**Comment by steveklabnik** [comment]
I am not seeing them anymore as well, so I think this has. Thanks for the prompt!
