### ISSUE TITLE
Rustdoc does not display function for reexports of a path that refers to both a fn and mod

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#23903]
Or at least rustdoc doesn't show the function. I haven't tested it. It also compiles without a warning.

**Comment by liigo** [comment]
Please test it first, and make it precise, if you're reporting an issue.

**Comment by huonw** [comment]
The following seems to compile fine, so the reexport appears to be working. I guess this just is a rustdoc bug?

```rust
mod foo {
    pub fn bar() {}
    pub mod bar { pub fn baz() {} }
}

mod qux {
    pub use foo::bar;
}

fn main() {
    foo::bar();
    foo::bar::baz();
    qux::bar();
    qux::bar::baz();
}
```
