### ISSUE TITLE
rustdoc links to private structs, causing 404s

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#23912]
See http://doc.rust-lang.org/std/primitive.char.html#method.into_searcher as an example, `CharEqPattern` goes nowhere

**Comment by rprichard** [comment]
Another example: https://doc.rust-lang.org/std/fmt/struct.Formatter.html#method.align. The `core::fmt::rt::v1::Alignment` type is public in this case, but it's explicitly hidden.

**Comment by steveklabnik** [comment]
Yeah, there's a _lot_ of these.

**Comment by tomjakubowski** [comment]
For `CharEqPattern`, it could be related to re-exported signatures. The same method in `core` doesn't have this issue: http://doc.rust-lang.org/core/primitive.char.html#method.into_searcher

Also, is it a bug that you can have private items in a public signature's `QPath`? Or private items in an impl for a public type? cc @alexcrichton @nikomatsakis

**Comment by tomjakubowski** [comment]
I wonder if rustdoc should be resolving qualified paths that it encounters.

**Comment by mitaa** [comment]
Is there still some unresolved issue here?

**Comment by QuietMisdreavus** [comment]
Still a thing; for example, [Copy](https://doc.rust-lang.org/1.19.0/std/marker/trait.Copy.html) tries to link to types in rand, but the doc link is broken. (That link goes to 1.19.0, but it's still there in today's nightly docs.)

If i were to guess, it probably has to do with rustdoc seeing types that are in dependencies of std, but aren't being documented alongside it.

**Comment by GuillaumeGomez** [comment]
Wrote a fix for it. Will make the PR tomorrow or after tomorrow.

**Comment by QuietMisdreavus** [comment]
This issue was actually fixed by https://github.com/rust-lang/rust/pull/44026. The issue i actually referenced in that PR was apparently a duplicate of this one. `>_>`
