### ISSUE TITLE
rustdoc has issues with std::rand::distributions

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#23916]
http://doc.rust-lang.org/std/rand/distributions/ has a `src` link that doesn't work.

**Comment by steveklabnik** [comment]
and all its submodules, apparently

**Comment by tomjakubowski** [comment]
I should note that while the module is deprecated, there is surely an underlying rustdoc issue that needs fixing! Hopefully it can be identified before the module is removed :)

**Comment by alexcrichton** [comment]
This is due to the fact that we've got a redirection rule set for `/rand` on the `doc.rust-lang.org` server to forward to the `rust-lang/rand` docs. This whole module is deprecated anyway, and soon there will be no reexports in the standard library from `rand`, so I'm going to close this.
