### ISSUE TITLE
improve Sized/Reflect trait docs

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#23915]
http://doc.rust-lang.org/core/marker/trait.Sized.html

The `implementors` section is nonexistant.

**Comment by steveklabnik** [comment]
and http://doc.rust-lang.org/std/marker/trait.PhantomFn.html

**Comment by steveklabnik** [comment]
and reflect http://doc.rust-lang.org/std/marker/trait.Reflect.html

**Comment by tomjakubowski** [comment]
This is an interesting problem. Rustdoc currently tracks implementors of a trait `Trait` by specifically looking for `impl Trait for <type> { /* ... */ }` items. Since these are implicitly implemented for marker traits Rustdoc will need to special-case those when generating implementor pages.

**Comment by alexcrichton** [comment]
I'm willing to say that this is all working as intended. I don't think we want to list every single type in the implementors section of `Sized` and `Reflect`, as it would be... all types!

I think that this is just a general "let's improve the documentation for these traits" bug, so I'm going to retitle/relabel.

**Comment by steveklabnik** [comment]
I'm not keeping bugs open for non-specific 'improve these docs,' so i'll give it a close, then. Of course I hope to improve these docs at some point!
