### ISSUE TITLE
Helpful error message when confusing a field with a method

### ISSUE THREAD

**Issue by catamorphism** [rust-lang/rust#2392]
I forget if there's already a bug on this, but it would be nice if, when you wrote ```A.B``` and ```A``` doesn't have a field named ```B```, but does have a nullary method named ```B```, the compiler gave a hint like "did you mean to write ```A.B()```?" It could also do vice versa (if you write A.B()``` and ```A``` is a class with field ```B```, it could ask "did you mean ```A.B```?)

I ran into this in trans, where I have frequently written ```bcx.ccx``` instead of ```bcx.ccx()```.

**Comment by huonw** [comment]
Updated the example @vks gives:

```rust
struct Cat {
    x: i32
}

trait Meow {
    fn mew(&self) -> i32;
}

impl Meow for Cat {
    fn mew(&self) -> i32 {
        self.x
    }
}

fn main() {
    let kitty = Cat { x:5 };
    assert!(kitty.x() == 5);
}
```

which now prints

```
<anon>:17:19: 17:22 error: type `Cat` does not implement any method in scope named `x`
<anon>:17     assert!(kitty.x() == 5);
                            ^~~
<anon>:17:19: 17:22 note: use `(s.x)(...)` if you meant to call the function stored in the `x` field
<anon>:17     assert!(kitty.x() == 5);
                            ^~~
```

It's nice that the note is there, but the text is suboptimal: `kitty.x` isn't a function.

**Comment by Nashenas88** [comment]
I'm working on a fix for this, but I'm struggling with the final portion. With this code:

```rust
struct Cat<F> where F: FnMut() -> u32 {
    func: F,
    x: i32
}

trait Meow {
    fn mew(&self) -> i32;
}

impl Meow for Cat {
    fn mew(&self) -> i32 {
        self.x
    }
}

fn main() {
    let kitty = Cat { func: || 5, x: 5 };
    assert!(kitty.x() == 5);
    let x = kitty.func();
    assert_eq!(x, 5);
}
```

I get the output:

```
<anon>:18:19: 18:22 error: type `Cat` does not implement any method in scope named `x`
<anon>:18     assert!(kitty.x() == 5);
                            ^~~
<anon>:18:19: 18:22 note: did you mean to write `Cat.x`?
<anon>:18     assert!(kitty.x() == 5);
                            ^~~
<anon>:19:19: 19:25 error: type `Cat` does not implement any method in scope named `func`
<anon>:19     let x = kitty.func();
                            ^~~~~~
<anon>:19:19: 19:25 note: use `(Cat.func)(...)` if you meant to call the function stored in the `func` field
<anon>:19     let x = kitty.func();
                            ^~~~~~
```

My current changes are [here](https://github.com/rust-lang/rust/compare/master...Nashenas88:field-method-message-2392). I'm not sure if it's possible to have the output say "kitty.func" and "kitty.x" with the input to the `report_error` function. Any ideas? Or should I just keep the message in the same format as it is now and output "s.func" and "did you mean to write `s.x`?"?

**Comment by Nashenas88** [comment]
I got around that error message. Now I'm making sure the previous `(kitty.func)(...)` message is displayed under the proper circumstances.
