### ISSUE TITLE
error output between self-hosted versus cross-compile target differs significantly for some tests

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#23926]
The error output between self-hosted versus cross-compile target can differ significantly for some tests.

In some cases one can get around this via `error-pattern`, but it does not work universally.

This bug is to mark such cases, and hopefully go back and identify _why_ the error output is so different (in some cases the reason may be self-evident, but that was not universally true).

**Comment by pnkfelix** [comment]
Ah this case 
  https://github.com/rust-lang/rust/blob/2a9de1d989d7f95846b711eec2695cbd86794ee3/src/test/compile-fail/huge-array-simple.rs
is one of the ones that seems self-evident:

 * on 32-bit hosts, the shift overflows.
 * But on 64-bit hosts, the shift succeeds, and then the attempt to create the huge array overflows.

Maybe the easiest thing would be to make 32- and 64-bit variants of that same test.  (That or conditionalize the size we feed into the array construction based on pointer size.)

**Comment by steveklabnik** [comment]
Triage: no changes I'm aware of.

**Comment by Mark-Simulacrum** [comment]
There are two other tests currently tagged with this issue, const-eval-overflow-3.rs and const-eval-overflow-3b.rs, both in compile-fail. The issue with both appears to be the same as with the previous test mentioned; we either can or cannot create and evaluate the const array depending on platform.

**Comment by pnkfelix** [comment]
I wonder if we might be able to leverage the revision system in some way here. That, or as I noted earlier: make pointer-size-specific variants of each test. (And then presumably ignore the tests on platforms that cannot support the 64-bit pointer-sized variant.)

**Comment by pnkfelix** [comment]
Better solution: make target-specific versions of each `fn main` with a customized const expression for the target of interest, and then use `// normalize-stderr-test REGEXP -> OUTPUT` to normalize to a single canonical output for the test.
