### ISSUE TITLE
Stability attributes ignored on use declarations

### ISSUE THREAD

**Issue by rprichard** [rust-lang/rust#23937]
`std::collections` reexports `collections::linked_list`, which has this alias:

``` rust
#[deprecated(since = "1.0.0", reason = "renamed to LinkedList")]
#[unstable(feature = "collections")]
pub use LinkedList as DList;
```

`collections::linked_list` and `collections::linked_list::LinkedList` are stable, so presumably the intent of these stability attributes was to stop stable code from using the `DList` name, but it doesn't work.  This compiles fine:

``` rust
use std::collections::linked_list::DList;
fn main() {
    DList::<i32>::new();
}
```

AFAICT, stability attributes don't affect `pub use` declarations.

(Aside: AFAICT, stability attributes also don't affect `impl`s either, but maybe I'm missing something? The standard library has stability attributes on many of its `impl`s.)

**Comment by steveklabnik** [comment]
This appears to be fixed. 

```
#![feature(staged_api)]
#![staged_api]

#[stable]
struct Foo;

#[deprecated(since = "1.0.0", reason = "renamed to LinkedList")]
#[unstable(feature = "collections")]
pub use Foo as Bar;

fn main() {
    Bar::new();
}
```

gives

```
hello.rs:9:9: 9:19 error: `Foo` is private, and cannot be reexported [E0364]
hello.rs:9 pub use Foo as Bar;
                   ^~~~~~~~~~
hello.rs:9:9: 9:19 help: run `rustc --explain E0364` to see a detailed explanation
hello.rs:9:9: 9:19 note: Consider marking `Foo` as `pub` in the imported module
hello.rs:9 pub use Foo as Bar;
                   ^~~~~~~~~~
```

**Comment by petrochenkov** [comment]
@steveklabnik 
This is not fixed.
Correct example is:

```
#![feature(staged_api)]
#![staged_api]

#[stable(feature = "rust1", since = "1.0.0")]
pub struct Foo;

#[deprecated(since = "1.0.0", reason = "renamed to LinkedList")]
#[unstable(feature = "collections", issue = "0")]
pub use Foo as Bar;

fn main() {
    let bar = Bar;
}
```

Use of `Bar` should give a deprecation warning / stability error, but it doesn't - stability/deprecation attributes on reexports are ignored.

**Comment by steveklabnik** [comment]
Ah, my bad.

**Comment by bstrie** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/30827.
