### ISSUE TITLE
Implement an `all` lint to allow people to mass-toggle every available lint at once

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#23935]
There should exist a special `all` lint which would make it possible to do any of the following:
```
#[allow(all)]
#[warn(all)]
#[deny(all)]
rustc -A all
rustc -W all
rustc -D all
```
Be sure to document this in the output of `rustc -W help`. If this lint is already implemented and I just can't figure out how to invoke it, then the documentation step still needs to be completed before this bug is closed.

Inspired by this reddit plea: https://www.reddit.com/r/rust/comments/310p4s/how_do_i_turn_off_warnings_in_rustc/

**Comment by Manishearth** [comment]
```
#![allow(warnings)]
#![warn(warnings)]
#![deny(warnings)]
rustc -A warnings
rustc -W warnings
rustc -D warnings
```

:smile: 

This is listed in the help page, just that it's wedged between all the other individual lints. Probably should be listed in the lint groups instead.

**Comment by alexcrichton** [comment]
Yes I believe that the "warnings" group lint suffices for now, you probably really don't want to turn on all lints as you'll get warnings for things like using `Box`! That specific reddit comment thread should be good with `-A warnings`, so I think we're all set here!
