### ISSUE TITLE
testsuite idea: print $(TESTNAME) value in the test stamp files (and then check it)

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#23957]
I find it a little awkward that I have to track down the right stamp file to delete when I try using `$(TESTNAME)` to narrow the test suite while e.g. debugging a test.

I imagine we _might_ be able get around this in the makefile by only allowing the stamp file to satisfy the necessary dependency if it has a matching value for `$(TESTNAME)`.

(Originally I thought that putting the info into the content of the file would be the right option, but on reflection, another approach would be to encode the value of `$(TESTNAME)` _into_ the needed stamp filename itself.)

**Comment by pnkfelix** [comment]
this is arguably a dupe of #7540, except that I'm actually suggesting a potential fix.

**Comment by cyplo** [comment]
Hi ! Is this still an issue ? If so - does the fix seem reasonably straightforward or is this a bigger one ?
If it is a small-medium one, maybe we could promote this one via This Week In Rust/having "help wanted"/etc ?

**Comment by pnkfelix** [comment]
@cyplo It is still an issue, at least with the `make` based builds. I don't know what `rustbuild` does here, if it supports the test suite at all.

**Comment by Mark-Simulacrum** [comment]
Since #7540 is fixed (see last comment) with rustbuild, I'm going to close.
