### ISSUE TITLE
Can't use externally defined lifetimes in macros due to hygiene

### ISSUE THREAD

**Issue by HeroesGrave** [rust-lang/rust#23956]
I've tried using `ty`, `expr`, `tt` and `ident` fragments but nothing works.

Macros should have a lifetime fragment type (`$foo:lifetime`). It's currently a rather annoying hole in `macro_rules!` usability.

**Comment by steveklabnik** [comment]
superseded by https://github.com/rust-lang/rust/issues/34303, I believe. Closing!
