### ISSUE TITLE
!0u32/2 gives “error: attempted to divide with overflow in a constant expression [E0020]”

### ISSUE THREAD

**Issue by andersk** [rust-lang/rust#23968]
```rust
println!("{}", !0u32);  // 4294967295
println!("{}", !0u32/2);  // error: attempted to divide with overflow in a constant expression [E0020]
const A: u32 = !0;
println!("{}", A/2);  // error: attempted to divide with overflow in a constant expression [E0020]
let a: u32 = !0;
println!("{}", a/2);  // 2147483647
const B: u32 = 4294967295;
println!("{}", A == B);  // true
println!("{}", B/2);  // 2147483647
```

This affects the test suites for the `num` and `rand` crates.

```console
$ rustc --version
rustc 1.0.0-dev (built 2015-04-02)
$ dpkg-query -W rust-nightly
rust-nightly	201504020407~2e3b0c0~vivid
```

**Comment by pnkfelix** [comment]
triage: I-wrong, P-high (1.0)

**Comment by pnkfelix** [comment]
triage: P-high (1.0)

**Comment by pnkfelix** [comment]
@nrc I ended up adding the 1.0 milestone by hand; isn't the above note with `triage:` supposed to do it?

**Comment by pnkfelix** [comment]
cc #23897

**Comment by nrc** [comment]
@pnkfelix the log above says that highfive did add this to the 1.0 milestone - it might just have been that your local view of the webpage needed refreshing?

**Comment by pnkfelix** [comment]
@nrc yeah I guess so, I don't know what happened anymore.  Maybe I should have given highfive a little more time to react.
