### ISSUE TITLE
Tuple indexing syntax is missing from the rust book

### ISSUE THREAD

**Issue by andreabedini** [rust-lang/rust#23962]
It seems tuple indexing syntax is not introduced anywhere in the current documentation.

It shows up briefly here http://doc.rust-lang.org/nightly/reference.html#tuple-types as 

    assert!(p.0 == 10);

but nowhere else.

I think it should be introduced both there and here http://doc.rust-lang.org/nightly/book/compound-data-types.html#tuples

I'd help with some text but but there's nothing I hate more than writing :)

ping @steveklabnik

**Comment by steveklabnik** [comment]
I thought I had this in somewhere, but maybe I don't
