### ISSUE TITLE
Can define a associated type more than once

### ISSUE THREAD

**Issue by Kimundi** [rust-lang/rust#23969]
```rust
trait Foo {
    type Ty;
}

impl Foo for () {
    type Ty = ();
    type Ty = usize;
}

fn main() { 
    let _: <() as Foo>::Ty = ();
}
```

This erroneously parses and compiles fine, the compiler seems to use the first definition of `Ty` in the impl.

This might have been introduced by #23265, ping @eddyb.

**Comment by alexcrichton** [comment]
triage: I-nominated

**Comment by pnkfelix** [comment]
classifying as just a bug.  P-backcompat-lang, not 1.0 blocker.

**Comment by brson** [comment]
Demoting this to P-medium. Somebody should get on it though!
