### ISSUE TITLE
saturating_mul methods?

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#23975]
Integers have `checked_add`, `checked_mul`, and `saturating_add` methods, but not `saturating_mul`. Is there a reason not to have this in std?

CC @aturon

**Comment by pnkfelix** [comment]
I suspect we want the full set,  `saturating_add`, `saturating_sub`, `saturating_mul`, `saturating_div` (not sure about whether `saturating_rem` makes any sense).

See also https://github.com/rust-lang/rfcs/issues/928 and https://github.com/rust-lang/rfcs/issues/964

**Comment by apasel422** [comment]
`saturating_mul` [now exists](https://doc.rust-lang.org/nightly/std/?search=saturating_mul) for all integer types.

**Comment by alexcrichton** [comment]
Yay!
