### ISSUE TITLE
Don’t suggest 'help: add #![feature(…)]' when it’s forbidden

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#23973]
Steps to reproduce:

```sh
mkdir foo
cd foo
multirust override beta  # Or obtain Rust beta in some other way
echo 'extern crate core; fn main(){}' > a.rs
echo '#![feature(core)] extern crate core; fn main(){}' > b.rs
```

The output of `rustc a.rs` is:
```rust
a.rs:1:1: 1:19 error: use of unstable library feature 'core'
a.rs:1 extern crate core; fn main(){}
       ^~~~~~~~~~~~~~~~~~
a.rs:1:19: 1:19 help: add #![feature(core)] to the crate attributes to enable
```

`b.rs` does as suggested by the `help` message, but that fails too (as expected):
```rust
b.rs:1:1: 1:18 error: unstable feature
b.rs:1 #![feature(core)] extern crate core; fn main(){}
       ^~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
error: aborting due to previous error
```

Proposed fix: in the beta and stable channels (i.e. whenever `#![feature(…)]` is forbidden), the `help` message that suggests adding `#![feature(…)]` should not be shown.

(Clean up the test case with `multirust remove-override; cd ..; rm -r foo`.)

CC @brson

**Comment by steveklabnik** [comment]
Gonna milestone this real quick, as it seems quite important.

**Comment by pnkfelix** [comment]
I might be able to whip up a quick fix, though I'm not 100% sure about testing it properly ... (I've never actually tried building something for a non-dev release channel before...)

**Comment by steveklabnik** [comment]
after chatting with @pnkfelix it seems like I have a patch, building it now

**Comment by steveklabnik** [comment]
gonna leave @pnkfelix to it

**Comment by conradkleinespel** [comment]
Hello good Rust folks :smile: 

Before the beta, I used `std::slice::bytes:MutableByteVector` which is in `core`. Is there any way to use this trait during the beta ? I'm not sure how I can get the code to compile.

Thanks for any tip / hints you can offer :+1:

**Comment by SimonSapin** [comment]
Hi @conradkleinespel. Commenting on random unrelated issues is usually not the right thing to do. You should rather open a new issue, or ask on http://users.rust-lang.org/ . But to answer your question anyway, that trait only has [one method](https://github.com/rust-lang/rust/blob/b2e65ee6e4e1523b1d4c56ea0ec430e28946f2f4/src/libcore/slice.rs#L1507-L1518):

```
    /// A trait for operations on mutable `[u8]`s.
    pub trait MutableByteVector {
        /// Sets all bytes of the receiver to the given value.
        fn set_memory(&mut self, value: u8);
    }

    impl MutableByteVector for [u8] {
        #[inline]
        fn set_memory(&mut self, value: u8) {
            unsafe { ptr::write_bytes(self.as_mut_ptr(), value, self.len()) };
        }
    }
```

… and `std::ptr::write_bytes` is stable and can be used on beta. So I’d recommend you copy/paste the trait into your code, or make a function.

**Comment by conradkleinespel** [comment]
@SimonSapin Thanks for taking the time to answer. I appreciate it.

I don't see how this is unrelated. This is related, since the code I'm talking about used to compile with `#![feature(core)]` and the compiler suggests to do that, during the beta period.

Thanks for your tip on copying the function :+1: I guess I'll just do that if nothing better is available and change this again when the trait is stable.

**Comment by SimonSapin** [comment]
This specific issue is about fixing one of the compiler’s error message, not about fixing code that triggers that error. It really helps everyone to keep discussions on topic.

**Comment by conradkleinespel** [comment]
Alright. I understand. I'll make sure to open a new issue or go on StackOverflow next time if appropriate. Thanks again :+1:

**Comment by jonalmeida** [comment]
This doesn't seem to be properly fixed in the beta channel. I'm still being recommended to add `#![feature(libc)]` in the errors, and then told it's not available in the beta channel.
```zsh
[/tmp] rustc snappy.rs
snappy.rs:1:1: 1:19 error: use of unstable library feature 'libc'
snappy.rs:1 extern crate libc;
            ^~~~~~~~~~~~~~~~~~
snappy.rs:1:19: 1:19 help: add #![feature(libc)] to the crate attributes to enable
snappy.rs:2:5: 2:17 error: use of unstable library feature 'libc'
snappy.rs:2 use libc::size_t;
                ^~~~~~~~~~~~
snappy.rs:2:17: 2:17 help: add #![feature(libc)] to the crate attributes to enable
snappy.rs:6:56: 6:62 error: use of unstable library feature 'libc'
snappy.rs:6         fn snappy_max_compressed_length(source_length: size_t) -> size_t;
                                                                   ^~~~~~
snappy.rs:6:62: 6:62 help: add #![feature(libc)] to the crate attributes to enable
snappy.rs:6:67: 6:73 error: use of unstable library feature 'libc'
snappy.rs:6         fn snappy_max_compressed_length(source_length: size_t) -> size_t;
                                                                              ^~~~~~
snappy.rs:6:73: 6:73 help: add #![feature(libc)] to the crate attributes to enable
error: aborting due to 4 previous errors
[/tmp] rustc snappy.rs
snappy.rs:1:1: 1:18 error: unstable feature
snappy.rs:1 #![feature(libc)]
            ^~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
error: aborting due to previous error
```

Rust version:
```zsh
[/tmp] rustc --version
rustc 1.0.0-beta (9854143cb 2015-04-02) (built 2015-04-02)
```

The code I used (snappy example in the docs with the extra addition on the first line:
```rust
#![feature(libc)]
extern crate libc;
use libc::size_t;

#[link(name = "snappy")]
extern {
        fn snappy_max_compressed_length(source_length: size_t) -> size_t;
}

fn main() {
        let x = unsafe { snappy_max_compressed_length(100) };
            println!("max compressed length of a 100 byte buffer: {}", x); 
}

```

**Comment by bombless** [comment]
This happened after Beta release.
We'll see the effect of this patch in 1.0 and afterwards Beta, etc.

**Comment by jonalmeida** [comment]
Whoops, I thought this made it in before beta. Thanks!

**Comment by SimonSapin** [comment]
@brson, are there plans to release updates to the beta channel within a given 6 weeks cycle? Either this one or in the future.

**Comment by pnkfelix** [comment]
I'm certain there will be updates; see discussion from last night here: https://github.com/rust-lang/meeting-minutes/blob/master/weekly-meetings/2015-04-07.md#policy-for-prs-targeting-beta-vs-master

**Comment by Russell91** [comment]
So how does one fix this error? I'm a new user of the rust library and I can't seem to use the collections library during the beta due to this problem. Given this git issue is a top google result, it would be nice if there were a solution here.

**Comment by pnkfelix** [comment]
@Russell91 by design, you have access to the parts of `libcollections` that are *re-exported* from `libstd` (and are stable).  

http://doc.rust-lang.org/1.0.0-beta/std/collections/
