### ISSUE TITLE
Build fails with external LLVM with ARM backend disabled

### ISSUE THREAD

**Issue by pcercuei** [rust-lang/rust#23971]
When compiling with an external LLVM toolchain (using --llvm-root) that does not support the ARM backend, the compilation of the Rust compiler will fail.

I traced it to mk/main.mk:270:
```
LLVM_COMPONENTS=x86 arm aarch64 mips powerpc ipo bitreader bitwriter linker asmparser mcjit interpreter instrumentation
```

This causes the link step to fail, as "llvm-config" issues an error as it does not recognize the "arm" and "aarch64" components.

**Comment by pcercuei** [comment]
Actually this is not enouch since the LLVM_LIBS_* and LLVM_LDFLAGS_* are set in mk/main.mk but don't seem to be used elsewhere.
When adding those variables inside mk/target.mk for the linking step, I still get errors as Rustc seems to use ARM-specific symbols from the LLVM libraries.

**Comment by tamird** [comment]
Dupe of #14729?

**Comment by alexcrichton** [comment]
Looks like it!
