### ISSUE TITLE
Specifying `no_std` with `extern crate std` does not import `core`

### ISSUE THREAD

**Issue by Virtlink** [rust-lang/rust#23982]
I'm trying to have `std` imported conditionally for testing only, as I use `core` in my OS kernel, and found this issue. This minimal code:

    #![feature(no_std)]
    #![no_std]
    extern crate std;

    #[derive(Copy)]
    pub enum Kind {
        None = 0,
        Reserved = 1,
    }

Gives errors on `cargo build`:

       Compiling example v0.0.1 (file:///home/virtlink/projects/example)
    src/lib.rs:5:10: 5:14 error: failed to resolve. Maybe a missing `extern crate core`?
    src/lib.rs:5 #[derive(Copy)]
                          ^~~~
    src/lib.rs:5:10: 5:14 note: in expansion of #[derive_Copy]
    src/lib.rs:5:10: 5:14 note: expansion site
    src/lib.rs:5:10: 5:14 error: use of undeclared trait name `core::marker::Copy`
    src/lib.rs:5 #[derive(Copy)]
                          ^~~~
    src/lib.rs:5:10: 5:14 note: in expansion of #[derive_Copy]
    src/lib.rs:5:10: 5:14 note: expansion site
    error: aborting due to 2 previous errors
    Could not compile `example`.

However, if you remove the top three lines and let `std` be imported implicitly, then it works. For some reason the explicit `extern crate std` behaves differently from the implicit `std` import, which I did not expect.

I can't (and wouldn't expect to have to) do `extern crate core` explicitly, due to issue #23983.

    rustc 1.0.0-nightly (c89de2c56 2015-03-28) (built 2015-03-29)
    binary: rustc
    commit-hash: c89de2c56baeb61e7cc434924dcc8bedd32b26b8
    commit-date: 2015-03-28
    build-date: 2015-03-29
    host: x86_64-unknown-linux-gnu
    release: 1.0.0-nightly

**Comment by alexcrichton** [comment]
Thanks for the report! The usage of `#![no_std]` is definitely pretty rough around the edges. I'm going to link this to our [tracking issue](https://github.com/rust-lang/rfcs/issues/1005) for stabilizing the `#![no_std]` attribute for now to make sure we handle it. In light of that, I'm also going to close in favor of that issue as well!
