### ISSUE TITLE
Associated item stability is not pulled from trait

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#23989]
Items in a trait implementation should inherit the stability from the trait items, but this is not currently happening for associated types. (Or, at least, rustdoc is not reporting them correctly).

See, for example, the `Index` implementation [for `String`](http://static.rust-lang.org/doc/master/std/string/struct.String.html)

**Comment by steveklabnik** [comment]
Triage: not aware of any changes.

**Comment by petrochenkov** [comment]
Individual trait impl items don't even have stability now.
This can be closed.
