### ISSUE TITLE
Error msg is obtuse when doing `float_fallback += 1;` (or any int literal)

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#23994]
This may be WONTFIX but I'm reporting it in case it isn't. I'm not sure what the opinion on this is exactly anyway. The idea came from [here](http://users.rust-lang.org/t/is-the-homepage-example-wrong-on-purpose/763). This error may come up very easily on [rust-lang.org](http://www.rust-lang.org/) and so is likely very noticeable. This:

``` rust
fn main() {
    let mut x = 0.0;
    x += 1;
}
```

Gives this error:

``` cmd
<anon>:3:5: 3:6 error: binary assignment operation `+=` cannot be applied to types `_` and `_` [E0368]
<anon>:3     x += 1;
             ^
error: aborting due to previous error
playpen: application terminated with error code 101
```

There are three issues, particularly to a new user (first time exploring `rust-lang.org`):
- The distinction `0` and `0.0` may seem bizarre
- Use of the mysterious type `_` will be puzzling and makes the error confusing
- Comparing `_` and `_` makes it worse.

It would be ideal if `1` could be inferred to the type of `x` in this case. This would also avoid this confusing error on the rust main landing page.

**Comment by daboross** [comment]
Just as a note, I think both types are _ because rustc doesn't know exactly what types they actually *are*. The `1` could be any number type really, from `u8` to `i64`, and the `0.0` could be either `f32` or `f64`. It should have a better way of describing this, yes, but I don't think it's exactly clear what exactly it *should* be saying instead of `_`. Since it doesn't know what either of them are, it is surprising that it doesn't assume the 1 to be an f32/f64 as well.

**Comment by bluss** [comment]
Wishes for new features should go on the RFC repo, and the issue is already present: rust-lang/rfcs#260

**Comment by bluss** [comment]
Note: The well-defined default type for `0.0` is `f64` in Rust (in case it is not inferred to a specific floating point type)

**Comment by pnkfelix** [comment]
Nonetheless, the error message here is particularly bad ...

**Comment by pnkfelix** [comment]
(but I agree with @bluss's assessment, and conclude that my title change is not quite right.)

**Comment by mdinger** [comment]
@bluss It didn't occur to me this would be a feature. I thought it might have just been a bug or old design decision.

What a better error message would look like isn't clear which is why I didn't suggest it though.

**Comment by jaredly** [comment]
Instead of '_' it would be nice to have "integral type" (that language shows up elsewhere) and "float type"

**Comment by leodasvacas** [comment]
1.14 output:
```
error[E0277]: the trait bound `{float}: std::ops::AddAssign<{integer}>` is not satisfied
 --> <anon>:3:5
  |
3 |     x += 1;
  |     ^^^^^^ the trait `std::ops::AddAssign<{integer}>` is not implemented for `{float}`
  |
  = help: the following implementations were found:
  = help:   <f64 as std::ops::AddAssign>
  = help:   <f32 as std::ops::AddAssign>
  = help:   <u64 as std::ops::AddAssign>
  = help:   <std::time::Duration as std::ops::AddAssign>
  = help: and 24 others
```
This bug is fixed.

**Comment by bluss** [comment]
Thank you. New bugs can be filed if there are problems with the new error message.
