### ISSUE TITLE
Not sure on how to pass a trait method to an operator.

### ISSUE THREAD

**Issue by norcalli** [rust-lang/rust#23999]
I'm not even sure how to title this. As you can see in [this playpen](http://is.gd/xvf7R3), I was playing around with the idea to implement a pipe operator [from this stackoverflow](http://stackoverflow.com/questions/17054978/composition-operator-and-pipe-forward-operator-in-rust). But I'm getting what feels like inconsistent behaviour. Is there a way to do this without having to define a new function? And why does the method call not work?

```rust
// #![feature(unboxed_closures)]
use std::ops::{Shr, FnOnce};

struct Wrapped<T>(T);

impl<A, B, F: FnOnce(A) -> B> Shr<F> for Wrapped<A> {
    type Output = Wrapped<B>;

    fn shr(self, f: F) -> Wrapped<B> {
        Wrapped(f(self.0))
    }
}

fn tos<T: ToString>(t: T) -> String { t.to_string() }

fn main () {
    // error: the type of this value must be known in this context
    //let s = Wrapped(1i32) >> (|x| x + 1) >> (|x| 2*x) >> (|x| x.to_string());
    
    // error: ...the trait `core::ops::FnOnce<(i32,)>` is required (expected i32, found &-ptr)
    //let s = Wrapped(1i32) >> (|x| x + 1) >> (|x| 2*x) >> ToString::to_string;
    
    
    // Works:
    //let s = Wrapped(1i32) >> (|x| x + 1) >> (|x| 2*x) >> (|x| format!("{}", x));
    
    // This works:
    //let s = Wrapped(1i32) >> (|x| x + 1) >> (|x| 2*x) >> (|x| tos(x));
    
    // Which is basically this, which also works:
    let s = Wrapped(1i32) >> (|x| x + 1) >> (|x| 2*x) >> tos;
    println!("{}", s.0)
}
```

**Comment by cybergeek94** [comment]
`ToString::to_string` takes `&self` and not `self`, that's why you get the second error

This works: 
```rust
let s = Wrapped(1i32) >> (|x| x + 1) >> (|x| 2*x) >> (|x| ToString::to_string(&x));
```

As for why `(|x| x.to_string())` fails to typecheck, I couldn't say. It'd be nice if the compiler explained the type ambiguity here. Adding a type annotation fixes it, though: 

```rust
let s = Wrapped(1i32) >> (|x| x + 1) >> (|x| 2*x) >> (|x: i32| x.to_string());
```

**Comment by norcalli** [comment]
@cybergeek94 After playing more with rust, the `ToString` point makes sense. I was seeing `&` still in C++ terms before. But mostly, I want to understand better why the `.to_string()` example doesn't work.

**Comment by steveklabnik** [comment]
Triage: this doesn't really seem like a bug, and it's been over a year with no comment, so closing.
