### ISSUE TITLE
doc for std::vec repeats itself

### ISSUE THREAD

**Issue by EdorianDark** [rust-lang/rust#24006]
In the nigtly documentation for std::vec the traid implementation for PartialEq is listed 69 times.

    impl<'a, 'b, A, B> PartialEq<[B; 0]> for Vec<A> where A: PartialEq<B> 
([B;1] untill [B;31] are omited)
    impl<'a, 'b, A, B> PartialEq<&'b [B; 32]> for Vec<A> where A: PartialEq<B>

**Comment by steveklabnik** [comment]
This isn't a bug, notice how `[B; 0]` turns into `[B; 1]`, and then `[B; 2]`.

Each size of an array is its own type.
