### ISSUE TITLE
json Using Autoserialization example not compiling

### ISSUE THREAD

**Issue by kostya** [rust-lang/rust#24007]
i trying to compile this example: https://doc.rust-lang.org/serialize/json/#using-autoserialization, but get

```
a.rs:5:26: 5:41 error: failed to resolve. Maybe a missing `extern crate rustc_serialize`?
a.rs:5 #[derive(RustcDecodable, RustcEncodable)]
```

rustc 1.0.0-nightly (d754722a0 2015-03-31) (built 2015-04-01)

**Comment by kostya** [comment]
fixed by this example: https://doc.rust-lang.org/rustc-serialize/rustc_serialize/json/index.html#using-autoserialization

**Comment by yaitskov** [comment]
then it fails with 

```
error: can't find crate for `rustc_serialize
```
