### ISSUE TITLE
resurrect research paper list

### ISSUE THREAD

**Issue by vks** [rust-lang/rust#24004]
With removing the wiki, the list of research papers was removed as well. They still can be found [here](https://github.com/rust-lang/rust-wiki-backup/blob/029a999f7a641ee25596aa00ca09f6b760f1d10e/Note-research.md). However, this location is really hard to find, and I think it is a quite interesting resource.

Would it make sense to add it to the documentation in the main rust repo?

**Comment by steveklabnik** [comment]
Yes, that'd be great.

**Comment by nikomatsakis** [comment]
This does feel like the kind of thing for which wikis are a very good fit.

**Comment by vks** [comment]
Well, we killed the wiki, didn't we?

**Comment by pczarn** [comment]
this is done
