### ISSUE TITLE
Doc: std::process::exit v.s. threads

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#24001]
The documentation for `std::process::exit` should mention what happens to other threads in the same process. Are they killed instantly? Are they joined? Are destructors in the thread’s stack run?

**Comment by bluss** [comment]
> Terminates the current process with the specified exit code.

> This function will never return and will immediately terminate the current process. The exit code is passed through to the underlying OS and will be available for consumption by another process.

> Note that because this function never returns, and that it terminates the process, no destructors on the current stack or any other thread's stack will be run. If a clean shutdown is needed it is recommended to only call this function at a known point where there are no more destructors left to run.

Looks like they are terminated instantly. The destructor question is explicitly addressed -- they do not run, in any thread.

**Comment by SimonSapin** [comment]
Looks like I didn’t real carefully enough. Sorry!
