### ISSUE TITLE
Consolidate documentation from Pointers section on ownership under Ownership section

### ISSUE THREAD

**Issue by aquach** [rust-lang/rust#24019]
I've been following the rust book to learn rust, and I found the second half of the pointers section (https://github.com/rust-lang/rust/blob/master/src/doc/trpl/pointers.md) confusing because it introduces Boxes and refers to ownership without having formally introduced it in the following Ownership section. It's hard to motivate why Boxes are useful and a good abstraction without having a clear picture of ownership and movement. I think it would make sense to move the section on Boxes from Pointers into Ownership.

Relatedly, I think my mental model on ownership, movement, and borrowing became a lot clearer when I started with ownership, Boxes, and movement, then motivated why borrowing was useful and how to borrow safely—aka, explain buying from a store, then borrowing from a library, rather than starting with borrowing and going backwards to ownership. I can see why it makes sense to introduce references first as they're lighter weight.

Just my two cents!

**Comment by steveklabnik** [comment]
Hey @aquach! Thanks for this.

I have plans to re-organize this stuff, and I think you're going to like it. I'm going to leave this open for now, but may close it at some point. I do think the weakness you've pointed out is legitimate, but I may solve the issue another way.

**Comment by aquach** [comment]
Thanks for your patient response! Glad to hear it.

**Comment by steveklabnik** [comment]
So, now that the TOC has changed, the old pointer guide is gone, so I'm considering this closed for now. Ownership still needs to be improved, but that'll happen regardless of this issue. thank you again!
