### ISSUE TITLE
Automated ICE issue traging

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#24017]
Hopefully this nice-to-have issue belongs in this tracker.

It would be nice to have an automated triage bot that looks through issues tagged with `I-ICE` and runs the test case with the latest nightly. In case it compiles fine or errors out gracefully, it should mark it as `E-needstest` or perhaps `E-revisit` (as it may very well be still ICEing, just that some changes are necessary). It shouldn't be too hard to identify what the particular code sample is as in most cases it's the only standalone code snippet in the issue description, so no extra process overhead would be necessary for this to work well, I think.

This could be extended further to work with other types of issues but this is perhaps the most immediately obvious application that I can think of.

I'd love to work on this myself but sadly time is scarce so I'm putting up the idea here, at least. :) I know in the perfect world rustc wouldn't ICE so much that we'd need extra process but since that's a reality that is unlikely to change, this may be worth considering.

**Comment by barosl** [comment]
This is indeed an interesting idea! So in your scenario, the bot should automatically extract the test case from the reported issue, right?

**Comment by jakub-** [comment]
@barosl Indeed!

I naturally think tools like this must be careful not to add overhead to the process such as imposing a stricter structure on issues being filed. But I think the tool will be able to identify the test case in most cases (i.e. decide which code block resembles Rust code the most etc.)

**Comment by steveklabnik** [comment]
Glacier kind of fills this role today.
