### ISSUE TITLE
'make' should not update local snapshot unnecessarily

### ISSUE THREAD

**Issue by dhardy** [rust-lang/rust#24026]
So I did this (trying to make use of some time on the train to hack on the compiler):

1.  (online) check out rust code base
2.  (online) run `./configure`
3.  (offline) build with `make` (successfully)
4.  connect to the web via phone while on train (low data limit and slow)
5.  `make install` ... only instead of just installing the existing build output it somehow notices that a new snapshot is available and tries to download (at which point I kill)
6.  (offline again) `make` now fails

Maybe this is not a common use case, but intuitively I would not expect building to update dependencies unless (a) they have not yet been fetched, (b) newer versions are required than installed (i.e. after repo update) or (c) on manual command. Is it possible to do this?

**Comment by steveklabnik** [comment]
I'm not sure this is fixible, it's generally neccesary to be on the exact snapshot of Rust.

**Comment by steveklabnik** [comment]
Isn't `(a)` your case here?

**Comment by dhardy** [comment]
How exactly is (a) the case? I did a full 'make' before this; surely 'make install' doesn't need dependencies that 'make' doesn't?

To be honest I just find this confusing...

On Sat Apr 4 19:00:44 2015 GMT+0300, Steve Klabnik wrote:
> Isn't `(a)` your case here?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/rust-lang/rust/issues/24026#issuecomment-8960475

-- 
Sent from my Jolla

**Comment by steveklabnik** [comment]
Oops, sorry, I mis-read your post. My apologies.

**Comment by steveklabnik** [comment]
Triage: not aware of any changes here, though maybe rustbuild is better about this?

**Comment by alexcrichton** [comment]
Yeah I believe that this is solved with rustbuild, which is hopefully coming soon, so I'm going to close this in favor of that.
