### ISSUE TITLE
Move "3.8 Associated Types" section after "3.12 Traits"

### ISSUE THREAD

**Issue by aquach** [rust-lang/rust#24020]
The "Associated Types" section assumes knowledge of traits, so it makes sense to put it after the section on traits.

**Comment by steveklabnik** [comment]
These sections are intended to be read out of order, and stand relatively alone. In that context, I'm closing this, but we can do a better job of things like the intro here: http://doc.rust-lang.org/nightly/book/closures.html#closure-implementation

**Comment by aquach** [comment]
That makes sense, thanks! Though to facilitate user comprehension, it seems like a good idea to order the chapters at least a little bit, since most people are going to be reading them in the order they appear even if it wasn't intended to be that way.

**Comment by steveklabnik** [comment]
That is one of the things I'm giving very serious consideration to with the big plans I have for the book during the beta period. :smile: :+1:

**Comment by aquach** [comment]
:+1:
