### ISSUE TITLE
The "testing" section of the rust book needs a small correction

### ISSUE THREAD

**Issue by lucatrv** [rust-lang/rust#24030]
The code example at https://doc.rust-lang.org/book/testing.html#documentation-tests should be corrected changing `mod tests {` into `mod test {`.

**Comment by steveklabnik** [comment]
nice catch!

**Comment by callahad** [comment]
Should this instance be `mod test`, or should everything else be `mod tests` instead?

Judging from crates.io, it looks like `mod tests` is more common. Granted, half of it is alexcrichton, but still ;-)

Incoming PR to that effect.

**Comment by callahad** [comment]
$ grep -r 'mod tests {' src/lib* | wc -l
          63
    $ grep -r 'mod test {'  src/lib* | wc -l
          58

Oh, really now?

**Comment by lucatrv** [comment]
I actually vote for everything else to be `mod tests`.

**Comment by callahad** [comment]
Aw, shoot. From some more grepping, the style guide and the language reference both refer to `mod test`. Going with that.

**Comment by lucatrv** [comment]
Ok but... to me it doesn't make sense that we use `mod test` and then we name the folder `tests`, as they both can contain multiple tests...

**Comment by callahad** [comment]
/me considers giving Steve a choose-your-own-adventure pair of pull requests.
