### ISSUE TITLE
std::io::Error is Send but not Sync

### ISSUE THREAD

**Issue by kballard** [rust-lang/rust#24049]
The `std::io::Error` type is `Send` but it's not `Sync`. This is because of the use of `Box<Error+Send>`, as that value is not `Sync`, and so therefore `io::Error` is not `Sync`.

This is a problem for me as I want to stuff an `io::Error` into a `sync::Arc` and have the resulting value be `Send`, but `Arc` is only `Send` if its element type is `Send + Sync`.

/cc @alexcrichton

**Comment by alexcrichton** [comment]
This is currently an intentional decision as by using a trait object it will *always* be opting out of some marker traits. The only real fundamental piece of functionality we wanted to add to `io::Error` was the ability to send it across threads, hence `Send`. That said we can always tweak this, however.

**Comment by alexcrichton** [comment]
I'm starting to think that putting an error in an `Arc` is a pretty important use case, in which case I would be fine going ahead and adding the `Sync` bound to `io::Error`

**Comment by kballard** [comment]
I'm still in favor of just making `io::Error` use `Arc` directly instead of `Box` (which still requires the `Sync` bound), because then I could just go back to calling `.clone()` on `io::Error` instead of using a custom `Error` type that pretends to be the underlying shared `io::Error`.

**Comment by kballard** [comment]
It occurs to me that, AFAIK, we can't use smart pointers with trait objects yet. So we can't actually say `Arc<error::Error+Send+Sync>`. `io::Error` currently has a `Box`-in-a-`Box` so we could use `Arc` on the outer `Box`, although I don't see any good reason for it to have two `Box`es right now at all (AFAICT all it's doing is saving one word from the size of `io::Error`s initialized with OS error codes).

**Comment by kballard** [comment]
#24133 makes `io::Error` implement `Sync`. I've filed #24135 for the proposal to make `io::Error` use `Arc` internally so it can conform to `Clone`.
