### ISSUE TITLE
Consider stabilizing std::raw::TraitObject

### ISSUE THREAD

**Issue by carllerche** [rust-lang/rust#24050]
Consider stabilizing std::raw::TraitObject or some other API that allows deconstructing / constructing trait objects into the various components. I have needed to do this a number of times for various optimizations (avoid allocations and optimizing the memory layout of various structures).

cc @aturon @nikomatsakis

**Comment by steveklabnik** [comment]
I know @reem cares about this too

**Comment by reem** [comment]
fwiw my use of `raw::TraitObject` has just been to do downcasting and access the data field, which @nikomatsakis figured out a way around which I wrote up (and use from) https://github.com/reem/rust-traitobject. We also discussed another weird workaround of just inlining the definition, but that will break horribly if the internal representation changes.

**Comment by alexcrichton** [comment]
Thanks for the issue! I'm gonna move this over to #24028 for now so we don't have an issue-per-api :)
