### ISSUE TITLE
rustup.sh: fail faster if user doesn't have required permissions

### ISSUE THREAD

**Issue by vbezhenar** [rust-lang/rust#24052]
If user runs `rustup.sh` without sudo, it'll download large file only to fail at the last stage. May be script should do some quick-checks to fail faster.

**Comment by GuillaumeGomez** [comment]
I asked the same question some times ago and the answer was: "you have to check a script before executing it, it's your reponsibility to run it with the needed authorizations".

Otherwise I agree with you. I hope the answer will be a little more favorable this time.

**Comment by daboross** [comment]
If this is implemented, it would be nice to only enable it when not using `--save`. With `--save`, downloading it and saving it then failing to install might be a desirable behavior.

**Comment by steveklabnik** [comment]
Triage: i wonder if today this shouldn't be re-filed against https://github.com/rust-lang/rustup.sh, and in general, `rustup.sh` is on its way out, so this ticket may be unneeded in the near future.

**Comment by edunham** [comment]
Help wanted: Please PR to https://github.com/rust-lang/rustup.sh

**Comment by mark-i-m** [comment]
I think rust-lang/rustup.sh#69 should solve this, right?

**Comment by GuillaumeGomez** [comment]
@mark-i-m: It should yes. Add "Fixes #24052" in a message of your PR, it'll close this issue when it gets merged.
