### ISSUE TITLE
Include page title in the API search result

### ISSUE THREAD

**Issue by mhristache** [rust-lang/rust#24062]
The API doc search is not very user friendly as the results only include a description of each result entry. The description is most of the time very generic, e.g. it's hard to know when the search result points to a module doc, or to a primitive or whatever.

See the screen shot below, the first result is pointing to the `str` module doc, which is not very helpful IMHO. The helpful result is the 4th one (the `str` primitive doc) but it's impossible to know that without going thru each result.

![screen shot 2015-04-04 at 12 56 59](https://cloud.githubusercontent.com/assets/2771485/6992396/c25c93f2-dacb-11e4-921f-cd0474524c30.png)

I think the search results should include the title of the page which will make it possible to easily find the wanted page.

**Comment by tomjakubowski** [comment]
The final segment of each path is color coded, but yeah there's not really a way to know which color is which other than by experience.

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by steveklabnik** [comment]
Triage: the page titles are even more generic, they just have the type name in them.

There has been no change, but I wonder if this is something we want to fix, really. Maybe it comes down to writing better summaries. (Also, note that the `str` primitive type is first nowadays.)

**Comment by jsha** [comment]
Search results now show `str (primitive)`, and color code different types of results: in the light theme, blue for modules, purple for structs, and orange for fns (not all colors listed here). @mhristache does this solve the issue for you?

![image](https://user-images.githubusercontent.com/220205/120676993-76d20a00-c44b-11eb-908d-6b327f0a753d.png)

**Comment by mhristache** [comment]
I guess it does. Thanks for the improvements!
