### ISSUE TITLE
Char primitive page links to non-existent struct

### ISSUE THREAD

**Issue by daboross** [rust-lang/rust#24077]
http://doc.rust-lang.org/std/primitive.char.html links to http://doc.rust-lang.org/core/str/pattern/struct.CharSearcher.html with `type Searcher = CharSearcher<'a>`, and struct.CharSearcher.html seems to 404.

**Comment by steveklabnik** [comment]
I have this open as another bug, it's because `CharSearcher` isn't a public type.

**Comment by daboross** [comment]
ahh, ok. Thanks!
