### ISSUE TITLE
Official Rust book's docs on slice patterns fail in current 1.0.0 Beta release

### ISSUE THREAD

**Issue by toolness** [rust-lang/rust#24076]
I'm very new to Rust, so apologies if this is something obvious, or is already logged as a bug that I haven't managed to find yet...

The [Patterns section of The Rust Programming Language book](http://doc.rust-lang.org/1.0.0-beta/book/patterns.html) has the following code:

> If you want to match against a slice or array, you can use `&`:
> ```rust
fn main() {
    let v = vec!["match_this", "1"];
>
    match &v[..] {
        ["match_this", second] => println!("The second element is {}", second),
        _ => {},
    }
}
```

However, actually compiling this using Rust 1.0.0 Beta returns the following error:

```
src\main.rs:5:9: 5:31 error: slice pattern syntax is experimental
src\main.rs:5         ["match_this", second] => println!("The second element is
{}", second),
                      ^~~~~~~~~~~~~~~~~~~~~~
src\main.rs:5:31: 5:31 help: add #![feature(slice_patterns)] to the crate attributes to enable
error: aborting due to previous error
Could not compile `foo`.
```

Yet following the help by adding the `slice_patterns` crate attribute fails too:

```
src\main.rs:1:1: 1:28 error: unstable feature
src\main.rs:1 #![feature(slice_patterns)]
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
error: aborting due to previous error
Could not compile `foo`.
```

Perhaps this particular section of the chapter should be moved to the [Unstable Rust](http://doc.rust-lang.org/1.0.0-beta/book/unstable.html) section of the book? Or am I missing something obvious?

## Meta

`rustc --version --verbose`:

```
rustc 1.0.0-beta (9854143cb 2015-04-02) (built 2015-04-02)
binary: rustc
commit-hash: 9854143cba679834bc4ef932858cd5303f015a0e
commit-date: 2015-04-02
build-date: 2015-04-02
host: x86_64-pc-windows-gnu
release: 1.0.0-beta
```

**Comment by steveklabnik** [comment]
Yes, this should move to the unstable section

**Comment by steveklabnik** [comment]
I've since moved this to unstable. Thanks!
