### ISSUE TITLE
book: Associated Types depends on Traits, but precedes it

### ISSUE THREAD

**Issue by github-monoculture** [rust-lang/rust#24074]
The Associated Types section talks about Traits the whole way through, so one has to skip ahead a few sections to learn about Traits.

**Comment by steveklabnik** [comment]
Thanks @github-monoculture ! Currently, the second section of the book isn't meant to be in any particular order, so this isn't really a bug at the moment.

I'm going to be doing a re-organization of the table of contents this week, so this will end up being addressed then.
