### ISSUE TITLE
Unclear vector/slice comparison in section 2.12 of docs

### ISSUE THREAD

**Issue by maxbrunsfeld** [rust-lang/rust#24070]
Thanks for creating such readable docs!

When vectors are introduced in [section 2.12](https://github.com/rust-lang/rust/blob/master/src/doc/trpl/arrays-vectors-and-slices.md), an analogy is made involving slices:

> Vectors are to slices what String is to &str.

But I don't think slices have been introduced yet; they're introduced later in that section:

> A *slice* is a reference to (or "view" into) an array.

Maybe the first quote should compare vectors to arrays, rather than slices?

**Comment by steveklabnik** [comment]
You're welcome!

So, one thing is that we generally assume that these are read out of order. I'm working on a new TOC that should address larger issues, but this might be an inter-issue. I'm pretty sure we talked about slices in section 1, though, do you happen to know?

**Comment by maxbrunsfeld** [comment]
Yeah, I was reading the sections out of order myself; I'm talking about the ordering *within* this one section though. Vectors are introduced first, and explained via an analogy with slices. Then slices are introduced further down.

**Comment by steveklabnik** [comment]
yes, understood. I was just wondering if this is the first place we _ever_ talk about slices, or if they were before?

**Comment by maxbrunsfeld** [comment]
I don't think that they are. String slices are introduced in the previous section though.
