### ISSUE TITLE
slice.splitn usize argument differs from str.splitn

### ISSUE THREAD

**Issue by daboross** [rust-lang/rust#24082]
The `str.splitn` method was updated to use the `usize` parameter as the maximum splits to make, instead of the maximum number of items to return. However, `slice.splitn` still uses the `usize` parameter as the maximum number of items to return. Both methods are stable.

This inconsistency could possibly be way more confusing than having them both one way or the other.

Excerpt from `str.splitn` documentation (http://doc.rust-lang.org/std/primitive.str.html#method.splitn)
```
An iterator over substrings of self, separated by characters matched by a pattern, returning most count items.
```

From `slice.splitn` documentation (http://doc.rust-lang.org/std/primitive.slice.html#method.splitn):
```
Returns an iterator over subslices separated by elements that match pred, limited to returning at most n items. The matched element is not contained in the subslices.
```

**Comment by daboross** [comment]
Sorry, wasn't sure if this was an accident after the switching of the usage in `str.splitn`, or something which would be better addressed in the rfcs repository. If this is in the wrong place, I'll move it to where it would be better suited. I'm not sure this is that important of an issue if it was specifically excluded from the change in `str.splitn`, it was just a bit confusing when using the slice method after using the new str method.

**Comment by alexcrichton** [comment]
I'm a little confused, could you clarify a bit? Currently the count parameter on both functions indicates the number of returned items, for example:

```rust
fn main() {
    for a in "ababa".splitn(2, 'b') {
        println!("{}", a);
    }
    for a in [1, 2, 1, 2, 1].splitn(2, |x| *x == 2) {
        println!("{:?}", a);
    }
}
```

```
a
aba
[1]
[1, 2, 1]
```

Do you think this is a docs problem?

**Comment by daboross** [comment]
Oh, what. I think I completely misread the docs that I pasted, they are the exact same.

I'm not entirely sure what I was thinking, thank you for clarifying!

**Comment by alexcrichton** [comment]
Ah ok, thanks for the issue regardless!
