### ISSUE TITLE
Add Servo's memory reporting to rustc

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#24083]
This probably means pulling out Servo's stuff into a crate of its own (if that is possible and amenable to the Servo folks), then using that crate in rustc (either as a submodule or by just moving the reporting stuff into the rust distro). Adding the actual hooks into rustc shouldn't be too tricky, presumably we'd need to add a -Z flag and code to setup the system reporter and to call that, probably in the same places we use `time_passes`. Finer-grained memory reporting can come later.

We really need decent stats on compiler memory usage before we start doing big refactorings of the compiler.

One thing I'm not sure about is if we can do memory reporting at the end of a phase and get the peak memory usage during that phase. That seems to me to be the most useful statistic, but it doesn't look like we can get that - only the amount of memory currently allocated, which is probably minimal between phases.

cc @jdm @nnethercote

**Comment by jdm** [comment]
Relevant low-level stuff: http://mxr.mozilla.org/servo/source/components/util/mem.rs
Relevant high-level stuff: http://mxr.mozilla.org/servo/source/components/profile/mem.rs

**Comment by nrc** [comment]
I added cruder memory reporting, so we have enough for now. We might want something more sophisticated in the future, but I don't think this needs to stay open.
