### ISSUE TITLE
Pointers and references are not listed as primitive types

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#24090]
Rustdoc does not list `*const _`, `*mut _`, `&_`, `&mut _` as primitive types. They have some inherent methods (e.g. `(*const _)::offset`), but they won’t be discoverable even if https://github.com/rust-lang/rust/issues/23511 is fixed unless this also is fixed.

**Comment by steveklabnik** [comment]
dup of https://github.com/rust-lang/rust/issues/15654 and https://github.com/rust-lang/rust/issues/15654
