### ISSUE TITLE
ICE caused by LLVM assertion: Assertion `S->getType()->isPtrOrPtrVectorTy() && "Invalid cast"'

### ISSUE THREAD

**Issue by Valloric** [rust-lang/rust#24098]
I was updating some code to rust beta and have just hit this roadblock when trying to run tests:

```
rustc: /home/rustbuild/src/rust-buildbot/slave/beta-dist-rustc-linux/build/src/llvm/lib/IR/Constants.cpp:1622: static llvm::Constant* llvm::ConstantExpr::getPointerCast(llvm::Constant*, llvm::Type*): Assertion `S->getType()->isPtrOrPtrVectorTy() && "Invalid cast"' failed.
Aborted (core dumped)
```

Repro steps:

1. Checkout [this commit](https://github.com/Valloric/nailgun/commit/fd59694d5797383d6c3dcdac19af4e748f5e8d02).
2. Run `./test.sh` from the top-level repo dir.

I tried minimizing the code by hand for a smaller test case, but failed.

Version: `rustc 1.0.0-beta (9854143cb 2015-04-02) (built 2015-04-02)`
OS: OS X Yosemite 10.10.2 (14C1514)

Seems related to: #19748, #19826

**Comment by sanxiyn** [comment]
I failed to reproduce this, after applying Valloric/nailgun@1eaf332 which was necessary to compile. Does it still happen for you?

**Comment by Valloric** [comment]
I haven't tried to repro this since, but the current nailgun codebase doesn't have this issue because I added workarounds. If you tried to repro with the exact nailgun and rustc commits listed, it would most likely repro, but that may not be relevant since rustc has moved on since then.

**Comment by apasel422** [comment]
After checking out the commit given in the first post and updating `generator/unescape.rs` for feature gates and a removed function, this no longer ICEs.
