### ISSUE TITLE
thread::spawn should not print panic message

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#24099]
http://is.gd/fUQtJN prints a `thread '<unnamed>' panicked at 'explicit panic', <anon>:5` even though I supposedly explicitly handle it.

**Comment by shepmaster** [comment]
The code in question, in case the link goes stale:

```rust
use std::thread;

fn main() {
    let r = thread::spawn(|| {
        panic!();
    }).join();
    println!("{:?}", r.is_err());
}
```

**Comment by ebfull** [comment]
This is one of the things which is not stable yet. This is how rustc does it:

```rust
#![feature(set_stdio)]

use std::thread;
use std::io;
use std::io::prelude::*;
use std::sync::{Arc,Mutex};

fn main() {
    struct Sink(Arc<Mutex<Vec<u8>>>);
    impl Write for Sink {
        fn write(&mut self, data: &[u8]) -> io::Result<usize> {
            Write::write(&mut *self.0.lock().unwrap(), data)
        }
        fn flush(&mut self) -> io::Result<()> { Ok(()) }
    }

    let data = Arc::new(Mutex::new(Vec::new()));
    let err = Sink(data.clone());

    let r = thread::spawn(|| {
        io::set_panic(Box::new(err));
        panic!();
    }).join();
    println!("{:?}", r.is_err());
}
```

Why is the std::io::set_panic() function not documented in the nightly docs?

**Comment by nagisa** [comment]
> Why is the std::io::set_panic() function not documented in the 
nightly docs?

Because it is an implementation detail of the standard library.

**Comment by alexcrichton** [comment]
cc @aturon and https://github.com/rust-lang/rfcs/issues/946

**Comment by steveklabnik** [comment]
With https://github.com/rust-lang/rfcs/pull/1328 merged, this should be helpful for this, yeah?

**Comment by aturon** [comment]
@steveklabnik Yes, to some degree. Note, though, that the panic handler will run immediately upon panicking, regardless of any subsequent recovers.

**Comment by bltavares** [comment]
Triaging: given that we have the rust-lang/rfcs#1328 merged, and [stabilised already](https://github.com/rust-lang/rust/issues/30449), should we update the code example to the following?

```rust
#![feature(panic_handler)]
use std::panic;
use std::thread;

fn main() {
    let r1 = thread::spawn(|| {
        panic!("This should print");
    }).join();
    println!("r1: {:?}", r1.is_err());

    let r2 = thread::spawn(|| {
        panic::set_hook(Box::new(|_| ()));
        panic!("This should not print");
    }).join();
    panic::take_hook();
    println!("r2: {:?}", r2.is_err());
    
    let r3 = thread::spawn(|| {
        panic!("This should print");
    }).join();
    println!("r3: {:?}", r3.is_err());
}

```

**Comment by Mark-Simulacrum** [comment]
What is intended to happen here? As far as I know, the print on panic behavior isn't really possible to change, though we do have features that are either stabilized or on track that solve this (e.g., `panic::set_hook`). Perhaps the right thing to do is to close, then? If people want this behavior (no printing), they should use a custom hook.

**Comment by Mark-Simulacrum** [comment]
`panic::set_hook` allows disabling or modifying the print message; as such, I'm going to close. For example, code here (https://github.com/rust-lang/rust/issues/24099#issuecomment-222790630) now prints (note: doesn't print 'should not print').

```
thread '<unnamed>' panicked at 'This should print', test.rs:7
note: Run with `RUST_BACKTRACE=1` for a backtrace.
r1: true
r2: true
thread '<unnamed>' panicked at 'This should print', test.rs:19
r3: true
```
