### ISSUE TITLE
Access not existing member vector: no type for expr in fcx

### ISSUE THREAD

**Issue by faern** [rust-lang/rust#24094]
Accessing self.not_exsisting_vector[self.not_existing + self.also_not_existing] fails as it should, but it also panics, which it should not.

I tried this code (http://is.gd/S6oqIh):

    struct Foo;
    impl Foo {
        pub fn create_a_mess(&self) {
            self.not_existing_vector[self.i + self.a];
        }
    }
    fn main() {}

I expected to see this happen: Just complain that the member did not exist, not panic.

Instead, this happened:

    <anon>:5:9: 5:33 error: attempted access of field `not_existing_vector` on type `&Foo`, but no field with that name was found
    <anon>:5         self.not_existing_vector[self.i + self.a];

                     ^~~~~~~~~~~~~~~~~~~~~~~~
    error: internal compiler error: no type for expr in fcx 0x7f1af37ecff0

## Meta

    rustc 1.0.0-nightly (f207ecbe0 2015-04-03) (built 2015-04-03)
    binary: rustc
    commit-hash: f207ecbe021e2a81fbff4ea1904b955a156aa340
    commit-date: 2015-04-03
    build-date: 2015-04-03
    host: x86_64-apple-darwin
    release: 1.0.0-nightly

Backtrace:

    stack backtrace:
       1:        0x10eda6987 - sys::backtrace::write::h8872f4f658a62d46iJC
       2:        0x10edd48a3 - panicking::on_panic::h845201cbea1c5a54uxI
       3:        0x10ecf8cee - rt::unwind::begin_unwind_inner::hfc7848f7429ac5d45eI
       4:        0x10e4c91ae - rt::unwind::begin_unwind::h396107918539692450
       5:        0x10e4c99f9 - diagnostic::Handler::bug::h690b37fb3bd82960EsB
       6:        0x10bdca017 - session::Session::bug::hedf08858114489ddFPq
       7:        0x10b320984 - check::FnCtxt<'a, 'tcx>::expr_ty::h5a77c9e464ed1f8c1up
       8:        0x10b33ec8c - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_expr::hbfce55e0efbccd3e1bc
       9:        0x10b33f01a - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_expr::hbfce55e0efbccd3e1bc
      10:        0x10b33f0c0 - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_expr::hbfce55e0efbccd3e1bc
      11:        0x10b33f0c0 - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_expr::hbfce55e0efbccd3e1bc
      12:        0x10b3fd26b - check::check_bare_fn::hcbfa2ceb51ac809fvPn
      13:        0x10b402cc7 - check::check_method_body::h97455aeaff919321lno
      14:        0x10b3fa22f - check::check_item::hcd4af901dd683671g8n
      15:        0x10b4d2746 - check_crate::closure.36252
      16:        0x10b4ccd17 - check_crate::h34c23998ac3af75d1oC
      17:        0x10b1ec2e5 - driver::phase_3_run_analysis_passes::h1e90d1b6a6af8247gGa
      18:        0x10b1d0a15 - driver::compile_input::h43156fddb0e7acceQba
      19:        0x10b28e985 - run_compiler::hf5bcc2a2a9004c41S4b
      20:        0x10b28c152 - boxed::F.FnBox<A>::call_box::h9818158584254676665
      21:        0x10b28b647 - rt::unwind::try::try_fn::h13069897533439949939
      22:        0x10ee5ebe8 - rust_try_inner
      23:        0x10ee5ebd5 - rust_try
      24:        0x10b28b93a - boxed::F.FnBox<A>::call_box::h16467879214397932316
      25:        0x10edbdd8d - sys::thread::create::thread_start::h81aa05d82aaf9eebbeH
      26:     0x7fff875e1267 - _pthread_body
      27:     0x7fff875e11e4 - _pthread_start

**Comment by faern** [comment]
Might be related to and/or same bug as: #24054

**Comment by pmarcelll** [comment]
I can't reproduce it with `rustc 1.2.0-nightly (20d23d8e5 2015-06-18)`.

**Comment by alexcrichton** [comment]
Agreed!
