### ISSUE TITLE
Improve core::convert documentation.

### ISSUE THREAD

**Issue by TimNN** [rust-lang/rust#24107]
The `core::convert` documentation is currently very minimal, especially with regard to Into / From and the difference between the two (ie. when to use which (implement From if possible, use Into in bounds)) and their relationship (Into is implemented for anything implementing From).

Also explain why there are two traits instead of one (coherence).

P.S.: the parts in parenthesis are based on my current understanding of the situation, which may or may not be correct.

**Comment by steveklabnik** [comment]
I generally don't keep issues like this open, but I'll try to just knock this one out soon.

(I haven't gone over this part of the stdlib yet, so it's going to be minimal)

**Comment by TimNN** [comment]
Then feel free to close it :smile: I just wanted to ensure that the documentation is improved at some point, because right now it's missing some more or less important points as mentioned above.

**Comment by steveklabnik** [comment]
Cool. :+1:  Thanks again for opening, I'd rather hear too much than not enough.

**Comment by TimNN** [comment]
Thats what I thought!
