### ISSUE TITLE
Make it easier to not download docs at all.

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#24117]
The 'rust' package includes docs, which take up a bunch of room, slowing the download. Some people don't want docs, and downloading is a waste.

Problem here is that it's now impossible for tools like rustup/multirust to determine which version of cargo to pair with each revision of rust. Secondary problem is that the archive date for rustc/cargo packages may be different from the archive date of the rust package, so one may not get the toolchain they were expecting.

One possible (probably easiest) solution is to add an 'online' installer, that doesn't actually include the bins, but knows where the components live. This can be added to rust-installer.

cc https://github.com/brson/multirust/issues/33

**Comment by nagisa** [comment]
gzipped documentation takes up only about 7MB of the package. With xzip (see https://github.com/rust-lang/rust/issues/21724) it is an essentially free 3MB. Might not be worth having separate doc-less artefacts.

**Comment by steveklabnik** [comment]
Triage: no change.

Personal note: as @nagisa says, it's very small, and offline docs are quite useful. Lots of people ask about "how do i install the docs locally" on IRC, I would prefer to just keep them.

**Comment by nagisa** [comment]
I think this is essentially resolved. We distribute `rustc`, `rust-std` and `rust-docs` packages, which in most cases should be preferable to the one-big-bundle packages anyway.

**Comment by brson** [comment]
With the `rustup component` subcommand we can make the docs an optional package in the manifests.

**Comment by japaric** [comment]
[Rust documentation is now optional and opt-in when installing via rustup](https://users.rust-lang.org/t/psa-rust-documentation-is-now-optional-and-opt-in-when-installing-via-rustup/8072/1)

**Comment by alexcrichton** [comment]
Closing due to @japaric's last comment
