### ISSUE TITLE
RangeFrom<u8> stops at 254

### ISSUE THREAD

**Issue by phaylon** [rust-lang/rust#24119]
I tried printing all valid `u8`s by doing

    for n in 0u8.. {
        println!("{}", n);
    }

and was surprised to find it only printed up to 254.

I'm unsure if this is supposed to be this way (`range_inclusive` can be used). If so, I'd propose adding this to the Iterators/Ranges section of the book.

**Comment by 14427** [comment]
The problem is the next method of RangeFrom:

```rust
fn next(&mut self) -> Option<A> {
    self.start.step(&A::one()).map(|mut n| {
        mem::swap(&mut n, &mut self.start);
        n
    })
}
```

It returns the previous value, then updates itself to store the next one. The value 255 ends up being the value that represents a "done" state, so it can't return it.

I can't think of any solution that doesn't involve adding a `done` flag to RangeFrom.

**Comment by Stebalien** [comment]
Or impl IntoIter instead of Iterator (and use a helper struct to keep track of the range).

**Comment by rprichard** [comment]
Seems similar to #23635.

**Comment by AaronFriel** [comment]
Question: What is the origin of this Rust behavior, or what is its justification? 

It behaves differently from similar syntax in Haskell, Swift, and Go, so I'm wondering if it's fruitful to have behavior different from peer languages (in trying to attract people away from languages where syntax like this does not exist.)

**Comment by steveklabnik** [comment]
Ruby has both exclusive and inclusive ranges

```
steve@warmasteve@warmachine:~/src/rust$ irb
irb(main):001:0> (1..3).to_a
=> [1, 2, 3]
irb(main):002:0> (1...3).to_a
=> [1, 2]
chine:~/src/rust$ irb
irb(main):001:0> (1..3).to_a
=> [1, 2, 3]
irb(main):002:0> (1...3).to_a
=> [1, 2]

```

**Comment by tsion** [comment]
The origin is related to the for-loop idiom in C. `for (int i = a; i < b; ++i)` corresponds to the `a..b` range. It has some nice properties such as how it iterates over exactly `b - a` elements, whereas an inclusive range does `b - a + 1` and would require you to say, for example, `0..v.len()-1` for the indices of a vector if `..` were inclusive.

Essentially, it seems like the exclusive behaviour is useful more often than inclusive in a systems language.

**Comment by Gankro** [comment]
Exclusive behaviour is also a leaner implementation. For inclusive behaviour you need some kind of flag for "now yield the inclusive element". This issue is an exact example of why: How do you statefully write an iterator from `0` to `u8::MAX`, inclusive?

**Comment by aturon** [comment]
cc https://github.com/rust-lang/rust/pull/24120, which adjusts this behavior by triggering an overflow on non-wrapped-arithmetic types; it makes the semantics equivalent to repeatedly updating `n = n + 1`.

**Comment by azar77** [comment]
> cc #24120, which adjusts this behavior by triggering an overflow on non-wrapped-arithmetic types; it makes the semantics equivalent to repeatedly updating n = n + 1.

so @aturon, just to be clear, with the above PR merged, `(0u8..).last()` now panics. Is this the intended behavior?
