### ISSUE TITLE
Trait objects are not properly explained 

### ISSUE THREAD

**Issue by maximih** [rust-lang/rust#24128]
The book [mentions] (http://doc.rust-lang.org/1.0.0-beta/book/associated-types.html#trait-objects-with-associated-types
) trait objects without properly explaining them:

```
There’s one more bit of syntax we should talk about: trait objects. If you try to create a trait object from an associated type, like this:
...
You’ll get two errors: ..
```

I would like to know what a trait object is and what is it useful for, before learning how to define one.

**Comment by steveklabnik** [comment]
trait objects are explained in the 'dynamic and static dispatch' chapter http://doc.rust-lang.org/nightly/book/static-and-dynamic-dispatch.html

**Comment by maximih** [comment]
Great, thanks. 

I guess it would add some value to add a link to the `Dynamic and Static Dispatch` chapter in the `Associated Types` chapter as the the later comes first in the book.

**Comment by steveklabnik** [comment]
Yeah, I wouldn't be opposed to doing so. I'd do it right now, but I'm about to change the TOC in general, so the links would just grow stale. Sorry about that!

**Comment by steveklabnik** [comment]
(and when i do the editing pass, i'm going to do a better job of these kinds of links)
