### ISSUE TITLE
Source headers point to wrong copyright file

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#24122]
Looks like this.

```
// Copyright 2013-2014 The Rust Project Developers. See the COPYRIGHT
// file at the top-level directory of this distribution and at
// http://rust-lang.org/COPYRIGHT.
```

'http://rust-lang.org/COPYRIGHT' does not and has not ever existed.

Best just to fix this with a redirect to the proper file on `www.` if we can.

**Comment by remram44** [comment]
It seems to redirect now -- close?

**Comment by alexcrichton** [comment]
Indeed!
