### ISSUE TITLE
Wrong example about pointers in documentation

### ISSUE THREAD

**Issue by kless** [rust-lang/rust#24127]
http://doc.rust-lang.org/1.0.0-beta/book/pointers.html
The book claims that the next code will give an error:
```
fn main() {
    let x = 5;
    let y = 8;
    let z = &y;

    println!("{}", x + z);
}
```
Looks like Add has been implemented for <pointer> + <value> and vice versa on the primitives, so that example is wrong now

**Comment by steveklabnik** [comment]
This chapter has since disappeared, solving the issue.
