### ISSUE TITLE
Compiler Error on impl of a trait

### ISSUE THREAD

**Issue by olynch** [rust-lang/rust#24134]
I'm getting a compiler panic while trying to compile https://github.com/iron/router.
Notice: I did not write this code, so it may just be outdated for the current version of Rust, however I thought I should do my due diligence and report the bug.

Full Error report:
   Compiling router v0.0.9 (file:///home/olynch/git/router)
src/router.rs:158:1: 158:45 error: internal compiler error: coherence failed to report ambiguity: cannot locate the impl of the trait `core::marker::MarkerTrait` for the type `iron::middleware::Handler`
src/router.rs:158 impl Key for Router { type Value = Params; }
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:130

stack backtrace:
   1:     0x7fb982541818 - sys::backtrace::write::h4618bbda30a2c1fakHC
   2:     0x7fb98256cbe7 - panicking::on_panic::h94b32ff0a2406463uUI
   3:     0x7fb9824a48f3 - rt::unwind::begin_unwind_inner::h310b6bce2d1d1820CzI
   4:     0x7fb97f84bf1d - rt::unwind::begin_unwind::h15255259843176184093
   5:     0x7fb97f84bec3 - diagnostic::SpanHandler::span_bug::he0c1a59febe6c207YmB
   6:     0x7fb980411fbd - middle::traits::error_reporting::report_fulfillment_error::h361f4d21db110ed2FQN
   7:     0x7fb980290121 - middle::traits::error_reporting::report_fulfillment_errors::h1a0f8aa12029694cVPN
   8:     0x7fb98118753c - check::vtable::select_all_fcx_obligations_or_error::haf7db39d8950f48dX1b
   9:     0x7fb9812112d9 - check::wf::CheckTypeWellFormedVisitor<'ccx, 'tcx>::check_item_well_formed::h857600b69cfccd2amWk
  10:     0x7fb981219aa2 - visit::walk_item::h16647639657954483846
  11:     0x7fb981313e19 - check_crate::closure.36364
  12:     0x7fb98130e3c3 - check_crate::hda9802680caa3ff01oC
  13:     0x7fb982bc249d - driver::phase_3_run_analysis_passes::h360d9d4448a0da27gGa
  14:     0x7fb982ba62f5 - driver::compile_input::h16213dd19660ff98Qba
  15:     0x7fb982c5da05 - run_compiler::h2a37c69935ac5f41S4b
  16:     0x7fb982c5b31d - boxed::F.FnBox<A>::call_box::h5013090055299594809
  17:     0x7fb982c5a859 - rt::unwind::try::try_fn::h6394874154857801728
  18:     0x7fb9825e9398 - rust_try_inner
  19:     0x7fb9825e9385 - rust_try
  20:     0x7fb982c5ab2b - boxed::F.FnBox<A>::call_box::h8372456613525927705
  21:     0x7fb982557bd1 - sys::thread::create::thread_start::h0a2c84bef4c472f7MuH
  22:     0x7fb97c32b181 - start_thread
  23:     0x7fb98210747c - __clone
  24:                0x0 - <unknown>

Could not compile `router`.

## Meta

`rustc --version --verbose`:
rustc 1.0.0-nightly (be9bd7c93 2015-04-05) (built 2015-04-06)
binary: rustc
commit-hash: be9bd7c93a53fe554a359e60c5f78991fb783eed
commit-date: 2015-04-05
build-date: 2015-04-06
host: x86_64-unknown-linux-gnu
release: 1.0.0-nightly

**Comment by gsingh93** [comment]
This should have been fixed here: https://github.com/rust-lang/rust/pull/24056

You'll have to wait for the next nightly.

**Comment by gsingh93** [comment]
Try it with the latest nightly, this should be fixed.

**Comment by Munksgaard** [comment]
Indeed, this compiles with `rustc 1.1.0-dev (30a42faa1 2015-05-13) (built 2015-05-13)`. 
Should we close it @steveklabnik ?

**Comment by olynch** [comment]
It now compiles! Issue closed.
