### ISSUE TITLE
`trait Foo {}` produces confusing error about `Self`

### ISSUE THREAD

**Issue by kballard** [rust-lang/rust#24131]
Trying to define an empty trait:

```rust
trait Foo {}
```

produces a confusing message about `Self`:

```
unnamed.rs:1:1: 1:13 error: parameter `Self` is never used
unnamed.rs:1 trait Foo {}
             ^~~~~~~~~~~~
unnamed.rs:1:13: 1:13 help: consider removing `Self` or using a marker such as `core::marker::PhantomFn`
error: aborting due to previous error
```

It appears that the compiler is internally treating the trait as though it had a type parameter defined called `Self`, and then complaining about the parameter being unused. But from the user's perspective there is no such parameter, and the suggestion to remove it is nonsense. The error message should be adjusted to recognize when it's complaining about `Self` and to explain itself better.

**Comment by rprichard** [comment]
Duplicate of #22598.

I agree that the diagnostic is confusing.

**Comment by kballard** [comment]
You're right, that ticket does cover this case.
