### ISSUE TITLE
Broken link in http://doc.rust-lang.org/nightly/book/hello-world.html

### ISSUE THREAD

**Issue by xfq** [rust-lang/rust#24146]
In https://github.com/rust-lang/rust/blame/336dd6c8f03db7d70731da18d89040b1cb7d4765/src/doc/trpl/hello-world.md#L92 , there is a link to `src/etc/CONFIGS.md`, but in http://doc.rust-lang.org/nightly/book/hello-world.html , the link becomes `src/etc/CONFIGS.html`, which doesn't exist (404).

I've searched for other 404 issues (such as #23735), but IMHO this one is different so I create a new issue here.

**Comment by mitaa** [comment]
I've noticed that too but there's #22900 already open for this.

**Comment by steveklabnik** [comment]
yes, this is a duplicate. Thanks for reporting though!
