### ISSUE TITLE
aarch64-apple-ios: Returning structs by value in extern "C" functions uses wrong calling convention

### ISSUE THREAD

**Issue by jgallagher** [rust-lang/rust#24154]
Creating an extern C function like this:

```rust
#[repr(C)]
pub struct Point {
    x: f32,
    y: f32,
}

#[no_mangle]
pub extern "C" fn get_point() -> Point {
    return Point{x: 10.0, y: 20.0}
}
```

and compiling using `cargo build --target aarch64-apple-ios --release`, the assembly produced for `get_point` is:

```
_get_point:
0000000000000000                movz    x0, #16800, lsl #48
0000000000000004                movk    x0, #16672, lsl #16
0000000000000008                ret
```

My ARM assembly is a little rusty, but I believe this is expecting the caller to pass in the address of a `Point` in `x0`, and then the function fills it in.

However, this C code, which should be equivalent:

```C
struct point {
    float x;
    float y;
};

struct point get_point(void) {
    return (struct point){10.0, 20.0};
}
```

compiles to the following assembly in Xcode 6.2 targeting arm64:

```
0x1000fec74:  fmov   s0, #1.000000e+01
0x1000fec78:  fmov   s1, #2.000000e+01
0x1000fec7c:  ret
```

which is returning the two struct fields in the SIMD registers.

Is this an issue of how aarch64 is defined or configured, maybe?

**Comment by jgallagher** [comment]
Reading the [calling conventions for AArch64](http://infocenter.arm.com/help/topic/com.arm.doc.ihi0055b/IHI0055B_aapcs64.pdf), I believe the Xcode version is correct and Rust is incorrect. According to section 5.4 rule C.2, since `Point` is an HFA (Homogenous Floating-point Aggregates, section 4.3.5.1), its fields should be passed in SIMD registers. According to the first bullet in section 5.5, a returned `Point` should follow the same convention.

**Comment by jgallagher** [comment]
Sorry, one last note. It looks like writing Rust code to take a struct by value has the same problem. This rust function:

```rust
#[no_mangle]
pub extern "C" fn sum_point(p: Point) -> f32 {
    p.x + p.y
}
```

compiles to this assembly:

```
000000000000000c                fmov    s0, w0
0000000000000010                lsr     x8, x0, #32
0000000000000014                fmov    s1, w8
0000000000000018                fadd    s0, s0, s1
000000000000001c                ret
```

but the equivalent C function compiled in Xcode produces:

```
0x10001ac4c:  fadd   s0, s0, s1
0x10001ac50:  ret
```

**Comment by vhbit** [comment]
@steveklabnik I'd say 'A-iOS' is incorrect label as this is related to Aarch64 in general and can happen on Android too.

**Comment by pnkfelix** [comment]
@vhbit (to be fair i suspect @steveklabnik was working from the description in the title)

**Comment by vhbit** [comment]
@steveklabnik, may I ask you also to cc me on issues which you mark with iOS label - till today I didn't know it exists at all as I don't track issues.

**Comment by vhbit** [comment]
@pnkfelix I didn't mean to offense anyone, I apologize if that sounded like that - my intention was just to clarify issue

**Comment by steveklabnik** [comment]
Yeah, I just try to ensure each issue has _at least_ one label, but I'm not always perfect with them.

@vhbit I can try to remember :)

**Comment by pnkfelix** [comment]
@steveklabnik do you know if there is a way to utilize the github's API so that someone could register to receive notices of such labels?

**Comment by steveklabnik** [comment]
Not off the top of my head. https://developer.github.com/v3/issues/labels/ could probably make it work, I'd bet.
