### ISSUE TITLE
`&mut [T;N] as *mut T` does not compile, but `&[T;N] as *const T` does

### ISSUE THREAD

**Issue by Jexell** [rust-lang/rust#24151]
``` rust
unsafe {
    let my_num: &[i32; 2] = &[10, 20];
    let my_num: *const i32 = my_num as *const i32; // This works.
    println!("{}", *my_num.offset(1));
}
```

``` rust
unsafe {
    let my_num: &mut [i32; 2] = &mut [10, 20];
    // error: mismatched types:
    //  expected `*mut i32`,
    //         found `&mut [i32; 2]`
    let my_num: *mut i32 = my_num as *mut i32;
    println!("{}", *my_num.offset(1));
}
```

**Comment by alexcrichton** [comment]
cc @nrc, is this a coercion that's expected to work?

**Comment by alexcrichton** [comment]
triage: I-nominated

**Comment by nrc** [comment]
The first cast is from `&[i32; 2]` to `*const i32`, the second is from `&mut [i32; 2]` to `*mut i32`. I'm not actually sure if this is meant to work, I guess it should. The intention here is to give a way to treat arrays like C-arrays and get a pointer to the start of the array. It seems that if the array is mutable, then the pointer should be too.

I recommend this is P-low - it is backwards compatible, rare, and just a bug by omission, really. The fix should be pretty easy though.

**Comment by alexcrichton** [comment]
Ah I wasn't sure if this was intended, if it's actually intended then I don't mind removing the nomination as well!

**Comment by nikomatsakis** [comment]
I'm not sure how intended this is, but it doesn't seem too harmful. ;)

**Comment by pnkfelix** [comment]
P-low, (perhaps "just a bug", perhaps a minor feature.)

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by osa1** [comment]
This still happens today (with e32f372c420), but the error message is slightly different:

```
error[E0606]: casting `&mut [i32; 2]` as `*mut i32` is invalid
  --> test.rs:13:32
   |
13 |         let my_num: *mut i32 = my_num as *mut i32;
   |                                ^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

#80258 is another `*mut`-related issue.
