### ISSUE TITLE
Feature request: publish and maintain a copy of libarena on crates.io

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#24153]
See https://www.reddit.com/r/rust/comments/31qhyu/using_arena_in_beta/ . I’ve also wanted this myself.

Removing usage of unstable features would be tricky, but hopefully not impossible. For `alloc` in particular, a work-around I’ve used is:

```rust
fn allocate<T>(n: usize) -> *mut T {
    let vec = Vec::with_capacity(n);
    let ptr = vec.as_mut_ptr();
    unsafe { std::mem::forget(vec) };
    ptr
}

fn deallocate<T>(ptr: *mut T, n: usize) {
    Vec::from_raw_parts(ptr, 0, n)  // let it drop
}
```

**Comment by SimonSapin** [comment]
I took a stab at this. The reflection-based `Arena` goes fairly deep into compiler implementation details (transmuting `TraitObject.vtable`…), so I wouldn’t even try to port it to stable Rust.

As to `TypedArena`, porting it is more plausible but not straight-forward either since it uses not only `allocate` mentioned about but also `std::intrinsics::needs_drop`. Maybe that can be worked around with `Vec::from_raw_parts` with a non-zero length, but that would involve moving the chunk header outside of the data allocation. Unless we can just assume everything needs dropping and count on the entire loop being optimized away? That’s what `Vec::drop` seems to be doing…

**Comment by TeXitoi** [comment]
That would be great for the binarytree benchmark on http://benchmarksgame.alioth.debian.org/ (related issue: https://github.com/rust-lang/rfcs/issues/665)

**Comment by SimonSapin** [comment]
I published a rewrite of `TypedArena`: https://crates.io/crates/typed-arena

It runs on beta/stable. It’s probably less efficient, but uses much less unsafe code internally. (It’s based on `Vec<Vec<T>>` where inner vectors never grow beyond their initial capacity, instead of raw pointers and manual drops.)
