### ISSUE TITLE
Unused trait parameter error recommends deprecated PhantomFn

### ISSUE THREAD

**Issue by kballard** [rust-lang/rust#24164]
The error message for a trait with an unused parameter recommends the use of `PhantomFn` even though it's deprecated. It should presumably recommend `PhantomData` instead, and the documentation on `PhantomData` should be updated to include an example of how to use it with a trait.

Example ([play](http://is.gd/capjy1)):

```rust
trait Foo<T> {
    fn foo(&self);
}
```

yields

```
<anon>:1:11: 1:12 error: parameter `T` is never used
<anon>:1 trait Foo<T> {
                   ^
<anon>:1:12: 1:12 help: consider removing `T` or using a marker such as `core::marker::PhantomFn`
error: aborting due to previous error
```

You also get the same error today (suggesting `PhantomFn`) when using a "marker-like" trait with no functions, which is filed as #22598 (it needs a better error message).

**Comment by kballard** [comment]
I admit to being slightly confused as to why `PhantomFn` and `MarkerTrait` are deprecated. This happened in #23938 (Remove variances from traits and deprecate `PhantomFn`/`MarkerTrait`). But `MarkerTrait` is still used as the super trait of the other markers (`Send`, `Sized`, and `Reflect`).

As near as I can tell, without using either of these two deprecated traits, the only way to declare a marker-like trait (e.g. one that doesn't use `Self`) is to use an associated type with `PhantomData`, e.g.

```rust
trait Foo {
    type _phantom = PhantomData<Self>;
}
```

And it's not even clear if this is "correct". #23938 says that traits no longer have variance, so I guess it's ok? But I don't actually know.

/cc @nikomatsakis

**Comment by apasel422** [comment]
What version of `rustc` are you using? The following compiles successfully with `rustc 1.0.0-nightly (083b8a404 2015-04-05) (built 2015-04-05)
```rust
trait Foo<T> {
    fn foo(&self);
}

fn main() {}
```

**Comment by kballard** [comment]
Huh, you're right. I apparently had the beta on my system (it seems rustup.sh started installing that by default), and I'm not sure what version play.rust-lang.org is using right now.

Anyway, it seems `PhantomFn` stopped being recommended as of #23938.
