### ISSUE TITLE
`extern "C"` functions don't implement `Clone`

### ISSUE THREAD

**Issue by bfops** [rust-lang/rust#24161]
This should compile. It used to compile without deriving `Clone`, and it currently compiles if `extern "C"` is removed.

    #[derive(Copy, Clone)]
    struct Functions {
      pub foo: extern "C" fn(u32) -> u32,
    }

    fn main() {
    }

**Comment by kballard** [comment]
`Clone` also needs to be implemented for `unsafe fn`. Right now it's only implemented for `fn`s of 0–8 arguments.

**Comment by kballard** [comment]
Looking at the [source](https://github.com/rust-lang/rust/blob/master/src/libcore/clone.rs#L95) it's actually explicitly implemented on `extern "Rust" fn`.

**Comment by bfops** [comment]
Thanks!
