### ISSUE TITLE
FuzzyNum example in std::cmp documentation seems to violate PartialEq requirements

### ISSUE THREAD

**Issue by niconii** [rust-lang/rust#24173]
In the [documentation for `PartialEq`](https://doc.rust-lang.org/std/cmp/trait.PartialEq.html), it mentions that the equality must be symmetric (`a == b` implies `b == a`) and transitive (`a == b` and `b == c` implies `a == c`) to satisfy the partial equivalence relation.

However, in [`std::cmp`'s documentation](https://doc.rust-lang.org/std/cmp/), it gives a `PartialEq` example for a `FuzzyNum` struct, but this does not appear to be transitive. For example, the fuzzy numbers 20 and 24 are equal, 24 and 28 are equal, but 20 and 28 are not equal.

Is there something I'm missing here, or should the example be rewritten?

**Comment by steveklabnik** [comment]
I'm pretty sure it's just a sloppy example.

**Comment by sfackler** [comment]
A range type would be a better thing to use as an example as it would actually be partially ordered.

**Comment by pnkfelix** [comment]
(Note this is about partial eq, not ord.)

Range types may work still.  Or we could adapt the kernels example from the linked Wikipedia article.
