### ISSUE TITLE
rustdoc: Self: Sized bounds in different crates are pruned

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#24183]
For example [`Iterator::map`](http://doc.rust-lang.org/std/iter/trait.Iterator.html#method.map) should have a `Self: Sized` bound, but we're a little too aggressive about pruning out the `Sized` bounds.

For comparison [`core::iter::Iterator::map`](http://doc.rust-lang.org/core/iter/trait.Iterator.html#method.map) does indeed have the bound.

**Comment by apasel422** [comment]
This also applies to `Sized` bounds on traits.

**Comment by crumblingstatue** [comment]
This prompted a question on IRC about whether `Clone` requires `Sized`, because the `Sized` bound is not visible in the libstd documentation. It *is* visible in the libcore docs though.

**Comment by jonas-schievink** [comment]
Triage: This still happens

**Comment by guswynn** [comment]
This actually ended up biting me today, is there a plan to handle this? I could help implement if I get pointers

**Comment by jyn514** [comment]
@guillaumegomez https://github.com/rust-lang/rust/pull/78181 did not fix this - it now shows `impl !Sized for dyn Trait`, which is nice, but it doesn't show `Self: Sized` bounds on traits. For traits it does matter because the default is `?Sized`.

**Comment by jyn514** [comment]
> This actually ended up biting me today, is there a plan to handle this? I could help implement if I get pointers

@guswynn I would start by finding out why this is different between local crates and cross-crate re-exports. I expect `impl Clean<Item> for hir::TraitItem<'_>` is behaving differently from `impl Clean<Type> for (ty::TraitRef<'_>, &[TypeBinding]) `.

**Comment by tmandry** [comment]
Ah, I also hit this today when looking at [`Clone`](https://doc.rust-lang.org/stable/std/clone/trait.Clone.html). Kudos to whoever can figure this one out :)
