### ISSUE TITLE
Can't borrow part of a struct

### ISSUE THREAD

**Issue by Undeterminant** [rust-lang/rust#24187]
Seems like a rather convoluted example, but borrowing in member functions is... weird.

    struct DoesNotCopy(usize);
    
    struct Broken {
      x: usize,
      y: DoesNotCopy
    }
    
    impl Broken {
      fn decompose(&self) -> (usize, &DoesNotCopy) {
        (self.x, &self.y)
      }
    
      fn do_stuff(&mut self) -> (usize, &Foo) {
        let x = self.decompose();
        self.x = 0; // error: cannot assign to `self.x` because it is borrowed
        x
      }
    }

My intuition says that this should be okay. If I copy out the part that I'm going to modify, and take an immutable reference to one part of the struct, I should be able to modify the rest without issue. If I inline the contents of the function where it's called, it works, i.e. `let x = (self.x, &self.y)` is fine.

**Comment by bombless** [comment]
shorter version:
```rust
fn main() {
    let ref mut x = Box::new(42);
    let ref y = x;
    **x = 0; // error: cannot assign to `**x` because it is borrowed
}
```
I believe this is intended.

As your example, let's see the caller part:
```
fn foo(v: &mut Broken) {
    v.x = 42;
    v.do_stuff(); // we don't use the return value here
    // now where is the chance to destruct 42?
}
```
So if we don't reject the `self.x = 0;` line, we never have a chance to detect the leak.
In short, the `self.x = 0;` line break basic rule of ownership system.

**Comment by pnkfelix** [comment]
The signature for `fn decompose` does not encode borrowing "part of" `self`.  So when compiling  client code calling `decompose`, we must assume all of `self` is borrowed.

**Comment by bombless** [comment]
Hmm I was wrong.
We can loose the rule here, if it turns out to be important, I guess.

**Comment by oli-obk** [comment]
> The signature for fn decompose does not encode borrowing "part of" self. So when compiling client code calling decompose, we must assume all of self is borrowed.

is it currently possible in rust to specify a partial borrow?

**Comment by pnkfelix** [comment]
@oli-obk not today, no.  I think there may have been discussions of such a feature in the past, but it is not an immediate goal.

**Comment by pnkfelix** [comment]
(There may be a way to hack in a smart pointer that carries as many lifetimes as necessary, as a way to express the desired API here, but I think the implementation of such a smart pointer would need to resort to unsafe code... )

**Comment by oli-obk** [comment]
thanks, so I guess this is more of a stackoverflow question or rfc-issue than a rust-issue:

@Undeterminant: you can implement what you want along those lines:

```rust
impl Broken {
    fn decompose(&mut self) -> (&mut usize, &DoesNotCopy) {
        (&mut self.x, &self.y)
    }

    fn do_stuff(&mut self) -> (usize, &DoesNotCopy) {
        let (ref mut x, ref y) = self.decompose();
        (std::mem::replace(x, 0), y)
    }
}
```

[Playpen][1]

  [1]: http://is.gd/Gvx9ZD

**Comment by bombless** [comment]
Or more close: http://is.gd/xfPhly
```rust
struct DoesNotCopy(usize);

struct Broken {
    x: usize,
    y: DoesNotCopy
}

impl Broken {
    fn decompose(&mut self) -> (usize, &DoesNotCopy) {
        (self.x, &self.y)
    }

    fn do_stuff(&mut self) -> (usize, &DoesNotCopy) {
        let (ref mut x, ref y) = self.decompose();
        (std::mem::replace(x, 0), y)
    }
}
```
Nice job!

**Comment by oli-obk** [comment]
that won't work. you just modified a variable that is local to the do_stuff function.

**Comment by Undeterminant** [comment]
As far as I know, mem::replace requires a mutable borrow, which wouldn't be possible in that case. You can coerce a ptr::write without ownership but it just feels wrong.

**Comment by oli-obk** [comment]
Without seeing your code, we can't be of much help. Maybe make a post on stackoverflow?

**Comment by Undeterminant** [comment]
I'll post one later. For now, it seems that this isn't a compiler bug, so, I'll close it.

**Comment by Undeterminant** [comment]
After looking into this more, it seems that it's just clunky to borrow out part of a struct as mutable without borrowing the rest. I don't see an easy way to fix that, though.

I don't think that an SO question is necessary; I'll just deal for now. :)

**Comment by nielsle** [comment]
Just for reference. The following compiles now
~~~
struct DoesNotCopy(usize);

struct Broken {
    x: usize,
    y: DoesNotCopy,
}

impl Broken {
    fn decompose(&mut self) -> (usize, &DoesNotCopy) {
        let &mut Broken {mut x, ref mut y} = self;
        (x, y)
    }

    fn do_stuff(&mut self) -> (usize, &DoesNotCopy) {
        let (mut x, mut y) = self.decompose();
        x = 0;
        (x, y)
    }
}
~~~
https://gist.github.com/38b7e06f15ad75ac3da66521dc7baa29
