### ISSUE TITLE
Collections or_insert_with Option<T>

### ISSUE THREAD

**Issue by james-darkfox** [rust-lang/rust#24196]
After looking at the new or_insert/_with/ functions; I noticed that the _with function doesn't allow the child function to decide if the insert will occur.

Here I request for an optional version that allows the function to make that decision.

It doesn't need to do the add manually; instead it is perfectly clean to use Option's `Some(inserted_value)` or `None`.

The following is an example using this method against the rustbyexample.com HashMap example.
http://is.gd/myihhV

```rust
pub fn or_maybe_insert_with<F: FnOnce() -> V>(self, default: F) -> Option<&'a mut V> {
    match self {
        Occupied(entry) => entry.into_mut(),
        Vacant(entry) => match default() {
            Some(val) => Some(entry.insert(val)),
            _         => None,
        },
    }
}
```

Example usage: early return when the value neither already exists and wasn't added.

```rust
let value = match map.entry(key).or_maybe_insert_with(||{ Some("insert me!") }) {
    Some(v) => v,
    _       => return, // early return
}
```

**Comment by kballard** [comment]
Is this worth complicating the API? `or_insert`/`or_insert_with` are meant to be convenient functions for common operations. If you need something more complicated you're free to operate on the `OccupiedEntry` / `VacantEntry` types directly.

**Comment by reem** [comment]
I agree with @kballard. We don't want to end up back at the old `find_or_insert_with` mess.

**Comment by james-darkfox** [comment]
Okay; manual it seems for everyone else too. I still expect this condition to be more common and worthy of an API helper.

**Comment by james-darkfox** [comment]
Concluded to not be common and no changes required.

**Comment by stevenroose** [comment]
Hmm, coming here because of this exact feature. In 2015 the API could have been a breaking change and just take an option always. Now I think a `or_maybe_insert_with(FnOnce() -> Option<V>)` would still be worthwhile. It's a niche part of the API anyway, so I don't think it can be too cluttered.

Anyway going for manual right now :)
