### ISSUE TITLE
On empty iterator min/max panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by estin** [rust-lang/rust#24202]
rustc 1.0.0-nightly (d9146bf8b 2015-04-07) (built 2015-04-08)

```
fn main() {
    let a: Vec<usize> = Vec::new();
    println!("min {}", a.iter().min().unwrap());
}
```

thread '\<main\>' panicked at 'called `Option::unwrap()` on a `None` value'

**Comment by kballard** [comment]
This is correct behavior. Calling `.min()` or `.max()` on an iterator that yields no elements returns `None` (this is why the method has an `Option` return type). Calling `.unwrap()` on `None` panics.

I'm closing this report as there appears to be no bug here. If you have any questions, feel free to comment on the ticket, or reopen it if you think there's still an issue here.
