### ISSUE TITLE
Stability attribute should not be displayed as just color

### ISSUE THREAD

**Issue by rodrigorc** [rust-lang/rust#24201]
In rustdoc documentation, the stability attribute is shown as a little vertical bar to the left of the item. In the main window of crates, types, etc. it is also shown as text in the header of the window. But some items, as `impl` member functions do not have a proper window, so the stability is never seen in plain text.

It is a well known usability rule that relevant information should never be revealed with color only, as the sensibility to color [varies highly between individuals](http://stackoverflow.com/questions/29481065/why-is-vecresize-an-unstable-function/).

I would like stability to be shown as a letter, icon or something other than color alone, so that color-blind people will see what they are doing.

**Comment by steveklabnik** [comment]
We chose the current colors to be decent for color-blind people, IIRC.

**Comment by killercup** [comment]
The colored bars have tooltips (like "stable" or "deprecated").

This reminds me: many stability attributes contain further information that is only "visible" in that little tooltip if you hover above that small colored bar – this doesn't work on touch devices. (_rustdoc_ just writes this to the `title` attribute of the `a.stability` element).

Should that information be displayed more prominently? (Might be another issue, sorry of this is too off-topic.)

**Comment by steveklabnik** [comment]
We have an issue for that already, @killercup

**Comment by rodrigorc** [comment]
There are a lot of color-blindness types. Choosing a set of about 5 colors easy to differentiate for everybody is practically impossible.

See for example this image:

![stability](https://cloud.githubusercontent.com/assets/1128630/7052538/797980a2-de2f-11e4-854b-d48219dd0314.png)

I can barely see the difference between the orange and the green ones, unless they are just next to each other. And I'm just slightly color-blind. (The magenta one is fine for me though.)

The problem with the tooltip is double: 1. you cannot see it in touchscreens. 2. You have to move the mouse over it for every function, and there may be a lot of functions to check, if you want to use only stable functions you have to step through all of them.

**Comment by steveklabnik** [comment]
I'm not saying that it's perfect, just trying to add some context.

**Comment by rodrigorc** [comment]
Don't worry, we color-blind people are not very sensitive about this ;-p

However, the rule of not using only color for conveying information stands: any combination other than black / gray / white will be confusing for somebody. And imagine the situation with real blind people and screen readers!

For me adding an icon, or even a simple uppercase letter (S for stable, U for unstable, D deprecated)  would be more than welcomed.

**Comment by killercup** [comment]
I couldn't help but think of icons for this.

state | icon
--- | ---
stable | :smiley:
unstable | :warning:
deprecated | :skull:

**Comment by steveklabnik** [comment]
@killercup that is.... amazing

**Comment by vogon** [comment]
some prior art: developer.mozilla.org uses icons for "deprecated" and "unstable", as well:
![autocapitalize](https://cloud.githubusercontent.com/assets/88932/7052979/e14e00c0-dde6-11e4-9a47-7c0d09c05658.png)
![x-moz-errormessage](https://cloud.githubusercontent.com/assets/88932/7052991/e4d7908a-dde6-11e4-8a85-8bec0f88bb54.png)

**Comment by killercup** [comment]
@steveklabnik, thanks. I was gonna go with :snowflake: for "deprecated", but then stable APIs are kinda frozen…

I'd prefer to use a monochrome icon font, though, using the old colors ;)

**Comment by kballard** [comment]
I like the icons idea. They'd also provide good touch targets for revealing the stability info (which is important for non-touch devices as well; users may not know to expect a tooltip, and you can't copy text from a tooltip).

**Comment by aturon** [comment]
I also really like the idea of icons; I think we should remove the little color blobs altogether. I also think that stable APIs should have no marking (they should be the default), and the icons should go to the right as in the [above comment](https://github.com/rust-lang/rust/issues/24201#issuecomment-91005107). That would help with some other alignment issues as well.

**Comment by rodrigorc** [comment]
@aturon: Agreed. I like the mozilla style best. Profesional and easy to see from a distance.

About the tooltip information, I would keep it as tooltip in content lists, such as members of a crate, but promote it to full paragraph when viewing the details. After all, the reason for unstability is IMO quite important.
