### ISSUE TITLE
Change unwinding line arguments from usize to u32

### ISSUE THREAD

**Issue by rprichard** [rust-lang/rust#24208]
The `file_line` arguments to `std::rt::unwind::begin_unwind` and `std::rt::unwind::begin_unwind_fmt` takes a `&(&str, usize)`.  We changed `line!` to `u32`, so we should also update these two functions to also take a `u32`.

I had noticed this a while ago, but had been putting off fixing them, because it didn't seem time-sensitive.  However, I realized today that these functions are stable, so it's technically a breaking-change.

**Comment by rprichard** [comment]
Also, given the existence of `#[allow_internal_unstable]`, do we really intend these functions to be stable?

**Comment by alexcrichton** [comment]
Oh yay we definitely don't need to! I've opened https://github.com/rust-lang/rust/pull/24212 on this topic.

**Comment by steveklabnik** [comment]
Given that said PR was merged, should this be closed, or not? It's purely internal now, yeah?

**Comment by rprichard** [comment]
Yes, it's purely internal now, so this issue can be closed.
