### ISSUE TITLE
Non-module extern crate is not visible to imports

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#24219]
```
fn main() {
    extern crate core;
    use core::cell;
}
```

Should work but doesn't. Note that it is only imports that seem to be affected, in the above example, using `core` in a path in a type or expression work fine.

**Comment by P1start** [comment]
I think the example in the issue is the intended behaviour, as `use` accepts a global path, while everything else uses a local path by default. `self` normally lets you use a local path in `use`, though, but that [doesn't work either](http://is.gd/wxNGMY), so I guess this is a real bug.

**Comment by sfackler** [comment]
cc #18084

**Comment by nrc** [comment]
So, since use always uses absolute paths, fixing #18084 seems to be the way to resolve this.

**Comment by glaebhoerl** [comment]
See also https://github.com/rust-lang/rfcs/issues/959.
