### ISSUE TITLE
Override Iterator methods when possible in `std`

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#24214]
Now that `Iterator` has re-emerged as a single trait, it's possible to override default methods like `count`, `last` and `nth` for iterators on slices, vectors, and so on. We should audit the applicable iterators and take advantage of overrides when possible.

libcore:

* [x] slice::Iter(Mut): count, last, nth
* [x] slice::Windows: count, last, nth  #27652
* [x] slice::Chunks(Mut): count, last, nth #27652
* [ ] char::{EscapeDefault, EscapeUnicode}: count, last, nth (techically but probably not worth it)
* [ ] str::Bytes: count, last, nth
* [x] iter::Chain: count, last, nth
* [x] iter::Enumerate: count, nth
* [x] iter::Peekable: count, last, nth
* [x] iter::Skip: count, last, next (should call nth), nth
* [x] iter::Take: nth
* [x] iter::Fuse: count, last, nth

**Comment by aturon** [comment]
I'd be happy to mentor work on this bug.

**Comment by djmally** [comment]
I would be interested in working on this.

**Comment by GuillaumeGomez** [comment]
Me too.

**Comment by tamird** [comment]
Also interested in working on this. Anything left to do?

**Comment by djmally** [comment]
@aturon Any word on this?

**Comment by pnkfelix** [comment]
Also, I'm curious if methods like `skip(n)` are required to actually call `next` n tines, or if they are allowed to "jump ahead" on random-access iterators.  (Maybe that sort of trick will have to wait for specialization in the language, to avoid composing that with e.g. a `map` or other potentially side-effectful iterator

**Comment by Stebalien** [comment]
@pnkfelix `skip` can call `nth` on the underlying iterator and the underlying iterator can optimize `nth` if possible.

**Comment by pnkfelix** [comment]
@Stebalien I think that is my point: You say "the underlying iterator can optimize `nth` if possible", but I claim to allow that would require changing the specification of `nth`, which currently is specified as "going through `n` iterations", which I interpret as "calls the `next()` method `n` times" -- a side-effectful iterator chain (e.g. one using `inspect`) can observe the difference between that or jumping ahead `n` steps when given a random-access iterator.

**Comment by aturon** [comment]
Oh dear, I seem to've lost track of this thread, sorry to everyone who was waiting on me to organize things!

I think probably the first place to start is just to get a list of the public iterators in std, which we can turn into a checklist and track assignees for. Part of the work will just be figuring out which cases are actually opportunities for doing better.

Anyone interested in putting such a list together? I'd be glad to help coordinate.

**Comment by aturon** [comment]
(And if no one is in a position to make a list, I can put one together tomorrow.)

**Comment by Stebalien** [comment]
@pnkfelix It doesn't because:
1. Skip can assume that the underlying iterator correctly implements `nth`.
2. Some iterators (e.g. `slice::Iter`) have side-effect-free `next` methods. These iterators can implement optimized `nth` functions.

So `vec![1, 2, 3, 4, 5].iter().skip(2)` can have a constant time skip given an optimized `slice::Iter::nth` method. Unfortunately, as implemented, ranges can't optimize `nth` this way because they are generic.

**Comment by Stebalien** [comment]
Here's core:

* slice::Iter(Mut): count, last, nth
* slice::Windows: count, last, nth
* slice::Chunks(Mut): count, last, nth
* char::{EscapeDefault, EscapeUnicode}: count, last, nth (techically but probably not worth it)
* str::Bytes: count, last, nth
* iter::Chain: count, last, nth
* iter::Enumerate: count, nth
* iter::Peekable: count, last, nth
* iter::Skip: count, last, next (should call nth), nth
* iter::Take: nth
* iter::Fuse: count, last, nth

**Comment by aturon** [comment]
Thanks @Stebalien! I've added this as a checklist to the top of the issue.

Anyone on thread: feel free to let me know if you want to take on a particular module/crate and I can put your name next to the item to "claim" it.

**Comment by wldcordeiro** [comment]
I'm interested in this @aturon would I just fork the repo and work on master or should I make a separate branch like `rust-lang/slice-iter` or something?

**Comment by aturon** [comment]
@wldcordeiro 

It usually works best to fork, and then create a branch in your local copy that tracks the master branch on this repo. We use the "fork and pull" model [here](https://help.github.com/articles/using-pull-requests/).

Once you get cooking, write a comment here to say which modules you're taking so we can avoid overlap. Thanks!

**Comment by Stebalien** [comment]
I have one for `Iter(Mut)`. However, I'm not happy with the performance of nth (see the inline comment). Issue linked above ^.

**Comment by Stebalien** [comment]
To add to the list, `nth` should be overridden in the by_ref iterators (`impl<I: Iterator> Iterator for &(mut) I { .. }`

**Comment by pnkfelix** [comment]
@Stebalien wrote:

> Some iterators (e.g. slice::Iter) have side-effect-free next methods. These iterators can implement optimized nth functions.
> 
> So vec![1, 2, 3, 4, 5].iter().skip(2) can have a constant time skip given an optimized slice::Iter::nth method. Unfortunately, as implemented, ranges can't optimize nth this way because they are generic.

I think I see.  So you are saying `vec![...].iter()` would provide the optimized `nth` (and thus could be used in an optimized fashion by the `skip` method), while `vec![...].iter().map(...)` and `vec![...].iter().inspect(...)` would be forced to fall back to calling `next()` n times, right?

**Comment by Stebalien** [comment]
@pnkfelix Exactly. It should also be possible to optimize methods like any, all, min, max, etc. by avoiding bounds checks but I don't know if it's worth it. However, it probably is worthwhile to optimize those methods for the Bytes/Chars iterators because doing so will allow us to read in large chunks instead of byte-by-byte.

**Comment by aturon** [comment]
Note that in the long run, we'll need full "specialization" in order to optimize chained cases -- so this issue is primarily about the lowest-hanging fruit that we can tackle with today's trait system.

**Comment by Stebalien** [comment]
Additional iterators to consider optimizing:

* path::Iter: last
* path::Components: last
* io::{Bytes, Chars}: count, last, nth, partition, fold, all, any, max, min, max\_by, min\_by, unzip, sum, product
   * Implementing these methods could significantly reduce the number of system calls by reading in as much as possible. Is this worth it or should we just expect users to use a buffered reader?
* env::{Vars, VarsOs, Args, ArgsOs} count, nth, last
  * Calls down to sys::os::{Env, Args}.
* sys::os::{Env, Args} count, nth, last
* vec::IntoIter <s>count</s> (done), nth, last
    * These may not be worth it because we have to drop each element anyways...

**Comment by pnkfelix** [comment]
> * vec::IntoIter <s>count</s> (done), nth, last
>     * These may not be worth it because we have to drop each element anyways...

One can still add a specialized path by inspecting the type for the element; see related discussion on #24280

**Comment by ericye16** [comment]
Are there still things to do for this issue? If there are and they're not assigned I'd like to work on this too.

**Comment by alex-ozdemir** [comment]
I'm planning take care the slice::Windows & slice::Chunks(Mut). Let me know if you're working on this and I should redirect my attention to a different item.

**Comment by ijks** [comment]
Willing to work on str::Bytes. Is it still up for grabs?

**Comment by alex-ozdemir** [comment]
I think you would be safe taking a crack at it :smile:

**Comment by ranma42** [comment]
All of the methods listed in the top comment seem to have been implemented with the exception of those for EscapeDefault and EscapeUnicode. I took an initial stab at them here: https://github.com/ranma42/rust/tree/escape-iters ; if they are desired, I will clean up the code and add proper commit messages.
It might be a good idea to also audit iterators outside of libcore and add them to the to-do list.

**Comment by Ticki** [comment]
`EscapeDefault` can be checked. My PR was merged.

**Comment by ijks** [comment]
Just noticed `str::Bytes` can be checked as well.

**Comment by brson** [comment]
From comments it appears this is done. Thanks all.
