### ISSUE TITLE
sort and sort_by not in API docs

### ISSUE THREAD

**Issue by palango** [rust-lang/rust#24229]
I tried to find docs for `sort` and `sort_by` today. However they don't show up in the API docs for neither beta nor nightly.
It is however included in the source.

**Comment by alexcrichton** [comment]
They are [actually there](http://doc.rust-lang.org/std/primitive.slice.html#method.sort_by), they just [don't show up in the search index](https://github.com/rust-lang/rust/issues/23511), so closing as a dupe of #23511.

Thanks for the issue though!
