### ISSUE TITLE
On windows, use SetDllDirectory when dynamically linking libraries.

### ISSUE THREAD

**Issue by LaylConway** [rust-lang/rust#24226]
Currently results from cargo that need a .DLL on windows aren't runable until you copy over the .DLLs from their out directories to the folder the .exe is in. Making the .exe use SetDllDirectory before trying to load the DLLs should fix this without having to move the DLLs in the build result.

MSDN Reference for SetDllDirectory:
https://msdn.microsoft.com/en-us/library/ms686203(VS.85).aspx

**Comment by nagisa** [comment]
> Making the .exe use SetDllDirectory before trying to load the DLLs should fix this without having to move the DLLs in the build result.

I fear Windows might do the linking before the entry point is executed and we get a chance to call the function.

Does `cargo run` not work here?

**Comment by LaylConway** [comment]
`cargo run` does work but I can't ship cargo with the software

**Comment by Diggsey** [comment]
Windows loads DLLs lazily - as long as the call to SetDllDirectory happens before the first call into a DLL, it should work fine.

**Comment by steveklabnik** [comment]
This sounds like a Cargo issue, please open it up over there: https://github.com/rust-lang/cargo/issues/new

thanks!
