### ISSUE TITLE
Clarify in the book when rustdoc tests are run

### ISSUE THREAD

**Issue by contradictioned** [rust-lang/rust#24228]
The new [chapter on documentation](http://doc.rust-lang.org/1.0.0-beta/book/documentation.html#running-documentation-tests) is great, but in my opinion the documentation tests are still missleading.

When you

1. create a crate with `cargo new --bin mycrate`
2. write a doc test
3. run `cargo test`

it will **not** run this doctest, only if the create was created without the `--bin` flag. This behaviour is documented in the [crates manifest](http://doc.crates.io/manifest.html) but this should be noted directly in the book. Particularly as I think, most readers of the book will play around with a project with a main.rs but not with a lib.rs.

**Comment by thiagooak** [comment]
Why do we run them on `cargo test` only for libraries?

Would be nice to know in order to write the docs.

```
That's right, cargo test tests embedded documentation too.

Note that cargo test will run the embedded documentation tests on libraries only, 
we do run it on binary programs in order to... / because ...
```

**Comment by contradictioned** [comment]
I have no idea, in the discussion in the IRC we just did not really have any reasoning
