### ISSUE TITLE
RUST_BACKTRACE=1 occasionally causes memory explosion

### ISSUE THREAD

**Issue by jdm** [rust-lang/rust#24231]
We've seen OOM errors occur on Servo's CI infrastructure before, and narrowed them down to the presence of RUST_BACKTRACE=1 and Servo panicking. A contributor did some more digging and came up with this analysis: https://groups.google.com/forum/#!topic/mozilla.dev.servo/UyR2fjiKahk

**Comment by steveklabnik** [comment]
Triage: https://github.com/rust-lang/rust/pull/24344 was merged, so closing
