### ISSUE TITLE
std::io::{empty, sink} do not replace /dev/null

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#24235]
In particular, splitting up the `Read` and `Write` halves mean that you can't use these in a generic context that expects a full stream (`Read + Write`).

We should consider deprecating these in favor of a single `null` constructor that is both `Read` and `Write`.

**Comment by aturon** [comment]
cc @alexcrichton

**Comment by alexcrichton** [comment]
I'm personally comfortable with a `io::null` name, but if we were to deprecate the `empty`/`sink` constructors in favor of this we'd want to basically insta-stabilize it at which point we may want to get some more consensus before taking action.

**Comment by steveklabnik** [comment]
`empty` and `sink` are now stable, so I guess this can be closed?

**Comment by alexcrichton** [comment]
Yeah I think this better belongs as an RFC issue nowadays and I haven't heard much of a desire for this recently so we may be covered.
