### ISSUE TITLE
v1.0.0-beta : 'rustc.exe'  crash on VISTA pro 32-bits

### ISSUE THREAD

**Issue by LETARTARE** [rust-lang/rust#24238]
Hello,
I just downloaded   (April 09, 2015) : version 1.0.0-beta April 3, 2015,  windows-32 (.msi and .exe)
I use : MinGw32-TDM-4.7.1 , with " ld --version -> GNU ld (GNU Binutils) 2.22"

I just tried : "rustc.exe --version", is the message provided by VISTA
````
VISTA message:
Signature du problème :
  Nom d’événement de problème:	APPCRASH
  Nom de l’application:	rustc.exe
  Version de l’application:	0.0.0.0
  Horodatage de l'application:	35004555
  Nom du module par défaut:	KERNEL32.dll!TryAcquireSRWLockExclusive
  Version du module par défaut:	6.0.6002.18881
  Horodateur du module par défaut:	51da3e27
  Code de l’exception:	c0000139
  Décalage de l’exception:	00009f5d
  Version du système:	6.0.6002.2.2.0.768.2
  Identificateur de paramètres régionaux:	1036
  Information supplémentaire n° 1:	9d13
  Information supplémentaire n° 2:	1abee00edb3fc1158f9ad6f44f0f6be8
  Information supplémentaire n° 3:	9d13
  Information supplémentaire n° 4:	1abee00edb3fc1158f9ad6f44f0f6be8
````
ditto for 'cargo.exe' and  'rustdoc.exe'.
Best regards

**Comment by steveklabnik** [comment]
We don't currently support Windows Vista, sorry! Windows 7 is the minimal version at this time. We've talked about ways of possibly supporting older platforms, but cannot right now.

**Comment by rtaycher** [comment]
Possibly the same sort of problem??
Has the same Exception Code.

Windows 8.1 With bing (32 bit windows, i686-pc-windows-msvcy)

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	rustc.exe
  Application Version:	0.0.0.0
  Application Timestamp:	566e3feb
  Fault Module Name:	1.7\bin\rustc_llvm-17a8ccbd.dll!_except1
  Fault Module Version:	6.3.9600.18146
  Fault Module Timestamp:	5650afc8
  Exception Code:	c0000139
  Exception Offset:	00097420
  OS Version:	6.3.9600.2.0.0.768.101
  Locale ID:	1033
  Additional Information 1:	1abe
  Additional Information 2:	1abee00edb3fc1158f9ad6f44f0f6be8
  Additional Information 3:	1abe
  Additional Information 4:	1abee00edb3fc1158f9ad6f44f0f6be8

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
