### ISSUE TITLE
rustc panic due to attempt to take value of `char_at`

### ISSUE THREAD

**Issue by rkrn** [rust-lang/rust#24257]
I came across this while making a typo. I had intended to write `.char_at(pos)` instead of `.char_at[pos]`. As follows:

    Users/rkrn/nlp/src/faststr/search.rs:15:23: 15:30 error: attempted to take value of method `char_at` on type `&str`
    /Users/rkrn/nlp/src/faststr/search.rs:15               pattern.char_at[pos] != pattern.char_at[pos-shift] {
                                                                                   ^~~~~~~
    /Users/rkrn/nlp/src/faststr/search.rs:15:30: 15:30 help: maybe a `()` to call it is missing? If not, try an anonymous function
    /Users/rkrn/nlp/src/faststr/search.rs:15:47: 15:54 error: attempted to take value of method `char_at` on type `&str`
    /Users/rkrn/nlp/src/faststr/search.rs:15               pattern.char_at[pos] != pattern.char_at[pos-shift] {
                                                                                                           ^~~~~~~
    /Users/rkrn/nlp/src/faststr/search.rs:15:54: 15:54 help: maybe a `()` to call it is missing? If not, try an anonymous function
    error: internal compiler error: no type for expr in fcx 0x10dfef698
    note: the compiler unexpectedly panicked. this is a bug.
    note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
    note: run with `RUST_BACKTRACE=1` for a backtrace

Backtrace:

       stack backtrace:
          1:        0x10c617f77 - sys::backtrace::write::h799ab135045ca9ca1LC
          2:        0x10c645e4d - panicking::on_panic::h9502e488a92fc8bcHAI
          3:        0x10c56a2de - rt::unwind::begin_unwind_inner::hf0537788ee16eadbiiI
          4:        0x10bd445ae - rt::unwind::begin_unwind::h447731439410619827
          5:        0x10bd44df9 - diagnostic::Handler::bug::hb6bac6e14e70580aZsB
          6:        0x1096392f7 - session::Session::bug::ha8fc29f5409f2777nYq
          7:        0x108b91dc4 - check::FnCtxt<'a, 'tcx>::expr_ty::h9a16e9499db8c677qwp
          8:        0x108bb00cc - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_expr::h23ed0f8d0cc660811bc
          9:        0x108bb045a - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_expr::h23ed0f8d0cc660811bc
         10:        0x108bb0591 - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_expr::h23ed0f8d0cc660811bc
         11:        0x108bb0591 - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_expr::h23ed0f8d0cc660811bc
         12:        0x108bb06dd - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_expr::h23ed0f8d0cc660811bc
         13:        0x108bb0965 - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_expr::h23ed0f8d0cc660811bc
         14:        0x108bb08fe - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_expr::h23ed0f8d0cc660811bc
         15:        0x108bb0a47 - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_expr::h23ed0f8d0cc660811bc
         16:        0x108bb08fe - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_expr::h23ed0f8d0cc660811bc
         17:        0x108bb0965 - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_expr::h23ed0f8d0cc660811bc
         18:        0x108c6e80b - check::check_bare_fn::h05c77be534ada2cfUQn
         19:        0x108c67ee2 - check::check_item::h9d89bedf29e4fe82F9n
         20:        0x108c6c892 - visit::walk_item::h15797362535539718087
         21:        0x108c6c89d - visit::walk_item::h15797362535539718087
         22:        0x108d44681 - check_crate::closure.36302
         23:        0x108d3eae7 - check_crate::h09aa7856a322fd44bwC
         24:        0x108a61355 - driver::phase_3_run_analysis_passes::h1af60e7c926ca39dgGa
         25:        0x108a45a85 - driver::compile_input::h27cf4320fd56e5cbQba
         26:        0x108b03a15 - run_compiler::h93c68a2a3c26052bV4b
         27:        0x108b011e2 - boxed::F.FnBox<A>::call_box::h4498816167135712709
         28:        0x108b006d7 - rt::unwind::try::try_fn::h2387014819904265058
         29:        0x10c6cfea8 - rust_try_inner
         30:        0x10c6cfe95 - rust_try
         31:        0x108b009ca - boxed::F.FnBox<A>::call_box::h4850138824497903476
         32:        0x10c62f37d - sys::thread::create::thread_start::h42d6d904fce5365aihH
         33:     0x7fff8bcea7a1 - _pthread_start

Hope this is useful!

**Comment by arielb1** [comment]
Could you give more context?

**Comment by rkrn** [comment]
Here is the full offending code:

    pub fn kmp(text: &str, pattern: &str) -> i64 {
        let pattern_length = pattern.len();

        let mut shifts = vec![1; pattern_length+1];
        let mut shift = 1;

        for pos in 0..pattern_length {
            while shift <= pos &&
                  pattern.char_at[pos] != pattern.char_at[pos-shift] {
                shift += shifts[pos-shift];
            }
            shifts[pos+1] = shift;
        }

        let mut start_pos = 0;
        let mut match_len: i64 = 0;
        let mut count = 0;
        for ch in text.chars() {
            while match_len == pattern_length as i64 ||
                   match_len >= 0 &&
                   pattern.char_at(match_len as usize) != ch {
                start_pos += shifts[match_len as usize];
                match_len -= shifts[match_len as usize] as i64;
            }
            match_len += 1;
            if match_len == pattern_length as i64 { count += 1; }
        }
        return count;
    }

**Comment by bombless** [comment]
shorter reproduce but with longer backtrace:
```rust
fn main() {
    let foo;
    0.bar[0-0];
    foo[-0];
}
```
```
$ rustc -Vv
rustc 1.0.0-dev (47551b574 2015-04-14) (built 2015-04-15)
binary: rustc
commit-hash: 47551b57456c108c69f698b114606a275fb01643
commit-date: 2015-04-14
build-date: 2015-04-15
host: x86_64-pc-windows-gnu
release: 1.0.0-dev
```
```
stack backtrace:
   1:         0x712b8995 - sys::backtrace::write::hfd38368ec8028bb1KRC
   2:         0x712f1489 - rt::unwind::register::h08a584336097b7c4suI
   3:         0x711870e7 - rt::unwind::begin_unwind_inner::ha607f27fd721be6aCrI
   4:           0x7e3e5c - diagnostic::SpanHandler::span_bug::hbcfacf13792ec7b7RmB
   5:           0x7e49de - diagnostic::Handler::bug::h5e7022718f8d292atsB
   6:          0x181f960 - session::Session::bug::h00ee353635d6a6cbwRp
   7:          0x344f1b1
   8:          0x3494520 - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_expr::h176b043f5e5d64f1u8b
   9:          0x349b6fe - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_local::h47e175418774f1e02dc
  10:          0x34949c6 - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_expr::h176b043f5e5d64f1u8b
  11:          0x3496583 - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_stmt::h26fb82aef4a14a88W7b
  12:          0x34964d2 - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_stmt::h26fb82aef4a14a88W7b
  13:          0x349e9df - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_ty::h693089c487ea030aTec
  14:          0x3495ccf - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_block::hbe55732ed3d9c51flbc
  15:          0x3495a14 - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_expr::h176b043f5e5d64f1u8b
  16:          0x361e212 - check::CheckItemTypesVisitor<'a, 'tcx>.Visitor<'tcx>::visit_ty::h2305b4702c4e64e77Pn
  17:          0x361683f - check::CheckItemTypesVisitor<'a, 'tcx>.Visitor<'tcx>::visit_item::h9881b7ab20a4696eLPn
  18:          0x361600c - check::CheckItemTypesVisitor<'a, 'tcx>.Visitor<'tcx>::visit_item::h9881b7ab20a4696eLPn
  19:          0x361bf8e - check::CheckItemTypesVisitor<'a, 'tcx>.Visitor<'tcx>::visit_ty::h2305b4702c4e64e77Pn
  20:          0x361beef - check::CheckItemTypesVisitor<'a, 'tcx>.Visitor<'tcx>::visit_ty::h2305b4702c4e64e77Pn
  21:          0x361d83b - check::CheckItemTypesVisitor<'a, 'tcx>.Visitor<'tcx>::visit_ty::h2305b4702c4e64e77Pn
  22:          0x361d46c - check::CheckItemTypesVisitor<'a, 'tcx>.Visitor<'tcx>::visit_ty::h2305b4702c4e64e77Pn
  23:          0x382727d - check_crate::hbe12ce8ac4dc7ab7YmC
  24:          0x3826e5a - check_crate::hbe12ce8ac4dc7ab7YmC
  25:          0x3823c04 - check_crate::hbe12ce8ac4dc7ab7YmC
  26:         0x652eed9d - driver::phase_3_run_analysis_passes::hbe0b356835407069nGa
  27:         0x652c2634 - driver::compile_input::hfc619fda1a2632e0Qba
  28:         0x654de669 - run_compiler::h653034a0f1a715a3F4b
  29:         0x654db99b - monitor::Sink.Write::flush::h8d33e737534a5fe0U7c
  30:         0x654dafe4 - run::ha9cc11ce37570e6cl4b
  31:         0x654daedd - run::ha9cc11ce37570e6cl4b
  32:         0x654dac63 - run::ha9cc11ce37570e6cl4b
  33:         0x654da5ed - run::ha9cc11ce37570e6cl4b
  34:         0x654da578 - run::ha9cc11ce37570e6cl4b
  35:         0x654da521 - run::ha9cc11ce37570e6cl4b
  36:         0x713ac1dc - rust_try
  37:         0x713ac1b9 - rust_try
  38:         0x654d9b24 - run::ha9cc11ce37570e6cl4b
  39:         0x654d979d - run::ha9cc11ce37570e6cl4b
  40:         0x654dada9 - run::ha9cc11ce37570e6cl4b
  41:         0x71239693 - sys::thread::guard::current::he68668c1a0c584c2X4G
  42:         0x712b19ed - sys_common::stack::record_sp_limit::target_record_sp_limit::he14532463c6507db1HB
  43:         0x712d5ec1 - sys::tcp::TcpListener::bind::hcd7eb5130b8064cdhUG
  44:         0x712d5ea1 - sys::tcp::TcpListener::bind::hcd7eb5130b8064cdhUG
  45:     0x7ffd2f6b16ad - BaseThreadInitThunk
```

**Comment by pmarcelll** [comment]
I can't reproduce it, both test cases gave a regular build error.
```
rustc 1.2.0-nightly (20d23d8e5 2015-06-18)
binary: rustc
commit-hash: 20d23d8e57c0313c811135535d6872463cc6525d
commit-date: 2015-06-18
host: x86_64-unknown-linux-gnu
release: 1.2.0-nightly
```

**Comment by alexcrichton** [comment]
Agreed!
