### ISSUE TITLE
Rust Book Site Chapter 3 broken

### ISSUE THREAD

**Issue by frostyandy2k** [rust-lang/rust#24252]
Hi

The Documentation at https://doc.rust-lang.org/book/learn-rust.html is empty. Would be awesome if someone can fix it or tell me where I can report this bug.

Best to all contributors!

**Comment by alexcrichton** [comment]
cc @steveklabnik

**Comment by steveklabnik** [comment]
I have an in-progress PR that adds text to this: https://github.com/rust-lang/rust/pull/24244 

Thank you! Since that's already open, I'm going to give this a close.

**Comment by steveklabnik** [comment]
(and in the future, this is absolutely the right place)
