### ISSUE TITLE
Cannot use integer modulus in freestanding code - dependency on libm

### ISSUE THREAD

**Issue by krzysz00** [rust-lang/rust#24256]
I was working on a mini-kernel (https://github.com/krzysz00/rust-kernel/) when I found that libcore (which, according to the documentation, is dependency-free and freestanding) unavoidable depends on libm.

I compiled the following code by `rustc lib.rs [linker flag for rlibc]; ld libtest.a`

```rust
#![feature(no_std,lang_items,asm,core)]
#![no_std]

#![crate_type="staticlib"]
#![crate_name="test"]

#[macro_use]
extern crate core;

extern crate rlibc;

#[inline(never)]
fn mod_by(divisor: u32) -> u32 {
    return 14 % divisor;
}

#[lang="start"]
#[no_mangle]
pub fn _start() -> u32 {
    let ret = mod_by(7);
    ret
}

#[lang = "stack_exhausted"] extern fn stack_exhausted() {}
#[lang = "eh_personality"] extern fn eh_personality() {}
#[lang = "panic_fmt"] fn panic_fmt() -> ! { loop {} }
```

I expected the code to compile cleanly and run, or for there to be some form of `no_floats` directive that would remove dependencies on `libm`.

The code instead threw a large number of linker errors related to a lack of floating-point functions. 

## Meta
```
rustc 1.0.0-nightly (d9146bf8b 2015-04-07) (built 2015-04-08)
binary: rustc
commit-hash: d9146bf8ba0bdf98a46c4656899e54802e96ac0c
commit-date: 2015-04-07
build-date: 2015-04-08
host: x86_64-unknown-linux-gnu
release: 1.0.0-nightly
```

**Comment by oli-obk** [comment]
as a hack you could try to run llvm's link time optimizations, which should remove all the unused (float) functions from libcore (and result in a smaller binary).

**Comment by krzysz00** [comment]
I wrote a [rlibm](https://github.com/krzysz00/rust-kernel/blob/mallocoid/deps/rlibm.rs) (by analogy with rlibc), which stubs out the relevant libm functions (the stubs generally return NaN). Since the functions weren't being called, they got optimized out of the final binary anyway, but they had to be there or `ld` would complain. 

Should I publish that as a standalone library?

**Comment by alexcrichton** [comment]
Most Rust code is intended to be linked with `--gc-sections`, and if you do that you should be able to strip out all the unused references to floating point symbols.

**Comment by krzysz00** [comment]
Yeah, that was what I was missing. Thanks!

**Comment by krzysz00** [comment]
Actually, the --gc-sections removed the libm dependency. I figure I should close this then, since this is not actually an issue.
