### ISSUE TITLE
Specification and Grammar incomplete with regards to lexing rules

### ISSUE THREAD

**Issue by bruno-medeiros** [rust-lang/rust#24272]
Both the reference (http://doc.rust-lang.org/reference.html#lexical-structure) and the grammar reference (http://doc.rust-lang.org/grammar.html#lexical-structure) are very incomplete with regards to the lexing rules. For example:
 * lifetimes token not documented
 * attributes token not documented
 * character/string literal token rules are incomplete, they do not seem to specify the `b`/`br#` prefixes for character and string literals.

I'm writing a lexer for an IDE (to do syntax highlighting), and since I'm not yet familar with Rust itself,  this makes my life a bit harder...

**Comment by steveklabnik** [comment]
Yup, we'd love to get this filled out.

**Comment by fhahn** [comment]
@bruno-medeiros there exists an Antler [lexer](https://github.com/rust-lang/rust/blob/master/src/grammar/RustLexer.g4), which only differs from the Rust lexer [slightly](https://github.com/rust-lang/rust/issues/15883), maybe this could help.

**Comment by bruno-medeiros** [comment]
> there exists an Antler lexer, which only differs from the Rust lexer slightly, maybe this could help.
Yeah it does. Another user had directed me to it too.

Hum, and I just realized too the Attribute rule is not a token, but a grammar rule...

**Comment by bruno-medeiros** [comment]
> there exists an Antler lexer, which only differs from the Rust lexer slightly, maybe this could help.

Yeah it does. Another user had also directed me to that.

Hum, and I also just realized the Attribute rule is not a token, but a grammar rule...

**Comment by steveklabnik** [comment]
I'm going to close this in favor of https://github.com/rust-lang/rust/issues/30942, which is more general.
