### ISSUE TITLE
Can't derive Copy for structs containing arrays

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#24288]
Since Copy: Clone and arrays implement Copy but not Clone.

Whose bright idea was it to have a language item depend on an arbitrary trait?

**Comment by retep998** [comment]
`impl Clone for Blah { fn clone(&self) -> Blah { *self } }`

**Comment by mahkoh** [comment]
No shit. Then why doesn't `#[derive(Copy, Clone)]` do this?

**Comment by retep998** [comment]
Because `[derive]` is unable to inspect what traits are already implemented for a type to choose the appropriate implementation.

**Comment by retep998** [comment]
However you do bring up a good point with that `Copy: Clone` yet arrays impl `Copy` but not `Clone`. That's definitely something that needs to be fixed, and I believe integer generics are the key to solving it.

**Comment by mahkoh** [comment]
>Because `#[derive] `is unable to inspect what traits are already implemented for a type to choose the appropriate implementation.

Looks like you found the solution: Change derive to be able to do this.

**Comment by kballard** [comment]
@mahkoh You raise a legitimate issue, but you need to watch your language and tone of voice. The way you've written your ticket and replies is unnecessarily rude, and this isn't an isolated incident.

**Comment by tsion** [comment]
@mahkoh Hey, we can solve this problem without being rude about it. This is an annoying wart, for sure, but it's not the end of the world, and it will get fixed.

**Comment by mahkoh** [comment]
@kballard @tsion Interesting.

**Comment by nikomatsakis** [comment]
@mahkoh in fact, that was implemented as part of PR https://github.com/rust-lang/rust/pull/23905. I was just encouraging erickt on IRC to extract that out as a separate thing, in fact.

**Comment by eternaleye** [comment]
@mahkoh https://github.com/rust-lang/rust/pull/23905 may be of interest.

I will note that your tone comes across as quite confrontational, while the Rust community seems to strive for a more collaborative atmosphere in my experience.

**Comment by retep998** [comment]
@mahkoh Sorry about all the people that decided to take over this issue to complain about your rudeness.

**Comment by steveklabnik** [comment]
@retep998 that's one reason why rudeness is so bad: it's a distraction from the technical point at hand.

**Comment by mahkoh** [comment]
@nikomatsakis 

>Yes, this PR explicitly handles `#[derive(Copy, Clone)]`

Then that should solve the problem.
