### ISSUE TITLE
In some cases, types reexported out of private modules do not show up in rustdoc

### ISSUE THREAD

**Issue by carllerche** [rust-lang/rust#24296]
In the Bytes lib I re-export some structs out of private modules, but for some reason they don't show up in the generated docs.

Reexport: https://github.com/carllerche/bytes/blob/40f1d1aa77f0fce11da943b67b408e29f05eb893/src/lib.rs#L25

Docs (though kind of sad): https://github.com/carllerche/bytes/blob/master/src/str/bytes.rs#L8

Rustdoc: http://carllerche.github.io/bytes/bytes/index.html

**Comment by fhartwig** [comment]
This seems to have been fixed, though I don't know how/when. Making the `buf` and `str` modules of the bytes crate private, I can't reproduce this problem any more (on nightly). The structs docs now get "inlined" into the crate root now, which is probably what we want.
