### ISSUE TITLE
JoinGuard does not document that it panics if join-on-drop returns an error

### ISSUE THREAD

**Issue by kballard** [rust-lang/rust#24300]
The documentation on [`std::thread::JoinGuard`](http://doc.rust-lang.org/nightly/std/thread/struct.JoinGuard.html) and the things that use it ([`std::thread::scoped`](http://doc.rust-lang.org/nightly/std/thread/fn.scoped.html), [`std::thread::Builder::scoped`](http://doc.rust-lang.org/nightly/std/thread/struct.Builder.html#method.scoped), and the [`std::thread` module documentation](http://doc.rust-lang.org/nightly/std/thread/index.html)) document that `JoinGuard` joins the thread when it's dropped, but they do not document that if this implicit join results in an `Err` it panics the current thread. This seems like a very important thing to document.

**Comment by steveklabnik** [comment]
http://doc.rust-lang.org/nightly/std/thread/struct.JoinGuard.html#method.join does in fact say 'panics on the child thread are propagated by panicking the parent.'
