### ISSUE TITLE
Add a flag to unstable rustc and cargo to "emulate stable"

### ISSUE THREAD

**Issue by XMPPwocky** [rust-lang/rust#24316]
In other words:

```
rustc --emulate-stable
```

will disallow unstable code, even in unstable channels, and 

```
cargo build --emulate-stable
```

will pass`--emulate-stable` along to rustc, _even when building dependencies_.

These flags would help developers by allowing them to only install one version of rustc, but still be sure that their code would work on a stable channel.

**Comment by nrc** [comment]
Personally, I prefer developers to use multi-rust. If that is a problem we should make multi-rust better. The stability system is already complex, and I wouldn't like to make it more so. However, I don't know it in detail, if this is just a few lines of code, then I guess I would be happy to see it.

**Comment by eddyb** [comment]
@nrc Disallowing unstable features is currently done by omitting a magic env var, and we already have a nice enum for all the states, so supporting this flag should be rather straight-forward, if desired.

**Comment by wthrowe** [comment]
Would this actually let you test that your code would work on stable rather than that it will work on stable two versions from now?

**Comment by nikomatsakis** [comment]
I'd like to drill in on what the problem is precisely we are trying to solve. I think that the vision was that you could write code that works on stable (but test it under nightly) by simply not enabling any feature-gates. But clearly there are shortcomings, can we enumerate those?

Some things I can think of:

- accidentally using new APIs (that will become stable two release cycles from now, but are not included in the current stable compiler)
- bug fixes

**Comment by shepmaster** [comment]
> Personally, I prefer developers to use multi-rust. If that is a problem we should make multi-rust better.

A downside of this would be the environments where that tool doesn't exist; Windows being the big one.

**Comment by steveklabnik** [comment]
There's a big push underway to unify all of our installation and related
tooling, so it should have it soon.

**Comment by pmarcelll** [comment]
Triage: I think as previously mentioned, adding extra complexity to the stability system is not worth it, and since rustup reached 1.0, writing `cargo +stable build` is an easy and straightforward workaround.

**Comment by steveklabnik** [comment]
It's been a while, let's nominate so the compiler team can make a decision if this is something we'd even want.

**Comment by nikomatsakis** [comment]
@rfcbot fcp close

I propose we close this issue. It's still not clear exactly what problem it's trying to solve, and clearly this issue has been around for a while without a lot of complaints.

**Comment by Mark-Simulacrum** [comment]
@Aatch @bkoropoff Friendly reminder that this is waiting on your approval to close it.

**Comment by aturon** [comment]
I'm going to close the issue; active members of the compiler team have already signed off.
