### ISSUE TITLE
Remove repr-lookup attempt in `derive` expansion

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#24320]
Spawned off of #24270, in particular this discussion: https://github.com/rust-lang/rust/pull/24270#discussion-diff-28163635

The new code for `deriving(PartialOrd)` attempts to look up if there is a `repr` attribute on the `enum` that is driving the deriving expansion, because we need (at least) to incorporate knowledge of whether the discriminant is meant to be interpreted as a signed integer or an unsigned one (since the current intrinsic always returns a `u64` today).

However, the look up may be fragile, since @sfackler points out that a later pass of expansion could add the `repr` that we are seeking.

There are a number of different ways to solve this problem (see the linked discussion for some of them).

**Comment by pnkfelix** [comment]
I do not see this as a terribly high priority item.

Exposing the problem requires injecting a `repr` attribute at a later pass of expansion, but I am not sure there are currently any instances of expansions that do this.

**Comment by pnkfelix** [comment]
triage: P-low

**Comment by Mark-Simulacrum** [comment]
I think this is largely unsolveable to the extent that derives are always going to be less than perfect (we don't know enough at expansion time). In particular, we hit this issue with repr(packed) types and related desire for the type to be Copy... 

I'm going to close this issue as I don't think it's worthwhile to track this.
