### ISSUE TITLE
Duplicate trait functions in documentation for std::fs::File

### ISSUE THREAD

**Issue by alfiedotwtf** [rust-lang/rust#24324]
Currently, the documentation for std::fs::File is showing duplicate content:

    http://doc.rust-lang.org/1.0.0-beta/std/fs/struct.File.html#

    ...
    impl AsRawFd for File
      fn as_raw_fd(&self) -> RawFd
    impl FromRawFd for File
      fn from_raw_fd(fd: RawFd) -> File
    impl AsRawFd for File
      fn as_raw_fd(&self) -> RawFd
    impl FromRawFd for File
      fn from_raw_fd(fd: RawFd) -> File

**Comment by lifthrasiir** [comment]
Another occurrence: https://doc.rust-lang.org/nightly/std/fs/struct.Metadata.html

**Comment by christopherdumas** [comment]
@alfiedotwtf I found out why:
```rust
    #[allow(deprecated)]
    #[stable(feature = "rust1", since = "1.0.0")]
    impl AsRawFd for old_io::fs::File {
        fn as_raw_fd(&self) -> RawFd {
            self.as_inner().fd()
        }
    }

    #[stable(feature = "rust1", since = "1.0.0")]
    impl AsRawFd for fs::File {
        fn as_raw_fd(&self) -> RawFd {
            self.as_inner().fd().raw()
        }
    }
```
Apparently, the old `fs::File` is still around, and it's `impl`s are showing up on the documentation page. It seems to me that the only way to fix this would be to completely delete the old `fs::File`

**Comment by alfiedotwtf** [comment]
Thanks for finding the reasoning behind this.

As it's doing the right thing, I guess I'll close this ticket :)
