### ISSUE TITLE
Trait generic over lifetime causes uses of associated types to fail to infer properly inside default methods

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#24338]
``` rust
trait DictLike<'a> {
    type ItemsIterator: Iterator<Item=u8>;

    fn items(&self) -> Self::ItemsIterator;

    fn get(&self)  {
        for k in self.items() {} 
        // get(self)
    }
}

// fn get<'a, X: ?Sized + DictLike<'a>>(x: &X) { for k in x.items() {} }

fn main() {}
```

```
<anon>:7:13: 7:14 error: unable to infer enough type information about `_`; type annotations required [E0282]
<anon>:7         for k in self.items() {} 
                     ^
```

Strangely, switching to the commented out form works fine, i.e. just moving the body of the code out of the default method.

Nominating since I am unsure how important we regard inference issues like this to be.

**Comment by pnkfelix** [comment]
Probably "just-a-bug"; P-low, not 1.0.

**Comment by eefriedman** [comment]
Testcase without for loop desugaring:
```rust
trait DictLike<'a> {
    type ItemsIterator: Iterator<Item=u8>;
    fn get(mut c: Self::ItemsIterator) {
        c = c.into_iter();
    }
}
fn main() {}
```

**Comment by mitchmindtree** [comment]
Just thought I'd mention I ran into this bug just now while writing a trait with some associated iterator type - frustrating errors, but managed to side-step it with @huonw 's workaround [here](http://stackoverflow.com/a/31815824/1711917).

**Comment by malbarbo** [comment]
The test cases in this issue compile fine since rustc 1.4 ([Playground](https://play.rust-lang.org/?gist=b0bd682b4b33620e692805ecdc624686&version=stable&backtrace=0) for rustc stable).

**Comment by malbarbo** [comment]
Please add E-needstest tag so one can write a regression test an the issue be closed.
