### ISSUE TITLE
Code example in std::net::lookup_host is not working

### ISSUE THREAD

**Issue by achanda** [rust-lang/rust#24332]
Th example here: https://doc.rust-lang.org/std/net/fn.lookup_host.html shows

```
<anon>:2:1: 2:18 error: an external crate named `std` has already been imported into this module [E0259]
<anon>:2 extern crate std;
         ^~~~~~~~~~~~~~~~~
error: aborting due to previous error
playpen: application terminated with error code 101
```

**Comment by steveklabnik** [comment]
We need an explicit `main` here, I think

**Comment by achanda** [comment]
@steveklabnik when I click on the codepen link, I do see an explicit `main`. However, the function `foo` was not being called.

**Comment by steveklabnik** [comment]
Right, but I think it does the wrong thing, because that main is generated by Rustdoc.


It's only a theory, I could be wrong

**Comment by steveklabnik** [comment]
Oh! No, this is https://github.com/rust-lang/rust/pull/24597
