### ISSUE TITLE
Regression from beta: closure may outlive the current function, but it borrows `...`, which is owned by the current function

### ISSUE THREAD

**Issue by tomaka** [rust-lang/rust#24364]
As reported in [this thread](http://internals.rust-lang.org/t/regression-report-beta-2015-04-03-vs-nightly-2015-04-10/1860/5), the two examples [here](https://github.com/tomaka/glium/tree/891b83655a3b6fc1a059ba7c9808e357b973b3e9/examples-disabled) no longer compile with the nightly but they *do* compile with the beta (tested with the 2015-04-12 nightly).

```
examples/displacement_mapping.rs:200:25: 237:6 error: closure may outlive the current function, but it borrows `opengl_texture`, which is owned by the current function [E0373]
examples/displacement_mapping.rs:200     support::start_loop(|| {
examples/displacement_mapping.rs:201         // building the uniforms
examples/displacement_mapping.rs:202         let uniforms = uniform! {
examples/displacement_mapping.rs:203             inner_level: 64.0f32,
examples/displacement_mapping.rs:204             outer_level: 64.0f32,
examples/displacement_mapping.rs:205             projection_matrix: camera.get_perspective(),
                                     ...
examples/displacement_mapping.rs:212:30: 212:44 note: `opengl_texture` is borrowed here
examples/displacement_mapping.rs:212             height_texture: &opengl_texture,
                                                                  ^~~~~~~~~~~~~~
<glium macros>:1:1: 12:46 note: in expansion of uniform!
examples/displacement_mapping.rs:202:24: 215:11 note: expansion site
examples/displacement_mapping.rs:200:25: 237:6 help: to force the closure to take ownership of `opengl_texture` (and any other referenced variables), use the `move` keyword, as shown:
examples/displacement_mapping.rs:        support::start_loop(move || {
examples/displacement_mapping.rs:            // building the uniforms
examples/displacement_mapping.rs:            let uniforms = uniform! {
examples/displacement_mapping.rs:                inner_level: 64.0f32,
examples/displacement_mapping.rs:                outer_level: 64.0f32,
examples/displacement_mapping.rs:                projection_matrix: camera.get_perspective(),
                                     ...
```

I didn't manage to reproduce on a small scale, so I'll explain a bit the code of `displacement_mapping.rs`:

- At [line 32](https://github.com/tomaka/glium/blob/891b83655a3b6fc1a059ba7c9808e357b973b3e9/examples-disabled/displacement_mapping.rs#L32) we create a struct of type `CompressedTexture2d`.
- The type `&'a CompressedTexture2d` implements the trait `IntoUniformValue<'a>`. This trait can turn the reference into a `UniformValue<'a>`.
- [Line 200](https://github.com/tomaka/glium/blob/891b83655a3b6fc1a059ba7c9808e357b973b3e9/examples-disabled/displacement_mapping.rs#L200) we enter a closure. The `support::start_loop` function has this signature: `fn start_loop<F>(mut callback: F) where F: FnMut() -> Action`.
- [Lines 202-215](https://github.com/tomaka/glium/blob/891b83655a3b6fc1a059ba7c9808e357b973b3e9/examples-disabled/displacement_mapping.rs#L202-L215) we borrow `&'a` the texture, call `into_uniform_value()` and store the `UniformValue<'a>` in a `Vec`.
- [Lines 220-225](https://github.com/tomaka/glium/blob/891b83655a3b6fc1a059ba7c9808e357b973b3e9/examples-disabled/displacement_mapping.rs#L220-L225) uses `&uniforms` (only borrows it to see its content, doesn't do anything special with its lifetime).

More precisely, the `uniform!` macro invokation does the following:
```rust
{
    let uniforms = UniformsStorage::new("inner_level", 64.0f32);
    let uniforms = uniforms.add("outer_level", 64.0f32);
    ...
    let uniforms = uniforms.add("height_texture", &opengl_texture);
    let uniforms = uniforms.add("elevation", 0.3f32);
    let uniforms = uniforms.add("color_texture", &opengl_texture);
    uniforms
}
```

See [the definition of `UniformsStorage` here](https://github.com/tomaka/glium/blob/891b83655a3b6fc1a059ba7c9808e357b973b3e9/src/uniforms/uniforms.rs).

**Comment by brson** [comment]
I'm untagging all pre-1.0 regressions to repurpose it for stable regressions.

**Comment by pnkfelix** [comment]
@brson from skimming the description this *might* be a regression against 1.0 -- it is described as code that compiled in the beta but did not compile in nightly....

(As an aside, perhaps we should have distinct tags for regressions against the stable channel versus regressions against the beta channel.  Or maybe not, perhaps both need equal prioritization...)

**Comment by tomaka** [comment]
I'm closing this as 1.0 is old now. Fixing a regression from beta to 1.0 doesn't really make sense.
