### ISSUE TITLE
Use Unicode line drawing characters for spans

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#24387]
![example](http://i.imgur.com/G2lm9I9.png)

See discussion on old PR #21406. @Manishearth expressed interest in reviving this.

**Comment by sinistersnare** [comment]
+1 sounds nice.

Would this work on any windows terminals, such as  the shell that comes with mingw?

**Comment by liigo** [comment]
Always prefer ASCII characters.

**Comment by tbelaire** [comment]
The plan, from [before][1] was to have both a flag `--output-plain-ascii`, as well as environment variables which can be set to `always`, `auto` or `never`, for each of color, having underlines at all, and having unicode underlines.


[1]: https://github.com/rust-lang/rust/pull/21406#issuecomment-74359331

**Comment by P1start** [comment]
Alternatively, we could use U+203E OVERLINE (`‾`, also part of WGL4) to create a simpler underline effect:

![U+202E OVERLINE in a warning](https://cloud.githubusercontent.com/assets/2055302/8536639/1d16e38a-24a8-11e5-8bfc-beca87dcfffc.png)


This is different from using an ANSI escape code such as `\x1b[4m` because it allows the underline colour to be different from the text’s colour.

**Comment by shinglyu** [comment]
I'm a noob, can I give it a try? I could try writing a unicode version, then implement the `--output-plain-ascii` flag.

**Comment by Manishearth** [comment]
@shinglyu sure! You can borrow a lot of stuff from Keegan's impl [here](https://github.com/rust-lang/rust/pull/21406/files), feel free to ask me if you have more questions!

**Comment by shinglyu** [comment]
@Manishearth : nice to see you again :)

**Comment by shinglyu** [comment]
@Manishearth : I tried to read the patch https://github.com/rust-lang/rust/pull/21406, but I had a hard time understanding the codebase. Is there any document/blog post/diagram/etc that explains the folder structure and runtime behavior? Most of the docs I found are explaining the Rust language syntax. 

Or should I start by reading the llvm tutorial?

**Comment by Manishearth** [comment]
src/librustc/session/config.rs contains the stuff for sorting out command line arguments

src/libsyntax/diagnostic.rs has the stuff for printing out a span.

You don't need to understand the rest at this stage, really :)

**Comment by shinglyu** [comment]
@Manishearth : thanks! I'll take a look.

**Comment by shinglyu** [comment]
@Manishearth @kmcallister : Changing ascii to UTF-8 is pretty straight forward. But I want to clarify the spec. 

From what I understand in the closed PR, 
* We have 3 environment variables for output capability
  * `RUSTC_OUTPUT_COLOR = always | auto | never`
  * `RUSTC_OUTPUT_CURSOR_POS = always | auto | never`
  * `RUSTC_OUTPUT_UTF8 = always | auto | never`
  * If any of the three is un-set or is invalid value, use `auto`
* There are 2 way to set the above three as `never`:
  * --output-plain-ascii flag
  * RUSTC_OUTPUT_PLAIN_ASCII = <any value>

I have some questions:
* If cursor positioning is not enabled, what do we do?
* What are all those flag stability and warning thing?

Thanks!

**Comment by bluss** [comment]
Most programs will check against `LC_CTYPE` (i.e. the locale's encoding setting) to see what they can emit. If it's not a UTF-8 locale, just emit ascii.

**Comment by christopherdumas** [comment]
Is this going anywhere?

**Comment by christopherdumas** [comment]
I like the idea, but Rust still doesn't do this.

**Comment by pmatos** [comment]
@shinglyu how is this going?

**Comment by shinglyu** [comment]
I'm sorry, too occupied by other things. Anyone interested can take it.

Paulo Matos <notifications@github.com> 於 2015年10月19日 週一 下午9:48寫道：

**Comment by shinglyu** [comment]
To be more precise, drawing unicode chars is trivial. The hard part is handling all the commandline flags. I might be able to put together something this week, but if anyone think he/she can finish this faster, please feel free to take it.

**Comment by shinglyu** [comment]
Sorry I claimed it but didn't finish it on time. Give me one week to work on this. If I can't make it, anyone if free to take it.

**Comment by pmatos** [comment]
OK, @shinglyu , if you see you won't make it, can you please post your progress so someone can pick it up where you left off instead of starting from scratch? Thanks!

**Comment by pnkfelix** [comment]
Uh @shinglyu @pmatos   do note there is https://github.com/rust-lang/rust/pull/28902

**Comment by shinglyu** [comment]
Oh ok, so look like the old PR is being revived. Let's go with #28902 then.

**Comment by brson** [comment]
With the recent churn in error reporting, this will probably need to start from scratch. Still a cool idea.

**Comment by brson** [comment]
cc @jonathandturner maybe you have ideas about how to beautify new error reporting with unicode.

**Comment by jonathandturner** [comment]
We've got an RFC going here: https://github.com/rust-lang/rfcs/pull/1644

We opted not to use Unicode because we did a look at what was generally available across platforms and Windows doesn't use Unicode by default in the terminal.  I know that they're working on a better terminal experience, so things might change there.

**Comment by steveklabnik** [comment]
The error format RFC ended up explicitly deciding against this: https://github.com/rust-lang/rfcs/blob/master/text/1644-default-and-expanded-rustc-errors.md#format-of-error-messages So I'm going to give it a close.
