### ISSUE TITLE
Feedback on rust book > Patterns

### ISSUE THREAD

**Issue by theWebalyst** [rust-lang/rust#24388]
I'm reading the book in section order and some sections have obvs been switched and the text still assumes the old order. I'm just going to mention that but not point out the occurrences here. However, it may explain some of my confusion, if a section I'm commenting on is silently assuming I've read something that now occurs later.

Firstly, I like Rust and am enjoying reading about it. The most confusing bit so far (a testament to how good the book has been) is "match" which has a very simple example, and "patterns" which uses match to illustrate a several patterns: https://doc.rust-lang.org/book/patterns.html

I can't tell from this what these code samples do, or what most of the patterns mean. Example output would help clarify this, but some of the descriptions probably still need expanding too.

I couldn't make sense of patterns based on these examples. 

Match guards appear to show overlapping cases (e.g. "5" would match both "OptionalInt::Value(i) if i > 5" and "OptionalInt::Value(..)"). Does match allow overlapping patterns? If so, what is the behaviour - first match only?

I don't understand how the "ref and ref mut" patterns work - the example seems to just show a matching example. In general the examples don't show what matches and why, what doesn't etc. which leaves a big gap in my understanding.

There may be some implicit knowledge that renders all this clear, but I haven't gained it by reading the book in order to this point. 

So far this is the only thing I know I don't understand, which is pretty damn good if true :-)
Also, where's the regexp pattern!? ;-)

**Comment by steveklabnik** [comment]
I think sample output here would be a great idea, for sure.

To answer the questions quickly, the patterns match in order: so the `OptionalInt` case, if `i` is 5, that will match, because it comes before the `..` case.

**Comment by theWebalyst** [comment]
Just to clarify further.. So a maximum of one case will 'match'?

**Comment by steveklabnik** [comment]
Yup.

**Comment by theWebalyst** [comment]
This comment is a placeholder that you might take as additional feedback, but its just raw braindump while I'm reading. Consider the following work in progress that I may re-visit and edit/delete:

#### Trait Objects https://doc.rust-lang.org/book/trait-objects.html
I get most of the explanations of dispatch, but while I do recall the basics of vtables from C++ (last touched >10yrs ago) I can't follow the explanation of representation, either because I've not got the information I need at this point (missing sections? inadequate attention and understanding on my part? inadequate explanation on yours? I'm not sure) or because I'm being slow to understand (my normal). 

I'm also left wondering why you've gone into this depth in a "read to use" section of the book. Is it appropriate here? It seems to be documenting something that would only be of interest to compiler writers or those really needing to stretch the capabilities of the compiler.

One thing that I've not grasped yet and which makes it a bit harder for me to understand the vtable explanation examples is the meaning of () within:

```pub struct TraitObject {
    pub data: *mut (),
    pub vtable: *mut (),
}```

I'm taking it as "collection" but not sure yet. I'm also unsure about why things are cast within the bodies of functions and forced outside to the caller. Essentially with my level of understanding at this point I'd need leading through the examples in much finder detail than is appropriate for a section that I take to be describing compiler implementation, and not really about documenting the language and its use to a newcomer.

#### Closures https://doc.rust-lang.org/book/closures.html
I'm also foundering while reading about ownership with regard to closures, from quite early on. Possibly because I need to go back and understand ownership better, but also possible because the explanations are too thin for me. I'm just noting this at this stage so I can re-visit, but for now I'll probably skip on.

**Comment by theWebalyst** [comment]
Ok, I've finished my first read through and the preceding comment concludes my feedback. Hope it is helpful. I look forward to updates and adiitions.

**Comment by steveklabnik** [comment]
Thanks! Dumps always are. I'm hoping to go through this issue sometime this weekend, so I'll check it out then.

**Comment by pnkfelix** [comment]
@theWebalyst BTW, regarding match and patterns, the most recent blog post may be of interest: 

  http://blog.rust-lang.org/2015/04/17/Enums-match-mutation-and-moves.html

(Full disclosure : I wrote it)

**Comment by theWebalyst** [comment]
Thanks @pnkfelix that looks very useful. Rust is powerful! Have bookmarked it :-)

PS Felix was a fave of mine!

**Comment by steveklabnik** [comment]
Okay, I've gone through the rest of this too. Thanks again for the feedback. Between the already-open PR, work that's been done since this was filed, and some of the future work I'm doing, I'm going to give this a close, since no _specific_ issue is going to close it. This has been very helpful, thanks again :)
