### ISSUE TITLE
64-bit .exe installer for windows has wrong default directory

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust#24397]
The .exe installer tries to install to "C:\Program Files (x86)\Rust", even though it's the 64-bit version. It then fails to create the destination directory due to a permission error.

The .msi installer correctly defaults to "C:\Program Files\Rust <channel> <version>", and has no problems with permissions, I would expect the .exe installer to have the same behaviour.

**Comment by alexchandel** [comment]
Rust should install to `C:\tools\`, just like Ant, Python, and many others. `C:\tools\` is the place for developer tools that have a known folder. `C:\Program Files\` is badly named (compare to `C:\ProgramData\`), poorly suited for command line tools, and clutters the already hideous PATH more than `C:\tools\`.

**Comment by Diggsey** [comment]
> Rust should install to C:\tools\, just like Ant, Python, and many others.

Neither Ant nor Python install to C:\tools\ by default, and searching I can't find any reference to C:\tools\ even being a thing? Both Python and Ant install to C:\Python<Version> and C:\ant, which is incredibly annoying, so please don't do that!

**Comment by alexchandel** [comment]
@Diggsey I might be mistaken, but installing both through [chocolatey](https://chocolatey.org/) stuck them in `C:/tools/` for me. I'd recommend anyone with a machine running Vista or later use chocolatey. And there's a trend in chocolatey to have packages extract to `C:/tools/` when they aren't self-contained enough for `C:/ProgramData/chocolatey/lib/`.

**Comment by alexchandel** [comment]
For an OS without much filesystem hierarchy, `C:\tools\` is a decent place for developer and command-line packages, similar to `/opt` on some unices. But I'd much rather see a [chocolatey package for Rust](https://chocolatey.org/packages/rust/1.0.0-alpha2) that actually obeyed chocolatey's conventions and extracted an archive to `C:\ProgramData\chocolatey\lib\rust\`, with no installer/registry involvement. But Rust only [provides](http://www.rust-lang.org/install.html) `msi` and `exe` installers for windows. :\

And all packages that do this reduce PATH clutter, since chocolatey symlinks their executables into `C:\ProgramData\chocolatey\bin\`.

**Comment by vadimcn** [comment]
The idea was to deprecate the .exe installer once .msi is known to be working satisfactory.

**Comment by alexchandel** [comment]
@vadimcn Can we have a zip release too, that contains Rust and Cargo like the others? Linux and OS X have an archive release. Those are preferred in chocolatey because they don't involve the registry or any other Windows components.

**Comment by brson** [comment]
@alexchandel We do produce tarballs for windows.

**Comment by brson** [comment]
Seems like we should probably just stop producing the .exe's

**Comment by alexchandel** [comment]
@brson I don't see a cargo+rustc nightly tarball for windows, although I do see ones for linux and osx.

**Comment by steveklabnik** [comment]
triage: We do not link to the .exe installer anymore, but we still produce them. I don't have access to windows at the moment to check if this bug has been resolved, but it's been a long time...

**Comment by alexchandel** [comment]
Grabbing the Windows download link from [downloads](https://www.rust-lang.org/en-US/downloads.html) and swapping the `.msi` for `.tar.gz` yields a functional link to the [tarball](https://static.rust-lang.org/dist/rust-nightly-i686-pc-windows-gnu.tar.gz), which is nice.

Testing on win7-x64, the MSI extracts with lessmsi, but the directory structure is somewhat unusual so there's no one-liner to get the Rust folder out. The best I came up with was:
```bat
lessmsi x rust-foo.msi \opt\ && move \opt\SourceDir\Rust \opt\rust && rmdir /s /q \opt\SourceDir
```
This yields a Rust install rooted at `\opt\rust`.

However now that rustup.rs exists, multiple targets aren't really an issue anymore. Someone should make a Chocolatey package for rustup.rs...

**Comment by Mark-Simulacrum** [comment]
Can someone with access to Windows check what happens here today?

**Comment by Diggsey** [comment]
@Mark-Simulacrum The latest version installs to `C:\Rust` instead, which works, but is a terrible default.

**Comment by steveklabnik** [comment]
Triage: 

![image](https://user-images.githubusercontent.com/27786/47793427-9f725000-dcf4-11e8-9509-38f6f58606ce.png)

This seems... fine. I'm not sure if this should stay open or not; I'll let the relevant team (infra? compiler?) decide.
