### ISSUE TITLE
Remove unicode::regex

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#24409]
The `unicode` crate (the one shipping with rustc) contains a `regex` module with some special-purpose tables of Unicode data to support the `regex` crate. But `regex` now has [its own copy](https://github.com/rust-lang/regex/blob/master/src/unicode.rs) of these tables, so I believe the module and the script that generate it can just be removed.

CC @alexcrichton, @kwantam

**Comment by kwantam** [comment]
I think this was addressed by #24339.

**Comment by SimonSapin** [comment]
Indeed! Thanks.
