### ISSUE TITLE
Attributes not documented in the Rust Reference

### ISSUE THREAD

**Issue by jimmycuadra** [rust-lang/rust#24406]
I have discovered a few attributes that are not documented in the Rust Reference:

* `cfg_attr`
* `stable`
* `unstable`
* `deprecated`

The ones relating to stability are also not mentioned in the Rust Book in the Documentation section.

**Comment by steveklabnik** [comment]
> The ones relating to stability are also not mentioned in the Rust Book in the Documentation section.

Yeah, that section is mostly about documenting your own code, and these attributes cannot be used outside of the standard library.

**Comment by jimmycuadra** [comment]
I didn't realize they were specific to the stdlib. That would explain why they didn't work when I tried them. What's the reason for limiting to the stdlib? It'd be a very useful feature in general.

**Comment by steveklabnik** [comment]
They're closely tied to release channels, which non-stdlib crates don't use. We agree it would be useful and want to make something, but haven't worked on a design yet.
