### ISSUE TITLE
rustdoc: Generates wrong signature for function with associated type parameter

### ISSUE THREAD

**Issue by mbudde** [rust-lang/rust#24417]
Create a library with the following `src/lib.rs`:
```rust
pub trait SomeTrait {
    type Typ;
}

pub struct Foo<T> {
    bar: T
}

impl<T: SomeTrait> Foo<T> {
    pub fn foo(&self, bar: T::Typ) {}
}
```
and run `cargo doc`. The documentation will show the type of `Foo::foo` as `fn foo(&self, bar: T)` and not `fn foo(&self, bar: T::Typ)` as expected.

`rustdoc 1.0.0-beta (9854143cb 2015-04-02) (built 2015-04-02)`

**Comment by steveklabnik** [comment]
You may want to try the nightly; a number of bugs have been fixed post-beta. Can you check?

**Comment by mbudde** [comment]
@steveklabnik: I can reproduce with `rustdoc 1.0.0-nightly (e6a812402 2015-04-14) (built 2015-04-14)`.

**Comment by steveklabnik** [comment]
:+1: thanks for checking.

**Comment by huonw** [comment]
triage: I-nominated

This can lead to some very confusing signatures, especially since associated types are quite widely used in the standard library with core types like iterators.

**Comment by mbudde** [comment]
I ran into the problem while reading the documentation for [mio](http://carllerche.github.io/mio/mio/struct.EventLoop.html#method.timeout_ms). I have not been able to find any instances of this problem in the standard library (only a couple of hits in the `librustc` crate) [1] .

[1] `git grep '\<fn[^(]*([^)]*[A-RT-Z][a-zA-Z_]*::[A-Z][^)]*)'`

**Comment by pnkfelix** [comment]
P-high, not 1.0.  Seems nice to fix, but without an example of this bug occurring in the stdlib itself, it is not a 1.0 blocker.

**Comment by bluss** [comment]
This is part of many kinds of signatures

source: `fn interleave<J>(self, other: J) -> Interleave<Self, J::IntoIter>`

displays as: `fn interleave<J>(self, other: J) -> Interleave<Self, J>`

where bounds:

source: `where I::Item: PartialEq<J::Item>`
display as: `where I: PartialEq<J>`
