### ISSUE TITLE
Some descriptions beginning with  `/// ` in docs

### ISSUE THREAD

**Issue by killercup** [rust-lang/rust#24410]
In the [`std::str` API docs](http://doc.rust-lang.org/std/str/index.html), some Struct descriptions beginn with `///`.

![std__str_-_rust](https://cloud.githubusercontent.com/assets/20063/7132987/baf67ffe-e28e-11e4-9c0f-14f60ab08915.jpg)

Some of these structs are generated by macros, e.g. `Matches` [here](https://github.com/rust-lang/rust/blob/5dc8060e3fbf49f225885217dc9f966ce95ff72d/src/libcore/str/mod.rs#L781-L782).

**Comment by Kimundi** [comment]
Its an issue with doc comments taken as an attribute in a macro. cc @kmcallister

**Comment by pyfisch** [comment]
Duplicate of #23812
