### ISSUE TITLE
`configure --enable-debug` sub options cannot be overridden

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#24416]
Spawned off of #24405.

`configure --enable-debug` will enable `CFG_ENABLE_LLVM_ASSERTIONS`, `CFG_ENABLE_DEBUG_ASSERTIONS`, `CFG_ENABLE_DEBUG_JEMALLOC`, 
and there is no way to turn them off.

The options `--disable-{llvm-assertions,debug-assertions,debug-jemalloc}` will all be silently ignored.

An analogous approach to that used by #24408 would probably work here.

But it might be better still to revisit how we are handling the option parsing in `configure` here, (for example, an invocation like `configure --enable-debug --disable-debug` has many potential interpretations, including emitting an error outright, but you might be surprised which one we choose under the current configure implementation).  The strategy of "ignore arguments that already match the default" seems like a big pitfall in the script.

**Comment by pnkfelix** [comment]
@brson points out also that:
> the fix (#24408) for that regression turns on --enable-optimize-cxx when `--enable-debug --enable-optimize`, while --enable-optimize alone does not imply --enable-optimize-cxx

So it would be good to address that too.

**Comment by pnkfelix** [comment]
part of #8058

**Comment by wthrowe** [comment]
I believe this issue is also causing `./configure --enable-optimize --disable-optimize` to give an optimized build.

Since the script interface is modeled after autoconf (same script name and argument forms) having different argument processing behavior than autoconf (where later options override earlier ones) is surprising.

**Comment by steveklabnik** [comment]
I believe this has now been fixed with `config.toml`:

```toml
# =============================================================================
# Tweaking how LLVM is compiled
# =============================================================================
[llvm]

# Indicates whether the LLVM build is a Release or Debug build
#optimize = true

# Indicates whether an LLVM Release build should include debug info
#release-debuginfo = false

# Indicates whether the LLVM assertions are enabled or not
#assertions = false
```

now all available separately. Closing! let me know if that's wrong.
