### ISSUE TITLE
Improve "no type for local variable" error when in check_const_with_ty 

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#24414]
The control flow for `rustc_typeck::check::check_const_with_ty` can end up spitting out an error of the form:

```
non-constant-expr-for-fixed-len-vec.rs:15:25: 15:26 error: no type for local variable 10
non-constant-expr-for-fixed-len-vec.rs:15         let _x: [isize; n];
```

With the compiler as it stands today, this is usually coupled with an error of the form:

``` rust
error: array length constant evaluation error: non-constant path in constant expr
```

but other changes being made may lead to _only_ the "no type for local variable" message being emitted.

We can do better here, e.g. by passing along knowledge that we are looking at a const-expr and then reporting that local variables simply are invalid within const-exprs.

**Comment by dgopstein** [comment]
Just received a lone `no type for local variable`. It's reproducible with the following program:

```rust
fn main() {
  let len: usize = 1;
  let arr: [char; len] = ['a'];
}
```

**Comment by pyk** [comment]
Any update for more informative error message? as described in #31082

**Comment by eddyb** [comment]
This is an outright bug, the correct behavior is for `len` to not pass name resolution.
Fixed on an in-progress branch, self-assigning for tracking.
