### ISSUE TITLE
Suggestion: assert pattern macro.

### ISSUE THREAD

**Issue by norcalli** [rust-lang/rust#24429]
```rust
macro_rules! assert_pattern {
    ($a:expr => $b:pat) => {
        assert!(match $a { $b => true, _ => false });
    }
}
```

Something like this would be useful for checking a pattern instead of deriving `Eq,PartialEq` for an enum.

**Comment by alexcrichton** [comment]
There's actually a crates on crates.io that does this already! https://crates.io/crates/matches

Right now we're also tracking new feature requests in the [RFC repo](https://github.com/rust-lang/rfcs), so if you feel that it still needs to be included in the stdlib by default, feel free to open an issue!

**Comment by alexcrichton** [comment]
Er, looks like there's already an issue!

https://github.com/rust-lang/rfcs/issues/264
