### ISSUE TITLE
Tracking issue for Std::iter::{once, empty} (RFC 771)

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#24443]
https://github.com/rust-lang/rfcs/pull/771

**Comment by aturon** [comment]
cc @XMPPwocky

**Comment by XMPPwocky** [comment]
Are you OK with just a PR?

**Comment by alexcrichton** [comment]
Sure!

**Comment by XMPPwocky** [comment]
Is it worth writing tests for this? I'm not really sure how it could break, but better safe than sorry I suppose...

**Comment by alexcrichton** [comment]
Yeah but just some simple tests would be fine to have

**Comment by Stebalien** [comment]
@XMPPwocky ping?

**Comment by XMPPwocky** [comment]
Working on it right now.

**Comment by Stebalien** [comment]
Thanks. I had some free time so I thought I'd check.
