### ISSUE TITLE
"transmute called on types with potentially different sizes" for zero-sized phantom data

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#24459]
```
use std::mem::transmute;
use std::marker::PhantomData;

fn main() {}
pub struct Thing<T> (PhantomData<T>);

pub unsafe trait HasDual {
    type Dual;
}

fn change<T: HasDual>(c: Thing<T>) -> Thing<T::Dual> {
    unsafe { transmute::<Thing<T>, Thing<T::Dual>>(c) }
}
```

On [compiling](http://is.gd/TI1OVh), we get:

```
<anon>:12:14: 12:51 error: transmute called on types with potentially different sizes: Thing<T> (could be 0 bits) to Thing<<T as HasDual>::Dual> (could be 128 bits)
<anon>:12     unsafe { transmute::<Thing<T>, Thing<T::Dual>>(c) }
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

However, struct `Thing<T>` is _always_ 0-sized.

This doesn't happen if the associated types are removed (Is it doing some trait object-esque magic here?)

**Comment by Manishearth** [comment]
cc @nikomatsakis

**Comment by Manishearth** [comment]
Note: This also happens when the struct has some substantial fields(which are all equal) followed by phantom data (which depends on the type param).

**Comment by laumann** [comment]
We have something like the following in our [rust-sessions](https://github.com/Munksgaard/rust-sessions/blob/master/src/lib.rs#L452-460) (session types in Rust) project (exactly the case @Manishearth describes in his last post)

```rust
struct Chan<P> = (Sender<Box<u8>>, Receiver<Box<u8>>, PhantomData<P>)

fn request<P, Q>(rx: Receiver<Chan<P>) -> Chan<Q> {
    unsafe { transmute(rx.recv().unwrap()) }
}
```
where we want to transmute from `P` to `Q`, both presumably zero-sized phantom types.

So far, we're able to work around it by destructuring the received `Chan` and creating a new one:
```rust
fn request<P, Q>(rx: Receiver<Chan<P>>) -> Chan<Q> {
    let Chan(tx, rx, _) = rx.recv().unwrap();
    Chan(tx, rx, PhantomData)
}
```

**Comment by steveklabnik** [comment]
This program successfully compiles today, so seems like this has been fixed.
