### ISSUE TITLE
Can't use crate with '-' in name, for [build-dependencies]

### ISSUE THREAD

**Issue by ceram1** [rust-lang/rust#24463]
I can't use some crates like 'rust-serialize' in [build-dependencies]
But 'phf_codegen' works.

Cargo.toml
```
[package]
build = "codegen/main.rs"

[dependencies]
rustc-serialize = "*"

[build-dependencies]
phf_codegen = "*"
rustc-serialize = "*"
```

```rust
extern crate rustc_serialize;
```
works in src/main.rs,

but
```rust
extern crate phf_codegen;
extern crate rustc-serialize;
```
in codegen/main.rs says
codegen/main.rs:2:19: 2:20 error: expected one of `;` or `as`, found `-`
codegen/main.rs:2 extern crate rustc-serialize;

and

```rust
extern crate phf_codegen;
extern crate rustc_serialize;
```
says
codegen/main.rs:2:1: 2:30 error: can't find crate for `rustc_serialize`
codegen/main.rs:2 extern crate rustc_serialize;

**Comment by nagisa** [comment]
This is a cargo issue. Please report it to https://github.com/rust-lang/cargo/issues/new

**Comment by nagisa** [comment]
I believe `extern crate something-with-hyphens` is not supposed to work and cargo is supposed to provide `rustc` with `--extern rustc_serialize=path-to-rlib.rlib`.

Generally, I’d guess this is a cargo issue, but it certainly needs more information to say for sure.

**Comment by alexcrichton** [comment]
@nagisa is right in that this is a Cargo issue, so could you report it against rust-lang/cargo instead? You may want to try making sure that your Cargo is up-to-date though as this sort of error can be indicative of an out-of-date Cargo (or rustc)

**Comment by ceram1** [comment]
Moved issue to rust-lang/cargo.
