### ISSUE TITLE
Traits section of Book references generics before they have been discussed

### ISSUE THREAD

**Issue by brettcannon** [rust-lang/rust#24470]
E.g., the [Our inverse Example](file:///Users/bcannon/Downloads/rust-nightly-x86_64-apple-darwin/rust-docs/share/doc/rust/html/book/traits.html#our-inverse-example) section talks about being "Back in Generics" even though Traits is section 5.21 and Generics is 5.23. There are couple of other places that mention generics in the section as if they have already been discussed.

**Comment by steveklabnik** [comment]
Thank you! I'm in the middle of doing a general editing pass, and I haven't gotten there yet. I'll be addressing this as I go.
