### ISSUE TITLE
Linkify more things in rustdoc

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#24484]
A page like [vec](http://doc.rust-lang.org/nightly/std/vec/struct.Vec.html#) has many things that could be useful to link to. These should be possible to link to by clicking on:
- [x] The `Trait Implementations` header
- [x] `impl`'s on a page.
- [x] `Methods` at the top

On [index](http://doc.rust-lang.org/nightly/std/ops/trait.Index.html) it's hit or miss:
- [x] Examples
- [x] Associated Types
- [x] Required Methods
- [x] Implementors

On [clone](http://doc.rust-lang.org/nightly/std/clone/trait.Clone.html)
- [x] Provided Methods

I don't have any big use cases but when I want to link to these for something like this bug I can't link to any specific line. I gotta say go to vec page, scroll 75% to bottom. Squint hard to see it.

**Comment by joshtriplett** [comment]
Just ran into this today; I'd really like to have links from the impls in the Implementors section to the source containing the impl.

**Comment by steveklabnik** [comment]
Triage: we always need more links....

**Comment by QuietMisdreavus** [comment]
Update: Headers written in docs and (most) auto-generated headers are either fully hyperlinked or have a "section marker" symbol that shows up on hover. Major auto-generated page headers have links in the top of the sidebar of the page. Impl blocks do not have hyperlinks (yet); that's https://github.com/rust-lang/rust/issues/23552.

**Comment by QuietMisdreavus** [comment]
Since https://github.com/rust-lang/rust/pull/43979 got merged and closed out https://github.com/rust-lang/rust/issues/23552, that was the last major request on this issue, so i'll close this out. If you think of something else that needs a hyperlinked header, feel free to open a new issue or reopen this one.
