### ISSUE TITLE
Rustdoc broken hyperlinks

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust#24486]
I've come across quite a few broken links just while browsing the online documentation generated by rustdoc (particularly when clicking on links from search results). There are already issues relating to specific cases, but perhaps there should be a catch-all test on the output of rustdoc to check that all generated hyperlinks are valid?

**Comment by steveklabnik** [comment]
> perhaps there should be a catch-all test on the output of rustdoc to check that all generated hyperlinks are valid?

The problem with things like this is that services that go down then break your build. We did this for Rust By Example, but then a bad deploy caused the whole site to 404, and we couldn't bring it back up because the site was 404'ing :wink: 

Specific cases should be looked into, and bugs should get filed, for sure, but running checks like this takes about an hour and a half, I've done it with linkchecker.

**Comment by Diggsey** [comment]
I was thinking more of something which ran on the files offline - it can ignore external urls, but just check that internal urls point to a file that was actually generated. That wouldn't be affected by anything outside the current build.

**Comment by jakub-** [comment]
Also, rather than using `linkchecker`, which – as @steveklabnik is saying – usually is not an expedient process, we could have `rustdoc` record all the URLs produced when generating the HTML and then validate them against the directory structure.

**Comment by nathanl** [comment]
One example: From http://doc.rust-lang.org/1.0.0-beta/book/hello-world.html

>>>
We provide some sample configurations for various editors.
>>>

Link is broken.

**Comment by steveklabnik** [comment]
That's due to a Rustdoc... Mis-feature, for which we already have a bug open.

**Comment by chris-code** [comment]
Another instance of a broken link is found in
https://doc.rust-lang.org/stable/book/the-stack-and-the-heap.html

It says
> If you’d like to dive into this topic in greater detail, this paper is a great introduction.

where 'this paper' is a dead link to
http://www.cs.northwestern.edu/~pdinda/icsclass/doc/dsa.pdf

**Comment by steveklabnik** [comment]
So, I'm going to give this bug a close. If there are specific things that are causing `rustdoc` to generate invalid links, they should be filed as bugs, and if there are specific, manually linked links that are wrong, they should have a bug, but I don't see under what conditions this bug will ever get closed.
