### ISSUE TITLE
Rustdoc problem with lifetimes

### ISSUE THREAD

**Issue by iopq** [rust-lang/rust#24503]
http://webcache.googleusercontent.com/search?q=cache:ufyF2_8E4hUJ:doc.rust-lang.org/1.0.0-alpha.2/std/string/type.CowString.html+&cd=2&hl=en&ct=clnk&gl=us

Using a single apostrophe breaks the tag:

```
<a class='stability Deprecated' title='use Cow<'a, str> instead'>Deprecated</a>
```

as you can see, the title is `use Cow<` and the rest is malformed HTML

**Comment by alexcrichton** [comment]
Thanks for the report! This should be fixed by https://github.com/rust-lang/rust/pull/24396, however, as the way we render descriptions will be changing.
