### ISSUE TITLE
Standardize on either 'upper_case' or 'uppercase'

### ISSUE THREAD

**Issue by nstoddard** [rust-lang/rust#24536]
The standard library uses names like `to_uppercase`, while there's a warning with the name `non_upper_case_globals`. One of these should be changed, for consistency. (There may be other instances of this inconsistent naming - I haven't checked.)

It would be a breaking change to change functions like `to_ascii_uppercase`, but renaming `non_upper_case_globals` to `non_uppercase_globals` should only result in more warnings, so it doesn't seem like a breaking change.

**Comment by steveklabnik** [comment]
Naming conventions are covered by https://github.com/rust-lang/rfcs/blob/master/text/0430-finalizing-naming-conventions.md,

**Comment by steveklabnik** [comment]
Oh, you literally mean one or two words for 'upper case,' _not_ when things should be upper vs lower case. Sorry about that!

**Comment by SimonSapin** [comment]
`char::to_uppercase` is `#[stable]` and so can not be removed in 1.x. Deprecating it in favor of renamed method doesn’t seem worth it.

I don’t know if renaming the attribute is considered a breaking change.

**Comment by soderstroff** [comment]
Is this issue still relevant? I think the warning mentioned is stabilized and changing it would break existing code that uses it.

**Comment by steveklabnik** [comment]
Yes, I don't think that this particular thing is actionable nowadays. Such is life! Hopefully these are the worst things we regret in the future :)
