### ISSUE TITLE
Buildbot may test the wrong commit

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#24531]
If a build is cancelled too soon, it may send a kill signal to a `git` process early on in the `git clone` step of buildbot. This will in turn leave the `.git/index.lock` file lying around, causing all future invocations of `git` to fail.

Subsequent builds then fail to update the repository, and all future builds end up running tests for the previous revision that was checked out into the local directory. This may cause an endless string of failures or false positives.

There are two problems at play here:
- [ ] Buildbot should notice when the git update failed, and probably fail the whole build instead of allowing it to continue
- [ ] Killing a build too soon should not corrupt the git folder

**Comment by pnkfelix** [comment]
cc me

**Comment by steveklabnik** [comment]
Triage: I am not aware of any changes here.

**Comment by edunham** [comment]
Help wanted: Research whether there's a Git command to test integrity of repo and detect that a clone or update was aborted haldway through.

**Comment by zofrex** [comment]
As I understand it, it's safe to kill Git operations and it won't leave the local repo in a corrupted state. I think all that needs to happen on that front is deleting the lock file?

**Comment by edunham** [comment]
@zofrex That's consistent with my own experiences fixing Buildbot when it got into this state; I have nuked the lock file and then everything was back to normal.

**Comment by zofrex** [comment]
My proposed plan of action, then:

- [ ] Triple-check that there's no way that parallel invocations of git could occur (otherwise blindly deleting the lock file seems like a bad idea)
- [ ] Delete .git/index.lock if it exists
- [ ] Fail the build if git operations return non-zero (best practice regardless of anything else)

**Comment by alexcrichton** [comment]
buildbot's on its way out, so closing
