### ISSUE TITLE
Cannot mutably borrow inside a match guard

### ISSUE THREAD

**Issue by Binero** [rust-lang/rust#24535]
I understand this shouldn't be possible in some occasions, because you might be able to modify what you're matching, which can cause the match to break. Why would it be disallowed to mutably borrow something that only exists within the match though? 

```rust
fn main() {
    let a = 3u8;
    
    match a {
        0 => (),
        3 if compare(&a, &mut 3) => (),
        _ => (),
    }
}

fn compare(a: &u8, b: &mut u8) -> bool {
    a == b
}
```
http://is.gd/yuIFGc

I have constructed this minimal case. In my actual code I am running `.iter().any()` on a variable form outside the match, which isn't allowed because `.any()` requires a mutable borrow. As the thing I am mutably borrowing only exists within the match, this makes even less sense to me.

Compiler bug?

**Comment by asQuirreL** [comment]
Hi @Binero, I actually solved your use case like so: http://is.gd/ffFhbA by using `.contains(...)` instead of your `.iter().any()`.

**Comment by Binero** [comment]
This certainly is a nice fix (and probably how it should've been done in the first place), however I still feel like this should be possible.

**Comment by steveklabnik** [comment]
Changing `match` in this way would require an RFC, I would believe, as it's a pretty significant change, and would need to be well-thouht-out for soundness reasons. You should open an RFC issue instead. Thanks!
