### ISSUE TITLE
Confusing error message when you attempt to build for a target that rustc isn't prepared for

### ISSUE THREAD

**Issue by posix4e** [rust-lang/rust#24544]
I am trying to build rustboot

rustc -O --target i686-unknown-linux-gnu --crate-type lib -o main.o --emit obj main.rs

Get's 
te-type lib -o main.o --emit obj main.rs
main.rs:7:1: 7:19 error: can't find crate for `core`
main.rs:7 extern crate core;
          ^~~~~~~~~~~~~~~~~~

The actual error should tell you that you are trying to build for a target that rustc can't handle.

**Comment by brson** [comment]
Fixed.
