### ISSUE TITLE
Make `lifetime` a keyword

### ISSUE THREAD

**Issue by P1start** [rust-lang/rust#24549]
The [associated items RFC](https://github.com/rust-lang/rfcs/blob/master/text/0195-associated-items.md) adds the ability to declare associated lifetimes using the `lifetime` keyword. Presumably this would require adding `lifetime` as a keyword.

**Comment by kballard** [comment]
Technically, we could get away with making it a contextual keyword, only treating it specially within a `trait` or `impl` block. We don't currently have any precedent for contextual keywords, although it's been suggested a number of times in the past for various things.

**Comment by P1start** [comment]
There could be some more uses for `lifetime`, though. In particular, I’m thinking of an HKT-like extension to the language where traits can be for arbitrary kinds, including lifetimes. So something like the following could be valid:

```rust
trait NotStatic for lifetime {}

impl NotStatic for .. {}
impl !NotStatic for 'static {}
```

Or perhaps the kind signature for a type like `struct Foo<'a>` would be `type<lifetime>`. These all might seem to work fine with `lifetime` as a contextual keyword, but it falls apart when you allow things like user-defined kinds.

I’m honestly not super fussed about whether `lifetime` ends up as a normal keyword or not (most other uses of it would probably be 2.0.0+ features anyway), but I’d certainly rather an explicit decision be made about it than a decision to make it a contextual keyword being implicitly made through indecision.

**Comment by steveklabnik** [comment]
Nominating, as this seems important for backcompat reasons.

**Comment by pnkfelix** [comment]
The plan of record is for some sort of scheme for contextual keywords in some form.  We'll figure it out after 1.0, but we do not need to make this change before 1.0.

Closing.
