### ISSUE TITLE
Linking to external libraries on Windows requires two copies of the libraries in different directories

### ISSUE THREAD

**Issue by nstoddard** [rust-lang/rust#24540]
On Windows 64-bit, the linker looks for DLLs in `bin\x86_64-pc-windows-gnu`. However, when running the program, either with `cargo run` or running it directly, it doesn't look there, and instead looks for the DLLs in the project's base directory as well as the directories in your PATH. As a result, you need to include two copies of each DLL, one in each location.

It would be nice if it would always look for the DLLs in `bin\x86_64-pc-windows-gnu`, in order to avoid having to pollute the project's base directory with DLLs. Unfortunately I'm not familiar with how Windows looks for DLLs, so I don't know how difficult this would be to implement.

**Comment by steveklabnik** [comment]
I _believe_ this is a Cargo issue, not really a `rustc` issue, yeah? /cc @alexcrichton

**Comment by alexcrichton** [comment]
This one reason why the compiler favors static linkage by default. Unfortunately there's no way for rustc to inject a path into each binary on Windows, so you'll have to set up your PATH environment variable appropriately before running executables if they're dynamically linked.

For most usage the dlls in the same folder as `rustc.exe` will suffice, so if `rustc.exe` is in your PATH then everything but plugins should work out ok as well.

**Comment by alexcrichton** [comment]
I'm not certain that this is a Cargo issue, though. @nstoddard can you be more specific in how this problem arises and what triggers it?

**Comment by nstoddard** [comment]
I'll use GLFW as an example. I have a program which uses [glfw-rs](https://github.com/bjz/glfw-rs), which requires linking with `glfw3.dll`. If I put this DLL in my project's base directory (alongside `Cargo.toml`), the linker doesn't find it and I get this error:

```
error: linking with `gcc` failed: exit code: 1
note: "gcc" "-Wl,--enable-long-section-names" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-static-libgcc" "-m64" "-L" "C:\Rust\bin\rustlib\x86_64-pc-windows-gnu\lib" "-o" <lots of rlibs and irrelevant stuff>  "-L" "C:\Users\Nathan\Desktop\code\image-viewer\target\release" "-L" "C:\Users\Nathan\Desktop\code\image-viewer\target\release\deps" "-L" "C:\Users\Nathan\Dropbox\code\in-progress\image-viewer\target\release\build\time-15ec407cfcd2d643\out" "-L" "C:\Rust\bin\rustlib\x86_64-pc-windows-gnu\lib" "-L" "C:\Users\Nathan\Desktop\code\image-viewer\.rust\bin\x86_64-pc-windows-gnu" "-L" "C:\Users\Nathan\Desktop\code\image-viewer\bin\x86_64-pc-windows-gnu" "-Wl,--whole-archive" "-Wl,-Bstatic" "-Wl,--no-whole-archive" "-Wl,-Bdynamic" "-lglfw3" "-lopengl32" "-lgdi32" "-lfreetype-6" "-lws2_32" "-luserenv" "-lcompiler-rt"
note: ld: cannot find -lglfw3
ld: cannot find -lfreetype-6
```

It appears that the base directory isn't included in a `-L` flag. Looking at those flags, there's a few places where the linker looks for DLLs, and the best one to use seems to be `bin\x86_64-pc-windows-gnu`, as most of the others would require putting the DLLs in the Rust installation directory, which doesn't seem like a good idea.

The problem is, once I move `glfw3.dll` to `bin\x86_64-pc-windows-gnu`, the linking works but the program doesn't start, and I get this error:

```
The program can't start because glfw3.dll is missing from your computer. Try reinstalling the program to fix this problem. 
```

I need to put another copy of `glfw3.dll` somewhere the program can find it at runtime, and for development the easiest choice is the project's base directory.

I'm not sure whether this is a rustc issue or a Cargo issue. Which one chooses which `-L` flags to pass to the linker?

There's a few possible solutions to this. One solution would be to pass a `-L` flag for the project's base directory. However, that would require you to pollute the base directory with DLLs, and may lead to problems if you have 32-bit and 64-bit versions of the DLLs.

Another option would be for `cargo build` and other cargo commands to copy all libraries found in `bin\x86_64-pc-windows-gnu` (and related directories, for 32-bit windows and such) to `target\debug` or `target\release`. This seems like the best option to me, if the copying process doesn't take too long; could symlinks be used instead of actually copying the files? This would allow you to put all your DLLs in one place, and things would just work.

**Comment by retep998** [comment]
On Windows linking should actually only need to be done to a `.lib` or a `.a`, not to a `.dll` directly. You'd have all your `.a` libraries in a location visible to rustc at compile time, while the `.dll`s would be somewhere visible to the binary at run time.
Cargo build scripts let you specify directories to look in for libraries. http://doc.crates.io/build-script.html#outputs-of-the-build-script

**Comment by alexcrichton** [comment]
This primarily sounds like a problem glfw-rs would want to solve rather than Cargo or the compiler. Cargo probably won't be copying dlls into each output folder, and symlinks require admin privileges by default on Windows. The build script support @retep998 linked to also allows for local overrides where you can [globally inform Cargo](http://doc.crates.io/build-script.html#overriding-build-scripts) where `glfw3.dll` is located which will then cause it to pick it up at both compile-time and runtime.

In general though this is just an aspect of Windows that Cargo and the compiler help to solve but won't solve altogether. @retep998 is correct in that dealing with static libraries is generally much easier to do as there's no runtime dependency on the DLL. Otherwise you'll just need to make sure that the DLL is in your PATH at runtime and there's a build script or override to inform Cargo where it is at compile time.
