### ISSUE TITLE
No longer possible to add numbers without libcore?

### ISSUE THREAD

**Issue by thesam** [rust-lang/rust#24550]
Hi!

I have a fork of rustboot which I try to keep up to date with the latest rust releases. Lately, I have run into an issue with the basic operators, for example using '+' to add two numbers. This used to work before without libcore, but I guess something has changed? 
```
#![feature(no_std)]
#![feature(lang_items)]
#![no_std]

#[lang="phantom_fn"]
trait PhantomFn<A: ?Sized, R: ?Sized = ()> {}

#[lang="sized"]
trait Sized: PhantomFn<Self> {}

fn main() {
    let x = 1 + 1;
}
```
Output:
```
$ rustc main.rs 
main.rs:12:13: 12:14 error: binary operation `+` cannot be applied to type `_` [E0369]
main.rs:12     let x = 1 + 1;
                       ^
error: aborting due to previous error
```

**Comment by steveklabnik** [comment]
You need to define the `add` lang item if you're not using libcore.
