### ISSUE TITLE
Consider adding a .foreach()-like method to Iterator

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#24566]
Proposed in https://github.com/rust-lang/rfcs/pull/582 and https://github.com/rust-lang/rfcs/pull/1064, the `Iterator` trait could have a `.foreach` method which drains the iterator immediately and runs a closure on each element to concisely do so without a `for` loop.

**Comment by steveklabnik** [comment]
should be over here instead: https://github.com/rust-lang/rfcs/issues/1070

**Comment by alexcrichton** [comment]
Oh oops! I meant for this to be in rust-lang/rfcs but wasn't paying attention...
