### ISSUE TITLE
File does not implement Debug

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#24570]
All types should, but it doesn't:

```
the trait `core::fmt::Debug` is not implemented for the type `std::fs::File` [E0277]
```

**Comment by sfackler** [comment]
We can easily slap one on that just prints the file descriptor/HANDLE, but it would ideally include the path of the open file. It looks like it'll be a bit of a pain to get.

Windows can get it via either [`GetFinalPathNameByHandle`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364962(v=vs.85).aspx) or [`GetFileInformationByHandleEx`](https://msdn.microsoft.com/en-us/library/aa364953(VS.85).aspx). It does look like both of those require Vista, but this page has a workaround for earlier versions of Windows: https://msdn.microsoft.com/en-us/library/windows/desktop/aa366789%28v=vs.85%29.aspx.

OSX can grab it by passing `F_GETPATH` to `fnctl`: https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man2/fcntl.2.html.

Looks like Linux may have to poke around in `/proc/self/fds/` unfortunately.

**Comment by sfackler** [comment]
It'd also be nice to print if the file's writable or read only.

**Comment by lfairy** [comment]
On Linux, you can read the link at `/proc/self/fd/<FD>`. The destination of that symlink is the name of the file.

That shouldn't be too hard, given that we have a [`read_link`](http://doc.rust-lang.org/nightly/std/fs/fn.read_link.html) function in `std`.

**Comment by lfairy** [comment]
I'm working on this.

**Comment by nagisa** [comment]
relying on procfs is bad, because it may not be mounted or be mounted at a non-standard location.

**Comment by lfairy** [comment]
@nagisa We aren't really relying on it here. If `/proc` isn't present, the code would just not print a path. No biggie.

**Comment by lfairy** [comment]
Currently the `Debug` impl gives path and access mode information on Linux only.

If anyone wants to flesh out the Windows or OS X or BSD code, then feel free.

**Comment by steveklabnik** [comment]
```
use std::fs::File;

fn main() {
    let f = File::open("hello.rs");
    println!("{:?}", f);
}
```

prints

```
Ok(File { fd: 3, path: "/home/steve/tmp/hello.rs", read: true, write: false })
```

**Comment by Eh2406** [comment]
There is a FIXME related to this issue,
https://github.com/rust-lang/rust/blob/master/src/libstd/sys/windows/fs.rs#L445
Now that the issue is closed can the FIXME be fix, or made more specific?
