### ISSUE TITLE
pretty printer ICE on large const-expr summation

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#24579]
(imported from improperly closed bug #17406)

This code:

``` rust
static I104: int =
    0 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1
        + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 +
        1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1
        + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 +
        1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1
        + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1;

fn main() {
}
```

when I hit the "format" button in the [playpen](http://is.gd/2Y1VHZ) (which I assume just calls `rustc -Z unstable-options --pretty`), it ICEs.

**Comment by pnkfelix** [comment]
(the new playpen doesn't have a format button anymore ...)

**Comment by pnkfelix** [comment]
Here is a way to emulate the problem in the playpen nonetheless (by creating the file in question and manually invoking rustc's pretty-printer to expose the ICE): http://is.gd/OF0lBs

**Comment by pmarcelll** [comment]
Triage: I can't reproduce it.

**Comment by Mark-Simulacrum** [comment]
Cannot reproduce -- closing.
