### ISSUE TITLE
Rustdoc inlined Deref impls should not include static methods.

### ISSUE THREAD

**Issue by Stebalien** [rust-lang/rust#24575]
As of #24396, rustdoc inlines Deref impls (:smiley:). However, static methods are also included. Static methods probably shouldn't be included as they can't be called through Deref. They also appear to mess with search results.

**Comment by aochagavia** [comment]
What about methods that take `&mut self`? Should we hide those too?

**Comment by alexcrichton** [comment]
@aochagavia nah I think including those is fine because they are applicable to a `DerefMut` implementation. In theory the "most correct" thing to do would be to detect whether `DerefMut` is implemented or not but it's also fine to not do that for now.
