### ISSUE TITLE
Build fails on MSYS2

### ISSUE THREAD

**Issue by killkrt** [rust-lang/rust#24574]
Hi,

I've installed MSYS2 on a clean installation of Windows 7 SP1 64bit, installed the building tool chain as described in the guide (that is mingw-w64-x86_64-toolchain and base-devel), but the configure script fails with the following error:

```
configure: error: unsupported target triples "x86_64-pc-windows-gnu" found
```

This is the full output:
```
configure: looking for configure programs
configure: found program cmp
configure: found program mkdir
configure: found program printf
configure: found program cut
configure: found program head
configure: found program grep
configure: found program xargs
configure: found program cp
configure: found program find
configure: found program uname
configure: found program date
configure: found program tr
configure: found program sed
configure: found program file
configure: found program make
configure: inspecting environment
configure: recreating config.tmp
configure:
configure: processing ./configure args
configure:
configure: CFG_LOCALSTATEDIR    := /var/lib
configure: CFG_SYSCONFDIR       := /etc
configure: CFG_DATADIR          := /share
configure: CFG_INFODIR          := /share/info
configure: CFG_LLVM_ROOT        :=
configure: CFG_JEMALLOC_ROOT    :=
configure: CFG_BUILD            := x86_64-pc-windows-gnu
configure: CFG_ANDROID_CROSS_PATH := /opt/ndk_standalone
configure: CFG_RELEASE_CHANNEL  := dev
configure: CFG_BUILD            := x86_64-pc-windows-gnu
configure: CFG_LIBDIR           := /usr/local/bin
configure:
configure: validating ./configure args
configure:
configure: CFG_BOOTSTRAP_KEY    := 00:27:07
configure:
configure: looking for build programs
configure:
configure: CFG_CURLORWGET       := /mingw64/bin/curl (7.41.0)
configure: CFG_PYTHON           := /mingw64/bin/python2.7
./configure: line 691: [: /home/Kill: binary operator expected
configure: CFG_GIT              := /usr/bin/git (2.3.5)
configure: CFG_CLANG            :=
configure: CFG_CCACHE           :=
configure: CFG_GCC              := /mingw64/bin/gcc (5,)
configure: CFG_LD               := /mingw64/bin/ld (2.25)
configure: CFG_VALGRIND         :=
configure: CFG_PERF             :=
configure: CFG_ISCC             :=
configure: CFG_ANTLR4           :=
configure: CFG_GRUN             :=
configure: CFG_FLEX             := /usr/bin/flex (2.5.39)
configure: CFG_BISON            := /usr/bin/bison (3.0.4)
configure: CFG_PANDOC           :=
configure: CFG_XELATEX          :=
configure: CFG_GDB              := /mingw64/bin/gdb (7.6.2)
configure: CFG_LLDB             :=
configure: CFG_GDB_VERSION      := GNU gdb (GDB) 7.6.2
configure:
configure: looking for target specific programs
configure:
configure: CFG_ADB              :=
configure: CFG_CC               := gcc
configure: error: unsupported target triples "x86_64-pc-windows-gnu" found
```

**Comment by killkrt** [comment]
I think the problem is that my home folder name contains spaces. MSYS2 creates the home folder using the user name from Windows (that in my case contains spaces).
I think the issue could be fixed easily putting double quote in the right place in the configure script. I'll make a test and then make a pull request.

**Comment by bombless** [comment]
Hmm did you run with  mingw64_shell.bat or in cmd.exe?

**Comment by killkrt** [comment]
I ran with mingw64_shell.bat, anyway I noticed that also the LLVM configure script has the same issue... I'm starting to think to change the home folder name...

**Comment by killkrt** [comment]
Ok... I have changed my home folder name (removing the space) and the build worked, but now I'm getting another problem. It seems the carriage return is completely messed up in the MSYS2 shell:

![screen shot 2015-04-19 at 18 46 18](https://cloud.githubusercontent.com/assets/4274153/7220353/70c689f8-e6c4-11e4-899b-203bacd761fb.png)

**Comment by bombless** [comment]
Did you download MSYS2 from http://sourceforge.net/projects/msys2/ , as https://github.com/rust-lang/rust-wiki-backup/blob/master/Note-getting-started-developing-Rust.md suggests?

**Comment by killkrt** [comment]
Uhm... I downloaded from here: http://msys2.github.io
So I will revert my virtual machine and try again!

**Comment by bombless** [comment]
Ah, nvm, they lead to the same URL anyway.

**Comment by Diggsey** [comment]
The newline problem has been fixed in msys2 now. Updating msys2 via pacman is enough to solve the problem.

**Comment by alexcrichton** [comment]
Sounds like this may be working now with a recent MSYS2, so closing.
