### ISSUE TITLE
Don't allow array types in extern "C" functions.

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#24578]
(imported from improperly closed bug #16221)

You cannot pass an array to or return an array from a C function. 
The signature `f(char x[N])` is equivalent to `f(char *x)` for every `N` in C.  Therefore it is meaningless to write this in Rust, (or rather, it does not mean what a C programmer and/or FFI generation tool likely thinks it means):

```
    extern "C" fn f(x: [i32, ..4]); // void f(int x[4])
```

Option for dealing with this:
- We can extend our existing lint to detect cases like this and warn about them.
- We could make the `extern "C" fn` form reject this signature, since the expected correspondence between Rust and C does not hold here.
- If the Rust FFI binding generation scripts/programs out there are generating this sort of code, they need to be fixed.

**Comment by pnkfelix** [comment]
triage: P-low

**Comment by steveklabnik** [comment]
Triage: array syntax has changed, here's the correct syntax:

```
extern {
    fn f(x: [i32; 4]);
}

fn main() {}
```

no warning or anything.

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by estebank** [comment]
This would have to be implemented as a lint now due to the potential of breaking existing builds. It should be easy enough to implement.
