### ISSUE TITLE
rustc crash when #[no_mangle] function is declared multiple times with different signatures.

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#24583]
(imported from improperly closed bug #18358)

```rust
#![allow(dead_code)]

pub mod x {
    #[no_mangle]
    pub fn f() { }
}

pub mod y {
    #[no_mangle]
    pub fn f(_: i32) { }
}

fn main() { }
```

[playpen](http://is.gd/SCMl71)

This crashes with:
```
rustc: /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/include/llvm/Support/Casting.h:237: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::Function; Y = llvm::Value; typename llvm::cast_retty<X, Y*>::ret_type = llvm::Function*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
Aborted (core dumped)
playpen: application terminated with error code 134
Program ended.
```

(I don't know what it does if one compiles about LLVM assertions turned on.)

**Comment by nagisa** [comment]
This doesn’t crash anymore. 

```
test.rs:10:5: 10:25 error: symbol `f` is already defined
test.rs:10     pub fn f(_: i32) { }
               ^~~~~~~~~~~~~~~~~~~~
```

**Comment by pnkfelix** [comment]
@nagisa it currently crashes in the playpen, set to "Nightly" ... are you saying its been fixed since the last nightly, but the PR didn't reference this ticket?

**Comment by nagisa** [comment]
@pnkfelix cases like these are errors (or ICEs, like in https://github.com/rust-lang/rust/issues/24561) since #23011.

I think playpen’s nightly might be outdated.

**Comment by alexcrichton** [comment]
I think @nagisa is right, I get an error on the most recent nightly, co closing. I'll investigate what's up with playpen.
