### ISSUE TITLE
Unstable functions can't be collapsed in rustdoc

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang/rust#24593]
This may have been intentional (as to not hide the "unstable" marking when everything is collapsed), but it's still annoying.

![2015-04-18-210637_684x367_scrot](https://cloud.githubusercontent.com/assets/667901/7218104/d24849fc-e60e-11e4-9c8b-21740a0d980b.png)

I would suggest that the collapsed state could have an indication of the function's instability. Perhaps collapsing a function's description would not hide the unstability marker.

**Comment by liigo** [comment]
It was fixed by PR https://github.com/rust-lang/rust/pull/24717 (commit: https://github.com/liigo/rust/commit/76a590d0ef15506ed805a943b3a19ce65651903f)
