### ISSUE TITLE
need more libc consts bindings in liblibc

### ISSUE THREAD

**Issue by doomsplayer** [rust-lang/rust#24607]
As #24594 , we need `IPPROTO_TCP` and `TCP_KEEPALIVE` at least to merge this PR successfully.
So, are there any document for category convention of liblibc? I would like to help but dunno which mod owns `IPPROTO_TCP` and `TCP_KEEPALIVE`, and anything else.

**Comment by alexcrichton** [comment]
Unfortunately this isn't quite an actionable bug as we're probably not going to scour each system to ensure we have an exhausting listing of all constants. We generally add values to liblibc in an on-demand fashion instead of having an issue-per constant, so I'm going to close this for now.
