### ISSUE TITLE
several tests fails with check-stage3-rpass-full and not with check-stage2-rpass-full

### ISSUE THREAD

**Issue by semarie** [rust-lang/rust#24609]
Doing testing at stage3 under openbsd, I have several failures in rpass-full that I don't have at stage2 (all tests pass at stage2).

In order to debug, I have test it under Linux, and I reproduce theses issues. All errors below come from Linux using `make check-stage3-rpass-full` (configure options are just `--disable-docs` and `--disable-valgrind-rpass`) .

```
failures:
    [run-pass] run-pass-fulldeps/derive-totalsum.rs
    [run-pass] run-pass-fulldeps/issue_16723_multiple_items_syntax_ext.rs
    [run-pass] run-pass-fulldeps/lint-group-plugin.rs
    [run-pass] run-pass-fulldeps/lint-plugin-cmdline-allow.rs
    [run-pass] run-pass-fulldeps/lint-plugin-cmdline-load.rs
    [run-pass] run-pass-fulldeps/lint-plugin.rs
    [run-pass] run-pass-fulldeps/macro-crate-does-hygiene-work.rs
    [run-pass] run-pass-fulldeps/macro-crate.rs
    [run-pass] run-pass-fulldeps/mbe_matching_test_macro.rs
    [run-pass] run-pass-fulldeps/plugin-args-1.rs
    [run-pass] run-pass-fulldeps/plugin-args-2.rs
    [run-pass] run-pass-fulldeps/plugin-args-3.rs
    [run-pass] run-pass-fulldeps/plugin-lib-ok-in-plugin.rs
    [run-pass] run-pass-fulldeps/plugin-plus-extern-crate.rs
    [run-pass] run-pass-fulldeps/roman-numerals-macro.rs
    [run-pass] run-pass-fulldeps/syntax-extension-with-dll-deps.rs

test result: FAILED. 14 passed; 16 failed; 1 ignored; 0 measured
```

The failures seems mainly related to plugins.
Errors messages are kind of:
- `error: macro undefined`
- `error:`derive`may only be applied to structs and enums`

And there are some ICE too:
- `thread 'rustc' panicked at 'fold converted a module to not a module'`
- `thread '<unnamed>' panicked at 'index out of bounds: the len is 60 but the index is 68'`

The main difference between stage2 and stage3 is `-C prefer-dynamic` option.

**Comment by semarie** [comment]
@steveklabnik I am not agreed about A-bsd flag: it is reproductible under Linux. Please note there are also several ICE generated. Thanks to review the labels.

**Comment by steveklabnik** [comment]
@semarie ah, you're right, thanks! I was going through it quickly, and mis-read. Fixed!

**Comment by semarie** [comment]
I have run a bisect in order to have some informations.
the `check-stage3-rpass-full` target start failing with 50f4a0ec7458a4c14d4814cc71b289bf12b5ce6b (more than one year ago), with the introduction of `macro-crate` test in `run-pass-fulldeps`.

so basically it say (if I understand well) that macro export don't work with rustc stage3.

**Comment by wesleywiser** [comment]
Just ran into this on OS X

**Comment by alexcrichton** [comment]
Make's now gone, so closing.
