### ISSUE TITLE
librustc_data_structures missing from 2015-04-19 nightly

### ISSUE THREAD

**Issue by apasel422** [rust-lang/rust#24603]
```sh
> rustc
rustc: error while loading shared libraries: librustc_data_structures-4e7c5e5c.so: cannot open shared object file: No such file or directory
```

**Comment by alexcrichton** [comment]
I believe this library is indeed inside the tarball, perhaps `LD_LIBRARY_PATH` for you isn't set up?

**Comment by apasel422** [comment]
Hmm. This was the first time that `sudo ./rustup --channel=nightly` didn't just work. Let me see.

**Comment by alexcrichton** [comment]
On some systems you may also need to run `sudo ldconfig` I believe, and I think rustup accidentally stopped doing that recently?

**Comment by apasel422** [comment]
That did the trick. Thanks!

**Comment by nrc** [comment]
I got bit by this just now too. Is there an issue/fix to make rustup do the `ldconfig` step again?

**Comment by alexcrichton** [comment]
@nrc I believe that's covered by https://github.com/rust-lang/rust/issues/24358
