### ISSUE TITLE
Rustdoc should show both a stability colour, and unstable/deprecation text

### ISSUE THREAD

**Issue by thepowersgang** [rust-lang/rust#24617]
While the recent change to make deprecated items more obvious is nice, the lack of colour annotations makes it harder to scan down a list (e.g. in trait impls) and spot stable/unstable items.

Could the colours be restored (along side the new warning boxes)?

**Comment by steveklabnik** [comment]
One of the reasons the colors were bad was color-blind users...

**Comment by thepowersgang** [comment]
Understandable. As said, I just think the colours (and maybe symbols?) should return along side the new text boxes. For easier scanning (and inclusion alongside the prototypes)

**Comment by alexcrichton** [comment]
The idea here is that the set of unstable/deprecated items is actually pretty small, so there doesn't need to be that much visual distinction, but I'd certainly believe that the UI could be better.

**Comment by steveklabnik** [comment]
We no longer have colors, and we do display a message for unstable/deprecated things. Closing!

**Comment by steveklabnik** [comment]
Well, I guess this ticket was about adding them back in, so let's leave this open just in case. @thepowersgang with all of the changes here, do you still think we could do better?

**Comment by steveklabnik** [comment]
Okay, it's been a while; I'm going to give this one a close. If someone feels strongly about it and has a proposal for today's situation with regards to stability markers, please open a new issue. Thanks!
