### ISSUE TITLE
Default for AtomicPtr?

### ISSUE THREAD

**Issue by njwhite** [rust-lang/rust#24613]
Is there any reason why there isn't an `ATOMIC_PTR_INIT` (cf `ATOMIC_BOOL_INIT`, `ATOMIC_ISIZE_INIT`, &c.) struct? I'd like to use AtomicPtrs in statically-initialized variables - and `AtomicPtr` is the only atomic class that doesn't implement the `Default` trait. A std::ptr::null_mut() seems to be a sensible initial value.

**Comment by sfackler** [comment]
You can't define generic consts so `ATOMIC_PTR_INIT` can't be expressed. We can add a `Default` implementation though.
