### ISSUE TITLE
Mismatched assumptions for interaction between associated type and lifetime in trait

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#24622]
```rust
pub trait Foo<'a> {
    type Bar: std::fmt::Debug;
    fn baz(&'a self) -> Self::Bar;
}

pub struct X {
    name : String,
}

impl<'a> Foo<'a> for X {
    type Bar = &'a String;
    fn baz(&'a self) -> &'a String {
        &self.name
    }
}

pub fn foo<T: for<'a> Foo<'a>>(x: T) {
    let y = x.baz();
    drop(x);
    // for T = X, this is a &String pointing to dropped memory
    println!("{:?}", y); 
}

pub fn main() {
    foo(X { name: "foo".to_string() });
}
```

This segfaults.

The `impl` is allowing `&'a String` because `'a` is in scope, but the use in `foo` assumes that `Bar` is independent of `'a`.

(Noticed in http://stackoverflow.com/q/29745134/1256624 .)

**Comment by huonw** [comment]
triage: P-high

cc @nikomatsakis

**Comment by bluss** [comment]
petgraph uses this kind of trait to provide generic "neighbor vertex" iterators.

**Comment by arielb1** [comment]
I think a cleaner example is:

```Rust
pub trait Foo<'a> {
    type Bar;
}

impl<'a, T> Foo<'a> for T { type Bar = &'a T; }

fn denormalise<'a, T>(t: &'a T) -> <T as Foo<'a>>::Bar {
    t
}

pub fn free_and_use<T: for<'a> Foo<'a>,
                    F: for<'a> FnOnce(<T as Foo<'a>>::Bar)>(x: T, f: F) {
    let y;
    'body: loop { // lifetime annotations added for clarity
        's: loop { y = denormalise(&x); break }
        drop(x);
        return f(y);
    }
}

pub fn main() {
    free_and_use("foo".to_string(), |s| println!("{}", s));
}
```

It is clear here that the declaration and implementation of `Foo` is not doing anything wrong, but `free_and_use` wrongly assumes that `<T as Foo<'s>>::Bar : 'body`, which does not make a lot of sense.

**Comment by nikomatsakis** [comment]
Yes, I see the problem. It lies in some of the logic around type parameter outlives rules -- we assume type parameters outlive the current fn, and we assume the same of projections, which is clearly wrong. I've been wanting to revisit these rules about projections and how long they live (https://github.com/rust-lang/rust/issues/23442) though not for soundness reasons.

**Comment by nikomatsakis** [comment]
triage: P-high

**Comment by nikomatsakis** [comment]
Just FYI -- I've been working steadily on this. I'm going to try and writeup my thoughts "soon" (famous last words).

**Comment by nikomatsakis** [comment]
This original example is now giving me an error on stable: http://is.gd/bidora

The question is, did we add a test?

**Comment by nikomatsakis** [comment]
The test associated-types-outlives.rs claims to be a regression test for this issue. Closing!
