### ISSUE TITLE
rustbook: Generics chapter trait confusion

### ISSUE THREAD

**Issue by Munksgaard** [rust-lang/rust#24621]
The generics chapter ends like this:

    To fix this example, we need to learn about another Rust feature: traits.

But the generics chapter (5.23) comes after the traits chapter (5.21). However, there is a trait object chapter (5.25) that comes after the generics chapter.

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/24571 Will fix this. Thanks!
