### ISSUE TITLE
Debug impl of floating numbers does not display signaling NaNs

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#24624]
```
use std::mem;

fn main() {
    let signaling_nan: f32 = unsafe {mem::transmute(0x7FC0_0000u32)};
    assert_eq!(format!("{:?}", signaling_nan), "sNaN(00000)");
}
```

fails with “assertion failed: `(left == right)` (left: `"NaN"`, right: `"sNaN(00000)"`)”

The actual representation is bikeshedable (could be just “sNaN” etc).

[playpen](http://is.gd/mGrmcs)

**Comment by steveklabnik** [comment]
Triage: no chae

**Comment by dtolnay** [comment]
This seems okay but I would prefer to see an [RFC](https://github.com/rust-lang/rfcs/blob/master/libs_changes.md) to justify this a little better. In particular:

- What use cases is this intended to solve?
- How do some other languages solve those use cases?
- Does Debug of a quiet NaN also need to tell us which of the many quiet NaNs it is?
- *(less important)* Brainstorm some alternative representations.
