### ISSUE TITLE
Wrong formatting of negative zero when sign is requested

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#24623]
``` rust
use std::mem;
fn main() { 
    let neg_zero: f32 = unsafe { mem::transmute(0x8000_0000u32) };
    assert_eq!(format!("{:+}", neg_zero), "-0");
}
```

Fails with “assertion failed: `(left == right)` (left: `"+0"`, right: `"-0"`)”

[playpen](http://is.gd/SXlL11)

**Comment by rkruppe** [comment]
Note that `{:?+}` produces the desired result. So this is consistent with the behavior agreed upon in #20596 (Display treats negative zero as positive, Debug differentiates them). In the light of that, it's not clear to me why the `+` format code should make a difference.

Also, by the way: You can produce a negative zero with `-0.0`, no need for the transmute.

**Comment by bstrie** [comment]
Triage: still relevant.
