### ISSUE TITLE
Consider renaming `.connect()` to `.join()`

### ISSUE THREAD

**Issue by barosl** [rust-lang/rust#24645]
`SliceConcatExt` has a method named `.connect()`, which is similar to `.join()` in other languages. I don't have any specific numbers, but "join" seems to be used more widely.

We could not use "join" because it was previously a keyword. Now it isn't, and `SliceConcatExt` is currently marked as unstable, so how about renaming the method to a more popular name?

One blocker is that `SliceConcatExt` is already exported to the prelude. So, although it is technically unstable, the change will still break the currently accepted beta-compatible code.

Will this require a RFC?

cc http://www.reddit.com/r/rust/comments/336rj3/whats_the_best_way_to_join_strings_with_a_space/

**Comment by frewsxcv** [comment]
What other languages use:

* Ruby: [`join`](http://ruby-doc.org/core-2.2.0/Array.html#method-i-join)
* Python: [`join`](https://docs.python.org/3/library/stdtypes.html#str.join)
* JavaScript: [`join`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join)

**Comment by petrochenkov** [comment]
- C++ (boost): [join](http://www.boost.org/doc/libs/1_58_0/doc/html/string_algo/reference.html#header.boost.algorithm.string.join_hpp)
- C#: [Join](https://msdn.microsoft.com/en-us/library/dd783876(v=vs.110).aspx)
- Java 8: [join](http://docs.oracle.com/javase/8/docs/api/java/lang/String.html#join-java.lang.CharSequence-java.lang.Iterable-)
- Perl: [join](http://perldoc.perl.org/functions/join.html)

**Comment by bombless** [comment]
+1, we should do it in 1.1-nighty

**Comment by aturon** [comment]
Interesting! I'd always found the `connect` name intuitive, but the precedent here seems quite strong.

It'd be good for this to go through an RFC. We can't do an outright renaming at this point, but we could deprecate the old name and introduce a new one if there's strong enough consensus. (The fact that the *methods* of this trait are already stable reflects a commitment to the existing names; the lack of stability of the trait is more about how we provide these impls in `std`.)

**Comment by frewsxcv** [comment]
https://github.com/rust-lang/rfcs/issues/1102 merged, this can probably be closed?

**Comment by alexcrichton** [comment]
Indeed!
