### ISSUE TITLE
Extra 20px left margin applied to typedef'd return types

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#24655]
![capture](https://cloud.githubusercontent.com/assets/1455697/7246889/e143f438-e7b7-11e4-9ad7-423e8c7745dd.PNG)

http://sfackler.github.io/rust-postgres/doc/postgres/struct.Row.html

**Comment by frewsxcv** [comment]
Looks like it got added in https://github.com/rust-lang/rust/commit/0a46933c4d81573e78ce16cd215ba155a3114fce#diff-e0f884b85741a0964cc4b7722e0e6fadR351

**Comment by bluss** [comment]
I think using `.content .impl-items > .type` would fix it to only apply to associated types, not types in other positions (return value)
