### ISSUE TITLE
Deduplicate doc URLs

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#24659]
There are at least three sets of URLs that give the same thing:

http://doc.rust-lang.org/std/
http://doc.rust-lang.org/nightly/std/
http://static.rust-lang.org/doc/master/std/

One of the should be picked and the others redirect to it.

Related, but I believe not quite duplicate: #9461, #12466, #14466, #18558.

CC @brson

**Comment by steveklabnik** [comment]
The second are synonymous on purpose, and I'm not sure the third is even exposed anywhere, exactly

**Comment by tomjakubowski** [comment]
Presumably /std/ will be (or redirect to) the stable channel docs, right?

**Comment by steveklabnik** [comment]
Yes, once we have a stable channel :)

**Comment by SimonSapin** [comment]
I’d like to revisit the decision to have URLs synonymous on purpose, which can be bad for search engines, and use redirects instead.

**Comment by steveklabnik** [comment]
There's a second ticket open for `rel=canonical`, but I think that the reason that there can't be redirects is that they're just files on S3. /cc @alexcrichton

**Comment by SimonSapin** [comment]
S3 seems to support redirects: https://aws.amazon.com/blogs/aws/amazon-s3-support-for-website-redirects/ (though I haven’t looked into details).

**Comment by alexcrichton** [comment]
Last I looked into redirects they won't work for `static.rust-lang.org`, but that site is not linked from anywhere so I don't think that we should be worried about it. The other two I feel like are fine to have, we can use the `rel=canonical` trick to disambiguate, but I don't want either to go away.

**Comment by Valloric** [comment]
I'll [link to a comment I've made before](https://github.com/rust-lang/rust/issues/12466#issuecomment-55336614) about duplicate URL structures on rust-lang.org.

This is something you should strongly consider fixing.

**Comment by alexcrichton** [comment]
cc @steveklabnik (and rest of the docs team, although there's no alias)

Right now we have stable docs available in two locations:

http://doc.rust-lang.org/std/
http://doc.rust-lang.org/nightly/std/

On the infrastructure side we can make one redirect to the other. Does the docs team have a preference as to which is the canonical version

**Comment by tomjakubowski** [comment]
Did you mean to say stable docs are available at /std/ and at /stable/std/? Or are the docs at /nightly/std/ docs for the stable distribution?

**Comment by alexcrichton** [comment]
Oops, yes!

**Comment by steveklabnik** [comment]
> (and rest of the docs team, although there's no alias)

Let's try this: @rust-lang/docs 

:confetti_ball:

**Comment by steveklabnik** [comment]
> Does the docs team have a preference as to which is the canonical version?

So, there's actually three locations: there is also `/current-version/std`.

I think I prefer the longer one to be the canonical URL.

**Comment by frewsxcv** [comment]
Relevant RFC: https://github.com/rust-lang/rfcs/pull/1826

**Comment by frewsxcv** [comment]
Is there anything else actionable to do here?

**Comment by frewsxcv** [comment]
Now that the [RFC I linked earlier has merged](https://github.com/rust-lang/rfcs/pull/1826), a [tracking issue has been opened](https://github.com/rust-lang/rust/issues/44687), and as I see it, there's nothing else actionable in this particular issue so I'm going to close it.
