### ISSUE TITLE
32bit linux binary illegal instruction crash

### ISSUE THREAD

**Issue by petevine** [rust-lang/rust#24668]
The official beta2 binary crashes on my 32bit athlon xp processor.

```
Program received signal SIGILL, Illegal instruction.
0xb58fb410 in llvm::sys::MemoryFence() () from ../lib/librustc_llvm-4e7c5e5c.so
(gdb) bt
#0  0xb58fb410 in llvm::sys::MemoryFence() ()
   from ../lib/librustc_llvm-4e7c5e5c.so
#1  0xb58bc145 in llvm::PassRegistry::getPassRegistry() ()
   from ../lib/librustc_llvm-4e7c5e5c.so
#2  0xb58bb1ac in llvm::PassNameParser::PassNameParser() ()
   from ../lib/librustc_llvm-4e7c5e5c.so
#3  0xb589f23c in llvm::cl::list<llvm::PassInfo const*, bool, llvm::PassNameParser>::list<char [13], llvm::cl::desc, llvm::cl::OptionHidden>(char const (&) [13], llvm::cl::desc const&, llvm::cl::OptionHidden const&) ()
   from ../lib/librustc_llvm-4e7c5e5c.so
#4  0xb58a930e in _GLOBAL__sub_I_LegacyPassManager.cpp ()
   from ../lib/librustc_llvm-4e7c5e5c.so
#5  0xb7fec9ee in call_init.part () from /lib/ld-linux.so.2
#6  0xb7fecae4 in _dl_init () from /lib/ld-linux.so.2
#7  0xb7fddd5f in _dl_start_user () from /lib/ld-linux.so.2
```

**Comment by petevine** [comment]
Btw, if this crash is caused by cross compiling on a 64bit machine leaving all SSE instruction sets on, you've just created a circular dependency in the 32bit build process (i.e. it won't be possible to build rust from source which requires a working rustc binary)

**Comment by nagisa** [comment]
https://github.com/rust-lang/cargo/issues/958 related. Especially relevant is [this comment](https://github.com/rust-lang/cargo/issues/958#issuecomment-64322368).

**Comment by nagisa** [comment]
It might be nice to have builds for absolute baseline architecture (8086-ish with 8087?) so one could run rust on ancient hardware. Not sure whether LLVM even supports that, though.

**Comment by petevine** [comment]
It seems with the latest nightly it's now possible to run rustc using qemu-i386 userspace translation.
Previously qemu-i386 printed 'unsupported syscall 355' and  rustc crashed whereas now it prints that message and all goes forward as expected.

**Comment by petevine** [comment]
I was able to create a fully working rustc/cargo build for the generic i686 architecture.

It can be downloaded from here:
https://www.dropbox.com/sh/9ga4a7df1nafuc2/AABSiVQwwpyXa2Ellm0Ihgwxa?dl=0
