### ISSUE TITLE
Rustc: error while loading shared libraries: librustc_driver--4e7c5e5c.so

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#24677]
When I run a cargo build command, I get the following errors:

Process didn't exit successfully: `rustc -vV` (exit code: 127)
--- stderr
rustc: error while loading shared libraries: librustc_driver-4e7c5e5c.so: cannot open shared object file: No such file or directory

My computer is running the latest version of arch linux, and I installed rust using the curl command: curl -sf -L https://static.rust-lang.org/rustup.sh | sudo sh

I don't think the issue is with my code, but you can look in my repositories for my simple hello_world program here:  https://github.com/a-jamesregan/LearnRust

**Comment by skeuomorf** [comment]
I have the same problem running latest version of arch linux, running ``rustc`` generates the same error (without running cargo).

**Comment by zaeleus** [comment]
Add `/usr/local/lib` to your `LD_LIBRARY_PATH` (or include it in your `/etc/ld.so.conf` so `ldconfig` searches it when run).

This doesn't happen just on Arch. Most non-Debian systems don't trust anything outside `/lib` and `/usr/lib` by default. Because rustup installs to `/usr/local`, `ldconfig` doesn't see the newly installed libraries.

**Comment by skeuomorf** [comment]
Ah, I see. You're correct @zaeleus.

For anyone else who faces this problem:
1- Edit the file ``/etc/ld.so.conf`` and add ``/usr/local/lib`` to it, you will need ``sudo`` rights to be able to write changes to the file.
2- Run ``sudo ldconfig`` to update the ldconfig cache.
3- Profit!

**Comment by a-jamesregan** [comment]
Thanks @skeuomorf, what you suggested worked.  It's worth nothing that when you say to add `/usr/local/lib` to the file, you should do this *literally*.  I got confused because the file by default contains a single line starting with `include /etc/ld.so.conf.d/*.conf`.  If you place an `include` before `/usr/local/lib` the fix doesn't work.

@steveklabnik, should I mark this issue as closed now?  Or is this going to be used to track the issue in the `rustup.sh` script?

**Comment by chessnokov** [comment]
just run:
`sudo ldconfig /usr/local/lib`

**Comment by yantonov** [comment]
Same problem if you install rust into specifi dir (./configure --prefix=$INSTALL_DIR && make && make install)
In that case you need to manually add file, for example rustlib.conf at /etc/ld.so.conf.d/ which contains one line $INSTALL_DIR.
You can do this way:
sudo echo $INSTALL_DIR >> /etc/ld.so.conf.d/rustlib.conf 
Than reconfigure ldconfig by call
sudo ldconfig

**Comment by andschwa** [comment]
Reporting that the latest version of the installer fails to add the path properly on CentOS 7.

**Comment by a-jamesregan** [comment]
Ha ha ha!  I just had this problem again on a different distro (fedora instead of ubuntu, or was it arch?) and when I searched for the issue again, my own bug request came up!  I just wanted to point out that this issue exists for Fedora too.

**Comment by PAStheLoD** [comment]
If editing anything in /etc/ is not really an option (or someone prefers not to), using a script to launch cargo (and I assume this works for other executables in bin/) works pretty well:


`~/bin/cargo`:

```
#!/bin/bash
PREFIX=/home/john/rust
export LD_LIBRARY_PATH=$PREFIX/lib
exec $PREFIX/bin/cargo "$@"
```

Maybe rustup could emit minimal shims/wrappers like these, kind of how other version managers do it. (rvm, pyenv, nvm)

**Comment by cyplo** [comment]
Seems that this is the same issue as: #26860
Comment there references rust-lang/rust-installer#30 as the main culript. It has a patch already, so probably will be fixed soon :)

**Comment by a-jamesregan** [comment]
@cyplo Sorry, I can't check to see if it works in Arch.  As much fun - and by that I mean a headache - as it was setting up Arch, I'm now running Ubuntu.  Rust seems to be working fine on 15.10 though!

**Comment by cyplo** [comment]
No worries, thanks a lot for checking :) Running ok on my ubuntu machine as well, fedora one having problems though. thanks again !

**Comment by Gabriel-Alves-Cunha** [comment]
Fedora still having problem with it.

**Comment by dev-tom-0108** [comment]
> Add `/usr/local/lib` to your `LD_LIBRARY_PATH` (or include it in your `/etc/ld.so.conf` so `ldconfig` searches it when run).
> 
> This doesn't happen just on Arch. Most non-Debian systems don't trust anything outside `/lib` and `/usr/lib` by default. Because rustup installs to `/usr/local`, `ldconfig` doesn't see the newly installed libraries.
@zaeleus 

I got the same error when build anchor.
I tried and followed to your suggestion. But it's same.
Any ideas?
My `anchor version` is 0.25.0.

**Comment by johnnie0318** [comment]
```
BPF SDK: /root/.local/share/solana/install/releases/stable-ab8180121d35f47895def5cb6a68ad3109d91b6c/solana-release/bin/sdk/bpf
cargo-build-bpf child: rustup toolchain list -v
cargo-build-bpf child: cargo +bpf build --target bpfel-unknown-unknown --release
error: process didn't exit successfully: `rustc -vV` (exit status: 127)
--- stderr
/root/.rustup/toolchains/bpf/bin/rustc: error while loading shared libraries: librustc_driver-0a24654c7f10b1f7.so: cannot open shared object file: No such file or directory
```
Same error for here.
Followed all instructions above but still get the error.
I am using root account on ubuntu 20.04

**Comment by divaisthewonder** [comment]
hi All - thanks for the posting. while i building the latest firefox, i am getting the same error. i did everything as suggested.

[root@USTNCOL-BHU01-RHELDMZHUB01 bin]# /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc --version --verbose
/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc: error while loading shared libraries: librustc_driver-eaf580548f9ab3b9.so: cannot open shared object file: Operation not permitted
[root@USTNCOL-BHU01-RHELDMZHUB01 bin]#

**Comment by P1119r1m** [comment]
It looks like Rust build system is immature.
If I run "./x.py build" and "./x.py install" into some non-system folder I will get and error running `rustc`:
```
.../Git/install/bin# ./rustc 
./rustc: error while loading shared libraries: librustc_driver-12c173733915d579.so: cannot open shared object file: No such file or directory
```

Yes, we can fix this problem using LD_LIBRARY_PATH-related workaroung.
But this looks completely immature.
