### ISSUE TITLE
Large executable file generated for trivial codes

### ISSUE THREAD

**Issue by critiqjo** [rust-lang/rust#24684]
This is a nonissue.

true.rs:
``` fn main() { } ```

true.c:
``` int main() { return 0; } ```

compile:
```
$ rustc -o truer true.rs
$ gcc -o truec true.c
$ ls -l
total 644
-rwxr-xr-x 1 john john   6600 Apr 22 11:21 truec
-rw-r--r-- 1 john john     25 Apr 22 11:21 true.c
-rwxr-xr-x 1 john john 642376 Apr 22 11:21 truer
-rw-r--r-- 1 john john     14 Apr 22 11:21 true.rs
```
The file generated by rustc is almost 100 times bigger. Is there a way to optimize executable file size? (I tried `-C opt-level=3 -C debuginfo=0`, but made no difference)

Motivation (not directly related): https://www.computer.org/cms/Computer.org/ComputingNow/issues/2015/04/mso2015020010.pdf

**Comment by killercup** [comment]
You might be interested in http://mainisusuallyafunction.blogspot.de/2015/01/151-byte-static-linux-binary-in-rust.html

**Comment by critiqjo** [comment]
Thanks! I was curious if there was any default method provided by rustc itself.

**Comment by steveklabnik** [comment]
> I was curious if there was any default method provided by rustc itself.

Yes, you could dynamically link, you could use LTO... they're in the blog post. :)
