### ISSUE TITLE
Remove or unstabilize all deprecated items in 1.0.0

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#24691]
Previously: http://internals.rust-lang.org/t/remove-or-unstabilize-all-deprecated-items-in-1-0-0/1945

Per SemVer, major releases are the only time when we get to remove stuff. If 1.0.0 final contains any `#[deprecated]` item, we’ll be stuck with them until 2.0 (which hopefully will be in a very long time!)

Proposal: Make sure that all `#[deprecated]` items in 1.0.0 are also marked `#[unstable]`. This will effectively make them unavailable in beta and release builds, meaning we can remove them in some future 1.x release without breaking backward-compatibility. In terms of [release process](http://internals.rust-lang.org/t/release-channels-git-branching-and-the-release-process/1940), this means back-porting a patch to beta. Then a new beta pre-release might be good.

Alternative: remove deprecated items entirely.

CC @brson

**Comment by bstrie** [comment]
Figuring that removing deprecated things is worth such a late-stage nomination.

**Comment by aturon** [comment]
@alexcrichton has been planning a patch to remove all deprecated items before 1.0.

**Comment by alexcrichton** [comment]
This was completed in https://github.com/rust-lang/rust/pull/24636 which is now merged.

**Comment by SimonSapin** [comment]
I found a few that feel through the cracks and are still `#[deprecated]` and `#[stable]`:
* `std::fs::soft_link`
* `f64::is_positive` and `f64::is_negative` (inherent methods)

**Comment by alexcrichton** [comment]
The goal of that PR was to remove all deprecated items that were slated for deletion before 1.0. The `soft_link` method was deprecated *very* recently and will make its way into 1.0 (at virtually no overhead). The `f64::is_{positive,negative}` methods were also deprecated very very recently and don't necessarily warrant a breaking change.

**Comment by SimonSapin** [comment]
So it is a decision to keep them in 1.0 and be stuck with them “forever”? (Really until 2.0, but in a way not making a 2.0 for a very long time is a sign of success.)

**Comment by alexcrichton** [comment]
It's a fact of life that we're going to grow deprecated functions over time, so we need to be comfortable with it no matter what. "Being stuck" with these functions has very little overhead to us as the remaining ones are all minor renamings basically and the compiler/tests don't depend on them at all (unlike the old `std::num` traits).

**Comment by SimonSapin** [comment]
Alright, fair enough. Thanks for #24636!
