### ISSUE TITLE
Possible issue with optin_builtin_traits

### ISSUE THREAD

**Issue by rajatgoel** [rust-lang/rust#24710]
It is not clear why this code is not compiling - http://is.gd/rLiwGC

Just want to make sure this is something not yet implemented/supported and not a bug in compiler.

**Comment by steveklabnik** [comment]
```
<anon>:39:9: 39:19 error: the trait `NotString` is not implemented for the type `collections::string::String` [E0277]
```

```
impl !NotString for String { }
```

Seems to make sense to me?

**Comment by rajatgoel** [comment]
What the compiler is saying is true. What is not clear is that why is it complaining about that on line 39 where we are converting from `Y` to `X` and not from `String` to `X`. `Y` implements `Error + NotString` and thus it should use the `From` implementation on line 12 to convert to `X`.

**Comment by petrochenkov** [comment]
Add `impl NotString for Y { }` to the program and it will compile.
When you implement `!NotString` for some type `T` it automatically becomes implemented for all types containing `T` - `Option<T>`, `Vec<T>`, `Y(T)` etc. and you have to override this automatic impls.
This is weird, but this is how OIBIT work, they are just not supposed to be used for specialization, but for "viral" traits like `Send`.

**Comment by rajatgoel** [comment]
@petrochenkov ah, that makes sense (if T is !Send .. anything containing it will also be !Send, etc). And thanks for suggesting the fix too.
