### ISSUE TITLE
LLVM ERROR: Attributes 'readnone and readonly' are incompatible!

### ISSUE THREAD

**Issue by TyOverby** [rust-lang/rust#24713]
When I use cargo to set `[profile.dev]` to use `opt-level = 1`, `cargo build` fails with this error.  Any other opt-level and it's fine.

```
Attributes 'readnone and readonly' are incompatible!
void ({ i8*, void (i8*)** }*, { i8*, void (i8*)** }*)* @"_ZN25Box$LT$CloneAny$GT$.Clone5clone20hea41b2e97e38689bjhaE"
LLVM ERROR: Broken function found, compilation aborted!
```

The project that I'm getting this error on is private for now, but it is breaking when compiling [typemap v0.2.1](https://github.com/reem/rust-typemap#bdaf7a23).

**Comment by nagisa** [comment]
Minimized case

```rust
#![feature(box_syntax)]
#![crate_type="lib"]

trait Clone2 {
    fn clone_convert(&self) -> Box<Clone3>;
}
trait Clone3: Clone2 {}
impl<T: Clone + 'static> Clone3 for T {}
impl<T: Clone + 'static> Clone2 for T {
    fn clone_convert(&self) -> Box<Clone3> {
        box self.clone()
    }
}
impl Clone for Box<Clone3> {
    fn clone(&self) -> Self {
        self.clone_convert()
    }
}
```

This is bug in our codegen, I fear (especially because we *do* dereference pointers we get), since we indeed emit both `readonly` and `readnone`. Interesting this is only caught by an optimisation pass, though...

**Comment by dotdash** [comment]
We do not emit `readnone`.

This is a bug in LLVM, there are two functions that call each other, and a pointer argument is only used in the mutual calls. In that case, the pointer argument gets the `readnone` attribute, but if there's already a `readonly` attribute present, that is not removed and the verifier complains.

This triggers the error:

```llvm
define void @bar(i8* readonly) {
  call void @foo(i8* %0)
    ret void
}

define void @foo(i8* readonly) {
  call void @bar(i8* %0)
  ret void
}
```

Patch submitted at http://reviews.llvm.org/D9995

**Comment by sanxiyn** [comment]
Can this be closed now?

**Comment by apasel422** [comment]
This no longer appears to be an issue.
