### ISSUE TITLE
reference grammar: no_struct_literal_expr undefined

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#24723]
In the [reference](http://doc.rust-lang.org/reference.html) `no_struct_literal_expr` is [used](http://doc.rust-lang.org/reference.html#while-loops) in the grammar but isn't defined

Reference meta bug https://github.com/rust-lang/rust/issues/16676

**Comment by mdinger** [comment]
Is the grammar moving out of the reference into grammar? Then each section could just link to the correct grammar section or are they both going to be maintained?

**Comment by steveklabnik** [comment]
Yes, I've been meaning to just remove it in favor of GRAMMAR.md

**Comment by mdinger** [comment]
Okay. That's easy.

**Comment by mdinger** [comment]
This is fixed since the grammar isn't in the reference anymore. The grammar has many many similar issues and this nitpick won't  really help any alone.
