### ISSUE TITLE
Broken inline code spans in rustdoc

### ISSUE THREAD

**Issue by retep998** [rust-lang/rust#24746]
Using Windows 8.1 x64 with `rustc 1.1.0-dev (e9e9279d8 2015-04-22) (built 2015-04-22)`
![](http://i.imgur.com/S2DrW5v.png)

**Comment by steveklabnik** [comment]
I'm adding the 'windows' tag because the docs for the site are generated on linux and look just fine.

**Comment by lucy** [comment]
Can reproduce locally on linux (running d8b64c7fb2809eeba8ff9125cc95c4c38efb9a8a).

**Comment by retep998** [comment]
Another issue, everything starts getting underlined after a certain point.
![](http://i.imgur.com/VktgUUZ.png)

**Comment by retep998** [comment]
Also the `[-]` button at the top of each page has stopped working.

**Comment by kagia** [comment]
Just to add to the screenshots here is a code snippet that can reliably reproduce the bug.

```rust
#![feature(rustdoc)]

extern crate rustdoc;

use rustdoc::html::markdown::Markdown;

fn main() {
	let source = "`This` should not be repeated. After `This<U>` nothing should be underlined.";

	let html = Markdown(source);

	println!("{}", html);
}
```

on my Win8.1 machine produces:

```plain
<p><code>This</code>`This<code>should not be repeated. After</code>This<U>` nothing should be underlined.</p>
```

**Comment by habnabit** [comment]
I get the same issues on OS X from 613e57b448c88591b6076a8cea9799f1f3876687.

**Comment by Eljay** [comment]
This seems to only happen for code spans <= 8 characters, e.g:

![image](https://cloud.githubusercontent.com/assets/6574/8638136/84d5e74c-28a8-11e5-894f-b9677e20f009.png)
The other problems (e.g. screwed up formatting) are just a result of the "leaked" span content being output directly as html.

**Comment by Eljay** [comment]
Interestingly, this doesn't happen in 32-bit builds or MSVC builds.

Tested on `rustc 1.4.0-nightly (1181679c8 2015-08-07)`
