### ISSUE TITLE
Create import library to go with dylib on Windows

### ISSUE THREAD

**Issue by retep998** [rust-lang/rust#24763]
On Windows, in order to link to a `.dll` you actually link to an import library instead, either `.a` or `.lib`. When creating a `.dll` with `rustc --crate-type=dylib` however, no such import library is created, thus making it difficult to link to from C/C++.
If an import library is created, the metadata could be moved from the `.dll` to the library, thus solving #23366.

**Comment by vadimcn** [comment]
`rustc --crate-type=dylib -C link-args=-Wl,-out-implib,library.lib ...` will cause linker to create an import library in addition to the .dll.

**Comment by steveklabnik** [comment]
@retep998 did @vadimcn's suggestion solve this issue?

**Comment by steveklabnik** [comment]
Closing until proven otherwise.
