### ISSUE TITLE
`-Z time-passes` has poorly formatted output

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#24773]
```
time: 0.004 	translation
  time: 0.000 	llvm function passes
  time: 0.000 	llvm module passes
  time: 0.002 	codegen passes
  time: 0.000 	codegen passes
time: 0.006 	LLVM passes
  time: 0.145 	running linker
time: 0.145 	linking

```

There seems to be extra indents going on in a number of these lines. The rest are all left-aligned.

**Comment by dotdash** [comment]
The indented ones are "external" passes.  And "LLVM passes" is the
cumulative time for the for indented passes above it, so there's a reason
for them being indented.
Am 24.04.2015 17:21 schrieb "Steve Klabnik" <notifications@github.com>:

**Comment by steveklabnik** [comment]
Ah, that wasn't very clear at all.
