### ISSUE TITLE
Beautiful printing for rustc --explain command

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#24771]
I open this issue to allow people to follow this feature status and I'd also like to do it myself if no one is against it.

This issue was "proposed" in #24523.

**Comment by tbelaire** [comment]
So, I think it'd look best with the markdown rule of blank line + 4 space indent denotes a code block, same as ``` does, and that is a cleaner fallback when printing it to the terminal I feel.  Does that make sense?

**Comment by GuillaumeGomez** [comment]
You mean writing error explanation like this:

```Rust
blabla
blabla

`` `
    code
    code
`` `

blabla
```

?

**Comment by tbelaire** [comment]
No, check it out, this is a code block

    this is a code block.


Source:
```
No, check it out, this is a code block

    this is a code block.

```

**Comment by tbelaire** [comment]
Here's the spec for it: http://daringfireball.net/projects/markdown/syntax#precode

**Comment by steveklabnik** [comment]
Triage: I am not 100% sure what exactly is being proposed here; @jonathandturner has been working on a new error formatting RFC that may significantly modify `--explain`'s output, though.

**Comment by Mark-Simulacrum** [comment]
This does not seem to be a concrete issue, so I'm not sure that we should keep it open. @GuillaumeGomez Could you maybe update the description with at least one or two things that we should do?

**Comment by GuillaumeGomez** [comment]
I think there's no point keeping it open now. People are working on this and it's on the roadmap iirc. Let's close it then.
