### ISSUE TITLE
`std::rc::try_unwrap()` should only consider the strong refcount

### ISSUE THREAD

**Issue by cybergeek94** [rust-lang/rust#24789]
From [this reddit thread][1].

[`std::rc::try_unwrap()`][2] returns `Err` if the `Rc` is not unique, which includes weak references. This fails intuition as the logic is the same as when the last `Rc` is dropped, which only considers strong references when deciding whether to drop the contained value, except it keeps the contained value from being destroyed. I fail to see how it is unsafe to unwrap when only weak references remain.

[1]: http://www.reddit.com/r/rust/comments/33oxls/move_value_out_of_rc_with_weak_refernces/
[2]: http://doc.rust-lang.org/std/rc/fn.try_unwrap.html

**Comment by SimonSapin** [comment]
This is fixed in #27837 and can be closed.
