### ISSUE TITLE
ICE: Assertion `R == 0 && "Already initialized this value register!"' failed

### ISSUE THREAD

**Issue by GBGamer** [rust-lang/rust#24799]
With the asm! templates.

You can see the code at https://github.com/GBGamer/os-dev/blob/master/kernel/low_level.rs

The specific assertion is:

```
rustc --emit=obj --target=i686-unknown-linux-gnu -C no-stack-check -C relocation-model=dynamic-no-pic --crate-type lib -L kernel/deps kernel/lib.rs -o kernel/lib.o
rustc: /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/include/llvm/CodeGen/FunctionLoweringInfo.h:158: unsigned int llvm::FunctionLoweringInfo::InitializeRegForValue(const llvm::Value*): Assertion `R == 0 && "Already initialized this value register!"' failed.
make: *** [kernel/lib.o] Aborted (core dumped)
```

**Comment by GBGamer** [comment]
If you're wondering why this assert is running, it's because I'm using intel syntax without specifying the intel syntax option.

**Comment by GBGamer** [comment]
The smallest program that shows this behavior:

```rust
#![feature(asm)]

fn main() {
    let mut _test: u32;
    unsafe {
        asm!("mov $2, %eax" : "=a"(_test));
    }
}
```

**Comment by huonw** [comment]
Register constraints are written with `{...name...}`, and literals with double `$$` (this design is definitely subpart and is part of the reason that `asm!` is unstable). The following compiles fine:

```rust
#![feature(asm)]

fn main() {
    let mut _test: u32;
    unsafe {
        asm!("mov $$2, %eax" : "={ax}"(_test));
    }
}
```

(It's not necessary to specify the exact width.)

Thanks for filing but this isn't a bug.

**Comment by GBGamer** [comment]
@huonw It is still a bug. There is an llvm assertion here. Even if this isn't correct, there should not be an llvm assertion.

If this is true, then it's a bug with the documentation, where it still shows this syntax.
