### ISSUE TITLE
Unstable indexing permitted in beta channel

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#24791]
I just discovered you can slice the slice iterator. It's neat, but unstable. `.as_slice()` as well as the `Index` implementations for the `slice::Iter` are marked unstable, but you can still use the slicing syntax in the beta channel.

Compiles in rustc 1.0.0-beta.2 (e9080ec39 2015-04-16) (built 2015-04-16)

```rust
println!("{:?}", &[1,2,3].iter()[..1]);
```

The effect is that converting iterators to slices isn't closed down like it was intended.

**Comment by bluss** [comment]
Not sure if it's intentional or not.

**Comment by bluss** [comment]
cc @aturon

**Comment by alexcrichton** [comment]
This is an unfortunate fallout of our current stability system, although it looks like we don't currently have another open bug on this. The consequence is that the stability of an `impl` is not tracked, only the stability of the trait itself is considered when evaluating the stability of a method call.

(unfortunately).

**Comment by aturon** [comment]
We've talked about `#[cfg(nightly)]` in the past, but it didn't occur to me that it would also help with situations like this one. We should look into it.

In the meantime, I think we just need to decide whether we're willing to stabilize this functionality. I think it's unstable mostly because it was a relatively recent addition.

**Comment by pnkfelix** [comment]
Decision: remove this functionality for 1.0 (since we do not have a way to mark it as unstable).

P-high.

**Comment by alexcrichton** [comment]
triage: (1.0)

**Comment by bluss** [comment]
Add for Vec was discussed because it is exposed in the same way. It's hard to tell what's intentional. Needs big review?

**Comment by pnkfelix** [comment]
@bluss yeah, there was discussion of that in the meeting that was not recorded here.

I think the main idea was that we would lint (or grep, etc) for uses of `#[unstable]` on impls, (or perhaps even go so far as to lint for any `impl` that does not have an `#[stable]` on it?) and try to ensure that none get in that are not marked as `#[cfg(nightly)]`...

**Comment by alexcrichton** [comment]
@bluss I've [created a PR for this](https://github.com/rust-lang/rust/pull/25006) in which I marked that impl stable [for these reasons](https://github.com/rust-lang/rust/pull/25006#issuecomment-97990463)

**Comment by bluss** [comment]
Looks good!
