### ISSUE TITLE
Document object safety in the reference

### ISSUE THREAD

**Issue by mbrubeck** [rust-lang/rust#24800]
The official docs don't currently mention how to determine whether a trait is object-safe.  For reference:

* http://huonw.github.io/blog/2015/01/object-safety/
* https://github.com/rust-lang/rfcs/blob/master/text/0255-object-safety.md

**Comment by steveklabnik** [comment]
I don't know when this was added, but http://doc.rust-lang.org/reference.html#trait-objects says

> Note that for a trait object to be instantiated, the trait must be object-safe. Object safety rules are defined in RFC 255.
