### ISSUE TITLE
Make more of `syntax::parse::parser::Parser`'s methods public

### ISSUE THREAD

**Issue by canndrew** [rust-lang/rust#24801]
I'm writing a syntax extension and there are methods that would be useful to me which are private inside `syntax::parse::parser::Parser`. Specifically I'd like access to `parse_struct_def` but there seems to be plenty of methods which are private for no apparent reason.

**Comment by aturon** [comment]
@steveklabnik FYI, this is pretty much outside of the purview of "library stabilization" as we've been doing it with `std` -- we don't really have a plan in place yet for scrutinizing these APIs. I'm not really sure if there is an "owner" here.

**Comment by steveklabnik** [comment]
Triage: compiler extensions will no longer be using the internals of these crates, and so deciding what is public and what isn't shouldn't be a problem any more. Closing!
