### ISSUE TITLE
#[derive(FromPrimitive)] should use the num crate

### ISSUE THREAD

**Issue by kballard** [rust-lang/rust#24822]
The compiler still supports `#[derive(FromPrimitive)]` but it uses `std::num::FromPrimitive` which doesn't exist anymore. The compiler should remove its built-in support for `#[derive_FromPrimitive]` and the `num` crate should implement it instead.

Alternatively, to avoid the need for `#![feature(custom_derive)]`, the compiler's built-in support could be adjusted to use `num::traits::FromPrimitive` instead, with the expectation that clients will adopt the external `num` crate, but this approach is inflexible (the `num` crate can't change `FromPrimitive` without breaking compatibility).

**Comment by nwin** [comment]
This is really an issue. At the moment there is no convenient way of converting an integer value to an enum. `enum_primitive` also doesn’t work because of #24189.

**Comment by bombless** [comment]
I think people can use invoke a macro to define an enum, in this way they can impl From easily.

**Comment by nwin** [comment]
I don’t want to write a new macro for every enum, this is as convenient as just implementing `From` manually.

**Comment by durka** [comment]
`#[derive(FromPrimitive)]` was removed in #31400 so this can be closed.
