### ISSUE TITLE
Cannot implement `From<T> for U` where T is private and U is public

### ISSUE THREAD

**Issue by kballard** [rust-lang/rust#24824]
I assume this is a logical consequence of the current trait coherence rules, but I admit I'm not really up to speed on what rules we ended up setting on. But the end result is that I cannot derive `From<T>` for a public type if `T` is a private type. The resulting error message is `error: private type in exported type signature`.

Example:

``` rust
struct Private {
    x: i32
}

#[derive(Debug)]
pub struct Public {
    y: i32
}

impl From<Private> for Public {
    fn from(val: Private) -> Public {
        return Public { y: val.x }
    }
}

fn main() {
    println!("{:?}", Public::from(Private { x: 42 }));
}
```

> ```
> unnamed.rs:10:11: 10:18 error: private type in exported type signature
> unnamed.rs:10 impl From<Private> for Public {
>                         ^~~~~~~
> error: aborting due to previous error
> ```

It is possible to implement the inverse trait `Into`, which is better than nothing, but it is a bit unfortunate that this doesn't work.

See also #24823, where I request the ability to `#[derive]` the `From` trait for a C-like enum (converting from integral representation). This limitation here arose when I tried to implement the other direction (converting from the enum back into an integral representation), as my sample enum was not public.

/cc @nikomatsakis

**Comment by steveklabnik** [comment]
Triage: this code compiles today. Closing!
