### ISSUE TITLE
How can i set timeout now?

### ISSUE THREAD

**Issue by FillZpp** [rust-lang/rust#24836]
My project used the `Timer` in `old_io`, so that i can set timeout by `oneshot`. 
Now i find the `old_io` module has been removed and how can i set timeout?

**Comment by Stebalien** [comment]
Please as support questions on the discourse forum: https://users.rust-lang.org. Regarding you question, does `std::thread::sleep_ms` do what you want?

**Comment by FillZpp** [comment]
No. What i want is the `Timer.oneshot()` in `old_io`. Its result can be used in macro `select!` with `std::sync::mpsc::Receiver` to set the timeout of `Receiver`.

**Comment by Stebalien** [comment]
As far as I know, those are gone for the time being. You could roll your own or try using mio instead of the built-in channels.

**Comment by steveklabnik** [comment]
Yes, this is no longer in the standard library, and you'll have to implement it yourself for now.
