### ISSUE TITLE
Documentation text on trait impl methods is hidden in docs

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#24838]
I use documentation on my trait impls to tell users about how my types behave:

```rust
impl<N, E, Ty, Ix> Index<NodeIndex<Ix>> for Graph<N, E, Ty, Ix> where
    Ty: EdgeType,
    Ix: IndexType,
{
    type Output = N;
    /// Index the **Graph** by **NodeIndex** to access node weights.
    ///
    /// **Panics** if the node doesn't exist.
    fn index(&self, index: NodeIndex<Ix>) -> &N {
        &self.nodes[index.index()].weight
    }
}
```

This documentation is not rendered anymore. I expect to see it under the entry for the `Index` implementation of the `Graph` type.

I think this was lost after (the otherwise very awesome!) documentation changes by @alexcrichton

**Comment by bluss** [comment]
Note: Documenation on top of the `impl` item itself is properly rendered. If you too agree this is adequate, please close the issue again.

**Comment by aepsil0n** [comment]
Just for reference: this also leaves the (perhaps not entirely obvious) operator impls on HashSets undocumented. Also see [this SO question](http://stackoverflow.com/questions/31137928/where-is-the-rust-documentation-for-trait-implementations) on this issue.

**Comment by mcast** [comment]
Yes, #27058 is dup of this.  It is hiding stable parts of std from me: https://doc.rust-lang.org/1.1.0/src/core/result.rs.html#883-890
