### ISSUE TITLE
rustc crash when trying to reference static export from another crate

### ISSUE THREAD

**Issue by Eljay** [rust-lang/rust#24843]
https://gist.github.com/Eljay/24d13b4a27c4f6735b05

rustc just crashes with no useful errors. I guess you're not supposed to be able to do this anyway and it works if either are const instead of static but it shouldn't crash.

Tested with latest nightly and 1.0.0-beta.2 on windows 64-bit.

**Comment by thomas-huet** [comment]
No longer crashes:

```
error[E0394]: cannot refer to other statics by value, use the address-of operator or a constant instead
 --> src/main.rs:3:35
  |
3 | static TEST_STR_2: &'static str = &test::TEST_STR;
  |                                   ^^^^^^^^^^^^^^^ referring to another static by value
  |
  = note: use the address-of operator or a constant instead
```

**Comment by Mark-Simulacrum** [comment]
E-needstest.

**Comment by steveklabnik** [comment]
Triage: not aware of any tests being added.

**Comment by mbrobbel** [comment]
It seems that the E0394 error was removed in https://github.com/rust-lang/rust/pull/51110 and the tests were moved from compile-fail and ui/error-codes to run-pass.
