### ISSUE TITLE
Type parameter default not respected with enums

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#24857]
``` rust
enum Foo<S = i32> {
    Bar,
    Baz(S)
}

fn f<S>(_: Foo<S>) {}

fn main() {
    f(Foo::Bar);
}
```

```
~ ❯ rustc test.rs
test.rs:9:5: 9:6 error: unable to infer enough type information about `_`; type annotations required [E0282]
test.rs:9     f(Foo::Bar);
              ^
error: aborting due to previous error
```

**Comment by sfackler** [comment]
This may actually just be "RFC 213 hasn't been implemented yet". Any idea, @nikomatsakis?

**Comment by apasel422** [comment]
Item 2 from RFC 213 hasn't been implemented yet, so default type parameters aren't used as fallbacks for inference. The same issue occurs with structs:
```rust
use std::marker::PhantomData;

struct Foo<T = ()>(PhantomData<T>);

fn f<S>(_: Foo<S>) {}

fn main() {
    f(Foo(PhantomData));
}
```
```sh
> rustc foo.rs
foo.rs:8:5: 8:6 error: unable to infer enough type information about `_`; type annotations required [E0282]
foo.rs:8     f(Foo(PhantomData));
             ^
error: aborting due to previous error
```

CC #21939.

**Comment by gkoz** [comment]
Is this the same or different issue?
```Rust
fn foo<T = i32>(x: Option<T>) { }

fn main() {
    foo(None)
}
```
```
<anon>:4:5: 4:8 error: unable to infer enough type information about `_`; type annotations required [E0282]
<anon>:4     foo(None)
             ^~~
```

**Comment by sfackler** [comment]
I believe that's the same issue.

**Comment by IvanUkhov** [comment]
[Here](http://is.gd/CAKMEX) is another context where default values could be useful:

```rust
trait Foo {
    fn foo() -> Self;
}

impl Foo for f32 {
    fn foo() -> f32 {
        42.0
    }
}

impl Foo for f64 {
    fn foo() -> f64 {
        42.0
    }
}

fn bar<T: Foo=f64>() -> T { // “=f64” has no effect.
    T::foo()
}

fn main() {
    let _: f64 = bar(); // The type annotation is still needed.
}
```


Regards,
Ivan

**Comment by jroesch** [comment]
I currently have a PR open that implements default type parameter fallback, if anyone is so inclined any test cases would be appreciated. PR: https://github.com/rust-lang/rust/pull/26870

**Comment by steveklabnik** [comment]
Triage: still true today

**Comment by nikomatsakis** [comment]
I feel like this is expected behavior at the moment. At least until we settle the story around default type parameter fallback, which is more the purview of <https://github.com/rust-lang/rust/issues/27336>. I'd be inclined to close this myself.

**Comment by Mark-Simulacrum** [comment]
Closing as expected behavior per @nikomatsakis's comment.
