### ISSUE TITLE
Infinite memory use with nested * repetition in macro

### ISSUE THREAD

**Issue by mindcat** [rust-lang/rust#24858]
Play rust link: http://is.gd/DVjBtk
```Rust
macro_rules! a {(<$($($d:expr),*$($c:ident),*)*>) => (B<$($d,)*$($c,)*>);}a! (<>);
```

**Comment by huonw** [comment]
Minimal example:

```rust
macro_rules! a {
    ($($($d:tt)*)*) => ();
}

a!();
```

**Comment by SCareAngel** [comment]
So problem code is double repetition?
Is there any workaround?

**Comment by jonas-schievink** [comment]
I don't think the root problem is a double-repetition, but rather a repetition of something that can be 0 tokens long. In this case `$($d:tt)*` can contain 0 tokens, which then cause the memory explosion on the attempt to repeat it. Replacing the inner repetition with `$($d:tt)+` prevents this bug, changing the outer repetition to use `+` doesn't.

See #28085, which I think is a duplicate of this (tl;dr: replacing the matcher with just `$()+` or `$()*` also causes this).

**Comment by jonas-schievink** [comment]
Also, this looks like a duplicate of #5067
