### ISSUE TITLE
Always scroll to the top after searching for something in rustdoc

### ISSUE THREAD

**Issue by gsingh93** [rust-lang/rust#24878]
If you are looking at the documentation for a function and have a URL that looks something like:  http://doc.rust-lang.org/collections/struct.BitVec.html#method.get, with the `#method.<name>` at the end, if you type something in the search box and hit enter quickly, the search results page will scroll down to somewhere in the middle. If you wait instead of hitting enter quickly, then everything is fine. There are probably multiple ways of fixing this problem, one is to scroll to the top after each search with some JavaScript.

**Comment by gsingh93** [comment]
@steveklabnik or anyone else who knows how this code works, could this issue be fixed by adding a `window.scrollTo(0, 0)` after this line: https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/static/main.js#L586

I haven't tested it, building Rust takes too long on my computer.

**Comment by pmarcelll** [comment]
@gsingh93 can you still reproduce it?

**Comment by gsingh93** [comment]
Can't reproduce, must have been fixed since then.
