### ISSUE TITLE
--emit=asm,link -C opt-level=1 causes "Instruction does not dominate all uses!"

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#24876]
```rust
fn main() {
    let mut v = 0;
    for i in 0..0 {
        v += i;
    }
    println!("{}", v)
}
```

Compiling with `rustc --emit=asm,link -C opt-level=1` (with `1.1.0-nightly (da623844a 2015-04-25) (built 2015-04-26)` gives:

```
Instruction does not dominate all uses!
  %1 = bitcast %"2.core::fmt::Arguments"* %0 to i64*
  %tmpcast = bitcast i64* %1 to %"2.core::ops::Range<i32>"*
LLVM ERROR: Broken function found, compilation aborted!
```

**Comment by apasel422** [comment]
Still ICEs with the given compilation command.

**Comment by arielb1** [comment]
cc @dotdash

**Comment by dotdash** [comment]
This is due to stack coloring / merging of stack slots. When preparing the asm for output, stack merging eliminates an alloca leading to non-SSA compliant IR, which is fine for _this_ pass, but we're re-using the same IR again, and then the verifier rightfully complains.
