### ISSUE TITLE
slice pattern bug

### ISSUE THREAD

**Issue by mind** [rust-lang/rust#24875]
The following program prints 102. Commenting out the match arm for either 100 or 102 causes the correct value (101) to be printed. I believe the first and third cases are being merged as they have the same form (but different guards), ruining the priority.

    #![feature(slice_patterns)]
    
    fn main() {
        let v = vec![1, 2];
        println!("{}", test(&v));
    }

    fn test(a: &[u64]) -> u64 {
        match a {
            [a, b ..]  if a == 3  => 100,
            [a, b]     if a == 1  => 101,
            [a, b ..]             => 102,
            _                     => 103
        }
    }
    // rustc 1.1.0-dev (69e47c77b 2015-04-23) (built 2015-04-23)

**Comment by mind** [comment]
I'm actually seeing similar behavior even without guards (rest pattern overriding an earlier fixed-arity pattern).

**Comment by jfirebaugh** [comment]
Seems to be working as expected now: https://play.rust-lang.org/?gist=2de1a5847481016cfe1909c6b24634f9&version=nightly&backtrace=0

**Comment by arielb1** [comment]
Sure. Bug never existed in MIR.
