### ISSUE TITLE
make failed with wrong Makefile path of llvm under OS X

### ISSUE THREAD

**Issue by mindon** [rust-lang/rust#24887]
key logs
# environment

rvm_path = /usr/local/rvm
# makefile (from 'Makefile.config', line 111)

LLVM_ON_UNIX := 1
# makefile (from 'Makefile.config', line 59)

PROJ_SRC_DIR := /home/lab/rust/src/llvm/home/lab/rust/x86_64-apple-darwin/llvm

it's said caused by "built-in implementation of realpath in Make" http://stackoverflow.com/questions/4763381/no-rule-to-make-target-makefile-needed-by-makefile

make version is "GNU Make 4.1"

how can i switch to macro version realpath instead of make version?

**Comment by richo** [comment]
Can you upload the full output of `./configure` and `make` ?

**Comment by mindon** [comment]
configure log
-----------------------------------
configure: looking for configure programs
configure: found program cmp
configure: found program mkdir
configure: found program printf
configure: found program cut
configure: found program head
configure: found program grep
configure: found program xargs
configure: found program cp
configure: found program find
configure: found program uname
configure: found program date
configure: found program tr
configure: found program sed
configure: found program file
configure: found program make
configure: inspecting environment
configure: recreating config.tmp
configure: 
configure: processing ./configure args
configure: 
configure: CFG_LOCALSTATEDIR    := /var/lib 
configure: CFG_SYSCONFDIR       := /etc 
configure: CFG_DATADIR          := /share 
configure: CFG_INFODIR          := /share/info 
configure: CFG_LLVM_ROOT        :=  
configure: CFG_JEMALLOC_ROOT    :=  
configure: CFG_BUILD            := x86_64-apple-darwin 
configure: CFG_ANDROID_CROSS_PATH := /opt/ndk_standalone 
configure: CFG_RELEASE_CHANNEL  := dev 
configure: CFG_BUILD            := x86_64-apple-darwin 
configure: CFG_LIBDIR           := /usr/local/lib 
configure: 
configure: validating ./configure args
configure: 
configure: CFG_BOOTSTRAP_KEY    := 15:23:28 
configure: 
configure: looking for build programs
configure: 
configure: CFG_CURLORWGET       := /usr/local/bin/curl (curl 7.41.0 (x86_64-apple-darwin14.1.0) libcurl/7.41.0 OpenSSL/0.9.8zd zlib/1.2.5)
configure: CFG_PYTHON           := /usr/bin/python2.7 
configure: CFG_GIT              := /usr/bin/git (git version 2.3.2 (Apple Git-55))
configure: CFG_CLANG            := /usr/bin/clang++ (Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn))
configure: CFG_CCACHE           :=  
configure: CFG_GCC              := /usr/bin/gcc (Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn))
configure: CFG_LD               := /usr/bin/ld 
configure: CFG_VALGRIND         :=  
configure: CFG_PERF             :=  
configure: CFG_ISCC             :=  
configure: CFG_ANTLR4           :=  
configure: CFG_GRUN             :=  
configure: CFG_FLEX             := /usr/bin/flex (flex 2.5.35 Apple(flex-31))
configure: CFG_BISON            := /usr/local/bin/bison (bison (GNU Bison) 3.0.4)
configure: CFG_PANDOC           :=  
configure: CFG_XELATEX          :=  
configure: CFG_GDB              :=  
configure: CFG_LLDB             := /usr/bin/lldb (lldb-330.0.44)
configure: CFG_LLDB_VERSION     := lldb-330.0.44 
configure: CFG_LLDB_PYTHON_DIR  := /Applications/Xcode.app/Contents/Sh ...
configure: 
configure: looking for target specific programs
configure: 
configure: CFG_ADB              := /home/lab/adt/sdk ...
configure: 
configure: on OS X 10.9, forcing use of clang
configure: 
configure: CFG_ENABLE_CLANG     := 1 
configure: CFG_USING_CLANG      := 1 
configure: 
configure: found ok version of CLANG: 3.6.0svn
configure: 
configure: CFG_CC               := clang 
configure: CFG_CXX              := clang++ 
configure: 
configure: making directories
configure: 
configure: 
configure: configuring submodules
configure: 
configure: git: submodule sync
Synchronizing submodule url for 'src/compiler-rt'
Synchronizing submodule url for 'src/jemalloc'
Synchronizing submodule url for 'src/llvm'
Synchronizing submodule url for 'src/rt/hoedown'
Synchronizing submodule url for 'src/rust-installer'
configure: git: submodule init
configure: git: submodule update
configure: git: submodule foreach sync
Entering 'src/compiler-rt'
Entering 'src/jemalloc'
Entering 'src/llvm'
Entering 'src/rt/hoedown'
Entering 'src/rust-installer'
configure: git: submodule foreach update
configure: git: submodule status
 58ab642c30d9f97735d5745b5d01781ee199c6ae src/compiler-rt (remotes/origin/rust-2015-01-08-do-not-delete)
 e24a1a025a1f214e40eedafe3b9c7b1d69937922 src/jemalloc (3.6.0-158-ge24a1a0)
 bff69076975642c64e76dbeaa53476bfa7212086 src/llvm (remotes/origin/rust-llvm-2015-02-19)
 238c4d57cce10d33b05cf52a91fc62a09f31ffbb src/rt/hoedown (2.0.0-63-g238c4d5)
 e54d4823d26cdb3f98e5a1b17e1c257cd329aa61 src/rust-installer (heads/master)
-aed73472416064642911af790b25d57c9390b6c7 src/rust-installer/test/rust-installer-v1
-e577c97b494be2815b215e3042207d6d4b7c5516 src/rust-installer/test/rust-installer-v2
configure: git: submodule clobber
Entering 'src/compiler-rt'
Entering 'src/jemalloc'
Entering 'src/llvm'
Removing utils/llvm-build/llvmbuild/__init__.pyc
Removing utils/llvm-build/llvmbuild/componentinfo.pyc
Removing utils/llvm-build/llvmbuild/configutil.pyc
Removing utils/llvm-build/llvmbuild/main.pyc
Removing utils/llvm-build/llvmbuild/util.pyc
Entering 'src/rt/hoedown'
Entering 'src/rust-installer'
Entering 'src/compiler-rt'
Entering 'src/jemalloc'
Entering 'src/llvm'
Entering 'src/rt/hoedown'
Entering 'src/rust-installer'
configure: 
configure: looking at LLVM
configure: 
configure: configuring LLVM for x86_64-apple-darwin
configure: configuring LLVM with:
configure: --enable-targets=x86,x86_64,arm,aarch64,mips,powerpc --enable-optimized --disable-assertions --disable-docs --enable-bindings=none --disable-terminfo --disable-zlib --disable-libffi --enable-libcpp --build=x86_64-apple-darwin                         --host=x86_64-apple-darwin --target=x86_64-apple-darwin --with-python=/usr/bin/python2.7
checking for x86_64-apple-darwin-clang... clang -Qunused-arguments
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang -Qunused-arguments accepts -g... yes
checking for clang -Qunused-arguments option to accept ISO C89... none needed
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ -Qunused-arguments accepts -g... yes
checking how to run the C preprocessor... clang -Qunused-arguments -E
checking whether GCC or Clang is our host compiler... clang
checking build system type... x86_64-apple-darwin
checking host system type... x86_64-apple-darwin
checking target system type... x86_64-apple-darwin
checking type of operating system we're going to host on... Darwin
checking type of operating system we're going to target... Darwin
checking target architecture... x86_64
checking whether Clang is new enough... yes
checking optimization flags... -O3
checking for GNU make... make
checking whether ln -s works... yes
checking for nm... /usr/bin/nm
checking for cmp... /usr/bin/cmp
checking for cp... /bin/cp
checking for date... /bin/date
checking for find... /usr/bin/find
checking for grep... /usr/bin/grep
checking for mkdir... /bin/mkdir
checking for mv... /bin/mv
checking for x86_64-apple-darwin-ranlib... no
checking for ranlib... ranlib
checking for x86_64-apple-darwin-ar... no
checking for ar... ar
checking for rm... /bin/rm
checking for sed... /usr/bin/sed
checking for tar... /usr/bin/tar
checking for pwd... /bin/pwd
checking for dot... echo dot
checking for a BSD-compatible install... /usr/bin/install -c
checking for bzip2... /usr/local/bin/bzip2
checking for cat... /bin/cat
checking for doxygen... no
checking for groff... /usr/bin/groff
checking for gzip... /usr/bin/gzip
checking for pdfroff... /usr/bin/pdfroff
checking for zip... /usr/bin/zip
checking for go... /home/lab/go/bin/go
checking for ocamlfind... no
checking for gas... no
checking for as... /usr/bin/as
checking for linker version... 242
checking for compiler -Wl,-R<path> option... no
checking for compiler -rdynamic option... yes
checking for compiler -Wl,--version-script option... no
checking for grep that handles long lines and -e... (cached) /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking tool compatibility... ok
checking optional compiler flags... -Wno-variadic-macros -Wno-missing-field-initializers -Wcovered-switch-default -Wno-uninitialized  -Wno-comment
checking for python... user defined: /usr/bin/python2.7
checking for python >= 2.7... /usr/bin/python2.7 (2.7.6)
checking for sin in -lm... yes
checking for library containing dlopen... none required
checking for library containing clock_gettime... no
checking for library containing el_init... -ledit
checking for library containing mallinfo... no
checking for pthread_mutex_init in -lpthread... yes
checking for library containing pthread_mutex_lock... none required
checking for library containing pthread_rwlock_init... none required
checking for library containing pthread_getspecific... none required
checking for xml2-config... xml2-config
checking for libxml2 includes... -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2
checking for xmlReadFile in -lxml2... yes
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for MAP_ANONYMOUS vs. MAP_ANON... no
checking whether stat file-mode macros are broken... no
checking for sys/wait.h that is POSIX.1 compatible... yes
checking whether time.h and sys/time.h may both be included... yes
checking for cxxabi.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking execinfo.h usability... yes
checking execinfo.h presence... yes
checking for execinfo.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for inttypes.h... (cached) yes
checking link.h usability... no
checking link.h presence... no
checking for link.h... no
checking malloc.h usability... no
checking malloc.h presence... no
checking for malloc.h... no
checking setjmp.h usability... yes
checking setjmp.h presence... yes
checking for setjmp.h... yes
checking signal.h usability... yes
checking signal.h presence... yes
checking for signal.h... yes
checking for stdint.h... (cached) yes
checking termios.h usability... yes
checking termios.h presence... yes
checking for termios.h... yes
checking for unistd.h... (cached) yes
checking utime.h usability... yes
checking utime.h presence... yes
checking for utime.h... yes
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/resource.h usability... yes
checking sys/resource.h presence... yes
checking for sys/resource.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking sys/uio.h usability... yes
checking sys/uio.h presence... yes
checking for sys/uio.h... yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking malloc/malloc.h usability... yes
checking malloc/malloc.h presence... yes
checking for malloc/malloc.h... yes
checking mach/mach.h usability... yes
checking mach/mach.h presence... yes
checking for mach/mach.h... yes
checking valgrind/valgrind.h usability... no
checking valgrind/valgrind.h presence... no
checking for valgrind/valgrind.h... no
checking fenv.h usability... yes
checking fenv.h presence... yes
checking for fenv.h... yes
checking whether FE_ALL_EXCEPT is declared... yes
checking whether FE_INEXACT is declared... yes
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking CrashReporterClient.h usability... no
checking CrashReporterClient.h presence... no
checking for CrashReporterClient.h... no
checking __crashreporter_info__... yes
checking for HUGE_VAL sanity... yes
checking for pid_t... yes
checking for size_t... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking for int64_t... yes
checking for uint64_t... yes
checking for backtrace... yes
checking for ceilf... yes
checking for floorf... yes
checking for roundf... yes
checking for rintf... yes
checking for nearbyintf... yes
checking for getcwd... yes
checking for powf... yes
checking for fmodf... yes
checking for strtof... yes
checking for round... yes
checking for log... yes
checking for log2... yes
checking for log10... yes
checking for exp... yes
checking for exp2... yes
checking for getpagesize... yes
checking for getrusage... yes
checking for getrlimit... yes
checking for setrlimit... yes
checking for gettimeofday... yes
checking for isatty... yes
checking for mkdtemp... yes
checking for mkstemp... yes
checking for mktemp... yes
checking for posix_spawn... yes
checking for pread... yes
checking for realpath... yes
checking for sbrk... yes
checking for setrlimit... (cached) yes
checking for strerror... yes
checking for strerror_r... yes
checking for setenv... yes
checking for strtoll... yes
checking for strtoq... yes
checking for sysconf... yes
checking for malloc_zone_statistics... yes
checking for setjmp... yes
checking for longjmp... yes
checking for sigsetjmp... yes
checking for siglongjmp... yes
checking for writev... yes
checking for futimes... yes
checking for futimens... no
checking if printf has the %a format character... yes
checking for srand48/lrand48/drand48 in <stdlib.h>... yes
checking whether arc4random is declared... yes
checking whether strerror_s is declared... no
checking for isnan in <math.h>... yes
checking for isnan in <cmath>... yes
checking for std::isnan in <cmath>... yes
checking for isinf in <math.h>... yes
checking for isinf in <cmath>... yes
checking for std::isinf in <cmath>... yes
checking for finite in <ieeefp.h>... no
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for getpagesize... (cached) yes
checking for working mmap... yes
checking for mmap of files... yes
checking if /dev/zero is needed for mmap... no
checking for GCC atomic builtins... yes
checking for __dso_handle... yes
checking for compiler -fvisibility-inlines-hidden option... yes
configure: creating ./config.status
config.status: creating include/llvm/Config/Targets.def
config.status: creating include/llvm/Config/AsmPrinters.def
config.status: creating include/llvm/Config/AsmParsers.def
config.status: creating include/llvm/Config/Disassemblers.def
config.status: creating Makefile.config
config.status: creating llvm.spec
config.status: creating docs/doxygen.cfg
config.status: creating bindings/ocaml/llvm/META.llvm
config.status: creating include/llvm/Config/config.h
config.status: creating include/llvm/Config/llvm-config.h
config.status: creating include/llvm/Support/DataTypes.h
config.status: include/llvm/Support/DataTypes.h is unchanged
config.status: executing setup commands
config.status: executing Makefile commands
config.status: executing Makefile.common commands
config.status: executing examples/Makefile commands
config.status: executing lib/Makefile commands
config.status: executing test/Makefile commands
config.status: executing test/Makefile.tests commands
config.status: executing unittests/Makefile commands
config.status: executing tools/Makefile commands
config.status: executing utils/Makefile commands
config.status: executing projects/Makefile commands
config.status: executing bindings/Makefile commands
config.status: executing bindings/ocaml/Makefile.ocaml commands
configure: 
configure: writing configuration
configure: 
configure: CFG_SRC_DIR          := /home/lab/rust/ 
configure: CFG_BUILD_DIR        := /home/lab/rust/ 
configure: CFG_OSTYPE           := apple-darwin 
configure: CFG_CPUTYPE          := x86_64 
configure: CFG_CONFIGURE_ARGS   :=  
configure: CFG_PREFIX           := /usr/local 
configure: CFG_HOST             := x86_64-apple-darwin 
configure: CFG_TARGET           := x86_64-apple-darwin 
configure: CFG_LIBDIR_RELATIVE  := lib 
configure: CFG_DISABLE_MANAGE_SUBMODULES :=  
configure: CFG_ANDROID_CROSS_PATH := /opt/ndk_standalone 
configure: CFG_MANDIR           := /usr/local/share/man 
configure: CFG_LLVM_SRC_DIR     := /home/lab/rust/sr ...
configure: CFG_LLVM_BUILD_DIR_x86_64_apple_darwin := /home/lab/rust/x8 ...
configure: CFG_LLVM_INST_DIR_x86_64_apple_darwin := /home/lab/rust/x8 ...
configure: 
configure: leaving ./Makefile unchanged
configure: mv config.tmp config.mk
configure: 
configure: configured in release mode. for development consider --enable-debug
configure: 
configure: run `make help`
configure:

**Comment by mindon** [comment]
make log
------------------------
cfg: version 1.1.0-dev (2b8c9b12f 2015-04-28) (built 2015-04-28)
cfg: build triple x86_64-apple-darwin
cfg: host triples x86_64-apple-darwin
cfg: target triples x86_64-apple-darwin
cfg: host for x86_64-apple-darwin is x86_64
cfg: os for x86_64-apple-darwin is apple-darwin
cfg: good valgrind for x86_64-apple-darwin is 
cfg: using CC=clang (CFG_CC)
cfg: using CXX=clang++ (CFG_CXX)
cfg: enabling valgrind run-pass tests (CFG_ENABLE_VALGRIND_RPASS)
cfg: valgrind-rpass command set to 
cfg: no xelatex found, disabling LaTeX docs
cfg: no pandoc found, omitting PDF and EPUB docs
make: cleaning llvm
make[1]: Entering directory '/home/lab/rust'
cfg: version 1.1.0-dev (2b8c9b12f 2015-04-28) (built 2015-04-28)
cfg: build triple x86_64-apple-darwin
cfg: host triples x86_64-apple-darwin
cfg: target triples x86_64-apple-darwin
cfg: host for x86_64-apple-darwin is x86_64
cfg: os for x86_64-apple-darwin is apple-darwin
cfg: good valgrind for x86_64-apple-darwin is 
cfg: using CC=clang (CFG_CC)
cfg: using CXX=clang++ (CFG_CXX)
cfg: enabling valgrind run-pass tests (CFG_ENABLE_VALGRIND_RPASS)
cfg: valgrind-rpass command set to 
cfg: no xelatex found, disabling LaTeX docs
cfg: no pandoc found, omitting PDF and EPUB docs
cfg: including snap rules
cfg: including dist rules
cfg: including clean rules
make[2]: Entering directory '/home/lab/rust/x86_64-apple-darwin/llvm'
llvm[2]: Constructing LLVMBuild project information.
make[2]: Leaving directory '/home/lab/rust/x86_64-apple-darwin/llvm'
/home/lab/rust/mk/clean.mk:132: recipe for target 'clean-llvmx86_64-apple-darwin' failed
make[1]: Leaving directory '/home/lab/rust'
/home/lab/rust/mk/llvm.mk:61: recipe for target '/home/lab/rust/x86_64-apple-darwin/llvm/llvm-auto-clean-stamp' failed

**Comment by mindon** [comment]
make error
------------------
make[2]: *** No rule to make target '/home/lab/rust/src/llvm/home/lab/rust/x86_64-apple-darwin/llvm/Makefile', needed by 'Makefile'.  Stop.

**Comment by mindon** [comment]
here's my fixes for this issue:
update **src/llvm/Makefile.config.in** before running ./configure
or update **x86_64-apple-darwin/llvm/Makefile.config** before make

**line 59:**

    PROJ_SRC_DIR    := $(LLVM_SRC_ROOT)$(patsubst $(PROJ_OBJ_ROOT)%,%,$(PROJ_OBJ_DIR))


update to

    PROJ_SRC_DIR    := $(patsubst $(PROJ_OBJ_ROOT)%,$(LLVM_SRC_ROOT)%,$(PROJ_OBJ_DIR))


**line 86:**


    PROJ_SRC_DIR := $(call realpath, $(PROJ_SRC_ROOT)/$(patsubst $(PROJ_OBJ_ROOT)%,%,$(PROJ_OBJ_DIR)))

update to

    PROJ_SRC_DIR := $(call realpath, $(patsubst $(PROJ_OBJ_ROOT)%,$(PROJ_SRC_ROOT)%,$(PROJ_OBJ_DIR)))

**Comment by tamird** [comment]
@mindon seems like you should submit a PR?

**Comment by alexcrichton** [comment]
Make's now gone, so closing.
