### ISSUE TITLE
Docs for core::ptr::Unique have messed-up "Safety" sections

### ISSUE THREAD

**Issue by jruderman** [rust-lang/rust#24896]
https://doc.rust-lang.org/core/ptr/struct.Unique.html

There are "Safety" sections for a few methods.
- They are H1, too big and not following document structure. They should be H5, or not be sections at all.
- They have the same ID. They should have unique IDs, or no IDs at all.

I think it would be best to make them anonymous inline-headers:

> **Safety:** While this method and its mutable counterpart...

**Comment by pmarcelll** [comment]
These methods were moved, they can be found [here](https://doc.rust-lang.org/std/primitive.pointer.html). "Panics" and "Example" are also H1, so it seems to be consistent. They also have unique IDs now, so I think this can be closed.

**Comment by Mark-Simulacrum** [comment]
There are no more safety sections. I don't see anything wrong today, closing.
