### ISSUE TITLE
rustc should suggest implementing current traits rather than deprecated ones

### ISSUE THREAD

**Issue by sqweek** [rust-lang/rust#24907]
I had fun on my bus ride this morning debugging some code; I tried to pass one of my structs into `format!` and was greeted with:

```
src/main.rs:500:50: 500:58 error: the trait `core::fmt::String` is not implemented for the type `DataPos` [E0277]
```

Fair enough, I've been putting that off for awhile. I wasn't online to look up the trait documentation so I started a partial-implementation -> compile loop to extract the required signatures from rustc, one tiny step at a time. I had to laugh when I got to the end of the process only to find:

```
src/main.rs:437:6: 437:23 warning: use of deprecated item: renamed to Display, #[warn(deprecated)] on by default
src/main.rs:437 impl core::fmt::String for DataPos {
                     ^~~~~~~~~~~~~~~~~
```

:D
Aside from that and #18760 (I first tried `&mut self` rather than `&mut core::fmt::Formatter`) the errors were quite good and informative. It might be worth having E0046 include the signatures along with the item names? But I can also see this being overwhelming on traits with many items...

**Comment by steveklabnik** [comment]
Triage: this issue is almost two years old, with no other comments. It's mostly a pain of upgrading from pre-1.0 Rust to today's Rust; we haven't deprecated much since then. As such, I'm going to give this a close.
