### ISSUE TITLE
book sidebar jumps to top when following forward/back links

### ISSUE THREAD

**Issue by penguin42** [rust-lang/rust#24901]
When reading the book, if you have scrolled down on the left hand sidebar so you can see the current section and what comes soon, when you click on the link at the bottom of the current section to move to the next section, the sidebar then flips back to the top.  This is gently annoying.

**Comment by steveklabnik** [comment]
Hmmm, I thought this was a dup, but maybe not.

**Comment by steveklabnik** [comment]
This is not likely to be fixed, as

1) this is the default behavior to web pages, so I am wary to modify it
2) mdbook adds little foward/back links in page as well, and these do the right thing, and rustbook is likely to be removed in favor of mdbook in the future

**Comment by steveklabnik** [comment]
Update: mdbook is going to replace rustbook, so I'm going to give this a close. Thanks @penguin42 !
