### ISSUE TITLE
std libs collapse doesn't work anymore

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#24918]
The collapse button at the top right on the std lib [docs](http://doc.rust-lang.org/nightly/std/) doesn't work anymore. It should.

**Comment by mdinger** [comment]
[beta](doc.rust-lang.org/std/) doesn't work either.

**Comment by Diggsey** [comment]
The problem is in "main.js" in the "toggle-all-docs" event handler, which is attempting to use the HTML entities for '+'/'−' in a javascript string. This was likely broken when '[-]' was changed to '[−]'. It should use a unicode escape sequence.

**Comment by mohtar** [comment]
The pull request has been merged and it looks like the collapse button is working in the nightly docs now. This should be closed.

**Comment by mdinger** [comment]
Yup
