### ISSUE TITLE
associated constants can't be `use`d

### ISSUE THREAD

**Issue by tamird** [rust-lang/rust#24915]
https://is.gd/vYwA6X

main.rs:

``` rust
#![feature(associated_consts)]
struct Foo;

impl Foo {
  const SUP: &'static str = "sup";
}

use Foo::SUP;

fn main() {
  let sup = SUP;
  assert_eq!(sup, Foo::SUP);
}
```

rustc:

```
error: unresolved import `Foo::SUP`. Not a module `Foo` [--explain E0432]
 --> <anon>:8:5
8 |> use Foo::SUP;
  |>     ^^^^^^^^

error: aborting due to previous error
```

I'm not sure if this is specifically not intended, but it seems to me that it would be convenient to mirror the behaviour of enums in this way. cc @quantheory

**Comment by quantheory** [comment]
This isn't intended to work; associated types and methods can't be used in this way either, so this behavior is consistent with those cases, although I can see how `use` of associated constants would be convenient. I think that this has been proposed before, but AFAIK there hasn't been an RFC to allow `use` of associated items yet.

A workaround would be to just declare a copy/alias of the constant in the scope where you wanted to `use` it:

```rust
const SUP: &'static str = Foo::SUP;
```

This doesn't seem to work for associated types, though, so I should probably file a bug for that if there's not one already.

**Comment by tamird** [comment]
The suggested workaround does work now, but the original issue remains.

**Comment by Mark-Simulacrum** [comment]
Do we want this? It feels sort of weird to allow `use` to import associated constants but not other items from traits/impls. I almost feel like I saw an issue about expanding use to allow this somewhere recently, but I can't find it.

**Comment by Mark-Simulacrum** [comment]
Nominating for the lang team. I think it makes sense to discuss this, since it relates to @eddyb's (I believe) thoughts on moving the `std::{f32, i32, ...}` constants to associated constants and removing the modules. In order to effectively do so though we'd have to either allow importing or have the odd case where we're technically moving to potentially worse-looking code.

**Comment by eddyb** [comment]
We can just deprecate the old modules without removing them.

**Comment by Mark-Simulacrum** [comment]
Right, but whereas right now in a module that deals with just `u32` I can `use std::u32::*;` I won't be able to after this feature in any way without running into deprecation warnings.

**Comment by joshtriplett** [comment]
This isn't something that was part of the original specification for associated constants. Folks in @rust-lang/lang generally thought this sounded plausible, but it needs an RFC written to specify it.

**Comment by petrochenkov** [comment]
cc https://internals.rust-lang.org/t/importing-associated-constants/6610/5
