### ISSUE TITLE
Compiler panic

### ISSUE THREAD

**Issue by sharnik** [rust-lang/rust#24913]
I get an unexpected compiler panic error when I try to compile this code: https://gist.github.com/sharnik/3d1973950e6fb21640a3
(It's already been stripped of what I could remove with the error still happening)

I try to compile it with the following rust version: rustc 1.0.0-beta (9854143cb 2015-04-02) (built 2015-04-02). The backtrace is included in the code gist.

Let me know if I can add anything to the issue to make the debugging easier.

**Comment by steveklabnik** [comment]
can confirm on `rustc 1.1.0-nightly (5fb0259ed 2015-04-26) (built 2015-04-27)` on Linux as well.

**Comment by pmarcelll** [comment]
I can't reproduce it with `rustc 1.2.0-nightly (20d23d8e5 2015-06-18)`.

**Comment by alexcrichton** [comment]
Agreed!
