### ISSUE TITLE
Unexpected interpolate tokens in `quote_item!` macro

### ISSUE THREAD

**Issue by ptal** [rust-lang/rust#24914]
Recent changes (I guess #23085) make interpolated items unexpected when quoting items. The error is:`expected one of `const`, `extern`, `fn`, `pub`, `type`, `unsafe`, or `}`, found `an interpolated item``.  The full failing code is available https://github.com/ptal/Rust.peg/commit/20ddd3d76e09d390150e9f5401d92fc2bd95ab71 and a snippet is below:

```
pub struct PegCompiler<'cx>
{
  cx: &'cx ExtCtxt<'cx>,
  top_level_items: Vec<rust::P<rust::Item>>
}

impl<'cx> PegCompiler<'cx>
{
  fn compile_peg(&mut self) {
    let items = &self.top_level_items;
    parser.push(quote_item!(self.cx,
        impl Parser
        {
          pub fn new() -> Parser
          {
            Parser
          }
          $items // <== Remove this, and the error dissapears.
        }).unwrap());
  }
}
```

On `rustc 1.1.0-dev (441b3f0c2 2015-04-28) (built 2015-04-28)`

**Comment by sunng87** [comment]
I confirm the same issue with my little Derive macro [tojson_macros](https://github.com/sunng87/tojson_macros)

**Comment by ptal** [comment]
As of `rustc 1.1.0-dev (a979efc2f 2015-05-04) (built 2015-05-04)` the error message changed: ``error: expected ident, found `an interpolated item`.``

**Comment by ptal** [comment]
This bug persists but the interpolated item seems now "expanded", the new error is:

```
src/test/ntcc.rs:15:1: 138:2 error: expected one of `const`, `extern`, `fn`, `pub`, `type`, `unsafe`, or `}`, found `fn lt(input: &str, pos: usize) -> Result<usize, String> {
    match peg::runtime::match_literal(input, pos, "<", 1usize) {
        Ok(pos) => { Parser::spacing(input, pos) }
        x => x,
    }
}`
```

**Comment by ptal** [comment]
After investigations, it is normal that the code does not compile. This is due to the introduction of `ImplItem`. We tried to add free functions of type `Item` as method of an implementation (that should be of type `ImplItem`).

So the only problem is the bad error message.

**Comment by steveklabnik** [comment]
Triage: compiler plugin stuff is changing wildly; it will not be using this interface publicly. And given that is about a diagnostic, and nobody has commented in a while, I'm going to give this a close. If someone else sees a bad diagnostic like this with stable code, please let me know!
