### ISSUE TITLE
librustc/README.md is completely out of date

### ISSUE THREAD

**Issue by GBGamer** [rust-lang/rust#24912]
Someone who understands how it all works should probably update that.

**Comment by steveklabnik** [comment]
In general, all of these internal docs are. I'm not sure to what degree we expect them to always be great / current.

**Comment by steveklabnik** [comment]
Yeah, these internals-only docs aren't really being kept up. If and when we start publishing public versions of these crates, this should be fixed, but until then, keeping an issue open isn't particularly helpful.
