### ISSUE TITLE
split_whitespace example is failing on playpen

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#24916]
The [str::split_whitespace()`](http://doc.rust-lang.org/nightly/std/primitive.str.html#method.split_whitespace) example isn't working. It's example fails on playpen and I think it used to work previously. It's not [marked](https://github.com/rust-lang/rust/blob/master/src/libcollections/str.rs#L1774) as *no test* so I'm not sure how this got past the testsuite.

**Comment by mdinger** [comment]
cc https://github.com/rust-lang/rust-by-example/issues/560

**Comment by alexcrichton** [comment]
This is because `split_whitespace` was added in nightly but the playpen uses beta by default, so it looks like this is working as intended.

**Comment by mdinger** [comment]
@alexcrichton It definitely works now but didn't work when I filed it on nightly. This [rbe example](http://rustbyexample.com/str.html) was failing at the time too and rbe uses nightly specifically.

Weird.
