### ISSUE TITLE
Benchmark example is broken in the book

### ISSUE THREAD

**Issue by gsingh93** [rust-lang/rust#24923]
The benchmark example here does not compile: https://doc.rust-lang.org/book/benchmark-tests.html

Error message when running `rustc foo.rs --test`:
```
foo.rs:10:1: 23:2 error: the name `test` conflicts with an external crate that has been imported into this module [E0260]
foo.rs:10 mod test {
foo.rs:11     use super::*;
foo.rs:12     use test::Bencher;
foo.rs:13 
foo.rs:14     #[test]
foo.rs:15     fn it_works() {
          ...
error: aborting due to previous error
```

**Comment by jooert** [comment]
Oh, i forgot to change this part of the docs in #24783, where it was decided to have unit tests in a submodule `tests` rather than `test` because of exactly the same problem you're describing here. PR is #24931.
