### ISSUE TITLE
With a ridiculous amount of errors, ICE (capacity overflow)

### ISSUE THREAD

**Issue by ubsan** [rust-lang/rust#24955]
check out the gist: https://gist.github.com/GBGamer/e5e6b049fd715b219db4

This is my own modification of the compiler which has no bounds checks (but which makes it unsafe to index). This is an issue whenever you have a ridiculous amount of errors, however.

**Comment by GBGamer** [comment]
This should never be encountered normally, but, you know, still an ICE.

**Comment by pnkfelix** [comment]
is this really actionable without a backtrace?

**Comment by GBGamer** [comment]
@pnkfelix I just copy-pasted the output RUST_BACKTRACE=1 make

**Comment by pnkfelix** [comment]
@GBGamer funny, okay.  I'm used to seeing the backtraces at the bottom after my error listings.

**Comment by GBGamer** [comment]
@pnkfelix yeah, I know, I was weirded out too :P

**Comment by steveklabnik** [comment]
updated link https://gist.github.com/ubsan/e5e6b049fd715b219db4

> This is an issue whenever you have a ridiculous amount of errors, however.

@ubsan do you happen to have a good way to trigger this error?

**Comment by kennytm** [comment]
Both links are dead 😢.

**Comment by bstrie** [comment]
Given that we can no longer access the code to reproduce and that it seems to suggest that it requires bespoke modifications to the compiler, I'm inclined to close this unless @ubsan or someone can recreate the test case to show it's still relevant on today's compiler.

**Comment by pnkfelix** [comment]
I agree with @bstrie
