### ISSUE TITLE
Iterator documentation uses an array when it probably meant to use a vec

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#24977]
http://doc.rust-lang.org/1.0.0-beta.3/book/iterators.html#iterators

See the third code block:
```rust
let nums = [1, 2, 3];

for num in nums.iter() {
   println!("{}", num);
}
```
Up to this point this chapter has used `vec![]` instead of `[]` exclusively, and even the paragraph above this code refers to "vectors". This has led to some confusion over whether `[]` creates a vector, which is probably not an explanation fit for this section.

**Comment by pnkfelix** [comment]
doesn't the documentation also try to present semi-idiomatic rust, though?  Creating a `vec!` when a static array would suffice will just get people filing bugs against *that*, right?

**Comment by bluss** [comment]
Further down it uses .step_by which is unstable.
