### ISSUE TITLE
thread 'rustc' panicked at 'Box<Any>'

### ISSUE THREAD

**Issue by xeviox-com** [rust-lang/rust#24985]
Rust compiler exists with the error:
thread 'rustc' panicked at 'Box<Any>'

I tried this code:
http://is.gd/rQc7sJ

## Meta
`rustc --version --verbose`:
rustc 1.0.0-nightly (be9bd7c93 2015-04-05) (built 2015-04-06)
binary: rustc
commit-hash: be9bd7c93a53fe554a359e60c5f78991fb783eed
commit-date: 2015-04-05
build-date: 2015-04-06
host: x86_64-unknown-linux-gnu
release: 1.0.0-nightly

Backtrace:
$ cargo build --verbose
       Fresh libc v0.1.5
       Fresh log v0.3.1
   Compiling confrep v0.0.1 (file:///home/ben/coding/rust/confrep)
     Running `rustc src/main.rs --crate-name confrep --crate-type bin -g --out-dir /home/ben/coding/rust/confrep/target/debug --emit=dep-info,link -L dependency=/home/ben/coding/rust/confrep/target/debug -L dependency=/home/ben/coding/rust/confrep/target/debug/deps --extern getopts=/home/ben/coding/rust/confrep/target/debug/deps/libgetopts-13bfb58dc9e184de.rlib`
       Fresh getopts v0.2.9
src/main.rs:25:5: 25:43 warning: unreachable statement, #[warn(unreachable_code)] on by default
src/main.rs:25     let path = Path::new("/tmp/test-file");
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: internal compiler error: trans_local_var: no datum for local/arg 111 found
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:190

stack backtrace:
   1:     0x7f12c814d818 - sys::backtrace::write::h4618bbda30a2c1fakHC
   2:     0x7f12c8178be7 - panicking::on_panic::h94b32ff0a2406463uUI
   3:     0x7f12c80b08f3 - rt::unwind::begin_unwind_inner::h310b6bce2d1d1820CzI
   4:     0x7f12c5479f1d - rt::unwind::begin_unwind::h15255259843176184093
   5:     0x7f12c547a672 - diagnostic::Handler::bug::hb1aacf1770b183eeEsB
   6:     0x7f12c5e8c18b - session::Session::bug::hd7bb7b0f91601b5aFPq
   7:     0x7f12c7800d88 - trans::expr::trans_local_var::hfea7d9a1edfd43efNMi
   8:     0x7f12c77f75a1 - trans::expr::trans_def::h937da413b4ed2c37rli
   9:     0x7f12c77e3cf5 - trans::expr::trans_unadjusted::he520ad41983d76aeTXh
  10:     0x7f12c779b1e4 - trans::expr::trans::h21448d53b5dc88f5Blh
  11:     0x7f12c7892320 - trans::_match::trans_match_inner::h0490aa4abb428a0egUw
  12:     0x7f12c77e532c - trans::expr::trans_rvalue_dps_unadjusted::h7d73176442430ed1mti
  13:     0x7f12c7799878 - trans::expr::trans_into::h102b7487f22b7d50gfh
  14:     0x7f12c779a8e2 - trans::controlflow::trans_block::hd967465be585d26eH6d
  15:     0x7f12c78715bf - trans::base::trans_closure::hb04d661ffbb2ab64Qtt
  16:     0x7f12c7783516 - trans::base::trans_fn::h87734e73f2d4fb7azEt
  17:     0x7f12c777e1af - trans::base::trans_item::haf9903795e15a115P2t
  18:     0x7f12c7879b2c - trans::base::trans_crate::hec200aa517bde9c3lZu
  19:     0x7f12c87daa8f - driver::phase_4_translate_to_llvm::h8f420e4a7c43d0e6aOa
  20:     0x7f12c87b24db - driver::compile_input::h16213dd19660ff98Qba
  21:     0x7f12c8869a05 - run_compiler::h2a37c69935ac5f41S4b
  22:     0x7f12c886731d - boxed::F.FnBox<A>::call_box::h5013090055299594809
  23:     0x7f12c8866859 - rt::unwind::try::try_fn::h6394874154857801728
  24:     0x7f12c81f5398 - rust_try_inner
  25:     0x7f12c81f5385 - rust_try
  26:     0x7f12c8866b2b - boxed::F.FnBox<A>::call_box::h8372456613525927705
  27:     0x7f12c8163bd1 - sys::thread::create::thread_start::h0a2c84bef4c472f7MuH
  28:     0x7f12c1f59373 - start_thread
  29:     0x7f12c7d2327c - __clone
  30:                0x0 - <unknown>

Could not compile `confrep`.

Caused by:
  Process didn't exit successfully: `rustc src/main.rs --crate-name confrep --crate-type bin -g --out-dir /home/ben/coding/rust/confrep/target/debug --emit=dep-info,link -L dependency=/home/ben/coding/rust/confrep/target/debug -L dependency=/home/ben/coding/rust/confrep/target/debug/deps --extern getopts=/home/ben/coding/rust/confrep/target/debug/deps/libgetopts-13bfb58dc9e184de.rlib` (exit code: 101)

**Comment by steveklabnik** [comment]
This code no longer ICEs for me as of

```
$ rustc --version
rustc 1.3.0-nightly (bf3c979ec 2015-06-30)
```
