### ISSUE TITLE
by value closure's span starts at `||` instead of at `move`

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#24986]
The related piece of code is

```rust
// libsyntax/parse/parser.rs:2104
                if try!(self.eat_keyword(keywords::Move) ){
                    return self.parse_lambda_expr(CaptureByValue);
                }
```
Since `move` got eaten, `self.span.lo` will point behind the `move`
```rust
// libsyntax/parse/parser.rs:2864
    pub fn parse_lambda_expr(&mut self, capture_clause: CaptureClause)
                             -> PResult<P<Expr>>
    {
        let lo = self.span.lo;
```

I don't know anything about the code in libsyntax. I'd probably make a mess of it.
My intuition says simply adding `self.span.lo = lo;` just before the `return self.parse_lambda_expr(CaptureByValue);` might not be the best idea, since other code might depend on `lo` not getting modified here.

**Comment by bombless** [comment]
I have a feeling that we don't have good regression test to see if codemap works correctly.
I hope it would help if we add some unit tests to libsyntax.

**Comment by oli-obk** [comment]
I guess one could use rustfmt as a regression test :D

**Comment by jakub-** [comment]
Testing this indirectly is not too hard. One needs to find a diagnostic that uses a closure's span and then test that that diagnostic spans the closure correctly by breaking up the code by tokens into multiple lines.

```rust
move
||
{
// ...
}
```
