### ISSUE TITLE
rustdoc generates duplicate `id` attributes

### ISSUE THREAD

**Issue by apasel422** [rust-lang/rust#25001]
When two items in the same documentation page have the same name, rustdoc generates duplicate HTML `id` attributes for them. This makes the HTML invalid, but more importantly, it makes it impossible to link to anything but the one that shows up first in the source.

For example, [`Vec`'s page](http://doc.rust-lang.org/nightly/std/vec/struct.Vec.html) contains multiple impls of `IntoIterator`, and therefore multiple HTML elements that have an `id` attribute of `assoc_type.Item`, `assoc_type.IntoIter`, and `method.into_iter`.

This is not limited to impls of the same trait, as different traits (and inherent impls) could define methods or associated types with the same name.

**Comment by nagisa** [comment]
Similar to https://github.com/rust-lang/rust/issues/17476
