### ISSUE TITLE
Calculate the value of CFG_FILENAME_EXTRA from the version

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#25007]
This value has not changed in a long time, but to support sxs installation in a single dir it needs to. It should just be hashed from the value of `CFG_RELEASE`.

**Comment by lfairy** [comment]
@brson So should we pipe the value through e.g. md5sum?

That could be awkward on BSDs, where the hash programs have a [different naming convention and interface][1].

I think we can patch over the differences by adding a check to the configure script. Something like this:

```sh
# Use `md5sum` on GNU platforms, and `md5 -q` on BSD
if md5_hasher=$(which md5sum)
then
    CFG_HASH_COMMAND="$md5_hasher | head -c 6"
elif md5_hasher=$(which md5)
then
    CFG_HASH_COMMAND="$md5_hasher -q | head -c 6"
else
    err 'either `md5sum` or `md5` must be installed'
fi
putvar CFG_HASH_COMMAND
```

then in the Makefile we have:

```make
CFG_FILENAME_EXTRA=$(shell echo -n $(CFG_RELEASE) | $(CFG_HASH_COMMAND))
```

But if there's a simpler way then I'm all ears.

[1]: https://stackoverflow.com/questions/1299833/bsd-md5-vs-gnu-md5sum-output-format
