### ISSUE TITLE
UFCS does not work with `Box<Self>` methods

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#25019]
The following example shows a method that works when called as a method on `Box<Trait>`, but not in UFCS style:

```rust
trait Foo {}
impl Foo {
    fn foo(self: Box<Foo>) {}
}
fn do_it(t: Box<Foo>) {
    // works fine
    t.foo();

    // error: Box<Foo> has no method named foo
    <Box<Foo>>::foo(t);
}
```

**Comment by aturon** [comment]
cc @nrc @eddyb @nikomatsakis

**Comment by aturon** [comment]
Nevermind, this should be `<Foo>::foo(t)`.

**Comment by nikomatsakis** [comment]
I don't consider this a bug. [Writing `Foo::foo(t)`](http://is.gd/HZFkt9) works fine.

**Comment by nikomatsakis** [comment]
oh, @aturon beat me.
