### ISSUE TITLE
rustdoc shows duplicate bounds for derived implementations

### ISSUE THREAD

**Issue by tsion** [rust-lang/rust#25022]
See the derived implementations at the bottom of http://doc.rust-lang.org/1.0.0-beta.3/std/num/struct.Wrapping.html for example.

```rust
impl<T> Clone for Wrapping<T> where T: Clone + Clone
```

**Comment by tsion** [comment]
Interestingly, `impl<Idx> Clone for Range<Idx> where Idx: Clone + Clone + Clone` has `Clone` three times. My theory is that there's an extra bound for each use of the type parameter inside the struct, since `Wrapping<T>` has one `T` field and `Range<Idx>` has two `Idx` fields.

**Comment by tomjakubowski** [comment]
I think this is a bug in `#[derive(Clone)]`, actually. 

```rust
// bar.rs
#[derive(Clone)]
struct Foo<T>(pub T);

fn main() {
}
```

The results of `--pretty=expanded`:

```rust
#![feature(no_std)]
#![no_std]
#[prelude_import]
use std::prelude::v1::*;
#[macro_use]
extern crate std as std;
struct Foo<T>(pub T);
#[automatically_derived]
impl <T: ::std::clone::Clone> ::std::clone::Clone for Foo<T> where
 T: ::std::clone::Clone {
    #[inline]
    fn clone(&self) -> Foo<T> {
        match *self {
            Foo(ref __self_0_0) =>
            Foo(::std::clone::Clone::clone(&(*__self_0_0))),
        }
    }
}

fn main() { }
```

Note the extra bound.
