### ISSUE TITLE
Cannot have multiple anonymous parameters in a default trait method definition

### ISSUE THREAD

**Issue by P1start** [rust-lang/rust#25026]
``` rust
fn main() {}

trait Foo {
    fn foo(&self, i32) {} // Fine
    fn bar(&self, i32, i32) {} // error: identifier `` is bound more than once in this parameter list
}
```

Arguably, allowing _any_ anonymous parameters in a default trait method shouldn’t be allowed at all for consistency with `impl`s.

**Comment by steveklabnik** [comment]
Weird, I wouldn't expect any to be okay...

**Comment by steveklabnik** [comment]
Triage: this compiles without error today. Closing!
