### ISSUE TITLE
Allow indexing HashMap/BTreeMap mutably

### ISSUE THREAD

**Issue by Ms2ger** [rust-lang/rust#25034]
Note #23559. The suggestion is to use `get_mut` instead, but that's a lot uglier.

**Comment by Gankro** [comment]
tl;dr for anyone frustrated with this: blocked on IndexSet being fully defined to avoid Messes

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by dtolnay** [comment]
This is going to require an RFC. Let's track this as part of https://github.com/rust-lang/rfcs/issues/997.

**Comment by BatmanAoD** [comment]
@dtolnay @Gankra It's not immediately clear to me from looking at RFC issue 997 why BTreeMap and HashMap can't yet implement the existing `IndexMut` trait; is there already discussion about the connection somewhere that you can point me to? If not, would one of you mind explaining the connection here?

**Comment by dtolnay** [comment]
IndexMut would make `map[k] = v` compile but panic on key not already present. Presumably a user would expect insertion into the map, like in C++ and Go and JavaScript and every other language with that syntax, not a panic. That is https://github.com/rust-lang/rfcs/issues/997 and some designs are mutually exclusive with IndexMut.
