### ISSUE TITLE
FnMut sugar doesn't work through struct member variables

### ISSUE THREAD

**Issue by kaiskye** [rust-lang/rust#25039]
From what I understand, calling functions through an FnMut reference performs a sugaring operation that converts the call to call_mut(...). This doesn't seem to apply if the FnMut reference is stored inside of a struct.

Here is an example that stores a reference to an FnMut trait inside of a struct.

	struct MyStruct<'a, F> where F: 'a + FnMut() {
		func: &'a mut F
	}

	impl<'a, F> MyStruct<'a, F> where F: 'a + FnMut() {
		fn call_me(&mut self) {
			// self.func() -- DOESN'T WORK
			let mut f = &mut self.func;
			f();
		}
	}

	fn main() {
		let mut f = || {};
		let mut s = MyStruct { func: &mut f };
		s.call_me();
	}

Calling self.func() directly results in the following error:

    error: type `&mut MyStruct<'a, F>` does not implement any method in scope named `func`

However, binding self.func to a local variable and then calling through that compiles without errors.

## Meta

`rustc --version --verbose`:

	rustc 1.0.0-beta.3 (5241bf9c3 2015-04-25) (built 2015-04-25)
	binary: rustc
	commit-hash: 5241bf9c34d156ea6064367a33cbd7222eeb5789
	commit-date: 2015-04-25
	build-date: 2015-04-25
	host: x86_64-pc-windows-gnu
	release: 1.0.0-beta.3

**Comment by japaric** [comment]
You need to use `(self.func)()` to disambiguate from the method call `self.func()`. [Playpen](http://is.gd/WLD6Lr)

**Comment by kaiskye** [comment]
Ah, my bad! Makes sense.
