### ISSUE TITLE
Pretty-printer incorrectly outputs type items with where clauses

### ISSUE THREAD

**Issue by jooert** [rust-lang/rust#25031]
So I wrote a regression test for a certain error and it held up the rollup PR (see #24979) because while my test passed the `run-pass` it failed during the `pretty` pass. The problem is that the prettifier (compiling with `-Z unstable-options --pretty=expanded`) transforms the original code example from #22471 
```Rust
type Foo<T> where T: Copy = Box<T>;
```
into
```Rust
type Foo<T> = Box<T> where T: Copy;
```
which upon compilation leads to the following error:
```
error: expected one of `+`, `::`, or `;`, found `where`
type Foo<T> = Box<T> where T: Copy;
```
This seems to indicate a bug in the prettifier as (seemingly) valid code is transformed into non-compiling one.

**Comment by bluss** [comment]
basically the PR that added the syntax `type Foo<T> where T: Copy = Box<T>;` should have updated the pretty code to handle that too. That's what the pretty tests are trying to enforce.

**Comment by jooert** [comment]
It still may, as it isn't merged yet, but I have no idea how to do that. :smiley:

**Comment by jooert** [comment]
Sorry, I misread your comment, you weren't talking about my PR.
