### ISSUE TITLE
Cannot construct a struct inside a macro when the struct name is a macro argument

### ISSUE THREAD

**Issue by johnsoft** [rust-lang/rust#25073]
The title says it all. I don't know whether this is a bug or some inherent limitation in the design of the macro system, but there are no matching issues for the keywords \<struct macro> so I figured I'd file an issue.

Test case:

    macro_rules! build_struct {
        ($s:path) => {{
    	    $s { key: 12345 }
        }}
    }

    struct X { key: u32 }

    fn main() {
        let x = build_struct!(X);
    }

Expected result:

    it works

Actual result (on both 1.0 beta and current nightly):

    <anon>:3:9: 3:10 error: expected one of `.`, `;`, `}`, or an operator, found `{`
    <anon>:3     	$s { key: 12345 }
                 	   ^

Replacing `($s:path)` with `($s:ty)` also fails, but with a different error.

    <anon>:2:19: 2:21 error: unexpected token: `X`
    <anon>:2     ($s:ty) => {{ $s { key: 12345 } }}
                               ^~

Partial workaround for a more complicated test case (thanks to FreeFull on IRC):

    macro_rules! make_thing_with_key {
        ($($s:ident)::+, $($f:ident : $e:expr),+) => {{
    	    $($s)::+ { key: 12345, $($f: $e),+ }
        }}
    }

    mod foo { pub struct X { pub key: u32, pub foo: &'static str, pub bar: &'static str } }

    fn main() {
        let x = make_thing_with_key!(foo::X, foo: "b", bar: "c");
    }

**Comment by oli-obk** [comment]
did you maybe want `ident`?

```rust
macro_rules! build_struct {
    ($s:ident) => {{
        $s { key: 12345 }
    }}
}

struct X { key: u32 }

fn main() {
    let x = build_struct!(X);
}
```

yields

```
<anon>:7:12: 7:20 warning: struct field is never used: `key`, #[warn(dead_code)] on by default
<anon>:7 struct X { key: u32 }
                    ^~~~~~~~
<anon>:10:9: 10:10 warning: unused variable: `x`, #[warn(unused_variables)] on by default
<anon>:10     let x = build_struct!(X);
                  ^
```

**Comment by steveklabnik** [comment]
Yes, @johnsoft , I think @oli-obk is correct. Since it's been a few days, I'm going to give this a close, but let us know if that's wrong and we'll re-open!
