### ISSUE TITLE
[docs] Replace "iterators" chapter in book with hoverbears' post

### ISSUE THREAD

**Issue by bguiz** [rust-lang/rust#25084]
I vote that we replace the current one with an adapted version of hoverbears' blog post "a journey into iterators", or at least, include some more of the examples from the blog post in the current version.

- Current one: https://doc.rust-lang.org/book/iterators.html
- Hoverbear's blog post: http://hoverbear.org/2015/05/02/a-journey-into-iterators/
- Having just gone through both of them, I think that while the former "gets the job done", the latter is a much much better intro to the topic!

CC @Hoverbear @steveklabnik

**Comment by steveklabnik** [comment]
They serve different purposes: Hoverbear's post is more of a general introduction to various iterators that are in the standard library, whereas the book's is an introduction to the general concept. Content like Hoverbears' post would be great for `std::iter`'s documentation.

@hoverbear, if you want to contribute any of your content upstream, please open a PR. Always happy to have additions.
