### ISSUE TITLE
Binary installers webpage is not served securely

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#25090]
The page at http://www.rust-lang.org/install.html cannot be accessed over https, which is definitely a page that warrants encryption. Ideally we'd have the entire subdomain accessible over https, but if nothing else that page needs it.

cc @brson

**Comment by bstrie** [comment]
Nominated because I think we all expect a lot of people to be using those pages as of 1.0.

**Comment by steveklabnik** [comment]
This should be on rust-lang/rust-www, no?

**Comment by alexcrichton** [comment]
triage: P-medium

**Comment by bstrie** [comment]
Looks like the page is now secured.
