### ISSUE TITLE
`bind()` for `std::net::TcpStream`

### ISSUE THREAD

**Issue by tilpner** [rust-lang/rust#25102]
[`std::net::TcpStream`](http://doc.rust-lang.org/nightly/std/net/struct.TcpStream.html) doesn't expose an API to bind to local IP addresses.

Python solves this with [an optional `source_address` argument](https://docs.python.org/3.4/library/socket.html#socket.create_connection).

[mio](https://github.com/carllerche/mio) seems to expose this with a [`bind`](http://carllerche.github.io/mio/mio/tcp/struct.TcpSocket.html#method.bind) method, and I think the standard library shouldn't omit such functionality.

**Comment by alexcrichton** [comment]
Thanks for the report! This is currently covered by the [std::net expansion](https://github.com/rust-lang/rfcs/issues/957) RFC issue, though, so closing in favor of that.

**Comment by richardwhiuk** [comment]
For anyone in the future,, you can do this using the `net2` crate - https://docs.rs/net2/0.2.32/net2/struct.TcpBuilder.html
