### ISSUE TITLE
`&..`: unexpected token ..

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#25119]
``` rust
fn main() { &..; }
```

```
<anon>:1:14: 1:16 error: unexpected token: `..`
<anon>:1 fn main() { &..; }
                      ^~
```

This may be on purpose, but if not, this is useful for passing `..` into generic APIs that take references.

**Comment by klutzy** [comment]
parser-lalr accepts `&..;` well: `(ExprAddrOf (ExprRange <none> <none>))`, so at least one of them is buggy.

**Comment by dgrunwald** [comment]
This is intentional in rustc. `..` is only accepted as expression in locations where `a..b` would also be accepted.

That is, because the parentheses in `&(a..b)` are required, they are also required in `&(..)`.

**Comment by brson** [comment]
Seems like expected behavior to me.
