### ISSUE TITLE
Cannot implement traits for pointers to types defined in the crate

### ISSUE THREAD

**Issue by michaelwu** [rust-lang/rust#25126]
Test case:
```
use std::default::Default;
use std::ptr;

struct Foo;

impl Default for *mut Foo {
    fn default() -> *mut Foo {
        ptr::null_mut();
    }
}

fn main() {}
```
Fails with 
```
<anon>:6:1: 10:2 error: the impl does not reference any types defined in this crate; only traits defined in the current crate can be implemented for arbitrary types [E0117]
<anon>:6 impl Default for *mut Foo {
<anon>:7     fn default() -> *mut Foo {
<anon>:8         ptr::null_mut();
<anon>:9     }
<anon>:10 }
```

**Comment by alexcrichton** [comment]
I believe that this is intentional because the type `*mut T` isn't really "owned" by any crate, and in this case the crate neither owns `Default` nor `*mut T`, so even though `Foo` is owned it doesn't pass the coherence rules. That being said I think it'd be fine to add `Default` implementations for pointers in the standard library :)

**Comment by SSheldon** [comment]
Just ran into this, @alexcrichton any insight on why pointers and references are treated differently in this regard?

It makes me think something's wrong when that code with pointers fails to compile but implementing the same thing with references works fine:
``` rust
use std::default::Default;

struct Foo;

impl<'a> Default for &'a Foo {
    fn default() -> &'a Foo {
        panic!();
    }
}

fn main() {}
```

**Comment by alexcrichton** [comment]
@SSheldon if it's specifically the `Default` trait then I'd guess it's b/c there's already an impl for raw pointers in the standard library, but not for references.
