### ISSUE TITLE
Rustdoc search for "slice" should have primitive as top result

### ISSUE THREAD

**Issue by ucarion** [rust-lang/rust#25167]
When browsing documentation and searching for "slice", the top three results are:

1. [`std::slice` the module](https://doc.rust-lang.org/std/slice/index.html)
2. [`std::raw::Slice` the struct representation](https://doc.rust-lang.org/std/raw/struct.Slice.html)
3. [`std::slice` the primitive](https://doc.rust-lang.org/std/primitive.slice.html)

I think `std::slice`-the-primitive should be the top result (it is currently the third result), because it tells me what I can do to a slice, which is usually what I'm wondering about when I search for "slice". `std::slice`-the-module gives meager documentation, and links to structs, which I'm comparatively rarely interested in.

/cc @steveklabnik since you're the documentation guy?

**Comment by cmr** [comment]
@alexcrichton do you know if the search indexing could have 'prioritizing' like this?

**Comment by killercup** [comment]
@cmr From a quick glance at rustdoc's `main.js`: [This sort function](https://github.com/rust-lang/rust/blob/05d5fcaa5ba0c385e1dc97037c89fae437634fc3/src/librustdoc/html/static/main.js#L288) seems to be responsible for setting the priority of results. The 'type' of result is currently only the second last criteria and orders by index of [this types array](https://github.com/rust-lang/rust/blob/05d5fcaa5ba0c385e1dc97037c89fae437634fc3/src/librustdoc/html/static/main.js#L18-L37).

So, making types more important, moving 'primitive' up in the types array (or adding a special case for primitives) are good options.

**Comment by cmr** [comment]
@killercup Sounds like you should make a PR!

**Comment by killercup** [comment]
Maybe over the weekend!
