### ISSUE TITLE
Normalize calling tcp.shutdown multiple times across OSes

### ISSUE THREAD

**Issue by seanmonstar** [rust-lang/rust#25164]
Calling `tcp.shutdown(how)` multiple times will return different values, depending on the OS. On Linux, it returns `Ok(())`, on OS X, it returns `ErrorKind::NotConnected`.

Perhaps this behavior could be made to be the same across platforms. If not, at the least, the docs should call it out.

Noticed from https://github.com/hyperium/hyper/issues/508

/cc @aturon @alexcrichton

**Comment by steveklabnik** [comment]
Tagging as libs until the decision is made that this is different across platforms.

**Comment by nagisa** [comment]
I don’t think we can do anything sensible here.

**Comment by steveklabnik** [comment]
Triage: re-tagging as docs to make mention of this
