### ISSUE TITLE
Rustdoc omits required brackets in type

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust#25183]
Example: http://doc.rust-lang.org/nightly/std/rt/unwind/type.Callback.html

Rustdoc displays the type as `&Any + Send`, which will fail to compile. The actual type (as can been seen from the source) is `&(Any + Send)`

**Comment by steveklabnik** [comment]
Triage: this type is gone. Not sure if there are other examples or not...

**Comment by kennytm** [comment]
Not fixed in 1.18:  
https://doc.rust-lang.org/1.18.0/std/panic/struct.PanicInfo.html#method.payload

Fixed in 1.19:   
https://doc.rust-lang.org/1.19.0/std/panic/struct.PanicInfo.html#method.payload
