### ISSUE TITLE
Add id values to rustdoc source view for convenient linking

### ISSUE THREAD

**Issue by jdm** [rust-lang/rust#25189]
It would be really nice to provide stable links in the source view for generated documentation. I envision providing ids for thinks like data types and function names, and perhaps method implementations; these would need to remain stable as long as the type names involved did not change.

**Comment by jdm** [comment]
As an example, http://doc.servo.org/src/script/dom/document.rs.html#struct-Document could link to the opening line of the declaration of the Document struct, by changing `<span class='ident'>Document</span>` to `<span class='ident' id='struct-Document'>Document</span>`.

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by steveklabnik** [comment]
The line number is linkable; it's not quite the same thing. @rust-lang/rustdoc is this a feature we'd consider adding? It seems like a marginal improvement to me.

**Comment by GuillaumeGomez** [comment]
Ids have been somewhat stable for quite some time now, aren't they?

**Comment by steveklabnik** [comment]
Not in the source view, right?

**Comment by GuillaumeGomez** [comment]
In the source view, the ids are literally line numbers.

**Comment by steveklabnik** [comment]
Right, this ticket is asking for

> I envision providing ids for thinks like data types and function names, and perhaps method implementations; 

in addition to that.

**Comment by GuillaumeGomez** [comment]
I have difficulties to understand what need it would fulfil...

**Comment by jdm** [comment]
Me too! No need to debate this further; github links to specific revisions work fine.
