### ISSUE TITLE
ScopedKey<T> has unnecessary implicit Sized bound

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust#25193]
ScopedKey only ever deals with references or pointers to T, so the Sized bound is unnecessary. This is required for storing trait objects and other DSTs in a `scoped_thread_local!`

I'll submit a PR fixing this imminently.

**Comment by alexcrichton** [comment]
The associated PR ended up being closed because the OS actually only allows us to store one pointer, so I think that we're going to stick with this for now. We can possibly expand it in the future if necessary.
