### ISSUE TITLE
0u8..-1 compiles without warning

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#25206]
`0u8..-1` compiles, runs (as 0..255) without warning or error. Debug assertions don't fire.

We error on `0..-1u8` **error: unary negation of unsigned integers may be removed in the future**.

We can't "fix" this backwards compatibly after 1.0.

`0u8..-1` should either warn or trip debug assertions.

**Comment by bombless** [comment]
Hmm we cannot add warning because of compatibly?
I just want to make sure...

**Comment by bluss** [comment]
We can add a warning, but to make it a hard error would be breaking.

**Comment by nagisa** [comment]
I believe this behaviour is intentional because people want to do bit fiddling and can’t be bothered to use `!0` (bitwise-not 0). We had a chance to make this to be a compile-time error, but no consensus was reached.

**Comment by nagisa** [comment]
I think this should error the same way as `0u8..-1` case errors, for consistency with `let x: u8 = -1`, which also errors.

**Comment by bombless** [comment]
FWIW, I think we are contributing to Rust 1.1, so it's fine to break some 1.0 code.

**Comment by Stebalien** [comment]
@bombless Point releases are not allowed to introduce backwards incompatible changes (except bug fixes). Only major releases (2.0) can do that.

**Comment by nagisa** [comment]
We could always make it a warning for 1.x series and note it will become an error in next major release.

**Comment by bombless** [comment]
Hmm if somebody's quick enough to make a patch then we can backport it to beta branch and fix this in time. Also this can be considered a bug anyway.
