### ISSUE TITLE
Hang of rustc (1.1.0-nightly)

### ISSUE THREAD

**Issue by dpc** [rust-lang/rust#25205]
https://travis-ci.org/dpc/rdu/builds/61730951

Code that triggers the hang:

https://github.com/dpc/rdu/tree/fc5c6a26129ed5c5960fe1d30a3c256b03be0713

**Comment by dpc** [comment]
It seems the the problem is with recursive:

```
fn visit_dirs<F : FnMut(&Path), E : FnMut(&Path, io::Error)>(dir: &Path, fs : Option<u64>, mut cb: F, mut err: E) {
...
}
```

https://github.com/dpc/rdu/blob/fc5c6a26129ed5c5960fe1d30a3c256b03be0713/src/main.rs#L104

as the code compiles just fine when I change it to dynamic dispatch.

**Comment by eefriedman** [comment]
The "compiletime" label seems wrong: this can't compile.  There's an infinite monomorphization loop.

Reduced example:

```rust
use std::io;
use std::path::Path;
fn visit_dirs<F : FnMut(&Path), E : FnMut(&Path, io::Error)>(dir: &Path, fs : Option<u64>, mut cb: F, mut err: E) {
    visit_dirs(&dir, fs, |p| cb(p), |p, e| err(p, e));
}
fn main() {
    visit_dirs(Path::new("foo.txt"), None, |p|{}, |p,e|{});
}
```

**Comment by eefriedman** [comment]
Oh, and this appears to be fixed; on nightly, it gives "error: reached the recursion limit during monomorphization".

**Comment by steveklabnik** [comment]
Yup, it's fixed on nightly. Thanks @dpc for reporting and @eefriedman for double-checking!
