### ISSUE TITLE
std::net::TcpStream::set_nodelay marked as unstable

### ISSUE THREAD

**Issue by icorderi** [rust-lang/rust#25201]
Guys, any particular reason disabling Naggles is still marked as unstable?
- [set_nodelay] current code.
- [doc] for beta4.

[set_nodelay]: https://github.com/rust-lang/rust/blob/70db76602e0fbd88c718e4f564b90a8819978773/src/libstd/net/tcp.rs#L129-L132

[doc]: http://doc.rust-lang.org/1.0.0-beta.4/std/net/struct.TcpStream.html#method.set_nodelay

**Comment by alexcrichton** [comment]
Thanks for the report! The current suite of setting various options for a `TcpStream` and friends has not received the amount of scrutiny expected from a stable API, and requires thought to consider expansion of the API to more socket options in the future as well as how it plays into other kinds of sockets and such. 

We've currently [got an RFC issue open](https://github.com/rust-lang/rfcs/issues/957) about the expansion of the `std::net` API surface area, and this falls under the category of "More socket options" at the bottom. I hope to write an RFC quite soon for these APIs which will then be slated to hopefully be included as `#[stable]` in the 1.2 release.

In the meantime, however, the `AsRawFd` and `AsRawSocket` traits are `#[stable]` on Rust master so you can set the options manually (albeit somewhat painfully).
