### ISSUE TITLE
Waste memory in comparison with Golang or C

### ISSUE THREAD

**Issue by nareix** [rust-lang/rust#25202]
http://benchmarksgame.alioth.debian.org/u64q/rust.html

**Comment by oli-obk** [comment]
I'm confused. Compared to golang rust actually uses half the memory in the `k-nucleotide` benchmark. all other benchmarks are about the same in rust, go and c. Please provide more information in the bug-report than a link to a benchmarking webpage. Something like the used code, the resulting memory use and the compiler-flags used.

**Comment by sparrisable** [comment]
Rust uses 10 times as much memory in the n-body benchmark:

n-body 	
Rust         4,972
C gcc       436

**Comment by sparrisable** [comment]
Some compiler flags for convenience:

/usr/local/src/rust-1.0.0-beta/rustc/bin/rustc -C opt-level=3 -C target-cpu=core2 -C lto nbody.rs -o nbody.rust_run

/usr/bin/gcc -pipe -Wall -O3 -fomit-frame-pointer -march=native -mfpmath=sse -msse3 nbody.gcc-4.c -o nbody.gcc-4.gcc_run -lm
rm nbody.gcc-4.c

**Comment by oli-obk** [comment]
> Huge differences in default memory allocation don't necessarily mean there'll be huge differences in Memory-used for tasks that require memory to be allocated:
	Java 	C 	Free Pascal 	
	13,996KB 	320KB 	8KB 	n-body

The [faq says this is a non-issue in the n-body program](http://benchmarksgame.alioth.debian.org/play.html#whymemory).

**Comment by steveklabnik** [comment]
While it's generally a good idea to improve these benchmarks, unless there's something _specific_ that's a bug in Rust itself, it doesn't really belong here as an issue. Many of the benchmarks for the Shootout don't even compile at the moment.
