### ISSUE TITLE
Cannot expand ty into a generic function constraint during macro expansion

### ISSUE THREAD

**Issue by thelink2012** [rust-lang/rust#25236]
In a macro, whenever a `ty` is expanded into a generic function constrait an error gets issued during the macro expansion.

This (http://is.gd/nJgJwq)

```
use std::ops::Add;

macro_rules! test {
    (
        fn fun<F: $f_type:ty>();
    ) => {
        fn fun<F: $f_type>(_f: F)  {}
    }
}

test! {
    fn fun<F: Add>();
}
```

Gives

```
<anon>:7:19: 7:26 error: expected one of `,`, `=`, `>`, or `?`, found `Add`
<anon>:7         fn fun<F: $f_type>(_f: F)  {}
```

And moving the F into a `where` in the expansion block doesn't fix it but gives another message (http://is.gd/93BKLN):

```
<anon>:7:32: 7:42 error: each predicate in a `where` clause must have at least one bound in it
<anon>:7         fn fun<F>(_f: F) where F: $f_type  {}
                                        ^~~~~~~~~~
<anon>:7:35: 7:42 error: expected one of `,`, `?`, or `{`, found `Add`
<anon>:7         fn fun<F>(_f: F) where F: $f_type  {}
                                           ^~~~~~~
```

For the sake of testing purposes I tried other types instead of `ty` in the macro and `ident` worked, however only for simple names like `Add`, when names such as `ops::Add` or `Fn(i32)` are used errors are issued (http://is.gd/PJDQbY):

```
`<anon>:15:15: 15:17 error: no rules expected the token `::`
<anon>:15     fn fun<ops::Add>();
                        ^~
```

## Meta

All the tests were conducted on the playpen using the nightly and beta option (no difference) so I'm not sure about the version but the issue also happens on my local installation `rustc 1.0.0-beta.3 (5241bf9c3 2015-04-25) (built 2015-04-25)` _(yep a bit outdated but cba to update eh)_.

**Comment by eddyb** [comment]
This is not a bug, `Add` there is not a type, but a trait reference, which doesn't have a fragment specifier in `macro_rules`.
To get `ops::Add` working, `path` might work. `$(<$($t:type),*>)*` would allow you to pass type parameters. `Fn(A) -> R` is harder to support, but perhaps not impossible.

**Comment by thelink2012** [comment]
Additionally the `ty` doesn't work when it's followed by `>>` (double closing a generic) but `>` works. (http://is.gd/ehawq8).
Well if those are limitations of the grammar too bad :/

**Comment by steveklabnik** [comment]
Since this isn't a bug, I'm giving it a close.

**Comment by steveklabnik** [comment]
re-opening due to the `>>` issue. I'm not 100% sure if this is intended or not

**Comment by thelink2012** [comment]
Nah, let me just open another issue because organization.
#25274
