### ISSUE TITLE
std::iter::Iterator::Item url is broken (both beta and nightly)

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#25245]
Like said in the title, the page referenced by this link doesn't lead anywhere.

**Comment by Stebalien** [comment]
For the lazy: http://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html?search=std%3A%3Aiter%3A%3AIterator%3A%3AItem
Yields this (non-existent) link: http://doc.rust-lang.org/nightly/std/iter/Iterator/associatedtype.Item.html

**Comment by Stebalien** [comment]
Dup of #22442.

**Comment by GuillaumeGomez** [comment]
@Stebalien: Thanks, I close it then.
