### ISSUE TITLE
TRPL: Explain Bottom and Unit Types

### ISSUE THREAD

**Issue by killercup** [rust-lang/rust#25244]
The book currently lacks any mention of these two special types:

- The bottom type, `!`, which denotes there is no type (this e.g. the type of a function that does not return) and
- the unit type, `()`, which is basically an empty tuple and thus a type with exactly one variant.

@steveklabnik, I wanted to make a PR for this, but I wasn't sure where to add this. The ["Primitive Types"](http://doc.rust-lang.org/nightly/book/primitive-types.html) chapter seems to cover the topic of types, but people read about `bool`, `str` and `i32` are probably not looking for type theory material…

**Comment by steveklabnik** [comment]
The unit type no longer exists, and ! is mentioned, though I forget where at the moment.

**Comment by killercup** [comment]
Oh, okay. What is the type of `()` and how should I pronounce it? Empty tuple?

Bottom is used in http://doc.rust-lang.org/nightly/book/lang-items.html but I couldn't find the word 'bottom' being used to describe a type in `src/doc/`. Do we call it something else?

Wikipedia mentions Rust, by the way: https://en.wikipedia.org/wiki/Unit_type and https://en.wikipedia.org/wiki/Bottom_type

**Comment by killercup** [comment]
@steveklabnik, never mind, I found it: [Diverging functions](http://doc.rust-lang.org/nightly/book/functions.html#diverging-functions)

**Comment by steveklabnik** [comment]
I don't think ! Is technically a bottom type.

The type of () is just a zero-sized or empty tuple, yes.

It's not particularly surprising that Wikipedia is outdated, heh. We _did_ have an express unit type before, it's just gone now.

**Comment by jakub-** [comment]
The unit type was removed from the compiler implementation for convenience reasons but that doesn't mean we're not allowed to pretend it exists in user-facing terminology and documentation, including TRPL, if it's deemed beneficial for didactics.

**Comment by steveklabnik** [comment]
>  that doesn't mean we're not allowed to pretend it exists

I feel very strongly that we are not allowed. Teaching something that doesn't actually exist isn't a good idea.

**Comment by jakub-** [comment]
> I feel very strongly that we are not allowed. Teaching something that doesn't actually exist isn't a good idea.

Poor wording on my part. It does exist, it just has a different name (nullary tuple).

This particular issue is obviously insignificant but on a meta level it seems like giving names to entities that aren't necessarily formally distinct, when such a simplification benefits the learning process of the student, is a valid thing to do in teaching, and is also quite common.

**Comment by pnkfelix** [comment]
I agree with @jakub- : I plan to continue referring to `()` as "unit", even if it's just a short hand  for "empty tuple".  (See also discussion here: https://github.com/rust-lang/rust/pull/24738#issuecomment-96245868 )

It has a special role in the language so special treatment is justifiable.

**Comment by graue** [comment]
There are several places where the reference doc mentions "unit" or "the unit type" with an associated link to the "[Primitive types](http://doc.rust-lang.org/nightly/reference.html#primitive-types)" section. Example: "If a `main` function is present, its return type must be `unit`" in section 5. However, nothing in that section mentions the unit or empty tuple type.

Suggestion: add a sentence about it to the "[Tuple types](http://doc.rust-lang.org/nightly/reference.html#tuple-types)" section, and update these references to link there. The mention could be something like,

> For historical reasons and convenience, the tuple type with no elements (`()`) is sometimes called "unit".

**Comment by suhr** [comment]
Should translations use analog of the “unit type/value” term or just use “empty tuple” everywhere?

**Comment by steveklabnik** [comment]
Okay, so, after having some discussions with people, I understand where my historical confusion comes from. Ignoring that, however, I agree with @graue wrt how a patch for this should go.
