### ISSUE TITLE
primitive types don't have a [src] link

### ISSUE THREAD

**Issue by cgaebel** [rust-lang/rust#25269]
Consider [this page](http://doc.rust-lang.org/std/primitive.slice.html).

There's no `[src]` links to anything. No methods, no file, nothing. Ideally, they'd be back to where they were before. :)

**Comment by steveklabnik** [comment]
yes, this is because they're primitive, built-in types. They don't really work the same way as everything else.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this as fixed -- there are source links for some things now, e.g. methods on primitive pages, and I don't see anything missing.
