### ISSUE TITLE
Incorrect "error: private type in exported type signature"

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust#25260]
The following code will fail to compile:
```rust
pub trait Test {
    type Result;
}

mod Foo {
    pub struct Ty;
}

struct Bar;

impl Test for Foo::Ty {
    type Result = Bar;
}

fn main() {
}
```

When in fact no private types are exported.

**Comment by alexcrichton** [comment]
This is actually currently working as intended I believe. The definition of a "public signature" is that the type `Ty` is marked `pub`, so it's considered a public type subject to the privacy rules. You can find more details in the [associated RFC](https://github.com/rust-lang/rfcs/blob/master/text/0136-no-privates-in-public.md)

**Comment by Diggsey** [comment]
If so, that's disappointing. It seriously hinders the ability to make some patterns modular.

In the example, there's no way to access `Foo::Ty` from the outer scope without making it public, and yet to do so forces other types to be exported from that scope!
