### ISSUE TITLE
`make check` fails on Windows due to check-sanitycheck

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#25265]
check-sanitycheck.py uses Unix-only module `resource`, `make check` runs `check-sanitycheck` and therefore fails on Windows
```
Traceback (most recent call last):
  File "C:/msys64/home/rust/src/etc/check-sanitycheck.py", line 16, in <module>
    import resource
ImportError: No module named resource
```
Workaround: use `make tidy && make check-notidy` instead of `make check`

cc @richo

**Comment by richo** [comment]
Oof, sorry! Having a look now

**Comment by richo** [comment]
What version of python and windows are you on? I was fairly sure that I confirmed this did something reasonable on not-posix, but I do not in fact have a windows box to test on. I'm kinda confused about how the builders are working right now.

**Comment by petrochenkov** [comment]
msys2 x64 on Windows 7
