### ISSUE TITLE
Advertise impls of out-of-create traits for third party types with some type parameters set to in-crate types in rustdoc

### ISSUE THREAD

**Issue by reem** [rust-lang/rust#25264]
As an example, in iron, the impls of `Modifier<Response>` for std types like `String`, `File`, and `Path` are not advertised anywhere in the generated documentation.

**Comment by jashephe** [comment]
Just wanted to add in, this would be useful for rust-gnome as well, because we're starting to have a few cross-crate trait impls, and, as of now, have no easy way of documenting them.

**Comment by steveklabnik** [comment]
Triage: no change. Given that this is an open set of things, I'm not sure it's something that can ever really be done...

**Comment by QuietMisdreavus** [comment]
Just to clarify this: You want to be able to show a trait implementation when one of its type parameters is a local type? i.e. `impl From<LocalType> for ForeignType` would show on `LocalType`'s page? That might not take *too* much work, but i'd like to make sure that that's what's being requested.

**Comment by jethrogb** [comment]
> Given that this is an open set of things, I'm not sure it's something that can ever really be done...

Because of the coherence rules, impls can only be defined in one place depending on the types they reference. That's the place they should be documented as well.

**Comment by jethrogb** [comment]
#42440 was labelled C-bug but this is labelled C-enhancement

**Comment by QuietMisdreavus** [comment]
I'll swap the labels, since this is a shortcoming of the generated docs.

**Comment by QuietMisdreavus** [comment]
I've opened https://github.com/rust-lang/rust/pull/44969 to fix this.
