### ISSUE TITLE
rustdoc feature - Documentation on impl blocks

### ISSUE THREAD

**Issue by thepowersgang** [rust-lang/rust#25296]
Add a way to document an entire `impl` block.

This will allow documenting quirks of implementations, like that `io::Read` on `&[u8]` updates the pointer. It could also be used to document groups of methods on a type (that relate to the same concept, e.g. the same enum variant)

**Comment by reem** [comment]
This would be really useful in iron as well, for documenting implementations of `Modifier<Request | Response>` as well as `Plugin<Request | Response>`.

**Comment by bluss** [comment]
This is already present. Just put the doc comment on top of the `impl X for Foo ` block. Previously,

**Comment by steveklabnik** [comment]
@thepowersgang @reem have you checked out what @bluss is saying? Does this already work?

**Comment by thepowersgang** [comment]
... confirmed. While rustdoc doesn't show the docs for implementations on the trait's page, it does show them on the type's page.
