### ISSUE TITLE
Macro documentation links to an empty page

### ISSUE THREAD

**Issue by graue** [rust-lang/rust#25305]
The `macros` link [from the API docs index](http://doc.rust-lang.org/1.0.0-beta.4/std/#the-rust-prelude-and-macros) goes to an [empty page](http://doc.rust-lang.org/1.0.0-beta.4/std/macros/). Should this link to the [prelude docs](http://doc.rust-lang.org/1.0.0-beta.4/std/prelude/) instead? It looks like if you go there, the macros (like `println!`) are listed on the left sidebar.

**Comment by steveklabnik** [comment]
There's no particular module for macros anymore, nice catch! 

Every doc shows those macros on the left. It might be better to split the macros bit away from the prelude, and just give them their own section here. What do you think?

**Comment by Anachron** [comment]
Even though I'm not the owner of this ticket, I agree.

**Comment by steveklabnik** [comment]
This has since been fixed, as the main section was reorganized.
