### ISSUE TITLE
make: stale diagnostics info in .json files can break unclean builds

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#25364]
make: error E0038 from `librustc' also found in`tmp/extended-errors/librustc_typeck.json' (from unclean build?)

That is, I did a `git pull` up to:

```
commit fa433875274ff4a7c4cab7d87c1284ba782ef643
Merge: 30a42fa b799cd8
Author: bors <bors@rust-lang.org>
Date:   Wed May 13 06:43:05 2015 +0000

    Auto merge of #24619 - nrc:rc-coerce, r=nikomatsakis

    r? @nikomatsakis (note a few TODOs left in the code where I wasn't sure about stuff).
```

in a build directory that already had artifacts from a prior build lying around.

I re-ran `configure` (something I do sometimes when `git pull`'ing with an unknown set of changes):

```
/Users/fklock/Dev/Mozilla/rust.git/configure --enable-debug --enable-optimize     --enable-ccache --enable-clang --prefix=~/opt/rust-dbg --disable-optimize-tests --disable-llvm-assertions 
```

And then when attempting the build, I got this:

```
rustc: x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/librustc
/Users/fklock/Dev/Mozilla/rust.git/src/librustc/lib.rs:170:1: 170:52 error: error E0038 from `librustc' also found in `tmp/extended-errors/librustc_typeck.json'
/Users/fklock/Dev/Mozilla/rust.git/src/librustc/lib.rs:170 __build_diagnostic_array! { librustc, DIAGNOSTICS }
                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
```

**Comment by pnkfelix** [comment]
(I am now double-checking whether a build from a fresh directory gets rid of the problem, as I assume it will.  If so, then this is a relatively low priority ticket -- potentially even closable if the problem does not re-exhibit itself after that fresh build finishes...)

**Comment by pnkfelix** [comment]
A build in a fresh directory does not exhibit the problem on the first build, but if you immediately follow it by another call to `make`, two bad things happen:

 * The successive call to `make` seems to think that a rebuild of
    ```
    rustc: x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/librustc
    ```
is necessary, even though we just finished a build.  (That to me is a sign that our dependencies are broken in some way.)

 * This attempt to build that library immediately fails, again due to the "error also found in json file" problem that I am listing in this ticket.

**Comment by pnkfelix** [comment]
Ah, I think I see the problem: our diagnostics plugin works by treating the json files as representing the error codes registered by all the crates.

But if there's a json file lying around from a previous build for a crate that we have not yet rebuilt, then we can erroneously load it in and report a conflict.

(Unfortunately in my experience `make` is not so great at encoding the production of side-products, e.g. these .json files, in its rules.)

Anyway, the simplest thing *might* be to add a make rule that just deletes the .json files if they predate any of the files from its origin crate.  I will see what I can do about that.

**Comment by pnkfelix** [comment]
oh wait, this approach might be bad ... it might cause `libsyntax` to be rebuilt when any `rustc` crate changes, even when the json file is not deleted.

I ... need to think about this.  I had considered trying to use an `order-only` dependency, but I am not sure that can fix things here.  I'll leave this PR open in the hopes that a reviewer can suggest a fix, but this should not get checked in until I resolve this.

**Comment by pnkfelix** [comment]
See also PR #25592, which notes that in addition to the bug outlined here, there is also the issue that:

> The code does not currently handle concurrent compilations where JSON files in the metadata directory may be half-written and hence contain invalid JSON when read.

**Comment by steveklabnik** [comment]
Triage: hopefully fixed by rustbuild?

**Comment by alexcrichton** [comment]
I think we've since fixed this, so closing.
