### ISSUE TITLE
Check types in method signatures

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#25388]
We don't check that types in method signatures are well-formed, or even when they are Sized. I mean, this compiles:
```Rust
pub struct U<T: Send+Sync+Copy+::std::fmt::Display>(*const T);

pub trait Trait { }

pub trait OtherTrait {
    fn f(self, u: U<Trait>);
    fn g(self, u: [u8]);
}

impl OtherTrait for () {
    fn f(self, u: U<Trait>) { }
    fn g(self, ref u: [u8]) {}
}

fn main () {}
```

**Comment by arielb1** [comment]
Fixing this seems 1) important but 2) kind-of backward-compatibility breaking

**Comment by apasel422** [comment]
Related to #19182.

**Comment by nikomatsakis** [comment]
We intentionally chose not to check that argument types are `Sized` in trait definitions. We do check it when the method is implemented, and the full type is known, and we check that values we actually pass as arguments are sized. (Moreover, at least for now, if two types are related by subtyping, then either both are sized or neither is.) So I don't think that's a big problem. But I agree we need to cleanup some corner cases of WF.
