### ISSUE TITLE
LLVM -O2 compile time regression

### ISSUE THREAD

**Issue by seanmonstar** [rust-lang/rust#25393]
`rustc 1.1.0-nightly (9ecc9896d 2015-05-10) (built 2015-05-11)`

time: 58.110    LLVM passes

vs

`rustc 1.1.0-nightly (c2b30b86d 2015-05-12) (built 2015-05-13)`

time: 785.935   LLVM passes

running `cargo rustc --release -- -Z time-passes --test` on hyper@0.5.0

Full output at https://gist.github.com/seanmonstar/390e04d63ad28f234050

**Comment by huonw** [comment]
cc @nrc (There's a slight suspicion that this may be caused by #24619, since that's touching trans/codegen.)

**Comment by seanmonstar** [comment]
ran with `rustc 1.1.0-nightly (4b88e8f63 2015-05-11) (built 2015-05-12)`, got `time: 58.253    LLVM passes`

**Comment by nrc** [comment]
cc @eddyb

**Comment by eddyb** [comment]
@seanmonstar Could you provide `.ll` files for before and after? Hopefully `cargo rustc --emit=llvm-ir` should work now.

**Comment by seanmonstar** [comment]
@eddyb https://gist.github.com/seanmonstar/b302a74d1e0aea3a59e2

**Comment by dotdash** [comment]
Looks like this is caused by https://github.com/kballard/rust/commit/e1e34e9275918679336210874f8dd770323daa81 -- the assume intrinsics no longer get simplified into nonnull metadata on load instructions and cause massive slowdowns.
