### ISSUE TITLE
Lifetime documentation should include an example where the lifetime of a return is dependent on two arguments

### ISSUE THREAD

**Issue by brianquinlan** [rust-lang/rust#25417]
The document page:
https://doc.rust-lang.org/book/lifetimes.html

For example:
fn <'a>a_or_b(a : &'a str, b : &'a str)  -> &'a str

**Comment by steveklabnik** [comment]
There is an example of the syntax in the elision section, but you're right that more and better examples would be good here, for sure.

**Comment by brianquinlan** [comment]
What example were you thinking of? I couldn't see one.

**Comment by steveklabnik** [comment]
Oh, two of the same! I was looking at

```
fn frob(s: &str, t: &str) -> &str; // ILLEGAL, two inputs
fn frob<'a, 'b>(s: &'a str, t: &'b str) -> &str; // Expanded: Output lifetime is unclear
```

**Comment by brianquinlan** [comment]
Yes, two of the same. I guessed the syntax would be:
fn <'a,'b>a_or_b(a : &'a str, b : &'b str) -> &'a 'b str

but I was wrong :-)
