### ISSUE TITLE
Return Char iterator from string functions like find and rfind.

### ISSUE THREAD

**Issue by SDX2000** [rust-lang/rust#25427]
What is the point of returning an index into a string from functions like [find](doc.rust-lang.org/std/primitive.str.html#method.find) and rfind if you cannot index strings in Rust? I would recommend changing these functions to return a char iterator instead.

**Comment by huonw** [comment]
One can interact with strings via methods like `char_at` (indexing `char`s via byte indices) and slicing, e.g. `&s[i..]`.

**Comment by shepmaster** [comment]
Those functions are now stable (hooray 1.0!), so they couldn't be *changed* if we wanted. However, I very much use the slicing form, which is quite useful!

**Comment by SDX2000** [comment]
Isn't char_at() O(n) and marked as unstable? However I agree slices are a good argument for returning indices.

**Comment by huonw** [comment]
`char_at` is O(1).
