### ISSUE TITLE
Improve the E0106/E0107 descriptions

### ISSUE THREAD

**Issue by viraptor** [rust-lang/rust#25424]
Hi, I keep running into issues with the lifetime specifiers/parameters missing which result in the E0106/E0107 errors, but even with some experience I get confused which exact place the error is about.

I think some hints like:
- `&Object` -> `error: missing lifetime specifier (did you mean &'a Object ?) [E0106]`
- `&Object` -> `error: wrong number of lifetime parameters: expected 1, found 0 (did you mean &Object<'a> ?) [E0107]`

would be great. I understand the error message already says this, but from the beginning it tripped me up more times than anything else.

**Comment by steveklabnik** [comment]
Error messages have undergone a total overhaul since this ticket was filed; as such, I'm going to give it a close.

@viraptor if you still find some of these messages confusing, please open new tickets, and include code that triggers the error please! Thanks.
