### ISSUE TITLE
Machine Readable File Describing Error Codes

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#25425]
I'm the author of rustbot on Moznet, and I'm adding an `!error <code>` command. I figured that if there was an easy way to get a summary of the error, I'd post the error summary and a link to the full description, but there's no machine readable (e.g., JSON or TOML) description of the error codes. As I cannot be the only person who might find such a thing useful (e.g. IDEs), I'm filing this issue requesting that such a machine readable file be made when making rustc's documentation.

``` json
{
    "E0001": {
        "name": "Dead Match Arm",
        "summary": "An expression arm corresponding to a noted pattern will never be reached.",
        "description": "This error suggests that the expression arm corresponding to the noted pattern will never be reached as for all possible values of the expression being matched, one of the preceding patterns will match.\nThis means that perhaps some of the preceding patterns are too general, this one is too specific or the ordering is incorrect."
    },

    "...." : {}
}
```

A question that has to be asked is what the keys will be. Will it be "E1" or "E0001" or something else? Also, how will code examples in the description be handled, e.g. [E0007](http://doc.rust-lang.org/error-index.html#E0007)?

---

As a side note, having a name and summary for each error would also help tremendously. Right now it's just a numeric code and a full description. I included them in the above example JSON file. Otherwise, it'd just be an object with just a description property.

**Comment by huonw** [comment]
There is JSON output: https://github.com/rust-lang/rust/pull/24884

**Comment by Havvy** [comment]
Ah, I asked @steveklabnik on IRC and he said there wasn't.

Is this JSON file accessible online somewhere?  [I asked @huonw on IRC and he doesn't know.]

**Comment by Havvy** [comment]
It looks like the environmental variable `ERROR_METADATA_VAR` is not set, the JSON file gets deleted. Is this variable set for the build that rust-lang's documentation is built from?

**Comment by steveklabnik** [comment]
Triage: lots of changes in errors, we might be moving away from codes? I think @jonathandturner told me that. Anyway, this is still a valid ticket.

**Comment by jonathandturner** [comment]
We're keeping error codes for now, we're just thinking of moving away of using them in --explain in the future, and instead having an expanded error format that uses the actual code the user wrote.

**Comment by Mark-Simulacrum** [comment]
To my knowledge we've not yet changed anything here. Arguably, this is also relevant for discussion elsewhere that wants to rewrite long error diagnostic extraction to take a different approach.

**Comment by Havvy** [comment]
Since this is an enhancement that nobody is going to be working on in the near to medium term, I'm going to close it.
