### ISSUE TITLE
`&-ptr` should be less used in compiler errors

### ISSUE THREAD

**Issue by barosl** [rust-lang/rust#25426]
When comparing mismatched types, today's rustc prints `&-ptr` when one of the types is a reference. For example,

```
 expected `&i32`,
    found `f64`
(expected &-ptr,
    found f64) [E0308]
```

```
expected `core::result::Result<_, &str>`,
    found `core::result::Result<i32, collections::string::String>`
(expected &-ptr,
    found struct `collections::string::String`) [E0308]
```

There might be reasons for this, but it's inconvenient in many cases. If the compiler is giving attention to the &-difference of the two types, it should print `&-ptr` only when the two compared types could be deduced from one type. (e.g. `&i32` and `i32`) But in general, if those two types are fairly distinct, just printing the full type name would be much more handy.

**Comment by arielb1** [comment]
We currently just print the non-matching type constructors - I mean, should we also do this between `Box<T>` and `U`? Between `Option<T>` and `U`?

**Comment by Manishearth** [comment]
I think we should go one level deeper if we find a sigil-based type constructor.

No, no need to do this with box, because that is a textual type ctor.

**Comment by steveklabnik** [comment]
I believe this changed recently, and it seems so:

```rust
error[E0308]: mismatched types
 --> foo.rs:2:19
  |
2 |     let y: &i32 = 5.0f64;
  |                   ^^^^^^ expected &i32, found f64
  |
  = note: expected type `&i32`
  = note:    found type `f64`
```

Closing!
