### ISSUE TITLE
Small errors in stable dining philosophers example

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#25430]
http://doc.rust-lang.org/stable/book/dining-philosophers.html

I can't fix these myself until later, anyone else  want to do it? cc @steveklabnik @killercup @geofft

> Here, we make a [struct][struct] to represent a philosopher. For now, a name is all we need. We choose the [String][string] type for the name, rather than &str.

The links here are broken

> While this is only five lines, they’re a dense four. Let’s break it down.

Should be: "While this is only five lines, they’re a dense five. Let’s break it down."

> If you run this program, you’ll see that the philosophers eat out of order! We have mult-threading!

* multi-threading

**Comment by killercup** [comment]
'Multi-threading' already fixed by #25360

**Comment by killercup** [comment]
@parir wins this one! :)
