### ISSUE TITLE
Life time documentation: mixed up wording in last paragraph of the first section

### ISSUE THREAD

**Issue by SDX2000** [rust-lang/rust#25438]
Change: We need to ensure that any reference to a Foo cannot outlive the reference to an i32 it contains.
to: We need to ensure that any reference to the contained i32 does not outlive the containing Foo.

**Comment by SDX2000** [comment]
Link: https://doc.rust-lang.org/book/lifetimes.html

**Comment by steveklabnik** [comment]
Sure, I would accept this. Mind sending a PR?
