### ISSUE TITLE
Improve diagnostics for drop order borrowck bugs

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#25433]
See http://www.reddit.com/r/rust/comments/361vy6/how_to_get_around_with_does_not_live_long_enough/.compact

When there's a borrowck bug that arises due to the LIFO drop ordering; we should mention this in a note.

**Comment by steveklabnik** [comment]
```text
   = note: values in a scope are dropped in the opposite order they are created
```

🎊
