### ISSUE TITLE
1.0 release should be tagged in Git

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#25442]
It is currently not tagged in git.

https://github.com/rust-lang/rust/tags

**Comment by alexcrichton** [comment]
Don't worry, it's coming! We plan on tagging and pushing tonight at the 1.0 release party in SF :)

**Comment by frewsxcv** [comment]
Excellent!

![](https://cloud.githubusercontent.com/assets/416575/7659202/450f5aac-fb0e-11e4-9ef8-cdea68b96af5.gif)

**Comment by frewsxcv** [comment]
This was added three hours ago

https://github.com/rust-lang/rust/releases
