### ISSUE TITLE
Missing signatures in .msi files

### ISSUE THREAD

**Issue by MichalStaruch** [rust-lang/rust#25457]
Both .msi files (32- and 64-bit) for Rust 1.0.0 are missing signatures, resulting in unknown publisher warning when running installer on Windows.

**Comment by alexcrichton** [comment]
cc @brson, @vadimcn

**Comment by vadimcn** [comment]
Signing is easy; obtaining a cert and securely storing the private key are usually the sticking points of the process.   How do other Mozilla projects deal with build signing?

**Comment by ismail** [comment]
This is still true for 1.7.0 release, it would be immensely helpful if you could sign your releases.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/27694, which I'm making the canonical "we should sign things" issue.
