### ISSUE TITLE
release tarball gid too large for windows

### ISSUE THREAD

**Issue by rillian** [rust-lang/rust#25461]
On Mozilla build machines:

```
15:24:30     INFO -  + tar xf rust-1.0.0-i686-pc-windows-gnu.tar.gz
15:24:30     INFO -  tar: Archive value 197121 is out of gid_t range 0..65535
```

It would be nice if we're being compatible generating tar.gz to make it work with obsolete tar implementations. Otherwise it could be tar.xz.

**Comment by bltavares** [comment]
Triaging: On the [download official webpage](https://www.rust-lang.org/downloads.html) there is no option to download the `.tar.gz` package for windows, but it is available on the [archives](https://static.rust-lang.org/dist/index.html).

I don't have access to a Windows machine at this moment to check if this is still an issue.

**Comment by brson** [comment]
Is it possible to set the gid to 0 when the tarball is created?

**Comment by rillian** [comment]
GNU `tar` has a `--group=0` option for this.

**Comment by Mark-Simulacrum** [comment]
Triage: We still produce artifacts with the same group number: 197121.

Determined by downloading the tarball for windows and running: `tar -v --numeric-owner -t -f ./rust-nightly-i686-pc-windows-gnu.tar.gz rust-nightly-i686-pc-windows-gnu/ | head`.
