### ISSUE TITLE
Performance regression compiling glium

### ISSUE THREAD

**Issue by XMPPwocky** [rust-lang/rust#25478]
http://github.com/tomaka/glium

Used to take <10 minutes to compile in release builds, but with nightly (5/15/15) I'm sitting at around the 2-hour mark and it's still not done building.

**Comment by shepmaster** [comment]
Perhaps related to #25393?

**Comment by Ryman** [comment]
I think this was fixed by the related issue? Otherwise we would probably still be hearing about it?

**Comment by petevine** [comment]
Seeing as this issue was never closed, `glium` currently takes a few hours on my ARM machine whereas in the past it used to take, IIRC, 10-15 or maybe even fewer minutes. Seems like a huge regression.

**Comment by arielb1** [comment]
Are you using `-Z orbit`? Could you give us the output of `-Z time-passes`?

**Comment by petevine** [comment]
I'll have to leave it running overnight. And yes, I default to `-Z orbit`.

**Comment by petevine** [comment]
@arielb1 Attached in the previous post.

**Comment by nikomatsakis** [comment]
Is this still an issue?

**Comment by eddyb** [comment]
@petevine How much RAM do you have? Any chance it could be swapping for hours?

**Comment by eddyb** [comment]
@petevine Do you have the timings without `-Z orbit`? The issue is older than MIR trans.

**Comment by petevine** [comment]
It's the same issue as the linked one, I already OK'ed @jschievink's findings.

**Comment by eddyb** [comment]
Alright then, the original issue appears to have been fixed long ago.
