### ISSUE TITLE
Rust 1.0.0 tarball does not have proper permissions on directories.

### ISSUE THREAD

**Issue by kori** [rust-lang/rust#25479]
The tarball in question: https://static.rust-lang.org/dist/rustc-1.0.0-src.tar.gz

I actually don't really understand what's going on, one +x is set, and I don't understand why +x is needed on directories, but it is.

I ran into a snag, even while operating as root. I got "permission denied" when installing:

```
cfg: version 1.0.0-dev (built 2015-05-15)
cfg: build triple x86_64-unknown-linux-gnu
cfg: host triples x86_64-unknown-linux-gnu
cfg: target triples x86_64-unknown-linux-gnu
cfg: host for x86_64-unknown-linux-gnu is x86_64
cfg: os for x86_64-unknown-linux-gnu is unknown-linux-gnu
cfg: good valgrind for x86_64-unknown-linux-gnu is 1
cfg: using CC=ccache gcc (CFG_CC)
cfg: enabling valgrind run-pass tests (CFG_ENABLE_VALGRIND_RPASS)
cfg: valgrind-rpass command set to "/usr/bin/valgrind" --error-exitcode=100 --soname-synonyms=somalloc=NONE --quiet --suppressions=/home/kori/local/build/rust/src/rustc-1.0.0/src/etc/x86.supp  --tool=memcheck --leak-check=full
cfg: no xelatex found, disabling LaTeX docs
cfg: no pandoc found, omitting PDF and EPUB docs
cfg: disabling doc build (CFG_DISABLE_DOCS)
cfg: including prepare rules
cfg: including dist rules
cfg: including install rules
make: stat: GNUmakefile: Permission denied
make: stat: makefile: Permission denied
make: stat: Makefile: Permission denied
make: stat: prepare_install: Permission denied
make: *** No rule to make target 'prepare_install'.  Stop.
/home/kori/local/build/rust/src/rustc-1.0.0/mk/install.mk:14: recipe for target 'install' failed
make: *** [install] Error 2
```

I did some digging, and I figured out the problem.

SOLUTION: Mode a+x needs to be set for **all** directories, so it works properly.

This is currently not the case.

EDIT: Apparently you need a+x to search for the files inside directories properly.

https://en.wikipedia.org/wiki/Chmod#Common_Errors

More detail: the dirs are currently `drwx------`, they should be at least `drwx--x--x`, but ideally `drwxr-xr-x`

**Comment by huonw** [comment]
cc @brson, @alexcrichton

**Comment by Stebalien** [comment]
`drwx------` (700) should work as long as you own the directories.

Unfortunately, when run under `sudo` (`sudo make`), the makefile detects that it is running under `sudo` and temporarily drops privileges to the original user (the one that called `sudo`) when building. This is fine in the `sudo make` case assuming the user that is calling `sudo` is the same user that extracted the archive (a reasonable assumption). However, if you extract the archive using `sudo`, the files will be owned by root and `sudo make` will fail because it tries to build as your user, not root.

IMO, the makefile should not try to be smart. If building as root is dangerous, the makefile should tell the user so and abort.

**Comment by kori** [comment]
While experimenting with this, I tried fixing the permissions, and I've run into yet another problem.

`make prepare_install` works, but `make install` doesn't, it complains:
    make: *** No rule to make target 'prepare_install'.  Stop.
    /home/kori/local/build/rust/src/rustc-1.0.0/mk/install.mk:14: recipe for target 'install' failed
    make: *** [install] Error 2
This doesn't make any sense.

**Comment by kori** [comment]
Yeah, I just took @Stebalien's tip and removed these lines: https://github.com/rust-lang/rust/blob/master/mk/install.mk#L12-15
Works fine now.

**Comment by brson** [comment]
This may be a more general problem. AIUI permissions in tarballs are pretty broken because they encode local user id's that don't make any sense when distributed elsewhere. For this reason rust-installer explicitly sets the permissions of every single file during install.

**Comment by brson** [comment]
I'm curious though when this problems started happening. Our source tarball generation has barely changed ever. Has this always been a problem?

**Comment by brson** [comment]
Nominating because one of our release artifacts seems to be completely broken.

**Comment by alexcrichton** [comment]
triage: P-medium

Would love to fix, but doesn't seem super high priority right now.

**Comment by brson** [comment]
FWIW, I hacked around this a long time ago in rust-installer by setting the permissions on everything at install time.

**Comment by RalfJung** [comment]
Looking at <https://static.rust-lang.org/dist/rustc-1.17.0-src.tar.gz> and <https://static.rust-lang.org/dist/rustc-1.16.0-src.tar.gz>, this seems to be fixed, isn't it? I looked at a couple of directories, they all had `rwxr-xr-x`.

In fact, the code in rustup that works around it is nowadays actively harmful... see <https://github.com/rust-lang-nursery/rustup.rs/issues/1140>

**Comment by Mark-Simulacrum** [comment]
Yes, I am fairly certain (checked a few days back) this was fixed in the move towards a Rusty rust-installer. Closing.
