### ISSUE TITLE
Add release notes

### ISSUE THREAD

**Issue by wooque** [rust-lang/rust#25486]
It would be nice to have release notes per channel atached on http://www.rust-lang.org/install.html, and maybe on home page, so users can view what's new (features, major bugfixes) in stable (sincle last stable), beta and nightly, similar to Firefox. Because 1.1 beta is out but there is no clear way to see what's new in beta compared to 1.0 stable.

**Comment by steveklabnik** [comment]
@wooque in general, bugs against the site go on the https://github.com/rust-lang/rust-www repo

**Comment by steveklabnik** [comment]
(but yes, release notes there would be nice)

**Comment by alexcrichton** [comment]
The install page now links the release announcement always which transitively links the release notes, so closing.
