### ISSUE TITLE
.cloned() is stable but std::iter::Cloned is not

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#25480]
https://github.com/rust-lang/rust/blob/4ce08a5d70a4dfc4da7ed0bc0098cfd2176b8411/src/libcore/iter.rs#L1014 vs. https://github.com/rust-lang/rust/blob/4ce08a5d70a4dfc4da7ed0bc0098cfd2176b8411/src/libcore/iter.rs#L1373

Accidental mismatch? cc @alexcrichton, @aturon

**Comment by alexcrichton** [comment]
Yeah I believe this is just an accident, I've submitted #25496 for this.
