### ISSUE TITLE
Rust book links to old compiler.

### ISSUE THREAD

**Issue by Aaronepower** [rust-lang/rust#25489]
The rust book currently links to, an old beta version of rust, causing some problems using the tutorial. Example: Dining philosophers will not compile.

**Comment by Stebalien** [comment]
What's your rust version?

**Comment by Aaronepower** [comment]
According to the installer: 1.0.0-beta. On windows x64.

**Comment by sfackler** [comment]
It compiles on 1.0.0-beta.2 and up. You should update your compiler.

**Comment by alexcrichton** [comment]
I believe @sfackler is right here, so closing, but thanks for the report!
