### ISSUE TITLE
Debian package for Rust 1.0

### ISSUE THREAD

**Issue by MartinThoma** [rust-lang/rust#25482]
It seems as if there are currently no packages for rust in the debian package repository:

https://packages.debian.org/search?keywords=rust&searchon=names&suite=stable&section=all

Are there any plans to package Rust 1.0 for Debian?

**Comment by neuschaefer** [comment]
There is an ongoing "intent to package" at Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=689207

**Comment by manfredbrandl** [comment]
There is a new rustc packages at Debian: https://ftp-master.debian.org/new/rustc_1.0.0~beta.4-1~exp1.html

**Comment by steveklabnik** [comment]
Hey @MartinThoma ! As @neuschaefer and @manfredbrandl point out, there is effort ongoing, but those debian bugs are the right place to pursue this. As such I'm giving it a close. Thanks!

(I use Debian, so I'm excited for these packages)
