### ISSUE TITLE
TRPL: example from stable book with step_by does not compile with stable 1.0 compiler

### ISSUE THREAD

**Issue by manfredbrandl** [rust-lang/rust#25499]
In http://doc.rust-lang.org/stable/book/iterators.html there the third code from the bottom reads:
```
for i in (1..).step_by(5).take(5) {
    println!("{}", i);
}
```

Trying to compile this gives:
```
manfred@sony:~/rustprojects/step_by$ cargo build
   Compiling step_by v0.1.0 (file:///home/manfred/rustprojects/step_by)
src/main.rs:2:20: 2:30 error: use of unstable library feature 'step_by': recent addition
src/main.rs:2     for i in (1..).step_by(5).take(5) {
                                 ^~~~~~~~~~
error: aborting due to previous error
Could not compile `step_by`.

To learn more, run the command again with --verbose.
manfred@sony:~/rustprojects/step_by$ 
```

In http://doc.rust-lang.org/1.0.0/core/ops/struct.Range.html#method.step_by
one can see "Unstable: recent addition"
I did not find a way to compile the example.
Adding '#[unstable]' as first line in the source does not help but gives:

```
src/main.rs:1:3: 1:11 error: stability attributes may not be used outside of the standard library
src/main.rs:1 #[unstable]
                ^~~~~~~~
```
rustc --version --verbose
rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14)
binary: rustc
commit-hash: a59de37e99060162a2674e3ff45409ac73595c0e
commit-date: 2015-05-13
build-date: 2015-05-14
host: x86_64-unknown-linux-gnu
release: 1.0.0

**Comment by manfredbrandl** [comment]
I also cannot use the feature directive:
```
manfred@sony:~/rustprojects/step_by$ cargo build
   Compiling step_by v0.1.0 (file:///home/manfred/rustprojects/step_by)
src/main.rs:1:1: 1:21 error: unstable feature
src/main.rs:1 #![feature(step_by)]
              ^~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the stable release channel
error: aborting due to previous error
Could not compile `step_by`.

To learn more, run the command again with --verbose.
manfred@sony:~/rustprojects/step_by$ 
```

**Comment by mo** [comment]
Using "#![feature(step_by)]" should work if you switch to the nightly channel. For example, I got it to work using:
rustc 1.1.0-nightly (7a52835c1 2015-05-16) (built 2015-05-16)

**Comment by michaelsproul** [comment]
Yeah, all unstable features are disabled in the stable and beta builds. You can read more of the rationale for this here: http://blog.rust-lang.org/2014/10/30/Stability.html

It is potentially problematic that `step_by` is used in the stable docs, as it also won't be stable for 1.1 in six weeks.

**Comment by manfredbrandl** [comment]
As a potential user I expect that I can use the examples in the stable docs with the stable compiler. If I cannot then I expect to see a note describing why not.

**Comment by steveklabnik** [comment]
The book shouldn't use unstable things except in the nightly section at the end, for sure.

**Comment by michaelsproul** [comment]
@steveklabnik: In terms of making this change, would it involve manually patching the 1.0 source? In general do we have a way to update the docs for a release after the release has been made?

**Comment by steveklabnik** [comment]
No, it's just a bug to be fixed on master and will go out with the next release its part of.
