### ISSUE TITLE
typo in rust book

### ISSUE THREAD

**Issue by tromey** [rust-lang/rust#25500]
I was reading here:

http://doc.rust-lang.org/stable/book/concurrency.html

It says:

Rust's type system is up to the thread, and gives you powerful ways to reason about concurrent code at compile time.

I think it should say "up to the task", not "up to the thread".

**Comment by killercup** [comment]
Already fixed in nightly: http://doc.rust-lang.org/nightly/book/concurrency.html

**Comment by alexcrichton** [comment]
I believe @killercup is correct, so closing, but thanks for the report!
