### ISSUE TITLE
Unclear clear error message for borrowed contexts

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#25507]
The error message for the following snippet could be improved, from IRC I was told to add `.iter()` onto line 7 (which worked). I believe a hint in the error message would be helpful.

```
struct MyStruct {
    member : Vec<u8>,
}

impl MyStruct {
    fn example (&self) {
        for foo in self.member { // line 7
            println!("{}", foo);
        }
    }
}

fn main() {
    let a = MyStruct { member : vec!(1, 2, 3) };
    a.example();
}
```

Error seen:

```
src/main.rs:7:20: 7:24 error: cannot move out of borrowed content
src/main.rs:7         for foo in self.member {
                                 ^~~~
note: in expansion of for loop expansion
src/main.rs:7:9: 9:10 note: expansion site
error: aborting due to previous error
```

rustc --version --verbose:

```
rustc 1.1.0-nightly (e5394240a 2015-05-14) (built 2015-05-13)
binary: rustc
commit-hash: e5394240a295650b567aa406b4a0e1e3a6749a5f
commit-date: 2015-05-14
build-date: 2015-05-13
host: x86_64-apple-darwin
release: 1.1.0-nightly
```

**Comment by Stebalien** [comment]
This could definitely be improved. Just as an FYI, for loops take `IntoIterator`s by-value so the following also works:
```rust
for foo in &self.member {
    // ...
}
```
This is because `IntoIterator` is implemented on both `&Vec<T>` (producing an iterator that yields references to the items) and `Vec<T>` (producing an iterator that yields the items by value and consumes the vector.

We should probably add a detailed error message for this case; you're not the first to be confused.

**Comment by luke-gru** [comment]
I just stumbled into this, +1 for more helpful error message

**Comment by TheYokai** [comment]
I also stumbled upon this myself. Adding iter() also worked. +1 for better error message handling...

**Comment by jleedev** [comment]
I just ran into this. Here's a slightly different example:

```rust
#[derive(Debug)]
struct X;  // not Copy

struct Y{field: Option<X>}

fn main() {
    let v: Vec<Y> = Vec::new();
    for y in v.iter() {
        println!("{:?}", y.field.unwrap_or(X));
    }
}
```

Error:

```
rustc 1.13.0 (2c6933acc 2016-11-07)
error[E0507]: cannot move out of borrowed content
 --> <anon>:9:26
  |
9 |         println!("{:?}", y.field.unwrap_or(X));
  |                          ^ cannot move out of borrowed content
```

Ultimately, the diagnostic here should explain _why_ something is being moved, and what was borrowed in the first place. Namely, it's because the call to `unwrap_or` takes `self`.

The lifecycle of my example is worth nothing as well: The loop originally iterated over just `v`, which implicitly calls `into_iter()`, but I manually inserted `iter()` to make `enumerate()` work. No clue if it's generally useful, but a hint "did you mean into_iter" would have helped me here.

**Comment by jleedev** [comment]
This particular error pops up on me occasionally, so I have some more insight/complaints about my example. Let `it: &Option<X>`:

These three all give "cannot move out of borrowed content":

    it.unwrap();
    *it;
    Option::unwrap(*it);

But this gives "expected type `std::option::Option<_>`, found type `&std::option::Option<X>`", which I think is more in line with my intent.

    Option::unwrap(it);

When I type `it.unwrap()`, I am told that my error is an attempt to dereference it. But I think my error is in calling a method that takes ownership of a value which I have only borrowed. The compiler is inserting an implicit dereference and then chastising me about it.

**Comment by steveklabnik** [comment]
Triage: no changes, I do see people complain about this diagnostic fairly regularly...

**Comment by estebank** [comment]
[Current output](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ddfb47abef5393c81150ef7a6db38537):

```
error[E0507]: cannot move out of `self.member` which is behind a shared reference
 --> src/main.rs:7:20
  |
7 |         for foo in self.member { // line 7
  |                    ^^^^^^^^^^^ move occurs because `self.member` has type `std::vec::Vec<u8>`, which does not implement the `Copy` trait
```

**Comment by estebank** [comment]
Current output:

```
error[E0507]: cannot move out of `self.member` which is behind a shared reference
 --> src/main.rs:7:20
  |
7 |         for foo in self.member { // line 7
  |                    ^^^^^^^^^^^
  |                    |
  |                    move occurs because `self.member` has type `std::vec::Vec<u8>`, which does not implement the `Copy` trait
  |                    help: consider iterating over a slice of the `Vec<_>`'s content: `&self.member`
```

```
error[E0507]: cannot move out of `y.field` which is behind a shared reference
 --> src/main.rs:9:26
  |
9 |         println!("{:?}", y.field.unwrap_or(X));
  |                          ^^^^^^^
  |                          |
  |                          move occurs because `y.field` has type `std::option::Option<X>`, which does not implement the `Copy` trait
  |                          help: consider borrowing the `Option`'s content: `y.field.as_ref()`
```
