### ISSUE TITLE
rustdoc doesn't build markdown tables

### ISSUE THREAD

**Issue by davidcroda** [rust-lang/rust#25514]
This is especially apparent on the memory management section.

Compare the memory diagrams on the official book versus the github rendered markdown: 
 - http://doc.rust-lang.org/stable/book/the-stack-and-the-heap.html 
 - https://github.com/rust-lang/rust/blob/master/src/doc/trpl/the-stack-and-the-heap.md

I think the documentation was written with the github rendering in mind.

**Comment by huonw** [comment]
This was a bug in the formatting used, and is already fixed on nightly: http://doc.rust-lang.org/nightly/book/the-stack-and-the-heap.html

Thanks for filing!
