### ISSUE TITLE
API docs misleading about path to `from_str_radix` method

### ISSUE THREAD

**Issue by Valloric** [rust-lang/rust#25517]
1. Go to stable API docs: http://doc.rust-lang.org/stable/std/
2. In search bar, type "radix".
3. See tons of `std::[type]::from_str_radix` methods. Pick `std::u32::from_str_radix`, click it and read the docs for it.
4. Try to use it like so ([playpen link](http://is.gd/md3xUw)):

```rust
fn main() {
  println!("{}" , std::u32::from_str_radix("1", 16).unwrap()); 
}
```

Output:
```
<anon>:3:19: 3:43 error: unresolved name `std::u32::from_str_radix`
<anon>:3   println!("{}" , std::u32::from_str_radix("1", 16).unwrap()); 
                           ^~~~~~~~~~~~~~~~~~~~~~~~
```

Now bang your head for half an hour until you randomly call the method with `u32::from_str_radix`, so _without_ the `std` prefix, in spite of the path provided in the API search box. :)

This code works:

```rust
fn main() {
  println!("{}" , u32::from_str_radix("1", 16).unwrap()); 
}
```

@steveklabnik

**Comment by tyt2y3** [comment]
Thanks a lot! You saved my day :)
