### ISSUE TITLE
Add a conditional banner to the rust docs stating it's out of date

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#25513]
https://github.com/rust-lang/rust/issues/22063 suggested adding a banner stating "this version is really old" but modifying rust after the fact wasn't well liked. A better way would be to add a conditional banner which checks rust-lang or something similar to see if something new has been released. It should only appear if it's too old or something similar.

It could even have grades:
* Yellow: soon to be out of date
* Orange: is out of date
* Red: way out of date

Recently it came up on [reddit](http://www.reddit.com/r/rust/comments/3672gy/is_the_documentation_for_strsliceslice_wrong/).

**Comment by azerupi** [comment]
I like the way they do it in the [Django docs](https://docs.djangoproject.com/en/1.8/) for example. Bottom right corner, you can choose the version. It's a lot less intrusive than a banner. It's not very obvious, but you could ad an explicit text stating that this version is out of date.

**Comment by mdinger** [comment]
See also https://github.com/rust-lang/rust/issues/14466#issuecomment-73439058

**Comment by azerupi** [comment]
> See also #14466 (comment)

Ow, Sorry for the duplicate :)

And actually I spoke without checking, but Django uses a deprecation banner too for old versions. You can't miss it but it some weird way it still is non-intrusive :yum: 

Also one thing they have in Django docs, is a box with more information when something has changed recently. Like this:

![image](https://cloud.githubusercontent.com/assets/7647338/8508752/c3e73c1e-227d-11e5-8c3e-ac6166d09a20.png)

**Comment by steveklabnik** [comment]
Triage: this is significantly less of a problem today. MIT's docs went away, and now that things are stable, the most that happens is that someone misses a newer API that could be useful to them. Given that this issue has had no comment in the last year, I'm gonna give it a close.
