### ISSUE TITLE
Unknown error from cargo

### ISSUE THREAD

**Issue by thanatos** [rust-lang/rust#25518]
I seem to have messed something up while trying to create a minimal example for another bug.

My setup is simple, I think:

```bash
% ls -l
total 12
-rw-r--r-- 1 royiv royiv   41 May 16 20:24 Cargo.lock
-rw-r--r-- 1 royiv royiv  121 May 16 20:24 Cargo.toml
drwxr-xr-x 2 royiv royiv 4096 May 16 20:23 src
% cat Cargo.toml 
[package]
name = "build"
version = "0.1.0"

[[bin]]
name = "build"
path = "src/main.rs"
% cat Cargo.lock 
[root]
name = "build"
version = "0.1.0"

% ls -l src     
total 4
-rw-r--r-- 1 royiv royiv 14 May 16 20:23 main.rs
% cat src/main.rs 
fn main() { }
```

but:

```bash
% cargo build          
An unknown error occurred

To learn more, run the command again with --verbose.
```

```bash
% cargo build --verbose
Is a directory (os error 21)
```

I'm sure I'm doing something that's obviously dumb to someone experienced with Cargo, but I'm not, and it isn't. Cargo itself doesn't seem really know what's going on here either.

**Comment by thanatos** [comment]
…`build` is the name of a directory in the directory where the executable gets written out.

Presumably, the following are thus illegal as binary names in cargo: `build`, `deps`, `examples`, and `native`.

**Comment by alexcrichton** [comment]
Ah yeah I've been meaning to explicitly deny these target names for some time now, but unfortunately you'll need to avoid the names of the directories in `target/debug` as they'll be showing up there no matter what.

**Comment by alexcrichton** [comment]
Oh actually, I'm going to move this to the Cargo repo here: https://github.com/rust-lang/cargo/issues/1618, thanks for the report though!
