### ISSUE TITLE
Module std::slice documentation doesn't contain any essential slice-related methods

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust#25545]
Most slice-related Google searches point to:

https://doc.rust-lang.org/std/slice/

but this page is rarely relevant, because all the essential slice methods are documented at:

https://doc.rust-lang.org/std/primitive.slice.html

This is non-obvious and frustrating, because to a newbie user it seems like the standard library doesn't contain any useful slice methods!

e.g. Googling "rust convert slice to vector" doesn't find `to_vec`!

It'd be great if "std/primitive.slice.html" could be folded into "std/slice/", and if rustdoc can't do that, then at least add a huge flashing neon on "std/slice/" that it doesn't document most methods available for slices.

**Comment by pmarcelll** [comment]
I think it's fixed.

**Comment by steveklabnik** [comment]
Agreed, thanks.

**Comment by naktinis** [comment]
Can you expand a little on how exactly it is fixed?

**Comment by pmarcelll** [comment]
Searching for ```slice``` gives ```slice (primitive type)``` and ```std::slice```. They also have links to each other.

**Comment by naktinis** [comment]
I've tried googling "rust convert slice to vector" (as this issue's author suggested) and it only shows https://doc.rust-lang.org/std/slice/ as before, and not https://doc.rust-lang.org/std/primitive.slice.html.

It's nice that these articles were at least cross-linked, but I'm sure such questions will keep coming up for new users.
