### ISSUE TITLE
fmt documentation inconsistent

### ISSUE THREAD

**Issue by iragsdale** [rust-lang/rust#25547]
I see an inconsistency on this page: http://rustbyexample.com/hello/print/fmt.html

First it says: "The most common formatting trait is Debug, which handles cases where the argument type is left unspecified: {} for instance."

Below it says "Here's the full list of formatting traits and their respective argument types: unspecified -> Display".

Based on my test with 1.0 the latter is correct.

**Comment by sanxiyn** [comment]
Fixed by https://github.com/rust-lang/rust-by-example/pull/574.
