### ISSUE TITLE
Location pointed to by the "trait `core::marker::Sized` is not implemented for the type" error is very vague

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust#25543]
When a struct contains an unsized member inside a nested struct, the error points to the start of a definition the top-level struct, rather than the member in a leaf struct which is the real cause.

```rust
struct nothere {
  nope: f32,
  nothere: Vec<f32>,
  maybe: Vec<bad>,
  guesswhere: f32,
}

struct bad {
  bad: [f32],
}
```

>     <anon>:1:1: 6:2 error: the trait `core::marker::Sized` is not implemented for the type `[f32]` [E0277]
>     <anon>:1 struct nothere {
>     <anon>:2   nope: f32,
>     <anon>:3   nothere: Vec<f32>,
>     <anon>:4   maybe: Vec<bad>,
>     <anon>:5   guesswhere: f32,
>     <anon>:6 }
>     <anon>:1:1: 6:2 note: `[f32]` does not have a constant size known at compile-time
>     <anon>:1 struct nothere {
>     <anon>:2   nope: f32,
>     <anon>:3   nothere: Vec<f32>,
>     <anon>:4   maybe: Vec<bad>,
>     <anon>:5   guesswhere: f32,
>     <anon>:6 }

I'd expect error to point to:

```rust
struct bad {
  bad: [f32],
}
```

**Comment by apasel422** [comment]
This now results in the following error:
```
foo.rs:4:5: 4:20 error: the trait `core::marker::Sized` is not implemented for the type `[f32]` [E0277]
foo.rs:4     maybe: Vec<bad>,
             ^~~~~~~~~~~~~~~
foo.rs:4:5: 4:20 help: run `rustc --explain E0277` to see a detailed explanation
foo.rs:4:5: 4:20 note: `[f32]` does not have a constant size known at compile-time
foo.rs:4     maybe: Vec<bad>,
             ^~~~~~~~~~~~~~~
foo.rs:4:5: 4:20 note: required because it appears within the type `bad`
foo.rs:4     maybe: Vec<bad>,
             ^~~~~~~~~~~~~~~
foo.rs:4:5: 4:20 note: required by `collections::vec::Vec`
foo.rs:4     maybe: Vec<bad>,
             ^~~~~~~~~~~~~~~
```

**Comment by pornel** [comment]
Close enough for me :)
