### ISSUE TITLE
stdout/stderr should be flushed when reading from stdin

### ISSUE THREAD

**Issue by barosl** [rust-lang/rust#25555]
As stdout is flushed only when a newline character is printed, the following program does not work properly:

```rust
print!("Input a text: ");

let mut text = String::new();
stdin().read_line(&mut text).unwrap();

println!("Text: {}", text);
```

Therefore, it is required to flush explicitly like `stdout().flush().unwrap()`. #23818 suggested always calling flush if anything is printed, but it is probably not acceptable due to the performance concerns.

However, at least C and Python seem to have an implicit flushing behavior when `scanf()`/`input()` is called, so the following works as expected:

```python
print('Input a text: ', end='')

text = input()

print('Text: {}'.format(text))
```

```c
printf("Input a text: ");

char text[1024];
fgets(text, sizeof(text), stdin);

printf("Text: %s", text);
```

It would also be a good idea to adopt a similar strategy in Rust.

**Comment by cmr** [comment]
This seems like a decent "Do What I Mean" fix.

**Comment by nagisa** [comment]
We used to do this, but do not anymore (https://github.com/rust-lang/rust/pull/23087) because it used to be a very easy way to cause a deadlock. Since stdio now uses reentrant mutexes (https://github.com/rust-lang/rust/pull/24029), I believe this functionality can be introduced again.

**Comment by alexcrichton** [comment]
The associated PR for this issue [was closed](https://github.com/rust-lang/rust/pull/25572#issuecomment-110860578), so I'm going to close this as well.
