### ISSUE TITLE
rust 1.0.0 installation fails on mac os x yosemite

### ISSUE THREAD

**Issue by shadowleaves** [rust-lang/rust#25557]
after installation, got the following error. tried both binary package from rust-lang.org and the script (curl -sSf https://static.rust-lang.org/rustup.sh | sh).

rustc --version

dyld: Library not loaded: x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/librustc_driver-4e7c5e5c.dylib
  Referenced from: /usr/local/bin/rustc
  Reason: image not found
Trace/BPT trap: 5

**Comment by shadowleaves** [comment]
this problem can be fixed by manually setting the following variable:

export DYLD_LIBRARY_PATH=/usr/local/lib/rustlib/x86_64-apple-darwin/lib/

**Comment by alexcrichton** [comment]
Thanks for the report! It looks like you've found the solution, and this is otherwise tracked by #24677.

**Comment by phact** [comment]
This happened when I run rustup.sh with the -prefix flag. Would it make sense to add `export DYLD_LIBRARY_PATH=$prefix/lib/` and export `PATH=$PATH:/rust/lib/` to rustup.sh?
