### ISSUE TITLE
Dollar signs in installation section of TRPL can be confusing.

### ISSUE THREAD

**Issue by nham** [rust-lang/rust#25554]
Currently the Installation section of TRPL displays commands to be typed into the command line with a dollar sign in front, like this:

```
$ rustc --version
```

I see that there's a warning that you shouldn't type them, but nevertheless one person was already confused: https://users.rust-lang.org/t/powershell-and-rustc-command/1411

Either the warning should be made more prominent, or the dollar signs should be removed. (Note that in [Clojure from the ground up](https://aphyr.com/posts/301-clojure-from-the-ground-up-welcome) there are no dollar signs, which seems to work well).

cc @steveklabnik

**Comment by steveklabnik** [comment]
This has a very, very long history of being how to show command line things. I would prefer something to be more prominent over breaking with history.

**Comment by nagisa** [comment]
Dollar signs could be added with CSS `:before`, so it wouldn’t be copy-able.

**Comment by tshepang** [comment]
Great idea there @nagisa.
