### ISSUE TITLE
Unfinished issues for 1.0 Milestone

### ISSUE THREAD

**Issue by wldcordeiro** [rust-lang/rust#25559]
This should probably be cleaned up and/or moved to the 1.1 milestone, shouldn't it? The idea is that all the issues for 1.0 should be done with 1.0's release.

**Comment by steveklabnik** [comment]
We generally decided to stop using milestones. I'll bring this up at the next triage meeting.

**Comment by steveklabnik** [comment]
Since we're not using milestones anymore, I've de-milestoned everything, and closed them. Thanks!
