### ISSUE TITLE
Mistake in Documentation in the heaps section of the book

### ISSUE THREAD

**Issue by tmtwd** [rust-lang/rust#25558]
Next, foo() calls bar() with x and z:
 | Address | Name | Value | +----------------------+------+----------------------+ | 230 | | 20 | | (230) - 1 | | 5 | | ... | ... | ... | | 10 | e | 4 | | 9 | d | (230) - 1 | | 8 | c | 5 | | 7 | b | 4 | | 6 | a | 0 | | 5 | z | 4 | | 4 | y | 10 | | 3 | x | 0 | | 2 | j | 0 | | 1 | i | 230 | | 0 | h | 3 |
 this part is wrong I believe, this is the memory after we say
 let e = &d;
 however the address of d is 9, not 4, which it says in the memory chart

**Comment by steveklabnik** [comment]
I _think_ this is fixed in nightly, can you confirm?

**Comment by tmtwd** [comment]
Yup it is fixed now!
