### ISSUE TITLE
The book translation in Korean

### ISSUE THREAD

**Issue by heejongahn** [rust-lang/rust#25566]
Hi, I'm a undergrad student from KAIST, Republic of Korea. As grand 1.0 is finally released (Yay!), I'm thinking about translating the book in Korean with some people from Korean rust group. However, I couldn't find any translation guidelines in Contribution tab. I asked around in irc channel, and someone told me to ask @steveklabnik, as he wrote the majority of the docs.

So, is there anything we should keep in mind before start translating? Also, is there any chance that our translation will get linked by official book? Please let me know.

**Comment by lifthrasiir** [comment]
You probably want to contact the [Korean Rust user group](http://rust-kr.org) first.

**Comment by klutzy** [comment]
Yep, we're planning to open a translation repo at @rust-kr soon :)

**Comment by heejongahn** [comment]
Actually I asked about this in Korean Rust IRC first (my nick is 히종!) but anyway let's discuss further in irc then!

**Comment by steveklabnik** [comment]
Hey @heejongahn !

The biggest thing to keep in mind is that the book is still changing, and more is being added. So, you'll have to figure out some way to keep up with that.

I would eventually like for there to be official links to translated versions, but until the book is _done_ enough that it's truly stable, I think the effort of keeping up with changes makes it not worthwhile to translate currently. You may feel a bit differently. Also, I know @mkpanov, I think, wanted to do some translation work too...

**Comment by heejongahn** [comment]
For now, a repository(https://github.com/rust-kr/doc.rust-kr.org) is made and we still are discussing about the details such as word choices and stuffs. Thanks for your opinion and the reply!

**Comment by steveklabnik** [comment]
Cool! Since this isn't a bug, exactly, I'm going to give it a close. Thanks for doing the work!
