### ISSUE TITLE
Precedence of Unary Negative Operator vs Methods

### ISSUE THREAD

**Issue by dbrgn** [rust-lang/rust#25564]
Right now, methods on negative literals take precedence over the unary operator:

```
1.32.abs(): 1
-1.32.abs(): -1
pos.abs(): 1
neg.abs(): 1
-pos.abs(): -1
-neg.abs(): -1
```

Playpen: http://is.gd/0YgB1E

While that [might make sense](http://mathforum.org/library/drmath/view/53194.html) from a mathematical point of view, I think it's rather unintuitive.

I see two ways to improve this issue:

- According to someone in the #rust channel, "ruby treats -3.abs as (-3).abs and -x.abs as -(x.abs)". I find that quite intuitive.
- The compiler could generate a warning if a method is called on a negative literal without using parentheses to make things more explicit. Otherwise this might cause subtle bugs.

Is a change related to precedence even possible now that 1.0 is stable?

**Comment by nagisa** [comment]
> I find that quite intuitive.

Really? You propose to change precedence of operators depending on whether it is a variable or literal?
Anyway, our precedence rules are set in stone now and won’t be changed before 2.0 for sure.

**Comment by huonw** [comment]
1.0 means change isn't possible, and anyway, the current precedence seems like the standard one to me, I would be quite surprised if there were any languages other than ruby that behaves like that. Thanks for taking the time to write this up, but I'm going to close.

**Comment by dbrgn** [comment]
> Anyway, our precedence rules are set in stone now and won’t be changed before 2.0 for sure.

Yeah, I already assumed that. And there are also good reasons to keep it that way :) But a compiler warning might make sense. Something like `-1.32.abs()` could lead to bugs due to people misunderstanding the precedence.
