### ISSUE TITLE
64-bit windows installer doesn't set PATH properly

### ISSUE THREAD

**Issue by barbiomalefico** [rust-lang/rust#25565]
I downloaded the Rust installer for 64 bits windows. I installed RUST and restarted my PC.
I started the command line and execute the command
C:\>rustc --version
"rustc" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.

My windows is in Italian and the error says that rustc is not a recognized program.

If I go into the folder C:\Program Files\Rust beta 1.0 \ bin and run the command I get
rustc--version
rustc 1.0.0-beta (9854143cb 4/2/2015) (built 4/2/2015).

My conclusion is that the Installer did not properly set the PATH environment variable

**Comment by klutzy** [comment]
Rust MSI installer has the 'Advanced' option, which provides "Add to PATH" feature.
The problem is it's off by default. I don't know if it is intentional or not.

**Comment by klutzy** [comment]
cc @brson @vadimcn

**Comment by pnkfelix** [comment]
Someone at the Paris release party mentioned this issue to me as well.  He said that the Windows installer *used* to add to the `PATH` by default.  Assuming that is true, then I assume that it was a deliberate decision to switch to not adding to `PATH` by default (though I have not yet attempted to dig into the issue database to see if its documented there...)

**Comment by vadimcn** [comment]
Yes, this was an intentional change to prevent confusion when multiple versions of Rust are installed.  As @klutzy mentions above, one can override the default by going through the "Advanced" install sequence.

**Comment by pnkfelix** [comment]
@vadimcn ah I see.

Hmm.  I am not sure if we are optimizing for the right case here.

In particular, I would expect we will have far more users that (1.) do not attempt to install multiple versions, and (2.) do not look at the Advanced options for their first experience with Rust.  And that leads me to think that we should optimize for the case where one would want the `PATH` modified by default.

Is there some way that we could have this choice default to "on" by default, if one is using the default install directory?  Or is the target install directory an orthogonal choice in the installation process to whether one is on the "Advanced" versus "non-Advanced"

**Comment by vadimcn** [comment]
I personally prefer installers that don't spam my PATH, but if people prefer it the other way, we can change it as you suggest.

**Comment by pnkfelix** [comment]
Well the person at the release party indicated that if we're not going to make it the default, then it should be significantly highlighted in whatever documentation we expect the newcomer to use.

(I'm not a windows user, i don't have a dog in this fight; I just want the new user experience to be as good as we can manage.)

**Comment by ndarilek** [comment]
I think it should be the default, if for no other reason than it is the default on every other platform, and none of Rust's otherwise excellent documentation indicates that everything else behaves this way, but Windows requires... Also, I'm not sure how you're expected to use the toolchain if it isn't in your path (not being snarky, it's a genuine question.)

I'd also note tat, when uninstalling, the installer doesn't remove its directory from the path. I've had a number of Rust betas piling up on my path, which is a bit frustrating when I go back to add it but have to remove beta, an old entry for c:\rust, etc.

Thanks.

**Comment by vadimcn** [comment]
> Also, I'm not sure how you're expected to use the toolchain if it isn't in your path

You can launch the appropriate Rust Shell from the Start menu.
Note that e.g. Visual C doesn't add itself to the path either.  You have to launch a special command prompt from the Visual Studio Tools folder to have it on  the path.

> I'd also note tat, when uninstalling, the installer doesn't remove its directory from the path

Strange...  I just tested this and it worked as expected.

**Comment by klutzy** [comment]
What about showing "Advanced" dialog as default? I think the "Advanced" step is not so useful to be skipped for most cases, since it provides PATH option as well as where is the installation path.

**Comment by iopq** [comment]
I'm a Windows user and not only did I not know that I have to dig into Advanced to get the path, I think uninstalling should remove from path when you remove the folder.

**Comment by Dangthrimble** [comment]
I have just installed Rust on Windows. I have many years of experience as a software engineer, but have not had the opportunity to write code in anger for a while. I thought Rust might be a good place to start again. Reading through the documentation I was advised to "download the appropriate installer" and that, after installation, running `$ rustc --version` would tell me the version number. Guess what ...

Firstly, I can't recall any tool that I have installed that can be called from the command line yet isn't in the path by default. Secondly, if not including the path is to remain the default behaviour, the documentation should be updated to indicate that is the case and how to use the "Advanced" dialog to change that. However, I agree with @pnkfelix, the default should be newbie friendly with the "Advanced" options being for those more in the know. 

I don't imagine many people would bother to go straight to GitHub and search for an existing issue. Some would google the problem, others post a question on a forum somewhere, others would flame Rust and yet others would just give up and go home. Surely you don't want to lose potential Rust users just to make life easier for power users installing multiple versions of Rust!

**Comment by pnkfelix** [comment]
@Dangthrimble just to play devil's advocate here: Have you ever installed the Command Line tools for Visual Studio?  (I cannot remember what this used to be called or perhaps what it is still called, if Microsoft still offers it as a free download for developers...)

The reason I ask is that I have been reminded that this protocol of "You launch the shell for the development environment via the appropriate shell that has been added to the Start Menu" is the precedent established by Microsoft.  In other words, I think that serves as an example of a tool that one can call from the command line yet isn't in the path by default.

**Comment by Dangthrimble** [comment]
Most of my coding was for embedded software and I have never used Visual Studio. It may be an example, but it is not one I have ever come across and I imagine that could be the case for a number of potential Rust users.

**Comment by vadimcn** [comment]
Thanks for being my advocate, @pnkfelix! LOL
Other examples command line tools that don't add themselves to the path automatically: Python, mingw-builds.  Basically anything that you may have multiple versions of installed side-by-side.
Now, admittedly, the Python installer doesn't offer the "just install with default options" button, it only has the equivalent of our "Advanced" UI sequence.  It wouldn't be hard to do the same in the Rust installer, if people prefer that \<shrug\>.
I suppose the ultimate solution would be to make a Windows port of [multirust](https://github.com/brson/multirust).

**Comment by Dangthrimble** [comment]
In the meantime, wouldn't it make sense to update the [Introduction to Rust](https://doc.rust-lang.org/book/). I'm happy to make the changes if it's open to amendment and someone can point me at the source.

**Comment by steveklabnik** [comment]
@Dangthrimble it's in `src/doc/trpl`

**Comment by explodingbat** [comment]
Surely the "advanced" option is the having multiple simultaneous versions thing? I just installed Rust and immediately had to look up what directory it was in and how to add things to Windows' PATH variable, am not impressed.

**Comment by vadimcn** [comment]
Well, okay, let's have a poll: 

What should be done about this issue?
1. Leave it as-is, i.e. quick install does not add Rust to the PATH.  Users have to either run it via shortcuts under StartMenu/Rust, or, add it to the PATH themselves.
2. Have quick install add Rust to the PATH, but only if there are no other Rust installations on the machine.  This helps casual users, who only install Rust once, but I think this is more confusing for those installing multiple versions side-by-side.
3. Remove the quick install button altogether.  Users will always have to go through the advanced sequence, but on the plus side, "Add to PATH" option becomes more discoverable.
4. Other ideas?  (Please keep this reasonable.  Due to declarative nature of Windows Installer packages, implementation of complex rules gets really hairy really quickly).

**Comment by Dangthrimble** [comment]
Advanced options are for advanced users and someone who is installing multiple versions of rust sounds like an advanced user to me. The simple install should add rust to the PATH. However, if a rust install can detect another installed version of rust it should offer to:
1. Uninstall the earlier version, or
2. Remove rust from the PATH (with a warning)

**Comment by explodingbat** [comment]
Not sure if i'm qualified to vote, but i like vadimcn's option 3.

It's not a Quick install if i have to google how to complete it by hand.

**Comment by ndarilek** [comment]
I'm confused, just about every Windows installer I run offers me a list
of tasks to complete, like "Add to start menu", "Add desktop shortcut",
"Add to path". These are just checkboxes, not hugely complex rules, and
they're not behind a "Quick install" option. What's wrong with doing
that? Not sure if that's one of the options listed in this poll, maybe
it's the "get rid of quick install" option. If that's the case then
perhaps it'd make sense to do that, since I don't find that particularly
time-consuming.

**Comment by krisdigitx** [comment]
SO I fixed this by re-running the installation ->Select Change -> Select Add to Path and that worked fine with Rust windows 64bit.

**Comment by iopq** [comment]
Whenever I walk through people installing Rust for the first time I always say "you don't want to do a quick install, we're going to add Rust to the path"

I mean, it seems like it's the best default, you always want the first installation on the path
