### ISSUE TITLE
Unfortunate comparison between const and #define in Rust Book 5.27

### ISSUE THREAD

**Issue by matthieu-m** [rust-lang/rust#25573]
At the end of Rust Book chapter 5.27 *`const` and `static`* is [the following extract](https://github.com/rust-lang/rust/blame/master/src/doc/trpl/const-and-static.md#L82):

> A `const` can be thought of as a `#define` in C: it has metadata overhead but it has no runtime overhead. “Should I use a `#define` or a `static` in C,” is largely the same question as whether you should use a `const` or a `static` in Rust.

Unfortunately, this is rather misleading. An experienced C programmer will try and avoid `#define` as much as possible (they do have their use) because:

 - a `#define` is unscoped, and the C preprocessor is *just* a text preprocessor
 - a `#define` is untyped

You can check [constants - "static const" vs "define" in C](http://stackoverflow.com/questions/1674032/static-const-vs-define-in-c) for more context and relevant advices; specifically Jonathan Leffer's answer (yep, just skip mine). *Note: in C++, the answer is `static const` because C++ lifts a lot of restrictions for where one can use `static const` variables.*

Since in Rust `const` is scoped and typed, it is really no equivalent to `#define`. It is, however, much closer to `enum`.

Maybe simply comparing to `enum` instead of `#define` would avoid confusing the reader?

**Comment by steveklabnik** [comment]
We had a chat about this on Reddit, I wanted an issue here for more visibility. Thoughts, anyone else?

**Comment by alexcrichton** [comment]
I think it would be fine to add some clarification here, but the emphasis is that the definition is inlined everywhere (like `#define`), not so much the odd semantics of `#define`
