### ISSUE TITLE
TRPL: Table formatting on the stack and heap chapter is incorrect

### ISSUE THREAD

**Issue by markstory** [rust-lang/rust#25589]
The table markup in [the stack and heap chapter](https://doc.rust-lang.org/book/the-stack-and-the-heap.html) is incorrect. Instead of rendering HTML, it renders

![screen shot 2015-05-18 at 23 42 48](https://cloud.githubusercontent.com/assets/24086/7695055/e746b954-fdb7-11e4-8256-686f386d3356.png)

Which is considerably harder to read. I'm happy to fix the markup, but I don't know what the correct markup should be.

**Comment by steveklabnik** [comment]
This has already been fixed actually. See the nightly version of the book.

Thanks for reporting!
