### ISSUE TITLE
Rust Book chapter 3.2: explain why table.clone() is needed

### ISSUE THREAD

**Issue by iven** [rust-lang/rust#25597]
In the book:

> Finally, inside of our map()/collect() loop, we call table.clone(). The clone() method on Arc<T> is what bumps up the reference count, and when it goes out of scope, it decrements the count.

I think it's better to add a few lines and let the readers know why bumping up the reference count here is needed.

**Comment by steveklabnik** [comment]
It's hard to figure out what level of depth to go into in these higher-level docs, you're right.
