### ISSUE TITLE
Rustdoc: inline methods available through blanket impls

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#25608]
On reddit: https://www.reddit.com/r/rust/comments/36f94o/how_do_i_read_the_api_docs/

> I had a terrible time with the API docs. Take [str](https://doc.rust-lang.org/std/str/)... I know I can use `to_string()` on it because I saw a web page that said I could, but I can't seem to infer that from the docs. Then I search for `to_string()` and get [this page](https://doc.rust-lang.org/std/string/trait.ToString.html#tymethod.to_string), but it doesn't seem to apply to str types.

What’s going on is that the `to_string()` method is on the `ToString` trait which has a blanket impl

``` rust
impl<T> ToString for T where T: Display + ?Sized
```

… and `str` implements `Display`.

So in the spirit of #19190 (show methods available through deref), rustdoc should also show methods available through blanket implementations.

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by QuietMisdreavus** [comment]
Closing as duplicate in favor of #33772, which had more discussion.
