### ISSUE TITLE
Documentation of std::str does not link to str type

### ISSUE THREAD

**Issue by nwin** [rust-lang/rust#25600]
At the moment it is impossible to find the documentation of the [str primitive type](https://doc.rust-lang.org/std/primitive.str.html) with the search function. At the same time std::str does not link to it’s documentation. This leads to some confusion because it is not clear what traits and methods are implemented by it.

**Comment by nwin** [comment]
This is not easily fixable since both pages share the same source but are in different subdirectories of generated docs such that the link will only be valid on one of the two pages.

**Comment by steveklabnik** [comment]
Yes, i'm tagging this as 'rustdoc' for that reason. Unsure how to make it work properly.

**Comment by bluss** [comment]
It's not impossible to find -- search for `str` and you get two hits, `std::str` with str in blue, this is the module, `std::str` with str in black, this is the primitive type. Just FYI!

**Comment by nwin** [comment]
Interesting, I overlooked that every time. But beside that it should be linked since it definitively leads to confusion (-> few topics on reddit).

**Comment by pmarcelll** [comment]
Searching for ```str``` now gives ```str (primitive type)``` as the first result.

**Comment by bluss** [comment]
Thanks! This has then been fixed.
