### ISSUE TITLE
No warning about unstable crates if typeck fails

### ISSUE THREAD

**Issue by Ryman** [rust-lang/rust#25613]
I'm not sure we can do much about this since lints run after typeck, but it's a bit of a papercut. The example below will fail typechecking, so there is no error about use of the unstable serialize crate (which would guide a user to fixing the error):

``` rust
extern crate serialize; <- Would be more helpful to error here
extern crate upstream;

use serialize::json::ToJson;

// Upstream lib 
{
    trait Foo {};
    // in upstream lib serialize == rustc_serialize but a user reading 
    // the code (or docs) may miss the import rename
    impl Foo for serialize::json::Json {}
    fn foo<F: Foo>(f: F) {}
}

fn main() {
    // ERROR: the trait `Foo` is not implemented for the type `serialize::json::Json`
    upstream::foo(32i32.to_json())
    println!("")
}
```

**Comment by steveklabnik** [comment]
Given that nobody has commented on this issue in over a year, and as you mention, @Ryman , it's not clear this can be fixed, I'm gonna give this one a close.
