### ISSUE TITLE
Improve documentation for Vec::as_slice

### ISSUE THREAD

**Issue by mbrubeck** [rust-lang/rust#25622]
`Vec::as_slice` and `Vec::as_mut_slice` are both marked unstable with reason "waiting on RFC revision."  But the docs for `as_mut_slice` say that it is deprecated.

If these methods are deprecated, they should be marked deprecated instead of unstable.  And either way, a hint should be added regarding how to replace `Vec::as_slice` in old code.

[moved from rust-lang/rfcs#1128]

**Comment by mbrubeck** [comment]
cc @bluss

**Comment by steveklabnik** [comment]
See https://github.com/rust-lang/rust/pull/25833#issuecomment-106033786 , this is actually correct

**Comment by mbrubeck** [comment]
There are still these problems to be fixed:

* `as_mut_slice` docs say it is deprecated, when it isn't.
* `as_slice` docs don't point to the stable alternative `&v[..]`.

**Comment by steveklabnik** [comment]
>  as_mut_slice docs say it is deprecated, when it isn't.

Which are these? It shows as unstable in that patch I worked up

**Comment by steveklabnik** [comment]
ahhh i see, it's in the words, not the attribute
