### ISSUE TITLE
Rust book: keep index static

### ISSUE THREAD

**Issue by danobi** [rust-lang/rust#25626]
I don't do much web dev, so I don't know if static is the right term for this. What I mean is the index on the left side of the page in rust book should hold its current scroll position when moving around sections. It would make browsing through the book much more pleasant.

**Comment by steveklabnik** [comment]
Thanks @danobi ! You're right that this is a bit annoying at the moment, but we already have a bug open to fix it. It needs some JavaScript, as this is the default way the web works.

**Comment by frewsxcv** [comment]
@danobi In case you want to follow progress, 'Subscribe' to https://github.com/rust-lang/rust/issues/24901

**Comment by steveklabnik** [comment]
Oh, yeah, good call @frewsxcv , sorry @danobi :sweat:
