### ISSUE TITLE
Stabilizing statically intialized UnsafeCell?

### ISSUE THREAD

**Issue by aldanor** [rust-lang/rust#25634]
Seeing as the cell types have been somewhat recently stabilized, is static cell initialization supposed to be stabilized too at some point?

```rust
pub const FOO: Foo = Foo {
    counter: UnsafeCell { value: 0 },
};
```
currently triggers "error: use of unstable library feature 'core'" lint, however there's really no other way to work around this as far as I know.

**Comment by alexcrichton** [comment]
Thanks for the report! Currently we're probably not going to have an issue-per-feature to stabilize, and we plan to stabilize this once [`const fn`](https://github.com/rust-lang/rust/pull/25609) lands (allowing `UnsafeCell::new`). I'm going to close this in favor of that as once that feature is stabilized this should "just work"!

**Comment by aldanor** [comment]
@alexcrichton Thanks for the quick answer! I must have missed that there's an open PR for the const-fn RFC now... this will be extremely useful. However, it will still be feature-gated for a good while if/when it lands, is that right?

**Comment by alexcrichton** [comment]
Yeah it will be feature gated for awhile (perhaps slated for 1.2 or 1.3?).
