### ISSUE TITLE
failed to install rustc from source code,missing librustc_driver.so

### ISSUE THREAD

**Issue by ggaaooppeenngg** [rust-lang/rust#25639]
rustc: error while loading shared libraries: librustc_driver-d8ace771.so: cannot open shared object file: No such file or directory

ubuntu 14.04 AMD64

**Comment by upyx** [comment]
You should specify LD_LIBRARY_PATH to `lib` directory with `librustc_driver-d8ace771.so` for run rustc directly. Also you can just use `make install` command with root (!) permissions.

**Comment by ggaaooppeenngg** [comment]
where is the __lib__ directory,can you give me a example? I can not install it as root.

**Comment by kingkf** [comment]
you can install like this：
sh rustup.sh --prefix=*you want install dir*
then
you will find a lib directory in the path
add the path to LD_LIBRARY_PATH  use export in .bashrc or .zshrc like this:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:*you  install dir*/lib

and add bin path also:
export PATH=$PATH:*you  install dir*/bin/
source ~/.bashrc

try
rustc --version
done

**Comment by steveklabnik** [comment]
Since this is not exactly a bug, I'm giving it a close. @ggaaooppeenngg , please let us know if you still can't get it to work.
