### ISSUE TITLE
Add a --test-threads option for rustc test binaries

### ISSUE THREAD

**Issue by jimmycuadra** [rust-lang/rust#25636]
Discussion carried over from: rust-lang/cargo#1591

Test binaries created by rustc should have a `--test-threads` option instead of (in addition to?) controlling the thread count with `RUST_TEST_THREADS`. It's not a consistent user experience to have some functionality controlled via environment variables and some via command line options. CLI options should be preferred since they encourage users to keep configuration local to a single execution of a test binary and not export it globally, making it affect other test runs perhaps accidentally. It would also make the output of `test_binary -h` more uniform and compact.

**Comment by brson** [comment]
Agreed.

**Comment by nixpulvis** [comment]
The ability to specify this in the `Cargo.toml` somehow might be nice. One of my crates I'm working on needs all the tests run like this.

**Comment by steveklabnik** [comment]
It is already set table by an env var, no? Cargo just can't specify them. So still not ideal but might work in the meantime.

**Comment by nixpulvis** [comment]
@steveklabnik Oh cool thanks, I'll set that in my project.
