### ISSUE TITLE
Methods from deref in rustdoc cause clashes in method anchors

### ISSUE THREAD

**Issue by netvl** [rust-lang/rust#25674]
Example is [here](http://doc.rust-lang.org/nightly/std/path/struct.PathBuf.html#method.new) - there is `new` method on `PathBuf` and `new` method on `Path` which is shown as if available through Deref.

If you click on `new()` in the Deref section, you will get to `new()` in the main impl section.

**Comment by steveklabnik** [comment]
This issue got opened twice, closing in favor of N-1 :)

**Comment by netvl** [comment]
Hmm, you don't mean #25673, do you? They are different.

**Comment by huonw** [comment]
Oh, actually, closing as a dupe of https://github.com/rust-lang/rust/issues/25001 (thanks for filing!).
