### ISSUE TITLE
Could not compile `libc`.

### ISSUE THREAD

**Issue by kingkf** [rust-lang/rust#25672]
[xxx@ooo guessing_game]$ cargo build
   Compiling libc v0.1.8
/home/meihua/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.1.8/rust/src/liblibc/lib.rs:80:46: 80:49 error: expected `;`, found `as`
/home/meihua/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.1.8/rust/src/liblibc/lib.rs:80 #[cfg(feature = "cargo-build")] extern crate std as core;
                                                                                                                                                ^~~
/home/meihua/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.1.8/rust/src/liblibc/lib.rs:80:49: 80:49 help: perhaps you meant to enclose the crate name `std` in a string?
error: aborting due to previous error
Could not compile `libc`.

rust version:
[xxx@ooo guessing_game]$ rustc --version
rustc 1.0.0-nightly (30e1f9a1c 2015-03-14) (built 2015-03-15)

**Comment by steveklabnik** [comment]
Your Rust is very old, please update to the 1.0 final release! Thanks.
