### ISSUE TITLE
Test case: Using an iterator removes bounds check but slows down performance by near 10%

### ISSUE THREAD

**Issue by learnopengles** [rust-lang/rust#25678]
As per the comment by @bluss over here: https://users.rust-lang.org/t/how-to-speed-up-this-rust-code-im-measuring-a-30-slowdown-versus-the-c-version/1488/2?u=loes using the code at this gist: https://gist.github.com/anonymous/fd213a7b8ffdcfd219dc

Adding #[inline(never)] to apply_lowpass fixes the performance issue that was making this code slower than clang. If that's done, however, it seems that rustc can't remove the bounds check at this line:

```
output[i as usize] = get_output_sample(filter_state);
```

Replacing the body:

```
for i in 0..length {
    push_sample(filter_state, input[i as usize]);
    apply_lowpass_single(filter_state);
    output[i as usize] = get_output_sample(filter_state);
}
```

with:

```
for (input_ptr, output_ptr) in input.iter().zip(output) {
    push_sample(filter_state, *input_ptr);
    apply_lowpass_single(filter_state);
    *output_ptr = get_output_sample(filter_state);
}
```

removes all of the bounds checks, but seems to add enough extra instructions to the end of the loop that the perf is actually slowed down by nearly 10%.

**Comment by bluss** [comment]
I've actually developed a sort of mitigation for this as ZipTrusted (unstable, in itertools). Although I thought our codegen for .zip had improved since then.

**Comment by learnopengles** [comment]
I retested this and Rust is now faster than clang in this same test, with the ZIP iterator being slightly faster than the regular for loop:

### Rust
```
rustc --version
rustc 1.14.0 (e8a012324 2016-12-16)
```
(Regular for-loop)
```
cargo run --release
Dummy:0
Iterations:866
Rust Results: 90704017 shorts per second.
```
(ZIP iterator)
```
cargo run --release
Dummy:0
Iterations:885
Rust Results: 92784664 shorts per second.
```

### C++ Clang
```
clang++ --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
Thread model: posix

```
```
clang++ -std=c++11 -O2 dsp.cpp main.cpp -o dsp && ./dsp

Dummy:0
Iterations:835
C results: 87462808 shorts per second.
```

I'm curious why the for loop is slightly slower, but no matter, this particular I-slow bug is definitely no longer present on Rust 1.14!
