### ISSUE TITLE
MultiItemDecorator should take &Annotatable

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#25683]
```
pub trait ItemDecorator {
    fn expand(&self, ecx: &mut ExtCtxt, sp: Span, meta_item: &MetaItem, item: &Item, push: &mut FnMut(P<Item>));
}
```

is deprecated in favor of

```
pub trait MultiItemDecorator {
    fn expand(&self, ecx: &mut ExtCtxt, sp: Span, meta_item: &MetaItem, item: Annotatable, push: &mut FnMut(Annotatable));
}
```

The new version takes the thing being decorated by-move, and this is achieved [by a clone](https://github.com/rust-lang/rust/blob/f786437bd223740d9767345731d458d10936f8d7/src/libsyntax/ext/expand.rs#L1215). The clone is totally unnecessary; a decorator doesn't modify the original item and should be fine with a simple reference to it.

This probably causes a lot of unnecessary clones since MultiDecorators are used everywhere in the form of `#[derive]`.

Should we make this `&Annotatable` and remove the clone?

cc @nrc @huonw

**Comment by bluss** [comment]
How large is annotatable? It only matters if iit's expensive to clone.

**Comment by Manishearth** [comment]
An Annotatable is generally an Item. In this case, mostly structs and enums. Cloning a struct in the AST isn't too expensive, but when you do it multiple times for almost every struct it adds up. I'm going to profile this for the heck of it and see.

**Comment by nrc** [comment]
An `Annotatable` is just an enum of pointers (a pointer to an item, not actually an item), so it is only one word, cloning it shouldn't make any difference. Think of it as a smart pointer. Still interested to see a profile.

**Comment by Manishearth** [comment]
It contains `P` which does a deep clone
