### ISSUE TITLE
Disconnect between compiler error message and help message

### ISSUE THREAD

**Issue by tincann** [rust-lang/rust#25682]
```
src/main.rs:9:1: 9:24 error: compiler plugins are experimental and possibly buggy
src/main.rs:9 #[plugin(regex_macros)]
              ^~~~~~~~~~~~~~~~~~~~~~~
src/main.rs:9:1: 9:24 help: add #![feature(plugin)] to the crate attributes to enable
```

eddyb> ideally, the help: line would be immediately after the error: line, not after the code snippet
eddyb> that way it would be much harder to miss the help: line. there's _so_ many questions where the answer is given by the compiler after the error message, it's just not obvious because it's not "paired" visually

**Comment by MrMormon** [comment]
Maybe the Rust team is expecting a PR?

**Comment by Mark-Simulacrum** [comment]
So this is still the case today, but I'm inclined to close this issue since I think this is intentional. @rust-lang/compiler, do you agree that we don't want to move the help message above the inline source code?

```
error: compiler plugins are experimental and possibly buggy (see issue #29597)
 --> test.rs:1:1
  |
1 | #![plugin(help)]
  | ^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(plugin)] to the crate attributes to enable

error: aborting due to previous error(s)
```

**Comment by nikomatsakis** [comment]
I think the current style is fine. Closing.
