### ISSUE TITLE
failed to install rustc from source code,error unknown token.

### ISSUE THREAD

**Issue by ggaaooppeenngg** [rust-lang/rust#25699]
```
<stdin>:1:24: 1:25 error: unknown start of token: `
<stdin>:1 (A.) the Drop impl for `D` instantiates `D` at 'a directly,
                                 ^
thread '<unnamed>' panicked at 'Box<Any>', /home/tuoye.gp/workspace/rust/src/libsyntax/parse/lexer/mod.rs:167
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Any', /home/tuoye.gp/workspace/rust/src/libcore/result.rs:729
/home/tuoye.gp/workspace/rust/mk/docs.mk:264: recipe for target 'doc/rustc_typeck/index.html' failed
make[1]: *** [doc/rustc_typeck/index.html] Error 101
make[1]: Leaving directory '/home/tuoye.gp/workspace/rust'
/home/tuoye.gp/workspace/rust/mk/install.mk:16: recipe for target 'install' failed
make: *** [install] Error 2
```

I got the message above,how to fix it?

**Comment by brson** [comment]
Urgh. This should never have gotten through the CI bots. Some rules must be being built by the install target that aren't under the normal build.

**Comment by brson** [comment]
I will try to look into this today while I'm investigating other nightly breakage.

**Comment by pnkfelix** [comment]
I assume this is being introduced by the doc comment I wrote here:

  https://github.com/rust-lang/rust/blob/b5b5a177588c0e8dfc6b9e79540bcbd1eeb9ef91/src/librustc_typeck/check/dropck.rs#L245

So the two bugs here are:
  1. Fix the above doc comment in dropck.  (Presumably just replace the indents with nested bullets.)
  2. What rules do we need to change to synchronize `make install` with the CI bots (to catch this kind of case in the future) -- presumably its happening because `make install` attempts to build documentation for rust itself ... which sounds a lot like good old: #14424 ; see also #19698

**Comment by brson** [comment]
I posted a PR to stop building compiler docs. It does not fix the bug in the docs though.

**Comment by brson** [comment]
Fixed.

**Comment by brson** [comment]
Er, oh yeah, the underlying problem is not fixed, that the docs have broken examples.

**Comment by brson** [comment]
Sigh, actually, I'll call this fixed since the title of the bug is about install failure and that works now. Broken examples in the rustc crate are nbd to me atm.

**Comment by sononix** [comment]
Just downloaded a fresh install from git and ran on a virgin arch linux box running on AWS and getting this error again 

cfg: using CC=gcc (CFG_CC)
cfg: disabling valgrind run-pass tests
cfg: including prepare rules
cfg: including dist rules
cfg: including install rules
cleaning destination tmp/dist/rustc-1.5.0-dev-x86_64-unknown-linux-gnu-image
prepare: tmp/dist/rustc-1.5.0-dev-x86_64-unknown-linux-gnu-image/bin
prepare: tmp/dist/rustc-1.5.0-dev-x86_64-unknown-linux-gnu-image/lib
prepare: tmp/dist/rustc-1.5.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/etc
prepare: tmp/dist/rustc-1.5.0-dev-x86_64-unknown-linux-gnu-image/share/man/man1
rustc: x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc
/root/Downloads/rust/mk/target.mk:164: recipe for target 'x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/stamp.rustc' failed
make[1]: *** [x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/stamp.rustc] Killed
make[1]: Leaving directory '/root/Downloads/rust'
/root/Downloads/rust/mk/install.mk:16: recipe for target 'install' failed
make: *** [install] Error 2

any ideas
