### ISSUE TITLE
[[T]] is allowed in structs

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust#25692]
The following construct compiles:

```rust
struct Foo {
 foo: [[u8]],
}
```

Even though `let foo: [[u8]]` doesn't. From my [very limited understanding](https://github.com/rust-lang/rust-by-example/issues/576) this type doesn't make sense, so it'd be nice if the compiler rejected it at the point of definition.

**Comment by cybergeek94** [comment]
Because of `[[u8]]`, `Foo` is an unsized struct, or a dynamically sized type (DST), which means it can only be bound by `let` behind a pointer, e.g. `&Foo` or `Box<Foo>`. It's the same with a bare `[[u8]]`.

**Comment by Diggsey** [comment]
No, pornel is right, `[u8]` is a DST, but `[[u8]]` is an invalid type - you can't have a slice of DSTs because arrays/slices require that all of their elements are the same size.

**Comment by cybergeek94** [comment]
That makes sense now. The `let foo: [[u8]]` part threw me off, made it sound like the problem was simpler than that. You can't bind DST to the stack.

**Comment by Manishearth** [comment]
The same goes for `[str]`, as was brought up in irc yesterday.

These aren't types that can ever be constructed, and the compiler doesn't know how to handle them, so they should be forbidden in all places.

**Comment by Manishearth** [comment]
See also: https://github.com/rust-lang/rust/issues/21748


The generic issue is that `[T]` should be `[T]` where `T: Sized` internally.

**Comment by eddyb** [comment]
`[[T]]` makes perfect sense as `exists N, M.[[T; N]; M]`, it's just not implemented - that's the main reason we should require `T: Sized` in `[T]` for now.

**Comment by brson** [comment]
Nominating because rustc accepts bogus syntax.

**Comment by nikomatsakis** [comment]
triage: P-medium

Assigning medium priority since it's hard to construct useful programs that rely on this, as far as I know.

**Comment by TimNN** [comment]
This seems to have been fixed on stable: http://is.gd/P0QUd6

**Comment by alexcrichton** [comment]
Yay!
