### ISSUE TITLE
'Mismatched type' error doesn't use aliased type names

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust#25694]
``` rust
type mytype = f32;

fn main() {
    let foo: mytype = 1usize;
}
```

fails with:

>  expected `f32`,
>    found `usize`

but I'd expect it to say something along the lines:

>  expected `mytype` (`f32`)
>    found `usize`

(The problem has been mentioned in comments of #3417)

**Comment by ebfull** [comment]
Associated types act as type synonyms in the same sense, and it would be nice if error message included those where applicable as well.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/17164.
