### ISSUE TITLE
Mac OS X installer does not document supported versions & fails with unhelpful message on old Mac

### ISSUE THREAD

**Issue by mcclure** [rust-lang/rust#25704]
If I go to rust-lang.org, I see a big friendly blue "Install" button labeled with:
Recommended Version:
1.0.0 (Mac installer)

Problem 1: You do not clarify on the web page which versions of Mac the installer runs on (OS version, and if 10.6 or older is supported, 32- or 64- bit).

Problem 2: When I click the "install" button and run the pkg, it quickly halts with this message:

![screen shot 2015-05-21 at 10 40 16 pm](https://cloud.githubusercontent.com/assets/277318/7771029/801d3d4c-0051-11e5-9aac-9356365c8ae3.png)

Notice the buttons are grayed out— clicking on them does nothing. This error message makes no sense at all.

For context, I am running 10.6.8 on 64-bit intel (this is fairly old in Mac years, so it would be unsurprising if the Rust binaries do not support it). While the Installer is running, these messages appear in Console.app:

![screen shot 2015-05-22 at 7 08 45 am](https://cloud.githubusercontent.com/assets/277318/7771036/95968728-0051-11e5-8f78-3dbb6af6f8d9.png)

Expected behavior: If the installer fails, it should be with an error message that makes sense. If my operating system version is not supported, I would expect the Rust web page or installer to simply tell me so.

**Comment by cmr** [comment]
Moved to https://github.com/rust-lang/rust-installer/issues/35

**Comment by cmr** [comment]
(Thanks for the report!)
