### ISSUE TITLE
Robust error explanation index and error code uniqueness checking

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#25705]
The PR's #25380 #25592 #25603 were motivated by brittleness such as #25364.

But removing the diagnostics metadata output and checking represents a step backward, in that we no longer have an auto-generated error index (nor uniqueness checking).

This issue is a work-item to put those two features back.

**Comment by mcast** [comment]
> [...] we no longer have an auto-generated error index (nor uniqueness checking).
> This issue is a work-item to put those two features back.

Are these two both covered by #26009 ?

> It'd be nice to hang on to the error index in the Rust 1.2 release... currently it's disabled due to
> [...]
> * In the error-index-generator - which runs once all crates have been compiled - we can check uniqueness.

(Via #26240)

**Comment by michaelsproul** [comment]
> Are these two both covered by #26009 ?

Yeah, this a "duplicate", but it's my fault, I created #26009 because I hadn't seen this.
