### ISSUE TITLE
RangeFrom loops endlessly

### ISSUE THREAD

**Issue by anmej** [rust-lang/rust#25707]
`for i in (254u8..) { println!("{:?}", i) }` will not stop at 255, but instead loops back to 0 and continues from there.

**Comment by Kimundi** [comment]
https://github.com/rust-lang/rust/issues/20249 indicates this is intentional

**Comment by Gankro** [comment]
Note that it should panic in debug builds

**Comment by Gankro** [comment]
See #25696 for assertions that this is not desirable behaviour
