### ISSUE TITLE
REPL like jshell(JEP 222)?

### ISSUE THREAD

**Issue by jjia-acme** [rust-lang/rust#25712]
can we have a REPL console?
like in Java
http://openjdk.java.net/jeps/222

**Comment by pnkfelix** [comment]
For online experimentation, there is the playpen: https://play.rust-lang.org/

You can also send expressions to the `playbot` on the `#rust` IRC channel.

We used to have an experimental command line REPL, `rusti`, but it was brittle and not maintained well, so it was eventually retired.  See PR #9897

There may be future attempts to make a rust repl atop other components provided here, but I do not know if such a tool will ever again be part of the rust project itself.  In any case, such a tool certainly seems like it would need to first go through the RFC process:

  https://github.com/rust-lang/rfcs#when-you-need-to-follow-this-process

**Comment by jjia-acme** [comment]
thank you for your useful info!
