### ISSUE TITLE
Docs: stable and nightly are showing broken ^ anchors

### ISSUE THREAD

**Issue by alfiedotwtf** [rust-lang/rust#25721]
I've noticed in a couple of places that ^anchors look broken e.g:

    http://doc.rust-lang.org/stable/book/the-stack-and-the-heap.html

The docs currently being served show:

    "In this case, however, it doesn’t.[moving] When the function is over, we need to free the stack"

Building the docs locally however gives me:

    "In this case, however, it doesn’t.1 When the function is over, we need to free the stack"

**Comment by killercup** [comment]
I think #25601 fixes this. The nightly docs should contain it when the next nightly is built.

**Comment by steveklabnik** [comment]
Yes, that's correct.

**Comment by alfiedotwtf** [comment]
Amesome.

Sorry for the dup!
