### ISSUE TITLE
Builds with multiple --host's are broken

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#25723]
The build system now expects all non-build-triple platforms to use an explicit linker, but no platforms provide this but MSVC.

cc https://github.com/rust-lang/rust/pull/25719

**Comment by brson** [comment]
The problem is the `LINK_{triple}` variables in `platform.mk` are all undefined.

**Comment by brson** [comment]
cc @alexcrichton

**Comment by Stebalien** [comment]
cc  #25727

**Comment by alexcrichton** [comment]
guh, sorry about this!
