### ISSUE TITLE
Upload feature list to s3

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#25724]
The feature list displayed during tidy is useful for reporting purposes. Have the doc build generate it so it's uploaded nightly, in json format probably.

**Comment by brson** [comment]
Let's upload it with the docs. Easiest.

The script src/etc/featureck.py knows how to extract metadata for all the features. Modify this script so that, if given a new command line argument, outputs that metadata in json format, then modify `mk/docs.mk` to call this script and output the json to the `doc/` folder. That should be sufficient to upload the information.

@aturon json is sufficient right? You are going to further refine that data to put it on a website somewhere?

**Comment by aturon** [comment]
@brson json is great. The current intended use case is for a tool that generates stubs for the weekly subteam report stubs.

**Comment by steveklabnik** [comment]
Triage: no change.

https://internals.rust-lang.org/t/the-most-used-unstable-features-in-rust/4370 is related and was posted recently.

**Comment by Mark-Simulacrum** [comment]
No change once more. I'm somewhat uncertain that we want this, too; it feels like a nice thing I suppose but not all that useful. Unless I'm missing a use case of course.

**Comment by steveklabnik** [comment]
Triage: we have the unstable book as a list of features, though that's not for exactly the same purpose. Regardless, nobody else has wanted this in the past few years, so I doubt it's ever going to be implemented. Closing!
