### ISSUE TITLE
rustc crashes while compiling my experimental kernel (index out of bounds panic)

### ISSUE THREAD

**Issue by ababo** [rust-lang/rust#25732]
The bug appeared since built 2015-05-02 (carefully checked). Here is the output for this build:

```
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'index out of bounds: the len is 70 but the index is 70', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcollections/vec.rs:1349

stack backtrace:
   1:     0x2b070bd67ee9 - sys::backtrace::write::h9d474f8e9af32ff4eas
   2:     0x2b070bd6fa29 - panicking::on_panic::h780bc016e25d560eHOw
   3:     0x2b070bd30a52 - rt::unwind::begin_unwind_inner::he10b5af763481bfaRtw
   4:     0x2b070bd31817 - rt::unwind::begin_unwind_fmt::h9bb9f2d65e37b92bXsw
   5:     0x2b070bd6f606 - rust_begin_unwind
   6:     0x2b070bdbbdd4 - panicking::panic_fmt::h11c0222b0ca0e381hJy
   7:     0x2b070bdc60bc - panicking::panic_bounds_check::he71f2efcc0ad7c8bnIy
   8:     0x2b070dbe05e9 - middle::lang_items::LanguageItemCollector<'a>::collect_item::hffbd84ccf0676757NTB
   9:     0x2b070dbe3d0d - middle::lang_items::collect_language_items::hbb4d88a5751ae1c2zXB
  10:     0x2b070b998dd6 - driver::phase_3_run_analysis_passes::h876ca40ef22f652btGa
  11:     0x2b070b97bfec - driver::compile_input::h19dbb81f9d079a10Qba
  12:     0x2b070ba34dc1 - run_compiler::h6fdcc5ae4819da2c65b
  13:     0x2b070ba32612 - boxed::F.FnBox<A>::call_box::h15867338134671801927
  14:     0x2b070ba31bd9 - rt::unwind::try::try_fn::h10571205104630549427
  15:     0x2b070bde32f8 - rust_try_inner
  16:     0x2b070bde32e5 - rust_try
  17:     0x2b070ba31e74 - boxed::F.FnBox<A>::call_box::h11752498478748955554
  18:     0x2b070bd6e7c1 - sys::thread::Thread::new::thread_start::h9f92b31902592327dAv
  19:     0x2b0711ef0181 - start_thread
  20:     0x2b070c37847c - __clone
  21:                0x0 - <unknown>
```

With current nightly version I get the different output:

```
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'assertion failed: `(left == right)` (left: `60789`, right: `60794`)', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librbml/lib.rs:462

stack backtrace:
   1:     0x2b4b4f916169 - sys::backtrace::write::h4052d6a51ba10f8105r
   2:     0x2b4b4f91e0b9 - panicking::on_panic::h90cadee2464dd3b41Kw
   3:     0x2b4b4f8df192 - rt::unwind::begin_unwind_inner::ha0307b6be50a7723bqw
   4:     0x2b4b4f8dff27 - rt::unwind::begin_unwind_fmt::hb83f1cf97f4362d4hpw
   5:     0x2b4b565fbb24 - reader::doc_as_u64::h909934356f9014c5HNa
   6:     0x2b4b518b6507 - metadata::decoder::translated_def_id::h27b3403b26a49f9edxj
   7:     0x2b4b50664b7e - build_reduced_graph::GraphBuilder<'a, 'b, 'tcx>::build_reduced_graph_for_item::hfad93f34f73d6f31hSa
   8:     0x2b4b5065f56f - build_reduced_graph::BuildReducedGraphVisitor<'a, 'b, 'tcx>.Visitor<'v>::visit_item::h5827d119cd5f21d5MNb
   9:     0x2b4b506b4c6a - resolve_crate::h9b28f68538793170iai
  10:     0x2b4b4f5449c2 - driver::phase_3_run_analysis_passes::h83b5112ae07f494ftGa
  11:     0x2b4b4f52a0cc - driver::compile_input::h0a7842b43c159d70Qba
  12:     0x2b4b4f5e0011 - run_compiler::hb2dfa1770188c5e175b
  13:     0x2b4b4f5dd862 - boxed::F.FnBox<A>::call_box::h10739628233630710986
  14:     0x2b4b4f5dce29 - rt::unwind::try::try_fn::h12004866116241301408
  15:     0x2b4b4f9967c8 - rust_try_inner
  16:     0x2b4b4f9967b5 - rust_try
  17:     0x2b4b4f5dd0c4 - boxed::F.FnBox<A>::call_box::h9242018289459349633
  18:     0x2b4b4f91ce51 - sys::thread::Thread::new::thread_start::he4baa243e39f5dd6ixv
  19:     0x2b4b55ab5181 - start_thread
  20:     0x2b4b4ff2c47c - __clone
  21:                0x0 - <unknown>
```

Reproduced in Ubuntu 14.04 with code from [here] (https://github.com/ababo/toy/tree/f97794b3a4fe1d1a6626102895e9aea15d449866).

**Comment by Stebalien** [comment]
dup of  #24474

**Comment by ababo** [comment]
You hurry to much closing the issue. Current nightly release:

error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'assertion failed: `(left == right)` (left: `60789`, right: `60794`)', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/librbml/lib.rs:485


make: *** [/Users/ababo/Dropbox/toy/build-x86_64/kernel.o] Error 101
Simons-MacBook-Pro:toy ababo$ export RUST_BACKTRACE=1
Simons-MacBook-Pro:toy ababo$ make run ARCH=x86_64
Compiling /Users/ababo/Dropbox/toy/build-x86_64/kernel.o
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'assertion failed: `(left == right)` (left: `60789`, right: `60794`)', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/librbml/lib.rs:485

stack backtrace:
   1:        0x105f9ff6f - sys::backtrace::write::h194a2b834b3389c8x3r
   2:        0x105fa8ad0 - panicking::on_panic::hed7c6101b1a9182d8jw
   3:        0x105f637c5 - rt::unwind::begin_unwind_inner::h9eb24763cabf3cbaR1v
   4:        0x105f645cc - rt::unwind::begin_unwind_fmt::h47924304389d18bdX0v
   5:        0x10395bc37 - reader::doc_as_u64::hcd14114c0a7fdabaAOa
   6:        0x1032ceeda - metadata::decoder::translated_def_id::hfd5d194675dbba19cik
   7:        0x102b73ef8 - build_reduced_graph::GraphBuilder<'a, 'b, 'tcx>::build_reduced_graph_for_item::he65a941351264377hSa
   8:        0x102b6de22 - build_reduced_graph::BuildReducedGraphVisitor<'a, 'b, 'tcx>.Visitor<'v>::visit_item::h43a0fad5183a9d48NNb
   9:        0x102bcc4fa - resolve_crate::h59078e6b1e6f701dTai
  10:        0x102653e3b - driver::phase_3_run_analysis_passes::hbd0ee74091130d46GGa
  11:        0x102639933 - driver::compile_input::h7ce6bdafd400a500Qba
  12:        0x1026f5ed4 - run_compiler::hca164b07e3bf1f85o6b
  13:        0x1026f363a - boxed::F.FnBox<A>::call_box::h7101975463738732429
  14:        0x1026f2d37 - rt::unwind::try::try_fn::h15875263410352898573
  15:        0x1060310e8 - rust_try_inner
  16:        0x1060310d5 - rust_try
  17:        0x105f92c65 - rt::unwind::try::inner_try::h1407c16b806277acKXv
  18:        0x1026f2fb5 - boxed::F.FnBox<A>::call_box::h5243292170036710726
  19:        0x105fa75dd - sys::thread::Thread::new::thread_start::h537b42626c7f5c37nmv
  20:     0x7fff93a31267 - _pthread_body
  21:     0x7fff93a311e4 - _pthread_start

**Comment by alexcrichton** [comment]
@ababo ah don't worry, I just closed this as a dupe of https://github.com/rust-lang/rust/issues/24474 as @Stebalien mentioned, it's still a very real issue!
