### ISSUE TITLE
std::boxed::into_raw should be marked as safe

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/rust#25755]
If I understand the [reasoning behind marking `mem::forget`](https://github.com/rust-lang/rust/commit/dd59b1fb4c66089c10b7e189975aeb171085312e) safe, then I think the same should apply to `into_raw`.

Currently, [it says](https://github.com/rust-lang/rust/blob/820b1d83933d1a3ddcc18e6cfcfea91b6ee2eee6/src/liballoc/boxed.rs#L142-L144):

> Function is unsafe, because result of this function is no longer automatically managed that may lead to memory or other resource leak.

**Comment by Gankro** [comment]
Agreed. It's safe. Basically a mem::forget that returns an integer.
