### ISSUE TITLE
`nocapture` attribute is missing on function arguments

### ISSUE THREAD

**Issue by dotdash** [rust-lang/rust#25759]
In a function like `fn foo(x: &i32)`, the pointer is known not to be captured by the function because its lifetime doesn't allow it. We used to emit the `nocapture` attribute for such function arguments but don't do so anymore.

**Comment by dotdash** [comment]
I briefly discussed this with @eddyb on irc the other day, and the way we used to set `nocapture` would allow for undefined behaviour in safe code:

```rust
fn foo(x: &i32) -> *const i32 {
    x as *const i32
}
```

Since we based the attribute purely on the fact that the pointer has an anonymous lifetime, `nocapture` would be set here, although the pointer does escape.

I assume we don't want to have UB in safe code, right? That would mean that we need to perform some analysis on the function body to determine which attributes we can emit and that we need to emit those attributes in the metadata, because other crates can't necessarilly perform this analysis, because they don't have access to the function body at all.

**Comment by shepmaster** [comment]
What are the benefits of applying the `nocapture` attribute when it is valid?

**Comment by ranma42** [comment]
LLVM seems to be inferring the `nocapture` attribute in the `functionattrs` pass. I think that, thank to lifetimes, the analysis performed in Rust could be more accurate than that performed in LLVM, but for trivial examples LLVM computes the attribute as desired.

**Comment by dotdash** [comment]
@ranma LLVM can't do that for external functions though. We'd still have to store the information in the crate metadata, even if we don't perform the analysis ourselves and just inspect what LLVM could infer.

**Comment by nikomatsakis** [comment]
In the absence of clearer unsafe code guidelines, it is not clear when we should add this attribute anyhow.

**Comment by brson** [comment]
Wishlist. If somebody ever figures it out, great.
