### ISSUE TITLE
Cover the short form match arm syntax Point { x, y } in addition to Point { x: x, y: y }

### ISSUE THREAD

**Issue by nliberg** [rust-lang/rust#25779]
The patterns.md page doesn't explain that it's possible to match compound data in this way:
 `match origin { Point { x, y, .. } => ()`
Currently only this form is covered:
`match origin { Point { x: x, y: y, .. } => ()`

The latter form results in compiler warnings (`warning: the y: in this pattern is redundant and can be removed`). I'm not sure whether it should be avoided for that reason.

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/26108 fixed this
