### ISSUE TITLE
rustc panic on crazy lifetime code

### ISSUE THREAD

**Issue by ericsink** [rust-lang/rust#25774]
rustc just asked me to file a bug report.

The code that causes rustc to panic is in the following gist:

https://gist.github.com/ericsink/94835e3ed01784f3225a

Sorry for the ~4000 line file.  I have no idea how to trim it down to something smaller that still reproduces the panic.

I was trying to give struct SegmentCursor a reference back to the struct db that created it.  So I had to start adding explicit lifetimes all over the place.

FWIW, if you want to see or diff from the place I started before making the change that caused rustc to panic, the file is here:

https://github.com/ericsink/LSM/blob/master/rs/src/lib.rs

and the version you want is in this commit:

0bc3e474c3b9da43807ac73849daf0068ec1735a

But anyway

Here's the compiler I'm using:

rustc 1.1.0-nightly (c4b23aec4 2015-04-29) (built 2015-04-28)
binary: rustc
commit-hash: c4b23aec4c5ddf32df1e0ba3cc23212327cd8b1f
commit-date: 2015-04-29
build-date: 2015-04-28
host: x86_64-apple-darwin
release: 1.1.0-nightly

And here's the stack trace:

thread 'rustc' panicked at 'Box<Any>', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libsyntax/diagnostic.rs:170

stack backtrace:
   1:        0x10529f24f - sys::backtrace::write::h0714aaf7fe41e02dzVr
   2:        0x1052a78c0 - panicking::on_panic::hb86b9b356f51f92dEVv
   3:        0x105263c35 - rt::unwind::begin_unwind_inner::h58f79e41dbedf2efnDv
   4:        0x104a5598e - rt::unwind::begin_unwind::h17476740655312162035
   5:        0x104a5591a - diagnostic::SpanHandler::span_bug::h6ece18e7aebef0b3cFB
   6:        0x1024fd71b - middle::infer::region_inference::RegionVarBindings<'a, 'tcx>::make_subregion::he60a593b72e2fd85yhv
   7:        0x1024b8758 - middle::infer::region_inference::RegionVarBindings<'a, 'tcx>::make_eqregion::hf65096ae1c1b3b0a0gv
   8:        0x1024b091b - middle::infer::equate::Equate<'a, 'tcx>.TypeRelation<'a, 'tcx>::regions::hfa4c86be50c0c9c07pq
   9:        0x1024b46a9 - middle::infer::sub::Sub<'a, 'tcx>.TypeRelation<'a, 'tcx>::relate_with_variance::h9286450150694230498
  10:        0x1024b3d3b - middle::ty_relate::relate_substs::h10097045333893871943
  11:        0x1024b332a - middle::ty_relate::relate_item_substs::h4357746226965114642
  12:        0x102513b27 - middle::ty_relate::super_relate_tys::h16553438660823187938
  13:        0x1024abc32 - middle::infer::sub::Sub<'a, 'tcx>.TypeRelation<'a, 'tcx>::tys::h0720d2122871d207jpx
  14:        0x102518617 - middle::infer::InferCtxt<'a, 'tcx>::sub_types::h83d8b857be0b9449iTy
  15:        0x10208183f - check::method::probe::ProbeContext<'a, 'tcx>::consider_candidates::h959372f449962be611h
  16:        0x1020815cf - check::method::probe::ProbeContext<'a, 'tcx>::pick_method::hedc4369721a1e898YXh
  17:        0x1020809c6 - check::method::probe::ProbeContext<'a, 'tcx>::pick_core::h61b45ed4a4578cc9SSh
  18:        0x1020767bc - check::method::probe::probe::closure.31731
  19:        0x102074029 - check::method::probe::probe::hee4923d75a19097b8Hg
  20:        0x10202d9e4 - check::resolve_ty_and_def_ufcs::h244d6b4b01dd80bbiYr
  21:        0x102110b40 - check::check_expr_with_unifier::h8527598931454308257
  22:        0x1020af74c - check::callee::check_call::h9d48641f8dbf70e8uVl
  23:        0x1020db456 - check::check_expr_with_unifier::h2620947197098337973
  24:        0x1020b550c - check::check_argument_types::h382f9297397ef06cq0p
  25:        0x1020b28de - check::callee::confirm_builtin_call::hbc010ad4f4bda7d8M4l
  26:        0x1020b1069 - check::callee::check_call::h9d48641f8dbf70e8uVl
  27:        0x1020f6e31 - check::check_expr_with_unifier::h17685357569681961405
  28:        0x1020cbd9b - check::check_block_with_expected::hcfa15fbdb8c43f45tds
  29:        0x1020f74b8 - check::check_expr_with_unifier::h17685357569681961405
  30:        0x102035c83 - check::_match::check_match::closure.29464
  31:        0x1020359c1 - check::_match::check_match::h1ee836cfebb44c84Vqb
  32:        0x1020f7454 - check::check_expr_with_unifier::h17685357569681961405
  33:        0x1020cbd9b - check::check_block_with_expected::hcfa15fbdb8c43f45tds
  34:        0x102102335 - check::check_expr_with_unifier::h16667247497716976070
  35:        0x1020e06f8 - check::check_expr_with_unifier::check_then_else::h0086fe91e78fdbceRCq
  36:        0x1020f72c0 - check::check_expr_with_unifier::h17685357569681961405
  37:        0x1020cbd9b - check::check_block_with_expected::hcfa15fbdb8c43f45tds
  38:        0x1020aed28 - check::check_fn::hfb888ade54742a88nSn
  39:        0x1020c71a5 - check::check_bare_fn::h01c9c7a0b174d430WHn
  40:        0x1020d2c07 - check::check_method_body::h2fc6b3c8015b76ccXjo
  41:        0x1020c504b - check::CheckItemBodiesVisitor<'a, 'tcx>.Visitor<'tcx>::visit_item::hbef2e2a14382e80aZEn
  42:        0x10218a74a - check_crate::closure.38872
  43:        0x102185b77 - check_crate::h782cff8740252e81rCC
  44:        0x1019da124 - driver::phase_3_run_analysis_passes::h2554ff95bce00587tGa
  45:        0x1019bc18c - driver::compile_input::h7c6cf9b085c57594Qba
  46:        0x101a7bac3 - run_compiler::h55b523753cbd518765b
  47:        0x101a7922a - boxed::F.FnBox<A>::call_box::h11476165885616507686
  48:        0x101a78767 - rt::unwind::try::try_fn::h13518150216340287792
  49:        0x105329c58 - rust_try_inner
  50:        0x105329c45 - rust_try
  51:        0x101a78a4e - boxed::F.FnBox<A>::call_box::h735039165869315632
  52:        0x1052a62bd - sys::thread::Thread::new::thread_start::hf4c42a114072ab47mYu
  53:     0x7fff8aca1898 - _pthread_body
  54:     0x7fff8aca1729 - _pthread_start

**Comment by ericsink** [comment]
And here's the error message from the compiler:

src/lib.rs:1:1: 1:1 error: internal compiler error: cannot relate bound region: ReEarlyBound(14123, TypeSpace, 0, 'a) <= ReStatic
src/lib.rs:1 /*
             ^
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
erics-air-2:rs eric$

**Comment by shepmaster** [comment]
You may want to use backticks to format your code nicer:

\`\`\`rust
code here
\`\`\` 

becomes

```rust
code here
```

**Comment by shepmaster** [comment]
Example file has a nice error message in `rustc 1.2.0-dev (893e41693 2015-05-24) (built 2015-05-25)`:

```
repro.rs:3558:32: 3558:83 error: this function takes 4 parameters but 3 parameters were supplied [E0061]
repro.rs:3558                 let csr = try!(SegmentCursor::new(&self.path, self.pgsz, rootPage));
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by ericsink** [comment]
Ah.  Yes, I just upgraded to a new nightly and discovered the same thing.  Closing the issue.
