### ISSUE TITLE
Update or remove `make nitty-gritty`?

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/rust#25775]
So there's [this text in nitty-gritty that says this section is outdated](https://github.com/rust-lang/rust/blob/master/Makefile.in#L112-L118), and [THAT text was last edited over a year ago](https://github.com/rust-lang/rust/commit/334af011f01ceda1086d335231ada3363190b8a9).

Given that text and its history, should nitty-gritty just be removed? (I can totally do that ;)) If not, this could use some updating (but I'm not sure what it should be updated with).

**Comment by steveklabnik** [comment]
:+1:

**Comment by richo** [comment]
I've been thinking seriously that I want to write up some docs on the make
infra.

Nitty gritty isn't in a good place but it's some of the only docs we have
and I've used it. Id be sad if it got deleted.

**Comment by steveklabnik** [comment]
Triage: no change, other than the fact that rustbuild will eventually make this obsolete.

**Comment by alexcrichton** [comment]
Make's now gone, so closing.
