### ISSUE TITLE
Static methods provided through dereferences should not be shown 

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#25782]
Documentation for `CString` lists [from_ptr] as a method provided through `Deref<Target=CStr>`, but my crude testing has showed you cannot use it through CString (and perhaps all static methods provided this way). Perhaps such static methods should not be listed in the documentation?

[from_ptr]: http://doc.rust-lang.org/nightly/std/ffi/struct.CString.html#method.from_ptr

**Comment by bluss** [comment]
dup of #24575

**Comment by nagisa** [comment]
Indeed. Thanks @bluss
