### ISSUE TITLE
Release train paths under Windows

### ISSUE THREAD

**Issue by ndarilek** [rust-lang/rust#25781]
I use Mingw and its associated shells under Windows. Unfortunately, there's an ugly issue where the Windows path is only propagated to Mingw shells on first boot, making Rust upgrades a bit more difficult. If I want to use Rust in my mingw shell, I have to reboot or use vanilla cmd.

For instance, Rust is now in c:\program files\rust stable 1.0. (Or something similar, in any case.) Might it make more sense to instead use c:\program files\rust {stable,beta,nightly}? Then I can run separate toolchains if I like and switch my path accordingly, but a 1.0-1.1 upgrade won't break my path if I want to stick with stable. This moves the version information out of the path, but is it really necessary when `rustc -v` works everywhere consistently? Perhaps I might want multiple stable/beta versions installed, but in that case the advanced installer would let me choose another directory anyway. This would also help with the uninstall case--I've used Windows versions for the past 6-8 months or so and my path was littered with a whole bunch of old directories that weren't removed when I uninstalled older versions. :)

Thanks.

**Comment by Diggsey** [comment]
I've been using rust with mingw for a while and I haven't encountered this issue - simply starting a new msys2 shell will get fresh versions of the environment variables, exactly the same as with vanilla cmd. Is this a known bug with msys?

**Comment by ndarilek** [comment]
Maybe it's how I run my shells, I don't use msys2, but rather win-r "bash".

Right now, for instance, if I run cmd directly, cargo and rustc work. If
I run bash first, they don't. If paths don't change, I find this problem
doesn't appear, and most binaries which I run from the command line
don't embed the version into the path.

**Comment by retep998** [comment]
The environment variables of a process are based on the environment variables when the process starts up. This means that you need to fully close and reopen bash in order for changes to `PATH` to be recognized.

**Comment by ndarilek** [comment]
Yeah, Linux user since Slackware '96 here. :) I wish that was true in
this instance but it isn't.

**Comment by brson** [comment]
This does sound like a slightly unexpected setup, but from the description (things sort of work sometimes) it sounds like there may be some solution.

**Comment by iopq** [comment]
@ndarilek try this work-around: https://iopq.wordpress.com/2015/03/09/how-to-update-the-path-variable-on-windows-without-logging-off-or-rebooting/

**Comment by steveklabnik** [comment]
@ndarilek have you seen this lately? https://github.com/rust-lang/rust-packaging/pull/52 should be helping.

**Comment by Mark-Simulacrum** [comment]
I'm going to close -- I feel like this is something that we might be able to handle better but @ndarilek hasn't responded if the workaround or the PR linked in the previous comment helped. It also seems like others don't experience this, so perhaps it's an environment specific issue (though we'd love to alleviate those too).

**Comment by ndarilek** [comment]
Ack, sorry I failed to respond, I switched back to Linux 1.5 years ago 
and couldn't be happier. Not sure if this issue still exists, but I 
haven't been in a position to test it for a while anyway. Thanks for 
closing it.
