### ISSUE TITLE
Rustdoc: Named hyperlinks broken in summaries

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#25787]
This link:

http://alexcrichton.com/git2-rs/git2/index.html

displays:

>  A structure to represent a git [refspec][1].

-----------

This link:

http://alexcrichton.com/git2-rs/git2/struct.Refspec.html

displays:

> A structure to represent a git [refspec](http://git-scm.com/book/en/Git-Internals-The-Refspec).

**Comment by bluss** [comment]
Summaries also show `**boldface**` with asterisks verbatim, no bold.
