### ISSUE TITLE
Document the functionality of the placeholder operator character `_`

### ISSUE THREAD

**Issue by skeuomorf** [rust-lang/rust#25786]
Currently there isn't documentation explaining how the `_` character works

**Comment by barca** [comment]
Are you referring to its usage or implementation.  Currently the book provides a very brief description of what _ does, however I could write up something slightly more detailed if desired. (see below):
http://blog.vrinek.io/rust/doc/book/patterns.html

**Comment by skeuomorf** [comment]
@barca Hmm, the conversation that starts here https://botbot.me/mozilla/rust/2015-05-25/?msg=40115096&page=31 might be interesting
