### ISSUE TITLE
documentations 404 page numbering starts with 0.1

### ISSUE THREAD

**Issue by benaryorg** [rust-lang/rust#25794]
I was viewing the [documentation](http://doc.rust-lang.org) when I (do not ask how) visited the site [/std/copy/index.html](http://doc.rust-lang.org/std/copy/index.html).

I immediately noticed that the numbering began with
> 0.1 Search

I looked up the corresponding sources ([/src/doc/not_found.md](https://github.com/rust-lang/rust/blob/5449f5d29e175230a1285ebe92394f50c76e1df6/src/doc/not_found.md)).

I am neither sure if this is a bug, nor am I sure if this is already fixed as I am not familiar with the structure of your documentation.

**Comment by brson** [comment]
I agree it would be better to have something else as section headers here.
