### ISSUE TITLE
Publish signing key and security team key to keybase.io

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#25815]
keybase.io is a seemingly-popular new service for validating GPG keys. I'd like to publish our keys there but haven't gotten around to it.

**Comment by steveklabnik** [comment]
If you need an invite, I can send you one.

**Comment by edunham** [comment]
Is there a centralized email address or alias that we use for the security team? I have spare keybase.io invites and can set it up, if I can get access to that alias. 

It's probably preferable to base the account and identity on a transferrable account rather than any one team member, so we can handle turnover more gracefully.

**Comment by alexcrichton** [comment]
We do have a security mailing list set up at security@rust-lang.org, but it's currently primarily related to [safely disclosing security bugs](http://www.rust-lang.org/security.html). I don't believe that we currently have an email alias for gpg keys and such. The email listed on the signing key itself is rust-key@rust-lang.org, and we could probably set up an alias for that (done through DNS I believe).

**Comment by edunham** [comment]
I've created the rust-key email alias, currently directing just to me (but I can add others). The keybase identity is at https://keybase.io/rust . 

The next step is for someone who holds the private key to https://raw.githubusercontent.com/rust-lang/rust-www/gh-pages/rust-key.gpg.ascii to run the command in https://gist.github.com/edunham/f556f8c22c336077754b to verify that the key is really ours. 

If that was the wrong key to verify, I'll need to either generate a link for the right public key or get the keybase login credentials to someone with the public and private keys so they can do it. 

Once the command in that gist has been run, I'll upload the project logo as the account's avatar as well.

**Comment by alexcrichton** [comment]
Done! https://keybase.io/rust
