### ISSUE TITLE
compiler crashes when trying to infer return type in impl

### ISSUE THREAD

**Issue by hclarke** [rust-lang/rust#25810]
i'm using the higher kinded type hack mentioned in this rfc: https://github.com/rust-lang/rfcs/blob/master/text/0195-associated-items.md#encoding-higher-kinded-types

if i use the same function signature in the impl as in the trait, the compiler crashes: https://play.rust-lang.org/?gist=16c39194b959959dc326&version=stable

but if the impl fn's return type is more specific, it works fine: https://play.rust-lang.org/?gist=e94d2b8108f14d6bc370&version=stable

**Comment by steveklabnik** [comment]
This no longer ICEs as of `rustc 1.6.0-nightly (9303055f3 2015-11-19)`
