### ISSUE TITLE
Add a revocation cert to the Rust signing key

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#25814]
When I generated this key I foolishly decided not to add a rev cert. Add one to the key, republish it to static.rust-lang.org and the keyservers, send copies to the people who should have it, update the copy baked into multirust.

I _suspect_ that augmenting the pubkey this way is 'backwards compatible' in that it won't disrupt validations by people using the old key, but I do not know this. Find this out first!

**Comment by edunham** [comment]
I just did a quick local test to confirm my assumption that generating a revocation cert is doesn't change the key itself:

* generate test key
* export test key into `before_cert` file
* generate revocation cert for test key
* export test key into `after_cert` file
* diff `before_cert` against `after_cert`, and they were identical

Anyone who holds the private key can generate a revocation cert, stating a reason and adding an optional description. We then store the revocation cert somewhere safe until we want to revoke the key, when we use it with `gpg --import revocation_cert_filename` and then use `gpg --send-keys` to push the revoked key to the keyservers and deactivate it (as described [here](http://www.hackdiary.com/2004/01/18/revoking-a-gpg-key/)). 

This means we won't need to republish the public key or anything.

If everyone who holds a copy of the private key generates their own revocation cert, we'd know exactly who revoked the key if anyone ever did, but I'm not sure if this is information we'll ever want. 

In the long term, it would be better to have each person who needs to use the key actually hold a [subkey](https://wiki.debian.org/Subkeys) of the signing key, and keep the actual master key Super Secret (TM).

**Comment by muggenhor** [comment]
If revocation's the only goal you can also designate other people's keys as revokers. I.e. you don't need any of a key's secret material to revoke it.

Look at the [GPG documentation](https://gnupg.org/documentation/manuals/gnupg/OpenPGP-Key-Management.html#OpenPGP-Key-Management) for the `addrevoker` command (in the `--edit-key` menu) and the `--desig-revoke` command line option to gpg.

**Comment by edunham** [comment]
@brson To address the initial issue, I now have a revocation key and a backup of it. How would you like it to be distributed to consider this particular issue resolved?  

In the longer term, I'm looking at techniques we can use to more securely share use of the signing key (possibly requiring consensus from a quorum of team members to sign a release), but those are relatively low-priority compared to some of the other infrastructure problems.

**Comment by brson** [comment]
@edunham If you send it to @alexcrichton and I we can close this.

**Comment by edunham** [comment]
TODO: Encrypt & send revocation certs to Brian and Alex, then close this.

**Comment by Mark-Simulacrum** [comment]
@edunham Did you have a chance to send out revocation certs?

**Comment by edunham** [comment]
They are now in a 1password vault to which @aturon, @alexcrichton, and @brson have access. Admins of the team within 1password have permission to add others as they see fit.
