### ISSUE TITLE
Remove build date from --version

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#25812]
I added this some months ago because I thought it would help stem confusion about the reported commit date when it happens to be a few days behind the release artifacts. I no longer think this is a great idea for two reasons:

1) This date is not guaranteed to be the same across platforms. There have been occasions when the builds were spread across multiple days. Because these strings are not guaranteed to be the same one can't compare the output of two `rustc --version` invocations to check for equivalence, which is something I have wanted to do (I think one of my tools has to frob this string to eliminate the build date). Fixing this would require more complexity in the buildbot config than I'm comfortable with atm.

2) The commit date for nightlies should never actually be more than 1-2 days behind the distribution date since the head commit is always a merge commit. The original motivation for adding the build date may not have been very strong.

**Comment by brson** [comment]
In some since this is a stable breaking change since tools do parse the output of `--version`. I think we can get away with it though. cc @alexcrichton

**Comment by alexcrichton** [comment]
Yeah I agree with the rationale here, and I also agree that I think we can get away with it.

**Comment by nrc** [comment]
We should be advertising these changes more widely - anything that could break anything should be at least posed on internals and give some notice that things will change. I agree with the change here, but it would be nice to update my scripts in advance rather than after a few days of them being broken.

**Comment by DanielKeep** [comment]
Well great, now I have to get the build date some other way for my `rustup.ps1` script.

I actually did notice that the reported build date and the `Last-Modified` timestamp on the downloads were out a bit, so I was fuzzing them.  I suppose I can just grab the timestamp from the compiler executable itself.

Ah well. :)
