### ISSUE TITLE
internal compiler error: no type for expr in fcx

### ISSUE THREAD

**Issue by robitex** [rust-lang/rust#25831]
Ops, I accidentally inverted the position of type in function declaration and I get a compiler internal error.

    fn inc_vec(&mut v: Vec<u8>) {// error of type position
    fn inc_vec(v: &mut Vec<u8>) {// correct syntax

I'm not sure if this error was just reported here.
I tried this code:

    fn main() {
	    groups(5)
    }

    fn groups(n: usize) {
        let mut v: Vec<u8> = vec![0; n];
        
        for w in 1..256 {
            inc_vec(&mut v);
            println!("{} {} {} {} {} -- {}", v[0], v[1], v[2], v[3], v[4], w);
        }
    }

    fn inc_vec(&mut v: Vec<u8>) {// error of type position
        let mut carry = false;
        let n = v.len();
        
        if v[n-1] == (n-2) as u8 {
            v[n-1] = 0;
            carry = true;
        } else {
            v[n-1] += 1;
        }
        let mut i = n-2;
        while carry {
            if v[i] == (n-2) as u8 {
                v[i] = 0;
                i -= 1;
            } else {
                v[i] += 1;
                carry = false;
            }
        }
    }

I expected to see this happen: <explanation>

Instead, this happened: <explanation>

## Meta

`rustc --version --verbose`:
rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14)
binary: rustc
commit-hash: a59de37e99060162a2674e3ff45409ac73595c0e
commit-date: 2015-05-13
build-date: 2015-05-14
host: x86_64-unknown-linux-gnu
release: 1.0.0

Backtrace:
$ RUST_BACKTRACE=1 rustc 03-test-group.rs
03-test-group.rs:13:17: 13:23 error: mismatched types:
 expected `collections::vec::Vec<u8>`,
    found `&mut collections::vec::Vec<u8>`
(expected struct `collections::vec::Vec`,
    found &-ptr) [E0308]
03-test-group.rs:13         inc_vec(&mut v);
                                    ^~~~~~
03-test-group.rs:18:12: 18:18 error: mismatched types:
 expected `collections::vec::Vec<u8>`,
    found `&mut _`
(expected struct `collections::vec::Vec`,
    found &-ptr) [E0308]
03-test-group.rs:18 fn inc_vec(&mut v: Vec<u8>) {// error of type position
                               ^~~~~~
03-test-group.rs:20:13: 20:20 error: the type of this value must be known in this context
03-test-group.rs:20     let n = v.len();
                                ^~~~~~~
error: internal compiler error: no type for expr in fcx 0x7f4fb4feeff8
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:209

stack backtrace:
   1:     0x7f4fbc2fb449 - sys::backtrace::write::hbc46dc0cfb3b9537d4r
   2:     0x7f4fbc303156 - panicking::on_panic::h74d3c14d86c58ac8jrw
   3:     0x7f4fbc2c6462 - rt::unwind::begin_unwind_inner::h382cea404b11eb00t6v
   4:     0x7f4fb98913fd - rt::unwind::begin_unwind::h6365792021826883910
   5:     0x7f4fb9891abb - diagnostic::Handler::bug::h8da0df7c5604a97agwB
   6:     0x7f4fba26467b - session::Session::bug::h415dd0bf24016cc06Dq
   7:     0x7f4fbb0ac212 - check::FnCtxt<'a, 'tcx>::expr_ty::h0b20f2a038bc7a0c70o
   8:     0x7f4fbb0c1427 - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_expr::h419b8916d070b338bdc
   9:     0x7f4fbb0c1830 - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_expr::h419b8916d070b338bdc
  10:     0x7f4fbb0c1966 - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_expr::h419b8916d070b338bdc
  11:     0x7f4fbb0c19ad - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_expr::h419b8916d070b338bdc
  12:     0x7f4fbb1499cb - check::check_bare_fn::h1ca89f422d965ecetwn
  13:     0x7f4fbb1476f2 - check::CheckItemBodiesVisitor<'a, 'tcx>.Visitor<'tcx>::visit_item::h29ccc99d00d684a7wtn
  14:     0x7f4fbb20b69a - check_crate::closure.38028
  15:     0x7f4fbb206a30 - check_crate::h22dcd95e17a2d96dXcC
  16:     0x7f4fbc83fcc8 - driver::phase_3_run_analysis_passes::h43926ceca86caa9fnGa
  17:     0x7f4fbc820dc5 - driver::compile_input::hb78754f2f33c01efQba
  18:     0x7f4fbc8e24d1 - run_compiler::h258d36d5501c1cdfz4b
  19:     0x7f4fbc8e0122 - boxed::F.FnBox<A>::call_box::h7239693171334256553
  20:     0x7f4fbc8df659 - rt::unwind::try::try_fn::h14329119008520845439
  21:     0x7f4fbc375ac8 - rust_try_inner
  22:     0x7f4fbc375ab5 - rust_try
  23:     0x7f4fbc8df908 - boxed::F.FnBox<A>::call_box::h17332056298259451807
  24:     0x7f4fbc302041 - sys::thread::create::thread_start::h490278b5c3c0b49faqv
  25:     0x7f4fb6b84181 - start_thread
  26:     0x7f4fbbf4c47c - __clone
  27:                0x0 - <unknown>

Thank you.
R.

**Comment by arielb1** [comment]
Code does not crash in beta or nightly.

**Comment by alexcrichton** [comment]
Confirmed fixed on nightly/beta, thanks for the report though!
