### ISSUE TITLE
Why does configure require an old python?

### ISSUE THREAD

**Issue by bcxorg** [rust-lang/rust#25847]
configure: error: Found Python 3.1.2, but LLVM requires Python 2.4-2.7

On my solaris box I have python 3.1.2 and that is the only python I ever installed. Does this mean I will have to install an old python just to build rust?

**Comment by steveklabnik** [comment]
We just introduced a patch to help with python3, I thought....

**Comment by alexcrichton** [comment]
Yes LLVM requires an older Python for its build system, and I don't think that's changed recently, so we'd have to fix that upstream before we can fix it ourselves unfortunately.
