### ISSUE TITLE
BinaryHeap is not exception safe

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#25842]
BinaryHeap is using `zeroed()` and may not be exception safe. I.e. it is in an inconsistent state after being recovered after panic. See issue #25662 and others.

Relevant code is [BinaryHeap::sift_up, sift_down_range](https://github.com/rust-lang/rust/blob/47f9e528f13403f48dc0521f360055430da6d538/src/libcollections/binary_heap.rs#L485-L527)

cc @cmr

**Comment by bluss** [comment]
My immediate ideas are one of

- Use PPYP and set vector length to zero temporarily. Panicing in comparison functions will leak all elements in the heap 
- Use more swaps

**Comment by bluss** [comment]
@Gankro's got the idea: https://botbot.me/mozilla/rust-internals/2015-03-24/?msg=34945483&page=6

**Comment by Gankro** [comment]
Long ago I suggested two other strategies:

* A two-pass phase where you do all comparisons first, then once you've found the Final Destination you actually do the swaps (which requires no untrusted code to run).
* A panic guard which on drop puts the "working" element back in the "uninit" location in the array

**Comment by alexcrichton** [comment]
triage: I-nominated, T-libs

**Comment by bluss** [comment]
I'm trying gankro's panic guard idea.
