### ISSUE TITLE
./configure fails for Solairs

### ISSUE THREAD

**Issue by bcxorg** [rust-lang/rust#25846]
bcx@sf5:rust/src[345] ./configure
configure: looking for configure programs
configure: found program cmp
configure: found program mkdir
configure: found program printf
configure: found program cut
configure: found program head
configure: found program grep
configure: found program xargs
configure: found program cp
configure: found program find
configure: found program uname
configure: found program date
configure: found program tr
configure: found program sed
configure: found program file
configure: found program make
configure: inspecting environment
configure: error: unknown OS type: SunOS
bcx@sf5:rust/src[346]

**Comment by sanxiyn** [comment]
cf. #21000.

**Comment by steveklabnik** [comment]
Yes, closing in favor of that issue.
