### ISSUE TITLE
mention the possibility of using enum constructors as functions in expressions

### ISSUE THREAD

**Issue by nliberg** [rust-lang/rust#25850]
Neither the nightly Rust reference nor the book seem to mention the fact that one can use enum constructors in a function like way inside expressions, eg. `my_iterator.map(Option::Some)`.

(unless I'm mistaken and it's there somewhere, but I didn't find it)

**Comment by steveklabnik** [comment]
It's maybe obliquely mentioned at best.

**Comment by shepmaster** [comment]
IMO, this is two parts:

1. stating that enum constructors *are* functions.
2. stating that functions can be used where `Fn*` traits are.

I don't know how much you need to go into every permutation of every feature in Rust ^_^
