### ISSUE TITLE
Mutable Static docs (owned pointers / sync)

### ISSUE THREAD

**Issue by mitaa** [rust-lang/rust#25851]
```rust
static mut FOO: Option<Box<usize>> = None;
//<anon>:1:38: 1:42 error: mutable statics are not allowed to have owned pointers
//<anon>:1 static mut FOO: Option<Box<usize>> = None;
                                                ^~~~
```

I am not sure why this is forbidden, but it is certainly undocumented.

Also the TRPL says `Furthermore, any type stored in a static must be Sync.` but does not mention that this is not true for static mut's.

**Comment by steveklabnik** [comment]
whoah, we still have 'owned pointers' in an error message?

**Comment by nham** [comment]
@steveklabnik I'm planning on tackling this by adding an error code and an explanation. What do you think the error message should be instead? `mutable statics are not allowed to have boxes` ?

**Comment by steveklabnik** [comment]
Yes, thanks!

**Comment by steveklabnik** [comment]
This error now says 'hello.rs:1:38: 1:42 error: mutable statics are not allowed to have boxes [E0397]' on nightly

**Comment by nham** [comment]
Yes, however the "explanation" is still lacking I think. It just says

 > It is not allowed for a mutable static to allocate or have destructors. For
example

Not really an explanation ;) Also, [RFC 246](https://github.com/rust-lang/rfcs/blob/master/text/0246-const-vs-static.md), which introduced this error, doesn't discuss this topic from what I read, so I'm not exactly sure why this is disallowed.
