### ISSUE TITLE
Incorrect unreachable pattern analysis

### ISSUE THREAD

**Issue by brianquinlan** [rust-lang/rust#25890]
```
fn printmap(grid : &[[char; 7]; 7], path: &Vec<Position>) -> [[char; 7]; 7] {
	let mut m = grid.clone();
	let last_path_index = path.len() - 1;
	for (i, p) in path.iter().enumerate() {
		m[p.y][p.x] = match i {
			0 => '@',
			last_path_index => 'X',
			_ => '.',
		};
	}
	m
}
```
src/lib.rs:183:4: 183:5 error: unreachable pattern [E0001]
src/lib.rs:183 			_ => '.',
               			^
src/lib.rs:183:4: 183:5 help: pass `--explain E0001` to see a detailed explanation
error: aborting due to previous error

**Comment by jdm** [comment]
The compiler is actually correct here, and the `last_path_index => 'X'` isn't doing what it looks like. Patterns need to be constant values; the equivalent you're looking for is `_ if i == last_path_index => 'X'`. Right now all it means is "bind the name last_path_index to any value not matched by previous arms", which means the `_` arm will never match.

**Comment by brianquinlan** [comment]
Thanks for the explanation!
