### ISSUE TITLE
Rustdoc: No mention of copy trait for primitive types

### ISSUE THREAD

**Issue by azerupi** [rust-lang/rust#25893]
As a new rust user I have struggled with a little problem: http://stackoverflow.com/questions/30540419/rust-ownership-copy-clone-trait

The ownership and borrowing rules are well explained in the docs **but** the copy trait and the types that implement them are not! 

In the doc http://doc.rust-lang.org/std/marker/trait.Copy.html primitive types are not listed as copy trait implementors. They should at least be mentioned there.

It would be good to also add  a little more info here: http://doc.rust-lang.org/book/ownership.html#copy-types Maybe give some examples like in my question on stackoverflow:

> The following two snippets of code only compile because `i32` and `bool` types both implement the copy trait. Meaning that the ownership is **not** moved by default but copied instead
> 
> ``` rust
> fn main() {
>     let a = 5;
> 
>     let _y = double(a);
>     println!("{}", a);
> }
> 
> fn double(x: i32) -> i32 {
>     x * 2
> }
> ```
> 
> ``` rust
> fn main() {
>     let a = true;
> 
>     let _y = change_truth(a);
>     println!("{}", a);
> }
> 
> fn change_truth(x: bool) -> bool {
>     !x
> }
> ```

This is **very important** since it is an **exception to the most important rule** of the language

Let me know if I have to make a pull request with a "change proposal" :)

**Comment by steveklabnik** [comment]
Triage: no real change.

**Comment by shepmaster** [comment]
This [continues to confuse newcomers](http://stackoverflow.com/q/41413336/155423).

**Comment by steveklabnik** [comment]
@mbrubeck points out that `str` is not `Copy` https://play.rust-lang.org/?gist=a7e12362ef93f657e7f23f411637e879&version=stable

**Comment by scottmcm** [comment]
This just confused me for the stable-soon never type, where I think it's likely that even experienced rustaceans would be wondering about implemented traits.

**Comment by vext01** [comment]
Is it me, or do the docs still not mention the `Copy` trait in (e.g.) `usize` and `ptr`?
