### ISSUE TITLE
Poor error message when forgetting the bang in a macro.

### ISSUE THREAD

**Issue by Ms2ger** [rust-lang/rust#25910]
```rust
fn main() {
    for i in 1..10 {
        println("{}", i);
    }
}
```
yields (on playpen):
```
<anon>:3:9: 3:16 error: unresolved name `println`. Did you mean `iter`?
<anon>:3         println("{}", i);
                 ^~~~~~~
error: aborting due to previous error
playpen: application terminated with error code 101
```
which is not helpful.

**Comment by nagisa** [comment]
This is a bit towards `E-hard`, because macro expansion and name resolution happen in two different places and we do not retain much macro-related information by the time resolve happens. That is, you’d need to reconstruct a list of all macro names from scratch.

**Comment by sfackler** [comment]
Might be worth special casing `println` though, since it's so common. (Maybe `try` and `vec` as well?)

**Comment by Manishearth** [comment]
#5780

**Comment by Manishearth** [comment]
https://github.com/rust-lang/rust/pull/29968
