### ISSUE TITLE
Should link to improved long-form error for nonlexical borrows

### ISSUE THREAD

**Issue by pythonesque** [rust-lang/rust#25913]
Our current message, "help: consider using a `let` binding to increase its lifetime," doesn't have a long-form version indicating that there are future plans for it to be fixed (e.g. by linking the non-lexical borrows issue, https://github.com/rust-lang/rfcs/issues/811).  I believe this would be warranted given the frequency with which people encounter this error and the fact that the given solution is correct often enough to warrant that message in the first place.

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by Mark-Simulacrum** [comment]
I think that this wouldn't be all that helpful, and might almost be discouraging to users of the language -- the feature isn't gated behind some flag they could enable yet -- and largely I feel like it would just add to the frustration with the compiler typically experienced by people looking at lifetime errors. As such, I'm going to close.
