### ISSUE TITLE
docs: One of lifetime elision examples says "output lifetime is unclear" but not "ILLEGAL"

### ISSUE THREAD

**Issue by dequis** [rust-lang/rust#25915]
http://doc.rust-lang.org/book/lifetimes.html#examples

```
fn frob(s: &str, t: &str) -> &str; // ILLEGAL, two inputs
fn frob<'a, 'b>(s: &'a str, t: &'b str) -> &str; // Expanded: Output lifetime is unclear
```

All other examples say `ILLEGAL` clearly, and when i read it, it seemed like the expanded version was legal, even though the output lifetime is unclear, which sounded a lot like the kind of "undefined behavior" rust wants to avoid, and that made me feel very uncomfortable.

If this is actually illegal, it would be nice to say it explicitly.

**Comment by nagisa** [comment]
I’d actually replace “unclear” with “ambiguous”.
