### ISSUE TITLE
Document that .iter() has an element type of &T

### ISSUE THREAD

**Issue by Wilfred** [rust-lang/rust#25928]
The [docs for Vec::iter](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.iter) show the following type:

``` rust
fn iter(&self) -> Iter<T>
```

As a result, I was puzzled that the following doesn't work:

``` rust
let bar: Vec<&str> = vec!["a", "b", "c", "b"].iter().collect();
```

It turns out that that `Iter` implements an iterator with element type &T. On the [Iter docs page](https://doc.rust-lang.org/std/slice/struct.Iter.html) we see `type Item = &'a T` but it's easy to overlook.

I think it would be worth adding a line to `Vec::iter`'s documentation to say:

> Iterator element type is &T.

This is the approach taken in itertools docs ([example](http://bluss.github.io/rust-itertools/doc/itertools/trait.Itertools.html#method.tee)) and I think it helps significantly.

**Comment by steveklabnik** [comment]
I'm generally not a fan, as text is hard to track with changes. I'd rather see `rustdoc` grow support for something like this if if's truly useful.  I'm not sure how common this misunderstanding is.

**Comment by bluss** [comment]
I'm a fan of this. I think the iterator element type is only obvious when you already know rust quite well, and it answers one of the single most important questions missing from the function signature.

**Comment by Gankro** [comment]
Ideally all these interfaces should just say `-> impl Iterator<&T>` or
whatever that future syntax is.

**Comment by bluss** [comment]
Yes but that's far future right now.

I'm also wondering what we are going to do about multiple traits. I mean, `-> impl Iterator<&T>` doesn't describe all we need from it, we need something like `-> impl DoubleEndedIterator<Item=&T> + ExactSizeIterator + Clone`.

**Comment by thenewwazoo** [comment]
Raising this from the dead to say that this just bit me (e.g. "why do I have to dereference _twice_ in `.filter`?)

**Comment by QuietMisdreavus** [comment]
I've started https://github.com/rust-lang/rust/pull/45039 to work on this.
