### ISSUE TITLE
[rustbook] Can't include custom anchors to headings

### ISSUE THREAD

**Issue by mkpankov** [rust-lang/rust#25931]
I tried to include anchor with custom key to heading with `### <a name="head1234"></a>Heading!`, and it got stripped.

We need such functionality for proper linking in translations of TRPL: currently we have, for example, a link `https://doc.rust-lang.org/stable/book/glossary.html#abstract-syntax-tree` in `https://doc.rust-lang.org/stable/book/macros.html`, and heading `# Abstract Syntax Tree` is translated to `# Абстрактное синтаксическое дерево (Дерево абстрактного синтаксического анализа)`, so the proper anchor link to that would be urlencoded `https://doc.rust-lang.org/stable/book//glossary.html#%D0%90%D0%B1%D1%81%D1%82%D1%80%D0%B0%D0%BA%D1%82%D0%BD%D0%BE%D0%B5-%D1%81%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5-%D0%B4%D0%B5%D1%80%D0%B5%D0%B2%D0%BE-%28%D0%94%D0%B5%D1%80%D0%B5%D0%B2%D0%BE-%D0%B0%D0%B1%D1%81%D1%82%D1%80%D0%B0%D0%BA%D1%82%D0%BD%D0%BE%D0%B3%D0%BE-%D1%81%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B3%D0%BE-%D0%B0%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%29)`, which is unbearable :)

So, I'd really like to refer be able to do `# <a name="abstract-syntax-tree"></a> Абстрактное синтаксическое дерево` and have it to be translated into working link.

**Comment by killercup** [comment]
@mkpankov Have you tried an empty div above the headline instead?

I'm pretty sure rustbook is based on rustdoc which uses https://github.com/hoedown/hoedown for rendering Markdown. You can see some inline HTML is supported.

(Ideally, someone would extend hoedown to parse something like the [header attributes](http://pandoc.org/README.html#header-identifiers-in-html-latex-and-context) from Pandoc or Markdown Extra.)

**Comment by mkpankov** [comment]
@killercup thanks, discovered simple 

```
<a name="foo"></a>
# Heading
```

does work.
