### ISSUE TITLE
Seems like the compiler/optimizer is doing something weird here

### ISSUE THREAD

**Issue by ericsink** [rust-lang/rust#25942]
Nutshell summary:  I made some code changes that caused a performance degradation that was very surprising.  Possibly relevant is that along with the slowdown, valgrind --tool=callgrind started showing time spent in arena_avail_remove and arena_avail_insert.

The code to reproduce this is in the rs directory of this repo:

https://github.com/ericsink/LSM

The faster version (let's call it C) is commit 630968f0536b079d2f614a7a596c61cc8105b290, and that commit message has some additional detail.

The slower version (let's call it B) is its immediate parent, 78f75009defc98fd8745604a29bd1e7e2cea443f.

The starting point (let's call it A) for this series of changes is a014746795b82b682460d1f5eed1f12cd9a8e479.

So, starting at A, I made a bunch of changes, all of which were designed to make the code faster by using more references and less memory allocation.  Arriving at B, I discovered that actually, everything was slower.  Commit C is an undo of most of those changes to get the perf back.

There may not be an actual "bug" here, but I found the result quite unintuitive.

**Comment by ericsink** [comment]
Forgot this part:

rustc 1.2.0-nightly (78c4d5387 2015-05-30) (built 2015-05-30)
binary: rustc
commit-hash: 78c4d53871b3d75b4de5f96cb1f9cdc11648ccc6
commit-date: 2015-05-30
build-date: 2015-05-30
host: x86_64-apple-darwin
release: 1.2.0-nightly

**Comment by ericsink** [comment]
My current theory is that the "code I thought would be faster" is actually doing more heap allocation than I thought.  Still digging.

I intend to keep this moving forward toward one of two outcomes:  This issue should either turn into an actionable bug report (smaller repro case, less conjecture, etc) or it should be closed as invalid with a summary of what was really happening.

**Comment by steveklabnik** [comment]
> This issue should either turn into an actionable bug report (smaller repro case, less conjecture, etc) or it should be closed as invalid with a summary of what was really happening.

@ericsink did you ever figure this out? It looks like maybe the directory got renamed or something; I didn't see it in the repo today.

**Comment by ericsink** [comment]
Hmm, sorry I left this dangling.

No, I never got this to become something addressable by the Rust team.  

I may have realized that I was just doing something dumb, but I haven't worked on that side-project in a while, and I honestly don't remember for sure.

So, I'm going to close this.  Thanks.

**Comment by steveklabnik** [comment]
No worries! Thanks for the update.
