### ISSUE TITLE
rustc stackoverflow

### ISSUE THREAD

**Issue by yshui** [rust-lang/rust#25954]
Offending program: http://is.gd/uNH2bk

**Comment by bluss** [comment]
Reduced, but only a little

```rust
use std::cell::{Cell, RefCell};
struct A<T: Fn()> {
    x: RefCell<Option<T>>,
    b: Cell<i32>,
}

fn main() {
    let mut p = A{x: RefCell::new(None), b: Cell::new(4i32)};
    let q = || p.b.set(5i32);
    *(p.x.borrow_mut()) = Some(q);
}
```

**Comment by mitaa** [comment]
Further reduced:

```rust
use std::mem;

struct B<F: Fn()->()> (F);

fn main() {
    let mut p = B(std::mem::zeroed());
    p.0 = ||{p.0;} ;
}
```

**Comment by bluss** [comment]
:blush: nice

**Comment by bluss** [comment]
The recursion is inside check::regionck::type_must_outlive

**Comment by nikomatsakis** [comment]
I'm curious what is the origin of this example?

**Comment by nikomatsakis** [comment]
So the core problem is that closure types can contain themselves. In PR https://github.com/rust-lang/rust/pull/27087, I changed how closures are desugared, preventing cyclic closures and thus sidestepping this problem.
