### ISSUE TITLE
Documentation search no longer works in Chrome Canary when accessing local documentation

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/rust#25953]
The console reports this error:

```
Uncaught SecurityError: Failed to execute 'pushState' on 'History': A history state object with URL 'file:///Users/me/Projects/rust/doc/std/index.html?search=hello' cannot be created in a document with origin 'null'.search @ main.js:578
```

This is [the line of JS](https://github.com/rust-lang/rust/blob/613e57b448c88591b6076a8cea9799f1f3876687/src/librustdoc/html/static/main.js#L578) in question.

I recognize that I'm using a beta browser version, and that the team may not wish to support these browsers. However, it's easy for me to report it, just in case it becomes a problem with the next released version!

### Meta

* Chrome Version 45.0.2454.85 (64-bit)
* OS X
* `rustc 1.2.0`

**Comment by ujh** [comment]
It's broken for me, too. I'm using Chrome 45.0.2454.85 (not Chrome canary). Also Mac OSX and `rustc 1.4.0-nightly (fd230ff12 2015-09-13)`.
