### ISSUE TITLE
Warn when code contains cfg(ndebug)

### ISSUE THREAD

**Issue by mbrubeck** [rust-lang/rust#25950]
The `ndebug` cfg directive was replaced by `debug_assertions`, but old code that still uses `cfg(ndebug)` or `cfg(not(ndebug))` will still compile without warnings, and silently do the wrong thing in release builds.  A compiler warning would be helpful for catching this problem in older Rust projects.  cc @Manishearth

**Comment by Manishearth** [comment]
@alexcrichton Do we want this, or should this be in an external crate?

(IMO at least deprecation lints should be in rustc)

**Comment by alexcrichton** [comment]
I would not personally want this, projects may want to attach their own meaning to ndebug orthogonal of the compiler itself.

**Comment by bltavares** [comment]
Triaging: Should this be closed?

**Comment by steveklabnik** [comment]
I would vote yes. @mbrubeck what do you think? Has enough time passed that this is not going to be useful anymore?

**Comment by mbrubeck** [comment]
Yes, I think so.
