### ISSUE TITLE
TRPL: link error

### ISSUE THREAD

**Issue by FuGangqiang** [rust-lang/rust#25964]
in the page [compiler-plugins](https://doc.rust-lang.org/nightly/book/compiler-plugins.html),there are many links return 404
- [rustc::plugin](https://doc.rust-lang.org/nightly/rustc/plugin/) 
- [args method](https://doc.rust-lang.org/nightly/rustc/plugin/registry/struct.Registry.html#method.args)
- [syntax trees](https://doc.rust-lang.org/nightly/syntax/ast/)
- [Registry::register_syntax_extension](https://doc.rust-lang.org/nightly/rustc/plugin/registry/struct.Registry.html#method.register_syntax_extension)
- [syntax::parse](https://doc.rust-lang.org/nightly/syntax/parse/)
- [Spans](https://doc.rust-lang.org/nightly/syntax/codemap/struct.Span.html)
- [Spanned](https://doc.rust-lang.org/nightly/syntax/codemap/struct.Spanned.html)
- [ExtCtxt::span_fatal](https://doc.rust-lang.org/nightly/syntax/ext/base/struct.ExtCtxt.html#method.span_fatal)
- ...

**Comment by TimNN** [comment]
Ha, I just came here to report the same problem. For the moment you can find all of them if you remove the 'nightly' part of the url. (Which also means that the links in the stable version of 'compiler-plugins' work)

**Comment by steveklabnik** [comment]
Ah yes, we hid these internal docs, but plugins work with internals.

**Comment by TimNN** [comment]
Another problem is that the current `rustc` docs use the wrong search index: searching gives only results from the main rust documentation.

eg.: searching for `register` finds only `std::rt::unwind::register` and `std::collections::bit_set::SetIter` but none of the `Registry::register_*` methods.

**Comment by steveklabnik** [comment]
That's also intended, basically.

**Comment by TimNN** [comment]
I expected as much, but this is really inconvenient. It would be awesome if these docs would be accessible (and searchable) somewhere. Would it maybe be possible to build them (searchable) only for the nightlies, which already allow access to unstable parts of the language?

**Comment by steveklabnik** [comment]
In the last few days, we have had brief discussion about an /internals
which would mirror /nightly but include these docs.

**Comment by marjakm** [comment]
These links are now broken in all versions of the book
https://doc.rust-lang.org/book/compiler-plugins.html
https://doc.rust-lang.org/stable/book/compiler-plugins.html
https://doc.rust-lang.org/beta/book/compiler-plugins.html
https://doc.rust-lang.org/nightly/book/compiler-plugins.html

**Comment by TimNN** [comment]
For those finding this issue and looking for the docs, they are currently made available by @Manishearth: http://manishearth.github.io/rust-internals-docs/rustc/

**Comment by steveklabnik** [comment]
Triage: no change, still.

**Comment by steveklabnik** [comment]
We have now moved this to https://doc.rust-lang.org/nightly/unstable-book/plugin.html and removed all the links. They're so unstable they were never really gonna work anyway. I'm going to consider this closed. Thanks!
