### ISSUE TITLE
Don't panic when stdout doesn't exist

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#25977]
Tracking issue for https://github.com/rust-lang/rfcs/pull/1014

**Comment by remram44** [comment]
See also #14505: *compiler* crashes on lost stdout (will probably be fixed when this is fixed)

**Comment by remram44** [comment]
It seems that, while closing stdout descriptor and calling print!() won't panic anymore, writing to a broken pipe still panics:
```
thread '<main>' panicked at 'failed printing to stdout: Broken pipe (os error 32)', ../src/libstd/io/stdio.rs:585
```

It is not clear from the RFC (https://github.com/rust-lang/rfcs/blob/master/text/1014-stdout-existential-crisis.md) whether this was intended, but it might warrant clarification.

**Comment by alexcrichton** [comment]
There was [a little discussion](https://github.com/rust-lang/rfcs/pull/1014#discussion_r27155309) on the RFC (in the collapsed comments), but it may not have made its way into the text.

**Comment by remram44** [comment]
It seems that the behavior of stdout() (and even panic!()) was discussed at length but not print!(). It seems weird to have print!() work fine in daemons or after closing stdout, but not when the pipe gets closed... (looking into it, `|head` works (eg output gets silently discarded once head is done) and `|false` panics...)
