### ISSUE TITLE
Implement Extend<&T> where T: Copy for collections

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#25976]
Tracking issue for https://github.com/rust-lang/rfcs/pull/839

**Comment by Gankro** [comment]
Willing to mentor.

**Comment by wesleywiser** [comment]
@Gankro I'd like to take a shot at it if that's ok.

**Comment by jooert** [comment]
@wesleywiser Ah, sorry, I've just finished working on it, will send a pull request now.

**Comment by wesleywiser** [comment]
@jooert No problem!
