### ISSUE TITLE
Failed inference involving Send and Sync trait bounds

### ISSUE THREAD

**Issue by Veedrac** [rust-lang/rust#25982]
You can do

```
let x: Box<Error> = Box::from("☺");

// or
let x: Box<Error + Send + Sync> = From::from("☺");
let y: Box<Error> = x;
```

Is there any hope of ever being able to do this?

```
let x: Box<Error> = From::from("☹");
```

This currently errors with

```
<anon>:4:25: 4:35 error: the trait `std::error::Error` is not implemented for the type `&str` [E0277]
<anon>:4     let x: Box<Error> = From::from("☹");
                                 ^~~~~~~~~~
```

The inability to do this inference automatically and the resulting error are confusing.

[FIrst asked here.](http://www.reddit.com/r/rust/comments/37cryf/hey_new_rust_users_got_an_easy_question_ask_it/crqq2oo)

**Comment by Veedrac** [comment]
I've run into this again from the argument side with implicit casts for `fn(A) -> B {name}` types:

    trait Trait {
        fn method(&self) { println!("doing"); }
    }
    
    impl Trait for fn() {}
    
    fn function() {}
    
    fn main() {
        // This doesn't work
        function.method();

        // This does
        let f: fn() = function;
        f.method();
    }

**Comment by jonas-schievink** [comment]
@Veedrac that seems like a different issue (I think only deref coercion is applied to the method receiver, you need an `fn` pointer reification)

**Comment by Veedrac** [comment]
Seems to be fixed!
