### ISSUE TITLE
split() should document the behavior around adjacent separators, particularly at the start of the string

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#25986]
It's not clear to me if this is the expected behavior or not, but [this program](http://is.gd/mw32K6):

```rust
fn main() {
    let x = "    a  b c".to_string();
    let d: Vec<_> = x.split(' ').collect();
    println!("{:?}", d);
}
```

yields:

```
["", "", "", "", "a", "", "b", "c"]
```

whereas I expected:

```
["a","b","c"]
```

If the current behavior *is* expected, it should be more clearly documented, at minimum.

cc @Kimundi

**Comment by nikomatsakis** [comment]
That said, it does seem inconsistent to me? For example, four leading spaces yields four empty entries, but two intermediate spaces yield one empty entry, and one intermediate space yields no empty entries.

**Comment by Veedrac** [comment]
There are two reasonable behaviours I see. One is to split around padding, to get `["a", "b", "c"]`. The other is to split around delimiters, eg. `",12,,34".split(',') → ["", "12", "", "34"]`. This would keep the ends of the string, even if empty.

**Comment by bluss** [comment]
It is certainly expected by the implementors, this is the way it has been since introduction of .split() I believe. Since it's stable, I guess it's a documentation issue

**Comment by bluss** [comment]
FWIW, python does the same thing

```python
>>> "    a  b c".split(' ')
['', '', '', '', 'a', '', 'b', 'c']
```

**Comment by nikomatsakis** [comment]
@bluss yes, ok, that makes sense (I did not, it's true, consider the "empty string" at the beginning.)

I don't particularly like this behavior -- I've always found it annoying in Python too :) -- but yes I agree it's a doc issue, not a bug.

**Comment by Kimundi** [comment]
@bluss basically said all I'd say already. So yeah, I guess the docs could be improved a bit?

**Comment by nagisa** [comment]
> That said, it does seem inconsistent to me? For example, four leading spaces yields four empty entries, but two intermediate spaces yield one empty entry, and one intermediate space yields no empty entries. 

.split(x).connect(x) should be an identity function, which is how it is consistent.

**Comment by Veedrac** [comment]
@nagisa This doesn't seem to actually be the case. The number of leading spaces seems to match the number of empty entries. Eg.

    println!("{:?}", " a  b c".to_owned().split(' ').collect::<Vec<_>>());
    #>>> ["", "a", "", "b", "c"]

As such, the requirement seems to hold.

**Comment by nagisa** [comment]
> @nagisa This doesn't seem to actually be the case.

I don’t understand what you’re trying to say here, because `split(x).connect(x)` is an identity function (well, yeah, you have to collect it in between, etc; but that’s not the point):

```
" a  b c" == " a  b c".to_owned().split(' ').collect::<Vec<_>>().connect(" ")
(20:39:06) playbot: (notice) true
```

**Comment by Veedrac** [comment]
Sorry, I thought by saying "should be" you were implying that it wasn't - I was pointing out that it is consistent. Nvm, we agree.
