### ISSUE TITLE
Pretty printing doesn't show struct members in IDE

### ISSUE THREAD

**Issue by vadimcn** [rust-lang/rust#25997]
When pretty printers are registered in GDB (gdb 7.8.1 from mingw-w64), and pretty printing over MI interface is enabled<sup>1</sup>, all structs are shown in IDE as `{...}` with no children.

For example,
```rust
struct Foo { a:u32, b:u32, c:u32}
let mystruct = Foo { a:1, b:2, c:3 };
```
Normal CLI works: `p mystruct` prints `$1 = Foo = {a = 1, b = 2, c = 3}`,

However, MI command: `-var-create - * "mystruct"` sends back `^done,name="var1",numchild="0",value="{...}",type="struct Foo",thread-id="1",dynamic="1",has_more="1"`
:disappointed:  

--
<sup>1</sup> I've added these lines to gdb_rust_pretty_printing.py, and loaded it via `source ...\gdb_rust_pretty_printing.py`:
```python
if __name__=="__main__":
    gdb.pretty_printers.insert(0, rust_pretty_printer_lookup_function)
    gdb.execute("interpreter-exec mi \"-enable-pretty-printing\"")
```

**Comment by vadimcn** [comment]
cc @michaelwoerister

**Comment by vadimcn** [comment]
Oh, nevermind, it's just that VisualStudio does not understand dynamic varobj's.
Too bad we can't create non-dynamic varobjs from pretty printer... :disappointed:

**Comment by dwjbosman** [comment]
I am facing the same problem. I am using Theia cppdebug extension. It uses rust-gdb in interpreter=mi mode. With debugging enabled I see that it runs MI commands:

`-var-create - * "mystruct" `

and sends back 

`^done,name="var1",numchild="0",value="{...}",type="struct Foo",thread-id="1",dynamic="1",has_more="1"`

As a consequence the GUI shows "{...}". How did you solve this? How can I get the details of a struct?
