### ISSUE TITLE
Rustdoc: "'?' for more options" in the search field is ambiguous

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rust#25996]
A placeholder text _in_ the search field hints:

> …, '?' for more options

so I've entered "?" _in the search field_ and ended up on this page:

https://doc.rust-lang.org/std/?search=%3F

Oops! I've realised that you've meant pressing <kbd>Shift+/</kbd> when text input _isn't focused_, but text input placeholder text is generally used as an example for the text input itself, so it confused me.

I suggest handling search for `?` as a special case and displaying the help text too.

And perhaps even better solution would be to automatically display a search syntax cheatsheet below the search input when the input is focused. Splunk search has something like this (they call it [search assistant](http://image.slidesharecdn.com/splunklivebeginnertrainingnyc-130503133959-phpapp01/95/splunk-live-beginner-training-nyc-17-638.jpg?cb=1367588588)).

**Comment by barosl** [comment]
FWIW, it also lists `S`, which should be pressed outside of the text field. I agree displaying a help when the field is focused would be great. Possibly only when the text field is empty (the user is about to start typing).

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by jyn514** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/39263
