### ISSUE TITLE
error: unstable feature

### ISSUE THREAD

**Issue by Jfromchina** [rust-lang/rust#25998]
I encountered the problem below, my version is Release1.0.0, is it the latest version? which one is stable Release?
$ rustc main.rs
main.rs:1:1: 1:25 error: unstable feature
main.rs:1 #![feature(collections)]
^~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the stable release channel
error: aborting due to previous error

$ rustc --version --verbose
rustc 1.0.0 (a59de37 2015-05-13) (built 2015-05-14)
binary: rustc
commit-hash: a59de37
commit-date: 2015-05-13
build-date: 2015-05-14
host: x86_64-unknown-linux-gnu
release: 1.0.0

**Comment by jdm** [comment]
Yes, the release versions are stable. Nightly versions are unstable.

**Comment by alexcrichton** [comment]
To add to what @jdm said, you can find nightlies on the [install page](http://rust-lang.org/install.html), but otherwise this is working as intended, so closing.
