### ISSUE TITLE
Rustdoc: Search help keybind `?` does nothing

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#26016]
Typing `?` in rustdoc doesn't do anything. Probably a keyboard layout issue. `S` works fine.

Platform: Firefox or Chromium, Linux x86-64.

Keyboard layout: Swedish.

My `?` is under `Shift`-`+`.

**Comment by Gankro** [comment]
It's working for me in Firefox on OSX, what're you seeing this in?

**Comment by bluss** [comment]
Updated. I think it's hardcoded to US keylayout or so.

**Comment by Gankro** [comment]
Yep: 

https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/static/main.js#L84-L85

```
        if (e.which === 191) { // question mark
            if (e.shiftKey && $('#help').hasClass('hidden')) {
```

**Comment by Gankro** [comment]
@bluss Can you pull up your browser's JS console (ctrl+shift+k on firefox, ctrl+shift+j on chromium in linux iirc) and paste in this code snippet:

```
document.addEventListener('keypress', function(e) { if (e.key === "?") { console.log("Yes!"); } });
```

click back on the page, type `?` and tell me if the console prints "Yes!" or not?

**Comment by bluss** [comment]
Sure, thanks for the steps. Firefox: It says "Yes!", chromium: Nothing happens.

**Comment by bluss** [comment]
My 5 minutes of experience with javascript tells me e.char or e.charCode should be preferred. In chrome, charCode gives `63` which is the ascii encoding of `?`.

**Comment by Gankro** [comment]
These are in an awesome limbo state of the old way being deprecated and the new way being unimplemented. We'll probably have to test a few ways and pray.

**Comment by Gankro** [comment]
Some data: https://gist.github.com/anonymous/f95c0f4526fbceb201b4

**Comment by Gankro** [comment]
Discussing it on IRC, it looks like e.key should indeed be preferred with `which` or `keyCode` used as a "legacy fallback". I'm a bit busy focusing on getting collections stuff fixed up. I'm willing to mentor anyone who wants to get a try at working on rustdoc stuff.

**Comment by klnusbaum** [comment]
I think I know a good way to do this. Looking at [this][1] it would appear you can actually function called `String.fromCharCode` to get the key that was pressed in string form and then compare on that. Let me give it a shot.


[1]: http://www.javascriptkit.com/javatutors/javascriptkey2.shtml

**Comment by klnusbaum** [comment]
Actually [this][1] looks even better.

[1]: http://stackoverflow.com/questions/1846599/how-to-find-out-what-character-key-is-pressed

**Comment by klnusbaum** [comment]
hmmm, I may have spoken too soon. Let me do some more digging.

**Comment by klnusbaum** [comment]
Is there an easy way to build the docs without compiling the whole rust project from source?

**Comment by Gankro** [comment]
If you're just fiddling with JS, you can just edit/replace the JS files in
the generated docs.

The command for making the docs is `make docs` but this necessarily builds
at least some of the compiler.

**Comment by azerupi** [comment]
I haven't read into details yet, but this page has some info: http://javascript.info/tutorial/keyboard-events

**Especially:**

> The only event which reliably provides the character is keypress.

```js
// event.type must be keypress
function getChar(event) {
  if (event.which == null) {
    return String.fromCharCode(event.keyCode) // IE
  } else if (event.which!=0 && event.charCode!=0) {
    return String.fromCharCode(event.which)   // the rest
  } else {
    return null // special key
  }
}
```

At the moment the docs use the `keyup` event

I will make some tests when I have time, unless someone beats me to it :)

**Comment by azerupi** [comment]
@bluss I made a pull request but it needs some testing, could you try http://www.mathieudavid.org/test/rustdoc/std/index.html and let me know if it works? It fixed the issue for me but I only tested it with an Azerty keyboard on Google Chrome.

**Comment by bluss** [comment]
Nice! Tested with Firefox & Chromium and it works well.

**Comment by azerupi** [comment]
Perfect :) Thank you for testing
