### ISSUE TITLE
LinkedList corrupted in .split_off()

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#26021]
User seppo0010 in #rust irc found this corruption and crasher bug in `LinkedList::split_off()`

Exists in rustc 1.0 and nightly

[(playpen link)](https://play.rust-lang.org/?gist=2cf6a275259d981183eb&version=nightly)

```rust
use std::collections::LinkedList;

fn main() {
    let mut v1 = LinkedList::new();
    v1.push_front(1u8);
    v1.push_front(1u8);
    v1.push_front(1u8);
    v1.push_front(1u8);
    let _ = v1.split_off(3);
    assert_eq!(v1.len(), 3);
    //assert_eq!(v2.len(), 1);

    println!("{}", v1.iter().len());
    println!("{}", v1.iter().collect::<Vec<_>>().len());
}
```

Corruption is visible when you let the split off vector drop at once.

It's too late for me to analyze this right now, but I suspect a backlink is not being updated correctly.

**Comment by Gankro** [comment]
Found it. Missing nulling of a ptr.
