### ISSUE TITLE
SOCK_SEQPACKET not defined in liblibc

### ISSUE THREAD

**Issue by agrover** [rust-lang/rust#26036]
Linux defines a SOCK_SEQPACKET socket type with value 5, in addition to SOCK_DGRAM and SOCK_STREAM. I went to go add it to liblibc/lib.rs but I wasn't quite sure which spot I should add it, so thought I'd better let someone else get it right :smile:

**Comment by alexcrichton** [comment]
Thanks for the report! Currently the liblibc library isn't striving to be a completely exhaustive set of bindings, so we generally aren't keeping tracking issues for pieces it doesn't yet contain. As a result I'm going to close this, but we of course accept any contributions to adding new constants and such! 

Unfortunately the organization is a bit of a mess right now, but if you find the areas where `SOCK_DGRAM` is defined that's where you'll want to put it. You'll just need to find the area which is under `#[cfg(target_os = "linux")]`
