### ISSUE TITLE
Type incorrectly inferred for negative integer that is inferred as an usize

### ISSUE THREAD

**Issue by pvginkel** [rust-lang/rust#26033]
The output of the following test case is `18446744073709551615`:

```rust
fn main() {
    let mut x = -1;
    
    for i in vec![1usize] {
        break;
        x = i;
    }
    
    println!("{}", x);
}
```

The problem is that `x` is inferred as being `usize`. However, the `-1` initial value cannot be hold in that type, so it overflows/gets transmuted into an `usize`.

My expectation is that this should result in a compilation error.

## Meta

rustc 1.1.0-beta (cd7d89af9 2015-05-16) (built 2015-05-16)
binary: rustc
commit-hash: cd7d89af9169885642d43597302af69f842bbd78
commit-date: 2015-05-16
build-date: 2015-05-16
host: x86_64-pc-windows-gnu
release: 1.1.0-beta

**Comment by nagisa** [comment]
Same thing as https://github.com/rust-lang/rust/issues/24676.

**Comment by alexcrichton** [comment]
Indeed, closing as a dupe.
