### ISSUE TITLE
Deprecated attribute should be inherited

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#26040]
We've cycled through a few different inheritance strategies for stability attributes, but with the move to release channels we've lost inheritance for the deprecated attribute. This appears not to be an intentional choice, and there are strong ergonomic reasons to use inheritance here.

We should alter the lint's computation so that deprecation is inherited. Should be pretty easy to do.

**Comment by aturon** [comment]
I'm happy to mentor if someone wants to work on this.

**Comment by aturon** [comment]
cc @Manishearth

**Comment by ericye16** [comment]
I'd like to tackle this, if still available. I think my starting point is src/librustc/middle/stability.rs, is that correct?

**Comment by Gankro** [comment]
Whoops, sorry @erickye16, I started working on this earlier this morning and have a WIP PR up.

(I'm not super confident in the design, though)

**Comment by Gankro** [comment]
In particular this change seems very... noisy. It might be worth investigating coalescing deprecated API usage errors.
