### ISSUE TITLE
"Dynamic Symbol Retrieval Error" using node.js mixed with rust dll file under windows

### ISSUE THREAD

**Issue by fuyingfuying** [rust-lang/rust#26053]
Hi，
I'm a new user of rust. I'm learning rust language recently. So firstly I read "The Rust Programming Language" eBook from its official website. In the meantime I want use nodejs libs to develop my app because there are no useful rust libs for web development. So I still use nodejs. But there are some heavy computation in my apps, So in these parts i want to use rust instead. fortunately, In the section 3.3(https://doc.rust-lang.org/stable/book/rust-inside-other-languages.html), they introduce the ffi module can support my idea. So I followed the introduce of section 3.3 to validate this method. However, running the example always generates the following message: 
![image](https://cloud.githubusercontent.com/assets/12774287/8019622/74d2ee42-0c8a-11e5-9516-f39925a14c7d.png)

My environment is windows 8.1 64bits. io.js x64 2.2.1, ffi 1.3.1, rust 1.0.0. my machine has installed vs 2013 update 4 community version, so the node-gyp works well and the ffi module has installed successfully. the rust example code is:

use std::thread;

fn process() {
let handles: Vec<> = (0..10).map(|| {
thread::spawn(|| {
let mut _x = 0;
for _ in (0..5000001) {
_x += 1
}
})
}).collect();

for h in handles {
    h.join().ok().expect("Could not join a thread!");
}
}

it is same with the The Rust Programming Language ebook. And the node.js code is same with the ebook:

var ffi = require('ffi');

var lib = ffi.Library('target/release/embed', {
'process': [ 'void', [] ]
});

lib.process();

console.log("done!");

The dll file generated by the rust source file is called "embed.dll". It is generated by the command "cargo build --release".

I want your's solution as quick as posiible, thank you very much!!

**Comment by jdm** [comment]
Does using `extern "C" fn process() {` make a difference?

**Comment by alexcrichton** [comment]
As @jdm mentioned, you'll want to ensure that the function is marked with `extern` (the `"C"` is optional) to ensure that the ABI matches what node.js expects. You'll also want to be sure it's `pub` to make sure it's exported from the DLL, and finally you'll want to add the `#[no_mangle]` attribute to ensure that the symbol isn't mangled (e.g. it's actually called `process`). After that it should be good to go!

**Comment by fuyingfuying** [comment]
The problem has been solved!!Thank you very much^_^

**Comment by snehabhapkar10** [comment]
@fuyingfuying , how did the problem solve?
