### ISSUE TITLE
Functions moving a box cannot immediately mutate it.

### ISSUE THREAD

**Issue by Jexell** [rust-lang/rust#26054]
The following code...
```rust
fn foo(ptr: Box<i32>) -> Box<i32> {
    let mut ptr = ptr; // ... Cannot compile without this line.
    *ptr += 1;
    ptr
}

fn main() {
    let mut x = Box::new(0);
    let x = foo(x);
    println!("{:?}", x);
}
```
If the line is omitted I get the following error message in the Rust playpen:
```
<anon>:3:5: 3:14 error: cannot assign to immutable `Box` content `*ptr`
<anon>:3     *ptr += 1;
             ^~~~~~~~~
error: aborting due to previous error
playpen: application terminated with error code 101
```
Even if this is not a bug in the compiler, the compiler error message is confusing, especially as it is not obvious how to make `ptr` mutable.

**Comment by jdm** [comment]
`fn foo(mut ptr: Box<i32>) -> Box<i32> {` is what you're looking for.

**Comment by Jexell** [comment]
Thanks, I did not know that you could do this..
