### ISSUE TITLE
expansion-based `box` exacerbates pretty-printing to unstableness

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#26067]
Spawned off of #23616

The new expansion-based `box` protocol (#22181) will internally expanded into calls to API methods that are unstable.

This is going to mean that tests that use `box` that today can be tagged with `pretty-expanded FIXME #23616` are going to have to switch to not opting-into the `pretty-expanded` test, I think due to the same issue as #23616.

(Thinking about the problem now, we could work around this problem by having the pretty-printer inject attributes to turn off the stability checking.  This would only work on nightly so it wouldn't resolve #23616 as written, but it would allow us to continue testing pretty-expanded on things that use `box`, I think...)

**Comment by steveklabnik** [comment]
Triage: no changes that I'm aware of.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/23616. I don't see this as being a separate problem, really.
