### ISSUE TITLE
compile-rt regression?

### ISSUE THREAD

**Issue by apirogov** [rust-lang/rust#26069]
I am on Arch Linux and trying to compile Rust. After cloning, ./configure && make I get the "can not find gcc triple" error when building compiler-rt that should be fixed (#12356, #12359). With LANGUAGE=C it continues the build.

**Comment by seifertm** [comment]
I had the same issue when building Rust on Gentoo Linux (using the package manager). With my default locale `de_DE.utf8` I get the following error:

    make/platform/clang_linux.mk:16: *** "unable to infer compiler target triple for gcc".  Schluss.
    make[1]: Verzeichnis „/var/tmp/portage/dev-lang/rust-1.0.0/work/rustc-1.0.0/src/compiler-rt“ wird verlassen
    /var/tmp/portage/dev-lang/rust-1.0.0/work/rustc-1.0.0/mk/rt.mk:318: die Regel für Ziel „x86_64-unknown-linux-gnu/rt/libcompiler-rt.a“ scheiterte
    make: *** [x86_64-unknown-linux-gnu/rt/libcompiler-rt.a] Fehler 2

If I prepend `LC_ALL="C"` to the build command, everything works just fine.

**Comment by bryteise** [comment]
I see the same issue, the LC_ALL="C" prepend didn't get everything building for me though. This is with 1.2.0.

**Comment by steveklabnik** [comment]
Hi everyone! This thread is now very old, and we've been doing a lot of work on the build system, so I assume this is all stale. Please open new issues if you're still having problems, thanks!
