### ISSUE TITLE
A borrow confusion

### ISSUE THREAD

**Issue by ctemple** [rust-lang/rust#26064]
hei guys,I am a Novice,there is A confusion about borrow

Imagine a game server and a container with multiple objects, like HashMap, when the object is updated, there may change other objects or their own properties, which is a recurring situation, any way? Code as shown below

/ / container  borrowed
for key,value in objects.iter_mut {
 // current object borrowed
 value.update ();
}

// object.update
fn update(self &mut) {
...
...
 // Failed:: need borrow self again or other object
 let other_or_self = get_global_objects () ->find (10000); // find object in container
 other_or_self.set_life (1000); //
}

**Comment by samnardoni** [comment]
It would be best to ask this question at [users.rust-lang.org](https://users.rust-lang.org/).

**Comment by Aatch** [comment]
This isn't really an issue. Feel free to ask at [users.rust-lang.org](users.rust-lang.org), StackOverflow or on IRC.
