### ISSUE TITLE
Source Code comments containing old array syntax

### ISSUE THREAD

**Issue by TheNeikos** [rust-lang/rust#26074]
Would a pull request fixing the source code comments be appreciated? I noticed that there were a few here and there in the source code.

I mean notations like `[T, ..n]` instead of `[T; n]` which was added in rfc#520

I ask because it is a minor change, and perhaps there is already a system in place for cleanup. (Which I did not find in Contributing.md)

**Comment by sanxiyn** [comment]
Yes, I think it will be appreciated.

**Comment by steveklabnik** [comment]
Agreed, I will r+ such a PR.

**Comment by steveklabnik** [comment]
(But given that this is not a bug, I'm giving it a close)

**Comment by TheNeikos** [comment]
I have submitted my pr: https://github.com/rust-lang/rust/pull/26099
