### ISSUE TITLE
Impls for function pointers are patchy

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#26082]
I'd expect function pointers (`fn()` with all combinations of safety and ABI) to implement roughly the same set of traits as raw pointers, namely:
`PartialEq`, `Eq`, `Clone`, `PartialOrd`, `Ord`, `Hash`, `fmt::Pointer`, `Debug`

Currently `Clone` is implemented for safe and unsafe function pointers, but all the ABIs except for "Rust" and "C" are ignored, i.e. a paradoxical situation takes place - `extern "rare_abi" fn()` is `Copy`, but not `Clone` (Edit: and it causes ICEs).
`PartialEq` is implemented only for safe function pointers with "C" ABI.
All the other traits are not implemented.

**Comment by petrochenkov** [comment]
(I'm going to implement all of these if there are no objections.)

**Comment by bluss** [comment]
See issue  #24000 -- fn() types are also further parameterized by their number of lifetime parameters unfortunately, so it's very hard to cover even all possibilities of regular rust ABI functions.

**Comment by petrochenkov** [comment]
Hm, interesting
```
impl<T> Clone for for<'a> fn(&'a T) {}
```
works for plain references and other "concrete" uses of lifetimes, but I see no way to cover something like this
```
impl<T> Clone for for<'a> fn(T) where T: 'a {} // made up syntax
```
generically.
