### ISSUE TITLE
Regression because of #26008

### ISSUE THREAD

**Issue by tomaka** [rust-lang/rust#26096]
#26008 caused a regression ([see travis](https://travis-ci.org/tomaka/glium/builds/65866335)).

Here is the code:

```rust
use std::rc::Rc;
    
let a: Rc<Option<u32>> = Rc::new(Some(5));
let _b: Option<&u32> = a.as_ref();
```

It works with stable because `as_ref()` is called on the `Option`.
But in the nightlies, `as_ref()` is called on the `Rc` and I get a `&Option<u32>` instead of a `Option<&u32>`.

**Comment by Aatch** [comment]
Related to #26080

**Comment by arielb1** [comment]
@Aatch 

Not really. This case works in the same way as `a.clone()` (working on the `Rc` rather than dereferencing it).

**Comment by retep998** [comment]
According to the semver RFC this is semver compatible because it is possible to rewrite the code in a way that will work with both versions. `Option::as_ref(&*a)`

**Comment by alexcrichton** [comment]
triage: P-high

decided to revert the addition of the `AsRef` impl, and try again later perhaps but first run it through crater.
