### ISSUE TITLE
Errors for traits not being implemented on trait objects should be clearer

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#26100]
http://xania.org/201506/traits-and-trait-objects

``` rust
pub trait Tr {
    fn me<A>(&self, a: A);
}

fn render(obj: &Tr) {
    obj.me(1);
}
```

gives the cryptic error

```
<anon>:6:9: 6:14 error: the trait `Tr` is not implemented for the type `Tr` [E0277]
<anon>:6     obj.me(1);
                 ^~~~~
```

`Tr` is not object safe. We should have notes when:
- A non-object safe thing is used as a trait object (warning, not error)
- A note on the "trait not implemented" error. A different error code with an explanation of object safety is a plus.

**Comment by nham** [comment]
If you add the following code, you get a respectable error message:

```rust
struct Bar;

impl Tr for Bar {
    fn me<A>(&self, a: A) {}
}

fn main() {
    let b = Bar;
    let obj = &b as &Tr;

    render(obj);
}
```

Because actually trying to coerce to a trait object gives you E0038:

```
no_obj_safety.rs:6:9: 6:14 error: the trait `Tr` is not implemented for the type `Tr` [E0277]
no_obj_safety.rs:6     obj.me(1);
                           ^~~~~
no_obj_safety.rs:17:15: 17:17 error: cannot convert to a trait object because trait `Tr` is not object-safe [E0038]
no_obj_safety.rs:17     let obj = &b as &Tr;
                                  ^~
no_obj_safety.rs:17:15: 17:17 note: method `me` has generic type parameters
no_obj_safety.rs:17     let obj = &b as &Tr;
                                  ^~
error: aborting due to 2 previous errors
```

What we really want is the `note: method `me` has generic type parameters` note here regardless of whether a trait object value is actually created or just referenced in a function signature

**Comment by arielb1** [comment]
Shouldn't this be a wf check?

**Comment by steveklabnik** [comment]
Today, this gives a "cannot be made into an object" error, so I think it can be closed!
