### ISSUE TITLE
bench should put deliminators on nanosecond numbers

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#26109]
From [this initial rust experience blog](http://ericsink.com/entries/rust1.html), `cargo bench` (I assume identical to `rustc --test`) should report nanosecond times as `3_000_000` or `3,000,000`, not `3000000`.

This reportedly would require fixing in libtest.

**Comment by bluss** [comment]
I posted a PR for this yesterday. Well I chose to round & use units, but you can opine either way  #26068

**Comment by mdinger** [comment]
@bluss nice! If you'll just tag that as fixing this then bors will take care of the rest.
