### ISSUE TITLE
TRPL: (assignment == empty tuple), please elaborate

### ISSUE THREAD

**Issue by mcast** [rust-lang/rust#26120]
Hi,

I really like TRPL and have found it answers most of my questions in the footnotes.
Looking at https://github.com/rust-lang/rust/blame/stable/src/doc/trpl/functions.md#L144-L153

> Note that assigning to an already-bound variable (e.g. y = 5) is still an expression,
> although its value is not particularly useful. Unlike other languages where an assignment
> evaluates to the assigned value (e.g. 5 in the previous example), in Rust the value of an
> assignment is an empty tuple ():
```rust
let mut y = 5;
 
let x = (y = 6);  // x has the value `()`, not `6`
```

I guessed this difference would be to discourage "clever" coding..?  It would be nice to have an explanatory link to read.

Thanks,

Matthew

----
ps. research done...  I could find only https://internals.rust-lang.org/t/allow-loops-to-return-values-other-than/567 on loop return values.

**Comment by tbu-** [comment]
Since you can't return the new value of `y` (it would need to be cloned), which value could you return. The only possibility would be the old value of `y`, but that would probably be too surprising.

**Comment by bluss** [comment]
mcast, this is the impact of ownership semantics. For general types, you can't give the same value to two different owners (both y and x).

**Comment by mcast** [comment]
Thanks @tbu- @bluss, that makes sense now.  Would it be right to add a forward reference?

```diff
diff --git a/src/doc/trpl/functions.md b/src/doc/trpl/functions.md
--- a/src/doc/trpl/functions.md
+++ b/src/doc/trpl/functions.md
@@ -146,3 +146,5 @@
  expression, although its value is not particularly useful. Unlike other
  languages where an assignment evaluates to the assigned value (e.g. `5` in the
- previous example), in Rust the value of an assignment is an empty tuple `()`:
+ previous example), in Rust the value of an assignment is an empty tuple `()`
+ because the value can have (just one owner)[ownership.html], and any other
+ value would be too surprising:
```

(diff cooked manually, hope it fits)

**Comment by steveklabnik** [comment]
@mcast yes, I would accept that as a PR. :)

**Comment by mcast** [comment]
Thanks for the merge, and sorry about the mistakes.
