### ISSUE TITLE
Destructuring fails to infer FnOnce

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#26139]
This should move `n` but it doesn't. It doesn't seem to infer it properly.

Code:
```rust
struct Name(String);

fn apply<F>(f: F) where
    F: FnOnce() {

    f()
}

fn main() {
    let n = Name(String::new());
    let consume = || {
        let Name(i) = n;
    };

    apply(consume);
}
```

Error:
```cmd
<anon>:12:23: 12:24 error: cannot move out of captured outer variable in an `Fn` closure
<anon>:12         let Name(i) = n;
                                ^
```

**Comment by cybergeek94** [comment]
Currently the compiler needs a hint when it should move a value into a closure:

```rust 
let consume = move || {
    //...
};
```

Eventually, I think we do want to infer moving upvars but it might be difficult. I think there's already an issue for tracking this problem that explains it in more detail.

**Comment by mdinger** [comment]
Even with 'move', the exact same error remains.

**Comment by talchas** [comment]
So move also is insufficient here - you wind up with the same error. However if you write
```
    let n = Name(String::new());
    let m = Name(String::new());
    let consume = move || {
        let m = m;
        let Name(i) = n;
    };
```
it will work, and yet fail ("error: cannot move out of captured outer variable in an `FnOnce` closure") without the move. It seems that the destructuring-let isn't included in figuring out it needs to be an FnOnce closure or something, /and/ the closure is missing move.

**Comment by brson** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/30046
