### ISSUE TITLE
Unused feature warning doesn't show for non-lib features

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#26135]
Features like `thread_local` or `unsafe_no_drop_flag` or `box_syntax`, which are needed to use language features, are not caught by the `unused_feature` lint.

Perhaps we should add some more robust usage-checking?

**Comment by Manishearth** [comment]
cc @brson @Gankro

**Comment by brson** [comment]
This is a known limitation of the current implementation. Should probably be fixed.

**Comment by steveklabnik** [comment]
Triage: no changes I'm aware of.

**Comment by sanmai-NL** [comment]
Duplicate of #23528, @Mark-Simulacrum?

**Comment by Mark-Simulacrum** [comment]
Yep! Thanks.
