### ISSUE TITLE
Dead testing code in the tree?

### ISSUE THREAD

**Issue by tshepang** [rust-lang/rust#26156]
These 2 files appear to be not used:

- src/libcoretest/hash/sip.rs
- src/libcoretest/intrinsics.rs

I only suspected they may not be used because they use `uint` in them, so there's probably more unused files?

**Comment by fhahn** [comment]
I think this issue can be closed, as both files should be used now: https://github.com/rust-lang/rust/blob/master/src/libcoretest/lib.rs#L61 and https://github.com/rust-lang/rust/blob/master/src/libcoretest/hash/mod.rs#L11

**Comment by alexcrichton** [comment]
Yay!
