### ISSUE TITLE
FreeBSD buildbots broken by 31764a9

### ISSUE THREAD

**Issue by dhuseby** [rust-lang/rust#26183]
Changeset 31764a9 broke the FreeBSD buildbots because it switched from defaulting to clang to defaulting to gcc.  Based on the output from the failing configure step, it's obvious the buildbots don't have gcc installed.

cc: @wca

**Comment by dhuseby** [comment]
PR submitted #26185.

**Comment by steveklabnik** [comment]
Since https://github.com/rust-lang/rust/pull/26185 was merged I'm giving this a close.
