### ISSUE TITLE
10% of calls to .*iter() are redundant

### ISSUE THREAD

**Issue by Veedrac** [rust-lang/rust#26188]
The source has just over 200 calls to `iter`, `iter_mut` or `into_iter` to things that take and `T: IntoIterator`. This is, by my count, about 10% of them!

Some examples are `left.extend(Some(x).into_iter())` instead of `left.extend(Some(x))` and `for &(s,t) in v.iter()` instead of `for &(s,t) in v`.

I thought this would make a quick, trivial change to warm myself up to the build system and such, so I've already got a branch removing it. I thought I'd ask if it's actually desirable to do so, though, since it's a lot of seemingly-meaningless code churn.

If this is wanted, the docs should probably also be updated to emphasize that many calls to `.*iter()` aren't needed. Much of the documentation for `iter()` and co. uses them in places where they can be elided.

**Comment by steveklabnik** [comment]
> the docs should probably also be updated to emphasize that many calls to .*iter() aren't needed.

We do already specifically talk about this in the doc, but you have to remember that `rustc`'s codebase is older than `IntoIterator`! :) 

Generally speaking, we accept PRs that update the code to something more idiomatic. I don't speak for everyone, but I would be :+1: on it.

**Comment by steveklabnik** [comment]
After pinging #rust-internals, it would seem that others agree. Please send a PR! Thanks :)

**Comment by Manishearth** [comment]
Rust and Servo are bad examples for idiomatic rust code because of the hysterisis of rust upgrades. 

I haven't seen _new_ code doing this, so I don't think it's a pervasive problem -- just isolated to rust. :+1: to fixing it :smile:
