### ISSUE TITLE
Use of raw pointer as self parameter

### ISSUE THREAD

**Issue by eefriedman** [rust-lang/rust#26194]
Testcase:
```rust
struct S(String);
impl S {
    fn f(self: *mut S) -> String { self.0 } 
}
fn main() { S("".to_owned()).f(); }
```

This somehow compiles and runs without any errors.

I'm not sure how exactly this is getting interpreted by the compiler, but it seems dubious at best.

**Comment by Veedrac** [comment]
`self` is of type `S` inside the function, and seems to be moved "correctly".

    s.f();
    s.f();

gives

    <anon>:8:5: 8:6 error: use of moved value: `s`
    <anon>:8     s.f();

whilst

    fn f(self: *mut S) { let _: () = self; }

gives

    <anon>:3:38: 3:42 error: mismatched types:
     expected `()`,
        found `S`
