### ISSUE TITLE
Casting a function pointer to a non-machine integer type results in an LLVM Error

### ISSUE THREAD

**Issue by Aatch** [rust-lang/rust#26203]
This code produces the error `LLVM ERROR: expected relocatable expression`:

```rust
fn foo(_: i32) { }

fn main() {
    let x : u32 = foo as u32;
}
```

I'd expect this to work on a 32-bit platform though. I'd argue this is technically LLVM's bug, since casting a regular raw pointer works just fine.

This does however raise the point of whether or not allowing casting to non-machine integers from pointers should be allowed. The case that uncovered this bug was actually supposed to be casting the return value of the function.

The fix for this should be fairly simple, if we decide to accept the behaviour (either out of backwards compability concerns or otherwise), just run all casts like this through the machine integer first.

/cc @rust-lang/compiler @rust-lang/lang

**Comment by alexcrichton** [comment]
@rust-lang/lang -- guh github perms

**Comment by Aatch** [comment]
Nevermind, I just discovered that this doesn't error on nightly.
