### ISSUE TITLE
Some things don't implement IntoIterator

### ISSUE THREAD

**Issue by Veedrac** [rust-lang/rust#26220]
There are some missing `IntoIterator`s:

* By-reference and mut-reference for `Option`
* By-reference and mut-reference for `Result`
* By-reference for `Path`
* Several misc. internal things (`TraitObligationStackList`, `SearchPaths`, `ArchiveRO`, `RawTable`, `Book`)

Given the by-value `IntoIterator` `impl`s for `Option` and `Result`, I don't see why by-reference iteration would be special. `Path` should probably be `IntoIterator`. I'm indifferent with regards to internal stuff.

**Comment by apasel422** [comment]
This was partially addressed by #28039.

**Comment by arielb1** [comment]
internal things will only get impls when they are needed for internal purposes. e.g. `TraitObligationStackList` is only ever accessed by immutable reference.

**Comment by apasel422** [comment]
CC @rust-lang/libs. The only outstanding part of this is `&Path` (and presumably `&PathBuf`).

**Comment by alexcrichton** [comment]
Seems like an easy bug to knock out!
