### ISSUE TITLE
Error about "different enum" could be more helpful

### ISSUE THREAD

**Issue by viraptor** [rust-lang/rust#26236]
I ran into an error saying:
```
src/database.rs:141:28: 141:52 note: expansion site
src/db_pool.rs:20:55: 20:68 error: mismatched types:
 expected `postgres::SslMode`,
    found `postgres::SslMode`
(expected enum `postgres::SslMode`,
    found a different enum `postgres::SslMode`) [E0308]
src/db_pool.rs:20     let manager = PostgresConnectionManager::new(url, SslMode::None).unwrap();
```

Which is not very useful for debugging. I get where the problem could come from - different library versions used in different dependencies... but this doesn't really help me see where the different versions come from.

**Comment by sfackler** [comment]
This looks like somewhat of a dup of #22750, but we definitely do need better handling of this kind of situation. The current message is pretty awful.

**Comment by steveklabnik** [comment]
Yes, this is a dup of #22750, and agreed that it's particularly terrible :(
