### ISSUE TITLE
1.0.0 lacks `share/doc/rust/html/error-index.html`

### ISSUE THREAD

**Issue by mcast** [rust-lang/rust#26240]
After install from `rust-1.0.0-x86_64-apple-darwin.tar.gz`, the link in `share/doc/rust/html/index.html#the-error-index` to `share/doc/rust/html/error-index.html` is 404.  (This doesn't trouble me, I'm still poking around.)

404 because it is absent rather than renamed - by `grep -r "Rust Compiler Error Index" rust-1.0.0/`.

I found src/error-index-generator/main.rs but haven't looked at where the ends don't meet.  I'm happy to carry on digging later...

**Comment by mcast** [comment]
Found something: deaa1172 removes `error-index` from `DOC_TARGETS := trpl style error-index` in `mk/docs.mk` due to #25705.

**Comment by steveklabnik** [comment]
That patch landed way after 1.0, so it shouldn't have affected this.

**Comment by mcast** [comment]
Yes...  98fef7b8 is where the href arrives on stable.  It is the same as part of 6faa8d67, to the second, but the latter also touches `src/librustc/diagnostics.rs`.

`src/error-index-generator/main.rs` is added only in 1174114 and that isn't in stable. `git log --name-only stable |grep error-index` is nul.

So what to do?
* Remove that section of `src/doc/index.md` from stable
* Run the tool now (compile from master, run on stable?), stash the resulting html in the stable tree

The one on master isn't compiling for me just now.  Maybe it can be my first dunking in rust.
```console
$ DYLD_LIBRARY_PATH=~/Applications/rust-1.0.0/lib rustc -o error-index-generator src/error-index-generator/main.rs 
src/error-index-generator/main.rs:23:37: 23:53 error: unresolved import `syntax::diagnostics::metadata::get_metadata_dir`. Could not find `metadata` in `syntax::diagnostics`
src/error-index-generator/main.rs:23 use syntax::diagnostics::metadata::{get_metadata_dir, ErrorMetadataMap};
                                                                         ^~~~~~~~~~~~~~~~
src/error-index-generator/main.rs:23:55: 23:71 error: unresolved import `syntax::diagnostics::metadata::ErrorMetadataMap`. Could not find `metadata` in `syntax::diagnostics`
src/error-index-generator/main.rs:23 use syntax::diagnostics::metadata::{get_metadata_dir, ErrorMetadataMap};
                                                                                           ^~~~~~~~~~~~~~~~
error: aborting due to 2 previous errors
```
and yes, some kind of installer/dyld problem too.

**Comment by alexcrichton** [comment]
Unfortunately the error-index-generator uses unstable features right now (links to libsyntax as you've seen), which means that it's not generally going to work if you compile it out-of-tree (due to libsyntax changing rapidly over time).

I think that generation of this is currently disabled as well due to various implementation issues in the previous version, so I'm going to close this in favor of https://github.com/rust-lang/rust/issues/26009.
