### ISSUE TITLE
Could some one help me fix this?

### ISSUE THREAD

**Issue by Dgreatcornholio** [rust-lang/rust#26269]
When i Try to join in a server. WHen it says loading map. The game just crashes and gives me an error report. I will gladly send you one if you want me to. Please help me!

**Comment by Stebalien** [comment]
Hi. This is the bug tracker for rust the *programming language*. You're looking for rust the game: [forums](http://facepunch.com/forumdisplay.php?f=415), [support](http://support.facepunchstudios.com/)
