### ISSUE TITLE
Lifetime Invalid unless Using Type Alias.

### ISSUE THREAD

**Issue by Psylee11235** [rust-lang/rust#26266]
The issue is with the following code, which appears to be valid:
```
use std::collections::HashMap;
use std::collections::LinkedList;

trait Generator { }

trait Object {
    fn do_thing(&mut self, list: &LinkedList<Box<Generator>>);
}

pub struct Container {
    // Key type irrelevant.
    map: HashMap<u32, Box<Object>>
}

impl Container{
    pub fn modify_contents(&mut self) {
        let temp = LinkedList::new();
        for (_, obj) in self.map.iter_mut() {
            // temp being local is irrelevant; error occurs even passed as a parameter or as return value.
            obj.do_thing(&temp);
        }
    }
}
```

The given error is that `temp` does not live long enough. However, if I change the parameter list of do_thing to
```
fn do_thing(&self mut, list: LinkedList<Box<T>>)
```
Where I've aliased Generator to T with
```
pub type T = Generator;
```

It compiles and will run fine. Happens on each 1.0.0, beta, and nightly builds.

Notes: "reference must be valid for the block at 15:28, but borrowed value is only valid for the block suffix following statement 0 at 16:31."

**Comment by mitaa** [comment]
This fails to compile as described
```rust
fn do_thing<'a>(&mut self, list: &'a LinkedList<Box<Generator + 'a>>);
```

This compiles
```rust
fn do_thing<'a, 'b>(&mut self, list: &'a LinkedList<Box<Generator + 'b>>);
```

The type alias seems to result in `Generator + 'static`

I guess this has to do with [default object bounds (RFC 0599)](https://github.com/rust-lang/rfcs/blob/master/text/0599-default-object-bound.md)

**Comment by arielb1** [comment]
This is as expected (cc rust-lang/rfcs#1156).
