### ISSUE TITLE
ICE with mut reference in `static mut`

### ISSUE THREAD

**Issue by eefriedman** [rust-lang/rust#26263]
Testcase:
```rust
static mut TEST: [isize; 1] = [1];
static mut TEST2: &'static mut [isize] = unsafe { &mut TEST };
fn main() {
    println!("{}", unsafe { TEST2[0] });
}
```

Produces:
```
<anon>:2:56: 2:60 error: internal compiler error: expected a const, fn, struct, or variant def
<anon>:2 static mut TEST2: &'static mut [isize] = unsafe { &mut TEST };
                                                                ^~~~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:176
```

**Comment by arielb1** [comment]
I think the original intent was to allow references to slices `&mut [1,2,3]`.

**Comment by arielb1** [comment]
What level of this should be allowed? We don't borrowck statics, so you can do `(&mut A, &mut A)`.

**Comment by eefriedman** [comment]
I would figure if someone is willing to use unsafe blocks to build a static mut variable, we should just let them shoot themselves in the foot.  You can construct a static mut variable containing `(&mut A, &mut A)` at runtime anyway.

**Comment by apasel422** [comment]
Triage: Still an issue.

**Comment by steveklabnik** [comment]
This ICE seems to be fixed on

```
rustc 1.12.0-nightly (b30eff7ba 2016-08-05)
```

I have a hunch that this is due to MIR being turned on, though I'm not sure. Please let me know if this still ICEs for you, but closing for now :confetti_ball:
