### ISSUE TITLE
Hint for a lifetime binding of a type in a trait suggests invalid syntax [E0309]

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rust#26271]
Hint in the error message for this code appears to suggest a syntax that doesn't compile ([playpen](http://is.gd/jKV7UL)):

``` rust
trait Tr {
    type TrSubtype;
}

struct Bar<'a, Item: Tr>  {
    item: Item,
    item_sub: &'a <Item as Tr>::TrSubtype,
}
```

> error: the associated type `<Item as Tr>::TrSubtype` may not live long enough  
> […] consider adding an explicit lifetime bound `<Item as Tr>::TrSubtype: 'a`...

When I did what (I thought was) suggested (since the same syntax worked in simpler cases):

``` rust
struct Bar<'a, Item: Tr, <Item as Tr>::TrSubtype: 'a>  {
```

it failed with a very unfriendly syntax error:

> error: expected ident, found `<`  

After a lot of head scratching I've discovered that it meant:

``` rust
struct Bar<'a, Item: Tr> where <Item as Tr>::TrSubtype: 'a  {
```

So I suggest either:
- Make the error hint suggest syntax with the `where` keyword when necessary
- Allow the syntax without `where`: `<'a, Item: Tr, <Item as Tr>::TrSubtype: 'a>>`
- or detect when `<` is found instead of an ident and emit error along lines of "Move that to the `where` clause".

**Comment by Anachron** [comment]
I would give :+1: to the last one.

**Comment by steveklabnik** [comment]
Triage: same error as today.

**Comment by estebank** [comment]
Funnily enough, [this code now works in the latest beta](https://play.rust-lang.org/?gist=fbe9035d3e9483f9441249e7c2414b2a&version=beta&mode=debug&edition=2015).

---

Do not close: we still want to change the parser to accept `struct Bar<'a, Item: Tr, <Item as Tr>::TrSubtype: 'a>  {` and emit a tailored diagnostic.
