### ISSUE TITLE
Wrapping<T> does not wrap on shift operations

### ISSUE THREAD

**Issue by nwin** [rust-lang/rust#26270]
The following code leads to a panic:

```rust
use std::num::Wrapping;
fn main() {
    println!("{}", (Wrapping(1i32) >> (32usize)).0)
}
```

This is surprising as the description of `Wrapping` implies, that all implemented arithmetic operations just overflow (somehow). It also contradicts the behavior of the unstable method `u32::wrapping_shr`. The latter has also a slightly surprising behavior since `1u32.wrapping_shr(32) == 1`, `1u32.wrapping_shr(33) == 0`, `1u32.wrapping_shr(64) == 1` etc.

**Comment by alexcrichton** [comment]
I think this may just be an oversight in the implementation.

**Comment by nagisa** [comment]
Shifting by not less than width of shiftee is generally considered to be UB in some architectures. The panic should indeed not happen though.

**Comment by lfairy** [comment]
Looks like it's fixed now. Should we close this issue?

**Comment by alexcrichton** [comment]
Indeed!
