### ISSUE TITLE
documentation buglet in Traits section

### ISSUE THREAD

**Issue by tromey** [rust-lang/rust#26287]
I am reading here:

http://doc.rust-lang.org/stable/book/traits.html#where-clause

I also checked the nightly docs, which are the same.

The example says:

```
// can be called with T == i64
fn inverse<T>() -> T
        // this is using ConvertTo as if it were "ConvertFrom<i32>"
        where i32: ConvertTo<T> {
    1i32.convert()
}
```

However, I did not see any other mention of `li32`.  It seems like it should probably be the name of a formal argument to `inverse`.

**Comment by Stebalien** [comment]
1i32 = one i32. Fonts...

**Comment by tromey** [comment]
Ouch, I did not see that at all.  How about making it "79i32" or something like that?

**Comment by Stebalien** [comment]
Alternatively, we could ditch the serifed font.
