### ISSUE TITLE
error-message about lifetime is shadowing more useful error-message

### ISSUE THREAD

**Issue by colin-kiegel** [rust-lang/rust#26295]
Update - I got confused by the error message

Most error messages are very good, but some are confusing, like this one (code below):
* ........ error: `owned` does not live long enough

I would have expected the following error instead, which I find more intuitive:
* ........ error: cannot move out of `string` because it is borrowed

You can copy-paste this snippet to http://play.rust-lang.org/.
```Rust
// Foo has a str-borrow with a lifetime 'a and an owned String-object
struct Foo<'a> {
    ptr: &'a str,
    string: String,
}

#[test]
fn new_foo() {
    // try to create an instance of Foo where foo.ptr points to foo.owned
    let foo = {
        let owned = "This belongs to Foo".to_string();
        
        Foo {
            ptr: &owned,
            string: owned,
        }
    }; // <--- Rust errors that 'owned' goes out-of-scope here,
      //     but that's not intuitve, because it looks like it is 'moved' and returned,
      //     however the real error is that 'owned' is invalidated by the borrow &owned
}
```

```
<anon>:14:19: 14:24 error: `owned` does not live long enough
<anon>:14             ptr: &owned,
                            ^~~~~
<anon>:17:7: 20:2 note: reference must be valid for the block suffix following statement 0 at 17:6...
<anon>:17     }; // <--- Rust errors that 'owned' goes out-of-scope here,
<anon>:18       //     but that's not intuitve, because it looks like it is 'moved' and returned,
<anon>:19       //     however the real error is that 'owned' is invalidated by the borrow &owned
<anon>:20 }
<anon>:11:55: 17:6 note: ...but borrowed value is only valid for the block suffix following statement 0 at 11:54
<anon>:11         let owned = "This belongs to Foo".to_string();
<anon>:12         
<anon>:13         Foo {
<anon>:14             ptr: &owned,
<anon>:15             string: owned,
<anon>:16         }
          ...
```

**Comment by arielb1** [comment]
The error is correct. While there is indeed a borrow error there, `owned` is declared inside of a block, but you try to return it outside the block. This would still be a problem even if `owned` was a `Copy` type (e.g. `u32`). Local variables never outlive their defining block (you can move a value out of a local, but then it isn't that local variable anymore).

**Comment by arielb1** [comment]
I mean, your code would still be broken even if you didn't move `owned` into the struct - the local won't outlive its block in any case (of course, the move makes the local's *value* outlive the block, but that still won't help you of course).

Anyway, the reason you hit the lifetime error first is because lifetimes are computed before borrow-checking is done. This is not going to change, because attempting to borrow-check code with invalid lifetimes tends to lead to error cascades.
