### ISSUE TITLE
OS X no longer reports upstream LLVM version

### ISSUE THREAD

**Issue by horse-mans** [rust-lang/rust#26292]
Starting with OS X El Capitan, the output of `clang --version` is similar to:

```
Apple LLVM version 7.0.0 (clang-700.0.53)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```

This means, going forward, that the logic at https://github.com/rust-lang/rust/blob/3d74fbd4961dc66781bc5531e5d937eaee45d99c/configure#L974 can no longer accurately determine what version of clang is running on OS X.

Before El Capitan's beta I would have suggested having pairs of Apple Clang versions and their upstream counterparts to compare to (i.e. using a resource such as https://gist.github.com/yamaya/2924292) but I imagine the new `--version` output is Apple subtly suggesting applications shouldn't need to know what version of LLVM is under the hood.

**Comment by nagisa** [comment]
> Apple subtly suggesting applications shouldn't need to know what version of LLVM is under the hood.

We are not an application, we are a compiler. Since they do not want us to, anymore, I guess the only way is to go ahead and ship our own set of LLVM tools (we currently do not).

**Comment by polidore** [comment]
any safe workaround?

**Comment by nagisa** [comment]
https://github.com/rust-lang/rust/pull/27006 was merged, therefore it should work.

**Comment by steveklabnik** [comment]
closing, thanks @nagisa
