### ISSUE TITLE
rustdoc: support for the --nocapture feature of libtest

### ISSUE THREAD

**Issue by IvanUkhov** [rust-lang/rust#26309]
Currently, `librustdoc` is diligently [passing](https://github.com/rust-lang/rust/blob/0d82fb55dbb9b28798ea7c2004fa91fe3ae23b86/src/librustdoc/test.rs#L117) test arguments to `libtest` via `--test-args`, including `--nocapture`. However, `librustdoc` internally [captures](https://github.com/rust-lang/rust/blob/0d82fb55dbb9b28798ea7c2004fa91fe3ae23b86/src/librustdoc/test.rs#L247) the output of doc-tests and doesn’t let it get through to `libtest`. Consequently, the usage of `--nocapture` in this context is somewhat limited (when supplied it reveals compiler warnings, for instance) and doesn’t serve its main purpose. This behavior is inconsistent with the rest of the testing.

Regards,
Ivan

**Comment by cramertj** [comment]
Ping @steveklabnik-- has there been any more discussion about this?

**Comment by gnzlbg** [comment]
Ping @QuietMisdreavus , can someone cc docs team here? This has been open for a long time.

**Comment by QuietMisdreavus** [comment]
cc @rust-lang/rustdoc 

IIRC, the last time we tried to make `--nocapture` work, we hit problems with how the output was passed from doctests back to libtest. @GuillaumeGomez, do you remember what happened there?

**Comment by GuillaumeGomez** [comment]
I still have an in-progress branch on this one. It's tricky because libtest is handling outputs itself and we need to add functionalities to tell it not to do it. But then, outputs get lost... somewhere. This is where I am now. Trying to get back outputs (both stdout and stderr).

**Comment by steveklabnik** [comment]
Triage: I don't think anything has changed here.

**Comment by GuillaumeGomez** [comment]
Definitely didn't. I start I'll start over from start when I'll get back to it.

**Comment by pipehappy1** [comment]
This feature is much appreciated. Without this, the doc test can only benefit doc reader but less useful for debugging during dev.
