### ISSUE TITLE
use gdb fails on windows

### ISSUE THREAD

**Issue by rjdgtn** [rust-lang/rust#26303]
gdb fails with error: ' "C:\...\main.exe": not in executable format: File format not recognized'

after try:
rustc -g main.rs
gdb main.exe

verions:
rustc 1.0.0
GDB 7.6.1

**Comment by retep998** [comment]
Make sure the GDB is for the same bitness as Rust. If you have a 64-bit Rust then you need a 64-bit GDB, and likewise for 32-bit.

**Comment by rjdgtn** [comment]
thanks. that was a problem
