### ISSUE TITLE
A couple of confusing diagnostics with &str slices

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#26319]
https://play.rust-lang.org/?gist=089ca2d7214f6761051c&version=stable

``` rust
let s = "abc";
let t = if true { s[..2] } else { s };       // confusing error message
let u: &str = if true { s[..2] } else { s }; // clear error message
let v = s[..2];                              // strange error message
let w: &str = s[..2];                        // clear error message
```

These are four attempts to take a slice of a `&str`, in two pairs. They are all wrong because indexing a `&str` returns a `str`, so you need an extra `&`. That's not the point. The point is without type annotations, the error diagnostics seem like they could use some improvement.

Especially the first one -- it sounds like it is saying my expression ought to be a `str`, but it already is. I think it's actually saying the associated type `Index::Output` ought to be a `str`, but the way the diagnostic is written, it sounds backwards.

Can either of these diagnostics be improved?

**Comment by steveklabnik** [comment]
Three of these have the same errors now: mismatched type between `str` and `&str`. The third has an error about Sized not being implemented.

**Comment by durka** [comment]
Maybe there could be a suggestion, if a variable is inferred to type `T: !Sized`, to add a `&` and make the variable `&T` instead?

**Comment by estebank** [comment]
Suggested output:

```
error[E0277]: the trait bound `str: std::marker::Sized` is not satisfied
 --> src/main.rs:3:5
  |
3 | let v = s[..2];                              // strange error message
  |     ^   ------ help: considering borrowing the slice: `&s[..2]`
  |     |
  |     `str` does not have a constant size known at compile-time
  |
  = help: the trait `std::marker::Sized` is not implemented for `str`
  = note: all local variables must have a statically known size
help: considering borrowing the slice
```
