### ISSUE TITLE
Optimize Int to String (Display) methods.

### ISSUE THREAD

**Issue by arthurprs** [rust-lang/rust#26310]
As of today rust uses a naive implementation for converting integers to decimal strings in ***Int*** [Debug/Display methods](https://github.com/rust-lang/rust/blob/f76d9bcfc2c269452522fbbe19f66fe653325646/src/libcore/fmt/num.rs).

I propose adding an optimization for the most commonly used case, that is, printing as decimals.

I wrote a reasonably optimized version [here](https://github.com/arthurprs/rust-optimized-inttostr). Further optimizations are possible but I tried to keep the code size small (which I think is important),  it's a road of diminished gains.

This should be non measurable overall but might give us a minor speedup on ***serde*** and ***rustc*** serializers.

Should I adapt the code and file PR?

**Comment by steveklabnik** [comment]
> Should I adapt the code and file PR?

I'd want something more than 'might give us a minor speedup', if you can post benchmarks that show it's faster, then we'd probably take such a thing, but benchmarks are important :)

(also, https://internals.rust-lang.org/ might be a better forum for this kind of question, as it isn't really a bug, exactly. So closing!)

**Comment by arthurprs** [comment]
Follow up thread on internals, including benchmarks https://internals.rust-lang.org/t/optimize-int-to-string-conversions/2245
