### ISSUE TITLE
Misleading section on angle-brackets for specializing traits in `Generic functions` section

### ISSUE THREAD

**Issue by simendsjo** [rust-lang/rust#26320]
In the [reference.md](https://github.com/rust-lang/rust/blob/master/src/doc/reference.md) in the section [Generic functions](https://doc.rust-lang.org/nightly/reference.html#generic-functions) it is stated that

> Each type parameter must be explicitly declared, in an **angle-bracket**-enclosed, comma-separated list following the function name.

(emphasis mine)

But the example shows a type parameter on `Fn`, which requires parenthesis-enclosed type parameters rather than angle-brackets. `geofft` mentioned on IRC that this might be some special case to open the possibility to easier change the `Fn` traits at a later time (if I understood correctly), but I found it confusing to see a specialization using parenthesis without ever having heard they existed.

**Comment by steveklabnik** [comment]
Isn't the text referring to

    fn iter<T, F>

Those angle brackets?

**Comment by geofft** [comment]
Yeah, I suspect the real confusion here is that the `Fn()` syntax with parens has not yet been introduced (nor is it explained anywhere, apparently), so it's the wrong example at this point in the document, and it's not clear to a first-time reader what is being referred to. It seems like there should be a sufficient example here that doesn't use closures, maybe one simple one with `println!` and `Display`, and one using traits over collections or iterators or something, to demonstrate that parameterized types can appear in the bounds, to make it easier to understand.

That said, the reference is explicitly not intended to be pedagogical, and implicitly not yet expected to be complete.
