### ISSUE TITLE
Nested macros can't define any new variables

### ISSUE THREAD

**Issue by reem** [rust-lang/rust#26329]
Example: http://is.gd/9LFIF2

The outer macro attempts to parse the new variables as existing ones, and errors when it can't find them.

**Comment by mitsuhiko** [comment]
I just ran into this.  Very annoying issue.  If it's too hard to make the identity nesting work it would be possible to just use `$$` to refer to nested variables (with added repetition at each new level).

**Comment by mitsuhiko** [comment]
This seems to be a duplicate of #6994.

**Comment by alexcrichton** [comment]
Thanks for the reference @mitsuhiko!
