### ISSUE TITLE
No warning for forward-declared variable with unused mutability

### ISSUE THREAD

**Issue by bluederef** [rust-lang/rust#26332]
The compiler gives no warning for a forward-declared variable which need not be mutable.

This code:
```rust
let mut x = 5;
let y = x + 10;
println!("{}", y);
```
yields a warning:
```rust
<anon>:2:9: 2:14 warning: variable does not need to be mutable, #[warn(unused_mut)] on by default
<anon>:2     let mut x = 5;
                 ^~~~~
```
While this code does not:
```rust
let mut x;
x = 5;
let y = x + 10;
println!("{}", y);
```

## Meta

`rustc --version --verbose`:
rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14)
binary: rustc
commit-hash: a59de37e99060162a2674e3ff45409ac73595c0e
commit-date: 2015-05-13
build-date: 2015-05-14
host: x86_64-unknown-linux-gnu
release: 1.0.0

**Comment by steveklabnik** [comment]
This is interesting, I bet it's because `x=5` is always treated as mutation, regardless.
