### ISSUE TITLE
Macros in match blocks can't expand to a pattern *and* block

### ISSUE THREAD

**Issue by reem** [rust-lang/rust#26330]
Example of incorrect behavior: http://is.gd/WmvsML

In the above example, the `branch!` macro should expand to a pattern and block, but rustc insists that it only expands into a pattern, and still expects further patterns or a block.

**Comment by reem** [comment]
@cmr told me on IRC this is because macros must produce a single valid AST node, and we don't have an AST node for "match arm".

**Comment by lfairy** [comment]
Is there any workaround for this? A macro that I'm writing works this way.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/12832.
