### ISSUE TITLE
Code examples in rust-inside-other-languages.html use "libembed", should be "embed"

### ISSUE THREAD

**Issue by tanderberg** [rust-lang/rust#26343]
The FFI examples for Ruby, Python and Node in https://doc.rust-lang.org/book/rust-inside-other-languages.html try to load "libembed", but following the preceding instructions produces a library called "embed".

**Comment by steveklabnik** [comment]
Are you sure? Did you set 

```
[lib]
name = "embed"
crate-type = ["dylib"]
```

in your cargo.toml?

**Comment by tanderberg** [comment]
Yes.

**Comment by steveklabnik** [comment]
Hrm. What platform are you on? And which version of Cargo and Rust are you using?

On my machine:

```
$ ls target/release/
build  deps  examples  libembed.so  native
```

**Comment by tanderberg** [comment]
Windows 8.1 Pro 64 bit.
rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14)
cargo 0.2.0-nightly (efb482d 2015-04-30) (built 2015-04-30)

**Comment by steveklabnik** [comment]
I bet that's it, then. I'll have to update the text to mention this, thanks!

**Comment by tanderberg** [comment]
I think it might be better to make sure that rustc uses the same naming convention on all supported platforms. Having to keep track of when to prepend a "lib" would be a nuisance.

**Comment by steveklabnik** [comment]
When there's a discrepancy between two platforms, you can do three things:

1. do the native thing on each platform
2. do something non-native on each platform
3. do something that's native to one platform on all platforms

With regards to shared libraries, we generally choose 1.

**Comment by tanderberg** [comment]
#1 sounds good. On Linux, when creating a library with gcc, you need to specify the full soname, including "lib" prefix (see e.g. http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html). So if rustc simply used the name given in cargo.toml, there would be surprises on either Linux or Windows.

**Comment by steveklabnik** [comment]
The chapter does say:

> As an aside, this may be embed.dll or libembed.dylib, depending on the platform.

So this is covered.
