### ISSUE TITLE
TRPL erroneously states that concurrency is all library

### ISSUE THREAD

**Issue by Gankro** [rust-lang/rust#26344]
> Before we talk about the concurrency features that come with Rust, it's important to understand something: Rust is low-level enough that all of this is provided by the standard library, not by the language. This means that if you don't like some aspect of the way Rust handles concurrency, you can implement an alternative way of doing things.

Atomics are a language feature that the compiler (LLVM) has to have a deep understanding of in its optimization passes. 

Send and Sync are also opt-in-built-in-traits, which makes them a pseudo-language construct.

**Comment by tshepang** [comment]
Does this mean Atomics should be mentioned in the Language Reference? What about Send and Sync?

**Comment by tshepang** [comment]
@Gankro ^

**Comment by tshepang** [comment]
@Gankro Does this mean Atomics should be mentioned in the Language Reference? What about Send and Sync? Currently, only Sync is mentioned, and that only in passing.
