### ISSUE TITLE
No warning for unused struct member if explicitly ignored

### ISSUE THREAD

**Issue by bluederef** [rust-lang/rust#26353]
The compiler gives no warning for an unused struct member if explicitly ignored.

This code:
```rust
struct MyStruct { foo: i32, bar: i32 }

fn main() {
    let my_struct = MyStruct { foo: 2, bar: 3 };
    match my_struct {
        MyStruct { foo, .. } => println!("foo is {}", foo)
    }
}
```
yields a warning:
```rust
<anon>:1:29: 1:37 warning: struct field is never used: `bar`, #[warn(dead_code)] on by default
<anon>:1 struct MyStruct { foo: i32, bar: i32 }
                                     ^~~~~~~~
```
While this code does not:
```rust
struct MyStruct { foo: i32, bar: i32 }

fn main() {
    let my_struct = MyStruct { foo: 2, bar: 3 };
    match my_struct {
        MyStruct { foo, bar: _ } => println!("foo is {}", foo)
    }
}
```

## Meta

`rustc --version --verbose`:
rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14)
binary: rustc
commit-hash: a59de37e99060162a2674e3ff45409ac73595c0e
commit-date: 2015-05-13
build-date: 2015-05-14
host: x86_64-unknown-linux-gnu
release: 1.0.0

**Comment by nagisa** [comment]
I think current behaviour is correct.

**Comment by cybergeek94** [comment]
@nagisa On first impression I would have agreed with you but after some thought I think this case should trip the lint. Even though the field has been acknowledged by the programmer, which might explain why it doesn't trip the lint, it's still dead code and so should be marked by the lint.

**Comment by AdamBadawy** [comment]
Right. My sentiment is that it's not about the author of that specific match expression being aware of all the fields, but rather that there is an unnecessary field in the struct.
