### ISSUE TITLE
The book sometimes says "threads" instead of "tasks"

### ISSUE THREAD

**Issue by tanderberg** [rust-lang/rust#26359]
Reading https://doc.rust-lang.org/book/, I have begun to think that somebody ran a global search & replace for "thread" -> "task". In iterators.html, there is a statement that "Rust provides a number of useful iterators to accomplish various threads", while concurrency.html proudly proclaims that "Rust's type system is up to the thread".

**Comment by bluss** [comment]
These are fixed in the beta and nightly branches, thank you and feel free to report more issues you can find. Docs have been read & patched by many since Rust 1.0, but the fixes are not live yet. See also the [nightly version of the book](https://doc.rust-lang.org/nightly/book/).
