### ISSUE TITLE
Dining Philosophers typo

### ISSUE THREAD

**Issue by zorbathut** [rust-lang/rust#26362]
Near the top of the Dining Philosophers book example, as displayed on https://doc.rust-lang.org/book/dining-philosophers.html :

> Here, we make a [struct][struct] to represent a philosopher. For now, a name is all we need. We choose the [String][string] type for the name, rather than &str.

This seems to work fine on the Git page - https://github.com/rust-lang/rust/blob/master/src/doc/trpl/dining-philosophers.md - but one way or another, the main documentation site formatting is broken, showing just the brackets instead of a working link.

**Comment by steveklabnik** [comment]
This was a bug that has been fixed since the last release, check out the page at https://doc.rust-lang.org/beta/book/dining-philosophers.html

Thank you for reporting though!
