### ISSUE TITLE
symbol names specified by link_name get mangled on x86 but not x86_64

### ISSUE THREAD

**Issue by bvinc** [rust-lang/rust#26365]
When specifying the link_name attribute for an extern function, the symbol names get mangled on x86 but not on x86_64.

I tried this code:
```rust
extern "stdcall" {
    #[link_name="mylinknamestdcall"]
    pub fn a(x: u32) -> u32;
}
extern "C" {
    #[link_name="mylinknamec"]
    pub fn b(x: u32) -> u32;
}

fn main() {
	unsafe {
	    a(1);
	    b(2);
	}
}
```

Of course, it fails to compile.  But here is what happens on Windows x86:

```
note: C:\src\symboltest\target\debug\symboltest.o: In function `ZN10symboltest4mainE':
C:\src\symboltest/src/main.rs:12: undefined reference to `mylinknamestdcall@4'
C:\src\symboltest/src/main.rs:13: undefined reference to `mylinknamec'
```

This error message is a bit misleading, since underscores aren't showing up in the error message.  The true symbol names that are undefined are:
```
$ objdump.exe -t target/debug/symboltest.o | grep mylinkname
[ 30](sec  0)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x00000000 _mylinknamestdcall@4
[ 31](sec  0)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x00000000 _mylinknamec
```

Notice that both symbol names are being mangled, depending on the calling convention.

On x86_64, the exact same code produces non-mangled symbols:
```
$ objdump.exe -t target/debug/symboltest.o | grep mylinkname
[ 31](sec  0)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x00000000 mylinknamestdcall
[ 32](sec  0)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x00000000 mylinknamec
```

I would expect that a name specified by the `link_name` attribute would not get mangled.  I would also expect the same behavior on x86 and x86_64.

```
$ rustc --version --verbose
rustc 1.2.0-nightly (d6c8028ce 2015-06-09)
binary: rustc
commit-hash: d6c8028ce0eaf18abb67e4e2dafc5aae2e6e91de
commit-date: 2015-06-09
host: i686-pc-windows-gnu
release: 1.2.0-nightly
```

## Workaround

If you start your `link_name` attribute with a \x01, this apparently signals LLVM to disable name mangling.  Like: `#[link_name="\x01mylinkname"]`

**Comment by retep998** [comment]
That form of mangling on x86 is actually pretty standard and most linkers/compilers will properly resolve such symbols to the mangled version.

**Comment by bvinc** [comment]
Nevermind.  It seems that these calling conventions don't seem to exist on x86_64.  Names never get mangled on x86_64.  So there was no real issue of rustc acting differently on x86_64 and x86.  There is too much misinformation in this ticket.  Closing.
