### ISSUE TITLE
Rust Book provides wrong install link for Windows

### ISSUE THREAD

**Issue by zorbathut** [rust-lang/rust#26363]
The Windows installers links at https://doc.rust-lang.org/book/installing-rust.html point to https://static.rust-lang.org/dist/rust-1.0.0-beta-i686-pc-windows-gnu.msi and https://static.rust-lang.org/dist/rust-1.0.0-beta-x86_64-pc-windows-gnu.msi . These installers are out of date and aren't able to run the source code shown in the book itself, which would probably be discouraging for new users.

These should either be meticulously kept up to date or changed into a link to the download page itself. (The latter is probably easier :V)

**Comment by steveklabnik** [comment]
On nightly, this has been changed to a link to the installer page: http://doc.rust-lang.org/nightly/book/installing-rust.html

Thanks again for reporting! All good fixes, we've just already made them. :)
