### ISSUE TITLE
rustdoc: Searching should change the document title

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#26360]
When you search, the document title remains the same as the last page you were on. This is quite confusing if you look through your tab's browsing history. For example, you might see something like:

* (newest)
* std::cmp::Eq - Rust
* std::borrow::Borrow - Rust
* std::borrow::Borrow - Rust
* (oldest)

However, the second entry takes you to the page "Results for eq". The title of that page should also be "Results for eq".

**Comment by Aatch** [comment]
Agreed, I often end up going back to a search page because it didn't look like one in the list.
