### ISSUE TITLE
Global is external, but doesn't have external or weak linkage! issue with codegen-units on rust beta

### ISSUE THREAD

**Issue by daboross** [rust-lang/rust#26379]
When using codegen-units = 4 in Cargo.toml in rust 1.1-beta.3, I get the following error compiling.

Output: https://gist.github.com/daboross/0bf54724a6999b24090f

It does work correctly in the latest nightly, but this may be something which needs backporting at one point or another if that isn't already planned?

**Comment by alexcrichton** [comment]
Thanks for the report! We're probably not going to backport changes like this (they're somewhat invasive), however, so I'm going to close this for now.

**Comment by daboross** [comment]
sounds good!
