### ISSUE TITLE
Documentation for Clone lists incorrect implementation definitions

### ISSUE THREAD

**Issue by Nashenas88** [rust-lang/rust#26384]
The documentation for `Clone` states that the first implementor is `Wrapping`:
`impl<T> Clone for Wrapping<T> where T: `***`Clone + Clone`***

`Range` is even more interesting:
`impl<Idx> Clone for Range<Idx> where Idx: `***`Clone + Clone + Clone`***

I would think that these should be documented as `impl<T> Clone for Wrapping<T> where T: Clone` and `impl<Idx> Clone for Range<Idx> where Idx: Clone`, respectively.

**Comment by steveklabnik** [comment]
I _believe_ this is a duplicate, but can't quite find it.

It's certianly something strange with `Clone`.

**Comment by Aatch** [comment]
@steveklabnik this seems like 3 issues, really:

1. Deriving produces duplicate bounds.
2. The compiler doesn't de-duplicate them later.
3. Rustdoc doesn't de-duplicate them.

Ideally, the deriving code shouldn't be generating the duplicates (and conversion with @huonw suggests that it's just left-over code from an experiment with a different deriving technique). The other two cases would be nice to fix too though.

**Comment by Nashenas88** [comment]
@steveklabnik, I also thought someone *must* have noticed before, but I also didn't have any luck finding an existing bug. I thought it would be better to find it, and if it truly was a duplicate, it would be easy to just class.

**Comment by Nashenas88** [comment]
Sorry, I accidentally clicked "close" instead of "cancel". @steveklabnik, I also thought it would be a duplicate, but I spent quite some time searching for an existing one with no luck. I filed it in case it was one of those where everyone thought it was filed, but wasn't.

**Comment by alexcrichton** [comment]
I think the dupe we're searching for is https://github.com/rust-lang/rust/issues/25022, so closing in favor of that.
