### ISSUE TITLE
Clarify cast rules (tracking issue for RFC 1052)

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#26391]
Much of the implementation work for rust-lang/rfcs#1052 has been done, but there remain some corner cases to fix:

- [ ] Casts between raw pointers to different traits are accepted but should not be (e.g. http://is.gd/1jCOSz)
- [ ] Double-check other cases, ensure adequate tests exist

**Comment by nikomatsakis** [comment]
triage: P-high -- I'm giving this high priority since accepting casts that we ought not to is a backwards compatibility risk, though it is mitigated by the fact that afaik the illegal casts yield an ICE (but I haven't done exhaustive testing)

**Comment by arielb1** [comment]
The newly-illegal casts shouldn't be ICE-s (I mean, on nightly). Casts on stable are just randomly ICE-ey.
