### ISSUE TITLE
io::Error's Debug implementation for the Os variant should display more information

### ISSUE THREAD

**Issue by reem** [rust-lang/rust#26408]
`Error { repr: Os(num) }` yields practically no information, and to even figure out what type of error occurred a user has to go run another rust script to use the Display implementation on an error with that os error code. It's not a good UX.

**Comment by reem** [comment]
The Debug impl is used quite often, especially through unwrap.

**Comment by arielb1** [comment]
You can look up the error code via `strerror` (e.g. `python -c 'print __import__("os").strerror(24)'`). In fact on windows the standard way to report an error is via its status.

**Comment by reem** [comment]
I appreciate the tip, but still consider this is a serious UX problem since I really shouldn't need python to conveniently find out what kind of error I'm dealing with.
