### ISSUE TITLE
Return expressions without a semicolon compile

### ISSUE THREAD

**Issue by pmarcelll** [rust-lang/rust#26425]
My "investigation": https://github.com/rust-lang/rust/issues/17257#issuecomment-113206852

Test case:
```rust
fn foo() -> i32 {
    return 1 // no semicolon
}

fn main() {
    println!("{}", foo());
}
```
This compiles, but the [reference](https://doc.rust-lang.org/reference.html#return-expressions) doesn't mention, that is should.

**Comment by Aatch** [comment]
The reference also doesn't say it shouldn't. This is expected behaviour as it allows this to be valid Rust code:

```rust
match foo {

**Comment by pmarcelll** [comment]
Ok, thanks. It really makes sense now (and it makes things a bit more flexible and ergonomic), but I think it should be mentioned in TRPL.
