### ISSUE TITLE
Tracking issue for Adjust default object bounds (RFC 1156)

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#26438]
https://github.com/rust-lang/rfcs/pull/1156

**Comment by nikomatsakis** [comment]
https://github.com/rust-lang/rust/pull/26370 has landed on nightly, it implements the warnings. PR #26829 rebases the same work to beta. Once that has landed, we can modify nightly to use the newer defaults (and not issue warnings anymore).

**Comment by nikomatsakis** [comment]
I...believe this has been done and is all settled now.

**Comment by nikomatsakis** [comment]
In particular: https://github.com/rust-lang/rust/pull/27045
