### ISSUE TITLE
Valgrind shows invalid read/write when using threads

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#26442]
```rust
// valgrind-test.rs
extern crate vg;

use std::thread;
use std::sync::{Arc,Mutex};
use vg::*;

fn main() {
	let arc=Arc::new(Mutex::new(()));
	let mut threads=vec![];

	for _ in 0..1000 {
		let arc_clone=arc.clone();
		threads.push(thread::spawn(move||{*arc_clone.lock().unwrap();}));
	}

	for t in threads.into_iter() {
		t.join().unwrap();
	}
}
```

Running like this usually gets me `Invalid read`/`Invalid write` errors within 5 executions:

```
rustc <(echo) -g --crate-type rlib --crate-name vg --out-dir .
rustc valgrind-test.rs -g --extern vg=./libvg.rlib
while valgrind --soname-synonyms=somalloc=NONE --redzone-size=64 --freelist-vol=100000000 --error-exitcode=1 ./valgrind-test ; do test ; done
```

Some particularly interesting errors are at http://pastebin.com/0m346AT5

The `--soname-synonyms=somalloc=NONE` option is supposed to make valgrind work properly with statically-linked jemalloc.

It might be my imagination, but it looks like linking to the empty crate significantly increases the chance of Valgrind errors showing up, although not linking this way does not completely eliminate the errors.

Tested on Linux with rust-stable, rust-stable with debug build of libstd only, rust-nightly.

**Comment by Aatch** [comment]
Looks like it's just a missing `into_raw` in `Thread::new` on the passed closure. It looks like the windows version of the code suffers from the same issue.

**Comment by alexcrichton** [comment]
I'm somewhat wary of valgrind as it often produces false positives. @Aatch can you explain a little more what you found? There is a [`mem::forget`](https://github.com/rust-lang/rust/blob/a38e7585fc29289581e6cefcdf9e201c3d58ed14/src/libstd/sys/unix/thread.rs#L71) when the thread successfully spawns and otherwise we still have ownership of the closure so it needs to be freed (hence the lack of `into_raw`).

**Comment by Aatch** [comment]
@alexcrichton ah, I missed that, sorry.

**Comment by steveklabnik** [comment]
So is this not a bug then?

**Comment by jethrogb** [comment]
Could be related to #29106

**Comment by jethrogb** [comment]
Actually, I can no longer reproduce this, so closing.
