### ISSUE TITLE
Type inference breakage around extend()

### ISSUE THREAD

**Issue by Tobba** [rust-lang/rust#26465]
```
use std::mem::uninitialized;

fn main() {
    let mut foo = Vec::<u32>::new();
    unsafe {
    	foo.extend((0..0).map(|_| uninitialized()));
    }
}
```

This builds on stable, but not on nightly.

**Comment by Gankro** [comment]
This is expected behaviour due to the addition of `extend<Item=&T> where T: Clone` (and indeed picking the wrong default would cause UB here).
