### ISSUE TITLE
Trying to access public function with same name as private field gives confusing error

### ISSUE THREAD

**Issue by stephenmw** [rust-lang/rust#26472]
When trying to access the len of a Vec I forgot the parens. This led to an error message about using a private field which confused me. (Thanks to the IRC for helping me find the problem!)

Code:

    use std::vec::Vec;

    fn main() {
    	let xs: Vec<i32> = Vec::new();
    	xs.len;
    }

Error:

    baderror.rs:5:2: 5:8 error: field `len` of struct `collections::vec::Vec` is private
    baderror.rs:5 	xs.len;
                  	^~~~~~
    error: aborting due to previous error
    Illegal instruction

**Comment by stephenmw** [comment]
@aturon

**Comment by Ms2ger** [comment]
CC me

**Comment by Ms2ger** [comment]
Maybe fixed by #26305?

**Comment by steveklabnik** [comment]
It is not, @Ms2ger , I can confirm same error with `rustc 1.2.0-nightly (cffaf0e7a 2015-06-23)`

**Comment by Manishearth** [comment]
cc @Nashenas88 want to try looking into this?

**Comment by Nashenas88** [comment]
@Manishearth, that seems tricky. The error is correct, but maybe we could add a useful note here. I'll take a look later today.

**Comment by Nashenas88** [comment]
This looks fixable, though I think I've also found a bug in #26305. I could potentially be recommending private functions there. A common solution could fix both of these issues, but the code for this error is in librustc_privacy, and the code for #26305 is in librustc_typeck. Where should I put the fix so it's accessible by both folders?

**Comment by Nashenas88** [comment]
I was wrong, it's not so simple. Something that didn't pop into my head until later is the fact that Rust allows a struct field and a struct implementation's function to have the same name. Most languages don't allow this. I thought the code between the two could be shared, but the use cases are totally different.

I played around with the following on the playground to see what the existing behavior is:

```rust
#![feature(unboxed_closures)]
mod inner {
    pub struct Dog {
        pub x: usize,
    	pub c: Barking,
    	d: Barking,
    }
    
    impl Dog {
        pub fn new() -> Dog {
            Dog {
                x: 5,
                c: Barking,
                d: Barking,
            }
        }
        
        pub fn d() -> usize {
            3
        }
    }
    
    pub struct Barking;
    impl Barking {
        pub fn woof(&self) -> usize {
            3
        }
    }
    
    impl Fn<()> for Barking {
        extern "rust-call" fn call(&self, _: ()) -> usize {
            self.woof()
        }
    }
    
    impl FnMut<()> for Barking {   
        extern "rust-call" fn call_mut(&mut self, _: ()) -> usize {
            self.woof()
        }
    }
    
    impl FnOnce<()> for Barking {
        type Output = usize;
        extern "rust-call" fn call_once(self, _: ()) -> usize {
            self.woof()
        }
    }
}

fn main() {
    let dog = inner::Dog::new();
    let _ = dog.x();
    let _ = dog.c();
    let _ = (dog.c)();
    let _ = dog.d();
    let _ = (dog.d)();
}
```

This gives the following output on nightly: 
```
<anon>:52:17: 52:20 error: no method named `x` found for type `inner::Dog` in the current scope
<anon>:52     let _ = dog.x();
                          ^~~
<anon>:52:17: 52:20 note: did you mean to write `dog.x`?
<anon>:52     let _ = dog.x();
                          ^~~
<anon>:53:17: 53:20 error: no method named `c` found for type `inner::Dog` in the current scope
<anon>:53     let _ = dog.c();
                          ^~~
<anon>:53:17: 53:20 note: use `(dog.c)(...)` if you meant to call the function stored in the `c` field
<anon>:53     let _ = dog.c();
                          ^~~
<anon>:55:17: 55:20 error: no method named `d` found for type `inner::Dog` in the current scope
<anon>:55     let _ = dog.d();
                          ^~~
<anon>:55:17: 55:20 note: use `(dog.d)(...)` if you meant to call the function stored in the `d` field
<anon>:55     let _ = dog.d();
                          ^~~
<anon>:55:17: 55:20 note: found defined static methods, maybe a `self` is missing?
<anon>:18:9: 20:10 note: candidate #1 is defined in an impl for the type `inner::Dog`
<anon>:18         pub fn d() -> usize {
<anon>:19             3
<anon>:20         }
error: aborting due to 3 previous errors
playpen: application terminated with error code 101
```
(playground [here](http://is.gd/VJv7dQ))


If I add `&self

**Comment by Nashenas88** [comment]
FYI: I haven't been had the time to work on this issue as thoroughly as I'd have liked to. Anyone is free to pick this up.
