### ISSUE TITLE
rustdoc: broken links to `rand` from `std`

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#26471]
If you go to a place in the libstd docs that references the rand crate, such as [here](http://doc.rust-lang.org/std/primitive.f64.html#method.rand), all the links ([1](http://doc.rust-lang.org/rand/trait.Rand.html), [2](http://doc.rust-lang.org/rand/trait.Rand.html#method.rand), [3](http://doc.rust-lang.org/rand/trait.Rng.html)) are broken. Looks like they need an extra "/rand/" in the URL. The same problem occurs in the nightly docs (not sure what the correct URL is for those, though).

Since these links to trait impls are auto-generated by rustdoc, I'm assuming this is a bug in rustdoc, not just a typo in the documentation. Or it has something to do with the rand code existing in libstd but also librand.

**Comment by steveklabnik** [comment]
> Or it has something to do with the rand code existing in libstd but also librand.

I believe this is the cause. @alexcrichton any ideas?

**Comment by alexcrichton** [comment]
Ah yes this is just a private trait in the distribution, so it just needs to be marked `#[doc(hidden)]`.
