### ISSUE TITLE
rustdoc: include "pub use" re-exports in search

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#26486]
When a crate re-exports something from deep in its internal structure with "pub use", you can only find the thing at its original path. A case in point (that just happened on IRC) is searching for something like `uid_t` in the libc crate; you get the path `libc::types::os::arch::posix88::uid_t` when actually `libc::uid_t` suffices, but to know that you have to scan through the list of re-exports. Is it feasible for rustdoc to index these re-exported use paths?

**Comment by nodakai** [comment]
+1

Or, http://doc.rust-lang.org/libc/libc/types/os/arch/posix88/type.uid_t.html could have a new section on known re-exports, something like

> **Re-exports**
> 
> `libc::uid_t`

just like the **Implementors** section of traits.

**Comment by steveklabnik** [comment]
Triage: I think this is fixed? https://doc.rust-lang.org/libc/x86_64-unknown-linux-gnu/libc/struct.Dl_info.html?search=uid_t shows `libc::uid_t` first. Though maybe the structure of libc changed rather than rustdoc itself.

**Comment by steveklabnik** [comment]
Triage: still not 100% sure of the status here, maybe @GuillaumeGomez can decide if this is fixed, or a thing that we may or may not fix in the future.

**Comment by GuillaumeGomez** [comment]
They definitely are available in the search, which creates duplicates sometimes (for examples, `core` types reexported in `std`). Closing then!
