### ISSUE TITLE
Unused assignment warning when casting value

### ISSUE THREAD

**Issue by mbudde** [rust-lang/rust#26498]
```rust
fn main() {
    let mut a: u32 = 0;
    a = 5;
    println!("{}", a as i32);
}
```
warns that the value assigned to `a` is never read. ([playpen](http://is.gd/ibfhVB))

**Comment by bluss** [comment]
I think rustc is correct. It's this assignment that's never used: `= 0`, on the first line of the function.

**Comment by mbudde** [comment]
Whoops.. Sorry for the noise!
