### ISSUE TITLE
A (closing) brace is a thing

### ISSUE THREAD

**Issue by tshepang** [rust-lang/rust#26507]
We need a better word than *thing* in [book/documentation][1].

> documentation comments apply to the thing after them, and there's no thing after that last comment.

But there is indeed a thing... a closing brace.

[1]: https://doc.rust-lang.org/book/documentation.html

**Comment by bluss** [comment]
We usually call them items, and rustc does too

```
<anon>:2:22: 2:23 error: expected item after attributes
<anon>:2     #[allow(warnings)]
```

**Comment by tshepang** [comment]
Current Stable, Beta, and Nightly calls them `ident`

**Comment by Aatch** [comment]
@tshepang and thats the issue. Most of the time doc comments must be followed by an item, except when the doc comment is in an enum or a struct definition. In which case the parser expects an ident in both cases, but that's just a parsing thing. In reality it expects a variant for the enum and a field for the struct.

So we need a word that somehow covers "item", "variant" and "field". "Doc-commentable node" is the only truly accurate description and apart from being rather circular doesn't exactly roll off of the tongue.

**Comment by tshepang** [comment]
@Aatch I'd be happy with "expected item, variant, or field after comment" :)

**Comment by steveklabnik** [comment]
I agree that 'thing' isn't optimal, but this isn't reference material, and I'm not sure that expanding to that mouthful increases clarity.

**Comment by steveklabnik** [comment]
Yeah, after thinking about this more, given that the book isn't exactly a reference, I think this is fine.
