### ISSUE TITLE
bad option flag

### ISSUE THREAD

**Issue by fernandezpablo85** [rust-lang/rust#26523]
shouldn't this be `--help -h` instead of `--help -v`? 

https://github.com/rust-lang/rust/blob/e4efb47b9d23a96ff4684df80360bbed0ec68bc9/src/librustc_driver/lib.rs#L514

**Comment by steveklabnik** [comment]
```
$ rustc --help -h
error: Option 'help' given more than once.
```

?

**Comment by fernandezpablo85** [comment]
perhaps that's not the line, I mean that running:

`$ rust`

outputs a lot of stuff and lastly:

![screen shot 2015-06-23 at 5 18 10 pm](https://cloud.githubusercontent.com/assets/28029/8316221/f252fdbe-19cb-11e5-8e9e-8ce064e068af.png)

in the "usage" message, it should read `--help -h` instead of `--help -v`, since `-v` is a different flag.

**Comment by sfackler** [comment]
`--help -v` prints "verbose help" - more options than just `--help` does.

**Comment by fernandezpablo85** [comment]
Oh, my bad, I though `-v` was the shorthand of `--help`, like these cases:

![screen shot 2015-06-23 at 5 26 08 pm](https://cloud.githubusercontent.com/assets/28029/8316384/fe600326-19cc-11e5-9f08-904451e866eb.png)

**Comment by nagisa** [comment]
I doubt this is actionable, unless you have an idea how the presentation could be changed so it is not ambiguous.

**Comment by steveklabnik** [comment]
Yes, this isn't really. It's 'verbose help,' and other programs use this pattern as well.
