### ISSUE TITLE
TcpListener::bind broken under Windows 7

### ISSUE THREAD

**Issue by mohtar** [rust-lang/rust#26543]
Creating a TCP listener socket will result in error under Windows 7. Minimal test case:

```rust
fn main() {
    use std::net::TcpListener;
    let listener = TcpListener::bind("127.0.0.1:8000").unwrap();
}
```

This will produce an error with code 10041 (`WSAEPROTOTYPE`).

This was tested on stable Rust (1.0.0).

After a bit digging, turns out [this particular piece of code](https://github.com/rust-lang/rust/blob/a59de37e99060162a2674e3ff45409ac73595c0e/src/libstd/sys/windows/net.rs#L82-L84) might be the cause of the breakage. According to the Winsock docs, The `WSA_FLAG_NO_HANDLE_INHERIT` flag is [supported on at least Windows 7 *SP1*](https://msdn.microsoft.com/en-us/library/windows/desktop/ms742212%28v=vs.85%29.aspx), so running on vanilla Windows 7 would not work and would apparently break your program.

**Comment by sfackler** [comment]
cc @retep998 @alexcrichton

**Comment by nagisa** [comment]
Might be similar to https://github.com/rust-lang/rust/issues/26518.
