### ISSUE TITLE
Remove char::to_titlecase?

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#26555]
Converting a string to titlecase requires a word-breaking algorithm, which std does *not* provide. We do have the method for converting a single char to titlecase, if one can identify the first char of a word. This method requires a few kb of lookup tables.

We might want to consider whether its wise to ship one without the other. This is marked for stabilization in 1.2 so we need to decide soon.

cc @SimonSapin @alexcrichton @aturon

**Comment by alexcrichton** [comment]
> This is marked for stabilization in 1.2 so we need to decide soon.

[The method is marked as unstable](https://github.com/rust-lang/rust/blob/4757d9bcc41ca59b6d52bd85d57faab0b71802e9/src/librustc_unicode/char.rs#L495-L497) so I'm fine just deleting it, I don't think it's marked to be stable.
