### ISSUE TITLE
docs: std::slice::from_raw_parts() does not mention that p must be non-null even for zero length slices

### ISSUE THREAD

**Issue by jmesmon** [rust-lang/rust#26552]
Link to the docs in question: https://doc.rust-lang.org/nightly/std/slice/fn.from_raw_parts.html

**Comment by Gankro** [comment]
Is there *any* API that accepts a null raw pointer?

**Comment by bluss** [comment]
What about ptr::copy if the count is zero?

**Comment by nagisa** [comment]
@Gankro transmute does :)

```rust
println!("{:?}", unsafe { 
    ::std::mem::transmute::<*const u8, Option<&u8>>(::std::ptr::null()) 
});
```

**Comment by Gankro** [comment]
@nagisa I suppose I implicitly meant "explicitly accepts a pointer, and not some opaque T"
