### ISSUE TITLE
Rename rustc_unicode

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#26554]
Besides this (recently-renamed) library, all `rustc_*` crates are _outside_ of the std facade. Every time I see this crate now I am confused of its role. If we don't want to take the `unicode` name then let's pick a different naming scheme that doesn't collide with the existing. Maybe `std_unicode`.

**Comment by liigo** [comment]
It's not a fully function completed Unicode library, name it `foo_unicode`
will confuse people. Especially, std_unicode implying
standard/official/default unicode. Perhaps we should name it `chars` or
else, avoiding 'unicode'.

**Comment by frewsxcv** [comment]
Opened a PR for this: https://github.com/rust-lang/rust/pull/38049.
