### ISSUE TITLE
Assignment to field of tuple literal is no-op

### ISSUE THREAD

**Issue by eefriedman** [rust-lang/rust#26557]
Testcase:
```rust
fn main() { 
    let a = 1;
    (a,2).0=2;
    assert_eq!(a, 1);
}
```

This currently compiles/runs without any diagnostics... I think this should probably be a compile error.

**Comment by petrochenkov** [comment]
Similar example:
```
struct S { s: u8 }
fn main() {
    S{s: 19}.s = 10;
}
```

(An equivalent example doesn't compile in C++ because they have value category (rvalueness) propagated through field access) 
```
struct S { char s; };
int main()
{
    S{19}.s = 10;
}
```

**Comment by arielb1** [comment]
We currently always consider fields to be lvalues - I'm not sure this is really a bug.

**Comment by eefriedman** [comment]
Even if we decide the typechecker's weird definition of an lvalue is correct, we would want a lint for assignments which are trivially meaningless.

**Comment by barosl** [comment]
Isn't the code above like

```python
a = 1
{'x': a}['x'] = 2
assert a == 1
```

in Python? I would say this is a valid code.

Something like a dead code lint might be good to have, though.

**Comment by sanxiyn** [comment]
Implemented in Clippy.
