### ISSUE TITLE
Trait information is discarded

### ISSUE THREAD

**Issue by yongqli** [rust-lang/rust#26564]
I would expect this to compile, but it doesn't. Is this intentional? It seems that `M2` discards the `f64: Mul<Self, Output=Self>` constraint.

    use std::ops::{Mul};

    pub trait M: Sized where f64: Mul<Self, Output=Self> {
    }

    pub trait M2: M {
        fn f(self, a: f64) -> Self {
            a * self
        }
    }

Error is:

    error: the trait `core::ops::Mul<Self>` is not implemented for the type `f64` [E0277]
    <anon>:11         a * self

**Comment by arielb1** [comment]
Non-supertrait predicates (i.e. predicates not of the form `Self: Trait<..>`) are not automatically elaborated. You have to add them manually:
```Rust
use std::ops::{Mul};

pub trait M: Sized where f64: Mul<Self, Output=Self> {
}

pub trait M2: M
        where f64 : Mul<Self, Output=Self> // <- ADDED
{
    fn f(self, a: f64) -> Self {
        a * self
    }
}

fn main() {}
```

**Comment by yongqli** [comment]
Should this be an RFC? Because it's quite tedious to repeat things the compiler already knows about.

**Comment by steveklabnik** [comment]
Yes, this is currently expected behavior (at least, as I understand it) and would require an RFC to change.
