### ISSUE TITLE
spurious "shadowed label name" warning

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#26570]
This [playpen](https://play.rust-lang.org/?gist=2b40a6af0322f84860a0&version=nightly) has an outer loop called `'outer` with two inner loops, one _after_ the other, both called `'inner`. The warning says the name `'inner` is shadowed, but it seems like it really isn't, since you can't refer to a loop's label after the end of the loop.

**Comment by frewsxcv** [comment]
Minimal example:

```rust
fn main() {
    'outer: while false {}
    'outer: while false {}
}
```

[Playpen link for the code above](http://is.gd/1uhHrO)

**Comment by Eljay** [comment]
This seems like intended behaviour, see #24162.

**Comment by durka** [comment]
Ah, future proofing! Makes sense, thanks.
