### ISSUE TITLE
nightly docs claim impl of both Send and !Send for Rc.  (etc for Sync)

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#26573]
The stable docs had a bug where they claimed that `Rc` implements Send and Sync.

The nightly docs are better, in that now they claim that `Rc` implements `!Send` and `!Sync`... unfortunately, they continue to also claim that `Rc` implements `Send` and `Sync`.

 * https://doc.rust-lang.org/nightly/std/marker/trait.Send.html

 * https://doc.rust-lang.org/nightly/std/marker/trait.Sync.html

cc @alexcrichton

**Comment by jooert** [comment]
Triage: This seems to be fixed now. However the docs still state three times that `Rc` implements `!Send` and `!Sync` (see #25061).

**Comment by alexcrichton** [comment]
Indeed!
