### ISSUE TITLE
Obsolete the --disable-elf-tls configure option

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#26581]
This option was added to support OSX 10.6, but it's not ideal as it requires that a separate toolchain of Rust is downloaded to compile Rust code for Firefox on OSX. Ideally our support would look something like this:

* The compiler recognizes the "standard method" of specifying that OSX 10.6 is being targeted (not the current version). I believe that this is an environment variable?
* The compiler will then generate an appropriate `#[cfg]` when this is set to allow the crate to know that it's targeting 10.6 (or whatever the relevant OSX target is)
* The standard library is then compiled against 10.6 *always*
* The macros in the standard library will then select the "best implementation" based on the context they're built into.

This will incur a perf hit for the standard library itself, but it would allow us to go back to "one distribution works everywhere" which is much nicer than "go build a separate copy of Rust to work on 10.6".

cc @rillian

**Comment by rillian** [comment]
For Firefox we use ```MACOSX_DEPLOYMENT_TARGET=10.6``` in the environment. This is supported by clang, and overridden by the command line -mmacosx-version-min switch.

I guess that would become #[cfg(macosx_deployment_target)] or maybe #[cfg(target_version)].

```man
MACOSX_DEPLOYMENT_TARGET
           If -mmacosx-version-min is unspecified, the default deployment target
           is read from this environment variable.  This option only affects
           darwin targets.
```

To match clang's behaviour here rustc would include two versions of the standard library and selectively link to the one with or without TLS based on this variable. This is still a step in that direction, though, so I'm fine with the proposed change. "One distribution" is definitely better for our use in Firefox.
