### ISSUE TITLE
AMD CodeXL always detects a segfault when running Rust code on Windows

### ISSUE THREAD

**Issue by tomaka** [rust-lang/rust#26590]
I had already reported this problem in #15644 but it was ignored. I'm reopening an issue for this.

When running any Rust program inside AMD CodeXL, a second-chance exception is immediatly detected ([see screenshot](http://i.imgur.com/pXkyXTx.png)). As I said in #15644 it used to work at some point in the past.

This happens even with an empty Rust program (with an empty `main`).

To be sure, I tried running CodeXL with a C program compiled with MinGW, and it works perfectly fine.

**Comment by nagisa** [comment]
Is there any way to see backtrace at the time of exception?

**Comment by tomaka** [comment]
I don't think so :-/

**Comment by tomaka** [comment]
This doesn't happen with programs compiled with the MSVC nightly.

**Comment by brson** [comment]
Still a bug?

**Comment by tomaka** [comment]
AMD CodeXL only runs if you have an AMD GPU, and unfortunately I have changed my hardware about a year ago. Therefore I can't check anymore.

**Comment by steveklabnik** [comment]
Then, let's give this a close.

If anyone has this issue and can reproduce, please let me know, and we'll reopen. Thanks!
