### ISSUE TITLE
liballoc: try jemalloc as system allocator if --disable-jemalloc

### ISSUE THREAD

**Issue by jbeich** [rust-lang/rust#26592]
FreeBSD comes with jemalloc in libc used for `malloc()` et al. Non-standard API is exposed via `<malloc_np.h>`. It maybe worth to use system version if the version bundled with rustc is compatible. Probably, only by default downstream in the port.

Pros:
- Doesn't shadow system alloc functions for debugging/security
- Better tuned/tested on non-Tier1 platforms (powerpc?)
- Easier to upgrade/replace/hack jemalloc system-wide
- Less confusion with memory reporting e.g.,
  `$ MALLOC_CONF=stats_print:true ./any-rust-app`
  `$ JE_MALLOC_CONF=stats_print:true ./any-rust-app`
- Slightly less memory usage in rust apps

Cons:
- Rust-specific tunning may affect non-native libs (is it bad?)
- Compatibility shims for earlier versions (3.6.0 minimal?)
- Minor API difference:
  - No `je_` prefix in functions, variables
  - `<malloc_np.h>` vs. `"jemalloc.h"`

**Comment by steveklabnik** [comment]
Triage: no real changes here. We have been talking about punting on jemalloc entirely, but that's nowhere near decided yet.

**Comment by Mark-Simulacrum** [comment]
I'm not quite sure what this is suggesting. I think it wants us to pretend the system allocator is jemalloc if --disable-jemalloc? But I'd expect that to be transparent to us (whether the systema alloc is jemalloc or not we should still call the same functions, I think -- not certain, though.) On the other hand, it's possible this is asking that when the APIs are available then we should compile with a system-provided jemalloc. That seems rather hard. Either way, I don't think this is something we'd look to implement quite right now. If you're interested, I'd file a thread on internals for discussion!
