### ISSUE TITLE
Docs for trait implementations should show where the function bodies are located 

### ISSUE THREAD

**Issue by patrickjm** [rust-lang/rust#26608]
Example: say you want to call `read_to_string` on some third party HTTP `Response` that implements `std::io::Read`. Looking at the documentation:
![yelom8n](https://cloud.githubusercontent.com/assets/4460805/8369187/9000ce32-1b7b-11e5-80f9-d446ef7b903b.png)
Unless you went to the [std documentation for Read](https://doc.rust-lang.org/nightly/std/io/trait.Read.html), there is no indication that the `read_to_string` function is actually located in a different place (`std::io`) than the `read` function (which is in the `Response` module).

This makes figuring out which things to `use` in your Rust code a considerably more awkward process. Perhaps there could be a way to better display this in the documentation?

**Comment by steveklabnik** [comment]
You're referring to the source location? I'm not quite sure what you mean about not being in the same place.
