### ISSUE TITLE
Improve error message "incorrect close delimiter" when none are open

### ISSUE THREAD

**Issue by jruderman** [rust-lang/rust#26607]
}

It just says "incorrect close delimiter". It should be more specific: no delimiters were open, so the problem is definitely that I forgot to close something earlier in the file.

https://github.com/rust-lang/rust/blob/a2f2a647633505fa83bcd9644d296ad529ebac41/src/libsyntax/parse/parser.rs#L2493

**Comment by BigBoneDaddy** [comment]
@jruderman That is very confused!

**Comment by birkenfeld** [comment]
Now says "unexpected close delimiter", which I think is good enough. Can be closed?
