### ISSUE TITLE
Broken src link in Servo docs

### ISSUE THREAD

**Issue by jruderman** [rust-lang/rust#26606]
http://doc.servo.org/msg/constellation_msg/constant.SUPER.html

The "src" link at the top goes to the incorrect URL:

    http://doc.servo.org/src/msg/%3Cbitflags%20macros%3E.html#7-8

**Comment by steveklabnik** [comment]
Can you please file this against https://github.com/servo/servo instead? This tracker is just for Rust itself. Thanks!

**Comment by jdm** [comment]
This is a bug in rustdoc afaict.

**Comment by steveklabnik** [comment]
Ah! Sorry about that @jruderman

**Comment by frewsxcv** [comment]
Might be related to #26560

**Comment by BigBoneDaddy** [comment]
@steveklabnik No problems Steve mistakes happen and we move on!
