### ISSUE TITLE
msvc: Support a i686-pc-windows-msvc host compiler

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#26602]
We should provide nightlies for a i686-pc-windows-msvc host compiler (much in the same way we have a x86_64-pc-windows-msvc host compiler). Unfortunately there is currently a bug in LLVM preventing us from doing so, so the bootstrap aborts at libsyntax because of this bug: https://llvm.org/bugs/show_bug.cgi?id=23957

Build system support is being added in https://github.com/rust-lang/rust/pull/26601, but it's largely untested because a compiler could never be produced!

**Comment by BigBoneDaddy** [comment]
That LLVM bug status now RESOLVED FIXED!

**Comment by KostaCitrix** [comment]
Now that the llvm bug is closed, what in what rough timeline can we expect an i686-pc-windows-msvc triple?

I don't want to be pushy, I'm just wondering whether we need to wait for an llvm release (not sure how often that happens) or what other roadblocks there might be...

Thanks in advance & keep up the great work! :)

**Comment by alexcrichton** [comment]
The LLVM bug was just one blocker for getting this compiler bootstrapped, there are likely to be a good number of other bugs (perhaps more LLVM ones) to overcome before we get to a full compiler. Hopefully soon though!

**Comment by alexcrichton** [comment]
Once https://github.com/rust-lang/rust/pull/27076 lands and new snapshots are prepared I believe that we're ready to start bootstrapping in the same manner 64-bit is doing so today.
