### ISSUE TITLE
Rust program crashes when linked with -mwindows

### ISSUE THREAD

**Issue by anfractuosity** [rust-lang/rust#26604]
I'm finding when I link my program with -mwindows, it will crash instantly 
when run

**Comment by anfractuosity** [comment]
It seems it's only when you call println! interestingly

**Comment by mitaa** [comment]
#24821 may be related.

**Comment by steveklabnik** [comment]
Yes, closing as a duplicate of that for now. If you find a non-`println!` case, let me know and we can re-open!
