### ISSUE TITLE
Rust to Emscripten

### ISSUE THREAD

**Issue by adjivas** [rust-lang/rust#26618]
Hi @all!

In this issue, I try to understand how use Rust with Emscripten and I try this:

What I want do:
```shell
$ cargo new hello --bin && cd ./hello &&  #OK
  rustc  --emit=llvm-ir ./src/main.rs  &&  #OK
  emcc -v ./src/main.ll -o ./test.html;  #FAIL
```

The output-error:
```shell
$ emcc -v main.ll -o ./src/test.html;
  INFO     root: (Emscripten: Running sanity checks)
  /opt/emscripten-fastcomp/llvm-as: main.ll:21:112: error: expected comma after getelementptr's type
  @ref978 = internal unnamed_addr constant [1 x %str_slice] [%str_slice { i8* getelementptr inbounds ([14 x i8]* @str977, i32 0, i32 0), i64 14 }]
                                                                                                               ^
  Traceback (most recent call last):
    File "/usr/bin/emcc", line 1110, in <module>
      shared.Building.llvm_as(input_file, temp_file)
    File "/usr/lib/emscripten/tools/shared.py", line 1461, in llvm_as
      assert os.path.exists(output_filename), 'Could not create bc file: ' + output
  AssertionError: Could not create bc file: 
```

Thank you in for the help that you can give.

***
About my binary versions:
```shell
$ rustc --version;
  rustc 1.2.0-dev (ae74652b4 2015-06-07)
$ cargo --version;
  cargo 0.2.0-nightly (efb482d 2015-04-30) (built 2015-04-30)
$ emcc --version;
  emcc (Emscripten gcc/clang-like replacement) 1.34.1 ()
  Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
  This is free and open source software under the MIT license.
  There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by eefriedman** [comment]
If you're going to do this, you have to, among other things, build Emscripten and Rust against the same version of LLVM.

**Comment by BigBoneDaddy** [comment]
@adjivas Why would you take strong robust language like Rust and make it run on unrobust badly typed JavaScripts?

**Comment by alexcrichton** [comment]
As @eefriedman mentioned the LLVM versions between emscripten and Rust must be the same, and even after that there's likely some extra work to be done to get things working. Emscripten currently isn't a supported platform, however, so I'd recommend opening an issue in rust-lang/rfcs if you'd like to request support as it will likely be a somewhat significant undertaking.

**Comment by adjivas** [comment]
@eefriedman, @alexcrichton, thank you for your recommendation.
@BigBoneDaddy, it's for build my projects to a true terminal's version and web's version but it's essentially by curiosity.

**Comment by BigBoneDaddy** [comment]
@adjivas Thank you for explanation! A million apologies from me to you I did not implicate that you are wrong to want what you want! Explore and dig deep my friend! Dig deep into the wild unknown of EcmaScript! :dancers: :dancer: :dancers:
