### ISSUE TITLE
Rust website does not render correctly.

### ISSUE THREAD

**Issue by Lindenk** [rust-lang/rust#26611]
When accessing http://rust-lang.org, this is what loads (http://imgur.com/olTsCyw) in both Chromium and Firefox.

I'm running Arch Linux x64. 
Window manager and compositors are bspwm and compton (although I don't expect that to make a difference).
Fonts appear to be loading correctly and no console errors are logged when loading the page. Firefox had no extensions running, and I disabled my adblocker on chromium. All other pages on the rust site also seem to load this way as well.

When opened in Midori, this is what loaded (http://imgur.com/IjtrS9W), also with no errors.

I can post more screenshots or give more information as needed.

I understand this will probably be difficult for someone else to reproduce, however I can't use the site if I can't read it, so even a work around would be appreciated.

**Comment by steveklabnik** [comment]
We've had several issues filed for this before, I wonder if they had solutions. IIRC it was even Arch...

**Comment by frewsxcv** [comment]
Relevant issue: https://github.com/rust-lang/rust/issues/24614

**Comment by Lindenk** [comment]
Ah looks like I had the same problem. I must have missed that issue when I was looking for a duplicate. Thanks!
