### ISSUE TITLE
Formatting of chars with fixed width was broken?

### ISSUE THREAD

**Issue by askobara** [rust-lang/rust#26625]
Current code gives different results on stable and nightly branches
```rust
fn main() {
    println!("{: >5} | {: >5}", 112, 0);
    println!("{: >5} | {: >5}", '.', 0);
}
```
Here is the stable:
```
  112 |     0
    . |     0
```
And here is the nightly:
```
  112 |     0
. |     0
```

**Comment by eefriedman** [comment]
Ooh, that's nasty... first guess is a regression from https://github.com/rust-lang/rust/pull/24689/files .  @SimonSapin?

**Comment by BigBoneDaddy** [comment]
@eefriedman Are you saying it is maybe problem with Display::fmt() no longer called or is it problem with ☃ in string?

**Comment by SimonSapin** [comment]
Untested fix:

```rust
impl Display for char {
    fn fmt(&self, f: &mut Formatter) -> Result {
        if f.width.is_none() && f.precision.is_none() {
            f.write_char(*self)
        } else {
            let mut utf8 = [0; 4];
            let amt = self.encode_utf8(&mut utf8).unwrap_or(0);
            let s: &str = unsafe { mem::transmute(&utf8[..amt]) };
            f.pad(s)
        }
    }
}

**Comment by alexcrichton** [comment]
triage: P-high

We're also likely to backport the fix to beta. Note that this is not broken on 1.1.0 stable but it is broken on 1.2.0.
