### ISSUE TITLE
Missing std::raw type for structs/enums ending in DSTs

### ISSUE THREAD

**Issue by reinerp** [rust-lang/rust#26628]
There's no std::raw type to represent these DSTs:

```rust
struct MyDst {
  some_header_data: u32,
  dst_part: [u8],
}

struct MyDst2 { 
  some_header_data: u32,
  dst_part: Drop,
}

enum MyDst3 {
  Option1(u32, [u8]),
  Option2(u32, Drop),
}
```

Either the existing `std::raw::Slice` and `std::raw::Trait` types should document how to be used for the above DSTs, or new types should be defined in `std::raw` for the above examples.

**Comment by eefriedman** [comment]
You can safely transmute any DST to either an std::raw::TraitObject or an std::raw::Slice; `*const ()` and `usize` are guaranteed to have the same representation.  I suppose the documentation could make that a bit more explicit, maybe?

**Comment by reinerp** [comment]
Yes, improving the documentation would help.

The type parameter `T` in `Slice<T>` is also a bit misleading here. In the case of

```rust
struct MyDst {
  some_header_data: u64,
  dst_part: [u16],
}
```

if I transmute to `Slice<u16>` I'll get:

```rust
struct Slice<u16> {
  data: *const u16,
  len: usize
}
```

but the data pointer actually points to `MyDst`, not to a `u16`. I'd consider dropping the `T` type param entirely from `Slice` and just make it:

```rust
struct Slice {
  data: *const (),
  len: usize
}
```

**Comment by steveklabnik** [comment]
Any suggestions for how to best improve the docs here? I'm not sure which approach is best, as `std::raw` isn't something I use.

**Comment by steveklabnik** [comment]
@reinerp if you have specific suggestions for the documentation, please let me know, but without those details, I can't really fix this. It'd be nice to know exactly what and where needs to improve in what way to help your understanding. Thank you!
