### ISSUE TITLE
File paths in --target are handled in a sub-par manner

### ISSUE THREAD

**Issue by Tobba** [rust-lang/rust#26639]
Currently if a file path is passed to --target it will be used as the target name. This has a few nasty side effects:
- If relative paths are used different relative paths pointing to the same file will be seen as different targets
- Relative paths pointing to _different_ files may result in a match
- If absolute paths are used the target specifications may not be moved around the filesystem without doing a full rebuild
- The path to the target specification is leaked all over the place, and target-related errors become verbose

**Comment by Tobba** [comment]
The workaround for this is using the (mostly) undocumented RUST_TARGET_PATH environment variable.

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by Mark-Simulacrum** [comment]
I'm going to close in favor of https://github.com/rust-lang/rust/issues/24666.
