### ISSUE TITLE
Inline assembly disappears from output

### ISSUE THREAD

**Issue by uzytkownik** [rust-lang/rust#26648]
It seems like bug in LLVM generator. Code

``` rust
let rip: u64;
asm!("movq %rip, %rax" : "={rax}"(rip) ::: "volatile");
```

Produces correct LLVM IR:

```
  %46 = call i64 asm sideeffect "movq %rip, %rax", "={rax},~{dirflag},~{fpsr},~{flags}"(), !dbg !4561, !srcloc !4562
```

But the output sometimes does not contain the instruction and the value of `rip` is `0x1d1d1d1d1d1d1d1d`.

**Comment by eefriedman** [comment]
Umm, I think you meant to write "leaq (%rip), %rax"?  You can't MOV out of RIP.

It's probably a bug that LLVM doesn't reject it, though.

**Comment by uzytkownik** [comment]
It looks like this is issue 22892 after all.

> Umm, I think you meant to write "leaq (%rip), %rax"? You can't MOV out of RIP.

Yes, I just didn't remembered that I cannot.

**Comment by jethrogb** [comment]
Referencing #22892

**Comment by jethrogb** [comment]
Fixed in latest nightly: https://is.gd/Q3RvxB
