### ISSUE TITLE
Configure File's Regular Expression no longer valid for newest version of Apple's LLVM

### ISSUE THREAD

**Issue by jcmiller11** [rust-lang/rust#26652]
At line 990 the Clang version checking does the following:

sed 's/.*\(version .*\)/\1/; s/.*based on \(LLVM .*\))/\1/' \

It looks like in the newest version of Apple's LLVM they removed the "based on (LLVM *)" part.  Running Clang --version returns

Apple LLVM version 7.0.0 (clang-700.0.53)

I could have submitted a simple patch to get around this, but since it looks like Apple is just going to be using their own version scheme from here on out I'm not sure how you guys would like to handle this moving forward.

**Comment by mitaa** [comment]
dup of #26292

**Comment by alexcrichton** [comment]
Thanks @mitaa!
