### ISSUE TITLE
io::Seek should implement .tell()

### ISSUE THREAD

**Issue by whitequark** [rust-lang/rust#26650]
A `file.tell()` is much nicer than `file.seek(std::io::SeekFrom::Current(0))`. Additionally, I think `.tell()` doesn't need the file to be mutably borrowed (but I'm not sure).

**Comment by alexcrichton** [comment]
Thanks for the report! Additions to the standard I/O traits, however, should go through the RFC process, so this issue should go into rust-lang/rust instead of this repo.

**Comment by alexcrichton** [comment]
Er, rust-lang/rfcs*

**Comment by whitequark** [comment]
And... you're just closing? That's not a very nice way to handle this...

Anyway, https://github.com/rust-lang/rfcs/issues/1181.
