### ISSUE TITLE
Changing a moved struct

### ISSUE THREAD

**Issue by jbornschein** [rust-lang/rust#26665]
I was very surprised that this code compiles and outputs `1`. When I try to print `a.val` after the assignment I get a compile error -- as I expected.

Assuming A has move semantics, this should IMHO never compile ... and/or, (according to my newbie mental model of move semantics) output a 2.

    struct A {
        val: i32
    }

    fn main() {
        let mut a = A{val: 1};
        let a_ = a;

        a.val = 2;
        println!("a_: {}", a_.val);
    }

**Comment by steveklabnik** [comment]
/cc @rust-lang/lang 

This isn't unsafe or anything, but we may want to change that? Or have a diagnostic of some kind?

**Comment by huonw** [comment]
Local variables are semantically memory locations on the stack, which can own values. Move semantics means that something like `let a_ = a;` moves the *value* out of `a` (into a new independent stack slot `a_`), leaving the latter as an "empty" stack slot. It's possible to reinitialise the slot (i.e. put a new value into it) and continue to use it, e.g. `a = A { val: 2 }; println!("{}", a.val);` works perfectly OK. Rust somewhat tracks the initialisation state of structs on a per-field basis but it doesn't do this fully, as demonstrated by `a.val` not working, but it could in future.

It would be unsafe if `a.val = 2` caused `a_.val` to also be `2`, as it would be a source of mutable sharing which is the thing Rust tries to control/protect against.

Closing as not-a-bug, but thanks for filing!

**Comment by jbornschein** [comment]
Thanks for the explanation!
