### ISSUE TITLE
unreachable pattern in match

### ISSUE THREAD

**Issue by kworr** [rust-lang/rust#26674]
Here I have a sample:

    fn test (x: u32, y: u32) {
      match x {
        1 => println!("1"),
        y => println!("y"),
        _ => println!("_"),
      };
    }
    
    fn main() {
      test(5, 4);
    }

It fails with "unreachable pattern" at "_" which actually is a case that should be executed. Probably a flow in statical analysis. My rust is 1.1.

**Comment by mitaa** [comment]
This code doesn't do what you think it does -> 
The second arm unconditionally binds x to a new variable (just like `let` would).

You'd have to write:
```rust
fn test (x: u32, y: u32) {
  match x {
    1 => println!("1"),
    _ if x==y => println!("y"),
    _ => println!("_"),
  };
}

fn main() {
  test(4, 5);
}
```

**Comment by dotdash** [comment]
Thanks @mitaa
