### ISSUE TITLE
make command for js and css in docs

### ISSUE THREAD

**Issue by azerupi** [rust-lang/rust#26672]
It would be really great to have a make command for when only the `js` or `css` files are modified in the docs. At the moment we have `make docs` and `make trpl` but this builds quite a lot and when no rust file has been modified it does nothing...

I have to modify a rust file (and revert it) to be able to trigger a build when I work on the `js` and `css` files.

**Comment by steveklabnik** [comment]
Triage: no change. rustbuild may or may not just fix this?

**Comment by alexcrichton** [comment]
Make's now gone, so closing.
