### ISSUE TITLE
rustdoc: Pressing back after search doesn't reset <title>

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#26673]
1. Navigate to https://doc.rust-lang.org/nightly/std/index.html
2. Type a query in the search bar (wait for results to appear)
3. Take note of the title of the search results
3. Press 'back' and notice how the title doesn't reset

**Comment by jooert** [comment]
Which browser are you using? It does work fine for me in Firefox 38 under Linux.

**Comment by frewsxcv** [comment]
Latest stable Firefox and latest stable Chrome on OSX 10.10

**Comment by filsmick** [comment]
Doesn't reset for me on OS X 10.10.2 (Yosemite), Chrome 43.0.2357.130.

**Comment by thelostt** [comment]
Doesn't reset here. Mozilla Firefox 38.0.5

**Comment by jooert** [comment]
My browser probably cached an old version, now it doesn't reset on my setup, too.

**Comment by frewsxcv** [comment]
This still happens for me, but that might be because #26732  hasn't been deployed yet

**Comment by Gankro** [comment]
Should have been deployed to nightly, but it clearly hasn't:

https://doc.rust-lang.org/nightly/std/

**Comment by Gankro** [comment]
This change just *barely* missed landing in the last nightly.
