### ISSUE TITLE
Warn that Chars iterator does not iterate "characters"

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust#26689]
The `Chars` iterator iterates over Unicode Scalar Values, but when people think about "characters" they usually mean something closer to what Unicode calls "grapheme clusters".

This leads to surprising results and thus potential errors, [for example][1]: 

    "éé".chars().count() == 3
    "🇺🇸".chars().count() == 2

I suggest adding a warning to the documentation that this iterator isn't iterating over "characters", and that users should consider using `UnicodeSegmentation::graphemes` iterator instead.

[1]: https://play.rust-lang.org/?code=fn%20main()%20%7B%0A%20%20%20%20println!(%22%7B%7D%22%2C%20%22%C3%A9e%CC%81%22.chars().count())%3B%0A%7D%0A&version=nightly

**Comment by steveklabnik** [comment]
Rust's `char` type is a unicode scalar value, and its documentation does currently say 'codepoints', explicitly: http://doc.rust-lang.org/stable/std/primitive.str.html#method.chars

**Comment by pornel** [comment]
The documentation is technically correct, but I think insufficient to prevent users from falling into a trap.

The difference between Unicode codepoint and a character is subtle and tricky, and to make it worse in most cases (and all examples in Rust documentation) it _appears_ to be the same thing.

The documentation shows only simple cases where one codepoint is one grapheme cluster, which—along with the name of the `char` type—could lead users to wrongly assume that codepoints are characters.

**Comment by steveklabnik** [comment]
Yeah, I guess what I meant was "here's what we have, what specifically could improve?"

A PR would be a great way to workshop it :)

**Comment by steveklabnik** [comment]
@pornel are you still persuing a PR, or should I write something?

**Comment by pornel** [comment]
Sorry, I've been a bit ill. It's still on my todo list.

**Comment by steveklabnik** [comment]
It's all good! Feel better. I have other work I can do, was just curious.
