### ISSUE TITLE
Default associated types defined in terms of other associated types don't work.

### ISSUE THREAD

**Issue by michaelsproul** [rust-lang/rust#26680]
I was trying to do something like this:

```rust
pub trait Thing {
    type Key;
    type Value;
    type KV = (Self::Key, Self::Value);

    fn get_key(kv: Self::KV) -> Self::Key {
        kv.0
    }
}

struct U32Thing;
impl Thing for U32Thing {
    type Key = u32;
    type Value = u32;
}

fn main() {
    println!("{}", U32Thing::get_key((45, 0)));
}
```

It fails on nightly with the following message:

```
$ rustc -V
rustc 1.3.0-nightly (faa04a8b9 2015-06-30)
$ rustc test.rs
test.rs:7:9: 7:13 error: attempted tuple index `0` on type `<Self as Thing>::KV`, but the type was not a tuple or tuple struct
test.rs:7         kv.0
                  ^~~~
error: aborting due to previous error
```

My intention was for the `Self::KV` type to act as a local type alias (typically not override by implementers). From the [RFC][rfc] I got the impression that this should be supported:

> We deal with this in a very simple way:
> * If a trait implementor overrides any default associated types, they must also override all default functions and methods.
> * Otherwise, a trait implementor can selectively override individual default methods/functions, as they can today.

[rfc]: https://github.com/rust-lang/rfcs/blob/master/text/0195-associated-items.md#defaults

**Comment by arielb1** [comment]
That part of the RFC wasn't yet implemented.

**Comment by arielb1** [comment]
This would be a [breaking-change], so I think we missed it.

**Comment by michaelsproul** [comment]
> That part of the RFC isn't yet implemented.

Ah yes, you're right. We don't have the default type/default method interaction at all:

```rust
pub trait Thing<'a> {
    type X = &'a str;

    fn foo(x: Self::X) -> String {
        x.to_string()
    }
}

struct Impl;
impl<'a> Thing<'a> for Impl {}

fn main() {
    println!("{}", Impl::foo("wow"));
}
```

```
$ rustc test.rs
test.rs:5:11: 5:22 error: no method named `to_string` found for type `<Self as Thing<'a>>::X` in the current scope
test.rs:5         x.to_string()
                    ^~~~~~~~~~~
test.rs:5:11: 5:22 note: the method `to_string` exists but the following trait bounds were not satisfied: `<Self as Thing<'_>>::X : core::fmt::Display`
error: aborting due to previous error
```

You're also right about it being a breaking change, in the example above, adding the `Display` bound allows it to compile. Overriding `X` in an implementation then allows `foo` to keep working without redefinition, which would be broken with the new/RFC rules.

**Comment by michaelsproul** [comment]
I'm satisfied this won't work, closing.
