### ISSUE TITLE
Permissions in the source tarball

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/rust#26685]
Currently, the files in the source tarball have permissions 600, and 700 for directories. Shouldn't it be 644 and 755 ? I'm packaging the sources for Archlinux, and I need to change the permissions for the files to be world-readable.

Tested : https://static.rust-lang.org/dist/rustc-1.1.0-src.tar.gz

**Comment by alexcrichton** [comment]
cc @brson

**Comment by brson** [comment]
Yes, that sounds right. We've had several problems with the permissions in the tarballs. @Yamakaky if you can figure out how to get them to come out right please do.

**Comment by hexsel** [comment]
Looks like a dupe of https://github.com/rust-lang/rust/issues/25479?

**Comment by steveklabnik** [comment]
Seems so, yes.
