### ISSUE TITLE
prelude_import should be unstable?

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#26690]
cc @chris-morgan, @eddyb 

If this is a bug, we should fix it asap.

**Comment by eddyb** [comment]
@brson can the impact be estimated without merging a patch to make `#[prelude_import]` unstable?

**Comment by eddyb** [comment]
If [GitHub search](https://github.com/search?l=rust&q=prelude_import&type=Code&utf8=%E2%9C%93) is to be believed, the only uses of `#[prelude_import]` appear only in the compiler and in pretty-printed output.

**Comment by brson** [comment]
I've got a crater run of @eddyb's pr started.
