### ISSUE TITLE
internal compiler error: cannot relate bound region: ReEarlyBound(7289, TypeSpace, 0, 'a) <= ReStatic

### ISSUE THREAD

**Issue by rodolf0** [rust-lang/rust#26708]
Hit this bug converting my code from using moving to references, ie: started adding lifetime specifiers. I don't exactly know what is happening to give more context sorry.

## Meta

`rustc --version --verbose`:
rustc 1.1.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-apple-darwin
release: 1.1.0

Backtrace:
08:12:05 ~/Source/tox/src/lisp 146 $ RUST_BACKTRACE=1 cargo build
   Compiling tox v0.0.2 (file:///Users/rudolph/Source/tox)
/Users/rudolph/Source/tox/src/lib.rs:1:1: 1:1 error: internal compiler error: cannot relate bound region: ReEarlyBound(7289, TypeSpace, 0, 'a) <= ReStatic
/Users/rudolph/Source/tox/src/lib.rs:1 #![cfg_attr(feature="dynlink-eval", feature(std_misc))]
                                       ^
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /private/tmp/rust20150626-13301-uiklsd/rustc-1.1.0/src/libsyntax/diagnostic.rs:170

stack backtrace:
   1:        0x10e2752af - sys::backtrace::write::h4d34c75aaa44ebb3c2r
   2:        0x10e27dd00 - panicking::on_panic::hacede89293da7355Lgw
   3:        0x10e238f75 - rt::unwind::begin_unwind_inner::h5f5b5041038f2bdbuYv
   4:        0x10da2c16e - rt::unwind::begin_unwind::h12951405995355290391
   5:        0x10da2c0fa - diagnostic::SpanHandler::span_bug::hee7db6ae704bc5ces5B
   6:        0x10bbcba04 - middle::infer::region_inference::RegionVarBindings<'a, 'tcx>::make_subregion::h17ea3dff0f2660c8Bev
   7:        0x10bb850ca - middle::infer::equate::Equate<'a, 'tcx>.TypeRelation<'a, 'tcx>::regions::h80df655f0e10f760mnq
   8:        0x10bb87f56 - middle::ty_relate::relate_substs::h1820706976693806946
   9:        0x10bb8747e - middle::ty_relate::relate_item_substs::h5159513170405011443
  10:        0x10bbe0bfd - middle::ty_relate::super_relate_tys::h13757148578343650441
  11:        0x10bb8038a - middle::infer::sub::Sub<'a, 'tcx>.TypeRelation<'a, 'tcx>::tys::h8f36f6cbabf97f15pmx
  12:        0x10bbe5328 - middle::infer::InferCtxt<'a, 'tcx>::sub_types::h44695d59239b12f5nQy
  13:        0x10b7568e6 - check::method::probe::ProbeContext<'a, 'tcx>::consider_candidates::h2f2bc09beb104474nOh
  14:        0x10b7566cf - check::method::probe::ProbeContext<'a, 'tcx>::pick_method::hdf7aeeb8e7eebf86kKh
  15:        0x10b755aa6 - check::method::probe::ProbeContext<'a, 'tcx>::pick_core::hd60323c5030c3e6beFh
  16:        0x10b74c72c - check::method::probe::probe::closure.31708
  17:        0x10b74a219 - check::method::probe::probe::hf489dbf76e38f57e5ug
  18:        0x10b705664 - check::resolve_ty_and_def_ufcs::h4cf8dd2bbed5e4c2sPr
  19:        0x10b7e7ff6 - check::check_expr_with_unifier::h13097485377881690292
  20:        0x10b7848dc - check::callee::check_call::h2e00fe4937686aa9rIl
  21:        0x10b7cc9e7 - check::check_expr_with_unifier::h4842156260799133842
  22:        0x10b70d9e3 - check::_match::check_match::closure.29465
  23:        0x10b70d771 - check::_match::check_match::hf68e92c4534b33ccBwb
  24:        0x10b7cd00a - check::check_expr_with_unifier::h4842156260799133842
  25:        0x10b7a099b - check::check_block_with_expected::h199e371e659025aeD4r
  26:        0x10b784018 - check::check_fn::h55c03a4c93607e58gFn
  27:        0x10b79b093 - check::check_bare_fn::h4d16c4fbaed14d0fTun
  28:        0x10b7a7dc7 - check::check_method_body::hd9e0a05f6bf1d003P6n
  29:        0x10b798f5b - check::CheckItemBodiesVisitor<'a, 'tcx>.Visitor<'tcx>::visit_item::h1532f96ccb32559eWrn
  30:        0x10b7993be - check::CheckItemBodiesVisitor<'a, 'tcx>.Visitor<'tcx>::visit_item::h1532f96ccb32559eWrn
  31:        0x10b7993be - check::CheckItemBodiesVisitor<'a, 'tcx>.Visitor<'tcx>::visit_item::h1532f96ccb32559eWrn
  32:        0x10b85e13a - check_crate::closure.38929
  33:        0x10b857bca - check_crate::h654cce81e26e2e52sJC
  34:        0x10b09096f - driver::phase_3_run_analysis_passes::h073a89ef997f0bf9tGa
  35:        0x10b075393 - driver::compile_input::h63cfd6f3c40c781aQba
  36:        0x10b130fd3 - run_compiler::h229c6f07beca286e75b
  37:        0x10b12e73a - boxed::F.FnBox<A>::call_box::h2635158398789933060
  38:        0x10b12dc97 - rt::unwind::try::try_fn::h7804430850065071904
  39:        0x10e305148 - rust_try_inner
  40:        0x10e305135 - rust_try
  41:        0x10b12df6d - boxed::F.FnBox<A>::call_box::h16128375054666647916
  42:        0x10e27c8ed - sys::thread::Thread::new::thread_start::haf1cc4119c0aa4b2Yjv
  43:     0x7fff8e358267 - _pthread_body
  44:     0x7fff8e3581e4 - _pthread_start

**Comment by arielb1** [comment]
Does this occur with 1.2? If it does, could you post some code that reproduces that bug?

**Comment by rodolf0** [comment]
I haven't tried 1.2. Sorry for the lack of context, I ran into this bug
with some throw away code. I thought the stack would be enough :(

- Rodolfo

**Comment by eddyb** [comment]
@rodolf0 these kinds of bugs are almost impossible to hit unless you try random things.
The only interesting bit in the stack trace is `resolve_ty_and_def_ufcs`, which means the issue occurred in a path to a method.

**Comment by steveklabnik** [comment]
Yes, unfortunately, without a code sample, there's no way to tell if this bug is fixed. If you can reproduce, please let me know!
