### ISSUE TITLE
Add support for cross compiling to the rump kernel

### ISSUE THREAD

**Issue by posix4e** [rust-lang/rust#26702]
https://github.com/rumpkernel/ is a neat project for a minimal netbsd anykernel. Since rump kernel is compatible with netbsd I've started adding support for cross compiling a amd64 netbsd rustc at 
https://github.com/rust-lang/rust/pull/26682
https://github.com/rust-lang/rust-installer/pull/38

An additional pull request needs to be filed actually get rust to use that rust-installer pull request. Once netbsd is in the tree, compiling for rump should be trivial.

**Comment by posix4e** [comment]
For some reason I can't assign this to myself

**Comment by Gankro** [comment]
Only members of the organization can be assigned an issue.

**Comment by posix4e** [comment]
Gatcha! cheers

**Comment by posix4e** [comment]
So we got the first two pull requests in, now we need to build a stage0 snapshot

fetch: x86_64-unknown-netbsd/stage0/bin/rustc
Traceback (most recent call last):
  File "/root/rust/src/etc/get-snapshot.py", line 78, in <module>
    main(sys.argv)
  File "/root/rust/src/etc/get-snapshot.py", line 60, in main
    snap = determine_curr_snapshot(triple)
  File "/root/rust/src/etc/snapshot.py", line 301, in determine_curr_snapshot
    (platform, rev))
Exception: no snapshot file found for platform netbsd-x86_64, rev 7b95b5c
/root/rust/mk/stage0.mk:17: recipe for target 'x86_64-unknown-netbsd/stage0/bin/rustc' failed
gmake: *** [x86_64-unknown-netbsd/stage0/bin/rustc] Error 1

I'm curious if this is something I can do. I certainly can cross compile one on linux

**Comment by alexcrichton** [comment]
Done! The `x86_64-rumprun-netbsd` target is suitable for this
