### ISSUE TITLE
Generic bit operations are cubersome

### ISSUE THREAD

**Issue by uzytkownik** [rust-lang/rust#26707]
I've tried to implement operations which operates on bitvectors. For example:

``` rust
fn set_bits<T, I = T>(start: I, end: I, val: T) -> T
    where T : ::core::num::Zero +
              ::core::num::One +
              ::core::cmp::Eq +
              ::core::ops::Not<Output = T> +
              ::core::ops::Sub<T, Output = T> +
              ::core::ops::Shl<I, Output = T> +
              ::core::ops::BitAnd<T, Output = T> +
              ::core::ops::BitOr<T, Output = T> +
              ::core::marker::Copy,
          I : ::core::num::One +
              ::core::ops::Add<I, Output = I> +
              ::core::ops::Sub<I, Output = I> +
              ::core::marker::Copy
{
    let len = end - start + I::one();
    let mask = (T::one() << len) - T::one();
    if !mask & val != T::zero() {
        panic!("Stored value is larger then field");
    }
    val << start
}
```

This has 2 problems:
- For relative simple operation it requires 13 trait declarations
- It panics for trivial edge case (setting all field)

The latter could be solved by using `Wrapping`. However for some reasons `Shl<usize>` is only `Shl` implemented for `Wrapping` while for all others `Shl<T>` is implemented (where `T` is the type). It would be nice if there was a `Bits<T, Index=I>` trait which would provide functions to operate on bits and `Wrapping` would use the same types as normal numerics.

**Comment by arielb1** [comment]
You can use relative paths instead of absolute paths:
```Rust
#![feature(zero_one)]

use std::ops::{Not,Add,Sub,Shl,BitAnd,BitOr};
use std::num::{Zero,One};

fn set_bits<T, I = T>(start: I, end: I, val: T) -> T
    where T : Zero + One + Eq + Not<Output=T> + Sub<Output=T> + Shl<I, Output=T> 
                   + BitAnd<Output=T> + BitOr + Copy,
          I : One + Add<Output=I> + Sub<Output=I> + Copy
{
    let len = end - start + I::one();
    let mask = (T::one() << len) - T::one();
    if !mask & val != T::zero() {
        panic!("Stored value is larger then field");
    }
    val << start
}
```

Anyway, you can create  `Bits` trait manually:
```Rust
#![feature(zero_one)]

use std::ops::{Not,Add,Sub,Shl,BitAnd,BitOr};
use std::num::{Zero,One};

trait Bits<I> : Zero + One + Eq + Not<Output=Self> + BitAnd<Output=Self>
                     + BitOr<Output=Self> + Shl<I, Output=Self> + Copy {}
impl<T, I> Bits<I> for T where
    T: Zero + One + Eq + Not<Output=T> + BitAnd<Output=T>
            + BitOr<Output=T> + Shl<I, Output=T> + Copy {}
            
pub fn set_bits<T, I = T>(start: I, end: I, val: T) -> T
    where T : Bits<I> + Sub<Output=T>,
          I : One + Add<Output=I> + Sub<Output=I> + Copy
{
    let len = end - start + I::one();
    let mask = (T::one() << len) - T::one();
    if !mask & val != T::zero() {
        panic!("Stored value is larger then field");
    }
    val << start
}

fn main() {}
```

**Comment by uzytkownik** [comment]
> Anyway, you can create Bits trait manually:

Yes, sure - that's what I intend to do for now. However:
 - operations on bits as bits seems very useful in system programming language and it seems that many people could benefit of having it in core. Currently even Haskell has it in standard library (of course the fact that language X has feature Y does not imply that Rust needs to have this feature).
 - Probably you would want to have a few extra fields such as querying for number of bits.
 - this still does not solve the Wrapping issue (as a note - it looks like `1 << x` for `x >= 64` is UB for `Wrapping<u64>` despite that documentation suggest it would be 0).

**Comment by steveklabnik** [comment]
Triage:

So, first of all, almost all of these traits have been removed.

>  It would be nice if there was a Bits<T, Index=I> trait which would provide functions to operate on bits 

This does not exist today, though.

> and Wrapping would use the same types as normal numerics.

`Shl<usize>` is the only `Shl` implemented for `Wrapping` today.

Adding new traits to the standard library usually requires an RFC, but I'm not entirely sure if the `Shl` stuff is just an oversight or not. @rust-lang/libs ?

**Comment by dtolnay** [comment]
I agree that the current approach that requires 13 trait bounds for `set_bits` is not ideal. Thanks for raising this issue!

I am not confident that we will be able to reach consensus on a solution here -- somebody will need to propose a concrete solution in an [RFC](https://github.com/rust-lang/rfcs/blob/master/libs_changes.md).
