### ISSUE TITLE
Chaining Arc<RefCell<..>> confuses borrowck.

### ISSUE THREAD

**Issue by dpc** [rust-lang/rust#26706]
http://is.gd/rNjThX

```
use std::sync::Arc;
use std::cell::RefCell;

struct A {
    a : Arc<RefCell<i32>>
}

struct B {
    b : Arc<RefCell<A>>
}

impl B {
    fn is_foo(&self) -> bool {
        *self.b.borrow().a.borrow() == 2
    }
}
```

This should compile, but it does not. Breaking the chain is a workaround.

**Comment by Aatch** [comment]
cc @pnkfelix is this an issue with destruction scopes specifically, or related to rvalue lifetimes in general?

**Comment by arielb1** [comment]
I think this is intentional well-known fallout of dropck.

**Comment by arielb1** [comment]
@Aatch 

The issue here is that the first borrow must be valid during the destruction of the second borrow, but the current destruction-scope implementation requires it to be valid for the entire `is_foo` block.

**Comment by pnkfelix** [comment]
cc #22321

**Comment by pnkfelix** [comment]
this seems like a probable dupe of #22323

**Comment by alexcrichton** [comment]
Yeah I think this is just a dupe of #22323 as well.
