### ISSUE TITLE
ICE "Type parameter `Bar/TypeSpace.0` (Bar/TypeSpace/0) out of range when substituting (root type=Some(Bar)) substs=Substs[types=[[];[];[]], regions=[[];[];[]]]"

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#26714]
I got this ICE while trying to get E0128 error with code:

```Rust
pub struct Foo<Bar=Bar>; //~ ERROR E0128
pub struct Baz(Foo);

fn main() {
    println!("Hello, world!");
}
```

I'll add the backtrace when I'll have a rust compiler (other than play.rust-lang at least).

**Comment by arielb1** [comment]
Should be fixed in nightly.

**Comment by GuillaumeGomez** [comment]
It isn't on play.rust-lang nightly version (I built with it).

**Comment by arielb1** [comment]
play.rust-lang.org is slow to update

**Comment by GuillaumeGomez** [comment]
Damn !
