### ISSUE TITLE
Internal Fulfillment Context assertion tripped, needs more investigation

### ISSUE THREAD

**Issue by jroesch** [rust-lang/rust#26721]
I'm not sure if this is a bug or not, needs further investigation. It appears that by reusing the fulfillment_cx [here](https://github.com/jroesch/rust/blob/fulfillment-context-refactor/src/librustc/middle/traits/mod.rs#L452) we incur more obligations and later trip an [assertion](https://github.com/jroesch/rust/blob/fulfillment-context-refactor/src/librustc_typeck/check/regionck.rs#L337).
    
The two possibilities I see is:
    - normalization is not actually fully happening and we have a bug else where
    - we are adding a duplicate bound into the list causing its size to change.

**Comment by steveklabnik** [comment]
Did you ever investigate further?

**Comment by jroesch** [comment]
@steveklabnik I'm currently rewriting a large chunk of the fulfillment context that I believe will make this a non-issue, but we should probably keep this open for the time being if that is okay with you?

**Comment by steveklabnik** [comment]
:+1:

**Comment by soltanmm** [comment]
@jroesch There's a [`FIXME` comment](https://github.com/rust-lang/rust/blob/dbf994bbaff214e6441a8e97df180db7b29e7189/src/librustc/middle/traits/mod.rs#L476) that references this issue at present. Is that supposed to be there?

**Comment by jroesch** [comment]
@soltanmm this is references a problem with the current fulfillment context design, where we can't re-use fulfillment contexts because they have no transactional support, this was fixed on my branch refactoring the inference engine. I'm currently trying to rebase this with https://github.com/rust-lang/rust/pull/30533, still need to touch base with Niko about it though. Was with family for my grandmother's 90th birthday that past couple days, home again and back to work.
