### ISSUE TITLE
cfg!(linux) should work

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#26726]
Currently you need cfg!(unix), but we use #[cfg(target_os="linux")]. I haven't tested, but we should make sure #[cfg(target_os="unix")] also works.

**Comment by sfackler** [comment]
`#[cfg(unix)]` and `#[cfg(windows)]` are shorthands for `#[target_family = "unix"]` and `#[target_family = "windows"]` respectively, not `target_os`.

**Comment by steveklabnik** [comment]
So this isn't a bug then?

**Comment by alexcrichton** [comment]
Ah yes this isn't a bug in the sense where it's intended to work, and we'd need an RFC to get it to work.
