### ISSUE TITLE
cannot move into irrefutable slice patterns with multiple elements

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#26736]
``` rust
let arr = [Box::new(1), Box::new(2), Box::new(3)];
let [a, b, c] = arr;
```

fails with

```
<anon>:5:13: 5:14 error: use of moved value: `arr[..]` [E0382]
<anon>:5     let [a, b, c] = arr;
                     ^
<anon>:5:10: 5:11 note: `arr[..]` moved here because it has type `Box<i32>`, which is moved by default
<anon>:5     let [a, b, c] = arr;
                  ^
<anon>:5:10: 5:11 help: use `ref` to override
```

while the following work fine:

``` rust
let arr = [Box::new(1)];
let [a] = arr;
```

``` rust

enum Dummy<T> {
    Val([T; 2]),
}
let arr = [Box::new(1), Box::new(2)];
let Dummy::Val([a, b]) = Dummy::Val(arr);
```

**Comment by arielb1** [comment]
Slice patterns are broken.

**Comment by oli-obk** [comment]
yes they are, is there any consensus on whether to report bugs and fix it or simply rewrite it from scratch?

**Comment by BigBoneDaddy** [comment]
@oli-obk Are you volunteer to rewrite it from scratch?

**Comment by steveklabnik** [comment]
Triage; no change on slice patterns

**Comment by mikhail-m1** [comment]
works with `-Z borrowck=mir`, hope it will be soon by default

**Comment by dgriffen** [comment]
This is still happening on stable as of the 1.26 release. This may cause confusion for people trying to use slice patterns since the release notes show an example of them. The only way the release notes get away with it is because they use numbers which are `Copy`.

**Comment by andersk** [comment]
These work fine as parameter patterns, so here’s an annoying but functional workaround while we’re waiting for MIR borrowck:

```rust
let arr = [Box::new(1), Box::new(2), Box::new(3)];
let (a, b, c) = (|[a, b, c]: [Box<i32>; 3]| (a, b, c))(arr);
```
