### ISSUE TITLE
Codegen bug: UnsafeCell<T: ?Sized> is declared noalias, despite it being aliasable

### ISSUE THREAD

**Issue by GBGamer** [rust-lang/rust#26748]
`fn(&UnsafeCell<i32>)` => `define internal void @and_test(%"2.core::cell::UnsafeCell<i32>"* dereferenceable(4)) unnamed_addr #1`

As you can see, no `noalias`, and, weirdly, no `nocapture`.

`fn(&UnsafeCell<[i32]>)` => `define internal void @and_test({ %"2.core::cell::UnsafeCell<[i32]>"*, i64 }* noalias nocapture dereferenceable(16)) unnamed_addr #1`

And, as you can see, there is a `noalias` and a `nocapture`.

Here, check these playpen examples out:

`UnsafeCell<i32>`: http://is.gd/vkyoUn

`UnsafeCell<[i32]>`: http://is.gd/FlOr8A

**Comment by Gankro** [comment]
This doesn't appear to repro on beta or nightly.

Problem solved?

**Comment by GBGamer** [comment]
Guess not, weird... Probably should've tested on beta and nightly.
