### ISSUE TITLE
Function pointers don't seem to be mentioned in the book

### ISSUE THREAD

**Issue by niconii** [rust-lang/rust#26746]
The fact that function pointers implement the closure traits `Fn`/`FnMut`/`FnOnce` also doesn't seem to be mentioned in either the book or the reference.

**Comment by steveklabnik** [comment]
We do mention the type, but not that they implement Fn: http://doc.rust-lang.org/book/primitive-types.html#functions

**Comment by BigBoneDaddy** [comment]
@steveklabnik Sound to me like maybe clarification be needed if @niconii confuse.

**Comment by reem** [comment]
Note that `fn` items are not actually function pointers, they share the same mechanism as closures of being anonymous types with impls of `Fn*`, they are only coercible to `fn` pointers (`fn(X) -> Y`).
