### ISSUE TITLE
The .msi installer freezes if you try to overwrite an existing Rust installation

### ISSUE THREAD

**Issue by tomaka** [rust-lang/rust#26758]
I can't belive this issue wasn't reported. Many people on IRC had this problem at the release of 1.1.

If you have the version 1.0 of Rust installed for example in `C:\Program Files\Rust`, then try to install version 1.1 to the same location, the installer will freeze forever and you have to kill it.

The problem disappears if you uninstall the previous version first.

**Comment by cybergeek94** [comment]
I'm having the opposite problem in #26765. In a non-default folder, the .msi installer just naively adds the library files to the current install, confusing `rustc` on which to use.

**Comment by brson** [comment]
Nominating because this is pretty bad.

**Comment by alexcrichton** [comment]
triage: P-medium

Would love to fix, but doesn't seem super high priority right now.

**Comment by tomaka** [comment]
I just installed the 1.9 nightly. The installer still froze, but only for about 30 seconds instead of forever.

**Comment by brson** [comment]
cc @vadimcn

**Comment by patricksjackson** [comment]
The broken update hasn't been reported since 1.1, almost two years ago. Does this still need a fix?

**Comment by Enselic** [comment]
Triage: Closing since no one said this still needs to be fixed, and the problem was reported on a now ancient version.
