### ISSUE TITLE
Nightly: thread 'rustc' panicked at 'parse_region: bad input'

### ISSUE THREAD

**Issue by justinas** [rust-lang/rust#26767]
Building justinas/fortythree@d4b377ce8d2c0ba4fd4e3c2360a308e6c122bf08 with the latest nightly (2015-07-01 at the moment) makes the compiler panic unexpectedly.

     thread 'rustc' panicked at 'parse_region: bad input', ../src/librustc/metadata/tydecode.rs:358

This is seemingly caused by the usage of `write!` macro from libcore. The code compiled fine up until nightly-2015-06-15 at least IIRC.

You can find the full backtrace [in this Gist](https://gist.github.com/justinas/bfce65c260f606ea719d).

**Comment by arielb1** [comment]
Does this reproduce on a clean rebuild?

**Comment by justinas** [comment]
Yes, tried `make clean && make` to the same effect.

**Comment by nrc** [comment]
I'm having trouble reproducing this. I tried pulling the branch you mention and running make, this didn't get quite to the end of the build process. I am missing  i386-elf-ld and couldn't figure out how to get it.

I tried creating a minimal test case with various combinations of `write!`, but couldn't repro.

@justinas could you provide a minimal test case please? Or at least a version of your project that can be built with standard Rust tools? Thanks!

**Comment by justinas** [comment]
I think I had a version mismatch between the installed rustc (through multirust) and the tree from which `libcore.rlib` was built. Updated the latter and the problem has disappeared.
