### ISSUE TITLE
f32 seen as ambiguous associated type

### ISSUE THREAD

**Issue by pfalabella** [rust-lang/rust#26760]
see http://stackoverflow.com/questions/31208465/pi-constant-is-ambiguous

``` rust
   fn main() {
        let _ = f32::consts::PI;
    }
```

fails to compile with:

``` bash
$ rustc -
<anon>:2:13: 2:28 error: ambiguous associated type; specify the type using the syntax `<f32 as Trait>::consts` [E0223]
<anon>:2     let i = f32::consts::PI;
                     ^~~~~~~~~~~~~~~
error: aborting due to previous error
```

on rust 1.0 stable and 1.1 stable

using the full path `std::f32::consts::PI;` works. The compilation error looks wrong (why is f32 an associated type)?

**Comment by jonas-schievink** [comment]
You're using the type `f32`, not the module, so rustc tries to resolve `consts` as an associated type. If you put a `use std::f32` somewhere, it works.

**Comment by pfalabella** [comment]
Yes, I probably haven't made myself very clear in the description above. 
I've noted that fully specifying the path works, but I still think "ambiguous associated type" referring to f32 is a confusing error message (I can't blame the person asking the SO question for interpreting it as "f32 is an associated type and defined in two or more traits" none of which is true).

**Comment by jonas-schievink** [comment]
That's true. The message should read something like "no associated type `consts` found" (at least this seems to be the case here). It would also help if rustc would output a list of implemented Traits that have the ambiguous associated type whenever this happens.

**Comment by bluss** [comment]
Rustc is underlining all of `f32::consts::PI`, and it should call it an associated item, not just type.

**Comment by arielb1** [comment]
And we have the wonderful comment
```Rust
// Will fail except for T::A and Self::A; i.e., if ty/ty_path_def are not a type
// parameter or Self.
```

**Comment by steveklabnik** [comment]
Triage, with the new errors:

```
error[E0223]: ambiguous associated type
 --> <anon>:2:17
  |
2 |         let _ = f32::consts::PI;
  |                 ^^^^^^^^^^^^^^^ ambiguous associated type
  |
  = note: specify the type using the syntax `<f32 as Trait>::consts`
```

ouch 😦

**Comment by Mark-Simulacrum** [comment]
The consts in the number type modules should probably be moved to associated constants. I believe we're mostly on board with this, but there's not currently an issue to my knowledge.

**Comment by abique** [comment]
I'm running into this error, this is quite ridiculous to have so much troubles just to use PI.

**Comment by eminence** [comment]
At a minimum, the `ambiguous associated type, specify the type using the syntax <f32 as Trait>::consts` error message is totally bogus and should be improved

**Comment by AliAbdullah1999** [comment]
can anyone guide me in this

**Comment by AliAbdullah1999** [comment]
105 |     let v_02 = <Vehicle as Trait>::create_vehicle{
    |                                                  ^ expected one of `.`, `::`, `;`, `?`, or an operator here
//i talked about this error above
