### ISSUE TITLE
Structs can be created via type-aliases

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#26773]
## STR

```Rust
struct S { v: u32 }
type T=S;
fn main() {
    let T { v: u } = T { v: 42 };
    println!("{}", u)
}
```

This also works with type parameters:
```Rust
struct S<T> { v: T }
type Alias<T> = S<Vec<T>>;
fn main() {
    // look at ma, no type annotations
    println!("{:?}", Alias { v: Some(4).iter().collect() }.v);
}
```

## Result

Code compiles and works.

## Expected Results

This should not compile. Actually, we may keep this for backwards-compatibility. cc @brson @eddyb

**Comment by sfackler** [comment]
Why should this not compile?

**Comment by arielb1** [comment]
@sfackler 

I think of struct literals as a resolve thing.

**Comment by tomjakubowski** [comment]
Given that this snippet works, I'd expect that the struct literal initialization would work too:

```rust
struct S<T> { v: T }

impl<T> S<T> {
    fn new(x: T) -> Self { S { v: x } }
}

type Alias<T> = S<Vec<T>>;

fn main() {
    // look at ma, no type annotations
    println!("{:?}", Alias::new(Some(4).iter().collect()).v);
}
```

**Comment by eddyb** [comment]
@tomjakubowski not exactly, `Alias::new` is shorthand for `<Alias>::new` (this is true even if you have `S` instead of `Alias`), whereas `struct` literals don't (or weren't intended to) have this property.
E.g. `Self::new(42)` works inside an `impl` but `Self { v: 42 }` doesn't.

**Comment by arielb1** [comment]
This is tested (`struct-aliases.rs`) and therefore intended behaviour.
