### ISSUE TITLE
Export fd_set in libc or libnative

### ISSUE THREAD

**Issue by dimbleby** [rust-lang/rust#26794]
This is essentially re-opening #16297.  

Per the original reporter, I'm trying to write a binding to a C network-related library and would like fd_set to be available without having to duplicate effort.

That issue was closed on the grounds that the desired function did exist, which indeed it did at the time.  But e136421 removed it.

**Comment by alexcrichton** [comment]
Thanks for the report! We typically don't keep open issue for missing exports from liblibc, but feel free to send a PR to export it!
