### ISSUE TITLE
reference: explain what "implies" means in Closure types section

### ISSUE THREAD

**Issue by tshepang** [rust-lang/rust#26793]
There are these 2 statements in [8.1.10](http://doc.rust-lang.org/reference.html#closure-types):

> `FnMut` implies `FnOnce`
> `Fn` implies `FnMut` and `FnOnce`

Is the word *implies* used correctly? What does it mean?

**Comment by steveklabnik** [comment]
It means that if you implement `FnMut`, you've also implemented `FnOnce`. It's a trait inheritance hierarchy.

**Comment by tshepang** [comment]
I was hoping a PR would close this issue @steveklabnik

**Comment by tshepang** [comment]
here goes: https://github.com/rust-lang/rust/pull/26808
