### ISSUE TITLE
comments.md doesn't know about `//!`

### ISSUE THREAD

**Issue by ErinCall** [rust-lang/rust#26801]
[The chapter on comments](http://doc.rust-lang.org/book/comments.html) discusses two types of comments: `//` comments and `///` doc comments. [The section on testing](http://doc.rust-lang.org/book/testing.html#documentation-tests) mentions a third type: `//!` module doc comments. Should src/doc/trpl/comments.md be updated to include `//!`, or have I misunderstood something?

I'd be happy to help update the docs, but I thought I should make sure I know what's going on before I start telling everyone else :)

**Comment by bluss** [comment]
The reference [lists all four (or six) syntaxes](http://doc.rust-lang.org/reference.html#comments) for doc comments. Maybe mentioning `//!` is a good idea for the book though.

**Comment by steveklabnik** [comment]
Yeah, I would not be opposed to describing `//!` in the comments section as well.

**Comment by ErinCall** [comment]
Thanks y'all! :)
