### ISSUE TITLE
Recursive constant checker needs to check types

### ISSUE THREAD

**Issue by eefriedman** [rust-lang/rust#26810]
``` rust
type A = [u8; C.0];
const C: (usize, A) = (1, [1]);
struct A2 {
    u: usize,
    a: [u8; C2.u]
}
const C2: A2 = A2{ u:1, a:[1] };
fn main() {
    println!("{:?} {:?}", C.1, C2.a);
}
```

Currently accepted without errors; I would expect an error.

**Comment by Aatch** [comment]
Whats wrong with it, other than being a bit confusing? There's no recursive dependency for the values, just a slightly odd dependency between the constant and the type of the constant. It's not actually recursive though.

The fact that it compiles and gives the expected result suggests that this isn't a bug.

**Comment by eefriedman** [comment]
Well, that particular testcase isn't fundamentally unsound by itself, I guess... it's just hard to write testcases here because const_eval is very limited at the moment.  Another testcase, which I just came up with:

```rust
trait A {
    type T;
}
impl A for [u8; 257] {
    type T = u8;
}
impl A for [u8; 1] {
    type T = u16;
}
type T = <[u8; C] as A>::T;
const C: usize = 257 as T as usize;
fn main() {}
```

Rust currently rejects this with ```non-scalar cast: `i32` as `<[u8; 257] as A>::T` ```... but clearly there's an inconsistency somewhere.  I would argue that the issue is that we should explicitly reject this because of the recursion.

If we ever support size_of or array indexing in const_eval, those will also lead to very awkward results.

**Comment by oli-obk** [comment]
```rust
const X: [u8; Y[0]] = [1, 6];
const Y: [u8; X[0]] = [2];
```

fails with 

```
<anon>:11:1: 11:30 error: recursive constant [E0265]
<anon>:11 const X: [u8; Y[0]] = [1, 6];
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<anon>:11:1: 11:30 help: see the detailed explanation for E0265
<anon>:12:1: 12:27 error: recursive constant [E0265]
<anon>:12 const Y: [u8; X[0]] = [2];
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
<anon>:12:1: 12:27 help: see the detailed explanation for E0265
error: aborting due to 2 previous errors
```

same error with `const C2: (usize, [u8; C2.0]) = (1, [1]);`
which should be identical to @eefriedman's 

```rust
type A = [u8; C.0];
const C: (usize, A) = (1, [1]);
```

which doesn't error

**Comment by eefriedman** [comment]
Here's another fun testcase:

```
#![feature(const_indexing)]
type A = [u8; C.1[0] as usize];
const C: (usize, A) = (1, [257]);
fn main(){
}
```

```
error: mismatched types [--explain E0308]
 --> <anon>:3:27
  |>
3 |> const C: (usize, A) = (1, [257]);
  |>                           ^^^^^ expected an array with a fixed size of 257 elements, found one with 1 elements
note: expected type `[u8; 257]`
note:    found type `[u8; 1]`
```

**Comment by Mark-Simulacrum** [comment]
Today, all of the examples in this issue are "unsupported cyclic reference"s, so I don't know that it's worth keeping this open, so I'm closing. Please reopen if that's the incorrect decision.
