### ISSUE TITLE
concat_idents! fails "expecting comma"

### ISSUE THREAD

**Issue by CodingAnarchy** [rust-lang/rust#26843]
Attempting to use the concat_idents! macro in some code I'm messing around with locally, and it keeps failing on compile with:

```
[matt@loki crypto]$ rustc crypto.rs 
crypto.rs:22:17: 22:71 error: concat_idents! expecting comma.
crypto.rs:22         let f = concat_idents!(token::str_to_ident(argv[1]), _encrypt);
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
```

As one can see from the code, I'm following the documentation and there IS a comma in that list.

As it's likely relevant:

```
[matt@loki crypto]$ rustc --version
rustc 1.1.0 (35ceea399 2015-06-19)
```

**Comment by eefriedman** [comment]
Granted, the diagnostic could be a bit better.  That said, what the heck are you trying to do?  `token::str_to_ident(argv[1])` is a call expression, not an identifier.

**Comment by CodingAnarchy** [comment]
I expected that to fail - overall I wanted to convert a string to an ident. Or compare an ident to a string - either would work.

However, this still fails even when I did it literally - the equivalent of `concat_idents!(foo, bar)`

**Comment by CodingAnarchy** [comment]
Correction, it looks like that was because it was including the `::`.  Ok, maybe it's just getting a hang of the odd corner cases involved with all this that's causing me to be confused.

**Comment by eefriedman** [comment]
If you're not sure how to do something in Rust, please post a question on StackOverflow or users.rust-lang.org, not here.

**Comment by CodingAnarchy** [comment]
To be fair, I didn't post this because I didn't know how to do something, but because I was discovering an error that I didn't expect or understand when trying something that seemed like it should work.

I understand there's a lot of churn and development despite the 1.1 release, so that's to be expected.  It's also new, so I'm learning as I go.  I don't find it unreasonable that this is here, even if it turns out to have wasted a bit of time.  Sorry about that.  I'll go ahead and close it now.
