### ISSUE TITLE
Associated constants should not be object safe

### ISSUE THREAD

**Issue by P1start** [rust-lang/rust#26847]
The following code compiles:

``` rust
#![feature(associated_consts)]

trait Foo {
    const FOO: u32;
}

impl Foo for () {
    const FOO: u32 = 1;
}

fn main() {
    let _: &Foo = &();
}
```

Furthermore, adding the line `<Foo>::FOO;` to `main` causes an ICE:

```
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'assertion failed: match trait_items[method_offset_in_trait] {
    ty::MethodTraitItem(_) => true,
    _ => false,
}', ../src/librustc/middle/traits/util.rs:439
```

**Comment by oli-obk** [comment]
I think the code should be legal to compile. It's impossible to get the value of `FOO` from a variable (there's no such thing as `a::FOO` where `a` is a binding of type `&Foo`).

**Comment by arielb1** [comment]
Well it shouldn't compile

**Comment by brson** [comment]
I don't know if this can lead to unsoundness or not. Correct me.

**Comment by brson** [comment]
@eddyb says no

**Comment by withoutboats** [comment]
Update on this, the example in the original post compiles today.

But this ICEs:

```rust
#![feature(associated_consts)]

trait Foo {
    const FOO: u32;
}

impl Foo for () {
    const FOO: u32 = 1;
}

fn main() {
    let _ = <Foo as Foo>::FOO;
}
```

AFAICT there are two options here:

1. Associated consts are not object safe, just like associated (static) functions.
2. Associated consts must all be specified, just like associated types.

I think its sensible to start with the first. The second makes more sense in the context of a world with const params, but the first can be extended to the second.

It might also make sense some day to allow `where` clauses on associated consts just like methods (and on associated types, for that matter, which connects in some degree with the ATC RFC).

**Comment by withoutboats** [comment]
https://github.com/rust-lang/rust/pull/41494

**Comment by gnzlbg** [comment]
Can't associated consts be part of the vtable/fat pointers?

**Comment by withoutboats** [comment]
Associated consts are inlined at compiletime, they can't have a value which is determined at runtime. This is a hard requirement for making things like const fn and const generics work.

**Comment by gnzlbg** [comment]
I think that having to write:

```rust
trait Foo {
    fn get_x(&self) -> u32;
}

trait FooC {
    const X: u32;
}

impl Foo for () {
    fn get_x(&self) -> u32 { 3 } ;
}

impl FooC for () {
    const X: u32 = 3;
}
```

instead of just:

```rust
trait Foo {
  const X: u32;
}
```

or 

```rust
trait Foo {
  const X: u32;
  fn get_x(&self) -> u32 { Self::X } 
}
```

is a pain.

> they can't have a value which is determined at runtime. 

The value is determined at compile-time, but I am talking about being able to access that value at run-time via dynamic dispatch.

**Comment by withoutboats** [comment]
The value is not determined at compile time for the virtually dispatched type `Foo` (the trait object type).

**Comment by gnzlbg** [comment]
> The value is not determined at compile time for the virtually dispatched type Foo (the trait object type).

I did not say otherwise. What I did say is that currently there is no way to access this value at run-time but there should be one.

**Comment by gnzlbg** [comment]
Maybe the problem is that traits supports associated consts, and associated consts are _values_, but traits do not support associated values.

**Comment by nifker** [comment]
Will they be object-safe in the future?
