### ISSUE TITLE
Difficult for plugins to set visibility of Items

### ISSUE THREAD

**Issue by vojtechkral** [rust-lang/rust#26851]
Even though the `vis` field of `syntax::ast::Item` is `pub`, it's pretty difficult for compiler plugins to set visibility of an item, since they tend to be passed around wrapped in `P<>`. `ExtCtxt` doesn't seem to provide any means to do it.

I had to write this horrible hack to set visibility of Items:

```
fn hack_vis(item: &mut P<Item>, vis: Visibility) {
	let item_mut = unsafe {
		&mut *::std::mem::transmute::<_, *mut Item>(&**item)
	};

	item_mut.vis = vis;
}
```

Or maybe I missed something...?
Am I supposed to create `use` statements for each item instead?
Or am I supposed to create Items by hand?

Thanks for help.

**Comment by sfackler** [comment]
You probably want to use `P::map`: https://doc.rust-lang.org/stable/syntax/ptr/struct.P.html#method.map

**Comment by vojtechkral** [comment]
Ah, yes, that's what I missed! Thanks! :smile:
