### ISSUE TITLE
Add issue references to each `#[unstable]`

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#26868]
`#[unstable]` now supports the `issue = "NNN"` field, that allows linking it to an issue here, e.g. `#[unstable(feature = "foo", reason = "bar", issue = "1234")]`. We should use it more.

The exact arrangement of which library features need issues/how those issues will be laid out is up in the air at the moment, so this issue isn't yet a call to action.

[TODO: make some sort of checklist]

cc @rust-lang/libs

**Comment by Gankro** [comment]
* [ ] all the features

**Comment by Gankro** [comment]
These are the libs team's official recommendations. Someone needs to write a script to autogenerate issues for each with these recommendations.

# Never stabilize

* core_intrinsics

* collections
* rustc_private
* rustdoc
* test
* unicode

* c_void_variant
* char_internals
* core_panic
* float_error_internals
* flt2dec
* fmt_internals
* int_error_internals
* io_error_internals
* issue_14344_fixme
* print
* rt
* set_stdio
* str_internals
* thread_local_internals

# Ready for stabilization

* append
* as_unsafe_cell
* ascii
* box_raw
* cstr_memory
* cstr_to_str
* drain
* duration
* error_downcast
* fs_mode
* hash_slice
* hasher_write
* io_error_inner
* ip_addr
* park_timeout
* process_id
* result_expect
* socket_timeout
* split_off
* str_utf16
* thread_local_state
* thread_sleep
* time
* vec_deque_retain
* wait_timeout
* wait_timeout_with

# Ready for deprecation

* bitset
* bitvec
* box_heap
* btree_b
* cmp_partial
* duration_span
* dynamic_lib
* exit_status
* fixed_size_array
* float_consts
* fnbox
* fs_time
* hash_default
* int_slice
* io
* iter_iterate
* iter_min_max
* iter_reset_fuse
* iter_to_slice
* iter_to_vec
* linked_list_extras
* map_in_place
* move_from
* mpsc_select
* owned_ascii_ext
* page_size
* ptr_as_ref
* read_and_zero
* ref_slice
* result_fold
* scan_state
* semaphore
* slice_chars
* slice_position_elem
* subslice_offset
* vec_resize
* vecmap

# Need work

* alloc
* arc_counts
* arc_unique
* arc_weak
* as_slice
* borrow_state
* btree_range
* catch_panic
* cell_extras
* clone_from_slice
* coerce_unsized
* collections_bound
* collections_range
* convert
* core
* core_char_ext
* core_float
* core_prelude
* core_simd
* core_slice_ext
* core_str_ext
* deque_extras
* dir_builder
* error_type_id
* filling_drop
* float_extras
* float_from_str_radix
* fmt_flags
* fmt_radix
* fs_canonicalize
* fs_walk
* get_type_id
* hashmap_hasher
* heap_api
* into_cow
* ip
* iter_arith
* iter_cmp
* iter_order
* lookup_addr
* lookup_host
* nonzero
* num_bits_bytes
* oom
* open_options_ext
* path_components_peek
* path_ext
* path_prefix
* path_relative_from
* pattern
* rand
* range_inclusive
* raw
* rc_counts
* rc_unique
* rc_weak
* reentrant_mutex
* reflect_marker
* scoped_tls
* slice_bytes
* slice_concat_ext
* slice_extras
* static_condvar
* static_mutex
* static_rwlock
* step_by
* step_trait
* str_char
* str_escape
* str_match_indices
* str_parse_error
* tcp
* udp
* unique
* unsize
* utf8_error
* vec_push_all
* wrapping
* zero_one

**Comment by aturon** [comment]
We don't want issues for any of these except the "Needs Work" category -- for the rest, we should just make PRs to stabilize or deprecate.

Also, for the ones in Needs Work, each issue should give detail about the uncertainty in the design. Not sure that we should create the issues in bulk, rather than creating them hand-in-hand with these details (and grouping together as appropriate).

Finally, we'll want some scheme for tagging these so that the subteam report script can pick them up for its dashboard.
