### ISSUE TITLE
ICE compiling "solicit" crate

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#26862]
Sorry about the giant backtrace. This is attempting to compile [solicit](https://github.com/mlalic/solicit).

    nri@nri-desktop:~/software/nri/solicit$ RUST_BACKTRACE=1 cargo build --verbose
           Fresh libc v0.1.8
           Fresh log v0.3.1
       Compiling solicit v0.4.0 (file:///home/nri/software/nri/solicit)
         Running `rustc src/lib.rs --crate-name solicit --crate-type lib -g --out-dir /home/nri/software/nri/solicit/target/debug --emit=dep-info,link -L dependency=/home/nri/software/nri/solicit/target/debug -L dependency=/home/nri/software/nri/solicit/target/debug/deps --extern hpack=/home/nri/software/nri/solicit/target/debug/deps/libhpack-37abaf37ec66685c.rlib --extern log=/home/nri/software/nri/solicit/target/debug/deps/liblog-8a6aba167994951e.rlib`
           Fresh hpack v0.2.0
    ../src/libcore/iter.rs:804:35: 804:42 error: internal compiler error: Encountered errors `[FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<http::session::DefaultStream as core::cmp::PartialOrd>)),depth=1),Unimplemented)]` fulfilling during trans
    note: the compiler unexpectedly panicked. this is a bug.
    note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
    thread 'rustc' panicked at 'Box<Any>', ../src/libsyntax/diagnostic.rs:176
    
    stack backtrace:
       1:     0x7f1891a2f47e - sys::backtrace::write::h15a4b63788f03a48Lqs
       2:     0x7f1891a37124 - panicking::on_panic::hb2be65ef48ba45c7x8w
       3:     0x7f18919f9ebe - rt::unwind::begin_unwind_inner::h7715c8393aa9ab22bOw
       4:     0x7f188edf1e7c - rt::unwind::begin_unwind::h3650488909509931796
       5:     0x7f188edf1e1b - diagnostic::SpanHandler::span_bug::haaf8ccf79acf272fl5A
       6:     0x7f188f8d88e8 - session::Session::span_bug::h467417c9950ae9aee1s
       7:     0x7f1890866a3f - trans::common::fulfill_obligation::h0f47bd02a093d3d50Ur
       8:     0x7f18908530fb - trans::meth::trans_method_callee::ha0e5a2304805b987TfJ
       9:     0x7f18908c8c6b - trans::callee::trans_call_inner::h14194426857929661190
      10:     0x7f18908a9534 - trans::expr::trans_rvalue_dps_unadjusted::h3c597b7a665fcf0cetB
      11:     0x7f18908836e9 - trans::expr::trans_into::hc80d5e59b4643c2a4jA
      12:     0x7f1890814a15 - trans::controlflow::trans_block::h2cc15a51cdc30b54ncv
      13:     0x7f189081373b - trans::base::trans_closure::hdcc639dcd785862cZ0h
      14:     0x7f189085bae9 - trans::closure::trans_closure_expr::h9b2d2f24a1ad8ab0GMq
      15:     0x7f189086e127 - trans::consts::const_expr_unadjusted::h35537b466655181aQTs
      16:     0x7f1890821d7f - trans::consts::const_expr::h6ac7f2e94b5bb278GDs
      17:     0x7f189086cc7a - trans::consts::get_const_expr_as_global::ha098998f45f7267aeys
      18:     0x7f18907f7889 - trans::expr::trans::h7f856dd9d0a4e0bbkqA
      19:     0x7f189084a262 - trans::callee::trans_args::hf6c3eafcb63221bfuBo
      20:     0x7f189085044a - trans::callee::trans_call_inner::h15818476892571144510
      21:     0x7f18908aa12b - trans::expr::trans_rvalue_dps_unadjusted::h3c597b7a665fcf0cetB
      22:     0x7f18908a861a - trans::expr::trans_unadjusted::h4be66308ca683c69SXA
      23:     0x7f18907f7cad - trans::expr::trans::h7f856dd9d0a4e0bbkqA
      24:     0x7f189084a262 - trans::callee::trans_args::hf6c3eafcb63221bfuBo
      25:     0x7f1890851d1a - trans::callee::trans_call_inner::h6915871255462828367
      26:     0x7f18908a92ec - trans::expr::trans_rvalue_dps_unadjusted::h3c597b7a665fcf0cetB
      27:     0x7f18908836e9 - trans::expr::trans_into::hc80d5e59b4643c2a4jA
      28:     0x7f1890814a15 - trans::controlflow::trans_block::h2cc15a51cdc30b54ncv
      29:     0x7f189081373b - trans::base::trans_closure::hdcc639dcd785862cZ0h
      30:     0x7f1890814f87 - trans::base::trans_fn::h1f0f258022927678Mai
      31:     0x7f189084eeaf - trans::monomorphize::monomorphic_fn::hd970ed37c27c406aGeK
      32:     0x7f189083ed6b - trans::callee::trans_fn_ref_with_substs::hbd189834aea5a3b1iXn
      33:     0x7f1890904718 - trans::meth::emit_vtable_methods::closure.51383
      34:     0x7f1890902300 - vec::Vec<T>.FromIterator<T>::from_iter::h16359156833613505192
      35:     0x7f189090047a - trans::meth::get_vtable::closure.51329
      36:     0x7f1890901ca4 - iter::FlatMap<I, U, F>.Iterator::next::h14671371846128640387
      37:     0x7f1890901e6c - vec::Vec<T>::extend_desugared::h9062722263518753548
      38:     0x7f1890900f50 - iter::Iterator::collect::h12738638325186617143
      39:     0x7f1890872e74 - trans::expr::unsized_info::h715449673cb7430bDxA
      40:     0x7f18908b00c1 - trans::expr::coerce_unsized::h42154fb64305c882qIA
      41:     0x7f18907f847b - trans::expr::trans::h7f856dd9d0a4e0bbkqA
      42:     0x7f1890883452 - trans::expr::trans_into::hc80d5e59b4643c2a4jA
      43:     0x7f1890816d86 - trans::expr::trans_adt::hc5d1f123412f49f1PYB
      44:     0x7f18908162f2 - trans::base::trans_named_tuple_constructor::h99949572873a589aeei
      45:     0x7f189084f90d - trans::callee::trans_call_inner::h15818476892571144510
      46:     0x7f18908aa12b - trans::expr::trans_rvalue_dps_unadjusted::h3c597b7a665fcf0cetB
      47:     0x7f18908836e9 - trans::expr::trans_into::hc80d5e59b4643c2a4jA
      48:     0x7f1890814a15 - trans::controlflow::trans_block::h2cc15a51cdc30b54ncv
      49:     0x7f189081373b - trans::base::trans_closure::hdcc639dcd785862cZ0h
      50:     0x7f1890814f87 - trans::base::trans_fn::h1f0f258022927678Mai
      51:     0x7f189084ed62 - trans::monomorphize::monomorphic_fn::hd970ed37c27c406aGeK
      52:     0x7f189083ed6b - trans::callee::trans_fn_ref_with_substs::hbd189834aea5a3b1iXn
      53:     0x7f189085377a - trans::meth::trans_method_callee::ha0e5a2304805b987TfJ
      54:     0x7f1890850e03 - trans::callee::trans_call_inner::h6915871255462828367
      55:     0x7f18908a92ec - trans::expr::trans_rvalue_dps_unadjusted::h3c597b7a665fcf0cetB
      56:     0x7f18908a861a - trans::expr::trans_unadjusted::h4be66308ca683c69SXA
      57:     0x7f18907f7cad - trans::expr::trans::h7f856dd9d0a4e0bbkqA
      58:     0x7f189084a262 - trans::callee::trans_args::hf6c3eafcb63221bfuBo
      59:     0x7f1890851d1a - trans::callee::trans_call_inner::h6915871255462828367
      60:     0x7f18908a92ec - trans::expr::trans_rvalue_dps_unadjusted::h3c597b7a665fcf0cetB
      61:     0x7f18908a861a - trans::expr::trans_unadjusted::h4be66308ca683c69SXA
      62:     0x7f18907f7cad - trans::expr::trans::h7f856dd9d0a4e0bbkqA
      63:     0x7f189084a262 - trans::callee::trans_args::hf6c3eafcb63221bfuBo
      64:     0x7f189085044a - trans::callee::trans_call_inner::h15818476892571144510
      65:     0x7f18908aa12b - trans::expr::trans_rvalue_dps_unadjusted::h3c597b7a665fcf0cetB
      66:     0x7f18908a861a - trans::expr::trans_unadjusted::h4be66308ca683c69SXA
      67:     0x7f18907f7cad - trans::expr::trans::h7f856dd9d0a4e0bbkqA
      68:     0x7f189088329c - trans::expr::trans_to_lvalue::h5a3a7ad65443faca1WA
      69:     0x7f18908eb20c - trans::_match::trans_match_inner::h80262585b88a43c2bLI
      70:     0x7f18908a980a - trans::expr::trans_rvalue_dps_unadjusted::h3c597b7a665fcf0cetB
      71:     0x7f18908836e9 - trans::expr::trans_into::hc80d5e59b4643c2a4jA
      72:     0x7f18908f5c48 - trans::_match::mk_binding_alloca::h12714933589080796399
      73:     0x7f18908032e9 - trans::base::init_local::h0889b80b86142b03ljh
      74:     0x7f18908146d6 - trans::controlflow::trans_block::h2cc15a51cdc30b54ncv
      75:     0x7f18908a983d - trans::expr::trans_rvalue_dps_unadjusted::h3c597b7a665fcf0cetB
      76:     0x7f18908836e9 - trans::expr::trans_into::hc80d5e59b4643c2a4jA
      77:     0x7f1890883216 - trans::controlflow::trans_stmt_semi::hdaa3b6a0657ed3derbv
      78:     0x7f18908146aa - trans::controlflow::trans_block::h2cc15a51cdc30b54ncv
      79:     0x7f189081373b - trans::base::trans_closure::hdcc639dcd785862cZ0h
      80:     0x7f1890814f87 - trans::base::trans_fn::h1f0f258022927678Mai
      81:     0x7f189084ed62 - trans::monomorphize::monomorphic_fn::hd970ed37c27c406aGeK
      82:     0x7f189083ed6b - trans::callee::trans_fn_ref_with_substs::hbd189834aea5a3b1iXn
      83:     0x7f189085377a - trans::meth::trans_method_callee::ha0e5a2304805b987TfJ
      84:     0x7f1890850e03 - trans::callee::trans_call_inner::h6915871255462828367
      85:     0x7f18908a92ec - trans::expr::trans_rvalue_dps_unadjusted::h3c597b7a665fcf0cetB
      86:     0x7f18908a861a - trans::expr::trans_unadjusted::h4be66308ca683c69SXA
      87:     0x7f18907f7cad - trans::expr::trans::h7f856dd9d0a4e0bbkqA
      88:     0x7f189088329c - trans::expr::trans_to_lvalue::h5a3a7ad65443faca1WA
      89:     0x7f18908eb20c - trans::_match::trans_match_inner::h80262585b88a43c2bLI
      90:     0x7f18908a980a - trans::expr::trans_rvalue_dps_unadjusted::h3c597b7a665fcf0cetB
      91:     0x7f18908836e9 - trans::expr::trans_into::hc80d5e59b4643c2a4jA
      92:     0x7f18908f5c48 - trans::_match::mk_binding_alloca::h12714933589080796399
      93:     0x7f18908032e9 - trans::base::init_local::h0889b80b86142b03ljh
      94:     0x7f18908146d6 - trans::controlflow::trans_block::h2cc15a51cdc30b54ncv
      95:     0x7f189081373b - trans::base::trans_closure::hdcc639dcd785862cZ0h
      96:     0x7f1890814f87 - trans::base::trans_fn::h1f0f258022927678Mai
      97:     0x7f189084ed62 - trans::monomorphize::monomorphic_fn::hd970ed37c27c406aGeK
      98:     0x7f189083ed6b - trans::callee::trans_fn_ref_with_substs::hbd189834aea5a3b1iXn
      99:     0x7f189083d8c2 - trans::callee::trans_fn_ref::hb9b06523ab574ce3EMn
      100:     0x7f18908526a2 - trans::meth::trans_method_callee::ha0e5a2304805b987TfJ
     ... <frames omitted>
    
    Could not compile `solicit`.
    
    Caused by:
      Process didn't exit successfully: `rustc src/lib.rs --crate-name solicit --crate-type lib -g --out-dir /home/nri/software/nri/solicit/target/debug --emit=dep-info,link -L dependency=/home/nri/software/nri/solicit/target/debug -L dependency=/home/nri/software/nri/solicit/target/debug/deps --extern hpack=/home/nri/software/nri/solicit/target/debug/deps/libhpack-37abaf37ec66685c.rlib --extern log=/home/nri/software/nri/solicit/target/debug/deps/liblog-8a6aba167994951e.rlib` (exit code: 101)
    nri@nri-desktop:~/software/nri/solicit$ rustc -vV
    rustc 1.3.0-nightly (6d71ce536 2015-07-06)
    binary: rustc
    commit-hash: 6d71ce536439a9160100259c95c9c252a4061b86
    commit-date: 2015-07-06
    host: x86_64-unknown-linux-gnu
    release: 1.3.0-nightly
    stage: stage1
    nri@nri-desktop:~/software/nri/solicit$

**Comment by durka** [comment]
BTW, it builds on stable and beta so this is a new ICE.

**Comment by durka** [comment]
ICE was introduced between nightly-2015-07-01 and nightly-2015-07-07.

**Comment by jroesch** [comment]
I believe this this the bug I created and @eddyb fixed yesterday in #26807

**Comment by eddyb** [comment]
@durka The fix will be in the next nightly.
