### ISSUE TITLE
libstd: Div is not implemented for Wrapping

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust#26867]
Is this intentional or has this been an oversight?

**Comment by Gankro** [comment]
Should be implemented.

**Comment by alexcrichton** [comment]
Yeah this is fine to implement, but we tend to not keep tracking issues open for minor things like this, so closing. Feel free to send a PR though!

**Comment by crumblingstatue** [comment]
Right now I don't plan on hacking on the Rust codebase, so I won't implement this myself.
Won't not tracking this issue make it easy to forget implementing this?
Or is it not beneficial enough to implement that forgetting it is fine?

**Comment by huonw** [comment]
Reopening.

Tagging as E-easy, since this should just be calling the normal `/` operator (we can't avoid checking for 0 and -1, since they're actually undefined behaviour).
