### ISSUE TITLE
Do not require to implement a trait method if a constraint is not satisfied

### ISSUE THREAD

**Issue by IvanUkhov** [rust-lang/rust#26880]
Consider the [following example](http://is.gd/TOrGVM):

```rust
trait Foo {
    fn foo(&self);
    fn bar(&self) where Self: Bar;
}

trait Bar {
}

struct Baz;

impl Foo for Baz {
    fn foo(&self) {}
}
```

The example produces the following error:

```
<anon>:11:1: 13:2 error: not all trait items implemented, missing: `bar` [E0046]
<anon>:11 impl Foo for Baz {
<anon>:12     fn foo(&self) {}
<anon>:13 }
```

However, `Baz` doesn’t implement `Bar`, and presumably it shouldn’t be required to implement `bar` when implementing `Foo`.

Regards,
Ivan

**Comment by steveklabnik** [comment]
The `Foo` trait here has a `bar` method that's not implemented.

**Comment by apasel422** [comment]
This appears to be a duplicate of #20021.
