### ISSUE TITLE
`Stdin:read_line` does not need `&mut self`

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#26890]
Currently, `Stdin::read_line` takes `self` as `&mut`. Why is that? The implementation simply locks and calls `read_line` on the guard, and locking doesn't need a mutable `self`. So this is unnecessary, and the doc doesn't say why this was done. (Nor does the source.)

So I propose for this to be changed to `&self`. Looks like an oversight of some refactoring to me.

**Comment by sfackler** [comment]
I imagine it's like that because the signature was copied off of the `Read` trait - changing it to take `&self` seems fine to me personally. cc @alexcrichton

**Comment by alexcrichton** [comment]
Yeah I think it'd be fine to switch to `&self`

**Comment by RalfJung** [comment]
Is it quicker for one of you to just do that, or should I submit a PR?

**Comment by sfackler** [comment]
Go for it!

**Comment by RalfJung** [comment]
See #26897.
