### ISSUE TITLE
illegal hardware instruction

### ISSUE THREAD

**Issue by yongqli** [rust-lang/rust#26908]
rustc generates an executable which crashes with `illegal hardware instruction`.

Steps to reproduce:

    git clone https://github.com/j-e-k/rust-dmat-bug
    cd rust-dmat-bug
    cargo bench

**Comment by yongqli** [comment]
Ok, I think I figured out what's going on. `bug[(i,j)] = x.clone();` causes the destructor for `bug[(i,j)]` to be run, but it is uninitialized.

**Comment by yongqli** [comment]
Actually, shouldn't it be safe to drop an zeroed out `Vec`? This doesn't crash: https://play.rust-lang.org/?gist=f657533bf78cbaba8549&version=nightly

**Comment by Aatch** [comment]
This isn't a bug. The Vec isn't zeroed out and even if it was, all-zeroes isn't valid for a Vec. While your example there doesn't crash, that doesn't really mean much. The optimizer can be very finicky about these kinds of things.

I suggest using the `from_elem` method on `DMat` instead.
