### ISSUE TITLE
Rename SliceConcatExt::connect to join

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#26900]
Tracking issue for https://github.com/rust-lang/rfcs/pull/1102

**Comment by wesleywiser** [comment]
Hi, I'd like to take this if that's OK. 

Should I also change all of the places in this repo where `.connect` is called to call `.join` instead? Or does that break bootstrapping? 

Thanks!

**Comment by alexcrichton** [comment]
You should indeed! The stage0 libstd will have the rename so the bootstrap should be just fine (aka if `make` finishes then you're fine)

**Comment by wesleywiser** [comment]
Thanks! I'm working on this now.
