### ISSUE TITLE
Explain when/why to use lifetimes in TRPL Lifetimes chapter

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/rust#26916]
Some [feedback from Reddit](https://www.reddit.com/r/rust/comments/3cl12r/is_rust_too_complicated/csx0y6t): 

> The book doesn't explicitly explain when to use lifetimes. [This page](https://doc.rust-lang.org/book/lifetimes.html) explains in broad strokes why Rust needs lifetimes and then jumps straight into syntax and special cases, without giving an example of when lifetimes are needed.
>
> Rust-by-example does list the cases, but they are below the fold on a page titled [the borrow checker](http://rustbyexample.com/scope/lifetime/borrow.html). The page on lifetimes in the book needs to explicitly state (in bullet points) to use lifetimes when:
>
> - A function returns a reference
> - A structure holds a reference
>
> and maybe give an example of each.

I totally agree that the reasons are important.

**Comment by steveklabnik** [comment]
We currently go to great lengths to talk about lifetimes being a property of references, why you need them, and we cover both of those cases with examples.
