### ISSUE TITLE
Rules for object safety should be documented

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#26938]
Currently, the only documentation of the rules for object safety I could find is in [this blog post](https://huonw.github.io/blog/2015/01/object-safety/). However, this should also become part of the official documentation, for example [here](http://doc.rust-lang.org/stable/book/trait-objects.html).

**Comment by steveklabnik** [comment]
It is currently defined in http://doc.rust-lang.org/reference.html#trait-objects but having it in the book would be nice too.
