### ISSUE TITLE
Allow destructuring of Drop types by-value

### ISSUE THREAD

**Issue by Gankro** [rust-lang/rust#26940]
This is equivalent to mem::forget, and therefore seems to be safe if a bit foolhardy. Only really a problem within the module that defines the type regardless.

Maybe have a warn on by default.

I don't like having to ptr::read out my fields when they aren't Copy.

**Comment by pnkfelix** [comment]
-1.  I don't agree with the reasoning by equivalence with `mem::forget` here -- it is usually easy to grep for and otherwise notice uses of `mem::forget` to catch (non-leak) cases where the destructor is not run, but this change would make it much hard to catch such cases.

(That is, I am inferring that is the effect you want here, that the destructor will not be run... maybe I misunderstood that part of the proposal.)

Also, shouldn't this be in the RFCs repo?

**Comment by Diggsey** [comment]
It's only possible to get equivalent behaviour via `mem::forget` if the type has no private fields. At the moment you're guaranteed that the destructor for private fields can only ever run if the container's destructor has already run. Even if you only allow destructuring of the public fields, that's new behaviour that couldn't be emulated before.

However, with the restriction that destructuring can only be used in a context where ALL fields are accessible, I'm all for this feature.

**Comment by Gankro** [comment]
@pnkfelix you understand my proposal, but I think the warn lint would handle grepping, no?

**Comment by eefriedman** [comment]
Another problem you might not have considered:

```rust
pub struct MaybeCrashOnDrop { c: bool }
impl Drop for MaybeCrashOnDrop {
    fn drop(&mut self) {
        if self.c {
            unsafe { *(1 as *mut u8) = 0 }
        }
    }
}
pub struct InteriorUnsafe { pub m: MaybeCrashOnDrop }
impl InteriorUnsafe {
    pub fn new() -> InteriorUnsafe {
        InteriorUnsafe { m: MaybeCrashOnDrop{ c: true } }
    }
}
impl Drop for InteriorUnsafe {
    fn drop(&mut self) {
        self.m.c = false;
    }
}
```

This code is safe on current Rust, but isn't safe if destructuring arbitrary types where all the fields are visible is allowed.  This is kind of subtle: it depends on the property that it isn't possible for safe code to create a value of type MaybeCrashOnDrop that isn't wrapped in an InteriorUnsafe.

**Comment by Gankro** [comment]
Hmm... that's an interesting example, for sure! I suppose I will have to live with ptr::read'ing the fields and mem::forgetting the struct.
