### ISSUE TITLE
improve error message for using unbound 'self' in macro

### ISSUE THREAD

**Issue by comex** [rust-lang/rust#26946]
I just mistakenly tried to naively use `self` in a macro (which is only invoked by a method taking self), and got the error:

```
 error: `self` is not available in a static method. Maybe a `self` argument is missing?
```

As described in #15682, failure is intended due to hygiene.  However, the error message is inaccurate, because a macro body is not a static method.  It should be changed to take this case into account.

**Comment by brson** [comment]
Seems a bit vague without a test case. Closing, but feel free to reopen with more detail.
