### ISSUE TITLE
LTO faulty build which is fixed by print!()

### ISSUE THREAD

**Issue by DoumanAsh** [rust-lang/rust#26969]
Found strange thing when i enable ```lto``` optimization:
It always panics at this place https://github.com/DoumanAsh/collectionScripts/blob/lto_hyper/rust/vim_updater/src/main.rs#L43
```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', C:/bot/slave/stable-dist-rustc-win-g
nu-64/build/src/libcore\result.rs:729
````

But if i'll place printout here https://github.com/DoumanAsh/collectionScripts/blob/lto_hyper/rust/vim_updater/src/main.rs#L43
Then it works just fine.

Rust version:
```
rustc 1.1.0 (35ceea399 2015-06-19)
```

I'm not sure if there is bug in hyper or in rust or in my program, but i decided first to ask you for help to understand this issue.

**Comment by DoumanAsh** [comment]
Ping you @reem and @seanmonstar in case if you have some ideas for that :) or just FYI :)

**Comment by nagisa** [comment]
A few diagnostic questions:

* How do you enable LTO? Is it via `-C lto` or do you pass linker-specific arguments via `-C link-args`?
* Is that windows?
* Could you run your panicking program with `RUST_BACKTRACE` environment variable set (to `1`) and post the backtrace here?

**Comment by DoumanAsh** [comment]
It is passed by Cargo.
* I set ```lto = true```
* platform is windows, yes
* Backtrace:
```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', C:/bot/slave/stable-dist-rustc-win-g
nu-64/build/src/libcore\result.rs:729
stack backtrace:
   1:           0x477832 - main
   2:           0x47ac20 - main
   3:           0x473980 - main
   4:           0x4742de - main
   5:           0x48431c - main
   6:           0x43f3c3 - main
   7:           0x44019c - main
   8:           0x404251
   9:           0x487eec - main
  10:           0x487ec9 - main
  11:           0x41a799 - main
  12:           0x4013b5
  13:           0x4014e8
  14:     0x7fff36f513d2 - BaseThreadInitThunk
```

**Comment by alexcrichton** [comment]
It's not clear to me that this is a bug caused by LTO, adding something like a print can seriously alter the timings of when things are run and a PoisonError only comes up in concurrent situations. How are you running this? (`cargo run --release`?). I'm not able to reproduce this locally on Linux, and this may also just be a bug in one of the underlying dependencies.

**Comment by DoumanAsh** [comment]
@alexcrichton It is not clear to me too, but i decided first to try post this issue here as i don't know where to start :(
I'm building my crate with ```cargo build --release``` and then execute in manually. But it should be the same as ```cargo run --release``` :)

**Comment by DoumanAsh** [comment]
Is it possible to make backtrace more proper? with file lines and etc? :)

**Comment by DoumanAsh** [comment]
@alexcrichton 
just out of curiosity were you testing it with nighty/beta compiler?

**Comment by alexcrichton** [comment]
> Is it possible to make backtrace more proper? with file lines and etc? :)

Unfortunately not currently with Windows, that's only available on Linux right now.

>  just out of curiosity were you testing it with nighty/beta compiler?

All of stable, beta, and nightly operate normally for me without causing a panic.

**Comment by DoumanAsh** [comment]
Just to be sure, were you using ```lto_hyper``` branch? :)

If it is so and no one i able to reproduce this issue then i think i'll close this issue

**Comment by alexcrichton** [comment]
Yeah the commit I was using was d142e581770540097c4784b98a941355b1851667 (just to make sure it didn't change)

**Comment by DoumanAsh** [comment]
Ok, i'll close this issue.
