### ISSUE TITLE
for loop issue

### ISSUE THREAD

**Issue by geraldstanje** [rust-lang/rust#26975]
hi, 

the following code just just terminates without any error...ideas?
if this code is not allowed the compiler needs to create an compile error?

```
fn main() {
   for i in (10..0) {
    println!("{}", i);
   } 
}
```

playground: http://is.gd/yLCmj2

i know you could use: for i in (0..10).rev()

**Comment by alexcrichton** [comment]
This is intentional as the range `10..0` is an empty range because the start is larger than the end. Looks lie you've seen the fix, though, of `(0..10).rev()`!

**Comment by Gankro** [comment]
@manishearth is this something rust-clippy can handle?

**Comment by Manishearth** [comment]
Yes, cc @llogiq

**Comment by geraldstanje** [comment]
@alexcrichton shouldnt the compiler return a compiler error or warning in this case?

**Comment by Manishearth** [comment]
It's not necessarily the job of the compiler to emit warnings for footguns like these. We do it in some cases, but not all. Projects like rust-clippy exist to write lints for a wider range of footguns.
