### ISSUE TITLE
impl<T> is not introduced in the book

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/rust#26991]
There's only a few references to `impl<` in TRPL:

1. src/doc/trpl/deref-coercions.md
2. src/doc/trpl/lifetimes.md
3. src/doc/trpl/unsized-types.md

None of these really mention that you use `impl<T>` to declare a typename that will participate in either the trait or item involved in the implementation.

**Comment by lastorset** [comment]
I've got a draft going in [my fork](https://github.com/rust-lang/rust/compare/master...lastorset:lastorset-traits?expand=1). Will submit a PR soon, but feel free to review before I do.

**Comment by shepmaster** [comment]
@lastorset your docs look great! I added some initial comments in your branch. Thanks for taking a crack at this!

**Comment by steveklabnik** [comment]
@lastorset yeah, please send a PR whenever you're ready :)

**Comment by lastorset** [comment]
Thanks, I appreciate the feedback! I want to work through it again before I submit.
