### ISSUE TITLE
ICE when using macro as for loop parameter

### ISSUE THREAD

**Issue by milesrout** [rust-lang/rust#27004]
macro_rules! foo {
        () => ()
    }
    
    pub fn main () {
        for foo!() in (1..) {
        }
    }

error:

    error: internal compiler error: unexpected panic
    note: the compiler unexpectedly panicked. this is a bug.
    note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
    note: run with `RUST_BACKTRACE=1` for a backtrace
    thread 'rustc' panicked at 'fold_mac disabled by default', /home/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libsyntax/fold.rs:190
    
    
    playpen: application terminated with error code 101

version is whatever is considered stable by `play.rust-lang.org` at 3:30pm UTC+12 13/07/2015, but also for the nightly and beta releases.

**Comment by Aatch** [comment]
I haven't looked yet, but I assume that this is due to the order in which expansions happen. With the `for` expansion happening before macro expansions. I'm not familiar enough with the code to know if simply doing macro expansion first is a sensible fix or not.
