### ISSUE TITLE
TRPL markup [^moving] rendered as superscript

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#27035]
The source markup for https://doc.rust-lang.org/book/the-stack-and-the-heap.html#the-heap contains:

```md
In this case, however, it doesn’t.[^moving] When the function is over, …

[^moving]: We can make the memory live longer by transferring …
```

It’s rendered as:

```html
In this case, however, it doesn’t.[<sup>moving]</sup> When the function is over,
```

… which doesn’t seem to be intended.

CC @steveklabnik

**Comment by steveklabnik** [comment]
Very odd.

**Comment by SimonSapin** [comment]
Is this syntax for footnotes that might not be supported by rustdoc?

**Comment by nagisa** [comment]
Yes. Author probably used pandoc to render the document, which supports the feature.

**Comment by steveklabnik** [comment]
I thought I learned about this syntax through rustdoc, though...

**Comment by steveklabnik** [comment]
for exmaple, grammar.md: http://doc.rust-lang.org/grammar.html#fn1

**Comment by Gankro** [comment]
This is a feature supported by hoedown that we enable in rustdoc: https://github.com/hoedown/hoedown/issues/92

**Comment by steveklabnik** [comment]
So, I guess the real question is why it isn't being rendered properly here. @alexcrichton any ideas?

**Comment by alexcrichton** [comment]
We may just need to update hoedown (it hasn't been updated in ages). Either that or just not use footnotes.

**Comment by steveklabnik** [comment]
But we do use footnotes and some of them do get rendered, just not this one. If they all didn't work, that'd make sense...

**Comment by alexcrichton** [comment]
Ah then we may just need to update hoedown as our bundled version may not have the bugfix mentioned above.

**Comment by steveklabnik** [comment]
Agreed! Thanks for the triage.
