### ISSUE TITLE
Rust Book "Mutability" section is unclear

### ISSUE THREAD

**Issue by jimblandy** [rust-lang/rust#27049]
The explanations in src/doc/trpl/mutability.md are unclear, especially compared to the rest of TRPL, which is generally pretty great.

> When a binding is mutable, it means you’re allowed to change what the binding points to. So in the above example, it’s not so much that the value at x is changing, but that the binding changed from one i32 to another.

The issues I see here are:
- In the example being discussed, there are no pointers, so "points to" seems to come out of nowhere.
- Using the phrase "the value at x" to refer to a variable's value again suggests there's some indirection going on, but we're just assigning to a variable. There's nothing subtle here at all.
- The second sentence feels like a distinction without a difference.

Later:

> However, when we say something is ‘immutable’ in Rust, that doesn’t mean that it’s not able to be changed: We mean something has ‘exterior mutability’.

Is that a typo? Or is saying something is immutable really saying it has exterior *mutability*?

The term 'exterior mutability' is never mentioned again.

I don't have concrete suggestions (like a pull request) because I'm worried I just don't get what we're going for here.

**Comment by steveklabnik** [comment]
exterior mutability is the opposite of interior mutability, basically. It's
rarely mentioned explicitly since it's the default. you're right that
that's a typo.

**Comment by arielb1** [comment]
The "binding of x" vs. "value at x" is more interesting in languages with implicit pointers - in Rust, unless an explicit pointer dereference is involved, the "value at x" is always an rvalue and changing it is meaningless (in the same sense as `2 = 3;`).

**Comment by leodasvacas** [comment]
I also feel this "distinction without a difference" is more confusing than explanatory.

**Comment by steveklabnik** [comment]
I'm not planning on making any more major changes to this draft of the book, and mutability will be dealt with differently in the next draft. So I'm going to give this one a close.
