### ISSUE TITLE
Some example code not showing in rustdoc

### ISSUE THREAD

**Issue by mcast** [rust-lang/rust#27058]
Following #rust conversation with kimundi (just now from about 11:18pm +01:00), I found a [useful example](https://doc.rust-lang.org/stable/src/core/result.rs.html#883-890) in the source,
```rust
    /// Takes each element in the `Iterator`: if it is an `Err`, no further
    /// elements are taken, and the `Err` is returned. Should no `Err` occur, a
    /// container with the values of each `Result` is returned.
    ///
    /// Here is an example which increments every integer in a vector,
    /// checking for overflow:
```
but it seems not to be rendered anywhere on doc.rust-lang.org .

Or at least, [search engines](https://encrypted.google.com/search?q=site%3Adoc.rust-lang.org+%22Here+is+an+example+which+increments+every+integer+in+a+vector%2C+checking+for+overflow%22&btnG=Search&hl=en&gbv=1&filter=0) aren't finding the text (refresh too slow?), and it isn't where I look for it (I'm hopelessly lost?).

**Comment by eefriedman** [comment]
See also issue #24838/issue #26871.

**Comment by mcast** [comment]
Thanks @eefriedman, this is a dup.
