### ISSUE TITLE
running "make -j8 rustc-stage1 && make check-stage1" yields lldb error in debuginfo tests

### ISSUE THREAD

**Issue by AlisdairO** [rust-lang/rust#27053]
When I run make -j8 rustc-stage1 && make check-stage1, I'm having problems during the check phase, as the lldb-debuginfo tests fail.  

I'm running OSX Mavericks (10.9.5), python 2.7.10 (also tried 2.7.5).  The errors all look approximately like the following:

---- [debuginfo-lldb] debuginfo/associated-types.rs stdout ----
    NOTE: compiletest thinks it is using LLDB version 320

error: Error while running LLDB
status: signal: 6
command: "/opt/local/bin/python2.7" "/Users/alisdair/coding/rust/github/rust3/rust/src/etc/lldb_batchmode.py" "x86_64-apple-darwin/test/debuginfo-lldb/associated-types.stage1-x86_64-apple-darwin" "x86_64-apple-darwin/test/debuginfo-lldb/associated-types.debugger.script"
## stdout:

---
## stderr:

Fatal Python error: PyThreadState_Get: no current thread

---

thread '[debuginfo-lldb] debuginfo/associated-types.rs' panicked at 'explicit panic', /Users/alisdair/coding/rust/github/rust3/rust/src/compiletest/runtest.rs:1490

stack backtrace:
   1:        0x10adeaa7c - sys::backtrace::write::h586834ebba3e6ecdsfs
   2:        0x10adf2844 - panicking::on_panic::he0c2d5bf787ca962jxw
   3:        0x10adb5993 - rt::unwind::begin_unwind_inner::h3133064673244d2bvfw
   4:        0x10abb2a4f - rt::unwind::begin_unwind::h18105261098028733237
   5:        0x10abcd196 - runtest::fatal_proc_rec::habf6f687388c2730TMc
   6:        0x10abc1027 - runtest::run::h9dc8a338c86311b3YNa
   7:        0x10abebf66 - boxed::F.FnBox<A>::call_box::h10189477282828699771
   8:        0x10ac27c21 - boxed::F.FnBox<A>::call_box::h16535673906505838925
   9:        0x10ac26227 - rt::unwind::try::try_fn::h14250546107872681382
  10:        0x10ae7f9c8 - rust_try_inner
  11:        0x10ae7f9b5 - rust_try
  12:        0x10addf945 - rt::unwind::try::inner_try::hea962f3835ea3e18obw
  13:        0x10ac26478 - boxed::F.FnBox<A>::call_box::h8047771136870442878
  14:        0x10adf1308 - sys::thread::Thread::new::thread_start::h1a466ad39c1a34b6yzv
  15:     0x7fff9a6e1898 - _pthread_body
  16:     0x7fff9a6e1729 - _pthread_start

**Comment by tamird** [comment]
The reason for this is explained in https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Common-Issues.md#python-segmentation-fault-11-on-import-some_python_module

On my machine, I had to switch from the `pyenv`-provided python 2.7.10 to the system python 2.7.10 (yes, same version) in order to get the lldb tests to work. Not particularly satisfying.

**Comment by AlisdairO** [comment]
Ah, thanks a lot for the info!  I suppose there's not much that can be done about this from a rust project point of view?  Can close if so.

**Comment by alexcrichton** [comment]
Make's now gone, so closing.
