### ISSUE TITLE
dead link in documentation

### ISSUE THREAD

**Issue by benaryorg** [rust-lang/rust#27097]
There is a dead link on [doc.rust-lang.org/[…]/trait.Copy.html](http://doc.rust-lang.org/std/marker/trait.Copy.html).

If you scroll down to the implementations and click on `Fp` you run into a 404.

**Comment by steveklabnik** [comment]
Thanks! This is a dup of https://github.com/rust-lang/rust/issues/23912 though, so I'm closing it in favor of that. It's certainly an issue, but we're tracking it there.

**Comment by benaryorg** [comment]
No problem.

Looks like I didn't search well enough.
