### ISSUE TITLE
Fulfill additional higher-kinded "outlives" predicates

### ISSUE THREAD

**Issue by apasel422** [rust-lang/rust#27113]
Types fail to fulfill higher-kinded "outlives" predicates when the higher-kinded region is present on the left-hand side of the predicate. For example:

``` rust
fn foo<T>() where for<'a> &'a T: 'a {}

fn main() {
    foo::<i32>();
    //~^ ERROR the requirement `for<'a> &'a i32: 'a` is not satisfied [E0280]
}
```

CC @nikomatsakis.

**Comment by apasel422** [comment]
This doesn't actually have to do with diagnostics. A more accurate label would be `lifetimes`.

**Comment by apasel422** [comment]
@nikomatsakis Any advice for progressing on this?

**Comment by apasel422** [comment]
Ping.

**Comment by nikomatsakis** [comment]
@apasel422 heh, sorry. I think that solving this is actually going to be a bit tricky. What we really want to do, I think, is refactor how the trait resolution code works so that we can more easily introduce predicates into the environment and check under those assumptions. But probably there's an easier, shorter-term fix here, even if it covers less ground.

**Comment by beamspease** [comment]
I ran into this issue, and as I understand it's not possible without some work on Higher Kinded Lifetimes.
https://www.reddit.com/r/rust/comments/3lfl5p/trait_method_that_returns_owned_copy/

Dunno if this is the correct bug to comment on, but I just wanted to note that it seems like it makes it impossible to implement ToOwned for a trait...

**Comment by timotree3** [comment]
Is there any progress on this issue? Are Polonius or Chalk going to fix this?

I can reproduce it with something as simple as

```rust
trait Foo where for<'a> &'a u64: 'a {}
```

**Comment by Spoonbender** [comment]
Triage: resolved

Both examples compile on stable `rustc 1.59.0 (9d1b2106e 2022-02-23)`

I think we can close this one

**Comment by estebank** [comment]
[We already have a test](https://github.com/rust-lang/rust/blob/cf2dff2b1e3fa55fa5415d524200070d0d7aacfe/tests/ui/associated-types/higher-ranked-projection.rs).
