### ISSUE TITLE
rustdoc: items are shown as if defined in crate when reexported cross-module and cross-crate

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#27123]
Consider 

``` rust
extern crate innercrate; //defines only one public item `from_inner_crate`

pub use inner::{inner_fn, from_inner_crate};


/// Top level documentation
pub fn top_level(){}


pub mod inner {
    pub use innercrate::from_inner_crate;
    /// Defined inside inner module
    pub fn inner_fn(){}
}
```

Documentation renders from_inner_crate as if it was defined at the top level of crate rather than showing it as an reexport from inner module.

![what output from rustdoc looks like](https://cloud.githubusercontent.com/assets/679122/8765655/512f38d6-2e1f-11e5-8350-4fb1ff64c90f.png)

**Comment by nagisa** [comment]
cc https://github.com/rust-lang/rust/issues/24305, not sure if any of list items in that meta-issue are duplicates.

**Comment by brson** [comment]
The behavior described in the op is intended. rustdoc does have an option not to inline reexports. If there are missing features still please open a new ticket with further clarification.
