### ISSUE TITLE
No SyntaxExtension variant can modify foreign items

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang/rust#27126]
`SyntaxExtension::MultiModifier` only visits true items, ImplItems, and TraitItems, not `ForeignItem`s.  This makes it impossible to write syntax extensions which operate directly on foreign items (e.g. functions declared inside an `extern` block).

I started work on https://github.com/rust-lang/rfcs/issues/1217 out of tree but hit this issue almost right away.

**Comment by steveklabnik** [comment]
Triage: this bit still exists.

**Comment by steveklabnik** [comment]
Triage: this still exists, but syntax extensions are never being stabilized as a public api, and there's been no real comments since this issue has been opened. I'm going to close this as WONTFIX. If you really truly care about this still please let me know!

**Comment by petrochenkov** [comment]
This was actually fixed in https://github.com/rust-lang/rust/pull/49350
