### ISSUE TITLE
negate_unsigned feature gate warning should be changed to feature gate.

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#27141]
negate_unsigned feature gate (librustc_lint/builtin.rs) currently emits a warning instead of actual feature_gate due to backwards [compatibility concerns][1]. After some time passes this warning should be converted to feature gate.

Basically, reverting the “Convert negate_unsigned feature gate to a warning” commit (0ca8e4994ee) from https://github.com/rust-lang/rust/pull/27026 and fixing up conflicts (if any) should do.

Note to any people who are planning to do this: ask somebody from language team whether enough time has passed since we started to emit the warning before submitting a PR.

[1]: https://github.com/rust-lang/rust/pull/27026#issuecomment-122787339

**Comment by pnkfelix** [comment]
I think once the next beta has been release we can go ahead and apply this change to nightly.

**Comment by steveklabnik** [comment]
Did this end up happening?

**Comment by nagisa** [comment]
This has not landed yet. 

I’ve asked @pnkfelix several times on IRC which shift he had in mind (1.3 to beta or 1.4 to beta), because his comment was posted on the day of such shift, but never got a response.
