### ISSUE TITLE
rustc cannot statically link to C library

### ISSUE THREAD

**Issue by vks** [rust-lang/rust#27142]
When trying to link to a static C library called `md`

```
rustc src/lib.rs [...] -L native=/path/to/md -l static=md
```

it fails:

```
error: linking with `cc` failed: exit code: 1
[...]
note: /usr/bin/ld: /path/to/md/libmd.a(acosh.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
/path/to/md/libmd.a(acosh.o): error adding symbols: Bad value
collect2: error: ld returned 1 exit status

error: aborting due to previous error
```

I don't understand why rustc tries making a shared object. Changing the argument to `-l dylib` does not make any difference.

**Comment by vks** [comment]
How to reproduce:

```
$ git clone https://github.com/vks/special-fun.git
$ cd special-fun
$ cargo build  # works
[...]
$ cargo test  # fails
[...]
```

Maybe it is related to `rustc --test`?

**Comment by alexcrichton** [comment]
This is actually working as intended because rustc produces position-independent output by default (even for executables, not just for dynamic libraries). You'll need to add `-fPIC` to your makefiles for the native library or use a build dependency like `gcc` to build native code.

**Comment by vks** [comment]
Is it possible to make it produce non position-independent output?

**Comment by alexcrichton** [comment]
Yes `rustc -C relocation-model=static` should lift this requirement.
