### ISSUE TITLE
std::process::Command.status() hangs if subprocess output is >64K characters

### ISSUE THREAD

**Issue by TheJakeSchmidt** [rust-lang/rust#27152]
std::process::Command hangs in status(), even if output() was called first, if the subprocess prints more than 64K characters to stdout.

This Rust program hangs between the two println!() statements, but passes if you change 65536 to 65535:

    use std::process::Command;
    use std::process::Stdio;

    fn main() {
        let mut process = Command::new("python");
        process.arg("-c").arg("print('a' * 65536)")
            .stdout(Stdio::piped())
            .stdin(Stdio::null())
            .stderr(Stdio::null())
            .output();
        println!("Calling status()");
        process.status();
        println!("status() returned");
    }

I tested this with rustc version "rustc 1.3.0-dev (c70417bd1 2015-07-20)".

**Comment by alexcrichton** [comment]
This is actually working as intended, and I believe hang your seeing is just related to how much the kernel buffers the output between processes. A `Command` represents a pending execution of a `Child`, so what's happening here is that you're spawning two processes. The second process is just immediately calling `wait` without trying to read any of the piped stdout, so if the child process is blocked writing to stdout then it'll never return (as the parent isn't reading the pipe).

**Comment by TheJakeSchmidt** [comment]
Sorry, I should have given more detail - I filed this bug report a little too fast. I don't think this is working as intended, for a couple of reasons, but let me know if I'm wrong.

When the program hangs, the subprocess is blocked on a write() call to its stdout file descriptor (according to GDB). I'm pretty sure that's not supposed to happen after output() has been called - the output() call spawns a thread that should consume all the output from the pipe before returning (https://github.com/rust-lang/rust/blob/feba393b8ed60efe79f9f5207fde904d085949f5/src/libstd/process.rs#L533). The hang is expected if status() is called before output(), but not if output() is called first.

Additionally, the equivalent Python program works (even with large numbers), so I don't think it's an inherent limitation of the kernel:

    import subprocess

    def main():
        proc = subprocess.Popen(["python",  "-c", "print('a' * 10000000)"],
                                shell=False, stdout=subprocess.PIPE)
        proc.communicate()
        print "Calling wait()"
        proc.wait()
        print "wait() returned"

    if __name__ == '__main__':
        main()

**Comment by retep998** [comment]
You are invoking `status()` on a `Command`, which is spawning a fresh new process. Your previous call to `output()` was on a different process. What you probably want to do is get the `ExitStatus` from the `status` field of the `Output` you get from `output()`.

**Comment by TheJakeSchmidt** [comment]
Ahhhh, that makes sense. I didn't realize that status() was re-executing the child process. Thank you, and sorry for the erroneous report.
