### ISSUE TITLE
Extend missing_doc lint to consts and statics again.

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#27161]
Reverting [here](https://github.com/rust-lang/rust/pull/27160) until [this RFC](https://github.com/rust-lang/rfcs/pull/1193) is implemented.

**Comment by xiongmao86** [comment]
This seem to be done in a recent merge.

**Comment by alexcrichton** [comment]
Indeed! It was re-applied in https://github.com/rust-lang/rust/pull/27575
