### ISSUE TITLE
Multiple specialisations possible but no way to select one.

### ISSUE THREAD

**Issue by nwin** [rust-lang/rust#27179]
In the following example ([playground](http://is.gd/nNw6gv)) I cannot specify which `new` to use. I was surprised that I could write the second implementation in the first place as [RFC#1210](https://github.com/rust-lang/rfcs/pull/1210) is not accepted yet. So there are no rules which one to use.

```rust
struct Cursor<T> {
    i: T
}

impl<T: AsRef<[u8]>> Cursor<T> {
    fn new(t: T) -> Self { Cursor {i: t} }
}

impl Cursor<[u8; 2]> {
    fn new(t: [u8; 2]) -> Self { Cursor {i: t} }
}

fn main() {
    let c = Cursor::<[u8; 2]>::new([0; 2]);
}
```

**Comment by tamird** [comment]
You can use UFCS to select a specific method, I believe.

**Comment by Stebalien** [comment]
@tamird You can't. Here's an example that doesn't use trait bounds or static methods and does use UFCS:

```rust
struct Foo<T>(T);

impl<T> Foo<T> {
    fn foo(&self) {
        println!("generic");
    }
}

impl Foo<()> {
    fn foo(&self) {
        println!("specific");
    }
}

fn main() {
    let f = Foo(());
    <::Foo<()>>::foo(&f);
}

```

**Comment by arielb1** [comment]
These are inherent impls, not trait impls. This isn't specialization really.

**Comment by nwin** [comment]
Still, it won’t work using UFCS

    <Cursor<[u8; 2]>>::new([0; 2]);

will produce the same error message (or am I missing something?).

**Comment by arielb1** [comment]
@nwin

This isn't really impl-specialization: essentially, you just created 2 completely distinct `Cursor::new` methods, but there is no way to disambiguate between them when both are available, making the "specific" method useless (AFAICT). You *can* actually refer to the "generic" method by calling a function that lacks the trait-bound (with specialization, that would print "specific").

```Rust
struct Foo<T>(T);

impl<T> Foo<T> {
    fn foo(&self) {
        println!("generic");
    }
}

impl Foo<()> {
    fn foo(&self) {
        println!("specific");
    }
}

fn foo_foo<T>(t: &Foo<T>) { t.foo(); }

fn main() {
    let f = Foo(());
    foo_foo(&f);
}
```

Note that you can, in fact, have 2 inherent impls with the same signature and method-name (leaving no way to disambiguate):
```Rust
impl<T> Foo<T> {
    fn foo(&self) {
        println!("generic");
    }
}

impl<T> Foo<T> {
    fn foo(&self) {
        println!("specific");
    }
}
```

Maybe we should lint against these useless impls?

**Comment by nwin** [comment]
@arielb1 What else should it be? How would you call it then? It specializes on the impl block and this case is also covered in the RFC I mentioned.

I think the last example should be an error. It is completely useless and definitively not intended by the user to have identical impl-blocks.

**Comment by arielb1** [comment]
@nwin

That's the point, it *doesn't*. For every `(base-type, method name)`, there is a list of inherent-impl methods with that base-type and name. At typechecking time, the compiler calculates the set of impls that are potentially correct (types match, impl in-scope, etc.), and complains if there is more than 1.

**Comment by nikomatsakis** [comment]
So, my take is that the current implementation is not well thought out in this respect. In exploring specialization, @aturon and I encountered a lot of these kinds of oddities. The specialization RFC specifically describes a "rationalization" of inherent methods in terms of implicit traits that I think ought to be the "intended" semantics. As noted in the RFC, this is not 100% backwards compatible when it comes to corner cases like the ones presented here, but then the ones presented here aren't really doing anything particularly sensible. 

So in a sense I think both @arielb1 and @nwin are correct -- @arielb1 is describing the current implementation well, but @nwin seems to be describing the model espoused by the specialization RFC, at least based on a cursory reading.

**Comment by steveklabnik** [comment]
Okay. So for now, this is Not a Bug. Closing!
