### ISSUE TITLE
Improve code of conduct visibility 

### ISSUE THREAD

**Issue by Aaronepower** [rust-lang/rust#27187]
Rust is often credited with a great community, a code of conduct would add greatly to this.
Sample: http://todogroup.org/opencodeofconduct/

**Comment by Stebalien** [comment]
http://www.rust-lang.org/conduct.html

**Comment by Aaronepower** [comment]
This should be copied into the repo?

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md already mentions that 

> As a reminder, all contributors are expected to follow our Code of Conduct.

Which links to the site. The code of conduct is important to us, but having multiple copies around isn't very DRY. Thank you for caring about this, though!
