### ISSUE TITLE
Please provide unprivileged install for RUST

### ISSUE THREAD

**Issue by ArthurZ** [rust-lang/rust#27198]
For users on Windows OS without the full admin/privileged rights it is impossible to install RUST therefore please provide a possibility to install RUST by other means than MSI (installer).

**Comment by alexcrichton** [comment]
This is actually currently possible today, the installers have the ability to install for just the local users in which case you don't need any privileges to install.

**Comment by ArthurZ** [comment]
@alexcrichton I can't even start the MSI bootstrapping, it prompts for the privilged account password

**Comment by nodakai** [comment]
I could install `rust-1.1.0-x86_64-pc-windows-gnu.msi` onto x64 Win7 Pro SP1 with a non-Admin user.

@ArthurZ What version of Windows do you use?  Launch `winver.exe` via "Search programs and files" in the start-up menu to check the version.

![winver.exe](http://cdn.windows7themes.net/pics/winver.jpg)

**Comment by ArthurZ** [comment]
The same Windows build, but on SP1. 
Not an issue with RUST, it was the broken Windows Installer. 
Please close this issue and thanks!
