### ISSUE TITLE
internal compiler error: unexpected panic

### ISSUE THREAD

**Issue by yongqli** [rust-lang/rust#27190]
rustc --version
    rustc 1.3.0-dev (136c623a6 2015-07-20)

    error: internal compiler error: unexpected panic
    note: the compiler unexpectedly panicked. this is a bug.
    note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
    thread 'rustc' panicked at 'index out of bounds: the len is 163 but the index is 165', src/libcollections/vec.rs:1246

    stack backtrace:
       1:        0x10b333105 - sys::backtrace::write::h4c111a1258819d2f2ts
       2:        0x10b33c17e - panicking::on_panic::h33dc402bf9951ea3tUw
       3:        0x10b2f5cc2 - rt::unwind::begin_unwind_inner::h258242b5ee3ea4bbFCw
       4:        0x10b2f6b6c - rt::unwind::begin_unwind_fmt::h29cff6098ce1b103LBw
       5:        0x10b33bcfc - rust_begin_unwind
       6:        0x10b395315 - panicking::panic_fmt::h0f01bb1ca929c3a8ZeC
       7:        0x10b38fa55 - panicking::panic_bounds_check::hbef09d56c60c34805dC
       8:        0x1086835c6 - middle::infer::freshen::TypeFreshener<'a, 'tcx>.TypeFolder<'tcx>::fold_ty::hb04cbb3e99323851hUz
       9:        0x108684b19 - middle::ty_fold::TypeFolder::fold_substs::h10277980681197289425
      10:        0x1085ea81a - middle::traits::select::SelectionContext<'cx, 'tcx>::select::h150c120ec75f7857zvT
      11:        0x10870123f - middle::traits::fulfill::process_predicate::h0cdff7d56c6fa129FqR
      12:        0x1086ffd56 - middle::traits::fulfill::FulfillmentContext<'tcx>::select::he284812e20d18afd7jR
      13:        0x1086ff823 - middle::traits::fulfill::FulfillmentContext<'tcx>::select_where_possible::h74df06163f800581SiR
      14:        0x1082567c9 - check::FnCtxt<'a, 'tcx>::select_obligations_where_possible::h5b680d18110c50a87kp
      15:        0x1081f224a - check::FnCtxt<'a, 'tcx>::resolve_type_vars_if_possible::h5264bdca1b37405enBo
      16:        0x1081f3972 - check::demand::coerce::hb6a09b9955962d391pf
      17:        0x108279e19 - check::check_expr_with_unifier::h14130798179127750926
      18:        0x10829f619 - check::check_decl_initializer::hb7a39a928dbd5dce5Sr
      19:        0x10829f6e3 - check::check_decl_local::h606b3660abd4ffe3jUr
      20:        0x10829f8ee - check::check_stmt::h14d2b1e3601f6042cWr
      21:        0x10824ee97 - check::check_block_with_expected::hb7db74741c92ee09g0r
      22:        0x108231cc3 - check::check_fn::h1ef7196787255064OFn
      23:        0x108249275 - check::check_bare_fn::h7d46c7e56b3f338crvn
      24:        0x1082472c3 - check::check_item_body::hd93b370111426bdd4Vn
      25:        0x108247492 - visit::walk_item::h10586019360988062493
      26:        0x10824749d - visit::walk_item::h10586019360988062493
      27:        0x108248e6d - check::check_item_types::hff74139af14f8d6fYsn
      28:        0x108306d67 - check_crate::h447794802c7fa013KTC
      29:        0x107b4ee49 - driver::phase_3_run_analysis_passes::closure.16369
      30:        0x107b4d7f2 - middle::ty::ctxt<'tcx>::create_and_enter::h8101287957067407741
      31:        0x107b489e0 - driver::phase_3_run_analysis_passes::h16108929088794624082
      32:        0x107b2e7be - driver::compile_input::he6a5f989fefc2832Tba
      33:        0x107c1094b - run_compiler::h7a19ee287319dbcfA7b
      34:        0x107c0e1c0 - boxed::F.FnBox<A>::call_box::h11676062181285324871
      35:        0x107c0da67 - rt::unwind::try::try_fn::h5316072723613735160
      36:        0x10b3cd058 - rust_try_inner
      37:        0x10b3cd045 - rust_try
      38:        0x10b325705 - rt::unwind::try::inner_try::h90bcdff2924c1310yyw
      39:        0x107c0dc98 - boxed::F.FnBox<A>::call_box::h10842136710623760398
      40:        0x10b33abfd - sys::thread::Thread::new::thread_start::h34b787c11432bfafIWv
      41:     0x7fff8b67b267 - _pthread_body
      42:     0x7fff8b67b1e4 - _pthread_start

**Comment by apasel422** [comment]
The ICE is from running `rustc --version`?

**Comment by yongqli** [comment]
No, it is from trying to compile a file that has errors. When the error is fixed the ICE disappears.

**Comment by apasel422** [comment]
Could you post the contents of the file?

**Comment by emoon** [comment]
@yongqli could you post the content of the file? Otherwise it will be very difficult to track down the problem.

**Comment by apasel422** [comment]
@yongqli Is the code that causes this still available?

**Comment by yongqli** [comment]
Sorry, no :(.
