### ISSUE TITLE
Same compiler error two times

### ISSUE THREAD

**Issue by dawirstejeck** [rust-lang/rust#27247]
Hi everybody,
while playing around with rust for the first time (which is great fun!), I noticed something odd. Compiling this:
https://play.rust-lang.org/?gist=fb5a1d527f2681d38858&version=stable
gives me the same error two times on stable, beta and nightly.

Edit: the given error doesn't exist by the way...
https://doc.rust-lang.org/error-index.html#E0277

**Comment by sanxiyn** [comment]
I can't reproduce this on nightly any more. Can you?

**Comment by dawirstejeck** [comment]
It's fixed in nightly!
