### ISSUE TITLE
Add set_limit() fn to std::io::Take

### ISSUE THREAD

**Issue by carllerche** [rust-lang/rust#27269]
`std::io::Cursor` has a fn to update the position yet `Take` does not have a fn for setting the limit. Being able to update the limit is required for implementing various traits for Take. For example, `Read` works by updating the limit.

I was hoping to implement `Buf` for `Take` (in the bytes crate) but am currently unable to do so.

**Comment by carllerche** [comment]
It would also be nice if `Take` implemented:

* `get_ref`
* `get_mut`
* `into_inner`

**Comment by Mark-Simulacrum** [comment]
This is only missing the set_limit function today, as the rest are implemented (tracked, in part, by https://github.com/rust-lang/rust/issues/41519). I've filed https://github.com/rust-lang/rust/pull/42697 to implement set_limit.
