### ISSUE TITLE
Stabilisation of `result_expect`

### ISSUE THREAD

**Issue by thepowersgang** [rust-lang/rust#27277]
Introduced in RFC1119, covers the `Result::expect` method.

An easy candidate for stabilisation as far as I can see, as it's just a single method that brings `Result`'s and `Option`'s APIs closer.

(#26868)

**Comment by yohanesu** [comment]
When can we expect this to be usable from stable 1.2?

**Comment by alexcrichton** [comment]
This'll serve as the tracking issue for the `result_expect` feature

**Comment by thepowersgang** [comment]
@yohanesu Hopefully it will be stabilised for 1.4 (i.e. when current nightly is made stable)

**Comment by alexcrichton** [comment]
This feature is now entering its final comment period for stabilization.

**Comment by retep998** [comment]
Super useful function, I'm okay with stabilizing this.
