### ISSUE TITLE
User facing messages MUST NOT say "illegal".

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#27288]
`error: illegal width `4` for float literal, valid widths are 32 and 64`

`error: illegal recursive enum type; wrap the inner value in a box to make it representable [E0072]`

You can almost always replace `illegal` with `invalid`. Since we're (probably) not breaking the law writing Rust code, we shouldn't use terms about breaking the law.

It seems like this language mostly comes from early specifications, and it causes problems. If panic reasons are visible to end users - users who don't understand it's not illegal under the penal code - they may think they've done something really bad. It's also probably not a good word to see for people for whom English is not their first language.

So please, let's get all the occurrences of "illegal" in error messages out of the language.

**Comment by nagisa** [comment]
I’m doing this, along with other assorted diagnostics improvements.

**Comment by Stebalien** [comment]
This is only really important for potentially user-facing errors. Programmers should know what illegal means in the context of programming.
