### ISSUE TITLE
Allow asserts in constant functions

### ISSUE THREAD

**Issue by uzytkownik** [rust-lang/rust#27293]
Currently constant functions are not allowed to contain asserts. As asserts are base of defensive it would be nice if they were at least ignored - if nor changed into static asserts - in contexts when constant functions are required.

**Comment by steveklabnik** [comment]
I think this would require an RFC. @eddyb ?

**Comment by eddyb** [comment]
@uzytkownik Are you talking about `assert!`?
That's a macro that expands to something like `if !cond { panic!(...) }`.
Actually, I remember now, someone was suggesting this a while back and I told them it *might* work, if the compiler would const-evaluate the `panic_fmt` "weak" language item and emit a compile-time error.

It requires the inevitable overhaul of the constant evaluator, support for control-flow (at least `if`) in constants, and running formatting in the compiler, from a constant `format_args!`.
Then again, the formatting traits can't have the `fmt` methods constant, so scratch that last part.

@steveklabnik I agree, this definitely needs a RFC, although it's likely possible, there's probably even more hairy details than I listed above.

**Comment by shepmaster** [comment]
For what it's worth, I'd love the ability to raise compile-time assertions, so I'd be happy to see an RFC proposed for this.

**Comment by steveklabnik** [comment]
Okay, @uzytkownik , yes, please pursue an RFC if you'd like to add this feature: https://github.com/rust-lang/rfcs/
