### ISSUE TITLE
Add BitAndNot

### ISSUE THREAD

**Issue by dnspies** [rust-lang/rust#27306]
The ANDNOT operation is used at least as commonly as XOR and often has a more efficient implementation than x & !y.
It introduces a symmetric function to OR for implementing clear-bit and set-bit on bit-vector-like classes.

It should be given the same attention (including it's own operator symbol, perhaps &~ or &!) and status the other three bit operators have (or at least the same as XOR).

**Comment by huonw** [comment]
I would assume that most compilers have a peephole optimisation for `x & !y` -> whatever is the most efficient implementation, similar to how `x % 2` becomes `x & 1` and `x << y | x >> (32 - y)` will become a rotate.

**Comment by Aatch** [comment]
This doesn't seem worth it. While yes, there are instructions for doing this specific operation, on x86 at least, it's slower than doing a `not` and an `and`, as the x86 instruction is actually an MMX instruction (and uses the MMX execution units, of which there are far fewer). Furthermore, the related bit-test instructions seem to also have pretty high latencies, so it's no surprise LLVM is reluctant to generate them.

Testing with clang, the output is the same for x86 as rustc, an `and` and a `not`. Using clang's output as a proxy for rustc output for the same arch:

* **ARM** Outputs the `bic` ("bit clear") instruction, which is logically AND NOT.
* **MIPS** Outputs an `and` + `not`, as it doesn't have a single-instruction implementation.
* **PowerPC** Outputs `andc` which is "and with [ones] complement", aka AND NOT.

So given that we can't actually generate a direct ANDNOT at the LLVM level (it doesn't have an instruction for it) and LLVM clearly generates the equivalent instruction when it thinks it's the best option, I'm going to say that a special operator for this case is unnecessary. Given that you'd read `a & !b` as "'a' and not 'b'", I don't think there's any real advantage to making is special.

(For comparison, `a ^ b` is `(a | b) & !(a & b)`, which isn't exactly obvious)

**Comment by Gankro** [comment]
I agree with the others. I've also never seen this operator in any other language, so there's not exactly a precedent.
