### ISSUE TITLE
Confusing error message (compiler expects `fn` but found `fn`) on macro expantion

### ISSUE THREAD

**Issue by uzytkownik** [rust-lang/rust#27314]
``` rust
macro_rules! test {
    ($Trait:ident, {$($items:tt)*}) => {
        trait $Trait {
            $($items)*
        }
    }
}

test!(Foo, {
    fn test() {}
});
```

Error message:

```
<anon>:4:15: 4:21 error: expected one of `const`, `extern`, `fn`, `type`, or `unsafe`, found `fn`
<anon>:4             $($items)*
                       ^~~~~~
playpen: application terminated with error code 101
```

(the problem in code seems related to issue #22694)

**Comment by bsteinb** [comment]
I think I just hit some form of this issue: [playpen](http://is.gd/KAx9Pc). I am not sure whether this is really about diagnostics and confusing error messages. Is macro expansion allowed inside trait bodies? Book and reference only seem to say they can expand to items.

**Comment by Mark-Simulacrum** [comment]
This now works. Closing.
