### ISSUE TITLE
error: internal compiler error: unexpected panic while building nix-rust

### ISSUE THREAD

**Issue by MarkusJais** [rust-lang/rust#27321]
Hello,

for my latest PR for mq_unlink support in nix-rust the Travis build fails with a message that says:

error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.

The PR where this happes can be found here:

https://github.com/carllerche/nix-rust/pull/167

That part looks suspicious:
hread 'rustc' panicked at 'assertion failed: (left == right) (left: '&', right: ']')', ../src/librustc/metadata/tydecode.rs:567
Could not compile rand.

Here is a broken build:
https://travis-ci.org/carllerche/nix-rust/jobs/72583927

Hope this helps.

Markus

**Comment by arielb1** [comment]
This looks like a metadata version mismatch. Closing.
