### ISSUE TITLE
Test examples in extended diagnostics

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#27328]
The [extended error explanations](https://github.com/rust-lang/rust/blob/master/src/librustc/diagnostics.rs) are filled with amazing examples, but they are not validated in any way.

Having these tested would be a great extension to the test suite and ensure that they do not become misleading as they bitrot.

Since many of these examples don't compile, we might need to improve rustdoc's testing of compile failures.

cc @GuillaumeGomez @steveklabnik

**Comment by brson** [comment]
cc @michaelsproul

**Comment by brson** [comment]
Once we have compile-fail tests for docs there are a bunch of examples in the docs that can be tested.

For now, we can not deal with unstable features in compile-fail tests and continue to ignore such examples.

**Comment by michaelsproul** [comment]
Interesting! I've been pretty busy with uni-related stuff but I'll have more Rust time in a month or so!

**Comment by GuillaumeGomez** [comment]
I'm starting to work on it.
