### ISSUE TITLE
Cargo/rustc fails to compile a project when it is located on one specific Windows drive

### ISSUE THREAD

**Issue by kirillkh** [rust-lang/rust#27329]
I get unexpected errors when running 'cargo build' on a very simple project that basically just imports 'num' crate. The problem happens when I try to compile a project with this Cargo.toml (I can reproduce the problem with just this file in the directory and nothing else.)

Cargo.toml: https://play.rust-lang.org/?gist=53cd0fb058d3e5801df0&version=stable

RUST_LOG=cargo,rustc::metadata cargo build -v: https://gist.github.com/kirillkh/3080f95476ab0bb15cc8

The problem happens only when the project directory is located on one specific Windows drive (M:). It doesn't happen when the directory is located on any of my other 3 drives. The drive passes chkdsk without errors, the project directory is recursively owned by my user, and my user has recursive full access permissions on it.

One special thing about the drive is that it is of 1.5Tb size. Perhaps there is an integer overflow?

**Comment by kirillkh** [comment]
According to what acrichto told me on IRC (if I understood correctly), the problem is that Cargo passes the project-specific libc candidate, but rustc picks the bundled version:

INFO:rustc::metadata::loader: lib candidate: M:\pirust\target\debug\deps\liblibc-d5e533d3fc4af810.rlib
INFO:rustc::metadata::loader: lib candidate: H:\devel\rust\bin\rustlib\i686-pc-windows-gnu\lib\liblibc-74fa456f.rlib
INFO:rustc::metadata::loader: rlib reading metadata from: \\?\H:\devel\rust\bin\rustlib\i686-pc-windows-gnu\lib\liblibc-74fa456f.rlib

I would also question why cargo even passes a potentially incompatible version of libc. If it didn't, the problem would have been much easier to nail down.

**Comment by kirillkh** [comment]
Well, I have traced the issue to get_path() in sys/windows/fs.rs.
GetFinalPathNameByHandleW() results in a failure (code: 3, message: "The system cannot find the path specified.") when the file is on m: drive.

Furthermore, if I change VOLUME_NAME_DOS to other values, I get different results:
VOLUME_NAME_DOS => Error(...)
VOLUME_NAME_GUID => Ok("\\?\Volume{e937bd64-1760-11e4-bb64-000acd03f995}\vcredist.bmp")
VOLUME_NAME_NONE => Ok("\vcredist.bmp")
VOLUME_NAME_NT => Ok("\Device\HarddiskVolume5\vcredist.bmp")

A quick Google search didn't produce any explanation to this.

**Comment by alexcrichton** [comment]
Fascinating! I think that's definitely the problem here. I wonder why it's returning an error for the `DOS` case? The [documentation says](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364962%28v=vs.85%29.aspx):

> Can be returned if you are searching for a drive letter and one does not exist. For example, the handle was opened on a drive that is not currently mounted, or if you create a volume and do not assign it a drive letter. If a volume has no drive letter, you can use the volume GUID path to identify it.
>
> This return value can also be returned if you are searching for a volume GUID path on a network share. Volume GUID paths are not created for network shares.

It sounds like though you've got a drive letter and it's mounted? That's somewhat confusing...

cc @retep998, @klutzy

**Comment by kirillkh** [comment]
Oh it is mounted for sure. Perhaps something is broken inside Windows' guts, but other programs seem to work fine with it...

**Comment by kirillkh** [comment]
Minimal test case: https://gist.github.com/kirillkh/5549fca1089d18835da0

**Comment by kirillkh** [comment]
Well, I have reset the drive letter in Windows, and the problem is gone. Maybe it's still a good idea to investigate why rustc was trying to use the incompatible bundled libc version, though.

**Comment by steveklabnik** [comment]
Triage: given that nobody seems to have seen this in a year and a half, I'm going to give this a close. Thanks @kirillkh !
