### ISSUE TITLE
Remove morestack dependency.

### ISSUE THREAD

**Issue by ababo** [rust-lang/rust#27332]
As we know the concept of segmented stack has been already abandoned. But for freestanding build the Rust compiler still complains about missing *libmorestack.a*:

> rustc --crate-type rlib,staticlib --target x86_64-unknown-linux-gnu -C opt-level=3 -C no-stack-check -Z no-landing-pads --cfg arch_x86_64 --sysroot /dev/null -L /path/to/lib.rs -o /path/to/libcore.rlib

> error: could not find native static library `morestack`, perhaps an -L flag is missing?

I suppose this dependency should be removed.

**Comment by alexcrichton** [comment]
I believe this is covered by #16012, so closing in favor of that.
