### ISSUE TITLE
Make OOM a lang item

### ISSUE THREAD

**Issue by Gankro** [rust-lang/rust#27335]
Currently `alloc::oom` just calls `intrinsics::abort` making the program look like it faulted, when really we killed it in a controlled manner. The reason it does that is that liballoc only assumes we have an allocator and no other OS/runtime.

However if oom was a lang item, we could implement it *only* in std, and have it print a message without allocating using 

```rust
std::rt::abort("Allocator returned out of memory, aborting program")
```

no_std users could also opt into custom oom hooks, though they still have to crash the program.

We could also potentially add a flag for building std that makes oom unwind instead.

**Comment by alexcrichton** [comment]
Sounds like a good plan to me! This would basically use the same infrastructure as `panic_fmt` and friends.

**Comment by steveklabnik** [comment]
Isn't this more of an RFC kinda thing?

**Comment by steveklabnik** [comment]
Yes, seems like it would be. Let's go that route, please!
