### ISSUE TITLE
difficulty with binding example in patterns.md

### ISSUE THREAD

**Issue by zjttoefs** [rust-lang/rust#27347]
The second example for the bindings contains advanced syntax that the reader has not seen (at leat to the best of my knowledge when skipping "learn rust"). Those bits:

```rust
let mut x: Option<Person> = Some(Person { name: Some(name) });
match x {
    Some(Person { name: ref a @ Some(_), .. }) => println!("{:?}", a),
    _ => {}
}
```

This `Some` business is new and the matching of the inner type far from obvious. 
Even the format string `"{:?}"` is not explained. 

As an aside: There is no index that would find where `Some` is actually covered in the book.

(Otherwise: Well done on the book!)

**Comment by zjttoefs** [comment]
Both the `ref` and that use of `..` are forward references within the same page. So just reordering a bit would help a lot.

**Comment by steveklabnik** [comment]
Thanks! Yeah, this can certainly use some cleaning up.
