### ISSUE TITLE
Compiler UI/UX Design Guidelines Document

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#27344]
There's a lot of compiler UI and UX rules that exist in the developer mindshare, but are not documented anywhere. They aren't really Rust code style guidelines, since they only apply to the compiler (and possibly compiler plugins), so we really need to have another document for them.

A couple examples for this are:

* Error messages **MUST NOT** use `illegal` when `invalid` or similar works. See issue #27288.
* `Error` and `Warning` messages **SHOULD NOT** suggest how to fix them. If there is a common fix, they should be done with a `Note`.

**Comment by Havvy** [comment]
So, if I wanted to start this, where should I put this? I'm thinking /src/doc/ux-guidelines.

**Comment by P1start** [comment]
Suggestions for fixing errors should normally be `help`s, not `note`s. Also, errors should always start with a lowercase letter and not end in a full stop.

**Comment by steveklabnik** [comment]
closing in favor of https://internals.rust-lang.org/t/pre-rfc-rustc-ux-guidelines/2419 and the eventual RFC
