### ISSUE TITLE
Path join() not joining correctly with relative path: "./something"

### ISSUE THREAD

**Issue by azerupi** [rust-lang/rust#27354]
When you join a path with a relative path like `./something` it does not strip the `./`

For example ([Playpen](https://play.rust-lang.org/?gist=004728342ced073706bd&version=nightly))
```rust
fn main() {
    let base = PathBuf::from("/some/path");
    let relative = PathBuf::from("./some/relative/path");
    let path = base.join(relative);
    println!("{:?}", path);
}
```
Output:
```
"/some/path/./some/relative/path"
```

I may be wrong, but I think it should output: 
```
"/some/path/some/relative/path"
```

**Comment by nagisa** [comment]
Both paths are valid and have the same meaning.

**Comment by alexcrichton** [comment]
cc @aturon

**Comment by azerupi** [comment]
> Both paths are valid and have the same meaning.

I was not aware of that, in that case it's a lot less relevant.

**Comment by retep998** [comment]
Also note that Rust tries not to normalize your paths unless you specifically ask for it, due to the different ways that platforms will interpret paths. In particular, verbatim paths on Windows (paths that start with `\\?\`) will treat `.` as the literal name of a directory, rather than having a special meaning.

**Comment by aturon** [comment]
As @retep998 said, the path system doesn't normalize in general (and in particular doesn't change the string representation). If you ask various questions like "give me the components of this path" or "are these two paths equal?" you'll get answers based on a small amount of normalization.

For example:

```rust
fn main() {
    let base = PathBuf::from("/some/path");
    let relative = PathBuf::from("./some/relative/path");
    let path = base.join(relative);
    println!("{:?}", path);
}
```

I'm going to close this as working-as-intended. Thanks for the report!
