### ISSUE TITLE
Cargo.toml confused by [dependencies.url]

### ISSUE THREAD

**Issue by davidpbrown** [rust-lang/rust#27363]
Using Cargo.toml [dependencies.url] in error against some named crate.io, will lead to compile errors, rather than suggesting some "failed to parse" error against Cargo.toml.

For example:
```
[dependencies.url]
regex = "*"
git = "https://github.com/servo/rust-url"
```
will lead to 
> error: can't find crate for \`regex\`

Searching that error then leads to more confusion, against old bugs that don't suggest anything of Cargo.toml structure.

Better would be to test dependencies.url detail and if not of the form ["url_string"] and instead [name = "name"], then suggest structure of Cargo.toml is confused.

**Comment by sfackler** [comment]
This should probably be filed on https://github.com/rust-lang/cargo

**Comment by davidpbrown** [comment]
oops.. will do.
