### ISSUE TITLE
Error E0399 regression on nightly from beta.

### ISSUE THREAD

**Issue by dylanede** [rust-lang/rust#27377]
I have found that with a trait of the form
```
trait Foo {
    type A = ();
    fn get_a(&self) -> Option<Self::A> { None }
    type B = ();
    fn get_b(&self) -> Option<Self::B> { None }
}

impl Foo for () {
    type A = ();
}
```
I get the following error message on nightly (as of the time of this post), but not on beta.
```
<anon>:9:5: 9:17 error: the following trait items need to be reimplemented as `A` was overridden: `get_a`, `B`, `get_b` [E0399]
<anon>:9     type A = ();
```
I can possibly understand `get_a` needing to be reimplemented, but `B` and `get_b` as well?
I don't get the error message when types do not have defaults, like so:
```
trait Foo {
    type A;
    fn get_a(&self) -> Option<Self::A> { None }
    type B = ();
    fn get_b(&self) -> Option<Self::B> { None }
}

impl Foo for () {
    type A = ();
}
```
Note that it no longer errors out saying that the methods need to be reimplemented.

**Comment by arielb1** [comment]
That's completely intentional. In fact, 1.2.0 will soon warn on that condition too (#27364).

**Comment by dylanede** [comment]
@arielb1 Why is that intentional? It makes implementing traits that have a lot of default types and methods annoying, since often it makes having default types and methods useless.

**Comment by dylanede** [comment]
Having looked at the relevant part in the RFC, I can't see why that approach was taken. It makes more sense to me for the default function implementations to only be allowed to assume the constraints on the associated types, not their default types.

**Comment by aturon** [comment]
@dylanede See https://github.com/rust-lang/rust/pull/26728#issuecomment-126028594 -- we are planning to feature gate defaulted associated types, and will likely alter the semantics away from the RFC toward a design like the one you suggest.

**Comment by steveklabnik** [comment]
Should this issue be closed?

**Comment by dylanede** [comment]
If it is going to be closed then an issue about the changes to the design from the RFC that @aturon talked about should be opened first.

**Comment by steveklabnik** [comment]
I'm going to give this one a close, in favor of https://github.com/rust-lang/rust/issues/29661 , the one tracking stabilizing associated types.
