### ISSUE TITLE
Allow late environment capture for closures

### ISSUE THREAD

**Issue by jucs** [rust-lang/rust#27408]
I suggest to allow a closure to capture their environment either at its call site or whenever a reference to the closure leaves the scope in which it can access the environment.

This would allow the following code which is a very common use case of lambdas and is currently rejected by the borrow checker:

```Rust
let mut x = 42;
let f = || x += 1;
x += 42;
f()
```
I can't see any reason to capture the environment at the definition site of the lambda. If, however, my suggestion has some drawbacks, it could also be considered to introduce a keyword 'late' which can be used as follows:

```Rust
let mut x = 42;
let f = late || x += 1;
x += 42;
f()
```

**Comment by steveklabnik** [comment]
A significant language change like this would need to go through the RFC process. Please pursue this over there! https://github.com/rust-lang/rfcs/
