### ISSUE TITLE
Rustbook isn't stripping %'s

### ISSUE THREAD

**Issue by Gankro** [rust-lang/rust#27404]
https://doc.rust-lang.org/nightly/adv-book/

and

https://doc.rust-lang.org/nightly/book/

Show the title rendered twice, once as a header, once as `% ...`

**Comment by Gankro** [comment]
CC @azerupi I imagine this is fallout from #26216

**Comment by azerupi** [comment]
I don't think it's me, but I will check.
Have there been any commits for Rustdoc? That is the first thing I would check because the markdown is rendered by Rustdoc.

**Comment by azerupi** [comment]
It's not happening on my local version. So I guess a commit between mine and now broke Rustdoc.

**Comment by Gankro** [comment]
CC @oli-obk

**Comment by Gankro** [comment]
(just pinging random people who seem to have been in there recently...)

**Comment by azerupi** [comment]
Yeah no problem ;) I have tried to search the commit logs but I failed miserably. There are so many..
