### ISSUE TITLE
Bikeshed "The Advanced Rust Programming Language" as a name

### ISSUE THREAD

**Issue by Gankro** [rust-lang/rust#27412]
@dherman suggested this iirc -- but I can't remember.

@brson is concerned that it is too similar

Originally it was called *The Unsafe Rust Programming Language* since it largely focuses on unsafe code and the stuff that matters to it.

**Comment by brson** [comment]
Here are my problems with the current arrangement:

* A second book, and one that claims to be 'advanced', diminishes both the significance of 'The Book' and it's brand. It will never have the stature of 'The C Programming Language' if it has a more 'advanced' big brother looming over it.
* Multiple separate books is a path to balkanization of the docs, where Steve gets his docs, Gankro gets his docs, I get my docs and nobody's working together.
* Practically, if we now publish The Book, we have to exclude a big chunk of information that people would probably want included.
* The name is inaccurate - this is a document about unsafe programming. 'Advanced' has many connotations. This isn't advanced concurrency, advanced architectural design - it's advanced unsafe.

**Comment by steveklabnik** [comment]
@brson and I are basically on the same page when it comes to "Advanced," I had the exact same thoughts.

**Comment by Gankro** [comment]
Discussing at lunch the top contender became "The Rustinomicon" in reference to the fact that this is dark magic that mere mortals dare not tamper with.

**Comment by Toby-S** [comment]
@Gankro does it need to be separate from TRPLB? Essentially echoing what @brson said, anyone who wants to understand rust to a decent standard will probably want to know this stuff.

**Comment by Gankro** [comment]
@Toby-S the important thing about this text, and indeed Rust itself, is that *you don't need to know it*. This is a book for all the horrible details unsafe code entails. I believe it would be a mistake to include it with THE book, which *is* Everything You Need To Know.

**Comment by pnkfelix** [comment]
(I thought was going to be spelled "Rust**o**nomicon", since we're implicitly making references to "Necr**o**nomicon" and "Crypt**o**nomicon".)

**Comment by pnkfelix** [comment]
(oh, oh: https://github.com/Gankro/rust/commit/7570be85dde329a48fa857dbc44dd98fbc24e712 )
