### ISSUE TITLE
Getting started in the book should state how to get a backtrace

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#27428]
This is the most annoying and most useless error message ever if you don't know how to get a backtrace. The docs should state how to get one. Without a backtrace it's only helpful if you already know where the error isn't always the case.

This:
```rust
vec![1, 2][7];
```

Returns:
```cmd
thread '<main>' panicked at 'index out of bounds: the len is 2 but the index is 7', /home/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcollections/vec.rs:1359
playpen: application terminated with error code 101
```

**Comment by kstep** [comment]
A better option may be not the full traceback by default, but just make panic point to user's code, not code from std, as Perl's [Carp](http://search.cpan.org/~rjbs/Carp-1.36/lib/Carp.pm) does, by unwinding stack trace up to the point where it goes out of "trusted" std code.

**Comment by kstep** [comment]
I know ask the problems with unwinding, but it's already there when you print traceback anyway, why not make another step to users?

**Comment by mdinger** [comment]
Nice! Now it's at least documented.
