### ISSUE TITLE
Is there plan to add `Result<T, E>.expect_err` method?

### ISSUE THREAD

**Issue by FuGangqiang** [rust-lang/rust#27425]
`Result<T, E>` has `unwrap` and `expect` method yielding `Ok`,
but only has `unwrap_err` yielding `Err`, there isn't `expect_err` method.

**Comment by cybergeek94** [comment]
Not enough demand, maybe? Rust follows a minimalist philosophy: the standard library doesn't try to cover all possible use-cases, only the ones that appear to be most common.

That said, this sounds like it could be pretty useful, especially in unit tests functions with `#[should_fail]`. I don't see any mention of an `expect_err` counterpart on the discussion for the original [`Result::expect()` RFC](https://github.com/rust-lang/rfcs/pull/1119). I guess no one thought to consider it.

If you want to try drafting an RFC to propose adding `Result::expect_err()`, [this is a good place to start](https://github.com/rust-lang/rfcs#before-creating-an-rfc). It's common practice to post the draft on https://internals.rust-lang.org first to get feedback on it.

**Comment by steveklabnik** [comment]
Triage: today, small additions like this don't need a full RFC, just a PR. @FuGangqiang if you (or anyone else) would like to send a PR in for this, it can be discussed there. But since this is a small request and nobody has commented in over a year, I'm going to give this issue a close. Thanks!
