### ISSUE TITLE
the type placeholder `_` is not allowed within types on item signatures should hint at generics

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#27435]
The following signature yields the mentioned error

``` rust
fn shuffle(args: Vec<_>) -> Vec<_>
```

it should be replaced by

``` rust
fn shuffle<T>(args: Vec<T>) -> Vec<T>
```

There should be an error hint suggesting this change.

**Comment by aatxe** [comment]
:+1: 

I've been wanting this for a while. (As well as sugar to make `Vec` equivalent to `Vec<_>`, but I imagine that might be unpopular.)

**Comment by arielb1** [comment]
@aatxe 

Generic Elision isn't going to be a supported feature (you *do* need to be able to specify type parameters in paths - e.g. `foo::<T>`).

**Comment by cyplo** [comment]
Hi ! @arielb1: does it mean this issue can be closed ?

**Comment by estebank** [comment]
[Current output](https://play.rust-lang.org/?gist=eec46df7bf9330a34d5524b6c925130a&version=nightly):

```
error[E0121]: the type placeholder `_` is not allowed within types on item signatures
 --> src/main.rs:1:22
  |
1 | fn shuffle(args: Vec<_>) -> Vec<_> {}
  |                      ^ not allowed in type signatures

error[E0121]: the type placeholder `_` is not allowed within types on item signatures
 --> src/main.rs:1:33
  |
1 | fn shuffle(args: Vec<_>) -> Vec<_> {}
  |                                 ^ not allowed in type signatures
```
