### ISSUE TITLE
Invalid error (E0425) reported

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#27433]
In the following code:

``` Rust
fn main() {
    let foo = 42u32;
    const FOO : u32 = foo;
}
```

We have the following errors:

``` Shell
<anon>:3:23: 3:26 error: attempt to use a non-constant value in a constant [E0435]
<anon>:3     const FOO : u32 = foo;
                               ^~~
<anon>:3:23: 3:26 error: unresolved name `foo` [E0425]
<anon>:3     const FOO : u32 = foo;
```

The first one is "normal", however, the E0425 might mislead developer's understanding on this error.

cc @eddyb

**Comment by eddyb** [comment]
IMO the second error is fine, because the local `foo` variable is not in scope for the `FOO` constant item.
The first one could be a note instead of an error and rephrased, perhaps.

**Comment by brson** [comment]
Current output:

```
fn main() {
    let foo = 42u32;
    const FOO : u32 = foo;
}
```

Seems fixed cc @GuillaumeGomez

**Comment by brson** [comment]
Just add test.

**Comment by GuillaumeGomez** [comment]
@brson: Do you have the PR which fixed this issue by any chance? (so I can add the test accordingly to it if still needed)

**Comment by brson** [comment]
@GuillaumeGomez no I do not. I just noticed that the op is working.

**Comment by estebank** [comment]
@brson [test merged](https://github.com/rust-lang/rust/pull/39653), this issue be closed.
