### ISSUE TITLE
Optimize EBML encoding

### ISSUE THREAD

**Issue by catamorphism** [rust-lang/rust#2743]
"optionally perform 'relaxations' on end_tag to more efficiently encode sizes; this is a fixed point iteration" (from ```std::ebml```)

**Comment by steveklabnik** [comment]
triage: removing libs, since we aren't exposing this publicly.

**Comment by lucaszanella** [comment]
What is std::ebml?

**Comment by steveklabnik** [comment]
@lucaszanella this bug is from 2012. It's something that existed then, but does not exist now.

**Comment by lucaszanella** [comment]
> @lucaszanella this bug is from 2012. It's something that existed then, but does not exist now.

I was searching for ebml libs on Rust. Was this one?
