### ISSUE TITLE
rustc panics if the terminal's terminfo is invalid

### ISSUE THREAD

**Issue by anachrome** [rust-lang/rust#27446]
If the terminfo for my terminal is malformed, rustc panics with

```
thread '<main>' panicked at 'assertion failed: `(left == right)` (left: `0`, right: `2`)', /home/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libterm/terminfo/parser/compiled.rs:315
```

The simplest reproduction is

```
touch ~/.terminfo/r/rxvt-unicode-256color
```

or whatever the `$TERM` variable is.

**Comment by bluss** [comment]
It looks like this is fixed in "upstream" libterm, so requires import from there.

**Comment by brson** [comment]
Fixed. Needs test.

**Comment by Mark-Simulacrum** [comment]
I don't really think this needs a test or at least not inside rustc itself; closing.
