### ISSUE TITLE
compiler error on crate hyper 0.6.6 (solicit v.0.4.0)

### ISSUE THREAD

**Issue by fatcrack** [rust-lang/rust#27443]
I just tried to include extern crate hyper = "*" -> 0.6.6
when crate starts building there is an internal compiler error:

Cargo.toml
[dependencies]
hyper="*"

$ rustc --version
rustc 1.3.0-nightly (freebsd)

$ cargo build
   Compiling solicit v0.4.0
src/libcore/iter.rs:804:35: 804:42 error: internal compiler error: Encountered errors `[FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<http::session::DefaultStream as core::cmp::PartialOrd>)),depth=1),Unimplemented)]` fulfilling during trans
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', src/libsyntax/diagnostic.rs:176

Could not compile `solicit`.

To learn more, run the command again with --verbose.
$ cargo build --verbose
       Fresh traitobject v0.0.1
       Fresh libc v0.1.8
       Fresh winapi v0.2.1
       Fresh winapi-build v0.1.1
       Fresh unicase v0.1.0
       Fresh typeable v0.1.2
       Fresh rustc-serialize v0.3.15
       Fresh pkg-config v0.3.5
       Fresh httparse v0.1.5
       Fresh matches v0.1.2
       Fresh lazy_static v0.1.12
       Fresh language-tags v0.0.7
       Fresh gcc v0.3.12
       Fresh bitflags v0.3.2
       Fresh log v0.3.1
       Fresh num_cpus v0.2.6
   Compiling solicit v0.4.0
     Running `rustc /home/mrx/.cargo/registry/src/github.com-0a35038f75765ae4/solicit-0.4.0/src/lib.rs --crate-name solicit --crate-type lib -g -C metadata=c21ee68bf7520de5 -C extra-filename=-c21ee68bf7520de5 --out-dir /home/mrx/coding/rust/crawl/target/debug/deps --emit=dep-info,link -L dependency=/home/mrx/coding/rust/crawl/target/debug/deps -L dependency=/home/mrx/coding/rust/crawl/target/debug/deps --extern log=/home/mrx/coding/rust/crawl/target/debug/deps/liblog-8a6aba167994951e.rlib --extern hpack=/home/mrx/coding/rust/crawl/target/debug/deps/libhpack-37abaf37ec66685c.rlib -Awarnings`
       Fresh url v0.2.36
       Fresh mime v0.0.12
       Fresh hpack v0.2.0
       Fresh kernel32-sys v0.1.3
       Fresh openssl-sys v0.6.4
       Fresh time v0.1.32
       Fresh openssl v0.6.4
       Fresh cookie v0.1.21
src/libcore/iter.rs:804:35: 804:42 error: internal compiler error: Encountered errors `[FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<http::session::DefaultStream as core::cmp::PartialOrd>)),depth=1),Unimplemented)]` fulfilling during trans
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', src/libsyntax/diagnostic.rs:176

Could not compile `solicit`.

Caused by:
  Process didn't exit successfully: `rustc /home/mrx/.cargo/registry/src/github.com-0a35038f75765ae4/solicit-0.4.0/src/lib.rs --crate-name solicit --crate-type lib -g -C metadata=c21ee68bf7520de5 -C extra-filename=-c21ee68bf7520de5 --out-dir /home/mrx/coding/rust/crawl/target/debug/deps --emit=dep-info,link -L dependency=/home/mrx/coding/rust/crawl/target/debug/deps -L dependency=/home/mrx/coding/rust/crawl/target/debug/deps --extern log=/home/mrx/coding/rust/crawl/target/debug/deps/liblog-8a6aba167994951e.rlib --extern hpack=/home/mrx/coding/rust/crawl/target/debug/deps/libhpack-37abaf37ec66685c.rlib -Awarnings` (exit code: 101)
$

**Comment by sanxiyn** [comment]
solicit 0.4.0 hits RFC 1214 WF change (namely Self: Sized) now. It is likely this is the same issue.

rustc has WF change now, and solicit was fixed in mlalic/solicit@d50634e.
