### ISSUE TITLE
Entry point `_ZSt24__throw_out_of_range_fmtPKcz` not found in `libstdc++6.dll`

### ISSUE THREAD

**Issue by tomaka** [rust-lang/rust#27452]
I cloned and compiled https://github.com/steveklabnik/rustbook on Windows 32bits.

When trying to run the `rustbook.exe` executable, I get an error about entry point `_ZSt24__throw_out_of_range_fmtPKcz` not found in `libstdc++6.dll` (the exact message is in french for me). Happens in both debug and release.

Rust version: (32bits)

> rustc 1.3.0-nightly (4dfe7a16c 2015-07-30)

**Comment by alexcrichton** [comment]
This may be because the version of the C++ standard library is different from the builders perhaps?

**Comment by tomaka** [comment]
Isn't Rust supposed *not* to link to `libstdc++6.dll`? (that's why I opened this issue)

**Comment by tomaka** [comment]
Plus the fact that even though I've been using this installation for the past year or so and compiled a lot of programs with it, this is the first Rust program ever to give me this error.

**Comment by alexcrichton** [comment]
rustbook [links to the compiler](https://github.com/steveklabnik/rustbook/blob/master/src/main.rs#L18-L19) which pulls in LLVM which requires the C++ standard library.

**Comment by Gankro** [comment]
steve's rustbook repo is a trap, as far as I know. rustbook is basically hardcoded to look for the stage2 artifacts it was supposed to be built with. Here's my instructions for getting a valid rustbook instance:

https://github.com/Gankro/too-many-lists/#building

(--enable-rpath is the secret sauce)

**Comment by tomaka** [comment]
Oh I see, I should have taken a look at the source code.
