### ISSUE TITLE
Possible error about variance in the nomicon

### ISSUE THREAD

**Issue by diaphore** [rust-lang/rust#27457]
[In the paragraph about the variance of `&mut T`](https://github.com/rust-lang/rust/blame/master/src/doc/tarpl/subtyping.md#L97)

> (...) If `&mut T` was variant over T, then `&mut &'a str` would be a subtype of `&mut &'static str`,
__since `&'a str` is a subtype of `&'static str`.__ (...)

The exact opposite is said at the beginning of the chapter :

> Subtyping on lifetimes is in terms of that relationship: if `'a: 'b` ("a contains
b" or "a outlives b"), then `'a` is a subtype of `'b`.

Also, the doc seems to be meant for the Randolf-Carters of this world or the others, and while it is nice to introduce the more abstract notion of subtyping early on, it would be much more readable if "is a subtype of" were replaced with "outlives" in the later explanations IMHO.

@Gankro

**Comment by Gankro** [comment]
Oops! Good catch.

**Comment by steveklabnik** [comment]
@Gankro we should discuss tagging for the nomicon, for now, tagging with docs and assigning to you
