### ISSUE TITLE
std::ptr::null() should perhaps use `llvm::ConstantPointerNull` rather than `0 as *const T`

### ISSUE THREAD

**Issue by nodakai** [rust-lang/rust#27466]
- http://llvm.org/docs/doxygen/html/classllvm_1_1ConstantPointerNull.html

But I know of no platform where `0 as *const T` is wrong!  Maybe not that important...
- http://stackoverflow.com/questions/12126252/what-does-nvidia-gpu-do-with-device-memory-0x0
- https://software.intel.com/en-us/articles/the-generic-address-space-in-opencl-20

**Comment by Gankro** [comment]
`0 as *const T` is pretty pervasive last I checked... I'd be surprised if
we could ever work on a platform where 0 is not null.

**Comment by eefriedman** [comment]
llvm::ConstantPointerNull is defined to be equivalent to inttoptr of zero; switching from one to the other is completely pointless.

**Comment by sfackler** [comment]
C converts the integral constant 0 when used in a pointer context to the platform null pointer value. It seems like we'd need to do the same if we wanted to handle platforms with a non-zero null pointer, though that rule seems kind of insane and really error prone.

**Comment by steveklabnik** [comment]
Given @eefriedman 's comment and the lack of consensus here and lack of comments in over a year, I'm going to give this one a close. @nodakai if you feel strongly that we should do this, let me know!
