### ISSUE TITLE
Stabilization of weak pointers

### ISSUE THREAD

**Issue by aepsil0n** [rust-lang/rust#27465]
Currently, both `alloc::rc::Weak` and `alloc::arc::Weak` are unstable. The somewhat vague reason for this is that *weak pointers may not belong in this module*. Now this has been addressed multiple times in #24028 and I have been observing this situation for a few months. However, as far as I can tell, nothing has happened so far.

Stabilizing my FRP library Carboxyl is currently blocked on this issue (see aepsil0n/carboxyl#47). Hence, I would really, really love to see this stabilized.

So my main question there is: is it really, as the instability note indicates, just a matter of discussing whether it should be moved to another module? Or is there anything more to it? In either case I would be happy to help out with anything that needs doing.

I did some archeology on the git logs. And, apparently @brson marked `alloc::rc::Weak` as unstable a year ago in cf8bfde. Shortly thereafter, @alexcrichton adapted this policy to `alloc::arc::Weak` in e5da6a7. So perhaps one of you could comment on the motivation behind that and whether it still applies today?

**Comment by bluss** [comment]
See the active dicussion at rust-lang/rfcs#1232

**Comment by aepsil0n** [comment]
Thank you for the hint. I had not picked up that RFC yet.

**Comment by alexcrichton** [comment]
Yeah the RFC @bluss linked is where discussion is happening now so I'm going to close this in favor of that
