### ISSUE TITLE
trim and related giving unexpected behavior on strings with many nulls

### ISSUE THREAD

**Issue by shaleh** [rust-lang/rust#27462]
#[test]
    fn validate_trim() {
        let s: &str = "QUIT\r\n";
        let s2: &str = "\x51\x55\x49\x54\x0d\x0a";
        let buf: [u8; 6] = [ 81u8, 85u8, 73u8, 84u8, 13u8, 10u8 ];
        let buf2: [u8; 16] = [ 0x51u8, 0x55u8, 0x49u8, 0x54u8, 0x0Du8, 0x0Au8,
                               0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ];
    
        let input: &str = str::from_utf8(&buf).unwrap();
        let input2: &str = str::from_utf8(&buf2).unwrap();
    
        assert_eq!("QUIT", s.trim());
        assert_eq!("QUIT", s.trim_right());
    
        assert_eq!("QUIT", s.trim());
        assert_eq!("QUIT", s2.trim_right());
    
        assert_eq!("QUIT", input.trim());
        assert_eq!("QUIT", input.trim_right());
    
        assert_eq!("QUIT", input2.trim());            // FAILS
        assert_eq!("QUIT", input2.trim_right());   // FAILS
    }

    	thread 'validate_trim' panicked at 'assertion failed: `(left == right)` (left: `"QUIT"`, right: `"QUIT\r\n\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}"`)'

**Comment by nagisa** [comment]
I’m pretty sure this bug is inactionable. Null bytes are not whitespace and rust strings may contain as many of them as necessary at any position in the string, hence there’s no reason to expect null bytes should not exist or that they should be trimmed.

**Comment by shaleh** [comment]
I expect that the nulls are there. But it should skip them at the end and still remove the 0x0D and 0x0A. It is those which are problematic.

**Comment by nagisa** [comment]
This `\r\n` newline sequence is in a middle of the string not at the end or beginning of it. Documentation for trim says:

> Returns a &str with leading and trailing whitespace removed.

**Comment by shaleh** [comment]
Why? Null means end of string. If I print that string it stops at the newline. All trim_right should be doing is find end and work in.

On August 1, 2015 4:20:09 PM PDT, Simonas Kazlauskas <notifications@github.com> wrote:
>This `\r\n` newline sequence is in a middle of the string not at the
>end or beginning of it. Documentation for trim says:
>
>> Returns a &str with leading and trailing whitespace removed.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/rust-lang/rust/issues/27462#issuecomment-126961286

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by Diggsey** [comment]
Null doesn't mean end of string.

**Comment by bluss** [comment]
You can use a custom pattern with `.trim_matches()` to strip both whitespaces and nulls if you want.

**Comment by shaleh** [comment]
I have code like this:

    let mut buf: [u8; 4096] = [0u8; 4096];
    
    loop {
        match stream.read(&mut buf) {
            Ok(count) => {
                // handle good read
            },
            Err(e) => {
                // handle bad read
            },
        }
    
        // need to wipe out contents of buf, I have been doing a dumb loop equiv of memset(buf, 0, count)
    }

This is classic tcp server stuff. I am not finding clarity in the Rust docs or elsewhere to do it in a more idiomatic way. Either the old blog posts don't compile or it is all one shot, one read example code.

My expectation is a zeroed out buffer can be read into a usable string some how. I do not want to go tangential here and talk about stream reads. The pattern I show is pretty normal though. Maybe documenting it as a Rust anti-pattern would be useful. At the least mentioning that unlike convention NUL chars are left in strings.

**Comment by Gankro** [comment]
@shaleh All you need to do is remember how far you've written and subslice the buffer to ignore the parts you never wrote to:

`let buf = &buf[..bytes_written];`

Then you can further process it in a normal fashion.

**Comment by Aatch** [comment]
As @nagisa said, nulls are not considered whitespace under the unicode definition, so trim shouldn't treat them as such. Closing as not-a-bug.
