### ISSUE TITLE
docs: add `meta` to the list of valid designators

### ISSUE THREAD

**Issue by IvanUkhov** [rust-lang/rust#27471]
The documentation [says](https://doc.rust-lang.org/reference.html#macro-by-example):

> Valid designators are item, block, stmt, pat, expr, ty (type), ident, path, tt (either side of the => in macro rules).

`meta` is presumably a valid designator as well.

Regards,
Ivan

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/27528 was merged so i'm closing this, thanks!
