### ISSUE TITLE
into_ascii_lowercase shouldn't be deprecated

### ISSUE THREAD

**Issue by pcwalton** [rust-lang/rust#27472]
We really really need it for performance in Servo.

**Comment by arielb1** [comment]
Can't you implement it yourself?

**Comment by mitsuhiko** [comment]
This is a very common operation. What's the use in deprecating it?

**Comment by Diggsey** [comment]
The deprecation reason is "would prefer to do this in a more general way". However, it seems like this is such a common operation that it would still be worth having the extra API surface as a convenience, even if a more general method is added later.

**Comment by alexcrichton** [comment]
This API is currently being deprecated for a number of reasons:

* It sticks out in terms of the API of the `ascii` module. It's an entirely separate trait and this sort of design pattern doesn't show up anywhere else in the standard library.
* It is not required for the standard library to implement this functionality, it can be done externally with no loss in terms of ergonomics or performance.
* It didn't seem to have enough usage to warrant deciding how to stabilize it.

We can publish a crate on crates.io if there is enough demand for functionality like this.

**Comment by apasel422** [comment]
This method no longer exists.
