### ISSUE TITLE
still some unneeded integer suffixes in the docs

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#27501]
I noticed recently that the FFI chapter still has `1u32` in places, from before integer fallback existed. That, along with any other suffixes, should be removed.

(I'm not sure how many there are, exactly, but looking around for more while those get fixed is a Good Idea)

**Comment by friedm** [comment]
I'd be happy to take this, if no one minds.

**Comment by friedm** [comment]
Some suffixes are left in the chapters about casting, traits, and overloads but they all seemed helpful for the reader.  There didn't seem to be any suffixes in the ffi chapter.

**Comment by nagisa** [comment]
May be closed?

**Comment by steveklabnik** [comment]
Thanks for doing that, @friedm
