### ISSUE TITLE
"Concurrency" section comes before "Traits" in TRPL

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang/rust#27510]
The [Concurrency](http://doc.rust-lang.org/nightly/book/concurrency.html) chapter of TRPL gives some background on `Send` and `Sync`, describing them as traits and giving a summary of their properties and how they allow preservation of memory safety in a concurrent context. But this section precedes any discussion of traits (unless one takes the "Learn Rust" path, where they are briefly mentioned) at all in the book. At the very least it could link to the "Traits" chapter of the following section.

Admittedly, I've been reading TRPL by jumping between sections (because I already have a decent grasp of the language... I think :-)), so I may well have missed a "suggested reading order" in an introductory chapter that would ease my concerns. I did see the paragraph that suggests jumping to either of the "Learn Rust" or "Syntax and Semantics" sections, depending on one's preference, but nothing I could find gave a suggestion of where "Effective Rust" fits in the order of one's personal curriculum.

**Comment by steveklabnik** [comment]
"Effective Rust" is a section that assumes you know the basics of Rust already, which is why it comes after "Learn Rust."

I may or may not be re-ordering these in the future, but they're in this order because of complaints about the _previous_ order... I can't at the moment talk about when and how it may happen, but at the moment, this is Not a Bug. Thanks though!

**Comment by tomjakubowski** [comment]
The "Learn Rust" section might could use some more information about traits then.

**Comment by steveklabnik** [comment]
Yeah, there's a number of issues for sure. Hopefully I can talk about plans soon.

**Comment by tomjakubowski** [comment]
Great! I'm looking forward to hearing more!

**Comment by tomjakubowski** [comment]
Thanks @steveklabnik
