### ISSUE TITLE
Missing information when spanning E0282

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#27513]
The function call note_obligation_cause seems to be missing after [this line](https://github.com/rust-lang/rust/blob/master/src/librustc/middle/traits/error_reporting.rs#L349-L352) but is present [here](https://github.com/rust-lang/rust/blob/master/src/librustc/middle/traits/error_reporting.rs#L357). Is it on purpose ?

cc @eddyb
cc @nikomatsakis

**Comment by nikomatsakis** [comment]
I recently noticed this myself. I added it back in a branch I'm working on, actually. Not sure how or why it got lost, perhaps as part of the code that implemented custom trait failure (`on_unimplemented`) reporting (but that's pure speculation on my part).

**Comment by GuillaumeGomez** [comment]
Perfect, don't forget to close this issue when your PR is merged. :p

**Comment by GuillaumeGomez** [comment]
@nikomatsakis: While you're in this file, can you remove this ";;" [here](https://github.com/rust-lang/rust/blob/master/src/librustc/middle/traits/error_reporting.rs#L356) please ? ^^

**Comment by birkenfeld** [comment]
Call is still not present, current location: https://github.com/rust-lang/rust/blob/855fb6192263a5c059325bb4b4e10b55e4e8ddbb/src/librustc/traits/error_reporting.rs#L669

**Comment by Mark-Simulacrum** [comment]
I can't find a problem today; I'm going to close -- if someone can find it, please do let us know!
