### ISSUE TITLE
repr C newtype for empty enum

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#27511]
It's currently legal to define the following type, even though `repr(C)` on empty enums is forbidden.

``` rust
    enum No {}
    #[repr(C)]
    struct Yes(No);
```

**Comment by eefriedman** [comment]
What's the problem?  Every instance of the struct "Yes" is guaranteed to have the same layout as it would in C. :)

(On a side note, the FFI lint only checks foreign items at the moment.)

**Comment by oli-obk** [comment]
I don't see how any `repr(C)` type could contain a type that is not `repr(C)`. I assumed it was an oversight

**Comment by steveklabnik** [comment]
> I don't see how any repr(C) type could contain a type that is not repr(C). I assumed it was an oversight

This sounds true to me as well, @nikomatsakis ?

**Comment by Gankro** [comment]
This is because repr(C) has dual meaning:

* lay out the fields in the order I give them and supress some interesting
optimizations
* Be compatible with C

You may be interested in the former without ever caring about the latter.
You may even be interested in the former without caring about some of the
nested types.

**Comment by nodakai** [comment]
> You may even be interested in the former without caring about some of the nested types.

@Gankro I don't see how the layout of the `[repr(C)]` type can be meaningful when its fields have unspecified layout.

We should at least see a warning for such an inconsistency.

**Comment by nikomatsakis** [comment]
@nodakai 

Well, imagine you have a struct like:

```rust
#[repr(C)]
struct Foo {
    bar: Bar,
    baz: Baz,
}

struct Bar { .. }
struct Baz { .. }
```

This tells me that the data for `Bar` will precede the data for `Baz` in memory, though it doesn't tell me anything about the fields of `Bar` and `Baz` (or size/alignment thereof). But it's still meaningful.

**Comment by nodakai** [comment]
@nikomatsakis 

> But it's still meaningful.

?? Seriously I can think of no practical uses.  Am I missing anything?

**Comment by arielb1** [comment]
@nodakai 

It allows you to interconvert `*const Foo` and `*const Bar`.

**Comment by Mark-Simulacrum** [comment]
It feels to me like the conclusion reached in this that, if anything, this is a diagnostics issue for a non-`repr(C)` type inside a `repr(C)` struct. However, what Gankro states [here] makes me think that isn't actually something we want to lint about. As such, I'm going to close. Please reopen if there's differing opinions.

[here]: https://github.com/rust-lang/rust/issues/27511#issuecomment-127772094
