### ISSUE TITLE
Docs: nomicon: missing word in send-and-sync.md

### ISSUE THREAD

**Issue by lady-segfault** [rust-lang/rust#27526]
In `send-and-sync.md`, there is a sentence where some word(s?) seem to be missing: 

> This means that they are unsafe to implement, and other unsafe code can that they are correctly implemented.

(I suppose it's something like "other unsafe code can ASSUME that..."?)

r? @Gankro 

PS: I'm not sure if this is the appropriate place to post this kind of feedback on the book, don't hesitate to tell me if other ways are more adapted :)

**Comment by Gankro** [comment]
Totally the right place! (and totally the right fix!)

**Comment by apasel422** [comment]
This was fixed in #27527.
