### ISSUE TITLE
Bad span for self type

### ISSUE THREAD

**Issue by marcusklaas** [rust-lang/rust#27522]
The high end of the span of `&SomeType` in

``` rust
trait Foo {
    fn handler(self: &SomeType);
}
```

is incorrectly set to `BytePos(0)`.

**Comment by marcusklaas** [comment]
It's seems to be caused by this `hack': https://github.com/rust-lang/rust/blob/master/src/libsyntax/ast.rs#L1503-L1521.

Weirdly enough, the proper span is shown for diagnostics: [play.rust-lang.org](https://play.rust-lang.org/?code=trait%20Foo%20{%0A%20%20%20%20fn%20test%28self%3A%20%26Self%29%3B%0A}%0A%0Astruct%20Bar%3B%0A%0Aimpl%20Foo%20for%20Bar%20{%0A%20%20%20%20fn%20test%28self%3A%20Baz%29%20{%0A%20%20%20%20}%0A}%0A%0Afn%20main%28%29%20{%0A}&version=nightly)

Any pointers, @eddyb?

**Comment by eddyb** [comment]
Since `Self` works in `impl`s now, it's probably time to retire that hack and always provide the correct type.
`SelfExplicit` appears to hold the type (with its correct span), instead of the `self` argument itself, in this case.

**Comment by estebank** [comment]
This has been fixed. Can this ticket be closed?
