### ISSUE TITLE
Span output should be shortened to three lines (w/ ellipsis) unless --verbose

### ISSUE THREAD

**Issue by llogiq** [rust-lang/rust#27560]
The compiler reports spanned warnings and errors with the full span of the responsible code. While that makes it abundandly clear where the error arose, it also makes the output very verbose by default.

Since we have a `--verbose` command line flag, I propose that the compiler shortens all spans that are more than three lines of code with ellipsis unless the verbose output is requested. This keeps the compiler messages compact.

**Comment by steveklabnik** [comment]
We've undergone a lot of changes and re-thinks to errors since this happend, and nobody else has chimed in here. I think we can give this one a close. @llogiq I'd suggest a thread on internals if you still think this is a good idea.

**Comment by llogiq** [comment]
Fine with me.
