### ISSUE TITLE
Tracking issue for the `use_group_as` RFC

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#27578]
Tracking issue for rust-lang/rfcs#1219.

Intention is to permit syntax like:

```rust
use std::io::{
    Error as IoError,
    Read,
    Write
}
```

the semantics of which are fairly self-explanatory.

**Comment by Manishearth** [comment]
https://github.com/rust-lang/rust/pull/27451

**Comment by apasel422** [comment]
Should this be closed now?
