### ISSUE TITLE
Tracking issue for `read_exact` (RFC #980)

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#27585]
https://github.com/rust-lang/rfcs/pull/980

**Comment by cesarb** [comment]
I posted the proposed implementation I wrote a few weeks ago as https://github.com/rust-lang/rust/pull/27588

**Comment by mkpankov** [comment]
Any plans on stabilizing this? I'd like to use `read_exact()` on stable.

**Comment by sfackler** [comment]
We'll be identifying features to stabilize in the next couple of weeks, and I'd be on board with this being one of them. I'll nominate it now so we don't forget.

**Comment by alexcrichton** [comment]
:bell: This issue is now entering its cycle-long **final comment period** for stabilization :bell:

**Comment by jonas-schievink** [comment]
One thing that caught my eye: This can return `ErrorKind::UnexpectedEOF`. Shouldn't the variant be named `UnexpectedEof`?

**Comment by alexcrichton** [comment]
Good point! I do believe it should be called `UnexpectedEof` as well

**Comment by cesarb** [comment]
> This can return `ErrorKind::UnexpectedEOF`. Shouldn't the variant be named `UnexpectedEof`?

Well, `UnexpectedEOF` is short for `UnexpectedEndOfFile`, so it also makes sense to have the `EOF` in all-uppercase. That said, the reason I called it `UnexpectedEOF` was solely "the `byteorder` crate called it `UnexpectedEOF`". Other than what I said in the "Naming" section of the RFC, I don't have any opinion on this matter; either `UnexpectedEOF` or `UnexpectedEof` would work equally well IMO.

**Comment by alexcrichton** [comment]
Ah yeah our [naming conventions](http://doc.rust-lang.org/style/style/naming/README.html), however, say:

>  In CamelCase, acronyms count as one word: use Uuid rather than UUID. In snake_case, acronyms are lower-cased: is_xid_start.

So along those lines it should be `Eof` rather than `EOF`

**Comment by alexcrichton** [comment]
The libs team discussed this during triage today and the conclusion was to **stabilize** with the renaming of `UnexpectedEOF` to `UnexpectedEof`
