### ISSUE TITLE
Redundant mut checking does not work for lazily initialized variables

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#27581]
The following piece of code contains a redundant `mut`, but triggers no warning:

```{rust}
fn main() {
    let mut a;
    a = 13;
    println!("{}", a);
}
```

**Comment by mitaa** [comment]
Duplicate of #15278

**Comment by RalfJung** [comment]
Dang, I did search for duplicates, but only with "redundant", not with "unused". Oh well. Thanks for the pointer!
