### ISSUE TITLE
The Rust Reference - no mention of #[cfg(target_env)].

### ISSUE THREAD

**Issue by Eljay** [rust-lang/rust#27587]
Title says it all.

cc @steveklabnik

**Comment by alexcrichton** [comment]
This was added recently for MUSL/MSVC, and for @steveklabnik's sake the docs would probably look something like:

* `target_env` - a cfg option provided by the compiler by default describing the runtime environment of the target platform. Some examples of this are "musl" for builds targeting the MUSL libc implementation, "msvc" for Windows builds targeting MSVC, and "gnu" frequently the rest of the time. This option may also be blank on some platforms.
