### ISSUE TITLE
Error message for mutating field of immutable struct could be clearer

### ISSUE THREAD

**Issue by sleeparrow** [rust-lang/rust#27593]
``` rust
struct Foo {
    pub v: Vec<String>
}

fn main() {
    let f = Foo { v: Vec::new() };
    f.v.push("cat".to_string());
}
```

The above code gives this compile error:

``` rust
<anon>:8:5: 8:8 error: cannot borrow immutable field `f.v` as mutable
<anon>:8     f.v.push("cat".to_string());
             ^~~
```

From my perspective, this implies that the field somehow needs to be marked as mutable, when in fact the user error is that the struct is immutable.

I believe the error message could be improved by saying something like `cannot borrow field `v` of immutable struct `f` as mutable`.
#18150 is "related".

**Comment by steveklabnik** [comment]
Triage: no change. I agree that "immutable field" is bad here.

**Comment by Mark-Simulacrum** [comment]
Probably needs an extension of https://github.com/rust-lang/rust/pull/39139 to immutable bindings instead of just references. Unfamiliar with the code, but possibly easy?
