### ISSUE TITLE
Wrong "Private type in exported type signature" error

### ISSUE THREAD

**Issue by netvl** [rust-lang/rust#27608]
Consider this code:
```rust
mod a {
    pub mod x {
        pub fn return_x() -> ::X { ::X }
    }
}

struct X;

fn main() {
    let _value = a::x::return_x();
}
```
It fails to compile with the following error:
```
test.rs:3:30: 3:33 error: private type in exported type signature
test.rs:3         pub fn return_x() -> ::X { ::X }
                                       ^~~
```

However, while `fn return_x()` is `pub` and `mod x` is also `pub`, this function never gets exported from the crate because `mod a` is private. Therefore, `X`, being private, is also not available outside the crate. I think that such code should be allowed.

**Comment by crumblingstatue** [comment]
I have run into this as well.
```Rust
mod foo {
    // Private implementation detail struct
    struct Strut;
    fn doit() {
        self::bar::fun();
    }
    mod bar {
        // bar::fun() is a private implementation detail of mod foo
        pub fn fun() -> super::Strut {
            unimplemented!()
        }
    }
}

fn main() {
    // foo::bar::fun(); // inaccessible outside of `foo`
}
```

```
<anon>:9:25: 9:37 error: private type in exported type signature
<anon>:9         pub fn fun() -> super::Strut {
                                 ^~~~~~~~~~~~
```

**Comment by alexcrichton** [comment]
This has been [filed before](https://github.com/rust-lang/rust/issues/25260#issuecomment-100583361) and the gist is that the definition of a "public signature" is that the type is marked `pub`, so it's considered a public type subject to the privacy rules. You can find more details in the [associated RFC](https://github.com/rust-lang/rfcs/blob/master/text/0136-no-privates-in-public.md)
