### ISSUE TITLE
When are we getting the "more general mechanism" for struct inheritance

### ISSUE THREAD

**Issue by boghison** [rust-lang/rust#27606]
Aka virtual structs, [this](https://github.com/rust-lang/rfcs/blob/master/text/0341-remove-virtual-structs.md), although relatively old, said that there might be a general mechanism in the future. When is the future and what is the general mechanism?

**Comment by alexcrichton** [comment]
You can watch https://github.com/rust-lang/rfcs/issues/349 for updates on this issue, so closing in favor of that.

**Comment by boghison** [comment]
@alexcrichton Yes, I looked at that, but there hasn't been anything new in a long time. Is there any way to do anything about this?
