### ISSUE TITLE
extern crate foo with use self::foo doesn't work inside a function

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#27626]
EDIT (@steveklabnik) see https://github.com/rust-lang/rust/issues/27626#issuecomment-263955318

This code fails and rustc doesn't tell you why:

``` rust
fn main() {
    extern crate rand;
    use self::rand::Rng;
}
```

([playpen](http://is.gd/xYyadr))

I think it should at least warn, assuming there is some reason why it can't do what it looks like it does.

**Comment by tomjakubowski** [comment]
It's not true that it does *nothing* at all ([playpen](https://gist.github.com/a6e76c188620817723dd))

```rust
#![feature(rand)]
    
fn main() {
    extern crate rand;
    let rng = rand::chacha::ChaChaRng::new_unseeded();
}
```

**Comment by durka** [comment]
Huh. Fascinating. And you can use trait methods that way without importing the trait, as long as you use UFCS, which I thought was supposed to be impossible. So, I count this as another confusion caused by use paths being different from all other paths.

**Comment by durka** [comment]
Well, maybe I'll leave the issue open, in case there's any way to fix the diagnostic.

**Comment by steveklabnik** [comment]
Given that nobody has commented in over a year, I'm going to give this one a close; a better diagnostic here would be nice, but since nobody else has run into it, and this is a very niche case, I don't think we need to track it. If you feel super strongly, we can re-open I guess, but I doubt this is going to be fixed.

**Comment by durka** [comment]
Would you object if I opened a new bug at least about the ridiculous
suggestion "did you mean `self::self::rand`"? Or maybe there's already an
issue about that.

**Comment by steveklabnik** [comment]
I am not sure if there is; let's re-open this one for that then, I guess.

**Comment by durka** [comment]
I suppose an easy fix is just to omit the suggestion when the path already
begins with `self::`.

**Comment by steveklabnik** [comment]
Triage: this error message has gotten a bit weirder:

```text
error[E0432]: unresolved import `self::rand`
 --> src\main.rs:3:15
  |
3 |     use self::rand::Rng;
  |               ^^^^ maybe a missing `extern crate rand;`?

warning: unused import: `self::rand::Rng`
 --> src\main.rs:3:9
  |
3 |     use self::rand::Rng;
  |         ^^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default
```

It seems like the import both works and doesn't work, simultaneously?

**Comment by Mark-Simulacrum** [comment]
I'm going to go ahead and close this; the error today in a project that just has rand in Cargo.toml seems mostly acceptable for this niche case, if the extern crate is moved to root scope then things just work, as expected.
