### ISSUE TITLE
btree: Reliance on structure layout

### ISSUE THREAD

**Issue by tbu-** [rust-lang/rust#27620]
The function `collections::btree::node::Node::as_slices_internal_mut` relies on structure layout of two relatively unrelated structures to be the same, which is considered a bad thing™:

    #[inline]
    pub fn as_slices_internal_mut<'b>(&'b mut self) -> MutNodeSlice<'b, K, V> {
        unsafe { mem::transmute(self.as_slices_internal()) }
    }

**Comment by apasel422** [comment]
I'm working on this.
