### ISSUE TITLE
Add "How to build documentation" section.

### ISSUE THREAD

**Issue by Aaronepower** [rust-lang/rust#27632]
It'd be helpful for people who want make documentation pull requests that aren't just typo's to be able to build the documentation, and preview it themselves. Adding a "How To" about how documentation for the  main repo should be built, would be helpful.

**Comment by TimNN** [comment]
Building the documentation should be as simple as `make docs`, which however requires a full rust build which can take some time. Once a full build has been completed `make docs NO_REBUILD=1` should allow you to build the documentation without rebuilding the whole compiler. I don't think there currently is a way to build the docs without building the compiler.

**Comment by steveklabnik** [comment]
>  I don't think there currently is a way to build the docs without building the compiler.

You can run `rustdoc` on any crate, so I often `rustdoc --test src/libcore/lib.rs` or whatever I'm working on. It works on markdown files too.

**Comment by tomjakubowski** [comment]
> You can run rustdoc on any crate, so I often rustdoc --test src/libcore/lib.rs or whatever I'm working on. It works on markdown files too.

It's worth noting that you need a (very) recent version of rustdoc to create docs from the source in master HEAD. It's often the case that even a nightly rustdoc is not new enough (although maybe it is, if you pass `--cfg stage0` or something...).

**Comment by steveklabnik** [comment]
Huh, I've never ran into that as an issue.
