### ISSUE TITLE
Exporting a function as main does not work as expected

### ISSUE THREAD

**Issue by tbu-** [rust-lang/rust#27640]
mod foo {
        pub fn bar() {
        }
    }
    pub use foo::bar as main;

does not compile due to

    error: main function not found
    aborting due to previous error

The expected behaviour would be that the compiler treats the global symbol `main` which resolves to `foo::bar` as the main function.

**Comment by Aatch** [comment]
Hmm, I'm not sure how I feel about this. I guess I'm leaning towards not supporting this, as the `main` function isn't really "exported" like re-exports are. Note that we do support main functions that aren't `fn main()` at the top level via the `#[main]` attribute.

**Comment by steveklabnik** [comment]
@rust-lang/lang , would this need an RFC?

**Comment by nrc** [comment]
Yeah this should get an RFC.

Does this have a motivation that `#[main]` can't address?

**Comment by tbu-** [comment]
@nrc Consistency. Using a main method from a library.

**Comment by steveklabnik** [comment]
I also think this should go through an RFC. @tbu- , please pursue one for this.
