### ISSUE TITLE
x86 MSVC does not use SSE(2)

### ISSUE THREAD

**Issue by rkruppe** [rust-lang/rust#27646]
@cmr noticed this on IRC. [On `i686-pc-windows-gnu`][mingw32] and in fact on all other `i686-*` triples (except iOS, which is technically called `i386-*`), a SSE2-capable microarchitecture is assumed. @dotdash said that this was copied from Clang. Not doing so on MSVC might be an accident, and a rather costly one.

[mingw32]: https://github.com/rust-lang/rust/blob/master/src/librustc_back/target/i686_pc_windows_gnu.rs

**Comment by cmr** [comment]
Specifically, in the target spec, we have: https://github.com/rust-lang/rust/blob/master/src/librustc_back/target/i686_pc_windows_msvc.rs#L15, unlike every other `i686` target which assumes `pentium4` (except for Mac, which assumes `yonah`, which is newer, so that's fine).

**Comment by cmr** [comment]
cc @alexcrichton, who wrote that code. Is this an intentional quirk of the MSVC toolchain?

**Comment by alexcrichton** [comment]
Oh dear no this was not intentional at all, I just assumed everything was `i686`! Feel free to send a PR to update!
