### ISSUE TITLE
string interpolation

### ISSUE THREAD

**Issue by antonkulaga** [rust-lang/rust#27661]
things like:
```rust
	let name = "Anton".to_string();
	print!("hello {}",name);
```
are very akward and verbose. What about scala-like string interpolation?
```rust
	let name = "Anton".to_string();
	print!(s"hello $name"); // s is put before string to tell that it is a string interpolation
```
or maybe even without "$" sign:
```rust
	let name = "Anton".to_string();
	print!(s"hello {name}"); // s is put before string to tell that it is a string interpolation
```

**Comment by alexcrichton** [comment]
Feature requests such as this start out on the rust-lang/rfcs repo instead of this one, so could you open an issue there instead if you'd like to pursue this?

**Comment by DenisKolodin** [comment]
Some implementations needs high cost. Scala don't avoid it. But this way works:
```
fn main() {
	println!("x = {}, y = {y}", 10, y = 30);
}
```

**Comment by antonkulaga** [comment]
@alexcrichton 

thank you, I will move it to rfcs

>Some implementations need high cost. Scala don't avoid it. But this way works:

Scala does it compile time, so runtime performance is the same as just string concatenation.

```rust
println!("x = {}, y = {y}", 10, y = 30);
```
it is actually what I call "akward and verbose way". In Scala you can insert variables in a s"some text ${variableOrCodeThatReturns} another text ${variableOrCodeThatReturns2}" in an easy way and everywhere (not only inside print statement like here).
