### ISSUE TITLE
Write::write_fmt causes page fault on a bare metal

### ISSUE THREAD

**Issue by ababo** [rust-lang/rust#27673]
My experimental code crashes when running on bare x86_64-metal (page fault when IDT is not yet set), but works perfectly on aarch64.

By careful tracing I figured out that the cause of this page fault consists of corrupted address (much higher than 0x200_000, while only the first 2M page is yet mapped as 1:1) of function "f" passed as an argument to core::fmt::ArgumentV1::new() function:

```rust
#[doc(hidden)]
#[unstable(feature = "fmt_internals", reason = "internal to format_args!")]
pub fn new<'b, T>(x: &'b T,
                  f: fn(&T, &mut Formatter) -> Result) -> ArgumentV1<'b> {
    unsafe {
        ArgumentV1 {
            formatter: mem::transmute(f),
            value: mem::transmute(x)
        }
    }
} 
```
AFAIK this value is hard-coded by rustc compiler being result of compile-time processing of format_args! variadic arguments.

**Comment by alexcrichton** [comment]
Do you have some code that exhibits this failure mode? Without a reproduction it's tough to see what's going on here.

**Comment by ababo** [comment]
Take code from [here](https://github.com/ababo/arwen-tmp).

**Comment by ababo** [comment]
Alternatively you can take more recent [project](https://cloud.githubusercontent.com/assets/503292/9210047/33997918-407a-11e5-86c8-5680bc910770.png) (the same thing actually, but with another configurer). Just change the extension from png to zip.

**Comment by arielb1** [comment]
@ababo 

Are you sure you have global variables set up properly in your image?

**Comment by ababo** [comment]
Guys, did you try to reproduce the problem?

**Comment by ababo** [comment]
I just figured out that using -C relocation-model=static eliminates the problem.

**Comment by steveklabnik** [comment]
So, is this not a bug then?

**Comment by ababo** [comment]
This is a bug, because it does not work with the default relocation model.

**Comment by arielb1** [comment]
@ababo 

Are you sure the your loader handles the relocations created by the default relocation-model correctly?

**Comment by ababo** [comment]
I use GRUB2, so I believe it should do it properly.

**Comment by cmr** [comment]
@ababo I'm convinced this is an issue with the loader, I can't find any code in GRUB2 that does relocations at all.

The correct fix is to specify the static relocation-model in your target specification. The default of pic is as a secure default for already-existing operating systems, but it's expected that bare metal targets use `static` if they don't have a robust loader.

**Comment by ababo** [comment]
What is a problem for loader to handle PIC-code? Why does it need some special treatment?

**Comment by cmr** [comment]
@ababo it's more complex - it requires reading the relocation section and rewriting portions of segments with correct addresses.

**Comment by cmr** [comment]
(whereas with the "static" relocation model, all addresses are already absolute, you just need to drop the segment in memory at the correct address)

**Comment by ababo** [comment]
Yes, I got it, thanks.
