### ISSUE TITLE
`--extern` broken for indirect dependencies

### ISSUE THREAD

**Issue by JustAPerson** [rust-lang/rust#27686]
alpha.rs
```rust
pub struct Test; 
```

beta.rs:
```rust
extern crate alpha;

pub use alpha::Test;
```

gamma.rs
```rust
extern crate beta;

pub use beta::Test;
```

Now, run the following
```
mkdir -p bin
rustc alpha.rs -o bin/libalpha.rlib  --crate-type lib
rustc beta.rs  -o bin/libbeta.rlib   --extern alpha=bin/libalpha.rlib --crate-type lib
rustc gamma.rs -o bin/libgamma.rlib  --extern alpha=bin/libalpha.rlib --extern beta=bin/libbeta.rlib --crate-type lib
```

You get the following error:
```
gamma.rs:1:1: 1:19 error: can't find crate for `alpha` which `beta` depends on
gamma.rs:1 extern crate beta;
           ^~~~~~~~~~~~~~~~~~
error: aborting due to previous error
```

A simple fix to this is to add `extern crate alpha;` at the beginning of gamma.rs, but that should not be unnecessary.
Reproduces on nightly.

**Comment by alexcrichton** [comment]
This is currently working as intended, the `--extern` flags only work for specifying the immediate set of dependencies (those listed in `extern crate`), and transitive dependencies must be found through `-L` paths. You can use `-L dependency=...` to make sure that only transitive dependencies are found in those paths.

**Comment by JustAPerson** [comment]
@alexcrichton 
If that is the intended behavior, then please reopen this issue and mark it as a documentation problem.
I cannot find where this distinction is explained.

```
    -L [KIND=]PATH      Add a directory to the library search path
    -l [KIND=]NAME      Link the generated crate(s) to the specified native
                        library NAME. The optional KIND can be one of, static,
                        dylib, or framework. If omitted, dylib is assumed.

    --extern NAME=PATH  Specify where an external rust library is located
```

This section of `rustc -hv` would imply that:

* `-l`/`-L` are for use with static libraries only, not even mentioning the `dependency` KIND. `-Ldir/` by itself will not actually search for crates in that directory.
* `--extern` should be used for telling rust where to locate any crate and is an intuitive solution to errors like `can't find crate for bar which foo depends on`

For reference, how do you thus indicate to rust where to locate a crate whose filename does not follow the `libcrate.rlib` pattern?

**Comment by alexcrichton** [comment]
Yeah seems reasonable to leave open as a docs issue. Not sure exhaustive documentation should go into the `-h` message but the man page could certainly be beefed up.

> For reference, how do you thus indicate to rust where to locate a crate whose filename does not follow the libcrate.rlib pattern? 

That... can't actually be done I don't think. The only way the compiler looks for transitive dependencies is via `lib<foo>*.rlib`  where `<foo>` is the name of the crate.
