### ISSUE TITLE
need more coercions for composed iterator types that have Fns

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#27692]
Rust's problems with returning the complicated types that result from iterator composition are well-known.
- See e.g. https://github.com/rust-lang/rfcs/pull/105 
- (with possible follow-on tracking at https://github.com/rust-lang/rfcs/issues/518 , though most of the conversation seems to be continuing on at https://github.com/rust-lang/rfcs/pull/105 )

The usual response is that for the short-term one can often work-around the issues with iterator composition via newtypes or type aliases.

However, while this appears to work for simple examples, it seems like it breaks when nesting an iterator that has a `Fn` type parameter more than one level deep. (This may be related to the introduction of unique types for each function item, I am not sure.)

Example ([playpen link](http://is.gd/99GLaq)):

``` rust
// Example inspired from comment here:
// https://github.com/rust-lang/rfcs/pull/105#issuecomment-67441120

use std::iter::{Filter, Map};
use std::slice::Iter;
type even_fn = fn(&&i32) -> bool;
type add1_fn = fn(&i32) -> i32;
type F<'a> = Filter<Iter<'a, i32>, even_fn>;
type M<'a> = Map<Iter<'a, i32>, add1_fn>;
type MF<'a> = Map<Filter<Iter<'a, i32>, even_fn>, add1_fn>;

fn even(&&i: &&i32) -> bool { i % 2 == 0 }
fn add1(&i: &i32) -> i32 { i + 1 }

// these work
fn evens<'a>(ns: &'a [i32]) -> F<'a> { ns.iter().filter(even) }
fn incrs<'a>(ns: &'a [i32]) -> M<'a> { ns.iter().map(add1) }

// this does not
#[cfg(not(iter_composition))]
fn composed<'a>(ns: &'a [i32]) -> MF<'a> { ns.iter().filter(even).map(add1) }

fn main() {}
```

yields compiler error:

```
<anon>:21:44: 21:76 error: mismatched types:
 expected `core::iter::Map<core::iter::Filter<core::slice::Iter<'a, i32>, fn(&&i32) -> bool>, fn(&i32) -> i32>`,
    found `core::iter::Map<core::iter::Filter<core::slice::Iter<'_, i32>, fn(&&i32) -> bool {even}>, fn(&i32) -> i32 {add1}>`
(expected fn pointer,
    found fn item) [E0308]
<anon>:21 fn composed<'a>(ns: &'a [i32]) -> MF<'a> { ns.iter().filter(even).map(add1) }
                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<anon>:21:44: 21:76 help: see the detailed explanation for E0308
error: aborting due to previous error
playpen: application terminated with error code 101
```

**Comment by pnkfelix** [comment]
(my internet connectivity is limited and so I cannot readily download the relevant versions of Rust, but it seems like this was broken in this manner prior to the 1.0 release, and thus if this did work in the past, it probably has not ever worked in the stable channels.  Which is good since it means its not as high priority to fix it.  Still, its annoying.)

**Comment by pnkfelix** [comment]
(ah maybe this is actually an issue with the error messages not printing the implicit `for <'a>`  bindings?)

**Comment by pnkfelix** [comment]
This version, where I have added a manual cast `even as even_fn`, works:

```rust
fn composed<'a>(ns: &'a [i32]) -> MF<'a> { ns.iter().filter(even as even_fn).map(add1) }
```

so perhaps our implicit coercion rules just need to be extended to cover something here?

**Comment by bluss** [comment]
I was reminded recently that while this is the solution which requires the least boilerplate, using fn pointers can lead to some overhead if the function call can not be inlined, and it often can't.

**Comment by pnkfelix** [comment]
Maybe the another orthogonal (and in some ways better) answer here would be to extend our type expression syntax to allow me to actually write the type `fn even` (which currently prints as `fn(&&i32) -> bool {even}` in a explicit type instantiation like `Map<Filter<Iter<'a, i32>, fn even>, fn add1>`

**Comment by steveklabnik** [comment]
Triage: @pnkfelix do you feel this is still useful? `impl trait` should help with these kinds of cases, yeah?

**Comment by steveklabnik** [comment]
Triage: I'm going to close this bug. Felix, if you still feel this deserves to be open, please do so with clarifications :)
