### ISSUE TITLE
Adding Deref impl affects lifetime bounds of other methods

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#27697]
From https://users.rust-lang.org/t/does-implementing-deref-affect-the-lifetime-bounds-of-all-other-methods/

---

Code: ~~http://is.gd/AkyE699~~ http://is.gd/AkyE69

If the Deref is removed, the code compiles. Presumably, the inclusion of the Deref implementation on the trait object causes the lifetime bounds to change on the do_something method.

**Comment by Stebalien** [comment]
Code: http://is.gd/AkyE69

**Comment by bluss** [comment]
For debugging, notice that `impl Deref for MyTrait` is equivalent to `impl Deref for MyTrait + 'static`.

**Comment by steveklabnik** [comment]
Triage: still reproduces today.

**Comment by frewsxcv** [comment]
Triage: still reproduces today.

**Comment by pnkfelix** [comment]
This no longer reproduces. Tagging as E-needstest
