### ISSUE TITLE
Tracking issue for fs::DirBuilder

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#27710]
This is a tracking issue for the unstable `dir_builder` feature in the standard library. The current purpose of this is to provide access to platform-specific options such as modes on Unix or security attributes on Windows. The current `create_dir` and `create_dir_all` APIs are built on top of this API right now.

There aren't too many open questions other than bikeshedding things like naming and such. [C++ may have some inspiration](http://en.cppreference.com/w/cpp/experimental/fs) as well for an API like this.

**Comment by aturon** [comment]
Nominating for stabilization in 1.6.

**Comment by retep998** [comment]
I'm okay with the current design with those three functions. Hopefully we can get some platform specific extension traits soon though.

**Comment by alexcrichton** [comment]
:bell: This issue is now entering its cycle-long **final comment period** for stabilization :bell:

**Comment by alexcrichton** [comment]
The libs team discussed this during triage today and the decision was to **stabilize**
