### ISSUE TITLE
Tracking issue for `fs_mode` stabilization

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#27712]
The `fs_mode` feature refers to platform-specific constants for file access modes exported in `std::os`. While these constants are OK as-is, we don't have a clear overall vision for which constants should be included in `std::os` or how they should be organized. Before we stabilize, we should establish such a vision.

cc @alexcrichton

**Comment by alexcrichton** [comment]
Nominating for deprecation and removal

**Comment by alexcrichton** [comment]
:bell: This issue is now entering its **final comment period** for deprecation :bell:

**Comment by drbo** [comment]
What will be the replacement?

**Comment by alexcrichton** [comment]
The libc crate should have all of these constants, but if it doesn't just let me know!

**Comment by alexcrichton** [comment]
The libs team discussed this in triage recently and decided to **deprecate**
