### ISSUE TITLE
Tracking issue for `path_components_peek` stabilization

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#27727]
The `path::Components::peek` method allows you to peek at the next component in the iterator without actually consuming it. There's no strong reason for it to remain unstable, except that the conventions around such methods are a bit unclear.

**Comment by nagisa** [comment]
Any reason a more general Peekable<Components> cannot be used instead?

**Comment by aturon** [comment]
@nagisa Not really, no.

Nominating for deprecation in 1.6.

**Comment by alexcrichton** [comment]
:bell: This issue is now entering its cycle-long **final comment period** for deprecation :bell:

**Comment by alexcrichton** [comment]
The libs team discussed this during triage today and the decision was to **deprecate**
