### ISSUE TITLE
Tracking issue for `path_prefix` stabilization

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#27722]
The `Path::prefix` method allows you to extract a `Prefix` from a path, if any -- which is relevant only on Windows, where the prefix gives e.g. volume information.

It's already possible to get this information through the `components` iterator, so it's not clear whether this additional convenience is worth exposing.

cc @retep998

**Comment by alexcrichton** [comment]
Nominating for deprecation/removal

**Comment by alexcrichton** [comment]
:bell: This issue is now entering its **final comment period** for deprecation :bell:

**Comment by alexcrichton** [comment]
The libs team discussed this in triage recently and the decision was to **deprecate**
