### ISSUE TITLE
Tracking issue for OpenOptionsExt on Windows

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#27720]
This is a tracking issue for the unstable `open_options_ext` feature in the standard library. Currently Unix has a stable extension trait for setting the mode of a file but Windows has not stabilized any of its functionality. The current set of methods on the Windows extension trait just provide the ability to override any of the arguments to `CreateFile`.

The open questions here are:

* Is the naming right?
* Are the types right? (e.g. should they be updated to use `std::os::windows::raw`?)
* Do more options want to be specified?
* Does Unix want any more methods on `OpenOptionsExt`?

APIs:

* `OpenOptionsExt::access_mode`
* `OpenOptionsExt::share_mode`
* `OpenOptionsExt::attributes`
* `OpenOptionsExt::security_qos_flags`

**Comment by retep998** [comment]
For [`CreateFile2`](https://msdn.microsoft.com/en-us/library/windows/desktop/hh449422%28v=vs.85%29.aspx) (which Rust would have to use if we wanted to support non-desktop apps since [`CreateFile`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363858%28v=vs.85%29.aspx) is desktop only) it takes flags and attributes as [two separate parameters](https://msdn.microsoft.com/en-us/library/windows/desktop/hh449426%28v=vs.85%29.aspx), so it may be a good idea to separate those and then when we invoke `CreateFile` just or them back together.

**Comment by retep998** [comment]
`u32` is very much the right type to use, although whether it should be behind some sort of alias is an entirely different debate and would be a backwards compatible change to make so it isn't an issue regardless.

There are more options that we will want to eventually support.

**Comment by alexcrichton** [comment]
Interesting! Perhaps we should call `CreateFile2` unless it's not available? (e.g. Windows 7 and below).

Also yeah `u32` is fine, I figure we may want to take a `DWORD` alias though (although also perhaps not)

**Comment by kamalmarhubi** [comment]
> Does Unix want any more methods on `OpenOptionsExt`?

I'd like it if Unix exposed the `flags` parameter to `open`.

**Comment by kamalmarhubi** [comment]
Additionally, it would be nice to have a way to toggle particular flags as opposed to just overriding all of them.

**Comment by alexcrichton** [comment]
🔔 This issue is now entering its cycle-long **final comment period** for stabilization 🔔 

The libs team would like to perform one final pass to ensure that all of these arguments have very clearly documented interactions with the underlying arguments and other builder options, but otherwise these seem good for stabilizing!

**Comment by alexcrichton** [comment]
The libs team discussed this during triage yesterday and the decision was to **stabilized**. I looked over these APIs again and they do indeed all have clear mappings to the underlying values.

**Comment by pravic** [comment]
@retep998 

> which Rust would have to use if we wanted to support non-desktop apps

Guess it requires a bit more than just wanting to support the windows store apps.

**Comment by retep998** [comment]
@pravic There's a ton of stuff that Rust would have to do before libstd could be used for Windows store apps. Still nice to at least leave the door open for that in APIs like this.
