### ISSUE TITLE
Tracking issue for formatting with a radix

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#27728]
This is a tracking issue for the unstable `fmt_radix` feature in the standard library. These functions provide the ability to format a number in an arbitrary radix. Note that base 2, 8, and 10, and 16 are already supported via various formatting flags.

Needs a decision about whether this functionality should even be in the standard library, and it will perhaps want a different interface as well.

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/issues/18301 was an open issue related to an older version of this code.

**Comment by alexcrichton** [comment]
Nominating for removal

**Comment by alexcrichton** [comment]
:bell: This issue is now entering its **final comment period** for deprecation :bell:

**Comment by alexcrichton** [comment]
The libs team discussed this in triage recently and the decision was to **deprecate**

**Comment by SimonSapin** [comment]
So libstd does not provide any way to do the reverse of e.g. `std::u32::from_str_radix` with bases other than 2, 8, 10, or 16?

(Maybe that’s ok, the asymmetry is just unusual.)

**Comment by alexcrichton** [comment]
@SimonSapin for now yeah that's the state of affairs

**Comment by EvanCarroll** [comment]
@alexcrichton is there a reason why this feature was deprecated. It sounds extremely useful. Why isn't this in core for bases <= 26. (which is just ascii).

**Comment by gilescope** [comment]
It is useful. I needed it to test the optimised number parsing algorithm, so the _tests_ of std lib now include this functionality even if we do not want to expose it. Personally it seems asymmetric to have one function and not the inverse. (If we already have this code somewhere else in the std lib test code then let me know and I will call that and remove the implementation that I introduced)

https://github.com/rust-lang/rust/pull/95399

**Comment by gilescope** [comment]
Ah, I see the std lib has does ship this code, it's just not exposed because... https://github.com/rust-lang/rust/blob/d9b3ff7d34335c5bc0b2afed640b65d64a85fe03/library/core/src/fmt/num.rs#L67
