### ISSUE TITLE
Tracking issue for `IntoCow` stabilization

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#27735]
The `IntoCow` trait is a custom conversion trait for working with `Cow`; the custom nature is needed to deal with trait coherence issues.

Ultimately, the hope was that this trait could support ergonomic "ownership polymorphism" for things like the `entry` API. That's not the case today due to coherence limitations, but may become possible with [impl specialization](https://github.com/rust-lang/rfcs/pull/1210) or other changes to the trait system.

The API needs a full re-evaluation before stabilization.

**Comment by sfackler** [comment]
Seems like we can potentially deprecate this due to a lack of interest?

**Comment by Gankro** [comment]
This is being used in [HashMap2](https://github.com/contain-rs/hashmap2) to provide an ergonomic CoW entry, but I think there's some silly issues that result.

@apasel422 do you recall the details?

**Comment by SimonSapin** [comment]
Does `Into<Cow<_>>` not work for `HashMap2`?

**Comment by apasel422** [comment]
CC contain-rs/hashmap2#2.

**Comment by alexcrichton** [comment]
:bell: This issue is now entering its **final comment period** for deprecation :bell:

**Comment by alexcrichton** [comment]
The libs team discussed this in triage recently and the decision was to **deprecate**
