### ISSUE TITLE
Tracking issue for reentrant mutexes

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#27738]
This is a tracking issue for the unstable `reentrant_mutex` feature in the standard library. Currently this flavor of mutex is not exposed at all in the standard library (it's private in the `sys`module), but it's an often-useful form of a mutex. 

We should decide whether or not the standard library will expose this flavor of mutex and then ensure that the API is audited for conventions, naming, and performance.

cc @nagisa

**Comment by nagisa** [comment]
I’m still a bit uncomfortable by the fact that we do not allow inner mutability in this particular Mutex. You’d usually won’t want to Mutex-guard immutable data because it is, well, immutable and in most cases is already MT-safe, and mutable ReentrantMutex ready to share and use looks a little bit odd/redundant: `Arc<ReentrantMutex<RefCell<T>>>`.

**Comment by arielb1** [comment]
@nagisa 

The idea of `ReentrantMutex` is to allow accessing a big multi-`Cell` (and/or `RefCell`) context-structure from multiple threads. This would be kind-of broken by making it return `&mut`

**Comment by Diggsey** [comment]
@nagisa `RwLock` already does pretty much what you're suggesting anyway? ReentrantMutex fills a gap in the standard library: taking something !Sync, and making it Sync, with as little overhead as possible.

**Comment by alexcrichton** [comment]
This type isn't actually exposed from the standard library, I believe I just mistakenly read the `unstable` tag, so closing.

**Comment by nox** [comment]
Can we reopen this? We are going to need this in Servo for exactly the reason @Diggsey mentioned.

Cc @asajeffrey.

**Comment by asajeffrey** [comment]
I ended up reimplementing the interface on top of regular mutexes https://github.com/servo/servo/blob/master/components/util/remutex.rs. The main use case is data structures that are reentrant but not thread-safe, and use interior mutability. In our case that was IPC channels, but you can do similar examples with cells.

**Comment by alexcrichton** [comment]
Note that this was never an exported interface of the standard library, so we'd probably require an RFC to add this feature to the standard library

**Comment by asajeffrey** [comment]
Given that reentrant mutexes can be implemented on top of stdlib's mutexes, should they be in std or a crate? One argument for putting them in std would be if there's an efficiency gain from using native reentrant mutexes.

**Comment by nox** [comment]
Given the stdlib's reentrant mutexes AFAIK aren't implemented on top of `Mutex` and they already live in there, I would rather write an RFC and just expose them.

**Comment by ckaran** [comment]
Well, it's been about 4.5 years, can we look at this again?

**Comment by SimonSapin** [comment]
This thread can be informative for historical context but it is marked as closed, let’s discuss in https://github.com/rust-lang/rust/issues/58612.
