### ISSUE TITLE
Tracking issue for `wait_timeout_with` stabilization

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#27748]
The [`wait_timeout_with` method](http://static.rust-lang.org/doc/master/std/sync/struct.Condvar.html#method.wait_timeout_with) allows you to wait on a `CondVar` with a particular timeout, but also to cancel waiting based on a closure you pass in.

It's not clear if this API is broadly useful enough to go in `std`, or whether this is its ideal form.

cc @sfackler

**Comment by alexcrichton** [comment]
:bell: This issue is now entering its cycle **final comment period** to be deprecated in 1.8 :bell:

**Comment by alexcrichton** [comment]
The libs team discussed this during triage yesterday and the decision was to **deprecate**
