### ISSUE TITLE
Tracking issue for str::match_indices

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#27743]
This is a tracking issue for the unstable `str_match_indices` feature in the standard library. This function should largely be good to go except for the note indicating that the returned iterator should probably yield different types of values to stay consistent with other methods.

cc @Kimundi

**Comment by aturon** [comment]
Nominating for 1.5 FCP discussion.

**Comment by alexcrichton** [comment]
This issue is now entering its cycle-long FCP for stabilization in 1.5

(assuming the signature change)

**Comment by alexcrichton** [comment]
The libs team discussed this during triage today and the decision was to stabilize.
