### ISSUE TITLE
Tracking issue for slice_splits

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#27742]
This is a tracking issue for the unstable `slice_splits` feature in the standard library. These functions were added in [RFC 1058](https://github.com/rust-lang/rfcs/pull/1058) and implemented in https://github.com/rust-lang/rust/pull/26966.

These probably just need to bake for awhile and get a decision on whether they should be stable or not.

cc @kballard, @nagisa

**Comment by nagisa** [comment]
Removal of deprecated `tail` and `init` is also in scope of this issue.

**Comment by bluss** [comment]
@nagisa That's in PR #27684

**Comment by alexcrichton** [comment]
Yeah in general removal of deprecated items I think will start happening right after we make a release so we probably won't make tracking issues for those kinds of items.

**Comment by alexcrichton** [comment]
Nominating for 1.5 resolution, we may also want to consider adding the same methods to strings early on in the cycle as well.

**Comment by alexcrichton** [comment]
This issue is now entering its cycle-long FCP for stabilization in 1.5

**Comment by alexcrichton** [comment]
The libs team discussed this during triage today and the decision was to stabilize.
