### ISSUE TITLE
Tracking issue for `num_bits_bytes` stabilization

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#27753]
The `BITS` and `BYTES` constants for e.g. `i32` are currently unstable, due to lack of clarity around:

- Should these be associated constants of the type instead?
- Is there a better way to get at these via e.g. `size_of`?

cc @eddyb

**Comment by eddyb** [comment]
`BYTES` would be directly redundant with any kind of `size_of` computation in constants, so I'd be against keeping it, if the latter is on the horizon.
`BITS` on the other hand, is indeed `BYTES * 8` in all the cases we currently provide it in, but it might be more ergonomic.
Do we have (even rough) usage numbers?
Technically, anyone can implement their own trait with associated constants, so a straight-forward replacement would be available where necessary, even if `std` doesn't provide it and `size_of` still doesn't work in constant.

**Comment by alexcrichton** [comment]
We've gotten this far without these being stable, let's just axe them.

**Comment by SimonSapin** [comment]
Does this include `usize::BYTES` and `isize::BYTES`? `mem::size_of` doesn’t work in const contexts.

**Comment by alexcrichton** [comment]
:bell: This issue is now entering its **final comment period** for deprecation :bell:

although ping @rust-lang/compiler, I hear claims that there were discussions of these constants at the work week, and there may be something we're interested of!

----

@SimonSapin  yeah this'd be those constants (they're unstable today anyway).

**Comment by SimonSapin** [comment]
Is there a replacement that works in `const` contexts (e.g. array sizes) and does not involve multiple definitions with `#[cfg(target_pointer_width = "64")]`?

**Comment by SimonSapin** [comment]
A single `std::ptr::BYTES` constant would work.

**Comment by alexcrichton** [comment]
There isn't a replacement that I currently know of, although if this is used widely throughout the nightly ecosystem we can leave them for now until there's a suitable replacement.

**Comment by andrewtj** [comment]
I've been using `std::usize::BYTES` in `const` contexts. Doing a `#[cfg(target_pointer_width = …)]` dance instead wouldn't be much of a hassle but a more succinct alternative would be nice.

**Comment by tari** [comment]
Could `size_of` be made `const` so it becomes usable in `const` contexts even after removal of `BYTES`? I agree that these constants are of limited utility, but a `#[cfg]` dance is not very nice to work with.

**Comment by eddyb** [comment]
@tari It can be, but it requires more work on constants (the actual computation only depends on the pointer size and target-specific alignments).

**Comment by alexcrichton** [comment]
The libs team discussed this in triage recently and the decision was to **deprecate**

**Comment by alexcrichton** [comment]
Closed by https://github.com/rust-lang/rust/pull/30943

**Comment by SimonSapin** [comment]
This was removed without any replacement :(

**Comment by SimonSapin** [comment]
To clarify, since the first message of this thread mentions `i32`, I only care about one `const` for the size of `usize`/`isize`/pointers, since that’s the only one that changes per platform.
