### ISSUE TITLE
rustdoc unstable should show feature name and issue

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#27759]
rustdoc currently shows unstable things like the following (for [`Result::expect`](http://doc.rust-lang.org/stable/std/result/enum.Result.html#method.expect)):

> Unstable: newly introduced 

It could also include the name of the feature and a link to the tracking issue, e.g.

> Unstable (`result_expect` #27277): newly introduced

**Comment by durka** [comment]
This is fixed.
