### ISSUE TITLE
Tracking issue for VecDeque::retain

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#27767]
This is a tracking issue for the unstable `vec_deque_retain` feature in the standard library. This is probably ready to just be stabilized as-is.

cc @Gankro

**Comment by Gankro** [comment]
I still maintain this is a fake method that doesn't actually exist. But yeah, seems fine.

**Comment by alexcrichton** [comment]
This feature is now entering its final comment period for stabilization.

**Comment by frankmcsherry** [comment]
random comment: given that drop is safe and pre-pooping is an understood technology, `retain` implementations generally could set their `len`s to zero and then run without doing all the `mem::swap` operations they seem to like to do.

**Comment by Gankro** [comment]
That seems fine, though something we should avoid when possible if not necessary.
