### ISSUE TITLE
Tracking issue for Box::{into_raw, from_raw}

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#27768]
This is a tracking issue for the `box_raw` unstable feature in the standard library. These methods are functionally ready to go but may need to settle on some names. Other candidates (like those that `CString` chose) are `into_ptr` and `from_ptr`. These shouldn't be stabilized until they're consistent across the board.

**Comment by Gankro** [comment]
My vote is for into_raw, solely for the purpose of indicating that it's safely round-trippable. 

It wouldn't be a tragedy to settle on into_ptr.

**Comment by alexcrichton** [comment]
This feature is now entering its final comment period for stabilization.
