### ISSUE TITLE
Tracking issue for viewing Result/Option as slices

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#27776]
This is a tracking issue for the unstable `as_slice` feature in the standard library. These functions enable viewing a `Result<T, U>` and `Option<T>` as some form of `[T]` (both shared and mutably). In each case an array of at most one item will be returned.

It's somewhat unclear ([like with `ref_slice` and `ref_mut_slice`](https://github.com/rust-lang/rust/issues/27774)) how useful these are and whether they should exist to me.

**Comment by nagisa** [comment]
These can be trivially implemented in terms of `ref_slice` and `ref_mut_slice`.

**Comment by SimonSapin** [comment]
Which in turn can be trivially implemented in terms of `slice::from_raw_parts{,_mut}`, although with `unsafe` code.

**Comment by alexcrichton** [comment]
This feature is now entering its final comment period for deprecation

**Comment by devonhollowood** [comment]
This seems like it could be pretty useful in some niche scenarios, although admittedly I haven't personally run into any of those niches. It seems useful enough though that I'm not sure that this should be deprecated.

**Comment by aturon** [comment]
As usual, I think there's little harm in providing additional conversions that follow the usual conventions.
