### ISSUE TITLE
Tracking issue for iter::range_inclusive

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#27777]
This is a tracking issue for the unstable `range_inclusive` feature in the standard library. This will likely be deprecated and removed if https://github.com/rust-lang/rfcs/pull/1192 is accepted. Otherwise this will likely be deprecated and removed in favor of a builder-style interface on `Range`

**Comment by BurntSushi** [comment]
Now that rust-lang/rfcs#1192 has been accepted, can we deprecate this?

**Comment by alexcrichton** [comment]
This issue is now entering its cycle-long FCP for deprecation in 1.5

**Comment by alexcrichton** [comment]
The libs team discussed this during triage today and the decision was to deprecated.
