### ISSUE TITLE
Tracking issue for some Duration-taking functions

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#27771]
This is a tracking issue for some small Duration-taking functions in the standard library, specifically the `park_timeout` and `thread_sleep` functions. Now that `Duration` is stabilized these are likely ready to be stable as-is.

**Comment by alexcrichton** [comment]
This feature is now entering its final comment period for stabilization.

**Comment by nagisa** [comment]
What do we do with the `_ms` variants? Deprecate or leave as is?

**Comment by alexcrichton** [comment]
Yeah we'd just deprecate them all in place

**Comment by SimonSapin** [comment]
Before we deprecate something `#[stable]` whose replacement has not reached the stable channel yet, I’d like to have a way to write libraries that build without warnings both on the stable and nightly channels. Perhaps opting out of deprecation warnings for specific items?

**Comment by aturon** [comment]
@SimonSapin We've talked about tying deprecation to particular versions, so that the warnings don't start until the relevant stable release (but it still shows as deprecated in rustdoc, etc).

For the time being, we can just do this manually by waiting to deprecate.

**Comment by SimonSapin** [comment]
@aturon Yes, either of these would work.
