### ISSUE TITLE
Tracking issue for Condvar::wait_timeout

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#27772]
This is a tracking issue for the unstable `wait_timeout` feature in the standard library. An open question here is whether the tuple return value with a `bool` is appropriate or whether an `enum` of some form should be returned instead.

cc @sfackler

**Comment by sfackler** [comment]
It now returns an opaque struct with a method that identifies if a timeout occurred.

Nominating for stabilization in the next cycle.

**Comment by alexcrichton** [comment]
This issue is now entering its cycle-long FCP for stabilization in 1.5

It's likely that `wait_timeout_ms` won't actually be deprecated until `wait_timeout` hits stable.

**Comment by alexcrichton** [comment]
The libs team discussed this during triage today and the decision was to stabilize.
