### ISSUE TITLE
Tracking issue for DebugTuple::formatter

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#27782]
This is a tracking issue for the unstable feature `debug_builder_formatter` in the standard library. This method was add relatively recently, and my thoughts on it are:

* It seems odd to have this function only on `DebugTuple` and no other builders.
* It does seem reasonable to allow reading out the formatter for flags and such in various situations perhaps.

cc @sfackler

**Comment by sfackler** [comment]
This exists due to some sketchiness in Debug impls for tuples. We should hide it behind privacy rather than a feature gate.

**Comment by alexcrichton** [comment]
:bell: This issue is now entering its **final comment period** for deprecation :bell:

@sfackler has claimed the fix for this :)

**Comment by alexcrichton** [comment]
The libs team discussed this in triage recently and the decision was to **deprecate**
