### ISSUE TITLE
Tracking issue for VecDeque Extras

### ISSUE THREAD

**Issue by Gankro** [rust-lang/rust#27788]
This covers the `deque_extras` blanket feature, which should probably be sharded more in the future. It covers:
- `truncate`
- `resize`
- `as_slices`
- `as_mut_slices`
- `swap_back_remove`
- `swap_front_remove`

Some notes:
- `truncate` and `resize` are strange because they aren't directional (they just truncate off the back). Need work.
- `as_slices` and `as_mut_slices` seem good to go. A bit niche, but so is VecDeque. Maybe move the `mut` to the end. RFC'd and everything.
- `swap_back_remove` and `swap_front_remove` also seem good to go. Maybe move the directional specifier to the end. RFC'd and everything.

**Comment by eefriedman** [comment]
`shrink_to_fit` and `insert` are now also part of `deque_extras`.

**Comment by sfackler** [comment]
I think we can pretty easily stabilize `as_slices` and `as_mut_slices`. Not sure about the others.

**Comment by alexcrichton** [comment]
This issue is now entering its cycle-long FCP for stabilization in 1.5

Specifically the `as_slices` and `as_mut_slices` along `swap_*_remove` methods are being considered for stabilization. We are also considering renaming the swapping methods.

**Comment by llogiq** [comment]
@alexcrichton How should the swapping methods be named?

**Comment by alexcrichton** [comment]
@llogiq as mentioned in the issue description, the other candidate names would be `swap_remove_back` and `swap_remove_front`

**Comment by alexcrichton** [comment]
The libs team discussed this during triage today and the decision was to stabilize:

* `insert`
* `shrink_to_fit`
* `as_slices`
* `as_mut_slices`
* `swap_remove_front` (renamed from `swap_front_remove`)
* `swap_remove_back` (renamed from `swap_back_remove`)

**Comment by Gankro** [comment]
Oh, we forgot to discuss as_mut_slices vs as_slices_mut.

I think we should move muts to the back as much as possible, even if in this case we're making "mutable slices", it's still the _mut variant of as_slices.

**Comment by alexcrichton** [comment]
Hm I'm not sure I'd follow the same reasoning, in method names types like `&mut [T]` and `*mut T` are referred to as `mut_slice` and `mut_ptr`. We've always known about this with regards to the `_mut`-at-the-end convention, so I would feel that these methods are correctly named.

**Comment by Gankro** [comment]
Yeah I've been a bit ambivalent about that naming scheme, but I guess it's
a bit too late for that!

**Comment by sfackler** [comment]
The only remaining unstable methods on `VecDeque` are `truncate` and `resize`. Nominating to stabilize.

@rfcbot fcp merge
