### ISSUE TITLE
Tracking issue for creating BTree{Map,Set} with a B

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#27795]
This is a tracking issue for the unstable `btree_b` feature in the standard library.

cc @Gankro, perhaps you can fill in the details here?

**Comment by Gankro** [comment]
It's a cool idea but it's never carried its weight in practice. I had a PR
that removed it but it got closed for other reasons.

**Comment by bluss** [comment]
Don't forget runtime `::with_b` kind of conflicts with type-level "b" configuration

**Comment by alexcrichton** [comment]
This feature is now entering its final comment period for deprecation

**Comment by arthurprs** [comment]
I think this shouldn't go stable, this is definitely something that would be much better at the type level.
