### ISSUE TITLE
Tracking issue for Vec::resize

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#27790]
This is a tracking issue for the unstable `vec_resize` feature in the standard library. To the best of my knowledge there's no blocker for this beyond "we should decide to have it or not". 

cc @Gankro

**Comment by aturon** [comment]
Nominating for 1.5 FCP discussion.

**Comment by alexcrichton** [comment]
This issue is now entering its cycle-long FCP for stabilization in 1.5

**Comment by bluss** [comment]
The growing part is a "critical" component where we need to grow & zerofill a vector.

**Comment by dhardy** [comment]
As bluss said, I'd like either `resize` or `fn ensure_size_is_at_least(&mut self, len: usize, fill: T)`.

The alternative is cumbersome:

    let by = newlen - v.len();
    v.extend(iter::repeat(0).take(by));

**Comment by FranklinChen** [comment]
I'd like a one-stop way to do what I have to do now:

```rust
let mut a = Vec::with_capacity(k);
a.resize(k, x);
```

**Comment by huonw** [comment]
`vec![x; k]` should work for that.

**Comment by FranklinChen** [comment]
@huonw D'oh, thanks! I honestly spent a long time looking for how to do that and couldn't find it. I just found it at https://doc.rust-lang.org/nightly/std/vec/struct.Vec.html

I'm very concerned that I've been having a lot of trouble finding out this kind of information (another problem was finding slice syntax information), because it's embedded in text rather than displayed as a "method". Perhaps there should be bulleted documentation for all syntax and macros in its own section? Is it my fault I don't necessarily read whole paragraphs of text that are classified as "examples"?

**Comment by bluss** [comment]
@dhardy The alternative is cumbersome and for now, much less efficient, I'll point out.

**Comment by dhardy** [comment]
@bluss thanks. I didn't realise I could create a vec with `vec![x; k]` but would still like `resize`.

**Comment by bluss** [comment]
I'm a bit worried by all the people that don't find `vec![x; N]`.

**Comment by petrochenkov** [comment]
@bluss 
Can you reopen https://github.com/rust-lang/rust/issues/26723 ?
It's still a problem and the motivation for closing it was unconvincing, but I forgot about it at the time.

**Comment by steveklabnik** [comment]
Yeah, discovery is hard :/

**Comment by alexcrichton** [comment]
The libs team discussed this today and the decision was to stabilize.

**Comment by bluss** [comment]
No comment on the dual role of growing and shrinking? Why have both? Only the grow part seems useful (and only the grow part is unique to this method).

**Comment by Gankro** [comment]
@bluss the dual role was frequently requested. I was personally happy when we just had truncate and whatever the growing version was. *shrug*

**Comment by bluss** [comment]
I see.

**Comment by Gankro** [comment]
fwiw this was accepted in collections reform part 2.

See e.g. https://github.com/rust-lang/rfcs/pull/509#discussion_r21779741 for discussion
