### ISSUE TITLE
Dust off MapReduce

### ISSUE THREAD

**Issue by eholk** [rust-lang/rust#2779]
There's a wiki page about the design of a map reduce library for Rust:

https://github.com/mozilla/rust/wiki/Bikeshed-mapreduce

A version of this lives in the wordcount benchmarks, but it would be good to polish this and move it into libstd.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#637
