### ISSUE TITLE
Tracking issue for str::split_at

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#27792]
This is a tracking issue for the unstable `str_split_at` feature in the standard library. These are just mirrors of the slice `split_at` methods so I suspect that they will just be stabilized as-is.

**Comment by bluss** [comment]
I hope this is stabilized soon.

**Comment by alexcrichton** [comment]
This feature is now entering its final comment period for stabilization.

**Comment by ogham** [comment]
I needed this just now and it was exactly what I was looking for!
