### ISSUE TITLE
Tracking issue for consumption into OS handles

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#27797]
This is a tracking issue for the `into_raw_os` feature in the standard library which allows consuming I/O primitives to gain ownership of the underlying resource.

I believe this is basically ready to be stabilized as-is.

**Comment by alexcrichton** [comment]
This feature is now entering its final comment period for stabilization.

**Comment by Stebalien** [comment]
See https://github.com/rust-lang/rfcs/issues/1256 for concerns about guarantees. I think this API is fine to stabilize as-is but wanted to bring this up.
