### ISSUE TITLE
Missing snapshots for Bitrig, FreeBSD 32-bit and FreeBSD 64-bit

### ISSUE THREAD

**Issue by dhuseby** [rust-lang/rust#27805]
This issue is for adding the snapshots.

**Comment by dhuseby** [comment]
Snapshots inbound.  See PR #27821

**Comment by gkoz** [comment]
Could you please look into taking care of NetBSD as well?

**Comment by dhuseby** [comment]
@gkoz I've got a NetBSD builder set up on my VM host already but I've been unable to build it from source just yet.  I've been using my cross-bootstrap scripts to get a rustc that runs on NetBSD.  Just a couple issues left I think, but I'm busy with lots of things right now.  It might be a little while, but I'm hoping to have it online ASAP.

**Comment by gkoz** [comment]
@dhuseby great, thanks for the update!
