### ISSUE TITLE
f32 "%" is broken on MSVC

### ISSUE THREAD

**Issue by eefriedman** [rust-lang/rust#27859]
```rust
fn main() {
  println!("{}", 1.5f32 % std::env::args().len() as f32);
}
```

This code doesn't link on MSVC targets.  (Sorry if I messed up the testcase; I don't have a Rust install on Windows to test with.)

**Comment by Diggsey** [comment]
Isn't this supposed to be removed anyway? #27824 
Does calling fmod directly work?
