### ISSUE TITLE
No single-call way to constant-time move elements in and out of a Vec for pair/triple/etc.-wise operations

### ISSUE THREAD

**Issue by soltanmm** [rust-lang/rust#27861]
This results in some annoying code bloat when trying to mutate two or more vector elements with respect to one another:

```rust
struct A {
    a: u8,
    b: u8
}

impl A {
    pub fn do_stuff(&mut self, other: &mut Self) {
        self.a = other.a % self.b;
        other.b = self.b % other.a;
    }
}

fn main() {
    let mut v = vec![A{a:1,b:1}, A{a:1,b:2}, A{a:2,b:5}, A{a:3,b:6}];
    let i = 0;
    let j = 1;
    
    let mut a = v.swap_remove(i);
    let mut b = v.swap_remove(j);
    a.do_stuff(&mut b);
    let end_minus_1 = v.len() - 1;
    v.push(a);
    v.swap(i, end_minus_1);
    v.push(b);
    v.swap(j, end_minus_1);
    
    // compare with:
    //
    // let mut a = v.replace(i, A{a:0,b:0});
    // let mut b = v.replace(j, A{a:0,b:0});
    // a.do_stuff(&mut b);
    // v.replace(i, a);
    // b.replace(j, b);
}
```
[playpen](http://is.gd/HXBqaH)

Note that we have to also get the vector length and store it as an lvalue to get around `v` being mutably borrowed within the function call expression `v.swap(...)`. We currently have an overall 160% increase in the number of lines of code to do the same thing as a block of code using an operation arguably more atomic than `swap_remove`.

Alternatives to this include cloning the vector once for each argument beyond unary arity of the operation, calling across all the different vectors, and then unifying the result, and using `unsafe` code to skip out on the borrow checker via raw pointers. Neither of those alternatives are particularly satisfying.

**Comment by Gankro** [comment]
Why are you moving the elements at all?

Sounds like you just want mem::replace:

```rust
    use std::mem;
    let mut v = vec![A{a:1,b:1}, A{a:1,b:2}, A{a:2,b:5}, A{a:3,b:6}];
    let i = 0;
    let j = 1;
    let mut a = mem::replace(&mut v[i], A{a:0,b:0});
    let mut b = mem::replace(&mut v[j], A{a:0,b:0});
    
    a.do_stuff(&mut b);
    
    mem::replace(&mut v[i], a);
    mem::replace(&mut v[j], b);
```

But also, why move the elements at all?

```rust
    let mut v = vec![A{a:1,b:1}, A{a:1,b:2}, A{a:2,b:5}, A{a:3,b:6}];
    let (l, r) = v.split_at_mut(1);
    let a = &mut l[0];
    let b = &mut r[0];
    a.do_stuff(b);
}
```

**Comment by soltanmm** [comment]
Huh. I guess I did want `mem::replace`. I believe the `split_at_mut` solution is a bit facetious by taking advantage of the example arbitrarily having `j-i == 1`, but, I'm in no position to complain. Thanks!

**Comment by Gankro** [comment]
I just got lazy on the logic --

```rust
let i = 0;
let j = 0;
assert!(i != j, "Does this even make sense if i = j?");
let (min, max) = if i < j { (i, j) } else { (j, i) }
let (v1, v2) = v.split_at_mut(max);
v1[min].do_stuff(&mut v2[0])
```

Unles you really always want i to do_stuff to j, then you just expand out the branch, etc.
