### ISSUE TITLE
`syntax::ast::Expr_::ExprClosure` should have an Expr instead of Block

### ISSUE THREAD

**Issue by marcusklaas** [rust-lang/rust#27872]
Currently closures of the form `|a| a * a` are very hard to pretty-print since `a * a` is wrapped in an `ast::Block`, even though there are no curly braces.

Match arms contain general sub-expressions, as well.

Is there any technical reason why they are treated differently?

**Comment by nrc** [comment]
Fixed by https://github.com/rust-lang/rust/commit/49772fbf5dc1137a031086999b20ab7b961f3655 (#37412).
