### ISSUE TITLE
rustc --color=never prints colours

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#27879]
```
rustc --color=never
error: no input filename given
```

the “error:” in the message above is coloured red.

**Comment by steveklabnik** [comment]
It does work with everything but this kind of error.

**Comment by steveklabnik** [comment]
I _believe_ that this is `early_error` and `early_warn` in `librustc::session` don't respect `--color`.

**Comment by steveklabnik** [comment]
Yes, they send `Auto` as the color config.
