### ISSUE TITLE
ABIs are validated before cfg-ing

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#27873]
The ABI string for `extern "..."` is validated while being parsed, meaning one can get errors about in `cfg`'d off modules:

```rust
#[cfg(foo)]
mod foo {
    extern "foo" {}
}
```

```
<anon>:3:12: 3:17 error: illegal ABI: expected one of [cdecl, stdcall, fastcall, aapcs, win64, Rust, C, system, rust-intrinsic, rust-call], found `foo`
<anon>:3     extern "foo" {}
                    ^~~~~
```

(Compiled without `--cfg foo`.)

This isn't necessarily wrong, but it is weird and somewhat annoying if one needs it. (It can be worked-around by hiding the `extern` block behind a macro: `macro_rules! annoying ( () => { extern "foo" {} }); annoying!()`.)

**Comment by nagisa** [comment]
Any ideas where we could move the check into?

Any of borrowck, typeck, lints, privacy and resolve don’t exactly fit. I think trans thematically is the best place to have it, but it is a shame to have it error out so late for such an easy to detect and obvious error.

**Comment by huonw** [comment]
> Any ideas where we could move the check into?

> Any of borrowck, typeck, lints, privacy and resolve don’t exactly fit. I think trans thematically is the best place to have it, but it is a shame to have it error out so late for such an easy to detect and obvious error.

NB. we can add a special `abick` pass if necessary (i.e. there's no reason for us to compromise by putting the error in trans).

> IMO there’s no reason to have cfg blocks with code that does not compile.

Yeah, of course. However, there are cases when the `cfg`d code does compile, e.g. I encountered this in #27169 where I added an ABI and had to use it in `core` inside a `#[cfg(not(stage0))]` module. Similarly, if we add ABIs in future, someone might have code designed to compile with Rust 1.0.0, but can take advantage of the newer ABI if it is available.

**Comment by cesarb** [comment]
> I’m personally fine keeping it a parse error, IMO there’s no reason to have cfg blocks with code that does not compile.

The `cfg` block might be to gate nightly-only code. The code within the gated block is compiled only when a cargo feature is enabled; the code outside it works both on stable and nightly.

I hit it myself; I'm playing with the SIMD work from @huonw's pull request, but I want to keep the crate working on stable. [I worked around it by using a conditional `include!(...)`](https://github.com/cesarb/blake2-rfc/commit/4dbacf33dd365ffc6a7e6b8b448adc6afc80fd39).
