### ISSUE TITLE
Change handling of doc comments to warn when mis-parsed, not error.

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#2789]
Now that we've implemented doc comments as attributes I am doubtful that it was the correct thing to do. There are a lot of positions where attributes aren't valid and now the parser rejects things like:

```
let x = y; //// xy
````

I was planning putting some smarts into the lexer to detect four slashes and not consider those doc attributes, but then patrick checked in some code like `///< comment` which was rejected.

Comments not being treated as whitespace is weird.

**Comment by carols10cents** [comment]
(Hi, I'm trying to [help make E-easy issues more accessible to newcomers](https://users.rust-lang.org/t/mentoring-newcomers-to-the-rust-ecosystem/3088/15?u=carols10cents) :smile_cat:)

Checking reproducibility:
- [x] [Four slashes compiles without error](http://is.gd/Zfgiw8)
- [x] [The `/****** Some Stuff ******/` comment compiles without error](http://is.gd/pv06Mj)
- [x] [Three slashes does not compile](http://is.gd/4DxIGk) with the error:
```
<anon>:3:16: 3:33 error: expected item after doc comment
<anon>:3     let x = 3; /// three slashes
                        ^~~~~~~~~~~~~~~~~
```
which seems clearer than the "expected item after attributes" error, so I think this is fixed
- [?] [mikedilger's code does not compile](http://is.gd/f35W7l) with the same error reported:
```
<anon>:6:3: 6:4 error: an inner attribute is not permitted in this context
<anon>:6 #![feature(phase)]
           ^
<anon>:6:3: 6:4 help: place inner attribute at the top of the module or block
error: aborting due to previous error
```

I'm not totally convinced this is the same problem as the others though... but maybe it is? [A smaller example](http://is.gd/ZD6DKu):

```
/**
 * If you remove this comment, the compiler error will go away.
 * It's not very clear from the error message what the problem is.
 */

#![feature(phase)]
fn main() {
    println!("hi");
}
```

From #4106:

- [?] [Original example fails with a similar confusing error as originally reported](http://is.gd/EdPr56), that is, it's not clear that the comment is the problem, it just says "expected one of `const`, `extern`, `fn`, `type`, or `unsafe`, found `}`"
- [x] [Trailing empty doc comment](http://is.gd/1RgDfW) fails with the clear error message "expected item after doc comment"

So it looks like there are still some less-than-ideal cases, and that the fix would be a better error message indicating that there was a doc comment in an unsupported location? Is that correct?

If so, where would one start looking to go about making the error message better?

**Comment by Manishearth** [comment]
Thanks! :smile:

**Comment by Manishearth** [comment]
> and that the fix would be a better error message indicating that there was a doc comment in an unsupported location? Is that correct?

Yes. We basically want to add a note around https://github.com/rust-lang/rust/blob/master/src/libsyntax/parse/parser.rs#L3415

It would be even better if these were parsed correctly, but that's not an easy fix.

**Comment by Wafflespeanut** [comment]
I'll try this! :)

**Comment by cflewis** [comment]
Should this be closed?

**Comment by mikedilger** [comment]
My comment above is still applicable, 2 years on.  If it has been determined to be a separate issue, I can file it separately.  Otherwise I think this should stay open.

**Comment by brson** [comment]
I've opened a new issue specifically to deal with @mikedilger's issue: https://github.com/rust-lang/rust/issues/34516
