### ISSUE TITLE
Rust1.2  Windows7 64bit, rust-openssl issue or a rust-gcc issue

### ISSUE THREAD

**Issue by ScottHuangZL** [rust-lang/rust#27898]
https://users.rust-lang.org/t/i-try-to-build-a-nickel-example-but-gap-at-openssl-sys-0-6-4/2528/5

Please refer to the forum post. We cannot build OpenSSL at Win7 64bit enviroment by Rust1.2 even I have install openssl at C:\OpenSSL-Win64 and set ENV already.

Please help to resolve it, thanks.

**Comment by alexcrichton** [comment]
Thanks for the report! This looks like it's an issue with rust-openssl, however, and not necessarily the compiler and/or standard library itself, so could you open an issue over there instead?
