### ISSUE TITLE
Write nomicon dot-operator section

### ISSUE THREAD

**Issue by Gankro** [rust-lang/rust#27909]
https://doc.rust-lang.org/nightly/nomicon/dot-operator.html

**Comment by steveklabnik** [comment]
triage: no change ❤️

**Comment by steveklabnik** [comment]
Triage: I'm giving this a close now that the nomicon has its own repo: https://github.com/rust-lang-nursery/nomicon

this still needs to be done, but let's just treat that repo as a clean slate.
