### ISSUE TITLE
Write nomicon Implementing Arc and Mutex chapter

### ISSUE THREAD

**Issue by Gankro** [rust-lang/rust#27910]
https://doc.rust-lang.org/nightly/nomicon/arc-and-mutex.html

**Comment by mark-i-m** [comment]
@Gankro The book is really great! Do you know of plans to complete this chapter?

**Comment by steveklabnik** [comment]
Triage: I'm giving this a close now that the nomicon has its own repo: https://github.com/rust-lang-nursery/nomicon

this still needs to be done, but let's just treat that repo as a clean slate.
