### ISSUE TITLE
Book: "Prelude" explanation could be more prominent/thorough

### ISSUE THREAD

**Issue by niconii** [rust-lang/rust#27917]
"Prelude" doesn't seem to be a very common term outside of Haskell, yet it seems to only be explained in the Guessing Game section of the book. Even then, it only mentions it being the stuff imported by default, which doesn't explain `std::io::prelude`.

**Comment by steveklabnik** [comment]
I'm not sure where this actually belongs, do you have any thoughts?

> Even then, it only mentions it being the stuff imported by default, which doesn't explain std::io::prelude.

Can you elaborate on this? It does say the word 'prelude', and links to the module documentation for it, which covers it further.

**Comment by niconii** [comment]
Well, I guess what I'm getting at there is that in contrast to `std::prelude`, `std::io::prelude` isn't "a set of things that are imported by default"; rather it's "a set of things that are useful to import all at once". It's a similar meaning, but it's not quite the same thing.

As for where it belongs in the book, I'm not entirely sure either; maybe a short section in the Syntax and Semantics chapter?

**Comment by niconii** [comment]
Also, I guess for some context, this issue arose because of [some confusion in IRC](https://botbot.me/mozilla/rust/msg/47688806/).

**Comment by steveklabnik** [comment]
Ahhhh I missed the io!
