### ISSUE TITLE
Not possible to get pid and stdout on a spawned process

### ISSUE THREAD

**Issue by joewilliams** [rust-lang/rust#27928]
Using the unstable Child `.id()` API it does not seem possible to both get the PID and stdout. I have created reproducible code and output [here](https://gist.github.com/joewilliams/7516a093e192adf72af2). I believe this may be due to the use of `.spawn()` and `.wait_with_output()` and stdout having already been written to stdout. At least I believe that's what my example shows. Is it impossible currently to get both the PID and stdout or am I doing it wrong™?

**Comment by eefriedman** [comment]
The default behavior for stdout differs depending on whether you use `output()` or `spawn()`; you can override the default using the `stdout()` method.  Example: https://play.rust-lang.org/?gist=19acc1b30fc88b2a615b&version=nightly .  See also https://doc.rust-lang.org/nightly/std/process/struct.Command.html .

**Comment by joewilliams** [comment]
That worked perfectly, thank you!
