### ISSUE TITLE
Cargo: produce deterministic filenames for  `build --test` and `test --no-run`

### ISSUE THREAD

**Issue by bruno-medeiros** [rust-lang/rust#27923]
I'm doing IDE integration, and I want my IDE to be able to debug the test binaries - for which the IDE has to launch those programs itself, it shouldn't use `cargo test`. However (unlike `--bin`for example) neither `build --test` nor `test --no-run` produce a deterministic filename, but something random like `test1-748b2ca97d589628.exe`.

**Comment by steveklabnik** [comment]
Hey @bruno-medeiros ! There's actually a separate tracker for Cargo, over at  https://github.com/rust-lang/cargo/issues/new, would you mind filing this over there please? thanks!

**Comment by bruno-medeiros** [comment]
My bad.
https://github.com/rust-lang/cargo/issues/1924
