### ISSUE TITLE
Improve book support for windows

### ISSUE THREAD

**Issue by Rannath** [rust-lang/rust#27936]
https://doc.rust-lang.org/stable/book/testing.html could be improved by mentioning `echo %errorlevel%` for use in Windows. Perhaps an appendix for Windows?

**Comment by steveklabnik** [comment]
I don't want to suggest that Windows people are second-class by putting it in an appendix, so this should just be in the regular docs.

This is the return value of a program, yes? What's some good docs on what `%errorlevel%` is? I don't use windows that much myself.

/cc @retep998

**Comment by retep998** [comment]
I cannot find any direct msdn documentation on `%errorlevel%` although I can find Microsoft blog posts that refer to it.

http://blogs.msdn.com/b/oldnewthing/archive/2008/09/26/8965755.aspx
http://blogs.msdn.com/b/powershell/archive/2006/09/15/errorlevel-equivalent.aspx

**Comment by Rannath** [comment]
Honestly I got it from stackoverflow.
http://www.robvanderwoude.com/errorlevel.php is another good one retep ninja'd me on my others.

**Comment by eefriedman** [comment]
Official MS documentation: https://web.archive.org/web/20140205211715/http://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/ntcmds_shelloverview.mspx .  Apparently Microsoft decided to delete all references to cmd.exe from the official documentation.
