### ISSUE TITLE
from_raw_parts needs an equivalent for dynamically-sized structs

### ISSUE THREAD

**Issue by geofft** [rust-lang/rust#27940]
There's no good way to generate a non-raw pointer to a struct with a DST in tail position, which would handy for some FFI use cases involving flexible array members and the like. You can fake it in stable Rust, but only by abusing `transmute`:

``` rust
struct PascalString<T: ?Sized> {
    length: u8,
    body: T,
}

unsafe fn parse_pascal_string<'a>(s: *const u8) -> &'a PascalString<[u8]> {
    let length = std::ptr::read(s);
    std::mem::transmute(std::slice::from_raw_parts(s, length as usize))
}

fn main() {
    let x = b"\x05Hello world";
    let y = unsafe { parse_pascal_string(x.as_ptr()) };
    println!("{}", std::str::from_utf8(&y.body).unwrap());
}
```

This [works fine](http://is.gd/3Cx8kr) in stable Rust, but the `transmute` from `&[u8]` to `&PascalString<[u8]>` is pretty bogus (the `&[u8]` is pretty meaningless). What I'm doing is assuming that the representation of a fat pointer to a dynamically-sized struct looks like the representation of a slice, and that the length field is the length of the dynamically-sized tail element. To be fair, this is rule `Fat-Struct` from @nikomatsakis' [DST blog post](http://smallcultfollowing.com/babysteps/blog/2014/01/05/dst-take-5/), but I'm not sure I should be reading that as a stability promise, let alone an ABI stability promise.

An `unsafe fn from_raw_parts<T: ?Sized>(p: *const T, len: usize) -> &'a T` explicitly for fat struct pointers (as opposed to `std::slice::from_raw_parts`, which returns `&'a [T]`), with rules on what `p` and `len` should be and what `T`s are valid (`!Sized`, for starters), would probably solve this. IMO stating those rules in doc instead of in the function type is fine, since it's no worse than stating rules about the returned lifetime in `std::slice::from_raw_parts` in doc. This is an unsafe function, after all.

**Comment by arielb1** [comment]
Your references-to-pascal-string end up containing a (redundant) length, which could break FFI interoperability. `*const T` already contains the duplicate information.

**Comment by nikomatsakis** [comment]
So I've always envisioned that we'd wind up with some primitive routines for manipulating fat pointers. I imagine some of these might come about as part of the allocator design, since writing a generic allocator often winds up requiring the ability to talk about fat/thin pointers. We need to be a bit careful with the design: I'd like it to scale to "obese" pointers that have more than one word of extra data, should we want that in the future. At some point I sketched out a set of such primitives but I'm not sure where those notes have gone off to.

**Comment by steveklabnik** [comment]
Triage: it's been 18 months with no comments. Smaller additons to the standard library don't need RFCs anymore, so sending in a PR to implement this seems like a good idea if anyone still desires this. Closing!
