### ISSUE TITLE
Code in E0139 explanation is not valid anymore

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#27946]
```
let result: SomeType = mem::uninitialized();
unsafe { copy_nonoverlapping(&v, &result) };
result // `v` transmuted to type `SomeType`
```

std::ptr::copy_nonoverlapping takes 3 arguments, but only 2 are provided. It also does not typecheck anymore either.

**Comment by apasel422** [comment]
I think this example should just be removed, as `std::ptr::copy_nonoverlapping` requires its source and destination types to be the same. For a "real" manual transmute, someone could transmute the pointers to `u8` and then pass the correct number of bytes as the third argument to that function.
