### ISSUE TITLE
Tests output without color when RUST_TEST_NOCAPTURE=1 is set

### ISSUE THREAD

**Issue by varding** [rust-lang/rust#27959]
Is it design so or a bug?

platform:win7 x64  rustc 1.2.0 (082e47636 2015-08-03)
 
tests output with color:
![color](https://cloud.githubusercontent.com/assets/4688041/9428055/5916ee66-49ce-11e5-8003-adec646282ac.png)

after set RUST_TEST_NOCAPTURE=1 in console
tests output without color:
![no_color](https://cloud.githubusercontent.com/assets/4688041/9428057/5d492f80-49ce-11e5-9a42-acf3b8bb9049.png)

**Comment by alexcrichton** [comment]
This is currently intentional because the concurrent output could interfere with the control codes used for colorization on some terminals. As a result if we're not capturing output (which means lots of output could happen concurrently) we disable colorization.
