### ISSUE TITLE
Compiler panic on std::str::FromStr::Err import

### ISSUE THREAD

**Issue by spencerdeinum** [rust-lang/rust#27951]
I receive a panic in the compiler when attempting to build the following code. I am just learning rust so I have no idea if this could would actually work, but I am assuming it should not panic.

I tried this code:

```rust
use std::str::FromStr::Err;

fn main() {
}

fn usage_error(error: Err) {
    println!("{}", error);
}
```

I expected to see this happen: Code compiling OR returning an error.

Instead, this happened: Compiler panics

## Meta

`rustc --version --verbose`:

```
rustc 1.2.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-apple-darwin
release: 1.2.0
```

Backtrace:

thread 'rustc' panicked at 'assertion failed: index.end <= self.len()', src/libcore/slice.rs:544

stack backtrace:
   1:        0x10aea06c5 - sys::backtrace::write::ha0392dfc93409ff9uns
   2:        0x10aea8f23 - panicking::on_panic::h9af4e864a0f7cedbiGw
   3:        0x10ae64ce2 - rt::unwind::begin_unwind_inner::hb8083a9296ba29c5uow
   4:        0x10ae65a39 - rt::unwind::begin_unwind_fmt::h9b0a9c1b54fdf9d2Anw
   5:        0x10aea8aac - rust_begin_unwind
   6:        0x10aefc3e5 - panicking::panic_fmt::h2417f2413f9273e9H8B
   7:        0x10aef4e31 - panicking::panic::h299642838fa3d1dce7B
   8:        0x10821067e - astconv::finish_resolving_def_to_ty::hfc5e6c50adf71d1076v
   9:        0x1081cee3b - astconv::ast_ty_to_ty::h397754290b665be5V8v
  10:        0x108226188 - vec::Vec<T>.FromIterator<T>::from_iter::h12406954681214066773
  11:        0x10822580b - astconv::ty_of_method_or_bare_fn::haf6915a743325fc6Now
  12:        0x10824d9b8 - collect::type_scheme_of_item::h5546378e96fa8371NMy
  13:        0x1082442fc - collect::convert_typed_item::h23dad15637336536rRy
  14:        0x10822baa9 - collect::convert_item::hb6675e38b8981edfR0x
  15:        0x1082286d6 - collect::collect_item_types::h0d25780da09ccaf9W7w
  16:        0x10827945a - check_crate::h7ad0d3fa235b056c9fD
  17:        0x107ab3496 - driver::phase_3_run_analysis_passes::closure.15763
  18:        0x107ab1984 - middle::ty::with_ctxt::h13069179515655679932
  19:        0x107aac78a - driver::phase_3_run_analysis_passes::h1063659777208750563
  20:        0x107a8f887 - driver::compile_input::h07fa904d203e5d51Tba
  21:        0x107b6b74f - run_compiler::hf4c1ec13cef326ebx7b
  22:        0x107b69003 - boxed::F.FnBox<A>::call_box::h2932037325644119082
  23:        0x107b687c7 - rt::unwind::try::try_fn::h14976289988143769367
  24:        0x10af332e8 - rust_try_inner
  25:        0x10af332d5 - rust_try
  26:        0x10ae92ba5 - rt::unwind::try::inner_try::h57bed9f7476c75a2nkw
  27:        0x107b689f8 - boxed::F.FnBox<A>::call_box::h16983286315137263172
  28:        0x10aea79ad - sys::thread::Thread::new::thread_start::h74554fc940d53646HIv
  29:     0x7fff8c96c059 - _pthread_body
  30:     0x7fff8c96bfd6 - _pthread_start

**Comment by alexcrichton** [comment]
This has been fixed in nightly, but thanks for the report!

**Comment by spencerdeinum** [comment]
No problem! Keep up the good work!
