### ISSUE TITLE
Trait object lifetime issues

### ISSUE THREAD

**Issue by arcnmx** [rust-lang/rust#27953]
The following code seems like it should typecheck fine, but doesn't.

``` rust
    struct S;
    trait T { }

    impl AsRef<T> for S {
        fn as_ref(&self) -> &T {
            unimplemented!()
        }
    }
```

`error: method `as_ref` has an incompatible type for trait: expected bound lifetime parameter , found concrete lifetime`
(note that the space after "parameter" seems suspicious)

**Comment by eefriedman** [comment]
I think your testcase isn't valid Rust.  The following works:

```rust
struct S;
trait T { }
impl<'a> AsRef<T+'a> for S {
    fn as_ref<'b>(&'b self) -> &'b (T+'a) {
        unimplemented!()
    }
}
fn main() {
    S.as_ref();
}
```
The following also works:
```rust
struct S;
trait T { }
impl AsRef<T+'static> for S {
    fn as_ref(&self) -> &(T+'static) {
        unimplemented!()
    }
}
fn main() {}
```

And the following, which I think is equivalent to your testcase, doesn't work because of the lifetime mismatch in the return type:

```rust
struct S;
trait T { }
impl AsRef<T+'static> for S {
    fn as_ref<'a>(&'a self) -> &'a (T+'a) {
        unimplemented!()
    }
}
fn main() {}
```

Granted, the diagnostic is terrible.

**Comment by arcnmx** [comment]
Aha! I'd tried different variations with the elision but hadn't come across that. Thanks!

**Comment by KalitaAlexey** [comment]
Why should explicit lifetime be used?
Code from `string.rs`
```
impl AsRef<str> for String {
    #[inline]
    fn as_ref(&self) -> &str {
        self
    }
}
```
There is no explicit lifetime.

**Comment by arielb1** [comment]
@KalitaAlexey 

`str` and `String` are not trait objects.

**Comment by KalitaAlexey** [comment]
I don't see connection. Could you please provide more information?

**Comment by leodasvacas** [comment]
Triage: Diagnostics for this have improved and now give a detailed explanation. It's still not great but the issue outdated. Should be closed.

As a note, the following is the minimal that compiles:
```rust
struct S;
trait T { }

impl AsRef<T> for S {
    fn as_ref(&self) -> &(T+'static) {
        unimplemented!()
    }
}
```

**Comment by steveklabnik** [comment]
I agree. Closing!
