### ISSUE TITLE
Note where implicit Sized requirement comes from

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rust#27964]
I was not aware that `Sized` is a default requirement for type parameters, so I was very confused why [this code doesn't compile](https://play.rust-lang.org/?code=%0Atrait%20OopsSized%3CO%20%2F*%20missing%20%3A%20%3FSized%20*%2F%3E%20%7B%0A%20%20%20%20fn%20observers%28%26self%29%20-%3E%20Option%3CBox%3CO%3E%3E%3B%0A%7D%0A%0A%0Astruct%20Foo%3B%0A%0Atrait%20Unsized%20%7B%7D%0A%0Aimpl%20OopsSized%3CUnsized%3E%20for%20Foo%20%7B%0A%20%20%20%20fn%20observers%28%26self%29%20-%3E%20Option%3CBox%3CUnsized%3E%3E%20%7B%0A%20%20%20%20%20%20%20%20None%0A%20%20%20%20%7D%0A%7D%0A%0Afn%20main%28%29%20%7B%7D&version=nightly):

``` rust
trait OopsSized<O /* missing : ?Sized */> {
    fn foo(&self) -> Option<Box<O>>;
}

trait Unsized {}

struct Foo;

impl OopsSized<Unsized> for Foo {
    fn foo(&self) -> Option<Box<Unsized>> {
        None
    }
}
```

I couldn't understand why compiler insists on having `Sized` for the innermost type, if `Box` doesn't care and makes the boxed type sized.

The current explanation for E0277 doesn't cover this case specifically, and it doesn't mention the unusual `?Sized` syntax. It'd help me if, for example, the hint:

> note: required by `OopsSized`

made implied defaults explicitly spelled out:

> note: required by `OopsSized<O: Sized>`

and/or hinted how to fix it:

> note: required by `OopsSized`, because `O` by default is `Sized`. Try `O: ?Sized`.

**Comment by makoConstruct** [comment]
I second this, it's extremely confusing.

```
trait Reader{}
impl Reader for () {}
fn reader_for()-> Box<Reader> { Box::new(()) }

fn check_vec<R:Reader>(r:&R){} //R needs to be Reader+?Sized for some reason, but new rust programmers wont know that.

fn main() {
	check_vec(&*reader_for());
		//error: the trait `core::marker::Sized` is not implemented for the type `Reader<T>`
		//note: `Reader<T>` does not have a constant size known at compile-time
		//note: required by `check_vec`
}
```

The user will not be able to figure out why the function requires Sized when they did not define it to require Sized and when none of its functionality depends on Sized.

**Comment by estebank** [comment]
The original case has had no changes.

The case in the last comment has the following output in #68377:

```
error[E0277]: the size for values of type `dyn Reader` cannot be known at compilation time
 --> file.rs:8:15
  |
5 | fn check_vec<R:Reader>(r:&R){} //R needs to be Reader+?Sized for some reason, but new rust programmers wont know that.
  |    --------- -       - help: consider relaxing the implicit `Sized` restriction: `+  ?Sized`
  |              |
  |              required by this bound in `check_vec`
...
8 |     check_vec(&*reader_for());
  |               ^^^^^^^^^^^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `std::marker::Sized` is not implemented for `dyn Reader`
  = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
```

**Comment by najamelan** [comment]
One from the [user forum](https://users.rust-lang.org/t/wrapping-boxed-errors/38951), [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=66943a8d8e850922681779926208b1fd):
```rust
use std::error::Error;

fn library_function<F1, E1>(f1: F1) -> Result<(), E1>
where
    F1: FnOnce() -> Result<(), E1>,
    E1: Error, // <-remove this line -> compile
{
    f1()
}

fn main() -> Result<(), Box<dyn Error>> 
{
    library_function( || Ok(()) )
}
```
Error:
```
error[E0277]: the size for values of type `dyn std::error::Error` cannot be known at compilation time
  --> src/main.rs:13:5
   |
3  | fn library_function<F1, E1>(f1: F1) -> Result<(), E1>
   |    ----------------
...
6  |     E1: Error, // <-remove this line -> compile
   |         ----- required by this bound in `library_function`
...
13 |     library_function( || Ok(()) )
   |     ^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `dyn std::error::Error`
   = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
   = note: required because of the requirements on the impl of `std::error::Error` for `std::boxed::Box<dyn std::error::Error>`
```
Analysis:
There is a blanket impl for `Error` on `Box<T>`, but not on `Box<T: ?Sized>`. credit to @Yandros

Go figure.

I suppose the ideal here would be something like: "Box<dyn Error> does not implement Error. The following Impl where found: impl `Error` for `Box<T>` -> requires T: Sized"

**Comment by estebank** [comment]
@najamelan could you copy that comment as a new ticket? The original report will be closed by #69709 but yours won't be addressed by that PR, sadly.

**Comment by estebank** [comment]
Current output:

```
error[E0277]: the size for values of type `(dyn Unsized + 'static)` cannot be known at compilation time
  --> src/main.rs:11:6
   |
2  | trait OopsSized<O /* missing : ?Sized */> {
   |                 - required by this bound in `OopsSized`
...
11 | impl OopsSized<Unsized> for Foo {
   |      ^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `(dyn Unsized + 'static)`
   = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
```

**Comment by estebank** [comment]
Output with #73261:

<img width="961" alt="Screen Shot 2020-06-16 at 5 27 01 PM" src="https://user-images.githubusercontent.com/1606434/84841246-a13a7580-aff6-11ea-9eed-cad2236588b3.png">

```
error[E0277]: the size for values of type `(dyn Unsized + 'static)` cannot be known at compilation time
 --> file6.rs:9:6
  |
1 | trait OopsSized<O /* missing : ?Sized */> {
  |                 - required by this bound in `OopsSized`
...
9 | impl OopsSized<Unsized> for Foo {
  |      ^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `std::marker::Sized` is not implemented for `(dyn Unsized + 'static)`
  = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
help: consider relaxing the implicit `Sized` restriction
  |
1 | trait OopsSized<O: ?Sized /* missing : ?Sized */> {
  |                  ^^^^^^^^
```
