### ISSUE TITLE
No way to timeout when receiving from a Receiver

### ISSUE THREAD

**Issue by adamcrume** [rust-lang/rust#27965]
It apparently used to be possible to timeout on `Receiver::recv` by using a `Timer` and `select!`.  Now that `Timer` is gone, that's not possible.  Either something like `Timer` should be re-introduced, or something similar to `Receiver::try_recv` could be added which accepts a timeout.

**Comment by alexcrichton** [comment]
Thanks for the report! This is [currently being tracked](https://github.com/rust-lang/rfcs/issues/962) in the RFC repo.
