### ISSUE TITLE
Type parameters not allowed on Result

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#27969]
``` rust
fn main() {
    let () = Result::<(), ()>::Ok(());
    //let () = Result::Ok::<(), ()>(());  // <-- This is what I meant to do
}
```

gives:

```
<anon>:2:23: 2:25 error: type parameters are not allowed on this type [E0109]
<anon>:2     let () = Result::<(), ()>::Ok(());
                               ^~
```

This is misleading, since `Result` can obviously have type params. I also think the error should mention the type, since it might not always be obvious (especially with the span pointing at the first type parameter instead of the type).

**Comment by steveklabnik** [comment]
Triage: the error is still the same.

**Comment by burdges** [comment]
Just ran into this.  It feels inconsistent with `Struct::<T>::method()`.  If its painful to fix, then maybe the error message could explain where the type parameters should go.

**Comment by steveklabnik** [comment]
This... now seems to work?

```rust
fn main() {
    let x = Result::<(), ()>::Ok(());
}
```

compiles without error. I'm not sure what happened in the last two years to fix it. Other combinations work as well, like `Result::<i32, ()>::Ok(5)`.
