### ISSUE TITLE
macro_rules cannot expand `concat!(...)` into a variant arm

### ISSUE THREAD

**Issue by erickt** [rust-lang/rust#27967]
Here is a reduced example of the bug:

``` rust
macro_rules! foo {
    ($key:expr) => {
        match "foobar" {
            $key => "",
            _ => "",
        }
    }
}

fn main() {
    foo! {
        concat!("foo", "bar")
    };
}
```

This errors with:

```
foo.rs:4:13: 4:17 error: unexpected token: `concat!("foo" , "bar")`
foo.rs:4             $key => "",
                     ^~~~
```

**Comment by eefriedman** [comment]
Did you mean to write `($key:pat)`?

**Comment by erickt** [comment]
@eefriedman: hey you're right that did work. With some tweaks to fix the type error:

```
macro_rules! foo {
    ($key:pat) => {
        match "foobar" {
            $key => "",
            _ => "",
        }
    }
}

fn main() {
    foo! {
        concat!("foo", "bar")
    };
}
```

It would be nice to still fix `$(key,expr)` since this does work:

```rust
macro_rules! foo {
    ($key:expr) => {
        match "foo" {
            $key => "",
            _ => "",
        }
    }
}

fn main() {
    foo! {
        "foo"
    };
}
```

It's nice to have the `$(key:pat)` alternative though.

**Comment by eddyb** [comment]
@erickt That's a special-case for `ExprLit`. I *guess* `ExprMac` could also be special-cased to be "convertible" to `PatMac`.

**Comment by steveklabnik** [comment]
Triage: no change, no comments in 19 months. I'm going to say we're not going to end up making this change. 😄

**Comment by eddyb** [comment]
@steveklabnik It just got forgotten, like most things you'll find are. cc @jseyfried

**Comment by jseyfried** [comment]
This seems reasonable to support since now since it's backwards compatible and we want to go in this direction for macros 2.0 anyway.

**Comment by steveklabnik** [comment]
Triage: this now compiles!
