### ISSUE TITLE
Fix a number of `run-make` tests on MSVC.

### ISSUE THREAD

**Issue by DiamondLovesYou** [rust-lang/rust#27979]
Due to the way MSYS sandboxes file paths, paths passed to `cl.exe` are expanded into values which are invalid outside of MSYS.

**Comment by alexcrichton** [comment]
This was done in https://github.com/rust-lang/rust/pull/28421

**Comment by Eh2406** [comment]
There is a FIXME related to this issue,
https://github.com/rust-lang/rust/blob/master/src/test/run-make/relocation-model/Makefile#L13
Now that the issue is closed can the FIXME be fix, or made more specific?
