### ISSUE TITLE
std::net::AddrParseError doesn't implement std::error::Error

### ISSUE THREAD

**Issue by Magisun** [rust-lang/rust#27973]
I was writing a generic argument parse validator for my program, which involved matching errors from FromStr::parse. After constraining the error type to Error, I ran into an issue when creating a validator for parsing IP addresses:

    main.rs:48:24: 48:47 error: the trait `std::error::Error` is not implemented for the type
     `std::net::parser::AddrParseError` [E0277]

**Comment by sfackler** [comment]
Fixed in #27976
