### ISSUE TITLE
Supply snapshot source tarballs for src/snapshots.txt

### ISSUE THREAD

**Issue by mneumann** [rust-lang/rust#27977]
It would be great if, in addition to the nightly tarballs, there were .tar.gz's for every snapshot listed in ```src/snapshots.txt```. This would make snapshot creation on e.g. DragonFly simpler, as it could be more easily integrated into the ports system, which do not like fetching sources from git repos especially as it comes to recursive git repos. 

Right now you can easily build daily snapshots from source, but to build a specific listed snapshot, it requires a much different procedure.

**Comment by alexcrichton** [comment]
The SHA of each hash is listed, and I believe you can download the tarball of any SHA from github, would that be enough?

**Comment by mneumann** [comment]
I think github does not include the git submodules.

**Comment by mneumann** [comment]
I am going the way to manually download all git submodules (I think there are only 4 of them). Closing this issue :)
