### ISSUE TITLE
No terminal color with Git for Windows 2.5 (mintty.exe)

### ISSUE THREAD

**Issue by JoshBlake** [rust-lang/rust#28005]
I am using 1.3 beta and previously was using Git for Windows 1.9.5 with the msys terminal. Rustc output had pretty colors, but then today I upgraded to Git for Windows 2.5, which includes the mintty.exe replacement terminal (w/ bash shell). The terminal itself has colored text, such as on the prompt lines, but rustc/cargo no longer have color. 

I've searched all previous issues and support for mintty and msys, but haven't been able to solve the problem. (Tried setting the TERM variable to different combinations, setting MSYSCON, etc.) I've also read through the code for rust/libterm and the term crate. When I create a test program with the term crate, console color works fine:

```
extern crate term;

fn main() {
    let mut t = term::stderr().unwrap();

    t.fg(term::color::GREEN).unwrap();
    write!(t, "hello, ").unwrap();

    t.fg(term::color::RED).unwrap();
    writeln!(t, "world!").unwrap();

    t.reset().unwrap();
}
```

So it seems the term crate is able to produce color in my environment, but I cannot figure out why rustc cannot. I'm hoping that someone can give some advice or help me debug this issue.

Thanks

**Comment by retep998** [comment]
`rustc` and `cargo` only use terminal colors if the terminal they are in is a TTY. The only way they can tell whether they are in a TTY is by checking whether `GetConsoleMode` succeeds, which only succeeds on standard Windows consoles. The typical msys bash that Git for Windows provides uses the standard Windows console and thus colors are enabled. When using mintty you are no longer using a standard Windows console and `rustc`/`cargo` have no way to know whether they are in a terminal (mintty exposes stdin and stdout as nothing more than pipes), thus colors are disabled. If you force enable colors then colors will work fine, but AFAIK there's no convenient way to always force enable it.

**Comment by JoshBlake** [comment]
Thanks for the explanation. I already use bash aliases like cb for cargo build, so I will try adding the cargo color options from https://github.com/rust-lang/cargo/pull/1832
