### ISSUE TITLE
i32::pow only handles overflow up to an exponent of 1023

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#28012]
Playpen: http://is.gd/zhwksu

```rust
fn main() {
    let x: i32 = 2;

    println!("{}", x.pow(1024));
    println!("{}", x.pow(1023));
}
```

Prints:
```
0
thread '<main>' panicked at 'arithmetic operation overflowed', ../src/libcore/num/mod.rs:550
```

Interestingly, this only seems to happen with an even base. The overflow is detected correctly when `x` is set to 3 or other odd numbers.

**Comment by bluss** [comment]
cc @pnkfelix introducing this behavior in c8db89aa82573b89481fde598da6e54371f266cb, it may be deliberate.

**Comment by BurntSushi** [comment]
I'm not sure this is intended behavior, and if it was, it does seem surprising. Should a method called `pow` really be able to return a wrong answer? What seems to happen is if the exponent is even, and each iteration of the `pow` loop divides by `2`, then the `if (exp & 1) == 1 {` check is never hit, which I think is supposed to cause `pow` to panic if overflow is observable. Certainly overflow is observable here.

**Comment by alexcrichton** [comment]
This looks like a bug, seems fine to fix

**Comment by nikomatsakis** [comment]
I agree with @alexcrichton
