### ISSUE TITLE
Can't expand macro inside slice pattern

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#28041]
``` rust
#![feature(slice_patterns)]

macro_rules! m {
    () => ( c.. );
}

fn main() {
    match [0, 1, 2] {
        [ c.. ] => {}
        [ m!() ] => {}
    }
}
```

Gives this error:

```
<anon>:4:14: 4:16 error: macro expansion ignores token `..` and any following
<anon>:4     () => ( c.. );
                      ^~
<anon>:10:11: 10:15 note: caused by the macro expansion here; the usage of `m` is likely invalid in this context
<anon>:10         [ m!() ] => {}
                    ^~~~
```

The macro is accepted, but apparently parsed as a regular pattern. Since `c..` isn't a valid pattern, this fails.

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by petrochenkov** [comment]
Correct syntax:
```rust
    match [0, 1, 2] {
        [ c.. ] => {}
        [ m!().. ] => {}
    }
```
Macros are permitted in *pattern* position, and therefore need to expand into a pattern. `PAT..` is not a pattern, `PAT` is a pattern. `..` is some special disambiguating syntax to discern between elements and subslices.
I'd say this is not an issue, or at least "works as expected".

**Comment by jonas-schievink** [comment]
Makes sense, feel free to close
