### ISSUE TITLE
Rename Rust to be less discriminatory towards noble metals

### ISSUE THREAD

**Issue by rightfold** [rust-lang/rust#28059]
Rust should be renamed to something which does not discriminate against noble metals. Not all metals corrode, such as ruthenium, rhodium, palladium, silver, osmium, iridium, platinum, and gold, and yet they still make significant contributions to society and thus should not be ignored or bullied. Please change the name of Rust to something that does not discriminate against noble metals. This would also conform better to the [Code of Conduct](https://www.rust-lang.org/conduct.html):

> We are committed to providing a friendly, safe and welcoming environment for all.

**Comment by plainSimpleGarak** [comment]
I second this motion.

**Comment by griwes** [comment]
I third this motion.

**Comment by ApfelUser** [comment]
I fourth this motion.

**Comment by Jefffrey** [comment]
I fifth this motion.
