### ISSUE TITLE
Set recovery methods

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#28050]
Tracking issue for https://github.com/rust-lang/rfcs/pull/1194

cc https://github.com/rust-lang/rust/pull/28043

**Comment by alexcrichton** [comment]
Leaving open as this is actually the tracking issue for these methods.

**Comment by apasel422** [comment]
Whoops, my bad!

**Comment by apasel422** [comment]
Looks like this wasn't actually re-opened.

**Comment by alexcrichton** [comment]
Oops..

**Comment by alexcrichton** [comment]
:bell: This issue is now entering its cycle-long **final comment period** for stabilization in 1.9 :bell:

**Comment by aturon** [comment]
These look good to me. My only (very small) hesitation is with the naming of `replace`, given that it still inserts the element even if one is not present.

In an ideal world, this method would simply be `insert`. Ah well.

**Comment by alexcrichton** [comment]
The libs team discussed this during triage and the decision was to **stabilize**.

One other possible name for `replace` which was discussed was `put` but it doesn't quite invoke the same connotation that `replace` does with relation to `insert`.
