### ISSUE TITLE
Document use _ as _ syntax

### ISSUE THREAD

**Issue by sinistersnare** [rust-lang/rust#28064]
/u/DroidLogician on reddit [mentioned](https://www.reddit.com/r/rust/comments/3ink8q/is_there_a_way_to_include_a_crate_that_shares_a/cuifk8p) that the `use _ as _` syntax is undocumeted, at least in the crates and module chapter of TRPL.

@steveklabnik, this seems like your territory :)

**Comment by cybergeek94** [comment]
Also the `extern "crate" as my_crate;` syntax.

**Comment by daboross** [comment]
I think `extern crate "crate" as my_crate;` is now `extern crate cratename as my_crate` without quotes. `"crate"` hasn't worked since the addition of turning `-` into `_` in crate names.

**Comment by durka** [comment]
I think this can be closed.
