### ISSUE TITLE
`use` of unstable function is not gated in import list

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#28075]
This compiles on stable:

`use std::thread::{catch_panic};`

but this does not:

```
use std::thread::catch_panic;
error: use of unstable library feature 'catch_panic': recent API addition
```

Fortunately, I can't find a way to actually use the import anyway, but it's a stability trap.

**Comment by brson** [comment]
Let's fix soon!

**Comment by brson** [comment]
This should be a matter of fixing the appropriate case in `stability.rs` and adding a test.

**Comment by apasel422** [comment]
This actually applies to all stability attributes and unused feature checks, and it looks like this is a result of `ViewPathList` being visited as a series of calls to `visit_ident` followed by a call to `walk_path` with only the path prefix. For example, when `use`-ing the deprecated `std::iter::order` this way:

foo.rs:
```rust
#![feature(iter_order)]
use std::iter::{order};
fn main() {}
```
Output:
```
foo.rs:1:12: 1:22 warning: unused or unknown feature, #[warn(unused_features)] on by default
foo.rs:1 #![feature(iter_order)]
                    ^~~~~~~~~~
foo.rs:3:17: 3:22 warning: unused import, #[warn(unused_imports)] on by default
foo.rs:3 use std::iter::{order};
```

**Comment by apasel422** [comment]
Compare that with:
```rust
#![feature(iter_order)]
use std::iter::order;
fn main() {}
```
Output:
```
foo.rs:2:5: 2:21 warning: unused import, #[warn(unused_imports)] on by default
foo.rs:2 use std::iter::order;
             ^~~~~~~~~~~~~~~~
foo.rs:2:5: 2:21 warning: use of deprecated item: use the equivalent methods on `Iterator` instead, #[warn(deprecated)] on by default
foo.rs:2 use std::iter::order;
             ^~~~~~~~~~~~~~~~
```

**Comment by terrynsun** [comment]
I'd like to try looking at this, if that's okay. Do you have any quick pointers for someone new to rustc?

**Comment by apasel422** [comment]
@terrynsun Go for it!

**Comment by brson** [comment]
@terrynsun How's this going?

**Comment by terrynsun** [comment]
Sorry! I was struggling with the structure of the AST walking and couldn't figure it out.

**Comment by alexcrichton** [comment]
triage: P-high
