### ISSUE TITLE
Read::bytes() and Read::chars() iterators should ignore Interrupted errors

### ISSUE THREAD

**Issue by eefriedman** [rust-lang/rust#28074]
https://github.com/rust-lang/rust/blob/fd302a95e1197e5f8401ecaa15f2cb0f81c830c3/src/libstd/io/mod.rs#L1549 etc.; `Interrupted` errors should be ignored here for the same reason they are ignored with `BufRead::lines()`.

**Comment by steveklabnik** [comment]
I _believe_ this is fixed. [This](https://github.com/rust-lang/rust/blob/691eba1358fc3c9c7a8033314a4112d43680c128/src/libstd/io/mod.rs#L1627-L1634) now calls [this](https://github.com/rust-lang/rust/blob/691eba1358fc3c9c7a8033314a4112d43680c128/src/libstd/io/mod.rs#L1603-L1613)

     Err(ref e) if e.kind() == ErrorKind::Interrupted => continue,

**Comment by Mark-Simulacrum** [comment]
Closing as fixed, we properly handle interrupted in this case today.
