### ISSUE TITLE
no_debug and omit_gdb_pretty_printer_sections attributes exist and are ungated

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#28091]
This compiles without a peep from the compiler:

```rust
#[no_debug]
#[omit_gdb_pretty_printer_section]
fn main() {}
```

The later especially seems to be purely designed for the rust testsuite, so should probably be feature gated.

(Nominating for more discussion and some sort of priority: if the decision is made to feature gate them,fixing this should just involve changing a few lines of `src/libsyntax/feature_gate.rs` and then adding the appropriate `feature(...)`s to the tests that use them.)

**Comment by christopherdumas** [comment]
Should someone implement this?

**Comment by nikomatsakis** [comment]
These should both be feature-gated.

**Comment by nikomatsakis** [comment]
triage: P-medium

**Comment by nikomatsakis** [comment]
Tagging with E-mentor -- I'm happy to mentor this. (nmatsakis on IRC)
