### ISSUE TITLE
Report same/similar errors only once

### ISSUE THREAD

**Issue by tyoc213** [rust-lang/rust#28098]
It seems that https://github.com/rust-lang/rust/issues/20692 is not only a case for duplicate error messages as shown by

```rust
fn main() {
    let array = [1, 2, 3];
    for a in array {
        println!( "{}", a);
    }
}
```

Which print the error 3 times.

It is the same as the other case about map https://github.com/rust-lang/rust/blob/7ae4a8e9f3150f62964151ef54b3da3cd24ee123/src/librustc/middle/traits/object_safety.rs#L78-L85

originally spot at https://users.rust-lang.org/t/iterator-and-differences-between-array-and-array/2672

----------

I think implementing ```distinct```so that you can collect only the different items could be a good way to start solving this in the board way (all across scala error reporting).

**Comment by eddyb** [comment]
Minimal examples:
```rust
fn main() {
    Iterator::next(&mut false); // 2 errors
    for _ in false {} // 3 errors
}
```
