### ISSUE TITLE
Validate usage of inline attributes

### ISSUE THREAD

**Issue by catamorphism** [rust-lang/rust#2809]
```syntax::attr::find_inline_attr``` has a FIXME saying "validate the usage of ```#[inline]``` and ```#[inline(always)]```".

**Comment by nagisa** [comment]
#22490 validates well-formedness of the inline attribute, but it is still unknown whether there’s any ways to misuse #[inline] attribute in a way which would be invalid (e.g. not on a function).

If the comment in original report happens to have referred to validation of attribute well-formedness, this issue can then be closed. Do not forget to remove the FIXME comment too.
