### ISSUE TITLE
Private `Recover` trait is visible in `BTreeMap` docs

### ISSUE THREAD

**Issue by apasel422** [rust-lang/rust#28093]
It shows up on https://doc.rust-lang.org/nightly/std/collections/struct.BTreeMap.html and https://doc.rust-lang.org/nightly/std/collections/btree_map/struct.BTreeMap.html, but not on https://doc.rust-lang.org/nightly/collections/struct.BTreeMap.html or https://doc.rust-lang.org/nightly/collections/btree_map/struct.BTreeMap.html.

**Comment by alexcrichton** [comment]
This is actually a known bug in rustdoc and/or the compiler, although I can't seem to find the issue right now... Basically it'll suffice to just tag the trait with `#[doc(hidden)]` for now.
