### ISSUE TITLE
Bad span assigned to continue keyword

### ISSUE THREAD

**Issue by marcusklaas** [rust-lang/rust#28105]
The break expression span contains its keyword, but the one for continue does not: http://is.gd/phbWGX

cc https://github.com/nrc/rustfmt/issues/184

**Comment by nagisa** [comment]
I’d say its the break span that’s more wrong here. The error message is about the label after all.

**Comment by marcusklaas** [comment]
I only used the labels to generate an error message which shows the span. Even without labels, the span is incorrect.

I could agree that the highlighted part in the error message could be only the label, but that's an other issue in my mind.

**Comment by nagisa** [comment]
Oh indeed.
