### ISSUE TITLE
Update Rustonomicon to mention contravariance

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#28100]
[Claiming that rust does not use contravariance in its type system](https://doc.rust-lang.org/nightly/nomicon/subtyping.html#variance) seems to be an error.

The Rustonomicon should be updated. I've already been confused enough since I took the "it does not exist" as a fact.

Quoting irc:
> `< eddyb> playbot: fn foo<'a, T: 'static>(x: &'a fn(&'a T), ptr: &mut &'a fn(&'static T)) { *ptr = x; }`
>  `-playbot:#rust- ()`
>  `< eddyb> if that's not contravariance, I don't know what is`

**Comment by bluss** [comment]
Maybe the core team decided to reserve contravariance for the higher and more expensive Rusty Titan levels.

**Comment by Gankro** [comment]
@bluss this is something that's in the pipeline to be removed, but @nikomatsakis has taken longer than expected to post an RFC for -- contravariance is currently unsound.

**Comment by aturon** [comment]
I think it's fine to do a quick update to the text to say that while Rust currently has contravariance, this is expected to be removed in the near future.
