### ISSUE TITLE
deriving cleanup

### ISSUE THREAD

**Issue by catamorphism** [rust-lang/rust#2810]
* Hygiene
* Search for "__" strings
* Don't assume ```std``` is the standard library

(from a FIXME in ```syntax::ext::deriving```)

**Comment by alexcrichton** [comment]
triage: P-low

I believe most cleanup here has been done and the leftover `__` are either implementation details or either aspects of hygiene which haven't been implemented yet, so I no longer think this is a backwards-compatibility problem for libraries.

**Comment by durka** [comment]
So I went through and looked at the `__` strings throughout src/libsyntax_ext/deriving.

They fall into several categories:

1. function arguments (functions like `PartialEq::eq`, `PartialCmp::partial_cmp`, etc)
2. local bindings, either variables or match pattern captures
3. type parameters (`__H` for `#[derive(Hash)]`, `__S` for `#[derive(RustcEncodable)]`, `__D` for `#[derive(RustcDecodable)]`)

I believe we can remove the `__` from 1 and 2. There is no user code in these functions except for struct and field names, and shadowing those doesn't seem to break things: http://is.gd/nng9Lm

For the type parameters unfortunately there is a risk of collision: http://is.gd/5EC2iM
However, it seems to me we could be doing better here: we could actually scan the list of type parameters and make a new one that can't collide.

Thoughts?
