### ISSUE TITLE
continue and break keyword related errors invalidly include the next token into span

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#28108]
Once https://github.com/rust-lang/rust/issues/28105 is fixed, there’s still an issue of both `continue` and `break` keyword spans including a token after the keyword into a span.

e.g. for 

```rust
fn main() { break }
```

span includes the closing brakcet

```
<anon>:1 fn main() { break }
                     ^~~~~~~
```

**Comment by marcusklaas** [comment]
I've got a fix for this!
