### ISSUE TITLE
Should we default to jemalloc on OpenBSD, FireflyBSD and Bitrig?

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#28112]
Supported since [jemalloc 4.0](https://github.com/jemalloc/jemalloc/releases/tag/4.0.0)

**Comment by steveklabnik** [comment]
Triage: I am not sure if this is still relevant, but these kinds of questions are best served on internals; I'd argue, as they tend to get lost in the bug tracker, as we can see 😄 

I'm going to give this a close.
