### ISSUE TITLE
Windows TLS destructors don't run in a statically linked binary

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#28111]
On `-msvc` TLS destructors do not appear to be run at all.

On `-gnu` TLS destructors appear to run when a non-main thread exits (as expected) or `std::process:exit` is called (es expected), but not run when main thread is terminated normally (by returning from `fn main`; not expected).

Various variations of [this](https://gist.github.com/retep998/e68e4dc7313d241ce0ff)/[this](https://gist.github.com/4ff9c2044ef501b833e8) program has been used for testing.

cc @retep998 who did the testing

**Comment by nagisa** [comment]
> // The linker must not discard p_thread_callback_base.  (We force a reference to this variable with a linker /INCLUDE:symbol pragma to ensure that.) If this variable is discarded, the OnThreadExit function will never be called.

and

> //.CRT section is merged with .rdata on x64 so it must be constant data.
#pragma const_seg(".CRT$XLB")
// When defining a const variable, it must have external linkage to be sure the linker doesn't discard it.

are comments from the [chromium’s TLS impl](https://src.chromium.org/svn/trunk/src/base/threading/thread_local_storage_win.cc) pointing towards something that might be missing from our implementation: we do not make sure data is constant on x64 and we do not make sure our symbol is `\INCLUDE`d.

**Comment by alexcrichton** [comment]
The bug here for threads in general specifically has to do with linkage, and I'm about to fix that in #28130, and for the main thread I've opened #28129 as it's not specific to Windows unfortunately.

For now I'm gonna recategorize this as "TLS destructors don't run in a statically linked binary on Windows"
