### ISSUE TITLE
Multi-span reporting feature

### ISSUE THREAD

**Issue by llogiq** [rust-lang/rust#28124]
For some lints, the user experience would be greatly enhanced if we could report a span with multiple highlights. E.g. in a unicode lint, we currently report every matching unicode sequence within a string, which can be *very* verbose. 

To reduce the clutter, it would be great if we could somehow advise `rustc` to report the string once, but highlight a given list of spans within the string. For example, this could look like:

    uni.rs:5:20: "This string contàìns multìple non nfc sequenc̀es."
                                  ^^       ^                  ^

Similarly, this feature could be used with a good number of other error message to get more compact, readable output.

**Comment by Manishearth** [comment]
This would be useful internally for unused imports as well.

**Comment by sanxiyn** [comment]
See #16132 for this applied to unused imports.
