### ISSUE TITLE
simplify CFG_FILENAME_EXTRA

### ISSUE THREAD

**Issue by infinity0** [rust-lang/rust#28120]
I'm wondering what is the rationale behind the hash values appended to the shared objects generated by `rustc` (and `cargo` too apparently, but filing only here for now.) At first I thought the hash was of some file contents, to ensure that unstable stuff doesn't get linked to. but that's not the case. The hash is only of the version string, and contains no extra information:

```
mk/main.mk:CFG_FILENAME_EXTRA=$(shell printf '%s' $(CFG_RELEASE) | $(CFG_HASH_COMMAND))}
```

I'm wondering if we can change it simply to `CFG_FILENAME_EXTRA = $(CFG_RELEASE)` instead? It seems reasonable to me, since it is only filename changes. It would make it more human-readable too, and open up the possibility of comparing the values to figure out which is newer.

**Comment by alexcrichton** [comment]
The primary purpose of these strings is to not take up names like `/usr/lib/libstd.so` in a normal installation (that's a bit privileged). Cargo also does this so you can have two crates called "foo"  from either different sources or with different versions.

I feel that `libstd-1.0.0.so` is still a bit more privileged than it needs to be and there's also some form of versioning on Linux anyway, so it may be odd to put versions elsewhere in the filename.

**Comment by alexcrichton** [comment]
Make's gone now, so closing.
