### ISSUE TITLE
HIR: tracking issue for HIR-related things.

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#28139]
Initial landing: #28138

**Comment by nrc** [comment]
#28140 move desugaring to lowering step
#28141 unify literals and attributes
#28142 delete the AST after lowering
#28143 cache lowering info
#28144 remove ids from the AST
#28145 separate AST and HIR lints

**Comment by eddyb** [comment]
cc @rust-lang/compiler

**Comment by Manishearth** [comment]
We may also want to reexport `Ident` and `NodeId` through HIR

**Comment by eddyb** [comment]
@Manishearth `Ident` has the overhead of hygiene information, maybe we could use only `Name` in the HIR (or some sort of general interned string index `Symbol` - that's just a naming concern though).

And `NodeId` will probably be split into per-node-type IDs.

**Comment by Manishearth** [comment]
Yeah, that works. Also we need to reexport `Name`, forgot about that one.

**Comment by steveklabnik** [comment]
Triage: this is a metabug. I updated some of @nrc's checkboxes from above.

**Comment by nikomatsakis** [comment]
I think we can close this bug, the transition to HIR is effectively complete.
