### ISSUE TITLE
HIR: cache lowering info

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#28143]
Lowering is O(n) in the number of nodes reached, so could take a while if it happens often (it doesn't at the moment, but could in the future). It might make sense to cache the lowering step, so we can cheaply go from AST to HIR. This is probably most important for tools, rather than the compiler itself.

**Comment by steveklabnik** [comment]
Triage: no idea.

**Comment by nikomatsakis** [comment]
I sort of think we should close this. It's kind of a complex question and I don't think having this bug is helpful really. Feel free to re-open.
