### ISSUE TITLE
HIR: remove ids from the AST

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#28144]
I think only the HIR needs ids.

**Comment by nrc** [comment]
Note that this is not as simple as just removing the fields and assigning ids to the HIR, rather than the AST - we currently use ids from the AST for identifying AST nodes in save-analysis.

**Comment by steveklabnik** [comment]
Triage: no idea.

**Comment by nikomatsakis** [comment]
I sort of think we should close this. It's kind of a complex question and I don't think having this bug is helpful really.
