### ISSUE TITLE
bad span: generics ending with `>>`

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#28158]
```
#[derive(Copy, Clone)]
pub struct StdCounter<T: Zero + Add<T, Output = T> + Sub<T, Output = T>> {
    pub value: T
}
```

Apparently, inserting a space between the `>>` fixes the issue.

**Comment by fhahn** [comment]
I tried to reproduce the issue, but it seems fixed. The complete code I used to test this is:

    #![feature(zero_one)]
    use std::ops::{Deref, Sub, Add};
    use std::num::Zero;
    
    fn homura<T: Deref<Target=i32>>(_: T) { }
    
    #[derive(Copy, Clone)]
    pub struct StdCounter<T: Zero + Add<T, Output = T> + Sub<T, Output = T>> {
        pub value: T
    }
    
    fn main() {}

**Comment by nrc** [comment]
This was fixed by https://github.com/rust-lang/rust/pull/28291
