### ISSUE TITLE
Settle execution order uncertainty for `+=`

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#28160]
When translating something like `a += b` to MIR, an uncertainty arose about what the semantics of

```
a = 0;
a += { a = 22; 2 }
```

ought to be. Should resulting value of `a` be `24` or `2`, basically? The current MIR yields 24, on the basis that this is more-or-less what will happen in the case of overloading as well (presuming non-lexical lifetimes, since I think otherwise you get a borrowck error).

**Comment by eefriedman** [comment]
See also #27868.

**Comment by llogiq** [comment]
I think this is a degenerate case, and should be at least linted against.

**Comment by petrochenkov** [comment]
I'm surprised this is allowed by the borrow checker (regardless of non-lexical lifetimes).
In my intuition `a` is clearly firstly mutably borrowed here (and released when the whole `A += B` is evaluated)
```
a += { a = 22; 2 }
^
```

, but then modified here
```
a += { a = 22; 2 }
         ^
```
despite being borrowed.

**Comment by llogiq** [comment]
@petrochenkov `a` could be `Copy`.

**Comment by petrochenkov** [comment]
@llogiq 
And? You still can't modify borrowed `Copy` data.

**Comment by llogiq** [comment]
No. There is no borrow. `a` is taken by value (and copied, because it is `Copy`).

**Comment by petrochenkov** [comment]
@llogiq 
`+=` is interested in the location of `a`, not only in its value, it has to borrow it.

I mean, the effective signature of `+=` is `fn(&mut Lhs, Rhs);` (the same as in https://github.com/rust-lang/rfcs/pull/953) and this snipped doesn't pass borrow checker after being rewritten with a function.
http://is.gd/itvea6
IMO, built-in `+=` should behave in the same prohibitive way as its overloaded equivalent with regards to borrow checker instead of allowing snippets with weird semantics, like the original example.

**Comment by llogiq** [comment]
Ah, I see. You're right, `a` *must* be borrowed, because else the mutation couldn't have been observed in the containing code.

**Comment by tomaka** [comment]
The following code prints `488447264` on the playpen: (http://is.gd/k4cPWw)

```rust
fn main() {
    let mut a;
    a += { a = 2; 3 };
    println!("{:?}", a);
}
```

**Comment by llogiq** [comment]
Does it add the address of &a to the value?

**Comment by petrochenkov** [comment]
The following code sends `a` to the Moon!
```
fn main() -> () {
    let mut a = 0;
    a += {
        let aptr = &mut a;
        thread::scoped(|| {
            loop {
                *aptr = 10;
            }
        });
        11
    };
    a = 12;
    println!("{}", a);
}
```

**Comment by Stebalien** [comment]
@llogiq no. 3 is getting added to uninitialized memory. It's a repeating byte (0x1d) followed by a 0x1d + 3 byte. http://is.gd/Q0Hhr3

**Comment by nagisa** [comment]
IMO `+=` should be simply a sugar for

```rust
AddAssign::add_assign(&mut self, rhs);
```

where AddAssign is some trait [added in the future](https://github.com/rust-lang/rfcs/issues/393) to overload `+=`.

```rust
a = 0;
AddAssign::add_assign(&mut a, &{ a = 22; 2 });
```

**Comment by eddyb** [comment]
@nagisa Yes and no. Yes, that is a valid desugaring, but no, the borrow doesn't happen before `rhs` is evaluated.
In fact, it's a current limitation that borrows are evaluated like that.
There's no memory unsafety here (as long as `a` is not moved, it will have the same address), since the mutable borrow is only used by the mutable call, not by any other expressions in the call.

However, there's an evaluation bug here: the LHS *must not* be read before evaluating the RHS, but the current implementation disobeys that rule and can cause UB AFAICT.

**Comment by arielb1** [comment]
Currently borrowck evaluates `+=` right-to-left while trans evaluates it left-to-right.

```Rust
fn main() {
    let a = Box::new(2);
    let mut b = 2;
    *{ *a; &mut b } //~ ERROR use of moved value
        +=
    { drop(a); 1 };
}
```

`=`-assignment is both evaluated and borrow-checked right-to-left (trans erroneously tries to elide the copy of the RHS, but that is a different issue).

Unfortunately, evaluating `=` left-to-right would break code like
```Rust
    let x: &mut [u8] = calculate();
    x[i] = x[j];
```
As it would translate into
```
    %temp : &mut [u8] = call calculate, onerr exit
    x = %temp
    %boundck_1 : bool = i >= x.len
    bt %boundck_1, panic_boundck_1
    %lhs : &mut u8 = &mut x[i]
    %boundck_2: bool = j >= x.len
    bt %boundck_2, panic_boundck_2
    %rhs : u8 = x[j]
    *%lhs = %rhs
    ret
exit:
    unwind
```

Here the borrow of `x[i]` conflicts with the read of `x[j]`. Note that we need some kind of borrow to at least prevent `x`'s length from changing after the bound-check (it does not need to be mutable, but there are more complicated examples where the RHS can change `x[j]`).

One way to fix this (suggested by @eddyb) is to move the lvalue evaluation (including the bounds check) to after the RHS computation, which relies on lvalue evaluations not being able to invalidate borrows.

We also thought of potentially packing coercions into the lvalue evaluation. This could also make code like `v.push(v.len())` work. Unfortunately, it doesn't work well with UFCS. We may want to add an autoref expression for that and/or move addr-ofs too.

**Comment by petrochenkov** [comment]
>Note that we need some kind of borrow to at least prevent x's length from changing after the bound-check

Heh.
```
fn report(a: &Vec<i32>) {
    println!("{:?} {:?} {:?} {:?}", a.len(), a.capacity(), a[0], &a[0] as *const _);
}

fn main() -> () {
    let mut a = vec![0];
    report(&a);
    let xxx = &a[0] as *const _;
    println!("{:?} {:?}", xxx, unsafe { *xxx });
    a[0] += {
        report(&a);
        a.push(1);
        report(&a);
        a.push(2);
        report(&a);
        3
    };
    report(&a);
    println!("{:?} {:?}", xxx, unsafe { *xxx });
}

1 1 0 0x7f4386024008
0x7f4386024008 0
1 1 0 0x7f4386024008
2 2 0 0x7f4386024008
3 4 0 0x7f4386023000
3 4 0 0x7f4386023000
0x7f4386024008 3
```

**Comment by eddyb** [comment]
Since several people voiced their disagreement on the need for supporting assignment in the RHS, as a counterexample I have [this piece of code](https://github.com/eddyb/r3/blob/9e1d129bc4e4dc9bbd5af50bb0039dea8edd9387/src/bin/rid3.rs#L75) written this week (coincidentally) which was miscompiled (`|=` and any other `OP=` operators have the same issue as `+=`).

The relevant bit:
```rust
            dirty |= match event {
                E::KeyboardInput(ElementState::Pressed, _, Some(key)) => {
                    dirty |= root.dispatch(&ui::event::KeyDown(key));
                    for e in key_tracker.down(key) {
                        dirty |= root.dispatch(&e);
                    }
                    false
                }
                ...
            };
```

And the workaround looks like this:
```rust
            dirty |= match event {
                E::KeyboardInput(ElementState::Pressed, _, Some(key)) => {
                    let mut dirty = root.dispatch(&ui::event::KeyDown(key));
                    for e in key_tracker.down(key) {
                        dirty |= root.dispatch(&e);
                    }
                    dirty
                }
                ...
            };
```

Is this an usecase we want to support or not?

If there is an easy way to trigger borrowck errors on such usecases (or warnings, but that seems less likely), can we get a crater run to estimate the prevalence of LHS reads/writes in the RHS of `LHS OP= RHS` expression, in the wild?

**Comment by eddyb** [comment]
@arielb1 You could argue that bounds-checked indexing is not "pure" and thus cannot avoid being borrowed, in some way, unlike other lvalues.

**Comment by eddyb** [comment]
On IRC I came up with this example which seems to make the smarter schemes fall apart:
```rust
let mut boxed = Box::new(vec![...]);
(*boxed).push({
    mem::replace(&mut boxed, Box::new(vec![])).len()
})
```
Do we need to differentiate between `GEP`-style lvalue computations (lvalue -> lvalue with only offsets) and lvalue computations that actually load data from memory?
The result of the former (such as struct/tuple field accesses) *should* be the same before and after any possible expression that may mutate the lvalues in question.

**Comment by arielb1** [comment]
@eddyb 

This is annoying because overloaded deref can be both.

**Comment by arielb1** [comment]
One proposal that mostly maintains LTR and handles `x[i] = x[j]`

## Definitions

An lvalue expression is basically the current rustc lvalue expression.

Unresolved Question: do we include overloaded index/deref in index/deref lvalues? this makes more code compile but could be confusing in some cases?

```
LVALUE_EXPR = 
       MUTABILITY RVALUE_EXPR           - temporary
       | LVALUE_EXPR . FIELD            - field access
       | LVALUE_EXPR [ RVALUE_EXPR ]    - indexing (including overloaded?)
       | *MUTABILITY RVALUE_EXPR        - deref
       | LOCAL                          - local variable
```

Evaluating an expression "to an lvalue" is just evaluating all the rvalue-expressions in it. Note that after an expression is evaluated to an lvalue, finalizing its evaluation can still read memory and possibly run user code (if we allow overloaded derefs/indexing).

Evaluating an expression "to an rvalue" is just standard evaluation.

To evaluate an expression with a receiver, that's it "LHS = RHS", "LHS OP= RHS", "LHS.foo(ARG1, ARG2)", first the pre-final-autoref receiver is evaluated to an lvalue, then the other operands are evaluated to rvalues, then the receiver evaluation is finalized and autoref-ed if needed.

## Examples

```Rust
x[I] = x[J];
// equiv
let i = I;
let rhs = x[J];
x[I] = x[J]
```

```Rust
a.b.f(a.b.g(), a.b.h())
// equiv
let arg0 = a.b.g();
let arg1 = a.b.h();
a.b.f(arg0, arg1); // potentially with overloaded autoderef
```

```Rust
(*boxed).push({
    mem::replace(&mut boxed, Box::new(vec![])).len()
})
// equiv
let arg0 = mem::replace(&mut boxed, Box::new(vec![])).len();
(*boxed).push(arg0);
```

```Rust
a.b().c().d()
// equiv
let t0 = a.b(); // this is an rvalue
let t1 = t0.c();
let t2 = t1.d();
```

**Comment by arielb1** [comment]
## Application

When should the "evaluate lvalue's rvalue components first, then lvalue" rule be applied? Only to method calls and assignment ops? Everywhere an lvalue is required? Does this include the pseudo-lvalue of `*`?

**Comment by llogiq** [comment]
@arielb1 I think the "Simple assignment" should read

```
x[I] = x[J];
// equiv
let i = I;
let rhs = x[J];
x[i] = rhs;
```

**Comment by arielb1** [comment]
@nikomatsakis (replying here because discourse refuses to work)

> My feeling is that we should keep the evaluation order LTR where possible, but overall it should be > relatively easy to predict. Thus complex orderings that "mostly" preserve LTR seems (to me) to be > overall less good than just saying "assignments are RTL".

I don't really have a problem with a "typically LTR, receiver and assignment RHS last" ordering, but @eddyb is rather surprised by it. However, it may just be that my rules just push the surprisingness into subtler cases.

> The interaction with overloaded operators is also an important question. It is not clear to me that self.balance -= x and self.balance = self.balance - x should always be equivalent. They are certainly distinct with overloaded operators, since one desugars into an &mut self operator (or at least that is the proposed desugaring). I think we should strive that the builtin operations can be modeled using overloaded versions, which would imply that self.balance -= foo() will "read" the current value of self.balance only after foo() is evaluated (unlike self.balance = self.balance - foo()). Subtle, but they you go. (I imagine that all languages which desugar -= specially can encounter a similar situation.)

You can't have the trivial desugaring anyway - `self.balance = self.balance - x` calls both `Deref` and `DerefMut` on `Self`. With my rules it (`self.balance -= x`) should behave the same as `self.balance.sub_by(x)`, except the adjustment rules are different (and aren't they different anyway?). C# does this naïvely IIRC.

**Comment by nikomatsakis** [comment]
@arielb1 I don't think changing the order of assignment for receiver is a
good idea. Is your goal here to overcome the "nested method call" borrowck
errors?

**Comment by arielb1** [comment]
@nikomatsakis 

I want to treat method receivers like assignment LHS-es to fix the "foo.push(foo[0])" problem.

**Comment by nikomatsakis** [comment]
triage: P-medium

**Comment by GBGamer** [comment]
I agree with @nagisa; we should just treat

```rust
let mut a = 0;
a += { a = 6; 2};
println("{}", a);
```

as `a.add_assign({a = 6; 2})`, and this snippet should print `8`;

**Comment by bstrie** [comment]
Given that commenters in here have demonstrated undefined behavior in here, I'm tagging this with I-soundness.

Personally I'd like to keep the rules as simple as possible even if it means a trivial amount of breakage (which is permissible from fixing soundness flaws). If the operators can be desugared to method calls as you'd expect everywhere else, that would be ideal.

**Comment by arielb1** [comment]
@bstrie 

This will not be unsound with the MIR, just cause more compile-time errors.

**Comment by bstrie** [comment]
@arielb1 , good the hear, but I'd prefer not to remove the label until we start trans-ing from MIR, which won't be for a while yet. :)

**Comment by shepmaster** [comment]
Now that MIR presumably has had to deal with this, what was the decision?

**Comment by nikomatsakis** [comment]
Actually this has not been formally decided. (I mean, we've always had the impl doing *something* in any case, and it still does -- but is it the right thing?) I'm pretty dubious about changing the order of execution just to allow for fewer errors though -- I think we should stick to left-to-right whenever possible (`a = b` seems to be a prominent exception, since there we evaluate `b` first and then `a`). I've been meaning for some time to try and write-up some thoughts on this matter and in particular on how we can extend borrowck to avoid some of the errors that we currently see from nested method calls and the like.

**Comment by eddyb** [comment]
@nikomatsakis Huh, I'm very surprised `*a() = b()` is evaluated RTL in MIR, although I've lost track of the conversations on the matter.
We had a discussion on IRC, related to @rjw245's [draft report](https://www.reddit.com/r/rust/comments/4qnj8b/comparing_concurrency_in_rust_and_c/) where they found that `*mutex.lock() = expensive_computation();` would keep the mutex locked for the whole duration of the RHS call - apparently it seems with MIR that is not the case?

Only overloaded augmented assignment [seems to have LTR ordering](https://play.rust-lang.org/?gist=b309f2bfc4e4c658f8050c6a07b6db7e&version=nightly&run=1) in MIR.

**Comment by eddyb** [comment]
@nikomatsakis If I'd have to give one reason for evaluating assignments LTR is that it enables RVO.
Otherwise there's a necessary copy if the functions can't be inlined or have *any* side-effects *at all*.

**Comment by ubsan** [comment]
@nikomatsakis I agree with @eddyb: LTR is better. It's how the rest of the language works, so it's less confusing.

Also, I'd like it if `a += b` was equivalent to `AddAssign::add_assign(&mut a, b)`. This means, probably, that `a += [expr]`, where `[expr]` includes `a`, would not be allowed. This is obviously not ideal...

**Comment by nikomatsakis** [comment]
See this internals thread: https://internals.rust-lang.org/t/settling-execution-order-for/4253

**Comment by cristicbz** [comment]
Putting all the examples into the playground now suggests soundness issues have been resolved. Maybe remove the label, since now it's just a matter of figuring out what the right execution order is?

https://is.gd/2xjOGo   (prints 5 rather than the uninitialised memory it did previously)
https://is.gd/02GpcD  (prints `3 4 3`, so I think it's fixed)
https://is.gd/JLN7M6  (doesn't compile now)

**Comment by nikomatsakis** [comment]
I'm not sure that we have much leeway to change this at this point anyhow. Maybe a little. =)

**Comment by nikomatsakis** [comment]
It could use someone to kind of draw together all the considerations and make a summary of current status, at minimum.

**Comment by Centril** [comment]
Triage, @nikomatsakis any updates?

**Comment by RalfJung** [comment]
@nikomatsakis @eddyb are there any updates on this?

**Comment by eddyb** [comment]
I thought this has been resolved forever ago, am surprised this is still open.

**Comment by nikomatsakis** [comment]
I'm going to just close the issue. We're not going to change the MIR we generate now in any major way. If in the process of looking at some of the issues around defining the semantics of MIR we make tweaks here, we can address those individually.

**Comment by RalfJung** [comment]
> If in the process of looking at some of the issues around defining the semantics of MIR we make tweaks here, we can address those individually.

Note that this here is not a question of MIR semantics but of surface Rust semantics -- so MIR semantics discussion seems entirely orthogonal to me.

**Comment by nikomatsakis** [comment]
Yes, I know. What I meant was: if we uncover some kind of problem with the current lowering in the course of that work, we might consider a specific proposal here, but it seems obvious that we don't want to be altering the observed semantics of running code at this juncture absent a very concrete proposal and strong motivation.
