### ISSUE TITLE
functional struct : no documentation

### ISSUE THREAD

**Issue by gbersac** [rust-lang/rust#28168]
Consider the following code :
```rust
struct MyStruct;

fn main() {
    let var = MyStruct {};
}
```
The following error message appear :
```
example.rs:4:24: 4:25 error: structure literal must either have at least one field or use functional structure update syntax
example.rs:4     let var = MyStruct {};
```
The problem is there is no way to understand what a functional struct is. I searched in the reference, asked on irc.

By the way, the error message is understandable but it would be better to have it propose a solution. 

My use case was that I wanted different way to calculate something. I created a trait and implement it for as many different structure as there is different way to calculate that thing. Some of that struct didn't need a field.

**Comment by christopherdumas** [comment]
Couldn't you use an enumeration for that? Maybe:

    enum MyAlgorithm {
        Foo(isize),
        Bar,
        Baz(isize, &str)
    }

**Comment by christopherdumas** [comment]
But yes, the reference to "functional structs" is strange.

**Comment by steveklabnik** [comment]
Yes, 'functional' should be removed. We call it "update syntax" now http://doc.rust-lang.org/stable/book/structs.html#update-syntax

**Comment by steveklabnik** [comment]
@christopherdumas it's `funcional (structure update syntax)` not `(functional structure) ( update syntax)`, if that makes any sense.

**Comment by arielb1** [comment]
@steveklabnik 

That parse error is silly. I would prefer to avoid resolve's "MyStruct does not name a structure". Maybe "unit-like structures are constructed without braces: `MyStruct`" would be better help.

**Comment by steveklabnik** [comment]
Oh yeah, this should absolutely be improved, I'm just trying to add context :)

**Comment by christopherdumas** [comment]
Does anyone know where in the rust codebase this error might be coming from?

**Comment by birkenfeld** [comment]
Can be closed; the syntax in question is now legal anyway.

**Comment by steveklabnik** [comment]
Yup!
