### ISSUE TITLE
milliseconds should be represented by u64, not u32 type

### ISSUE THREAD

**Issue by kirillkh** [rust-lang/rust#28171]
I found at least two cases in the standard API where milliseconds are represented by u32 variables:
`std::sync::Condvar::wait_timeout_ms()` and `std::thread::park_timeout_ms()`. However unlikely, it is not completely impossible for the user to expect being able to pass parameter value >= 2^32, as that value is less than 50 days. Also note that milliseconds are often passed on from another API that deals with u64 values, and so the user will likely convert the value unconditionally, without checking whether it's safe to do so.

**Comment by nagisa** [comment]
These functions are supposed to only be a compromise before we get stable `Duration` and `Duration`-taking functions, which is [happening soon](https://github.com/rust-lang/rust/issues/27771).

**Comment by alexcrichton** [comment]
Ah yeah these are just going to be deprecated in favor of the `Duration` taking functions (which was the long-term plan since inception), so I'm gonna close this in favor #27771.
