### ISSUE TITLE
Suggestion for chapter about bindings

### ISSUE THREAD

**Issue by gor77** [rust-lang/rust#28177]
Hi,

 I feel variable bindings need to be explained more. 

Working and learning alone, it took me quite some time to figure them out 
(hopefuly I got everything right). Things like:

1. Keyword let declares a new binding - sort of linkage between name and value. 
It has to be used ONLY when you want to introduce a new binding:
```rust
fn main() {
    x = 2; // this is an error
}
```

2. You can have two or more bindings with the same name. The one declared 
last will "win" (or shadow) over the previous one
```rust
fn main() {
    let x = 2;
    let x = 3; //no error here, from now on x is 3
}
```

3. Each new binding can have its mutability independently declared, 
even if it has the same name as one before
```rust
fn main() {
    
    let x = 2;
    let mut x = 3; // from now on, x has value 3 and it can be changed

}
```

These things are simply not stressed enough in the book (or not mentioned at all) and understanding these things is the basis for understanding something  like this:
```rust
let x = 2; // this is immutable binding and from now on we can't modify x
let mut x = x; // but when we create a new mutable binding with the same name
x = 3; //...then we can change x
```

**Comment by xiaochuanyu** [comment]
Just a note. Comparing to [Rust By Example section about bindings](http://rustbyexample.com/variable_bindings.html), shadowing and declaring uninitialized bindings have been left out.
