### ISSUE TITLE
Operator overloading issues

### ISSUE THREAD

**Issue by Robzz** [rust-lang/rust#28183]
I did a quick search on the bug tracker and didn't find a duplicate so I'll just drop this here : 

According to the docs, `HashSet` implements `Sub`, but apparently operator overloading fails in this case. Calling `Sub::sub` directly does work. This example also fails with `BTreeSet`. Tested on latest nightly. Here's an example that shows the problem : http://is.gd/hSUS2w

Maybe it's just me missing something obvious, but after some fighting with the compiler, I think this is a bug.

**Comment by sfackler** [comment]
`Sub` is implemented on `&HashSet` and takes another `&HashSet`: http://is.gd/AJ1Ii5

**Comment by Robzz** [comment]
Oh. I have no idea how the hell I could miss that. Thank you, and sorry. Closing.
