### ISSUE TITLE
why not derive(Debug) by default

### ISSUE THREAD

**Issue by ztq56** [rust-lang/rust#28185]
and use attribute #[nodebug] to specific others?

in the document, it says 

> Format trait for the :? format. Useful for debugging, all types should implement this.
> Generally speaking, you should just derive a Debug implementation.

but sometimes missing it, and I could only manually add it package by package.

**Comment by cybergeek94** [comment]
At this point it'd be too widespread of a breaking change to auto-derive `Debug` by default, because basically all crates would have to be updated.

This would work great as a note or warning lint, though. CC @Manishearth about the viability of this as an idea for clippy.

**Comment by Manishearth** [comment]
It's possible as a lint (if all children derive trait Foo, lint that you should too), but perhaps should be `Allow`. `derive` ing everything isn't always necessary.

**Comment by steveklabnik** [comment]
making a change like this, as @cybergeek94 mentions, would require an RFC. Please pursue one if you're interested in making this, but yeah, there are backwards compatibility challenges here.

**Comment by omega-tree** [comment]
Now that we have epochs, Please revisit this!
