### ISSUE TITLE
Reference paragraph mentions nonexistent example

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#28196]
https://doc.rust-lang.org/nightly/reference.html#match-expressions

> A pattern that's just an identifier, like **Nil** in the previous example, could either refer to an enum variant that's in scope, or bind a new variable. The compiler resolves this ambiguity by forbidding variable bindings that occur in match patterns from shadowing names of variants that are in scope. For example, wherever **List** is in scope, a match pattern would not be able to bind **Nil** as a new name.

Nil and List are not mentioned in the previous example

**Comment by christopherdumas** [comment]
Should we add an example, or remove the reference?

**Comment by frewsxcv** [comment]
I don't have an answer to that question, but it's worth mentioning that 'Nil' and 'List' are used in examples later in the Reference

**Comment by steveklabnik** [comment]
I would remove the reference.

**Comment by christopherdumas** [comment]
:arrow_up: I created a pull request doing as you suggest, @steveklabnik.

**Comment by frewsxcv** [comment]
Fixed in #28216

**Comment by frewsxcv** [comment]
Thanks @christopherdumas
