### ISSUE TITLE
Vec.append is a confusing method name

### ISSUE THREAD

**Issue by hartsantler** [rust-lang/rust#28223]
Coming from Python, as many others probably are, i find the method name `append` to be misleading.
From the rust docs:
http://doc.rust-lang.org/std/vec/struct.Vec.html#method.append

__Moves all the elements of other into Self, leaving other empty.__

This is similar to the `extend` method in Python, but still a little different because it moves the elements into self.  I think it makes much sense to call the method something like: `merge` or `move_from`

**Comment by alexcrichton** [comment]
We've actually already got a tracking issue for this method (https://github.com/rust-lang/rust/issues/27765), so I'm gonna move this comment over there.
