### ISSUE TITLE
Add the release dates to RELEASES.md

### ISSUE THREAD

**Issue by kud1ing** [rust-lang/rust#28228]
Pages like Wikipedia/Wikidata need to prove that a given information is correct.
The announcement blog posts seem to be the only obvious place to look up the the exact release dates. Blog post URLs are not necessarily stable over time. It would be simpler to just refer to RELEASES.md.

**Comment by steveklabnik** [comment]
They already contain the month, is the day that important?

**Comment by kud1ing** [comment]
> is the day that important?

That probably depends on the context. Most software on Wikidata has the complete date defined.
Does it hurt? I would add the days in a PR myself, just wanted to make sure there is no opposition.
I suggest we use ISO-format.
