### ISSUE TITLE
Rust panics if index out of bounds

### ISSUE THREAD

**Issue by christopherdumas** [rust-lang/rust#28230]
```rust
fn main () {
    let x = vec![1, 2, 3];
    println!("Got: {}", x[88]);
}
```
This code compiles just fine, but, when I run it, I get an ICE, or something similar:

```
thread '<main>' panicked at 'index out of bounds: the len is 3 but the index is 88', ../src/libcollections/vec.rs:1047
```
Note that this is the same problem as in #28217. Here are the lines it references:

```rust
#[stable(feature = "rust1", since = "1.0.0")]
impl<T> Index<usize> for Vec<T> {
    type Output = T;

    #[inline]
    fn index(&self, index: usize) -> &T {
        // NB built-in indexing via `&[T]`
        &(**self)[index]
    }
}
```

I'm not sure if this is intended behavior or not, but it seems odd.

**Comment by jdm** [comment]
This is intended behaviour - the `[x]` form of indexing panics, because it cannot return a reference to an element that doesn't exist. `.get(x)` returns an `Option<T>`, so it doesn't panic. The panicking behaviour is documented at https://doc.rust-lang.org/nightly/reference.html#index-expressions .

**Comment by shamiao** [comment]
recent url of index expressions document: 
(stable) https://doc.rust-lang.org/reference.html#index-expressions
(nightly) https://doc.rust-lang.org/nightly/reference/expressions.html#index-expressions
