### ISSUE TITLE
Introduction to Rust codebase

### ISSUE THREAD

**Issue by christopherdumas** [rust-lang/rust#28245]
I want to contribute to Rust, but it is very hard to gain specific knowledge of the Rust codebase and how it works on my own. It is doable, by reading the source code and jumping-to-definition in Emacs, but is there any documentation generated for the source code, or something to that effect?

**Comment by jonas-schievink** [comment]
There is http://manishearth.github.io/rust-internals-docs/std/index.html which contains docs for the internal crates

**Comment by christopherdumas** [comment]
Awesome! Thanks a ton! :+1: :smile:

**Comment by christopherdumas** [comment]
@jonas-schievink Those docs are invaluable!

**Comment by steveklabnik** [comment]
I'm gonna give this a close, then.
