### ISSUE TITLE
Open tracking issues for all language features

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#28244]
https://github.com/rust-lang/rust/issues/26868 but for lang features.

The issues for each thing should be recorded in the corresponding place in `libsyntax/feature_gate.rs`, and when they've all been opened & recorded, the FIXME's relating to this issue in that file should be removed.

**Comment by huonw** [comment]
triage: I-nominated.

This has been very helpful for library features: promoting discussion, and allows people to track progress, so it'd be great to utilize properly for language ones too.

**Comment by nikomatsakis** [comment]
triage: P-medium
