### ISSUE TITLE
rustdoc fails to treat pipe character inside code blocks properly

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#28251]
Both of these examples should look like the original when rendered as a table in rustdoc but neither do.

This:
```
//! Test  | Table
//! ------|-------------
//! t = b | `x | y | z`
```

Results in:
```
//! Test  | Table
//! ------|-------------
//! t = b | `x
```

This:

```
//! Test  | Table
//! ------|-------------
//! t = b | `x \| y \| z`
```

Results in:

```
//! Test  | Table
//! ------|-------------
//! t = b | `x \
```

This was supposed to be fixed when rust updated hoedown to 3.0.4 (https://github.com/rust-lang/rust/pull/27945) but it doesn't seem to work inside code blocks. https://github.com/hoedown/hoedown/issues/77 seems to have covered those cases so I'm not sure where the problem lies.

**Comment by Eljay** [comment]
This seems to be a bug with hoedown itself, I get the same output without using rustdoc:

```bash
$ cat test.md
Test  | Table
------|-------------
t = b | `x \| y \| z`

$ ./hoedown --tables test.md
<table>
<thead>
<tr>
<th>Test</th>
<th>Table</th>
</tr>
</thead>

<tbody>
<tr>
<td>t = b</td>
<td>`x \</td>
</tr>
</tbody>
</table>
```

**Comment by mdinger** [comment]
Reportedly fixed in 3.0.5 which was just released. See https://github.com/hoedown/hoedown/issues/169 . @Eljay can you confirm the fix works? I haven't setup hoedown.

**Comment by Eljay** [comment]
That was fast, seems to be fixed:

```bash
$ ./hoedown -v
Built with Hoedown 3.0.5.
$ ./hoedown --tables test.md
<table>
<thead>
<tr>
<th>Test</th>
<th>Table</th>
</tr>
</thead>

<tbody>
<tr>
<td>t = b</td>
<td><code>x \| y \| z</code></td>
</tr>
</tbody>
</table>
```

@alexcrichton Before I submit a PR for this, is there any reason for the rust-lang/hoedown fork now or can I just point the submodule directly at hoedown?

**Comment by mdinger** [comment]
@alexcrichton ^^

**Comment by alexcrichton** [comment]
Ah sorry, missed this! We currently just conventionally have a fork for all repos. It's partly motivated by just making sure the repo doesn't disappear (e.g. you can build historical versions of Rust), but it's not the strongest reason, it's done mostly today because we just did it yesterday!

**Comment by Eljay** [comment]
Completely forgot about this as well, PR submitted.

**Comment by mdinger** [comment]
Cool. How did 2 commits between 3.0.4 and 3.0.5 balloon into 85 commits to Rust with 3000 lines of code change? That surprised me. Did the 3.0.4 not update properly?

**Comment by alexcrichton** [comment]
Ah the PR was sent against the master branch, not the last branch we had of hoedown, hence the large number of changes.

**Comment by mdinger** [comment]
@alexcrichton Ah, I see. Thanks!
