### ISSUE TITLE
segfault while compiling stage2 libsyntax for i686-pc-windows-gnu

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust#28260]
@alexcrichton has indicated this may be related to using newer versions of gcc, which might explain why it doesn't fail on the buildbot machines.

The segfault occurs while running the `tailcallelim` llvm pass on `ast::Pat_::drop()`, possibly during the prerequisite `tti` analysis.

Turning on any kind of debug information for either rust or llvm causes the problem to disappear.

**Comment by Diggsey** [comment]
I've reported this as an LLVM bug: https://llvm.org/bugs/show_bug.cgi?id=24722

**Comment by alexcrichton** [comment]
Closing as a duplicate of https://github.com/rust-lang/rust/issues/28962

**Comment by alexcrichton** [comment]
Er actually this has a smaller number, gonna go in favor of this.

**Comment by alexcrichton** [comment]
Also so this shows up in github search:

gcc 5.2 fails to build LLVM successfully on MinGW as it segfaults at runtime

**Comment by tkelman** [comment]
This should be fixed in GCC 6, I believe - https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66655

**Comment by taralx** [comment]
I have indications that GCC 5.3 also works, but I didn't have time to fully test. If someone has a windows box and wants to try it... :)

**Comment by petrochenkov** [comment]
@taralx 
5.3 doesn't work, but this segfault happens only when LLVM assertions are enabled, maybe you tested without them?

**Comment by taralx** [comment]
I did indeed test without them. Thanks for the heads up.

**Comment by alexcrichton** [comment]
Testing today, it appears that master branch builds fine with gcc 5.4.0. I suspect we fixed this "by accident" when we updated LLVM at some point
