### ISSUE TITLE
Improve Error Handling chapter

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#28298]
A long while back, @BurntSushi  wrote http://blog.burntsushi.net/rust-error-handling/ . It is awesome, and deserves to be in the book in some form. Last we talked, @BurntSushi was okay with us using it from a licensing perspective.

**Comment by christopherdumas** [comment]
It looks to me like adding it to the book would require a major rewrite of it (The blog post) because it is written in a different style from the book (author talks about "I").

**Comment by BurntSushi** [comment]
Yes! How should we do this? The article is in markdown here: https://github.com/BurntSushi/blog/blob/master/content/post/rust-error-handling.md (Well, mostly markdown. There are a few custom constructs for my questionable attempt at making sure all code compiles.) They should be easy to lift out. Should I do that and submit an initial PR? Should it be a guide? (There is already `guide-error-handling.md`.)

**Comment by christopherdumas** [comment]
Maybe we could replace the error handling guide with @BurntSushi's article?

**Comment by christopherdumas** [comment]
It is a really awesome article. It would definitely be worth it to adapt it for the Rust book.

**Comment by steveklabnik** [comment]
Yes, that'd be the intention, basically, to replace the existing guide.

I wouldn't be opposed to "import wholesale, change from I to we", frankly. Can't say more, but I don't think extra editing is important at first. (should be able to say soon)

**Comment by christopherdumas** [comment]
Regex to the rscue!

**Comment by christopherdumas** [comment]
I'd be willing to do this.

**Comment by BurntSushi** [comment]
OK, I'm working on the initial PR now.

**Comment by christopherdumas** [comment]
Oh. I just finished doing it.

**Comment by christopherdumas** [comment]
I put the pull request up at #28301.

**Comment by steveklabnik** [comment]
This was fixed with the merging of https://github.com/rust-lang/rust/pull/28301
