### ISSUE TITLE
Nightly documentation's std::vec's source link does not work

### ISSUE THREAD

**Issue by e00E** [rust-lang/rust#28302]
The `source` link on the `vec` page https://doc.rust-lang.org/nightly/std/vec/index.html leads to https://doc.rust-lang.org/nightly/core_collections/vec/?gotosrc=24157 which is just a `Not Found` page. I randomly clicked source on other pages and they seem to work.

**Comment by nfallen** [comment]
I will fix this!

**Comment by nfallen** [comment]
The link is going to core_collections/vec when it should just be going to collections/vec. I can't push a change to the index.html file because it is in the gitignore so I'm assuming the link is generated somewhere else. I'm new to the repo, so does anyone else know where the link is generated?

**Comment by Gankro** [comment]
@nfallen yes all of these pages are generated [from the code source](https://github.com/rust-lang/rust/blob/master/src/libcollections/vec.rs)

This is a bug in rustdoc, which generates these links: https://github.com/rust-lang/rust/tree/master/src/librustdoc

I'm not sure if there's a specific issue for this, but [rustdoc has a lot of bugs, and needs a lot of love](https://github.com/rust-lang/rust/labels/A-rustdoc)

**Comment by nfallen** [comment]
thank you @Gankro I will look into the rustdoc bug

**Comment by Gankro** [comment]
@alexcrichton probably knows the most about our current design

**Comment by mitaa** [comment]
Seems fixed?

@nfallen 
> The link is going to core_collections/vec when it should just be going to collections/vec

Judging from that this seems to have been the same problem as #30109 and #30198

**Comment by steveklabnik** [comment]
This is in fact fixed!
