### ISSUE TITLE
Documentation search finds std::rand::Rng::shuffle but does not find corresponding page

### ISSUE THREAD

**Issue by e00E** [rust-lang/rust#28303]
I search for `shuffle` in the documentation like so https://doc.rust-lang.org/stable/std/?search=shuffle . 
The result is `std::rand::Rng::shuffle  - Shuffle a mutable slice in place.` but the link https://doc.rust-lang.org/stable/rand/trait.Rng.html#method.shuffle does not lead anywhere. Happens in both stable and nightly and the documentation curiously does not find the rand module or Rng trait.

**Comment by e00E** [comment]
Trying to use the rand module in rust nightly yields `error: module `rand` is private`.

**Comment by e00E** [comment]
Now I found https://doc.rust-lang.org/num/rand/index.html but this still means there is that one old search result in the docs!

**Comment by bluss** [comment]
FYI, the doc home of the [`rand` crate is here](http://doc.rust-lang.org/rand/rand/index.html). It should no show up at all in libstd's docs or doc search.

**Comment by steveklabnik** [comment]
shuffle no longer appears in doc search, so I'm going to give this one a close.
