### ISSUE TITLE
Broken links in rustbook chapter on compiler plugins

### ISSUE THREAD

**Issue by eminence** [rust-lang/rust#28309]
This might be a known side-effect of the immature nature of compiler plugins, but nearly all of the links from the "Compiler Plugins" chapter are broken.

https://doc.rust-lang.org/nightly/book/compiler-plugins.html

Example from the 2nd paragraph:

See the [rustc::plugin](https://doc.rust-lang.org/nightly/rustc/plugin/) documentation for more about the mechanics of defining and loading a plugin.

All broken links are generally to a page from the `rustc` docs or the `syntax` docs (which I can't actually find anywhere)

**Comment by ebfull** [comment]
> All broken links are generally to a page from the rustc docs or the syntax docs (which I can't actually find anywhere)

This is what that page wants to point to:

http://manishearth.github.io/rust-internals-docs/rustc/plugin/index.html

This stuff is no longer produced by default because it cluttered up the documentation and got indexed by search engines.

**Comment by steveklabnik** [comment]
Yes, this is a known limitation of the current set of choices on how to do things.

We've been talking about making an official /internals route, with which this could then be updated to, but I'm not sure it was ever done. @edunham?

**Comment by steveklabnik** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/29893
