### ISSUE TITLE
Weird dropping issues with transmute() and "" vs "let _ = "

### ISSUE THREAD

**Issue by ubsan** [rust-lang/rust#28310]
``` rust
struct Dropper;

impl Drop for Dropper {
    fn drop(&mut self) {
        println!("drop");
    }
}

fn main() {
    let d = Dropper;
    unsafe { std::mem::transmute::<_, u8>(d) };
}
```

this prints "drop".

``` rust
struct Dropper;

impl Drop for Dropper {
    fn drop(&mut self) {
        println!("drop");
    }
}

fn main() {
    let d = Dropper;
    let _ = unsafe { std::mem::transmute::<_, u8>(d) };
}
```

this does not.

play.rust-lang.org, latest nightly.

http://is.gd/7QVbiz

**Comment by GBGamer** [comment]
What is happening is that the drop flag is getting set to "dropped" in the second version, while it is never set off of "not dropped" in the first.

**Comment by GBGamer** [comment]
Okay, I started reading the assembly, because it makes way more sense.

Cleaned up:

```
main:
    push	rbp
    mov	rbp, rsp
    sub	rsp, 16

    lea	rdi, [rbp - 8]
    mov	byte ptr [rbp - 1], 61
    mov	byte ptr [rbp - 8], -44 ; this is where the drop flag is set
    call	_ZN7Dropper9drop.256317hcf85f43760592a92E

    add	rsp, 16
    pop	rbp
    ret
```

and

```
main:
    push	rbp
    mov	rbp, rsp
    sub	rsp, 32
    lea	rax, [rbp - 8] ; first, remember that rax points to the Dropper
    mov	esi, 29 ; this is what we're memsetting to
                            ; don't ask me why it's here and not closer to the function
    mov	ecx, 1
    mov	edx, ecx ; set one byte
    mov	byte ptr [rbp - 1], 61

    mov	byte ptr [rbp - 8], -44 ; notice we set the drop flag here
    mov	dil, byte ptr [rbp - 8]
    mov	byte ptr [rbp - 9], dil
    mov	r8, rax
    mov	qword ptr [rbp - 24], rax ; r8 and [rbp - 24] are both pointing to the Dropper now
    mov	rdi, r8 ; we're memsetting the Dropper, here
    call	memset@PLT   ; this memset

    mov	r9b, byte ptr [rbp - 9]
    mov	byte ptr [rbp - 10], r9b

    mov	rdi, qword ptr [rbp - 24]
    call	_ZN7Dropper9drop.256317h2845f499b38a318cE

    add	rsp, 32
    pop	rbp
    ret
```

**Comment by arielb1** [comment]
`d` is consumed by the transmute and should not be dropped.

**Comment by bltavares** [comment]
Triaging: is this still a valid issue?

**Comment by ubsan** [comment]
Yes.

**Comment by ubsan** [comment]
This is still a valid issue even with MIR. The issue is with `transmute`.

**Comment by eddyb** [comment]
Well, MIR *as it is right now*, with `transmute` in another function. My MIR transmute might work, didn't get to check it yet.

```rust
#![crate_type = "lib"]

pub struct Dropper;

impl Drop for Dropper {
    fn drop(&mut self) {}
}

pub unsafe fn foo(d: Dropper) {
    std::mem::transmute::<_, u8>(d);
}
```

The IR for this shows that `d` is managed using a `dropflag_hint_19` variable but `transmute` unconditionally calls the drop glue without looking at `dropflag_hint_19`.
*While* the drop glue checks for the drop filling pattern, `d` was never overwritten with it (because `dropflag_hint_19` is being used instead for that purpose).

**Comment by Mark-Simulacrum** [comment]
The two code samples in the original issue now compile with equivalent outputs (no output), which is what I think we expect to have happen, though I'm only ~90% sure. As such, I'm going to close, but please do reopen if this is still an issue with a code sample that demonstrates it.

**Comment by ubsan** [comment]
I would like to point out that this is entirely undefined behavior, and therefore technically correct compilation :)
