### ISSUE TITLE
Use --release-channel=stable by default on releases

### ISSUE THREAD

**Issue by radare** [rust-lang/rust#28322]
Release tarballs should be compilable with just basic `./configure ; make ; sudo make install` without having to pass special flags to configure. This is the case of the `--release-channel` option, that must be changed in the releases.

**Comment by alexcrichton** [comment]
cc @brson, @edunham, this seems like a good idea to me!

**Comment by edunham** [comment]
I have no objections to this idea. 

Please cc me [if|when] a PR adds this feature, since the change may necessitate some minor changes to avoid changing the buildslaves' behavior.

**Comment by brson** [comment]
I think I'm ok with this, although there's also something to be said for distributing the same source we are building from and this will require flipping a bit somewhere (ofc we're not building from the source tarball at all and basically nobody has any idea whether it even works :).

Off-hand I don't have a smart way to do this. I guess we would need to add some additional metadata to the source directory for the configure script to scrape, or we could frob the configure script with sed when packaging the source tarball.

**Comment by alexcrichton** [comment]
We could perhaps special case this and say ["if .git isn't present we're a source tarball"](https://github.com/rust-lang/rust/blob/master/configure#L733-L742) and just piggy back on that logic.

**Comment by brson** [comment]
@alexcrichton Yeah, we could. I'm wary though that those may be two distinct cases.

**Comment by steveklabnik** [comment]
Yeah, I feel vaguely the same re: repeatable builds and such, but @alexcrichton 's suggestion seems reasonable, but possibly footgun-ny...

**Comment by radare** [comment]
Maybe just check if .git exists?

**Comment by brson** [comment]
OK, let's just piggy-back on the .git check.
