### ISSUE TITLE
dereferences in statics can create broken code

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#28324]
## STR
```Rust
extern {
    static error_message_count: u32; // anything will do
}
pub static BAZ: u32 = *&error_message_count;
fn main() {}
```

##

**Comment by arielb1** [comment]
## Result

This code can't be linked. Currently it trips an LLVM assertion.

**Comment by eefriedman** [comment]
I think this is a duplicate... but I can't find it at the moment; essentially, we don't enforce the restriction that you're not allowed to dereference the address of a static.

**Comment by christopherdumas** [comment]
Should this restriction be added?

**Comment by jonas-schievink** [comment]
This seems to segfault on stable and beta. On nightly it doesn't compile, so this looks fixed: `error: cannot refer to other statics by value, use the address-of operator or a constant instead`
