### ISSUE TITLE
Cannot hygienically create test functions in macro

### ISSUE THREAD

**Issue by tbu-** [rust-lang/rust#28335]
Code:

```
macro_rules! macro_ {
    ($t:ty) => {
        #[test]
        fn test() { }
    }
}

struct Foo;
struct Bar;
macro_!(Foo);
macro_!(Bar);
```

Error:

```
a.rs:4:9: 4:22 error: duplicate definition of value `test` [E0428]
a.rs:4         fn test() { }
               ^~~~~~~~~~~~~
a.rs:1:1: 6:2 note: in expansion of macro_!
a.rs:11:1: 11:14 note: expansion site
a.rs:4:9: 4:22 help: run `rustc --explain E0428` to see a detailed explanation
a.rs:4:9: 4:22 note: first definition of value `test` here
a.rs:4         fn test() { }
               ^~~~~~~~~~~~~
a.rs:1:1: 6:2 note: in expansion of macro_!
a.rs:10:1: 10:14 note: expansion site
error: aborting due to previous error
```

**Comment by tomjakubowski** [comment]
The `#[test]` attribute is irrelevant; fails with the same message without it.

**Comment by christopherdumas** [comment]
So we can't hygienically create **any** functions? That seems odd.

**Comment by lfairy** [comment]
One workaround is to nest the function in a module:

```rust
macro_rules! generate_test {
    ($m:ident, $t:ty) => {
        #[cfg(test)]
        mod $m {
            #[test]
            fn test() { }
        }
    }
}

struct Foo;
generate_test!(foo, Foo);
```

**Comment by semmaz** [comment]
The problem here is not about hygiene of your macro,
```rust
macro_!(Foo);
macro_!(Bar);
```
will expand into two functions with same identifier (name) - `test`, hence the error message about `duplicate definition of value 'test'`.

So, as @lfairy pointed out, you can do this, I'll only add that module usage is [unnecessary](http://is.gd/d7p6G6).

**Comment by tbu-** [comment]
@semmaz 

I thought this is what macro hygiene is: The identifiers within your macro don't clash with those outside of it?

**Comment by jonas-schievink** [comment]
@tbu- That's true, but I think only locals are hygienic

**Comment by durka** [comment]
It says in the book, "This holds for let bindings and loop labels, but not for items."

**Comment by steveklabnik** [comment]
Triage: it's been 18 months, and it's not clear that there's actually a bug here. Closing! If that's wrong, please open a new bug with the exact details today, thank you!

**Comment by tbu-** [comment]
Yea, probably not a bug. Sorry for not closing it before.
