### ISSUE TITLE
Improve [..] and as_slice documentation

### ISSUE THREAD

**Issue by rseymour** [rust-lang/rust#28359]
The section of the Rust book on Slices is nice (hard to find in primitive types) but it gives more information on [..] (and it's origins in [1..] and [3..5] [..3] type indexing):

https://github.com/rust-lang/rust/blob/master/src/doc/trpl/primitive-types.md#slices

The actual docs for slice just intro it out of nowhere with no explanation of the fact that it's syntactic sugar for as_slice.  

https://github.com/rust-lang/rust/blob/9165a4e2dcaaa878a33379c6ff097c68f0ca0485/src/libcollections/slice.rs#L19

This is a subtle thing, but since googling for [..] is hard and github searching for "[..]" is basically impossible, it's a tough thing to have to search out, let alone explain on the web. 

Thanks!  Anyway, great documentation, hard to search for without single page, but I would want to fix the docs in libcollections if possible since ideally it would have more information and detail there.

-Rich

**Comment by steveklabnik** [comment]
> hard to search for without single page

cc https://github.com/rust-lang/rust/issues/22786


I completely agree that this is a bit weird right now. I'd like to add something, but I'm not sure what form it should take.

**Comment by christopherdumas** [comment]
It doesn't seem like `as_slice` is defined in rust nightly. Playground link: https://play.rust-lang.org/?gist=b220989e7c850403dd7b&version=stable

**Comment by steveklabnik** [comment]
In general, `as_slice()` is behind the `convert` feature gate, and `&foo[..]` should be used instead.

**Comment by christopherdumas** [comment]
Ah. That explains it. So it seems like `as_slice` and `[..]` are actually different things, because one is behind a feature gate, and one is not. Am I right about this?

**Comment by steveklabnik** [comment]
They do the same thing. The syntax was added later, one of the motivations was that `.as_slice()` is common and quite long, as well as an inexpensive operation.

**Comment by leodasvacas** [comment]
:+1: to this, it's totally ungoogleable, from the reference I concluded it's an use of the range operator, the book section could mention it.
