### ISSUE TITLE
Field access of cast expression: discrepancy between parser-lalr and rustc

### ISSUE THREAD

**Issue by rprichard** [rust-lang/rust#28362]
It's not clear to me whether this code is valid syntax.  It looks wrong, so maybe it ought to be rejected.  `rustc` rejects it, but `parser-lalr` accepts it:

``` rust
struct S { f: i32 }
fn main() {
    let s = S { f: 42 };
    s as S.f;
}
```

It _looks_ like it should parse as `s as (S.f)`, and that wouldn't parse.  `parser-lalr` parses it as `(s as S).f`

```
test.rs:4:11: 4:12 error: expected one of `!`, `(`, `::`, `;`, `<`, `}`, or an operator, found `.`
test.rs:4     s as S.f;
                    ^
```

(To test the LALR grammar, build the check-grammar target, then run grammar/parser-lalr -v.)

**Comment by brson** [comment]
Current output:

```
rustc 1.16.0 (30cf806ef 2017-03-10)
error: expected one of `!`, `(`, `::`, `;`, `<`, or `}`, found `.`
 --> <anon>:4:11
  |
4 |     s as S.f;
  |           ^

error[E0308]: mismatched types
 --> <anon>:4:5
  |
4 |     s as S.f;
  |     ^^^^^^ expected (), found struct `S`
  |
  = note: expected type `()`
             found type `S`

error: aborting due to previous error
```

**Comment by nikomatsakis** [comment]
Seems clear that parser-lalr is wrong here.

**Comment by nikomatsakis** [comment]
However, I can see why it arises. `foo.bar` is not a valid type, after all.

**Comment by steveklabnik** [comment]
Triage; is parser-lalr still a thing? is this issue relevant?

**Comment by Mark-Simulacrum** [comment]
I don't think we currently maintain any separate grammar - see https://github.com/rust-lang/rust/pull/64896.
