### ISSUE TITLE
Calling a block: discrepancy between parser-lalr and rustc

### ISSUE THREAD

**Issue by rprichard** [rust-lang/rust#28361]
I don't know whether this code is valid syntax:

``` rust
fn f(i: i32) -> i32 { i }
fn main() {
    1 + {f}(1);
}
```

It is rejected by `rustc`:

```
test.rs:3:12: 3:13 error: expected one of `.`, `;`, `}`, or an operator, found `(`
test.rs:3     1 + {f}(1);
                     ^
```

It is _accepted_ by the LALR parser in src/grammar.  (Build the `check-grammar` target, then run `grammar/parser-lalr -v`.)

**Comment by rprichard** [comment]
#27478 is a similar issue.

`rustc` and `parser-lalr` both accept these variants:
```rust
(1 + {f}(1));
let _ = 1 + {f}(1);
```

**Comment by rprichard** [comment]
More sublety: assignment is OK:
```rust
fn f(i: i32) -> i32 { i }
fn main() {
    let mut b: bool;
    let mut i: i32;
    1 == {f}(1); // error: expected one of `.`, `;`, `}`, or an operator, found `(`
    i = {f}(1); // OK
    b = 1 == {f}(1); // OK
}
```

**Comment by nagisa** [comment]
Seems like should be valid.

```
fn f(i: i32) -> i32 { i }
fn main() {
    1 + {{f}(1)};
}
```

seems to get mis-parsed in some way as well.

**Comment by steveklabnik** [comment]
Tagging with T-lang as the language team should decide what the grammar actually is here.

**Comment by Mark-Simulacrum** [comment]
I personally think that this is not something we should allow due to requiring parens elsewhere; and in any case it doesn't seem like it's worthwhile to keep this issue open.
