### ISSUE TITLE
Somehow address redundancies between doc-comment code and crate code

### ISSUE THREAD

**Issue by Kimundi** [rust-lang/rust#28373]
# Issue

I noticed with a few of my crates that I have some redundancies between my docs and the code in the crate, specifically testcases. As a example, here `nice_example()` is duplicated:

``````
//! docs docs docs
//! docs docs docs
//! ```
//! fn nice_example() { ... }
//! ```

...

#[test]
fn nice_example() { ... }
``````

Now, there are right now two ways to deal with this:
- Keep both copies
  - Con: redundant copies, code can start drifting apart unintentionally.
  - Pro: If docs and tests diverge intentional, no additional work is needed.
- Remove the separate unit test copy of the code.
  - Pro: The docs will get tested anyway
  - Pro: No redundancy
  - Con: Unit tests get split between two locations
  - Con: Unit tests start mixing with documentation, a change to either might cause changes to both and/or moving the unit test code back and forth between the docs and the crate.

As an additional issue, having rust code in doc comments be highlighted as rust code is kinda complicated - or at least not implemented in most highlighters.
# Proposal

Have a way in doc comments to "include" the source code of an item in the documented crate, eg:

``````
//! docs docs docs
//! docs docs docs
//! ```
//! #rustdoc_include self::nice_example
//! ```

...

#[test]
fn nice_example() { ... }
``````
- Pro: Only one copy of the actual code
- Pro: No redundancy
- Pro: Unit tests can be kept separate from the docs, even if they are nicely documented and used as example code in them.
- Pro: If the docs don't want to use that particular code example anymore, only the reference needs
  to be deleted, and a nicely commented unit test remains.
- The one copy of the code is outside doc comments, and thus will get highlighted correctly.
- Con: More machinery for rustdoc to support
- Con: Harder to read and write the documentation directly in the source.

**Comment by steveklabnik** [comment]
Since doc examples are already run as tests, why do you need it in the tests as well as in the docs?

**Comment by frewsxcv** [comment]
Should this be in rust-lang/rfcs?

**Comment by Kimundi** [comment]
Whoops, I forgot aboput this issue.

I... don't think it belongs into RFCs? I mean, its purely localized feature for the rustdoc doc generator, it has no effect on language semantic.

Well, thinking about it again I guess it would affect how the doc ecosystem handles writing examples in general, but thats still kinda orthogonal since you still would use this feature on a case-by-case basis.

**Comment by steveklabnik** [comment]
>  (Or am I misremembering and the rfc repo is about any kind of feature to any part of Rusts ecosystem?)

It is, but for "substantial" changes.

**Comment by gyscos** [comment]
Being able to include example files (from the `examples/` directory) would also go a long way toward reducing this kind of redundancy.

**Comment by Mark-Simulacrum** [comment]
I personally think this is a substantial enough change to rustdoc and would be RFC worthy, even if the RFC would be pretty small.
