### ISSUE TITLE
Information about @bors

### ISSUE THREAD

**Issue by christopherdumas** [rust-lang/rust#28380]
I'm planning to write a short manual for bors, so anyone who has any information about how bors works, please post here.

**Comment by bluss** [comment]
All of this information should be up to date and correct. The current impl behind bors is called homu.

http://homu.io/ see also the link to the homu repo,

There is also a bit of bors docs in [CONTRIBUTING.md](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md)

**Comment by bluss** [comment]
I have dug into the source a times, just to check details of the commands.

For example it's useful to know the detail that the flags `try` and `rollup` are sticky (saved in the pr state) and stay unless unset (`try-` or `rollup-`).

**Comment by nagisa** [comment]
http://buildbot.rust-lang.org/homu/ has a cheat sheet.
