### ISSUE TITLE
Missing code snippet in the Error Handling guide

### ISSUE THREAD

**Issue by swatteau** [rust-lang/rust#28418]
Paragraph 6 of https://doc.rust-lang.org/nightly/book/error-handling.html#the-option-type starts with : "But wait, what about unwrap used in unwrap-double?". The problem is that there is no code sample involving something called `unwrap-double`. It seems that there is some piece of text missing. Moreover, the presence of a dash in the name is a little dubious.

EDIT: same thing with `option-ex-string-find` at the beginning of https://doc.rust-lang.org/nightly/book/error-handling.html#composing-option%3Ct%3E-values. I guess there might be other occurences of this problem in the rest of the text.

**Comment by christopherdumas** [comment]
Wow. It seems like I've overlooked a ton of things.

**Comment by christopherdumas** [comment]
@swatteau I figured out whats going on. In the original blog post, each code snippet was named like a file. The things he was referencing, like unwrap-double, were the names of the code snippets.

**Comment by swatteau** [comment]
@christopherdumas I just skimmed the rest of the text and saw nothing else so that may well be the only two places where the problem occurs.

**Comment by steveklabnik** [comment]
@christopherdumas This is what happens when there's a huge amount of text, it happens. :) More eyes find more bugs!

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/28755 also fixed this, I believe!
