### ISSUE TITLE
Broken anchor links in new Error Handling guide

### ISSUE THREAD

**Issue by filsmick** [rust-lang/rust#28412]
In the [Error Handling guide](https://doc.rust-lang.org/nightly/book/error-handling.html), clicking the anchor link "A brief interlude: unwrapping isn't evil" in the table of contents has no effect.

It points to: https://doc.rust-lang.org/nightly/book/error-handling.html#a-brief-interlude-unwrapping-isnt-evil

...whereas the heading's anchor is: https://doc.rust-lang.org/nightly/book/error-handling.html#a-brief-interlude:-unwrapping-isn't-evil

EDIT: it's actually worse than that - it seems all headings containing special characters (`<`, `>`, `!`) have broken links:
- [Composing `Option<T>` values](https://doc.rust-lang.org/nightly/book/error-handling.html#composing-optiont-values)
- [The `try!` macro](https://doc.rust-lang.org/nightly/book/error-handling.html#the-try-macro)
- [The real `try!` macro](https://doc.rust-lang.org/nightly/book/error-handling.html#the-real-try-macro)
- [Error handling with `Box<Error>`](https://doc.rust-lang.org/nightly/book/error-handling.html#error-handling-with-boxerror)

**Comment by swatteau** [comment]
The problem is apparently not limited to just headings. For example, the first sentence in the section https://doc.rust-lang.org/nightly/book/error-handling.html#the-option-type says : "The Option type is defined in the standard library" but the link provided leads to the section on pattern matching.

**Comment by christopherdumas** [comment]
I'm sorry, I'll get right on that. Thanks for noticing, @filsmick.

**Comment by christopherdumas** [comment]
@filsmick Thats strange, because in my local markdown viewer, all those links work.

**Comment by semmaz** [comment]
@christopherdumas Yeah, the reason is because `rustdoc` doesn't discard special chars in sections `id` and `href` attributes.

**Comment by christopherdumas** [comment]
Well, I fixed it now.

**Comment by filsmick** [comment]
https://doc.rust-lang.org/stable/book/error-handling.html#table-of-contents

Try clicking on "Composing Option<T> values". Looks like the fix didn't make it to stable?

**Comment by steveklabnik** [comment]
@filsmick yes, it was fixed after 1.4 was released. 1.5 has the fix.
