### ISSUE TITLE
Using a plugin that was built without `-C prefer-dynamic` causes LLVM error

### ISSUE THREAD

**Issue by pczarn** [rust-lang/rust#28434]
I forgot to add `plugin = true` to Cargo.toml and got this when building an external test:

```
: CommandLine Error: Option 'interpreter-print-volatile' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

For reference, this is an incorrect way to build a plugin:
`rustc src/lib.rs --crate-type dylib -g`
This is added by `plugin = true`:
`rustc src/lib.rs --crate-type dylib -C prefer-dynamic -g --test -C metadata=7ede684f643fceb6 -C extra-filename=-7ede684f643fceb6`

**Comment by steveklabnik** [comment]
Is there any way we can get a full reproduction here? Does this work with any plugin code at all?

**Comment by Yamakaky** [comment]
I have a [similar problem](https://travis-ci.org/crabtw/rust-bindgen/jobs/132862267) with [bindgen_plugin](https://github.com/crabtw/rust-bindgen/tree/fix-plugin).

**Comment by Mark-Simulacrum** [comment]
Could someone provide a quick summary of how to reproduce this? Otherwise I think we should close.

**Comment by steveklabnik** [comment]
With no reproduction instructions in almost two years, I'm going to close this. Thanks!
