### ISSUE TITLE
Crates failing on beta

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#28446]
This has been reported multiple times: https://travis-ci.org/serde-rs/json/jobs/80688459

The new beta is mysteriously failing. Looks cargo-related. Need to fix this asap.

cc @alexcrichton @rust-lang/tools

**Comment by brson** [comment]
I'll try to repro later.

**Comment by brson** [comment]
@alexcrichton suspects this https://github.com/huonw/travis-cargo/blob/master/travis_cargo.py#L22-L26

**Comment by brson** [comment]
PR is already up: https://github.com/huonw/travis-cargo/pull/21

**Comment by huonw** [comment]
I published travis-cargo 0.1.8, which should fix this.
