### ISSUE TITLE
trpl: Invalid byte size terminology

### ISSUE THREAD

**Issue by baskerville** [rust-lang/rust#28461]
The following terms are used in `the-stack-and-the-heap.md`: *gigabyte*, *GB*.
But a gigabyte is 10^9 bytes, not 2^30.
The correct terms are: *gibibyte*, *GiB*.

**Comment by steveklabnik** [comment]
Given the news in https://users.rust-lang.org/t/the-rust-programming-language-is-going-to-be-published-by-no-starch-press/2777 , I'm going to wait to ask my editor what they think before pursing this one way or another.

**Comment by nagisa** [comment]
OP is right. There’s a non-trivial difference between `G-` and `Gi-`. This confusion usually stems from the long-term storage device manufacturers who try to sell less for more using two very similarly sounding units.

**Comment by steveklabnik** [comment]
OP is right in a technical sense, but almost everyone uses the more colloquial version, and I'm concerned about obscuring understanding.

**Comment by baskerville** [comment]
Before the standardization, the term *gigabyte* was ambiguous. It's no longer the case.

By not using the proper term you're willingly allowing the ambiguity to persist.

You can always add a footnote explaining why it's important to use the right term.
