### ISSUE TITLE
rustdoc generates cross-crate links to pages which don't exist because of #[doc(hidden)]

### ISSUE THREAD

**Issue by eefriedman** [rust-lang/rust#28480]
For example, https://doc.rust-lang.org/nightly/std/fmt/struct.Formatter.html#method.align links to https://doc.rust-lang.org/nightly/core/fmt/rt/v1/enum.Alignment.html, which doesn't exist because std::fmt::rt is marked #[doc(hidden)] .

**Comment by eefriedman** [comment]
Related: https://doc.rust-lang.org/nightly/std/fmt/trait.Debug.html links to https://doc.rust-lang.org/nightly/core/num/flt2dec/bignum/struct.Big32x40.html, which doesn't exist because it isn't a public type.

**Comment by mitaa** [comment]
These instances have been "fixed", but the underlying problem is IIRC still present. (#31948, https://github.com/rust-lang/rust/commit/8aa268e731aa201e086675f38e4337702c63f104)
