### ISSUE TITLE
Poor diagnostics on implicitly required `Sized` bound for all type parameters

### ISSUE THREAD

**Issue by soltanmm** [rust-lang/rust#28487]
[This](https://play.rust-lang.org/?gist=5563b832a31eefd08109&version=nightly):

```
fn main() {}

struct A<T: B> {
    a: T::S
}

trait B {
    type S;
    fn s(&self) -> Self::S;
    fn res(&self) -> A<Self> {
        A { a: self.s() }
    }
}
```

errors out with:

```
<anon>:11:9: 11:10 error: the trait `core::marker::Sized` is not implemented for the type `Self` [E0277]
<anon>:11         A { a: self.s() }
                  ^
<anon>:11:9: 11:10 help: see the detailed explanation for E0277
<anon>:11:9: 11:10 note: `Self` does not have a constant size known at compile-time
<anon>:11:9: 11:10 note: required by `A`
error: aborting due to previous error
playpen: application terminated with error code 101
```

I'd expect that only the the associated type `S` needs to be Sized, not Self.

**Comment by cybergeek94** [comment]
Adding a `?Sized` bound to the parameter on `struct A` fixes the problem:

http://is.gd/TFETqZ

Type parameters on structs have an implicit `Sized` bound by default. It's a papercut, but I don't believe it's an error.

**Comment by soltanmm** [comment]
Learned something new. I guess I'd like to have seen a diagnostic.

Alternatively, is there any modern reason for making type parameters on structs `Sized` by default or is that a holdover, e.g. from when it was safe to assume that type parameters would always directly appear as struct members (pre-associated types)?

**Comment by cybergeek94** [comment]
@soltanmm In actuality, it looks like an implicit `Sized` bound is added only when the parameter is bounded by a trait: http://is.gd/qGECsy

Adding the `Sized` bound to `B` fixes it as well, but that prevents it from being used as a trait object.

> is there any modern reason for making type parameters on structs Sized by default or is that a holdover, e.g, from when it was safe to assume that type parameters would always directly appear as struct members (pre-associated types)?

I spent quite some time trying to think of a good answer, but nothing solid came to mind, just a lot of conjecture. The closest I got to a satisfying answer was preventing users from accidentally creating DSTs out of structs that weren't designed for it, but that doesn't explain why it works without any trait bounds.

**Comment by arielb1** [comment]
@soltanmm 

The reason is to not annoy users with errors about missing `Sized` bounds. All type parameters (structs, impls, fns, also associated types) have a `Sized` bound unless you use `?Sized`.

**Comment by soltanmm** [comment]
@arielb1 I'm sorry, I'm not sure I understand what you meant (impls and fns aren't type parameters as far as I know). Is this a justification for a blanket rule, despite superfluous bounds?

**Comment by arielb1** [comment]
@soltanmm 

Every type parameter (this includes type parameters in impls, traits, structs, enums, fns, and any other place I have missed, with the exceptions of `type`-aliases and the `Self` of traits) that is not marked as `?Sized` gets an implicit `Param: Sized` bound, just as if you had typed it manually. T

For example:
```Rust
fn foo<T>() {} // this requires T: Sized
trait Foo<P> {} // this requires P: Sized, but not `Self: Sized`
impl<T> Foo<u32> for [*const T] {} // this requires T: Sized (but not `[*const T]: Sized`)
impl<T:?Sized> Foo<()> for T {} // does not require `T: Sized`
```

**Comment by soltanmm** [comment]
If that's up for discussion, would this be best handled in RFC-land?

In the meanwhile, the diagnostics are at the very least a bit ad hoc relative to what's expected (especially given that The Book does not cover this explicitly).

**Comment by steveklabnik** [comment]
>If that's up for discussion, would this be best handled in RFC-land?

I don't think it is, as it'd be a breaking change.

> (especially given that The Book does not appear to cover this explicitly).

https://doc.rust-lang.org/stable/book/unsized-types.html

> All generic type parameters implicitly have the Sized bound, so the ?Sized can be used to opt-out of the implicit bound.

The diagnostic is also slightly different today:

```
> error[E0277]: the trait bound `Self: std::marker::Sized` is not satisfied
  --> <anon>:10:5
   |
10 |       fn res(&self) -> A<Self> {
   |  _____^ starting here...
11 | |         A { a: self.s() }
12 | |     }
   | |_____^ ...ending here: the trait `std::marker::Sized` is not implemented for `Self`
   |
   = help: consider adding a `where Self: std::marker::Sized` bound
   = note: required by `A`
```

Given all this, and the lack of comments in 18 months, I think that we don't need to keep this issue open. Closing!
