### ISSUE TITLE
`VecDeque::push_back(())` does not work correctly.

### ISSUE THREAD

**Issue by dpc** [rust-lang/rust#28488]
http://is.gd/NY4tCl

```
use std::collections::VecDeque;
 
fn main() {
    let mut v = VecDeque::new();
    v.push_back(());                                                                                                         
    assert!(v.len() > 0 );   
}

thread '<main>' panicked at 'assertion failed: v.len() > 0', <anon>:6
```

**Comment by ituxbag** [comment]
() is void type / value, so it should be correct; if you add nothinh to an empty collection, the collection remains  empty ...

**Comment by utkarshkukreti** [comment]
`VecDeque::push_front()` too:

```rust
use std::collections::VecDeque;
 
fn main() {
    let mut v = VecDeque::new();
    v.push_front(());                                                                                                         
    assert_eq!(v.len(), 1);   
}
```

fails with

```
thread '<main>' panicked at 'assertion failed: `(left == right)` (left: `2`, right: `1`)', <anon>:6
```

**Comment by jonas-schievink** [comment]
@ituxbag No, the collection just contains one nothing ;)

`()` is just a zero-sized type, adding it to collections stores 0 bytes, but 1 element. For example, it works fine with a`Vec<()>`:

```rust
fn main() {
    let mut v = Vec::new();
    v.push(());
    v.push(());
    assert_eq!(v.len(), 2);
}
```

**Comment by apasel422** [comment]
This variant appears to loop forever, presumably in `drop` since it outputs `2` (!) first:
```rust
use std::collections::VecDeque;

fn main() {
    let mut v = VecDeque::new();
    v.push_front(());
    println!("{}", v.len());
}
```

**Comment by bluss** [comment]
Let's aim to improve the testsuite with general collections + Zero sized types tests too.

**Comment by bluss** [comment]
Ok, Zero sized types (ZSTs) is a can of worms, potentially there are several problems, but the VecDeque in Rust 1.3 with ZST uses `capacity = !0` which is not a power of two. Now how to fix this..

**Comment by Gankro** [comment]
I would recommend `isize::MAX + 1`, giving a capacity of isize::MAX elements -- I'm becoming more swayed that this is a reasonable upper bound to select unconditionally.

**Comment by Gankro** [comment]
Oh, right this capacity is inherited from RawVec! Annoying, but not a big deal.

**Comment by bluss** [comment]
This used to work in Rust 1.0, 1.1, 1.2. [Regression report, ad-hoc via travis](https://travis-ci.org/bluss/odds/builds/81070434)

**Comment by bluss** [comment]
@dpc As soon as a new nightly is built, it would be great if you could verify that the bug was fixed for the original problem.

**Comment by dpc** [comment]
Sure. I'll try that tomorrow.

**Comment by bluss** [comment]
@dpc Any luck?

**Comment by dpc** [comment]
The original problem reported confirmed it's fixed in: https://github.com/dpc/mioco/issues/55#issuecomment-142004340

**Comment by bluss** [comment]
Thank you! Good to have some confidence so that we can backport the fix to beta.
