### ISSUE TITLE
Emitted LLVM-IR should be annotated to connect to rs source

### ISSUE THREAD

**Issue by daniel-vainsencher** [rust-lang/rust#28482]
I've tried looking at llvm-ir output to understand how my code is translated by rustc, but this is currently very difficult.

Can be by line numbers, or include original source in an llvm-ir comment.
For those llvm-ir assignments that correspond to rust variable assignments, giving the rust variable name would be great. Etc.

**Comment by eefriedman** [comment]
The llvm-dis tool already has code to do this.  See https://github.com/llvm-mirror/llvm/blob/4a4558e436353fa1fc4cd4ddff7491e631d71357/tools/llvm-dis/llvm-dis.cpp#L71 .  It would be possible to integrate something similar into rustc directly if you think it's useful.

**Comment by daniel-vainsencher** [comment]
Something like that, except of course that it ties the llvm-ir to the rust code, not to the assembly.

**Comment by steveklabnik** [comment]
Triage: no change I'm aware of

**Comment by Mark-Simulacrum** [comment]
I personally don't think this is something we're likely to implement on our side and if it's a relatively small change would be implementable by PR (as an unstable flag, probably), and if it's something more complicated then it'd be internals thread and such worthy.
