### ISSUE TITLE
LLVM assertion hit while building SpiderMonkey bindings

### ISSUE THREAD

**Issue by michaelwu** [rust-lang/rust#28502]
I have some code at https://gist.github.com/michaelwu/1040fa8f592ad020f893 . Building it with the latest nightly using `rustc --crate-type lib jsapi.rs` results in this assertion `Assertion failed: (getOperand(0)->getType() == cast<PointerType>(getOperand(1)->getType())->getElementType() && "Ptr must be a pointer to Val type!"), function AssertOK, file /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/llvm/lib/IR/Instructions.cpp, line 995.`.

I'm using rustc 1.5.0-nightly (cff041170 2015-09-17).

**Comment by michaelwu** [comment]
I've reduced the crash to: http://is.gd/wMIy8s

**Comment by michaelwu** [comment]
I've reduced it even further. http://is.gd/IOPhRx
```
pub struct Handle {
    pub ptr: *const u32,
}

pub struct ObjectOpResult;
impl ObjectOpResult {
    pub unsafe extern "C" fn test(_obj: Handle) {
    }
}
```

**Comment by dotdash** [comment]
Looks like we're not generating a shim to bridge between the C ABI and the Rust ABI when the function appears in an `impl` block.

**Comment by liebharc** [comment]
I've found this issue report since I just hit the same issue in my pet project. One thing which might be relevant is that the example http://is.gd/IOPhRx compiles fine on my Windows machine and fails on my Linux machine. Both machines are running:
```
rustc 1.6.0-nightly (338cdd7e0 2015-11-24)
```

**Comment by mrhota** [comment]
@steveklabnik @michaelwu's testcase doesn't crash on stable or nightly.

**Comment by michaelwu** [comment]
Guess it's fixed.
