### ISSUE TITLE
LLVM contains non-DSFG-compatible file

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#28509]
Per @anguslees, the file  src/llvm/cmake/modules/LLVMParseArguments.cmake carries the CC-BY _2.5_ license (an old version of the license), which is [not compatible with the Debian Free Software Guidelines](https://wiki.debian.org/DFSGLicenses). We are distributing this file in our source tarballs.

I don't know what practical impact this has besides making life slightly harder for Debian packagers.

[Original report](https://internals.rust-lang.org/t/perfecting-rust-packaging/2623/18?u=brson)

**Comment by anguslees** [comment]
I think this (old) thread has a concise discussion of the (unintended) DRM and credit issues Debian found with the wording in CC-BY 2.5:
 https://lists.debian.org/debian-project/2013/03/msg00000.html

I think (IANAL, etc) the practical impact is that this file may have difficulties with certain types of modification, and distributing it in DRM situations (eg: encrypted harddisks).  I haven't read the license sufficiently carefully to suggest how far those effects extends beyond the configure.sh/cmake stage.

**Comment by brson** [comment]
The file in question does not exist at that path any longer.

**Comment by brson** [comment]
I'm inclined to close this. If somebody else discovers a licensing issue they can raise it again.
