### ISSUE TITLE
transmute_copy doc is backward.

### ISSUE THREAD

**Issue by diaphore** [rust-lang/rust#28513]
The doc for [`mem::transmute_copy`][transmute_copy] states ...

> Interprets `src` as `&U`, and then reads `src` without moving the contained value.

... but the function is built around [`ptr::read`][read] which does a raw copy *first*. The distinction is crucial when accessing data with alignment restrictions. The [Nomicon][nomicon] documents the actual semantics more clearly :

>  It copies `size_of<U>` bytes out of an `&T` and interprets them as a `U`.

[transmute_copy]: https://github.com/rust-lang/rust/blob/master/src/libcore/mem.rs#L532
[read]: https://github.com/rust-lang/rust/blob/master/src/libcore/ptr.rs#L123
[nomicon]: https://github.com/rust-lang/rust/blame/master/src/doc/nomicon/transmutes.md#L27

**Comment by bluss** [comment]
The pointer is cast to `*const U` before it's passed to `ptr::read`, so it's read like an `&U`.

**Comment by alexcrichton** [comment]
Yeah I agree with @bluss in thinking the documentation here is fine because it's what's actually happening (reinterpreting the pointer then using `ptr::read` to read the value).

The nomicon is basically also right just worded differently I think. As a result, closing, but thanks for the report!
