### ISSUE TITLE
The docs for print! and println! should contain panics section

### ISSUE THREAD

**Issue by llogiq** [rust-lang/rust#28510]
Invocations of the `print!(..)` and `println!(..)` macros may panic if stdout isn't writeable. This is undocumented as of yet.

Proposed solution: Add a `# Panics` section in both doc comments.

**Comment by retep998** [comment]
This is closely related to https://github.com/rust-lang/rfcs/pull/1014 which made `print!` and friends not panic if stdout doesn't exist. Should it be expanded to cover other kinds of behavior?
Also see discussion in https://github.com/rust-lang/rust/issues/25977#issuecomment-135999955

**Comment by llogiq** [comment]
I agree that making `print!` not panic could be an even better solution. However, in the meantime, we still have an undocumented `Panic`. My suggestion is to fix the docs first (and don't forget to roll them back if we fix the actual `panic!`) and then concentrate on #25977.
