### ISSUE TITLE
Test that all collections work with zero-sized types (ZST)

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#28518]
In light of #28488, add tests to the testsuite that exercise all collections using ZST. Most common ZST is the `()` (empty tuple), and all collections need to support it.

**Comment by apasel422** [comment]
CC #28493.

**Comment by GlenDC** [comment]
I'm ok to do this :) I will jump on it today if that's alright :)

**Comment by apasel422** [comment]
@GlenDC Go for it!

**Comment by apasel422** [comment]
@GlenDC Are you still working on this?

**Comment by GlenDC** [comment]
I wasn't, but if that's fine for you I would like to retake work on this
tomorrow. I suddenly had a lot on my mind as my life will be changing a lot
from christmas on. But you revived me, so to speak. :) I will try to push a
proposed solution by tomorrow or the day after!

On 23 November 2015 at 19:39, Andrew Paseltiner <notifications@github.com>
wrote:

> @GlenDC <https://github.com/GlenDC> Are you still working on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rust-lang/rust/issues/28518#issuecomment-159040279>.
>



-- 
with kind regards

De Cauwsemaecker Glen
*Game developer and*
*Open Source Hacker*

http://www.glendc.com/

**Comment by apasel422** [comment]
@GlenDC Sure, go right ahead. No rush!

**Comment by KiChjang** [comment]
I think I'll take this, since there's radio silence on this issue.

**Comment by GlenDC** [comment]
@KiChjang yes please. Sorry, for being a roadblock. Thanks for taking it over :)
