### ISSUE TITLE
Re-exported functions aren't being resolved when used from other modules.

### ISSUE THREAD

**Issue by TyOverby** [rust-lang/rust#28524]
I did most of my development for a project on the 1.4-nightly branch of the compiler, but when running travis.ci (1.3-stable), I got really weird import resolution errors.

[errors here](https://travis-ci.org/TyOverby/ares/builds/81212781) - [source code here](https://github.com/TyOverby/ares)

The only imports that were unresolved were ones that were re-exported via `pub use` in another module, however, when I tried to make a [minimal test case](http://is.gd/gmns3V) it ends up working fine...

**Comment by TyOverby** [comment]
Reported as a bug because I don't know if this was a 1.3 regression, or if it was planned as a feature for 1.4.

**Comment by steveklabnik** [comment]
So, this builds on `1.4.0-beta.1`, and `rustc 1.5.0-nightly (7bf4c885f 2015-09-26)`, but yes, apparently not in 1.3. I'm guessing a bug got fixed, but since it is, I'm giving it a close. Thanks!
