### ISSUE TITLE
Replace the ast::Mac_ enum with a struct

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#28527]
https://github.com/rust-lang/rust/blob/master/src/libsyntax/ast.rs#L1137

```rust
pub enum Mac_ {
    MacInvocTT(Path, Vec<TokenTree>, SyntaxContext),   // new macro-invocation
}
```

this should instead be something like 

```rust
pub struct MacroInvoke {
    path: Path,
    tts: Vec<TokenTree>,
    context: SyntaxContext,
}
```

We'd need to update all type and other errors.

I'm willing to mentor this.

Please leave a comment if you're working on this and let me know if you need any help.

**Comment by apasel422** [comment]
I'm working on this.

**Comment by Manishearth** [comment]
Awesome!

**Comment by Manishearth** [comment]
Note: You may want to base it on top of https://github.com/rust-lang/rust/pull/28526, and convert the complicated "`and_then` + destructuring `match`" to a simpler "move `MacroInvoke` out of `P<T>` via `and_then` and then use fields throughout the function"
