### ISSUE TITLE
Rustdoc handling of public re-export is broken

### ISSUE THREAD

**Issue by rkruppe** [rust-lang/rust#28537]
Looking at nightly docs of `core::num`, the presentation of `ParseFloatError` is confusing. It looks like this: 

![rustdoc](https://cloud.githubusercontent.com/assets/2311707/9981695/622813d4-5fc4-11e5-9734-5884e190c801.PNG)

It should be rendered like `ParseIntError`, for example. The fact that it's defined in a private submodule is irrelevant and should not leak to unsuspecting users. The type *does* have a page, which can be found with the search, and links from other pages (functions, traits) do work. It's just the landing page for `core::num` that sucks.

FWIW, in `std::num` it *is* rendered normally (the source link is broken, but whatever).

**Comment by marti1125** [comment]
@steveklabnik I would like to take this.

**Comment by steveklabnik** [comment]
Have at it!

**Comment by adambadawy** [comment]
I think I'm looking at the same issue, but I want to give my analysis of it, cause the symptoms are a little different than described by @rkruppe.

I made a library crate named `kraid` for testing this.



### Example 1

`lib.rs`:
```rust
/// MyType is _my_ type
pub struct MyType;
```

A normal looking page is generated for `kraid` with `MyType` listed under **Structs**. The page generated for `MyType` also looks good.



### Example 2

`lib.rs`:
```rust
mod foo {
    /// MyType is _my_ type
    pub struct MyType;
}

pub use self::foo::MyType;
```

Same exact output as **Example 1**; the module `foo` is not mentioned. There was an instance in a non-minimal example where the `MyType` page was not rendered at all (file not found), but not this time I guess.



### Example 3

`lib.rs`:
```rust
mod foo {
    mod bar {
        /// MyType is _my_ type
        pub struct MyType;
    }

    pub use self::bar::MyType;
}

pub use self::foo::MyType;
```

`pub use self::foo::MyType;` is listed under **Reexports**, and `foo` is a link to a blank page. `kraid/foo/struct.MyType.html` is also a blank page, and unreachable by link.



----

If anyone thinks this is a separate issue, I can open one up.

**Comment by rkruppe** [comment]
As you say, the way to trigger it is different: I described a re-export from a *hidden, public module*. You described a re-export from a *private submodule of a private module*. However, I hope that this is caused by the same piece of code and both can be fixed in one small patch. Let's just expand the scope of this issue.

**Comment by adambadawy** [comment]
Hey @marti1125, have you made progress on this? I might try fixing it myself.

**Comment by marti1125** [comment]
@adambadawy you can try it! I don't have any progress =(

**Comment by adambadawy** [comment]
@marti1125 :ok_hand: I'll have a look. Not sure I have the knowledge to fix it.
