### ISSUE TITLE
Give windows-gnu-specific issues a tag separate from A-windows

### ISSUE THREAD

**Issue by briansmith** [rust-lang/rust#28530]
I propose that A-windows be used for any issue that affects -msvc targets, but not for any issue that doesn't affect -msvc targets. In particular, if an issue is msys-specific then it shouldn't be given the A-windows tag, but instead a different one like A-Windows-gnu.

In theory there could be issues that affect -msvc but not -gnu, but I don't think supporting that case is important enough to justify an additional separation of tags.

This idea rests on the premise that -msvc is the default and most important Windows target, and that we should be paying attention more to -msvc than to -gnu.

The reason I suggest this is that it is very difficult to figure out the current state of the -msvc target from looking at the bug tracker, because there's too much -gnu-specific stuff mixed in.

**Comment by alexcrichton** [comment]
To clarify, the state of msvc is "everything should work on 64-bit and please report bugs if you find otherwise"

**Comment by Diggsey** [comment]
AFAIK, there are very few issues that affect `-gnu` but not `-msvc`, and a decent number that affect just `-msvc`.

**Comment by retep998** [comment]
I'd be okay with having a A-windows-gnu and A-windows-msvc with A-windows covering all of windows in general.

**Comment by petrochenkov** [comment]
>I'd be okay with having a A-windows-gnu and A-windows-msvc with A-windows covering all of windows in general.

+1

**Comment by steveklabnik** [comment]
:+1: :shipit:
