### ISSUE TITLE
Compiler crash while linking lambdas across crates

### ISSUE THREAD

**Issue by valarauca** [rust-lang/rust#28542]
Source code that causes crash

https://github.com/valarauca/Block/tree/CompilerCrash

Has own dedicated branch. Readme.md includes git check out of extern crate which was loaded.

Occurs in Rustc v1.3 x86_64 Linux v3.19.3

Also Occurs in Rustc v1.2 x86_64 

rustc 1.4.0-beta.1 (d2e13e822 2015-09-15) doesn't crash.

**Comment by arielb1** [comment]
Doesn't seem important enough for a backport.
