### ISSUE TITLE
Docs say Rust is not production ready.

### ISSUE THREAD

**Issue by DevJac** [rust-lang/rust#28545]
https://doc.rust-lang.org/stable/complement-project-faq.html#is-any-part-of-this-thing-production-ready?

The above link states that rust is not production ready. Is this a mistake?

**Comment by petrochenkov** [comment]
I wonder how many people read this FAQ after 1.0 :fearful:

**Comment by steveklabnik** [comment]
Well, we're hoping to re-do the FAQ: https://internals.rust-lang.org/t/rusty-web-improvement-bureau/2572

(I'll send a PR to fix this in the meantime though, nice catch!)

**Comment by briansmith** [comment]
I see that this was merged. But, the website still says the same thing, that Rust isn't production-ready. I think the issue should be re-opened until the website is actually updated. This is an important issue as far as advocacy and community-building goes.

**Comment by steveklabnik** [comment]
They've already made their way to beta, and so will be part of stable as of the next release.

The docs are part of the release, we'd have to cut a 1.5.1 to update this.

**Comment by briansmith** [comment]
OK, thanks for clarifying that. I think it's reasonable to let it ride until 1.5 is released.
