### ISSUE TITLE
llvm 3.6 required? (3.5 allowed by configure)

### ISSUE THREAD

**Issue by mikosdikos** [rust-lang/rust#28547]
Hi, I'm going to try building  rustc 1.3 on an old 32bit debian box - is using the installed llvm 3.5 kosher? 
 
Configure doesn't complain so it should probably be ok?

I'd like to shorten the build time but not get any nasty suprises afterwards.

**Comment by steveklabnik** [comment]
As far as I know, it should work, given that it's in `configure`. And since you've had no problems, seems like everything is okay?

Let us know if it doesn't.

**Comment by mikosdikos** [comment]
I'm following the i386 thread on users, where I'm known as boyshill, and decided to help but someone says this:

https://internals.rust-lang.org/t/building-with-system-llvm/1647

**Comment by mikosdikos** [comment]
I've found an old linux P4 belonging to a friend but still can't devote too much time to installing a new distro.
Maybe you know of some live usb distribution that would allow me to use something newer and avoid this potential issue?
I just want to compile natively, no unsupported archs. 
Thx

**Comment by steveklabnik** [comment]
Okay, I am confused. Are you saying that you've tried with 3.5, and it doesn't work? Or something else?

**Comment by mikosdikos** [comment]
No, in case this could become an issue I simply wanted to work around it by not using this version. If there's no reason  to avoid it I'll get back to you with the result tomorrow.

**Comment by mikosdikos** [comment]
You were right, no problem whatevah - sorry for the fuss!
