### ISSUE TITLE
Macro invocations allow type parameters in the path

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#28558]
`vec::<T,U,V,W::X::Y<Z>>![1,2,3,4];` is valid syntax and compiles to a regular vector.

This is because macros use `Path`s, not `Ident`s as their names. Multi-segment paths are disallowed, but the path can have type parameters.

We can move macros to `Ident`s, however this would not be backwards compatible since anyone using `vec::<T>![1,2]` would get a syntax error (even though the original syntax is meaningless). It's still a bug, so perhaps we can get away with this breaking change.

Thoughts?

cc @eddyb  @alexcrichton

**Comment by eddyb** [comment]
I'd say fix it and do a crater run.

**Comment by alexcrichton** [comment]
Sounds like a plan to me

**Comment by drbo** [comment]
Ping?

**Comment by eddyb** [comment]
@drbo I don't think anyone worked on it.
In case someone wants to work on it, the two relevant points are [type macros](https://github.com/rust-lang/rust/blob/15e8a67c47dc624cc7de67dfa8020a1daefc5067/src/libsyntax/parse/parser.rs#L1463) and [expressions macros](https://github.com/rust-lang/rust/blob/15e8a67c47dc624cc7de67dfa8020a1daefc5067/src/libsyntax/parse/parser.rs#L2339).
It should be possible to error if the path is absolute, has more than one component, or any lifetime/type parameters. We can then do a crater run to see if these are used in the wild for some reason.

**Comment by eddyb** [comment]
cc @jseyfried @petrochenkov @nrc

**Comment by jseyfried** [comment]
I'm on it.

**Comment by jseyfried** [comment]
I fixed this in #34495.
