### ISSUE TITLE
derive(Default) fails on struct using associated type of param.

### ISSUE THREAD

**Issue by jpetkau** [rust-lang/rust#28553]
`#[derive(Default)]` fails on objects that contain a field of an associated type, even if that field is Default.

For example (also https://gist.github.com/4c85bcab2cf9f8c56dc2): 

```rust
trait TR {
  type Assoc : Clone + Copy + Default;
}

#[derive(Clone, Copy, Default)]
struct Foo<T: TR> {
  thing : T::Assoc,
}

impl <T: TR> Foo<T> {
    fn bar() {
        // This works
        let _ : T::Assoc = Default::default();
        // This does not.
        let _ : Foo<T> = Default::default();
    }
}
```

This fails with "error: the trait `core::default::Default` is not implemented for the type `T` [E0277]". Except that we don't *want* a default T, we want a default Node<T>.

Manually implementing Default works as a workaround:
```rust
impl<T: TR> Default for Foo<T> {
    fn default() -> Self { Foo { thing : Default::default() } }
}
```
Happens in 1.3, beta, and nightly as of Sep. 20.

**Comment by eefriedman** [comment]
See also #26925.

**Comment by jpetkau** [comment]
duplicate of #26925.

Thanks, I figured there must be a dup but my search-fu failed.
