### ISSUE TITLE
[libarena::TypedArena::grow()] alloc size increment is fatal with huge numbers (capacity)

### ISSUE THREAD

**Issue by Siassei** [rust-lang/rust#28551]
The size of a TypedArena is automatical increased if the TypedArena is full.
https://github.com/rust-lang/rust/blob/master/src/libarena/lib.rs#L486

The [grow](https://github.com/rust-lang/rust/blob/master/src/libarena/lib.rs#L500-509) function [calculate](https://github.com/rust-lang/rust/blob/master/src/libarena/lib.rs#L503) a new capacity for the next chunk. Each grow call, the size for the next chunk is doubled.
This works fine for small TypedArena sizes. But if capacity is a big number than a huge chunk would be reserved for only ... e.g small number of elements are needed. The maximum size of  [new_capacity](https://github.com/rust-lang/rust/blob/master/src/libarena/lib.rs#L503) must be limited to a maximum size.
It should be added a new field to TypedArena with a default value (e.g. 512) and a function to setup a another value.

**Comment by steveklabnik** [comment]
@rust-lang/compiler, given that this is an internals library, do we want to expand it?

**Comment by eddyb** [comment]
We probably want to fine-tune it for the compiler itself.
One thing we should really do is in-place realloc, because that would let us reuse the same chunks (after a certain size, I believe that in-place realloc will always succeed if there's available virtual memory after it), and we could also get the "actual allocated size" when we allocate a new chunk.

**Comment by nikomatsakis** [comment]
I think this type eventually would have wide-spread utility, but it's not stable now, and it might be that the compiler's patterns are different from other programs. So tuning for the compiler does seem ok, particularly if it makes a noticeable perf improvement.

**Comment by arielb1** [comment]
@nikomatsakis 

`TypedArena` overhead is less than 0.1% of compilation time. Also, on virtual memory systems, overallocation does not actually waste much memory.

**Comment by nikomatsakis** [comment]
@arielb1 

> TypedArena overhead is less than 0.1% of compilation time. Also, on virtual memory systems, overallocation does not actually waste much memory.

from this, should I conclude you feel that any change here is unnecessary?

**Comment by arielb1** [comment]
@nikomatsakis 

Yeah.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this since TypedArena doesn't cause much overhead for the compiler itself (see https://github.com/rust-lang/rust/issues/28551#issuecomment-156723819) so there's no need to track this I think.
