### ISSUE TITLE
Add tests for macro-based impls

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#28561]
A lot of impls for primitives in libcore are done via macros, in lieu of variadic generics. This is done for [tuples](https://github.com/rust-lang/rust/blob/master/src/libcore/tuple.rs), [function pointers](https://github.com/rust-lang/rust/blob/master/src/libcore/ptr.rs#L382), and [arrays](https://github.com/rust-lang/rust/blob/master/src/libcore/array.rs#L175).

However, tweaking these macros can sometimes lead to [regressions like these](https://github.com/rust-lang/rust/issues/28559) (caused by [this tweak](https://github.com/rust-lang/rust/commit/bc7c4304ab2af12e782945f139eb73e4842b9d68)).

We should have some run-pass tests that ensure that the relevant traits are indeed implemented. Something like

```rust
#[derive(Copy,Clone, Eq,PartialEq,Hash,Ord,Debug)]
struct Fn {
    fn0: fn(),
    fn1: fn(u8),
    fn2: fn(u8, u8),
    ...
    fn12: fn(u8, u8, u8 ....)
}
```

for `fn`, and similar for the other macro-impld primitives.

**Comment by Manishearth** [comment]
@apasel422 Interested in working on this?

**Comment by apasel422** [comment]
@Manishearth Sure!
