### ISSUE TITLE
Fat pointer trait implementations

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust#28579]
Currently `Hash` is only implemented for thin pointers, and `Eq`/`PartialEq` aren't implemented for any pointers (but `==` works for all pointers).

All of these traits should be implemented for all pointers.

Without this, it's impossible to implement generic reference-equality semantics that support dynamically sized types, even in unsafe code, thanks to #27570. Even with #27570 it will still be impossible to do safely on stable rust, since `raw::TraitObject` is unstable, and even if it were stable, the type system isn't powerful enough to express when to use `raw::TraitObject` vs a thin pointer.

Fixing this properly will likely require improvements to the type system. Any improvement which solves rust-lang/rfcs#1279 should be enough.

**Comment by arielb1** [comment]
You can "dynamically" `mem::transmute` by using `copy_memory` (and `size_of`).

**Comment by Diggsey** [comment]
That's still unstable, and it's still nontrivial to implement Hash. You *can* do it with unsafe code and size_of, but it's not ideal - this sort of thing should be handled by the standard library so that user code doesn't have to depend on implementation details like the layout of fat pointers.

Without sufficiently smart optimizations, it will also generate sub-optimal code.

When it's possible to write a generic `ReferenceEquality<T: Deref>` wrapper that can be used to key a `HashMap` without requiring unsafe code, then this can be closed.

**Comment by arielb1** [comment]
`Eq` is implemented for all pointers, including fat ones:
```Rust
fn check_eq<T: Eq>(t: T) { t == t; }
fn main() {
    let x: *mut [u8] = &mut [0,1];
    check_eq(x);
}
```

Anyway, why is

**Comment by Diggsey** [comment]
> Eq is implemented for all pointers, including fat ones

Ah, it doesn't show up in rustdoc. I guess it's implemented internally in the compiler or something?

> Anyway, why is

A truly deep question :thought_balloon:

**Comment by arielb1** [comment]
http://doc.rust-lang.org/std/cmp/trait.Eq.html

has

`impl<T> Eq for *const T where T: ?Sized`

The impl (at `https://github.com/rust-lang/rust/blob/master/src/libcore/ptr.rs#L279`) just does `*self == *other` - the real implementation is in trans.

**Comment by arielb1** [comment]
It *would* be nice to have better primitives for accessing the fields of fat pointers, and at least implement `Hash` for them (not in the compiler, obviously, just using memcpy).

**Comment by steveklabnik** [comment]
Triage: 18 months with no comments. It seems that the original issue is in fact not an issue. Closing!
