### ISSUE TITLE
TRPL: Document that Send and Sync are automatically derived

### ISSUE THREAD

**Issue by geofft** [rust-lang/rust#28581]
As far as I can tell, there is no documentation [outside of the _Rustonomicon_](https://doc.rust-lang.org/nomicon/send-and-sync.html) that says that `Send` and `Sync` are automatically derived on datatypes that consist solely of `Send` and `Sync` members, and that all primitives other than raw pointers are `Send + Sync`.

So it is a [natural worry for newcomers](https://www.reddit.com/r/programming/comments/3ltwwf/bjarne_stroustrup_announces_c_core_guidelines/cv9q6lr) that the language is less thread-usable than it is (i.e., that libraries will forget to manually implement `Send + Sync`, and be pathologically safe by being unusable across threads), and it's hard to clarify that. (I only found this part of the 'nomicon through `git grep`; the obvious Google results for 'rust send and sync' didn't have a clear statement that they were automatically derived.)

This might be as easy as copying the two 'nomicon paragraphs starting with "Send and Sync are also automatically derived traits" into concurrency.md or so; there's no nontrivial discussion of unsafety in them. I could also send in a PR adding an example of using a `Send + Sync` struct, if that would be helpful.

**Comment by christopherdumas** [comment]
Does someone need to work on this, or is there already a PR? I'd like to do this.

**Comment by Havvy** [comment]
A PR would link to the issue. Nothing has linked here, so go for it.

**Comment by leodasvacas** [comment]
Perhaps it could go with a mention of `derive`? It seems to be nowhere in the book, and it's another thing most types can get for free.

**Comment by critiqjo** [comment]
Actually, `derive` is documented in the [reference](https://doc.rust-lang.org/nightly/reference.html#derive), which is linked to from [Attributes](https://doc.rust-lang.org/nightly/book/attributes.html) section of the book (see the last para)... :smile:

**Comment by leodasvacas** [comment]
Yes, but still it's nowhere in the book, it's a very common and useful attribute, deserves a mention IMO, and would go well with the Send and Sync stuff in a section or subsection.

**Comment by critiqjo** [comment]
I totally agree that it deserves a mention in the book... But `Send` and `Sync` are automatically derived, so isn't it unrelated to `derive`?

I think it could be mentioned in a new sub-section named "Popular attributes" or something in Attributes section... Open a new issue, @leodasvacas
