### ISSUE TITLE
LLVM assertion with asm! output constraint for "d" on x86 and x86_64

### ISSUE THREAD

**Issue by emberian** [rust-lang/rust#28587]
``` rust
#![feature(asm)]

fn main() {
    let a: usize;

    unsafe {
        asm!("" : "=d"(a) : : : );
    }
}
```

```
vagrant@vagrant-ubuntu-trusty-64:~$ rustc reg-repro.rs 
reg-repro.rs:4:9: 4:10 warning: variable `a` is assigned to, but never used, #[warn(unused_variables)] on by default
reg-repro.rs:4     let a: usize;
                       ^
reg-repro.rs:7:24: 7:25 warning: value assigned to `a` is never read, #[warn(unused_assignments)] on by default
reg-repro.rs:7         asm!("" : "=d"(a) : : : );
                                      ^
note: in expansion of asm!
reg-repro.rs:7:9: 7:35 note: expansion site
rustc: /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/include/llvm/CodeGen/FunctionLoweringInfo.h:169: unsigned int llvm::FunctionLoweringInfo::InitializeRegForValue(const llvm::Value*): Assertion `R == 0 && "Already initialized this value register!"' failed.
```

**Comment by nagisa** [comment]
[Relevant discussion](https://botbot.me/mozilla/rust-internals/2015-09-26/?msg=50583363&page=7)

**Comment by jooert** [comment]
Triage: This doesn't assert anymore but gives a proper error while compiling (see https://is.gd/zIn5HT).

**Comment by Mark-Simulacrum** [comment]
Reproduced today, and as above, no LLVM assertion. E-needstest.

**Comment by varkor** [comment]
There seem to still be issues with this test case on `armhf-gnu`: https://github.com/rust-lang/rust/pull/59046#issuecomment-471196612.

**Comment by Mark-Simulacrum** [comment]
Seems we aren't quite ready for a test case here.

@rustbot modify labels: -E-needstest.

**Comment by lenary** [comment]
The constraint codes in LLVM inline assembly are very target dependent. Any tests using these should be gated by target, which should avoid flakiness, and most flakiness in the constraints will be caused by LLVM and not rustc.

**Comment by Amanieu** [comment]
This issue does not apply to the new `asm!` ([RFC 2850](https://github.com/rust-lang/rfcs/pull/2850)) which validates operand register classes.

The legacy `llvm_asm!` is deprecated and is no longer maintained.
