### ISSUE TITLE
Book: most links in the `Compiler Plugins` section are dead

### ISSUE THREAD

**Issue by tomaka** [rust-lang/rust#28583]
At https://doc.rust-lang.org/book/compiler-plugins.html

All links to the documentation are dead.

**Comment by semmaz** [comment]
That's because they lead to compiler docs that aren't exposed on `doc.rust-lang.org`. I think this should be mentioned somewhere.

**Comment by steveklabnik** [comment]
Yes, this is a known limitation of the current system. We already have another bug open for this somewhere, but thanks!
