### ISSUE TITLE
Failing to build rust 1.3.0

### ISSUE THREAD

**Issue by wkennington** [rust-lang/rust#28594]
I'm trying to update the upstream NixOS/nixpkgs rust compiler and running into some issues in the build process around building libcore. Here is the specific build log https://gist.github.com/wkennington/8d73d37789b4497bd3f1. However, using the same build with the current HEAD source, everything works as expected https://gist.github.com/wkennington/36ce1c2fd4088848c7a8.

**Comment by eefriedman** [comment]
`--enable-local-rust --local-rust-root=$snapshot`

The normal configure process downloads a specific snapshot; compiling rustc using any other snapshot is unsupported.

**Comment by wkennington** [comment]
Oh wow, I just realized im using the new snapshot as opposed to the latest one inside of the tagged release.
