### ISSUE TITLE
Option to control -Werror in makefiles

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#28599]
The existing build rules hardcode `-Werror` flags to gcc.

@jauhien [mentioned](https://internals.rust-lang.org/t/perfecting-rust-packaging/2623/37?u=brson) that Gentoo e.g. might want to control this.

**Comment by brson** [comment]
I'm not sure off hand the best way to make this configurable.

**Comment by dylanmckay** [comment]
What do you think about a `--disable-werror` option to `rust/configure`?

**Comment by alexcrichton** [comment]
Make's gone now, so closing.
