### ISSUE TITLE
trpl: combine Match, Patterns, and "if let" sections

### ISSUE THREAD

**Issue by critiqjo** [rust-lang/rust#28591]
All three of them can be combined into a single "Pattern Matching" section.

Also, none of them mentions about irrefutable patterns:
```rust
struct Point { x: i32 }
let Point { x } = Point { x: 34 };
```

(Ref: [Match](https://doc.rust-lang.org/nightly/book/match.html), [Patterns](https://doc.rust-lang.org/nightly/book/patterns.html), [if let](https://doc.rust-lang.org/nightly/book/if-let.html))

**Comment by steveklabnik** [comment]
Patterns are in more places than just this, though, including things like function arguments.

**Comment by critiqjo** [comment]
Wow! I didn't know that... This works, huh?!
```rust
struct Point { x: i32 }
fn test(Point { x }: Point) {}
```

Anyway, isn't it worth bringing them all together? (no label is added yet, which is why the question)

**Comment by steveklabnik** [comment]
I'm going to bring this up with my editor, we'll see. I'm not a fan, as they're all separate things, but we'll see.

**Comment by critiqjo** [comment]
That's great!

I found that there are a lot more possibilities for grouping, though it may not be a good idea, since it messes up the reading order quiet a bit. Anyway, here goes:

Type System (part I)
- Primitive types
- Structs
- Enums
- Vectors
- Strings

Control Structures
- if
- Loops
- Match

Ownership System
- Ownership
- Borrowing
- Lifetimes

Pattern Matching
- Patterns
- (more ways of matching)
  - if/while let
  - Irrefutable matches

Type System (part II)
- Mutability
- Generics
- Traits
  - Drop
  - Operator overloading
  - Deref coercions
  - #[derive]
- type aliases
- const and static
- Iterators *

Type System (part III)
- Polymorphism (Trait objects)
- Casting between types
- Associated types
- Unsized types
- More traits *
  - FromStr
  - Default
  - Clone and Copy
  - Debug and Display
  - Borrow and AsRef
  - Send and Sync

These groups should not be merged into a single page/file. I think only the summary page should be modified.

Another idea is to tag these pages with the group names and provide a way to browse by tags (an alternate view) (like Wikipedia categories) (may not be worth the effort).

Currently, there are no 3-level deep links, but why? (It might be nicer to split up [Error Handling](https://doc.rust-lang.org/nightly/book/error-handling.html) section to multiple pages.)

(uncategorized)
- Variable bindings
- Functions
- Comments
- Method syntax
- Closures
- UFCS
- Crates and Modules
- Attributes
- Macros
- Raw pointers
- unsafe

**Comment by steveklabnik** [comment]
This ended up very close to the reorganization that we're implementing. https://github.com/rust-lang/book is the current work. Anyway, this is likely to happen there, and isn't likely to happen here, so I'm giving it a close. Thanks again for suggesting this!

**Comment by critiqjo** [comment]
Awesome!! :+1:
