### ISSUE TITLE
Automatically run grammar tests (grammar bot)

### ISSUE THREAD

**Issue by edunham** [rust-lang/rust#28592]
How to grammar tests: `make check-grammar` https://github.com/rust-lang/rust/issues/2234
How to add bot to Travis build matrix: https://github.com/rust-lang/rust/pull/28500

**Comment by alexcrichton** [comment]
cc #15880, I think maybe the original issue? not sure... Has some dependency information though!

**Comment by dns2utf8** [comment]
I would like to take this on.

**Comment by edunham** [comment]
@dns2utf8, thanks for volunteering! Is there anything we can do to help you out here?

**Comment by fhahn** [comment]
@dns2utf8 are you still working on it? If not, I could have a look this weekend.

**Comment by dns2utf8** [comment]
Sorry it took so long. To answer the questions: The bot needs antlr4, bison, flex and all the build tools required for rustc.

As soon as #37607 is merged, a simple `make check-lexer` will run all current test.

If I did it myself I would probably use a docker container with Arch inside.

**Comment by dns2utf8** [comment]
I created the PR #37825 but my local dry-runs failed to compile llvm inside any docker container.

**Comment by steveklabnik** [comment]
Triage: there's the new grammar WG, and they're tracking this themselves, I'm going to close in favor of https://github.com/rust-lang-nursery/wg-grammar/issues/5
