### ISSUE TITLE
Wishlist: Include syntactically complete examples for every example in the rust-lang book.

### ISSUE THREAD

**Issue by rundrop1** [rust-lang/rust#28630]
The book as it is is wonderful, thank you.  I am here to inquire about the possibility of having a second book that includes verbose examples.  I know fn main() was left out of the examples for readability but if each example was syntactically complete I could spend a lot less time wondering what is what since a compile-able example of the feature being explained would allow me to tinker and be fully immersed instead of getting just a gist of it.

If someone is willing to proof my work I am willing to do the lions share of what I'm asking for, if this is a "bad idea", that's ok with me too.  I also think a link to the nightly reference should be one of the first things you find in the book, I didn't know it existed until I heard about it in #rust-offtopic.

**Comment by jonas-schievink** [comment]
You can click on the blue arrow in the top right corner of all (?) code examples to open them in the playpen, they'll also have a `fn main()` if required

**Comment by rundrop1** [comment]
Well that's that! Thank you!
