### ISSUE TITLE
why does rustc on OSX use LC_UNIXTHREAD instead of LC_MAIN?

### ISSUE THREAD

**Issue by m4b** [rust-lang/rust#28641]
I've noticed that `/usr/local/bin/rustc` on OSX (Yosemite in my case) uses the (I believe deprecated) `LC_UNIXTHREAD` load command to specify the entry point and C runtime initialization routines instead of the standard `LC_MAIN`.

Is there a particular reason for this?

**Comment by alexcrichton** [comment]
It looks like `LC_MAIN` was introduced in 10.8 but our nightlies are compatible with (and built on) 10.7 so they don't use it. Note that we don't actually do anything special here, we just get whatever the linker spits out by default. E.g. an executable produced on 10.10 for me uses `LC_MAIN` as I presume you'd expect.
