### ISSUE TITLE
the book attributes page isn't practically useful

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#28643]
The [attributes section](http://doc.rust-lang.org/nightly/book/attributes.html) doesn't cover how these rules are applied to typically used libraries or binaries and should be expanded. For example, why does this case fail? It's trying to apply that feature to the enclosing module which seems reasonable:

```rust
pub mod inner {
    // Not valid. `feature` is only applicable to crates.
    #![feature(step_by)]
    pub fn threes() {
        for i in (0..10).step_by(3) { println!("{}", i); }
    }
}

fn main() {
    inner::threes();
}
```

It would be useful to expand it to include examples that show actual usage patterns like how to enable `#![feature()]`, `#[test]`, and `#[cfg]` patterns on a `lib.rs` and `main.rs` files in a practical fashion. This seems like it would enable people much more than it does currently.

My attempt at answering such a question is [here](https://users.rust-lang.org/t/i-love-rust-but-one-thing-about-modules-is-aweful/2930/35) in case it's useful.

**Comment by sanxiyn** [comment]
On the other hand, we do say this:

```
foo.rs:3:5: 3:25 warning: crate-level attribute should be in the root module, #[warn(unused_attributes)] on by default
foo.rs:3     #![feature(step_by)]
             ^~~~~~~~~~~~~~~~~~~~
```

**Comment by mdinger** [comment]
Yeah, the compiler is pretty helpful but when you go to the book looking for explanations about why, it's slightly lacking in that regard.

**Comment by steveklabnik** [comment]
This is good feedback, but given my work on the next-gen of the book, I'm not likely to fix it. If anyone wants to flesh out this section with more, please feel free!
