### ISSUE TITLE
Missing interactive tour of Rust with problems to solve

### ISSUE THREAD

**Issue by absoludity** [rust-lang/rust#28648]
As a new learner of Rust, I'm reading the book (which is great), but am lacking hands-on problem solving with Rust as I learn. I'd love to see (or help out with) something similar to the [interactive golang tour](https://tour.golang.org/welcome/1).

I'm interested if anyone is already working on something similar. [RustByExample](http://rustbyexample.com/index.html) (which looks great for examples) may have the same intention - and just be lacking some interactive activities for each step.

**Comment by steveklabnik** [comment]
Hey @absoludity ! You're right that we don't have something exactly the same, but Rust By Example does feel like it's almost in the right place.

We keep the issues tracker for just bugs, though, so I'm going to give this a close. If you want others to find out about this, I'd suggest making a post on https://users.rust-lang.org/ , which is more of a discussion forum. Thanks!
