### ISSUE TITLE
HIR: Move lifetime elision to HIR lowering

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#28644]
If we can

**Comment by arielb1** [comment]
@nrc 

it is somewhat hard, as elision can occur in type aliases. This of course all depends on moving resolution.

**Comment by eddyb** [comment]
This seems to assume lifetime elision is a syntactical sugar, when it's actually semantic sugar (it depends on lifetimes in definitions of types).

**Comment by nrc** [comment]
I believe at least some elision is purely syntactic - that could be moved here and the type-dependent stuff left alone. Not sure about the aliases issue.

**Comment by jonas-schievink** [comment]
> This of course all depends on moving resolution.

As far as I can tell, this was done in #33443. Can this now be fully implemented?

**Comment by eddyb** [comment]
@jonas-schievink Hmm, I suppose you can always look at lifetime parameter definitions in custom user types, so this would work. *However*, [the current implementation](https://github.com/rust-lang/rust/blob/master/src/librustc_typeck/rscope.rs) takes advantage of the Debruijn index representation of late-bound lifetimes to avoid actually touching the lifetime parameter definitions.

**Comment by eddyb** [comment]
#39305 did as much as I thought was reasonable, anything more would really pollute lowering.
@nrc are you happy with that progress, for closing this issue?
