### ISSUE TITLE
emphasize that &mut is a distinct type from & in the book

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#28684]
Most if not all the book's discussions on [borrowing](http://doc.rust-lang.org/nightly/book/references-and-borrowing.html) and [mut](http://doc.rust-lang.org/nightly/book/mutability.html) focus on type binding of this sort:

```rust
let i = &mut 3;
let j = &7;
```

[Mutability](http://doc.rust-lang.org/nightly/book/mutability.html#field-level-mutability) even asserts `mut` as not usable in a field via this example:

```rust
struct Point {
    x: i32,
    mut y: i32, // nope
}
```

This led me to conclude `mut` is a property of binding and so assumed the following:

```rust
// Assumed invalid
struct Borrow<'a>(&'a mut i32);
// Assumed the proper way to do this
struct Borrow<'a>(&'a i32);

let i = 3;
// `mut` is added here instead
let b = Borrow(&mut i);
```

The fact that both `&T` and `&mut T` are valid as types and not just as bindings should be emphasized to clarify this.

[EDIT]

Found in [this](https://users.rust-lang.org/t/mutability-affects-lifetime-inference/3008) thread

**Comment by steveklabnik** [comment]
I'm not exactly sure how to emphasize it more, we talk about references and borrowed references as being totally different things a number of times.

**Comment by mdinger** [comment]
Hmm...it might be related me having a pretty decent idea of how things work and so I generally skim the page looking for examples similar to what I'm looking for rather than read it in it's entirety as I might when I first started learning rust.

I suppose what I would do is add a code example to [mut](http://doc.rust-lang.org/nightly/book/mutability.html) with a definition of a struct with a mutable reference with 2 functions, somewhat like this (probably with some extra text around it):

```rust
#[derive(Debug)] struct RefMut<'a>(&'a mut i32);
#[derive(Debug)] struct RefImmut<'a>(&'a i32);

let ref_mut = RefMut(&mut 9);
let ref_immut = RefImmut(&9);

println!("{:?}", ref_mut);
println!("{:?}", ref_immut);
```

Admittedly, this is a pretty weak example but I do think it shows a few things which the page doesn't have yet which are valuable:

* `&mut` is able to be used in a type definition (not strictly as an operator)
* `&mut` in a function definition matches the type definition and isn't just some slight of hand around a `&`.
* It's easy to find via skimming and searching
* The types `&` and `&mut` are able to be contrasted directly
* You could use `let x: &mut i32 = &9;` alternatively but I think actually defining a type is slight more effective

---

If you like the idea but think it needs more work, I can try to mock it up further later if that helps.

**Comment by steveklabnik** [comment]
We haven't covered structs yet in that part of the book, so this example can't work directly. I think I have a solution, though.

**Comment by steveklabnik** [comment]
Actually, I don't. We explicitly talk about the differences between both positions in `let mut x = &mut 5`.

I think, for now, I'm going to chalk this one up to simple confusion. I have been meaning to re-write the mutability section anyway, which would end up invalidating this ticket.

If anyone else is confused in this way, let me know, and we can try to figure out how to make it more clear in the short term.

**Comment by mdinger** [comment]
Yeah, not too big. Punt is okay.
