### ISSUE TITLE
Rules for matching against variable unclear.

### ISSUE THREAD

**Issue by Aaronepower** [rust-lang/rust#28687]
When you have a match statement against a variable the behaviour is unexpected.

[I tried this code:](http://is.gd/7AZ2lx)
```
fn main() {
    let x = 'x';
    let c = 'c';
    match c {
        x => println!("Bug? {} {}", x, c),
    }
    
    println!("x: {}", x)
}
```

#### I expected to to see this happen:

Either get an error telling me that placing a variable won't do what I think it will do. Or allow this to happen, and allow for specific cases, as currently adding any extra arms returns a `unreachable pattern` error.

#### Instead this happened:

This compiles with no errors, or warning, and prints out:
```
Bug? c c
x: x
```

## Meta

`rustc --version --verbose`

```
rustc 1.3.0 (9a92aaf19 2015-09-15)
binary: rustc
commit-hash: 9a92aaf19a64603b02b4130fe52958cc12488900
commit-date: 2015-09-15
host: x86_64-apple-darwin
release: 1.3.0
```

**Comment by bluss** [comment]
You can match against patterns that are composed of: Literals, ranges, Struct constructors, Enum variant constructors and `const` constants.

If you put in an identifier like this it's just a new binding (a catch-all). Rust generally allows variable shadowing without warning (`let x = 1; let x = x + 1` is ok), so this is consistent with that at least.

**Comment by bluss** [comment]
Relevant doc section is [Patterns](http://doc.rust-lang.org/nightly/book/patterns.html). I think it could be clarified around this issue.

**Comment by steveklabnik** [comment]
tagging with docs to see if i can make this somehow more prominent, but I'm not sure.
