### ISSUE TITLE
Constraining associated type of super trait seems impossible

### ISSUE THREAD

**Issue by sellibitze** [rust-lang/rust#28690]
I just tried to do something like this

```rust
use std::ops::{ Deref, DerefMut };

trait Array: Deref + DerefMut where <Self as Deref>::Target = [Self::Item] {
    type Item;
}
```

and various variations of it including

```rust
trait Array: Deref<Target = [Self::Item]> + DerefMut {
    type Item;
}
```

```rust
trait Array: Deref + DerefMut {
    type Item where Self::Target = [Self::Item]; // invalid context for a where clause
}
```

```rust
trait Array where Self: Deref<Target = [Self::Item]> {
    type Item;
}
```

and I don't seem able to express this in a way so that the compiler accepts it. The error message

```
<anon>:3:50: 3:60 error: unsupported cyclic reference between types/traits detected [E0391]
<anon>:3 pub trait SmallArray where Self: Deref<Target = [Self::Item]> {
```

seems a bit too conservative. @eddyb suggested I file an issue for this.

**Comment by arielb1** [comment]
This works:

```Rust
trait Array: Deref<Target = [<Self as Deref>::Item]> + DerefMut {
    type Item;
}
```

**Comment by bluss** [comment]
The `where X = Y` syntax that rustdoc sometimes generates is not valid Rust.

**Comment by sellibitze** [comment]
@arielb1: Thanks. You probably meant "<Self as Array>". At least that works. :)

**Comment by eddyb** [comment]
@arielb1 IMO the error is bogus because the set of supertraits and associated types does not depend on type parameters or even `Self`.

**Comment by arielb1** [comment]
@eddyb 

Locating the trait for the projection's trait-ref requires looking over the supertraits, which causes the cycle.
