### ISSUE TITLE
Tuple struct patterns can match unit structs

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#28692]
This compiles on stable and nightly, but it shouldn't:
```rust
struct S;

fn main() {
    let S(..) = S;
}
```

**Comment by steveklabnik** [comment]
/cc @rust-lang/lang 

This kind of makes sense because `..` is "doesn't matter", but it's not very useful. I'm not sure if we want to disallow it or not.

**Comment by petrochenkov** [comment]
The problem is that "kinds" of structs are different, `()`-structs and `{}`-structs never mix, normally.
I'm working on a fix, it's a direct continuation of https://github.com/rust-lang/rust/pull/28336

**Comment by tbu-** [comment]
I think there was a recent RFC touching this.

**Comment by arielb1** [comment]
@petrochenkov 

You can't match `{ }` structs/variants because they don't have a value namespace entry, only unit structs/variants.

**Comment by durka** [comment]
To be honest, I don't see why `S(..)` can't match a {}-struct as well.

**Comment by arielb1** [comment]
@durka

You will get an `unresolved enum variant, struct or const `S`` error.

**Comment by durka** [comment]
@arielb1 I know it doesn't work, but I don't see why it couldn't be made to work.

**Comment by pnkfelix** [comment]
@durka see https://github.com/rust-lang/rfcs/pull/218 , in particular https://github.com/pnkfelix/rfcs/blob/empty-struct-with-braces-take-2/active/0000-empty-structs-with-braces.md#empty-tuple-structs ; we are allowing unit and braced structs to mix in ways that we do not want to allow tuple structs to mix as well.

**Comment by nikomatsakis** [comment]
Regarding the ability of `S(..)` to matching against a "unit struct", I've always seen this as a feature -- basically a way to enumerate a variant without saying anything about how much data is in it -- but I guess it is a bit fishy, particularly given the distinction between brace and tuple structs. I'm not really sure what my opinion is on this matter yet.

**Comment by petrochenkov** [comment]
@nikomatsakis 
If we follow the route mentioned in https://github.com/rust-lang/rfcs/pull/218#issuecomment-76393168, then `S{..}` will naturally be a "match anything" pattern for structs/variants.
