### ISSUE TITLE
Possible error in example on subtyping and variance in nomicon

### ISSUE THREAD

**Issue by netvl** [rust-lang/rust#28704]
The following piece of code is present at the end of variance chapter in nomicon:

```rust
use std::cell::Cell;

struct Foo<'a, 'b, A: 'a, B: 'b, C, D, E, F, G, H> {
    a: &'a A,     // variant over 'a and A
    b: &'b mut B, // invariant over 'b and B
    c: *const C,  // variant over C
    d: *mut D,    // invariant over D
    e: Vec<E>,    // variant over E
    f: Cell<F>,   // invariant over F
    g: G,         // variant over G
    h1: H,        // would also be variant over H except...
    h2: Cell<H>,  // invariant over H, because invariance wins
}
```

It says that `Foo` is invariant over `'b`, however, all references, mutable included, are variant over their lifetime parameters, as explained earlier in this chapter. Wouldn't then `Foo` be variant over `'b`?

**Comment by jonastepe** [comment]
Just saw that too. It was confusing. I am glad someone already reported it.

**Comment by bluss** [comment]
@netvl You're right.
