### ISSUE TITLE
Clarify a sentence in the Iterators section of the book

### ISSUE THREAD

**Issue by reddraggone9** [rust-lang/rust#28701]
In the [Iterators section](https://github.com/rust-lang/rust/blame/master/src/doc/trpl/iterators.md#L284-L285) of TRPL where it is talking about `take(n)` the page says, "Note that this has no side effect on the original iterator." It's not really clear what this is trying to convey.

**Comment by steveklabnik** [comment]
Yup, I wrote this. Probably should just remove the sentence, I agree.

**Comment by steveklabnik** [comment]
This was fixed
