### ISSUE TITLE
command-line help for -{W,A,D,F} is ambiguous (suggests presence of non-existent 'all' option)

### ISSUE THREAD

**Issue by froydnj** [rust-lang/rust#28708]
I downloaded the rust 1.3.0 distribution; `rustc -W help` says, in part:

```
Available lint options:
    -W <foo>           Warn about <foo>
    -A <foo>           Allow <foo>
    -D <foo>           Deny <foo>
    -F <foo>           Forbid <foo> (deny, and deny all overrides)
```

The documentation here for `-F` suggests to me that `-F all` would be acceptable (perhaps `-W all` or `-A all` too, perhaps).  But that doesn't seem to work; `rustc` says:

```
error: unknown forbid flag: all
error: aborting due to previous error
```

Either adding the `all` group or clarifying the help output around `-F` would be most welcome.  (It's also not immediately clear what the difference between `-D` and `-F` is, especially since `-D` would apparently override the presence of an earlier `-F`...?)

**Comment by pnkfelix** [comment]
Would "deny <foo> and all overrides" be clearer?

**Comment by froydnj** [comment]
I think so, yes.

**Comment by pnkfelix** [comment]
@froydnj in particular, `-F` is meant to prevent embedded uses of `#[allow(..)]` or `#[warn(..)]`, which would normally override a `-D ..` or `#[deny(..)]`

**Comment by froydnj** [comment]
Indeed, stating it that way makes it much clearer what's going on.  I think I was confused by the use of "deny" in multiple contexts here.

**Comment by steveklabnik** [comment]
Triage: no change. Seems easy enough, tagging as such.
