### ISSUE TITLE
make check-stage1 is currently not working

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#28710]
Lots of [discussion](https://internals.rust-lang.org/t/stage1-tests-and-landing-pads/2606/10) as well as [proposed](https://github.com/rust-lang/rust/pull/28206/files) [fixes](https://github.com/rust-lang/rust/pull/27417).

Looks like the best solution for now (from the discuss thread) is to just enable landing pads in all stages instead of just disabling in stage0.

**Comment by nagisa** [comment]
How about `./configure --disable-landing-pads` for buildbot use and `./configure --enable-landing-pads` by default for everybody else?

**Comment by arielb1** [comment]
How about just fixing panics without landing pads?

**Comment by alexcrichton** [comment]
This is quite old, and probably no longer true, so closing.
