### ISSUE TITLE
--emit dep-info is a little difficult to use

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#28716]
The compiler's `dep-info` output doesn't work quite as one might expect when
coming from the land of gcc/clang, for example:

1. If only a `dep-info` file is generated, the output filename is pretty
   unlikely to what's going to be compiled later on:

  ```
  $ rustc foo.rs --emit dep-info
  $ ls
  foo.d  foo.rs
  ```

2. If a dep-info and link file are generated, you can't customize the output
   filename of the dep-info file:

  ```
  $ rustc foo.rs --emit dep-info,link -o foo.pp
  warning: ignoring specified output filename because multiple outputs were requested
  $ ls
  foo.d       foo.rs      libfoo.rlib
  ```

The compiler probably wants the ability to specify a dedicated location for the dep-info file during the same compilation of a staticlib or executable. For example, something like:

```
    --dep-file FILE     Configure output location of the dep-info output
```

This would allow customizing the output location as well as enabling dep-info to know what the actual output artifact is (e.g. of the `link` output type).

Some more info can be found on [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1208566).

**Comment by apasel422** [comment]
`Session`'s `write_dependency_info` field actually has an `Option<PathBuf>` that represents a specified output filename, but it doesn't appear to be set anywhere.

**Comment by apasel422** [comment]
[The comments in librustc_driver/driver.rs](https://github.com/rust-lang/rust/blob/d3fc6e1858f6882bc9bd14641420bf3c4f7ee86b/src/librustc_driver/driver.rs#L870-L873) refer to some obsolete flags:
```rust
// Write out dependency rules to the dep-info file if requested with
// --dep-info
let deps_filename = match sess.opts.write_dependency_info {
    // Use filename from --dep-file argument if given
```

**Comment by alexcrichton** [comment]
Yeah these flags have gone through some various iterations over time, and it's probably high time to refactor all this support in the compiler!
