### ISSUE TITLE
cfg_target_features not working

### ISSUE THREAD

**Issue by valarauca** [rust-lang/rust#28718]
How to replicate:

       $git clone https://github.com/valarauca/getcup.git
       $cd getcup
       $cargo build
       $target/debug/getcup
          SSE2 compatible

Doesn't matter what order the flags are in. 

Tested on Linux 3.19.0-28, x86_64, i7-4790, built with rustc 1.5.0-nightly (7bf4c885f 2015-09-26)

Tested on OSX Darwin 14.5.0 x86_64 i5-5257U, build with rustc 1.5.0-nightly (7bf4c885f 2015-09-26)

Neither of these will get a valid target_feature="avx"

**Comment by alexcrichton** [comment]
I believe that this is currently the case because LLVM disables these extra CPU features by default. You'll have to pass `-C target-feature=...` flags to get LLVM to enable code generation for the various platforms. I think you can also use `-C target-cpu=native` for selecting the native CPU as well.

As this isn't a bug in the compiler, however, I'm gonna close this. Thanks for the report though!

**Comment by valarauca** [comment]
Here were the results

      $rustc main.rs -C target-feature="avx"
       'avx' is not a recognized processor for this target (ignoring processor)

It prints the error message 40 times

      $ rustc main.rs -C target-feature=avx
         c/llvm/lib/MC/SubtargetFeature.cpp:197: llvm::FeatureBitse
         llvm::SubtargetFeatures::ApplyFeatureFlag(llvm::FeatureBitset, llvm::StringRef,
         llvm::ArrayRef<llvm::SubtargetFeatureKV>): Assertion `hasFlag(Feature)' failed. 
          Aborted (core dumped)

Well okay. So when I pass in the normal gnu target string

         $rustc main.rs -C target-feature=corei7-avx
         c/llvm/lib/MC/SubtargetFeature.cpp:197: llvm::FeatureBitse
         llvm::SubtargetFeatures::ApplyFeatureFlag(llvm::FeatureBitset, llvm::StringRef,
         llvm::ArrayRef<llvm::SubtargetFeatureKV>): Assertion `hasFlag(Feature)' failed. 
          Aborted (core dumped)

So I try the target-cpu

         $rustc main.rs -C target-cpu=native

Compile works so I run it

            SSE2

So now I try to pass the gnu processor arg string

           $rustc main.rs -C target-cpu=corei7-avx

Compile works so I run it

            SSE2

**Comment by alexcrichton** [comment]
Ah that's right currently `cfg(target_feature)` doesn't take into account the CPU, it goes through different paths than LLVM currently. For enabling features though the syntax is `+avx` as opposed to `avx` which should do the trick!

**Comment by valarauca** [comment]
Hey prefect thank you!
