### ISSUE TITLE
Rustdoc does not compile code pieces if they are not separated from the surrounding text

### ISSUE THREAD

**Issue by netvl** [rust-lang/rust#28712]
The following is a perfectly valid Markdown, however, Rustdoc does not compile the piece of code (and, naturally, it is not run as a test with `cargo test`):

`````` rust
/// This is a test:
/// ```rust
/// let x = SomeUnknownStructure::new();
/// ```
``````

This, however, does work:

`````` rust
/// This is a test:
///
/// ```rust
/// let x = SomeUnknownStructure::new();
/// ```
``````

(that is, it fails to compile due to unknown symbol `SomeUnknownStructure`).

Note the empty line before the code block in the doc comment.

**Comment by Aatch** [comment]
Does it render correctly? If not it may be a bug in the mardown parser.

**Comment by netvl** [comment]
It looks like that it also renders incorrectly:
<img width="1021" alt="screen shot 2015-09-30 at 12 05 49" src="https://cloud.githubusercontent.com/assets/280456/10188894/9f1c6a7a-676b-11e5-93d4-0020d74a342c.png">
This is for the first snippet from the original post, the second snippet looks correctly.

**Comment by sfackler** [comment]
This is how at least some markdown parsers work - without a double line break before the tick marks, it's treated as part of the previous paragraph.

**Comment by Aatch** [comment]
The decision now then is whether we consider this working-as-expected or an actual bug?

**Comment by steveklabnik** [comment]
CommonMark says

> A fenced code block may interrupt a paragraph, and does not require a blank line either before or after.

http://spec.commonmark.org/0.22/#code-fence

So I would argue it is a bug.

**Comment by insaneinside** [comment]
Also affects lists.
> In CommonMark, a list can interrupt a paragraph. That is, no blank line is needed to separate a paragraph from a following list:

[http://spec.commonmark.org/0.24/#lists]()

**Comment by Mark-Simulacrum** [comment]
With `-Zunstable-options --enable-commonmark`, rustdoc emits the following today, so I'm going to close this.

```
WARNING: test.rs - main (line 2) Code block is not currently run as a test, but will in future versions of rustdoc. Please ensure this code block is a runnable test, or use the `ignore` directive.
```

```
/// This is a test:
/// ```rust
/// let x = SomeUnknownStructure::new();
/// ```
pub fn main() {}
```
