### ISSUE TITLE
Add high level summary at the top of crates/modules in the book

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#28739]
[crates and modules](http://doc.rust-lang.org/nightly/book/crates-and-modules.html) has a lot of info which is buried deep in the text. It'd be good to have a few major points that the text covers highlighted at the top, perhaps with bullet points or something.

* The crate is the compilation unit; modules are subordinate to the crate
* One cargo unit typically contains up to 2 crates:
  - a `lib.rs` crate for the library
  - a `main.rs` crate for the binary
* Interaction across crates is handled via `extern crate` command
* `mod foo.rs` and `mod foo { ... }` are equivalent except:
  - `mod { ... }` puts the contents inside the braces
  - `mod foo.rs;` requests `cargo` find the contents in either:
    * `foo.rs`
    * `foo/mod.rs`
* Modules are private by default. Make them public with `pub`
* Namespace importation is handled via `use`:
  - Relative paths:
    * `use foo::bar`;: use `bar` inside of `foo`
    * `use foo::bar::baz;`: use `baz` inside of `bar` inside of `foo`
    * `use foo::{bar, baz};`: use `bar` and `baz` which are both inside `foo`
    * `use foo::*;`: use all names inside `foo`
    * `use foo::{self, bar};`: use `bar` inside `foo` and module `foo`
  - Absolute paths:
    * `use ::foo::bar;` use `bar` inside of `foo` which is at the crate root
  - Renames are allowed:
    * `use foo as tofu;`: use `foo` under the name `tofu`

I tried to skim the page looking for all the major points. Maybe I grabbed too many but if this table was at the top, it might help people not miss things so easily. Probably would be useful other places too.

**Comment by mdinger** [comment]
See [users](https://users.rust-lang.org/t/i-love-rust-but-one-thing-about-modules-is-aweful/2930) for where this idea came from

**Comment by steveklabnik** [comment]
I'm tagging with "book" because I would like to have this kind of thing integrated into rustbook somehow. The Errors chapter is also long, and has a summary, but it feels very..odd

**Comment by mdinger** [comment]
@steveklabnik Could you clarify what you mean? I'm interpreting your statement to say the tooling needs to improve to autogenerate major points or have an optional `prelude` section covering something of this sort perhaps in a second file. I ask because it seems a having a `## Prelude` section would suffice and I'm not sure why this wouldn't be the recommended way.

**Comment by steveklabnik** [comment]
>  I'm interpreting your statement to say the tooling needs to improve to autogenerate major points

Yes, I think this is probably the best path.

>  I ask because it seems a having a ## Prelude section would suffice and I'm not sure why this wouldn't be the recommended way.

Well, a table of contents is the whole overview, but Rustbook only understands a "chapter" and "first subheading", not the entire TOC. If the tool handled this, it would get auto-updated when things change, etc. It's a basic "code generated vs manual" kind of thing.

We could do `##Prelude` as a stopgap, I guess...

**Comment by mdinger** [comment]
Okay, so I guess the tooling would need to be able to pick out something flagged with `@HIGHLIGHT` or something similar because it seems difficult to autogenerate major points without help otherwise.

**Comment by steveklabnik** [comment]
Given the work on the new book, this isn't likely to get fixed, as I'm not really planning on modifying the existing chapter. Since I'm not going to do it, I'm going to give this a close, but if someone wants to do it themselves, feel free to submit a PR.
