### ISSUE TITLE
std::fs::OpenOptions::mode() is affected by the current umask

### ISSUE THREAD

**Issue by BlacklightShining** [rust-lang/rust#28747]
Just what it says on the tin. I'm not sure if this is intentional, but if it is, there should definitely be a way to open a file with an unmasked mode.

`rustc --version --verbose`:

```
rustc 1.3.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-apple-darwin
release: 1.3.0
```

**Comment by nagisa** [comment]
I… don’t think there’s an atomic way to ignore the umask in `open(2)`.

Best thing you/we could do is calling `umask(2)` with `0`, creating the file and restoring the umask afterwards; but that pretty much circumvents the reason umask exists and exposes us to races (something we’ve been trying to prevent).

**Comment by alexcrichton** [comment]
I agree with @nagisa that pairing together a `umask` call with an `open` call is probably something we don't want to do (e.g. the atomicity concerns), and it's something that could always be done by the caller.

Is there, however, an API like `open` that ignores umask? If so it seems reasonable to bind it. If not then this is probably a "working as intended" sort of issue.

**Comment by BlacklightShining** [comment]
How do you even call `umask()` from Rust? Searching the docs for `umask` turns up nothing.

**Comment by nagisa** [comment]
Via liblibc (if it is bound there) or by binding it itself.

Exposing umask in some form in std::os::unix might be a good feature
request, though.

**Comment by steveklabnik** [comment]
Given that nobody has commented on this in a long time, and it seems like we don't want to change anything here, I'm giving this a close. Thanks!
