### ISSUE TITLE
Toggle stack unwinding without printing error message

### ISSUE THREAD

**Issue by zonyitoo** [rust-lang/rust#28752]
Is it possible to toggle stack unwinding without printing error message to stderr?

I am working on a coroutine library and I want to manually unwind the stack when destroying coroutines. But now I could only use `panic!` to do the trick.

**Comment by jonas-schievink** [comment]
Not possible at the moment, but there's an RFC that should allow what you want: rust-lang/rfcs#1100

**Comment by alexcrichton** [comment]
Thanks for the report! Right now the standard library doesn't support this sort of functionality, but it's available [externally on crates.io](https://crates.io/crates/backtrace). We may want to include this in the standard library at some point, but that's handled through RFCs and/or the nursery, so I'm going to close this issue.

**Comment by alexcrichton** [comment]
Wait holy cow I totally misinterpreted this. @jonas-schievink was spot on, however, so I'll still leave this closed in favor of that RFC
