### ISSUE TITLE
Possible wrong "value assigned to `something` is never read" warning

### ISSUE THREAD

**Issue by Daiver** [rust-lang/rust#28774]
I learning rust and write my own simple macros.
(This macros just fills my matrix like vec! fills Vec<T>)

    #[derive(Debug)]
    struct MatrixXf
    {
        rows: usize,
        cols: usize,
        values: Vec<f32>
    }

    macro_rules! mat {
        [ $($( $x: expr ),*);* ] => {{
            let mut tmp_vec = Vec::new();
            let mut rows = 0;
            let mut cols = 0;
            let mut is_first_row_collected = false;
            $(
                let mut inner_cols = 0;
                $(
                    tmp_vec.push($x);
                    inner_cols += 1;
                )*
                if is_first_row_collected {
                    assert!(inner_cols == cols);
                } else {
                    is_first_row_collected = true;
                    cols = inner_cols;
                }
                rows += 1;
            )*
            MatrixXf{
                values: tmp_vec, 
                rows: rows,
                cols: cols
            }
        }}
    }

    fn main()
    {
        let m = mat![1.0, 2.0, 3.0; 4.0, 5.0, 6.0];
        println!("{:?}", m);
    }

Everything works well but compiler shows me following warning

    bugreportpreview.rs:24:17: 24:39 warning: value assigned to `is_first_row_collected` is never read, #[warn(unused_assignments)] on by default
    bugreportpreview.rs:24                 is_first_row_collected = true;
                                           ^~~~~~~~~~~~~~~~~~~~~~
    bugreportpreview.rs:9:1: 35:2 note: in expansion of mat!
    bugreportpreview.rs:39:13: 39:47 note: expansion site

But i use `is_first_row_collected` here:

     if is_first_row_collected {

Compiler info:

    rustc --version --verbose
    rustc 1.3.0 (9a92aaf19 2015-09-15)
    binary: rustc
    commit-hash: 9a92aaf19a64603b02b4130fe52958cc12488900
    commit-date: 2015-09-15
    host: x86_64-unknown-linux-gnu
    release: 1.3.0

PS Sorry for my poor English

**Comment by jonas-schievink** [comment]
Your code expands to something that contains this:

```rust
if is_first_row_collected {
    assert!(inner_cols == cols);
} else {
    is_first_row_collected = true;
    cols = inner_cols;
}
rows += 1;

let m = MatrixXf{
    values: tmp_vec, 
    rows: rows,
    cols: cols
};
```

Since `is_first_row_collected` is assigned in the `else` branch but never used afterwards (only before), the Lint is indeed correct.

**Comment by Daiver** [comment]
Thank you. I thought about `$(...)*` as kind of loop but it is expansion
