### ISSUE TITLE
There should be a Box<Error+Send+Sync> -> Box<Error> From conversion

### ISSUE THREAD

**Issue by talchas** [rust-lang/rust#28773]
This conversion is done implicitly, but implicit conversions aren't done in generic lookup. This means that

``` rust
fn foo() -> Result<(), Box<Error + Send + Sync>> { try!(Err("foo")) }
fn bar() -> Result<(), Box<Error>> { try!(foo()); }
```

will fail, which is obnoxious and means adding these bounds in a library is not just a theoretical breaking change, but one that will happen. The impl would be trivial.

**Comment by jonas-schievink** [comment]
I could also imagine implicit coercions from `Box<A + B>` to `Box<A>` and `Box<B>` to work quite well in general.

Tangentially related: #28326 and rust-lang/rfcs#1277

**Comment by steveklabnik** [comment]
Triage: trivial impls like this can be done via PR; please send one in if this is still needed, thanks!
