### ISSUE TITLE
Hidden type shows up in rustdoc

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#28800]
On https://doc.rust-lang.org/stable/std/cmp/trait.Ord.html and other pages, one might find implementors such as:

```rust
impl Ord for Big32x36
impl Ord for Big8x3
```

But these types are not exported and should be hidden from the documentation.

**Comment by rkruppe** [comment]
Note: Technically these types are accessible &mdash; as in, with the proper `#![feature()]` you can use them &mdash; but they are inside a `#[doc(hidden)]` module and not re-exported from there.

**Comment by mitaa** [comment]
These aren't shown anymore since #31903
