### ISSUE TITLE
Regression in type inference of casting in constants

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#28801]
This works in stable, beta and nightly:
```rust
let x: *mut () = (0 as *const usize) as *const _ as *mut _;
```

This only works in stable:
```rust
const x: *mut () = (0 as *const usize) as *const _ as *mut _;
```

But in beta and nightly results in:
```
<anon>:2:47: 2:55 error: unable to infer enough type information about `_`; type annotations or generic parameter binding required [E0282]
<anon>:2     const x: *mut () = (0 as *const usize) as *const _ as *mut _;
```

**Comment by alexcrichton** [comment]
triage: I-nominated

**Comment by arielb1** [comment]
This compiles with `rustc 1.5.0-nightly (168a23ebe 2015-10-01)` and `1.3.0`, but not `1.4.0` Should we bisect?

**Comment by arielb1** [comment]
This looks to be fixed by #28131. Should I beta-nominate that?

**Comment by alexcrichton** [comment]
@arielb1 yeah I'll beta-nominate that, thanks for the investigation!

**Comment by alexcrichton** [comment]
Also removing I-nominated as this should be dealt with by the beta-nomination

**Comment by alexcrichton** [comment]
Thanks for the report again @jethrogb! I'm gonna close this in favor of the beta nomination over at #28131 now.
