### ISSUE TITLE
Unclear description in closure section of Rust Book

### ISSUE THREAD

**Issue by billmurphy5th** [rust-lang/rust#28803]
The first section on https://doc.rust-lang.org/stable/book/closures.html can be difficult to understand for novice programmers, particularly the line "Anonymous functions that have an associated environment are called ‘closures’, because they close over an environment."  It's difficult from this context to understand what "environment" is referring to.

**Comment by steveklabnik** [comment]
Yeah, this definition is kind of embarassingly self-referential :sweat:

**Comment by chills42** [comment]
I'm going to try to clarify this.

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/28856 fixed this
