### ISSUE TITLE
Audit iterator specializations for side effects

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#28810]
After some discussion about https://github.com/rust-lang/rust/pull/28125 the libs subteam decided that iterator adaptors should always preserve the same semantics in terms of the convenience methods and such. This was not audited for when all the initial specializations landed, so we should take a look and make sure that everything adheres to this policy.

Additionally, documentation should be added to the `Iterator` trait methods indicating what form of guarantees you are given (e.g. calling `last` is equivalent to exhausting the iterator).

triage: I-nominated

**Comment by Stebalien** [comment]
I've checked `libcore/iter.rs`. `core::iter::Chain::last` should exhaust `a` before `b` but that's the only bug I found (and it wasn't my bug for once :smile:).

Unless, of course, you care about drop order. I haven't tried to reason about that.

**Comment by Stebalien** [comment]
The slice iterators (`libcore/slice.rs`) are fine because they are side-effect free.

**Comment by Stebalien** [comment]
`libcollections/vec` and `libcore/str` are fine because they are also side-effect free.

**Comment by Stebalien** [comment]
I'd appreciate it if someone else double checked but I think that's all of them.

**Comment by nagisa** [comment]
> Unless, of course, you care about drop order.

This is relevant as well, because implementations of Drop may also (and usually do, in form of memory deallocation) contain side effects.

**Comment by Stebalien** [comment]
> This is relevant as well, because implementations of Drop may also (and usually do, in form of memory deallocation) contain side effects.

I strongly disagree. Drop has side effects but programmers should never rely on drop *order* except stack drop order because drop order is often unspecified (e.g. within structs).

----

# Drop out of order

* core::iter::Chain::last
* core::iter::Peekable::last
* core::iter::Skip::last (fixable?)

# Audited

* [x] core::iter::Chain
* [x] core::iter::Enumerate
* [x] core::iter::Peekable
* [x] core::iter::Skip
* [x] core::iter::Take
* [x] core::iter::Fuse
* [x] core::str::Bytes
* [x] core::slice::Iter
* [x] core::slice::IterMut
* [x] core::slice::Windows
* [x] core::slice::Chunks
* [x] core::slice::ChunksMut
* [x] collections::vec::IntoIter

**Comment by nagisa** [comment]
> I strongly disagree. Drop has side effects but programmers should never rely on drop order except stack drop order because drop order is often unspecified (e.g. within structs).

Ah right, this will be decided by https://github.com/rust-lang/rfcs/issues/744#issuecomment-132251327 anyway.

**Comment by alexcrichton** [comment]
Awesome, thanks for the work here @Stebalien!

**Comment by Stebalien** [comment]
Updated list of out-of-order drops (didn't notice `Peekable::count`).

**Comment by alexcrichton** [comment]
triage: P-medium

**Comment by aturon** [comment]
(Need to make sure this behavior is documented/explicitly promised.)

**Comment by huonw** [comment]
Is this done? (Everything in the list above is :white_check_mark:'d)

**Comment by Stebalien** [comment]
I believe this is left open as to-be-documented. Also, I don't see any decision as to whether out of order drop is ok.

**Comment by steveklabnik** [comment]
re-tagging as docs

**Comment by steveklabnik** [comment]
So I believe that all of these are then documented in Iterator's methods, at least as far as I can tell. Can someone from libs double check me here and help provide any specifics as to what's not documented?

**Comment by alexcrichton** [comment]
Looks good to me, thanks @steveklabnik!
