### ISSUE TITLE
const fn with `_` as an arg name vomits

### ISSUE THREAD

**Issue by Gankro** [rust-lang/rust#28822]
## Doesn't work:

```rust
#![feature(const_fn)]
fn main(){}
const fn size_ofs(_: usize) { }
```

```
<anon>:3:19: 3:20 error: arguments of constant functions can only be immutable by-value bindings [E0022]
<anon>:3 const fn size_ofs(_: usize) { }
                           ^
<anon>:3:19: 3:20 help: see the detailed explanation for E0022
error: aborting due to previous error
playpen: application terminated with error code 101
```

-----

## Works:

```rust
#![feature(const_fn)]
fn main(){}
const fn size_ofs(_foo: usize) { }
```

```
<anon>:3:1: 3:35 warning: function is never used: `size_ofs`, #[warn(dead_code)] on by default
<anon>:3 const fn size_ofs(_foo: usize) { }
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Manishearth** [comment]
Willing to mentor this.

Fix is simple, just need to check for [`PatWild`](http://manishearth.github.io/rust-internals-docs/rustc_front/hir/enum.Pat_.html#variant.PatWild) [where E0022 is emitted](https://github.com/rust-lang/rust/blob/e82faeb65594302897223b2ca4ee6927fb54625f/src/librustc/middle/check_const.rs#L179).

**Comment by GlenDC** [comment]
I've been willing for a long time to start getting involved in some contributions to Rust, so if it's ok for you I would like to give this one a go and make it my first contribution.

**Comment by Manishearth** [comment]
Go ahead!
