### ISSUE TITLE
Macro designators listed but not explained

### ISSUE THREAD

**Issue by locks** [rust-lang/rust#28824]
In https://doc.rust-lang.org/reference.html#macro-by-example the various designators available for macro construction are listed, but they are not explained. The closest I could find was https://danielkeep.github.io/practical-intro-to-macros.html:

![Macro designators](https://cloud.githubusercontent.com/assets/32344/10262849/0d301c20-69d1-11e5-858a-9ed834410d4c.png)

I am willing to take a stab at it with some guidance.

**Comment by steveklabnik** [comment]
I am bad at macros, but yes, this should be explained more.
