### ISSUE TITLE
Avoid use of 'just' in trpl

### ISSUE THREAD

**Issue by Charlotteis** [rust-lang/rust#28835]
Hi! I'm just reading through The Rust Programming Language Book (TRPL) and I noticed usage of the word 'just' a few times: "e.g. just install this thing". I've written a bit on this word but to keep it short; I feel that this is quite a loaded word and we could do better without it. In most cases, the work could be to remove 'just' where appropriate from the book, where I often then realise its use wasn't needed at all.

Somewhere else I wrote, which gives some explanation of my reasoning:

> Avoid use of "easy", "simple" and "just". If you tell me something is easy and I don't understand it, I feel alienated. What is easy to you is not easy to other people. 

PS. I took me a long time to find the TRPL source, and maybe we could add a link to the source in the book itself at the beginning? I'm not familiar with the pull request process here (and judging by the CONTRIBUTING.md it's a lengthy one!) so I didn't feel confident to jump in and do it myself (yet?).

Stay cool, thank you for the book!

☀️

**Comment by steveklabnik** [comment]
Thank you! I agree very strongly, bad habits die hard. :(

The front page of the book, the very first subheading, says "contributing" and has a link. Can we do something to make it more prominent?

>  I didn't feel confident to jump in and do it myself (yet?).

Most of that stuff relates to code changes. The book workflow is largely just "please send in a PR." We do have some standards, but that's exactly what review is for, so don't worry about it too much.

**Comment by Charlotteis** [comment]
@steveklabnik Hi Steve!

I admit I must have forgotten about that subheading, because I was knee deep into the `guessing_game` by this point :) So, apologies for that and I don't think anything else needs to be done.

If the book workflow is simpler as you say, I am happy to start helping with this on a page by page basis. Of course, other people could join in too. I'd love to contribute to this.

🎉

**Comment by steveklabnik** [comment]
>  So, apologies for that and I don't think anything else needs to be done.

:+1: it's all good. Especially with a 300 page document, it's hard to remember it all...

> I'd love to contribute to this.

Please do! I will work on other things and let you take this.
