### ISSUE TITLE
four-byte uncode characters confuse `'`

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#28851]
This Rust program:

```
fn main() {
    let len = 'ஶ்ரீ'.len_utf8();
}
```

contains `TAMIL SYLLABLE SHRII (śrī)`, aka `U+0BB6 U+0BCD U+0BB0 U+0BC0`. When trying to compile this program, I get this error:

```text
2:20: 2:22 error: unterminated character constant: '.
2     let len = 'ஶ்ரீ'.len_utf8();
```

I know that it isn't a copy-paste issue, because I used vim's `C-V u` to type in the four code points manually.

**Comment by arielb1** [comment]
Aren't `char`-s unicode scalar values?

**Comment by steveklabnik** [comment]
@arielb1 yes. up to four bytes. am I doing something wrong here? I am bad at encodings, so this is likely.

**Comment by arielb1** [comment]
@steveklabnik 

Unicode scalar value != character.

**Comment by steveklabnik** [comment]
Yes, but it's four bytes, no?

**Comment by steveklabnik** [comment]
Ahhh this isn't actually four bytes. Sigh. Thanks.

**Comment by steveklabnik** [comment]
(basically, I thought that those four things were four bytes, but they're four codepoints themselves)

**Comment by steveklabnik** [comment]
Actually, I am re-opening, because this diagnostic message is really bad. It should say that you're putting something that's larger than a single USV into a char literal.
