### ISSUE TITLE
Use proper spans in ext::tt::transcribe

### ISSUE THREAD

**Issue by catamorphism** [rust-lang/rust#2887]
Several FIXMEs (formerly TODOs) there that mention using the correct spans for different errors.

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by Manishearth** [comment]
@nrc Is this still an issue?

**Comment by nrc** [comment]
yes

**Comment by Mark-Simulacrum** [comment]
@nrc Did #31089 address this? The description of that PR mentions that it partially addressed this, but I don't know to what extent.

**Comment by nrc** [comment]
cc @pnkfelix, but I don't think this issue is entirely fixed, we still use some bad spans, that PR just fixed one case of them.

**Comment by Mark-Simulacrum** [comment]
@jseyfried You've done a lot of work on this file recently, perhaps you could comment if there's still more to be done with the spans? `src/libsyntax/ext/tt/transcribe.rs` is the file for reference.

**Comment by jseyfried** [comment]
I'm not familiar with the details off the top of my head, but IIRC there are comments about spans that could use improvements in the file.

**Comment by Mark-Simulacrum** [comment]
That memory was correct; there are many FIXME comments in the file.

**Comment by steveklabnik** [comment]
There are now four FIXMEs in that file. No idea if that's few enough for this ticket or not.

**Comment by mark-i-m** [comment]
If #60620 is correct and gets merged, we would be down to just one FIXME and it is about hygiene.

Specifically, when transcribing a MBE, when we replace a meta-variable with a matched nonterminal, currently:
- If the meta-variable was a `:tt`, we don't do anything to the syntax context of token trees (`$x:tt`).
- If the meta-variable is any other type of nonterminal, we apply the mark of the current expansion to the span of the nonterminal.

Why the distinction?

cc @petrochenkov

**Comment by petrochenkov** [comment]
>Why the distinction?

https://github.com/rust-lang/rust/pull/78603 has an answer for this question.
