### ISSUE TITLE
cargo new --vcs git doesn't init a branch, if alread inside a tree

### ISSUE THREAD

**Issue by sourcefrog** [rust-lang/rust#28879]
I was slightly surprised by this:

```
% cd /tmp
% git init a
Initialized empty Git repository in /private/tmp/a/.git/
% cd a/
% cargo new --vcs git -v --bin b
% ls -a b
.		..		Cargo.toml	src
```

Perhaps this is working as intended but I would have liked at least a warning.

**Comment by jdm** [comment]
Could you file this in https://github.com/rust-lang/cargo instead?

**Comment by sourcefrog** [comment]
ah it's a dupe of https://github.com/rust-lang/cargo/pull/1969 anyhow
