### ISSUE TITLE
Improving installation on local directory by updating LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by jlmenut** [rust-lang/rust#28917]
When installing rust in a local directory on linux (not /usr/local but /home/name/rust for example), it is necessary to update LD_LIBRARY_PATH with the path to the rust libraries.

For example, in bash:
> export LD_LIBRARY_PATH="/path/to/library":$LD_LIBRARY_PATH

An improvement of rustup.sh would be to make the installer update the shell configuration file or at least warn the user to update it.

**Comment by mzabaluev** [comment]
Please, no modifications of `LD_LIBRARY_PATH` for the whole user account or system-wide, without the installing user's explicit knowledge.

That said, it would be nice to print out a reminder note about `LD_LIBRARY_PATH` (and maybe `PATH` too) when Rust is installed under a custom prefix.

**Comment by jlmenut** [comment]
Of course the installer should not change  ```LD_LIBRARY_PATH``` without  his agreement but it could ask for it and update the rc file if the user choose ```yes```. You're right about ```path```

**Comment by daniel-vainsencher** [comment]
Just had to discover this issue and do it myself, took a few tries. A "just paste this into .bashrc" reminder would have saved time!

**Comment by brson** [comment]
I agree the installer should make the suggestion in a way that can be copy-pasted into .bashrc. I think it used to do this, but I may have deleted it at some point.

**Comment by steveklabnik** [comment]
@brson what's the right place for these kinds of issues these days? The mutlrust-rs projects? Is there a repository for the "new rustup"?

**Comment by alexcrichton** [comment]
rpath is enabled by default, so no longer necessary
