### ISSUE TITLE
Illegal instruction when building rust 1.3 on Debian 8 Jessie 64bits and using system-wide LLVM 3.5

### ISSUE THREAD

**Issue by hartmel** [rust-lang/rust#28918]
When building rust 1.3 on debian Jessie 64-bit __with the LLVM software provided by the distribution__, compilation fails with an illegal instruction error. When rust is built with the bundled LLVM, no error occurs.
Rust Build has been configured with : `./configure --prefix=/opt/rust/gcc-localllvm --llvm-root=/usr/lib/llvm-3.5`. Debian Jessie comes with llvm-3.5, no higher version is available from official repositories.

The last lines of the log are : 
```shell
rustc: x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_typeck
rustc: x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_resolve
rustc: x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_trans
Illegal instruction
/home/user/rust/gcc-locallvm/rustc-1.3.0/mk/target.mk:171: recipe for target 'x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/stamp.rustc_trans' failed
make: *** [x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/stamp.rustc_trans] Error 132
```
Running `make --trace` gave the faulty command line : 
```shell
CFG_LLVM_LINKAGE_FILE=/home/user/rust/gcc-locallvm/rustc-1.3.0/x86_64-unknown-linux-gnu/rt/llvmdeps.rs LD_LIBRARY_PATH=/home/user/rust/gcc-locallvm/rustc-1.3.0/x86_64-unknown-linux-gnu/stage1/lib:$LD_LIBRARY_PATH   x86_64-unknown-linux-gnu/stage1/bin/rustc --cfg stage1  -O --cfg rtopt -C prefer-dynamic --target=x86_64-unknown-linux-gnu  -D warnings -L "x86_64-unknown-linux-gnu/rt" -L "/usr/lib/llvm-3.5/lib"    --out-dir x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib -C extra-filename=-7e44814b src/librustc_trans/lib.rs
```
Running the same command without the "-O" flags works.
Running the same command with -C opt-level=0 works.
Running the same command with -C opt-level=1 fails.

**Comment by alexcrichton** [comment]
Unfortunately there were bug fixes in LLVM since 3.5 was released which we are currently relying on (e.g. LLVM 3.5 is not supported by the compiler), but if you build LLVM from source it should work just fine! I think that there have been some patch releases to 3.5 which should at least get the compiler bootstrapping (but not passing tests), however.

As there's not much we can do here I'm going to close this for now though.

**Comment by hartmel** [comment]
Thanks for your answer, I understand the problem. I followed this error message, in fact : https://github.com/rust-lang/rust/blob/master/configure#L964
What is the minimal LLVM version ? 3.6 ?

**Comment by dotdash** [comment]
I think 3.5.2 used to work. Not sure whether that's still the case though
:-/

2015-10-09 20:42 GMT+02:00 hartmel <notifications@github.com>:

**Comment by alexcrichton** [comment]
Ah yeah that unfortunately hasn't been updated in awhile (the configure script). I think we bootstrap with the vanilla 3.6 release of LLVM and I think @dotdash is right that we at least bootstrap with the most recent patch release of LLVM 3.5, we just won't pass all tests until you use LLVM 3.7.

**Comment by hartmel** [comment]
OK, thanks for your answers.
