### ISSUE TITLE
Add an exit_crate(..) callback to LateLintPass

### ISSUE THREAD

**Issue by llogiq** [rust-lang/rust#28942]
I [had to](https://llogiq.github.io/2015/10/09/lint-data.html) resort to implement `Visitor` for my lint so I could do something _after_ having walked the whole crate. This hurts performance for something that could easily be done by having an `exit_crate(self, cx: &LateContext, krate: &Crate)` on `LateLintPass` which is called after having walked the crate.

**Comment by eddyb** [comment]
Seems useful for anything that collects information - perhaps we want a similar mechanism for syntax extensions, too.

**Comment by nikomatsakis** [comment]
Seems like it'd be more natural to have a `visit_crate`, which you can then override.

**Comment by llogiq** [comment]
@nikomatsakis that would expose the underlying Visitor to the lint, right? This means those lints overriding it would need to `walk_crate(..)`. I think a callback after the `walk` is less error-prone.

**Comment by steveklabnik** [comment]
triage: no changes i'm aware of

**Comment by llogiq** [comment]
The `*LintPass` visitor interfaces now have `check_crate_post(..)`, along with other `_post` methods. Closing this.
