### ISSUE TITLE
Allow "blessed" libraries to be used via `extern crate` from play.rust-lang.org

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#28956]
One of the biggest unspoken advantages of being in the stdlib is that it's trivial to provide a working example of their usage thanks to their inclusion on play.rust-lang.org. While I *suppose* we could finagle a way to have every library that's on crates.io available from the playpen, for the moment it would be great if we could just do e.g. `extern crate regex;` and have it Just Work for all crates that are personally maintained by the Rust developers (rust-lang and rust-lang-nursery, but not rust-lang-deprecated).

**Comment by jdm** [comment]
Doesn't this belong in https://github.com/rust-lang/rust-playpen instead?

**Comment by steveklabnik** [comment]
Yes, it does

**Comment by bstrie** [comment]
@steveklabnik , it's poor form to close a bug because it belongs in another repo but neglect to actually move the bug to that repo. Please don't let us lose bugs like this.

Filed as https://github.com/rust-lang/rust-playpen/issues/151 .
