### ISSUE TITLE
TcpStream::read receives 0 bytes on Mac OS 10.10.5

### ISSUE THREAD

**Issue by dignan** [rust-lang/rust#28955]
It appears TcpStream::read receives 0 bytes and returns immediately on both stable (1.3.0) and nightly despite not reaching EOF.  It doesn't matter whether or not I set a read timeout, either.  I tested with both nightly and stable, as well as with and without a read timeout (on nightly).  I used a Python client to send test data to the server, since I'm more familiar with that.

Rust Test Server:
```
use std::net::TcpListener;

use std::io::Read;

fn main() {
    let listener = TcpListener::bind("127.0.0.1:9010").unwrap();
    let mut stream_and_addr = listener.accept().unwrap();
    let mut buf = Vec::with_capacity(32);
    let num_bytes_received = stream_and_addr.0.read(&mut buf).unwrap();

    println!("Got {} bytes", num_bytes_received);
}
```

With set_read_timeout (for nightly):
```
use std::net::TcpListener;
use std::io::Read;
use std::time::Duration;

fn main() {
    let listener = TcpListener::bind("127.0.0.1:9010").unwrap();
    let stream_and_addr = listener.accept().unwrap();
    let mut buf = Vec::with_capacity(32);
    let mut stream = stream_and_addr.0;

    stream.set_read_timeout(Some(Duration::new(5, 0))).unwrap();
    let num_bytes_received = stream.read(&mut buf).unwrap();

    println!("Got {} bytes", num_bytes_received);
}
```

Python Test Client:
```
import socket

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(("127.0.0.1", 9010))
s.send("some test data")
s.close()
```

**Comment by dignan** [comment]
The problem here is actually that Vec::with_capacity(32) allocates space, but the vector returned is still 0 length: https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#capacity-and-reallocation

**Comment by levkk** [comment]
I'm getting this too on `rustc 1.58.1 (db9d1b20b 2022-01-20)`. Same code as yours.
