### ISSUE TITLE
Compiler can't choose an implementation if there are more than one

### ISSUE THREAD

**Issue by DenisKolodin** [rust-lang/rust#29002]
I've surprised with contradictory compiler's behaviour in the following code:

```rust

trait Extractor<T> {
    fn extract(&self) -> Option<T>;
}

struct Container;

impl Extractor<String> for Container {
    fn extract(&self) -> Option<String> { None }
}

fn expected(_: &str) { }

fn main() {
    let c = Container;
    match c.extract() {
        Some(ref s) => expected(s),
        None => (),
    }
}
```

That compiles well as long as I don't add an another implementation:
```rust
impl Extractor<i64> for Container {
    fn extract(&self) -> Option<i64> { None }
}
```

Now the same code doesn't work and compilation fails with:
```
<anon>:21:13: 21:22 error: the trait `core::marker::Sized` is not implemented for the type `str` [E0277]
<anon>:21     match c.extract() {
                      ^~~~~~~~~
<anon>:21:13: 21:22 help: see the detailed explanation for E0277
<anon>:21:13: 21:22 note: `str` does not have a constant size known at compile-time
<anon>:21     match c.extract() {
                      ^~~~~~~~~
```

I know how to specify type, but I'm more concerned with unexpected behaviour. Why compiler had confused?

**Comment by eefriedman** [comment]
Basically, the compiler has two different ways of reasoning about this sort of construct.

If there's exactly one implementation of Extractor, the compiler reasons forward. it picks that implementation, and concludes that `s` is of type `&String` based on that.  Therefore, the call to `expected(s)` desugars to `expected(&**s)`.

If there are multiple implementations, it reasons backwards: it sees that `expected(s)` takes an `&str`, therefore the type of `s` must be `&str`, and therefore `extract()` must return an `Option<str>`.

The interaction is a little unfortunate, but I don't think there's any practical to change inference to make your second testcase work.

**Comment by DenisKolodin** [comment]
@eefriedman Thank you for quick and clear explanation.
Solution requires advanced heuristic for types which differ in fact. I have to close this issue.
