### ISSUE TITLE
PhantomData should implement Clone

### ISSUE THREAD

**Issue by Yoric** [rust-lang/rust#29005]
I don't see any good reason to prevent it, and this would have saved me lots of manual implementations of `Clone`.

**Comment by apasel422** [comment]
`PhantomData` does implement `Clone`: https://doc.rust-lang.org/stable/std/marker/struct.PhantomData.html.

What version of Rust are you using? Can you post some source code that doesn't compile due to this issue?

**Comment by alexcrichton** [comment]
Agreed with @apasel422, so closing, but feel free to post an error message here so we can help debug!

**Comment by Yoric** [comment]
Here's a minimized misleading sample:
````rust
use std::marker::PhantomData;

trait Foo<T>: Clone {
}

#[derive(Clone)]
pub struct KeyedIgnoring<T> {
    witness: PhantomData<T>,
}

impl<T> Foo<T> for KeyedIgnoring<T> /* where Foo<T> : Clone */ {
    // error: the trait `core::clone::Clone` is not implemented for the type `T`
}

fn main() {
    println!("Hello, world!");
}
````

Now, if I uncomment `where Foo<T>: Clone`, this works. But I only tried this after you had closed the bug, because the error message led me to believe that the issue was in `PhantomData`.

**Comment by Yoric** [comment]
Also, adding `where Foo<T>: Clone` doesn't scale very well in my code, as I find myself adding numerous such clauses for each `impl`.

**Comment by eefriedman** [comment]
See #26925; you should be able to get around the issue by implementing Clone manually.  (`impl<T> Clone for KeyedIgnoring<T> { fn clone(&self) -> Self { KeyedIgnoring { witness: PhantomData } } }`).

**Comment by Yoric** [comment]
Yes, hence
>   this would have saved me lots of manual implementations of Clone

in my original comment.

As it is, I had to revert my change in which I added `where Foo<T>: Clone`, as it breaks client code.

**Comment by alexcrichton** [comment]
Yes currently `derive(Clone)` will put a `Clone` requirement on all type parameters of the struct, so the dependency on `Clone` for `T` comes from `KeyedIgnoring` instead of the `PhantomData` itself.
