### ISSUE TITLE
RawVec of ZST should be safe to transmute

### ISSUE THREAD

**Issue by srijs** [rust-lang/rust#29019]
`RawVec` currently stores its buffer capacity not in bytes but as the number of elements that fit in it. That makes transmute as unsafe to use on it as on any other data structure.

If `RawVec` would store the capacity as the size of the buffer in bytes, that would mean that `mem::transmute` would be safe to use on it, enabling a conversion from `RawVec<T>` into a `RawVec<U>` without any runtime cost.

Furthermore, it would enable a safe transmutation from the vacuous `Vec<Void>` to `Vec<T>` for any T, similar to what's possible with slices today. It also makes this possible for other RawVec-backed structs, e.g. `VecDeque`.

Being able to universally quantify guaranteed-to-be-empty data structures this way without any runtime cost can be very useful.

Compare: https://hackage.haskell.org/package/void-0.7.1/docs/Data-Void-Unsafe.html

**Comment by bluss** [comment]
That alone does not make it safe to transmute. The allocation's alignment is computed from the element type, and that information is lost. (It's needed to deallocate).

Further, I'm not sure if this would be a cost free change, it would need an integer division / bit shift to compute the length for indexing and slicing.

**Comment by Gankro** [comment]
I agree with @bluss' assessment. It's not sound (alignment matters for a couple reasons), and it would penalize "normal" code which doesn't really care about "number of bytes".

**Comment by srijs** [comment]
I see, thanks for the clarification about alignment.

I guess I was too focussed on making the `Vec<Void>` case work, I should have been clear from the start that this was my main use-case.

Assuming `size_of::<Void> == 0` (which should be true for an uninhabited data type?), I still find it inconvenient that the stored capacity would be usize max. Could this be something that could be checked on calls to things like `capacity` or `push`? Is my understanding correct that the compiler would be able to optimise that if-sizeof-zero statement away after the monomorphisation phase?

**Comment by bluss** [comment]
Transmuting from a vector with zero sized type (ZST) element doesn't give you much anything. Vecs with ZST have no allocation, they are just a length counter! Just `Vec::new()` wins you the same.

**Comment by srijs** [comment]
In my case I have a nested data-structure that contains the vectors at the leaves. It would be convenient if I could transmute the structure without having to traverse it.

**Comment by bluss** [comment]
Yes, branches on the size of the type parameter are of course compiled out like that.

It sounds pretty reasonable to request that the stored capacity for the ZST case should be 0. That way all empty, zero capacity, and all non-empty RawVec with ZST elements can be transmuted to another.

**Comment by bluss** [comment]
Isn't it reasonable that we fix this up for consistency anyway? `Vec::new()` and `Vec::with_capacity(0)` produce different internal values, (but will report the same value in `capacity()`).

```rust
fn as_bytes<T: ?Sized>(x: &T) -> &[u8] {
unsafe {
    std::slice::from_raw_parts(x as *const  T as *const u8, std::mem::size_of_val(x))
}
}

> as_bytes(&Vec::<()>::new())
[1, 0, 0, 0, 0, 0, 0, 0, 255, 255, 255, 255, 255, 255, 255, 255, 0, 0, 0, 0, 0, 0, 0, 0]

> as_bytes(&Vec::<()>::with_capacity(0))
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

> as_bytes(&Vec::<()>::with_capacity(1))
[1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

**Comment by Gankro** [comment]
I believe the inconsistency is an artifact of changing internal design to support zero-sized slices

`Box<[()]> -> Vec<()> -> Box<[()]>`

Presumably RawVec's `new` ctor can be changed to set the internal cap to `0` perfectly fine.

**Comment by srijs** [comment]
That sounds good.

Being able to guarantee that a vector can only be empty via `Vec<Void>` is a powerful thing to be able to express on a type level. It feels like enabling that bit of static safety plus a low-cost conversion is in the spirit of the Rust language.

**Comment by Gankro** [comment]
@srijs what do you mean by "empty"? I don't understand the safety/cost argument.

I'm pretty wary of you transmuting anything; everything you're describing is Undefined Behaviour as far as I know (but Rust doesn't currently abuse that behaviour).

**Comment by srijs** [comment]
@Gankro it is an inherent property that if you have an uninhabited type, that allows you to guarantee certain things about containers that are parameterised by it.

For instance, an `Option<Void>` can only be `None`, since `Some(Void)` is impossible to construct. The same is true for a `Vec<Void>` which is guaranteed to have length zero because a call to `push`, for example, would require a value of type `Void`.

I am aware that I might be lacking some knowledge in this area, which is why I am asking about things and I surely will not try to use these tricks in production code with my current level of knowledge.

Could you describe what would constitute undefined behaviour when transmuting a vector from void (at which point the internal pointer is `heap::EMPTY`, and the length must be zero) and another type?

**Comment by Gankro** [comment]
@srijs Rust doesn't guarantee that `Vec<T>` and `Vec<U>` have the same field ordering (though there is no reason why they wouldn't -- it's just something we've agreed to leave out):

To safely transmute, you have to be working with `repr(C)` or primitive types (&, i32, bool, ...).

https://doc.rust-lang.org/nightly/nomicon/repr-rust.html

https://doc.rust-lang.org/nightly/nomicon/transmutes.html

**Comment by steveklabnik** [comment]
So... it doesn't seem like there's a bug here?

**Comment by Gankro** [comment]
Ageed.
