### ISSUE TITLE
Book at docs.rust-lang.org behind master. Continuous deployment for docs?

### ISSUE THREAD

**Issue by chrisccerami** [rust-lang/rust#29011]
There have been some helpful doc updates recently that aren't reflected at https://doc.rust-lang.org/stable/book, such as https://github.com/rust-lang/rust/commit/bcf3921a2aaf72c0f7a3e052dd2ef20f188054a3 by @mike-marcacci from August 8. I think it would be worth considering a CI approach to the docs/book to help keep them up to date.

**Comment by steveklabnik** [comment]
> I think it would be worth considering a CI approach to the docs/book to help keep them up to date.

The book works just like everything else: stable points to the current stable release, which is 1.3. So that URL will never be consistent with master. That said, that commit should be in 1.3, so I'm not sure what's up. @brson @edunham?

**Comment by chrisccerami** [comment]
@steveklabnik Ah, duh. That seems obvious in hindsight. Looking at 1.3.0, it actually looks like that commit is not there.

**Comment by alexcrichton** [comment]
Yeah as @steveklabnik mentioned we're on a rolling release schedule so these fixes don't come out instantly, and it looks like that commit missed 1.3 but it'll be in 1.4!

**Comment by mike-marcacci** [comment]
@chrisccerami glad you liked the commit :)
