### ISSUE TITLE
Parsing "+" or "-" to f32/f64 on nightly

### ISSUE THREAD

**Issue by yoeljacobsen** [rust-lang/rust#29042]
I tried this code:

    match "+".parse::<f32>() {
      Ok(v) => println!("f32 OK: {}", v),
      Err(e) => println!("f32 Error: {}", e) 
    }

    match "-".parse::<f64>() {
      Ok(v) => println!("f64 OK: {}", v),
      Err(e) => println!("f64 Error: {}", e) 
    }

I expected to see this happen: "Error: invalid float literal"

Instead, this happened: OK: 0

It seems the "leading +" and "leading -" is broken. 

Further, with i32 and i64 is emits an error but IMO an incorrect one:

"cannot parse integer from empty string"

I would expect: "Invalid integer literal"

## Meta

`rustc --version --verbose`:

rustc 1.5.0-nightly (81b3b27cf 2015-10-11)
binary: rustc
commit-hash: 81b3b27cf533e50424f749d1c1db23e5d8db952f
commit-date: 2015-10-11
host: x86_64-unknown-linux-gnu
release: 1.5.0-nightly

**Comment by rkruppe** [comment]
Oh my, this is embarrassing. Preparing a fix right now.

**Comment by alexcrichton** [comment]
Thanks for taking a look @rkruppe! Looks like this is working as expected on stable and has leaked into beta/nightly, so tagging as such.

**Comment by rkruppe** [comment]
Yes, this is a bus (not checking for empty strings in the right places) of the dec2flt code. The bug is also in beta, so the PR (which I'll file very soon) should probably be backported to beta.
