### ISSUE TITLE
Thread-safe clone provider

### ISSUE THREAD

**Issue by Yoric** [rust-lang/rust#29041]
Consider a structure `Foo`, which implements `Clone` for sharing between threads but not `Sync`. For instance, any structure containing a `Sender`. The best way to share a `Foo` is therefore to have a local instance instantiated explicitly somewhere on the stack, and to lug it around the code, cloning wherever it is needed. This is, however, painful for large projects, especially if I do not have one instance of `Foo` to carry around but several thousands (which is [my current use case](https://github.com/servo/servo/issues/7029)).

For the same of readability, I would like to be able to define a module or a static object implementing the following function (resp method):
````rust
pub fn get_a_foo() -> Foo // Return a fresh clone of Foo.
````

For the moment, as far as I can tell, writing this is not possible in Rust. `static mut` requires `Sync`, so `lazy_static!` is out of the question, while afaict `thread_local!` cannot provide sophisticated values.

# Sketch of a possible API

````rust
/// A structure whose sole role is to provide clones of a source object to any thread that
/// requests it.
///
/// Initially, any call to `get` will return `None`. To let the `CloneProvider` provide
/// something more useful, clients need to call method `attach`.
impl CloneProvider<T> where T: Clone {
  /// Provide an original for the `CloneProvider`, returns a guard.
  ///
  /// Until the guard is dropped or `attach` is called again, any call to `get`
  /// will return a clone of `value`. If a previous value is currently attached
  /// by a previous call to `attach`, this previous value is dropped.
  ///
  /// Once the guard is dropped, `value` is dropped and further calls to `get`
  /// will again return `None`.
  fn attach(&self, value: T) -> Guard<T>; // Or perhaps return the old value?

  /// Return a clone of the attached value.
  ///
  /// If there is no currently attached value, return `None`.
  fn get(&self) -> Option<T>;
}

unsafe impl<T> Sync for CloneProvider<T> {
}
````

# Example use

````rust

static provider_of_foo : CloneProvider<Foo> = CloneProvider::new();

fn main() {
  let original = Foo:new();
  let guard = provider_of_foo.attach(original);
  // ...
  sub();
  // ...
}

fn sub() {
  for i in 1..10 {
    let foo = provider_of_foo.get().unwrap();
    thread::spawn(|| {
      foo.stuff();
    }
  }
}
````

**edit** Rewrote the sketch.
**edit** Title and layout.

**Comment by huonw** [comment]
One problem is there's absolutely no guarantee that `Clone` is thread-safe for non-`Sync` types, e.g. it's `unsafe` to clone an `Rc` on multiple threads (it causes a data race on the reference count). That said, there are types which can be safely `Clone`d concurrently despite not being `Sync` (e.g. `Cell`); I'm not sure the best way to capture this.

**Comment by Diggsey** [comment]
@huonw Cell cannot be safely cloned concurrently, because it may be partially written by another thread.

**Comment by Yoric** [comment]
Wouldn't that be `Send + Sync`, then?

**Comment by huonw** [comment]
@Diggsey Oh, good point! Whoops...

**Comment by Diggsey** [comment]
You could define a new unsafe trait, `SyncClone`, and then bound `CloneProvider` by that trait.

`SyncClone` would inherit from `Clone`, and provide the guarantee that the `clone` method can be called concurrently, as long as the object isn't accessed in any other way at the same time.

However, you'd still need to wrap the T contained in `CloneProvider` in an RwLock, to ensure that the `attach` method wouldn't overlap with any cloning.

**Comment by SimonSapin** [comment]
Would this work?

```rust
pub fn get_a_foo() -> Foo {
    lazy_static! {
        static ref FOO: Mutex<Foo> = Mutex::new(Foo { … });
    }
    FOO.lock().unwrap().clone()
}
```

“I have `!Sync` and need `Sync`” is what mutexes are all about.

**Comment by Diggsey** [comment]
@SimonSapin It would work, but there would be unnecessary contention for the mutex. Particulary for the OPs example, that would be less than ideal.

**Comment by Yoric** [comment]
@SimonSapin ````
error: the trait `core::marker::Sync` is not implemented for the type `core::cell::UnsafeCell<std::sync::mpsc::Flavor<telemetry::task::Op>>`
````

**Comment by Yoric** [comment]
Early prototype [here](https://github.com/Yoric/clone_provider/blob/master/src/lib.rs), with an example of usage [here](https://github.com/Yoric/clone_provider/blob/master/examples/test.rs). No `Mutex` or `RwLock`, just an `AtomicPtr`. I don't think I have missed anything, but this clearly needs more testing & doc.

**Comment by SimonSapin** [comment]
Hearing @nical chatting about lock-free algorithms gave me this idea: have an atomic pointer that is swapped with NULL to gain exclusive access:

```rust
#![feature(const_fn)]

use std::marker::PhantomData;
use std::ptr;
use std::sync::atomic::{AtomicPtr, Ordering};

pub struct AtomicCell<T> {
    ptr: AtomicPtr<T>,
    phantom: PhantomData<T>,  // std::ptr::Unique is not atomic
}

impl<T> AtomicCell<T> {
    pub const fn new() -> Self {
        AtomicCell {
            ptr: AtomicPtr::new(ptr::null_mut()),
            phantom: PhantomData,
        }
    }

    pub fn set(&self, value: T) {
        self.replace(Some(Box::new(value)));
        // Drop the previous value, if any
    }

    pub fn replace(&self, value: Option<Box<T>>) -> Option<Box<T>> {
        let ptr = match value {
            Some(box_) => Box::into_raw(box_),
            None => ptr::null_mut(),
        };
        opt_box_from_ptr(self.ptr.swap(ptr, Ordering::SeqCst))
    }
}

fn opt_box_from_ptr<T>(ptr: *mut T) -> Option<Box<T>> {
    if ptr.is_null() {
        None
    } else {
        Some(unsafe { Box::from_raw(ptr) })
    }
}

impl<T> AtomicCell<T> {
    pub fn spin_lock<R, F: FnOnce(&mut T) -> R>(&self, f: F) -> R {
        loop {
            let ptr = self.ptr.swap(ptr::null_mut(), Ordering::SeqCst);
            if !ptr.is_null() {
                // Atomic swap gives us exclusive access
                let result = f(unsafe { &mut *ptr });
                // Drop an other value that might have been inserted by another thread.
                drop(opt_box_from_ptr(self.ptr.swap(ptr, Ordering::SeqCst)));
                return result
            }
            // Spin until we swap a non-null
        }
    }
}

unsafe impl<T: Clone> Sync for AtomicCell<T> {}

#[cfg(test)]
mod tests {
    use AtomicCell;
    use std::ops::Add;
    use std::sync::mpsc::{channel, Sender};
    use std::thread;

    static CELL: AtomicCell<Sender<u32>> = AtomicCell::new();

    #[test]
    fn it_works() {
        let (tx, rx) = channel();
        CELL.set(tx);
        for i in 0..10 {
            thread::spawn(move || {
                let tx = CELL.spin_lock(|tx| tx.clone());
                tx.send(i).unwrap();

                // Or even…
                CELL.spin_lock(|tx| tx.send(i).unwrap());
            });
        }
        assert_eq!(rx.iter().take(20).fold(0, Add::add), 45 * 2);
    }
}
```

**Comment by SimonSapin** [comment]
I guess `SpinLock` is a better name than `AtomicCell`.

**Comment by Yoric** [comment]
That's basically my v2 :)

**Comment by Yoric** [comment]
If we change
````rust
unsafe impl<T: Clone> Sync for AtomicCell<T> {}
````
to
````rust
unsafe impl<T: Send + Clone> Sync for AtomicCell<T> {}
````

We get rid of the unsafe example with `Rc`. More surprisingly, we also get rid of an equivalent unsafe example with both `Cell` and `RefCell`. I can't explain this yet, as both `Cell` and `RefCell` implement `Send` and `Clone`.

We can't compile any of the following:
````rust
static CELL: AtomicCell<Cell<u32>> = AtomicCell::new();
static CELL: AtomicCell<Cell<Sender<u32>>> = AtomicCell::new();
static CELL: AtomicCell<Arc<Cell<u32>>> = AtomicCell::new();
static CELL: AtomicCell<Arc<Cell<Sender<u32>>>> = AtomicCell::new();
static CELL: AtomicCell<Arc<RefCell<u32>>> = AtomicCell::new();
static CELL: AtomicCell<Arc<RefCell<Sender<u32>>>> = AtomicCell::new();
````

which looks surprisingly good.

**Comment by Yoric** [comment]
Oh, and a question on `spin_lock`. If the callback panics, the entire cell becomes unusable, right? Is that an acceptable behavior?

**Comment by Yoric** [comment]
Uploaded a [v2 of my code](https://github.com/Yoric/clone_provider/src/lib/rs) based on @SimonSapin's  version and my feedback.

**Comment by Yoric** [comment]
Uploaded a v3, which adds dropping support.

**Comment by Gankro** [comment]
While this is all good stuff, it seems way too niche to provide in the std lib.

**Comment by Yoric** [comment]
Fair enough. Now that `const fn` is on its way, this can easily be turned into a crate.

**Comment by SimonSapin** [comment]
Good point about panic in the callback. (Same if it’s specialized to `<T as Clone>::clone`, if `T` is generic.)

I agree on having this kind of thing in external crates rather than the standard library. We can always revisit in a specific pattern becomes wildly popular.

**Comment by Gankro** [comment]
I'm closing this as out-of scope for the Rust project itself. Feel free to continue the discussion on users.rust-lang or elsewhere.

Have a nice day! :smile_cat:

**Comment by Yoric** [comment]
Crate is available [here](https://crates.io/crates/atomic_cell), if anybody's interested in testing. @SimonSapin , I hope you don't mind, I've put you as co-author.
