### ISSUE TITLE
Perhaps document breaking changes better

### ISSUE THREAD

**Issue by rkruppe** [rust-lang/rust#29049]
Now that breaking changes are much more rare, and preceded by long discussion of how the breakage can be worked around, it may be worthwhile to provide a single document that lists:

- Summary of the change.
- Information that helps you identify that it is indeed *this* change that broke your code (e.g. the feature or function affected, compiler error messages).
- How to work around the issue, in particular:
  - How to get the old behavior back, if at all.
  - If the breaking change was to introduce new behavior, what this new behavior is and how to get it.

It could be as simple as a Markdown file in the repo. Since we don't do as many breaking and behavioral changes any more, it may not be an undue burden to ask people to write a paragraph or two about their change in such a log. (Then again, we still cobble together the release notes on the day before the release...)

This came up [while talking to](https://github.com/TyOverby/ares/issues/32#issuecomment-148118452) the developers of [ares] about the recent change to accept leading plus in integer parsing. If you don't follow the Rust repo closely, it can be difficult to make sense of the `[breaking-change]` commit messages and find the exact information that you need to fix your crate.

[ares]: https://github.com/TyOverby/ares

**Comment by steveklabnik** [comment]
As this isn't a bug, could you make a thread on internals instead? Thanks!

**Comment by rkruppe** [comment]
D'oh! Sure, [done](https://internals.rust-lang.org/t/document-breaking-changes-better/2791/1).
