### ISSUE TITLE
[Docs] Terminology inconsistency between 'iterator adapters' and 'iterator adaptors'

### ISSUE THREAD

**Issue by dcarral** [rust-lang/rust#29063]
## Context

After having first read about iterators the TRPL book, it called my attention the scarce number of matching results in the API docs for a query like "iterator adapters". Curiously enough, it looks like the term used there is "adaptors" instead of adapters.

## Data
- Appearances @ TRPL(*): 
  - "iterator adapters" -> 7
  - "iterator adaptors" -> 1 (part of compilation output)
- Appearances @ API docs(**): 
  - "iterator adapters" -> 1 (book)
  - "iterator adaptors" -> 158 

\* Appearances found using typical 'Search in directory' feature in a text editor.
\** Appearances found using the site search filter in Google, ie. "iterator adaptors" site:doc.rust-lang.org

## Next steps

Assuming that there aren't semantics involved between these two words in English, I'd like to know what's your opinion on the next steps to take (so we can avoid the inconsistency and possible confusion). 

What about replacing 'adapters' to 'adaptors' everywhere in the book?

**Comment by apasel422** [comment]
I assume this was fixed by #29066?

**Comment by dcarral** [comment]
Yes, this issue can be safely closed now.
