### ISSUE TITLE
doc/style/changing directory is outdated.

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#29077]
The directory https://github.com/rust-lang/rust/tree/master/src/doc/style/changing has a pre-1.0 page attached to it, and the post-1.0 page talks about higher kinded types.

Given that nobody's mentioned this yet, I don't think this chapter of the style guide is even useful, and should be fully axed.

**Comment by Havvy** [comment]
cc @steveklabnik

**Comment by steveklabnik** [comment]
We generally imported @aturon's stuff wholesale, and not a lot has been done with it. So yeah, I would imagine this section should probably just go.

**Comment by Havvy** [comment]
Closing in favor of PR.
