### ISSUE TITLE
Arithmetic operation overflowed in rustc_trans::trans::cabi_x86_64

### ISSUE THREAD

**Issue by apasel422** [rust-lang/rust#29073]
I'm getting an "arithmetic operation overflowed" ICE in librustc_trans/trans/cabi_x86_64.rs on line 454 when building stage1 libstd on 64-bit Ubuntu. Likely related to #27017.

**Comment by alexcrichton** [comment]
cc @luqmana

**Comment by apasel422** [comment]
Note that this occurred with `--enable-debug --enable-debug-assertions`. More reason to fix #27010.

**Comment by apasel422** [comment]
From what I can tell, this is choking on the [`getnameinfo`](https://github.com/rust-lang/rust/blob/9cca96545faf2cfc972cc67b83deae2a78935c43/src/libstd/sys/common/net.rs#L140-L143) function, which takes 7 "integer" arguments:
```rust
extern "system" {
     fn getnameinfo(sa: *const libc::sockaddr, salen: socklen_t,
                    host: *mut c_char, hostlen: libc::size_t,
                    serv: *mut c_char, servlen: libc::size_t,
                    flags: c_int) -> c_int;
}
```

**Comment by luqmana** [comment]
Yea, I know what the issue is. I'll get a fix up as soon as I get home.
