### ISSUE TITLE
Confusing error message for non-ASCII byte literals

### ISSUE THREAD

**Issue by tsion** [rust-lang/rust#29088]
Playpen: http://is.gd/DB2ZBU

Code like `b'→'` that puts a unicode character in a byte literal gets a confusing error message:

```
<anon>:2:7: 2:8 error: byte constant must be ASCII. Use a \xHH escape for a non-ASCII byte: \u{2192}
<anon>:2     b'→'
               ^
```

A lot of people read this as if the part after the colon is in reference to "use a \xHH escape", so it should show an example of that, but it really is just displaying the char that is in error, though somewhat obfuscated by using the codepoint instead of the actual char.

**Comment by pkmoore** [comment]
I agree. As someone unfamiliar with the language the error message lead me to fix the playpen code like this:

fn main() {
    b'\u{2192}'
}

Which leads to:

error: unicode escape sequences cannot be used as a byte or in a byte string
