### ISSUE TITLE
Shadowed label warning should be a hardwired lint

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#29097]
There's no way to turn off the shadowed label warning: http://is.gd/0e3wQf.

We should add a `SHADOWED_LABEL` lint to [builtin.rs](https://github.com/rust-lang/rust/blob/293966694c3c8e0c7028e8f54340fbc328d85bff/src/librustc/lint/builtin.rs), and convert the `span_warn` [here](https://github.com/rust-lang/rust/blob/293966694c3c8e0c7028e8f54340fbc328d85bff/src/librustc/middle/resolve_lifetime.rs#L366) to an `add_lint`, similar to [what we do for unused imports](https://github.com/rust-lang/rust/blob/293966694c3c8e0c7028e8f54340fbc328d85bff/src/librustc_resolve/check_unused.rs#L67)

cc @alexcrichton since this adds a new lint

(There are other similar warnings in rustc, some to do with obsolete features, others to do with things which perhaps should be errors. Should we be doing the same to them?)

**Comment by pnkfelix** [comment]
hmm, while I understand the desire to make this warning behave like other warnings, my thinking was that we would eventually make this a hard error once we resolved the macro issues.

**Comment by pnkfelix** [comment]
(that thinking is semi-reflected in the comment immediately above the [linked code](https://github.com/rust-lang/rust/blob/293966694c3c8e0c7028e8f54340fbc328d85bff/src/librustc/middle/resolve_lifetime.rs#L366))

**Comment by Manishearth** [comment]
Ah, okay. What about https://github.com/rust-lang/rust/blob/293966694c3c8e0c7028e8f54340fbc328d85bff/src/librustc/middle/check_match.rs#L253 ?

**Comment by Manishearth** [comment]
(Removing E-Easy till we figure out if this should happen)

**Comment by pnkfelix** [comment]
> Ah, okay. What about https://github.com/rust-lang/rust/blob/293966694c3c8e0c7028e8f54340fbc328d85bff/src/librustc/middle/check_match.rs#L253 ?

That ... I think can be a lint. . .

I mean, I admit, it is a little difficult to make the call in each of these cases.

## Lifetime Shadowing

The basis for the label-shadowing one is that we *might* (with perhaps > 50% probability) in the future want to actually use labels to denote block lifetimes and allow for writing them in borrow expressions. But to use labels for that purpose, you *really* don't want to have duplicates.

(Now, maybe another answer here, just in the name of backwards-compatibility, will be to disable that future extension to the language in the context of a function that has such duplicate labels...)

## Pattern Binding and Variant Identifier Collision

Would we ever make this a hard error?  I don't know; its not like the rule is as simple as "an identifier is always a binding form in a pattern."

But I would be willing to bet that there is less than 50% chance that we would ever make this a hard error in the future, and therefore it makes sense to provide the capability to disable the warning, and therefore it makes sense to revise it as a proper lint.

**Comment by steveklabnik** [comment]
Since new lints have a big impact on users of rustc, the policy is that they should go through the RFC process like other user-facing changes. As such, I'm going to give this one a close, but if anyone comes across this ticket and wants this lint, consider adding it to clippy and/or writing up an RFC. Thanks!
