### ISSUE TITLE
Ambiguous elided lifetime error claims non-elided lifetime is elided

### ISSUE THREAD

**Issue by wthrowe** [rust-lang/rust#29094]
``` rust
struct Thing<'a>(&'a ());

fn func1<'a>(_arg: &'a Thing) -> &() { unimplemented!() }
fn func2<'a>(_arg: &Thing<'a>) -> &() { unimplemented!() }
```

gives

```
test.rs:3:34: 3:37 error: missing lifetime specifier [E0106]
test.rs:3 fn func1<'a>(_arg: &'a Thing) -> &() { unimplemented!() }
                                           ^~~
test.rs:3:34: 3:37 help: run `rustc --explain E0106` to see a detailed explanation
test.rs:3:34: 3:37 help: this function's return type contains a borrowed value, but the signature does not say which one of `_arg`'s 2 elided lifetimes it is borrowed from
test.rs:4:35: 4:38 error: missing lifetime specifier [E0106]
test.rs:4 fn func2<'a>(_arg: &Thing<'a>) -> &() { unimplemented!() }
                                            ^~~
test.rs:4:35: 4:38 help: run `rustc --explain E0106` to see a detailed explanation
test.rs:4:35: 4:38 help: this function's return type contains a borrowed value, but the signature does not say which one of `_arg`'s 2 elided lifetimes it is borrowed from
error: aborting due to 2 previous errors
```

Each time it refers to "`_arg`'s 2 elided lifetimes", but in both cases only one of `_arg`'s lifetimes is elided.

**Comment by arielb1** [comment]
We should just remove the "elided" - the rules work (and always worked) for all lifetimes.

**Comment by Mark-Simulacrum** [comment]
E-easy/E-mentor. The code needs to be updated [here](https://github.com/rust-lang/rust/blob/4ed2edaafe82fb8d44e81e00ca3e4f7659855ba2/src/librustc/middle/resolve_lifetime.rs#L1366-L1367) to remove elided. A few tests will then fail, probably src/test/compile-fail/issue-26638.rs, src/test/compile-fail/issue-30255.rs, and src/test/compile-fail/lifetime-elision-return-type-requires-explicit-lifetime.rs which will need to be updated to remove the word elided as well.

Let us know if you'd like to work on this, or if you have any questions; we'll be happy to help.

**Comment by stephen-lazaro** [comment]
I'd be happy to take a shot at this over the weekend if no one else is interested.

**Comment by Mark-Simulacrum** [comment]
Go ahead! Let us know if there's anything we can do to help you out.

`./x.py test --incremental src/test/compile-fail` is probably your best bet for compiling and testing in this case.

**Comment by Mark-Simulacrum** [comment]
Reopening per https://github.com/rust-lang/rust/pull/42415#issuecomment-306063397.

**Comment by steveklabnik** [comment]
Triage: the error today:

```text
Compiling playground v0.0.1 (/playground)
error[E0106]: missing lifetime specifier
 --> src/lib.rs:3:34
  |
3 | fn func1<'a>(_arg: &'a Thing) -> &() { unimplemented!() }
  |                                  ^ expected lifetime parameter
  |
  = help: this function's return type contains a borrowed value, but the signature does not say which one of `_arg`'s 2 lifetimes it is borrowed from

error[E0106]: missing lifetime specifier
 --> src/lib.rs:4:35
  |
4 | fn func2<'a>(_arg: &Thing<'a>) -> &() { unimplemented!() }
  |                                   ^ expected lifetime parameter
  |
  = help: this function's return type contains a borrowed value, but the signature does not say which one of `_arg`'s 2 lifetimes it is borrowed from

error: aborting due to 2 previous errors
```

It still does not suggest `'a`, so keeping open as per @estebank 's comment.
