### ISSUE TITLE
Nightly borrowck regression

### ISSUE THREAD

**Issue by arcnmx** [rust-lang/rust#29103]
The following code compiles on stable and beta but not on the current nightly:

```rust
#[derive(Clone)]
struct S;

impl S {
    fn borrow(&self) -> Vec<&Self> { vec![self] }
    
    fn borrow_mut(&mut self, _: &S) { }
}

fn main() {
    let mut s = S;
    for x in s.borrow().into_iter().cloned().collect::<Vec<_>>() {
        s.borrow_mut(&x)
    }
}
```

**Comment by alexcrichton** [comment]
triage: I-nominated

**Comment by nikomatsakis** [comment]
triage: P-high

**Comment by nikomatsakis** [comment]
Not sure what's going on here just yet.

**Comment by arielb1** [comment]
This fails on stable (1.3) too if you explicitly deref `S` (either via `*`, `.deref`, or `Deref::deref`) rather than autderefing.

**Comment by arielb1** [comment]
Minified:
```Rust
#[derive(Clone)]
struct S;

fn borrow<'a>(s: &'a S) -> Vec<&'a S> { vec![s] }

fn main() {
    let s = S;
    match <Vec<&S> as IntoIterator>::into_iter(borrow(&s)) {
        _ => drop(s)
    };
}
```

**Comment by nikomatsakis** [comment]
I believe this will be fixed by @pnkfelix's PR here: https://github.com/rust-lang/rust/pull/29186

**Comment by nikomatsakis** [comment]
@pnkfelix can you confirm?

**Comment by pnkfelix** [comment]
yes it looks to me like #29186 fixes this.

I also think the test that #29186 adds should suffice to cover this bug; does anyone disagree with that claim?

If no one disagrees then I'll close this as a dupe of #29166

**Comment by nikomatsakis** [comment]
I agree. Closing as dup of #29166.
