### ISSUE TITLE
unsafe const fn declaration order

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#29107]
The [recent implementation](https://github.com/rust-lang/rust/pull/28827#issuecomment-148083432) uses the syntax `unsafe const fn`, but the RFC says `const unsafe fn`.

**Comment by thepowersgang** [comment]
Actually, the RFC text says `unsafe const fn`, but a [comment on the PR](https://github.com/rust-lang/rfcs/pull/1245#issuecomment-146999181) says `const unsafe fn`

**Comment by nikomatsakis** [comment]
Discussed in the meeting today and decided we might as well stick to our decision, arbitrary though it may have been, and thus we should accept only `const unsafe fn`. I think that most of us would prefer to actually accept modifiers in any order, but it seems weird to accept *just these two particular modifiers* in any order, and thus we should just open a more general RFC about allowing arbitrary modifiers to appear in any order.

**Comment by thepowersgang** [comment]
I'm doing a final compilation check on the commit above, once it's done I'll file a PR reversing the order.

**Comment by thepowersgang** [comment]
RFC update PR rust-lang/rfcs#1335 and implementation update #29274

**Comment by nikomatsakis** [comment]
Done in #29274
