### ISSUE TITLE
impl default type param fallback not firing without explicitly typed expression context

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#29101]
One of the big motivations for default type parameter fallback ([RFC #213][]) was for future-proofing our API's: We wanted to be able to stabilize an api like `Vec<T>`, with the expectation that future versions of `Vec` might want additional type parameters, like `Vec<T, A> where A:Allocator`, and that we would accomplish this by specifying a default type parameter `Vec<T, A=DefaultAlloc>`, and then old code written against `Vec<T>` would just fill in `A=DefaultAlloc` for the missing parameter.

[RFC #213]: https://github.com/rust-lang/rfcs/blob/master/text/0213-defaulted-type-params.md

However, it seems like the current implementation is missing something, since my attempt to prototype `Vec<T, A:Allocator=DefaultAlloc>` is hitting problems with type inference on code that should not need modification.

Here is a concrete example of the problem I am facing. Start with this code (all of the concatenated snippets can be found [here](https://gist.github.com/pnkfelix/d330129c808d1c7f5671)): 

```rust
#[cfg(version1)]
#[derive(Debug)] struct Mec { x: i32 }

#[cfg(version1)]
impl Mec {
    pub fn new(x: i32) -> Self { Mec { x: x } }
}

fn main() {
    let m1: Mec = Mec::new(1);
    println!("Hi {:?}", m1);

    let m2 = Mec::new(2);
    println!("Hi {:?}", m2);
}
```

You can compile and run it (it works as is) like so:
```
% rustc --cfg version1 default-fallback2.rs && ./default-fallback2
Hi Mec { x: 1 }
Hi Mec { x: 2 }
```

Now lets add a defaulted type parameter to `Mec`:

```rust
#[derive(Debug, Default)] struct Dflt;
#[derive(Debug, Default)] struct Alt;

#[cfg(any(version2, version3))]
#[derive(Debug)] struct Mec<A=Dflt> { x: i32, a: A }

#[cfg(version2)]
impl Mec<Dflt> {
    pub fn new(x: i32) -> Self { Mec { x: x, a: Default::default() } }
}
```

We can keep compiling and running with `version2` here, there's no problem yet:

```rust
% rustc --cfg version2 default-fallback2.rs && ./default-fallback2
Hi Mec { x: 1, a: Dflt }
Hi Mec { x: 2, a: Dflt }
```

The problem comes when we try to further generalize: What if we wanted to allow `Mec::new()` to work for any `A` that implements `Default` (like `struct Alt` above)?  That's our third version, and that's where things go wrong:

```rust
#[cfg(version3)]
impl<A:Default=Dflt> Mec<A> {
    pub fn new(x: i32) -> Self { Mec { x: x, a: Default::default() } }
}
```

Now we get a type inference error:

```
% rustc --cfg version3 default-fallback2.rs && ./default-fallback2
default-fallback2.rs:13:14: 13:22 error: unable to infer enough type information about `_`; type annotations or generic parameter binding required [E0282]
default-fallback2.rs:13     let m2 = Mec::new(2);
                                     ^~~~~~~~
default-fallback2.rs:13:14: 13:22 help: run `rustc --explain E0282` to see a detailed explanation
error: aborting due to previous error
```

(Note that the `let m1: Mec = Mec::new(1);` invocation works; its only when we leave out the type annotation on the `let m2 = ...` binding that inference fails to fall back to `A=Dflt`.)

**Comment by nikomatsakis** [comment]
> (Note that the let m1: Mec = Mec::new(1); invocation works; its only when we leave out the type annotation on the let m2 = ... binding that inference fails to fall back to A=Dflt.)

The reason for this is that, at least presently, when you write `Mec`, it is as if you wrote `Mec<Dflt>`. That is, the defaults are expanded, rather than informing inference.

**Comment by nikomatsakis** [comment]
@pnkfelix what happens if you write `let m1: Mec<_>`?

**Comment by pnkfelix** [comment]
@nikomatsakis it still errors; playpen: http://is.gd/u5nGsg

**Comment by nikomatsakis** [comment]
Just remembered that you need `#![feature(default_type_parameter_fallback)]`

**Comment by pnkfelix** [comment]
Ah that does fix things, as illustrated here: http://is.gd/sFRVUs

**Comment by pnkfelix** [comment]
Closing.

Feature seems to be working as expected, I just was user-erroring by leaving out the feature gate.

(There is still an implicit problem in that we cannot expect client-crates to turn on the feature-gate here, so we are still restricted in the Allocator work as to which API's we can parameterize over `A:Allocator + Default`, but that's okay; we can generalize incrementally and let the latter wait until `feature(default_type_parameter_fallback)` is ungated.)
