### ISSUE TITLE
dropck doc oversights / revision

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#29111]
The implementation of non-parametric dropck (#28861) included comments and doc that is missing a few things.
1. There was feedback from @Gankro on changes to the rustonomicon that should be further tweaks (see comment thread from #28861)
2. There should be a _huge_ warning (maybe even a lint or something) that if you put `#[unsafe_destructor_blind_to_params]` on a struct that is using native pointers (e.g. `struct Foo<T>( { ptr: *mut T }`) then you almost certainly need a `PhantomData` in there.

The old code before #28861 was in fact busted in this respect, as one can see by taking the test case from #29106 and running it on older versions of Rust.

**Comment by Gankro** [comment]
:+1: for a lint; CC @Manishearth

**Comment by Manishearth** [comment]
hardwired lint makes sense here.

Note that if you add a lint, you need to be careful about backcompat if you're going to be removing it. We don't have a framework for "obsolete" lints yet, but it could be added.

**Comment by steveklabnik** [comment]
Triage: I didn't even know this attribute was a thing!

**Comment by apasel422** [comment]
@steveklabnik The `unsafe_destructor_blind_to_params` attribute is deprecated now. CC #34761.

**Comment by Mark-Simulacrum** [comment]
@pnkfelix Is there a chance you could comment on the status of this issue since the attribute was deprecated in favor of (other?) issues.

**Comment by steveklabnik** [comment]
Triage: with no comment from @pnkfelix, I'm going to consider this stale and close it. felix, please let me know if you think this is still important and we can re-open.
