### ISSUE TITLE
Unable to link static rust library to 32-bit C program on windows.

### ISSUE THREAD

**Issue by shadowmint** [rust-lang/rust#29135]
Here is a reproducible test case: https://github.com/shadowmint/rust-extern

This code works fine on mac and linux, but not on windows.

On windows, the msys linker reports:

```
doug@Tio /c/projects/rust-all/rust-extern/build
$ make
[ 50%] Linking C executable external.exe
CMakeFiles/external.dir/objects.a(test.c.obj):test.c:(.text+0x2a): undefined reference to `rs_str'
CMakeFiles/external.dir/objects.a(test.c.obj):test.c:(.text+0x3e): undefined reference to `rs_trigger'
CMakeFiles/external.dir/objects.a(test.c.obj):test.c:(.text+0x4a): undefined reference to `rs_trigger'
CMakeFiles/external.dir/objects.a(test.c.obj):test.c:(.text+0x56): undefined reference to `rs_register'
CMakeFiles/external.dir/objects.a(test.c.obj):test.c:(.text+0x62): undefined reference to `rs_trigger'
CMakeFiles/external.dir/objects.a(test.c.obj):test.c:(.text+0x6e): undefined reference to `rs_trigger'
c:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/bin/ld.exe: CMakeFiles
/external.dir/objects.a(test.c.obj): bad reloc address 0x20 in section `.eh_frame'
c:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/bin/ld.exe: final link
 failed: Invalid operation
collect2.exe: error: ld returned 1 exit status
make[2]: *** [external.exe] Error 1
make[1]: *** [CMakeFiles/external.dir/all] Error 2
make: *** [all] Error 2
```

However, the link flags being used are perfectly normal:

```
/C/MinGW/bin/gcc.exe     -Wl,--whole-archive CMakeFiles/external.dir/objects.a -Wl,--no-whole-archive  -o external.exe -Wl,--out-implib,libexternal.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles/external.dir/linklibs.rsp
```

where linklibs.rsp is:

```
 ../target/debug/libextern.a -lws2_32 -luserenv -ladvapi32 -lkernel32 -luser3lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32
```

Notice specifically as mentioned in the repository README, a fake c based fixture for the same api is included in the the `c` folder; when linked against this library, the compile step works fine. That is to say, the cmake build step to compile the c target is correct.

It's difficult to tell exactly what's going on here, but it seems like the static library generated by rustc isn't being picked up as a valid file by gcc.

```
$ rustc --version
rustc 1.3.0 (9a92aaf19 2015-09-15)
from: https://static.rust-lang.org/dist/rust-1.3.0-i686-pc-windows-gnu.msi
```

Notice that this is the 32-bit version of both rustc and msys.

I would guess that I was doing something wrong here, but this repository *actually worked* on rust 1.0; so something has changed in the way things work between then and now?

**Comment by shadowmint** [comment]
Sorry, and just to be clear: calling C from rust works perfectly fine, obviously.

This is specifically with regard to compiling a crate as a static/dynamic library and calling it from an external C application.

It occurred to try loading the dynamic library using python, which gives:

```
doug@Tio /c/projects/rust-all/rust-extern/target/debug
$ /c/Python27/python.exe
Python 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes
>>> ex = ctypes.CDLL("extern.dll")
>>> ex.rs_str()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python27\lib\ctypes\__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "c:\Python27\lib\ctypes\__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'rs_str' not found
```

Which is odd, given:

```
doug@Tio /c/projects/rust-all/rust-extern/target/debug
$ nm extern.dll | grep rs_
627c16e0 t __ZN10rs_trigger10__rust_abiE
628950a4 r __ZN10rs_trigger15__STATIC_FMTSTR20hdfbe560ac65b650e4baE
62895098 r __ZN10rs_trigger15__STATIC_FMTSTR20hdfbe560ac65b650epbaE
628950ac r __ZN10rs_trigger15__STATIC_FMTSTR20hdfbe560ac65b650eucaE
62895090 r __ZN10rs_trigger15__STATIC_FMTSTR20hdfbe560ac65b650eVaaE
62895a68 R __ZN11dynamic_lib2dl19check_for_errors_in15__STATIC_FMTSTR20h94187edf
1ce43451q4dE
627c19e0 t __ZN11rs_register10__rust_abiE
6289516c r __ZN11rs_register15__STATIC_FMTSTR20hdfbe560ac65b650e6caE
627c98e0 T __ZN3env7vars_os20h2fe647ea53eb2950b7dE
627c1580 t __ZN6rs_str10__rust_abiE
627c19c0 T _rs_register@4
627c1570 T _rs_str@0
627c16c0 T _rs_trigger@4
```

I'm not quite sure what to make of that; the DLL is the right 32-bit type, but the symbol names aren't right perhaps?

**Comment by eefriedman** [comment]
This is sort of a random guess, but I think you want `extern "C"` rather than `extern "system"`?

**Comment by retep998** [comment]
`extern "system"` actually means `extern "stdcall"` on 32-bit while `extern "C"` means `extern "cdecl"`. The default that the C code uses depends on the flags you pass to the compiler, so it would probably be best if you explicitly specified `stdcall` or `cdecl` on both sides.

**Comment by shadowmint** [comment]
That wont resolve the missing symbols surely?

I did try with cdecl before, but that didnt seem to work either... but
sure. I'll give extern C another try later.

**Comment by retep998** [comment]
It actually might resolve the missing symbols issue because different calling conventions decorate/mangle the symbol names differently.

**Comment by shadowmint** [comment]
Woo, seems you're right.

Either using `__stdcall` and `extern "system"` or `__cdecl` and `extern "C"` works, but you can't mix and match.
