### ISSUE TITLE
Tracking issue for owned CString conversions

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#29157]
This is a tracking issue for the `into_foo` methods being added in https://github.com/rust-lang/rust/pull/28977. Some possible future questions to consider:

* Is `IntoStringError` suitable? Named appropriately? Correct set of accessors? etc.
* Should be paired with an `Into` implementation

**Comment by Diggsey** [comment]
Relatedly, I think the documentation for CString could be improved: it should make it explicit that CStrings do not have or enforce any specific encoding, they are simply null-terminated arbitrary byte sequences.

On the other hand, all of the conversion methods will implicitly assume that it is supposed to contain UTF8 data (an unfortunate decision IMO, but too late to change). It should therefore warn that the default conversions will not necessarily be what is required: users should look to the documentation of the C library they are interfacing with to determine what, if any, encoding is used for its strings.

**Comment by alexcrichton** [comment]
:bell: This issue is now entering its **final comment period** for stabilization :bell:

**Comment by BurntSushi** [comment]
This looks OK to me. I would like to echo some of @Diggsey's thoughts. In particular, the docs could use improving. e.g., `into_string` should probably "UTF-8 data" instead of "Unicode data."

**Comment by alexcrichton** [comment]
The libs team discussed this recently and the decision was to **stabilize**

**Comment by alexcrichton** [comment]
Closed by https://github.com/rust-lang/rust/pull/30943
