### ISSUE TITLE
Possibly Erroneous E0384 on Some Version of Compilers

### ISSUE THREAD

**Issue by devonhollowood** [rust-lang/rust#29173]
Recently during [this reddit discussion](https://www.reddit.com/r/rust/comments/3p8vsd/start_loop_over_from_inside_a_closure/cw4bxug) it became clear that there exists some code which produces an E0384 error (reassignment of immutable variable) for /u/crossroads1112 and not for me (/u/VikingofRock). The code in question:

    use std::io;

    fn main() {
        let vec: Vec<f64>;
        loop {
            let mut buffer = String::new();
            io::stdin().read_line(&mut buffer)
                .ok()
                .expect("Could not read input");
            let result: Result<Vec<f64>, _> =
                buffer.trim().split(",").map(|s| s.parse()).collect();
            vec = match result{
                Ok(v) => v,
                Err(_) => continue,
            };
            for i in &vec {
                println!("{}", i);
            }
            break;
        }
    }

This compiles without error for me, but /u/crossroads1112's rustc gives:

    ./test.rs:12:9: 15:10 error: re-assignment of immutable variable `vec` [E0384]
    ./test.rs:12         vec = match result {
    ./test.rs:13             Ok(v) => v,
    ./test.rs:14             Err(_) => continue,
    ./test.rs:15         };  
    ./test.rs:12:9: 15:10 note: prior assignment occurs here
    ./test.rs:12         vec = match result {
    ./test.rs:13             Ok(v) => v,
    ./test.rs:14             Err(_) => continue,
    ./test.rs:15         }; 

It is not quite clear to me what the expected behavior is here. It seems as though `vec` does not logically need to be mutable, but it is somewhat surprising to me that the compiler can understand the code well enough to determine that.

## Meta

I tested on the following rustc versions:

    rustc 1.3.0 (9a92aaf19 2015-09-15)
    binary: rustc
    commit-hash: 9a92aaf19a64603b02b4130fe52958cc12488900
    commit-date: 2015-09-15
    host: x86_64-apple-darwin
    release: 1.3.0

    rustc 1.5.0-nightly (206af38e7 2015-10-17)
    binary: rustc
    commit-hash: 206af38e74ce7fa4b0e781ece7f1067c018c580e
    commit-date: 2015-10-17
    host: x86_64-apple-darwin
    release: 1.5.0-nightly

Both were installed using multirust. I have directed /u/crossroads1112 to this issue, and asked him to post his output of rustc --version --verbose as well.

**Comment by crossroads1112** [comment]
/u/crossroads1112: For some reason the code now compiles correctly. I'm not sure what the issue was
