### ISSUE TITLE
Unit/tuple structs with the same name as a module are allowed.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#29185]
The following two type-definition/module conflicts cause errors:
```rust
enum Foo {}
mod Foo {}
```
```rust
struct Bar { x: bool }
mod Bar {}
````
But unit and tuple structs, due to [the special-casing to check for value conflicts](https://github.com/rust-lang/rust/blob/db54339f5a62a694320bd5b80872391cab9f4a1f/src/librustc_resolve/build_reduced_graph.rs#L496-L498), end up not checking for module conflicts, resulting in the following two examples compiling:
```rust
struct Foo;
mod Foo {}
```
```rust
struct Bar(bool);
mod Bar {}
```

**Comment by james-darkfox** [comment]
I found this issue when using a struct with fields. This only causes the error when the module is defined first. 

https://play.rust-lang.org/?gist=f66e0f4649a86c845270&version=stable

**Comment by alexcrichton** [comment]
This is in theory being fixed by https://github.com/rust-lang/rust/pull/26421, but it looks like progress is slow there

**Comment by eddyb** [comment]
Closing as duplicate of #21546.
