### ISSUE TITLE
#[test]s on non top-level functions.

### ISSUE THREAD

**Issue by james-darkfox** [rust-lang/rust#29182]
It would be nice if we could implement test cases directly on a type that they test. This is especially useful when generating code (and test cases) with macros.

In the example below, the expected result would be `Unit::my_important_test` when testing.

``` rust
struct Unit;

impl Unit {
    #[test]
    fn my_important_test() { /* ... */ }
}
```

Alternatively one can just create a non_camel_case module sharing the same identifier as the `struct`. But this looks off for that exact reason. And abuses the bug as reported in #29185.

``` rust
#[cfg(test)] #[allow(non_camel_case)]
mod Unit {
    #[test]
    fn my_important_test() { /* ... */ }
}
```

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by steveklabnik** [comment]
Triage: no change. Given that this was filed in 2015, with zero additional comments, I'm going to close this. We have some work underway for more flexible test runners; they may or may not implement this feature, but it doesn't appear like this is something broadly desired nor going to be implemented any time soon.
