### ISSUE TITLE
`AtomicPtr` doesn't implement `std::fmt::Pointer`

### ISSUE THREAD

**Issue by apasel422** [rust-lang/rust#29212]
It can use a technique analogous to its `Debug` impl to do so.

**Comment by nagisa** [comment]
If we `impl fmt::Pointer for AtomicPtr`, we should also consider implementing `Display` for `AtomicBool`, `AtomicIsize` and `AtomicUsize`. I think not implementing these traits just yet is conscious.

**Comment by steveklabnik** [comment]
Triage: no change. here's a test case

```rust
use std::sync::atomic::AtomicPtr;

fn main() {
    let ptr = &mut 5;
    let some_ptr  = AtomicPtr::new(ptr);
    
    println!("{:p}", some_ptr);
}
```

**Comment by dtolnay** [comment]
I would be fine with adding these impls. The impls should access the atomic using the most restrictive memory ordering. Then if you want any other ordering there is a totally reasonable workaround:

```rust
println!("{:p}", some_ptr.load(Ordering::Relaxed));
```
