### ISSUE TITLE
Rustdoc search could search unstable feature names

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#29221]
E.g. searching for `feature:foo` would find items with `#[unstable(feature = "foo", ...`. This may be useful for someone reading some code with a `feature`, working out what it covers, and is useful for working out what a tracking issue covers, although it will only apply to the standard library and so may not be worth it.

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by steveklabnik** [comment]
Triage: no comments in over three years. This might be an interesting feature, but it is apparently not particularly desired. Closing!
