### ISSUE TITLE
Document how to best write examples that use try for error handling

### ISSUE THREAD

**Issue by killercup** [rust-lang/rust#29234]
@steveklabnik wrote [on reddit](https://www.reddit.com/r/rust/comments/3pn25i/should_unwrap_be_banned_or_discouraged/cw8uo15?context=3), this this is a common style in `std`:

    /// A doc test using `try!`:
    ///
    /// ```
    /// # fn f() -> io::Result<()> {
    /// let x = try!(package.open()); // danger, might explode
    /// x.insert("valuables", 42)
    /// try!(x.close_and_reactivate());
    /// # Ok(())
    /// # }
    /// # f();
    /// ```

We should add that to the [documentation chapter of TRPL](https://doc.rust-lang.org/nightly/book/documentation.html) and maybe also to the docs of `try!`.

**Comment by steveklabnik** [comment]
I'm willing to mentor anyone who wants to do this.

**Comment by efindlay** [comment]
I'll take this on.

**Comment by steveklabnik** [comment]
@efindlay great! Let me know if you need any help.

**Comment by efindlay** [comment]
I reduced the example to one try! Maybe its better to have two try! s. I'm not sure.
