### ISSUE TITLE
Inconsistancy with Default. Mutable slices are mising

### ISSUE THREAD

**Issue by james-darkfox** [rust-lang/rust#29244]
Default is implemented for `&'a [T]` but not `&'a mut [T]`. Is there any reason for this? While writing mutually generic code, I needed exactly this. Alternatively the quick work around is to just have my own trait and implement it for both slices.

@rust-lang/libs

---
My mutually generic code: [option_mut](https://github.com/james-darkfox/rs-option_mut) and [lense](https://github.com/james-darkfox/rs-lense) (currently working on making `lenses` mutually generic through the use of `option_mut`)

**Comment by Gankro** [comment]
Seems like a trivial omission. Easy to add, doesn't need an RFC.

**Comment by nxnfufunezn** [comment]
I'll take this on..

**Comment by Gankro** [comment]
@nxnfufunezn :scream_cat: It appears that @james-darkfox already picked it up and submitted a PR (see above).

**Comment by nxnfufunezn** [comment]
:disappointed:
