### ISSUE TITLE
Add ICEs to Glacier

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#29249]
My [Glacier](https://github.com/steveklabnik/glacier) repository is tracking our ICEs. Once per day, a Travis build confirms that the example still causes an ICE.

@Manishearth suggested I make a metabug here, so if you're looking for an easy way to contribute, this is it! I'm willing to mentor anyone who needs help.

https://github.com/rust-lang/rust/issues?q=is%3Aopen+is%3Aissue+label%3AI-ICE is the list of bugs. Here's a tracking list of which ones that have been added:

- [x] https://github.com/rust-lang/rust/issues/29191
- [x] https://github.com/rust-lang/rust/issues/29184
- [x] https://github.com/rust-lang/rust/issues/29161
- [x] https://github.com/rust-lang/rust/issues/29115
- [x] https://github.com/rust-lang/rust/issues/29052
- [x] https://github.com/rust-lang/rust/issues/28971
- [x] https://github.com/rust-lang/rust/issues/28946
- [x] https://github.com/rust-lang/rust/issues/28804
- [x] https://github.com/rust-lang/rust/issues/28766
- [x] https://github.com/rust-lang/rust/issues/28751
- [x] https://github.com/rust-lang/rust/issues/28625
- [x] https://github.com/rust-lang/rust/issues/28604
- [x] https://github.com/rust-lang/rust/issues/28600
- [x] https://github.com/rust-lang/rust/issues/28575
- [x] https://github.com/rust-lang/rust/issues/28557
- [x] https://github.com/rust-lang/rust/issues/28540
- [x] https://github.com/rust-lang/rust/issues/28502
- [ ] https://github.com/rust-lang/rust/issues/28434
- [x] https://github.com/rust-lang/rust/issues/28410
- [x] https://github.com/rust-lang/rust/issues/28347
- [x] https://github.com/rust-lang/rust/issues/28324
- [x] https://github.com/rust-lang/rust/issues/28308
- [x] https://github.com/rust-lang/rust/issues/28288
- [x] https://github.com/rust-lang/rust/issues/28217
- [x] https://github.com/rust-lang/rust/issues/28189
- [x] https://github.com/rust-lang/rust/issues/28172
- [x] https://github.com/rust-lang/rust/issues/28150
- [x] https://github.com/rust-lang/rust/issues/28104
- [x] https://github.com/rust-lang/rust/issues/28089
- [x] https://github.com/rust-lang/rust/issues/28040
- [ ] https://github.com/rust-lang/rust/issues/28002
- [x] https://github.com/rust-lang/rust/issues/27985
- [x] https://github.com/rust-lang/rust/issues/27954
- [x] https://github.com/rust-lang/rust/issues/27925
- [x] https://github.com/rust-lang/rust/issues/27918
- [x] https://github.com/rust-lang/rust/issues/27901
- [x] https://github.com/rust-lang/rust/issues/27895
- [x] https://github.com/rust-lang/rust/issues/27874
- [x] https://github.com/rust-lang/rust/issues/27844
- [x] https://github.com/rust-lang/rust/issues/27819
- [x] https://github.com/rust-lang/rust/issues/27645
- [x] https://github.com/rust-lang/rust/issues/27631
- [x] https://github.com/rust-lang/rust/issues/27480
- [x] https://github.com/rust-lang/rust/issues/27455
- [x] https://github.com/rust-lang/rust/issues/27443
- [x] https://github.com/rust-lang/rust/issues/27430
- [x] https://github.com/rust-lang/rust/issues/27321
- [x] https://github.com/rust-lang/rust/issues/27320
- [x] https://github.com/rust-lang/rust/issues/27316
- [x] https://github.com/rust-lang/rust/issues/27268
- [x] https://github.com/rust-lang/rust/issues/27249
- [x] https://github.com/rust-lang/rust/issues/27190
- [x] https://github.com/rust-lang/rust/issues/27128
- [x] https://github.com/rust-lang/rust/issues/27125
- [x] https://github.com/rust-lang/rust/issues/27119
- [x] https://github.com/rust-lang/rust/issues/27092
- [x] https://github.com/rust-lang/rust/issues/27078
- [x] https://github.com/rust-lang/rust/issues/26997
- [x] https://github.com/rust-lang/rust/issues/26989
- [x] https://github.com/rust-lang/rust/issues/26886
- [ ] https://github.com/rust-lang/rust/issues/26774
- [x] https://github.com/rust-lang/rust/issues/26510
- [x] https://github.com/rust-lang/rust/issues/26483
- [x] https://github.com/rust-lang/rust/issues/26480
- [ ] https://github.com/rust-lang/rust/issues/26467
- [x] https://github.com/rust-lang/rust/issues/26459
- [x] https://github.com/rust-lang/rust/issues/26406
- [x] https://github.com/rust-lang/rust/issues/26263
- [x] https://github.com/rust-lang/rust/issues/26237
- [ ] https://github.com/rust-lang/rust/issues/26233
- [x] https://github.com/rust-lang/rust/issues/26201
- [x] https://github.com/rust-lang/rust/issues/26166
- [x] https://github.com/rust-lang/rust/issues/26095
- [x] https://github.com/rust-lang/rust/issues/26094
- [x] https://github.com/rust-lang/rust/issues/26093
- [x] https://github.com/rust-lang/rust/issues/26056
- [x] https://github.com/rust-lang/rust/issues/26049
- [x] https://github.com/rust-lang/rust/issues/25940
- [x] https://github.com/rust-lang/rust/issues/25810
- [ ] https://github.com/rust-lang/rust/issues/25801
- [x] https://github.com/rust-lang/rust/issues/25793
- [x] https://github.com/rust-lang/rust/issues/25733
- [x] https://github.com/rust-lang/rust/issues/25693
- [ ] https://github.com/rust-lang/rust/issues/25690
- [x] https://github.com/rust-lang/rust/issues/25579
- [x] https://github.com/rust-lang/rust/issues/25498
- [ ] https://github.com/rust-lang/rust/issues/25415
- [x] https://github.com/rust-lang/rust/issues/25386
- [x] https://github.com/rust-lang/rust/issues/25385
- [ ] https://github.com/rust-lang/rust/issues/25362
- [x] https://github.com/rust-lang/rust/issues/25353
- [x] https://github.com/rust-lang/rust/issues/25145
- [x] https://github.com/rust-lang/rust/issues/25051
- [x] https://github.com/rust-lang/rust/issues/25050
- [x] https://github.com/rust-lang/rust/issues/25036
- [x] https://github.com/rust-lang/rust/issues/24972
- [x] https://github.com/rust-lang/rust/issues/24957
- [ ] https://github.com/rust-lang/rust/issues/24956
- [ ] https://github.com/rust-lang/rust/issues/24955
- [x] https://github.com/rust-lang/rust/issues/24954
- [x] https://github.com/rust-lang/rust/issues/24947
- [ ] https://github.com/rust-lang/rust/issues/24877
- [x] https://github.com/rust-lang/rust/issues/24876
- [ ] https://github.com/rust-lang/rust/issues/24843
- [x] https://github.com/rust-lang/rust/issues/24841
- [x] https://github.com/rust-lang/rust/issues/24819
- [x] https://github.com/rust-lang/rust/issues/24810
- [ ] https://github.com/rust-lang/rust/issues/24761
- [x] https://github.com/rust-lang/rust/issues/24732
- [ ] https://github.com/rust-lang/rust/issues/24609
- [x] https://github.com/rust-lang/rust/issues/24599
- [x] https://github.com/rust-lang/rust/issues/24579
- [x] https://github.com/rust-lang/rust/issues/24561
- [ ] https://github.com/rust-lang/rust/issues/24520
- [ ] https://github.com/rust-lang/rust/issues/24469
- [x] https://github.com/rust-lang/rust/issues/24424
- [ ] https://github.com/rust-lang/rust/issues/24412
- [ ] https://github.com/rust-lang/rust/issues/24294
- [x] https://github.com/rust-lang/rust/issues/24204
- [x] https://github.com/rust-lang/rust/issues/24152
- [x] https://github.com/rust-lang/rust/issues/24106
- [x] https://github.com/rust-lang/rust/issues/24098
- [x] https://github.com/rust-lang/rust/issues/23992
- [x] https://github.com/rust-lang/rust/issues/23958
- [x] https://github.com/rust-lang/rust/issues/23891
- [x] https://github.com/rust-lang/rust/issues/23754
- [x] https://github.com/rust-lang/rust/issues/23707
- [ ] https://github.com/rust-lang/rust/issues/23667
- [x] https://github.com/rust-lang/rust/issues/23600
- [x] https://github.com/rust-lang/rust/issues/23524
- [x] https://github.com/rust-lang/rust/issues/23513
- [x] https://github.com/rust-lang/rust/issues/23458
- [ ] https://github.com/rust-lang/rust/issues/23407
- [x] https://github.com/rust-lang/rust/issues/23406
- [x] https://github.com/rust-lang/rust/issues/23370
- [x] https://github.com/rust-lang/rust/issues/23311
- [x] https://github.com/rust-lang/rust/issues/23281
- [x] https://github.com/rust-lang/rust/issues/23278
- [x] https://github.com/rust-lang/rust/issues/23217
- [x] https://github.com/rust-lang/rust/issues/23189
- [x] https://github.com/rust-lang/rust/issues/23175
- [ ] https://github.com/rust-lang/rust/issues/23110
- [x] https://github.com/rust-lang/rust/issues/23032
- [x] https://github.com/rust-lang/rust/issues/23003
- [ ] https://github.com/rust-lang/rust/issues/22933
- [x] https://github.com/rust-lang/rust/issues/22919
- [x] https://github.com/rust-lang/rust/issues/22894
- [x] https://github.com/rust-lang/rust/issues/22874
- [x] https://github.com/rust-lang/rust/issues/22872
- [x] https://github.com/rust-lang/rust/issues/22789
- [x] https://github.com/rust-lang/rust/issues/22781
- [ ] https://github.com/rust-lang/rust/issues/22713
- [x] https://github.com/rust-lang/rust/issues/22603
- [x] https://github.com/rust-lang/rust/issues/22566
- [x] https://github.com/rust-lang/rust/issues/22565
- [x] https://github.com/rust-lang/rust/issues/22465
- [x] https://github.com/rust-lang/rust/issues/22387
- [ ] https://github.com/rust-lang/rust/issues/22354
- [ ] https://github.com/rust-lang/rust/issues/21601
- [x] https://github.com/rust-lang/rust/issues/21599
- [x] https://github.com/rust-lang/rust/issues/21533
- [x] https://github.com/rust-lang/rust/issues/21461
- [x] https://github.com/rust-lang/rust/issues/21349
- [x] https://github.com/rust-lang/rust/issues/21335
- [x] https://github.com/rust-lang/rust/issues/21321
- [x] https://github.com/rust-lang/rust/issues/21275
- [x] https://github.com/rust-lang/rust/issues/21139
- [ ] https://github.com/rust-lang/rust/issues/21081
- [x] https://github.com/rust-lang/rust/issues/21073
- [x] https://github.com/rust-lang/rust/issues/20875
- [x] https://github.com/rust-lang/rust/issues/20847
- [x] https://github.com/rust-lang/rust/issues/20767
- [x] https://github.com/rust-lang/rust/issues/20753
- [x] https://github.com/rust-lang/rust/issues/20433
- [x] https://github.com/rust-lang/rust/issues/20319
- [x] https://github.com/rust-lang/rust/issues/20318
- [x] https://github.com/rust-lang/rust/issues/20108
- [x] https://github.com/rust-lang/rust/issues/20046
- [x] https://github.com/rust-lang/rust/issues/19675
- [x] https://github.com/rust-lang/rust/issues/19635
- [x] https://github.com/rust-lang/rust/issues/19500
- [x] https://github.com/rust-lang/rust/issues/19497
- [x] https://github.com/rust-lang/rust/issues/19397
- [x] https://github.com/rust-lang/rust/issues/19064
- [x] https://github.com/rust-lang/rust/issues/18953
- [x] https://github.com/rust-lang/rust/issues/18937
- [x] https://github.com/rust-lang/rust/issues/18027
- [x] https://github.com/rust-lang/rust/issues/17987
- [x] https://github.com/rust-lang/rust/issues/17391
- [x] https://github.com/rust-lang/rust/issues/16812
- [ ] https://github.com/rust-lang/rust/issues/16763
- [ ] https://github.com/rust-lang/rust/issues/16702
- [x] https://github.com/rust-lang/rust/issues/16229
- [x] https://github.com/rust-lang/rust/issues/15694
- [x] https://github.com/rust-lang/rust/issues/15522
- [x] https://github.com/rust-lang/rust/issues/15402
- [x] https://github.com/rust-lang/rust/issues/14505
- [x] https://github.com/rust-lang/rust/issues/14441 - not testable due to specific CPU needs
- [x] https://github.com/rust-lang/rust/issues/13727
- [x] https://github.com/rust-lang/rust/issues/13368

**Comment by bltavares** [comment]
I don't know how to reproduce #29249 on CI, as it requires a PII computer apparently.

**Comment by Gankro** [comment]
@bltavares you appear to have linked to this issue itself?

**Comment by bltavares** [comment]
@Gankro my bad #14441

**Comment by steveklabnik** [comment]
@bltavares hmmm, yes, that's a tough one. Maybe it's too much effort, and should just be checked off the list?

**Comment by bltavares** [comment]
@steveklabnik I think it makes sense to be checked here. What about adding a note to skip certain ICEs on Glacier?

**Comment by steveklabnik** [comment]
I checked it off and left a note.

**Comment by bltavares** [comment]
rust-lang/rust#15522 is a Windows bug and the initial files used to report the issue are not available anymore.

**Comment by bltavares** [comment]
#18937 Does not produce ICE, but is unsound according to the discussion and would better produce ICE.

**Comment by bltavares** [comment]
#18953 Is stale and needs test case. Was initially found on Zinc.

**Comment by bltavares** [comment]
#19497 Has no code to reproduce. Not sure what to do over there.

**Comment by bltavares** [comment]
#19500 Has no code to reproduce.

**Comment by bltavares** [comment]
#19635 Has no code to reproduce.

**Comment by bltavares** [comment]
#19675 has been closed already.

**Comment by emoon** [comment]
#26886 Doesn't seem to be an issue anymore and is marked with E-needstest

**Comment by steveklabnik** [comment]
Thank you both for all of your work here! This is great :100:

**Comment by bltavares** [comment]
@steveklabnik Thanks for showing a simple way to contribute back. (:

**Comment by bltavares** [comment]
#20767 Is stale and needs a compiling example

**Comment by bltavares** [comment]
#21275 Is stable and needs an example code

**Comment by bltavares** [comment]
#21321The author says it could have been fixed already, but the author is not sure (nor am I)

**Comment by bltavares** [comment]
#21349 Is stale and needs a small reproducible example.

**Comment by wheals** [comment]
#21461 was closed by the reporter as fixed by #26667.

**Comment by bltavares** [comment]
#24956 has been closed by #29284

**Comment by emoon** [comment]
These seems to have been closed

https://github.com/rust-lang/rust/issues/24957
https://github.com/rust-lang/rust/issues/24956

**Comment by bltavares** [comment]
#24947 No loger ICE

**Comment by bltavares** [comment]
#23370 has been closed already.

**Comment by bltavares** [comment]
#23003 has been closed.

**Comment by ville-h** [comment]
https://github.com/steveklabnik/glacier/blob/master/src/27954.rs appears to have been added but not marked as such

**Comment by tamird** [comment]
https://github.com/rust-lang/rust/issues/24956 is incorrectly marked; this issue was never resolved and is reopened.

**Comment by steveklabnik** [comment]
whoops! must have messed that up :(

**Comment by wldcordeiro** [comment]
I'll take on a couple if someone can mentor, I really want to learn me some more Rust by contributing to Rust. :smile:

**Comment by steveklabnik** [comment]
@wldcordeiro sure thing! Basically, pick one of the unchecked things, find the code that causes the compiler to crash, and then make a PR to steveklabnik/glacier that looks like this: https://github.com/steveklabnik/glacier/blob/master/src/15694.rs

File name is the issue number, and it's just the code.

I can help in real time if you drop by IRC.

**Comment by wldcordeiro** [comment]
Thanks @steveklabnik BTW: These are already closed.

- #27321
- #27190 
- #26056
- #25693
- #25353
- #25036
- #24152 
- #24098 
- #23754 
- #23217 
- #22465
- #21533
- #17391

**Comment by steveklabnik** [comment]
Thank you! Checked those off the list.

**Comment by emoon** [comment]
I did a pass on the remaining issues in the list. All of them are non-trivial to add to the current way the tests are being done now and can't be reproduced with a single source file.

So I'm not sure what would be the best way to proceed on the remaining issues without trying to make the testing script a bit more advanced (needs to be able to clone stuff on git, run cargo, or compile with rustc using specific flags to trigger issues in some cases)

**Comment by emoon** [comment]
Seems that https://github.com/rust-lang/rust/issues/29052 is closed now

**Comment by steveklabnik** [comment]
This list is basically done, I think; the remaining ones are not automatable. Thanks everyone!
