### ISSUE TITLE
E0211 can be triggered for different reasons

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#29248]
Both

```rust
#![feature(intrinsics)]

extern "rust-intrinsic" {
    fn size_of<T>(); // error: intrinsic has wrong type
}
```

and 

```rust
use std::rc::Rc;
struct Foo;

impl Foo {
    fn x(self: Rc<Foo>) {} // (Only Box<Self>, &Self, Self, or &mut Self work as explicit self params)
}
```

trigger E0211. The error index only handles the first (https://doc.rust-lang.org/error-index.html#E0211)

We should expand the help text to mention all cases that can trigger this error.

cc @GuillaumeGomez @AlisdairO

**Comment by Manishearth** [comment]
The cases are:

 - When a range has mismatched types (e.g. `1u8...1i8`)
 - When a start or main function has the wrong signature
 - When an intrinsic has the wrong type
 - When the self type is not amongst `Box<Self>, &Self, Self, &mut Self`

**Comment by GuillaumeGomez** [comment]
Thanks for reporting it! I'll try fixing it by the end of the week-end.

**Comment by steveklabnik** [comment]
Did the PR fix this?

**Comment by GuillaumeGomez** [comment]
Yup !

**Comment by Manishearth** [comment]
#29260
