### ISSUE TITLE
build from source failed to find shared object

### ISSUE THREAD

**Issue by HuStmpHrrr** [rust-lang/rust#29269]
In Debian Jessie, clone to local and build.  then:

```bash
./configure --prefix=$some_path
make && make install
```
since rust is in fast iteration, I try to avoid to have the files copied to system folders.

however, 

```
$ bin/rustc
./rustc: error while loading shared libraries: librustc_driver-bb943c5a.so: cannot open shared object file: No such file or directory
$ find . -type f -name '*.so' | grep librustc_driver-bb943c5a.so
50:./lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_driver-bb943c5a.so
54:./lib/librustc_driver-bb943c5a.so
```

therefore I doubt it's the linking problem.

```
$  export LD_LIBRARY_PATH=$PWD/lib
$ bin/rustc # working this time
```
if `LD_LIBRARY_PATH` is not set and `ldconfig` is not setup, 

```
$ ldd rustc
        linux-vdso.so.1 (0x00007ffc8a7f7000)
        librustc_driver-bb943c5a.so => not found
        libstd-bb943c5a.so => not found
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4df1b93000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4df213d000)
```
so I am wondering if it's intended? I think shared object linking can be setup while compiling, can't it?

I installed several software in the same way, and rustc is the first one I have dynamic linking issue.

**Comment by zazdxscf** [comment]
I think
`    --enable-rpath                   build rpaths into rustc itself`
to `./configure` but I'm unsure

(I'm a newbie btw)

**Comment by alexcrichton** [comment]
Yes this is currently intended behavior, it's recommended for developing rustc to pass `--enable-rpath` but otherwise the compiler doesn't do that by default (and the compiler also probably shouldn't be running ldconfig). As this is intended, though, I'm going to close.
