### ISSUE TITLE
A tab before an opening ``` panics doc tests

### ISSUE THREAD

**Issue by Stebalien** [rust-lang/rust#29268]
When a tab appears between /// and ``` in documentation code examples:

```
///<tab>```
///<tab>println!("here");
///<tab>```
```

The doc tests fail with:

```
<stdin>:2:5: 2:6 error: unknown start of token: `
<stdin>:2     ```
              ^
thread '<unnamed>' panicked at 'Box<Any>', ../src/libsyntax/parse/lexer/mod.rs:167
```

The worst part is that this tab looks like a space when tabwidth is set to 4.

**Comment by Stebalien** [comment]
Note: this doesn't happen when preceded by other doc text:
```
///<tab>a
///<tab>```
///<tab>println!("here");
///<tab>```
```

**Comment by mitaa** [comment]
This is fixed (though a rustdoc test in addition to the unit tests would be nice?)
