### ISSUE TITLE
`Hash::hash`'s type parameter should be `?Sized`

### ISSUE THREAD

**Issue by apasel422** [rust-lang/rust#29263]
The `Hasher` trait is not `Sized`, but `Hash::hash` is defined to take a sized type parameter. This prevents code like the following from working:

```rust
use std::hash::{Hash, Hasher};

fn bar(hasher: &mut Hasher) {
    1.hash(hasher);
}

fn main() {}
```

**Comment by apasel422** [comment]
Changing this now would be a breaking change, however, as all manual implementors would need to be updated.

**Comment by alexcrichton** [comment]
If this requires changing all implementors I think our hands may unfortunately be tied on this one

**Comment by apasel422** [comment]
Yeah, I guess this isn't going to be possible.
