### ISSUE TITLE
Memory leaks with diverging functions

### ISSUE THREAD

**Issue by DenisKolodin** [rust-lang/rust#29277]
Some external C libs uses `setjmp` as exceptions. I have function declared as diverging which does `longjmp` inside and never returns. But some data have lost if it was allocated in a heap:
```rust
pub fn jmp_outside() -> ! {...}

fn called_from_c() -> u32 {
    let s1 = String::new();
    {
        let s2 = String::new();
        {
            let s3 = String::new();
            // innermost checks....
            jmp_outside();
        }
    }
    // normal return
    0
}
```
Why diverging functions doesn't clean up locally heap allocations? I think that's dangerous behaviour. Never returns doesn't mean panics and fails only. Program can still be running. Is it possible to fix?

**Comment by petrochenkov** [comment]
Ha! Even C++, including `longjmp` as its official part, explicitly documents jmp-ing over destructors as undefined behavior (see C++ standard: 18.10 Other runtime support [support.runtime]).

**Comment by DenisKolodin** [comment]
The idea isn't jump over destructors. I can prevent leaks with construction like:
```rust
let res: Result<u32, ()> = {
    // do some allocations
};
match res {
  Ok(v) => v,
  Err(_) => jmp_outside(),
}
```
But why impossible to drop locals before diverging function will called? I find it convenient and safe.

**Comment by sfackler** [comment]
It wouldn't really be enough to drop locals of that frame - what about functions higher up the stack?

**Comment by DenisKolodin** [comment]
> about functions higher up the stack
In this case it becomes undefined behavior )

Did I understand correctly that I have to unwind stack manually with deallocating any until It will ready to jump because It's impossible to comprehend which must to be deallocated and where to stop unwindinwg?

**Comment by alexcrichton** [comment]
This is in general just a problem with this form of control flow, you've got to worry about local cleanups present on the stack both on the current frame and above. A change such as this would be a change in language semantics, and as a result is more appropriate in the RFC repo rather than this one.

I have personally also had this bite me in the past quite a bit, so it's one where perhaps a lint could be useful from time to time.

**Comment by DenisKolodin** [comment]
Thank you!
