### ISSUE TITLE
rustdoc: Show package version in the generated documentation when invoked through `cargo doc`

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust#29275]
It would be useful for users to know for which version of a package they are reading the documentation for.

This would be especially helpful in identifying outdated documentation online, which there is an abundance of.

**Comment by steveklabnik** [comment]
Triage: no change.

@crumblingstatue given this is about `cargo doc`, if you still care about this, could you open it up on the cargo repository instead? Thanks!

**Comment by crumblingstatue** [comment]
@steveklabnik Sure, but this would require support in rustdoc itself.
