### ISSUE TITLE
make -j4 NO_REBUILD=1   while compiling rust from git sources will fail

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#29271]
`make -j4 NO_REBUILD=1`
Fails with 

``` bash
/bin/sh: x86_64-unknown-linux-gnu/stage2/bin/rustdoc: No such file or directory
/home/zazdxscf/build/1nonpkgs/rust/rust/mk/docs.mk:138: recipe for target 'doc/grammar.html' failed
make: *** [doc/grammar.html] Error 127
make: *** Waiting for unfinished jobs....
```

Tried to report it here: https://github.com/rust-lang/rust/issues/14461#issuecomment-148112585 but that one's closed and I cannot reopen it.

Workaround: Use `-j1` instead of `-j4`,  or `-j4` and don't specify `NO_REBUILD=1`

**Comment by alexcrichton** [comment]
Make's gone now, so closing.
