### ISSUE TITLE
The book still flips the example links to the playpen

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#29308]
Go [here](http://doc.rust-lang.org/nightly/book/crates-and-modules.html#importing-modules-with-use) and mouse over the first example. The link is inverted without the new background. This should be updated.

**Comment by tbu-** [comment]
Curious. Why does this happen? :)

**Comment by mdinger** [comment]
I have no idea. I've tried `grep -r 'transform: scaleX' rust_src` and it always comes up empty except for where the book uses it. Maybe the nightly docs folder needs to be erased before the next doc set is built.

I'm trying rebuilding the docs to see if it helps so we'll see.

**Comment by mdinger** [comment]
Ah, I see. Rust maintains the transformations [separately](https://github.com/rust-lang/rust/blob/e02ada6d383459f372ab6f277f25e5e986a60ed8/src/doc/rust.css#L341-L349) for the book and rustdoc. They both need to be updated to fix it.
