### ISSUE TITLE
is_symlink() always returns false on linux

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust#29302]
test.rs:
```rust
use std::fs;

fn main() {
	println!("{}", fs::metadata("b").unwrap().file_type().is_symlink());
}
```

Commands:
```
> touch a
> ln -s a b
> rustc test.rs
> ./test
false
```

It doesn't work for directory symlinks either.

**Comment by nagisa** [comment]
Interestingly 

```c
#include<sys/stat.h>

int main(){
    struct stat sb;
    stat("tc", &sb);
    printf("%d %d\n", S_ISLNK(sb.st_mode), (sb.st_mode & S_IFMT) == S_IFLNK);
    return 0;
}
```
also prints a `0 0`…

**Comment by nagisa** [comment]
The problem here is that `stat`/`metadata` follows symbolic links. You must use [`symlink_metadata`](http://doc.rust-lang.org/stable/std/fs/fn.symlink_metadata.html) to retrieve information about file without following symbolic links.

**Comment by Diggsey** [comment]
@nagisa Ah, you're right, still I think it would be useful to mention that in the documentation for `is_symlink()` itself...
