### ISSUE TITLE
Rustdoc get confused by multiple level of re-exporting.

### ISSUE THREAD

**Issue by Luthaf** [rust-lang/rust#29319]
Using the following code, 

```rust
mod foo {
    mod bar {
        /// the Baz struct
        pub struct Baz;
    }
    pub use self::bar::Baz;
}

pub use foo::*;
```

`rustdoc` produce this output:

![capture d ecran de 2015-10-26 11 40 08](https://cloud.githubusercontent.com/assets/6141587/10727034/11826c66-7bd7-11e5-85ff-3e851e42b2f4.png)

With no link to `Baz`, and the link to `bar` leading to a blank page.

Changing `pub use foo::*;` to `pub use foo::Baz;` still produce a wrong ouptut:

![capture d ecran de 2015-10-26 11 49 26](https://cloud.githubusercontent.com/assets/6141587/10727135/ca7aa4b8-7bd7-11e5-99d9-81ac43b21ea2.png)

#### Meta: 

```
$ rustdoc --version
rustdoc 1.3.0 (9a92aaf19 2015-09-15)
$ rustc --version 
rustc 1.3.0 (9a92aaf19 2015-09-15)
```

**Comment by nagisa** [comment]
cc https://github.com/rust-lang/rust/issues/24305

**Comment by Eljay** [comment]
Works correctly on nightly:
![image](https://cloud.githubusercontent.com/assets/6574/10803752/be3e61d6-7dbb-11e5-9f01-ca376376ca78.png)

**Comment by steveklabnik** [comment]
@Luthaf could you try on nightly and confirm @Eljay 's findings?

**Comment by Luthaf** [comment]
I confirm this is fixed on nightly!
