### ISSUE TITLE
Despite using `if let`, `match arms have incompatible types`

### ISSUE THREAD

**Issue by GBGamer** [rust-lang/rust#29314]
```rust
fn main() {
    if let Some(b) = None {
       ()
    } else {
         1
    }
}
```

errors with

```
error: match arms have incompatible types:
````

**Comment by jonas-schievink** [comment]
This is not a bug, if let desugars to a match internally

**Comment by apasel422** [comment]
Yes, as @jonas-schievink said, this is the intended behavior.

**Comment by GBGamer** [comment]
@apasel422 yes I know it desugars to a match, that does not mean that it is not a bug.

**Comment by apasel422** [comment]
@GBGamer Ah, I see, this is specifically about the error message. Re-opening.

**Comment by GBGamer** [comment]
@apasel422 thanks :)
