### ISSUE TITLE
Separate templates from rustdoc source

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#29323]
If you want to modify anything about the way that rustdoc outputs HTML, you end up having to edit rustdoc's source. This causes a really long cycle time, as you have to re-compile rustdoc on each change.

Many people I've talked to about editing rustdoc's output have said "well, just show me where the template is, and I'll change it", and the answer is :sob: 

The only real issue with this is that to do it right, we'd end up having a dependency on a template system, because re-implementing one doesn't seem like the right idea as well. I'm not sure if that's an acceptable tradeoff or not.

**Comment by steveklabnik** [comment]
@alexcrichton points out to me that an issue with this is we'd still want to distribute said templates inside of rustdoc itself, which means ultimately, still re-building rustdoc. Not sure if there could be some sort of "load template from here" switch or something, which would help iteration time during development.

**Comment by nagisa** [comment]
We already have attributes for logo and whatnot. I don’t see why we couldn’t have one for a directory to some sort of well specified templates.

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by steveklabnik** [comment]
Triage: no real movement on this

**Comment by Mark-Simulacrum** [comment]
I'm going to go ahead and close this as this ultimately is a "rustdoc is slow to build for the first time" issue and this isn't really the right issue to track that. FWIW, I do think that we can make significant progress on that issue and maybe even solve it outright, but it'll take some legwork in bootstrap.
