### ISSUE TITLE
Trait-objects need associated-types of subtraits to be specified even when that's already done by the boxed trait

### ISSUE THREAD

**Issue by qrlpx** [rust-lang/rust#29328]
If someone has a shorter/more conclusive title in mind, shoot.

### code
```rust
trait Foo {
    type Bar;
}

trait FooBar: Foo<Bar = String> {}

struct Arb {
    foobar: Box<FooBar>,
}
```
__Playpen__: http://is.gd/6QKndB
### output
```
test.rs:8:17: 8:23 error: the value of the associated type `Bar` (from the trait `Foo`) must be specified [E0191]
test.rs:8     foobar: Box<FooBar>,
                          ^~~~~~
test.rs:8:17: 8:23 help: run `rustc --explain E0191` to see a detailed explanation
error: aborting due to previous error
```
### rustc version
```
rustc 1.5.0-nightly (0be1bcd06 2015-10-24)
```

**Comment by arielb1** [comment]
I would like to claim that this is a part of "non-supertrait predicates are not elaborated", but this quite ugly.

However, with the current acyclicity requirements, this would break stuff like
```Rust
trait Foo : Iterator where Self::Item: Copy {}
```

Maybe just give them the `ProjectionPredicate` treatment?

Maybe we need to have both "supertrait pre

**Comment by gwillen** [comment]
I just hit this issue and discovered this bug by searching. I don't understand most of the words in the comment explaining why this behavior is this way. :-) But it's definitely a weird UX issue, in that it's not at all obvious to a user why it would do this.

**Comment by Wyverald** [comment]
This also makes it hard to parameterize associated types.

```rust
trait Foo { type Bar; }
trait Foobar<T> : Foo<Bar=T> {}
struct Quux<'a> {
    foobar: &'a Foobar<String>,
}
```

That doesn't compile. I'll need to write `foobar: &'a Foobar<String, Bar=String>` instead.

**Comment by durka** [comment]
In combination with Fn traits, this seems like a hole in stability! Check out [this code](http://is.gd/EcgqRj):

```rust

trait FnAlias: Fn() {}
impl<T: Fn()> FnAlias for T {}

fn main() {
    let _: FnAlias;            // error
    let _: FnAlias<Output=()>; // no error, but I shouldn't be able to do this!
}
```

Normally I can't write an Fn trait while specifying the return type as an associated type, at least without `#![feature(unboxed_closures)]`. But here I have to.

**Comment by peterhj** [comment]
Appears to be the same as #23856 and possibly #24010?

**Comment by bstrie** [comment]
Tagging with A-stability based on durka's comment.

**Comment by nikomatsakis** [comment]
So while it's true that this bug allows you to name the `Output` parameter, in a sense, of the `Fn` traits, which we are normally not permitting, I don't think there is any plan to change the `Fn` traits in a way that would make this a *problem*. Still, an interesting thing.

**Comment by nikomatsakis** [comment]
In particular, we are more concerned about the *input argument* types, which may want to become variadic or otherwise change.

**Comment by nikomatsakis** [comment]
triage: P-medium

**Comment by nikomatsakis** [comment]
Closing as dup of #24010
