### ISSUE TITLE
API Docs: array

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#29331]
Part of https://github.com/rust-lang/rust/issues/29329

http://doc.rust-lang.org/std/primitive.array.html

Good things to do here: make sure to explain the type level integers / ergonomic issues, point out that most methods happen on slices, talk about `.iter()` inference weirdness.

**Comment by kmcallister** [comment]
Going to work on this.

**Comment by kmcallister** [comment]
Looks like some of this was done in e173ead68458da5c4cb241f3d105abc87c529071.

**Comment by matthew-piziak** [comment]
@kmcallister Yep. I didn't add any exposition about `.iter()` behavior though. Some of that would definitely be helpful.

**Comment by kmcallister** [comment]
@steveklabnik: Can you explain what you mean by "`.iter()` inference weirdness."?

**Comment by steveklabnik** [comment]
@kmcallister breifly (and I'll try to elaborate more later if this doesn't make sense) but it's about how sometimes, you have to explicitly call `.iter()` on an array whereas it would be inferred with vec through a for loop

    let a = [1, 2, 4, 5, 6];
    
    for e in a {
        println!("{}", e);
    }

fails, for example

**Comment by frewsxcv** [comment]
Opened up a tangential issue: https://github.com/rust-lang/rust/issues/36391
