### ISSUE TITLE
API Docs: ascii

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#29341]
Part of https://github.com/rust-lang/rust/issues/29329

http://doc.rust-lang.org/std/ascii/

**Comment by steveklabnik** [comment]
I am happy to mentor anyone who wants to tackle this issue.

**Comment by eugene-bulkin** [comment]
What exactly still needs to be documented for this module? Doesn't look like a whole lot is in there.

**Comment by steveklabnik** [comment]
Hey @eugene-bulkin ! Some of these issues were opened as just a "make sure we check these docs at least once.", so in some sense, you've already helped!

Things I'd note:

* The module-level docs are extremely short. There's not a lot to this module, but adding some extra context, for example, that most stuff in rust is utf-8, and a short summary of the two things in it would be good.
* https://doc.rust-lang.org/std/ascii/struct.EscapeDefault.html should look more like https://doc.rust-lang.org/stable/std/iter/struct.Chain.html, that is, it doesn't follow our standard "this is an iterator method" boilerplate, complete with linking up the function that makes it
* https://doc.rust-lang.org/std/ascii/fn.escape_default.html is pretty decent, but an example for each of those rules would be awesome.
* https://doc.rust-lang.org/std/ascii/trait.AsciiExt.html looks pretty good. Using 'utf8' as variable names isn't great here though, as ASCII and UTF-8 are compatible, that is, all valid ASCII is also valid UTF-8, so maybe making sure to re-word this as "ascii and non-ascii" rather than "ascii and utf-8" would be better.

That's about it I think! I'd love a PR for any part of this, or all of it if you have the time.

**Comment by eugene-bulkin** [comment]
I'm currently out of town so I won't be able to do anything for a week but if no one has claimed this by the time I get back I'll gladly take it on!

**Comment by eugene-bulkin** [comment]
Hey, I'm back from vacation and it looks like no one's claimed it, so I'll take it on!

**Comment by lukaramu** [comment]
I think this issue can be closed (as of #40988); the docs look pretty good now, as everything @steveklabnik noted [above] seems to be addressed! :tada:

[above]: https://github.com/rust-lang/rust/issues/29341#issuecomment-287779907

**Comment by steveklabnik** [comment]
woo!
