### ISSUE TITLE
API Docs: std::floating point stuff

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#29353]
Part of https://github.com/rust-lang/rust/issues/29329

like http://doc.rust-lang.org/std/f32/ pretty sure these are generated too, for all of them.

Here's what's needed to close out this issue:

- [ ] [the module docs](https://doc.rust-lang.org/std/f32/) should have a bit more about why this module exists.

**Comment by steveklabnik** [comment]
I am happy to mentor anyone who wants to tackle this issue.

**Comment by palango** [comment]
Hej @steveklabnik , what do you think about the following description?
> This module provides access to properties and bounds of this floating point data type. Furthermore mathematical constants are provided in the `consts` module.

**Comment by steveklabnik** [comment]
Hey @palango,

I like it. We should ask @rust-lang/libs though, why are some of these constants in `consts` and some are not?

**Comment by palango** [comment]
I guess the `std::f32` module is for data-type specific constants, whereas `std::f32::consts` is for mathematical constants with the possible accurcy.

**Comment by frewsxcv** [comment]
Do we want to consider #41122 a full solution here? Do we want to expand the docs a bit more?
