### ISSUE TITLE
API Docs: hash

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#29357]
Part of https://github.com/rust-lang/rust/issues/29329

http://doc.rust-lang.org/std/hash/

Here's what needs to be done to close out this issue: 

- [ ] [`BuildHasherDefault`](https://doc.rust-lang.org/std/hash/struct.BuildHasherDefault.html) needs a stronger summary/explanation distinction. "This structure is zero-sized and does not need construction." is weird.
- [ ] [`BuildHasher`](https://doc.rust-lang.org/std/hash/trait.BuildHasher.html) also needs a stronger summary/explanation distinction.  It also needs a better explanation of why it exists with an example.
- [ ] [`Hash`](https://doc.rust-lang.org/std/hash/trait.Hash.html) needs general improvement, it is the main bit of this module, but its docs feel tossed together and have few examples or coherence.
- [ ] [`Hasher`](https://doc.rust-lang.org/std/hash/trait.Hasher.html) needs more than just a summary line; it needs explanation and examples.

**Comment by adrianbrink** [comment]
What kind of further documentation are you looking for here? @steveklabnik

**Comment by steveklabnik** [comment]
Better explanations for https://doc.rust-lang.org/std/hash/struct.BuildHasherDefault.html

examples of implementing https://doc.rust-lang.org/std/hash/trait.BuildHasher.html and https://doc.rust-lang.org/std/hash/trait.Hash.html and https://doc.rust-lang.org/std/hash/trait.Hasher.html and more docs generally for all three.

**Comment by piordanov** [comment]
There seem to be a lengthy example of BuildHasherDefault added in this commit (https://github.com/rust-lang/rust/commit/d409fc378ca46fca6fb0b0b986b0f11cfc62eb8f)

Also for BuildHasher and Hash.html there is a healthy amount of documentation as of now. Hasher seems to be really outdated (still lists several Implementors without mentioning they have been deprecated), which I'm looking into right now.

**Comment by brson** [comment]
Thanks @piordanov ! Looks like all that's left is documenting `Hasher`.

**Comment by steveklabnik** [comment]
I am happy to mentor anyone who wants to tackle this issue.

**Comment by adrianbrink** [comment]
@steveklabnik I volunteer as a tribute :-)

**Comment by steveklabnik** [comment]
@adrianbrink wonderful! If you need any help, please just let me know, as I said above, happy to help you help me 😄 (We can do it here or ping me on IRC)

**Comment by steveklabnik** [comment]
@adrianbrink I have added more specifics in the main issue above

**Comment by lukaramu** [comment]
I'm gonna tackle this one this weekend!
