### ISSUE TITLE
API Docs: option

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#29366]
Part of https://github.com/rust-lang/rust/issues/29329

http://doc.rust-lang.org/std/option/

**Comment by leodasvacas** [comment]
In the `as_mut` and `iter_mut` examples, a match is used with a `None => {}` arm. `if let` would be more idiomatic.

**Comment by devonhollowood** [comment]
In the documentation for `unwrap_or` (and maybe for related methods like `ok_or` and `or`), it would be nice to make a note that the arguments to a function are always fully evaluated, meaning that 

    fn foo(opt: Option<Bar>) -> Bar {
        let bar = opt.unwrap_or(return Bar::new());
        bar.baz()
    }

 will always return `Bar::new()` instead of `opt.unwrap().baz()`, even if opt is `Some(_)`. This seems like a pitfall otherwise.

**Comment by steveklabnik** [comment]
I am happy to mentor anyone who wants to tackle this issue.

**Comment by irfanhudda** [comment]
@steveklabnik I'd like to help on this.

**Comment by steveklabnik** [comment]
@irfanhudda awesome! Let me know if I can help you help us in any way :)

**Comment by irfanhudda** [comment]
@steveklabnik Module level docs look fine here. I think the documentation of `IntoIter`, `Iter` and `IterMut` structs can be improved. Do we also need examples for these?

**Comment by steveklabnik** [comment]
Oh, I just noticed I didn't add a checklist for this issue!

They do not need examples, but they should follow the standard iterator boilerplate: https://doc.rust-lang.org/stable/std/iter/struct.SkipWhile.html

> An iterator that rejects elements while predicate is true.
> 
> This struct is created by the skip_while() method on Iterator. See its documentation for more.

**Comment by lukaramu** [comment]
I think this issue can be closed (as of #40999); the docs look pretty good now!

**Comment by steveklabnik** [comment]
:D
