### ISSUE TITLE
API Docs: path

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#29368]
Part of https://github.com/rust-lang/rust/issues/29329

http://doc.rust-lang.org/std/path/

Here's what's needed to close out this issue:

- [ ] [`Components`](https://doc.rust-lang.org/std/path/struct.Components.html) should use the standard iterator boilerplate.
- [ ] [`Display`](https://doc.rust-lang.org/std/path/struct.Display.html) needs some more explanation and a link to the `display` method.
- [ ] [`Iter`](https://doc.rust-lang.org/std/path/struct.Iter.html) should use the standard iterator boilerplate.
- [ ] [`PrefixComponent`](https://doc.rust-lang.org/std/path/struct.PrefixComponent.html) needs general expansion and examples
- [ ] [`StripPrefixError`](https://doc.rust-lang.org/std/path/struct.StripPrefixError.html) needs a shorter summary and a link to the method it comes from.
- [ ] [`Component`](https://doc.rust-lang.org/std/path/enum.Component.html) shouldn't say to refer to the module, we should move most of its docs here.
- [ ] [`Prefix`](https://doc.rust-lang.org/std/path/enum.Prefix.html) could use more explanation, and `is_verbatim` needs an example.

**Comment by mgattozzi** [comment]
@steveklabnik I'd be willing to help further document this module. Are there any trouble spots in particular that could use further clarification or items within the module that could use more documentation or examples?

**Comment by steveklabnik** [comment]
@mgattozzi things I can see right now:

1. some stuff could use examples, not just on the individual methods, but also generally
2. https://doc.rust-lang.org/std/path/struct.Iter.html should link to the method that creates it, see the various iterator structs in `std::iter` for some boilerplate text.

**Comment by mgattozzi** [comment]
Alright I'll start working on it this week. I'll link the branch I'll be working on here once I start so anyone can look at the progress, then put in a PR when it's ready.

**Comment by steveklabnik** [comment]
I am happy to mentor anyone who wants to tackle this issue.

**Comment by lukaramu** [comment]
I'm gonna work on this one!
