### ISSUE TITLE
API Docs: net

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#29363]
Part of https://github.com/rust-lang/rust/issues/29329

http://doc.rust-lang.org/std/net/

Here's what needs to be done to close out this issue: 

- [ ] [the module documentation](https://doc.rust-lang.org/std/net/) is very tiny and needs expanded.
- [ ] [`ParseError`](https://doc.rust-lang.org/std/net/struct.AddrParseError.html) needs to link to where it comes from and have examples.
- [ ] [`Incoming`](https://doc.rust-lang.org/std/net/struct.Incoming.html) should use the standard iterator boilerplate and move its semantics into the method docs.
- [ ] [`Ipv4Addr`](https://doc.rust-lang.org/std/net/struct.Ipv4Addr.html) needs better top-level docs and should link to `IpAddr`
- [ ] many places in these docs should say "IETF RFC" rather than "RFC", as we have Rust RFCs as well.
- [ ] [`Ipv6Addr`](https://doc.rust-lang.org/std/net/struct.Ipv6Addr.html) same as `Ipv4Addr`.
- [ ] [`SocketAddrV4`](https://doc.rust-lang.org/std/net/struct.SocketAddrV4.html) has poor top-level docs and needs to have a defined summary/explanation split. Its methods are okay, but very short. It needs to link to `SocketAddr`.
- [ ] [`SocketAddrV6`](https://doc.rust-lang.org/std/net/struct.SocketAddrV6.html) same
- [ ] [`TcpListener`](https://doc.rust-lang.org/std/net/struct.TcpListener.html)'s docs don't really say what it is.
- [ ] [`TcpStream`](https://doc.rust-lang.org/std/net/struct.TcpStream.html)'s the same.
- [ ] [`UpdSocket`](https://doc.rust-lang.org/std/net/struct.UdpSocket.html) is the same.
- [ ] [`IpAddr`](https://doc.rust-lang.org/std/net/enum.IpAddr.html) should link to an IETF RFC
- [ ] [`Shutdown`](https://doc.rust-lang.org/std/net/enum.Shutdown.html) should use the standard boilerplate 
- [ ] [`SocketAddr`](https://doc.rust-lang.org/std/net/enum.SocketAddr.html) has very short docs.
- [ ] [`ToSocketAddrs`](https://doc.rust-lang.org/std/net/trait.ToSocketAddrs.html) needs a lot of links.

**Comment by apoelstra** [comment]
Hi,

https://doc.rust-lang.org/std/net/struct.Incoming.html

Says that the `Incoming` iterator will return an infinite list of incoming connections. In fact, it may error out (for example if the system runs out of file descriptors) and return an infinite list of errors, with no delays in between. A naive "log and retry" loop may become a spinloop in this case, pegging the CPU and/or filling log space.

**Comment by steveklabnik** [comment]
I am happy to mentor anyone who wants to tackle this issue.

**Comment by lukaramu** [comment]
I'm gonna try to tackle (parts of?) the docs for `TcpListener` & `TcpStream`, especially with regard to #40322 since I've been digging information for that up anyway.
