### ISSUE TITLE
API Docs: std::mem

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#29362]
Part of https://github.com/rust-lang/rust/issues/29329

http://doc.rust-lang.org/std/mem/

**Comment by GuillaumeGomez** [comment]
I don't see anything to do here.

**Comment by steveklabnik** [comment]
This module is mostly about quality; the module documentation is quite light, as are the individual functions.

**Comment by kmcallister** [comment]
I'll take a look at the `mem` docs today.

**Comment by kmcallister** [comment]
PR is #36357.
