### ISSUE TITLE
LLVM assertion: Can only indirectify direct input operands!

### ISSUE THREAD

**Issue by Amanieu** [rust-lang/rust#29382]
The following code triggers an LLVM assert:

``` rust
#![feature(asm)]
unsafe fn test(x: *mut u32) {
    asm!("": "=m" (*x));
}
```

```
rustc: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp:6012: void llvm::SelectionDAGBuilder::visitInlineAsm(llvm::ImmutableCallSite): Assertion `(OpInfo.isMultipleAlternative || (OpInfo.Type == InlineAsm::isInput)) && "Can only indirectify direct input operands!"' failed.
```

One thing of note in the LLVM output is this line:

``` llvm
%5 = call i32 asm "", "=m,~{dirflag},~{fpsr},~{flags}"(), !dbg !199, !srcloc !201
```

Note that the operand to the asm is left empty for some reason, which is probably wrong.

**Comment by Amanieu** [comment]
Here is what clang generates for equivalent code, it seems to translate "m" and "=m" into "*m" and "=*m":
```llvm
call void asm "", "=*m"(i32* %2) #1, !srcloc !3
```

Using the =*m constraint directly from rust is difficult because type checking treats it as an output even though the parameter is an input pointer value.

**Comment by brson** [comment]
Still repros.

**Comment by steveklabnik** [comment]
paypen repro: https://is.gd/rUbnON

**Comment by eddyb** [comment]
@Amanieu By `_` you mean `*`?

**Comment by Amanieu** [comment]
@eddyb yes

**Comment by eddyb** [comment]
@Amanieu We should update the compiler to treat `=*m` as write to `*output`, I guess.
Maybe MIR borrowck will be able to handle it better *shrug*.

**Comment by istankovic** [comment]
Still a problem with `rustc 1.26.0-nightly (adf2135ad 2018-03-17)`.

**Comment by Amanieu** [comment]
This issue does not apply to the new `asm!` ([RFC 2850](https://github.com/rust-lang/rfcs/pull/2850)) which doesn't support memory constraints.

The legacy `llvm_asm!` is deprecated and is no longer maintained.
