### ISSUE TITLE
Rust Book Grammatical Error

### ISSUE THREAD

**Issue by ddrouin** [rust-lang/rust#29401]
In The Stack and Heap section:

"There’s some important things we have to take note of here."

is slightly incorrect because there's is usually considered as a contraction for there is. Although according to this: http://english.stackexchange.com/questions/12865/is-therere-similar-to-theres-a-correct-contraction maybe it's acceptable.  Nonetheless it would be better to write:

"There are some important things we have to take note of here."

**Comment by steveklabnik** [comment]
Thank you! I would accept a patch for that change.

If anyone would like to try to fix this, I'm willing to help. The source is in `src/doc/trpl/the-stack-and-the-heap.md`, just the text needs changed.
