### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by klemen-forstneric** [rust-lang/rust#29407]
There's an error in the documentation: http://doc.rust-lang.org/std/#primitives.

At usize, it says: "The pointer-sized **signed** integer type.". It should instead say: "The pointer-sized **unsigned** integer type."

**Comment by steveklabnik** [comment]
Thanks for reporting! Anyone who wants to try fixing this, I'd be happy to help!

**Comment by steveklabnik** [comment]
I have discovered that this was already fixed! https://github.com/rust-lang/rust/pull/29410#issuecomment-151655871
