### ISSUE TITLE
Unable to access data in enum in rust-gdb

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#29423]
E.g. given:

``` rust
enum Foo { A(Box<u32>), B }
fn main() {
    let x = Box::new(1);
    let foo = Foo::A(Box::new(0));
}
```

Breaking on line 5 allows one to inspect values, however there doesn't seem to be a way to inspect what's inside the `A` stored in `foo`, e.g.

```
(gdb) p x
$1 = (i32 *) 0x7ffff6424008
(gdb) p foo
$2 = A = {0x7ffff6424010}
(gdb) p *x
$3 = 1
(gdb) p *foo
Attempt to take contents of a non-pointer value.
(gdb) 
```

**Comment by huonw** [comment]
Ah, so it appears that it is *possible*:

```
(gdb) p *foo.RUST$ENCODED$ENUM$0$B.__0
$5 = 0
```

**Comment by michaelwoerister** [comment]
It is always possible and it never is nice `:)` At least as long as we don't make GDB natively understand Rust. Expression evaluation is not extensible via Python plugins in GDB.

In theory, one could write a special `rust-print-enum-field` command that knows about all the special ways enums can be encoded (and it wouldn't have to have a such unwieldy name).

**Comment by arielb1** [comment]
@michaelwoerister 

We should at least have a decent way of casting these pointer-wrappers to Rust pointers (or maybe there is one?)

**Comment by tromey** [comment]
FWIW this works in my gdb branch now:

```
(gdb) p foo
$4 = debug::Foo::A(0x7ffff682a010)
(gdb) p *foo.0
$5 = 0
```

**Comment by tromey** [comment]
This has been in upstream gdb for a while now, and IMO this bug can be closed.
