### ISSUE TITLE
Revisit type link coloring for rustdoc

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#29421]
Rustdoc link coloring was updated in https://github.com/rust-lang/rust/pull/29264 and there was some discussion about whether links should be underlined on hover and whether all types should be colored the same. See https://github.com/rust-lang/rust/pull/29240 for the discussion. Extra colors were added to some of the links and merged (being merged presently) to get further experience in practice for the time being.

The link coloring and underlining should be revisited in the future to ascertain if any further change is necessary. Maybe this should be a part of https://github.com/rust-lang/rust/issues/29329

**Comment by steveklabnik** [comment]
It's been over a year, and these colors didn't cause an outrage, and were changed more times. Gonna consider this one done. Thanks @mdinger !
