### ISSUE TITLE
Remove `ConstrainVarSubReg` from inference and replace with a verify

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#29436]
Region inference needs some big-scale love, but even without that it has some deprecated bits. For example, the role of `ConstrainVarSubReg` has really been relegated to a verification step. We ought to remove it and just use `VerifyRegSubReg`. I started doing this, but it gets a bit complicated in dealing with the error reporting code (which itself needs to be reworked). So I decided to put it off for now and label it a FIXME.

**Comment by nikomatsakis** [comment]
I'd be happy to mentor this work, though it's kind of in the guts of things.

**Comment by brson** [comment]
Triage: `ConstrainVarSubReg` still exists. Help still wanted.

**Comment by jdhorwitz** [comment]
@nikomatsakis If you are still wiling to mentor I would love to help with this.  Thanks!

**Comment by nikomatsakis** [comment]
Hmm @jdhorwitz at this point I'm not sure if this refactoring is worth it. We expect to replace a lot of this code anyway. I think I'm inclined to close this issue, but I have [a list of mentoring tasks](https://gist.github.com/nikomatsakis/089b8857a7e605259f025cbaf9f677fb) that I try to keep up to date. I have been planning (for some time, I confess) to go through and for each one write up directions for each one, but if anything catches your eye, let me know.
