### ISSUE TITLE
Strange behavior when clicking to "Examples" and "Panics" headers in the docs

### ISSUE THREAD

**Issue by defuz** [rust-lang/rust#29449]
1. Go to https://doc.rust-lang.org/std/vec/struct.Vec.html
2. Scroll page to method definitions
3. Click to any "Examples" or "Panics" header.
4. Page jumps to the first same block on the page.

The problem is that all of these links have the same anchors (#examples, #panics). It is discouraging, especially when you're trying to give someone a link to an example of the documentation.

If it is not an easy fix, it might be worth at least remove `<a>` in these headers, and especially remove section character (§) on hover (it is clearly suggests that the link can be copied, but url is invalid).

And I'm sorry if this is a duplicate, I haven't found any similar issue.

**Comment by apasel422** [comment]
This is similar to #25001.

**Comment by NamPNQ** [comment]
This is fixed in https://github.com/alexcrichton/rust/commit/e60c8b2dcd69bb1f5815f089361302d4c755ff29
