### ISSUE TITLE
Add Capacity/length methods for OsString

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#29453]
Tracking issue for https://github.com/rust-lang/rfcs/pull/1307

**Comment by frewsxcv** [comment]
I'm currently working on this.

**Comment by frewsxcv** [comment]
Implemented in #31608

**Comment by alexcrichton** [comment]
:bell: This issue is now entering its cycle-long **final comment period** for stabilization in 1.9 :bell:

**Comment by alexcrichton** [comment]
The libs team discussed this during triage yesterday and the decision was to **stabilize**
