### ISSUE TITLE
Pretty print isn't pretty for floats

### ISSUE THREAD

**Issue by DenisKolodin** [rust-lang/rust#29472]
The following code:
```rust
fn main() {
    println!("{}", 1.2999999999999999);
    println!("{:?}", 1.2999999999999999);
    println!("{:.3}", 1.2999999999999999);
    println!("{:.*}", 5, 1.2999999999999999);

    // aren't pretty too
    println!("{:#}", 1.2999999999999999);
    println!("{:#?}", 1.2999999999999999);
}
```
prints:
```rust
1.2999999999999998
1.2999999999999998
1.300
1.30000
1.2999999999999998
1.2999999999999998
```
C behaviour:
```c
#include <stdio.h>
void main() {
  double f = 1.2999999999999999999;
  printf("%.14g", f);
}
```
prints:
```c
1.3
```
With Rust everything works like **f**, but not like **g**.

Is that really no way to get behaviour like **g** option of `printf`?
It's highly important feature for serialization libs.

*rustc 1.6.0-nightly (8ca0acc25 2015-10-28)*

**Comment by rkruppe** [comment]
[1.2999999999999999 != 1.3](https://play.rust-lang.org/?gist=3b40c092a2d09585b4f5&version=stable). Pretty printing should not be inaccurate by default. However, we've long wanted a mode that prints the shortest exact literal, see #24612 for some discussion. The difference to the default behavior would be that it would use exponential notation when that gives a shorter result. This mode should probably react gracefully --- i.e., omit trailing zeros --- when given a precision with `.N`. Then you can get short, slightly inaccurate outputs without pointless zeros.

Aside:

>  It's highly important feature for serialization libs.

Wouldn't serialization libraries want accuracy more than pleasing human readers?

**Comment by DenisKolodin** [comment]
Thank you for conception.

> Wouldn't serialization libraries want accuracy more than pleasing human readers?

Not by humans. But problem becoming little deeper... I have some Lua code, which contains parameters that numeric constants. I used to pure Lua to JSON serializer which calls Lua's `tostring` that calls `sprintf` inside. It produces `0.1` to `0.1`. But when I take parameter directly from Lua state as numeric (= C `double`) and serialize it I get `0.10000000000000001` value in JSON. I don't do any calculations inside Lua or Rust with that constant but values differs (Maybe there is dirty value transformation during interpreting Lua code, because constant has inaccurate value inside Lua VM). `sprintf` + `g` solves it.

 #24612 doesn't provide a twin for `g` option. Is there another activity in this direction?

**Comment by rkruppe** [comment]
`0.10000000000000001` equals `0.1`, so accuracy is not a reason to print the former. I can only assume your JSON serializer is being stupid, possibly aided by Lua indeed mangling the value internally. In any case, Rust's float formatting will never print `0.10000000000000001`, it will only use as many decimal digits as necessary, with the aforementioned caveat that it isn't allowed to use exponential notation.

**Comment by DenisKolodin** [comment]
I've found better example:
```rust
fn main() {
    let mut x = 0.1;
    for z in (1..100) {
        x = x + 0.01;
        println!("{}", x);
    }
}
```
it prints:
```rust
0.11
0.12
0.13
0.14
0.15000000000000002
0.16000000000000003
0.17000000000000004
0.18000000000000005
0.19000000000000006
0.20000000000000007
0.21000000000000008
0.22000000000000008
```

That's really terrible print )
It seems other languages use `g` as default print strategy. What do you think about it?

**Comment by rkruppe** [comment]
This is an example of floating point arithmetic being inaccurate. The number *really is* closer to `0.22000000000000008` than to `0.22` and trying to hide that doesn't do a service to anyone:

- it misleads people who try to find out how two numbers could possibly be not equal
- it is a hazard for serialization, because it rounds during an operation that one might not expect to round
- it doesn't confront float newbies with the reality of float arithmetic (which they *will* run into)

Besides, I do not buy that other languages do round by default. Here's [Java](http://ideone.com/DsqsG8), [JavaScript](http://ideone.com/lIVlJv), [Python](http://ideone.com/0vFijm), [Ruby](http://ideone.com/ljhEOj) giving identical or very similar output. Either `%g` does not do what you think it does, or these languages do not use `%g`.

**Comment by DenisKolodin** [comment]
I think you are right, `0.22000000000000008` is value we have in memory, and it's bad idea to change its representation. But using another formatting library is uncomfortable to print nice-looking values.

**Comment by rkruppe** [comment]
I absolutely agree you that there should be a formatting operator that is prettier and can also round to N decimal digits while remaining pretty. I just don't want it to print by default.

**Comment by pnkfelix** [comment]
cc me

**Comment by roquendm** [comment]
If you want to error free load/store floating point via text files and target multiple languages...use hexadecimal.  Using decimal is a recipe for pain.

**Comment by rkruppe** [comment]
@roquendm

It's true that decimal representation of binary floats has many downsides, but unfortunately it is also very convenient for humans. Decimal output must exist, might as well make it as pretty as possible while remaining accurate. And the really hard part of the implementation is already solved, loading and storing floating point number is already correct in Rust (you may have to round when you first read decimal input, but every subsequent load-store cycle preserves the bits exactly).

**Comment by pnkfelix** [comment]
@rkruppe I had assumed that the suggestion to use hexadecimal was a response to the scenario given above where one is trying to serialize data between Lua and Rust.  (But then again, it was unclear whom @roquendm 's comment was actually directed at... the "and target multiple languages" part was what made me think the text was targetted at @DenisKolodin )

**Comment by pnkfelix** [comment]
> #24612 doesn't provide a twin for `g` option. Is there another activity in this direction?

The discussion on #24612 did (in a [comment](https://github.com/rust-lang/rust/pull/24612#issuecomment-94634677)) mention how we might want to make `Display` (`{}`) and `Debug` (`{:?}`) outputs differ in their semantics.  `Display` would be a rough analogue to `g` and `Debug` would continue to mean `f`.

But its not clear how far we would actually want to go with this.  It would probably better to allocate a separate format modifier for this purpose, e.g. `{:g}`. (What did `g` stand for, anyway? I've always assumed it was chosen just because its the next letter after `f`, but that won't suffice for selecting a name for [a `std::fmt` trait](https://doc.rust-lang.org/std/fmt/#formatting-traits)

**Comment by rkruppe** [comment]
Since `#` is the "pretty print" operator for some kinds of output (e.g. `{:#?}`) and in all other case at least selects an *alternative* format (`{:#x}` for example), I think `{:#}` and `{:#?}` would be an appropriate spelling. I do not know if this is what @DenisKolodin wants, but in any case reading his posts gave me this thought.

**Comment by roquendm** [comment]
Indeed my comment was "if one wants to (as simply as possible) be bit-exact across all languages which might read/write the data in a text based format" then use hex floats,

**Comment by huonw** [comment]
Nominating to discuss:

1. making `Display` and `Debug` differ
2. using `#` as the "pretty"/`%g` version
3. adding `{:g}` for prettier output (the main benefit of this IMO, is automatically choosing between exponential and non-exponential notation, in addition to the already-discussed fact it doesn't try to round-tripping)

I'm not a huge fan of 1, but 2 doesn't seem crazy... although 3 and/or people just using e.g. `{:.3}` seems less subtle.

**Comment by DenisKolodin** [comment]
I see in the doc that: `#` - is alternative form of printing the *same value*. Maybe we don't have to add round surprise to alternate (`#`) specifier. But `g` also is not a format trait because value changes.

What about to use `-` sign? It isn't used now, but semantic hints us to substraction or shrinking.

```rust
println!("{:-}", 1.2999999999999999);
// 1.3
println!("{:-?}", 1.2999999999999999);
// 1.3
```

**Comment by rkruppe** [comment]
`Display` and `Debug` already differ for [signed zeros][signz]. However, that's the only difference and as I already expressed my opposition for either `{}` or `{:?}` to round.

> (the main benefit of this IMO, is automatically choosing between exponential and non-exponential notation, in addition to the already-discussed fact it doesn't try to round-tripping)

I'm not sure what you're saying here, can't the `#` route also take the liberty to switch between exponential and decimal notation?

@DenisKolodin `{:-}` is already a valid format specifier, though it's currently "not used" (which seems to mean "ignored"). However, as `+` is currently used for something related to the sign of the output, using `-` for something completely unrelated is pretty confusing IMHO.

---

Another thing that bugs me about a direct `%g`-analogue is the question of how many digits it should round to by default. C specifies 6 according to cppreference.com, but that seems completely arbitrary and it seems unlikely that this is the ideal value for most use cases. I would rather have the option (whether it be `:#`, `:g`, or something else) by itself only enable the dynamic switch to exponential notation. If *additionally* a precision is specified via `.N`, then take that into account when choosing the threshold for when to use the exponent, and also strip trailing zeros (i.e. what C's `%.Ng` does). But the default would still be accurate.

NB: I would also prefer ordinary `{:.N}` to strip trailing zeros, though I can see the guarantee of "exactly N decimal digits" be useful in some contexts.

[signz]: https://play.rust-lang.org/?gist=f86eeace50f951932b47&version=stable

**Comment by aturon** [comment]
**Libs team consensus**: any of the changes being discussed here should go through the RFC process. The team would be wiling to consider an RFC for any of the options [@huonw mentioned](https://github.com/rust-lang/rust/issues/29472#issuecomment-169177651), but would be particularly keen for either option 2 or 3.
