### ISSUE TITLE
Switch rustdoc away from Markdown

### ISSUE THREAD

**Issue by flying-sheep** [rust-lang/rust#29474]
Technical documentation needs more features than Markdown has.

E.g. the ability to easily (and prettily) link to classes and functions from text is invaluable for usability.

While Markdown is well-known and has good syntax for inline links, those features lend themselves rather to forums and the like than for large documents with a high amount of structure and internal crossreferences.

looking at pages like [Path](https://doc.rust-lang.org/std/path/struct.Path.html), i’m sad about the lack of visually distinct and link-wielding references in the text.

I think [Sphinx](http://sphinx-doc.org/tutorial.html) is as close to perfection as it can get. Its extensible roles and directives, as well as advanced features based on them like intersphinx links are perfect for what a programming language documentation needs.

instead of having a generic `str` in that text, we could e.g. have a [<samp>str</samp>](https://doc.rust-lang.org/std/primitive.str.html) in there with only a few characters added in the documentation markup.

So I propose to rebase rustdoc onto sphinx, or (although that’s probably too much work) a intersphinx-compatible rST implementation

**Comment by rkruppe** [comment]
I like Sphinx too but we've had this discussion in the past and it seems pretty clear that Markdown going anywhere. The most one could expect is for reStructuredText to be supported *alongside* Markdown, or more realistically in a separate tool. See https://internals.rust-lang.org/t/rustdoc-restructuredtext-vs-markdown/356 for some prior discussion.

**Comment by flying-sheep** [comment]
> that Markdown going anywhere

sorry, i can’t make sense of that. do you mean that markdown is taking over everywhere?

> The most one could expect is for reStructuredText to be supported *alongside* Markdown

hmm, that could work. we’d need a metadata index like the intersphinx mappings that allow us to resolve namespaced structs/traits/functions to urls, and then refer to them using rST roles, e.g.

and the ones not using rST would miss out on that.

i mean, this is horrible:

```md
Note the documentation for the primitives [`str`](primitive.str.html)
and [`[T]`](primitive.slice.html) (also called 'slice'). Many method calls
on [`String`](string/struct.String.html) and [`Vec`](vec/struct.Vec.html)
are actually calls to methods on `str` and `[T]` respectively, via [deref
coercions](../book/deref-coercions.html).
```

compared to

```rst
Note the documentation for the primitives :primitive:`str` and
:primitive:`[T]` (also called 'slice'). Many method calls on
:struct:`~std::string::String` and :struct:`~std::vec::Vec` are
actually calls to methods on :primitive:`str` and :primitive:`[T]`
respectively, via :book:`deref coercions`.
```

less semantic, less information there, less links for MD.

**Comment by rkruppe** [comment]
> sorry, i can’t make sense of that. do you mean that markdown is taking over everywhere?

I mean that Markdown is here to stay. Rust people will still be writing documentation in Markdown for the next few years, possibly forever.

**Comment by steveklabnik** [comment]
Hey @flying-sheep.

Thanks for bringing this up. It's quite true that Markdown has some weaknesses. We've been discussing this exact issue for a while over at https://internals.rust-lang.org/t/rustdoc-restructuredtext-vs-markdown/356.

Regardless, a change of this magnitude would certainly need an RFC today. We have hundreds and hundreds of pages of documentation in markdown, and moving to something else would really need to justify that effort. As such, the Rust issue tracker isn't the place to have this discussion, please check out that internals thread and possibly work on an RFC, taking into account all of the things over there. Thanks!

**Comment by flying-sheep** [comment]
I’m active in that thread. I just can’t see what kind of “momentum” (citation Gankro) a markup language can have.

@rkruppe seems to have a similar opinion, so please enlighten me: how is the popularity of one teachable-in-5-minutes markup language somehow significant over another teachable-in-5-minutes markup language?

**Comment by retep998** [comment]
@flying-sheep Because there's a huge amount of documentation already written in markdown. Teaching people a different markup language isn't difficult. Changing the huge amounts of documentation that already exist out there, in a language that is trying to be stable, would be a huge change.

**Comment by hexsel** [comment]
I think the expression "x is not going anywhere" means "x is not going to disappear" in the sense there is no interest on removing it, not a matter of popularity, but of practicality due to the effort of migrating and verifying all existing documentation.

**Comment by flying-sheep** [comment]
markdown is pretty limited in scope. is there any reason pandoc couldn’t just convert everything in a minute?

**Comment by Gankro** [comment]
@flying-sheep the big win IMO for markdown is that it has won the battle for the internet. Anyone who uses users/internals, reddit, github, stackoverflow, etc is familiar with markdown already. Markdown is unfortunately a fragmented standard and we use some extra widgets (code rendering being a nasty one), but the basic stuff just works.

omitted: a bitter rant about the general state of rustdoc, and how no one would bother to implement this suggestion even if it was accepted.

**Comment by flying-sheep** [comment]
i’m still questioning the value of people being familiar with it (you really can learn the whole thing in if not 5 then ~12 minutes, just like the equivalent subset of rST)

sorry to hear that about rustdoc…

**Comment by alexeymuranov** [comment]
> @flying-sheep the big win IMO for markdown is that it has won the battle for the internet. Anyone who uses users/internals, reddit, github, stackoverflow, etc is familiar with markdown already.

It might be that Markdown has won the battle as a format for blog and forum posts, issue reports and comments. However, documentation and HTML publishing are rather different IMO.
