### ISSUE TITLE
String/character escape rules do not match the reference

### ISSUE THREAD

**Issue by keleshev** [rust-lang/rust#29470]
The [reference](https://doc.rust-lang.org/stable/reference.html#characters-and-strings) does not allow `\'` escape inside strings, and neither `\"` inside character literals. This makes sense, as the backslash is redundant in these cases. However, the compiler accepts both: http://is.gd/CDBzp1

**Comment by petrochenkov** [comment]
The reference is incomplete, the full list is
```
\xFF (2 hex digits)
\u{FFFF} (1 to 6 hex digits)
\n
\r
\t
\0
\"
\'
\\
```

**Comment by keleshev** [comment]
@petrochenkov the reference includes all of your examples, except:
1. no `\0`
2. `\'` is restricted to character literals
3. `\"` is restricted to string literals

![screen shot 2015-11-06 at 14 23 40](https://cloud.githubusercontent.com/assets/619158/10998001/033d07c4-8492-11e5-9dd9-e3822dada3fa.png)

**Comment by keleshev** [comment]
And I think this restriction is made on purpose. It does not make sense to have `\'` inside string literal, because `'` (single quite) works fine as well.

**Comment by steveklabnik** [comment]
cc @rust-lang/lang is the compiler too accepting here, or is this a docs bug?

**Comment by nrc** [comment]
/me shrugs
seems either position is reasonable. I don't think it's worth a breaking change to 'fix' the compiler unless there is an example of this being dangerous. I guess it might be bad if the user expects `\'` to be `\'` not `'` and so doesn't escape the `\`

**Comment by nikomatsakis** [comment]
I agree with @nrc. I think it'd actually be more confusing to have the same sequence (e.g., `\"`) mean different things in character vs string literals. Or at least I'd find it confusing.

**Comment by steveklabnik** [comment]
Okay! Moving to docs bug then.
