### ISSUE TITLE
Rustdoc mis-parses links with spaces

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#29483]
If you're using a reference-style link with a parenthetical statement after it:

```
//! blah blah blah [something] (also known as bar)
//!
//! [something]: whatever.html
```

This will ignore the reference and link to `also known as bar`.

CommonMark says: 
http://spec.commonmark.org/0.21/#example-460

> [Whitespace] is not allowed between the link text and the following parenthesis:

**Comment by nagisa** [comment]
Hoedown does not target CommonMark.

**Comment by steveklabnik** [comment]
Yeah, this and https://github.com/rust-lang/rust/issues/29481 might both entirely be upstream, but I wanted to 1) make a note to investigate later and 2) have some sort of documentation that things might diverge from expected, for future searchers. :)

I would like to switch to something CommonMark compliant, personally.

**Comment by durka** [comment]
@nagisa [this](https://github.com/hoedown/hoedown/wiki/Spec-differences) claims Hoedown actually does target CommonMark.

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by durka** [comment]
@steveklabnik have this an #29481 been filed as Hoedown bugs? Worst they could do is say "not our problem". Though, hoedown looks unmaintained.

**Comment by steveklabnik** [comment]
I don't believe they have, mostly because I would prefer to port rustdoc to pulldown-cmark to eliminate yet another c dependency.

**Comment by frewsxcv** [comment]
Opened an issue for moving to pulldown-cmark: https://github.com/rust-lang/rust/issues/38400

**Comment by Mark-Simulacrum** [comment]
Work with `--enable-commonmark` so I'm going to go ahead and close.
