### ISSUE TITLE
Rustdoc gets confused with complex link text involving []s

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#29481]
This might be markdown, it might be rustdoc, it might be both. I haven't determined yet. But links like this don't work:

```
//! * [`[T; n]`] - An inline *array* with a fixed size at compile time.
//! * [`[T]`] - A dynamically sized *slice* into any other kind of contiguous
//! * [`Box<[T]>`] - *owned slice*
//!
//! [`Box<[T]>`]: boxed/index.html
//! [`[T; n]`]: primitive.array.html
//! [`[T]`]: primitive.slice.html
```

It would seem `[` inside this style of link confuses the parser.

**Comment by steveklabnik** [comment]
CommonMark says: http://spec.commonmark.org/0.21/#links

> Brackets are allowed in the link text only if (a) they are backslash-escaped or (b) they appear as a matched pair of brackets, with an open bracket [, a sequence of zero or more inlines, and a close bracket ].

so at least in theory, this should Just Work.

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by Mark-Simulacrum** [comment]
As best as I can tell, these work with `--enable-commonmark` so closing.
