### ISSUE TITLE
book: 'Angle-bracket Form' does not explain why expanded form is needed

### ISSUE THREAD

**Issue by ivan** [rust-lang/rust#29493]
https://doc.rust-lang.org/book/ufcs.html#angle-bracket-form gives an example that uses `<Bar as Clone>::clone(self);`, where using `Clone::clone(self);` works just as well (tested: rustc 1.6.0-nightly (2e07996a9 2015-10-29)).  And therefore I have no idea why and where I'd need the longer form.

I tested

```rust
trait Foo {
    fn clone(&self);
}

#[derive(Clone)]
struct Bar;

impl Foo for Bar {
    fn clone(&self) {
        println!("Making a clone of Bar");

        //<Bar as Clone>::clone(self);
        Clone::clone(self);
    }
}

fn main() {
   let b = Bar;
   Foo::clone(&b);
}
```

**Comment by sfackler** [comment]
The expanded form is required when the method you want to call doesn't mention `Self` in any way. For example:

```rust
trait Foo {
    fn foo() -> i32;
}

struct Bar;

impl Foo for Bar {
    fn foo() -> i32 {
        10
    }
}

fn main() {
    println!("{}", <Bar as Foo>::foo());
}
```

Seems like the example in the book should be updated to something like that.

**Comment by Gankro** [comment]
I've never seen a place where it's necessary, but the following are all technically equivalent:

```rust
// foo: Foo
foo.

**Comment by Gankro** [comment]
GOD DANG GITHUB IT'S 3AM STOP

**Comment by steveklabnik** [comment]
@sfackler `Bar::foo()` works just fine there.


I agree we need a better example.... but I'm not sure what that is.

**Comment by sfackler** [comment]
Ah yeah. If you add a `fn foo()` directly to `Bar` as well, *then* you should need to use the full UFCS form to specify you want to call `Foo`'s `foo` rather than `Bar`'s:

```rust
trait Foo {
    fn foo() -> i32;
}

struct Bar;

impl Bar {
    fn foo() -> i32 {
        20
    }
}

impl Foo for Bar {
    fn foo() -> i32 {
        10
    }
}

fn main() {
    println!("{}", <Bar as Foo>::foo());
}
```
