### ISSUE TITLE
Get rid of `ok().expect()` in the docs

### ISSUE THREAD

**Issue by fhartwig** [rust-lang/rust#29506]
[This discussion](https://users.rust-lang.org/t/rust-n00b-question-about-result-etc/3470) showed that some people are confused by the use of the `.ok().expect()` on `Result` values in the documentation. Since `Result::expect` is now stable, this pattern has become mostly obsolete (with the exception of `Result` types whose error types do not implement `Debug`, which shouldn't be very common).

It probably shouldn't be used in the docs any more. Probably the most important place where this should be fixed is https://github.com/rust-lang/rust/blob/6d43fef3aaf64b2e7df14ca676a3a39b723ed7f3/src/doc/trpl/guessing-game.md , which will need to be re-written a bit since the text explicitly references that pattern.

**Comment by frewsxcv** [comment]
Now that #29507 has merged, can this be closed?

**Comment by steveklabnik** [comment]
That PR only says it address part of the issue.

**Comment by fhartwig** [comment]
#29507 fixed all the instances of this pattern that I could find in the docs, except for the guessing game. The guessing game has a paragraph that talks about the `ok().expect()` thing, and I wasn't sure if we just want to delete that or rewrite it (and how to rewrite it).
