### ISSUE TITLE
Slice coercion is too conservative with generic receiver.

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#29504]
``` rust
fn main(){
    let x = "hello world";
    let y = ['h', 'e'];
    println!("{:?}", x.find(&y));
}
```

will not compile with “error: the trait `core::ops::Fn<(char,)>` is not implemented for the type `[char; 2]`”, but there’s `impl<'a, 'b> Pattern<'a> for &'b [char]`, which could’ve been used if coercion happened.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/39511.
