### ISSUE TITLE
Windows: Static libraries should end with .lib not .a when using the MSVC ABI install

### ISSUE THREAD

**Issue by pjmlp** [rust-lang/rust#29508]
The standard extension for Windows static libraries is .lib.

By keeping the .a extension while using the MSVC ABI, we are forced to rename the files when integrating Rust libraries into compiler chains that expect .lib as an extension.

Reopening the bug here as suggested by alexcrichton (https://github.com/rust-lang/cargo/issues/2100)

**Comment by nagisa** [comment]
Duplicateish of https://github.com/rust-lang/rust/issues/28025. Maybe reopen that instead, since it has more relevant discussion?

**Comment by retep998** [comment]
`rustc foo.rs --crate-type=staticlib` produces `libfoo.a`.
This needs to be changed to produce `foo.lib` for -msvc.

**Comment by retep998** [comment]
Actually, since that would conflict with the import library produced by `--crate-type=dylib` I propose using `libfoo.lib` instead as it matches the conventions that Microsoft uses to distinguish static/dynamic libraries (such as `ucrt.lib` vs `libucrt.lib`)
