### ISSUE TITLE
Blanket trait impls are not listed as implementations in rustdoc

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#29503]
`ToString` has the implementation `impl<T: fmt::Display + ?Sized> ToString for T`  which is [not listed in its documentation page.](http://doc.rust-lang.org/nightly/collections/string/trait.ToString.html)

It is however [listed in libstd](http://doc.rust-lang.org/nightly/std/string/trait.ToString.html), so rustdoc does the correct thing after doc inlining.

This bug with blanket impls shows up in user's crates, [see discussion on users.rust-lang](https://users.rust-lang.org/t/rustdoc-generic-implementation-missing-from-implementors-list/3475); for example the `Itertools` trait in itertools does not have its blanket impl visible in the docs.

**Comment by pmarcelll** [comment]
It regressed on nightly, it also disappeard from the libstd page.

**Comment by jethrogb** [comment]
The regression is not due to specialization, see e.g. https://doc.rust-lang.org/stable/std/any/trait.Any.html vs https://doc.rust-lang.org/nightly/std/any/trait.Any.html which does not use specialization.

**Comment by flying-sheep** [comment]
is this the same for me?

hmm, is this bug affecting me? [my docs](http://flying-sheep.github.io/path-glob/path_glob/trait.Glob.html)

**Comment by bluss** [comment]
@flying-sheep Yes, it's the same bug.

**Comment by flying-sheep** [comment]
thanks. a bit confusing, since that impl is the whole point of my crate :smile:

**Comment by jethrogb** [comment]
The regression was already fixed in #33133
