### ISSUE TITLE
Improve E0432

### ISSUE THREAD

**Issue by Dashed** [rust-lang/rust#29517]
For the following error code: https://doc.rust-lang.org/error-index.html#E0432

 I think it's useful to suggest that the following statement may be needed for `main.rs`: 

```rust
extern crate <name>;
```

**Comment by durka** [comment]
It actually does say that in the error message:

```rust
expr.rs:5:6: 5:15 error: unresolved import `something::Foo`. Maybe a missing `extern crate something`? [E0432]
expr.rs:5 {use something::Foo;}
```

But not on the error explanations page.
