### ISSUE TITLE
Can't use librustc in staticlib

### ISSUE THREAD

**Issue by mintern** [rust-lang/rust#29512]
`lib.rs`:
```rust
#![feature(rustc_private)]
extern crate rustc;
```

```
$ rustc --crate-type dylib lib.rs && echo 'Success!'
Success!
$ rustc --crate-type staticlib lib.rs && echo 'Success!'
error: dependency `rustc_back` not found in rlib format
error: dependency `rustc_data_structures` not found in rlib format
error: dependency `rustc` not found in rlib format
error: dependency `syntax` not found in rlib format
error: dependency `rustc_front` not found in rlib format
error: dependency `rustc_llvm` not found in rlib format
error: dependency `fmt_macros` not found in rlib format
error: aborting due to 7 previous errors
```

**Comment by retep998** [comment]
Only the dylib versions of rustc crates are included with the distribution for the sake of writing plugins.

**Comment by alexcrichton** [comment]
Yes this is currently intentional. To build a staticlib you have to have rlibs available for all upstream components, but we don't provide rlibs for the compiler because that would cause plugins to not work (which are an exported API of the compiler).

**Comment by mintern** [comment]
So it sounds like I'm out of luck for creating a library that leverages the compiler and is used by another language? Or is there a way that I can do this? I'm on nightlies, have the source checked out, etc.

If this is intentional, I couldn't find any documentation to that effect, and no suggestions as to how to work around it. The only option I'm currently aware of is to build a separate service and use IPC to communicate with a compiler library.

**Comment by retep998** [comment]
You can create your library as a dylib just fine. Is there any reason why you specifically need it as a staticlib?

**Comment by mintern** [comment]
As soon as I added `extern crate staticlib`, I was hitting a segmentation fault:

```
# A fatal error has been detected by the Java Runtime Environment:
#
SUREFIRE-859: #  SIGSEGV (0xb) at pc=0x00007f0549664f4d, pid=32209, tid=139660732696320
#
# JRE version: Java(TM) SE Runtime Environment (8.0_66-b17) (build 1.8.0_66-b17)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.66-b17 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libzip.so+0x11f4d]  ZIP_GetEntry2+0xed
```

My assumption was that Java is linked against a different version of `libzip` than the Rust library expects, and it's causing a segmentation fault.

Also, my original plan was to distribute this library as part of a NetBeans plugin, and it would be ideal if the user didn't have any dependencies.

Perhaps I'm making poor assumptions?
