### ISSUE TITLE
Unclear error message when destructuring in const fn

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#29525]
``` rust
const fn i((a, b): (u32, u32)) -> u32 { a + b }
```

[Errors with E0022](http://is.gd/qkrOKq) "arguments of constant functions can only be immutable by-value bindings". The detailed explanation for E0022 is:

> Constant functions are not allowed to mutate anything. Thus, binding to an argument with a mutable pattern is not allowed. For example,
> 
> ``` rust
> const fn foo(mut x: u8) {
>     // do stuff
> }
> ```
> 
> is bad because the function body may not mutate x.
> 
> Remove any mutable bindings from the argument list to fix this error. In case you need to mutate the argument, try lazily initializing a global variable instead of using a const fn, or refactoring the code to a functional style to avoid mutation if possible.

This does not seem to be the correct error message.

**Comment by estebank** [comment]
[Current output](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=aa4a48b30e02d2746e6a2f588e90b9e1):

```
error: local variables in const fn are unstable
 --> src/lib.rs:1:13
  |
1 | const fn i((a, b): (u32, u32)) -> u32 { a + b }
  |             ^
```

**Comment by estebank** [comment]
This is now accepted in beta and nightly :)
