### ISSUE TITLE
No support for converting wide strings to *u16 and [u16] on Windows

### ISSUE THREAD

**Issue by pjmlp** [rust-lang/rust#29521]
After spending hours tracking down outdated tutorials on the Internet and the issue about Windows documentation not being visible on the Rust web site, I was able to find out about std::os::windows::ffi::EncodeWide and OsStringExt.

However Windows std support still seems to miss conversion into [u16] and *u16, which are also needed.

Unless I have missed them somewhere.

**Comment by alexcrichton** [comment]
Thanks for the report! Due to the way that OS strings are stored on Windows the only way to do this is via `encode_wide`, there's no actual way to return a `[u16]` or `*const u16`, so I'm going to close this.

We do have other bugs tracking the windows-specific documentation, issue, however, so this hopefully won't be so hard to find in the future!

**Comment by pjmlp** [comment]
Given that this is now closed, any plans to make Rust strings friendlier to Windows system programmers?

I saw posts of everyone being forced to write their own conversions. Not a good way to sell Rust.

**Comment by alexcrichton** [comment]
I'd certainly be interested in methods to make various operations easier! A good candidate would perhaps be a method that just returns a `Vec<u16>` or perhaps even a 0-terminated vector, but it's not clear how much better this is over `foo.encode_wide().collect::<Vec<_>>()`.

**Comment by pjmlp** [comment]
Not sure if this is the place to further discuss the issue, given that it is closed.

Anyway, this started as I wanted to investigate if with Rust 1.4 (MSVC toolchain) I could finally make it part of a WinRT application. Now as a plain dll, eventually in the future as  WinRT component assuming Rust ever does COM.

https://github.com/pjmlp/WinRT-Rust

An example that would eventually be like _"Look this is how one does WinRT with Rust"_.

However due to the lack of information on how to handle wide character strings, I ended up returning a plain *u8 with the conversion from Rust strings to UTF-16 taking place on C++/CX side.

Afterwards I kept searching the web only to find out, as mentioned, that everyone has their own little solution.

Given that all Windows system programming languages can deal with wide strings directly, it appeared to me that it is bad PR for Rust in Windows to tell developers used to Delphi WideString, C wchar, C++ wstring, and other builtin conversions to UTF-16/DBCS, including wide string literals, that with Rust an external package is required and literals also need conversions. 

For example, I wasn't aware of `foo.encode_wide().collect::<Vec<_>>()`, maybe it would enough to provide util functions that wrap the `encode_wide().collect::<Vec<_>>()` part or provide a crate similar with wide char and string manipulation functions.

Is there already one, that I could eventually contribute to?

**Comment by alexcrichton** [comment]
I think this is probably a case where we could probably need to bolster up our docs! Working with wide strings in Rust should work quite well, all instances of `str` can just be re-encoded as UTF-16 at any time, and `OsString` has the `encode_wide` method to go to a wide string. Leveraging these two may not be surfaced much in the docs, however, but you shouldn't need to go to any external crate to get the FFI utilities you need in theory.

**Comment by pronebird** [comment]
@alexcrichton  Could you please clarify what `encode_wide` does and why documentation states that it can produce ill-formed UTF-16. If `encode_wide` produces UTF-16 it seems that this may result in invalid encoding on Windows as I suspect that Windows expects UCS-2 instead.
