### ISSUE TITLE
Clarify whether `#[repr(C)]` can be used on tuple structs or not.

### ISSUE THREAD

**Issue by nwin** [rust-lang/rust#29526]
Until now I had the impression that it would be undefined how this construct would behave. [The Rustonomicon](https://doc.rust-lang.org/nightly/nomicon/other-reprs.html#reprc) implies that this is still the case, as tuple-structs are just like “named tuples”. On the other hand, [the reference](https://doc.rust-lang.org/stable/reference.html#structure-types) implies that it should be safe to use `#[repr(C)]` since tuple structs behave like normal structs with anonymous fields.

I would appreciate if this would be clarified in the docs. If it is still undefined behavior `#[repr(C)]` on a tuple struct should cause an compiler error.

**Comment by eefriedman** [comment]
It's well-defined; perhaps the docs aren't as clear as they could be.

**Comment by Aatch** [comment]
Just to be clear, tuples and structs are handled pretty much identically. There are two properties, named type and named fields that distinguish the 3 options:

  | Type Named? | Field Named?
---|---|---
`struct Foo { a: i32 }` | Yes | Yes
`struct Foo(i32)` | Yes | No
N/A (Would be "record" or similar) | No | Yes
`(i32, i32)` | No | No

In theory, there is no reason you couldn't apply `#[repr(C)]` to tuples, except that there's no source-code definition for them.

**Comment by nikomatsakis** [comment]
I see no reason to disallow it. I vote "not a bug".

**Comment by nrc** [comment]
Agree. Change to a docs bug?

**Comment by steveklabnik** [comment]
Sounds good, I'll document it.
