### ISSUE TITLE
Incorrect resolution with module paths and closure analysis

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#29522]
The following code incorrectly fails to compile:

```rust
use std::thread::spawn;

mod foo {
    struct Scope<'a>(&'a u8);
    pub fn scope<'a, F, R>(f: F) -> R where F: FnOnce(&Scope<'a>) -> R {
        panic!()
    }
}

fn main() {
    foo::scope(|scope| {
        spawn(move || {
            foo::scope(|s| {});
        });
    });
}
```

with error:

```
src/lib.rs:13:9: 13:14 error: the type `[closure@src/lib.rs:13:15: 15:10 scope:&foo::Scope<'_>]` does not fulfill the required lifetime [E0477]
src/lib.rs:13         spawn(move || {
                      ^~~~~
note: type must outlive the static lifetime
```

However, if you change the name `scope` in the closure within `main`, it works fine:

```rust
fn main() {
    foo::scope(|s| {
        spawn(move || {
            foo::scope(|s| {});
        });
    });
}
```

**Comment by nikomatsakis** [comment]
This is certainly creepy, nominating. Also I marked it as `A-lifetimes` because I don't think this impacts name resolution per se. My first thought is it is related to some of the known indeterminancies in region inference.

**Comment by aturon** [comment]
(This happens in 1.4 stable, 1.5 beta, and the 2015-10-31 nightly)

**Comment by aturon** [comment]
@nikomatsakis Note that the particular error here may be misleading. The [original report](https://github.com/aturon/crossbeam/issues/18) was getting an error about `Sync` not being satisfied.

**Comment by nikomatsakis** [comment]
@aturon yes, I saw that, though it seems **likely** related

**Comment by arielb1** [comment]
Figured this out. Apparently resolve registers `scope` as an upvar. Will fix.
