### ISSUE TITLE
Cannot derive Clone when using 'braced_empty_structs'

### ISSUE THREAD

**Issue by Thinkofname** [rust-lang/rust#29548]
Code:
```rust
#![feature(braced_empty_structs)]

#[derive(Clone)]
struct Test {}

fn main() {
}
```
Playground: https://play.rust-lang.org/?gist=7d3786c5b71415babb04&version=nightly

Error:
```
<anon>:1:1: 1:1 error: unresolved enum variant, struct or const `Test` [E0419]
<anon>:1 #![feature(braced_empty_structs)]
         ^
<anon>:3:10: 3:15 note: in this expansion of #[derive_Clone] (defined in <anon>)
<anon>:1:1: 1:1 help: see the detailed explanation for E0419
<anon>:3:10: 3:15 error: `Test` is the name of a struct or struct variant, but this expression uses it like a function name [E0423]
<anon>:3 #[derive(Clone)]
                  ^~~~~
<anon>:3:10: 3:15 note: in this expansion of #[derive_Clone] (defined in <anon>)
<anon>:3:10: 3:15 help: see the detailed explanation for E0423
<anon>:3:10: 3:15 help: did you mean to write: `Test { /* fields */ }`?
error: aborting due to 2 previous errors
```

This should work just like `struct Test;` unless i'm missing something?

**Comment by steveklabnik** [comment]
Yup, seems like a bug.

**Comment by petrochenkov** [comment]
Derive can be simplified and always emit `{}` version for non-tuple structs, fixing this issue, but https://github.com/rust-lang/rust/pull/29383 should land first.

**Comment by tsion** [comment]
This also affects enums, e.g. http://is.gd/qwKetS.

**Comment by alexreg** [comment]
Any progress on this? This has been around a while.

**Comment by petrochenkov** [comment]
I was waiting for stabilization of `braced_empty_structs` to fix this cleanly.
But it can be done without stabilization too, I'll try to fix it this weekend.

**Comment by alexreg** [comment]
Thanks, that would be great.
