### ISSUE TITLE
unwrap! in docs looks like a macro

### ISSUE THREAD

**Issue by mstevens** [rust-lang/rust#29542]
this is totally nitpicky, but:

reading the docs at https://doc.rust-lang.org/stable/book/error-handling.html

it says:

"Why? Because Rust will make us call unwrap! This can give us a nice bird's eye view of how we need to approach error handling."

even in my web browser with "unwrap" colored, this looks really like unwrap! is a macro. Which is confusing for the learner!

**Comment by porglezomp** [comment]
Just looking at it quickly, I suggest
> Why? Because Rust will make us call the `unwrap` method!
