### ISSUE TITLE
Broken link/formatting in docs for std

### ISSUE THREAD

**Issue by thinkofdeath** [rust-lang/rust#29552]
https://doc.rust-lang.org/nightly/std/ 

The line
`documents the constant values [MIN] and MAX.` 

MAX links to https://doc.rust-lang.org/nightly/std/rarely%20useful . Looking at the [source](https://github.com/rust-lang/rust/blob/708e319f804b799291b2c89f50cf70c0532e1a7b/src/libstd/lib.rs#L79) it looks like rustdoc ignored the space between `]` and `(` and made it a link.

**Comment by steveklabnik** [comment]
Gah! This is https://github.com/rust-lang/rust/issues/29483. I recently changed this, and it missed my manual inspection.

**Comment by steveklabnik** [comment]
For anyone that wants to fix this, the idea is to change line 79 of `src/libstd/lib.rs` to use the inline link syntax, `[]()`. Which also means removing line 156, where the target is.

I'm making this a part of https://github.com/rust-lang/rust/issues/29429 so we don't ship a release without the fix, but if you're interested in helping out, please do it before I get to it!

**Comment by rilut** [comment]
Pardon me, I didn't understand. Would a backslash fix it?

**Comment by steveklabnik** [comment]
Take the [] and make it a []() style link instead, basically. The URL is down below, since it's a footnote-style link right now.

**Comment by abhijeetbhagat** [comment]
I can do this. Shall i?

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/29624 fixed this
