### ISSUE TITLE
Compiler command line customization in the Rust makefile

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#29554]
Distros often have a standard, custom, set of flags that should be passed to all compiler invocations when building the binaries distributed as packages for that platform (think things like hardening options). For example, Debian wants to pass `-Wl,-z,relro` during the link step.

To support this, every compiler invocation in the makefile needs to include the appropriate `CFLAGS`, `CXXFLAGS`, `LDFLAGS`, or `RUSTFLAGS` variable.  See the [Debian patch for guidance][debian-make].

re https://internals.rust-lang.org/t/perfecting-rust-packaging-the-plan/2767

**Comment by brson** [comment]
This is done. Thanks @bltavares .

**Comment by bltavares** [comment]
You are welcome (:
