### ISSUE TITLE
Ensure that SxS installation of crates from multiple compilers works reliably

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#29560]
For SxS installations of arbitrary Rust compilers, there will be multiple copies of the standard library residing in the same path. Without care, rustc will see them as duplicates.

Neither @alexcrichton or I am confident that the current crate resolver correctly rejects crates that weren't generated by the same compiler, though we suspect it works correctly in most scenarios.

Tightening this up further could have negative implications for e.g. a distributed Cargo cache, depending on how strict rustc is about rejecting crates it didn't produce.

I'm not sure how real this problem is but probably needs some thought.

https://internals.rust-lang.org/t/perfecting-rust-packaging-the-plan/2767

**Comment by steveklabnik** [comment]
Triage: dunno if @brson gave this any thought yet exactly 😄

**Comment by steveklabnik** [comment]
Triage: it seems packaging is working well, and brson doesn't work on Rust anymore. I'm going to close this.
