### ISSUE TITLE
Fix --libdir issues

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#29561]
The way rust and rust-installer handles `--libdir` is broken, and at least in Gentoo's case is unusable without patching.

See [Gentoo's rust-installer patch][gentoo-libdir-patch]. And an old [rust-installer PR][installer-libdir].

[gentoo-libdir-patch]: https://github.com/gentoo/gentoo-rust/blob/master/dev-lang/rust/files/rust-1.1.0-install.patch
[installer-libdir]: https://github.com/rust-lang/rust-installer/pull/25

re https://internals.rust-lang.org/t/perfecting-rust-packaging-the-plan/2767

**Comment by wthrowe** [comment]
It appears that `--libdir` fails on recent nightlys even with Gentoo's patch: gentoo/gentoo-rust#29
