### ISSUE TITLE
Update Homebrew packages

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#29562]
The homebrew packages don't have a dedicated maintainer, and the current recipe has flaws: the obvious one is that there is no cargo source tarball for it to use.

While it builds Rust from source it appears to install Cargo from binaries.

It also removes the uninstall script. I'm not clear on why. Perhaps Homebrew has its own uninstall mechanism?

I think we don't actually need to take over maintenance of the Homebrew package, just update it for best practices once we get them sorted out.

re https://internals.rust-lang.org/t/perfecting-rust-packaging-the-plan/2767

**Comment by sfackler** [comment]
Homebrew does have its own uninstall mechanism.

**Comment by Luthaf** [comment]
What should be changed here? Just build rust and cargo from source ?

**Comment by Mark-Simulacrum** [comment]
I believe that Homebrew packages are somewhat-actively being maintained. At the very least, new releases are being added to brew.
