### ISSUE TITLE
Mir: remove Panic terminator and instead just call suitable lang item

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#29573]
Panic in MIR is unimplemented. It should call into the panic lang item.

**Comment by wesleywiser** [comment]
Hi, I'd like to give this a shot.

**Comment by nikomatsakis** [comment]
@wesleywiser great! If you want to chat about it, the easiest way is to privmsg me on IRC (`nmatsakis`) or send me an email (`nmatsakis@mozilla.com`). I will note though that it may be that we should reshape panics to just be calls, in which case this task is more about handling *calls* than about panics per se, which is maybe a bigger job (but a very important one).

**Comment by nikomatsakis** [comment]
I now think we should refactor panics to simply call into the appropriate lang item and not have an explicit `Panic` terminator.

**Comment by nagisa** [comment]
Replacing `Panic` terminator with explicit call to language item that’s followed by a `Diverge` (I assume `Diverge` has the same semantics as `intrinsics::unreachable`) terminator sounds good to me.

**Comment by nagisa** [comment]
On the other hand, it would make implementing certain codegen features such as `-C no-landing-pads` near-impossible? Then probably doesn’t sounds as good as it did before 😃

**Comment by nikomatsakis** [comment]
@nagisa I don't see why it makes that any harder. In such a mode we presumably would not emit a Panic either, and/or we'd change the lang item to abort (and strip away the landing pads path so that the call block has no successors).

**Comment by nikomatsakis** [comment]
@nagisa also, the semantics of diverge are *not* unreachable. The diverge
terminator continues unwinding. Perhaps it should have been called "resume".

**Comment by nikomatsakis** [comment]
Though, we could say that if landing pads are disabled, then the Diverge
terminator just traps, and then we can keep directing all panic pathways
directly into the Diverge block. Not sure, plenty of ok options I guess.
