### ISSUE TITLE
an error at the Rust book

### ISSUE THREAD

**Issue by samuelyao314** [rust-lang/rust#29570]
an example at https://doc.rust-lang.org/stable/book/concurrency.html
      println!("{}", handle.join().unwrap());

this is a compiler error.  The collect is:
      println!("{:?}", handle.join().unwrap());

**Comment by steveklabnik** [comment]
@samuelyao314 which version of Rust are you running? https://play.rust-lang.org/?code=use%20std%3A%3Athread%3B%0A%0Afn%20main%28%29%20{%0A%20%20%20%20let%20handle%20%3D%20thread%3A%3Aspawn%28||%20{%0A%20%20%20%20%20%20%20%20%22Hello%20from%20a%20thread!%22%0A%20%20%20%20}%29%3B%0A%0A%20%20%20%20println!%28%22{}%22%2C%20handle.join%28%29.unwrap%28%29%29%3B%0A}%0A does run just fine for me.

**Comment by samuelyao314** [comment]
It's strange.  It can work now. Maybe it is my mistake.

**Comment by steveklabnik** [comment]
Okay! If you figure out exactly what's wrong, just let me know.
