### ISSUE TITLE
Mir: Trans of casts unimplemented

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#29576]
We need to support the various kinds of casts. This mostly involves looking at the old trans code for casts and porting it over to MIR, I imagine. The relevant `unimplemented!` is in `trans/mir/rvalue.rs`. Note that there are two: one for when trans'ing into a particular location (which would be used e.g. for casts to fat pointers) and one for when trans'ing into an `Operand` (e.g. for integer casts).

**Comment by KiChjang** [comment]
Is this issue up for grabs? If so I'd like to see what I can do about it.

**Comment by nagisa** [comment]
@KiChjang I already have code somewhere for `Misc` cast-kind somewhere around, which I’ll rebase onto master in a moment. Everything else seems to already be implemented.

**Comment by nagisa** [comment]
This is fully implemented to my knowledge (baring bugs) and thus can be closed.
