### ISSUE TITLE
Allow I/O cancellation

### ISSUE THREAD

**Issue by taralx** [rust-lang/rust#29589]
There are some cases where one wants to cancel a blocking I/O operation (usually a read). In most cases you can do this by closing the underlying connection, but that feels kind of hacky. If rust is using select/poll/epoll/kqueue, it would be nice if there were a way to "de-queue" a request.

**Comment by sfackler** [comment]
Rust is not using select/poll/epoll/kqueue. A `read` call on a `TcpStream` corresponds directly to a `read` libc call.

**Comment by taralx** [comment]
Sadface. How about some pthread_kill/sigaction combo then?

**Comment by sfackler** [comment]
The philosophy of the IO portions of the standard library are designed to be thin wrappers around the underlying OS primitives - `read` maps to `read`, `write` maps to `write`, `shutdown` maps to `shutdown` etc. The system used to be significantly more magical, but that ends up making life harder for anyone that wants to work with the system to add more functionality. If we registered a signal handler and used pthread_kill (which is a source of horrifying scariness in itself), that means that downstream users are suddenly prohibited form registering signal handlers without breaking chunks of the IO system. The RFC that proposed the changes has more background as well: https://github.com/rust-lang/rfcs/blob/master/text/0517-io-os-reform.md

**Comment by taralx** [comment]
Cool. Okay, so this is out of scope for the standard library at this time. I can do the pthread_kill/sigaction stuff separately.

**Comment by retep998** [comment]
Don't forget that Windows has its own way of cancelling blocking IO.
