### ISSUE TITLE
when running "make",encounter error

### ISSUE THREAD

**Issue by luckypoem** [rust-lang/rust#29606]
hi.

```
 Entering directory `/root/rust/x86_64-unknown-linux-gnu/llvm/utils/TableGen'
llvm[3]: Compiling AsmMatcherEmitter.cpp for Release build
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
/bin/rm: cannot remove '/root/rust/x86_64-unknown-linux-gnu/llvm/utils/TableGen/Release/AsmMatcherEmitter.d.tmp': No such file or directory
make[3]: *** [/root/rust/x86_64-unknown-linux-gnu/llvm/utils/TableGen/Release/AsmMatcherEmitter.o] Error 1
make[3]: Leaving directory `/root/rust/x86_64-unknown-linux-gnu/llvm/utils/TableGen'
make[2]: *** [TableGen/.makeall] Error 2
make[2]: Leaving directory `/root/rust/x86_64-unknown-linux-gnu/llvm/utils'
make[1]: *** [all] Error 1
make[1]: Leaving directory `/root/rust/x86_64-unknown-linux-gnu/llvm'
make: *** [/root/rust/x86_64-unknown-linux-gnu/llvm/Release/bin/llvm-config] Error 2
root@VM:~/rust#
```

how to fix it?
thanks

**Comment by sanxiyn** [comment]
Your C++ compiler failed to compile LLVM. Update your C++ compiler.

You can check the version of your C++ compiler by running `g++ --version`. Do that, and check the version against [LLVM's list of known compilers which fail to compile LLVM](http://llvm.org/releases/3.4/docs/GettingStarted.html#broken-versions-of-gcc-and-other-tools).

**Comment by alexcrichton** [comment]
Yeah unfortunately it looks like just a standard error with `g++`, so closing (as it's unrelated to our build I believe)

**Comment by luckypoem** [comment]
hi.
@sanxiyn 
i checked http://llvm.org/releases/3.4/docs/GettingStarted.html#broken-versions-of-gcc-and-other-tools,
but actually the version of my gcc is 4.8.4 which is higher than the requirement of the article.so why i still 
encounter error??

root@VM:~# g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04) 
root@VM:~#

**Comment by sanxiyn** [comment]
You may want to check whether you have enough memory in your VM.

**Comment by luckypoem** [comment]
hi.
@sanxiyn 

root@VM:~# free -m
             total       used       free     shared    buffers     cached
Mem:           256        147        108          5          0         84
-/+ buffers/cache:         63        192
Swap:            0          0          0
root@VM:~#

my vm still  have memory-108mb. 108mb ram is not enuf ?how much ram do i need?

**Comment by sanxiyn** [comment]
~100 MB is definitely not enough. Usual recommendation is more than 2 GB.
