### ISSUE TITLE
Tracking issue for `quote` feature

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#29601]
Tracks stabilization for the `quote_*` family of macros.

**Comment by eefriedman** [comment]
There isn't really much incentive to stabilize this at the moment; this is basically only useful with plugins.

**Comment by aturon** [comment]
cc plugin tracking: https://github.com/rust-lang/rust/issues/29597

@eefriedman Thanks for your help filling out these skeletons! I was a bit uncertain about the right granularity -- we could consolidate some of these plugins-centric features into the plugins tracking issue, perhaps.

**Comment by eefriedman** [comment]
Mmm... I guess this makes sense to keep separate; we could in theory change the way this feature works, and stabilize it separately from plugins.  (For example, we could use some trickery involving duck typing and `use` statements to allow someone to specify what AST-building library to use.)

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by SimonSapin** [comment]
One change indirectly affecting this is that we now have a concrete plan for Macros 2.0 which will make this feature obsolete, so it is now on a path to (eventual) deprecation rather than stabilization.

**Comment by SimonSapin** [comment]
I believe https://github.com/rust-lang/rust/pull/51285 should have closed this. Please reopen or comment if this is not the case.
