### ISSUE TITLE
extern crate privacy is "public" without requiring "pub".

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#29654]
```rust
mod foo {
    extern crate std;
}

fn main() {
    println!("{}", foo::std::mem::size_of::<i32>());
}
```
[Try on playpen](http://is.gd/yUwRYM).

This is due to [`is_public` being `true` for all `ItemExternCrate` regardless of whether they are `pub`](https://github.com/rust-lang/rust/blob/1dac3adc34a85670d81f86345054ec58e658b68b/src/librustc_resolve/build_reduced_graph.rs#L395).

Even then, `pub extern crate` is not handled correctly in all cases, see #26775.

**Comment by nikomatsakis** [comment]
triage: P-high

**Comment by nrc** [comment]
I'm going to close this and discuss further on #26775 - the two issues are very connected and that issue has more discussion.

> This is due to is_public being true for all ItemExternCrate regardless of whether they are pub.

This is not the case - is_public there is referring to the module itself, not the importing directive, so being true all the time is correct. More on #26775.
