### ISSUE TITLE
"Secure Connection Failed" accessing https://doc.rust-lang.org/ in Firefox 42.0

### ISSUE THREAD

**Issue by domenic** [rust-lang/rust#29669]
Since this does not occur with a fresh profile, it is presumably my problem. But I thought it would be worth reporting just in case it indicates some deeper problem. Feel free to close though!

- Relevant error text: "Secure Connection Failed / The connection to the server was reset while the page was loading. / The page you are trying to view cannot be shown because the authenticity of the received data could not be verified."
- Windows 10 (RTM)
- Also occured in 41.0.2 before I upgraded
- Occurs in both normal browsing and private browsing
- Occurs even after disabling all addons
- Does _not_ occur with a fresh profile.
- The page _works_ on the same computer and network in Edge and Chrome, both of which show a secure UI.
- Appears to have no certificate at all, at least that I can surface through the UI:
<img width="453" alt="no tls" src="https://cloud.githubusercontent.com/assets/617481/11013979/af478a7e-8566-11e5-90ba-c4f3622777dc.png">

Very curious... Would love to learn better techniques for debugging what's going on here.

**Comment by steveklabnik** [comment]
So, what's interesting is that my Firefox does not consider "does not supply ownership information" enough to consider it insecure.

/cc @edunham , any idea what's up here?

**Comment by Ygg01** [comment]
I also had this problem on Windows 7, XUbuntu and Windows XP on Firefox 42.
![Image of problem displaying advance SSL settings](http://i.imgur.com/7Qt768p.png)

I suspect that the problematic issue is shared using Firefox Sync. This issue doesn't happen on Chrome.

**Comment by nagisa** [comment]
@steveklabnik Lack of owner information does not make website insecure. Rather, owner info only occurs in those more expensive certificates and the only thing it really does is “pimping up” the lock icon to something like
![screenshot from 2015-11-07 14-11-40](https://cloud.githubusercontent.com/assets/679122/11015095/7cb8f8c0-8559-11e5-823c-3bdf45db2e2c.png)

**Comment by steveklabnik** [comment]
Yeah, it was late when I saw this, and I thought that was the source of the
error, I realize it's about EV certs, not the actual error.

**Comment by ollie27** [comment]
Do you have `security.tls.version.max` in `about:config` set to 1 or something other than 3 by any chance?

**Comment by Ygg01** [comment]
@ollie27 it seems that is the issue. I have no idea what set that `security.tls.version.max` to 1, though?

**Comment by steveklabnik** [comment]
Someone on Twitter says we need to update NGINX.

**Comment by nagisa** [comment]
Sadly, the newest nginx on Ubuntu 14.04LTS (which is what we seem to be using) is what we’re using. Alternative would be to update whole OS to non-LTS (next LTS comes out in 16.04) or use our own build of nginx (comes with its own can of worms).

**Comment by ollie27** [comment]
@Ygg01 I don't know what could have changed that, it might be worth creating a fresh profile in case any of your other settings have weird values.

I don't know about updating nginx but the config should probably by reviewed as https://www.ssllabs.com/ssltest/analyze.html?d=doc.rust-lang.org shows some issues:
- not supporting TLS 1.0 which is what seems to have caused the issue here and presumably prevents some older clients from connecting
- weak Diffie-Hellman (DH) key exchange parameters

Using the Intermediate configuration from https://wiki.mozilla.org/Security/Server_Side_TLS will probably help.

**Comment by domenic** [comment]
Confirmed, it was security.tls.version.max set to 1 for me too! I can guarantee I never set this manually; that seems very bad. Maybe it is because I have been syncing the same Firefox profile for years, ever since before TLS 1.3 was supported?

Leaving open in case you want to track the server configuration changes here, but feel free to close!

**Comment by domenic** [comment]
Confirmed, it was security.tls.version.max set to 1 for me too! I can guarantee I never set this manually; that seems very bad. Maybe it is because I have been syncing the same Firefox profile for years, ever since before TLS 1.3 was supported?

Leaving open in case you want to track the server configuration changes here, but feel free to close!

**Comment by locka99** [comment]
I had this issue too and resetting the value fixed it. I don't know what set the value either - perhaps an add-on did it, or it's a legacy of something Firefox did in the past.
