### ISSUE TITLE
Extended error message not available for privacy errors

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#29665]
On currently nightly, I get:
```
$rustc --explain E0446
error: no extended information for E0446
```
([playpen](http://is.gd/C1X5tJ))

Yet the description for this error was merged weeks ago: #28312

**Comment by Manishearth** [comment]
cc @GuillaumeGomez , in the future when adding new diagnostics mods be sure to add a `build_diagnostic_array` call
