### ISSUE TITLE
Non-exported type in exported type signature does not error

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#29668]
```rust
mod m1 {
	struct A;
	pub fn x() -> A { A }
}

fn main() {
	let x=m1::x();
	println!("{:?}",&x as *const _ as *const u8);
}
```
This generates an error:
```
<anon>:3:16: 3:17 error: private type in exported type signature [E0446]
<anon>:3 	pub fn x() -> A { A }
         	              ^
```
Yet this compiles fine:
```rust
mod m1 {
	mod m2 { pub struct A; }
	use self::m2::A as A;
	pub fn x() -> A { A }
}

fn main() {
	let x=m1::x();
	println!("{:?}",&x as *const _ as *const u8);
}
```
However, one is unable to specify the return type of `m1::x()` outside of `m1`.

**Comment by jethrogb** [comment]
Related/potential dupe of #28450, #28325, #18082

**Comment by jethrogb** [comment]
There was some discussion on IRC that since `struct A` is marked `pub`, it *might* be exported, which *might* make this not-a-bug. I think it should be possible to definitively prove whether the type is exported in an accessible way. In particular, one might require for exported functions that when traversing up the path, at some point there must be a valid exported path for the function and all types in the function type signature.

**Comment by jethrogb** [comment]
Actually that can be circumvented by later re-exporting a module containing exporting a function but not a module exporting the appropriate type.

**Comment by petrochenkov** [comment]
According to RFC 136 a type is exported automatically if it's mentioned in any kind of public interface, with one minor sanity check - it should be marked as `pub`. It's not yet implemented though.
So, yeah, unnameable types is a thing. (But not necessarily a good one)

**Comment by drbo** [comment]
The D language has [Voldemort types](http://wiki.dlang.org/Voldemort_types), which are types that cannot be named.  In that language they are widely used.  However, I don't know how useful they are in Rust, which uses generics instead of templates.
