### ISSUE TITLE
Cannot build on Antergos (Arch-Linux based)

### ISSUE THREAD

**Issue by Carbon-Labs** [rust-lang/rust#29673]
I'm trying to build a cargo project with rust, but it isn't running.
```
Running `./encode-plus`
Could not execute process `./encode-plus` (never executed)

Caused by:
  Permission denied (os error 13)
```
It compiled, though. However, it did run when I was on Windows 10. What's wrong?

**Comment by apasel422** [comment]
@Carbon-Labs Can you post a link to the code?

**Comment by Carbon-Labs** [comment]
Sorry I didn't reply!

[Repo here](https://github.com/Carbon-Labs/Encode-Plus)

**Comment by fhahn** [comment]
@Carbon-Labs I managed to compile and run your project with Rust 1.4.0 (on Arch Linux). I had to remove `#![feature(str_split_at)]` from `main.rs` and add a `[[bin]]` section to your Cargo.toml however:

     [[bin]]
     name = "encode-plus"
     path = "main.rs"

Could you check if the problem still persists and if it does, could you provide some additional information, like which Rust version you are using and which commands you run exactly?

**Comment by Carbon-Labs** [comment]
It was Rust 1.3.0.

I ran `cargo run` to run it. I'll check if it works.

**Comment by Carbon-Labs** [comment]
Didn't work when I ran it, but now, I think a new update fixed the problem. Didn't need to change anything.

**Comment by Carbon-Labs** [comment]
I figured out what was wrong, finally. My file was on a USB stick, and the system did not like that. Also, I had to use `sudo`, even if it was not on a USB.
