### ISSUE TITLE
Tracking issue for `cfg_target_vendor`

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#29718]
Allows conditional compilation based on the target vendor, added in https://github.com/rust-lang/rust/pull/28612. This issue tracks stabilization.

**Comment by jethrogb** [comment]
Users will be needing this to distinguish between the in-tree `x86_64-fortanix-unknown-sgx` target and other `all(target_arch = "x86_64", target_env = "sgx")` targets, see #57231. Can this be moved to FCP for stabilization?

**Comment by nagisa** [comment]
cc @rust-lang/lang ^

**Comment by joshtriplett** [comment]
I don't see any risk to stabilizing `target_vendor`. Let's stabilize this. Could we get a stabilization PR?

**Comment by Centril** [comment]
In that stabilization PR I would like:
- A description of behavior being stabilized
- and of what is not
- divergences from any RFC (there aren't any... an explanation of why)
- links to relevant test files (both for what is accepted and what is rejected)
- how long this has been implemented, including a link to the implementing PR.

**Comment by jethrogb** [comment]
stabilization PR #57465
