### ISSUE TITLE
Document the traits that are #[derive]-able

### ISSUE THREAD

**Issue by mackwic** [rust-lang/rust#29711]
Hi Rust !

Neither on [the reference](http://doc.rust-lang.org/stable/reference.html#derive) nor the [doc of the trait itself](http://doc.rust-lang.org/std/cmp/trait.PartialEq.html) inform us of the derivability of the standard traits.

It would be great to have the list of all the derivable traits in the Reference, and each trait could have a note in its doc saying that this trait is automagically derivable.

Also, it could be worth pointing some of the issues with deriving in the doc.
A quick search showed me some lifetimes error in some special cases, and performance issue for large enums. This is something that could be in the doc of the traits with these known issues using auto-deriving.

**Comment by apasel422** [comment]
While it would be helpful to list them elsewhere, they are currently listed in the book: https://doc.rust-lang.org/nightly/book/traits.html#deriving.

**Comment by ebfull** [comment]
Note that nothing appears to prevent that list from going out of date.

**Comment by nixpulvis** [comment]
> However, deriving is limited to a certain set of traits [...]

This limitation would be nice to get away from as well. I'm not sure if this has been discussed elsewhere.

**Comment by apasel422** [comment]
@nixpulvis See https://users.rust-lang.org/t/implementing-a-custom-derive-foo-macro/1965.

**Comment by steveklabnik** [comment]
> each trait could have a note in its doc saying that this trait is automagically derivable.

I think this is the right way to go to solve this issue, for sure. It's not in the reference because it's not _really_ a language thing, and the restriction will go away eventually.
