### ISSUE TITLE
Tracking issue for `braced_empty_structs` (RFC 218)

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#29720]
Allows empty structs using braces, as per https://github.com/rust-lang/rfcs/pull/218. This issue tracks stabilization.

**Comment by petrochenkov** [comment]
Need to land https://github.com/rust-lang/rust/pull/29383 and fix https://github.com/rust-lang/rust/issues/29548 before stabilizing

**Comment by petrochenkov** [comment]
I'd like to have this stabilized in this cycle.
https://github.com/rust-lang/rust/issues/29548 can actually be fixed in much cleaner way if the feature gate is removed, so I suggest to remove it now and not in the end of the cycle.

**Comment by petrochenkov** [comment]
I can't ping @rust-lang/lang, so ping @aturon

**Comment by alexcrichton** [comment]
cc @rust-lang/lang (yay github permissions?)

**Comment by alexcrichton** [comment]
triage: I-nominated

**Comment by aturon** [comment]
The lang team is moving this feature into **final comment period**. :8ball:

**Comment by aturon** [comment]
The lang team has decided to **stabilize** this feature.
