### ISSUE TITLE
Improve "previous borrow" location in borrow error message

### ISSUE THREAD

**Issue by thibault-ml** [rust-lang/rust#29733]
Given the following code:

``` rust
use std::collections::HashMap;

fn main() {
    let mut vec = vec![0, 1, 2, 3, 4];
    let mut map = HashMap::<&i32, &str>::new();

    for key in &vec {
        map.insert(key, "value");
    }

    vec.push(5);
}
```

The compiler will complain with the following error message:

```
error[E0502]: cannot borrow `vec` as mutable because it is also borrowed as immutable
  --> /tmp/test_borrow_message.rs:11:5
   |
7  |     for key in &vec {
   |                 --- immutable borrow occurs here
...
11 |     vec.push(5);
   |     ^^^ mutable borrow occurs here
12 | }
   | - immutable borrow ends here

error: aborting due to previous error
```

While the borrow error is expected, the message seems pretty unclear to me. 

Removing/commenting the `map.insert(key, "value");` line will allow rustc to compile the file, which shows the problem isn't really exactly with the borrow happening at line 7 (for loop), but with the fact that the borrow is then extended to the lifetime of the `map` variable.
This can be verified with the following code which works because the `map` variable is gone by the time we need to mutable borrow again:

``` rust
use std::collections::HashMap;

fn main() {
    let mut vec = vec![0, 1, 2, 3, 4];
    {
        let mut map = HashMap::<&i32, &str>::new();
        for key in &vec {
            map.insert(key, "value");
        }
    }
    vec.push(5);
}
```

It feels like the compiler should be clearer as to where the borrow is actually "stored". It's able to show that the borrow ends when `map` goes away, so I feel it should be clearer that the borrow issue stems from the `map.insert(key, "value");` line, which extends the borrow's "lifetime" to the lifetime of `map`

(this error is output by rust 1.4.0)

**Comment by steveklabnik** [comment]
So, the borrow _is_ happening during the `&vec`. The reason that it works if you remove the `insert()` call is that that's what's causing the problem: you're trying to take a `&mut` borrow out on something that's already borrowed.

**Comment by Kixunil** [comment]
Seems like it's similar to one [I've encountered](https://play.rust-lang.org/?gist=321bf058921fc67bb451376297faa022&version=stable&backtrace=0). (Try commenting-out body of `for` loop.)
