### ISSUE TITLE
this rustbook sentence is confusing (to me)

### ISSUE THREAD

**Issue by zazdxscf** [rust-lang/rust#29730]
`If you are writing, you need two or more pointers to the same memory, and you can only have one &mut at a time.`
from: https://doc.rust-lang.org/nightly/book/references-and-borrowing.html#the-rules

**Comment by steveklabnik** [comment]
I agree that it's a bit odd, yeah. I'll try to figure out a better phrasing.

It's trying to say that if you don't have two pointers to the same location in memory, you can't get a race, since a race inherently means two simultaneous load/stores.

**Comment by norcalli** [comment]
What about "However, as we can only have one `&mut` at a time (the only kind of reference that can write), it is impossible to have a data race." It works as a drop in replacement for that sentence. You could drop the stuff in parentheses as well for succinctness.

**Comment by steveklabnik** [comment]
I like it.

**Comment by norcalli** [comment]
Should I make a PR or is there an aggregate PR for minor changes like this?

**Comment by steveklabnik** [comment]
We don't do aggregate PRs, feel free to send one in for just this, thanks!
:)
