### ISSUE TITLE
Arithmetic makes borrow checker overly restrictive

### ISSUE THREAD

**Issue by dotdash** [rust-lang/rust#29743]
UPDATE: This was fixed by #47167 but still [needs a regression test to be added](https://github.com/rust-lang/rust/issues/29743#issuecomment-358650299).

----

``` rust
fn main() {
    let mut i = [1,2,3];
    i[i[0]] = 0; // Works
    i[i[0] - 1] = 0; // Is rejected
}
```

I had expect the `- 1` not to make any difference, but the borrow checker complains with the following error:

```
<anon>:4:7: 4:11 error: cannot use `i[..]` because it was mutably borrowed
<anon>:4     i[i[0] - 1] = 0;
               ^~~~
<anon>:4:5: 4:6 note: borrow of `i` occurs here
<anon>:4     i[i[0] - 1] = 0;
```

**Comment by steveklabnik** [comment]
@rust-lang/lang, is this behavior expected? I wonder if there's something weird going on here

**Comment by nikomatsakis** [comment]
Does seem odd. I suspect that the borrow checker is (incorrectly) still locked into the days when indices were passed by reference, rather than by value.

**Comment by nikomatsakis** [comment]
triage: P-medium

**Comment by nikomatsakis** [comment]
Likely to be fixed by MIR, though.

**Comment by sanxiyn** [comment]
Still reproduces.

**Comment by nikomatsakis** [comment]
(Note: would be fixed by a borrowck-based MIR is what I meant, which is not yet done.)

**Comment by cyplo** [comment]
Still seems to be a problem on rustc 1.23.0-nightly (8b22e70b2 2017-10-31) - not sure if expected ?

```
error[E0503]: cannot use `i[..]` because it was mutably borrowed
 --> main.rs:4:7
  |
4 |     i[i[0] - 1] = 0; // Is rejected
  |     - ^^^^ use of borrowed `i`
  |     |
  |     borrow of `i` occurs here

error: aborting due to previous error
```

**Comment by pnkfelix** [comment]
Hmm MIR-borrowck does not seem to address this case, at least not out-of-the-box

**Comment by nikomatsakis** [comment]
The first question is to decide, I suppose, what the expected behavior is =)

**Comment by nikomatsakis** [comment]
In other words, I think I would expect consistent behavior, but I could see how this might wind up as an error in both cases.

**Comment by nikomatsakis** [comment]
Well, based on [this play test case](https://play.rust-lang.org/?gist=e14c2ae1093cd6e227d625b370fc80df&version=nightly), we do not get consistent behavior.

**Comment by nikomatsakis** [comment]
I wonder if https://github.com/rust-lang/rust/pull/47167 will affect this, actually.

**Comment by nikomatsakis** [comment]
Seems like #47167 fixes it.

**Comment by nikomatsakis** [comment]
It now [works on nightly](https://play.rust-lang.org/?gist=8e3ac46d42e5b376dfbbeb21cc0ee84a&version=nightly). Marking as E-needstest. Removing from WG-compiler-nll, since this was not specific to NLL in any way.
