### ISSUE TITLE
docs: Explain the borrowing happening when matching data-variant enums within structs

### ISSUE THREAD

**Issue by thibault-ml** [rust-lang/rust#29745]
I believe the documentation, either in the "Borrowing" or the "Enums" section, could be a bit more explicit about what happens when using enums that have data components.

This bug reports just shows how I went along and tried to understand what was happening, and while all of it now makes sense, I believe it could be good to have the documentation explain what is happening a bit more.

Take the following code:

```rust
#[derive(Debug, Clone, Eq, PartialEq)]
enum SessionStatus {
    NeedInput,
    NeedToWrite(String),
}

struct Session {
    status: SessionStatus,
}

impl Session {
    fn execute(mut self) -> Option<Self> {
        match self.status {
            SessionStatus::NeedToWrite(string_value) => {
                println!("Need to write: {:?}", string_value);
            }
            _ => {}
        }
        Some(self)
    }
}
```

This generates the following compiler error:
```
/tmp/test-rust/test_enum.rs:20:14: 20:18 error: use of partially moved value: `self` [E0382]
/tmp/test-rust/test_enum.rs:20         Some(self)
                                            ^~~~
/tmp/test-rust/test_enum.rs:20:14: 20:18 help: run `rustc --explain E0382` to see a detailed explanation
/tmp/test-rust/test_enum.rs:14:40: 14:52 note: `(self.status:SessionStatus::NeedToWrite).0` moved here because it has type `collections::string::String`, which is moved by default
/tmp/test-rust/test_enum.rs:14             SessionStatus::NeedToWrite(string_value) => {
                                                                      ^~~~~~~~~~~~
/tmp/test-rust/test_enum.rs:14:40: 14:52 help: if you would like to borrow the value instead, use a `ref` binding as shown:
/tmp/test-rust/test_enum.rs:               SessionStatus::NeedToWrite(ref string_value) => {
error: aborting due to previous error
```

Which, if I understand correctly, means `self` was moved (moved where or to what variable, I don't know), because the `String` owned by the `status` ivar was moved as well.
I believe I now understand that this is because the `String` is owned by `self.status`, so the `String` value has to be borrowed via a `ref`, because it cannot just be "moved out" `self.status`.

Now, let's say I've added the `ref`, and wanted to modify the status:

```rust
impl Session {
    fn execute(mut self) -> Option<Self> {
        match self.status {
            SessionStatus::NeedToWrite(ref string_value) => {
                println!("Need to write: {:?}", string_value);
                self.status = SessionStatus::NeedInput;
            }
            _ => {}
        }
        Some(self)
    }
}
```

The compiler complains:

```
/tmp/test-rust/test_enum.rs:16:17: 16:55 error: cannot assign to `self.status` because it is borrowed
/tmp/test-rust/test_enum.rs:16                 self.status = SessionStatus::NeedInput;
                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/test-rust/test_enum.rs:14:40: 14:56 note: borrow of `self.status` occurs here
/tmp/test-rust/test_enum.rs:14             SessionStatus::NeedToWrite(ref string_value) => {
                                                                      ^~~~~~~~~~~~~~~~
error: aborting due to previous error
```

This code matches against `SessionStatus::NeedToWrite` and creates a variable `string_value` that is a reference to `(self.status:SessionStatus::NeedToWrite).0`, so we can't reassign `self.status` while a reference to it exists. This makes sense.

Now, if I remove the `ref` but keep the assignment:

```rust
impl Session {
    fn execute(mut self) -> Option<Self> {
        match self.status {
            SessionStatus::NeedToWrite(string_value) => {
                println!("Need to write: {:?}", string_value);
                self.status = SessionStatus::NeedInput;
            }
            _ => {}
        }
        Some(self)
    }
}
```

This now works! My understanding is the following:
Moving the `String` contained by `SessionStatus::NeedToWrite` in `self.status` resulted in a partially moved value of `self`, because `self.status` was referring to an enum value whose data was moved. However, this code works because we are setting `self.status` to a new value, meaning `self.status` is not referring to a moved value anymore.

Again, this all make sense, and I now find this behaviour totally expected (and pretty awesome that it is checked), but I believe the documentation could do with a little clarification for new starters, because it may not be as obvious to everyone starting with Rust and struggling with references and the borrow checker.

**Comment by steveklabnik** [comment]
Hey @thibault-ml ! First off, sorry that I left no comment here. New year, finding out old issues that slipped through the cracks. :)

I'm working on a new draft of the book that's basically completely re-written, and so will cover this stuff in a lot more depth. So I'm not as focused on tweaking the existing one. So if you wanted to send a PR with some updates, I would probably accept them, but for now, this isn't super likely to change. I do agree that this is a weakness, but it'd take some work to fix, and would end up going away anyway... thank you for bringing it up!
