### ISSUE TITLE
Missing the Ternary Conditional Operator

### ISSUE THREAD

**Issue by dangerrust** [rust-lang/rust#29747]
Hello,

It looks like Rust forgot to implement the ternary conditional operator

It's operator that looks like this: `condition ? trueExpression : falseExpression`

This important feature lets you do things like `return value == 5 ? success : failure;`

I think it easy to add support for this in Rust

**Comment by Toby-S** [comment]
In Rust everything is an expression, so you can just use:

```rust
if condition { trueExpression } else { falseExpression }
```

**Comment by Gankro** [comment]
Rust will never implement the ternary. If-else is adequate, and it's a waste of great symbols.

**Comment by bluss** [comment]
Better places to possible extensions of the Rust language is primarily http://internals.rust-lang.org and the [RFC repo](https://github.com/rust-lang/rfcs).
