### ISSUE TITLE
Don't build stage0 libstd etc.

### ISSUE THREAD

**Issue by eefriedman** [rust-lang/rust#29756]
We should be able to build rustc against the snapshot's libstd, rather than building a stage0 libstd.  This has a bunch of benefits:

- It improves build times.
- It removes the need to add cfg(stage0) hacks to libstd ever again.
- It would provide a path to eventually build rustc against stable rustc without any hacks.

Possible downsides:
- Increased build times for people hacking on libstd; probably not a big deal given that stage0 compiler bits wouldn't depend on the modified libstd.
- The stage0 built compiler is slightly less representative of the current state of the codebase.

**Comment by alexcrichton** [comment]
This is more possible with today's rustbuild build system, but I think it's pretty unlikely to happen for awhile. We're bootstrapping from nightlies so we do actually have a libstd to use, but a prerequisite for this is probably to get the compiler off unstable APIs from the standard library, which would likely be a pretty major effort in itself.

For now though I'm gonna close as hopefully rustbuild targets a number of concerns with build times and such, and also targets the concern of building with a stable rustc (as in theory `cargo build` would "just work" if it's only using stable libstd APIs)
