### ISSUE TITLE
book should mention crates.io in FFI chapter

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#29762]
If you blindly copy the example code from the FFI chapter you get the "libc is unstable" warning.

**Comment by durka** [comment]
Ugh... so the examples have a hidden `#![feature(libc)]` line, so you'll see that if you click through to the playpen. I see why it's done that way (so the examples are runnable) but it seems bad, pedagogically. Thoughts?

**Comment by steveklabnik** [comment]
The issue is, normally, you want to copy the code exactly, and put libc in your cargo.toml. That's why I hid it.

**Comment by durka** [comment]
Yeah, that makes sense. So maybe just a mention at the beginning about putting libc in Cargo.toml. And maaaybe another sentence about how if you click the examples some extra lines get inserted to make it compile in the playpen? (About half of them don't compile anyway since they refer to nonexistent libraries, though this could be fixed with even more hidden lines containing `#[cfg]` trickery.)

**Comment by steveklabnik** [comment]
:+1:

**Comment by durka** [comment]
Fun bash ...thing to pull code blocks out of a Markdown file and try compiling them:

```bash
for block in $(grep -n '```' src/doc/trpl/ffi.md | paste -s -d ':\n' - | grep 'rust\|no_run')
do
    from=$(echo $block | cut -d: -f1);
    to=$(echo $block | cut -d: -f3);
    f=$(mktemp /tmp/doctest.XXX);
    head -$((to - 1)) src/doc/trpl/ffi.md | tail -$(($to - $from - 1)) | sed 's/^# //' >$f;
    mr ru nightly rustc $f >/dev/null 2>&1 && rm doctest;
    echo $?;
    rm $f;
done
```

**Comment by steveklabnik** [comment]
`rustdoc --test path/to/markdown` will do that already :)

**Comment by durka** [comment]
Oh, how about that :)

**Comment by durka** [comment]
Does that not try linking? 'Cause it says everything passes but my bash script disagrees.
