### ISSUE TITLE
Support bitshift in left arm of match

### ISSUE THREAD

**Issue by daschl** [rust-lang/rust#29779]
Hi folks,

I don't know if I'm doing something wrong, but I have the feeling this should work. So for example this works, as expected:

```rust
	fn from_i64(n: i64) -> Option<Self> {
		match n {
			1 => Some(TopologyFlag::WholeSystem),
			2 => Some(TopologyFlag::IsThisSystem),
			4 => Some(TopologyFlag::IoDevices),
			8 => Some(TopologyFlag::IoBridges),
			16 => Some(TopologyFlag::WholeIo),
			32 => Some(TopologyFlag::ICaches),
			_ => None,
		}
	}
```

Now when I use bitshift on the left arms of the match it doesn't compile

```rust
	fn from_i64(n: i64) -> Option<Self> {
		match n {
			1 << 0 => Some(TopologyFlag::WholeSystem),
			1 << 1 => Some(TopologyFlag::IsThisSystem),
			1 << 2 => Some(TopologyFlag::IoDevices),
			1 << 3 => Some(TopologyFlag::IoBridges),
			1 << 4 => Some(TopologyFlag::WholeIo),
			1 << 5 => Some(TopologyFlag::ICaches),
			_ => None,
		}
	}
```

with

```
   Compiling hwloc v0.1.0 (file:///Users/michael/rust/hwloc-rs)
src/ffi.rs:118:6: 118:8src/ffi.rs:118:6: 118:8  errorerror: : expected one of `...`, `=>`, `if`, or `|`, found `<<`expected one of `...`, `=>`, `if`, or `|`, found `<<`

src/ffi.rs:118 			1 << 0 => Some(TopologyFlag::WholeSystem),src/ffi.rs
:118 			1 << 0 => Some(TopologyFlag::WholeSystem),
               			                 			  ^~
^~
Build failed, waiting for other jobs to finish...
Could not compile `hwloc`.

To learn more, run the command again with --verbose.
```

Maybe this can be treated as a feature request? I also tried to wrap it like (1 << 1), but no dice.

**Comment by durka** [comment]
The left side of a match arm isn't an expression, it's a pattern. So I would say this is very unlikely.

**Comment by durka** [comment]
You can rewrite the arm from `1 << n` to `x if x == 1 << n`.

**Comment by daschl** [comment]
Thanks for the clarification! If this is not making sense to add feel free to close:) I'll keep it open for now in case someone else wants to add thoughts as well :)

**Comment by nagisa** [comment]
```rust
const A: u8 = 1<<2;
fn main(){
    match 4 {
        A => panic!("yay"),
        _ => panic!("nay"),
    }
}
```

however takes a `yay` branch, so you could make yourself a macro which would desugar into consts and match like this yourself.

Either way, this issue belonds to rust-lang/rfcs repository.

**Comment by Toby-S** [comment]
cc @steveklabnik needs rfc

**Comment by Aatch** [comment]
As @nagisa says, this would be an RFC, so I'll close it and refer you to [rust-lang/rfcs](https://github.com/rust-lang/rfcs)

Supporting constant expressions as irrefutable patterns doesn't seem *too* bad to me, so I think it's definitely worth an RFC to discuss it if you want to take it further.

**Comment by daschl** [comment]
It's fine for me the way it is, if someone wants to run with an RFC that's also fine for me as well - I currently don't have the time and skills to push one down the stream :)
