### ISSUE TITLE
nomicon: reference to copy_lifetime

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#29784]
http://doc.rust-lang.org/nightly/nomicon/unbounded-lifetimes.html mentions a fn called `copy_lifetime` but there is no such fn (anymore?).

**Comment by apasel422** [comment]
CC @Gankro.

**Comment by Gankro** [comment]
Yeah this is what it was: https://doc.rust-lang.org/1.0.0/std/mem/fn.copy_lifetime.html

text needs updating.
