### ISSUE TITLE
ICE when compiling winapi-rs

### ISSUE THREAD

**Issue by untitaker** [rust-lang/rust#29783]
Compiling advapi32-sys v0.1.2
       Compiling kernel32-sys v0.2.1
       Compiling kernel32-sys v0.1.4
    error: internal compiler error: unexpected panic
    note: the compiler unexpectedly panicked. this is a bug.
    note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/m
    aster/CONTRIBUTING.md#bug-reports
    thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Error {
     repr: Os { code: 1, message: "Incorrect function." } }', ../src/libcore\result.
    rs:736

    stack backtrace:
       0: 0x638fd257 - register_frame_ctor
       1: 0x638c5564 - register_frame_ctor
       2: 0x63919aa0 - register_frame_ctor

    error: internal compiler error: unexpected panic
    note: the compiler unexpectedly panicked. this is a bug.
    note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/m
    aster/CONTRIBUTING.md#bug-reports
    thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Error {
     repr: Os { code: 1, message: "Incorrect function." } }', ../src/libcore\result.
    rs:736

    stack backtrace:
       0: 0x638fd257 - register_frame_ctor
       1: 0x638c5564 - register_frame_ctor
       2: 0x63919aa0 - register_frame_ctor

    error: internal compiler error: unexpected panic
    note: the compiler unexpectedly panicked. this is a bug.
    note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/m
    aster/CONTRIBUTING.md#bug-reports
    thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Error {
     repr: Os { code: 1, message: "Incorrect function." } }', ../src/libcore\result.
    rs:736

    stack backtrace:
       0: 0x638fd257 - register_frame_ctor
       1: 0x638c5564 - register_frame_ctor
       2: 0x63919aa0 - register_frame_ctor

    Build failed, waiting for other jobs to finish...
    Could not compile `kernel32-sys`.

    To learn more, run the command again with --verbose.

    E:\rust-atomicwrites>

This happens when running `cargo test` on [rust-atomicwrites](https://github.com/untitaker/rust-atomicwrites), but it also happens when running `cargo test` on a git clone of `winapi-rs`. Same exact backtrace, on many modules like `advapi-rs` or `kernel32-sys`.

I don't get this issue in appveyor. I'm running Rust 1.4 (the 32-bit version) on Windows 7 Ultimate (SP1) inside of VirtualBox.

**Comment by untitaker** [comment]
C:\Users\untitaker>rustc --version --verbose
    rustc 1.4.0 (8ab8581f6 2015-10-27)
    binary: rustc
    commit-hash: 8ab8581f6921bc7a8e3fa4defffd2814372dcb15
    commit-date: 2015-10-27
    host: i686-pc-windows-gnu
    release: 1.4.0

**Comment by alexcrichton** [comment]
Hm I can't seem to reproduce this locally either, did you perhaps specify some custom options when installing?

**Comment by untitaker** [comment]
Nope.

That Windows VM is pirated and hasn't recieved updates for two years though. The update process itself is broken, it always ends up reverting them. I wonder if it makes sense to even keep this issue open.

**Comment by alexcrichton** [comment]
If you can, using gdb to get a better backtrace may be useful to help pinpoint where this is coming from

**Comment by untitaker** [comment]
The VM recently trashed itself and can't be booted up anymore. I'm closing this for now.

Sorry for the low-quality bugreport.
