### ISSUE TITLE
[MIR] Add hair::Constant<'tcx> and change ExprKind::Repeat to use it

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#29789]
See https://github.com/nagisa/rust/commit/234c5c39830595442a68d7963cfb62af4dadcc62#commitcomment-14339085 and relevant FIXME in src/librustc_mir/hair/mod.rs

**Comment by nikomatsakis** [comment]
As a side-note, http://smallcultfollowing.com/babysteps/blog/2015/08/20/virtual-structs-part-3-bringing-enums-and-structs-together/ would solve this problem quite neatly, if we were to adopt and implement it. :)
