### ISSUE TITLE
index is not an integer constant expression when using const fn argument

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#29798]
``` rust
#![feature(const_fn)]
const fn test(x: usize) -> i32 {
    [42;5][x]
}
fn main () {
    let _ = test(5);
}
```

<del>I guess we cannot const evaluate the index anymore but must translate it with llvm's constant evaluator, because it might only be available as a value we got from a static. But then I'm not sure how to do the range check.</del>

Nope, that's not a problem. Is there any reason not to thin out trans/consts down to the point where it's just a thin wrapper around const_eval + translation of `ConstVal` to `ValueRef`?

I mean after #25570 (const indexing), since after that I think the const_eval is feature-equivalent with the const translator.

**Comment by eefriedman** [comment]
const_eval currently can't return an address as a result (needed to evaluate e.g. `const I: &'static u32 = &1`).

Granted, that isn't a fundamental issue.

**Comment by oli-obk** [comment]
right. That would be solvable by adding a `ConstVal::Ref` variant.

**Comment by oli-obk** [comment]
This now ices with `thread 'main' panicked at 'index out of bounds: the len is 5 but the index is 5'`

**Comment by Mark-Simulacrum** [comment]
No longer ICEs or errors. E-needstest.
