### ISSUE TITLE
in stmt context, seq!(() "") accepted while seq!("" 4) rejected

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#29799]
(spawned off of #25658)

This may not necessarily be a macro expansion issue, but that seems like the most likely candidate.

The following code:

``` rust
macro_rules! seq {
    ($($e:expr)*) => ($($e)*);
}

fn main() {
    {      (); "";  }
    { seq!(()  ""); }

    {      "";  4;  }
    { seq!(""   4); }
}
```

yields the following compilation error:

``` rust
% rustc /tmp/seq.rs
/tmp/seq.rs:10:12: 10:14 error: mismatched types:
 expected `()`,
    found `&'static str`
(expected (),
    found &-ptr) [E0308]
/tmp/seq.rs:10     { seq!(""   4); }
                          ^~
/tmp/seq.rs:10:7: 10:20 note: in this expansion of seq! (defined in /tmp/seq.rs)
/tmp/seq.rs:10:12: 10:14 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
% 
```

but according to `rustc -Z unstable-options --pretty expanded`, there is no difference between the second `seq!` and the expression that precedes it:

``` rust
% rustc --version
rustc 1.6.0-dev (eacd35984 2015-11-03)
% rustc -Z unstable-options --pretty expanded /tmp/seq.rs
#![feature(no_std, prelude_import)]
#![no_std]
#[prelude_import]
use std::prelude::v1::*;
#[macro_use]
extern crate std as std;

fn main() {
    { (); ""; }
    { (); ""; }

    { ""; 4; }
    { ""; 4; }
}
% 
```

(My current suspicion is that the `--pretty expanded` is not showing us the closest match to the actual AST being produced by expansion.)

**Comment by nikomatsakis** [comment]
This is almost certainly related to the "statements that do not have semicolons must have unit type". I imagine it's related to the parser's behavior when it encounters an "expr token". The pretty printer output is probably somewhat misleading.

**Comment by Mark-Simulacrum** [comment]
The example now doesn't compile with a different error, which seems correct, since `() ""` isn't valid Rust. This appears to be because the macro no longer inserts semicolons after expressions automatically, if the macro is edited to insert them (`($($e:expr)*) => ($($e;)*);` then the code does, indeed, compile.

New error:
```
error: expected one of `.`, `;`, `?`, `}`, or an operator, found `""`
 --> src/lib.rs:2:25
  |
2 |     ($($e:expr)*) => ($($e)*);
  |                         ^^ expected one of `.`, `;`, `?`, `}`, or an operator here

error: expected one of `.`, `;`, `?`, `}`, or an operator, found `4`
 --> src/lib.rs:2:25
  |
2 |     ($($e:expr)*) => ($($e)*);
  |                         ^^ expected one of `.`, `;`, `?`, `}`, or an operator here

error: aborting due to 2 previous errors
```
