### ISSUE TITLE
Unreachable code suppresses warnings

### ISSUE THREAD

**Issue by ranma42** [rust-lang/rust#29803]
```rust
println!("{}", false && ((1u8 - 5u8) == 42));
```
results in "warning: attempted to sub with overflow", but
```rust
println!("{}", if false { ((1u8 - 5u8) == 42) } else { false });
```
compiles with no warning at all.

I would expect both expressions to warn, either because of the overflow or because of dead code (or both).

**Comment by 0xmohit** [comment]
The second example produces warning with 1.12.0 -- <https://is.gd/Pz7wkc>.
