### ISSUE TITLE
ICE with *-*-ios targets without ios developer stuff installed

### ISSUE THREAD

**Issue by wthrowe** [rust-lang/rust#29812]
```
$ echo 'fn main() {}' | rustc - -Z unstable-options --pretty=normal --target=x86_64-apple-ios
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'failed to get iphonesimulator SDK path: No such file or directory (os error 2)', src/librustc_back/target/apple_ios_base.rs:59
```

I don't expect to be able to actually compile anything with those targets, but it shouldn't ICE and most of the `--pretty` modes should probably work.  (`--pretty` works with all other targets, except for `--pretty=typed` because that needs libstd.)

**Comment by cardoe** [comment]
This should likely improve with #34980.

**Comment by japaric** [comment]
Triage: Still happens with 1.11.0:

```
$ rustup run stable rustc -V
rustc 1.11.0 (9b21dcd6a 2016-08-15)

$ rustup run stable rustc --target aarch64-apple-ios --print cfg
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'failed to get iphoneos SDK path: No such file or directory (os error 2)', ../src/librustc_back/target/apple_ios_base.rs:59
```

Copying Alex's [comment](https://github.com/rust-lang/rust/issues/36157#issuecomment-243820605) on a duplicate issue here so it doesn't get lost:

> I believe this has essentially always been the case, but I'd love to have a fix! I think the best choice here is to delay the pieces of the iOS target that are fallible until we actually need them, for example at link time.

**Comment by cardoe** [comment]
@japaric The change I mentioned didn't land until 1.12.0. I've removed the explicit `panic!()` call and now its returning a `Result` which I believe is now handled gracefully. I'd love if you could test it for me.

```
$ rustup run beta rustc --target aarch64-apple-ios --print cfg
```

My Mac has Xcode installed now and I haven't had the time to uninstall it to test this.

**Comment by cardoe** [comment]
This is confirmed to not ICE and can be closed.

**Comment by alexcrichton** [comment]
Yay!
