### ISSUE TITLE
DragonFlyBSD builder cannot build rustc

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#29818]
See http://buildbot.rust-lang.org/builders/auto-dragonflybsd-64-opt/builds/554/steps/compile/logs/stdio

```
rustc: x86_64-unknown-dragonfly/stage0/lib/rustlib/x86_64-unknown-dragonfly/lib/libstd
../src/libstd/sys/unix/stack_overflow.rs:48:16: 48:24 error: unresolved import `libc::SIGSTKSZ`. There is no `SIGSTKSZ` in `libc` [E0432]
../src/libstd/sys/unix/stack_overflow.rs:48                SIGSTKSZ, sighandler_t};
                                                           ^~~~~~~~
```

**Comment by nagisa** [comment]
cc @alexcrichton since you seem to be the maintainer of the new liblibc.

**Comment by alexcrichton** [comment]
I'm personally not a huge fan of keeping around tracking bugs for things like this, there are likely hundreds of platforms that Rust doesn't compile on! That being said this seems like something either needs to be added to libc or the submodule just needs to be updated.
