### ISSUE TITLE
Exception for cyclic-safe traits

### ISSUE THREAD

**Issue by james-darkfox** [rust-lang/rust#29826]
Thy cyclic supertrait lint and super-trait tracing code should have an exception to allow for cyclic-safe traits.

https://play.rust-lang.org/?gist=cc794942ed0663d530d8&version=nightly

A trait definition like this is currently invalid.
```rust
trait Mode<M>: Mode<A> { type Return; }
```
Instead of being invalid, this should cut the recursion at the point that `M == RequiredMode`.

Any type that implements `Mode<B>` **must** also implement `Mode<A>` and when selecting specific traits with `<T as Trait>`, the exact trait should be respected.
```rust
<T as Mode<B>>::Return // B
<T as Mode<A>>::Return // A
<<T as Mode<B>> as Mode<A>>::Return // A
```

As demonstrated in #12511, I would also say that `trait T: T {}` should be the identity of `T`, and consequently be the identity of the exception to permit cyclic-safe types.

### Cyclic safe traits

```rust
trait Trait: Trait { ... } // Trait == Trait, stop recurring // lint redundant trait?
```
```rust
trait Mode<M>: Mode<A> { ... } // When M == A, stop recurring
```

### Cyclic unsafe traits

```rust
trait A: B { ... }
trait B: A { ... } 
```

**Comment by eefriedman** [comment]
In theory, there isn't any reason we can't support `trait A: B { ... } trait B: A { ... }`.  We can reason about the cycle the same way we can for `trait A: A`.

**Comment by james-darkfox** [comment]
@eefriedman True but that would require understanding the known state, instead of just with the exact trait definition. I think that would require a little more work, but indeed, doable.

**Comment by arielb1** [comment]
@james-darkfox 

It was an intentional design decision not to allow for cyclic traits. If you desire to change it, you should post an issue at [rust-lang/rfcs](/rust-lang/rfcs/issues).
