### ISSUE TITLE
[Suggestion] taking some FORTRAN ideas for making rust scientific compute friendly ? 

### ISSUE THREAD

**Issue by LifeIsStrange** [rust-lang/rust#29829]
https://www.ibiblio.org/pub/languages/fortran/ch1-2.html
https://www.researchgate.net/post/Why_is_fortran_extensively_used_in_scientific_computing_and_not_any_other_language
:)

**Comment by Toby-S** [comment]
If you're interested in discussing some of the ideas mentioned there, a more appropriate place to post would be on the [Rust subreddit](https://reddit.com/r/rust), or on the [Rust users site](http://users.rust-lang.org). If you want to propose a specific idea (or ideas) instead, you should open [an rfc](https://github.com/rust-lang/rfcs).

**Comment by LifeIsStrange** [comment]
Ok sorry, should I close the issue ?

**Comment by Toby-S** [comment]
No problem, and yes, that's probably a good idea :-)
