### ISSUE TITLE
Lifetime suggestions missing when implicit Trait+'static is present.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#29849]
Neither of the following two examples give suggestions for a working signature:

``` rust
fn foo(x: &i32) -> &'static i32 { x }
```

``` rust
fn foo(x: &i32) -> Box<std::fmt::Debug> {
    Box::new(x)
}
```

In the first example, it's somewhat understandable, because the `'static` there is explicit.
However, in the second example, the `'static` is implied by the owned trait object.

Suggestions are provided for both of the examples, if `'static` is replaced with a paramter:

``` rust
// help: consider using an explicit lifetime parameter as shown:
// fn foo<'a>(x: &'a i32) -> &'a i32
fn foo<'a>(x: &i32) -> &'a i32 { x }
```

``` rust
// help: consider using an explicit lifetime parameter as shown:
// fn foo<'a>(x: &'a i32) -> Box<std::fmt::Debug+ 'a>
fn foo<'a>(x: &i32) -> Box<std::fmt::Debug+'a> {
    Box::new(x)
}
```

**Comment by Mark-Simulacrum** [comment]
I'm going to close this since we don't give lifetime suggestions anymore and the new work on that will presumably cause both new bugs and fix old bugs; it doesn't seem useful to keep this open. Feel free to reopen though.
