### ISSUE TITLE
[MIR] Drop is missing for `_` function arguments

### ISSUE THREAD

**Issue by dotdash** [rust-lang/rust#29856]
```rust
#![feature(rustc_attrs)]

struct Drp;
impl Drop for Drp {
    fn drop(&mut self) {
    }
}

#[rustc_mir(graphviz="test.gv")]
fn into_inner(_: Drp) {
}

fn main() {
}
```

There is no `Drop` in the MIR for the function argument at all. In fact, all the starting block does is to jump to the end block.

**Comment by nikomatsakis** [comment]
We had some brief discussion on IRC. I think my intention was that we would drop the args, much as we do in trans today. (And the processing for dynamic drop would remove those when not needed.)

**Comment by nikomatsakis** [comment]
Relevant conversation on IRC: https://botbot.me/mozilla/rustc/2015-11-17/?msg=54339937&page=2

**Comment by nagisa** [comment]
The drop now exists.
