### ISSUE TITLE
Stack vs. Heap documentation could use more colours

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#29854]
https://doc.rust-lang.org/stable/book/the-stack-and-the-heap.html includes many large tables with some connection to code, but they and the transitions between them are somewhat complicated. So one (somewhat) low-hanging fruit for improving the stack v. heap documentation would be using more colours to connect stack variables with the function they come from.

E.g. "Let’s try a three-deep example:" could look like

```rust
fn red() {
    let i = 6;
}

fn blue() {
    let a = 5;
    let b = 100;
    let c = 1;

    red();
}

fn main() {
    let x = 42;

    blue();
}
```

![mockup](https://cloud.githubusercontent.com/assets/1203825/11176277/6a254974-8c8f-11e5-8bbf-3b77f1daefae.png)

(There's a mistake in the text: "And then `red()` calls `blue()`" should be "And then `blue()` calls `red()`".)

It would be important to just use these as an extra piece, not core to the explanation, for (colour-)blind people.

Inspired/suggested by [@velartrill on twitter](https://twitter.com/velartrill/status/666152044336701440), who also [suggests using greys in a slightly different way](https://twitter.com/velartrill/status/666156550654984194).

**Comment by brson** [comment]
Neat idea.

**Comment by Manishearth** [comment]
Relevant code: https://github.com/rust-lang/rust/blob/master/src/doc/book/the-stack-and-the-heap.md

**Comment by steveklabnik** [comment]
Update: there has been some work done here, but there could be more.

**Comment by steveklabnik** [comment]
I am going to give this one a close, as I'm not going to be working on this chapter of the book anymore.

If someone wants to make this look more colorful, please be my guest!
