### ISSUE TITLE
c_char has changed on ARM in 1.6 

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#29867]
Android was changed in [#29546](https://github.com/rust-lang/rust/pull/29546/files#diff-c4f9e907b21efdcec1a2c091ff9ee641R15) and Linux ARM was changed in https://github.com/rust-lang/rust/pull/29775. Both are bug fixes as the definitions have been corrected, but this is causing breakage:

* https://github.com/rust-lang/rust/pull/29775#issuecomment-157083714
* https://github.com/carllerche/curl-rust/issues/89
* https://github.com/jeaye/ncurses-rs/issues/99
* https://github.com/rust-lang/cargo/issues/2141

Can we help mitigate this breakage? Should we revert "the fix" for now? 

Opening a tracking issue (and nominating it) to discuss this.

**Comment by alexcrichton** [comment]
Some other points:

* Updating to libc 0.2 and using Rust nightly should not cause errors to show up
* ARM is not a tier 1 platform right now, but it's kinda close to one
* libc 0.1 is no longer compatible with nightly std on ARM (due to this and `CString`)
* libc 0.2 is not compatible with Rust 1.5 and prior (due to this and `CString`)

**Comment by arcnmx** [comment]
Note that #29775 only changed `raw::os::c_char`, which probably no one seemed to be using at all (and has been mismatched with libc on Android for months apparently). ARM Linux was also broken in #29546 since the main observable problem was with the type `CStr::as_ptr` returned.

It sucks. My solution has been to pin specific versions via hacking on Cargo.lock. I'm not sure that reverting back to the wrong type is the right course of action to take, though.

**Comment by SimonSapin** [comment]
Should library use types from `std::os::raw` when they exist instead of libc? (Maybe depending on whether or not they need other things from libc?) Should rust-bindgen be changed to use `std::os::raw` for types that exist there?

**Comment by alexcrichton** [comment]
That's a good question! I don't think it should matter as the types should in theory always be the same.

**Comment by arcnmx** [comment]
I think they should, tbh. In theory they should be the same, but if you plan on using std methods, you should be using the types it exports, and not assuming some external crates.io crate matches up.

**Comment by SimonSapin** [comment]
CC @larsbergstrom

**Comment by bluss** [comment]
Can we reorganize this somehow so that we use a *single source of truth*? Defining `c_char` in libstd, in-tree liblibc and crates.io liblibc is in two places too many right.

**Comment by alexcrichton** [comment]
The libs team discussed this during triage yesterday and the conclusion was that we're unlikely to go back to the old incorrect definitions and otherwise we'll basically just do what we can to help mitigate this breakage.

@bluss that's possible, yeah, although it wouldn't have fixed this problem because the "single source of truth" from before was wrong (both libstd and libc disagreed).

**Comment by SimonSapin** [comment]
I hope that updating all the things (https://github.com/servo/servo/issues/8608) to libc 0.2 will fix the build errors related to this for Servo.

**Comment by bluss** [comment]
@alexcrichton But the major fallout comes from incompatible types, not from the change per se? If all the crates used `c_char` reexported from libstd, and I think you can't compile against more than one version of libstd, they'd all be using the same type.

**Comment by alexcrichton** [comment]
Yeah that's true and it would help mitigate problems like this. There's a number of interesting issues around libc reexporting types from the standard library, however, so it's currently not done.

**Comment by cuviper** [comment]
@bluss but libc is the source of `c_char` for libstd, so the problem comes when your external libc crate doesn't match the one built into libstd.

Maybe the libc crate should use a cfg feature for this?  Set that feature to provide its own good `c_char` when used within libstd, else just reexport `std::os::raw::c_char`.  This way external use always agrees with libstd.

**Comment by petevine** [comment]
https://github.com/alexcrichton/filetime/issues/4

**Comment by petevine** [comment]
https://github.com/hannobraun/inotify-rs/pull/33

**Comment by petevine** [comment]
Even `aarch64` is affected to this very day.
