### ISSUE TITLE
translating statics/consts segfaults LLVM if order is wrong

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#29884]
This test case (a permutation of `const-autoderef.rs`) causes rustc to segfault (somewhere in LLVM):

``` rust
static B: u8 = (&A)[0];
static A: [u8; 1] = ['h' as u8];
static D: u8 = (&C)[0];
static C: &'static &'static &'static &'static [u8; 1] = & & & &A;

pub fn main() {
    assert_eq!(B, A[0]);
    assert_eq!(D, A[0]);
}
```

Uncovered while working on separating items from HIR, since the new visitors can sometimes visit items in different orders (unless you force them to do otherwise).

**Comment by nikomatsakis** [comment]
I believe the cause of this is https://github.com/rust-lang/rust/pull/26630.

**Comment by nikomatsakis** [comment]
cc @eefriedman -- this is triggered by recursive statics (see also some notes on #29719, if you haven't already)

**Comment by arielb1** [comment]
duplicate of #28324

**Comment by nikomatsakis** [comment]
@arielb1 ah, yes, I remember this issue. And there is a legit question also of whether we should support the kind of derefs etc that are evident here vs having people create intermediate statics. I personally am not terribly fond of that, since the value of a static is not necessarily fixed over the course of an execution.

**Comment by arielb1** [comment]
@nagisa 

The issue is known - we are attempting to dereference a static that is not defined.

**Comment by eefriedman** [comment]
This is fixed.

**Comment by nikomatsakis** [comment]
The original test case, indeed, does not seem to compile.

**Comment by nagisa** [comment]
Shouldn’t we add a regression test or something?

**Comment by nikomatsakis** [comment]
@nagisa I was thinking that the test for #28324 (I presume there is one...) sufficed.

**Comment by nagisa** [comment]
Ah hmm. Okay nevermind then.
