### ISSUE TITLE
Doc & test update after change in eh_unwind_resume signature

### ISSUE THREAD

**Issue by tytouf** [rust-lang/rust#29898]
When building a bare metal application with the nightly version of rustc 1.6.0-dev (3042fedb4 2015-11-16) I get an assert in LLVM:

```
rustc: /home/caugier/ws/rust/src/llvm/lib/IR/Instructions.cpp:234: void llvm::CallInst::init(llvm::FunctionType*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, const llvm::Twine&): Assertion `(Args.size() == FTy->getNumParams() || (FTy->isVarArg() && Args.size() > FTy->getNumParams())) && "Calling a function with bad signature!"' failed.
```

After investigating a bit it seems the issue comes after a change in eh_unwind_resume signature from () to (*mut u8).

Doc needs to updated for sure, but I found that some tests are using it as well.

A validation of the signature would also help people when migrating by providing a specific error message.

**Comment by Ticki** [comment]
Can confirm. This is still an error.

**Comment by lilred** [comment]
Ran into the same issue.

**Comment by steveklabnik** [comment]
Which documentation is incorrect here?

**Comment by lilred** [comment]
1. The error message is non-obvious
2. The signature of `eh_unwind_resume` is not documented anywhere. When it changed, stuff stopped compiling overnight, and it was really hard to figure out why :|

**Comment by steveklabnik** [comment]
related: https://github.com/rust-lang/rust/issues/33677

**Comment by frewsxcv** [comment]
There's some documentation here now: https://doc.rust-lang.org/nightly/unstable-book/language-features/lang-items.html

Does this need to be expanded further?

**Comment by Mark-Simulacrum** [comment]
I think that page is sufficient. I'm going to close this, in favor of more targeted issues being filed as users encounter problems.
