### ISSUE TITLE
Doc example does not compile in section 3.3. Rust Inside Other Languages

### ISSUE THREAD

**Issue by nooninm** [rust-lang/rust#29895]
The books says "Try running this example ...".  I pasted the code below, verbatim.  It does not compile.  I put it in a "fn main()" block, but it still did not compile.

```
threads = []

10.times do
  threads << Thread.new do
    count = 0

    5_000_000.times do
      count += 1
    end

    count
  end
end

threads.each do |t|
  puts "Thread finished with count=#{t.value}"
end
puts "done!"
```

-------------- paste error output
src\main.rs:1:1: 1:8 error: expected item, found `threads`
src\main.rs:1 threads = []
              ^~~~~~~

**Comment by steveklabnik** [comment]
Hey @nooninm !

So, this is actually Ruby code, not Rust. Right before, it says:

> Here’s an example of this code in Ruby:

Is there some way we could maybe make this more clear, somehow?

**Comment by nooninm** [comment]
>Is there some way
No, I see that Ruby is already stated in several places.
Thanks

**Comment by steveklabnik** [comment]
Okay!
