### ISSUE TITLE
install script incomplete for non-sudo installation into $HOME/.local

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [rust-lang/rust#29905]
its common to install software into ´~/.local´ when superuser access is not availiable, however after installation rustc complains about missing shared libs instead of executing

a simple workaround seems to be to add ´~/.local/lib´ to the ´LD_LIBRARY_PATH´ env var´
printing a message to help with that seems sensible

**Comment by sanxiyn** [comment]
Note that [multirust](https://github.com/brson/multirust) handles this automatically (LD_LIBRARY_PATH is added in a shell script wrapper).

**Comment by steveklabnik** [comment]
Should this bug be filed against https://github.com/rust-lang/rustup instead?

**Comment by RonnyPfannschmidt** [comment]
seems like it, does github haveany way to move issues between projects ?

**Comment by brson** [comment]
http://github.com/rust-lang/rust-installer is probably the more appropriate place. It is a conscious decesion not to deal with LD_LIBRARY_PATH for non-system installations. I don't know how to do it consistently and reliably.

rust-installer should print a message in these cases suggesting the user deal with LD_LIBRARY_PATH. I believe it used to, but that may have been removed at some point.

**Comment by steveklabnik** [comment]
Closing, as this should be re-filed. @RonnyPfannschmidt if you still care about this, please do.
