### ISSUE TITLE
Default impls don't substitute type parameters properly in rustdoc

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#29909]
For example, on http://doc.rust-lang.org/nightly/std/primitive.slice.html, we have

``` rust
impl<T> Repr<Slice<T>> for [T]
fn repr(&self) -> T
```

however it should actually be

``` rust
impl<T> Repr<Slice<T>> for [T]
fn repr(&self) -> Option<T>
```

since `Repr` is

``` rust
pub trait Repr<T> {
    fn repr() -> T { ... }
}
```

Out of tree example:

``` rust
pub trait Repr<T> {
   fn repr() -> T {unimplemented!()}
}
pub struct Foo;
impl<T> Repr<Option<T>> for Foo {}
```

It doesn't even need the type parameter:

``` rust
pub trait Repr<T> {
   fn repr() -> T {unimplemented!()}
}
pub struct Foo;
impl Repr<u8> for Foo {}
```

Looks like rustdoc is picking up the signature from the default impl.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/14072 which has more information and discussion.
