### ISSUE TITLE
Possible redundancy in the Rust Book

### ISSUE THREAD

**Issue by crossroads1112** [rust-lang/rust#29915]
In the guessing game example, the reader is instructed to read a line from `stdin` like so:

    let mut guess = String::new();
    
    io::stdin().read_line(&mut guess)
        .ok()
        .expect("Failed to read line");

Is there a reason to convert the `io::Result` into an `Option` and then call `expect()`? As I understand it, `Result`s have an `expect` method too which would accomplish the same thing here e.g.

    let mut guess = String::new();
    
    io::stdin().read_line(&mut gues)
        .expect("Failed to read line");

**Comment by sfackler** [comment]
That's a hold over from before `Result`'s version of `expect` was stable. I think the docs may have since been fixed? cc @steveklabnik

**Comment by crossroads1112** [comment]
Ah, sorry I was unaware
