### ISSUE TITLE
MinGW's `env::vars_os` and `env::var_os` disagree

### ISSUE THREAD

**Issue by tbu-** [rust-lang/rust#29911]
See also #29910, https://github.com/rust-lang/rust/pull/29297#issuecomment-157539813 and the relevant test file `src/test/run-pass/env-vars.rs`: [permanent link](https://github.com/rust-lang/rust/blob/28f6b8897845f4590c50757b30766fb792d2cdb7/src/test/run-pass/env-vars.rs), [current version](https://github.com/rust-lang/rust/blob/master/src/test/run-pass/env-vars.rs).

**Comment by tbu-** [comment]
I guess with #29297 merged this could be closed?

**Comment by alexcrichton** [comment]
I think so, yeah, thanks @tbu-!
