### ISSUE TITLE
CString::from_vec_unchecked may not need to be `unsafe`

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#29918]
It's not obvious if one can cause memory unsafety with [this function](https://doc.rust-lang.org/nightly/std/ffi/struct.CString.html#method.from_vec_unchecked): when would an interior null be problematic?

Pointed out by @wthrowe in https://github.com/rust-lang/rfcs/pull/1323#issuecomment-157521663.

**Comment by bluss** [comment]
The question is if we want to drop the invariant that CString is guarding (no interior nulls). thestinger claimed this would cause security bugs. It's certainly in the category of problem prevention rather than direct memory safety.

**Comment by alexcrichton** [comment]
The libs team discussed this during triage yesterday and the conclusion was that it is a static contract of the `CString` type that there are no interior nul bytes. It is considered suitable for types which provide these sorts of static contracts to use `unsafe` for methods that may violate this, so this fits within the conventions of the standard library.
