### ISSUE TITLE
Broken link in the compiler plugin documentation

### ISSUE THREAD

**Issue by SeanHeelan** [rust-lang/rust#29912]
In the Lint Plugins section of https://doc.rust-lang.org/book/compiler-plugins.html the LintPass link (in the phrase "a LintPass implementation defining ") is to https://doc.rust-lang.org/rustc/lint/trait.LintPass.html, which is apparently not a valid destination.

**Comment by steveklabnik** [comment]
Thanks sean! However, this is a duplicate of https://github.com/rust-lang/rust/issues/29893, actually. So I'm going to give it a close.
