### ISSUE TITLE
std::str::FromStr should mention it gets used in str::parse

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#29919]
On the surface, the `FromStr` seems like a pretty pointless trait, but it should maybe mention it gets used in `str::parse` so it seems slightly less pointless

https://doc.rust-lang.org/nightly/std/str/trait.FromStr.html

**Comment by sfackler** [comment]
:+1:

**Comment by steveklabnik** [comment]
part of https://github.com/rust-lang/rust/issues/29375

**Comment by devonhollowood** [comment]
I can do this.
