### ISSUE TITLE
reference: section "Behavior considered undefined" is not clear

### ISSUE THREAD

**Issue by tshepang** [rust-lang/rust#29936]
We have this paragraph ([source](:
https://doc.rust-lang.org/reference.html#behavior-considered-undefined)

> The following is a list of behavior which is forbidden in all Rust code, including within unsafe blocks and unsafe functions. Type checking provides the guarantee that these issues are never caused by safe code.

First sentence (these issues are not possible in Rust) seem to conflict with the second one (these issues are not possible in _safe_ Rust).

**Comment by durka** [comment]
It says **forbidden** in Rust, not **impossible**. In safe code, the compiler checks. In unsafe code, you are still not allowed to do these things but the compiler cannot watch your back.

**Comment by tshepang** [comment]
What is the difference between *forbidden* and *impossible*?

**Comment by durka** [comment]
The difference is who is at fault. If you find a way to cause undefined behavior in purely safe code, you file a bug here. If you cause undefined behavior using unsafe code, that's your fault.

**Comment by tshepang** [comment]
Still not clear. Perhaps an example?

**Comment by durka** [comment]
This code compiles:

```rust
let x: *const i32 = 0 as *const i32;
unsafe { let y = *x; }
````

It crashes when I run it, but the behavior is undefined (per the reference) so it may do something else like [make demons fly out of your nose](http://catb.org/jargon/html/N/nasal-demons.html). This program is incorrect because it causes undefined behavior.

This code does not compile:

```rust
let x: *const i32 = 0 as *const i32;
let y = *x;
```

I didn't say the magic word `unsafe`, so the compiler prevents me from doing things that could cause undefined behavior (in this case, dereferencing a raw pointer).

**Comment by arielb1** [comment]
@tshepang 

It is definitely *possible*, and probably very easy, for you to drive while drunk. It is even possible that you do it and not be hurt in any way. However, doing that is *forbidden* - if a cop catches you in the act, you will be facing penalties - and, even if you don't get caught, it is still very dangerous - you could hit something. LLVM UB is similar: you may get away with it, but LLVM can catch you and erase your code, and even if it does not you could overwrite your return address and be 0wned. 

Here "safe Rust" is not having access to alcohol - it prevents you from driving drunk. The analogy is somewhat stronger than that: someone with access to alcohol (misbehaving unsafe code) could give it to you (safe code) and you could drink it and drive.

**Comment by tshepang** [comment]
It looks what you mean is that *forbidden* means the code may compile, but may fail at run-time (e.g. Segmentation fault). Is that so?

**Comment by durka** [comment]
It might do what you expected, it might do something else, it might crash with a segmentation fault, etc. It's undefined.

**Comment by durka** [comment]
To put it another way, causing undefined behavior is not allowed. There are two ways to evade the Undefined Behavior Police:

1. Use safe code.
2. Use unsafe code and be very careful.

**Comment by tshepang** [comment]
Then *forbidden* is a bad word. I thought it meant *does not compile*. Instead, you are saying that it means *undefined behavior*.

**Comment by durka** [comment]
What if the first sentence

> The following is a list of behavior which is forbidden in all Rust code, including within `unsafe` blocks and `unsafe` functions.

were replaced by

> Rust code (including within `unsafe` blocks and `unsafe` functions) is incorrect if it exhibits any of the behaviors in the following list.

Is that any better?

**Comment by tshepang** [comment]
much better, though it appears more accurate to just use the word *undefined*

**Comment by durka** [comment]
Given that "undefined" confused you (and I imagine others) in the first place, it seems like a good idea to use some synonyms :)

**Comment by tshepang** [comment]
The word that tripped me is *forbidden*; *undefined* is clear enough... sorry for not making that clear enough.

**Comment by durka** [comment]
Though I think it's important to precisely define _undefined_ as well. At least when I learned C++ I was confused for a while as to what it means. i.e. it does *not* mean implementation-defined, it means actually-not-allowed-and-the-optimizer-is-free-to-assume-it-never-happens.

**Comment by steveklabnik** [comment]
The reference is now in its own repo, I have moved this to https://github.com/rust-lang-nursery/reference/issues/19

**Comment by tshepang** [comment]
thanks @steveklabnik
