### ISSUE TITLE
Is drop() working correctly in this scenario?

### ISSUE THREAD

**Issue by sga001** [rust-lang/rust#29940]
Hello. I was experimenting with RwLock to see if and how I could upgrade/downgrade a lock. I ended up converging on something similar to the following code: 

    use std::sync::RwLock;

    struct Foo {
        a: Vec<u8>,
    }

    fn main() {
        let lock = RwLock::new(Foo{ a: vec![1, 2, 3] });
        let mut x = lock.read().unwrap();
    
        let a_ptr = &x.a;
    
        if a_ptr.len() > 1 {
           drop(a_ptr);
           drop(x);
           let mut y = lock.write().unwrap();
           y.a[0] = 3;
           drop(y);
           x = lock.read().unwrap();
       }
 
       println!("{:?}", x.a);
    }

My expectation was that drop(a_ptr) would allow me to then call drop(x). This would then release the read lock and the call to lock.write() would not result in deadlock. However, this is not the case. I get the error: 

    error: cannot move out of `x` because it is borrowed
         drop(x);
    note: borrow of `x` occurs here
        let a_ptr = &x.a;

Am I misunderstanding how drop works? or is this a bug?

**Comment by steveklabnik** [comment]
`drop` does not actually change the lifetimes, just calls destructors.
