### ISSUE TITLE
Deref coercion does not occur when attempting to satisfy trait bounds

### ISSUE THREAD

**Issue by sgrif** [rust-lang/rust#29959]
This seems like something the compiler should definitely be able to handle. Example here: http://is.gd/9h7Isd

**Comment by apasel422** [comment]
Deref coercions don't occur in generic contexts. See https://www.reddit.com/r/rust/comments/3qu3xr/why_cant_i_get_a_deref_coercion_to_a_slice/ for a similar issue and some explanation.

**Comment by sgrif** [comment]
While I think that argument makes sense for Vec, certainly one would expect `&[T; 2]` to coerce to `&[T]`.

**Comment by apasel422** [comment]
[RFC 401 specifically calls this out](https://github.com/rust-lang/rfcs/blob/master/text/0401-coercions.md#coercions):

> Note that we do not perform coercions when matching traits (except for receivers, see below). If there is an impl for some type `U`, and `T` coerces to `U`, that does not constitute an implementation for `T`.

**Comment by sgrif** [comment]
Fair enough. Thanks for clarifying
