### ISSUE TITLE
Implement conversion from Box to Rc / Arc.

### ISSUE THREAD

**Issue by Ms2ger** [rust-lang/rust#29953]
Initially proposed in #29580.

**Comment by Ms2ger** [comment]
Though the implementation there wasn't too interesting; it would be more useful to have an implementation that works on unsized types/

**Comment by apasel422** [comment]
How would this work? The backing storage for `Arc<T>` and `Rc<T>` is two `usize`s bigger than that of `Box<T>`. Or would this not be a "free" conversion?

**Comment by Ms2ger** [comment]
I guess it would need to reallocate, yes.

**Comment by alexcrichton** [comment]
I think that this issue is more appropriate in rust-lang/rfcs (e.g. feature requests), could you move over there instead?

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/40475.

**Comment by snuk182** [comment]
Doesn't https://github.com/rust-lang/rust/issues/40475 cover the boxed *arrays* conversions only?

**Comment by Mark-Simulacrum** [comment]
From the RFC: `From<Box<T: ?Sized>> for Rc<T>` is to be added. I think that covers it?
