### ISSUE TITLE
Test time::tests::instant_math fails on Windows (GNU) with +/-1 error

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#29970]
Windows 8.1 64-bit / MSYS2 / MinGW-w64

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)` (left: `Instant { t: 3793243355088 }`, right: `Instant { t: 3793243355087 }`)', src/libstd\time/mod.rs:252
test time::tests::instant_math ... FAILED
```

cc @alexcrichton

**Comment by alexcrichton** [comment]
Interesting! This is testing the property that the duration between two instants plus the first is the same as the second. Unfortunately this isn't true on Windows due to the +/- one problem on multiple cores.

Have to think about what's the best course of action here.

**Comment by petrochenkov** [comment]
This still fails, btw

```
thread '<unnamed>' panicked at 'assertion failed: a - Duration::new(0, 1) <= b', src/libstd\time/mod.rs:262
```
