### ISSUE TITLE
compiler-rt fails to build on NetBSD

### ISSUE THREAD

**Issue by gandro** [rust-lang/rust#29977]
With the compiler-rt update in PR #29478, `gcc_personality_v0.c` now includes the `unwind.h` header to deduplicate some type definitions (commit: https://github.com/rust-lang/compiler-rt/commit/5f0c79f722b6d2f9368c43af2308596c4a9d0b56) . 

The `unwind.h` [header available in NetBSD](http://nxr.netbsd.org/xref/src/lib/libexecinfo/unwind.h?r=1.3) however does not provide all required definitions. Specifically, `_Unwind_Action` is absent in this header, leading to the following build failure:

```
.../rust/src/compiler-rt/lib/builtins/gcc_personality_v0.c:151:35: error: unknown type name '_Unwind_Action'
__gcc_personality_v0(int version, _Unwind_Action actions,
                                  ^
```

Side note: As far as I understand, NetBSD provides the above header only if the platform uses libgcc_eh (e.g. on amd64 using gcc, which is supported by Rust currently). Otherwise, LLVM's libunwind header is installed, which contains the required definitions.

I'm not sure how to fix this. Should Rust's compiler-rt duplicate the type definitions again?

**Comment by alexcrichton** [comment]
Ah this may have just been missed out in the compiler-rt update, it should be fine to basically pull in whatever the same fix was previously again.

**Comment by jakllsch** [comment]
The correct unwind.h is also available via the libunwind package from pkgsrc.  But that may or may not be a good solution.

**Comment by jakllsch** [comment]
Looked at this more.  https://nxr.netbsd.org/xref/src/lib/libc/compiler_rt/Makefile.inc?r=1.30#29 and https://nxr.netbsd.org/xref/src/share/mk/bsd.own.mk?r=1.938#127 shows that gcc_personality_v0.c is only used on EABI ARM machines, which rustc for NetBSD does not currently target.  I'll probably have a patch to address that just forces HAVE_UNWIND_H=OFF on NetBSD/non-ARM.

**Comment by alexcrichton** [comment]
I believe this is no longer being built, so closing.
