### ISSUE TITLE
False borrow checker error: cannot use `self.x` because it was mutably borrowed

### ISSUE THREAD

**Issue by istankovic** [rust-lang/rust#29975]
Currently the borrow checker emits errors for simple cases like
the following:

```
struct Foo {
    x: isize,
}

impl Foo {
    fn foo(&mut self) {
        self.bar(self.x);
    }

    fn bar(&mut self, v: isize) {
        self.x = v + 1;
    }
}

fn main() {
}
```

The above results in
```
foo.rs:7:18: 7:24 error: cannot use `self.x` because it was mutably borrowed [E0503]
foo.rs:7         self.bar(self.x);
                          ^~~~~~
foo.rs:7:9: 7:13 note: borrow of `*self` occurs here
foo.rs:7         self.bar(self.x);
                 ^~~~
error: aborting due to previous error
```

This is with `rustc 1.6.0-nightly (d5fde83ae 2015-11-12)`.
An ugly workaround for this is to make an explicit copy of ``self.x``, e.g.
```
    fn foo(&mut self) {
        let tmp = self.x;
        self.bar(tmp);
    }
```

**Comment by Manishearth** [comment]
Thanks for the bug report! This is being tracked at 
https://github.com/rust-lang/rfcs/issues/811, and probably will get fixed once the MIR work is done.

Previously: https://github.com/rust-lang/rust/issues/6268, https://github.com/rust-lang/rust/issues/20403
