### ISSUE TITLE
len() of some unicode characters is equal to 3.

### ISSUE THREAD

**Issue by honorabrutroll** [rust-lang/rust#29978]
As the title said, some Unicode characters are being counted as 3. Some of the characters that I've tested are Ṯ, █, and ẕ, but I'm sure that there are many more.

This was the code I used to test:
```rust
fn main() {
    println!("{}", "ẕ".len());
}
```

**Comment by sfackler** [comment]
As noted in the [documentation](https://doc.rust-lang.org/stable/std/primitive.str.html#method.len), the `len` method on a `str` returns the length in bytes. `str` values are UTF-8 encoded, and the graphemes you've pointed out are 3 bytes in that encoding.

**Comment by honorabrutroll** [comment]
Oh ok. Is there any function that will return the character length of a ```str```?

**Comment by sfackler** [comment]
The "character length" of a string is not a super well defined concept. [`"foo".chars().len()`](https://doc.rust-lang.org/stable/std/primitive.str.html#method.chars) will give you the number of Unicode codepoints in the string. However, this will probably not correspond to what you think of as characters. The `unicode-segmentation` crate provides [`"foo".graphemes().len()`](http://unicode-rs.github.io/unicode-segmentation/unicode_segmentation/trait.UnicodeSegmentation.html#tymethod.graphemes) which returns the number of [grapheme clusters](http://www.unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries) in the string.

**Comment by honorabrutroll** [comment]
Alright, thanks!

**Comment by pmarcelll** [comment]
It's actually ```"foo".chars().count()```, but I'm sure you would have figured it out.
