### ISSUE TITLE
Unexpected type returned from struct_tail

### ISSUE THREAD

**Issue by hban** [rust-lang/rust#29986]
I tried this code (I'm still learning the language, so snippet is probably nonsensical):

    use std::iter::Peekable;
    
    struct Foo {
        bar: i32
    }
    
    impl Foo {
        fn parse(iter: &Peekable<Iterator<Item=u8>>) {
        }
    }

I expected to see this happen: compile to pass or to print compilation errors.

Instead, this happened:

    error: internal compiler error: unexpected panic
    note: the compiler unexpectedly panicked. this is a bug.
    note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
    thread 'rustc' panicked at 'Unexpected type returned from struct_tail: core::option::Option<<core::iter::Iterator<Item=u8> + 'static as core::iter::Iterator>::Item> for ty=core::iter::Peekable<core::iter::Iterator<Item=u8> + 'static>', ../src/librustc_trans\trans\type_of.rs:385

Compiler doesn't crash if offending function is placed outside `impl` block.

## Meta

`rustc --version --verbose`:

    rustc 1.4.0 (8ab8581f6 2015-10-27)
    binary: rustc
    commit-hash: 8ab8581f6921bc7a8e3fa4defffd2814372dcb15
    commit-date: 2015-10-27
    host: x86_64-pc-windows-gnu
    release: 1.4.0

Backtrace:

       0:         0x653814fe - <unknown>
       1:         0x6537deb9 - <unknown>
       2:         0x6534571e - <unknown>
       3:         0x6534608b - <unknown>
       4:         0x6bf889dd - <unknown>
       5:         0x6bf9b3af - <unknown>
       6:         0x6c063b2d - <unknown>
       7:         0x6bf95814 - <unknown>
       8:         0x6bfc1d77 - <unknown>
       9:         0x6bfc3d96 - <unknown>
      10:         0x6bfbcf51 - <unknown>
      11:         0x6bfba70c - <unknown>
      12:         0x6bfc690d - <unknown>
      13:         0x61bd4766 - <unknown>
      14:         0x61bcf242 - <unknown>
      15:         0x61baab77 - <unknown>
      16:         0x61ba64d8 - <unknown>
      17:         0x61b82cf8 - <unknown>
      18:         0x61cf1e07 - <unknown>
      19:         0x61cef5f1 - <unknown>
      20:         0x61ceefe8 - <unknown>
      21:         0x65371643 - <unknown>
      22:         0x61cef183 - <unknown>
      23:         0x6538721d - <unknown>
      24:     0x7ffbac212d91 - <unknown>

**Comment by Ticki** [comment]
Assuming your crate type is `lib`, you should try to clean up the build. If you're using cargo, run `cargo clean`.

**Comment by jonas-schievink** [comment]
@Ticki Why would that help? [This playpen](http://is.gd/WyqpzK) also ICEs.

**Comment by Ticki** [comment]
In playpen, the error is not unexpected. Peekable<I> assumes that I is Sized (which traits are not). As such, you need to make your code generic. This compiles: http://is.gd/FFgiu0

**Comment by Ticki** [comment]
But this is clearly a bug. It should not ICE.

**Comment by arielb1** [comment]
This correctly warns on beta/nightly - this will soon be an error.

**Comment by hban** [comment]
This still panics on 1.5 and nightly.
