### ISSUE TITLE
Rust Compiler Error Index errors should be named.

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#29982]
Basically, we have `E0001 through E0444`, but as far as I can tell, these errors don't have names other than their index, which makes discussing them difficult. It'd be nice if these errors had names, and the names showed up in the error index. Possibly making the header being "ENNNN - Name".

**Comment by GuillaumeGomez** [comment]
It could be discussed. Let's put it in the docs team discussion.

**Comment by QuietMisdreavus** [comment]
We discussed this at the docs team meeting today, and couldn't reach a consensus on whether we wanted to expend the effort putting this together. If i remember right, errors are usually emitted with a summary line, so grabbing those and codifying them into the error index (if they aren't already) would get close to solving this.

**Comment by Havvy** [comment]
Since this is an enhancement that probably nobody is going to do anything about this in the near to medium term, I'm going to close it.
