### ISSUE TITLE
Book: Concurrency example is bad

### ISSUE THREAD

**Issue by karyon** [rust-lang/rust#29990]
Link: https://doc.rust-lang.org/stable/book/concurrency.html

To me, having an array with items to work on, then giving each thread an ID and let each work on the corresponding item is maybe error-prone but data race free when done correctly. In C/C++, a solution to prevent programmer errors would be to give each thread a reference to the one item it's supposed to work on, and i expected to see something like that as solution (not knowing rust enough, i don't know whether that's even possible). The proposed solution in the chapter looks really bad: It introduces synchronization on the whole array which is not necessary and just overhead.

Then there is no explanation given why any waiting is needed.

Lastly, as far as i understand the send/receive is used for simply joining the threads, which should be done by actually using join, not send/receive.

**Comment by apasel422** [comment]
I think a lot of this can change once `thread::scoped` is resurrected.

**Comment by steveklabnik** [comment]
Yes, an even better way is to use `crossbeam` or `scoped_threadpool`, but we don't discuss external crates in the docs.

I don't think that in just std alone, we can talk about more than this, so I don't think this can really be improved that much.

**Comment by steveklabnik** [comment]
This issue is not likely to be fixed. I'm working on a redux of the book, and so it will naturally be fixed then, but that means I'm not putting a lot of time into the existing draft.

Anyone who wants to improve this chapter of the book, please send PRs!
