### ISSUE TITLE
std::array's documentation mistakenly says it derefs to [T]

### ISSUE THREAD

**Issue by niconii** [rust-lang/rust#29993]
The doc page for [`std::array`](https://doc.rust-lang.org/nightly/std/primitive.array.html) says this:

> Arrays dereference to slices (`[T]`), so their methods can be called on arrays.

However, though this is true of `Vec<T>`, arrays in fact coerce via [`CoerceUnsized`](https://doc.rust-lang.org/std/ops/trait.CoerceUnsized.html), not via deref coercion.

**Comment by bluss** [comment]
It's compiler built in either way, not related to the Deref or CoerceUnsized traits.

**Comment by Gankro** [comment]
@nrc how would you describe the current situation

**Comment by nrc** [comment]
There is definitely no dereferencing going on, so "coerce" is more accurate. This uses the `Unsize` trait, not the `CoerceUnsized` one, but since all the impls of `Unsize` are magic, there is not much point in mentioning it. I'd just say the compiler coerces it and leave it at that.

**Comment by bluss** [comment]
and it's the same unsizing happening in both method resolution as with coercion?

**Comment by nrc** [comment]
@bluss  yes
