### ISSUE TITLE
Lifetime inference + Associated types limitation / bug?

### ISSUE THREAD

**Issue by frankmcsherry** [rust-lang/rust#30002]
I was able to write the following, and could imagine a world in which it works. At the same time, I could also imagine many good reasons that Rust can't reach a conclusion that I think I can reach. I floated it on IRC, where it was suggested to report it (and you all can figure out if it is a bug, a missing feature, or a wontfix).

The following hunk of code errors on playpen, with the concern that in calling `test`, Rust can't confirm that the associated type `<&'a String as Test<'a>>::Inner` lives long enough to be referenced by `&'b`. However, we see that in defining the trait `Test<'a>` there is a requirement that `Inner: 'a`, and in the `for<...>` construct we impose the requirement that `'a: 'b`. 

``` rust
trait Test<'a> {
    type Inner:'a;
}

impl<'a> Test<'a> for &'a String {
    type Inner = &'a String;
}

fn test<L>(func: L) where L : for<'b,'a:'b> Fn(&'b <&'a String as Test<'a>>::Inner) { }

fn main() {
    test(|x| println!("{:?}", x));
}
```

There could be any number of issues here, including total misunderstanding on my part. 

It seems that if I change the definition of `test` to remove the use of an associated type, as

``` rust
fn test<L>(func: L) where L : for<'b,'a:'b> Fn(&'b &'a String) { }
```

it works out just fine. Slightly disconcertingly for my understanding, I can also remove the `'a:'b` constraint, and no complaints. Maybe that's ok in this example?

If I change the definition of `test` to only have a single lifetime, as

``` rust
fn test<L>(func: L) where L : for<'a> Fn(&'a <&'a String as Test<'a>>::Inner) { }
```

It builds just fine (on nightly; stable has an ICE), but it also builds fine if I remove the `'a` requirement on `Inner` from the trait definition (I was really hoping that would error). Clearly I'm a bit confused about how things work.

Should the first version of the code have worked, or is there a glitch in sticking these bits of reasoning together?

**Comment by arielb1** [comment]
Lifetime bounds on associated types (`for<'a, 'b: 'a>`) indeed do nothing at all. OTOH, your code should have worked - an item's predicate well-formedness is supposed to be checked at the instantiation site.

**Comment by arielb1** [comment]
cc @nikomatsakis

**Comment by frankmcsherry** [comment]
Ah, ok. Is it right that it is resolved as "`for<'b,'a:'b>` doesn't do that (yet, maybe ever), so Rust can't infer what you want"? Happy to close if so, just didn't want it to be a "hrm, it should work".

**Comment by arielb1** [comment]
@frankmcsherry 

Thinking about this more: the `Inner: 'a` does indeed hold in our case. Some of our code is doing something stupid.

`for<'b, 'a:'b>` does nothing.

**Comment by nikomatsakis** [comment]
I'm surprised that `for<'b, 'a:'b>` parses, actually. I...don't think that was entirely intentional.

**Comment by nikomatsakis** [comment]
To be clear: not that it doesn't make sense and have value, just that we haven't implemented support for that sort of where clause.

**Comment by frankmcsherry** [comment]
It's all good. Happy to either close this as "working as intended" or leave it open as a "still possible to write something with surprising semantics" issue.

**Comment by steveklabnik** [comment]
Triage: years later, there's a different error:

```text
error: lifetime bounds cannot be used in this context
 --> src/main.rs:9:41
  |
9 | fn test<L>(func: L) where L : for<'b,'a:'b> Fn(&'b <&'a String as Test<'a>>::Inner) { }
  |                                         ^^

error: aborting due to previous error
```
