### ISSUE TITLE
Remove `#[staged_api]`

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#30008]
The only purpose this serves is to make stability attributes modal, distinguishing between in-tree and out-of-tree use cases. https://github.com/rust-lang/rust/pull/29952 though renamed `#[deprecated]` to `#[rustc_deprecated]`, so afaik `#[staged_api]` does nothing useful.

**Comment by brson** [comment]
Fixing this should be a matter of removing the code that checks it in stability.rs, following the leads to other fallout in the compiler, removing the attribute from all the crates it's attached to.

**Comment by petrochenkov** [comment]
Hm, what about `stable` and `unstable`? They are guarded by `#[staged_api]` as well.
