### ISSUE TITLE
Better error message when forgetting the right operand in an if condition

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rust#30035]
Hello.
The following code gives an error message that could be improved:

``` rust
fn main() {
    let n = 1;
    if 5 == {
        println!("five");
    }
}
```

It gives the following error:

```
src/main.rs:6:1: 6:2 error: expected `{`, found `}`
src/main.rs:6 }
              ^
src/main.rs:6:1: 6:2 help: place this code inside a block
```

This is because the compiler sees the right operand as a block expression, and is looking for the condition body, something like:

``` rust
fn main() {
    let n = 1;
    if 5 == {
        println!("five");
        5
    } {
        println!("Five");
    }
}
```

while we most probably mean to write something like:

``` rust
fn main() {
    let n = 1;
    if 5 == n {
        println!("five");
    }
}
```

So, it would be nice to improve this error message.

**Comment by nagisa** [comment]
This… would be pretty non-trivial to improve. What really bugs me is `help` being pretty useless, which for I’m going to fill another issue.

**Comment by estebank** [comment]
FWIW, the originally reported output was:

```
error: expected `{`, found `}`
 --> src/main.rs:8:1
  |
8 | }
  | ^
```
