### ISSUE TITLE
Implement `Default` for DefId

### ISSUE THREAD

**Issue by aochagavia** [rust-lang/rust#30039]
Would it make sense to do this? If so, I would be happy to provide a PR. I guess it would look like the code below:

    DefId {
        krate: 0,
        index: DefIndex::new(0)
    }

**Comment by apasel422** [comment]
Is this necessary for something in particular?

**Comment by petrochenkov** [comment]
@apasel422 
By accident, I needed this last week.
[Here](https://github.com/rust-lang/rust/blob/master/src/librustc/middle/privacy.rs#L58) you can see a manual implementation of `Default` for some map keyed with IDs. Why can't it be derived? Because of https://github.com/rust-lang/rust/issues/26925 in the first place, but also because `DefId` is not `Default`.

**Comment by Manishearth** [comment]
I don't think it makes sense to return bad defids. There's a reason it has to be manually derived, since it could have been a case where autoderiving returns an invalid struct with a bad defid.

**Comment by aochagavia** [comment]
I just needed to create dummy defids, so I wrote a `default_defid` function. Afterwards, I looked `DefId` up in the documentation to see if it implemented `Default`. Since it doesn't, I thought I could ask about it (instead of directly opening a PR). If it doesn't make sense, we can close this issue. I am happy with my `default_defid` function :smile:

**Comment by Manishearth** [comment]
> I just needed to create dummy defids,

But why? :smile: 

That shouldn't be necessary.

**Comment by aochagavia** [comment]
@Manishearth I am working on an [experimental refactoring tool](https://github.com/GSam/rust-refactor). The existing code was written by somebody else and he uses dummy defids in some places. I don't yet know if it is necessary, though. I guess I will discover it later on, when I have a better understanding of the code.

**Comment by Manishearth** [comment]
Ah, cool. Makes sense. As far as rustc goes we shouldn't be using dummy defids, and outside of rustc also it may not always be the best path.

**Comment by Manishearth** [comment]
(Closing, unless anyone feels that there's a need for this in the compiler)
