### ISSUE TITLE
“help: place this code inside a block” is… pretty confusing

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#30037]
```
fn main() {
    let n = 1;
    if 5 == {
        println!("five");
    }
}
```

reports

```
<anon>:6:1: 6:2 error: expected `{`, found `}`
<anon>:6 }
         ^
<anon>:6:1: 6:2 help: place this code inside a block
```

The help message is pretty confusing. Which code it has in mind? There’s no code which you could place into a block to fix this error either, as far as I can see.

**Comment by antoyo** [comment]
This help message makes sense with the following code:

```rust
fn main() {
    let n = 1;
    if n == 5
        println!("five");
}
```

because it needs curly braces for the body of the condition.

**Comment by Aatch** [comment]
One possible fix could be to attempt to parse an expression and only show the help message if it succeeded. So since `}` is not a valid expression, it won't work work. This would catch the case we want to, demonstrated by @antoyo, while hopefully avoiding the useless help message.

**Comment by estebank** [comment]
This ticket can be closed, given:

```rust
fn main() {
    let n = 1;
    if 5 == 1
        println!("five");
}
fn foo() {
    let n = 1;
    if 5 == {
        println!("five");
    }
}
```

[Diagnostics](https://is.gd/ro9l7Y):

```rust
error: expected `{`, found `println`
 --> <anon>:4:9
  |
4 |         println!("five");
  |         ^^^^^^^
  |
help: try placing this code inside a block
  |         { println!("five") }

error: expected `{`, found `}`
  --> <anon>:11:1
   |
11 | }
   | ^
```

CC @jonathandturner

**Comment by jonathandturner** [comment]
Definitely a bit better.

**Comment by antoyo** [comment]
Well, it does not seem to fix the issue in the first post.
It is the same error message, isn't it?

**Comment by jonathandturner** [comment]
@antoyo - this one shows the code to put in the block

**Comment by antoyo** [comment]
What I meant is that the error from the first post:
>```rust
>fn main() {
>    let n = 1;
>    if 5 == {
>        println!("five");
>    }
>}
>```
>reports
>```
><anon>:6:1: 6:2 error: expected `{`, found `}`
><anon>:6 }
>         ^
><anon>:6:1: 6:2 help: place this code inside a block
>```
does not seem to have changed:
>```
>error: expected `{`, found `}`
>  --> <anon>:11:1
>    |
>11 | }
>    | ^
>```

**Comment by jonathandturner** [comment]
@antoyo - that part of the error is still correct, but there's an additional part now which gives more information:

```
error: expected `{`, found `println`
 --> <anon>:4:9
  |
4 |         println!("five");
  |         ^^^^^^^
  |
help: try placing this code inside a block
  |         { println!("five") }
```

**Comment by antoyo** [comment]
My understanding is that this error message is for the code in the second post:
```rust
fn main() {
    let n = 1;
    if n == 5
        println!("five");
}
```
But the code from the first post still gives the same error, right?

**Comment by estebank** [comment]
@antoyo #30035 is still open, this [was a follow up](https://github.com/rust-lang/rust/issues/30035#issuecomment-159402730) only about the `help: place this code inside a block` message not being relevant.
