### ISSUE TITLE
error: internal compiler error: ty_is_local invoked on unexpected type: [type error]

### ISSUE THREAD

**Issue by crossroads1112** [rust-lang/rust#30042]
I was compiling the gtk crate and encountered the error in the title of this bug report. Here is the back trace

    
       1:     0x7f915aa320e0 - sys::backtrace::tracing::imp::write::h61025b053ecf325ekFt
       2:     0x7f915aa38a35 - panicking::log_panic::_<closure>::closure.40427
       3:     0x7f915aa384a5 - panicking::log_panic::h810f264853a4355ftrx
       4:     0x7f915a9fb6f3 - sys_common::unwind::begin_unwind_inner::hbd407a4b3e46ffb2pys
       5:     0x7f915489da07 - sys_common::unwind::begin_unwind::begin_unwind::h12778516175749217386
       6:     0x7f915489e826 - diagnostic::_<impl>::bug::hb5bf367b4ae38077KNB
       7:     0x7f9158741633 - session::_<impl>::bug::h35c7c1a9611fe060nXw
       8:     0x7f9158967196 - middle::traits::coherence::ty_is_local_constructor::hf869039458cab4a8VYR
       9:     0x7f915896642b - middle::traits::coherence::ty_is_local::heb13453b810d6546FXR
      10:     0x7f9158964299 - middle::traits::coherence::orphan_check_trait_ref::h21b00b2055e551f5jOR
      11:     0x7f915898b602 - middle::traits::select::_<impl>::candidate_from_obligation::haf2db6577927fd27LmW
      12:     0x7f91589937ec - middle::traits::select::_<impl>::evaluate_stack::h2150b848210ebd9c5bW
      13:     0x7f915899282e - middle::traits::select::_<impl>::evaluate_predicate_recursively::hb315c88a027ac28772V
      14:     0x7f9158993b25 - middle::traits::select::_<impl>::evaluate_candidate::_<closure>::closure.98945
      15:     0x7f915899386e - middle::traits::select::_<impl>::evaluate_stack::h2150b848210ebd9c5bW
      16:     0x7f915899282e - middle::traits::select::_<impl>::evaluate_predicate_recursively::hb315c88a027ac28772V
      17:     0x7f915895ff5b - middle::traits::coherence::overlap::h33051cc59e12f843XvR
      18:     0x7f915895f80c - middle::traits::coherence::overlapping_impls::h0f5e1b61c58f6e2eXtR
      19:     0x7f91596f6115 - coherence::overlap::_<impl>::check_if_impls_overlap::hbf11512eeaa20fb3C0A
      20:     0x7f915970424c - coherence::check_coherence::h76005ebf75431f08uXB
      21:     0x7f915970f652 - check_crate::h3b3fa7fbf1a21c08zsD
      22:     0x7f915af0b018 - driver::phase_3_run_analysis_passes::_<closure>::closure.22319
      23:     0x7f915aeeeb83 - middle::ty::context::_<impl>::create_and_enter::create_and_enter::h6140370089204457743
      24:     0x7f915aee9f3b - driver::phase_3_run_analysis_passes::h17099906288982987434
      25:     0x7f915aeca072 - driver::compile_input::hb8ee5cd1170b8c93cca
      26:     0x7f915b02bf6b - run_compiler::h55a157f2ab9ee307lvc
      27:     0x7f915b028fe6 - sys_common::unwind::try::try_fn::try_fn::h4463948223350095985
      28:     0x7f915aa2fe08 - __rust_try
      29:     0x7f915aa23d2b - sys_common::unwind::try::inner_try::h64c4d3f64d9a7839Xus
      30:     0x7f915b029334 - boxed::_<impl>::call_box::call_box::h12513187165841813857
      31:     0x7f915aa374c3 - sys::thread::_<impl>::new::thread_start::he22739286253a60feNw
      32:     0x7f91540f14a3 - start_thread
      33:     0x7f915a6c013c - clone
      34:                0x0 - <unknown>

**Comment by jonas-schievink** [comment]
#29857

**Comment by crossroads1112** [comment]
My fault. Didn't realize this was already reported.
