### ISSUE TITLE
fs::metadata - Value too large for defined data type

### ISSUE THREAD

**Issue by szagi3891** [rust-lang/rust#30050]
When i try get info abouth file with function : .metadata()
https://doc.rust-lang.org/std/fs/struct.DirEntry.html#method.metadata

I get an error:
{ repr: Os { code: 75, message: "Value too large for defined data type" } }

This file is in the directory is the size : 17848195008 byte.

**Comment by sfackler** [comment]
What OS are you on?

**Comment by szagi3891** [comment]
My platform : x86, linux (debian 8)

**Comment by alexcrichton** [comment]
Yeah it looks like you're trying to open a 17GB+ file in a 32-bit binary but we currently aren't using [the LFS functions](https://github.com/rust-lang-nursery/libc/pull/23) which allow opening files larger than 4GB on 32-bit Linux platforms.

I think this should be a pretty easy change to make, just gotta tweak some structs here and ther!

**Comment by alexcrichton** [comment]
triage: I-nominated

Seems like a good thing to categorize on behalf of the libs team though. This will have ramifications on the `std::os` module (e.g. the `stat` structure exposed) which may be good to discuss.

**Comment by cuviper** [comment]
This discussion was just rekindled on the [internals LFS thread](https://internals.rust-lang.org/t/pre-rfc-rust-and-large-file-support-lfs/2777) too.

I'd like to take this on, if no one else is already doing it.

**Comment by alexcrichton** [comment]
@cuviper feel free!

**Comment by cuviper** [comment]
Just a small update, I did get a little time to work on this over the holiday, but it's not pull-worthy yet.  There's some overlap with #30175 though in fixing up `dirent`, where LFS wants `dirent64`, so I think it will make sense for me to wait for that to merge and then build on top.

**Comment by alexcrichton** [comment]
We talked about this in the libs triage meeting yesterday, and the conclusion was that I'll draft up an RFC to write about this as it'll have ramifications on `std::os::raw`

**Comment by alexcrichton** [comment]
I've now [opened an RFC](https://github.com/rust-lang/rfcs/pull/1415) which I hope will help enable us to fix this issue in a "backwards-compatible" fashion
