### ISSUE TITLE
Make some of the ast_util functions into methods

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#30058]
https://github.com/rust-lang/rust/blob/master/src/libsyntax/ast_util.rs

Things like 

```
pub fn stmt_id(s: &Stmt) -> Option<NodeId>
```

should instead be

```
impl Stmt {
    pub fn id(s: &Stmt) -> Option<NodeId> {..}
}
```

The same goes for many other functions that take their first argument as an AST type (BinOp, Stmt, IntTy, Path, Ident, etc. Similarly, functions like [these](https://github.com/rust-lang/rust/blob/master/src/libsyntax/ast_util.rs#L239) could be `Generics::empty()` instead.

(Feel free to keep it in the same file or move it to ast.rs)

**Comment by faineance** [comment]
Is this up for grabs? I'd like to start contributing to Rust.

**Comment by faineance** [comment]
I presume I'd need to update all usage across the codebase.

**Comment by faineance** [comment]
I've just noticed a bunch of the extremely similar functions declared in [here](https://github.com/rust-lang/rust/blob/9303055f37a34adfceec1d1012b87308136295ce/src/librustc_front/util.rs#L84) what's up with that?

**Comment by jonas-schievink** [comment]
@faineance These are part of the [HIR](https://github.com/rust-lang/rfcs/blob/master/text/1191-hir.md), they should probably be made into methods as well

**Comment by faineance** [comment]
What do you think about refactoring them with traits?

**Comment by jonas-schievink** [comment]
I'd prefer plain methods, since that allows to change the HIR without changing the trait or AST - which is basically the point of the HIR. It would also have exactly 2 implementors - AST and HIR - and probably never gain more than that, which makes it a bit useless.

**Comment by faineance** [comment]
Good point, thanks.

**Comment by Manishearth** [comment]
Yes, this is up for grabs. Feel free to work on it!

The HIR and AST should stay separate as they will slowly diverge over time.

**Comment by Manishearth** [comment]
https://github.com/rust-lang/rust/pull/30105
