### ISSUE TITLE
Online documentation version switcher

### ISSUE THREAD

**Issue by Carreau** [rust-lang/rust#30062]
Hi, I'm astonished to not have found a similar issue, I apologize if it does exist but I didn't found it. I might have used the wrong terms. 

It would be convenient in the online docs to turn the `div#versioninfo` into a doc version switcher. 

`div#versioninfo` is this thing on the bottom right corner of documentations pages:
<img width="78" alt="screen shot 2015-11-25 at 23 01 02" src="https://cloud.githubusercontent.com/assets/335567/11410520/7221deea-93c8-11e5-8058-ec53f9f6ca6e.png">

At least a stable/nightly selector. I can imagine a switch between major versions later. It is not obvious for the newcomer what the URL scheme is. I just  tried a few before figuring out it was `nightly` and not `latest`.

You think might want also to set a `<link rel="canonical" href="http://doc.rust-lang.org/path/to/same/stable/page" />` to avoid google indexing the nightly too much, and also as the same page is available under `/foo.html` and `stable/foo.html`, that should (IIUC) de-duplicate search results and increase ranking.

I'm not too sure of where to fix that, and where are all the valid urls published on docs.rust-lang.org.

Thanks.

**Comment by steveklabnik** [comment]
I believe this is https://github.com/rust-lang/rust/issues/24336 and https://github.com/rust-lang/cargo/issues/1681 and also elements of https://github.com/rust-lang/rust/issues/14466

So yeah, nothing _exact_, but similar.

**Comment by kzys** [comment]
I'm working on #44687 currently. The demo site is http://rust-pull-request.s3-website-us-east-1.amazonaws.com/44687/std/

**Comment by jyn514** [comment]
I don't think this needs to be a general purpose rustdoc feature, since docs.rs already shows different versions and you'll only ever have one version available locally. I do think this would be nice to have for the standard library though - I think that could be written with existing rustdoc features using `--html-after-content` and some javascript:

```
        --html-after-content FILES
                        files to include inline between the content and
                        </body> of a rendered Markdown file or generated
                        documentation
```

**Comment by jyn514** [comment]
Mentoring instructions: First, write some JS that injects the right versions into the page, where the version number is now. Then, add it to the rust-lang/rust repo and add `--html-after-content your_file.js` here: https://github.com/rust-lang/rust/issues/30062#issuecomment-736116602
If that works well, we can figure out if and how to backport this to the existing documentation.

**Comment by ehuss** [comment]
@jyn514 I think one of the solutions currently being looked at is to use Lambda@Edge to inject a switcher on doc.rust-lang.org (see https://internals.rust-lang.org/t/adding-outdated-notices-to-archived-versions-of-documentation/12281/17 and #44687. This would allow switching for all pages (not just the std API).  There are various issues with a javascript-only approach that a server-side approach would work better (viewing docs locally, handling new releases, etc.).

**Comment by jyn514** [comment]
Should this be closed in favor of https://github.com/rust-lang/rust/issues/44687 then?

**Comment by ehuss** [comment]
I think so, since the RFC covers this.
