### ISSUE TITLE
Document the consequences of various PhantomData forms

### ISSUE THREAD

**Issue by vberger** [rust-lang/rust#30069]
To work around the ``parameter `T` is never used [E0392]`` error, one if often suggested to use [PhantomData](https://doc.rust-lang.org/nightly/std/marker/struct.PhantomData.html).

However, the documentation of PhantomData explains that various forms are possible, but is quite vague about the consequences of the choice of a form (and also only handles a small subset of the possible forms).

From my understanding given [this reddit thread I opened](https://www.reddit.com/r/rust/comments/3ta4ga/phantomdata_and_ownership/) these various forms can have different consequences (regarding dopck and/or lifetime variance ?):

- `PhantomData<T>`
- `PhantomData<&'a T>`
- `PhantomData<&'a mut T>`
- `PhantomData<*const T>`
- `PhantomData<*mut T>`
- `PhantomData<fn(T) -> ()>`
- `PhantomData<fn() -> T>`
- `PhantomData<fn(T) -> T>`

But I have no real idea about what using one or another changes.

**Comment by GuillaumeGomez** [comment]
cc @Manishearth
cc @steveklabnik

**Comment by Manishearth** [comment]
cc @Gankro

**Comment by vberger** [comment]
I had forgotten to check the rustonomicon, and [this page](https://doc.rust-lang.org/stable/nomicon/subtyping.html) seems relevant.

Could be worth explaining the relation of `PhantomData` with variance and add a link to it in the doc, maybe ?

**Comment by Gankro** [comment]
- `PhantomData<T>` - drop check, variant over T
- `PhantomData<&'a T>` - variant over 'a, variant over T
- `PhantomData<&'a mut T>` - variant over 'a, invariant over T
- `PhantomData<*const T>` - variant over T
- `PhantomData<*mut T>` - invariant over T
- `PhantomData<fn(T) -> ()>` - contravariant over T, assuming we keep that
- `PhantomData<fn() -> T>` - drop check, variant over T (a function that produces T from nothing is isomorphic to T)
- `PhantomData<fn(T) -> T>` - invariant over T?

The standard widget for "invariant over 'a" is `Cell<&'a ()>`.

**Comment by durka** [comment]
I wonder if there is already a crate that provides aliases to those various forms of PhantomData, appropriately named for a bit more self-documentation. If not I have a sudden desire to publish one :)

**Comment by Gankro** [comment]
I wouldn't recommend it -- it's what we used to have, but it was really confusing and no one could remember. The current system of "use what you semantically have" works a lot better.

**Comment by bluss** [comment]
According to the dropck rfc, `PhantomData<fn() -> T>` has no ownership = dropck implications.

**Comment by steveklabnik** [comment]
Yeah, so I'm not sure what the best way is to expand this. The first sentence is

> PhantomData<T> allows you to describe that a type acts as if it stores a value of type T, even though it does not.

Which does cover all of these forms. It's just that.

**Comment by Manishearth** [comment]
Yeah, but it doesn't explain why you would use it, or what features can be inherited from those types.

There's some dropck and variance stuff, but there's nowhere that people can go to to read about it.

**Comment by Gankro** [comment]
Well, [there's stuff in the nomicon](https://doc.rust-lang.org/stable/nomicon/phantom-data.html).

**Comment by Manishearth** [comment]
We should link to it from the phantomdata docs then

**Comment by Rufflewind** [comment]
It’d be nice if the nomicon had [Gankro’s neat table](https://github.com/rust-lang/rust/issues/30069#issuecomment-159928136) though!
