### ISSUE TITLE
Documentation for `cfg!` says it takes a single token tree

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#30073]
The documentation page for `cfg!` starts with this:

```rust
macro_rules! cfg { ($cfg:tt) => ({ /* compiler built-in */ }) }
```

In reality, `cfg!` accepts things like `feature = "bla"`, which isn't a single token tree.

**Comment by durka** [comment]
Should be `$cfg:meta` I guess, right?

**Comment by jonas-schievink** [comment]
I think so, yeah

**Comment by durka** [comment]
Source [here](http://doc.rust-lang.org/nightly/src/std/macros.rs.html#489). Looks like the doc for `include!` is also wrong, as it says `$cfg:tt` where it should probably have `$file:expr` same as `include_bytes!` above.
