### ISSUE TITLE
Can't define pub fn in child module if it uses a type defined in the parent module

### ISSUE THREAD

**Issue by 4xrsJCr9** [rust-lang/rust#30070]
```rust
mod parent {
    mod child {
        use super::Test;
        pub fn child_fn(test: Test) {
        }
    }
    struct Test(u32);
}
```
The above fails to compile on `rustc 1.6.0-nightly (2ba44607f 2015-11-22)` (Playground link: http://is.gd/kngh6n).

I want to be able to use `child_fn` from within the parent module. Since the child module and its types are completely private to the parent module, shouldn't this work?

**Comment by oli-obk** [comment]
duplicate of #27608

works as expected

**Comment by petrochenkov** [comment]
>Since the child module and its types are completely private to the parent module, shouldn't this work?

And then you add `pub use self::child::child_fn;` in the `parent` module and private `Test` leaks outside of `parent`. So, this is by design, yes.

**Comment by oli-obk** [comment]
The idea is that every module can be checked on its own, instead of having to check the entire crate.

**Comment by 4xrsJCr9** [comment]
@oli-obk: 
I should have found that issue; sorry for the duplication.

@petrochenkov: 
> And then you add `pub use self::child::child_fn;` in the `parent` module and private `Test` leaks outside of parent. So, this is by design, yes.

Perhaps the compiler should wait till I *actually* leak `Test` before it starts complaining. 

Having said that, I can appreciate how much the simpler/faster it would be to implement the design from the [RFC](https://github.com/rust-lang/rfcs/blob/master/text/0136-no-privates-in-public.md) linked to #27608. 

Thank you both for your replies.
