### ISSUE TITLE
Create impl_name! and fn_name! macros

### ISSUE THREAD

**Issue by malbarbo** [rust-lang/rust#30072]
The macros `file!`, `line!`, `column!` and `module_path!` provides information about the locations. To complete these would be great if there are `impl_name!`, `fn_name!` and `impl_fn_name!` macros.

The result of `impl_name!` for a default method would be the `Trait` name. Would be an error to call `impl_name!` in a function (that is, not a method).

Some initial tests

```rust
trait X {
    fn f(&self) {
        assert_eq!("X", impl_name!());
        assert_eq!("f", fn_name!());
        assert_eq!("X::f", impl_fn_name!());
    }
}

struct S;

impl X for S {
    fn f(&self) {
        assert_eq!("S", impl_name!());
        assert_eq!("f", fn_name!());
        assert_eq!("S::f", impl_fn_name!());
    }
}

impl S {
    fn g(&self) {
        assert_eq!("S", impl_name!())
        assert_eq!("g", fn_name!())
    }
}

fn f() {
    // impl_name!(); // do not compile
    assert_eq!("f", fn_name!())
}
```

**Comment by durka** [comment]
Adding macros to the standard library usually requires an RFC, I think.

**Comment by steveklabnik** [comment]
Yes, given that they come into scope for all programs, and can't really be made unstable, but instead go straight to stable, means that adding them is difficult.

**Comment by steveklabnik** [comment]
Triage: yes, this would require an RFC today. Please pursue one if this is important to you!
