### ISSUE TITLE
"0 elided lifetimes" is confusing

### ISSUE THREAD

**Issue by sanxiyn** [rust-lang/rust#30086]
```rust
fn a() -> &i32 {
    panic!();
}
fn b(x: i32) -> &i32 {
    panic!();
}
```

```
test.rs:1:11: 1:15 help: this function's return type contains a borrowed value,
but there is no value for it to be borrowed from
test.rs:4:17: 4:21 help: this function's return type contains a borrowed value,
but the signature does not say which one of `x`'s 0 elided lifetimes it is borrowed from
```

Help for `a` is reasonable, but help for `b` is not. See also #22760.

**Comment by arielb1** [comment]
@sanxiyn 

What would you prefer for an error message? Same as the previous one?

**Comment by sanxiyn** [comment]
Yes, same as the previous one would be an improvement.

**Comment by Manishearth** [comment]
Code: https://github.com/rust-lang/rust/blob/323781cdf700172a9b8fedf0614a995d4a4d81c0/src/librustc_typeck/astconv.rs#L199

The fix is basically to check for `n == 0` in any of the elision failure cases and then show the second warning unconditionally in such a case.
