### ISSUE TITLE
rust vs clang vs windows compatibility

### ISSUE THREAD

**Issue by nooninm** [rust-lang/rust#30099]
Is rust with clang going to have ongoing compatibility problems with current and future Windows OS versions?

It appears that the rust language uses clang, which as of 2015 no longer supports Windows XP or Vista.  Hence neither does rust.  Is the same thing going to happen with Windows 7 in 5 years, then Windows 10 in another 5 years?  Are customers of software written in rust going to have to worry that it has a limited lifetime?

Does anyone know if there were strong technical reasons for clang not to support XP and Vista?  The reason given seemed to be that there were easier constructs that Windows 7 and above provides that makes writing for clang much easier.  Given the natural advances of technology, will that not also be true every few years as each new version, with its new bells and whistles, gets put into the Windows OS?

Has clang dropped support for any current versions of Linux/BSD?

Does Mozilla plan to look into any other base for libraries, or is clang planned for the life of rust?

Thanks

**Comment by steveklabnik** [comment]
These kinds of discussions are best suited for http://internals.rust-lang.org/, would you mind posting this over there please? Thanks!
