### ISSUE TITLE
No way to print intermediate Command results

### ISSUE THREAD

**Issue by Gankro** [rust-lang/rust#30098]
I have an application that spends about 30 minutes executing benchmarks by invoking Cargo through std::process::Command. It would be really nice to be able to print intermediate results as each bench completes, but Command doesn't seem to expose anything. It would be sufficient for my purposes to be able to tee stdout/err to the parent process' stdout/err, but a more general mechanism may be desirable.

**Comment by eefriedman** [comment]
It's not impossible with the current API, just kind of inconvenient.  Given a piped stdout, you can do whatever you want with the stream (including implementing a tee-like mechanism).

(Did you mean to file this against rust-lang/rfcs?)

**Comment by Gankro** [comment]
(I'm always terrible at picking the right repo)

**Comment by Gankro** [comment]
@eefriedman can you elaborate on what you're proposing (I'm not super familiar with piping processes)?

**Comment by eefriedman** [comment]
```rust
fn main() {
    use std::process::Command;
    use std::process::Stdio;
    use std::io::Read;
    use std::io::Write;
    use std::io::stdout;

    let child = Command::new("cat")
                         .arg("/usr/include/stdio.h")
                         .stdout(Stdio::piped())
                         .spawn()
                         .unwrap_or_else(|e| { panic!("failed to execute process: {}", e) });
    let mut out = child.stdout.unwrap();
    let mut read_buf = [0u8; 64];
    let mut out_buf: Vec<u8> = Vec::new();
    while let Ok(size) = out.read(&mut read_buf) {
        if size == 0 {
            break;
        }
        stdout().write_all(&read_buf).unwrap();
        out_buf.extend(read_buf.iter());
    }
}
```

This writes the child's stdout to the parent's stdout, and saves the result.  It could easily be packaged up into a crate if someone was interested.

**Comment by Gankro** [comment]
Hey awesome, thanks! I think this is sufficient for the job.
