### ISSUE TITLE
Add `std::str::line_indices` iterator method?

### ISSUE THREAD

**Issue by mitchmindtree** [rust-lang/rust#30090]
I'm currently working on text manipulation in conrod and I have a few use-cases where I'd like to get the byte indices at which each line starts and ends so that I can store and re-use them for faster repeated line iteration (faster than using `Lines` each time, that is).

I imagine the method signature looking something like this

``` rust
/// An iterator over the start and end indices of each line in a string, separated by \n or \r\n.
///
/// This does not include the empty string after a trailing newline or CRLF.
pub fn line_indices(&self) -> LineIndices
```

Where `LineIndices`' `Item` is `(usize, usize)` (the indices into each line slice).

I can see this filling the following gap:

| `.chars()` | `.char_indices()` |
| --- | --- |
| `.lines()` | ??? |

**Comment by Gankro** [comment]
There's a slight difference here in that lines returns slices, from which you can retrieve the offset by address introspection. This is not possible with chars.

**Comment by Aatch** [comment]
Hmm, I agree this is useful, but I'm wondering if it's useful enough to warrant inclusion into the standard library. It seems like a fairly specific use-case, since even similar cases might be able to just use the slices directly.

/cc @rust-lang/libs

**Comment by bluss** [comment]
Ascii char and single-byte string searches have yet to be using `memchr`, which could improve the performance of for example a \n-searching split iterator.

**Comment by Kimundi** [comment]
To actually be consistent with `char_indices()` it would have to yield `(usize, &str)` like `match_indices()`.

We could just expose a `LinesPattern` type that matches on `\n` and `\r\n`, then `x.line_indices()` would be expressible as `x.match_indices(LinesPattern)`

**Comment by bluss** [comment]
With a regex (and the pattern feature gate), it should already be possible to do the LinesPattern and use it with `match_indices`.

**Comment by dtolnay** [comment]
I agree that this feels too specific to be useful in the standard library. Here is what this might look like with a loop that looks for line breaks:

```rust
extern crate regex;
use regex::Regex;

fn main() {
    let input = "aaa\r\nbbb\n\nccc\n";
    let linebreak = Regex::new(r"\r?\n").unwrap();
    let mut prev = 0;
    for m in linebreak.find_iter(input) {
        println!("{}..{} {:?}", prev, m.start(), &input[prev..m.start()]);
        prev = m.end();
    }
    if prev < input.len() {
        println!("{}..{} {:?}", prev, input.len(), &input[prev..]);
    }
}
```

**Comment by 9999years** [comment]
For future visitors, [the `line_span` crate](https://docs.rs/line-span/latest/line_span/) provides a rather nice API for this:

> ```rust
> use line_span::LineSpanExt;
> 
> let text = "foo\nbar\r\nbaz";
> 
> for span in text.line_spans() {
>     println!(
>         "{:>2?}: {:?} {:?} {:?}",
>         span.range(),
>         span.as_str(),
>         span.as_str_with_ending(),
>         span.ending_str(),
>     );
> }
> ```
> 
> This will output the following:
> 
> (Manually aligned for better readability)
> 
> ```
> 0.. 3: "foo" "foo\n"   "\n"
> 4.. 7: "bar" "bar\r\n" "\r\n"
> 9..12: "baz" "baz"     ""
> ```
