### ISSUE TITLE
Redundant cloning of git submodules

### ISSUE THREAD

**Issue by petevine** [rust-lang/rust#30107]
When building from git source, the build system makes a deep clone of git submodules, even those, like `jemalloc` or `llvm`, that had been disabled with configure options. (`--disable-jemalloc` and `--llvm-root` respectively)

Not downloading a couple hundred megabytes of data spread over tens of thousands of small files is especially important on flash devices (and slow connections).

**Comment by Aatch** [comment]
At the very least it should probably do a shallower clone of those repos. As best I can tell, you should be able to just pass `--depth 1` to `git submodule update` just fine.

**Comment by petevine** [comment]
Yep, that would be a great start. However the gist of this report is to completely forego downloading the source trees that are never going to be used.

**Comment by petevine** [comment]
@japaric I've just tested your patch, having done a `rust` shallow clone first and `llvm` is not cloned at all but `jemalloc` still is.  Still, a huge improvement; thanks!

I also paid attention to the amount of data downloaded by fully cloning other modules, like `compiler-rt`, `liblibc`, etc. and it seems bootstrapping from a source snapshot is still the fastest option, requiring a 50% smaller download.
