### ISSUE TITLE
Links to types in an extern crate declared somewhere other than the crate root are broken

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#30109]
See for example `SslStream` on this page: http://sfackler.github.io/rust-postgres/doc/v0.10.1/postgres/io/trait.StreamWrapper.html

The link has an `/io/openssl/` in it that shouldn't be there.

**Comment by mitaa** [comment]
I'm pretty sure this broke with #27458, which invalidates the assumption that item paths from within the local and external crate are the same.

https://github.com/rust-lang/rust/blob/master/src/librustdoc/clean/inline.rs#L134-L147
