### ISSUE TITLE
macro expanding to nothing in match arm causes uninformative parse error

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#30128]
[Failing code](http://is.gd/q92sdB):

``` rust
macro_rules! empty { () => () }

fn main() {
    match 42 {
        _ => empty!()
    };
}
```

The error is "unexpected token: `<eof>`" with a span of 1:1: 1:1.

[Workaround](http://is.gd/93TwC5):

``` rust
macro_rules! empty { () => () }

fn main() {
    match 42 {
        _ => { empty!(); }
    };
}
```

Expected: the failing code either compiles or at least gives an error pointing at the problem.

Found by mohawk on IRC.

**Comment by makoConstruct** [comment]
A further reduced case, probably the same problem:
```rust
macro_rules! mac { () => () }

fn main(){ let a = mac!(); }
```

Likely connected to #10951 as well.

**Comment by estebank** [comment]
Possibly related to #26288.

**Comment by estebank** [comment]
CC #27569

**Comment by estebank** [comment]
CC #33953
