### ISSUE TITLE
Implement Read/Write on Cursor over &mut Vec

### ISSUE THREAD

**Issue by dbrodie** [rust-lang/rust#30132]
It is currently impossible to use a std::io::Cursor over a Vec in a smart pointer (Mutex, RefCell, ...) in a sane way. Please implement Read/Write/... over Cursor<&'a mut Vec<u8>>.

Discussed on [users.rust-lang.org](https://users.rust-lang.org/t/missing-implementation-of-cursor-for-a-derefmut-of-vec/3826).

**Comment by est31** [comment]
Good workaround is to call the `as_mut_slice` function on the mutable Vec reference when creating the Cursor. Then you'll have `Cursor<&'a mut[..]>` and Read/Write is implemented.

**Comment by nox** [comment]
AFAICT, adding such an impl is a breaking change:

```rust
use std::marker::PhantomData;

struct Cursor<T>(PhantomData<T>);

impl<T> Cursor<T> {
    fn new(_: T) -> Self {
        Cursor(PhantomData)
    }
}

trait Write {
    fn flush(&mut self) {}
}

impl<'a> Write for Cursor<&'a mut [u8]> {}
impl Write for Cursor<Vec<u8>> {}

// This code doesn't type check if this is uncommented:
// impl<'a> Write for Cursor<&'a mut Vec<u8>> {}

fn main() {
    let mut vec = vec![0u8];
    Cursor::new(vec.as_mut()).flush();
}
```

**Comment by sfackler** [comment]
New implementations are allowed to cause inference breakage.

**Comment by dtolnay** [comment]
Seems reasonable. I would be interested in seeing a PR that implements this.
