### ISSUE TITLE
Enable panic-free compilation with no stdlib

### ISSUE THREAD

**Issue by alexchandel** [rust-lang/rust#30139]
Programming safety-critical and crash-free systems in Rust is excessively difficult, even with no_std, because there are so many panics scattered throughout libcore. When any possibility of an exception being thrown is unacceptable, even when caught with [catch_panic](27719)/`recover`, much work must be expended avoiding and removing them from object files. There should be a flag, e.g. `-C no-panic`, that makes the panicking language items unnecessary and causes the compiler to emit an error whenever a function is called that can panic.

**Comment by steveklabnik** [comment]
A change of this magnitude needs to go through the RFC process; the idea of removing panics from the language is one that has a long history and is very controversial.

**Comment by alexchandel** [comment]
@steveklabnik Ok, I can start an RFC. But I'm not proposing to remove them from the language. I want the compiler to help me avoid calling `panic_fmt!`, or calling anything that calls `panic_fmt!`; this could even be a lint.
