### ISSUE TITLE
Add ability to redefine Index for [T] to eliminate panicking

### ISSUE THREAD

**Issue by alexchandel** [rust-lang/rust#30142]
When writing safety-critical code in Rust, it's necessary and somewhat of a nuisance to avoid slice notation: hundreds of expressions like `self.is_hash.get(n)` crop up.

It would go a long way to permit something like:
```rust
if let Some(x) = a_slice[n] {
  ...
else {
  ...
}
```

Such a redefinition shouldn't apply to any dependency crates; its effects could even be kept from dependent crates, or it could only be permitted in a top-level crate. I realize this may involve an orphan implementation, but with the aforementioned scoping, the issues associated with orphans can be avoided.

**Comment by steveklabnik** [comment]
This changes the semantics of stable Rust, and isn't going to be possible. A change of this magnitude is definitely RFC worthy, as it would impact almost all Rust code in existence.

**Comment by alexchandel** [comment]
@steveklabnik I can write an RFC, but it would only affect Rust crates that actually *use* it, right? It doesn't need to break anything.

**Comment by steveklabnik** [comment]
It's a breaking change to semantics, which are 'panics when out of bounds'.

**Comment by alexchandel** [comment]
@steveklabnik Right, but any crate that didn't specifically enable this would still have 'panics when out of bounds' semantics.
