### ISSUE TITLE
book: Dining Philosophers chapter uses unwrap() without explanation

### ISSUE THREAD

**Issue by salty-horse** [rust-lang/rust#30163]
```unwrap()``` is used several times throughout the chapter.

There is only a single vague mention of it, despite it being used several times in the code:
>Since this shouldn’t happen, we just use ```unwrap()```.

A bit more detail would be helpful, especially when it is first introduced in the code.

**Comment by steveklabnik** [comment]
Sure thing! Going through this section first is supposed to be a "throw you in the deep end" kind of deal, where we don't explain everything, but we could do better here.

**Comment by salty-horse** [comment]
The text doesn't go into detail (and shouldn't), but it does at least address every other piece of code (at least, that's my sense from reading it. I may have missed something)
