### ISSUE TITLE
Tracking issue for `enumset`

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#30179]
The [issue number for enumset](https://doc.rust-lang.org/stable/src/collections/enum_set.rs.html#19) is currently 0. It either needs to be assigned one or it needs to be annotated deprectated.

**Comment by alexcrichton** [comment]
Ah this is actually intended to be an internal implementation detail which is never to be exported, it's just waiting on the compiler to stop using it to delete it. I thought there was a PR to do that awhile ago but I'm not sure what happened to it...

For now though we tend to not keep issues open for these "perma-deprecated" parts, so I'm gonna close this, thanks for the reminder to remove it though!

**Comment by durka** [comment]
@alexcrichton shouldn't it be actually marked deprecated, or at least the note changed so it doesn't sound like a new feature?

**Comment by alexcrichton** [comment]
Yeah it's fine to change the note, it's not currently deprecated b/c it's not imported publicly from std.

**Comment by jethrogb** [comment]
It appears in the docs though.

**Comment by alexcrichton** [comment]
@jethrogb only for libcollections though, which is an unstable library

**Comment by jethrogb** [comment]
I suppose, but some of it leaks into the std docs: https://doc.rust-lang.org/stable/std/iter/trait.FromIterator.html#implementors-list

**Comment by alexcrichton** [comment]
Sure, and those are just bugs in rustdoc
