### ISSUE TITLE
Arrays [T;N] are not always properly parsed as types

### ISSUE THREAD

**Issue by vberger** [rust-lang/rust#30186]
This works:

```rust
fn main() {
    let a = [0u32, 0, 0];
    let b = <[u32;3]>::from(a);
}
```

but this doesn't:

```rust
fn main() {
    let a = [0u32, 0, 0];
    let b = [u32;3]::from(a);
}
```

The error being:

```
<anon>:3:20: 3:22 error: expected one of `.`, `;`, or an operator, found `::`
<anon>:3     let b = [u32;3]::from(a);
                            ^~
```

**Comment by bluss** [comment]
This is expected, the syntax `<Ty>::method` explicitly takes a type inside `<>` but the other syntax doesn't do that, if it did look for types it would accept `Vec<T>::new()` too, which it doesn't.  (`<Vec<T>>::new()` is ok!).
