### ISSUE TITLE
Access to globals in loop not optimzied

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#30193]
```rust
pub static mut X: *mut u32 = 0 as *mut u32;

pub extern fn f() {
    loop {
        unsafe {
            *X = 'a' as u32;
        }
    }
}
```

This reloads the value of `X` in every iteration. But `X` cannot be modified while inside the loop because that would be a race condition. Hence `X` should only be loaded once.

**Comment by eefriedman** [comment]
The problem isn't the potential for a race; the problem is that the compiler can't prove that X doesn't point at itself.
