### ISSUE TITLE
Broken [src] links in documentation

### ISSUE THREAD

**Issue by Seeker14491** [rust-lang/rust#30198]
The [src] link on these pages is broken:
https://doc.rust-lang.org/nightly/std/collections/struct.BTreeMap.html
https://doc.rust-lang.org/nightly/std/collections/struct.BTreeSet.html
https://doc.rust-lang.org/nightly/std/collections/struct.BinaryHeap.html
https://doc.rust-lang.org/nightly/std/collections/struct.LinkedList.html
https://doc.rust-lang.org/nightly/std/collections/struct.VecDeque.html

The links are also broken in the stable docs version of these pages.

**Comment by mitaa** [comment]
I think this should be fixed by #30149 (haven't verified yet).

(The link wrongly points to `core_collections` instead of `collections` because the re-export in std looks like `extern crate collections as core_collections;`)

**Comment by mitaa** [comment]
I've built the docs locally and the issue somehow persists.
