### ISSUE TITLE
Add mem::replace to prelude

### ISSUE THREAD

**Issue by jFransham** [rust-lang/rust#30199]
`mem::replace` is a really standard thing to use in Rust, and is the only way to achieve some things safely. However, it takes a lot of people a really long time to realise this, because it's hidden away in the scary-looking `mem` module, and requires the hacky-looking `mem::replace` call every time you use it, even though it's not a hack - it's the accepted method of doing it. If it was in the prelude, newbies would be able to write `replace(a, b)` without even using an import, which seems like it makes a lot more sense to me. Apart from anything else, `mem::drop` is already in the prelude and I would argue that is less useful than replace.

**Comment by retep998** [comment]
This should belong in the RFC repo.

**Comment by steveklabnik** [comment]
Yes, changes to the prelude should go through the RFC process.
