### ISSUE TITLE
Mention the `warnings` lint group in `rustc -W help` text

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#30203]
`rustc -W help` mentions:

```
Lint groups provided by rustc:

         name  sub-lints
         ----  ---------
    bad-style  non-camel-case-types, non-snake-case, non-upper-case-globals
       unused  unused-imports, unused-variables, unused-assignments, dead-code, unused-mut, unreachable-code, unused-must-use, unused-unsafe, path-statements, unused-attributes
```

There's another lint group, `warnings`, which turns off all builtin lints. We should mention it in this list (preferably at the top), or in another line below.

Relevant code: https://github.com/rust-lang/rust/blob/ac0e84522437331f9a06d04a5842acf0234cc86e/src/librustc_driver/lib.rs#L670

If you wish to make it appear in the table, ensure that `max_name_len` takes the presence of `warnings` into account too. Instead of listing the lints for the second column, add some text along the lines of "all builtin lints".

**Comment by faineance** [comment]
Can I take this?

**Comment by Manishearth** [comment]
Sure! Let me know if you need help!

(assigning to self since I can't assign it to you)

**Comment by athaeryn** [comment]
@faineance are you working on this? If you're not, I'd like to take it!

**Comment by huonw** [comment]
Hm, @Manishearth, where is this lint group defined?

**Comment by Manishearth** [comment]
It's not. It's magically in built, and the help text is similarly hand-crafted.
