### ISSUE TITLE
Is `rustc --emit=<type>=<path>` supported?

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#30204]
There seems to be code hanging around to support a variant of `--emit` of the form `--emit=<type>=<path>`.

Its not clear what it is supposed to do.

I suspect it was meant to be a way to indicate a specific file name to use for an output (so that one could do e.g.  `rustc --emit asm=bar.s --emit obj foo.rs` to get machine code in `foo.o` (inferred) and assembly in `bar.s` (explicitly specified).

But if that's the intention, it does not seem to work currently.  (Which is fine because the option is undocumented anyway.)

**Comment by pnkfelix** [comment]
(or is it somehow meant to be used as an *input* filename? )

**Comment by pnkfelix** [comment]
cc @alexcrichton

**Comment by alexcrichton** [comment]
Yeah this was [added](https://github.com/rust-lang/rust/pull/28768/files) [recently](https://github.com/rust-lang/rust/commit/8c963c07) to make `dep-info` emission [more customizable](https://github.com/rust-lang/rust/issues/28716) and I tried to [add some docs for it](https://github.com/rust-lang/rust/blob/ac0e84522437331f9a06d04a5842acf0234cc86e/man/rustc.1#L55-L58) but our man pages are actually pretty rarely read I think...

We've also got what I was hoping was a [pretty exhaustive test](https://github.com/rust-lang/rust/blob/ac0e84522437331f9a06d04a5842acf0234cc86e/src/test/run-make/output-type-permutations/Makefile) for this sort of functionality, and when I run `rustc --emit asm=bar.s --emit obj foo.rs` it works for me? (nightly channel right now)

When you say that it doesn't work, what sort of behavior did you see?

**Comment by pnkfelix** [comment]
@alexcrichton oh maybe I wasn't testing against nightly; let me double check

**Comment by pnkfelix** [comment]
@alexcrichton I think I know the problem: I'm using `--emit=asm=bar`, not `--emit asm=bar`

**Comment by alexcrichton** [comment]
Oh weird, I would expect getopts to consider those two equivalent... I wonder if there's a bug in getopts?

**Comment by pnkfelix** [comment]
@alexcrichton yes I think it is, I just saw something suspicious; look here: 

  https://github.com/rust-lang/rust/blob/master/src/libgetopts/lib.rs#L605

(I bet the `split` above it should be a `splitn`...)

**Comment by alexcrichton** [comment]
Ah yep that'd do it!

**Comment by pnkfelix** [comment]
I'm cherry-picking https://github.com/rust-lang-nursery/getopts/commit/8ec916b86afce0a2a9100b7327b12b5ffcb2cabb as we speak.  :)
