### ISSUE TITLE
rustdocs: missing items in reexported modules

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#30213]
`std::fmt` is reexported as:

```
pub use core_collections::fmt;
```

This didn’t used to be a problem, http://doc.rust-lang.org/1.4.0/std/fmt/#structs documents a bunch of things. But most of it went missing: http://doc.rust-lang.org/nightly/std/fmt/#structs. (Note that URLs are for 1.4 and current nightly.)

CC @alexcrichton

**Comment by petrochenkov** [comment]
The main suspect is probably https://github.com/rust-lang/rust/pull/29822, I'll look at what happens.

**Comment by alexcrichton** [comment]
Thanks for investigating @petrochenkov!

**Comment by petrochenkov** [comment]
Ha, it's not https://github.com/rust-lang/rust/pull/29822, it's https://github.com/rust-lang/rust/pull/30043.
cc @arielb1

**Comment by mitaa** [comment]
Fixed by #30870

**Comment by alexcrichton** [comment]
Thanks @mitaa!
