### ISSUE TITLE
Book: Broken link(s) to book source after trpl->book dir change

### ISSUE THREAD

**Issue by bartcone** [rust-lang/rust#30218]
It seems that the _mobile_ version of the site wasn't updated with the new links to the book src. 

Old: https://github.com/rust-lang/rust/tree/master/src/doc/trpl
New: https://github.com/rust-lang/rust/tree/master/src/doc/book

Specifically the contributing section [here](http://doc.rust-lang.org/book/README.html). There maybe more places as well, just don't have the time to check right now. 

Checked with iPhone. iPad seems to load correctly.

**Comment by dillona** [comment]
Looks to be fixed in commit e37cd6d5 (PR #29966 )

**Comment by steveklabnik** [comment]
yup, thanks!
