### ISSUE TITLE
Deal with libcore/libstd doc duplication on primitives

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#30214]
Right now there are a number of extension traits in libcore that [are being stabilized](https://github.com/rust-lang/rust/pull/30187), including:
- `SliceExt`
- `StrExt`
- `CharExt`
- `Float`

These all currently have very little or no documentation because all the actual docs live elsewhere (e.g. libcollections, libstd, librustc_unicode, etc). When browsing the libcore-only docs, however, this may be a bit jarring, so we may want to resolve this somehow. A few strategies possible are:
1. Duplicate all the docs. Pros are that it's all there where you need it, cons are that the two will inevitably get out of sync and duplication is always bad.
2. Add links from core docs to std docs. Pros are that it's easy to maintain and add new APIs without excessive duplication, cons are that you've gotta click to see the docs.
3. Automatically merge std docs into core. Pros are that it's easy to maintain and you've got everything where you need it, cons are that it's difficult to implement.

I'd vote for route (2) personally.

**Comment by aturon** [comment]
(2) seems like the most pragmatic for the time being.

**Comment by sfackler** [comment]
I'd go for 2 as well.

**Comment by steveklabnik** [comment]
3 is really tough, but is gonna bit us with core docs anyway, for like... everything.

2 seems best here for now.

**Comment by steveklabnik** [comment]
Hm, so I can't actually find the doc pages for these traits.

**Comment by steveklabnik** [comment]
Update: these traits have been removed, and replaced by inherent impls. As such, this ticket is moot. Closing!
