### ISSUE TITLE
Windows 10 SDK detection broken with new SDK

### ISSUE THREAD

**Issue by retep998** [rust-lang/rust#30229]
The new Windows 10 SDK changed some registry values slightly which broke the current Windows 10 SDK detection code.

This results in the linker error `note: LINK : fatal error LNK1181: cannot open input file 'ws2_32.lib'`

I am working on a PR to ~~fix this~~ completely overhaul the code for the better.

In the meantime you can work around this issue by manually invoking vcvars as done [here](https://github.com/libpnet/libpnet/pull/135).

**Comment by retep998** [comment]
Alas, because this isn't a regression, even when my PR does land, this issue will continue to plague people until it proliferates into stable.

**Comment by maximih** [comment]
Can this be back ported to beta pls? ping @alexcrichton

**Comment by retep998** [comment]
That would involve back porting https://github.com/rust-lang/rust/pull/30233 and https://github.com/rust-lang/rust/pull/30516

**Comment by steveklabnik** [comment]
I ran into this today with someone, but the file was `userenv.lib`. Rust 1.21.0. Haven't been able to debug it.

**Comment by retep998** [comment]
@steveklabnik In general when someone gets an error where the linker can't find a system library (rather than being unable to find the linker), this is typically because they have an incomplete Windows SDK. To debug this, you'd need to know which paths the linker is searching in (via the `/LIBPATH` arguments which you can view when the linker command line is printed out because linking fail). Find the directory which corresponds to the Windows SDK (such as `C:\Program Files (x86)\Windows Kits\10\Lib\10.0.16299.0\um\x64`) and check whether that library actually exists there. If not, that version of the Windows SDK may need to be repaired or reinstalled.

**Comment by steveklabnik** [comment]
Thanks!

In the end, my student uninstalled and reinstalled both the Windows stuff and Rust stuff, and it magically worked, so I bet that was it.
