### ISSUE TITLE
Closures chapter relies on ``trait T : K { ... }`` which isn't introduced in Traits chapter.

### ISSUE THREAD

**Issue by nejucomo** [rust-lang/rust#30237]
From [Closure Implementation](https://doc.rust-lang.org/book/closures.html#closure-implementation):

> [Closure definitions] are effectively syntax sugar for traits. You’ll want to make sure to have read the traits chapter before this one, as well as the chapter on trait objects.

It then introduces the ``Fn*`` traits as follows (abbreviated):

```
pub trait Fn<Args> : FnMut<Args> {
    …
}

pub trait FnMut<Args> : FnOnce<Args> {
    …
}

pub trait FnOnce<Args> {
    …
}
```

I'm not familiar with the ``:`` syntax in declarations. (Tangent: My *assumption* would be that ``trait A : B`` means for any type to implement ``A`` it *must* have an implementation of ``B``, but then I was confused why a ``Fn`` impl *implies* a ``FnMut`` impl.)

So I skimmed the [Traits](https://doc.rust-lang.org/book/traits.html) chapter, but I did not see an explanation of this colon syntax. Likewise with the [Trait Objects](https://doc.rust-lang.org/book/trait-objects.html) chapter.

**Edit:** Fix broken link targets.

**Comment by durka** [comment]
Well, you're right about what it means. And it is explained at the [end of the Traits chapter](https://doc.rust-lang.org/book/traits.html#inheritance).

**Comment by steveklabnik** [comment]
Yup, it's there! Thanks.
