### ISSUE TITLE
Feature-gate non-Rust ABI methods

### ISSUE THREAD

**Issue by Aatch** [rust-lang/rust#30235]
Currently we allow methods to be marked with the `extern` qualifier indicating that they have a non-Rust ABI (default is "C"). They are rather bug-ridden, only really working by accident, see #26997 and #26049.

While I personally think they shouldn't be allowed to start with, putting them behind a feature-gate until we make a decision either way seems like a good idea.

Hopefully this doesn't require an RFC, but if it does, I'll write one up and this can be a tracking issue.

/cc @rust-lang/lang

**Comment by nrc** [comment]
+1 for feature gating, but I think it probably does need an RFC

**Comment by nikomatsakis** [comment]
Didn't we write an RFC about this already? I have some vague memory of this.

**Comment by pnkfelix** [comment]
(When I first read this, it seemed absurdly broad, but then I saw another interpretation, so here's my Q...)

@Aatch just to be clear, you're just talking about methods (as in, "stuff in impl blocks") and not free-fn's, right?

I.e. we would *not* be feature-gating
```rust
extern fn printf(fmt: *const u8);
```

but we *would* be feature-gating:

```rust
impl Print { extern fn printf(fmt: *const u8); }
```

Right?

**Comment by steveklabnik** [comment]
@pnkfelix i had the same reaction, and then read closely and realized that yeah, I think @Aatch is talking about only methods.
