### ISSUE TITLE
RawFloat documentation 404

### ISSUE THREAD

**Issue by tiffany352** [rust-lang/rust#30243]
In the [documentation for f32](https://doc.rust-lang.org/std/primitive.f32.html), it is listed that RawFloat is implemented for f32, and the link for that trait is a 404. RawFloat comes from `core::num::dec2flt::rawfp`, and is a public trait.

**Comment by steveklabnik** [comment]
This has already been mentioned over at https://github.com/rust-lang/rust/issues/29584, so I'm going to close this one as a duplicate. Thanks for filing!
