### ISSUE TITLE
`PathBuf` does not have `is_empty()`

### ISSUE THREAD

**Issue by dhardy** [rust-lang/rust#30259]
It is possible to create an empty `PathBuf`:

    let p = PathBuf::new();

— yet `PathBuf` has no `is_empty()` function (nor, apparently, do `Path` or `OsStr` or `OsString`).

This seems inconsistent.

Of course, there are several ways around this (`p == PathBuf::new()`, `p.to_str().map_or(true, |s| s.is_empty())`, wrapping with `Option`), but having a simple way to check this would be nice.

**Comment by frewsxcv** [comment]
Implemented in #31877.

**Comment by frewsxcv** [comment]
Now that https://github.com/rust-lang/rust/pull/31608 landed, getting the length and emptiness is pretty easy:

```rust
let _ = some_path.as_os_str().len();
let _ = some_path.as_os_str().is_empty();
```

Does anyone think it's still worth it to add the `len` and `is_empty` methods on `Path`?

**Comment by dhardy** [comment]
I don't see why you'd want `len()` but `is_empty()` would be useful.

**Comment by alexcrichton** [comment]
Closing due to the reasons outlined in [this comment](https://github.com/rust-lang/rust/pull/31877#issuecomment-191901957)

**Comment by dhardy** [comment]
@alexcrichton My use-case was completely different: using `path == PathBuf::new()` as a synonym for `None`. Possibly I should just wrap with `Option` even though technically it's more abstraction than needed.

**Comment by alexcrichton** [comment]
Yeah for now you probably want to take a look at `.as_os_str()` if you want to test a literally empty buffer, and otherwise `None` would probably be best for "this hasn't been initialized"
