### ISSUE TITLE
Symbol names with <impl> are too obscure

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#30260]
Symbol names of methods don't include the type name, instead they use the string `<impl>`.

Obscure symbol names makes reading backtraces, profiling and debugging harder.

Examples:

- `_$LT$impl$GT$::with_capacity::h1e508e0577f260f2tka` for `Vec::with_capacity`.
- `isomorphism::_$LT$impl$GT$::new::new::h10192896492405891948` 
for an item named `isomorphism::Vf2State::new`; with the type name gone, it's 
hard to directly understand which method it is

**Comment by gwillen** [comment]
Yay! Thank you. :D This was really annoying.
