### ISSUE TITLE
Broken links in the Compiler Plugins chapter of the Book

### ISSUE THREAD

**Issue by defyrlt** [rust-lang/rust#30268]
Here's the [chapter](https://doc.rust-lang.org/nightly/book/compiler-plugins.html). All of the links leading to https://doc.rust-lang.org/nightly/syntax/ are broken. On the IRC I was told that I can find docs [here](http://manishearth.github.io/rust-internals-docs/syntax/index.html). Maybe something like `internals.rust-lang.org/docs` would be an appropriate place for it?

cc @steveklabnik

**Comment by steveklabnik** [comment]
This is a dup of https://github.com/rust-lang/rust/issues/28309 and https://github.com/rust-lang/rust/issues/29912 which is a dup of https://github.com/rust-lang/rust/issues/29893

Thanks for filing though!
