### ISSUE TITLE
Treating DST constructor as a function aborts compiler

### ISSUE THREAD

**Issue by Stebalien** [rust-lang/rust#30276]
Aborts (no backtrace):

``` rust
struct Test([i32]);
fn main() {
  let x = Test;
}
```

With:

``` txt
rustc: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/lib/IR/Instructions.cpp:995: void llvm::StoreInst::AssertOK(): Assertion `getOperand(0)->getType() == cast<PointerType>(getOperand(1)->getType())->getElementType() && "Ptr must be a pointer to Val type!"' failed.
```

Forked from: #30240.

**Comment by Stebalien** [comment]
According to @Aatch,
> The last error is the most complex as it's a weird case of struct Test([i32]) being a perfectly valid type, but fn([i32]) -> Test not being a valid function. We probably need to check whether you're forcing the creation of an invalid function and error somewhere earlier. That's where the error comes from, btw, the creation of the fn Test(_0: [i32]) -> Test { ... } function body.

**Comment by Aatch** [comment]
The minimum reproduction is this:

```rust
struct Test([i32]);
fn main() {
  let x = Test;
}
```

Just to show that it's not got anything to do with taking a reference.

**Comment by Stebalien** [comment]
@Aatch, updated.

**Comment by steveklabnik** [comment]
This no longer ICEs!

**Comment by eddyb** [comment]
@steveklabnik Not too fast:
```rust
struct Test([i32]);
fn main() {
  let x: fn(_) -> Test = Test;
}
```
Reification is now lazy, `Test` itself is a zero-sized function item.

**Comment by nikomatsakis** [comment]
cc me

**Comment by Stebalien** [comment]
This appears to have been fixed.

**Comment by eddyb** [comment]
This shouldn't have been "fixed", hiding the ICE only happened by accident.

**Comment by bjorn3** [comment]
```
error[E0277]: the size for values of type `[i32]` cannot be known at compilation time
--> src/main.rs:3:36
| 3 | fn main() { let x: fn(_) -> Test = Test; }
    |                         ^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `[i32]`
    = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
    = note: all function arguments must have a statically known size
    = help: unsized locals are gated as an unstable feature
```

Rustc now errors on unsized locals being feature gated.

**Comment by workingjubilee** [comment]
No longer ICEs (again), but correctly refuses to compile on nightly even with #![feature(unsized_locals)]. Test was removed previously, should the test be brought back, then?

**Comment by nikomatsakis** [comment]
@workingjubilee seems like yes!
