### ISSUE TITLE
No (obvious way to find) documentation about how string literals are represented

### ISSUE THREAD

**Issue by hsivonen** [rust-lang/rust#30283]
When looking at the obvious chapters of both the Rust Book and the Rustonomicon, I couldn't find answers to these questions about string literals. It would be nice for the docs to answer these questions.

1. If there are two string literals with the same content, is their storage consolidated in the data segment of the shared library or executable so that the start pointers of both slices have the same value?
1.1. If yes, does such consolidation happen within the crate or also across crate boundaries?

2. Is there a way to ask Rust to make the byte after the string content zero so that the start pointer of the slice could be returned via FFI to C as a C string (assuming the content of the string does not include U+0000)?

3. If the content of one string literal is a substring of another, are both stored separately or is Rust smart enough to store only the longer string and make the other slice point to the right part of the longer string's content?

**Comment by steveklabnik** [comment]
These aren't documented because they're not guaranteed.

Currently, duplicate string literals are de-duplicated. Unsure about cross-crate.

No.

I'm not sure.

Because this isn't a bug, really, I'm going to give it a close, but you should make a post on users.rust-Lang.org about it.

**Comment by petrochenkov** [comment]
>2\. Is there a way to ask Rust to make the byte after the string content zero so that the start pointer of the slice could be returned via FFI to C as a C string (assuming the content of the string does not include U+0000)?

`"string content\0"`

**Comment by hsivonen** [comment]
@steveklabnik:

Thanks. I filed this as a bug, because other languages document whether it's correct to compare strings that came from literals via a mere pointer compare (e.g. Java says yes and C says no).

@petrochenkov:

Sure, but then the in-Rust usage becomes annoying as you have to take care of slicing off the last byte.

**Comment by cybergeek94** [comment]
@hsivonen Have a look at [this crate](https://crates.io/crates/const-cstr/) 

Full disclosure: I am the author. There was one other crate which had similar functionality but it depended on the semantics of byte-string literals while this one doesn't. I've used it in a few of my own crates and I think it works fine.

**Comment by hsivonen** [comment]
@cybergeek94: Thank you!
