### ISSUE TITLE
Docs: please mention panicking in vec! documentation

### ISSUE THREAD

**Issue by e-oz** [rust-lang/rust#30281]
Example of panic:
http://is.gd/tXpV3W

0 words "panic" here: https://doc.rust-lang.org/nightly/book/vectors.html
and here: https://doc.rust-lang.org/nightly/std/vec/

**Comment by steveklabnik** [comment]
This isn't due to Vec directly, it is due to Index.

That said, it should still be mentioned overall, but will certainly be part of my API docs work. Would you mind leaving a comment over on https://github.com/rust-lang/rust/issues/29380? Thanks!
