### ISSUE TITLE
Incorrectly printed generic in pattern matching error suggestion

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#30302]
Code:

```
enum Stack<T> {
    Nil,
    Cons(T, Box<Stack<T>>)
}

fn isEmpty<T>(s: Stack<T>) -> bool {
    match s {
        Nil => true,
        _   => false,
    }    
}
```

Error:

```
src/lib.rs:10:9: 10:12 warning: pattern binding Nil is named the same as one of the variants of the type Stack<T> [E0170]
src/lib.rs:10 Nil => true,
^~~
src/lib.rs:10:9: 10:12 help: run rustc --explain E0170 to see a detailed explanation
src/lib.rs:10:9: 10:12 help: if you meant to match on a variant, consider making the path in the pattern qualified: Stack<T>::Nil
src/lib.rs:11:9: 11:10 error: unreachable pattern [E0001]
src/lib.rs:11 _ => false,
```

This suggests pattern matching on `Stack<T>::Nil`, but that is not the correct syntax. It should be `Stack::Nil` or `Stack::Nil::<T>`.

[Original thread](https://users.rust-lang.org/t/rustc-leads-me-down-wrong-path/3922)

**Comment by pmatos** [comment]
Let me add that the reason I didn't straight away open a bug was because this error was with an old version of rustc and I haven't tested a more recent one. For the record, this is with 

    $ rustc --version
    rustc 1.3.0 (9a92aaf19 2015-09-15)

@brson have you tried with a recent version?

**Comment by jonas-schievink** [comment]
http://is.gd/DLWwMU reproduces on current nightly (although the output seems messed up)
