### ISSUE TITLE
abs_sub is strangely named

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#30315]
The C name is `fdim`, and the operation is described as "positive difference" by e.g. the C function's [man page](http://manpages.ubuntu.com/manpages/wily/en/man3/fdim.3.html), which isn't really suggested by "abs_sub" at all.

**Comment by nagisa** [comment]
I disagree `abs_sub` is strangely named. At least it is much better than `fdim`. While it could certainly be `abs_diff`erence, `abs`olute value`_sub`traction is fine IMO.

**Comment by ranma42** [comment]
Note that `abs_sub` does not compute the absolute value of the difference `abs(x-y)`, but instead `max(x-y, 0)`.

**Comment by jFransham** [comment]
@ranma42 `abs(x) === max(x, 0)` (logically, even if not in implementation), so `abs(x-y) === max(x-y, 0)`

**Comment by rkruppe** [comment]
@jFransham abs(-1) is 1, but max(-1, 0) is 0. Did you mean abs(x) = max(x, -x)? In any case, [this playground](https://play.rust-lang.org/?gist=8aa3b0addd53ebaef067&version=stable) demonstrates what @ranma42 stated.

**Comment by nagisa** [comment]
Good point, I guess `abs_sub` indeed does not make any sense at all.

**Comment by GuillaumeGomez** [comment]
I think one of the following names would fit better:
* positive_difference
* positive_diff
* pos_diff (but I don't really like this one, too short IMO)

**Comment by nagisa** [comment]
[Monus](https://en.wikipedia.org/wiki/Monus) as pointed out by sp3d on IRC.

**Comment by nagisa** [comment]
Most of the methods name the result (e.g. `(10.0).log()` stands for logarithm of `10.0`), and only some name the operation (e.g. `mul_add` which stands for `multiply-add`). I’d prefer staying with the bunch of first bucket, which pretty much implies using `difference` for whatever comes in the 2nd part. So `{}_difference` or `{}_diff`.

**Comment by alexcrichton** [comment]
The libs team discussed this issue during triage the other day and the conclusion was that this is so confusingly named and sparingly  used that we should probably just document it. The deprecation message can indicate:

* What you probably want, `(a - b).abs()`, is not what this function is doing and that code is shorter than calling the function.
* If you want this, you probably don't want to call it via a misleading name, and `(a - b).max(0)` is probably clearer and has the same semantics.

**Comment by huonw** [comment]
> `(a - b).max(0)` is probably clearer and has the same semantics.

After the meetings, I realised this isn't quite true: `fdim(NAN, 1) == NAN.abs_sub(1) == NAN`, while `(NAN - 1).max(0) == 0`.

**Comment by HeroesGrave** [comment]
I just wasted somewhere between 3-4 hours over the last day debugging my game, thinking that this was equivalent to `(a - b).abs()`.

I'm definitely in support of deprecation and renaming.
