### ISSUE TITLE
How can I randomly select element from a vector or array in rust?

### ISSUE THREAD

**Issue by Lingling7** [rust-lang/rust#30316]
If I have a vector or array in rust, how can I randomly pick one element out, and the element is a struct.

**Comment by retep998** [comment]
Such questions are typically better suited for https://users.rust-lang.org/

But to answer your question, you'd likely use [`rand`](https://github.com/rust-lang-nursery/rand). It has all the methods you need to work with random numbers.

**Comment by sanxiyn** [comment]
Specifically, [`choose`](http://doc.rust-lang.org/rand/rand/trait.Rng.html#method.choose) method.

**Comment by Lingling7** [comment]
thanks! @retep998  @sanxiyn
