### ISSUE TITLE
Include the sample project itself in Crates and Modules (5.25 of book)

### ISSUE THREAD

**Issue by cjmochrie** [rust-lang/rust#30338]
I found this section confusing because the files are built up over time (and include some intermediate steps that don't actually work to show the process). I think that simply including a link to the repository of this example project would be very useful to get an overall sense of what the finished files and structure looks like.

**Comment by cjmochrie** [comment]
Not sure whether this would be helpful, but I'd be happy to create the repo as described in the documentation and submit a pull request with a link. But I have no idea whether that would violate documentation policy.

**Comment by steveklabnik** [comment]
Yes, if we were to point to a project, it would have to be under the rust-lang org. That said, we can always transfer it.

**Comment by steveklabnik** [comment]
Given that the new book will not be using this text, I'm going to close this. I will consider doing so there though!
