### ISSUE TITLE
"errrr0" isn't the most useful error message

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/rust#30336]
[This line](https://github.com/rust-lang/rust/blob/81dd3824ff4f4f85db2a092dab78e5e6c05f96cc/src/librustc/middle/infer/error_reporting.rs#L524) has strange error text:

```rust
self.tcx.sess.note("errrr0");
```

@Manishearth added this in 89af1532, but I'm guessing it was placeholder text that got overlooked during review.

**Comment by shepmaster** [comment]
I'm happy to fix this, but not quite clear what it should say ^_^. Not sure if explaining or fixing it would be easier...

**Comment by Manishearth** [comment]
We should just remove that line. That's debugging code which should go away.

Sorry about that :smiley_cat:

**Comment by Manishearth** [comment]
(fixed in #30339)
