### ISSUE TITLE
Box<T: Error> should implement Error (std::error::Error)

### ISSUE THREAD

**Issue by qrlpx** [rust-lang/rust#30349]
I'm not too sure what versioning-annotations to use, otherwise I'd do a PR myself.

```rust
impl<T: Error + ?Sized> Error for Box<T> {
    fn description(&self) -> &str {
        Error::description(&**self) 
    }
    fn cause(&self) -> Option<&Error> {
        Error::cause(&**self) 
    }
}
```

**Comment by nixpulvis** [comment]
Not a bad idea to just make the PR and ask in there. It's always easy to add stuff.

**Comment by GuillaumeGomez** [comment]
Nothing done on it yet? It's a nice idea so if no one added it, I'll do it myself in a few days (waiting for @qrlpx's confirmation).

**Comment by qrlpx** [comment]
No, feel free to go ahead.

**Comment by GuillaumeGomez** [comment]
@qrlpx: Thanks!
