### ISSUE TITLE
Re-add raw_pointer_derive lint as a no-op

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#30346]
Removed in #29882, causing [breakage](https://internals.rust-lang.org/t/regression-report-stable-2015-10-29-vs-beta-2015-11-05-vs-nightly-2015-11-19/2922/5) to maidsafe_utilities.

I recall at some point we decided *never* to remove lints because of this very problem and simply convert them to no-ops.

**Comment by brson** [comment]
Policy-wise this is similar but (imo) different to our policy of allowing changes to lints to break code. E.g. `cap-lints` won't affect removed lints.

**Comment by alexcrichton** [comment]
It looks like the breakage is due to `unknown_lints` which is itself a lint, so this seems like it's covered by our lint changes policy. Along those lines I can't actually think of a technical reason for why we'd want to *not* remove lints?

I do vaguely recall reaching the conclusion at some point, however, about not removing lints. I don't remember the reason, however, so I'd want to discuss this a bit before reverting.

**Comment by brson** [comment]
Two more crates broke in the latest [report](https://internals.rust-lang.org/t/regression-report-stable-2015-12-10-vs-beta-2015-12-10/3025/2).

**Comment by bluss** [comment]
Don't we have a cargo feature that ensures that warnings (lints) changes are of very low impact, i.e. don't really break things that depend on the crate, for example.

**Comment by sfackler** [comment]
Yep, lints are capped at allowed for dependencies. Changing this one to be a no-op and maybe adding a default-warn `noop-lints` lint or whatever seems like a good idea though. It seems excessive to stop compilation instead of just warning when this kind of thing happens.

**Comment by brson** [comment]
Another regression popped up [in this report](https://internals.rust-lang.org/t/regression-report-stable-2015-12-10-vs-nightly-2015-12-21/3026). accumulator-0.1.3

**Comment by brson** [comment]
Also containerof-0.2.1, memory_map-0.0.3.

**Comment by brson** [comment]
After updating the regression sheet I count 7 crates affected by this.

**Comment by brson** [comment]
@nikomatsakis and I discussed that we'd prefer removed lints indicate they were removed with a warning instead of saying 'unknown lint'. I may try to get a patch together that does this.

**Comment by pnkfelix** [comment]
triage: P-high

(it is questionable about whether this should be classified as a "regression" per se, in terms of what the impact actually is of this sort of change if you aren't opting into stronger lint settings.  but anyway, we want to handle this case better.)

**Comment by nikomatsakis** [comment]
It seems there is a mechanism for registering that a lint has been *removed*, why didn't we use that?

**Comment by brson** [comment]
I will try adding it back as a removed lint and making sure it doesn't cause build failures.

**Comment by brson** [comment]
I've gotten in to yak shaving with the code for registering renamed and removed lints. It doesn't have test coverage and has some issues. Still expect to get a patch in.

**Comment by nikomatsakis** [comment]
Is this not fixed?

**Comment by nikomatsakis** [comment]
@brson ^^ :)

**Comment by alexcrichton** [comment]
Done in https://github.com/rust-lang/rust/pull/30878
