### ISSUE TITLE
std::thread::JoinHandle should support timeout

### ISSUE THREAD

**Issue by adamcrume** [rust-lang/rust#30350]
JoinHandle should have a join_timeout method.

**Comment by Stebalien** [comment]
I agree but this should probably be moved to an [RFC issue](https://github.com/rust-lang/rfcs/issues).

**Comment by adamcrume** [comment]
Fine by me.  I'm not terribly familiar with the process.

**Comment by adamcrume** [comment]
Moved to https://github.com/rust-lang/rfcs/issues/1404 .
