### ISSUE TITLE
Automatic Reporting for ICEs

### ISSUE THREAD

**Issue by nixpulvis** [rust-lang/rust#30357]
This might be a *bad* idea, but just a thought. I personally would be more than happy to enable a feature of the compiler to cache and upload/open issues for ICEs automatically. There would need to be a good way to avoid duplicates and attention to a lot of other details, but it might help catch more issues in the compiler.

**Comment by retep998** [comment]
If there was something automatic, I'd rather it be uploaded to a dedicated system and not by creating issues in this repo. Also it would have to be enabled for official binary distributions only as we don't want ICEs from people who are merely working on Rust.

**Comment by nixpulvis** [comment]
@retep998 I agree, having things polluting the issues here directly might be a bad idea.

**Comment by retep998** [comment]
Also there should be clear documentation that Rust automatically uploads ICEs and there should be an easy to find and use opt out mechanism.

**Comment by nixpulvis** [comment]
I think that's the hardest decision to make if we want this feature. Is it opt-out or opt-in, and how if so.

**Comment by killercup** [comment]
How about writing the ICE log output to a file and telling the user something like "Oh no, an internal error happened! You can find more informationen in `rustc-error.log`. If you want to report this to the Rust developers, run `rustc --report-ice rustc-error.log`. Please note that the error log may contain specific information about your program."

This could also work in combination with <https://github.com/steveklabnik/glacier>.

**Comment by nagisa** [comment]
The ICE reports are most of the time only useful when there’s a minimised example which causes the ICE to happen in the first place. It is unethical to upload the whole crate for an ICE report and no code only tells us there’s a way to cause that particular ICE happen which is not useful at all.

**Comment by steveklabnik** [comment]
This would be a significant enough change to warrant an RFC, I think. @nagisa is right to bring up ethics here, such a thing would need to be discussed at length, signaled very clearly, and would require new infrastructure.
