### ISSUE TITLE
[E0514] error message not clear 

### ISSUE THREAD

**Issue by petevine** [rust-lang/rust#30363]
I was trying to cross-compile something, and even though, the identically named down to the hash (compatible?), std crate for the cross arch had come from the same minor version (rustc 1.6.0-dev) I still got the error:

````
 hello.rs:1:1: 1:1 error: the crate `std` has been compiled with rustc 1.6.0-dev, which is incompatible with this version of rustc [E0514]
````

What is required for the crates to be compatible then? The exact commit hash of the rust compilers as well?

If so, this issue could be about something else too - building from a full source snapshot (instead of git clones) doesn't put the hash info into the binary.

**Comment by sfackler** [comment]
The compilers must have been built from the same commit.

**Comment by petevine** [comment]
Strange that it's not printing the hash if it's still able to compare against it.

**Comment by Ticki** [comment]
Try to run `cargo clean`

**Comment by petevine** [comment]
Fresh from the reddit thread, eh?
It's not that issue.

**Comment by Ticki** [comment]
Reddit thread?

**Comment by petevine** [comment]
https://www.reddit.com/r/rust/comments/3wic4c/error_the_crate_regex_has_been_compiled_with_an/

**Comment by arielb1** [comment]
What compilers were you using?

**Comment by petevine** [comment]
Those were 1.6 nightlies for armhf (from rustbuild) and i686 (mine) architectures roughly from the same day - hence the matching crate names.

**Comment by arielb1** [comment]
Apparently the nightlies are built with different values of `CFG_VERSION`. Could @alexcrichton  investigate?

**Comment by arielb1** [comment]
The `CFG_VERSION` is visible by doing `strings $RLIB_FILE_CREATED_BY_RUSTC | grep "rustc 1[.]"`.

**Comment by alexcrichton** [comment]
I guess this may depend on the string being compared, the nightly compilers have the version string ending with `-nightly` and from-source builds use `-dev` by default (configurable either way of course).

I wonder if perhaps this check should just compare commit revisions?

**Comment by petevine** [comment]
I can confirm I got it working in both directions using 1.5.0-dev (after building from the same snapshot on both architectures) - `rustc -vV` doesn't include hash info nor build date though.

**Comment by petevine** [comment]
I'd like to suggest including the commit info in the full source snapshots so that it can be parsed by the build scripts and `rustc -vV` doesn't end up like this:

```
rustc 1.8.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: arm-unknown-linux-gnueabihf
release: 1.8.0-dev
````

**Comment by Ticki** [comment]
Fixed by https://github.com/rust-lang/rust/pull/30622

**Comment by petevine** [comment]
The original issue has turned out to be about something else - fully compatible crates were being rejected for the sole reason `CFG_VERSION` was different.  Otherwise, the message would have been crystal clear.

In other words, it's not possible to pick up crates from rust-lang and use them in your own compiler built from tarball, meaning https://github.com/rust-lang/rust/pull/30622 shouldn't close this.

**Comment by petevine** [comment]
https://github.com/rust-lang/rust/issues/33286
