### ISSUE TITLE
Unused variable `result` without variable result (for loop)

### ISSUE THREAD

**Issue by tbu-** [rust-lang/rust#30371]
Code:

```
fn main() {
    for _ in match return () {
        () => Some(0),
    } {}
}
```

Warning:

```
$ rustc a.rs
a.rs:2:5: 4:9 warning: unused variable: `result`, #[warn(unused_variables)] on by default
a.rs:2     for _ in match return () {
a.rs:3         () => Some(0),
a.rs:4     } {}
```

[Playpen](https://play.rust-lang.org/?gist=3f4373be0860d4685bf5&version=nightly)

It probably has something to do with for loop desugaring.

**Comment by mitaa** [comment]
I think this should be marked "E-Easy"

Relevant code is in [src/librustc_front/lowering.rs](https://github.com/rust-lang/rust/blob/462ec057649e11ce1967b0eea6c0353375c160ea/src/librustc_front/lowering.rs#L1498).
Prefixing the variable name with an [underscore](https://github.com/rust-lang/rust/blob/462ec057649e11ce1967b0eea6c0353375c160ea/src/librustc/middle/liveness.rs#L1540-L1547) should probably be enough to fix this
(and a testcase in [src/test/run-pass](https://github.com/rust-lang/rust/tree/master/src/test/run-pass))

**Comment by durka** [comment]
E-easy! I'd like to try this one.
