### ISSUE TITLE
Book: broken link in Syntax Index

### ISSUE THREAD

**Issue by fbergr** [rust-lang/rust#30397]
The following link in [Syntax Index](https://doc.rust-lang.org/book/syntax-index.html)

https://doc.rust-lang.org/book/unsized-types.html#?sized (*See Unsized Types (?Sized).*)

Should be

https://doc.rust-lang.org/book/unsized-types.html#sized

**Comment by steveklabnik** [comment]
If anyone is looking to contribute a fix for this, that'd be great! 

To do so would require changing the link here https://github.com/rust-lang/rust/blob/master/src/doc/book/syntax-index.md

**Comment by fbergr** [comment]
I could try to fix the issue.

**Comment by JIghtuse** [comment]
@steveklabnik this issue should be closed, I suppose.

**Comment by steveklabnik** [comment]
Nice catch!
