### ISSUE TITLE
Cargo build fails when another folders exists

### ISSUE THREAD

**Issue by DenisKolodin** [rust-lang/rust#30395]
Disagreeable conflict: If I put `node_modules` folder with npm packages into folder with Rust project I get an error:
```
$ cargo build
Unable to update file:///C:/DEV/SIMULATOR
```
Maybe it's not a good idea to combine projects, but I think that conflict isn't a right behaviour.
If I remove that folder, cargo builds well. Why it happens?

Env: *rustc 1.7.0-nightly (110df043b 2015-12-13) | 64 bit | Win 10*

**Comment by durka** [comment]
This issue belongs in the rust-lang/cargo repository. And it would probably help if you can try to narrow down which file(s) cause cargo to fail (which node packages installed? what other non-rust files/folders e.g. package.json exist?).

**Comment by alexcrichton** [comment]
Cargo does currently do some probing of the filesystem, so it may be the case that it's a little to eager to propagate errors upwards in some circumstances, but that's definitely a bug in Cargo! You should be able to layer projects over one another and Cargo should continue to work just fine.

As @durka mentioned, though, could you reopen this in the Cargo repo? I don't think this has much to do with the compiler itself, and that's where all the code for Cargo lives.

**Comment by DenisKolodin** [comment]
Oh, sorry! It's really cargo's issue. Reopened here: https://github.com/rust-lang/cargo/issues/2211
