### ISSUE TITLE
Tracking issue for `downgraded_weak` (No way to construct std::rc::Weak without a strong reference)

### ISSUE THREAD

**Issue by shahn** [rust-lang/rust#30425]
When deserializing Weak, there's currently no clean way to handle the case that there's no strong reference anymore. Serializing doesn't have the same issue. There seem to be two solutions to this, either provide an explicit constructor that returns a Weak without using a strong reference to create it, or implementing Default for it that does the same. I prefer the former, as Default might be a bit surprising.

This would be a simple, non-backwards-incompatible change. Possible constructor name bikeshedding: Weak::new_downgraded()

### Unstable APIs

* `Weak::new`

**Comment by sfackler** [comment]
I feel like I'm missing a bit of context here - wouldn't the stored object immediately be freed since the strong reference count will be zero?

**Comment by huonw** [comment]
@sfackler, yeah, the `Weak<T>` never actually contains a `T` so it's always non-upgradable, but it allows deserialising things that happen to contain a `Weak` (where it isn't unexpected for the `Weak` to be invalid).

**Comment by Gankro** [comment]
Seems easy enough to add. Basically Option::None.

**Comment by oli-obk** [comment]
`Weak` could simply implement `Default`...

**Comment by shahn** [comment]
@oli-obk It could, but wouldn't it be a bit surprising that the Default for Weak is an unusable Weak?

**Comment by sfackler** [comment]
Ah, got it. `Weak::new_empty()` (or whatever name) seems reasonable enough.

**Comment by Gankro** [comment]
Just to be clear: an empty Weak would still allocate memory. We're all in agreement that this is the desired semantic? The alternative would be adding a sentinel state to every weak pointer that needs to be checked on every access.

**Comment by Veedrac** [comment]
If you care about allocating memory for empty `Weak`s, you could make them point to some thread-local instead. Just increment the thread-local's weak count on construction and make sure it starts with a count of 1 so it never gets deallocated.

It sounds like a needless optimization for a rare case, and the aliasing is probably undefined behaviour without care, but it's workable if you *really* want it.

**Comment by shahn** [comment]
Yes, it's fine to allocate the memory (you even want to do it to match the pre-serialization state). Having a constructor called new_* should make that clear, imo

**Comment by apasel422** [comment]
This was implemented in #30467.

**Comment by shahn** [comment]
I think this issue needs to stay open until a stabilization decision was made

**Comment by alexcrichton** [comment]
🔔 This issue is now entering its cycle-long **final comment period** for stabilization 🔔 

The libs team is also considering adding a `Default` impl for `Weak` as well.

**Comment by alexcrichton** [comment]
The libs team discussed this issue during triage yesterday and the decision was to **stabilize** with the `Default` impl as well

**Comment by SimonSapin** [comment]
Sounds OK if we make sure to explain in documentation that the created `Weak<T>` doesn’t point to a `T` value and can never be upgraded, and include an example where it can be useful to do this.
