### ISSUE TITLE
Rustbook panics on Rust 1.7.0-nightly

### ISSUE THREAD

**Issue by ebkalderon** [rust-lang/rust#30421]
I tried to run rustbook 0.4.0 on a project of mine. I got this error:

`thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:330`

My copy of rustbook was compiled in release mode using Rust 1.7.0-nightly (110df043b 2015-12-13). I ran `cargo build` inside my project's "doc" folder. Here's my "doc" directory structure:

```
doc/
  +- design/
  |    +- README.md
  +- SUMMARY.md
```

And here's the backtrace:

```
   1:     0x7fc8be00f2e0 - sys::backtrace::tracing::imp::write::h7f8bffe1677463dfM0t
   2:     0x7fc8be015e25 - panicking::log_panic::_<closure>::closure.41442
   3:     0x7fc8be0158c8 - panicking::log_panic::h1e3f4d9fc8696c4017x
   4:     0x7fc8bdfdeec3 - sys_common::unwind::begin_unwind_inner::hf2f35ad4f77e2e7dlTs
   5:     0x7fc8bdfdf828 - sys_common::unwind::begin_unwind_fmt::ha2709a0f77ea06dcrSs
   6:     0x7fc8be00d131 - rust_begin_unwind
   7:     0x7fc8be05c2bf - panicking::panic_fmt::h5b8cd9bf4aef841ePnK
   8:     0x7fc8be05c958 - panicking::panic::hf0b9b21510863f3fmmK
   9:     0x557c34241509 - book::parse_summary::h58743d8db617ec3d1ga
  10:     0x557c342449cc - build::_<impl>::execute::h6e08e3b3527623b8fRa
  11:     0x557c3423e444 - main::hf0aef9d68c6dce8042a
  12:     0x7fc8be015654 - sys_common::unwind::try::try_fn::h15933761231195618505
  13:     0x7fc8be00cf78 - __rust_try
  14:     0x7fc8be0152f6 - rt::lang_start::h814024ec1a885bb594x
  15:     0x7fc8bd9c760f - __libc_start_main
  16:     0x557c3423d588 - _start
  17:                0x0 - <unknown>
```

**Comment by steveklabnik** [comment]
Thank you! You may want to check out https://github.com/azerupi/mdBook, since rustbook is not really being developed any more, and might even replace rustbook generally.

**Comment by ebkalderon** [comment]
I'm trying out mdBook. It works great! But what about the existing Rust book and the Rustonomicon? Will they be migrated to use mdBook eventually? Do they already?

**Comment by steveklabnik** [comment]
I'm giving it a trail for The Book, and if it works out, then we'll end up porting both, yes. It's just in a trial phase right now, so I can't make any guarantees :)

**Comment by steveklabnik** [comment]
rustbook is slated to die at this point, to be replaced by mdbook. I'm gonna give this a close, thanks!
