### ISSUE TITLE
Better diagnostics for `let = (let =`

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#30440]
This code isn't valid Rust:

```rust
let x = (let y = 6);
```

We have an okay, but not great, diagnostic here:

```text
src/main.rs:2:14: 2:17 error: expected identifier, found keyword `let`
src/main.rs:2     let x = (let y = 6);
                           ^~~
src/main.rs:2:18: 2:19 error: expected one of `!`, `)`, `,`, `.`, `::`, `{`, or an operator, found `y`
src/main.rs:2     let x = (let y = 6);
                               ^
```

It might be nice to add a `note` when the keyword found is `let` that mentions that `let` is not an expression, and so cannot be used in this way.

**Comment by Manishearth** [comment]
@Wafflespeanut want to work on this? It's a similar task to the other doc comment one, but much simpler since it's a very specific situation.

**Comment by Wafflespeanut** [comment]
Of course! Thanks! :)

**Comment by Wafflespeanut** [comment]
I'd be happy to help someone :)

**Comment by Wafflespeanut** [comment]
So, the parser already has its ways to differentiate keywords from identifiers. All we have to do is find the right place where that error is thrown, check whether it's a `let` and add a note along with the error. The parser has all sorts of code, and adding a note's also around there somewhere :)

Code: `src/libsyntax/parse/parser.rs`

**Comment by dsprenkels** [comment]
I would like to try this. :)

**Comment by Manishearth** [comment]
Awesome! Feel free to ask waffles or me for help (you can find us both on IRC on #rust-internals), or ask questions here.
