### ISSUE TITLE
ICE with if-let inside closure

### ISSUE THREAD

**Issue by hban** [rust-lang/rust#30464]
Code (`if-let` references `Bar3`, but there is no variant with that name):

    enum Foo {
		Bar1,
		Bar2,
	}
	
	fn test() {
		let test = |foo| if let &Foo::Bar3 = foo { 1 } else { 2 };
	}

Output:

	src\lib.rs:7:27: 7:36 error: no associated item named `Bar3` found for type `Foo` in the current scope
	src\lib.rs:7    let test = |foo| if let &Foo::Bar3 = foo { 1 } else { 2 };
											^~~~~~~~~
	error: internal compiler error: unexpected panic
	note: the compiler unexpectedly panicked. this is a bug.
	note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
	thread 'rustc' panicked at 'path not fully resolved: PathResolution { base_def: DefTy(DefId { krate: 0, node: DefIndex(4) => Foo }, true), last_private: LastMod(AllPublic), depth: 1 }', ../src/librustc\middle\def.rs:83

`rustc --version --verbose`:

	rustc 1.5.0 (3d7cd77e4 2015-12-04)
	binary: rustc
	commit-hash: 3d7cd77e442ce34eaac8a176ae8be17669498ebc
	commit-date: 2015-12-04
	host: x86_64-pc-windows-gnu
	release: 1.5.0

~~Also panics on nightly.~~

**Comment by mitaa** [comment]
Doesn't ICE for me (playpen nightly, beta, and local `1.7.0-nightly (abf60b20a 2015-12-19)`)

**Comment by hban** [comment]
I tried again and you're right, it panics only on 1.5. Thanks for checking.
