### ISSUE TITLE
Consider checking constants in public interfaces for privacy

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#30475]
I.e. making something like

```
const PRIV: usize = 10;
pub fn f() -> [u8; PRIV] { ... };
```

a privacy error/warning.

Some discussion in https://github.com/rust-lang/rust/pull/29973#issuecomment-165723770 and below.
There are unresolved questions - what exactly should be checked - all signatures, all signatures except for constant initializers, const function bodies?

**Comment by petrochenkov** [comment]
Personally, I don't think it's a good idea to make this a language rule, maybe a lint at best, due to leaky nature of this restriction (it gives no useful guarantees).

**Comment by petrochenkov** [comment]
@nikomatsakis 
I think this can be closed now as not fitting into the privacy model and too breaking to change.

**Comment by nikomatsakis** [comment]
Agreed.
