### ISSUE TITLE
Mir: translation of indexing is incorrect

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#30474]
```rust
const C: [u32; 5] = [0, 42, 112, 212, 433];

#[rustc_mir(graphviz="foo.gv")]
fn mir() {
    C[3];
}

fn main(){}
```

will fail to compile with an LLVM abort:

```
Stored value type does not match pointer operand type!
  store [5 x i32] %4, i32* %temp1, align 4
 i32Invalid bitcast
i8 addrspace(9)* bitcast (%str_slice { i8* getelementptr inbounds ([7 x i8], [7 x i8]* @str3466, i32 0, i32 0), i64 7 } to i8 addrspace(9)*)
```

Seems to be a mis-translation of indexing (trans/mir/lvalue at `ProjectionElem::Index`).

**Comment by nagisa** [comment]
This is not related to https://github.com/rust-lang/rust/issues/30479.

According to @eddyb we might do something incorrectly with GEPs.

**Comment by eddyb** [comment]
That was my first guess, but it seems that `C[3]` is an rvalue with the type `[u32; 5]`, suggesting `C` itself was loaded.

**Comment by eddyb** [comment]
Oh, my first guess was right: all GEPs are `build::InBoundsGEP(bcx, tr_base.llval, &[llindex])` but that's not enough.
You see, GEP's first index is for the pointer itself. `C[3]` gets translated as `*(&C).offset(3)` not `*(&C[0]).offset(3)`.
All GEP calls should use `0` as the first index and then the index of the array element/struct field.
