### ISSUE TITLE
libc::malloc doesn't need to be unsafe

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust#30489]
[malloc](https://doc.rust-lang.org/uuid/libc/funcs/c95/stdlib/fn.malloc.html) is declared as unsafe, but AFAIK there's nothing unsafe about the call. Dereferencing of malloc'ed pointer is unsafe, but that's a different thing.

```rust
pub unsafe extern fn malloc(size: size_t) -> *mut c_void
```

**Comment by apasel422** [comment]
`extern` functions are inherently marked `unsafe`: https://doc.rust-lang.org/book/ffi.html.

**Comment by alexcrichton** [comment]
Yes currently all FFI functions exported by libc are `unsafe` because they're all inherently defined as such but it's also calling foreign code which can generally do anything!
