### ISSUE TITLE
Benchmark testing not possible in rust 1.4

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [rust-lang/rust#30488]
The method to create and run benchmark tests described in this documentation page:

https://doc.rust-lang.org/book/benchmark-tests.html

does not work when using rust 1.4

If you chose the Run button to try it in the playground I have not been able to get any version of it to run, even after editing file (for pub on function inside main, use of "feature", etc etc)

Should run cargo test to execute those documentations tests?

**Comment by steveklabnik** [comment]
Yes, benchmark tests are currently unstable, so to use them you need a nightly compiler.

**Comment by bluss** [comment]
Note it's listed in the part of the book called *Nighty Rust*. Best way is to put your benchmarks into the `benches/` directory, that way regular cargo build and cargo test will ignore them, and you can run cargo bench with a nightly compiler.

**Comment by andrewdavidmackenzie** [comment]
You're correct. I thought I read it in the "Testing" section, but now see you're right and will do as you say.

When it becomes stable, will it still be possible to put benchmark tests into the same source files as the functions they test, and not just in the separate benchmarks directory?

Feel free to close this issue now - and thanks for your help.

**Comment by steveklabnik** [comment]
We can't be sure what will happen when they become stable, that's the whole point of them being unstable :) anything can change.

That said, if the current design stays current, then yes.
