### ISSUE TITLE
Escape sequences are not printed correctly

### ISSUE THREAD

**Issue by domoritz** [rust-lang/rust#30491]
I'm trying to replace the terminal output with new output and want to use escape sequences. 

I tried this code:

```rust
print!("\033[2J\033[1;1H");
```
I expected that the terminal content would be replaced (as it happens with python and go). Instead, I got `\033[2J\033[1;1H` as the output. I can understand that this is intended behavior but how can I print the escape sequence correctly? 

```
$ rustc --version --verbose
rustc 1.5.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-apple-darwin
release: 1.5.0
```

**Comment by apasel422** [comment]
The issue is that you're trying to use an octal character escape sequence, which Rust doesn't support, so `\0` is instead being interpreted as the null character. You have to use a hexadecimal escape instead:

```rust
print!("\x1b[2J\x1b[1;1H");
```

**Comment by domoritz** [comment]
Awesome, it works! Thank you @apasel422.

**Comment by stanislaw** [comment]
Stumbled upon this issue when was trying to use octal character escape sequence. Happy to have found this clarified officially. Thanks.
