### ISSUE TITLE
the trait `core::convert::From<usize>` is not implemented for the type `u64`

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust#30495]
There are various `From` implementations for integers, but this one is curiously absent.

I thought about making a pull request, but I can't find where the other integer `From` traits are defined.

**Comment by petrochenkov** [comment]
>I can't find where the other integer From traits are defined.

https://github.com/rust-lang/rust/blob/master/src/libcore/num/mod.rs#L1984

The discusion about `usize` is in https://github.com/rust-lang/rust/pull/28921 and https://github.com/rust-lang/rust/pull/29220 (make sure to "Show outdated diff")
TL;DR: We need more motivating examples and maybe some mini-RFC describing the portability aspect to dispel the fears of the libs team.

**Comment by pornel** [comment]
Thanks @petrochenkov. Both issues are about conversion _to_ `usize`, which is the opposite direction than specified in this issue. I needed conversion _from_ `usize` to `u64` in order to use a FFI.  

Anyway, I've noticed that there is a trait for `usize` to `size_t`, so I can tweak FFI to use it.
