### ISSUE TITLE
Probably misleading example for std::net::UdpSocket in docs

### ISSUE THREAD

**Issue by defyrlt** [rust-lang/rust#30507]
In the example for [std::net::UdpSocket](https://doc.rust-lang.org/nightly/std/net/struct.UdpSocket.html) `drop` is used:
```rust
drop(socket); // close the socket
```
This is redundant and might mislead users that they're supposed to explicitly `drop` the socket. I think this should be removed.

cc @steveklabnik ?

**Comment by steveklabnik** [comment]
Yes, I agree.
