### ISSUE TITLE
Wrapping<T> needs many different impls to make it useable

### ISSUE THREAD

**Issue by ubsan** [rust-lang/rust#30524]
* Rem
* Shl
* Shr
* \*Assign

Plus `impl Op<T> for Wrapping<T>`

**Comment by ubsan** [comment]
It really is just an oversight. `Wrapping<T>` is sadly overlooked :(

**Comment by Eh2406** [comment]
There is a FIXME related to this issue,
https://github.com/rust-lang/rust/blob/master/src/test/run-pass/num-wrapping.rs#L70
https://github.com/rust-lang/rust/blob/master/src/test/run-pass/num-wrapping.rs#L176
Now that the issue is closed can the FIXME be fix, or made more specific?
