### ISSUE TITLE
FreeBSD build broken

### ISSUE THREAD

**Issue by ebfe** [rust-lang/rust#30521]
rustc: x86_64-unknown-freebsd/stage0/lib/rustlib/x86_64-unknown-freebsd/lib/libcore
    src/libcore/nonzero.rs:45:15: 45:21 error: expected identifier, found keyword `unsafe`
    src/libcore/nonzero.rs:45     pub const unsafe fn new(inner: T) -> NonZero<T> {
                                            ^~~~~~
    src/libcore/nonzero.rs:45:22: 45:24 error: expected `:`, found `fn`
    src/libcore/nonzero.rs:45     pub const unsafe fn new(inner: T) -> NonZero<T> {
                                                   ^~
    /src/rust/mk/target.mk:194: recipe for target 'x86_64-unknown-freebsd/stage0/lib/rustlib/x86_64-unknown-freebsd/lib/stamp.core' failed
    gmake: *** [x86_64-unknown-freebsd/stage0/lib/rustlib/x86_64-unknown-freebsd/lib/stamp.core] Error 101

`git bisect` points to cd1848a1a60f40f.

cc @alexcrichton

**Comment by alexcrichton** [comment]
Yeah for this we just need a new FreeBSD snapshot (cc @dhuseby), other than that though I don't think there's much to be gained from leaving this issue around. This is a standard "a tier-3 platform has fallen behind" issue and we tend to not leave them open.

**Comment by ebfe** [comment]
Is there a better place to file and track FreeBSD issues?

**Comment by alexcrichton** [comment]
I guess not

**Comment by askalski** [comment]
I tried to reproduce this bug using GhostBSD 10.1, and the regression went even further:

```
$ ./mach build -d
looking for rustc at /usr/home/akuda/mozilla/servo/.servo/rust/2015-12-09/rustc-nightly-x86_64-unknown/rustc/bin/rustc
Downloading Rust compiler...
Download failed (403): Forbidden - https://static-rust-lang-org.s3.amazonaws.com/dist/2015-12-09/rustc-nightly-x86_64-unknown.tar.gz
```

it seems like "unknown-gnu-linux" version is available, but just "unknown" is not.

**Comment by mneumann** [comment]
Yeah, I also noticed that the build for Dragonfly has some issues (last version I tried is 11th of Dec). I'll fix it when I have some more time.

**Comment by dhuseby** [comment]
This is because there isn't a snapshot recent enough to understand that code.

**Comment by dhuseby** [comment]
@ebfe the best thing to do is to tag these issues with the A-bsd label.  I am watching all of the bsd tagged issues.
