### ISSUE TITLE
Slice pattern matching not expressive enough

### ISSUE THREAD

**Issue by Ticki** [rust-lang/rust#30540]
Following example do not work.

```rust
fn main() {
    let a = [1, 2, 3];
    match &a {
        [a.., 2, b..] => println!("It works"),
        _ => {},
    }
}
```

This results in the error:

```rust
main.rs:4:19: 4:21 error: expected one of `,` or `@`, found `..`
main.rs:4         [a.., 2, b..] => println!("It works"),
                            ^~
Could not compile `test`.

To learn more, run the command again with --verbose.
```

Even though, it should not.

**Comment by Ticki** [comment]
Note that reachability checking is possible even though more than one wildcard is used in the same match arm (it's just not implemented yet).

**Comment by jonas-schievink** [comment]
Since this requires a linear search through the whole slice, I'm assuming that this is by design and would need an RFC amendment (I haven't actually read the slice patterns RFC)

**Comment by sfackler** [comment]
What would happen if there are multiple 2s?

**Comment by Ticki** [comment]
> What would happen if there are multiple 2s?

All's fine, then. This is only related to variable bounds, obviously.

**Comment by Ticki** [comment]
https://github.com/rust-lang/rust/blob/master/src/librustc/middle/check_match.rs#L538-L981

**Comment by sfackler** [comment]
@Ticki I meant, which 2 is chosen as the split between a and b?

**Comment by Ticki** [comment]
I see. Since it's just linear search, it would be the first `2` to find.

**Comment by lilred** [comment]
Maybe post this as an RFC?

**Comment by Ticki** [comment]
Yes, will look into it, @lilred

**Comment by arielb1** [comment]
This should be an RFC. Closing.
