### ISSUE TITLE
Mangled Output Formatting In Powershell

### ISSUE THREAD

**Issue by martindevans** [rust-lang/rust#30559]
Something seems to have gone terribly wrong with the formatting of rustc output to powershell!

![untitled](https://cloud.githubusercontent.com/assets/177519/12004495/82aded40-ab55-11e5-93dc-f99748e49b18.png)

As you can see from the image above it seems like rustc has totally lost the plot formatting the first error.

I'm using a surface pro 4, windows 10, powershell. My powershell is *not* in legacy mode, window is 80 chars wide and buffer is also 80 chars wide. Unfortunately I don't have access to another PC to test this on right now but if you tell me any additional information you'd like I'll try to provide it.

**Comment by sfackler** [comment]
It looks like output from two rustc processes interleaved. I've seen this before when running `cargo test` in certain configurations when it tries to build the lib and the test binary at the same time.

**Comment by martindevans** [comment]
Ahh interesting, is there a quick easy fix?

**Comment by sfackler** [comment]
I just run `cargo build` instead of `cargo test` to fix the errors and then jump back to `cargo test`.

**Comment by jonas-schievink** [comment]
I think doing `cargo test -j1` will execute rustc in series, so it should work as well

**Comment by martindevans** [comment]
Cargo build then cargo test seems to be working. Thanks for your help guys.

Merry Christmas :santa:

**Comment by retep998** [comment]
Unfortunately we let the rustc instances write to the console directly because if they were redirected to pipes colors wouldn't work due to conhost using API calls rather than escape codes for colors.
