### ISSUE TITLE
std::sync::mpsc doesn't implement fmt::Debug for Sender, Receiver etc.

### ISSUE THREAD

**Issue by antrik** [rust-lang/rust#30563]
All public types should implement Debug.

Per conversation on #rust-internals, there might be some useful information that could be printed for these types -- but even just "Sender { .. }" etc. would be a start.

**Comment by apasel422** [comment]
Was this closed by #30894?

**Comment by antrik** [comment]
@apasel422 probably.

It has been suggested that way more useful info could actually be printed instead of the opaque placeholders -- but that would be more of a wishlist item than a bug...

The patch is sufficient to fix the actual problem I was running into: not being able to #[derive(Debug)] on any structure containing mpsc Senders/Receivers.

**Comment by alexcrichton** [comment]
Ok, closing.
