### ISSUE TITLE
book: Inconsistency between "a `&mut`" and "an `&mut`"

### ISSUE THREAD

**Issue by salty-horse** [rust-lang/rust#30568]
The book uses both forms several times. It should be consistent.

files with `a &mut`:

benchmark-tests.md
borrow-and-asref.md
guessing-game.md
references-and-borrowing.md

files with `an &mut`:

choosing-your-guarantees.md
choosing-your-guarantees.md
lifetimes.md
references-and-borrowing.md

**Comment by steveklabnik** [comment]
It should generally be "a", since it's "a mutable reference"
