### ISSUE TITLE
Fill/Alignment is ignored for Debug

### ISSUE THREAD

**Issue by stepancheg** [rust-lang/rust#30573]
Code:

```
println!("<<<{:>10}>>>", "abcd");
println!("<<<{:>10?}>>>", "abcd");
```

outputs:

```
<<<      abcd>>>
<<<"abcd">>>
```

First version is padded, second is not.

Debug output should be padded, or it should be a compilation error at least.

[Playpen](https://play.rust-lang.org/?gist=508b3943de5101b6eaee)

**Comment by alexcrichton** [comment]
Various formatting flags like this are ignored by almost all formatting implementations, so I don't think it's possible to yield a compilation error. That being said there's a case that perhaps the standard `Debug` implementations should respect this, as well as the debug builders.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/30164.
