### ISSUE TITLE
Mismatch between documentation and implementation of debug_assert_eq macro

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#30600]
The documentation for the `debug_assert_eq` macro claims:

> Asserts that two expressions are equal to each other, testing equality in both directions.

But if you read the implementation of `debug_assert_eq`, you see that it tests equality in one direction only. Also see the example: http://is.gd/YGKAOj

**Comment by durka** [comment]
What does "equality in both directions" even mean?

**Comment by sfackler** [comment]
It used to check if `left == right && right == left`.

**Comment by est31** [comment]
The commit that introduced this mismatch was
5cf126ae2f6af1cdac901f6995e3c2bab35e587f

debug_assert_eq internally uses assert_eq, and when assert_eq was changed to check equality in one direction only (in above commit), the documentation for debug_assert_eq wasn't adjusted.

**Comment by est31** [comment]
As the macro was stabilized when it checked equality in one direction only. I guess it makes most sense to adjust the documentation, and not the code?

**Comment by sfackler** [comment]
Yep, this is a docs issue.
