### ISSUE TITLE
by-value methods show as inherited by Deref in Rustdoc

### ISSUE THREAD

**Issue by vberger** [rust-lang/rust#30607]
See for example: http://vberger.github.io/wayland-client-rs/wayland_client/cursor/struct.CursorImageBuffer.html

Unless the target type is `Copy`, it is not possible to call a method taking a `self` argument (it would result in a "cannot move out of borrowed content" error), so showing these methods as available in the docs is erroneous.

**Comment by alexcrichton** [comment]
Discussion happened on https://github.com/rust-lang/rust/pull/33396, but the conclusion was that we probably don't want to do this, so I'm going to close this.
