### ISSUE TITLE
Make write!/writeln! work in no_std without importing core::fmt::Write

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#30605]
The fmt traits are in the std prelude. Right now, using write!/writeln! requires importing `core::fmt::Write` explicitly, which is a bit gross. It'd be handy if it either used `$crate::fmt::Write::write_fmt(val, ...)`, or if `core::fmt::Write` were in the prelude.

**Comment by cmr** [comment]
I think @alexcrichton would know what the tradeoffs are here.

**Comment by lfairy** [comment]
I'm not Alex, but many `std::io` types (such as [`Stdout`](http://doc.rust-lang.org/std/io/struct.Stdout.html)) do not implement `std::fmt::Write`.

**Comment by retep998** [comment]
I think the problem is that it is using duck typing to either use `fmt::Write` or `io::Write`.

**Comment by alexcrichton** [comment]
Yes unfortunately this macro can't use UFCS as it switches between the two traits @retep998 mentioned (e.g. you have to import at least one)
