### ISSUE TITLE
Mir: casting &str to *const str will cast twice

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#30612]
```rust
#[rustc_mir(graphviz="foo.gv")]
fn mir(){
    "hello" as *const str;
}
```

will result in

![foo](https://cloud.githubusercontent.com/assets/679122/12038777/7b8aa470-ae63-11e5-91f8-cf0f4071387a.png)

Note the repeated cast to `*const str`.

**Comment by arielb1** [comment]
This is semi-expected. One of the casts is a coercion and the other is the identity cast. We shouldn't however be emitting `Misc` instructions for identity casts.

**Comment by pczarn** [comment]
What kind of instruction should be emitted for identity casts?

**Comment by arielb1** [comment]
We should not be emitting any instructions for an identity cast. I think that this could be best done in a post-processing pass.

**Comment by eddyb** [comment]
I believe my "mir: Ignore noop casts (e.g. when `as` used for coercion)." commit from #32080 fixes this.

**Comment by nagisa** [comment]
Seems to be fixed indeed.
