### ISSUE TITLE
Aggressive inlining of str::contains

### ISSUE THREAD

**Issue by emoon** [rust-lang/rust#30617]
When using something like this

```Rust
let t0 = "foo";
let t1 = "bar";

if t0.contains(t1) {
   ...
}
```

The generated code is quite big which might be caused by aggressive inlining. In this case where the function is quite big it would likely be better to keep it outline instead.

Example over here https://play.rust-lang.org/?gist=f9a5f33f784b459ea62f&version=stable6 (make sure to switch to Release)

Original post from the Rust forum https://users.rust-lang.org/t/code-generation-for-str-contains/4100

**Comment by Gankro** [comment]
Is this the case in a program with many invocations of `contains`? The sample program inlining everything to death seems quite reasonable, considering there aren't any other usages of the function in the binary.

**Comment by emoon** [comment]
I tested now and you are correct. If I have two calls they will be outlined while when I have one it gets inlined. The reason I found it strange was that it was part of a larger function and it had quite a bit of code in it but I would assume it's for the same reason.

Thanks for the reply and I will just close this one.

**Comment by Gankro** [comment]
Awesome! Thanks for following up, and good luck! :sparkling_heart:
