### ISSUE TITLE
Android cross-compiler rustc build failed on x86 host

### ISSUE THREAD

**Issue by wyklq** [rust-lang/rust#30611]
My system:
• Ubuntu 15.10, 32 bit
• gcc 5.2.1
• Android ndk version r10d
• android toolchain created with  `android-ndk-r10d/build/tools/make-standalone-toolchain.sh --platform="android-21" --toolchain=x86-4.9 --arch=x86 --install-dir="/opt/ndk"  `

Source code: 
`rustc-nightly-src.tar.gz` downloaded on 2015.12.29

Configuration:
`./configure --disable-docs --target=i686-linux-android --i686-linux-android-ndk=/opt/ndk`

Error:
`rustc: i686-unknown-linux-gnu/stage2/lib/rustlib/i686-linux-android/lib/libstd
 src/libstd/thread/local.rs:299:13 299:26 error: unresolved name 'register_dtor' [E0425]
 src/libstd/thread/local.rs:299                    register_dtor(self as *const _ as *mut u8,
...
`

Workaround:
  commentted out line src/libstd/thread/local.rs:314
`
    //#[cfg(target_os = "linux")]
    unsafe fn register_dtor(t: *mut u8, dtor: unsafe extern fn(*mut u8)) {
    ...
`

Suspect:
  i686-linux-android target is not considered as a linux, which is wrong.

**Comment by alexcrichton** [comment]
Ah yeah it may be the case that the target spec for i686 android  in librustc_back needs to have the `has_elf_tls` option turned off.

**Comment by wyklq** [comment]
Yes, this points to the root cause, it solves my problem. 
And it seems latest nightly build has fixed the issue by setting "base.has_elf_tls = false" in src/librustc_back/target/android_base.rs.  So, it solves both i686_linux-android target, and future x86_64-linux-android.
Thanks.
