### ISSUE TITLE
[MIR] Loop bodies should not have destination of any sort

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#30636]
Loop bodies are not supposed to have destination (loops, on the other hand, may), but since MIR code generates all blocks the same way, it results in an artefact of a never-used dummy assignment in MIR for some loops like:

```
loop { () }
```

or

```
while 1 == 2 { () }
```

![foo](https://cloud.githubusercontent.com/assets/679122/12050391/90410f7c-aefd-11e5-8534-f353289b7971.png)

Probably the best thing to do here would be to have a different ExprKind for loop bodies and ignore “returns” from blocks there.

**Comment by nikomatsakis** [comment]
The code in `build/expr/category.rs` already has this comment, which seems like it is pointing out roughly the same suggestion:

```rust
           ExprKind::Loop { .. } |
            ExprKind::Block { .. } |
            ExprKind::Break { .. } |
            ExprKind::Continue { .. } |
            ExprKind::Return { .. } =>
                // FIXME(#27840) these probably want their own
                // category, like "nonterminating"
                Some(Category::Rvalue(RvalueFunc::Into)),
```

**Comment by nagisa** [comment]
After some discussion with @nikomatsakis it seems to us that introducing a MIR pass somewhere later in the pipeline (e.g. after MIR-based-borrowck) might be a better, and more general, approach. The pass in question would remove unnecessary assignments: most notably, for this issue, the assignments of values of void (zero-sized, without destructor) type.

**Comment by arielb1** [comment]
Our MIR trans code *should* just not lower writes to zero-sized types to anything.

**Comment by nagisa** [comment]
@arielb1 these (i.e. at least moves, in form of `var1 = var0`) are necessary in precense of ZST which have associated destructors.

**Comment by nikomatsakis** [comment]
@arielb1 I certainly agree about the trans code -- the question is whether MIR construction should include them. I think the answer there has to be yes. I think the trans code currently screens them out, but the point of @nagisa's comment was that maybe it'd be better to do this as a pre-pass before trans (but after our static analyses has concluded).

**Comment by nagisa** [comment]
IMO trans should also represent MIR it gets as faithfully as possible, so the graphviz you look at and LLVM IR you have at hand are as close as possible. There’s no necessity to introduce workarounds into MIR trans now what later can be implemented as an optimisation on MIR itself.

**Comment by arielb1** [comment]
@nagisa 

The obvious LLVM equivalent of a zero-sized write is no code at all.

Removing pointless unit writes from the MIR might make it smaller and easier to understand, but writes of other zero-sized types may have important semantic content - that is the typical tradeoff of looking at code with/without optimizations.

Of course, if we want heavy optimizations, we would need to have both type-safe and type-unsafe versions of MIR. We also need drop-flag-containing and drop-flag-lacking versions of MIR, but I am not sure we don't want drop-flag-containing type-safe MIR.

**Comment by nagisa** [comment]
> The obvious LLVM equivalent of a zero-sized write is no code at all.

Sure. However, MIR trans is not really structured in a way to let us avoid generating these, so we, currently, generate something resembling `store undef, %destination`, where `%destination` sometimes is also an `undef`.

> Of course, if we want heavy optimizations, we would need to have both type-safe and type-unsafe versions of MIR. We also need drop-flag-containing and drop-flag-lacking versions of MIR, but I am not sure we don't want drop-flag-containing type-safe MIR.

I do not see the implication here. Why would untyped MIR be necessary for heavier optimisations?

> writes of other zero-sized types may have important semantic content

I agree.

**Comment by arielb1** [comment]
> Sure. However, MIR trans is not really structured in a way to let us avoid generating these, so we, currently, generate something resembling `store undef, %destination`, where `%destination` sometimes is also an `undef`.

Shouldn't be so hard to fix.

**Comment by arielb1** [comment]
> I do not see the implication here. Why would untyped MIR be necessary for heavier optimisations?

Because optimizations have a tendency of breaking type-safety, or at least borrow-safety.

**Comment by tsion** [comment]
Another consequence of this is making MIR not type-correct by inserting statements like `tmp1 = ()` where `tmp1` does not have type `()`, see #30876.

**Comment by nikomatsakis** [comment]
Heh, actually I think that #30876 is kind of a separate thing. That basically just suggests that the hack that was added in https://github.com/rust-lang/rust/pull/30635 was kind of bogus. I forgot of course that `loop { }` does not have type `()`.

**Comment by nikomatsakis** [comment]
On Mon, Jan 11, 2016 at 01:35:55PM -0800, arielb1 wrote:
> Removing pointless unit writes from the MIR might make it smaller and easier to understand, but writes of other zero-sized types may have important semantic content - that is the typical tradeoff of looking at code with/without optimizations.

I agree with this, which is why I have been talking about the idea of lowering MIR to "untyped MIR" after our safety analysis are done (but before trans). Ah, but I see you say that in your next paragraph :)

> Of course, if we want heavy optimizations, we would need to have both type-safe and type-unsafe versions of MIR. We also need drop-flag-containing and drop-flag-lacking versions of MIR, but I am not sure we don't want drop-flag-containing type-safe MIR.

Right. I think we just need "MIR" and "lowered MIR", basically.

**Comment by oli-obk** [comment]
With our current optimizations the MIR of the examples does not contain such assignments anymore.
