### ISSUE TITLE
Clarify iterator protocol and .next_back()

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#30633]
The iterator protocol documents that behavior on further calls after `.next()` returns None is open to decide for the implementation. We should clarify in `DoubleEndedIterator` that `.next_back()` is to be understood in the same way, and that calls to `next` and `next_back` are interchangeable — any of the two may return `None`, and after that point, the iteration is done the same way.

**Comment by steveklabnik** [comment]
/cc @rust-lang/libs 

This seems reasonable to me, but this is your call

**Comment by Gankro** [comment]
Yeah this is correct. `DoubleEndedIterator == Deque`; `next == pop_front`, `next_back == pop_back`.

**Comment by bluss** [comment]
:heart:  @steveklabnik
