### ISSUE TITLE
`iter::repeat` shouldn't implement DoubleEndedIterator.

### ISSUE THREAD

**Issue by Stebalien** [rust-lang/rust#30649]
Infinite sequences have at most one end (singly infinite). I don't know if fixing this is worth a breaking change but I felt it should, at least, be brought up.

**Comment by nagisa** [comment]
I would consider repeat to be bi-infinite sequence, and IMO this issue should be fixed by repurposing DoubleEndedIterator to be a bidirectional iterator instead so it could be used for both finite sequences and bi-infinite sequences.

**Comment by Stebalien** [comment]
The point of DoubleEndedIterator is to support `Iterator::reverse`. This doesn't make sense for singly/doubly infinite sequences because there's no way to start iterating from the other end.

**Comment by Mark-Simulacrum** [comment]
This would be backwards incompatible today, and I don't think we should do it. To me, an infinite sequence has no start or end, which makes reversing direction of iteration meaningless from the iterator's point of view, and so I don't see any reason not to implement it.

**Comment by Stebalien** [comment]
> This would be backwards incompatible today, and I don't think we should do it.

At this point, I agree.

> To me, an infinite sequence has no start or end, which makes reversing direction of iteration meaningless from the iterator's point of view, and so I don't see any reason not to implement it.

I may be misunderstanding your argument but it sounds like you're saying "this makes no sense (the operation is meaningless) therefore we should do it".

**Comment by Mark-Simulacrum** [comment]
Well, what I mean is that because the operation conceptually is possible (direction doesn't actually matter, but changing it is also fine) we shouldn't restrict the iterator from doing it.
