### ISSUE TITLE
Fill/Alignment broken with chinese characters

### ISSUE THREAD

**Issue by phsym** [rust-lang/rust#30646]
Using [fill/alignment](http://doc.rust-lang.org/nightly/std/fmt/index.html#fillalignment) in string formatting (for example in a `println!`) is broken when it contains chinese characters (and maybe other kind of characters).

For example the following code :
```rust
extern crate unicode_width;
use unicode_width::UnicodeWidthStr;

fn main() {
    let lstr = "abcdefgabcdefg";
    let cstr = "由系统自动更新";
    println!("{} : {}", lstr, UnicodeWidthStr::width(lstr));
    println!("{} : {}", cstr, UnicodeWidthStr::width(cstr));
    println!("{:*<20}", lstr);
    println!("{:*<20}", cstr);
}
```
Will print :
```
abcdefgabcdefg : 14
由系统自动更新 : 14
abcdefgabcdefg******
由系统自动更新*************
```

The chinese string has 7 symbols, which means it has the width of 14 characters since each symbol is 2 characters wide. `unicode_width` crate properly reports the width, but formatting with alignment/fill treat it as it was 7 characters wide

**Comment by nagisa** [comment]
> The chinese string has 7 symbols, which means it has the width of 14 characters since each symbol is 2 characters wide.

CJK hieroglyphs are not 2 “characters wide” nor they are 1 “characters wide”. How these symbols are drawn on screen is decided by the presentation layer. It just happens that most of the terminal emulators will allocate 2 monospace blocks for each wide character. That being said, relying on unicode-width to decide how many ASCII `-`s correspond to a single symbol you have is not entirely correct in all cases.

> Using fill/alignment in string formatting (for example in a println!) is broken when it contains chinese characters (and maybe other kind of characters).

Now, in context of Rust (and its documentation), character, in most cases, means a single `char` (that is, an unicode codepoint) and not observable width in some specific environment. All of these graphemes are separate codepoints and the behaviour of `println!` seems to be correct in that regard. 

It is simply the case of `println!` and `format!` being a wrong tool for printing out tables into monospace terminals which allocate 2 slots for each CJK character.

---

A similar case involves [combining marks](https://play.rust-lang.org/?gist=88895d8b516f25664740&version=stable), which you also should test for.

**Comment by phsym** [comment]
Understood. Thanks @nagisa.  I guess this issue can be closed. Just one more question, do you have any idea how I can detect (if possible) the width of a character ?

**Comment by nagisa** [comment]
@phsym it is not really possible unless you’re drawing the glyphs on the screen yourself. That being said, what unicode-width crate gives you should be a pretty good approximation of the common case when outputting to the terminals. It won’t work always, but it should work in most cases.

**Comment by phsym** [comment]
OK. I will do this, and add a note in my readme about the font restriction for such kind of characters.
Also, since the fill/align capability in rust won't work in such case, I'll need to write my own function for this. That's not a big deal. Thanks again

**Comment by alexcrichton** [comment]
Yes this is sort of intentional, yet also a bug at the same time. We don't want to include all the various flavorful unicode properties in libcore just to have format widths calculated correctly 100% of the time (that's what crates.io is for), so I'm at least personally of the opinion that this is "working as intended"

**Comment by phsym** [comment]
Thanks. May I close the issue then ?

**Comment by alexcrichton** [comment]
Sure, sounds good to me.
