### ISSUE TITLE
--show-span should be a -Z option

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#30656]
Not a breaking change since it is an unstable option.

**Comment by jas-on** [comment]
Is it already an unstable option? https://github.com/rust-lang/rust/blob/master/src/librustc_driver/lib.rs#L143

**Comment by sfackler** [comment]
@jas-on this issue is saying that `--show-span` should be changed to `-Z show-span`. It is already an unstable option.

**Comment by jas-on** [comment]
So `show-span` can accept `expr|pat|ty` as arguments. How would those be specified if `show-span` were change to a `-Z FLAG`?

**Comment by nrc** [comment]
Hopefully exactly the same way, not sure how possible that is. If it is not possible right now, then this probably isn't an easy issue to fix. I can look into it next week.

**Comment by alexcrichton** [comment]
We've got kinda our own syntax for the `-Z` flags so where today you pass `--show-span foo` it could instead be `-Z show-span=foo`
