### ISSUE TITLE
Trait object impl block implicitly requires 'static lifetime

### ISSUE THREAD

**Issue by VFLashM** [rust-lang/rust#30664]
Defining `impl` block for trait puts automatic `'static` lifetime restriction on trait objects. Apparently because of default object bounds.

It is:
1. Inconsistent, because you don't need it in `impl for` block and can't even use trait object lifetime syntax there.
2. Unnecessary, because even when additional lifetime restrictions are required, they can be specified for `self` value in methods.

Example:
```rust
trait T {
    fn just_fine(&self);
}

// works with explicit trivial lifetime
// impl<'a> T + 'a {
impl T {
    fn bad_stuff(&self) { println!("bad_stuff"); }
}

struct S;

impl T for S {
    fn just_fine(&self) { println!("just_fine"); }
}

fn main() {
    let s = S;
    let t: &T = &s; // error: `s` does not live long enough
    t.just_fine();
    t.bad_stuff();
    
    // on a side note, is this normal?
    // struct imports all of the trait methods
    // why doesn't it import methods form impl block?
    //s.bad_stuff(); // error: no method named `bad_stuff` found for type `S` in the current scope
}
```

**Comment by arielb1** [comment]
This is by design: see [RFC1156](https://github.com/rust-lang/rfcs/blob/master/text/1156-adjust-default-object-bounds.md).

**Comment by arielb1** [comment]
Answer to side note: rustc does not try to do trait object coercion (to convert a struct to a trait object) when doing method matching.

**Comment by VFLashM** [comment]
Could you please elaborate?

As far as I can see RFC1156 changes default object bounds behavior for boxed trait objects. It doesn't affect references to trait objects. My case doesn't have any boxes and not even focused on references.

The issue is:
1. Adding impl block implicitly put lifetime restrictions on objects. Trait impl block is the only impl block that does that.
2. Apparently there is no reason to deal with lifetimes at this level. In most cases the whole impl block should be orthogonal to object's lifetime. Even if any restrictions are required, they can be applied to `self` in function definitions.

Another issue is that it's nearly impossible to find the source of the problem. Error message is non-descriptive. If this behavior is, in fact, intended one, then error message probably should state what caused static lifetime restriction.

**Comment by VFLashM** [comment]
Please note that I can't reopen this issue and it appears to me that it is still not answered.

**Comment by CasualX** [comment]
I ran into this and didn't know what was happening until I asked ([reddit](https://www.reddit.com/r/rust/comments/57virt/hey_rustaceans_got_an_easy_question_ask_here/da5q94v/)).

Perhaps the compiler could suggest the `impl<'a> Trait + 'a` syntax?
