### ISSUE TITLE
Ambiguous deprecation notice

### ISSUE THREAD

**Issue by achanda** [rust-lang/rust#30671]
The notice for the following items says `too small a type to pull its weight`. IMHO, the message is ambiguous and does not say what type should be used instead.
- `std::net::SocketAddr`
- `std::net::SocketAddr::ip`
- `std::net::IpAddr`

**Comment by GuillaumeGomez** [comment]
In each case, it says that you have to use the type corresponding to your needs. If you need ipv4, use ipv4 types, otherwise use ipv6 types.

**Comment by dimbleby** [comment]
[Shameless plug](https://crates.io/crates/ip)

**Comment by Mark-Simulacrum** [comment]
None of these appear to be deprecated today, I believe reverted in 2067c570fb37623abc6effc3752a682795dfc83e. Closing.
