### ISSUE TITLE
Bad link to `write!` macro in docs

### ISSUE THREAD

**Issue by tbelaire** [rust-lang/rust#30673]
The link to `write!` in the docs for [write_fmt][1] is 

    https://doc.rust-lang.org/std/std/macro.write!.html

when it should be 

    https://doc.rust-lang.org/std/macro.write!.html

There is an extra `std/` in the path.

[1]: https://doc.rust-lang.org/std/io/trait.Write.html#method.write_fmt

**Comment by fhartwig** [comment]
This is already fixed on nightly.

**Comment by steveklabnik** [comment]
Yup! Thanks for reporting, but this has already been fixed.
