### ISSUE TITLE
E0275 recursion error with bound on struct

### ISSUE THREAD

**Issue by pfalabella** [rust-lang/rust#30685]
see this question on SO: [Complex trait requirements on struct](http://stackoverflow.com/questions/34552927/complex-trait-requirements-on-struct/34577038)
The issue is here, a struct and its impl, both with the same bounds generate a E0275. Removing the bound on the struct, the code compiles: 

    pub struct Model<'a, A> 
        where A: OptimAlgorithm<Model<'a, A>> // commenting this line, 
                                              // it compiles 
    {
        layer_sizes: &'a [usize],
        alg: A,
    }
    
    impl<'a, A> Model<'a, A>
        where A: OptimAlgorithm<Model<'a, A>>
    {
        pub fn new(layers: &[usize]) -> Model<Algorithm> {
            Model {
                layer_sizes: layers,
                alg: Algorithm::default(),
            }
        }
    }
[Playground](https://play.rust-lang.org/?gist=397fc4d0d083570c51a0&version=stable)

**Comment by arielb1** [comment]
Don't break rustc. The issue isn't with the bound, it is that `<Algorithm as OptimAlgorithm<Model<Algorithm>>>` can't be resolved.

**Comment by arielb1** [comment]
This looks like the inductivity issue. I think lifetimes prevent this from working correctly.

**Comment by AtheMathmo** [comment]
@arielb1 @pfalabella I'm the poster of the SO question referenced. Thank you to both of you for taking the time to look into this issue.

As the issue is still open I'd like to try and get a little clarity. @arielb1 Are you saying this is more a design issue than a bug?

**Comment by arielb1** [comment]
Right, more like a design issue.

**Comment by AtheMathmo** [comment]
@arielb1 Actually can I just check one more thing. If we remove the `'a` lifetime from the Model then the code compiles. See [here](https://gist.github.com/7704b971810faada8e6e). From what you said above this should still cause a cast which cannot be resolved?

**Comment by arielb1** [comment]
We intentionally blocked it on beta/stable.
