### ISSUE TITLE
Libstd should set doc root to point to stable docs for stable releases

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#30693]
Libstd defines `html_root_url = "https://doc.rust-lang.org/nightly/",` in its crate root. This should change to point to stable docs for stable releases of rust, so that stable rust/rustdoc generate pages that link to those docs.

**Comment by arcnmx** [comment]
Nitpick that probably doesn't matter: `https://doc.rust-lang.org/stable/` vs `https://doc.rust-lang.org/1.5.0/` is somewhat of a concern. While using `stable` is the better option, "stable" doesn't necessarily imply that it will be semver-compatible forever if a Rust 2.0 is ever released!

**Comment by brson** [comment]
A potential solution: https://github.com/rust-lang/rust/issues/19603

**Comment by dtolnay** [comment]
As noted in https://github.com/rust-lang/rust/pull/35307#issuecomment-237764591, this needs to be automated in a way that does not require a PR like #35307 before every release. I would welcome a PR to solve this permanently if anyone has ideas for how. I don't believe we need an RFC.

**Comment by kennytm** [comment]
Does something like `#![html_root_url = concat!("https://doc.rust-lang.org/", env!("RUST_CHANNEL"))]` work? IIRC it doesn't (otherwise we would have `#[doc = include_str!(...)]` already)
