### ISSUE TITLE
Add more lint checks for style

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#3070]
We have one now that checks for camel case on types, variants and traits.

We have some other rules:

* ~~consts are all caps~~ #7523
* every other ident is lower case and underscores

Let's have lint passes for those as well.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#609
