### ISSUE TITLE
API documentation: links from external crates are broken

### ISSUE THREAD

**Issue by kirelagin** [rust-lang/rust#30703]
1. Go to e.g. https://doc.rust-lang.org/rand/rand/index.html.
2. Search for something in core, say `expect`.
3. Choose something, e.g. `core::option::Option::expect`.
4. Get a 404 at https://doc.rust-lang.org/rand/core/option/enum.Option.html#method.expect (note the “rand” prefix).

**Comment by Mark-Simulacrum** [comment]
I believe this isn't a problem anymore, though I'm not entirely certain; closing. Let us know if you can reproduce and we'll reopen.
