### ISSUE TITLE
rust-gdb on OS X

### ISSUE THREAD

**Issue by davidbecher** [rust-lang/rust#30706]
Hey there,

I am running OS X and since I am not the biggest fan of `lldb` I installed good old `gdb` via Homebrew. However, the OS X `rust` installation neither installs the `rust-gdb` script, nor the according python pretty-printer scripts, only `rust-lldb` gets installed.
I tried pulling `rust-gdb` and the python-scripts from the Github repository, but running `rust-gdb` on a file which I compiled with the `-g` flag does not load the pretty-printer scripts. How exactly can I solve this problem? Or is it not possible to use `gdb` on OS X with rust? `gdb` has some very nice features which `lldb` does not have so I would rather use `gdb`.

**Comment by davidbecher** [comment]
I have been doing some digging and I found out that on Linux at least the gdb auto-load python script feature (https://sourceware.org/gdb/onlinedocs/gdb/dotdebug_005fgdb_005fscripts-section.html#dotdebug_005fgdb_005fscripts-section) is responsible for the loading of the python pretty-printer script! Seems that on OS X that `.debug_gdb_scripts` section won't get used or created by rustc. I achieved manually from within gdb to execute the python commands to set the pretty-printer for the object-files which was quite cumbersome to do manually. Is there some other was which automatically loads the pretty-printer script and sets its for all the object files?

**Comment by brson** [comment]
I can't find offhand where we decide which debugger scripts to install, but I do recall that somewhere we decide based on platform. IMO we should install both wrappers everywhere even though both debuggers aren't common on all plattforms.

**Comment by brson** [comment]
[Here's the condition](https://github.com/rust-lang/rust/blob/43403b416907e6b965c37daa53d071e1c054a302/mk/prepare.mk#L193) that decides which debugger wrappers to install.

**Comment by vincom2** [comment]
How did you get gdb on OS X to load the necessary pretty-printing scripts?

**Comment by royalstream** [comment]
I'm using a **.gdbinit** file to load the pretty printers with GDB on OSX
Scroll to the bottom of [this](https://medium.com/@royalstream/rust-development-using-vs-code-on-os-x-debugging-included-bc10c9863777) for details.

**Comment by Mark-Simulacrum** [comment]
We now install `rust-gdb` and `rust-lldb` on macOS.

**Comment by adaszko** [comment]
Hi, I'm still experiencing this problem on macOS (i.e. Rust-specific pretty printer not being loaded into GDB installed from Homebrew) and I was able to fix the problem (thanks to @royalstream's instructions) by adding:

```
python
# This is valid for rustup rust installation only.  The path will be different for Homebrew-installed Rust.
import os
sys.path.insert(0, os.path.join(os.getenv('HOME'), ".rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/etc"))
import gdb_rust_pretty_printing
gdb_rust_pretty_printing.register_printers(gdb)
end
```

to my `.gdbinit` file.
