### ISSUE TITLE
JSON errors with suggestions are incomplete

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#30701]
The suggestion code snippet does not include the suggested change, it has the original code.

To fix this, look for the FIXME for this issue in src/libsyntax/errors/json.rs. We should extend `DiagnosticSpan` with another field: `override_snippet` and use this in the suggestion case.

**Comment by AnthonyBroadCrawford** [comment]
@nrc mind if I run with this one?  Additionally, if I have any questions is it okay to ping you?

**Comment by nrc** [comment]
@AnthonyBroadCrawford that would be great and please feel free to ping me. Note that JSON errors haven't landed yet, you'll need this to land first: https://github.com/rust-lang/rust/pull/30711 (or you could pull that branch and work off that).

**Comment by AnthonyBroadCrawford** [comment]
@nrc sounds good.  What's the ETA on #30711 if you don't mind me asking?

**Comment by nrc** [comment]
@AnthonyBroadCrawford I wish I knew! As soon as it gets a review and passes tests :-). Hopefully, by the start of next week.

**Comment by AnthonyBroadCrawford** [comment]
@nrc Awesome.  For now I'll just merge that branch into my fork/branch to work from there.  I can rebase if any changes come about via the review.

Thanks again!

**Comment by nrc** [comment]
@AnthonyBroadCrawford #30711 has finally landed, sorry that took so long. Did you manage to get started? Do you need any pointers?

**Comment by AnthonyBroadCrawford** [comment]
Not yet.  I'll be on it tonight.  Looking forward to digging into @nrc.  Are you in the IRC channel usually?  If so, I'll message you there.

**Comment by AnthonyBroadCrawford** [comment]
Also, I'll take any pointers or advice you have.  This would be my first commit to this project and I'm just starting to get the lay of the land reading the code-base et al.

**Comment by nrc** [comment]
@AnthonyBroadCrawford yes, I tend to be in #rust-internals and #rustc during working hours in NZ. I'll also see mentions if you ping me when I'm not online.

This is where you should start: https://dxr.mozilla.org/rust/source/src/libsyntax/errors/json.rs#187

This is how it is done for the normal error emitter: https://dxr.mozilla.org/rust/source/src/libsyntax/errors/emitter.rs#221-265. In particular, you probably want something like [complete](https://dxr.mozilla.org/rust/source/src/libsyntax/errors/emitter.rs#244) as the text for the JSON.

The way JSON errors work is we make a bunch of structs and then serialise them to JSON. The struct which represents a span is [DiagnosticSpan](https://dxr.mozilla.org/rust/source/src/libsyntax/errors/json.rs#92). At the moment, we don't include the actual code in there, just enough detail to find the code in the source text. With suggestions, we want to suggest some code to replace that span. So we should add a field for that (`replacement_text: Option<String>` or something). You could add that to either `Diagnostic` or `DiagnosticSpan`, probably `Diagnostic` is better.

**Comment by AnthonyBroadCrawford** [comment]
@nrc Thanks, this is helpful.  What's the best way to produce the errors as json.  Are those details available in the previous pr that this issue depends on?  (I'm going to go look there and if I find what I'm looking for I'll update this thread)

**Comment by nrc** [comment]
run rustc with the flags `-Zunstable-options --error-format=json`

**Comment by AnthonyBroadCrawford** [comment]
Keeping you in the loop @nrc as I should have a PR for you to pee at tomorrow.

**Comment by mitaa** [comment]
@AnthonyBroadCrawford @nrc Note that the layout of `RenderSpan::Suggestion` has changed with #30411

**Comment by AnthonyBroadCrawford** [comment]
thanks @mitaa

**Comment by vegai** [comment]
Is anyone working at this? I could take a shot.

**Comment by nrc** [comment]
ping @AnthonyBroadCrawford re the above comment. Are you still looking at this?

**Comment by sanxiyn** [comment]
This was fixed as part of porting compiletest to JSON in #33020, and FIXME is no more.
