### ISSUE TITLE
sepcomp-lib-lto test fails with multiple codegen units

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#30717]
I'm not sure whether this is a bug or not. I built rust with multiple codegen units in the hopes of faster compile times:

    RUSTFLAGS="-C codegen-units=4" make -j4 check-stage1-rpass

and the test failed

```
failures:

---- [run-pass] run-pass/sepcomp-lib-lto.rs stdout ----

error: compilation failed!
status: exit code: 101
command: x86_64-apple-darwin/stage1/bin/rustc /Users/alex/Programming/rust/rust/src/test/run-pass/sepcomp-lib-lto.rs -L x86_64-apple-darwin/test/run-pass/ --target=x86_64-apple-darwin -L x86_64-apple-darwin/test/run-pass/sepcomp-lib-lto.stage1-x86_64-apple-darwin.run-pass.libaux -o x86_64-apple-darwin/test/run-pass/sepcomp-lib-lto.stage1-x86_64-apple-darwin -C codegen-units=4 --cfg rtopt -O -L x86_64-apple-darwin/rt -C lto
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
error: can't perform LTO when using multiple codegen units

------------------------------------------

thread '[run-pass] run-pass/sepcomp-lib-lto.rs' panicked at 'explicit panic', /Users/alex/Programming/rust/rust/src/compiletest/runtest.rs:1505
```

I'm sure this build configuration is unsupported so as I said maybe this isn't a bug. But maybe this test should be conditionally ignored, somehow.

**Comment by huonw** [comment]
This isn't a bug; as the error message says, one cannot do LTO with more than one codegen unit. Thanks for filing!

**Comment by pnkfelix** [comment]
@durka FYI you probablyalreadyknowthis, but you can run t he build step with the rust flags setting separately from the check

```
make rustc-stage1 RUSTFLAGS=...
make check-stage1-rpass
```

**Comment by durka** [comment]
Ah, I did not know that @pnkfelix. All I know about the Makefile rules comes from `make tips` which is very very thin on info about progressions of rules like that. Is there a better source?

**Comment by pnkfelix** [comment]
@durka not at the moment but maybe in the "dungeon" (see brson 's post on internals.rust-lang.org )

**Comment by petevine** [comment]
If someone enables lto in Cargo.toml, like [here](https://github.com/Stebalien/exa/commit/88b86b61231f493f745efadad5b10183d2195149) and I'm using `codegen-units` transparently for every compilation that leads to failure.
If these options are mutually exclusive, why not ignore the latter?
