### ISSUE TITLE
Example for pattern binding doesn't need to use binding syntax

### ISSUE THREAD

**Issue by learnopengles** [rust-lang/rust#30725]
I'm learning Rust and came across the following part in the book, under "Syntax and Semantics" > "Patterns" > "Bindings":

> This is useful when you want to do a complicated match of part of a data structure:

```
#[derive(Debug)]
struct Person {
    name: Option<String>,
}

let name = "Steve".to_string();
let mut x: Option<Person> = Some(Person { name: Some(name) });
match x {
    Some(Person { name: ref a @ Some(_), .. }) => println!("{:?}", a),
    _ => {}
}
```

However, if we change `Some(Person { name: ref a @ Some(_), .. }) => println!("{:?}", a)` to `Some(Person { name: Some(a), .. }) => println!("{:?}", a)` (or we can also use `ref a`), it also works in the Playground, so I'm not sure why we wouldn't just use this instead of the more complicated syntax, and when the more complicated syntax is strictly necessary.

See: [Rust Playground](https://play.rust-lang.org/?code=fn%20main%28%29%20%7B%0A%20%20%20%20%23%5Bderive%28Debug%29%5D%0A%20%20%20%20struct%20Person%20%7B%0A%20%20%20%20%20%20%20%20name%3A%20Option%3CString%3E%2C%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20let%20name%20%3D%20%22Steve%22.to_string%28%29%3B%0A%20%20%20%20let%20mut%20x%3A%20Option%3CPerson%3E%20%3D%20Some%28Person%20%7B%20name%3A%20Some%28name%29%20%7D%29%3B%0A%20%20%20%20match%20x%20%7B%0A%20%20%20%20%20%20%20%20Some%28Person%20%7B%20name%3A%20ref%20a%20%40%20Some%28_%29%2C%20..%20%7D%29%20%3D%3E%20println!%28%22%7B%3A%3F%7D%22%2C%20a%29%2C%0A%20%20%20%20%20%20%20%20_%20%3D%3E%20%7B%7D%0A%20%20%20%20%7D%0A%20%20%20%20%0A%7D)

**Comment by steveklabnik** [comment]
The difference between the two is that in one, `a` is `"Steve"`, but in the other, `a` is `Some("Steve")`.

I would still be interested in an example that's more motivating, but I've never even used `@` myself. Any ideas?

**Comment by learnopengles** [comment]
Oh, I see! I guess that makes sense. I think from a beginner's POV, it would help to contrast both styles and to show an example that can only be solved with the `@` syntax. Alternatively, if it's not a commonly-used style, it could be deferred to a later chapter that goes more in-depth.

 I read that you are restructuring the book, so an idea for the new structure could be to first show the common patterns, and then later on, introduce `@` through more advanced patterns and showing how it differs from a regular binding and scenarios where it would be better to use `@`.

**Comment by steveklabnik** [comment]
Yeah, in the new book, it will work like that.

> to show an example that can only be solved with the @ syntax.

I think this is the key. @rust-lang/lang any ideas here?

**Comment by GuillaumeGomez** [comment]
I wrote an example using it on my [french tutorial](http://blog.guillaume-gomez.fr/Rust/1/5#Toujours%20plus%20loin%20!). Here it is:

```Rust
let i = 0i32;

match i {
    x @ 10...100 => println!("{} is between 9 and 101", x),
    x => println!("{} isn't between 9 and 101", x)
};
```

**Comment by pnkfelix** [comment]
here's another example that shows off some bells and whistles of pattern matching:

```rust
fn foo(mut x: (Option<usize>, &str)) {
    println!("x  pre: {:?}", x);
    if let (ref mut y @ None, s) = x {
        *y = Some(s.len());
    }
    println!("x post: {:?}", x);
}

fn main() {
    foo((None, "hi"));
    foo((Some(10), "hello"));
}
```

when run, prints:
```
x  pre: (None, "hi")
x post: (Some(2), "hi")
x  pre: (Some(10), "hello")
x post: (Some(10), "hello")
```

**Comment by steveklabnik** [comment]
Since this is for the old book, p-low.

**Comment by steveklabnik** [comment]
We've decided that the old book is accepting minor PRs, but not open issues. If you still want to improve this, please send a PR to https://github.com/rust-lang/book/, thank you!
