### ISSUE TITLE
Token tree parsing is inefficient in cases of nested macros

### ISSUE THREAD

**Issue by paulstansifer** [rust-lang/rust#3073]
In a case like this:
````
m!{ 4 + m!{ 2+ 3 } }
````
...the body of the innermost invocation gets parsed as a token tree *n* times, where *n* is the nesting depth of the macros.

What should happen is the parser should tell the lexer "I'm looking for a token tree; you don't happen to be operating on a token tree already by any chance?". `string_reader`s will say "No", and tt_readers will say "Why yes; here's the whole next subtree." In parse.rs, `parse_token_tree` will use this information similarly to the way that the the `maybe_whole!` macro works.

**Comment by steveklabnik** [comment]
Triage: the gist is out of date fairly badly, after doing the easy updates I'm getting

```
play-tt-parse1.rs:2:6: 2:14 error: `$e1:expr` is followed by `@`, which is not allowed for `expr` fragments
play-tt-parse1.rs:2     ($e1:expr @ $e2:expr) => ({ $e1 })
                         ^~~~~~~~
```

**Comment by cmr** [comment]
@steveklabnik should be able to replace the `@` with `=>` everywhere to update it.

**Comment by Toby-S** [comment]
@steveklabnik I don't think this occurs anymore, unless I messed something up when getting it to compile. Using [this updated version](https://gist.github.com/Toby-S/455ceb913739d10754eb):

```
$ time rustc play-tt-parse1.rs 

real    0m0.204s
user    0m0.172s
sys     0m0.024s
```

On the latest nightly, rustc 1.5.0-nightly (e0e262737 2015-10-27).

**Comment by steveklabnik** [comment]
@Toby-S thanks!

Anyone else, if this is still happening, please let us know.

**Comment by paulstansifer** [comment]
Nice!
