### ISSUE TITLE
Stable regression in tcod-0.8.0 resolving AsRef<Path>

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#30744]
[Originally reported by crater](https://internals.rust-lang.org/t/regression-report-stable-2015-10-29-vs-beta-2015-11-05-vs-nightly-2015-11-19/2922).

tcod-0.8.0 builds on 1.4 but not 1.5. The errors (two of them) are:

```
brian@ip-10-235-20-183:~/dev/tcod-0.8.0⟫ cargo build
   Compiling tcod-sys v3.0.2
   Compiling tcod v0.8.0 (file:///mnt/dev/tcod-0.8.0)
src/console.rs:479:39: 479:62 error: mismatched types:
 expected `&std::path::Path`,
    found `&core::convert::AsRef<std::path::Path>`
(expected struct `std::path::Path`,
    found trait core::convert::AsRef) [E0308]
src/console.rs:479                 Root::set_custom_font(self.font_path.as_ref(),
                                                         ^~~~~~~~~~~~~~~~~~~~~~~
src/console.rs:479:39: 479:62 help: run `rustc --explain E0308` to see a detailed explanation
src/console.rs:486:60: 486:70 error: no method named `as_bytes` found for type `&core::convert::AsRef<str>` in the current scope
src/console.rs:486             let c_title = CString::new(self.title.as_ref().as_bytes()).unwrap();
                                                                              ^~~~~~~~~~
error: aborting due to 2 previous errors
Could not compile `tcod`.
```

**Comment by brson** [comment]
You can get the source with `curl -sSfL https://crates.io/api/v1/crates/tcod/0.8.0/download > tcod-0.8.0.tar.gz`. Note that you'll have to edit Cargo.toml to remove the `path` line in the tcod-sys dep.

**Comment by brson** [comment]
I've updated the OP to indicate that this is actually a regression from 1.4->1.5 *stable*.

**Comment by nikomatsakis** [comment]
likely related to adding an `AsRef` impl?

cc @alexcrichton

**Comment by aturon** [comment]
Note that `self.font_path` has type `Box<AsRef<Path> + 'a>`, and the error we're getting here is connected to some intermediate trait object.

I don't think this is related to new `AsRef` impls or anything like that. Possibly an issue with method dispatch choking on the multiple layers at play here?

**Comment by brson** [comment]
We can try to bisect.

**Comment by aturon** [comment]
@brson OK -- FWIW, the current behavior looks buggy, so we can can also just try to reduce the test and make a fix directly.

**Comment by nikomatsakis** [comment]
Probably a good starting point would be trying to create a minimized test case.

**Comment by bltavares** [comment]
Would this be a minimized test case?

```rust
use std::path::Path;

struct Root<'a> {
    font_path: Box<AsRef<Path> + 'a>
}

fn main() {
    let path = Path::new("/");
    let root = Root {
        font_path: Box::new(&path)
    };

    let path_ref : &Path = root.font_path.as_ref();
}
```

I get the following with `rustc 1.7.0-nightly (d5e229057 2016-01-04)`

```
30744.rs:13:28: 13:51 error: mismatched types:
 expected `&std::path::Path`,
    found `&core::convert::AsRef<std::path::Path>`
(expected struct `std::path::Path`,
    found trait core::convert::AsRef) [E0308]
30744.rs:13     let path_ref : &Path = root.font_path.as_ref();
                                       ^~~~~~~~~~~~~~~~~~~~~~~
30744.rs:13:28: 13:51 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
```

**Comment by pnkfelix** [comment]
triage: P-high

someone should indeed try to figure out what the problem is; whether the test case in the previous comment is a representative (i.e. try it against Rust 1.4 or so), et cetera.

**Comment by bltavares** [comment]
I was able to confirm that the code fails to compile on `rustc 1.5.0 (3d7cd77e4 2015-12-04)` but compiles on `rustc 1.4.0 (8ab8581f6 2015-10-27)`.

On January 7, 2016 7:07:41 PM GMT-02:00, Felix S Klock II <notifications@github.com> wrote:
>triage: P-high
>
>someone should indeed try to figure out what the problem is; whether
>the test case in the previous comment is a representative (i.e. try it
>against Rust 1.4 or so), et cetera.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/rust-lang/rust/issues/30744#issuecomment-169805274

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by brson** [comment]
@bltavares Thanks for the investigation!

**Comment by aturon** [comment]
I'm going to look into this.

**Comment by arielb1** [comment]
I am quite sure this impl is guilty:
```Rust
#[stable(since = "1.5.0", feature = "smart_ptr_as_ref")]
impl<T: ?Sized> AsRef<T> for Box<T> {
    fn as_ref(&self) -> &T {
        &**self
    }
}
```

**Comment by arielb1** [comment]
I am quite sure we have seen this issue before - and our consensus is that methods like `as_ref` should not be used in non-generic code, because autoderef may start picking the wrong method. This *is* however an annoying gotcha in Rust. Better add it to the FAQ.

**Comment by aturon** [comment]
@arielb1 Good catch; I'm sure you're correct, and I agree with the analysis. Thanks!

**Comment by brson** [comment]
Thanks everyone for investigating.
