### ISSUE TITLE
Explain what an "OS string" is in OsStr/OsString docs

### ISSUE THREAD

**Issue by birkenfeld** [rust-lang/rust#30743]
Currently, this is pretty bare: http://doc.rust-lang.org/nightly/std/ffi/struct.OsString.html

> Owned, mutable OS strings.

Needs some explanation what an OS string is, and why it is different from C and Rust strings.

**Comment by birkenfeld** [comment]
Actually, the `std/ffi/os_str.rs` docstring has the needed info, but since this module isn't exported publicly, it is lost to the docs.

What is the best course of action in these cases?

**Comment by steveklabnik** [comment]
This is basically part of https://github.com/rust-lang/rust/issues/29354

**Comment by steveklabnik** [comment]
> What is the best course of action in these cases?

Just the most straightforward thing: there's work to be done. Just hasn't been done yet.

**Comment by birkenfeld** [comment]
> Just the most straightforward thing: there's work to be done. Just hasn't been done yet.

I get that. The question was more like, should the existing text be moved to the structs, or to the module that is exported in the docs?

**Comment by steveklabnik** [comment]
Ahh, sorry. So yeah, module-level docs should discuss the module as a whole, the struct docs, just that struct.

Checking out that source you found, yeah, even just moving them to be on the struct itself would be a pretty big improvement; maybe let's say that closes this ticket, and then making them awesome is just part of that metabug. Sound good?
