### ISSUE TITLE
Tracking issue for panic::propagate

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#30752]
`panic::propagate` triggers a panic without invoking the panic handler or wrapping the payload in a `Box<Any>`, allowing for panics to be recovered from at an FFI boundary, transported back into Rust and restarted.

**Comment by sfackler** [comment]
Example usage: https://github.com/sfackler/rust-openssl/commit/fd6454f625bb7efde3772ae106180cc6ac7c02dd

**Comment by alexcrichton** [comment]
:bell: This issue is now entering its cycle-long **final comment period** for stabilization in 1.9 :bell:

The name of this function likely wants to closely consider the naming of [`panic::recover`](https://github.com/rust-lang/rust/issues/27719) of course!

**Comment by alexcrichton** [comment]
The libs team discussed this during triage yesterday and the decision was to **stabilize** with the name `resume_unwind`

cc https://github.com/rust-lang/rust/issues/27719#issuecomment-206998250
