### ISSUE TITLE
thread_local!() can't take attributes

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#30756]
```
#![deny(unsafe_code)]

thread_local!(static KEY: u8 = 1);

fn main() {
}
```

will hit an unsafe_code warning due to an unsafe function internally defined in the thread local macro (the unsafe function is a recent addition). There's no way to `allow()` it.

The macro should take in attributes.

**Comment by Stebalien** [comment]
The correct fix for this specific bug is to annotate `__gettit` with `#[allow(unsafe_code])`. Are there any other use cases for passing attributes through?

**Comment by sfackler** [comment]
dead_code possibly.

**Comment by nodakai** [comment]
For now, we can artificially add an inner module:
```rust
#![deny(unsafe_code)]

mod inner {
#![allow(unsafe_code)]
thread_local!(pub static KEY: u8 = 1);
}
use inner::KEY;

fn main() {
    KEY.with(|x| { x == &0u8 });
}
```
