### ISSUE TITLE
Coherence rules interact strangely w/ single element tuples

### ISSUE THREAD

**Issue by sgrif** [rust-lang/rust#30762]
The following is rejected:

```rust
trait Foo {
    type Bar;
}

impl<Bar, A: Foo<Bar=Bar>> Foo for (A) {
    type Bar = Bar;
}
```

because it claims `Bar` is unconstrained. However, the same constraint is accepted for a 2 element tuple

```rust
trait Foo {
    type Bar;
}

impl<Bar, A: Foo<Bar=Bar>, B: Foo<Bar=Bar>> Foo for (A, B) {
    type Bar = Bar;
}
```

**Comment by petrochenkov** [comment]
`(A)` is the same type as `A`, parens can be used for grouping in the type grammar.
1-element tuple is `(A,)`

**Comment by sgrif** [comment]
Ah, that explains my confusion. Thanks
