### ISSUE TITLE
Explain quantification in glossary

### ISSUE THREAD

**Issue by numerodix** [rust-lang/rust#30764]
@steveklabnik 
I notice that the chapter on error handling talks about quantification in types. This probably isn't a very well known concept for people not coming from Haskell. Should this be added to the glossary?

**Comment by steveklabnik** [comment]
If you would like to add such a thing, I would accept a PR. However, I'm not really working on adding a ton of new stuff to the existing book, as the new book is completely re-written, and so won't have this particular problem. :)
