### ISSUE TITLE
Linking with gold does not search /usr/local/lib

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#30784]
If it thinks it can rustc will link with the gold linker. Unfortunately ld.bfd and ld.gold do not search the same paths for libraries. The bfd linker looks in the _runtime_ linker path, while gold does not. This creates a very confusing difference in behavior.

[Original report](https://github.com/rust-lang/rust/pull/29974#issuecomment-168935855).

**Comment by eddyb** [comment]
Like I said on the on the PR, this seems to be a distro/user bug, since it would affect everything using gold, not just rustc.

**Comment by birkenfeld** [comment]
How it can be a distro bug I'm not sure, if that's just the way that gold works.

Does any distro actually install gold as the default linker (`ld`)? There is usually a mechanism to switch to it, but it isn't the default.

By the way, since there usually *is* this mechanism, why not let that extend to Rust as well, and let the user choose by whatever is `ld` on their system?

**Comment by rprichard** [comment]
The title says `/etc/local/lib`.  I think it should be `/usr/local/lib`?

**Comment by brson** [comment]
@rprichard updated the op. Thanks.

**Comment by alexcrichton** [comment]
Removing nomination/regression tags but leaving open as to why we reverted gold

**Comment by bstrie** [comment]
> leaving open as to why we reverted gold

If the implication is that this was being left open only in the event that gold was made rustc's default linker someday, at this point I think it's unlikely that gold would be chosen over something like LLD. To that end I'd suggest this can be closed.

**Comment by Mark-Simulacrum** [comment]
I agree that this doesn't seem particularly useful to keep open - this is just linker behavior, and rustc doesn't even invoke/care about linker search paths itself for the most part.
