### ISSUE TITLE
rustc should attempt to use the gold linker by default, but this breaks Debian Wheezy because of obsolete gcc

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#30783]
[Original report](https://github.com/rust-lang/rust/pull/29974#issuecomment-168166164).

Rust nightly uses the gold linker where it can by passing `-fuse-ld=gold` to gcc when it sees that ld.gold exists. Unfortunately, even if `ld.gold` exists `gcc` may not understand `-fuse-ld=gold`.

This distro came out in May 2013, so it's not that old.

**Comment by brson** [comment]
If this can't be fixed in the next week it should probably be reverted to rethink the migration strategy.

**Comment by alexcrichton** [comment]
Aw man this is unfortunate. Agree on reverting if we can't figure anything else out.

I guess an "ideal solution" would be if gcc/clang read an environment variable as well as an argument, but I unfortunately don't see such an environment variable in clang at least. We can *maybe* try to parse something like `/etc/issue` but that seems pretty sketchy.

I wonder, how is one supposed to tell gcc on wheezy to use gold?

**Comment by brson** [comment]
@xitep suggested how to [detect gcc's support for this](https://github.com/rust-lang/rust/pull/29974#issuecomment-170115653). Unfortunately it involves running gcc an extra time. I can't think of anything better.

**Comment by alexcrichton** [comment]
It's true that's a possibility, I would likely prefer to see that as the compiler attempts to run the entire linker and then parses the error message if one shows up, and only then is gold removed if the entire linker fails. That way we'd only run gcc once if possible, and twice in the worst case.

That being said that's still a pretty big hit for distros because it's 2 times on all compiles, which is pretty unfortunate :(

**Comment by xitep** [comment]
I actually like the idea of environment variables from a user perspective. If I'd be able to set `RUSTC_DISABLE_GOLD=1` (or similar) in one of my login scripts to the system I'd be totally happy (right now my solution is quite ugly with wrapping `rustc` with custom scripts). So far, I think, `rustc` itself doesn't interpret any envs, does it? So it'd be new territory with its own set of problems I guess.

**Comment by alexcrichton** [comment]
Oh sorry I meant moreso the compiler sets an environment variable which `gcc` then interprets rather than the other way around. I'd personally prefer to avoid too many environment variables for the rustc compiler.

**Comment by xitep** [comment]
_"I wonder, how is one supposed to tell gcc on wheezy to use gold?"_: it seems just by installing [binutils-gold](https://packages.debian.org/wheezy/binutils-gold). `/usr/bin/ld` becomes a symlink to `/usr/bin/ld.gold`.

**Comment by xitep** [comment]
An alternative to `/etc/issue` might also be `/etc/debian_version`. But, parsing these files seems very fragile to me :/

**Comment by alexcrichton** [comment]
Hm detecting whether `ld` is a symlink and whether it points to `ld.gold` seems reasonable, but there's still a possibility that the symlink isn't there, `ld.gold` exists, and `-fuse-ld=gold` isn't accepted unfortunately

**Comment by pnkfelix** [comment]
@alexcrichton 

> That being said that's still a pretty big hit for distros because it's 2 times on all compiles, which is pretty unfortunate

Assuming we add *some* way for the user to specify "disable gold", we could issue a warning when we run gcc twice, recommending that the user change their rustc invocation (or host configuration) accordingly

**Comment by pnkfelix** [comment]
(that way it's only "2 times until user changes host configuration to disable gold usage on rustc " Which is better than 2 times always

**Comment by alexcrichton** [comment]
@pnkfelix perhaps yeah, but at that point I'd probably be more in favor of just disabling by default.

**Comment by vadimcn** [comment]
I read @xitep's comment as "those who want to use gold can simply replace ld with a symlink to it".

**Comment by birkenfeld** [comment]
Or use the distro's mechanism for switching (such as `update-alternatives` in Debian).

**Comment by alexcrichton** [comment]
Removing regression/nomination tags as this was fixed, leaving open as a reference to why we reverted ld.gold

**Comment by bstrie** [comment]
Since we're leaving this open, I've changed the title to something potentially more actionable.

**Comment by bstrie** [comment]
This is certainly part of a broader debate, but how long are we willing to support obsolete distros? Wheezy is already obsolete as of Jessie, and as of Stretch next year it will be doubly obsolete.

**Comment by xitep** [comment]
personally, i'm stuck with wheezy on a few systems for this year. regarding this particular issue, making a `rustc` wrapper as suggested by [eddyb in the original issue](https://github.com/rust-lang/rust/pull/29974#issuecomment-168182271) worked just fine for me. the only pain point was to preserve this wrapper upon updates by multirust (but that's something i'm not doing often on these systems.)

my point in a broader sense: it seems to me that supporting a platform which is merely [a few years old](https://www.debian.org/releases/wheezy/) and [is going to be supported for some more](https://www.debian.org/News/2016/20160212) makes rust an attractive alternative to other languages (in particular c++ and java.) i wouldn't be surprised if i wasn't the only one having to deal with "such old systems" in production.

**Comment by xitep** [comment]
hello, i just got aware of [RUSTFLAGS](https://github.com/rust-lang/cargo/pull/2241) which seems like a solution to my [originally reported problem](https://github.com/rust-lang/rust/pull/29974#issuecomment-168166164). given the desire to use ld.gold by default, i think it might worth considering to enable that patch now and have ppl on such old platforms use `export RUSTFLAGS="-C disable-gold"`. what do  you think?

**Comment by bstrie** [comment]
I propose that we revisit this around February 2017, since that's approximately the Stretch release date, by which point Wheezy will be even more emphatically obsolete. Which isn't to suggest that we shouldn't care about people still using Wheezy by then, but we need to prioritize the needs of the greatest proportion of our users, and gold-by-default is a significant speed win.

**Comment by sanmai-NL** [comment]
@bstrie: small update, the release date for Debian Stretch [has been set at 17 June 2017](https://wiki.debian.org/DebianStretch).

**Comment by SimonSapin** [comment]
Or is it @rust-lang/dev-tools ?

**Comment by glandium** [comment]
Note that Wheezy is going to have some extra support time. https://raphaelhertzog.com/2018/02/20/time-to-join-extended-long-term-support-for-debian-7-wheezy/

But... why does rust invoke ld through gcc anyways?

**Comment by SimonSapin** [comment]
Even if some people and companies want to keep supporting Wheezy, does that mean that recent rustc versions need to do the same?

**Comment by glandium** [comment]
Well, Firefox builds are done on Debian Wheezy at the moment...

**Comment by workingjubilee** [comment]
It's 2020.
It's time for
![the_gold_experience](https://user-images.githubusercontent.com/46493976/92313474-e7adc980-ef80-11ea-9ed0-3e18aaf2e3de.jpg)
