### ISSUE TITLE
Can't link to an external thread local symbol

### ISSUE THREAD

**Issue by mneumann** [rust-lang/rust#30795]
I am trying to link to

```c
extern __thread int errno;
```
I try it with:

```rust
extern "C" {
    #[thread_local]
    #[link_name = "errno"]
    static errno: c_int;
}
```
But it seem that it omits the ```thread_local``` part. Any ideas how to get it to work? The linker tells me that I have both thread-local and non-thread local references to ```errno``` defined, so above links to the non-thread local.

**Comment by alexcrichton** [comment]
I think this is because we don't recognize `#[thread_local]` on extern globals, for example:

```rust
#![feature(thread_local)]

extern {
    #[thread_local]
    #[link_name = "errno"]
    pub static errno: i32;
}

pub fn foo() -> i32 {
    unsafe { errno }
}
```

```llvm
; ModuleID = 'foo.0.rs'
target datalayout = "e-m:o-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-apple-darwin"

@errno = external global i32

; Function Attrs: uwtable
define i32 @_ZN3foo20h5ca9ce4ccbe13eabhaaE() unnamed_addr #0 {
entry-block:
  %0 = load i32, i32* @errno, align 4
  ret i32 %0
}

attributes #0 = { uwtable "no-frame-pointer-elim"="true" }
```

(note the lack of `thread_local` on the `extern` declaration)

**Comment by mneumann** [comment]
@alexcrichton: DragonFly would need it in order to support ```errno```. Otherwise we need a shim C wrapper again (```__dfly_error```). This was removed in some earlier commit. In my local patches I have added a rt/errno.c again, but in the long term this clearly is not the solution.

**Comment by alexcrichton** [comment]
This may actually be easy enough to add to trans, I think you'll basically need to [copy this code](https://github.com/rust-lang/rust/blob/d01ed8ad8e517e41d3e4f5a25ba926ab769d7b1b/src/librustc_trans/trans/base.rs#L250-L254) over into the [foreign module as well](https://github.com/rust-lang/rust/blob/d01ed8ad8e517e41d3e4f5a25ba926ab769d7b1b/src/librustc_trans/trans/foreign.rs#L116-L117).

It's possible that we could add back the C shim wrapper, although I'd prefer not to do so!

**Comment by mneumann** [comment]
@alexcrichton : Thanks for pointing out the solution! I have a pull request (https://github.com/rust-lang/rust/pull/30856) that fixes that. Much better than requiring a C wrapper! With that fix and some other libc related things, I can now build rust on DragonFly again.

**Comment by oskimora13** [comment]
> I am trying to link to
> 
> extern __thread int errno;
> I try it with:
> 
> extern "C" {
>     #[thread_local]
>     #[link_name = "errno"]
>     static errno: c_int;
> }
> But it seem that it omits the `thread_local` part. Any ideas how to get it to work? The linker tells me that I have both thread-local and non-thread local references to `errno` defined, so above links to the non-thread local.
