### ISSUE TITLE
Iterator is needlessly a language item

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#30803]
Iterator language item has been removed [a year ago](https://github.com/rust-lang/rust/pull/20790), but `trait Iterator` still has `#[lang = "iterator"]` on it. That’s not necessary and can be removed.

**Comment by apasel422** [comment]
Shouldn't both `IntoIterator` and `Iterator` be language items?

**Comment by GuillaumeGomez** [comment]
@apasel422: Seems more logical to remove it if it's not needed anymore than the contrary.

**Comment by apasel422** [comment]
My reasoning is that `for` depends on both traits (plus `Option`). Compiling this:

```rust
#![feature(lang_items)]
#![feature(no_core)]

#![crate_type = "lib"]

#![no_std]
#![no_core]

#[lang = "sized"]
trait Sized {}

pub fn foo() {
    for _ in () {
    }
}
```
yields
```
foo.rs:13:5: 13:9 error: failed to resolve. Maybe a missing `extern crate iter`? [E0433]
foo.rs:13     for _ in () {
              ^~~~
foo.rs:13:5: 13:9 help: run `rustc --explain E0433` to see a detailed explanation
foo.rs:13:5: 14:6 error: unresolved name `iter::IntoIterator::into_iter` [E0425]
foo.rs:13     for _ in () {
foo.rs:14     }
foo.rs:13:5: 14:6 help: run `rustc --explain E0425` to see a detailed explanation
foo.rs:13:5: 13:9 error: failed to resolve. Maybe a missing `extern crate iter`? [E0433]
foo.rs:13     for _ in () {
              ^~~~
foo.rs:13:5: 13:9 help: run `rustc --explain E0433` to see a detailed explanation
foo.rs:13:5: 14:6 error: unresolved name `iter::Iterator::next` [E0425]
foo.rs:13     for _ in () {
foo.rs:14     }
foo.rs:13:5: 14:6 help: run `rustc --explain E0425` to see a detailed explanation
foo.rs:13:5: 14:6 error: unresolved enum variant, struct or const `Some` [E0419]
foo.rs:13     for _ in () {
foo.rs:14     }
foo.rs:13:5: 14:6 help: run `rustc --explain E0419` to see a detailed explanation
foo.rs:13:5: 14:6 error: unresolved enum variant, struct or const `None` [E0419]
foo.rs:13     for _ in () {
foo.rs:14     }
```

**Comment by GuillaumeGomez** [comment]
Then why `IntoIterator` has been removed from language item?

**Comment by durka** [comment]
I think I agree with @apasel422... when for loops are desugared the absolute path to IntoIterator is used by name, but it seems like it would be more robust to use a lang item (cc #30809).

**Comment by nagisa** [comment]
> Shouldn't both IntoIterator and Iterator be language items?

I generally would agree, but making them language items would be a breaking change of sorts and discussion towards that effect should be through a RFC. Removing the `#[lang="iterator"]` attribute *now* (i.e. cleanup of stdlib) and (re-)introducing `Iterator` and `IntoIterator` language items later (so the for-loop desugaring is more resilient) are not mutually exclusive goals.

**Comment by apasel422** [comment]
@nagisa Proposed in rust-lang/rfcs#1457.

**Comment by alexcrichton** [comment]
I think it'd be fine to add these as language items to improve error messages, but in the meantime it seems fine to remove the annotation if they're not used in the compiler currently (e.g. we can add it back *very* easily at any point in the future)
