### ISSUE TITLE
Lifetime parameter is never used when used as a parameter for a type bound.

### ISSUE THREAD

**Issue by Mokosha** [rust-lang/rust#30806]
I'm not sure if this is a duplicate or if this constitutes a phantom type. However, the following behavior of the type system came as a surprise to me.

Consider the following program:

```
trait Foo<'a> {
    fn do_foo(&'a self) {
        println!("Do foo!");
    }
}

struct SomeFoo {
    id: usize
}

impl<'a> Foo<'a> for SomeFoo { }
impl SomeFoo {
    pub fn new() -> SomeFoo { SomeFoo { id: 3 } }
}

struct Bar<'a, T: Foo<'a>> {
    foo: T
}

fn main() {
    let b = Bar { foo: SomeFoo::new() };
    b.foo.do_foo();
}
```

In this example, `rustc` complains that the parameter `'a` is never used, but it certainly is in order to restrict the parametric type of `T`! This doesn't constitute a phantom type because the lifetime certainly has meaning outside of the type system in this case.

```
test.rs:16:12: 16:14 error: parameter `'a` is never used [E0392]
test.rs:16 struct Bar<'a, T: Foo<'a>> {
                      ^~
test.rs:16:12: 16:14 help: run `rustc --explain E0392` to see a detailed explanation
test.rs:16:12: 16:14 help: consider removing `'a` or using a marker such as `core::marker::PhantomData`
error: aborting due to previous error
```

If this isn't a bug, then there should be some way to infer the lifetime parameter of the `Foo` trait in this situation:

    struct Bar<T: Foo> {
      // ...
    }

That variant results in:

````
test.rs:16:15: 16:18 error: wrong number of lifetime parameters: expected 1, found 0 [E0107]
test.rs:16 struct Bar<T: Foo> {
                         ^~~
test.rs:16:15: 16:18 help: run `rustc --explain E0107` to see a detailed explanation
error: aborting due to previous error
````

and

    struct Bar<T: Foo<'a>> {
      // ...
    }

(expectedly) results in:

```
test.rs:16:19: 16:21 error: use of undeclared lifetime name `'a` [E0261]
test.rs:16 struct Bar<T: Foo<'a>> {
                             ^~
test.rs:16:19: 16:21 help: run `rustc --explain E0261` to see a detailed explanation
error: aborting due to previous error
```

**Comment by nixpulvis** [comment]
Not that this is directly related to your issue, but I wouldn't use the term "dependent type" here.

**Comment by Mokosha** [comment]
Sorry, you're right. *Parametric type* is what I meant. I've edited my post.

**Comment by bluss** [comment]
You'd run into the same thing if it were `struct Bar<U, T: Foo<U>> { foo: T }`. You need a `PhantomData` in that situation.

**Comment by arielb1** [comment]
This is not a bug.

**Comment by Mokosha** [comment]
OK, sorry about the noise. FWIW, I'd say that `U` in `struct Bar<U, T: Foo<U>> ...` is also "used".
