### ISSUE TITLE
link_section attribute can cause unsafety

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#30815]
This attribute allows items to be put into arbitrary sections which is unsafe. I'm not sure what the policy for attributes is but I recall that there are some attributes prefixed with unsafe_ because they can cause unsafety.

**Comment by GuillaumeGomez** [comment]
I don't think it changes much to add "unsafe_" as prefix but why not?

Just for the record, the feature is declared [here](https://github.com/rust-lang/rust/blob/master/src/libsyntax/feature_gate.rs#L367) in the [KNOWN_ATTRIBUTES list](https://github.com/rust-lang/rust/blob/master/src/libsyntax/feature_gate.rs#L50).

**Comment by bltavares** [comment]
Triaging: here is the updated [location](https://github.com/rust-lang/rust/blob/92e3fb3ebe6d7129ff0fe85c17f30c8669899129/src/libsyntax/feature_gate.rs#L411) on the latest master for the KNOW_ATTRIBUTES list.

**Comment by mahkoh** [comment]
This issue does not make much sense since the much more common start attribute can be used to cause segfaults via safe code much more easily.
