### ISSUE TITLE
Add a `used` attribute.

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#30817]
This attribute prevents LLVM from removing a symbol even if it can prove that the symbol is not used. This can be simulated with the following code:

```rust
#[export_name = "llvm.used"]
#[linkage = "appending"]
static mut _X: [*const u8; 1] = [&F as *const _ as *const _];
```

which prevents `F` from being removed.

**Comment by huonw** [comment]
cc https://github.com/rust-lang/rfcs/pull/1459.
