### ISSUE TITLE
Incomplete Documentation regarding ToString trait

### ISSUE THREAD

**Issue by davidbecher** [rust-lang/rust#30810]
I was just wondering, as I was looking through the Rust book I saw a function called `to_string()` associated to an error type (in this specific case `ParseIntError`) which is, however, not documented in the API.

```rust
use std::env;

fn double_arg(mut argv: env::Args) -> Result<i32, String> {
    argv.nth(1)
        .ok_or("Please give at least one argument".to_owned())
        .and_then(|arg| arg.parse::<i32>().map_err(|err| err.to_string()))
}

fn main() {
    match double_arg(env::args()) {
        Ok(n) => println!("{}", n),
        Err(err) => println!("Error: {}", err),
    }
}
```
I found the code here: https://doc.rust-lang.org/book/error-handling.html#composing-option-and-result

I looked through the documentation and neither `std::Err` nor `ParseIntError` have `to_string` listed as one of their methods. `ParseIntError`'s documentation also not states implementing the `collections::string::ToString` trait. Have I overlooked something or is the documentation actually inaccurate?

**Comment by steveklabnik** [comment]
It's because ToString is:


    impl<T> ToString for T where T: Display + ?Sized

And the error also implements Display.

**Comment by steveklabnik** [comment]
(so yeah, tough to find out about, but not a bug. We already have a number of Rustdoc issues about this kind of presentation issue, blanket impls are tough from a UX perspective.

**Comment by davidbecher** [comment]
Ah okay, thanks! ;) Yeah, but still: then rustdoc should be blamed for not making it clear in the first place.

**Comment by davidbecher** [comment]
BTW: I just had to do some digging to actually understand what

```
impl<T> ToString for T where T: Display + ?Sized
```

means. Would be nice if someone would add something in the rust book about such "blanket implementations"... ;)!

**Comment by steveklabnik** [comment]
The next iteration of the book will talk about them more explicitly, for sure :+1:
