### ISSUE TITLE
"Getting started" page in the book mentions "crates" before explaining what a crate is

### ISSUE THREAD

**Issue by K900** [rust-lang/rust#30825]
https://doc.rust-lang.org/nightly/book/getting-started.html

> With simple projects, Cargo doesn't bring a whole lot over just using rustc, but it will become useful in future. With complex projects composed of multiple **crates**, it’s much easier to let Cargo coordinate the build. With Cargo, you can just run cargo build, and it should work the right way.

The concept of crates is only (properly) introduced in the next chapter.

**Comment by Luke-Nukem** [comment]
Created [pull request](https://github.com/rust-lang/rust/pull/30836) which hopefully addresses the issue.

**Comment by steveklabnik** [comment]
This was fixed!
