### ISSUE TITLE
No link from doc.rust-lang.org to www.rust-lang.org

### ISSUE THREAD

**Issue by nodakai** [rust-lang/rust#30838]
We have no link from doc.rust-lang.org to www.rust-lang.org, and it is not good in terms of usability.  I guess this is because doc.rust-lang.org is a verbatim copy of the raw output from `rustdoc`.

See how Python documents are organized:
- https://docs.python.org/2/library/

![python-doc-hdr](https://cloud.githubusercontent.com/assets/90726/12589048/bb18dbc2-c496-11e5-989f-132c15bcebe8.png)

I think this is the relevant functionality of the Sphinx documentation tool for Python:
- http://www.sphinx-doc.org/en/stable/web/quickstart.html

We should aim for the same level of usability standard and `rustdoc` should be flexible enough to achieve it.

**Comment by GuillaumeGomez** [comment]
Generally, people come to doc.rust-lang.org from www.rust-lang.org. But that might be a good thing to add it.

**Comment by steveklabnik** [comment]
Also, I don't think this can be a rustdoc thing, because many, many rustdoc outputs are not hosted on rust-lang.org

**Comment by steveklabnik** [comment]
(Rustdoc already lets you choose where the logo links to, iiirc, but it's usually the docs rather than another site.)

**Comment by nodakai** [comment]
@steveklabnik I'm not saying rustdoc should hard-code a link to www.rust-lang.org.  If you write a Rust library and publicize its documentation, you might want a backlink from the generated HTML to www.steveklabnik.com.  I'm claiming there should be a general mechanism to realize such designs.

Thankfully rustdoc supports these command line options which seem promising:
```
    --html-in-header FILES
                        files to include inline in the <head> section of a
                        rendered Markdown file or generated documentation
    --html-before-content FILES
                        files to include inline between <body> and the content
                        of a rendered Markdown file or generated documentation
    --html-after-content FILES
                        files to include inline between the content and
                        </body> of a rendered Markdown file or generated
                        documentation
```
I'll try see how they fit my proposal.

**Comment by steveklabnik** [comment]
https://www.rust-lang.org/en-US/documentation.html now links to doc.rust-lang.org, many times 🎊

**Comment by steveklabnik** [comment]
Oh wait, this is the _inverse_ issue, sorry for the noise! There hasn't been any change here.

**Comment by steveklabnik** [comment]
Triage: https://github.com/rust-lang/rust/issues/44687 may fix this, but there's been no change

**Comment by Mark-Simulacrum** [comment]
doc.rust-lang.org redirects to https://www.rust-lang.org/learn today, but I think we probably want these links from e.g. https://doc.rust-lang.org/std/index.html as well so leaving open.

**Comment by jyn514** [comment]
Triage: this would be pretty easily fixed by modifying the index page for doc.rust-lang.org: https://github.com/rust-lang/rust/blob/master/src/doc/index.md
