### ISSUE TITLE
private_in_public lint seems like an overkill

### ISSUE THREAD

**Issue by gifnksm** [rust-lang/rust#30840]
# code
I think this code is valid because all functions that can access to `foo` are able to access to `S`.

```
mod foo {
    pub fn foo() -> ::S {
      ::S
    }
}

struct S;

fn main() {
  foo::foo();
}
```
playground: http://is.gd/6BNQkh

# output

```
<anon>:2:21: 2:24 error: private type in exported type signature [E0446]
<anon>:2     pub fn foo() -> ::S {
                             ^~~
error: aborting due to previous error
```

**Comment by petrochenkov** [comment]
If you add a reexport of `foo::foo` to the root module, then private `S` can leave its crate:

```
pub use foo::foo;

mod foo {
    pub fn foo() -> ::S {
      ::S
    }
}

struct S;

fn main() {
  foo::foo();
}
```

We do not track reexport chains and prevent leaking of private types with a simple rule, enabling local reasoning - if the function is `pub`, then its return type should be `pub` as well.
The rules may become more relaxed and more complex in the future, but these changes are not designed and not implemented yet, so the current rules are conservatively strict.
(Also, `private_in_public` is only temporary a lint, it's a strict language rule, that wasn't completely enforced before, it will become an error in the future.)

With [RFC 1422](https://github.com/rust-lang/rfcs/pull/1422) this code could be written as
```
mod foo {
    pub(crate) fn foo() -> ::S {
      ::S
    }
}

struct S;

fn main() {
  foo::foo();
}
```

**Comment by gifnksm** [comment]
I understand current rules and future plan, so this seems to be an intended behavior for now.

Thank you for the detailed answer.
