### ISSUE TITLE
unused-extern-crates causes false positive with macro_use

### ISSUE THREAD

**Issue by Ms2ger** [rust-lang/rust#30849]
For example, it warns for `bitflags`/`lazy_static` even when those macros are used in the crate.

**Comment by alexcrichton** [comment]
This is why the lint is allow-by-default, it's got false positives

**Comment by Ms2ger** [comment]
Sure, but that doesn't mean some of them can't be fixed.

**Comment by zwn** [comment]
Is this the right place to look at?
https://github.com/rust-lang/rust/blob/master/src/librustc_resolve/check_unused.rs

**Comment by SimonSapin** [comment]
On IRC about this:
> @eddyb: s/false positives/macros aren't integrated with name resolution yet/

**Comment by eddyb** [comment]
It's actually possible to silence the error by adding `#[no_link]` to the macro-only `extern crate bitflags;` (which is what `librustc` does), effectively removing `bitflags` from the scope.

If/when we move name resolution earlier and use it during macro expansion, the macro will actually be imported through the `bitflags` name and the warning wouldn't get triggered.

**Comment by Ms2ger** [comment]
#39060 improved this.

CC @jseyfried

**Comment by jseyfried** [comment]
@eddyb 
> If/when we move name resolution earlier and use it during macro expansion, the macro will actually be imported through the bitflags name and the warning wouldn't get triggered.

Now that macro modularization is implemented, this is true today!

> adding `#[no_link]` to the macro-only `extern crate bitflags;` effectively [removes] bitflags from the scope.

For the record, this changed in #37247 to support `use` macro imports from `#[no_link]` crates.
