### ISSUE TITLE
https://doc.rust-lang.org/book/index.html gives a `Secure Connection Failed` error in Firefox DevEdition.

### ISSUE THREAD

**Issue by bwinton** [rust-lang/rust#30857]
The "http://" version works, and both versions work in Firefox Release.

(Apologies if this is in the wrong repo!)

**Comment by ollie27** [comment]
Is this the same as #29669? i.e. do you have `security.tls.version.max` in `about:config` set to 1 or something other than 3?

**Comment by bwinton** [comment]
Ah, apparently I did, although I don't remember changing it, or why I would.  Reverting that back to the default fixes it for me.  Thanks!

**Comment by Gankro** [comment]
Closing as dupe, have a great day!
