### ISSUE TITLE
Setting process env vars with interior nuls leads to unexpected env for child

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang/rust#30862]
[Noticed by @talchas](https://github.com/rust-lang/rust/issues/30858#issuecomment-171048969) when discussing #30858.

The environment variables are never checked for interior nuls. This leads to very unexpected results in the child's env. Keys with interior nuls are truncated and have no values, and values are truncated at the nul:

```
use std::process::Command;

fn main() {
    Command::new("/usr/bin/env").env("a\0b", "c\0d")
                                .env("ab", "c\0d")
                                .status()
                                .unwrap();
}
```
([playground](http://is.gd/swL9IL))

Output:
```
a
ab=c
USER=rust
HOME=/home/rust
PATH=/usr/local/bin:/usr/bin:/bin
LOGNAME=rust
PWD=/home/rust
```

**Comment by kamalmarhubi** [comment]
As with #30858, it's probably best to validate when spawning the child, so that the error can be returned in a `Result`.

**Comment by nagisa** [comment]
The underlying issue in both cases is that `OsString` allows interior nulls, while neither POSIX-y nor Windows systems support that use-case at all.

cc @alexcrichton

**Comment by kamalmarhubi** [comment]
Yeah, conversion to `CString` at spawn would be the right thing to do.

**Comment by kamalmarhubi** [comment]
I have a patch in the works for this.
