### ISSUE TITLE
Custom target files don't support (pre|post)_link_objects_(dll|exe)

### ISSUE THREAD

**Issue by lilred** [rust-lang/rust#30868]
I'm writing a target file for code that runs on the Xen hypervisor. In order to produce executable binaries, I need cargo to link with a bootloader object file. However, when producing static libraries etc., linking against this bootloader object is liable to cause all sorts of problems. I'd like to use the `pre_link_objects_exe` field of `TargetOptions` to link against the bootloader.

The fix seems like it would be simple: simply add a few `key!` calls in `librustc_back/target/mod.rs`.

I would really appreciate if this change was made, I could then publish a fully working Xen target :)

**Comment by steveklabnik** [comment]
Triage: not aware of any changes here

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/71769.
