### ISSUE TITLE
Problems with The Book, suggested fixes

### ISSUE THREAD

**Issue by donaldcallen** [rust-lang/rust#30880]
In 5.1: Variable Bindings/Type Annotations, there is a sentence that reads "If it can figure out what the type of something is, Rust doesn’t require you to actually type it out.." I don't think it's a good idea to use the word "type" with two entirely different meanings in the same sentence, particularly in a section about types! My suggestion: "If it can figure
out what the type of something is, Rust doesn’t require you to specify the type explicitly."

In 5.10: Mutability, there is the following:

"When a binding is mutable, it means you’re allowed to change what the binding points to. So in the above example, it’s not so much that the value at x is changing, but that the binding changed from one i32 to another.

If you want to change what the binding points to, you’ll need a mutable reference:"

The first paragraph says that you need a mutable binding to "change what the binding points to". The second paragraph says you need a mutable REFERENCE to "change what the binding points to". These cannot both  be correct. I think the first paragraph is wrong. I think the first sentence should read "When a binding is mutable, it means you’re allowed to change what the binding contains."

**Comment by donaldcallen** [comment]
4.8 References and Borrowing, in the subsection '&mut references'. It is trying to
explain why the mutable borrow needs to be in a block, a restricted
scope, the reason being that 'println!("{}", x);' creates an immutable
borrow of 'x'. But we've been taught earlier that borrows
are references, pointers, and look like '&x'. So what the hell is
going on here? To understand this, you have to realize that

a. println! is a macro, not a function, the section on which appears
much later in the book, and
b. println!'s *expansion* contains an immutable borrow of 'x'.

This is a very poor example and should be replaced by something that explicitly creates an immutable borrow.

**Comment by steveklabnik** [comment]
Thanks for this, @donaldcallen ! I am mostly working on the second draft of the book these days, which will also fix a lot of the the things you bring up here. The question is, how much do I want to go back and fix this stuff, slowing down the new work... I will give it some thoughts. A lot of this could be easy, but some of it might be hard.

**Comment by donaldcallen** [comment]
My personal opinion is that priority should absolutely be given to the second draft. I would not slow that work down by trying to fix the original.

I will continue, as the occasion arises, to add to this issue. My purpose is to try to help you with the second draft by pointing out places that I think are incorrect or unclear in the original.

**Comment by steveklabnik** [comment]
Great! That in and of itself is very, very helpful.

**Comment by donaldcallen** [comment]
Years ago, I worked for Bert Sutherland at Bolt Beranek and Newman. Bert is one of the great men in the last 50 or 60 years of Computer Science (see https://en.wikipedia.org/wiki/Bert_Sutherland). Bert once said to me "Computer programs are like waffles; you always throw the first one away". I think that applies to technical documentation as well.

**Comment by donaldcallen** [comment]
Section 4.9, Lifetimes, is completely incomprehensible to me. It never defines the meaning of

fn foo<'a>(...). Does that mean 'a' is the name of the lifetime of foo? If so, then why would you ever write foo<'a,'b>(...), since a and b would be different names for the same lifetime. This section needs to explain *clearly* the semantics of the notation and it does not.

This is one of my most frustrating encounters with this book, because I am trying, in the course of learning Rust, to get a test program working that does some calling out to C (to access a sqlite database). I'm getting complaints from the Rust compiler about the lifetimes of references and to fix these, I need to understand this section and simply cannot. I will continue re-reading it to try to tease what I need from it, but good documentation should not require this kind of effort, particularly from someone who has done this stuff as long and as extensively as I have.

**Comment by steveklabnik** [comment]
Yeah, this whole bit is being _entirely_ re-written. Currently on ownership, and borrowing, hoping to have a draft of lifetimes up soon.

**Comment by donaldcallen** [comment]
Section 4.10, Borrow and AsRef: This section has so many problems, I hardly know where to begin.

Let's start with the fact that it talks about traits, which haven't yet been discussed in the Book and so aren't defined yet. I think forward references like these should not be used, especially in a tutorial.

The major problem is that the section simply doesn't adequately explain what Borrow does, what AsRef does, and what the difference is. It tries, but fails. The issues are similar to the Lifetime section. The writing is incomprehensible and does not make the key points clearly.

I must say that I'm about at the point of giving up on Rust until the documentation improves. A language this complex is unusable unless adequately explained and it simply is not there at this point.

**Comment by steveklabnik** [comment]
> which haven't yet been discussed in the Book and so aren't defined yet

To be clear, "Effective Rust" is intended to be read after you have a handle on the language. The ordering of the sections has a weird history, and in fact, is re-arranged on beta.

**Comment by donaldcallen** [comment]
Yes, the ordering is completely mis-leading. If you are expected to "have a handle on the language" when reading "Effective Rust", that section should appear after the sections that purport to give you that handle. Having said that, I *do* have something of a handle on the language and I still can't make any sense of the Borrow and AsRef section. The problem is more than just the ordering. It's the clarity, or lack thereof, of the writing. I'm sorry to be blunt, but this is a serious problem that has cropped up in a number of places (I already mentioned the Lifetime section, which exhibits the same problem).

**Comment by steveklabnik** [comment]
Yeah, this is why the book is being re-written.

**Comment by Zteve** [comment]
With reference to the [borrowing section on mutable references](https://doc.rust-lang.org/book/references-and-borrowing.html#mut-references) I suggest something like the following example instead:
```rust
fn main() {
    let x = 5;
    let y = &mut x;
    *y += 1;
    take(&x);
}
fn take(v: &i32){}
```
which gives the same error, followed by a correction:
```rust
fn main() {
    let mut x = 5;
    { let y = &mut x;
      *y += 1;
    }
    take(&x);
}
fn take(v: &i32){
    println!("v is {}", v);
}
```
So that the macro/function issue is avoided. (The use of `println!` in the function `take` can be explained because of the error you get if you don't use `v` in the function.)

I'm currently writing my own notes in these areas to help to clarify concepts to myself.

**Comment by steveklabnik** [comment]
Quoting myself from a while ago:

> I am mostly working on the second draft of the book these days, which will also fix a lot of the the things you bring up here. The question is, how much do I want to go back and fix this stuff, slowing down the new work... I will give it some thoughts. A lot of this could be easy, but some of it might be hard.

At this point, we have the second edition of the book in-tree. https://github.com/rust-lang/book is where the work is being done. We're accepting minor PRs for the first edition, but not tracking issues. As such, I'm going to give this a close. Please send in small PRs if you still care, and please feel free to open individual issues for problems with the second edition. Thank you!

**Comment by Zteve** [comment]
This is entirely reasonable. I'm reading the second edition (I found this recently, but didn't know about it beforehand) and enjoying it immensely.  However, it petered out just when it got interesting!

More power to you.
