### ISSUE TITLE
Add flag to allow running both ignored and not ignored tests

### ISSUE THREAD

**Issue by numerodix** [rust-lang/rust#30927]
This is the set of command line options for debug builds:

```
Options:
    --ignored           Run ignored tests
    --test              Run tests and not benchmarks
    --bench             Run benchmarks instead of tests
    -h --help           Display this message (longer with --help)
    --logfile PATH      Write logs to the specified file instead of stdout
    --nocapture         don't capture stdout/stderr of each task, allow
                        printing directly
    --color auto|always|never
                        Configure coloring of output: auto = colorize if
                        stdout is a tty and tests are run on serially
                        (default); always = always colorize output; never =
                        never colorize output;
```

I'm proposing to extend this with an `--all` flag that allows running all tests, both those selected by `--test` and those selected by `--ignored`.

There can be different reasons why a test is relegated to `ignored` status:
1. It could be that the test is not currently passing, but there are plans to fix it later.
2. It could be that the test is slow to run, and marking it `ignored` excludes it from the default test set and makes running the test suite faster.
3. And other reasons beyond...

In case (2) it may still be desirable to select all tests to be executed in a context where test running time is less impactful to a human (eg. in CI).

Currently, in order to run all tests and return a global pass/fail for the test suite it requires sequencing invocations of the binary in a shell script. This is not a major issue, however when tests are run under coverage or via something like `cargo test` it becomes less convenient to execute both sets of tests.

Adding an `--all` flag simply makes it slightly more ergonomic in my view.

The proposed `--all` flag would override any other test selection, such that:
- `--all` would select all tests.
- `--test --all` would select all tests.
- `--ignored --all` would select all tests.
- `--test` would select only non-ignored tests (as now).
- `--ignored` would select only ignored tests (as now).

I have implemented this on a [branch](https://github.com/numerodix/rust/commits/tests-all-switch). If you think this is a good idea please advise on next steps.

**Comment by numerodix** [comment]
Maybe I need to add a name in the ticket? @huonw would you mind?

**Comment by nicokoch** [comment]
I like this a lot, makes fixing currently failing tests (that are ignored so the builds pass) a LOT more convenient.

**Comment by steveklabnik** [comment]
Triage: there's been no comments on this issue in two and a half years; we're also pursuing custom test runners, and that would likely fix this issue. As such, I don't think this is very likely to be implemented directly. Closing!
