### ISSUE TITLE
macro future-proofing regression: `$a:ty [ b ]` is now rejected

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#30923]
(spawned off of https://github.com/rust-lang/rust/issues/25658#issuecomment-171452478 )

macro future-proofing regression: `$a:ty [ b ]` is now rejected

This was indeed a direct consequence of the rules as stated in https://github.com/rust-lang/rfcs/pull/1384

But since we may want to fix one-off cases like this, I am opening a separate issue and marking it as a regression.

**Comment by pnkfelix** [comment]
cc https://github.com/rust-lang/rust/issues/30450

**Comment by pnkfelix** [comment]
cc @nikomatsakis @retep998

**Comment by LeoTestard** [comment]
As of 1.8.0, the following macro compiles on stable:

```
macro_rules! foo(
	($a:ty [ $b:ident ]) => ()
);
```

I think this issue can be closed.
