### ISSUE TITLE
Error reporting for trait failures should give backtrace

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#30976]
Now that https://github.com/rust-lang/rust/pull/30533 has landed, we can change how we report trait errors to give a complete backtrace. In fact, I suspect the most intuitive thing would be to start from the root obligation and print _that_, and then show the chain of reasoning which ultimately failed. For example, if we had `Vec<Box<Foo>>: Debug` and it turns out that `Foo: ?Debug`, then we would print something like:
- `Vec<Box<Foo>>: Debug` does not hold
  - impl from stdlib for `Vec` does not apply because `Box<Foo>: Debug` does not hold:
  - impl from stdlib for `Box` does not apply because `Foo: Debug` does not hold:
  - no impl of `Debug` for `Foo` found

As part of this, we will want to (I think) change how we assign "causes" to the subobligations. Currently, we propagate the cause of the root obligation. I think what we want to do instead is to assign a cause that indicates the impl whence the subobligation was created. That way, when printing the backtrace, we can walk through the impls and show them to the user.

PS, I know there is a duplicate of various existing bug reports. I didn't really look, but we should try to gather up all the various examples into one master bug. Perhaps this one?

cc @aturon @arielb1

**Comment by aturon** [comment]
I'd like to take this on, but wanted to check in with @arielb1 -- were you thinking of doing this?

**Comment by arielb1** [comment]
I will try to do it today.

**Comment by GuillaumeGomez** [comment]
Any news on this?

**Comment by golddranks** [comment]
If I understand this issue correctly, it would help for the error messages to "bridge the gap" in problems like this: https://www.reddit.com/r/rust/comments/417s0f/question_about_generics_and_api_declarations/cz0cyse

My question is: is there any similar diagnostic feature planned for backtracing lifetime obligations? I recently saw a problem where such an error message would've been very helpful:
https://www.reddit.com/r/rust/comments/49414d/reference_must_be_valid_for_the_static_lifetime/d0pgtos

**Comment by steveklabnik** [comment]
Triage: this seems like a huge feature. @nikomatsakis is there any possibility of something like Chalk making this feasible?

**Comment by arielb1** [comment]
@steveklabnik 

I think we give trait error backtraces for quite some time, but they are somewhat badly-formatted, so this is somewhat of a diagnostic issue.

**Comment by estebank** [comment]
I believe that the current output of `ObligationCause`s fulfills the original request of this ticket.

**Comment by estebank** [comment]
I still believe this is done. Closing.
