### ISSUE TITLE
In rust book, error handling refactoring example changes result

### ISSUE THREAD

**Issue by kimroen** [rust-lang/rust#30984]
https://doc.rust-lang.org/book/error-handling.html#composing-option-and-result

This whole thing is really great, but after the changes in this particular section, the example program goes from doubling the provided number to just spitting back out the number it got (albeit now with excellent error handling along the way).

The name of the function (`double_arg`) indicates that the doubling should happen in there, and I'm actually not quite sure where it would make sense to put it, while maintaining the point of the section (showing off `ok_or` and `map_err`).

A copy of the program I'm talking about, for convenience:

```rust
use std::env;

fn double_arg(mut argv: env::Args) -> Result<i32, String> {
    argv.nth(1)
        .ok_or("Please give at least one argument".to_owned())
        .and_then(|arg| arg.parse::<i32>().map_err(|err| err.to_string()))
}

fn main() {
    match double_arg(env::args()) {
        Ok(n) => println!("{}", n),
        Err(err) => println!("Error: {}", err),
    }
}
```

**Comment by fhartwig** [comment]
I think the problem you're talking about has been fixed in https://github.com/rust-lang/rust/pull/30053
It's already fixed in the docs for beta and nightly, we just have to wait until the current beta gets promoted to stable.

**Comment by kimroen** [comment]
@fhartwig Yeah, looks like it! Thanks for the pointer.

**Comment by steveklabnik** [comment]
Closing since it was fixed.
