### ISSUE TITLE
ICE: unexpected panic at Option::unwrap()

### ISSUE THREAD

**Issue by ljedrz** [rust-lang/rust#30995]
Hello,

I tried to run the following code (reduced case, still causes the ICE):

```rust
extern crate xml;

use xml::reader::{EventReader, XmlEvent};
use xml::namespace::Namespace;

fn main() {

}

fn inerpret_xpath(xpath: &str) -> Vec<(XmlEvent::StartElement)> {
    let steps: Vec<&str> = xpath.split('/').collect();
    let elems: Vec<(XmlEvent::StartElement)> = Vec::new();

    for step in steps {
        let elem = XmlEvent::StartElement {
            name: "derp".from_str(),
            attributes: Vec::new(),
            namespace: Namespace::empty()
        };
        elems.push(elem);
    }
}
```
But received the following error (cargo run --verbose):

       Fresh bitflags v0.4.0 (file:///C:/Local/poligon/rust/bitflags)
       Fresh xml-rs v0.3.0 (file:///C:/Local/poligon/rust/xml-rs)
   Compiling xml_extractor v0.1.0 (file:///C:/Local/poligon/rust/xml_extractor)
     Running `rustc src\main.rs --crate-name xml_extractor --crate-type bin -g --out-dir C:\Local\poligon\rust\xml_extractor\target\debug --emit=dep-info,link -L dependency=C:\Local\poligon\rust\xml_extractor\target\debug -L dependency=C:\Local\poligon\rust\xml_extractor\target\debug\deps --extern xml=C:\Local\poligon\rust\xml_extractor\target\debug\deps\libxml-25aaede7b8a84d1e.rlib`
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore\option.rs:366

The backtrace:

   Compiling xml_extractor v0.1.0 (file:///C:/Local/poligon/rust/xml_extractor)
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore\option.rs:366
stack backtrace:
   0:         0x6ff00e07 - strncmp
   1:         0x6ff08538 - strncmp
   2:         0x6fec537c - strncmp
   3:         0x6fec5aeb - strncmp
   4:         0x6fefe022 - strncmp
   5:         0x6ff23c68 - strncmp
   6:         0x6ff1e0c0 - strncmp
   7:         0x6dd0b7ef - strncmp
   8:         0x6dcd4df3 - strncmp
   9:         0x6dcd490b - strncmp
  10:         0x6dd16838 - strncmp
  11:         0x6dd1648b - strncmp
  12:         0x6dd13ef9 - strncmp
  13:         0x6dcd2fd9 - strncmp
  14:         0x6dd1de8c - strncmp
  15:         0x6dd09f66 - strncmp
  16:         0x6dcd4df3 - strncmp
  17:         0x6dd1a55e - strncmp
  18:         0x6dd23055 - strncmp
  19:         0x6dd45f14 - strncmp
  20:         0x6dd3e0a5 - strncmp
  21:         0x6dd28cc2 - strncmp
  22:         0x6dd25836 - strncmp
  23:         0x6dd6ee3a - strncmp
  24:         0x6e506ff4 - strncmp
  25:         0x6e4ea4de - strncmp
  26:         0x6e4e5f38 - strncmp
  27:         0x6e4c317c - strncmp
  28:         0x6e62efb7 - strncmp
  29:         0x6e62becc - strncmp
  30:         0x6fef1401 - strncmp
  31:         0x6e62c3a1 - strncmp
  32:         0x6ff06dbd - strncmp
  33:         0x777a59dc - strncmp

## Meta

`rustc --version --verbose`:

rustc 1.5.0 (3d7cd77e4 2015-12-04)
binary: rustc
commit-hash: 3d7cd77e442ce34eaac8a176ae8be17669498ebc
commit-date: 2015-12-04
host: x86_64-pc-windows-gnu (Windows 7 to be exact)
release: 1.5.0

**Comment by mitaa** [comment]
Dup of #30535
(`XmlEvent::StartElement` is a enum struct-variant, but is used here as a type, instead of just `XmlEvent`)
