### ISSUE TITLE
Inlined code has wrong filepaths in debug info

### ISSUE THREAD

**Issue by vadimcn** [rust-lang/rust#30993]
Here's an example llvm-dwarfdump'ed from a rust executable:

```
0x000002bf:           DW_TAG_formal_parameter [7]  
                        DW_AT_location [DW_FORM_exprloc]    (<0x2> 91 70 )
                        DW_AT_name [DW_FORM_strp]   ( .debug_str[0x00003066] = "f")
                        DW_AT_decl_file [DW_FORM_data1] ("c:\testcrate\../src/libcore\fmt\mod.rs")
                        DW_AT_decl_line [DW_FORM_data1] (194)
                        DW_AT_type [DW_FORM_ref4]   (cu + 0x35ed => {0x000035ed})
```

(c:\testcrate is the location of my crate)

I am not sure what path should be emitted there (given that stdlib may have been compiled on a different machine), but what we have now is clearly not correct.

**Comment by Mark-Simulacrum** [comment]
I think this is still an issue. The following command returns no output (and rustc-perf being https://github.com/rust-lang-nursery/rustc-perf). However, macros still report the wrong location (e.g., `..._decl_file [DW_FORM_data1]	("/home/mark/rustc-perf/<panic macros>")`). It's possible this is an indication of a problem specific to macros, or that the overall issue is still a problem, and I just don't have any specific code that gets inlined from libcore/libstd.

```
llvm-dwarfdump target/debug/rustc-perf > t
rg DW_AT_decl_file t | rg -v '"/check' | rg -v 'DW_FORM_data1$' | rg -v '.[hc]"' | rg 'rustc-perf/' | rg -v '<.*macros>' | rg -v 'debug/build/backtrace-' | rg --replace '' '^.*DW_AT' | rg -v '"/home/mark/rustc-perf/src/(api|lib|server|util|date|load|git|main).rs"'
```

**Comment by steveklabnik** [comment]
Triage: not aware of any changes here

**Comment by wesleywiser** [comment]
Visited during wg-debugging triage. Experimentally, this issue appears to have been resolved. We think these test cases probably cover the original reported issue so we are closing this as already resolved:

- https://github.com/rust-lang/rust/blob/356c651e6d013fe9ca1d47da278ba208a95dbcf9/tests/run-make/remap-path-prefix-dwarf/Makefile
- https://github.com/rust-lang/rust/blob/0ac9ca4f88c03e6fc507ab8937573dca1ccfd2ed/src/test/codegen/remap_path_prefix/issue-73167-remap-std.rs
