### ISSUE TITLE
internal compiler error: unprintable span

### ISSUE THREAD

**Issue by rillian** [rust-lang/rust#31011]
Trying to access a struct member from a macro inside a parameterized closure, I get:

```
src/lib.rs:407:26: 266:22 error: attempted access of field `trace` on type `&mut C`, but no field with that name was found
(internal compiler error: unprintable span)
src/lib.rs:407:21: 407:95 note: in this expansion of log! (defined in src/lib.rs)
```

The code may well be wrong, but I thought the internal compiler error was worth reporting.

**Comment by rillian** [comment]
Code showing the issue is available at https://notabug.org/rillian/mp4parse-rust/src/issue-31011

I see this with both 1.5 stable and 17 nightly.

cc @Gankro

**Comment by rillian** [comment]
Here's a simpler example: https://play.rust-lang.org/?gist=fd7e6bbc22a85d299bdd

**Comment by rillian** [comment]
And an even simpler one:  https://play.rust-lang.org/?gist=8d172764fd95ff346bed

**Comment by rillian** [comment]
The ICE does _not_ occur without the macro. This prints the compile error cleanly: https://play.rust-lang.org/?gist=7459e2ba9918ba9e56c1

**Comment by wesleywiser** [comment]
It seems that this happens when the span the compiler wants to print out starts in one location and ends in another (for example, starts in a macro expansion but ends in the actual program input). See these related issues #29084, #28308, #25385, #28288.
