### ISSUE TITLE
Implement `LinkedList::reverse`

### ISSUE THREAD

**Issue by apasel422** [rust-lang/rust#31016]
`LinkedList` can reverse its nodes in `O(n)` time with no additional allocation.

**Comment by Gankro** [comment]
Does anyone actually need/want this?

**Comment by apasel422** [comment]
@Gankro Eh, maybe not. This can just be built atop `IterMut` anyway.

**Comment by Gankro** [comment]
Seems pretty marginal, then. Only diff is whether moving elements or pointers is cheaper.

Anyway, this would need to be filled against RFCs anyway, I think.
