### ISSUE TITLE
compiler-rt may build x86_64 libraries for --build-i686-pc-windows-msvc

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#31021]
With following configure options (using cmake):

```
./configure --build=i686-pc-windows-msvc --host=x86_64-pc-windows-msvc --enable-optimize
```

the build will fail with `cp: cannot stat 'i686-pc-windows-msvc/rt/compiler-rt/lib/windows/Release/clang_rt.builtins-i386.lib`. Instead of i386 version, a x86_64 one exists instead.

**Comment by nagisa** [comment]
An interesting warning that has popped up during configuration of the compiler-rt:

```
Manually-specified variables were not used by the project:
    CMAKE_BUILD_TYPE
```

**Comment by alexcrichton** [comment]
Make's gone now, so closing.
