### ISSUE TITLE
`--enable-debuginfo` does not enable LLVM debug info

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#31033]
According to [this code](https://github.com/rust-lang/rust/blob/84157dbd4c7420e3e5b4dd22e4ff244889aa6275/configure#L1468) we only enable LLVM debug-info when `--disable-llvm-optimize` is set. We should also enable LLVM debug info when `--enable-debuginfo` is set.

**Comment by KalitaAlexey** [comment]
What you suggest to do if I need rust debug info, but not need LLVM debug info?

**Comment by frewsxcv** [comment]
Sort of related https://github.com/rust-lang/rust/issues/24840

**Comment by mrhota** [comment]
For future travelers, I came here after reading @nnethercote's blog post about perf testing and profiling: https://blog.mozilla.org/nnethercote/2016/10/14/how-to-speed-up-the-rust-compiler/

At the end he mentioned treating LLVM like a black box because he didn't yet know how to enable debuginfo in LLVM itself. Well, it looks like @nagisa's comment resolves that mystery. Except it looks like the option is actually called `--disable-optimize-llvm`.

**Comment by Mark-Simulacrum** [comment]
That option sounds like it disables optimizations, though...

**Comment by mrhota** [comment]
@Mark-Simulacrum Indeed. And in fact, you can `--enable-optimize` and `--enable-debug` for `rustc`

Perhaps bundling up LLVM debuginfo with LLVM optimization is no good.

Maybe `--disable-optimize-llvm` should merely disable optimized LLVM, and user should specify `--enable-llvm-debuginfo` independently if desired.

**Comment by mrhota** [comment]
In `configure`, it looks like `CMAKE_BUILD_TYPE=RelWithDebInfo` corresponds to `--enable-optimize-llvm` and the hypothetical `--enable-llvm-debuginfo` while `CMAKE_BUILD_TYPE=Debug` corresponds to `--disable-optimize-llvm`.

**Comment by nnethercote** [comment]
Should we file a new issue to make it easier to build LLVM with optimizations and debuginfo?

**Comment by mrhota** [comment]
@nnethercote I intended to issue a PR referring here, but I'll defer to your judgment.

**Comment by nnethercote** [comment]
Oh, if you have a PR there's no need for a separate issue. Thank you for doing it!

**Comment by mrhota** [comment]
Oh, I think I just misunderstood your intention, given the title of this issue is slightly broader in intent than the conclusion I came to with my PR. Well, I'm not sure how to dispose of the two issues. Close this one, maybe?

**Comment by mrhota** [comment]
@nagisa I added support for llvm debuginfo in a release build via a specific build option in #37742. This issue might be obsolete now. Want to close it?

**Comment by nagisa** [comment]
Yeah, that PR seems good enough of a fix.
