### ISSUE TITLE
lookup_host reading uninitialized memory?

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#31044]
`std::net::lookup_host` (which is used by `impl ToSocketAddrs for str` among others) calls `getaddrinfo` with NULL for its `const char* service` parameter. The man page for getaddrinfo says:

> If service is NULL, then the port number of the returned socket addresses will be left uninitialized.

Yet `lookup_host` reads that field when creating a `SocketAddr`.

Reading the source code of glibc and musl, they both seem to default to a well-initialized zero, at least in their latest git commit. I don’t know if this bit of man page means that the port number can ever be uninitialized as in "reading uninitialized memory is undefined behavior".

**Comment by alexcrichton** [comment]
I'd be fine just defaulting the port to 0 or something like that to paper around this.

**Comment by SimonSapin** [comment]
(I think that `lookup_host` should return an iterator of `IpAddr` rather than `SocketAddr` as long as it doesn’t take a `service` argument, but that’s almost a separate issue. And I think that the `service` argument wouldn’t be useful.)

**Comment by steveklabnik** [comment]
Triage: the code for this lives in `.\src\libstd\sys_common\net.rs`, but has yet to be updated.

**Comment by Mark-Simulacrum** [comment]
AFAICT, this seems to no longer be the case, though I can't find the commit that made it no longer the case. In particular, https://github.com/rust-lang/rust/blob/fba38ac27e2ade309f4c2504a6d6cd3556972a28/src/libstd/sys_common/net.rs#L194-L198 no longer appears to read the port from uninitialized memory...
