### ISSUE TITLE
Concurrency example in TRPL is not obvious/convincing

### ISSUE THREAD

**Issue by matklad** [rust-lang/rust#31047]
This is the example of a racy code used in [shared state](https://doc.rust-lang.org/book/concurrency.html#safe-shared-mutable-state) section:

```Rust
use std::thread;

fn main() {
    let mut data = vec![1, 2, 3];

    for i in 0..3 {
        thread::spawn(move || {
            data[i] += 1;
        });
    }

    thread::sleep_ms(50);
}
```

The first problem with the example is that the race condition is not obvious ([proof](https://users.rust-lang.org/t/question-about-concurrency-example-in-rust-book/4365)).

The second problem is that in reality you'd better avoid indices here, and use a combination of iterators and scoped threads to solve the problem without any locks and Arcs (like [here](https://gist.github.com/matklad/5327876d6e9ae400361e#file-libs-rs-L13-L26)).

I think this example is better:

```Rust
use std::thread;

fn main() {
    let mut data = vec![];

    for i in 0..3 {
        thread::spawn(move || {
            data.push(i)
        });
    }

    thread::sleep_ms(50);
}
```

**Comment by steveklabnik** [comment]
I would accept a PR to change the example, but I'm focusing my time on the new draft of the book, which doesn't use this text at all. So I'm going to give this issue a close, but feel free to submit a PR changing it if you care about this a lot!
