### ISSUE TITLE
Escaped HTML present in doc comments gets rendered in search results

### ISSUE THREAD

**Issue by jdm** [rust-lang/rust#31059]
By escaped, I mean stuff like
```rust
/// stuff for `<iframe>`
```
which renders fine in non-search listings (it looks like `<iframe>`, instead of a literal iframe element on the page).

**Comment by steveklabnik** [comment]
I thought we had an issue for this, but cannot find it.

**Comment by frewsxcv** [comment]
Relevant to inline summary rendering: https://github.com/rust-lang/rust/issues/25787

**Comment by mitaa** [comment]
Search result descriptions aren't markdown rendered and read/written unaltered from the search-index to the page.

*Should* these descriptions be markdown rendered or html escaped (#18419)?
