### ISSUE TITLE
provide on_unimplemented hint for ops::Index

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#31062]
As discussed on IRC. cc @steveklabnik 

If you do `slice[2i32]` you get an error that tells you what is wrong (`Index<i32>` is not implemented for `[T]`) but not how to fix it (slices are indexed by usize). A quick fix would be to use `#[rustc_on_unimplemented]`; it would look [like this](http://is.gd/Wei0AV).

If you are indexing something that isn't `[T]` then the message would be a false positive.

**Comment by GuillaumeGomez** [comment]
It looks like fun, I take it.

**Comment by durka** [comment]
Fixed by #33401.

**Comment by pnkfelix** [comment]
PR #33491 is going to regress this issue; reopen when it lands

**Comment by arielb1** [comment]
@pnkfelix 

No it's not. It is going to give the same error message on ranges (which is debatable), but it will give the correct error message with slices.

**Comment by GuillaumeGomez** [comment]
@arielb1: This feature isn't just for ranges and slices. So for now, this is a regression.

**Comment by pnkfelix** [comment]
@arielb1 I inferred that something regressed from the fact that you removed one of unit tests in #33491, but I guess I am not clear on how much of a regression occurred.
