### ISSUE TITLE
Warn on non-derived Clone impl on Copy types?

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#31086]
From https://github.com/rust-lang/rust/issues/27750#issuecomment-173670142
> a Clone impl can diverge from the Copy one (because Clone is manually done)

This sounds bad, maybe?

Should we have a lint that warns in this case? Maybe even make it an error after a while?

Sort of related: #31085

**Comment by sfackler** [comment]
There are cases where you can't rely on the derived versions (the bounds may be overly conservative for example), but warning when one of the impls is derived an the other is not may be doable?

**Comment by alexcrichton** [comment]
I would not want a lint for something like this personally as there are types that are `Copy` but not `Clone` (unfortunately), such as:

* Large fixed-size arrays
* Many kinds of function pointers
* Large tuples I believe

I think this is a compiler bug kinda but it's unfortunately what we have today. This means that `#[derive(Clone, Copy)]` is not always possible if `#[derive(Copy)]` is present.

**Comment by SimonSapin** [comment]
@sfackler Is there a case like that where you also have `Copy`?

@alexcrichton If this is a lint, `#[allow(…)]` can be used in these case which will hopefully become more rare as we fix compiler bugs/limitations.

**Comment by sfackler** [comment]
`struct Foo<T>(PhantomData<T>)` is one case where you could want an unconditional impl of Copy and Clone for all `T`, not just `T: Clone`.

**Comment by alexcrichton** [comment]
@SimonSapin indeed! My personal opinions on lints is to be **far** more restrictive to the point that if I ever have to write `#![allow]` at all I would rather the lint not exist (e.g. false positives in my opinion kill the usefulness of the lint).

Either way, however, that's just my personal opinion, and I don't want to digress this issue to talking about lines, I mainly just wanted to point out that such a lint would indeed have false positives (including the cases that @sfackler is mentioning)

**Comment by SimonSapin** [comment]
Alright, that’s fair enough. Maybe this lint would belong in Clippy more than rustc? CC @Manishearth

**Comment by Manishearth** [comment]
Yes, this makes sense, we just got a PR for a similar lint for Hash/PartialEq

**Comment by Manishearth** [comment]
cc @mcarton

**Comment by steveklabnik** [comment]
Closing since this has been implemented in Clippy.
