### ISSUE TITLE
#[derive(Clone)] should rely on Copy when possible

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#31085]
When a type that is also `Copy` has `#[derive(Clone)]`, the derived implementation should be:

```rust
    fn clone(&self) -> Self { *self }
```

From https://github.com/rust-lang/rust/issues/27750#issuecomment-173673691
> As the example in https://github.com/rust-lang/rust/issues/27750#issuecomment-162710779 shows, even when a composite type like Composite is Copy, its clone implementation may be less efficient than its Copy impl, due to copying fields individually instead of as a block.

Maybe being `Copy` is hard to determine exactly by the time `#[derive(Clone)]` needs to do its thing, but at least this could happen when both traits are in the same derive attribute? `#[derive(Copy, Clone)]`

**Comment by bluss** [comment]
A more specific example https://play.rust-lang.org/?gist=ef17b9c31e01be5f65c2&version=nightly where `clone_composite` is a loop and `copy_composite` turns into memcpy.

**Comment by sfackler** [comment]
We currently just desugar `#[derive(Clone, Copy)]` to `#[derive_Clone] #[derive_Copy]`, but it could special case the `Clone` and `Copy` combo.

**Comment by alexcrichton** [comment]
I would be quite ok specializing `#[derive(Clone, Copy)]`, much else beyond that does seem unfortunately quite difficult :(

**Comment by SimonSapin** [comment]
It’s a start, and it may even be the common case.

**Comment by retep998** [comment]
I've had to use a macro to define all my structs in winapi just so I can get that efficient Copy-based Clone impl to improve compile times.

**Comment by durka** [comment]
Okay, so thinking about this idea of special-casing `#[derive(Copy, Clone)]` as `#[derive_CopyClone]` and make that More Magic (tm).

From the code

```rust
#[derive(Copy, Clone)]
struct S<T>(T);

fn main() { }
```

you get (cleaned up)

```rust
struct S<T>(T);

impl <T: Clone> Clone for S<T> {
    fn clone(&self) -> S<T> {
        match *self {
            S(ref x) => S(Clone::clone(&*x)),
        }
    }
}

impl <T: Copy> Copy for S<T> { }

fn main() { }
```

Now instead of the above `Clone` impl we would like there to be

```rust
impl<T: Clone + Copy> Clone for S<T> {
    fn clone(&self) -> S<T> {
        *self
    }
}
```

but now `S<T>: !Clone where T: Clone + !Copy` (please forgive the horrible abuse of notation). Is it possible to do this in a backwards-compatible way? Maybe it can done only for types with no generic parameters?

**Comment by durka** [comment]
[Playpen illustrating the above concern.](http://is.gd/p5vaCj)

**Comment by bluss** [comment]
I think you would need specialization to supply both the `where T: Clone` and  the `where T: Copy`  implementations, the latter is more specific, so it should work out.

**Comment by durka** [comment]
So we'll revisit this after specialization lands?

**Comment by bluss** [comment]
You can do it well already for the case without type parameters

**Comment by durka** [comment]
Agreed.

**Comment by durka** [comment]
See #31414.
