### ISSUE TITLE
Coercion does not take place between if-else and match arms

### ISSUE THREAD

**Issue by jdm** [rust-lang/rust#31091]
This does not compile:

``` rust
fn main() {
  let v = Some(vec![1, 2, 3]);
  let s = match v {
      Some(ref v) => &v[..],
      None => &[],
  };
  println!("{:?}", s);
}
```

It says: 

```
<anon>:4:23: 4:28 error: type mismatch resolving `<collections::vec::Vec<_> as core::ops::Index<core::ops::RangeFull>>::Output == [_; 0]`:
 expected slice,
    found array of 0 elements [E0271]
<anon>:4       Some(ref v) => &v[..],
                               ^~~~~
```

This compiles:

``` rust
fn main() {
  const EMPTY: [i32; 0] = [];
  const EMPTY_SLICE: &'static [i32] = &EMPTY;
  let v = Some(vec![1, 2, 3]);
  let s = match v {
      Some(ref v) => &v[..],
      None => EMPTY_SLICE,
  };
  println!("{:?}", s);
}
```

This also compiles:

``` rust
fn main() {
  let v = Some(vec![1, 2, 3]);
  let s = v.as_ref().map(|v| &v[..]).unwrap_or(&[]);
  println!("{:?}", s);
}
```

**Comment by arielb1** [comment]
Similar:
```Rust
fn main() {
    let v = vec![];
    let _s = if true {
        &[]
    } else {
        &v[..]
    };
}
```

rustc checks each arm of an `if`/`match` with the expected type coming from the outside. This means you won't get a coercion.

**Comment by arielb1** [comment]
I mean, these also work:
```Rust
fn main() {
  let v = Some(vec![1, 2, 3]);
  let s = match v {
      Some(ref v) => &v[..],
      None => &[] as &[_],
  };
  println!("{:?}", s);
}
```
```Rust
fn main() {
  let v = Some(vec![1, 2, 3]);
  let s: &[_] = match v {
      Some(ref v) => &v[..],
      None => &[],
  };
  println!("{:?}", s);
}
```

**Comment by jdm** [comment]
This isn't just if/else, since my first example was a match expression.

**Comment by arielb1** [comment]
As I said, it is a problem in both.

**Comment by pnkfelix** [comment]
This sort of thing is, I believe, a well-known issue in languages that support type-inference (especially ones that have subtyping, which when I squint my eyes, our coercion rules fall into a similar category in terms of the potential type inference issues).

I'm not quite sure what the best fix is.

I'm tempted to say that we should try to resolve it by finding some way to improve the error message. Such a message would (1.) point the user at the conflict that arose between the two arms during the type inference attempt, and (2.) suggest the option of using an explicit type annotation, to resolve manually the question of what type to use).
 * (I'm suggesting the above as an alternative to e.g. trying to change our type inference and coercion system to make it "smart enough" to compile the original code.)

Even this "simpler" error-message oriented approach may be quite difficult to actually implement in practice, though. @nikomatsakis has long talked about reading over the prior art here with respect to improvements to type-inference failure messages.

**Comment by Mark-Simulacrum** [comment]
The examples here appear to compile today. Closing; it seems that this has been fixed.
