### ISSUE TITLE
transmute_copy doc example is too trivial

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang/rust#31094]
http://doc.rust-lang.org/nightly/std/mem/fn.transmute_copy.html#examples

```rust
use std::mem;

let one = unsafe { mem::transmute_copy(&1) };

assert_eq!(1, one);
```

This transmutes an `i32` to... an `i32`! A more realistic example might be to transmute a byte array to a packed struct.

**Comment by steveklabnik** [comment]
part of https://github.com/rust-lang/rust/issues/29362

**Comment by frewsxcv** [comment]
I took a stab at this: https://github.com/rust-lang/rust/pull/31720
