### ISSUE TITLE
rustdoc: hide constness of fns in stable docs

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#31098]
Rustdoc shows const fns as `const`, but you can't call them in a const context because they're still unstable. If you aren't in a const context, it doesn't matter whether the fn is const or not. So it's confusing and maybe it shouldn't be shown at all until the feature is stable.

cc @jethrogb

**Comment by jethrogb** [comment]
Compare [1.5.0 docs](https://doc.rust-lang.org/1.5.0/std/sync/atomic/struct.AtomicBool.html#method.new)
```rust
fn new(v: bool) -> AtomicBool
```
and [stable docs](https://doc.rust-lang.org/stable/std/sync/atomic/struct.AtomicBool.html#method.new)
```rust
const fn new(v: bool) -> AtomicBool
```
This documentation change suggests that this a stable change. Yet `const fn` is still unstable. The stable docs should hide the `const` qualifier on `const fn`s.

**Comment by tomjakubowski** [comment]
This should a pretty straightforward change for someone looking to get into rustdoc development.

**Comment by durka** [comment]
@tomjakubowski is it? does rustdoc know whether it's documenting stable/beta vs nightly?

**Comment by tomjakubowski** [comment]
> @tomjakubowski is it? does rustdoc know whether it's documenting stable/beta vs nightly?

If rustdoc is going to simply remove `const` from functions until the feature is stabilized, then it doesn't matter.

If not, there's a little more work but it's not too bad.  I think simply checking `option_env!("CFG_RELEASE_CHANNEL")` or `CFG_DISABLE_UNSTABLE_FEATURES` would suffice; nightly `rustdoc` binaries would produce `const` in documentation and others would not.

**Comment by durka** [comment]
I think it should make that distinction. If you _are_ on nightly, you can turn on the feature and use the const fns in const contexts, so you want that information.

**Comment by jethrogb** [comment]
I don't think this issue is fixed until the docs at /stable/ actually don't show the qualification.

**Comment by mitaa** [comment]
I think this is still an issue?
