### ISSUE TITLE
BufReader should provide a way to seek without dumping the buffer

### ISSUE THREAD

**Issue by taralx** [rust-lang/rust#31100]
BufReader's seek() implementation always dumps the buffer. This is not good for performance, where users may want to skip a variable amount of buffered data -- only BufReader really knows if it's reasonable to move the pointer or not.

Additionally, only BufReader can know if the pointer can be reversed or not -- so there's absolutely no cheap way to "unget" data from BufReader, even if you know it's seekable.

I'd recommend removing this behavior and moving it to unwrap() or another method (sync?), but it's now baked into a stable API.

What are the options now?

**Comment by taralx** [comment]
(I'm in the process of writing my own BufReader implementation that doesn't do this.)

**Comment by neokril** [comment]
Currently BufReader saves only the offset within buffered data.
As I understand to keep buffer during seek it needs to save "global offset" within inner Reader and update it in all read/seek operations.
It needs this "global offset" because seek operation should return new position in underlying Reader which is not currently saved anywhere. 

Another variant is to make a separate call (e.g. `buffered_seek`) which will use only buffered data, will move only relative to current position and return true/false (true if it was able to move current position inside the buffer; false - nothing happened need a separate call to "seek" to actually move the pointer).

**Comment by taralx** [comment]
I'm not trying to avoid seeking the underlying stream, I'm trying to avoid dumping the buffer. In my implementation, small seeks that fit in the existing buffer cause a call to self.inner.seek(SeekFrom::Current(0)).

**Comment by neokril** [comment]
@taralx Could you please share your implementation?

You use self.inner.seek(SeekFrom::Current(0)) to get current file offset. Am I correct?

**Comment by taralx** [comment]
Not without getting source approval from my employer, sorry.

Yes, I implement "pub fn pos(&mut self) -> io::Result<u64>" and then in seek I have snippets like:

```rust
let p = try!(self.pos());
self.pos -= back;
return p - back;
```

**Comment by gcarq** [comment]
Some time ago I had a similiar requirement, I extracted the implementation into a own library: [seek_bufread](https://github.com/gcarq/seek_bufread/tree/master), maybe its useful for you.

**Comment by lolgesten** [comment]
I stumbled upon this today. When decoding mp4 movies, the decoder will do small seeks forward to skip in the region of 100 bytes at a time. I used a BufReader with 65k capacity to avoid my underlying reader doing http requests for every seek, only to find that BufReader isn't helping at all.

I think BufReader could be more useful if it worked from the buffer also when seek fits.

**Comment by dtolnay** [comment]
I would like to see a PR that implements `seek(SeekFrom::Current(n))` without dumping the buffer if the offset `n` is within the buffered data. I may be missing something but I don't think BufReader would need to store a global offset in order to make this work.

**Comment by taralx** [comment]
FWIW, this solution requires R:Seek. A `try_seek_relative`  function would not have such a requirement.

**Comment by SimonSapin** [comment]
This should not be closed, the new method is still unstable.

It’s been a couple months though. @rust-lang/libs FCP to stabilize?

**Comment by SimonSapin** [comment]
This should not be closed, the new method is still unstable. It’s been a couple months though:

@rfcbot fcp merge

**Comment by alexcrichton** [comment]
@SimonSapin to confirm, this is for the `seek_relative` method, right?

**Comment by SimonSapin** [comment]
Yes, that is the one item with `issue = "31100"`.

**Comment by SimonSapin** [comment]
Hmm, maybe I needed to reopen the issue before making the command:

@rfcbot fcp merge

**Comment by jethrogb** [comment]
I agree with @dtolnay and don't think a separate method is needed for this. This can just be the behavior when calling `seek(SeekFrom::Current(n))`.

**Comment by tmccombs** [comment]
> I agree with @dtolnay and don't think a separate method is needed for this. This can just be the behavior when calling seek(SeekFrom::Current(n)).

I think it could be done something like this:

```rust
fn seek(&mut self, pos: SeekFrom) -> io::Result<u64> {
        let result: u64;
        if let SeekFrom::Current(n) = pos {
            if let Some(new_pos) = (self.pos as i64).checked_add(n) {
                if new_pos >= 0 && new_pos <= self.cap {
                    self.pos = new_pos as usize;
                    return self.inner.seek(SeekFrom::Current(0)).map(|p| p + (self.cap - self.pos));
                }
            }
            // .. the rest is the same as before
```

**Comment by abonander** [comment]
I don't have any real cases in mind but changing the existing seek semantics could cause subtle bugs for people who are relying on it. E.g. if the user is expecting the data at an in-buffer offset to change in the underlying reader and is using seek to refresh the buffer, this optimization would cause it to yield stale data.

**Comment by t-rapp** [comment]
I stumbled over this ticket when implementing a library that parses media files. What makes me uneasy about using `seek_relative` (besides being available in nightly only) is the fact that often I do not have the current position. From reading the source code of [BufReader seek](https://doc.rust-lang.org/std/io/struct.BufReader.html#method.seek) is seems that the internal buffer is flushed even when doing `seek(SeekFrom::Current(0))` to get the current position.

It would be great to add an optimization path for this case to the `Seek` trait implementation of `BufReader`.

**Comment by funchal** [comment]
Hi I'm new to rust, I'm surprised by this behaviour. Can I ask why `BufReader` should flush the buffer on seek within the buffer, like *ever*? I understand this is documented behaviour of a stable api, but I can't think of any reason to write code that would rely on this intentionally, and also can't think of any code that could break unintentionally. I could be wrong but it feels like this was perhaps excessive documentation that now constrains the behaviour of this api to remain inefficient.

**Comment by taralx** [comment]
Because that's the way to sync the BufReader's idea of where the file pointer is with the underlying reader. The other alternative would be to make `into_inner` do it, but it can't because it doesn't depend on `R:Seek`.

**Comment by cgburgess** [comment]
> Because that's the way to sync the BufReader's idea of where the file pointer is with the underlying reader. The other alternative would be to make `into_inner` do it, but it can't because it doesn't depend on `R:Seek`.

It seems like the major issue then is that we are worried people using seek_relative will lose track of where they are in the file/stream and try to seek past the end? The function already returns a result so why is this really an issue? This is my first time stumbling upon a nightly feature so I am just curious.

**Comment by taralx** [comment]
No, the major issue is one of compatibility guarantees. Right now, if you want to sync the BufReader's position with the underlying Reader and extract it, you `seek` and then `into_inner`. So that pattern needs to continue to work.

**Comment by funchal** [comment]
Can't we just leave `seek` alone then and add a separate api `seek2` or whatever which has the little enhancement of not losing the buffer when you seek within it?

**Comment by sfackler** [comment]
That already happened: https://doc.rust-lang.org/std/io/struct.BufReader.html#method.seek_relative

**Comment by taralx** [comment]
I've been advocating for `try_seek_relative` because the existing method requires `R: Seek` where that's not necessary for a BufReader.

**Comment by czipperz** [comment]
@taralx do you want to write up a pr? I doubt it would be very difficult.  Just refactor `seek_relative`s code that already does this out into the method?

**Comment by czipperz** [comment]
I do find it mildly ironic that the [original implementation explicitly documented](https://github.com/rust-lang/rust/commit/0a380a9318cb450fc54153c1327a35cf02fab8e6#diff-a074b6c6ae44d9ac353aa145411afb53R131) that it would always flush the buffer and why.

**Comment by taralx** [comment]
Life is a little busy right now, so if someone else is excited to do it, go for it. Otherwise I'll see if I can't find some time to put together a PR.

**Comment by fintelia** [comment]
@SimonSapin it seems that there was a final comment period for this in Mar 2018 that passed with no objections. Does that now mean there can be a stabilization PR?

**Comment by t-rapp** [comment]
At least for my use-case of parsing media files I'm still relying on the `seek_bufread` crate instead of using `seek_relative` because there seems to be no way in stdlib BufReader to get the current position without dumping the buffer.

**Comment by maxburke** [comment]
One of the challenges I have been finding with BufReader is that the stream_position convenience method is implemented with `seek(SeekFrom::Current(0))` which dumps the buffer.

Is it possible to have this case specialized so that getting the current position doesn't cause the buffer to be thrown away?

**Comment by alecmocatta** [comment]
I'm not entirely clear on the status of [`BufReader::seek_relative`](https://doc.rust-lang.org/nightly/std/io/struct.BufReader.html#method.seek_relative). It was implemented, this issue was denoted as the tracking issue, there's was a successful fcp, but it's still unstable? What was the fcp for?

**Comment by Diggsey** [comment]
@alecmocatta someone still needs to open a PR to mark the method as stable.

**Comment by elomatreb** [comment]
As someone unfamiliar with the processes of Rust development, is there a chance of getting this into one of the upcoming releases?

**Comment by workingjubilee** [comment]
The relevant PR passed FCP, has been approved to merge, and this should become stable in 1.53.0 if all goes well.
