### ISSUE TITLE
Broken links in 1.6 release notes

### ISSUE THREAD

**Issue by vwim** [rust-lang/rust#31102]
In section "Stabilized APIs" there seem to be a few broken links:
* ErrorKind::UnexpectedEof
* Vec::extend_from_slice
* Iterator::min_by_key
* Iterator::max_by_key

Maybe there are more, haven't checked them all.

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/31099 has some stuff

**Comment by steveklabnik** [comment]
All of these examples seem to be fixed now https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-160-2016-01-21
