### ISSUE TITLE
Unsetting GREP_OPTIONS in configure script

### ISSUE THREAD

**Issue by iskolbin** [rust-lang/rust#31107]
Because of coloring **grep** cannot correctly extract versions ( LLVM for example ) when GREP_OPTIONS is set in .bash_profile ( OS X ). Unsetting GREP_OPTIONS solves this problem:

``` diff
@@ -1,5 +1,7 @@
 #!/bin/sh

+unset GREP_OPTIONS
+
```

**Comment by 0xmohit** [comment]
`GREP_OPTIONS` would be removed in a future release of `grep`.  Quoting from the manual:

```
       GREP_OPTIONS
              This variable specifies default options to be placed in front of
              any explicit options.  As  this  causes  problems  when  writing
              portable  scripts,  this  feature  will  be  removed in a future
              release of grep, and grep warns if it is used.   Please  use  an
              alias or script instead.
```

It would appear that there isn't anything to do here.

**Comment by Mark-Simulacrum** [comment]
I'm going to go ahead and close this since this is primarily going to go away in the future anyway, though if a pull request was submitted we'd consider accepting it. I don't think tracking this separately is helpful.
