### ISSUE TITLE
std::string::ParseError doesn't implement neither std::error::Error nor std::fmt::Display.

### ISSUE THREAD

**Issue by serejkaaa512** [rust-lang/rust#31106]
subj

**Comment by alexcrichton** [comment]
Tagging as `E-easy` as should be a pretty good first bug to tackle for libstd!

**Comment by dirk** [comment]
@alexcrichton: Going to give this a shot!

One question, given that `ParseError` is sort of a non-error (at least according to [the docs](https://doc.rust-lang.org/src/collections/string.rs.html#1420-1427)), will returning/writing "parse error" be enough to satisfy `error::Error` and `fmt::Display`?

**Comment by alexcrichton** [comment]
@dirk ok! Yeah it should be fine to just ensure that *something* semi-reasonable comes out, it's more likely the case that just having these traits implemented is useful rather than ensuring the implementations themselves are useful :)

**Comment by bluss** [comment]
Since it's a void enum, you can use the same implementation as clone does in fact:

`match *self {}`

It handles the enum exhaustively (as match forces you to) and makes sure all possible cases (zero cases) are handled. !

**Comment by dirk** [comment]
@alexcrichton: PR #31124 is up!
