### ISSUE TITLE
undefined reference to 'log2f' on android

### ISSUE THREAD

**Issue by not-fl3** [rust-lang/rust#31119]
I tried this code:

```
fn main() {
    let _ = 10.0f32.log2();
}
```
Everithing was fine without cross compilation, but with
> rustc aaa.rs --target=arm-linux-androideabi -C linker="arm-linux-androideabi-gcc-4.8"

i got followed result: 

> error: linking with `arm-linux-androideabi-gcc-4.8` failed: exit code: 1
note: "arm-linux-androideabi-gcc-4.8" "-Wl,--as-needed" "-Wl,--allow-multiple-definition" "-L" "/usr/local/lib64/rustlib/arm-linux-androideabi/lib" "aaa.0.o" "-o" "aaa" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "-L" "/usr/local/lib64/rustlib/arm-linux-androideabi/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/usr/local/lib64/rustlib/arm-linux-androideabi/lib/libstd-db5a760f.rlib" "/usr/local/lib64/rustlib/arm-linux-androideabi/lib/libcollections-db5a760f.rlib" "/usr/local/lib64/rustlib/arm-linux-androideabi/lib/librustc_unicode-db5a760f.rlib" "/usr/local/lib64/rustlib/arm-linux-androideabi/lib/librand-db5a760f.rlib" "/usr/local/lib64/rustlib/arm-linux-androideabi/lib/liballoc-db5a760f.rlib" "/usr/local/lib64/rustlib/arm-linux-androideabi/lib/liballoc_jemalloc-db5a760f.rlib" "/usr/local/lib64/rustlib/arm-linux-androideabi/lib/liblibc-db5a760f.rlib" "/usr/local/lib64/rustlib/arm-linux-androideabi/lib/libcore-db5a760f.rlib" "-l" "dl" "-l" "log" "-l" "gcc" "-l" "gcc" "-l" "c" "-l" "m" "-pie" "-l" "compiler-rt"
note: aaa.0.o:aaa.0.rs:function f32::f32::log2::h94a06ad56bda381bXwa: error: undefined reference to 'log2f'
collect2: error: ld returned 1 exit status

error: aborting due to previous error

While with log(), not log2() everithing works fine.

## Meta

`rustc --version --verbose`:

rustc 1.8.0-dev (cd1b84549 2016-01-22)
binary: rustc
commit-hash: cd1b845492e13ae9e0da382dc0ec09d676d2dd59
commit-date: 2016-01-22
host: x86_64-unknown-linux-gnu
release: 1.8.0-dev

**Comment by alexcrichton** [comment]
Hm unfortunately I can't seem to reproduce this. To help diagnose:

* Where'd you install `rustc` from?
* Where'd you install the arm-linux-androideabi Rust standard library from?
* Where'd you install the NDK from? (the command line to install it would also be useful here)

For reference I ran this inside of the [rust-buildbot android docker image](https://github.com/rust-lang/rust-buildbot/blob/master/slaves/android/Dockerfile) (which has the ndk version r10e), I installed `rustc` through multirust and the Rust standard library via a custom download of the nightlies we're producing.

**Comment by not-fl3** [comment]
Answering your questions i maybe have found problem: i made NDK with 
make-standalone-toolchain.sh \
    --platform=android-14 \
    --arch=arm \
    --install-dir=~/ndk-standalone-14-arm

with android-15+ everithing linking fine. 
So, for me, its reproducable only on api level 14.

**Comment by alexcrichton** [comment]
Ok, thanks for the info! That'd definitely explain the linker error here.

Currently our nightlies are compiled with the API level 18 (I believe), which would explain why we haven't seen this. I don't believe that we have any particular reason for choosing (that I know of at least), but I'm curious if you're trying to specifically target 14? If that's a big enough use case we could consider moving our nightlies back to an older API level.

**Comment by not-fl3** [comment]
For me its not an issue at this moment, i just didn know about such restriction :)

**Comment by alexcrichton** [comment]
Ah ok, in that case I'm going to close as our minimum API version level is 18 currently, but if this becomes an issue please let us know! It may not be too hard to go backwards even farther.

**Comment by kanerogers** [comment]
Hi, there!

I've been having this same issue, and after a fair bit of Googling, I've finally stumbled upon this issue.

A bit of a shame that the minimum API is 18 - the target I'm compiling for is 16, which along with 17 comprises 20.5% of the Android market [at time of writing](http://developer.android.com/about/dashboards/index.html).

If it's not too much work to backport, API level 16 is the minimum API version used in a number of other projects (eg. React Native).

Please let me know if there's anything further I can do to assist.

**Comment by alexcrichton** [comment]
Yeah I'm pretty sure we'd be fine going backwards to a previous API revision so long as we don't lose any major functionality. The steps to do so would be:

1. Updated the [android buildslave](https://github.com/rust-lang/rust-buildbot/tree/master/slaves/android) to have an API-level 16 NDK and emulator image
2. Update the [buildmaster config](https://github.com/rust-lang/rust-buildbot/blob/master/master/master.cfg) to use the older NDK.
3. Update the standard library to run all tests with the API level 16 NDK

Once that's all done we can take care of updating the actual prod buildbots to the newer images.

**Comment by kanerogers** [comment]
Thanks for your help, Alex!

Would you like me to go ahead and do this in a branch and return back?

K

**Comment by alexcrichton** [comment]
Sure! If we get to the point where we're dropping a lot of support in the standard library to go back in API revisions we may need to rethink, but it likely won't come to that.

**Comment by kanerogers** [comment]
Thanks, @alexcrichton. :smile: 

I've created a PR for rust-buildbot [here](https://github.com/rust-lang/rust-buildbot/pull/65), but I'm a little unsure how I can

> Update the standard library to run all tests with the API level 16 NDK

If you're able to please point me in the right direction, I'll get it done!
