### ISSUE TITLE
Windows7, MinGW32/GitBash, rustc and cargo hangs and freezes 100% of the time

### ISSUE THREAD

**Issue by rask** [rust-lang/rust#31114]
I installed Rust 1.6 (Stable) and Cargo using the packaged Windows GNU installer MSI 30 minutes ago. Everything installed fine, but when I attempt to run either `rustc` or `cargo` (any subcommands) the commands just hang. This happens on Git Bash and cmd.exe both.

I have to kill the command with Ctrl-C, but the `rustc.exe` process(es) does not end. I can't even kill it using task managers or admin-elevated cmd.exe prompts.

The only way to end the `rustc.exe` process is to reboot the computer and do your best not to attempt to run it again.

The `rustc.exe` processes that hang do not use any CPU or disk IO resources. They all reserve 312kB of private memory.

Windows event logs state that the installation worked fine. `RUST_BACKTRACE=1 rustc` makes no change. There is no indication whatsoever anywhere telling me what is wrong.

I'm attempting a reinstall right now. Rust documentation states that the installer is tested to work properly on Windows 7 64-bit, so this confuses me a little. Is the MSI installer a package that contains all dependencies or do I need to do something more to make it work?

Additionally I'm running ansicon.exe to color the output of Git Bash, but I have it mapped to a separate start command so Git Bash plainly does not use it.

Let me know if more information is needed.

**Comment by alexcrichton** [comment]
Wow this is... weird! Can't say I've ever seen this or a report of something like this happening before. To clarify, though:

* You're on Windows 7 64-bit, right? 
* The `x86_64-pc-windows-gnu` installer was used?
* Does this reproduce even after rebooting?

cc @vadimcn, @retep998, any ideas what this may indicate the underlying error is?

**Comment by retep998** [comment]
Could you try installing `x86_64-pc-windows-msvc` and seeing if that works? If it does work then I'm blaming jemalloc, if not then I'm confused.

I've seen a few reports on IRC before of people having processes that are frozen like that and most of the time we figured out it was their anti virus. Could you try temporarily disabling your anti virus perhaps?

**Comment by vadimcn** [comment]
Looks like ANSICON injects its dll into processes to hook some system APIs.  I am not sure how targeted this injection is, but this sort of console replacements/enhancers have been a problem for Rust programs in the past (because mingw runtime does some non-standard things to the process memory as well).   Would it be possible to test with ansicon disabled?

**Comment by rask** [comment]
I'm not sure whether I changed something else accidentally while doing other things, but after disabling (and re-enabling) Avast Antivirus the `rustc --version` actually worked and returned the correct output.

I will continue investigating in case this problem returns.

**Comment by alexcrichton** [comment]
Ok, thanks for the info everyone! In that case I'll close for now but we can definitely reopen or make a new issue if it crops up again.
