### ISSUE TITLE
BTreeMap/Set should specify iteration is ordered

### ISSUE THREAD

**Issue by Roxxik** [rust-lang/rust#31129]
I just wanted to note that it is nowhere mentioned that all iterators from there are in sorted order. While I have to admit that it makes sense for a ordered container to provide ordered iterators, it is not documented. In the examples it is assumed that the iterators are ordered, but nowhere explictly stated.
Neither in the BTreeMap nor the BTreeSet.

**Comment by steveklabnik** [comment]
part of https://github.com/rust-lang/rust/issues/29348

**Comment by jonhoo** [comment]
This is not actually closed, as the `BTreeSet` documentation for `iter()` still does not mention this.
