### ISSUE TITLE
Add lint that all crates are #[unstable]

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#31122]
It's easy to forget to write it when adding new crates, as in https://github.com/rust-lang/rust/pull/31120, and then release a crate as stable accidentally.

In [tidy.py](https://github.com/rust-lang/rust/blob/master/src/etc/tidy.py) add a whitelist of crates that *can* be stable; in the loop, if the file name looks like 'src/*/lib.rs' it should have the attribute unless its on the whitelist.

**Comment by alexcrichton** [comment]
:+1:

**Comment by brson** [comment]
Since https://github.com/rust-lang/rust/pull/31120 also was adding a single attribute everywhere, the lint might additionally lint for other common crate attributes.

**Comment by brson** [comment]
I can mentor.

**Comment by KiChjang** [comment]
Can I pick this up? I've been meaning to understand the business of lints.
