### ISSUE TITLE
Add `[` to the follow set for `ty`

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#31135]
As decided in rust-lang/rfcs#1462.

cc @pnkfelix 
cc @retep998

**Comment by durka** [comment]
So according to the RFC document, `FOLLOW(path) = FOLLOW(ty)`. Does that mean we are adding `[` to `FOLLOW(path)` as well?

**Comment by nikomatsakis** [comment]
Seems like yes. After all, a type can be just a path, so if we added a
`[` suffix on paths, it would effectively add such a suffix to types
as well.
