### ISSUE TITLE
Warnings about removed lints may want to itself become a lint

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#31141]
Right now the warnings about a removed lint is a full-fledged warning in the compiler, which primarily means that it is not affected by `--cap-lints allow`. Note that `-A warnings` does indeed suppress the warning, but Cargo no longer pases `-A warnings`.

This ends up meaning that if you just updated to Rust 1.6 (where `raw_pointer_derive` was removed) and recompile your project, you're actually pretty likely to get tons of these warnings from all your upstream dependencies. (although you yourself are unlikely to have `allow(raw_pointer_derive)`. Ideally these warnings would behave like other lint warnings in Cargo, which is that they are ignored in dependencies by default (e.g. suppressed via `--cap-lints allow`).

cc @wycats (reporter)
cc @brson (implementor)

**Comment by alexcrichton** [comment]
As another concrete example, the `libc 0.1`, `openssl-sys 0.7.4`, `curl-sys`, and `curl` crates all had the `raw_pointer_derive` lint explicitly as `#[allow]`, and I found that at least a bunch of the projects I was working with depended on one of these at some point, which meant that there were lots of warnings when updating to 1.6

**Comment by alexcrichton** [comment]
cc https://github.com/rust-lang/rust/pull/30878

**Comment by retep998** [comment]
Funnily enough, the warning for an invalid lint is actually a lint so you can disable warnings for invalid lints, but not removed lints.

**Comment by brson** [comment]
I agree.
