### ISSUE TITLE
Better Explanation of Cargo.lock in 'Getting Started'

### ISSUE THREAD

**Issue by common-nighthawk** [rust-lang/rust#31149]
In 'Getting Started' it is implied that running `cargo build --release` is what creates a Cargo.lock file.  The explanation of Cargo.lock is in the section 'Building for Release'.

From what I can see, just running `cargo build` creates a Cargo.lock file.

I don't know enough about Rust to know if something recently changed or if this is significant.  But wanted to raise the issue, as it looked slightly off as I am going through the tutorials.

Thanks!!

**Comment by steveklabnik** [comment]
Both do, you don't explicitly need `--release`.

**Comment by common-nighthawk** [comment]
It feels to me that the docs imply  `--release` is what creates the .lock file.

"*Building for Release*
When your project is finally ready for release, you can use cargo build --release to compile your project with optimizations.  ... Running this command also causes Cargo to create a new file called Cargo.lock ... Cargo uses the Cargo.lock file to keep track of dependencies in your application."

Please feel free to close if you disagree or think it's too minor to warrant a change.  Just wanted to raise it for consideration, because it confused me a bit.  Also happy to submit a PR if easier.

**Comment by steveklabnik** [comment]
Oh, it should still be carified, I was just trying to give you the answer in the meantime :)

**Comment by common-nighthawk** [comment]
You're the best.  Thank you, @steveklabnik!

**Comment by dirk** [comment]
@common-nighthawk: Want to close this now that #31159 is merged?

**Comment by common-nighthawk** [comment]
lovely.  thanks, @dirk!
