### ISSUE TITLE
Document how the "_" pattern works

### ISSUE THREAD

**Issue by rkruppe** [rust-lang/rust#31154]
#31153 was closed and the user who filed it was educated, but they're not the first and not the last person to be confused by this. AFAIK the behavior of `_` &mdash; especially how it's different from `_foo` &mdash; is not documented, at least I couldn't find anything in the reference and it seems a tad obscure to be mentioned in the book.

**Comment by durka** [comment]
Well it is covered [here](https://doc.rust-lang.org/nightly/book/patterns.html#ignoring-bindings) (and linked from the Syntax Index) but it doesn't explain the behavior discussed in #31153.
