### ISSUE TITLE
Windows linker regression in 1.6

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#31151]
[As reported here](https://www.reddit.com/r/rust/comments/428re7/fixed_link_problem_on_windows_with_rust_16/). 

> I had a problem after upgrading from 1.5 (stable) to 1.6 (stable), so I thought I'd document the fix here. My system is Windows 10, 64-bit; Rust compiler is MSVC ABI; Visual Studio 13 Express for Desktop is installed.

> After upgrading, all cargo builds failed with "link.exe could not find ws2_32.lib". The problem was that the LIB path wasn't set. Setting the environment variable LIB to:

> "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\lib\amd64"; "C:\Program Files (x86)\Windows Kits\8.1\Lib\winv6.3\um\x64" fixed the problem. Your paths may vary, of course, and you might have to add other paths if you have other missing libraries.

> I'm not sure why this worked with earlier versions of Rust; it seems like it should always have failed.

@retep998 Do you know what we should change to make this work out of the box again?

**Comment by retep998** [comment]
I have some ideas of what to do that I got after interrogating a different person on IRC about their issues. I will put together a PR that makes that code even more robust.

**Comment by alexcrichton** [comment]
triage: P-low
