### ISSUE TITLE
Failure to spawn on Windows if stdio handles are null

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#31167]
As [reported here](https://github.com/rust-lang/cargo/issues/2294#issuecomment-174165109), if one of the stdio handles for a Windows process is unset (e.g. isn't present) then you won't actually be able to spawn a process by default. All handles are set, by default, to "inherit", but [this currently means](https://github.com/rust-lang/rust/blob/5a81d9aa6d622b3ea208118c9b121340f04b6460/src/libstd/sys/windows/process.rs#L355) duplicate the existing handle, which in turn means that if the stdio handle isn't present this operation will fail.

Rust currently [defends against this](https://github.com/rust-lang/rust/blob/5a81d9aa6d622b3ea208118c9b121340f04b6460/src/libstd/sys/windows/process.rs#L367) by always opening up handles even if `Stdio::null()` is specified (just pointing them to a blank stream), but Rust should also defend against this situation when it was spawned from elsewhere.

**Comment by emoon** [comment]
cc @emoon
