### ISSUE TITLE
ICE: resolve_trait_associated_const: unexpected vtable type

### ISSUE THREAD

**Issue by yongqli** [rust-lang/rust#31187]
#![feature(associated_consts)]
    pub trait VecN {
        const DIM: usize;
    }
    pub trait Mat where Self::Row: VecN {
        type Row;
        fn a(&self) -> usize {
            Self::Row::DIM
        }
    }

    fn main() { 
    }

https://play.rust-lang.org/?gist=1324f11606a59254efb5&version=nightly

**Comment by sanxiyn** [comment]
Closing in favor of #29924.
