### ISSUE TITLE
--sysroot should be passed on to the linker

### ISSUE THREAD

**Issue by Zoxc** [rust-lang/rust#31180]
The linker needs to be passed the --sysroot option so it can find libraries when cross compiling.

I tried simply modifying rustc to pass the option on to the linker, but --sysroot is used during the bootstrap of rustc without an actual sysroot (i.e. there is only rust libraries, not C, so linking will fail).

**Comment by alexcrichton** [comment]
This seems like a use case for `-C link-args` as the *Rust* sysroot is very different from the *C* sysroot.

**Comment by Zoxc** [comment]
How is the Rust sysroot is very different from the C sysroot and why? I had plotted to use the same folder for both.

**Comment by alexcrichton** [comment]
The compiler currently has basically zero knowledge about the filesystem layout of the underlying C compiler, it just assumes the linker will find the right system libraries in the provided `-L` paths. In that sense there is no intention for the Rust sysroot to contain the C sysroot at all, so they're intended to be separate entities.

**Comment by Mark-Simulacrum** [comment]
Closing as per the above -- we don't intend to do this.
