### ISSUE TITLE
Fix typo in primitive-types.md

### ISSUE THREAD

**Issue by trpapp** [rust-lang/rust#31194]
Under the 'Slicing syntax' section:

The code reads: let middle = &a[1..4]; // A slice of a: just the elements 1, 2, and 3
It should read: let middle = &a[1..3]; // A slice of a: just the elements 1, 2, and 3

1..4 are elements 1, 2, 3 and 4; not 1, 2, and 3

**Comment by apasel422** [comment]
The range `1..4` contains `{1, 2, 3}` because the lower bound is inclusive and the upper bound is exclusive.

**Comment by apasel422** [comment]
You can verify that [here](https://play.rust-lang.org/?code=fn%20main%28%29%20{%0A%20%20%20%20for%20i%20in%201..4%20{%0A%20%20%20%20%20%20%20%20println!%28%22{}%22%2C%20i%29%3B%0A%20%20%20%20}%0A}&version=stable).

**Comment by trpapp** [comment]
Didn't know this! Thanks!
