### ISSUE TITLE
Fix typo in ownership.md

### ISSUE THREAD

**Issue by trpapp** [rust-lang/rust#31198]
Under 'Move semantics'

The text reads: A similar thing happens if we define a function which takes ownership, and try to use something after we’ve passed it as an argument:

The text should read: A similar thing happens if we define a function which takes ownership, and tries to use something after we've passed it as an argument:

**Comment by apasel422** [comment]
I think that the original text is correct: It's "we" who are trying to use something after we've passed it as an argument.

**Comment by trpapp** [comment]
Ah, I can see that. I read it as the function taking ownership and trying or tries to use something.

**Comment by apasel422** [comment]
Yeah, the sentence could probably be rewritten for clarity.

**Comment by trpapp** [comment]
Agreed! This is mostly trivial, I assume. I'm just going through the docs and getting the hang of Rust so I figure I'd contribute where I can.

**Comment by apasel422** [comment]
Much appreciated! It might be best if you accumulate a list of typos and put them into a single issue, or -- better yet -- open a pull request with the corrections.

**Comment by trpapp** [comment]
Thanks for the tip! As you can tell I'm new to git/GitHub as well, haha.

**Comment by steveklabnik** [comment]
A lot of stuff happens due to the fact that I come from a place which has a heavy regional dialect.

Yes, please send a PR if you figure out a better wording here!

**Comment by trpapp** [comment]
It's all good. I have foreign parents and in my opinion, as long as I can make out what they are trying to say, I can understandingly interpret it. Your document is a great resource and I'm hoping to add to that if I can.
