### ISSUE TITLE
There is no way to `unsafe impl` `'static`

### ISSUE THREAD

**Issue by reem** [rust-lang/rust#31196]
This would be extremely useful when using invariant lifetimes as a marker for e.g. safe unchecked indexing, it would be nice to be able to say `unsafe impl<'id> 'static for InvariantLifetime<'id> {}` (where `InvariantLifetime<'a>` is `PhantomData<fn(&'a ()) -> &'a ()>`).

**Comment by reem** [comment]
I am not sure if this is at all feasible, if it's completely bonkers feel free to close.

**Comment by huonw** [comment]
This feels somewhat crazy, but it'd be oh-so-useful: I've had to box things behind trait objects just so that I can erase the lifetime (transmuting `Box<Trait + 'a>` to `Box<Trait + 'static>`) for cases when I'm guaranteeing lifetime correctness in some external way.

**Comment by reem** [comment]
If we had 'type parameter which doesn't unify with anything but itself' as a native part of the type system, it would also solve this problem (using lifetimes for this is admittedly a hack).

**Comment by huonw** [comment]
That solves using lifetimes as a tag, but not having to (ab)use trait objects to force things to be `'static` (unlike the marker traits).

**Comment by arielb1** [comment]
This is currently dangerous because rustc assumes that every lifetime that is `:'static` equals `'static`. Also, this would be very dangerous with `Any`.

**Comment by aturon** [comment]
The lang team discussed this issue, and felt that while there are plausible motivations for the feature, there are also significant dangers. We would consider a fleshed out RFC in this area presenting a strong argument for the importance of the feature and mitigation of the pitfalls that have been raised here.
