### ISSUE TITLE
Add Invariant<T> marker type

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#31218]
From a discussion about different ways to write an Invariant type parameter marker; since we need to express it via `PhantomData`.

candidates were basically (although this was only used for `&'a ()` cases)

1. `PhantomData<*mut T>`
2. `PhantomData<Cell<T>>`
3. `PhantomData<fn(T) -> T>`

Which all have different drawbacks and incidental other implications.

The source of the confusion was (3) case not passing my simple test for invariance.

Because of the drawbacks, it seems it would be useful to have a real invariance marker in rust's libstd.

(1) and (2) make the type `!Sync`. (2) has owns-`T` implications (3) has bug #31200. All of (1), (2), (3) don't respond like `Invarant<T>` should to custom new OIBITS.

cc @reem if you are interested.

**Comment by Gankro** [comment]
This seems like an RFCs thing.

I'm kinda ambivalent on this. We used to have these and that was confusing... but sometimes you do know exactly the semantic you want and there's no "natural" phantom for it.

**Comment by bluss** [comment]
It's more confusing to keep track of all incidental collaterals of the phantomdata formulations.

**Comment by nikomatsakis** [comment]
I'm sort of ambivalent as well. On the one hand, `PhantomData

**Comment by bluss** [comment]
RFC makes sense.

**Comment by pnkfelix** [comment]
Note also this important comment https://github.com/rust-lang/rust/issues/31200#issuecomment-175125579 in response to the claim that "(3) has bug #31200"
