### ISSUE TITLE
NonZero constructor in debug-builds should assert input is actually nonzero.

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#31217]
NonZero constructor in debug-builds should assert input is actually nonzero.

In particular, I am a bit concerned by the somewhat free-wheeling way that we are adding uses of the unsafe `NonZero::new` constructor function without any checks that the given input actually _is_ non-zero.

I freely admit that I do not have many examples of current bugs that such a check would have prevented. However, I can point to some questionable code in a previous iteration of the libstd btree code that such a check would have at least caught: prior to PR #30426, the btree node.rs code had this line:

  https://github.com/rust-lang/rust/blob/26a2f852beae15235e7d3c4c5751ffe8e9459817/src/libcollections/btree/node.rs#L305

Was this a bug? Well, ... according to the invariants of `Unique` and `NonZero`, the `keys.is_null()` check should in principle be optimizable to be "always false", right?
- The assignment occurs at the end of a drop method implementation, but the struct in question was marked `#[unsafe_no_drop_flag]`, and so that drop code can (and will) be run repeatedly, so that `keys.is_null()` call can well occur in a context where the data is in a "bad state"
- (indeed, the whole point of the `keys.is_null()` check is to catch the null being used as a sentinel value, even though it is in fact illegal in that context.)

**Comment by pnkfelix** [comment]
To actually put in this check, the language would need to be extended to some degree, since `NonZero::new` is marked as a `const fn`.

**Comment by pnkfelix** [comment]
another necessary extension to the language implementation would probably be #28809 (see why in https://github.com/rust-lang/rust/issues/28809#issuecomment-149567575 )

**Comment by pnkfelix** [comment]
cc #27730

**Comment by pnkfelix** [comment]
In case its not clear, I strongly encourage the libs team to *not* stabilize `NonZero` until this is addressed in some way.

**Comment by pnkfelix** [comment]
(and see also https://github.com/rust-lang/rust/pull/27573 )

**Comment by eddyb** [comment]
`NonZero::new` should return `Option<Self>` and we could *maybe* provide a `new_unchecked` method, if really needed.

**Comment by Gankro** [comment]
`new_unchecked` is literally the only thing a consumer would ever use. You're asserting the value is statically NonZero in low-level unsafe code.

Note that adding the debug assert is an exception-safety concern -- though it will only trigger if you were about to do UB, so it's ok I guess?

**Comment by eddyb** [comment]
@Gankro How do you know the value is non-zero to begin with?

**Comment by apasel422** [comment]
@eddyb One place this could be used where the value is known to be non-zero is with `HashMap`'s [`SafeHash`](https://github.com/rust-lang/rust/blob/1fa0be2bc038e0575a601ba0273cd83d91d064f2/src/libstd/collections/hash/table.rs#L154).

**Comment by Gankro** [comment]
@eddyb usually because we're already checking -- e.g. it came out of an allocator and we didn't abort. Unique is pretty universally used for "we're Box but not".

The problem code exists because someone was using `null` as a sentinel instead of heap::EMPTY for whatever reason. Probably because of the old filling drop?

**Comment by eddyb** [comment]
@Gankro There's your answer. If it's known to be not NULL, then the allocator should return `NonZero<*mut u8>` or even `Unique`.
The *allocator* is what uses `NonZero::new` and matches on the result.

**Comment by Gankro** [comment]
Yep, that'd be great. 's in the allocator API RFC to some extent already.

**Comment by steveklabnik** [comment]
Triage: NonZero has been replaced with many types, like NonZeroU8. These have both checked and unsafe unchecked constructors. Closing!
