### ISSUE TITLE
Support thread affinity

### ISSUE THREAD

**Issue by jamperry** [rust-lang/rust#31213]
I am porting a C++ application into Rust and I need to set thread affinity masks for the Rust threads to improve cache locality so it minimises cache misses.

Not sure if this functionality should be part of `std` or if I should create it as a separate library.

**Comment by alexcrichton** [comment]
Thanks for the report! Feature requests today tend to go in the rust-lang/rfcs repo as this issue tracker is generally intended for bug reports. Would you be ok reopening the issue over there? Thanks!

**Comment by jamperry** [comment]
Ah, sorry, it's been a while since I last contributed. I will move it to the suggested repo.
