### ISSUE TITLE
{TcpStream,UdpSocket,etc}::try_clone should be named something else

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#31239]

**Comment by oli-obk** [comment]
closed by accident?

**Comment by frewsxcv** [comment]
Why was this closed?

**Comment by frewsxcv** [comment]
Nevermind, I see that issues with this label are intentionally closed

**Comment by bstrie** [comment]
@sfackler I'm not sure that this requires Rust 2.0 to achieve. We could simply follow the precedent set by our renaming of `connect` to `join` on strings and deprecate the old names.
