### ISSUE TITLE
Wrapping code in `fn main` too much in the book's code examples

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/rust#31249]
I've only found this to be a problem in the [testing section](https://doc.rust-lang.org/book/testing.html) but there could be more.

In the code example that follows "Let's make our test fail:", if you click the "Run" button to open that example in the playground, running it exits successfully when it's supposed to fail because the test gets wrapped in `fn main`:

<img width="775" alt="screen shot 2016-01-27 at 6 53 20 pm" src="https://cloud.githubusercontent.com/assets/193874/12632706/033c5500-c528-11e5-9c69-331b9c559ef2.png">

I'm not sure exactly where the `fn main` is being added, but if I inspect the HTML of the page there's a `<span class="rusttest">` that contains `fn main`:

<img width="1273" alt="screen shot 2016-01-27 at 6 52 39 pm" src="https://cloud.githubusercontent.com/assets/193874/12632750/56a84a6e-c528-11e5-9e82-b647079a12ef.png">

Is there a way to opt out of the main wrapping in this case?

I know @steveklabnik is redoing the book; is integration with play.rust-lang.org going to be a part of the new book too, or is this irrelevant? Is this something that's just part of TRPL or is it part of rustbook that other books might use?

I'm going to go research the answers to these questions but wanted to post this in the meantime :)

**Comment by steveklabnik** [comment]
My email got lost in the GitHub outage :) Re-written below:

--------------------------------

This is just normal Rustdoc behavior for examples. We can either:

Add a new rule about #[test]s

Fix it online by writing a main() explicitly.


The second is a lot less work, and isn't really worse. There's already a few situations where the default doesn't work and you have to do this; it's not clear to me more complex rules is helpful.

**Comment by carols10cents** [comment]
I've been saving the tab with half a response started in this textarea since the outage ;)

I researched what the new book is doing, and saw that it was using mdBook.

mdBook has the code-running feature implemented in a different way-- described in https://github.com/azerupi/mdBook/issues/29 ([example](http://azerupi.github.io/mdBook/format/rust.html#Inserting%20runnable%20Rust%20files). It also lets you hide lines with comments!

So yeah, I guess this spot just needs a `# // fn main() {}` :)
