### ISSUE TITLE
clarify BuilderHasherDefault summary

### ISSUE THREAD

**Issue by tshepang** [rust-lang/rust#31242]
This line is not clear:

> A structure which implements BuildHasher for all Hasher types which also implement Default.

I don't know if BuilderHasherDefault implements BuilderHasher and Default for Hasher types, or if it implements BuilderHasher for Hasher types that themselves implement Default.

**Comment by steveklabnik** [comment]
@alexcrichton any thoughts on making the semantics here more clear? I'm not mega familiar with the Hash stuff.

**Comment by alexcrichton** [comment]
I was basically just attempting with words to describe the [trait impls](http://doc.rust-lang.org/std/hash/struct.BuildHasherDefault.html) on `BuildHasherDefault`, but as @aturon was also confused by the wording I guess it *definitely* didn't get the point across!

**Comment by steveklabnik** [comment]
I would be happy to work with anyone who wants to work on this issue.

**Comment by adrianbrink** [comment]
@steveklabnik I would be glad to help out :-) What's the best way to start on this?

I am trying to find the source for the docs and I am ending up [here](https://github.com/rust-lang/rust/tree/master/src/doc), but somehow I think I am wrong.

**Comment by steveklabnik** [comment]
Hey @adrianbrink ! Thanks :)

That's the directory for all of the long-form docs. The API documentation is in the source. With this specific bit of docs, it's here: https://github.com/rust-lang/rust/blob/9316ae515e2f8f3f497fb4f1559910c1eef2433d/src/libcore/hash/mod.rs#L251-L255

So modifying these lines is where you need to go! Feel free to take a shot at it and just open a PR; we can workshop specific wording if you'd like in the PR itself. :smile:

**Comment by frewsxcv** [comment]
Opened a PR for this: https://github.com/rust-lang/rust/pull/38334.

**Comment by frewsxcv** [comment]
Oh sorry, I just realized now that it's tagged `E-Easy`. Had I noticed this earlier, I wouldn't have worked on it, sorry about that!
