### ISSUE TITLE
'rustc_plugin' link in book is broken

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#31251]
http://doc.rust-lang.org/nightly/book/compiler-plugins.html#introduction

links to: http://doc.rust-lang.org/nightly/rustc_plugin/

**Comment by frewsxcv** [comment]
The following 'args' link also fails

**Comment by steveklabnik** [comment]
Yes, they are all broken. This is a duplicate, but I'm on mobile, so I can't find the other one right now.

Until we host an "internals" docs, they won't work.
