### ISSUE TITLE
Rustdoc highlights return tuples incorrectly

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#31261]
http://doc.rust-lang.org/std/string/struct.String.html#method.split_at

![2016-01-28-111324_80x43_scrot](https://cloud.githubusercontent.com/assets/27786/12650251/14ff8f68-c5b0-11e5-81a8-fe98f03aa7b6.png)

The `(` shouldn't be blue.

**Comment by ollie27** [comment]
Was this not fixed in #31121? Now both the parentheses are blue https://doc.rust-lang.org/nightly/std/string/struct.String.html#method.split_at.

**Comment by steveklabnik** [comment]
Ah! I should have double checked, yes.
