### ISSUE TITLE
Add `SeekFrom` to the IO prelude

### ISSUE THREAD

**Issue by forticulous** [rust-lang/rust#31268]
The IO prelude currently includes Read, Write and Seek, but in order to use Seek you almost always need `SeekFrom` in scope also.  I think it makes sense to include `SeekFrom` also.

**Comment by steveklabnik** [comment]
/cc @rust-lang/libs 

Adding something to the prelude is very dangerous.

**Comment by forticulous** [comment]
It looks like the general pattern is that only traits are a part of the io prelude.  So in that way it would be counter to the pattern to add an enum like SeekFrom.
