### ISSUE TITLE
`HashMap` and `HashSet` should provide a getter for their hashers

### ISSUE THREAD

**Issue by apasel422** [rust-lang/rust#31262]
```rust
impl<K: Eq + Hash, V, S: BuildHasher> HashMap<K, V, S> {
    pub fn hasher(&self) -> &S { &self.hash_builder }
}

impl<T: Eq + Hash, S: BuildHasher> HashSet<T, S> {
    pub fn hasher(&self) -> &S { self.map.hasher() }
}
```

This would let us close contain-rs/linked-hash-map#3, and likely has other (niche) uses for code that needs to reproduce hashes.

**Comment by rthomas** [comment]
I'd be interested in taking this one on.

**Comment by rthomas** [comment]
As per @Gankro s suggestion I've put this behind an unstable feature flag `hashmap_public_hasher`.

**Comment by rthomas** [comment]
This has been merged, this issue can now be closed.

**Comment by apasel422** [comment]
@rthomas This actually needs to stay open to track the stability of the newly added methods.

**Comment by alexcrichton** [comment]
:bell: This issue is now entering its cycle-long **final comment period** for stabilization in 1.9 :bell:

**Comment by alexcrichton** [comment]
The libs team discussed this during triage yesterday and the decision was to **stabilize**
