### ISSUE TITLE
Documentation about Child process detach

### ISSUE THREAD

**Issue by LukasKalbertodt** [rust-lang/rust#31289]
It would be nice, if the [docs of `process::Child`](https://doc.rust-lang.org/std/process/struct.Child.html) would mention that the process is detached (and not joined) by default, when a `Child` object goes out of scope. Not having a `Drop` impl is too subtile IMO.

**Comment by steveklabnik** [comment]
Part of https://github.com/rust-lang/rust/issues/29370

**Comment by dirk** [comment]
@steveklabnik: I'd be happy to take this on. :smile:

**Comment by steveklabnik** [comment]
Please do! :)
