### ISSUE TITLE
Typos in "The Guessing Game"

### ISSUE THREAD

**Issue by theroseknight** [rust-lang/rust#31284]
Brand new to Rust so I apologize if this is not the right place for something like this.  I just finished "The Guessing Game" and noticed a small typo:

*We can do that with three more lines. Here’s our new program:*

*The new three lines:*

```
    let guess: u32 = guess.trim().parse()
        .expect("Please type a number!");
```

It appears the book was updated at some point to only contain two lines. 

Similarly. in the following section. this could be a typo or possibly just confusing:

```
io::stdin().read_line(&mut guess).expect("failed to read line"); 
```
*If we leave off calling these two methods, our program will compile, but we’ll get a warning:*

The two methods could refer to .expect and panic!.

**Comment by steveklabnik** [comment]
Nope, this is a typo. There used to be calls to `ok()` in there, and they were removed, but the English wasn't.
