### ISSUE TITLE
enum entries are not compile-time constants

### ISSUE THREAD

**Issue by Kingsquee** [rust-lang/rust#31300]
```rust
pub enum Foo {
    a,
    b,
    CAPACITY,
}

fn main() {
    let arr = [0; Foo::CAPACITY as usize];
}
```

```
<anon>:8:19: 8:41 error: expected constant integer for repeat count, but non-constant path in constant expression [E0307]
<anon>:8     let arr = [0; Foo::CAPACITY as usize];
                           ^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by dirk** [comment]
@Kingsquee: Quick triage: this looks to be an issue in how the compiler generates and assigns the discriminant (0, 1, 2, etc.) for each field. If you specify these yourself (see below) it will compile just fine.

```rust
pub enum Foo {
    A = 0,
    B = 1,
    CAPACITY = 2,
}

fn main() {
    let arr = [0; Foo::CAPACITY as usize];
}
```

**Comment by Kingsquee** [comment]
@dirk Thanks, good to know!

**Comment by dirk** [comment]
@Kingsquee: Glad to help. :smile: 

In regards to the original issue: is predictable auto-assignment of descriminants for enums a feature that should be introduced into the language?

@steveklabnik: Would there be a better place to start/revive this discussion than in this issue?

**Comment by mitaa** [comment]
This issue is tracked here #23898 (this is iow a duplicate)

**Comment by Kingsquee** [comment]
@mitaa Thanks, I'll close this issue then.
