### ISSUE TITLE
Documentation: accessing the private items of a parent module

### ISSUE THREAD

**Issue by swatteau** [rust-lang/rust#31309]
When accessing items defined in the parent module, it is tempting to write `use super::*;`. However, this does not allow accessing private items. For example, this fails:

```rust
fn print_hello() {
    println!("hello");
}

mod inner {
    use super::*;
    pub fn do_something() {
        print_hello(); // error: unresolved name `print_hello` [E0425]
    }
}
```
This is a mistake I've made several times (I suspect many others have too) and the solution is to be explicit about the item used, either with 
```rust
use super::print_hello;
```
or
```rust
super::print_hello();
```

On this topic, the [Rust Reference](https://doc.rust-lang.org/stable/reference.html#use-declarations) says:

> Use declarations support a number of convenient shortcuts:
> - ...
> - Binding all paths matching a given prefix, using the asterisk wildcard syntax `use a::b::*`;
> - ...

I find this a bit misleading because the asterisk wildcard syntax really only binds *public* paths matching a given prefix.

I think it would be nice to add a paragraph in the Rust Book to explain how to access private items properly and to state clearly that `use super::*` won't help.

**Comment by steveklabnik** [comment]
I just added one to the book. The PR may still be open, or it may have been merged in the last day or two; I'm on mobile or I'd check.

**Comment by steveklabnik** [comment]
Yes, it was https://github.com/rust-lang/rust/pull/31226
