### ISSUE TITLE
fs::rename fails when dest exists only on windows

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#31301]
This code fails on windows, not on linux:

```
use std::fs;

fn main() {
    let src = "testdir1";
    let dest = "testdir2";
    fs::create_dir(src).unwrap();
    fs::create_dir(dest).unwrap();
    fs::rename(src, dest).unwrap();
}
```

with

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 5, message: "Access is denied." } }', ../src/libcore\result.rs:741
```

**Comment by alexcrichton** [comment]
I opened this awhile ago as https://github.com/rust-lang/rust/issues/15836 and closed that as "not a bug" because we're just exporting the system's behavior. I'm personally inclined to say that this is something we shouldn't handle in the standard library (but may wish to document)

**Comment by nodakai** [comment]
FYI, Java 7 introduced [`java.nio.file.Files.move()`](http://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#move%28java.nio.file.Path,%20java.nio.file.Path,%20java.nio.file.CopyOption...%29) rather than fixing an [decades-old API `java.io.File.renameTo()`](http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4017593)

**Comment by retep998** [comment]
Maybe std should expose an option to allow overwriting the destination. Interestingly, the option `MOVEFILE_REPLACE_EXISTING` states `This value cannot be used if lpNewFileName or lpExistingFileName names a directory.` so even with that you wouldn't be able to overwrite an existing directory.

**Comment by alexcrichton** [comment]
I'd be wary of making a core operation like this do more than one I/O operation as it'd be tough to ensure that it remains "transactional".

We already attempt to make Windows/Unix behave the same by passing the flag @retep998 mentioned, and the remaining behavior is something I'd prefer to just document.

**Comment by retep998** [comment]
I'm not suggesting that the standard library do that, documenting the current behavior should be sufficient. It's just a workaround that users can easily use right now if they do want that sort of behavior on Windows.

**Comment by barosl** [comment]
I tested `MoveFileEx` with `MOVEFILE_REPLACE_EXISTING` on Windows, and the explanation on MSDN seems to be a bit different from the implementation. `lpNewFileName` must not be a directory, yes, but `lpExistingFileName` *can* be a directory. So replacing a file with a directory using `MoveFileEx` is entirely possible (!). Note that the `rename` POSIX API demands both `from` and `to` are of the same type, which prevents such renaming/replacing.
