### ISSUE TITLE
'-g' flag causes crash in PowerPC rustc for certain inputs.

### ISSUE THREAD

**Issue by Mokosha** [rust-lang/rust#31302]
In particular, I'm experiencing the following behavior:

test.rs:

```
fn main() {
   println!("Hello, world!");
}
```

build.rs:

```
fn main() {
    println!("{}", 2 + 3);
}
```

```
[~/test]$ rustc --version
rustc 1.8.0-dev (53c2933d4 2016-01-29)
[~/test]$ rustc -o test test.rs -g
[~/test]$ rustc -o test build.rs -g
Expected no forward declarations!
!217 = <temporary!> !{}
LLVM ERROR: Broken function found, compilation aborted!
[~/test]$ rustc -o test build.rs
[~/test]$ ./test
5
```

I'm aware that PowerPC is not a "tier 1" platform, but any insight into why this might happen would be interesting. Given my experience, the learning curve for how debug symbols are added via '-g' is a bit steep.

**Comment by steveklabnik** [comment]
Is this still happening today?

**Comment by Mokosha** [comment]
I don't know I unfortunately donated my PPC machine after moving to a much smaller apartment in the cit. 😕

**Comment by steveklabnik** [comment]
Okay! Sorry to hear that :(

Since nobody else has commented, I'm going to close this issue. If anyone else sees this come up, please let me know!
