### ISSUE TITLE
Impossible to create a BTreeMap of RefCell<T>

### ISSUE THREAD

**Issue by gbersac** [rust-lang/rust#31310]
Since `RefCell` doesn't implement the `core::cmp::Ord` trait, it is not possible to instantiate a `BTreeMap` for it, event if the generic type `T` implement it. I don't see any reason why `RefCell<T>` can't be compared to another `RefCell<T>` (or even a `T` instance).

**Comment by jonas-schievink** [comment]
Because it would have to `borrow()` the value, which can possibly panic and is subtle

**Comment by gbersac** [comment]
How to create a dictionnary of `RefCell` then ?

**Comment by jonas-schievink** [comment]
A `RefCell` as a *key* of a dictionary? Well, you could build your own wrapper type that implements `Ord` by calling `deref()`, but that's probably a bad idea anyway, since you could change how the keys compare to each other while they're in the map.
