### ISSUE TITLE
Provide Powershell shortcut alongside the cmd one on Windows.

### ISSUE THREAD

**Issue by pjmlp** [rust-lang/rust#31320]
Powershell is the way to go on Windows systems for modern CLI and installed by default since Windows Vista.

What about providing a short-cut to start a Powershell session instead of an old style cmd one?

I can provide the necessary PR if required.

**Comment by retep998** [comment]
We provide a cmd shortcut?

**Comment by Aatch** [comment]
I don't use Windows, but I can't see the harm in at least providing both options.

**Comment by pjmlp** [comment]
@retep998

Providing a cmd shortcut when Windows developers have been moving to Powershell since Windows XP is like providing a Korn Shell configuration script when almost everyone is moving to Bash on a specific UNIX system.

Sure it will make a few Korn Shell users happy, but not the majority that need to start Bash from a  Korn configured shell. .

With Windows Server Core, all configuration scripts are mostly done in Powershell.

As I mentioned I can do the PR, if I know what is to be provided.

**Comment by retep998** [comment]
@pjmlp I was mostly questioning the fact whether we actually did provide a cmd shortcut. If we _do_ provide a cmd shortcut then yes we should provide a powershell shortcut as well. I use powershell myself for all my rust development.

**Comment by pjmlp** [comment]
Ah sorry for my reply than.

I misunderstood it as implying having cmd should already be good enough.
Am 01.02.2016 20:41 schrieb "Peter Atashian" <notifications@github.com>:

**Comment by Mark-Simulacrum** [comment]
Is this still an issue today? I can't find `.bat` or `.psc?1` files in the Rust installers for `windows-{gnu,msvc}` cc @retep998

**Comment by pjmlp** [comment]
Not sure now that rustup is being used as the main installation.

This was more a kind of heads up related to Windows devs expectations.



Am 29.04.2017 5:07 Vorm. schrieb "Mark Simulacrum" <notifications@github.com

**Comment by steveklabnik** [comment]
I'm going to close this one; I use exclusively powershell for development with no issue, and it seems like this was related to old installers.
