### ISSUE TITLE
The Rust Programming Language - 4.6 Loops issue

### ISSUE THREAD

**Issue by theroseknight** [rust-lang/rust#31334]
The following code will not build or run.  The issue is that 'lines' is never defined in this section of the book. 

```
for (linenumber, line) in lines.enumerate() {
    println!("{}: {}", linenumber, line);
}
Outputs:

0: Content of line one
1: Content of line two
2: Content of line three
3: Content of line four
```

Rust is my first attempt to contribute to someone else's project so if I am not using these issues correctly please let me know and I will cease adding them as I go through the book.

**Comment by Aatch** [comment]
The sample will run if you click the "Run" button that appears when you mouse over the sample. There is a `lines` variable defined, just hidden as it's not relevant there. In fact, showing a `lines` variable would probably be counter productive, as it could mislead readers not aware that it's just a stand-in for any arbitrary iterator.

To be honest, that section is a little sparse anyway and could probably do with a forward reference to the Iterators chapter along with a little more explanation.

**Comment by durka** [comment]
There should probably be a "How to read this book" section that mentions the examples are clickable, and moreover automatically tested, so if you think it looks wrong, click Run to get a second opinion. It could also warn new Rustaceans about hidden lines in doctests (it's covered in the Documentation chapter, but that's too late) and tell them to watch out for it in the std docs too.
