### ISSUE TITLE
missing From<Vec<T>> for Cow<'a, [T]> impl

### ISSUE THREAD

**Issue by talchas** [rust-lang/rust#31354]
Both Vec<T> and &[T] are missing From impls for Cow, unlike String/&str and PathBuf/&Path. Coherence is not (afaict) an issue, since the impl would be in the same crate as Cow.

Is there some reason these don't exist (do they cause coherence issues in downstream crates or something)?

**Comment by alexcrichton** [comment]
Whoa, I have no idea why these aren't implemented... Should be good to go ahead and add them! Want to send a PR?
