### ISSUE TITLE
const fn can cause infinite recursion in rustc

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#31364]
``` rust
#![feature(const_fn)]
const fn a() -> usize { b() }
const fn b() -> usize { a() }
const ARR: [i32; a()] = [5; 6];

fn main(){}
```

> thread 'rustc' has overflowed its stack

The same problem happens in trans when using `static A: usize = a();` instead.

Since we do not have constant conditionals, there's currently no way recursion ever makes sense.

**Comment by tmiasko** [comment]
What about short-circuit behaviour of && and ||, shouldn't it allow you to get
a conditional evaluation inside const?  I will note that it also does not work
as of now. Code below overflow stack with const, and works fine without it.

```rust
#![feature(const_fn)]
const fn a(i: bool) -> bool { i || a(true) }

fn main() {
  println!("{}", a(false));
}
```

**Comment by oli-obk** [comment]
short circuiting has its own bug(#29608) and we're delaying it until we have a single constant evaluator based on MIR, since it'll create some confusion between the two constant evaluators we currently have

**Comment by durka** [comment]
Why doesn't the recursion limit cover this?

**Comment by kylone** [comment]
@durka Best guess: Ran out of stack before hitting the recursion limit. This could happen if the function call chain is long enough during the constant evaluator working on evaluating these recursive functions.
