### ISSUE TITLE
Path equality isn't correct

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#31374]
The following code always returns false whereas it shouldn't:

```Rust
use std::path::Path;

fn main() {
    println!("{}", Path::new("src") == Path::new("./src"));
}
```

Here, both `Path`s refer to the same location. I'm writing a patch ([canonicalize function](http://static.rust-lang.org/doc/master/std/fs/fn.canonicalize.html)).

**Comment by nagisa** [comment]
From [boost](http://www.boost.org/doc/libs/1_33_1/libs/filesystem/doc/path.htm#Path_equality):

> Programmers wishing to determine if two paths are "the same" must decide if that means "the same representation" or "resolve to the same actual file or directory", and choose the appropriate function accordingly.

This is a case from the same bucket.

(Keep in mind, that implicitly canonicalizing paths is also wrong – race conditions may make `Path::new("src") == Path::new("src")` to be `false`!)

**Comment by GuillaumeGomez** [comment]
@nagisa: Hum... Hard to tell. I just can't get rid of the fact that this equality should return true and not false...

**Comment by aturon** [comment]
@GuillaumeGomez This is the intended normalization. Some programs distinguish between `./foo` and `foo` in terms of `$PATH` lookup -- i.e., the former looks only in the current directory, whereas the latter searches in everything listed in `$PATH`.

**Comment by GuillaumeGomez** [comment]
@aturon: That's what @nagisa explained to me. It's just a bit hard to understand why we have a `Path` object then. Just implementing a `Path` on `&str` would have been enough then, no?

**Comment by aturon** [comment]
@GuillaumeGomez `Path` is basically a wrapper around `OsStr` that provides a small amount of normalization, as well as parsing. It's a pretty standard approach; see [the RFC](https://github.com/rust-lang/rfcs/pull/474) for more details on the design.

**Comment by GuillaumeGomez** [comment]
@aturon: Thanks for the link.
