### ISSUE TITLE
Inconsistency in whether methods of shadowed traits are usable

### ISSUE THREAD

**Issue by jseyfried** [rust-lang/rust#31379]
This compiles:
```rust
mod foo {
    trait IntoIterator {}    
    fn f() { Some(0).into_iter(); }
}
```
but this doesn't:
```rust
trait T {}
mod bar {
    use T as IntoIterator;
    fn f() { Some(0).into_iter(); }
}
```
More generally, a shadowed trait's methods are usable if it is shadowed by an item, but not if it is shadowed by an import.

Should methods from shadowed traits be usable?

**Comment by jseyfried** [comment]
cc @nikomatsakis

**Comment by nikomatsakis** [comment]
cc @rust-lang/lang

**Comment by nikomatsakis** [comment]
Nominating for discussion at meeting. Clearly we should be *consistent*. I'm inclined to think that they should not be available, ever.

**Comment by dirk** [comment]
> I'm inclined to think that they should not be available, ever.

I'm of the same thoughts as @nikomatsakis. A new "thing" with the same name as another outer "thing" should not inherit/infer/have/etc. any part of that outer thing. This is the case with [variable bindings](http://rustbyexample.com/variable_bindings/scope.html), but—according to the presented opinion—it seems like it needs to be made consistent for trait bindings, right?

**Comment by bluss** [comment]
Is there a reason to shadow traits by name? What happens here is that it must find a method named `.into_iter()` among the imported traits, and that name has not been shadowed in any way, so it should be callable.

**Comment by nikomatsakis** [comment]
@bluss 

> Is there a reason to shadow traits by name? What happens here is that it must find a method named .into_iter() among the imported traits, and that name has not been shadowed in any way, so it should be callable.

Well, that's the question, isn't it. Imagine then that `trait T` *did* have an `into_iter` method -- would you prefer an ambiguity error here, or success?

**Comment by bluss** [comment]
Ambiguity error if `T` was implemented for `Option<i32>` in the example (and this is already implemented). Otherwise it doesn't interfere in any way.

**Comment by nikomatsakis** [comment]
Another more challenging example might be:

```rust
mod foo {
    use path1::Trait;
    fn bar() {
        use path2::Trait;
    }
}
```

should the methods from `path1::Trait` be available, given that it is shadowed by `path2::Trait`?

**Comment by nikomatsakis** [comment]
My feeling is that the simplest rule is to say that methods come from "traits that are in scope", and shadowed traits are not in scope. This interpretation is shadowing of items from prelude and globs, which seem like they should clearly not count towards method resolution.

**Comment by nikomatsakis** [comment]
Discussed in @rust-lang/lang meeting and settled on "methods from shadowed traits should be unavailable". 

triage: P-medium

**Comment by jseyfried** [comment]
> This interpretation is shadowing of items from prelude and globs

Do we also want methods from `path1::Trait` in your more challenging example to be unavailable?
