### ISSUE TITLE
ICE when const-evaling a block that does not end with an expression

### ISSUE THREAD

**Issue by scurest** [rust-lang/rust#31384]
Unreachable code is entered when trying to const-eval a block that doesn't have a terminating expression.

``` rust
const fn f(_: ()) -> usize { 1 }
fn main() {
    [0; f({})];
}
```

The relevant line is https://github.com/rust-lang/rust/blob/8c77ffb484ada2c8f10bf2da5bbe6a9f82f935bb/src/librustc/middle/const_eval.rs#L1124

**Comment by oli-obk** [comment]
That was me! I found no way to trigger this so I made it unreachable, but I forgot about const fn arguments. We don't have a way of creating a unit constant. Technically it would be an empty tuple, but our constant tuples are just an expression id, we can't create new ones in the const evaluator.

**Comment by oli-obk** [comment]
does not ice anymore, but reports a normal error
