### ISSUE TITLE
Tracking issue for CommandExt::before_exec

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#31398]
Open questions:
- The requirements for `Send` + `Sync` on the closure need to be documented and are "somewhat odd"
- It's somewhat surprising to have to deal with a list of callbacks to invoke, especially when order might matter quite a bit.
- There are weird semantics with using `Stdio::piped()` for any of the stdio handles because they'll immediately close the other half of the pipe (via CLOEXEC). 

This is a tracking issue for https://github.com/rust-lang/rfcs/pull/1359.

**Comment by dirk** [comment]
I'm planning on giving this a shot this evening. :smile:

**Comment by alexcrichton** [comment]
@dirk oh sorry I should have mentioned that I'm working on implementing this. There's actually a good deal of refactoring I'd like to do at the same time, and I'm already halfway through it so far!

**Comment by dirk** [comment]
@alexcrichton: Oh, no worries! Thanks for replying so quickly.

**Comment by pnkfelix** [comment]
@alexcrichton I am seeing test failures in `check-stage1-rpass` for `src/test/run-pass/command-before-exec.rs` on Mac OS X.  (This is with a MIR analysis branch, with no changes to code gen; I haven't double-checked against a clean master yet, but it seems very unlikely that my own changes are related.)

Is this functionality only working for stage2 and higher?

Or is there potentially some latent bug here that I should double check?

**Comment by alexcrichton** [comment]
Hm in theory the test should work for all stages, so seems suspicious that it's failing! Do you have some logs that I could look at? May be able to help diagnose what's happening in any case.

**Comment by pnkfelix** [comment]
@alexcrichton here is a gist of a run I did locally.

Running the test binary itself on its own by hand does not reproduce the issue, and the nature of the test makes it difficult to add `println!` style instrumentation to the test. :)

**Comment by pnkfelix** [comment]
From https://gist.github.com/pnkfelix/aa878b372761f957a9d4#file-gistfile1-txt-L21 it appears this is the line that is causing the test to fail when run in the context of `compiletest` (though I have not yet tried removing the given assertions to see what happens...)

```rust
    let output = Command::new(&me).arg("test3").before_exec(|| {
        env::set_current_dir("/").unwrap();
        Ok(())
    }).output().unwrap();
    assert!(output.status.success());
```

**Comment by pnkfelix** [comment]
I revised the portion of the test to check the `stdout` and `stderr` buffers before checking the `output.status`, and added instrumentation to print out the contents of the `stderr` buffer when it is non-empty.

I.e. I put in this:

```rust
    if !output.stderr.is_empty() {
        println!("stderr: {:?}", String::from_utf8(output.stderr.clone()));
    }
    assert!(output.stderr.is_empty());
    assert!(output.stdout.is_empty());
    assert!(output.status.success());
```

This yielded something useful:

```
% DYLD_LIBRARY_PATH=$(pwd)/x86_64-apple-darwin/stage1/lib:$(pwd)/x86_64-apple-darwin/llvm/Release/lib:$DYLD_LIBRARY_PATH x86_64-apple-darwin/stage1/bin/compiletest --compile-lib-path x86_64-apple-darwin/stage1/lib --run-lib-path x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib --rustc-path x86_64-apple-darwin/stage1/bin/rustc  --aux-base $(pwd)/../src/test/auxiliary/ --stage-id stage1-x86_64-apple-darwin --target x86_64-apple-darwin --host x86_64-apple-darwin --python "/Users/fklock/bin/python2.7"  --host-rustcflags "   --cfg rtopt   -C rpath -L x86_64-apple-darwin/rt" --lldb-python-dir=/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python --target-rustcflags "   --cfg rtopt   -C rpath -L x86_64-apple-darwin/rt" command-before-exec  --src-base /Users/fklock/Dev/Mozilla/rust-mir/src/test/run-pass/ --build-base x86_64-apple-darwin/test/run-pass/ --mode run-pass --rustdoc-path x86_64-apple-darwin/stage1/bin/rustdoc --android-cross-path=

running 1 test
test [run-pass] run-pass/command-before-exec.rs ... FAILED

failures:

---- [run-pass] run-pass/command-before-exec.rs stdout ----
	
error: test run failed!
status: exit code: 101
command: x86_64-apple-darwin/test/run-pass/command-before-exec.stage1-x86_64-apple-darwin 
stdout:
------------------------------------------
stderr: Ok("dyld: Symbol not found: __ZN11collections4hash5table16round_up_to_next10_FILE_LINE20h6b6ee708a299a5faiacE\n  Referenced from: /Users/fklock/Dev/Mozilla/rust-mir/objdir-dbgopt/x86_64-apple-darwin/test/run-pass/command-before-exec.stage1-x86_64-apple-darwin\n  Expected in: /Users/fklock/Dev/Mozilla/rust-mir/objdir-dbgopt/x86_64-apple-darwin/stage1/lib/libstd-9026086f.dylib\n in /Users/fklock/Dev/Mozilla/rust-mir/objdir-dbgopt/x86_64-apple-darwin/test/run-pass/command-before-exec.stage1-x86_64-apple-darwin\n")

------------------------------------------
stderr:
------------------------------------------
thread '<main>' panicked at 'assertion failed: output.stderr.is_empty()', /Users/fklock/Dev/Mozilla/rust-mir/src/test/run-pass/command-before-exec.rs:62
note: Run with `RUST_BACKTRACE=1` for a backtrace.

------------------------------------------

thread '[run-pass] run-pass/command-before-exec.rs' panicked at 'explicit panic', /Users/fklock/Dev/Mozilla/rust-mir/src/compiletest/runtest.rs:1651
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    [run-pass] run-pass/command-before-exec.rs

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured

thread '<main>' panicked at 'Some tests failed', /Users/fklock/Dev/Mozilla/rust-mir/src/compiletest/compiletest.rs:246
```

**Comment by pnkfelix** [comment]
(i'll try doing a clean build off master, to see if this reproduces in such a context or if there is some build product that is messed up in my local build above.)

**Comment by alexcrichton** [comment]
Oh there may be some craziness with rpath or something like that. If you add `// no-prefer-dynamic` to the top of the test, does it work?

**Comment by pnkfelix** [comment]
@alexcrichton yes adding `// no-prefer-dynamic` causes the test to pass again.

So what is the next step?

My intuition is that either there is a bug, or the specification needs to reflect this so-called craziness; in the former case I don't know what the bug actually is, and in the latter case I guess once the specification has been updated then we just put the `// no-prefer-dynamic` into the test itself?

**Comment by alexcrichton** [comment]
I think the bug has something to do with the fact that the path to find the dynamic libraries is relative and relies on the current directory being the same as when it was built. With the current directory changing when the binary is invoked it causes the dynamic library lookup paths to be different, which causes the failure.

Maybe this is failing locally for you (and not on the bots) due to some `./configure` option or another? In any case linking statically sidesteps these concerns so I don't think there's too much of an underlying bug really.

**Comment by pnkfelix** [comment]
@alexcrichton okay. Just in case it matters, the build itself is in a subdirectory of the `rust` checkout (named `objdir-dbgopt` in this case), and the configure invocation was (I think) something along the lines of:
```
configure --enable-debug --enable-optimize     --enable-ccache --enable-clang --prefix=~/opt/rust-dbg --disable-optimize-tests --disable-llvm-assertions 
```

**Comment by alexcrichton** [comment]
:bell: This issue is now entering its cycle-long **final comment period** for partial stabilization in 1.9 :bell:

The libs team has decided to tentatively stabilize `CommandExt::exec` for 1.9, but to continue to leave `before_exec` unstable. Some thoughts of ours were:

* The requirements for `Send` + `Sync` on the closure need to be documented and are "somewhat odd"
* It's somewhat surprising to have to deal with a list of callbacks to invoke, especially when order might matter quite a bit.
* There are weird semantics with using `Stdio::piped()` for any of the stdio handles because they'll immediately close the other half of the pipe (via CLOEXEC).

**Comment by alexcrichton** [comment]
The libs team discussed this during triage yesterday and the conclusion was to **stabilize** the `exec` method and leave out `before_exec` for now.

**Comment by luser** [comment]
Is it just the list of issues in [your previous comment](https://github.com/rust-lang/rust/issues/31398#issuecomment-195481589) that need to be sorted out still? I've run into two cases recently where this API would have made my life easier (enabling ptrace for a child process with `PTRACE_TRACEME`, and getting the mach task for a child process on OS X).

**Comment by alexcrichton** [comment]
@luser yeah most of those are still relevant (I'll update the top comment), unfortunately. It could just be time though to declare "this is the way it'll be"

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

I personally feel that [despite the drawbacks](https://github.com/rust-lang/rust/issues/31398#issuecomment-195481589) `before_exec` is still useful in situations like @luser mentioned plus others. Although it can be built out-of-tree with `CommandExt::exec` it's massively painful to do so.

**Comment by luser** [comment]
FWIW I implemented the ptrace case as a crate here using `before_exec`: https://github.com/luser/spawn-ptrace

**Comment by l0kod** [comment]
FYI [tty-rs](https://github.com/stemjail/tty-rs) use `before_exec` for *setsid(2)*.

**Comment by mattgreen** [comment]
Looking forward to this landing in stable soon.

Most users don't need it, but when you do, it's really useful. watchexec uses it to [create a new process group](https://github.com/mattgreen/watchexec/blob/48b0def80de39331f5906d48d96c97e89779e4e9/src/process.rs#L32) when launching processes on non-Windows OSes.
