### ISSUE TITLE
An import that should be resolvable is left unresolved.

### ISSUE THREAD

**Issue by jseyfried** [rust-lang/rust#31404]
Example:
```rust
pub mod foo {
    pub mod bar {
        pub fn f() {}
    }
}

mod baz {
    pub use foo;
    pub use self::foo::bar; // This import is unresolved, but it should resolve to ::foo::bar

    pub use self::bar::f as foo;
}
```
This compiles if `foo` is copied into `baz` instead of being imported with `pub use foo;`.

**Comment by jseyfried** [comment]
This is a related example that is more realistic and also doesn't doesn't resolve:
```rust
mod foo {
    pub mod bar {}
    pub use self::bar as baz;

    pub use self::baz::*;
}
```

**Comment by KalitaAlexey** [comment]
Shouldn't you need write `pub use super::foo`?

**Comment by jseyfried** [comment]
That would work too. Paths in use declarations are crate-relative unless they start with self or super.

**Comment by KalitaAlexey** [comment]
Yeah. You are right. I didn't know that.
