### ISSUE TITLE
std::process Cgroups?

### ISSUE THREAD

**Issue by SethDusek** [rust-lang/rust#31406]
Could it be possible to have cgroup support for std::process? Like a linux-specific trait so that you can limit certain things of processes for example:

```rust
Command::new("somecommand")
.arg("somearg")
.cgroup("somegroup:/somesubgroup")
.spawn()
```

It'd be really useful in certain stuff such as timeouts and memory limits, etc

**Comment by alexcrichton** [comment]
Thanks for the report! A feature request to add support for cgroups (e.g. a platform-specific extension) currently belongs over in the rust-lang/rfcs repo, but you may also be interested in the recently-approved [`CommandExt::before_exec`](https://github.com/rust-lang/rfcs/pull/1359) function which should allow this as well (e.g. arbitrary code execution following just before an `exec`.

If the `before_exec` doesn't work out, could you open an issue against rust-lang/rfcs? Thanks!
