### ISSUE TITLE
Tracking issue for file_try_clone

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#31405]

**Comment by bluss** [comment]
I think this was intended to be picked up by Rust 1.8 stabilization? @alexcrichton, do you know? There was a wish to stabilize it soon when it was added.

**Comment by alexcrichton** [comment]
:bell: This issue is now entering its cycle-long **final comment period** for stabilization in 1.9 :bell:

**Comment by aturon** [comment]
For the record, the naming here is in part justified by the already-stable [method on tcp streams](http://static.rust-lang.org/doc/master/std/net/struct.TcpStream.html#method.try_clone).

**Comment by SimonSapin** [comment]
The naming convention of `try_FOO` for methods that return `Result` is also consistent with https://github.com/rust-lang/rfcs/pull/1542 (`try_from` and `try_into`).

The `try!` macro however *takes* a `Result` and does not generally return one. So we may end up with `try!(x.try_clone())` and `try!(y.try_into())` (which sounds repetitive and has two different meaning for the same word) being used a lot… But then if the `?` operator sticks around maybe `try!` will be deprecated or go out of fashion, leaving us with `x.try_clone()?` and `y.try_into()?` which looks nicer to me.

**Comment by alexcrichton** [comment]
The libs team discussed this during triage yesterday and the decision was to **stabilize**
