### ISSUE TITLE
rustc suggests a trait from a crate that hasn't been `extern use`d.

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#31422]
I copy-pasted some code into a test case and get this error resolving `join`. It says `itertools::Itertools` is a candidate, but I haven't written `extern crate itertools`. This error suggests that `use itertools::Itertools` will work, but it will not.

This was the error:

```
$ cargo build && eRUST_BACKTRACE=1 cargo test -p rust-install --test dist
   Compiling rust-install v0.0.4 (file:///C:/Users/brian/Documents/dev/multirust-rs)
rust-install\tests\dist.rs:222:68: 222:72 error: no method named `join` found for type `core::iter::Map<core::slice::Iter<'_, u8>, [closure@rust-install\tests\dist.rs:222:42: 222:66]>` in the current scope
rust-install\tests\dist.rs:222     let hex = hasher.finish().iter().map(|b| format!("{:02x}", b)).join("");
                                                                                                  ^~~~
rust-install\tests\dist.rs:222:68: 222:72 help: items from traits can only be used if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
rust-install\tests\dist.rs:222:68: 222:72 help: candidate #1: use `itertools::Itertools`
error: aborting due to previous error
Could not compile `rust-install`.

To learn more, run the command again with --verbose.
```

**Comment by durka** [comment]
Spooky. rustc didn't learn to browse crates.io on its own, did it? It sure [seems like](https://github.com/Diggsey/multirust-rs/blob/master/rust-install/src/lib.rs#L7) you do have `extern crate itertools`...

**Comment by nagisa** [comment]
The `extern crate` is in a different crate. Seems like we suggest traits from indirect dependencies; but I’m not sure if that behaviour is incorrect, honestly.

**Comment by brson** [comment]
Yeah, it's in a different crate. It may be useful information to convey, but as presented I think it's misleading.

**Comment by steveklabnik** [comment]
Triage: this issue needs reproduction instructions

**Comment by Mark-Simulacrum** [comment]
Closing. We can reopen with reproduction instructions but otherwise this isn't worth keeping around.
