### ISSUE TITLE
rustc man page shows no link to rust-lang.org on OS X

### ISSUE THREAD

**Issue by saurvs** [rust-lang/rust#31432]
![screen shot 2016-02-05 at 10 43 33 pm](https://cloud.githubusercontent.com/assets/12742708/12853422/013461ce-cc5a-11e5-98da-80b7773347ee.png)

On OS X 11.1, the ```rustc``` man page doesn't display the link to https://www.rust-lang.org in the ```DESCRIPTION``` section.

**Comment by durka** [comment]
Seems like the `.UR` request for formatting a URL isn't supported by whatever OSX uses to display man pages, whereas it works on Linux.

```sh
$ ag '\.UR' ~/.multirust/toolchains/stable/share/man/man1/rustc.1
10:.UR https://www.rust\-lang.org
89:.UR http://www.sourceware.org/autobook/
291:.UR https://github.com/rust\-lang/rust/issues
```

None of these links show up. (As a side note, multirust doesn't hook up the right stuff for `man rustc` to work.)
