### ISSUE TITLE
Duplicate entries in trait std::clone::Clone implementors

### ISSUE THREAD

**Issue by WiSaGaN** [rust-lang/rust#31431]
In [std::clone::Clone](http://doc.rust-lang.org/nightly/std/clone/trait.Clone.html),
we see there are duplicate entries,
`impl<T> Clone for Box<T> where T: Clone`
`impl<T: Clone> Clone for Box<T>`
`impl<T> Clone for Box<T> where T: Clone`
@bluss suggested

> probably something related to the multiple crate structure of std

Not sure if this is related to #26384, but it's still in nightly doc.

**Comment by jonas-schievink** [comment]
Duplicate of #25061?

**Comment by steveklabnik** [comment]
yes, it would seem so.
