### ISSUE TITLE
`Foo(..)` patterns work for tuple structs, but `(..)` doesn't work for tuples

### ISSUE THREAD

**Issue by niconii** [rust-lang/rust#31443]
Right now, [this compiles](https://play.rust-lang.org/?gist=cd33108e66f35535cb14&version=nightly):
```rust
struct Foo(i32, i32, i32);

fn main() {
    match Foo(1, 2, 3) {
        Foo(..) => { }
    }
}
```
but [this fails to compile](https://play.rust-lang.org/?gist=1a1c89eb2514c5966e93&version=nightly):
```rust
fn main() {
    match (1, 2, 3) {
        // must write `(_, _, _) => { }`
        (..) => { }
    }
}
```

**Comment by petrochenkov** [comment]
Yeah, also
```
struct Foo(i32, i32, i32);

fn main() {
    match Foo(1, 2, 3) {
        Foo(a, ..) => { }
    }
}
```
doesn't work. `..` in patterns has a couple of pretty obvious extensions, someone just need to write an RFC (probably me, at least I was going to do it some time ago).

**Comment by durka** [comment]
@petrochenkov have to be careful because in

```rust
struct Foo(i32, RangeFull);

fn main() {
    match Foo(i32, ..) {
        Foo(a, ..) => { }
    }
}
```

the `..` is not a catchall pattern. So the extensions may lead to confusion/ambiguity. I guess this already a problem with `struct Foo(RangeFull);`.

**Comment by petrochenkov** [comment]
@durka 
`RangeFull` literals `..` are not considered patterns, so there's no conflict currently.

**Comment by steveklabnik** [comment]
Closing in favor of the RFC, since this would be a language change.
