### ISSUE TITLE
Shared<T> does not forward Sync

### ISSUE THREAD

**Issue by alexreg** [rust-lang/rust#31456]
While it's correct for it not to forward the `Send` trait, because it could violate mutability rules, there seems to be no reason it shouldn't forward the `Sync` trait (as `Unique<T>` does).

**Comment by apasel422** [comment]
I'm not sure that the definition of `Sync` would permit this, as you can get `*mut T`s out of a `&Shared<T>`. From [the docs](https://doc.rust-lang.org/std/marker/trait.Sync.html):

> The precise definition is: a type `T` is `Sync` if `&T` is thread-safe. In other words, there is no possibility of data races when passing `&T` references between threads.

The [Nomicon](https://doc.rust-lang.org/nomicon/send-and-sync.html) has more details.

**Comment by alexreg** [comment]
That is an unsafe operation however, so the usual rules don’t apply.

**Comment by bluss** [comment]
Since you can't access `T` from a `Shared<T>` without unsafe code, it doesn't matter for correctness either way. How `Shared<T>` behaves is just chosen for what's convenient in the places where it is used as a building block.

**Comment by apasel422** [comment]
@alexreg In that case, why is `*mut T` `!Sync`?

**Comment by Kimundi** [comment]
From the nomicon link you posted: "Doing anything useful with a raw pointer requires dereferencing it, which is already unsafe. In that sense, one could argue that it would be "fine" for them to be marked as thread safe." ;)

**Comment by alexreg** [comment]
Anyway, if we’re going to use the argument “it can only be accessed unsafely”, then I think `Unique<T>` should *not* forward `Send`/`Sync` either, for the sake of consistency.

**Comment by nagisa** [comment]
> Anyway, if we’re going to use the argument “it can only be accessed unsafely”, then I think `Unique<T>` should *not* forward `Send`/`Sync` either, for the sake of consistency.

Documentation for `Unique<T>` explains the reasoning:

> Unique pointers are Sync if T is Sync because the data they reference is unaliased. Note that this aliasing invariant is unenforced by the type system; the abstraction using the Unique must enforce it.

Shared has no such semantic attached to it.

**Comment by alexreg** [comment]
This rather misses the point, since you can alias raw pointers anyway.

I think it’s all a big lie to be talking about guarantees with unsafe pointers anyway. Why not make this explicit by not pretending there are by implementing these traits?

**Comment by bluss** [comment]
`Unique<T>` and `Shared<T>` are conveniences, utilities, that encapsulate some recurring patterns in implementing Rc, Arc, and various collections. It's not about guarantees embodied by the Unique/Shared themselves, but defaults for properties w.r.t `T` that the type that uses `Unique<T>/Shared<T>` will want to have.

Being utility building blocks, it only makes sense to change them if you show why changed properties would be a better for their use case (current uses in libstd as well as cases in non-libstd code). For example, if a property of either Unique or Shared would make it easy to create bugs. 

Note that `Arc<T>` has the following properties:

- `Arc<T>: Send where T: Send + Sync`
- `Arc<T>: Sync where T: Send + Sync`

so the suggested change is a correct default for neither Rc nor Arc.

**Comment by Mark-Simulacrum** [comment]
Based on https://github.com/rust-lang/rust/issues/27730 (tracking issue) and https://github.com/rust-lang/rust/pull/41064#issuecomment-298671581, we explicitly do not want to implement Sync for `Shared<T>`, so closing. If you disagree, please let us know and we'll reopen; also please leave a comment on the tracking issue voicing your opinion (we're headed towards FCP and stabilization of Shared, I believe, soon-ish).
