### ISSUE TITLE
linker error when returning (and using) a struct that is not exported

### ISSUE THREAD

**Issue by mttnff** [rust-lang/rust#31464]
I just came across a linker error, which should probably give an error during compilation instead. Minimal example:

lib.rs:
```rust
mod stuff {
    pub struct MyStruct(u8);

    //some very useful struct
    impl MyStruct {
        pub fn new() -> MyStruct { MyStruct(42) }
        pub fn get_data(self) -> u8 { self.0 }
    }
}

use stuff::MyStruct;

pub fn foo() -> MyStruct {
    MyStruct::new()
}
```

When adding a binary target `bin/exe.rs` like this:
```rust
extern crate crash;

fn main() {
    //linker error here
    let n = crash::foo().get_data();
    println!("Got: {}",n);
}
```

I get the following linker error on `cargo build` or `cargo build --bin exe`:
```
note: /.../crash/target/debug/exe.0.o: In function `exe::main':
/.../crash/src/bin/exe.rs:5: undefined reference to `stuff::_$LT$impl$GT$::get_data::hda4b62b5e3688f36taa'
collect2: error: ld returned 1 exit status
```

I am not familiar with the way rust handles modules, but I think this should indeed not work, so the compiler should probably give an error here.

Note that this compiles (and runs) fine if `pub mod stuff` is used instead of `mod stuff`, or if `pub use stuff::MyStruct` is used, which would make `MyStruct` accessible.

Compiler versions used:
```
rustc 1.6.0 (c30b771ad 2016-01-19)
rustc 1.8.0-nightly (3623797eb 2016-02-07)
cargo 0.7.0-nightly (1af03be 2015-12-08)
```

**Comment by sfackler** [comment]
This is definitely a bug, but you should be able to get things to work by using `pub use stuff::MyStruct` instead of `use stuff::MyStruct`.

**Comment by petrochenkov** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/16734

**Comment by mttnff** [comment]
Indeed, sorry for missing out on that.
