### ISSUE TITLE
[MIR] repr::Mir should have a name or span

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#31467]
Otherwise, error reporting is problematic.

**Comment by nagisa** [comment]
Each `Mir` comes from `MirMap` and has an associated `NodeId`. It is possible to extract most of the source-level info from that and HIR map.

(OTOH, I don’t see why including a span or something like that would be detrimental)

**Comment by arielb1** [comment]
I am working on this

**Comment by arielb1** [comment]
This is fixed as of Rust 1.15.
