### ISSUE TITLE
Compilation timeout

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#31475]
The following code compilation never ends:

```Rust
fn foo() -> ! {
    loop {}
}

fn main() {
    let x = 3;
    
    let y = match x {
        1 => 1,
        2 => 4,
        _ => foo(),
    };
}
```

**Comment by durka** [comment]
Compiles fine for me. It enters an infinite loop at runtime, but that looks like it's intended?

**Comment by GuillaumeGomez** [comment]
No you're right, it's `rustdoc --test` which doesn't have a timeout. I'll update the E0270 in order to avoid rustdoc to go crazy.
