### ISSUE TITLE
[MIR] Phantom unit write after return

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#31472]
## EDIT: I was confused about the issue

``` Rust
pub fn foo(mut value: u64) -> usize {
    return 0;
}
```

```
fn(arg0: u64) -> usize {
    let mut var0: u64; // value
    let mut tmp0: ();
    let mut tmp1: ();

    bb0: {
        var0 = arg0;
        return = const 0;
        goto -> bb1;
    }

    bb1: {
        return;
    }

    bb2: {
        drop(tmp0) -> bb3;
    }

    bb3: {
        return = ();
        goto -> bb1;
    }
}
```

**Comment by arielb1** [comment]
The write here is the empty write at the end of a block - which should not exist if the block is diverging.

Unclear whether we should not create the (ill-formed) write when building or remove it in post-processing.

**Comment by nagisa** [comment]
NB: This write gets removed by simplifycfg (you need to comment the pass out to reproduce the issue).

**Comment by arielb1** [comment]
This would still pose a problem to analysis passes that want to run before SimplifyCfg. I am adding an early pass for my MIR typeck PR to ameliorate this problem.

**Comment by nagisa** [comment]
Likely caused by [this](https://github.com/rust-lang/rust/blob/master/src/librustc_mir/build/block.rs#L280)

**Comment by arielb1** [comment]
The root cause of the problem is that typeck allows "diverging" blocks to have any kind of return value instead of requiring it to be MIR. I think that clearing the diverging blocks in a post-pass is a better strategy than detecting diverging blocks in HAIR.

**Comment by tsion** [comment]
Maybe we should only emit [what @nagisa linked to](https://github.com/rust-lang/rust/blob/master/src/librustc_mir/build/block.rs#L28) when the actual type of the block is unit?

Generally, a missing final expression doesn't necessarily mean `()`  could be inserted, e.g.:

```rust
fn foo() -> i32 { panic!(); } // OK
fn foo() -> i32 { panic!(); () } // expected `i32`, found `()` - http://is.gd/qVOTyf
```

**Comment by nagisa** [comment]
@tsion your code sample should always fail before MIR generation. I believe it is only the `return *;` case that matters.
