### ISSUE TITLE
foreign function invalid error message

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#31481]
This code works:

``` Rust
extern "C" {
    fn foo(x: u8, ...);
}
```

While this one doesn't:

``` Rust
extern "C" fn foo(x: u8, ...); // error: only foreign functions are allowed to be variadic
```

I don't think this is the expected behavior.

**Comment by huonw** [comment]
`extern "C" fn foo(..)` is defining a Rust function that uses the C ABI (i.e. is callable from C), not importing a C function called `foo`. That is, it only differs to `fn foo(..)` in low-level code-generation details, it still has all the normal Rust features/restrictions. This includes not working with variadic arguments.

Also, writing `extern "C" fn foo(..);` without a body isn't valid, e.g. if the `...` is removed to allow compilation to progress, you instead get:

```rust
extern "C" fn foo(x: u8); // error: expected one of `->`, `where`, or `{`, found `;`
```

I suppose the error message could possibly be clearer.

**Comment by GuillaumeGomez** [comment]
I really thought that the two writings were equivalent. I'm a bit surprised.

**Comment by GuillaumeGomez** [comment]
Since the original message came from a lack of knowledge, I changed the title to better reflect the "real" issue here.

Also, I'd like to work on this issue.
