### ISSUE TITLE
Cannot glob import the crate root.

### ISSUE THREAD

**Issue by retep998** [rust-lang/rust#31484]
The following does not compile.
```Rust
mod foo {
    use *;
    pub fn meow(){bar()}
}
pub fn bar(){}
fn main(){foo::meow()}
```
Also tried `use ::*;` `use {*};` and `use ::{*};`.

I'm not sure why we don't support this case. Maybe nobody felt anyone would ever use it? It sure would be nice to have in winapi.

**Comment by keeperofdakeys** [comment]
Can you do `use self::*;` for this?

**Comment by retep998** [comment]
Yes that is a workaround but not a solution. It's rather unfriendly to arbitrarily nested modules as you'd end up with things like  `use super::super::super::*;`. We allow importing items directly from the crate root, and we allow glob imports in other paths that are relative to the crate root, so missing the simple case of glob importing the crate root itself seems like an oversight.
