### ISSUE TITLE
--cfg accepts invalid cfgs

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#31495]
List meta items are not allowed in `cfg` specs because the compiler reserves them for built-in predicates like `any`.

So for example you can't write

```
foo.rs:1:7: 1:16 error: invalid predicate `foo`
foo.rs:1 #[cfg(foo(bar))]
               ^~~~~~~~~
```

You *can* though write `rustc --cfg "foo(bar))". This should be similarly rejected.

cc https://github.com/rust-lang/rust/pull/31278

**Comment by brson** [comment]
This is probably pretty easy. Comparing the parsing in libsyntax with the parsing in librustc_driver and fix the latter to be like the former. Add a test to src/tests/compile-fail with the `compile-flags:` directive set to `--cfg whatever`.

**Comment by kamalmarhubi** [comment]
Should `rustc --cfg any(foo)` be accepted?

**Comment by kamalmarhubi** [comment]
I'm assuming it should not for now.

**Comment by brson** [comment]
@kamalmarhubi No it should not.

**Comment by kamalmarhubi** [comment]
Excellent, less fixup work for me :-)
