### ISSUE TITLE
rustdoc duplicates "implementors" in some rare cases

### ISSUE THREAD

**Issue by nodakai** [rust-lang/rust#31491]
- http://doc.rust-lang.org/std/convert/trait.Into.html#implementors
- http://doc.rust-lang.org/nightly/std/convert/trait.Into.html#implementors

> Implementors
>
> `impl<T, U> Into<U> for T where U: From<T>`
> `impl Into<Vec<u8>> for String`
> `impl Into<OsString> for PathBuf`
> `impl Into<Vec<u8>> for String`

**Comment by jonas-schievink** [comment]
Duplicate of #25061, I think

**Comment by steveklabnik** [comment]
Yes, it would seem so.
