### ISSUE TITLE
documentation test fails with library

### ISSUE THREAD

**Issue by zetok** [rust-lang/rust#31533]
I've tried to document something in crate I'm making, and `cargo test` panicked on documentation test.

Reproducible: Always
Note that it's not reproducible if crate is not a lib.

Most reduced doc which fails to pass documentation test:
```
/// ```
/// +-----+
/// |nope |
/// +-----+
/// ```
///
/// Eh.
pub fn somefn() {}
```

Steps to reproduce:
1. Create new library with `cargo new lib`
2. Append test case to `lib/src/lib.rs`
3. Run `cargo test`

↑ which results in:
```
Doc-tests lib

running 1 test
test somefn_0 ... FAILED

failures:

---- somefn_0 stdout ----
	<anon>:2:5: 2:6 error: unexpected token: `+`
<anon>:2     +-----+
             ^
thread 'somefn_0' panicked at 'Box<Any>', ../src/libsyntax/parse/mod.rs:98


failures:
    somefn_0

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured
```

Rust:
$ rustc --version --verbose
rustc 1.6.0 (c30b771ad 2016-01-19)
binary: rustc
commit-hash: c30b771ad9d44ab84f8c88b80c25fcfde2433126
commit-date: 2016-01-19
host: x86_64-unknown-linux-gnu
release: 1.6.0

Might be related to #29771 ?

Please feel free to rename issue to something better.

**Comment by ollie27** [comment]
rustdoc interprets anything in a code block as a test and tries to run it. You can avoid that by doing:
```
/// ```text
/// +-----+
/// |nope |
/// +-----+
/// ```
```
See https://doc.rust-lang.org/nightly/book/documentation.html for more information.

**Comment by zetok** [comment]
Oh, ok, thanks. I didn't expect that something in comments would be run. Sorry for the issue.
