### ISSUE TITLE
Writing to values after giving up ownership doesn't error

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang/rust#31538]
Taking this example:

```rust
struct Data {
    x: i32,
    y: Vec<i32>
}

fn use_data(mut data: Data) {
    data.x = 1;
    data.y.push(7);
}

fn main() {
    let mut data = Data { x: 0, y: Vec::new() };

    use_data(data);

    data.x = 2;
    //data.y.push(8);
}
```

Currently, Rust nightly doesn't error on the 'data.x = 2' line, even though we've given up ownership to data.  The error does appear if you uncomment the following line and try to do something a little less trivial than assigning to an i32.  

Should we treat them the same and warn of *any* use, whether reading or writing, of any field of a value that we no longer own?

**Comment by arielb1** [comment]
Why should it error?

**Comment by bluss** [comment]
The behavior after `data` is moved from is pretty haphazard, for example

```rust
    data.y = vec![];  // is ok
    drop(data.y); // error: use of moved value: `data.y`
```

**Comment by jonathandturner** [comment]
@arielb1 - it's a totally fair question.  For me it's about having a mental model that's simple to explain for how ownership works after you've handed off ownership of your data.  Like @bluss shows, the current behavior is a mix of errors and non-errors, depending on what you're doing.  

I think a simpler mental model might be something like "after you hand off ownership, any read or write to the data will error."  Currently, it's something more like "after you hand off ownership, any read will fail and any write will appear to succeed but will not update the value you've handed off. Instead, it updates an invisible copy you can not read.  Also, any update (eg .push(x) or drop) will fail"

**Comment by alexcrichton** [comment]
Thanks for the report! I think this is the same as https://github.com/rust-lang/rust/issues/26665 which is in turn described more thoroughly in https://github.com/rust-lang/rust/issues/21232, so I'm going to close in favor of that.
