### ISSUE TITLE
Tracking issue for the Rust Language Server

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#31548]
Tracking issue for https://github.com/rust-lang/rfcs/pull/1317

(to be filled in by @nrc...)

**Comment by archshift** [comment]
Has work started on this yet?

**Comment by nrc** [comment]
@archshift no. It is low priority for now until there is concrete progress with incremental compilation (perhaps mid 2016).

**Comment by pyfisch** [comment]
[The Language Server Protocol](https://code.visualstudio.com/blogs) is "a common protocol for languages" and is supported Red Hat, Codenvy and Microsoft. If this becomes a standard protocol it would be great if Rust used it.

**Comment by lilianmoraru** [comment]
@pyfisch Came here to post this :smile:

**Comment by mfarrugi** [comment]
Kythe also has a similar, though less targeted goal than the 'Language Server Protocol'.

**Comment by Marwes** [comment]
Added basic language server support for my own language (written in Rust). The language server API is not complete yet but I would be happy to separate out the language agnostic parts to its own crate if that would be useful. 

https://github.com/Marwes/gluon_language-server

**Comment by bruno-medeiros** [comment]
> Added basic language server support for my own language (written in Rust). The language server API is not complete yet but I would be happy to separate out the language agnostic parts to its own crate if that would be useful.
> 
> https://github.com/Marwes/gluon_language-server

Ha, I had just started very similar work last week: https://github.com/RustDT/RustLSP
RustLSP is meant to be just the LSP protocol, not tied to any actual language engine.

I'm hoping later to actually provide a basic Rust language server, by integrating Racer, Rainicorn, maybe even cargo build and rustw to the LSP protocol.

**Comment by Marwes** [comment]
@bruno-medeiros I finished making the rest of the [serializing structures](https://github.com/Marwes/gluon_language-server/blob/master/src/language_server.rs) yesterday (barring a mistake here or there), if you want I can move them to a crate and submit to crates.io if you want to skip the tedious part of the server.

**Comment by alexcrichton** [comment]
I suspect that this tracking issue isn't really tracking much any more, so closing.
