### ISSUE TITLE
--color=always still checks for a terminal before printing colors

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#31546]
rustc --color=always foo.rs 2>&1 | cat

This produces colored output on 1.6.0, but not 1.7.0 or 1.8.0. Related to rust-lang/rust-playpen#174, cc @nrc.

**Comment by durka** [comment]
Also related to #29999, @Stebalien do you have any thoughts?

**Comment by TimNN** [comment]
I also commented on the playpen issue and think that some change (maybe #29999) changed `term::stderr()` so that it no longer returns `Some(_)` if `stderr` is not a tty or something like that.

**Comment by nrc** [comment]
A fix for this should get uplifted to Beta (not sure how to signal that with the available labels).

**Comment by Stebalien** [comment]
Ignoring windows...

The term library doesn't care if it's writing to a TTY, only if (1) the TERM environment variable is set and (2) it can find/parse the terminfo database.

This appears to have been introduced in #30711. Adding `-Z unstable-options --error-format=human` brings the color back. I've submitted a pull-request.
