### ISSUE TITLE
Docs: Vec<T>'s contents being contiguous could be a little more clear

### ISSUE THREAD

**Issue by niconii** [rust-lang/rust#31554]
At the moment, `Vec<T>`'s [module](https://doc.rust-lang.org/nightly/std/vec/index.html) and [type](https://doc.rust-lang.org/nightly/std/vec/struct.Vec.html) doc pages don't quite make it clear that its contents are in fact contiguous. They imply it in several places...

> Vectors have `O(1)` indexing, amortized `O(1)` push (to the end) and `O(1)` pop (from the end).

> Most fundamentally, Vec is and always will be a (pointer, capacity, length) triplet. No more, no less.

...but it would be better to make it more clear. In addition, `Vec<T>`'s documentation refers to it as a "growable list type", which could be misleading in light of this; "list" is more often used to mean a linked list.

Perhaps something like one of these would be better as the description line:

> A contiguous growable list type with heap-allocated contents, written `Vec<T>` but pronounced 'vector.'

> A growable array type with heap-allocated contents, written `Vec<T>` but pronounced 'vector.'

**Comment by GuillaumeGomez** [comment]
A more global description is a nice idea. However, keeping the original text is also a nice thing, it's appreciated to have algorithm's complexity. So from my point of view, this would be perfect:

> A contiguous growable list type with heap-allocated contents, written Vec<T> but pronounced 'vector.'
>
> A growable array type with heap-allocated contents, written Vec<T> but pronounced 'vector.'
>
> Vectors have O(1) indexing, amortized O(1) push (to the end) and O(1) pop (from the end).

**Comment by steveklabnik** [comment]
part of https://github.com/rust-lang/rust/issues/29380
