### ISSUE TITLE
Incomplete save-analysis for macros

### ISSUE THREAD

**Issue by DanielJCampbell** [rust-lang/rust#31553]
Currently macros are only recorded if they are called at some point in non-generated source code. The most notable effect of this is that if a macro references some other macro internally (eg. foo! expands to bar!), that macro will not be indexed.

A fix probably requires changes to expansion traces, to store more information about macro bodies after expansion, or manually pulling nested macro calls out of callee spans.

**Comment by Mark-Simulacrum** [comment]
Test case for future visits:

```rust
macro_rules! a {
    () => {
        macro_rules! b {
            () => {
                0
            };
        }
        b!()
    }
}

fn main() {
    a!();
}
```

```
rustc -Z save-analysis test.rs
rg '"name":"b"' save-analysis-temp/test.json # should find "b"
```

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by jyn514** [comment]
Save-analysis has been [removed from the compiler](https://github.com/rust-lang/rust/pull/101841).
