### ISSUE TITLE
Tracking issue for SocketAddr setters

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#31572]
#31083 adds `set_ip` and `set_port` methods to `SocketAddr`, `SocketAddrV4`, and `SocketAddrV6`; as well as `set_flowinfo` and `set_scope_id` on `SocketAddrV6`. They are all fairly straightforward and correspond to existing getter methods.

As all new additions, they will be `#[unstable]` for now.

**Comment by Aatch** [comment]
Seems like 'B-unstable' is the most appropriate label for this issue? There's no RFC, but this is a stability-tracking issue.

**Comment by alexcrichton** [comment]
Indeed! We try to have `B-unstable` for all tracking issues on the libs team

**Comment by SimonSapin** [comment]
Yes. I would have set it, but you need write access to a repository to set labels :)

**Comment by alexcrichton** [comment]
:bell: This issue is now entering its cycle-long **final comment period** for stabilization in 1.9 :bell:

**Comment by alexcrichton** [comment]
The libs team discussed this issue during triage yesterday and the decision was to **stabilize**
