### ISSUE TITLE
no_run doctests no longer verify lints

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#31576]
For code like this:

```rust
#![doc(test(attr(deny(warnings))))]

/// ```no_run
/// let a = 3;
/// ```
pub fn foo() {}
```

The stable/beta rustdoc will generate an error, while the nightly rustdoc will pass silently. [This block](https://github.com/rust-lang/rust/blob/master/src/librustdoc/test.rs#L253-L255) looks suspicious perhaps?

~~r?~~ cc @nrc

**Comment by alexcrichton** [comment]
er, that r? was meant to be a cc

**Comment by alexcrichton** [comment]
Tagging as a regression and nominating

**Comment by crumblingstatue** [comment]
The borrow checker also does not seem to operate on `no_run` tests.

```rust
//! ```no_run
//! fn main() {
//! let mut s = "hello".to_owned();
//! let ref1 = &mut s;
//! let ref2 = &mut s;
//! }
//! ```
```

Will past the Doc-tests.

**Comment by steveklabnik** [comment]
@crumblingstatue 's error does not happen on 

```
rustc 1.9.0-nightly  (388ccda45 2016-03-07)
```

so it must have happened recently.

**Comment by crumblingstatue** [comment]
@steveklabnik 
The Doc-Test also passes on `rustc 1.8.0-beta.1 (facbfdd71 2016-03-02)`. It fails on stable, which is the correct behavior.
How are you testing it?
I use `rustdoc --test foo.rs`

**Comment by steveklabnik** [comment]
I meant that the test fails, sorry. I cannot reproduce the bug.

**Comment by crumblingstatue** [comment]
Just to show a real life case, and the fact that this is not just an anomaly on my local system, here is a travis build of a project that passes on both beta and nightly, but fails (properly) on stable.

https://travis-ci.org/jeremyletang/rust-sfml/builds/115021280

**Comment by nikomatsakis** [comment]
@nrc, any thoughts?

**Comment by nikomatsakis** [comment]
tagging with T-compiler just so we can review in compiler mtg, even though it's sort of more tools.

**Comment by nikomatsakis** [comment]
triage: P-high

**Comment by alexcrichton** [comment]
Bisection-via-nightly turns up 2016-02-01 was the last good and 2016-02-02 is the first bad. This points to some commit between 094c5b0d61a0fb19a1cb94dddd6f59a975089b4b and b94cd7a5bd488324e39047682e1e4dad9c08fa, of which the most suspect is #31250.

[This line looks quite suspect](https://github.com/rust-lang/rust/blob/master/src/librustc_driver/driver.rs#L196-L198), returning that there are 0 errors when `result` may otherwise indicate that errors would have happened.

Ok so after writing all that up I tested it out and I'll just make a PR soon.
