### ISSUE TITLE
error index tests are not run during `make check`

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#31587]
https://github.com/rust-lang/rust/pull/30726 adds testing of the error index. They run on `make check-docs` but not yet on `make check`. They should.

This is just a matter of deciphering tests.mk and figuring the right rule to add.

**Comment by GuillaumeGomez** [comment]
I don't think anything Makefile related should be labelled as easy.

**Comment by james-w** [comment]
I will take a look at this. I'm pretty experienced with Makefiles, and I've had a look and
I think I follow how this works.

**Comment by apasel422** [comment]
This would likely have prevented #33662.

**Comment by dsprenkels** [comment]
This issue has been fixed by #34201 and may be closed.
