### ISSUE TITLE
ICE: assert! on Non Boolean

### ISSUE THREAD

**Issue by nixpulvis** [rust-lang/rust#31592]
Running the following yields an unhelpful error message, and ICE in the span printing.

```rust
fn main() {
    assert!(Ok(1));
}
```

With error

```
error: cannot apply unary operator `!` to type `core::result::Result<_, _>`
```

A potential solution could be `if $cond { } else { panic! ... }`

Either way there is some problem with span printing on this bad use of `assert!`.

**Comment by arielb1** [comment]
No ICE in the span printing on nightly.
