### ISSUE TITLE
Rustdoc: static methods have self argument in search-index

### ISSUE THREAD

**Issue by mitaa** [rust-lang/rust#31598]
Searching i.e. for ["vec -> vec"](http://doc.rust-lang.org/nightly/std/?search=vec%20-%3E%20vec) returns `Vec::new` as search result.

**Comment by quodlibetor** [comment]
Without the self type as the lhs of the `U -> T` there is no way to search for "all methods that produce T" (i.e. [`-> vec`](http://doc.rust-lang.org/nightly/std/?search=-%3E%20Vec) and similar don't work) perhaps something like `* -> T` and/or `void -> T` should be added before this is fixed?
