### ISSUE TITLE
Incorrect documentation on read_and_drop

### ISSUE THREAD

**Issue by Thiez** [rust-lang/rust#31599]
The documentation of the unstable function `core::ptr::read_and_drop` makes a reference to `read_and_zero`, but this function does not exist (anymore?). Expressing the semantics of `read_and_drop` in terms of something that does not exist is unhelpful.

The problem seems to be located [here](https://github.com/rust-lang/rust/blob/e548d6c08f87c6a0a15a91c21df0990112b5a7f4/src/libcore/ptr.rs#L130).

I imagine the fix would involve traveling back in time until before `read_and_zero` was removed and copying its documentation, after correcting for the differences between it and the `read_and_drop` function.

@steveklabnik

**Comment by bluss** [comment]
Filling drop is a temporary "feature" of rust, and in the long run this function will not be needed once the in-struct drop flags are gone. In anticipation of this improvement, it would be best to not write any code that relies on read_and_drop.

**Comment by Thiez** [comment]
I'm not using that function, I was merely browsing the docs and noticed the documentation was wrong. I would expect the documentation of functions to be correct even if they are unstable and scheduled for removal, unless the removal is scheduled for the immediate future.
