### ISSUE TITLE
error: internal compiler error: cannot get field of type: ...

### ISSUE THREAD

**Issue by Yoric** [rust-lang/rust#31603]
Between yesterday and today, something changed that broke my builds with Nightly. I don't know if this is an upgrade to the latest Nightly or a change in my code yet.

See https://travis-ci.org/fxbox/thinkerbell/builds/108783925 for links to all the details.

**Comment by arielb1** [comment]
a backtrace would help

**Comment by Yoric** [comment]
See above link, it includes a backtrace.

**Comment by arielb1** [comment]
I suspect this is a duplicate of #31504.

**Comment by Yoric** [comment]
Fixed by #31504.
