### ISSUE TITLE
[Doc] the try! and vec! macros don't have a [src] link

### ISSUE THREAD

**Issue by aoaaxy** [rust-lang/rust#31601]
Hi. Would it be feasible to have a link to the source code on github for the specific function/macro from its doc? 
For example, from this doc: https://doc.rust-lang.org/std/macro.try!.html
I wanted to know what's in-between these `{ ... }` and I imagined how great would be if there were a nearby link pointing to the source code for this `try!` macro. An example of such link would be: https://github.com/rust-lang/rust/blob/stable/src/libcore/macros.rs#L194
 That kind of immediate accessibility would increase everyone's knowledge, I believe, because it would be less deterring than doing something like this instead: https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=%22macro_rules!+try%22&type=Code 
(personally I wouldn't have looked it up at all; but depends on each person's drive, I guess)

Thank you for your consideration.

**Comment by mitaa** [comment]
This works for most things, but it seems like rustdoc has a problem here because `try` is is a macro re-export from `core`.

i.e the `[src]` button is available [here](https://doc.rust-lang.org/core/macro.try!.html) at the top right.

**Comment by aoaaxy** [comment]
Oh that's amazing! I didn't know that's already true for others!(I just blindly assumed it's not)
Thank you for this!

**Comment by steveklabnik** [comment]
There are already open issues for macros not being able to show their source, so this is a duplicate. Thanks though!
