### ISSUE TITLE
Multiple-file single project/crate with function calls example in guide, please?

### ISSUE THREAD

**Issue by luxspes** [rust-lang/rust#31625]
This https://github.com/rust-lang/rust/issues/18533 is far from fixed, the crates guide does not explain at all how to find the way to use more than one file on your project.
It explains how to call files from one project into another project, but if if you try to have 2 files in one crate and call a function from each other you will fail and the guide will not help you at all.
You create a crate (using Rust 1.6):

cargo new lists

then you add a file first.rs with a function:

` pub fn blah() {}
`
Then on lib.rs
you simply write:

pub mod first;

```
fn it_works() {
    blah();
}
```

And then try to build and you will get:

Compiling lists v0.1.0 (file:///Rust/lists)
src/lib.rs:8:9: 8:13 error: unresolved name `blah` [E0425]
src/lib.rs:8         blah();
                     ^~~~
src/lib.rs:8:9: 8:13 help: run `rustc --explain E0425` to see a detailed explanation
error: aborting due to previous error
Could not compile `lists`.

And in http://doc.rust-lang.org/book/crates-and-modules.html there is no answer or similar scenario to follow

**Comment by steveklabnik** [comment]
There is an entire section that covers this https://doc.rust-lang.org/book/crates-and-modules.html#multiple-file-crates

**Comment by steveklabnik** [comment]
(You need to call `first::blah()` rather than just `blah()`)

**Comment by sqrl** [comment]
The linked guide is comprehensive. But I think the section doesn't fulfill luxspes's usage case:
They're asking for a simple guide for how to break up a project into multiple files, all within the root module.

The docs are comprehensive, but they could do a better job of speaking to the initial need of, say, simply breaking up a large main.rs or lib.rs file, prior to the English/Japanese submodules discussions.
