### ISSUE TITLE
Add documentation for &str prefixes.

### ISSUE THREAD

**Issue by Aaronepower** [rust-lang/rust#31634]
I cannot find any documentation of `&str` prefixes, some are obvious, like `b"Hello"` gives the equivalent in bytes, which is easily shown by it's usage in doc tests, but for example the prefix `r#"Hello"#` isn't obvious from it's usage. 

There may also be other prefixes, but there is no definitive place to find that out. There should be a list of prefixes available to remove this "hidden" knowledge. This could be added to the [`str`](http://doc.rust-lang.org/std/primitive.str.html) primitive documentation.

**Comment by petrochenkov** [comment]
The [language reference](http://doc.rust-lang.org/reference.html) contains information like this.
http://doc.rust-lang.org/std/primitive.str.html and http://doc.rust-lang.org/std in general are about library things.

**Comment by Aaronepower** [comment]
@petrochenkov Maybe it should just contain a link to the language reference then?

**Comment by rkruppe** [comment]
I'm ambivalent about linking to the language reference. It's old, often incomplete or outdated, sometimes misleading, occasionally even wrong (e.g. in examples). Even if it were complete, up-to-date and correct, it's far too detailed for casual learning.

The *syntax* reference seems like a better place for this information.

**Comment by steveklabnik** [comment]
Yes, the syntax reference is where this kind of information should live. It doesn't belong in the `str` docs, because a byte string won't generate a `str`, for example.
