### ISSUE TITLE
Spurious timeout in test net::tcp::tests::close_read_wakes_up

### ISSUE THREAD

**Issue by pitdicker** [rust-lang/rust#31657]
It just happend with my unrelated pull request on auto-win-msvc-32-opt.
It is the only test that dit not complete between this build and the previous.
It also contains the comment: "this test will never finish if the child doesn't wake up"

**Comment by pitdicker** [comment]
This seems to be relevant.
http://stackoverflow.com/questions/10935267/does-a-socket-shutdown-call-from-another-thread-always-make-blocking-recv-thre

A thread may not wake up on Windows if a socket is shut down.

**Comment by alexcrichton** [comment]
Hm that just seems to indicate that the child will *eventually* wake up... I wonder if `Shutdown::Both` would fix the problem here?
