### ISSUE TITLE
E0404 error explanation is too narrow

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#31687]
The E0404 is explaining something about implementing non-traits, but the error code is also presented for cases like in https://github.com/rust-lang/rust/issues/31686. The error explanation should either be expanded to include the current case or a different error code should be used.

cc @GuillaumeGomez on the thing described in this comment, since you originally authored the explanation for the code.

**Comment by GuillaumeGomez** [comment]
Thanks! I'll take a look as soon as I can.

**Comment by GuillaumeGomez** [comment]
The following code (wrote by @nagisa) reproduces it:

```Rust
struct A<'a> {
    a: ::std::marker::PhantomData<&'a ()>
}

struct B {
    b: for<'a> A<'a>
}

fn main(){}
```

I think the best solution here is to create another error code.

**Comment by oli-obk** [comment]
I think updating the docs to also include `dyn Trait` types is the best solution here as it looks like the same underlying problem to me

**Comment by Dylan-DPC** [comment]
This is fixed as E0404 is now reworked with the other error code in https://github.com/rust-lang/rust/pull/69887
