### ISSUE TITLE
`type` aliases cannot be used for traits note is printed wrongly

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#31686]
```
src/librustc/session/mod.rs:63:39: 63:67 error: `mir::transform::Passes` is not a trait [E0404]
src/librustc/session/mod.rs:63     pub mir_passes: RefCell<for<'tcx> mir::transform::Passes<'tcx>>,
                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/librustc/session/mod.rs:63:39: 63:67 help: run `rustc --explain E0404` to see a detailed explanation
src/librustc/session/mod.rs:63:39: 63:67 note: `type` aliases cannot be used for traits
src/librustc/session/mod.rs:63     pub mir_passes: RefCell<for<'tcx> mir::transform::Passes<'tcx>>,
                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The error here is pretty clear, but the note is completely wrong as the relevant snippet appears in the type of the struct field and not `type` item.

**Comment by nagisa** [comment]
A bit relatedly, the `E0404` is explaining something about implementing non-traits. The error explanation should either be expanded to include the current case or a different error code should be used.

**Comment by Manishearth** [comment]
The note should use fileline_note instead, and we should have an extra help message in case the type alias has a span (which will not be the case if it's from a foreign mod)

**Comment by Manishearth** [comment]
Mentoring this.

[Relevant code](https://github.com/rust-lang/rust/blob/504ca6f4221b5745c5d72902c1c30415845afa26/src/librustc_resolve/lib.rs#L1991)
Change the `span_note` to `fileline_note`.

You will also need to use `resolver.ast_map.span_if_local(def_id)` on the defid contained in the `TyAlias` to find the span for the alias (to use for outputting the extra note)

Let me know if you have any questions!

**Comment by nagisa** [comment]
@Manishearth while I do not disagree with general suggestion to use `fileline_note` but I think that won’t resolve the issue, because `mir::transform::Passes<'tcx>` is not a typedef in a first place.

---

https://github.com/rust-lang/rust/issues/31687#issuecomment-184627673 has a code sample which reproduces the issue, by the way.

**Comment by Manishearth** [comment]
As I see it there are two distinct issues. One is tha

**Comment by nagisa** [comment]
Oh, it doesn’t fail on nightly. I guess, then, original issue I reported is not really an issue anymore.

**Comment by vegai** [comment]
https://github.com/rust-lang/rust/pull/32005
