### ISSUE TITLE
Tuples should be fundamental

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#31682]
Test case:

``` rust
use std::net::{Ipv4Addr, Ipv6Addr, SocketAddr, ToSocketAddrs};
use std::{vec, io};

pub enum Host {
    Domain(String),
    Ipv4(Ipv4Addr),
    Ipv6(Ipv6Addr),
}

impl ToSocketAddrs for (Host, u16) {
    type Iter = vec::IntoIter<SocketAddr>;
    fn to_socket_addrs(&self) -> io::Result<Self::Iter> {
        unimplemented!()
    }
}
```

Output with rustc 1.8.0-nightly (fae516277 2016-02-13):

``` rust
a.rs:10:1: 15:2 error: the impl does not reference any types defined in this crate; only traits defined in the current crate can be implemented for arbitrary types [E0117]
a.rs:10 impl ToSocketAddrs for (Host, u16) {
a.rs:11     type Iter = vec::IntoIter<SocketAddr>;
a.rs:12     fn to_socket_addrs(&self) -> io::Result<Self::Iter> {
a.rs:13         unimplemented!()
a.rs:14     }
a.rs:15 }
a.rs:10:1: 15:2 help: run `rustc --explain E0117` to see a detailed explanation
error: aborting due to previous error
```

But the impl _does_ define a type defined in this crate, `Host`.

Is this impl fundamentally problematic, or could coherence rules be extended for tuples?

**Comment by arielb1** [comment]
That's the annoying future compatibility rules. Tuples are currently not `#[fundamental]` - I imagine that we should fix this. cc @nikomatsakis

**Comment by nikomatsakis** [comment]
Hmm. It does seem like tuples ought to be considered fundamental. I'd not be opposed to an RFC on this topic.

**Comment by SimonSapin** [comment]
In case that’s a hint for me to write an RFC: I don’t feel I can since I don’t understand the finer details of coherence rules or what fundamental means in this context, only the end result of “I can’t write this seemingly-reasonable code”.

**Comment by nikomatsakis** [comment]
It wasn't really a hint to *YOU* Simon ;)

Probably this doesn't merit a full RFC actually; an amendment to the existing one might suffice.

**Comment by jashephe** [comment]
Are there any recommended work-arounds for this? I just ran into the same problem (entertainingly, with pretty must the exact code posted in the test case). Has there been any progress on an RFC addition?

**Comment by sharpjs** [comment]
I've also run into this issue.  @jashephe My workaround was just to make my own tuple-like struct and implement the trait for that struct instead.

```rust
impl ToSocketAddrs for Pair<Host, u16> { ...
```

My quick search did not find any RFC for making tuples `#[fundamental]`.  I'm not opposed to writing an RFC for this.  I've been rusting since 1.0, but only learned about `#[fundamental]` a few minutes ago.  I'd need to do a bit of research before attempting my first RFC.

**Comment by nikomatsakis** [comment]
I think treating tuples as fundamental makes sense. We should probably write up an RFC for it.

**Comment by sharpjs** [comment]
Well, then, I'll attempt to write it!

**Comment by Mark-Simulacrum** [comment]
I'm told that @nikomatsakis is the person to speak to why tuples aren't fundamental. @arielb1 says that they aren't sure why this is the case.

**Comment by Mark-Simulacrum** [comment]
Nominating for lang team. I believe we should close this issue in favor of one on the rfcs repo, though it seems unlikely that unless someone motivated steps up to write the RFC it'll happen. Perhaps we could mentor someone? I recall @nrc had a mentoring repo for RFCs...

**Comment by Mark-Simulacrum** [comment]
Closing. If someone wants to pursue this, please follow the RFC process here https://github.com/rust-lang/rfcs#before-creating-an-rfc. There's no real point in the lang team discussing this until that happens.

**Comment by cramertj** [comment]
This is actually included as a part of my [variadic generics RFC](https://github.com/rust-lang/rfcs/pull/1935). It might be useful to break it out into a smaller proposal, though.
