### ISSUE TITLE
HashSet iteration on drop not elided for Copy elements

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#31711]
If a `HashSet` has `Copy` elements, it doesn't need to visit all elements on drop. The iteration in RawTable's drop still is computed even if the elements have no destructors, which leads to O(n) average complexity even then.

**Comment by rkruppe** [comment]
To be clear, this is also in release mode, right? A while back there was a similar issue for vec but AFAIK that one was only about debug mode.

**Comment by bluss** [comment]
Yes, also in release mode.
