### ISSUE TITLE
There is no way to set connection timeout for TcpStream

### ISSUE THREAD

**Issue by Fiedzia** [rust-lang/rust#31724]
I see that its possible to define timeouts for read/write, but not for initiating connection. I've noticed this while trying to add this to memcached client, and it turned out there is just no way to do it in std lib.

**Comment by alexcrichton** [comment]
This is indeed correct! This is one of the purposes of the [net2 crate](https://crates.io/crates/net2/) (to provide extensions to libstd types). You can use the [`TcpBuilder`](http://doc.rust-lang.org/net2-rs/net2/struct.TcpBuilder.html) to create an in-progress socket, `bind` it, set it to nonblocking mode, and then use `select` or some other similar polling system to wait for it to become readable (timing out if it takes too long)

**Comment by Fiedzia** [comment]
Thanks. It would save me some pain if it was mentioned in the documentation.

**Comment by Fedcomp** [comment]
@alexcrichton i am `bind`ing it to some random local interface and port, converting it to `TcpStream`, setting it to non-blocking mode. What to do next? the socket is not yet connected to remote host.

**Comment by alexcrichton** [comment]
@Fedcomp this is [now implemented on nightly](https://doc.rust-lang.org/nightly/std/net/struct.TcpStream.html#method.connect_timeout) to be used.

**Comment by Fedcomp** [comment]
yeah i just found it out, is there a way to make it on stable rust? (1.18)

**Comment by alexcrichton** [comment]
Not for now, no, it hasn't been stabilized yet (currently no target for stabilization either)
