### ISSUE TITLE
String docs are misleading.

### ISSUE THREAD

**Issue by CamJN** [rust-lang/rust#31744]
Ping @steveklabnik 

https://doc.rust-lang.org/std/string/struct.String.html#method.to_uppercase
https://doc.rust-lang.org/std/string/struct.String.html#method.to_lowercase

These methods are on str not String, which is not hard to see from the examples but only if you read them, and notice that those aren't strings. Probably shouldn't be in the String docs, or at least update the example to be a string which is then deref-coerced to a &str.

I double checked this too just in case, if you try and use then on a real string you get this error: ```no associated item named `to_uppercase` found for type `collections::string::String` in the current scope```

**Comment by frewsxcv** [comment]
Those methods fall under the section with heading:

> Methods from Deref<Target=str>

So it should be implied that these are methods on `str`, not `String`. If you know a way to make this more obvious/clear, definitely share!

**Comment by sfackler** [comment]
Those methods should automatically be callable from a `String` as well: http://is.gd/GrVA5H

**Comment by CamJN** [comment]
@sfackler Then I must have royally screwed up my dev env. XD

@frewsxcv Not sure how to make that more obvious, I tend to grep into the page to find what I want so I don't see the headings at all. And adding a marker to each function saying if it's from that type directly would probably take too much room.

**Comment by frewsxcv** [comment]
It'd be interesting if the `impl` heading used something like [position=sticky](http://html5-demos.appspot.com/static/css/sticky.html) so that it's obvious which section you're in

**Comment by CamJN** [comment]
Yeah that'd be cool.

**Comment by bluss** [comment]
Since it's a method, you'd usually call it like `s.to_uppercase()` and not `Typename::to_uppercase(&s)`. Using the former, the docs are correct -- you can call it.

**Comment by steveklabnik** [comment]
Since this is not a bug, I'm giving it a close. Thanks all!
