### ISSUE TITLE
Trace_macros!() is not effectively gated

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#31753]
Since the trace_macros feature has effect before compilation stops, it's not really effectively gated.

``` rust
#![feature(trace_macros)]
trace_macros!(true);

fn main() {
    println!("{}", 1);
}
```

output:

```
println! { "{}" , 1 }
print! { concat ! ( "{}" , "\n" ) , 1 }
<anon>:1:1: 1:26 error: #[feature] may not be used on the stable release channel
<anon>:1 #![feature(trace_macros)]
         ^~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
```

**Comment by durka** [comment]
Compilation doesn't complete, so is it really a stability hazard?

**Comment by pnkfelix** [comment]
I'd say that gate is pretty *effective*, but it isn't *effect-free* ... ha ha ha...

**Comment by nikomatsakis** [comment]
Discussed in @rust-lang/compiler triage mtg. Since compilation doesn't succeed, it's not really possible to publish crates that rely on this. If we take it away, some people could get upset, but it won't cause widescale breakage (and people can always get upset when you take something away, feature-gate or no). Therefore, P-low.

triage: P-low

**Comment by spazm** [comment]
This behavior is still present and has not been fixed incidentally.

Results from building with cargo 1.37.0:
```
% cargo --version
cargo 1.37.0 (9edd08916 2019-08-02)
% cargo build
   Compiling bar v0.1.0 (/home/andrew/src/github/bar)
note: trace_macro
 --> src/main.rs:5:9
  |
5 |         println!("{}", 1);
  |         ^^^^^^^^^^^^^^^^^^
  |
  = note: expanding `println! { "{}" , 1 }`
  = note: to `{ $crate :: io :: _print ( format_args_nl ! ( "{}" , 1 ) ) ; }`

error[E0554]: #![feature] may not be used on the stable release channel
 --> src/main.rs:1:1
  |
1 | #![feature(trace_macros)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: Could not compile `bar`.

To learn more, run the command again with --verbose.
```

**Comment by durka** [comment]
`trace_macros` is necessary for debugging macros, even on stable. Indeed, if nightly breaks something then you need the trace output to see what changed.

Perhaps we could "fix" this by stabilizing `trace_macros`, but making it an unconditional compile error. So you'd get:

```
$ cargo build
   Compiling bar v0.1.0 (/home/andrew/src/github/bar)
note: trace_macro
 --> src/main.rs:5:9
  |
5 |         println!("{}", 1);
  |         ^^^^^^^^^^^^^^^^^^
  |
  = note: expanding `println! { "{}" , 1 }`
  = note: to `{ $crate :: io :: _print ( format_args_nl ! ( "{}" , 1 ) ) ; }`

error[E0XYZW]: `trace_macros` must be removed to finish compiling
 --> src/main.rs:2:1
  |
2 | trace_macros!(true);
  | ^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

**Comment by petrochenkov** [comment]
I'd close this as working as expected.
As a rule of thumb, feature gates don't *change* any behavior, only produce a non-fatal error (with few exceptions like `feature(nll)`).

Making this macro stable but producing an error will make things like `use std::trace_macros as my_trace;` stable, which we don't want unless `trace_macros` is actually stabilized.

**Comment by nikomatsakis** [comment]
I agree with @petrochenkov that this isn't a real *bug*.

**Comment by petrochenkov** [comment]
Closing, as explained in https://github.com/rust-lang/rust/issues/31753#issuecomment-589556592.
