### ISSUE TITLE
rustc doesn't propagate custom link sections

### ISSUE THREAD

**Issue by rasendubi** [rust-lang/rust#31758]
I have a library that outputs a custom link section (`.isr_vector`). That works fine, but when I link that library into the second one, there is no `.isr_vector` section in the result static library.

That worked before, so I bisected the issue down to a nightly build. The first bad nightly is 2016-02-12 (`rustc 1.8.0-nightly (4b2c7030f 2016-02-12)`). The last good one is 2016-02-11 (`rustc 1.8.0-nightly (3f4227af1 2016-02-10)`).

The full source is here: https://github.com/rasendubi/bkernel/tree/f788e32a2e0493420236cc2642cfaa9c4824203a. The link section is defined in https://github.com/rasendubi/bkernel/blob/f788e32a2e0493420236cc2642cfaa9c4824203a/stm32f4/isr_vector.rs.

**Comment by alexcrichton** [comment]
Do you have a small reproduction that we can test against? It'd help to know how you're linking a library into a second one as that may have something going awry there as well.

**Comment by rasendubi** [comment]
Pushed a small reproduction to https://github.com/rasendubi/rust_link_section. Steps to reproduce:
```
cargo build --release
objdump -h target/release/liblink_section.a | grep .custom_section
```

I also discovered the issue shows only with LTO enabled. Seems that it collects the section because nobody refers to it. Can I instruct the compiler to keep the section?

**Comment by alexcrichton** [comment]
Ah it looks like this was caused by #30830 where we fixed LTO to internalize static symbols that weren't needed as part of the ABI. If you mark the symbol as `#[no_mangle]` for now that should do the trick.

We don't really exhaustively define how we retain symbols, however, especially for LTO, so this is indeed a little bit of a gray area as to what the "correct" behavior here is.

cc @arcnmx

**Comment by rasendubi** [comment]
Thanks! Adding `#[no_mangle]` fixed my build.

I'm closing the issue now. Feel free to re-open if you expect any further activity.

**Comment by arcnmx** [comment]
As much as I would've liked `link_section` to be in the list of extern indicators, it's true that it isn't necessarily correct. See also https://github.com/rust-lang/rfcs/pull/1459, there's definitely discussion to be had about what counts as an externally reachable symbol vs internal symbols that we simply don't want removed, etc.
