### ISSUE TITLE
Tracking issue for ptr::{read,write}_volatile

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#31756]
Tracking issue for https://github.com/rust-lang/rfcs/pull/1467

**Comment by alexcrichton** [comment]
cc @Amanieu, would you be interested in implementing?

**Comment by Amanieu** [comment]
I'll give it a go when I find some free time, hopefully this weekend.

**Comment by oli-obk** [comment]
`write_volatile` can still end up triggering a llvm assertion: #29663

**Comment by alexcrichton** [comment]
:bell: This issue is now entering its cycle-long **final comment period** for tentative stabilization in 1.9 :bell:

The libs team is comfortable with these APIs as-is, but we're pretty worried about stabilizing with the LLVM assert being a known downside. If the assert hasn't been fixed by the time the 1.9 beta release rolls around we'll likely just punt on stabilization of these APIs.

**Comment by Zoxc** [comment]
How will volatile reads/writes not supported by the platform be reported back to the user?

**Comment by nodakai** [comment]
Should `T` be restricted to `Copy`?  I'm not sure

**Comment by jonas-schievink** [comment]
@nodakai `ptr::read` isn't restricted in that way, so my guess is no

@Zoxc ...they can be *not* supported? How? Or did you confuse this with *atomic* reads and writes?

**Comment by Amanieu** [comment]
The assert should be fixed by #32233

**Comment by Zoxc** [comment]
Hm.. it seems LLVM will implicitly split volatile operations that aren't supported. I'm not sure that is desirable semantics.

**Comment by Amanieu** [comment]
C does the same thing so I think it's fine.

**Comment by aturon** [comment]
cc @rust-lang/compiler @rust-lang/lang -- the libs team will be meeting soon to reach a stabilization decision. This API cuts across your concerns as well, so please have a look!

**Comment by huonw** [comment]
Since we don't really have a memory model/Rust abstract machine, we don't have a strong model for what volatile means (the C definition is essentially "execute exactly the operations the C abstract machine would execute"). I imagine this isn't particularly problematic in practice, but it seems like something to keep in mind.

Also, we may want to make sure the documentation doesn't tie the behaviour of these functions to LLVM's definition of volatile? (It currently refers to the LLVM docs, a reference we may want to either remove or explicitly state is non-binding.)

**Comment by alexcrichton** [comment]
The libs team discussed this during triage yesterday and the decision was to **stabilize**.

We discussed what the documentation would look like and we concluded that we should point to C11 instead of LLVM and also add a note saying that the memory model for Rust isn't formally defined so the precise semantics are subject to change, but it's likely to be "suitable as an equivalent to volatile in C" or something like that.
