### ISSUE TITLE
Tracking issue for <[T]>::copy_from_slice

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#31755]
Tracking issue for https://github.com/rust-lang/rfcs/pull/1419

**Comment by alexcrichton** [comment]
cc @ubsan, would you like to implement?

**Comment by ubsan** [comment]
@alexcrichton sure, I'll do it tonight :)

**Comment by ubsan** [comment]
Well... start work on it at least.

**Comment by briansmith** [comment]
What's the reason that it is unstable? I feel like all the arguing that's been argued about it has been argued already. If it weren't destined to be stabilized then I don't think we'd have gotten this far. So, why not just stabilize it right away?

**Comment by bluss** [comment]
All new API starts its life as unstable.

**Comment by comex** [comment]
It might be nice to have a similar memcpy version of Vec::extend_from_slice, although I guess there are enough APIs leading there that specialization might be preferred.  In any case, naively calling `to_owned` on a ~600MB `&[u8]` takes *60 seconds* on an unoptimized build.

**Comment by ubsan** [comment]
@comex yeah...

```rust
let v = Vec::with_capacity(slice.len());
unsafe {
    v.set_len(slice.len());
}
v.copy_from_slice(slice);
```

**Comment by alexcrichton** [comment]
:bell: This issue is now entering its cycle-long **final comment period** for stabilization in 1.9 :bell:

**Comment by alexcrichton** [comment]
The libs team discussed this during triage yesterday and the decision was to **stabilize**
