### ISSUE TITLE
Tracking issue for adding some net2 methods to std

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#31766]
This is a tracking issue for https://github.com/rust-lang/rfcs/pull/1461

**Comment by alexcrichton** [comment]
cc @sfackler, would you be interested in adding these?

**Comment by sfackler** [comment]
Yep, I can take it, but will wait until the next release.

**Comment by alexcrichton** [comment]
Implemented in https://github.com/rust-lang/rust/pull/31945
