### ISSUE TITLE
Investigate using the As-Infinitely-Ranged Integer Model for overflow detection

### ISSUE THREAD

**Issue by Aatch** [rust-lang/rust#31770]
Currently we use "precise" overflow traps, meaning we detect overflow when it happens. However this isn't strictly necessary for a couple reasons:
1. Some calculations have overflow that is "cancelled" out by a later step, for example `a + 100 - 1000`. The `a + 100` step may overflow, but the following `- 1000` step will cancel it out producing the correct result.
2. Overflowed calculations are only a problem if the produced value is observed. This actually came up in the compiler a couple times when overflow checking was first implemented as well as in one of the standard libraries, a value would overflow, but if it did, the value was never actual read from in that case anyway.

[This Paper](http://resources.sei.cmu.edu/library/asset-view.cfm?assetid=9019) (free to download), describes the As-Infinitely-Ranged Integer Model (AIR), which aims to mitigate some of those issues without losing safety.

**Comment by rphmeier** [comment]
I'd be interested in working on this over the next few weeks.

**Comment by pcwalton** [comment]
I think this needs an RFC, no?

**Comment by Aatch** [comment]
@pcwalton maybe. I just realised that we didn't have an issue around it, so I opened one. I think it falls into a grey area, since it's kinda user-visible, but kinda isn't. If someone wants to do an RFC though, that's fine.

**Comment by arielb1** [comment]
@aatch

This is a bit more than "kinda" user-visible. It allows for panics to occur at unexpected places, which unsafe code must take care of.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this in favor of a post on https://internals.rust-lang.org/ if we're still interested in this.
