### ISSUE TITLE
Arithmetic overflow when working with HashMap

### ISSUE THREAD

**Issue by dragostis** [rust-lang/rust#31790]
I have a `HashMap` defined as follows:
```
HashMap<String, Box<HashMap<u32, Box<Fn(&Rc<RefCell<MRuby>>, Value) -> Value>>>>
```

On Yosemite I get no errors, but it fails on Linux:
```
panicked at 'arithmetic operation overflowed', ../src/libstd/collections/hash/table.rs:626
```

[Travis](https://travis-ci.org/dragostis/mrusty/builds/110611773) build which failed.

**Comment by apasel422** [comment]
I think this is actually a bug in some of the unsafe code in your PR. I will comment there.

**Comment by dragostis** [comment]
After a bit of debugging, this appears to be an issue with a pointer.
```
let mruby = mem::transmute::<*const u8, &Rc<RefCell<MRuby>>>(ptr);

let borrow = mruby.borrow(); // here borrow.methods has a different value from the original one created in MRuby::new()
```
`methods` pointer is differe [here](https://github.com/dragostis/mrusty/blob/8e49823c390b342006318fabe251e73057bb39bf/src/mruby.rs#L204) and [here](https://github.com/dragostis/mrusty/blob/8e49823c390b342006318fabe251e73057bb39bf/src/mruby.rs#L62) on Linux but not on Yosemite.
