### ISSUE TITLE
`-C soft-float` silently ignored on x86

### ISSUE THREAD

**Issue by petevine** [rust-lang/rust#31798]
On 32-bit `x86` compiling with `-C soft-float` produces a binary but judging from the generated assembly this option is silently ignored.

Even if it's silly to expect this to work in absence of library support, shouldn't a warning be printed at least?

**Comment by GuillaumeGomez** [comment]
I think it might be a good idea to prevent users in case this option cannot be run.

**Comment by petevine** [comment]
Provided it's not too difficult I probably wouldn't want to tread on your patch anyway ;)
What exactly were you suggesting?

**Comment by GuillaumeGomez** [comment]
Just to provide a short code sample in here to help to save some time. :)

**Comment by petevine** [comment]
I know, it was a pun.  Are we talking about a warning or an error?

**Comment by GuillaumeGomez** [comment]
My bad! :p 

Since it's unavoidable, displaying an error which says something like "this option is not available on this computer" just before leaving seems fine to me.

Do you confirm @Manishearth?

**Comment by Manishearth** [comment]
I suggest we add a warning, not error. Often such flags are passed down by the build system with a "make it work if possible" intention, so we shouldn't crash.

**Comment by nagisa** [comment]
It is a bug we ignore the option and we should fix that instead. Software float emulation is possible regardless of target, but might need some extra libraries (e.g. `-lsoft-fp`) being linked in.

**Comment by petevine** [comment]
https://github.com/rust-lang/rust/pull/36261
