### ISSUE TITLE
Rustc does not stop on error.

### ISSUE THREAD

**Issue by KalitaAlexey** [rust-lang/rust#31804]
```rust
fn main() {
    println!("Hello, world!");
    let
}
```
It outputs
```
src/main.rs:4:1: 4:2 error: unexpected token: `<eof>`
src/main.rs:4 }
              ^
src/main.rs:4:1: 4:2 error: unexpected token: `<eof>`
src/main.rs:4 }
              ^
```
again and again. It does not stop.

```
rustc 1.8.0-nightly (57c357d89 2016-02-16)
```

**Comment by eddyb** [comment]
cc @nrc I think this is actually a feature.

**Comment by KalitaAlexey** [comment]
@eddyb What do you mean by feature? The Compiler does not stop. It spins three cores.

**Comment by eddyb** [comment]
@KalitaAlexey so it does this in a loop? My bad, I didn't understand.

**Comment by arielb1** [comment]
We got to fix that in beta.

**Comment by nikomatsakis** [comment]
triage: P-high

**Comment by dimbleby** [comment]
Introduced by #31555, according to a bisect.

**Comment by nikomatsakis** [comment]
Reassigning to @nrc now that he's back
