### ISSUE TITLE
Choice of philosophers is offensive

### ISSUE THREAD

**Issue by groucho1890** [rust-lang/rust#31817]
The choice of philosophers in section 3.2 of the Rust book is extremely offensive.

A few examples: Butler has publicly categorized the terrorist group Hezbollah as a "progressive social movement". Foucault has been a strong supporter of the radical Islamic revolution in Iran. The "philosophy" of Karl Marx is one of violence and divisiveness which has led and continues to lead to death and poverty worldwide. In the realm of social issues, it must be mentioned that he (and his bourgeois supporter, Engels) were homophobic and racist, making his inclusion in the list even more disrespectful to those minority groups. 

This choice of names is therefore offensive and unquestionably touches on sensitive issues which are not in any manner related to the Rust programming language. It is thus clearly in violation of Rust's Code of Conduct.

The author's views on these subjects do not belong on technical documentation and should not be inflicted upon Rust's community.

Please note that while I'm using a one-off account, this is not a troll. It's merely for protection against the kind of retaliation that has become common in unsafe environments that do not respect conflicting ideas, such as unfortunately Github has become.

**Comment by bluss** [comment]
Please see the nightly version of the book before reporting bugs: http://doc.rust-lang.org/nightly/book/

There are no philosophers in the book in the current version. Thank you anyway!

**Comment by retep998** [comment]
Clearly we should never use humans in the documentation as someone will always take offense at whatever selection of humans we have. There were earlier issues also taking offense at various choices of pronouns and genders for the philosophers.

In my opinion the only real solution is to use cute fuzzy rabbits which nobody could possibly take offense at.
