### ISSUE TITLE
rustdoc doesn't generate proper sublists from markdown

### ISSUE THREAD

**Issue by zetok** [rust-lang/rust#31826]
```
rustdoc 1.6.0 (c30b771ad 2016-01-19)
binary: rustdoc
commit-hash: c30b771ad9d44ab84f8c88b80c25fcfde2433126
commit-date: 2016-01-19
host: x86_64-unknown-linux-gnu
release: 1.6.0
```

Reproducible: Always

Steps to reproduce:
1. `rustdoc -o ./ file.md`

Content of `file.md`:
```
% title

some list

- 1st level
  - 2nd level
    - 3rd level
      - 4th level
        - 5th level
      - 4th levelv2
    - another 3rd level
  - and a 2nd level
```

rustdoc output:
![rustdoc output](https://cloud.githubusercontent.com/assets/3148759/13238023/1a6a9c8c-d9c8-11e5-8f2f-6959916115ae.png)

↓ sublists
http://spec.commonmark.org/dingus/?text=-%20a%0A%20%20-%20b%0A%20%20%20%20-%20c%0A%20%20%20%20%20%20-%20d%0A%20%20%20%20%20%20%20%20-%20e%0A%20%20%20%20%20%20-%20f%0A%20%20%20%20-%20g%0A%20%20-%20h%0A-%20i%0A

And how gh markdown renders it:

===
- 1st level
  - 2nd level
    - 3rd level
      - 4th level
        - 5th level
      - 4th levelv2
    - another 3rd level
  - and a 2nd level

**Comment by vlastachu** [comment]
Hello, I'm absolutly noob and there is a bit of research: 

1. rustdoc renders markdown by own [markdown implementation](https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/markdown.rs)
2. That implementation is set of bindings to [hoedown (C lib)](https://github.com/hoedown/hoedown)

My plan for the evening: 

1. Check rustdoc html 
2. Check isolated html::markdown output
3. Check hoedown output 

As far as I can see hoedown is widely usable lib, so I can wait bug on maximum top level of render like building final html of rustdoc, or css magic.

**Comment by vlastachu** [comment]
Well, after all hoedown shows the same result.

```html
<p>% title</p>

<p>some list</p>

<ul>
<li>1st level

<ul>
<li>2nd level</li>
<li>3rd level

<ul>
<li>4th level</li>
<li>5th level</li>
<li>4th levelv2</li>
</ul></li>
<li>another 3rd level</li>
<li>and a 2nd level</li>
</ul></li>
</ul>
```

You can use 4 spaces or tabs for expected result. ~~Also it may be necessary to inform author of hoedown, but I am not sure that this is bug, because markdown is not standardized.~~
 
I found very close [issue](https://github.com/hoedown/hoedown/issues/117) in hoedown. There is discussion about CommomMark support https://github.com/hoedown/hoedown/issues/119 

Possibly this issue should be closed.

**Comment by steveklabnik** [comment]
Thanks for the investigation @vlastachu ! I do think this should be closed as an upstream issue.

I would like to see rustdoc use a commonmark-compatible tool, but we haven't gotten the chance to do it yet. That's the only way I see this being resolved. Thanks again!
