### ISSUE TITLE
Utilize `if..let` instead of single `match` branch

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#31820]
https://github.com/rust-lang/rust/blob/98a59cf57e02b6e6a5a3bd74eb47b1422eaacc53/src/librustc_trans/trans/type_of.rs#L320-L323

More info: https://doc.rust-lang.org/book/if-let.html

**Comment by eddyb** [comment]
There are `match`es like this *all over the place*. I just replaced some of the ones in `trans` in a branch I'm working on atm.

**Comment by durka** [comment]
Clippy's [`single_match` lint](https://github.com/Manishearth/rust-clippy/wiki#single_match) should help finding them.

**Comment by nxnfufunezn** [comment]
or maybe this would help 
```bash 
ag "match.+\n(\s+)Some(.+)\n(\s+)(None|_) => (\(\)|\{\})"
 ```

**Comment by dileepbapat** [comment]
can I pick this up?

**Comment by frewsxcv** [comment]
@dileepbapat Go for it! Let us know if you need any help

**Comment by di1** [comment]
@frewsxcv let me know if this is ok

**Comment by dileepbapat** [comment]
@frewsxcv let me know if this is ok

**Comment by frewsxcv** [comment]
@dileepbapat Looks good, nice job! Your changes are waiting in a queue to be merged:

http://buildbot.rust-lang.org/homu/queue/rust

**Comment by durka** [comment]
This can be closed now.

**Comment by frewsxcv** [comment]
Thanks again @dileepbapat!
