### ISSUE TITLE
Documentation of libstd is lacking of comments on trait implementations

### ISSUE THREAD

**Issue by ticki** [rust-lang/rust#31821]
Currently, a lot of the implementation on types in libstd is unexplained, and the behavior of these are not always obvious.

For example,`PartialOrd<char>` for `char` is unexplained. Since the exact behavior can unobvious in this case, it should be properly documented (that it compares the unicode codepoints, based on their value). This is just one of the many undocumented implementations in libstd.

**Comment by steveklabnik** [comment]
This is because `rustdoc` currently hides them, even if they're there.

**Comment by steveklabnik** [comment]
(I don't know when this was changed but it was long ago, I think when @alexcrichton was fixing up rustdoc)

**Comment by Ticki** [comment]
No, they're not hidden. Look at `impl Rem<u32> for u32` in https://doc.rust-lang.org/std/primitive.u32.html.

They simply lack of documentation, not hidden.

**Comment by bluss** [comment]
Docs on impl methods are hidden, doc on impl block is not. Some impls contain docs that need to be moved to the impl block.

**Comment by steveklabnik** [comment]
Ah.

I would still prefer that they just be shown, personally.

**Comment by Ticki** [comment]
Ah, okay. Though, the docs on impl blocks certainly are missing.

**Comment by frewsxcv** [comment]
Somewhat related: https://github.com/rust-lang/rust/pull/23271

**Comment by mitaa** [comment]
Related: #24838

**Comment by steveklabnik** [comment]
Triage: no changes

**Comment by steveklabnik** [comment]
Triage: this is too broad and vague to be useful. If you'd like to see a specific implementation documented better, please open issues that are specific to that impl, or if you'd like to do an audit of every useful one, get in touch and we can see how to tackle it. Thank you!
