### ISSUE TITLE
Potential infinite loop/exponential slow down on infinite type

### ISSUE THREAD

**Issue by jroesch** [rust-lang/rust#31833]
This program causes the compiler to loop for 30+ seconds (I killed it before waiting). I reduced this from the head of [hubris](https://github.com/hubris-lang/hubris) which runs for several minutes while consuming 98% of my CPU. 

```rust
pub enum BindingMode {
    Implicit,
    Explicit
}

pub struct Binder {
    ty: Term,
    mode: BindingMode,
}

pub enum Term {
    Forall {
        binder: Binder,
        term: Box<Term>,
    },
    Lambda {
        binder: Binder,
        body: Box<Term>,
    },
}

fn main() {}
```

My current best guess is that there is a bug reporting that this type is infinite and then some processing on it loops forever. If you remove one of the cases from the `Term` enum it will compile. 

Boxing the `Term` in `Binder` fixes this.

```rust
pub enum BindingMode {
    Implicit,
    Explicit
}

pub struct Binder {
    ty: Box<Term>,
    mode: BindingMode,
}

pub enum Term {
    Forall {
        binder: Binder,
        term: Box<Term>,
    },
    Lambda {
        binder: Binder,
        body: Box<Term>,
    },
}

fn main() {}
```
rustc version: `rustc 1.8.0-nightly (c92e910c1 2016-02-21)`

**Comment by paulstansifer** [comment]
I hit this bug (or a similar one), also, and was able to minimize it pretty far:

```
#[derive(Clone)]
enum Type {
    Function(Type),
    Term(Type)
}
```

Removing either of the arms of the enum or the `#[derive(Clone)]` fixes the problem. `-Z time_passes` confirms that it is the typechecker that is taking forever.

**Comment by mitaa** [comment]
Seems to be fixed on beta, and nightly.

**Comment by alexcrichton** [comment]
Yay!
