### ISSUE TITLE
Missing Default for std::sync::Condvar

### ISSUE THREAD

**Issue by vi** [rust-lang/rust#31865]
It has `fn new()`, so there should be no problem for `Default`.

See also: https://github.com/Manishearth/rust-clippy/issues/705

**Comment by llogiq** [comment]
I'm going to hijack this issue and add missing `Default` impls for `Mutex<T>` and `RwLock<T>` where `T: Default`.

I'll have a PR ready shortly.

**Comment by tbu-** [comment]
Fixed by #32785.
