### ISSUE TITLE
Add warning for hexdec literals with mixed case-sensitivity

### ISSUE THREAD

**Issue by Robbepop** [rust-lang/rust#31860]
In Rust it is possible to define hexadecimal number literals with

```rust
let v1 = 0xff;
let v2 = 0xAC;
```
After the `0x` preix the programmer may use numerals from `0..9`, `a..f` and `A..F`.
So this makes it also possible to mix the case-sensitivity even within the same numeric literal:
```rust
let v3 = 0xFfEeDdCc;
```
It is also possible to suffix the literal for type explicity:
```rust
let v1 = 0xaai32; // may be confusing
let v2 = 0xAA_i32; // clear intent!
assert_eq!(v1,v2);
```
This is not only likely unreadable but also may lead to confusion:
```rust
let v4 = 0xFFAA_f32;
```
In this case the programmer wanted to instantiate a float (note the `f32` suffix) and it compiled fine.
However, it is not a float literal but still a valid hexdec literal which makes absolutely sense following the current rules.
```rust
let v5: f32 = 0xFFAA_f32; // error: mismatched types!
```
**Improvement:**
A possible improvement (not only to readability) is to add a warning when the user mixes case-sensitivity within the same hexa decimal literal as this would at least prevent the above case.
Using lower-case literals would still allow this possible trap, however it looks less tricky:
```rust
let v6 = 0xffaa_f32;
let v7 = 0xffaaf32;
assert_eq!(v6,v7);
```
**Better Solution:**
In my opinion an even better improvement would be to disallow lower-case characters in hexdec literals to make numeric suffixes more significant within the literal but I guess many people would disagree with this suggestion.
```rust
let e1 = 0xFF_AA00_11; // ok
let e2 = 0xFf_aAbB; // warning (or error!)
let e3 = 0xFA_CC_f32; // warning (or error!)
let e4 = 0xFACC_i64; // intent is clear!
let e5 = 0xFACCi32; // intent is still clearer than the following:
let e6 = 0xfacci32; // looks confusing
```
Another minor improvement for readability would be to allow suffixes (for hexdec literals) only when the last character of the literal is an `_` (underscore).

**Feasibility**
This may break code if errors are used instead of warnings, however it should be possible to create tools that fix such code automatically.

**Comment by GuillaumeGomez** [comment]
@Robbepop: Nicely found! I think we should also add a warning to force users to add '_' because the hex number and the type (it's even more important with float types). However, I think an RFC might be needed in here.

**Comment by nagisa** [comment]
Consider filling issue to https://github.com/Manishearth/rust-clippy instead.

**Comment by GuillaumeGomez** [comment]
@nagisa: Some clarification should be added in here, not only adding a lint.

**Comment by nagisa** [comment]
@GuillaumeGomez lints can print their own HELPs and HINTs too. Either way I very strongly doubt this will land into rustc since it is a very preference-based feature request.

**Comment by steveklabnik** [comment]
New lints require an RFC, and yeah, we suggest starting off in clippy here. Yes, there are other changes than just adding a lint, but they are also potentially breaking, and so would be serious enough to merit an RFC as well. So I'm gonna give this one a close. Thanks!

**Comment by Robbepop** [comment]
I also think that this may be suitable for more than just a lint.
The problem with hexdec literals and their definition is that they make it hard for future Rust specifications from adding support for user-defined literals as in C++.

**Problem**
The current definition is unambiguous because the current suffixes for hexdec literals start with letters `i` and `u`, but what about future Rust specifications that want to add other suffixes starting with any letter from `a` to `f`?

**Example**
E.g. what about a "complex" user-defined literal that may come in future Rust specifications?
```rust
let c: Complex = 1.337complex; // ok
```
A `complex` (or just `comp` or `c`) suffix may not be the best example at this point but it still demonstrates the ambiguity for hexdec literals.
```
let c = 0x1337complex; // compiler would read `0x1337c` as the number and would try to suffix it with `omplex` and it its current state would literally state the following:

> src/parser/lexer.rs:500:12: 500:25 error: invalid suffix `omplex` for numeric literal
> src/parser/lexer.rs:500 		let c = 0x1337complex;

By enforcing the underscore (`_`) before any suffix of hexdec literals with a warning this stalemate could be prevented opening the path for the future evolution of Rust.
