### ISSUE TITLE
Why can't we have mutable iterator on BinryHeap ?

### ISSUE THREAD

**Issue by gbersac** [rust-lang/rust#31888]
Not only, we can't have mutable iterator on `BinaryHeap`. We first convert it to a `Vec` using `BinaryHeap::into_vec()` and then create it back from a `Vec` using `BinaryHeap::from`. 

By the way, I found the `BinaryHeap` container not practical.

**Comment by sfackler** [comment]
Mutations of the entries in the heap could change their sort order. Turning it into a Vec and back will handle that properly.

**Comment by gbersac** [comment]
Yes, but is there an overhead to use `into_vec` and `from` ? It may slow down the all thing.

**Comment by pczarn** [comment]
@gbersac
`into_vec` has zero overhead, and `from` only restores the order, so it couldn't be faster with a special function.

**Comment by gbersac** [comment]
Ok, thanks.
