### ISSUE TITLE
The "Traits" section in the book doesn't mention "Self"

### ISSUE THREAD

**Issue by wesleywiser** [rust-lang/rust#31891]
See https://doc.rust-lang.org/book/traits.html

The [Syntax Index](https://doc.rust-lang.org/book/syntax-index.html) links to that section for "Self" so it should be mentioned in there.

**Comment by steveklabnik** [comment]
I am not really working on the existing book at this point, but if someone wants to take a crack at it, I would be happy to take a PR!

**Comment by wesleywiser** [comment]
Thanks Steve. I'll take a shot at it.

**Comment by munyari** [comment]
Just opened a PR

**Comment by reeze** [comment]
This can be closed.
