### ISSUE TITLE
Allow item macros to take type parameters

### ISSUE THREAD

**Issue by eholk** [rust-lang/rust#3190]
It might be able to write item macros that have type parameters associated with their identifier, such as:

```
generate_something! foo<T, U> { }
```

Especially in cases where we are making macros that expand into functions, enums, types, etc., it might be nice to have a single set of type parameters for all of the generated code.

This issue is relevant to #3165.

**Comment by kmcallister** [comment]
Closing this as wishlist / RFC.  It's something to consider alongside the "item macro sugar" that was proposed (and rejected) for RFC 453.
