### ISSUE TITLE
Consider changing the non_snake_case lint to skip names of #[no_mangle] extern functions

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#31924]
Since the function is tagged `#[no_mangle]` the exact name presumably has to exactly match something that another system is expecting, which may not be snake case. For example, JNI bindings will look something like

``` rust
#[no_mangle]
unsafe extern "C" fn Java_package_name_ClassName_methodName(...) { ... }
```

**Comment by steveklabnik** [comment]
Modifying lints requires an RFC now, as it can impact a LOT of code.

**Comment by steveklabnik** [comment]
(By modifying I mean "major changes" not bugfixes)

**Comment by aturon** [comment]
Hm, while I think **new** lints definitely want an RFC, modifications to existing ones can probably go through the lang team's nomination process, leading to either an immediate decision or request for RFC.

**Comment by steveklabnik** [comment]
I'm fine with that, just following (what I thought was) procedure. :smile:
