### ISSUE TITLE
Unclear paragraph in The Book

### ISSUE THREAD

**Issue by xrisk** [rust-lang/rust#31927]
> This is how you generally **move from ‘crash on error’ to ‘actually handle the returned by parse() is an** enum just like Ordering, but in this case, each variant has some data associated with it: Ok is a success, and Err is a failure.

From https://doc.rust-lang.org/book/guessing-game.html#looping (emphasis mine).

**Comment by steveklabnik** [comment]
Agreed, this is a bit unclear. I would say maybe

> The way you move from "crash on error" to "handle the error" is an enum...

Thoughts?

**Comment by Luke-Nukem** [comment]
I saw someone already had a go at clarification. Good work! I Added some further refinements which should help enhance it a bit more.

**Comment by steveklabnik** [comment]
This was fixed!

**Comment by xrisk** [comment]
👍 :smile:
