### ISSUE TITLE
Nightly docs missing relevant float parsing impls

### ISSUE THREAD

**Issue by rkruppe** [rust-lang/rust#31948]
#31903 hid all trait impls from `doc(hidden)` modules. This was a step in the right direction, since it removed several dead links (mentions of traits that really should be hidden). Unfortunately currently `FromStr` is implemented in the hidden module `core::num::dec2flt` and thus the current nightly doesn't document this impl at all (neither on the trait's page nor on the primitive pages). For the same reason, `ParseFloatError` doesn't seem to implement any traits (except `Error` o.O perhaps because of the bound on the associated type `FromStr::Error`).

**Comment by rkruppe** [comment]
cc @mitaa @alexcrichton 

Since AFAIK one can't override this behavior with an explicit `#[doc(..)]` annotation (and several of the traits that `ParseFloatError` is missing are derived) I fear we have to either ditch the strategy introduced by #31903 or move `impl FromStr for $float_type` and `ParseFloatError` back up to `core::num`. The latter doesn't help other code which might have the same problem. Is there an easy way to implement a "if the trait or implementing type is hidden, don't document the impl" heuristic?

**Comment by alexcrichton** [comment]
To me when thinking about #31903 it seemed like a mild antipattern to have public interfaces you want documented in a `#[doc(hidden)]` module. Would it be "easy enough" to move these impls up to `core::num`? If privacy or something gets in the way we can reconsider reverting perhaps.

**Comment by rkruppe** [comment]
Well it used to be that way, then (IIRC) you moved the impls into `core::num::dec2flt`, so it should just work.

**Comment by mitaa** [comment]
FWIW, I thought of another related testcase which is broken in the same way
```rust
// foo.rs
extern crate bar;

pub use bar::Foo;
```
```rust
// bar.rs
pub struct Foo;

mod private {
    trait Bar {}
    impl Bar for ::Foo {}
}
```
(the impl-inlining code doesn't look at privacy at all)

AIUI this would need to be solved in the same or similar way as necessary for
> if the trait or implementing type is hidden, don't document the impl

**Comment by alexcrichton** [comment]
Oh maybe it was privacy related in that case...
