### ISSUE TITLE
rustc/rustdoc invocation fails during build due to lack of sysroot / chroot build issues

### ISSUE THREAD

**Issue by apaprocki** [rust-lang/rust#31943]
For starters, I need to build rust within a `chroot` jail to generate a package. This jail has no access to `/proc`, and this causes issues with `librustc` here:

```
thread 'rustc' panicked at 'can't determine value for sysroot', src/librustc/session/filesearch.rs:165
```

I was able to work around this by explicitly passing the `--sysroot` to `rustc` during the build process by passing appropriate `..._STAGE#` flags for each stage when invoking `configure` and `make`:

```
SYSROOT:=$(shell pwd)/x86_64-unknown-linux-gnu/stage
RUSTFLAGS_STAGE0:=--sysroot $(SYSROOT)0 $(RUSTFLAGS)
RUSTFLAGS_STAGE1:=--sysroot $(SYSROOT)1 $(RUSTFLAGS)
RUSTFLAGS_STAGE2:=--sysroot $(SYSROOT)2 $(RUSTFLAGS)
RUSTFLAGS_STAGE3:=--sysroot $(SYSROOT)3 $(RUSTFLAGS)
```

This allows all of the `rustc` invocations to work properly and the build to work. The documentation build fails for the same reason because it invokes `rustdoc`, and there is no way to pass a `--sysroot` to `rustdoc` that I can see:

```
CFG_LLVM_LINKAGE_FILE=/tmp/rust-1.6-1.6.0-0/x86_64-unknown-linux-gnu/rt/llvmdeps.rs LD_LIBRARY_PATH=/tmp/rust-1.6-1.6.0-0/x86_64-unknown-linux-gnu/stage2/lib:$LD_LIBRARY_PATH x86_64-unknown-linux-gnu/stage2/bin/rustdoc --cfg dox --cfg stage2  src/libstd/lib.rs
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'can't determine value for sysroot', src/librustc/session/filesearch.rs:165
```

IMO, the best fix here is to modify `librustc` to fall back on extracting the path from `argv[0]` (in the C sense) if `/proc` does not exist. If that was done, then none of these `sysroot` games would be necessary because it is always invoked with the fully qualified path. Is that a viable option?

Without that option, can a `--sysroot` option be added to all the other binaries built/used during the build? `rustdoc`, `rustbook`, `error-index-generator`, etc..

**Comment by apaprocki** [comment]
`librustc` just calls into `libstd` `sys/unix/os.rs` for `current_exe()`, so change in the behavior would need to go there.

**Comment by apaprocki** [comment]
Confirmed that with the `RUSTFLAGS_STAGE#` flags above and passing `--disable-docs` to `configure` results in a successful build in a `chroot` jail.

**Comment by steveklabnik** [comment]
@apaprocki are you still seeing this today? A lot has changed with the build system since 2016.

**Comment by Dylan-DPC** [comment]
Closing this as build system has changed a lot since this issue was created
