### ISSUE TITLE
SipHasher should derive Eq

### ISSUE THREAD

**Issue by Noctune** [rust-lang/rust#31949]
It would be useful to check if two hashers are in the same state. For example, I need a bloom filter that supports efficient union operations. Iff two bloom filters have equal hashers and size, union is as easy as bitwise OR the filters together.

While we're at it, might as well derive some other traits too. Hash would be useful. Ord maybe, though possible, it doesn't make that much sense other than for storing SipHashers in a BTree or the like.

This is technically a change to the standard library, though a very minor one, so does it need an RFC or should I just make a pull request?

**Comment by sfackler** [comment]
I'd just open a PR for something small like a new derived impl.

**Comment by Noctune** [comment]
Closing. It probably makes more sense to make RandomState implement Eq instead (see #31975).
