### ISSUE TITLE
Some doc links are broken under core

### ISSUE THREAD

**Issue by aidanhs** [rust-lang/rust#31955]
For example, https://doc.rust-lang.org/core/ptr/index.html, click on "See also the pointer primitive types".

This can be perplexing if you've accidentally entered the `core` area by clicking on the 'wrong' search result, because now all your searches throw up results from `core` first and you end up with 'not found'. I've had this happen to me a few times over the past week and I've only just figured out what causes it.

**Comment by steveklabnik** [comment]
It's be cause those links are written by hand from the perspective of std, and the docs are blindly the same between the two.

There's another bug open about this...

**Comment by aidanhs** [comment]
Ah ok, I did have a search for something related but couldn't find anything - feel free to close.

**Comment by steveklabnik** [comment]
Ah, I found it! https://github.com/rust-lang/rust/issues/30214

Let's use that one :+1: Thanks again for reporting!
