### ISSUE TITLE
Minor improvement to docs for rc::Rc

### ISSUE THREAD

**Issue by lukaslueg** [rust-lang/rust#31950]
The docs for `try_unwrap()` currently read

> Unwraps the contained value if the Rc<T> has only one strong reference.

If I read this correctly, what it is actually saying is

> Unwraps the contained value if and only if the Rc<T> has exactly one strong reference.

Is this what is says?

**Comment by steveklabnik** [comment]
Yes, that's correct. I'm writing a patch to clarify right now.
