### ISSUE TITLE
separate rust-format or rustfmt tool that does the pretty-printing

### ISSUE THREAD

**Issue by dbp** [rust-lang/rust#3195]
It would be really nice to have the pretty printer be good enough to use it as a code formatter, ala gofmt. It still has some issues (I've been working on it), but it is reasonably close to being usable in that way.

But, the commandline invocation is kind of unwieldy (and feels redundant). It seems like --pretty should just pretty print, and other stuff should be handled secondarily, ie with:

--pretty-expanded
--pretty-typed
--pretty-expanded-identified
--pretty-identified

Alternatively, perhaps it would make more sense to actually split it into a separate binary, called rustfmt (or, in longer-keyword land, rustformat).

Thoughts?

**Comment by SirVer** [comment]
+1 for this. Feels pretty essential these days with clang-format (great!) and gofmt (so-so) setting standards.

**Comment by caizixian** [comment]
What's the status of this?

**Comment by steveklabnik** [comment]
The status is the same. Would love to have it, don't have one yet.

**Comment by caizixian** [comment]
@steveklabnik Is there any official style guide?

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust-guidelines

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#648
