### ISSUE TITLE
libstd fails to build on emscripten

### ISSUE THREAD

**Issue by Thinkofname** [rust-lang/rust#31951]
https://github.com/rust-lang/rust/blob/master/src/libstd/os/mod.rs#L38 
The linux os module is named `emscripten` when targeting javascript but as of https://github.com/rust-lang/rust/commit/aa23c98450063992473d40d707273903f8a3937d the linux module references itself directly https://github.com/rust-lang/rust/blob/master/src/libstd/os/linux/fs.rs#L19 which fails when its been renamed to `emscripten`

**Comment by gifnksm** [comment]
I believe #31986 fixes this.

**Comment by alexcrichton** [comment]
Thanks @gifnksm
