### ISSUE TITLE
Valgrind tests fail when compiled dynamically

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#31968]
Right now on our bots we're basically in a state where if valgrind rpass tests are compiled dynamically they will all fail, but when compiled statically they will pass. I'm not really sure what's going on unfortunately, but this is either a bug in valgrind or a bug with us, and we should know precisely what it is to ensure something more sinister isn't lurking.

Some links:
- 595d5b2 - first pass at linking tests statically, fixed #31328 
- https://github.com/rust-lang/rust/pull/31928#issuecomment-190304776 - another pass at linking all tests statically
- [Example failures](https://gist.github.com/alexcrichton/b3c73c6a2acf41876bb0)

**Comment by nagisa** [comment]
All the failures seem to be within platform’s dynamic loader. Here’s a few things to try:

1. Does updating kernel+glibc to the most recent versions (4.4-ish and 2.23-ish, respectively) help?
2. Does downgrading kernel+glibc to some older version help?
3. Does non-linux/non-glibc work correctly?

**Comment by cyplo** [comment]
Any news/changes on this one ?
