### ISSUE TITLE
Should we make rustbook as a submodule?

### ISSUE THREAD

**Issue by adamcavendish** [rust-lang/rust#31961]
The repo of rustbook no longer builds, so if we can make rustbook a submodule, then we can update the cargo rustbook to the latest version. And enables to install rustbook via `cargo install rustbook`
https://github.com/steveklabnik/rustbook

**Comment by steveklabnik** [comment]
That's just because I haven't updated it in a while; it's a copy of what's in-tree.

We're pretty much going to replace rustbook with mdbook eventually.

**Comment by steveklabnik** [comment]
So, the core issue here is that I'm hosting `rustbook` as a copy of the in-tree one. It's not that rustbook should be a submodule of me, but that I'm not syncing as often as I should. Please file issues on the repo if it gets out of date.

As such, I'm going to give this issue a close; it's more about my repo than it is about rust itself.

**Comment by steveklabnik** [comment]
(Also, it builds for me. Would you mind opening an issue about this on my repository?)

**Comment by adamcavendish** [comment]
@steveklabnik Thx, it builds now. I'm asking it here because ur repo doesn't allow issues.

**Comment by steveklabnik** [comment]
Ah, sorry about that! :( Glad it's working now.

**Comment by adamcavendish** [comment]
@steveklabnik Sorry, I still cannot get to the issues page. https://github.com/steveklabnik/rustbook/issues (it just redirects to pull-requests)

**Comment by steveklabnik** [comment]
Yes, I had turned them off, because it's not the place you should file issues against rustbook: this main repository is.

**Comment by adamcavendish** [comment]
@steveklabnik So, if next time we got an error, where should we ask?

**Comment by steveklabnik** [comment]
post it here
