### ISSUE TITLE
libtest captures stdout&stderr only on first thread.

### ISSUE THREAD

**Issue by dpc** [rust-lang/rust#31983]
Hi,

When testing anything multithreaded, the output of non-first thread are directly printed on the console.

I wonder if libtest could maybe expose the `set_panic` and `set_print` handlers, so other spawned threads can installed it manually as a workaround.

**Comment by Mark-Simulacrum** [comment]
Closing as duplicate of https://github.com/rust-lang/rust/issues/42474.
