### ISSUE TITLE
Explain different types of iteration

### ISSUE THREAD

**Issue by srinivasreddy** [rust-lang/rust#31991]
in the section Iteration of Vectors - https://github.com/rust-lang/rust/blob/master/src/doc/book/vectors.md, a note about difference between types of iteration would have been better, especially between reference iteration - &vector and ownership iteration - vector.

**Comment by steveklabnik** [comment]
I am not actively working on the in-tree book anymore, but would accept a patch for this.

**Comment by srinivasreddy** [comment]
PR is merged, hence closing this. #32002
