### ISSUE TITLE
rustdoc: Named fields should have their types displayed next to their descriptions

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust#32024]
Right now, the types of (struct / enum variant) fields are only displayed in the "code box" at the top:
![](https://hostr.co/file/970/GDszAZSpSCwx/rscrot_screenshot.png)

But the "code box" is not the usual place to go for documentation, as it is lacking the descriptions written by the author.

The actual descriptions are located further down. How much further depends on how many fields the struct/enum contains, but can be far enough that the "code box" is not visible anymore, so you can't see the types of the fields.
![](https://hostr.co/file/970/Sd7lcMb38r6F/rscrot_screenshot.png)

This is inconvenient. One does not want to jump back and forth between the "code box" and the descriptions to be able to know both the type and purpose of the field.

Furthermore, direct links to struct enum variants drop you off at the description site, so you only get the description, and have to scroll up if you also want to get the type information.

**Comment by birkenfeld** [comment]
This was implemented by #33867 and can be closed.

**Comment by crumblingstatue** [comment]
Neat!
