### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by mmuggli** [rust-lang/rust#32030]
http://doc.rust-lang.org/book/getting-started.html links to 
http://doc.rust-lang.org/book/learn-rust.html in the sentence "You have two options: Dive into a project with ‘Learn Rust’, or start from the bottom and work your way up with ‘Syntax and Semantics’. "

Following that link leads to a 'not found' page.

**Comment by steveklabnik** [comment]
Thank you! This is indeed broken as of stable, but was fixed and will be fixed in the next release, see http://doc.rust-lang.org/beta/book/getting-started.html
