### ISSUE TITLE
Lang item invalid code compiles

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#32033]
The following code compiles whereas it shouldn't:

```Rust
#![feature(lang_items)]

#[lang = "cookie"]
fn cookie() -> ! {
    loop {}
}

#[lang = "cookie"]
fn cookie2() -> ! {
//~^ ERROR: Duplicate lang item found: `cookie`.
//~| NOTE First definition of `cookie` here.
    loop {}
}

fn main() {}
```

cc @brson 
#31957

**Comment by GuillaumeGomez** [comment]
It seems this issue comes from [here](https://github.com/rust-lang/rust/blob/master/src/librustc/middle/lang_items.rs#L156-L164). If the lang_item doesn't already exist, the function won't check it.

**Comment by nagisa** [comment]
I’m not sure this is a problem per se. Namely, us not failing hard on unknown lang items allows #![no_std] users to maintain some compatibility between Rust versions. I.e. there’s a few language items that did exist in 1.0 but do not exist anymore. Crate authors can still define these language items unconditionally and enjoy support across more versions.

**Comment by GuillaumeGomez** [comment]
Hum... At first, I just wanted to check if a local lang item was double defined, but then wondered what was the point to allow them. With this, you can still declare std lang items, but you cannot create new ones. I'm going to wait to have some more opinions before doing anything else.

Thanks @nagisa!

**Comment by nagisa** [comment]
Tagging with T-lang so people won’t miss this.
