### ISSUE TITLE
Rustdoc search results ignore markdown formatting

### ISSUE THREAD

**Issue by cmbrandenburg** [rust-lang/rust#32040]
Using Rust 1.7, a rustdoc search result shown in the browser (as a consequence of pressing the `S` key and entering a search term) displays raw Markdown, not formatted text. For example, take the standard library documentation, press `S`, then enter the search term `trait: Neg`, and the search result will show this text verbatim:

```
The `Neg` trait is used to specify the functionality of unary `-`.
```

Whereas, it should be formatted—i.e., no backticks.

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by camelid** [comment]
triage: still no change

**Comment by camelid** [comment]
I think I have a simple way to solve some cases of this, so I'm assigning myself since this has been open for a long time without a fix.
