### ISSUE TITLE
Array indexing acting as array.get

### ISSUE THREAD

**Issue by Nokel81** [rust-lang/rust#32044]
I know that 
`let ar = [1, 2, 3, 4];`
`ar[4];`
will error out at runtime but
`ar.get(4);`
will return `None`.

Would it make sense for there to be a compiler tag that makes `ar[4]` behave like `ar.get(4)`?

**Comment by alexcrichton** [comment]
Thanks for the report! This would be a pretty significant language change, however, so I think that this probably belongs in the rust-lang/rfcs repo for now. Could you open an issue over there instead?
