### ISSUE TITLE
SipHasher documentation says too much

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#32043]
> Consider this as a main "general-purpose" hash for all hashtables

on http://doc.rust-lang.org/stable/std/hash/struct.SipHasher.html

is not something we should be telling people and the sentence should be removed.

**Comment by sfackler** [comment]
What in particular is wrong with that sentence?

**Comment by nagisa** [comment]
@sfackler we’re telling that some arbitrary hasher should be considered a main hasher (whatever main is supposed to mean here) for hashtables even while we reserve a capability to change (and likely will, eventually) default hasher for hashtables at will. Especially see https://github.com/rust-lang/rust/issues/29754.

**Comment by sfackler** [comment]
Ok, that makes sense. We could drop the hashtable reference entirely or weaken it to mentioning that it it is *currently* the default algorithm for our hash tables, though this may change in the future.
