### ISSUE TITLE
Check for version control conflict markers

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#32059]
See https://twitter.com/whitequark/status/706091651979083776

If a C file has a version control conflict marker (e.g. `<<<<<<<<< HEAD` or `>>>>>>>>>>>>> branch`), clang will helpfully detect it and spit out a more specific parse error. Sounds like something we could be doing too.

**Comment by sekjun9878** [comment]
:+1:

**Comment by tiehuis** [comment]
I'm actually quite interested in implementing this. It looks reasonable enough on a cursory glance.

My initial approach would likely be modifying the lexer itself and identifying conflict markers there. Seems like the most straight-forward approach given the line-based nature of conflict markers. There are probably a few different behaviours that could be explored (do we continue lexing? attempt to parse using one-conflict etc?) but more discussion is probably required before choosing anything complex.

Any suggestions are appreciated.

**Comment by Manishearth** [comment]
That sounds ok to me. Let me know if you have further questions!

**Comment by gchp** [comment]
@tiehuis did you make any progress on this? If not, I'd be interesting if giving it a shot myself...

**Comment by tiehuis** [comment]
I have made some progress, but a few things were still left to do. Been a bit inactive, so feel free to take a go. The rough approach I have which may be of some use) is:

- Modify the lexer at the `<` token scan to perform a scan through the source for a consecutive series of `<` tokens. If we find a match, then assume this is a version control marker and scan for a closing sequence of `>>>>>>>`.
- If a closing sequence is found, then report an error that a warning control marker is found and set a flag indicating that we are currently in a version control statement.
- Continue lexing tokens as normal. We assume that the new-diff contents (before `=======`) are the valid for the sake of better error messages.
- Once we find a `=`, then check if we are in a version-control scan state and scan for the diff marker. If this is the marker, then skip the old-diff and jump to the end of the trailing `>>>>>>>`. We know this exists.

**Comment by Centril** [comment]
cc @matklad re. lexer impl.

**Comment by PoignardAzur** [comment]
Any update on this?

**Comment by Manishearth** [comment]
Lack of people working on this

**Comment by estebank** [comment]
https://github.com/rust-lang/rust/pull/106242 will address some specific cases, but because it happens in the parser and not the lexer, it doesn't have full coverage for all cases people might encounter, but it does cover a few I thought of. At the very least, a check for where bounds, for ADT bodies and type parsing should be added.

**Comment by estebank** [comment]
Closing, we can open new tickets if specific cases are found where the current approach doesn't trigger.
