### ISSUE TITLE
Apparent rustc hang on malformed trait declaration

### ISSUE THREAD

**Issue by bobtwinkles** [rust-lang/rust#32069]
`rustc` appears to hang when there is a malformed trait declaration in a submodule. Specifically, I am able to reliably induce the hang with the following setup:

 1. Create a new project with `cargo new --bin bugtest`
 2. `mkdir src/ui`
 3. Put the following code in `src/ui/mod.rs`
```rust
pub trait Widget {
    pub fn draw(&self)
}
```
`cargo build` will appear to hang. I'm not sure if it's an infinite loop, or just really really slow.

Note the lack of a semicolon after the function declaration. While this is indeed malformed rust code, I would not expect the compiler to be extraordinarily slow to parse this code.

## Meta

```
rustc --version --verbose:

rustc 1.9.0-nightly (7b0b80ae2 2016-03-02)
binary: rustc
commit-hash: 7b0b80ae21a195a5dba91d557f94a96136c27eaf
commit-date: 2016-03-02
host: x86_64-unknown-linux-gnu
release: 1.9.0-nightly
```

**Comment by jonas-schievink** [comment]
You don't actually include that file, so it shouldn't get compiled. Did you forget a step in the reproduction?

**Comment by bobtwinkles** [comment]
I did indeed, you need to declare `mod ui;` in in `main.rs`.

**Comment by dimbleby** [comment]
#31804 again, presumably?

**Comment by bobtwinkles** [comment]
I don't believe so. In this case, the compiler never gets around to
producing an error. In addition, this appears to cause a hang only when the
malformed trait is in a file other than `main.rs`: putting the same code in
`main.rs` produces a compiler error as expected.

>

**Comment by steveklabnik** [comment]
(not _exactly_ an ICE, but hanging forever is close)

**Comment by dimbleby** [comment]
Fixed in the current nightly.  Perhaps this was after all the same as #31804 all along.

```
   Compiling bugtest v0.1.0 (file:///data/dch/bugtest)
src/ui/mod.rs:2:5: 2:8 error: expected one of `const`, `extern`, `fn`, `type`, or `unsafe`, found `pub`
src/ui/mod.rs:2     pub fn draw(&self)
                    ^~~
error: aborting due to previous error
error: Could not compile `bugtest`.

To learn more, run the command again with --verbose.
```

```
rustc --version
rustc 1.9.0-nightly (30a3849f2 2016-03-30)
```

**Comment by bobtwinkles** [comment]
Issue has been resolved, closing.
