### ISSUE TITLE
why shouldn't  we write println!(1) instead of println!("{}",1)

### ISSUE THREAD

**Issue by srinivasreddy** [rust-lang/rust#32065]

**Comment by bluss** [comment]
Is this a question or a bug report?

**Comment by Luke-Nukem** [comment]
@bluss they seem to be comparing it to how other languages "print", eg, Python. Perhaps an explanation on how the **println!** macro works would be good?

**Comment by Thiez** [comment]
Why write `println!("{}", 1)` when you can write `println!("1")`?

**Comment by bluss** [comment]
Note that you can in fact use `println!(1)`. It's an unintentional "feature".

**Comment by Aatch** [comment]
In the absence of an actual issue here, I'm going to just close this.
