### ISSUE TITLE
Duration overflows when created with Duration::new(u64::MAX, u32::MAX)

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#32070]
Creating `Duration::new(u64::MAX, u32::MAX)` results in a duration of 3 seconds.

From the documentation, it's not clear what `Duration::new` is supposed to do on overflow, but right now it silently wraps, whereas its overloaded math operators used explicit checked math.

[Playground link](https://play.rust-lang.org/?gist=b0119465058896b6fe18&version=stable).

I thought that compiling this in debug mode would panic because of overflow but it doesn't.

**Comment by brson** [comment]
Relatedly, I couldn't figure out how to create a maximum-sized Duration.

**Comment by japaric** [comment]
> Relatedly, I couldn't figure out how to create a maximum-sized Duration.

`Duration::new(u64::MAX, NANOS_PER_SEC - 1)` (where `NANOS_PER_SEC = 1_000_000_000`) returns the maximum duration. Perhaps we could add a `Duration::max()` constructor or a `time::MAX_DURATION` constant to make it more obvious.

**Comment by sfackler** [comment]
Could be `Duration::max_value()` to match primitive numeric types.

**Comment by nodakai** [comment]
- https://play.rust-lang.org/?gist=af78de22865a57f7a27c&version=nightly

```rust
#![crate_type="lib"]
pub fn new() -> u32 {
    std::u32::MAX + 10
}
```
↓
```llvm
ret i32 9
```

So constant folding doesn't honor the checked arithmetic semantics?

On the other hand, a `const` item raises a compile error *only when* the value is referenced by a function:
- https://play.rust-lang.org/?gist=7bf14b39e8fd488c46fc&version=nightly
```rust
#![crate_type="lib"]

pub const X: u32 = std::u32::MAX + 10;

// pub fn new() -> u32 { X }
```

**Comment by alexcrichton** [comment]
This has since been fixed, so closing.
