### ISSUE TITLE
Failed to allocate a guard page

### ISSUE THREAD

**Issue by joerg-krause** [rust-lang/rust#32082]
I am cross-compiling a cargo build `hello` for an unsupported ARMv5 target with a musl toolchain. I am using the instructions from [rust-cross-libs](https://github.com/joerg-krause/rust-cross-libs) to successfully build the rustlibs and hello.

I added an debug output to https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/thread.rs#L224 to get the page size used by Rust: `psize: 9459`

However, using a C test file with `long sz = sysconf(_SC_PAGESIZE);` prints a page size of `4096`, which I assume is correct.

I know ARMv5 and arm-*-*-musl are not officially supported, but maybe can give me a hint why `os::page_size()` returns a wrong and obviously page size.

**Comment by alexcrichton** [comment]
Was the standard library recompiled for armv5 as well? Right now I don't think we ship any armv5 standard libraries, nor do we have an armv5 target in the compiler.

Maybe the libc definition of `_SC_PAGESIZE` was wrong as well? Maybe the ABI is wrong? I guess it could be a number of factors.

**Comment by joerg-krause** [comment]
Yes, the standard library was recompiled for ARMv5. Cross-compiling hello for the ARMv5 target works fine with the glIbc, but somehow fails with musl.

I've seen that `_SC_PAGESIZE` is defined as an integer value of `30` both in [musl](http://git.musl-libc.org/cgit/musl/tree/include/unistd.h) and [stdlibc](https://github.com/rust-lang/libc/blob/2a48d49c22a2e3cac5b401c26d1e2ad6aedfcaa1/src/unix/notbsd/linux/mod.rs#L247). I'll check, if it is really `30` for my build.

**Comment by joerg-krause** [comment]
Ok, I need some work to do. `_SC_PAGESIZE` is wrong and I've to fix my custom JSON file to build the standard library correctly for musl and ARMv5.

**Comment by joerg-krause** [comment]
I fixed my custom JSON target file for [armv5te-unkwown-linux-musl](https://github.com/joerg-krause/rust-cross-libs/blob/master/cfg/armv5te-unknown-linux-musl.json).

Now, I can cross-compile cargos `hello` for my custom target `armv5te-unkwown-linux-musl` successfully.

**Comment by alexcrichton** [comment]
Aha, I'm glad it worked out! Should we leave this open? Does a patch need to make its way upstream?

**Comment by joerg-krause** [comment]
I'll close this. I proposed a PR to libc https://github.com/rust-lang/libc/pull/214 to link with the shared library.
