### ISSUE TITLE
Search text box is invisible to use

### ISSUE THREAD

**Issue by srinivasreddy** [rust-lang/rust#32098]
i did not notice the search textbox  though i have been reading the docs for some time. 
Can we make it more noticeable?

**Comment by srinivasreddy** [comment]
![untitled](https://cloud.githubusercontent.com/assets/198396/13568808/fcc80116-e489-11e5-8180-99c35c41c7ef.png)

**Comment by srinivasreddy** [comment]
Anyone agree with me?

**Comment by srinivasreddy** [comment]
Anyone agree with me?

**Comment by srinivasreddy** [comment]
some what related https://github.com/rust-lang/rust/issues/31060

**Comment by pmarcelll** [comment]
Mine looks like this (Firefox, Arch Linux, KDE Plasma 5):

![screenshot_20160329_191352](https://cloud.githubusercontent.com/assets/1909968/14116928/86d2b48c-f5e2-11e5-8b81-8b776c4dd1de.png)

**Comment by srinivasreddy** [comment]
sorry that red color was for emphasis. Now, I realize  i did it wrong. A slight change in the UI to indicate search box is here would be great.

**Comment by pmarcelll** [comment]
I agree, it can be a bit confusing for newcomers, I guess the best option would be a magnifying glass in the search bar, like on crates.io.

**Comment by steveklabnik** [comment]
The box is much more prominent these days:

![image](https://user-images.githubusercontent.com/27786/54477239-fbd19a00-47d3-11e9-9d91-630a9228f121.png)

Additionally, with no other comments since 2016, it seems most people aren't running into this. I'm going to give it a close, thank you!
