### ISSUE TITLE
cargo command not working

### ISSUE THREAD

**Issue by flik** [rust-lang/rust#32096]
I have linux Ubuntu and Installed rust but cargo command is not working. 

What could be the issue ?
How can I verify my system is in Tier 1 or not ?

**Comment by GuillaumeGomez** [comment]
If that's a cargo issue, then reopen your issue [here](https://github.com/rust-lang/cargo). Also, what doesn't work? What's the error message if you have any? How did you install it? Don't forget to add these information if you want help.

**Comment by flik** [comment]
Actually, I installed Rust in my system according to your instructions and when I was reading from 
https://doc.rust-lang.org/book/getting-started.html
**This document was saying** : 
 

> Cargo comes installed with Rust itself, if you used the official installers. 

So I was confusing why Cargo command not working in my system.

**Comment by steveklabnik** [comment]
@flik The questions @GuillaumeGomez are asking are still relevant, though. What exactly do you mean by "not working"? Do you get an error message, and if so, what is it?

**Comment by flik** [comment]
It is fixed. now cargo is working fine. I have to install it separately.
