### ISSUE TITLE
Implement OpAssign traits with references on the right hand side

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#32094]
`AddAssign` and the others are only implemented for equal right hand side arguments. `AddAssign<u32> for u32` works well for integers, but the by reference Rhs implementation is important too, so that bigints and other non-Copy data types can have some interface in common with the primitive number types.

**Comment by nodakai** [comment]
By not providing `AddAssign<&i32>`, you can assume `where T: AddAssign<T>` applies to lightweight/primitive numbers and `where T: AddAssign<&T>` applies to bignums

**Comment by 0tt** [comment]
Creates inconsistencies between x = x / y and x /= y, requiring an unnecessary dereference for iteration: https://is.gd/DIyCYY

**Comment by bluss** [comment]
@nodakai Then generic code can only handle either of them, but not both.

**Comment by alexcrichton** [comment]
This was attempted in https://github.com/rust-lang/rust/pull/41336#issuecomment-307118210 but unfortunately it caused too much breakage, so I'm going to close.

**Comment by OnlyLys** [comment]
Heads up for future readers, this was fixed in Rust 1.22.0.
