### ISSUE TITLE
Regression in interaction between 'use' statements, crates, and 'pub use'.

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#32106]
This compiles on stable but not on nightly:

```rust
extern crate std;

pub use a::*;
pub use b::*;

pub mod a {
    use std;
}

pub mod b {
    use std;
}

fn main() { }
```

Here's the error:

```
<anon>:9:9: 9:12 error: unresolved import [E0432]
<anon>:9     use std;
                 ^~~
<anon>:9:9: 9:12 help: see the detailed explanation for E0432
<anon>:5:9: 5:12 error: unresolved import [E0432]
<anon>:5     use std;
                 ^~~
<anon>:5:9: 5:12 help: see the detailed explanation for E0432
error: aborting due to 2 previous errors
playpen: application terminated with error code 101
```

**Comment by alexcrichton** [comment]
Might be a dupe of https://github.com/rust-lang/rust/issues/32089 which is fixed in https://github.com/rust-lang/rust/pull/32097, but not sure?

cc @jseyfried

**Comment by jseyfried** [comment]
Yeah, this is a dup of #32089.

This actually doesn't compile on stable since the explicit `extern crate std;` conflicts with the implicit, injected version. It does compile on stable without the explicit `extern crate std;` or with `#![no_std]`.

**Comment by alexcrichton** [comment]
Ah ok, closing as a dupe, thanks @jseyfried!
