### ISSUE TITLE
std::os::raw::c_char is hardcoded to i8

### ISSUE THREAD

**Issue by WiSaGaN** [rust-lang/rust#32118]
In `C`, whether `char` is signed or unsigned is implementation-defined. In ARM Linux, it is defined as unsigned. This hardcoding seems to have subtle problem when porting programs.

Another inconvenience for setting `char` to `i8` is `char` array becomes `[i8;_]`, which has no easy way to cast to `[u8;_]` safely.

I don't have a good solution for this though.

**Comment by japaric** [comment]
> std::os::raw::c_char is hardcoded to i8

It's not hard coded, [it's conditionally defined](https://github.com/rust-lang/rust/blob/3af60f831f75ae2632bbfd4c1aa66049ec2d486a/src/libstd/os/raw.rs#L15-L28) to be i8/u8 based on the architecture.

**Comment by WiSaGaN** [comment]
Sorry my fault.
