### ISSUE TITLE
Tracking issue for the Peekable::is_empty function

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#32111]
This is a tracking issue for the `peekable_is_empty` feature which is the `Peekable::is_empty` function on iterators.

**Comment by oyvindln** [comment]
What is blocking this from being stabilised?

**Comment by sfackler** [comment]
Nothing in particular other than that we haven't gotten to it yet.

**Comment by alexcrichton** [comment]
🔔 This issue is now entering its cycle-long **final comment period** for deprecation 🔔

The libs team discussed this and concluded:

* The API is somewhat non-conventional by having an `is_*` query taking `&mut self` and mutate state.
* This is different from collections `is_empty` methods in the sense that the signature is different and there is no corresponding `len`
* It's the same as `.peek().is_none()` which is also very easy to call.

**Comment by alexcrichton** [comment]
The libs team discussed this at triage yesterday and the decision was to **deprecate**

**Comment by Ms2ger** [comment]
`.peek().is_none()` is a positively *horrible* way of expressing the "is empty" predicate. Can we revert this, please?
