### ISSUE TITLE
Improve name resolution failure detection

### ISSUE THREAD

**Issue by jseyfried** [rust-lang/rust#32119]
Right now, this compiles ...
```rust
pub type T = ();

mod foo {
    pub use super::T;
}

mod bar {
    pub use super::*; // ... but replacing `*` with `T` causes unresolved imports.
}

pub use foo::*;
pub use bar::*;
```

Neither case compiled before #31726, when even this would not compile:
```rust
pub type T = ();
mod foo {
    pub use super::T;
}

pub use foo::*;
```

**Comment by jseyfried** [comment]
This a violation of the first coherence condition from [this comment](https://github.com/rust-lang/rust/pull/31726#issuecomment-193625147).

**Comment by steveklabnik** [comment]
Closing as #31726 was merged.

**Comment by steveklabnik** [comment]
Closing as #31726 was merged.
