### ISSUE TITLE
Deref coercions and &-to-* coercions don't compose

### ISSUE THREAD

**Issue by lilred** [rust-lang/rust#32122]
Minimal repro:

``` rust
use std::ops::Deref;

struct A (u8);

impl Deref for A {
    type Target = u8;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

fn main() {
    let a = A(0);

    //compiles
    let b: &u8 = &a;
    let c: *const u8 = b;

    //error
    let d: *const u8 = &a;
}
```

Compile error:

``` rust
coerce.rs:15:24: 15:26 error: mismatched types:
 expected `*const u8`,
    found `&A`
(expected u8,
    found struct `A`) [E0308]
coerce.rs:15     let c: *const u8 = &a;
                                    ^~
coerce.rs:15:24: 15:26 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
```

**Comment by lilred** [comment]
@bluss thanks for walking me through this.

**Comment by bluss** [comment]
RFC 401 says that coercions are transitive, but I also realize that it does not consider deref coercions at all.

**Comment by oli-obk** [comment]
While I'm not sure if this should be fixed, we can at least fix the diagnostic to tell to user to use `&*a` instead of `&a`.

cc @rust-lang/wg-diagnostics

**Comment by estebank** [comment]
This should probably be added to https://github.com/rust-lang/rust/blob/8ad83afe5bcfa983a24b6f720c9ef389350f414b/src/librustc_typeck/check/demand.rs#L581-L587

**Comment by eddyb** [comment]
cc @nikomatsakis Should we close this issue based on only a diagnostics improvement?

**Comment by nikomatsakis** [comment]
A good question. I do sort of think that coercions "should" compose, but I also suspect there are complications, and am somewhat tempted to say it's "working well enough" and leave it closed.
