### ISSUE TITLE
Nightly breaks my build

### ISSUE THREAD

**Issue by iopq** [rust-lang/rust#32138]
https://github.com/iopq/caffe.rs compiles in 1.8.0 nightly, but not in 1.9.0 giving me an error about `use ffi;` where `ffi` is not found

**Comment by alexcrichton** [comment]
This may be a dupe of https://github.com/rust-lang/rust/issues/32089, but could you try to get a reduced example to test out?

**Comment by iopq** [comment]
Yeah, sounds like the same issue.
