### ISSUE TITLE
Segfault when returning from a specific function on Mac Osx. Gets fixed by println! or binding a string to a variable.

### ISSUE THREAD

**Issue by paezao** [rust-lang/rust#32157]
Hello,

Im getting a weird segfault on the file1.rs line:

file1.rs
`let (mut ios, err) = get_terminal_attr();`

It gets fixed if I add the following line:

file2.rs:
```
pub fn get_terminal_attr() -> (Termios, c_int) {
    let a = "a"; // ADDED LINE
    unsafe {
        let mut ios = Termios {
            c_iflag: 0,
            c_oflag: 0,
            c_cflag: 0,
            c_lflag: 0,
            c_line: 0,
            c_cc: [0; 32],
            c_ispeed: 0,
            c_ospeed: 0
        };

        let attr = tcgetattr(0, &mut ios);
        (ios, attr)
    }
}
```

It also only segfaults on debug. Works okay on release.

## Meta

Im using nightly but it also crashes on stable.

`rustc --version --verbose`:
rustc 1.9.0-nightly (388ccda45 2016-03-07)
binary: rustc
commit-hash: 388ccda455140e51456980efc07d175c19dcf005
commit-date: 2016-03-07
host: x86_64-apple-darwin
release: 1.9.0-nightly

Backtrace:
Program received signal SIGSEGV, Segmentation fault.
0x00000001000048be in rusted::raw::W.IntoRawMode::into_raw_mode (self=)
at /Users/user/.cargo/git/checkouts/libterm-cfb8814c8a0f5aca/master/src/raw.rs:67
67 let (mut ios, err) = get_terminal_attr();

**Comment by alexcrichton** [comment]
What's the definition of `Termios` look like? If that's incorrect (e.g. too small) then the syscall could corrupt the stack. For reference here's [the definition in `libc`](https://github.com/rust-lang/libc/blob/04213bbac5e66c59482cf80ed47ec886e30ed8f7/src/unix/bsd/apple/mod.rs#L236).

**Comment by paezao** [comment]
Hello @alexcrichton, thanks for replying.

```
#[derive(Clone)]
#[repr(C)]
pub struct Termios {
    c_iflag: c_uint,
    c_oflag: c_uint,
    c_cflag: c_uint,
    c_lflag: c_uint,
    c_line: c_uchar,
    c_cc: [c_uchar; 32],
    c_ispeed: c_uint,
    c_ospeed: c_uint,
}
```

**Comment by alexcrichton** [comment]
Ah ok, looks like there's a significant amount of mismatch there, so that's probably what's going on! I'd recommend using `libc` wherever possible as all the definitions are validated to be correct.
