### ISSUE TITLE
book: 'Learn Rust' link in Getting Started chapter is broken

### ISSUE THREAD

**Issue by ordian** [rust-lang/rust#32151]
> You have two options: Dive into a project with ‘Learn Rust’, or start from the bottom and work your way up with ‘Syntax and Semantics’.

Broken link: [Learn Rust](https://doc.rust-lang.org/book/learn-rust.html)

**Comment by steveklabnik** [comment]
Thanks for reporting! This has already been fixed, and will be updated in the next release: https://doc.rust-lang.org/beta/book/getting-started.html
