### ISSUE TITLE
Beta and nightly on playpen produce worse code for `clz` intrinsic compared to stable

### ISSUE THREAD

**Issue by octurion** [rust-lang/rust#32166]
Consider the following code snippet (which calculates the number of binary digits of a `u32`):

    pub fn ilog2(n: u32) -> u32 {
        // 1 + 31 ^ a = 32 - a for all values of a in [0, 32],
        // but neither LLVM nor gcc 4.8 produce optimal
        // code for the second expression.
        1 + 31 ^ n.leading_zeros()
    }

This is what the assembly output looks like with optimizations turned on (on stable):

    _ZN5ilog220h72c96f05204d06ebeaaE:
        .cfi_startproc
        bsrl	%edi, %ecx
        movl	$63, %eax
        cmovnel	%ecx, %eax
        xorl	$63, %eax
        retq

(As you can see, only conditional instructions have been emitted instead of branches)

This is how the assembly output looks like with optimizations turned on (on beta and nightly):

    _ZN5ilog220h72c96f05204d06ebeaaE:
        .cfi_startproc
        movl	$32, %eax
        testl	%edi, %edi
        je	.LBB0_2
        bsrl	%edi, %eax
        xorl	$31, %eax
    .LBB0_2:
        xorl	$32, %eax
        retq

It looks to me like beta and nightly LLVM is being way too conservative regarding the `bsr` instruction (and assume it must never be invoked with an operand of 0, which is not true according to both Intel's and AMD's programmer's manuals).

**Comment by Aatch** [comment]
Given that we just emit a call to the `ctlz` llvm intrinsic, this is almost certainly an LLVM issue.

**Comment by Aatch** [comment]
Ah, after further investigation I found this: http://reviews.llvm.org/D7554. It seems that `bsr` (and related instructions) can actually be quite slow on some CPUs and seems that LLVM will now decide whether or not to speculate accordingly.

On my machine, the default settings produce this:

```
	movl	$32, %eax
	testl	%edi, %edi
	je	.LBB0_2
	bsrl	%edi, %eax
	xorl	$31, %eax
.LBB0_2:
	xorl	$32, %eax
	retq
```

Whereas passing `-Ctarget-cpu=native` or `-Ctarget-feature=+lzcnt` produces this:

```
	lzcntl	%edi, %eax
	xorl	$32, %eax
	retq
```

It seems that `bsr` and `bsf` are actually relatively slow on CPUs that don't support `lzcnt` or `bmi`, so LLVM won't speculate their execution.

---

As a side note, conditional moves aren't always better than branches, as they extend the dependency chain, potentially causing stalls that a branch (especially a well-predicted one) wouldn't suffer from.

**Comment by Aatch** [comment]
Pinging @rust-lang/compiler to get some input, but this can probably be closed.

**Comment by bltavares** [comment]
Triage: could this be closed already?

**Comment by alexcrichton** [comment]
Yeah looks like this is just an upstream LLVM issue
