### ISSUE TITLE
BTreeMap doesn't have IndexMut trait

### ISSUE THREAD

**Issue by abbradar** [rust-lang/rust#32170]
As we already have `get()` and `Index`, and also `get_mut()` it's strange not to have `IndexMut` -- it should be pretty straightforward using `get_mut()`:

```
impl<'a, K, Q, V> IndexMut<&'a Q> for BTreeMap<K, V>
  where K: Ord + Borrow<Q>, Q: Ord + ?Sized {
    fn index_mut(&mut self, index: &Q) -> &mut Self::Output {
      self.get_mut(index).unwrap()
    }
}
```

**Comment by sfackler** [comment]
These have been intentionally left off to make sure that there won't be any breakage if/when IndexAssign traits are added.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/25034.
