### ISSUE TITLE
Zero-sized functions pointers no longer variadic-compatible

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#32201]
Seems like a crazy edge case, but this code works on stable but is currently broken on nightly.

```rust
#![crate_type = "lib"]

extern {
    fn foo(a: i32, ...);
}

extern fn bar() {}

pub fn bad() {
    unsafe {
        foo(0, bar);
    }
}
```

On stable Rust, this produces the IR:

```llvm
define void @_ZN3bad20h6e7ac30c4401351fnaaE() unnamed_addr #2 {
entry-block:
  tail call void (i32, ...) @foo(i32 3, void ()* nonnull @_ZN3bar20h7198ce9121a8c42ckaaE)
  ret void
}
```

whereas on nightly it looks like:

```llvm
define void @_ZN3bad20had7770d3eb571d55naaE() unnamed_addr #1 {
entry-block:
  tail call void (i32, ...) @foo(i32 3, {} undef)
  ret void
}
```

Which is clearly bad! I noticed there's a warning for transmuting function types to function pointers (as now it's 0-sized to pointer-sized), but perhaps the same warning could be appplied here? Or better could the coercion be automatically applied?

For reference this was discovered in [`curl-rust`](https://github.com/carllerche/curl-rust/blob/e2b447e8de307cfa993ecdbeeaa5dda1fd594964/src/ffi/easy.rs#L68) which defines [variadic functions](https://github.com/carllerche/curl-rust/blob/e2b447e8de307cfa993ecdbeeaa5dda1fd594964/curl-sys/lib.rs#L473).

cc @eddyb, @nikomatsakis

**Comment by alexcrichton** [comment]
triage: I-nominated

**Comment by eddyb** [comment]
I... can't even:
```rust
extern {
    fn printf(_: *const u8, ...);
}

pub fn main() {
    unsafe {
        printf("'%s' has length %d\0".as_ptr(), "foobar\0");
    }
}
```
```
'foobar' has length 7
```
Works on [playpen](https://play.rust-lang.org/?gist=bbb21b9eda1f60c7261b&version=stable), shows no warnings...

**Comment by nikomatsakis** [comment]
/me sighs. Hate variadics. I imagine though that we could do some sort of special case for `...` arguments.

**Comment by eddyb** [comment]
I think we should force a small set of types in `rustc_typeck::check::check_argument_types` for variadic arguments, and `TyFnDef` can be deterministically coerced to a pointer (like we do for casts).

**Comment by nikomatsakis** [comment]
triage: P-high

**Comment by ben0x539** [comment]
Shouldn't it be sufficient to restrict the arguments to variadic C functions to repr(C) things?

**Comment by eddyb** [comment]
Turns out we do have some checks related to promotions, instead of actually performing them.
There were in `check_argument_types` all along, right under my nose.
Passing `bool`, `i8`, `u8`, `i16`, `u16` or `f32` is an error, and I can just add another case for functions.

**Comment by ranma42** [comment]
@eddyb Should we also blacklist fat pointers?
