### ISSUE TITLE
Rust requires an installed C compiler for linking, but book never mentions this is necessary

### ISSUE THREAD

**Issue by niconii** [rust-lang/rust#32208]
From what I understand, Rust executes `cc` for linking programs. However, the book doesn't mention that a C compiler needs to be installed before installing Rust, resulting in a confusing error along these lines when one attempts to compile a Rust program:
```
error: could not exec the linker `cc`: No such file or directory (os error 2)
```

**Comment by retep998** [comment]
Also note this does depend on the specific target you're using. `windows-gnu` for example bundles the linker and such so it is completely standalone for pure Rust code while `windows-msvc` depends on having MSVC installed.

**Comment by dustinlapierre** [comment]
I'm a beginner looking for a good entry level issue to work on and this one caught my eye. What kind of details are needed in the documentation surrounding this issue?

**Comment by steveklabnik** [comment]
@dustinlapierre sorry for taking a while to get back to you. Basically, a note should be added in https://github.com/rust-lang/rust/blob/master/src/doc/book/getting-started.md to mention that you will need a c compiler installed. The bits @retep998 mentioned should be the only exception to that rule, as far as I know.

**Comment by steveklabnik** [comment]
I would be happy to work with anyone who wants to tackle this issue.

**Comment by wezm** [comment]
This detail is already in the the Getting Started guide: https://github.com/rust-lang/rust/commit/6c56260b302d5b21ff780fc60aede25b40e3df76 perhaps it needs to be called out more prominently under the Installing on Linux or Mac and Installing on Windows sections? If so I'm happy to have a go.

**Comment by retep998** [comment]
For what it's worth, on `windows-msvc` rustc at least prints out a nicer message telling you that you need to get MSVC. https://github.com/rust-lang/rust/blob/master/src/librustc_trans/back/link.rs#L690-L695

**Comment by steveklabnik** [comment]
@wezm yes, I think that'd be good. Thanks!

**Comment by pmatos** [comment]
I just noticed, I did not reference the Mac on my pull request. Does anyone know what the situation is on the Mac regarding Linker requirements?
