### ISSUE TITLE
Consider running function passes just after each function is translated.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#32215]
Optimizations within a function should be able to remove some ugliness in the IR and keep the memory usage bounded (and maybe get speedier allocations).
However, I'm not sure if there are any potential losses from doing it early.

**Comment by arielb1** [comment]
What are the compile times on MIR-trans vs. old trans?

**Comment by eddyb** [comment]
@arielb1 I didn't get to check because it was all `-j36` parallel output spew but I could try a few builds just for the purposes of that.

**Comment by eddyb** [comment]
@arielb1 See [this comment on PR #32080](https://github.com/rust-lang/rust/pull/32080#issuecomment-196019692) - it appears that function passes alone free half of the memory we allocate during `trans`, which seems like a lot to me - although, some of that could be the contexts getting dropped after the "time: 14.097; rss: 1152MB       translation" line is printed.

**Comment by arielb1** [comment]
This does look like the memory consumed by the contexts - note that there are about 250MB between the start of the inference passes and the start of type-checking.

**Comment by alexcrichton** [comment]
I think this is effectively done today with the recent work to spawn off codegen workers as soon as a codegen unit is finished, so closing.

**Comment by eddyb** [comment]
We're much better, yes, but what I had in mind was far more aggressive.
I'm find with keeping this closed and focus on some hybrid system on top of LLVM for cutting down of IR instead of LLVM's own optimization passes.
