### ISSUE TITLE
' \" ' works in char literals

### ISSUE THREAD

**Issue by Robbepop** [rust-lang/rust#32249]
To write a double-quote (") in a string literal, once needs to escape with with a backslash like so:
```rust
let s = "double-quote: \"";
```
This is because it is also the delimiter of a string.
However, in character literals a single-quote (') is the delimiter and still, '\"' works without warnings:
```rust
assert_eq!('\"', '"'); // always true
```
I think this might be a bug since it is not really needed to have an escaped double-quote in character literals or was it implemented as a helpful routine?

The same is true for strings and a single-quote!
```rust
assert_eq!("\'", "'"); // always true
```
I am very sorry if this was explicitly wanted behaviour!

**Comment by petrochenkov** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/29470

**Comment by brson** [comment]
Working as intended per #29470. Thanks for the report.
