### ISSUE TITLE
formalize FromStr syntax

### ISSUE THREAD

**Issue by flying-sheep** [rust-lang/rust#32243]
AFAIK there’s no grammar specified anywhere that describes how `FromStr`/`parse` works.

E.g. some didn’t want `f64::from_str(".")` to work (#30344) and I wonder why `i32::from_str("1_000")` does _not_ work.

**Comment by rkruppe** [comment]
At least for float parsing there are comments on the `impl FromStr` but they are incomplete and probably not rendered by rustdoc.

**Comment by frewsxcv** [comment]
> probably not rendered by rustdoc.

The comments are now rendered by rustdoc: https://doc.rust-lang.org/std/primitive.f32.html (scroll down to `FromStr`). Anyone have suggestions for what to add to those docs? Do we even have a grammar for parsing floats?

**Comment by leoschwarz** [comment]
I didn't find a grammar for FromStr for floats however as most likely it would be a bad idea to change the parsing now, it could just be derived from the code and officially documented so users don't have to figure these things out themselves.

Maybe as grammar language [what was used for the Rust grammar specification](https://doc.rust-lang.org/grammar.html#notation) could be used, i.e. maybe link that and provide an expression for the valid numbers?

**Comment by flying-sheep** [comment]
> it would be a bad idea to change the parsing now

i’d like parsing to be more lenient and accept underscores, i guess you only meant parsing shouldn’t get stricter?

**Comment by steveklabnik** [comment]
This is a special case of https://github.com/rust-lang/rust/issues/31821, so closing as part of that.
