### ISSUE TITLE
Borrow checker incorrectly determines trait lifetime to be 'static

### ISSUE THREAD

**Issue by cmbrandenburg** [rust-lang/rust#32279]
I'm not sure if this is an error, but it _feels_ wrong to me. It's maybe related to #15144. Here's the code:

```rust
trait Bar<'a> {
    fn bar(self) -> &'a str;
}

impl Bar<'static> for &'static str {
    fn bar(self) -> &'static str {
        self
    }
}

impl<'a> Bar<'a> for &'a String {
    fn bar(self) -> &'a str {
        self.as_str()
    }
}

fn foo<'a, T, U>(x: T, y: U) -> &'a str
    where T: Bar<'a>,
          U: Bar<'a>
{
    let x = x.bar();
    let y = y.bar();
    if x < y {
        x
    } else {
        y
    }
}

fn main() {
    let s = String::from("Goodbye");
    let x = foo("Hello", &s);
    println!("{}", x);
}
```

Here's the compile-time error:

```
src/main.rs:32:27: 32:28 error: `s` does not live long enough
src/main.rs:32     let x = foo("Hello", &s);
                                         ^
note: reference must be valid for the static lifetime...
src/main.rs:31:37: 34:2 note: ...but borrowed value is only valid for the block suffix following statement 0 at 31:36
src/main.rs:31     let s = String::from("Goodbye");
src/main.rs:32     let x = foo("Hello", &s);
src/main.rs:33     println!("{}", x);
src/main.rs:34 }
```

It seems to me that, because the `T` type parameter to `foo` evaluates to `Bar<'static>` and `U` evaluates to `Bar<'lifetime_of_s_in_main>`, `foo` should evaluate its `'a` lifetime to be `'lifetime_of_s_in_main`, not `'static`.

**Comment by durka** [comment]
The problem is `&'static str` (the type of `"Hello"`) only implements `Bar<'static>`. It doesn't implement `Bar<'a>` for any other `'a`, so `foo`'s `'a` _must_ be `'static`. You can fix it by changing the trait implementation to this:

```rust
impl<'a> Bar<'a> for &'static str {
    fn bar(self) -> &'a str {
        self
    }
}
```

Because `&'static T` is convertible to `&'a T` for any other `'a`, but not so for `Bar<'static>`. At least that's my analysis.

**Comment by cmbrandenburg** [comment]
That fixes my problem, thanks so much!

As for whether this is a Rust issue, I still _feel_ like the borrow checker should see the `Bar<'static>` and allow that to be `Bar<'a>`. As I understand it, the `'a` means something akin to <q>the lifetime of at least the minimum `'a`</q>. A `'static` lifetime certainly qualifies. But I'm no expert.

**Comment by arielb1** [comment]
That would basically be variance on traits, which we decided against.
