### ISSUE TITLE
Add methods exposing keys of BTreeMap and HashMap entries

### ISSUE THREAD

**Issue by dstu** [rust-lang/rust#32281]
As discussed in [rfcs](https://github.com/rust-lang/rfcs/issues/1541), it would make sense to add a `keys()` method to the `Entry` variants for both map types.

[PR 32248](https://github.com/rust-lang/rust/pull/32248) has code and tests.

**Comment by frewsxcv** [comment]
Was this completed in #32248?

**Comment by apasel422** [comment]
@frewsxcv Yes. We'll keep it open as the tracking issue.

**Comment by sgrif** [comment]
Had a use case for this in Diesel this morning. (Code comparison: https://gist.github.com/sgrif/68cbba9a87084da3a2e8c42a12e7d6cf). Worked great, and was exactly the missing piece. Looking forward to seeing this stabilized.

**Comment by sfackler** [comment]
I just noticed that while this is on both `OccupiedEntry` and `VacantEntry`, the convenience impl on `Entry` is missing.

**Comment by seanmonstar** [comment]
If I wanted to propose a `fn take(self) -> (K, V)`, would it be fine to tag along with this issue, or should that require its own RFC?

**Comment by sfackler** [comment]
I think it'd be more associated with the key recovery tracking issue, but that's already landed. In any case, I don't think an RFC would be required - it can piggy back off of the existing key recovery one.

**Comment by sfackler** [comment]
cc @aturon

**Comment by alexcrichton** [comment]
🔔 This issue is now entering its cycle-long **final comment period** for stabilization 🔔

(including https://github.com/rust-lang/rust/pull/33148)

**Comment by aidanhs** [comment]
I have effectively the same use-case as @sgrif, +1 from me.

**Comment by alexcrichton** [comment]
The libs team discussed this during triage yesterday and the decision was to **stabilize**
