### ISSUE TITLE
windows 10 rustc main.rs

### ISSUE THREAD

**Issue by zanjs** [rust-lang/rust#32283]
### main.rs

`
fn main() {
    println!("Hello, world!");
}
`
### run
`
F:\coding\rust-lang\test\hello_world>rustc main.rs

error: could not exec the linker `link.exe`: 系统找不到指定的文件。
`

**Comment by Stebalien** [comment]
Assuming you're using the MSVC version of rust, you need to install Visual Studio 2013 or later. https://www.rust-lang.org/downloads.html#win-foot

**Comment by bombless** [comment]
@zanjs 你能说说你的安装包是从哪个地址下载的吗？
我的建议是你装这个版本：
<https://static.rust-lang.org/dist/rust-1.7.0-x86_64-pc-windows-gnu.msi> (64位操作系统）
<https://static.rust-lang.org/dist/rust-1.7.0-i686-pc-windows-gnu.msi> （32位操作系统）
如果你需要nightly-build，可以安装
<https://static.rust-lang.org/dist/rust-nightly-x86_64-pc-windows-gnu.msi> （64位操作系统）
<https://static.rust-lang.org/dist/rust-nightly-i686-pc-windows-gnu.msi> （32位操作系统）

记得安装时不要去掉安装链接器的勾

你现在用的这个是MSVC版本的，那个链接器是没有随安装包一起分发的，因此就像Stebalien说的，你需要先安装过MSVC。

**Comment by zanjs** [comment]
@bombless 
安装的 这个 https://static.rust-lang.org/dist/rust-1.7.0-x86_64-pc-windows-msvc.msi
谢谢你

@Stebalien Thanks!

**Comment by bombless** [comment]
I feel that we should modify the installer to make it more clear to the user that they need MSVC to make MSVC version actually work. Thoughts?

**Comment by zanjs** [comment]
@bombless 我电脑安装了 vs 2015 的 ，还需要装什么，貌似 MSVC的配置环境还不简单呀，果断使用

**Comment by bombless** [comment]
@zanjs 是啊，所以那个下载页有说

```text
Rust's support for the GNU ABI is more mature, and is recommended for typical uses.
```
更推荐GNU ABI而不是MSVC ABI。

我们可爱的WindowsBunny正试图改变这一状况 https://github.com/rust-lang/rust/pull/31158

我还在看怎么搞比较好，最偷懒的方式是安装包顺便给自己装一个MSVC哈哈哈。

至于要用MSVC版rustc的话，先要把MSVC里的link.exe所在的目录加到系统的PATH环境变量里吧。
