### ISSUE TITLE
Unaligned load/store regression - ARMv5 incorrect codegen

### ISSUE THREAD

**Issue by arcnmx** [rust-lang/rust#32289]
#23431 is back, the test case from that issue now miscompiles on ARMv5 again. This broke somewhere between the Jan 3rd and March 9th nightlies.

[main.rs and main.ll](http://pastie.org/private/300674wiucmvdy34h2m4ka)

**Comment by arcnmx** [comment]
CC @dotdash - you identified and fixed this issue the last time it came up, any ideas about what changed recently that brought it back?

**Comment by dotdash** [comment]
No idea. A cursory glance at the IR doesn't show up any missing alignment specifiers either.

**Comment by arcnmx** [comment]
[main.ll from old nightly + diff](http://pastie.org/private/k6qresvspdxjesfoiaxpwa)

The bizarre thing is that I don't see any real differences besides the identifier hashes in that diff...

**Comment by arcnmx** [comment]
Generated asm from both + diff: http://pastie.org/private/j5onpivq1disqrrnwy9pq

**Comment by arcnmx** [comment]
Okay, I've bisected across rustc versions...

Nightly `2016-01-30 303892ee1` works, `2016-01-31 9a07087bc` is broken.

https://github.com/rust-lang/rust/compare/303892ee1...9a07087bc ... and I see no changes to trans at all there ;_;

**Comment by joerg-krause** [comment]
@arcnmx Are you using a custom JSON target file for ARMv5?

**Comment by arcnmx** [comment]
@joerg-krause yeah, there's no built-in target for it in rustc. It's just:

```json
{
        "llvm-target": "armv5te-oe-linux-gnueabi",
        "target-endian": "little",
        "target-pointer-width": "32",
        "os": "linux",
        "arch": "arm",
        "linker": "arm-oe-linux-gnueabi-gcc",
        "ar": "arm-oe-linux-gnueabi-ar",
        "cpu": "arm926ej-s",
        "dynamic-linking": true,
        "executables": true,
        "linker-is-gnu": true,
        "position-independent-executables": true,
        "lib-allocation-crate": "alloc_system",
        "exe-allocation-crate": "alloc_system"
}
```

**Comment by arcnmx** [comment]
Okay I appear to have messed up... It's actually jan 28 vs 30 (there is no 29 nightly): https://github.com/rust-lang/rust/compare/38e23e8f7...303892ee1

**Comment by joerg-krause** [comment]
The issue you describe is about faulty data alignment. You have to tell LLVM to compile with `strict-align` option:

```
"features": "+v5te,+dsp,+soft-float,+strict-align,-crypto,-neon"
```

Have a look at my [armv5te-unknown-linux-gnueabi](https://github.com/joerg-krause/rust-cross-libs/blob/master/cfg/armv5te-unknown-linux-gnueabi.json) for comparison.

**Comment by joerg-krause** [comment]
Note, you'll have to recompile the rust libs after changing the target configuration.

**Comment by arcnmx** [comment]
@joerg-krause makes sense, thanks! Especially alongside the LLVM version update in the commit range I linked. Will try and report back.

**Comment by joerg-krause** [comment]
For the record, this issue https://github.com/rust-lang/rust/issues/31796 was related to faulty data alignment, too.

**Comment by arcnmx** [comment]
Yup, that seems to help, thanks! `strict-align` seems to be a new target feature in the updated LLVM... and of course they helpfully removed the logic that used to infer it from the CPU architecture...
