### ISSUE TITLE
Bit shift operator type mismatch under nightly

### ISSUE THREAD

**Issue by Johnson-A** [rust-lang/rust#32297]
With the newest nightly rustc 1.9.0-nightly (c66d2380a 2016-03-15), when compiling [jpeg_decoder](https://github.com/kaksmet/jpeg-decoder/blob/master/src/huffman.rs)

```
182:34 error: array length constant evaluation error: mismatched types:
 expected usize,
    found u8 [E0250]
/jpeg-decoder-0.1.2/src/huffman.rs:182     lut: [(u8, u8); 1 << LUT_BITS],
```

LUT_BITS is `u8` and `1 << LUT_BITS` needs to be `usize` but the shift can't find the right specialization of the bit shift to produce `usize`.

**Comment by jonas-schievink** [comment]
#32285 fixes this

**Comment by Johnson-A** [comment]
Great, sorry, I couldn't find a that issue before posting
