### ISSUE TITLE
Any::is missing in docs

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang/rust#32299]
Just noticed that if you search for "is" in the docs and click on the first (and second) link, you get a page not found.

https://doc.rust-lang.org/std/trait.Any.html#method.is

Not Found

Looks like you've taken a wrong turn.

Some things that might be helpful to you though:

Search

trait Any is site:doc.rust-lang.org
Rust doc search: is

**Comment by bluss** [comment]
Thanks! This bug is already reported, it is issue  #24137.
