### ISSUE TITLE
Fix src/test/run-pass/variadic-ffi.rs test

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#32305]
This test is ignored on MSVC because MSVC does not have a sprintf function. 

We have a variadic function defined in test helpers, which should be used in this test as well. See [mir_trans_calls_variadic](https://github.com/rust-lang/rust/blob/master/src/test/run-pass/mir_trans_calls_variadic.rs) for an example.

**Comment by rilut** [comment]
The `#[link(name = "rust_test_helpers")]`? What to do with it?

**Comment by nagisa** [comment]
@rilut It should be copied over along with the `extern { fn rust_interesting_average… }` block.
