### ISSUE TITLE
The folder path 'My Documents' contains an invalid character.

### ISSUE THREAD

**Issue by fivejjs** [rust-lang/rust#32300]
I try to install rust 1.7 on windows 7 pro.

Failed with error like this:

```
The folder path 'My Documents' contains an invalid character.
```

**Comment by retep998** [comment]
Why are you trying to install Rust to "My Documents"?

**Comment by nodakai** [comment]
"My Document" might be a red herring

- https://support.microsoft.com/en-us/kb/894510

**Comment by fivejjs** [comment]
I am not installing rust to "My Documents" folder. I just double click on the msi file. It runs smooth under my linux box. I guess it was my company's profile leads to the problem.

**Comment by Mark-Simulacrum** [comment]
@fivejjs Could you check if this happens today?

**Comment by Mark-Simulacrum** [comment]
I'm going to close since we've changed quite a bit about installation since then, I believe, and I don't believe I've seen other issues like this one recently. Let us know if this is still a problem.
