### ISSUE TITLE
Conflicting impl of Borrow with templated trait type

### ISSUE THREAD

**Issue by dhardy** [rust-lang/rust#32315]
Error:

```
<anon>:14:1: 18:2 error: conflicting implementations of trait `core::borrow::Borrow<IndexableValue<_, _>>` for type `IndexableValue<_, _>`: [E0119]
<anon>:14 impl<T, E> Borrow<E::K> for IndexableValue<T, E> where E: KeyComparator<T> {
<anon>:15     fn borrow(&self) -> &E::K {
<anon>:16         panic!("no impl")
<anon>:17     }
<anon>:18 }
<anon>:14:1: 18:2 help: see the detailed explanation for E0119
note: conflicting implementation in crate `core`
error: aborting due to previous error
playpen: application terminated with error code 101
```

Full example: [hashindexed / internal-key](https://github.com/dhardy/hashindexed/blob/adc220f38c9458fd18f7180fa1321db07a98976b/src/lib.rs).
Cut-down example: http://is.gd/sp3EA6

**Comment by Stebalien** [comment]
I believe the problem is that `E::K` could be an `IndexableValue<T, E>` but this error message isn't very enlightening.

```rust
struct Test;

impl KeyComparator<()> for Test {
    type K = IndexableValue<(), Test>;
}
```

This would conflict with `impl<T> Borrow<T> for T where T: ?Sized`.

**Comment by dhardy** [comment]
Good point @Stebalien. In theory `K` is the type of a field within type `T`, but this does not need to be the case. Restricting `K` never to be an `IndexableValue<_, _>` would be fine, but I don't think "is not a" is a valid type restriction?

**Comment by Stebalien** [comment]
No, negative constraints aren't allowed.

**Comment by dhardy** [comment]
Well, that's a bummer then. I could always stop playing template-kung-foo and duplicate all of the HashMap code, but that seems a silly.

Negative type constraints would be the simplest solution to my problem (see below), but "impl specialization" is already under development which should prove sufficient.

For my use-case, no type implementing `KeyComparator` can use type `IndexableValue`, since impls of the former are done outside the library and the latter is for internal usage only. The compiler doesn't know this and probably can't easily reason along these lines, yet it wants to prove its impls don't overlap for any possible templated types, not just those used (which makes a *lot* of sense to anyone who's tried to debug complex template logic in C++). Negative type constraints seem by far the easiest constraint (though it might be possible to botch something by comparing type sizes, if that's possible).

    type K: !IndexableValue<T, Self>;    // or <_, _>

**Comment by Mark-Simulacrum** [comment]
I think this is something that isn't really resolvable without specialization and we don't need to track this specifically, so I'm going to close. Please file another issue if you try to implement this with specialization and encounter an error (e.g., ICE or similar), and also take a look at the tracking issue: https://github.com/rust-lang/rust/issues/31844.
