### ISSUE TITLE
Should be possible to use the select!() macro within deny(unsafe_code)

### ISSUE THREAD

**Issue by Ms2ger** [rust-lang/rust#32331]

**Comment by steveklabnik** [comment]
I believe that this is a duplicate, but I can't remember enough about the other bug :(

**Comment by mitaa** [comment]
Did you perhaps think of #8472?

The unsafe block in `select!` could be annotated `allow(unsafe_code)`, but that would require all crates the macro *is used in* to have `feature(stmt_expr_attrs)`.

Another solution would be to move the unsafe block into a safe helper function...

**Comment by Ms2ger** [comment]
Also, while `deny(unsafe_code)` is my primary concern, something that works with `forbid` too would be even better.

**Comment by Mark-Simulacrum** [comment]
`select!` macro is gone today and we have a way of doing this I believe (rustc_internal_unsafe or some similar attribute on macros)
