### ISSUE TITLE
Prelude item shows up in two locations in docs

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#32343]
The items inside `std::os::unix::prelude` all get their own doc page under that namespace, which duplicates their more canonical location.

Compare:

- [std::os::unix::process::CommandExt](http://doc.rust-lang.org/nightly/std/os/unix/process/trait.CommandExt.html)
- [std::os::unix::prelude::CommandExt](http://doc.rust-lang.org/nightly/std/os/unix/prelude/trait.CommandExt.html)

This does not apply to `std::io::prelude`, I believe the difference is that the io prelude reexports items that are directly visible in their declared location.

Solving this (so that the prelude-ish module does not duplicate docs) would help me in third party library development as well.

**Comment by mitaa** [comment]
> This does not apply to std::io::prelude, I believe the difference is that the io prelude reexports items that are directly visible in their declared location.

Yes, crate-local inlining inlines items that would be stripped at their original location and does not track whether, how often, or where an item has been inlined.

It'd be easy enough to apply `doc(no_inline)` (already attached to `prelude::CommandExt`) to crate-local inlining, which is currently only considered in cross-crate inlining.

The only issue is that rustdoc doesn't know about "canonical locations", so it's not quite clear what should be done about the (probably broken) link of the `prelude::CommandExt` import.

**Comment by bluss** [comment]
So `doc(no_inline)` on those currently has no effect. Is the path that it uses to import the item not available?

**Comment by mitaa** [comment]
These links are generated using the fully resolved `DefId`, in this case pointing to `std::sys::unix::ext::process::CommandExt`, but apparently there is some [redirect magic for public types in private modules][0] (still broken for `doc(hidden)` though).

The used import-path is available as string-segments, but I'm a bit wary of using them to create links. (e.g. #29814)

[0]: https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/render.rs#L1313-L1322

**Comment by bluss** [comment]
Wow, you're so good at fixing rustdoc issues :heart:
