### ISSUE TITLE
Suggest renaming a trait import if the names clash

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#32354]
You can bring in multiple traits of the same name if you rename them.

[Example use case (playground code)](https://play.rust-lang.org/?gist=91d337ed5f7816d4330c&version=stable)

``` rust
use extension1::ConstructorExtension;
use extension2::ConstructorExtension;
```

current error:

```
<anon>:49:5: 49:37 error: a trait named `ConstructorExtension` has already been imported in this module [E0252]
<anon>:49 use extension2::ConstructorExtension;
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<anon>:49:5: 49:37 help: see the detailed explanation for E0252
<anon>:48:5: 48:37 note: previous import of `ConstructorExtension` here
<anon>:48 use extension1::ConstructorExtension;
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Suggested note: "You can rename an imported name with `as`".

**Comment by GuillaumeGomez** [comment]
Seems like a nice idea. I'm taking this issue.

**Comment by petrochenkov** [comment]
Two thoughts: 1) This is not specific to traits, any import (or non-import) can be renamed in case of conflict 2) resolve already has too many overly specific errors and messages, which seemed like a nice idea and easy PR material, with no evidence of their actual helpfulness.

**Comment by Mark-Simulacrum** [comment]
@GuillaumeGomez Checking in; I think no progress has been made. Do you think you'll have a chance to work on this soon?

**Comment by GuillaumeGomez** [comment]
No I won't. Feel free to take it.

**Comment by estebank** [comment]
### Mentoring instructions:

The [duplicated import struct is created in `src/librustc_resolve/lib.rs`](https://github.com/rust-lang/rust/blob/master/src/librustc_resolve/lib.rs#L3652). A new check should be added for _at least_ one of the bindings being an import. If only one of them is an import, do the following on the binding that is an import, if both are, choose one (I'd say `new_binding`):

    let cm = self.session.codemap();
    if let Ok(snippet) = cm.span_to_snippet(import_binding.span) {
        err.span_suggestion(import_binding.span,
                            "You can use `as` to change the binding name of the import",
                            format!("use {} as Other{}", snippet, name));
    } else {
        err.span_label(import_binding.span,
                       "You can use `as` to change the binding name of the import");
    }

**Comment by colinmarsh19** [comment]
I might take a look at this issue and see what I can do. Let me know if there are any conflicts --Colin

**Comment by estebank** [comment]
@colinmarsh19 go ahead! Feel free to reach out for help here, gitter, or IRC.
