### ISSUE TITLE
impl on type aliases

### ISSUE THREAD

**Issue by calebmer** [rust-lang/rust#32357]
To provide a nice interface to users I would like to be able to add some `impl` functions to a `type` alias. For example, I have the following code:

```rust
type Schema = Box<SchemaTrait + 'static>;

trait SchemaTrait {…}

struct SchemaNumber {…}
impl SchemaTrait for SchemaNumber {…}
```

I would like to add the following:

```rust
impl Schema {
  fn new_number() -> Schema {
    Box::new(SchemaNumber::new())
  }
}
```

So the following would work:

```rust
Schema::new_number()
```

But this would not:

```rust
Box::new_number() // Fails, method is only for the type alias.
```

Another use case is I have a map representing a JSON object (`BTreeMap<Key, Value>`) that I would like to add custom methods to without having to write a struct that redefines all of the `BTreeMap` methods. This currently [cannot be done](https://play.rust-lang.org/?gist=aeaf3eb75ead8b019d08&version=stable).

As a side note, this feels a little like classical inheritance…

**Comment by jonas-schievink** [comment]
A type alias is just that: An alias, not a different type. If you want to create a different type, use the newtype pattern for that.

**Comment by calebmer** [comment]
@jonas-schievink but the `newtype` pattern doesn't inherit all of the aliased types methods. Is there a reason that `type` couldn't create a new type?

**Comment by KalitaAlexey** [comment]
@calebmer Yes, it is. Because everyone using `type` as `alias`.

**Comment by nrc** [comment]
This would require an RFC and would be better served as an issue on that repo rather than here. Having said that, I don't believe this is desirable. The preferred approach is to use newtypes (as @jonas-schievink mentions). A possible solution is 'newtype deriving' where a newtype inherits impls. That has been discussed a fair amount before, not sure if there is an issue open for it.

**Comment by calebmer** [comment]
I would like to see an issue on newtype deriving if it exists.

**Comment by nikomatsakis** [comment]
Indeed, as @nrc noted, this would most definitely require an RFC, but I think more importantly it's not really something we would want. Type aliases, indeed, are just aliases. Some kind of lighter-weight deriving for struct wrappers (newtypes) would be nice though and would... probably... fill the use-case here. Therefore, I'm going to close this issue in favor of https://github.com/rust-lang/rfcs/issues/479.
