### ISSUE TITLE
rustc should accept rustc -O -C opt-level=x

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#32352]
`rustc -O -O` is ok just like `rustc -C opt-level=1 -C opt-level=2`. `-O` is documented to be the same as `-C opt-level=2`, so there should be no conflict, just have the last argument take precedent.

`-g` vs `-C debuginfo=2` behave the same way.

```
$ rustc -O -C opt-level=2
error: -O and -C opt-level both provided

$ rustc -C opt-level=1 -C opt-level=2 -g -g foo.rs
# ok.
```

**Comment by steveklabnik** [comment]
Triage: no change
