### ISSUE TITLE
Show unstable status for deprecated items

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#32374]
A deprecated item should still show its unstable status in the docs, otherwise both stable + deprecated and unstable + deprecated items are presented the same way (only the source code tells you the difference).

This is a problem because without the unstable label, doc items will be assumed to be stable by users.

Issue #24617 seems to be similar, but not exactly the same.

**Comment by euclio** [comment]
I'd like to work on this. Is there some documentation somewhere on how to build/hack on `rustdoc`?

**Comment by mitaa** [comment]
I don't think so..

```
// build just the rustdoc binary, useful for local experiments
make x86_64-unknown-linux-gnu/stage1/bin/rustdoc
// run the src/test/rustdoc tests
make check-stage1-rustdocck
```

For writing rustdoc tests you need to look at [`src/etc/htmldocck.py`][0], which is run on the generated documentation, and [compiletest][1]  and its [flags][2] in general.
(using existing tests as guidance is always useful - i.e. rustdoc tests with auxiliary crates need to be marked `// ignore-cross-compile`)

[0]: https://github.com/rust-lang/rust/blob/cf81e1aba86bebb4830f91d4097492dd21d8ebf6/src/etc/htmldocck.py#L11-L105
[1]: https://github.com/rust-lang/rust/blob/master/COMPILER_TESTS.md
[2]: https://github.com/rust-lang/rust/blob/master/src/compiletest/header.rs#L21-L58
