### ISSUE TITLE
Update documentation for tuple structs

### ISSUE THREAD

**Issue by amitsaha** [rust-lang/rust#32372]
I had to ask on #rust IRC channel to be able to understand tuple structs. Thanks to the nice people, I understand them now and wrote up a basic example to help my understanding:

```
// Demo of "tuple struct" - a structure with no field names, but
// just types
// https://doc.rust-lang.org/book/structs.html


pub struct Struct1 {
    x: i32,
}

pub struct Struct2 {
    x: i32,
}
    
// Declare a tuple struct
pub struct Struct(Struct1, Struct2);


fn main() {
        
    let s: Struct = Struct(Struct1 {x:2} , Struct2 {x:3});
    
    // Use indexes to access the inner data
    println!("{}", s.0.x);
    println!("{}", s.1.x);
    
    // Use destructuring to access the inner data
    let Struct(item1, item2) = s;
    println!("{} {}", item1.x, item2.x);
}
```

Wondering if I should consider adding this example and accompanying test to the docs here at  https://doc.rust-lang.org/book/structs.html and send a PR?

**Comment by steveklabnik** [comment]
Sure, I would take one. Thanks!

**Comment by srinivasreddy** [comment]
@steveklabnik  What is the depth of embedding here? Any idea?

**Comment by steveklabnik** [comment]
Just that it would need to make sense, the literal text here wouldn't quite work.

**Comment by steveklabnik** [comment]
I would be happy to work with anyone who wants to work on this issue.

**Comment by terrynsun** [comment]
I can take a stab at this!

**Comment by terrynsun** [comment]
Oh, it looks like someone already added a clarification of using dot notation with tuple structs. Do you think that resolves this issue?

**Comment by steveklabnik** [comment]
@terrynsun I think so yes! Thank you for investigating. :smile:
