### ISSUE TITLE
OsString could implement the Default trait

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang/rust#32385]
[`std::ffi::OsString`](http://doc.rust-lang.org/1.7.0/std/ffi/struct.OsString.html) has an associated function `new() -> OsString`, but no Default impl. Probably just an oversight, and so not RFC-worthy IMHO.

**Comment by tomjakubowski** [comment]
Test case: https://play.rust-lang.org/?gist=a0163d89a5fca1bd30d4&version=nightly

**Comment by frewsxcv** [comment]
Someone mark this as "good first bug"?

**Comment by alexcrichton** [comment]
Indeed!

**Comment by bluss** [comment]
The same applies to `&OsStr` (just do it the same way &str does).

**Comment by WiSaGaN** [comment]
I'll take it if no one hasn't already.

**Comment by frewsxcv** [comment]
> I'll take it if no one hasn't already.

Go for it!
