### ISSUE TITLE
rustdoc displays "pub" to struct-like enum variants and their fields

### ISSUE THREAD

**Issue by nodakai** [rust-lang/rust#32395]
- https://doc.rust-lang.org/nightly/std/ops/enum.RangeInclusive.html

```rust
pub enum RangeInclusive<Idx> {
    pub Empty {
        pub at: Idx,
    },
    pub NonEmpty {
        pub start: Idx,
        pub end: Idx,
    },
}
```

This is no longer valid Rust: https://doc.rust-lang.org/error-index.html#E0449

Incidentally, tuple-like enum variants seems to be free from this issue:

- https://doc.rust-lang.org/nightly/std/path/enum.Component.html

```
pub enum Component<'a> {
    Prefix(PrefixComponent<'a>),
    RootDir,
    CurDir,
    ParentDir,
    Normal(&'a OsStr),
}
```

**Comment by sfackler** [comment]
It looks like this only happens for enums reexported across crates. The libcore version of `RangeInclusive` is rendered correctly: https://doc.rust-lang.org/nightly/core/ops/enum.RangeInclusive.html
