### ISSUE TITLE
Missing checksum file for installs

### ISSUE THREAD

**Issue by octoquad** [rust-lang/rust#32398]
Following the Rust getting started [guide](https://doc.rust-lang.org/book/getting-started.html#installing-on-linux-or-mac) for installing on Linux or Mac, after running the curl command to download and install Rust, I noticed that the checksum file is missing. 

> $curl -sSf https://static.rust-lang.org/rustup.sh | sh
> rustup: gpg available. signatures will be verified
> rustup: downloading manifest for 'stable'
> **rustup: command failed: curl -s -f -O https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256**
> **rustup: couldn't download checksum file 'https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256'**
> rustup: downloading manifest for 'stable'
> rustup: downloading toolchain for 'stable'
> ######################################################################## 100.0%
> gpg: assuming signed data in '/home/user/.rustup/dl/f7d07fcd74b48b99db46/rust-1.7.0-x86_64-unknown-linux-gnu.tar.gz'
> gpg: Signature made Wed 02 Mar 2016 04:14:02 SAST using RSA key ID 7B3B09DC
> gpg: Good signature from "Rust Language (Tag and Release Signing Key) <rust-key@rust-lang.org>" [unknown]
> gpg: WARNING: This key is not certified with a trusted signature!
> gpg:          There is no indication that the signature belongs to the owner.
> Primary key fingerprint: 108F 6620 5EAE B0AA A8DD  5E1C 85AB 96E6 FA1B E5FE
>      Subkey fingerprint: C134 66B7 E169 A085 1886  3216 5CB4 A934 7B3B 09DC
> rustup: installing toolchain for 'stable'
> rustup: extracting installer
> [sudo] password for user: 
> install: creating uninstall script at /usr/local/lib/rustlib/uninstall.sh
> install: installing component 'rustc'
> install: installing component 'rust-std-x86_64-unknown-linux-gnu'
> install: installing component 'rust-docs'
> install: installing component 'cargo'
> 
>     Rust is ready to roll.
> 
> $ rustc --version
> rustc 1.7.0 (a5d1e7a59 2016-02-29)

This seems minor and does not affect the install, but should be fixed. Thanks

**Comment by bluss** [comment]
cc @brson

**Comment by woodsjay** [comment]
As a brand new user, this is very unsettling. I then got into the sudo problem which kept timing out as I turned my attention to other problems.

**Comment by nodakai** [comment]
Perhaps the [test scripts](https://github.com/rust-lang/rustup/blob/master/test-v2.sh) should run `rustup.sh` with `sh -x`

**Comment by brson** [comment]
Fixed.

**Comment by toomanycats** [comment]
Running Ubuntu I received the same failure:

`./rustup.sh
rustup: gpg available. signatures will be verified
rustup: downloading manifest for 'stable'
rustup: command failed: curl -s -f -O https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256
rustup: couldn't download checksum file 'https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256'
rustup: downloading manifest for 'stable'
rustup: command failed: curl -s -f -O https://static.rust-lang.org/dist/channel-rust-stable.sha256
rustup: couldn't download checksum file 'https://static.rust-lang.org/dist/channel-rust-stable.sha256'
`
