### ISSUE TITLE
is it a bug?

### ISSUE THREAD

**Issue by eruca** [rust-lang/rust#32391]
```rust
println!("{} is {0:.*}",   2.02, 5); // print 2.02 is 2.02000
```
follow the document  http://doc.rust-lang.org/std/fmt/   it should not be compiled,but it pass.I'm newer, asked someone else,he said it's maybe a bug, so ...

**Comment by shahn** [comment]
No, this is not a bug, just surprising. I'll write a doc fix to point out that case.

**Comment by nodakai** [comment]
I do think this is a bug, or we need to fix the formatting rule.  It isn't just about _clarification_.

- http://doc.rust-lang.org/std/fmt/#precision

> 3: An asterisk `.*`:
>
> `.*` means that this `{...}` is associated with two format inputs rather than one: the first input holds the `usize` precision, and the second holds the value to print. **Note that in this case, if one uses the format string `{<arg>:<spec>.*}`, then the `<arg>` part refers to the value to print, and the precision must come in the input preceding `<arg>`.**

(emphasis mine)

How could this statement be understood as `format!` should pick up the next unnumberd positional argument as the precision?

**Comment by shahn** [comment]
Oh curious, I missed that part. Indeed the behaviour is different. cc @steveklabnik - what is the intended behaviour here?

**Comment by nodakai** [comment]
The current implementation seems to *force* you to consume unnamed positional arguments even for printing a numbered positional argument, which I strongly doubt is the intended behavior.

**Comment by pnkfelix** [comment]
IMO the whole "takes the preceding parameter" specification seems really suspect when used in tandem with named parameters...

**Comment by pnkfelix** [comment]
(I'm a little surprised we didn't have it take a tuple of `(precision, value)` instead of feeding them in as separate arguments...)

**Comment by aturon** [comment]
cc @alexcrichton

**Comment by alexcrichton** [comment]
Although surprising, this behavior is intentional. Specifically [in the documentation](http://doc.rust-lang.org/std/fmt/#positional-parameters) you'll find this clause:

> Each formatting argument is allowed to specify which value argument it's referencing, and if omitted it is assumed to be "the next argument".

So here for the format string `"{} is {0:.*}"` the first reference, `{}`, does not specify what it references so it takes the 0th argument. The next reference, `{0:` references a specific argument, the 0th argument again. Finally the last reference `.*}`, does not reference a specific argument, so the next is taken, the 1th argument.

The docs that @nodakai pointed out could perhaps be clarified that it's the fallback behavior if positions aren't specified.

**Comment by shahn** [comment]
Seems like the "and the precision must come in the input preceding <arg>." that nodakai pointed out is plain wrong?

**Comment by alexcrichton** [comment]
No that behavior's correct, it just needs a clause indicating that it's not applicable if one of the arguments is specified at a particular position.

**Comment by nodakai** [comment]
@alexcrichton `.*` unconditionally consumes an unnumbered positional parameter *by design*? I have to say that was a bad decision. I like @pnkfelix's idea of `(usize, obj)` pair. What would be the formal procedure to introduce this incompatible change?

**Comment by eruca** [comment]
there are too many rules could apply to this issue which make complicated, preventing new-ers like me to learn and deep into rust.

**Comment by alexcrichton** [comment]
@nodakai yes this is intentional, and whether or not you think it's a bad decision or not the ship may have already sailed here. This has been stable for quite some time now and breakage may be hard to stomach, but the procedure is the same as all other breaking changes, they require an RFC.

**Comment by shahn** [comment]
In  "{\<arg\>:\<spec\>.*}", what is the \<spec\> part?

**Comment by shahn** [comment]
I hope I managed to capture everything above. I aimed mostly for terseness
