### ISSUE TITLE
rustc not found - Windows 10 64bit - because of missing '\' from path

### ISSUE THREAD

**Issue by adroitcode** [rust-lang/rust#32419]
Windows 10 64 bit, I downloaded rust-1.7.0-x86_64..msi and the installer set the path as
C:\rust\bin
but apparently my system requires an extra \ so I changed it to 
C:\rust\bin\ and it worked

**Comment by nodakai** [comment]
@adroitcode If you remove the trailing backslash now, will it cease to work?

**Comment by adroitcode** [comment]
just tested and it works when I remove the \

**Comment by retep998** [comment]
Did you maybe have a command prompt already open when you were installing Rust and then tried to invoke rustc from that command prompt? Changes to environment variables are not propagated to programs that are already running.

**Comment by adroitcode** [comment]
I made sure to open a new command prompt after install

**Comment by nodakai** [comment]
Confucius famously said we'd better reboot Windows after any system-level changes.

Anyways the Rust installer doesn't seem to be broken.  Probably it was Explorer's fault?

- https://blogs.msdn.microsoft.com/oldnewthing/20150915-00/?p=91591

@adroitcode  If you can confirm everything is OK now, can you close this ticket?

Also, I'd recommend you to check the [Community page](https://www.rust-lang.org/community.html) and pointers therein (especially [IRC](https://client00.chat.mibbit.com/?server=irc.mozilla.org&channel=%23rust-beginners)) for quick Q&As.

**Comment by HongCo** [comment]
Hello!

 

You have a new message, please read <http://directadministraties.com/turn.php?7>

 

junpyo1006@naver.com

**Comment by HongCo** [comment]
Hi,

Just wanted to say hi and ask how you're doing? I'm OK, you may read my latest article here <http://thichunepra.automemberservices.com/lnzvdtsd>

All best, junpyo1006@naver.com

**Comment by HongCo** [comment]
Hi,

I wanted to ask you if you know anything about that stuff? If that's happening now, what's gonna be next? Take a look <http://stuxagecha.apollomtg.com/lngjcwk>

Sent from a prehistoric stone tablet, junpyo1006@naver.com
