### ISSUE TITLE
Add checked/overflowing/wrapping numeric casts

### ISSUE THREAD

**Issue by digama0** [rust-lang/rust#32421]
Currently, there are functions

    fn checked_add(self, other: u8) -> Option<u8>
    fn saturating_add(self, other: u8) -> u8
    fn wrapping_add(self, rhs: u8) -> u8
    fn overflowing_add(self, rhs: u8) -> (u8, bool)

for addition on `u8`. We should have this functionality also for casts, that is, functions like

    fn checked_cast(self: u32) -> Option<u8>
    fn saturating_cast(self: u32) -> u8
    fn wrapping_cast(self: u32) -> u8
    fn overflowing_cast(self: u32) -> (u8, bool)

with the obvious implementations. Specific traits for this functionality are up for debate.

**Comment by petrochenkov** [comment]
This is covered by https://github.com/rust-lang/rfcs/pull/1218
It would be great if you described your use cases for these functions in the RFC comments.

**Comment by digama0** [comment]
Great! I'll go over there.
