### ISSUE TITLE
Can't configure on OSX (nightly)

### ISSUE THREAD

**Issue by yongqli** [rust-lang/rust#32442]
After updating Xcode, running `./configure` results in:

    configure: error: bad APPLE CLANG version: 7.3.0, need >=7.0

     % clang --version
    Apple LLVM version 7.3.0 (clang-703.0.29)
    Target: x86_64-apple-darwin15.4.0
    Thread model: posix
    InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by durka** [comment]
looks like this will be fixed by #32425

**Comment by cryon** [comment]
This is still an issue with release 1.8.
