### ISSUE TITLE
Source archives should contain Git commit hash and date

### ISSUE THREAD

**Issue by nodakai** [rust-lang/rust#32444]
Can we include the output of `git log -1` into the source archives?  It can be important for beta and nightly.

Ideally the download page should also display them.
- https://www.rust-lang.org/downloads.html

**Comment by petevine** [comment]
Yes, [please.](https://github.com/rust-lang/rust/issues/30363#issuecomment-186675689)

**Comment by alexcrichton** [comment]
This should be a pretty easy bug to tackle for anyone aspiring to do so. Let's just create a file called `VERSION` in our tarballs with basically the output of `rustc -v`

**Comment by brson** [comment]
This will require editing the makefiles in `mk/dist.mk` as well as the rustbuild build system in `src/rustbuild`. The version info is in `CFG_VERSION`. I realized that the installers already include this info in a file called 'version', so we can just duplicate that logic. Use the same lower case naming for consistency.
