### ISSUE TITLE
JSON errors should include macro expansion info

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#32457]
For non-JSON errors, this is computed from the span and codemap. For JSON errors, we should do basically the same thing and put the result in the JSON.

**Comment by steveklabnik** [comment]
the rustc book says

```
            /* The file where the span is located.
               For spans located within a macro expansion, this will be the
               name of the expanded macro in the format "<MACRONAME macros>".
            */
```

https://doc.rust-lang.org/stable/rustc/json.html

So it looks like we do this now!
