### ISSUE TITLE
Breaking Change - encode_utf8 destabilised

### ISSUE THREAD

**Issue by thepowersgang** [rust-lang/rust#32460]
The change 2b3c5acb1d41a870015c53825689e9ebe4b724e8 converted `char::encode_utf8` from a stable method of an unstable trait to an unstable method.

The trait `CharExt` is imported as part of libcore's prelude, which can be done on the stable build (see https://play.rust-lang.org/?gist=7320c1273bdc3dde5450&version=stable).
Under current nightly, the same code fails to compile due to this same API.

This is technically a regression, and may need a crater run to check if it breaks anything (unlikely), and may need closer scrutiny.

**Comment by thepowersgang** [comment]
cc #27784 @alexcrichton

**Comment by thepowersgang** [comment]
Note, discussion in the PR #32204 on the relevant lines. Appears that breakage was acknowledged and assumed to not have any impact.

**Comment by bluss** [comment]
It's a regression in the sense that it breaks / changes behavior of stable code (but this doesn't alone imply that, or imply that it not, needs to be fixed.)

**Comment by alexcrichton** [comment]
triage: I-nominated

nominating for discussion in a libs triage meeting. @thepowersgang is this enough enough to work around for you? For example, do you have crates that build on stable which require this method?

Ideally we could let this slide, but if the breakage is too much we'll just have to bite the bullet and revert.

**Comment by thepowersgang** [comment]
The only breakage I had was on a nightly-only project, I just noted that I needed to add a feature flag to a crate that didn't need any originally (so no real problem at all).

I just created this ticket to make sure that it was noticed and properly documented.

**Comment by alexcrichton** [comment]
Ok, thanks for the info and heads up! We'll discuss this at the next meeting and can decide what to do.

**Comment by thepowersgang** [comment]
Note - I am all for the new API, so if this change doesn't impact anyone else then probably just as good to keep it.

**Comment by alexcrichton** [comment]
The libs team discussed this regression during triage today and the decision was that this is acceptable for now. This is a clear case of fixing a bug. We'll do a crater run to analyze more crates and see what pops up, though.
