### ISSUE TITLE
Thread name with null crashes with "Illegal instruction"

### ISSUE THREAD

**Issue by diwic** [rust-lang/rust#32475]
Trying the following example on playpen (notice the `\0` inside the thread name)

    fn main() {
        std::thread::Builder::new().name("chi\0ld1".to_string()).spawn(|| {
            println!("Hello, world!");
        }).unwrap().join().unwrap();
    }

Playpen output:

    thread '<unnamed>' panicked at 'thread name may not contain interior null bytes', ../src/libstd/sys/unix/thread.rs:90
    note: Run with `RUST_BACKTRACE=1` for a backtrace.
    fatal runtime error: Could not unwind stack, error = 5
    playpen: application terminated abnormally with signal 4 (Illegal instruction)

Both on stable and nightly.

**Comment by diwic** [comment]
https://github.com/rust-lang/rust/pull/32476

**Comment by pmarcelll** [comment]
It can be closed, right?

**Comment by sfackler** [comment]
Yep

**Comment by diwic** [comment]
I was leaving it open because I did not know if it was going to be beta nominated or not.
