### ISSUE TITLE
Naked functions do not require unsafety

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#32489]
[RFC](https://github.com/rust-lang/rfcs/blob/master/text/1201-naked-fns.md) states that naked functions must either not contain any “safe” blocks or be unsafe themselves. Currently, code like 

```
#![feature(asm, naked_functions)]

#[naked]
extern "win64" fn naked(x: u32) -> u32 {
    x + 1
}
```

is accepted.

**Comment by nagisa** [comment]
cc https://github.com/rust-lang/rust/issues/32408

**Comment by steveklabnik** [comment]
Triage: still reproduces today

**Comment by npmccallum** [comment]
@nagisa @steveklabnik I propose we reject this bug in light of the [Constrained Naked RFC](https://github.com/rust-lang/rfcs/pull/2972). There is nothing which prevents a naked function from being safe.
