### ISSUE TITLE
broken links in compiler-plugins.html

### ISSUE THREAD

**Issue by oconnor663** [rust-lang/rust#32493]
https://doc.rust-lang.org/book/compiler-plugins.html

Both links in the Introduction section are dead.

**Comment by alexcrichton** [comment]
Thanks for the report! These have all been [fixed on nightly](https://doc.rust-lang.org/nightly/book/compiler-plugins.html), and that'll make its way to stable eventually.

**Comment by oconnor663** [comment]
Oh sweet, I'll remember to look there next time.
