### ISSUE TITLE
Flood of unexpected token: `<eof>` errors triggered by foo(|_|)

### ISSUE THREAD

**Issue by 0x7CFE** [rust-lang/rust#32505]
The easiest way to reproduce the error is to compile the following code:

```rust
pub fn test() {
    foo(|_|)
}
```

After I try `rustc report.rs -o test` I get the following output:

```
report.rs:3:1: 3:2 error: unexpected token: `<eof>`
report.rs:3 }
            ^
report.rs:3:1: 3:2 error: unexpected token: `<eof>`
report.rs:3 }
            ^
report.rs:3:1: 3:2 error: unexpected token: `<eof>`
report.rs:3 }
            ^
(ad infinitum...)
```
I expect to get the single line error output, not the flood.

## Meta

rustc 1.9.0-dev (10bdd808b 2016-03-18)
binary: rustc
commit-hash: 10bdd808b5e6e23ed8dd9f281c60193a570865f9
commit-date: 2016-03-18
host: x86_64-unknown-linux-gnu
release: 1.9.0-dev

**Comment by 0x7CFE** [comment]
Looks like it is a fairly recent bug. It reproduces on the nightly build, yet version `(rustc 1.7.0-beta.4 (5ed7d4e31 2016-02-26))` works ok.

I checked on my machine and through versions available at http://rust.godbolt.org/

**Comment by nagisa** [comment]
https://github.com/rust-lang/rust/pull/32479 might help.

**Comment by eddyb** [comment]
@nagisa It's actually fixed on master.

**Comment by nikomatsakis** [comment]
triage: P-low
