### ISSUE TITLE
Out of memory during compilation

### ISSUE THREAD

**Issue by Alex-Diez** [rust-lang/rust#32502]
Hi

I got OOM error during compilation following code

```rust
struct Node {
    key: isize,
    left: Option<Node>,
    right: Option<Node>,
}

impl Node {
    fn new(key: isize) -> Node {
        Node {
            key: key,
            left: None,
            right: None,
        }
    }
}

fn main() {
    let node = Node::new(1);
}
```

rustc 1.9.0-nightly (98f0a9128 2016-03-23)
binary: rustc
commit-hash: 98f0a9128f0fc6545de14a5de8f0e91675045e56
commit-date: 2016-03-23
host: x86_64-pc-windows-gnu
release: 1.9.0-nightly

I did a simple test on [PlayPen](http://is.gd/yEzWYn) today and got `playpen: timeout triggered!` message on both beta and nightly

**Comment by jonas-schievink** [comment]
That's #32326

**Comment by Alex-Diez** [comment]
Thanks for pointing
I will close this one
