### ISSUE TITLE
Why use path.display()?

### ISSUE THREAD

**Issue by srinivasreddy** [rust-lang/rust#32514]
I have tried this code 

`println!("{}", path);` where path is std::path::Path variable.  This code complains that Display is not implemented for Path. Instead i need to use path.display(). I do not understand, why can't we implement the trait - Display?

**Comment by bluss** [comment]
Hi! These discussions are best posted on [the user forum](https://users.rust-lang.org/), if you don't pop into a rust irc channel, where people can answer as well.

One problem with `Display` is that it is tied to `ToString` and its `.to_string()` method. And the problem with that, is that it would enable a method called `.to_string()` on a path, without proper notice to the user that this is a lossy conversion. Not all paths can be valid strings.

**Comment by bluss** [comment]
You're welcome to file bugs with problems in rust you find in the future! Questions and the like are best on the forum.
