### ISSUE TITLE
std::io::Stdin.read_line is not blocking

### ISSUE THREAD

**Issue by skylerberg** [rust-lang/rust#32517]
After updating to the latest nightly, `read_line` has stopped blocking. As soon as it is called, it returns successfully and reports that it read 0 bytes.

Code this problem was found in: https://github.com/redox-os/ion/blob/master/src/input_editor.rs#L5.
Rust version: `rustc 1.9.0-nightly (a1e29daf1 2016-03-25)`
Shells tested in: zsh, bash, tcsh, fish, ksh
Operating system: Ubuntu 14.04.
`uname -a`: `Linux sib5 4.2.3-040203-generic #201510030832 SMP Sat Oct 3 12:34:31 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by alexcrichton** [comment]
I believe this was fixed in https://github.com/rust-lang/rust/pull/32257, but thanks for the report!
