### ISSUE TITLE
doc.rust-lang.org is outdated

### ISSUE THREAD

**Issue by ProgVal** [rust-lang/rust#32528]
The [Closing Thoughts](https://doc.rust-lang.org/book/getting-started.html#closing-thoughts) section of the Getting Started page contains a broken link to “Learn Rust” (removed in 0c6c34de87c899ecb8b977e7ef24510ab2a68168)

This problem was fixed in ace39cbc15488eb949ef4dc13a10137b170709b1, but does not seem to be applied to the online doc.

**Comment by steveklabnik** [comment]
Yes, this is an artifact of the release process. That commit is in the next release, you can see it fixed on beta here: https://doc.rust-lang.org/beta/book/getting-started.html#closing-thoughts
