### ISSUE TITLE
Weird thread::sleep() behavior on Windows

### ISSUE THREAD

**Issue by Saevitus** [rust-lang/rust#32525]
We were messing with this code:
    
    
    use std::thread::sleep;
    use std::time::Duration;

    fn slow_print(str: String, t: u64) {
        for c in str.chars() {
            print!("{}", c);
            sleep(Duration::from_millis(t));
        }
    }
    
    fn main() {
    
        slow_print("ayy lmao".to_string(), 100);

    }

Which, on MacOS, sleeps after each letter for a period of time.

But on windows, the sleeping only delays the whole thread for the set amount of time then prints the whole string, instead of sleeping after each letter of the string.

## Meta

rustc 1.7.0 (a5d1e7a59 2016-02-29)
binary: rustc
commit-hash: a5d1e7a59a2a3413c377b003075349f854304b5e
commit-date: 2016-02-29
host: x86_64-pc-windows-gnu
release: 1.7.0

**Comment by nodakai** [comment]
I guess this is a side effect of output buffering by stdout.

- https://users.rust-lang.org/t/flush-the-standard-output-on-terminal/1018

If `std::io::stdout().flush()` resolves your issue, please close this ticket.

**Comment by 89z** [comment]
Arg I just ran into this, that `flush` tip should be mentioned here:

https://doc.rust-lang.org/std/thread/fn.sleep.html
