### ISSUE TITLE
Infinite loop when `let` is in only token in function body

### ISSUE THREAD

**Issue by kazagistar** [rust-lang/rust#32537]
This works fine in Stable, but is broken in Beta and Nightly:

```
fn main(){
    let
}
```
[Playground link.](http://is.gd/C2vEBT)

This is the output:

```
<anon>:3:1: 3:2 error: unexpected token: `<eof>`
<anon>:3 }
         ^
<anon>:3:1: 3:2 error: unexpected token: `<eof>`
<anon>:3 }
         ^
<anon>:3:1: 3:2 error: unexpected token: `<eof>`
<anon>:3 }
         ^

... <snip>
```

This keeps looping forever, or until the timeout on the playground.

In case it helps, here is the version info:
```
rustc 1.9.0-nightly (d5a91e695 2016-03-26)
binary: rustc
commit-hash: d5a91e69582b63f19192ad860df0f7a9a8530f56
commit-date: 2016-03-26
host: x86_64-apple-darwin
release: 1.9.0-nightly
```

**Comment by alexcrichton** [comment]
I think this has been [fixed on nightly](https://github.com/rust-lang/rust/pull/32435) and is nominated for a backport, so closing. 

Thanks for the report though!
