### ISSUE TITLE
Rustdoc fails with info about symbol names

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#32532]
A bunch of my nightly builds are now generating the error:

error: the current crate is indistinguishable from one of its dependencies: it has the same crate-name `libc` and was compiled with the same `-C metadata` arguments. This will result in symbol conflicts between the two. [E0519]

This is likely due to the revamp of symbol names, but it's also unfortunately a regression on nightly. I think what's happening here is that Cargo isn't passing `-C metadata` to rustdoc (because it can't) and then the crates.io libc crate is conflicting with the in-tree libc crate.

cc @nikomatsakis

**Comment by alexcrichton** [comment]
Ah, and an example of a [failing build](https://travis-ci.org/conduit-rust/conduit-cookie/jobs/118832935)

**Comment by brson** [comment]
I'm hitting this too.

**Comment by nikomatsakis** [comment]
cc @michaelwoerister

**Comment by nikomatsakis** [comment]
@brson specifically with libc, or with other crate names?

**Comment by nikomatsakis** [comment]
So I'm trying to figure out if the right answer here is that we should just be passing in metadata to rustdoc? Seems plausible.

**Comment by michaelwoerister** [comment]
Hm, in rustdoc we actually don't care about symbol name conflict, so we could indicate that to the crate loader?

**Comment by michaelwoerister** [comment]
The analysis of the underlying reason by @alexcrichton seems plausible to me, by the way.

**Comment by nikomatsakis** [comment]
> Hm, in rustdoc we actually don't care about symbol name conflict, so we could indicate that to the crate loader?

Maybe, but it seems sloppy to me -- I mean, why don't we care? The signatures might well be different, for example, so it might well matter. In any case, I'm trying to understand what is leading us to get this conflict still (I haven't reproduced it yet -- what target do I need to use?).

> The analysis of the underlying reason by @alexcrichton seems plausible to me, by the way.

I feel like I'm still missing something. From what I can tell, the error comes when generating docs for the `libc` crate -- so why is it accessing crates.io anyway? And doesn't crates.io give metadata when building? (Do we tell rustdoc where to find all dependencies the same way we tell rustc? I would expect so...but maybe it's falling back to some other behavior and scraping things off the file system?)

Perhaps part of it is that I am a bit removed from the details of how a lot of this lower level stuff works.

**Comment by nikomatsakis** [comment]
ok, I see now that this error is not when bootstrapping.

**Comment by nikomatsakis** [comment]
Further investigation reveals that somehow we do not seem to be supplying `-C metadata` except for tests. Oops. That will presumably fix this conflict, though not in the best possible way -- because now the makefile libc will have a disambiguator, so the rustdoc version would have a disambiguator of just `""` and everybody is happy.

That said, it seems to me that `rustdoc` should take a `-C metadata` argument -- presumably it should take the same arguments as rustc, since it basically *invokes* rustc.

**Comment by michaelwoerister** [comment]
> Cargo isn't passing -C metadata to rustdoc (because it can't)

@alexcrichton Can you elaborate on that?

**Comment by alexcrichton** [comment]
I believe this is fixed in https://github.com/rust-lang/rust/pull/32560, explained here: https://github.com/rust-lang/rust/pull/32560#issuecomment-202476254.

To elaborate on the lack of metadata, rustdoc simply doesn't accept `-C` flags, so that's why it's not being passe d:)

**Comment by nikomatsakis** [comment]
@alexcrichton did you actually check whether this is fixed? I wonder if it's worth trying to allow rustdoc to accept -C metadata -- I guess so long as it doesn't matter, it doesn't matter.

**Comment by alexcrichton** [comment]
Nah I was hoping to test with today's nightly, but that's blocked on https://github.com/rust-lang/rust/issues/32568. I'm pretty confident that the change would fix this, however.

**Comment by paukul** [comment]
FYI rustc 1.9.0-nightly (b678600ac 2016-03-29) fixed this issue for me
