### ISSUE TITLE
rustdoc still displays "pub" for an exported copy of struct-like enum variants

### ISSUE THREAD

**Issue by nodakai** [rust-lang/rust#32545]
Continued from #32395

Apparently #32423 was not a complete fix.

https://doc.rust-lang.org/nightly/std/ops/enum.RangeInclusive.html
```rust
pub enum RangeInclusive<Idx> {
    pub Empty {
        at: Idx,
    },
    pub NonEmpty {
        start: Idx,
        end: Idx,
    },
}
```

**Comment by mitaa** [comment]
Sorry... T_T

I think this should be fixed with https://github.com/rust-lang/rust/commit/d0f74b605942849b647b0e262fbda1969bd73c2a for good. Can you confirm that (once this has hit the docs)?

**Comment by tbu-** [comment]
This has been fixed, it now looks like this:
```
pub enum RangeInclusive<Idx> {
    Empty {
        at: Idx,
    },
    NonEmpty {
        start: Idx,
        end: Idx,
    },
}
```

**Comment by alexcrichton** [comment]
Yay!
