### ISSUE TITLE
Symbol names for generics are not stable across crates

### ISSUE THREAD

**Issue by dotdash** [rust-lang/rust#32554]
Given this:
cgu.rs
```rust
#![crate_type="lib"]
pub fn id<T>(t: T) -> T {
  t
}
pub fn user() {
  id(0);
}
```

a.rs
```rust
#![crate_type="lib"]
extern crate cgu;
pub fn user() {
  cgu::id(0);
}
```

We get two different symbol names for the monomorphizations of id.

cgu.ll
```llvm
define internal i32 @_ZN3cgu2id17h7cbc0f1ce1830012E(i32) unnamed_addr #0 {
entry-block:
  %dropflag_hint_6 = alloca i8
  %t = alloca i32
  store i8 61, i8* %dropflag_hint_6
  store i32 %0, i32* %t
  %1 = load i32, i32* %t
  ret i32 %1
}
```

a.ll
```llvm
define internal i32 @_ZN3cgu2id17h8a873a51d5137f87E(i32) unnamed_addr #0 {
entry-block:
  %t = alloca i32
  store i32 %0, i32* %t
  %1 = load i32, i32* %t
  ret i32 %1
}
```

cc @nikomatsakis @michaelwoerister

**Comment by michaelwoerister** [comment]
Interesting.

**Comment by michaelwoerister** [comment]
I'm going to look into this a little...

**Comment by michaelwoerister** [comment]
That might be the culprit:
https://github.com/rust-lang/rust/blob/641204a408ecda8494adce213e1d5c65f4220756/src/librustc/ty/context.rs#L437
```rust
pub fn crate_disambiguator(&self, cnum: ast::CrateNum) -> token::InternedString {
        if cnum == LOCAL_CRATE {
            self.sess.crate_disambiguator.get().as_str()
        } else {
            self.sess.cstore.crate_name(cnum)
        }
    }
```
One at least...

**Comment by nikomatsakis** [comment]
@michaelwoerister d'oh that looks like a copy-n-paste bug...

**Comment by michaelwoerister** [comment]
It does. I'm currently in the process of writing a test case for this.

**Comment by arielb1** [comment]
aren't these internal symbols anyway?

**Comment by dotdash** [comment]
@arielb1 Not necessarily when using multiple codegen units. And even otherwise, it's nice to have the same name across all crates. In theory, for a size-optimized build we might also want to switch to linkonce_odr or weak_odr linkage, in which case we'd also need the names to be the same.
