### ISSUE TITLE
Add `values_mut` to `{BTree, Hash}Map`

### ISSUE THREAD

**Issue by LukasKalbertodt** [rust-lang/rust#32551]
I don't understand why there is a [`values()` method](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.values), but no `values_mut()` method for map-collections. While `keys_mut()` can't work, `values_mut()` shouldn't be a problem, right?

It would be equivalent to `map.iter_mut().map(|(_, v)| v)`.

**Comment by frewsxcv** [comment]
I'll open a PR for this.

**Comment by frewsxcv** [comment]
Opened a PR: https://github.com/rust-lang/rust/pull/32633.

**Comment by frewsxcv** [comment]
This is now implemented in `master`.

**Comment by vks** [comment]
I think this can be closed.

**Comment by frewsxcv** [comment]
@vks From what I understand, all unstable features in the Rust compiler all need associated tracking issues until the features become stable. This is presumably the tracking issue for the `map_values_mut` feature.

**Comment by alexcrichton** [comment]
🔔 This issue is now entering its cycle-long **final comment period** for stabilization 🔔

**Comment by alexcrichton** [comment]
The libs team discussed this during triage yesterday and the decision was to **stabilize**
