### ISSUE TITLE
rustdoc where clause is not reproducible

### ISSUE THREAD

**Issue by sanxiyn** [rust-lang/rust#32555]
For example, run `make doc/alloc/index.html` twice in a row and check `doc/alloc/boxed/struct.Boxed.html`. Where clause of `flat_map` can be either `where U: IntoIterator, F: FnMut(Self::Item) -> U`, or `where F: FnMut(Self::Item) -> U, U: IntoIterator`.

I think it is suspect that `where_cluases` function in `src/librustdoc/clean/simplify.rs` uses `HashMap`.

**Comment by mitaa** [comment]
Related to #24473
