### ISSUE TITLE
[rustdoc] Anchors to trait implementations always point to the first

### ISSUE THREAD

**Issue by azerupi** [rust-lang/rust#32552]
The anchors that Rustdoc generates for multiple implementations of a trait (like `Add` for multiple different `rhs`) always point to the first implementation.

If you take a look to [rust-sfml Vector2f](http://www.rust-sfml.org/doc/rsfml/system/vector2/struct.Vector2f.html), it implements `impl Add<f32> for Vector2f` and `impl Add for Vector2f`. But both anchors are the same:  
http://www.rust-sfml.org/doc/rsfml/system/vector2/struct.Vector2f.html#method.add

You can't link to the second implementation...

**Comment by mitaa** [comment]
This should be fixed (#30036)

For example:
https://doc.rust-lang.org/nightly/std/string/struct.String.html#method.as_ref
https://doc.rust-lang.org/nightly/std/string/struct.String.html#method.as_ref-1

**Comment by azerupi** [comment]
OK, my bad :)

Thanks!
