### ISSUE TITLE
404 not found while install rust lang

### ISSUE THREAD

**Issue by netroby** [rust-lang/rust#32566]
https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256

was 404 not found while we try to install rust lang .

```
huzhifeng@w ~ $ wget -qO- https://static.rust-lang.org/rustup.sh | sh
rustup: gpg available. signatures will be verified
rustup: downloading manifest for 'stable'
rustup: command failed: curl -s -f -O https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256
rustup: couldn't download checksum file 'https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256'
rustup: downloading manifest for 'stable'

```

**Comment by durka** [comment]
This always happens for stable and beta, but the installation should continue anyway.

**Comment by nodakai** [comment]
@durka Oddly enough beta.toml.sha256 is in https://static.rust-lang.org/dist/ :-)

@netroby Have you tried https://www.rustup.rs/ ?  It can install the toolchains under your $HOME and keep them updated with the latest releases. The bad news is it's still at an early stage of development. The good news is, the compiler itself is quite stable unlike the installer :-)

Newcomers will keep posting the same bug again and again unless the team really fixes it. And how can they trust a compiler when they encounter an error even before they run it?

**Comment by cengizIO** [comment]
@netroby Hello!

This seems to affect the checksum file only. 

Rust compiler will install fine at your end. 

In the meantime, I'm going to explore this further.

Thanks for reporting!

**Comment by netroby** [comment]
Rust lang 1.8.0 rustup seems fix this bug now.
