### ISSUE TITLE
Cross-host builds are broken (and nightlies)

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#32568]
The bots [are failing](http://buildbot.rust-lang.org/builders/nightly-dist-rustc-mac/builds/553/steps/compile/logs/stdio) due to opaque rpath issues. I believe this was caused by b20e748ad88daee81488c1033971eec6b139d291 in https://github.com/rust-lang/rust/pull/32252 (cc @durka)

I'm tired and gonna go to bed, but I've got a build running which I'll hopefully be able to diagnose tomorrow morning. Just wanted to file this to make sure we know nightlies aren't working.

**Comment by durka** [comment]
Sucks. That change was necessary to make c-dynamic-dylib pass on my test server (host x86-64, target x86-unknown-linux). Are we just stuck backing out the whole thing and having `#[derive(Hash)]` broken until rustbuild works?
