### ISSUE TITLE
std::collections::BTreeSet documentation link to BTreeMap broken

### ISSUE THREAD

**Issue by archshift** [rust-lang/rust#32569]
[The docs for BTreeSet](https://doc.rust-lang.org/std/collections/struct.BTreeSet.html) link to BTreeMap in the intro section of the documentation. However, this link is broken.

**Comment by mitaa** [comment]
This is tracked in #32130, thanks for reporting though!

**Comment by steveklabnik** [comment]
Yes, closing as a duplicate.
