### ISSUE TITLE
Short array initialisation doesn't work with Clone types

### ISSUE THREAD

**Issue by emilio** [rust-lang/rust#32573]
I expected something like this to work:

```rust
#[derive(Clone)]
struct Foo;

fn main() {
    let foo_arr = [Foo; 500];
}
```

But it fails with the error:

```
error: the trait `core::marker::Copy` is not implemented for the type `Foo`.
```

It's not always possible to derive `Copy` in a struct (for example, if it contains a `Cell`), but it might be desirable to initialise an array this way.

Is there some reason for it not working on `Clone` types? Or is it just not implemented?

**Comment by steveklabnik** [comment]
http://doc.rust-lang.org/std/primitive.array.html

> Arrays of sizes from 0 to 32 (inclusive) implement the following traits if the element type allows it:

Basically, the type system can't be generic over integers, so traits are only implemented up to size 32. This limitation will hopefully be lifted eventually.

**Comment by emilio** [comment]
I don't think we're talking about the same thing, this doesn't work neither for `[Foo; 20]`.

**Comment by emilio** [comment]
What I'm complaining about is that:

> The repeat expression requires that the element type is Copy.

Where with `T: Clone` it'd be also useful.

**Comment by arielb1** [comment]
@emilio 

But the repeat expression is a built-in expression, and therefore it does not allocate. Once we have type-level integers, you could write a `clone` version in a library.

**Comment by emilio** [comment]
Humm... I see, so the problem is that `Clone` *might* allocate. That makes sense, and was the kind of thing I expected to be missing.

Thanks!
