### ISSUE TITLE
Differentiate between InvalidData and UnexpectedEnd in `std::str::Utf8Error`

### ISSUE THREAD

**Issue by troplin** [rust-lang/rust#32584]
For incremental "parsing" of string data (e.g. when reading from a stream) it would be helpful to know if an error is due to invalid bytes or premature end of data.

Something like:

``` rust
enum Utf8ErrorKind {
    InvalidData,
    UnexpectedEnd,
}

impl Utf8Error {
    pub fn kind(&self) -> Utf8ErrorKind {...}
}
```

or something simpler, like:

``` rust
impl Utf8Error {
    pub fn is_invalid_data(&self) -> bool {...}
}
```

As a side question, what's the preferred way for small feature requests like this one? Issue, PR, RFC or internals forum?

**Comment by Mark-Simulacrum** [comment]
The two APIs exposed by Utf8Error today, valid_up_to and error_len should satisfy this issue, so I'm going to close. For reference: https://doc.rust-lang.org/nightly/std/str/struct.Utf8Error.html.
