### ISSUE TITLE
Incorrect links in documentation

### ISSUE THREAD

**Issue by tyoc213** [rust-lang/rust#32585]
Here https://doc.rust-lang.org/book/getting-started.html#closing-thoughts the link 

 ‘Learn Rust’
https://doc.rust-lang.org/book/learn-rust.html 

Gives 404.

**Comment by alexcrichton** [comment]
Thanks for the report! This has been fixed on beta and nightly, so those fixes should go out for the next release.

**Comment by tyoc213** [comment]
@alexcrichton well, even if closed, I also think that the linked IRC channel for people reading the book should be now #rust-begginers

**Comment by alexcrichton** [comment]
Sure! Want to send a PR?

**Comment by tyoc213** [comment]
@alexcrichton sure why not xD! let me try!
