### ISSUE TITLE
Make it easier to build libstd, liballoc, libcore, etc for cross compiled environments

### ISSUE THREAD

**Issue by cardoe** [rust-lang/rust#32597]
This is really for those that do cross compiles and also for source based distros that cross compile. Right now you must build llvm, rustc, and libstd for each platform you intend to target but the idea here would be you build llvm, rustc and libstd for your HOST and it should only need libstd (and its depends) to be a full cross compile environment. e.g.

```
<snip>
/usr/lib/rust-1.7.0/rustlib/x86_64-unknown-linux-gnu/lib/libstd-6a154fe0.rlib

<snip>
/usr/lib/rust-1.7.0/rustlib/i686-unknown-linux-gnu/lib/libstd-6a154fe0.rlib

<snip>
/usr/lib/rust-1.7.0/rustlib/mips-unknown-linux-musl/lib/libstd-6a154fe0.rlib
```

It should be as simple as running: `cargo build --target=mips-unknown-linux-musl` or `cargo build --target=i686-unknown-linux-gnu`

A few projects are aiming to provide this or some subset of this but it seems like they run into limitations and have to massage parts of the Rust build system so it would be nice if the new rustbuild supported this use case.
- https://github.com/japaric/cargo-sysroot
- https://github.com/phil-opp/nightly-libcore

**Comment by archshift** [comment]
Indeed this would be incredibly useful, especially when trying to cross-compile to a platform that rust doesn't provide pre-built binaries for.

**Comment by joerg-krause** [comment]
Yes, I would really appreciate it! For now, cross-compiling the rustlibs for unsupported targets without the need to compile the whole rust environment cannot be done easily.

I asked for support a while ago: https://github.com/rust-lang/rust/issues/30710 and came up with my own solution to cross-build the rustlibs for my ARMv5 target: https://github.com/joerg-krause/rust-cross-libs.

**Comment by archshift** [comment]
For me personally I'd appreciate some kind of way to either `cargo install` a library (using a certain target) or have cargo, when resolving dependencies, to recursively use a provided libcore/other library.

For example, currently if you depend on https://crates.io/crates/rust-libcore in your `Cargo.toml

**Comment by cardoe** [comment]
@joerg-krause You might be interested in this support. I found your project at https://github.com/joerg-krause/rust-cross-libs which made me think of this.

**Comment by steveklabnik** [comment]
There has long been a desire to "bring xargo into cargo", so much so that it's on the cargo team's roadmap for this year. Given that this effort would be tracked as part of that, I don't think this tracking issue really serves a purpose; RFCs will be created and accepted (or denied) based on that effort. So I'm going to give this a close. Thanks!
