### ISSUE TITLE
Allow more-easily-parsable output format for libtest benchmark harness

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#32595]
I thought about creating a utility to visualize the results of `cargo bench`. Has there been any thought about adding a `--format=json` flag to `cargo bench` so this would be easier? I might be interested in implementing this if this gets approval

**Comment by nagisa** [comment]
Has been  a bunch of RFCs on the topic already, latest being https://github.com/rust-lang/rfcs/pull/1284.

**Comment by Mark-Simulacrum** [comment]
I think this would indeed need an RFC; closing.
