### ISSUE TITLE
The place of the name of copyright owner in LICENSE-APACHE is blank

### ISSUE THREAD

**Issue by Kroisse** [rust-lang/rust#32601]
<https://github.com/rust-lang/rust/blob/master/LICENSE-APACHE#L189>:

> ```Copyright [yyyy] [name of copyright owner]```

**Comment by jonas-schievink** [comment]
That's not the copyright owner, it's part of the "how to apply to your code" section

**Comment by Kroisse** [comment]
Oh, I got it. I've misunderstood this section. Closes the issue.
