### ISSUE TITLE
core dependency on c_int in memcmp

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#32610]
libcore/str/mod.rs uses `memcmp`, and declares it to return i32, in reality it returns c_int, so this is a potential portability concern.

Maybe memcmp can be made an intrinsic to resolve this.

**Comment by tbu-** [comment]
It also takes a `size_t` parameter, not a `uintptr_t`.

**Comment by bluss** [comment]
Neither of these are a practical issue. crate libc does not support any other configuration than `c_int = i32` so far.

**Comment by bluss** [comment]
cc @brson

**Comment by Mark-Simulacrum** [comment]
The extern function is now in src/libcore/slice/mod.rs.

**Comment by lzutao** [comment]
What should we do next? Should we try to create a `memcmp` intrinsic?

**Comment by drmorr0** [comment]
Hi, I believe this issue is causing array comparisons on the AVR architecture to break (see the linked issue, #78022).  Is there any consensus on a path forward here?
