### ISSUE TITLE
Misleading message: "error: the trait `Foo` is not implemented for the type `Bar`"

### ISSUE THREAD

**Issue by Yoric** [rust-lang/rust#32611]
Consider three crates High, Mid and Low, where:
- Mid depends on Low;
- High depends on both Mid and Low.

This is a quite common case.

Now, it sometimes happens that the dependency of Mid is bumped to a more recent version of Low. If, however, the developer fails to bump the dependency of High to a more recent version of Low, surprising error messages arise.

In particular,

```
"error: the trait `Foo` is not implemented for the type `Bar`"
```

may arise, without any change to the code of either `Foo` or `Bar`.

It would be great if the compiler could detect the error and somehow print something along the liens of

```
"error: using conflicting versions of the trait `Foo` for type `Bar`. You are probably using two distinct versions of the same library."
```

**Comment by steveklabnik** [comment]
Triage: I feel like this has gotten better in certain cases, but not all. It would be nice to make a way to reproduce this more easily, but it's non-trivial.
