### ISSUE TITLE
The compiler could infer some types using function return values

### ISSUE THREAD

**Issue by julienw** [rust-lang/rust#32614]
With the following code:

```rust
fn get() -> Option<Vec<usize>> {
    let vec = vec![0, 1, 2, 3, 4];
    let result = vec.iter().collect();
    if result.len() == 0 { None } else { Some(result) }
}

fn main() {
    get();
}
```

I get this error:
```
<anon>:4:8: 4:20 error: the type of this value must be known in this context
<anon>:4     if result.len() == 0 { None } else { Some(result) }
                ^~~~~~~~~~~~
error: aborting due to previous error
playpen: application terminated with error code 101
```
Live version: https://play.rust-lang.org/?gist=edcec40ef02d3d56568b68d1faa9b84a&version=nightly

I understand where the issue comes from: typing `result` using `Vec<_>` provides the necessary information. However here the compiler could infer the type of the value, because we're returning `Some(result)` in a branch, and the return type is fully known.

**Comment by arielb1** [comment]
That's not the issue here - the problem is that type checking visits the method call `result,len()` before it visits the inner `Some(result)`, and therefore it does not know which type to use.

If you don't use `result.len()` in the if-statement, it works.
