### ISSUE TITLE
Syntax “Fn(i32) -> i32” is used in the Book, but never introduced

### ISSUE THREAD

**Issue by ProgVal** [rust-lang/rust#32615]
First occurence: https://doc.rust-lang.org/beta/book/closures.html#taking-closures-as-arguments

I may have missed it, but I don't see any explanation of `->` in the context of traits.

**Comment by steveklabnik** [comment]
Thank you for these! I am not working on the current book in a significant fashion anymore, instead, working on a second draft. So I would take a PR to fix this, but won't be fixing it myself. So I'm going to give this a close. Any interested parties, feel free to send a patch! It'd be appreciated.
