### ISSUE TITLE
Self and Sized are used in the Book before being introduced

### ISSUE THREAD

**Issue by ProgVal** [rust-lang/rust#32616]
First occurence: https://doc.rust-lang.org/beta/book/trait-objects.html#object-safety

**Comment by steveklabnik** [comment]
Thank you for these! I am not working on the current book in a significant fashion anymore, instead, working on a second draft. So I would take a PR to fix this, but won't be fixing it myself. So I'm going to give this a close. Any interested parties, feel free to send a patch! It'd be appreciated.
