### ISSUE TITLE
emit DW_AT_main_subprogram

### ISSUE THREAD

**Issue by tromey** [rust-lang/rust#32620]
When making an executable, rustc should emit `DW_AT_main_subprogram` on the CU and the subprogram DIE for the main function that is going to be executed by `main`.

This marker would allow gdb's `start` command to find the correct spot in user code to set an initial breakpoint.  (This doesn't work yet, see https://sourceware.org/bugzilla/show_bug.cgi?id=16264 - but could be made to work.)

**Comment by michaelwoerister** [comment]
I can't find any way to make LLVM do this `:/`

**Comment by tromey** [comment]
FWIW I have a patch to LLVM to add the necessary bits.  Now I'm investigating how to get the information from the driver to `create_function_debug_context`.

**Comment by michaelwoerister** [comment]
See https://github.com/rust-lang/rust/blob/43006fcea0066a935b657fff9ccef56983cbf56c/src/librustc_trans/base.rs#L1144
This is how you can get the `DefId` of the main function.

**Comment by tromey** [comment]
Ok, I have this working.  I sent a patch to llvm-commits, but it needs moderator approval to go through, and then of course patch review.

I also have a rustc patch that works, but I haven't written a test case yet.

One possible issue is that the patch that applies to Rust's llvm is different from the patch I sent upstream.  My current plan is to wait until something goes in upstream, then backport it and submit a PR to the Rust fork.

**Comment by michaelwoerister** [comment]
Sounds like a good course of action `:)`

**Comment by tromey** [comment]
http://lists.llvm.org/pipermail/llvm-commits/Week-of-Mon-20161121/407070.html

**Comment by tromey** [comment]
You can see my patch here: https://github.com/tromey/rust/tree/main-subprogram

I think I can't really submit it until the rust-llvm patch is reviewed, because the final rust patch will have to include a change to the submodule revision.

**Comment by tromey** [comment]
Also, FYI, the gdb patch is still pending; I will ping it either tomorrow or Friday.

**Comment by cuviper** [comment]
What happens if you're using an external (unpatched) LLVM?  Will it ignore the unrecognized flag?

**Comment by tromey** [comment]
> What happens if you're using an external (unpatched) LLVM? Will it ignore the unrecognized flag?

I think it depends on the precise version of LLVM.  The version that Rust is using doesn't check flags less than 1<<27 (IIRC), but LLVM trunk checks that the flag is in range -- which is one reason the upstream LLVM patch is a bit different.  I didn't look to see when this change was made in LLVM, but I could if you like.

**Comment by cuviper** [comment]
Currently, Rust supports external LLVM 3.7+, so if unpatched LLVM won't handle this gracefully, it will have to be only conditionally added.

Rust's own is (roughly) 3.9, so if that's not checking flags then I guess it's ok -- the change must have happened only during 4.0 development, which now has your addition before its release anyway.

**Comment by tromey** [comment]
FWIW the gdb patch went in today.
