### ISSUE TITLE
Add a tool to verify core/std have the same API

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#32632]
In theory core is an exact subset of libstd's API surface area. In practice there's been some bugs here and there, so we should write a tool to verify that the two are the same. We can then check it into the tree and sleep soundly at night knowing that they'll never diverge again!

**Comment by alexcrichton** [comment]
cc @rust-lang/libs

**Comment by durka** [comment]
Perhaps just running `libcoretest` against std?

**Comment by alexcrichton** [comment]
Now that's not a bad idea! We could possibly do something like:

```
rustc src/libcoretest/lib.rs --extern core=path/to/libstd.rlib
```

**Comment by steveklabnik** [comment]
Triage: no change

there has been some discussion of eliminating the core/std distinction; if that ever comes to pass, this will end up being "fixed" by that.

**Comment by Mark-Simulacrum** [comment]
Closing as a duplicate of https://github.com/rust-lang/rust/issues/60479 (which has more discussion).
