### ISSUE TITLE
Tracking issue for {VecDeque,LinkedList}::contains

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#32630]
Tracking issue for https://github.com/rust-lang/rfcs/pull/1552

**Comment by LukasKalbertodt** [comment]
I'd like to try adding those methods in the next few days, if no one else is already on it (?) :-)

**Comment by alexcrichton** [comment]
🔔 This issue is now entering a cycle-long **final comment period** for stabilization 🔔

**Comment by alexcrichton** [comment]
Discussed recently, the libs team decided to **stabilize**.
