### ISSUE TITLE
Allow multiple inherent impls on primitive types

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#32631]
In the standard library it's pretty unfortunate that we have to redefine all methods on string, slice, characters, and floating point types in libraries outside of libcore with an inherent methods. It's also unfortunate to have all the extension traits in libcore.

Let's just bite the bullet and allow multiple inherent impls on this type. It will...
- Reduce duplication (thereby preventing drift between API surface area)
- Remove unstable traits
- Perhaps be simpler in terms of resolve

We'll have to be sure to update rustdoc, however, to provide one unified view to the API surface area rather than multiple impl blocks.

cc @rust-lang/libs

**Comment by aturon** [comment]
cc @rust-lang/lang

**Comment by czipperz** [comment]
It appears this has been put on the back burner.  Does anyone plan to implement this?

**Comment by Mark-Simulacrum** [comment]
We seem to mostly permit this today via some lang items (e.g., https://github.com/rust-lang/rust/blob/d0677b9abc143d64d6b0cd6720e36eb73674632f/src/libstd/f32.rs#L28-L29 and https://github.com/rust-lang/rust/blob/d0677b9abc143d64d6b0cd6720e36eb73674632f/src/libcore/num/f32.rs#L147-L149) -- closing as such. If I've misinterpreted then we can of course reopen.
