### ISSUE TITLE
"If not, try an anonymous function" is too vague to be helpful

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#32658]
I just got this error message:

```
../src/test/compile-fail/assign-to-method.rs:30:8: 30:13 error: attempted to take value of method `speak` on type `cat`
../src/test/compile-fail/assign-to-method.rs:30   nyan.speak = || println!("meow"); //~ ERROR attempted to take value of method
                                                       ^~~~~
../src/test/compile-fail/assign-to-method.rs:30:8: 30:13 help: maybe a `()` to call it is missing? If not, try an anonymous function
```

I don't know what "if not, try an anonymous function" means. What about an anonymous function am I supposed to try? Can we remove this help?

**Comment by fhartwig** [comment]
I think the bigger problem is not the vagueness, but that the help doesn't really make sense in this specific context (and neither does the error message). The help is probably fine when you're using (but not calling) a method in an expression, but it doesn't really apply if the method is on the left-hand side of an assignment.

**Comment by Mark-Simulacrum** [comment]
Minimal code to reproduce this:

```rust
fn main() {
    let px = "test".len;
}
```

**Comment by cyplo** [comment]
There referenced code has been merged in it seems.
The message is now (rustc 1.21.0 (3b72af97e 2017-10-09)):

```
error[E0615]: attempted to take value of method `len` on type `&'static str`
 --> main.rs:2:21
  |
2 |     let px = "test".len;
  |                     ^^^
  |
  = help: maybe a `()` to call it is missing?

error: aborting due to previous error
```

Would that be enough to close this issue ?

Thanks !
