### ISSUE TITLE
Docs suggest outdated libc crate version

### ISSUE THREAD

**Issue by slimsag** [rust-lang/rust#32662]
See [the FFI page](http://doc.rust-lang.org/book/ffi.html#a-note-about-libc) which suggests adding:

```
[dependencies]
libc = "0.2.0"
```

People may copy+paste this and not check with https://crates.io/crates/libc first. Might be worth fixing? not sure.

**Comment by retep998** [comment]
Or they could just say `libc = "0.2"`.

**Comment by sfackler** [comment]
An `0.2.0` version is equivalent to `0.2`.

**Comment by slimsag** [comment]
... are you saying `0.2` would actually download `0.2.9` and that `0.2.0` is somehow identical to `0.2.9` ? Could you explain how that works? from first glance it seems rather strange/invalid behavior

**Comment by sfackler** [comment]
`0.2.0` is shorthand for `^0.2.0`, which means `>= 0.2.0, < 0.3.0`: http://doc.crates.io/crates-io.html#using-cratesio-based-crates

**Comment by slimsag** [comment]
Got it.. you're totally right, I'm off my versioning game :) I'll close since this is invalid then.
