### ISSUE TITLE
rustc --explain: automatically use `less` on *nix systems

### ISSUE THREAD

**Issue by stelcheck** [rust-lang/rust#32665]
Ref: https://twitter.com/stelcheck/status/715502560891637760

Since many of the descriptions are rather lengthy, it would be nice to pipe to `less` by default on OS X, Linux and other *nix systems. Should stdout be piped to another process, this can be detected and disabled fairly easily.

**Comment by brson** [comment]
If we're going to consider a pager for this we should consider how pages fit into rustc output more generally. @nikomatsakis and I have talked a lot about how to integrate a pager into rustc.

**Comment by sanmai-NL** [comment]
Please do let any command line utilities default to the value of the environment variable `PAGER` instead of e.g. `less`.

**Comment by nikomatsakis** [comment]
> Please do let any command line utilities default to the value of the environment variable `PAGER` instead of e.g. `less`.

Seems like we should do whatever git does.

**Comment by stelcheck** [comment]
git seems to be using less.

@sanmai-NL didn't know about PAGER, but agree with you.

**Comment by nikomatsakis** [comment]
From the git man page:

>       -p, --paginate
>           Pipe all output into less (or if set, $PAGER) if standard
output is a terminal. This overrides the pager.<cmd> configuration options
(see the
>           "Configuration Mechanism" section below).

**Comment by cengizIO** [comment]
Hello.

If it's ok, I'd like to take this issue on me. Do some research and provide options that we can implement.

**Comment by Mark-Simulacrum** [comment]
@cengizIO Any progress? If not, could someone else take this issue on, or do you still want it?

**Comment by cengizIO** [comment]
Hello again @Mark-Simulacrum,

I couldn't help myself and I've implemented this for *nix systems. I can send a PR whenever I solve the Windows part.

**Comment by Mark-Simulacrum** [comment]
Sounds good!

**Comment by cengizIO** [comment]
Hello! This is currently blocked due to #42553
