### ISSUE TITLE
(Lossy) UTF-8 decoding from Cow<[u8]> to Cow<str>

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#32669]
I found myself writing code (almost) like this, with `Cow<[u8]>` as the output of some other algorithm ([percent-decoding](https://url.spec.whatwg.org/#percent-decode)).

``` rust
use std::borrow::Cow;
use std::str;

pub fn decode_utf8(input: Cow<[u8]>) -> Result<Cow<str>, str::Utf8Error> {
    match input {
        Cow::Borrowed(bytes) => {
            match str::from_utf8(bytes) {
                Ok(s) => Ok(s.into()),
                Err(e) => Err(e),
            }
        }
        Cow::Owned(bytes) => {
            match String::from_utf8(bytes) {
                Ok(s) => Ok(s.into()),
                Err(e) => Err(e.utf8_error()),
            }
        }
    }
}

pub fn decode_utf8_lossy(input: Cow<[u8]>) -> Cow<str> {
    match input {
        Cow::Borrowed(bytes) => String::from_utf8_lossy(bytes),
        Cow::Owned(bytes) => {
            match String::from_utf8_lossy(&bytes) {
                Cow::Borrowed(_) => unsafe { String::from_utf8_unchecked(bytes) }.into(),
                Cow::Owned(s) => s.into(),
            }
        }
    }
}
```

@alexcrichton, do you think this has its place in `std`? Maybe as `from_cow_utf8` and `from_cow_utf8_lossy` methods of `String`?

**Comment by alexcrichton** [comment]
This seems reasonable to me, but I wouldn't want to add it to libstd until we've thought about what the generic use case is here. Is `Cow<[u8]> -> Cow<str>` special? I've written similar code for `Cow<[u8]> -> Cow<Path>` before and it'd be good to think about what the possible union of the two APIs are.

**Comment by dtolnay** [comment]
This is a neat idea! I agree with Alex that by itself this use case seems too uncommon to belong in the standard library. It would be interesting to generalize this to other sorts of Cow -\> Cow conversions, like `Cow<[u8]>` to `Cow<Path>` and `Cow<[u8]>` to percent-decoded. I would be open to considering an [RFC](https://github.com/rust-lang/rfcs/blob/master/libs_changes.md).
