### ISSUE TITLE
Beta and nightly fail with out of memory on invalid recursive macros

### ISSUE THREAD

**Issue by VFLashM** [rust-lang/rust#32705]
This piece of code causes fatal runtime error on beta and nightly:
```rust
macro_rules! a {
    ( $name: ident ) => { impl $name { a!() } };
    () => {}
}
fn b() {
    a!(test);
}
```

**Comment by nikomatsakis** [comment]
This may be fixed, I can't reproduce. I suspect it was related to the spate of bugs that caused parser to loop infinitely.

**Comment by nikomatsakis** [comment]
I'm going to close but @VFLashM feel free to re-open if you think the problem still exists. (I tried both beta and nightly.)
