### ISSUE TITLE
Is debug rustc + (Release+Asserts) llvm a valid bootstrap combination?

### ISSUE THREAD

**Issue by petevine** [rust-lang/rust#32706]
If not, fine, otherwise here's a bug:

```rust
rustc: arm-unknown-linux-gnueabihf/stage0/lib/rustlib/arm-unknown-linux-gnueabihf/lib/librustc_trans
src/librustc_trans/attributes.rs:31:13: 31:43 error: unresolved name `llvm::RemoveFunctionAttributes` [E0425]
src/librustc_trans/attributes.rs:31             llvm::RemoveFunctionAttributes(val, attr)
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/librustc_trans/attributes.rs:31:13: 31:43 help: run `rustc --explain E0425` to see a detailed explanation
src/librustc_trans/attributes.rs:42:9: 42:39 error: unresolved name `llvm::RemoveFunctionAttributes` [E0425]
src/librustc_trans/attributes.rs:42         llvm::RemoveFunctionAttributes(val, llvm::Attribute::UWTable);
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/librustc_trans/attributes.rs:42:9: 42:39 help: run `rustc --explain E0425` to see a detailed explanation
src/librustc_trans/attributes.rs:50:9: 50:39 error: unresolved name `llvm::RemoveFunctionAttributes` [E0425]
src/librustc_trans/attributes.rs:50         llvm::RemoveFunctionAttributes(val, llvm::Attribute::NoUnwind);
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/librustc_trans/attributes.rs:50:9: 50:39 help: run `rustc --explain E0425` to see a detailed explanation
src/librustc_trans/attributes.rs:63:9: 63:39 error: unresolved name `llvm::RemoveFunctionAttributes` [E0425]
src/librustc_trans/attributes.rs:63         llvm::RemoveFunctionAttributes(val, llvm::Attribute::OptimizeForSize);
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/librustc_trans/attributes.rs:63:9: 63:39 help: run `rustc --explain E0425` to see a detailed explanation
src/librustc_trans/attributes.rs:73:9: 73:39 error: unresolved name `llvm::RemoveFunctionAttributes` [E0425]
src/librustc_trans/attributes.rs:73         llvm::RemoveFunctionAttributes(val, llvm::Attribute::Naked);
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/librustc_trans/attributes.rs:73:9: 73:39 help: run `rustc --explain E0425` to see a detailed explanation
error: aborting due to 5 previous errors
make: *** [arm-unknown-linux-gnueabihf/stage0/lib/rustlib/arm-unknown-linux-gnueabihf/lib/stamp.rustc_trans] Error 101
````

The reason I'm asking this (looks like a regular name resolution error), is the `cfg: disabling C++ optimization (CFG_DISABLE_OPTIMIZE_CXX)` option, which is not true in this case, as I was using an existing llvm build.

Source revision: `a09f386`

**Comment by Aatch** [comment]
I'm not sure what would cause this, but the most likely option is probably that your build is broken in some way. That function isn't conditionally compiled and the relevant file has the appropriate `use`s. There's also not been any relevant changes since that revision.

**Comment by sanxiyn** [comment]
It would be helpful to know what LLVM you are using, since it doesn't seem to be the default one.

**Comment by dotdash** [comment]
That function is in `RustWrapper.cpp`, i.e. it should be present regardless of the used LLVM version. Right now my best bet would be a problem in the Makefiles that caused that file not to be recompiled after an update.

**Comment by petevine** [comment]
Thanks, I must have broken something by trying to reuse an existing llvm build directory that I'd preserved.

It normally works for the same build type but this time it was changed to debug. The only other potential problem could be the `codegen-units` option - I'll try again without it.

**Comment by petevine** [comment]
Turned out I wasn't doing anything wrong but my local clone got corrupted somehow. It took ages to produce [this trace](https://github.com/rust-lang/rust/issues/32272#issuecomment-207549538) on ARM but it might help unravel the mystery of the `"Cannot promote non-promotable alloca!" assertion.
