### ISSUE TITLE
String::truncate() and Vec::truncate() are inconsistent if new_len > current length

### ISSUE THREAD

**Issue by Dr-Emann** [rust-lang/rust#32717]
[String::truncate](https://doc.rust-lang.org/collections/string/struct.String.html#method.truncate) specifies that it "panics if `new_len` > current length"
[Vec::truncate](https://doc.rust-lang.org/collections/vec/struct.Vec.html#method.truncate) specifies that "If `len` is greater than the vector's current length, this has no effect.

This seems very inconsistent. I would personally prefer Vec's semantics. I'm not sure if it's a breaking change to add/remove a _documented_ panic, and I fear it's not okay, but it feels very inconsistent.

**Comment by Aatch** [comment]
Looking at the source, I have a feeling the panic-on-greater-than isn't a deliberate decision. Since it simply asserts that the new length is a character boundary (and presumably "not in the string isn't a valid boundary"). I think adding a panic could be considered a breaking change, but removing one doesn't seem like it should be.

**Comment by Stebalien** [comment]
@Aatch getting rid of a panic is just as bad if not worse:

```rust
unsafe {
    s.truncate(10); // panics if s isn't long enough.
    s.as_mut_vec().as_mut_ptr() = b"1234567890";
}
```

This is obviously a stupid example but you get the point.

**Comment by brson** [comment]
Ignoring the panics seems an ok solution to me.

**Comment by alexcrichton** [comment]
This was discussed at libs triage and the decision was that this is indeed an inconsistency we'd like to fix and the window for fixing still seems open as the code this would break seems almost too niche to exist. I've [submitted a PR](https://github.com/rust-lang/rust/pull/32977) for this.
