### ISSUE TITLE
Bison grammar is outdated

### ISSUE THREAD

**Issue by pekabon** [rust-lang/rust#32723]
It looks like grammar (https://github.com/rust-lang/rust/tree/master/src/grammar) is outdated, for example '?' shortcut for try! is not supported.

**Comment by steveklabnik** [comment]
Well, one question is, should the grammar show nightly-only things. If so, it would not include `?`. That said, it's clearly not complete, if you look at all the `A-grammar` tags.

@nikomatsakis has been working on a larlpop grammar that would hopefully make this stuff easier...

**Comment by alexcrichton** [comment]
cc https://github.com/rust-lang/rust/issues/15880, a bot which is intended to run these tests

**Comment by Mark-Simulacrum** [comment]
I don't think we have a bison grammar in-tree anymore... @nikomatsakis @steveklabnik @alexcrichton Do you know of the current state of the in-tree grammar? Do we want to show nightly-only things in the grammar?

**Comment by alexcrichton** [comment]
Oh I have no idea what's up with the current in-tree grammar, I would expect it to be quite out of date at this point.

**Comment by steveklabnik** [comment]
Yeah, it's basically abandonware. Niko had some efforts to have a real one, but I assume anything we do have is horribly bit-rotted.

**Comment by Mark-Simulacrum** [comment]
Do we want to try and get some movement from the community on implementing a reference grammar? Is it something we're interested in maintaining? If not, we should probably go ahead and close out issues relevant to the reference grammar; if yes, arguably closing the issues in favor of a thread on internals would still be a good idea.

**Comment by steveklabnik** [comment]
> if yes, arguably closing the issues in favor of a thread on internals would still be a good idea.

I would go this route, but let's hear what @nikomatsakis has to say

**Comment by lukaramu** [comment]
Traige: There is ongoing work (as of about two weeks ago) on creating an up-to-date grammar in the reference (rust-lang-nursery/reference#84); generally, this issue seems to fall under that reference issue and #30942 more generally.

**Comment by steveklabnik** [comment]
Triage: there's a new grammar wg, and i don't even think the bison grammar still exists. closing as outdated.

**Comment by steveklabnik** [comment]
After posting that comment, I checked it out again and saw that it was still there, which led to https://github.com/rust-lang/rust/pull/55545
