### ISSUE TITLE
Incorrect Add trait in book

### ISSUE THREAD

**Issue by jyasskin** [rust-lang/rust#32720]
https://github.com/rust-lang/rust/blob/master/src/doc/book/operators-and-overloading.md defines `Point`'s  `Add` trait as:

```rust
impl Add for Point {
    type Output = Point;

    fn add(self, other: Point) -> Point {
        Point { x: self.x + other.x, y: self.y + other.y }
    }
}
```

and then gives the example of using it as:

```rust
    let p1 = Point { x: 1, y: 0 };
    let p2 = Point { x: 2, y: 3 };

    let p3 = p1 + p2;
```

This works, but it consumes both input points, contrary to the way most people expect `+` to work. that is, `let p4 = p1 + p2` fails to compile.

I'd suggest making `Point` copyable by additionally deriving `Clone` and `Copy`, but you could also show the `&`-based trait implementation.

I noticed this because of https://plus.google.com/+MattAustern/posts/eLJDWZFcd3J.

**Comment by Stebalien** [comment]
Alternatively, explain what the problem is here and suggest implementing `Copy` or `Add` on `&Point`.

**Comment by steveklabnik** [comment]
I am currently re-doing the book, and so I'm not making major changes myself. I agree that either of these implementations would be useful. If anyone wants to send a PR here, please do! But since I'm not going to, I'm going to give this a close.
