### ISSUE TITLE
Improve concurrency example so that it actually is a data race

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#32733]
See discussion on https://github.com/rust-lang/rust/pull/32538

https://github.com/rust-lang/rust/blob/master/src/doc/book/concurrency.md#safe-shared-mutable-state provides a program that could have a data race, but doesn't -- each thread accesses an independent array member.

We should use a program that does in fact have a data race; perhaps something that iterates over the same array twice or accesses random keys.

**Comment by apasel422** [comment]
This appears to have been fixed in #32815.
