### ISSUE TITLE
rustdoc should hide private members in a const definition

### ISSUE THREAD

**Issue by nodakai** [rust-lang/rust#32735]
- http://doc.rust-lang.org/nightly/std/time/constant.UNIX_EPOCH.html

> `pub const UNIX_EPOCH: SystemTime = SystemTime(time::UNIX_EPOCH)`

Here, `time::UNIX_EPOCH` refers to a constant in `libstd/sys/{unix,windows}/time.rs` (depending on the compile config) and should not be exposed. Its type is platform-specific, and private, too.

_Cf._ the `SystemTime` type is displayed as
- http://doc.rust-lang.org/nightly/std/time/struct.SystemTime.html

> `pub struct SystemTime(_);`

**Comment by ollie27** [comment]
Fixed by #53409. We don't show the values of consts anymore.
