### ISSUE TITLE
ICE: Error constructed but not emitted

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#32758]
```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "expected item, found `if`"', ../src/libcore/result.rs:746
```

Test case:

```
if expando.ptr.is_null() {
    println!("forall x. forall y. forall z. mult(x, mult(y, z)) = mult(mult(x, y), z) /\\
              forall x. mult(e(), x) = x /\\
              forall x. mult(x, x) = e()
              ==> forall x. forall y. mult(x, y) = mult(y, x)");
}
```

I suspect the problem is just having the code outside of a function, wrap it all in `fn main() {}` and the ICE goes away.

**Comment by LeoTestard** [comment]
I can't reproduce the bug neither with master, nor with a version from 5 days ago (so before this issue was reported). Has this been fixed already? What revision of rustc were you using?

**Comment by Mark-Simulacrum** [comment]
I can't reproduce either, so I'm going to close.
