### ISSUE TITLE
reference.html inconsistent on struct expressions

### ISSUE THREAD

**Issue by tromey** [rust-lang/rust#32769]
One part of the reference manual says that empty braces are allowed for struct expressions: https://doc.rust-lang.org/reference.html#structs

Another part says that the braces must contain one or more initializers: https://doc.rust-lang.org/reference.html#struct-expressions

`rustc` tells me that empty braces are an unstable extension, so one way to resolve the discrepancy would be to mention this in the manual, preferably at both spots.

**Comment by steveklabnik** [comment]
Yes, this is something that's changed, but the docs haven't.

**Comment by steveklabnik** [comment]
I would be happy to work with anyone who wants to work on this issue.

**Comment by abhijeetbhagat** [comment]
I can work on this. The latest compiler doesn't seem to give any kind of a warning related to empty braces - https://is.gd/h7oleb

**Comment by steveklabnik** [comment]
That'd be great! Since the time this issue was filed, braces are okay to use in stable. So these spots should be updated to reflect that.

**Comment by abhijeetbhagat** [comment]
I am not sure if this is the only file which requires the update.

**Comment by steveklabnik** [comment]
I don't believe so, or at least, not for this ticket. There's a lot of ways the reference can improve.

**Comment by apasel422** [comment]
@steveklabnik Was this fixed by #34742?

**Comment by achan1989** [comment]
@steveklabnik I believe this was fixed by pr #34742.  I see no inconsistencies in the book or reference.

**Comment by steveklabnik** [comment]
Closing! Thanks @apasel422 @achan1989
