### ISSUE TITLE
Macro-expanded procedural macros can be used even if they are unconfigured

### ISSUE THREAD

**Issue by jseyfried** [rust-lang/rust#32764]
For example, this compiles:
```rust
macro_rules! bar {
    {} => {
        #[cfg(foo)]
        macro_rules! baz { () => {} }
    }
}

bar! {}

fn main() { baz!(); }
```

If we replaced `bar! {}` with its expansion, `#[cfg(foo)] macro_rules! { baz { () => {} } }`, the example wouldn't compile.

**Comment by jseyfried** [comment]
I think we should fix this by removing unconfigured items after each macro expansion pass since we'll have to do this anyway to get accurate name resolution during macro expansion.

cc @nrc

**Comment by durka** [comment]
Same as #22250?

**Comment by jseyfried** [comment]
@durka yeah, closing in favor of #22250.
