### ISSUE TITLE
Docs: confusing description of `Primitive Types` 

### ISSUE THREAD

**Issue by tclfs** [rust-lang/rust#32762]
I'm a newcomer, and studying Rust. `The Rust Programming Language`[1], `The Rust Reference`[2], and `Rust by Example`[3] are my main resource. When I encountered the concept of `Primitive Types`, which is maybe the first concept to me, I was caught into trouble. All these referrences about this concept are lack of consistency.
[1] `primitives types` comprises "Booleans, char, Numeric types, Arrays, Slices, Tuples, Functions";
[2] 
   >The primitive types are the following:
   > - The boolean type bool with values true and false.
   > - The machine types (integer and floating-point).
   > - The machine-dependent integer types.

[3] add the `unit type ()` in comparison to [1].

In my understanding, the description in [2] may be pricise, all the other types are built-in types. I hope someone being good at this point can improve this contradiction.

**Comment by steveklabnik** [comment]
I recently edited this list, see nightly: http://doc.rust-lang.org/nightly/reference.html#primitive-types

I believe that this makes them consistent with each other. `unit` is a zero-length tuple, so it's already under the tuple types.

Does that help?

**Comment by tclfs** [comment]
Yeah, you solved my question. Thanks!
