### ISSUE TITLE
[MIR] Call Rvalue for function calls that don't need an unwind block

### ISSUE THREAD

**Issue by Aatch** [rust-lang/rust#32763]
Current a function call is represented by a terminator with one or two destinations for after the call. This is because LLVM's `invoke` instruction is a terminator. However, it isn't always the case that we need to use a `invoke`, either there's no cleanup to be done, so unwinding doesn't matter, or the function being called won't unwind. This result in having many blocks with unconditional jumps to the next block.

With this in mind, I wonder if having a Call rvalue would be useful. A good use case for it would be for intrinsic calls, as only a couple could possibly trigger unwinding. A MIR optimisation pass could also turn `Call` terminators into `Call` rvalues + a branch.

It's possible that it's not worth the extra complexity though.

**Comment by nagisa** [comment]
I’m not sure it is worth to introduce duplication in MIR representation just to get less blocks… And it doesn’t really work out well with calls which return by out-ptr.

**Comment by nikomatsakis** [comment]
I think we had decided previously against adding a call rvalue. I'd be inclined not to unless we have a strong case.

**Comment by nagisa** [comment]
> A good use case for it would be for intrinsic calls, as only a couple could possibly trigger unwinding.

This is the only thing that could benefit from this, and even then IMO desugaring intrinsics into straight MIR instructions would be better. Also the unwind block is optional already, and we must have the terminator version for unwind-less calls because of possibility of destination being by out-ptr.

Seems like a very small-gain & high-maintenance change.

**Comment by nagisa** [comment]
Since we are very likely to not go with the proposal, closing.
