### ISSUE TITLE
reference.html does not document tuple field expressions

### ISSUE THREAD

**Issue by tromey** [rust-lang/rust#32775]
I was reading reference.html (I'm using it as a guide for the gdb expression parser) and I couldn't find any reference to tuple field expressions.  These are expressions of the form "expr '.' N", where N is a decimal integer literal.

**Comment by steveklabnik** [comment]
It's there!  http://doc.rust-lang.org/reference.html#tuple-types

> Because tuple elements don't have a name, they can only be accessed by pattern-matching or by using N directly as a field to access the Nth element.
