### ISSUE TITLE
reference lexer and grammar incorrectly handle tuple field expressions

### ISSUE THREAD

**Issue by tromey** [rust-lang/rust#32776]
The reference grammar in `rust/src/grammar/lexer.l` returns `LIT_INTEGER` for any sort of integer, including hex, octal, etc.

Then `parser-lalr.y` implements tuple field expressions as:

```
| expr '.' LIT_INTEGER                                { $$ = mk_node("ExprTupleIndex", 1, $1); }
```

However, rustc rejects hexadecimal here:

```
b7.rs:4:31: 4:34 error: invalid tuple or tuple struct index
b7.rs:4     println!("{}, {}", x.0, x.0x1);
```

My guess is that the reference lexer is incorrect here.

**Comment by tromey** [comment]
rustc also seems to reject decimal literals including underscores, so "x.1_" is invalid.

**Comment by alexcrichton** [comment]
cc https://github.com/rust-lang/rust/issues/15880

**Comment by steveklabnik** [comment]
Triage: all of this is vestigial at this point, and the grammar WG is handling these kinds of issues. Closing.
