### ISSUE TITLE
`rustup toolchain list` should indicate the default toolchain

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#32784]
[Source](https://internals.rust-lang.org/t/beta-testing-rustup-rs/3316/64?u=brson).

> "rustup toolchain list" doesn't indicate the default toolchain.

Good point. It could be like `rustup target list` which uses parens to indicate the status. The list could say `(default)` next to the default toolchain and `(override)` or `(active)` next to an active override.

**Comment by alexcrichton** [comment]
@brson wrong repo perhaps?
