### ISSUE TITLE
getrandom_fill_bytes panics on Linux-on-Windows

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#32788]
Panics [here](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/rand.rs#L67) with an `unexpected getrandom error: 22`. Unfortunately, the current insider preview build is a bit unstable so I rolled back before being able to investigate further.

Not sure if this is a Windows bug or a Rust bug.

Tagging both A-windows and A-linux I guess?

**Comment by brson** [comment]
Neat! Can we just hack around it and fall back to `/dev`?

**Comment by sfackler** [comment]
Possibly. I'm setting up a VM right now to try to poke around more.

It could very well just be a bug in the Windows syscall interface.

**Comment by alexcrichton** [comment]
Error 22 corresponds to EINVAL, so maybe just something like an unimplemented syscall? We should probably fall back to the non-getrandom interface if it errors out.

**Comment by sfackler** [comment]
We can probably work around it by adding `EINVAL` to the check here: https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/rand.rs#L106, but it still seems like there's something wrong on the Windows side - it seems like it should be returning `ENOSYS` there.

**Comment by tbu-** [comment]
https://lkml.org/lkml/2015/10/25/123 says that callers only need to check for `ENOSYS` (or `EINTR` if the buffer size is larger than 256). This is probably a bug in Linux-on-Windows right now.

**Comment by sfackler** [comment]
I believe this has been resolved in later preview builds.
