### ISSUE TITLE
ICE: thread 'rustc' panicked at 'RefCell<T> already borrowed', ../src/libcore/cell.rs:444

### ISSUE THREAD

**Issue by Evrey** [rust-lang/rust#32797]
Travis-CI build failed, my local builds with a slightly older rustc nightly works just fine. This is the repository in question and the Travis-CI build log:

- Repo: https://github.com/Evrey/GBArs/tree/c48726c4b92913fdb3937770d26dedaeb57684a7
- Travis-CI Log: https://gist.github.com/Evrey/cdcf7f20bfefd1769faf6a39512503b1

rustc only seems to fail when compiling my `gbars` crate:

>    Compiling gbars v0.3.1 (file:///home/travis/build/Evrey/GBArs)
>     Running `rustc src/main.rs --crate-name gbars --crate-type bin -g --cfg feature=\"default\" --out-dir /home/travis/build/Evrey/GBArs/target/debug --emit=dep-info,link -L dependency=/home/travis/build/Evrey/GBArs/target/debug -L dependency=/home/travis/build/Evrey/GBArs/target/debug/deps --extern term=/home/travis/build/Evrey/GBArs/target/debug/deps/libterm-585dc449d37783e7.rlib --extern byteorder=/home/travis/build/Evrey/GBArs/target/debug/deps/libbyteorder-79579e11a5fc0173.rlib --extern log=/home/travis/build/Evrey/GBArs/target/debug/deps/liblog-342ffb7444a9471d.rlib --extern argparse=/home/travis/build/Evrey/GBArs/target/debug/deps/libargparse-b299699413f65723.rlib`
> error: internal compiler error: unexpected panic

Could be related to #18711, a way older and closed issue. (rustc 0.13.0-dev)

### Travis-CI (ICE)
    $ rustc --version
    rustc 1.9.0-nightly (bf5da36f1 2016-04-06)
    $ cargo --version
    cargo 0.10.0-nightly (f20ca62 2016-04-06)

Backtrace:

       1:     0x7f8cb4c54400 - std::sys::backtrace::tracing::imp::write::h714760a4c8c0cdd8
       2:     0x7f8cb4c61acb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hff309ab1d83ffd90
       3:     0x7f8cb4c6166b - std::panicking::default_hook::h08ad3bb09872855b
       4:     0x7f8cb4c253ef - std::sys_common::unwind::begin_unwind_inner::h406d5f1a330b854b
       5:     0x7f8cb4c274d8 - std::sys_common::unwind::begin_unwind_fmt::h57ea3fbee1a40196
       6:     0x7f8cb4c51af1 - rust_begin_unwind
       7:     0x7f8cb4cab53f - core::panicking::panic_fmt::ha6b3c19493c123b3
       8:     0x7f8cb4cac038 - core::panicking::panic::h188c6c6a0fe5463c
       9:     0x7f8cb39fbfbe - rustc_resolve::resolve_imports::_<impl ModuleS<'a>>::try_define_child::hfd59dfd790ce27ba
      10:     0x7f8cb3a042d3 - rustc_resolve::resolve_imports::_<impl ModuleS<'a>>::define_in_glob_importers::h7043f8c562791a18
      11:     0x7f8cb39fbf62 - rustc_resolve::resolve_imports::_<impl ModuleS<'a>>::try_define_child::hfd59dfd790ce27ba
      12:     0x7f8cb3a042d3 - rustc_resolve::resolve_imports::_<impl ModuleS<'a>>::define_in_glob_importers::h7043f8c562791a18
      13:     0x7f8cb39fbf62 - rustc_resolve::resolve_imports::_<impl ModuleS<'a>>::try_define_child::hfd59dfd790ce27ba
      14:     0x7f8cb3a06674 - rustc_resolve::resolve_imports::ImportResolver::resolve_imports_in_current_module::hcd653de830737026
      15:     0x7f8cb3a043a7 - rustc_resolve::resolve_imports::ImportResolver::resolve_imports_for_module_subtree::hdf6b441d9816f5a2
      16:     0x7f8cb3a0442e - rustc_resolve::resolve_imports::ImportResolver::resolve_imports_for_module_subtree::hdf6b441d9816f5a2
      17:     0x7f8cb3a0442e - rustc_resolve::resolve_imports::ImportResolver::resolve_imports_for_module_subtree::hdf6b441d9816f5a2
      18:     0x7f8cb3a0442e - rustc_resolve::resolve_imports::ImportResolver::resolve_imports_for_module_subtree::hdf6b441d9816f5a2
      19:     0x7f8cb3a0442e - rustc_resolve::resolve_imports::ImportResolver::resolve_imports_for_module_subtree::hdf6b441d9816f5a2
      20:     0x7f8cb39f872e - rustc_resolve::resolve_crate::h6e88006253f832e0
      21:     0x7f8cb519d322 - rustc_driver::driver::phase_3_run_analysis_passes::h035bf2dff707c080
      22:     0x7f8cb517213f - rustc_driver::driver::compile_input::h650fe5b01cb8d74d
      23:     0x7f8cb5157f04 - rustc_driver::run_compiler::h68d23e0e9b7b247d
      24:     0x7f8cb5155371 - std::sys_common::unwind::try::try_fn::h67fde221a73148bc
      25:     0x7f8cb4c51a7b - __rust_try
      26:     0x7f8cb4c51a0d - std::sys_common::unwind::inner_try::h4e97625a08807651
      27:     0x7f8cb5155bba - _<F as std..boxed..FnBox<A>>::call_box::hc8936fa120642c49
      28:     0x7f8cb4c5fc54 - std::sys::thread::Thread::new::thread_start::h74af400293164137
      29:     0x7f8cacd8fe99 - start_thread
      30:     0x7f8cb48ac38c - <unknown>

### Local compiler 1 (works)
    C:\???>rustc --version --verbose
    rustc 1.9.0-nightly (02310fd31 2016-03-19)
    binary: rustc
    commit-hash: 02310fd313cf3eed11fe5ac11921b73cc3b648d4
    commit-date: 2016-03-19
    host: x86_64-pc-windows-gnu
    release: 1.9.0-nightly
    
    C:\???>cargo --version --verbose
    cargo 0.10.0-nightly (132b82d 2016-03-19)

### Local compiler 2 (works)
    E:\???>rustc --version --verbose
    rustc 1.9.0-nightly (02310fd31 2016-03-19)
    binary: rustc
    commit-hash: 02310fd313cf3eed11fe5ac11921b73cc3b648d4
    commit-date: 2016-03-19
    host: i686-pc-windows-gnu
    release: 1.9.0-nightly
    
    E:\???>cargo --version --verbose
    cargo 0.10.0-nightly (132b82d 2016-03-19)

**Comment by arielb1** [comment]
cc @jseyfried

**Comment by plumenator** [comment]
Related: arcnmx/cargo-clippy/issues/19
