### ISSUE TITLE
is `#[cfg]` applicable to *some* non-stmt expressions?

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#32796]
Consider the following:

http://is.gd/28Q5H5

``` rust
#![feature(stmt_expr_attributes)]

fn foo(_x: &[u32]) { }

fn main() {
    foo(&[1, #[cfg(not(now))] 2, 3])
}
```

Currently this is accepted (see https://github.com/rust-lang/rust/pull/29850) but RFC 16 as written does not clearly say whether this is acceptable or not (see https://github.com/rust-lang/rfcs/blob/master/text/0016-more-attributes.md#cfg )

**Comment by pnkfelix** [comment]
cc @Kimundi

**Comment by pnkfelix** [comment]
Lang team discussed this.

Opinions were mixed about whether this should be allowed or not.

But the more fundamental conclusion is that the decision here should go through the RFC process (just as an amendment to RFC 16), rather than just having the lang team make a unilateral decision; we want to get input from the community about what is best here.

Note: It would be good to keep in mind that some use cases, such as function calls of the form
```rust
bar(1, #[cfg(no)] 2, 3)
```
 are at the very least difficult to try to use, because one cannot write
```rust
fn bar(a: u32, #[cfg(no)] b: u32, c: u32) { ... }
```

**Comment by tbu-** [comment]
I'm against such fine-grained `cfg` attributes. I think it'll produce unreadable code, similar to many `#ifdef`s inside the same term.

```
if(
#ifdef A
a
#endif
#if defined(A) && defined(B)
&&
#endif
#if defined(B)
b
#endif
#if defined(A) || defined(B)
&&
#endif
c)
{}
```

Compare that to

```
#[cfg(A)]      fn a() -> bool { a }
#[cfg(not(A))] fn a() -> bool { true }

#[cfg(B)]      fn b() -> bool { b }
#[cfg(not(B))] fn b() -> bool { true }

if a() && b() && c {
}
```

**Comment by pnkfelix** [comment]
cc #15701 ... this is effectively an unresolved question that needs to be added to that tracking issue before we stabilize this feature.

**Comment by Kimundi** [comment]
So, one of the motivating examples that lead to me implementing RFC #16 was the use case of a huge struct with many `#[cfg]`-guarded fields, and the desire to be able to write a constructor function for it without having combinatorial explosion of the possible variations.

While what I implemented did not fully reach that state due to things like struct constructors like `Foo { #[cfg] a: 5 }` or as you said function argument lists not accepting attributes, it does allow for this:

```rust
#![feature(stmt_expr_attributes)]

struct Foo(
    u8,
    #[cfg(foo)] u16
);

fn main() {
    let x = Foo(1, #[cfg(foo)] 2);
}
```

**Comment by tbu-** [comment]
That should be possible today, if I understand it correctly:

```
let x;
#[cfg(windows)]
{ x = 5; }
#[cfg(unix)]
{ x = 3; }
```

or even

```
#[cfg(windows)]
let x = 3;
#[cfg(unix)]
let x = 5;
```

**Comment by bluss** [comment]
@tbu- That needs the same feature (`stmt_expr_attributes`) to compile

**Comment by plietar** [comment]
There's a usecase for `#[cfg]` on expressions I find useful :

```rust
let backends = [
    #[cfg(feature = "foo-backend")] foo_backend,
    #[cfg(feature = "bar-backend")] bar_backend,
];
```

allowing multiple backends to be enabled at compile time using cargo features, and choosing one at runtime.
The alternative is to list all 2^N combinations, or use some macro magic to generate them ([I've had to resort to this in order to stay on stable](https://github.com/plietar/librespot/blob/c76b7b4/src/audio_backend/mod.rs)).

I guess you could consider this as a `#[cfg]` on a list element rather than an expression.

I'm more skeptical about other uses of it, especially on function calls.
`if cfg!(...) { 3 } else { 5 }` can be used for simpler cases (I assume this gets optimized out at compile time)

**Comment by brson** [comment]
This looks like the only thing blocking `stmt_expr_attributes` from stabilizing.

**Comment by brson** [comment]
Perhaps we can turn this behavior off and move forward with `stmt_expr_attributes` stabilization @rust-lang/libs?

**Comment by Kimundi** [comment]
Turn off in the sense of removal, or in the sense of adding a feature for it specifically?

**Comment by nrc** [comment]
I'm in favour of stabilising statement attributes and leaving expression ones under the existing feature flag (probably the easiest solution for users and the compiler, I'd also be happy with a new feature flag or removing expression attributes entirely, but either option seems less friendly).

**Comment by Mark-Simulacrum** [comment]
So I'm not really clear what this issue is addressing. I think it's about attributes working on some expression and not others... but I don't see representative examples. Could someone summarize the current situation (@nrc?)?

**Comment by durka** [comment]
Right now `[1, #[cfg(unix)] 2, 3]` is accepted on stable with no feature flag, so I'm not sure there is anything left to talk about here.

**Comment by nikomatsakis** [comment]
It's so clearly useful... I think I'd be against trying to remove it. But I'd like to know the current status too.

**Comment by pnkfelix** [comment]
yes it appears that #36995 may have (accidentally?) stabilized it for list elements, which was the main case this issue was discussing... at this point I'm not sure we can afford to remove it...

**Comment by pnkfelix** [comment]
So, as noted above, it appears that

```rust
fn foo(_x: &[u32]) { }

fn main() {
    foo(&[1, #[cfg(not(now))] 2, 3])
}
```

is now accepted on stable.

So regardless of whatever resoluton I was hoping to reach via discussion, it appears the matter has been resolved independently of the discussion here.

(Note to self: Maybe in the future when I discover oddities like this, I should immediately add compile-fail tests that are lacking the feature flag to ensure they don't get accidentally stabilized. At least, my interpretation of @nrc's stated position leads me to think that they did not intend to stabilize this aspect of attributes.)
