### ISSUE TITLE
Appending to a file has no effect, in stable

### ISSUE THREAD

**Issue by ProgVal** [rust-lang/rust#32801]
```rust
use std::io::Read;
use std::io::Write;
use std::fs::{File, OpenOptions};

fn main() {
    let mut f = File::create("foo.txt").unwrap();
    f.write("bar".as_bytes()).unwrap();
    let mut f = OpenOptions::new().append(true).open("foo.txt").unwrap();
    let _ = f.write_all("baz".as_bytes());
    f.flush().unwrap();
    
    let mut f = File::open("foo.txt").unwrap();
    let mut content = String::new();
    f.read_to_string(&mut content).unwrap();
    println!("{}", content);
}
```

[Beta and nightly's behavior](https://play.rust-lang.org/?gist=2a9c627a95b45c1fff8ddc03b367a0cc&version=beta&backtrace=0): prints `barbaz`
[Stable's behavior](https://play.rust-lang.org/?gist=2a9c627a95b45c1fff8ddc03b367a0cc&version=stable&backtrace=0): prints `bar`

**Comment by sfackler** [comment]
If you change line 9 to not ignore errors, you'll see that it fails on stable. In stable you'd have to manually specify `OpenOptions::new().write(true)..` or the file is opened read-only. I believe some of the changes to the semantics of `OpenOptions` now make append imply write.

**Comment by alexcrichton** [comment]
I believe this is an instance of [RFC 1252](https://github.com/rust-lang/rfcs/blob/master/text/1252-open-options.md) and sounds like it should be "fixed" soon! Closing as working for now (as it's a fixed bug), but thanks for the report!

**Comment by ProgVal** [comment]
Ok

@sfackler: By the way, your solution worked. Thanks
