### ISSUE TITLE
rustbuild: allow using ninja to build LLVM

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#32809]
Ninja is much faster at building LLVM, especially when more cores get involved. We should either:

1. Autodetect presence of ninja and use it automatically (with an option to force use of make); or
2. Allow using ninja (via some option).

**Comment by alexcrichton** [comment]
If anyone wants to dive into rustbuild, this should be a pretty easy bug to tackle! (in theory).

You'd probably want to start out by [adding a check to `sanity.rs`](https://github.com/rust-lang/rust/blob/master/src/bootstrap/build/sanity.rs) to just see if `ninja` exists and then when we [later build LLVM](https://github.com/rust-lang/rust/blob/7979dd6089ee5cba39cfbe6e880a3edeb7fff788/src/bootstrap/build/native.rs#L21) you should just be able to pass the argument to CMake!

We already just call `cmake --build` so I think that takes care of running ninja when it's configured, so we just need to tell CMake to use ninja.

**Comment by caipre** [comment]
I'll take this.
