### ISSUE TITLE
Should impls of method not show up (or show implementors) in rustdoc search?

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#32808]
[Enum search](http://doc.rust-lang.org/nightly/std/?search=enum) on rustdoc-generated documentation for the standard library has a lot of seemingly equivalent search results:

```
…
std::array::eq
std::slice::eq 
std::array::eq
std::slice::eq 
std::array::eq
std::slice::eq
… 
```

These are implementation of the same method for many different types (mostly arrays).

Perhaps we should either not show them or somehow display for which implementor the method is?

**Comment by mitaa** [comment]
Note also that i.e. all `std::array::eq` entries link to the exact same impl method.

**Comment by steveklabnik** [comment]
Triage: this does not seem to reproduce today, closing!
