### ISSUE TITLE
No way to make TcpStream::connect non-blocking

### ISSUE THREAD

**Issue by osa1** [rust-lang/rust#32821]
`TcpStream` API doesn't allow making `connect()` non-blocking, because `connect()` is the only way to create a `TcpStream`, and `set_nonblocking()` is a `TcpStream` method.

http://doc.rust-lang.org/nightly/std/net/struct.TcpStream.html#method.set_nonblocking

**Comment by sfackler** [comment]
The `net2` crate provides the functionality to do this, but the API's not super great right now: https://doc.rust-lang.org/net2-rs/net2/struct.TcpBuilder.html#method.to_tcp_stream and https://doc.rust-lang.org/net2-rs/net2/trait.TcpStreamExt.html#tymethod.connect

**Comment by alexcrichton** [comment]
Yes the standard library does not support this but the `net2` crate (as @sfackler mentioned) is intended for this kind of functionality. Closing as this is intended currently until `net2` is merged back into std.
