### ISSUE TITLE
Implement `From<Vec<T>>` and `Into<Vec<T>>` for `VecDeque<T>`

### ISSUE THREAD

**Issue by apasel422** [rust-lang/rust#32848]
This can be done without allocating or going through an iterator.

**Comment by davidhewitt** [comment]
Hi, I've just had a go at implementing this (my first contribution to Rust!). It's in my fork https://github.com/davidhewitt/rust/commit/4a2198364ec365b9d6ad505c92b78f33a24de1b1

Does this patch look like what you were looking for? If so, I'll open a pull request. Is there anything I should know about opening PRs for Rust (what to name them, do I need to put in a specially formatted description for a bot to parse etc.)?

**Comment by apasel422** [comment]
@davidhewitt Nice! That is what I was looking for. If you open a PR, I'll leave comments there. The PR title can be the same as your commit message, and the body can contain "Closes #32848" so that this issue can be closed automatically once the PR is merged.

**Comment by davidhewitt** [comment]
Thanks - #32866!
