### ISSUE TITLE
Warn on casting out-of-range char literal to u8

### ISSUE THREAD

**Issue by mbrubeck** [rust-lang/rust#32843]
`0x100 as u8` gives a "literal out of range for u8" warning, but `'\u{100}' as u8` compiles without any warning.  (Both expressions evaluate to `0u8`.)

**Comment by oli-obk** [comment]
that's because the first is not a cast, since `0x100` is inferred to be `u8` and then casted to `u8`. The second one is a `char` which is casted to `u8`.

**Comment by mbrubeck** [comment]
Ah, right. And `0x100_i32 as u8` does not warn either. I think I'll just close this as invalid.
