### ISSUE TITLE
Custom rc: compiler requires generic argument to be sized

### ISSUE THREAD

**Issue by VFLashM** [rust-lang/rust#32863]
I'm trying to implement custom rc class and hit a problem with dst.

Please see example below (tested on rust nightly).
Compiler requires generic argument to be sized, even though it's not really necessary.
`CustomRc<Trait>` is sized and `Bad` should not care whether or not `Trait` is sized.

What's even more puzzling is that standard `Rc` works fine. It makes me think I missed something, but I spent a lot of time on it and couldn't find a reason. It would be great if error mentioned which part of code required the missing trait constraint.

``` rust
use std::rc::Rc;
use std::marker::Unsize;
use std::ops::CoerceUnsized;

struct CustomRc<T: ?Sized>(Rc<T>);
impl<U: ?Sized, T: Unsize<U>> CoerceUnsized<CustomRc<U>> for CustomRc<T> {}

struct Struct;
trait Trait {}
impl Trait for Struct {}

struct Good(Rc<Trait>);
struct Bad(CustomRc<Trait>);

fn main() {
    {
        let s: Rc<Struct> = Rc::new(Struct);
        let t: Rc<Trait> = s;
        let good = Good(t); // as expected, works fine
    }
    {
        let s: CustomRc<Struct> = CustomRc(Rc::new(Struct));
        let t: CustomRc<Trait> = s;
        let bad = Bad(t); // error: the trait bound `Trait: std::marker::Sized` is not satisfied
    }
}   
```

**Comment by Aatch** [comment]
The fix is that in your `CoerceUnsized` impl, `T` needs to have the `?Sized` bound, this is because Rust is attempting to "coerce" from `CustomRc<Trait>` to `CustomRc<Trait>` and failing becaue there's no matching `CoerceUnsized` impl for this.

I think this case could probably be handled better, detecting "no-op" coercions like this and at least producing a different error.

**Comment by VFLashM** [comment]
Got it. Thank you!

It's quite surprising to see rust trying to coerce things here, though. Unsizing unsized type does not make much sense to me. It would make sense if rust supported upcasting, but that's another story.
As you mentioned, it would be great if it was handled automatically.

Feel free to close this ticket, though. I can make a new ticket with short description if necessary.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this. I don't see anything in particular that's actionable in this issue, though I could be missing something.
