### ISSUE TITLE
Trait object inherent methods do not show in docs anymore

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#32881]
The docs for [std::any::Any](http://doc.rust-lang.org/nightly/std/any/trait.Any.html) don't show the methods on the trait object type `Any` anymore. (They show in stable).

For example: Method `downcast_ref()` does not show up.

**Comment by mitaa** [comment]
The methods are shown for [`core::any::Any`](http://doc.rust-lang.org/nightly/core/any/trait.Any.html).

**Comment by bluss** [comment]
Aha, another doc inclusion bug
