### ISSUE TITLE
rustbuild: rustc's -Crpath does not work

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#32886]
The way the compiler emits rpath directives is relative to the output directory structure, but with rustbuild we output in one structure and then copy over into another. This means that `-Crpath` basically doesn't work, and things like `LD_LIBRARY_PATH` need to be specified manually.

This is a pretty tricky bug to fix as it will involve something like:

* Glorious hacks in the `src/bootstrap/rustc.rs` script to manually pass rpath directives
* Modifying the `-C rpath` argument to take some sort of value indicating what should be passed to the linker, this is an API change to the compiler, however.
* Use some sort of tool to modify this metadata in the executable after it's generated

I'm somewhat leaning towards the "glorious hacks" method for now to get something working and avoid changing the compiler, but there are other reasons why we would want to modify the `-C rpath` argument to the compiler as well perhaps.

**Comment by nagisa** [comment]
Why relative rpaths are not enough? The libraries can still be found at `../lib/*` relative to the binary.

**Comment by alexcrichton** [comment]
The problem is that we generate relative rpaths with the expectation that the directory structure at compile time is the same as that at runtime. With the makefiles we do that but with rustbuild we just take whatever Cargo outputs and massage it into the directory structure we later ship.

For example:

```
$ readelf -d ./build/x86_64-unknown-linux-gnu/stage1/bin/rustc | grep RUNPATH
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/deps:$ORIGIN/../../../stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib:/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib]
```

When compared to a normal build:

```
$ readelf -d ./x86_64-unknown-linux-gnu/stage1/bin/rustc | grep RUNPATH
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../lib:/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib]
```

Namely, the compiler relies on `$ORIGIN/../lib` to be in rpath on Linux, but it's not there (we'd have to specify that manually)

**Comment by brson** [comment]
Maybe a new -Z flag?

Hacks also fine.
