### ISSUE TITLE
ICEs are hiding information somewhere

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#32888]
Working on the compiler recently I generated this ICE

```
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'Box<Any>', src/libcore/option.rs:700
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I tracked it down to what I believe is [this `expect` call](https://github.com/rust-lang/rust/blob/b622c3e0856767d8e53cf141e2e0a7b6d72a198b/src/librustc/middle/lang_items.rs#L192-L193), but nowhere do I see the error message at that `expect` call,s o it looks like something about our ICE handle is *hiding information*.

Should probably get fixed?

**Comment by eddyb** [comment]
Is it really a `rustc` bug? This looks like panicking with a non-string *from `libcore`*:
```
thread 'rustc' panicked at 'Box<Any>', src/libcore/option.rs:700
```

**Comment by alexcrichton** [comment]
I have a feeling we'd have gotten a lot more bug reports if libcore itself were not panicking with string literals: https://github.com/rust-lang/rust/blob/b622c3e0856767d8e53cf141e2e0a7b6d72a198b/src/libcore/option.rs#L696-L701

The compiler panics with a token indicating that it was an ICE/bug, so I think that's where the `Box<Any>` is coming from.

**Comment by alexcrichton** [comment]
I think I need to become more trusting, this is due to local changes.
