### ISSUE TITLE
Consider moving some docs from alloc::arc to alloc::arc::Arc

### ISSUE THREAD

**Issue by Ms2ger** [rust-lang/rust#32905]
http://static.rust-lang.org/doc/master/alloc/arc/index.html has some useful docs, which are somewhat hard to find. In particular, someone on IRC misconstrued the more terse documentation on the `Arc` type itself to mean that it magically allowed mutable access.

CC @steveklabnik

**Comment by steveklabnik** [comment]
part of https://github.com/rust-lang/rust/issues/29377

**Comment by steveklabnik** [comment]
I would be happy to work with anyone who wants to work on this issue.

**Comment by izgzhen** [comment]
@steveklabnik Can I work on this one?

@Ms2ger Do you mean the lack of more information regarding `get_mut` and `make_mut`?

**Comment by Ms2ger** [comment]
I think everything on the module page would be more discoverable on the type page; the module page could then be limited to its first line and a link to the type page.

**Comment by steveklabnik** [comment]
@izgzhen sure thing!

In general, the module page should provide an overview of the module. And each type's page should provide an in-depth view of the type.

This module is very tiny, only encompassing `Arc` and `Weak`, and so it should be relatively small.

**Comment by JustAPerson** [comment]
Looks like this can be closed?

**Comment by steveklabnik** [comment]
Yes, thanks!
