### ISSUE TITLE
Cannot parse IPv6 addresses with zone indices

### ISSUE THREAD

**Issue by achanda** [rust-lang/rust#32904]
Here is what I see http://is.gd/SAqJsw
These addresses are described in https://en.wikipedia.org/wiki/IPv6_address#Link-local_addresses_and_zone_indices

**Comment by dtolnay** [comment]
I believe this is going to need an [RFC](https://github.com/rust-lang/rfcs/blob/master/libs_changes.md). Let's continue to track this in https://github.com/rust-lang/rfcs/issues/1992. Thanks!
