### ISSUE TITLE
building native libraries fails when CC/CXX contains spaces, eg for ccache

### ISSUE THREAD

**Issue by sourcefrog** [rust-lang/rust#32914]
with `CC='ccache gcc'`, building for example brotli-sys fails like this:

```
cargo:rustc-link-lib=static=brotli-dec
cargo:rustc-link-search=native=/home/mbp/src/conserve/target/debug/build/brotli-sys-c29cf30a86d86a13/out
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
PROFILE = Some("debug")
TARGET = Some("x86_64-unknown-linux-gnu")
debug=true opt-level=0
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = Some("ccache c++")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
running: "ccache c++" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-fPIC" "-I" "brotli/enc" "-I" "src" "-o" "/home/
mbp/src/conserve/target/debug/build/brotli-sys-c29cf30a86d86a13/out/src/brotli_capi.o" "-c" "src/brotli_capi.cc"

failed to execute command: No such file or directory (os error 2)
Is `ccache c++` not installed?
```

I think it should split the variable into words before executing, as other tools do.  Or, possibly do some more sophisticated shell-like interpretation.

**Comment by TimNN** [comment]
I believe that this is an issue with the [`gcc-rs` crate](https://github.com/alexcrichton/gcc-rs) which is used by brotli-sys to build the native library.

**Comment by alexcrichton** [comment]
Indeed! As @TimNN this is more relevant for the `gcc-rs` crate, so I'm going to close this here for now. As also mentioned this is currently intentional behavior, but this is so common it seems like this should just be fixed!

**Comment by sourcefrog** [comment]
Thanks @TimNN, I see it is documented.  But the currently documented behavior is different from most other build tools.

@alexcrichton are you saying I should file in gcc-rs?

**Comment by alexcrichton** [comment]
@sourcefrog indeed!
