### ISSUE TITLE
rustc does not allow being run via a symlink

### ISSUE THREAD

**Issue by rkitover** [rust-lang/rust#32917]
To add to #32916, if you install rust with e.g. GNU stow, then /usr/local/bin/rust is a symlink to e.g. /usr/local/stow/rust-git/bin/rustc, but if you do that you get errors like this compiling anything:

```
error: can't find crate for `std` [E0463]
```

Setting:

``` bash
export RUSTC=/usr/local/stow/rust-git/bin/rustc
```

fixes the problem for cargo at least.

**Comment by alexcrichton** [comment]
Is `/usr/local/lib/rustlib` linked into place as well, or is just the `rustc` binary linked into place? Currently the compiler finds the standard library essentially via a relative path from the executable, which I'm not sure in this case whether it'll be the destination of the symlink or the symlink itself, but I'd suspect the symlink itself

**Comment by rkitover** [comment]
Yup, the way stow works is it links everything into place in prefix as necessary, as files when the dir exists, and as links to dirs when they don't, so I have:

```
/usr/local/lib/rustlib -> ../stow/rust-git/lib/rustlib
```

**Comment by alexcrichton** [comment]
Hm could you try running with `RUST_LOG=rustc_metadata` and gist the output? That may have something which points to a culprit

**Comment by rkitover** [comment]
Had to rebuild rust with `--enable-debug-assertions --enable-llvm-assertions` as '#rust' told me to.

Running gmake for cargo git I get:

https://gist.github.com/rkitover/2a8550d6021b0aca9af03b4917d746f2

**Comment by alexcrichton** [comment]
Hm unfortunately those logs don't look too useful :(. Ah well, can perhaps try to reproduce some time in the future

**Comment by rkitover** [comment]
If you want to reproduce this, first, install GNU stow, it's in pretty much all package managers, then, from your rust checkout:

```bash
sudo mkdir -p /usr/local/stow/rust-git
mkdir inst
make install DESTDIR="`pwd`/inst"
sudo cp -r ./inst/usr/local/* /usr/local/stow/rust-git
(cd /usr/local/stow; sudo stow rust-git)
```

When you want to remove the symlinks from /usr/local:

```bash
(cd /usr/local/stow; sudo stow -D rust-git)
```

**Comment by petevine** [comment]
Setting `LD_LIBRARY_PATH` to where you moved the `lib` directory doesn't help?

**Comment by rkitover** [comment]
I tried this:

```bash
export LD_LIBRARY_PATH=/usr/local/stow/rust-git/lib/rustlib/x86_64-unknown-openbsd/lib/
```

Did not help, this is the only thing that works with cargo:

```bash
export RUSTC=/usr/local/stow/rust-git/bin/rustc
```

**Comment by petevine** [comment]
Yeah, sorry, that should pointed to just `rust-git/lib`

-original message-
Subject: Re: [rust-lang/rust] rustc does not allow being run via a symlink (#32917)
From: Rafael Kitover <notifications@github.com>
Date: 16.04.2016 23:03

I tried this:

```bash
export LD_LIBRARY_PATH=/usr/local/stow/rust-git/lib/rustlib/x86_64-unknown-openbsd/lib/
```

Did not help, this is the only thing that works with cargo:

```bash
export RUSTC=/usr/local/stow/rust-git/bin/rustc
```


---

**Comment by rkitover** [comment]
Nope that doesn't work either.

**Comment by petevine** [comment]
Is the `std` crate separate from the rest of rustlibs? Cause frankly, otherwise it should've worked 100%.

**Comment by rkitover** [comment]
No this is a standard install made using the script I posted above.

**Comment by petevine** [comment]
Could you post a `strace` of the working scenario? Doing a `strace rustc -vV` should be enough.

**Comment by petevine** [comment]
Or rather from a `hello world` compilation.

**Comment by rkitover** [comment]
This is the ktrace of running rustc on a hello world source via the symlink:

```
✔  ~/src
rkitover@openbsd-vm  ➤  ktrace rustc hello.rs
error: can't find crate for `std` [E0463]
error: aborting due to previous error
```

And this is the ktrace log:
https://gist.github.com/rkitover/0026dbd55bfb45cf745f824e4478ea8c

And here is the log for running rustc via actual path:
```
✔  ~/src
rkitover@openbsd-vm  ➤  /usr/local/stow/rust-git/bin/rustc hello.rs
✔  ~/src
rkitover@openbsd-vm  ➤  ./hello
Hello World!
```

And here is the ktrace log:
https://gist.github.com/86a4910a79862c6625b5ecb86cd12610

**Comment by petevine** [comment]
It's only searching in `/usr/local/lib/rustlib/x86_64-unknown-openbsd/lib` whereas it should be looking in `/usr/local/stow/rust-git/lib/rustlib/x86_64-unknown-openbsd/lib` as shown by the working trace.

Adding `/usr/local/stow/rust-git/lib` to your `LD_LIBRARY_PATH`  and maybe running `ldconfig` for good measure should have been enough but it isn't seemingly.

Rust solibs, however,  are being found in `/usr/local/stow/rust-git/lib/` so it seems to work partially.
How do you explain `/home/rkitover/lib/rustlib/x86_64-unknown-openbsd/lib` is being considered in the broken case?

**Comment by rkitover** [comment]
I have a `~/lib` but it's empty and no env vars that reference it.

**Comment by semarie** [comment]
@rkitover I saw your vm is OpenBSD. How do you build rustc ? Does the source comes from ports ? or with ports patches ? The rustc source in ports has local patches for the library path resolution (to not rely on `env::current_exe` which is broken under OpenBSD).

**Comment by semarie** [comment]
I think you are hited by the bad behaviour of `env::current_exe` under OpenBSD.

You should be able to workaround by using `rustc --sysroot=/usr/local/stow/rust-git`. A shell wrapper is also a possibility (see http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/lang/rust/files/Attic/rustc?rev=1.1.1.1&content-type=text/x-cvsweb-markup as example). But `rustdoc` doesn't have such flag...

**Comment by Mark-Simulacrum** [comment]
Linking `rustc` today seems to work, though I haven't tested on anything beyond macOS; I'm going to close but do let us know if this is an issue and we'll reopen.
