### ISSUE TITLE
Macro hygiene bug

### ISSUE THREAD

**Issue by jseyfried** [rust-lang/rust#32922]
The following should print `1`, but it currently prints `0`:
```rust
fn main() {
    let x = 0;
    macro_rules! foo { () => {
        let x = 1;
        macro_rules! bar { () => {x} }
        println!("{}", bar!());
    }}

    foo! {};
}
```

For comparison, the following correctly prints `1`:
```rust
fn main() {
    let x = 0;
    macro_rules! foo { () => {{ //< note the added brace here
        let x = 1;
        macro_rules! bar { () => {x} }
        println!("{}", bar!());
    }}}

    foo! {};
}
```

**Comment by jseyfried** [comment]
cc @nrc

**Comment by jseyfried** [comment]
Another example -- the following should print `1` but currently does not compile:
```rust
macro_rules! foo { () => {
    let x = 1;
    macro_rules! bar { () => {x} }
    println!("{}", bar!());
}}

fn main() {
    foo! {};
}
```

Either adding another pair of braces (as in my first example) or manually expanding the macro allows this example to compile.

**Comment by durka** [comment]
This is probably a special case of hygiene not really working at all in multi-statement macros, #31856.

**Comment by jseyfried** [comment]
@durka indeed it is. That issue is also fixed by #32923.

**Comment by durka** [comment]
Amazing, thanks! (Should we check crater for breakage, though?)

**Comment by jseyfried** [comment]
I think it's unlikely that there will be breakage, but it would probably be a good idea to check anyway, especially since silent changes in behavior are scary.

**Comment by durka** [comment]
Well crater doesn't catch those, so we just have to hope that nobody was actually using multi-statement macros...

**Comment by jseyfried** [comment]
True, but if there's no breakage I think that's pretty strong evidence that there won't be any behavior changes since I would think breakage (either due to there not being a shadowing binding in the macro expansion or due to the shadowing binding being of the wrong type) would be much more likely than a behavior change (in which there would need to be a shadowing binding of the same type).

**Comment by jseyfried** [comment]
Also, does crater run tests?

**Comment by bluss** [comment]
Right, crater does not normally run tests. So macros not used/expanded in a crate somewhere are entirely unexercised by crater.

**Comment by durka** [comment]
Does it _build_ the tests? If not perhaps it builds bins, and we could "test" macro crates that way?

**Comment by durka** [comment]
It [seems](https://github.com/brson/taskcluster-crater/blob/3af8ffcacdad7e5c44b46f3b7bebf536c2a084d7/run-crater-task.sh#L105) that crater simply runs `cargo build`. As an experiment I just hacked up [this crate](https://github.com/durka/counted-array) so the integration tests are configured as no-op bins, such that `cargo build` fails if the tests fail to build. It's pretty ugly though and is obviously opt-in.
