### ISSUE TITLE
Update Cargo.toml in getting-started doc

### ISSUE THREAD

**Issue by deepak** [rust-lang/rust#32928]
I am learning rust and reading the book for the first time

in https://github.com/rust-lang/rust/blob/9094935b460975b6fac272ebf5985dfd71b90104/src/doc/book/getting-started.md#making-a-new-cargo-project-the-easy-way

the generated `Cargo.toml` has changed

slight difference is that it has a section called `[dependencies]`

should we specify the actual file ?

**Comment by GuillaumeGomez** [comment]
It should look like the generated `Cargo.toml` file. Want to open a PR to fix this?

**Comment by deepak** [comment]
@GuillaumeGomez absolutely. on it

**Comment by deepak** [comment]
@GuillaumeGomez submitted a small PR
