### ISSUE TITLE
docs: add link for the next project in the guessing-game doc

### ISSUE THREAD

**Issue by deepak** [rust-lang/rust#32936]
I am learning rust and reading the book for the first time

The [guessing-game](https://github.com/rust-lang/rust/blob/01d76099f261abe50342d9261fad618c5323274b/src/doc/book/guessing-game.md#complete) section mentions a "Next Project" at the very end

> Our next project will show off even more.

We can add a link to that project ?

**Comment by GuillaumeGomez** [comment]
It's referring to the next project showed in the book (so next section if I remember well). If @steveklabnik confirms, this issue can be closed.

**Comment by steveklabnik** [comment]
Actually, this sentence is vestigial from when we had the Dining Philosophers chapter. I would actually prefer to remove this sentence. Want to submit another PR? :D

**Comment by deepak** [comment]
@steveklabnik absolutely :-) on it

**Comment by deepak** [comment]
was interested in looking at the old [example](https://github.com/rust-lang/rust/blob/27a1834ce522e3ec7fe4726b1661de16ee30c503/src/doc/book/dining-philosophers.md).
pasted here for future people
was removed in https://github.com/rust-lang/rust/commit/0c6c34de87c899ecb8b977e7ef24510ab2a68168

**Comment by deepak** [comment]
@steveklabnik sent PR
