### ISSUE TITLE
documentation: str::split_at_mut() example wrong

### ISSUE THREAD

**Issue by bungcip** [rust-lang/rust#32933]
it seem example in https://doc.rust-lang.org/std/primitive.str.html#method.split_at_mut
is duplicate of str::split_at() example

**Comment by GuillaumeGomez** [comment]
Indeed. Want to fix it?

**Comment by bungcip** [comment]
Sure, but I will need to clone & learn how to build rust from source tough. I hope my notebook is not too slow to compile it :).

**Comment by bluss** [comment]
Go ahead and fix. But for this small thing I would probably not build rust locally at all. Make sure the code compiles in a simpler environment, and then let the test builders take care of it?

**Comment by GuillaumeGomez** [comment]
Just like @bluss said, no need to build anything. Just modify the comment in the rustc source code and open a PR.

**Comment by tbu-** [comment]
Fixed by #32941.
