### ISSUE TITLE
trait object example doesn't compile

### ISSUE THREAD

**Issue by kindlychung** [rust-lang/rust#32955]
Code from the book:

```
fn main() {
    struct FooVtable {
        destructor: fn(*mut ()),
        size: usize,
        align: usize,
        method: fn(*const ()) -> String,
    }

    // u8:

    fn call_method_on_u8(x: *const ()) -> String {
        // the compiler guarantees that this function is only called
        // with `x` pointing to a u8
        let byte: &u8 = unsafe { &*(x as *const u8) };

        byte.method()
    }

    static Foo_for_u8_vtable: FooVtable = FooVtable {
        destructor: /* compiler magic */,
        size: 1,
        align: 1,

        // cast to a function pointer
        method: call_method_on_u8 as fn(*const ()) -> String,
    };


    // String:

    fn call_method_on_String(x: *const ()) -> String {
        // the compiler guarantees that this function is only called
        // with `x` pointing to a String
        let string: &String = unsafe { &*(x as *const String) };

        string.method()
    }

    static Foo_for_String_vtable: FooVtable = FooVtable {
        destructor: /* compiler magic */,
        // values for a 64-bit computer, halve them for 32-bit ones
        size: 24,
        align: 8,

        method: call_method_on_String as fn(*const ()) -> String,
    };
}
```

Error:

```
<anon>:20:41: 20:42 error: unexpected token: `,`
<anon>:20         destructor: /* compiler magic */,
                                                  ^
playpen: application terminated with error code 101
```

Apparently something has to be filled in. A beginner would have no idea what should go in there.

**Comment by durka** [comment]
I think the book should just make clear that this example isn't intended to be run, just to give a general idea how the compiler is representing things.

**Comment by steveklabnik** [comment]
Yes, I thought that was the case, but if someone has ideas on how to make it more clear, we should

**Comment by johnSerrano** [comment]
Why don't we simply make the code compile? Here is one such version:

    fn main() {
        struct FooVtable {
            destructor: fn(*mut ()),
            size: usize,
            align: usize,
            method: fn(*const ()) -> String,
        }

        // u8:

        fn call_method_on_u8(x: *const ()) -> String {
            // the compiler guarantees that this function is only called
            // with `x` pointing to a u8
            let byte: &u8 = unsafe { &*(x as *const u8) };

            byte.to_string()
        }

        fn drop(to_drop: *mut ()) {}

        static Foo_for_u8_vtable: FooVtable = FooVtable {
            destructor: drop,
            size: 1,
            align: 1,

            // cast to a function pointer
            method: call_method_on_u8 as fn(*const ()) -> String,
        };


        // String:

        fn call_method_on_String(x: *const ()) -> String {
            // the compiler guarantees that this function is only called
            // with `x` pointing to a String
            let string: &String = unsafe { &*(x as *const String) };

            string.to_string()
        }

        static Foo_for_String_vtable: FooVtable = FooVtable {
            destructor: drop,
            // values for a 64-bit computer, halve them for 32-bit ones
            size: 24,
            align: 8,

            method: call_method_on_String as fn(*const ()) -> String,
        };
    }

**Comment by kindlychung** [comment]
Why does `size` in `Foo_for_String_vtable` depends on whether the cpu is 64bit or 32bit, while in `Foo_for_u8_vtable` it does not?

**Comment by birkenfeld** [comment]
@johnSerrano that drop doesn't seem right for String.

In any case, I don't think there's a use for making this compileable -- it's not meant for readers to write such code.

**Comment by steveklabnik** [comment]
Tagging as p-low since this is for the old book; it'd be nice to have a PR!

**Comment by steveklabnik** [comment]
Update: we are accepting small PRs for the first edition of the book, but not keeping issues open. https://github.com/rust-lang/book is where you'd send said PR into; please do so if you want to see this fixed. Thanks!
