### ISSUE TITLE
The trait object Foo+Copy implements the trait Copy

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#32963]
`select` considers the trait object type `Foo+Copy` to implement the trait `Copy`, and therefore its supertraits `Clone` and `Sized`. This is totally bogus, as the trait object type is *not* Sized.

For example:
```Rust
use std::{fmt, mem};

fn size_of_copy<T: Copy+?Sized>() -> usize { mem::size_of::<T>() }

fn main() {
    println!("{}", size_of_copy::<fmt::Debug+Copy>());
}
```

This obviously should not compile, but it does (and prints 16, because of the `size_of` unsized hack).

**Comment by arielb1** [comment]
cc @nikomatsakis

**Comment by nikomatsakis** [comment]
@arielb1 indeed.

**Comment by nikomatsakis** [comment]
triage: P-high

**Comment by arielb1** [comment]
I am working on a fix.

**Comment by nikomatsakis** [comment]
@arielb1 saw your ping on IRC; it seems like we simply should consider `Copy` to be object-unsafe. Ideally with a warning period.

**Comment by nikomatsakis** [comment]
(I've always thought that unsized types would be move-only.)
