### ISSUE TITLE
Current atomics are not defined to be lock-free

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#32967]
Right now we define things like `AtomicPtr` unconditionally. On platforms without real atomics these get lowered to locks today. People write lock-free algorithms with these atomics that are not actually guaranteed to be lock free.

For comparison, I'm told (by @sunfish) that C++ _does_ try to guarantee that atomics are lock-free.

cc https://github.com/rust-lang/rfcs/pull/1543

**Comment by jmesmon** [comment]
`C++` (and `C11`) makes no guarantee of it's atomics being lock-free. Only `atomic_flag` is guaranteed to be lock free. All other `atomic<T>` variants are allowed to be implemented by locks.

Previous discussion around this can be seen in https://github.com/rust-lang/rfcs/pull/1505

**Comment by brson** [comment]
@jmesmon Ah, you are right. There is an [api](http://www.cplusplus.com/reference/atomic/atomic_is_lock_free/) for asking whether atomics are lock free.

**Comment by Amanieu** [comment]
The plan with rust-lang/rfcs#1543 is to only expose atomic types which are guaranteed to be lock-free. Non-lock free atomic types can then be built on top of those, like I did in the [atomic-rs](https://github.com/Amanieu/atomic-rs) library.

**Comment by dtolnay** [comment]
I believe this is being tracked in https://github.com/rust-lang/rust/issues/32976, as it is the thing currently blocking stabilization of the atomic types from https://github.com/rust-lang/rfcs/pull/1543.
