### ISSUE TITLE
Release note PR link incorrect (suggest enum variants for non-exhaustive match patterns)

### ISSUE THREAD

**Issue by tbu-** [rust-lang/rust#32975]
In [RELEASES.md](https://github.com/rust-lang/rust/blob/db2939409db26ab4904372c82492cd3488e4c44e/RELEASES.md#misc) we can find "Errors for non-exhaustive `match` patterns now list up to 3 missing variants while also indicating the total number of missing variants if more than 3.", but it links to #31534 which is about something different. I can't find the actual PR, if someone finds it, I could submit a patch.

**Comment by apasel422** [comment]
Was this #31020?

**Comment by tbu-** [comment]
Yea, looks like it.

**Comment by tbu-** [comment]
Fixed in https://github.com/rust-lang/rust/commit/3757a3786ca9ac21c385fda96baa2c0e457a2f52.
