### ISSUE TITLE
default impl not showing up in rustdoc

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#32974]
For example, we have [ToString](https://doc.rust-lang.org/stable/src/collections/up/src/libcollections/string.rs.html#1739-1749):
```rust
impl<T: fmt::Display + ?Sized> ToString for T {
    fn to_string(&self) -> String { /*...*/ }
}
```
This shows up fine in stable: https://doc.rust-lang.org/stable/std/string/trait.ToString.html

However, starting in beta, we have a [specializable version](https://doc.rust-lang.org/beta/src/collections/up/src/libcollections/string.rs.html#1756-1766):
```rust
impl<T: fmt::Display + ?Sized> ToString for T {
    default fn to_string(&self) -> String { /*...*/ }
}
```
Which doesn't show up: https://doc.rust-lang.org/beta/std/string/trait.ToString.html

**Comment by apasel422** [comment]
Is this related to #32841 and #29503?

**Comment by jethrogb** [comment]
Definitely a dupe of #32841, which I didn't find because it was unlabeled. Not sure if either of these is actually a dupe of #29503.

**Comment by jethrogb** [comment]
Not due to specialization, actually a regression, see e.g. https://doc.rust-lang.org/stable/std/any/trait.Any.html vs https://doc.rust-lang.org/nightly/std/any/trait.Any.html which does not use specialization.
