### ISSUE TITLE
`usize()` is parsed as the type `usize`

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#32995]
This compiles, but it seems it should not:

``` rust
let x: usize() = 1;
```

**Comment by bluss** [comment]
@ubsan pointed out that the origin is the Trait() syntax (for the no type parameters case).

**Comment by petrochenkov** [comment]
This is syntactically correct (think about `let a: Fn()`), but the sanity check "parenthesized parameters may only be used with a trait" is missing for primitive types.

**Comment by ubsan** [comment]
This is equivalent to `let x: usize<> = 1`.
