### ISSUE TITLE
`std::num::Wrapping` does not implement `std::fmt::Display`

### ISSUE THREAD

**Issue by Thiez** [rust-lang/rust#33006]
I would expect this to work, and print '1': `println!("{}", std::num::Wrapping(1u8));`. Instead the compiler informs me:

> error: the trait `core::fmt::Display` is not implemented for the type `core::num::Wrapping<u8>`

Perhaps `Wrapping` should implement `Display`?

**Comment by alexcrichton** [comment]
Sounds like a good idea to me!
