### ISSUE TITLE
What about disabling telemetry feature on msvc target?

### ISSUE THREAD

**Issue by pravic** [rust-lang/rust#33004]
_Preface:_
I am not familar with it actually, only digged into compiled binary and found references to the telemetry triggers (e.g. `__telemetry_main_invoke_trigger`). Quick googleing gived following links: [small article](http://webcache.googleusercontent.com/search?q=cache:R3Jds7pW_cgJ:http://levicki.net/articles/2015/12/03/RANT_Microsoft_Visual_Studio_2015.php%2Btelemetry+main+invoke+trigger&hl=ru&ct=clnk) at google cache and [how to disable it](https://connect.microsoft.com/VisualStudio/feedback/details/1852848/unexpected-dependency-of-advapi32-dll-when-statically-linking-the-runtime-library).

So, for example, I want to disable telemetry in my compiled binaries. I need either to link that _notelemetry.obj_ or to use the previous MSVC toolchain (2013 iirk).

What is the easier way to do it _for all cargo projects_? I found only one via `set RUSTFLAGS=-C link-args=notelemetry.obj` and with the similar key in _.cargo/config_.

Anyway, it is a one more reason to use the own runtime library.

**Comment by alexcrichton** [comment]
As far as I know we don't opt in to this anywhere, so is there some form of opt-out that we need to pass to the linker? If `-C link-args` works, does that work for now?

**Comment by pravic** [comment]
By default _msvcrt?.lib_ and _libcmt?.lib_ contain references to the telemetry triggers. 
But that references can be resolved to NO-OP stubs from *notelemetry.obj*, since symbols from object files has higher priority than from libraries.

And yes, `-C link-args` works well for me.

**Comment by retep998** [comment]
Ideally we would be able to tell Rust to link `notelemetry.obj` like any other library. However Rust currently forces our hand in only linking to libraries since both `kind=static` and `kind=dylib` tack on a `.lib` on Windows. It would be nice if there were more kinds for other things such as `kind=object` to pass along a `foo.obj`. Also would be nice to have a kind for `foo.res` resource files.

**Comment by Mark-Simulacrum** [comment]
I think the solution with `-C link-args` is what we should go with for the time being until an RFC is proposed and merged that expands the link kinds. There's not much that can be done on the rustc side until that happens, so I'm going to close. Please reopen if we do actually have something actionable.

**Comment by pravic** [comment]
That telemetry feature was disabled within the one of VS2015 updates.
