### ISSUE TITLE
Panic in librbml while drunk-compiling

### ISSUE THREAD

**Issue by pierrechevalier83** [rust-lang/rust#33015]
```
   Compiling pistoncore-input v0.9.0
/home/pierrec/.cargo/registry/src/github.com-88ac128001ac3a9a/pistoncore-input-0.9.0/src/lib.rs:9:1: 9:23 error: the crate "bitflags" has been compiled with rustc 1.7.0, which is incompatible with this version of rustc [E0514]
/home/pierrec/.cargo/registry/src/github.com-88ac128001ac3a9a/pistoncore-input-0.9.0/src/lib.rs:9 extern crate bitflags;
                                                                                                  ^~~~~~~~~~~~~~~~~~~~~~
/home/pierrec/.cargo/registry/src/github.com-88ac128001ac3a9a/pistoncore-input-0.9.0/src/lib.rs:9:1: 9:23 help: consider removing the compiled binaries and recompiling with your current version of rustc
ERROR:rbml::reader: failed to find block with tag 275
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rustlang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'explicit panic', ../src/librbml/lib.rs:436
note: Run with "RUST_BACKTRACE=1" for a backtrace.


Build failed, waiting for other jobs to finish...
Could not compile "pistoncore-input".
```

**Comment by pierrechevalier83** [comment]
Couldn't reproduce: next time I compiled, I just got a compile error in a different part of the compiled code. Just thought I would raise a ticket anyway because it should probably not have panicked the first time.

Lesson for future generations of rustaceans: don't compile code on friday pub night when drunk: It's bad for your health!

**Comment by sanmai-NL** [comment]
You have a curious idea of a night out!

**Comment by arielb1** [comment]
I think someone is doing error recovery for "error: the crate "bitflags" has been comp
iled with rustc 1.7.0, which is incompatible with this version of rustc"

**Comment by eddyb** [comment]
@pierrechevalier83 Something was very strange in your original description, I tried to clean up the markdown to make it easier to read.

**Comment by arielb1** [comment]
Problem lines of code:

https://github.com/rust-lang/rust/blob/2a815a26c8ce70e1aede585827c020d9775a8faf/src/libsyntax/errors/mod.rs#L209

```Rust

    pub fn emit(&mut self) {
        if self.cancelled() {
            return;
        }

        self.emitter.borrow_mut().emit_struct(&self);
        self.cancel();

        // if self.is_fatal() {
        //     panic!(FatalError);
        // }
    }
```

Why is the panic commented? cc @nrc

**Comment by nrc** [comment]
That seems like it should be uncommented. It's a mistake either way, I wouldn't deliberately check-in commented code, but I don't recall if it should be uncommented or just not there. It does seem like we should panic on fatal errors.

**Comment by nikomatsakis** [comment]
triage: P-medium

**Comment by filmor** [comment]
The ghost seems to be back, I'm getting this error when compiling RustAudio/synth on Windows. I'll try to get rustc compiled from source to debug this.

**Comment by eddyb** [comment]
@filmor Did you update your Rust version yet there are `rlib` files around that are older?

**Comment by filmor** [comment]
Not that I'm aware, this is a fresh build with a newly rustupped rustc. To be sure I cleaned up `.cargo` and `target` and I'm still getting the error.
