### ISSUE TITLE
Make duration constructor functions `const`.

### ISSUE THREAD

**Issue by quadrupleslap** [rust-lang/rust#33029]
Is there anything stopping the functions `from_millis, from_secs and new` in `std::time::Duration` from being constant?

**Comment by nagisa** [comment]
You cannot use a `const fn` with stable compiler, so for most purposes making these functions const now is useless.

**Comment by sfackler** [comment]
I'm not totally sure I understand that, @nagisa - stable users of the compiler will see no change and people on nightlies will be able to take advantage of the const-ness.

**Comment by tbu-** [comment]
Now impossible until we allow panics in `const` functions: #33072.

**Comment by ticki** [comment]
#34918

**Comment by dtolnay** [comment]
This is going to depend on what happens with https://github.com/rust-lang/rfcs/issues/1383. Let's continue to track this as part of https://github.com/rust-lang/rust/issues/24111 as Alex commented in https://github.com/rust-lang/rust/pull/33033#issuecomment-217042746:

> Adding a `const` fn is a serious API commitment that we may not always be able to uphold (e.g. #33072). In the meantime `const fn` is still unstable, and when stabilized we will likely want to perform a pass over the standard library to audit for functions which are const-compatible at that time.
