### ISSUE TITLE
'static is accepted as a loop label name

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#33059]
Compiles on stable/beta/nightly:
```
fn main() {
    'static: loop {
        break 'static
    }
}
```

Not sure if it's bad or not, but worth opening an issue.
It may conflict with a possible future block lifetime notation or something.

**Comment by brson** [comment]
Seems bogus.

**Comment by steveklabnik** [comment]
They're described as "lifetime names", so like, in a twisted way, it makes sense, but it also makes no sense. Agree that it should probably be removed.

**Comment by GuillaumeGomez** [comment]
Shouldn't rust keywords not be used as label name (and not just `static`)?

**Comment by alrz** [comment]
That's a double-negative right there.

**Comment by Azy8BsKXVko** [comment]
It seems like the difference in syntax would prevent a conflict, though I could be wrong (I'm new to Rust). It might be worthwhile to at least have the compiler throw a warning for ergonomic reasons.
