### ISSUE TITLE
`net::{TcpStream,TcpListener}::set_only_v6` are useless

### ISSUE THREAD

**Issue by troplin** [rust-lang/rust#33052]
AFAIUI, `net::TcpListener::set_only_v6` has to be called *before* `bind`ing a socket. However, with the current API this is not possible.

For `TcpStream` I'm not sure if this option is meaningful at all. And if it is, it surely has to be set *before* `connect`ing.

I know the FCP for those is over, but they should still be removed IMO.

**Comment by sfackler** [comment]
Oops, yeah, I'd say we should probably back these out of the beta. I'll raise it for discussion during libs triage.

@rust-lang/libs.
