### ISSUE TITLE
Duplicate impl blocks in rustdoc

### ISSUE THREAD

**Issue by caipre** [rust-lang/rust#33054]
The inherent methods for structs in `std::os::unix::net` are shown twice, eg: http://doc.rust-lang.org/nightly/std/os/unix/net/struct.SocketAddr.html

Not sure whether this is limited to nightly or not.

Possibly related to https://github.com/rust-lang/rust/issues/21474.

**Comment by GuillaumeGomez** [comment]
It's "supposed" to have been fixed in [this commit](https://github.com/rust-lang/rust/commit/0f3183f42b02aee06e920dec18b0f4d1c93e6a77).

cc @alexcrichton
