### ISSUE TITLE
Add support for new `allocsize` attribute in LLVM

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#33075]
This is mostly a TODO issue for when we next upgrade LLVM. They have recently [landed upstream](http://reviews.llvm.org/rL266032) support for a new attribute to tag functions with to indicate that they are an allocator.

This should hopefully obsolete [our local patch](https://github.com/rust-lang/llvm/commit/cca16c06fbec672b7d1dd9753491783a006bdfe5) and we should use these attributes instead.

**Comment by Mark-Simulacrum** [comment]
Did this happen? I'm not quite sure, but I feel like perhaps not. I think we do have a recent enough version of LLVM for this to be available....

**Comment by nagisa** [comment]
So, this allocsize attribute has this comment attached to it:

> allocsize should not imply that a function is a traditional allocation function (e.g. that can be optimized out/...); it just tells us how many bytes exist at the pointer handed back by the function.

and it seems that the whole purpose if it revolves around removing stuff like bound checks. It might still be super worth it to attach these attributes, but they won’t help with optimising out the allocations.

**Comment by nagisa** [comment]
See also [this](http://lists.llvm.org/pipermail/llvm-commits/Week-of-Mon-20161219/415091.html)

**Comment by alexcrichton** [comment]
It sounds like this isn't going to obsolete our local patch here, so closing.
