### ISSUE TITLE
rustc ran my code at compile time and then reported a failed `assert!` as an ICE

### ISSUE THREAD

**Issue by sgrif** [rust-lang/rust#33087]
To be clear, this was normal Rust code, not a compiler plugin or anything else.

Video of the event: https://www.twitch.tv/seantheprogrammer/v/61454250?t=49m45s

I completely understand if this is just closed, as I haven't really given much to reproduce. I would be remised if I didn't report it anyway though, as this somewhat fundamentally broke my understanding of what the compiler is doing

The code was doing some things with `TypeId` so I can kinda see in theory why maybe this would be a thing but not after I add a bunch of `println!`s and `asserts!`

**Comment by alexcrichton** [comment]
The backtrace had `diesel` in it, so perhaps this was a panic in one of diesel's plugins? (notably the `expand_infer_schema` function

**Comment by sgrif** [comment]
Ugh, you're right. Looking at it now, this is our compiler plugin using our non-compiler-plugin code... Sorry for the noise

**Comment by sgrif** [comment]
Faith in computers restored.
