### ISSUE TITLE
Can we get a decorate-sort-undecorate sorting in the standard libaries?

### ISSUE THREAD

**Issue by mwm** [rust-lang/rust#33104]
The decorate-sort-undecorate idiom makes for much faster key-based sorts, especially when key calculation is  expensive. My implementation for vectors (as I needed those rather than slices) looks like:

``` rust
fn decorated_sort<F, E, K>(v: &Vec<E>, key: F) -> Vec<&E>
    where F: Fn(&E) -> K, K: Ord + Clone, E: Clone {
        let v: Vec<(K, &E)> = v.iter().map(|m| (key(m), m)).collect();
        v.clone().sort_by_key(|t| t.0.clone());
        v.iter().map(|t| t.1).collect::<Vec<_>>()
    }
```

The quick test for timing for the case I was interested in looks like:

``` rust
    println!("sort_by_key: {:.2}",
             timeit(&mut || v.sort_by_key(|m| do_eval(&mut b.clone(), &m))));
    println!("DSU: {:.2}",
             timeit(&mut || {decorated_sort(&v, |m| do_eval(&mut b.clone(), &m));}));
```

The decorated version runs six times faster on even the relatively short lists (72 elements) I was using, decorated_sort ran six times faster than the sort_by_key.

**Comment by bluss** [comment]
New features can be suggested in the [RFC repo](https://github.com/rust-lang/rfcs) with a formal proposal (pull request) or issue.

You can make a one off tuple struct there and define the ordering to only use the first field. That removes the need to clone `K`.

**Comment by alexcrichton** [comment]
Ah yes we tend to track feature requests in the RFC repo, so I'm going to close this for now.
