### ISSUE TITLE
missing impls in std::str::Pattern docs

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#33113]
Some of the impls of Pattern disappeared from the std docs starting in beta. Compare:

- http://doc.rust-lang.org/std/str/pattern/trait.Pattern.html (stable docs, impls shown)
- http://doc.rust-lang.org/nightly/std/str/pattern/trait.Pattern.html (nightly docs, impls missing)

They are also missing from the stable (and nightly) docs of core.

**Comment by bluss** [comment]
Related to #29503. I'm surprised, I would not call `for CharEqPattern<C> where C: CharEq` a blanket impl.
