### ISSUE TITLE
Allow rebuilding just stage1 libcore, libstd, etc

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#33110]
A proposed workflow enhancer when developing libstd and/or the libraries it fronts.

The build system configuration or option will:
- Build but the stage1 compiler if it is missing, but not rebuild even if libcore, libstd etc are dirty.
- Use the stage1 compiler to rebuild libcore until libstd

The intention is to allow faster iteration and evaluation

---

The current crates that would be rebuilt would be:

```
rustc: x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore
rustc: x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc
rustc: x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand
rustc: x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_unicode
rustc: x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_bitflags
rustc: x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_system
rustc: x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc
rustc: x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc
rustc: x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections
rustc: x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd
rustc: x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libterm
rustc: x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts
rustc: x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest
```

**Comment by alexcrichton** [comment]
I believe this was implemented with `--keep-stage`, so closing.

**Comment by SimonSapin** [comment]
@alexcrichton Could you explain how that is used (e.g. what command takes that parameter)? What’s your recommended workflow when working on `std`?

**Comment by bluss** [comment]
--keep-stage is great for when you have changed the compiler and need to iterate on `not(cfg(stage0))` things (or equivalent). You build using `./x.py build --stage 1` first and rebuild using `./x.py build --keep-stage 0 --stage 1` I've used it to great effect this way.

There are other workflows where you can use local rebuild or some developing incremental compilation stuff instead, I don't know them well. This issue is sort of served by both these alternatives.
