### ISSUE TITLE
Tracking issue for -C overflow-checks

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#33134]
Tracking issue for https://github.com/rust-lang/rfcs/pull/1535

**Comment by alexcrichton** [comment]
FWIW this should be a relatively easy bug to knock out! 

The `force_overflow_checks` option is [defined with other debugging options](https://github.com/rust-lang/rust/blob/ccd96c945fb5d3a0841e0f9469d27f1fc8142edd/src/librustc/session/config.rs#L939-L940) and we'd just want to add a new flag to the [associated codegen options](https://github.com/rust-lang/rust/blob/ccd96c945fb5d3a0841e0f9469d27f1fc8142edd/src/librustc/session/config.rs#L778-L846) (we'll delete the `-Z` flag once everyone's migrated).

There's a few uses throughout the codebase which I believe will need an update:

* [`svh_visitor.rs`](https://github.com/rust-lang/rust/blob/ccd96c945fb5d3a0841e0f9469d27f1fc8142edd/src/librustc_incremental/calculate_svh/svh_visitor.rs#L66-L67)
* [`hair/cx/mod.rs`](https://github.com/rust-lang/rust/blob/ccd96c945fb5d3a0841e0f9469d27f1fc8142edd/src/librustc_mir/hair/cx/mod.rs#L62-L68)
* [`trans/base.rs`](https://github.com/rust-lang/rust/blob/ccd96c945fb5d3a0841e0f9469d27f1fc8142edd/src/librustc_trans/base.rs#L1135-L1139)

After that we'd just need to add a test which validates this behavior, likely a `src/test/run-pass/*.rs` addition with a `// compile-flags: ...` annotation at the top.

Likewise the Cargo support should be relatively easy:

* [First, `parse it`](https://github.com/rust-lang/cargo/blob/fdfdb5f393c39ef5899625b344489b6567aaaa28/src/cargo/util/toml.rs#L277-L286)
* [Add an option to cargo's profile](https://github.com/rust-lang/cargo/blob/fdfdb5f393c39ef5899625b344489b6567aaaa28/src/cargo/core/manifest.rs#L146-L161)
* [Merge a toml profile to a cargo profile](https://github.com/rust-lang/cargo/blob/fdfdb5f393c39ef5899625b344489b6567aaaa28/src/cargo/util/toml.rs#L1268-L1296)
* [Read the profile option in the backend](https://github.com/rust-lang/cargo/blob/fdfdb5f393c39ef5899625b344489b6567aaaa28/src/cargo/ops/cargo_rustc/mod.rs#L592-L596)
* [Extend `build_base_args` with the new option](https://github.com/rust-lang/cargo/blob/fdfdb5f393c39ef5899625b344489b6567aaaa28/src/cargo/ops/cargo_rustc/mod.rs#L724)

**Comment by froydnj** [comment]
I'd like to tackle this!

**Comment by froydnj** [comment]
OK, so this is pretty straightforward.  Couple questions after actually implementing this:

* The RFC says the option is `-C overflow-checks`, but comments on the RFC suggest that people expect this to be `-C overflow-checks(=on/off)`, so one could have (I guess) `-C debug-assertions -C overflow-checks=off`.  Which variant should be supported?
* It seems better to make the value in `CodegenOptions` the single source of truth to be used throughout the compiler by setting it based on the value of `-C debug-assertions` or `-Z force-overflow-checks`; this makes the uses easier to read and also makes any future removal of `-Z force-overflow-checks` straightforward.  How should `-C overflow-checks` interact with `-Z force-overflow-checks`?  Should we just consider any explicit setting of `-C overflow-checks` to "win" and only consult `-Z force-overflow-checks` if the `-C` option was not explicitly provided?  I guess that would mean that we'd almost have to implement the `-C overflow-checks(=on/off)` variant above?

**Comment by alexcrichton** [comment]
@froydnj I think it's fine to just reuse the existing [`parse_opt_bool`](https://github.com/rust-lang/rust/blob/536a900c471dffad6e33766a2866889000fbfa75/src/librustc/session/config.rs#L659-L676) which accepts a "standard variety" of boolean options.

> It seems better to make the value in CodegenOptions the single source of truth

Makes sense to me to have a single source of truth! Right now I don't think we have a lot of precedent for modifying `CodegenOptions` after creation so this may not be easy. Perhaps a helper method on `Session` though? That's what a [few other codegen-like options do](https://github.com/rust-lang/rust/blob/536a900c471dffad6e33766a2866889000fbfa75/src/librustc/session/mod.rs#L361-L374).

>  How should `-C overflow-checks` interact with `-Z force-overflow-checks`?

Yeah let's just have `-C` trump `-Z`. The precise semantics likely don't matter too much anyway as we'll quickly phase out the `-Z` version anyway.
