### ISSUE TITLE
impl Copy does not know about specialization

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#33162]
[(Playground link)](https://play.rust-lang.org/?gist=ff071268e631f721b1fa1c4cb222b97c&version=nightly&backtrace=0)

Imagine you have a type that you want to be `Copy` in a subset of cases (in a specialization).

In the example code, the bound `A: Copy` in `impl<A: Copy> Copy for Foo<A> { }` implies a special case of `Repr` where the type of the struct field is known to be `Copy`, and thus this should be allowed.

``` rust
#![feature(specialization)]

struct Foo<A> {
    repr: <A as Repr>::Data,
}

impl<A> Clone for Foo<A> {
    fn clone(&self) -> Self {
        panic!()
    }
}

impl<A: Copy> Copy for Foo<A> { }

trait Repr {
    type Data;
}

#[derive(Clone)]
struct IsNotCopy;

#[derive(Copy, Clone)]
struct IsCopy;

impl<A> Repr for A {
    default type Data = IsNotCopy;
}

impl<A: Copy> Repr for A {
    type Data = IsCopy;
}
```

**Comment by arielb1** [comment]
This looks like the normal "associated type being hidden from view" issue.

**Comment by bluss** [comment]
Ok. If I add `where A: Repr, A::Data: Copy ` the Copy impl does compile (but it makes Repr visible in the public).

**Comment by arielb1** [comment]
@bluss

The problem is that outside users are not allowed to assume *anything* about specialized associated items.

**Comment by bluss** [comment]
The code in the example seems to be self-contained and should not involve reasoning from the outside. The `A: Copy` bound implies a specific specialization that can not be specialized further.

**Comment by Mark-Simulacrum** [comment]
The example given now compiles. Does that mean this is fixed?

**Comment by bluss** [comment]
Yes, it's fixed entirely in the spirit of the issue (as long as it is not a mistake). This is great, and thanks for the triage.

(The issue showed up when working to make arrayvec Copy opportunistically, let's revisit that and see how it goes..)
