### ISSUE TITLE
Command::env()/env_remove() freeze the parent's environment

### ISSUE THREAD

**Issue by oconnor663** [rust-lang/rust#33183]
An example:

```rust
use std::process::Command;
use std::env;

fn main() {
    // Create a command to echo $foo.
    let mut c = Command::new("bash");
    c.arg("-c").arg("echo $foo");

    // Set an unrelated variable. This caches the current environment.
    c.env("UNRELATED_VARIABLE", "junk");

    // Define $foo in the parent. This has no effect on the child,
    // because of the line above!
    env::set_var("foo", "FOO IS DEFINED!!!");

    c.spawn().unwrap();
}
```

This program will run `echo $foo`, which prints an empty line because `$foo` is not defined in the child. But if we delete the line that sets `$UNRELATED_VARIABLE` and run again, we see `FOO IS DEFINED!!!` in the child's output.

The problem is that (at least in the unix implementation) the [`init_env_map` function](https://github.com/rust-lang/rust/blob/91aea5cf87953788477ccaa3a37c3f2c855e7a0a/src/libstd/sys/unix/process.rs#L129) caches the parent's environment the first time it's called. My preferred behavior would be that Command never caches anything from the parent, and instead reads the environment at the time the child is spawned. Does anyone know of code relying on the current behavior?

**Comment by alexcrichton** [comment]
cc https://github.com/rust-lang/rust/issues/28975, a similar issue

**Comment by oconnor663** [comment]
Definitely a dupe. I'll close this one.
