### ISSUE TITLE
Infinite loop when building recursive type

### ISSUE THREAD

**Issue by gdrooid** [rust-lang/rust#33180]
```rust
pub struct X {
 a : X,
 b : X
}
```
This causes an infinite loop when building, unlike:
```rust
pub struct X {
 a : X
}
```
where you get a `error: recursive type `X` has infinite size [E0072]`.

This happens on stable `rustc 1.8.0 (db2939409 2016-04-11)`.

**Comment by jonas-schievink** [comment]
This is fixed on nightly. Please check if bugs exist on the current nightly before opening an issue :)

**Comment by gdrooid** [comment]
I see, sorry.
