### ISSUE TITLE
Tracking issue for borrows outliving owners with destructors

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#33206]
This is a tracking issue for a planned fix for issue #31567

Any fix for #31567 is going to be a breaking change; thus, in accordance with existing policy (and draft RFC https://github.com/rust-lang/rfcs/pull/1589 ) I am planning to have the change emit warnings at first, and then after a warning cycle, we can upgrade it to an error.

So, I'm grabbing this issue now while I am working on the fix, so that my warning/error messages can reference a stable URL.

**Comment by brson** [comment]
@pnkfelix Any updates?

**Comment by pnkfelix** [comment]
I think this is fixed by NLL

**Comment by pnkfelix** [comment]
But also note PR #52782 which hasn’t landed bur does include tests that illustrate the breaking change I discussed here
