### ISSUE TITLE
ICE with C generic enum

### ISSUE THREAD

**Issue by pravic** [rust-lang/rust#33202]
http://is.gd/DOkUCJ Playground with backtrace

```rust
#[repr(C)]
pub enum CPOption<T> {
	PSome(T),
}

fn main() {
  println!("sizeof CPOption<i32> {}", std::mem::size_of::<CPOption<i32>>());
}
```

Versions affected: stable, beta, nightly.

**Comment by petevine** [comment]
Here's a [debug trace](https://gist.github.com/petevine/2b7666e1af775762dd0526d52ebdfe2f) from `rustc 1.9.0-dev (470ca1c3f 2016-04-07)`

**Comment by luqmana** [comment]
This is not limited to generic enums. Just an oversight in typeck that we allow it to get to trans at all.
