### ISSUE TITLE
Mistake in the Windows command line code in the Rust book

### ISSUE THREAD

**Issue by TomasHubelbauer** [rust-lang/rust#33219]
In the [Getting Started](http://doc.rust-lang.org/book/getting-started.html) section of the Rust book, there's this snippet under [Creating a new Executable and Source Directory](http://doc.rust-lang.org/book/getting-started.html#creating-a-new-executable-and-source-directory):

```sh
$ mkdir src
$ mv main.rs src/main.rs
$ rm main  # or 'del main.exe' on Windows
```

On Windows, there's no `mv`, just `move`. The `mv` and other commands are available when one uses Cygwin or similar, but the book says nothing about that, so it should be fixed to include a comment similarly to the line underneath it.

```sh
$ mkdir src
$ mv main.rs src/main.rs # or 'move main.rs src/main.rs' on Window
$ rm main  # or 'del main.exe' on Windows
```

**Comment by GuillaumeGomez** [comment]
Want to open a PR to modify it yourself? :)

**Comment by TomasHubelbauer** [comment]
I do and I will in a couple of days. :)

**Comment by GuillaumeGomez** [comment]
Great! cc me once done then please. :)

**Comment by retep998** [comment]
More specifically, it is only the `cmd` shell which doesn't support `rm` or `mv`. Powershell has aliases for both the `cmd` and `bash` versions.

**Comment by TomasHubelbauer** [comment]
@retep998 Thanks for the note. This is definitely good to know, but I haven't included it in the comment since with `move` you can't go wrong whichever shell you choose on Windows, so this should be beginner friendly.
