### ISSUE TITLE
value of private type accessible

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#33216]
The enum `Y` is not re-exported by module `a`, but I can end up accessing a value of it, by embedding the value in the re-exported enum `X`.

```rust
mod a {
    mod b {
        pub enum X {
            X1(Y),
        }
        #[derive(Debug)]
        pub enum Y {
            Y1
        }
        pub fn f() -> X {
            X::X1(Y::Y1)
        }
    }
    pub use self::b::{X, f};
}

fn main() {
    let x = a::f();
    let y = match x {
        a::X::X1(y) => y,
    };
    println!("{:?}", y);
}
```

**Comment by petrochenkov** [comment]
`enum Y` is marked `pub`, so it's considered accessible by the whole universe even if the type itself is not directly nameable.

**Comment by steveklabnik** [comment]
Yes, I am pretty sure that this isn't a bug. @rust-lang/lang ?

**Comment by nrc** [comment]
Yeah, I don't consider this a bug. It's not specific to enums:

```
mod a {
    mod b {
        pub fn f() -> S { S }
        pub struct S;
    }
    pub use a::b::f;
}
```

**Comment by nikomatsakis** [comment]
Agreed, not a bug. The enum type `Y` (in the original example) was declared as `pub`, meaning "potentially accessible by the entire world". If the desire was to limit the type to the `a` module, then `pub(a)` would have been correct. I'm going to close, but feel free to re-open or disagree.
