### ISSUE TITLE
UnwindSafe can't be used as an object bound

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#33222]
You can write `Box<Trait + Send>`, but you can't write `Box<Trait + UnwindSafe>`, despite both being auto traits. Is this intended?

**Comment by alexcrichton** [comment]
Yeah unfortunately you can't have `Box<A + B>` for arbitrary traits today. The current intention is to have `UnwindSafe` as a super trait rather than `+ UnwindSafe`

**Comment by alexreg** [comment]
What do you mean by a 'super trait'?

**Comment by alexcrichton** [comment]
Ah sorry, something like:

```rust
trait Trait: UnwindSafe {
    // ...
}
```

**Comment by bluss** [comment]
UnwindSafe is not an arbitrary trait, it's an auto trait.

**Comment by durka** [comment]
I mean you can just do the workaround

```rust
trait Trait {}
trait TraitPlusUnwindSafe: Trait + UnwindSafe {}
impl<T: Trait + UnwindSafe> TraitPlusUnwindSafe for T {}

Box<TraitPlusUnwindSafe>
```

but why? What's the difference between `UnwindSafe` and the older auto traits that don't need the workaround?

(The workaround works for any two traits, in fact, so I don't get the `Box<A + B>` restriction at all, but that's an RFC for another day.)

**Comment by alexcrichton** [comment]
In the past at least `Send` and `Sync` were special in the compiler, and that may just not have changed. This is basically just a dupe of "arbitrary `A + B` trait objects aren't supported"

**Comment by durka** [comment]
OK, closing as "semi-intended wart" I guess.
