### ISSUE TITLE
Support Unums Please

### ISSUE THREAD

**Issue by nikolay** [rust-lang/rust#33230]
http://www.johngustafson.net/unums.html
http://www.johngustafson.net/presentations/Unums2.0slides-withNotes.pdf

**Comment by Aatch** [comment]
While certainly interesting, unless they get hardware support, language-level support for them is neither required nor appropriate.

If you have a platform that LLVM supports that has unums built in, then feel free to re-open this issue.

**Comment by steveklabnik** [comment]
Also, features like this need an RFC, and so belong on that repository.

**Comment by TyrfingMjolnir** [comment]
The PDF is no longer available: Not Found [CFN #0005]
