### ISSUE TITLE
dep-info + -Z no-analysis no longer ignore extern crates

### ISSUE THREAD

**Issue by SiegeLord** [rust-lang/rust#33231]
Compiling this code:

```rust
extern crate doesnt_exist;

fn main() {}
```

With:

```
rustc -Z no-analysis --emit dep-info -o test.d test.rs
```

Used to work (and still works with rust 1.7), but recently has started failing (circa rustc 1.10.0-nightly (bd938166d 2016-04-25)) with this error:

```
test.rs:1:1: 1:27 error: can't find crate for `doesnt_exist` [E0463]
test.rs:1 extern crate doesnt_exist;
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
```

This makes that useful combination of flags no longer work. I suspect `-Z no-analysis` broke again.

**Comment by SiegeLord** [comment]
So this is broken again. Can this be reopened?

**Comment by jseyfried** [comment]
c.f. [this comment](https://github.com/rust-lang/rust/pull/33997#issuecomment-225426854)
