### ISSUE TITLE
Chaining filter calls on iterators leads to exponentially slower compile times

### ISSUE THREAD

**Issue by jabagawee** [rust-lang/rust#33245]
Apologies if this is a known problem already. I was working through a fairly simple Project Euler problem to learn some Rust and I think I found an issue (with possibly the type checker?).

I tried this code:

```rust
fn main() {
    let mut iterator = (1..)
        .filter(|x| x % 1 == 0)
        .filter(|x| x % 2 == 0)
        .filter(|x| x % 3 == 0)
        .filter(|x| x % 4 == 0)
        .filter(|x| x % 5 == 0)
        .filter(|x| x % 6 == 0)
        // .filter(|x| x % 7 == 0)
        // .filter(|x| x % 8 == 0)
        // .filter(|x| x % 9 == 0)
        // .filter(|x| x % 10 == 0);
    let answer = iterator.next().unwrap();
    println!("{}", answer);
}
```
I expected to see this happen: Compiling this should be pretty fast.

Instead, this happened: Exponential slowdown as I uncomment each filter line one by one

## Meta

`rustc --version --verbose`:

```
rustc 1.10.0-nightly (bd938166d 2016-04-25)
binary: rustc
commit-hash: bd938166d6dabc689777555d5046dce893555eb7
commit-date: 2016-04-25
host: x86_64-apple-darwin
release: 1.10.0-nightly
```

Backtrace: No backtrace

**Comment by nagisa** [comment]
We already know about this issue¹. Thanks for the report!

¹: See https://github.com/rust-lang/rust/issues/22204
