### ISSUE TITLE
Considering add a #[cfg] option for musl/glibc split

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#33244]
Right now `target_env` is predominately used to conditionally compile code for differing C libraries like msvc, glibc, musl, etc. On ARM, however, there are two glibc `target_env` annotations, "gnueabi" and "gneuabihf". This then also extends to musl with "musleabi" and "musleabihf". This seems unnecessarily complicated to say "conditionally compile this code when using musl", that is it should only require one annotation, not three.

We could possibly change `target_env` as I doubt anyone's using "gnueabihf" as a matcher, or we could add a new `target_libc`.

**Comment by alexcrichton** [comment]
cc https://github.com/rust-lang/rust/pull/33189

**Comment by nagisa** [comment]
The presence of absence of hard float should be denoted inside its own feature instead (`cfg(target_has_hardfloat)` or something).

**Comment by retep998** [comment]
Could we use `target_libc` for choosing between static vs dynamic or release vs debug for the msvc CRT?

**Comment by alexcrichton** [comment]
The toosl team discussed this issue at triage and the decision was to name `target_env` as either gnu or musl instead of also gnueabi/musleabi. I'll send a PR shortly

**Comment by ollie27** [comment]
There should probably also be a good way to distinguish between statically linked musl and dynamically linked musl targets.
