### ISSUE TITLE
Missing help on pattern guard

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#33247]
One the following [code](http://is.gd/Akc5Xp), suggesting to use `ref` keyword would be very appreciated I think.

**Comment by durka** [comment]
Hmm, need to be careful though... if the pattern guard actually consumes the value then you get a bug report for the compiler recommending wrong code: http://is.gd/zGSj9C

**Comment by GuillaumeGomez** [comment]
Hum... Then maybe an update of the error code explanation would be more appropriate to show the differences between the two cases.

**Comment by mrmiywj** [comment]
Hmm, using `ref` keyword is helpful [here](http://is.gd/Akc5Xp).
But in ()[http://is.gd/zGSj9C], what will be helpful except use `&self` in `consume`?

**Comment by GuillaumeGomez** [comment]
@mrmiywj: That's the point that durka pointed out. So that's why I propose to only change error explanation to reflect both cases.

**Comment by mrmiywj** [comment]
You mean that if in the context the ownership will not be taken, it is suggested to use `ref` here? 
Hmm, if it's right, I think it's a easy job and I can change the explanation to reflect both cases with some examples. U should not waste time on this dirty job.

**Comment by GuillaumeGomez** [comment]
Haha! Please do it if you want. cc me on the PR so I can review it.

**Comment by nikomatsakis** [comment]
Fixed by #33260
