### ISSUE TITLE
Checked overflow has particularly poor codegen on ARM

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#33268]
```rust
#![crate_type = "lib"]
#[no_mangle]
pub fn unchecked(x: i32, y: i32) -> i32 {
    x.wrapping_add(y)
}
#[no_mangle]
pub fn checked(x: i32, y: i32) -> i32 {
    x + y
}

#[no_mangle]
pub fn sum_unchecked(x: &[i32]) -> i32 {
    let mut s = 0i32;
    for y in x {
        s = s.wrapping_add(*y)
    }
    s
}
#[no_mangle]
pub fn sum_checked(x: &[i32]) -> i32 {
    let mut s = 0;
    for y in x {
        s += *y;
    }
    s
}
```

Compiled with 1.8, `-C opt-level=3 -Z force-overflow-checks --target arm-unknown-linux-gnueabihf`:

```asm
unchecked:
	add	r0, r1, r0
	bx	lr

checked:
	mov	r2, r0
	add	r0, r2, r1
	mov	r1, #1
	cmp	r0, r2
	movvc	r1, #0
	cmp	r1, #0
	bxeq	lr
	push	{r11, lr}
	ldr	r0, .LCPI1_0
.LPC1_0:
	add	r0, pc, r0
	bl	_ZN9panicking5panic20h68323117a6c854a2SaME(PLT)
```

And "in context" (i.e. demonstrating that the extra instructions aren't just because the function is too focused/aren't something that inlining fixes):

```asm
sum_unchecked:
	.fnstart
	mov	r2, #0
	cmp	r1, #0
	beq	.LBB2_3
	lsl	r1, r1, #2
	mov	r2, #0
.LBB2_2:
	ldr	r3, [r0], #4
	subs	r1, r1, #4
	add	r2, r3, r2
	bne	.LBB2_2
.LBB2_3:
	mov	r0, r2
	bx	lr

sum_checked:
	mov	r2, #0
	cmp	r1, #0
	beq	.LBB3_4
	lsl	r1, r1, #2
	mov	r3, #0
.LBB3_2:
	ldr	r2, [r0], #4
	add	r2, r3, r2
	cmp	r2, r3
	mov	r3, #1
	movvc	r3, #0
	cmp	r3, #0
	bne	.LBB3_5
	subs	r1, r1, #4
	mov	r3, r2
	bne	.LBB3_2
.LBB3_4:
	mov	r0, r2
	bx	lr
.LBB3_5:
	push	{r11, lr}
	ldr	r0, .LCPI3_0
.LPC3_0:
	add	r0, pc, r0
	bl	_ZN9panicking5panic20h68323117a6c854a2SaME(PLT)
```

In particular, it seems to me that the following sequence of instructions is pointless:

```rust
	mov	r1, #1
	cmp	r0, r2
	movvc	r1, #0
	cmp	r1, #0
	bxeq	lr
```

It is equivalent to something like `let r1 = 1; if overflow(r0, r2) { r1 = 0 } if r1 == 0 { return }`, but seems like all 5 instructions could be replaced with just `bxvc lr` (or maybe it has to be `cmp r0, r2; bxvc lr`, not sure).

(The equivalent on`x86` is much nicer.)

(This could well be an LLVM bug.)

**Comment by Aatch** [comment]
What do calls to `checked_*` end up looking like? I'm tempted to say this is an LLVM issue, given that it compiles to basically perfect code on x86.

**Comment by huonw** [comment]
Indeed. Clang is similarly poor, so I filed https://llvm.org/bugs/show_bug.cgi?id=27571 .

**Comment by huonw** [comment]
> What do calls to checked_* end up looking like?

Depending what you do with it, it can be OK, e.g. `x.checked_add(y).unwrap_or(x)` gives:

```asm
checked_:
	add	r1, r0, r1
	cmp	r1, r0
	movvs	r1, #0
	mov	r0, r1
	bx	lr
```

(Although it seems like better register allocation could avoid the final `mov`?)

On the other hand, that seems to be a fairly unique special case: most other uses of `checked_add` I tested give bad code generation (as in, have a redundant `cmp`/`movvc`/`cmp` chain).

**Comment by Aatch** [comment]
Yeah, it's probably an issue with LLVM's lowering in that case.
