### ISSUE TITLE
Implementation with existential lifetime issue

### ISSUE THREAD

**Issue by zakarumych** [rust-lang/rust#33273]
I believe the next code should compile:

``` rust
trait Trait<'a> {}
struct SomeType<'a> { data: &'a str }
impl<'a, 'b: 'a> Trait<'a> for SomeType<'b> {}

fn foo<T: for<'a> Trait<'a>>(t: T) {}

fn main() {
    let data = "qwerty";
    let some_type: SomeType<'static> = SomeType { data: data };
    foo(some_type);
}
```

Because `'static`: `'a` for any `'a`
Or, maybe I missed something?

**Comment by SCareAngel** [comment]
Of course if implementation could be rewritten as such `impl<'a, 'b> Trait<'a> for SomeType<'b> {}`. i.e. removing relation between `'b` and `'a`. Than this synthetic example would compile. But it could be impossible in many cases.

**Comment by nikomatsakis** [comment]
I agree it should compile; there are some long-standing issues with our handling of `for<>` bounds. The plan is to clean up them via a larger initiative (https://github.com/rust-lang/rust-roadmap/issues/8).

**Comment by cjgillot** [comment]
This now compiles.
