### ISSUE TITLE
ccache gcc not found

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#33285]
I'm building Rust with `--enable-ccache`, it fails at the miniz step:

```
compile: x86_64-unknown-linux-gnu/rt/miniz.o
make: ccache gcc: Command not found
/home/manishearth/Mozilla/rust/mk/rt.mk:90: recipe for target 'x86_64-unknown-linux-gnu/rt/miniz.o' failed
make: *** [x86_64-unknown-linux-gnu/rt/miniz.o] Error 127
```

**Comment by alexcrichton** [comment]
This is due to https://github.com/rust-lang/rust/pull/33093, specifically [this line](https://github.com/rust-lang/rust/blob/master/mk/platform.mk#L190). The problem is that --enable-ccache exports `CC="ccache gcc"` and it's ambiguous whether that's a file name with a space in it or two arguments.
