### ISSUE TITLE
Decouple `driver::run_compiler` from configuration parsing

### ISSUE THREAD

**Issue by aochagavia** [rust-lang/rust#33290]
It seems hacky that if you want to use the compiler as a library you still need to pass arguments like in the terminal, like shown below:

``` rust
run_compiler(["".to_string(), "crate_root.rs".to_string(), "-Zsave-analysis".to_string()],
             compiler_calls);
```
### Current situation

In `run_compiler`, the `args: &[String]` parameter is processed in the following way:
1. Produce a `getopts::Matches` struct
2. Based on the matches, generate a `config::Options`
3. Based on the matches, parse some extra data not included in `config::Options`: `odir`, `ofile`, `input`, `input_file_path`
4. Pass the `Matches` struct to some methods in `CompilerCalls` (`early_callback`, `no_input`, `late_callback`, `parse_pretty`)
### Proposed alternative
1. Change `run_compiler` to take `config::Options` instead of `&[String]`
2. Add all customizable options to `config::Options` (`odir`, `ofile`, etc)
3. Write a function responsible of parsing the args, like `fn parse_args(args: &[String]) -> Result<config::Options, ParseError>`
### Motivation
- Clearer separation of concerns means the code is easier to understand and modify
- This would be more library friendly: configuring the compiler requires creating a struct instead of playing with strings
- It becomes possible to write unit tests in order to verify that the configuration parsing code is correct

**Comment by aochagavia** [comment]
cc @nrc

**Comment by nrc** [comment]
SO the motivation for this is that I want it to be very easy to write a drop-in replacement for the compiler. You should be able to write `myrustc` which can be used just like `rustc` on the command line, without having to handle all the command line options. In particular, we should be able to add options to `rustc` without `myrustc` breaking or ignoring them.

I think that works if your `parse_args` function is what the compiler itself uses, then all the client has to do is have one more call (to `parse_args`) and that is not much more complex than today. 

I'm not sure if step 2 in your proposal will work - I think we must compute these things, and `config::Opions` is a very direct mirror of what gets put in on the command line.

**Comment by steveklabnik** [comment]
Triage: the signature of `run_compiler` hasn't changed. Nobody else has commented in two years. I don't think that an issue being open will help get this issue fixed. 

@rust-lang/compiler what do you think?

**Comment by eddyb** [comment]
I had a branch around, to parse CLI args *much earlier*, maybe I should revive it.

**Comment by Mark-Simulacrum** [comment]
rustc_interface I believe patches over this today via structs and such so I'm going to go ahead and close this
