### ISSUE TITLE
Better choice of LLVM optimization passes

### ISSUE THREAD

**Issue by DemiMarie** [rust-lang/rust#33299]
LLVM's `-O2` and `-O3` pipelines are [tuned for C and C++](http://llvm.org/docs/Frontend/PerformanceTips.html#pass-ordering) and Rust can almost certainly do better with a custom ordering.

**Comment by rkruppe** [comment]
See https://internals.rust-lang.org/t/using-a-custom-optimisation-pass-pipeline/2345 for prior discussion

**Comment by Mark-Simulacrum** [comment]
I feel like there's nothing concrete to be done here, and discussions such as these are better left for internals.rust-lang.org, so I'm going to close.
