### ISSUE TITLE
No impl of Ord for RefCell<T> or Cell<T> when T: Ord

### ISSUE THREAD

**Issue by vadixidav** [rust-lang/rust#33305]
Title says it all. I am working on it right now. Do I need to create an RFC or can I just send a PR?

**Comment by sfackler** [comment]
The implementation for RefCell is not super workable since it would have to either panic or return nonsensical results if the cell is borrowed mutably at the time. An impl for Cell seems like it should be fine though.

**Comment by Diggsey** [comment]
What's the problem with panicking? That's what `borrow()` does anyway if there's an outstanding mutable borrow. Given that this is single-threaded, it would be a program error anyway.

**Comment by Aatch** [comment]
@sfackler there is an impl of `PartialEq` for `RefCell<T: PartialEq>`, so `PartialOrd`/`Ord` should behave the same way anyway.

**Comment by tbu-** [comment]
Fixed by #33306.
