### ISSUE TITLE
Rustc compiler freezes when creating a recursive data structure

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rust#33310]
Hello.
The following code makes the compiler freezes:

```rust
struct Node {
    value: i32,
    left: Option<Node>,
    right: Option<Node>,
}

fn main() {
    println!("Hello, world!");
}
```
(the version with `Option<Box<Node>>` works fine, though)

Running `cargo build` takes forever. I use `rustc 1.8.0` on ArchLinux.

Thanks to fix this issue.

**Comment by rkruppe** [comment]
Should be fixed on beta and nightly. See also #32326 #32619 #33144 #33180

**Comment by antoyo** [comment]
Sorry, I have not found this issue.
