### ISSUE TITLE
Poor error messages for misplaced documentation comments

### ISSUE THREAD

**Issue by Thinkofname** [rust-lang/rust#33341]
https://play.rust-lang.org/?gist=9f18cc37901879332e989ed2319efca5&version=stable&backtrace=0
```rust
fn main() {
    /** */
    let _ = ();
}
```

and

https://play.rust-lang.org/?gist=324a76771257c6e5308698c834ad5f6b&version=nightly&backtrace=0
```rust
fn main() {
    /** */
}
```

Due to the fact documentation comments de-sugar into attributes. Not the end of the world but tripped me up when my editor used `/* */` to comment out a block starting with `*` and it broke the build.

**Comment by birkenfeld** [comment]
See also #27429.

**Comment by Thinkofname** [comment]
Looks like a dup of that, closing this one
