### ISSUE TITLE
save-analysis: use a decoupled representation for dumped data

### ISSUE THREAD

**Issue by aochagavia** [rust-lang/rust#33348]
Currently, the `Dump` trait exposes internal types of the compiler, which is undesirable. It also forces the trait's implementors to write lowering code (as can be seen in the current implementation of `json_dumper`).

### Proposed solution

1. Create a new module in `save-analysis` called `external_data` where the new `*Data` structs will live (they can be moved from `json_dumper`, along with the lowering code).
2. Modify the `Dump` trait to operate on `save_analysis::external_data::*` instead of on `save_analysis::data::*`.

### Some open problems

When getting a `DefId` from a `NodeId`, what should we do when `tcx.map.opt_local_def_id(node_id)` returns `None`? What does that mean? If we call the function with a `NodeId` provided by the compiler, should it always succeed? The current code doesn't make that assumption (see [data.rs](https://github.com/rust-lang/rust/blob/e1a575cb077d2070cc4527fa43bf9ef790f89f04/src/librustc_save_analysis/data.rs#L370))

**Comment by aochagavia** [comment]
cc @nrc

**Comment by nrc** [comment]
@aochagavia if the def id is from the local crate, then it should never return None. I think we can assume that and just unwrap. We do need to make sure we only call with local ids though, it is possible we could get a NodeId from an extern crate (via metadata or something?).
