### ISSUE TITLE
Please document ./install.sh --help in the release README.md

### ISSUE THREAD

**Issue by winks** [rust-lang/rust#33356]
Nowhere in README.md it says that `install.sh` has a `--prefix` or `--help` flag.

Yes, I can see this paragraph:
```
Read [The Book](http://doc.rust-lang.org/book/index.html) to learn how
to use Rust.
```

and I'm not asking for a full documentation in this file - but I think just documenting `--help` would be very good. I even gave `install.sh` a quick glance before using it (including searching for `prefix`) but apparently I didn't look close enough to find this.

**Comment by durka** [comment]
Where is that quote from exactly? Not in the top-level README.md.

**Comment by winks** [comment]
@durka I downloaded https://static.rust-lang.org/dist/rust-1.8.0-i686-unknown-linux-gnu.tar.gz and found it there.
Didn't go out of my way to search where that README comes from.

**Comment by steveklabnik** [comment]
@brson where does this README come from? I'm not sure.

**Comment by brson** [comment]
@steveklabnik @winks That README is https://github.com/rust-lang/rust-packaging/blob/master/etc/README.md

**Comment by steveklabnik** [comment]
Ah ha! Well, I'm willing to help anyone who wants to work on fixing this.

**Comment by winks** [comment]
https://github.com/rust-lang/rust-packaging/pull/53
