### ISSUE TITLE
MSVC: Segfaults with opt-level=3 plus unwinding

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#33352]
I've encountered two mysterious segfaults with opt-level=3 so far when porting our build system to rustbuild. Cargo tries to optimize aggressively by passing `-C opt-level=3` in optimized mode, but that had to get dialed back to `-C opt-level=2` in two cases.

One is [in compiletest](https://github.com/rust-lang/rust/blob/0eb575c702f56735d8bc6c3d76cb4d9bdeb13e84/src/tools/compiletest/Cargo.toml#L7), added in https://github.com/rust-lang/rust/pull/32755, and I believe [these failing logs](https://github.com/rust-lang/rust/pull/32755#issuecomment-210702500) ([cached here](https://gist.github.com/alexcrichton/32ac0b226edf964612dd3033a2ecb770)) are the segfault.

The next is in stdtest, being modified in https://github.com/rust-lang/rust/pull/33282, erroring [here](https://github.com/rust-lang/rust/pull/33282#issuecomment-215995058), and [cached here](https://gist.github.com/alexcrichton/2e3255ebdd8713a52bb7408ecc570034). The faulting test in std was [`sync::once::tests::poison_bad`](https://github.com/rust-lang/rust/blob/0eb575c702f56735d8bc6c3d76cb4d9bdeb13e84/src/libstd/sync/once.rs#L424).

Both faults look very related to unwinding, and are likely due to the early support of SEH in LLVM. This may or may not be fixed upstream (not tested), and if it's not we should probably reduce and send a test case upstream. Unfortunately simple minimizations have not succeeded just yet.

**Comment by steveklabnik** [comment]
@alexcrichton have you seen any segfaults lately? So much has happened since 2016 I am betting we should close this?

**Comment by alexcrichton** [comment]
Heh I have not, nor do I doubt this issue will help us actually find any, so I'll close!
