### ISSUE TITLE
New errors: expected/found types omitted

### ISSUE THREAD

**Issue by birkenfeld** [rust-lang/rust#33366]
I found this when I wanted to see how the new errors look. (If this is still expected to be WIP, let me know and I won't report other such cases for a while.)

In this test case, the "expected/found" notes don't appear:
```
$ x86_64-unknown-linux-gnu/stage1/bin/rustc src/test/compile-fail/wrong-ret-type.rs
src/test/compile-fail/wrong-ret-type.rs:12:49: 12:50 error: mismatched types [E0308]
src/test/compile-fail/wrong-ret-type.rs:12 fn mk_int() -> usize { let i: isize = 3; return i; }
                                                                                           ^
src/test/compile-fail/wrong-ret-type.rs:12:49: 12:50 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error

$ rustc src/test/compile-fail/wrong-ret-type.rs
src/test/compile-fail/wrong-ret-type.rs:12:49: 12:50 error: mismatched types:
 expected `usize`,
    found `isize` [E0308]
src/test/compile-fail/wrong-ret-type.rs:12 fn mk_int() -> usize { let i: isize = 3; return i; }
                                                                                           ^
src/test/compile-fail/wrong-ret-type.rs:12:49: 12:50 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
```

**Comment by birkenfeld** [comment]
Ah, I can see that this is because both types are "primitive", i.e. bool/char/int/float. In this case `is_simple_error` is true [here](https://github.com/rust-lang/rust/blob/44b3cd8c462a420ab64a44ef8f70c007001a1f44/src/librustc/infer/error_reporting.rs#L545) and `note_expected_found` is not called.

Previously, for these cases the "inner type error" in parens was omitted - which appears to be omitted in all cases now. I think the `is_simple_error` can just be removed, I'll open a PR.

**Comment by nikomatsakis** [comment]
cc @jonathandturner
