### ISSUE TITLE
Missing support ARM9 (soft-float) or install script error.

### ISSUE THREAD

**Issue by MrSpock** [rust-lang/rust#33395]
I tried to install rust on Arietta G25 board (http://www.acmesystems.it/arietta) and I got following error:
`root@arietta:/home/spock# curl -sSf https://static.rust-lang.org/rustup.sh | sh
rustup: gpg available. signatures will be verified
rustup: unknown CPU type: armv5tejl`

Does rust support ARM with soft-float  like one below  ?: 
`root@arietta:/home/spock# uname -a`
`
Linux arietta 4.4.4 #3 Sun Mar 6 13:49:08 CET 2016 armv5tejl GNU/Linux`

**Comment by nagisa** [comment]
Technically, there’s no reason it shouldn’t support it, but practically we do not ship prebuilt binaries for non-armv6/7. You will have to cross-compile rust for the target (and provide the target specification) on your own.

**Comment by petevine** [comment]
Yeah, the soft-float `arm-unknown-linux-gnueabi` should be downgraded to ARMv5.

Meanwhile, @MrSpock, have a look here:
https://github.com/joerg-krause/rust-cross-libs/

**Comment by Mark-Simulacrum** [comment]
I don't have the Arietta board to test it on, but rustup.sh is no longer the preferred way to install Rust. I'm going to close this, but please reopen if this is still a problem.
