### ISSUE TITLE
Spurious JSON parsing failure on bots

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#33390]
http://buildbot.rust-lang.org/builders/auto-win-gnu-32-nopt-t/builds/4079/steps/test/logs/stdio
https://gist.github.com/alexcrichton/997dd9cae99b934f945a01082d99313b
https://github.com/rust-lang/rust/pull/33376#issuecomment-216634970

```
failures:

---- [compile-fail] compile-fail\dep-graph-struct-signature.rs stdout ----
	thread '[compile-fail] compile-fail\dep-graph-struct-signature.rs' panicked at 'failed to decode compiler output as json: `ParseError(SyntaxError(ExpectedColon, 1, 11))`', C:/bot/slave/auto-win-gnu-32-nopt-t/build/src/tools/compiletest/src\json.rs:75
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    [compile-fail] compile-fail\dep-graph-struct-signature.rs

test result: FAILED. 2205 passed; 1 failed; 11 ignored; 0 measured
```

I've seen this a few times at this point, not really sure what's going on.

cc @nikomatsakis, @jonathandturner -- the failure message here is unfortunately hiding lots of information like what happened to the underlying process, can we try and surface that?

**Comment by jonathandturner** [comment]
@alexcrichton - do you have access the output it's failing to parse as json?

**Comment by jonathandturner** [comment]
I guess we could dump what we couldn't parse to stdout...

**Comment by nikomatsakis** [comment]
Possibly https://github.com/rust-lang/rust/pull/33313 ?

**Comment by nikomatsakis** [comment]
We could certainly dump the full output, yeah.

**Comment by alexcrichton** [comment]
That'd probably do it, yeah. In general though it seems like the diagnostic of a failed test could be greatly improved to include things like the process exit code, process stdout/stderr, etc.

@jonathandturner unfortunately there aren't these kind of logs for the tests :(

**Comment by jonathandturner** [comment]
Working on a quick fix to dump the failing input

**Comment by alexcrichton** [comment]
Another: https://github.com/rust-lang/rust/pull/33376#issuecomment-216692711

(different test this time)
