### ISSUE TITLE
Associated type cannot have bound that uses that type

### ISSUE THREAD

**Issue by KalitaAlexey** [rust-lang/rust#33400]
This works:

``` rust
fn works1<T: From<Vec<T>>>() -> T {
    Vec::new().into()
}

trait Trait {
    type A;
}

fn works2<T: Trait + From<Vec<T>>>() -> T {
    Vec::new().into()
}

fn works3<T>() -> T where T: Trait + From<Vec<T>> {
    Vec::new().into()
}

fn works4<T>() -> T where T: Trait, T: From<Vec<T>> {
    Vec::new().into()
}

fn main() {
    println!("Hello, world!");
}
```

That fails:

``` rust
trait Trait {
    type A;
}

fn fails<T: Trait>() -> T::A where T::A: From<Vec<T::A>> {
}

fn main() {
    println!("Hello, world!");
}
```

**Comment by KalitaAlexey** [comment]
This works:
```rust
trait T {
    type A: From<Vec<Self::A>>;
}

fn main() {
    println!("Hello, world!");
}
```

**Comment by Aatch** [comment]
For reference, this works (http://is.gd/7U2Oaa):

```rust
trait Trait {
    type A;
}

fn fails<T>() -> T where T: From<Vec<T>> {
    unimplemented!()
}

fn main() {
    println!("Hello, world!");
}
```

**Comment by arielb1** [comment]
You can always write the trait explicitly:

```Rust
trait Trait {
    type A;
}

fn fails<T: Trait>() -> T::A where T::A: From<Vec<<T as Trait>::A>> {
}

fn main() {
    println!("Hello, world!");
}
```

**Comment by KalitaAlexey** [comment]
@arielb1 Thanks for workaround, but this is a bug, am I right?

**Comment by arielb1** [comment]
More like a limitation. 

The problem is that you can't write
```Rust
trait Trait<T> {
    type A;
}

fn fails<T>() where T: Trait<T::A> {
}

fn main() {
    println!("Hello, world!");
}
```

Because that must be expanded to `T: Trait<<T as Trait<$0>>::A>` for some `$0`, and there is no way to figure out which `$0` to use. The cycle check must forbid that.

We can be smarter there and not do the check for associated types.

**Comment by KalitaAlexey** [comment]
I am compiling rustc. I am going to try to fix that.

**Comment by KalitaAlexey** [comment]
I can't fix that. I am asking for someone to help me.
I have fork of rust-lang with additional logging.
There are some gists:
**lib1.rs** - not working example
https://gist.github.com/KalitaAlexey/fd86846d093c32f048d2557e776cfd3b

**lib2.rs** - working example
https://gist.github.com/KalitaAlexey/a774cf7b2e5fbaf966074ac19eecbddf

**out1* - compiler output for lib1.rs
https://gist.github.com/KalitaAlexey/98a5e587fc90a37084701371cc1f0548

**out2** - compiler output for lib2.rs
https://gist.github.com/KalitaAlexey/e36b225c2f5376ff1e61af41390850eb

**Comment by Mark-Simulacrum** [comment]
From the original issue description, this now compiles, so I'm going to close. 

```
fn fails<T: Trait>() -> T::A where T::A: From<Vec<T::A>> {}
```
