### ISSUE TITLE
`fn f(*) {}` successfully compiles in method position

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#33413]
```
struct S {
    lol: u8
}

impl S {
    fn f(*) -> u8 {
        self.lol
    }
}

fn main() {
    println!("{}", S{lol:10}.f());
}
```
prints `10` on stable/beta/nightly.

This is the coolest syntax I've seen this year, now I'll always use `*` instead of `self` to save 3 keystrokes.

**Comment by durka** [comment]
Lol, this is great. So the `*` token is parsed [here](https://github.com/rust-lang/rust/blob/master/src/libsyntax/parse/parser.rs#L4705-4721) and it fabricates a `self` ident so it doesn't have to panic. But if there is no `self` after the `*` then line 4716, which emits the actual error, never executes.

**Comment by petrochenkov** [comment]
(I'm auditing parsing/resolution of `self` for hygiene issues, so I'll fix this as well.)
