### ISSUE TITLE
ICE in recent rustc version

### ISSUE THREAD

**Issue by dhardy** [rust-lang/rust#33436]
I don't know whether this was already reported. I get an ICE when running `cargo test` on [this Pippin version](https://github.com/dhardy/pippin/commit/ea988f0cfee6136749d63fe620a8f38b69600c1e) (also the previous commit, didn't test others).

[Compiler output](https://gist.github.com/dhardy/b811866331223a9eca7eb957bd35134b)

```
dhardy@localhost:~/other/pippin$ cargo --version && rustc --version
cargo 0.11.0-nightly (afac7fc 2016-04-27)
rustc 1.10.0-nightly (8da2bcac5 2016-04-28)
```

An older version works fine:

```
dhardy@localhost:~/other/pippin$ cargo --version && rustc --version
cargo 0.10.0-nightly (4576ae2 2016-03-16)
rustc 1.9.0-nightly (6e0f2f2f0 2016-03-16)
```

**Comment by nagisa** [comment]
cc @eddyb has Callee in trace.

**Comment by eddyb** [comment]
My guess is `Callee::trait_method` or `meth::get_impl_method` needs to normalize the substitutions/`TraitRef`.

**Comment by vwim** [comment]
Getting the same ICE with `rustc 1.10.0-nightly (b5ba5923f 2016-04-21)` while running https://github.com/sebcrozet/ncollide examples.

**Comment by xen0n** [comment]
Just bisected this and got

```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
7011e30352583b5965c4a9118ca2c14b8ab24454
55b5a365ef64c6c1a53e348a5a5a5ff1cac1d958
9221b9118b96d668e2cf5d701b10c0566aa072e9
5af3c12cfc07887b66ed1d8cd9e59e1c77cc8790
c6d214bdeb1bfc9664ad14085c94bf2cbc5af6ee
b122d1636ac502dad51c827c16dc95d80d96c838
c3f856e7e24be568902a38c6a488aee6098f94cc
89766a81ef6270595cb8e51f100ed44be4bb9929
e0970498c79de1a1381d697b3c27895ef798e288
16201d45f16845cb5dc2fc0b48bcf34a6715ea14
d6e72c48dd7dacebe08b44e7ee6ce0f052797f55
062a05dde8c3ea5386fa358d882e1eaca99a9ff0
b05556e06da7c79f9db746728c2557114a94b3b1
b918e37eb3e393c5a5b0408430e146c0b66ec7ed
cdfad40735745252ad42519df8a6c8ecc3739b58
da66431d06b961efd323f25978964df54d44d3c4
We cannot bisect more!
```

Surely it regressed during the trans refactoring, but as *none* of the intermediate commits is building it's not exactly sure which change is to blame though. Will help investigating further.

**Comment by xen0n** [comment]
I would try to fix this, already did one-liner fix in `trans/callee.rs` according to @eddyb , both `pippin` and the minimal testcase in #33461 passed without ICE. Will prepare the PR later ;-)
