### ISSUE TITLE
Type inference fails in unpredictable ways

### ISSUE THREAD

**Issue by notriddle** [rust-lang/rust#33449]
[This works](https://play.rust-lang.org/?gist=90f4a0519b6dc16a9961adbc87c26ab9&version=stable&backtrace=0)

``` rust
#![allow(unused)]

fn f<F>() -> Result<Option<F>, ()> {
    panic!()
}

fn g<G>() -> Option<G> {
    f().unwrap().unwrap()
}
```

[This does not](https://play.rust-lang.org/?gist=eb70e71a893d2c60ef0290a5149c6a7c&version=stable&backtrace=0):

``` rust
#![allow(unused)]

fn f<F>() -> Result<Option<F>, ()> {
    panic!()
}

fn g<G>() -> Option<G> where Option<G>: Sized { // <--
    f().unwrap().unwrap()
}
```

**Comment by jonas-schievink** [comment]
Might be related to #24066 (explained in more detail in [this comment](https://github.com/rust-lang/rust/pull/33108#issuecomment-213641152))

**Comment by dtolnay** [comment]
Thanks for filing this! Came up in https://github.com/serde-rs/serde/issues/305.

**Comment by arielb1** [comment]
workaround: explicitly specify type parameters rather than leaving them to inference:
```Rust
#![allow(unused)]

fn f<F>() -> Result<Option<F>, ()> {
    panic!()
}

fn g<G>() -> Option<G> where Option<G>: Sized {
    f::<Option<G>>().unwrap().unwrap()
}

fn main() {}
```

**Comment by bstrie** [comment]
Triage: the given code works when tested on Rust 1.41. Closing.
