### ISSUE TITLE
foo.bar: should expected `:`

### ISSUE THREAD

**Issue by liigo** [rust-lang/rust#33455]
```
use foo.bar; // expected one of `;` or `as`, found `.`
```

Should it expect a `:`?

Full example code:

```
mod foo {
    fn bar() {}
}

fn main() {
    use foo.bar; // expected one of `;` or `as`, found `.`
    bar();
}
```

**Comment by petrochenkov** [comment]
It should expect `::`, but it's lost from the expected set.
I't not an issue specific for `use`, but a symptom of a more general problem with expected token sets.
There's a long weekend ahead, I'll investigate.

**Comment by petrochenkov** [comment]
Oh wait, this works on nightly, as expected (fixed in https://github.com/rust-lang/rust/pull/33044, more specifically).
It means there are no problems with expected token sets.
