### ISSUE TITLE
size hint not taking effect in unzip

### ISSUE THREAD

**Issue by kindlychung** [rust-lang/rust#33468]
See [here](http://stackoverflow.com/questions/37074656/whats-the-purpose-of-sizehint-in-iteratorunzip/37075146#37075146) and [here](https://www.reddit.com/r/rust/comments/4i59b7/whats_the_purpose_of_sizehint_here/)

**Comment by bluss** [comment]
We should simply remove the `SizeHint` hack since it does not follow the rules for a sensible Iterator impl. Specialization can then be used to implement this even better.
