### ISSUE TITLE
Remove `Self: Sized` from `libsyntax::parse::lexer::Read::next_token()` function

### ISSUE THREAD

**Issue by gyscos** [rust-lang/rust#33506]
Commit 6887202ea added the `Self: Sized` bound to the `next_token` function in the `libsyntax::parse::lexer::Reader` trait ([diff here](https://github.com/rust-lang/rust/commit/6887202ea#diff-d06ad31c547d2d94c8b8770006977767R33)).
This bound doesn't seem necessary (it compiles fine without it), but it prevents using this method from a trait object.

Is there any reason for its addition? If not, could we remove it?

**Comment by mitaa** [comment]
That must be a leftover from me trying to make `unwrap_or_abort` take a closure somehow work.. sorry.

https://github.com/rust-lang/rust/pull/33199#issuecomment-214966921

**Comment by Mark-Simulacrum** [comment]
I'm marking this as E-easy because all that needs to be done is to remove `Self: Sized` from [here], I believe.

[here]: https://github.com/rust-lang/rust/blob/2d4ed8e0cbe2c5f3763273a5d8f6b15119473ba7/src/libsyntax/parse/lexer/mod.rs#L76

**Comment by tommyip** [comment]
I would like to take this issue.

**Comment by Mark-Simulacrum** [comment]
Go ahead! Let us know what we can do to help you. You can reach out either here or on IRC (`#rustc` on irc.mozilla.org).
