### ISSUE TITLE
LLVM assertion failure when compiling inline assembly with precise register constraints

### ISSUE THREAD

**Issue by schets** [rust-lang/rust#33503]
``` rust
#![feature(asm)]

unsafe fn cas_tagged(ptr: *const u64, old: (u64, u64), new: u64) -> (u64, u64) {
    let mut val: u64 = old.0;
    let mut counter: u64 = old.1;
    let ncounter: u64 = counter.wrapping_add(1);
    asm!("lock cmpxchg16b ($6)\n\t
          jne Lfail\n\t
          mov $4, $0\n\t
          mov $5, $1\n\t
          .Lfail"
         : "=a"(val), "=d" (val)
         : "0"(val), "1"(counter), "b"(new), "c"(ncounter), "r"(ptr)
         : "memory"
         : "volatile");
    (val, counter)
}
```

results in the llvm failure 

> llvm/lib/IR/InlineAsm.cpp:46: llvm::InlineAsm::InlineAsm(llvm::FunctionType*, const string&, const string&, bool, bool, llvm::InlineAsm::AsmDialect): Assertion `Verify(getFunctionType(), constraints) && "Function type not legal for constraints!"' failed.

When replacing the constraints with "r", the compilation fails claiming that the register names (%5) and (%0) are invalid.

When an identical (sans formatting differences) c++ version is compiled with clang, valid code is generated.
rustc:

> rustc 1.10.0-nightly (d91f8ab0f 2016-05-07)

**Comment by eefriedman** [comment]
```
pub unsafe fn cas_tagged(ptr: *const u64, old: (u64, u64), new: u64) -> (u64, u64) {
    let mut val: u64 = old.0;
    let mut counter: u64 = old.1;
    let ncounter: u64 = counter.wrapping_add(1);
    asm!("lock cmpxchg16b ($6)\n\t
          jne .Lfail\n\t
          mov $4, $0\n\t
          mov $5, $1\n\t
          .Lfail:"
         : "={rax}"(val), "={rdx}" (counter)
         : "0"(val), "1"(counter), "r"(new), "r"(ncounter), "r"(ptr)
         : "memory"
         : "volatile");
    (val, counter)
}
```

Yes, the diagnostics are terrible, but besides that, it seems to be working correctly.

**Comment by levex** [comment]
It doesn't seem to reproduce anymore!

**Comment by Elinvynia** [comment]
I am also unable to reproduce this anymore.

**Comment by Amanieu** [comment]
The issue here is that `"a"`, `"b"`, `"c"`, `"d"` are not valid constraint codes for LLVM's inline asm. You need to use `"{eax}"`, `"{ebx}"`, etc.

This issue does not apply to the new `asm!` ([RFC 2850](https://github.com/rust-lang/rfcs/pull/2850)).

The legacy `llvm_asm!` is deprecated and is no longer maintained.
