### ISSUE TITLE
Implement Clone for all Copy types "by magic"

### ISSUE THREAD

**Issue by DemiMarie** [rust-lang/rust#33507]
This probably needs an RFC, but one solution to the problem of `Copy` not implying `Clone` is to make this happen via compiler magic: the compiler "magically" inserts an implementation of `Clone` for _any_ `Copy` type.

GHC does something similar with `Coercible`.

**Comment by retep998** [comment]
Due to [RFC 1521](https://github.com/rust-lang/rfcs/pull/1521), we're allowed to assume that a `Clone` impl for `Copy` types is trivial and can be optimized out. Having the compiler automatically add trivial `memcpy` `Clone` implementation for all `Copy` types should be safe. As well there shouldn't be a backwards compatibility hazard as it would only allow more code to compile.

**Comment by bstrie** [comment]
Seems a bit magical, is the intent of this simply to allow one to type `#[derive(Copy)]` instead of `#[derive(Copy, Clone)]` ?

**Comment by durka** [comment]
@bstrie also to fix the bug where large arrays are tuples are `Copy` but not `Clone`.

**Comment by drbo** [comment]
@bstrie The latter is actually the main purpose.  Also to fix the ICEs that can result from a type being `Copy` but not `Clone`.

**Comment by sfackler** [comment]
This feels maybe doable with specialization, though I think it might require the lattice rule.

At the moment, we don't want to use specialization in a way that adds functionality that can't exist without it since the feature's unstable.

**Comment by durka** [comment]
I've never seen it tried, but yeah, whenever this comes up in the context
of specialization that seems to be the prevailing wisdom.

AFAIU the proposal here is to do it by magic, to eliminate concerns over
whether specialization is powerful and/or stable enough.

It's a good idea if we want to commit to the fact that large arrays and
tuples WILL be Clone... somehow... eventually. It's a bad idea if we could
contemplate fixing the bug some other way, like by making those types
non-Copy (a breaking change). There are also other ways to fix the bug,
like type-level integers, or even halfway type-level integers that I've
seen proposed (where you can impl for [T; _] but you can't refer to N
directly).

**Comment by retep998** [comment]
>It's a bad idea if we could contemplate fixing the bug some other way, like by making those types non-Copy (a breaking change)

Please no! This would break so much<sup>†</sup>!

<sup>†</sup>Mostly winapi.

**Comment by drbo** [comment]
Yes, the idea here is to do it purely by compiler magic.  My intent is
for the magic to be temporary, and to be removed when it becomes
possible to implement in libcore.
This is similar to the magic typing rules for std::mem::transmute (I
believe that there is no other way to write code that compiles if and
only if two types are the same size).

**Comment by Mark-Simulacrum** [comment]
I'm going to close this issue, since this is not the right place for it. If someone wants to pursue this, please follow the RFC process here https://github.com/rust-lang/rfcs#before-creating-an-rfc.
