### ISSUE TITLE
circular imports with globs

### ISSUE THREAD

**Issue by jesse99** [rust-lang/rust#3352]
Given that a crate is the unit of compilation it seems both silly and annoying to not be able to have modules within a crate use each other.

If, for some reason, this is not fixed then the error message should be. It's currently "failed to resolve imports" which provides essentially no insight into where the problem is. Identifying a circular import given that does not sound like fun at all, especially in a large project where the circular imports could be indirect.

**Comment by frewsxcv** [comment]
Visiting for triage: Can confirm this is still an issue

Rust playpen link: http://is.gd/jvqc02

**Comment by steveklabnik** [comment]
re-nominating, globs are no longer gated

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#889
