### ISSUE TITLE
"value assigned is never used" should point to value, not binding

### ISSUE THREAD

**Issue by sanxiyn** [rust-lang/rust#33536]
People are confused when warning points to binding, because it is often the case that while value assigned is never used, binding is used.

Suggestion found in [users.rust-lang.org thread](https://users.rust-lang.org/t/mystery-value-assigned-is-never-read-warning/5755).

**Comment by birkenfeld** [comment]
Problem is, this is also the case here:
```
let (mut a, b) = tup;
a = 5;
```
Where should we point here?

**Comment by CryZe** [comment]
It should point to `= tup;`. Where else should it point to?

**Comment by CryZe** [comment]
Oh I guess parts of tup could be used, I guess it should just say that the `a` binding is bound to `tup` which it never reads from.

**Comment by Mark-Simulacrum** [comment]
This has since been fixed.

```rust
fn main() {
    let mut a = 10;
    a = 15;
}
```

```
warning: variable `a` is assigned to, but never used
 --> test.rs:2:9
  |
2 |     let mut a = 10;
  |         ^^^^^
  |
  = note: #[warn(unused_variables)] on by default

warning: value assigned to `a` is never read
 --> test.rs:3:5
  |
3 |     a = 15;
  |     ^
  |
  = note: #[warn(unused_assignments)] on by default
```
