### ISSUE TITLE
regression around trait bounds with associated types 

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#33586]
The [following code](https://is.gd/WRzWie) works on stable, but not on the latest master. I believe it is valid.

```rust
trait ParallelIterator {
    type Item;
    fn drive_unindexed<C>(self, consumer: C) -> C::Result
        where C: Consumer<Self::Item>;
}

pub trait Consumer<ITEM> {
    type Result;
}

pub struct Enumerate<M> {
    base: M,
}

impl<M> ParallelIterator for Enumerate<M>
    where M: ParallelIterator,
{
    type Item = (usize, M::Item);

    fn drive_unindexed<C>(self, consumer: C) -> C::Result
        where C: Consumer<Self::Item>
    {
        panic!()
    }
}

fn main() { }
```

On master I get:

```
lunch-box. rustc ~/tmp/reduce.rs
/home/nmatsakis/tmp/reduce.rs:3:5: 4:39 error: the trait bound `C: Consumer<Self>` is not satisfied [E0277]
/home/nmatsakis/tmp/reduce.rs:3     fn drive_unindexed<C>(self, consumer: C) -> C::Result
                                    ^
/home/nmatsakis/tmp/reduce.rs:3:5: 4:39 help: run `rustc --explain E0277` to see a detailed explanation
/home/nmatsakis/tmp/reduce.rs:3:5: 4:39 help: consider adding a `where C: Consumer<Self>` bound
/home/nmatsakis/tmp/reduce.rs:20:5: 24:6 error: the trait bound `C: Consumer<Enumerate<M>>` is not satisfied [E0277]
/home/nmatsakis/tmp/reduce.rs:20     fn drive_unindexed<C>(self, consumer: C) -> C::Result
                                     ^
/home/nmatsakis/tmp/reduce.rs:20:5: 24:6 help: run `rustc --explain E0277` to see a detailed explanation
/home/nmatsakis/tmp/reduce.rs:20:5: 24:6 help: consider adding a `where C: Consumer<Enumerate<M>>` bound
error: aborting due to 2 previous errors
```

**Comment by nikomatsakis** [comment]
(This affects the latest Rayon.)

**Comment by nikomatsakis** [comment]
Note that the error messages are talking about `Consumer<Self>`.

**Comment by nikomatsakis** [comment]
Really this is enough to show the problem:

```rust


trait ParallelIterator {
    type Item;
    fn drive_unindexed<C>(self, consumer: C) -> C::Result
        where C: Consumer<Self::Item>;
}

pub trait Consumer<ITEM> {
    type Result;
}

fn main() { }
```

**Comment by nikomatsakis** [comment]
This DOES compile, which gives a pretty good clue:

```rust
trait ParallelIterator {
    type Item;
    fn drive_unindexed<C>(self, consumer: C) -> <C as Consumer<Self::Item>>::Result
        where C: Consumer<Self::Item>;
}

pub trait Consumer<ITEM> {
    type Result;
}

fn main() { }
```

**Comment by nikomatsakis** [comment]
cc @eddyb any PRs that you've seen whih might affect how `C::Result` is resolved?

**Comment by metajack** [comment]
This is blocking a Servo upgrade of rustc currently. We seem to be stuck around 2016-05-07 until this is fixed.

**Comment by nikomatsakis** [comment]
Seems likely to be a problem in the resolve refactoring. Basically the `Self::Item` in `Consumer<Self::Item>` gets translated to `Self`.

cc @jseyfried the problem seems to lie in resolve

**Comment by nikomatsakis** [comment]
never mind, I think the problem is in astconv

**Comment by eddyb** [comment]
Got to love nondescript [cleanup commits](https://github.com/rust-lang/rust/commit/0dd0925f5777122460ee84acf0b6dae76b58b25a#diff-1b4d50b82a87f1031cd5f99b64123de7L1211).
This broke saving the final `Def`, which was completely hidden by the `ast_ty_to_ty_cache`, until I removed that recently.
It wasn't a problem with expression paths because those don't use the resulting `Def` for anything and instead insert their own resolved method or associated constant `Def`.

**Comment by alexcrichton** [comment]
I've also noticed that [this crate fails on the current nightly](https://travis-ci.org/alexcrichton/futures-rs/builds/129780635) for presumably similar reasons
