### ISSUE TITLE
rustdoc regression: missing type parameters for impls of generic traits

### ISSUE THREAD

**Issue by mbrubeck** [rust-lang/rust#33592]
In the list of impls for a trait with type parameters, for example:

http://doc.rust-lang.org/nightly/std/convert/trait.AsRef.html#implementors

The impls currently appear like `impl<T> AsRef for [T]`

They should appear like `impl<T> AsRef<[T]> for [T]`

This is a regression from Rust 1.9 beta to Rust 1.10 nightly.

**Comment by alexcrichton** [comment]
cc @mitaa, ring any bells?

**Comment by ollie27** [comment]
It was caused by #32558, I'm working on a fix.

**Comment by alexcrichton** [comment]
Thanks @ollie27!
