### ISSUE TITLE
Cross compiling from windows to linux-musl

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust#33608]
It works! Almost.

`rustc` passes an additional library to the linker `-lutils`, which doesn't exist in the musl std package, and doesn't seem to be required. With that library removed, cross compiling to linux works out of the box with rustup (assuming you can obtain an elf linker...).

**Comment by sanmai-NL** [comment]
Do you propose to remove that linker option? May seem obvious, but you didn't state that.

**Comment by Diggsey** [comment]
Well I was hoping that someone could tell me whether `utils` is required for musl builds, or if its presence in the linker flags is a mistake.

Having looked into it, it seems to be the case that `libutils` for musl is just an empty library, but is still required in case we're linking with C code which expects to be able to link to it, so probably we should be including `libutils` as part of the rust package.

**Comment by alexcrichton** [comment]
Added in https://github.com/rust-lang/libc/pull/246 by accident I fixed in https://github.com/rust-lang/libc/pull/287 but we unfortunately can't update until https://github.com/rust-lang/libc/pull/291 lands (but hopefully that'll be soon!)
