### ISSUE TITLE
Support per-stage RUSTFLAGS in rustbuild.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#33609]
Right now rustbuild invokes cargo which wants to rebuild the world if it sees a different `RUSTFLAGS` value, while my workflow involves changing `RUSTFLAGS` just to test stage1+ with `-Z orbit`.

It would be nice to have passing `--stage1-rustflags "-Z orbit"` to the python script (or the environment variable `RUSTFLAGS1="-Z orbit") just work.

Currently the Makefiles have something similar but it doesn't actually work for `compiletest`, just `rustc`.

**Comment by apaprocki** [comment]
Did rustbuild ever get support for this? This appears to also be breaking `chroot` builds that need to pass per-stage `sysroot` values.

**Comment by Mark-Simulacrum** [comment]
I'm going to unassign @alexcrichton from this; I think others should be able to implement this and as far as I know they don't have any particular concern with this specific bug.

**Comment by Mark-Simulacrum** [comment]
We support this via `RUSTFLAG_STAGE_NOT_0` and `RUSTFLAGS_STAGE_0` set in the environment today.

**Comment by eddyb** [comment]
@Mark-Simulacrum I wonder if we should switch to `RUSTFLAGS_BOOTSTRAP` and `RUSTFLAGS_NOT_BOOTSTRAP`.

**Comment by Mark-Simulacrum** [comment]
That would make sense, I'll reopen to track that.
