### ISSUE TITLE
HashMap::extend_with() to handle collisions

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#33618]
HashMap provides a `extend` method, but that does not allow for handling the cases where key exists both in the hashmap and the iterator.

**Comment by apasel422** [comment]
I'd actually like to see an RFC for handling duplicate keys in general. The set types had rust-lang/rfcs#1194, but the map stuff was punted.

**Comment by dtolnay** [comment]
I believe this is going to require an [RFC](https://github.com/rust-lang/rfcs/blob/master/libs_changes.md). Some things to cover:

- Concrete use cases that involve extending a HashMap with potentially duplicated keys, needing to handle those duplicates somehow.
- Proposed API for `extend_with`.
- What are the current workarounds without `extend_with`, and how `extend_with` improves upon them.
- How this could be generalized to other map types, or even other collection types that are not maps.
