### ISSUE TITLE
Calling Trait methods after unwrapping &NamedTuple<Trait> segfaults

### ISSUE THREAD

**Issue by marcianx** [rust-lang/rust#33614]
This came up in https://users.rust-lang.org/t/dst-receivers-idempotent-unsize/5780 as I was trying to understand what `&NamedTuple<Trait>` actually means and how to use it.

My attempt to unwrap it to invoke the trait method segfaulted.

```rust
trait Trait { fn foo(&self) -> i32; }

impl Trait for i32 { fn foo(&self) -> i32 { *self } }

struct Wrapper<A: ?Sized + Trait>(A);

fn main() {
    let sized = Wrapper(42i32);
    let wrapped = &sized as &Wrapper<Trait>;

    // SEGFAULTS!
    match wrapped {
        &Wrapper(ref num) => println!("foo() = {:?}", (num as &Trait).foo())
    }
}
```
([playground](https://play.rust-lang.org/?gist=86bb17d4d58bd22edb6bbdb7525da47a&version=stable&backtrace=0))

**Comment by durka** [comment]
On nightly you get an LLVM assertion.

**Comment by marcianx** [comment]
To state the obvious, in case it isn't (since I wrote the code like this the first time because `&Wrapped<T> as &Wrapped<Trait>` is a very strange and new concept for me): the workaround is to reference the field directly via `wrapped.0` instead of doing a `match` on it.

**Comment by arielb1** [comment]
Fixed with MIR, and IIRC also on my `slice_patterns` branch.
