### ISSUE TITLE
rustdoc: Incorrect indentation for code boxes inside list items

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust#33621]
`````` rust
/// Does things.
///
/// # Example
///
/// ```rust
/// fn main() {
/// 1234
///     foo();
/// }
/// ```
pub fn foo() {}

/// Also does things.
///
/// - For example:
///
///   ```rust
///   fn main() {
///   1234
///       bar();
///   }
///   ```
pub fn bar() {}
``````

Rendered code box for foo:
![](http://i.imgur.com/xWWQ1eE.png)

Rendered code box for bar:
![](http://i.imgur.com/N8Yr360.png)

**Comment by steveklabnik** [comment]
Triage: I'm not entirely sure what the original bug is about, to be honest, but rustdoc follows the commonmark spec here. I double checked its output against the [dingus](https://spec.commonmark.org/dingus/). 

@crumblingstatue I'm going to give this a close as "working as intended", but please let me know if you have more context here!
