### ISSUE TITLE
Always use LLVM from last release's librustc_llvm.so.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#33623]
There is no reason anyone has to rebuild LLVM for local builds, we can backport all LLVM changes to beta and then reuse the previous `librustc_llvm-*.so` as a LLVM library package, as it contains all of the symbols you want (plus some insignificant amount of Rust functions).

This could lower the first contribution overhead for many people, alongside `NO_REBUILD` for rustbuild, e.g. changing just `libstd` shouldn't need to recompile the compiler to run a bunch of tests on it, _unless_ you are changing and/or testing the compiler, but that's a different feature.

cc @alexcrichton

**Comment by alexcrichton** [comment]
I'd want to think through the process of updating LLVM, but otherwise sounds plausible to me!

**Comment by marinintim** [comment]
@alexcrichton: is this issue stalled?

**Comment by alexcrichton** [comment]
@marinintim yes, I suspect that we won't be able to do this as it is infrastructurally very complicated

**Comment by steveklabnik** [comment]
Triage: as far as I know, this has not been done.

**Comment by workingjubilee** [comment]
A variety of tiny little LLVM patches actually wind up cherry-picked often enough, especially around releases, that this was probably always going to be a non-starter. However, with download-ci-llvm we have the "next best thing", of using a very recent LLVM build from CI, which indeed seems to lower new contributor overhead considerably. I believe the intended goal, albeit not the designed solution, of this issue has been satisfied. Thus, I am closing it. If you believe there is some additional gain worth pursuing here, please feel free to reopen this again, Eddy.
