### ISSUE TITLE
`..` in tuple-like patterns (tracking issue for RFC 1492)

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#33627]
Tracking issue for rust-lang/rfcs#1492

**Comment by petrochenkov** [comment]
I'll rebase https://github.com/rust-lang/rust/pull/32079 this weekend.

**Comment by petrochenkov** [comment]
I don't see neither anything preventing stabilization of this feature, nor strong motivation to stabilize it immediately.
`..` currently works in beta (1.11) and nightly (1.12), I suggest to stabilize it in in 1.13 (the next cycle), unless someone want it sooner or has reservations.

**Comment by nikomatsakis** [comment]
@rfcbot fcp

This is a small feature that does not interact with no known interactions with other things or bugs. I propose we move to stabilize it.

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

I propose that we **stabilize** this feature. There are no known blockers or interactions and it is a minor extension to existing syntax.

**Comment by aturon** [comment]
:bell: This feature is undergoing its **final comment period** with disposition to **stabilize** :bell:

**Comment by nikomatsakis** [comment]
The release is coming up, and this has not exactly been a controversial topic, so we've decide to make it official and approve this for stabilization.
