### ISSUE TITLE
doc: mark str representation example as "don't actually do this"

### ISSUE THREAD

**Issue by birkenfeld** [rust-lang/rust#33637]
The example [here](https://doc.rust-lang.org/std/primitive.str.html#representation) led to some confusion how to get a slice from a `Vec<u8>`: https://users.rust-lang.org/t/checking-for-incoming-data-on-tcpstream/5814/7

The example code should probably be flagged as "don't do this in practice, this is just to show the innards".

**Comment by steveklabnik** [comment]
I am willing to mentor anyone who wants to fix this

**Comment by JessRudder** [comment]
@steveklabnik I'm looking to do my first open source commit and this seems handleable. :)  Should I follow the instructions for documentation in the contributing.md and see how far I can get on this?

**Comment by steveklabnik** [comment]
@JessRudder yup! If you need any specific help, leave a comment or drop by IRC :)

**Comment by kyrias** [comment]
(This should be closed now.)
