### ISSUE TITLE
Mixed absolute-relative import is allowed in use delcaration

### ISSUE THREAD

**Issue by matklad** [rust-lang/rust#33636]
This compiles, though it probably should not:

```Rust
use ::self::foo::bar;

mod foo {
    pub fn bar() {}
}

fn main() {}
```

**Comment by petrochenkov** [comment]
This was fixed in https://github.com/rust-lang/rust/pull/32403, however it's temporarily reported as a warning for backward compatibility.

**Comment by matklad** [comment]
Ah yes, I should have checked this on nightly, thanks!
