### ISSUE TITLE
Filter crater failures by timeout / compiler error / LLVM assertion.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#33638]
We could be missing out on huge bugs just because they aren't obvious regressions.
And on the other hand, timeouts just fudge the stats without being relevant most of the time.

cc @brson @nikomatsakis (not sure if this should go on crater repo - is there one?)

**Comment by brson** [comment]
https://github.com/brson/taskcluster-crater is the crate repo. It does probably belong there, not that anyone would ever see it.

**Comment by Mark-Simulacrum** [comment]
Discussed in infra team meeting. Moved to cargobomb's repo: https://github.com/brson/cargobomb/issues/7.
