### ISSUE TITLE
Strange result for constant expression: (!0 ^ (!0 >> 1) + !0) as <Integral>

### ISSUE THREAD

**Issue by glasswings** [rust-lang/rust#33641]
`rustc` compiles this expression to `1` for all primitive integral types without warning unless the type of the literal `0` is explicitly annotated.  With explicit annotation the addition overflows.

C-compatible unsigned types would evaluate to `0x7Fu8`, `0x7FFFu16`, etc.

**Comment by nagisa** [comment]
The `!0` is a `-1i32`. I agree that it is surprising shift has no effect on signed integers and nobody noticed it so far…?!

```
(!0i32) >> 0 = ffffffff
(!0i32) >> 1 = ffffffff
(!0i32) >> 2 = ffffffff
(!0i32) >> 3 = ffffffff
(!0i32) >> 4 = ffffffff
(!0i32) >> 5 = ffffffff
(!0i32) >> 6 = ffffffff
(!0i32) >> 7 = ffffffff
(!0i32) >> 8 = ffffffff
(!0i32) >> 9 = ffffffff
(!0i32) >> 10 = ffffffff
(!0i32) >> 11 = ffffffff
(!0i32) >> 12 = ffffffff
(!0i32) >> 13 = ffffffff
(!0i32) >> 14 = ffffffff
(!0i32) >> 15 = ffffffff
(!0i32) >> 16 = ffffffff
(!0i32) >> 17 = ffffffff
(!0i32) >> 18 = ffffffff
(!0i32) >> 19 = ffffffff
(!0i32) >> 20 = ffffffff
(!0i32) >> 21 = ffffffff
(!0i32) >> 22 = ffffffff
(!0i32) >> 23 = ffffffff
(!0i32) >> 24 = ffffffff
(!0i32) >> 25 = ffffffff
(!0i32) >> 26 = ffffffff
(!0i32) >> 27 = ffffffff
(!0i32) >> 28 = ffffffff
(!0i32) >> 29 = ffffffff
(!0i32) >> 30 = ffffffff
(!0i32) >> 31 = ffffffff
```
[this](https://play.rust-lang.org/?gist=af0f513ab1d6e14d1697c4136397827c&version=nightly&backtrace=0).

**Comment by Diggsey** [comment]
@nagisa Right shift on negative numbers is behaving exactly as expected. It *does* have an affect, it's just that with signed numbers, the new bit shifted in from the left will be the same as the sign bit.

`1` is the correct answer for signed integers, because:
```
(!0 ^ (!0 >> 1) + !0)
= (-1 ^ (-1 >> 1) + -1)
= (-1 ^ -1 + -1)
= (-1 ^ -2)
= 1
```

**Comment by glasswings** [comment]
Ah, precedence explains it.  Thanks.
