### ISSUE TITLE
Insufficient arguments error E0061 & E0050 would be more helpful if it printed what arguments are needed

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust#33649]
When I call a function with insufficient arguments, rustc just says the number of arguments is wrong. 

> <anon>:4:5: 4:26 error: this function takes 1 parameter but 0 parameters were supplied [E0061]
> <anon>:4     std::fs::File::open();
>              ^~~~~~~~~~~~~~~~~~~~~

This would be much more helpful if it said which arguments, and what they are, e.g.:

> error: The `path` argument was not supplied to the `open` function

or at least show the funcition definition in a note:

> <anon>:4:5: 4:26 error: this function takes 1 parameter but 0 parameters were supplied [E0061]
> <anon>:4     std::fs::File::open();
> note: `fn open<P: AsRef<Path>>(path: P) -> Result<File>`

Similar problem applies to E0050 ("error: method `foo` has 1 parameter but the declaration in trait `bar` has 2").

----

rustc 1.10.0-nightly (2b79e05a0 2016-05-13)

**Comment by GuillaumeGomez** [comment]
Showing which parameter isn't supplied is quite difficult. It could be any and rustc should guess what argument you forgot between all arguments. Quite difficult.

However, showing the function definition in a note seems a nice idea.

**Comment by jonas-schievink** [comment]
@GuillaumeGomez the function definition might be in another crate, so you'd have to reconstruct it from metadata.

**Comment by pornel** [comment]
@GuillaumeGomez I think it'd be sufficient to list remaining arguments only (if I supplied 3, but 5 are required, show last 2). That's because if I got order of arguments wrong, it'll hopefully be picked by type checker, and that's a different error. Listing names (and types) of all arguments would be OK too.

**Comment by GuillaumeGomez** [comment]
> @GuillaumeGomez I think it'd be sufficient to list remaining arguments only (if I supplied 3, but 5 are required, show last 2). That's because if I got order of arguments wrong, it'll hopefully be picked by type checker, and that's a different error. Listing names (and types) of all arguments would be OK too.

Like I said, how do rustc can guess if you entered the 3 first or the 3 last? Or that they're even in the good order?

> @GuillaumeGomez the function definition might be in another crate, so you'd have to reconstruct it from metadata.

That was just a guess. :wink:

**Comment by sanmai-NL** [comment]
Could you also add the Rust version info here to your post? You'll help to make this issue tracker a more useful archive/reference in the future.

**Comment by pornel** [comment]
Thank you @estebank for fixing this :)
