### ISSUE TITLE
internal compiler error: const expr(10: &*"sth") of type &'static str has size 8 instead of 16

### ISSUE THREAD

**Issue by thiolliere** [rust-lang/rust#33648]
I raise an internal compiler error on play.rust-lang.org stable beta and nightly and on my machine.

I tried this code:

```rust
fn main() {
    let _ = &*"sth";
}
```

I expect no error even if I would write it differently.
instead I got `error: internal compiler error: const expr(10: &*"sth") of type &'static str has size 8 instead of 16`

**Comment by zackmdavis** [comment]
Doesn't seem to reproduce anymore?

```
$ rustc --version
rustc 1.14.0-nightly (a3bc191b5 2016-10-10)
$ cat scratch.rs 
fn main() {
    let _ = &*"sth";
}
$ rustc scratch.rs 
$ echo $?
0
```

**Comment by TimNN** [comment]
Indeed, this seems to be fixed also on stable & beta, and there was a regression test added in #35533.
