### ISSUE TITLE
f32 and f64 missing from std::str::FromStr doc page

### ISSUE THREAD

**Issue by marcianx** [rust-lang/rust#33646]
At the bottom of https://doc.rust-lang.org/std/str/trait.FromStr.html, it lists all the types that have implementations of `FromStr`. `f64` and `f32` seem to be missing even though the implementations exist. A search for `FromStr` also does not bring up the floating point variation either. Nevertheless, [ParseFloatError](https://doc.rust-lang.org/std/num/struct.ParseFloatError.html) exists (I guessed its name based on ParseIntError, and it was findable via search), and it mentions the existence of a `FromStr` implementation for the floating point types.

**Comment by birkenfeld** [comment]
This is fixed, likely by 6100b70b98ee090c9b8e7b4788e4513e64fcc3ff, in nightly.

**Comment by rkruppe** [comment]
Sounds like #31948

**Comment by marcianx** [comment]
This seems to be fixed now.
