### ISSUE TITLE
Inference rules changed on 1.10 nightly

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust#33657]
```Rust
struct Foo;
struct Bar;

fn foo_ref_to_bar_ptr(foo: &Foo) -> *const Bar {
	foo as *const _ as _
}

```

This builds on 1.10 nightly, but inference fails on beta and stable.

If this is a desired change, it should probably be documented, and regression tests added.
If not, it should be made into an error.

**Comment by arielb1** [comment]
This is a desired change, and which I am quite sure has a regression test.

**Comment by nagisa** [comment]
Seems like something we want in relnotes, thus, in order to be on the safe side, adding the label.

**Comment by nagisa** [comment]
@arielb1 do you know which PR made the change?

**Comment by arielb1** [comment]
Found it - #32258

**Comment by nagisa** [comment]
Thanks @arielb1

**Comment by crumblingstatue** [comment]
@brson Is this really a regression? As far as I understand, it strictly allows more code to compile, and doesn't break old code.

The reason I opened this issue is because this seemed like an undocumented change.

**Comment by arielb1** [comment]
not a regression.
