### ISSUE TITLE
Trait implementations should show summary line in documentation

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#33672]
We've always been unsure how much information to show about implementations, and right now, we only show signatures. [On HN](https://news.ycombinator.com/item?id=11708981) someone suggested that including the summary line would be helpful, so that you can understand what these things actually do, if you haven't used that particular trait before.

**Comment by Manishearth** [comment]
Perhaps we should somehow link to the full description? With a [read more]-like link

**Comment by AndrewBrinker** [comment]
Reducing the amount of link chasing necessary to understand what a function does sounds like a good idea, and I agree with @Manishearth that a "read more" link should be included. The question then is how much of the description to include. First sentence? Some arbitrary number of characters?
