### ISSUE TITLE
Test harness is injected on `--cfg test`

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#33670]
Cargo has an issue (https://github.com/rust-lang/cargo/issues/2305) with a proposed fix (https://github.com/rust-lang/cargo/pull/2469), but it unfortunately can't land because the compiler currently considers `--test` and `--cfg test` synonymous.

I'm... surprised by this behavior, and I'd expect `--cfg test` to *only* pass the `test` cfg.

**Comment by alexcrichton** [comment]
Ah, and the steps to reproduce:

```
$ touch bar.rs
$ rustc --cfg test bar.rs
$ ./bar

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

```

**Comment by sanxiyn** [comment]
I looked at the history. Originally, test harness was only injected for `--test`, not for `--cfg test`. Then b808eab (in 2012!) explicitly changed this, with comments (but without rationale...). Fix seems to be a matter of reverting that commit.
