### ISSUE TITLE
Autoref finds by-value methods from implementations for &T

### ISSUE THREAD

**Issue by ubsan** [rust-lang/rust#33697]
In my opinion, this should not happen, and is a bug.

```rust
trait Doop { fn doop(self); } 
impl<'a> Doop for &'a i32 { fn doop(self) { println!("doop"); } } 
0i32.doop()
```
And the actual problem with backwards compatibility:
```rust
impl<'a, T> IntoIterator for &'a [T] {
  fn into_iter(self) { /* ... */ }
}
for x in [0, 1, 2].into_iter() {
  println!("{}", x);
}
```
With this in the language, we cannot implement into_iter for arrays (and also breaks any time someone has a method for &mut T, and then adds a method with the same name for &T).

**Comment by durka** [comment]
I think this is done on purpose, so that `for x in &vec {}` is the same as `for x in vec.iter() {}` and so on.

**Comment by ubsan** [comment]
@durka That's not the same thing. `.iter` is a method on `Vec`, so it's fine to call. The issue is calling something from `&Vec` when you have a `Vec`.

**Comment by ubsan** [comment]
Note that it doesn't find reference methods (i.e., those that take self by reference).

**Comment by ubsan** [comment]
It checks for &T before checking for &mut T, but they both work the same way, and it *must* be a by-value method.

cc @nikomatsakis

**Comment by ubsan** [comment]
cc @scott @eddyb

**Comment by arielb1** [comment]
@ubsan

It quite intentionally does not care about by-reference vs. by-value. It finds methods whose receiver is  `&Self`, then `&mut Self`, then `Self`.

**Comment by arielb1** [comment]
Saying that this makes adding `into_iter` to arrays a breaking change is a bit fallacious, because fixing this bug will result in that code breaking just the same.

BTW, we intentionally allow ourselves to make changes that break inference like that
> Some details of type inference may change. For example, we expect to implement the fallback mechanism described in RFC 213, and we may wish to make minor changes to accommodate overloaded integer literals. In some cases, type inferences changes may be better handled via explicit opt-in.

**Comment by arielb1** [comment]
> and it *must* be a by-value method.

What else could it be? static methods don't have a receiver, and therefore it does not look for them (id. associated constants). Method receivers must be of the form `&Self`, `&mut Self`, `Self` or `Box<Self>`, otherwise you get an error.

In fact, we kind-of want to remove the latter restriction and allow receivers to be anything (e.g. `&Rc<Self>`). Then it would also match them.

**Comment by ubsan** [comment]
@arielb1 No, not that. Read the first example again. by-value means "takes self, not &self or &mut self or self: Box<Self>". You are able to call methods for a type that doesn't implement them.

**Comment by arielb1** [comment]
@ubsan 

See how this works: `<&'a i32>::doop` is an associated function of `<&'a i32>` with type `fn(&'a i32)`. Because it was declared with a `self`, it is an instance method (we need to come up with a better name) - the type of the receiver is `&'a i32`.

When we look up something like `(4).doop();`, it looks for an instance method with receiver types `&i32`, `&mut i32`, and `i32`, and it finds one on the first try.

**Comment by arielb1** [comment]
EDIT: got the order wrong, the order is `i32`, `&i32`, `&mut i32`. Doesn't matter here, because there is no ambiguity.

**Comment by ubsan** [comment]
@arielb1 Yes there is an ambiguity... You can implement something for both `&T` and `&mut T`. Then it'll only find the `&T` one.

That is a really, really... not good way of finding these, IMO,

**Comment by ubsan** [comment]
@arielb1 You pinged me on IRC when I was asleep. This isn't a good feature. I will not be implementing this in the rust compiler that I'm writing, if you want it to be a rustc specific extension that's fine, but it's really, really stupid. I can't say it nicer than that. Allowing me to call `into_iter` on types that don't implement it by turning it into a type that does is a bug in the implementation, no matter how intentional it is.

**Comment by bluss** [comment]
I'll register my thought here that `[1, 2, 3].into_iter()` should call the existing `&[T; 3]` impl for `IntoIterator` regardless, so there is nothing won for arrays in practice by fixing this issue.

**Comment by ubsan** [comment]
Alright, I got explained why this is a feature and not a bug. I still don't think it's correct, but I'm not upset anymore. I'm sorry for getting upset, all. I'm going to write an RFC to try to change it.
