### ISSUE TITLE
Bencher example from documentation does not compile if copied via playpen

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust#33700]
On this page I've clicked "Run" on the example:

https://doc.rust-lang.org/book/benchmark-tests.html

but because playpen doesn't use `cfg(test)`, I've [copied the code from playpen](https://is.gd/BnhJEZ) and ran locally with `cargo bench`, and got these errors:

> error: unresolved import `test::Bencher`. Did you mean `<opaque>::test`? [--explain E0432]
>   --> src/lib.rs:13:13
> 13 |>         use test::Bencher;
>    |>             ^^^^^^^^^^^^^
> 
> error: unresolved name `add_two` [--explain E0425]
>   --> src/lib.rs:17:27
> 17 |>             assert_eq!(4, add_two(2));
>    |>                           ^^^^^^^
> src/lib.rs:17:27: 17:34: note: in this expansion of assert_eq! (defined in &lt;std macros>)
> 
> error: unresolved name `add_two` [--explain E0425]
>   --> src/lib.rs:22:23
> 22 |>             b.iter(|| add_two(2));
>    |>                       ^^^^^^^
> 
> error: aborting due to 3 previous errors

---

rustc 1.10.0-nightly (2b79e05a0 2016-05-13)
binary: rustc
commit-hash: 2b79e05a05f7259891adc4d7b0487d44121eb0c1
commit-date: 2016-05-13
host: x86_64-apple-darwin
release: 1.10.0-nightly

---

The example for reference: https://is.gd/BnhJEZ

Initially I haven't noticed that Rust playpen _has modified the example code_ and added `fn main()`, which made the example invalid.

**Comment by durka** [comment]
This must be due to `extern crate` not being always public anymore?

**Comment by birkenfeld** [comment]
How are you compiling it? Works fine for me with rustc 1.10.0-nightly (cd6a40017 2016-05-16), using `cargo bench` and `rustc --cfg test`.

**Comment by pornel** [comment]
I'm running `cargo bench`. I've installed nightly via rustup.

**Comment by durka** [comment]
@pornel which nightly is it? (`rustc -V`)

**Comment by durka** [comment]
Seems to work also with nightly-2016-05-17. And it also works with the 5/13 version cited above for me. @pornel are you sure that's the version and code you're running?

**Comment by pornel** [comment]
I've noticed that I've used playpen to copy&paste the code, and playpen made the example invalid. I've updated the issue.

**Comment by steveklabnik** [comment]
This works today; it sounds more like a playpen bug anyway. Regardless, I'm going to give it a close, since it works. Thanks!
