### ISSUE TITLE
Make 'index out of bounds' a compile-time error

### ISSUE THREAD

**Issue by nkaretnikov** [rust-lang/rust#33701]
Started reading The Book yesterday and this puzzled me. From https://doc.rust-lang.org/book/primitive-types.html: "Arrays have type [T; N]. [...] The N is a compile-time constant, for the length of the array." But the following code doesn't produce a compile-time error. Can this be changed? FWIW, there are even some issues caused by the current behavior on this issue tracker.

% cat src/main.rs:
```rust
fn main() {
  let xs = [1,2,3];
  println!("out of bounds: {}", xs[3]);
}
```

```
% cargo build
   Compiling array-bounds v0.1.0 (file:///home/nikita/rust/array-bounds)
% cargo run
     Running `target/debug/array-bounds`
thread '<main>' panicked at 'index out of bounds: the len is 3 but the index is 3', src/main.rs:3
Process didn't exit successfully: `target/debug/array-bounds` (exit code: 101)
```

**Comment by Manishearth** [comment]
This can't be done as a compile time error since it's a breaking change. It could be added as a lint, but Rust isn't accepting new lints at the moment.

It does exist as a lint in clippy, though: https://github.com/Manishearth/rust-clippy/wiki#out_of_bounds_indexing

**Comment by Manishearth** [comment]
(closing since we usually close lint issues that have a lint in clippy.)

**Comment by nkaretnikov** [comment]
@Manishearth Are you saying that Rust will never adopt a feature if it's a breaking change?

**Comment by Manishearth** [comment]
Mostly, yes. There are caveats, in that Rust 2.0 may contain breaking changes, and  certain breaking changes to fix correctness bugs are also ok. But something like this is not really in those categories.

**Comment by nkaretnikov** [comment]
> But something like this is not really in those categories.
I disagree. Who do I need to talk to for it to be considered for 2.0?

**Comment by Manishearth** [comment]
I suggest you bring it up on https://internals.rust-lang.org. You'd need to also make an RfC.

**Comment by Manishearth** [comment]
Btw, I didn't say it doesn't make sense for Rust 2.0, I said it doesn't make sense as a breaking change now. This sounds like something that might be fine for Rust 2.0 (but Rust 2.0 is quite far in the future)

**Comment by nkaretnikov** [comment]
@Manishearth https://internals.rust-lang.org/t/make-index-out-of-bounds-a-compile-time-error/3489

**Comment by anguslees** [comment]
@Manishearth: Isn't this only a breaking change, if code is actually broken by it?

In this particular case, I think you're suggesting that there's some code out there that can statically be demonstrated to contain a run-time failure, and that the number of such cases is significant enough that we don't want to introduce the proposed compile-time failure.  Given the nature of the error, I suspect that there are *not* a significant number of such cases - would we be ok accepting such a change provided crator indicated that it had no effect on existing published crates?

**Comment by Manishearth** [comment]
Perhaps. Though there is the case of code that never runs causing this issue (e.g. when cfg is involved)

Even for crater runs, breaking changes have been made carefully and never to add new non-soundess error cases. You'd have to convince everyone the value of this as an error that is not achieved by the existing clippy lint or a lint in rustc. So far, nobody has.
