### ISSUE TITLE
Unclear match example explanation?

### ISSUE THREAD

**Issue by mark-summerfield** [rust-lang/rust#33715]
This is copied from: https://github.com/rust-lang/book/issues/103#issuecomment-220038714 as requested:

In https://doc.rust-lang.org/book/match.html it shows this example:

```rust
let x = 5;

match x {
    1 => println!("one"),
    ... // elided lines
    _ => println!("something else"),
}
```

And in the explanation afterwards it says:

> The compiler infers from x that it can have any positive 32bit value; for example 1 to 2,147,483,647.

But earlier in the book it says that x will be of inferred type i32 (i.e., signed), in which case shouldn't the above say "any 32 bit value from −2,147,483,648 to 2,147,483,647"?

**Comment by apasel422** [comment]
You're right. Feel free to submit a PR.

**Comment by apasel422** [comment]
This was also fixed in the nightly docs.
