### ISSUE TITLE
Incorrect variable name in the text

### ISSUE THREAD

**Issue by mark-summerfield** [rust-lang/rust#33717]
This is copied from https://github.com/rust-lang/book/issues/101#event-664521001 as requested:

In https://doc.rust-lang.org/book/ownership.html in the The Details subsection it has this code snippet:

```rust
let v = vec![1, 2, 3];

let mut v2 = v;
```

But in the text following the `v2.truncate(2)` snippet, it mentions v1 which doesn't exist. I think the v1's should be replaced by plain v.

**Comment by apasel422** [comment]
Agreed. Feel free to submit a PR for this.

**Comment by mark-summerfield** [comment]
Sorry, I don't know how to do a PR (pull request?); I am a mercurial user and not very familiar with github.

**Comment by apasel422** [comment]
Yes, a pull request. (Sorry for using the abbreviation.) You can navigate to the appropriate file in https://github.com/rust-lang/rust/tree/master/src/doc/book and click the "Edit" button, which should guide you through the process. See also https://help.github.com/articles/editing-files-in-your-repository/.

**Comment by mark-summerfield** [comment]
I did that but someone has already fixed it.

**Comment by apasel422** [comment]
I will close this issue then. It was indeed fixed in the nightly docs: http://doc.rust-lang.org/nightly/book/ownership.html.
