### ISSUE TITLE
Confusing texts in Variable Bindings

### ISSUE THREAD

**Issue by mark-summerfield** [rust-lang/rust#33718]
This is copied from https://github.com/rust-lang/book/issues/100#issuecomment-220040899 as requested:

I have just started reading the Rust Book online. In the Variable Bindings section's Patterns subsection it says:

> This means we can do things like:
let (x, y) = (1, 2);
After this expression is evaluated, x will be one, and y will be two.

This is confusing! I think the second sentence should be:

> After this expression is evaluated, x will be 1, and y will be 2.

The same problem occurs in the following Type Annotations subsection which says:

> let x: i32 = 5;
If I asked you to read this out loud to the rest of the class, you’d say “x is a binding with the type i32 and the value five.”

Again, I think spelling the numbers is confusing and the sentence should be:

> If I asked you to read this out loud to the rest of the class, you’d say “x is a binding with the type i32 and the value 5.”

There may be more occurrences, but if so I won't report them on the assumption that you'll either change none of them if you disagree with me or change them all.

I know that publishers recommend spelling out low numbers, but IMO this is not a good idea in a computer textbook where clarity is more important than purity.

**Comment by steveklabnik** [comment]
As I mentioned over there, this one is intentional. https://github.com/rust-lang/book/issues/100#issuecomment-220052183 Thanks though!

**Comment by mark-summerfield** [comment]
On Wed, 18 May 2016 10:12:58 -0700
Steve Klabnik <notifications@github.com> wrote:
> As I mentioned over there, this one is intentional.
> https://github.com/rust-lang/book/issues/100#issuecomment-220052183
> Thanks though!

Yes, but confusing. I think clarity is more important than a publisher's
guideline that was never intended for computer textbooks. But it's your
call of course:-)

-- 
Mark Summerfield, Qtrac Ltd.
    DiffPDF for Windows - PDF comparison tool
        http://www.qtrac.eu/diffpdf.html
