### ISSUE TITLE
Move ARM Linux support to Tier 1

### ISSUE THREAD

**Issue by mmatyas** [rust-lang/rust#33714]
Currently the following ARM Linux targets are in [Tier 2](https://doc.rust-lang.org/nightly/book/getting-started.html#tier-2):

- arm-unknown-linux-gnueabi
- arm-unknown-linux-gnueabihf
- armv7-unknown-linux-gnueabihf
- aarch64-unknown-linux-gnu

However, all of them have official rustc, std and cargo builds, and they are available via rustup. According to the [builders page](http://buildbot.rust-lang.org/builders), it seems some of them do have running automatic tests, eg. `auto-linux-64-cross-armhf`.

What I'd like to ask is, what's left to do to move these targets to Tier 1? Are there any problems, any blocker issues? Or some other reason?

**Comment by mmatyas** [comment]
Oh, I just noticed the tests are actually skipped...
Other than that, is there something else necessary?

**Comment by sanxiyn** [comment]
The blocking issue is running tests. QEMU was suggested to run tests, see #33114.

**Comment by alexcrichton** [comment]
Yeah the [definition of Tier 1](https://doc.rust-lang.org/nightly/book/getting-started.html#tier-1) is that we're running tests, which we currently aren't doing. We're also arguably lacking documentation for these platforms as they haven't seen as much usage as the x86/x86_64 platforms. In any case though this is largely covered by #33114, so I'm gonna close in favor of that, but thanks for the report!
