### ISSUE TITLE
Track cross-crate no-trans ("cargo check") pass timings.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#33725]
The following timings were obtained on #33602 with `src/bootstrap/rustc.rs` modified to always pass `-Z no-trans -Z time-passes` and then ran on a whole stage1 pass (libstd + rustc).

You can also look at the [raw log and the script](https://gist.github.com/eddyb/0db2f60395d3150a07bc0d15d158ee7b) that generated the table.

For each pass, the sum of that pass' timings across all crates is given.
I've emphasized all the passes that take more than 5 seconds in total.
Specifically, `item-bodies checking` seems to take a lot of time.
@nikomatsakis has mentioned that his projection cache makes type-checking faster, although its impact on these times is yet unknown.

Also, AFAIK @nrc and @jonathandturner have a proper perf tracking solution that could also do `-Z no-trans` runs, which should look better than my manual logs.

| Pass name | Total time |
| --- | --- |
| parsing | 2.089s |
| configuration 1 | 0.530s |
| recursion limit | 0.000s |
| crate injection | 0.000s |
| macro loading | 2.055s |
| plugin loading | 0.000s |
| plugin registration | 0.000s |
| **expansion** | **6.545s** |
| configuration 2 | 1.053s |
| gated configuration checking | 0.000s |
| maybe building test harness | 0.502s |
| prelude injection | 0.402s |
| checking that all macro invocations are gone | 0.070s |
| checking for inline asm in case the target doesn't support it | 0.000s |
| complete gated feature checking | 0.160s |
| assigning node ids | 0.431s |
| collecting defs | 0.315s |
| external crate/lib resolution | 0.817s |
| early lint checks | 0.334s |
| name resolution | 1.831s |
| lowering ast -> hir | 0.719s |
| indexing hir | 0.088s |
| attribute checking | 0.081s |
| language item collection | 0.079s |
| lifetime resolution | 0.107s |
| looking for entry point | 0.000s |
| looking for plugin registrar | 0.000s |
| region resolution | 0.413s |
| loop checking | 0.057s |
| static item recursion checking | 0.059s |
| load_dep_graph | 0.000s |
| type collecting | 1.132s |
| variance inference | 0.015s |
| coherence checking | 3.061s |
| **wf checking** | **5.322s** |
| **item-types checking** | **9.978s** |
| **item-bodies checking** | **84.693s** |
| drop-impl checking | 0.001s |
| const checking | 4.972s |
| privacy checking | 0.536s |
| stability index | 0.086s |
| intrinsic checking | 0.533s |
| effect checking | 0.134s |
| match checking | 1.516s |
| liveness checking | 0.489s |
| rvalue checking | 4.355s |
| **MIR dump** | **6.513s** |
| MIR passes | 4.136s |
| **borrow checking** | **9.307s** |
| reachability checking | 0.222s |
| death checking | 0.404s |
| stability checking | 0.455s |
| unused lib feature checking | 0.000s |
| lint checking | 4.582s |
| resolving dependency formats | 0.097s |
| Prepare MIR codegen passes | 0.920s |
| **&nbsp;&nbsp;write metadata** | **6.387s** |
| **&nbsp;&nbsp;translation item collection** | **16.706s** |
| &nbsp;&nbsp;codegen unit partitioning | 1.064s |
| **translation** | **25.007s** |
| assert dep graph | 0.015s |
| serialize dep graph | 0.000s |
| &nbsp;&nbsp;llvm function passes [0] | 0.000s |
| &nbsp;&nbsp;llvm module passes [0] | 0.000s |
| &nbsp;&nbsp;codegen passes [0] | 0.052s |
| LLVM passes | 0.239s |
| **linking** | **7.134s** |
| &nbsp;&nbsp;altering collections-fcd89c446c422598.rlib | 0.000s |
| &nbsp;&nbsp;altering panic_unwind-51e342ee2f803940.rlib | 0.000s |
| &nbsp;&nbsp;altering alloc-907db4fbb3fafc96.rlib | 0.000s |
| &nbsp;&nbsp;altering alloc_jemalloc-a216938f82a1db8c.rlib | 0.018s |
| &nbsp;&nbsp;altering rustc_unicode-6571ce0f83faa69c.rlib | 0.000s |
| &nbsp;&nbsp;altering unwind-cdc3b6d466599f1c.rlib | 0.000s |
| &nbsp;&nbsp;altering libc-0beda9f0eb92d0e5.rlib | 0.000s |
| &nbsp;&nbsp;altering rand-8b03f2aa3ee680c5.rlib | 0.000s |
| &nbsp;&nbsp;altering core-a4faa1f84cab77e5.rlib | 0.000s |
| **&nbsp;&nbsp;running linker** | **7.172s** |
| **total** | **194.591s** |

**Comment by steveklabnik** [comment]
Triage: https://perf.rust-lang.org/ still doesn't collect this data, as far as I know

**Comment by jonas-schievink** [comment]
Triage: https://perf.rust-lang.org/ now has lots of `-check` benchmarks. Closing as fixed!

**Comment by eddyb** [comment]
@jonas-schievink @Mark-Simulacrum We still don't benchmark compile times for rustc itself, do we?

**Comment by jonas-schievink** [comment]
Oh, I see. No, I don't think we do.

**Comment by Mark-Simulacrum** [comment]
I.. am uncertain how that relates to this issue though? (I agree it would be good to do, but seems orthogonal?)

**Comment by eddyb** [comment]
Alright, I guess this issue is old enough that it bakes in that assumption unnecessarily.
