### ISSUE TITLE
Separate suggestions from labels

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang/rust#33740]
Even if we show them the same to the user, separate suggestions from labels so that tools that need suggestions (like smart linters) can find them in the json:

https://github.com/rust-lang/rust/pull/33619/files/65cb5f73789723b5eeb4ba9332e3e034939369c4#r63732876

**Comment by oli-obk** [comment]
Isn't that what's already happening? Suggestions have a human readable text + a replacement that can be inserted automatically.

The change you linked to removed the machine readable suggestion

**Comment by estebank** [comment]
This is the current behavior. `span_suggestions` are presented apart in the `json` output, but they are presented inline as labels under specific circumstances (output is short, the suggested replacement is not an empty string, there's only one suggestion).
