### ISSUE TITLE
multiple rlib candidates for "regex" found

### ISSUE THREAD

**Issue by Xiaohong-Deng** [rust-lang/rust#33741]
Is there a way that I can explicitly set one of them as the default to resolve this problem?

> src/main.rs:1:1: 1:20 error: multiple rlib candidates for `regex` found [E0465]
> src/main.rs:1 extern crate regex;
>               ^~~~~~~~~~~~~~~~~~~
> src/main.rs:1:1: 1:20 note: candidate #1: /home/myproject/target/debug/deps/libregex-33f3d4c6de69fd7d.rlib
> src/main.rs:1 extern crate regex;
>               ^~~~~~~~~~~~~~~~~~~
> src/main.rs:1:1: 1:20 note: candidate #2: /home/myproject/target/debug/libregex.rlib
> src/main.rs:1 extern crate regex;
>               ^~~~~~~~~~~~~~~~~~~
> src/main.rs:1:1: 1:20 error: can't find crate for `regex` [E0463]
> src/main.rs:1 extern crate regex;
>               ^~~~~~~~~~~~~~~~~~~
> error: aborting due to 2 previous errors
> Could not compile `regex`.
>

**Comment by alexcrichton** [comment]
Indeed! You can pass `--extern regex=path/to/libregex.rlib` and that should take care of it
