### ISSUE TITLE
rustc asserts (crashes) when compiling argon2rs with simd enabled

### ISSUE THREAD

**Issue by upsuper** [rust-lang/rust#33764]
I'm running nightly Rust on OS X 10.10.5, and tried to run test on [argon2rs](https://github.com/bryant/argon2rs), and rustc crashes.

Run:
- multirust run nightly cargo test --features=simd

It outputs:

> Assertion failed: (ReqTy && "extractvalue indices invalid!"), function getExtractValue, file /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/llvm/lib/IR/Constants.cpp, line 2157.

**Comment by upsuper** [comment]
The code triggers the assertion is: https://play.rust-lang.org/?gist=d611783d92f7718d0e8038e0e60fc1de&version=nightly&backtrace=0

It seems this crashes on Rust Playground as well. And it crashes only if the test mod is compiled.

**Comment by upsuper** [comment]
This is a reduced testcase to reproduce this issue:
```rust
#![feature(repr_simd)]

#[repr(simd)]
#[allow(non_camel_case_types)]
pub struct u64x2(pub u64, pub u64);

fn main() {
    const T0: u64x2 = u64x2(0, 0);
    println!("{}", T0.0.rotate_right(8));
}
```

**Comment by Mark-Simulacrum** [comment]
This has since been fixed, closing.
