### ISSUE TITLE
Test fails when using RUST_NEW_ERROR_FORMAT

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang/rust#33763]
If you set RUST_NEW_ERROR_FORMAT, running the full 'make check' will fail.  @alexcrichton did some investigation and noticed this was one failure: https://github.com/rust-lang/rust/blob/master/src/test/run-make/unicode-input/span_length.rs#L94-L98

We may want to update the test or possibly move it to a UI test.

**Comment by jonathandturner** [comment]
cc @nikomatsakis

**Comment by nikomatsakis** [comment]
Yeah, I think this is precisely what the UI testing is all about.
