### ISSUE TITLE
sort function declarations in pre-tag lexically

### ISSUE THREAD

**Issue by postmodern** [rust-lang/rust#33782]
In the [pre tag](https://doc.rust-lang.org/stable/std/iter/trait.Iterator.html) that describes Traits, the function signatures are listed in order. This makes it hard to find a specific function signature you're looking for.

**Comment by birkenfeld** [comment]
I don't know, personally I like keeping the source order - as in your example of `Iterator`, it often conveys the importance of the functions, and groups related functionality.

**Comment by postmodern** [comment]
@birkenfeld why not both? Maybe add the ability to sort the functions by order or alphabetically? Does rustdoc already have `group` doc tag to explicitly tag functions into groupings?

**Comment by birkenfeld** [comment]
Dynamic reordering? That would be great!

**Comment by AndrewBrinker** [comment]
Would you want to only reorder the initial listing of function declarations, or also reorder the explanations below? Also, which ordering should be the default?

**Comment by postmodern** [comment]
If we're going to copy what other languages do, alphabetic or lexical ordering of both function declarations and the verbose descriptions seems to be the defacto norm:

* [Haskell](https://hackage.haskell.org/package/base-4.9.0.0/docs/Data-String.html)
* [Go](https://golang.org/pkg/strings/)
* [Java Doc](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html)
* [JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String)
* [Lua](http://www.gammon.com.au/scripts/doc.php?general=lua_string)
* [Python](https://docs.python.org/2/library/string.html)
* [RubyDoc (RDoc)](http://ruby-doc.org/core-2.3.1/String.html)
* [RubyDoc (YARD)](http://www.rubydoc.info/stdlib/core/String)
* [Swift](https://developer.apple.com/library/ios/documentation/Swift/Reference/Swift_String_Structure/index.html#//apple_ref/swift/struct/s:SS)

The outliers are [Standard ML](http://sml-family.org/Basis/string.html) and [OCaml](http://caml.inria.fr/pub/docs/manual-ocaml/libref/String.html), which lists functions in non-alphabetic order.

I could see some value in order functions by order of declaration, but that seems more useful to developers working on Rust as opposed to developers using Rust.

**Comment by jsha** [comment]
Bumping an old issue. I don't know what rustdoc looked like when this issue was filed, but the current situation is that the `<pre>` tag at the top of the page still keeps the source code order, _but_ the sidebar listing of methods is in lexical order. I suspect that solves the use case of looking for a specific function by name?

**Comment by Dylan-DPC** [comment]
Closing this as it's now fixed as it is shown in lexical order.
