### ISSUE TITLE
Rename main thread from "<main>" to "main"

### ISSUE THREAD

**Issue by WiSaGaN** [rust-lang/rust#33789]
Currently the main thread is named "\<main\>". See [playground](https://play.rust-lang.org/?gist=24fc130050d3cc2474db5bafda980cbf&version=stable&backtrace=0).
As a result, other thread names have to be of style "\<foo\>" to be consistent in logs or other outputs.

Since we only have this one thread that is named by the system, "\<\>" does not help in distinguishing system threads with other threads.

"main" is simpler, and more consistent with what a name should be.

The change may affect program behaviour though, as the name of the main thread can be used to determine whether the current thread is main thread.
If the main thread name has not been specified in any way, this may be considered not a breaking change.

**Comment by huonw** [comment]
cc @rust-lang/libs
