### ISSUE TITLE
Change key binding for "expand all" in docs

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#33791]
#33765 introduced a feature to expand all docs at once with the '+' key. However, if you want to zoom in for example, it'll expand all as well. Another key combo should be added.

cc @alex-ozdemir
cc  @Manishearth

**Comment by alex-ozdemir** [comment]
Any thoughts on what key would be best?

**Comment by GuillaumeGomez** [comment]
Adding another key to the "+" I guess? Something like "SHIFT+'+'" maybe?

**Comment by alex-ozdemir** [comment]
Moving this conversation to the new PR.
