### ISSUE TITLE
Clarify HashMap docs discussion of DoS protection

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#33817]
Today, the HashMap docs say:

> The hashes are all keyed by the thread-local random number generator on creation by default. This means that the ordering of the keys is randomized, but makes the tables more resistant to denial-of-service attacks (Hash DoS). No guarantees are made to the quality of the random data. The implementation uses the best available random data from your platform at the time of creation. This behavior can be overridden with one of the constructors.

While this is accurate, it's burying the lede: we should say much more clearly what the tradeoffs are, and point more directly toward the custom hashing infrastructure. E.g.:

> **By default, HashMaps use a somewhat slow hashing algorithm that provides resistance to denial-of-service attacks (Hash DoS).** For cases where DoS protection isn't needed, you can opt into a faster hasher by using *some details here*.

**Comment by steveklabnik** [comment]
part of https://github.com/rust-lang/rust/issues/29348

**Comment by steveklabnik** [comment]
I would be happy to work with anyone who wants to work on this issue.

**Comment by apoelstra** [comment]
https://github.com/rust-lang/rust/pull/33086 is relevant to this bug -- now the docs should say that Rust uses a slow hash function by default "for DoS protection", but does not actually provide DoS protection.

**Comment by mgattozzi** [comment]
@steveklabnik I'd like to take a crack at this issue with your help. I won't be able to work on it today but I could tomorrow.

**Comment by steveklabnik** [comment]
@mgattozzi great! Can you swing by IRC tomorrow? That'd be easiest

**Comment by mgattozzi** [comment]
The docs IRC channel correct? I'll swing by around 7pm EST maybe even
slightly earlier

**Comment by steveklabnik** [comment]
Yeah, any of them. That's a _little_ late for me, but I'm sure that one of us can be helpful :smile: 

(And I'm also happy to do it asynchronously through this issue too, just sometimes real-time is a bit easier.)

**Comment by mgattozzi** [comment]
I'll pop in around that time and if you're around great if not I'll point
the channel to this issue to ask for help if I need it. I could pop on
during work lunch break tomorrow and at least get a starting point from you
if that works as well.
