### ISSUE TITLE
FnBox is not callable with function call syntax if it has a bound lifetime argument

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#33811]
The following does not compile, but I expect it to! If the argument type is changed from `&str` to `i32` (and the call site adapted), then it compiles. [Playground](https://play.rust-lang.org/?gist=7a97b81ed05924f017395ce5e63ba0cf&version=nightly&backtrace=0)

``` rust
#![feature(fnbox)]

use std::boxed::FnBox;

struct Func {
    out: Box<FnBox(&str)>
}

impl Func {
    fn callme(self) {
        let s = String::new();
        (self.out)(&s);
    }
}
```

``` rust
error: expected function, found `Box<for<'r> std::boxed::FnBox<(&'r str,), Output=()> + 'static>`
  --> <anon>:12:9
12 |>         (self.out)(&s);
   |>         ^^^^^^^^^^^^^^
```

**Comment by alexcrichton** [comment]
cc https://github.com/rust-lang/rust/issues/28796 (tracking issue)

**Comment by eefriedman** [comment]
The relevant impl block looks like this:

```
impl<'a, A, R> FnOnce<A> for Box<FnBox<A, Output = R> + 'a> {
```

There is no type `A` which would allow this impl be used for `FnBox(&str)`: there isn't any appropriate lifetime for the reference.  Therefore, the `FnBox` can't be called.

**Comment by bluss** [comment]
Aha, thanks for the explanation! I had assumed FnBox had direct compiler support like the other closure traits. That means FnBox is stuck in the same hole as function pointers -- we can't reach all possible types from trait impls.

**Comment by jwilm** [comment]
Heh, ran into this first time needing a FnBox.

**Comment by steveklabnik** [comment]
If https://github.com/rust-lang/rust/issues/28796#issuecomment-433707872 succeeds, fnbox will go away

**Comment by cjgillot** [comment]
Now works with a `Box<dyn FnOnce(&str)>`.
