### ISSUE TITLE
Behavior on uncaught exception is different between -C panic=abort and -C panic=unwind

### ISSUE THREAD

**Issue by tomaka** [rust-lang/rust#33812]
When a program compiled with `-C panic=abort` panicks, the stack trace is printed and an illegal instruction is triggered (with the `ud2` opcode).
When a program compiled with `-C panic=unwind` doesn't catch a panic in the main thread, the stack trace is printed and the program aborts.

I don't have any strong opinion in favor of triggering an illegal instruction vs aborting, but I think the behavior should be the same between `panic=abort` and `panic=unwind`.

**Comment by huonw** [comment]
> and the program aborts

To be clear, I think this should read "and the program calls `exit(101)`", which is different to both `libc::abort()` and `std::intrinsics::abort()` (the latter is actually how the `ud2`s are created).

**Comment by retep998** [comment]
I'd really prefer if we called `DebugBreak` whenever there was an uncaught panic on Windows just to make debugging a bit easier, because otherwise with `panic=unwind` it is silently caught and the program exits cleanly (!) with an exit code of 101.

**Comment by briansmith** [comment]
> I'd really prefer if we called DebugBreak

Call `__debugbreak()` instead. `DebugBreak` can screw up call stacks (see old fixed bugs in the Firefox bug tracker).

**Comment by retep998** [comment]
@briangreenery Of course `__debugbreak()` is an intrinsic so we'd have to either hope LLVM has that intrinsic, or use inline assembly.

**Comment by alexcrichton** [comment]
In any case as I [mentioned before](https://github.com/rust-lang/rust/issues/33812#issuecomment-221005667) the behavior of `-C panic=unwind` is undefined if there's nothing to catch a panic, and with a lack of response I'm going to close this issue as well.

If there's something Windows-specific that should happen here, it would be best to open a new issue.

**Comment by retep998** [comment]
I opened a separate issue for that https://github.com/rust-lang/rust/issues/34502
