### ISSUE TITLE
error::Error is not implemented for fmt::Error

### ISSUE THREAD

**Issue by burtonageo** [rust-lang/rust#33827]
The [Error](https://doc.rust-lang.org/std/error/trait.Error.html) trait is not implemented for the [fmt::Error](https://github.com/rust-lang/rust/blob/master/src/libcore/fmt/mod.rs#L64) struct.

**Comment by GuillaumeGomez** [comment]
Some source code would be appreciated. Context and rustc version as well.

**Comment by Stebalien** [comment]
@GuillaumeGomez I think you're commenting on the wrong bug or misreading the issue. The issue here is that `fmt::Error` is an error and should implement `error::Error` but doesn't.

**Comment by GuillaumeGomez** [comment]
@Stebalien: I think I went too fast, indeed. Now @burtonageo also added a description, which helps. :)

**Comment by GuillaumeGomez** [comment]
I'm adding it btw.

**Comment by pmarcelll** [comment]
I looked around in the standard library's documentation, the only other case where error::Error is not implemented for an error is [FromBytesWithNulError](https://doc.rust-lang.org/nightly/std/ffi/struct.FromBytesWithNulError.html).

**Comment by GuillaumeGomez** [comment]
@pmarcelll: Want to add it maybe? Take a look at my PR if you don't know how to do it.

**Comment by pmarcelll** [comment]
Sure, I'll send a PR, but I'm busy currently, so only tomorrow.

**Comment by GuillaumeGomez** [comment]
No problem. ;)
