### ISSUE TITLE
regression in error reporting: user-defined types or type parameters cannot shadow the primitive types

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#33836]
stable reports

> user-defined types or type parameters cannot shadow the primitive types

and

> method `a` has an incompatible type for trait:
 expected type parameter,
    found u8 [E0053]

while beta/nightly just says

> error: mismatched types:
 expected `u8`,
    found `u8`
(expected type parameter,
    found u8) [E0308]

```rust
trait A {
    fn a<T>(&self) -> T;
}

struct AA {
    b: u8,
}

impl A for AA {
    fn a<u8>(&self) -> u8 {
        return self.b;
    }
}

fn main() {
    let a = AA {
        b: 2,
    };
    println!("{:?}", a.a());
}
```

**Comment by petrochenkov** [comment]
>error: mismatched types:
>expected u8,
>found u8
>(expected type parameter,
>found u8) [E0308]

Everything looks correct.
Behavior of primitive types changed recently, now they can be shadowed.
The error message is not specific to primitive types, any other shadowing gives similar messages:
>error: mismatched types:
>expected S,
>found S
>(expected type parameter,
>found struct S) [E0308]

**Comment by oli-obk** [comment]
> Behavior of primitive types changed recently, now they can be shadowed.

ah, makes sense.
