### ISSUE TITLE
Add an unbounded backtracking engine.

### ISSUE THREAD

**Issue by SeanRBurton** [rust-lang/rust#33838]
If it can be detected that a regular expression can be executed in linear time by backtracking (e.g. if it has no repetition operators), then it might make sense to do this rather than use the NFA. I suspect most of the code from the bounded engine could be reused. 

I am willing to work on this if you would like.

**Comment by TimNN** [comment]
I believe this should be better filed against https://github.com/rust-lang-nursery/regex?

**Comment by SeanRBurton** [comment]
Sorry, my mistake.
