### ISSUE TITLE
ICE with weird macro lifetime syntax

### ISSUE THREAD

**Issue by diwic** [rust-lang/rust#33837]
This code is totally broken, but since it ICEs (on beta and nightly, but not on stable), it's a bug anyhow:

    macro_rules! stupid { ($f0: ty, $f1: ty) => { for <'q> FnOnce(&'q $f0) -> $'q f1 }}
    fn test<T: stupid(String, &str)>() {} 

Fails with:

    <anon>:1:76: 1:78 error: expected identifier, found `'q`
    <anon>:1 macro_rules! stupid { ($f0: ty, $f1: ty) => { for <'q> FnOnce(&'q $f0) -> $'q f1 }}
                                                                                        ^~
    error: internal compiler error: unexpected panic
    note: the compiler unexpectedly panicked. this is a bug.
    note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
    thread 'rustc' panicked at 'internal error: entered unreachable code', ../src/libsyntax/parse/parser.rs:2857

**Comment by TimNN** [comment]
Looks like #33728.

**Comment by TimNN** [comment]
This has been fixed on the latest nightly, probably by #33870.

**Comment by alexcrichton** [comment]
Yay!
