### ISSUE TITLE
Broken link in the Rust book

### ISSUE THREAD

**Issue by keram88** [rust-lang/rust#33843]
The page https://doc.rust-lang.org/book/compiler-plugins.html contains a link to https://doc.rust-lang.org/rustc_plugin/ which goes nowhere.

**Comment by TimNN** [comment]
This has been fixed in the beta documentation: https://doc.rust-lang.org/beta/book/compiler-plugins.html

**Comment by steveklabnik** [comment]
Yup! Thanks for reporting, @keram88 , but since this has already been fixed, giving it a close.
