### ISSUE TITLE
struct field dependencies are overly conservative

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#33850]
The test cases I am adding in an upcoming PR show that for some reason we consider functions as dirty when any struct changes, even if the fn doesn't use that struct.

**Comment by nikomatsakis** [comment]
(Look for the FIXMEs.)

**Comment by nikomatsakis** [comment]
Heh, ok, I figured out why this is. The problem is that we use one dep-node for "trait selection on a given `Trait`". This is awfully coarse-grained, but I thought we could get away with it. Turns out, not such a good idea with the `Sized` trait.

**Comment by michaelwoerister** [comment]
`:D`

**Comment by nikomatsakis** [comment]
(got a fix locally, will prep PR soon)
