### ISSUE TITLE
compiler emits unsupported DT_FLAGS_1 value 0x8000000 in ELF

### ISSUE THREAD

**Issue by m4b** [rust-lang/rust#33863]
## Repro
1. compile a rust binary for a GNU/Linux target (probably anything that uses ELF, but I've only tested on GNU/Linux with glibc target), `rustc derp.rs -o derp`
2. run `LD_DEBUG=all derp`
3. Note the top of the output says:

```
     26491: 
     26491: WARNING: Unsupported flag value(s) of 0x8000000 in DT_FLAGS_1.
```
## Discussion

If you examine `/usr/include/elf.h`, you'll notice that there _does not_ exist a `DF_1_<X>` flag with this value.

Strangely, while `readelf -d derp` says the flag is `PIE` (which is not a flag in `DF_1`...); `objdump` says the flag is 0x800000, my own binary reading tool says it's  `0x8000000`, my dynamic linker also says it's `0x8000000`, and of course as we saw above, so does glibc's.

**Comment by michaelwoerister** [comment]
@nagisa Is there a specific reason why you added the `A-debuginfo` tag to this?

**Comment by nagisa** [comment]
Nope, my brains must have been fried out back then.

**Comment by cyplo** [comment]
Seems still there today (rustc 1.14.0-nightly (cae6ab1c4 2016-11-05))

**Comment by michaelwoerister** [comment]
@nagisa No problem `:)` Just wanted to make sure that I'm not missing something here. (Why did I only now get an email notification about your post?...)

**Comment by m4b** [comment]
Still here in latest nightly ...

**Comment by mirh** [comment]
Glibc added this in [2.27](https://sourceware.org/bugzilla/show_bug.cgi?id=22707) (not sure why readelf has proceeded it by [two happy years](https://sourceware.org/bugzilla/show_bug.cgi?id=22707))

Aside of that though, I don't think that makes it any less unsupported flag. What's setting it?

**Comment by bjorn3** [comment]
Should this be closed?

**Comment by workingjubilee** [comment]
Yes.
