### ISSUE TITLE
Missoptimization of functions with C calling convention

### ISSUE THREAD

**Issue by Florob** [rust-lang/rust#33868]
When trying to look at how aggregates are passed to functions I came across the following:
The code presented below erroneously outputs `488447261` instead of `20`.
This is using the 1.9.0 preview release (or anything newer) and seems to be a regression from 1.8.0.
The behaviour only occurs when using the C calling conventions and optimizations, eliminating either factor gives the correct result.

```rust
#[repr(C)]
struct S {
    a: u32,
    b: f32,
    c: u32
}

extern "C" fn test(s: S) -> u32 {
    s.a + s.b as u32 + s.c
}

fn main() {
    println!("{}", test(S { a: 12, b: 3.4, c: 5 }));
}
```

**Comment by retep998** [comment]
Which target is this for? There are multiple calling conventions across operating systems and architectures after all.

**Comment by Florob** [comment]
This is on x86_64-unknown-linux-gnu.

**Comment by michaelwoerister** [comment]
I can confirm this for `rustc 1.10.0-nightly (dd6e8d45e 2016-05-23)`

**Comment by nagisa** [comment]
Works on stable.

**Comment by nagisa** [comment]
cc @eddyb could it be your calling trans refactor?

**Comment by nagisa** [comment]
Seems like we invoke some UB:

```llvm
; Function Attrs: noinline norecurse nounwind readnone uwtable
define i32 @test({ i64, i64 }) unnamed_addr #0 {
entry-block:
  ret i32 undef
}
```

is what the function ends up being optimised to.

**Comment by nagisa** [comment]
[This](https://gist.github.com/nagisa/8e1b1d8053e495754ef85118b5fc7829) is what I managed to reduce the issue to.

**Comment by arielb1** [comment]
This suffices:
```Rust

#[no_mangle]
pub extern "C"  fn test(s: S) -> u32 {
    s.c
}
```

Bad IR:
```
define i32 @test({ i64, i64 }) unnamed_addr #0 !dbg !176 {
entry-block:
  %s = alloca %S
  %1 = bitcast %S* %s to { i64, i64 }*
  store { i64, i64 } %0, { i64, i64 }* %1, align 4
  call void @llvm.dbg.declare(metadata %S* %s, metadata !202, metadata !203), !dbg !204
  %2 = getelementptr inbounds %S, %S* %s, i32 0, i32 2
  %3 = load i32, i32* %2, !dbg !205
  ret i32 %3, !dbg !207
}
```

**Comment by arielb1** [comment]
The old, working functionality uses a shim:
```
  %1 = alloca { i64, i64 }
  store { i64, i64 } %0, { i64, i64 }* %1
  %2 = bitcast { i64, i64 }* %1 to %S*
  %3 = call i32 @_ZN4test10__rust_abiE(%S* noalias nocapture dereferenceable(12) %2)
  ret i32 %3
```

**Comment by arielb1** [comment]
We are storing 16 bytes of data in a 12-byte bag and that is killing us.

**Comment by nagisa** [comment]
Basically this should be 

```
%s = alloca {i64, i64}
store { i64, i64 } %0, { i64, i64 }* %s, align 4
%1 = bitcast { i64, i64 }* %s to %S*
```

instead. Shouldn’t be very hard to fix?

**Comment by nagisa** [comment]
For the reference, `define i32 @test(i64 %s.coerce0, i32 %s.coerce1) #0 {` is the signature generated by `clang` for an identical function. Alternatively we could use `{i64, i32}` instead of `{i64, i64}`.

**Comment by nikomatsakis** [comment]
@arielb1 what was the signature of the shim function?

**Comment by eddyb** [comment]
Ah, this is the problem @dotdash was aware of, isn't it?
Where none of our current system works perfectly right with respect to cast arguments/returns of different sizes but some of the old code was long-winded enough to avoid the problem.

**Comment by alexcrichton** [comment]
The core team discussed this issue today and our conclusions were as follows:

* Definitely seems like something we should fix immediately, hence the P-high.
* We're very likely to backport the fix to beta (unless it turns out to require a compiler refactor, which seems unlikely)
* We're moving forward with the 1.9 release tomorrow as this has been on nightly for at least 6 weeks and hasn't been discovered yet. That's at least a signal that the breakage isn't major enough to warrant blocking or delaying the entire release.
* Once the fix is backported to beta and has some testing on the beta branch we can consider whether to make a point release (e.g. 1.9.1). If this bug is widespread in practice then we can definitely do that, but if the impact continues to be low we may not do that.
