### ISSUE TITLE
Giving a trait method a default implementation can trigger unused_variables warnings

### ISSUE THREAD

**Issue by chris-morgan** [rust-lang/rust#33875]
```rust
trait X {
    fn foo(bar: Bar);
}
```

[Fine, no warnings.](https://is.gd/I5Z933)

But give it a default implementation that doesn’t use all those arguments (a perfectly plausible and reasonable situation):

```rust
trait X {
    fn foo(bar: Bar) { }
}
```

[A warning:](https://is.gd/QV748t)
```
<anon>:2:12: 2:15 warning: unused variable: `bar`, #[warn(unused_variables)] on by default
<anon>:2     fn foo(bar: Bar) { }
                    ^~~
```

Arguments to a trait fn default implementation should be considered immune from unused variables warnings, because their names are a part of the API as it gets documented.

The alternatives are (a) prefixing the variable name with an underscore, which is ugly in generated API docs; and (b) tacking `#[allow(unused_variables)]` onto the `fn foo`, which then silences other legitimate unused variables warnings in the *body* of the function.

**Comment by apasel422** [comment]
This is a duplicate of #26487.

**Comment by SoniEx2** [comment]
Why not split unused_variables and unused_parameters?

**Comment by SoniEx2** [comment]
Or why not just use

```rust
trait X {
    fn foo(bar: Bar) {
        let _ = bar; // a la `(void)x;` in C?
    }
}
```

**Comment by chris-morgan** [comment]
Not certain how I missed the existing issues when searching for it. I suspect I accidentally had it filtered to only open issues. Ah well. I still think it should be done, but this issue is not necessary.

**Comment by SoniEx2** [comment]
I feel like the "a la `(void)x;`" solution is the cleanest. Increasing compiler complexity for the unused_variables lint isn't needed.
