### ISSUE TITLE
upgrade to 1.9, build fail....

### ISSUE THREAD

**Issue by Matrix-Zhang** [rust-lang/rust#33899]
here is the RUST_BACKTRACE=1 cargo build log....

   Compiling bufstream v0.1.2 (registry git://crates.mirrors.ustc.edu.cn/index)
   Compiling byteorder v0.5.2 (registry git://crates.mirrors.ustc.edu.cn/index)
   Compiling winapi-build v0.1.1 (registry git://crates.mirrors.ustc.edu.cn/index)
   Compiling winapi v0.2.7 (registry git://crates.mirrors.ustc.edu.cn/index)
   Compiling num-traits v0.1.32 (registry git://crates.mirrors.ustc.edu.cn/index)
   Compiling libc v0.1.12 (registry git://crates.mirrors.ustc.edu.cn/index)
   Compiling libc v0.2.11 (registry git://crates.mirrors.ustc.edu.cn/index)
   Compiling gcc v0.3.28 (registry git://crates.mirrors.ustc.edu.cn/index)
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0 }', ../src/libcore\result.rs:746
stack backtrace:
   0:         0x6a481623 - <unknown>
   1:         0x6a480ab9 - <unknown>
   2:         0x6a444a0f - <unknown>
   3:         0x6a44659b - <unknown>
   4:         0x6a473d0b - <unknown>
   5:         0x6a496745 - <unknown>
   6:         0x6bb416d3 - <unknown>
   7:         0x6bb41634 - <unknown>
   8:         0x645130ed - <unknown>
   9:         0x645439a7 - <unknown>
  10:         0x6453b094 - <unknown>
  11:         0x64524058 - <unknown>
  12:         0x64522d25 - <unknown>
  13:         0x64524810 - <unknown>
  14:         0x6452459f - <unknown>
  15:         0x64520289 - <unknown>
  16:         0x64525711 - <unknown>
  17:         0x64527739 - <unknown>
  18:         0x64548b6a - <unknown>
  19:         0x6454774a - <unknown>
  20:         0x61eaeec7 - <unknown>
  21:         0x61e95760 - <unknown>
  22:         0x61e85eb5 - <unknown>
  23:         0x61e8320b - <unknown>
  24:         0x6a473c3a - <unknown>
  25:         0x61e83a9c - <unknown>
  26:         0x6a47eb39 - <unknown>
  27:     0x7ffed1348101 - <unknown>

thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0 }', ../src/libcore\result.rs:746
stack backtrace:
   0:         0x6a481623 - <unknown>
   1:         0x6a480ab9 - <unknown>
   2:         0x6a444a0f - <unknown>
   3:         0x6a44659b - <unknown>
   4:         0x6a473d0b - <unknown>
   5:         0x6a496745 - <unknown>
   6:         0x6bb416d3 - <unknown>
   7:         0x6bb41634 - <unknown>
   8:         0x645130ed - <unknown>
   9:         0x645439a7 - <unknown>
  10:         0x6453b094 - <unknown>
  11:         0x64524058 - <unknown>
  12:         0x64522d25 - <unknown>
  13:         0x64524810 - <unknown>
  14:         0x6452459f - <unknown>
  15:         0x64520289 - <unknown>
  16:         0x64525711 - <unknown>
  17:         0x64527739 - <unknown>
  18:         0x64548b6a - <unknown>
  19:         0x6454774a - <unknown>
  20:         0x61eaeec7 - <unknown>
  21:         0x61e95760 - <unknown>
  22:         0x61e85eb5 - <unknown>
  23:         0x61e8320b - <unknown>
  24:         0x6a473c3a - <unknown>
  25:         0x61e83a9c - <unknown>
  26:         0x6a47eb39 - <unknown>
  27:     0x7ffed1348101 - <unknown>

thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0 }', ../src/libcore\result.rs:746
stack backtrace:
   0:         0x6a481623 - <unknown>
   1:         0x6a480ab9 - <unknown>
   2:         0x6a444a0f - <unknown>
   3:         0x6a44659b - <unknown>
   4:         0x6a473d0b - <unknown>
   5:         0x6a496745 - <unknown>
   6:         0x6bb416d3 - <unknown>
   7:         0x6bb41634 - <unknown>
   8:         0x645130ed - <unknown>
   9:         0x645439a7 - <unknown>
  10:         0x6453b094 - <unknown>
  11:         0x64524058 - <unknown>
  12:         0x64522d25 - <unknown>
  13:         0x64524810 - <unknown>
  14:         0x6452459f - <unknown>
  15:         0x64520289 - <unknown>
  16:         0x64525711 - <unknown>
  17:         0x64527739 - <unknown>
  18:         0x64548b6a - <unknown>
  19:         0x6454774a - <unknown>
  20:         0x61eaeec7 - <unknown>
  21:         0x61e95760 - <unknown>
  22:         0x61e85eb5 - <unknown>
  23:         0x61e8320b - <unknown>
  24:         0x6a473c3a - <unknown>
  25:         0x61e83a9c - <unknown>
  26:         0x6a47eb39 - <unknown>
  27:     0x7ffed1348101 - <unknown>

thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0 }', ../src/libcore\result.rs:746
stack backtrace:
   0:         0x6a481623 - <unknown>
   1:         0x6a480ab9 - <unknown>
   2:         0x6a444a0f - <unknown>
   3:         0x6a44659b - <unknown>
   4:         0x6a473d0b - <unknown>
   5:         0x6a496745 - <unknown>
   6:         0x6bb416d3 - <unknown>
   7:         0x6bb41634 - <unknown>
   8:         0x645130ed - <unknown>
   9:         0x645439a7 - <unknown>
  10:         0x6453b094 - <unknown>
  11:         0x64524058 - <unknown>
  12:         0x64522d25 - <unknown>
  13:         0x64524810 - <unknown>
  14:         0x6452459f - <unknown>
  15:         0x64520289 - <unknown>
  16:         0x64525711 - <unknown>
  17:         0x64527739 - <unknown>
  18:         0x64548b6a - <unknown>
  19:         0x6454774a - <unknown>
  20:         0x61eaeec7 - <unknown>
  21:         0x61e95760 - <unknown>
  22:         0x61e85eb5 - <unknown>
  23:         0x61e8320b - <unknown>
  24:         0x6a473c3a - <unknown>
  25:         0x61e83a9c - <unknown>
  26:         0x6a47eb39 - <unknown>
  27:     0x7ffed1348101 - <unknown>

thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0 }', ../src/libcore\result.rs:746
stack backtrace:
   0:         0x6a481623 - <unknown>
   1:         0x6a480ab9 - <unknown>
   2:         0x6a444a0f - <unknown>
   3:         0x6a44659b - <unknown>
   4:         0x6a473d0b - <unknown>
   5:         0x6a496745 - <unknown>
   6:         0x6bb416d3 - <unknown>
   7:         0x6bb41634 - <unknown>
   8:         0x645130ed - <unknown>
   9:         0x645439a7 - <unknown>
  10:         0x6453b094 - <unknown>
  11:         0x64524058 - <unknown>
  12:         0x64522d25 - <unknown>
  13:         0x64524810 - <unknown>
  14:         0x6452459f - <unknown>
  15:         0x64520289 - <unknown>
  16:         0x64525711 - <unknown>
  17:         0x64527739 - <unknown>
  18:         0x64548b6a - <unknown>
  19:         0x6454774a - <unknown>
  20:         0x61eaeec7 - <unknown>
  21:         0x61e95760 - <unknown>
  22:         0x61e85eb5 - <unknown>
  23:         0x61e8320b - <unknown>
  24:         0x6a473c3a - <unknown>
  25:         0x61e83a9c - <unknown>
  26:         0x6a47eb39 - <unknown>
  27:     0x7ffed1348101 - <unknown>

thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 3 }', ../src/libcore\result.rs:746
stack backtrace:
   0:         0x6a481623 - <unknown>
   1:         0x6a480ab9 - <unknown>
   2:         0x6a444a0f - <unknown>
   3:         0x6a44659b - <unknown>
   4:         0x6a473d0b - <unknown>
   5:         0x6a496745 - <unknown>
   6:         0x6bb416d3 - <unknown>
   7:         0x6bb41634 - <unknown>
   8:         0x645130ed - <unknown>
   9:         0x645439a7 - <unknown>
  10:         0x6453b094 - <unknown>
  11:         0x64524058 - <unknown>
  12:         0x64522d25 - <unknown>
  13:         0x64524810 - <unknown>
  14:         0x6452459f - <unknown>
  15:         0x64520289 - <unknown>
  16:         0x64525711 - <unknown>
  17:         0x64527739 - <unknown>
  18:         0x64548b6a - <unknown>
  19:         0x6454774a - <unknown>
  20:         0x61eaeec7 - <unknown>
  21:         0x61e95760 - <unknown>
  22:         0x61e85eb5 - <unknown>
  23:         0x61e8320b - <unknown>
  24:         0x6a473c3a - <unknown>
  25:         0x61e83a9c - <unknown>
  26:         0x6a47eb39 - <unknown>
  27:     0x7ffed1348101 - <unknown>

thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 3 }', ../src/libcore\result.rs:746
stack backtrace:
   0:         0x6a481623 - <unknown>
   1:         0x6a480ab9 - <unknown>
   2:         0x6a444a0f - <unknown>
   3:         0x6a44659b - <unknown>
   4:         0x6a473d0b - <unknown>
   5:         0x6a496745 - <unknown>
   6:         0x6bb416d3 - <unknown>
   7:         0x6bb41634 - <unknown>
   8:         0x645130ed - <unknown>
   9:         0x645439a7 - <unknown>
  10:         0x6453b094 - <unknown>
  11:         0x64524058 - <unknown>
  12:         0x64522d25 - <unknown>
  13:         0x64524810 - <unknown>
  14:         0x6452459f - <unknown>
  15:         0x64520289 - <unknown>
  16:         0x64525711 - <unknown>
  17:         0x64527739 - <unknown>
  18:         0x64548b6a - <unknown>
  19:         0x6454774a - <unknown>
  20:         0x61eaeec7 - <unknown>
  21:         0x61e95760 - <unknown>
  22:         0x61e85eb5 - <unknown>
  23:         0x61e8320b - <unknown>
  24:         0x6a473c3a - <unknown>
  25:         0x61e83a9c - <unknown>
  26:         0x6a47eb39 - <unknown>
  27:     0x7ffed1348101 - <unknown>

Build failed, waiting for other jobs to finish...
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0 }', ../src/libcore\result.rs:746
stack backtrace:
   0:         0x6a481623 - <unknown>
   1:         0x6a480ab9 - <unknown>
   2:         0x6a444a0f - <unknown>
   3:         0x6a44659b - <unknown>
   4:         0x6a473d0b - <unknown>
   5:         0x6a496745 - <unknown>
   6:         0x6bb416d3 - <unknown>
   7:         0x6bb41634 - <unknown>
   8:         0x645130ed - <unknown>
   9:         0x645439a7 - <unknown>
  10:         0x6453b094 - <unknown>
  11:         0x64524058 - <unknown>
  12:         0x64522d25 - <unknown>
  13:         0x64524810 - <unknown>
  14:         0x6452459f - <unknown>
  15:         0x64520289 - <unknown>
  16:         0x64525711 - <unknown>
  17:         0x64527739 - <unknown>
  18:         0x64548b6a - <unknown>
  19:         0x6454774a - <unknown>
  20:         0x61eaeec7 - <unknown>
  21:         0x61e95760 - <unknown>
  22:         0x61e85eb5 - <unknown>
  23:         0x61e8320b - <unknown>
  24:         0x6a473c3a - <unknown>
  25:         0x61e83a9c - <unknown>
  26:         0x6a47eb39 - <unknown>
  27:     0x7ffed1348101 - <unknown>

**Comment by Matrix-Zhang** [comment]
i use rustup manage the toolchain, i change to nightly 1.10, the build is ok

**Comment by pnkfelix** [comment]
I'm not sure if there is enough information provided to replicate the issue here. ..

What is your host environment (processor and operating system? )

What is the cargo project you are building? 

What cargo invocation are you using that issues the first set of errors?

**Comment by Matrix-Zhang** [comment]
my host environment : WIN10 Enterprise Edition 64bit, I7-4700MQ
the project i'm buiding is quite simple demo project with mongodb,
here is the code:
```
#[macro_use]
extern crate bson;
extern crate mongodb;

use mongodb::db::ThreadedDatabase;
use mongodb::{Client, ThreadedClient};

fn main() {
    let client = Client::connect("192.168.8.110", 27017).unwrap();
    let collection = client.db("test").collection("test");
    let index_keys = doc!{"x" => 1};
    let result = collection.create_index(index_keys, None);
    println!("{:?}", result);
}

```
the firset set of error are :

error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 3 }', ../src/libcore\result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by pmarcelll** [comment]
I think I saw a similar issue somewhere recently, where metadata from the earlier build confused the updated compiler.
Does ```cargo clean``` and then ```cargo build``` help?

**Comment by Matrix-Zhang** [comment]
cargo clean then build is ok...
