### ISSUE TITLE
Missleading error message when defining function with template type by accident

### ISSUE THREAD

**Issue by dns2utf8** [rust-lang/rust#33901]
I noticed a very missleading error:
```rust
src/main.rs:16:12: 16:20 error: wrong number of type arguments: expected 1, found 0 [E0243]                                          
src/main.rs:16 fn fun(v : Template) { 
```

 with this code:
```rust
struct Template<T> {
  inner : T,
}

struct Simple {
  inner : usize,
}

fn main() {
  let t = Template { inner : -1 };
  let s = Simple { inner: 42 };

  fun(s);
}

// The function i am creating right now
fn fun(v : Template) {
}
```

I expected something like this:
```rust
error: mismatched types:
 expected `Template<T>`,
    found `Simple`
(expected struct `Template<T>`,
    found integral variable) [E0308]
```

I assume the message originates from the type checking of the functions where the compiler assumes the function declarations are more correct than the code useing them.
Then the error would be correct.

But using a library the error seems missleading.

**Comment by pmarcelll** [comment]
I think the compiler is right in this case, because your code contains two errors.
The correct signature of ```fun``` is ```fn fun<T>(v : Template<T>)```.
After fixing it, you get:
```
<anon>:13:7: 13:8 error: mismatched types:
 expected `Template<_>`,
    found `Simple`
(expected struct `Template`,
    found struct `Simple`) [E0308]
<anon>:13   fun(s);
                ^
<anon>:13:7: 13:8 help: see the detailed explanation for E0308
error: aborting due to previous error
```

**Comment by dns2utf8** [comment]
I agree from the point of the function declaration.

Fixing this problem took me 2 hours in my case. Maybe somebody has a good idea to address this problem.

**Comment by dns2utf8** [comment]
Maybe this would be a case for an IDE?

**Comment by pmarcelll** [comment]
The best solution for this problem, in my opinion is making a special case for missing angle brackets (the user of the type forgot, that it's templated, or doesn't know exactly, what a type argument is, and where it's expected).

**Comment by nagisa** [comment]
The compiler also underlines where exactly in the line the error is:

```
<anon>:17:12: 17:20 error: wrong number of type arguments: expected 1, found 0 [E0243]
<anon>:17 fn fun(v : Template) {
                     ^~~~~~~~
```

making it pretty obvious what exactly the compiler is complaining about. 

We perhaps could add a note like this:

```
note: definition of struct Template contains a type argument here
struct Template<T> {
                ^
...
```

but I do not see much value in it, because it is trivial to lookup the definition of such struct anyway.

**Comment by pmarcelll** [comment]
I think the source of confusion is that the term "type argument" is confusing/unfamiliar for a lot of people, because other languages use it differently, they use "type parameter" in this case (see [Java](https://docs.oracle.com/javase/tutorial/java/generics/types.html#instantiation), [Swift](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/GenericParametersAndArguments.html), [C++](http://en.cppreference.com/w/cpp/language/template_parameters)).
So when people see the word "type argument", the think of instantiating a generic type with concrete type arguments, they can't figure out that the compiler expects type parameters.

**Comment by arielb1** [comment]
@pmarcelll

But you *are* supposed to provide a type argument here - the type argument can be a parameter (`T`) itself, or it can be a concrete type (e.g. `u8`), but I don't see how this differs from Java.

**Comment by arielb1** [comment]
In any case, I don't think we can improve this.

**Comment by pmarcelll** [comment]
@arielb1 You are right, I forgot that concrete types are also accepted here.
@dns2utf8 If the error message would say "wrong number of *generic* type arguments", would it be easier to understand? What do you think?

**Comment by dns2utf8** [comment]
Hm, the "generic" would hint the user.

I agree, the compiler is right and adding the generic may be a bit redundant, but I think it would help.
