### ISSUE TITLE
The rust book page on mutability is confusingly worded

### ISSUE THREAD

**Issue by jwatt** [rust-lang/rust#33924]
In the [rust book section on mutability](https://doc.rust-lang.org/book/mutability.html) the text is written in a very confusing way. I'm particularly thinking of the bits of text like:

> when we say something is ‘immutable’ [...] we mean something has ‘exterior mutability’

Perhaps this can be reworded as:

> when we say something is ‘immutable’ [...] we mean something has ‘exterior **im**mutability’

Or if the phrase "exterior immutability" isn't acceptable, then a more general rewording like:

> when we say something is ‘immutable’ [...] we are referring to its ‘exterior mutability’

Or:

> when we say something is ‘immutable’ [...] we mean something has ‘exterior mutability’ that in this case is immutable

As it's currently worded it sounds roughly like saying "when something is immutable it is mutable", since saying that something has "exterior mutability" sounds like saying it is mutable on the exterior.

**Comment by steveklabnik** [comment]
I would be happy to work with anyone who wants to work on this issue.

**Comment by KaivoAnastetiks** [comment]
@steveklabnik I think this issue can be closed since #34621

**Comment by steveklabnik** [comment]
Great! Thanks :smile:
