### ISSUE TITLE
Error without line number (macros, deriving type)

### ISSUE THREAD

**Issue by dhardy** [rust-lang/rust#33949]
[Try compiling this](https://is.gd/8qR5jr):

``` rust
fn main() {
    let v = vec![];
}
```

The  error message never mentions a line number outside of the macro.

```
error: unable to infer enough type information about `_`; type annotations or generic parameter binding required [--explain E0282]
 --> <std macros>:3:1
3 |> < [ _ ] > :: into_vec ( box [ $ ( $ x ) , * ] ) ) ; ( $ ( $ x : expr , ) * )
  |> ^^^^^^^^^^^^^^^^^^^^^
<std macros>:3:1: 3:22: note: in this expansion of vec! (defined in <std macros>)

error: aborting due to previous error
playpen: application terminated with error code 101
```

**Comment by nagisa** [comment]
I feel like we had an issue about it already, but cannot find it.

cc @jonathandturner @nikomatsakis

**Comment by Mark-Simulacrum** [comment]
Today, this works and provides the expected line numbers.

```
error[E0282]: type annotations needed
 --> test.rs:2:13
  |
2 |     let v = vec![];
  |         -   ^^^^^^ cannot infer type for `T`
  |         |
  |         consider giving `v` a type
  |
  = note: this error originates in a macro outside of the current crate

error: aborting due to previous error(s)
```

**Comment by jonathandturner** [comment]
Agreed we're (considerably) better than where we were.

I do wonder if we could improve it a bit more, too.  A new user might look at this and go "what T?"  Not sure if it warrants its a separate issue, just throwing the idea out there.

**Comment by Mark-Simulacrum** [comment]
Yeah, we are discussing the what T to some extent on https://github.com/rust-lang/rust/issues/25633.
