### ISSUE TITLE
32-bit msvc variadic FFI probably broken

### ISSUE THREAD

**Issue by retep998** [rust-lang/rust#33952]
https://ci.appveyor.com/project/GuillaumeGomez/va-list-rs/build/1.0.22

Only the 32-bit msvc tests are failing. After adding some debug printfs to the C code it appears that the arguments are busted as soon as `create_va_list` is called. I even tacked on some `__cdecl` to make sure it wasn't accidentally compiling the function with the wrong calling convention.

Due to https://github.com/rust-lang/rust/issues/32305 this was never caught otherwise.

**Comment by GuillaumeGomez** [comment]
cc me

**Comment by retep998** [comment]
Nevermind, it seems `va_start` was just being called with an incorrect second parameter.
