### ISSUE TITLE
internal compiler error: unexpected vtable type

### ISSUE THREAD

**Issue by yongqli** [rust-lang/rust#33956]
`error: internal compiler error: ../src/librustc_const_eval/eval.rs:1052: resolve_trait_associated_const: unexpected vtable type`

Playground link: https://is.gd/89hb8e

**Comment by sanmai-NL** [comment]
Could you provide more information? See https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md

**Comment by yongqli** [comment]
The error can be reproduced by going to the playground link and clicking Run.

**Comment by nagisa** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/29924. Thanks for the report.
