### ISSUE TITLE
[clang assert] Duplicate option categories

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/rust#33969]
I'm working on [bindgen_plugin](https://github.com/crabtw/rust-bindgen), on nightly 1.11.0. I have the following error when I try to compile: https://travis-ci.org/crabtw/rust-bindgen/jobs/133976854#L507
Bindgen use libclang, so maybe it messes up with the instance rustc uses?

**Comment by Mark-Simulacrum** [comment]
Is there a chance you could attempt to reproduce today and check if this is still a problem?

**Comment by Yamakaky** [comment]
Well, `bindgen_plugin` development was stopped and removed, so I think we can close this issue.
