### ISSUE TITLE
Index trait compiler error could be more helpful

### ISSUE THREAD

**Issue by jedahan** [rust-lang/rust#33972]
I was trying to implement the Index trait (in my first real rust project), and was running in circles, with an implementation that started like:

``` rust
impl Index<u16> for Interconnect {
    type Output = u8;

    fn index<'a>(&'a self, index: u16) -> u8 {
```

There were two things I needed to learn from @Kimundi on #rust-beginners. The first was that Index requires returning an lvalue, not a primitive. So I tried

``` rust
impl Index<u16> for Interconnect {
    type Output = &u8;

    fn index<'a>(&'a self, index: u16) -> &u8 {
```

And then I started running in circles annotating lifetimes going nowhere fast.

The second thing I learned from @Kimundi is that the signature should look more like:

``` rust
impl Index<u16> for Interconnect {
    type Output = u8;

    fn index<'a>(&'a self, index: u16) -> &Self::Output {
```

This made a lot more sense to me, and it was not clear the relationship by looking at http://doc.rust-lang.org/std/ops/trait.Index.html#examples .

So I am wondering two things:
1. Can we update http://doc.rust-lang.org/std/ops/trait.Index.html#examples to more clearly show the relationship, or is that not possible because of the fact the example requires a lifetime specifier?
2. Can the compiler error make another suggestion / explanation when the type of Output and return value of index are the same thing?

**Comment by nagisa** [comment]
`fn index<'a>(&'a self, index: u16) -> &u8 {` and `fn index<'a>(&'a self, index: u16) -> &Self::Output {` are exactly the same thing, will both equally not work as they are wrong (you need `-> &'a` not `-> &`).

**Comment by jedahan** [comment]
They resolve to the same thing in my example, but when reading them, I think its clearer that Output and the return type are related by explicitly referencing Self.Output. It was that relationship that I was confused about.

Thanks for the tip that I can remove the lifetime specifier.

**Comment by arielb1** [comment]
@nagisa

He used `Self::Output = &u8` originally, so that didn't work.

**Comment by Mark-Simulacrum** [comment]
Today we give the expected signature if the method index is defined incorrectly; I think that should help here. I'm not super clear on what still needs to be done here -- or what needed to be done originally -- @jedahan Could you perhaps clarify and give us some concrete things that confused you so we could work towards fixing them? I wasn't able to extract those from the original issue description.

```
error[E0053]: method `index` has an incompatible type for trait
  --> test.rs:8:5
   |
8  | /     fn index<'a>(&'a self, index: u16) -> u8 {
9  | |         0
10 | |     }
   | |_____^ expected &u8, found u8
   |
   = note: expected type `fn(&Interconnect, u16) -> &u8`
              found type `fn(&Interconnect, u16) -> u8`

error: aborting due to previous error(s)
```

**Comment by jedahan** [comment]
Hmm maybe explaining why the expected type is &u8, like 
```
error[E0053]: method `index` has an incompatible type for trait
  --> test.rs:8:5
   |
8  | /     fn index<'a>(&'a self, index: u16) -> u8 {
9  | |         0
10 | |     }
   | |_____^ expected &u8, found u8
   |
   = note: expected type `fn(&Interconnect, u16) -> &u8`
              found type `fn(&Interconnect, u16) -> u8`

expected type `fn(&Interconnect, u16) -> &u8`, derived from 

2   |impl Index<u16> for Interconnect {
3.  |    type Output = u8;
                    ^------- Output is u8, 

error: aborting due to previous error(s)
```

This is a bit fuzzy, but generally, showing the relationship between Output and the function signatures would be cool.

Nowadays, I feel like I don't have as much of the naive context I had before.

**Comment by estebank** [comment]
[Current output](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=fcc6428322cb78f808834c818abe35f4):

```
error[[E0053]](https://doc.rust-lang.org/stable/error-index.html#E0053): method `index` has an incompatible type for trait
 --> src/lib.rs:6:43
  |
6 |     fn index<'a>(&'a self, index: u16) -> u8 {
  |                                           ^^
  |                                           |
  |                                           expected `&u8`, found `u8`
  |                                           help: change the output type to match the trait: `&u8`
  |
  = note: expected fn pointer `fn(&S, _) -> &u8`
             found fn pointer `fn(&S, _) -> u8`
```

We provide a more targeted span and a structured suggestion when the difference is only the borrow.
