### ISSUE TITLE
ICE on Beta and Nightly; Underscores in macro definitions

### ISSUE THREAD

**Issue by zrneely** [rust-lang/rust#33983]
Underscores as "variable" names in macro definitions cause an ICE on Beta and Nightly, but the error message works as expected on Stable. A quick example can be seen here: https://is.gd/3sWZP5

**Comment by TimNN** [comment]
This has been fixed in the latest nightly, probably by #33870 (which is not yet available on the playpen).

**Comment by alexcrichton** [comment]
Yay!
