### ISSUE TITLE
LLVM APT repository used by Travis is down

### ISSUE THREAD

**Issue by sanxiyn** [rust-lang/rust#34009]
We use LLVM APT repository hosted by llvm.org in Travis build, see .travis.yml.

http://llvm.org/apt/ currently says, "APT mirror was temporary switched off due to excess load. We are working on bringing it back. Stay tuned!".

I found email titled [IMPORTANT: APT repo temporary switched off](http://lists.llvm.org/pipermail/llvm-dev/2016-May/100303.html) sent to llvm-dev on 2016-05-31, which includes more details.

**Comment by eddyb** [comment]
Maybe if we weren't downloading from it on every build it wouldn't have that ridiculous amount of I/O :(.

**Comment by sylvestre** [comment]
The LLVM apt repo is fixed and moved to http://apt.llvm.org/
