### ISSUE TITLE
Move enum_variant_size_lint out of trans_crate().

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#34018]
The `enum_variant_size_lint` is located in trans because we formerly relied on LLVM for providing type layouts. This is not true any more and after collector-driven trans lands, `enum_variant_size_lint` is the only reason we walk the HIR in `trans_crate()` at all. This should be cleaned up.

**Comment by jonas-schievink** [comment]
Collector-driven trans is now merged, so I'm rebasing my patch for this.
