### ISSUE TITLE
Type checker depends on generic type bounds too aggressively

### ISSUE THREAD

**Issue by eefriedman** [rust-lang/rust#34024]
``` rust
fn f<T>(t:T) -> Box<T> { t.into() } // accepted
fn f2<T: Into<u32>>(t:T) -> Box<T> { t.into() } // error
fn f3<T: Into<u32>>(t:T) -> Box<T> { <T as Into<Box<T>>>::into(t) } // accepted
```

This seems counterintuitive: adding the `Into<u32>` suppresses the other implementations of `Into<...>`.

**Comment by rkruppe** [comment]
Seems related or perhaps even identical to #24066

**Comment by Mark-Simulacrum** [comment]
All three forms now compile, so I'm going to close.

**Comment by Mark-Simulacrum** [comment]
Not again, I tested in the wrong directory. Re-opening....

**Comment by Mark-Simulacrum** [comment]
I'm going to close this in favor of #24066. That contains the same problem (masking other impls with a where clause).
