### ISSUE TITLE
[rustdoc] Rustdoc should render crate examples and link to them on main documentation page

### ISSUE THREAD

**Issue by burtonageo** [rust-lang/rust#34022]
Cargo allows crate developers to create examples to show off their crate's API (as shown in http://doc.crates.io/guide.html#project-layout). These examples are very useful to see how the individual items in a crate can be used together, in a way that the standard documentation doesn't capture very well.

When viewing a crate's documentation, it would be useful if examples were rendered as standard source files, and there were links to view them on the main library overview page.

**Comment by steveklabnik** [comment]
Related to, but not the same as, https://github.com/rust-lang/rust/issues/16103 https://github.com/rust-lang/cargo/issues/739

**Comment by steveklabnik** [comment]
Ah, this was filed in the rust repo, not the cargo repo. @burtonageo mind re-filing https://github.com/rust-lang/cargo/issues/new thanks!

**Comment by steveklabnik** [comment]
(Specifically, because "examples" are a Cargo feature, not a Rust feature)

**Comment by burtonageo** [comment]
@steveklabnik Done, thanks
