### ISSUE TITLE
Create dep-node representing the overall trans of each partition

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#34038]
Right now we have dep-nodes representing the trans for individual items. We should create a dep-node also for each partition. These dep-nodes will not have a `DefId` but rather the string representing the partition name. They will have incoming edges from the trans of each individual item -- some trans items, such as drop glue, may not have their own individual item and can just be lumped under the partition node. 

Upon startup, when the dep-node for a partition is deemed to be dirty, we will also delete the associated `.o` file from the disk. The same is true if the hash of the partition contents (cc #34037) changes. 

One question: could it somehow happen (I don't think so...but maybe?) that a partition just ceases to exist, but none of the inputs change? I guess one example might be changing the partition strategy? We may just want to do a little walk over the graph and delete extra nodes.

cc @michaelwoerister

**Comment by michaelwoerister** [comment]
> One question: could it somehow happen (I don't think so...but maybe?) that a partition just ceases to exist, but none of the inputs change? I guess one example might be changing the partition strategy? We may just want to do a little walk over the graph and delete extra nodes.

I think that should be covered by the code that deletes partitions when the hash does not match any more. Since the name of old partition would not show up in the new partitioning, the corresponding object file would get deleted at that point.

**Comment by nikomatsakis** [comment]
@michaelwoerister 

> Since the name of old partition would not show up in the new partitioning, the corresponding object file would get deleted at that point.

This is basically what I meant by doing an extra walk.

**Comment by nikomatsakis** [comment]
Working on this issue now in my branch.
