### ISSUE TITLE
make check-stage0-coretest does not work

### ISSUE THREAD

**Issue by stepancheg** [rust-lang/rust#34049]
`make check-stage0-coretest` fails with error:

```
src/libcoretest/lib.rs:35:1: 35:22 error: #[feature] may not be used on the beta release channel
src/libcoretest/lib.rs:35 #![feature(try_from)]
                          ^~~~~~~~~~~~~~~~~~~~~
error: aborting due to 23 previous errors
make: *** [x86_64-apple-darwin/stage0/test/coretesttest-x86_64-apple-darwin] Error 101
```

Is there any workaround?

**Comment by nagisa** [comment]
We need to make sure `$RUSTC_BOOTSTRAP_KEY` is set for tests. You can set it yourself by copying the configure’s CFG_BOOTSTRAP_KEY.

**Comment by alexcrichton** [comment]
Make's gone now, so closing.

**Comment by eddyb** [comment]
Isn't this about `./x.py test --stage 0 src/libcoretest`now? i.e.the tests themselves?

**Comment by alexcrichton** [comment]
@eddyb is that not working?

**Comment by eddyb** [comment]
That one does nothing but `test src/libcore` appears to do the right thing even at stage0, nevermind.
