### ISSUE TITLE
`mut` is accepted before constants in patterns

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#34047]
This compiles on stable/beta/nightly and `C` is resolved as a constant and not a new binding.
```
const C: u8 = 0;

fn main() {
    match 1u8 {
        mut C => {}
        _ => {}
    }
}
```

**Comment by durka** [comment]
It doesn't match though: https://is.gd/ylHuUv

**Comment by rkruppe** [comment]
@durka The example matches on 0, while C is 1, so of course it doesn't match. Conversely, `match 1u8` works just fine, and the generated code looks good too. It seems the `mut` is simply ignored.
