### ISSUE TITLE
Doc suggestion: show output for `next_back()` example

### ISSUE THREAD

**Issue by xpe** [rust-lang/rust#34065]
For me, at least, the example using `next()` and `next_back()` tells the story better if it shows the output.

I'm reading about the [DoubleEndedIterator](https://doc.rust-lang.org/std/iter/trait.DoubleEndedIterator.html)

Thanks to mbrubeck on [#rust-beginners](https://www.rust-lang.org/community.html) for these examples:

```rs
let mut iter = vec![1,2,3,4,5].into_iter(); (iter.next(), iter.next_back())
(Some(1), Some(5))
```

```rs
let mut i = vec![1,2,3,4,5].into_iter(); (i.next(), i.next_back(), i.next(), i.next_back())
(Some(1), Some(5), Some(2), Some(4))
```

I plan to come back to this issue and [submit a proper documentation patch](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#writing-documentation).

**Comment by GuillaumeGomez** [comment]
Nice idea!

**Comment by steveklabnik** [comment]
I would be happy to work with anyone who wants to work on this issue.

**Comment by GuillaumeGomez** [comment]
If no one does it, I can but I think it could be a nice first contribution.

**Comment by steveklabnik** [comment]
@xpe So, looking at this again, what is the issue here? I'm not sure what's significantly different here.
