### ISSUE TITLE
Clarify that `expr`/`stmt` in macros can may only be followed by one of: => , ;

### ISSUE THREAD

**Issue by dashed** [rust-lang/rust#34069]
For the code:

``` rust
macro_rules! foo {
    ($something:expr invalid) => {{
        // ...
    }};
}

macro_rules! bar {
    ($something:stmt invalid) => {{
        // ...
    }};
}

fn main() {
    foo!(true invalid);
    bar!(true invalid);
}
```

https://is.gd/TFIoq1

The compiler would give the following errors for this

```
error: `$something:expr` is followed by `invalid`, which is not allowed for `expr` fragments
 --> <anon>:2:22
2 |>     ($something:expr invalid) => {{
  |>                      ^^^^^^^

error: `$something:stmt` is followed by `invalid`, which is not allowed for `stmt` fragments
 --> <anon>:8:22
8 |>     ($something:stmt invalid) => {{
  |>    
```

---

I think it would be better if the error clarified that `expr`/`stmt` in macros can may only be followed by one of: => , ;

**Comment by durka** [comment]
I'm working on cleaning up the follow set checker to make this easier.

**Comment by pnkfelix** [comment]
cc @LeoTestard

**Comment by Mark-Simulacrum** [comment]
@durka Did that cleanup ever happen? The errors are still the same today.

**Comment by durka** [comment]
Um... I have no idea what I was planning to do.

**Comment by durka** [comment]
What should be done (IMO) is to refactor [`is_in_follow()`](https://github.com/rust-lang/rust/blob/838e9c5123b6fdfbfc551e529a178e04e7aacf9a/src/libsyntax/ext/tt/macro_rules.rs#L746) so that instead of a `match`, it uses a map from `&str` to some kind of `FollowSet` type which is a list of tokens/idents and also has a `Display` impl, so then the error can do:

```rust
format!("{} cannot be followed by {} -- the follow set is {}",
    frag_spec, actual_token, follow_sets[frag_spec])
```

**Comment by Phlosioneer** [comment]
Issue triage: Issue still present, and still very annoying. This should probably be labeled `Easy` and `Compliler-Errors`.
