### ISSUE TITLE
Allow defining custom optimization passes on MIR

### ISSUE THREAD

**Issue by ticki** [rust-lang/rust#34066]
Allow one to register a custom optimization on the MIR pass as a compiler plugin.

**Comment by rkruppe** [comment]
cc https://internals.rust-lang.org/t/mir-compiler-plugins-for-custom-mir-passes/3166

**Comment by nagisa** [comment]
[You can already do this](https://github.com/rust-lang/rust/blob/7de2e6dc828473b60aefe4d2140a602cbeb6d6f9/src/test/run-pass-fulldeps/mir-pass.rs), but really, really shouldn’t for anything serious. We can and most importantly *will* break your use case every half a day.

**Comment by nikomatsakis** [comment]
I am pretty reluctant to provide custom MIR passes. As @nagisa says, I don't think we'll want to provide a stable interface here -- or, at least, not for a long time.

One thing I would **eventually** consider is to make it possible to input MIR directly into the compiler (this would basically stabilize some version of MIR and have it play a very similar role to Java Bytecode). One can then imagine custom passes that do not directly interact with the compiler, but rather just serialized MIR -- very much like syntax extensions operate on token trees. (It may even be that we don't have to *serialize*, but the core idea is the same.) This would be somewhat like the design of the rather awesomely flexible [SUIF](http://suif.stanford.edu/) framework.

But that all seems rather like science fiction to me at the moment and I'm not inclined to contemplate it just now.

**Comment by bstrie** [comment]
Should we move this to the RFCs repo, since it seems to be a wishlist item that also involves stabilizing an interface?

**Comment by nagisa** [comment]
Yes, this is not really a place for such a thing and this request has a bunch of other unstable preconditions too.
