### ISSUE TITLE
Trait methods with body and >1 unnamed parameters are wrongly rejected by resolve

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#34074]
Reproduces on stable/beta/nightly.
```
trait Tr {
    // error: identifier `` is bound more than once in this parameter list
    fn f(u8, u8) {}
}

fn main() {
}
```

**Comment by eddyb** [comment]
I expect it parses as `<invalid>: u8, <invalid>: u8` and it *might* lower to HIR as `_: u8, _: u8` although nothing should care at that point about the argument list.
However, resolve running on AST, it has to treat `<invalid>` (the empty identifier) as `_`.
