### ISSUE TITLE
fn prefix mentioned on std::path::Path documentation

### ISSUE THREAD

**Issue by Undeterminant** [rust-lang/rust#34076]
Link: https://doc.rust-lang.org/std/path/struct.Path.html

One example:
"On Windows, a path is absolute if it has a prefix and starts with the root: `c:\windows` is absolute, while `c:temp` and `\temp` are not. In other words, `path.is_absolute() == path.prefix().is_some() && path.has_root()`."

This should be reworded to avoid using `prefix()`, which has since been removed.

**Comment by steveklabnik** [comment]
I would be happy to work with anyone who wants to fix this issue.

**Comment by pwlandoll** [comment]
@steveklabnik I'm new to Rust, but I could take on this one. I've been looking and I can't seem to find a drop-in substitute for `path.prefix()`. Is there a way that I'm not seeing to determine the prefix of a path?

Would it be better to just remove the whole "In other words..." sentence? I think the first half of that bullet point could be enough to convey the idea. Other than that instance, I don't see anywhere else in the documentation that references `prefix()`. 

Thanks!

**Comment by steveklabnik** [comment]
@pwlandoll great! So, it does look like prefix was just removed entirely: https://github.com/rust-lang/rust/issues/27722

So yes, I would think the "in other words" part being removed would solve the issue :+1:

**Comment by pwlandoll** [comment]
Cool. I found [two](https://github.com/pwlandoll/rust/blob/master/src/libstd/path.rs#L1075) other [instances](https://github.com/pwlandoll/rust/blob/master/src/libstd/path.rs#L1459) of the `.prefix()` being used in the `src/libstd/path.rs` file, though both functions seem to have been marked as deprecated. Should these be removed as well?

**Comment by steveklabnik** [comment]
Don't worry about it; they are actually calling [this](https://github.com/pwlandoll/rust/blob/master/src/libstd/path.rs#L1476)

**Comment by pwlandoll** [comment]
Great, that works. So for this, what would I do before the pull request?  Just a `make check` or can I do `make check-stage1-std NO_REBUILD=1`?

**Comment by steveklabnik** [comment]
Frankly, just removing a non-example line of the documentation shouldn't affect tests at all, so I wouldn't even bother running it.

**Comment by pwlandoll** [comment]
Guess I can never be too sure. Pull request it is!

**Comment by GuillaumeGomez** [comment]
I think this issue has been solved by @pwlandoll's PR. If not, don't hesitate to say it.
