### ISSUE TITLE
mem::size_of() is not a const function

### ISSUE THREAD

**Issue by DemiMarie** [rust-lang/rust#34078]
`mem::size_of()` is not a const function, even though it is _always_ a compile-time constant.  This is seemingly arbitrary and is annoying in practice.

**Comment by eefriedman** [comment]
I'm pretty sure fixing this would be a one-line patch: `std::intrinsics::size_of` is already treated as a compile-time constant.

**Comment by eefriedman** [comment]
Err, wait, nevermind, wasn't testing correctly.  Anyway, seems reasonable (although it would probably be tricky to support in certain contexts, like array bounds).

**Comment by mtanski** [comment]
This pretty annoying, you can't use it in side of trait const expressions now.

```
trait DataType {
   type DiskType;
   const DISK_SIZE: usize;
   // ...
}

struct UInt32;

impl DataType {
   const DiskType = u32;
   const DISK_SIZE: usize = std::mem::size_of<Self::DiskType>();
}
```

Clearly this doesn't work, but it seams like it should.

**Comment by burdges** [comment]
I think the active thread on this is https://github.com/rust-lang/rfcs/issues/1144 but the associated constant one https://github.com/rust-lang/rfcs/pull/1168 looked cool too.

**Comment by SimonSapin** [comment]
@eddyb tells me on IRC that implementation difficulties are now longer relevant now that type checking happens on demand.

**Comment by frewsxcv** [comment]
There's a PR open for this now: https://github.com/rust-lang/rust/issues/42859
