### ISSUE TITLE
able to invoke unstable macro 2.0

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#34079]
Stability checking for `macro_rules!` was fixed in https://github.com/rust-lang/rust/pull/48524, but uses of declarative macros 2.0 (`macro` items) are still not checked for stability.

#### ORIGINAL ISSUE:

Why does this compile?

``` rust
fn main() {
    __thread_local_inner!(i32, 42);
}
```

`__thread_local_inner` is marked `#[unstable(...)] #[allow_internal_unstable]`.

**Comment by petrochenkov** [comment]
Because macros are not checked for stability!
At least this was the case when I made stability annotations on public macros mandatory in hopes of a better future.

**Comment by jseyfried** [comment]
cc me

**Comment by abonander** [comment]
I'm looking into implementing this, however are we just looking at `macro_rules!` macros for now or proc-macro and syntax extension invocations as well?

cc @nrc

**Comment by petrochenkov** [comment]
@abonander 
I'm reopening this because macros 2.0 (`macro` items) are not checked for stability yet.

**Comment by abonander** [comment]
@petrochenkov do you want to edit the issue/title/labels to reflect that since this still looks like it's for `macro_rules!` macros? Or should we just open a new issue?

**Comment by petrochenkov** [comment]
@abonander 
Updated.

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/62042
