### ISSUE TITLE
ICE when const is used as `X;` in nested function

### ISSUE THREAD

**Issue by Peach1** [rust-lang/rust#34107]
The following crashes the Rust compiler on nightly:

```rust
const X: i32 = 5;

fn main() {
    fn q() {
        X;
    }
}
```

"thread 'rustc' panicked at 'assertion failed: type_is_zero_size(bcx.ccx(), bcx.tcx().node_id_to_type(expr.id))', ../src/librustc_trans/expr.rs:158"

**Comment by niconii** [comment]
Even worse, this produces the same result:
```rust
const X: i32 = 5;

fn main() {
    X;
}
```

**Comment by c3st7n** [comment]
Dupe of https://github.com/rust-lang/rust/issues/34008?

**Comment by niconii** [comment]
Looks like that is indeed the case, so I'll close in favor of that one.
