### ISSUE TITLE
move `temporary_cstring_as_ptr` from clippy to rustc

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#34111]
Quoting the docs of the lint:

>**What it does:** This lint checks for getting the inner pointer of a temporary CString.
>**Why is this bad?** The inner pointer of a CString is only valid as long as the CString is alive.

~~@akaDemik~~ someone [found in a recent discussion](https://users.rust-lang.org/t/you-should-stop-telling-people-that-safe-rust-is-always-safe/6094/8?u=oli_obk) that there are [hundreds of `.unwrap().as_ptr()` calls](https://github.com/search?l=rust&q=%22unwrap%28%29.as_ptr%28%29%22&ref=searchresults&type=Code&utf8=%E2%9C%93) to be found on github (not all of them UB, but many).

I believe this amount of accidental UB is reason enough to add a "new" lint to rustc that prevents misusing this specific easy-to-misuse method.

**Comment by aka-demik** [comment]
We are different aka-demik's ;)

**Comment by steveklabnik** [comment]
New lints pretty much require RFCs these days.

**Comment by durka** [comment]
Or we could just deprecate the method (with a message warning of the potential for misuse) and provide `fn with_ptr<F: FnOnce(*const c_char)>(&self, f: F) { f(self.as_ptr()); }` instead. [Example.](https://is.gd/Iq8n7h)

**Comment by durka** [comment]
rust-lang/rfcs#1642 submitted.

**Comment by oli-obk** [comment]
Let's continue further discussion on the rfc
