### ISSUE TITLE
Confusing type of error when reference which is passed to function does not suited in mutability

### ISSUE THREAD

**Issue by olegabyst** [rust-lang/rust#34116]
Consider next snippet of code

```
struct Foo<'a> {
    x: &'a i32
}

impl<'a> Foo<'a> {
    fn new(x: &'a i32) -> Foo<'a> {
        Foo {
            x: x,
        }
    }
}

fn main() {
    let mut x = 33;
    let foo1 = Foo::new(&mut x);
    let foo2 = Foo::new(&mut x);
}
```

as result we have next error(rustc 1.9.0):

```
error: cannot borrow `x` as mutable more than once at a time [E0499]
```

But for me it's seems confusing, because I expected 2 variants:
1) compiler throw an error since `Foo::new` expect an immutable reference instead of mutable.
2) compiler understand that in both calls to `Foo::new` the resulted instances of `Foo` borrow `x` by immutable reference.
So, I think compiler should be either more smart or more strict . What do you think?

**Comment by TimNN** [comment]
Regarding the two variants you expect:

1) The compiler always allows you to use a mutable reference as if it was immutable, because not doing so would often be very inconvenient. This means that the following works, for example:

```rust
fn main() {
    let mut x = 33;
    let mut_ref = &mut x;
    let foo1 = Foo::new(mut_ref);
    let foo2 = Foo::new(mut_ref);
}
```

2) Even if the compiler would realise for `foo1` that you only borrow `x` immutably, it would still complain about the `&mut x` of `foo2` but now because you can't ``cannot borrow `x` as mutable because it is also borrowed as immutable``.

**Comment by OlegTsyba** [comment]
> 2) Even if the compiler would realise for foo1 that you only borrow x immutably, it would still complain about the &mut x of foo2 but now because you can't cannot borrow `x` as mutable because it is also borrowed as immutable.

yeah, It would be much better error explanation as for me, and  maximally close to what I expected.

**Comment by Mark-Simulacrum** [comment]
Hmm, I think there's not much we can change here. It would confuse me when the compiler said that `&mut T` is borrowing T as immutable--and that confusion seems worse than the double-borrow confusion. Ideally, we'd specify that `Foo::new` doesn't take a mutable borrow, but when to do that is hard to decide on--detecting an existing warning and only then doing that is probably nearly impossible. As such, I'm going to close, but please reopen if there's any concrete suggestions as to what could be done better that doesn't seem incongruous with the local source code.
