### ISSUE TITLE
Remove -Zinput-stats

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#34121]
Like #30505, there's no need for this command line flag, and `debug!` logging should be used instead.

**Comment by nrc** [comment]
I'll note that unlike #30505, the intended consumers of `-Zinput-stats` are tools, rather than users.

**Comment by Mark-Simulacrum** [comment]
I propose that we close this issue, as discussed in #37426: tools find it easier to parse output when given in the limited form of `-Zinput-stats` versus `debug!` logging.

**Comment by jonas-schievink** [comment]
Yeah, sounds like a good idea, since this is being used by tools.
