### ISSUE TITLE
add a description of how to fix an E-needstest issue to the contributor page

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#34135]
One of the easiest ways to get started in Rust is to add test cases for `E-needstest` bugs, but we don't have an easy description of the steps involved from what I could find. It actually touches on a surprising number of bits of convention, so it'd be worth writing down and adding to the https://www.rust-lang.org/contribute-bugs.html page (or some similar page).

cc @brson 

Here are some notes [from IRC](https://botbot.me/mozilla/rust-internals/2016-06-07/?msg=67426777&page=2) describing the steps:

```
05:49 <•nmatsakis> imjacobclark: well take https://github.com/rust-lang/rust/issues/25579 as an example
05:50 <•nmatsakis> imjacobclark: you basically would grab the minified example from https://github.com/rust-lang/rust/issues/25579#issuecomment-103199940
05:50 <•nmatsakis> imjacobclark: then make a file in src/test/run-pass named issue-25579.rs which contains that example, along with the standard license header (you can grab it from some neighboring file)
05:50 <•nmatsakis> imjacobclark: test that `make check` passes (or `make check-stage1-rpass` at least, which will run the tests w/o as much bootstrapping etc)
05:51 <•nmatsakis> imjacobclark: then open a pull request; you can put `r? @nikomatsakis` in the header to have me review it; add Fixes #25579
```

**Comment by nikomatsakis** [comment]
it occurs to me this should probably be filed on the rust-www repo.

**Comment by imjacobclark** [comment]
👍

**Comment by brson** [comment]
I added a corresponding issue to the www tracker. Don't mind leaving this open so it can be found though.

**Comment by steveklabnik** [comment]
closing; we should keep issues on the right pages, and anyone searching will still find closed issues too
