### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by valarauca** [rust-lang/rust#34144]
Error: While building LLVM (as part of rust) it fails. 

Steps to reproduce:

```
   $ git clone --depth 1 github.com/rust-lang/rust
   $ cd rust
   $ ./configure
   $ make && make install
```

Alternative Steps to reproduce:

```
$ wget https://static.rust-lang.org/dist/rustc-1.9.0-src.tar.gz
$ tar xf rustc-1.9.0-src.tar.gz
$ cd rustc-1.9.0
$ ./configure
$ make && make install
```

Error Message:

```
/home/-snip-/rust/src/llvm/lib/Support/ErrorHandling.cpp: In function ‘std::error_code llvm::mapWindowsError(unsigned int)’:
/home/-snip-/rust/src/llvm/lib/Support/ErrorHandling.cpp:152:21: error: ‘__MSABI_LONG’ was not declared in this scope
     MAP_ERR_TO_COND(ERROR_ACCESS_DENIED, permission_denied);
                     ^
/home/-snip-/rust/src/llvm/lib/Support/ErrorHandling.cpp:147:8: note: in definition of macro ‘MAP_ERR_TO_COND’
   case x:                                                                      \
        ^
/usr/bin/rm: cannot remove '/home/-snip-/rust/x86_64-pc-windows-gnu/llvm/lib/Support/Release/ErrorHandling.d.tmp': No such file or directory
```

Platform details:

Windows 7 x86_64 w/ mingw64

gcc v5.3.0 (same for g++)

git v2.8.2

make v4.2

**Comment by seventh-chord** [comment]
A similar error is mentioned in #20900, you might want to look at that.  
Personally I could not get the fixes suggested there to work. Adding `#define __MSABI_LONG(x) x` to `src/llvm/lib/Support/ErrorHandling.cpp` at line 146 made it compile, but I do not think this is a good solution.

**Comment by valarauca** [comment]
On the most recent version https://i.imgur.com/a6tYzrn.png

Repeated your steps given. No change.

**Comment by Mark-Simulacrum** [comment]
Could someone attempt to reproduce this and report back? I don't have access to a windows system.

**Comment by valarauca** [comment]
I've played around with this and I've _slightly_ managed to reproduce on Windows with other projects.

It appears when you read/write/delete something too often windows defenders locks you out to flag it and upload it to home base to ensure it isn't a virus.
