### ISSUE TITLE
Compiler panic caused by power_assert

### ISSUE THREAD

**Issue by brainwad** [rust-lang/rust#34156]
My compiler panics consistently when I use power_assert and override the builtin asserts.

I tried this code:

#![feature(plugin)]
#![plugin(power_assert(override_builtins))]

#[cfg(test)]
mod tests {
    #[test]
    fn test_equal() {
        assert!(vec![":)"] == vec![":)"]);
    }
}

I expected to see this happen: code compiles

Instead, this happened: compiler panics

## Meta

`rustc --version --verbose`:
rustc 1.11.0-nightly (1c975eafa 2016-06-05)
binary: rustc
commit-hash: 1c975eafa934e291e4f94b7252faae767de17313
commit-date: 2016-06-05
host: x86_64-pc-windows-gnu
release: 1.11.0-nightly

Backtrace:

error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'fold_mac disabled by default', ../src/libsyntax\fold.rs:174
stack backtrace:
   0:         0x6f283fbc - <unknown>
   1:         0x6f2835cf - <unknown>
   2:         0x6f244ac4 - <unknown>
   3:         0x670839c2 - <unknown>
   4:         0x670b4fd7 - <unknown>
   5:         0x6709facc - <unknown>
   6:         0x67096d2b - <unknown>
   7:         0x670969d3 - <unknown>
   8:         0x670968c5 - <unknown>
   9:         0x670a0a24 - <unknown>
  10:         0x67099155 - <unknown>
  11:         0x670969d3 - <unknown>
  12:         0x670968c5 - <unknown>
  13:         0x67087710 - <unknown>
  14:         0x6708753e - <unknown>
  15:         0x670430c8 - <unknown>
  16:         0x6ea4242e - <unknown>
  17:         0x62df0d57 - <unknown>
  18:         0x62e5998a - <unknown>
  19:         0x62e5e15c - <unknown>
  20:         0x62e65950 - <unknown>
  21:         0x62e64ab8 - <unknown>
  22:         0x62e6457e - <unknown>
  23:         0x62e437c0 - <unknown>
  24:         0x62e642af - <unknown>
  25:         0x62e3950a - <unknown>
  26:         0x62e3985a - <unknown>
  27:         0x62e94584 - <unknown>
  28:         0x62e94211 - <unknown>
  29:         0x62e93e20 - <unknown>
  30:         0x62e93b7f - <unknown>
  31:         0x62e46f72 - <unknown>
  32:         0x62e4398c - <unknown>
  33:         0x62e5307d - <unknown>
  34:         0x62e52cad - <unknown>
  35:         0x62e500e8 - <unknown>
  36:         0x62e947d9 - <unknown>
  37:         0x62e94211 - <unknown>
  38:         0x62e93e20 - <unknown>
  39:         0x62e93b7f - <unknown>
  40:         0x62e48519 - <unknown>
  41:         0x62e4398c - <unknown>
  42:         0x62e53475 - <unknown>
  43:         0x62e52cad - <unknown>
  44:         0x62e500e8 - <unknown>
  45:         0x62e947d9 - <unknown>
  46:         0x62e94211 - <unknown>
  47:         0x62e93e20 - <unknown>
  48:         0x62e93b7f - <unknown>
  49:         0x62e48519 - <unknown>
  50:         0x62e4398c - <unknown>
  51:         0x62e532cc - <unknown>
  52:         0x62ea2fba - <unknown>
  53:         0x62ea4397 - <unknown>
  54:         0x61815d25 - <unknown>
  55:         0x617c770a - <unknown>
  56:         0x617975da - <unknown>
  57:         0x61787330 - <unknown>
  58:         0x61783dc8 - <unknown>
  59:         0x6f293ab8 - <unknown>
  60:         0x617849ec - <unknown>
  61:         0x6f281339 - <unknown>
  62:     0x7ff936988101 - <unknown>

**Comment by TimNN** [comment]
I don't believe this is a problem with the rust compiler but rather with the `power_assert` crate, so you should probably report this issue [over there](https://github.com/gifnksm/power-assert-rs). 

Also, if I understand the situation correctly, you may be able to work around this problem by not using any macros inside the `assert!` macro.

**Comment by nagisa** [comment]
What @TimNN said seems to be true indeed. power_assert is a compiler plugin and it misbehaving can easily cause ICEs to happen.

Closing as not-ours.
