### ISSUE TITLE
`std::ops::Range` does not implement `std::hash::Hash`

### ISSUE THREAD

**Issue by alexander255** [rust-lang/rust#34170]
`Range` should implement `Hash` if the value it holds implements `Hash`.

Something like:

```
impl<T> core::hash::Hash for core::ops::Range<T> where T: core::hash::Hash {
    fn hash<H>(&self, state: &mut H) where H: core::hash::Hasher {
        core::hash::Hash::hash(self.start, state);
        core::hash::Hash::hash(self.end, state);
    }
}
```

**Comment by alexander255** [comment]
The same goes for `RangeStart`, `RangeEnd` and `RangeFull` of course.

**Comment by durka** [comment]
Can we just derive it?

**Comment by alexander255** [comment]
If we'd derive it, then all type parameters would be required to implement `Hash` if IIRC.

**Comment by sfackler** [comment]
Yep, but that's the behavior we'd want anyway, yes?

**Comment by durka** [comment]
Yes. Not sure how you'd hash a range with unhashable endpoints.

**Comment by alexander255** [comment]
@sfackler No, if the thing that the range is variant over is not hashable, then the `Range` itself shouldn't be hashable either. Doing `#[derive(Hash)]` would require the type parameter to *always* be hashable, which I don't see any reason for (besides the fact that it would break compatibility).

**Comment by sfackler** [comment]
@alexander255 I don't believe that's how `#[derive(Hash)]` works - all it will do is generate a hash impl that looks identical to the one in your original post. I does not modify bounds on the struct definition itself.

**Comment by alexander255** [comment]
@sflacker You're right:
Example with manual impl: https://is.gd/Jj6KRL
Example with derive: https://is.gd/W4O8ai

I was under the strong impression that `#[derive(Hash)]` will abort the compilation, requiring you to bound the type parameters appropriately (but apparently it's smarter than that).

**Comment by alexander255** [comment]
@durka Thanks!
