### ISSUE TITLE
doc: Broken link in "No stdlib" Page.

### ISSUE THREAD

**Issue by somemetricprefix** [rust-lang/rust#34176]
https://github.com/rust-lang/rust/blob/master/src/libstd/sys/common/unwind/gcc.rs
in the last paragraph is broken.

**Comment by steveklabnik** [comment]
Thanks. Given that it's an unstable page, this will happen from time to time.

**Comment by steveklabnik** [comment]
This was actually fixed at some point; the fix is currently in beta, so will be part of Rust 1.11. Thanks!
