### ISSUE TITLE
Is it possible to just use default partially.

### ISSUE THREAD

**Issue by ngaut** [rust-lang/rust#34197]
Source is here https://github.com/pingcap/tikv/blob/master/src/raft/raft.rs#L230
There are many redundant assignments. Like 0, None, and Default::default.
Can i make this code cleaner by using default value partially?  Thanks.

**Comment by steveklabnik** [comment]
Could you re-post this to the users forum at users.rust-lang.org please? We try to keep github issues for bugs only. Thanks!
