### ISSUE TITLE
rust-gdb Python Exception <type 'exceptions.TypeError'> Could not convert Python object: None

### ISSUE THREAD

**Issue by ctaggart** [rust-lang/rust#34205]
Working on https://github.com/ctaggart/rusty-vscode/issues/11, I added a Visual Studio Code extension that enables debugging with GDB. I installed latest stable GDB for Debian Jessie. The good news is I can hit breakpoints. The bad news is that I'm getting Python exceptions trying to inspect some variables. My guess is that it was related to the `rust-gdb` that is being used. Perhaps I should figure out how to compile that latest gdb from source with native rust support.

```
vscode@7e105e236ffa:~/demo$ gdb --version
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1

vscode@7e105e236ffa:~/demo$ rustup show
stable-x86_64-unknown-linux-gnu (default)
rustc 1.9.0 (e4e8b6668 2016-05-18)
```

Here, I'm using Nickel and I was hoping to be able to view the Request object, but trying to expand self resulted in a 

```
Python Exception <type 'exceptions.TypeError'> Could not convert Python object: None.
```

![image](https://cloud.githubusercontent.com/assets/80104/15971833/003f79e0-2ef0-11e6-92dc-b04f63401d49.png)

**Comment by tromey** [comment]
It's handy if you can `set python print-stack full` in gdb and then recreate; this will show the full Python stack at the point of the error.

**Comment by siddontang** [comment]
I meet the same problem

```
(gdb) set python print-stack full
(gdb) p bytes
$18 = Traceback (most recent call last):
  File "/usr/local/lib/rustlib/etc/gdb_rust_pretty_printing.py", line 217, in to_string
    (length, data_ptr) = rustpp.extract_length_and_ptr_from_slice(self.__val)
  File "/usr/local/lib/rustlib/etc/debugger_pretty_printers_common.py", line 322, in extract_length_and_ptr_from_slice
    length = slice_val.get_child_at_index(length_field_index).as_integer()
  File "/usr/local/lib/rustlib/etc/gdb_rust_pretty_printing.py", line 75, in get_child_at_index
    child = GdbValue(self.gdb_val[gdb_field])
TypeError: Could not convert Python object: <gdb.Field object at 0x7ff7ab72a288>.
```

**Comment by atulatri** [comment]
Same issue here.

**Comment by ctaggart** [comment]
@siddontang & @atulatri, I forget to close this issue when I solved my problem. I solved my problem here by setting `gdbpath` to `rust-gdb` like I mentioned in https://github.com/ctaggart/rusty-vscode/issues/11#issuecomment-225102376.

**Comment by atulatri** [comment]
I am not getting this issue with rust nighty.
