### ISSUE TITLE
Confusing warning note

### ISSUE THREAD

**Issue by dhad05** [rust-lang/rust#34215]
Considering this code:
https://play.rust-lang.org/?gist=5970880acf87ad712420af51680b1f0e&version=nightly&backtrace=0
The compiler says that `enum A` is never used, but it is actually used in `struct S`, thus removing it will lead to errors. I think this is very confusing. 
// sorry for bad english

**Comment by TimNN** [comment]
This is by design, also see [this comment](https://github.com/rust-lang/rust/issues/18618#issuecomment-61709955) (and the one above) on an older issue.
