### ISSUE TITLE
duplicated errors for invalid derives

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#34229]
[This code](https://is.gd/VSYc2K) attempts to derive `PartialOrd` in an invalid situation, and is rewarded with a barrage of duplicate errors:

``` rust
#[derive(PartialEq)] struct Comparable;
#[derive(PartialEq, PartialOrd)] struct Nope(Comparable);
```

The error `the trait core::cmp::PartialOrd is not implemented for the type Comparable` only appears once. However, the error `binary operation < cannot be applied to type Comparable` (along with note `an implementation of std::cmp::PartialOrd might be missing for Comparable`... gee, really?) appears **eight** times, four for `<` and four for `>`.

I assume this is because an error is generated at several points within the (invisible) generated `PartialOrd` implementation. But since they are all assigned the same span, maybe we can deduplicate.

**Comment by oli-obk** [comment]
Would the following be possible?:

1. encounter `T: Trait` bound failure
2. report error
3. make `T: Trait` true for the further compilation

It doesn't address all cases, but it would significantly improve this one.

**Comment by durka** [comment]
Should this be a UI or compile-fail test? I think cfail is out of favor these days, but a UI test will have to include a bug: https://github.com/rust-lang/rust/pull/45519#issuecomment-341181857

**Comment by michaelwoerister** [comment]
It should be a UI test, I'd say and we should fix that bug `:)`
