### ISSUE TITLE
Markdown not used in navigation of doc.rust-lang.org/book

### ISSUE THREAD

**Issue by donaldpipowitch** [rust-lang/rust#34224]
E.g. "4.26. `const` and `static`" is not formatted as markdown in the navigation. 

I think the `SUMMARY.md` is loaded here: https://github.com/rust-lang/rust/blob/e1195c24bb567019d7cdc65bf5a4c642e38475d1/src/tools/rustbook/build.rs#L209
The other files are probably rendered here: https://github.com/rust-lang/rust/blob/e1195c24bb567019d7cdc65bf5a4c642e38475d1/src/tools/rustbook/build.rs#L82

I'm not sure where `SUMMARY.md` should be rendered.

**Comment by steveklabnik** [comment]
This is likely to be fixed when the new book lands, but if someone wants to modify rustbook in the meantime, please do!

**Comment by steveklabnik** [comment]
rustbook is slated to die at this point, to be replaced by mdbook. I'm gonna give this a close, thanks!

**Comment by donaldpipowitch** [comment]
What is mdbook? Could you add a link? Thanks.

**Comment by steveklabnik** [comment]
Whoops, sorry! https://github.com/azerupi/mdBook

**Comment by donaldpipowitch** [comment]
Cool, thank you!
