### ISSUE TITLE
allow syntax::ext::base::MultiItemModifier to return multiple items

### ISSUE THREAD

**Issue by llogiq** [rust-lang/rust#34223]
As of yet, MultiItemModifiers can only return a single item, which can lead to problems with expanding macros or preprending items, e.g. `extern crate foo; use foo::bar` to avoid requiring users to manually import items.

A simple solution would be to change Annotatable to work on `SmallVec`s of `Item`s/`TraitItem`s/`ImplItem`s. However, this would break all procedural macros using this interface.

**Comment by jseyfried** [comment]
@llogiq c.f. #34253
