### ISSUE TITLE
Rustdoc crams struct fields into same line

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#34235]
If you look at the rustdoc generated page for structs with public fields, there is a `Field` section which lists all the fields.

There is no newline separation between the fields. They look crammed up, and reading them is very unergonomic.

See this example: https://doc.rust-lang.org/libc/x86_64-unknown-linux-gnu/libc/struct.Dl_info.html

Note: I don't mean the first section which looks like rust code, but I mean the section below which essentially repeats the fields.

Confirmed to exist at least with Firefox 47.0 and `rustdoc 1.11.0-nightly (915b003e3 2016-06-02)`, as well as whatever rustdoc has been used to generate above doc.

**Comment by steveklabnik** [comment]
There's a PR open https://github.com/rust-lang/rust/pull/34234

**Comment by est31** [comment]
@steveklabnik regarding your question in #34234 : I've done a nightly "bisect" using rustup override, and the last nightly that worked was `6e00b5556 2016-05-29`, the first with the bug was `601eb13dc 2016-05-31`.

So there are [46 possible commits](https://github.com/rust-lang/rust/compare/6e00b5556...601eb13dc) which could have introduced the regression.

Also note that the 05-29 version hasn't listed the types of the fields, whereas the 05-31 version does list them. Maybe this is related.

**Comment by GuillaumeGomez** [comment]
It has been fixed.
