### ISSUE TITLE
Safe wrapper for intrinsics::discriminant_value?

### ISSUE THREAD

**Issue by Ms2ger** [rust-lang/rust#34244]
It doesn't seem like it does anything unsafe.

**Comment by nagisa** [comment]
cc https://github.com/rust-lang/rust/issues/24263

**Comment by durka** [comment]
A wrapper [has been added](https://doc.rust-lang.org/beta/std/mem/fn.discriminant.html) though for now it hides the actual numerical value to prevent stability issues.
