### ISSUE TITLE
Book section on FFI with nullable pointers doesn't explain None == null.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#34250]
The paragraph in question (https://doc.rust-lang.org/book/ffi.html#the-nullable-pointer-optimization):

> # The "nullable pointer optimization"

> Certain types are defined to not be `null`. This includes references (`&T`,
> `&mut T`), boxes (`Box<T>`), and function pointers (`extern "abi" fn()`).
> When interfacing with C, pointers that might be null are often used.
> As a special case, a generic `enum` that contains exactly two variants, one of
> which contains no data and the other containing a single field, is eligible
> for the "nullable pointer optimization". When such an enum is instantiated
> with one of the non-nullable types, it is represented as a single pointer,
> and the non-data variant is represented as the null pointer. So
> `Option<extern "C" fn(c_int) -> c_int>` is how one represents a nullable
> function pointer using the C ABI.

While the paragraph does a good job at explaining when this optimizations happens (although it's missing the fact that the optimization can now look for deeply nested fields to use), it doesn't explicitly mention that `None` represents the "NULL" value and that `Some(function)` is how you create non-"NULL" values, nor does it have a code example.

What this can lead to is code that transmutes because it might not be entirely clear that there's a safe way to create values of that type.

cc @steveklabnik

**Comment by steveklabnik** [comment]
I'm not really working on the old book anymore, but would love to take a patch for this if someone would like to write one.

**Comment by sanmai-NL** [comment]
@steveklabnik: could you point me to the new book?

**Comment by steveklabnik** [comment]
http://rust-lang.github.io/book

**Comment by durka** [comment]
@eddyb it does say

> When such an enum is instantiated with one of the non-nullable types, it is represented as a single pointer, and the non-data variant is represented as the null pointer.

Do you just think it should more explicitly spell out that `Option::None` is an example of a "non-data variant", and include an example?

**Comment by eddyb** [comment]
@durka Yes, I think the description might not be clear without the definition of `Option` in sight.
Also, the description seems to talk about the type-parametrized `Option`, although that's not a requirement for triggering the optimization.

**Comment by durka** [comment]
@eddyb agreed, I'll mention that too. And IMO it's unfortunate to call this
an "optimization", since it is guaranteed, but I don't have a better term.

**Comment by durka** [comment]
see #34258
