### ISSUE TITLE
Add a feature like cgo

### ISSUE THREAD

**Issue by nabeelomer** [rust-lang/rust#34273]
[cgo](https://github.com/golang/go/wiki/cgo) is a feature of the Go programming language that allows C code to be included in Go code and C functions to be directly called from Go without having to write any wrappers. This sort of a feature would be really helpful for writing things like Linux kernel modules and other software that may link to C code.

**Comment by nagisa** [comment]
There’s a https://github.com/crabtw/rust-bindgen.

---

Feature requests like these should go to the [rfcs repo](https://github.com/rust-lang/rfcs/issues). Please open an issue there. Thanks!

(closing because wrong repository)
