### ISSUE TITLE
Simplify rustdoc URLs

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#34271]
The URLs for items in Rustdoc are Byzantine combinations of the kind of item, the parent (module/struct/enum, etc) and the name of the item. These are impossible for tools to synthesise without deep knowledge of the program structure (and pretty difficult even with that knowledge). They should be much simpler.

Question: are there any advantages of the current scheme?

**Comment by steveklabnik** [comment]
I find them _kind_ of okay to write by hand. Not great, but not terrible. Would welcome improvements.

**Comment by alexcrichton** [comment]
I personally type the path specifically with modules (e.g. `/std/net/`) although I'd also be fine if we emitted a bunch more redirect pages like `/__redirect/<id>.html` which just goes to the right place.

**Comment by steveklabnik** [comment]
Triage: I talked extremely briefly with @nrc two weeks ago in Hawaii and I vaguely remember him saying "yeah we're giving up on this." Is this true? Should this be closed? My memory is very likely to be faulty.

**Comment by steveklabnik** [comment]
Oh wait, https://github.com/rust-lang/rust/pull/35236 was a re-do of https://github.com/rust-lang/rust/issues/35020 which was supposed to close this. So I think this should be closed.
