### ISSUE TITLE
bootstrap.py --stage {1,2} --step doc-rustc fails

### ISSUE THREAD

**Issue by TimNN** [rust-lang/rust#34275]
`bootstrap.py --stage {1,2} --step doc-rustc` fails with:

 ```
'failed to copy `$PWD/build/x86_64-unknown-linux-gnu/stage1-test/x86_64-unknown-linux-gnu/doc/.stamp` to `$PWD/build/x86_64-unknown-linux-gnu/doc/.stamp`: No such file or directory (os error 2)', $RUST/src/bootstrap/build/util.rs:46
```

Note that there is no `doc` directory in `$PWD/build/x86_64-unknown-linux-gnu/`

Creating that directory fixes this problem but leads to another problem:

```
'fs::remove_dir_all(&out_dir) failed with No such file or directory (os error 2)', $RUST/src/bootstrap/build/doc.rs:183
``` 

This is because there is no `doc` directory in `$PWD/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/`, which the tool tries to `lstat` (checked with `strace`).

Creating that directory fixes the problem.

Note that for stage 2, all directories starting at `stage2-rustc` needed to be created.

**Comment by alexcrichton** [comment]
Oh dear yeah this isn't tested very well so I wouldn't be surprised if it breaks every now and then, thanks for the report!

**Comment by alexcrichton** [comment]
oops

**Comment by TimNN** [comment]
Yeah, I expected that (the not very well tested) so when I needed to build the compiler docs I decided to try using rust build by that.

By the way, I'm a little confused by the following:

The rustbuild configuration includes a `build.compiler-docs` key, which is also present in the `Config` struct as `compiler_docs`, however the field [does not seem to be ever used](https://github.com/rust-lang/rust/search?q=compiler_docs&type=Code&utf8=%E2%9C%93).

**Comment by alexcrichton** [comment]
Oh there should probably be a line in `step.rs` which adds that target to a dependency of the `docs` target, probably just got lost along the way somewhere by accident :(
