### ISSUE TITLE
dead_code lint fires on struct despite its static method getting called

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#34276]
```rust
struct A;
trait As {
    fn banana();
}

impl As for A {
    fn banana() { panic!("banana"); }
}

trait Bs<T: As> {
    fn do_it(&self) { T::banana() }
}

struct B;

impl Bs<A> for B {}

fn main() {
    Bs::do_it(&B)
}
```

When compiled, the dead_code lint fires, claiming that `A` is not used.

This code, when [run](https://play.rust-lang.org/?gist=23a48c7157f276c57e2035d9540d1ab9&version=stable&backtrace=0), panics with `banana`, thus proving that `A` is, in fact, used.

Possibly similar to https://github.com/rust-lang/rust/issues/32998.

**Comment by apasel422** [comment]
Duplicate of #19613?

**Comment by nagisa** [comment]
Seems to be right. I’ll update the said issue. Thanks @apasel422!
