### ISSUE TITLE
thread 'rustc' panicked at 'const fn has no result expression', ../src/libcore/option.rs:699

### ISSUE THREAD

**Issue by tupshin** [rust-lang/rust#34281]
Very easy to [reproduce](https://is.gd/PSTVmh) this error with rustc 1.11.0-nightly (ab0b87458 2016-06-13)

Play link above. Entire code below:

`#![feature(const_fn)]

const fn test_const() -> bool {}

fn main() {
    test_const();
}`

**Comment by oli-obk** [comment]
duplicate of #33031

**Comment by Mark-Simulacrum** [comment]
Closing as duplicate (and #33031 is also closed now).
