### ISSUE TITLE
Add link to XID_start and XID_continue definitions in language reference

### ISSUE THREAD

**Issue by casey** [rust-lang/rust#34289]
It would be great if the [identifiers section of the language reference](https://doc.rust-lang.org/reference.html#identifiers) linked to some kind of definition of `XID_start` and `XID_continue`. Just searching for "xid_start xid_continue" in google doesn't give good results.

There might be a better page out there, but this is the best reference I could find:
http://www.unicode.org/Public/4.1.0/ucd/DerivedCoreProperties.txt

**Comment by durka** [comment]
There is [this](http://unicode.org/cldr/utility/list-unicodeset.jsp?a=%5B%3AXID_Start%3A%5D&abb=on&g=&i=)...

**Comment by casey** [comment]
Nice find! That looks much nicer.

**Comment by steveklabnik** [comment]
Triage; this is a great first bug for anyone wanting to get started working on docs. I am happy to mentor anyone who's interested in tackling this!

**Comment by steveklabnik** [comment]
Note: the reference has moved to https://github.com/rust-lang-nursery/reference, so PRs would go there.

I'm going to leave this one around since it's such a great first bug, but ideally, it would be filed on that repo.

**Comment by VinithKrishnan** [comment]
I still don't see any link to the definitions of XID_start and XID_continue on the reference page.

**Comment by steveklabnik** [comment]
@VinithKrishnan yes, this bug is still open. Would you be interested in adding it?

**Comment by VinithKrishnan** [comment]
Yes,I would!

**Comment by steveklabnik** [comment]
@VinithKrishnan wonderful! 

https://github.com/rust-lang-nursery/reference is where the reference lives now. Note that these two URLs look a little different:

* https://doc.rust-lang.org/stable/reference.html
* https://doc.rust-lang.org/beta/reference/

that is, we've split the reference up into pages as well as moved it into its own repository.

The identifiers section now lives here: https://github.com/rust-lang-nursery/reference/blob/master/src/identifiers.md

So, sending a PR there to add these links should take care of it.

Please let me know if you need any more help than that! I'd be happy to answer any questions.

**Comment by steveklabnik** [comment]
closed by https://github.com/rust-lang-nursery/reference/pull/48, thank you @VinithKrishnan !
