### ISSUE TITLE
Cow::clone should do shallow copies?

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#34284]
In a recent PR [it was pointed out](https://github.com/rust-lang/rust/pull/33777#issuecomment-225425608) that cloning a Cow shouldn't ever need to allocate - the cloned Cow could borrow a pointer to the original.

**Comment by bluss** [comment]
No, this is not possible

```rust
impl<'a, T> Clone for Cow<'a, T> {
    fn clone<'b>(&'b self) -> Cow<'a, T> { ... }
}
```

The owned variant can only be borrowed for the scope `'b`, not the scope `'a` that is required.

**Comment by alexcrichton** [comment]
Aha excellent point!
