### ISSUE TITLE
Macro to check if a function returns a specific error

### ISSUE THREAD

**Issue by kless** [rust-lang/rust#34299]
At testing, it's also necessary to have a macro to checking a specific error returned by a function.

This macro gets it, so it could be added to standard library:

```
    // Checks that the function returns the given error.
    macro_rules! test_err {
        ($func:expr, $err:expr) => ({
            let func = $func;

            match func {
                Err(ref e) if *e == $err => (),
                Err(e) => panic!("got error {:?}, want {:?}", e, $err),
                _ => panic!("want error {:?}", $err),
            }
        })
    }
```

**Comment by durka** [comment]
I think you can just use `assert_eq!($func, Err($err))` for this.

**Comment by steveklabnik** [comment]
New macros require an RFC, as they're global and insta-stable. https://github.com/rust-lang/rfcs is the place to go, and in fact, there's a brand-new RFC you could work off of: https://github.com/rust-lang/rfcs/pull/1653 So please pursue this over there!

Thanks!
