### ISSUE TITLE
Reassign E0406 to be thrown when undeclared associated type appears in function signature.

### ISSUE THREAD

**Issue by cynicaldevil** [rust-lang/rust#34301]
Currently, when an undeclared associated type is used in a function signature within a trait body, like:
```rust
trait Foo {
    type Bar;
    //error: Baz is used but not declared
    fn return_bool(&self, &Self::Bar, &Self::Baz) -> bool;
}
```
it throws [E0220](https://doc.rust-lang.org/error-index.html#E0220), which isn't really helpful in this situation. Also, I found [E0406](https://github.com/rust-lang/rust/blob/7d2f75a953b5645d3a336b2978b48b60d310bf54/src/librustc_resolve/diagnostics.rs#L1108) to be the more appropriate error here. This error is thrown for some feature which hasn't been implemented yet( and probably won't be), so it can be repurposed. See [#34230](https://github.com/rust-lang/rust/pull/34230#issuecomment-226182208) for more.
   We could modify the error message for `E0220` to include the above erroneous code, but I think it would be better to throw `E0406` instead of `E0220` in this situation.

/cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
I'll try to take a look.

**Comment by eddyb** [comment]
E0406 is from some leftover code that shouldn't have existed in the first place.
E0220 is the correct error to use, message being:
```
error: associated type `Baz` not found for `Self``
```
The only problem I see is E0220's description needing to be updated. Also see https://github.com/rust-lang/rust/pull/34342#issuecomment-226944882.
