### ISSUE TITLE
Revert using the ? syntax for try! in libsyntax

### ISSUE THREAD

**Issue by erickt** [rust-lang/rust#34311]
The use of `...?`instead of `try!(...)` in libsyntax makes extracting libsyntax into syntex quite painful since it's not stable yet. This makes backports take a much longer time and causes a lot of problems for the syntex dependencies. Even if it was, it'd take a few release cycles until syntex would be able to use it. Since it's not stable and that this feature is just syntax sugar, it would be most helpful if we could remove it.

**Comment by tbu-** [comment]
Looks fixed?

**Comment by pnkfelix** [comment]
Until this line is gone, I'd say this should stay open:

https://github.com/rust-lang/rust/blob/master/src/libsyntax/lib.rs#L35

```rust
#![feature(question_mark)]
```

**Comment by frewsxcv** [comment]
Update: it's now:

```
#![cfg_attr(stage0, feature(question_mark))]
```

**Comment by Mark-Simulacrum** [comment]
Closing, I am fairly certain that question_mark is stable now.
