### ISSUE TITLE
Add dominator computation and cache to MIR

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#34326]
Many optimizations require dominators and post-dominators. These can be stored in the MIR cache like predecessors so that they can be re-used across execution. Prototype code [here](https://github.com/nikomatsakis/nll/tree/master/graph-algorithms/src) that can be adapted.

**Comment by nikomatsakis** [comment]
@scottcarr is working on this.

**Comment by Mark-Simulacrum** [comment]
There is now dominator code in MIR, but as far as I can tell, these are not cached. @nikomatsakis Perhaps caching dominators could be a mentored issue? I don't really know what the difficulty level with that is.

**Comment by nikomatsakis** [comment]
I think we should probably just close this, I feel like the future of how MIR opts should look is a bit too unclear (let me know if anyone disagrees).
