### ISSUE TITLE
Doctest names contain `&nbsp;` if there are multiple type parameters

### ISSUE THREAD

**Issue by rkruppe** [rust-lang/rust#34325]
For example, `make check` outputs:

```
run doc-crate-std [x86_64-pc-windows-msvc]
[...]
test collections::hash::map::HashMap<K,&nbsp;V,&nbsp;RandomState>::new_0 ... ok
test collections::hash::map::HashMap<K,&nbsp;V,&nbsp;RandomState>::with_capacity_0 ... ok
[...]

run doc-crate-core [x86_64-pc-windows-msvc]
[...]
test result::Result<T,&nbsp;E>::and_0 ... ok
test result::Result<T,&nbsp;E>::as_mut_0 ... ok
[...]
```

It's not std-specific, it also happens with `cargo test` on ordinary crates. Amusingly, it doesn't happen when there are spaces in the type name that come from an array type:

``` rust
struct Wrap<T>(T);

impl Wrap<[i32; 3]> {
    // doctests for methods here are called Wrap<[i32; 3]>::foo, not Wrap<[i32;&nbsp;3]>::foo
}
```

I observe this on 7aba683c76f3db78afa0c10a7b0ecfb02a3e8b63 and `rustc 1.11.0-nightly (bb4a79b08 2016-06-15)`, but not on 1.9 stable.

**Comment by euclio** [comment]
I'm not seeing this issue anymore on the current nightly.

**Comment by steveklabnik** [comment]
@rkruppe did this go away like @euclio suggests?

**Comment by rkruppe** [comment]
Yes, I just tested with `1.14.0-nightly (3f4408347 2016-10-27)`

**Comment by rkruppe** [comment]
(On 1.13 stable too.)
