### ISSUE TITLE
Add RISC-V support

### ISSUE THREAD

**Issue by sunnystormy** [rust-lang/rust#34333]
I want to add RISC-V support for Rust. I'd be happy to fork it and add this feature if I could pointed in the right direction of what files I'd need to edit?

The RISC-V foundation has already added support for [Go](https://github.com/riscv/riscv-go), so I felt porting this language would provide a good alternative.

Thank you for your help!

**Comment by nagisa** [comment]
You should ask for them to upstream their LLVM changes. With that we should pretty much support RISC-V without any extra changes on our side.

**Comment by sunnystormy** [comment]
[Done](https://github.com/riscv/riscv-llvm/issues/30).

**Comment by alexcrichton** [comment]
Ah yeah, we'd totally be on board for any new platforms! You may want to glance at some historical portings of Rust which tend to be small-ish patches that involve updating various pieces of the standard library and compiler to understand the new architecture. It's generally pretty unlikely that any major changes are necessary to support a new architecture, and PRs are of course always welcome!

We don't tend to keep around issues for tracking new platforms like this, so I'm gonna close this for now, but feel free to ask any questions here or elsewhere!

**Comment by sorear** [comment]
FYI, [the upstreaming has started](http://lists.llvm.org/pipermail/llvm-dev/2016-August/103748.html).

**Comment by Razican** [comment]
What is the status of RISC-V support in Rust, currently?

**Comment by sorear** [comment]
There isn't any

**Comment by PkmX** [comment]
FYI, I have an experimental port available at [pkmx/rust](https://github.com/PkmX/rust). It is based on LLVM patches from [lowRISC/riscv-llvm](https://github.com/lowRISC/riscv-llvm).

**Comment by starblue** [comment]
Is there any chance to use this for the HiFive1 board (i.e. RV32IMAC)?

**Comment by bgermann** [comment]
@starblue You should have a look at dvc94ch/riscv-rust-toolchain.
