### ISSUE TITLE
Include rustbook binary in the official release artifacts?

### ISSUE THREAD

**Issue by tatsuya6502** [rust-lang/rust#34332]
As far as I know, the official release artifacts (e.g. rust-1.9.0-x86_64-unknown-linux-gnu.tar.gz) contain `rustc`, `cargo` and `rustdoc` binaries. Why don't we add `rustbook` binary as well?

I have been working on [Japanese translation](https://rust-lang-ja.github.io/the-rust-programming-language-ja/1.6/book/) of The Rust Programming Language and it requires `rustbook` binary to build HTML files. On my CI environment, I am using [rustbook crate](https://crates.io/crates/rustbook), which is basically a copy of [tools/rustbook](https://github.com/rust-lang/rust/tree/master/src/tools/rustbook) in this repository (rust-lang/rust). 

It is not too bad but it is tedious to keep the rustbook crate up-to-date to the original in this repository. It would be much easier to me and other people using `rustbook` if the official release artifacts contain it.

**Comment by steveklabnik** [comment]
We are moving towards `mdbook` anyway, with the new book, so it's more likely that rustbook will just dissappear.

**Comment by tatsuya6502** [comment]
Thank you for the response. I am really exited about the new book.

`mdbook` is fine to me. We are also translating Rust by Example to [Japanese](http://rust-lang-ja.org/rust-by-example/), so we are already using it.

I see [The Rustonomicon](https://doc.rust-lang.org/nomicon/) and [The Style Guidelines](https://doc.rust-lang.org/style/) are also using rustbook. Please let me know if you need any help to convert them into `mdbook` format.

**Comment by tatsuya6502** [comment]
Actually, I was confused [`mdBook`](https://github.com/azerupi/mdBook) with node.js-based GitBook. I tried mdBook a couple of weeks ago and I liked it.
