### ISSUE TITLE
Fill/alignment overrides # specifier in format strings

### ISSUE THREAD

**Issue by Ketsuban** [rust-lang/rust#34341]
Here's a sample program.

``` rust
fn main() {
    let foo: u8 = 0xA;
    println!("{:b}", foo);
    println!("{:>08b}", foo);
    println!("{:#b}", foo);
    println!("{:#>08b}", foo); // <--
}
```

I expected this output.

```
1010
00001010
0b1010
0b00001010
```

I got this output.

```
1010
00001010
0b1010
00001010
```

**Comment by hirschenberger** [comment]
Your format string is wrong. The syntax from the [doc](https://doc.rust-lang.org/std/fmt/index.html#syntax) is:

```
format_spec := [[fill]align][sign]['#']['0'][width]['.' precision][type]
```

So the formatstring should be `{:>#08b}` and this works https://is.gd/Wpxf90

**Comment by Mark-Simulacrum** [comment]
Yes, the format syntax does appear to be incorrect here, and should be `{:>#010b}` to produce the result you expecte.
