### ISSUE TITLE
Please impl Index<usize> for str and String

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rust#34354]
`str` and `String` support indexing by various kinds of `Range` to produce a slice, but do not support indexing with a single index to produce a `char`.  That would simplify such operations by not requiring duplication of the index expression or introduction of an iterator and unwrapping.

**Comment by Stebalien** [comment]
We can't actually do that because the `Index` trait can only return references. At best, we could return a string slice that contained exactly one character.

**Comment by joshtriplett** [comment]
It can return a `*&char`, though.  And since `char` implements `Copy` and `Clone`, the caller can easily get a `char` from that if they want one.

**Comment by Stebalien** [comment]
But where would you *store* the char?

**Comment by Stebalien** [comment]
That is,

```rust
impl Index<usize> for String {
    type Output = char;
    fn index(&self, index: usize) -> &char {
        let c = self[index..].chars().next().unwrap()
        return &c; // c doesn't live long enough.
    }
}
```

**Comment by joshtriplett** [comment]
Ah, I see. Unfortunate typing there. Ideally the '&' would have been included in the associated type `Output`, rather than implied inherently by `Index`. But in the absence of that, yes, that doesn't work.

**Comment by tbu-** [comment]
The `&` can unfortunately not appear in the associated type only, because we can't bind it to the lifetime of `&self` in that case.

**Comment by rkruppe** [comment]
Foiled again by HKT!

**Comment by durka** [comment]
They could implement `Index<usize, Output=u8>`. On the other hand, the forced choice of `s.bytes()` vs `s.chars()` raises awareness that they aren't the same.

**Comment by Thiez** [comment]
Even without the problem of `Index` returning a reference, how do you image it would be implemented, if it returned a `char`? Strings in Rust are utf-8, so finding the nth character is a O(n) operation. Most people expect their indexing to be O(1) (or perhaps O(log(n)) in the worst case). In addition, indexing into a string is hardly ever a useful operation.

**Comment by rkruppe** [comment]
@Thiez Analogously to slicing (`Index<Range<usize>>`) and other methods such as `char_indices()`, the index would be a *byte* index which must lie on a code point boundary.

**Comment by alexcrichton** [comment]
As mentioned previously this is not possible when the output is `char`, but it is indeed possible when the output is `u8`. The libs team decided before 1.0, however, that we would not implement this as a `str` is moreso a container of `char` rather than a container of bytes. Adding an impl like this would be a large enough change that it would likely require an RFC, so I'm going to close this for now. RFCs are of course welcome though!
