### ISSUE TITLE
Strange error message

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#34359]
The following code:

``` rust
fn main() {
    for _ in 0 .. 2 {
        break();
    }
}
```

Returns the following error (on all rustc versions):

``` bash
error: the type of this value must be known in this context
```

Which is really strange. The same error occurs with "continue();".

**Comment by durka** [comment]
This might make it more clear what is going on:

```rust
fn main() {
    for _ in 0 .. 2 {
        let x = break;
        x(); //~ERROR
    }
}
```

**Comment by sanxiyn** [comment]
Another way to get this is `(return)();`. `return();` is special cased in the parser so that it does not parse as a call. `break();` will get the same treatment if we adopt RFC 1624.

What should be the error message here? I am inclined to close unless there is a good idea.

**Comment by eefriedman** [comment]
Well, I can see a few weaknesses in the error message:

1. No extended error explanation (`E****`).
2. The error message is describing the error from the compiler's perspective, not the user's perspective, and is overly generic.  It would be a lot more clear if the compiler said "not enough information to compute type of callee".
3. No note describing what we expect the user to do to fix the problem (along the lines of "use a variable to specify the type of an expression like this: `let x: i32 = ...;`").
4. (Larger change) It should be possible to detect the source of the unknown type, and give a more specific suggestion; for example, we could give specialized error messages for an uninitialized variable, a return statement, and a generic function whose generic type argument isn't specified.

**Comment by GuillaumeGomez** [comment]
@eefriedman: In the case the value with the unknown type isn't used, can't rustc just get over it and give it any matching type under the hood?

**Comment by sanxiyn** [comment]
I created a patch which changes the error to `error: cannot determine the type of this callee`.
