### ISSUE TITLE
Suggest using ranges in loops on primitive types, instead of calling .iter()

### ISSUE THREAD

**Issue by alexandermerritt** [rust-lang/rust#34353]
The following code results in output that isn't specifically helpful:

``` rust
fn main() {
    let max: usize = 10;
    for m in max { ; }
}
```

Compiler output:

```
error: the trait bound `usize: std::iter::Iterator` is not satisfied [--explain E0277]
 --> <anon>:3:5
3 |>     for m in max {
  |>     ^
note: `usize` is not an iterator; maybe try calling `.iter()` or a similar method
note: required by `std::iter::IntoIterator::into_iter`
```

Primitive types do not [currently] implement `Iterator`. Perhaps the output could see the type is primitive and suggest to create a type that implements `Iterator`, such as a range with `0..max`?
## Meta

```
rustc 1.11.0-nightly (bb4a79b08 2016-06-15)
binary: rustc
commit-hash: bb4a79b087158f396b984bdf552d2c90890b12a3
commit-date: 2016-06-15
host: x86_64-unknown-linux-gnu
release: 1.11.0-nightly
```

**Comment by Aatch** [comment]
That error message is already somewhat special, but it uses a special attribute on the trait itself. This would require actually special-casing Iterator in this case, and I'm not sure how useful that would be for the effort. I'm skeptical that this kind of thing is 1) particularly common and 2) something that somebody would deliberately do. What I mean by that second point is that there's a difference between doing `for m in max` and going "oh I meant `for m in 0..max` and doing that expecting it to work.

**Comment by estebank** [comment]
Once #47613 gets merged, this can be trivially added.
