### ISSUE TITLE
Book Documentation Section: referencing other items from a documentation comment 

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#34362]
I am documenting a trait method and would like to reference other trait methods so that they get hyperlinked. I would expect this to happen if I write \`MyTrait::other_method\` or just \`other_method\` but that is not the case. The book doesn't seem to mention anything about referencing other items (types, functions, trait, methods) from within documentation comments in such a way that they get hyperlinked.

**Comment by gnzlbg** [comment]
The way to at least hyperlink one trait method from another is:

```/// See [`other_method`](#tymethod.other_method).```

**Comment by steveklabnik** [comment]
Yes, currently, you must write links yourself. There have been various proposals for extending markdown in this way, but we have not come to a conclusion. As that's going to be such a big change, it's going to require an RFC.
