### ISSUE TITLE
Documentation: `std::intrinsics::cttz` does not specify the handling of zero.

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#34381]
The llvm docs for `llvm.cttz.iX(value, flag) specifies that a flag can be passed to control whether zero provides a defined result or not.

Whether `std::intrinsics::cttz` provides a defined result for zero or not should be specified in the documentation, since if not some code might require `if x == 0 { mem::sizeof(x) * 8 } else { std::intrinsics::cttz(x) }` to be used (instead of just `std::intrinsics::cttz(x)`).

See the LLVM documentation: http://llvm.org/docs/LangRef.html#llvm-cttz-intrinsic

**Comment by gnzlbg** [comment]
From: https://github.com/rust-lang/rust/blob/34fd68668152530dcd1d00865fa8514461b895d7/src/librustc_typeck/check/intrinsic.rs#L264 

It might seem that the intrinsic is always called with a value of 0 (false) but I cannot find where the `std::intrinsic::cttz` function is implemented to verify this. And the LLVM docs are a bit confusing about what exactly the flag means. The text seems to indicate that true means "consistent handling of zero" but the argument name "is_zero_undef" indicates that true means "inconsistent handling of zero".

**Comment by nagisa** [comment]
Ah I see now. This intrinsic is used to implement `u*::trailing_zeros` method, therefore we cannot afford it to be undef for corner-case values. It seems safe to say we pass whatever the flag makes 0 input defined for this intrinsic without even checking the implementation.

**Comment by gnzlbg** [comment]
> This intrinsic is used to implement u*::trailing_zeros method, therefore we cannot afford it to be undef for corner-case values.

That makes sense. Having to do `x == 0? 8 * CHAR_BITS : __builtin_ctz(x)` in C++ is error prone (since this behavior is what is actually desired all of the time).

Where is `u*::trailing_zeros` / `std::intrinsic::cttz` implemented? I was trying to find the source to see which argument is passed without any luck.

I guess to improve the docs it would be enough to add a note like:

> note: when `x == 0` the behavior of `std::intrinsic::cttz(x)` is defined in all platforms to return `8 * mem::sizeof(x)` (that is, the `llvm.cttz.iX` intrinsic is called with the flag `zero_is_undef` set to `false`).

**Comment by gnzlbg** [comment]
> Trailing_zeros is implemented here.

Thanks! Where is `std::intrinsic::cttz` implemented? That should call/generate the `llvm.cttz` intrinsic and pass the arguments somehow.

> If you click LLVM IR on this playpen, you’ll find a %3 = call i64 @llvm.cttz.i64(i64 %2, i1 false), !dbg !25.

Nice, TIL! One can also output the asm directly in the playpen :)

**Comment by nagisa** [comment]
> Where is std::intrinsic::cttz implemented?

Its implemented deep inside the translator and is not you can tweak without modifying the compiler itself. The LLVM intrinsic is emitted [here](https://github.com/rust-lang/rust/blob/5522e678bcefe14cc2ab3d0ab329b7059ce52b36/src/librustc_trans/intrinsic.rs#L1021) and [here](https://github.com/rust-lang/rust/blob/5522e678bcefe14cc2ab3d0ab329b7059ce52b36/src/librustc_trans/intrinsic.rs#L550).

**Comment by frewsxcv** [comment]
PR opened https://github.com/rust-lang/rust/pull/38310
