### ISSUE TITLE
On 64-bit windows-msvc, can't specify SysV calling convention

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#34388]
On most 64-bit platforms you can use `extern "C"` to select the SysV calling convention or `extern "win64"` to select the Microsoft calling convention. On windows-msvc, `extern "C"` is the same as `extern "win64"` and there's no way to select SysV.

**Comment by retep998** [comment]
Are there any situations where you'd want the SysV calling convention on Windows?

**Comment by Aatch** [comment]
@retep998 interfacing with assembly seems like a reasonable use-case.

**Comment by CensoredUsername** [comment]
@retep998 It's an annoyance/restriction when writing anything that deals with run-time assembling (JIT compilers for instance). It necessitates using of the asm feature to call into it or sticking to win64 as calling convention on all platforms.

**Comment by CensoredUsername** [comment]
This is available now since the merge of #34494, this issue can be closed in favor of the tracking issue.
