### ISSUE TITLE
Rust Reference documents operator associativity incorrectly

### ISSUE THREAD

**Issue by jameysharp** [rust-lang/rust#34386]
In section 7.2.12.8 "Operator precedence", the Rust reference says, "Operators at the same precedence level are evaluated left-to-right." I assume this is intended to mean that the binary operators are all left-associative.

However, the comparison operators (`==` `!=` `<` `>` `<=` `>=`) are apparently non-associative, requiring explicit parentheses if you want to apply one to the result of another, as in `(2 < 3) == true`. (That's a silly example, but I have in the past found utility in expressions like `(a < b) != (c < d)`.)

I think the implemented behavior is both reasonable and a good idea, so this is just a documentation bug, but I'm not really sure how to fix the documentation to be clear.

**Comment by eddyb** [comment]
Yes, it is. I believe it has to do with how `a < b < c`, even if it parsed, wouldn't be `a < b && b < c` like in some other languages (Python?) and would produce confusing type error messages in most cases.

**Comment by durka** [comment]
It actually does parse, even after the chained comparison error, and produces the expected type error :)

**Comment by Aatch** [comment]
@steveklabnik it's complicated, as the parser does technically parse `a == b == c == d` as `((a == b) == c) == d` (I think, this is a based on the error messages I got). I think the fact that chained comparisons throws an error means we should probably document them as non-associative though.

Chances are that section was written before the chained comparisons error was implemented.

**Comment by durka** [comment]
And those error messages should be suppressed.

**Comment by Mark-Simulacrum** [comment]
This appears to be a documentation issue, closing in favor of an issue on the reference: https://github.com/rust-lang-nursery/reference.
