### ISSUE TITLE
rustc accepts "---128i8" as a valid constant

### ISSUE THREAD

**Issue by eefriedman** [rust-lang/rust#34395]
```rust
pub fn main() {
    const X: i8 = ---128;
    const Z: [u8; X as u8 as usize] = [0; X as u8 as usize];
    println!("{}", Z[0]);
}
```

This is clearly ridiculous, but rustc is perfectly happy with it.

Regression from 1.9.

**Comment by tbu-** [comment]
```
use std::mem;
pub fn main() {
    const X: i8 = ---128;
    const Z: [u8; X as u8 as usize] = [0; X as u8 as usize];
    println!("{}", mem::size_of_val(&Z));
}
```
prints `128`.

Using the constant in any other way, e.g.
```
pub fn main() {
    const X: i8 = ---128;
    const Z: [u8; X as u8 as usize] = [0; X as u8 as usize];
    println!("{}", Z[0]);
    println!("{}", X);
}
```
errors out:
```
$ rustc a.rs
a.rs:2:20: 2:25 error: attempted to negate with overflow
a.rs:2     const X: i8 = ---128;
                          ^~~~~
error: aborting due to previous error
```

**Comment by dsprenkels** [comment]
This was caused by 82093cab6ff2e660dbb51c68a2624baa4cc1b250.

**Comment by oli-obk** [comment]
cc @eddyb is that fallout from your new const eval?

**Comment by eddyb** [comment]
@oli-obk I haven't removed anything, not that I can think of, to cause this.

**Comment by oli-obk** [comment]
Then it's very likely fallout from https://github.com/rust-lang/rust/commit/735c018974e5570ea13fd887aa70a011a5b8e7b8 (skipping double negations)

**Comment by eddyb** [comment]
@oli-obk The remaining error in that testcase feels wrong. `--128i8` should, IMO, be `-(-128i8)` - the literal is in range, but the negation overflows.

**Comment by oli-obk** [comment]
Actually I think it should be valid code, but yield `-128`, at least that's what the original literal out of range lints do

**Comment by eddyb** [comment]
@oli-obk But `-(-128i8)` overflows when negating, which is an error. Why should it be different than `-(-64i8 - 64)`?

**Comment by oli-obk** [comment]
I have no particular opinion on this. But the lint has code handling double negations: https://github.com/rust-lang/rust/blob/bb4b3fb7f97924919f072ec9a360bdf943218dbf/src/librustc_lint/types.rs#L121 (it's treating double negations as if they weren't there at all)

**Comment by dsprenkels** [comment]
The double negation is not the issue here. Consider the following code:

```rust
fn main() {
    const X: i8 = -100;
    const Y: u8 = X as u8;
    println!("{}", Y);
}
```

This will also compile just fine and print `156`. Where is goes wrong, is in the cast `X as u8`. Rust doesn't check if cast overflows, so the `<u8>` value becomes `156`.

[`cast_const_int`](https://github.com/rust-lang/rust/blob/735c018974e5570ea13fd887aa70a011a5b8e7b8/src/librustc_const_eval/eval.rs#L1067-L1111) can be changed to disallow casts that fail, or we can accept that these casts are can overflow silently.

**Comment by tbu-** [comment]
@dsprenkels I believe the issue is that --128 (aka 128) is an intermediate result of the computation that is out of bounds for the i8.

**Comment by oli-obk** [comment]
jup, that was a misunderstanding of some code on my part + the issue that processing HIR works the wrong way around (you start with the outer most expression). Reverting 735c018974e5570ea13fd887aa70a011a5b8e7b8 should do the job

**Comment by dsprenkels** [comment]
I thought that it was intended that `---128` would succesfully evaluate to `-128`. (That rustc knows that it's overflowing, but is smart to know that double negation will fix it in the end.) Pretend I said nothing.
