### ISSUE TITLE
post-MIR task: remove artifacts of embedded drop flags

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#34398]
Spawned off of #5016

After we shift entirely to MIR (i.e., it is not only on by default, but also the *only* option), we should then remove the drop-filling and fill-checking code.

**Comment by nagisa** [comment]
triage: A-mir

**Comment by ahmedcharles** [comment]
@eddyb Is this closed by #35764?

**Comment by eddyb** [comment]
Indeed!
