### ISSUE TITLE
error message for macro in wrong context is missing context

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#34421]
This is a regression from stable to beta and nightly.

This code is wrong (missing semicolons):

``` rust
macro_rules! make_item {
    ($a:ident) => { struct $a; }
}

fn a() { make_item!(A) }
fn b() { make_item!(B) }
```

Stable prints:

```
<anon>:2:21: 2:27 error: expected identifier, found keyword `struct`
<anon>:2     ($a:ident) => { struct $a; }
                             ^~~~~~
<anon>:5:21: 5:22 error: macro expansion ignores token `A` and any following
<anon>:5 fn a() { make_item!(A) }
                             ^
<anon>:5:10: 5:23 note: caused by the macro expansion here; the usage of `make_item!` is likely invalid in expression context
<anon>:5 fn a() { make_item!(A) }
                  ^~~~~~~~~~~~~
<anon>:2:21: 2:27 error: expected identifier, found keyword `struct`
<anon>:2     ($a:ident) => { struct $a; }
                             ^~~~~~
<anon>:6:21: 6:22 error: macro expansion ignores token `B` and any following
<anon>:6 fn b() { make_item!(B) }
                             ^
<anon>:6:10: 6:23 note: caused by the macro expansion here; the usage of `make_item!` is likely invalid in expression context
<anon>:6 fn b() { make_item!(B) }
                  ^~~~~~~~~~~~~
error: aborting due to 4 previous errors
```

Beta and nightly both print:

```
error: expected expression, found keyword `struct`
 --> <anon>:2:21
  |>
2 |>     ($a:ident) => { struct $a; }
  |>                     ^^^^^^
```

Notice that not only is all the useful information gone, but the compiler aborts after the first error instead of finding the rest. It does not matter whether `RUST_NEW_ERROR_FORMAT` is on or off.

cc @nikomatsakis @jonathandturner

**Comment by jseyfried** [comment]
cc me

**Comment by Mark-Simulacrum** [comment]
So this fell through the cracks, and was a stable to nightly/beta regression. It still is a regression, in a way, but only of diagnostics. @jseyfried Could you take a look?

**Comment by nikomatsakis** [comment]
Nominating for prioritization.

**Comment by nikomatsakis** [comment]
So this part of the (previous) stable message:

> macro expansion ignores token `A` and any following

feels like a bug to me anyhow.

This part:

> caused by the macro expansion here; the usage of `make_item!` is likely invalid in expression context

is sort of good. It'd be nice to preserve a backtrace, at least. And ideally we'd suggest adding a `;`.

**Comment by nikomatsakis** [comment]
Given how much time has past, we're going to call this P-medium for now. However, @jseyfried will try to write up some mentoring instructions (or maybe fix it). He has a plan. =)

triage: P-medium

**Comment by jseyfried** [comment]
I think the best path forward here is to try parsing an expression macro expansion as a statement before emitting an error. If the macro expansion parses as a statement successfully, we can emit a more helpful error suggesting that the user add a semicolon to the macro invocation.

**Comment by Freyskeyd** [comment]
I'm interested in this but I need informations to understand what to do :)

**Comment by estebank** [comment]
Current output:

```
error: expected expression, found keyword `struct`
 --> src/lib.rs:2:21
  |
2 |     ($a:ident) => { struct $a; }
  |                     ^^^^^^ expected expression
...
5 | fn a() { make_item!(A) }
  |          ------------- in this macro invocation
```

**Comment by oli-obk** [comment]
Diagnostics meeting triage: lowering priority as the current error is pretty good, even if not ideal yet.

**Comment by Centril** [comment]
Current output:
```

error: expected expression, found keyword `struct`
 --> src/lib.rs:2:21
  |
2 |     ($a:ident) => { struct $a; }
  |                     ^^^^^^ expected expression
...
5 | fn a() { make_item!(A) }
  |          ------------- in this macro invocation
  |
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: expected expression, found keyword `struct`
 --> src/lib.rs:2:21
  |
2 |     ($a:ident) => { struct $a; }
  |                     ^^^^^^ expected expression
...
6 | fn b() { make_item!(B) }
  |          ------------- in this macro invocation
  |
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 2 previous errors
```
(Notice that we recover -- it's not a fatal error now.)
