### ISSUE TITLE
rustbook: libraries ~ dependencies

### ISSUE THREAD

**Issue by ActualizeInMaterial** [rust-lang/rust#34444]
`We call libraries your code needs ‘dependencies’ since your code depends on them.`
src: https://doc.rust-lang.org/nightly/book/getting-started.html

**Comment by steveklabnik** [comment]
Sorry, can you clarify what this issue is about? I'm not understanding.

**Comment by ActualizeInMaterial** [comment]
the sentence doesn't make grammatical sense? sorry, I thought it was obvious

**Comment by Thiez** [comment]
I'm sure steve can read, and can understand that the line you quoted is somewhere on that page. That part is obvious. What is not obvious is what *you* think is *wrong* with it. It looks like you've just grabbed a random sentence from the rust-book, and it is entirely unclear what this issue is about, except that it is probably in some way related to the sentence you quoted.

**Comment by ActualizeInMaterial** [comment]
Here it is in context:

>Cargo is Rust’s build system and package manager, and Rustaceans use Cargo to manage their Rust projects. Cargo manages three things: building your code, downloading the libraries your code depends on, and building those libraries. **We call libraries your code needs ‘dependencies’ since your code depends on them.**

>The simplest Rust programs don’t have any dependencies, so right now, you'd only use the first part of its functionality. As you write more complex Rust programs, you’ll want to add dependencies, and if you start off using Cargo, that will be a lot easier to do.

Does that make sense to anyone?

**Comment by ActualizeInMaterial** [comment]
maybe `your code needs` is extraneous? or something else was meant there

**Comment by ActualizeInMaterial** [comment]
Oh wait, I get it:
`libraries your code needs` is taken as a whole(substantive?)
my bad then, I literally could not see this until now, thanks @Thiez
