### ISSUE TITLE
Lifetime Coercion

### ISSUE THREAD

**Issue by PompeiaPaetenari** [rust-lang/rust#34487]
Though the old tutorial seems to have been depreciated within the past couple days, I did want to point out this error I found that was in it (and no longer seems to be in the book).  I do not know if its inherent functionality was removed or is just hidden... (it always struck me as a bit silly anyhow).

```rust
// <'a: 'b, 'b> reads as lifetime 'a is at least as long as 'b.
// Here, we take in an &'a i32 and return a &'b i32 as a result of coercion.
fn choose_first<'a: 'b, 'b>(first: &'a i32, _: &'b i32) -> &'b i32
{
    first
}

fn main()
{
    let first = 2; // Longer lifetime
    {
        let second = 3; // Shorter lifetime
        println!("{} is the first", choose_first(&second, &first));
    }
    println!("{}",first);
}
```

Basically, what I read it as is that there would be an error message reporting that the lifetime of b was longer than a, thus invalidating the function signature.  However, no such error occurred despite the lifetime of 'first' being longer than that of 'second'.  Is this a misread or bad wording of the tutorial?

P.S. If this is no longer valid syntax or a feature discarded, please feel free to close the issue.

**Comment by steveklabnik** [comment]
Given that this is no longer in the book, I'm giving it a close, as it's not a bug. For questions like this, please post to users.rust-lang.org. Thanks!
