### ISSUE TITLE
rustc doesn’t auto-detect things for Visual Studio 15

### ISSUE THREAD

**Issue by chris-morgan** [rust-lang/rust#34484]
Had to run vcvars64.bat myself to get it to work; it was complaining it couldn’t find link.exe at first.

I presume we’ll just need to add things to `librustc_trans::back::msvc` for 15.0 which will probably be the same as 14.0. I’m happy to test it all out and submit a PR when I’ve verified it (having a machine now with Visual Studio 15 on it); I’ll just need to get set up for building rustc on Windows, and I’m not doing that now, or probably for a few days.

**Comment by retep998** [comment]
I already have a branch that I've had hanging around for a while which would fix this among other things. I really ought to polish it up and get it landed.
