### ISSUE TITLE
Cargo doesn’t produce colors on Windows

### ISSUE THREAD

**Issue by chris-morgan** [rust-lang/rust#34483]
(I’m using Windows 10 Insider Preview which has more vt100 support, but I believe basic colors are supported on even the stable Windows 10 cmd. For that matter, I’m not sure if we use vt100 codes or if we use the traditional Windows API calls; I haven’t looked yet.)

Messages from Cargo (e.g. the “Compiling”, “Running”, “Doc-tests” parts which are normally bold green) aren’t being colored on Windows under cmd. rustc messages (e.g. compiler warnings and errors) are being colored, and the standard test harnesses are coloring their output. Only Cargo isn’t.

**Comment by tbu-** [comment]
This issue should probably be filed for https://github.com/rust-lang/cargo.

**Comment by chris-morgan** [comment]
I completely forgot Cargo had a repository of its own. Just shows I haven’t been dealing with it all enough recently…

And rust-lang/cargo#2803, which this becomes a duplicate of, was filed only twelve hours ago!
