### ISSUE TITLE
./configure fails on windows when cmake is installed on a file path containing spaces

### ISSUE THREAD

**Issue by CensoredUsername** [rust-lang/rust#34490]
By default, cmake is installed in C:\Program Files\CMake, so this will fail on all default installations.

As far as I see, the culprit is in configure, line 1728: 
`(cd $LLVM_BUILD_DIR && eval "$CFG_CMAKE" $CMAKE_ARGS)`

A fix for this would be changing this line to 
`(cd $LLVM_BUILD_DIR && eval "\"$CFG_CMAKE\"" $CMAKE_ARGS)`

**Comment by alexcrichton** [comment]
Oh dear I'm endlessly confused by shell syntax...

Thanks for the report and fix @CensoredUsername! Want to send a PR for this?

**Comment by CensoredUsername** [comment]
Sure, I'll have one  up in a bit.

**Comment by CensoredUsername** [comment]
This is fixed now.
