### ISSUE TITLE
Measure impact of MIR on compilation times for existing benchmarks

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#34505]
Before enabling MIR by default, we'd like to measure MIR's impact on compilation time for the benchmarks listed here. Ideally there would be no regressions:

https://github.com/nrc/benchmarks

cc @rust-lang/compiler

**Comment by nrc** [comment]
Can add `-Zorbit` measurement to perf.r-l.o. Doing this on the backend to collect data should be trivial, the middle step of processing, maybe, and frontend to display the data is a bit non-trivial.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this. We've enabled MIR by default at this point, and I don't really recall what effect it had on the benchmarks. I feel like it was a regression, but... uncertain. This isn't tracking anything anyway, so closing.
