### ISSUE TITLE
Rustdoc rendering issue

### ISSUE THREAD

**Issue by jbcden** [rust-lang/rust#34501]
When I render the documentation for the following:

```rust
fn into_path(mut self) -> PathBuf
```

I am seeing:

```rust
fn into_path(self) -> PathBuf
```
instead.

**Comment by GuillaumeGomez** [comment]
Thanks, working on it!

**Comment by alexcrichton** [comment]
@GuillaumeGomez hm wait hang on, the signatures here are the same as `mut` is an implementation detail in this case. I think this is intended behavior, so closing.

**Comment by alexcrichton** [comment]
That is, from a client's point of view, the two signatures above are equivalent.

**Comment by GuillaumeGomez** [comment]
Good, one less problem!
