### ISSUE TITLE
Book section 4.8 (Ownership) v1 should be v.

### ISSUE THREAD

**Issue by jonmarkprice** [rust-lang/rust#34510]
In section 4.8, ["The details" subheading](https://doc.rust-lang.org/book/ownership.html#the-details), while explaining ownership with the following code example:
```rust
let v = vec![1, 2, 3];

let mut v2 = v;
```
the book suddenly switches to `v1` instead of `v` after the `v2.truncate` example.

> It would violate Rust’s safety guarantees by introducing a data race if one could access both v and v2 at the same time.
> 
> For example if we truncated the vector to just two elements through v2:
> ```rust
> v2.truncate(2);
>```
> and v1 were still accessible we'd end up with an invalid vector since v1 would not know that the heap data has been truncated. 

The book continues to use `v1` for the rest of the paragraph. But `v1` does not appear in any of the preceding code segments.

**Comment by jonmarkprice** [comment]
Hmm, just checked the markdown file ([ownership.md](https://github.com/rust-lang/rust/blob/master/src/doc/book/ownership.md)) and it's already using `v` (not `v1`). Did you already fix it or has online version not been rendered recently?

**Comment by jonmarkprice** [comment]
**Update:** Looks like #33035 fixed this already. Closing, sorry guys.

**Comment by steveklabnik** [comment]
Ah! Nice call.
