### ISSUE TITLE
Missing information about source file name - Getting Started 

### ISSUE THREAD

**Issue by rdotdk** [rust-lang/rust#34523]
In the rust book Getting Started section, it is mentioned that we can have source file name as "hello_world.rs", however in the cargo introduction section if we move the file inside src directory and run cargo build, it fails. Having the file renamed as main.rs makes cargo build success. This is not mentioned in the getting started document.

I think the Getting Started section should either say that the file name should be main.rs or if the file name is other than main.rs, it should mention on how to make cargo build succeed by telling the cargo to look for hello_world.rs in the src directory.

https://doc.rust-lang.org/book/getting-started.html

**Comment by JIghtuse** [comment]
Hm, this `hello_world.rs` is just an example of multiple-words source file name:

        If you’re using more than one word in your filename, use
        an underscore to separate them; for example, you'd use
        hello_world.rs rather than helloworld.rs.

 All other places mention `main.rs`:

        Next, make a new source file and call it main.rs

        ...
        Now open the main.rs file you just created

        ...
        mv main.rs src/main.rs

I would call it unfortunate place for file naming details: we switch from `main.rs` to `hello_world.rs` and back in the same paragaph. It make sense to move this example to  some other place.
