### ISSUE TITLE
Semicolons are not required on some statements in macros

### ISSUE THREAD

**Issue by jseyfried** [rust-lang/rust#34543]
For example, this compiles:
```rust
macro_rules! m { () => {
    let x = 1
    let y = 2
    println!("{}", x)
    println!("{}", y)
} }

fn main() {
    m!();
}
```

**Comment by durka** [comment]
Who knew that Rust had optional semicolon syntax built in? That must mean it's web scale!

**Comment by alexcrichton** [comment]
Nominating as this seems like it may actually be likely to cause fallout when fixed

**Comment by jseyfried** [comment]
I fixed this in #34660.

**Comment by dashed** [comment]
I'm unsure if this is related, but I'm getting these errors on nightly for compiling [chomp](https://github.com/m4rw3r/chomp) library:

```
<chomp macros>:5:59: 5:60 error: expected expression, found `.`
<chomp macros>:5 __parse_internal ! { @ EXPR ( $ input ; ) $ ( $ exp ) * } . bind (
                                                                           ^
<chomp macros>:9:59: 9:60 error: expected expression, found `.`
<chomp macros>:9 __parse_internal ! { @ EXPR ( $ input ; ) $ ( $ exp ) * } . bind (
                                                                           ^
<chomp macros>:5:59: 5:60 error: expected expression, found `.`
<chomp macros>:5 __parse_internal ! { @ EXPR ( $ input ; ) $ ( $ exp ) * } . bind (
                                                                           ^
<chomp macros>:9:59: 9:60 error: expected expression, found `.`
<chomp macros>:9 __parse_internal ! { @ EXPR ( $ input ; ) $ ( $ exp ) * } . bind (
                                                                           ^
<chomp macros>:9:59: 9:60 error: expected expression, found `.`
<chomp macros>:9 __parse_internal ! { @ EXPR ( $ input ; ) $ ( $ exp ) * } . bind (
```

Build fail example: https://travis-ci.org/dashed/chomp/jobs/142891865

-----

This is my attempted fix for this: https://github.com/dashed/chomp/commit/9c62b9f9b1ec5f1284ed229ede315b08d212df54

which passes on nightly: https://travis-ci.org/dashed/chomp/builds/142892066

**Comment by jseyfried** [comment]
@dashed, yeah that is related.
After #34660 lands, you still won't be able to use a braced macro invocation at the start of an expression in a statement position, just like you can't do this:
```rust
fn main() {
    if true { 0 } else { 1 } + 2; // This is parsed as if there were a semicolon after the `}`
}
```

However, after #34660 lands, you will be able to used a *non-braced* macro invocation at the start of an expression in a statement position (currently you can't do this in macro-expanded code but you can do it in unexpanded code). That is, after #34660, changing the `__parse_internal!` invocation to use parenthesis or brackets instead of braces would fix it.

cc @nrc @eddyb

**Comment by pnkfelix** [comment]
We are treating this as a bug that PR #34660 will fix. There are still some crater regressions to address.

**Comment by nrc** [comment]
triage: p-high

**Comment by pnkfelix** [comment]
P-high
