### ISSUE TITLE
Stable/beta configure fails on macOS 10.12 (Apple clang 8.0)

### ISSUE THREAD

**Issue by rahulg** [rust-lang/rust#34549]
Running `configure` on stable and beta branches on macOS 10.12 with the Xcode 8 command line tools fails with the following:

```
configure: error: bad APPLE CLANG version: 8.0.0, need >=7.0
```

The master branch shouldn't have this issue, since configure doesn't seem to whitelist Apple clang versions any more. The following one-line patch[1] fixes this issue on stable/beta:

```patch
diff --git a/configure b/configure
index fdef550..7a7b2e4 100755
--- a/configure
+++ b/configure
@@ -1023,7 +1023,7 @@ then
         if [ -n "$CFG_OSX_CLANG_VERSION" ]
         then
             case $CFG_OSX_CLANG_VERSION in
-                (7.0* | 7.1* | 7.2* | 7.3*)
+                (7.0* | 7.1* | 7.2* | 7.3* | 8.0*)
                 step_msg "found ok version of APPLE CLANG: $CFG_OSX_CLANG_VERSION"
                 ;;
                 (*)
```

[1] filed an issue instead of a PR since the PR wouldn't be against master

**Comment by alexcrichton** [comment]
Ah yeah this should be fixed on master and we can be sure to backport the relevant change (https://github.com/rust-lang/rust/pull/34383) to beta to ensure the next release (coming out next week) won't need that modification out of the box.

That's in the pipeline now so I'm gonna close this, but the next stable release should work just fine!

**Comment by rahulg** [comment]
Thanks!

**Comment by asemoon** [comment]
The same problem exists with clang 8.1.0 now
