### ISSUE TITLE
type_name intrinsic returns fully qualified pathes

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#34557]
The `type_name` intrinsic name implies that the function should only return the name of type, however it returns a fully qualified path of the type.

Try this:

``` rust
#![feature(core_intrinsics)]

use std::intrinsics::type_name;

fn main(){ 
    let vec: Option<Vec<bool>> = Some(vec![]);
    println!("{}", unsafe { type_name::<Option<Vec<bool>>>() });
}
```

Expected `Option<Vec<bool>>`, got `std::option::Option<std::vec::Vec<bool>>`.

**Comment by Mark-Simulacrum** [comment]
I feel like this isn't a bad thing. Fully qualified paths seem somewhat more useful. @nagisa Is there a specific reason other than the name that you wanted non-qualified paths?

**Comment by nagisa** [comment]
IMHO at this point the issue should serve as an "tracking" issue for type_name intrinsic redesign, which it badly needs.

As for specific reasons, we used this intrinsic like this in the compiler to automatically derive the name of MIR passes and, obviously, nobody wants to see the crate name prefix in those. We had to hack it with some quick'n'dirty string manipulation.

**Comment by Mark-Simulacrum** [comment]
Could you provide a list of things that would be preferable over the existing `type_name` output, in the original issue description? That would help make this bug more helpful to those visiting it, so that others may be able to help out and make this happen or people visiting for triage could diagnose whether this has happened.

**Comment by nagisa** [comment]
So ideally the intrinsic would eventually return data about the type in a structured way. Could be something as simple as `struct Ty { name: &str, path: &str, generic_args: &[Ty], lifetimes: &[&str], ... }`. I’m pretty sure this is written down somewhere else already, but I can’t remember where.

**Comment by abonander** [comment]
CC https://github.com/rust-lang/rfcs/issues/1428

**Comment by CAD97** [comment]
@nagisa I'm poking some at this.

I don't see any existing intrinsic in `libcore/intrinsics.rs` that returns anything other than a boolean, number, given generic, pointer (to given generic), or 2-tuple of the above. Is it possible for an intrinsic to return more complicated information?

Putting down some of the information I dug around for so I can find it again:

- `type_name` intrinsic implementation: https://github.com/rust-lang/rust/blob/a0dcecff90c45ad5d4eb60859e22bb3f1b03842a/src/librustc_trans/intrinsic.rs#L173-L177
- `type_name` exposed in libcore: https://github.com/rust-lang/rust/blob/a0dcecff90c45ad5d4eb60859e22bb3f1b03842a/src/libcore/intrinsics.rs#L689-L690
- `type_name`'s intrinsic type: https://github.com/rust-lang/rust/blob/a0dcecff90c45ad5d4eb60859e22bb3f1b03842a/src/librustc_typeck/check/intrinsic.rs#L152
- Walk immediate child types (method on `substs::type_at`'s return type, I think): https://github.com/rust-lang/rust/blob/ebddfcb0b19471d2277e05cfbc2ad8caa81637b7/src/librustc/ty/mod.rs#L2032-L2035

**Comment by Mark-Simulacrum** [comment]
So what I'd imagine is that we had a bunch of intrinsics for the individual bits (of which many exist already in some form) and then there'd be a wrapper struct, maybe in `std::any`, that calls the individual intrinsics and exposes a safe, but unstable, API. Then we could iterate further on that.

I don't think we should try to make an intrinsic return a struct, though I do believe it to be possible, since that seems unlikely to be a good approach; it makes it hard to interpret what the fields are to outside users'.

**Comment by CAD97** [comment]
Unless I missed something, the only current intrinsics that return type information are `type_id` and `type_name`.

**Comment by Mark-Simulacrum** [comment]
That's true. Or even just `split("::")` would probably work. @nagisa might have comments as to if that's sufficient or not... I'd lean towards no.

**Comment by nagisa** [comment]
This issue is about specifically redesigning the intrinsic. The intrinsic would be best off implemented as something that returns a tuple with all components, I think. The safe-wrapper would then put the data into fields of some named structure. It is true, that there aren't many intrinsics that would be as complicated as the structured `type_name` would end up being, so the implementation likely won’t be too easy.

Parsing strings is certainly not something we want to end up doing, because it is both inefficient and locks us into keeping the format of the string stable (not necessarily something we want). Besides, since this is an intrinsic, we can make it possible to implement `Display`/`Debug`, super efficiently (with a single `write_str()` call).

**Comment by najamelan** [comment]
> split("::")

As far as I can tell, this won't work if your type has generic parameters, because those also have a fqpn and you will get a very wrong result...

**Comment by Dylan-DPC** [comment]
This feature has been stabilised, so any changes would need a fresher discussion since it would possibly be a breaking change. Such a minor change doesn't have much gain at this moment so closing it.
