### ISSUE TITLE
Non-existent struct enum variant in pattern causes ICE

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust#34564]
This is a nightly regression, doesn't happen in 1.9 stable.

```Rust
fn main () {
    enum Enum {}
    if let Enum::Bar{} = unimplemented!() {}
}
```

```
error: internal compiler error: ../src/librustc/hir/def.rs:77: path not fully resolved: PathResolution { base_def: Enum(DefId { krate: 0, node: DefIndex(5) => main::Enum }), depth: 1 }
```

[Playground](https://is.gd/j6ybwA)

Locally tested with `rustc 1.11.0-nightly (ad7fe6521 2016-06-23)`

**Comment by petrochenkov** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/34209, fixed in https://github.com/rust-lang/rust/pull/34365.

**Comment by crumblingstatue** [comment]
Hmm. Strange I didn't find it when I searched for "enum struct ice". Closing.
