### ISSUE TITLE
[wishlist] portable way to pipe one command’s stdout to another’s stdin

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#34593]
Currently piping output between two commands involves going through raw handles and filedescriptors which requires `#[cfg]`d code and imports or spawning a thread and juggling data between two streams manually.

Ideally the API would be as simple as this:

```
let pipe = Stdio::interprocess_pipe();
let cmd1 = ….stdout(pipe.clone()).spawn();
let cmd2 = ....stdin(pipe).status();
```

or something along the lines.

**Comment by alexcrichton** [comment]
Added in https://github.com/rust-lang/rust/pull/42133
