### ISSUE TITLE
Print total time for a build invocation

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#34600]
I've found it nifty when building Servo that the total time for the build is printed at the end, and I think we may want to do so as well! Let's modify rustbuild (`src/bootstrap`) to print how long the entire program takes.

Depending on how easy it is we may want to modify the python script (`src/bootstrap/bootstrap.py`) as that's the wrapper for everything, but if it's too much effort then let's just modify `src/bootstrap/main.rs` and assume the python bits are fast.

Should be a pretty easy bug to knock out and I'd be willing to help out anyone interested!

**Comment by cynicaldevil** [comment]
I'll try my hand at this one.
