### ISSUE TITLE
Document arithmetic overflow behavior for atomic fetch_add and fetch_sub operations

### ISSUE THREAD

**Issue by mbrubeck** [rust-lang/rust#34618]
Are these operations guaranteed to wrap on overflow?  The documentation currently says nothing.

**Comment by nagisa** [comment]
undefined behaviour is all we can guarantee..

**Comment by nagisa** [comment]
Though it might be possible to implement overflow-checked fetch_add/sub in overflow-checked mode by doing CAS under the cover, to match the behaviour of operations with regular integers.

**Comment by rkruppe** [comment]
[LangRef](http://llvm.org/docs/LangRef.html#atomicrmw-instruction) doesn't say anything about overflow. Perhaps LLVM effectively assumes `nsw`/`nuw` but since that is not the default for the analogous "normal" operations, it's really impossible to guess. Perhaps ask LLVM developers?

**Comment by eefriedman** [comment]
The LLVM atomicrmw operations are guaranteed to wrap on overflow.  (I would never have guessed that anyone would assume anything else; I'll look into getting it documented.)

**Comment by mbrubeck** [comment]
> undefined behaviour is all we can guarantee, I think.

I hope you mean we guarantee *no* undefined behavior, since these are all safe functions.

**Comment by nagisa** [comment]
@mbrubeck usually overflowing an integer during operations is considered to be UB, which is why I said that. 

@eefriedman where does LLVM guarantee that?

**Comment by eefriedman** [comment]
http://llvm.org/docs/LangRef.html#add-instruction : "If the sum has unsigned overflow, the result returned is the mathematical result modulo 2<sup>n</sup>, where n is the bit width of the result."  Also, it would be impossible to implement C atomic add on top of atomicrmw if it had any other behavior.

**Comment by mbrubeck** [comment]
> usually overflowing an integer during operations is considered to be UB, which is why I said that.

Only in C and C++, right?  In Rust, arithmetic overflow is never undefined behavior.

**Comment by nagisa** [comment]
I don’t remember us making any guarantees about things which happen if integers overflow when overflow checks are not enabled, but it might just be me and my bad memory.

**Comment by nagisa** [comment]
[RFC 560](https://github.com/rust-lang/rfcs/blob/master/text/0560-integer-overflow.md) claims overflows are not UB in the C sense of UB, but still are a program error. I think we should strive to have atomics “behave” similarly.

**Comment by rkruppe** [comment]
Safe code must never have UB. And although "unspecified" results on overflow (i.e., some result which may not be relied on but has no side effects) were considered for a long time, the RFC now says that it always wraps:

> The operations +, -, *, can underflow and overflow. When checking is enabled this will panic. When checking is disabled this will two's complement wrap.

**Comment by Amanieu** [comment]
The C++11 atomic ops guarantee wrapping behavior (for both signed and unsigned integers). We should do the same.
