### ISSUE TITLE
libstd: Some fs tests check localized error messages and fail on non-English versions of Windows

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#34628]
The tests in question:

```
fs::tests::file_test_iounlinking_invalid_path_should_raise_condition
fs::tests::invalid_path_raises
fs::tests::open_flavors
```

They check that the error messages from OS contain the string "The parameter is incorrect" literally, but on non-English OS versions the error messages are translated.

cc @pitdicker @alexcrichton 
Feel free to close this issue if the fix is non-trivial, this is only a minor inconvenience - `make check` fails and the tests have to be skipped manually by `touch`ing `tmp/check-stage2-T-x86_64-pc-windows-gnu-H-x86_64-pc-windows-gnu-std.ok`.

**Comment by retep998** [comment]
It would be better if we checked the error code itself rather than analyzing the string, at least on Windows anyway where error codes are standardized. Should be a simple fix and I could mentor if someone wanted it.
