### ISSUE TITLE
Camel case warning fires on `X86_64`

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#34633]
I feel like the warning fires wrongly on this variant name in particular.

```
src/lib.rs:24:5: 24:11 warning: variant `X86_64` should have a camel case name such as `X8664`, #[warn(non_camel_case_types)] on by default
src/lib.rs:24     X86_64,
                  ^~~~~~
```

**Comment by Thiez** [comment]
[It looks like](https://github.com/rust-lang/rust/blob/6ae350213485f7c917113f3916e58c51cef97a76/src/librustc_lint/bad_style.rs#L66-L68) the warning fires whenever the name contains a '_' that is not leading or trailing. Would it be reasonable to make an exception for '_' if the characters directly before and after are digits?

**Comment by nagisa** [comment]
Adding an exception for digits only will lead to to an issue later about some other non-letter case. What should be done instead, IMO, is check that the character before and after `_` are letters and only warn then.

/me shrugs. Very bikeshedy thing to discuss.

**Comment by brson** [comment]
I understand wanting this to just work, but it's getting uncomfortably clever. Requiring a suppression here isn't so bad.

Is this a case that comes up other than for "X86_64"?
