### ISSUE TITLE
"The Book" Macro's confusing statement about binding rules

### ISSUE THREAD

**Issue by alex-sherwin** [rust-lang/rust#34631]
This statement "This holds for let bindings and loop labels, but not for items" implies that any "item" cannot introduce a new binding inside a macro.  The link to "items" includes functions as an "item", implying that you cannot introduce new function bindings.

But the following example does exactly that:

```
macro_rules! foo {
    () => (fn x() { });
}

fn main() {
    foo!();
    x();
}
```

I feel like this statement should be clarified, it confused me immediately, since it outlines two things that you *can* do, with a link of things you *cannot do*, yet the example is neither of the two things that you *can* do but is seemingly something you *cannot* do

**Comment by durka** [comment]
I think you lost the thread of the double negative (which means it should be rewritten to be less confusing). Here's what the book says with the interspersed code samples cut out:

> Rust has a hygienic macro system. Each macro expansion happens in a distinct ‘syntax context’, and each variable is tagged with the syntax context where it was introduced. It’s as though the variable state inside main is painted a different "color" from the variable state inside the macro, and therefore they don’t conflict.
> This also restricts the ability of macros to introduce new bindings at the invocation site. Code such as the following will not work:
> _[code that declares a local variable inside a macro and tries to use it outside]_
> Instead you need to pass the variable name into the invocation, so that it’s tagged with the right syntax context.
> _[the same code but with the name of the local passed in as an ident]_
> This holds for let bindings and loop labels, but not for items. So the following code does compile:
> _[code that declares a function inside a macro and uses it outside]

So "this" in "this holds" is the hygiene, which prevents identifiers escaping their syntax context. Hygiene does _not_ hold for items, which is why the function declaration works.

**Comment by alex-sherwin** [comment]
I think perhaps it should be re-worded, sections like this into the documentation are broken up between examples, I would expect most people trying to learn the language from this documentation will reach a section and stop at the examples and visualize/absorb/interact with them to solidify their understanding of  what they just read

Assuming that's true, reading it as I have been, I wouldn't expect to be confused by a stand-alone statement between examples

**Comment by steveklabnik** [comment]
Since I am re-writing the book, this will be fixed by that eventually. I would be happy to take a PR in the meantime if someone wants to improve the wording of this section. As such, I'm giving it a close. Thanks!
