### ISSUE TITLE
size_of and initializer type mismatch for C enums

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#34641]
For C enums (`#[repr(C)] enum A { ... }`) `::std::mem::size_of::<A>() = 4` is true on my system, however variant discriminants are required to be of type `isize`¹, and `isize` is `8` bytes big. Technically, Rust allows me to specify an invalid variant discriminant.

On systems where `isize` is 16 bits and C enum is still 32 bits, you cannot specify the whole range of discriminants.

¹: because discriminants with type != isize fail with constant eval error

```
error: constant evaluation error: mismatched types:
 expected `isize`,
    found `i32` [--explain E0080]
 --> test.rs:5:15
  |>
5 |> enum C { A = !0x0i32 }
  |>               ^^^^^^
```

**Comment by nagisa** [comment]
In old versions of rustc the same error came from typeck rather than constant evaluator.

**Comment by retep998** [comment]
Yes it is a known issue that `#[repr(C)] enum` is awful. https://github.com/rust-lang/rust/issues/28925

Then again Rust enums aren't even a valid substitute for C enums because C enums can hold any value safely while with Rust enums invalid variants are trap representations and cause UB.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this in favor of #28925, since that has a more detailed explanation of the issue.
