### ISSUE TITLE
Panic - idents with different contexts compared

### ISSUE THREAD

**Issue by enerqi** [rust-lang/rust#34640]
Panic building rustw with nightly windows x86 gnu.

`cargo build --release`

https://github.com/nrc/rustw at latest commit 73d3768b34d87f3f13d17f58194a6416f8394401 

thread 'rustc' panicked at 'idents with different contexts are compared with operator `==`: String#0, Config#2220.', ../src/libsyntax\ast.rs:116
## Meta

`rustc --version --verbose`:

rustc 1.11.0-nightly (1ab87b65a 2016-07-02)
binary: rustc
commit-hash: 1ab87b65a220a933dc9d171ef0fd865ddd88fe89
commit-date: 2016-07-02
host: x86_64-pc-windows-gnu
release: 1.11.0-nightly

Backtrace:

stack backtrace:
   0:         0x6f27ff7c - <unknown>
   1:         0x6f27f437 - <unknown>
   2:         0x6f244de4 - <unknown>
   3:         0x6f281025 - <unknown>
   4:         0x6f246c15 - <unknown>
   5:         0x62ba8023 - <unknown>
   6:          0x7205bcf - <unknown>
   7:          0x727f873 - <unknown>
   8:          0x71f1984 - <unknown>
   9:         0x62d93c26 - <unknown>
  10:         0x62dd8540 - <unknown>
  11:         0x62dd8166 - <unknown>
  12:         0x62dd6dba - <unknown>
  13:         0x62d93e69 - <unknown>
  14:         0x62dd8540 - <unknown>
  15:         0x62dd8166 - <unknown>
  16:         0x62dd6dba - <unknown>
  17:         0x62d93e69 - <unknown>
  18:         0x62dd8540 - <unknown>
  19:         0x62dd8166 - <unknown>
  20:         0x62dd6dba - <unknown>
  21:         0x62d93e69 - <unknown>
  22:         0x62d91d74 - <unknown>
  23:         0x62d9d6bd - <unknown>
  24:         0x62dd3ec2 - <unknown>
  25:         0x62dd3847 - <unknown>
  26:         0x62dd3659 - <unknown>
  27:         0x62dd27bc - <unknown>
  28:         0x62d943c3 - <unknown>
  29:         0x62d91d74 - <unknown>
  30:         0x62d9d6bd - <unknown>
  31:         0x62d9d342 - <unknown>
  32:         0x62d96841 - <unknown>
  33:         0x62dd4601 - <unknown>
  34:         0x62dd42fb - <unknown>
  35:         0x62d94b04 - <unknown>
  36:         0x62d91d74 - <unknown>
  37:         0x62d9d8ae - <unknown>
  38:         0x62d9d342 - <unknown>
  39:         0x62d96841 - <unknown>
  40:         0x62dd4601 - <unknown>
  41:         0x62dd42fb - <unknown>
  42:         0x62d94b04 - <unknown>
  43:         0x62d91d74 - <unknown>
  44:         0x62d9d8ae - <unknown>
  45:         0x62de6bb8 - <unknown>
  46:         0x62de7cb4 - <unknown>
  47:         0x61814a9c - <unknown>
  48:         0x617c416c - <unknown>
  49:         0x61795f73 - <unknown>
  50:         0x6178697c - <unknown>
  51:         0x617838e9 - <unknown>
  52:         0x6f28f5d8 - <unknown>
  53:         0x617843e3 - <unknown>
  54:         0x6f27d269 - <unknown>
  55:     0x7ff8ff292d91 - <unknown>

error: Could not compile `rustw`.

**Comment by TimNN** [comment]
The issue seems to be triggered by serde:

```
   1:        0x10527ddcb - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:        0x10528ac6a - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:        0x10528a79b - std::panicking::default_hook::he0146e6a74621cb4
   4:        0x10524ffb8 - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
   5:        0x10528b246 - std::panicking::begin_panic::he426e15a3766089a
   6:        0x105251df8 - std::panicking::begin_panic_fmt::hdddb415186c241e7
   7:        0x1049b7d56 - _<syntax..ast..Ident as core..cmp..PartialEq>::eq::h1cac43145945e564
   8:        0x106417034 - syntax::visit::walk_ty::hdcc38ee27307e5b7
   9:        0x1064753b0 - serde_codegen::ser::serialize_item::h00f24b4cdcf0239e
```

Also note that the `rustw` projects recommends you build using `nightly-2016-05-12` in case of build errors.

**Comment by Mark-Simulacrum** [comment]
As far as I can tell, a15dfca54f1b6e54226797fa12fe0d7a2bf9252e made this statically impossible (it removed the panic), so I'm closing.
