### ISSUE TITLE
problem in storing function (with generic arguments ) .

### ISSUE THREAD

**Issue by anil1596** [rust-lang/rust#34642]
struct New {num: i32 }
     struct ComplexThing <A>{   //( L1)
     calls:  Box<FnMut(&A)+Send+Sync>,
     }
     trait newstrait {
      fn display(&self);
    } 
    impl newstrait for New {
    fn display(&self){println!("new's num value : {}",self.num);}
    }
    impl newstrait for i32{
    fn display(&self){println!("number  : {}",self);}
    }
    fn  printline<A:newstrait>(p: &A){
         p.display();
    }
 
    fn main(){    
    let mut vec = Arc::new(Mutex::new(vec![ComplexThing{calls: Box::new(printline)}]));
    let mut len; 
     {
     let mut vec = vec.lock().unwrap();
     vec.push(ComplexThing{calls: Box::new(printline)}); //storing function in vector
     len = vec.len();
     }  
     for i in 0..len{
     thread::spawn(move||{
     let vec = vec.clone();
     let mut vec= vec.lock().unwrap();
     let ref mut elem =vec[i].calls;                
     if i!=1{
     elem(&New{num:1080}); //calling stored function with instance of structure New as argument ( L2 )     
     }else{
     let num = 434;
     elem(&num);   //calling stored function with i32  as an argument (L3)
     }  
     });           
      } 
      }

It is initialising generic type (A) at  L1 with  the type of arguments which are sent first and giving error on L3
          function_structure2.rs:33:11: 33:15 error: mismatched types:
          expected `&new`,
          found `&_`
          (expected struct `new`,
                 found integral variable) [E0308]
           function_structure2.rs:33      elem(&num); 

I read from https://gist.github.com/Kimundi/8391398  that rust makes copies of function which takes generic arguments for each type at compile time .
If a generic type is initialised with with  the type of arguments which are sent first ,then how to overcome this???

**Comment by Aatch** [comment]
The issue tracker is for problems with the compiler and standard library, please use the user forums (https://users.rust-lang.org) or IRC (irc.mozilla.org, channels #rust and #rust-beginners) for these kinds of queries.
