### ISSUE TITLE
Get rid of (almost all) drop flags with NonZero

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#34656]
C++'s version of drop flags is to have the programmer null something in the move constructor. This is similar to what we required with `unsafe_no_drop_flag`, except it is done in the move constructor instead of the destructor.

It occurs to me that we can use this to get rid of almost all the drop flags. Most drop flags are on nonzero-containing structs, except for things like `File`.

Whenever we have a `Drop` type on the stack in a situation that needs a drop flag, and it _unconditionally_ contains a NonZero, instead of inserting the drop flag, just null out the nonzero and check for it in the drop glue.

When I say unconditionally, I mean that there can't be an enum in between. So while the following types can be optimized this way:

``` rust
Vec<T>, Option<Vec<T>>
struct Foo {
  x: Vec<T>
}
impl Drop for Foo {}

// this is okay, because the drop flag is attached to the vec
// not the Bar. So we can pretend it is Quux after it has moved
// out because nobody will read it
enum Bar {
 Baz(Vec<T>, u8, Box<T>, ...)
 Quux
}
// Bar is not explicitly Drop
```

The following types cannot:

``` rust
struct Foo {
  x: Option<Vec<T>>
}
impl Drop for Foo {}

enum Bar {
 Baz(Vec<T>, u8, Box<T>, ...)
 Quux
}
impl Drop for Bar {}
```

So, the type that is `Drop` (not any non-explicit-`Drop` structs or enums around it) must always contain a `NonZero<T>`, notwithstanding any changes in discriminants.

Conceptually, this optimization is just replacing drop types with `Option<DropType>` and moves with `.take()`, at a post-borrowck stage.

cc @Aatch @eddyb @nikomatsakis

**Comment by eddyb** [comment]
@Manishearth Seems doable, as long as user code can *never* observe this property.
We have unchecked downcasts so we could just wrap locals in literally `Option` in MIR drop elaboration.

However, that might lower the number of immediate locals and require SROA to split them up again,
and if you do it on polymorphic code based on the fact that `sizeof Option<T> == sizeof T`, you won't catch a whole lot of generic cases.

**Comment by eefriedman** [comment]
It's probably doable... but it's not obvious it's a good idea.  A separate drop flag will get put into registers almost immediately by LLVM's mem2reg pass, but a drop flag stuck in the middle of a struct whose address is used much more difficult to analyze.

**Comment by Aatch** [comment]
@eefriedman that's my concern too. An "on-stack" drop flag is much easier for LLVM to analyze.

**Comment by nikomatsakis** [comment]
Is there even any data on how often we need drop flags? I suspect they are quite unusual and -- as others have noted -- not expensive when you do need them.

**Comment by bstrie** [comment]
I presume this (quite old) issue concerns the old-style drop flags rather than the new-style drop flags which have long since replaced them? It would be nice to get some clarification on if this is still relevant, or if the issue could be closed.

**Comment by Manishearth** [comment]
Still relevant, it could be used to get rid of the extra stack slot.

**Comment by jonas-schievink** [comment]
Is this worth it? Drop flags are only needed if it's not statically known whether something needs to be dropped. That limits the benefits of this optimization a lot.

**Comment by Manishearth** [comment]
Probably not as much as it would have been when this issue is filed, yeah

**Comment by Mark-Simulacrum** [comment]
I would also suspect that https://github.com/rust-lang/rust/issues/34656#issuecomment-230559748 is correct in that embedding is plausibly worse than normal drop flags. I would also, like Niko, be interested in some statistics as to how often drop flags are actually generated in practice. My initial guess is "almost never", but it's entirely non-scientific.

I wonder how easy it would be to get the compiler to dump the relevant information out...

**Comment by Manishearth** [comment]
I'm down with just closing this since it's very likely not worth the effort even if it is an improvement
