### ISSUE TITLE
std::io::Read.read's documentation should mention ErrorKind::Interrupted

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#34661]
https://doc.rust-lang.org/std/io/trait.Read.html#tymethod.read currently says:

> This function does not provide any guarantees about whether it blocks waiting for data, but if an object needs to block for a read but cannot it will typically signal this via an Err return value.

This could be taken as meaning EAGAIN/EWOULDBLOCK need to be handled (which, btw, is not in ErrorKind, but O_NONBLOCK is probably not in libstd anyways), but it looks like it means one needs to handle EINTR, which, if you're not familiar with the POSIX API, is very easy to skip.

BTW, this, unfortunately, makes read() cumbersome to use.

**Comment by sfackler** [comment]
> (which, btw, is not in ErrorKind

https://doc.rust-lang.org/std/io/enum.ErrorKind.html#variant.WouldBlock

**Comment by steveklabnik** [comment]
sub-bug of https://github.com/rust-lang/rust/issues/40322

**Comment by steveklabnik** [comment]
(as such, closing it in favor of that one, even though this one is older, as that one is more general)
