### ISSUE TITLE
resolve: `resolver.with_module_lexical_scope()` needs testing

### ISSUE THREAD

**Issue by jseyfried** [rust-lang/rust#34673]
cc @nrc

**Comment by jseyfried** [comment]
cc @JohnHeitmann (c.f. #34655)

**Comment by Mark-Simulacrum** [comment]
@jseyfried This function is unused within this repository; can you comment on what kind of testing you mean? Is this compile-fail/run-pass tests? I don't think so; since it's unused.

**Comment by jseyfried** [comment]
@Mark-Simulacrum Unit testing that it behaves correctly.

**Comment by JohnTitor** [comment]
Triage: I'm going to close as outdated, since I cannot find this method in `rustc_resolve` now. If the method still exists somewhere and I overlook it, feel free to re-open.
