### ISSUE TITLE
IndexItem should be serialised as an object rather than an array

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#34678]
See html/render.rs for the Rust side and main.js and possibly other places for the JS side.

I see no reason why this struct is serialised as an array, thus losing the information about which field is which. Using an object would retain that information and make things less error-prone, I believe.

**Comment by GuillaumeGomez** [comment]
You've got this issue when running rustdoc on librustdoc? Can you give me the `rustdoc` command you used to generate doc please?

**Comment by nrc** [comment]
This isn't a bug, but a suggestion for improvement. It's just a refactoring of the code, it doesn't need to be run on anything.

Having read the code a bit more, I think the reason it might be done like this is for efficiency, but I don't think that is important here - doesn't really matter if we use a few more bytes for the index, right?

**Comment by GuillaumeGomez** [comment]
Ah ok, my bad. I thought the output of this struct in particular was bad. Sorry about the misunderstanding! :smiley_cat:

**Comment by jonas-schievink** [comment]
Seems like this was done deliberately in #13431

**Comment by nrc** [comment]
Based on #13431, looks like we should not do this.
