### ISSUE TITLE
A diagnostic for flipping let declaration order

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#34692]
This might be a bit far out, but consider an example like this:  https://play.rust-lang.org/?gist=d082c5d632ab0249fe1fa917c76f7178&version=stable&backtrace=0

Here, the solution is to flip lines 7 and 8.  We should be able to detect this and make a better recommendation.

/cc @jonathandturner @nikomatsakis

**Comment by steveklabnik** [comment]
Triage: we do have 

     = note: values in a scope are dropped in the opposite order they are created

**Comment by estebank** [comment]
The code now works on 2018 mode and needs no diagnostic change.
