### ISSUE TITLE
writeln! documentation should tell what kind of newline is used

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#34697]
As I was using writeln! to fill an in-memory buffer for data that explicitly wants a specific type of newlines (LF, fortunately), and I was wondering whether writeln! would always use LF, or would use the type of newline relevant to the platform (essentially, LF on Unix, CR/LF on Windows), and couldn't find the answer in https://doc.rust-lang.org/std/macro.writeln!.html.

(I got my answer on IRC, it's always LF)

There may be other places where such information is relevant (println! comes to mind).

Cc: @steveklabnik

**Comment by GuillaumeGomez** [comment]
@glandium: Sure, want to add it? :)

**Comment by glandium** [comment]
I would, if I knew whether there are other places that would benefit from this information as well.

**Comment by GuillaumeGomez** [comment]
Except for `writeln!` and `println!`, I don't see any places... You can already add it to these docs and if another function/macro needs it, then we'll add it.
