### ISSUE TITLE
More clearly Error Message: Calculating with different types

### ISSUE THREAD

**Issue by StefanoD** [rust-lang/rust#34698]
This yields with rust 1.9

`let result = -0.25 % 2;`

following error message:

> <anon>:7:18: 7:27 error: the trait bound `_: std::ops::Rem<_>` is not satisfied [E0277]
> <anon>:7     let result = -0.25 % 2;
>                           ^~~~~~~~~
> <anon>:7:18: 7:27 help: see the detailed explanation for E0277
> <anon>:7:18: 7:27 help: the following implementations were found:
> <anon>:7:18: 7:27 help:   <f64 as std::ops::Rem>
> <anon>:7:18: 7:27 help:   <&'a f64 as std::ops::Rem<f64>>
> <anon>:7:18: 7:27 help:   <f64 as std::ops::Rem<&'a f64>>
> <anon>:7:18: 7:27 help:   <&'b f64 as std::ops::Rem<&'a f64>>
> <anon>:7:18: 7:27 help: and 54 others
> error: aborting due to previous error

This is the fix:

`let result = -0.25 % 2.0;`

This is a really compilicated error message for the fact, that calucating with different types are not allowed.

**Comment by brson** [comment]
cc @jonathandturner

**Comment by jonathandturner** [comment]
cc @nikomatsakis - who was thinking about better type error reporting

**Comment by Mark-Simulacrum** [comment]
Fixed today, I think. We don't give a suggestion as to `float % float` but I don't really think that's feasible.

```
rustc 1.19.0-dev (5dfcd85fd 2017-05-19)
error[E0277]: the trait bound `{float}: std::ops::Rem<{integer}>` is not satisfied
 --> test.rs:2:14
  |
2 | let result = -0.25 % 2;}
  |              ^^^^^^^^^ the trait `std::ops::Rem<{integer}>` is not implemented for `{float}`
  |
  = note: no implementation for `{float} % {integer}`

error: aborting due to previous error

```
