### ISSUE TITLE
this is funny :)

### ISSUE THREAD

**Issue by icanrealizeum** [rust-lang/rust#34704]
The funny part is that in the same place we get these two errors:
`expected i32, found ()`
`expected (), found i32`
I get why it happens, I just thought it's a funny quirk :D

```rust
fn main() {
    let x = 5;

    let y: i32 = if x == 5 {
        10
    };
    println!("{:?}",y);
}
```

```
error: if may be missing an else clause [--explain E0308]
 --> <anon>:4:18
  |>
4 |>     let y: i32 = if x == 5 {
  |>                  ^ expected (), found i32
note: expected type `()`
note:    found type `i32`

error: aborting due to previous error
Compilation failed.
```

`expected (), found i32`

```rust
fn main() {
    let x = 5;

    let y: i32 = if x == 5 {
        10;
    };
    println!("{:?}",y);
}
```

**EDIT:** grrrr, accidentally pressed Ctrl+Enter and I wasn't done editing!!!

```
error: mismatched types [--explain E0308]
 --> <anon>:4:18
  |>
4 |>     let y: i32 = if x == 5 {
  |>                  ^ expected i32, found ()
note: expected type `i32`
note:    found type `()`

error: aborting due to previous error
```

`expected i32, found ()`

source: https://doc.rust-lang.org/book/if.html

**Comment by arielb1** [comment]
Yeah. In one case the error is caused by the type annotation, and in the other the error is caused by an if expression without an else. Type errors are and will continue to be reported by the first place that finds them.
