### ISSUE TITLE
Semantics of Receiver::try_recv() differ between Sender and SyncSender

### ISSUE THREAD

**Issue by GGist** [rust-lang/rust#34711]
<short summary of the bug>

I tried this code:

```rust
use std::sync::mpsc::{self};
use std::mem;

fn main() {
    let (sync_send, sync_recv) = mpsc::sync_channel(1);
    
    sync_send.send(()).unwrap();
    mem::drop(sync_send);
    
    println!("{:?}", sync_recv.try_recv());
    
    //-----------------------------------------//

    let (send, recv) = mpsc::channel();
    
    send.send(()).unwrap();
    mem::drop(send);
    
    println!("{:?}", recv.try_recv());
}
```

I expected to see this happen:
```
Ok(())
Ok(())
```

Instead, this happened:
```
Err(Disconnected)
Ok(())
```

## Notes

I see that in the docs there is a comment under the ```Receiver::recv()``` method that states "However, since channels are buffered, messages sent before the disconnect will still be properly received." but this comment is not duplicated under ```Receiver::try_recv()```.

However, I tried tracing the specific ```Receiver``` used in conjunction with ```SyncSender```s which led me to [here](https://github.com/rust-lang/rust/blob/master/src/libstd/sync/mpsc/sync.rs#L312) where it looks like an eager check for a disconnect while ignoring possible data that is still buffered in the ```Queue```. Is this intended?

**Comment by alexcrichton** [comment]
Oh dear, this definitely looks like a bug to me! If you've got a fix in mind, feel free to send a PR of course!
