### ISSUE TITLE
E0502 not rendered correctly

### ISSUE THREAD

**Issue by timothy-mcroy** [rust-lang/rust#34716]
#32777 

The markdown bug that I introduced in 
https://github.com/rust-lang/rust/commit/acfe199c02a3cbc0d500678ea30426daf392f0d3

was fixed at 

https://github.com/rust-lang/rust/commit/ae755938640e4477acc77331aac2b02d0f17ac94

but somehow was undone during merging.

https://github.com/rust-lang/rust/blame/master/src/librustc_borrowck/diagnostics.rs#L505

This is causing the markdown bug to be rendered on the compiler documentation. 

https://doc.rust-lang.org/error-index.html#E0506

@GuillaumeGomez

**Comment by brson** [comment]
This is an easy bug to fix. Just correct the markdown per the OP.

**Comment by GuillaumeGomez** [comment]
@timothy-mcroy: @brson said it was an easy bug. Want to do it?

**Comment by srinivasreddy** [comment]
I am taking it.

**Comment by timothy-mcroy** [comment]
@GuillaumeGomez I would have simply made the PR, but I'm pretty swamped with summer school at the moment.  Thanks @srinivasreddy

**Comment by GuillaumeGomez** [comment]
@timothy-mcroy: Don't worry, if @srinivasreddy wouldn't have take it, i would have done it. It's just that it's an easy contribution so I try to leave them to new contributors.

**Comment by brson** [comment]
@srinivasreddy How's this going?

**Comment by srinivasreddy** [comment]
sorry for the delayed response. But i do not see why E0502 is rendered incorrect. I cannot find the missing empty line before and after - ```.   Maybe @timoth-mcroy could shed some light on this.

**Comment by srinivasreddy** [comment]
Or may be it was fixed in meantime?

**Comment by GuillaumeGomez** [comment]
It seems fixed. I close it then.
