### ISSUE TITLE
Document bool cast semantics

### ISSUE THREAD

**Issue by porglezomp** [rust-lang/rust#34729]
After a short debate on the IRC over whether `true as i32` is guaranteed to be `1`, and `false as i32` is guaranteed to be `0`, I think that the [semantics section on casts](https://doc.rust-lang.org/book/casting-between-types.html#numeric-casts) should explicitly describe what a `bool as integer_type` cast does.

**Comment by est31** [comment]
The reference [indirectly](https://doc.rust-lang.org/reference.html#behavior-considered-undefined) documents the representation, but the [machine types](https://doc.rust-lang.org/reference.html#machine-types) section would deserve documentation of the `bool` type as well.

**Comment by steveklabnik** [comment]
The reference lives in its own repo, so I have moved this there: https://github.com/rust-lang-nursery/reference/issues/20 Thanks!
