### ISSUE TITLE
doc: prose mentioning types should include links to that type

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#34747]
See for example https://doc.rust-lang.org/std/macro.vec!.html

There are many mentions of `Vec`, like in

> Creates a `Vec` containing the arguments.

and it would really be useful if that linked to the corresponding type.

**Comment by steveklabnik** [comment]
This is generally true, however, this ticket isn't particularly actionable, since there's no good way to tell if we've got them all or not. As such, I'm going to give it a close, but yes, any PRs to improve linking here is a good thing!

**Comment by steveklabnik** [comment]
(And, is partially covered by all the "all API docs" metabug)

**Comment by glandium** [comment]
Is there an type of markdown annotation that would automatically consider those as types? After looking around, it doesn't seem to. On the contrary, it seems one needs to put explicit links manually, as in https://doc.rust-lang.org/src/core/up/src/libcore/any.rs.html#20.

I'd argue it would be nice if rustdoc allowed to annotate things in a way such that types can be linked properly without having to add explicit links to `../../std/(...)`

**Comment by steveklabnik** [comment]
Not currently, but see https://github.com/rust-lang/rfcs/pull/1661
