### ISSUE TITLE
Internal compiler error in rustfmt on the playpen

### ISSUE THREAD

**Issue by DemiMarie** [rust-lang/rust#34775]
In the Rust playpen, trying to format [this mess](https://play.rust-lang.org/?code=use%20std%3A%3Amarker%3A%3APhantomData%3B%20use%20std%3A%3Acollections%3A%3AHashSet%3B%20use%20std%3A%3Ahash%3A%3A%7BHash%2C%20Hasher%7D%3B%20use%20std%3A%3Aborrow%3A%3ABorrow%3B%20struct%20PartMap%20K%2C%20V%2C%20F%3A%20Fn%20%26V%20%20-%3E%20%26K%20%2B%20Clone%3E%20%7B%20map%3A%20HashSet%20Wrap%20K%2C%20V%2C%20F%3E%3E%2C%20fun%3A%20F%2C%20_p%3A%20PhantomData%20K%3E%2C%20%7D%20struct%20Wrap%20K%2C%20V%2C%20F%3A%20Fn%20%26V%20%20-%3E%20%26K%3E%20%7B%20v%3A%20V%2C%20fun%3A%20F%2C%20_p%3A%20PhantomData%20K%3E%2C%20%7D%20impl%20K%2C%20V%2C%20F%3A%20Fn%20%26V%20%20-%3E%20%26K%3E%20Borrow%20K%3E%20for%20Wrap%20K%2C%20V%2C%20F%3E%20%7B%20fn%20borrow%20%26self%20%20-%3E%20%26K%20%7B%20self.key%20%20%20%7D%20%7D%20impl%20K%2C%20V%2C%20F%3A%20Fn%20%26V%20%20-%3E%20%26K%3E%20Wrap%20K%2C%20V%2C%20F%3E%20%7B%20fn%20key%20%26self%20%20-%3E%20%26K%20%7B%20%20self.fun%20%20%26self.v%20%20%7D%20%7D%20impl%20K%3A%20Hash%2C%20V%2C%20F%3A%20Fn%20%26V%20%20-%3E%20%26K%3E%20Hash%20for%20Wrap%20K%2C%20V%2C%20F%3E%20%7B%20fn%20hash%20H%3E%20%26self%2C%20state%3A%20%26mut%20H%20%20where%20H%3A%20Hasher%20%7B%20self.key%20%20.hash%20state%20%3B%20%7D%20%7D%20impl%20K%3A%20PartialEq%2C%20V%2C%20F%3A%20Fn%20%26V%20%20-%3E%20%26K%3E%20PartialEq%20for%20Wrap%20K%2C%20V%2C%20F%3E%20%7B%20fn%20eq%20%26self%2C%20other%3A%20%26Self%20%20-%3E%20bool%20%7B%20self.key%20%20%20%20%20%20other.key%20%20%20%7D%20%7D%20impl%20K%3A%20Eq%2C%20V%2C%20F%3A%20Fn%20%26V%20%20-%3E%20%26K%3E%20Eq%20for%20Wrap%20K%2C%20V%2C%20F%3E%20%7B%7D%20impl%20K%3A%20Eq%20%2B%20Hash%2C%20V%2C%20F%3A%20Fn%20%26V%20%20-%3E%20%26K%20%2B%20Clone%3E%20PartMap%20K%2C%20V%2C%20F%3E%20%7B%20pub%20fn%20new%20f%3A%20F%20%20-%3E%20Self%20%7B%20PartMap%20%7B%20map%3A%20HashSet%3A%3Anew%20%20%2C%20fun%3A%20f%2C%20_p%3A%20PhantomData%2C%20%7D%20%7D%20fn%20wrap%20%26self%2C%20v%3A%20V%20%20-%3E%20Wrap%20K%2C%20V%2C%20F%3E%20%7B%20Wrap%20%7B%20v%3A%20v%2C%20fun%3A%20self.fun.clone%20%20%2C%20_p%3A%20PhantomData%20%7D%20%7D%20pub%20fn%20insert%20%26mut%20self%2C%20v%3A%20V%20%20-%3E%20Option%20V%3E%20%7B%20let%20wrap%20%20%20self.wrap%20v%20%3B%20self.map.replace%20wrap%20.map%20%7Cw%7C%20w.v%20%20%7D%20pub%20fn%20get%20%26self%2C%20k%3A%20%26K%20%20-%3E%20Option%20%26V%3E%20%7B%20self.map.get%20k%20.map%20%7Cw%7C%20%26w.v%20%20%7D%20%7D%20fn%20main%20%20%20%7B%20%7D&version=stable&backtrace=0#21424933432789284650) causes this:

```
error: internal compiler error: Error constructed but not emitted
thread 'main' panicked at 'explicit panic', root/.cargo/registry/src/github.com-1ecc6299db9ec823/syntex_syntax-0.32.0/src/errors/mod.rs:361
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by jonas-schievink** [comment]
That's a rustfmt or syntex issue

**Comment by Mark-Simulacrum** [comment]
This no longer ICEs. Marking as E-needstest.

```
$ rustfmt --write-mode overwrite test.rs
error: expected `where`, `{`, `(`, or `;` after struct name, found `K`
 --> test.rs:1:133
  |
1 | use std::marker::PhantomData; use std::collections::HashSet; use std::hash::{Hash, Hasher}; use std::borrow::Borrow; struct PartMap K, V, F: Fn &V  -> &K + Clone> { map: HashSet Wrap K, V, F>>, fun: F, _p: PhantomData K>, } struct Wrap K, V, F: Fn &V  -> &K> { v: V, fun: F, _p: PhantomData K>, } impl K, V, F: Fn &V  -> &K> Borrow K> for Wrap K, V, F> { fn borrow &self  -> &K { self.key   } } impl K, V, F: Fn &V  -> &K> Wrap K, V, F> { fn key &self  -> &K {  self.fun  &self.v  } } impl K: Hash, V, F: Fn &V  -> &K> Hash for Wrap K, V, F> { fn hash H> &self, state: &mut H  where H: Hasher { self.key  .hash state ; } } impl K: PartialEq, V, F: Fn &V  -> &K> PartialEq for Wrap K, V, F> { fn eq &self, other: &Self  -> bool { self.key      other.key   } } impl K: Eq, V, F: Fn &V  -> &K> Eq for Wrap K, V, F> {} impl K: Eq + Hash, V, F: Fn &V  -> &K + Clone> PartMap K, V, F> { pub fn new f: F  -> Self { PartMap { map: HashSet::new  , fun: f, _p: PhantomData, } } fn wrap &self, v: V  -> Wrap K, V, F> { Wrap { v: v, fun: self.fun.clone  , _p: PhantomData } } pub fn insert &mut self, v: V  -> Option V> { let wrap   self.wrap v ; self.map.replace wrap .map |w| w.v  } pub fn get &self, k: &K  -> Option &V> { self.map.get k .map |w| &w.v  } } fn main   { }
  |                                                                                                                                     ^
```

**Comment by Mark-Simulacrum** [comment]
Well, actually, this is maybe(?) never was a compiler bug, so closing and removing E-needstest. I'm not even sure what we would really be testing here...
