### ISSUE TITLE
Cannot match against enum discriminants

### ISSUE THREAD

**Issue by casey** [rust-lang/rust#34773]
It does not appear to be possible to match an integer against enum discriminants.

Example here: https://is.gd/HMrSU6

```
#![repr(u8)]
enum Foo {
    A = 0,
    B = 1,
    C = 2
}

fn main() {
    let x = 0u8;
    match x {
        Foo::A as u8 => println!("A"),
        Foo::B as u8 => println!("B"),
        Foo::C as u8 => println!("C"),
        _ => println!("No match!"),
    };
}
```

and the error message:

```
error: expected one of `::`, `=>`, `if`, or `|`, found `as`
  --> <anon>:11:16
11 |>         Foo::A as u8 => println!("A"),
   |>                ^^

error: aborting due to previous error
```

Since discriminants are compile-time constants, it seems like this should be allowed.

**Comment by jonas-schievink** [comment]
You can't match against arbitrary constant expressions. This does in fact work if you put the `u8` discriminant into a constant:

```rust
#![repr(u8)]
enum Foo {
    A = 0,
    B = 1,
    C = 2
}

fn main() {
    let x = 0u8;
    const A: u8 = Foo::A as u8;
    const B: u8 = Foo::B as u8;
    const C: u8 = Foo::C as u8;
    
    match x {
        A => println!("A"),
        B => println!("B"),
        C => println!("C"),
        _ => println!("No match!"),
    };
}
```

**Comment by casey** [comment]
Hmm, interesting, I just kind of assumed that that would be allowed. Is there a reason you can't?

**Comment by jonas-schievink** [comment]
Well for one it would create an ambiguity with the `|` operator:

```rust
fn main() {
    match 0 {
        0 | 1 => println!("aaa"),
        _ => println!("nope"),
    }
}
```

This prints "aaa" now (since `|` matches the left or right pattern), but if you interpret `0 | 1` as an expression it would equal `1` and "nope" would be printed.

**Comment by casey** [comment]
Oh right, I forgot that the corner of the grammar that applies here is the grammar for patterns, which is different than the grammar for expressions.

I suppose in that case my suggestion would be to extend the pattern grammar to allow `as` casts.

**Comment by nagisa** [comment]
> I suppose in that case my suggestion would be to extend the pattern grammar to allow as casts.

RFC.

**Comment by fweimer** [comment]
This worries me a bit:

```rust
    const A: u8 = Foo::A as u8;
```

What if the discriminating integer for `Foo::A` does not fit into a `u8`? How would I even detect this?

**Comment by casey** [comment]
Closing this, since it's RFC material.
