### ISSUE TITLE
tests for cleanup in guards

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#3478]
I realized I forgot to ensure that there are tests for cleanup of by-value bindings in match guards.  For example, if the guard should fail, or be false, we have to be sure we don't leak.  Similarly, just testing that if the guard is taken, cleanup occurs---there may not be good dedicated tests for that either.

**Comment by cmr** [comment]
I don't see any tests for this still, though I'm not sure if this is refering to the no-longer-allowed ability to move from the matched value in the guard.

**Comment by steveklabnik** [comment]
Triage: this ticket is incredibly old at this point. I'm going to assume @cmr is right. @nikomatsakis if you think that's wrong, please re-open with the correct context.
