### ISSUE TITLE
Broken link in website

### ISSUE THREAD

**Issue by gabomgp** [rust-lang/rust#34790]
The link [improving the IDE experience](https://www.rust-lang.org/en-US/ides.html)  is broken in page https://www.rust-lang.org/en-US/contribute-tools.html

**Comment by eefriedman** [comment]
CC @steveklabnik

**Comment by steveklabnik** [comment]
@brson, we wanted to point this to the Forge, yeah?

**Comment by brson** [comment]
Yes, that's my slight preference, bu I don't understand why the link is broken. The source file exists.
