### ISSUE TITLE
Inverted Color Scheme for The Book

### ISSUE THREAD

**Issue by Razaekel** [rust-lang/rust#34795]
It'd be nice to have a inverted color scheme (ex. White on Black) for The Book, especially for those late night coding sessions or for those who prefer reading a dark theme.

**Comment by steveklabnik** [comment]
This will likely be fixed when the new book is merged; rustbook does not support themes, but mdbook does, and we're using it for the new one.

**Comment by Razaekel** [comment]
Oh nice! Is there a outstanding PR or tracking issue for the new book?

**Comment by GuillaumeGomez** [comment]
@Razaekel: Here you go:

https://github.com/rust-lang/book
http://rust-lang.github.io/book/

**Comment by Razaekel** [comment]
Wow, those look nice! Thanks!

**Comment by retep998** [comment]
@GuillaumeGomez Now we just need the same for the rustdoc documentation.

**Comment by steveklabnik** [comment]
Given that this isn't going to be fixed before the new book happens, and that it will address this issue, I'm going to give it a close. Thanks!
