### ISSUE TITLE
Reference doc on `cfg` does not cover `cfg(feature = "...")`

### ISSUE THREAD

**Issue by dhardy** [rust-lang/rust#34803]
Rust appears to support `#[cfg(feature = "foo")]` to control optional features: [Cargo doc](http://doc.crates.io/manifest.html#the-features-section).

The Rust reference on `cfg` does not mention `feature`: [nightly doc](https://doc.rust-lang.org/nightly/reference.html#conditional-compilation).

**Comment by kennytm** [comment]
Rust support `#[cfg(anything)]` when you pass `--cfg anything` to rustc. Cargo is just passing `--cfg feature=foo` to the compiler.

The documentation could be improved to mention the `--cfg` flag though.

**Comment by dhardy** [comment]
Something's slightly odd with the doc though, because [this](https://doc.rust-lang.org/nightly/reference.html#conditional-compilation) says that the `feature="foo"` form is only allowed with compiler-defined configuration options, which means `feature` is compiler-defined.

**Comment by kennytm** [comment]
Probably outdated, or the reference is misinterpreting the meaning of [RFC 194](https://github.com/rust-lang/rfcs/pull/194).  The following works:

```rust
fn main() {
    println!("{}", cfg!(a="b"));
}
```

```bash
$ rustc --cfg 'a="b"' 1.rs && ./1
true
```

**Comment by steveklabnik** [comment]
The reference has its own repo now, I have migrated this issue over there: https://github.com/rust-lang-nursery/reference/issues/21 Thanks!
