### ISSUE TITLE
rustbuild: `doc-rustc` overwrites search index

### ISSUE THREAD

**Issue by TimNN** [rust-lang/rust#34800]
Building the compiler docs with rustbuild overwrites the js search index of the std docs with the one from the compiler docs.

~~Example: https://rust-beta-doc.timnn.me/std/index.html?search=String~~ (that is no longer live).

**Comment by alexcrichton** [comment]
Hm I think that this may be a result of a little too aggressively cleaning out the `doc` directory, there's probably some `fs::remove_dir_all` which should be sequenced differently or perhaps just not run at all.

**Comment by ollie27** [comment]
This was fixed by #40199.

**Comment by alexcrichton** [comment]
Indeed!
