### ISSUE TITLE
Llvm assertion failed when using malformed? asm!() parameters

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#34821]
When I try to compile this code I get a llvm assertion:

```rust
#![feature(asm)]
fn main() {
    let loc = 0;
    unsafe{
        asm!("jmp [$loc]" : "={loc}"(&loc));
    }
}
```

The assertion is:
```
rustc: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/include/llvm/CodeGen/FunctionLoweringInfo.h:173: unsigned int llvm::FunctionLoweringInfo::InitializeRegForValue(const llvm::Value*): Assertion `R == 0 && "Already initialized this value register!"' failed.
Aborted (core dumped)
```

It's build using the nightly the playground is using when I write this issue.

**Comment by shepmaster** [comment]
It's unclear to me what you are trying to accomplish, but I believe your syntax is incorrect.

The complete syntax for `asm!`, so far I know is:

```
asm!(  // assembly
     : // output operands
     : // input operands
     : // clobbers
     : // options
)
```

And it appears you are trying to use an output-only variable as input. Changing to this compiles:

```rust
#![feature(asm)]
fn main() {
    let loc = 0;
    unsafe {
        asm!("jmp [$loc]" : : "{loc}"(&loc) : );
    }
}
```

Also, I just learned you have give variables names through the macro; all my assembly has the terrible `$0`, `$1` auto-generated names!

**Comment by shepmaster** [comment]
> Also, I just learned you can give variables names through the macro;

Actually, I'm not sure that you can. The code I posted earlier does the annoying thing of just eating the malformed assembly with no errors; it's not present in the disassembled output. I think it's trying to write to the `loc` register, which doesn't exist. The syntax for specifying a symbolic name would look something like `[loc] "r" (&loc)`, which isn't parsed by the current macro.

**Comment by bjorn3** [comment]
Why does llvm crash, instead of rust giving me a error?

**Comment by shepmaster** [comment]
> Why does llvm crash, instead of rust giving me a error?

I don't know how to answer that in a useful manner. Presumably LLVM has an assertion because they expect no one to ever trigger that case and Rust doesn't guard against it because the inline assembly is (mostly) directly handed to LLVM.

It appears that clang does some amount of sanitization before directly handing it to LLVM:

```
foo.c:3:22: error: invalid output constraint '{loc}' in asm
  asm ("jmp [$loc]" :"{loc}"(&loc) : :);
                     ^
```

**Comment by bjorn3** [comment]
Ok, I will close this.
