### ISSUE TITLE
Tracking issue for --explain expansion

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#34827]
Tracking issue for the `--explain` related portions of https://github.com/rust-lang/rfcs/pull/1644

Current open questions are:
- Let's look at an implementation! Does it end up being reasonable?
- Is there a way to deprecate `--explain <CODE>` and instead use `--explain` to activate these errors?
- Is it easy to template these longer explanations for authors?

cc @jonathandturner (feel free to fill out more)

**Comment by GuillaumeGomez** [comment]
Some error explanations are (I think) very easy to update to this new RFC. Some others (the longest or most "general" ones) are almost impossible as is. Some rework on these last ones is needed first (split them in smaller errors for example).

**Comment by Dylan-DPC** [comment]
#61137

**Comment by GuillaumeGomez** [comment]
Closing this one then.
