### ISSUE TITLE
bad-style check suggestion: Guard clauses

### ISSUE THREAD

**Issue by phillipp** [rust-lang/rust#34820]
Hi,
I tried Rust today and I really like what you created!

I noticed that there are lint warnings regarding bad style. I wonder how far this should be taken, but I wanted to suggest that the compiler warns if a guard clause would make the code more readable (IMHO). I think of situations where a complete block has only one expression that is an if, e.g.:

```
  for (i, char) in str.char_indices() {
    if &char == sep {
      // do lots of things
    }
  }
```

It might be easier to read (because you don't need to nest/indent so deep) if you would use a guard clause, especially if the block body is large:

```
  for (i, char) in str.char_indices() {
    if &char != sep { continue }
    // do lots of things
  }
```

I understand that this is highly subjective, but it might be something that makes the code more readable.

**Comment by durka** [comment]
Seems like a matter for [clippy](https://github.com/Manishearth/rust-clippy).

**Comment by Mark-Simulacrum** [comment]
Closing as something that we shouldn't track on rust-lang/rust.
