### ISSUE TITLE
A --static switch for rustc that "just works"

### ISSUE THREAD

**Issue by timkofu** [rust-lang/rust#34833]
Ran with the above switch, rustc will produce a self contained binary that can run on the specified target without dependencies. Whatever size the resulting binary will be will be acceptable.

**Comment by retep998** [comment]
I think this would be better as an RFC that details what exactly will happen on each platform. A self contained binary on Windows is a very different matter than one on Linux which is in turn different from one on Mac OS X.

**Comment by nagisa** [comment]
That’s exactly what the `-musl` targets are for on linux. You will get a fully static binary.

I doubt you can make a fully static binary on windows or [OS X](https://developer.apple.com/library/mac/qa/qa1118/_index.html)¹ though.

**Comment by steveklabnik** [comment]
I echo what both other commentors said; this would need an RFC to spell out exactly what happens on non-Linux platforms, and on Linux today, you can do this with `-musl`. Please pursue one if this is important to you!
