### ISSUE TITLE
compiler error: cannot relate bound region

### ISSUE THREAD

**Issue by benaryorg** [rust-lang/rust#34840]
My [nightli.es](https://nightli.es) build of one of my first experiments with rust just panicked when compiling on travis.
[log.txt is on Pastebin](https://pastebin.com/vV8EGZKw)

The error was that: `error: internal compiler error: ../src/librustc/infer/region_inference/mod.rs:734: cannot relate bound region: '_#0r <= ReEarlyBound(TypeSpace, 0, 'r)`

Everything should be in that logfile, for convenience, [here's the repo](https://github.com/benaryorg/rust-cli_calculator).

**Comment by jonas-schievink** [comment]
See #34780 and #34791

**Comment by steveklabnik** [comment]
I just opened https://github.com/rust-lang/rust/issues/34839 which was also a duplicate of other issues

**Comment by benaryorg** [comment]
Okay, sorry for the duplicate then.
