### ISSUE TITLE
Add fs::read_to_string

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#34857]
Every time I want to load the contents of a file to a `String` I think this same thing: "there should be a fs::read_to_string".

It looks like to me the most convenient way to do this once `?` is stable (which doesn't seem to be near) might be `File::open(path)?.read_to_string()?`, assuming you've got the `Read` trait imported. It's just not as nice.

We as @rust-lang/libs can be more aggressive about identifying and adding simple ergonomic improvements like this.

**Comment by retep998** [comment]
What if we had a `read_to_vec` instead and then you convert that into `String`?

**Comment by Stebalien** [comment]
Alternatively, we could make it generic:

```rust
// Call as `fs::read::<String>("my_file")`
mod fs {
    fn read<T: SomeTrait, P: AsRef<Path>>(path: P) -> T { /* ... */ }
}
```
`SomeTrait` could just be `Write` but that would be a bit inefficient (it would require an intermediate buffer).

**Comment by gkoz** [comment]
An `fs::read_to_string` would encourage trying to slurp files regardless of their size. Going through `Read` you can use `take` (but it won't tell you if the input is too big :disappointed:).

BTW is trying to read the whole file into memory an anti-pattern? Apparently `toml-rs` only parses `&str` but not `T: Read`. If it did take any reader would you still need to `read_to_string` so often?

**Comment by Stebalien** [comment]
@gkoz I think this is one of those "pay for what you use" things. If you want to do things efficiently, manually read the file one chunk at a time; if you just need to read the file into memory and know it isn't malicious (e.g., a config file), you can use the helper function. However, your two caveats should definitely be mentioned in the documentation.

**Comment by brson** [comment]
Libs team discussed and is amenable to a convenience, though the design may need some consideration still. Some concrete points brought up:

* Taking `&mut String` like `Read::read_to_string` probably the wrong choice for the convenience method - should return `String`
* If it doesn't take `&mut String` then the name `read_to_string` may not be right because it doesn't look like `Read::read_to_string`.
* Maybe it should be a method on `Path`.

**Comment by kvark** [comment]
Can we just `impl<R: Read> Into<String> for R {...}`?

**Comment by joshtriplett** [comment]
@kvark That would work for files, but would conflict with instances of Into for other implementations of Read, notably the implementation for String.

**Comment by matklad** [comment]
There's a crate for that: https://github.com/pornel/rust-file

**Comment by binarybana** [comment]
For naming, how about `read_as_str` to indicate that it is allocating a new `String` for you?

**Comment by Mark-Simulacrum** [comment]
The questions that were already brought up by the libs team and general uncertainty I can see about this lead me to believe it requires an RFC. As such, I'm closing -- if someone wants to pursue this, please follow the process outlined here: https://github.com/rust-lang/rfcs#before-creating-an-rfc.
