### ISSUE TITLE
Intern project: Annotated source browser

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#3485]
I was thinking: it'd be very cool to have a tool based on `rustc` that presented an annotated view of the source code, showing:

- the inferred types of local variables, expressions;
- hyperlinks between fn calls and the source text;
- monomorphized versions of generic fns etc specific to a particular call site

This might also be useful in presenting error messages and so forth.

Seems like it would make a great intern project (we should have a tag for that).

**Comment by nick29581** [comment]
I'm tracking DXR implementation in https://github.com/nick29581/rust-dxr

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#611
