### ISSUE TITLE
The Book discusses ownership after vectors, but some text claims otherwise

### ISSUE THREAD

**Issue by Blaisorblade** [rust-lang/rust#34865]
Ownership, borrowing and lifetimes are discussed after vectors and before methods, but the text seems written with another order in mind.

In particular, there's an inaccuracy in https://doc.rust-lang.org/book/ownership.html, which says:

> We'll cover vectors in detail later in this chapter [...]

Should this be removed/rephrased/dealt with some other way? I might try a PR for this (removing the inaccuracy) myself.

**Comment by steveklabnik** [comment]
A PR for this would be great; I would say "in a later chapter" and create a forward reference.
