### ISSUE TITLE
The Book discusses lifetimes in a way that could be improved

### ISSUE THREAD

**Issue by Blaisorblade** [rust-lang/rust#34870]
As mentioned in #34865, ownership, borrowing and lifetimes are discussed after vectors and before methods, but the text seems written with another order in mind.

In particular, more confusingly than #34865, lifetimes are discussed without warning before structs, methods, etc., but the text relies on these concepts—see https://doc.rust-lang.org/book/lifetimes.html#impl-blocks.

Since lifetimes have quite some essential complexity, adding accidental complexity to their introduction seems especially unfortunate. Beyond that, the page on [lifetimes](https://doc.rust-lang.org/book/lifetimes.html) has a few other issues and appears generally harder to follow—while I could follow everything up to https://doc.rust-lang.org/book/references-and-borrowing.html on a first read, this was much more confusing.

I understand that topologically sorting topics in dependency order is hard (because there are often cycles), but part of the discussion of lifetimes could be done assuming only knowledge of functions (and possibly generics). That includes lifetime elision, most of the examples in the "Examples" section, the `'static` lifetime—those can be explained without using structs or methods.

The second big topic in here seems about lifetime-polymorphic structures, but I don't get that yet fully—I guess the text could elaborate more on this point, with some concrete example:

> So why do we need a lifetime here? We need to ensure that any reference to a Foo cannot outlive the reference to an i32 it contains.

**Comment by steveklabnik** [comment]
Yes, some stuff has shifted around over time. More forward references would be good. However, given that I'm currently re-writing the book, I'm not going to be making big changes like this. If someone wants to send in a PR, feel free, but since it's going to be eventually fixed by the new book, I'm giving it a close. Thanks!
