### ISSUE TITLE
Add next_if to Peekable

### ISSUE THREAD

**Issue by W4RH4WK** [rust-lang/rust#34882]
I'd like to propose the addition of a convenience function to `Peekable`. The `next_if` method takes a predicate and returns the next item iff it evaluates to `true` and the iterator has not been exhausted.

Note that the iterator is _not_ advanced if the predicate does not evaluate to `true`, hence this is only available in `Peekable`. Something like this:

``` rust
impl<I: Iterator> Peekable<I> {

    #[inline]
    fn next_if<P>(&mut self, predicate: P) -> Option<Self::Item>
        where P: FnMut(&Self::Item) -> bool
    {
        if self.peek().map(predicate).unwrap_or(false) {
            self.next()
        } else {
            None
        }
    }

}
```

**Comment by dtolnay** [comment]
This is a neat idea! I would prefer for it to go through the [RFC](https://github.com/rust-lang/rfcs/blob/master/libs_changes.md) process if anyone feels strongly enough to spearhead that. There are two important points for the RFC to make:

- There exist reasonably common use cases in real code where they would want to call `next_if`.
- The proposed `next_if` method is the best way for those use cases to solve what they want to do.
