### ISSUE TITLE
Enhance inline assembly to support symbolic names

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/rust#34887]
It would be nice to support [syntax like this](https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html):

``` c
asm ("bsfl %[aMask], %[aIndex]"
    : [aIndex] "=r" (Index)
    : [aMask] "r" (Mask)
    : "cc");
```

Instead of the current position-based `$0`, `$1`, etc.

**Comment by Amanieu** [comment]
This issue does not apply to the new `asm!` ([RFC 2850](https://github.com/rust-lang/rfcs/pull/2850)) which has support for named operands.

The legacy `llvm_asm!` is deprecated and is no longer maintained.
