### ISSUE TITLE
Strange error message on empty asm! macro

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/rust#34881]
The following code produces a strange error:

``` rust
#![feature(asm)]

fn main() { 
   unsafe { asm!() }
}
```

The error is:

```
error: expected expression, found `<eof>`
```

[Playpen link](https://is.gd/tkXVzi)

The error does not contain any file or line information, so it's pretty hard to find the offending line. The error also occurs on stable, where inline assembly isn't even allowed.

**Comment by asdfopiweut** [comment]
It's not about inline assembly imo:
```rust
macro_rules! emit_bug {
// if nothing on input, then return what?
    () => (); // () => (()); <-- This works
}

fn main() {
   emit_bug!() // no semicolon here
}
```

**Comment by phil-opp** [comment]
@asdfopiweut I can reproduce it on my machine and [on playpen](https://is.gd/gEHuKp). The same error: `expected expression, found <eof>`. So I think this issue should also get `A-macros`.

cc @sanxiyn

**Comment by Mark-Simulacrum** [comment]
This is https://github.com/rust-lang/rust/issues/30128, closing in favor of that.
