### ISSUE TITLE
Add missing information on underscore usage to the book

### ISSUE THREAD

**Issue by SplittyDev** [rust-lang/rust#34903]
I noticed that there is virtually no information on the usage of underscores in numeric literals in the book.

The [syntax index][syntax_index] only mentions underscores in the context of pattern matching as `"ignored" pattern binding`, so I suggest adding the other use of underscores to the [syntax index][syntax_index] too.

[syntax_index]: https://doc.rust-lang.org/book/syntax-index.html

**Comment by steveklabnik** [comment]
I would be willing to mentor anyone who wants to help with this issue.

**Comment by abhijeetbhagat** [comment]
I can update.

**Comment by abhijeetbhagat** [comment]
@SplittyDev btw there is text about using underscores in integer literals [here](https://doc.rust-lang.org/reference.html#integer-literals)

**Comment by kyrias** [comment]
Is #34990 enough for this, or do you want something more in-depth?

**Comment by pmatos** [comment]
It seems #34990 was merged, should this be closed?

**Comment by steveklabnik** [comment]
I believe so!
