### ISSUE TITLE
`N.pow(M)` returns zero, does not overflow for unsigned `N` and both `N` and `M` even (sometimes)

### ISSUE THREAD

**Issue by insaneinside** [rust-lang/rust#34913]
Today I learned that eight to the power of eight is zero.  Who'da thunk?

Incorrect:
`2u8.pow(500)` :arrow_right: `0` :x:
`8u8.pow(8)` :arrow_right: `0` :x:
`4u32.pow(1000)` :arrow_right: `0` :x:

Correct:
`8u8.pow(7)` :arrow_right: overflow :white_check_mark: 
`8i8.pow(8)` :arrow_right: overflow :white_check_mark: 
`2u8.pow(9)` :arrow_right: overflow :white_check_mark:

Oddly enough, this one breaks the pattern:
`2u8.pow(10)` :arrow_right: overflow :white_check_mark:

Haven't bothered with further cases; at this point it's probably best to just look at the implementation and see what's going on.

**Comment by eefriedman** [comment]
#28248 was supposed to fix this; looks like it missed the unsigned version?

**Comment by insaneinside** [comment]
[This playpen](https://is.gd/eTh5ie) says that `8u8.pow(8)` is `0` on nightly.

**Comment by eefriedman** [comment]
I meant that #28248 fixed this for pow() on signed integers, but not on unsigned integers; it looks like the implementation is copy-pasted for some reason.

**Comment by porglezomp** [comment]
Could I take a stab at this?

**Comment by eefriedman** [comment]
Sure; feel free to ask if you have questions.

**Comment by porglezomp** [comment]
Is overflow checking off in the libcore tests? It'd be nice to be able to write some standard `#[should_panic]` tests for overflow, but they seem to not panic even on cases that should right now.

**Comment by eefriedman** [comment]
Overflow checking in unit tests (`#[test]`) should reflect whether the whole compiler was built in debug or release mode.

If you need to specify the overflow mode, you can use a separate test which explicitly specifies `-C debug-assertions`, like #28248.

**Comment by Mark-Simulacrum** [comment]
This has since been fixed, in #34942, which it looks like also added a test, so closing.
