### ISSUE TITLE
Pattern referring to nonexistent variant causes ICE on beta.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#34929]
```rust
enum E { V { x: u8 } }

fn main() {
    match (E::V { x: 0 }) {
        E::V_Typoed { .. } => {}
    }
}
```

Produces, on beta:
```rust
error: internal compiler error: ../src/librustc/hir/def.rs:77: path not fully resolved:
PathResolution { base_def: Enum(DefId { krate: 0, node: DefIndex(4) => E }), depth: 1 }
```

On stable and nightly it triggers an appropriate resolution failure error. cc @petrochenkov

**Comment by Aatch** [comment]
Be nice to know what change fixed it again so we can backport it into beta.

**Comment by petrochenkov** [comment]
>Be nice to know what change fixed it again so we can backport it into beta.

It's https://github.com/rust-lang/rust/pull/34365/commits/a397b60ebba531fb4de7e88111e0d489e44c549e, I'll extract the minimal fix for beta.

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rust-lang/rust/pull/34964
