### ISSUE TITLE
Tuple-struct signature in generated docs is misordered.

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#34928]
[In the source](https://github.com/georust/rust-geo/blob/8369162ccc7431c3584d68ae18a5e18387556bae/src/types.rs#L239):

```rust
pub struct GeometryCollection<T>(pub Vec<Geometry<T>>) where T: Float;
```

[In the generated documentation](https://georust.github.io/rust-geo/geo/struct.GeometryCollection.html):

```rust
pub struct GeometryCollection<T> where T: Float(pub Vec<Geometry<T>>);
```

**Comment by Aatch** [comment]
This is because for record structs, the syntax is `struct Foo<T> where T: Bar { /***/ }`, so tuple structs will need some special-casing here.
