### ISSUE TITLE
Improve rustdoc formatting of long function names

### ISSUE THREAD

**Issue by moosingin3space** [rust-lang/rust#34926]
This could integrate with `rustfmt` to make long function names easier to read.

In particular, http://tailhook.github.io/unshare/nix/sys/socket/fn.recvmsg.html
would be easier to read as:

``` rust
pub fn recvmsg<'a, T>(fd: RawFd, 
                      iov: &[IoVec<&mut [u8]>], 
                      cmsg_buffer: Option<&'a mut CmsgSpace<T>>, 
                      flags: SockMessageFlags) 
               -> Result<RecvMsg<'a>>
```

**Comment by steveklabnik** [comment]
I would assume that `rustfmt` integration is the only way to go here; otherwise, we have to re-hash all of its decisions.

**Comment by nagisa** [comment]
What it really should do is just reuse the formatting of the declaration/definition as in source, with some leading spaces removed.

**Comment by QuietMisdreavus** [comment]
It's not quite "run it through rustfmt" or "use the source formatting", but with #36679 (and pending #37190), would this be alleviated?

**Comment by QuietMisdreavus** [comment]
Closing via #41084, which renders fn signatures according to style RFCs.
