### ISSUE TITLE
VecDeque docs should mention in which direction indices go

### ISSUE THREAD

**Issue by rkruppe** [rust-lang/rust#34920]
It's not clear to me whether index 0 is the front or the back of the deque. For example, the `std::collections::vec_deque` module docs only say "It also has O(1) indexing like a vector." and the documentation of `VecDeque::get` only states "Retrieves an element in the VecDeque by index." and the example retrieves the middle element of a three-element deque. From the iteration order, or the example in `swap`, I can infer that it's from the front (and of course I could try it out) but it's would have saved me some time if it was just stated up-front in the relevant locations.

**Comment by GuillaumeGomez** [comment]
Interested in doing it? It is quite an easy change. :)

**Comment by abhijeetbhagat** [comment]
I can work on this.

**Comment by GuillaumeGomez** [comment]
@abhijeetbhagat: Please do.

**Comment by GuillaumeGomez** [comment]
@abhijeetbhagat: I need a PR to review. :stuck_out_tongue:

**Comment by mgattozzi** [comment]
@GuillaumeGomez since this change got merged you might want to close the issue. I just came across this browsing the docs tag thinking it was still open.

**Comment by GuillaumeGomez** [comment]
@mgattozzi: Thanks for notifying me!
