### ISSUE TITLE
Tracking issue for `mpsc::Receiver::try_iter`

### ISSUE THREAD

**Issue by mitchmindtree** [rust-lang/rust#34931]
Tracking issue for the new non-blocking `mpsc::Receiver` iterator API introduced in #34724.

The API is currently gated behind the unstable `receiver_try_iter` feature.

The API includes:
- `std::sync::mpsc::Receiver::try_iter`
- `std::sync::mpsc::TryIter`

cc @alexcrichton

**Comment by mitchmindtree** [comment]
Hey folks, just thought I'd ping this and ask if there's anything I can do to help guide this towards stable? Would love to start using it, but no worries if it's just low on the priority list :+1:

**Comment by Geemili** [comment]
I'd like to know the same thing as mitchmindtree. Is this being guide towards stable?

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

Seems like a nifty API to have!
