### ISSUE TITLE
View Rust Book as single page

### ISSUE THREAD

**Issue by Xazax-hun** [rust-lang/rust#34952]
It would be great to be able to open the rust book as a single page. This way it could be saved using pocket and read from the phone on the go.

**Comment by deepankarsharma** [comment]
+1

**Comment by killercup** [comment]
Have a look at: http://killercup.github.io/trpl-ebook/ (especially the TRPL HTML links)

It's not updated automatically, and not integrated into the build process or anything, though.

**Comment by Xazax-hun** [comment]
This is exactly what I was thinking about :) Is there a plan to make something like this official? (In a sense it is automatically generated for each new release and available from the rust website?) Having EPUB/Mobi distribution is also a good idea! :)

**Comment by steveklabnik** [comment]
rustbook is slated to die at this point, to be replaced by mdbook. I'm gonna give this a close, thanks! This feature should be moved upstream.
