### ISSUE TITLE
Special case behavior of `#![cfg(..)]` at crate root needs documenting

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#34968]
Spawned off of https://github.com/rust-lang/rust/issues/34932#issuecomment-234397781

If you put the inner attribute `#![cfg(..)]` at a crate root, this (apparently) causes an empty crate to be generated. I.e., it is as if the crate itself still exists, but all of its contents have disappeared.

This is slightly different than the behavior of `#![cfg(..)]` elsewhere (e.g. in a `mod` item), where such an inner attribute will cause the whole item to be omitted from the AST, rather than just causing the contents of the item to be omitted.

I don't see any mention of this corner case in the Rust documentation for Conditional Compilation, here: https://doc.rust-lang.org/book/conditional-compilation.html

**Comment by QuietMisdreavus** [comment]
Since the second edition of the book doesn't have a dedicated section to conditional compilation, I'm moving the issue to the reference repo: https://github.com/rust-lang-nursery/reference/issues/103

**Comment by steveklabnik** [comment]
This needs to be documented in the reference, so moving over to https://github.com/rust-lang-nursery/reference/issues/105
