### ISSUE TITLE
Enums not being stored as compactly as possible

### ISSUE THREAD

**Issue by sourtin** [rust-lang/rust#34961]
I noticed that some enums seem to not be stored as compactly as they could be considering they should equate to unions. The two enums below, `Foo` and `Bar`, consist of two variants each. Each variant is <= 8 bytes, so the total size should fit within (8+tag) bytes, and they should take up the same space as each other. It seems however that the data is being stored adjacently rather than overlapping, as `Foo` takes up 16 bytes and `Bar` takes up 12 bytes. Is this a bug or is there an alternative way to obtain more compact data structures? (I suppose I could manually tag a struct and use `transmute` if necessary.)

```rust
enum Foo {
    Integer(i64),
    Rational(i32, u32)
}
println!("{:?}", std::mem::size_of::<Foo>());
// => 16

enum Bar {
    Integer(i32),
    Rational(i32, u32)
}
println!("{:?}", std::mem::size_of::<Bar>());
// => 12
```

**Comment by jonas-schievink** [comment]
I believe the tag is stored first, followed by padding such that the `i64` or `i32` is aligned to 4 Bytes, which is why the tag seems to take up 8/4 Bytes.

**Comment by sourtin** [comment]
Ah ok, that makes sense. Thanks!

**Comment by jonas-schievink** [comment]
In case you're interested, here's an issue about improving the layout optimizations the compiler does: rust-lang/rfcs#1230
