### ISSUE TITLE
The check against LLVM's data-layout needs to be relaxed/updated

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#34960]
Discovered in #34743, LLVM's data layouts are changing over time. If we assert that our own data layout agrees with LLVM's then if we change to a newer LLVM we break compatibility with older LLVMs. It looks like the change to the data layout was backwards compatible, I think, so we probably just need a different check here.

cc @eddyb

**Comment by eddyb** [comment]
Previous thoughts at #33446, but that never materialized.

**Comment by Mark-Simulacrum** [comment]
Yeah, I'm going to close in favor of #33446 and leave a comment there.
