### ISSUE TITLE
[LLVM] Use the LLVMInitializeAllTargets* functions

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#34962]
LLVM has the functions to initialize all supported targets already. We should get rid of [this] monstrosity and use the functions instead.

The problem is that these functions are currently `static inline` and thus have no symbol of their own. In order to be able to use them in rustc, we need to create a binding for it.

For now the migration would look something like this:

* [ ] Implement `RustLLVMInitializeAll{Targets,TargetInfos,TargetMCs,AsmPrinters,AsmParsers}` in rust_llvm. These would call the `static inline` counterparts directly.
* [ ] `initialize_available_targets` gets changed to call newly created wrappers;
* [ ] Make sure our distribution LLVM is only compiled with the targets that we want to support (x86, ARM, Aarch64, MIPS, PNaCl); 

[this]: https://github.com/rust-lang/rust/blob/75886537858530447051b9c1ef595c4ba59017c5/src/librustc_llvm/lib.rs#L2369

cc @rust-lang/compiler 

I also would consider this as an `E-easy` issue. The general direction for fixing this issue are listed above and this issue would help to understand how LLVM initialisation works and how rustc ties into the LLVM.

---

Once something like [this patch](https://reviews.llvm.org/D22736) lands and gets into all LLVM versions we support we could then remove the wrapper altogether.

**Comment by eddyb** [comment]
Do we get any benefits from this, if we still support older LLVM versions? cc @alexcrichton @badboy

**Comment by nagisa** [comment]
Primary benefit is an ability to target `rustc` at stuff other than the list of targets we currently hardcode if LLVM is not distributed by us (linked dynamically by distro or something).

**Comment by nagisa** [comment]
Secondary benefit is that it would not force the dynamically linked LLVM to actually provide all those targets (i.e. if some distro distributes LLVM which can only do some of the targets we currently hardcode).

Of course that would introduce an error-case for [this call](https://github.com/rust-lang/rust/blob/7ed6068d3e528167e95b684d086a39e099fd26f1/src/librustc_trans/back/write.rs#L215) which would need to be checked for and reported appropriately.

**Comment by nagisa** [comment]
Apparently the `LLVMInitializeAllTarget*` stuff is all `static inline`, which is why I never noticed them before.
