### ISSUE TITLE
Warn or abort if -Zincremental is used without -Zorbit

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#34973]
Because of #34151, incremental compilation cannot work reliably without MIR-trans. We should make sure that we can't run into this accidentally.

cc @nikomatsakis

**Comment by michaelwoerister** [comment]
I added this to the milestone, since it's easy to do and can only lead to trouble once people try out the alpha.

**Comment by nikomatsakis** [comment]
Maybe we should just make `-Z incremental` imply `-Z orbit`? In any case, I just spent a bit of time debugging a case where I forgot to use -Z orbit =)

**Comment by nikomatsakis** [comment]
Maybe we should just make `-Z incremental` imply `-Z orbit` or something like that?
