### ISSUE TITLE
libbacktrace symbols are exposed from libstd

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#34984]
We should compile libbacktrace I... think with `-fvisibility=hidden`, but I don't think that we are. This causes the symbols to be exported when they shouldn't be:

``` rust
$ echo '#[no_mangle] pub extern fn foo() { panic!() }' > foo.rs
$ echo 'extern void foo(); int main() { foo(); return 0; }' > foo.c
$ rustc foo.rs --crate-type staticlib -C lto
$ gcc foo.c libfoo.a
$ nm -g ./a.out | grep backtrace_
0000000000512a7b T backtrace_alloc
000000000051131b T backtrace_close
0000000000511365 T backtrace_create_state
00000000005181c4 T backtrace_dwarf_add
0000000000512c5c T backtrace_free
00000000005128dd T backtrace_get_view
0000000000512772 T backtrace_initialize
0000000000511277 T backtrace_open
0000000000511192 T backtrace_pcinfo
0000000000518320 T backtrace_qsort
00000000005129d7 T backtrace_release_view
0000000000511202 T backtrace_syminfo
0000000000512eb7 T backtrace_vector_finish
0000000000512d12 T backtrace_vector_grow
0000000000512f01 T backtrace_vector_release
```

cc https://bugzilla.mozilla.org/show_bug.cgi?id=1288173
cc @froydnj

**Comment by alexcrichton** [comment]
This should be a relatively easy bug to tackle if anyone's interested, but I'm not convinced of the solution so I'm not gonna tag E-easy just yet. If you've got a Linux machine though it'd be great to play around on!

**Comment by alexcrichton** [comment]
For reference we compile libbacktrace in two places currently:

* [The makefiles](https://github.com/rust-lang/rust/blob/master/mk/rt.mk#L635-L676)
* [libstd's build script](https://github.com/rust-lang/rust/blob/master/src/libstd/build.rs#L63)

Both will need to be modified with the same solution once we figure it out.

**Comment by nxnfufunezn** [comment]
I would like to give it a shot..

**Comment by alexcrichton** [comment]
Sure thing, thanks @nxnfufunezn! If you need any help feel free to ping me here or on IRC

**Comment by munyari** [comment]
If @nxnfufunezn isn't working on this, I'd like to take it on

**Comment by nxnfufunezn** [comment]
@munyari sure..
