### ISSUE TITLE
atomic-lock-free test doesn't account for LLVM support

### ISSUE THREAD

**Issue by cuviper** [rust-lang/rust#35023]
In `run-make/atomic-lock-free/Makefile`, it attempts to build its script for many different architectures.  However, when using an external LLVM build, it may not have all architectures available, so the test will fail despite anything Rust could do.  For example, on Fedora 24 I have:

```
$ llvm-config --targets-built
X86 AMDGPU PowerPC NVPTX SystemZ AArch64 ARM BPF CppBackend
```

In particular this doesn't have "Mips", so the `mips` and `mipsel` targets will fail in `atomic-lock-free`.  It would be nicer if this test only attempted architectures that are included in one's build of LLVM.

**Comment by nagisa** [comment]
See https://github.com/rust-lang/rust/issues/34962 (this would be a first step to fix the issue).

Rustc currently *requires* LLVM to support `x86`, `aarch64`, `arm`, `mips`, `powerpc` and `nacl` targets. You cannot omit any of these unless you patch rustc code in various places.

**Comment by sanxiyn** [comment]
We "sort of" support LLVM configured with different targets since #27937. It is not the case we don't have any code to support that use case.

**Comment by cuviper** [comment]
Thanks for the links.

@nagisa Where else would you expect problems?  I found the entire "make check" was fine except for this one `atomic-lock-free` test.

Anyway, Fedora's LLVM maintainers agreed to add "Mips" next time they rebuild, so I guess this isn't a huge issue for me.  But if Rust ever decides to add another "required" target, it would be good to understand how urgent that is to comply.
