### ISSUE TITLE
Panic on a simple type error

### ISSUE THREAD

**Issue by pijul** [rust-lang/rust#35024]
Rust 1.9.0 panics on the following (wrong) code:

```
use std::io::BufRead;
fn main() {
    let x = b"blabla blibli";
    let s = &x[..];
    let mut v = Vec::new();
    s.read_line(&mut v)
}
```

(but works fine with `String::new()` instead of `Vec::new()`).

**Comment by TimNN** [comment]
I'm pretty sure that this was fixed by #33852 and should work fine in nightly.

**Comment by pijul** [comment]
I have no way to run nightly on my machine, feel free to close if fixed.

**Comment by oli-obk** [comment]
jup, works fine on nightly: https://is.gd/UeG59L

**Comment by pijul** [comment]
Ok, sorry for the noise.
