### ISSUE TITLE
diagnostics: The `compile-fail/lifetime-inference-give-expl-lifetime-param.rs` test is unreliable

### ISSUE THREAD

**Issue by jseyfried** [rust-lang/rust#35038]
The "consider using an explicit lifetime parameter" notes depend on the ids of interned strings, so they can differ between platforms after #34856.

**Comment by jseyfried** [comment]
cc @nikomatsakis

**Comment by steveklabnik** [comment]
Triage: it seems that this file no longer exists? Any idea where this test is now?

**Comment by Mark-Simulacrum** [comment]
We removed this suggestion entirely in a2735c02493d816835a19249dd258e0c678530d0 it seems so closing out (found by doing `git log -- src/test/compile-fail/lifetime-inference-give-expl-lifetime-param.rs`).
