### ISSUE TITLE
Tracking issue for `no_panic_abs` stabilization

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#35057]
See https://github.com/rust-lang/rfcs/pull/1678 and https://github.com/rust-lang/rust/pull/35058

**Comment by sfackler** [comment]
The libs team discussed these methods and are placing them in a final comment period to **stabilize**.

**Comment by alexcrichton** [comment]
The libs team discussed this at triage yesterday and the conclusion was to **stabilize**
