### ISSUE TITLE
UnsafeCell::into_inner should not be unsafe

### ISSUE THREAD

**Issue by ubsan** [rust-lang/rust#35067]
It's been unsafe since 2014 when it was called `unwrap`. Nobody thought about it, I guess, but it shouldn't be unsafe.

**Comment by retep998** [comment]
For reference the PR which added it is https://github.com/rust-lang/rust/pull/12686

**Comment by durka** [comment]
Someone thought about it enough to [document the rationale](https://github.com/rust-lang/rust/blob/master/src/libcore/cell.rs#L895):

> This function is unsafe because this thread or another thread may currently be inspecting the inner value.

Has something changed to make this consideration unnecessary or do you have an explanation of why the reasoning is faulty?

**Comment by retep998** [comment]
@durka Because the function takes `self` so by definition it must be the owner of the value so there can be no other viewers, either from this thread or another thread.

**Comment by ubsan** [comment]
Although this isn't backwards-compatible

```rust
let x: unsafe fn(_) -> _ = UnsafeCell::<u32>::into_inner;
```

there is some prior art of going unsafe -> safe: `std::mem::forget` (although, that was pre-1.0)

**Comment by durka** [comment]
That's weird, it seems like you ought to be able to assign a safe fn to an
unsafe fn pointer.

**Comment by nikomatsakis** [comment]
We removed the subtyping relation at some point; it does seem like a coercion would be (probably) ok, but that would still not be (strictly) backwards compatible.

**Comment by nikomatsakis** [comment]
(I tend to agree that `into_inner` could be safe, though, and I highly doubt any existing crates would actually break due to this change.)

**Comment by retep998** [comment]
We could always do a crater run just to be absolutely sure nobody is turning `UnsafeCell::into_inner` into a function pointer.

**Comment by cyplo** [comment]
HI ! Any news on this one ?

**Comment by nikomatsakis** [comment]
No change that I know of.

**Comment by cramertj** [comment]
FWIW the relevant coercion was added in https://github.com/rust-lang/rust/pull/37389.

**Comment by asomers** [comment]
This change is breaking my crate.  If I add the `unsafe` then it will work for older compilers.  If I remove the `unsafe` then it will work for newer compilers.  Is there a conditional compilation attribute for compiler version?  I can't find one.

**Comment by cramertj** [comment]
@asomers Use `#[allow(unused_unsafe)] unsafe { ... }`
