### ISSUE TITLE
Tracking issue for the functions for debug escaping `char_escape_debug`

### ISSUE THREAD

**Issue by tbu-** [rust-lang/rust#35068]
`std::char::escape_debug`, `std::char::EscapeDebug`.

**Comment by nikonthethird** [comment]
I hope this is the correct spot to mention that all examples of std::char::escape_debug use std::char::escape_default.

https://doc.rust-lang.org/std/primitive.char.html#method.escape_debug

**Comment by Mark-Simulacrum** [comment]
The above has been fixed; the function is correctly documented. Nominating for libs team discussion as to stabilization, I don't think we're going to get much information out of usage since this is such a niche API. I'm personally not certain I like the name: `escape_debug` seems odd to me, it's not really anything related to debugging I think.

cc @rust-lang/libs

**Comment by tbu-** [comment]
`debug` refers to the fact that it is used for the `Debug` implementation of `String` and `&str`.

I would prefer to call these functions just `escape` (best would be `escape_default`, but that one is taken). Could we maybe permanently deprecate `escape_default` in favor of something like `escape_nonascii` to make it clear that escaping all non-ASCII code points has nothing to do with "default"?

**Comment by sfackler** [comment]
@rfcbot fcp merge

**Comment by dtolnay** [comment]
@rfcbot reviewed

**Comment by BurntSushi** [comment]
Sorry, but I've lost context on this change and this issue doesn't appear to link to anything. What is the purpose of this new method? Is it just a rename?

**Comment by tbu-** [comment]
The function escapes characters the way the `Debug` implementation for  `str` and `char` does.

**Comment by dtolnay** [comment]
If we are doing this, I would also like to have a plan for #27791 which includes [`<str>::escape_debug`](https://doc.rust-lang.org/std/primitive.str.html#method.escape_debug). Looks like there were concerns about consistency between char's and str's escape_default in https://github.com/rust-lang/rust/issues/27791#issuecomment-172035085.

@rfcbot concern str

**Comment by brson** [comment]
Please change this sentence in the docs: "This will escape the characters similar to the Debug implementations of str or char." I assume this is not just similar, it is the implementation of 'Debug'.

**Comment by tbu-** [comment]
Currently. What if we wanted to change either of these but not the other? `escape_default` couldn't be changed because the documentation was too concrete.

**Comment by tbu-** [comment]
Maybe we could state that it does the same as the `Debug` implementation for `str`.

**Comment by ariasuni** [comment]
The only difference between `escape_default` and `escape_debug` seems to be that the first uses the range `'\x20' ... '\x7e'` to determine printable characters (i.e. characters which will not be escaped) where the second uses `is_printable()` (why not the actual code used for `Debug` then?).

**Comment by tbu-** [comment]
@ariasuni It's the other way around, the `Debug` implementation of `char` and `str` use `escape_debug`.

**Comment by ariasuni** [comment]
Oh, that explains a lot. So what does `is_printable()` is supposed to do?

**Comment by tbu-** [comment]
It's supposed to decide whether a codepoint is printed directly in the `Debug` output (e.g. if it's a character from some alphabet), or whether it should be escaped (e.g. if it is a control code point).

```
is_printable('a')
is_printable('α')
!is_printable('\n')
!is_printable('\0')
```

**Comment by ariasuni** [comment]
I get it, I’m wondering on what properties/logic this choice is based. Reading the (undocumented) source code is not helpful… I just understand that it’s based on the Unicode character class (also it probably should be updated for Unicode 10.0.0).

**Comment by tbu-** [comment]
See the original pull request: #34485.

**Comment by dtolnay** [comment]
@rfcbot resolved str

`char::escape_debug` is good to go. We will address the consistency question as part of #27791.

**Comment by leo60228** [comment]
I'm not sure of a better place to put this. Is this function guaranteed so that `format!("\"{}\"", x.escape_debug())` returns valid Rust code that represents a value equal to `x`?
