### ISSUE TITLE
Tracking issue for RefCell::{try_borrow, try_borrow_mut}

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#35070]
Tracking issue for https://github.com/rust-lang/rfcs/pull/1660

Stabilization of these functions should be contingent on confirming the conventions around naming of this style of methods.

Another idea I've had recently is we perhaps want to connect the lifetime of the `RefCell` to the error type as well, but we can always do that later as well.

**Comment by SimonSapin** [comment]
The error types do have a lifetime parameter now. Can we go to FCP and bikeshed the naming in that period? (I think the naming is fine.)

**Comment by aturon** [comment]
This nomination didn't come in before our meeting yesterday, but I'd be fine adding it.

**Proposing FCP with inclination to stabilize**.

Libs team, please signal your agreement below or leave comments with concerns:

- [ ] @alexcrichton 
- [ ] @aturon
- [ ] @brson 
- [ ] @BurntSushi 
- [ ] @Kimundi
- [ ] @sfackler

**Comment by brson** [comment]
It looks like I'm being asked to sign off on something before the design is complete ("Can we go to FCP and bikeshed the naming in that period?"). I don't agree to that.

**Comment by SimonSapin** [comment]
@brson As I see it, the design is complete and there was just some mild reservation about the naming in the RFC discussion. It’s been a month since this was implemented and merged, and two months since the RFC was first submitted. I don’t think new information is likely to appear if we wait more.

**Comment by brson** [comment]
@SimonSapin understood, but I think this is a bug in the new process. Me checking that box is _my final decision_ as a member of the libs team, and the design _is not final_.

**Comment by brson** [comment]
Per discussion with @aturon I've checked the box and we'll discuss the process mechanics later.

**Comment by alexcrichton** [comment]
:bell: The library team has decided to move this into **final comment period** for stabilization :bell:

**Comment by alexcrichton** [comment]
The libs team discussed this during triage yesterday and the conclusion was to **stabilize**

We also figured that the type/lifetime parameter on the errors returned aren't worth it, so they'll get removed.
