### ISSUE TITLE
`Trait::method` and `<_ as Trait>::method` are treated differently by type checker

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#35096]
```
trait Trait<Param = u8> {
    fn method() {}
}

Trait::method // (1) Param is substituted as a fresh inference variable and inferred
<_ as Trait>::method // (2) Default type parameter (u8) is substituted, Param is not inferred
```

Behavior (2) is pretty unusual, in all other cases type parameters in expression/pattern paths are inferred.
It also prevents desugaring all associated paths into the `<TYPE as Option<TRAIT>>::ASSOC_ITEM` form because some extra bookkeeping is required to discern between `Trait::method` and `<_ as Trait>::method`.

What is the history and motivation behind this behavior? (It was introduced in https://github.com/rust-lang/rust/commit/85ba8178e2e995c0da6eb9268612baca8a6ba2e3)
cc @eddyb @nikomatsakis 

Unfortunately, fixing this causes some breakage, see the branch here https://github.com/petrochenkov/rust/tree/ufcs-subst

**Comment by eddyb** [comment]
@petrochenkov The difference is that `<_ as Trait>` puts `Trait` in a type context where defaults are *required*.
For the purposes of fully qualified paths, `Trait::method` is *not* a projection from a type.
`T::A` should be replaced with `<T>::A` unless `T::A` was resolved by name resolution (which is the case for `Trait::method`).

More generally, given `a::b::c::X::Y::Z` and a resolution depth of 2, `<<a::b::c::X>::Y>::Z` is the desugared form.

**Comment by petrochenkov** [comment]
><_ as Trait> puts Trait in a type context

I don't really see the difference between `Trait`s in `Trait::method` and in `<... as Trait>::method` and why the second one is in a different context. They are resolved and type checked identically otherwise.

**Comment by petrochenkov** [comment]
>More generally, given `a::b::c::X::Y::Z` and a resolution depth of 2, `<<a::b::c::X>::Y>::Z` is the desugared form.

Oh, by the way for me the motivation in this desugaring is basically to have additional `NodeId`s for `X`, `Y` and `Z` to be able to keep separate resolutions/types/etc for them in tables. Do you have anything else about it in mind?

**Comment by eddyb** [comment]
@petrochenkov Only expression paths have the relaxed behavior, and within `<...>` there are only type paths. Think of it the same way that `Box<Trait>` doesn't infer the type parameter of `Trait`.

*However*, there is a bigger problem here: `T::A` is more relaxed than `<T>::A`, which makes that desugaring problematic, *unless* `_` parameters are injected:

```rust
struct Foo<T = ()>(T);

impl<T> Foo<T> {
    fn bar() {}
}

fn main() {
    Foo::bar();
    // Equivalent to:
    <Foo<_>>::bar();
}
```

As for the motivation, having them as separate entries in the tables and simplifying the type-level resolution algorithm is indeed my motivation.

Oh, and `<TYPE as Option<TRAIT>>::ASSOC_ITEM` is not exactly accurate.
`<T as Trait>::A` is technically `Trait::<Self=T>::A`, handled by name resolution, *unlike* `T::A` that is `<T>::A`, i.e. type-dependent resolution.

**Comment by petrochenkov** [comment]
> Adding angle brackets to `NonTrait::assoc_item` can change semantics.

Sigh, this is unfortunate. Not even in technical sense (the desugaring is complicated), but in general, as a subtle exception to a simple rule that no one is aware about until it attacks.

**Comment by eddyb** [comment]
@petrochenkov The rule is that if you have a path expression, *everything* in it gets inferred, whereas if you have a path type, required parameters must be provided and defaults are used.

The misleading simple rule is the desugaring one, not the difference between expression/type paths, but it's not obvious how they interact, I suppose.

**Comment by eddyb** [comment]
Nominated for discussion by @rust-lang/lang.

**Comment by petrochenkov** [comment]
>The rule is that if you have a path expression, everything in it gets inferred, whereas if you have a path type, required parameters must be provided and defaults are used.

Yep, I realize that, this is a simple and self-contained rule. It's 1) the border between the expression and type contexts is positioned somewhat unexpectedly and 2) given that border the consequences like `Type::method != <Type>::method` may be non-obviousю

**Comment by eddyb** [comment]
Discussed in @rust-lang/lang meeting. Consensus was that this has the intended semantics.
One interesting point by @pnkfelix was that we might eventually want to add `Foo<..>` which would expand into placeholders for all declared lifetime and type parameters.

@petrochenkov Do you think you could use a HIR-only `<..>` as the "bookkeeping" method?
One advantage is that expression paths and type paths can then be unified in semantics at the HIR level.
`T::A` with a depth of 1 becomes `<T>::A` in a type context and `<T<..>>::A<..>` in an expression context.
`Trait::method` can desugar to  `<_ as Trait<..>>::method<..>`, to keep `Self` always explicit.

**Comment by petrochenkov** [comment]
Sounds like a plan.
Closing this as not-an-issue then.

**Comment by eddyb** [comment]
@petrochenkov So I have a branch where I needed one node for each element of an associated path.
I ended up adding `<..>` at the HIR level, but it shows up in error messages:
```rust
`Tr::A::f<u8>` does not name a unit variant, unit struct or a constant [E0533]
// ^ before / after v
`<<S as Tr>::A<..>>::f::<u8>` does not name a unit variant, unit struct or a constant [E0533]
```
Should I leave it like that, not display `<..>` in pretty-printing, or do something else?

**Comment by petrochenkov** [comment]
It looks like `..` is better omitted.
It cannot be written in source code, so `Second::<..>` can only originate from `Second`, and paths in error messages should be close to what the user wrote.
Drawback: omitting `..` makes paths mean something slightly incorrect in type context. I think it's tolerable, brevity and proximity to the source seem to be more important in this context.
