### ISSUE TITLE
EncodeUtf8 iterator implementation results in bad code

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#35099]
Provided https://github.com/rust-lang/rust/pull/35098 (more precisely https://github.com/rust-lang/rust/pull/35098/commits/f729e1753d0a6cf2c595caaa07374b09bcb50fbf commit) lands, iterating `x.encode_utf8().as_slice()` results in considerably better code compared to `x.encode_utf8()`.

One major problem with the `EncodeUtf8` iterator is the fact that it uses checked indexing, despite it being obvious this iterator cannot index out-of-bounds. However, even if that problem is fixed, noticeably worse code is still generated, but I couldn’t exactly pinpoint why.

cc @alexcrichton https://github.com/rust-lang/rust/pull/32204

**Comment by eefriedman** [comment]
Maybe it's a problem that EncodeUtf8::next() isn't marked `#[inline]`?  Or are you not running into that issue because you're writing code inside libstd?

**Comment by nagisa** [comment]
Yes, I was writing code inside libstd, so the method got inlined regardless of attribute (or lack of it thereof).

**Comment by eefriedman** [comment]
I looked into this a bit; there are a few related problems, but I think the biggest problem is that LLVM can't really figure out that accesses to EncodeUtf8.buf don't alias accesses to EncodeUtf8.pos, which prevents a lot of simplifications.  There's been some discussion of this on the LLVM mailing lists; see http://lists.llvm.org/pipermail/llvm-dev/2016-July/102867.html and http://lists.llvm.org/pipermail/llvm-dev/2016-July/102472.html .

**Comment by nagisa** [comment]
Not relevant anymore as a different approach is now used, that generates pretty nice code.
