### ISSUE TITLE
Add Mutex methods that ignore poisoning

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#35092]
Scenarios where one wants to ignore poisoning happen. Having to type extra incantations to ignore the poisoning can be quite unpleasant, makes Rust less ergonomic, and is a source of complaints. Let's please consider adding conveniences for cases where poisoning is not desired, either additional methods, or new types that do not poison.

**Comment by brson** [comment]
For reference, this is what you type when you need to ignore poisoning: `mutex.lock().unwrap_or_else(|e| e.into_inner())`

**Comment by brson** [comment]
Would be worthwhile to survey existing code bases to see how common it is to ignore poisoning.

**Comment by sfackler** [comment]
I made a wrapper crate over the standard library types to do this: https://crates.io/crates/antidote

I have needed to poison a data structure exactly once in my career (Rust and not-Rust).

**Comment by alexcrichton** [comment]
The libs team discussed this yesterday and the conclusion was that a change like this would require an RFC, so as a result we're going to close this in favor of a future incarnation in the rust-lang/rfcs repo.

**Comment by Ericson2314** [comment]
Relatedly, I'd like `PoisonError` to turn into an empty type with panic=abort.

**Comment by glaebhoerl** [comment]
@Ericson2314 Wouldn't that break source compatibility? (Am I right to assume that panic=abort is not supposed to?)

**Comment by Ericson2314** [comment]
@glaebhoerl sorry this would be a scenario thing where one can be portable/parametric wrt panic strategy, or rely on one not working with the other.
