### ISSUE TITLE
Stdout does panic in pipe

### ISSUE THREAD

**Issue by gemmarx** [rust-lang/rust#35108]
In a 64-bit Linux box, the code below fails to write, and dies with a panic message only in a pipeline.
```rust
fn main() {
    use std::io::Write;

    let buf = "\n".as_bytes();
    for _ in 1..2000 {
        std::io::stdout().write(buf).unwrap();
    }
}
```
```bash
#This is ok.
$ rustc main.rs
$ ./main

#However, this calls a panic.
$ ./main | head -0
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 32, message: "Broken pipe" } }', ../src/libcore/result.rs:788
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

On the other hand, following two codes work with no trouble.
```rust
fn main() {
    use std::io::Write;

    let buf = "\n".as_bytes();
    for _ in 1..100 {
        std::io::stdout().write(buf).unwrap();
    }
}
```

```rust
fn main() {
    use libc::{c_int, size_t, c_void};

    let fd: c_int = 1;
    let buf = "\n".as_bytes();
    for _ in 1..2000 { unsafe {
        libc::write(fd,
                    buf.as_ptr() as *const c_void,
                    buf.len() as size_t);
    } }
}
```

What's happened?
It seems to be a buggy behaviour.
( rustc version is 1.12.0-nightly (feeca9457 2016-07-26) )

**Comment by nagisa** [comment]
As the `message: "Broken pipe"` implies, the stuff you’re piping into exits before your code finishes writing all your newlines.

The 2nd program likely finishes because it manages to write all of its stuff before `head -0` exits. The 3rd program has different behaviour from the 1st or 2nd programs – it does not check the return code of `libc::write`, essentially ignoring the errors.

It seems to me that its working as it should be working.

**Comment by gemmarx** [comment]
Oh, thank you very much. I get it.

It sounds naatural to handle exceptions neatly when bytes to write are to be greater than the buffer size of pipeline (maybe 1024K?).

This means that print! or write! macro family is not good to use in pipeline because they cannot catch errors, right?

**Comment by nagisa** [comment]
`write!` allows you to handle the errors just fine (it returns a `Result`). `print!` does not.

**Comment by gemmarx** [comment]
That reminds me!

Thank you, nagisa-san.
This issue shall be close tomorrow.

**Comment by gemmarx** [comment]
In my short research, "wc" command in [coreutils projict](https://github.com/uutils/coreutils) and [exa](https://github.com/ogham/exa) at least have this panic problem.
They have lost some values as a filter command.
There could be more appropriate affordance for Stdout.
