### ISSUE TITLE
Can't build from source

### ISSUE THREAD

**Issue by yongqli** [rust-lang/rust#35105]
I'm trying to build from a git checkout on OSX but I get the error:

    checking for stdbool.h that conforms to C99... In file included from /Users/yongqli/projects/rust/src/rustllvm/ExecutionEngineWrapper.cpp:11:
    In file included from /Users/yongqli/projects/rust/src/rustllvm/rustllvm.h:11:
    In file included from //Users//yongqli//projects//rust//src//llvm//include/llvm/IR/IRBuilder.h:22:
    In file included from //Users//yongqli//projects//rust//src//llvm//include/llvm/IR/ConstantFolder.h:21:
    In file included from //Users//yongqli//projects//rust//src//llvm//include/llvm/IR/InstrTypes.h:21:
    //Users//yongqli//projects//rust//src//llvm//include/llvm/IR/Attributes.h:69:14: fatal error: 'llvm/IR/Attributes.inc' file not found
        #include "llvm/IR/Attributes.inc"
                 ^

**Comment by Aatch** [comment]
Could you provide some more information? What commands did you use, etc.

**Comment by yongqli** [comment]
Looks like there were some left over files that `git clean -f` didn't catch.
