### ISSUE TITLE
Extern statics can be accessed in safe Rust

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#35112]
This code crashes:
```rust
#[no_mangle] pub static X: usize = 0;
mod test {
    extern {
        pub static X: &'static u32;
    }
}
fn main() {
     println!("{}", X);
     println!("{}", *test::X);
}
```
@ubsan wrote this code on irc.
https://botbot.me/mozilla/rust-internals/2016-07-28/?msg=70411962&page=5

**Comment by ubsan** [comment]
I'd argue the solution is to require `unsafe` when accessing statics that are extern, *or* that we do `unsafe extern` when writing an extern block that includes statics.

**Comment by Stebalien** [comment]
Why do we even allow extern *references*? Shouldn't this be `pub static X: *const u32`?

**Comment by petrochenkov** [comment]
It's pretty horrifying that `unsafe` isn't required to access foreign statics.
Given that you can write a `static` with any Rust type with any invariants (`improper_ctypes` is not a hard rule)
```
extern "C" {
    static STATIC: Vec<u8>;
}

fn main() {
    println!("{}", STATIC[0]);
}
```
and the C side can contain arbitrary bytes under the name `STATIC`.

**Comment by steveklabnik** [comment]
nominating due to unsoundness

**Comment by ubsan** [comment]
@petrochenkov technically, the Rust side can also contain arbitrary bytes under the name `STATIC`.

**Comment by retep998** [comment]
I'd be okay with extern statics requiring unsafe to access. Would probably need a very long deprecation/warning period however.

**Comment by ubsan** [comment]
@retep998 it's unsound, therefore, it doesn't need that long of a deprecation period, in my opinion. Maybe two cycles.

**Comment by rkruppe** [comment]
Since this would presumably go through a forward compatibility lint, it could be made `deny`-by-default soon-ish. A hard error should perhaps take longer &mdash; just because it's unsound doesn't mean it won't affect many crates.

**Comment by ubsan** [comment]
@rkruppe makes sense.

**Comment by retep998** [comment]
Probably one Rust release warn by default, and then at least one deny by default and keeping it deny by default for a while until crater says it is mostly okay.

**Comment by nikomatsakis** [comment]
Agreed, it seems very clear that accessing an extern static should be unsafe -- just as calling an extern fn is unsafe. Just a plain oversight. There are many ways for this to go wrong:

- the C code could mutate the static
- the type might not match what the C type is
- etc

So we should add a forwards-compatibility lint and make it unsafe to access an extern static. I agree we'll want to have a (very) long deprecation period.
