### ISSUE TITLE
Documentation is not entirely clear what `write!` returns

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#35110]
Looking at [`write!`](https://doc.rust-lang.org/stable/std/macro.write!.html) documentation page, the only thing you can figure out is that `write!` does return something and “something” has a `unwrap()` method.

**Comment by TimNN** [comment]
I'm pretty sure that write is not even guaranteed to return anything with an `unwrap()` method...

Write basically calls whatever `write_fmt` method on `$dst` is in scope (and makes *no* other guarantees).

**Comment by nagisa** [comment]
It, then, should document *that*.

**Comment by retep998** [comment]
Yay duck typing!

**Comment by steveklabnik** [comment]
part of https://github.com/rust-lang/rust/issues/29381

**Comment by steveklabnik** [comment]
I would be willing to work with anyone who wanted to fix this issue.

**Comment by TimNN** [comment]
Some related issues regarding that macro & it's documentation: #21615, #28049

**Comment by cengizIO** [comment]
@steveklabnik Hello! I can work on this.

**Comment by steveklabnik** [comment]
@cengizIO great! Do you need any help from me?

**Comment by cengizIO** [comment]
@steveklabnik Hello. Not currently. I'll come up with a PR and ask your comments on it tomorrow or the next day.

Thanks for keeping an eye!
