### ISSUE TITLE
Audit metadata dep-graph edges

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#35111]
When we record the metadata, we create a new task for the metadata pertaining to each item. The incoming edges to this task are then used to compute the hash of the metadata. This is all good, but there are a number of cases of "information leaks" that will lead to missing edges.

One example:

```rust
fn encode_info_for_method<'a, 'tcx>(ecx: &EncodeContext<'a, 'tcx>,
                                    rbml_w: &mut Encoder,
                                    index: &mut CrateIndex<'a, 'tcx>,
                                    m: &ty::Method<'tcx>,
                                    is_default_impl: bool,
                                    parent_id: NodeId,
                                    impl_item_opt: Option<&hir::ImplItem>) {

    debug!("encode_info_for_method: {:?} {:?}", m.def_id,
           m.name);
    let _task = index.record(m.def_id, rbml_w); // creates a task X
```

Here, if the function reads from `m` or `impl_item_opt`, this will not result in any incoming edges to the task `X`. To make this correct, we should either add artificial, explicit reads to account for those parameters or -- probably better -- minimize the data we pass in, and have `encode_info_for_method` go fetch things out of the appropriate maps, which will register the proper reads.

**Comment by michaelwoerister** [comment]
So, if we used `TyCtxt::visit_all_items_in_krate()` instead of `Crate::visit_all_items()` at https://github.com/rust-lang/rust/blob/5a7773a18098be712d7e1ce4fded36aed8c3c311/src/librustc_metadata/encoder.rs#L1417, that would fix the majority of problems, right?

**Comment by nikomatsakis** [comment]
@michaelwoerister yeah, actually, I think that was a mistake on my part. That would certainly be a good step. :) Probably ought to change the names there to make the distinction more obvious.

**Comment by nikomatsakis** [comment]
I'll tackle this.

**Comment by michaelwoerister** [comment]
It would also be good to see if we are reading data from external crates that is not linked to a specific `DefId` (i.e. "global" data like the disambiguator) but still influences codegen in some way.
