### ISSUE TITLE
Unsound: Borrowck missing that closure needs to be "move" 

### ISSUE THREAD

**Issue by diwic** [rust-lang/rust#35139]
Here's as far as I've come in minifying the problem. It gives bad result on both Stable, Beta and Nightly according to playground.

    pub trait MethodType: Sized + Default {
        type GetProp: ?Sized;
    }
    
    #[derive(Default, Debug, Copy, Clone)]
    pub struct MTFn;
    
    impl<'a> MethodType for MTFn {
        type GetProp = Fn(&mut String) -> Result<(), ()> + 'a;
    }
    
    pub struct Property<M: MethodType> {
        get_cb: Option<Box<M::GetProp>>,
    }
    
    impl<'a> Property<MTFn> {
        pub fn on_get<H>(mut self, handler: H) -> Property<MTFn>
            where H: Fn(&mut String) -> Result<(), ()> + 'a {
            self.get_cb = Some(Box::new(handler) as Box<_>);
            self
        }
    }
    
    fn main() {
        let z: Option<Property<MTFn>>;
        {
            let mut v = format!("ABC DEF GHI JKL");
            let p = Property { get_cb: None };
            
            // This line should give an error indicating we need a "move" closure
            z = Some(p.on_get(|s| { *s = v.clone(); Ok(()) }));
            
            // Destroy v to show the error
            v = format!("MNO PQR");
        }
        let mut q = format!("STU");
        let _ = (z.unwrap().get_cb.unwrap())(&mut q);
        println!("{}", q); // Prints "STU PQR" !
    }

**Comment by eefriedman** [comment]
The problem has to do with `type GetProp = Fn(&mut String) -> Result<(), ()> + 'a;`.  It probably should be triggering E0207 ("the lifetime parameter `'a` is not constrained by the impl trait, self type, or predicates").

**Comment by diwic** [comment]
@eefriedman, hmm, but this would be a bad solution in my real code. I want to indicate that the GetProp function can borrow from its environment (as opposed to `+ 'static`, which is the default and does not allow borrows at all. I believe?).

**Comment by eefriedman** [comment]
You can change `MTFn` to `pub struct MTFn<'a>(PhantomData<&'a u8>);`, then write `impl<'a> MethodType for MTFn<'a> {`, and everything should work.
