### ISSUE TITLE
Book typo: 4.23. Closures: missing i in i32

### ISSUE THREAD

**Issue by Stargateur** [rust-lang/rust#35147]
In chapiter 4.23. Closures, section "Taking closures as arguments"

There are two exemple where i is missing

``` rust
fn call_with_ref<'a, F>(some_closure:F) -> i32 
    where F: Fn(&'a 32) -> i32 {
```
``` rust
fn call_with_ref<F>(some_closure:F) -> i32
    where F: for<'a> Fn(&'a 32) -> i32 {
```

**Comment by wesleywiser** [comment]
This was fixed in 81386cf277d29b347bf4506571b9f0bcd3326523. I guess this hasn't made it to `stable` yet?
