### ISSUE TITLE
compiler panic (enum pattern didn't resolve to enum or struct None)

### ISSUE THREAD

**Issue by tones111** [rust-lang/rust#35152]
I come across a compiler panic message when attempting to build (cargo build) the attached code.  This might be a dupe of issue #33293, so maybe someone can test against a version with that fix applied.  Thanks.

$ rustc --version --verbose
rustc 1.10.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.10.0

[bug.zip](https://github.com/rust-lang/rust/files/392822/bug.zip)

**Comment by sanxiyn** [comment]
Yes, this is fixed.
