### ISSUE TITLE
New gdb with Rust support does not honor rust-gdb's pretty printers

### ISSUE THREAD

**Issue by DemiMarie** [rust-lang/rust#35155]
`gdb` git HEAD, when invoked via `rust-gdb`, does not honor the Rust pretty-printers.  This results in bad printing of types like `Vec`.

**Comment by michaelwoerister** [comment]
cc @tromey

**Comment by tromey** [comment]
It's most useful if you can report the version of rustc that you are using.  I was able to reproduce the problem with stable.  I'll look into it.

**Comment by tromey** [comment]
The older gdb says the type of a vec variable is:

```
(gdb) whatis x
type = struct Vec<i32>
```

However git gdb says:

```
(gdb) whatis x
type = collections::vec::Vec<i32>
```

The rust pretty-printers assume that the type tag holds the unqualified name (see `GdbType.get_unqualified_type_name`), but in git gdb, this is not the case:

```
(gdb) python print (val.type.tag)
collections::vec::Vec<i32>
```

Perhaps the Rust gdb scripts could be updated to recognize this name, though I'm not 100% certain this will work in all cases.
