### ISSUE TITLE
Unhelpful error message in macros which invoke other macros

### ISSUE THREAD

**Issue by tiffany352** [rust-lang/rust#35150]
The problematic code:

``` rust
macro_rules! x {
    ($a:expr, $b:expr) => {}
}

macro_rules! y {
    ($a:expr, $b:expr) => {
        x!($a, $b)
    }
}

// much later

fn foo() {
    macro_rules! x {
        ($a:expr) => {}
    }

    // later still

    y!(1, 2)
}
```

Rustc output:

```
error: no rules expected the token `,`
 --> <anon>:8:14
8 |>         x!($a, $b)
  |>              ^
```

[Playpen link](https://is.gd/ett0rc)

This error points out that the `y!` macro performed an incorrect invocation of the `x!` macro, but fails to point out which `x!` macro in particular it is trying to invoke, or the location where the `y!` macro was invoked. In addition, it doesn't point out tokens which the macro would accept (in this case, the end of the invocation).

**Comment by eddyb** [comment]
cc @jonathandturner

**Comment by estebank** [comment]
[Current output](https://play.rust-lang.org/?gist=5dff9e25ba0a255cca1d9547d5b9b924&version=nightly&mode=debug&edition=2015) still doesn't point at the called macro's _definition_ (like we _do_ for functions):

```
error: no rules expected the token `,`
  --> src/main.rs:8:14
   |
8  |         x!($a, $b)
   |              ^
...
21 |     y!(1, 2)
   |     -------- in this macro invocation
```
