### ISSUE TITLE
`pub` should not be allowed on nested items

### ISSUE THREAD

**Issue by matklad** [rust-lang/rust#35158]
The following compiles without errors:

```Rust
fn main() {
    pub struct S;
    let _ = S;
}
```

It probably should be an error to specify `pub` on a nested item, because it has no effect.

**Comment by petrochenkov** [comment]
Hey, we permitted this only a few months ago, it's too soon to make it an error again.
See https://github.com/rust-lang/rust/issues/31776 for details.

**Comment by matklad** [comment]
Hm, perhaps a lint should be added? Originally I though of the following example: 

```
fn a() {
    pub extern fn foo() {}
}
```
