### ISSUE TITLE
Rustdoc: Wrong documentation in case of types that only implement Deref, but not DerefMut

### ISSUE THREAD

**Issue by Sawyer47** [rust-lang/rust#35169]
Wrong documentation is generated for types that only implement Deref, but not DerefMut. It inherits methods from both Deref and DerefMut.

Steps to reproduce:
`cargo new deref-doc-bug`

````
/// lib.rs
pub struct Foo;

impl std::ops::Deref for Foo {
    type Target = [char];
    fn deref(&self) -> &[char] { &[] }
}
````
`cargo doc --open`

Generated documentation has methods for both `&[char]` and `&mut [char]`, for example`fn get_mut`.

## Version
````
rustc 1.12.0-nightly (1225e122f 2016-07-30)
rustdoc 1.12.0-nightly (1225e122f 2016-07-30)
````

**Comment by Mark-Simulacrum** [comment]
Cannot reproduce, versions below:

cargo:
`cargo 0.13.0-nightly (c205132 2016-08-09)`

rustc:
```
rustc 1.12.0-nightly (1deb02ea6 2016-08-12)
binary: rustc
commit-hash: 1deb02ea69a7ca3fd8011a45bb75ff22c3f7579a
commit-date: 2016-08-12
host: x86_64-apple-darwin
release: 1.12.0-nightly
```

rustdoc:
```
rustdoc 1.12.0-nightly (1deb02ea6 2016-08-12)
binary: rustdoc
commit-hash: 1deb02ea69a7ca3fd8011a45bb75ff22c3f7579a
commit-date: 2016-08-12
host: x86_64-apple-darwin
release: 1.12.0-nightly
```

**Comment by Sawyer47** [comment]
I still reproduce it. Maybe my description was not entirely clear. If a type implements the std::ops::Deref trait then there is an additional section in its documentation page `Methods from Deref<Target=...>`.
Even though `Deref::deref` returns an immutable reference, the generated documentation contains all methods, including those that would require `DerefMut`  implementation for the code to compile.

So, considering the example code from my previous message :

````
    let mut foo = Foo;
    assert_eq!(foo.len(), 0);      // ok
    assert_eq!(foo.get(0), None);  // ok
    // compile error, but generated documentation lists get_mut as an available function
    assert_eq!(foo.get_mut(0), None); 
````

I quickly grepped the source code and it looks like rustdoc only checks for the implementation of Deref 
([link to code](https://github.com/rust-lang/rust/blob/689c6c48ecd3d89d120c6aecf8b69222920e4520/src/librustdoc/core.rs#L55)).
