### ISSUE TITLE
Compiler allows type aliases with unused lifetime parameters

### ISSUE THREAD

**Issue by abonander** [rust-lang/rust#35160]
First noticed with [this funky type alias](http://docs.piston.rs/piston_window/piston_window/type.G2dTexture.html), which probably needed a lifetime at one point but doesn't anymore.

Simplest case is the most trivial: create a type alias with a lifetime parameter, but don't use it on the RHS:

``` rust
// No Error
pub type MyType<'a> = String;

// Errors
// pub type MyType<T> = String;

// Errors
// pub struct MyType<'a> {}
```

[Playground](https://is.gd/TTuCYZ)

The linked example compiles on all three channels.

As far as I understand it, unused type parameters are always supposed to be hard errors, as established in [RFC 738](https://github.com/rust-lang/rfcs/blob/master/text/0738-variance.md#the-corner-case-unused-parameters-and-parameters-that-are-only-used-unsafely), so this must be a corner case that was never implemented, or otherwise a regression. I haven't tested previous releases, I might do that tomorrow if someone hasn't gotten to this already,

**Comment by eddyb** [comment]
You can't misuse it because the checks are done on the semantic type, so it sees right through type aliases, e.g. `impl<'a> Foo for MyType<'a>` will fail because `Foo for String` doesn't mention `'a`.

**Comment by cybergeek94** [comment]
@eddyb [Are you sure about that?](https://is.gd/ibHELw)

**Comment by eddyb** [comment]
@cybergeek94 You're not using it anywhere so it's actually ignored, apparently.
[Here's the error](https://play.rust-lang.org/?gist=2bf3d87e421f5fa91d81ba657e019d18&version=nightly&backtrace=0).

**Comment by Mark-Simulacrum** [comment]
I'm going to mark this is a diagnostics issue since it's likely an error centering on the type alias's definition site would be a lot more helpful here.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/35160.

**Comment by abonander** [comment]
@Mark-Simulacrum you just closed this issue in favor of itself.

**Comment by Mark-Simulacrum** [comment]
Someone fix clipboards please; https://github.com/rust-lang/rust/issues/41960.
