### ISSUE TITLE
compiletest: error-pattern and warnings are not checked in run-pass tests

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#35165]
There are some `run-pass` tests that seemingly check whether a specific warning or error is emitted. As far as I can tell though, the `compiletest` tool just ignores the given directives in a `run-pass` test case, i.e. changing the given directives to something unexpected still lets the tests pass.

Some affected test cases (in no particular order):
- `attr-before-view-item.rs`
- `attr-before-view-item2.rs`
- `deprecated-macro_escape-inner.rs`
- `deprecated-macro_escape.rs`
- `deriving-meta-empty-trait-list.rs`
- `liveness-assign-imm-local-after-ret.rs`
- `unreachable-code-1.rs`
- `auxiliary/const_fn_lib.rs`
- `auxiliary/issue_3136_a.rs`
- `enum-size-variance.rs`
- `issue-25757.rs`
- `pred-not-bool.rs`
- `issue-19100.rs`
- `issue-2611-3.rs`

cc @rust-lang/compiler @rust-lang/tools

**Comment by brson** [comment]
Nice catch.

**Comment by brson** [comment]
An easy way to get started fixing this is to add checks for the warnings to run-pass. It should be relatively easy to crib off the compile-fail code to figure out how to do it.

Additionally add code that makes error directives `//~ERROR` or `error-pattern` *errors* since they don't make sense in run-pass tests.

For any tests that begin to fail because of these changes, check with the author of those tests to figure out how to proceed.

**Comment by terrynsun** [comment]
Can I try working on this?

**Comment by michaelwoerister** [comment]
@terrynsun Absolutely!

You might want to take a look at the implementation of [compiletest::runtest::run_cfail_test](https://github.com/rust-lang/rust/blob/545a3a94fcbdd68c4eeb60848c8eae2118c639c7/src/tools/compiletest/src/runtest.rs#L129) for clues on what to add to [compiletest::runtest::run_rpass_test](https://github.com/rust-lang/rust/blob/545a3a94fcbdd68c4eeb60848c8eae2118c639c7/src/tools/compiletest/src/runtest.rs#L197).

**Comment by ahmedcharles** [comment]
I have a fix for this, I just need a few other PRs to land first.

**Comment by terrynsun** [comment]
Cool! Sorry for taking so long to try to work on this.

**Comment by michael-zapata** [comment]
This should be closed, since the associated PR is in tree, right?

**Comment by michaelwoerister** [comment]
@michael-zapata True, thanks for the reminder!
