### ISSUE TITLE
eat while running

### ISSUE THREAD

**Issue by tovarishdno** [rust-lang/rust#35179]
Before i put the TAB eat any food and running - never had a problem with it stopped my running. But now, i need to click to mouse0 in TAB, whatever i was able to do at least something
Vid: https://youtu.be/E0d2j9ogp0o

**Comment by dns2utf8** [comment]
Hi Tovarishdno

I think you are looking for the [Rust-Forum](https://lab.facepunch.com/rust) or the [Steam-Forum](https://steamcommunity.com/app/252490/discussions/4/). This project has no ties to the game [Rust](https://playrust.com/)

Regards
