### ISSUE TITLE
LLVM lifetime intrinsics and MIR

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#35171]
MIR is currently not emitting LLVM lifetime intrinsics. This means we will generate larger stack frames than trans. 

cc @eddyb @arielb1 @nagisa, with whom I know I have discussed this

**Comment by Mark-Simulacrum** [comment]
Was this fixed by #35409?

**Comment by nagisa** [comment]
yes.

**Comment by ranma42** [comment]
If this was fixed, should it be closed?
