### ISSUE TITLE
gdb git HEAD cannot invoke methods

### ISSUE THREAD

**Issue by DemiMarie** [rust-lang/rust#35173]
`gdb` (git HEAD) cannot invoke member functions, as their demangled name contains `{{impl}}` or other syntactically-invalid forms.

**Comment by nagisa** [comment]
Since gdb now implements Rust support natively, this probably should be reported against gdb instead.

**Comment by Mark-Simulacrum** [comment]
Closing, this is better tracked in https://github.com/rust-lang/rust/issues/37646, and this specific issue isn't specific enough to keep open.
