### ISSUE TITLE
doc: some links to char primitive give Not Found "Looks like you've taken a wrong turn."

### ISSUE THREAD

**Issue by icanrealizeum** [rust-lang/rust#35185]
This might be more generic, but in my case, clicking on the `char` links on this page: https://doc.rust-lang.org/std/string/struct.String.html#method.chars
gives a page with:
```
Not Found

Looks like you've taken a wrong turn.

Some things that might be helpful to you though:

Search


primitive char site:doc.rust-lang.org
 Search DuckDuckGo
Rust doc search: char
```

The good link appears to be this: https://doc.rust-lang.org/std/char/index.html

Thanks!

**Comment by icanrealizeum** [comment]
Oh wait actually, the good link seems to be this:
https://doc.rust-lang.org/std/primitive.char.html
instead of what it tried:
https://doc.rust-lang.org/std/string/primitive.char.html

**Comment by durka** [comment]
See #32129.

**Comment by icanrealizeum** [comment]
yup, duplicate.
Thank you:)
