### ISSUE TITLE
rustbuild ignores the llvm-config setting

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#35199]
I got in my `src/bootstrap/config.toml`:

```
[target.x86_64-unknown-linux-gnu]
…
llvm-config = "/home/nagisa/local/bin/llvm-config"
```

but rustc_llvm/build.rs still seems to attempt using /usr/bin/llvm-config

```
$ cat build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/build/rustc_llvm-9ee423514f5f4196/output 
cargo:rustc-cfg=cargobuild
cargo:rerun-if-changed=/usr/bin/llvm-config
```

cc @alexcrichton

**Comment by alexcrichton** [comment]
I think that the actual behavior (from IRC) that happened here was that `llvm-config` configuration change in `cargo.toml`, but the build script wasn't re-run.

The build script should probably print out `rerun-if-changed` pointing at `config.toml` if it exists, passed through via rustbuild.

**Comment by Mark-Simulacrum** [comment]
@alexcrichton I think the build script doesn't point to config.toml with `rerun-if-changed`; is it possible we could make this into an E-easy issue? I get the feeling that this would also make a decent intro into rustbuild.

**Comment by alexcrichton** [comment]
Certainly!

I think we'll need to pass the path of config.toml via an env var, but that shouldn't be too onerous to do in rustbuild either. If anyone's got any questions please feel free to ask!

**Comment by venkatagiri** [comment]
I would like to work on this. Can I use the env var `CFG_TOML` to pass the path of `config.toml` from `bootstrap::compile::rustc`? Or `LLVM_CFG_TOML` or `CONFIG_TOML`.

**Comment by Mark-Simulacrum** [comment]
I think an env var would probably be the best approach. `CFG_LLVM_TOML` seems good, but that can be bikeshedded in the PR. Let us know if we can do anything to help!
