### ISSUE TITLE
#[derive(Default)] constraints type parameters despite not being required for a Default bound.

### ISSUE THREAD

**Issue by ticki** [rust-lang/rust#35263]
```rust
#[derive(Default)]
struct Type<T> {
    vec: Vec<T>,
}
```

only derives `Type<T>: Default` if `T: Default`, which is unnecessary, given a `Vec<T>: Default` for any unbounded `T`.

**Comment by jonas-schievink** [comment]
Sounds like #26925

**Comment by ticki** [comment]
Certainly related, but not exactly a duplicate.

**Comment by apasel422** [comment]
Since #32673 was a duplicate of #26925, I would argue this is as well.

**Comment by eddyb** [comment]
Closing as duplicate of #26925.
