### ISSUE TITLE
E0060 and E0061 bonus improvements for error messages

### ISSUE THREAD

**Issue by birryree** [rust-lang/rust#35290]
cc @GuillaumeGomez 

This issue tracks the bonus portions of issues #35215 and #35216. I worked on the `span_label` fixes for them and @jaredwy said he would take on the bonus portion.

**Bonus for E0060**:

>     error[E0060]: this function takes at least 1 parameter but 0 parameters were supplied
>       --> src/test/compile-fail/E0060.rs:16:14
>        |
>     16 |     unsafe { printf(); } //~ ERROR E0060
>        |              ^^^^^^^^ expected at least 1 parameter
>        |
>        = note: the following parameter type was expected: *const u8
> 
> Bonus: There may be a better way of displaying the information from the note. Could it be part of the label?

**Bonus for E0061**:

> 
> 
>     error[E0061]: this function takes 2 parameters but 1 parameter was supplied
>       --> src/test/compile-fail/E0061.rs:14:5
>        |
>     14 |     f(0); //~ ERROR E0061
>        |     ^^^^ expected 2 parameters
>        |
>        = note: the following parameter types were expected: u16, &str
> 
>     error: aborting due to previous error
> 
> Bonus: the types could be incorporated into the label rather than a note (though we may want to avoid types with long names in the label)

**Comment by GuillaumeGomez** [comment]
Thanks for opening it @birryree!

cc @jonathandturner

**Comment by KiChjang** [comment]
@jaredwy Are you still working on this?

**Comment by jaredwy** [comment]
@kichjang I have been yup. :) wound up in hospital. So just no time to clean it up and push yet unfortunately.

Sorry!

**Comment by jonathandturner** [comment]
@jaredwy - woah, that's crazy!  Hopefully things are (mostly) better now.

**Comment by GuillaumeGomez** [comment]
@jaredwy: Sorry, didn't see you took it and I did it. :-/ As apologies, I propose you to have a first possible lock on https://github.com/rust-lang/rust/pull/35920 before we give them to others as well.

**Comment by jaredwy** [comment]
@jonathandturner All is well, thanks! Was expected surgery just managed to get in earlier  :) 

@GuillaumeGomez that is ok :) Spent the past week on the couch. I might hit you up on that offer of an apology in way of mentoring on a bigger rust issue :D

**Comment by GuillaumeGomez** [comment]
@jaredwy: Let's do it like this then. Try to get better meanwhile!

**Comment by jaredwy** [comment]
@GuillaumeGomez great! will send you an email.
