### ISSUE TITLE
process::ExitStatus propagation

### ISSUE THREAD

**Issue by mitsuhiko** [rust-lang/rust#35293]
Currently if you have a `process::ExitStatus` it is my understanding that if you want to `process::exit` with it (to propagate the status) you need to do lots of platform specific handling due to the splitting of the signal on unix.

Eg, something like this:

``` rust
#[cfg(unix)]
pub fn get_raw_exit_status(status: ExitStatus) -> i32 {
    status.code().or_else(|| status.signal().map(|x| x + 127)).unwrap_or(255)
}

#[cfg(not(unix))]
pub fn get_raw_exit_status(status: ExitStatus) -> i32 {
    status.code().unwrap_or(255)
}

process::exit(get_raw_exit_status(child.wait()))
```

Maybe one could implement a function on `ExitStatus` that invokes process::exit correctly (and a ToRaw function that returns an i32?)

**Comment by zackw** [comment]
You can't actually mimic exiting due to a signal with a call to `exit()`.  It would have to be something like

```rust
mod process {
    fn propagate_exit(status: ExitStatus) -> ! {
        run_atexit_handlers();
        kill_all_other_threads();
        if let Ok(sig) = status.signal() {
            unmask_and_reset_handler_for_signal(sig);
            kill(getpid(), sig);
        } else {
            _exit(status.code().unwrap());
        }
        unreachable!();
    }
}
```

**Comment by dtolnay** [comment]
I agree that exiting with an ExitStatus could be handled better by the standard library. I believe this is going to require an [RFC](https://github.com/rust-lang/rfcs/blob/master/libs_changes.md) -- someone will need to come up with a concrete design for how to expose this, and justify why it is the best way to address the use cases that we care about.
