### ISSUE TITLE
Test functions should work when defined inside other functions

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#3532]
This doesn't work, but I frequently want to do it

```
fn foo() {

  ...

  #[test]
  fn test1() { }
}
```

The generated code for running test functions uses paths to the tests, and it's not possible to generate a path to `test1`. The test runner already breaks resolution rules to run private tests, so maybe we can break yet more.

We would want to consider though how this could work with reflection-based test runners - the way we currently break visibility rules to run tests is already bad news for reflection.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#612
