### ISSUE TITLE
Stop prepending the path and line number to every line in error messages

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#3533]
For the sake of people with 80-character terminals, Rust code is limited to 78 characters in width. So why do error messages on 80-character terminals look like this:
```
/home/ben/code/rust-projects/rust/src/rustc/metadata/filesearch.rs:24:0: 29:1 wa
rning: type, variant, or trait must be camel case
/home/ben/code/rust-projects/rust/src/rustc/metadata/filesearch.rs:24 trait file
search {
/home/ben/code/rust-projects/rust/src/rustc/metadata/filesearch.rs:25     fn sys
root() -> Path;
/home/ben/code/rust-projects/rust/src/rustc/metadata/filesearch.rs:26     fn lib
_search_paths() -> ~[Path];
/home/ben/code/rust-projects/rust/src/rustc/metadata/filesearch.rs:27     fn get
_target_lib_path() -> Path;
/home/ben/code/rust-projects/rust/src/rustc/metadata/filesearch.rs:28     fn get
_target_lib_file_path(file: &Path) -> Path;
/home/ben/code/rust-projects/rust/src/rustc/metadata/filesearch.rs:29 }
```
This is a pathological case, but I still manage to hit this frequently even though my term is often well wider than 80 characters.

Here's how Java formats its error messages:
```
jello.java:3: cannot find symbol
symbol  : variable Exception
location: class jello
        throw Exception;
              ^
1 error
```
Taking inspiration from this, Rust error messages could instead look like:
```
Warning: type, variant, or trait must be camel case
/home/ben/code/rust-projects/rust/src/rustc/metadata/filesearch.rs 24:0-29:1
trait filesearch {
    fn sysroot() -> Path;
    fn lib_search_paths() -> ~[Path];
    fn get_target_lib_path() -> Path;
    fn get_target_lib_file_path(file: &Path) -> Path;
}
```

**Comment by BigBoneDaddy** [comment]
@tbelaire Does that fix fix this?

**Comment by tbelaire** [comment]
No.  #11715 just fixes the line numbers to line up properly when we go from 9 to 10, or 99 to 100, as the formatting broke by one space.  If we removed the line numbers and column numbers, it would be moot.

**Comment by Manishearth** [comment]
Relevant code:

https://github.com/rust-lang/rust/blob/ca4b9674c26c1de07a2042cb68e6a062d7184cef/src/libsyntax/diagnostic.rs#L464

We should split that to handle one-line and multi-line errors, keeping one-line errors as is and indenting multi-line errors by a fixed amount instead of appending the line number.

**Comment by Manishearth** [comment]
Should there be a CLI flag for turning this off?

**Comment by Manishearth** [comment]
@Wafflespeanut is working on this

Note: We should preserve the old behavior with a rust flag like --machine-readable-errors or something for IDEs

**Comment by bstrie** [comment]
I'm fine with having a flag to re-enable verbose error output for the purpose of IDEs, but the other comments in this thread seem to imply that's not actually necessary. What IDEs need output like this?

**Comment by Boddlnagg** [comment]
VisualRust is parsing rustc output, but that's actually [not very robust](https://github.com/PistonDevelopers/VisualRust/issues/113) at the moment, so we need to change something there anyway. I'm also looking forward to having a structured machine-readable output format as proposed in https://github.com/nrc/rfcs/blob/ide/text/0000-ide.md#error-format. I'd say having separate output formats for humans (focusing on readability) and IDEs is the way forward.
