### ISSUE TITLE
Old school errors not showing labels as notes

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang/rust#35330]
Originally, we had intended that old school errors would treat most labels as notes just so we would have similar information between the two formats.  With the latest refactor, this seems to have been removed.

This may or may not be related: https://gist.github.com/trixnz/ad11e68687529e164427df8f8eb63116

```
error[E0507]: cannot move out of borrowed content
  --> src/test/compile-fail/borrowck/borrowck-move-out-of-vec-tail.rs:30:17
   |
30 |                 &[Foo { string: a },
   |                 ^               - hint: to prevent move, use `ref a` or `ref mut a`
   |                 |
   |                 cannot move out of borrowed content
...
34 |                   Foo { string: b }] => {
   |                                 - ...and here (use `ref b` or `ref mut b`)

error: aborting due to previous error
```

Same error after `unset RUST_NEW_ERROR_FORMAT`

```
jturner-23759:rust jturner$ rustc src/test/compile-fail/borrowck/borrowck-move-out-of-vec-tail.rs 
src/test/compile-fail/borrowck/borrowck-move-out-of-vec-tail.rs:30:17: 34:37 error: cannot move out of borrowed content [E0507]
src/test/compile-fail/borrowck/borrowck-move-out-of-vec-tail.rs:30                 &[Foo { string: a },
                                                                                   ^               ^
src/test/compile-fail/borrowck/borrowck-move-out-of-vec-tail.rs:30:17: 34:37 help: run `rustc --explain E0507` to see a detailed explanation
error: aborting due to previous error 
```

**Comment by nagisa** [comment]
Maybe it would make sense to have a separate `LABEL` marker for the labels?

**Comment by jonathandturner** [comment]
@nagisa - yeah, though we should chat with @nikomatsakis.  He's been leaning towards more tests being UI tests that check for these things, so you can check layout at the same time.

**Comment by nikomatsakis** [comment]
@jonathandturner I am reminded that I had planned to start a thread on internals to talk it over. I am not sure what I think would be best, but I feel pretty sure that I do not like the fact that `//~ foo` works (i.e., I think I would prefer limiting things to `//~ [ERROR|WARNING|NOTE|HELP]`, which would then at least get the rule that notes/helps must be exhaustively checked if they are checked at all.

**Comment by lfairy** [comment]
Should this be closed now, since old school errors no longer exist (#35401)?

**Comment by jonathandturner** [comment]
@lfairy - good catch
