### ISSUE TITLE
292 error messages are missing unit tests

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang/rust#35347]
The following errors are missing unit tests in the test directory(292 in total).  I know we "test using --explain" I don't think this is really sufficient to ensure that the error message has high quality since we're only really running the explain and not looking at the error message itself.

E0003
E0006
E0014
E0019
E0020
E0066
E0068
E0073
E0074
E0082
E0085
E0086
E0090
E0103
E0104
E0122
E0123
E0127
E0129
E0134
E0135
E0136
E0139
E0141
E0153
E0154
E0157
E0159
E0163
E0167
E0168
E0170
E0173
E0174
E0182
E0183
E0187
E0188
E0189
E0190
E0193
E0196
E0198
E0201
E0202
E0203
E0204
E0205
E0208
E0209
E0211
E0212
E0213
E0214
E0215
E0216
E0217
E0218
E0219
E0220
E0221
E0222
E0224
E0225
E0226
E0227
E0228
E0230
E0231
E0232
E0233
E0234
E0235
E0236
E0237
E0238
E0239
E0240
E0241
E0242
E0243
E0244
E0245
E0246
E0247
E0248
E0249
E0251
E0253
E0254
E0255
E0256
E0257
E0258
E0259
E0260
E0261
E0262
E0263
E0264
E0267
E0268
E0271
E0272
E0273
E0274
E0276
E0278
E0279
E0280
E0281
E0283
E0284
E0285
E0296
E0297
E0298
E0299
E0300
E0301
E0302
E0304
E0305
E0311
E0313
E0314
E0315
E0316
E0319
E0320
E0328
E0329
E0364
E0365
E0366
E0369
E0370
E0372
E0374
E0375
E0376
E0377
E0380
E0381
E0382
E0383
E0384
E0385
E0386
E0387
E0389
E0390
E0392
E0393
E0394
E0398
E0399
E0401
E0402
E0403
E0406
E0407
E0408
E0409
E0410
E0411
E0413
E0414
E0415
E0416
E0417
E0418
E0419
E0420
E0421
E0422
E0423
E0424
E0426
E0427
E0428
E0429
E0430
E0431
E0434
E0435
E0436
E0437
E0438
E0439
E0440
E0441
E0442
E0443
E0445
E0447
E0448
E0449
E0450
E0451
E0452
E0453
E0454
E0455
E0456
E0457
E0458
E0459
E0460
E0461
E0462
E0463
E0464
E0465
E0466
E0467
E0468
E0469
E0470
E0471
E0472
E0473
E0474
E0475
E0476
E0477
E0479
E0480
E0481
E0482
E0483
E0484
E0485
E0486
E0487
E0488
E0489
E0490
E0491
E0492
E0493
E0494
E0496
E0497
E0498
E0500
E0501
E0502
E0503
E0504
E0505
E0506
E0508
E0511
E0512
E0513
E0514
E0516
E0517
E0518
E0519
E0521
E0522
E0523
E0524
E0526
E0527
E0528
E0529
E0530
E0531
E0532
E0533
E0534
E0535
E0536
E0537
E0538
E0543
E0545
E0549
E0550
E0551
E0552
E0553
E0554
E0555
E0556
E0557
E0558
E0559
E0560

**Comment by GuillaumeGomez** [comment]
Already working on it. I assign it to myself to avoid conflicts.

**Comment by Mark-Simulacrum** [comment]
As far as I can tell, at least some of these are still missing tests, but I don't really know of an easy way to get an accurate count.
