### ISSUE TITLE
__rust_*alloc functions are not documented

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#35361]
Behaviour of these functions, behaviour of arguments they take and everything else about these functions is not documented in any way.

Alas, jemalloc doesn’t really document its functions well itself, so short of reading the whole source of jemalloc on every upgrade, I doubt there’s a sensible way to exhaustively document these functions.

**Comment by steveklabnik** [comment]
I don't generally document internals, so someone else will have to take this one up.

**Comment by steveklabnik** [comment]
>  I doubt there’s a sensible way to exhaustively document these functions.

What would resolve this ticket, then?

**Comment by nagisa** [comment]
> What would resolve this ticket, then?

I guess somebody will have to:

1) chat with @alexcrichton and figure out what intended semantics of each function and their arguments are (and verify the stuff figured out);
2) read source code/manpages/documentation for functions used in implementation of current allocators (jemalloc/system/winapi) and figure out the semantics from that;

For example:

> \<nagisa_\>	acrichto: what’s align parameter for reallocate for then? show?
> \<acrichto\>	nagisa_: the incoming block's alignment I believe; and the resulting outgoing block's alignment

> internals

People writing unsafe code do rely on these “internals”, so having documentation for them would be useful for the wider audience IMO.

**Comment by alexcrichton** [comment]
These are all documented in [heap.rs](https://github.com/rust-lang/rust/blob/master/src/liballoc/heap.rs) to some extent.

**Comment by nagisa** [comment]
Oh. Docs seem sufficient there.
