### ISSUE TITLE
The `TypeId` hash should not use the SVH

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#35379]
It is incompatible with incremental compilation. It should use the crate-name/crate-disambiguator and the stuff for deterministically hashing def-paths (some of which has not yet landed).

cc @michaelwoerister

**Comment by michaelwoerister** [comment]
:+1:

**Comment by eddyb** [comment]
Is this solved now?

**Comment by michaelwoerister** [comment]
@eddyb Yes! 🎉
