### ISSUE TITLE
myriad-closures test takes ages to compile

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#35398]
About 2.5 minutes of rustc on my machine. Can we test that stuff in a different way? Maybe only run test on CI?

**Comment by nikomatsakis** [comment]
Why does it take so long? Just the sheer size?

**Comment by nagisa** [comment]
> Just the sheer size?

Yes. It makes 2¹² functions containing 2⁴ closures each.

**Comment by nagisa** [comment]
With optimisations

> time: 61.222; rss: 233MB	llvm module passes [0]

Forcing optimisations off for this test would save a minute while still properly testing the thing this test is testing. AFAIR there’s no way to force optimisation off, though.

**Comment by eddyb** [comment]
Does it *need* to run? For tests that only need to compile we usually `#[rustc_error] fn main() {}` them.

**Comment by michaelwoerister** [comment]
@eddyb I seem to remember the test failing without the fix it is supposed to test.

But maybe we can just move this to somewhere where it doesn't cause trouble? One of the full-deps targets, maybe?

**Comment by eddyb** [comment]
@michaelwoerister If we have a nopt test builder for mingw then yes, this test would be useful *there*.

**Comment by eddyb** [comment]
I think we screwed up at some point, the IR is pretty bad (and would explain why it's slow):
```rust
fn main() {
    fn function() {
        let c = |a: u32| a + 4;
        let _ = c(2);
    }
    let _ = function();
}
```
```llvm
%closure = type {}

; Function Attrs: uwtable
define internal void @test::main() unnamed_addr #0 {
entry-block:
  %_0 = alloca {}
  br label %start

start:                                            ; preds = %entry-block
  call void @test::main::function()
  br label %bb1

bb1:                                              ; preds = %start
  ret void
}

; Function Attrs: uwtable
define internal void @test::main::function() unnamed_addr #0 {
entry-block:
  %_0 = alloca {}
  %c = alloca %closure
  %_4 = alloca { i32 }
  br label %start

start:                                            ; preds = %entry-block
  %0 = bitcast { i32 }* %_4 to i8*
  call void @llvm.lifetime.start(i64 4, i8* %0)
  %1 = getelementptr inbounds { i32 }, { i32 }* %_4, i32 0, i32 0
  store i32 2, i32* %1
  %2 = load { i32 }, { i32 }* %_4
  %3 = extractvalue { i32 } %2, 0
  %4 = call i32 @"test::main::function::{{closure}}"(%closure* noalias readonly %c, i32 %3)
  br label %bb1

bb1:                                              ; preds = %start
  %5 = bitcast { i32 }* %_4 to i8*
  call void @llvm.lifetime.end(i64 4, i8* %5)
  ret void
}

; Function Attrs: uwtable
define internal i32 @"test::main::function::{{closure}}"(%closure* noalias readonly, i32) unnamed_addr #0 {
entry-block:
  br label %start

start:                                            ; preds = %entry-block
  %2 = add i32 %1, 4
  ret i32 %2
}
```

**Comment by arielb1** [comment]
Can't LLVM optimize the `{ i32 }` dance in function passes?

**Comment by arielb1** [comment]
I think the problem might have to do with the fact that the `myriad_closures` function is *huge*.

**Comment by eddyb** [comment]
@arielb1 That's with `-C no-prepopulate-passes` - the fact that we touch memory results in many more instructions that slow it down in memdep analysis and optimizations etc. (not that we want optimizations).

To fix the closure codegen in general we should probably move away from `rust-call` and onto a more VG-oriented "spread arguments" model, but that's even more work to do 😞.

**Comment by arielb1** [comment]
@eddyb 

I am quite sure everything is cleaned up when we get to module passes, which is what takes most of the time.

**Comment by ishitatsuyuki** [comment]
This compiles in about 40s now. Can someone decide if this still worth investigating?
