### ISSUE TITLE
[rustbuild] -j option is ignored for tests

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#35399]
With rustbuid `python src/bootstrap/bootstrap.py --step check --stage 1 -j8`, during tests only one stage of tests will be run at a time and only one core will be utilized by the test runner.

The script should take care to pass over the flag.

**Comment by alexcrichton** [comment]
The test runner is always libtest, so I thought, which always uses all cores. In that sense `-j1` isn't transmitted correctly, but "use all cores" should be the default. Did you see this not as the behavior though?

**Comment by nagisa** [comment]
I’m telling what I’m seeing on my system. It only runs run-pass tests on one core for me and nothing else (i.e. only one core is maxed). I haven’t gotten past the run-pass tests to see if the test runner would even try to run the other tests because I have test failures in `run-pass/backtrace-debuginfo-aux.rs` and `run-pass/mod_file_aux.rs` which I haven’t investigated yet.

**Comment by nagisa** [comment]
Okay, I was semi-wrong about it. I was just looking at utilisation while the [myriad-closures](https://github.com/rust-lang/rust/issues/35398) test was running after all other tests were already complete, giving impression that only one core is used.

rustbuild still only runs different classes of tests sequentially, though.

**Comment by alexcrichton** [comment]
Yes rustbuild runs tests serially, and all tests are internally parallelized by default. Not sure what more we would do?
