### ISSUE TITLE
Can't specify linker arguments with space in them

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#35440]
Executing `rustc -C link-args=...` results in the `...` being split by whitespace and each element being supplied as a single argument to the linker. This means it's not possible to specify a linker argument with whitespace in it (for example, a path to a linker script) on the command line. The same applies to the `#[link_args]` attribute. Possible solutions are parsing some kind of escaping (fragile) and allowing setting multiple `link-arg` arguments, each of which individually is not whitespace-split.

**Comment by sanxiyn** [comment]
See rust-lang/rfcs#1509 for a discussion and a design.

**Comment by japaric** [comment]
> allowing setting multiple link-arg arguments

#36574 implements this

**Comment by sanxiyn** [comment]
Fixed by #36574.
