### ISSUE TITLE
Book chapter ordering changed? Text inconsistent

### ISSUE THREAD

**Issue by OJFord** [rust-lang/rust#35457]
It appears that the chapter ordering may have changed.

As it stands, 4.8 Ownership gives a basic `vec!` example and says not to worry, it will be explained later; in fact, it was explained just now in 4.7 Vectors.

Similarly, 4.10 Lifetimes appears to assume familiarity with 4.12 Structs.

The simplest solution might be to switch chapter 4.7 with 4.12 - but I realise that may be the entirely deliberate change that caused this problem, in which case I suppose the content just could do with updating a bit.

**Comment by steveklabnik** [comment]
It's not exactly just that; it's also that people added different things over time. So it was "oh hey this info is missing" but that accidentally introduced a forward reference.

We're currently in the process of entirely re-writing the book, work is being done over here: https://github.com/rust-lang/book As such, I'm not really making big changes to the existing book, if you or someone else wants to take a shot at fixing these issues, please send in a PR! But I'm going to give this one a close, as it's going to be fixed more generally when the book gets replaced. Thanks!

**Comment by OJFord** [comment]
Sounds good; the new version looks like the more factored structure will help prevent issues like this. :)

It's not a big deal, I only noticed because I'm reading through 'cover' to 'cover'. If a PR does pop up you'll know I'm avoiding something else!

Cheers.
