### ISSUE TITLE
[question: python extension] how can I write extension(FFI) library to python3 with Rust

### ISSUE THREAD

**Issue by CDLuminate** [rust-lang/rust#35459]
I'm still learning rust and I'd like to try writing extension in rust for python.
I succeed with some hacks, but that makes me more confused.

I wrote this code:
```
pub fn kernel (s: &'static str) -> i32 {  // [1]
  println!("arg string [{}] len [{}]", s, s.len());
  42
}
```
I compiled it with
```
$ rustc --crate-type dylib x.rs
```
then I found the kernel function entrace point with binutil
```
$ nm libx.so | ack kernel
0000000000383108 d _ZN1x6kernel15__STATIC_FMTSTR17h8dbf7ea278fab1c2E
00000000000b4020 T _ZN1x6kernel17h696f1b75bfc331c3E
```
after that I wrote such an python3 script
```
$ cat confuse.py 
import ctypes
x = ctypes.CDLL('./libx.so')
msg = "Hello Rust Library".encode("UTF-8")
#print(x._ZN1x6kernel17h696f1b75bfc331c3E(msg)) # segfault
print(x._ZN1x6kernel17h696f1b75bfc331c3E(msg, len(msg))) // [2]
```
and it works
```
$ python3 confuse.py 
arg string [Hello Rust Library] len [18]
42
```

According to mark `//[1]` from the rust code we know the kernel function definition is `kernel(string)` instead of `kernel(string, string_size)`, but what actually works is the later.

My question is:  
1. How hacky is it to call Rust library function with FFI/CFFI ?  
2. What's the recommended way to write extension library in rust for python? I searched but found nearly nothing... Is it to use crate `libc` ? (e.g. https://github.com/dgrunwald/rust-cpython/blob/master/python3-sys/examples/version.rs)

**Comment by TimNN** [comment]
`ctypes` expects functions to have the C ABI (as far as I know), which is not the default for rust functions. I recommend you take a look at the [ffi chapter in the book](https://doc.rust-lang.org/book/ffi.html). Also rust slices (and unsized types in general), such as `[u8]` and `str` are not considered "ffi safe" and should not be used in the C interface of a library.

You'll probably want somthing like

```rust
use std::ffi::CStr;
use std::os::raw::c_char;

#[no_mangle]
pub extern "C" fn kernel(s: *const c_char) -> i32 {
    let cs = unsafe { CStr::from_ptr(s) };
    let s = cs.to_string_lossy();
    println!("arg string [{}] len [{}]", s, s.len());
    42
}
```

Apart from that calling rust from C (python) shouldn't be "hacky" at all.

**Comment by shepmaster** [comment]
Also [The Rust FFI Omnibus](http://jakegoulding.com/rust-ffi-omnibus/) includes Python examples.

**Comment by CDLuminate** [comment]
@TimNN @shepmaster
Thank you for quick answer!

The snippet works well and to my suprise the generated symbol in rust library is quite clean:
```
$ nm libkernel.so | ack kernel
0000000000384108 d _ZN6kernel6kernel15__STATIC_FMTSTR17h42857d76e83fb6f3E
00000000000b4090 T kernel
000000000038f3d0 D rust_metadata_kernel_f0c475c1165a0b09
```
and the python ffi caller script is not confusing anymore:
```python
kernel.kernel("hello".encode())
```

Well, I think the official doc should be updated to point out that by default rust library ABI is not quite compatible as C ABI.

**Comment by Aatch** [comment]
The issue tracker isn't an appropriate place for these kinds of questions. We're happy to help, but please use the [forums](https://users.rust-lang.org) or IRC (#rust or #rust-beginners on irc.mozilla.org).
