### ISSUE TITLE
Document Why From Isn't Always Implemented

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#35451]
Apparently the `From<T>` trait isn't always implemented for things where it could be. See also, [Why there is no `impl<'a, T: Clone> From<&'a T> for T`?](https://www.reddit.com/r/rust/comments/4whhrc/why_there_is_no_impla_t_clone_froma_t_for_t/).

Should we add documentation explaining why they aren't implemented for those types?

If so, other than `impl <'a, T: Clone> From<&'a T> for T`, are there other types that they are purposely not implemented for even though it can be?

**Comment by steveklabnik** [comment]
In general, documenting "why not" is tough, as there are millions of "why not"s, compared to exactly one "why".

**Comment by Havvy** [comment]
Another option is to leave these "why not"s for The Rust Book, though having it in the official documentation says its been decided officially and it's not an oversight.

**Comment by frewsxcv** [comment]
I don't know what actionable item there is here. If there is a reason we don't have that `impl`, what is it? Personally, I don't see much value in such an `impl` as writing:

```rust
let a: &u32 = &10;
let b: u32 = *a;
```

is easier than:

```rust
let a: &u32 = &10;
let b: u32 = a.into();  // or: let b = u32::from(a);
```

**Comment by steveklabnik** [comment]
I don't think this is actually actionable. Closing.
