### ISSUE TITLE
Sort help messages with spans after those without

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang/rust#35460]
From https://github.com/Manishearth/rust-clippy/issues/1148

Looks like help (and potentially other types) with spans may not be sorted to display after the those without spans.

When clippy reports a suggestion with a macro in the code, it seems to print the expanded form. Using the example from README.md, you can see it is not behaving as expected:

``` rust
fn main(){                             
    let x = Some(1u8);                 
    match x {                          
        Some(y) => println!("{:?}", y),
        _ => ()                        
    }                                  
}
```

results in:

```
warning: you seem to be trying to use match for destructuring a single pattern. Consider using `if let`, #[warn(single_match)] on by default
 --> src\main.rs:3:5
  |
3 |     match x {
  |     ^
  |
help: try this
  |     if let Some(y) = x { $ crate :: io :: _print ( format_args ! ( $ ( $ arg ) * ) ) }
  = help: for further information visit https://github.com/Manishearth/rust-clippy/wiki#single_match
```

**Comment by oli-obk** [comment]
This seems to work now:

```
  = note: #[warn(single_match)] on by default
  = help: for further information visit https://github.com/rust-lang-nursery/rust-clippy/wiki#single_match
help: try this
  |
3 |     if let Some(y) = x {
4 | println!("{:?}", y)
5 | }                                  
  |
```

**Comment by estebank** [comment]
Suggestions always come last now (which I believe was the original reason for this ticket).

Help messages and notes continue to be emitted in the order they were called, in order to maintain readability of messages that may or may not have spans but have a narrative flow.
