### ISSUE TITLE
HashMap has no way to avoid key copy or double hash for insertion

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#35463]
Currently all HashMap APIs which make insertion into a map possible (`insert`, `entry`) require the key by-value. If avoiding a `clone` is desired, the user must instead use something like `if !map.contains(key) { map.insert(key.clone(), val); }`, which results in key getting hashed twice.

Ideally, something like `HashMap::insert_clone(key: &K, val: V) where K: Clone` or `HashMap::entry_clone(key: &K) where K: Clone` would exist.

**Comment by nagisa** [comment]
Note that internal APIs have the ways to achieve this. `HashMap::search` takes a key by reference and returns InternalEntry, which, if converted to plain entry, gets provided the key by value.

**Comment by nagisa** [comment]
Another option is to have a method like `HashMap::occupied_entry(key: &K) -> Option<OccupiedEntry>`.

**Comment by Stebalien** [comment]
Personally, I'd use `ToOwned` instead of `Clone`. IIRC, I believe there was extensive discussion about this in some RFC issues.

**Comment by nagisa** [comment]
Ah, right, as always, I don’t care about bounds very much as long as it is possible to avoid both extra allocation when hashmap already has the key and double hashing when it doesn’t.

**Comment by dtolnay** [comment]
I believe this is going to require an RFC. There is already https://github.com/rust-lang/rfcs/issues/1203 tracking a similar idea so let's continue the discussion there.
