### ISSUE TITLE
Rust on Windows Vista (crash with SetThreadErrorMode)

### ISSUE THREAD

**Issue by techtonik** [rust-lang/rust#35471]
`rust-1.10.0-i686-pc-windows-gnu.msi` contains compiler that doesn't run on Vista - crashes with missing `SetThreadErrorMode` in `KERNEL32.dll`. I thought that I can use Rust as a platform independent C replacement, but it seems not possible. Maybe there are binaries without those Windows 10 specific optimizations that I missed?

![image](https://cloud.githubusercontent.com/assets/515889/17464247/36b41078-5ce3-11e6-81ba-9630f2cd4844.png)

**Comment by nagisa** [comment]
The compiler itself requires at least Window 7 (Windows Server 2008 R2) to run. Programs compiled with Rust *may* run with Windows all the way back to XP, but some features exposed by the standard library (most notably locking) will not work.

**Comment by techtonik** [comment]
@nagisa is it possible to to use software emulation for missing features on development machines? It will help to save the day. Also, can Rust detect and warn when such feature would be missing on target platform and compiled program won't run?

**Comment by petrochenkov** [comment]
@techtonik 
>is it possible to to use software emulation for missing features on development machines?

Sure, there's an issue about this: https://github.com/rust-lang/rust/issues/26654
Unfortunately no one had enough motivation to implement the emulation so far.
There were attempts though - https://github.com/rust-lang/rust/pull/27036, you can try to resurrect that PR if you need XP/Vista support.
RFC 1632 (https://github.com/rust-lang/rfcs/pull/1632) worked the problem around by not using Windows API calls at all for synchronization primitives, but it was rejected.

**Comment by nagisa** [comment]
> is it possible to to use software emulation for missing features on development machines?

It would certainly be possible to switch out our use of SetThreadErrorMode with [SetErrorMode](https://msdn.microsoft.com/en-us/library/windows/desktop/ms680621(v=vs.85).aspx), but I’m pretty sure there’s more cases like this, many of which are not as trivially solved.

> Also, can Rust detect and warn when such feature would be missing on target platform and compiled program won't run?

Everything is possible, but not necessarily feasible. At the moment targetting Windows does not differentiate between you targetting Windows XP and Windows 10. Compiled code is the same. A number of user facing changes would be necessary to implement something like that and we’ve very consciously claimed only [Tier 3 support](https://forge.rust-lang.org/platform-support.html) for libstd only on XP.

**Comment by retep998** [comment]
@nagisa Choosing which version of Windows you want to target could actually be done by telling winapi which version you want, and then it informs downstream dependencies of that choice https://github.com/rust-lang/cargo/issues/2980. Of course it doesn't work too well for std at the moment but in a future where something like https://github.com/rust-lang/rfcs/pull/1133 has been implemented it could even cover that.

**Comment by techtonik** [comment]
> It would certainly be possible to switch out our use of SetThreadErrorMode with SetErrorMode, but I’m pretty sure there’s more cases like this, many of which are not as trivially solved.

Is there any attempt to collect and document those issues for learning and making consensus?

**Comment by Amanieu** [comment]
The problem here is that it's LLVM that requires at least Windows 7 to run, rather than the Rust compiler itself.

Note that this only applies to rustc: most Rust programs will run fine on Windows XP and above (barring some issues with locking, which is a separate issue).

**Comment by techtonik** [comment]
So is there an issue in LLVM that can be referenced from here?

**Comment by Amanieu** [comment]
Not that I know of. Dropping support for older versions of Windows was an explicit decision from the LLVM developers. See http://llvm.org/releases/3.8.1/docs/ReleaseNotes.html.

**Comment by Mark-Simulacrum** [comment]
I don't believe there's anything we can do about this, but I may be wrong. Perhaps @retep998 could comment? I feel like we should close this...

**Comment by retep998** [comment]
If LLVM has decided to not support running on Windows Vista, then there is nothing we can do here. If rustc ever supports an alternate backend that does support Windows Vista, then this can be reconsidered then.
