### ISSUE TITLE
rustc-builtins: use the target *specification* (rather than its triple) in build.rs

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#35474]
follow up of #35021 

`rustc-builtins`' `build.rs` uses `$TARGET` to decide which intrinsics to compile. This won't work well with custom targets because these targets can have arbitrary triples (e.g. `cortex-m0`) that don't reflect the actual target specification (ARM architecture, no OS, etc). To make `rustc-builtins` more robust we should use the target specification (`target_arch`, `target_os`, etc) instead of the triple. This will improve `rustc-builtins`'s support of custom targets and should simplify its `build.rs` logic: `if spec.target_arch == "arm"` instead of `if target.starts_with("arm") || target.starts_with("thumb")`.

There's no standard mechanism to access the target specification from a build script but we could use an external crate like @nagisa's [target_build_utils](https://crates.io/crates/target_build_utils).

cc @alexcrichton @brson

**Comment by nagisa** [comment]
I was planning to write an RFC on the topic of built-in and custom targets overall. I’ll try to get to it once I finish my other in-progress stuff.

**Comment by alexcrichton** [comment]
Would certainly be nice to have! This logic should probably all live in gcc-rs anyway, and I wouldn't mind piling on more parsing/configuration to that crate, but if @nagisa's got an RFC along these lines sounds good to me to wait for that as well

**Comment by japaric** [comment]
TIL: `rustc --print cfg` is a thing. We could use that.

**Comment by brson** [comment]
`rustc --print cfg` seems fine.

**Comment by Mark-Simulacrum** [comment]
From https://github.com/rust-lang/rust/pull/36512#issuecomment-258009942, I believe this has landed "upstream" in the compiler-builtins repo, so I'm going to close this issue since it's not really tracking anything. For those interested, https://github.com/rust-lang-nursery/compiler-builtins/issues/66 is probably the best place to watch.
