### ISSUE TITLE
port the "autoref-arg" code used in overloaded operators to use the ptr adjustment table

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#3548]
We have this nice table in the tcx called `adjustments` that's supposed to track when an expression is being auto-ref'd or auto-deref'd.  It would make borrowck, trans, and other pieces of code that are concerned with this "just work".  But it's not being used for overloaded operators right now.

**Comment by steveklabnik** [comment]
Triage: this seems to be about deep compiler stuff that's probably gone by now. Is that true, @nikomatsakis ?

**Comment by nikomatsakis** [comment]
Sadly it is not gone by now. But it's also a long standing bug that is not that important, MIR makes it even less relevant.

**Comment by eddyb** [comment]
For the record, this is currently handled in [`rustc_mir::hair::cx::expr`](https://github.com/rust-lang/rust/blob/ae23e65eb8f207d0c9be82e7f2043d98a32d4f57/src/librustc_mir/hair/cx/expr.rs#L979-L1004) for [comparison binops](https://github.com/rust-lang/rust/blob/ae23e65eb8f207d0c9be82e7f2043d98a32d4f57/src/librustc/hir/mod.rs#L763-L784) and [deref](https://github.com/rust-lang/rust/blob/ae23e65eb8f207d0c9be82e7f2043d98a32d4f57/src/librustc/hir/mod.rs#L808-L814).

**Comment by nikomatsakis** [comment]
@eddyb maybe we should just close this? I feel like it'll be fixed "in passing" at some point, but I'm not sure that keeping the bug open is very valuable.

**Comment by eddyb** [comment]
Agreed, the only realistic way this may happen if HAIR is output from typeck.

**Comment by eddyb** [comment]
Turns out that it's not that hard of a change, so I'm doing it as minor cleanup in a future PR.
