### ISSUE TITLE
Inlining breaks LLDB expression evaluator

### ISSUE THREAD

**Issue by vadimcn** [rust-lang/rust#35487]
Compile this code with `-Copt-level=0`:

``` rust

#[inline(never)]
fn zzz() {}

#[inline(always)]
fn inlined_fn() {
    let a = 1;
    zzz(); // #break
}

fn main() {
    inlined_fn();
}
```

In LLDB, set a breakpoint on line 8, then run the program.
After breaking, type `print a`'.    Result: 

```
error: use of undeclared identifier 'a'
error: 1 error parsing expression
```

Interestingly, the `frame variable` command shows the expected value: `(int) a = 1`.

Meta: 
LLDB version: lldb-360.1.25 (OSX XCode 8)
Rustc version: rustc 1.10.0 (cfcb716cf 2016-07-03) x86_64-apple-darwin

**Comment by vadimcn** [comment]
Note: this is very likely an LLDB bug, because the equivalent C++ code exhibits the same behavior.
```c++
__attribute__((noinline))
void zzz() {}

__attribute__((always_inline))
void inlined_fn() { 
    {
    int a = 1;
    zzz(); // #break
    }
}

int main() {
    inlined_fn();
    return 0;
}
```
The extra lexical scope in `inlined_fn` is important - without it, evaluation produces the correct result: `(int) $0 = 1`

GDB works correctly.

**Comment by michaelwoerister** [comment]
That makes me sad `:(`

**Comment by Mark-Simulacrum** [comment]
So if this is an LLDB bug, then it seems like there's no use in us tracking it. As such, I'm going to close.
