### ISSUE TITLE
rustdoc generates playpen links with incorrect indentation

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#35483]
Steps to reproduce:
1. https://doc.rust-lang.org/std/env/fn.args.html
2. Click on "Run" in the example block

Playpen opens up with this code snippet:

``` rust
fn main() {
    use std::env;

// Prints each argument on a separate line
for argument in env::args() {
    println!("{}", argument);
}
}
```

It _should_ instead open up with this snippet:

``` rust
fn main() {
    use std::env;

    // Prints each argument on a separate line
    for argument in env::args() {
        println!("{}", argument);
    }
}
```

**Comment by durka** [comment]
Introduced sometime between 1.9.0 and 1.10.0.

**Comment by ollie27** [comment]
This was caused by #33512 which fixed #25944. There is an open PR about this: #35012.

**Comment by kzys** [comment]
Note that #35012 has been closed without merging the change. Meanwhile Playground is showing the snippet like below now;

```
#![allow(unused)]
fn main() {
use std::env;

// Prints each argument on a separate line
for argument in env::args() {
    println!("{}", argument);
}
}
```

**Comment by kzys** [comment]
As @alexcrichton wrote on #35012, indenting Rust code without parsing would change the meaning of the code. So, can we fix the issue without parsing (or parsing Rust code for indentation is worthwhile?)

**Comment by QuietMisdreavus** [comment]
Current status: The code that goes into playground links is generated by the same code that generates doctests, so any change to fix this issue will also affect doctests. Coincidentally enough, thanks to https://github.com/rust-lang/rust/pull/54861 we run the full libsyntax parser on doctests now, so if there's a way to match items back to their place in the original string we can try to mess with the indentation that way.

**Comment by fmease** [comment]
This now works correctly
