### ISSUE TITLE
Panic in libtest 

### ISSUE THREAD

**Issue by svark** [rust-lang/rust#35490]
Panic in libtest

I tried this command:

`cargo test -no-run
`
I expected that cargo or rustc identify that the option -no-run provided is unknown.
(as per @alexcrichton this needs fixing in rustc)
Instead, this happened:

Running exe_name
 thread 'main' panicked at '"Unrecognized option: \'n\'."', ../src/libtest/lib.rs:246
## Meta

`rustc --version --verbose`:
rustc 1.12.0-nightly (b5ad2779e 2016-07-16)
binary: rustc
commit-hash: b5ad2779ea155f6a1b2b61415bc804dcbb23400c
commit-date: 2016-07-16
host: i686-pc-windows-gnu
release: 1.12.0-nightly
Backtrace:
stack backtrace:

**Comment by bvinc** [comment]
This is caused by docopt/docopt.rs#137.  -no-test is being interpreted as a positional argument which cargo passes to the test program.  The test program panics if it sees unexpected options.

**Comment by svark** [comment]
It looks like this is fixed now.

Tested with

rustc 1.17.0-nightly (0648517fa 2017-02-03)
binary: rustc
commit-hash: 0648517faf1e2cf37c8b6770cbd0180a816ed9a0
commit-date: 2017-02-03
host: i686-pc-windows-msvc
release: 1.17.0-nightly
LLVM version: 3.9
