### ISSUE TITLE
E0004 bonus update: spans can't cross nodes

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang/rust#35529]
From https://github.com/rust-lang/rust/pull/35485

After talking with @arielb1 (and seeing @nrc's comments) - let's actually change the span to be one we can do safely:

From:

```
match x {
^^^^^^^ pattern `HastaLaVistaBaby` not covered
```

To:

```
match x {
      ^ pattern `HastaLaVistaBaby` not covered
```

CC: @KiChjang

**Comment by KiChjang** [comment]
Okay, this should be a simple fix, I'm taking it.

**Comment by arielb1** [comment]
I have a mega-pr #35308 that includes it.

**Comment by arielb1** [comment]
Still, I find spanning the scrutinee is a bit odd. But spanning the whole `match` isn't so pretty, so...

**Comment by KiChjang** [comment]
Commented on your PR.
