### ISSUE TITLE
LLVM assertion failure with moving boxed DST

### ISSUE THREAD

**Issue by apasel422** [rust-lang/rust#35546]
The following successfully typechecks on `rustc 1.12.0-nightly (b30eff7ba 2016-08-05)`, but generates an LLVM assertion failure:

```rust
struct Node<T: ?Sized + Send> {
    next: Option<Box<Node<Send>>>,
    value: T,
}

fn clear(head: &mut Option<Box<Node<Send>>>) {
    while let Some(node) = head.take() {
        *head = node.next;
    }
}

fn main() {}
```
Error:
```
rustc: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/lib/IR/Instructions.cpp:263: void llvm::CallInst::init(llvm::FunctionType*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::ArrayRef<llvm::OperandBundleDefT<llvm::Value*> >, const llvm::Twine&): Assertion `(i >= FTy->getNumParams() || FTy->getParamType(i) == Args[i]->getType()) && "Calling a function with a bad signature!"' failed.
```
Note that replacing `*head = node.next` with `*head = node.next.take()` (and making `node` mutable) allows compilation to succeed.

**Comment by TimNN** [comment]
First occurs in nightly-2016-08-03 which turns on mir by default, does not occur on nightly-2016-08-03 with -Z orbit=off.

**Comment by TimNN** [comment]
Using `-Z orbit` this was introduced between `nightly-2016-06-05` and `nightly-2016-06-06` ([Changes](http://github.com/rust-lang/rust/compare/12238b984...1c975eafa)).

**Comment by nikomatsakis** [comment]
Problem seems to be that we call the `drop` with a fat pointer as 2 arguments, but it expects a pointer to a tuple.

**Comment by nikomatsakis** [comment]
I have a fix for this, running the full `make check` locally now to see if I broke anything else on the way.
