### ISSUE TITLE
incr. comp.: Don't compute HIR hash values twice

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#35549]
When loading the dependency graph during incremental compilation, we already have to compute the ICH of most (or all?) HIR nodes in the current codebase. These hashes could be cached instead of calculating them again later when saving the dep-graph back out.

cc @nikomatsakis

**Comment by nikomatsakis** [comment]
One quite note: It's not clear to me that caching this is better...but it probably is. Using more memory tends to not cost that much in terms of running time, ultimately.

**Comment by nikomatsakis** [comment]
It turns out that fixing this bug would also fix #35593 -- that is caused by the fact that typeck rewrites the result of name resolution in place, and hence the name resolution hashes after typeck are different than the ones from before. =(
