### ISSUE TITLE
Consider not running the verifier in non-debug builds

### ISSUE THREAD

**Issue by pcwalton** [rust-lang/rust#3554]
The LLVM verifier is the second slowest pass after LiveIRVariables (2.4%/2.085 s). It's unnecessary and rarely catches stuff that the assertions don't. We should only run it in debug rustc builds.

**Comment by steveklabnik** [comment]
Triage:

### -Z time-llvm-passes 2>&1 | grep "Module Verifier"

```
   0.1400 (  9.3%)   0.0360 ( 12.5%)   0.1760 (  9.8%)   0.1131 (  6.5%)  Module Verifier
   0.0640 (  4.2%)   0.0120 (  4.2%)   0.0760 (  4.2%)   0.0726 (  4.2%)  Module Verifier
   0.0680 (  4.5%)   0.0040 (  1.4%)   0.0720 (  4.0%)   0.0712 (  4.1%)  Module Verifier

```

### -O -Z time-llvm-passes 2>&1| grep "Module Verifier"

```
   0.1240 (  1.1%)   0.0040 (  1.4%)   0.1280 (  1.2%)   0.1158 (  1.0%)  Module Verifier
   0.0560 (  0.5%)   0.0000 (  0.0%)   0.0560 (  0.5%)   0.0609 (  0.5%)  Module Verifier
   0.0440 (  0.4%)   0.0000 (  0.0%)   0.0440 (  0.4%)   0.0499 (  0.4%)  Module Verifier
```

tested with wtftw, takes 17s total on my machine

**Comment by brson** [comment]
It's a small improvement. Still doesn't seem worth turning it off to me. Are we ever going to want to turn off the LLVM module verifier? Can we close this issue?

cc @rust-lang/compiler

**Comment by brson** [comment]
You snooze you lose!
