### ISSUE TITLE
Type alias of type instance of generic tuple struct can't be used interchangably with a tuple struct of this type

### ISSUE THREAD

**Issue by fkjogu** [rust-lang/rust#35545]
Having a type alias to a specific type instance of a generic tuple struct, does not behave like a non generic tuple struct of this type. For example
```rust
struct Foo<T>(T);

type Bar = Foo<i32>;

fn main() {
    let a = Bar(42); //Error
}
```
gives

```
error[E0425]: unresolved name `Bar`
 --> <anon>:6:13
  |
6 |     let a = Bar(42);
  |             ^^^

error: aborting due to previous error
```

I expected `Bar` to be identically to `struct Bar(i32)`.

Rustc version: `rustc 1.12.0-nightly (b30eff7ba 2016-08-05)`.

See https://is.gd/6Qr4P6 for a playbook.

**Comment by TimNN** [comment]
This does not work even without generic parameters:

```rust
struct Foo(i32);

type Bar = Foo;

fn main() {
    let a = Bar(42); //~ ERROR  unresolved name `Bar`
}
```

This is a duplicate of #17422 which was closed:

Basically, as far as I understand the situation, `Bar(42)` basically looks for a "function" (constructor) called `Bar` however `Bar` in only a type (these are two separate namespaces). See also [this comment](https://github.com/rust-lang/rust/issues/4508#issuecomment-48074635), linked from the duplicate issue.

**Comment by fkjogu** [comment]
Oh, did not find the other issue for some reason. Thx. Closing this.
