### ISSUE TITLE
Improve `std::collections`

### ISSUE THREAD

**Issue by RustPowers** [rust-lang/rust#35551]
1. Move `std::vec` to the module `std::collections`. Why? He's taken out of context. Directly hardly anyone uses `std::vec` module. In addition, the `Vec` object is re-exported with `std::preluge`, so the breaking is small.
2. Remove re-exports in `std::collections` and add `std::collections::preluge`. (Similar to the module `std::io::preluge`)

**Comment by apasel422** [comment]
1. Please see #34944.
2. Removing the re-exports would be a breaking change.

**Comment by brson** [comment]
Thanks for the report but these changes have been discussed before and are not going to be made.
