### ISSUE TITLE
ICE: inlinable function call in a function with debug info must have a !dbg location

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#35566]
Happens at stage 1 during rustc bootstrap with enabled debug info and MIR on Windows/GNU.

```
./configure --enable-debug --enable-optimize
make rustc-stage1 VERBOSE=1
```

Result:

```
CFG_LLVM_LINKAGE_FILE=/home/we/rust/x86_64-pc-windows-gnu/rt/llvmdeps.rs PATH=/home/we/rust/x86_64-pc-windows-gnu/stage1/bin:/home/we/rust/x86_64-pc-windows-gnu/llvm/lib:$PATH   x86_64-pc-windows-gnu/stage1/bin/rustc.exe --cfg stage1  -O --cfg rtopt -C debug-assertions=on -g -C rpath -C prefer-dynamic --target=x86_64-pc-windows-gnu   -L "x86_64-pc-windows-gnu/rt" -L native="C:/msys64/home/we/rust/x86_64-pc-windows-gnu/llvm/lib"     --out-dir x86_64-pc-windows-gnu/stage1/lib/rustlib/x86_64-pc-windows-gnu/lib -C extra-filename=-f53fb285 -C metadata=f53fb285 src/libpanic_unwind/lib.rs
inlinable function call in a function with debug info must have a !dbg location
  call void @rust_eh_unwind_resume(i8* %7)
LLVM ERROR: Broken function found, compilation aborted!
make: *** [/home/we/rust/mk/target.mk:216: x86_64-pc-windows-gnu/stage1/lib/rustlib/x86_64-pc-windows-gnu/lib/stamp.panic_unwind] Error 1
```

This looks very similar to https://github.com/rust-lang/rust/pull/35141
cc @eddyb @nagisa

**Comment by petrochenkov** [comment]
I investigated this a bit, but without much success.
This is a Windows specific problem (`custom_unwind_resume == true`) happening when the compiled crate contains definition of lang item `eh_unwind_resume` (`lang_items.eh_unwind_resume().is_some()`), basically only `libpanic_unwind`.
cc @vadimcn @alexcrichton maybe you have ideas how to fix this

**Comment by eddyb** [comment]
@petrochenkov The problem is [this line](https://github.com/rust-lang/rust/blob/3c5a0fa45b5e2786b6e64e27f48cd129e7aefdbd/src/librustc_trans/base.rs#L1101), called from [MIR trans](https://github.com/rust-lang/rust/blob/3c5a0fa45b5e2786b6e64e27f48cd129e7aefdbd/src/librustc_trans/mir/block.rs#L122). The fix is to move this to the call and use the `Builder` API instead of `bcx.with_block`, to get the correct debuginfo applied.

Sorry for not looking into this sooner, #35764 was a priority - we can to start getting rid of *all* `with_block` calls after it lands, and even move the smaller remaining pieces of old trans to `Builder`, too.

**Comment by est31** [comment]
Sadly, still not fixed yet. Ran into this when wanting to debug strange behaviour on Windows, where printf based debugging actually changed behaviour.

**Comment by est31** [comment]
@petrochenkov 's workaround of tagging with `#[no_debug]` worked for me as well.

**Comment by eddyb** [comment]
It fell through the cracks again, I ended up working solely on higher-up parts of the compiler.
cc @Mark-Simulacrum Want to take on a small trans rewrite?

**Comment by segevfiner** [comment]
I just tried building master and encountered this issue. 😕

**Comment by eddyb** [comment]
@segevfiner It's because the beta doesn't have the fix. Try building stage1 libstd without debuginfo then use `--keep-stage 0` always with `x.py` so the beta compiler is not used, and only then enable debuginfo.

**Comment by cengizIO** [comment]
I just hit on this with my tree on 089682611f055ca6315e2229e5ed29be3d2b41c8 while building `stage1` `libstd` with debuginfo on MSYS2 Windows.

I guess I should use windows only for gaming.
