### ISSUE TITLE
Comparing &str against &'static str works, but &std::string::String against &'static str fails

### ISSUE THREAD

**Issue by ljedrz** [rust-lang/rust#35572]
I'm not sure this is an issue, it might just be unintuitive or undocumented.

Consider the following code:
```rust
enum Color {
    Black,
    White
}

impl Color {
    fn new(input: &str) -> Result<Color, &str> {
        match input {
            "black" => Ok(Color::Black),
            "white" => Ok(Color::White),
            _ => Err("invalid color")
        }
    }
}
```
It works nicely; however, when I applied a method to the input value that turned it to a ```String``` and prefixed it with a ```&``` expecting it to behave like ```&str```, the ```match``` no longer works and the following code:
```rust
impl Color {
    fn new(input: &str) -> Result<Color, &str> {
        match &input.to_lowercase() {
            "black" => Ok(Color::Black),
            "white" => Ok(Color::White),
            _ => Err("invalid color")
        }
    }
}
```
returns the following error:
```rust
test.rs:17:13: 17:20 error: mismatched types [E0308]
test.rs:17             "black" => Ok(Color::Black),
                       ^~~~~~~
test.rs:17:13: 17:20 help: run `rustc --explain E0308` to see a detailed explanation
test.rs:17:13: 17:20 note: expected type `&std::string::String`
test.rs:17:13: 17:20 note:    found type `&'static str`
```
Is this expected? I know there are easy workarounds as applying ```as_ref()``` or ```as_str()```, but I think this behavior is at least unintuitive.

**Comment by steveklabnik** [comment]
I believe this is expected, and not one of the areas that `Deref` coercion kicks in. But I'm not sure.

**Comment by Mark-Simulacrum** [comment]
I think this is the same as the issues described here: #28606.

**Comment by ljedrz** [comment]
Yes, this is indeed a duplicate; I'll close this one, then.
