### ISSUE TITLE
ICE - trait lifetime polymorphism + associated type

### ISSUE THREAD

**Issue by idupree** [rust-lang/rust#35570]
```
trait Trait1<T> {}
trait Trait2<'a> {
  type Ty;
}
fn ice(param: Box<for <'a> Trait1<<() as Trait2<'a>>::Ty>>) {}
fn main() {}
```

stable: `error: internal compiler error: ../src/librustc_trans/debuginfo/metadata.rs:306: get_unique_type_id_of_type() - unexpected type: <() as Trait2<'static>>::Ty`

nightly: `thread 'rustc' panicked at 'assertion failed: ty.is_normalized_for_trans()', ../src/librustc_trans/collector.rs:534`

The stable version's ICE error message also appears in nightly if I write a transmute inside ice():

```
use std::mem;
fn ice(param: Box<for <'a> Trait1<<() as Trait2<'a>>::Ty>>) {
  let e: (usize, usize) = unsafe{mem::transmute(param)};
}
```

(This came up while trying to find ways to convince Rust that two complicated type expressions are the same type. I got this ICE, simplified here.)

**Comment by TimNN** [comment]
cc #36381

**Comment by talchas** [comment]
A related one that fails with get_unique_type_id_of_type in both cases:

```rust
trait Lifetime<'a> {
    type Out;
}
impl<'a> Lifetime<'a> for () {
    type Out = &'a ();
}
fn foo<'a>(x: &'a ()) -> <() as Lifetime<'a>>::Out {
    x
}

fn takes_lifetime(f: for<'a> fn(&'a ()) -> <() as Lifetime<'a>>::Out) {
}
fn main() {
    takes_lifetime(foo);
}
```

Replacing the explicit fn() with a desired F: for<'a> FnOnce... gives the problematic errors reported in #34430 (at least it doesn't ICE in that case!).

Also apparently this is a regression somewhat, as it doesn't crash on 1.10 (and https://is.gd/NOhNNU doesn't error, etc)

**Comment by Mark-Simulacrum** [comment]
Neither example ICEs today. E-needstest.
