### ISSUE TITLE
E0164 should be smarter

### ISSUE THREAD

**Issue by wesleywiser** [rust-lang/rust#35583]
``` rust
enum A {
  B { c: i32 }
}

fn main() {
  let b = A::B { c: 1 };

  match b {
    A::B(1) => "uh oh",
    _ => ""
  };
}
```

results in 

```
error[E0164]: `A::B` does not name a tuple variant or a tuple struct
 --> <anon>:9:5
  |
9 |     A::B(1) => "uh oh",
  |     ^^^^^^^
```

There should be a `note` or `hint` saying that user need to use the struct matching syntax (`A::B { c: 1 }`). When I first read the error, I thought I had mistyped the name or forgotten to import it. 

This might be a duplicate of #35377.

**Comment by estebank** [comment]
I believe the [current output](https://is.gd/aS0s3G) addresses this issue:

```rust
error[E0532]: expected tuple struct/variant, found struct variant `A::B`
 --> <anon>:9:5
  |
9 |     A::B(1) => "uh oh",
  |     ^^^^ did you mean `A::B { /* fields */ }`?
```
