### ISSUE TITLE
Box<Error> leads to confusing error message since 'static isn't visible in user code

### ISSUE THREAD

**Issue by viraptor** [rust-lang/rust#35580]
I've got the following code (this is the smallest I could get it to):

```
use std::error::Error;

struct SomeStruct;

#[derive(Debug)]
enum SomeError<'a> {
    Something(&'a str),
    Other,
}

fn do_stuff(doc: &usize) -> Result<SomeStruct, SomeError> {
    Ok(SomeStruct)
}

fn get_things() -> Result<SomeStruct, Box<Error>> {
    let res = try!(Err(SomeError::Other));
    Ok(try!(do_stuff(&res)))
}

fn main() {
    let _ = get_things();
}

impl<'a> std::fmt::Display for SomeError<'a> {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> Result<(), std::fmt::Error> {
        write!(f, "blah")
    }
}
impl<'a> Error for SomeError<'a> {
    fn description(&self) -> &str { "blah" }
}
```

Which reports about `do_stuff(&res)`: "reference must be valid for the static lifetime..." but it never says why. With some extra code, the error actually shows extra information that `expected std::result::Result<SomeStruct, Box<std::error::Error + 'static>>, found std::result::Result<SomeStruct, Box<std::error::Error>>`, which helps (shows that the `Err` needs to be static), but doesn't explain why is that required. The `+ 'static` doesn't exist in the source and it only pops up randomly in the error message.

I would expect at least the type mismatch to be always printed. And possibly some explanation why did the `'static` lifetime appear in it.

**Comment by viraptor** [comment]
Apparently this doesn't even have to be a `'static`, but is just an effect of compiler adding the default lifetime, which makes the error even more cryptic. See https://stackoverflow.com/questions/38884989/where-did-the-static-lifetime-come-from/38885733#38885733

**Comment by Mark-Simulacrum** [comment]
Updated title. Today's error is really bad, I think, since it doesn't mention the return type or `Box` in any way, which is where the heart of the issue lies, I believe.

```
error: `res` does not live long enough
  --> ./test.rs:17:23
   |
17 |     Ok(try!(do_stuff(&res)))
   |                       ^^^ does not live long enough
18 | }
   | - borrowed value only lives until here
   |
   = note: borrowed value must be valid for the static lifetime...
```

**Comment by Mark-Simulacrum** [comment]
Pulled this into https://github.com/rust-lang/rust/issues/43531. Closing, thanks!
