### ISSUE TITLE
Introduce `as_slice`/`as_mut_slice` methods on `std::vec::IntoIter` struct.

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#35601]
Tracking issue for: https://github.com/rust-lang/rust/pull/35447

**Comment by SimonSapin** [comment]
I’ve wanted to use this today, but I’ll probably have to change my code to work differently.

FCP to stabilize?

**Comment by SimonSapin** [comment]
For context: this code is using `vec::IntoIter<syn::TokenTree>` as parser input.

For more context: I’m attempting to replace a compiler plugin (for a procedural expression-macro) by a build script that parses the source file for a Rust module with the `syn` crate, walks the AST to find invocations of this macro, and replace them with the expansion. `Vec<TokenTree>` is used to represent the "arguments" of a macro invocation.

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

Neat methods!
