### ISSUE TITLE
[MIR tests] error could be better than “ran out of MIR”

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#35604]
> ran out of mir dump output to match against

is what the test runner reports when any sort of error happens (missing file, mismatched line(s), etc). Doesn’t help out writing tests at all.

**Comment by Mark-Simulacrum** [comment]
Error looks more comprehensive today: https://github.com/rust-lang/rust/blob/978d2cfee1ee9da704c960c8047e978a7003b582/src/tools/compiletest/src/runtest.rs#L2351, closing.
