### ISSUE TITLE
Incorrect lifetime suggested in diagnostics help message

### ISSUE THREAD

**Issue by viraptor** [rust-lang/rust#35619]
I got the following suggestion for correcting error:

```
help: consider using an explicit lifetime parameter as shown: fn string_by_path<'a, 'b>(doc: &'a Json, path: &'b [&'b str])
 -> Result<String, Box<Error+ 'c>>
  --> src/main.rs:16:1
   |
16 | fn string_by_path<'a,'b,'c>(doc: &'a Json, path: &'b [&'b str]) -> Result<String, Box<Error + 'c>> {
   | ^
```

But (irrelevant if this is going towards better solution or not) the suggestion is clearly illegal, because it's missing `'c` which exists in the return type.

**Comment by brson** [comment]
I agree that incorrect help suggestions are terrible and we should try much harder not to make them. I changed the title to be more about this specif message though since ISTM that "never suggest obviously illegal solutions" is quite a tall order. Let's solve this one!

cc @jonathandturner bogus help is super counterproductive.

**Comment by nikomatsakis** [comment]
So this particular problem appears to be that we are failing to check trait object bounds, which didn't exist at the time this code was implemented. But there are also deeper problems with this check -- for example, it doesn't consider the possibility `'a: 'b`-style where-clauses. There are probably a number of fixes that could be done here.

**Comment by nikomatsakis** [comment]
triage: P-medium

**Comment by arielb1** [comment]
@brson 

`I-wrong` is only for wrong-codegen issues.

**Comment by brson** [comment]
@arielb1 I don't know how you come to this conclusion, but codegen is only one of Rust's many functions, and many of them can be "wrong". Which I-tag do you think applies here?

**Comment by arielb1** [comment]
The compiler team was using I-wrong for bugs where the compiler silently emits wrong code. I suppose that silent standard library breakage also counts.

Diagnostic problems are just `A-diagnostics`.

**Comment by leodasvacas** [comment]
Explicit lifetime suggestions where removed, this is fixed.

**Comment by steveklabnik** [comment]
Specifically, removed in https://github.com/rust-lang/rust/pull/37057
