### ISSUE TITLE
'debug-opt' builds are timing out while building librustc

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#35628]
See
https://buildbot.rust-lang.org/builders/auto-linux-64-debug-opt/builds/3453
https://buildbot.rust-lang.org/builders/auto-linux-64-debug-opt/builds/3454
https://buildbot.rust-lang.org/builders/auto-linux-64-debug-opt/builds/3455
and probably a few more.

**Comment by brson** [comment]
Can this crate legitimately be taking 30 minutes to build? http://perf.rust-lang.org/ says bootstrap time has gotten ... 92% better. wtf

**Comment by Mark-Simulacrum** [comment]
Well, the new numbers show only 0.1% decrease, I suspect that the 92% was noise from the LLVM problems.

**Comment by eddyb** [comment]
@brson I have tried debug-opt locally and there's no such large measurable time difference, although rustbuild may have different behavior here.

**Comment by alexcrichton** [comment]
Haven't seen these in awhile, increase in timeout seems to have fixed it.
