### ISSUE TITLE
Link for different titles is broken in books/README.md

### ISSUE THREAD

**Issue by ashu01** [rust-lang/rust#35629]
Links in file https://github.com/rust-lang/rust/blob/master/src/doc/book/README.md are broken.
* [Getting started][gs] - Set up your computer for Rust development.
* [Tutorial: Guessing Game][gg] - Learn some Rust with a small project.
* [Syntax and Semantics][ss] - Each bit of Rust, broken down into small chunks.
* [Effective Rust][er] - Higher-level concepts for writing excellent Rust code.
* [Nightly Rust][nr] - Cutting-edge features that aren’t in stable builds yet.
* [Glossary][gl] - A reference of terms used in the book.
* [Bibliography][bi] - Background on Rust's influences, papers about Rust.

 The above links in the mentioned file generates Error code 404.

**Comment by ahmedcharles** [comment]
This is not intended to be read on github.com directly, but instead, it's meant to be built into html which is either included into a tarball for distribution or for hosting, like it is here: https://doc.rust-lang.org/book/README.html

I.e. this is by design, not a bug.

**Comment by Mark-Simulacrum** [comment]
Should this be closed, since it's by design/not really fixable?

**Comment by steveklabnik** [comment]
Yes. Thank you for reporting, but this is not fixable.
