### ISSUE TITLE
In the current book, recommend rustup.rs over rustup.sh

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/rust#35653]
Specifically at https://doc.rust-lang.org/book/getting-started.html#installing-on-linux-or-mac, and recommend rustup.rs for Windows too, right?

We've [switched the new book to do this already](https://github.com/rust-lang/book/commit/8af84e7514be2a3aa72e3a421925cf68cb73f342), but in the meantime, the old book should recommend the new recommended toolchain :)

If it's too soon to do this because rustup.rs isn't stable enough yet, consider this a reminder issue to make this change once it is :)

**Comment by steveklabnik** [comment]
@brson wants to wait a bit, and we'd need to then make sure to update the website in sync (see https://github.com/rust-lang/rust-www/issues/478)

**Comment by est31** [comment]
Maybe the big red warning "this is beta software" should be removed from the https://rustup.rs website?

**Comment by frewsxcv** [comment]
This will be fixed by https://github.com/rust-lang/rust/issues/38122.
