### ISSUE TITLE
Fragment specifiers in macro are not taken into account

### ISSUE THREAD

**Issue by GuillaumeLestringant** [rust-lang/rust#35650]
Here is a minimum example of the problem.

``` rust
macro_rules! size    {
    ($ty:ty) => {
        std::mem::size_of::<$ty>()
    };
    ($size:tt) => {
        $size
    };
}

fn main()   {
    println!("{}", size!(u32));
    println!("{}", size!(4));
}
```

Compilation fails with following error.

> temp.rs:12:26: 12:27 error: expected type, found `4` 
> temp.rs:12     println!("{}", size!(4));

Which means that the fragment qualifier is not taken into account to choose which variant of the macro is to be used.

**Comment by durka** [comment]
Yeah, macros don't do backtracking. You'll need to adjust the matchers to provide some other way to disambiguate.

**Comment by GuillaumeLestringant** [comment]
Yes, I *obviously* know that I could just put brackets or whatever around one of the patterns to make it distinct. But the whole point of having fragment qualifiers is *precisely* to distinguish between two otherwise identical patterns. If macros cannot do it although they have the perfect tool for it, then they are stupid and ought to be improved.

**Comment by durka** [comment]
It wasn't obvious to me that you knew the workaround -- sorry for assuming!

Also see #33840.

**Comment by GuillaumeLestringant** [comment]
Thanks for pointing the PR. It is blocked for now, but I suppose there is still hope.

Sorry for being harsh. I have been raging for months over how annoyingly limited and stupid Rust macros are, and I finally found a case general and obvious enough to justify my complaining…

**Comment by Mark-Simulacrum** [comment]
triage: Macros still don't backtrack. I can't find an issue for that, though I do suspect that one exists in some form. Labeling as A-macros, though.

**Comment by durka** [comment]
@Mark-Simulacrum here is [one](https://github.com/rust-lang/rust/issues/26444) (closed).

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/42838 -- macro rules do not backtrack.
