### ISSUE TITLE
Provide a macro like std::file!() just for the function name

### ISSUE THREAD

**Issue by sdroege** [rust-lang/rust#35651]
Having such a macro would be useful for adding context information to logs.

**Comment by insaneinside** [comment]
1.  Macros are currently not namespaced.
2.  What would this macro do that [`file!`](https://doc.rust-lang.org/std/macro.file!.html) does not?

**Comment by Aatch** [comment]
This requires an RFC, as there's a fair bit of ambiguity as to what the "name" of a function might be.

**Comment by JustAPerson** [comment]
Whatever name is generated for debug symbols might be a start. When looking in gdb, those seem unambiguous after monomorphisation etc.

**Comment by steveklabnik** [comment]
Yes, new macros need to go through the RFC process, even for relatively trivial ones. See https://github.com/rust-lang/rfcs/pull/1653 as an example. @sdroege please file one if you're interested in pursuing this!

**Comment by sdroege** [comment]
Thanks, I'll look into that!
