### ISSUE TITLE
Compiler is overly eager to build following file lock wait

### ISSUE THREAD

**Issue by talexand** [rust-lang/rust#35658]
## Steps to reproduce

1. Run emacs? (It makes and deletes autosave files in the same directories as working file buffers, which may help trigger it.)
  - `flycheck-rust` may be a contributor.
2. Iterate over a file and `cargo test` immediately after saving. Success if you see "waiting for file lock" in build output.
3. Observe that build process can't actually get the crate referenced properly (as below).

### Workaround

1. Sigh at below output.
2. `cargo test` again without touching any files.
3. Observe usual passing tests.

## Error log

An example from a project I'm working on:

```
$ cargo test
    Blocking waiting for file lock on build directory
   Compiling wd40 v0.1.0 (file:///Users/talex/git/starfighter/wd40)
    Finished debug [unoptimized + debuginfo] target(s) in 14.0 secs
     Running target/debug/deps/wd40-f757f6198b80f6ed

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

   Doc-tests wd40

running 11 tests
test account::orders_0 ... FAILED
test game::start_level_0 ... FAILED
test account::place_order_0 ... FAILED
test account::stock_orders_0 ... FAILED
test heartbeat_0 ... FAILED
test stock::order_cancel_0 ... FAILED
test stock::last_quote_0 ... FAILED
test stock::order_status_0 ... FAILED
test venue::heartbeat_0 ... FAILED
test venue::stocks_0 ... FAILED
test stock::orderbook_0 ... FAILED

failures:

---- account::orders_0 stdout ----
	error: extern location for wd40 does not exist: /Users/talex/git/starfighter/wd40/target/debug/deps/libwd40.rlib
<anon>:1:1: 1:19 error: can't find crate for `wd40` [E0463]
<anon>:1 extern crate wd40;
         ^~~~~~~~~~~~~~~~~~
error: aborting due to 2 previous errors
thread 'account::orders_0' panicked at 'Box<Any>', ../src/librustc_errors/lib.rs:674
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'account::orders_0' panicked at 'couldn't compile the test', ../src/librustdoc/test.rs:287

---- game::start_level_0 stdout ----
	error: extern location for wd40 does not exist: /Users/talex/git/starfighter/wd40/target/debug/deps/libwd40.rlib
<anon>:1:1: 1:19 error: can't find crate for `wd40` [E0463]
<anon>:1 extern crate wd40;
         ^~~~~~~~~~~~~~~~~~
error: aborting due to 2 previous errors
thread 'game::start_level_0' panicked at 'Box<Any>', ../src/librustc_errors/lib.rs:674
thread 'game::start_level_0' panicked at 'couldn't compile the test', ../src/librustdoc/test.rs:287

TRUNCATED
```

## Meta

- Rust: rustc 1.12.0-nightly (28ce3e8a5 2016-08-01)
- OS: Latest OSX

**Comment by Aatch** [comment]
I think this might be a cargo bug, not a compiler one. @rust-lang/tools, care to confirm?

**Comment by tomjakubowski** [comment]
I've observed this same bug on nightly but not beta or stable. It tends to crop up if you're running flycheck-rust and also using `M-x compile` or similar to build your project.

**Comment by talexand** [comment]
Good point. I do have flycheck running, which presumably is collecting build error output to do its job.

**Comment by alexcrichton** [comment]
Yes Cargo doesn't hold locks on the output directory while tests are running, which can cause this problem. I also believe that this is a Cargo bug rather than a rustc bug, so may be most appropriate to reopen against rust-lang/cargo

**Comment by talexand** [comment]
Migrated.
