### ISSUE TITLE
Suggest using the enum when a variant is used as a type

### ISSUE THREAD

**Issue by Wilfred** [rust-lang/rust#35675]
Consider the code:

``` rust
enum Fruit {
    Apple(i64),
    Orange(i64),
}

fn should_return_fruit() -> Apple {
    Apple(5)
}
```

The current error wording is:

```
error[E0412]: type name `Apple` is undefined or not in scope
 --> <anon>:7:29
  |
7 | fn should_return_fruit() -> Apple {
  |                             ^^^^^ undefined or not in scope
  |
  = help: no candidates by the name of `Apple` found in your project; maybe you misspelled the name or forgot to import an external crate?
```

I periodically make this exact mistake. It would be really nice if rustc could spot this error and say `did you mean Fruit?`

**Comment by Aatch** [comment]
I'm not sure about your exact case, but I think such a suggestion for this:

```rust
enum Fruit {
    Apple(i64),
    Orange(i64),
}

fn should_return_fruit() -> Fruit::Apple {
    Fruit::Apple(5)
}
```

Or, more likely, this:

```rust
use Fruit::*;
enum Fruit {
    Apple(i64),
    Orange(i64),
}

fn should_return_fruit() -> Apple {
    Apple(5)
}
```

Makes sense, and likely isn't too hard to implement.

**Comment by retep998** [comment]
>Or, more likely, this:
```Rust
use Fruit::*;
enum Fruit {
    Apple(i64),
    Orange(i64),
}
>
fn should_return_fruit() -> Apple {
    Apple(5)
}
```
@Aatch I'm pretty sure that is invalid because `Apple` isn't a type and cannot be specified as the return type for `should_return_fruit`.

**Comment by Aatch** [comment]
@retep998 that's the point. I meant that suggestion should work in those cases, but not the original example, as `Apple` isn't in scope.

By "more likely", I meant that it's more likely to come up than the first example.

**Comment by sanxiyn** [comment]
@Aatch's example gives this error, which seems good to me:

```
error[E0248]: found value `Fruit::Apple` used as a type
 --> 35675.rs:8:29
  |
8 | fn should_return_fruit() -> Apple {
  |                             ^^^^^ value used as a type
```

That is, different errors are given depending on whether name is in scope.
