### ISSUE TITLE
rustdoc: remove macro redirects

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#35705]
PR #35234 changed macro URLs to remove the `!`. It left redirects in so as not to break existing URLs. At some point, we should remove these redirects so as not to accumulate too much cruft. Obviously this will require some message before we do so.

See FIXME in render.rs

**Comment by ollie27** [comment]
Personally I don't see much reason to ever remove the redirects. For example I would expect https://doc.rust-lang.org/std/macro.assert!.html to continue to work basically forever,

**Comment by Mark-Simulacrum** [comment]
Nominating for discussion. It's been almost two years; I think we should consider this issue again.

**Comment by QuietMisdreavus** [comment]
@rust-lang/rustdoc, what do you think?

I personally don't see the harm in keeping it. Do we have crates with many more macros than the standard library, where having these redirect pages is a problem? I'm with @ollie27, keeping the link alive is more important to me than removing these small files from the output.

**Comment by GuillaumeGomez** [comment]
I don't know why it'd cause issues so ok for me.

**Comment by QuietMisdreavus** [comment]
Based on the rousing discussion here, I think the consensus can be described as "it's okay to keep them around". Before i close this issue, though, we should remove the FIXME that it refers to:

https://github.com/rust-lang/rust/blob/12ed235adc62e63b16bb4f715b143c37a5efa00d/src/librustdoc/html/render.rs#L1969-L1978

Just to keep things neat.

**Comment by QuietMisdreavus** [comment]
A PR to remove that comment is live at https://github.com/rust-lang/rust/pull/52510.
