### ISSUE TITLE
rust-gdb starts with error on nightly

### ISSUE THREAD

**Issue by ereichert** [rust-lang/rust#35724]
This may be related to 

https://github.com/rust-lang/rust/pull/35585
https://github.com/rust-lang/rust/issues/35155

Tried to run rust-gdb for the first time in a while so I'm not sure when this started.

nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.12.0-nightly (197be89f3 2016-08-15)

rust-gdb --args target/debug/tlx ~/Downloads/moviesample/trailer.mp4
GNU gdb (GDB) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from target/debug/tlx...done.
Traceback (most recent call last):
  File "/root/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/etc/gdb_load_rust_pretty_printers.py", line 11, in <module>
    import gdb_rust_pretty_printing
  File "/root/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/etc/gdb_rust_pretty_printing.py", line 19, in <module>
    if sys.version_info.major >= 3:
AttributeError: 'tuple' object has no attribute 'major'
(gdb) 

Works on stable however:

stable-x86_64-unknown-linux-gnu unchanged - rustc 1.10.0 (cfcb716cf 2016-07-03)

rust-gdb --args target/debug/tlx ~/Downloads/moviesample/trailer.mp4
GNU gdb (GDB) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from target/debug/tlx...done.
(gdb)

**Comment by michaelwoerister** [comment]
Can you try opening `/root/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/etc/gdb_rust_pretty_printing.py` and changing the `if sys.version_info.major >= 3:` to `if sys.version_info[0] >= 3:`? That should be compatible with more versions of Python.

**Comment by ereichert** [comment]
Is that request still applicable if I'm using rustup instead of multirust?

**Comment by michaelwoerister** [comment]
Yes, I just copied the path from your error report above, so that should be the correct one.

**Comment by ereichert** [comment]
Ignore that last comment.  I see that rustup uses .multirust.

Same result however.

rust-gdb --args target/debug/tlx ~/Downloads/moviesample/trailer.mp4
GNU gdb (GDB) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from target/debug/tlx...done.
Traceback (most recent call last):
  File "/root/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/etc/gdb_load_rust_pretty_printers.py", line 11, in <module>
    import gdb_rust_pretty_printing
  File "/root/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/etc/gdb_rust_pretty_printing.py", line 19, in <module>
    if sys.version_info.major[0] >= 3:
AttributeError: 'tuple' object has no attribute 'major'
(gdb)

**Comment by ereichert** [comment]
Sorry.  I see the problem.

**Comment by ereichert** [comment]
That did the job.

rust-gdb --args target/debug/tlx ~/Downloads/moviesample/trailer.mp4
GNU gdb (GDB) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from target/debug/tlx...done.
(gdb)

**Comment by michaelwoerister** [comment]
Excellent `:)` Thanks for your help! I'll make a PR with the fix.

**Comment by ereichert** [comment]
Thanks
