### ISSUE TITLE
A puzzled “[E0283]: type annotations required” error

### ISSUE THREAD

**Issue by sickHamm** [rust-lang/rust#35738]
maybe a type inference (or trait bound check) bug for array; 
```
#![feature(collections_bound)]
#![feature(collections)]
#![feature(btree_range)]

use std::collections::BTreeMap;
use std::collections::Bound::{Included, Excluded, Unbounded};
use std::collections::btree_map::Range;

type ID = [u8; 20];
// [u8; 20] impl Ord
#[derive(Ord, Eq, PartialOrd, PartialEq)]
struct NID([u8; 20]);

trait Foo<K, V> {
    fn foo(&self, key :&K);
}

// // Error
impl<V> Foo<[u8; 20], V> for  BTreeMap<[u8; 20], V> {
    fn foo(&self, key: &[u8; 20]) {
        let range: Range<[u8; 20], V> = Self::range(self, Unbounded, Included(key));
    }
}

// // // Work
// impl<K, V> Foo<K, V> for  BTreeMap<K, V>
//     where K: Ord{
//     fn foo(&self, key: &K) {
//         let range: Range<K, V> = Self::range(self, Unbounded, Included(key));
//     }
// }

// impl<V> Foo<u8, V> for  BTreeMap<u8, V> {
//     fn foo(&self, key: &u8) {
//         let range: Range<u8, V> = Self::range(self, Unbounded, Included(key));
//     }
// }
```

**Comment by TimNN** [comment]
The following works (requires `#![feature(type_ascription)]`):

```rust
impl<V> Foo<[u8; 20], V> for  BTreeMap<[u8; 20], V> {
    fn foo<'a>(&self, key: &'a [u8; 20]) {
        let range: Range<[u8; 20], V> = Self::range(self, Unbounded: Bound<&'a [u8; 20]>, Included(key));
    }
}
```

So apparently the compiler is having troubles inferring the correct type for the `Unbounded` in this specific case.

**Comment by sickHamm** [comment]
@TimNN  thank your workaround

**Comment by jonas-schievink** [comment]
No need to use type ascription:

```rust
impl<V> Foo<[u8; 20], V> for  BTreeMap<[u8; 20], V> {
    fn foo<'a>(&self, key: &'a [u8; 20]) {
        let range: Range<[u8; 20], V> = Self::range(self, Unbounded::<&'a [u8; 20]>, Included(key));
    }
}
```

**Comment by jonas-schievink** [comment]
Regarding the actual issue, I don't think that's a bug. The signature of `BTreeMap::range` looks like this:
```rust
fn range<Min: ?Sized + Ord, Max: ?Sized + Ord>(&self, min: Bound<&Min>, max: Bound<&Max>) -> Range<K, V> where K: Borrow<Min> + Borrow<Max>
```

`K` is `[u8; 20]` in this impl. There are two `K: Borrow` impls in the standard library that could apply:

```rust
impl<T> Borrow<T> for T where T: ?Sized
impl<T> Borrow<[T]> for [T; 20]
```

I believe this is just the compiler telling you that it doesn't know which one to use.

**Comment by TimNN** [comment]
@jonas-schievink: A, thanks, I didn't remember that syntax.

**Comment by sickHamm** [comment]
@jonas-schievink  I don't think this relevant to `Borrow`， this is error message `type annotations required: cannot resolve '_: std::cmp::Ord``.  
I agree with @TimNN

> compiler is having troubles inferring the correct type for the Unbounded 

because `Unbounded` unlike `Included(T)` has a general  a parameter, but this problem is
the type inference system has inconsistent behavior for T, u8, [u8; 20].

**Comment by TimNN** [comment]
@sickHamm, I think @jonas-schievink is correct:

* The compiler knows that `K = [u8; 20]`
* Now it must determine the exact type of `Unbound`, that means it must find some type for `Min` such that:
    1. `Unbound: Bound<&Min>` and
    2. `K: Borrow<Min>` or with `K` substituted: `[u8; 20]: Borrow<Min>`
* (i) is fulfilled for *all* types
* So the only constrained remaining for `Min` is (ii): `[u8; 20]: Borrow<Min>`.
* As @jonas-schievink mentioned the compiler has two choices here (and does not know which is the correct one):
    1. `Min = [u8; 20]` due to `impl<T> Borrow<T> for T where T: ?Sized`
    2. `Min = [u8]` due to `impl<T> Borrow<[T]> for [T; 20]`

The last point is the crucial difference between `T`, `u8`, `[u8; 20]`:
* For `T` and `u8` there is only one `Borrow` implementation, thus the compiler can infer the type of `Min`.
* For `[u8; 20]` there are two `Borrow` implementations, the compiler does not know which of these to choose, and so cannot infer the type of `Min`.

**Comment by sickHamm** [comment]
@TimNN  Yes,  I'm wrong, Thank you  very much for detailed explanation. improve my understanding for rust's type inference.

**Comment by sickHamm** [comment]
BTW: This syntax ` Unbounded::<&'a [u8; 20]>` is have a special term ? Where I can learn more about this.
