### ISSUE TITLE
Create a Rust actor library with high-level patterns, recovery, networking, sandboxing

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#3573]
Rust has a lot of powerful concurrency tools, but they aren't packaged up into a high-level, consistent interface.

Things that would be great in an actor library:

* High-level help with implementing actor patterns, nice interface, minimal boilerplate
* Cross-process actors with sandboxing. Sandboxing is very important to [Servo], which has some initial sandboxing libraries.
* Network-based messaging and actors
* Reliable failure and recovery schemes. Rust has linked task failure, but no higher-level constructs to help users make use of it for creating reliable systems ala Erlang OTP.

Take inspiration from Scala, Akka and Erlang.

This probably isn't suitable for the main repo, but would be very useful for projects like Servo.

[Servo]: http://github.com/mozilla/servo

**Comment by bandrei** [comment]
I'm considering joining in too. More for the rust learning experience. Let me know if you guys intend to start this.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#613
