### ISSUE TITLE
Generate commented assembly with --emit=asm

### ISSUE THREAD

**Issue by jrmuizel** [rust-lang/rust#35741]
clang -S produces nicely commented .s files. It would be nice if rustc did this too.

e.g. simd shuffles are commented
.loc directives have the corresponding line number comment
        .loc    1 4 25 is_stmt 1        ## test.c:4:25
debug information is commented
        .byte   14                      ## DW_FORM_strp
        .byte   17                      ## DW_AT_low_pc
        .byte   1                       ## DW_FORM_addr
        .byte   18                      ## DW_AT_high_pc
        .byte   1                       ## DW_FORM_addr

**Comment by eddyb** [comment]
There might be a `-C` or `-Z` flag already for this. AFAIK what clang emits comes from LLVM.

**Comment by Mark-Simulacrum** [comment]
This flag is already added, should be usable (issue can be closed?):
`-Z asm-comments -- generate comments into the assembly (may change behavior)`

**Comment by jrmuizel** [comment]
Any reason not to make this the default?

**Comment by Mark-Simulacrum** [comment]
Likely the fact that it may change the behavior (I don't actually know what that means but this seems like a valid assumption).

**Comment by jrmuizel** [comment]
it looks like -Z asm-comments doesn't do this. MCOptions.AsmVerbose must be set to true for the assembler to emit them.

**Comment by Mark-Simulacrum** [comment]
So it looks like -Zasm-comments isn't actually used anywhere based on what I can find in the source... or, rather, its uses are in methods that are themselves never called.

**Comment by jrmuizel** [comment]
Yeah, to get comments I believe I needed to set a verbose flag in some llvm context. Clang does this by default and it would be nice if rustc did too.

**Comment by gnzlbg** [comment]
IIUC without this neither the playground nor godbolt (compiler-explorer) can map assembly to lines of Rust source code.

**Comment by rkruppe** [comment]
Godbolt uses debug info AFAIK? Our debug info isn't always great but in general it's working, isn't it?

**Comment by gnzlbg** [comment]
It seems like they just don't do it much. Godbolt uses `.loc` directives in the assembly file, which rustc seems to generate correctly, sorry for the noise.
