### ISSUE TITLE
Rustdoc tests fail due to htmlparser python dependency

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#35760]
```
Traceback (most recent call last):
  File "/home/nagisa/Documents/rust/rust/src/etc/htmldocck.py", line 113, in <module>
    from HTMLParser import HTMLParser
ImportError: No module named 'HTMLParser'
```

**Comment by jonas-schievink** [comment]
`HTMLParser` seems to be a part of Python 2, and was renamed to `html.parser` in Python 3. I have both Python versions installed, so maybe the build system is using the wrong executable? I'm hitting this with rustbuild, not sure about the old build system.

**Comment by jonas-schievink** [comment]
The old build system [is probing python2 first](https://github.com/rust-lang/rust/blob/master/configure#L749), but it's [not used by rustbuild](https://github.com/rust-lang/rust/blob/master/src/bootstrap/check.rs#L129)

**Comment by euclio** [comment]
Just ran into this. Should probably be tagged with A-rustbuild.
