### ISSUE TITLE
Tracking issue for check methods on Duration

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#35774]
Tracking issue for https://github.com/rust-lang/rfcs/pull/1640

**Comment by eugene-bulkin** [comment]
Has anyone taken this on?

**Comment by alexcrichton** [comment]
@eugene-bulkin it's all yours! (I don't think anyone else is currently working on it)

> What specifically can overflow or fail in div()?

I believe division by 0 is the only thing to worry about here

> Would duration_checked_ops be more appropriate as a feature name?

Certainly! We tend to just pick "whatever name" for library features, we're not too principled about it.

**Comment by eugene-bulkin** [comment]
Cool, I'll toss a PR out within the near future!

**Comment by sfackler** [comment]
@rfcbot fcp merge

Matches conventions

**Comment by aturon** [comment]
:bell: This feature is going into its **final comment period** with disposition to **stabilize**. :bell:
