### ISSUE TITLE
The Book is missing (links to it are broken)

### ISSUE THREAD

**Issue by snej** [rust-lang/rust#35788]
The main documentation page prominently links to The Rust Book at https://doc.rust-lang.org/book/ … unfortunately that link is broken ("Not Found / Looks like you've taken a wrong turn.") The suggested links on the 404 page don't mention the book, only the reference. Where did the book go?

I went to the root URL of that site, https://doc.rust-lang.org, but even that page is missing. Huh?

**Comment by steveklabnik** [comment]
We are about to release 1.11, and so there is a short period of time (a few minutes) where the docs disappear during the deploy process. Hold tight! (and thanks for reporting!)
