### ISSUE TITLE
investigate compile-time regressions from 2016-08-17

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#35805]
We don't really know what caused it, but http://perf.rust-lang.org/ reveals:

- 25% drop on issue-32278-big-array-of-strings

and smaller drops on a number of other tests. Merits investigation.

**Comment by eddyb** [comment]
We have [more accurate stats](https://gist.github.com/Mark-Simulacrum/bc68a236ec2647f4665800363dbd13f4) for the switch to MIR, thanks to @Mark-Simulacrum.

**Comment by eddyb** [comment]
Looking at [this graph](http://perf.rust-lang.org/graphs.html?start=Tue%20Aug%2002%202016%2003%3A05%3A57%20GMT%2B0000%20(UTC)&end=Thu%20Aug%2018%202016%2015%3A54%3A10%20GMT%2B0000%20(UTC)&kind=benchmarks&crates=issue-32278-big-array-of-strings&phases=total&group_by=crate):
* old trans -> MIR trans regression is a false positive
* anomalies on 8/12, 8/14, 8/17 and 8/18 are false positives
 * no commits explain *both* regressions and the reversal of those regressions
* minor increase on 8/14 ([commits](https://github.com/rust-lang/rust/compare/2e29b126b60a19f491e7f1845dd98df50700e37a...1d5b758bab979b1db723bcc97ecd8398127bd8bc)) is from #35409 (added `Storage{Live,Dead}`)
* minor decrease on 8/17 ([commits](https://github.com/rust-lang/rust/compare/9376da6f77e8b7ed204ee704b29e96213b69d0f1...6c0d66af693dc960e042631643b0d76a05a4b9a9)) is from #35605 (more efficient `Generics`/`Substs`)

Everything else appears to be noise (similar on all benchmarks), nothing to do here!
