### ISSUE TITLE
Creating a std::process::Command to run cargo hangs forever

### ISSUE THREAD

**Issue by ssahli** [rust-lang/rust#35816]
The issue seems to be when calling cargo within a cargo instance. I'm running a system test on a compiler plugin we're working on using `cargo test --lib`, and the system test's first lines of code are as follows:

```
Command::new("cargo")
            .arg("clean")
            .arg("-p")
            .arg("rustproof")
            .status()
            .expect("failed to execute child process: cargo clean -p rustproof");
```

I specifically use `RUST_TEST_THREADS=1 cargo test --lib` to ensure no race conditions. The `.status()` in the above `Command` returns:

```
Blocking waiting for file lock on the git checkouts
```

And as expected:

```
test tests::system_tests::test_examples has been running for over 60 seconds
```

This only occurs on nightlies AFTER the following version:

```
rustc 1.12.0-nightly (8787a1233 2016-08-11)
binary: rustc
commit-hash: 8787a12334439d47e931be26fef53381ce337c3a
commit-date: 2016-08-11
host: x86_64-apple-darwin
release: 1.12.0-nightly
```

**Comment by alexcrichton** [comment]
Cargo has its own file locks and such, and it looks like this is just a case of deadlock? I'm not sure if there's an actual bug here unfortunately.

That is, there was a change in Cargo to hold file locks while tests are running (so other processes don't tromp all over the tests), and that's what cause the "breakage" here.

**Comment by arc3x** [comment]
I am working ssahli. 
It is worth noting that this issue happens when part of our project is included via a github link in `Cargo.toml`
```toml
[dependencies]
libsmt = { git = "https://github.com/Rust-Proof/libsmt.rs.git" }
```

This issue evaporates when libsmt is placed in the root of our project and included as:
```toml
[dependencies]
libsmt = { path = "libsmt.rs" }
```

**Comment by alexcrichton** [comment]
@arc3x I think it's the same issue in the sense that this is not a bug. When `cargo test` is run, it holds locks while it's executing tests. If you then run `cargo clean` *inside* of a test, it will try to re-acquire those locks, deadlocking.

The "fix" you're seeing is that some locks are only acquired with git repositories. If you don't have any git repositories there's no need to grab those locks.

**Comment by Mark-Simulacrum** [comment]
So I think there isn't a bug here, and it's certainly not a rust-lang/rust bug. If you're still interested, please file an issue over at rust-lang/cargo. Thanks!
