### ISSUE TITLE
File IO with read_to_end and read_to_string is slower than possible

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#35823]
Rust's current implementation of `read_to_end` will read exponentially larger chunks of the buffer, but only up to 8192. This is slow when reading a greater than 16KB file if counting by syscalls.

NodeJS reads the entire file in one go, making 3 syscalls: open, fstat, read, and close.
Rust currently makes (for the same file) 58 syscalls not counting mmap/madvise which may be circumstantial (not related to IO). Specifically: open, ioctl, read \* 37, mmap, madvise, read \* 18, madvise \* 14, close.

I would expect that functions such as read_to_end and read_to_string would do the minimal work necessary to read the entire file.

The below diff is what it takes to currently get Rust to do 4 syscalls (open, fstat, read, read, close). I think it's reasonable that similar code could be included (perhaps with specialization) in the filesystem reading code.

The difference between the two (with dropping caches):
fast version:

```
real    2m45.157s
user    0m11.484s
sys 0m1.516s
```

current, slower version:

```
real    3m9.654s
user    0m11.580s
sys 0m1.956s
```

``` diff
-            let mut file = File::open(entry.path())?;
-            let mut file_contents = String::new();
+
+            let file = File::open(entry.path())?;
+            let capacity = match file.metadata() {
+                Ok(metadata) => metadata.len(),
+                Err(_) => 0,
+            };
+            let mut reader = BufReader::with_capacity(capacity as usize, file);
+            let mut file_contents = String::with_capacity(capacity as usize);
+            let len = match reader.fill_buf() {
+                Ok(buf) => {
+                    match ::std::str::from_utf8(buf) {
+                        Ok(s) => file_contents.push_str(s),
+                        Err(_) => {
+                            skipped += 1;
+                            continue;
+                        }
+                    };
+                    buf.len()
+                },
+                Err(_) => {
+                    skipped += 1;
+                    continue;
+                }
+            };
+            reader.consume(len);
+            reader.read_to_string(&mut file_contents)?;
+
             // Skip files whose size is 0.
-            if file.read_to_string(&mut file_contents)? == 0 {
+            if file_contents.is_empty() {
```

**Comment by Stebalien** [comment]
I completely agree but we can do better. We can just read directly to the string (given a bit of unsafe code).

**Comment by Mark-Simulacrum** [comment]
The standard library already reads into the underlying `Vec<u8>` buffer of strings and then does a pass to check that the data is valid. That's something that should continue to be done; my point with showing the code above was to demonstrate that it is possible currently, and that including something like what I suggest shouldn't require a massive overhaul of the code which reads to end/string.

**Comment by alexcrichton** [comment]
This has been [proposed before](https://github.com/rust-lang/rust/pull/27159) as well, and I've written up [some concerns about this solution](https://github.com/rust-lang/rust/pull/27159#issuecomment-123038113).

It basically just boils down to the fact that if you expect `read` to only call `read`, this can cause problems. If you want your program to run fast, though, then it's not unexpected but rather desired.

**Comment by Mark-Simulacrum** [comment]
Would it be unreasonable to ask that if a buffer has been pre-allocated to the capacity, the buffer's capacity is used as a heuristic? This requires no extra syscalls. Also, it seems (though I may be wrong here) that this was the behavior before 240734c31e529557583a0dc8e97abf858b4a375d (PR #23847); where the write size no longer used the underlying buffers capacity as a baseline for how much to read.

I feel that while growing the underlying buffer's capacity without bounds isn't a good idea (at least by default); using the existing capacity still makes sense. Namely, if the buffer's capacity is greater than the default buffer size (8KB), then don't allocate more memory (this is already the case). However, if given a buffer with a greater capacity, attempt to read `buf.capacity() - buf.len()` as before, in the original code which introduced faster behavior (ccb4e8423; PR #23820).

Some form of exponential (?) backing off could be implemented if the read returns less than expected.

**Comment by alexcrichton** [comment]
@Mark-Simulacrum hm it should be the case right now that if you have a pre-allocated buffer (via `Vec::with_capacity` or something like that) we should attempt to `read` into the entire buffer. I could imagine that the growing is not proportional after that, but it seems reasonable to change that!

**Comment by Mark-Simulacrum** [comment]
[This](https://github.com/rust-lang/rust/blob/master/src/libstd/io/mod.rs#L345) is the line in the source code for the `read_to_end` (used by both `Read::read_to_string` and `Read::read_to_end`). I see no reference to the capacity, though I may be misreading something.

I can try to get the description I've listed above implemented, though I'm not sure I can run the tests locally with any success (in the past I've seen failures on master, so I suspect something in my environment may be wrong).

**Comment by retep998** [comment]
The current default `read_to_end` appears to simply start with a read of 16 always. https://github.com/rust-lang/rust/blob/b30eff7ba72a78e31acd61a2b6931919a0ad62e8/src/libstd/io/mod.rs#L345-L374

Some types however opt into using `read_to_end_uninitialized` instead however, which reads into the space between `.len()` and `.capacity()` however big it is. https://github.com/rust-lang/rust/blob/e1195c24bb567019d7cdc65bf5a4c642e38475d1/src/libstd/sys/common/io.rs

**Comment by Mark-Simulacrum** [comment]
These are the only uses of read_to_end_unitialized that I could find aside from tests/benchmarks. FileDesc is used by File in src/libstr/sys/unix/fs.rs I think, but I don't understand where `std::fs::File` comes from yet.

Either way, it seems that the capacity-based reading either doesn't currently happen or doesn't happen on Windows.

 - FileDesc - src/libstd/sys/unix/fd.rs:150
 - RawHandle - src/libstd/sys/windows/handle.rs:198
 - Socket - src/libstd/sys/windows/net.rs:250
 - Stdin - src/libstd/sys/windows/stdio.rs:148

**Comment by alexcrichton** [comment]
Yes that's the generic implementation of `read_to_end` but that's not the one that's specialized for files. Both [Windows](https://github.com/rust-lang/rust/blob/413ada30402f823a86a75578afc63d07179f6a23/src/libstd/sys/windows/handle.rs#L198) and [Unix](https://github.com/rust-lang/rust/blob/413ada30402f823a86a75578afc63d07179f6a23/src/libstd/sys/unix/fd.rs#L150) bottom out in [`read_to_end_uninitialized`](https://github.com/rust-lang/rust/blob/413ada30402f823a86a75578afc63d07179f6a23/src/libstd/sys/common/io.rs#L26) which reads [up to the vector's capacity](https://github.com/rust-lang/rust/blob/413ada30402f823a86a75578afc63d07179f6a23/src/libstd/sys/common/io.rs#L42-L43).

**Comment by Mark-Simulacrum** [comment]
Hmm, I'm not sure I'm doing this right, but with the code below and debugging in gdb, I'm hitting the read_to_end helper function, not the read_to_end_unitialized. So.. not sure what's going on here. I'm on unix (Ubuntu 16.04)...
```rust
let mut file = File::open(entry.path())?;
let mut file_contents = String::new();
file.read_to_string(&mut file_contents).unwrap();
```

**Comment by alexcrichton** [comment]
Oh looks like the implementation of `read_to_string` [calls the `read_to_end` helper](https://github.com/rust-lang/rust/blob/f883b0bbab6c433eb7b7042b605b4339022c563a/src/libstd/io/mod.rs#L568) rather than `self.read_to_end`. We can probably trivially fix that and have `read_to_string` benefit in the same way that `read_to_end` does!

**Comment by Mark-Simulacrum** [comment]
I don't believe there's much more to do here, so I'm going to close. Benchmarks seemed to indicate this wasn't actually a win.
