### ISSUE TITLE
rust-src package is corrupt

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#35840]
For some reason the manifest.in file is empty.

cc @Diggsey

**Comment by Diggsey** [comment]
If I run `make dist` locally, the source package is fine :confused: (although the manifest could be simplified by using bulk dirs). Will investigate further...

**Comment by Diggsey** [comment]
So far I've determined that it only fails on linux.

**Comment by Diggsey** [comment]
Ah I've tracked down the problem: rust-lang/rust-installer#47

While it's technically a bug in rust-installer, we should probably be using bulk-dirs for the source anyway, and that will fix the problem by shortening the manifest.
