### ISSUE TITLE
我能够把Rust语言的标准库文档翻译成中文版本吗？

### ISSUE THREAD

**Issue by 3442853561** [rust-lang/rust#35865]
我能够把Rust语言的标准库文档翻译成中文版本吗？
May I translat the standard library documents into Chinese?
https://www.gitbook.com/book/3442853561/ruststd_chinese

**Comment by arielb1** [comment]
This is all Chinese to me. Please write in English.

**Comment by nagisa** [comment]
The standard library documentation has the same license (MIT or Apache 2.0) as the code it documents, so you may change (translate) and distribute the changed (translated) version however you wish.

**Comment by 3442853561** [comment]
@arielb1 I want to translat standard library documents into Chinese,for Chinese people and programers read.

**Comment by 3442853561** [comment]
@nagisa Thank you very much.非常感谢

**Comment by 3442853561** [comment]
I don't know how to use the gitbook ,so I put it on http://doc.oschina.net/ruststd_chinese

**Comment by xen0n** [comment]
My opinions (as a Chinese speaker):

Usually the single biggest problem of documentation translations is *difficulty keeping sync*, so I won't encourage individual *ad-hoc* efforts to do so IMO. Documentation translation is a large and far-reaching topic, only participating in the form of individual issues is not enough. We need to at least form consensus inside the Chinese Rust community on how all of this really should be done, and then go through the RFC process to benefit the whole culturally-diverse Rust community as a whole.

That said, I'm not member of the Rust team, so please take my opinions with a grain of salt. Rust team members are very busy, and they're prioritizing bug-fixing and new features over i18n/l10n goodies (see how rustc is still English-only even internally, and a discussion about this on internals forum). We'd better discuss this inside the Chinese community and produce an RFC first.

**Comment by xen0n** [comment]
I see there may well be people having difficulties with English read the former reply, so here's a Chinese version as well.

因为通常文档翻译项目的最大问题都是**难以保持同步**，所以我个人并不赞同单打独斗的不成体系的此类行为。文档翻译是涉及面很广的宽泛话题，单纯用开 issue 吹风的形式来参与是不够的。我们至少要在中文 Rust 社区内部形成整个流程的共识，然后进入 RFC 流程，这样不仅中文用户需求得到满足，整个多元文化的 Rust 社区也会从中受益。

话虽这么讲，我不是 Rust 团队成员，我的观点不一定非要接受。由于 Rust 团队成员非常忙，bug 修复和新功能开发是优先处理事项，国际化/本地化相比之下优先级较低，比如现在 rustc 内部的文本消息处理还只考虑纯英语，internals 论坛上有关于这个的讨论。所以我们还是先内部讨论出 RFC 比较好。

**Comment by KiChjang** [comment]
《Rust 程式語言》已有部份繁體中文翻譯，可以去https://github.com/askeing/rust-book參考參考。
