### ISSUE TITLE
Improve docs around File and BufReader

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#35875]
Part of https://github.com/rust-lang/rust/issues/29356 and related to https://github.com/rust-lang/rust/issues/29300

Inspired by https://www.reddit.com/r/rust/comments/4yinbt/writing_a_jpeg_decoder_in_rust_part_2/d6obhd8?st=is4wut7k&sh=6d31802c

BufReader's talks about why you'd need it, but it's not super clear from File, which is more likely how people will discover this stuff. We should make sure people using File as a Read understand things here.

**Comment by marti1125** [comment]
Hi @steveklabnik I would like  contribute with this =D

**Comment by steveklabnik** [comment]
@marti1125 awesome! Please let me know if you need any help

**Comment by marti1125** [comment]
Hi @steveklabnik could you give some step how to improve this documentation please

**Comment by steveklabnik** [comment]
Hey @marti1125:

So, the main issue here is explaining in `File`'s docs why you might want to pair the File with `BufReader`. I would approach this in two steps:

1. Mention in File's docs that you might want to combine it with BufReader, and link to Bufreader's docs
2. update BufReader's docs to be a little more clear about what's going on. It's very terse at the moment.

Does that make sense?

**Comment by frewsxcv** [comment]
Opened a PR that addresses this: https://github.com/rust-lang/rust/pull/38443.
