### ISSUE TITLE
Tracking issue for static lifetime in statics (RFC #1623)

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#35897]
Tracking issue for "static lifetime in statics", rust-lang/rfcs#1623, which defaults omitted lifetimes in statics to `'static`.

cc @llogiq

**Comment by nikomatsakis** [comment]
I would be up for mentoring someone in implementing this.

**Comment by llogiq** [comment]
Cool! I'm not sure if I can find the time, but if I do, I'd be glad to code this up.

**Comment by nikomatsakis** [comment]
Here are some pointers into the code:

- first off, for historical reasons, the code often calls lifetimes regions :)
- when a region is elided, that winds up being resolved in `librustc_typeck` by a `RegionScope`, defined in `librustc_typeck/rscope.rs`; in particular the `anon_regions()` method is called to figure out what to do
- currently statics use an `ExplicitRscope`; [this is selected in this code in collect.rs](https://github.com/rust-lang/rust/blob/master/src/librustc_typeck/collect.rs#L1556-L1558), which handles statics and constants
- we would want to switch that to a `ElidableRscope` with default set to `ty::ReStatic`, I think

**Comment by llogiq** [comment]
Great! I think with those pointers I should be able to make *some* progress even with a modest amount of time.

**Comment by nikomatsakis** [comment]
This should not have been closed.

**Comment by nikomatsakis** [comment]
(Until it becomes stable.)

**Comment by llogiq** [comment]
@chriskrycho just a friendly heads-up: Did you get around to documenting this?

**Comment by chriskrycho** [comment]
I did not, but it’s on my list for after-work tasks this week!

**Comment by nikomatsakis** [comment]
@llogiq this is fully implemented at this point, right? I guess we are blocked on some documentation efforts? I'd like to stabilize this change.

**Comment by chriskrycho** [comment]
This was, perhaps ironically given my RFC, blocked on me actually getting around to documenting it. I will aim to document it Monday.

**Comment by nikomatsakis** [comment]
@chriskrycho 

> This was, perhaps ironically given my RFC, blocked on me actually getting around to documenting it. I will aim to document it Monday.

OK :)

**Comment by llogiq** [comment]
I too would love to see this stabilized. Thank you Niko for pushing this forward! Also thank you Chris for caring about the docs.

**Comment by chriskrycho** [comment]
Sorry, didn’t get to this today as I was sick. Tomorrow, tomorrow, tomorrow!

**Comment by llogiq** [comment]
Get well soon!

**Comment by chriskrycho** [comment]
Documentation PR inbound shortly!

**Comment by aturon** [comment]
I'm going to go ahead and nominate for FCP, to kick the process off. Note that actual stabilization is blocked by docs landing, but we can at least start discussing whether to move to FCP (which itself lasts several weeks).

@rfcbot fcp merge

**Comment by llogiq** [comment]
As I commented on #37928, removing the feature gate would very probably make the doc tests pass, thus removing the last hurdle before merging.

It's a bit unfortunate to have this deadlock problem, but perhaps we can learn something from it?

**Comment by chriskrycho** [comment]
Yeah, this is a process thing I didn't see coming in the discussion in https://github.com/rust-lang/rfcs/issues/1636.

**Comment by withoutboats** [comment]
@rfcbot reviewed

**Comment by pnkfelix** [comment]
@rfcbot reviewed

**Comment by est31** [comment]
@rfcbot you are broken! Something is supposed to happen here, no?

**Comment by eddyb** [comment]
I've checked off both of them manually just now, maybe that will do something?

**Comment by nikomatsakis** [comment]
Hmm, cc @dikaiosune :(

**Comment by aturon** [comment]
OK, I'm going to put this into FCP manually.

:bell: **This feature is entering its final comment period for stabilization.** :bell:

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by brson** [comment]
Reopening until this is backported to 1.16.

**Comment by nikomatsakis** [comment]
@brson wait, why are we backporting? We don't normally backport new features and stabilizations, do we? This seems relatively minor.

**Comment by alexcrichton** [comment]
@nikomatsakis would the lang team prefer to not backport? I don't think there's been a definitive answer in either https://github.com/rust-lang/rust/pull/39265 (stabilization PR) or in https://github.com/rust-lang/rust/pull/37928 (doc PR).

I believe @est31 [proposed a backport](https://github.com/rust-lang/rust/pull/39265#issuecomment-277533745) and I tagged it as such b/c of the request, but no answer has been had. 

If the answer is "no", however, then we can denominate and remove from milestones.

**Comment by est31** [comment]
Just note that back when I was proposing the backport, I thought that stabilisations usually do get backported. Didn't know that its usually only done exceptionally.

**Comment by llogiq** [comment]
Given that it's not much code, a backport wouldn't be *that* costly (and probably much appreciated :smile:).

But I'm also fine with waiting for 1.17 if there are more pressing matters.

**Comment by aturon** [comment]
@alexcrichton I think we should not backport. This is just a normal stabilization and should follow the normal process.

**Comment by alexcrichton** [comment]
Sounds like the backport isn't gonna happen, so I'm going to remove beta-nominated from the PRs and un-milestone this issue.

**Comment by alexcrichton** [comment]
Er, also re-close this issue

**Comment by golddranks** [comment]
@brson, this feature is still mentioned in release notes, even though it didn't land.
