### ISSUE TITLE
nonsense help message for stray `=>`

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#35907]
Code:

```rust
if true => { }
```

Output:

```
error: expected `{`, found `=>`
 --> expr.rs:5:10
  |
5 | if true => { }
  |         ^^
  |
  = help: place this code inside a block
```

"Place this code inside a block" doesn't make any sense here.

**Comment by Aatch** [comment]
It's there to catch this:

```rust
if (foo)
   bar;
```

But the way it's implemented means that if we get something that isn't a block, we say to put it in a block. We might be able try parsing an expression, and show the help only if that works.
