### ISSUE TITLE
`make` hangs on macOS 10.12 using homebrew

### ISSUE THREAD

**Issue by silverwind** [rust-lang/rust#35938]
It seems the homebrew package of `rustc` (1.11.0 in my case) is unable to compile on the latest macOS Sierra beta. `make` did hang for 12 hours at pretty much full CPU usage for me after which I had to kill the process.

````
==> Upgrading rust
==> Using the sandbox
==> Downloading https://static.rust-lang.org/dist/rustc-1.11.0-src.tar.gz
Already downloaded: /Users/silverwind/Library/Caches/Homebrew/rust-1.11.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/rust/1.11.0 --enable-clang --release-channel=stable
==> make
````
No additional output is seen, I assume `brew` suppresses it.

XCode Version 8.0 beta 6 (8S201h)
macOS 10.12 (16A304a)

 Possibly related: https://github.com/rust-lang/rust/issues/34741

**Comment by alexcrichton** [comment]
The 1.11.0 compiler bootstraps from the 1.10.0 compiler, which is [known to fail](https://github.com/rust-lang/rust/pull/34719) on OSX 10.12. We've backported the fix to 1.11.0 so the compilers we ship should work, but otherwise this is an unfortunate case where 1.11.0 won't be able to bootstrap on OSX 10.12.

**Comment by silverwind** [comment]
I've just compiled successfully off master, so I assume it's just a matter of homebrew updating their version, right?

**Comment by alexcrichton** [comment]
Yeah the master branch is bootstrapping from the 1.12.0 beta, which has a fix for OSX 10.12

**Comment by silverwind** [comment]
Alright, will wait for 1.12 before updating again :)

**Comment by nathantsoi** [comment]
any updates? this is still failing for me

**Comment by concept47** [comment]
My problem is worse. I login to my console and it just hangs ... no prompt.

At fault is a rustc process that looks like this on further inspection

    cwd
    /Users/xxxx
    txt
    /usr/local/Cellar/rust/1.3.0/bin/rustc
    txt
    /usr/local/Cellar/rust/1.3.0/lib/librustc_driver-198068b3.dylib
    txt
    /usr/local/Cellar/rust/1.3.0/lib/librustc_trans-198068b3.dylib
    txt
    /usr/local/Cellar/rust/1.3.0/lib/librustc_privacy-198068b3.dylib
    txt
    /usr/local/Cellar/rust/1.3.0/lib/librustc_borrowck-198068b3.dylib
    txt
    /usr/local/Cellar/rust/1.3.0/lib/librustc_resolve-198068b3.dylib
    txt
    /usr/local/Cellar/rust/1.3.0/lib/librustc_lint-198068b3.dylib
    txt
    /usr/local/Cellar/rust/1.3.0/lib/librustc_typeck-198068b3.dylib
    txt
    /usr/local/Cellar/rust/1.3.0/lib/librustc-198068b3.dylib
    txt
    /usr/local/Cellar/rust/1.3.0/lib/libflate-198068b3.dylib
    txt
    /usr/local/Cellar/rust/1.3.0/lib/librustc_data_structures-198068b3.dylib
    txt
    /usr/local/Cellar/rust/1.3.0/lib/libarena-198068b3.dylib
    txt
    /usr/local/Cellar/rust/1.3.0/lib/libgraphviz-198068b3.dylib
    txt
    /usr/local/Cellar/rust/1.3.0/lib/libgetopts-198068b3.dylib
    txt
    /usr/local/Cellar/rust/1.3.0/lib/librbml-198068b3.dylib
    txt
    /usr/local/Cellar/rust/1.3.0/lib/librustc_back-198068b3.dylib
    txt
    /usr/local/Cellar/rust/1.3.0/lib/libsyntax-198068b3.dylib
    txt
    /usr/local/Cellar/rust/1.3.0/lib/libserialize-198068b3.dylib
    txt
    /usr/local/Cellar/rust/1.3.0/lib/libterm-198068b3.dylib
    txt
    /usr/local/Cellar/rust/1.3.0/lib/liblog-198068b3.dylib
    txt
    /usr/local/Cellar/rust/1.3.0/lib/libfmt_macros-198068b3.dylib
    txt
    /usr/local/Cellar/rust/1.3.0/lib/librustc_llvm-198068b3.dylib
    txt
    /usr/local/Cellar/rust/1.3.0/lib/libstd-198068b3.dylib
    txt
    /usr/lib/dyld
    txt
    /private/var/db/dyld/dyld_shared_cache_x86_64h
    0
    1
    ->0xe3735ee23421397b
    2
    ->0xe3735ee2342137fb
    3
    ->0xe3735ee230950d2b


Any idea whats going on?

Just upgraded to 10.12, from 10.11.

**Comment by concept47** [comment]
Had to navigate to the /usr/local/Cellar/rust folder and rename it, then kill the `rustc` process

removed rust from my system just to be safe.
