### ISSUE TITLE
"cannot assign to immutable field" could be confusing

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#35937]
``` rust
struct S { x: i32 }
let s = S { x: 42 };
s.x += 1; //~ERROR cannot assign to immutable field
```

It occurred to me that this might be confusing to newcomers because fields don't have mutability in Rust, instead we have inherited mutability. So maybe it should say "cannot assign to field of immutable struct" or "cannot modify field due to immutable binding" or something.

cf #18150

**Comment by eddyb** [comment]
cc @jonathandturner

**Comment by Zoxc** [comment]
I got this error now:
```
error: cannot assign to immutable field
   --> C:\Users\John\Documents\rust-co\coroutines\future\src\lib.rs:128:21
    |
128 |                     self.timers[i].delta -= 1;
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
```
Where `self` is `&mut EventLoop` which means I don't know the real cause of the error.

From:
https://github.com/Zoxc/coroutines/blob/e25d2b66a8cae8b03440ed4fdd2d32408fd71735/future/src/lib.rs#L128

**Comment by eddyb** [comment]
@Zoxc My guess would be missing `DerefMut` or `IndexMut` impl.

@nikomatsakis @jonathandturner We should print the first element of the lvalue that causes the whole lvalue to be immutable only, either an immutable variable, reference or overloaded deref/indexing.

**Comment by Zoxc** [comment]
@eddyb I forgot I changed `timers` to `Vec<Rc<Timer>>`

**Comment by eddyb** [comment]
Then the error message should contain "...because `Rc<Timer>` implements `Deref` but not `DerefMut`".

**Comment by nikomatsakis** [comment]
@eddyb 

> @nikomatsakis @jonathandturner We should print the first element of the lvalue that causes the whole lvalue to be immutable only, either an immutable variable, reference or overloaded deref/indexing.

I was working with @caipre on a PR to do this at some point, but I think they lost steam. It was a bit trickier than I at first thought. In any case, there is an issue specific to this problem: https://github.com/rust-lang/rust/issues/28419

**Comment by caipre** [comment]
Yeah, sorry about that. 😞 The issue turned out to be rather more difficult than I anticipated and I got caught up with some things where I wasn't able to put time into it any longer. If someone has a good idea of how to resolve that issue, I don't want to be a blocker.

**Comment by durka** [comment]
IMO this was not closed by #40767. The [note that was added](https://github.com/rust-lang/rust/pull/40841/files#diff-444a718daba0145d2c923b41ed9cee37R1) (suggesting a change to the struct binding) is helpful, but the error still says "immutable field" which implies that individual fields can be mutable.

**Comment by nikomatsakis** [comment]
@durka I am inclined to agree. I'd like us to be less specific in many of these messages, since I think they imply things that are not true.

**Comment by estebank** [comment]
Current output:

```
error[E0594]: cannot assign to field `s.x` of immutable binding
 --> src/main.rs:4:1
  |
3 | let s = S { x: 42 };
  |     - consider changing this to `mut s`
4 | s.x += 1;
  | ^^^^^^^^ cannot mutably borrow field of immutable binding
```

**Comment by durka** [comment]
LGTM.
