### ISSUE TITLE
mem::replace and mem::swap say they don't copy, but they do

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#35935]
`mem::replace`:

> Replaces the value at a mutable location with a new one, returning the old value, without deinitializing or copying either one.

`mem::swap`:

> Swap the values at two mutable locations of the same type, without deinitializing or copying either one.

However, `replace` calls `swap` which uses `copy_nonoverlapping`, making the docs technically false. Should it say "without cloning" or "without deep-copying" instead?

**Comment by rkruppe** [comment]
It *moves*. Moves are in the end implemented by copying bytes, but that's not what "copy" means in most Rust contexts.

**Comment by bluss** [comment]
They don't copy in Rust semantics, but we should rewrite them to talk about move semantics, which will make it easier for everyone to understand.

These functions are not unsafe or tricky or anything, so we really don't need to reassure users about how they work (they will obey Rust's regular rules, of course)?

`replace`

> Move out the value at a mutable location and return it, and move the new value in to replace it.

`swap`

> Swap the values at two mutable locations.

Not sure what to even say about swap. Maybe

>  Each value is moved to the other's location.

**Comment by brson** [comment]
All that needs to happen here is update docs per @bluss.

**Comment by durka** [comment]
Yeah I wasn't saying the implementations had any problem.

**Comment by kmcallister** [comment]
I also changed this wording in #36357.

**Comment by steveklabnik** [comment]
Thanks to @kmcallister 's work, giving this a close.
