### ISSUE TITLE
Formatting regression in Crates and Modules chapter

### ISSUE THREAD

**Issue by caipre** [rust-lang/rust#35942]
The markdown seems fine, but the gitbook isn't rendering correctly:
![screen shot 2016-08-23 at 13 50 34](https://cloud.githubusercontent.com/assets/295094/17903222/a5bba362-6938-11e6-9178-b4eb9800df60.png)

https://doc.rust-lang.org/book/crates-and-modules.html

**Comment by durka** [comment]
Just a missing linebreak. Fixed by #35466 but since these are the most public docs (and an oft-linked chapter) maybe we can get that fast-tracked to the stable site somehow? cc @steveklabnik

**Comment by caipre** [comment]
Oh, sorry -- I saw that change in the history and assumed it was what I was seeing at doc.rust-lang.org. Nightly renders correctly: https://doc.rust-lang.org/nightly/book/crates-and-modules.html

**Comment by steveklabnik** [comment]
There's not a way to fast-track to stable; we'd have to release a whole new point release, and we only do for really, really egregious things. This isn't great, but it's only for a short while. Closing as "already fixed". Thanks for reporting though, @caipre !
