### ISSUE TITLE
support code such as `fn(x: !) -> ! { x }` with #![feature(never_type)]

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#35940]
This kind of code worked with the original implementation of `#![feature(never_type)]`, but that's because the check for diverging functions that converge was removed from liveness. With that restored, it incorrectly fires here.

@eddyb believes the fix involves:

```
<eddyb> and if you want to fix it *separately*, basically have a check like that that
        changes succ to be self.s.exit_ln if there's a NeverToAny adjustment for that
        expression, here https://github.com/rust-lang/rust/blob/master/src/librustc/middle/liveness.rs#L930
<eddyb> durka42: oh and if you do that separate PR, you can remove the ExprCall and
        ExprMethod call is_never checks
```

cc @canndrew. Discovered during #35883.

**Comment by arielb1** [comment]
You can also skip the check in liveness if the return expression has type `TyNever`.

**Comment by durka** [comment]
@arielb1 isn't that the check that we put back in at #35883? If you don't check you end up with `fn foo() -> ! { 42 }` being accepted.

**Comment by Mark-Simulacrum** [comment]
The below is now accepted. `src/test/run-fail/call-fn-never-arg.rs` tests for this.

```rust
#![feature(never_type)]

fn x(y: !) -> ! { y }
```
