### ISSUE TITLE
TcpListener docs example contains an explicit drop that can never be reached

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#35950]
The `incoming` iterator never returns `None`, so the `drop` at the end will never be reached. The explicit matching against the socket result also seems potentially nonconventional docs-wise?

https://doc.rust-lang.org/std/net/struct.TcpListener.html#examples

**Comment by abonander** [comment]
Also, what are the semantics of this iterator when the listener is set to nonblocking mode? If it's equivalent to `accept()` it should run the loop with `WouldBlock` errors until a connection is made.

**Comment by sfackler** [comment]
That's what it'd do, yeah. The `next` method is super simple: https://doc.rust-lang.org/src/std/up/src/libstd/sys/unix/ext/net.rs.html#532
