### ISSUE TITLE
Can we run with LLVM assertions on the bots?

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#35998]
Probably on the debug builds.

cc @alexcrichton @edunham @jonathandturner

**Comment by alexcrichton** [comment]
I don't know of any particular reason why not. We may have disabled in the past to decrease cycle time, but that's pretty much it.

**Comment by retep998** [comment]
We especially should run with LLVM assertions on the cargobuild bot. https://github.com/rust-lang/rust-buildbot/issues/120

**Comment by nrc** [comment]
we recently had a bug (#35991) which was only exposed by LLVM assertions, so if we have the bot time it would be great to have them turned on in at least some capacity.

**Comment by alexcrichton** [comment]
I had to revert this in https://github.com/rust-lang/rust-buildbot/commit/71b494e52fce494d411a9283cb0c81a65ab68b50 because we've been getting failures on the mac bots looking like:

```
cp: x86_64-apple-darwin/stage1/lib/librustc_typeck
cp: x86_64-apple-darwin/stage1/lib/librustc_trans
cp: x86_64-apple-darwin/stage1/lib/librustc_plugin
cp: x86_64-apple-darwin/stage1/lib/librustc_borrowck
rustc: x86_64-apple-darwin/stage0/lib/rustlib/x86_64-apple-darwin/lib/librustc_driver
cp: x86_64-apple-darwin/stage1/lib/libproc_macro
rustc: x86_64-apple-darwin/stage0/lib/rustlib/x86_64-apple-darwin/bin/rustc
cp: x86_64-apple-darwin/stage1/lib/librustc_driver
cp: x86_64-apple-darwin/stage1/bin/rustc
rustc: x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/libcore
make: *** [x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/stamp.core] Segmentation fault: 11
```

I ran this patch through dev but maybe it regressed recently?

**Comment by alexcrichton** [comment]
Wait no on second thought it may be a stale LLVM build, I'm going to clean the mac bots and try again.

**Comment by alexcrichton** [comment]
Yup was a dirty build directory!

More problems though: https://buildbot.rust-lang.org/builders/auto-linux-cross-opt/builds/3519/steps/compile/logs/stdio

More issues https://github.com/rust-lang/rust/issues/36150
