### ISSUE TITLE
Rustc coerces smart pointer to unsized too eagerly

### ISSUE THREAD

**Issue by plietar** [rust-lang/rust#36007]
Full code: https://is.gd/hZ9nqK

Given a smart pointer, which only works on types implementing the trait `Bar` or on `Bar` trait objects, such that `Pointer<T>` is allowed to coerce to `Pointer<Bar>`, and the corresponding `PartialEq` implementation :

``` rust
trait Bar {}
struct Foo;
impl Bar for Foo {}

struct Pointer<T: ?Sized>
        where T: Bar + Unsize<Bar> {

    value: *mut T,
}

impl <T: ?Sized> CoerceUnsized<Pointer<Bar>> for Pointer<T>
        where T: Bar + Unsize<Bar> {}

impl <T: ?Sized, U: ?Sized> PartialEq<Pointer<U>> for Pointer<T>
        where T: Bar + Unsize<Bar>,
              U: Bar + Unsize<Bar> {

    fn eq(&self, _other: &Pointer<U>) -> bool {
        true
    }
}
```

Applying the `==` operator on two `Pointer<Foo>` will try to coerce them to `Pointer<Bar>`, even though this isn't needed. This is an issue since coercion moves the original pointer.

``` rust
fn cmp(x: Pointer<Foo>, y: Pointer<Foo>) {
    x == y;
    x == y; // use of moved value: `y`
}
```

Removing the `CoerceUnsized` implementation lets the code build, which means that the coercion is not needed.

As @Diggsey [pointed out on reddit](https://www.reddit.com/r/rust/comments/4zm2c6/unsized_coercions_and_operators/d6wyasj), if the `PartialEq` is restricted to pointers with identical types (`PartialEq for Pointer<T>`), then no coercion occurs.

**Comment by bluss** [comment]
Seems related to #31740

**Comment by abonander** [comment]
I've discovered a simpler reproduction: https://is.gd/0OpDXV

```rust
#![feature(coerce_unsized, unsize)]

use std::marker::Unsize;
use std::ops::CoerceUnsized;

struct Foo<T: ?Sized>(Box<T>);

impl<T> CoerceUnsized<Foo<Baz>> for Foo<T> where T: Unsize<Baz> {}

struct Bar;

trait Baz {}

impl Baz for Bar {}

fn main() {
    let foo = Foo(Box::new(Bar));
    let foobar: Foo<Bar> = foo;
}
```

Curiously, when you just do `let foo: Foo<Bar> = Foo(Box::new(Bar));`, there's no problem. The overeager coercion can only occur in the presence of type inference. 

It also only occurs when the `impl CoerceUnsized` is non-parametric, i.e. not written like this:

```rust
impl<T, U: ?Sized> CoerceUnsized<Foo<U>> for Foo<T> where T: Unsize<U> {}
```

Likely because it allows `Foo<Bar>` to coerce to itself. This also explains why it hasn't come up in the stdlib, because no type tries to coerce to a specific unsized type; it's all parametric.

**Comment by Mark-Simulacrum** [comment]
The original code compiles with no errors today, so seems like E-needstest.

**Comment by Mark-Simulacrum** [comment]
I think I tested the wrong thing; not E-needstest.

**Comment by compiler-errors** [comment]
This is fixed but does need a test, though I think it could also be closed without a test, since it's been open for so long there's probably already coverage :thinking:

**Comment by jackh726** [comment]
I think we should add the test just to be sure.
