### ISSUE TITLE
Publish host builds of mips, mipsel, mips64el for Linux

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#36015]
Today we publish target builds for mips and mipsel, and have no support for mips64el. All three of these are or will soon be supported by Debian and Fedora.

- [x] mips
- [x] mipsel
- [ ] mips64el

cc https://github.com/rust-lang/rust/issues/36006#issuecomment-242679364

**Comment by japaric** [comment]
> mips64el

#36024 adds the target definition to the compiler.

**Comment by japaric** [comment]
I managed to produce functional rustcs for the mips and mipsel targets. I've sent the required changes to the rust-buildbot repository (rust-lang/rust-builtbot#121).

**Comment by alexcrichton** [comment]
Just deployed a change for mips/mipsel, we should hopefully have those tomorrow night

**Comment by alexcrichton** [comment]
Ok, added mips64 as well, closing.

**Comment by alexcrichton** [comment]
Complications last night prevented these nightlies from going out, hopefully tonight though!
