### ISSUE TITLE
"multiple dylibs candidates for std" found

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#36022]
[Original report](https://users.rust-lang.org/t/linking-problems-with-1-12-beta1/7001)

> This project links against libssh2, which is installed in /usr/local/, as is the Rust compiler. With Rust 1.11, I needed to add `-rustc-link-search = ["/usr/local/lib"]` in my Cargo config, to make it find libssh2. With Rust 1.12-beta1, this is no longer needed, and if present, causes error E0465.

@csperkins can you share the repo this reproduces with, or provide a reduced test case?

Nominating because this is a beta regression.

**Comment by csperkins** [comment]
Can't duplicate with a clean repo - sorry for the noise. Assuming this was something improperly cleaned, potentially from several releases ago, although can't see what.

**Comment by brson** [comment]
Closing per @csperkins
