### ISSUE TITLE
`incremental/ich_method_call_trait_scope.rs` appears to be failing on windows

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#36020]
https://github.com/rust-lang/rust/pull/36017 disables `ich_method_call_trait_scope` because it has been failing on windows. Reason currently unknown, something to do with I/O errors...

**Comment by nikomatsakis** [comment]
cc @michaelwoerister

**Comment by alexcrichton** [comment]
I believe [this is the diagnosis](https://github.com/rust-lang/rust/pull/36017#issuecomment-242817382), and I don't think we'll need to land the PR after all, so closing.
