### ISSUE TITLE
Rustdoc should preserve order of item declaration by default.

### ISSUE THREAD

**Issue by nixpulvis** [rust-lang/rust#36033]
I'm trying to write code in a specific order for the proposes of reading, and the fact that it sorts them by default alphabetically is not what I want.

At least make it an option, what the default it might be an argument.

**Comment by apasel422** [comment]
Sort of a duplicate of #8552.

**Comment by QuietMisdreavus** [comment]
Current status: Thanks to https://github.com/rust-lang/rust/pull/46787 there is a `--sort-modules-by-appearance` flag that will leave items on module pages in declaration order. The flag is still unstable, but it exists.

**Comment by Dylan-DPC** [comment]
Closing this as it is implemented by #46787
