### ISSUE TITLE
C程式語言中的那個類型更類似常數？

### ISSUE THREAD

**Issue by 3442853561** [rust-lang/rust#36039]
There is some wrong when we translate the book.We have a problem with the type of `const ` .It is more like the type of `const ` in C language or `#define` in C language,or neighter?How can we translate as well as tell the others to learn it?

**Comment by izgzhen** [comment]
```
Constants live for the entire lifetime of a program. More specifically, constants in Rust have no fixed address in memory. This is because they’re effectively inlined to each place that they’re used. 
```

More like `#define` as far as I see.

BTW, I think it is better asked at https://github.com/rust-lang/book/ or the repository where you did the translation ;)

**Comment by Aatch** [comment]
Not sure this is appropriate as an issue here, so I'm going to close it. If there's an issue related to translating the book, then that would be the place to ask this question.
