### ISSUE TITLE
Support `#[derive(Copy, Clone)]` and `#[derive(Clone)]` for unions with `Copy` fields

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#36043]
```
#[derive(Clone)] // OK, both `u8` and `u16` are `Copy`, `clone` is implemented as `memcpy`
union U {
    a: u8,
    b: u16,
}
```

This wasn't implemented in https://github.com/rust-lang/rust/pull/36016 for reasons described in https://github.com/rust-lang/rust/pull/36016#discussion_r76496154
cc https://github.com/rust-lang/rust/issues/32836 https://github.com/rust-lang/rust/pull/31414 @durka

**Comment by durka** [comment]
I knew that hack would come back to bite us :)

We can just remove it if we agree on the policy that all Clone + !Copy
types will eventually be fixed...

**Comment by durka** [comment]
Reproducing @petrochenkov's comment from the union PR:

> There are some difficulties with the current implementation of `#[derive(Clone)]`, it generates pattern matching even for the "shallow clone" case to check bounds, but these patterns are not appropriate for unions, this needs to be done in some other way somehow in some other PR.
> 
>     #[derive(Copy, Clone)]
>     struct S {
>         a: u8,
>         b: u8,
>     }
> 
> =>
> 
>     impl ::std::clone::Clone for S {
>         #[inline]
>         fn clone(&self) -> S {
>             match *self {
>     
>                 S { a: ref __self_0_0, b: ref __self_0_1 } => { // <== BAD
>     
>                     ::std::clone::assert_receiver_is_clone(&(*__self_0_0));
>                     ::std::clone::assert_receiver_is_clone(&(*__self_0_1));
>                     *self
>                 }
>             }
>         }
>     }
>     impl ::std::marker::Copy for S { }
>     struct S {
>         a: u8,
>         b: u8,
>     }

---

Can we instead remove the parameter from `assert_receiver_is_clone` and generate something like this?

    // libcore
    pub fn assert_receiver_is_clone<T: Clone + ?Sized>() {}

    union U { a: u8, b: u16 }

    impl ::std::clone::Clone for U {
        #[inline]
        fn clone(&self) -> U {
            ::std::clone::assert_receiver_is_clone::<u8>();
            ::std::clone::assert_receiver_is_clone::<u16>();
            *self
        }
    }

**Comment by nagisa** [comment]
For unions `derive(Clone)` without `derive(Copy)` makes little sense IMO, since the fields must be Copy to derive either, so we should just require users to derive both at all times for unions.

**Comment by Stebalien** [comment]
(@durka pedantic `!Clone + Copy`)

**Comment by durka** [comment]
@Stebalien oops yeah.

**Comment by petrochenkov** [comment]
By the way, why do `#[derive(Clone, Copy)]` and `#[derive(Copy, Clone)]` generate different code? (Unoptimized in the first case.)

**Comment by durka** [comment]
Uh, they aren't supposed to. I added the check to the `#[derive_Clone]` handler because I figured even if you wrote `#[derive(Clone, Copy)]` then all the attributes would be attached before the handlers are called. But I guess I thought wrong? Or maybe the behavior changed?
