### ISSUE TITLE
Certain wrong code crashes nightly rustc

### ISSUE THREAD

**Issue by vlad9486** [rust-lang/rust#36051]
The crash happens when trait method returns `Option<Self>` but implementation returns just `Self`. It happens only on nightly version. [Playground](https://play.rust-lang.org/?gist=f1067b92ee4e2bf4f08c72c65f4423a9&version=nightly&backtrace=0)

**Comment by Stebalien** [comment]
Dup of #35869. Should be fixed by https://github.com/rust-lang/rust/pull/35877
