### ISSUE TITLE
Rust Doc accidentally elides lifetimes

### ISSUE THREAD

**Issue by CryZe** [rust-lang/rust#36067]
For some reason the lifetime `'a` is missing in the docs for `std::slice::from_raw_parts` and it's probably missing in more places. It shows that it's returning a `&'a [T]` but the lifetime is completely missing from the rest of the function signature even though it's clearly there in the source code.

[std::slice::from_raw_parts](https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html)

Signature in Source Code:
```rust
pub unsafe fn from_raw_parts<'a, T>(p: *const T, len: usize) -> &'a [T]
```

Documentation:
```rust
pub unsafe fn from_raw_parts<T>(p: *const T, len: usize) -> &'a [T]
```

**Comment by bluss** [comment]
Thank you! This is already present as issue  #14462
