### ISSUE TITLE
x86_64 MSVC coretest::ptr::test_variadic_fnptr: "error LNK2019: unresolved external symbol"

### ISSUE THREAD

**Issue by rkruppe** [rust-lang/rust#36076]
I get a linker error when building coretest as part of the `check` step, or more specifically `check-crate-std`. The source of the problem is the test `test_variadic_fnptr` in `src/coretest/ptr.rs`, and the same error can be provoked by this self-contained program:

```rust
fn main() {
    extern "C" {
        fn printf(_: *const u8, ...);
    }
    let p: unsafe extern "C" fn(*const u8, ...) = printf;
    let _q = p.clone();
}
```

Some notes:

- compiling with optimizations will inline the `clone` and subsequently eliminate all the code including the part taking the address of `printf`, and then it compiles just fine.
- It appears related to being variadic, since `fabs` in place of `printf` worked just fine.
- It doesn't matter whether I take the address of the function or call it.

## Meta

Reproduced with a rustup-provided nightly from August 21 and with the current bootstrap compiler (beta-2016-08-17).

**Comment by nagisa** [comment]
printf function is not a thing in MSVC. That test ought to be removed, because we test variadic functions in [this test](https://github.com/rust-lang/rust/blob/master/src/test/run-pass/variadic-ffi.rs), including the function pointer.

**Comment by rkruppe** [comment]
If there is no way that test can work, why haven't MSVC bots been failing since forever?

**Comment by rkruppe** [comment]
Why aren't the MSVC bots seeing the same error, then?

**Comment by nagisa** [comment]
Well existence of an actual function might depend on MSVC version, I guess. (e.g. the ulibc and the old libc implementation) Perhaps that’s the reason buildbots haven’t been failing?

> printf function is not a thing in MSVC

I really meant to say that it is not guaranteed to be a function and may be a macro too (i.e. does not export a symbol to link to)

**Comment by retep998** [comment]
@nagisa If we can detect whether we're using a new enough MSVC version, we can tell the Rust to tell the linker to link `legacy_stdio_definitions.lib` which provides `printf`.

**Comment by nagisa** [comment]
Why? Just use the test helper we have exactly for this issue.

**Comment by retep998** [comment]
@nagisa Well sure, that's probably easier and more reliable.

**Comment by rkruppe** [comment]
Are the test helpers available to coretest? Because `test_variadic_fnptr` tests some library features (hashing, clone, equality) that should, ideally, go into coretest.
