### ISSUE TITLE
vec! macro slows down compiler with ~10,000+ elements, rust 1.11

### ISSUE THREAD

**Issue by ideasman42** [rust-lang/rust#36074]
In the attached example, compilation takes between 2.5-3.5 minutes here (AMD FX-8350, 4ghz).

Both with:

```
cargo build --release
```

and

```
cargo build
```

Of course having large data-sets defined this way is something to avoid, even so - ideally it wouldn't be prohibitively slow to compile, since they may be useful in some corner cases (generated code for example).

See: [main.rs.txt](https://github.com/rust-lang/rust/files/441179/main.rs.txt)

**Comment by TimNN** [comment]
Seems to be fixed on beta / nightly.

On stable I get around 170s for expansion whereas it's around 5s in beta / nightly (other phases are negligible).

**Comment by steveklabnik** [comment]
I wonder if that means "fixed by MIR"...

**Comment by TimNN** [comment]
@steveklabnik I don't think so, macro expansion happens long before mir / trans is reached, doesn't it?

**Comment by steveklabnik** [comment]
It would, yeah, I was thinking maybe it does a better job of handling the code it's given. As I said though, just a random thought; I don't actually know.

**Comment by TimNN** [comment]
I checked `-Z time-passes`, anything but macro expansion had sub second timings on all channels.

**Comment by keeperofdakeys** [comment]
Testing with rustc 1.13, this only takes 5 seconds to compile. This definitely seems fixed now, so this issue can probably be closed.
