### ISSUE TITLE
What to do with the old book when the new book is ready

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/rust#36094]
For some value of ready. This is related to these issues in the [new book repo]()
- https://github.com/rust-lang/book/issues/181
- https://github.com/rust-lang/book/issues/235 
- https://github.com/rust-lang/book/issues/236

But since this issue has to do with what happens to the current (old) version of the book, I'm filing it in this repo where this book lives. 

This issue is for deciding between a bunch of possibilities for the current book. I'm happy to make more issues if these decisions should be split into other issues at any time, or for actually doing the work once we decide what work should be done.

Possibilities to discuss:
- We would like if at all possible to leave the current book at its current URLs so that links to it don't break.
  - What does that mean for the URLs for the new book? 
  - Should we have a version in the URLs?
  - Should the old book's URLs redirect to different URLs, say, `/v1/`?
  - Should there be a banner on old book URLs saying "You are reading an outdated version of the book, you may want to try the new book"?
  - Should we automatically redirect old book URLs to the new book, and have a banner offering a link back to the old book?
- Should the old book stay in rust-lang/rust or get its own repo too?
- Should the old book continue to be shipped with rust installations for offline reading?
- When should these transitions take place? When the new book is complete or sooner, or should we have a transition period with both? 
- Should we ever stop making the old book available?

**Comment by carols10cents** [comment]
People have mentioned that the new book's chapter on ownership and borrowing is much better than the old book's. While the new book remains unfinished, the early chapters (including the one on ownership and borrowing) have been through multiple rounds of editing and are pretty polished at this point. What do yinz think of [this suggestion](https://www.reddit.com/r/rust/comments/5qe89b/setting_expectations_for_rusts_difficulty/dd0babj/):

> Perhaps a simple hyperlinked annotation indicating that, while the new book is under heavy development, this section is in a usable state?

Either just on relevant chapters of the old book that we want to recommend the new book for, or on any page of the old book, or on the first page of the old book?

[Also from Reddit](https://www.reddit.com/r/rust/comments/5qe89b/setting_expectations_for_rusts_difficulty/dd0hv9y/), a bit more dramatic than I'd say this, but:

> If a medical trial of a new drug goes really well doctors sometimes consider it unethical to continue the trial and keep giving some patients the placebo. I'd say this is similar!

**Comment by carols10cents** [comment]
cc @steveklabnik

**Comment by vossad01** [comment]
Are there two books, or an old and a new book (meaning the old book is deprecated by the first)?  As a learner, that distinction is key in what I would expect to happen.

If there are two books that distinction should be made more clear than it is now and there should be a clear maintenance path for each book.

Based on the language in the above comment, it sounds like the intention is for the "old" book be replaced by the "new" book, based on that understanding I will stop scare-quoting "old" and "new".  Everything that follows is based on that assumption, and I may have different things to say if both books intend to be continued (I only think both should be continued if there is a content/format reason that both must exist).  My opinion here is influenced by recent experience with a couple projects where versioned web documentation and old sites made Googling for things and getting the latest or a maintained result a real challenge.

My suggestions:

> Should we ever stop making the old book available?

Yes.  As soon as possible.  The two books are not differentiated and thus create confusion for new learners.  Having both increases maintenance effort and splits the attention of maintainers.

> Should the old book stay in rust-lang/rust or get its own repo too?

The old book should be deleted from this repository.  This avoids any confusion and makes sure users end up at the right place.  If there is a window of ongoing maintenance (new publications) after the transition is made, then that subtree of the repository can be split into its own branch/repository for that purpose.

> We would like if at all possible to leave the current book at its current URLs so that links to it don't break.

I agree that it is a very good idea to not break current links.  However, I do not think that should not mean that the old book needs to be hosted indefinitely.  A mapping should be identified from each page in the old book to where it best maps to in the new book.

If there is a transitory period (which I would base on the state of the new book when it starts being published and promoted), then rel="canonical" links to the location should be added on every page.  Displaying a banner with a link to the new book would also be nice for readers, but the rel="canonical" is most important for getting the new pages to turn up in search results.

Once the transitory period (as determined by time or analytics) is over or if there was none, the old URLs can be set to redirect to the content in the new book (with no link back, the old book will be unpublished).

> Should we have a version in the URLs?

If this is referring to book version, then I believe it is addressed in the above.
If this is referring to Rust version and old versions of the book corresponding to past Rust versions will also be live, then there should be a fixed URL path that always points to the latest released version and every past version should have rel="canonical" links pointing to the latest version URL.  This should make sure search engines (1) recognize the duplicated, similar pages are different versions of the same thing and (2) makes the prioritized result the latest version.

**Comment by steveklabnik** [comment]
I'm going to close this in favor of https://github.com/rust-lang/rust/issues/39588, which is the one tracking actually moving the two books into the book repo. Thanks Carol! (And @vossad01 for the opinions here)
