### ISSUE TITLE
Snap package for Linux

### ISSUE THREAD

**Issue by eyelash** [rust-lang/rust#36106]
It would be nice if a [Snap package](http://snapcraft.io/) could be provided additional to the .tar.gz on the downloads page and possibly be uploaded to the Ubuntu Store.

I feel slightly uncomfortable executing a shell script that I downloaded from the internet with root rights and I like to have all my installed software tracked by a package manager. Unfortunately the Rust packages provided in the official Ubuntu 16.04 repositories won't be updated to newer versions of Rust so a Snap package would allow me to easily have the latest Rust installed.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this in favor of posting on internals.rust-lang.org if you're interested; if there's significant support from there we can move into an issue and subsequent implementation here.
