### ISSUE TITLE
README.md confusing sentence in msys2 for Windows

### ISSUE THREAD

**Issue by barik** [rust-lang/rust#36115]
The last sentence says:

```
# or CMake installed and in PATH you can remove them from this list. Note
# that it is important that the `python2` and `cmake` packages **not** used.
# The build has historically been known to fail with these packages.
```

I'm unclear on the sentence starting with `Note`. The sentence seems to be missing a verb: are not used? But if that is true, it looks like the `pacman` command below wants to install them anyway.

**Comment by frewsxcv** [comment]
cc @alexcrichton [who wrote these sentences](https://github.com/rust-lang/rust/commit/cb74a5874f52ad82d9ccb6ececb36f27f5a5fda5#diff-04c6e90faac2675aa89e2176d2eec7d8R84). The description in the commit message also seems relevant to this Issue. I don't know much about MSYS2, but it looks like it might be the case that there exists a `python2` package, but it shouldn't be used. Instead, one should install `mingw-w64-x86_64-python2`.

**Comment by petrochenkov** [comment]
Yep, `python2` and `mingw-w64-x86_64-python2` are different packages.
MSYS2 has three subsystems/environments with separate sets of packages - `msys2`, `mingw32` and `mingw64` (more about them [here](https://sourceforge.net/p/msys2/wiki/MSYS2%20introduction/)).
Rust is usually built in `mingw64` environment (or `mingw32`; `msys2` is used for development of MSYS2 itself) and has to use `mingw64` version of Python.

(Curiously, `mingw-w64-x86_64-make` fails trying to build Rust (at least it did the last time I tried it), so `make` from `msys2` environment has to be used. Also `mingw-w64-x86_64-python2` and `mingw-w64-x86_64-gdb` have completely broken interactive shell, so you have to deal with all subsystems anyway sooner or later :D)

**Comment by petrochenkov** [comment]
@barik 
Does my answer resolves the issue (modulo the missing verb)?
I'm not sure all these technicalities need to be put into README.

**Comment by barik** [comment]
@petrochenkov Thanks, yes that resolves the issue. I guess when reading it originally, I didn't realize `python2` was actually referring to a package in the MSYS ecosystem. Wonder if something like the following would help clarify for future readers, without having to get into too many technicalities:

> Note that it is important that you **do not use** the `python2` and `cmake` packages from the [`msys2` subsystem](https://sourceforge.net/p/msys2/wiki/MSYS2%20introduction/). The build has historically been known to fail with these packages.
