### ISSUE TITLE
rustbuild incorrectly builds std for musl targets

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#36143]
It copies the crt\*.o objects from the *host* system libraries when it, instead, should copy them from the musl-root. [Related code](https://github.com/rust-lang/rust/blob/71ee82a8aa0c02fc2c73e84f40bdb55512d10938/src/bootstrap/compile.rs#L103-L107)

It asks rustc to pass -ldl -lpthread and -lrt to the linker when it shouldn't because those are already included in musl libc.a. [Related code](https://github.com/rust-lang/rust/blob/71ee82a8aa0c02fc2c73e84f40bdb55512d10938/src/libstd/build.rs#L38-L42)

cc @alexcrichton

**Comment by alexcrichton** [comment]
Hm the crt.o files look like they're coming from the target compiler, but maybe the target passed in is wrong? The -ldl and -lpthread stuff should definitely be omitted on musl!

**Comment by japaric** [comment]
```
$ gcc -print-file-name=crti.o
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crti.o
$ musl-gcc -print-file-name=crti.o
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crti.o
```

But the musl-root in my case is `/musl`.

**Comment by alexcrichton** [comment]
Oh weird, I was hoping `musl-gcc` would do the right thing :(
