### ISSUE TITLE
`rustc --target aarch64-apple-ios --print cfg` shouldn't ICE

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#36157]
```
$ rustup run stable rustc --target aarch64-apple-ios --print cfg
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'failed to get iphoneos SDK path: No such file or directory (os error 2)', ../src/librustc_back/target/apple_ios_base.rs:59
```

I should be able to query information about the target even if I don't have the SDK installed.

### Meta

```
$ rustup run stable rustc -V
rustc 1.11.0 (9b21dcd6a 2016-08-15)
```

I don't know if this has been fixed on nightly because of #36156

cc @alexcrichton

**Comment by alexcrichton** [comment]
I believe this has essentially always been the case, but I'd love to have a fix! I think the best choice here is to delay the pieces of the iOS target that are fallible until we actually need them, for example at link time.

**Comment by TimNN** [comment]
I think this is basically a duplicate of #29812.

**Comment by japaric** [comment]
> I think this is basically a duplicate of #29812.

Yup, I'll close this one.
