### ISSUE TITLE
Cannot bootstrap for PowerPC with LLVM assertions enabled

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#36150]
[Relevant code to disable this](https://github.com/rust-lang/rust/blob/a4d11495f9e70ee246ab6a61dec8bdc751fb142a/src/ci/docker/dist-powerpc-linux/Dockerfile#L45-L47)

From [these logs](https://buildbot.rust-lang.org/builders/auto-linux-cross-opt/builds/3519/steps/compile/logs/stdio).

```
rustc: x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore
rustc: x86_64-unknown-linux-gnu/stage2/lib/rustlib/aarch64-unknown-linux-gnu/lib/libcore
rustc: x86_64-unknown-linux-gnu/stage2/lib/rustlib/arm-unknown-linux-gnueabi/lib/libcore
rustc: x86_64-unknown-linux-gnu/stage2/lib/rustlib/arm-unknown-linux-gnueabihf/lib/libcore
rustc: x86_64-unknown-linux-gnu/stage2/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libcore
rustc: x86_64-unknown-linux-gnu/stage2/lib/rustlib/mips-unknown-linux-gnu/lib/libcore
rustc: x86_64-unknown-linux-gnu/stage2/lib/rustlib/mips-unknown-linux-musl/lib/libcore
rustc: x86_64-unknown-linux-gnu/stage2/lib/rustlib/mipsel-unknown-linux-gnu/lib/libcore
rustc: x86_64-unknown-linux-gnu/stage2/lib/rustlib/mipsel-unknown-linux-musl/lib/libcore
rustc: x86_64-unknown-linux-gnu/stage2/lib/rustlib/powerpc-unknown-linux-gnu/lib/libcore
rustc: x86_64-unknown-linux-gnu/stage2/lib/rustlib/powerpc64-unknown-linux-gnu/lib/libcore
Invalid PPC CTR loop!
UNREACHABLE executed at /buildslave/rust-buildbot/slave/auto-linux-cross-opt/build/src/llvm/lib/Target/PowerPC/PPCCTRLoops.cpp:722!
Aborted (core dumped)
make: *** [x86_64-unknown-linux-gnu/stage2/lib/rustlib/powerpc-unknown-linux-gnu/lib/stamp.core] Error 134
```

This means we do not blanket turn on LLVM assertions on all of our bots, which we would ideally like to do. I'm going to try turning them off for _just_ the cross bot though.

**Comment by alexcrichton** [comment]
cc https://github.com/rust-lang/rust-buildbot/commit/571864e94556ca576c93b67e6a7ad77fed5b0eda

cc @eddyb

**Comment by nagisa** [comment]
Seems related to https://llvm.org/bugs/show_bug.cgi?id=27083 somewhat. We do not use the maxnum intrinsic (totally should!) but from the existence of bug for maxnum seems to suggest that a similar issue for some non-maxnum intrinsic is likely to exist (and libcore is kinda intrinsic-heavy).
