### ISSUE TITLE
Stop compiling LLVM with asserts

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#3615]
LLVM has a lot of asserts, and we build them. In a hypothetical Rust production build maybe we want to not do that.

It's at least worth investigating the perf impact.

**Comment by steveklabnik** [comment]
Triage: we still build with assertions, but we have a flag to build without.

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/commit/6b95d8bed8afff7262ec5623677e320bf63d2230

> This makes the default configuration fully optimized, with ... no llvm asserts,
