### ISSUE TITLE
Errant edge to krate node

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#36168]
I noticed when checking the `syntex-syntax` node that, when I add a private fn into the crate module, it invalidates the krate-0 module. This is because the metadata includes edges to the immediate children. This seems bad, but then there is also a read whenever we read an inlined item from crate X of the crate root, which means that this winds up triggering bad reuse. I am trying to figure out why this read arises and remove it, but I'd also like to remove the dependency of metadata.

**Comment by michaelwoerister** [comment]
Was this fixed by https://github.com/rust-lang/rust/commit/c6363b801316c1d8279f55a6be44746d71018ceb?

**Comment by nikomatsakis** [comment]
@michaelwoerister quite likely; I guess I will make a perf test to check

**Comment by nikomatsakis** [comment]
Looks good. Posted a PR with a fix.
