### ISSUE TITLE
#[link_args] is not propagated from libraries to binaries

### ISSUE THREAD

**Issue by whitequark** [rust-lang/rust#36176]
To reproduce:
```
// foo.rs
#![feature(link_args)]
#[link_args = "-Wl,-just_die"]
extern {}
```
```
// main.rs
extern crate foo;
fn main() {}
```
Build with:
```
rustc foo.rs --crate-type lib
rustc main.rs -L .
```
This successfully builds (and it shouldn't, if it would pass the `-Wl,-just_die`). (`--verbose` is not usable here because of https://github.com/rust-lang/rust/issues/36175). If I replace `#[link_args]` with e.g. `#[link(name = "just_die")]` then the linker invocation fails, so I believe this is a bug with link_args.

**Comment by whitequark** [comment]
My particular use case is a library that includes DWARF unwinding info that crashes ld64, so I need to be able to include `#[link_args = "-Wl,-no_compact_unwind"]` in the library to work around that, otherwise it has to be manually inserted into every binary crate.

**Comment by japaric** [comment]
How this propagation mechanism should work is an unresolved question of the issue that's tracking the stabilization of this `link_args` feature. cf. https://github.com/rust-lang/rust/issues/29596#issuecomment-153919231

**Comment by alexcrichton** [comment]
This is an intentional design decision of `#![link_args]`, and is one of the reasons it's not generally suitable for passing linker arguments. This "feature" has basically always been slated for deprecation/removal.

**Comment by whitequark** [comment]
@alexcrichton ack, closing then. I assume that once lld gets integrated into rustc this goes away / gets turned into proper attributes, though the situation might be worse for thrid-party Rust compilers...
