### ISSUE TITLE
Issue with DirectX 12

### ISSUE THREAD

**Issue by matross4** [rust-lang/rust#36187]
Not long ago I did a clean install of Windows 10 mostly due to pre-installed DX12. The first game I tried to start with it was Rust. But when I joined a server I was stucked. I could not move camera or player. UI worked as usual. Then I joined another server and I could move, but it was not playable. Just look at these pictures. At the 1st server a had the same screen but at least I could move.
![20160901183251_1](https://cloud.githubusercontent.com/assets/21638886/18164644/987271ee-7073-11e6-8786-a317e251bf9b.jpg)
![20160901183222_1](https://cloud.githubusercontent.com/assets/21638886/18164645/98789588-7073-11e6-914b-288682ddfed9.jpg)
![20160901183242_1](https://cloud.githubusercontent.com/assets/21638886/18164646/988e461c-7073-11e6-9ab7-4b1006a09c62.jpg)

**Comment by jonas-schievink** [comment]
This is a bug tracker for the Rust programming language, not the Rust game
