### ISSUE TITLE
E0537 has a span with extra characters

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang/rust#36182]
```
error[E0537]: invalid predicate `unknown`
  --> src/test/compile-fail/E0537.rs:11:7
   |
11 | #[cfg(unknown())] //~ ERROR E0537
   |       ^^^^^^^^^^
```

Currently, we underline a little too much of the predicate.  Notice that we underline two `)` instead of just the matching `)`

I noticed that E0535 and E0536 also have the same problem

**Comment by mikhail-m1** [comment]
I think bug in this line https://github.com/rust-lang/rust/blob/master/src/libsyntax/parse/attr.rs#L239
it takes span.hi from unprocessed (current) token.  It's can be easy fixed by taking  span.lo, but this will work incorrect for spaces between )) . I tried add some spaces but parse failed.

**Comment by mikhail-m1** [comment]
parser has last_span, so just need to change span -> last_span :)
