### ISSUE TITLE
lldb crash on stack frame with closure: DWARF DIE at 0x000a7888 (class closure) has a member variable 0x000a788e (__0) whose type is a forward declaration, not a complete definition

### ISSUE THREAD

**Issue by bholley** [rust-lang/rust#36185]
After stumbling upon #33062, I grabbed a copy of XCode 8 Beta and tried out lldb to debug assertion in Stylo (experimental Servo-in-Firefox). When I try to backtrace or |up| my way through a stackframe with a closure, lldb aborts:

error: libgkrust.a(geckoservo.0.o) DWARF DIE at 0x000a7888 (class closure) has a member variable 0x000a788e (__0) whose type is a forward declaration, not a complete definition.
Please file a bug against the compiler and include the preprocessed output for /files/mozilla/repos/qq/obj-x86_64-apple-darwin15.6.0/toolkit/library/rust/geckoservo

Interested in any suggestions or workarounds.

**Comment by bholley** [comment]
Any thoughts @michaelwoerister?

CC @eddyb @alexcrichton @Manishearth

**Comment by michaelwoerister** [comment]
Hm, that's interesting. I didn't think that we produced forward declarations anywhere. Seems like a bug on our side though.

**Comment by larsbergstrom** [comment]
Looking at https://bugzilla.mozilla.org/show_bug.cgi?id=1301751, this problem is probably pretty high-priority as it is breaking the ability to get stack backtraces for Firefox on macOS.

**Comment by michaelwoerister** [comment]
I'll see if I can reproduce it.

**Comment by luser** [comment]
I'm not entirely sure if this is the same bug as https://bugzilla.mozilla.org/show_bug.cgi?id=1301751 or not. We don't see that error message, we just see llvm-dsymutil crashing.

**Comment by brson** [comment]
@michaelwoerister just pinging you for updates on this P-high bug.

**Comment by bholley** [comment]
Looks like michael is working with ted to reproduce the issue in https://bugzilla.mozilla.org/show_bug.cgi?id=1301751 . If whatever fix is uncovered there doesn't fix the lldb issue, I'll get repro steps together.

**Comment by michaelwoerister** [comment]
So, investigations on that [other, possibly related, bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1301751) yielded that the problem only occurs with Rust 1.11 stable, but doesn't occur with the current beta any more. @bholley, could you try reproducing the issue with the current Rust beta?

**Comment by bholley** [comment]
The code seems to have changed since I encountered this problem, and the closure is gone. I tried to reintroduce it, but couldn't reproduce the problem.

I'll see if this reproduces in the coming weeks, and if so, will make sure I try with 1.12 or newer.

**Comment by michaelwoerister** [comment]
OK, I'll close this bug then. Can't leave a P-high issue open without being able to reproduce it.
Be sure to open a new issue of another problem pops up.

**Comment by gidon285** [comment]
i have the same bug, if you still want to reproduce it, i have.
