### ISSUE TITLE
Contributing.md should speak about make tidy

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#36191]
For the moment, a lot of new contributors encounter an issue when they open a PR because they don't know about the `make tidy` command. It should be added.

cc @steveklabnik

**Comment by Cobrand** [comment]
I volunteer as tribute !

Just to be sure I don't forget anything, `make tidy` checks for : 
* Trailing whitespaces
* Length of all the lines of the file (which shouldn't be higher than 99)
* TODOs in comments

Did I forget something ?

**Comment by steveklabnik** [comment]
I think it'd be best to say "stuff like" rather than to exhaustively list, otherwise, it will go out of date.

**Comment by GuillaumeGomez** [comment]
@Cobrand: I'm not sure it's really needed to add all of this but I think you have everything.

**Comment by Cobrand** [comment]
I guess this can be closed now ?
