### ISSUE TITLE
splitn documentation is not clear

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#36202]
> An iterator over substrings of the given string slice, separated by a pattern, restricted to returning at most count items.
> 
> The last element returned, if any, will contain the remainder of the string slice.

Is the last element yielded by the iterator the remainder _after_ the N items, or is the remainder included in N? The answer is the latter, but I don't think it's clear. Or am I the problem here?

**Comment by frewsxcv** [comment]
>  restricted to returning at most `count` items

This is supposed to indicate to the user how many items are returned by the iterator. Were you thinking `splitn` might return` count + 1` items?

**Comment by durka** [comment]
That was my confusion. The examples make it clear though.

**Comment by frewsxcv** [comment]
PR opened that attempts to address this: https://github.com/rust-lang/rust/pull/36930

**Comment by frewsxcv** [comment]
I'm going to consider the changes in https://github.com/rust-lang/rust/pull/36930 as resolving this. If someone feels otherwise, let me know and I'll reopen.
