### ISSUE TITLE
configure needs to detect name of the nodejs binary

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#36207]
On some systems it's nodejs, on some its node. It should probably just use "nodejs" unless "nodejs" doesn't exist and "node" does. Not having node shouldn't be an error. I don't recall exactly how the configure script handles these cases but there's existing code to crib off of.

Then bootstrap can pass that value to compiletest via command line, which uses it for running emscripten tests.

**Comment by brson** [comment]
cc https://github.com/rust-lang/rust/issues/33205

**Comment by foophoof** [comment]
Is this solved now that #36256 is merged?

**Comment by alexcrichton** [comment]
@foophoof indeed, thanks!
