### ISSUE TITLE
Missing feature gate for the default of `'static`

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#36216]
We neglected to add a feature gate for the new default to `'static` in statics and constants (added in https://github.com/rust-lang/rust/pull/35915). Need to fix this pronto.

cc @llogiq -- you up for that? (Sorry to ask you twice, just decided I wanted a way to track this so I don't forget.)

**Comment by llogiq** [comment]
Sure. I guess I'll need to look into how feature gates are implemented and then conditionally use the old/new behavior.

**Comment by nikomatsakis** [comment]
I am up for mentoring this for whomever (hence the E-mentor tag). [This was my description of how to *add* the change.](https://github.com/rust-lang/rust/issues/35897#issuecomment-241476626) I think what you need to do to fix this is as follows:

- add the feature gate (in `libsyntax/feature_gate.rs`)
- make a new rscope, I think, instead of re-using the elidable rscope (or else add a bool to the elidable one)
- this new rscope, in the method `base_object_lifetime_default`, should check the feature-gate (`self.tcx().sess.features.borrow().static_in_const`). If it is not set, it should issue an error to the given span suggesting the use of the feature gate. Either way it can return `'static`, I guess.

**Comment by nikomatsakis** [comment]
ok @llogiq above comment may help :)

**Comment by nikomatsakis** [comment]
closed by https://github.com/rust-lang/rust/pull/36332
