### ISSUE TITLE
can rustbuild default to ccache for LLVM?

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#36226]
Is there a reason that `ccache = false` is the default? I keep forgetting to modify config.toml when I check out a branch.

**Comment by nagisa** [comment]
config.toml is not checked into the tree so it should stay dirty at all times and you should never have to modify it when jumping across branches.

**Comment by durka** [comment]
I use worktrees to prevent rebuilds when jumping across branches anyway. But that's orthogonal to my question.

**Comment by durka** [comment]
Better yet, can we distribute a binary snapshot of LLVM?

**Comment by alexcrichton** [comment]
Right now rustbuild just mirrors `./configure`, and yes the idea is that to get around that you can persist `config.toml` across multiple branches

> Better yet, can we distribute a binary snapshot of LLVM?

Let's keep this issue focused and discuss that elsewhere

**Comment by durka** [comment]
OK, so to return to the subject then -- is there a reason not to turn ccache on by default, or is it a just a holdover and if so can we change it?

**Comment by alexcrichton** [comment]
I'm not sure if any other projects turn ccache on by default, and it takes up some serious disk space if you don't watch it.

**Comment by durka** [comment]
Fair enough.
