### ISSUE TITLE
Sort error messages by file and line number

### ISSUE THREAD

**Issue by solson** [rust-lang/rust#36229]
It would be more clear if error messages were printed out sorted. Say, by filename and then by line within a given file. Currently it seems like they are printed in the order they were emitted, which is mostly arbitrary.

cc @whitequark

**Comment by TimNN** [comment]
Related: #32650.

**Comment by Mark-Simulacrum** [comment]
Nominating for compiler team discussion, though I'm inclined to close for similar reasons as #32650 -- it seems unlikely to get implemented and largely impractical; and should be done by an external tool probably.

**Comment by nikomatsakis** [comment]
Discussed in the compiler team mtg. We agree with @Mark-Simulacrum's assessment. Going to close.

Among other things, buffering up errors is not good (takes a long time to see anything), and in an IDE it's a moot point. I also think that ordering by filename/line is not always what you want either.
