### ISSUE TITLE
rustbuild: make a config.toml entry for codegen tests

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#36232]
If you configure for system LLVM and run bootstrap.py without first running `./configure --disable-codegen-tests`, the sanity check panics:

    thread 'main' panicked at 'filecheck executable "/root/rust/FileCheck" does not exist', src/bootstrap/sanity.rs:93

(where `/root/rust` is the directory part of the path to llvm-config given in config.toml)

Per @alexcrichton there should be an option in config.toml to disable the codegen tests.

**Comment by alexcrichton** [comment]
Should be a pretty easy bug to tackle! What needs to happen here is:

* An option needs to be [added to this struct](https://github.com/rust-lang/rust/blob/ef9786ce0eac75bbe293d04dadc959bd481236a6/src/bootstrap/config.rs#L129-L147)
* That option then needs to configure [the global option](https://github.com/rust-lang/rust/blob/ef9786ce0eac75bbe293d04dadc959bd481236a6/src/bootstrap/config.rs#L81)
* That configuration would probably happen in [this block](https://github.com/rust-lang/rust/blob/ef9786ce0eac75bbe293d04dadc959bd481236a6/src/bootstrap/config.rs#L229-L249).

**Comment by durka** [comment]
I'll take it!
