### ISSUE TITLE
non_upper_case_globals lint should be suppressed for #[no_mangle] items

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang/rust#36258]
``` rust
#[no_mangle]
pub static this_symbol_is_required_to_exist: i32 = 1;

fn main() {
}
```

Yields compiler warning:

```
warning: static constant `this_symbol_is_required_to_exist` should have an upper case name such as `THIS_SYMBOL_IS_REQUIRED_TO_EXIST`, #[warn(non_upper_case_globals)] on by default
 --> <anon>:2:1
  |
2 | pub static this_symbol_is_required_to_exist: i32 = 1;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I think `#[no_mangle]` is a good hint that the symbol's name (incl. capitalization) is important enough that stylistic lints should be disabled for it. The lint already ignores functions in `extern "C" {}` blocks, for example:

``` rust
extern "C" {
    pub fn This_IS_WaCkYcapitalization();
}
```

**Comment by nagisa** [comment]
You should use `link_name` instead.

**Comment by joshtriplett** [comment]
@nagisa That would work, but would require repetition, naming the symbol twice.  And it would give the symbol a different name in Rust and in C, which could lead to user confusion.  If the interface to external code requires a symbol with a given name, FFI code may wish to use that name.

**Comment by nagisa** [comment]
@joshtriplett I personally feel that consistency with surrounding rust code (i.e. rust conventions) is more important than consistency with the exported symbols (remember, you cannot just wrap statics either).

Either way, I guess my case is just a stylistic preference and this bug is certainly valid.
