### ISSUE TITLE
[rustbuild] cross-compiling does not pass target through to the C compiler

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#36253]
```
$ python2 src/bootstrap/bootstrap.py --stage 1 --step libstd -j8 --target=armv7-unknown-linux-gnu
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
running: "clang" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-march=armv7-a" "-fno-builtin" "-fvisibility=hidden" "-fomit-frame-pointer" "-ffreestanding" "-o" "/home/nagisa/Documents/rust/rust/worktrees/more-cace/build/armv7-unknown-linux-gnu/compiler-rt/absvdi2.o" "-c" "/home/nagisa/Documents/rust/rust/worktrees/more-cace/src/compiler-rt/lib/builtins/absvdi2.c"
error: unknown target CPU 'armv7-a'
ExitStatus(ExitStatus(256))
```

The invocation of the C compiler should pass through the `--target`.

(similarly it should be passing float-abi for the arms too)

**Comment by alexcrichton** [comment]
Strictly speaking the title of this issue is not correct, rustbuild goes to *great lengths* to pass through cross compilers. 

Do you have `CC=clang`, however? The gcc-rs crate will fall back on that environment variable before checking the built-in variables.

**Comment by nagisa** [comment]
Yes, I have. I do not see how having `CC` set should prevent `gcc-rs` in any way from passing the target.

**Comment by alexcrichton** [comment]
We ask gcc-rs what the compiler is for each target. The logic there *always* falls back to `CC`. That's why it's happening.

**Comment by jyn514** [comment]
@nagisa are you still running into this issue? if so, does setting `target.cc` in config.toml fix the issue? I would be ok with having bootstrap give a hard error if `CC` is different from the config and telling you to use the config instead.

**Comment by nagisa** [comment]
Woah this is an old issue. Thanks for doing the triage!

Neither `target.cc` or `CC` are relevant to this issue as `clang` does not depend on target-prefixed compiler binaries. Rather it relies on the `--target=...` flag just like `rustc` does.

I didn’t test this, but it looks like cc-rs does now pass the `--target` argument when the tool family looks like a `Clang`, and I imagine we tell what the target is to `cc-rs`, so I’m going to close it.
