### ISSUE TITLE
Document what `Default` does for each type in libstd

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#36265]
Document what `Default` does for each type in libstd.

For example, for the `Default` impl for i32, mention that it returns 0. For slice, mention it returns an empty slice.

**Comment by cbreeden** [comment]
I'm thinking about where a good place would be to document this behavior.  I'm leaning towards documenting these behaviors in the documents for each individual type, as opposed to in the docs for `Default`.

**Comment by durka** [comment]
It would be nice if the comments were near the Default impl so they don't become stale (obviously they won't for primitive types, but this would be a good convention for user types as well). It could be a good addition to the "built-in traits section" that's been occasionally suggested for Rustdoc. Somewhere near the top it would say, e.g.:

> - This type is not Copy.
> - This type is Clone-able.
> - This type is not Send nor Sync.
> - This type has a Default and it is 0.

**Comment by bluss** [comment]
@cbreeden I was thinking on the Default-impl for each type. For example for a slice, it would show up on this impl or on this method (depending on what works right now). https://doc.rust-lang.org/std/primitive.slice.html#method.default

**Comment by athulappadan** [comment]
I would like to take up this task and would like to get an explanation of how to go about it.

**Comment by GuillaumeGomez** [comment]
@athulappadan: Find all the `Default` implementations and explain in the doc comments what it's doing. For example:

```rust
impl Default for String {
    /// Creates an empty `String`.
    fn default() -> String {
        String::new() // I guess it's doing this
    }
}
```

**Comment by bluss** [comment]
@athulappadan Don't miss this document when starting out. And feel free to ask questions https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md

**Comment by matthew-piziak** [comment]
@athulappadan Any update on this issue? If not I might like to work on it.

**Comment by athulappadan** [comment]
I was a bit busy. Will submit a PR tomorrow.

**Comment by caipre** [comment]
@athulappadan : Can this be closed?

**Comment by frewsxcv** [comment]
> @athulappadan : Can this be closed?


One more in #38186
