### ISSUE TITLE
Add libcore documentation for macros::builtin (include_bytes!, include_str!, etc.)

### ISSUE THREAD

**Issue by newpavlov** [rust-lang/rust#36272]
While `include_bytes!`, `include_str!` and other macros from `std::macros::builtin` are available with `no_std` there is no documentation for them in [libcore docs](https://doc.rust-lang.org/core/).

**Comment by TimNN** [comment]
Are you sure they are not available with `no_std`? As far as I know these are built into the compiler and available in all crates. I think it is only their documentation which is only available in `std` and not in `core`.

This should be true for all macros in the [`std::macros::builtin`](https://github.com/rust-lang/rust/blob/master/src/libstd/macros.rs#L193) module.

**Comment by newpavlov** [comment]
Hm, they are indeed available. I will edit this issue.
