### ISSUE TITLE
run-pass/coerce-expected-unsized.rs : jemalloc aborts in enable-debug builds

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#36278]
Configure flags (I suspect  `--enable-debug` is the only relevant one, though of course I recommend passing `--enable-optimize` for bootstrapping):

```
% ../configure --enable-debug --enable-optimize --enable-ccache --enable-clang --disable-optimize-tests --disable-llvm-assertions`
```

Steps to reproduce:

```
% ./x86_64-apple-darwin/stage1/bin/rustc  ../src/test/run-pass/coerce-expect-unsized.rs
% ./coerce-expect-unsized 
<jemalloc>: ../../../../src/jemalloc/src/jemalloc.c:2520: Failed assertion: "usize == isalloc(ptr, config_prof)"
Abort trap: 6
%
```

**Comment by pnkfelix** [comment]
`git bisect` indicates that this was injected by 3e313d9528adc64042012a19cc9a700bff11f19d (PR #36027); cc @eddyb

**Comment by eddyb** [comment]
I didn't fully check the validity of the rest of the code, I thought it was correct modulo initial starting data.
Maybe it doesn't round up to the struct's own alignment? Resulting in a smaller size passed to jemalloc.

**Comment by pnkfelix** [comment]
Stepping through a variant of the code, I'm certainly observing a discrepancy where we pass a small size to allocate and a larger size to deallocate.

**Comment by pnkfelix** [comment]
Code: https://is.gd/3BpBuR

some data from `rr`:

```
[...]

Breakpoint 4, alloc_jemalloc::__rust_allocate (size=128, align=8)
    at /home/fklock/Dev/Mozilla/rust.git/src/liballoc_jemalloc/lib.rs:98
(rr) finish
Run till exit from #0  alloc_jemalloc::__rust_allocate (size=128, align=8)
    at /home/fklock/Dev/Mozilla/rust.git/src/liballoc_jemalloc/lib.rs:98
0x000055d8f114849d in alloc::heap::allocate::h4983eab5bdfc0c37 ()
Value returned is $18 = (u8 *) 0x7fd2faa1b000 '\245' <repeats 128 times>
(rr) c
Continuing.

[...]

size: 24 val: 24
size: 32 val: 32
Dropping y

Breakpoint 3, alloc_jemalloc::__rust_deallocate (ptr=0x7fd2faa1b000 "", old_size=136,
    align=8) at /home/fklock/Dev/Mozilla/rust.git/src/liballoc_jemalloc/lib.rs:124
(rr)
```

**Comment by pnkfelix** [comment]
(note that the code I posted is not printing the actually relevant sizes, since it seems to me like our issue is with the size of the array in the `RcBox`, but that code is only printing the size of the `Rc` itself. Whoops.)

**Comment by pnkfelix** [comment]
On the other hand, manually breaking on `﻿_ZN4core3mem11size_of_val17h7b43c19501a0b435E(%"5.std::rc::RcBox<std::cell::RefCell<[isize]>>"* nonnull, i64)` and walking through it indicates that *it* is definitely returning 136.

Here's the LLVM IR for the generated code for that routine:

```
; Function Attrs: inlinehint uwtable
define internal i64 @_ZN4core3mem11size_of_val17h7b43c19501a0b435E(%"5.std::rc::RcBox<std::cell::RefCell<[isize]>>"* nonnull, i64) unnamed_addr #1 {
entry-block:
  %tmp_ret = alloca i64
  br label %start

start:                                            ; preds = %entry-block
  %2 = mul i64 %1, 8
  %3 = add i64 0, %2
  %4 = add i64 %3, 7
  %5 = and i64 %4, -8
  %6 = add i64 8, %5
  %7 = add i64 %6, 7
  %8 = and i64 %7, -8
  %9 = add i64 24, %8
  %10 = add i64 %9, 7
  %11 = and i64 %10, -8
  store i64 %11, i64* %tmp_ret
  %12 = load i64, i64* %tmp_ret
  br label %bb1

bb1:                                              ; preds = %start
  ret i64 %12
}
```

(I haven't yet validated where its getting 8 and 24 from in that computation, but if nothing else:

```
(rr) p (((101 + 8 + 8-1) & -8) + 24 + 8-1) & -8
$47 = 136
```

**Comment by pnkfelix** [comment]
Hmm maybe we are double-counting the `RefCell` contribution when we calcuate `RcBox<RefCell<[u8]>>` ?

**Comment by pnkfelix** [comment]
In particular, [this line](https://github.com/rust-lang/rust/blob/93067ca089ea570e4e2bdfc456958c81a4d1e092/src/librustc_trans/glue.rs#L369) where we recurse:

```rust
        let last_field = def.struct_variant().fields.last().unwrap();
        let field_ty = monomorphize::field_ty(bcx.tcx(), substs, last_field);
        let (unsized_size, unsized_align) = size_and_align_of_dst(bcx, field_ty, info);
```

that is I think recurring on the last field that is immediately present in the struct, causing us to add 8.  But the already computed prefix size (24 in this case) actually *includes* the prefix that is in that last field, I think

**Comment by eddyb** [comment]
@pnkfelix Does `struct_tail` instead of the last field work?
If the intention is to find the nested-most field, that is.
Although, I'm not entirely sure that would work well due to alignment.

Come to think of it, is this because `min_size` includes nested prefixes, and we don't want that?
It should be easy enough to completely ignore the last field, instead of `variant.min_size()` it'd be
```rust
let fields = variant.offset_after_field.len();
if fields >= 2 {
    variant.offset_after_field[fields - 2].bytes()
} else {
    0
}
```

**Comment by pnkfelix** [comment]
@eddyb yeah that sounds promising (that is, to not use `variant.min_size()` at all)
