### ISSUE TITLE
`Box<[T]>::into_raw` is useless

### ISSUE THREAD

**Issue by vinipsmaker** [rust-lang/rust#36284]
Sorry about the horrible title, but I really don't know how to else "summarize" this problem.

I tried to get an answer for this several times on StackOverflow (after documentation proved useless) and now I'm coming here. Maybe it's just a matter of updating documentation to have guarantees of a behaviour that will continue to work on future versions of Rust (the main purpose of documentation in the first place) or maybe the error is me who failed to spot the useful part.

I need to expose a Rust library to C applications and I need to expose an array of size only know at runtime to a function which will own this data and later will call a Rust function to deallocate it. I have a `Vec<u8>` and I need to get this `(*mut u8, usize)` tuple out of it. Later I need to get receive this same tuple and deallocate its data.

One option is to [use `mem::forget` + `Vec::from_raw_parts`](https://github.com/maidsafe/safe_core/commit/97bca53a826eddf12ce87bf823983ecff788c5e6#diff-6c72b345033f35005d017f9f5a1e1c9eR59), but this is far from ideal as `shrink_to_fit` isn't guaranteed to work and I'd also need to store capacity (the C library really shouldn't need to worry about that).

The perfect option would be to use `Vec::into_boxed_slice`. However, it crashed when I tried to use the pointer for the first element (`slice::as_mut_ptr`) to `Box::from_raw`, as it should. And I cannot pass the pointer return from `Box::into_raw` to the C function, as the memory layout is unspecified and I don't have any guarantee it'll be a pointer to the first element.

How do we fix this? Update documentation? Add some extra function to `Box<[T]>` like `Box<[T]>::from_raw_parts(ptr: *mut T, len: usize)`?

**Comment by nagisa** [comment]
> I have a Vec<u8> and I need to get this (*mut u8, usize) tuple out of it. Later I need to get receive this same tuple and deallocate its data.

```
let ptr = vec.as_mut_ptr();
let capacity = vec.capacity();
::std::mem::forget(vec);
```

> this is far from ideal as shrink_to_fit isn't guaranteed to work… The perfect option would be to use Vec::into_boxed_slice. However, it crashed when I tried to use the pointer for the first element (slice::as_mut_ptr) to Box::from_raw,

This is how you construct a fat slice box out of pointer and capacity:

```
let slice = slice::from_raw_parts_mut(ptr, capacity);
let boxed_slice: Box<[T]> = Box::from_raw(slice);
```

`shrink_to_fit` is exactly what `Vec::into_boxed_slice` does before making a boxed slice, so there’s really absolutely no difference between using that or `Vec::into_boxed_slice`.

> And I cannot pass the pointer return from Box::into_raw to the C function, as the memory layout is unspecified and I don't have any guarantee it'll be a pointer to the first element.

You should be able to pass `slice::as_mut_ptr` to C code just fine.

**Comment by ollie27** [comment]
@nagisa [`shrink_to_fit`](https://doc.rust-lang.org/nightly/std/vec/struct.Vec.html#method.shrink_to_fit) doesn't guarantee that the length will equal the capacity so I think `into_boxed_slice` is the correct thing to use.

**Comment by nagisa** [comment]
@ollie27 then we have a larger problem of invalid implementation of `Vec::into_boxed_slice`.

**Comment by ollie27** [comment]
See #29847.

**Comment by bluss** [comment]
You can pass the pointer (.as_mut_ptr()) and length (.len()) to C.

You can create a `*mut [T]` using `std::slice::from_raw_parts_mut`, then use Box::from_raw to remake a `Box<[T]>`.

**Comment by ustulation** [comment]
I think the problem is with documentation. [shrink_to_fit](https://doc.rust-lang.org/collections/vec/struct.Vec.html#method.shrink_to_fit) from the documentation isn't guaranteed to make `capacity == len`. So if you loose information about capacity, [from_raw_parts](https://doc.rust-lang.org/collections/vec/struct.Vec.html#method.from_raw_parts) is an undefined behaviour (if you assume `len == capacity` and pass it as such). I assume the only way `into_vec()` on Boxed-slice will be well behaved is if it guarantees to make `len == capacity` but [documentation](https://doc.rust-lang.org/collections/vec/struct.Vec.html#method.into_boxed_slice) says it's exactly as if we did `shrink_to_fit`. This seems contradictory.

**Comment by vinipsmaker** [comment]
I think boxed slice is more appropriate here. We don't need to give more guarantees to `Vec`. We could just "fix" boxed slice.

**Comment by vinipsmaker** [comment]
Hey guys, any update on this? Our FFI interfaces still feel weird taking a `capacity` member everywhere.

**Comment by ollie27** [comment]
I'm not sure what update you're waiting on. The documentation certainly needs to be improved but as far as I'm aware you can do the following now with no problems:

```rust
pub fn vec_to_ptr_len(v: Vec<u8>) -> (*mut u8, usize) {
    let mut b = v.into_boxed_slice();
    let ptr = b.as_mut_ptr();
    let len = b.len();
    std::mem::forget(b);
    (ptr, len)
}

pub unsafe fn ptr_len_to_vec(ptr: *mut u8, len: usize) -> Vec<u8> {
    Box::from_raw(std::slice::from_raw_parts_mut(ptr, len)).into_vec()
}
```

**Comment by steveklabnik** [comment]
I would like to close out this ticket. Here's how I understand it: What's left is basically @ustulation's comment above, that is, `shrink_to_fit` says it does not guarantee capacity but `into_boxed_slice` seems like it must, yet says it's the same as `shrink_to_fit`.

@rust-lang/libs, what do you want done here?

**Comment by bluss** [comment]
I think that there is lacking clarity and it needs one hard look at usable size again (if that is ok)? Rust could gain some memory utilization there, removing clown shoes, without breaking any current Vec API. It requires looking at jemalloc's size bins and working out the relevant details. The theory is that all capacities in the same bin are equivalent, and usable size gives you the largest one in the allocation's current bin.

With that in place, docs related to this can be clarified with confidence.

**Comment by alexcrichton** [comment]
Taking advantage of extra space given to us by the allocator seems like it falls under https://github.com/rust-lang/rust/issues/29931, in which case it sounds to me like @steveklabnik is right, we should just remove the clause from `into_boxed_slice` about it being equivalent to `shrink_to_fit`.

The fact that `into_boxed_slice` calls `shrink_to_fit` is just an implementation detail we need not worry about. If we change the implementation of `Vec` to take advantage of excess capacity then we'll fix that implementation as well.

**Comment by bluss** [comment]
That sounds good!

**Comment by QuietMisdreavus** [comment]
In case anyone is willing to tackle this, the docs team wants to take this approach:

> ...we should just remove the clause from `into_boxed_slice` about it being equivalent to `shrink_to_fit`.

**Comment by SeanPrashad** [comment]
Hi there! I'm a student at Seneca College whose enrolled in an Open Source course taught by my professor and Mozillian, David Humphrey. I would love to tackle this bug for my course if it's still available and unassigned.

**Comment by steveklabnik** [comment]
That'd be great! Is @QuietMisdreavus 's post on what to do clear enough?

**Comment by SeanPrashad** [comment]
@steveklabnik I would love to say yes and get on my way but I'm still a little unclear. Would I be removing documentation `into_boxed_slice` and `shrink_to_fit`? Any and all clarification is welcomed!!

**Comment by steveklabnik** [comment]
> Would I be removing documentation for into_boxed_slice being equivalent to shrink_to_fit? 

Yup! To elaborate a little further, that means modifying these lines: https://github.com/rust-lang/rust/blob/94a82adbb491b5fd0585370d4fcc7b36798e70d5/src/liballoc/vec.rs#L510-L516

The sentence about excess capacity should stay, but the second one and the link should be removed.

**Comment by SeanPrashad** [comment]
Thank you so much @steveklabnik! I will have to prepare my local environment on my laptop and get to work. Once I'm done and ready to submit a PR, I will let you know!

**Comment by vinipsmaker** [comment]
Thanks.
