### ISSUE TITLE
Don't generate code for unused #[inline] function

### ISSUE THREAD

**Issue by retep998** [rust-lang/rust#36280]
If a function or method is marked `#[inline]` and it isn't actually called anywhere in that crate, then no code should be generated for it. This would save a lot of time on translation and LLVM passes for certain crates, such as winapi.

@eddyb told me to open this issue. Blame him.

**Comment by eddyb** [comment]
cc @rust-lang/compiler - especially @michaelwoerister, I believe the collector should be able to reliably detect whether an `#[inline]` function is actually used, the only change needed to get this behavior (*if* we want it) would be to not use `#[inline]` functions as roots in the collector.

**Comment by michaelwoerister** [comment]
Afaict, the only thing that needs to be adapted should be [TransItem::is_instantiated_only_on_demand()](https://github.com/rust-lang/rust/blob/2dbf600d159a5c65b53419f1669834d1f81496a7/src/librustc_trans/trans_item.rs#L265). There's also `TransItem::requests_inline()` which makes it easy to check for the `#[inline]` attribute.

**Comment by retep998** [comment]
I did a simple patch which changed that function and it didn't really affect compile times. In fact the LLVM IR is just as big, leading me to conclude that there is more going on to decide whether to instantiate something than that function.

I'll let someone else take it from here because this is beyond my knowledge of rustc: https://github.com/retep998/rust/commit/e8d9b867b79f84425a07ded0887f6e5486bbd9b0

**Comment by michaelwoerister** [comment]
@retep998 Do you have an example of a function that you would expect not to be generated?

**Comment by retep998** [comment]
@michaelwoerister For example a simple `#[inline] pub fn foo() {}`. Or perhaps a trait impl `impl Clone for Foo { #[inline] fn clone(&self) -> Foo { *Foo } }`. According to a quick test, doing `--emit=llvm-ir` with a rustc built with my patch, functions defined like that in winapi are still being generated.

**Comment by michaelwoerister** [comment]
> For example a simple `#[inline] pub fn foo() {}`.

If the function isn't used or referenced anywhere in the crate then the modification you made should have done the trick. I'll take a look when I find the time.

**Comment by michaelwoerister** [comment]
I'm removing the nominated tag, this doesn't really need discussion in the meeting, it should just be investigated and fixed.

**Comment by michaelwoerister** [comment]
While investigating #36309 I figured out why the fix suggested above didn't help: it only fixes the problem on the multiple-codegen-units-path. For it to work with just one codegen-unit, the change will be a bit more complicated, but it will probably be part of the fix for #36309.

**Comment by retep998** [comment]
This was fixed by https://github.com/rust-lang/rust/pull/36524

**Comment by Boddlnagg** [comment]
Awesome! 🎉 This improved compile times of [winrt-rust](https://github.com/contextfree/winrt-rust/) quite a lot:

|                  | time [secs] | rlib size [bytes] |
|------------------|-------------|-------------------|
| Before (Debug)   | 351.46      | 263.572.720       |
| Before (Release) | 506.68      | 154.972.432       |
| After (Debug)    | 285.87      | 187.843.258       |
| After (Release)  | 305.48      | 119.689.216       |


"Before" is `rustc 1.13.0-nightly (c772948b6 2016-09-20)` , "After" is `rustc 1.13.0-nightly (4f9812a59 2016-09-21)`. See complete logs with `-Z time-passes` in [this gist](https://gist.github.com/Boddlnagg/908f6cd832d328eb096c089dc40abc55).

**Comment by brson** [comment]
@Boddlnagg oh nice results!

**Comment by bluss** [comment]
ndarray (a much smaller crate) had compile time improve by 20%. Its release mode time for llvm passes dropped from 1.2 s to 0.2 s.
