### ISSUE TITLE
[rustbuild] should not assume llvm-config shares root with FileCheck

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#36282]
I have a wrapper for llvm-config in `~/local/bin/` to workaround for a bug in original llvm-config, but rustbuild assumes there’s `FileCheck` in the same directory as `llvm-config`, making rustbuild fail.

It should instead get the LLVM bindir from llvm-config itself.

```
$ which llvm-config
/home/nagisa/local/bin/llvm-config
$ llvm-config --bindir
/usr/bin
```

**Comment by durka** [comment]
We also [just added](https://github.com/rust-lang/rust/pull/36234) a config.toml option to stop it from looking for FileCheck at all.

**Comment by sanxiyn** [comment]
Another way to trigger this is `llvm-config = "/usr/bin/llvm-config-3.9"`. bindir is /usr/lib/llvm-3.9/bin, /usr/bin/FileCheck-3.9 is a symbolic link to /usr/lib/llvm-3.9/bin/FileCheck. rustbuild tries to find /usr/bin/FileCheck which does not exist and fail.
