### ISSUE TITLE
Nightly panics on an unused type parameter when lifetimes are involved?

### ISSUE THREAD

**Issue by cdbfoster** [rust-lang/rust#36299]
This causes a panic with the nightly compiler: https://is.gd/OAufPJ
The stable compiler correctly reports an error about the unused type parameter.

**Comment by cdbfoster** [comment]
Even more succinctly: https://is.gd/jFGYBg

**Comment by TimNN** [comment]
`nightly-2016-09-03` is still good, `nightly-2016-09-04` causes the ICE, [changes](https://github.com/rust-lang/rust/compare/ef9786ce0...70598e04f).
