### ISSUE TITLE
LLVM_VERSION_MINOR is 0 in LLVM trunk now

### ISSUE THREAD

**Issue by sanxiyn** [rust-lang/rust#36295]
`rustllvm` includes some `#if LLVM_VERSION_MINOR >= 8` checks which are intended as "LLVM 3.8 or later". Now LLVM SVN trunk is 4.0, LLVM_VERSION_MINOR is 0, and the check fails.

**Comment by shepmaster** [comment]
Oh, are you also working on supporting LLVM 4.x? We are doing it for the AVR fork.

**Comment by shepmaster** [comment]
Note that even with the version checks updated, the new LLVM code still fails (perhaps as should be expected). We've got some [in-progress work](https://github.com/avr-rust/rust/commits/avr-support-4.0) and are [tracking some of the work](https://github.com/avr-rust/rust/issues/18). I'd expect us to submit the non-AVR specific changes upstream, once they are working.

**Comment by sanxiyn** [comment]
Fixed by #36742.
