### ISSUE TITLE
Strange deadlock bug on Rust nightly

### ISSUE THREAD

**Issue by bvssvni** [rust-lang/rust#36294]
`rustc 1.13.0-nightly (91f057de3 2016-09-04)`

This runs forever on Rust stable (1.11) but hangs on Rust nightly.

Reduced case:

```rust
use std::sync::{Arc, Mutex};
use std::any::Any;

fn main() {
    let mut counter = 0;
    loop {
        let _ = foo();
        counter += 1;
        println!("counter {}", counter); // stops at ~ 495 - 499
    }
}

fn foo() -> Arc<Mutex<Any>> {
    Arc::new(Mutex::new(false)) as Arc<Mutex<Any>>
}
```

**Comment by nagisa** [comment]
This tries to take a futex in a single threaded program for some reason. This is more minimised: 

```
use std::sync::{Arc, Mutex};
use std::any::Any;

fn main() {
    loop {
        drop(foo());
    }
}

fn foo() -> Box<Mutex<Any>> {
    Box::new(Mutex::new(0u32)) as Box<Mutex<Any>>
}
```

Only fails at optimisation levels 0 and 1, but not 2 or 3. Also doesn’t fail if inner data is `()` or `u64`, but will fail with `u8`, `u16`, `u32`.

**Comment by eddyb** [comment]
This looks like it might be #36278.
