### ISSUE TITLE
Missing Eq implementations for types implementing PartialEq

### ISSUE THREAD

**Issue by whitequark** [rust-lang/rust#36301]
Specifically (I looked at everything in std ):
- [x] std::num::ParseIntError
- [x] std::str::ParseBoolError
- [x] std::num::FpCategory

There seems to be no good reason for omitting Eq there, just an oversight. All other similar types already implement Eq.

**Comment by rkruppe** [comment]
A quick `grep` suggests there are around 300 types that derive `PartialEq` but not `Eq` in all of `src/`, though I don't have a quick way to tell how many of those *can* implement `Eq`. I wish there was an easy way to run clippy on all the code.

**Comment by whitequark** [comment]
That is really not an accurate way of measuring it because it takes into account all of the rustc-internal types, for which it probably doesn't matter much whether they implement Eq or not. Here's a nicer way:
```
git grep derive | \
  egrep -v '^(test|doc|libcollectionstest|tools|librust|libunwind|libsyntax|libtest|libterm|librbml|libserialize|libfmt_macros)' | \
  grep PartialEq | \
  grep -v '\bEq'
```

This produces only 32 examples, some of which implement Eq without deriving it:
```
libcore/char.rs:733:#[derive(PartialEq, Debug)]
libcore/cmp.rs:135:/// the `derive` strategy requires all fields are `PartialEq`, which isn't
libcore/cmp.rs:187:#[derive(Clone, Copy, PartialEq, Debug, Hash)]
libcore/fmt/num.rs:103:#[derive(Clone, PartialEq)]
libcore/fmt/num.rs:107:#[derive(Clone, PartialEq)]
libcore/fmt/num.rs:111:#[derive(Clone, PartialEq)]
libcore/fmt/num.rs:115:#[derive(Clone, PartialEq)]
libcore/fmt/num.rs:119:#[derive(Clone, PartialEq)]
libcore/fmt/rt/v1.rs:34:#[derive(Copy, Clone, PartialEq)]
libcore/num/dec2flt/mod.rs:159:#[derive(Debug, Clone, PartialEq)]
libcore/num/dec2flt/mod.rs:165:#[derive(Debug, Clone, PartialEq)]
libcore/num/flt2dec/decoder.rs:26:#[derive(Copy, Clone, Debug, PartialEq)]
libcore/num/flt2dec/decoder.rs:43:#[derive(Copy, Clone, Debug, PartialEq)]
libcore/num/mod.rs:2414:#[derive(Copy, Clone, PartialEq, Debug)]
libcore/num/mod.rs:2757:#[derive(Debug, Clone, PartialEq)]
libcore/num/mod.rs:2761:#[derive(Debug, Clone, PartialEq)]
libcore/str/mod.rs:112:#[derive(Debug, Clone, PartialEq)]
libcoretest/any.rs:14:#[derive(PartialEq, Debug)]
liblog/lib.rs:233:#[derive(Copy, Clone, PartialEq, PartialOrd, Debug)]
librand/distributions/mod.rs:272:    #[derive(PartialEq, Debug)]
libstd/collections/hash/map.rs:302:/// We must also derive `PartialEq`.
libstd/collections/hash/table.rs:138:#[derive(PartialEq, Copy, Clone)]
libstd/error.rs:461:    #[derive(Debug, PartialEq)]
libstd/error.rs:463:    #[derive(Debug, PartialEq)]
libstd/ffi/c_str.rs:158:#[derive(Clone, PartialEq, Debug)]
libstd/ffi/c_str.rs:164:#[derive(Clone, PartialEq, Debug)]
libstd/ffi/c_str.rs:170:#[derive(Clone, PartialEq, Debug)]
libstd/net/mod.rs:43:#[derive(Copy, Clone, PartialEq, Debug)]
libstd/net/parser.rs:375:#[derive(Debug, Clone, PartialEq)]
libstd/path.rs:461:#[derive(Copy, Clone, PartialEq, PartialOrd, Debug)]
libstd/sync/mpsc/select.rs:106:#[derive(PartialEq)]
libstd/sys/windows/pipe.rs:168:#[derive(PartialEq, Debug)]
```

**Comment by Mark-Simulacrum** [comment]
`rg 'derive.*PartialEq' | rg -v Eq` returns nothing, so at least those types with derived equivalence seem to all implement both. I'm not sure how many types (or what types) that implement these traits manually don't follow this though. I think it might be possible to add such a thing as a lint on the rustdoc-like level once it's reimplemented atop the RLS api.

**Comment by dtolnay** [comment]
I checked the search from https://github.com/rust-lang/rust/issues/36301#issuecomment-245028901 and it looks like all the public types that should implement PartialEq now do. Fixed!
