### ISSUE TITLE
"Unable to infer enough type information" for a function

### ISSUE THREAD

**Issue by Relrin** [rust-lang/rust#36305]
At the moment I'm implementing my own crate for Rust language - BERT serializer. When I'd implemented a first deserializer for the u8 type, I implemented a simple test which you can look [here](https://github.com/Relrin/bert-rs/blob/e248ac19f62fbf505ff31df2485583943224e10f/bert_tests/tests/test_deserializers.rs#L6-L14). It was taken from the actual state of my create, which still in development.
With this code I expected to see that tests for serializers and deserializes passed successfully. But instead of this I'm catching the following error:

``` bash
relrin at MacBook-Relrin in ~/code/bert-rs on git:serder-rs-deserializer 
=> make test
cd bert_tests && rustup run nightly cargo test --no-default-features --features serde_macros
   Compiling bert_tests v0.1.0 (file:///Users/savicvalera/code/bert-rs/bert_tests)
error[E0282]: unable to infer enough type information about `_`
  --> tests/test_deserializers.rs:11:9
   |
11 |         binary_to_term(&data).unwrap(),
   |         ^^^^^^^^^^^^^^ cannot infer type for `_`
   |
   = note: type annotations or generic parameter binding required
```

The function which is calling at that test is located [here](https://github.com/Relrin/bert-rs/blob/e248ac19f62fbf505ff31df2485583943224e10f/bert/src/deserializers.rs#L165-L170).

The more simple code for this issue looks like:

``` rust
fn f<T>() -> T {
    unimplemented!()
}

fn main() {
    assert_eq!(f(), 100u8); // failed: cannot infer type for `_`
    assert_eq!(100u8, f()); // passed successfully
}
```

So, right now I have swapped this two expressions in the `assert_eq!` macro. This is really unexpected behaviour for me.

All tests are running on the nightly build:

``` bash
rustc --version
rustc 1.13.0-nightly (3c5a0fa45 2016-08-22)
```

It also reproduced on the [rust playground](https://play.rust-lang.org/?gist=dee7f7ff34dd30407a6140b89db7ec38&version=stable&backtrace=0) with debug/release build and stable/beta/nightly channels.

**Comment by jonas-schievink** [comment]
This happens because `assert_eq!(f(), 100u8)` expands to something involving `f() == 100u8`, which is roughly equivalent to `f().eq(&100u8)`. Resolving the method call fails because the receiver type isn't known, which is a known shortcoming of the type inference algorithm.

**Comment by Relrin** [comment]
As far as I know, in the most languages which I've used for  `==` operator no sense in which order we specify arguments - a result will be the same. Why not do likewise with this macro? Because at the moment it looks like a "feature" of the macro.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this in favor of #41976, which I just opened -- I'm going to collect the issues I see that describe this problem there. I know I've seen more than one already... but finding them is hard.
