### ISSUE TITLE
codegen-units setting in Cargo.toml causes LLVM error with nightly-i686-pc-windows-msvc

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rust#36309]
Using the latest nightly `rustc 1.13.0-nightly (cbe4de78e 2016-09-05)` I'm getting this error on a project that uses euclid which uses xml-rs:
```LLVM ERROR: assembler label 'L__ehtable$_ZN3xml6reader6parser10MarkupData13take_
encoding17hb15412b3bac19ec7E' can not be undefined
error: Could not compile `xml-rs`.```
This happens only when I have `codegen-units = 4` in my Cargo.toml and only with the 32bit version of the toolchain, only with `nightly-i686-pc-windows-msvc` not with `nightly-x86_64-pc-windows-msvc`.
(I tested 4 configs: with/without `codegen-units = 4` in Cargo.toml ⨯ 32/64 bit)

**Comment by brson** [comment]
cc @mw

**Comment by alexcrichton** [comment]
cc @michaelwoerister

**Comment by brson** [comment]
Nominating for @rust-lang/compiler triage.

**Comment by michaelwoerister** [comment]
I have a dim memory of fixing this exact same problem two months ago... :confused:

**Comment by michaelwoerister** [comment]
I knew that I had seen this problem before somewhere: https://github.com/rust-lang/rust/pull/33890#issuecomment-229162953

**Comment by brson** [comment]
@michaelwoerister is this fixed?

**Comment by brson** [comment]
@Boscop maybe you can check if this is fixed?

**Comment by michaelwoerister** [comment]
It should be fixed but I'm not sure the fix is in nightly yet.

**Comment by pnkfelix** [comment]
@michaelwoerister it should be in nightly, the most recent one is:

rustc 1.13.0-nightly (4f9812a59 2016-09-21)

**Comment by michaelwoerister** [comment]
I spent some time trying to write a small test case without success. Since this is fixed for `xml-rs` which is cited by the original report, I'll close this.
