### ISSUE TITLE
E0277 for unions only mentions structs and enum variants

### ISSUE THREAD

**Issue by apasel422** [rust-lang/rust#36312]
The note issued for the following is "only the last field of a struct or enum variant may have a dynamically sized type," which is confusing, since no struct or enum variant is used:

``` rust
#![feature(untagged_unions)]

union Foo<T: ?Sized> {
    value: T,
}
```

**Comment by durka** [comment]
Similar to #36252.

**Comment by nagisa** [comment]
Is there any reason to forbid any union variant from being dynamically sized? As far as layout is concerned every single field/variant of union is the last.

**Comment by apasel422** [comment]
@nagisa I'd like to see dynamically sized union fields supported as well.

**Comment by petrochenkov** [comment]
@apasel422 
>I'd like to see dynamically sized union fields supported as well.

What is the motivation? (Besides "Why not?")
I didn't implement them because enums don't support DST's either, and the union RFC doesn't talk about DSTs and design work (read, one more RFC) is required.

**Comment by apasel422** [comment]
@petrochenkov My original use case was something like:

```rust
union Inner<T: ?Sized> {
    value: T,
}

pub struct NoDrop<T: ?Sized>(Inner<T>);
```

where you want something like `Box<NoDrop<Trait>>`, which will let the `Box`'s allocation be freed but prevent `Trait` from being dropped. But now I'm struggling to come up with a reason to do that.

**Comment by joshtriplett** [comment]
@petrochenkov Is there any non-trivial design question that arises from putting DSTs in a union, or would they just work in the obvious way? Not arguing against an additional RFC here, just asking if I've missed some unexpected complexity arising from that combination.

**Comment by petrochenkov** [comment]
@joshtriplett 
I don't remember exactly, something about unsizing coercions and how to construct unsized unions (with examples). This coercion business also represented the largest part of implementation work. 
\+ Something about last/non-last/>1 unsized fields in unions, they are different from structs in this regard.

**Comment by Mark-Simulacrum** [comment]
Aside from the overall question of DSTs in unions, for the time being we should fix the error message [here](https://github.com/rust-lang/rust/blob/0b17b4c0846d0e01544e90bb2aa2776576e825d1/src/librustc/traits/error_reporting.rs#L1140) in some way, but I don't know if we have access to whether it's a union or struct at that point -- "last field" for a union doesn't really make sense.
