### ISSUE TITLE
Index and IndexMut documentation could be improved

### ISSUE THREAD

**Issue by Cobrand** [rust-lang/rust#36329]
[Index](https://doc.rust-lang.org/std/ops/trait.Index.html) and [IndexMut](https://doc.rust-lang.org/std/ops/trait.IndexMut.html) are definitely lacking in explanations.

For starters, nothing says what does `v[x]` do exactly. (spoilers : it's sugar for `*v.index(x)` and `*v.index_mut(x)` and _not_ `v.index(x)` ; that allows things like `v[x] = 5`).

`Index<usize>` is implemented for lots of trivial types (str, String, Vec, ...), but nothing is said about `Index<Range...>`, and I think it would be worth showing some examples.

I'm opening this, but I'm planning to open a PR next week fixing this, unless someone else is up for it of course.

**Comment by marti1125** [comment]
Hi @Cobrand I would like to work in this =D

**Comment by Cobrand** [comment]
@marti1125 Then go ahead :+1: !

**Comment by marti1125** [comment]
@Cobrand I don't know how to start =/

**Comment by Cobrand** [comment]
Well, I could help of course, but I think you are mistaken about me; I'm not a mentor or anything, just a perfectly average contributor, so my help will be quite limited: I wouldn't like to lead you the wrong way.

I guess you could start by writing in pure english what I've described up there, and minimum requirement would be :

* Explain what `v[x]` does (litterally a subtitute of *v.index(x) and *v.index_mut(x) if an lvalue is needed).
* Adding examples of usages of `v[x]` (`v[x] = 5`, `let f : &i64 = &v[x]`, things like this)
* Adding examples for `.index(range)`, for instance v[..5] if v is a slice, will return the first 5 elements as a slice. (Do the same thing with slice mut).
* Use your imagination for creative examples

Again sorry if I misled you, I'm not a mentor in any way

**Comment by steveklabnik** [comment]
> , just a perfectly average contributor, so my help will be quite limited

I actually think this means that you have a great deal of ability to help; often, more experienced contributors won't realize that an explanation is too advanced, or that something is missing.

All of these seem like great improvements to me.

**Comment by Cobrand** [comment]
@marti1125 do you still want to work on this ?
