### ISSUE TITLE
warning: literal out of range for signed integer type

### ISSUE THREAD

**Issue by tipdbmp** [rust-lang/rust#36359]
The following warns about a literal that is out of range for ```i32``` but it shouldn't?
```rust
fn main() {
    let minus_1: i32 = 0xFF_FF_FF_FF_i32;
    println!("{}", minus_1);
}
// =>
// warning: literal out of range for i32, #[warn(overflowing_literals)] on by default
// -1

```

**Comment by Aatch** [comment]
It is out-of-range. The maximum value for a signed 32-bit integer is 0x7FFFFFFF.

**Comment by tipdbmp** [comment]
Well isn't ```-1_i32 (0xFF_FF_FF_FF_i32)``` well within the range of ```std::i32::MIN .. std::i32::MAX```?

```rust
fn main() {
    let minus_1: i32 = 0xFF_FF_FF_FF_i32;

    if std::i32::MIN <= minus_1 && minus_1 <= std::i32::MAX {
        println!("{}", minus_1);
    }
}
// =>
// -1
```
Maybe I am confused?

**Comment by TimNN** [comment]
@tipdbmp: While the 32bits represented by `0xFF_FF_FF_FF` represent a valid `i32`, `0xFF_FF_FF_FF` is primarily interpreted as a positive number, which is larger than `i32::MAX`. Thus that number overflows (which the link warns about) and becomes `-1`.
