### ISSUE TITLE
Regression in Beta and Nightly in type inference

### ISSUE THREAD

**Issue by Razican** [rust-lang/rust#36352]
Stable build: https://travis-ci.org/SUPERAndroidAnalyzer/super/jobs/158500096
Beta build: https://travis-ci.org/SUPERAndroidAnalyzer/super/jobs/158500095
Nightly build: https://travis-ci.org/SUPERAndroidAnalyzer/super/jobs/158500094

Beta and nightly fail when trying to get a file name as a `String` from a `PathBuf`. The code is the following:
```
let dir_iter = try!(fs::read_dir("some/random/path"));
for f in dir_iter {
    let path_file = match f.unwrap().path().file_name() {
            Some(n) => String::from(n.to_string_lossy().borrow()),
            None => String::new(),
    };
    println!("{}", path_file);
}
```

And it also happens when getting the value from an `AsRef<str>`, in this example code:
```
pub fn new<S: AsRef<str>>(somedata: S) -> String {
    String::from(somedata.as_ref())
}
```

In both cases the error is the same:
`type annotations required: cannot resolve std::string::String: std::convert::From<&_>`

**Comment by arielb1** [comment]
That's because of the `impl<'a> From<&'a [char]> for String` impl added in https://github.com/rust-lang/rust/commit/ac73335f.

**Comment by alexcrichton** [comment]
Thanks for the investigation @arielb1! This is essentially expected breakage as per our library stability conventions (e.g. fixable by a local type annotation). 

I believe @sfackler is going to open an issue, however, to track a system to better deal with these, however.

**Comment by sfackler** [comment]
#36443

**Comment by alexcrichton** [comment]
Thanks @sfackler! Closing in favor of #36443

**Comment by brson** [comment]
This was also reported 5 times on crater late in the beta cycle: https://github.com/rust-lang/rust/issues/36352

**Comment by brson** [comment]
I'm opening this to consider reverting.
