### ISSUE TITLE
Use vDSO when possible.

### ISSUE THREAD

**Issue by dpc** [rust-lang/rust#36358]
I've discovered that Go is using vDSO on Linux to get current time, which makes it much faster. From my initial investigation, it seems Rust is now taking advantage of that yet.

Reference: https://blog.cloudflare.com/its-go-time-on-linux/

**Comment by sfackler** [comment]
We just call into libc, which should route through the vDSO without any manual intervention needed,

> If you’re writing your application in a language that uses glibc, you are probably already getting your time via vDSO. Go doesn’t use glibc, so it has to implement this functionality in its runtime.

**Comment by dpc** [comment]
I don't know why, but getting current time in chrono is around 60ns, instead of what's promised for vDSO. I though that maybe two syscalls are being made (current time + current timezone?), and vDSO is not being used. I guess if libc is providing vDSO, then this issue can be closed.

**Comment by sfackler** [comment]
`chrono` doesn't use the standard library to get the current time, so this issue should be filed on that repo.

**Comment by dpc** [comment]
OH. Good to know. Thank you.
