### ISSUE TITLE
Defaults for type parameters not properly documented

### ISSUE THREAD

**Issue by bruno-medeiros** [rust-lang/rust#36362]
This feature is not properly documented in https://doc.rust-lang.org/book 
It is first mentioned only in https://doc.rust-lang.org/book/operators-and-overloading.html , but clearly it should be mentioned earlier in the Generics chapter.

**Comment by steveklabnik** [comment]
I am not making significant revisions to the book because I'm [re-writing it](https://github.com/rust-lang/book), but if someone would like to improve this, please send in a PR!
