### ISSUE TITLE
EncodeUtf8::as_slice results in suboptimal code

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#36368]
> // We know for sure this method cannot slice out-of-bounds because:
> // \* 0 ≤ self.pos ≤ 3
> // \* self.buf.len() = 4
> //
> // This way the slicing will always succeed, but LLVM is incapable of figuring out both
> // these conditions hold, resulting in suboptimal code, especially after inlining, 
> // containing bound checks and unwinding support code.

**Comment by durka** [comment]
Where are these comments from? Anyway, sounds like a case for the new panic-safe slicing stuff (#36340).

**Comment by nagisa** [comment]
[Here](https://github.com/rust-lang/rust/pull/35098/files#diff-0192328d1cff6eff500c3cd5363d69b3L655)

**Comment by nagisa** [comment]
Not applicable anymore, as a different approach is now used.
