### ISSUE TITLE
`impl Trait` doesn't understand that empty functions return ()

### ISSUE THREAD

**Issue by Stebalien** [rust-lang/rust#36379]
The following should compile because `(): Default`:

``` rust
#![feature(conservative_impl_trait)]
fn test() -> impl Default {}
```

However, it fails with:

``` rust
error[E0282]: unable to infer enough type information about `_`
 --> tmp.rs:2:14
  |
2 | fn test() -> impl Default {}
  |              ^^^^^^^^^^^^ cannot infer type for `_`
  |
  = note: type annotations or generic parameter binding required
```

(Obviously, nobody will ever run into this in practice...)

**Comment by Mark-Simulacrum** [comment]
This works today; E-needstest.

**Comment by venkatagiri** [comment]
@Mark-Simulacrum would a `run-pass` be fine for this?

**Comment by Mark-Simulacrum** [comment]
Let's go with a compile-fail test that look something like [this one](https://github.com/rust-lang/rust/blob/master/src/test/compile-fail/privacy/restricted/lookup-ignores-private.rs); meaningful part being these [two lines](https://github.com/rust-lang/rust/blob/master/src/test/compile-fail/privacy/restricted/lookup-ignores-private.rs#L39-L40). Let me know if you have any more questions!
