### ISSUE TITLE
Better suggestion when attempting to iterate over array

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#36391]
# Code

``` rust
let a = [1, 2, 4, 5, 6];

for e in a {
    println!("{}", e);
}
```
# Compiler error

```
error[E0277]: the trait bound `[{integer}; 5]: std::iter::Iterator` is not satisfied
 --> <anon>:6:5
  |
6 |     for e in a {
  |     ^ trait `[{integer}; 5]: std::iter::Iterator` not satisfied
  |
  = note: `[{integer}; 5]` is not an iterator; maybe try calling `.iter()` or a similar method
  = note: required by `std::iter::IntoIterator::into_iter`

error: aborting due to previous error
```
# Suggestion

Instead of suggesting `.iter()`, it'd be cool if we cool if we could check if the borrowed type implements `IntoIterator` and then suggest prefixing with `&`. More concretely, in the example above, `[T; 5]` does not implement `IntoIterator` but `&[T; 5]` does.

**Comment by durka** [comment]
For reference the message is generated [here](https://github.com/rust-lang/rust/blob/f8ba7cb863bf2e5fe081d82358c7cda376a7eac6/src/libcore/iter/iterator.rs#L29-L30). Improving it would require expanding the `#[rustc_on_unimplemented]` machinery or abandoning it for a custom message somewhere in the compiler (maybe in the `for` loop lowering but that might be too early).

**Comment by nagisa** [comment]
```
for i in [0; N].iter() {}
```

Works for arrays of any size N, so the suggestion is valid? Whether you opt into explicitly converting into slice and using its `IntoIterator` or use the slice’s `iter/iter_mut` method through coercions is purely stylistic choice.

**Comment by Mark-Simulacrum** [comment]
The span in this case is also quite bad -- probably because of the desugaring, I'd guess.

**Comment by frewsxcv** [comment]
Greetings from three years in the future 👋🏻 

If anyone stumbles across this, arrays now implement `IntoIterator`, so this shouldn't be an issue anymore https://blog.rust-lang.org/2021/05/11/edition-2021.html#intoiterator-for-arrays
