### ISSUE TITLE
Improvements to the assertion failed error message

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rust#36392]
Hello.
It would be nice to show the differences between the left and right value more visually, with a diff-like format and/or with colors.
For instance, with the following code:

``` rust
assert_eq!("my very very very very very very very very long sentence",
    "my very very very very very very very very long snetence");
```

we get:

```
thread 'test' panicked at 'assertion failed: `(left == right)` (left: `"my very very very very very very very very long sentence"`, right: `"my very very very very very very very very long snetence"`), tests/lib.rs:10
```

It is not easy to spot immediately the difference between the expected and the actual values.
Showing this with colors would greatly reduce the amount of time needed to spot the difference.
Thanks.

**Comment by Mark-Simulacrum** [comment]
For the time being, you can use something like the manual implementation of what you want [here](https://github.com/rust-lang-nursery/rustc-perf/blob/master/rs-backend/tests/lib.rs#L69). The [diff](https://crates.io/crates/diff) crate also has some examples that do more advanced things.

**Comment by bluss** [comment]
@antoyo Useful assert macro improvements can be prototyped in a separate crate first, might be the best way.

**Comment by Boddlnagg** [comment]
Such a thing already exists: https://github.com/gifnksm/power-assert-rs (also see https://crates.io/search?q=assert)

**Comment by Mark-Simulacrum** [comment]
Closing in favor of the tracking issue for this feature, https://github.com/rust-lang/rust/issues/41615.
