### ISSUE TITLE
rustc panics if outputting help message fails

### ISSUE THREAD

**Issue by vi** [rust-lang/rust#36415]
```
$ rustc --help > /dev/full
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.
```

I stumbled upon it when tried `rustc -Z help | grpe orbit`

Version is `rustc 1.13.0-nightly (1576de0ce 2016-08-21)`

**Comment by vi** [comment]
Related: https://github.com/rust-lang/rust/issues/24821

**Comment by Mark-Simulacrum** [comment]
So investigating this leads me to believe that we're handling something incorrectly here: https://github.com/rust-lang/rust/blob/77f1bec6f5eb9ed632c973b97b12701294e6d3a5/src/libstd/io/stdio.rs#L691. The panic! seems to still be called despite the error being IO-related:

```
$ rustc -vV | test
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'failed printing to stdout: Broken pipe (os error 32)', src/libstd/io/stdio.rs:691
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/34376.
