### ISSUE TITLE
Command.arg seems to be adding a trailing quotation mark

### ISSUE THREAD

**Issue by Visic** [rust-lang/rust#36419]
On windows 10, the following code should start the cmd process, run the "dir" command, and then exit. 

```
use std::process::{Command};
fn main() {
	let mut process = Command::new("cmd").arg("/c dir").spawn().unwrap();
	let _ = process.wait();
}
```

However, instead of actually running "dir" and printing out a directory listing, it always errors with:
'dir"' is not recognized as an internal or external command, operable program or batch file.

## Meta
rustc 1.11.0 (9b21dcd6a 2016-08-15)
binary: rustc
commit-hash: 9b21dcd6a89f38e8ceccb2ede8c9027cb409f6e3
commit-date: 2016-08-15
host: x86_64-pc-windows-msvc
release: 1.11.0

**Comment by nagisa** [comment]
This executes equivalent of `"cmd" "/c dir"` and not `"cmd" /c "dir"` which is what you probably want.

I would suggest trying instead

```
    let mut process = Command::new("cmd").arg("/c").arg("dir").spawn().unwrap();
```

(that being said, `"cmd" "/c" "dir"` fails on windows regardless, which seems… wrong?)

**Comment by Visic** [comment]
Thank you, that did fix the problem I was having! You are correct, it seems to be a quirk in windows, not rust.
