### ISSUE TITLE
Add the complete set of rules for method resolution in the Rust Reference

### ISSUE THREAD

**Issue by cbreeden** [rust-lang/rust#36427]
For references, see
- [StackOverflow Answer](http://stackoverflow.com/questions/28519997/what-are-rusts-exact-auto-dereferencing-rules)
- [TypeCk ReadMe](https://github.com/rust-lang/rust/tree/b6d91a2bdac45cd919497a24207fab843124d4ba/src/librustc_typeck/check/method#method-lookup)

**Comment by steveklabnik** [comment]
The reference lives in its own repo now, I've moved it over there: https://github.com/rust-lang-nursery/reference/issues/23

thanks!
