### ISSUE TITLE
Allow to forget about borrowing outside scoping

### ISSUE THREAD

**Issue by uzytkownik** [rust-lang/rust#36422]
It's more of a paper cut but I find it tedious to write code in following fashion:

```
let (foo, bar, almost_all_variables) = {
     let foobar = borrow_some_variable;
     let foo = borrow_some_variable.foo();
     let bar = borrow_some_variable.bar();
     ...
     (foo, bar, almost_all_variables)
};
// Here I cannot have a borrowed variable
let (foobar, ....) = {
```

I would prefer to have something like:

```
let foobar = borrow_some_variable;
let foo = borrow_some_variable.foo();
let bar = borrow_some_variable.bar();
...
forger foobar;
// We behave as if we exited scope of foobar and all dependent variables but with autoexport of them
```

Or at least some syntax sugar over the top:

```
scoped! {
     let foobar = borrow_some_variable;
     outer!(let foo = borrow_some_variable.foo()); // Export to outer scop
     outer!(let bar = borrow_some_variable.bar());
};
```

**Comment by durka** [comment]
This is covered under "non-lexical lifetimes" -- once those are implemented, then `drop(foobar);` where `foobar` is a reference will work. See http://smallcultfollowing.com/babysteps/blog/2016/04/27/non-lexical-lifetimes-introduction/

**Comment by rkruppe** [comment]
Part of rust-lang/rfcs#811

**Comment by Thiez** [comment]
> This is covered under "non-lexical lifetimes" -- once those are implemented, then `drop(foobar);` where `foobar` is a reference will work. See http://smallcultfollowing.com/babysteps/blog/2016/04/27/non-lexical-lifetimes-introduction/

Surely that would only work for `&mut T` references, since `&T` references are `Copy`?

**Comment by nikomatsakis** [comment]
I'm going to close this as "the basic point of NLL" -- it seems like too general of a bug report to be actionable just now. @uzytkownik, if you like you may experiment with NLL by doing `#![feature(nll)]`, and if you encounter problems, please do file issues! =)
