### ISSUE TITLE
Embed the MIT license

### ISSUE THREAD

**Issue by Zoxc** [rust-lang/rust#36437]
Embed the MIT license (for Rust libraries, compiler-rt and musl) in libstd so standalone binaries can legally be distributed. `libbacktrace` and `jemalloc` would probably have to be avoided for this (Windows gets a free pass).

**Comment by Stebalien** [comment]
That won't work unless rust also provides a default command-line flag to see the licenses (which won't happen). The licenses need to be user-accessible.

**Comment by whitequark** [comment]
Not necessary for, at least, compiler-rt, since the relevant [LLVM policy document](http://llvm.org/docs/DeveloperPolicy.html#license) explicitly describes using MIT such that no notices are required with the binaries:

> In addition to the UIUC license, the runtime library components of LLVM (compiler_rt, libc++, and libclc) are also licensed under the MIT License, which does not contain the binary redistribution clause.

Arguably this also applies to other MIT-licensed code.

**Comment by Stebalien** [comment]
Well, the MIT license explicitly states:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

Where I take "included" to imply "human accessible" as this is a legal document, not a technical document. I believe this is one of the reasons rust is also distributed under the Apache-2.0 License as you only have to include one copy of that (instead of one per library). @cmr probably has more to say on this subject.

**Comment by whitequark** [comment]
Given the amount of commercial entities that ship compiler-rt I would expect LLVM's interpretation to be correct...

**Comment by Stebalien** [comment]
@whitequark 

I wouldn't. Companies tend to interpret licenses as they please and the MIT license is very explicit about this. While the MIT license doesn't explicitly say that the text has to be included "in the documentation" (as the NCSA license does), included still implies accessible in some way. This is why a lot of proprietary software have some way of displaying the licenses (including MIT licenses) of all included open source software.

IMO, the appropriate way to do this is to use a plugin to extract licensing information from cargo and bundle it into the compiled binary (compressed, if possible). The program would then have to provide some way to display these licenses (e.g., a command line flag).

**Comment by whitequark** [comment]
@Stebalien I was referred to this [thread on llvm-dev](http://lists.llvm.org/pipermail/llvm-dev/2011-July/041244.html). TL;DR you are completely right in your comment above, and the policy document represents, more or less, [speculation](http://lists.llvm.org/pipermail/llvm-dev/2011-July/041299.html).

**Comment by Zoxc** [comment]
My reading of MIT is that it requires the notice and the copyright to be part of the binary (for example a license segment) in a way that's readable for some tool. BSD in the other hand requires the binary itself to produce the license somehow.

**Comment by est31** [comment]
:+1: @Stebalien 's idea to bundle the info with the binary and display it to the user. I believe though that for GUI programs a command line flag wouldn't be enough as people tend to not start GUI programs via the command line anymore.

The idea to let cargo do all the work is in my opinion really great. The actual license text could be exposed via some function inside std that looks for the text in a special place in the binary where cargo has put it, then GUI programs could integrate it as well, depending on their author's legal interpretation of the MIT.

**Comment by Mark-Simulacrum** [comment]
cc @brson since this is a license question

**Comment by Mark-Simulacrum** [comment]
cc @rust-lang/core -- license question.

**Comment by aturon** [comment]
We discussed this issue in the core team meeting today. The legal issues in this area are a bit murky, and at the moment we're not inclined to make the proposed change until the issue is more than hypothetical. (This is something that's been discussed on and off for years).
