### ISSUE TITLE
Tracking issue for `str::replacen`

### ISSUE THREAD

**Issue by knight42** [rust-lang/rust#36436]
Implemented in #36347 

cc @alexcrichton

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

Still looks like a good API to me!

**Comment by brson** [comment]
What's special abut the first N of a thing during replacement that it needs its own function? I don't see much discussion on the linked PR that created this, and I don't recall anything about it.

**Comment by knight42** [comment]
@brson 
I often came across a case that I only need to replace the first match in a line during text processing. Since `str::replace` will always replace all the matches, I guess adding a parameter to control the count of occurrences would be more convenient.

**Comment by aturon** [comment]
Note that this method follows the convention set out by methods like `splitn`.

I suspect `replacen` with a count of 1 will be a common usage.

**Comment by knight42** [comment]
@brson Does this sound good to you? Or are there any improvement that I can make?

**Comment by brson** [comment]
@knight42 it's good. Thanks.

**Comment by aturon** [comment]
Manually moving to **final comment period** with disposition to **stabilize**.
