### ISSUE TITLE
Layout broken in Crates & Modules documentation

### ISSUE THREAD

**Issue by jonhnet** [rust-lang/rust#36455]
This page:
   https://doc.rust-lang.org/stable/book/crates-and-modules.html
says: "We’ll use this module layout:" followed by a bunch of +--- text that looks like it's supposed to lay out in a < pre >, but is all strung together, so the structure isn't visible.

**Comment by apasel422** [comment]
This has been fixed in nightly: https://doc.rust-lang.org/nightly/book/crates-and-modules.html

**Comment by jonhnet** [comment]
That was ridiculously speedy. Thanks!

**Comment by steveklabnik** [comment]
Closing, as it's not a bug. Thank you for reporting though!
