### ISSUE TITLE
FIXME: Drop glue takes unsized values differently than other functions

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#36457]
Currently drop glue takes sized values as a `*(data, meta)`, but elsewhere in MIR we pass `(data, meta)` as two separate arguments. This is hokey and introduces a lot of pain to convert back and forth. I've tried to tag many of those areas with this issue number.

cc @eddyb

**Comment by Mark-Simulacrum** [comment]
I have a [branch](https://github.com/Mark-Simulacrum/rust/tree/drop-glue) that in theory fixes this, but it's based on #38302. Will post PR once that gets merged.
