### ISSUE TITLE
Installer uses does not update path properly, on Windows

### ISSUE THREAD

**Issue by InovaWiki** [rust-lang/rust#36462]
So:
- path isn't updated after installing a new version 
- installer doesn't mention this, despite giving the option of updating the path
- uninstalling old version of Rust suddenly breaks the system

Besides, paths are a mistake just like null pointers! Rust got rid of them but keeps paths?? You can't be serious.   

It's the same old Linux and C refrain over and over again: "let's mess up (f*ck) the newbies, tadada". It's institutionalized trolling, by peple "in the know". For you have to know. So sure to "always keep the pitfalls! Add with an upbeat intonation: "That's what the command-line is for!".  

Neither the download page nor the installer hint at the damn C-compiler needed. Installer doesn't even check. 

Lousy first and surely lasting impressions.

**Comment by nagisa** [comment]
> * path isn't updated after installing a new version
> * installer doesn't mention this, despite giving the option of updating the path

Have you tried restarting after completing installation?

> * uninstalling old version of Rust suddenly breaks the system

Could you please elaborate in what exact way your system was broken by the Rust uninstaller?

> Besides, paths are a mistake just like null pointers! Rust got rid of them but keeps paths?? You can't be serious. 

Mistake or not notwithstanding, the `$PATH` thing is not something that Rust can decide to get rid of, as it is an inherent part of the system in which the Rust compiler gets installed and runs.

> Neither the download page nor the installer hint at the damn C-compiler needed. 

Which version of the installer have you downloaded (the windows-gnu one or the windows-msvc one)? [The footnotes](https://www.rust-lang.org/en-US/downloads.html#win-foot) (linked to by near any mention of Windows on that same page) on the download page. Here’s what it says now:

>  † There are two prominent ABIs in use on Windows: the native (MSVC) ABI used by Visual Studio, and the GNU ABI used by the GCC toolchain. Which version of Rust you need depends largely on what C/C++ libraries you want to interoperate with: for interop with software produced by Visual Studio use the MSVC build of Rust; for interop with GNU software built using the MinGW/MSYS2 toolchain use the GNU build.

> MSVC builds of Rust additionally require the Microsoft Visual C++ build tools for Visual Studio 2013 or later. The easiest way to acquire the build tools is by installing Microsoft Visual C++ Build Tools 2015 which provides just the Visual C++ build tools. Alternately, you can install Visual Studio 2015 or Visual Studio 2013 and during install select the "C++ tools". No additional software installation is necessary for basic use of the GNU build.

> Rust's support for the GNU ABI is more mature, and is recommended for typical uses. 

Does it not state the requirement to install Visual Studio (supposing you got the MSVC version) clearly enough, or are the footnotes themselves not prominent (or prominently linked to) enough?

> Installer doesn't even check. 

That’s something which could be fixed cc @brson

**Comment by retep998** [comment]
Note that you don't need to modify `PATH` on Windows. There are ways to register an application via the registry so that it can still be found without modifying `PATH`. https://msdn.microsoft.com/en-us/library/windows/desktop/ee872121

**Comment by InovaWiki** [comment]
Hi. Thanks for responding an a fantastic manner. 

> Have you tried restarting after completing installation?

No. Path depends on this??


> Could you please elaborate in what exact way your system was broken by the Rust uninstaller?

Well, if the path points to some install, say 1.8, then after installing 1.11 Rust will still be using 1.8. Now removing 1.8 results in an invalid path and 1.11 won't be used. The path became a dangling pointer. 


> Mistake or not notwithstanding, the $PATH thing is not something that Rust can decide to get rid of, as it is an inherent part of the system in which the Rust compiler gets installed and runs.

You are defending a dangling pointer. My main point: you are part of a damned heritage not willing to be informed, instead willing to throw others off the same cliff and perpetuate the stupidity that maintains the high priests of the shell in power. Stupidity, yes (you can feed this to Linus). 

PATH is a pervasive idea, but plainly a very bad idea, that makes (some) sense in the context of the (damned) shell. I think you never thought about it, as a culture, but yet, if you decide you can't find a better way or won't challenge the status quo of the powers that be, you can use an indirection: one program launching another, and printing out a line saying it does so. 

Note: searching seems like a bad idea in the first place, yet PATH takes that approach. 
Note: But if you must, I don't see why a command  should not traverse up the path, looking for ../bin folders to see if the name matches. It can then cache that damned place. Summary: no need for PATH and the trashcan it is (mangled into single damned string!). 
Note: PATH is a global, not allowing local overrides. F*cked right from the start. 

Summary: solving this in a more fundamental sense is very worth your while. 


> Which version of the installer have you downloaded (the windows-gnu one or the windows-msvc one)? 

I started with the MS version, as it is smaller; why wouldn't I want that? Then, much later, I discovered that I also needed a C- compiler, so I downloaded the MINGW version. 

> The footnotes (linked to by near any mention of Windows on that same page) on the download page state the requirement. Here’s what it says now:
>
> † There are two prominent ABIs in use on Windows: the native (MSVC) ABI used by Visual Studio, and the GNU ABI used by the GCC toolchain. Which version of Rust you need depends largely on what C/C++ libraries you want to interoperate with: (...)

Note that in no way does it explicitly say you need a damned C-compiler. "Interoperability with C" may mean something else, it may be a calling convention like cdecl. The point is: who knows, who cares? If it is a requirement it should say so near the download: "this will not work without a damned C-compiler, of your choice, if you don't know, here is MINGW". It should *not* leave the obvious out, or speak in terms that can (and will) be misconstrued. It should not be a footnote.  

This info is obvious to everyone who had contact with the community. They all know you need a damned C-compiler. Everybody else doesn't. 

I installed Rust. It is a compiler. So I thought. No it wasn't. It was a frontend. It uses LLVM as a backend. No it doesn't. It uses something else. That's the path of confusion. The unimaginable: it needs a freaking C-compiler. WTF??! Wasn't the point of Rust avoiding C?


> Rust's support for the GNU ABI is more mature, and is recommended for typical uses.

That's good to hear, please recommend so on the page itself, along with the link to install the (undamned) MINGW. 


> Does it not state the requirement to install Visual Studio (supposing you got the MSVC version) clearly enough, or are the footnotes themselves not prominent (or prominently linked to) enough?

I guess answered that. Thank you. 

These issues are the root cause of the "damned" part, in front of the "C-compiler" and the (C and Linux) community, which is full of this shit. 

Let me explain. A compiler should be the simplest thing to use and install. It only has dependencies on the file-system and the CPU, so it works before all the rest of the system works: GPU, windowing, mouse, etc. So why do we have these issues? Even Go, which has a focus on this, does not installl properly. Yes, the f*cking path! 

If you have a brain, OR if you value human kindness (note the "either" part and its logical implications), kill the path. Because it is a root cause of swearing and frustrations. Be kind, be human. 

Thank you.

**Comment by retep998** [comment]
>No. Path depends on this??

Updates to the system environment variables are __not__ propagated to any processes that are currently running, so at the very least you have to restart your shell to pick up the new environment variables. Sometimes you may have to do a full reboot.

>Well, if the path points to some install, say 1.8, then after installing 1.11 Rust will still be using 1.8. Now removing 1.8 results in an invalid path and 1.11 won't be used. The path became a dangling pointer. 

This is one of the problems that https://rustup.rs/ solves. I recommend uninstalling any existing Rust installations, removing any trace of Rust from your `PATH` and then using rustup. This avoids the need for updating `PATH` with each new version of Rust.

>Summary: solving this in a more fundamental sense is very worth your while. 

`PATH` is essential if you want to be able to invoke `rustc` from the command line. When you execute a command, guess where it looks for an executable that has a matching name? That's right, in `PATH`. Every shell does this, and if we want you to be able to run `rustc` from whatever shell you're using, then we have to put Rust into your `PATH` somehow. We don't control your shell, we can't change this reality.

>The unimaginable: it needs a freaking C-compiler. WTF??! Wasn't the point of Rust avoiding C?

Rust doesn't need a C compiler, what it actually needs is the linker and system libraries to link to. It just so happens that these things come in the same package with a C compiler.

Also, this requirement is not at all specific to Windows, every single target requires this stuff, except for the `pc-windows-gnu` targets because it bundles the bare minimum MinGW needed, so having a more prominent notice on the download page would definitely be helpful.

**Comment by nagisa** [comment]
Just to clarify, Visual Studio is necessary for the MSVC version, because that’s the only (official) way to obtain the `link.exe` (i.e. the Microsoft Linker) and various other toolings which are not inherently related to C or C++.

---

@retep998 you linked to a way to inform windows of pathes via registry? Why did you remove your comment since?

> This is one of the problems that https://rustup.rs/ solves. I recommend uninstalling any existing Rust installations, removing any trace of Rust from your PATH and then using rustup. This avoids the need for updating PATH with each new version of Rust.

Seems like rustup is yet another thing we should prominently feature on our homepage.

**Comment by InovaWiki** [comment]
> PATH is essential if you want to be able to invoke rustc from the command line. When you execute a command, guess where it looks for an executable that has a matching name? That's right, in PATH. 

Sadly this is the culturally conditioned response I am well aware of.

**Comment by retep998** [comment]
>>PATH is essential if you want to be able to invoke rustc from the command line. When you execute a command, guess where it looks for an executable that has a matching name? That's right, in PATH.
>
>Sadly this is the culturally conditioned response I am well aware of.

Do you have a way to solve this problem? There's really no point in complaining about how awful `PATH` is to us, unless you have some sort of magical solution that Rust can actually do to avoid depending on `PATH`.

**Comment by InovaWiki** [comment]
The workaround I suggested is: launch a rust.exe proxy (which is on the path) instead. It would launch the desired version, passing all params. 

It could remember the selection for the current folder, so it would be possible to use multiple rust installs. 

It would insert a message, demonstrating its presence, and suggesting how to change the current selection. 

Other thoughts would involve a service ("run Rust") or a REPL, but this goes way beyond the scope of an installer. 

As you also imply, I think the system is broken, and the shell itself is the root of all evil and culturally central to the point of being a banner item, so goodluck with changing that. Nevertheless it is something that could and should be flagged upstream. 

I believe a search looking up the path makes a much more sensible system, by avoiding a global repository.  That takes ".bin" folders along the path, which may shortcut into a global repository (as /bin is). In other words, treat the file-system as lexical scope, as in a decent programming language.

**Comment by retep998** [comment]
>The workaround I suggested is: launch a rust.exe proxy (which is on the path) instead. It would launch the desired version, passing all params. 

This is exactly what rustup.rs is. It provides proxy binaries for Rust and Cargo so you never need to change your `PATH` to switch between different Rust toolchains.

**Comment by InovaWiki** [comment]
Ok. This thread can be closed. Maybe with rustup I'll have more luck. 

In this case I tried to run a Conrod demo. But even with the C-compiler and the path, it did not work. Who knows why. There is always an answer to why. But the thing is, that *specific* answer does not matter, and certainly should not rest on the shoulder of the publisher or the consumer. The publisher just needs to transfer his state, which is local state by definition, not global state, as is the PATH.
