### ISSUE TITLE
Add --unpretty=mir to rustc --help -v

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#36473]
Add --unpretty=mir to rustc --help -v

It's hidden from the help output.

**Comment by nagisa** [comment]
We have multiple ways to output MIR, but I think `-Z dump-mir` is the preferred one. Should we go ahead and remove the rest cc @rust-lang/compiler?

**Comment by nagisa** [comment]
We could expand `dump-mir` with various way to dump MIR (including the whole-crate dump). I myself prefer graphviz, for example, but there’s no way to `dump_mir+graphviz` currently for example.

**Comment by nikomatsakis** [comment]
I do dump-mir='' to dump the whole crate at once. The one thing it lacks is
graphviz output which is sometimes nice.

**Comment by eddyb** [comment]
@nikomatsakis Does that result in one single file? I mostly use `--unpretty=mir` together with a pager and sometimes jump around functions.

**Comment by nikomatsakis** [comment]
@eddyb no it has multiple files (which I prefer, but YMMV)

**Comment by Mark-Simulacrum** [comment]
We have --emit=mir today; does that fit the bill?

**Comment by RalfJung** [comment]
Having output to stdout (like --unpretty does) is sometimes much more useful than having it in files (even more so since the files have names that don't say anything about which function they contain).

**Comment by jyn514** [comment]
`--unpretty` is now an unstable `-Z` option and shows up in `-Z help`:
```
    -Z                       unpretty=val -- present the input source, unstable (and less-pretty) variants;
        valid types are any of the types for `--pretty`, as well as:
        `expanded`, `expanded,identified`,
        `expanded,hygiene` (with internal representations),
        `everybody_loops` (all function bodies replaced with `loop {}`),
        `ast-tree` (raw AST before expansion),
        `ast-tree,expanded` (raw AST after expansion),
        `hir` (the HIR), `hir,identified`,
        `hir,typed` (HIR with types for each node),
        `hir-tree` (dump the raw HIR),
        `mir` (the MIR), or `mir-cfg` (graphviz formatted MIR)
```
So I think this can be closed; `--help -v` doesn't show any other unstable options and I don't think unpretty should be special.

**Comment by jyn514** [comment]
Oh hmm, `--pretty` is missing though. Does pretty do anything `--unpretty` doesn't? It seems weird to have both.
```
$ rustc --pretty=x -Z unstable-options
error: argument to `pretty` must be one of `normal`, `expanded`, `identified`, or `expanded,identified`; got x
```
