### ISSUE TITLE
can't bootstrap compiler from the rust-src component because of file permissions

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#36488]
All the files, even the scripts (*.sh), have their permissions set to 644.

Bootstrapping fails while executing alloc_jemalloc build script with the following error message:

```
$ chmod +x $(rustc --print sysroot)/lib/rustlib/src/rust/configure
$ $(rustc --print sysroot)/lib/rustlib/src/rust/configure --enable-rustbuild --target=arm-unknown-linux-gnueabi
$ make
<snip>
--- stderr
./config.status: line 1197: /home/japaric/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc_jemalloc/../jemalloc/include/jemalloc/internal/private_namespace.sh: Permission denied
./config.status: line 1201: /home/japaric/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc_jemalloc/../jemalloc/include/jemalloc/internal/private_unnamespace.sh: Permission denied
./config.status: line 1221: /home/japaric/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc_jemalloc/../jemalloc/include/jemalloc/internal/public_namespace.sh: Permission denied
./config.status: line 1225: /home/japaric/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc_jemalloc/../jemalloc/include/jemalloc/internal/public_unnamespace.sh: Permission denied
./config.status: line 1237: /home/japaric/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc_jemalloc/../jemalloc/include/jemalloc/jemalloc_rename.sh: Permission denied
./config.status: line 1241: /home/japaric/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc_jemalloc/../jemalloc/include/jemalloc/jemalloc_mangle.sh: Permission denied
./config.status: line 1245: /home/japaric/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc_jemalloc/../jemalloc/include/jemalloc/jemalloc_mangle.sh: Permission denied
./config.status: line 1249: /home/japaric/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc_jemalloc/../jemalloc/include/jemalloc/jemalloc.sh: Permission denied
<snip>
```

cc @brson @Diggsey 
### Meta

```
$ rustc -V
rustc 1.13.0-nightly (5531c314a 2016-09-12)
```

**Comment by japaric** [comment]
You can't compile std with jemalloc enabled from the rust-src component either. The build fails with the same error message I posted above.

**Comment by brson** [comment]
Could be related to https://github.com/rust-lang/rust/issues/25479.

rustup has code to explicitly fix permissions in the 'bin' directory, maybe others. Probably best though to figure out how to make this tarball carry the right permissions with it.

**Comment by japaric** [comment]
@alexcrichton @brson Is this now easier to fix now that we are using Travis for testing/packaging? (This is blocking Xargo from being able to (cross) compile `std` with the "jemalloc" feature enabled.)

**Comment by alexcrichton** [comment]
Source tarballs are created from rustbuild now, but we're not using Travis for packaging. I don't think this bug fix should be any easier than before, though.

**Comment by brson** [comment]
This is going to involve hacking on both rustbuild and rustup. Ideally rustbuild will produce tarballs with the correct permissions and rustup will use those permissions when extracting the tarball.

**Comment by RalfJung** [comment]
Couldn't the `install.sh` script fix permissions? I haven't figured out yet what is putting that script into the tarball, but it seems like a natural place.

**Comment by RalfJung** [comment]
I suspect if we used <https://github.com/rust-lang/rust/commit/3be02fc41032febc28e22a8a41ec7dc85ca1ce19> on Linux, that would also preserve permissions.

@alexcrichton you went from hard-links to copies because of trouble on Windows. Would it be possible to still use hard-links on non-Windows platforms?

**Comment by RalfJung** [comment]
Never mind, the permission copying seems to actually work. The tarball does contain the right permissions. If this is still a problem (which we can only really test once #41952 is fixed), the bug is somewhere in rustup.

**Comment by RalfJung** [comment]
The tarball available at <https://static.rust-lang.org/dist/rust-src-nightly.tar.xz> has the right permissions (and same for the .gz). When I run `install.sh` to put things somewhere, the permissions are gone. I am not sure if rustup runs this script, but if to does, that's where the permissions get lost.

**Comment by RalfJung** [comment]
The `install.sh` is probably still wrong (I did not look closer into this), but when things are installed via rustup, the permissions should now be good. (Well, once the next rustup is released.)
