### ISSUE TITLE
Use case for unit-like struct.

### ISSUE THREAD

**Issue by kindlychung** [rust-lang/rust#36493]
From https://doc.rust-lang.org/book/structs.html

> This is rarely useful on its own (although sometimes it can serve as a marker type), but in combination with other features, it can become useful. For instance, a library may ask you to create a structure that implements a certain trait to handle events. If you don’t have any data you need to store in the structure, you can create a unit-like struct.

Would be nice to have an example to elaborate this.

**Comment by francozappa** [comment]
From the same page:

    struct Electron {} // use empty braces...
    struct Proton;     // ...or just a semicolon
    // whether you declared the struct with braces or not, do the same when creating one
    let x = Electron {};
    let y = Proton;

However If I change 

    // same code as before
    let y = Proton {};

`rustc` will compile with no error.

**Comment by steveklabnik** [comment]
I am re-writing the book right now, and so I'm not making significant updates to the book. If you or anyone else wants to send in a PR to improve this, I would accept it, but since it's going to be fixed eventually by the new book, I'm giving this ticket a close. Thanks!

**Comment by francozappa** [comment]
Hi @steveklabnik ,

What is the branch/repo that you are using to rewrite the book ?

I'm the review for the Italian version of the first edition of the book, and I'm finishing to review Chap 4. DO you think is a good idea to continue with the review (that is time consuming) or maybe is better to wait for the translation of the next one :question: 

Thanks.

**Comment by steveklabnik** [comment]
It's here: https://github.com/rust-lang/book

It's not going to be ready for months yet, so it really depends. If you think that you'd be done in a month or two, it's probably worth it, and if not, waiting is probably better :)
