### ISSUE TITLE
Lifetime doc needs improvement. 

### ISSUE THREAD

**Issue by kindlychung** [rust-lang/rust#36492]
I think the chapter on lifetime in the book is too brief and abstract. After reading it I feel like I get very little understanding about what lifetime actually means. 

Multiple examples in different contexts (struct, impl, fn, etc) might be necessary to enlighten the reader about this core concept of Rust (probably also the most difficult).

**Comment by steveklabnik** [comment]
Thank you for filing! I agree it needs work; I'm re-writing the book right now, actually. So this will very much be fixed when that lands. Thanks!
