### ISSUE TITLE
Closure in constant causes compile time panic

### ISSUE THREAD

**Issue by joonazan** [rust-lang/rust#36506]
I tried moving a part of my code that was used in printing out a peculiarly encoded board in normal order into a global constant, so I could reuse it. This is a complete program that reproduces the error.

``` rust
const xy_to_state: [[usize; 6]; 6] = {
    let quadrant = [[0, 1, 2], [7, 7, 3], [6, 5, 4]];
    let mut board = [[0; 6]; 6];

    for q in 0..4 {
        let mut set = |r: usize, c: usize, v: usize| {
            board[r + 3*(q / 2)][c + 3*(q % 2)] = v;
        };

        for (i, row) in quadrant.iter().enumerate() {
            for (j, square) in row.iter().enumerate() {
                set(i, j, (q << 3) | *square);
            }
        }
        set(1, 1, 32 + q);
    }

    board
};

fn main(){
    println!("{:?}", xy_to_state);
}
```

```
rustc --version --verbose
rustc 1.11.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.11.0
```

This unknown-linux-gnu is Arch Linux.

**Comment by Aatch** [comment]
Note that this won't work anyway. You can't have control flow like that in `const` expressions.

**Comment by joonazan** [comment]
What is the most suitable alternative?

2016-09-16 0:57 GMT+03:00 James Miller <notifications@github.com>:

**Comment by durka** [comment]
Use a [lazy static](https://docs.rs/lazy_static) if you want that value as a global, otherwise a function.

**Comment by joonazan** [comment]
@durka: I tried making it a function, but it made my whole program four times slower than with a hard-coded constant. I guess lazy_static would have approximately the performance of hardcoding.

I am actually a bit surprised that the compiler doesn't optimize away a pure function like it would do in a pure language. Is the compiler not smart enough, or is it not allowed to use extra space for a constant array?

**Comment by Mark-Simulacrum** [comment]
I don't see an ICE today, just a lot of errors about things not being supported in constants, so I'm going to close.
