### ISSUE TITLE
Book:  Please add documentation for the different crate types

### ISSUE THREAD

**Issue by JinShil** [rust-lang/rust#36522]
Please add documentation to the book (perhaps in the [Crates and Modules chapter](https://doc.rust-lang.org/book/crates-and-modules.html)) comparing and contrasting the different crate types:  rlib, dylib, cdylib, etc...  Thanks!

**Comment by steveklabnik** [comment]
Thanks for the issue! I am re-writing the book right now, and so am not making major changes to the existing book. That said, the book isn't absolutely comprehensive; I would think that this would make a great page for Cargo's docs, though. Mind opening an issue over there? Thanks! https://github.com/rust-lang/cargo/issues/new
