### ISSUE TITLE
building compiler docs fails

### ISSUE THREAD

**Issue by llogiq** [rust-lang/rust#36533]
Steps taken:

```
$ git clone https://github.com/rust-lang/rust &&\
cd rust && ./configure --enabled compiler idols &&\
make docs
```

Expected result:

Full docs including compiler docs in `doc/` subdirectory

Actual result:

`make` fails during `doc/rustc_built-in/index.html`, rustdoc error: `Unrecognized option: 'l'`.

**Comment by rkruppe** [comment]
Again? #36031 was only fixed 11 days ago :cry: I second this motion by @retep998 in the last issue:

> Might be worth having `--enable-compiler-docs` on some of the buildbots.

**Comment by llogiq** [comment]
I third @retep998's motion. At least one should have it.

**Comment by ollie27** [comment]
It looks like this was caused by #35021 (cc @japaric). It's trying to pass `-lstatic=compiler-rt` to rustdoc when compiling the docs for `compiler_builtins` but rustdoc doesn't support `-l`.

**Comment by stefanhusmann** [comment]
How can this be fixed? Alternativly, how can I suppress the build of docs?

**Comment by Manishearth** [comment]
`./configure --disable-compiler-docs` . It's off by default.

I use 

```rust
diff --git a/mk/crates.mk b/mk/crates.mk
index c7abf27..f68fc2a 100644
--- a/mk/crates.mk
+++ b/mk/crates.mk
@@ -78,7 +78,6 @@ DEPS_panic_abort := libc alloc
 DEPS_panic_unwind := libc alloc unwind
 DEPS_unwind := libc
 
-RUSTFLAGS_compiler_builtins := -lstatic=compiler-rt
 
 # FIXME(stage0): change this to just `RUSTFLAGS_panic_abort := ...`
 RUSTFLAGS1_panic_abort := -C panic=abort
```

on my builds to get the compiler doc build to pass

**Comment by ollie27** [comment]
This can be closed now. It was a bug in the long gone Makefiles. The compiler docs now build fine with rustbuild, or at least did and will again after #40852.
