### ISSUE TITLE
E0046 should give missing methods prototypes

### ISSUE THREAD

**Issue by kali** [rust-lang/rust#36534]
It would be great if the error message was giving the whole prototype of the missing methods, ready to be cut-and-pasted (scalac does it).

cc @jonathandturner

**Comment by jonathandturner** [comment]
@kali - would https://github.com/rust-lang/rust/pull/36371#issuecomment-246692698 do something similar to what you're looking for?

**Comment by kali** [comment]
Yep, exactly. I think we can call this one a dup.

**Comment by jonathandturner** [comment]
Sounds good.

**Comment by jonathandturner** [comment]
(dup of https://github.com/rust-lang/rust/pull/36371#issuecomment-246692698)

**Comment by RReverser** [comment]
@jonathandturner Looks like #36371 was a PR not an issue, and it was closed without merging. Should this issue be reopened until some PR fixes it?

**Comment by jonathandturner** [comment]
Pinging @estebank, who is working on errors

**Comment by estebank** [comment]
[The current output](https://play.rust-lang.org/?gist=886e6a797619cac561cfe9069256059c&version=nightly) is improved over that PR's proposal:

```
error[E0046]: not all trait items implemented, missing: `fmt`
  --> src/main.rs:17:1
   |
17 | impl std::fmt::Display for A {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `fmt` in implementation
   |
   = note: `fmt` from trait: `fn(&Self, &mut std::fmt::Formatter<'_>) -> std::result::Result<(), std::fmt::Error>`

error[E0046]: not all trait items implemented, missing: `Err`, `from_str`
  --> src/main.rs:19:1
   |
19 | impl FromStr for A{}
   | ^^^^^^^^^^^^^^^^^^ missing `Err`, `from_str` in implementation
   |
   = note: `Err` from trait: `type Err;`
   = note: `from_str` from trait: `fn(&str) -> std::result::Result<Self, <Self as std::str::FromStr>::Err>`

error[E0046]: not all trait items implemented, missing: `Foo`, `foo`, `bar`, `bay`
  --> src/main.rs:21:1
   |
6  |       type Foo;
   |       --------- `Foo` from trait
...
9  |       fn foo() -> T;
   |       -------------- `foo` from trait
10 |       fn bar();
   |       --------- `bar` from trait
11 | /     fn    bay<
12 | |         'lifetime,    TypeParameterA
13 | |             >(  a   : usize,
14 | |                 b: u8  );
   | |_________________________- `bay` from trait
...
21 |   impl X<usize> for A {
   |   ^^^^^^^^^^^^^^^^^^^ missing `Foo`, `foo`, `bar`, `bay` in implementation
```

It's not exactly cut-and-paste, but it provides enough information to fix the problem.

**Comment by RReverser** [comment]
Yeah it's improved, but for complex signatures from external crates cut and paste would be still helpful (which is what this issue was about I believe).
