### ISSUE TITLE
[rustdoc] Shows associated types for Mul<usize> impls incorrectly

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#36541]
```
impl Mul<usize> for usize
    type Output = usize
    fn mul(self, other: usize) -> usize

impl<'a> Mul<usize> for &'a usize
    type Output = usize::Output
    fn mul(self, other: usize) -> usize::Output

impl<'a> Mul<&'a usize> for usize
    type Output = usize::Output
    fn mul(self, other: &'a usize) -> usize::Output

impl<'a, 'b> Mul<&'a usize> for &'b usize
    type Output = usize::Output
    fn mul(self, other: &'a usize) -> usize::Output
```

The associated `Output` type and return type for `mul` make no sense for last 3 impls.

**Comment by steveklabnik** [comment]
Triage: this has gotten weirder:

![image](https://user-images.githubusercontent.com/27786/72074886-559dd600-32b8-11ea-85bb-afa9485c036e.png)

**Comment by nagisa** [comment]
`<usize as Mul<usize>>::Output` is correct, though. Perhaps not super easy to to read and leads to a rabbit chase, but correct. Improving that behaviour is a broader change to rustdoc or possibly the implementations. Therefore closing.
