### ISSUE TITLE
rustc should emit an error when there's a bootstrap key mismatch

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#36544]
@glandium hit a situation today where he was trying to bootstrap from the wrong compiler, and because rustc didn't see a bootstrap key match it just didn't turn on unstable features, and resulted in a mysterious failure. An error about a bootstrap key mismatch would be much more clear.

Fix is probably in rustc::session::config where CFG_BOOTSTRAP_KEY is compared.

cc @alexcrichton

**Comment by nagisa** [comment]
Would completely break rustc for people who have `$CFG_BOOSTRAP_KEY` in their environment for non-rustc purposes. I’m not sure error is warranted, but note or warning may be fine.

**Comment by brson** [comment]
@nagisa `CFG_BOOTSTRAP_KEY` is not the value being compared, it's `RUSTC_BOOTSTRAP_KEY`.

**Comment by VladDrakul** [comment]
Hey guys, I'm new and trying to figure this one out for everyone :) Go team!!

@brson, did @alexcrichton have CFG_DISABLE_UNSTABLE_FEATURES set as an environment flag? It looks like if you didn't have CFG_BOOTSTRAP_KEY or RUSTC_BOOTSTRAP_KEY flags set (both are checked in src/librustc/session/config.rs, in the function get_unstable_features_setting() ), but you had CFG_DISABLE_UNSTABLE_FEATURES set to false, you would be able to continue.

There's a match statement, and when either of the [CFG/RUSTC]_BOOTSTRAP_KEY values come up as None, then if CFG_DISABLE_UNSTABLE_FEATURES is set to false, I think it returns UnstableFeatures::Allow, but if CFG_DISABLE_UNSTABLE_FEATURES is set to true, then it returns UnstableFeatures::Disallow.

**Comment by alexcrichton** [comment]
@VladDrakul I think the idea is that if [this comparison](https://github.com/rust-lang/rust/blob/c2769285ad6d078c9a4499ad9e11278e4b78023c/src/librustc/session/config.rs#L1543) returns `!=` then a warning is issued, otherwise nothing happens.

**Comment by TimNN** [comment]
I suppose this can be closed, now that bootstrap key checking has been disabled in #37265.
