### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by pmarcelll** [rust-lang/rust#36556]
The files `src/libstd/sync/mpsc/spsc_queue.rs` and `src/libstd/sync/mpsc/spsc_queue.rs` was originally added a long time ago in #10080, and the first line is `Copyright (c) 2010-2011 Dmitry Vyukov. All rights reserved.` (explained in #9710). These files are only licensed under the BSD 2-Clause license.
- The file doesn't contain the usual `Copyright The Rust Developers`, although the team is a co-author.
- Does the second clause means, that rustc should print the whole BSD license just for these? (Or I'm misinterpreting it?)

Is it an issue at all? (I'm not that familiar with distributing and licensing software.) If it is, can we do something about it?

**Comment by Mark-Simulacrum** [comment]
cc @brson because this is a licensing question

**Comment by aturon** [comment]
cc @rust-lang/core

**Comment by pmarcelll** [comment]
Thanks for looking into this issue!
The code comes from #9710, from the first comment:

> I included the license Dmitry asked me to use when I implemented a C++11 version of this queue a while ago. If the license is an issue, I suggest reaching out to Dmitry.

So I guess it's worth asking him, he's active on Github.

@dvyukov with all due respect, can you help us resolve this issue? The real issue is that the code in question has a different license than the rest of the codebase (although the Apache2/MIT dual license is very similar to the BSD license).

**Comment by brson** [comment]
I think it is not a _problem_ that these files are BSD licensed - rustc carries a bunch of licenses, including the BSD, but it wouldn't hurt to relicense them.
