### ISSUE TITLE
Generating macro rules with macro rules breaks $crate

### ISSUE THREAD

**Issue by NipaJ** [rust-lang/rust#36558]
Generating exported macro rules with macro rules ends up breaking the $crate variable. See the following example:

```
/* lib.rs */
// macro_rules! bug_generator {
    // () => {
        #[macro_export]
        macro_rules! bug {
            () => { $crate::get_value() }
        }
    // }
// }

// bug_generator!();

pub fn get_value() -> u32 { 5u32 }
```

```
/* main.rs */
#[macro_use]
extern crate rustbug;

fn main() {
    let value = bug!();
    println!("{}", value);
}
```

The code above works fine, until you add the commented lines. The bug seems to be that $crate doesn't expand to ::rustbug when invoked from main.rs.

**Comment by Mark-Simulacrum** [comment]
Closing, both cases work now.
