### ISSUE TITLE
Error without location

### ISSUE THREAD

**Issue by alygin** [rust-lang/rust#36561]
There're two known compiler errors that provide no location information:

```
error: main function not found
error: aborting due to previous error
```

It holds true for both the standard output and the JSON error format.

While the latter is a meta error and obviously is not related to a particular place in the source code, the former one could at least come with a file name. It would be of use to both humans and IDEs, particularly when there're several executables in a single project (in the `examples` or `src/bin` folders).

Since there's always a particular file in which `rustc` is looking for the `main()` function, this file name should be mentioned in the message either with the `1:1` position, or with no position at all. This would let the user or IDE to quickly jump directly to the file in which the problem must be fixed.

**Comment by estebank** [comment]
Current output:

```
$ rustc file.rs
error[E0601]: `main` function not found in crate `file`
  |
  = note: consider adding a `main` function to `file.rs`
```

**Comment by alygin** [comment]
@estebank, thank you for the notice, the output surely looks much better now. Though, it still lacks a code reference that would conform with other error messages and could be used by parsers.

I mean something like that:

```
$ rustc file.rs
error[E0601]: `main` function not found in crate `file`
 --> file.rs
  |
  = note: consider adding a `main` function to `file.rs`
```

Extracting the file name from the note text, which is a subject of occasional change, doesn't seem like a reliable approach.
