### ISSUE TITLE
Use `usize` instead of `u64` for hashes in HashMap

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#36567]
Just a note on the current implementation which stores the hash values per bucket as u64. We can't use more than `usize`'s bits of a hash to select a bucket anyway, so we only need to store that part in the table. This would be an improvement on 32-bit platforms to make the hashmap's data structures smaller, hopefully improving cache utilization during insert and lookup.

**Comment by eddyb** [comment]
cc @rust-lang/compiler This might be relevant to `rustc`, although as tempting as x32-style schemes may seem, they're not *that* portable. Still, it would be interesting to see if we can better perf on linux.

**Comment by bluss** [comment]
I've made the PR #36595. Can anyone test see what effect it has on bootstrap on 32-bit?

**Comment by bluss** [comment]
If we're hunting hashmap improvements, maybe one should even get [ordermap](https://github.com/bluss/ordermap) into finished shape, and use rustc as a benchmark for it.

**Comment by arthurprs** [comment]
We probably want to investigate switching the layout to HHHHHHKVKVKVKVKVKV as well, that will definitely improve the iteration and growing speed. There was an attempt here https://github.com/rust-lang/rust/pull/21973

**Comment by arthurprs** [comment]
regarding the previous, I started experimenting in this branch https://github.com/arthurprs/hashmap2/commit/e18a3230d6aa411166385dced5d8674cd09a71b4 I'm a bit tired so I can't tell why insertions are quite a bit slower, lookups are slight faster.

**Comment by arthurprs** [comment]
Ok, here's where it's at right now

```
➜  hashmap2 git:(layout) ✗ cargo benchcmp hashmap:: hhhkvjv:: bench.txt
 name                           hashmap:: ns/iter  hhhkvjv:: ns/iter  diff ns/iter   diff % 
 grow_10_000                    900,987            748,947                -152,040  -16.87% 
 grow_fnv_10_000                468,339            412,397                 -55,942  -11.94% 
 insert_100                     2,453              2,345                      -108   -4.40% 
 insert_1000                    22,255             21,745                     -510   -2.29% 
 insert_100_000                 4,197,661          3,970,342              -227,319   -5.42% 
 insert_10_000                  299,783            278,901                 -20,882   -6.97% 
 insert_int_bigvalue_10_000     771,563            688,716                 -82,847  -10.74% 
 insert_str_10_000              335,973            319,684                 -16,289   -4.85% 
 insert_string_10_000           1,096,811          1,023,304               -73,507   -6.70% 
 iterate_10_000                 67,109             57,290                   -9,819  -14.63% 
 lookup_100_000_multi           192,011            183,866                  -8,145   -4.24% 
 lookup_100_000_multi_10p       13,552             14,830                    1,278    9.43% 
 lookup_100_000_single          39                 38                           -1   -2.56% 
 lookup_100_000_single_10p      39                 38                           -1   -2.56% 
 lookup_10_000_exist            140,285            135,199                  -5,086   -3.63% 
 lookup_hashmap_10_000_noexist  147,883            148,633                     750    0.51% 
 merge_shuffle                  1,222,215          1,182,413               -39,802   -3.26% 
 merge_simple                   20,338,275         20,373,096               34,821    0.17% 
 new                            6                  6                             0    0.00% 
 with_capacity_10e5             3,218              3,221                         3    0.09%
```

**Comment by bluss** [comment]
That's very impressive @arthurps, any improvement like that must be welcome. Any downsides that you know of? The previous try stalled on code style / implementation details.

The simple u64 → usize PR be merged long before, since it's a simple change.

**Comment by bluss** [comment]
The lookup_100_000_multi_10p performance drop of course attracts some attention, is that something that's consistent between runs? Maybe there's a cache use change that can explain it.

**Comment by bluss** [comment]
Oh right, one drawback that was mention is that `(K, V)` is stored like that, which leads to losses to alignment especially if K and V are very different.

**Comment by arthurprs** [comment]
@bluss yeah I'm not sure that's noise.

Since Robin hood puts a good bound on the probing distance I think it may be a gain even if it wastes space in padding. I'll add a bench for that.

**Comment by arthurprs** [comment]
I was a little skeptical so I made a round of benchmark improvements https://github.com/arthurprs/hashmap2/commit/f8bd5795f32e825ce15794d475fc2730cec7cd6d. I tried to make sure value was not a `()` and that it's actually accessed on lookup benchmarks. I think we can all agree that's more realistic. To my disbelief the improvements are real.

```
➜  hashmap2 git:(layout) ✗ cargo benchcmp hashmap:: hhkvkv:: bench.txt
 name                             hashmap:: ns/iter  hhkvkv:: ns/iter  diff ns/iter   diff % 
 grow_10_000                      831,494            774,845                -56,649   -6.81% 
 grow_fnv_10_000                  436,332            408,507                -27,825   -6.38% 
 insert_100                       2,287              2,185                     -102   -4.46% 
 insert_1000                      23,240             22,016                  -1,224   -5.27% 
 insert_100_000                   4,686,280          3,714,852             -971,428  -20.73% 
 insert_10_000                    321,412            286,961                -34,451  -10.72% 
 insert_int_bigvalue_10_000       747,207            411,894               -335,313  -44.88% 
 insert_str_10_000                331,262            327,805                 -3,457   -1.04% 
 insert_string_10_000             786,945            783,286                 -3,659   -0.46% 
 iterate_10_000                   61,394             56,323                  -5,071   -8.26% 
 lookup_100_000_multi             190,329            185,459                 -4,870   -2.56% 
 lookup_100_000_multi_bigvalue    193,315            190,748                 -2,567   -1.33% 
 lookup_10_000_exist              149,193            132,171                -17,022  -11.41% 
 lookup_10_000_multi              152,040            141,125                -10,915   -7.18% 
 lookup_10_000_multi_bigvalue     159,889            147,993                -11,896   -7.44% 
 lookup_1_000_000_multi           137,578            132,193                 -5,385   -3.91% 
 lookup_1_000_000_multi_bigvalue  144,100            135,437                 -8,663   -6.01% 
 lookup_10_000_noexist    146,147            147,957                  1,810    1.24% 
 merge_shuffle                    1,283,138          1,172,662             -110,476   -8.61% 
 merge_simple                     37,187,914         22,913,279         -14,274,635  -38.39% 
 new                              6                  5                           -1  -16.67% 
 with_capacity_10e5               3,241              3,203                      -38   -1.17% 
```

**Comment by bluss** [comment]
It would make sense for `.get(k).cloned()` lookup to favour the kvkvkv layout more (at least more there than..) and `.contains_key(k)` for the kkkvvv layout, due to caching effects.

**Comment by alexcrichton** [comment]
Discussed at libs triage the other day, our [thoughts are on the PR](https://github.com/rust-lang/rust/pull/36595#issuecomment-249725336).
