### ISSUE TITLE
impl FromIterator for BTreeSet?

### ISSUE THREAD

**Issue by kindlychung** [rust-lang/rust#36562]
It seems natural to create a set from an iterator.

**Comment by sfackler** [comment]
That implementation appears to already exist, at least looking at `BTreeSet`'s docs: https://doc.rust-lang.org/std/collections/struct.BTreeSet.html

**Comment by sfackler** [comment]
The implementation is here and has been present since 1.0: https://github.com/rust-lang/rust/blob/master/src/libcollections/btree/set.rs#L617
