### ISSUE TITLE
HashMap: Does not reserve in extend

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#36579]
HashMap: Does not reserve in extend. This exacerbates the performance pathology when extending one map with another, mentioned in #36481.

~~(I'm working on a fix)~~

**Comment by bluss** [comment]
This should probably be closed ("WONTFIX") if we accept that hashmaps must be ready for being extended with iterators that are just duplicates of existing keys (i.e. no growth needed).

**Comment by sfackler** [comment]
Hmm, yeah, the overlap case is interesting. Probably worth discussing with @rust-lang/libs but I think I agree that the current no reserve behavior is the way to go.

**Comment by alexcrichton** [comment]
Closing due to [this comment](https://github.com/rust-lang/rust/issues/36579#issuecomment-248039198) but the libs team [is very interested](https://github.com/rust-lang/rust/issues/36481#issuecomment-250340646) in exploring our options here!

**Comment by arthurprs** [comment]
I think the decision here is a bit too conservative, we should discuss some sort of middle ground (even if arbitrary). The stdlib HM is optimized for reads, not writes, and this decision sort of goes against that.

From the top of my head I can of two ways.
1. Assume some factor of overlap but reserve a fraction of the items upfront.
2. Consider a more write optimized load factor when doing batch inserts.
