### ISSUE TITLE
Option docs conflates panics with safety

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#36581]
In Rust, *safety* is memory safety, and panic is *safe*. Option docs should not use "safety" for this notice: https://doc.rust-lang.org/nightly/std/option/enum.Option.html#safety-note

**Comment by sfackler** [comment]
Should probably just retitle that section to "Warning" or "Note" or something like that.

**Comment by steveklabnik** [comment]
Yes, this seems sub-par. I would remove the heading and move it into the regular description, personally.

**Comment by jpadkins** [comment]
I'd be interested in fixing this.
