### ISSUE TITLE
impl type parameter used only in projections can't be inferred

### ISSUE THREAD

**Issue by carllerche** [rust-lang/rust#36584]
Given the following impl block:

``` rust
impl<F, T, B, E> Future for Connecting<F, Client<T::In, T::Out, B, E>>
    where F: Future<Item = T, Error = io::Error>,
          T: Transport<Error = E> + Send + 'static,
          T::In: Send + 'static,
          T::Out: Send + 'static,
          B: Stream<Item = T::BodyIn, Error = E> + Send + 'static,
          E: From<Error<E>> + Send + 'static,
{ ... }
```

[source](https://github.com/tokio-rs/tokio-proto/blob/maybe-rustc-bug/src/pipeline/client.rs#L37-L44)

`T` is not able to be inferred. When using this code, rustc outputs an error message about having to annotate types, however even annotating the types doesn't solve the problem.

I would expect one of two outcomes:

a) `T` is inferred from `F::Item`
b) The impl block is rejected (it currently compiles and users of `Connecting` get the error message)

[Here is some code](https://github.com/tokio-rs/tokio-proto/blob/maybe-rustc-bug/tests/test_pipeline_client.rs#L117-L120) attempting to use `Connecting`

**Comment by eddyb** [comment]
cc @rust-lang/lang

**Comment by nikomatsakis** [comment]
Hmm. It'd be really helpful to try and pare this down to a smaller test case...

**Comment by nikomatsakis** [comment]
OK so I think the problem may lie with the `connect` function:

```rust
pub fn connect<T, B, E>(handle: &Handle, new_transport: T) -> Connecting<T::Future, Client<T::In, T::Out, B, E>>
    where T: NewTransport<Error = E>,
          T::In: Send + 'static,
          T::Out: Send + 'static,
          T::Item: Send + 'static,
          B: Stream<Item = T::BodyIn, Error = E> + Send + 'static,
E: From<Error<E>> + Send + 'static,
```

Note this case:

```rust
Connecting<T::Future, Client<T::In, T::Out, B, E>>
           ^^^^^^^^^
```

Maybe we can't infer the `T` somehow? It seems like the `T` will be the type of the second argument, which appears to be a closure here:

https://github.com/tokio-rs/tokio-proto/blob/maybe-rustc-bug/tests/test_pipeline_client.rs#L118

(Distracted, so take w/ a grain of salt)

**Comment by nikomatsakis** [comment]
triage: P-medium

**Comment by Mark-Simulacrum** [comment]
If someone provides a code example that reproduces this today, then we can reopen, but right now all links in this issue are dead, so I'm going to close.
