### ISSUE TITLE
Reachable symbols should be determined by the MIR

### ISSUE THREAD

**Issue by Aatch** [rust-lang/rust#36594]
Currently, the set of reachable symbols is determined by the privacy, and whether or a function that references the symbol could be inlined cross-crate. With MIR inlining (see #36593), symbols that were previously considered unreachable from outside the crate may become reachable if an item that isn't inlined cross-crate is inlined into another function that _is_ inlined cross-crate.

**Comment by jonas-schievink** [comment]
This looks like it would fix #35870, too

**Comment by steveklabnik** [comment]
Triage: no idea what the situation is with this bug, honestly.

**Comment by eddyb** [comment]
cc @michaelwoerister @Zoxc @oli-obk

**Comment by oli-obk** [comment]
cc @wesleywiser

**Comment by bjorn3** [comment]
cc @cjgillot Do you think https://github.com/rust-lang/rust/pull/91743 could make whatever this issue is about visible on stable? Or do you think this issue has been fixed since?

**Comment by cjgillot** [comment]
I have no idea what this bug is about.

**Comment by oli-obk** [comment]
the monomorphization collector works completely on MIR nowadays. I think we fixed all these issues since they were occurring with return-position-impl-trait already.
