### ISSUE TITLE
Libraries installed on windows do not have expected symbols

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#3660]
From ssylvan:

Consider this a very preliminary bug report, I only gave it about two
minutes because I have to run, so I could probably track this down
further with some process monitor logging. In case this is useful as
is I'll just tell you here.

On 64-bit Windows 8 RTM I get this in a message box when running the
executable produced by compiling the example on rust-lang.org.

```
---------------------------
helloworld.exe - Entry Point Not Found
---------------------------
The procedure entry point
_ZN4rand14__extensions__10meth_1235514gen_uint_range17_be256aac3933fdb73_04E
could not be located in the dynamic link library
D:\Programming\rust\helloworld.exe.
```

**Comment by steveklabnik** [comment]
It's been almost a year, and "this shouldn't be an issue anymore." If anyone is still seeing this, please let me know, closing until we know this is true.
