### ISSUE TITLE
make tidy runs before the rest of make check with -jn>1

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#36613]
This is extremely annoying since it means you have to have nicely formatted code to run the tests. We changed this years ago and it seems to have reverted to the old behaviour.

**Comment by nrc** [comment]
At least when running `-jn` where n > 1.

**Comment by pnkfelix** [comment]
FYI the point where we changed it was back in #15516

**Comment by alexcrichton** [comment]
Yes I think the confusing/annoying part here can be subjective, some want it one way and some want it another. I don't think there's necessarily a right answer here.

**Comment by nrc** [comment]
I'm not trying to change the normal behaviour, just trying to make `make check -j1` and `make check -jn` have the same behaviour.

**Comment by petrochenkov** [comment]
>some want it one way and some want it another. I don't think there's necessarily a right answer here.

Data point: I normally use `make tidy`, `make check-notidy` or `make something-very-specific`. `make check` seems to never be the most appropriate target.

**Comment by alexcrichton** [comment]
Make's gone now, so closing.
