### ISSUE TITLE
Module level attributes are being parsed before plugins are registered

### ISSUE THREAD

**Issue by draivin** [rust-lang/rust#36617]
Previously I was using a plugin to register a `MultiModifier`, and the plugin users would use a `#![modifier]` attribute in the entry module of their programs, so the plugin could rewrite anything inside the module.

But on the latest nightly, this results in a compilation error: 
```
error: The attribute `modifier` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
```
This leads me to believe that module level attributes are now being parsed before the plugins finish registering.

Tagging @jseyfried.

**Comment by jseyfried** [comment]
Fixed in #36618.
