### ISSUE TITLE
Dep info contains invalid file paths when rustc-macro is used

### ISSUE THREAD

**Issue by Thinkofname** [rust-lang/rust#36625]
Noticed it causing issues with cargo as it uses `--emit=dep-info,link` and then parses the files as part of the fingerprinting process.

It seems every instance of macro generated code (e.g. via serde_derive) creates a `rustc-macro\ source\ code` entry into this file which when cargo tries to look up it can't find. 

Cargo issue: https://github.com/rust-lang/cargo/issues/3094

**Comment by alexcrichton** [comment]
Added this to the macros 1.1 tracking issue https://github.com/rust-lang/rust/issues/35900

(I consider this a blocker for stabilization)
