### ISSUE TITLE
rustdoc: Renders Run button even if playpen is not enabled

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#36621]
rustdoc renders the **Run** button even if playpen is not enabled now. Clicking the button has no useful effect.

Was this caused by #36334 ?

**Comment by GuillaumeGomez** [comment]
Do you have a page/code example please?

**Comment by bluss** [comment]
Sure, http://bluss.github.io/arrayvec/doc/arrayvec/struct.ArrayVec.html as of today. Generated with `rustc 1.13.0-nightly (32571c05c 2016-09-17)`

**Comment by GuillaumeGomez** [comment]
I don't see any run button on the url you gave me. :-/

**Comment by bluss** [comment]
Lol, I pushed an update so that it redirects to docs.rs. My bad.

**Comment by GuillaumeGomez** [comment]
Ok, I understand what's wrong. I'll fix it as soon as I can.
