### ISSUE TITLE
Tracking issue for retain() method for HashMap (`retain_hash_collection`)

### ISSUE THREAD

**Issue by navaati** [rust-lang/rust#36648]
The HashMap type does not have a retain method like the one in Vec.

**Comment by Cobrand** [comment]
I wonder if that needs an RFC ? Pretty small change to std, but still a change to std

**Comment by nagisa** [comment]
Small backward-compatible additions do not need an RFC unless they hit some sort of controversy.

**Comment by mbrubeck** [comment]
This was [added in nightly](https://doc.rust-lang.org/nightly/std/collections/struct.HashSet.html#method.retain) as an unstable feature `retain_hash_collection` with a link to this issue. The issue should be re-opened for tracking stabilization.  CC @rust-lang/libs

**Comment by jrmuizel** [comment]
It would be nice if BTreeMap got retain() as well

**Comment by alexbool** [comment]
What is holding stabilization now?

**Comment by sfackler** [comment]
Nothing as far as I know!

@rfcbot fcp merge

**Comment by alexbool** [comment]
Thanks for lightning quick answer @sfackler !

**Comment by alexcrichton** [comment]
@rfcbot reviewed

**Comment by Mark-Simulacrum** [comment]
`BTreeMap`, as [mentioned above](https://github.com/rust-lang/rust/issues/36648#issuecomment-285521851) doesn't appear to have this method. Should that be added before stabilization? Would that require a separate feature at this point?

**Comment by F001** [comment]
This feature `retain_hash_collection` is only for `HashMap` and `HashSet`. We should assign another name for the feature for `BTreeMap` and `BTreeSet`, such as `retain_btree_collection`.

**Comment by alexcrichton** [comment]
@Mark-Simulacrum yeah at this point we'd probably have a separate issue for that, but we'd definitely welcome a PR to implement it!

**Comment by camlorn** [comment]
If doing these isn't going to need an RFC, can someone (me? I feel like I'm volunteering) put them on all the containers?

Doing an RFC for this was something I was planning to do when I had this hypothetical thing called time, but if it's not needed then someone should just go for it.  Retain is the only way to express loops that might delete, and I don't see why we shouldn't have it on everything where it makes sense.

**Comment by Mark-Simulacrum** [comment]
Yeah, I think the other containers just need implementations and another tracking issue opened, as per https://github.com/rust-lang/rust/issues/36648#issuecomment-297233304. Go right ahead!
