### ISSUE TITLE
Panic=abort as a target option?

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/rust#36647]
Let's assume a target with no unwinding support (e.g. a small system on a chip).  [RFC 1513](https://github.com/rust-lang/rfcs/blob/master/text/1513-less-unwinding.md) added a `-C panic=strategy` flag and a cargo profile option for disabling the unwinding machinery. However, even with those options, we still need dummy implementations for `eh_personality` and `_Unwind_Resume`. 

The reason is that the cross-compiled sysroot (e.g. via xargo) still contains references to those functions. We can avoid this by setting `RUSTFLAGS` to `-C panic=abort` when invoking `xargo`. This way, the sysroot is created without unwinding. This solution works, but feels a bit hacky.

We could solve this problem in an easier way if we added a option for `panic=abort` in the target json. Then we could express targets without unwinding support and xargo would automatically compile the sysroot correctly.

**Comment by rkruppe** [comment]
A concept of targets without unwinding support would not only be useful for embedded programming but also for GPU-ish targets.

**Comment by alexcrichton** [comment]
This seems reasonable to me. The current default is [set here](https://github.com/rust-lang/rust/blob/49dd95b07807a26f94bf11eb4771bbb7d79ef02c/src/librustc/session/config.rs#L803) but we could make that an option and instead punt the default to the target spec.

**Comment by japaric** [comment]
I'll give this a try.

**Comment by japaric** [comment]
Fix in #36794
