### ISSUE TITLE
i8 and u8 not correctly shown in MSVC debugger

### ISSUE THREAD

**Issue by Boddlnagg** [rust-lang/rust#36646]
Compiling the following program with the MSVC toolchain and the running it in the MSVC debugger shows that there is some problem with inspecting values of type `i8` and `u8` (this was originally found while investigating #36503):

``` rust
fn main() {
    let value_i8:  i8  = -1;
    let value_i16: i16 = -2;
    let value_i32: i32 = -3;
    let value_i64: i64 = -4;

    let value_u8:  u8  = 1;
    let value_u16: u16 = 2;
    let value_u32: u32 = 3;
    let value_u64: u64 = 4;

    let value_f32: f32 = 5.;
    let value_f64: f64 = 6.;


    let slice_u8: &[u8] = &[1,2,3];
    let slice_i8: &[i8] = &[1,2,3];
    let slice_u16: &[u16] = &[1,2,3];
    let slice_i16: &[i16] = &[1,2,3];

    // Without these, the values would be optimized away
    println!("{} {} {} {}", value_i8, value_i16, value_i32, value_i64);
    println!("{} {} {} {}", value_u8, value_u16, value_u32, value_u64);
    println!("{} {}", value_f32, value_f64);
    println!("{:?} {:?} {:?} {:?}", slice_u8, slice_i8, slice_u16, slice_i16);
}
```

![debugger](https://cloud.githubusercontent.com/assets/1024333/18745991/10855b18-80c5-11e6-8594-435d31a55844.png)

The screenshot shows that the problem also appears for `&[u8]` and `&[i8]`, where the debugger can't show the pointer (`data_ptr`).

**Comment by alexcrichton** [comment]
cc @michaelwoerister

**Comment by Boddlnagg** [comment]
cvdump (from https://github.com/Microsoft/microsoft-pdb/) says that the typeindex of both `value_i8` and `value_i16` is 0x0011, which according to https://github.com/Microsoft/microsoft-pdb/blob/master/include/cvinfo.h corresponds to
```
T_SHORT = 0x0011, // 16 bit signed
``` 
Similarly, `value_u8` and `value_u16` both have typeindex 0x0021, corresponding to
```
T_USHORT = 0x0021, // 16 bit unsigned
```
I'm trying to fix this in the PDB manually to see if it makes things work correctly.

**Comment by Boddlnagg** [comment]
Looks like it's coming from the translation of DWARF to CodeView DebugInfo in LLVM, so it's really an LLVM issue: https://github.com/llvm-mirror/llvm/blob/864e0ffb0eb47f848aca60d1f08fc2962fbb5009/lib/CodeGen/AsmPrinter/CodeViewDebug.cpp#L1223-L1240

**Comment by michaelwoerister** [comment]
@Boddlnagg That's some nice detective work there `:)`

From what I see in `cvinfo.h`, the given typeindices actually seem to be reasonable. `i8` and `u8` *are* signed and unsigned integers after all. It would be interesting what MSVC itself emits for an `uint8_t`, for example.

**Comment by michaelwoerister** [comment]
OK, so MSVC seems to emit char types for those:
```
This code:
uint8_t variable1 = 1;
int8_t variable2 = 2;

Results in this PDB:
(0003E8)  S_BPREL32: [FFFFFFEF], Type:       T_CHAR(0010), variable1
(0003FC)  S_BPREL32: [FFFFFFFB], Type:      T_UCHAR(0020), variable2
```

I'd still consider it a bug in the MSVC debugger rather than in LLVM.

**Comment by Boddlnagg** [comment]
I agree that the MSVC debugger behavior is unexpected, but LLVM has already [changed](https://github.com/llvm-mirror/llvm/commit/83f42796fedc8278cc3c473b31f36a5d485bd189) a usage of T_INT8 to T_QUAD (both represent 64-bit integers), probably because of a similar issue, so it looks like the T_INTx types are just not supported very well by the debugger.

The debugger module for using GDB directly inside MSVC (https://github.com/Microsoft/MIEngine) does the same thing by the way (although coming from the opposite direction, since it uses the DWARF data directly):
![debugger-mi](https://cloud.githubusercontent.com/assets/1024333/18919469/918ab202-859e-11e6-834b-055a7f1802aa.png)

**Comment by michaelwoerister** [comment]
I submitted a bug with LLVM: https://llvm.org/bugs/show_bug.cgi?id=30552
Thank you so much for looking into this, @Boddlnagg!

**Comment by Boddlnagg** [comment]
A fix has landed in LLVM :)

**Comment by michaelwoerister** [comment]
I consider this fixed.

**Comment by gurry** [comment]
Guys can you please confirm if this issue is actually fixed? I'm still seeing it with rustc 1.14:

![image](https://cloud.githubusercontent.com/assets/1068853/22021474/a173a83a-dce3-11e6-8e75-d3dcbd27ff36.png)

Rustup list output:
![image](https://cloud.githubusercontent.com/assets/1068853/22021506/c8bf0718-dce3-11e6-9d77-3aef645113cd.png)

**Comment by sfackler** [comment]
Reopening since the LLVM fix has not propagated to our fork.

**Comment by gurry** [comment]
Hi guys, Any indication whether a fix will make it into 1.15 or not? I'm not sure what the policy is on updating rust's mirror of LLVM. If someone can help me I can do the rebase or merge. Or do we wait for the next official release of LLVM to come out before we do the merge?

**Comment by gurry** [comment]
As per information provided by @brson [here](https://users.rust-lang.org/t/is-36646-fixed/8981/6?u=gurry), upgrade to next version of LLVM is in progress. The status can be tracked here: https://github.com/rust-lang/rust/issues/37609

**Comment by MichaelNecio** [comment]
#37609 has been closed. Can this issue be closed now too?

**Comment by Boddlnagg** [comment]
I can confirm that this is working now in my test program with the latest nightly (`rustc 1.19.0-nightly (f89d8d184 2017-05-30)`)

![debugger-fixed](https://cloud.githubusercontent.com/assets/1024333/26629409/8d6c2d16-4602-11e7-8331-21df1e53e196.png)

**Comment by michaelwoerister** [comment]
Cool, thanks @Boddlnagg!
