### ISSUE TITLE
win64 generates SSE instructions even when they are disabled with -sse

### ISSUE THREAD

**Issue by AndrewScull** [rust-lang/rust#36653]
Following the advice of https://github.com/rust-lang/rfcs/issues/1364, I tried to avoid using SSE instructions by disabling MMX and SSE, and enabling soft-float with the features field of my tagert "features": "-mmx,-sse,+soft-float". However, when using an extern "win64" function for my UEFI entry point, movaps instructions are still generated to save and restore the xmm6-15 registers.

I have put together a [minimal example](https://github.com/AndrewScull/rust-win64-soft-float) to demonstate the problem.

**Comment by nagisa** [comment]
https://llvm.org/bugs/show_bug.cgi?id=30503

**Comment by nagisa** [comment]
Fixed in LLVM by r282819.

**Comment by Mark-Simulacrum** [comment]
I'm going to assume we've already backported/migrated to an LLVM with that patch; can someone verify that this is fixed?

**Comment by alexcrichton** [comment]
We I believe have long since updated LLVM, so closing.
