### ISSUE TITLE
Add `move` keyword for closures to the Reference

### ISSUE THREAD

**Issue by cbreeden** [rust-lang/rust#36683]
Currently the rust reference doesn't mention the `move` keyword used in snippets like this:

``` rust
let mut add_num = move |x: i32| num += x;
```

**Comment by akadark** [comment]
https://doc.rust-lang.org/grammar.html#keywords includes `move` in the list of keywords.

**Comment by steveklabnik** [comment]
This has now been fixed, thank you!

**Comment by paulie4** [comment]
NOTE: the new location for the added `move` documentation is here:
https://doc.rust-lang.org/reference/expressions/closure-expr.html
