### ISSUE TITLE
Macro not from standard library says "Note: this error originates in a macro from the standard library"

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#36693]
This is just a type error, but it claims it's from a macro in the standard library when it's not. 

```rust
error[E0308]: mismatched types
 --> <anon>:3:13
  |
3 | let x: () = test_case!();
  |             ^^^^^^^^^^^^ expected (), found i32
  |
  = note: expected type `()`
  = note:    found type `i32`
  = note: this error originates in a macro from the standard library
```

implementation:

```rust
#[macro_export]                                                                                                                                         
macro_rules! test_case {                                                         
    () => (1i32);                                                                
} 
```

It's probably any cross-crate use that triggers it.

**Comment by bluss** [comment]
cc @jonathandturner

**Comment by jonathandturner** [comment]
I just landed a PR for this/something similar. Did you try it against the latest matter?

**Comment by bluss** [comment]
I did not. This was `rustc 1.13.0-nightly (4f9812a59 2016-09-21)`. I'll try the newer nightlies as they come out.

**Comment by bluss** [comment]
right, now it says "note: this error originates in a macro outside of the current crate", so this is fixed.
