### ISSUE TITLE
E310 uses weird terminology

### ISSUE THREAD

**Issue by rkruppe** [rust-lang/rust#36700]
For context, the message is, in the case of a type parameter `T` missing a lifetime bound:

> error: the parameter type `T` may not live long enough

The suggestion that follows (adding a lifetime bound to `T`) is fine, but I've just seen someone confused by the wording of the actual error message. Irrespective of any misconceptions or lack of knowledge that might have factored in that specific person's confusion, this message does seem to use very strange terminology. Types, as opposed to values, don't really _live_ (it's occasionally convenient to make puns about this, but in this case it hurts), and it's not really a question of how long a value of type `T` lives but rather of lifetime parameters contained in `T`. Also, "parameter type" looks odd &mdash; "type parameter" seems much more common.

I'd suggest something like

> error: values of type `T` may contain data that does not live long enough

The exact wording is just a straw man, I don't think it's optimal.

**Comment by Mark-Simulacrum** [comment]
The note added today improves the situation but the main error message could still be enhanced.

```rust
struct Foo<T> {
    foo: &'static T
}
```

```
error[E0310]: the parameter type `T` may not live long enough
 --> test.rs:4:5
  |
4 |     foo: &'static T
  |     ^^^^^^^^^^^^^^^
  |
  = help: consider adding an explicit lifetime bound `T: 'static`...
note: ...so that the reference type `&'static T` does not outlive the data it points at
 --> test.rs:4:5
  |
4 |     foo: &'static T
  |     ^^^^^^^^^^^^^^^

error: aborting due to previous error(s)
```

**Comment by estebank** [comment]
Related: https://github.com/rust-lang/rust/issues/33652

**Comment by rkruppe** [comment]
I don't think this should have been closed. #44782 is a good improvement of the error message, but did not change the primary message. It still says "the parameter type `T` may not live long enough" which is bad for reasons described above.

(I can't re-open, could someone with more permissions do that please?)
