### ISSUE TITLE
Nested slice patterns are not checked for exhaustiveness

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#36728]
## Meta

```
$ rustc -V
rustc 1.13.0-dev (41e3aee3c 2016-09-23)
```

## STR

```Rust
#![feature(slice_patterns)]

fn main() {
    match [None::<String>] {
        [[Some(x)]..] => println!("{:?}", x)
    }
}
```

## Expected Result

Exhaustiveness Error

## Actual result

Code compiles and results in `unreachable`.

**Comment by bstrie** [comment]
This may not be the right place to ask this, but what's our policy on using the I-unsound tag on unstable features? I often filter issues via I-unsound specifically to see how many known soundness holes exist in stable Rust, which is diluted by including the unsoundess in unstable features (which, IMO, are generally expected to be WIP anyway so unsoundess isn't really a surprise).

On the other hand, stabilizing this feature would obviously first require this bug to be fixed. I don't want to remove the tag for now, so maybe I'll just give this B-unstable for now (though I'm not actually certain if that's what B-unstable is intended to be used for).

**Comment by arielb1** [comment]
duplicate of #26158.
