### ISSUE TITLE
Documentation of some macros has presentation problems

### ISSUE THREAD

**Issue by kumbayo** [rust-lang/rust#36722]
For some macros the documentation has presentation problems,
for others macros the documentation it is OK.
Problems:
- Variable names are not highlighted in blue
- There is an additional space between $ and the variable name (and in other places)
- Unexpected line breaks even when horizontal space is left (Might be a separate unrelated problem)

OK
![ok_macro_panic](https://cloud.githubusercontent.com/assets/1041267/18816982/5107d07a-8355-11e6-9fb4-ef0d9e995641.png)

Problematic
![error_macro_assert](https://cloud.githubusercontent.com/assets/1041267/18816985/570e974c-8355-11e6-88f5-add8dedf9374.png)

Problematic macros:
https://doc.rust-lang.org/std/macro.assert!.html
https://doc.rust-lang.org/std/macro.assert_eq!.html
https://doc.rust-lang.org/std/macro.try!.html
https://doc.rust-lang.org/std/macro.unreachable!.html
https://doc.rust-lang.org/std/macro.vec!.html (no problem of linebreaks here)
https://doc.rust-lang.org/std/macro.write!.html
...

Ok macros:
https://doc.rust-lang.org/std/macro.cfg!.html
https://doc.rust-lang.org/std/macro.concat!.html
https://doc.rust-lang.org/std/macro.env!.html
https://doc.rust-lang.org/std/macro.format_args!.html
https://doc.rust-lang.org/std/macro.panic!.html
...

It seems macros with "Stable since 1.0.0" are displayed properly?

Firefox 48.0, Ubuntu 16.04
Android, Chrome 53.0

**Comment by TimNN** [comment]
So I think that the situations is as follows:

* If a macro was defined in an extern crate (eg `core`) and then reexported in another crate (eg `std`):
    * stability information is lost
    * the actual source of the macro is lost / unavailable, so the parsed ast needs to be "pretty" printed (which doesn't really look pretty)
* If the macro was defined in the current crate, the actual source can be shown
* Also note: Some (or all of?) the macros you listed as "ok" are only *documented* in `std` but available in `core` as well as all other crates (since they are actually implemented in the compiler and the `macro_rules` are only there for documentation)

**Comment by durka** [comment]
Maybe there could be an attribute that causes a macro to be preserved in crate metadata as text, for use in documentation?

**Comment by durka** [comment]
Or we could run the deserialized text through rustfmt to at least make it readable.

**Comment by steveklabnik** [comment]
Triage: some of these are better, but not fixed yet.

**Comment by jyn514** [comment]
These are all fixed on master. Here's assert as an example: 
![image](https://user-images.githubusercontent.com/23638587/114078972-97c91500-9877-11eb-8379-b92336350f91.png)
