### ISSUE TITLE
Compiler doc build fails due to `-l` flag for compiler_builtins

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#36738]
https://github.com/rust-lang/rust/blob/9966397b61d5e065b692c59f4f721e31d038f1fc/mk/crates.mk#L81 adds a `-l` flag to  the `compiler_builtins` `$RUSTFLAGS`. This is also passed to rustdoc, which fails since rustdoc doesn't accept `-l` flags.

This makes the doc build for the internal docs fail.

cc @alexcrichton

**Comment by rkruppe** [comment]
Dupe of #36533
