### ISSUE TITLE
No warnings for unused variable assigned to wildcard

### ISSUE THREAD

**Issue by syml** [rust-lang/rust#36739]
fn main() {
let c = 0;
let _ = c;
}

doesn't produce any unused variable warnings.

**Comment by KalitaAlexey** [comment]
@syml Hi. What's problem?

**Comment by syml** [comment]
Well it could be that the user genuinely forgot such an "unused variable". There won't be warnings to help in that case.

**Comment by alexcrichton** [comment]
@syml we don't warn about "variable names" whose name starts with an `_`, so in this case the `let _ = c` isn't warned about (as we interpret it as "explicitly ignore this"). The `c` binding is then used as it's used in an assignment.

**Comment by syml** [comment]
Ok, thanks for the explanation.
