### ISSUE TITLE
TLS allocation failure appears to cause infinite panics

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#36749]
A panic will transitively attempt to access TLS, but TLS key allocation can fail. Looks like Gecko has [a pseudo-stack trace](https://gist.github.com/luser/650057bfc2ca2f88ea5a703fca0c77bb) which shows this.

We should handle this w/ an immediate abort instead of trying to keep calling the panic handler.  If we've still got it [this assertion](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/windows/thread_local.rs#L69) should be a `rtassert` instead of just an `assert`

**Comment by luser** [comment]
That pseudo-stack is from this user crash report here:
https://crash-stats.mozilla.com/report/index/1f1d41e2-e800-4230-884b-8a5842160925

**Comment by alexcrichton** [comment]
An alternative solution is to make TLS allocation infallible. Right now we don't use `#[thread_local]` on Windows, which I believe is infallible. I don't recall why, however, we don't use `#[thread_local]`!

**Comment by nagisa** [comment]
> On Windows operating systems before Windows Vista, __declspec( thread ) has some limitations. If a DLL declares any data or object as __declspec( thread ), it can cause a protection fault if dynamically loaded. After the DLL is loaded with LoadLibrary, it causes system failure whenever the code references the __declspec( thread ) data. Because the global variable space for a thread is allocated at run time, the size of this space is based on a calculation of the requirements of the application plus the requirements of all the DLLs that are statically linked. When you use LoadLibrary, you cannot extend this space to allow for the thread local variables declared with __declspec( thread ). Use the TLS APIs, such as TlsAlloc, in your DLL to allocate TLS if the DLL might be loaded with LoadLibrary.

Basically we might have to drop the WinXP support we have to use `#[thread_local]`.

**Comment by jackh726** [comment]
I'm going to close this, since there is no reproduction, and it's not clear that this is still a problem. The link in the OP to std code is broken.

I looked around a little bit, and I think [this](https://github.com/rust-lang/rust/blob/bf8716f1cd6416266807706bcae0ecb2e51c9d4a/library/std/src/sys_common/thread_local_key.rs#L137) is the equivalent code today. I see an rtassert and no assert.
