### ISSUE TITLE
Upgrade to macOS sierra: rustc randomly running @ 100% CPU

### ISSUE THREAD

**Issue by allthetime** [rust-lang/rust#36751]
So I've read that there are some outstanding issues with the new OSX, on top of that I have run into a perplexing issue.

I have a temperature and CPU monitor running at all times, and once in a while suddenly it jumps to 90 degrees and 100% CPU. The reason is `rustc`

I installed rust from source and wasn't aware that rust ran any background processes, so this activity is concerning. I usually have to kill it a few times before it stops, and I have no idea why, or where it is running from. Is this possible some kind of security issue on my end, or is there some cron job included in the rust installation for updating or something?

**Comment by alexcrichton** [comment]
Thanks for the report! What version of rustc were you compiling and/or running? There's a known pre 1.11.0-bug which we believe causes an issue like this.

**Comment by allthetime** [comment]
Hmm, I'm not sure actually. Doing `rustc --version` just returns

`rustc(69126,0x7fffb9a413c0) malloc: *** malloc_zone_unregister() failed for 0x7fffb9a37000`

I think it is 1.9.0 though, according the files in my `RUST_SRC_PATH`

I've attempted to install 1.13.0-dev but am getting an error during `make install`

`install: error: Option '--docdir=/usr/local/share/doc/rust' is not recognized`

I see it's referenced here though: https://github.com/rust-lang/rust/issues/36451 but I'm unclear on what the work around is... install nightly??

&nbsp;

&nbsp:

Sorry to dump this load on you, but can you offer any insight as to why rustc is trying to run in the background without any input from me? I've checked all my bash profiles and there's nothing there. It could be `racer` trying to start up in sublime or something.

Thanks for your attention on this issue.

**Comment by allthetime** [comment]
I installed nightly for now and everything is running smoothly.
