### ISSUE TITLE
Rustc version does not match manifest version

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust#36773]
Often the date given by `rustc --version` is the day before the date on the manifest. Also the date given by `cargo --version` often does not match one or both of those dates.

This is confusing for users installing a specific version of rust, and it makes referring to a nightly by date ambiguous.

Ideally there would be a mechanism to ensure that regardless of when the components are built or packaged, they all agree on the date given by `--version` and the manifest date.

**Comment by Diggsey** [comment]
This is causing confusion for people on IRC on almost a daily basis 🙁

**Comment by jyn514** [comment]
This is a duplicate of https://github.com/rust-lang/rust/issues/51533 (which was opened later but has more discussion).
