### ISSUE TITLE
Use quieter test output when running tests on Travis CI

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#36788]
Currently on Travis CI for this repository, running the full test suite results in one having to download the raw log because the entire log is too long to fit in Travis CI's web UI. It also causes my browser tab to halt for a few seconds to render. I propose we turn on the [quieter test output](https://github.com/rust-lang/rust/pull/31887) for test running on Travis CI. This will also make it easier to find test failures for PRs where there are failures.

**Comment by alexcrichton** [comment]
Sounds like a great idea!

**Comment by frewsxcv** [comment]
@alexcrichton Have any suggestions about how to accomplish this with rustbuild?

**Comment by alexcrichton** [comment]
Perhaps could be a `./configure` option which is threaded through to the tests themselves?

**Comment by frewsxcv** [comment]
Nevermind, I guess this was intentionally turned off in 2727866831190406ad13613d55c5846677b7d777

**Comment by alexcrichton** [comment]
Ah yeah this was explicitly re-enabled to help diagnose flaky failures we've been having.
