### ISSUE TITLE
rustbuild doesn't pass arguments to `check-std` tests

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#36785]
If e.g. I write `python2 src/bootstrap/bootstrap.py --stage 2 --step check-crate-std  --target=asmjs-unknown-emscripten -- --ignored`, I don't run the ignored tests like I would expect.

**Comment by Mark-Simulacrum** [comment]
The correct syntax is `--test-args --ignored` (though this obviously may not work, as they're usually ignored for a reason).
