### ISSUE TITLE
`impl Trait` ICE returning a recursive type

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#36792]
We were trying to make a function that returns itself.

``` rust
#![feature(conservative_impl_trait)]
fn foo() -> impl Copy {
    foo
}
```

rustc overflows its stack.

cc @aturon

**Comment by aturon** [comment]
cc @eddyb

**Comment by eddyb** [comment]
Well, you've sort of succeeded: what trans sees is `fn foo() -> typeof foo` (an infinitely recursive type).

However, I would've expected `traits::project` to catch this via the recursion limit, as the backtrace repeats `traits::project::AssociatedTypeNormalizer::fold_ty`. cc @nikomatsakis

**Comment by topecongiro** [comment]
rustc does not overflow its stack on `rustc 1.24.0-nightly (cddc4a62d 2017-12-26)`.
