### ISSUE TITLE
Crates and modules chapter formatting

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#36790]
There seems to be a formatting SNAFU in the [Crates and modules chapter](https://doc.rust-lang.org/stable/book/crates-and-modules.html#basic-terminology-crates-and-modules) of the Rust book (at least on Firefox), right after "We’ll use this module layout".

**Comment by rkruppe** [comment]
[Fixed on nightly.](https://doc.rust-lang.org/nightly/book/crates-and-modules.html#basic-terminology-crates-and-modules)
