### ISSUE TITLE
Lint errors resulting from lint groups or "warnings" meta-lint obscure the original lint name

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#36846]
This has frustrated me several times. Lint errors are at their best when they tell you which lint triggered them. Example

```
fn main() { }
fn foo() { }
```

```
warning: function is never used: `foo`, #[warn(dead_code)] on by default
 --> main.rs:2:1
  |
2 | fn foo() { }
  | ^^^^^^^^^^^^
```

So now I know that if the lint is wrong I can write `allow(dead_code)`. On the other hand:

```
#![deny(warnings)]
fn main() { }
fn foo() { }
```

```
error: function is never used: `foo`
 --> main.rs:3:1
  |
3 | fn foo() { }
  | ^^^^^^^^^^^^
  |
note: lint level defined here
 --> main.rs:1:9
  |
1 | #![deny(warnings)]
  |         ^^^^^^^^

error: aborting due to previous error
```

Now I have no idea what to write to shut the compiler up. Likewise:

```
#![deny(unused)]
fn main() { }
fn foo() { }
```

**Comment by brson** [comment]
cc @jonathandturner

**Comment by zackmdavis** [comment]
Adding the lint name to the message [when the source of the lint level was an attribute](https://github.com/rust-lang/rust/blob/b30022a1d/src/librustc/lint/context.rs#L464-L467) should be easy enough. I think we can do better, though, if we also add the attribute to the enum data [recording where the lint level was set](https://github.com/rust-lang/rust/blob/b30022a1d/src/librustc/lint/mod.rs#L306-L307); that way, we can only add the lint name to the message when it doesn't match the attribute (as for `#[deny(warnings)]` and the like) and not when it's obvious from the "lint level defined here" note.

I'm happy to work on this.

**Comment by jonathandturner** [comment]
@zackmdavis - sounds good.  Would be curious to see what the mockups of your changes would look like
