### ISSUE TITLE
librustc_llvm: call llvm-config with correct linking mode

### ISSUE THREAD

**Issue by chneukirchen** [rust-lang/rust#36854]
In 1.12, `src/librustc_llvm/build.rs` figures out which libraries it needs for external LLVM using `llvm-config --libs` which breaks if you have LLVM with `-DLLVM_BUILD_LLVM_DYLIB=ON` and `-DLLVM_LINK_LLVM_DYLIB=OFF` (which is needed for clang 3.9 these days), since then there is a dynamic `libLLVM3.9.so` and lots of `libLLVM*.a`, but the code sees the `libLLVM` and decides it has to link statically, which fails.

The code should decide whether to link static or dynamic first, and then call `llvm-config --libs --link-shared` resp `--link-static`, to get the correct library name.

**Comment by alexcrichton** [comment]
Thanks for the report! Sounds like it should be a relatively easy bug to tackle as well!

**Comment by chneukirchen** [comment]
In Void, we work around it by just adding `--link-static`, I guess for a general fix you need some policy how to link it.

https://github.com/voidlinux/void-packages/blob/79600b7b416c46191aefa079cd544c9a3b6779d7/srcpkgs/rust/patches/link-llvm-static.patch

**Comment by alexcrichton** [comment]
Oh we basically always want to link LLVM statically, so we can probably just always pass it.

**Comment by cuviper** [comment]
> Oh we basically always want to link LLVM statically, so we can probably just always pass it.

We emphatically *don't* want that in distro builds.  Would you accept a patch to make this conditional?

**Comment by alexcrichton** [comment]
@cuviper certainly!
