### ISSUE TITLE
Rust should pass the corresponding -O flag to emcc

### ISSUE THREAD

**Issue by tomaka** [rust-lang/rust#36897]
For example when compiling with `--opt-level=2`, Rustc should pass `-O2` to emcc.

However we may also want to pass `--memory-init-file 0`, otherwise emcc will generate a secondary `.mem` file. I'm not sure whether that's desired.

cc @brson

**Comment by alexcrichton** [comment]
This is [done now](https://github.com/rust-lang/rust/blob/f6d7514545cbe83e771a400d04049b96dfb210cd/src/librustc_trans/back/linker.rs#L671-L683)
