### ISSUE TITLE
Incorrect documentation for `write!` in `std::fmt`

### ISSUE THREAD

**Issue by c4rlo** [rust-lang/rust#36906]
The [`std::fmt` docs](https://doc.rust-lang.org/std/fmt/index.html#write) currently say about the `write!` macro:

> Under the hood, this function is actually invoking the `write` function defined in this module.

But in fact, `write!` is defined as calling the `write_fmt` method on its argument, as per [its documentation](https://doc.rust-lang.org/std/macro.write!.html).

**Comment by birryree** [comment]
I'd say clarification could be in order, but technically speaking, saying:

> Under the hood, this function is actually invoking the write function defined in this module.

is correct.

From `src/libcore/fmt/mod.rs:1133`:

`std::write!` invokes `write_fmt` which invokes `write`.

    /// Writes some formatted information into this instance
    #[stable(feature = "rust1", since = "1.0.0")]
    pub fn write_fmt(&mut self, fmt: Arguments) -> Result {
        write(self.buf, fmt)
    }
