### ISSUE TITLE
Alternate form print flag doesn't add padding correctly

### ISSUE THREAD

**Issue by cjm00** [rust-lang/rust#36911]
When running this code (on stable and nightly):
```
fn main() {
    println!("{:02x}", 9);  
    println!("{:#02x}", 9); 
}
```
I would expect to see
```
09
0x09
```
but what you actually get is:
```
09
0x9
```

Is this intended behavior?

**Comment by nagisa** [comment]
`02` gives 2 slots for the whole string, not the part after `0x`.

```
println!("{:#04x}", 0x9) # 0x09
```

**Comment by birryree** [comment]
(Probably) Intended behavior. Rust's `std::fmt` behavior mirrors that of C's `printf`-style formatting, where code similar to yours would result in the same output. Under `printf`-style behavior, the `0x` in hex formatting is considered as part of the characters when you want zero padding.

```
#include <stdio.h>

int main() {
    printf("%#02x", 9);
    return 0;
}
```

Output:

    0x9

**Comment by alexcrichton** [comment]
Yes this is currently intended behavior, although I forget if it was C it was mirroring or Python or whether it "just happened" ...
