### ISSUE TITLE
'Run' button on the nightly error index doesn't open playground

### ISSUE THREAD

**Issue by m-decoster** [rust-lang/rust#36910]
In the [compiler error index](https://doc.rust-lang.org/nightly/error-index.html), like in other parts of the documentation, it is possible to click a 'Run' button to open a playground containing the code from a `<code>` block. Unlike in other parts of the documentation, this does not work, and opens the same page in a new tab instead.

The issue in the page's HTML is that the `href` attribute of the `a` element that shows the button is blank:

`<a class="test-arrow" target="_blank" href="">Run</a>`.

In other parts of the documentation (e.g. [the rust reference](https://doc.rust-lang.org/nightly/reference.html)), this is not the case:

`<a class="test-arrow" target="_blank" href="https://play.rust-lang.org/?code=fn%20main()%20%7B%0A%20%20%20%20let%20a%20%3D%20%22foobar%22%3B%0Alet%20b%20%3D%20%22foo%5C%0A%20%20%20%20%20%20%20%20%20bar%22%3B%0A%0Aassert_eq!(a%2Cb)%3B%0A%7D">Run</a>`.

This is likely an issue in the HTML generation, but I have not pinned down where exactly the generation goes wrong.

**Comment by bluss** [comment]
I think this is just issue #36621

**Comment by m-decoster** [comment]
This issue will probably be solved when yours is solved, so should this be closed? @GuillaumeGomez

**Comment by bluss** [comment]
Closed as duplicate.

**Comment by bluss** [comment]
It doesn't look like this issue will be solved together with the other.
