### ISSUE TITLE
Segmentation fault when printing backtrace

### ISSUE THREAD

**Issue by DemiMarie** [rust-lang/rust#36919]
My [incomplete Scheme interpreter in Rust][1] builds and tests successfully.  However, if a call to `panic!()` is added at the end of `api::tests::intern_many_symbols`, and the tests are run with `RUST_BACKTRACE=1`, the program segfaults.

[1]: /DemiMarie/rusty_scheme

**Comment by Aatch** [comment]
Your library appears to make use of unsafe code. On top of that, the code as it currently stands doesn't appear to compile anyway, making it very difficult to know what is going on. If you could please 1) verify that this is in fact an error in the compiler or standard libraries and 2) try and construct a reproducible test case.

**Comment by DemiMarie** [comment]
@Aatch Check out my branch `reproduce-rustc-bug`.  It has an extremely minimal test case.

Basically, any panic from within a Cargo test causes a segfault when backtrace printing is enabled.

**Comment by alexcrichton** [comment]
@DemiMarie looking at that minimization, is it true that this segfaults?

```rust
#[test]
fn foo() {
    panic!();
}
```

```
$ RUST_BACKTRACE=1 rustc --test foo.rs
$ ./foo
```

If so, could you also gist information about your compiler? (e.g. `rustc -vV`)

**Comment by DemiMarie** [comment]
The following shell script reproduces the crash for me:

    unset CDPATH
    cargo new some-directory || exit 1
    cd some-directory || exit 1
    trap 'cd .. && rm -r some-directory' EXIT
    cat > src/lib.rs <<\EOF
    #[cfg(test)]
    mod test {
        #[test]
        fn it_works() {
             panic!()
        }
    }
    EOF
    RUST_BACKTRACE=1 cargo test

`rustc -vV` gives:

    rustc 1.14.0-nightly (289f3a4ca 2016-09-29)
    binary: rustc
    commit-hash: 289f3a4ca79916d6445b452fc19a18a1e42a879a
    commit-date: 2016-09-29
    host: x86_64-unknown-linux-gnu
    release: 1.14.0-nightly

**Comment by DemiMarie** [comment]
Update: I just recalled that I was using a snapshot of binutils, rather than a release, from installing a nightly GDB to get Rust support.  Reverting to the distribution binutils fixed the crash.

So this is probably a bug in the nightly version of binutils I was using.

**Comment by alexcrichton** [comment]
Ah ok, thanks for the update! In that case closing.
