### ISSUE TITLE
ICH: Function unsafety does not affect incr. comp. hash

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#36914]
See https://github.com/rust-lang/rust/issues/36812#issuecomment-250905199

**Comment by retep998** [comment]
Does function unsafety actually affect the generated code? Shouldn't it only affect whether you're allowed to perform certain operations?

**Comment by michaelwoerister** [comment]
I don't think it does yet but it likely will in the future because the compiler will be more conservative regarding optimizations around unsafe code. I think there's some information o that in http://smallcultfollowing.com/babysteps/blog/2016/05/27/the-tootsie-pop-model-for-unsafe-code.

Another thing to consider is that at some point we will cache more than just machine code, so if something influences just analysis, we also have to be able to track it.

**Comment by MathieuBordere** [comment]
make check is failing with `test [debuginfo-lldb] debuginfo-lldb/union-smoke.rs ... FAILED` will try to figure it out before I create a PR.

**Comment by michaelwoerister** [comment]
Fixed by #36974 with additional tests in #37072.
