### ISSUE TITLE
Invalid usage of `&mut self` in `std::sync::mpsc`

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#36934]
Almost all of the internal code in the `mpsc` module makes use of `&mut self`, which isn't valid because it's all explicitly designed to work across multiple threads, meaning the guarantees of `&mut self` don't hold. This entire implementation dates back to Fall 2013, which is long before the multithreading of `&self` vs `&mut self` was even decided!

We should update these implementation details to basically never use `&mut self` but instead use `UnsafeCell` where appropriate.

**Comment by jnicholls** [comment]
Could this be a root cause for why this unreachable is being hit, due to a spurious wake up? https://github.com/rust-lang/rust/blob/1.12.0/src/libstd/sync/mpsc/mod.rs#L880  Seeing Empty condition in 1.12.0.

**Comment by alexcrichton** [comment]
@jnicholls perhaps yeah, but AFAIK https://github.com/rust-lang/rust/pull/38421 didn't have any substantive change beyond a standard refactor, so my guess is that it'd be unlikely
