### ISSUE TITLE
Wording in Concurrency section

### ISSUE THREAD

**Issue by adrian5** [rust-lang/rust#36939]
https://github.com/rust-lang/rust/blob/master/src/doc/book/concurrency.md

> Rust's memory safety features also apply to its concurrency story too.

Also/too; I think the trailing too can just be gotten rid of.

> It allows the sharing of data between threads, but shared mutable data is unsafe and when threads are involved can cause data races!

Above sentence should use additional punctuation to make it more readable, e.g.:

> It allows the sharing of data between threads, but shared mutable data is unsafe and – when threads are involved – can cause data races!

**Comment by steveklabnik** [comment]
I would happily take a PR for this!
