### ISSUE TITLE
Tracking issue for {IpAddr,SockAddr}::ip_v{4,6} methods

### ISSUE THREAD

**Issue by achanda** [rust-lang/rust#36949]
These methods are proposed:
`IpAddr::is_ipv4()`
`SockAddr::is_ipv4()`
These return `true` if the underlying IP address is an IPv4 address.

`IpAddr::is_ipv6()`
`SockAddr::is_ipv6()`
These return `true` if the underlying IP address is an IPv6 address.

https://github.com/rust-lang/rust/pull/36707
https://github.com/rust-lang/rust/pull/36762

**Comment by achanda** [comment]
Can I propose stabilising these methods?

**Comment by alexcrichton** [comment]
Sounds reasonable to me!

@rfcbot fcp merge

**Comment by achanda** [comment]
Shouldn't @rfcbot mark this for FCP now?

**Comment by aturon** [comment]
Yes -- the bot has been buggy lately. Thanks for catching it -- I'll mark it manually.

🔔 **This issue is entering its final comment period for stabilization** 🔔

**Comment by achanda** [comment]
Sorry for bugging on this again, but shouldn't this be accepted now since it has been in FCP for more than a week?

**Comment by alexcrichton** [comment]
@achanda this is for stabilizing, so we'll have a batch PR that rounds up everything and stabilizes close to the end of the cycle.
