### ISSUE TITLE
Potential compile time regression in item-types checking

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#36947]
Diff: https://github.com/rust-lang/rust/compare/1cdc0fb11af12c04fb4b1984615f03b11a60decc...144af3e97aa30feba3d36a98ac04c0f1b2bc0bea

Perf.rlo [graph], though it basically just shows that item-types checking regressed from 0.67 to 1.006.

[graph]: http://perf.rust-lang.org/graphs.html?start=2016-09-26T11%3A25%3A58.000Z&end=2016-10-03T11%3A25%3A58.000Z&kind=benchmarks&group_by=phase&crates=issue-32278-big-array-of-strings&phases=AST%20validation%2CLLVM%20passes%2CMIR%20dump%2CMIR%20passes%2CPrepare%20MIR%20codegen%20passes%2Cassert%20dep%20graph%2Cassigning%20node%20ids%2Cattribute%20checking%2Cborrow%20checking%2Cchecking%20for%20inline%20asm%20in%20case%20the%20target%20doesn%27t%20support%20it%2Cchecking%20that%20all%20macro%20invocations%20are%20gone%2Ccoherence%20checking%2Ccollecting%20defs%2Ccomplete%20gated%20feature%20checking%2Ccomplete%20gated%20feature%20checking%201%2Ccomplete%20gated%20feature%20checking%202%2Ccompute_incremental_hashes_map%2Cconfiguration%2Cconfiguration%201%2Cconfiguration%202%2Cconst%20checking%2Cconst%20fn%20bodies%20and%20arguments%2Ccrate%20injection%2Cdeath%20checking%2Cdrop-impl%20checking%2Cearly%20lint%20checks%2Ceffect%20checking%2Cerasing%20regions%20from%20MIR%2Cexpansion%2Cexternal%20crate%2Flib%20resolution%2Cgated%20configuration%20checking%2Cgated%20macro%20checking%2Cindexing%20hir%2Cintrinsic%20checking%2Citem-bodies%20checking%2Citem-types%20checking%2Clanguage%20item%20collection%2Clifetime%20resolution%2Clinking%2Clint%20checking%2Cliveness%20checking%2Cload_dep_graph%2Clooking%20for%20entry%20point%2Clooking%20for%20plugin%20registrar%2Cloop%20checking%2Clowering%20ast%20-%3E%20hir%2Cmacro%20loading%2Cmatch%20checking%2Cmaybe%20building%20test%20harness%2Cmaybe%20creating%20a%20macro%20crate%2Cname%20resolution%2Cparsing%2Cplugin%20loading%2Cplugin%20registration%2Cprelude%20injection%2Cprivacy%20checking%2Creachability%20checking%2Crecursion%20limit%2Cregion%20resolution%2Cresolution%2Cresolving%20dependency%20formats%2Crvalue%20checking%2Cserialize%20dep%20graph%2Cserialize%20work%20products%2Cstability%20checking%2Cstability%20index%2Cstatic%20item%20recursion%20checking%2Ctotal%2Ctranslation%2Ctype%20collecting%2Cunused%20lib%20feature%20checking%2Cvariance%20inference%2Cwf%20checking

cc @brson (the commits in the range are from #36807).

IRC discussion has led @brson to believe that this is a result of memchr changes.

**Comment by brson** [comment]
The only thing in that patch that looks remotely performance sensitive to me is the inlining around memchr. If I accidentally switched the memchr implementation to the slow version, that would also explain it.

**Comment by brson** [comment]
The regression [disappeared](http://perf.rust-lang.org/graphs.html?start=2016-09-25T05%3A20%3A25%2B00%3A00&end=2016-10-04T02%3A36%3A27%2B00%3A00&kind=benchmarks&crates=issue-32278-big-array-of-strings&phases=item-types%20checking&group_by=phase).

**Comment by Mark-Simulacrum** [comment]
I guess this can then be closed, probably just noise.
