### ISSUE TITLE
Docs don't show that pointer::is_null() is defined only where T: Sized

### ISSUE THREAD

**Issue by Ms2ger** [rust-lang/rust#36952]

**Comment by xfix** [comment]
To clarify the issue, documentation says (there is also similar implementation for `mut` pointers):

```rust
impl<T> *const T where T: ?Sized
```

But that doesn't match the actual implementation where T has to be `Sized`.

**Comment by durka** [comment]
There's a `T: ?Sized` on the impl, but the actual function puts back `T: Sized` and the docs don't reflect this.

**Comment by bluss** [comment]
Looks like the usual cross crate doc inclusion issue. The methods are defined in core.

**Comment by Kixunil** [comment]
I've just encountered this issue. [Example](https://play.rust-lang.org/?gist=d1560528d215d399310b69fb56389557&version=stable&backtrace=0).

Any explanation why `T` must impl `Sized`? What's the correct approach to null-check in case of unsized types?

**Comment by Mark-Simulacrum** [comment]
Closing as a duplicate of https://github.com/rust-lang/rust/issues/24183.
