### ISSUE TITLE
Make rust-docs package optional, not installed by default

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#36970]
Today the rust-docs package is a required component. Now that rustup supports component installation it can be made optional. This change needs to be done in rust-buildbot.

**Comment by durka** [comment]
I think it should still be default. Nobody wants to discover at the airport that they should have included just one more rustup incantation.

**Comment by nagisa** [comment]
Very duplicate-ish of https://github.com/rust-lang/rust/issues/24117

**Comment by nagisa** [comment]
@brson why exactly changing defaults in rustup is not enough? Doesn’t it already download the separate packages?

**Comment by Mark-Simulacrum** [comment]
Making the docs component optional, but still installed by default seems like the way to go forward here; that should avoid the missing docs at airport problem, but still allow those who don't want docs to not have to download them.

**Comment by japaric** [comment]
[Rust documentation is now optional and opt-in when installing via rustup](https://users.rust-lang.org/t/psa-rust-documentation-is-now-optional-and-opt-in-when-installing-via-rustup/8072/1)

**Comment by alexcrichton** [comment]
This was done, and then undone, so I'm going to close.
