### ISSUE TITLE
Cannot view resources in Rust MSVC Windows binaries in Visual Studio

### ISSUE THREAD

**Issue by larsbergstrom** [rust-lang/rust#36985]
When you create a binary (dev or release) from Rust on Windows using the MSVC toolchain, it cannot be opened by Visual Studio for viewing the resources, etc. You will get the errors:

```
---------------------------
Microsoft Visual Studio
---------------------------
Cannot open file.
---------------------------
OK   
---------------------------
```

and then:

```
---------------------------
Microsoft Visual Studio
---------------------------
The system cannot open the device or file specified. (Exception from HRESULT: 0x8007006E)
---------------------------
OK   
---------------------------
```

Which err.exe tells me is:

```
  ERROR_OPEN_FAILED                                             winerror.h
# The system cannot open the device or file specified.
```

The test program I used is:

```
fn main() {
   println!("Hello, world");
}
```

And here's the compiler version and build steps (plus verification it works):

```
C:\Users\larsberg>rustc --version
rustc 1.12.0 (3191fbae9 2016-09-23)

C:\Users\larsberg>cd tmp

C:\Users\larsberg\tmp>rustc hello.rs

C:\Users\larsberg\tmp>hello
Hello, world

C:\Users\larsberg\tmp>
```

This is also reproducing in Servo builds: https://github.com/servo/servo/issues/13588

cc @alexcrichton

**Comment by larsbergstrom** [comment]
Note that you CAN still debug it (by doing File->Open project/solution) and then launching it.

(thanks, @windowsbunny!)

**Comment by alexcrichton** [comment]
@larsbergstrom could you clarify by what you mean here in terms of debugging the binaries? All I've ever done is the File->Open Project/Solution tactic, so I was completely unaware there was another...

**Comment by larsbergstrom** [comment]
@alexcrichton I've updated the bug title to reflect the actual issue VS is encountering in this path. Normally, when you use VS to open a binary, you can see the resources in it - the various strings, local, subsystem, embedded stuff (e.g., icons). Rust binaries must have something in there that is throwing VS off.

To be clear, since there's a workaround for debugging, it's definitely not high-pri, but I am curious what's getting embedded in the PE that is causing VS to error out.

**Comment by alexcrichton** [comment]
Ok, thanks for the update!

**Comment by wesleywiser** [comment]
I've retested this in VS 2022 and VS 2019 and both versions are able to open Rust binaries without error (but typically there is nothing to show as most crates don't embed icons or use embedded resource files).

![image](https://user-images.githubusercontent.com/831192/149168608-4c31d933-f43d-4ff4-b0ff-19867a0f6d2b.png)


I'm going to close this issue since it seems to have already been resolved.
