### ISSUE TITLE
`make install` doesn't work correctly with relative directory prefixes

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#36989]
When I configured with  `--prefix=install-prefix` and ran `make install`, my install ended up in `./tmp/empty_dir/install-prefix`.

**Comment by 0xmohit** [comment]
Seems to be because of `cd` [here](https://github.com/rust-lang/rust/blob/master/mk/install.mk#L11-L16) which was apparently added for #15558.

If the `cd` cannot be removed, then converting `DESTDIR` to absolute path before installing might work.

**Comment by Mark-Simulacrum** [comment]
I think this is still an issue with rustbuild, but should be somewhat easy to fix.. I think we just want to call canonicalize on the paths here: https://github.com/rust-lang/rust/blob/master/src/bootstrap/install.rs#L41. @alexcrichton Does that sound correct to you? If so, this is E-easy and E-mentor (by me).

**Comment by alexcrichton** [comment]
I believe so!

**Comment by toddboom** [comment]
@alexchrichton @Mark-Simulacrum I'll take a crack at this one if nobody else has started on it yet.

**Comment by Mark-Simulacrum** [comment]
Go ahead! Let us know if there's anything we can do to help you.

**Comment by toddboom** [comment]
Just an update - still working on this, just got buried in a move. Will try to get it knocked out this week.

**Comment by toddboom** [comment]
@Mark-Simulacrum @alexcrichton are there any unit-like tests that run against the install scripts? or do they just get tested as part of the full build?

**Comment by alexcrichton** [comment]
No unfortunately I don't think we test this step at all on CI :(

**Comment by jhgit** [comment]
canonicalizing the prefix breaks when prefix is a symbolic link.

e.g., /usr/local -> /some/other/location

Now if you want to install to <destdir>/usr/local, everything goes to <destdir>/some/other/location instead with many files including references to /some/other/location internally.

Now when I want to change the /usr/local sym link (in my case, the underlying location is a shared NFS mount point) to point to /a/different/location that contains the rust install, all the references to /some/other/location are wrong - leaving the best remaining option to recompile rust (and that's painful) on each occurrence where the underlying path pointed to by <prefix> is different.

There must be a better way to solve the relative path issue than by manually converting all sym links to their resolved paths.
