### ISSUE TITLE
`Foo::<>` does not use type parameter defaults

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#36980]
This is about the stable Rust feature that types can have type parameter defaults.

Example code below. I expected that if `Test::<T>::method` specifies one type parameter, and leaves the second to the defaulted, that `Test::<>::method` should leave both type parameters to be defaulted. Instead it is equivalent to `Test::method` (both type parameters inferred).

``` rust
#[derive(Default)]
pub struct Test<X = String, Y = String> {
    x: X,
    y: Y,
}

fn main() {
    // both explicit
    let s = Test::<f32, f32>::default();

    // use default for second
    let t = Test::<i32>::default();

    // use default for both? 
    // error[E0282]: unable to infer enough type information about `_`
    let u = Test::<>::default();

    // This uses the default for both.
    let u2 = <Test>::default();
}
```

[playground link](https://play.rust-lang.org/?gist=bb0ce46a76523d173cd47acb65005788&version=nightly&backtrace=0)

**Comment by petrochenkov** [comment]
This works as expected right now, but the rules are... counterintuitive.
Basically `<Test>`, `Test` (aka `Test::<>`) and `Test::<A, B, C>` use different rules - 1) defaults are used, nothing is inferred, 2) everything is inferred, defaults are not used 3) defaults are used, nothing is inferred.
I hope this can be fixed somehow by using inference and falling back to defaults, but any inaccurate step from the current rules is a breaking change unfortunately.
@eddyb should know more details.

**Comment by bluss** [comment]
@petrochenkov Ok, I'm reminded that `::<>` is valid on all types, I had forgot about that. Maybe this issue is a bit silly! It's still surprising that one can't reach the all defaults case using the regular path syntax.

**Comment by eddyb** [comment]
`::<>` is a noop, not sure if it should be or not. It is quite silly either way :disappointed:.

**Comment by steveklabnik** [comment]
Closing in favor of https://github.com/rust-lang-nursery/reference/issues/24
