### ISSUE TITLE
Building libstd without libcompiler_builtins

### ISSUE THREAD

**Issue by Zoxc** [rust-lang/rust#36990]
After [this mess](https://github.com/rust-lang/rust/pull/35021) there isn't a way to build `libstd` without building `libcompiler_builtins` (which is unable to build on my OS)

**Comment by Zoxc** [comment]
Could it be made a optional `std` dependency? That would work for me, since I build `std` out-of-tree with explicit features.

**Comment by Zoxc** [comment]
Actually I used Cargo's `[replace]` feature (which is broken) to replace `compiler_builtins` with a dummy crate.

**Comment by archshift** [comment]
This would be much appreciated.

**Comment by bjorn3** [comment]
compiler_builtins is unconditionally necessary when stack probing is enabled, as it is on x86_64. This is because rustc uses `__rust_probestack` as stack probe function and there is no system library providing this, just compiler_builtins. Why did compiler_builtins not compile on your system?

**Comment by Mark-Simulacrum** [comment]
Without details on the failed build I'm going to go ahead and close. I believe we currently support a Rust-only, but likely less optimized, compiler builtins (or are working towards that), which should be buildable pretty much everywhere Rust is.
