### ISSUE TITLE
The heart example in docs for std::char primitive is ambiguous

### ISSUE THREAD

**Issue by ljedrz** [rust-lang/rust#36998]
I was going through the [docs for std::char](https://doc.rust-lang.org/stable/std/primitive.char.html) and found out that the heart is at first encoded with two codepoints (❤️) and just one afterwards (❤). This is misleading, as the difference is not visible in the browser (at least not in Chrome) and the reader first sees information that:

> Trying to create a literal with let heart = '❤️'; gives an error

and afterwards there are perfectly valid examples like

```
for c in '❤'.escape_unicode() {
    print!("{}", c);
}
```

What makes matters worse is that they both start with the same code point; the second example I listed states that:

> This prints:
> `\u{2764}`

While in the first case there is:

> `assert_eq!(Some('\u{2764}'), iter.next());`
> `assert_eq!(Some('\u{fe0f}'), iter.next());`

I found this misleading and had to use a hex editor to discover the difference.

**Comment by steveklabnik** [comment]
Interesting, your browsers render these the same? They're very different here:

![2016-10-06-110402_213x56_scrot](https://cloud.githubusercontent.com/assets/27786/19157846/a1e6ff86-8bb4-11e6-84a9-958442972f5d.png)

**Comment by ljedrz** [comment]
Yes, and the same on my phone (Bugsplorer or Edge as they now call it). I will provide the desktop screenshot when I have the chance; I can attach a screenshot from my phone for now:
![wp_ss_20161006_0001](https://cloud.githubusercontent.com/assets/3750347/19159266/1518c8f4-8bec-11e6-9615-10f5f08ae5fb.png)

**Comment by ljedrz** [comment]
Screenshot from a PC using the current stable Chrome:

![image](https://cloud.githubusercontent.com/assets/3750347/19160278/91171c00-8bef-11e6-85fb-e3107aee47f4.png)

I think there is a little difference in size, but it's not apparent, since in the docs they are far apart.

At my work I also use Chrome with a different font and both hearts are plain black.

**Comment by ljedrz** [comment]
This is how the two-codepoint and one-codepoint examples look like in another Chrome; when formatted as code, they look the same:

![hearts](https://cloud.githubusercontent.com/assets/3750347/19183965/1ac343f8-8c7b-11e6-9e7e-320c1d715302.png)

**Comment by frewsxcv** [comment]
This will be fixed by https://github.com/rust-lang/rust/pull/43919.
