### ISSUE TITLE
Android bots may fail to come online

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#37005]
We've had tons of historical problems where our android builders fail to come online. I don't understand the precise reason but my best hunch is that the following sequence of events happens:
1. Buildbot spins up a new EC2 instance
2. Buildbot then decides to wait N seconds for this instance to connect to the buildmaster
3. The EC2 instance boots
4. The instance runs a startup script which runs a docker image
5. The [docker image](https://hub.docker.com/r/alexcrichton/rust-slave-android/tags/), being 2GB, takes awhile to download
6. Buildbot times out the instance, killing it

At that point we're in a state of limbo where the instance is then _later_ auto-shut down after an hour (presumably by some other buildbot system). Buildbot then refuses to bring another bot online, so we have to restart everything, killing LLVM caches and active instances.

I don't understand though why this doesn't plague the linux-cross images [which are also 2GB](https://hub.docker.com/r/alexcrichton/rust-slave-linux-cross/tags/). Maybe one's a bigger 2GB than the other...

**Comment by alexcrichton** [comment]
The plot thickens...

Startup script:

```
sleep 20 && docker run --privileged `curl -s http://169.254.169.254/latest/user-data | tail -n +2 | head -n 1`' 2>&1 | logger
```

that `curl` command returns

```
alexcrichton/rust-slave-android:2016-09-26
```

Sample output from `/var/log/syslog` that presumably just failed

```
[..]
Oct  6 18:23:19 ip-10-254-18-90 logger: 5118e66f5b88: Download complete
Oct  6 18:23:19 ip-10-254-18-90 logger: 80b5adf538d8: Verifying Checksum
Oct  6 18:23:19 ip-10-254-18-90 logger: 80b5adf538d8: Download complete
Oct  6 18:23:20 ip-10-254-18-90 logger: 436c176520d3: Verifying Checksum
Oct  6 18:23:20 ip-10-254-18-90 logger: 436c176520d3: Download complete
Oct  6 18:23:21 ip-10-254-18-90 logger: f20591fd81f5: Verifying Checksum
Oct  6 18:23:21 ip-10-254-18-90 logger: f20591fd81f5: Download complete
Oct  6 18:23:21 ip-10-254-18-90 logger: ee05860fd60c: Verifying Checksum
Oct  6 18:23:21 ip-10-254-18-90 logger: ee05860fd60c: Download complete
Oct  6 18:23:24 ip-10-254-18-90 logger: 97ee82faf4f8: Verifying Checksum
Oct  6 18:23:24 ip-10-254-18-90 logger: 97ee82faf4f8: Download complete
Oct  6 18:24:16 ip-10-254-18-90 logger: 5b7c374f521c: Verifying Checksum
Oct  6 18:24:16 ip-10-254-18-90 logger: 5b7c374f521c: Download complete
Oct  6 18:24:30 ip-10-254-18-90 logger: 3bc1bbaefa45: Verifying Checksum
Oct  6 18:24:30 ip-10-254-18-90 logger: 3bc1bbaefa45: Download complete
Oct  6 18:24:31 ip-10-254-18-90 logger: 436c176520d3: Pull complete
Oct  6 18:24:31 ip-10-254-18-90 logger: 67891c7e4743: Pull complete
Oct  6 18:24:31 ip-10-254-18-90 logger: 19d170efa81d: Pull complete
Oct  6 18:24:31 ip-10-254-18-90 logger: fc1d374b7277: Pull complete
Oct  6 18:24:31 ip-10-254-18-90 logger: b2a96566725c: Pull complete
Oct  6 18:24:32 ip-10-254-18-90 logger: 82a0656dd456: Pull complete
Oct  6 18:24:32 ip-10-254-18-90 logger: 3bb043260e66: Pull complete
Oct  6 18:24:34 ip-10-254-18-90 logger: 97ee82faf4f8: Pull complete
Oct  6 18:24:50 ip-10-254-18-90 logger: ee9790b19625: Verifying Checksum
Oct  6 18:24:50 ip-10-254-18-90 logger: Pulling repository docker.io/alexcrichton/rust-slave-android
Oct  6 18:24:50 ip-10-254-18-90 logger: Tag 2016-09-26 not found in repository docker.io/alexcrichton/rust-slave-android
```

when that tag definitely exists...

**Comment by alexcrichton** [comment]
I also vaguely remember seeing the other day an error about some stunnel port was already bound or already connected (after the docker container started). Absolutely no idea how that could have happened.

**Comment by Mark-Simulacrum** [comment]
I seem to recall that git doesn't by default pull tags, you need to do something special to get the tags. This might be completely misleading though.

**Comment by alexcrichton** [comment]
Buildbot's almost on its way out, so closing.
