### ISSUE TITLE
asm.js/wasm targets not usable on nightlies

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#37004]
While we produced asm.js/wasm targets on nightlies last night, the targets aren't actually usable on the standard suite of compilers. For example:

```
$ rustup target add asmjs-unknown-emscripten --toolchain nightly
$ cargo +nightly build --target asmjs-unknown-emscripten -v
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name _ --print=file-names --crate-type bin --crate-type rlib --target asmjs-unknown-emscripten` (exit code: 101)
--- stderr
error: Could not create LLVM TargetMachine for triple: asmjs-unknown-emscripten: No available targets are compatible with this triple. 
```

@tomaka pointed out to me that this is perhaps related to the fact that asmjs only works on rustbuild, not on the makefiles. The compiler I'm using was produced by the makefiles, so presumably it wasn't compiled with support for the asmjs target.

@brson this may necessitate an update to the makefiles :\

**Comment by jonas-schievink** [comment]
What's blocking building nightlies with rustbuild?
