### ISSUE TITLE
Document that RwLock might panic

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#37010]
[Like a `Mutex`](https://doc.rust-lang.org/std/sync/struct.Mutex.html#panics), [`RwLock` might panic](https://github.com/rust-lang/rust/blob/f796112/src/libstd/sys/unix/rwlock.rs#L59) if the current thread already holds a lock. This however is [not documented](https://doc.rust-lang.org/std/sync/struct.RwLock.html).

**Comment by retep998** [comment]
It might also not panic and simply deadlock. Or it might even cause [undefined behavior](https://github.com/rust-lang/rust/issues/35836).

**Comment by tmiasko** [comment]
Additionally [error checking is done only on debug mode](https://github.com/rust-lang/rust/issues/34966), so it can silently fail without actually locking anything.
