### ISSUE TITLE
Regression: Sized not satisfied

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#37019]
A [stable-to-beta crater report](https://gist.github.com/alexcrichton/ab516d4d73470c9da0884780d716fd2b) shows regressions related to 

```
error[E0277](B: the trait bound `Self: std::marker::Sized` is not satisfied(B 
```

* [cfg-regex-0.0.0](https://crates.io/crates/cfg-regex) ([before](https://tools.taskcluster.net/task-inspector/#xgIdOR1UR-qSgHtCXGrrgA)) ([after](https://tools.taskcluster.net/task-inspector/#W2d2wCIHTrKxGcSvevsCzQ))
* [lense-0.1.2](https://crates.io/crates/lense) ([before](https://tools.taskcluster.net/task-inspector/#kHC-Hz4xQamDb8aJKFa18g)) ([after](https://tools.taskcluster.net/task-inspector/#qLc6fa40TteSqWZk2JBSeQ))
* [mel-0.2.1](https://crates.io/crates/mel) ([before](https://tools.taskcluster.net/task-inspector/#hVRLN9LzS2WuPPg9w0yMTA)) ([after](https://tools.taskcluster.net/task-inspector/#1xSt0LvHQXmq1A3jurp6jQ))
* [rendarray-0.2.0-alpha.8](https://crates.io/crates/rendarray) ([before](https://tools.taskcluster.net/task-inspector/#w8dSdiddRCixQn326Qxp3A)) ([after](https://tools.taskcluster.net/task-inspector/#gkbATpMUSw-sU-4mUeLfRQ))
* [sprs-ldl-0.1.0](https://crates.io/crates/sprs-ldl) ([before](https://tools.taskcluster.net/task-inspector/#Ojybi4zLTWWD7qEOvI8Few)) ([after](https://tools.taskcluster.net/task-inspector/#C7cnAot1T_GaPm7PuG2t-g))
* [vectormath-0.1.1](https://crates.io/crates/vectormath) ([before](https://tools.taskcluster.net/task-inspector/#tufnKbaaQfaMPTSZ2Khkaw)) ([after](https://tools.taskcluster.net/task-inspector/#2HKJ6FYSSCmnBkcNQGMIaA))

I'm opening an issue to ensure that we're tracking these regressions and they're either expected (so we can close), this is a dupe (so we can close), or we can fix (and then close!)

cc @rust-lang/compiler

**Comment by nikomatsakis** [comment]
This is related to https://github.com/rust-lang/rust/issues/33242. We turned that warning into a hard error in https://github.com/rust-lang/rust/pull/34982, which included a thorough survey of users (some of which are listed above).

**Comment by nikomatsakis** [comment]
In other words: expected. :)

**Comment by alexcrichton** [comment]
Yay! In that case I'll close this in favor of the previous discussions
