### ISSUE TITLE
#[must_use] attribute showing up in rustdoc output

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#37012]
https://doc.rust-lang.org/nightly/std/iter/struct.Cycle.html

<img width="1011" alt="screen shot 2016-10-06 at 8 06 34 pm" src="https://cloud.githubusercontent.com/assets/416575/19174918/6b1ab8ac-8c00-11e6-800f-f70c4d84fd01.png">

**Comment by durka** [comment]
It always did. Is this bad? Maybe rustdoc should parse it and display it in a prettier way, like it does with `#[unstable]` and `#[deprecated]`?

**Comment by frewsxcv** [comment]
Will bring this up at the next Rust doc meeting.

**Comment by ollie27** [comment]
Looks like this is intentional #22224. There is probably a better way of displaying it though.

**Comment by nagisa** [comment]
We probably will want to show even more of these (e.g. the `repr()`) attributes. If showing it as a plain attribute is insufficient, the solution should be extensible.

**Comment by GuillaumeGomez** [comment]
This issue has been fixed by hiding attributes by default.
