### ISSUE TITLE
Regression: zero sized fn types now breaking three crates

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#37017]
A [stable-to-beta crater report](https://gist.github.com/alexcrichton/ab516d4d73470c9da0884780d716fd2b) shows three regressions related to 

```
error(B: `unsafe extern "C" fn(*mut libc::c_void, *mut libc::c_void) {zmq_free_fn}` is now zero-sized and has to be cast to a pointer before transmuting to `*mut unsafe extern "C" fn(*mut libc::c_void, *mut libc::c_void)`, #[deny(transmute_from_fn_item_types)] on by default(B 
```

* [td_rlua-0.1.3](https://crates.io/crates/td_rlua) ([before](https://tools.taskcluster.net/task-inspector/#xYw6l2tlQf-39kgsb9eBGw)) ([after](https://tools.taskcluster.net/task-inspector/#7GqQxRSXSVyennnSNNlxBg))
* [hlua_master-0.1.8](https://crates.io/crates/hlua_master) ([before](https://tools.taskcluster.net/task-inspector/#x82Cp13mTKC31hVWH2C7gw)) ([after](https://tools.taskcluster.net/task-inspector/#djsONy5LSmiGD_ITG4Cu4A))
* [zmq-rs-0.1.7](https://crates.io/crates/zmq-rs) ([before](https://tools.taskcluster.net/task-inspector/#f456PxD5TIiWpSu-O9U3UQ)) ([after](https://tools.taskcluster.net/task-inspector/#DfzkLbf4TfqaYKBZ998bpw))

I'm opening an issue to ensure that we're tracking these regressions and they're either expected (so we can close), this is a dupe (so we can close), or we can fix (and then close!)

cc @rust-lang/compiler

**Comment by nikomatsakis** [comment]
This is related to <https://github.com/rust-lang/rust/issues/19925>.

**Comment by TimNN** [comment]
* hlua_master was yanked (only one version released)
* zmq-rs is fixed on master (but not released)
* td_rlua is broken on master

**Comment by alexcrichton** [comment]
Ah indeed, right! Thanks for the info @nikomatsakis! I'll close this in favor of the prior discussions.
