### ISSUE TITLE
Regression: no method in scope

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#37021]
A [stable-to-beta crater report](https://gist.github.com/alexcrichton/ab516d4d73470c9da0884780d716fd2b) shows regressions related to 

```
error(B: no method named `read_u8` found for type `&mut R` in the current scope(B
  (B--> (Bsrc/reader/parser/macros.rs:27:47(B
   (B|(B
27(B (B| (B        let val = try_with_pos!($pos, $reader.(Bread_u8(B());(B
   (B| (B                                              (B^^^^^^^(B
   (B| (B
  (B::: (Bsrc/reader/parser/binary.rs(B
   (B|(B
88(B (B| (B        let type_code = (Btry_read_le_u8!(common.pos, reader)(B;(B
   (B| (B                        (B-----------------------------------(B in this macro invocation(B
   (B|(B
   (B= (Bhelp(B: items from traits can only be used if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:(B
   (B= (Bhelp(B: candidate #1: `use reader::parser::macros::byteorder::ReadBytesExt`(B

```

* [fbx_direct-0.6.1](https://crates.io/crates/fbx_direct) ([before](https://tools.taskcluster.net/task-inspector/#OqqihZFmRrSBE1gSvBCtFQ)) ([after](https://tools.taskcluster.net/task-inspector/#FnBo2jPyS6mvIzTX7EIE-w))

I'm opening an issue to ensure that we're tracking these regressions and they're either expected (so we can close), this is a dupe (so we can close), or we can fix (and then close!)

cc @rust-lang/compiler

**Comment by TimNN** [comment]
Also fixed by 37023.
