### ISSUE TITLE
Regression: unresolved import

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#37020]
A [stable-to-beta crater report](https://gist.github.com/alexcrichton/ab516d4d73470c9da0884780d716fd2b) shows regressions related to 

```
error[E0432](B: unresolved import `glium::glutin::VirtualKeyCode`(B
  (B--> (Bsrc/graphics.rs:80:9(B
   (B|(B
80(B (B| (B    use (Bglium::glutin::VirtualKeyCode as Gvkc(B;(B
   (B| (B        (B^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^(B Could not find `glutin` in `glium`(B

```

* [jamkit-0.3.1](https://crates.io/crates/jamkit) ([before](https://tools.taskcluster.net/task-inspector/#nwqm5CzhTwCqa1KZ2FPUbQ)) ([after](https://tools.taskcluster.net/task-inspector/#i9NJKAYkT5usQvG04StJpg))

I'm opening an issue to ensure that we're tracking these regressions and they're either expected (so we can close), this is a dupe (so we can close), or we can fix (and then close!)

cc @rust-lang/compiler, @jseyfried

**Comment by jseyfried** [comment]
Fixed in #37023.
