### ISSUE TITLE
Question on unwrap_or_default

### ISSUE THREAD

**Issue by lukas-123** [rust-lang/rust#37025]
Just a short question: What is the reason that unwrap_or_default is implemented for Option, but not for Result?

**Comment by apasel422** [comment]
I'm not sure why the method was left off `Result`, but it can be written almost as succinctly with:

```rust
some_result.unwrap_or_else(Default::default)
```

**Comment by devonhollowood** [comment]
Would you consider accepting a pull request which implements `unwrap_or_default` for `Result`, or would this need to go through the RFC process?

**Comment by leodasvacas** [comment]
It might not be a good thing to make unwrapping results more ergonomic.

**Comment by bluss** [comment]
@devonhollowood A guess: it sounds appropriate to be just a PR. The libs team will ask you to "escalate" it to an RFC only if it's needed.

**Comment by arthurprs** [comment]
It'd be nice to address this papercut.
