### ISSUE TITLE
MIR codegen attributes cleanups to beginning of the lexical block.

### ISSUE THREAD

**Issue by vadimcn** [rust-lang/rust#37032]
Compile this code with debug info (-g):
```rust
1: fn main() {
2:     zzz();
3:     let s = String::from("sss");
4:     zzz();
5: }
6: 
7: fn zzz() {}
```
Set a breakpoint on line 2 and start line-stepping.  The line position order will be something like this: 2, 3, 4, 3 (cleanup for `s`), 1 (epilogue for `main`).
I think everyone will agree that it would make much more sense to attribute the last two to line 5.

The fix will probably need to be done in [rustc_trans::mir::MirContext::trans_block](https://github.com/rust-lang/rust/blob/6e8f92f11cdc713ddec4c60c66097d05c194bab2/src/librustc_trans/mir/block.rs#L43).
Also, this probably means that `mir::SourceInfo` should carry a `Pos`, not a `Span` (we only ever use span.lo anyways).

**Comment by vadimcn** [comment]
cc @michaelwoerister, @eddyb.   Amirite about trans_block()?

**Comment by michaelwoerister** [comment]
I haven't looked at this in detail but I agree that it would make sense to associate cleanup with the end of the scope. Old-trans did it this way.
