### ISSUE TITLE
Documentation for VecDeque.insert is unclear

### ISSUE THREAD

**Issue by generalelectrix** [rust-lang/rust#37046]
The documentation for VecDeque.insert describes implementation details of how it internally rearranges the data structure which make it unclear on what the actual behavior of the method call is:

"Inserts an element at index within the VecDeque. Whichever end is closer to the insertion point will be moved to make room, and all the affected elements will be moved to new positions.

Element at index 0 is the front of the queue."

The doc should clearly state that the element will be inserted at this index and the existing element at this index will be pushed towards the _back_ of the deque.  The current doc makes it sound like which direction the existing element will be pushed towards could be different depending on that implementation detail.

**Comment by frewsxcv** [comment]
Opened a PR for this: https://github.com/rust-lang/rust/pull/38581
