### ISSUE TITLE
Pluralise '1 type parameters' in errors

### ISSUE THREAD

**Issue by Wilfred** [rust-lang/rust#37042]
Given the code:

``` rust
fn too_many_type_params() -> Option<i64, i64> {
    None
}
```

rustc reports:

```
error[E0244]: wrong number of type arguments
 --> <anon>:1:30
  |
1 | fn too_many_type_params() -> Option<i64, i64> {
  |                              ^^^^^^^^^^^^^^^^ expected 1 type arguments, found 2
```

Ideally error messages would use correct plurals, so 'expected 1 type argument, found 2' in this case.

**Comment by zackmdavis** [comment]
I guess I should start remembering to use "fixes" or "resolves" language so that GitHub can [close these automatically](https://help.github.com/articles/closing-issues-via-commit-messages/).

**Comment by Wilfred** [comment]
Let me do the honours :)
