### ISSUE TITLE
Type constraint is somehow changed to Fn

### ISSUE THREAD

**Issue by tmccombs** [rust-lang/rust#37063]
The [slog](https://crates.io/crates/slog) crate has a trait called (Serialize)[http://dpc.pw/slog-rs/slog/ser/trait.Serialize.html]. 

When I define a generic function with a type constraint on that trait, and pass a Serialize trait object to that function, I get an error that the trait bound isn't satisfied for `std::ops::Fn<(&'c slog::Record<'d>,)>`.

For example:

``` rust
#[macro_use]
extern crate slog;

use slog::*;

fn foo<T: Serialize>(t: &T) {

}


fn main() {
    let x: &Serialize = &5;
    foo(&x);
}
```

Gives me the error: 

```
error[E0277]: the trait bound `for<'c, 'd> slog::Serialize: std::ops::Fn<(&'c slog::Record<'d>,)>` is not satisfied
  --> src/main.rs:22:5
   |
22 |     foo(&x);
   |     ^^^
   |
   = note: required because of the requirements on the impl of `std::ops::FnOnce<(&'c slog::Record<'d>,)>` for `&slog::Serialize`
   = note: required because of the requirements on the impl of `slog::Serialize` for `&slog::Serialize`
   = note: required by `foo`

error[E0277]: the trait bound `for<'c, 'd> slog::Serialize: std::ops::FnOnce<(&'c slog::Record<'d>,)>` is not satisfied
  --> src/main.rs:22:5
   |
22 |     foo(&x);
   |     ^^^
   |
   = note: required because of the requirements on the impl of `slog::Serialize` for `&slog::Serialize`
   = note: required by `foo`

```

I have no idea what the problem is or where the `std::ops::Fn<(&'c slog::Record<'d>,)>` is coming from.

**Comment by sfackler** [comment]
It comes from this blanked implementation for `Serialize`: 

```rust
impl<S: 'static + Serialize, F> Serialize for F where F: 'static + for<'c, 'd> Fn(&'c Record<'d>) -> S
```

**Comment by tmccombs** [comment]
hmmm, is this expected behavior? If so, what exactly does the error mean?

**Comment by sfackler** [comment]
It's consistent behavior, but probably not good behavior :). I believe the chain of events that leads to that is basically: "Ok, S doesn't implement Serialize. I see that if it implemented `'static + for<'c, 'd> Fn(&'c Record<'d>) -> S`, it would implement Serialize, so I'll complain about that".
