### ISSUE TITLE
Support `is_letter()` on `char`.

### ISSUE THREAD

**Issue by daschl** [rust-lang/rust#37069]
Unicode defines the category `L` for letter similar to others. We already have different accessors on `char` based on unicode and it would make sense to also check if the `char` is on a letter boundary (so for example you can split on non-letter boundaries). Go has a similar function available in its unicode package: https://golang.org/pkg/unicode/#IsLetter

Right now I'm using the `unicode_categories` crate but I think it has some bugs and I wonder if such basic unicode properties on char make sense to be part of stdlib directly.

**Comment by estebank** [comment]
Doesn't [`char::is_alphabetic`](https://doc.rust-lang.org/beta/std/primitive.char.html#method.is_alphabetic) fulfill this need? After cursory look at [the code, it seems to be doing exactly what you'd want](https://github.com/rust-lang/rust/blob/13a2dd9/src/librustc_unicode/char.rs#L530-L552).

**Comment by frewsxcv** [comment]
From what I understand, "alphabetic" and "letter" are different:

> Alphabetic: Lu | Ll | Lt | Lm | Lo | Nl | Other_Alphabetic

-- http://unicode.org/reports/tr44/#Alphabetic

> Letter: Lu | Ll | Lt | Lm | Lo

-- http://unicode.org/reports/tr44/#General_Category_Values

**Comment by daschl** [comment]
I think @frewsxcv is right and I also think it makes sense to expose those "basic" unicode categories on char since its incredibly useful for tokenizers and the like.

**Comment by estebank** [comment]
#38137 tracks the stabilization `is_letter`, which is being introduced in PR #38125.

**Comment by SimonSapin** [comment]
> Right now I'm using the `unicode_categories` crate but I think it has some bugs

Have you opened issues for these bugs, or checked that they’re already in the issue tracker?

**Comment by daschl** [comment]
@SimonSapin yes and did address them subsequently https://github.com/swgillespie/unicode-categories/pull/5 . That said, I still think `is_letter` has its place int he standard library

**Comment by alexcrichton** [comment]
Proposed in https://github.com/rust-lang/rust/pull/38125 the libs team [decided to close](https://github.com/rust-lang/rust/pull/38125#issuecomment-274652959), so I'm going to close this as well.
