### ISSUE TITLE
Compiler accepts invalid UTF-8

### ISSUE THREAD

**Issue by DemiMarie** [rust-lang/rust#37076]
The compiler accepts this program, even though the character literal contains an invalid UTF-8 character:

```rust
fn main() {
    '\u{FFFE}';
}
```

Technically this results in the compiled code having Undefined Behavior (invalid UTF-8 in a char).  However, I find it dubious that Rust programmers should need to know every detail of the Unicode standard.

**Comment by bluss** [comment]
'`\u{FFFE}` is not invalid, it's apparently a *Noncharacter*.

Section 23.7 in unicode 9.0  [(PDF, 23 MB)](http://www.unicode.org/versions/Unicode9.0.0/UnicodeStandard-9.0.pdf)

> Applications are free to use any of these noncharacter code points internally. They have no
standard interpretation when exchanged outside the context of internal use. However, they
are not illegal in interchange, nor does their presence cause Unicode text to be ill-formed.
The  intent  of  noncharacters  is  that  they  are  permanently  prohibited  from  being  assigned
interchangeable meanings by the Unicode Standard. They are not prohibited from occur-
ring  in  valid  Unicode  strings  which  happen  to  be  interchanged.  This  distinction,  which
might be seen as too finely drawn, ensures that noncharacters are correctly preserved when
“interchanged” internally, as when used in strings in APIs, in other interprocess protocols,
or when stored.

It's also included explicitly in Section 3.9 under *Well-Formed UTF-8 Byte Sequences*

**Comment by DemiMarie** [comment]
@bluss That makes sense.  Closing.
