### ISSUE TITLE
Public extern functions no longer gets exported with LTO

### ISSUE THREAD

**Issue by Zoxc** [rust-lang/rust#37077]
Public extern functions no longer gets exported with `-C lto`.  Tested on 3210fd5c20ffc6da420eb00e60bdc8704577fd3b

In particular this breaks `rlibc`.

Related https://github.com/rust-lang/rust/issues/18134

**Comment by toothbrush7777777** [comment]
Is there any workaround?

**Comment by toothbrush7777777** [comment]
@Zoxc If the functions are included in the project, everything works as intended. If they are in an external rlib such as `rlibc`, the linker aborts due to ``undefined reference to `memset'``. Is this due to the `linkage(weak)` attribute?

**Comment by jackh726** [comment]
I'm going to close this since there is no reproduction (and the linked issue has been closed).
