### ISSUE TITLE
SipHasher::new_with_keys deprecation message is unhelpful/misleading

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#37070]
Since https://github.com/rust-lang/rust/pull/36815, using `SipHasher::new_with_keys` gives a warning:

```
warning: use of deprecated item: use `DefaultHasher` instead, #[warn(deprecated)] on by default
```

But `DefaultHasher` does not have a `new_with_keys` method or anything similar. It looks like this functionality was deprecated without replacement. Assuming the libs team does not want to revisit this decision, the deprecation message should be changed to… something.

Right now, the easiest "fix" for code using this method is to use `#[allow(deprecated)]`. Since the method is marked `#[stable]` it’s not going away any time soon, so this is quite safe. But of course, recommending `#[allow(deprecated)]` in a deprecation message would defeat the point of deprecation.

Perhaps a "proper" fix would be to maintain a (non-deprecated) copy of `SipHasher` on crates.io?

One notable user of this method is [`phf`](https://github.com/sfackler/rust-phf/blob/5f0856327731107d9fada1b0318f6f15f32957c2/phf_shared/src/lib.rs#L29). CC @sfackler

**Comment by aturon** [comment]
cc @rust-lang/libs

**Comment by sfackler** [comment]
Seems like we should copy the impls out to an external crate.

**Comment by alexcrichton** [comment]
Splitting out seems fine to me, but I believe the `siphash` crate was already taken last I checked.

**Comment by Mark-Simulacrum** [comment]
The `siphasher` crate now exposes this API, closing.
