### ISSUE TITLE
differentiate between guesses and suggestions in diagnostic messages

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#37085]
When the compiler or a lint don't have a true solution to the issue they encountered, they can't use a suggestion, because those are supposed to be correct. But some situations (like "name is not defined or in scope") can't possibly know how to correctly fix the issue. I suggest to add another diagnostic called "guess" (the bikeshed may be of any colour).

The regular text-report won't be changed (so `guess` shows up as `help` like it does right now). But the json output would contain the guesses for processing by IDEs and tools like [rustfix](https://github.com/killercup/rustfix).

This way, suggestions can be automatically applied and guesses require user interaction to apply them.

The [json diagnostic structs](https://github.com/rust-lang/rust/blob/91f34c0c70746f5c938d25d02a8a66b41240b2f0/src/libsyntax/json.rs#L93) will be extended this way:

```rust
    /// A list of code snippets that could be used to replace the span,
    /// but may contain wrong suggestions. The user needs to take care
    /// to select the correct one or even ignore all of them.
    guesses: Vec<String>,
```

**Comment by sanxiyn** [comment]
Isn't this #33691?

**Comment by oli-obk** [comment]
Jup, it is
