### ISSUE TITLE
Investigate using /debug:fastlink

### ISSUE THREAD

**Issue by retep998** [rust-lang/rust#37101]
VS 2015 adds a new linker argument `/debug:fastlink` which saves time by not actually putting symbol information inside the PDB but instead simply references the object files and libraries provided as input. VS "15" makes it even faster. However, this does require that all the object files and libraries are still around when debugging the binary, and I believe rustc currently disposes of the object file immediately after passing it to the linker.

For more information, including some performance numbers:
https://blogs.msdn.microsoft.com/vcblog/2016/10/05/faster-c-build-cycle-in-vs-15-with-debugfastlink/

**Comment by Tomcc** [comment]
3 years later, [the gap between fastlink and full link has increased even further](https://devblogs.microsoft.com/cppblog/improved-linker-fundamentals-in-visual-studio-2019/).
When I googled "rust fastlink" I didn't expect to find a 3 year old issue with 0 comments, hopefully something can be done about that :P

**Comment by schulzch** [comment]
I think the right place to play around with these kind of flags would be [linker.rs:debuginfo()](https://github.com/rust-lang/rust/blob/b7820b28937ba875521a2525cf75223c80faf9f2/src/librustc_codegen_ssa/back/linker.rs#L634) or [windows_msvc_base.rs](https://github.com/rust-lang/rust/blob/50ffa79589600f515ff2710830c23cd2dce7cb76/src/librustc_target/spec/windows_msvc_base.rs#L8).

**Comment by wesleywiser** [comment]
Visited during wg-debugging triage. Would be great to have this implemented and I think the work on split-DWARF's unpacked representation might have put some of the necessary pieces in place to preserve the intermediate object files after compilation.

**Comment by workingjubilee** [comment]
[The documentation](https://learn.microsoft.com/en-us/cpp/build/reference/debug-generate-debug-info?view=msvc-170#remarks) now says:

> Since Visual Studio 2019, /DEBUG:FULL linking times have improved significantly, and /DEBUG:FASTLINK isn't always faster than /DEBUG:FULL. Since /DEBUG:FASTLINK no longer provides large build time improvements and results in a slower debugging experience versus /DEBUG:FULL, this option is no longer recommended.

so uhh investigated? and decided as resolved?? I guess???
