### ISSUE TITLE
rustc runs out of memory when compiling an invalid macro

### ISSUE THREAD

**Issue by jbendig** [rust-lang/rust#37113]
Compiling this invalid macro code with rustc causes all system memory to be used up until the process is killed.

```rust
macro_rules! test_macro {
    ( $( $t:ty ),* $(),*) => {
        enum SomeEnum {
            $( $t, )*
        };
    };
}

fn main() {
    test_macro!(String,);
}
```

I expected rustc to display an error message and return immediately. Instead, an error message is reported and then rustc hangs and eats up all available system memory.

I tried both stable and nightly:
  - stable-x86_64-unknown-linux-gnu - rustc 1.12.0 (3191fbae9 2016-09-23)
  - nightly-x86_64-unknown-linux-gnu - rustc 1.14.0-nightly (a3bc191b5 2016-10-10)

I think this might be related to #33136.

**Comment by jonas-schievink** [comment]
cc @TimNN, who I think has (had?) a fix for this

**Comment by TimNN** [comment]
I'm pretty sure this is a different issue (here, OOM occurs due to the error), my fix for empty repetitions has been merged.

My guess is that this is somehow related to parser recovery.
