### ISSUE TITLE
[goal] modifying private method in impl should not require users of public methods to recompile

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#37121]
One of the goals for the first alpha is that if you change the **body** of a private, inherent method, it should not cause the _callers_ of public methods to recompile, nor to require type-checking. 

Currently, however, it does. There are two reasons for this. Fixing either of these would fix the immediate problem described in this issue. Fixing both would be ideal.
- #35078 -- method body and signature are not separated
  - this means that changing the _body_ of a private method is considered to potentially change its signature 
- #36349 -- methods do not get their own dep-node, just impls
  - this means that changing the body of a private method also contaminates the entire impl, which in turn contaminates the list of inherent methods

**Comment by nikomatsakis** [comment]
There are test cases checked in that reference this issue with `FIXME(#37121)` markers (or will be shortly).

**Comment by petrochenkov** [comment]
Does this goal apply to methods using `impl Trait`?
```
struct S;

impl S {
    pub fn public() -> impl Clone {
        S::private()
    }
    fn private() -> impl Clone {
        0u8
    }
}
```

**Comment by steveklabnik** [comment]
> One of the goals for the first alpha

To be clear, this is about goals for incremental recompilation?

**Comment by nikomatsakis** [comment]
@petrochenkov 

> Does this goal apply to methods using impl Trait?

No, clearly not. I didn't mean this in a blanket way ("no possible change!"). But I meant "most of the time."

-----

@steveklabnik 

> To be clear, this is about goals for incremental recompilation?

right.

**Comment by nikomatsakis** [comment]
@petrochenkov but good point, that'd make a nice test case :)
