### ISSUE TITLE
double free corruption when trying to compile to emscripten

### ISSUE THREAD

**Issue by zbraniecki** [rust-lang/rust#37130]
When compiling this: https://pastebin.mozilla.org/8918190

using: "rustc --target=asmjs-unknown-emscripten hello.rs"
following instructions from https://users.rust-lang.org/t/compiling-to-the-web-with-rust-and-emscripten/7627

I'm getting this crash: https://pastebin.mozilla.org/8918194

CC' @brson

**Comment by brson** [comment]
Unfortunately that pastebins show up as empty today. Sad 😭 .

**Comment by alexcrichton** [comment]
I'm going to close this because unfortunately the pastebins are gone
