### ISSUE TITLE
Color codes in docs are like chaos

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#37147]
A good example is: https://github.com/rust-lang/rust/pull/37102#issuecomment-253204807

Keywords should have one color code.
Enums should have another color code.
Structs should have another color code.
...

Color codes are up to debate. I'll start to clean this up soon.

cc @eddyb

**Comment by eddyb** [comment]
What kate does, which works well for me, is bold keywords (real bold, not like that `?` in the linked issue),
and colors for things like macros or literals.
You can ignore one kind of information ("channel") to spot the other, easily. This principle can be extended to full HSL (each of hue, saturation and luminance being used for different semantic values).

If only one "channel" is used (e.g. hue), then it's much harder to distinguish between various intents.
That and striking colors should not be used for every other word, it leads to semantic satiation.

Example from kate (I really wish bold `?` were bolder :disappointed:):
![image](https://cloud.githubusercontent.com/assets/77424/19360619/f0ca395a-9187-11e6-8e6b-e8a8b8046441.png)

**Comment by eddyb** [comment]
cc @rust-lang/docs (also not sure how to ping the style team)

**Comment by GuillaumeGomez** [comment]
It seems to consider `Ok` as keyword. :-/

**Comment by eddyb** [comment]
Well, [it seems a bit silly](https://quickgit.kde.org/?p=syntax-highlighting.git&a=blob&h=89a25f326c33027266f96b13824af1ec5c6e5aa1&hb=df3c35ca2227a40b14760613056765741d653ffe&f=data%2Fsyntax%2Frust.xml):
```xml
        <list name="constants">
                <item> true </item>
                <item> false </item>
                <item> Some </item>
                <item> None </item>
                <item> Ok </item>
                <item> Err </item>
                <item> Success </item>
                <item> Failure </item>
                <item> Cons </item>
                <item> Nil </item>
        </list>
```
Out of those variants only `Some`, `None`, `Ok` and `Err` remain, and they're not keywords, unlike `true` and `false`. It's not exactly been thoroughly updated. *However*:
```xml
<keyword String="constants" attribute="Constant" context="#stay"/>
```
```xml
<itemData name="Constant"     defStyleNum="dsConstant" spellChecking="0"/>
```
And `dsConstant` is distinct from `dsKeyword`, so *I can* change it in the editor settings, if I want to.

**Comment by GuillaumeGomez** [comment]
You should! :p

**Comment by Mark-Simulacrum** [comment]
@GuillaumeGomez Is this something you still want to pursue? I've marked as T-doc.

**Comment by GuillaumeGomez** [comment]
@Mark-Simulacrum: It's still in discussion actually, so yes. :)

**Comment by steveklabnik** [comment]
Closing, as this is not super-actionable as is and many fixes have landed.
