### ISSUE TITLE
Better handling of following symlinks in std

### ISSUE THREAD

**Issue by nivekuil** [rust-lang/rust#37204]
The current convention in the standard library is to follow symlinks by default and have another function that doesn't follow symlinks, as in `fs::metadata` and `fs::symlink_metadata`. This convention isn't very extensible (e.g. I'd like to have a `path.symlink_exists()` that doesn't follow symlinks like `path.exists()`), and the naming isn't especially clear (symlink_metadata suggests that it only gets the metadata of a symlink).

A better way to do this might be to copy the method chaining model of DirBuilder by adding a
`fn follow(&mut self, follow_symlinks: bool) -> &mut Self` 
for Path (or PathBuf?) that modifies itself to follow symlinks. I'd like to work on this if desirable.

**Comment by Mark-Simulacrum** [comment]
@rust-lang/libs, do we want this? It seems like a rather hard-to-follow feature since distant code could change the semantics of local code; marking a `Path` as a "symlink follower" seems odd.

**Comment by BurntSushi** [comment]
This does indeed seem odd to me. A `Path` is a file path, and adding state to it regarding its symlink behavior in various functions does indeed seem very strange to me.

I feel like I sympathize with the frustration for the current design, but it's informed by the lower level APIs that everyone already knows and loves. If there's a better API to be had, I think I'd rather see that experimentation done on crates.io.

**Comment by sfackler** [comment]
I'm also a bit suspicious of the "action at a distance" this would cause.

In any case, I don't think this can actually be implemented since there's nowhere to put that boolean. `Path` needs to have a compatible representation with `&str` so the `AsRef<Path>` implementation can work.

**Comment by alexcrichton** [comment]
This was discussed in a libs triage meeting and the decision was to close (rationale listed above), so closing.
