### ISSUE TITLE
Macro declarations do not work in impl blocks

### ISSUE THREAD

**Issue by KiChjang** [rust-lang/rust#37205]
Minimal test case:

``` rust
struct Foo;

impl Foo {
    macro_rules! bar {
        () => (
            println!("Hi");
        );
    }

    pub fn say() {
        bar!();
    }
}

fn main() {
    Foo::say();
}
```

On stable it emits the following error:

```
rustc 1.12.0 (3191fbae9 2016-09-23)
error: expected one of `const`, `default`, `extern`, `fn`, `pub`, `type`, `unsafe`, or `}`, found `macro_rules`
 --> <anon>:4:5
  |
4 |     macro_rules! bar {
  |     ^^^^^^^^^^^

error: aborting due to previous error
```

And on beta or nightly, it emits the following instead:

```
rustc 1.14.0-nightly (6e8f92f11 2016-10-07)
error: expected open delimiter
 --> <anon>:4:18
  |
4 |     macro_rules! bar {
  |                  ^^^

error: aborting due to previous error
```

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by Centril** [comment]
Triage: we now emit:
```
error: macro definition is not supported in `trait`s or `impl`s
 --> src/main.rs:4:5
  |
4 |     macro_rules! bar {
  |     ^^^^^^^^^^^^^^^^

error: cannot find macro `bar` in this scope
  --> src/main.rs:11:9
   |
11 |         bar!();
   |         ^^^

error: aborting due to 2 previous errors
```

@KiChjang do you expect the example to compile successfully? If not, I think we can close.

**Comment by KiChjang** [comment]
It should compile, yes. I haven't heard a specific reason why we shouldn't allow macro declarations in impl blocks.

**Comment by Centril** [comment]
I'm not sure exactly how such a thing would interact with resolve, if e.g., the impl has type parameters... is this macro only local to the impl, and what about if it is exported?

cc @petrochenkov

**Comment by petrochenkov** [comment]
>I haven't heard a specific reason why we shouldn't allow macro declarations in impl blocks.

Why should we?
Impls are entirely about type-relative stuff.
We don't have associated macros, we don't want to resolve macros during type-checking, so we don't support macros in impls.

We could implement this only for `macro_rules` with their `let`-like scoping and not for `macro` items, but it would be strange to support a new exclusive feature for something we eventually want to replace.

**Comment by KiChjang** [comment]
This issue was created before macro items were introduced, so if that can introduce proper scoping so that it's able to be used in methods, then there's no need to have macro declarations in impl blocks.
