### ISSUE TITLE
-Cpanic=unwind requires private libgcc_s symbols that are not provided by LLVM libunwind

### ISSUE THREAD

**Issue by whitequark** [rust-lang/rust#37203]
Specifically, these:
- `_Unwind_GetIPInfo`
- `_Unwind_GetDataRelBase`
- `_Unwind_GetTextRelBase`

**Comment by eddyb** [comment]
cc @rust-lang/libs

**Comment by whitequark** [comment]
Relevant GCC bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=27880. Looks like this ought to be possible to disable with some `#[cfg]`, but I'm not sure which exactly.

**Comment by whitequark** [comment]
I'm currently using the following modification locally:
```
diff --git a/src/libpanic_unwind/gcc.rs b/src/libpanic_unwind/gcc.rs
index f9d55e0..3b0e314 100644
--- a/src/libpanic_unwind/gcc.rs
+++ b/src/libpanic_unwind/gcc.rs
@@ -252,6 +252,7 @@ unsafe extern "C" fn rust_eh_personality(state: uw::_Unwind_State,
     }
 }
 
+#[cfg(not(llvm_libunwind))]
 unsafe fn find_eh_action(context: *mut uw::_Unwind_Context) -> EHAction {
     let lsda = uw::_Unwind_GetLanguageSpecificData(context) as *const u8;
     let mut ip_before_instr: c_int = 0;
@@ -267,6 +268,21 @@ unsafe fn find_eh_action(context: *mut uw::_Unwind_Context) -> EHAction {
     eh::find_eh_action(lsda, &eh_context)
 }
 
+#[cfg(llvm_libunwind)]
+unsafe fn find_eh_action(context: *mut uw::_Unwind_Context) -> EHAction {
+    let lsda = uw::_Unwind_GetLanguageSpecificData(context) as *const u8;
+    let ip = uw::_Unwind_GetIP(context);
+    let eh_context = EHContext {
+        // The return address points 1 byte past the call instruction,
+        // which could be in the next IP range in LSDA range table.
+        ip: ip,
+        func_start: uw::_Unwind_GetRegionStart(context),
+        get_text_start: &|| unimplemented!(),
+        get_data_start: &|| unimplemented!(),
+    };
+    eh::find_eh_action(lsda, &eh_context)
+}
+
 // *** Delete after a new snapshot ***
 #[cfg(all(stage0, any(target_os = "ios", not(target_arch = "arm"))))]
 #[lang = "eh_personality_catch"]
```

**Comment by alexcrichton** [comment]
I'm not sure I quite understand what's going on here, what are the ramification of this and how is it being detected? The musl target links to what I thought was LLVM's libunwind and works the same as the glibc target, so... I'm not sure how to rationalize that with this.

**Comment by whitequark** [comment]
> I'm not sure I quite understand what's going on here, what are the ramification of this

The functions above are not part of the Itanium C++ EHABI, they are private functions added to libgcc_s and not standardized anywhere. LLVM's libunwind never even mentions these symbols so the musl target must be defining them on its own somehow.

> and how is it being detected?

It's not. I have a custom build script for my target that passes a --cfg.

**Comment by whitequark** [comment]
I figured it out. It's a GCC extension that LLVM libunwind simply defines to abort. There is no need in any change to Rust.

https://github.com/llvm-mirror/libunwind/blob/a2a8dc6252792240c486c890fe09c47ec2b933af/src/UnwindLevel1-gcc-ext.c#L64-L81
