### ISSUE TITLE
semicolon check in macro needs improving

### ISSUE THREAD

**Issue by bombless** [rust-lang/rust#37217]
https://play.rust-lang.org/?gist=9aca9a98b74f8a4522df7b0d16c8340e&version=beta&backtrace=0&run=1

I think the warning message here is not intentional.

**Comment by TimNN** [comment]
I'm pretty sure the warning message works as intended:

The first macro invocation (`own!(a, b);`) expands to `own!(@a) own!(@b)` which, if written in normal rust code, would produce a hard error. This was previously accepted by the compiler, but now triggers the warning introduced in #34660.

**Comment by bombless** [comment]
Hmm then the warning should be turned into an hard error now, I guess, thanks @TimNN

**Comment by bombless** [comment]
May I ask, why is the semicolon after `to_owned()` dropped in the `(@$x:ident) => { let $x = $x.to_owned(); };` part?
I figure it might be the root case that bug existed, which I don't really understand.

**Comment by TimNN** [comment]
I don't think that semicolon is dropped. However, as far as I know, macros are expanded in multiple steps: `own!(a, b);` is expanded to `own!(@a) own!(@b)`, which then parsed again and expanded to `let a = ...; let b = ...;` The warning is reported for the intermediate expansion, not the final one: the semicolons added by the `(@$x:ident)` rule don't exist yet.
