### ISSUE TITLE
Complete type inference implementation details

### ISSUE THREAD

**Issue by kelcecil** [rust-lang/rust#37226]
I notice when looking at the [README doc](https://github.com/rust-lang/rust/blob/master/src/librustc/infer/README.md) for librustc/infer that the last line under the header "Implementation details" directs the reader to refer to a section "Type Combining" that doesn't exist. It appears this documentation was either never completed or wasn't completely copied from it's origin. It would be nice to either have the completed documentation/explanation or to remove the text that points to nowhere.

**Comment by Kha** [comment]
The remainder of the comment is here: https://github.com/rust-lang/rust/blob/6dc035ed911672c6a1f7afc9eed15fb08e574e5b/src/librustc/infer/combine.rs#L12
