### ISSUE TITLE
Invalid instructions (UMAAL) are generated for the thumbv7m-none-eabi target

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#37227]
UMAAL is only available in the ARMv7E-M processors but if you compile `core` for the `thumbv7m` (ARMv7-M) target, `rustc`/LLVM generates them for the `core::num::flt2dec::strategy::grisu::format_shortest_opt` function.

**Comment by japaric** [comment]
Relevant information: See the ARM Cortex-M instructions groups table under [instructions sets](https://en.wikipedia.org/wiki/ARM_Cortex-M#Instruction_sets). UMAAL is in the group of instructions that are not available for the Cortex-M3, which is the processor the thumbv7m target covers.

Building core with a explicit `-C target-cpu=cortex-m3` still generates the UMAAL instruction. This seems like a bug in LLVM.

**Comment by pftbest** [comment]
Minimal IR that triggers the problem:
[bugpoint-reduced-simplified.ll](https://gist.github.com/pftbest/775d8b925bce4e72cedbe5f58d4fe6ac)
It generates umaal instruction when is compiled by `llc`

**Comment by pftbest** [comment]
I have submitted the fix for review:
https://reviews.llvm.org/D25890

**Comment by pftbest** [comment]
Fixed in llvm upstream, r285278 and r285280

**Comment by pftbest** [comment]
How does llvm version gets updated? Do I need to backport this fix to llvm 3.9 somehow, so it could land in rust?

**Comment by alexcrichton** [comment]
@pftbest nice! To update LLVM there's two routes:

1. Backport the patches to our fork, currently around the 3.9 release.
2. Upgrade our fork to the current LLVM head

(1) is much easier than (2) typically, and we're fine with both!

**Comment by pftbest** [comment]
So, I've rebased `rust-llvm-2016-07-09` branch to match llvm version `3.9.1` and then I backported my fix on top of it. The new branch is called [`rust-llvm-2016-10-29`](https://github.com/pftbest/llvm/tree/rust-llvm-2016-10-29) and I don't know what to do next.

**Comment by japaric** [comment]
@pftbest I think:

- Locally, make the rust repo's llvm submodule point to your 10-29 branch and test (`make check`) locally.
- If that works, ask a core member to create a new 10-29 branch in rust-lang/llvm
- Then send another PR to rust-lang/rust updating its llvm submodule to the new branch in rust-lang/llvm
- Cross your fingers and hope that it passes the buildbots.

**Comment by alexcrichton** [comment]
Ok I've [pushed your branch](https://github.com/rust-lang/llvm/commits/rust-llvm-2016-10-29) to rust-lang/llvm (thanks for the rebase to 3.9.1!). As @japaric mentioned if you want to send a PR to rust-lang/rust updating the submodule I'll r+ that

**Comment by pftbest** [comment]
Thank you! I have submitted a #37465
