### ISSUE TITLE
Slowdown with -C panic=abort

### ISSUE THREAD

**Issue by Digipom** [rust-lang/rust#37235]
Hi team, I decided to check out https://www.reddit.com/r/rust/comments/3wxi9x/why_is_rust_much_slower_than_swift_in_this_simple/ and wanted to see what kind of an impact the new panic=abort flag would have, and I noticed that this microbenchmark actually takes longer to run if -C panic=abort is passed on the command line.

Code:

```
fn fib(n: i64) -> i64 {
    if n <= 2 {
        1
    } else {
        fib(n - 1) + fib(n - 2)
    }
}

fn main() {
    let num = 45;
    println!("{}", fib(num))
}
```

> rustc --version
> rustc 1.12.0 (3191fbae9 2016-09-23)

Using the 'stable' branch of the compiler. 

Without panic=abort:

```
rustc -O fib.rs -o fib_rs
time ./fib_rs
1134903170

real    0m1.866s
user    0m1.861s
sys     0m0.003s
```

With panic=abort:

```
rustc -O fib.rs -C panic=abort -o fib_rs
time ./fib_rs
1134903170

real    0m2.295s
user    0m2.291s
sys     0m0.002s
```

Diffed ASM:  https://www.diffchecker.com/ocF7TSsM

The times are relatively consistent in several runs of each test. These tests were done on a Macbook Pro i7 with OSX 10.11.6 (El Capitan).

**Comment by TimNN** [comment]
I can observe the same behaviour (also on OS X) with the stable compiler. Strangely, I get the exact opposite behaviour when timing the code on the latest nightly.

**Comment by durka** [comment]
I get the same results as @TimNN. With beta and stable, panic=abort seems to be faster now.

**Comment by Digipom** [comment]
I tried and the same as @TimNN; if I switch to nightly, then the panic=abort one is faster than the other one with very similar timings. Hmm...

**Comment by Digipom** [comment]
On Rust 1.14 the abort version is significantly faster now.

Stable unwind: 2.6s
Stable abort: 2.0s

**Comment by Digipom** [comment]
rust.godbolt.org doesn't show any difference with the ASM, but if I ask Rust to emit the ASM then I can see this diff:

https://www.diffchecker.com/WNWOw2PB

The only difference seems to be that the unwind version has some extra .cfi directives. That alone could account for this difference? Interesting.

**Comment by Digipom** [comment]
Hmm, it seems that fib is called 2,269,806,339 times so even if those cfi directives are relatively cheap, that certainly can account for an extra 600ms. :) 

I'll close this since -C panic=abort seems to be doing its job now.

**Comment by rkruppe** [comment]
Those directives don't generate any code. They result in debug/unwinding info, but that's stored in a separate section which is not even touched in normal execution (i.e., no panics, no debugging, no stack Trave). And with the program being so small, it can't even be due to Instruktion cache misses... Weird.
