### ISSUE TITLE
Linking errors on beta/i686/travis-ci

### ISSUE THREAD

**Issue by fiveop** [rust-lang/rust#37258]
We have a problem building nix-rust for i686 on travis since beta switched to 1.13.0-beta.1 (see https://github.com/nix-rust/nix/issues/435). Since I cannot reproduce this behavior on my local maschine, building the current HEAD of the beta branch myself is no viable strategy to test if the recent changes helped.

Can we get another beta build, so we can test whether and ensure that this problem does not make it to stable (assuming it is a Rust problem)?

**Comment by TimNN** [comment]
I already posted this in the nix repo, however I'll post it here as well:

This is probably #36793, which was fixed by #36866 on nightly.

**Comment by alexcrichton** [comment]
Indeed! This should be fixed with a new beta soon, so closing. Thanks for the report though!
