### ISSUE TITLE
Metabug for proper MSVC support

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#37268]
For historo-technical reasons the metabug tracking this is in the rust-lang/rfcs repo, curated by @retep998. I was a bit surprised to find it there, so I'm simply making an issue here that links to it so that it is hopefully easier for others to find in the future. 

Behold: https://github.com/rust-lang/rfcs/issues/1061

**Comment by steveklabnik** [comment]
Triage: this is a metabug, so no direct progress.

**Comment by rylev** [comment]
The issue being linked to has been closed. If there's still a need for a meta-tracking issue for MSVC support, a new one should be opened.
