### ISSUE TITLE
`where T: ?Sized` is not supported

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#37275]
Rust documentation apparently normalizes all generics to use the form `where ....`, which leads to constructs such as:
```rust
pub trait AsRef<T> where T: ?Sized
```
(from https://doc.rust-lang.org/std/convert/trait.AsRef.html)

except that's not valid Rust:
```
error: unexpected `?`
```

The valid form is:
```rust
pub trait AsRef<T: ?Sized>
```

Either the where form for `?Sized` should be supported, or the documentation generator shouldn't normalize them. Either way is fine (although for consistency, it would seem the former would be better than the latter), but the current status quo is just confusing: you sometimes don't pick up valid syntax from the documentation.

**Comment by bluss** [comment]
Existing issue for Sized in where clauses: #20503
