### ISSUE TITLE
Wrong COPYRIGHT document at rust-lang.org

### ISSUE THREAD

**Issue by matklad** [rust-lang/rust#37279]
The documents at https://www.rust-lang.org/COPYRIGHT and https://github.com/rust-lang/rust/blob/master/COPYRIGHT differ. This must be a bug.

**Comment by matklad** [comment]
The latter one seems more old, but every file preamble refers to it

>// Copyright 2012 The Rust Project Developers. See the COPYRIGHT
// file at the top-level directory of this distribution and at
// http://rust-lang.org/COPYRIGHT.

**Comment by steveklabnik** [comment]
I'm not sure that first one even should be there...

**Comment by matklad** [comment]
@steveklabnik should this be assigned to somebody? Should be easy to fix, and confusion about licenses is not a great thing :)

**Comment by steveklabnik** [comment]
related https://github.com/rust-lang/rust/issues/39897

**Comment by steveklabnik** [comment]
@brson: how is www.rust-lang.org/COPYRIGHT generated? It is not in rust-lang/rust-www, where I expected....

**Comment by Mark-Simulacrum** [comment]
cc @rust-lang/infra @alexcrichton -- Does anyone know how rust-lang.org/COPYRIGHT got there and where it can be updated from?

**Comment by alexcrichton** [comment]
I think whenever the website is updated it doesn't delete old artifacts, so this is probably a super historical upload that's never been deleted. Ibelieve that if a `COPYRIGHT` file is added to the rust-www repo it should overwrite the one on rust-lang.org

**Comment by kzys** [comment]
The URL is 404, but many files in the repos are referencing the URL...

```
% git grep 'http://rust-lang.org/COPYRIGHT' | wc -l
   11336
%
```

**Comment by matklad** [comment]
File preambles are gone, so nothing points to  https://www.rust-lang.org/COPYRIGHT anymore!

Who would have though that changing all of the files would be easier than fixing one website? :D
