### ISSUE TITLE
impl `Copy` for most primitive types explicitly

### ISSUE THREAD

**Issue by liigo** [rust-lang/rust#37295]
I can't think of any reason not to do this.

cc https://github.com/rust-lang/rust/pull/37103

**Comment by liigo** [comment]
cc https://www.reddit.com/r/rust/comments/58yukd/if_rust_ensures_that_there_is_exactly_one_binding/
Some people are not aware that `i32` implements `Copy`. Many answers on /r/rust said "`i32` implements `Copy`", but it doesn't, at least not explicitly does.

**Comment by sinkuu** [comment]
`Copy` is a language built-in trait, so I guess it is automatically implemented for primitive types in the compiler. I don't understand rustc internals at all, but [fn copy_conditions](https://github.com/rust-lang/rust/blob/f9cb7dfc0c92e2196ee04b1a138f37069e60d71d/src/librustc/traits/select.rs#L1802) is a suspect:)

**Comment by liigo** [comment]
At docs level, make it clear that they implement `Copy`

- in language reference, or
- in std/core API reference

and, of cause, in the Book.

**Comment by ollie27** [comment]
I guess this is a duplicate of #25893.

**Comment by liigo** [comment]
closing as duplicate
