### ISSUE TITLE
Improvement in error message

### ISSUE THREAD

**Issue by flavius** [rust-lang/rust#37319]
Given this code:

```
fn main() {
    let t:u32 = 0;
    let v = vec![42];
    println!("{}", v[t]);
}
```

I would argue that putting the first piece of information which when fixed, leads to a fix of the problem, and spelling out the ":", would make the error message more helpful.

Instead of ```trait `std::vec::Vec<{integer}>: std::ops::Index<u32>` not satisfied``` it could be ```The trait `std::ops::Index<u32>` is not implemented for `std::vec::Vec<({integer}, {integer})>` ```

rustc nightly `rustc 1.14.0-nightly (16eeeac78 2016-10-18)`

**Comment by GuillaumeGomez** [comment]
Working on it.
