### ISSUE TITLE
changing private fn causes retranslation of struct

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#37335]
For some reason, changing a private fn in the `point` crate winds up causing a module that does `point::Point { .. }` to be retranslated. Not sure why this is but it is the only shortcoming we encounter in that use case.

**Comment by KalitaAlexey** [comment]
What is the status of it?
Is it still relevant?

**Comment by nikomatsakis** [comment]
I'm pretty sure this has been fixed.
