### ISSUE TITLE
Confusing wording in docs for slice::as_ptr/as_mut_ptr

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust#37334]
> Modifying the slice may cause its buffer to be reallocated, which would also make any pointers to it invalid.

I believe this is trying to refer to manipulating the data structure (e.g. `Vec`) that owns the memory the slice is borrowing, but modifying the slice data through a slice can never cause reallocation.

**Comment by QuietMisdreavus** [comment]
I opened #40603 to tweak this wording.

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/40603 was merged so this should be closed! 🎊
