### ISSUE TITLE
`try!()` macro is generating the `unused_qualifications` lint

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#37345]
The macro should not cause warnings in the user's code. This seems to show up due to other changes.

Seen here: https://internals.rust-lang.org/t/regression-report-stable-2016-10-20-vs-nightly-2016-10-21/4255

The lint is allow by default, but some configurations will enable it.

**Comment by bluss** [comment]
I don't think adding an allow in `try!()` is the right fix. Using explicit qualifications is the right thing to do in every macro, and we don't want every user-defined macro to have to add the allow attribute.

@jseyfried Do you know anything about this?

**Comment by jseyfried** [comment]
I'm not aware of any recent changes that would cause new warnings / regressions, but I could disable the lint for macro-expanded paths easily.

**Comment by TimNN** [comment]
Introduced between `nightly-2016-10-19` and `nightly-2016-10-21` ([Changes](http://github.com/rust-lang/rust/compare/16eeeac78...f09420685)).

@jseyfried: This could probably be a side effect of #37213.

**Comment by jseyfried** [comment]
@TimNN Indeed, fixed in #37361.

**Comment by retep998** [comment]
Totally just got bitten by this in winapi, can't wait for the next nightly.
