### ISSUE TITLE
Into<Option<String/&str>> strange behaviour

### ISSUE THREAD

**Issue by TyanNN** [rust-lang/rust#37348]
When `Into<Option<String>>` is used more than once in function declaration it behaves strangely

I tried this code:

```
fn add_image<T: Into<Option<String>>>(name: &str, tags: &[String], first_string: T, second_string: T) {
...
}
fn main() {
    add_image("test.jpg", &vec!["1".to_string(), "2".to_string()], "x".to_string(), None);
}
```

I expected to see this happen: it worked ok

Instead, this happened: 

```
add_image("test.jpg", &vec!["1".to_string(), "2".to_string()], "x".to_string(), None);
                                                                                ^^^^ expected struct `std::string::String`, found enum `std::option::Option`
```

Also, if T1 and T2 are used(`T1: Into<Option<String>>, T2: Into<Option<String>>`) it works fine

## Meta

`rustc --version --verbose`:
```
rustc 1.14.0-nightly (f09420685 2016-10-20)
binary: rustc
commit-hash: f094206851e72e70528790cc9c70a745184ff7b0
commit-date: 2016-10-20
host: x86_64-unknown-linux-gnu
release: 1.14.0-nightly
LLVM version: 3.9
```

**Comment by bluss** [comment]
If you use a single type parameter `T`, then that means it requires the two input types to be the same, so it seems this is not a bug.

**Comment by sfackler** [comment]
Yep, this looks like it's working as intended.
