### ISSUE TITLE
"multiple applicable items" since raw pointers to unsized implement Debug

### ISSUE THREAD

**Issue by TimNN** [rust-lang/rust#37354]
Breaking change from #36880

```rust
use std::fmt::{Formatter, Debug, Pointer};

fn foo(f: &mut Formatter) {
    let a: *const [i32] = &[0] as *const _;
    let _ = a.fmt(f);
}

fn main() {}
```

Affects `mbox v0.1.3`.

**Comment by nagisa** [comment]
One of those things we consider not-actually-breaking changes as being more explicit in user code would have prevented the breakage.

Still need to re-evaluate if such a breakage is acceptable for what it brings to the table. Certainly not `T-compiler`, most likely `T-libs`.

**Comment by TimNN** [comment]
> Certainly not T-compiler, most likely T-libs.

Yes, of course, not sure what I was thinking there...

**Comment by eddyb** [comment]
We shouldn't have ever done that bloody "all fmt traits have a `fmt` method" thing, but my solutions weren't exactly that great either (e.g. unsafe conversion between `&T` and `&fmt::Debug<T>`).

Either case there's a reason they're not in the prelude: you should *never* import those traits.
Just `use std::fmt;` and use paths from that.

**Comment by alexcrichton** [comment]
The libs team discussed this during triage and the conclusion was that this falls under the "acceptable breakage" umbrella and we'll send a patch upstream for this, so closing.
