### ISSUE TITLE
Binary search is doing bounds check

### ISSUE THREAD

**Issue by arthurprs** [rust-lang/rust#37379]
We did some work on that in https://github.com/rust-lang/rust/pull/30917 and we hoped llvm would eventually optimize the bounds checking away. Unfortunately it (still?) doesn't https://github.com/rust-lang/rust/pull/30917#issuecomment-255820425.

**Comment by ranma42** [comment]
cc me

**Comment by arthurprs** [comment]
Found the issue with the optimization, will follow up with a patch to llvm and rust fork.

**Comment by arthurprs** [comment]
Closed in https://github.com/llvm-project/llvm/commit/cf6e9a81f676b3e3885f86af704e834ef5c04264

**Comment by bluss** [comment]
Nice job!
