### ISSUE TITLE
Rust incorrectly coerces byte string literals

### ISSUE THREAD

**Issue by eugene2k** [rust-lang/rust#37377]
This code:
```
extern "C" {
    fn puts(string: *const std::os::raw::c_char) -> std::os::raw::c_int;
}
fn main() {
    [1,2,3] as *const u8;
    b"Hello" as *const u8;
    unsafe {
        puts([1,2,3] as *const i8);
        puts(b"Hello\0" as *const i8);
    }
}
```
produces these errors:
```
error: non-scalar cast: `[i32; 3]` as `*const u8`
 --> src/main.rs:7:5
  |
7 |     [1,2,3] as *const u8;
  |     ^^^^^^^^^^^^^^^^^^^^

error: non-scalar cast: `[i32; 3]` as `*const i8`
  --> src/main.rs:10:14
   |
10 |         puts([1,2,3] as *const i8);
   |              ^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
  --> src/main.rs:11:14
   |
11 |         puts(b"Hello\0" as *const i8);
   |              ^^^^^^^^^^^^^^^^^^^^^^ expected u8, found i8

error: aborting due to 3 previous errors
```

I'm not sure if it's supposed to be possible to cast byte string literals as *const ptrs, but when in the second call to `puts()` you try to cast b"Helo\0" as u8 instead of i8, the error changes to "exected i8, found u8".

Tested on stable(1.12) and nightly(2016-10-21)

**Comment by TimNN** [comment]
Regarding the second case, that behaves as expected, it's just a bit tricky to see:

* `b"Hello\0"` has type `&[u8]`
* `*const std::os::raw::c_char` is an alias for `*const i8`
* So when you try to cast `as *const i8`, the type of `b"Hello\0"` does not match
* And when you try to cast `as *const u8`, the type of the `puts` signature does not match

You can solve this using two casts `b"Hello\0" as *const u8 as *const i8` (or let the compiler work it's magic and use `puts(b"Hello\0" as *const _ as *const _)`.

**Comment by eugene2k** [comment]
Huh. Didn't realize that. I guess it's a false alarm then... thx!
