### ISSUE TITLE
unused import warning should have identifier in first line

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#37376]
Currently, the `unused_imports` lint does not include the identifier that is unused in the first line of its warning output.

Instead, it relies on the span system to highlight the identifier 

For example, for the following code:

```rust
mod a {
    pub fn foo() { }
    pub fn bar() { }
}

mod b {
    use a::{foo, bar};
}

fn main() {
    a::foo(); a::bar();
}
```

the produced warning is:

```
warning: unused import, #[warn(unused_imports)] on by default
 --> <anon>:7:13
  |
7 |     use a::{foo, bar};
  |             ^^^

warning: unused import, #[warn(unused_imports)] on by default
 --> <anon>:7:18
  |
7 |     use a::{foo, bar};
  |                  ^^^
```

This means that the user who is reviewing the warnings needs to scan down four lines after the warning itself before they can see which identifier is being highlighted. In some contexts, the output may have even flowed off the visible portion of the console output.

Some other similar lints do not suffer from this problem because they include the offending identifier in the first line of the warning. For example, the `unused_variables` and `dead_code` lints both include the name of the function or variable in the first line of the warning.

**Comment by dwillie** [comment]
I wouldn't mind having a look at this, but it's my first time working on this project – I see this issue is labeled easy, would it be a good first task?

**Comment by cramertj** [comment]
@dwillie Sorry, I just saw that you commented after I started work on #37394. It's not done, though-- you're welcome to fork my branch and finish it off, and I can close my current PR.

**Comment by dwillie** [comment]
@cramertj No, no, that's fine :) I hadn't started yet anyway
