### ISSUE TITLE
[Windows] Command:spawn() only searches for `.exe` files

### ISSUE THREAD

**Issue by afiune** [rust-lang/rust#37380]
## Problem Description

In the Windows world you have `.exe` files but you can also have `.bat` files that can be executables in your `PATH`. The problem is that the implementation of the `Command:spawn()` in windows only checks for **EXE** (https://github.com/rust-lang/rust/blob/master/src/libstd/sys/windows/process.rs#L141) that means that if we have some **BAT** files that we would like to execute we currently can't.
## Proposal Solution

Instead of checking just for **EXE** files we should check the `PATHEXT` Environment Variable to detect what available extensions we search for.

**Comment by Mark-Simulacrum** [comment]
From the pull request: "It sounds like this behavior is specific to cmd.exe not CreateProcess. We're emulating the latter, so it sounds like we may not wish to merge this." As such, I'm going to close.

**Comment by cengizIO** [comment]
Hello @Mark-Simulacrum 

Sorry for bumping this, I've a problem with `.com` files and this would fix that issue. Where shall I take that conversation?

**Comment by Mark-Simulacrum** [comment]
Let's open a new issue, and please link here and to the PR. Are `.com` files found and executed by `CreateProcess` on Windows? If not, then I suspect the resolution will be similar, but if yes, then it seems like changing it is a good idea.
