### ISSUE TITLE
Stop putting the ident interner in local storage

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#3738]
Global state isn't so desirable. The compiler stores an ident interner in local storage. It would be better to not do that.

**Comment by steveklabnik** [comment]
Is this issue still relevant today?

**Comment by steveklabnik** [comment]
Triage: it's been a year and a half since I asked about relevance; I'm going to close. A four-digit bug! whew.

Please let me know if this is wrong.

**Comment by jonas-schievink** [comment]
Still relevant: https://github.com/rust-lang/rust/blob/master/src/libsyntax/symbol.rs#L231

**Comment by Mark-Simulacrum** [comment]
Nominating for compiler team. I'm hoping that we can assign someone to investigate and then close this. Looking at the code myself, I'm inclined to say that fixing this isn't worth it.

**Comment by nikomatsakis** [comment]
I agree. Let's close this. Maybe we will do the refactoring and maybe we won't, but it's not worth keeping this issue open right now.
