### ISSUE TITLE
Spurious failure in HeapFree on Windows

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#37395]
https://buildbot.rust-lang.org/builders/auto-win-gnu-32-opt-rustbuild/builds/2829/steps/test/logs/stdio
https://gist.github.com/alexcrichton/9f36ff87645b87d02a0ee6d302d5798e

```
doc tests for: C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\src/doc\nomicon\repr-rust.md

running 7 tests
test _4 ... ignored
test _6 ... FAILED
test _0 ... ok
test _3 ... ok
test _1 ... ok
test _5 ... ok
test _2 ... ok

failures:

---- _6 stdout ----
    thread '_6' panicked at 'assertion failed: err != 0', C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\src\liballoc_system\lib.rs:233
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '_6' panicked at 'couldn't compile the test', C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\src\librustdoc\test.rs:283


failures:
    _6

test result: FAILED. 5 passed; 1 failed; 1 ignored; 0 measured
```

where the relevant line is here: https://github.com/rust-lang/rust/blob/7a208648daa5ed2697527e0c6b79c0697f3950d8/src/liballoc_system/lib.rs#L233

This is... terrifying!

**Comment by retep998** [comment]
I really wish this bug wasn't so spurious, so we could reliably figure out what was causing it. At the very least we need to change that `debug_assert!` to print out the error itself when that occurs, although I'd prefer changing it to `assert!` if the cost of doing so is acceptable.

**Comment by alexcrichton** [comment]
We haven't seen this in nearly a year, so this isn't doing much help staying open, so I'm going to close.
