### ISSUE TITLE
Borrow checker works wrongly with returned values.

### ISSUE THREAD

**Issue by loyd** [rust-lang/rust#37407]
Unfortunately I haven't found an open bug on this subject.

I tried this code:

``` rust
struct A(Vec<u32>);

impl A {
    fn drain(self) -> Vec<u32> {
        let mut nums = self.0;
        nums.drain(..).collect()          // error: `nums` does not live long enough

        // but it works fine:
        // return nums.drain(..).collect();
    }
}
```

[Try it](https://is.gd/RTw5Vs)

**Comment by jonas-schievink** [comment]
I think this is #21114

**Comment by TimNN** [comment]
Essentially the same issue as #31723, I think.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of #21114. Please reopen if that's incorrect, but from what I can tell this is a duplicate of that issue.
