### ISSUE TITLE
alloc::heap doc comments strange re old_size in [requested_size, usable_size]

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#37417]
The `reallocate`, `reallocate_inplace`, and `deallocate` all have doc comments that end with the sentence: 

> The `old_size` parameter may be any value in range_inclusive(requested_size, usable_size).

When reading the doc for `reallocate` and `reallocate_inplace`, I found this note confusing, because I interpreted the identifier `requested_size` as if it were referring to new size being requested by _this call_ to `reallocate* or`reallocate_inplace`.
- The reason that this interpretation leads to confusion is that it means we are requiring `old_size` to be in the range `[size, usable_size]`, and then in practice that means one cannot feed in a value for `old_size` where `size > old_size`; but the case where `size > old_size` is _precisely_ the use case for calling `reallocate` or `reallocate_inplace` in the first place. 

After subsequently searching the file for other occurrences of "requested_size" (and later, "requested size"), I discovered the same text in the `fn deallocate` doc comment. In that context, it cannot possibly mean a size requested for the current call.

That is when I realized that the notion of "requested_size" must be referring to a value from the _history_ of the memory allocations.

In particular, it probably means either:
1.  "what was the size that was used for the _original_ allocation request that returned this block's address?" ("original" meaning "first with no intervening transfer of the block back to the allocation pool via `realloc` or `dealloc`), or
2. "what was the _minimum_ size that was used, over the original allocation request and all successful reallocation requests that have maintained this block's address?"

The phrase "requested size" to me strongly implies the first of the two interpretations above, but I suspect the second interpretation is a strictly more useful one to adopt, (though it may be a bit niddly to get right...)

**Comment by steveklabnik** [comment]
This is for an unstable feature which has changed a lot since this was filed, so closing as stale. As part of stabilizing we need to review all the docs anyway.
