### ISSUE TITLE
Add trait can panic

### ISSUE THREAD

**Issue by jbcden** [rust-lang/rust#37421]
We don't mention in the docs that adding two numbers can overflow and cause a panic. Similarly, indexing out of bounds will also cause a panic.

**Comment by durka** [comment]
Anyone implementing any trait can panic. I'd think it would be more interesting for traits to document when implementors _must not_ panic.

**Comment by Cobrand** [comment]
For the panic of Add, it is not linked to the Add trait itself, but to the impl of Add by various primitive types such as i32, u32, ... `Add` itself should not mention that it panics when it overflows, cause it does not. For instance, if you add 2 `f32`s and the result is too big to be stored by the IEE 754 norm, the result will be `inf`, it will not panic.

Similarly, if you want `i32`, `u32` to not panic when an overflow occurs, you can use [`Wrapping`](https://doc.rust-lang.org/std/num/struct.Wrapping.html).

For the panic with Index, again, it depends on the implementation. Some impls might panic, while other don't. If you are talking about `Vec`s or slices in general, it is actually mentioned [here](https://doc.rust-lang.org/std/vec/struct.Vec.html#indexing)

**Comment by frewsxcv** [comment]
Right, so the actionable task is here is to document when `trait` `impl`s can panic, not `trait`s themselves.

**Comment by Mark-Simulacrum** [comment]
I'm not sure what we really want out of this. We could add more documentation about which traits are okay to panic! in. I'm going to nominate for a doc team discussion, perhaps we could arrive to a concrete list of things we want to do to close this out.

**Comment by steveklabnik** [comment]
doc team meeting triage: tagging as p-medium, we'll sort out exactly what we want to do here when we tackle the issue.

**Comment by steveklabnik** [comment]
Triage: this issue has had no comments for over a year. I personally find this quote compelling:

> Anyone implementing any trait can panic. I'd think it would be more interesting for traits to document when implementors must not panic.

And, since the current state hasn't led to massive confusion, I'm going to consider this stale and give it a close. Thank you!
