### ISSUE TITLE
rustc(79945,0x7fff9caeb3c0) malloc: *** malloc_zone_unregister() failed for 0x7fff9cae1000 OS X 10.12.1

### ISSUE THREAD

**Issue by aig787** [rust-lang/rust#37467]
Looks like #34674 may have resurfaced. 

```
$ rustc --version --verbose
rustc(79945,0x7fff9caeb3c0) malloc: *** malloc_zone_unregister() failed for 0x7fff9cae1000
```

Cargo build also pegs at 100% and hangs. Issue surfaces on both rust and rust-nightly from homebrew.

![screen shot 2016-10-29 at 12 12 03 pm](https://cloud.githubusercontent.com/assets/4955443/19832148/fbad8566-9dd0-11e6-9174-37c6e6a196d1.png)

**Comment by alexcrichton** [comment]
Thanks for the report! Although `rustc --version` isn't working, do you know what version of Rust you were trying to install and/or run?

**Comment by aig787** [comment]
Should be on both 1.0.0-beta.4 and whatever the nightly version was at the time I opened the issue. Is there w better way to check?

**Comment by aig787** [comment]
Closing this as it is a problem with the homebrew recipes. Neither of the recipes I was using was installing something more recent than 1.0.x.
