### ISSUE TITLE
Running tests timeout too fast

### ISSUE THREAD

**Issue by WaDelma** [rust-lang/rust#37461]
Starting from 1.12 tests started to timeout after a minute has been passed #2873.

This made 6 tests that were succeeding from in my library to timeout and be useless (https://travis-ci.org/WaDelma/poisson/jobs/171430077). (I already had problems with travis timing out which I fixed). It also says that the build was successful even though there were timeouted tests!

I agree with that there should be some kind of timeout, but it's currently too low for me.

So I propose that instead of hardcoding the timeout make it configurable.

**Comment by sfackler** [comment]
There is no timeout running tests. That message is printed after a test has been running for a minute, but it keeps going from there:

```rust
use std::thread;
use std::time::Duration;

#[test]
fn ok() {
    thread::sleep(Duration::from_secs(70));
}

#[test]
fn panic() {
    thread::sleep(Duration::from_secs(70));
    panic!();
}
```

```
     Running target/debug/deps/foo-aea0446ef0e9f61b

running 2 tests
test panic has been running for over 60 seconds
test ok has been running for over 60 seconds
test ok ... ok
test panic ... FAILED

failures:

---- panic stdout ----
        thread 'panic' panicked at 'explicit panic', src/lib.rs:12
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    panic

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured

error: test failed
```

**Comment by WaDelma** [comment]
Ah I read that wrong then... Nevermind.
