### ISSUE TITLE
Tracking issue for Windows subsystem support

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#37499]
Tracking issue for https://github.com/rust-lang/rfcs/pull/1665

**Comment by fischmax** [comment]
Not sure if this is the right place to comment, but since the RFC is already closed, I don't know where else to put it: a future inclusion of the native subsystem would enable us to write Windows kernel mode drivers. And ring 0 is really, where all that safety comes in handy ;-)

**Comment by chriskrycho** [comment]
Has this been stabilized? It doesn't appear in the release notes for 1.13.0 or 1.14.0 (the releases since the last commits and actions on this).

**Comment by alexcrichton** [comment]
@chriskrycho this has not yet been stabilized, no

**Comment by chriskrycho** [comment]
@alexcrichton thanks for the clarification! I've written it up as to-be-documented over on #38643 accordingly. (And presumably we'd catch it anyway, but I wanted to be exhaustive.)

**Comment by alexcrichton** [comment]
This seems like it's baked long enough and we haven't seen many changes, so I'd like to propose we stabilize it! To that end...

@rfcbot fcp merge

**Comment by brson** [comment]
We should consider backporting to 1.17.
