### ISSUE TITLE
Inconsistency with “at least one non-builtin trait is required for an object type”

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#37515]
Auto traits are alone allowed as object types in some cases and not others.

The following two lines are fine: (Using Send as an object type)

```rust
type Y = Send;

fn main() {
    let x = &1 as &Send;
}
```

The following line has an error:

```rust
type Z = for<'x> Send;  //~ error[E0224]: at least one non-builtin trait is required for an object type
```

The second error seems to speak against the first two examples.

Tested using `rustc 1.14.0-nightly (3f4408347 2016-10-27)`

**Comment by Mark-Simulacrum** [comment]
The latter compiles fine today; I *guess* this should get a test.

```
warning: type alias is never used: `Z`
 --> test.rs:1:1
  |
1 | type Z = for<'x> Send;
  | ^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(dead_code)] on by default

```
