### ISSUE TITLE
#[derive] suggestion should check for local struct

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#37522]
Consider this code:

```rust
struct Foo;

fn main() {
    println!("{:?} {:?}",
      /* 1 */ Foo,
      /* 2 */ std::fs::OpenOptions::new());
}
```

Both marked lines print the error that `Debug` is not satisfied and note that "if it is defined in your crate, add `#[derive(Debug)]` or manually implement it". The compiler should be able to check and issue the note only for (1), instead of printing the confusing "if it is defined in your crate".

**Comment by Mark-Simulacrum** [comment]
This message is currently printed using `#[rustc_on_unimplemented = "..."]`, so I feel like fixing this will be non-trivial. I'd be willing to try and so, though, if someone could provide some pointers.

**Comment by durka** [comment]
So either we need to move it into the compiler, or add another hack like `#[rustc_on_unimplemented_for_local]`/`#[rustc_on_unimplemented_for_remote]`.

**Comment by zackmdavis** [comment]
(Issue to improve `rustc_on_unimplemented` is #44755.)
