### ISSUE TITLE
Implement Debug for internal libraries

### ISSUE THREAD

**Issue by bytebuddha** [rust-lang/rust#37536]
I have noticed that the internal library's specifically librustc_driver and libsyntax, do not implement the Debug trait. I asked on [reddit](https://www.reddit.com/r/rust/comments/5866nf/rust_internal_debug_implementations/) and it seems they should, but just slipped through the cracks.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this -- we'd be happy to take PRs, but individually I don't think this is very actionable.
