### ISSUE TITLE
Add support to colorize the output of notes and errors

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#37532]
Sometimes coloring messages could be useful to highlight either inlined code or an important part of the output text without changing the text itself.

**Comment by bluss** [comment]
rustc's errors are colored. Can you add more information about your configuration, where color is missing?

**Comment by nagisa** [comment]
> rustc --color=always

**Comment by estebank** [comment]
This ticket had a very bad summary, sorry about that. What I'm proposing is adding support to (all?) the note and help methods in `Diagnostic`, like for example [`note_expected_found`](https://github.com/rust-lang/rust/blob/5fe733a15945b7599fdf820ceec1597259dd8490/src/librustc_errors/diagnostic.rs#L90-L102) to allow parts of `NOTE` and `HELP` lines to be colorized.

The idea to have this came to me while thinking about #21025, as something like this could be accomplished:

<pre>
foo.rs:9:7: 9:8 error: mismatched types:
 expected `Foo&lt;u8, <b>i8</b>&gt;`,
    found `Foo&lt;u8, <b>i64</b>&gt;`
(expected i8,
    found i64)
</pre>

**Comment by estebank** [comment]
Related #21334.
