### ISSUE TITLE
Tracking issue for Self and associated types in struct expressions and patterns

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#37544]
I'm going to add a feature gate according to https://github.com/rust-lang/rust/pull/37035#issuecomment-258003420, this is a corresponding tracking issue.

**Comment by crumblingstatue** [comment]
This doesn't feel complete to me without also allowing `Self` for tuple and unit-like struct, and enum expressions. It just feels wrong being able to do ` fn new() -> Self { Self { ... } }`, but not `fn new() -> Self { Self(...) }`, `fn new() -> Self { Self }`, and `fn new() -> Self { Self::Variant }`

**Comment by petrochenkov** [comment]
`Self::Variant` (and `Alias::Variant`) is in the queue (https://github.com/rust-lang/rust/issues/26264), it's just not implemented yet.

`Self(..)` for `struct S();` or `Self` for `struct S;` would be some kind of new language entity, *value alias* (different from just a constant) referring to the original value - struct constructor. It's certainly can be hacked into the compiler, but I'd like to have some more foundation under it and see wider picture - how else these value aliases can be used, how they are related to possible pattern aliases, etc.

**Comment by petrochenkov** [comment]
@crumblingstatue 
>Is there a fundamental reason why a type itself cannot be used for these purposes?

It's possible, just messy.
Suppose, for example, that we have an expression
```
A::B(0, 1)
```
It may a function call, or it may be a tuple struct construction.
We need to resolve `A::B` to understand what is it.
Rust have two primary namespaces - one is for types, and the other is for values. This is pretty fundamental thing that can't be changed backward compatibly.
Functions are defined in value namespace and types like structs are defined in type namespace.

If the "type itself" is used for looking up tuple struct constructors, then we need:
- Search `A::B` in both namespaces, this kind of contradicts to the point of namespaces.
- Set up namespace priorities. What if both function `A::B` and struct `A::B` exist? Should we prefer one of them or report an error?
- Ok, suppose we prefer a function. Now we need to resolve `A::B` in value namespace and if this resolution fails, then we need to resolve it again in type namespace.
Name resolution happens in two phases:
    - Primary resolution pass, based only on names, used for everything except for associated items.
    - Resolution in type checking, used for associated items (method resolution, etc.), this jumps through various type checking hoops (trait selection, inherent impls, parameter substitution, autoderef for methods) to find the correct resolution.

    If `A::B` is not resolved in value namespace during the first pass, then we can't simply search type namespace, because `A::B` may be, for example, a method. We need to record partial resolutions in both namespaces and proceed to type checking when full resolution is completed and we select a function if it's found and a type otherwise.

Instead of doing all this, tuple/unit structs define additional function/constant-like items in value namespace which then used during resolution of `A::B(0, 1)`, but can also be used in other ways like normal functions/constants. So, namespaces stay clearly separated and there's no need to disambiguate between types and values and keep both resolutions until type checking. But it's still possible to implement this fall back to types backward compatibly, even now.

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

I propose that we stabilize this tracking issue. This is the feature which allows you to use `Self` and associated types in struct expressions. Note that it is slightly different to write `impl Foo<T> { fn new() -> Self { Self { ... } }` as to write `impl Foo<T> { fn new() -> Self { Foo { ... } }`. In particular, in the latter case, the `Foo { ... }` does not specify what the type parameter is -- it must be inferred (in this case, from the declared return type). That is not true for `Self { ... }`.  I cannot imagine another semantics for this notation.

My main concern is that perhaps it is confusing to allow types (and not just structs) at all! I am open to the possibility of letting this bake a little longer and not moving to FCP.

**Comment by eddyb** [comment]
I like this feature and even look forward to having it integrated with variant types!

**Comment by nrc** [comment]
> My main concern is that perhaps it is confusing to allow types (and not just structs) at all!

This is my concern too, however, my understanding is that this ship sailed some time ago and we allow all sorts of things in the ident position of a struct literal.

**Comment by nikomatsakis** [comment]
@nrc 

> This is my concern too, however, my understanding is that this ship sailed some time ago and we allow all sorts of things in the ident position of a struct literal.

Off hand I'm not sure what you mean... have an example? Do we allow e.g. type aliases?

**Comment by nrc** [comment]
@nikomatsakis We do allow type aliases and this is what I had in mind. FWIW, we also allow, e.g., `Foo::<u32> { ... }`. However, associated types in that position do not work.

**Comment by nikomatsakis** [comment]
So in particular this does work:

```rust
struct Foo<T> { x: T }

type Bar = Foo<u32>;

fn main() {
    let x = Bar { x: 22 };
}
```

**Comment by withoutboats** [comment]
@rfcbot reviewed

**Comment by petrochenkov** [comment]
ping @nikomatsakis 
I hoped to get this into the upcoming beta :(

**Comment by aturon** [comment]
@petrochenkov We can backport the stabilization. Looks like this was blocked on @pnkfelix who's been on vacation. I'll try to get a hold of him now.

**Comment by pnkfelix** [comment]
@rfcbot reviewed

**Comment by nikomatsakis** [comment]
@petrochenkov you want to prepare stabilization PR?

**Comment by nikomatsakis** [comment]
@petrochenkov you want to prepare stabilization PR?
