### ISSUE TITLE
Into implementations should be changed to From

### ISSUE THREAD

**Issue by clarcharr** [rust-lang/rust#37561]
Currently, libstd has:

```
impl Into<Vec<u8>> for String
impl Into<OsString> for PathBuf
```

And this seems inconsistent with the other collection implementations which all use `From` instead. It makes sense that these would be changed to `From` to allow use of `from`, and it doesn't seem like it'd be a breaking change at all.

**Comment by steveklabnik** [comment]
>  it doesn't seem like it'd be a breaking change at all.

Given that all `From` impls yield an `Into` impl, probably not, but I wonder what @rust-lang/libs has to say about why this was chosen.

**Comment by alexcrichton** [comment]
Seems reasonable to me! I believe `Into` doesn't imply `From` (but the other way around does). We should switch these for consistency.

**Comment by retep998** [comment]
`From` for the `Vec<u8>` options is suspicious because that operation can fail. `From` for `OsString` to `PathBuf` seems fine though.

**Comment by caipre** [comment]
@clarcharr : Did you mean to include a distinct third case? The first and third are both `Into<Vec<u8>> for String`.

**Comment by cuviper** [comment]
@retep998 I think you're reading those backwards.  `String` can become `Vec<u8>` without fail (but not vice versa), so `impl Into<Vec<u8>> for String` would be changed to `impl From<String> for Vec<u8>`.

**Comment by clarcharr** [comment]
@caipre I actually completely missed that. I just copied this from the [docs](https://doc.rust-lang.org/std/convert/trait.Into.html), which seem to have duplicated the impl on the list? Not sure if that's a bug.

**Comment by retep998** [comment]
@cuviper Oh right, `From<T> for U` is still omni directional, it just allows you to do `U::from()` in addition to `T::into()`. In that case all those impls are fine by me.
