### ISSUE TITLE
Segfault if unaligned SSE load not assigned to local variable

### ISSUE THREAD

**Issue by hsivonen** [rust-lang/rust#37560]
When using the LLVM idiom that derefercing a pointer to a packed struct that contains one SIMD member generates an unaligned load instruction, if the result of the dereference isn't assigned to a variable before extracting the single member, a segfault occurs on x86_64 Linux Nightly.

I tried this code:

````rust
#![feature(simd)]

extern crate simd;

use simd::u8x16;

#[repr(packed)]
#[derive(Debug, Copy, Clone)]
struct Unalign<T>(T);

#[inline(always)]
pub unsafe fn load16_unaligned(ptr: *const u8) -> u8x16 {
//    let loaded = *(ptr as *const Unalign<u8x16>);
//    loaded.0
    (*(ptr as *const Unalign<u8x16>)).0
}

fn main() {
        let ascii: [u8; 16] = [0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x70, 0x71,
                               0x72, 0x73, 0x74, 0x75, 0x76];
        let simd = unsafe{ load16_unaligned(ascii.as_ptr())};
        println!("{:?}", simd);
}
````

I expected a printout
````
u8x16(97, 98, 99, 100, 101, 102, 103, 104, 105, 112, 113, 114, 115, 116, 117, 118)
````

Instead, a segfault occurred.

If I uncomment the commented lines and comment out the line
````rust
(*(ptr as *const Unalign<u8x16>)).0
````
the program works.

A [git repo](https://github.com/hsivonen/unaligned_fault) with two commits corresponding to these two states is available for experimentation.

## Meta

`rustc --version --verbose`:

````
rustc 1.14.0-nightly (7c69b0d5a 2016-11-01)
binary: rustc
commit-hash: 7c69b0d5ae8c404c4847fa214126ebd7c0246277
commit-date: 2016-11-01
host: x86_64-unknown-linux-gnu
release: 1.14.0-nightly
LLVM version: 3.9
````

**Comment by retep998** [comment]
I believe this is a dupe of https://github.com/rust-lang/rust/issues/27060

Rust does not currently tell LLVM to do unaligned loads from fields of structs which have been packed.

**Comment by hsivonen** [comment]
Thanks. Indeed looks like a duplicate of that one.
