### ISSUE TITLE
Split Vim extensions into separate repository

### ISSUE THREAD

**Issue by ahmadsalim** [rust-lang/rust#3756]
Currently the Vim extensions are in a subdirectory in the main repository, specifically here: src/etc/vim. 
This makes it less user-friendly with Vim extension handling tools like VAM, Vundle and Pathogen that rely on separate git repositories for handling each separate extension.

While it is possible in Vundle to configure a "run-time path" such that a subrepository is chosen, this might be less optimal.
This is because the whole rust repository (which is fairly large) must be checked each time when installing/updating vim extensions, instead of only the smaller vim-related parts.

On my computer this takes at least one minute, which is a reasonably long time considering the parts needed.

**Comment by huonw** [comment]
The extension is now in a separate repo, thanks to @steveklabnik: https://github.com/rust-lang/rust.vim
