### ISSUE TITLE
Rustdoc: List traits that a trait implements

### ISSUE THREAD

**Issue by icefoxen** [rust-lang/rust#37593]
Basically, a struct will list all the methods and traits that it implements, but a trait will not.  So while looking at the docs for a specific struct gets you complete info on what you can do with it, looking at the docs for a trait doesn't tell you anything about what other traits it brings along with it.

For example, `IntoIter` is implemented for `Iterator`, but there's no mention of this in the docs for the `Iterator` trait.  So if you implement `Iterator` on a type you get `IntoIter` for free along with it but there's no way to discover this unless you dig doooooown through the docs for `IntoIter`.

Sorry if this is a duplicate.

**Comment by Stebalien** [comment]
Technically, traits don't actually implement anything (trait *objects* can but that's a different story). Instead, you have blanket impls bounded by a set of traits. That is:

```rust
 // Note: Implementations on generic type parameters are called "blanket impls"
impl<T> MyTrait for T where T: Trait1 + Trait2 ... { /* ... */ }
```

So, in this case, I believe you'd want the `Trait1` and `Trait2` documentation to list the `MyTrait` implementation.

**Comment by bluss** [comment]
The unsized type `Trait` is the object type of the trait with the same name.

**Comment by Mark-Simulacrum** [comment]
Nominating for T-dev-tools discussion (cc @nrc) since I think that this is something that would be amazing, but also likely quite difficult.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/33772, thanks to @QuietMisdreavus who found it. No need to nominate that since it seems we've had sufficient discussion on this that we do want it very much.
