### ISSUE TITLE
Compilation failure: "fatal runtime error: out of memory"

### ISSUE THREAD

**Issue by bpowers** [rust-lang/rust#37606]
I have a recursive function that takes a closure, and calls it in order to return a value.  I expect it to work (or at least give me an error message), but instead `rustc` runs out of memory (on my linux system w/ 8 GB of RAM).

The code is here:
https://play.rust-lang.org/?gist=4534e70a5ca797295ca3e20374f4f08d&version=stable&backtrace=0
And also available here:
https://github.com/bpowers/rust-compilation-failure
It fails both when running `cargo test`, `cargo build`, and `rustc src/lib.rs --crate-type lib`.

`perf record` suggests the majority of time is spent in `rustc::ty::walk::push_subtypes` -- I imagine I'm hitting some bug where we recurse and add more items onto the subtype list than we consume, but IDK.

The code is quite likely buggy (I'm quite likely specifying the closure constraint wrong -- this is my first serious rust project), but ideally the compiler would give me an error I could stare at rather than crashing.

## Meta

Tested under both stable + nightly:
- rustc 1.12.1 (d4f39402a 2016-10-19)
- rustc 1.14.0-nightly (5665bdf3e 2016-11-02)

**Comment by michaelwoerister** [comment]
cc @rust-lang/compiler

**Comment by Mark-Simulacrum** [comment]
Looks like this doesn't burn us today: error: reached the type-length limit while instantiating `expr::<[closure@<anon>:150:28: 168:14 r:&&std::boxed::Box<typed:...`
