### ISSUE TITLE
Show `Foo` instead of `<FooConstForMethod as Foo>` in E0323

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#37618]
Given a file

```rust
trait Foo {
    fn bar(&self);
}

pub struct FooConstForMethod;

impl Foo for FooConstForMethod {
    const bar: u64 = 1;
}
```

produces output

```nocode
error[E0323]: item `bar` is an associated const, which doesn't match its trait `<FooConstForMethod as Foo>`
  --> $DIR/impl-wrong-item-for-trait.rs
   |
XX |     const bar: u64 = 1;
   |     ^^^^^^^^^^^^^^^^^^^ does not match trait
```

as per [this review](https://github.com/rust-lang/rust/pull/37370/files#r85758145) from @nikomatsakis, it would make sense to change it so that the output is (at least in this case):

```nocode
error[E0323]: item `bar` is an associated const, which doesn't match its trait `Foo`
```

**Comment by eddyb** [comment]
This seems to me like the difference between `{:?}` and `{}` on a `ty::TraitRef`. That is, all you'd need to do is remove `:?` from the format string.
