### ISSUE TITLE
Process should support child outliving the parent

### ISSUE THREAD

**Issue by mikedilger** [rust-lang/rust#37620]
https://github.com/rust-lang/rust/issues/14467 solved this in 2014, but subsequent move to std::process lost that functionality.  Is this recoverable?

Under Unix I can use CommandExt::exec(), but I'm aiming for code that will work under Windows as well.

**Comment by retep998** [comment]
According to the [documentation](https://doc.rust-lang.org/nightly/std/process/struct.Child.html#note)

>Take note that there is no implementation of Drop for child processes, so if you do not ensure the Child has exited then it will continue to run, even after the Child handle to the child process has gone out of scope.
>Calling wait (or other functions that wrap around it) will make the parent process wait until the child has actually exited before continuing.

Is this not sufficient for your purposes?

**Comment by mikedilger** [comment]
Oops, that is the bit of documentation I seem to have glossed over.
