### ISSUE TITLE
binop trait bound failures due to references should produce nicer message

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#37626]
Let's start off with an example:

```rust
#[derive(PartialEq)]
struct Foo;

fn main() {
    let x = &Foo;
    assert!(x == Foo);
}
```

yields

```
error[E0277]: the trait bound `&Foo: std::cmp::PartialEq<Foo>` is not satisfied
 --> <anon>:6:13
  |
6 |     assert!(x == Foo);
  |             ^^^^^^^^
  |
  = help: the following implementations were found:
  = help:   <Foo as std::cmp::PartialEq>

```

Which is either fixed by adding an ampersand before the second argument or a deref before the first

The error message should suggest to insert one or multiple derefs before the argument that has more references than the other. This is a regular issue I get from Rust newcomers.

**Comment by Mark-Simulacrum** [comment]
We don't currently have any suggestion to dereference `x`... error message is below.

```
error[E0277]: the trait bound `&Foo: std::cmp::PartialEq<Foo>` is not satisfied
 --> test.rs:6:13
  |
6 |     assert!(x == Foo);
  |             ^^^^^^^^ the trait `std::cmp::PartialEq<Foo>` is not implemented for `&Foo`
  |
  = note: can't compare `&Foo` with `Foo`

error: aborting due to previous error
```

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/39942 which is more specific.
