### ISSUE TITLE
Function args show up twice in VS debugger's Locals view

### ISSUE THREAD

**Issue by vvuk** [rust-lang/rust#37634]
Any function args show up twice in the VS debugger's Locals view.  Local variables show up only once.

**Comment by Mark-Simulacrum** [comment]
Could someone with access to Visual Studio and an MSVC environment take a look at this today?

**Comment by vvuk** [comment]
Sure! I'll take a look in the morning. Has something gone in that might
have improved this?

**Comment by Mark-Simulacrum** [comment]
Not that I know of, but it never hurts to check. I wasn't actually quite aware I had strayed into November of 2016 already with issue triage, which is actually a good thing in some ways -- it means we've updated most of our ~2800 issues in the last 7 months.

**Comment by wesleywiser** [comment]
I just tested a basic scenario in both VS 2019 and Windbg. I was able to see function arguments in the Locals view correctly (each argument only showed once with the correct name, type and value).

<details><summary>Test code</summary>

```
fn add_two_numbers(x: usize, y: usize) -> usize {
  x + y
}

struct Options {
  add_numbers: bool,
  left: usize,
  right: usize,
}

fn do_it(options: Options) -> usize {
  if options.add_numbers {
    add_two_numbers(options.left, options.right)
  } else {
    options.left - options.right
  }
}

fn main() {
    let result = do_it(Options { add_numbers: true, left: 10, right: 3 });
    let result_2 = do_it(Options { add_numbers: false, left: 9, right: 5 });

    println!("result = {}, result_2 = {}", result, result_2);
}

```

</details>

Since this is working and this issue is rather old, I'm going to close.
