### ISSUE TITLE
Incorrect `unused_extern_crate` warning while testing

### ISSUE THREAD

**Issue by dhardy** [rust-lang/rust#37648]
Given a new library with this dependency:

    [dependencies]
    env_logger = "0.3.5"

and this `src/lib.rs`:
```rust
#![warn(unused_extern_crates)]

// #[cfg(test)]
extern crate env_logger;

#[cfg(test)]
mod tests {
    use env_logger;
    
    #[test]
    fn it_works() {
        env_logger::init().unwrap();
    }
}
```

I would expect `cargo build` to warn about the unused crate `env_logger` (it does) but `cargo test` not to, since it does use it (it incorrectly claims the extern crate is not used).

The fix for users is to uncomment the `#[cfg(test)]` line above, however the warning is completely misleading (and worse if `#![deny(warnings)]` is used). When calling `cargo test`, the compiler should probably not even be aware that the extern crate is unused in other configurations (or if it is, the warning should be fixed).

**Comment by sfackler** [comment]
`cargo test` builds the crate twice - as a test and as a library (for doctesting). It is the second build that triggers the unused crate warning.

**Comment by dhardy** [comment]
Fair enough, but reporting that a crate is unused when it is used in some configurations is still incorrect. Not that I have any ideas for how to solve this; and the fix is probably not specific to the "unused extern crate" warning.

**Comment by TheNeikos** [comment]
You can put the `extern crate` inside `mod tests`

**Comment by dhardy** [comment]
@TheNeikos maybe I can, but that doesn't fix the confusing error message. As is very often the case, solving an understood problem is often much easier than understanding the problem in the first case, which is why good warning and error messages is important.

**Comment by TheNeikos** [comment]
The only confusing part I see is that cargo test doesn't make it 100% clear what part it builds when.
Maybe that would clear it up? So that way one can associate the warning with the correct build.

**Comment by dhardy** [comment]
Possibly. You want to implement multi-threaded builds with per-build message grouping? That would help, but it would have to hold back all messages until a build finishes or something.

**Comment by Mark-Simulacrum** [comment]
I believe the problem here is that we build crates twice with Cargo test, and so that leads to an incorrect error message specifically for `cargo test`. I don't think that this is a bug, though, since there is still a problem with the code without the `#[cfg(test)]` annotation.

If you're interested in the cargo changes to print the individual phases of test compilation (with and without `cfg(test)`) then please file a bug on rust-lang/cargo. Thanks!
