### ISSUE TITLE
Parse doc-comments on macro variants and render them in Rustdoc

### ISSUE THREAD

**Issue by abonander** [rust-lang/rust#37679]
I wanted to do something like the following to document how my macro behaves when invoked in different ways:

```rust
macro_rules! foo {
    /// Does a thing
    ($bar:expr) => ();
    /// Does a different thing
   ($baz:expr = $qux:expr) => ();
}
```

However, I was disappointed to find that it is not accepted by the parser as valid, even though regular comments are accepted in this position. But since regular comments are not rendered by Rustdoc, this doesn't really help me.

I think this would be really helpful in documenting behavior of macros, which is already difficult enough. However, I'm not sure how this needs to be approached and how big of a change it would be:

If the parser can be taught to treat doc-comments in this position as regular comments and Rustdoc can be taught to recognize them as doc-comments and render them in documentation, this wouldn't require any amendment to the grammar.

Otherwise, if we need to amend the language grammar to allow attributes on macro variants (and thus continue to expand doc-comments as normal), then this would obviously need an RFC and discussion. However, this could also allow other interesting attributes on macros, like `#[doc(hidden)]` for hiding macro variants that are primarily implementation details, or `#[cfg(...)]` for conditionally enabling macro variants.

I guess I can just use regular comments and ask the user to click the source link in the documentation for more details, or just use different macros altogether (I may end up doing that anyway as it might be better in my case, but still). However, I would consider these to be stopgap measures at best, IMO, especially since making this proposal work would be a nice win for documenation ergonomics.

**Comment by keeperofdakeys** [comment]
You can do this using the attribute form of the doc comment.

```
macro_rules! documented {
  ($(#[$attr:meta])*) => {
    fn foobar() {
    }
  }
}

documented!(#[doc = "Function foobar"]);
documentd!(
/// Function foobar
);
```

**Comment by abonander** [comment]
@keeperofdakeys No no no no, I want to document the macro variants themselves, not generate doc-comments in the macro. That's been working for a while now.

The parser accepts doc comments nor attributes in the position I described above.

**Comment by abonander** [comment]
@jseyfried You might be interested in this.

Allowing attributes on macro variants would be neat but I get the impression that there's not much interest in new features for `macro_rules!`. It would also require an RFC, which I am willing to draft. Maybe we could start with only allowing `#[doc]` attributes at first as I assume they don't do anything outside of Rustdoc.

**Comment by jseyfried** [comment]
Hmm, this might not make sense with macros 2.0 depending on how we end up doing matching.
I don't have a strong opinion on whether this would worth it for `macro_rules!`.
cc @nrc

**Comment by nrc** [comment]
I think this would be hard to implement. Doc comments are attributes on AST nodes and macros do not have AST nodes, they are just tokens. I think the pattern matching is pretty much an implementation detail of the macro too, so I'm not even sure this is appropriate.

**Comment by abonander** [comment]
Rustdoc does render the patterns, though, so it would make sense to be able to document the differences if they do behave differently.

As I understand it, `macro_rules!` is implemented as a compiler plugin so it does see attributes as tokens, but then it errors because it was expecting a pattern. It seems relatively simple to just have it ignore `#[doc]` when expanding (it can throw errors for other attributes, I know supporting arbitrary attributes is unrealistic) and then Rustdoc can recognize these attributes when parsing and render them as doc comments.

**Comment by abonander** [comment]
@jseyfried Is this idea feasible with macros 2.0? I haven't looked very closely at how pattern matching is supposed to work in the new system.

**Comment by jseyfried** [comment]
@abonander
We're thinking the following (not yet implemented)
```rust
macro m($toks:ts) {
    match!($toks, {
        (..) => { .. },
        (..) => { .. },
    });
}
```
with this following sugar (implemented today)
```rust
match m { (..) => { .. }, (..) => { .. } }
```

I think it would be feasible but (imo) not worth the complexity.

**Comment by abonander** [comment]
Closing as this doesn't seem like there's any interest in it.

**Comment by SOF3** [comment]
This might be useful on macros with many variants.
