### ISSUE TITLE
[src] links in beta and nightly documentation are broken

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#37684]
At least some of the `[src]` links in the beta standard library documentation are currently broken. I tried https://doc.rust-lang.org/beta/std/iter/trait.Iterator.html and https://doc.rust-lang.org/beta/std/iter/trait.IntoIterator.html.

**Comment by bluss** [comment]
Seems to affect some items that libstd reexports from libcore.

**Comment by alexcrichton** [comment]
I'd also be interested in investigating why CI isn't catching this...

**Comment by GuillaumeGomez** [comment]
The `[src]` link should be generated based on the "original" item instead of the current one. (spitting out the obvious)

**Comment by bluss** [comment]
Ok, good news, this bug did not migrate to stable when beta did?

**Comment by alexcrichton** [comment]
Something looks off-by-one in the gotosrc links (which is why linkchecker didn't catch this). libstd thinks the iterator trait is 3636 and libcore thinks it's 3637. Sounds like the ids used by rustdoc are perhaps no longer valid?

**Comment by GuillaumeGomez** [comment]
Taking a look.

**Comment by bluss** [comment]
Thanks for fixing this! rustdoc improvements = :heart:

**Comment by ollie27** [comment]
This isn't fixed. See [`std::str::Chars`](https://doc.rust-lang.org/nightly/std/str/struct.Chars.html). The link is https://doc.rust-lang.org/nightly/core/str/struct.Chars.html?gotosrc=42892 but it should be https://doc.rust-lang.org/nightly/core/str/struct.Chars.html?gotosrc=42906. They differ by 14 which is the same number of items with `#[cfg(dox)]` in [`src/libcore/macros.rs`](https://github.com/rust-lang/rust/blob/master/src/libcore/macros.rs) so I think it's the same issue.

**Comment by GuillaumeGomez** [comment]
Taking another look then.
