### ISSUE TITLE
Add support for a import_name attribute to control the name of the symbol that is imported

### ISSUE THREAD

**Issue by m4b** [rust-lang/rust#37683]
I can't seem to find the ability to do this, and I noticed `export_name` so I figured maybe I should add a RFC for this, but since I stole this title from an issue (
https://github.com/rust-lang/rust/issues/8735) raised by @huonw, and the changes were minimal, maybe it too will be minimal. :wink: 

## Proposal

Add an `#[import_name = "ZNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEE12_M_constructIN9__gnu_cxx17__normal_iteratorIPwS4_EEEEvT_SA_St20forward_iterator_tag"]` attribute inside of `extern` blocks to specify the  exact name of an import, but a different local name in the code.

E.g.:

```rust

extern {
  #[import_name="_ZN6snappy13RawUncompressEPKcmPc"]
  pub fn snappy_raw_uncompress();
}
```

## Reason

1. To make first steps to linking against C++ or beginning of C++ "interop"
2. Sometimes symbol names have unwritable characters in rust function names, and hence are not even importable via normal means.  You can create this situation right now by `#[no_mangle]` and `#[export_name]` and then create a dynamic library.

## Pros

1. The duality is nice. seriously
2. Anyone can experiment with the C++ ABI by painfully writing out import names if they want (or even better, automate it by scanning exported symbols, and piping them into a compiler extension :sunglasses: )
3. Can now import functions with unusable function names

## Cons

1. Another thing.
2. Could be abused?
3. ?

**Comment by cuviper** [comment]
I believe `#[link_name="foo"]` already does what you want -- see [FFI attributes](https://doc.rust-lang.org/reference.html#ffi-attributes).

**Comment by m4b** [comment]
Yup; I swear I tried this already and it did not work; then asked on irc, and then googling link_name showed it was used (at some point) for the binary to be linked against (e.g. `https://github.com/rust-lang/rust/issues/1295` and `https://github.com/rust-lang/rust/issues/1296`)

Thanks!
