### ISSUE TITLE
Stop rebuilding crates during testing

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#3770]
We have unit tests inline with crates, and testing them involves recompiling the crates in test mode. This is bad for development times. We are currently doing this for core, std, _rustc_, rustdoc, and cargo.

My preference is just to always compile the crates with tests and use an external test runner to invoke them. It will add some compile time to non-testing builds, and some size to the binaries so maybe we can have a way to turn them off.

We could also move all tests to their own libraries, but it would preclude testing private functions.

**Comment by steveklabnik** [comment]
Triage: no updates. I'm not sure this is somthing that will ever get implemented.

**Comment by alexcrichton** [comment]
This is quite an old bug at this point, and I think that we've got enough options for this today. With Cargo we can have external test suites in `tests/*.rs` and otherwise upcoming incremental compilation I believe may render this issue moot anyway
