### ISSUE TITLE
*mut T documentation disappeared

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#37715]
See https://doc.rust-lang.org/1.12.1/std/primitive.pointer.html vs https://doc.rust-lang.org/1.13.0/std/primitive.pointer.html

Tags: A-documentation or A-rustdoc and regression-from-stable-to-stable

**Comment by bluss** [comment]
But the doc is present in nightly: https://doc.rust-lang.org/nightly/std/primitive.pointer.html

**Comment by ollie27** [comment]
This was fixed by #36966.

**Comment by jethrogb** [comment]
Can you add a test?
