### ISSUE TITLE
Multiple unused formatting argument notes should use multispan

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#37718]
After https://github.com/rust-lang/rust/pull/37613, the output for `format!` errors looks like:

```
error: multiple unused formatting arguments
  --> $DIR/format-foreign.rs:12:5
   |
12 |     println!("%.*3$s %s!/n", "Hello,", "World", 4);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: argument never used
  --> $DIR/format-foreign.rs:12:30
   |
12 |     println!("%.*3$s %s!/n", "Hello,", "World", 4);
   |                              ^^^^^^^^
note: argument never used
  --> $DIR/format-foreign.rs:12:40
   |
12 |     println!("%.*3$s %s!/n", "Hello,", "World", 4);
   |                                        ^^^^^^^
note: argument never used
  --> $DIR/format-foreign.rs:12:49
   |
12 |     println!("%.*3$s %s!/n", "Hello,", "World", 4);
   |                                                 ^
   = help: `%.*3$s` should be written as `{:.2$}`
   = help: `%s` should be written as `{}`
   = note: printf formatting not supported; see the documentation for `std::fmt`
= note: this error originates in a macro outside of the current crate
```

that's a lot of lines dedicated to underlining macro acruments. They should all be output in one multispan.

cc @DanielKeep @estebank @jonathandturner @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Hum indeed. If no one has taken it in 12 hours, I'll give it a look.

**Comment by DanielKeep** [comment]
@GuillaumeGomez I'm poking at it right now.  I *think* I need to fix `ExtCtxt`'s methods to accept `<S: Into<MultiSpan>>` instead of just `Span`, and then I can use `MultiSpan` directly.

After all, I *created* the problem, I should *probably* fix it.  :P

**Comment by GuillaumeGomez** [comment]
Perfect. Good luck! :)

**Comment by cramertj** [comment]
I believe this should be closed.

**Comment by GuillaumeGomez** [comment]
Hold on, it seems the PR is still open.

**Comment by perryprog** [comment]
Seeing as there isn’t anyone working on this anymore, I’ll be happy to take over.

This is my first issue, (woot), so I’m not exactly sure where to start. I assume I should just fork the repo, change `format.rs` to use `span_lable`, and fix the tests?

Pinging @Nickforall and @DanielKeep in case you want to work on this still.

**Comment by Nickforall** [comment]
@perryprog I am not working on this anymore.

**Comment by Nickforall** [comment]
@perryprog I am not working on this anymore.

**Comment by Mark-Simulacrum** [comment]
@perryprog Those steps may be correct; @GuillaumeGomez or someone else may be able to verify for you. You can also look at #41256 and #37729 which appear to be previous PRs which attempted to do this. Let us know if you'd like any help!

**Comment by perryprog** [comment]
@Mark-Simulacrum Awesome! I'm super excited. Anyone specific I should `r?`?

**Comment by estebank** [comment]
@perryprog bors will select someone automatically if you don't specify anyone, but I think any of me, @GuillaumeGomez, @Mark-Simulacrum, @jonathandturner or @nikomatsakis would be available for review and or guidance.

**Comment by perryprog** [comment]
For some reason I seem to be getting [test errors](https://gist.github.com/perryprog/41b1972c04c17faaf74a87600e28f45e) unrelated to my changes. (ran `./x.py test --stage 1`)

**Comment by perryprog** [comment]
For some reason I seem to be getting [test errors](https://gist.github.com/perryprog/41b1972c04c17faaf74a87600e28f45e) unrelated to my changes. (ran `./x.py test --stage 1`)

**Comment by Mark-Simulacrum** [comment]
Those tests shouldn't actually be running in `--stage 1`... cc @alexcrichton. For these changes, I would suggest `./x.py test --stage 1 src/test/{compile-fail,ui}`, I think that should be enough.

**Comment by perryprog** [comment]
Gotcha, it’s possible I copy pasted from the wrong command (on mobile can’t check right now), but I’ll use that command for testing and see if it works.

I’m kinda busy for the rest of the week but I’ll keep working on it in my free time. I’ll comment here until I get a PR ready with any updates I have.
