### ISSUE TITLE
Separate trait items from trait

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#37712]
PR https://github.com/rust-lang/rust/pull/37660 separates impl items from impls in the HIR for improved interaction with incremental compilation. It probably makes sense to separate trait items from traits too -- not *so* much for improved incremental compilation precision, as because it makes the layout more analogous.

**Comment by nikomatsakis** [comment]
Marking this as E-mentor. I'll give a short write-up here; happy to provide a more detailed one too upon request!

The work that needs to be done is basically to model trait items on impl items -- we would get a `hir::TraitItemRef` like `hir::ImplItemRef`, a separate map in the `Krate` to store them, and modify the lowering routines analogously. Finally, there are a few places (marked with FIXMEs attached to this issue number) where we could convert to using a `ItemLikeVisitor` if trait items were considered "item like".

**Comment by eddyb** [comment]
Apologies to anyone who wanted to pick this up, but I was blocked on it so I did it, PR coming soon.

**Comment by eddyb** [comment]
Somehow the merge of #38449 didn't close this.
