### ISSUE TITLE
impl definitions

### ISSUE THREAD

**Issue by eav** [rust-lang/rust#37731]
Learning rust, maybe this is just me, but really difficult to get used to impl definitions:
```
trait Trait1 { ... }
trait Trait2WithAnotherName { ... }
struct Struct1 { ... }
```

```
impl Struct1 { ... }
impl Trait1 for Struct1 { ... }
impl Trait2WithAnotherName for Struct1 { ... }
```
would prefer something like this:

```
impl Struct1 { ... }
impl Struct1 with Trait1 { ... }
impl Struct1 with Trait2WithAnotherName { ... }
```

it's consistent, has the same indentation and much easier to read

**Comment by TimNN** [comment]
I don't think a change like this is likely to happen (even for something like rust 2.0):

* A change like this would break literally *all* (almost) existing rust code
* `impl Trait for Struct` is grammatically more correct than `impl Struct with Trait`, I think
* one can do things like `impl<T: AnotherTrait> Trait for T` which doesn't read that well in the proposed syntax: `impl<T: AnotherTrait> T with Trait` (in my opinion)

**Comment by petrochenkov** [comment]
Ok, suppose for a second we are in the RFC repo.

>A change like this would break literally all (almost) existing rust code

I suppose an extension is suggested, not a replacement.

>impl Trait for Struct is grammatically more correct than impl Struct with Trait, I think

We can use `impl Struct as Trait { ... }` to mirror UFCS `<Struct as Trait>::method()`.

---

I certainly feel @eav 's pain, it's hard to visually scan code in search of `Struct`'s interface, it would be nicer if `Struct` was immediately visible if and impl is part of its interface.

It would also be nice to be able to define impls right in the struct's body to avoid all the impl boilerplate and further localize `Struct`'s interface.

```
struct S {
    x: u8,
    y: u8,

    fn inherent_method() -> u8 { self.x + self.y }

    as Trait {
         fn trait_method() -> u8 { self.x - self.y }
    }
}
```

**Comment by eav** [comment]
Exactly my frustration comes mainly from reading code, where I always have to move eyes from left to right then from right to left just to see the actual type. Besides it's more logical to have type followed by trait. We used this rule for years for example, in java we define class then list interfaces one by one, the same thing with scala but with traits, in c++, and even in go you first see type then method. And now it's difficult at least for me to switch over.

@petrochenkov I think having both will mix things up, and I would not want to pollute the language without very good reason. Yes, frankly I doubt that replacement will ever happen as it's a core syntax and it had to be thought well out from the begining.  Anyway I just decided to share my first impressions about the language.

**Comment by nagisa** [comment]
Break the lines in some way (rather than putting everything in a single line) and it should become better very fast. For example I prefer writing impls like this instead:

```rust
impl Trait2WithAnotherName<A, B, C>
for Struct1
where A: This, B: There, C: Then {
    ...
}
```

It helps with scanning a lot. Maybe there’s more lines, but certainly has more pattern to match against.

---

That being said, I agree with @TimNN that this is inactionable and this probably isn’t a right forum for first language impressions (those go into [users](https://users.rust-lang.org/) forum or [reddit](https://reddit.com/r/rust).)

**Comment by steveklabnik** [comment]
Yes, thank you for telling us about your experiences, @eav , but this isn't the right place.

For requesting changes to the language, https://github.com/rust-lang/rfcs is the proper place. This has backwards compatibility issues though.

For general discussion, https://users.rust-lang.org/ is.

Please make a thread in one of those places if you'd like to continue this discussion!
