### ISSUE TITLE
Nightly regression: empty lifetime list in `for<lifetime-list>` doesn't parse anymore

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#37733]
Code:
```
type A = for<> fn(); // error: trailing attribute after lifetime parameters

fn main() {}
```
Compiles on 1.13-stable,beta, fails on 1.14-nightly.

**Comment by TimNN** [comment]
I think this was a deliberate change, I'm pretty sure I remember a PR who's whole point was to disallow exactly that (although I can't finde the PR right now).

**Comment by TimNN** [comment]
Apart from that, this was introduced between `nightly-2016-09-30` and `nightly-2016-10-03` ([Changes](http://github.com/rust-lang/rust/compare/289f3a4ca...144af3e97)).

**Comment by petrochenkov** [comment]
I strongly suspect this is an unintended side effect of https://github.com/rust-lang/rust/pull/34764.
Prohibiting this deliberately doesn't make any sense, empty lists are allowed in ([almost](https://github.com/rust-lang/rust/pull/37511#issuecomment-260127091)) all other possible cases.

**Comment by TimNN** [comment]
Yeah, I probably mis-remembered :(

I agree that this was probably a side effect of #34764.

**Comment by est31** [comment]
In fact, this fails too:

```rust
type B = for<'a,> fn();
```
