### ISSUE TITLE
Rustdoc: src links are broken

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#37739]
E.g., the src link at the top right of https://doc.rust-lang.org/nightly/std/cmp/enum.Ordering.html links to https://doc.rust-lang.org/nightly/core/cmp/enum.Ordering.html?gotosrc=33347 which redirects to https://doc.rust-lang.org/nightly/core/cmp/undefined

I haven't found any links which aren't broken, but tbh I haven't tried that hard.

**Comment by bluss** [comment]
This was #37684 and it is hopefully fixed now (closed 11 hours ago).
