### ISSUE TITLE
Confusing error messages (a closure can't be cloned)

### ISSUE THREAD

**Issue by gibfahn** [rust-lang/rust#37736]
Trying to filter and then clone an Iterator over the `chars` in `&str`, I'm getting an error message that was pretty opaque (at least to me).

### [Code](https://is.gd/kdA1hD)
```rust
    let f = |c: &char| c.is_digit(10);
    let iter = "abc123".chars().filter(f);
    match iter.clone().take(3).count() {
        3 => println!("{}", iter.collect::<String>()), // Print whole string including first three digits
        _ => {},
    }
```

### Error
```rust
error: no method named `clone` found for type `std::iter::Filter<std::str::Chars<'_>, [closure@test.rs:2:13: 2:38]>` in the current scope
 --> test.rs:4:16
  |
4 |     match iter.clone().take(3).count() {
  |                ^^^^^
  |
  = note: the method `clone` exists but the following trait bounds were not satisfied: `[closure@test.rs:2:13: 2:38] : std::clone::Clone`

error: aborting due to previous error
```

It'd be nice if this error gave more info about how to fix the problem (the fix seems to be to change L1 from `let f = |c: &char|` to `let f = &|c: &char|`). 

Sorry if this is a duplicate, I couldn't find anything obvious.

**EDIT:** What I'm trying to do is to make sure there are at least three digits in my Iterator before I actually collect it, I suspect the right answer isn't changing the filter closure (I'm not sure why that fixes the compiler error tbh), but using something else instead of `iter.clone()`.

**Comment by tirkarthi** [comment]
@gibfahn Asked the same at IRC. Its caused because closures inside the filter cannot be cloned. Passing & before the closure makes it a reference and references are always clone-able. Please find the chat log at https://botbot.me/mozilla/rust/2016-11-14/?msg=76433946&page=11 . Hope it helps

**Comment by gibfahn** [comment]
Thanks a lot @tirkarthi! Very helpful.

Now I understand the issue the error message seems obvious, but if it were possible to say something like `Closures can't be cloned, try using a function instead` it might be clearer. 

Maybe even something including the suggestion from Quxxy2 about using `fn f(c: &char) -> bool { c.is_digit(10) } "abc123".chars().filter(f as fn(_) -> _);`.

@jonathandturner @nikomatsakis Would a more specific error message be feasible/desirable? If not I'll close.

**Comment by gibfahn** [comment]
Looks like this will be fixed by https://github.com/rust-lang/rust/issues/44490.

**Comment by estebank** [comment]
The code now compiles without errors.
