### ISSUE TITLE
Update `Carrier` trait docs

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#37751]
Carrier trait docs need to be updated and fleshed out for its current implementation and relation to `?` (question mark operator).

**Comment by nrc** [comment]
The `Carrier` trait is not stable and is not intended to be used yet. I'd prefer if we didn't document in such a way that people actually use it.

**Comment by steveklabnik** [comment]
This would be a part of https://github.com/rust-lang/rust/issues/29365, and yes, we don't make documenting unstable things a priority. Let's give this a close in favor of that one, thanks!
