### ISSUE TITLE
Document `?` (question mark operator) in the Error Handling chapter in the book

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#37750]
The question mark operator needs to be covered in the error handling chapter.

**Comment by steveklabnik** [comment]
The existing book isn't getting updated by me, and the new book focuses on `?`. I'd take a patch for this, if someone wants to improve the situation before then, but since this isn't going to get closed in this form, I'm gonna give this a close, thanks!

**Comment by sourcefrog** [comment]
I just wanted to note that https://doc.rust-lang.org/std/macro.try.html now says 

> Prefer using ? syntax to try!. ? is built in to the language and is more succinct than try!. It is the standard method for error propagation.

but there's no obvious official explanation what that syntax is. 

I realize that might be transient.

**Comment by antrik** [comment]
I'd like to point out that more than half a year later, https://doc.rust-lang.org still links to https://doc.rust-lang.org/book/ as the primary resource, which doesn't explain the `?` at all as far as I can tell, aside from mentioning that it is "similar to try!"...

(And https://doc.rust-lang.org/reference/ doesn't seem to mention it either.)

**Comment by d9n** [comment]
Looks like the new book is covering it:

https://doc.rust-lang.org/book/second-edition/ch09-02-recoverable-errors-with-result.html#a-shortcut-for-propagating-errors-

**Comment by antrik** [comment]
@d9n the point was that until recently, the "old" book still was linked as the main documentation. I see that this changed now though -- so it's no longer an issue :-)
