### ISSUE TITLE
Ref<T> and &T have different lifetime requirements

### ISSUE THREAD

**Issue by KiChjang** [rust-lang/rust#37785]
This does not compile: https://is.gd/aNuNEg

This compiles:  https://is.gd/lInFDJ

Found when trying to solve https://github.com/servo/servo/pull/13418#discussion_r88085325

**Comment by bluss** [comment]
Ref has the drop-check rule because it has a destructor (Essentially issue #22321)

**Comment by KalitaAlexey** [comment]
Dear @bluss,
Is there any work in progress on it?

**Comment by memoryruins** [comment]
Triage: now compiles on 2018.
2015 errors:
```
error[E0597]: borrowed value does not live long enough
  --> src/main.rs:18:9
   |
18 |         Document { url: RefCell::new("hi".into()) }.url().clone()
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ temporary value does not live long enough
19 |     }
   |     - temporary value dropped here while still borrowed
   |
   = note: values in a scope are dropped in the opposite order they are created
```
`rustc: 1.32.0`

**Comment by pnkfelix** [comment]
FYI @memoryruins The use of NLL should not affect the dynamic semantics, at least in terms of when values are dropped.

Therefore the use of NLL-fixed-by-NLL might remain appropriate here. I'm investigating now.

**Comment by matthewjasper** [comment]
Closing since the code now compiles on both editions on nightly
