### ISSUE TITLE
Docs: Tooltips on hover for types from other crates

### ISSUE THREAD

**Issue by casey** [rust-lang/rust#37794]
I was looking at [docs for tokio-proto](https://tokio-rs.github.io/tokio-proto/tokio_proto/easy/multiplex/fn.connect.html), and noticed that there were helpful tooltips for types defined in the crate, but not for types like Handle and FramedIo, whice are defined in other crates.

It would be great if, even if they aren't clickable, types outside of the crate would get tooltips showing the full path of the type, to hint at where to look to learn more. So `Handle` would show a tooltip with `tokio_core::reactor::Handle` and `FramedIo` would show one with `tokio_core::io::FramedIo`.

**Comment by bluss** [comment]
FramedIo would be clickable if the crate that defines it sets the `#![doc(html_root_url)]` attribute.

**Comment by casey** [comment]
Having them be clickable would be great, but even if not, could they still have tooltips?

**Comment by jyn514** [comment]
Triage: this still happens today.

![image](https://user-images.githubusercontent.com/23638587/124698809-98de0280-deb7-11eb-86ca-048ed152c338.png)

**Comment by GuillaumeGomez** [comment]
It was fixed in https://github.com/rust-lang/rust/pull/107242.
