### ISSUE TITLE
unit test `coretest::num::test_i32f64` fails on some targets (again)

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#37805]
I'm seeing #36518 again in [smoke](https://github.com/japaric/smoke/pull/32). Same test but different affected targets and error message.

Affected targets:

- [mips-unknown-linux-gnu](https://travis-ci.org/japaric/smoke/jobs/176448202#L3586)
- [mips64-unknown-linux-gnuabi64](https://travis-ci.org/japaric/smoke/jobs/176448204#L3570)
- [mips64el-unknown-linux-gnuabi64](https://travis-ci.org/japaric/smoke/jobs/176448205#L3114)
- [mipsel-unknown-linux-gnu](https://travis-ci.org/japaric/smoke/jobs/176448206)

Note that the mips64 targets are new-ish and that the 32-bit mips targets are "old" but weren't affected by #36518.

Error message:

```
---- num::test_i32f64 stdout ----

	thread 'num::test_i32f64' panicked at 'assertion failed: `(left == right)` (left: `2147483647`, right: `-2147483648`)', /rust/lib/rustlib/src/rust/src/libcoretest/num/mod.rs:162
```

cc @brson @pnkfelix

**Comment by steveklabnik** [comment]
Triage: not sure what the status of this bug is.

**Comment by Dylan-DPC** [comment]
Closing this to clear up the issue tracker, and this test is likely fixed already
