### ISSUE TITLE
Compiling `libunwind` with `--test` for arm-musl targets produces dynamically linked binaries

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#37811]
When it should produce statically linked binaries like it does when it's (unwind is) compiled for x86_64-musl.

### STR

```
$ rustup component add rust-src

$ rustup target add arm-unknown-linux-musleabihf

$ rustc --crate-name=unwind --target arm-unknown-linux-musleabihf --test -C linker=arm-linux-gnueabihf-gcc $(rustc --print sysroot)/lib/rustlib/src/rust/src/libunw
ind/lib.rs

$ file unwind
unwind: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, not stripped
```

Furthermore, this part: `/lib/ld-linux-armhf.so.3` is wrong because that's the glibc dynamic loader which won't work with MUSL binaries. This Rust MUSL binary doesn't a dynamic loader to begin with; the binary should be fully statically linked.

Should be easy to fix, I think. Some `cfg` on some `extern` block probably isn't correctly handling the `cfg(test)` case. The `extern` block should be in `src/libunwind` (this repo) or in rust-lang/libc (`gcc_s` related stuff).

(Found via [smoke](https://github.com/japaric/smoke))

**Comment by alexcrichton** [comment]
I believe [this line is at fault](https://github.com/rust-lang/rust/blob/9d4b6fa51d86ad6141679a5a157fcd9bca48064c/src/libunwind/libunwind.rs#L241-L249), and this is fixed if you pass `--cfg cargobuild`. Hopefully when we transition away from the makefiles though we can get rid of that `--cfg cargobuild`!

In the meantime though I'm not sure this is a bug, but perhaps an extra flag that can be passed with smoke?

**Comment by brson** [comment]
Is this still a problem now that makefiles are dead?

**Comment by Mark-Simulacrum** [comment]
@alexcrichton @japaric Could someone verify if this has been fixed or if the fix has gotten even easier now that makefiles are gone?

**Comment by kevinmehall** [comment]
Appears to be fixed.

```
$ rustc --version
rustc 1.20.0-nightly (37849a002 2017-06-30)

$ rustc --crate-name=unwind --target arm-unknown-linux-musleabihf --test -C linker=arm-linux-gnueabihf-gcc $(rustc --print sysroot)/lib/rustlib/src/rust/src/libunwind/lib.rs

$ file unwind
unwind: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, BuildID[sha1]=05aec867a6e0d108a33c209fb6f8bf92ccdb069e, not stripped
```

**Comment by Mark-Simulacrum** [comment]
Marking e-needstest though if that's hard we can skip that I think.

**Comment by tamird** [comment]
For posterity, it seems that this was fixed in https://github.com/rust-lang/rust/pull/35060/commits/f0ec906d186a87b4b4c08b71a82f0e8803a110df. Also, adding a test seems hard, unless someone can point me to precedent for this kind of test (which would necessarily run only on linux+arm)?

**Comment by tamird** [comment]
Actually, it's more than that; this requires a cross toolchain. The test here is basically [smoke](https://github.com/japaric/smoke); I think this should be closed.

**Comment by sanmai-NL** [comment]
@Mark-Simulacrum: This issue can be closed now.
