### ISSUE TITLE
Provide an API for `std::process::Command` to set `CreateProcess` flags on Windows

### ISSUE THREAD

**Issue by luser** [rust-lang/rust#37827]
# Updated report

Now a tracking issue for `CommandExt::creation_flags` on Windows.

Open questions:

* Should we provide a method of *adding* flags as opposed to setting them entirely? Would be a bit more composition-friendly.

Also, don't forget to add to the prelude when stabilizing!

# Original report

There's a currently-unused codepath in the Windows implementation of `std::process::Command::spawn` that can set `DETATCHED_PROCESS`:
https://github.com/rust-lang/rust/blob/b1363a73ede57ae595f3a1be2bb75d308ba4f7f6/src/libstd/sys/windows/process.rs#L162

It looks like historically there was a method to set this but it got removed. Unfortunately there's currently no way to set this, and no other way to set the `CreateProcess` flags, so for a project I'm working on I basically had to reimplement `spawn` for Windows:
https://github.com/luser/sccache2/blob/89f4b44d01084846893a64137d965ee844fe2d72/src/commands.rs#L103

I think we need some way to set this, even if it's Windows-specific. There are a bunch of other flags that can be specified, so maybe a way to set arbitrary flags would be useful?
https://msdn.microsoft.com/en-us/library/windows/desktop/ms684863(v=vs.85).aspx

I think this would fit nicely onto a Windows equivalent of the [`std::os::unix::process::CommandExt`](https://doc.rust-lang.org/std/os/unix/process/trait.CommandExt.html) trait, maybe something like:
```rust
trait CommandExt {
  fn process_flags(&mut self, flags: u32) -> &mut Command
}
```

**Comment by sfackler** [comment]
Seems reasonable to me!

**Comment by alexcrichton** [comment]
👍

**Comment by retep998** [comment]
I'm always in favor of adding more Windows specific extension traits to expose useful functionality that other platforms don't seem to have.

**Comment by alexcrichton** [comment]
> can I just use this issue as the tracking issue for the new feature

Sure!

**Comment by luser** [comment]
To the open question: I had first written the API as originally proposed: with a `creation_flags` method to set the flags directly. Then I thought that might make it difficult if callers wanted to set different flags in different places, so I split it into `set_creation_flags` and `add_creation_flags` methods, but Alex asked me to change it back. I'm not sure it's that important, I don't think there are that many process creation flags that it would be useful to set from a library context, and callers can always aggregate flags into a u32 and just call `creation_flags` with that value.

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

With the one remaining open question I think it's safe to stabilize as this is still consistent with our approach to custom flags in other areas of platform-specific extensions as well.
