### ISSUE TITLE
Tracking issue for std::process::abort

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#37838]
Added in https://github.com/rust-lang/rust/pull/37833

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

**Comment by retep998** [comment]
I have just become aware of another function for fatally aborting an application on Windows. `FatalAppExit` which displays a message box and then terminates, but if a debugger is attached it will give the user the opportunity to debug the error.

**Comment by sfackler** [comment]
Ping @brson

**Comment by brson** [comment]
@retep998 Does that affect your opinion on whether this should be stabilized as-is?

**Comment by retep998** [comment]
@brson If the desired semantics are to abort without informing the user, then the current implementation is fine. If we want to inform the user that the application crashed then `FatalAppExit` may be a better idea.

**Comment by sfackler** [comment]
It looks like `FatalAppExit` can return if the user cancels the dialog box, so if we went that route we'd have to stick a fallback abort after the `FatalAppExit` call if we went that direction.

**Comment by SimonSapin** [comment]
Is the next step a PR to change `#[unstable]` to `#[stable]`?

I’ve file a minor docs issue: #40230.

**Comment by alexcrichton** [comment]
@SimonSapin yeah that's the next step, we typically do that just before the end of a cycle

**Comment by SimonSapin** [comment]
For what it’s worth, https://github.com/servo/servo/pull/16899 is a case where `process::abort` and `intrinsics::abort` are significantly different.

> Calling `process::abort` from the crash handler causes the crash handler to be invoked again recursively.
