### ISSUE TITLE
Using associated types on concrete types as parameters for trait impls causes incorrect type resolution

### ISSUE THREAD

**Issue by dylanede** [rust-lang/rust#37832]
This small example:

```rust
use ::std::borrow::ToOwned;

struct Foo;

impl From<<bool as ToOwned>::Owned> for Foo {
    fn from(v: <bool as ToOwned>::Owned) -> Foo {
        unimplemented!()
    }
}
```

causes the error E0119: "conflicting implementations of trait `std::convert::From<Foo>` for type `Foo`", though I have not written an implementation of `From<Foo>` anywhere. `<bool as ToOwned>::Owned` should be synonymous with `bool`, but in this case it doesn't appear to be, as replacing the first use of the associated type with `bool` stops the error.

I have observed this on stable, beta, and the latest nightly.

**Comment by Mark-Simulacrum** [comment]
Looks like a case of insufficient normalization.

**Comment by lcnr** [comment]
closing this as a duplicate of https://github.com/rust-lang/rust/issues/85576#issuecomment-2058244779. THanks for opening this issue 👍
