### ISSUE TITLE
Merge def_mod and def_ty maybe

### ISSUE THREAD

**Issue by pcwalton** [rust-lang/rust#3784]
Might simplify some code now that they're in one namespace.

**Comment by frewsxcv** [comment]
Triage: I can confirm that `DefMod` and `DefTy` still live in the codebase

[DefMod](https://github.com/rust-lang/rust/blob/ca4b9674c26c1de07a2042cb68e6a062d7184cef/src/librustc/middle/def.rs#L28)

[DefTy](https://github.com/rust-lang/rust/blob/ca4b9674c26c1de07a2042cb68e6a062d7184cef/src/librustc/middle/def.rs#L34)

**Comment by petrochenkov** [comment]
This can be closed now, I believe.
`def_mod` and `def_ty` are now `Def::{Mod, Enum, TyAlias and maybe Struct}` and they are often used after resolve, when types and modules are treated very differently.

**Comment by arielb1** [comment]
I think this was fixed.
