### ISSUE TITLE
Build fails on s390x - Appears unable to download stage0

### ISSUE THREAD

**Issue by gwfisher** [rust-lang/rust#37847]
I'm building rust on the s390x platform, and it's failing where it should be getting it's stage0 compiler. I'm not a python programmer, but it gives me this:

Traceback (most recent call last):
  File "/data/rust/src/etc/get-stage0.py", line 46, in <module>
    main(sys.argv[1])
  File "/data/rust/src/etc/get-stage0.py", line 34, in main
    bootstrap.get(url, dst)
  File "/data/rust/src/bootstrap/bootstrap.py", line 42, in get
    if not verify(temp_path, sha_path, True):
  File "/data/rust/src/bootstrap/bootstrap.py", line 74, in verify
    expected, _ = f.readline().split()
ValueError: too many values to unpack
make: *** [s390x-unknown-linux-gnu/stage0/bin/rustc] Error 1

If I go to the stage0 URL, it gives me a 404. The stage0 URL is:

https://static.rust-lang.org/dist/2016-09-28/rustc-beta-s390x-unknown-linux-gnu.tar.gz

Where can I get a different stage0 snapshot?

Thanks!

**Comment by gwfisher** [comment]
Solved. Sorta. I had to manually change the date to today in rust/src/etc/get-stage0.py and it downloaded rustc. Not the expected behavior, but it works

**Comment by alexcrichton** [comment]
Thanks for the report! I believe the first release which will have an s390x compiler is 1.14, which is currently in beta. Once https://github.com/rust-lang/rust/pull/37800 lands to update master (1.15) to bootstrap from beta (1.14) then this error should be resolved.

**Comment by gwfisher** [comment]
Excellent! :D I'll be looking forward to the next release. I'm excited to do rust work on system/z. I'll close this issue since the devs are aware of it.
