### ISSUE TITLE
Panic still: proc-macro

### ISSUE THREAD

**Issue by sackery** [rust-lang/rust#37845]
error: internal compiler error: ../src/librustc_metadata/decoder.rs:490: entry: id not found: DefIndex(1) in crate "serde_derive" with number 105

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'Box<Any>', ../src/librustc_errors/lib.rs:424
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by sackery** [comment]
with serde-derive.
rustc-nightly_11-17

**Comment by keeperofdakeys** [comment]
This looks like the same issue as https://github.com/rust-lang/rust/issues/37788, which should be fixed in the next nightly.
