### ISSUE TITLE
Doc suggestion: Layout of Struct traits, methods, etc. vs Module traits, etc.

### ISSUE THREAD

**Issue by johnwhelchel** [rust-lang/rust#37856]
# Doc Design Issue Thoughts

I've been looking into Rust a lot more lately after two false starts over the past couple of years, so I think I fit the pattern for a lot of people who are interested but are struggling to get over the hump of grokking Rust. One thing I've noticed and had "click" for me about the documentation that I find confusing is the difference between what's in the sidebar, and the user is actually searching for looking at. As an example, today I googled for the 'rust String doc' and was taken to this page.

![screen shot 2016-11-18 at 10 32 07 am](https://cloud.githubusercontent.com/assets/4014841/20435486/4e0e4bf2-ad7a-11e6-9569-845d58563bda.png)

I only just realized that everything on the left doesn't relate to the struct String at all. It relates to it's parent module std::string. If I want to see a list of functions String implements, I have to either scroll through the entire page, or hit the minus button in the upper right and scroll (which has pretty low discoverability, I only found out about it when trawling though an old thread on /r/rust. Perhaps it could be just the word "collapse" or "collapse all"? Digression, not what this issue is for).

If I want to see at a glance what traits are impl'd by String, this information also requires scrolling, and is interspersed by the actual methods on the trait themselves, so you can't see them all at once.

I would love to have the information for the Struct/Trait *at hand* more readily available for quick digestion, rather than that of its parent module. If I were looking at std::string, I would expect the information on the left of what you see in the linked image above to be front and center. And ta-da, it is ( after shrinking, while std is to the left, less distracting but there).

![screen shot 2016-11-18 at 10 37 12 am](https://cloud.githubusercontent.com/assets/4014841/20435700/192fff74-ad7b-11e6-99c4-d8739b4b33cc.png)

I suppose the idea of the current documentation is to mimic a sort of a hierarchical browser, and I do get it now. I just want to share that it was a source of confusion for me, where I would go to String docs, click on the Trait "ToString" to the left (a totally reasonable Trait to expect string to implement for itself in someway, just return itself), get confused about where I was and hit the back button. This would happen all the time. Now, looking back, I wonder how I couldn't understand, and so you all may think it's obvious as well, but I kept using the docs in a confusing fashion for a long time...

Additionally, c.f Ruby docs (which aren't that great really...) for which the left sidebar is not about the parent, but the current class

![screen shot 2016-11-18 at 11 01 28 am](https://cloud.githubusercontent.com/assets/4014841/20436508/788ffa0c-ad7e-11e6-8133-f5b9f15834ed.png)

or Java, which has the same issue but makes it more clear via separation, and presents at the top all of the implemented interfaces/subclasses, before diving into the weeds further below.

![screen shot 2016-11-18 at 11 04 08 am](https://cloud.githubusercontent.com/assets/4014841/20436579/d1643986-ad7e-11e6-88c3-27f08cc5cb8f.png)

# Proposed solution

1) Make the sidebar to the left somehow more clear that it's unrelated to the main docs at hand for a Struct/Trait/Module. Perhaps a change in background color, or a stronger vertical divider. With a different background color (light gray, e.g.), the background color of the actually selected item (to return to the first example, the 4th item in the list of Structs, the red highlighted string) could remain the same color as the main page to clue the user that they're viewing a subset or lower level "window" into on part of the information presented on the left. Here's a quick example just by changing some CSS. I resized some things and changed padding to make the colors connect, but you can get the gist.

![screen shot 2016-11-18 at 10 45 48 am](https://cloud.githubusercontent.com/assets/4014841/20435988/3ea4e99e-ad7c-11e6-83cb-cf9f6176538f.png)

2) Present the summarized information for the Trait/Struct/Enum (e.g. for a struct, a list of impl'd traits and methods) either
* in the right hand sidebar, always visible, that can be used to quickly access one in the main docs.
* beneath the top level description, but above the detailed documentation contents as a sort of "table of contents" (like the Java doc), which can be used to quickly access each relevant piece without having to scroll.

I prefer the first of those two suggestions, if only because a) the space is available b) the second solution mimics just having the page load with everything folded up (save quickly view impl'd traits, which you can't do at all) and c) the information would be visible no matter what part of the specific documentation are being viewed. This is less easy to mockup just by modifying the page but I think that get's the idea across.

I'd be happy to look into doing this if people agreed with me that it would be valuable.

**Comment by alexcrichton** [comment]
cc @rust-lang/docs

**Comment by GuillaumeGomez** [comment]
Oh, I really like the first solution (and the visual!). A darker left menu with the struct "highlighted" this way is really great! It'd be actually very simple to do. Let's see what others think as well.

**Comment by QuietMisdreavus** [comment]
If we're talking about rustdoc formatting tweaks, I'd be thrilled to help out with larger changes, or even test out some recommendations to get a visual of what something might look like.

I'd personally love it if we included some kind of table of contents on struct and trait pages, whether it's something as small as just links to the "Fields", "Methods", "Trait implementations", etc headers; or even making the sidebar display the full list on those pages. Currently the sidebar is used to hold the "sibling" elements to whatever the page is about, though, so that one could be viewed as a change in semantics.

More generally, my documentation habits come from spending a lot of time reading .NET documentation, which has condensed tables of contents like this:

![dotnet docs example](https://cloud.githubusercontent.com/assets/5217170/20440229/c12000b8-ad84-11e6-99be-e807dd592bc0.PNG)

Less relevant is that it also shuttles individual method/property/etc documentation into their own pages, opting instead to just display the summary line and a link on the class page itself. I'm hesitant to suggest going that far, but it at least can be approximated by the "collapse all" button, as you found out, so maybe more visibility for that would help.

In any case, I'll probably start tinkering on ways to provide tables of contents, and report back some generated examples once I have a few.

**Comment by steveklabnik** [comment]
Yeah I like part 1 as well. I agree that in general, rustdoc output could use an overhaul, but that's also a very long conversation. Part 1 seems very achievable.

**Comment by GuillaumeGomez** [comment]
@steveklabnik: and very easy to do! :)

**Comment by QuietMisdreavus** [comment]
So after a bit of tinkering, I had an initial idea of putting "header" links at the top of the sidebar so you could jump to different groups of elements.

![rustdoc toc](https://cloud.githubusercontent.com/assets/5217170/20452435/0cbee6a2-adcf-11e6-85cb-e952bf18fb1e.png)

![rustdoc toc part 2](https://cloud.githubusercontent.com/assets/5217170/20452434/0cbe61d2-adcf-11e6-83bc-96d55812006f.png)

Thoughts?

**Comment by GuillaumeGomez** [comment]
I don't like much like this. I really preferred when the background was darker and the current struct was with the "normal" (understand white) background color.

**Comment by frewsxcv** [comment]
Like others in here, I'm also in favor of @johnwhelchel's first proposal in the original post for this Issue.

@johnwhelchel Do you already have a branch with these changes or do you need some help implementing it?

**Comment by johnwhelchel** [comment]
I don't have a branch, my changes were simply made in the browser inspector. Just from poking around, and it looks like the HTML changes would be in the [JS](https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/static/main.js), in `initSidebarItems`. And the CSS [here](https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/static/rustdoc.css).

I'll take a look.

**Comment by johnwhelchel** [comment]
Actually, as a followup I'm not entirely sure how to make changes/test this. I've got a fork of the repo on my local machine, and have successfully run `make docs` after configuring which adds various files to the `./docs` folder. Changes to the linked JS file above though don't persist, and when re-running `makde docs` it says nothing has changed. Maybe I'm missing something obvious, but what's the standard workflow when making changes this way?

**Comment by GuillaumeGomez** [comment]
`make` isn't very smart and doesn't consider non-rs files. If you changed something in a non-rs file, just change the date of another rs file and then recompile (do it in a rustdoc rs-file to avoid too much  rebuild).

Also, is it possible to do it directly with CSS instead of playing with JS? Like I previously said, the less JS, the better. If you need to add a class when the menu is generated in JS, it's okay. But more than this might not be the best solution.

If you have trouble to do without changing too much JS, just don't mind my comment, I'll help you when you'll open the PR anyway.

Thanks for your contribution anyway!

**Comment by johnwhelchel** [comment]
I was just looking at the JS as a quick way to test that my changes were persisted by throwing in a log! I agree CSS is the way to go. I'll take a look, thanks for the advice re: make

**Comment by wesleywiser** [comment]
I hope I'm not stepping on anyone's toes but this issue looked like it had been inactive for a while so I thought I would try implementing the changes. I have a branch [here](https://github.com/wesleywiser/rust/tree/rustdoc_style) which implements this. Here's a few screenshots of the docs with this style change:

![screen shot 2017-03-04 at 12 29 48 pm](https://cloud.githubusercontent.com/assets/831192/23580829/db6c26c2-00d6-11e7-8d89-822e25ba79f0.png)

![screen shot 2017-03-04 at 12 30 10 pm](https://cloud.githubusercontent.com/assets/831192/23580828/db69eeca-00d6-11e7-9f89-1e06fd3bf098.png)

![screen shot 2017-03-04 at 12 30 31 pm](https://cloud.githubusercontent.com/assets/831192/23580830/db6d00ce-00d6-11e7-89ca-cd03e148a121.png)

Should I open a pull request with these changes?

**Comment by steveklabnik** [comment]
I like it!

**Comment by frewsxcv** [comment]
@wesleywiser Looks great!

It looks like your changes are already isolated in branch, so if opening a pull request is easy, I'd say go for it!

**Comment by wesleywiser** [comment]
Done. Huge thanks to @johnwhelchel for the great visual design!

**Comment by johnwhelchel** [comment]
Thanks to @wesleywiser for actually doing it! This had totally dropped from my mind and I had been away from Rust for a while, so I'm very glad it got done.

**Comment by GuillaumeGomez** [comment]
I guess we can now close this issue?
