### ISSUE TITLE
Rustbuild on 32-bit MSVC fails run-make tests on AppVeyor

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#37858]
In https://github.com/rust-lang/rust/pull/37817 I discovered that enabling rustbuild [fails to run 32-bit MSVC tests on AppVeyor](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.788/job/f6499tvr7jfmbim5). Specifically the run-make suite is failing with a bunch of errors like:

```
[02:33:05] C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe: error while loading shared libraries: mspdb140.dll: cannot open shared object file: No such file or directory
```

I know I've seen this before, just want to open an issue to track this. I think this is something like we're adding the wrong directory to `PATH` or we're forgetting a directory entirely.

**Comment by retep998** [comment]
The tools in `C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86` are cross tools from a host of amd64 to a target of x86. This means that the native host directory needs to be in `PATH` specifically `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64`.
