### ISSUE TITLE
Build failure on Mac OS X 10.11

### ISSUE THREAD

**Issue by g5pw** [rust-lang/rust#37852]
Rust 1.13 fails mid-build on mac OS X 10.11.6. It looks like it fails while linking `librustc_llvm-a4729905.dylib`.

I'm attaching the full build logs [here](https://gist.github.com/g5pw/32cd0c871ae46285c8d7750c2b0df40b), please ignore the macports-related stuff.

**Comment by alexcrichton** [comment]
This looks like C++ libraries are perhaps getting mixed up? I see that `-lstdc++` is getting passed with `librustc_llvm`, but LLVM was perhaps compiled with `-lc++`, causing all the link errors.

Looks like you're also using the makefiles as a build system which uses [this file](https://github.com/rust-lang/rust/blob/master/src/etc/mklldeps.py#L98-L110) to generate what libraries we're linking to with LLVM.

Do you have access to the build directory as well? If so, can you gist the contents of `x86_64-apple-darwin/rt/llvmdeps.rs`?

**Comment by g5pw** [comment]
Hmm... that's a good point, the thing is I didn't change anything in the portfile (this is about the MacPorts port of rust). Anyway, here is the file you asked: https://gist.github.com/g5pw/ed53c82737bb0e124f40ea421c473c78

**Comment by alexcrichton** [comment]
Are you perhaps linking against an external LLVM from MacPorts? Or is it the one that's included in the Rust repo? If it's an external one, can you gist the output of `llvm-config --cxxflags`?

**Comment by g5pw** [comment]
Although we don't explicitly set an external LLVM (we had plans for it, but it didn't compile at the time), it might get picked up by the build system perhaps? Here is the output of `llvm-config --cxxflags`:
```
% llvm-config --cxxflags
-I/opt/local/libexec/llvm-3.8/include -pipe -Os -std=c++11 -stdlib=libc++  -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -std=c++11 -DNDEBUG  -fno-exceptions -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
```

**Comment by alexcrichton** [comment]
Hm yeah if you don't specify it then it shouldn't get picked up automatically. You could try passing `--enable-rustbuild` perhaps which may be more reliable, but other than that I'm not sure what's going on :(

**Comment by g5pw** [comment]
I don't know if it helps, but the last version of rust that I successfully compiled on 10.11 was the 1.11.

**Comment by steveklabnik** [comment]
Triage: it's been a few years, and a *lot* has changed. @g5pw let me know if you're still seeing this today.
