### ISSUE TITLE
So strange term proc-derive

### ISSUE THREAD

**Issue by sackery** [rust-lang/rust#37869]

**Comment by durka** [comment]
Please elaborate.

**Comment by sackery** [comment]
which is the difference between derive and proc-derive?

**Comment by Stebalien** [comment]
I assume he's talking about `proc_macro_derive`.

**Comment by Stebalien** [comment]
However, @sackery, you should probably ask questions like that on https://users.rust-lang.org.

**Comment by keeperofdakeys** [comment]
@sackery https://users.rust-lang.org/t/macros-and-syntax-extensions-and-compiler-plugins-where-are-we-at/7600

**Comment by Aatch** [comment]
This doesn't seem like an issue for here, closing.
