### ISSUE TITLE
Include "length" in the documentation for Vec::len(), slice::len() etc.

### ISSUE THREAD

**Issue by mystor** [rust-lang/rust#37866]
This ensures that someone looking at the `Vec` documentation who searches for the word "length" to find the method which returns the length of the method will be able to find the method, and also explains the origin of the name if someone is unaware.

I bring this up because one of my coworkers came to me asking for the name of the method, because they were having trouble finding it in the documentation.

**Comment by steveklabnik** [comment]
The problem with this is that it's generally bad to include this in the summary, as it's just repeating what's already been said. So I didn't do this on purpose.

I'm not sure what exact text rustdoc searches though.... i'd be against putting this in the summary, but for putting it in the longer description

**Comment by ollie27** [comment]
We seem to be very inconsistent about what summaries to use for `len()` methods: https://doc.rust-lang.org/nightly/std/?search=len. Some say "length" and some say "number of elements". Perhaps changing them all to say something like "Returns the number of elements in / length of the slice." would help here.

**Comment by bluss** [comment]
It doesn't need to be in the summary(?), it can be in the body of the doc. [Searching for `length`](https://doc.rust-lang.org/nightly/std/index.html?search=length) already finds `slice::len` and `Vec::len` and so on, so the focus is simply in Ctrl+F search inside the doc page itself (if I understand correctly?).
