### ISSUE TITLE
rust-src tarballs are missing in recent nightlies

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#37878]
Like https://static.rust-lang.org/dist/2016-11-18/rustc-nightly-src.tar.gz

This [breaks pre-0.2.0 version of Xargo](https://travis-ci.org/japaric/cortex-m/jobs/177271748#L581). (Xargo 0.2+ uses the rust-src component; that works fine).

cc @brson

**Comment by alexcrichton** [comment]
Not sure what happened but today's tarball (https://static.rust-lang.org/dist/2016-11-19/rustc-nightly-src.tar.gz) exists

**Comment by japaric** [comment]
So I actually think this was caused by the sketchy logic that Xargo 0.1 uses to figure out the "build date" from the output `rustc -V` (it just adds one date to the date in that output) which is known to not always be correct.

Sorry for the noise.
