### ISSUE TITLE
Include file in the documentation

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/rust#37901]
It would be useful to be able a file in the documentation. My use-case is to include `examples/quickstart.rs` in the documentation of `lib.rs`. I could copy it, but it would be duplicated in the two files.

**Comment by euclio** [comment]
This would also be useful for including markdown documents in the source.  For example,

`#![doc(include = "README.md")]`

Could avoid duplication between the main library documentation and the project's README file.

**Comment by Yamakaky** [comment]
yes!

**Comment by steveklabnik** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/15470, thanks!

**Comment by gilescope** [comment]
For anyone that gets here from google the answer after following the trail is now:

`#![doc = include_str!("core_arch_docs.md")]`

 (see https://github.com/rust-lang/stdarch/pull/1013 )
