### ISSUE TITLE
Documentation phrase about panics in mpsc channel may be obsolete

### ISSUE THREAD

**Issue by vi** [rust-lang/rust#37915]
https://doc.rust-lang.org/std/sync/mpsc/fn.sync_channel.html#main

> As with asynchronous channels, all senders **will panic** in send if the Receiver has been destroyed.

https://doc.rust-lang.org/std/sync/mpsc/struct.SyncSender.html#send.v

> This function **will never panic**, but it may return Err if the Receiver has disconnected and is no longer able to receive information.

**Comment by Cobrand** [comment]
I will take care of this if no one minds
