### ISSUE TITLE
Matching on DerefMut prevents mutable borrow

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust#37949]
I've started using `Deref` and `DerefMut` more aggressively to make usage of my code more ergonomic. However, I then ran across a strange compiler error when trying to `match` on a value dereferenced through `DerefMut`. The issue illustrated by the following code.

```rust
use std::ops::{Deref, DerefMut};

enum X {
    A(usize),
    B,
}

struct Foo(X);

impl Deref for Foo {
    type Target = X;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl DerefMut for Foo {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}

struct Bar(Foo);

impl Bar {
    fn baz(&mut self) {
        match *self.0 {
            X::A(ref mut i) => { *i += 1; }
            X::B => { self.fail(); }
        }
    }

    fn fail(&mut self) {}
}

fn main() {
    Bar(Foo(X::A(0))).baz();
}
```

```console
$ rustc test.rs
error[E0499]: cannot borrow `*self` as mutable more than once at a time
  --> x.rs:34:17
   |
29 |         match *self.inner {
   |                ---------- first mutable borrow occurs here
...
34 |                 self.fail();
   |                 ^^^^ second mutable borrow occurs here
35 |             }
36 |         }
   |         - first borrow ends here
```

I have been unable to come up with a simpler test case. It is critical that there is another `match` arm that mutably borrows inside the matched value. Furthermore, `DerefMut` seems to be the culprit, as the following compiles fine:

```rust
enum X {
    A(usize),
    B,
}

struct Foo(X);
struct Bar(Foo);

impl Bar {
    fn baz(&mut self) {
        match (self.0).0 {
            X::A(ref mut i) => {
                *i += 1;
            }
            X::B => {
                self.fail();
            }
        }
    }

    fn fail(&mut self) {}
}

fn main() {
    Bar(Foo(X::A(0))).baz();
}
```

It could be that this is related to the lack of lexical scoping, though by my understanding the code above should work just fine without it (as illustrated by the non-`DerefMut` example code compiling just fine).

**Comment by bluss** [comment]
The borrow rules with deref mut are just the same as with other methods calls that take `&mut self`, the whole self is regarded as borrowed, instead of the finer grained tracking that's used for direct field access.

So it is expected, the problem is partly that those method calls (`.deref_mut()`) are invisible.

**Comment by jonhoo** [comment]
Ah, I see — in the `DerefMut` case, a reference is taken at the top of the `match` whose lifetime is the entire `match`, whereas in the second code example, a reference isn't really taken until `X::A(ref mut i)` matches? I do think the behavior here is counterintuitive though, as the two cases seem isomorphic? The current behavior also means that the only way (as far as I can tell) to express this `match` (if the fields of `Foo` are private) is
```rust
match *self.0 {
    X::A(ref mut i) => { *i += 1; }
    X::B => (),
}
if let X::B = *self.0 {
    self.fail();
}
```
It seems to me like the compiler has sufficient information to determine that the original construct is safe, but maybe it does in fact require lexical lifetimes? Is there perhaps a way we could improve the error message when `Deref` and `DerefMut` are used in `match` blocks?

**Comment by bluss** [comment]
It requires something else than lexical lifetimes, it requires seeing through the deref_mut method in a way that's not been proposed anywhere that I know.

**Comment by Mark-Simulacrum** [comment]
From what I can tell, this is not a bug -- or at least, is a side effect of current lifetime rules. As such, I'm going to close. It feels like this is something that is practically impossible to implement since it requires looking inside deref_mut.
