### ISSUE TITLE
If expressions not evaluated for constants

### ISSUE THREAD

**Issue by JinShil** [rust-lang/rust#37948]
This works fine:
```Rust
fn main() {
    let condition: bool = true;
    let result: u8 = if condition { 1 } else { 0 };
    println!("{}", result);
}
```

If assume, therefore, that this should work as well...
```Rust
const CONDITION: bool = true;
const RESULT: u8 = if CONDITION { 1 } else { 0 };

fn main() {
    println!("{}", RESULT);
}
```
...but it fails with
```
error[E0019]: constant contains unimplemented expression type
 --> <anon>:2:20
  |
2 | const RESULT: u8 = if CONDITION { 1 } else { 0 };
  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by Stebalien** [comment]
Your first example is evaluated at runtime, the second is evaluated at compile time. Rust doesn't currently support evaluating conditionals at compile time (support for calling functions is in the works but that doesn't cover conditionals).

**Comment by JinShil** [comment]
> Your first example is evaluated at runtime, the second is evaluated at compile time.

Just to clarify, I understand that one is evaluated at runtime, and the other at compile time.  The reason for submitting this issue is to point out the inconsistency.

**Comment by Stebalien** [comment]
@JinShil Got it. That kind of issue usually goes in the [rust-lang/rfcs](https://github.com/rust-lang/rfcs) repo (see https://github.com/rust-lang/rfcs/issues/322, specifically).

**Comment by est31** [comment]
miri will make this possible, and much more.

**Comment by steveklabnik** [comment]
Yes, @Stebalien is right here. Thanks @JinShil , but we should track this in the RFCs repo (and already are)
