### ISSUE TITLE
Tracking issue for ptr::{read,write}_unaligned

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#37955]
Tracking issue for https://github.com/rust-lang/rfcs/pull/1725

**Comment by chriskrycho** [comment]
Status check: it looks like this is implemented, behind a feature flag, and not-yet-documented?

**Comment by whitequark** [comment]
This has documentation now. What's the requirement for stabilization?

**Comment by alexcrichton** [comment]
Ah looks like this wasn't tagged B-unstable by accident which then fell under our radar. In that case...

@rfcbot fcp merge

**Comment by niconii** [comment]
The problem with `ptr::write`'s docs mentioned in #39733 is true of `ptr::write_unaligned`'s docs as well.

**Comment by whitequark** [comment]
@rfcbot calm down please
