### ISSUE TITLE
Need a mechanism to write rust-version-specific code

### ISSUE THREAD

**Issue by erickt** [rust-lang/rust#3795]
Since rust is still going through active development, it's hard to write a library that works for both rust-0.4 and rust-incoming. We need a cfg  `#[cfg(rust_version="0.5")]` to carve off chunks of code that have evolved in between versions.

If we want to get more fancy with these controls, I do have an old [semantic version parser](https://github.com/erickt/rust-semver) I wrote back in the 0.3 days. Maybe we could use something like that to let us write checks like:

```
#[cfg(rust_version=">=0.4-beta")]
#[cfg(rust_version="<=0.4")]
fn foo() { ... }

#[cfg(rust_version=">0.5")]
fn foo() { ... }
```

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#700
