### ISSUE TITLE
[Regression] test fails on 1.14.0-beta.2 (e627a2e6e 2016-11-16) with 'attempt to add with overflow'

### ISSUE THREAD

**Issue by zetok** [rust-lang/rust#37959]
Regressed from current and past stable (works on 1.13.0, 1.12.1) to current beta (1.14.0).

Error:

```
'attempt to add with overflow', ../src/libcore/ops.rs:263
```

Probably the code that beta handles wrongly: https://github.com/zetok/tox/commit/0885d7e2f14419f90b0daf172c7004331195a9c0#diff-47bd9ee511e98206d1a2d1ad0809b219R1427

Works on stable rustc 1.13.0 (2c6933acc 2016-11-07): https://travis-ci.org/zetok/tox/jobs/177605738#L960
Failed on beta rustc 1.14.0-beta.2 (e627a2e6e 2016-11-16): https://travis-ci.org/zetok/tox/jobs/177605739#L1137

**Comment by bluss** [comment]
This is intentional and it also was a regression that it stopped panicking (in 1.12 ?). It was fixed to not silently overflow in #36365

**Comment by arielb1** [comment]
Sure enough. Not a bug, but a fix to a regression introduced by MIR.
