### ISSUE TITLE
Redundant type specification in const definitions

### ISSUE THREAD

**Issue by JinShil** [rust-lang/rust#37950]
The following const expression appears unambiguous...
```Rust
struct BitField (u8, u8);

const BITFIELD = BitField(7, 0);   //  error: expected `:`, found `=`

fn main() { 
    println!("{}", BITFIELD.0);
}
```
...but to get it to compile, the type must be redundantly specified
```Rust
struct BitField (u8, u8);

const BITFIELD: BitField = BitField(7, 0);  // OK, but "BitField" is redundant

fn main() { 
    println!("{}", BITFIELD.0);
}
```

Fixing this seems in line with the [Rust 2017 Roadmap](https://internals.rust-lang.org/t/roadmap-2017-productivity-learning-curve-and-expressiveness/4097) item, _explicit types on statics and constants_

Interestingly, this works fine...
```Rust
struct BitField (u8, u8);

fn main() { 
    let bit_field = BitField(8, 0);   // No redundant type specification
    println!("{}", bit_field.0);
}
```
...so, the grammar appears inconsistent.

**Comment by sinkuu** [comment]
It seems like globals require explicit type signatures for the same reason as functions (which is by [design](https://www.rust-lang.org/en-US/faq.html#why-arent-function-signatures-inferred)). Anyway this problem is discussed in rfcs repo. https://github.com/rust-lang/rfcs/issues/1349

**Comment by est31** [comment]
I think it would be very bad if the type of a const would depend on where its used inside the crate (or even worse where its used outside of the crate).

**Comment by eddyb** [comment]
@est31 That's not their point, but rather that the initializer expression is already *fully typed*.

Unlike functions, global constants and statics have their values exposed, so the type being deduced wouldn't be too far of a stretch - it is, however, not possible to implement at the moment.

**Comment by est31** [comment]
@eddyb allowing they types of constants to be derived when the initializer expression is fully typed would still mean that there is an "inconsistency" to what let does. I agree that in this particular example it is silly to have to specify the type though.

**Comment by steveklabnik** [comment]
Yes, this is being tracked by https://github.com/rust-lang/rfcs/issues/1349. Thanks @JinShil !
