### ISSUE TITLE
There needs to be an EnumMap to go with EnumSet

### ISSUE THREAD

**Issue by icefoxen** [rust-lang/rust#37964]
Basically to mimic the use case of "I want to index an array with an enum".

(In other news it seems like the CLike trait should be able to be auto-derived for enums that don't have any member values, or which have member values that all implement CLike.)

**Comment by sfackler** [comment]
I believe this should be filed against the rust-lang/rfcs repo rather than here.

"need" is also a strong word :P

**Comment by icefoxen** [comment]
Well, *I* would sure like it, so obviously it's needed!  But seriously, it seems like it would make sense and jibe with the other std::collections types.

Should I shift this request over to rust-lang/rfcs ?

**Comment by sfackler** [comment]
Yep

**Comment by icefoxen** [comment]
Shuffled off into https://github.com/rust-lang/rfcs/issues/1798 , sorry for the noise.  :smile:
