### ISSUE TITLE
Beta cargo version needs to change

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#37969]
Don't know a better place to file this where we can track it, so filing here. 

Right now the Cargo tied to 1.14 beta suffers from https://github.com/rust-lang/cargo/issues/3303, which we need to fix. This regression in required libraries was introduced by https://github.com/rust-lang/cargo/pull/3272 and was later fixed by https://github.com/rust-lang/cargo/pull/3311 and https://github.com/rust-lang/cargo/pull/3315.

Beta's Cargo date is 2016-11-16, corresponding to rust-lang/cargo@a9c23dd and includes rust-lang/cargo#3272. The previous nightly, 2016-11-15, corresponds to rust-lang/cargo@9f1beaf which also includes rust-lang/cargo#3272. The previous *successful* nightly was 2016-11-09 which corresponds to rust-lang/cargo@5b5684e. Unfortunately that nightly does not contain https://github.com/rust-lang/cargo/pull/3280 which is required for beta to bootstrap with rustbuild.

So we've got a few options:

* Fast forward the Cargo nightly by a few weeks. We'd have to fixup version numbers with new commits.
* Start release branches of Cargo *now* with the support from https://github.com/rust-lang/cargo/pull/3239
* Prepare a custom branch of Cargo and upload a new nightly for some previous date manually (somehow).

My preference is to go with https://github.com/rust-lang/cargo/pull/3239. @brson what do you think?

**Comment by steveklabnik** [comment]
I like that option too.

**Comment by brson** [comment]
I don't understand what "Start release branches of Cargo now with the support from rust-lang/cargo#3239" means. What are release branches in this context and how does that solve the problem?

**Comment by brson** [comment]
I think you are saying create a new branch named "stable" (or something), based off some older commit, have it upload to s3, then backport whatever fixes we need. Then update rust-packaging to source cargo from those uploads instead of the nightlies.

That sounds fine to me. I think we do need a release branch for cargo that we can backport to.

**Comment by brson** [comment]
If you do that, can you make Cargo not build with `-nightly` in the version name on the stable branch?

**Comment by alexcrichton** [comment]
@brson oh yes sorry I mean creating `stable` and `beta` branches of Cargo, and then building binaries from there instead of just on nightly. That'd allow us to easily backport fixes to beta without having to fast-forward beta.

Also yeah I think we could fix the `-nightly` thing at the same time.

**Comment by alexcrichton** [comment]
I've opened https://github.com/rust-lang/cargo/pull/3345 to explore release branches on Cargo.

**Comment by alexcrichton** [comment]
https://github.com/rust-lang/cargo/pull/3353 is the first batch of backports for the Cargo associated with Rust 1.14.0

**Comment by alexcrichton** [comment]
Next beta build will have a fixed Cargo, closing.
