### ISSUE TITLE
Tracking issue for EnumSet

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#37966]

**Comment by frewsxcv** [comment]
For reference:

* https://doc.rust-lang.org/collections/enum_set/struct.EnumSet.html
* https://github.com/rust-lang/rust/blob/master/src/libcollections/enum_set.rs

**Comment by Stebalien** [comment]
The unstable notice says "matches collection reform specification, waiting for dust to settle" however, isn't it supposed to be replaced by https://github.com/contain-rs/enum-set (formally collect-rs)?

**Comment by sfackler** [comment]
That notice was bulk-applied to roughly everything in libcollections in the lead up to 1.0, so I wouldn't take it too literally. I think I'd like to just deprecate and remove this thing since it's been sitting around unnoticed for a year and a half.

**Comment by sfackler** [comment]
@rfcbot fcp close

This has been sitting around unnoticed in libcollections for a long time.

**Comment by cuviper** [comment]
What's the policy for actually removing this?

**Comment by alexcrichton** [comment]
After a full cycle of deprecation on nightly we can remove at any time through a PR. @cuviper would you be interested in sending such a PR? (you can also clean out other deprecated + unstable pieces!)

**Comment by cuviper** [comment]
Sure, I'll do a sweep.
