### ISSUE TITLE
Temporary Variable

### ISSUE THREAD

**Issue by sunjay** [rust-lang/rust#37970]
I don't know if this qualifies as a bug, but it is certainly very inconvenient. The problem is that if I run two operations on a value, the temporary value doesn't last long enough for me to perform the second operation.

I get an error like this:

```
error: borrowed value does not live long enough
  --> <anon>:8:40
   |
8  |         let line = line.unwrap().trim();
   |                    -------------       ^ temporary value dropped here while still borrowed
   |                    |
   |                    temporary value created here
9  |         println!("{}", line);
10 |     }
   |     - temporary value needs to live until here
   |
   = note: consider using a `let` binding to increase its lifetime

error: aborting due to previous error
```

With this code: (Play Rust: https://is.gd/p8nh7V)

```rust
use std::io;
use std::io::BufRead;


fn main() {
    let stdin = io::stdin();
    for line in stdin.lock().lines() {
        let line = line.unwrap().trim();
        println!("{}", line);
    }
}
```

This happens in both stable and nightly, but when I ran into it I had this version of nightly:

```
$ rustc --version --verbose
rustc 1.15.0-nightly (0bd2ce62b 2016-11-19)
binary: rustc
commit-hash: 0bd2ce62b27e2b9a7dfe92fc23d9098854008089
commit-date: 2016-11-19
host: x86_64-unknown-linux-gnu
release: 1.15.0-nightly
LLVM version: 3.9
```

I can fix it by breaking the statement into two lines like the error message directs me to: (Play Rust: https://is.gd/YMJ2yI)

```rust
use std::io;
use std::io::BufRead;


fn main() {
    let stdin = io::stdin();
    for line in stdin.lock().lines() {
        let line = line.unwrap();
        let line = line.trim();
        println!("{}", line);
    }
}
```

This seems unnecessarily messy though. Isn't there some way to preserve the unwrapped value and apply trim in the same statement?

**Comment by steveklabnik** [comment]
This isn't a bug.

> This seems unnecessarily messy though.

So, here's what happens: 

    let line = line.unwrap().trim();
                                     ^

Here, a temporary value is created by `unwrap()`. Specifically, it's a `String`, which means it has ownership over its contents. This means that when it goes out of scope, its memory will be freed.

    let line = line.unwrap().trim();
                                              ^

Here, we take that `String` and call `trim()` on it. `trim()` returns an `&str`, that is, a non-owning reference to the data in that String.

Finally, the line ends. Our temporary `String` is out of scope, so its memory gets freed. But, the `&str` we created with `trim()` is still referring to it; so it's a dangling pointer, pointing to invalid memory.

    let line = line.unwrap()
    let line = line.trim();

With this code, `unwrap()` still gives us a `String`, but it's no longer temporary. This means it's going to live until the end of the block, which in this case is the `for` loop. Then, we call `trim()` on it, which gives us the `&str`. But this time, it's not a temporary: it lives until the end of the loop. So does the `&str`. So this is fine.

This sort of "a reference keeps its referent alive" is bread and butter for GCs, but Rust doesn't have a GC. So this is just a quirk of how things work. I hope this helps!

**Comment by sunjay** [comment]
@steveklabnik Thanks for clarifying! That makes sense. 

Big fan of yours. :)
