### ISSUE TITLE
Decrease HashMap Load Factor

### ISSUE THREAD

**Issue by pssalmeida** [rust-lang/rust#38003]
Currently HashMap uses a load factor of approximately 0.9. While this is appropriate for reads (get), as Robin Hood Hashing gives a low distance from the starting point with very low, effectively fixed variance, such is not the case for writes (insert).

When writing over an occupied bucked, it will incur a displacement involving reads and writes over several buckets, either for the new value or the values already in the map. Not only this number is larger than for reads, but also has an increasing variance, quickly becoming very large as load approaches 1.

For a load factor *a*:  (**UPDATED**, previous lookup values were for random probing)

* the average number of probes in a read is ~~1/a*ln(1/1-a))~~ (1+1/(1-a))/2
* the average number of written buckets in a write is 1/(1-a)
* the probability of writing no more than *k* buckets in a write is 1 - a^k

In a table, the average buckets written, the 95th percentile buckets written, and the average buckets probed in a get, for different load factors:

a | Avg W | 95% W | Avg R
--- | ------ | ------- | ------
0.500 | 2 | 4.3 | ~~1.39~~ 1.5
0.666 | 3 | 7.4 | ~~1.65~~ 2.0
0.750 | 4 | 10.4 | ~~1.84~~ 2.5
0.800 | 5 | 13.4 | ~~2.01~~ 3.0
0.833 | 6 | 16.4 | ~~2.15~~ 3.5
0.857 | 7 | 19.4 | ~~2.27~~ 4.0
0.875 | 8 | 22.4 | ~~2.38~~ 4.5
0.888 | 9 | 25.4 | ~~2.47~~ 5.0
0.900 | 10 | 28.4 | ~~2.56~~ 5.5
0.950 | 20 | 58.4 | ~~3.15~~ 10.5
0.990 | 100 | 298.1 | ~~4.65~~ 50.5

It can be seen that for *a* = 0.9, the average probes when reading is just ~~2.56~~ 5.5, but the average number of buckets written when inserting is 10 and the 95th percentile is 28 buckets. For deletes it will not be much better when doing the backwards shift, as most keys will be displaced from their origin (the very low variance behaviour or RH).

While for many cases, the average over the map lifetime may not be much impacted, if it happens that a map is being operated near capacity, with elements constantly being inserted and others removed, e.g., when implementing an LRU cache, the number of buckets (re)written per insert (and also per delete) will be manifestly higher than desired.

While the exact load factor choice can be argued about, it seems that 0.9 is manifestly too high. Going from 0.9 to 0.8 would have a 12.5% memory overhead, while going from 0.8 to 0.9 doubles the average number of buckets written when inserting, and more than doubles the 95th percentile. Therefore, a load factor around 0.8 seems more reasonable.

**Comment by sfackler** [comment]
Concrete performance numbers for various load factors would probably be helpful.

**Comment by abonander** [comment]
Honestly, why isn't the load factor configurable to begin with? That would make it quite a bit easier to tune for specific use cases.

**Comment by arthurprs** [comment]
I was going to propose 0.833 (5/6) based on some tests I ran earlier, but we need more numbers to take an informed decision.

**Comment by funny-falcon** [comment]
Looks like 0.8 gives 20% improvement on read (ok, number of buckets readed is not directly transfers to performance, but still).

**Comment by pczarn** [comment]
I don't know the distribution for the number of buckets accessed by insertion, but here are more accurate numbers for lookup.

| a     | 50% R | 90% R | 95% R |
|-------|-------|-------|-------|
| 0.8   | 1.8   | 5.5   | 7.0   |
| 0.833 | 2.1   | 6.7   | 8.7   |
| 0.9   | 3.5   | 10.9  | 14.5  |

![lookup_cost_with_circles2](https://cloud.githubusercontent.com/assets/3356767/20650027/3bb14022-b4cd-11e6-9de7-4b5fd8038c11.png)

**Comment by funny-falcon** [comment]
So, 0.8 compared to 0.833 consumes 5% more memory and provides 15-20% more performance.

**Comment by arthurprs** [comment]
@funny-falcon how did you come up with these numbers?

**Comment by pssalmeida** [comment]
@abonander I also found surprising not being able to choose load factor, something that would be a good idea. Anyway, the question about what the sensible default should be remains.

@pczarn I find strange such long tails for lookup distribution ... I had the impression the variance would be much less. Also the shape does not look right. For high load factor it should start by a gentle slope and have a steep slope near the average.

Anyway, lookups are not the problem, as we are talking about 1 cache line most times, sometimes 2, rarely more than 2. I would also point out that for inserts, the cost is "amplified" by the payload size. We are not talking about only traversing hashes. An average of 10 means, in addition to the hashes, displacing 10 times the size of key and value. This makes such large numbers even more scary.

**Comment by funny-falcon** [comment]
@arthurprs only with mathematics and numbers from a table above. (Not, I've edited my comment: 15-20% less collision chain, not performance. Cause of great cache locality of Robin-Hood hashing, performance difference will be usually lesser).

For used space:
- 0.833 fill rate means one need 1/0.833=1.2 space, or 20% excess space.
- 0.8 fill rate means one need 1/0.8=1.25 space, or 25% excess space.
- 1.25/1.2 = 1.042, so it means, 0.8 fill rate uses 4.2% more space (in average) than 0.833 fill rate.

**Comment by matklad** [comment]
@pssalmeida are those back of an envelope calculations? They feel a bit odd to me, because they say that the average probe count for reading at 0.9 load factor should be 2.56. I've [recently measured](https://github.com/matklad/RobinHood) plain linear probing and robin hood hashing and I get 5.48 as the average probe length (for the elements which are in the table). Perhaps my measurements are wrong, but it still might be a good idea to instrument and measure the current implementation, as suggested by @sfackler .

**Comment by arthurprs** [comment]
@matklad I was checking your test-repo, I can't wrap my head around the timing/cache results. It should take less time and put less pressure on the cache, it makes no sense to me whatsoever.

**Comment by matklad** [comment]
@arthurprs this puzzles me as well! I want to plot the actual distribution of probe lengths and to run some specific tests about cache access (basically execute queries like "sum of the elements from i to k + i" with different distributions of `k`). But at least [the paper](https://infosys.cs.uni-saarland.de/publications/p249-richter.pdf) you've linked to from another issues seems to imply that RH is not automatically better than plain LP?

>We can conclude that RH provides a very interesting trade-off: for a small penalty (often within 1-5%) in peak performance on the best of cases (all lookups successful), RH significantly improves on the worst-case over LP in general, up to more than a factor 4.

**Comment by funny-falcon** [comment]
Possible solve of a puzzle:
- lesser variance not only means there is less number of long chains, but it could also mean there is less number of short chains.
- longer chain have more impact on mean value,
- So, given mean value of all chains is same, we have RH hashing has "larger mean of small chains".
- in other words: while RH has better "worst time" for single lookup, it has worse "average time".

And it is clear result of its algorithm: it prefers to make short chains longer to cut probability of "too long chain".

I think, if you compare "Distribution of number of buckets" between Linear hashing and RH hashing (as @pczarn did above for RH), it will describe your timing and cache misses.

**Comment by arthurprs** [comment]
That's it @funny-falcon. It's probably worth pointing out that the hash algorithm is "~perfect" and there's no deletions involved, so that's the best case for LP.

RH LP
```
25'th percentile is 2
50'th percentile is 4
85'th percentile is 10
90'th percentile is 12
95'th percentile is 15
99'th percentile is 23
100'th percentile is 56
```

LP
```
25'th percentile is 1
50'th percentile is 1
85'th percentile is 6
90'th percentile is 10
95'th percentile is 21
99'th percentile is 75
100'th percentile is 1271```

**Comment by pssalmeida** [comment]
@matklad I made a mistake. I was using the results from https://arxiv.org/abs/1605.04031, which I had just skimmed, but now I noticed that they discuss random probing. Meanwhile I found this talk https://www.ime.usp.br/~yoshi/FoCM2014/talks/viola.pdf, which states that the mean is (1 + 1/(1-a))/2, which gives exactly your experimental results!

So, the results are worse, even for lookups, which is another reason to decrease the load factor.

**Comment by pssalmeida** [comment]
Updated table with new formula for average number of buckets in lookup, for linear probing.

**Comment by sfackler** [comment]
Again, I care far more about actual timings of real operations rather than probe counts.

**Comment by arthurprs** [comment]
@pssalmeida Let me know if you'd like me to run numbers. I'm running HM benchmarks extensively during the last couple of months.

**Comment by pssalmeida** [comment]
@sfackler sure. If someone who has been already doing such measurements on HashMap could volunteer it would be nice. The experiments by @matklad already show that timing and cache misses can increase over a simple linear probing.

Intuitively, for simple LP, most hashes will have smaller distances to origin than RH LP, and will incur a single cache line read. So, even if some are farther, as long as they remain in a second cache line, it won't matter much if they are farther away, and only rarely a third cache line will be visited.

For RH LP, most hashes will have a distance to origin closer to the mean. If that is not very small, a non-negligible number of lookups may incur a second cache line read, giving worse results.

**Comment by pssalmeida** [comment]
@arthurprs If you could run some tests it would be great. An interesting case would be doing lots of insert-delete cycles in a full loaded to capacity table.

**Comment by arthurprs** [comment]
Some initial tests, source https://gist.github.com/arthurprs/97dabb2c28f8d778dc377d69d0b95758

```
➜  hashmap2 git:(load_factor) ✗ cargo-benchcmp _91:: _86:: bench.txt 
 name                    _91:: ns/iter  _86:: ns/iter  diff ns/iter   diff % 
 grow_100_000            9,898,568      8,205,605        -1,692,963  -17.10% 
 grow_10_000             739,400        606,523            -132,877  -17.97% 
 grow_big_value_100_000  18,947,340     15,886,857       -3,060,483  -16.15% 
 grow_big_value_10_000   1,696,487      1,520,755          -175,732  -10.36% 
 lru_sim                 61,511,142     25,931,731      -35,579,411  -57.84% 
➜  hashmap2 git:(load_factor) ✗ cargo-benchcmp _91:: _83:: bench.txt
 name                    _91:: ns/iter  _83:: ns/iter  diff ns/iter   diff % 
 grow_100_000            9,898,568      7,945,712        -1,952,856  -19.73% 
 grow_10_000             739,400        533,345            -206,055  -27.87% 
 grow_big_value_100_000  18,947,340     14,991,283       -3,956,057  -20.88% 
 grow_big_value_10_000   1,696,487      1,407,438          -289,049  -17.04% 
 lru_sim                 61,511,142     20,724,928      -40,786,214  -66.31% 
➜  hashmap2 git:(load_factor) ✗ cargo-benchcmp _91:: _80:: bench.txt
 name                    _91:: ns/iter  _80:: ns/iter  diff ns/iter   diff % 
 grow_100_000            9,898,568      7,863,597        -2,034,971  -20.56% 
 grow_10_000             739,400        532,390            -207,010  -28.00% 
 grow_big_value_100_000  18,947,340     14,441,190       -4,506,150  -23.78% 
 grow_big_value_10_000   1,696,487      1,371,787          -324,700  -19.14% 
 lru_sim                 61,511,142     16,784,123      -44,727,019  -72.71% 
```

**Comment by brson** [comment]
Numbers look good to me.

**Comment by sfackler** [comment]
@abonander One potential concern there is that the load factor you'd select is somewhat tied to the implementation. If we significantly changed HashMap's internals (as we're probably going to do to resolve the n^2 thing), the load factor someone's selected may all of the sudden be unacceptably slow.

**Comment by abonander** [comment]
@sfackler Then it may be better to abstract the load factor behind an enum that just lets them select a load factor that produces the desired effect from the implementation, maybe like the following:

```rust
pub enum LoadFactor {
    OptimizeLookup,
    OptimizeInsert,
    SaveMemory,
    Balanced
}
```

**Comment by arthurprs** [comment]
The fill factor isn't guaranteed or exposed directly by the api, so It shouldn't be a problem. A api for exposing/changing load factor will likely need an rfc.

**Comment by arthurprs** [comment]
Complete results now, code is here https://gist.github.com/arthurprs/97dabb2c28f8d778dc377d69d0b95758

It's really important to emphasize that **only the grow benchmark is realistic**, the others simulate the worst case performance of each load factor.

```
➜  hashmap2 git:(load_factor) ✗ cargo benchcmp _91:: _80:: bench2.txt
 name                    _91:: ns/iter  _80:: ns/iter  diff ns/iter   diff % 
 grow_100_000            9,898,568      7,863,597        -2,034,971  -20.56% 
 grow_10_000             739,400        532,390            -207,010  -28.00% 
 grow_big_value_100_000  18,947,340     14,441,190       -4,506,150  -23.78% 
 grow_big_value_10_000   1,696,487      1,371,787          -324,700  -19.14% 
 lookup_100_000          198,619        176,341             -22,278  -11.22% 
 lookup_100_000_unif     239,906        210,472             -29,434  -12.27% 
 lookup_1_000_000        255,092        209,030             -46,062  -18.06% 
 lookup_1_000_000_unif   716,114        591,138            -124,976  -17.45% 
 lru_sim                 61,511,142     16,784,123      -44,727,019  -72.71% 
```
```
➜  hashmap2 git:(load_factor) ✗ cargo benchcmp _91:: _83:: bench2.txt
 name                    _91:: ns/iter  _83:: ns/iter  diff ns/iter   diff % 
 grow_100_000            9,898,568      7,945,712        -1,952,856  -19.73% 
 grow_10_000             739,400        533,345            -206,055  -27.87% 
 grow_big_value_100_000  18,947,340     14,991,283       -3,956,057  -20.88% 
 grow_big_value_10_000   1,696,487      1,407,438          -289,049  -17.04% 
 lookup_100_000          198,619        180,257             -18,362   -9.24% 
 lookup_100_000_unif     239,906        220,410             -19,496   -8.13% 
 lookup_1_000_000        255,092        222,065             -33,027  -12.95% 
 lookup_1_000_000_unif   716,114        608,441            -107,673  -15.04% 
 lru_sim                 61,511,142     20,724,928      -40,786,214  -66.31% 
```
```
➜  hashmap2 git:(load_factor) ✗ cargo benchcmp _91:: _86:: bench2.txt
 name                    _91:: ns/iter  _86:: ns/iter  diff ns/iter   diff % 
 grow_100_000            9,898,568      8,205,605        -1,692,963  -17.10% 
 grow_10_000             739,400        606,523            -132,877  -17.97% 
 grow_big_value_100_000  18,947,340     15,886,857       -3,060,483  -16.15% 
 grow_big_value_10_000   1,696,487      1,520,755          -175,732  -10.36% 
 lookup_100_000          198,619        185,793             -12,826   -6.46% 
 lookup_100_000_unif     239,906        226,298             -13,608   -5.67% 
 lookup_1_000_000        255,092        229,754             -25,338   -9.93% 
 lookup_1_000_000_unif   716,114        636,031             -80,083  -11.18% 
 lru_sim                 61,511,142     25,931,731      -35,579,411  -57.84%
```

**Comment by pssalmeida** [comment]
@arthurprs Thanks for the benchmarks. The lru_sim, even if not realistic shows an impressive difference, but even the others show that there is considerable impact going from 0.91 to lower load factors.

**Comment by arthurprs** [comment]
Going over some issues I noticed that people subscribed to this might also be interested on https://github.com/rust-lang/rust/pull/38368

**Comment by arthurprs** [comment]
Now that #40561 is in this is the only remaining place I think can think of that we can extract nice gains (at least without a major rewrite).

With the updated code above I conducted several benchmarks with various load factors: 0.909 (today), 0.875, 0.857, 0.833 and 0.8;
The results can be seen in the gist https://gist.github.com/arthurprs/0b0ad2d7cf66195de50e6681d6bd2470

The current implementation is reasonably compact, so it wouldn't be unreasonable to set it down to 0.80, as that's still high (the highest?) compared to most stdlibs.

**Comment by arthurprs** [comment]
I found out that the lookup benchs are broken so ignore those, the others are ok though. I will do another round of tests soon.

**Comment by arthurprs** [comment]
Ok, I found some time today and here are the final results.

Tested load factors: 91% (90.09 actually), 87.5%, 85.7%, 83.3% and 80%.

```
➜  hashmap2 git:(adapt) ✗ cargo benchcmp s91_ s875_ bench.txt
 name                           s91_ ns/iter  s875_ ns/iter  diff ns/iter   diff % 
 ::grow_10_000                  725,027       625,813             -99,214  -13.68% 
 ::grow_big_value_10_000        1,549,729     1,370,511          -179,218  -11.56% 
 ::insert_10_000                280,410       282,352               1,942    0.69% 
 ::insert_int_big_value_10_000  388,196       388,781                 585    0.15% 
 ::insert_str_10_000            278,460       282,036               3,576    1.28% 
 ::lookup_100_000               346,780       346,505                -275   -0.08% 
 ::lookup_100_000_unif          347,420       352,619               5,199    1.50% 
 ::lru_sim                      16,725,522    13,357,712       -3,367,810  -20.14% 
 ::merge_shuffle                1,061,281     970,339             -90,942   -8.57% 
➜  hashmap2 git:(adapt) ✗ cargo benchcmp s91_ s857_ bench.txt
 name                           s91_ ns/iter  s857_ ns/iter  diff ns/iter   diff % 
 ::grow_10_000                  725,027       590,630            -134,397  -18.54% 
 ::grow_big_value_10_000        1,549,729     1,335,661          -214,068  -13.81% 
 ::insert_10_000                280,410       283,628               3,218    1.15% 
 ::insert_int_big_value_10_000  388,196       391,228               3,032    0.78% 
 ::insert_str_10_000            278,460       278,091                -369   -0.13% 
 ::lookup_100_000               346,780       345,877                -903   -0.26% 
 ::lookup_100_000_unif          347,420       345,124              -2,296   -0.66% 
 ::lru_sim                      16,725,522    12,186,222       -4,539,300  -27.14% 
 ::merge_shuffle                1,061,281     938,625            -122,656  -11.56% 
➜  hashmap2 git:(adapt) ✗ cargo benchcmp s91_ s833_ bench.txt
 name                           s91_ ns/iter  s833_ ns/iter  diff ns/iter   diff % 
 ::grow_10_000                  725,027       556,504            -168,523  -23.24% 
 ::grow_big_value_10_000        1,549,729     1,303,685          -246,044  -15.88% 
 ::insert_10_000                280,410       281,040                 630    0.22% 
 ::insert_int_big_value_10_000  388,196       384,993              -3,203   -0.83% 
 ::insert_str_10_000            278,460       274,348              -4,112   -1.48% 
 ::lookup_100_000               346,780       348,764               1,984    0.57% 
 ::lookup_100_000_unif          347,420       345,968              -1,452   -0.42% 
 ::lru_sim                      16,725,522    10,869,297       -5,856,225  -35.01% 
 ::merge_shuffle                1,061,281     899,307            -161,974  -15.26% 
➜  hashmap2 git:(adapt) ✗ cargo benchcmp s91_ s80_ bench.txt                   
 name                           s91_ ns/iter  s80_ ns/iter  diff ns/iter   diff % 
 ::grow_10_000                  725,027       519,754           -205,273  -28.31% 
 ::grow_big_value_10_000        1,549,729     1,208,050         -341,679  -22.05% 
 ::insert_10_000                280,410       280,800                390    0.14% 
 ::insert_int_big_value_10_000  388,196       382,706             -5,490   -1.41% 
 ::insert_str_10_000            278,460       273,270             -5,190   -1.86% 
 ::lookup_100_000               346,780       343,537             -3,243   -0.94% 
 ::lookup_100_000_unif          347,420       342,172             -5,248   -1.51% 
 ::lru_sim                      16,725,522    9,648,139       -7,077,383  -42.31% 
 ::merge_shuffle                1,061,281     880,150           -181,131  -17.07%
```

**Comment by arthurprs** [comment]
And some extra worst case tests, where constants are set to 95% of .capacity() after creation with with_capacity(X) https://gist.github.com/arthurprs/ae084a0c5a119ddd732d93eb6fd31d05

**Comment by arthurprs** [comment]
This may not be as significant with the new hashmap (hashbrown) implementation. @Amanieu might want to add his thoughts here.

**Comment by Amanieu** [comment]
The main concern here was that the high load factor would cause many entries to be moved during an insertion. Since the new hash table implementation does not move existing entries on insert, I think this can be closed.
