### ISSUE TITLE
Default type parameters are not in the language reference

### ISSUE THREAD

**Issue by diwic** [rust-lang/rust#38011]
Default type parameters (e g `struct Foo<A = u32>(A)`) is a language feature, but they are not mentioned in the [language reference](https://doc.rust-lang.org/reference.html#type-parameters).

It would be nice if such a reference also mentioned the tricky semantics around how it interacts with inference, as [mentioned here](https://github.com/rust-lang/rust/issues/36980#issuecomment-251726254).

**Comment by bluss** [comment]
Type parameter defaults are syntactical at the moment and don't really interact with inference.

The linked issue is basically that given `Test::<>::default()` I expected that to be equivalent to `<Test<>>::default()` but it is equivalent to `<Test<_, _>>::default()`

**Comment by diwic** [comment]
Maybe it's a bit poorly phrased, what I meant was something like, if you change `Test::<u32>` to `Test::<u32,_>`, then you disable default type parameters and enable inference (?). And to enable default type parameters in the first place you need either the `<Test>` syntax (which I hadn't seen before today), or `Test::<_>`, but the latter is impossible to use for the first default type parameter (given the linked issue).

All this might be a poor layman's explanation, which is the reason I filed the bug in the hope of getting a better one :-)

Side note: What would have been more intuitive to me, would be an algorithm like:

 1) If the type parameter is explicitly mentioned (i e `Test<u32, &str>`), use that
 2) else if inference can find out the correct type, use that
 3) else if there is a default type parameter, use that
 4) else give a compiler error.

...i e, that they would interact more than they do today. But that's a bigger question (and one the might be hard to do in a backwards compatible fashion, I don't know).

**Comment by steveklabnik** [comment]
The reference lives in its own repository now, I've moved it to https://github.com/rust-lang-nursery/reference/issues/24

Thanks!
