### ISSUE TITLE
bootstrap rustNightly from rustBeta never works with the 'correct' channels

### ISSUE THREAD

**Issue by qknight** [rust-lang/rust#38026]
# what we want
hey,
on NixOS we want to have `stable`, `beta` and `nightly` built as according to the docs of rust but we tried many different versions and it always fails with errors like this:

https://gist.github.com/qknight/15550e3b24b8a503897ac92fffe88804

or in short:
```
error[E0554]: #[feature] may not be used on the beta release channel
  --> src/libcore/lib.rs:93:1
   |
93 | #![feature(never_type)]
   | ^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #[feature] may not be used on the beta release channel
  --> src/libcore/lib.rs:94:1
   |
94 | #![feature(prelude_import)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 25 previous errors

```

that said have a look at these files:
https://github.com/nixcloud/nixpkgs/blob/experimentalUpdate/pkgs/development/compilers/rust/default.nix
https://github.com/nixcloud/nixpkgs/blob/experimentalUpdate/pkgs/development/compilers/rust/beta.nix
https://github.com/nixcloud/nixpkgs/blob/experimentalUpdate/pkgs/development/compilers/rust/nightly.nix

we use these channels:

* "--release-channel=stable" to build `stable`
* "--release-channel=beta" to build `beta` from `stable`
* "--release-channel=nightly" to build `nightly` from `beta`

and then it fails.

if we do this:
* "--release-channel=nightly" for building `stable`, `beta` and `nightly` we don't see the `channel` errors listed above.

what is going wrong here?

**Comment by the-kenny** [comment]
(I've seen this before and the following is my recollection, so it might not be completely correct) 

This happens when there's a mismatch between the version used to bootstrap the compiler and what the compiler being bootstrapped expects. The current build system uses a secret to enable unstable features for stable compilers. 

For a given compiler to bootstrap correctly you need to bootstrap it with the versions/snapshots specified in https://github.com/rust-lang/rust/blob/master/src/stage0.txt in the source tree of the compiler being built.

**Comment by the-kenny** [comment]
Also note that it *could* be related to https://github.com/rust-lang/rust/issues/34722 - but that would be a rather fringe case (and I added a big fat warning to our build code to *not* use `wrapProgram`).

My bet is on the beta/stage0.txt mismatch.

**Comment by qknight** [comment]
@alexcrichton do you have an idea?

**Comment by the-kenny** [comment]
@qknight Did you try my suggestion above? I'm pretty sure it's related to the (likely) usage of incompatible versions used for bootstrapping.

**Comment by nagisa** [comment]
Relevant recent changes to bootstrap key logic: https://github.com/rust-lang/rust/pull/37265 https://github.com/rust-lang/rust/pull/37566

**Comment by the-kenny** [comment]
@nagisa Thanks for the pointers! :) I just enabled this proactively in our tree in https://github.com/NixOS/nixpkgs/commit/bfc187f23a80a02135b2d76fb1e92adc7d5759ce

@qknight Can you rebase/merge current master into your branch and give it a try? It should be fine now if `rustc` really picks up the env var :)

**Comment by qknight** [comment]
@the-kenny i will play with your advice in a bit, thanks very much!

for now i plan to include this commit into nixpkgs: 

* https://github.com/nixcloud/nixpkgs/commit/d695f11c10162133b363741e3d117862a3280c38

why is this cool? this expression downloads a `nightly` rustc (no cargo) and totally bypasses hydra! this way everyone might be happy. installation in less time than a 100 mb download ;-)

**Comment by the-kenny** [comment]
+1 from my side, but other people's opinion might differ. Please note
that there's also a (dev-only, not for nixpkgs) expression that fetches
*todays* nightly every time it's run. Great for development :) 

Shall we move this discussion over to nixpkgs?

Joachim Schiele <notifications@github.com> writes:

> @the-kenny i will play with your advice in a bit, thanks very much!
>
> for now i plan to include this commit into nixpkgs: 
>
> * https://github.com/nixcloud/nixpkgs/commit/d695f11c10162133b363741e3d117862a3280c38
>
> why is this cool? this expression downloads a `nightly` rustc (no cargo) and totally bypasses hydra! this way everyone might be happy. installation in less time than a 100 mb download ;-)
>
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/rust-lang/rust/issues/38026#issuecomment-263252310

--

**Comment by alexcrichton** [comment]
Was the bootstrap logic resolved here as well? Is this closed now?

**Comment by qknight** [comment]
thanks a lot everyone! this bug-hunt was amazing!
