### ISSUE TITLE
[rustbuild] x.py build --stage 1 src/rustc --host=$HOST errors

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#38037]
with:

(In this example: `BUILD = x86_64-unknown-linux-gnu` and `HOST = arm-unknown-linux-gnueabi`)

```
Building stage0 std artifacts (x86_64-unknown-linux-gnu -> arm-unknown-linux-gnueabi)
(..)
Building stage0 test artifacts (x86_64-unknown-linux-gnu -> arm-unknown-linux-gnueabi)
(..)
Building LLVM for arm-unknown-linux-gnueabi
(..)
ninja: error: '/home/japaric/build/x86_64-unknown-linux-gnu/llvm/bin/llvm-tblgen', needed by 'include/llvm/IR/Attributes.inc.tmp', missing and no known rule to make it
```

when configured with `configure --enable-rustbuild --host=$HOST` or with `configure --enable-rustbuild --host=$HOST --llvm-root=/usr`.

I think this is because rustbuild tries to use the `llvm-tblgen` that's supposed to be generated by building LLVM for `$BUILD` but rusbuild nevers builds LLVM for `$BUILD` in this case.

cc @alexcrichton

**Comment by japaric** [comment]
### Workaround

Call: `x.py build --stage 1 src/llvm --host=$BUILD` before `x.py build --stage 1 src/rustc --host=$HOST`.

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rust-lang/rust/pull/38050
