### ISSUE TITLE
Undefined reference to method implemented on a type alias

### ISSUE THREAD

**Issue by Riateche** [rust-lang/rust#38031]
lib.rs:
```
pub struct A;
pub mod m1 {
  type A = ::A;
  impl A {
    pub fn f1(&self) {}
  }
}
```
test1.rs:
```
extern crate crate_name;
#[test]
fn test1() {
  crate_name::A.f1();
}
```
"cargo test" output:
```
warning: method is never used: `f1`, #[warn(dead_code)] on by default
 --> src/lib.rs:5:5
  |
5 |     pub fn f1(&self) {}
  |     ^^^^^^^^^^^^^^^^^^^

error: linking with `cc` failed: exit code: 1
  |
<linker command>
  = note: .../target/debug/deps/test1-8a1b07ca81971304.0.o: In function `test1::test1':
.../tests/test1.rs:5: undefined reference to `crate_name::m1::_$LT$impl$u20$crate_name..A$GT$::f1::h6e77858629cdd51c'
collect2: error: ld returned 1 exit status
```
Looks like some part of Rust thinks that `f1()` should not be available and removes its implementation, and some part thinks that the method is available and tries to use it. If the method should not really be available, rustc should output a sensible error about the missing method when building the test.

**Comment by eminence** [comment]
Old issue triage:   I can reproduce this issue in 1.14, but it **does not** reproduce in 1.15, nor in 1.48.   This can be closed
