### ISSUE TITLE
rustbuild: target.*.musl-root in config.toml is ignored

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#38058]
AFAICT, the `CFG_MUSL_ROOT_X86_64` "variable" in the `config.mk` file that `configure` generates overrides the `target.x86_64-unknown-linux-musl.musl-root` setting in `config.toml`. I think the precedence should be the other way around.

cc @alexcrichton is `CFG_MUSL_ROOT_X86_64` new-ish?

**Comment by alexcrichton** [comment]
Ah yes that's newer and should be preferred. I think I ran into this awhile ago as well.

I think there's a bug in rustbuild to ignore the x86_64 default if musl-root is specified, but we could also just stop documenting `musl-root` in rustbuild.
