### ISSUE TITLE
Don't suggest to use things which weren't found either.

### ISSUE THREAD

**Issue by leoschwarz** [rust-lang/rust#38054]
Sometimes it is very useful when rustc figures out that the faulty module use you just made is probably just a typo and directs you a potential match (thanks for that!). However it also directs you to potential matches which haven't been found either in certain cases, for example compiling

```rust
use DoesntExist1;
use DoesntExist2;
```

currently (2016-11-28) yields with both stable and nightly the following output:
```
error[E0432]: unresolved import `DoesntExist1`
 --> src/lib.rs:1:5
  |
1 | use DoesntExist1;
  |     ^^^^^^^^^^^^ no `DoesntExist1` in the root

error[E0432]: unresolved import `DoesntExist2`
 --> src/lib.rs:2:5
  |
2 | use DoesntExist2;
  |     ^^^^^^^^^^^^ no `DoesntExist2` in the root. Did you mean to use `DoesntExist1`?
```

While this is merely a suggestion displayed and shouldn't cause any harm at all maybe it might still be worth to check if what is suggested was actually found in the current scope. Or would that be too expensive (e.g. overhead in tracking what was already successfully imported and what not) and is thus left as is by design?

**Comment by jseyfried** [comment]
This should be fixable by changing the suggestion code in `resolve_imports.rs` to only consider suggesting names that do not resolve to `Def::Err`.

**Comment by cyplo** [comment]
Is this easy to fix ? If so - maybe worth marking as so and mentioning on Rust Weekly ?

**Comment by jseyfried** [comment]
@cyplo Yeah, I believe this can be fixed by replacing [these lines](https://github.com/rust-lang/rust/blob/c80c31a502c838f9ec06f1003d7c61cf9de9d551/src/librustc_resolve/resolve_imports.rs#L598-L599) with `_ => None,`.

**Comment by ioctaptceb** [comment]
I think I can take this, if it hasn't been worked on so far!

**Comment by tshepang** [comment]
@ioctaptceb got for it

**Comment by ioctaptceb** [comment]
How can I assign myself?

**Comment by cyplo** [comment]
Not sure if you can via github, due to permissions, but you can just start working on it :) There's a trace in the comments, anyone looking for more work would see them hopefully here in this issue.
