### ISSUE TITLE
Awkward wording of char slicing error message

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#38052]
```rust
fn slice_not_on_char_boundaries() {
    let s = "Здравствуйте";
    &s[0..1];
}
```

gives

```text
thread 'main' panicked at 'index 0 and/or 3 in `Здравствуйте` do not lie on character boundary'
```

To me, "index do not lie" feels weird, should be "does not lie".

**Comment by killercup** [comment]
Lol, I initially read this as saying "do not lie [about] character boundary" to the person who wrote `1..2`!

I'd suggest:

> byte index 0 and/or 3 in `Здравствуйте` is not on a character boundary

Assuming the actual problem is that you can't form a new string slice with invalid/cut off characters:

> byte index 0 and/or 3 in `Здравствуйте` is middle of a character, slice would be invalid UTF-8

**Comment by durka** [comment]
Well, the problem is "and/or": "0 and 3 are" / "0 or 3 is". Can we just check in the function that prints this message, and make the error message less vague? It's on the panic path anyway.

**Comment by bluss** [comment]
I made a PR with your strategy @durka. It feels good to be more friendly yet technically specific here (?)
