### ISSUE TITLE
Add ability to provide suggestions for move-out-of-borrowed errors

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#38063]
```rust
fn main() {
    #[derive(Debug)]
    struct Foo;
    let x = Some(Foo);
    let y = &x;
    {
        println!("{:?}", y.unwrap());
    }
}
```

will give a "cannot move out of borrow" error. The correct solution here is to use `.as_ref()`. We could make the compiler detect this case and suggest the fix.

Even better would be an annotation on the `unwrap()` function; `#[rustc_on_move("Try `.as_ref().unwrap()` instead?")]` that can be applied to methods on `self`?

**Comment by oli-obk** [comment]
I don't think this should have an annotation. Instead it should special-case on the `AsRef` trait and on custom `as_ref` impl methods that take `self: &'a Self<X, Y, Z, T, U, A, B, C>` as an argument and yield a `Self<X, Y, Z, &'a T, &'a U, A, B, C>`.

**Comment by estebank** [comment]
Current output:

```
error[E0507]: cannot move out of `*y` which is behind a shared reference
 --> src/main.rs:7:26
  |
7 |         println!("{:?}", y.unwrap());
  |                          ^
  |                          |
  |                          move occurs because `*y` has type `std::option::Option<main::Foo>`, which does not implement the `Copy` trait
  |                          help: consider borrowing the `Option`'s content: `y.as_ref()`
```
