### ISSUE TITLE
#[path] attributes incorrectly based on logical module paths

### ISSUE THREAD

**Issue by CryZe** [rust-lang/rust#38060]
The path attributes are based on the logical module path instead of the actual file they are located in, so they might contain folders that don't even exist.

## [Example](https://is.gd/F3v8jo)

```rust
mod foo {
    #[path = "baz/bar.rs"]
    mod bar;
}
```

## Error
```
error: couldn't read "foo/baz/bar.rs": No such file or directory (os error 2)
 --> <anon>:3:9
  |
3 |     mod bar;
  |         ^^^
```

It's looking for a folder called `foo` because it's in an inline module called `foo`. However there's no folder with that name. You can do `..` but that can still fail if the folder doesn't exist. At least it does in the Linux Subsystem of Windows, not in mingw however.

**Comment by jseyfried** [comment]
@CryZe 
> path attributes are based on the logical module path instead of the actual file they are located in

I think changing this would cause too much breakage in practice, and I'm not sure it would be a good idea in the first place.

You could add `#[path = ""]` to `mod foo { ... }` so that `foo` has the same logical path as its containing module:
```rust
#[path = ""]
mod foo {
    #[path = "baz/bar.rs"]
    mod bar;
}
```
or even better:
```rust
#[path = "baz"]
mod foo {
    #[path = "bar.rs"]
    mod bar;
}
```

**Comment by Mark-Simulacrum** [comment]
I think this isn't really a bug. I agree that changing it would likely cause a lot of breakage; I think the "right way" @jseyfried suggests is a good alternative. It represents the reality of the situation more clearly, to me, at least. As such, I'm going to close.
