### ISSUE TITLE
checked arithmetic not treated as constant in debug builds

### ISSUE THREAD

**Issue by BurntSushi** [rust-lang/rust#38074]
This code produces a compiler error with `rustc foo.rs` but compiles successfully with `rustc -O foo.rs`:

```rust
#![feature(platform_intrinsics, repr_simd)]

extern "platform-intrinsic" {
    fn simd_shuffle2<T, U>(x: T, y: T, idx: [u32; 2]) -> U;
}

#[repr(simd)]
#[derive(Clone, Copy)]
#[allow(non_camel_case_types)]
struct u64x2(u64, u64);

fn main() {
    let a = u64x2(1, 2);
    let r: u64x2 = unsafe { simd_shuffle2(a, a, [0-0, 0-0]) };
    assert_eq!(r.0, 1);
    assert_eq!(r.1, 1);
}
```

The error is:

```
$ rustc shuffle.rs 
error[E0526]: shuffle indices are not constant
  --> shuffle.rs:14:29
   |
14 |     let r: u64x2 = unsafe { simd_shuffle2(a, a, [0-0, 0-0]) };
   |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

**Comment by BurntSushi** [comment]
cc @eddyb

**Comment by eddyb** [comment]
This has to do with how the result of a checked op is a tuple and the 2's complement wrapping value is accessed through `temp.0`: the fix would be to track an initialization with a checked op in a field of `TempState::Defined`, then treat `temp.0` as constant if `temp` is promotable and has that flag.

I believe that the promoter will work as-is, it's just the constant qualifier that needs to understand this.

**Comment by eddyb** [comment]
Looking at it again, the const qualifier works fine with fields, but the promoter's initial set of potentially promotable temporaries doesn't include the tuple because one of the uses is by-field.
