### ISSUE TITLE
Type inference and impl visibility

### ISSUE THREAD

**Issue by ilammy** [rust-lang/rust#38070]
I've been abusing type-parameterized traits for C++-style template metaprogramming ([background](https://users.rust-lang.org/t/statically-dispatched-strategy-using-traits/8185/9)) and ran into this strange behavior of the type inferencer.

Suppose we have this:

```
mod equality {
    pub trait Equal<How> {
        fn equal(&Self, &Self) -> bool;
    }

    pub struct ByDefault;

    impl<T> Equal<ByDefault> for T where T: PartialEq {
        fn equal(a: &T, b: &T) -> bool {
            a == b
        }
    }
}

mod i32_default {
    use super::equality::{Equal, ByDefault};

    #[test]
    fn test() {
        assert_eq!(Equal::equal(& 0, &0), true);
        assert_eq!(Equal::equal(& 0, &1), false);
        assert_eq!(Equal::equal(&-1, &1), false);
    }
}
```

The compiler has been able to deduce the type of `Equal::<ByDefault>::equal(&i32, &i32)` just fine in this case. Though, it complains about `ByDefault` being used nowhere, and this works even if `ByDefault` is not imported into `i32_default` module.

However, it also breaks if another impl is added to the picture:

```
mod i32_absolute_equality {
    use super::equality::{Equal};

    pub struct ByAbsoluteValue;

    impl Equal<ByAbsoluteValue> for i32 {
        fn equal(a: &i32, b: &i32) -> bool {
            a.abs() == b.abs()
        }
    }
}
```

Given the following modules:

```
mod i32_special {
    use super::equality::{Equal};
    use super::i32_absolute_equality::{ByAbsoluteValue};

    #[test]
    fn test() {
        assert_eq!(Equal::equal(& 0, &0), true);
        assert_eq!(Equal::equal(& 0, &1), false);
        assert_eq!(Equal::equal(&-1, &1), true);
    }
}

mod i32_both {
    use super::equality::{Equal, ByDefault};
    use super::i32_absolute_equality::{ByAbsoluteValue};

    #[test]
    fn test() {
        assert_eq!(Equal::<ByDefault>::equal(& 0, &0), true);
        assert_eq!(Equal::<ByDefault>::equal(& 0, &1), false);
        assert_eq!(Equal::<ByDefault>::equal(&-1, &1), false);

        assert_eq!(Equal::<ByAbsoluteValue>::equal(& 0, &0), true);
        assert_eq!(Equal::<ByAbsoluteValue>::equal(& 0, &1), false);
        assert_eq!(Equal::<ByAbsoluteValue>::equal(&-1, &1), true);
    }
}
```

I have expected the type inferencer to be able to deduce the types in `i32_special` automatically, while in `i32_both` it should have required the user to disambiguate. The reason is that there is only one suitable `How` type for `Equal<How>` in scope in `i32_special`, and two of them in `i32_both` case. However, the compiler cannot infer the types in `i32_special`. Furthermore, it cannot (now) infer the types even in `i32_default`!

It seems that I (mistakingly?) assume that impls also have visibility that is controlled by the visibility of their parameters. In this case it all makes sense. That's why `i32_default` does not require `ByDefault` to be imported. That's why it works if there only one impl in crate, and does not work if there is any other impl for any other type anywhere. This may be true, but this is somewhat counterintuitive on my mind.

P.S.
```
$ rustc --version
rustc 1.13.0 (2c6933acc 2016-11-07)
```

**Comment by Mark-Simulacrum** [comment]
It is expected that type inference may break when adding more impls or code.

Closing.
