### ISSUE TITLE
Tracking issue for String::split_off

### ISSUE THREAD

**Issue by clarcharr** [rust-lang/rust#38080]
For PR #38056.

cc @alexcrichton

**Comment by brson** [comment]
@rfcbot fcp merge

Mirrors an existing vec function. It looks to me like the argument name needs to be changed for one of them to be consistent ("mid" vs "at").

**Comment by clarcharr** [comment]
Adding to what @brson said, `Vec::split_off` uses `at`, whereas `str::split_at` and `slice::split_at` use `mid`. Perhaps the original `split_off` should be changed to `mid`?
