### ISSUE TITLE
Unable to use std::fs::FileType for library

### ISSUE THREAD

**Issue by cholcombe973** [rust-lang/rust#38088]
i'm writing ffi bindings for glusterfs and I would really like to make use of some of the std library features like `std::fs::FileType`, `DirEntry` and `Metadata` among other things.  Gluster exposes a posix api over their gfapi bindings: https://github.com/gluster/glusterfs/blob/master/api/src/glfs.h.  You can see in my bindings here where the std library primitives would be useful: `https://github.com/cholcombe973/Gfapi-sys/blob/master/src/gluster.rs#L118`.  Is it possible to get some of them exposed?  Example: `https://github.com/rust-lang/rust/blob/ccdc26fd42dfccc5832114baa275f0936738095a/src/libstd/sys/unix/fs.rs#L58` They're currently private.

**Comment by Mark-Simulacrum** [comment]
I don't think we want to expose internal binding details, since it would make maintenance for libstd/libcore harder. You might want to look at something like [nix](https://crates.io/crates/nix) but I don't think that has the structs you want.

**Comment by cholcombe973** [comment]
No problem.  Thanks @Mark-Simulacrum
