### ISSUE TITLE
`x.py build --stage 1 src/libstd --target $T` rebuilding rustc crates when not necessary

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#38094]
[Logs](https://gist.github.com/japaric/2d654d69b8ee6eb9f81af56510a99d3e) of two consecutive `x.py build` calls that rebuild the rustc crates but not the crates "below" std. (Grep for `$ ` to see the commands)

cc @alexcrichton

**Comment by alexcrichton** [comment]
Suspicious:

```
stale: /shared/rust/checkouts/musl/src/liballoc_jemalloc/../jemalloc/.git/ORIG_HEAD -- 1480531948.379850662s vs 1480530784.555870554s
```

I think that'd trigger a rebuild of everything? Maybe this is just `alloc_jemalloc`'s build script being too eager about `cargo:rerun-if-changed`. Could you try tweaking that build script and see if it fixes the problems here?
