### ISSUE TITLE
rustbuild: Support enable-local-rust in bootstrap.py

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#38115]
The stage0 compiler is used in the initial python script to build the build system itself. Right now it respects `--local-rust-root` but it should also respect `--enable-local-rust` which indicates that `rustc` should be found from `PATH` if not otherwise specified.

**Comment by Mark-Simulacrum** [comment]
I can't find either local-rust-root or enable-local-rust in bootstrap.py today. Could you clarify if this is still a problem, @alexcrichton?

**Comment by alexcrichton** [comment]
Oh sorry this is a configure script option, `--enable-local-rust`, and it may or may not be fully implemented in rustbuild, I foget the status of it :(

**Comment by jyn514** [comment]
I'm going to close this since you can achieve the same thing with `rustc = "rustc"`; I don't think it's important to have exactly the same flags as the old makefiles, especially since they've been gone for several years now.
