### ISSUE TITLE
Rust compiler macro_rules! problem

### ISSUE THREAD

**Issue by vityafx** [rust-lang/rust#38127]
I had a code which worked okay:

        let date_start;
        if let Ok(ds) = remove(&mut map, "date_start") {
            if ds.is_string() {
                date_start = Some(DateTime::parse_from_str(ds.as_str().unwrap(),
                                                           "%Y-%m-%d")?.date()); // safe
            } else {
                date_start = None;
            }
        } else {
            date_start = None;
        }

As soon as I have a lot of such fields in my json map I decided to make a macro for this:

```
macro_rules! parse_optional_string {
    // Parse optional value with decoding it from json.
    // $json_map must be of type `BTreeMap<String, serde_json::Value>`
    ($field: ident, $path: expr, $json_map: ident, $decoder: expr) => {
        if let Ok(_temp_field_) = remove(&mut $json_map, $path) {
            if _temp_field_.is_string() {
                $field = Some($decoder(_temp_field_.as_str().unwrap_or("")));
            } else {
                $field = None;
            }
        } else {
            $field = None;
        }
    };
}
```

And tried to use it but it gives weird errors:

**Attempt 1 - forgot to unpack result**

        parse_optional_string!(date_end, "date_end", map,
                               |s| DateTime::parse_from_str(s, "%Y-%m-%d").date());

```
error: no method named `date` found for type `std::result::Result<chrono::DateTime<chrono::FixedOffset>, chrono::ParseError>` in the current scope
   --> src/tournaments.rs:377:76
    |
376 |         parse_optional_string!(date_end, "date_end", map,
    |         - in this macro invocation
377 |                                |s| DateTime::parse_from_str(s, "%Y-%m-%d").date());
    |                                                                            ^^^^


```

Okay, not a problem! **Attempt 2: adding ?**

        parse_optional_string!(date_end, "date_end", map,
                               |s| DateTime::parse_from_str(s, "%Y-%m-%d")?.date());

```
error[E0277]: the trait bound `chrono::Date<chrono::FixedOffset>: std::ops::Carrier` is not satisfied
   --> src/tournaments.rs:377:36
    |
376 |         parse_optional_string!(date_end, "date_end", map,
    |         - in this macro invocation
377 |                                |s| DateTime::parse_from_str(s, "%Y-%m-%d")?.date());
    |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ trait `chrono::Date<chrono::FixedOffset>: std::ops::Carrier` not satisfied
    |
    = note: required by `std::ops::Carrier::from_error`
```

**Attempt 3: trying to use old style `try!` (assuming it would work):**

        parse_optional_string!(date_end, "date_end", map,
                               |s| try!(DateTime::parse_from_str(s, "%Y-%m-%d")).date());

```

error[E0308]: mismatched types
   --> src/tournaments.rs:377:36
    |
376 |         parse_optional_string!(date_end, "date_end", map,
    |         - in this macro invocation
377 |                                |s| try!(DateTime::parse_from_str(s, "%Y-%m-%d")).date());
    |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found struct `chrono::Date`
    |
    = note: expected type `std::result::Result<_, _>`
    = note:    found type `chrono::Date<chrono::FixedOffset>`
```

Sooooo, I know the way it will work 100%, **Attempt 4: using unwrap()**:

        parse_optional_string!(date_end, "date_end", map,
                               |s| DateTime::parse_from_str(s, "%Y-%m-%d").unwrap().date());

And only the last way works. What is the problem here?

    serde_json = "0.8.3"
    chrono = "0.2.25"
    rustc version is rustc 1.13.0 (2c6933acc 2016-11-07)

**Comment by vityafx** [comment]
Sorry, just found a problem. The it seems is in lambda's return type:

        parse_optional_string!(date_end, "date_end", map,
                               |s| -> Result<Date<FixedOffset>> {
                                   Ok(try!(DateTime::parse_from_str(s, "%Y-%m-%d")).date())
                               });

**Comment by sinkuu** [comment]
(BTW you can use and_then instead of `if` cascade)

```rust
// as_ref() is there to prevent consuming Option<Value>
let date_start =
    if let Some(ds) = remove(&mut map, "date_start")
        .as_ref().and_then(Value::as_str)
    {
        Some(DateTime::parse_from_str(ds, "%Y-%m-%d")?)
    } else {
        None
    };
```

I'd like to make the macro return `Result<Option<Value>>`:

```rust
macro_rules! parse_optional_string {
    ($field: ident, $json_map: ident, $decoder: expr) => {
        if let Some(ds) = remove(&mut $json_map, stringify!($field))
            .as_ref().and_then(Value::as_str)
        {
            ($decoder)(ds).map(Some)
        } else {
            Ok(None)
        }
    };
}
```

```rust
let date_start =
    parse_optional_string!(date_start, map,
                           |ds| DateTime::parse_from_str(ds, "%Y-%m-%d"))?; // <- note `?` here
```
