### ISSUE TITLE
Confusing error message when mis-spelling macro invocation

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#38126]
When compiling
```rust
thread_local {
    static I: i32 = 0;
}
```
the following error is generated
```
error: expected one of `!` or `::`, found `{`
 --> m.rs:1:14
  |
1 | thread_local {
  |              ^
```

This happens because the only thing that could possibly be in an item position and not start with a keyword is a macro, and macros start with a path. A path can contain double colons. However, a macro invocation can not, and the compiler will generate an error at a later stage if you try to invoke a macro that way. See #28558

To be clear, I think the error message should just be “expected \`!\`, found \`{\`”.

**Comment by petrochenkov** [comment]
>A path can contain double colons. However, a macro invocation can not

This will change pretty soon - https://github.com/rust-lang/rust/pull/38082

**Comment by jethrogb** [comment]
I suppose it's not feasible to change the parser error message based on whether the feature is activated?

**Comment by jseyfried** [comment]
@jethrogb It's feasible, but I don't think the extra complexity is worth it.

**Comment by jethrogb** [comment]
Closing this because macros 2.0 is pretty much around the corner.
