### ISSUE TITLE
Borrowck documentation oversights

### ISSUE THREAD

**Issue by NSil** [rust-lang/rust#38120]
These are things that I noticed while reading 'librustc_borrowck/borrowck/README.md'. I'll update this issue as I read. Some of the issues that I mention are about things that are obviously missing, and others are just suggestions.

### Obviously missing
```text
**Mutability requires uniqueness.** To mutate a path
``` 
^  Incomplete sentence. (`... Or not to mutate a path?`)

### Suggestions
In the 'Formal rules' section, the predicate notation used in the rest of the document is introduced:
```text
PREDICATE(X, Y, Z)                  // Rule-Name
  Condition 1
  Condition 2
  Condition 3
```
At first glance, this is trivial, but then this predicate is introduced:
```text
MUTABILITY(X, imm)                  // M-Var-Imm
  DECL(X) = imm
```
I understood it as:
Some of the conditions are actually the conditions in which the predicate is tested.
If `ARGUMENT` is actually a `value`, it is the same as adding the condition `ARGUMENT = value` to the predicate. 

I don't know if I was correct, or if this is a common notation (I don't know how to search for an explanation about a notation) but a clarification or a link to one would help.

**Comment by Mark-Simulacrum** [comment]
cc @rust-lang/compiler, should we update this documentation?

**Comment by nikomatsakis** [comment]
> At first glance, this is trivial, but then this predicate is introduced:

The notation is basically "inference rule" notation -- we could probably add a `:-` and some commas and cite Prolog.  So basically in that example, `MUTABILITY(X, Imm)` holds if `DECL(X)` is equal to `imm`.

> should we update this documentation?

I'm somewhat inclined to rewrite it from scratch once borrowck MIR lands.

**Comment by nikomatsakis** [comment]
The documentation was written before the current borrowck rules and I think it's structure is more confusing than it has to be as a result.

**Comment by nikomatsakis** [comment]
Decided to close this issue -- we'll rewrite in terms of MIR borrowck.
