### ISSUE TITLE
impl Fn<T> for Box<Fn<T>> and similar should exist

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#38132]
For example you cannot write type like ` ::std::iter::Map<::std::ops::Range<u8>, Box<Fn(u8) -> u32>>` now.

**Comment by bluss** [comment]
Entangled with FnBox, see #28796

**Comment by dtolnay** [comment]
I don't know the full implications of this, but I would be interested in seeing a PR to add these impls and we can go from there.

**Comment by czipperz** [comment]
This should be closed

**Comment by dtolnay** [comment]
:+1: Fixed in 1.35.0.
