### ISSUE TITLE
Tracking issue for `char::is_letter` (feature `unicode_is_letter`)

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#38137]
Implemented in #38125.

**Comment by estebank** [comment]
cc @alexcrichton

**Comment by brson** [comment]
@rfcbot fcp merge

**Comment by brson** [comment]
My only qualm is the slippery slope of ever-expanding unicode tables.

**Comment by SimonSapin** [comment]
Stabilizing this feature seems somewhat premature, the PR that adds it has not been merged or r+’d yet.

I also share @brson’s concern. That PR adds 4336 bytes of static data to `std`, but this functionality could just as well be provided by an external crate.

**Comment by alexcrichton** [comment]
Yes I agree with @SimonSapin, we should probably at least let it bake in tree a bit before stabilizing.

**Comment by Kimundi** [comment]
Yeah, let's wait a bit

**Comment by brson** [comment]
@rfcbot cancel

**Comment by alexcrichton** [comment]
@rfcbot fcp cancel
