### ISSUE TITLE
Improve E0389 "cannot borrow data mutably in a `&` reference" error message

### ISSUE THREAD

**Issue by mikhail-m1** [rust-lang/rust#38147]
Error in next case could be more helpful
```
struct Foo<'a> {
    s: &'a mut String
}

impl<'a> Foo<'a> {
    fn f(&self) {
        self.s.push('x');
    }
}

fn main() {}
```

error:
```
error[E0389]: cannot borrow data mutably in a `&` reference
 --> 2.rs:7:9
  |
7 |         self.s.push('x');
  |         ^^^^^^ assignment into an immutable reference
```

cc @jonathandturner

**Comment by GuillaumeGomez** [comment]
How would you improve it? It seems pretty clear for me. :-/

**Comment by mikhail-m1** [comment]
I think not will be helpful 
```
 fn f(&self) {
      ^ use '&mut self' for make mutable
```
and for sample from tests
```
    let fancy_ref = &(&mut fancy);
                    ^use '&mut (&mut fancy)' for make mutable
    fancy_ref.num = 6; //~ ERROR E0389
```
I'm not sure it's easy to do, but I'll try.

**Comment by GuillaumeGomez** [comment]
Oh, I actually proposed such a change [here](https://github.com/rust-lang/rust/pull/37780). Still some little things to debate.

**Comment by mikhail-m1** [comment]
@GuillaumeGomez I don't understand how its related, are you already work on it?

**Comment by GuillaumeGomez** [comment]
It's the first step. It suggests references and stuff. However, if the variable isn't mutable, it won't say "make your variable mutable and then use &mut". This step will need to be added.
