### ISSUE TITLE
OpenCL support

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#3814]
Discussed in the following mailing list thread ("GPU support"):

https://mail.mozilla.org/pipermail/rust-dev/2012-October/002509.html

Filed here so it doesn't get forgotten.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#614
