### ISSUE TITLE
Borrow checker: borrows in else branch of if let

### ISSUE THREAD

**Issue by theduke** [rust-lang/rust#38159]
If there already is an issue for this, I apologize. I couldn't find one, but searching for this is a bit hard.

Right now, the borrow checker does not allow a borrow of a variable in the else branch if the let binding borrows the variable.

Example:
```rust
  let mut m = HashMap::<i64, bool>::new();
  if let Some(x) = m.get(&10) {
    // do something...
  }
  else {
    m.insert(10, true);
  }
```

The `m.insert` is invalid, because the borrow checker assumes an active borrow for the hashmap.

The `Some(x)` binding is not in scope anymore, though, and there's no way to access `x`, so this should be allowed.

**Comment by sfackler** [comment]
I believe this is covered by https://github.com/rust-lang/rfcs/issues/811

**Comment by theduke** [comment]
@sfackler yup, appear to be.

Closing as duplicate...
