### ISSUE TITLE
error index test failures are hard to find

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#38162]
cc @GuillaumeGomez 

You get a failure in Travis like "test failed: Rust_Compiler_Error_Index_167" but there is no other context. It would be nice to incorporate the error number or the source file into the test name.

**Comment by durka** [comment]
[Example](https://travis-ci.org/rust-lang/rust/jobs/181167374#L2135).

**Comment by GuillaumeGomez** [comment]
A PR to fix this is already opened [here](https://github.com/rust-lang/rust/pull/36320).
