### ISSUE TITLE
fn() type does not implements Debug, although rustdoc says it does so.

### ISSUE THREAD

**Issue by kdy1997** [rust-lang/rust#38170]
Debug trait: https://doc.rust-lang.org/std/fmt/trait.Debug.html

It contains ```impl<Ret> Debug for fn() -> Ret```.

I tried to compile this code

https://play.rust-lang.org/?gist=360a19def222bb4e64a79dfbe4f2d905&version=stable&backtrace=0
```rust
use std::fmt::Debug;

fn test_debug<T: Debug>(t: T) {}

fn static_fn() {}
fn static_fn_ret() -> (i32) {
    unimplemented!()
}

fn main() {
    test_debug(static_fn);
    test_debug(static_fn_ret);

    let as_var: fn() -> () = static_fn;
    test_debug(as_var);

    fn static_local_fn() {}
    test_debug(static_local_fn);
}
```
I expected it to be compiled, but compiler says Debug is not implemented.

(once per fn, but **except as_var**)
```
test_debug(static_fn);
^^^^^^^^^^ the trait `std::fmt::Debug` is not implemented for `fn() {main::static_local_fn}`
```

## Meta

```sh
$ rustc --version --verbose
rustc 1.15.0-nightly (d5814b03e 2016-11-23)
binary: rustc
commit-hash: d5814b03e652043be607f96e24709e06c2b55429
commit-date: 2016-11-23
host: x86_64-pc-windows-gnu
release: 1.15.0-nightly
LLVM version: 3.9
```

Edit: Added a link to rust playground, and modified code to make it testable on playground.
Edit: Modified slightly, as saving fn to variable makes it work.

**Comment by sfackler** [comment]
That `impl` is for function pointers, but each function defines its own type which implements the `Fn` trait. Note that the type error is complaining about `fn() {main::static_local_fn}`, not `fn()`.

**Comment by kdy1997** [comment]
I got it. I noticed fn() type implements debug after digging some rust core code.

I thought it is not documented, but now I find it in [the rust lang reference](https://doc.rust-lang.org/reference.html#function-types).
