### ISSUE TITLE
rustdoc: inconsistent indentation for block comments

### ISSUE THREAD

**Issue by zetok** [rust-lang/rust#38173]
Reproducible on both 1.11.0 and 1.15.0-nightly (c80c31a50 2016-12-02)

The code: https://github.com/zetok/tox/blob/b9842c08aec2905924114290fef72bb83b189d6d/src/toxcore/toxid.rs#L189,L239

Inconsistent indentation in generated docs:
![spectacle pe9944](https://cloud.githubusercontent.com/assets/3148759/20887000/b16d4da0-baf0-11e6-8ddc-404cb8c6e23e.png)

**Comment by GuillaumeGomez** [comment]
Funny bug. Actually, I didn't know that `/**` was still a thing.

**Comment by steveklabnik** [comment]
This appears to be fixed! Please let me know if you're still seeing this bug.
