### ISSUE TITLE
rustdoc or rustc: duplicate impls for std::marker::Send

### ISSUE THREAD

**Issue by KalitaAlexey** [rust-lang/rust#38178]
Hi everybody.

Look at https://doc.rust-lang.org/nightly/std/marker/trait.Send.html

There are
```rust
impl<T: ?Sized> !Send for Rc<T>
impl<T: ?Sized> !Send for Weak<T>
```
and
```rust
impl<T> !Send for Rc<T> where T: ?Sized
impl<T> !Send for Weak<T> where T: ?Sized
```

They are equal. Wow. There are same lines at the beginning.

**Comment by ollie27** [comment]
Dupe of #25061.

**Comment by KalitaAlexey** [comment]
Hi @ollie27,

You are right. I am closing this.
