### ISSUE TITLE
assertion failed: eps.windows(2).all(|w| w[0].cmp(self, &w[1]) != Ordering::Greater)

### ISSUE THREAD

**Issue by jedisct1** [rust-lang/rust#38177]
Got an ICE while compiling the `protobuf` crate with that recent snapshot: `rustc 1.15.0-nightly (28d6623bc 2016-12-03)` on arm.

```
thread 'rustc' panicked at 'assertion failed: eps.windows(2).all(|w| w[0].cmp(self, &w[1]) != Ordering::Greater)', /buildslave/rust-buildbot/slave/nightly-dist-rustc-cross-host-linux/build/src/librustc/ty/context.rs:1525
```

## Meta

`rustc --version --verbose`:
```
rustc 1.15.0-nightly (28d6623bc 2016-12-03)
binary: rustc
commit-hash: 28d6623bccf8f7e9a40a47895df75dd9ef2619da
commit-date: 2016-12-03
host: arm-unknown-linux-gnueabihf
release: 1.15.0-nightly
LLVM version: 3.9
```

Backtrace: https://gist.github.com/f7ea7c27e5acb684140d2a5227621617

**Comment by nikomatsakis** [comment]
triage: P-high

**Comment by pnkfelix** [comment]
/me is super-weirded out by the fact that the panic message is claiming that the assertion is arising from within `librustc/ty/context.rs`; I'm pretty sure there's never been any code there that looks anything like `eps.windows(2).all(|w| w[0].cmp(self, &w[1])`. Is that mismatch potentially a sign of broken source span information (e.g. arising from macro expansion)?

**Comment by Badel2** [comment]
I have this issue when compiling anything, even an empty project. As far as I can tell, it wasn't present in nightly 2217bd771 2016-11-25

```
thread 'rustc' panicked at 'assertion failed: eps.windows(2).all(|w| w[0].cmp(self, &w[1]) != Ordering::Greater)', /buildslave/rust-buildbot/slave/nightly-dist-rustc-cross-host-linux/build/src/librustc/ty/context.rs:1525
```

I tried to run with RUST_BACKTRACE=1 and it took 10 minutes (it takes maybe 1 second without). Backtrace: https://gist.github.com/Badel2/9d0f9245fadca1505042dd4af4ef553a

```
root@localhost:~# rustc --version --verbose
rustc 1.15.0-nightly (daf8c1dfc 2016-12-05)
binary: rustc
commit-hash: daf8c1dfce3b448fc581cc319f64632ec22bd0e1
commit-date: 2016-12-05
host: armv7-unknown-linux-gnueabihf
release: 1.15.0-nightly
LLVM version: 3.9
```

**Comment by arielb1** [comment]
I can't reproduce this. What configuration are you using?
