### ISSUE TITLE
[rustbuild] Use git2

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/rust#38184]
Currently, rustbuild uses a `Process` to launch `git`, and parse the output. Using [git2](https://crates.io/crates/git2) would be more robust. I can try to do it.

**Comment by jonas-schievink** [comment]
Note that libgit2 isn't quite at feature parity with git. For example, shallow clones are unsupported, which might be a problem for users who don't want to download the whole git history.

**Comment by alexcrichton** [comment]
I personally like to use git2 as it provides a cross platform and efficient git implementation. Thankfully rustbuild isn't too git heavy so doing this wouldn't take a lot of work I believe (it doesn't do shallow clones or the like). Additionally it'd make submodule management *much* faster I'd imagine, which I'm always a fan of!

My hesitation here though is that we'd have to build a bunch of native libraries. At least libgit2 and maybe curl? The build system is the main entry point so I'd like to keep it quick and easy to build, and I'm not quite sure what the impact would be.

I think we can get by without adding more build requirements (it just requires cmake) though so it's in theory not too bad. It'd be worth looking into whether we can build libgit2 with no dependencies as that would lighten the load quite a bit I believe

**Comment by est31** [comment]
IANAL, but to my best understanding, when vendoring GPL code, you might be obliged to guarantee source code downloads for 3 years (aka static.rlo may not be deleted), depending on which "option" you chose in section 3 of the GPLv2.

**Comment by alexcrichton** [comment]
Submodule management has now moved into Python, so I think this is unfortunately basically not possible, so closing.
