### ISSUE TITLE
[rustbuild] ignores the --build flag

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#38198]
`build` being commented-out in config.toml and running 

python x.py test --stage 2 --build=i686-unknown-linux-gnu

starts downloading the x86_64 compiler… and then tries to execute i686 compiler which fails with a terrible error of

```
failed to execute command: No such file or directory (os error 2)
```

**Comment by Mark-Simulacrum** [comment]
Yeah, still a problem.

**Comment by Mark-Simulacrum** [comment]
Should be fixed by https://github.com/rust-lang/rust/pull/43384.
