### ISSUE TITLE
Rust Reference: Clarify visibility of items in functions

### ISSUE THREAD

**Issue by itaibn** [rust-lang/rust#38193]
In Rust it is possible to define items inside functions. It is natural to ask whether it's possible to import these items with a `use` statement out of the function, like so:

```
pub fn func() {
    pub struct Struct;
}

use func::Struct;
```

The Rust Reference does not give any explicit answer on whether such a construct is valid. In particular, it says "Every item has a canonical path within its crate," which suggests the path of `Struct` in the example above is `func::Struct`, and it doesn't indicate such items are private. Only by running the code I could tell that this construct is not valid.

I suggest the Rust Reference clarify either in its discussion of paths, functions, or item statements that it's impossible to import an item from an item statement.

**Comment by steveklabnik** [comment]
The reference lives in its own repo now, I have migrated this to https://github.com/rust-lang-nursery/reference/issues/25

thanks!
