### ISSUE TITLE
Error for impl with lifetime

### ISSUE THREAD

**Issue by saixmh** [rust-lang/rust#38209]
For example

```rust
struct Foo<'a>(&'a str);

trait Bar<A> { type B; }

trait Baz {}

impl<'a, A, B: Bar<Foo<'a>, B=A>> Baz for B {}

fn main() {}
```

>error[E0207]: the type parameter `A` is not constrained by the impl trait, self type, or predicates
>&nbsp;&nbsp; --> src\main.rs:17:10
>&nbsp;&nbsp;&nbsp;&nbsp; |
>17 | impl<'a, A, B: Bar<Foo<'a>, B=A>> Baz for B {}
>&nbsp;&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ^ unconstrained type parameter

`rustc 1.15.0-nightly (2217bd771 2016-11-25)`

If **`impl`** a type which without **`lifetime`**, it's no errors. I consider this is a bug.

**Comment by saixmh** [comment]
```rust
struct Foo(i32);

trait Bar<A> { type B; }

trait Baz {}

impl<A, B: Bar<Foo, B=A>> Baz for B {}

fn main() {}
```
This is a succesful version.

**Comment by bombless** [comment]
This "succesful version" seems like a bug

**Comment by saixmh** [comment]
@bombless 噗，我英语渣

**Comment by bombless** [comment]
- - 搞错了，我删了那条回复

**Comment by saixmh** [comment]
@bombless 噗，要不要把这几条中文的都删了~？

**Comment by bombless** [comment]
Check https://github.com/rust-lang/rust/blob/master/src/librustc_typeck/impl_wf_check.rs#L58
It might be intended.

**Comment by saixmh** [comment]
@bombless Hmm, it seems like another thing.
