### ISSUE TITLE
[build system] Select llvm target

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/rust#38200]
Currently, llvm is built with all the possible targets including Mips, ARM... For development, we can speed the build by enabling only the native target (x86 or x86_64). Maybe it would also speed the build of rustc?

**Comment by japaric** [comment]
> For development, ...

FWIW, for development I use ccache (pass `--enable-ccache` to `configure`) and building LLVM takes one minute or less on a "fresh" bootstrap. (I usually work with several branches at the same time; one docker container per branch and all of them reuse the same ccache directory)

> we can speed the build by enabling only the native target

Just please don't change the defaullt. I'd be very upset if I spent several minutes building stage1 rustc just to learn that it can't cross compile anything.

**Comment by Yamakaky** [comment]
yeah, of course.

**Comment by xen0n** [comment]
This is such a niche use case, to the point that it's arguably already moot by use of `ccache`, if the sole purpose is to reduce build time. However there may be some other advantages, maybe space savings for use on some *really* storage-constrained systems? I don't know, it's trivial to make the list of targets configurable but the maintenance and support burden is real.

What do the Rust team think? cc @alexcrichton

**Comment by alexcrichton** [comment]
Seems fine to me to add an option for this! We won't do it on the bots, but that doesn't mean it can't exist.
