### ISSUE TITLE
Are BTreeSet iterators guaranteed to visit elements in ascending order?

### ISSUE THREAD

**Issue by Ms2ger** [rust-lang/rust#38204]
On IRC, we established that they probably do. We should document that.

CC @steveklabnik

**Comment by sfackler** [comment]
It is guaranteed I believe.

**Comment by frewsxcv** [comment]
It looks like this is already documented in all iterator methods [in the docs for BTreeSet](https://doc.rust-lang.org/nightly/std/collections/struct.BTreeSet.html) (ctrl-f for "in ascending order"), just not `BTreeSet::iter`.

**Comment by frewsxcv** [comment]
Will be fixed by https://github.com/rust-lang/rust/pull/38208
