### ISSUE TITLE
ICE with incremental build of servo with incremental compilation

### ISSUE THREAD

**Issue by bholley** [rust-lang/rust#38207]
CC @nikomatsakis 

Rev 75418b70054664634f8f69e636f84e7e4e2731ed

error: internal compiler error: ../src/librustc/ty/mod.rs:2346: could not load def-path for DefId { krate: CrateNum(12), node: DefIndex(1) }

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'Box<Any>', ../src/librustc_errors/lib.rs:424
stack backtrace:
   1:        0x10845518a - std::sys::imp::backtrace::tracing::imp::write::h944c02ac40aee2d7
   2:        0x10846244f - std::panicking::default_hook::{{closure}}::h6875a2976258b020
   3:        0x108461ffd - std::panicking::default_hook::h88ffbc5922643264
   4:        0x108462916 - std::panicking::rust_panic_with_hook::ha5aed1dfc0e220e3
   5:        0x108237f4a - std::panicking::begin_panic::h264cdc75d51b518b
   6:        0x108248d74 - rustc_errors::Handler::bug::h620f7270292f0095
   7:        0x104e4cedc - rustc::session::opt_span_bug_fmt::{{closure}}::h4a9b70c3df8b4b3a
   8:        0x104e4cce9 - rustc::session::opt_span_bug_fmt::h7d83586c6e2c7ae6
   9:        0x104e4c86a - rustc::session::bug_fmt::he2d2f00a4afa9d1e
  10:        0x104eda30c - rustc::ty::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::def_path::hc35cac324092b8f5
  11:        0x1041062c4 - rustc_incremental::persist::directory::DefIdDirectoryBuilder::add::h8825afc02579fe3b
  12:        0x1041068a2 - rustc_incremental::persist::directory::DefIdDirectoryBuilder::map::h4bf0a4dfa8942493
  13:        0x104120f15 - rustc_incremental::persist::save::save_dep_graph::h8ad44fda4512c5f8
  14:        0x103caccac - rustc_driver::driver::phase_4_translate_to_llvm::h48ed91c172294403
  15:        0x103c77246 - rustc_driver::driver::compile_input::{{closure}}::hf13172fc4e5a2f4d
  16:        0x103ca569d - rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::hd97ec26bf3a98036
  17:        0x103c84c76 - rustc_driver::driver::phase_3_run_analysis_passes::h6d446abb74c09795
  18:        0x103c752b5 - rustc_driver::driver::compile_input::h8e119234b60571d5
  19:        0x103cbed6b - rustc_driver::run_compiler::hbdfc4f84e2e0f4b9
  20:        0x103bddf68 - std::panicking::try::do_call::hf679f17bf3b43b0b
  21:        0x108464eca - __rust_maybe_catch_panic
  22:        0x103c00d3f - <F as alloc::boxed::FnBox<A>>::call_box::h506fb5d7b8891cd4
  23:        0x108461594 - std::sys::imp::thread::Thread::new::thread_start::h8084b1107992ae5b
  24:     0x7fff8b46899c - _pthread_body
  25:     0x7fff8b468919 - _pthread_start

Build failed, waiting for other jobs to finish...
error: Could not compile `html5ever-atoms`.

To learn more, run the command again with --verbose.
Build FAILED in 0:05:29

**Comment by nikomatsakis** [comment]
cc @michaelwoerister -- I'll try to reproduce this locally. This is used a nightly from a few days back (11-29, I think?). In any case, it seems like a blocker for beta.

**Comment by nikomatsakis** [comment]
I dig some digging into this. The problem has to do with the bogus def-ids given to proc-macros. Haven't had time to dig more yet. cc @jseyfried

**Comment by nikomatsakis** [comment]
By bogus I mean: def-ids without corresponding def-paths.
