### ISSUE TITLE
[travis] Split tests

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/rust#38201]
As we can see [here](https://travis-ci.org/rust-lang/rust/builds/181193969), the travis build spends most on it's time in one job which launches all the tests. By splitting the work between multiple jobs, we could at least divide the build time by two. Something like
```make
check: check1 check2 check3 check4
    ...
check1:
    ...
...
```
where we have four jobs running check[1-4].

**Comment by Mark-Simulacrum** [comment]
More jobs means more money though I believe and we'd have to recompile the compiler; so I don't think this would be all that helpful. Closing.
