### ISSUE TITLE
Doctests aren't running for documentation of macros

### ISSUE THREAD

**Issue by sgrif** [rust-lang/rust#38219]
I noticed that in a branch on Diesel where I had forgotten to update a few doctests, our builds were passing on nightly but failing on stable and beta. It appears that the doctests on macros are not being run on the current nightly. https://travis-ci.org/diesel-rs/diesel/builds/181708974

**Comment by alexcrichton** [comment]
cc @jseyfried, does this ring a bell for you?

**Comment by jseyfried** [comment]
This was caused by #37890, fixed in #38239.

**Comment by alexcrichton** [comment]
Thanks for the quick fix @jseyfried!
