### ISSUE TITLE
Document the types of "static" functions

### ISSUE THREAD

**Issue by jrvidal** [rust-lang/rust#38211]
There are a few aspects of "static" (non-closure) functions that I find useful to know but I can't seem to locate in the docs:
* They all implement `Copy`.
    * And they don't implement `Clone` (is this unusual?)
* They automatically implement the respective function call traits `Fn`, `FnMut` and `FnOnce`.
    * And since they don't have an environment... they are equivalent?

I think it might be appropriate to have an entry in the `std`/`core` documentation with this. Not sure if a new "primitive" page would be appropriate for it.

**Comment by bluss** [comment]
The lack of Clone is a rather annoying bug (#28229) and does of course makes no sense to keep around (`Copy` requires that `Clone` is implemented according to its definition).

**Comment by Mark-Simulacrum** [comment]
Tagging with T-doc. cc @rust-lang/docs, maybe this is good for inclusion into the reference? Or the book?

**Comment by Mark-Simulacrum** [comment]
This should be refiled onto the reference https://github.com/rust-lang-nursery/reference. Closing.
