### ISSUE TITLE
Add ability to pass CFLAGS and LIBS into bootstrap toml

### ISSUE THREAD

**Issue by kallisti5** [rust-lang/rust#38212]
https://github.com/rust-lang/rust/blob/master/src/bootstrap/config.toml.example

The Haiku cross compiler needs CFLAGS (include directories) and LIBS (-lroot and friends) added to the bootstrap.

I don't see an option in the config.toml.example to define these.
(under the # Options for specific targets)

Here is my usage:
```
[host.x86_64-unknown-haiku]
cc = "x86_64-unknown-haiku-gcc"
cxx = "x86_64-unknown-haiku-g++"
[target.x86_64-unknown-haiku]
cc = "x86_64-unknown-haiku-gcc"
cxx = "x86_64-unknown-haiku-g++"
```
Being able to pass "include paths" and lib search paths here would be helpful. (cflags would help cover this)

Here would be my ideal usage:
```
[host.x86_64-unknown-haiku]
cc = "x86_64-unknown-haiku-gcc"
cxx = "x86_64-unknown-haiku-g++"
cflags="-I/home/kallisti5/Code/haiku/headers/posix -I/home/kallisti5/Code/haiku/headers -L/home/kallisti5/Code/haiku/generated.x86_64/objects/haiku/x86_64/release/system/libroot/"
[target.x86_64-unknown-haiku]
cc = "x86_64-unknown-haiku-gcc"
cxx = "x86_64-unknown-haiku-g++"
cflags="-I/home/kallisti5/Code/haiku/headers/posix -I/home/kallisti5/Code/haiku/headers -L/home/kallisti5/Code/haiku/generated.x86_64/objects/haiku/x86_64/release/system/libroot/"
```

**Comment by alexcrichton** [comment]
Sounds like a good idea to me! AFAIK the `host` table isn't actually a config option, so it should be ok to leave that out.

**Comment by avongluck-r1soft** [comment]
Thanks Alex :-)

I went on a lark and tried cflags incase it wasn't documented... it didn't work :-)

CFLAGS as an environment flag *does* work but it impacts all builds, thus linux target builds end up trying to use haiku's include paths and everything breaks into a thousand pieces :-)

**Comment by kallisti5** [comment]
this *feels* like the right spot to add this:
https://github.com/rust-lang/rust/blob/master/src/bootstrap/config.rs#L295

Not sure if target has a a cflags.

**Comment by alexcrichton** [comment]
Yeah that's basically the right location, that'd just want to also get plumbed throughout other locations as well.

Note that `CFLAGS_$target` will set the flags for just that target. You can see more info here -- https://github.com/alexcrichton/gcc-rs#external-configuration-via-environment-variables

**Comment by jessicah** [comment]
Actually, using a cross-compiler with a configured sysroot obviates the need for this, and Haiku's cross-compiler already has sysroot support. I have succeeded in cross-compiling rustc (and cargo) for Haiku without these changes.

**Comment by kallisti5** [comment]
jessicah: Do you have any documentation on how you did it? I'd like to build a dist package for rust.

The following seems to not be enough alone:

```
[llvm]
[build]
target = ["x86_64-unknown-haiku"]
[install]
[rust]
use-jemalloc = false
debug-jemalloc = false
[target.x86_64-unknown-haiku]
cc = "/home/kallisti5/Code/haiku/generated.x86_64/cross-tools-x86_64/bin/x86_64-unknown-haiku-gcc"
cxx = "/home/kallisti5/Code/haiku/generated.x86_64/cross-tools-x86_64/bin/x86_64-unknown-haiku-g++"
[dist]
```

Include and library paths aren't getting picked up as mentioned before.

**Comment by kallisti5** [comment]
Ah... I bet you're making wrappers...

```
$ cat /usr/local/bin/x86_64-unknown-haiku-g*
#!/bin/bash
exec /home/kallisti5/Code/haiku/generated.x86_64/cross-tools-x86_64/bin/x86_64-unknown-haiku-g++ -sysroot= "$@"
#!/bin/bash
exec /home/kallisti5/Code/haiku/generated.x86_64/cross-tools-x86_64/bin/x86_64-unknown-haiku-gcc -sysroot= "$@"
```

**Comment by kallisti5** [comment]
@jessicah got us bootstrapped with the not-super-obvious sysroot approach... not 100% if there is still a viable story here.  Maybe this should transform into some kind of "Tips for bootstrapping" tecnical article with mentions of sysroots? :-)

**Comment by gibix** [comment]
hello! there are any news here? Can I work on it?

**Comment by Enselic** [comment]
Triage: Closing as won't fix since based on the discussion it seems like there is a solution already.
