### ISSUE TITLE
[rustbuild] --verbose should print the environment variables used by rustc wrapper

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#38221]
running rustbuild with --verbose prints the commands executed, but one cannot copy and run them manually, because the wrapper depends on various environment variables.

Thus the environment variables should also be printed out so one could set them and be able to run the wrapper manually.

**Comment by est31** [comment]
:+1: At least the relevant ones should be printed, like all the RUSTC_* ones.

**Comment by nagisa** [comment]
@nikomatsakis hit it as well. The most painless soln' would probably be something like `--shell-on-fail` flag which launches a shell with necessary variables set.
