### ISSUE TITLE
Unescaped HTML in unstable reason

### ISSUE THREAD

**Issue by jleedev** [rust-lang/rust#38220]
The docs for `FnBox` (https://doc.rust-lang.org/std/boxed/trait.FnBox.html) contain this line in the rendered output:

> will be deprecated if and when Box becomes usable

In the HTML source, this is the unescaped `Box<FnOnce>` instead of the escaped `Box&lt;FnOnce&gt;`.

**Comment by durka** [comment]
rustdoc needs to do the escaping. The reasons are also printed in error messages to the console.
