### ISSUE TITLE
Easy conversion between Result

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/rust#38235]
```rust
impl From<Result<T, E1>> for Result<T, E2> where E2: From<E1>
```

**Comment by sfackler** [comment]
This should be filed on https://github.com/rust-lang/rfcs

**Comment by Mark-Simulacrum** [comment]
To some extent, this is already possible: `Ok(res?)` will convert the error if a `From` implementation  for the is available. This would allow for a somewhat nicer form of that, though.

**Comment by Yamakaky** [comment]
Yeah, `res.into()` is cleaner.

**Comment by Yamakaky** [comment]
Closing for https://github.com/rust-lang/rfcs/issues/1813
