### ISSUE TITLE
Static variables are inlined when optimisations are enabled

### ISSUE THREAD

**Issue by aidanhs** [rust-lang/rust#38241]
Example (`#[start]` is used to slim the assembly):
```
#![feature(start)]
#[no_mangle]
pub static ABC: isize = 555;
#[start]
fn start(_argc: isize, _argv: *const *const u8) -> isize {
    ABC+1
}
```
https://is.gd/VxMUUu
Asm output from release mode:
```
	.text
	.intel_syntax noprefix
	.file	"rust_out.cgu-0.rs"
	.section	.text.main,"ax",@progbits
	.globl	main
	.p2align	4, 0x90
	.type	main,@function
main:
	mov	eax, 556
	ret
.Lfunc_end0:
	.size	main, .Lfunc_end0-main

	.type	ABC,@object
	.section	.rodata.ABC,"a",@progbits
	.globl	ABC
	.p2align	3
ABC:
	.quad	555
	.size	ABC, 8


	.section	".note.GNU-stack","",@progbits
```
Note that 556 has been inlined.

By comparison, C example using gcc:
```
int ABC = 555;
int main(int argc, char** argv) {
        return ABC+1;
}
```
Compiling to asm:
```
$ gcc -O2 -S x.c && cat x.s
        .file   "x.c"
        .section        .text.unlikely,"ax",@progbits
.LCOLDB0:
        .section        .text.startup,"ax",@progbits
.LHOTB0:
        .p2align 4,,15
        .globl  main
        .type   main, @function
main:
.LFB0:
        .cfi_startproc
        movl    ABC(%rip), %eax
        addl    $1, %eax
        ret
        .cfi_endproc
.LFE0:
        .size   main, .-main
        .section        .text.unlikely
.LCOLDE0:
        .section        .text.startup
.LHOTE0:
        .globl  ABC
        .data
        .align 4
        .type   ABC, @object
        .size   ABC, 4
ABC:
        .long   555
        .ident  "GCC: (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609"
        .section        .note.GNU-stack,"",@progbits
```
i.e. it loads from `ABC` each time (if `ABC` is made `static` in the C example it will inline, which is fine)

This is a direct contradiction of https://doc.rust-lang.org/beta/book/const-and-static.html#static

> Rust provides a ‘global variable’ sort of facility in static items. They’re similar to constants, but static items aren’t inlined upon use. This means that there is only one instance for each value, and it’s at a fixed location in memory.

and unhelpful if you want to edit symbol values in the binary after compilation and before running.

**Comment by nagisa** [comment]
The programs are not equivalent. The equivalent C program is

```
const int ABC = 555;
int main(int argc, char** argv) {
        return ABC+1;
}
```

which both clang and gcc inline as well.

Now the book certainly needs refinement. Namely what it states is correct in these cases:

* when static item is `static mut`;
* when the address of a static item is observed (i.e. `&ABC` will point to a memory in binary rather than a value on stack).

Otherwise, the compiler has no reason to avoid looking at the value of the static (since it is constant) and using its initial value to const-fold stuff.

**Comment by aidanhs** [comment]
Fair point about the equivalent C program.

> Now the book certainly needs refinement but I’m having a hard time finding a wrong interpretation of the current wording.

Well, it literally says "static items aren’t inlined upon use" under the "static" heading - I'm not sure how to get the correct interpretation (of this only being the case given your two bullet points) from there!

Can you clarify what you mean by the second point? Unless you do some magic, I'm pretty sure all statics will be memory in the binary, so isn't it always true? Ignoring the second point briefly, I'd propose that the sentence gets split to be more vague in the case of const statics and put the stronger guarantees under the "mutability" subheading.

**Comment by steveklabnik** [comment]
So, in my understanding, the key here is optimizations: logically speaking,
it is not inlined. But the optimizer may do what it wants. This is the same
as functions.

**Comment by aidanhs** [comment]
Is it worth noting that the optimizer may do odd things then? I generally wouldn't see the point of documenting the transformations an optimizer can do, but it feels like a direct contradiction to me - by comparison, the documentation for functions do not say that they won't be inlined. Here's a similar quote to the rust book, from the rust reference (https://doc.rust-lang.org/reference.html#static-items):

> A static item is similar to a constant, except that it represents a precise memory location in the program. A static is never "inlined" at the usage site, and all references to it refer to the same memory location.

"never" is a pretty strong statement.

----

Relatedly, but what do the participants of this thread think of this example?

```
#![feature(const_fn)]
#![feature(lang_items)]
#![feature(libc)]
#![feature(start)]
#![no_main]
extern crate libc;
use std::cell::UnsafeCell;
pub const ABC: UnsafeCell<i32> = UnsafeCell::new(555);
#[no_mangle]
pub extern fn main(_argc: i32, _argv: *const *const u8) -> i32 {
    unsafe { *ABC.get() = 560 };
    println!("ABC = {}", unsafe { *ABC.get() });
    0
}
#[lang = "eh_unwind_resume"]
#[no_mangle]
pub extern fn rust_eh_unwind_resume() {}
```
https://is.gd/hARIP8
Output:
```
ABC = 555
```

In the context of this quote from the reference:

> Statics may contain interior mutability through the UnsafeCell language item.

**Comment by nagisa** [comment]
> "never" is a pretty strong statement.

A program cannot observe value of constant static being inlined or not. That’s the primary thing. 

I do not think this issue is actionable past tweaking wording in documentation. Even moreso, if nobody can provide actual code that shows executable (without breaking all the invariants) observing a `static` (not `static mut`) being const-propagated or not.

> Relatedly, but what do the participants of this thread think of this example?

You’ve put the `UnsafeCell` into a `const`, not `static`. The 555 you see being output does not contradict the quote from the reference, since expression `ABC` always “inlines” in this case.

**Comment by aidanhs** [comment]
> I do not think this issue is actionable past tweaking wording in documentation. Even moreso, if nobody can provide actual code that shows executable (without breaking all the invariants) observing a static (not static mut) being const-propagated or not.

I'm not suggesting anything more than a doc tweak (now that the correct C equivalents have been pointed out to me).

One of the invariants is that the value in the static isn't changed between compile time and execution time (i.e. modifying a generated binary), but this may be so niche it's implicit - this is how I observed the inlining.

> You’ve put the UnsafeCell into a const, not static. The 555 you see being output does not contradict the quote from the reference, since expression ABC always “inlines” in this case.

You're right, I've no idea how I wrote `const` when I meant `static`, please ignore that example.

**Comment by aidanhs** [comment]
Just to be clear, now I've fixed my problem I don't really mind if you decide that modification between compilation and execution to be too niche to be worth altering the documentation for - feel free to close in that case.

**Comment by steveklabnik** [comment]
> I don't really mind if you decide that modification between compilation and execution to be too niche to be worth altering the documentation for - feel free to close in that case.

This is the path we're gonna take, thank you!
