### ISSUE TITLE
Buildbot failing due to a link error on arm-linux-androideabi

### ISSUE THREAD

**Issue by stjepang** [rust-lang/rust#38248]
PR #38192 was recently accepted, but didn't pass buildbot tests.
[build report](https://buildbot.rust-lang.org/builders/auto-linux-64-x-android-t/builds/11155)
[log contents](https://buildbot.rust-lang.org/builders/auto-linux-64-x-android-t/builds/11155/steps/test/logs/stdio)

The error is:
```
CANNOT LINK EXECUTABLE: cannot locate symbol "_ZN11collections5slice10merge_sort8collapse17hfd9d6022dd12b1bbE" referenced by "./collectionstest-b2ddd77ea87480bb"...

adb: error: remote object '/data/tmp/check-stage2-T-arm-linux-androideabi-H-x86_64-unknown-linux-gnu-collectionstest-b2ddd77ea87480bb.log' does not exist


command did not execute successfully: "adb" "pull" "/data/tmp/check-stage2-T-arm-linux-androideabi-H-x86_64-unknown-linux-gnu-collectionstest-b2ddd77ea87480bb.log" "/buildslave/rust-buildbot/slave/auto-linux-64-x-android-t/build/obj/build/tmp"
expected success, got: exit code: 1
```

Symbol `_ZN11collections5slice10merge_sort8collapse17hfd9d6022dd12b1bbE` is actually a function I introduced. It is a fn nested within another fn, and called from one place only.

**Comment by michaelwoerister** [comment]
cc me

**Comment by alexcrichton** [comment]
cc @rust-lang/compiler (in addition to @michaelwoerister)

**Comment by stjepang** [comment]
I should also note that, after some discussion over IRC, we decided to stick one `#[inline]` above that function. Hopefully that fixes the linker problem.

It's best to inline the function in this particular case anyway. By the way, the reason why the function was not getting inlined without explicit `#[inline]` is that that it was non-generic and called from a generic function.

**Comment by alexcrichton** [comment]
Buildbot's on its way out, and I think this was resolved, so closing.
