### ISSUE TITLE
A struct used as a bound is considered unused

### ISSUE THREAD

**Issue by KalitaAlexey** [rust-lang/rust#38242]
Hi.

I am not sure whether it is a bug.

For the following code:
```rust
struct Struct {}

trait Trait<T> {}

trait AnotherTrait {}

impl<T: Trait<Struct>> AnotherTrait for T {}

struct S<T> {
    t: T
}

impl S<Struct> {}

fn main() {}
```

The compiler shows that `Struct` is unused. I don't quite sure whether it is right.

**Comment by joshtriplett** [comment]
If you don't make the struct/trait public, so that some other module can take advantage of those definitions, then it seems accurate to describe them as unused.

**Comment by KalitaAlexey** [comment]
I agree. I just wanted to hear opinions.

**Comment by KalitaAlexey** [comment]
Yes. It is right behavior.
