### ISSUE TITLE
[parallel codegen] Windows linker failure

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#38254]
I can reproduce this on current master (7537f95), as well as a branch I have for the i128 PR (so its not a recent regression from the last 1-2 days...).

When I set codegen-units to 0 in config.toml, and start the build with `./x.py build -j 4`, the stage 0 compiler artifact build fails with:

```
build\x86_64-pc-windows-gnu\stage0-rustc\x86_64-pc-windows-gnu\release\deps\rustc_metadata-f72209e13ac87845.0.o:(.text+0x1491a): undefined reference to `rustc_metadata::index::_$LT$impl$u20$rustc_metadata..schema..LazySeq$LT$rustc_metadata..index..Index$GT$$GT$::iter_enumerated::_$u7b$$u7b$closure$u7d$$u7d$::hf7d447e1d3033d13'
collect2.exe: error: ld returned 1 exit status


error: aborting due to previous error

Build failed, waiting for other jobs to finish...
error: Could not compile `rustc_metadata`.
```

The VM has 4 threads. The error is not spurious, I could reproduce it for three times, without any try where I couldn't reproduce it.

When I set codegen-units back to the default of 1 it compiles successfully.

**Comment by est31** [comment]
cc @nrc I think I read somewhere that you are interested in parallel codegen regressions.

**Comment by alexcrichton** [comment]
cc @rust-lang/compiler

**Comment by michaelwoerister** [comment]
@alexcrichton Is `codegen-units=0` a meaningful value in Cargo?

**Comment by est31** [comment]
@michaelwoerister quoting config.toml.example:

```
# Number of codegen units to use for each compiler invocation. A value of 0
# means "the number of cores on this machine", and 1+ is passed through to the
# compiler.
```

**Comment by michaelwoerister** [comment]
@est31 Thanks for the info! I'll try to reproduce the problem. Did you encounter this on other platforms too?

**Comment by est31** [comment]
No, did the same on linux, not reproducible there.

**Comment by michaelwoerister** [comment]
I can reproduce this with MinGW64. With MSVC, I don't get an error, so this is probably related to the MinGW linker somehow.

**Comment by Manishearth** [comment]
Similar link issue caused by codegen units in https://github.com/rust-lang/rust/issues/38938 . On linux.

**Comment by michaelwoerister** [comment]
I cannot reproduce this anymore with current master (possibly because of #38822).

**Comment by Manishearth** [comment]
@bholley does bumping the nightly date on servo fix this?

**Comment by michaelwoerister** [comment]
I'm not sure that change has made it into the latest nightly yet.

**Comment by SimonSapin** [comment]
@Manishearth [Yes](https://github.com/rust-lang/rust/issues/38938#issuecomment-272308636).

**Comment by michaelwoerister** [comment]
@est31 Can you confirm that this is fixed?

**Comment by est31** [comment]
@michaelwoerister I'm giving it a try...

**Comment by est31** [comment]
Mhh I can't reproduce it either on commit 05383b2765fe6bb38ecf5f74f1b2d9bdf55df894 with the `rustc_metadata` crate. Most likely something in the code changed and it now doesn't trigger the bug anymore. IDK, as it can't be reproduced anymore I'm fine with closing the issue (if the underlying issue pops up again, maybe time for a new report...).
