### ISSUE TITLE
configure message re: rustbuild assumes curr dir is source dir

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#38251]
If you build rust out of tree, the configure script currently prints a message:

```
onfigure: NOTE you have now configured rust to use a rewritten build system
configure:      called rustbuild, and as a result this may have bugs that 
configure:      you did not see before. If you experience any issues you can
configure:      go back to the old build system with --disable-rustbuild and
configure:      please feel free to report any bugs!
configure: 
configure: run `python x.py --help`
```

The problem is that if I am running `configure` in a directory other than the root of the source directory, then the instruction to run `python x.py --help` will not work.

Furthermore, as a user who has often encountered software not supporting out-of-tree builds, when I encounter a message like that, my first instinct is to assume that *this* software does not support out of tree builds.

I recommend that the configure script detect whether the current directory is not the root of the Rust source directory, and if so, use `${CFG_SRC_DIR}/x.py` as the path to the python script instead of just `x.py`.

**Comment by pnkfelix** [comment]
cc @alexcrichton

**Comment by petrochenkov** [comment]
It probably makes sense to just copy `x.py` into the build directory on first run so it could be invoked without any prefixes.

**Comment by pnkfelix** [comment]
@petrochenkov oh indeed that may make sense, since I just noticed that the `Makefile.in` also assumes that `x.py` is present in the build directory...
