### ISSUE TITLE
llvm/msvc: line table entries for source lines that do not generate code

### ISSUE THREAD

**Issue by xanlpz** [rust-lang/rust#38263]
There are examples of source lines which will not generate any code (for example an alignment statement that matters for its side effects). LLVM will generate an entry in the line table for this, pointing to the correct source line but with a PC that is most likely a duplicate (of the previous or next line which actually does generate code). This is bound to confuse the debugger.

To fix this properly we'd need to go from line entries to generated code and get rid of those without the latter. Otherwise just by static analysis of the PC we could get rid of duplicates but wouldn't be able to know which source line is the right one to have in the CodeView data.

(cc @michaelwoerister)

**Comment by steveklabnik** [comment]
Triage: no idea what the status of this ticket is.
