### ISSUE TITLE
? is an operator!

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#38270]
This code is wrong:

```
fn main() {
    let x = 3
}
```

It gives an error message: 

```
expected one of `.`, `;`, `?`, or an operator, found `}`
```

The problem: `?` is an operator, so its mentioned twice in that list.

**Comment by est31** [comment]
cc #31436

**Comment by nagisa** [comment]
> The problem: ? is an operator, so its mentioned twice in that list.

`?` is not an operator as far as parser is concerned just like unary `-` or binary `.` is not an operator but an inherent part of a literal and expression grammar respectively. I’m dubious this will be easy to fix.

**Comment by Stebalien** [comment]
An easy fix would be to say "or a binary operator".
