### ISSUE TITLE
rustbuild: Unrecognized option: 'filter'

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#38275]
The option `--filter testname` for running specific tests is documented in [CONTRIBUTING.md](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) and [bootstrap/README.md](https://github.com/rust-lang/rust/blob/master/src/bootstrap/README.md).

There's one problem however, this option doesn't exist!
```
$ ../x.py test src/test/run-make --filter graphviz
    Finished debug [unoptimized] target(s) in 0.0 secs
failed to parse options: Unrecognized option: 'filter'.
Usage: x.py test [options] [<args>...]
```

The correct invocation uses highly unobvious `--test-args` instead of `--filter`:
```
../x.py test src/test/run-make --test-args graphviz
```
I'd never guess it without some digging through the source code, it's very surprising to me that people somehow use rustbuild for some time but nobody still reported this.

**Comment by petrochenkov** [comment]
It turns out `x.py test --help` mentions `--test-args`, but it still doesn't tell what it does.

**Comment by durka** [comment]
`x.py test --help` also says you can simply pass the filename of a specific test but it's not true. Documentation shouldn't be wishful thinking.

**Comment by alexcrichton** [comment]
Ah I renamed `--filter` at the last minute to `--test-args` and forgot to update the docs, should be an easy patch!

@petrochenkov would you like to send a PR to update the docs? 

Note that the `--test-args` argument acts the same was as `rustdoc --test-args`, it just passes arguments to the test harness.
