### ISSUE TITLE
Default to codegen-units=NUM_CORES for non-release builds

### ISSUE THREAD

**Issue by bholley** [rust-lang/rust#38276]
This saves 10-20% on debug builds of the servo script crate, which seems worthwhile.

CC @nikomatsakis @alexcrichton

**Comment by alexcrichton** [comment]
We haven't turned this on by default in the past but I don't think we've had a *huge* amount of motivation not to, we just haven't gotten around to doing so.

Some thoughts though that we may wish to consider before doing so:

* It's historically been unclear that this is a universal win, and may regress some cases (we should investigate)
* This is a further point of divergence between release and debug builds, which may be a source of bugs.
* Currently the compiler has no "jobserver" support, meaning parallel Cargo builds could accidentally and quickly overload the system.

I'd personally be in favor of doing this, however.

**Comment by Yamakaky** [comment]
It's not compatible with LTO, so maybe ignore the `codegen-units` setting when building with LTO enabled?

**Comment by bholley** [comment]
Is LTO ever used for non-release builds?

**Comment by Yamakaky** [comment]
Yeah, right, sorry

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/39037. I think that ultimately, making this the default is possibly something we want, but adding support for the compiler figuring out what the number is is a good first start; we can then proceed to making it the default if we want, though I think the wins from this will hopefully be lessened with time -- incremental comp. already generates lots of codegen units.
