### ISSUE TITLE
rustdoc: show the compilation environment in the doc

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/rust#38287]
A lot of crates use conditional compilation using features and `cfg(unix)`. It would be interesting to indicate in the generated doc which environment was used for the compilation. Maybe a link in the header/footer.

**Comment by steveklabnik** [comment]
Triage: no changes.

**Comment by jyn514** [comment]
There is `doc(cfg)` - would that meet your use case? https://github.com/rust-lang/rust/issues/43781
