### ISSUE TITLE
[rustbuild] python x.py test --stage 1 builds stage0 test stuff

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#38288]
```
Building stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
<snip>
Building stage0 tool tidy (x86_64-unknown-linux-gnu)
   Compiling tidy v0.1.0 (file:///home/nagisa/Documents/rust/rust/src/tools/tidy)
    Finished debug [unoptimized] target(s) in 1.53 secs
tidy check stage0 (x86_64-unknown-linux-gnu)
<snip>
Building stage0 test artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling getopts v0.0.0 (file:///home/nagisa/Documents/rust/rust/src/libgetopts)
   Compiling term v0.0.0 (file:///home/nagisa/Documents/rust/rust/src/libterm)
   Compiling test v0.0.0 (file:///home/nagisa/Documents/rust/rust/src/libtest)
   Compiling test_shim v0.1.0 (file:///home/nagisa/Documents/rust/rust/src/rustc/test_shim)
    Finished debug [unoptimized] target(s) in 4.84 secs
Building stage0 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   ....
```
Why is it building unnecessary stuff?

**Comment by alexcrichton** [comment]
Could you clarify what you mean by "test stuff"? It's not 100% clear what you're referring to in the paste above. What's there though is explained by:

> Building stage0 std artifacts

Testing stage1 requires stage0 to be compiled, so this is just a routine part of creating the stage1 compiler.

> Building stage0 tool tidy

Running all tests runs tidy, and tidy is always compiled at stage0.

> Building stage0 test artifacts

Like the standard library, this is just a routine "compile the stage0 artifacts" routine. The compiler uses crates like test, getopts, etc.

> Building stage0 compiler artifacts

This is just a routine "compile the compiler". These artifacts become the stage1 compiler.
