### ISSUE TITLE
The Book's examples should consistently use stderr for error messages

### ISSUE THREAD

**Issue by zackw** [rust-lang/rust#38303]
Some of The Book's examples use `println!` to emit error messages.  This is wrong; `println!` writes to stdout; error messages should always be written to stderr.

For instance (from https://doc.rust-lang.org/book/error-handling.html#parsing-integers)

```
use std::num::ParseIntError;

fn double_number(number_str: &str) -> Result<i32, ParseIntError> {
    match number_str.parse::<i32>() {
        Ok(n) => Ok(2 * n),
        Err(err) => Err(err),
    }
}

fn main() {
    match double_number("10") {
        Ok(n) => assert_eq!(n, 20),
        Err(err) => println!("Error: {:?}", err),
    }
}
```

Here `println!("Error: {:?}", err)` should be something like `writeln!(io::stderr(), format!("Error: {:?}", err))`.  (Please forgive me if I've got that wrong - I'm just barely starting to use the language, and I've not yet properly learned the I/O libraries.)

(That's a lot of extra typing. Perhaps there should be an `eprintln!()`?)

**Comment by steveklabnik** [comment]
The book is no longer being actively developed; we're working on the second edition over here: https://github.com/rust-lang/book In particular, this text is not used there. If someone would like to send in some kind of patch for this, we can discuss it there, but I'm also not sold on the additional complexity, as you've noted.

Anyway, thanks for filing, but we shouldn't keep an issue open for it.
