### ISSUE TITLE
Translation of Rust error messages into Chinese

### ISSUE THREAD

**Issue by KiChjang** [rust-lang/rust#38316]
There has been increasing numbers of users in the Chinese Rust community, and we'd like to support them better by having a translated Chinese version of the error message index as a first step.

cc @wayslog @tennix @3442853561 @steveklabnik @erickt

**Comment by steveklabnik** [comment]
This is going to be a massive, massive undertaking that will certainly need an RFC. Could you open an issue over there please? Thanks!

**Comment by 3442853561** [comment]
It is necessary to make a localized compiler now. I'm in.
