### ISSUE TITLE
rustbuild builds docs for too many crates

### ISSUE THREAD

**Issue by ollie27** [rust-lang/rust#38319]
The Makefiles only build the docs for:

```
std
alloc
collections
core
libc
rustc_unicode
```

I assume `alloc`, `collections` and `rustc_unicode` are included mostly so the src links in `std` work. I'm not sure why `libc` is included though...

Anyway, with rustbuild it builds all of these:

```
core
compiler_builtins
rand
libc
rustc_unicode
alloc
unwind
panic_abort
alloc_system
panic_unwind
collections
std
std_shim

getopts
term
test
test_shim
```

Most of these are implementation details of `std` so shouldn't be included. The `test` docs are a big problem because of the same issue as #34800, generating them means the search index will get overridden.

**Comment by steveklabnik** [comment]
I'd say it's a bit more complex than that: we do want the ability to build these docs, but don't currently include them in the releases.

**Comment by alexcrichton** [comment]
I'm going to preemptively tag this as a regression as it'll soon become one. I suspect we can fix this by just disabling rustdoc in Cargo.toml for a bunch of crates. Should be an easy thing to knock out!

**Comment by bluss** [comment]
Nightly docs may show effect of this? Search index only contains getopts, term, test crates. See example: https://doc.rust-lang.org/nightly/std/index.html?search=Vec

**Comment by ollie27** [comment]
Yeah, I figured that might happen. I've submitted a small PR to fix that: #38398.

**Comment by ollie27** [comment]
This needs to be reopened. Unfortunately #38658 didn't work, it only disabled docs for `std_shim`.

**Comment by bluss** [comment]
Still a stable → beta regression in the sense that the currently hosted beta rustdoc shows documentation for too many, crates like for example `alloc_system` and `unwind` (and more).

**Comment by alexcrichton** [comment]
Yes sorry @ollie27 I've been meaning to get around to reopening this. I suspect that there's a Cargo bug lurking here as to why we're building too much crate documentation.

@ollie27 do you want to send a PR to just explicitly pass `-p std -p collections ...` to explicitly whitelist crates we're documenting? We can worry about fixing the Cargo bug later.
