### ISSUE TITLE
"did you mean" for misusing a field as a method is misleading

### ISSUE THREAD

**Issue by whitequark** [rust-lang/rust#38321]
The error is currently:
```
error: no method named `src_addr` found for type `&wire::ipv4::Repr` in the current scope
   --> src/wire/ipv4.rs:409:34
    |
409 |         packet.set_src_addr(self.src_addr());
    |                                  ^^^^^^^^
    |
note: did you mean to write `self.src_addr`?
   --> src/wire/ipv4.rs:409:34
    |
409 |         packet.set_src_addr(self.src_addr());
    |                                  ^^^^^^^^
```
which is of course absurd.

To reproduce:
```rust
struct Foo {
    src_addr: usize
}

fn main() {
    let foo = Foo { src_addr: 10 };
    foo.src_addr()
}
```

**Comment by KalitaAlexey** [comment]
Why is it misleading?

**Comment by frewsxcv** [comment]
@whitequark Can you share the project where you encountered this error?

**Comment by whitequark** [comment]
> Why is it misleading?

Because it suggests to write the same thing as is already written.

**Comment by frewsxcv** [comment]
> > Why is it misleading?
> 
> Because it suggests to write the same thing as is already written.

The suggestion is telling you to write `self.src_addr` instead of `self.src_addr()`, since there is presumably a *field* (not a *method*) on your structure called `src_addr`.

**Comment by whitequark** [comment]
> The suggestion is telling you to write self.src_addr instead of self.src_addr(), since there is presumably a field (not a method) on your structure called src_addr.

It points to `src_addr` (not `src_addr()` and suggests to write `src_addr`). This makes no sense. It should at least highlight the parens so that it points to `src_addr()`.

**Comment by whitequark** [comment]
I've added a minimal repro to the issue text.

**Comment by whitequark** [comment]
Also, ideally it would highlight the entire `self.src_addr()` expression, not just the single token, since that's what it talks about in the error anyhow.

**Comment by KalitaAlexey** [comment]
I've got. It's a span problem.

**Comment by TheZoq2** [comment]
I just ran into this aswell. I agree that it would be more clear if it highlighted the whole `src_addr()` instead of just `src_addr` but adding a note saying something along the lines of 

```
There is no method called src_addr, did you mean to access the field src_addr?
```
Would be even more helpfull

**Comment by zackmdavis** [comment]
Yes, I found this confusing, too. I should submit a PR to fix this tomorrow (have code fix, but still need to correct compile-fail test expectations, but even more than that, need to sleep).

**Comment by zackmdavis** [comment]
okay, not literally tomorrow, but soon
