### ISSUE TITLE
Implicit returns with multiple #cfg[...] cause compilation errors

### ISSUE THREAD

**Issue by Susurrus** [rust-lang/rust#38337]
If there are two different #cfg[...] one after each other and they utilize implicit returns (don't have a trailing ';'), then a compilation error will occur.

Example of the error: https://is.gd/fiScoc
Fixed: https://is.gd/Z87TE0

I believe this is a compiler bug because in the fixed version there's still an implicit return as part of the last #cfg[...] and there isn't an error about it.

**Comment by sinkuu** [comment]
Attributes can be applied to expression, not only statements.

```rust
/* #[cfg(unix)]    */ return Ok("unix".to_string());
/* #[cfg(windows)] */ Ok("windows".to_string())
```

is syntactically valid, while this is not:

```rust
/* #[cfg(unix)]    */ Ok("unix".to_string())
/* #[cfg(windows)] */ Ok("windows".to_string())
```

**Comment by cyplo** [comment]
Still a problem on rustc 1.23.0-nightly (8b22e70b2 2017-10-31)

**Comment by Mark-Simulacrum** [comment]
This seems like expected behavior to me so I'm going to go ahead and close. Expressions can't be adjacent like this without some separator in general (and cfg is after parsing, not before/during).
