### ISSUE TITLE
https://doc.rust-lang.org/stable/book/syntax-index.html doesn't mention `?`

### ISSUE THREAD

**Issue by sgrif** [rust-lang/rust#38333]
Hi @steveklabnik. https://www.reddit.com/r/rust/comments/5hwx3d/writing_an_interpreter_in_rust/db4cre6/

**Comment by durka** [comment]
Fixed in nightly.

**Comment by steveklabnik** [comment]
Ah yes, seems @durka is right. Thanks @sgrif ! ❤️
