### ISSUE TITLE
Compilation does not end.

### ISSUE THREAD

**Issue by kotarou777775** [rust-lang/rust#38335]
I tried a recursive function like Continuation-passing style.

I tried this code
```
use std::ops::Fn;

fn fact<F>(n: i64, f: F) -> i64 
    where F: Fn(i64) -> i64 {

    match n {
        1 => f(1),
        _ => fact(n-1, |x|{f(n * x)}),
    }
}
fn main(){
    let v = fact(5, |x|{x});
    println!("{:?}", v);
}
```

I expected  the compilation would end or to see some compilation error, but the compilation is never finished without any error.  
I made it simpler.
```
use std::ops::Fn;

fn rec<F>(f: F) -> i64 
    where F: Fn(i64) -> i64 {
    rec(|x|{f(x)})
}
fn main(){
    let _ = rec(|x|{x});
}
```
It also happened same problem.  
Would you tell me why this problem has occured ?

## Meta

rustc 1.13.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-apple-darwin
release: 1.13.0

**Comment by xor** [comment]
I was able to reproduce this on linux64, with same rustc version.

I had this output and then the process just used up 100% CPU until killed.

> [xor@localhost rust]$ rustc test.rs 
warning: function cannot return without recurring, #[warn(unconditional_recursion)] on by default
 --> test.rs:3:1
  |
3 | fn rec<F>(f: F) -> i64 
  | ^
  |
note: recursive call site
 --> test.rs:5:5
  |
5 |     rec(|x|{f(x)})
  |     ^^^^^^^^^^^^^^
  = help: a `loop` may express intention better if this is on purpose

**Comment by aturon** [comment]
cc @eddyb

**Comment by eddyb** [comment]
I think this is a duplicate. cc @rust-lang/compiler

**Comment by Mark-Simulacrum** [comment]
Possibly fixed? I get the following when trying to compile:
```
warning: function cannot return without recurring, #[warn(unconditional_recursion)] on by default
 --> <anon>:3:1
  |
3 |   fn rec<F>(f: F) -> i64
  |  _^ starting here...
4 | |     where F: Fn(i64) -> i64 {
5 | |     rec(|x|{f(x)})
6 | | }
  | |_^ ...ending here
  |
note: recursive call site
 --> <anon>:5:5
  |
5 |     rec(|x|{f(x)})
  |     ^^^^^^^^^^^^^^
  = help: a `loop` may express intention better if this is on purpose

error: reached the type-length limit while instantiating `rec::<[closure@<anon>:5:9: 5:18 f:&[closure@<anon>:5:9: 5:18 f:&...`
 --> <anon>:3:1
  |
3 |   fn rec<F>(f: F) -> i64
  |  _^ starting here...
4 | |     where F: Fn(i64) -> i64 {
5 | |     rec(|x|{f(x)})
6 | | }
  | |_^ ...ending here
  |
  = note: consider adding a `#![type_length_limit="2097152"]` attribute to your crate

error: aborting due to previous error
```

**Comment by nikomatsakis** [comment]
The latter error (reached the type-limit) was the fix to this problem. Closing.
