### ISSUE TITLE
`Iterator::sum()/product()` maybe likely overflow, and panic

### ISSUE THREAD

**Issue by liigo** [rust-lang/rust#38343]
`Iterator::sum()` maybe likely overflow, and panic:

```
    let values = [126u8, 127, 128];
    let sum: u8 = values.iter().sum(); // panicked at 'attempt to add with overflow'
    println!("sum = {}", sum);
```

In this example code, `sum()` must returns type `u8`. But the sum of many `u8` values in iterator, may be likely out of range of type `u8`. 

Similar thing occurs to `Iterator::product()`.

cc https://github.com/rust-lang/rust/pull/38041

**Comment by leonardo-m** [comment]
So do you/we want other functions similar to Iterator::sum() and product() that return an Option<>?

**Comment by liigo** [comment]
I want to get a sum of type `u64`: `let sum: u64= [126u8, 127, 128].iter().sum();`

**Comment by Ms2ger** [comment]
`[126u8, 127, 128].iter().map(|x| x as u64).sum()` should work.

**Comment by liigo** [comment]
`[126u8, 127, 128].iter().fold(0u64, |a,b| a+(*b as u64))` should work. (i.e. don't use `sum`).

**Comment by alexcrichton** [comment]
This is [documented behavior](https://doc.rust-lang.org/std/iter/trait.Iterator.html#panics-3) of the methods:

> When calling sum and a primitive integer type is being returned, this method will panic if the computation overflows and debug assertions are enabled.

(closing as a result)

**Comment by glennpratt** [comment]
Implementing sum or product where the result is a larger type seems like it would be very valuable.

Sum or product on bytes (u8) will easily overflow, making the methods fairly useless unless I'm misunderstanding something.

**Comment by Ms2ger** [comment]
It doesn't do anything else than any other mathematical operation. Why are you doing mathematics on `u8` anyway?

**Comment by glennpratt** [comment]
Just implementing a toy program trying to familiarize myself with iterators. But one could also ask why does `impl<'a> Product<&'a u8> for u8` exist?

**Comment by glennpratt** [comment]
This is what I tried to do before I jumped to google:

```rust
5 |         let product = window.iter().product::<i32>();
  |                                     ^^^^^^^ the trait `std::iter::Product<&u8>` is not implemented for `i32`
```

**Comment by kantuni** [comment]
```rust
[126u8, 127, 128].iter().map(|x| *x as u64).sum()
```
did the job for me.
