### ISSUE TITLE
How is Python3 unsupported?

### ISSUE THREAD

**Issue by lethargilistic** [rust-lang/rust#38358]
I've gone through the project's Python code, using pylint and sight, and I cannot find anywhere that Python3 was not accounted for explicitly. I was able to build Rust while using a Python3 virtualenv, although since I don't know the exact purpose of all the Python code, I can't be sure how and when it's all called, so that may or may not be evidence.

Is there a known reason behind why Python3 isn't officially supported? A dependency that is only Python2, perhaps?

**Comment by nagisa** [comment]
It is unsupported in sense that landing python code is not gated on it working with python3. Otherwise people do build rustc with python3 (everybody on Arch, for example) and quickly fix the issues that arise.

**Comment by lethargilistic** [comment]
Well, if you expect it to break for users and then be fixed, I don't see why you don't gatekeep and have it supported before merging, but it's not a gigantic problem in the long run.

**Comment by AraHaan** [comment]
Better idea have each module as base to check python version and then either import the python 2 versions, or the Python 3.x ones to avoid any syntax errors from python. This is how I do it all the time, yes it will Add a ton more files but the build system would worth for python Python Versions.

The way you can do it is

```py
import sys
PY3X = sys.version_info >= (3, 0)
if PY3X:
    # import python 3.x version of this module.
else:
    # import python 2.x version of this module.
```

And then this would avoid any conflicts compiling from the 2 versions.

**Comment by nfnty** [comment]
@AraHaan No, the other way around; always make Python 3 the general case and Python 2 the exception.

**Comment by lethargilistic** [comment]
Doubling up the files like that isn't necessary.

The most any of the files in question needed to do was account for xrange or print functions. This is part of why I thought it was weird that Python2 was the only one with official support. Adding Python3 couldn't have been hard.

--Mike Overby



On Wed, Dec 14, 2016 at 5:20 PM -0500, "nfnty" <notifications@github.com<mailto:notifications@github.com>> wrote:


@AraHaan<https://github.com/AraHaan> No, the other way around; always make Python 3 the general case and Python 2 the exception.

**Comment by petrochenkov** [comment]
@nagisa 
>Otherwise people do build rustc with python3 (everybody on Arch, for example) and quickly fix the issues that arise.

How do they deal with LLVM build system requiring Python 2.7?
