### ISSUE TITLE
Add Appveyor as PR hook

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/rust#38364]
Currently, we only have the travis build which misses Windows. As it's a first-tier supported platform, it would be good to be able to spot problems earlier.

**Comment by nagisa** [comment]
No we do not have only travis and nothing is prevented from landing by Travis either. Our proper buildbots are [here](https://buildbot.rust-lang.org/) (though that might change in near future), and among other targets, there’s various configurations of windows.

**Comment by Yamakaky** [comment]
Is it run for each PR? If yes, having it displayed as a github check would be great.

**Comment by steveklabnik** [comment]
Travis is run for each PR, but it's not even a full run, it's just there to do an initial smoke test. Windows is absolutely fully tested on each merge, just like all other tier 1 platforms. Basically:

1. PR opened
2. Travis runs, shows green
3. Someone says "r+"
4. Goes into homu's queue
5. When it hits the top of the queue, all tests for all platforms are run via buildbot
6. if successful, bors merges.

I'm not sure adding more pre-check is really worth it, but maybe @rust-lang/compiler feels differently?

**Comment by alexcrichton** [comment]
Yes unfortunately we don't have the infrastructure capacity to run AppVeyor on Windows right now, so we aren't able to enable this for PR. We can perhaps one day set up a bot to cross compile from Linux to Windows to at least check it compiles, but that's more of a longer-term option.
