### ISSUE TITLE
Should accept positional arguments after flags

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#38373]
Consider a command line invocation like this:

```
python x.py test --stage 1 --target=x86_64-unknown-linux-gnu 
```

It has the most commonly edited arguments somewhere middle in the command line, and the least edited – on the sides. Instead I would, so editing the command would be very quick:

```
python x.py --target=x86_64-unknown-linux-gnu --stage 1 test
```

but it fails with an error:

```
unknown command: --stage
Usage: x.py --stage [options] [<args>...]
```

(unrelatedly, it seems like its usage is also kinda wrong)

**Comment by CleanCut** [comment]
If my PR is accepted, then this is fixed. ;-)

**Comment by Mark-Simulacrum** [comment]
Based on testing today, this is fixed -- closing.

**Comment by CleanCut** [comment]
:-)
