### ISSUE TITLE
Dynamic library, OSX, Segmentation fault

### ISSUE THREAD

**Issue by adjivas** [rust-lang/rust#38370]
Durring a test on Linux and OSX, I have found a [SegV for OSX system](https://travis-ci.org/adjivas/share/jobs/184018623#L112) for this [code of demonstration](httpshttps://github.com/adjivas/share/tree/7dcd3f9e4ad939e5b255559a01687de0263c9571/src/main.rs).

According to my observations, the accident happend when the *dlclose*(3)'s function is called for a dynamic crate named [hello](https://travis-ci.org/adjivas/share/jobs/181199573#L111) is used without the *nostd* mode, it's why in my report a simple [*println*](https://travis-ci.org/adjivas/share/jobs/181199573#L111)!'s will cause a Segv. 

I tried this code:
hello/src/lib.rs
```rust
#[no_mangle]
pub unsafe extern "C" fn start(common: *mut Segment) {
println!("This println cause de SegV when the dylib is closed");
...
```
src/main.rs
```rust
...
assert_ne!(libc::dlclose(handle), -1);
```

I expected to see this happen: [5763 Segmentation fault: 11](https://travis-ci.org/adjivas/share/jobs/184018623#L112)

The rust-lldb trace:
```shell
(lldb) run
Process 5350 launched: '/Users/adjivas/Repos/share/target/debug/share' (x86_64)
This println cause de SegV when the dylib is closed
cProcess 5350 stopped
* thread #1: tid = 0x244c60, 0x000000010122ab80, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10122ab80)
    frame #0: 0x000000010122ab80
error: memory read failed for 0x10122aa00
```

**Comment by alexcrichton** [comment]
IIRC this is the same as https://github.com/nagisa/rust_libloading/issues/5 and a dupe of https://github.com/rust-lang/rust/issues/28794

**Comment by alexcrichton** [comment]
Er didn't mean to close, I'm not 100% sure! If it is the same though, feel free to close!

**Comment by adjivas** [comment]
It's exactly the same issue of [#28794](https://github.com/rust-lang/rust/issues/28794), it's why I close this.
