### ISSUE TITLE
 Nice PR comment but no commit message body — ¿por qué no los dos?

### ISSUE THREAD

**Issue by LemmingAvalanche** [rust-lang/rust#38379]
(So this is just me being a stickler for VCS practices because I don’t have the Elisp chops to contribute code to this project (yet).)

I’ve seen many pull requests (PRs) with nice comments on them. But then I see the commit message (in the case when the PR consists of just one commit), and it turns out that it has no *body* (only a *summary line*). I wonder, why don’t more people just duplicate the PR comment to the commit message body (or vice versa)? Again, in the case when the PR consists of a single commit.

In some cases a commit message does not need a body. But if one has written a PR comment, then that strongly suggests (in my opinion) that having a commit message body would improve the commit.

Another argument is that GitHub will automatically duplicate the commit message body to the PR comment, if the PR is just a single commit. So at least if you write the *description* for the change that you are requesting a pull for pre-PR, you don’t even have to manually copy-and-paste. ☺

On the other hand, there are some cases where a PR comment makes sense, while it wouldn’t necessarily make sense to duplicate it to the commit message. Maybe the comment is pretty specific to the pull request, while not being relevant to the commit itself. In other words, maybe the PR comment would be out-of-place as an entry in `git log`.

What do you guys think?

**Comment by Mark-Simulacrum** [comment]
Both PR bodies and titles go into the commit log, so often I think this is a matter of the PR comment being written once the changes are done (or ready for review) instead of at commit time.

**Comment by LemmingAvalanche** [comment]
@Mark-Simulacrum Yep, you’re right.

It turns out that I posted this to the wrong project. ☺ Sorry about the noise!

https://github.com/syl20bnr/spacemacs/issues/7969
