### ISSUE TITLE
Referencing fn pointers with associated types of references ICEs

### ISSUE THREAD

**Issue by sgrif** [rust-lang/rust#38381]
Example reproduction script:

```rust
use std::ops::Deref;

fn main() {
    let x: fn(&i32) -> <&i32 as Deref>::Target = unimplemented!();
}
```

**Comment by mzji** [comment]
Looks like this is fixed by #38375 . @petrochenkov ?

**Comment by petrochenkov** [comment]
No, this is some other older issue, it happens on stable already.

**Comment by mzji** [comment]
Oh. Thanks for the explain @petrochenkov 😄

**Comment by Mark-Simulacrum** [comment]
This no longer ICEs. E-needstest.
