### ISSUE TITLE
Cargo broken on Windows in all releases since 2016-12-06

### ISSUE THREAD

**Issue by FlaShG** [rust-lang/rust#38385]
After doing `rustup update` while on the nightly channel, cargo started crashing on my machine immediately upon being started. When started through cmd, an error window popped up saying
```
The application was unable to start correctly (0xc000007b).
```
I tested different releases and my results were as following.

**Not broken**
* stable-x86_64-pc-windows-gnu (at the time of writing)
* nightly-2016-12-04-x86_64-pc-windows-gnu 
* nightly-2016-12-05-x86_64-pc-windows-gnu

**Broken**
* nightly-2016-12-06-x86_64-pc-windows-gnu 
* nightly-x86_64-pc-windows-gnu (at the time of writing)
* beta-2016-12-10-x86_64-pc-windows-gnu
* beta-x86_64-pc-windows-gnu (at the time of writing)

rustc is working fine in all releases, it seems to be only cargo itself that is causing problems.

My system is running Win10.
I'll provide more information if needed.

**Comment by snuk182** [comment]
Duplicate of https://github.com/rust-lang/cargo/issues/3384 ?

**Comment by FlaShG** [comment]
Looks like it - I didn't search for the issue in the correct repository it seems.
