### ISSUE TITLE
fn pointers taking references are not `Clone`

### ISSUE THREAD

**Issue by sgrif** [rust-lang/rust#38382]
The type `fn(&'a T)` implements `Clone`, while `fn(&T)` does not. This presumably applies to more traits than just `Clone`.

**Comment by stjepang** [comment]
This is probably related to #28229

**Comment by petrochenkov** [comment]
More like https://github.com/rust-lang/rust/issues/24000

The problem can probably be mitigated in practice to some extent by manually implementing fn pointer traits for a few most common cases involving references.
The place to add impls is [here](https://github.com/rust-lang/rust/blob/master/src/libcore/ptr.rs#L756).

**Comment by sgrif** [comment]
Yes, I agree. I did check that adding 

```rust
fnptr_impls_safety_abi! { extern "Rust" fn($(&$Arg),*) -> Ret, $($Arg),* }
```

compiles successfully. It does (e.g. no coherence issues). I didn't confirm whether it solved the problem I was encountering though.

**Comment by cjgillot** [comment]
This was fixed a long time ago.
