### ISSUE TITLE
3 line ICE on stable and nightly (Unexpected type in full type resolver)

### ISSUE THREAD

**Issue by tupshin** [rust-lang/rust#38404]
the following generates a compiler error on all current versions:
```
trait A<T>: std::ops::Add +Sized  {}
trait B<T>: A<T> {}
trait C<T>: A<B<T, Output = usize>> {}
```
RUST_BACKTRACE hangs for me, but emits:
`error: internal compiler error: ../src/librustc/infer/resolve.rs:132: Unexpected type in full type resolver: FreshTy(0)
`
https://is.gd/lkcWgT

This is greatly cut down from a real world example, and a blocking issue for me

**Comment by est31** [comment]
This is a regression of the `1.4.0` release of rust.

**Comment by nikomatsakis** [comment]
triage: P-medium

Pretty old regression, barely qualifies. =) However, @arielb1 says he has a fix.

**Comment by est31** [comment]
Oh sorry, disregary my comment above, the issue is reproducible on 1.3.0 as well as on stable 1.0.0. Its not a regression, at least not one from a stable rust release.
