### ISSUE TITLE
Borrow checker initiating borrow too soon

### ISSUE THREAD

**Issue by Xaeroxe23** [rust-lang/rust#38416]
Consider the following code:

```rust
fn main() {
    let mut my_foo = Foo::new();
    my_foo.set_bar(my_foo.get_bar() + 1); // Doesn't compile.

    let current_bar = my_foo.get_bar(); // This compiles just fine.
    my_foo.set_bar(current_bar + 1);
}

struct Foo {
    bar : i32
}

impl Foo {
    fn new() -> Foo {
        Foo{bar:0}
    }

    fn set_bar(&mut self, value : i32) {
        self.bar = value;
    }

    fn get_bar(&self) -> i32 {
        self.bar
    }
}
```

The first line does not compile due to error E0502 "cannot borrow 'my_foo' as immutable because it is also borrowed as mutable"

I expected the first line to compile just fine because execution of set_bar() cannot begin until execution of get_bar() is complete.

There may be something I'm missing here and some very good reason that line has to be expanded to the second form, which does compile, but it is not immediately obvious to me why the first form --which is cleaner syntax in my opinion-- does not compile.

**Comment by steveklabnik** [comment]
This is a well-known issue. You're right that the borrow checker is being too conservative here. I think it's distinct from non-lexical lifetimes, but I'm not 100% sure. I don't have the time right now to be able to find the duplicate issue, so I won't close it now, but maybe someone else can.

**Comment by Xaeroxe23** [comment]
Great!  I did a quick search for similar issues before posting this but I couldn't find any such issue.

**Comment by Xaeroxe23** [comment]
Ah found it.  Closing this

https://github.com/rust-lang/rust/issues/34035
