### ISSUE TITLE
`make tidy` trips over Emacs lockfile with opaque message

### ISSUE THREAD

**Issue by zackmdavis** [rust-lang/rust#38417]
[Emacs drops a broken symlink](http://stackoverflow.com/questions/5738170/why-does-emacs-create-temporary-symbolic-links-for-modified-files) in a file's directory to indicate that the file has unsaved changes. When [scanning Rust source files](https://github.com/rust-lang/rust/blob/d250169cb/src/tools/tidy/src/features.rs#L70) for features, the rustc development `tidy` tool will fail if such a lockfile exists in the source tree, with (this part being the actual bug, being that a dirty tree _should_ fail `tidy`) a message that doesn't make it clear what happened:

```
thread 'main' panicked at 'File::open(file) failed with No such file or directory (os error 2)', /home/zmd/Code/rust/src/tools/tidy/src/features.rs:71
```

(The novice compiler developer wonders: _what_ file?)

I think this is likely too obscure to be worth doing anything about, but somehow managed to fall slightly over my subjective threshold of "worth filing an Issue for"; sorry if I'm miscalibrated in this matter.

**Comment by bluss** [comment]
It looks like the [`t!()` macro](https://github.com/rust-lang/rust/blob/d250169cb5a96481a3e7c8f9fe05de49f60e5ae5/src/tools/tidy/src/main.rs#L22) has a two parameter case for reporting path errors, which means it could be fixed by just using `t!(File::open(&file), &file)`

**Comment by zackmdavis** [comment]
```
thread 'main' panicked at 'File::open(&file) failed on /home/zmd/Code/rust/src/librustc/infer/.#mod.rs with No such file or directory (os error 2)', /home/zmd/Code/rust/src/tools/tidy/src/features.rs:71
```
Yes, that's a bit better; thanks! :sparkling_heart:  (trivial PR to follow)
