### ISSUE TITLE
Failure to infer lifetime of a closure argument: "temporary value dropped here while still borrowed"

### ISSUE THREAD

**Issue by afck** [rust-lang/rust#38410]
This doesn't compile because the temporary value `5` doesn't live long enough:
```rust
fn main() {
    let g = |x: &u8| *x;
    let f = |y| g(y) + 1;
    let _ = f(&5);
}
```
But adding a type annotation to the argument of `f` fixes it:
```rust
fn main() {
    let g = |x: &u8| *x;
    let f = |y: &u8| g(y) + 1;
    let _ = f(&5);
}
```
https://play.rust-lang.org/?gist=6d16c45ed03dccb5ff36c24e041d8e6c&version=nightly&backtrace=0

**Comment by kleimkuhler** [comment]
This does not seem to be an issue anymore. Both examples are compiling without error now.

**Comment by afck** [comment]
You're right, this is resolved. Thank you!
