### ISSUE TITLE
`./configure --help` doesn't mention relation between `--prefix` and `--libdir`

### ISSUE THREAD

**Issue by socumbersome** [rust-lang/rust#38431]
To build Rust from source I issue `./configure --prefix=A --libdir=B` where `A` is not a prefix of `B` and this gives the following error:
`configure: error: libdir must begin with the prefix. Use --prefix to set it accordingly.`

The problem here is, I think, twofold:
* Issuing `./configure --help` we get `--prefix=[/usr/local]` and `--libdir=[/lib]` which is, as far as I understand, incorrect, because with the default values Rust's libs are installed into `/usr/local/lib`, and not `/lib`
* In the output of `./configure --help` it is not mentioned that libdir must begin with the prefix

In my opinion the second point could be omitted if there are a lot of caveats when setting various `configure` flags, but the first one should explicitly say something along the lines of: `--libdir=[$(CFG_PREFIX)/lib]` or `--libdir=$(prefix)/lib`.

I don't know whether my reasoning isn't flawed, as this: https://github.com/rust-lang/rust/blob/b1363a73ede57ae595f3a1be2bb75d308ba4f7f6/mk/install.mk#L14 seems to contradict it. But on the other hand, when installing Rust from source with default values, I see Rust's-related libs only in `/usr/local/lib` and not `/lib`.

**Comment by Mark-Simulacrum** [comment]
This is mentioned in the config.toml example; I'm going to go ahead and close. `configure` shouldn't really be used in most cases today.
