### ISSUE TITLE
[rustbuild] Should run tests in predictable and useful order

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#38435]
Currently rustbuild seems to run every test suite in a seemingly random order. One invocation will start from `ui` tests, another from `pretty` et cetera. It would probably more useful if tests were run in a well specified order – most useful to least useful:

* run-pass
* compile-fail
* run-fail
* codegen
* run-make
* ...
* pretty

(where the exact order is debatable, though I’m pretty sure run-pass and compile-fail ought to be the first two)

**Comment by Mark-Simulacrum** [comment]
The order is pretty much guaranteed to be predictable today. Once an order is decided on, this list should be reordered: https://github.com/rust-lang/rust/blob/2fc3aec4316a76429a5a0c8d2eccb19bf81982d6/src/bootstrap/builder.rs#L260-L263.

**Comment by Mark-Simulacrum** [comment]
I'm going to nominate for the compiler team, since I'm hoping they can provide feedback on the best order to by-default run tests in.

**Comment by nikomatsakis** [comment]
I don't have much of an opnion about the best order. I think I agree that `run-pass` and `compile-fail` (and maybe `ui`) should come first, and then maybe `ui`, but I don't *really* care. I personally tend to run either run-pass or compile-fail myself first, depending on the patch, and then come back for "the rest". Removing nomination. 

If the order is predictable, actually, I'm inclined to close this issue and let people who care open a PR.

**Comment by Mark-Simulacrum** [comment]
The order today should be stable and guaranteed; and people wanting to change it can do so via PRs. Closing.
