### ISSUE TITLE
rustbuild doesn't support DESTDIR

### ISSUE THREAD

**Issue by ncihnegn** [rust-lang/rust#38441]
No destdir is passed to install.sh in install.rs.

**Comment by Randl** [comment]
That causes fail in Gentoo build https://github.com/gentoo/gentoo-rust/issues/217

**Comment by Randl** [comment]
As far as I understand, we need to to pass `DESTDIR` to `install` function and add value of `DESTDIR` to prefix here https://github.com/rust-lang/rust/blob/master/src/bootstrap/install.rs#L27
