### ISSUE TITLE
rustbuild is flaky when --keep-stage is given

### ISSUE THREAD

**Issue by DemiMarie** [rust-lang/rust#38446]
When `--keep-stage=0` is passed, rustbuild acts strangely when running tests.  For example, it fails to run newly added tests without rebuilding the compiler.

**Comment by alexcrichton** [comment]
This is sort of the definition of `--keep-stage`, it's flaky unless it's precisely understood why it's ok to skip a previous stage. There's not really any way to solve this issue short of removing the flag itself. If you believe there's buggy logic in rustbuild elsewhere then we can dig into it, but I'm going to close this issue as it's not particularly actionable.
