### ISSUE TITLE
x.py doesn't chdir to its own directory

### ISSUE THREAD

**Issue by DemiMarie** [rust-lang/rust#38447]
`x.py` fails to chdir to its own directory.  Running it from elsewhere results in nonsense like re-downloading bootstrap compilers.

**Comment by sanxiyn** [comment]
Isn't this an intended behavior? So that you can have multiple build directories which do not clobber each other.

I agree cache could be shared. If you agree, we can update the title of the issue.

**Comment by petrochenkov** [comment]
I'm not even sure cache (= downloaded stage0 compiler/cargo) needs to be shared implicitly.
Now each build directory is nicely self-contained, and if you want to use a common stage0 compiler for several builds you can always specify it explicitly in `config.toml`.

**Comment by alexcrichton** [comment]
Yes this is currently expected behavior to support out-of-tree builds. I don't think there's really any location for a shared cache as well as often the source tree can be read-only where the only writable directory is the build tree (current directory)

**Comment by Mark-Simulacrum** [comment]
Closing as expected behavior -- I don't think we want to change this.
