### ISSUE TITLE
#[allow(non_camel_case_types)] doesn't work for individual enum variant

### ISSUE THREAD

**Issue by Riateche** [rust-lang/rust#38452]
`#[allow(non_camel_case_types)]` only works if applied to the whole enum. If applied to a variant, it does nothing.
```
enum A {
    #[allow(non_camel_case_types)]
    B_B
}
```
It should either suppress the warning for that variant or give an error or warning that this directive can't be applied in this context.

**Comment by acelot** [comment]
Understand. As a workaround, I've just suppress the warnings for the module.
```rust
#![allow(non_camel_case_types)]
pub mod gen_pages;
```
