### ISSUE TITLE
Multiple Environment Variables to Process Builder

### ISSUE THREAD

**Issue by dzobbe** [rust-lang/rust#38455]
Hi,

I am struggling in trying to pass to the command process builder a dynamic number of environment variables. As far as I know the "env" function can only set one environment variable. So one should call it multiple times. However, in my case, I have a number of environment variables which is known only at runtime. It could be really useful to have, as for the "arg" function, a "envs" function able to receive a vector of environment variables.

Cheers

**Comment by nagisa** [comment]
> I am struggling in trying to pass to the command process builder a dynamic number of environment variables. 

```
let cmd = Command::new(); 
for (var, val) in vars { cmd.env(var, val); }
```

Should be working just fine.

**Comment by dzobbe** [comment]
Oh dear, I am feeling like a stupid. Sometime obvious and trivial things are neglected :D Sorry for the stupid question

Thanks  ;)
