### ISSUE TITLE
Properly fix the personality_fn setting in MIR trans

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#38462]
https://github.com/rust-lang/rust/pull/37862 has landed despite my repeated warnings this is a hack and should be fixed properly. This issue is a reminder for self to fix this properly once the larger PRs in queue land (the old trans cleanup and i128).

The fix would likely be as simple as fixing init_cpad function and reverting the whole patch from the linked PR.

**Comment by Mark-Simulacrum** [comment]
Just leaving a note here so it's easier to find for whoever works on this: After #38302, init_cpad will not exist, but will be inlined into `trans_mir`.
