### ISSUE TITLE
gentle skepticism of x.py naming rationale

### ISSUE THREAD

**Issue by zackmdavis** [rust-lang/rust#38476]
The commit message for a270b8014 states:

> This `x` [the `x.py` script to call rustbuild] was chosen to be both short and easily tab-completable (no collisions in that namespace!).

But the present author's dev environments do end up with another path starting with `x` in that directory, requiring another character to be typed to disambiguate tab completion: namely, the build directory for x86 target triples—

```
~/Code/rust$ ./x
x86_64-unknown-linux-gnu/ x.py
```

Unless the present author somehow has something configured unusually such that the `x86_64-unknown-linux-gnu` build directory would ordinarily be created somewhere else, one wonders if the easily-tab-completable criterion have been better served by naming the script `q.py`?

**Comment by nagisa** [comment]
`x86_64-unknown-linux-gnu/` is a build artefact from the old configure-Makefile-based build system.

**Comment by zackmdavis** [comment]
I see, thanks! :sparkling_heart:
