### ISSUE TITLE
Outdated info in nomicon on drop flags

### ISSUE THREAD

**Issue by XMPPwocky** [rust-lang/rust#38481]
> As of Rust 1.0, the drop flags are actually not-so-secretly stashed in a hidden field of any type that implements Drop. Rust sets the drop flag by overwriting the entire value with a particular bit pattern. This is pretty obviously Not The Fastest and causes a bunch of trouble with optimizing code. It's legacy from a time when you could do much more complex conditional initialization.

> As such work is currently under way to move the flags out onto the stack frame where they more reasonably belong. Unfortunately, this work will take some time as it requires fairly substantial changes to the compiler.

[https://github.com/rust-lang/rust/blob/master/src/doc/nomicon/drop-flags.md](https://github.com/rust-lang/rust/blob/master/src/doc/nomicon/drop-flags.md)

The work described landed in #33622, so this is now out of date.

**Comment by sanxiyn** [comment]
See #39304.

**Comment by steveklabnik** [comment]
this has been fixed
