### ISSUE TITLE
rustbuild warning

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#38484]
When you compile rust you get:

```
warning: value assigned to `stage` is never read, #[warn(unused_assignments)] on by default
   --> src/bootstrap/flags.rs:277:17
    |
277 |                 stage = Some(1);
    |                 ^^^^^
```

Regression of #38072

cc @nikomatsakis 

Maybe rustbuild should be compiled with `#[forbid(warnings)]` to prevent errors like these in the future?

**Comment by est31** [comment]
cc @alexcrichton

**Comment by alexcrichton** [comment]
Yeah when we fix this let's tag rustbuild with `#![deny(warnings)]`
