### ISSUE TITLE
Linking JS files from libraries

### ISSUE THREAD

**Issue by chpio** [rust-lang/rust#38492]
hi,

it seems that it's not possible to link javascript files from a rust library at the moment. The usual practice is by setting the `--js-library $path_to_js_file` *emcc*-linker argument. But setting linker arguments from a lib is not allowed in rust (https://github.com/rust-lang/rust/issues/36176, https://github.com/rust-lang/cargo/issues/1293).

I can think of two possible solutions for this:
1. allowing link args when compiling to asm.js/wasm
2. using the extern-linking syntax and converting the link to an `--js-library` emcc argument to pull in the js file:
```rust
#[link(name="my_js_file")]
extern {
    fn add(a: size_t, b: size_t) -> size_t;
}
```

**Comment by badboy** [comment]
Can we get a `A-asmjs` tag here?

**Comment by chpio** [comment]
I'm closing this in favor of [stdweb](https://crates.io/crates/stdweb)'s inline js and wasm imports.
