### ISSUE TITLE
Compiler panicks 

### ISSUE THREAD

**Issue by imYavuz** [rust-lang/rust#38500]
When I try to run this code https://github.com/imYavuz/azra/blob/master/src/main.rs
This happens:
![adsiz](https://cloud.githubusercontent.com/assets/19875240/21364906/8c62cb72-c6fb-11e6-8fd5-1ab543e7028f.png)

**Comment by petrochenkov** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/38155, fixed in https://github.com/rust-lang/rust/pull/38375
