### ISSUE TITLE
AVG detects Rust 1.13 as a trojan

### ISSUE THREAD

**Issue by BookOwl** [rust-lang/rust#38510]
AVG says that it has found the following two threats on my system:

"Trojan horse Generic38.ADSI, c:\Program Files (x86)\Rust stable GNU 1.13\bin\log-a4729905.dll"
"Trojan horse Generic38.ADKS, c:\Program Files (x86)\Rust stable GNU 1.13\lib\rustlib\i686-pc-windows-gnu\lib\log-a4729905.dll"

I'm pretty sure that these are false positives, but you guys should probably check on why AVG is detecting these dlls as trojans.

**Comment by Stebalien** [comment]
That's a generic heuristic that detects "suspicious" behavior. Unfortunately, they're next to worthless. If you have time, could you submit those files here: https://secure.avg.com/submit-sample?

**Comment by steveklabnik** [comment]
Yes, this is not actionable, unless AVG tells us that we need something specific to stop triggering this. Please submit this to the link @Stebalien has given you, thanks!

I'm going to give this a close, but if they happen to come back with something we need to do, please leave a comment and let us know, and we can re-open.
