### ISSUE TITLE
Incr comp tests failing on windows with debuginfo turned on

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#38512]
Maybe its no issue, as other tests are failing with debuginfo turned on as well, but some incr comp regression tests fail on windows if debuginfo is turned on (tested with mingw, x86_64 target). 

Reproducible with `x.py test src/test/incremental --stage 2` and debuginfo-test set to true in config.toml.

@michaelwoerister can you say whether this is a bug or whether its wanted behaviour? If its wanted, feel free to close this as NOTABUG.

**Comment by michaelwoerister** [comment]
I'll look into it.

**Comment by michaelwoerister** [comment]
What exactly do you mean by "if debuginfo is turned on"?

The test certainly need control over whether they are compiled with or without debuginfo, so if some setting of the build system leaks into the test suite, that would be a bug.

**Comment by est31** [comment]
@michaelwoerister I meant the [debuginfo-tests](https://github.com/rust-lang/rust/blob/master/src/bootstrap/config.toml.example#L165) setting in config.toml. If the tests indeed are only made to work with debuginfo turned off then its no issue I think, just wanted to be sure that there is no bug with rustc where debuginfo changes some basic behaviour.

**Comment by michaelwoerister** [comment]
@est31 Ah, yes, that explains it. But it's kind of a problem. The build system should at least emit a warning. Many tests rely on being able to control their debuginfo and optimization settings.
