### ISSUE TITLE
Specialization on arrays does not work as expected.

### ISSUE THREAD

**Issue by Pireax** [rust-lang/rust#38515]
The following example currently does not work as expected:

    #![feature(specialization)]

    trait Length {
        fn length(&self) -> usize;
    }

    impl<T> Length for [T] {
        default fn length(&self) -> usize {
            println!("Default");
            self.len()
        }
    }

    impl<T> Length for [T]
        where T: Length
    {
        fn length(&self) -> usize {
            println!("Specialization");
            self.len() + self[0].length()
        }
    }

    impl<'a, T> Length for [&'a[T]]
    {
        fn length(&self) -> usize {
            println!("Specialization");
            self.len() + self[0].length()
        }
    }

    fn main() {
        let x = [[1, 2], [3, 4], [5, 6]];
        println!("{}", x.length());
    }

This does compile but it always only executes the default implementation of `Length`.
What I would expect to happen is specialization on `for [T] where T: Length` or `for [&'a[T]]`,
instead this outputs:

    Default
    3

Am I missing something here?

**Comment by apasel422** [comment]
The type of `x` in your example is `[[i32; 2]; 3]`. Method lookup autorefs that array as `&[[i32; 2]; 3]`, coerces it to a slice `&[[i32; 2]]`, and selects the default `Length` implementation.

You might try:

```rust
let x = [&[1, 2] as &[_], &[3, 4], &[5, 6]];
```

**Comment by Pireax** [comment]
Ah right, makes sense. The reason I want to do this is to recursively go into a nested array and get it's dimensions. Seems this isn't possible at the moment.
Thanks
