### ISSUE TITLE
illegal moves permitted in statics and constants

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#38520]
This code [compiles on nightly today](https://is.gd/5SDSWz) but it should not, because `Foo` is not `Copy`:

```rust
#![feature(const_fn)]

struct Foo(usize);

const fn get(x: Foo) -> usize {
    x.0
}

const X: Foo = Foo(22);
static Y: usize = get(*&X); // also a problem for `const Y`

fn main() {
}
```

Note that the `get(*&X)` in a function body [properly results in an error](https://is.gd/zU2BVo).

**Comment by nikomatsakis** [comment]
triage: P-medium

**Comment by nikomatsakis** [comment]
This is likely a problem of how borrowck kind of special-cases the handling of statics a bit. Should be relatively easy to fix. Could be fixed "en passante" by MIR borrowck; I'll also try to add some mentoring tips.

**Comment by cengizIO** [comment]
Hello @nikomatsakis. I'd like to take a shot at this if I'm allowed.

**Comment by cengizIO** [comment]
My first observation is that this isn't related to `const_fn`. Am I right?

I reading the [RFC](https://github.com/rust-lang/rfcs/blob/master/text/0911-const-fn.md) now and doesn't seem to require `Copy` on `const_fn`s.

**Comment by cengizIO** [comment]
Hello again @nikomatsakis 

I'm working on this right now.

**Comment by nikomatsakis** [comment]
@cengizIO ok -- how are you making out? Sorry I didn't get around to leaving any notes on how to proceed. Let me know if you still want me to go digging around -- or privmsg me on IRC (`nmatsakis`).

**Comment by nikomatsakis** [comment]
@cengizIO so looking at the code a bit, it seems clear that the problem is that the borrowck code has this kind of custom and woefully insufficient bit of code dedicated to statics and constants. It really ought to be using the same pathways as the rest of the code. (In particular, the `ExprUseVisitor`, which is a bit of code that interprets the HIR and gives callbacks corresponding to moves, borrows, etc). Unfortunately, those pathways are kind of setup more for regular expression bodies; I'm not 100% sure how easy they will be to apply.

I feel like this bug fix is "just" a refactoring, but the refactoring itself may not be all *that* simple. Doing the borrowck on the MIR we generate for constants would fix it, but it's not clear when MIR borrowck will land.

**Comment by cengizIO** [comment]
@nikomatsakis as we talked in IRC, I think this should be discussed widely before we start implementing anything.
