### ISSUE TITLE
feature request: std::process::Command.envs()

### ISSUE THREAD

**Issue by zackw** [rust-lang/rust#38526]
You can add a vector of command-line arguments to a Command object with `.args()`, but there's no equivalent for environment variables.  I'd like to be able to do things like

    let filtered_env : Vec<(String, String)> = 
        std::env::vars().filter(|&(ref k, ref v)| /* criterion */).collect();

    let status = Command::new("printenv")
        .stdin(Stdio::null())
        .stdout(Stdio::inherit())
        .env_clear()
        .envs(filtered_env)
        .status();

Right now I have to do instead

    let mut cmd = Command::new("printenv");
    cmd.stdin(Stdio::null());
    cmd.stdout(Stdio::inherit());
    cmd.env_clear();

    for (ref k, ref v) in filtered_env {
        cmd.env(k, v);
    }
    let status = cmd.status();

which breaks the builder pattern and extends the scope of the Command object.

**Comment by brson** [comment]
This sounds reasonable to me considering `args`. If you want to submit a PR for the feature go ahead.

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

**Comment by dtolnay** [comment]
@rfcbot reviewed

**Comment by zackw** [comment]
I'm confused; hasn't this already been merged?

**Comment by Mark-Simulacrum** [comment]
Yes, but it's currently [unstable](https://doc.rust-lang.org/nightly/std/process/struct.Command.html#method.envs). The FCP above starting means that the libs team believes the API is ready for stabilization.

**Comment by zackw** [comment]
Oh, ok. Thanks for the explanation.
