### ISSUE TITLE
support test::make_unpredictable ?

### ISSUE THREAD

**Issue by kkimdev** [rust-lang/rust#38522]
Facebook Folly's benchmarking util includes the following two functions:

https://github.com/facebook/folly/blob/1c098e2758d1bd55c48ffa26dab389dbbe96a666/folly/Benchmark.h#L260

```C++
void doNotOptimizeAway(const T& datum);
void makeUnpredictable(T& datum);
```

`doNotOptimizeAway` corresponds to `test::black_box` in Rust, but to my understanding we don't have `makeUnpredictable` counterpart.  I think it will be useful to ensure that tested code is not optimized by constant inputs.

**Comment by kkimdev** [comment]
@huonw @amaranth

**Comment by nagisa** [comment]
`black_box` does both. LLVM cannot do any optimisations based on the value of stuff passed into it.

**Comment by kkimdev** [comment]
Oh Ok, I missed that `black_box` also returns T thanks!
