### ISSUE TITLE
rustbuild should not grab the latest beta unless instructed to (or on first run)

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#38532]
There is a principle - one should opt-in to a build tool accessing the internet, but also a practical effect - I was in the middle of debugging and my 5 min edit-compile-debug cycle is now an hour because there a new beta got released and now I'm re-compiling llvm :-(

**Comment by est31** [comment]
related #37305

**Comment by alexcrichton** [comment]
I somewhat disagree with this in the sense that we're doing exactly the same thing as the previous build system, and no one complained about the makefiles...

**Comment by nrc** [comment]
@alexcrichton I thought I had to `git pull` in order to get a new snapshot? Or maybe `configure`? I don't remember the snapshot changing on a plain `make`.

**Comment by alexcrichton** [comment]
Hm there could perhaps be a bug, but I don't think that "rustbuild downloading stage0 compilers when it thinks it needs to" is a bug. If it thinks it should and it shouldn't then that's a bug.

**Comment by ranma42** [comment]
What was the outcome of the discussion?

**Comment by alexcrichton** [comment]
This was discussed during the recent tools triage meeting and the conclusion was that the current behavior should be working as intended (pinned betas, not the most recent beta), but if this reproduces again we can investigate!
