### ISSUE TITLE
Reference outlives content error message is wrong when there are explicit unrelated lifetimes

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#38545]
```rust
fn test<'a, 'b>(mut a: &'a i32, b: &'b i32) {
    a = b;
}
fn main() {}
```

gives

```
rustc 1.13.0 (2c6933acc 2016-11-07)
error[E0312]: lifetime of reference outlives lifetime of borrowed content...
 --> <anon>:2:9
  |
2 |     a = b;
  |         ^
  |
note: ...the reference is valid for the lifetime 'a as defined on the block at 1:44...
 --> <anon>:1:45
  |
1 | fn test<'a, 'b>(mut a: &'a i32, b: &'b i32) {
  |                                             ^
note: ...but the borrowed content is only valid for the lifetime 'b as defined on the block at 1:44
 --> <anon>:1:45
  |
1 | fn test<'a, 'b>(mut a: &'a i32, b: &'b i32) {
  |                                             ^
help: consider using an explicit lifetime parameter as shown: fn test<'a>(mut a: &'a i32, b: &'a i32)
 --> <anon>:1:1
  |
1 | fn test<'a, 'b>(mut a: &'a i32, b: &'b i32) {
  | ^

error: aborting due to previous error
```

There are two issues I see with this:
 * `lifetime of reference outlives lifetime of borrowed content`
   * This is not strictly true, the lifetime of the reference is independent from the lifetime of the borrowed content and the real issue is that the compiler cannot prove that the reference will not outlive the content without additional constraints added by the programmer.
 * The suggested fix
   * There are already explicit lifetime parameters, assumedly added for a reason, the more likely correct fix in this case would be to add `'b: 'a` rather than conflating the two lifetimes.

**Comment by estebank** [comment]
[Current output](https://play.rust-lang.org/?gist=f69feac9077c045ce8e41ccaf76873b7&version=nightly):

```
error[E0623]: lifetime mismatch
 --> src/main.rs:2:9
  |
1 | fn test<'a, 'b>(mut a: &'a i32, b: &'b i32) {
  |                        -------     ------- these two types are declared with different lifetimes...
2 |     a = b;
  |         ^ ...but data from `b` flows into `a` here
```

Still no suggestion to add constraint on `'b`.

**Comment by estebank** [comment]
Closing as per prior comment.
