### ISSUE TITLE
libstd Process tests depend on msys programs on windows

### ISSUE THREAD

**Issue by retep998** [rust-lang/rust#38565]
If you don't have some sort of msys in your PATH, then the libstd process tests will fail because they attempt to spawn programs that don't exist on Windows by default.

```
failures:

---- process::tests::test_finish_once stdout ----
        thread 'process::tests::test_finish_once' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "The system cannot find the file specified." } }', src\libcore\result.rs:845

---- process::tests::test_finish_twice stdout ----
        thread 'process::tests::test_finish_twice' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "The system cannot find the file specified." } }', src\libcore\result.rs:845

---- process::tests::test_process_output_error stdout ----
        thread 'process::tests::test_process_output_error' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "The system cannot find the file specified." } }', src\libcore\result.rs:845

---- process::tests::test_process_output_output stdout ----
        thread 'process::tests::test_process_output_output' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "The system cannot find the file specified." } }', src\libcore\result.rs:845

---- process::tests::test_process_status stdout ----
        thread 'process::tests::test_process_status' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "The system cannot find the file specified." } }', src\libcore\result.rs:845

---- process::tests::test_wait_with_output_once stdout ----
        thread 'process::tests::test_wait_with_output_once' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "The system cannot find the file specified." } }', src\libcore\result.rs:845


failures:
    process::tests::exit_reported_right
    process::tests::smoke
    process::tests::stdout_works
    process::tests::test_finish_once
    process::tests::test_finish_twice
    process::tests::test_process_output_error
    process::tests::test_process_output_output
    process::tests::test_process_status
    process::tests::test_wait_with_output_once
```

**Comment by brson** [comment]
It's probably best for the test suite to use it's own binaries for testing processes, but in the short term we can just make their names unix/windows-specific.

**Comment by brson** [comment]
The task here should probably be simple. Identify equivalent windows system exes to call for the failing tests and use cfgs to enable them on windows.

**Comment by abhijeetbhagat** [comment]
i can work on this.

**Comment by petrochenkov** [comment]
All `run-make` tests also fail when run without msys (they are not skipped on MSVC, at least in rustbuild).
In theory they could use MSVC's `nmake` instead of `make`, they should be compatible for very simple makefiles.

**Comment by alexcrichton** [comment]
@petrochenkov oh my plan with `run-make` was to migrate all the tests to Rust actually one day rather than prolonging the life of `make`. I feel like it'd be a never-ending series of painful PRs to maintain compatibility with both `make` and `nmake`, so we could solve both by making a rustbuild-like transition, just rewriting all the tests in Rust.

**Comment by petrochenkov** [comment]
>use MSVC's nmake instead of make

Some status update: This is a bad idea.
nmake and gnu make are largely incompatible and most of `src\test\run-make\tools.mk` and many makefiles need to be rewritten + run-make tests actively use other unix utilities unavailable in MSVC environment.
