### ISSUE TITLE
Rust 1.14 seems to make at least some performance sensitive code 10% slower

### ISSUE THREAD

**Issue by pedrocr** [rust-lang/rust#38578]
At least some of the tight loop code in https://github.com/pedrocr/rawloader has become 10% slower in rust 1.14. To replicate this do something like:

```sh
$ git clone https://github.com/pedrocr/rawloader.git
$ cd rawloader
$ cargo build --release
$ wget http://www.rawsamples.ch/raws/sony/RAW_SONY_SLT-A77V.ARW
$ echo performance | sudo tee /sys/devices/system/cpu/cpufreq/policy*/scaling_governor
$ ./target/release/benchmark RAW_SONY_SLT-A77V.ARW
Loading file "RAW_SONY_SLT-A77V.ARW"
Average decode time: 99 ms (110 iterations)
```

On the same machine using rust 1.13 I get:

```sh
$ ./target/release/benchmark RAW_SONY_SLT-A77V.ARW 
Loading file "RAW_SONY_SLT-A77V.ARW"
Average decode time: 88 ms (120 iterations)
```

That's a >10% performance regression. The relevant hot code in this case is this one:

https://github.com/pedrocr/rawloader/blob/master/src/decoders/arw.rs#L177-L207

decode_threaded() uses rayon and is just a simple wrapper:

https://github.com/pedrocr/rawloader/blob/master/src/decoders/basics.rs#L276-L284

**Comment by nagisa** [comment]
Another LLVM 3.9 case, I think.

**Comment by pedrocr** [comment]
Unfortunately I don't have a clang 3.9 to check if the equivalent C++ code shows the same regression.

**Comment by pedrocr** [comment]
I'll have another look. It's possible I no longer support 1.13. I haven't been testing back. It's always possible to just use the version from back then. You have a fast machine though :)

**Comment by pedrocr** [comment]
Okay, I've rerun this properly now. Here's what I did:

  * Went back to rawloader 0.30.0 so as to still be using the old toml. It seems toml 0.4 no longer works on 1.13
  * Thanks to rustup and how easy it is to build self-contained binaries I created five rawloader benchmark binaries for major releases from 1.13 to 1.17
  * Set all 4 CPU threads to performance and didn't run anything else at the same time
  * Then I ran the same sample file across all five binaries and did that three times averaging the results

Here's the outcome:

Rust Version | Average Decode Time (ms)
------------ | -------------
1.13.0 | 93
1.14.0 | 92
1.15.0 | 93
1.16.0 | 92
1.17.0 | 93

There's a very slight fluctuation between versions which can be just random chance. So either the regression only applied to some dependency that I have since updated (rayon would be the best bet) or I screwed up the initial testing. Closing it anyway and sorry for wasting time.

**Comment by pedrocr** [comment]
Because I was curious I reran this with more sleep time between runs to allow the processor to cool-off if needed and ran it five times instead of three and removed the highest and lowest value from each version. I also ran it with beta and nightly:

Rust Version | Average Decode Time (ms)
------------ | -------------
1.13.0 (2c6933acc 2016-11-07) | 93
1.14.0 (e8a012324 2016-12-16) | 93
1.15.0 (10893a9a3 2017-01-19) | 93
1.16.0 (30cf806ef 2017-03-10) | 93
1.17.0 (56124baa9 2017-04-24) | 93
1.18.0-beta.2 (f4e8e81c3 2017-05-11) | 85
1.19.0-nightly (826d8f385 2017-05-13) | 82

So no longer are the results extremely stable it seems the next two releases are going to be awesome. The CPU usage was noticeably higher in 1.18 and 1.19 though so it may be that rayon has more tricks up it's sleave with those versions.

**Comment by Mark-Simulacrum** [comment]
Thanks for doing the legwork here! Some of the wins in the next two releases may be due to LLVM 4.0 landing in-tree; though I'm uncertain, I think that's in 1.18. Please do report these in the future though, it's certainly not a waste of time!

**Comment by pedrocr** [comment]
Good to know. At least now I know how to do a much more valid benchmark run so the risk of false positives should be much lower :)
