### ISSUE TITLE
arm-unknown-linux-gnueabihf produces armv7 output not armv6

### ISSUE THREAD

**Issue by mkj** [rust-lang/rust#38570]
I'm cross compiling on x64 Linux to a Raspberry Pi 1, Raspbian Jessie. Binaries produced by arm-unknown-linux-gnueabi target work fine, binaries from arm-unknown-linux-gnueabihf segfault in _start().

Readelf tells me that the arm-unknown-linux-gnueabihf target is actually armv7, which contradicts https://forge.rust-lang.org/platform-support.html

```
~/src/rusthello> readelf -A target/*/debug/rusthello 

File: target/arm-unknown-linux-gnueabi/debug/rusthello
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "ARM v6"
  Tag_CPU_arch: v6                                           <--
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-1
  Tag_ABI_PCS_GOT_use: GOT-indirect
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_rounding: Needed
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_enum_size: int
  Tag_CPU_unaligned_access: v6
  Tag_ABI_FP_16bit_format: IEEE 754

File: target/arm-unknown-linux-gnueabihf/debug/rusthello
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "7-A"
  Tag_CPU_arch: v7                                           <--
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3-D16
  Tag_ABI_PCS_GOT_use: GOT-indirect
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_rounding: Needed
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_enum_size: int
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6
  Tag_ABI_FP_16bit_format: IEEE 754

File: target/armv7-unknown-linux-gnueabihf/debug/rusthello
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "7-A"
  Tag_CPU_arch: v7                                           <--
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3-D16
  Tag_ABI_PCS_GOT_use: GOT-indirect
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_rounding: Needed
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_enum_size: int
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6
  Tag_ABI_FP_16bit_format: IEEE 754

rustc 1.14.0 (e8a012324 2016-12-16)
binary: rustc
commit-hash: e8a0123241f0d397d39cd18fcc4e5e7edde22730
commit-date: 2016-12-16
host: x86_64-unknown-linux-gnu
release: 1.14.0
LLVM version: 3.9
```

**Comment by japaric** [comment]
I think this may be your cross toolchain's fault because all the Rust side is v6, AFAICT:

```
$ readelf -A $(rustc --print sysroot)/lib/rustlib/arm-unknown-linux-gnueabihf/lib/*.rlib | grep Tag_CPU_arch
  Tag_CPU_arch: v6
  Tag_CPU_arch: v6
  Tag_CPU_arch: v6
  Tag_CPU_arch: v6
  Tag_CPU_arch: v6
  Tag_CPU_arch: v6
(..)
```

If you are using the `gcc-arm-linux-gnueabihf` package that ships with Ubuntu, that would be problem because that toolchain targets ARMv7.

```
$ readelf -A /usr/arm-linux-gnueabihf/lib/crt1.o
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "7-A"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3-D16
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_rounding: Needed
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_align_preserved: 8-byte, except leaf SP
  Tag_ABI_enum_size: int
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6
```

You should use the toolchain in the [raspberrypi/tools](https://github.com/raspberrypi/tools) repo or build your own but that targets v6.

**Comment by mkj** [comment]
Thank you @japaric , that is the problem. I was using the Ubuntu toolchain, the raspberrypi one works as expected.
Sorry for the noise.

**Comment by cubetastic33** [comment]
> I think this may be your cross toolchain's fault because all the Rust side is v6, AFAICT:
> 
> ```
> $ readelf -A $(rustc --print sysroot)/lib/rustlib/arm-unknown-linux-gnueabihf/lib/*.rlib | grep Tag_CPU_arch
>   Tag_CPU_arch: v6
>   Tag_CPU_arch: v6
>   Tag_CPU_arch: v6
>   Tag_CPU_arch: v6
>   Tag_CPU_arch: v6
>   Tag_CPU_arch: v6
> (..)
> ```
> 
> If you are using the `gcc-arm-linux-gnueabihf` package that ships with Ubuntu, that would be problem because that toolchain targets ARMv7.
> 
> ```
> $ readelf -A /usr/arm-linux-gnueabihf/lib/crt1.o
> Attribute Section: aeabi
> File Attributes
>   Tag_CPU_name: "7-A"
>   Tag_CPU_arch: v7
>   Tag_CPU_arch_profile: Application
>   Tag_ARM_ISA_use: Yes
>   Tag_THUMB_ISA_use: Thumb-2
>   Tag_FP_arch: VFPv3-D16
>   Tag_ABI_PCS_wchar_t: 4
>   Tag_ABI_FP_rounding: Needed
>   Tag_ABI_FP_denormal: Needed
>   Tag_ABI_FP_exceptions: Needed
>   Tag_ABI_FP_number_model: IEEE 754
>   Tag_ABI_align_needed: 8-byte
>   Tag_ABI_align_preserved: 8-byte, except leaf SP
>   Tag_ABI_enum_size: int
>   Tag_ABI_VFP_args: VFP registers
>   Tag_CPU_unaligned_access: v6
> ```
> 
> You should use the toolchain in the [raspberrypi/tools](https://github.com/raspberrypi/tools) repo or build your own but that targets v6.

I don't understand what to do. I do face a similar issue, I am trying to cross-compile to ARMv6 from Ubuntu. How am I supposed to do this?

**Comment by moriyas1984** [comment]
Any update?

I also need some directions to cross-compile to ARMv6 from Ubuntu. 

Regards.

**Comment by moriyas1984** [comment]
Sorry, I have understood how to use it.

https://github.com/BurntSushi/ripgrep/issues/676#issuecomment-374058198

This comment told me how I should specify the linker in raspberrypi/tools.

Thank you.
