### ISSUE TITLE
[rustbuild] --keep-stage=0 and tidy

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#38582]
With `test --keep-stage=0` tidy.exe will not be built and if it didn’t exist previously, the tests will fail.

**Comment by alexcrichton** [comment]
This is just a case where `--keep-stage` is only meant for local quick development, not a battle tested feature. If we keep getting but reports about it then I'm tempted to just remove it to match apparent expectations.

**Comment by bluss** [comment]
tidy is not part of the use case, so I don't think this is a bug.

**Comment by Mark-Simulacrum** [comment]
I believe the new rustbuild fixed the problem, so I'm going to close this.
