### ISSUE TITLE
Allow for the ability to have undefined behaviour for division in release builds

### ISSUE THREAD

**Issue by jrmuizel** [rust-lang/rust#38592]
Currently, rust emits checks for division by 0 and division overflow when doing integer division. It would be nice to have a way to avoid these checks in performance sensitive code like arithmetic decoders (e.g. Opus)

**Comment by steveklabnik** [comment]
This kind of change would require an RFC, as it's a major change to the language. Specifically, it would modify [RFC 560](https://github.com/rust-lang/rfcs/blob/master/text/0560-integer-overflow.md). Specifically,

> The operations /, % for the arguments INT_MIN and -1 will unconditionally panic. This is unconditional for legacy reasons.

As such, I'm going to give this one a close; please pursue this in the RFCs repository. Thanks!

**Comment by jrmuizel** [comment]
Ok, I'll look into pursuing this there. In the mean time, could this behaviour be documented in an easier to find location than the RFC?
