### ISSUE TITLE
ToOwned trait bound not accepted for u8

### ISSUE THREAD

**Issue by nyarly** [rust-lang/rust#38597]
While `to_owned()` called on a reference to a `u8` returns a `u8`, a trait bound function doesn't accept `u8`/`&u8` as type parameters

I tried this code:

```rust
use std::collections::btree_map::BTreeMap;
use std::fmt::Debug;
use std::borrow::Borrow;

#[derive(Clone, Debug)]
pub struct Counts<T> {
    counts: BTreeMap<T, u32>,
    total: u32,
}

impl<T: Ord + Clone + Debug> Counts<T> {
    pub fn new<L, R>(list: L) -> Counts<T>
        where L: IntoIterator<Item = R>,
              R: ToOwned<Owned = T> + Sized,
              T: Borrow<R>
    {
        let mut fc = BTreeMap::new();
        let mut count = 0;
        for it in list {
            let entry = fc.entry(it.to_owned()).or_insert(0);
            *entry += 1;
            count += 1
        }

        Counts {
            counts: fc,
            total: count,
        }
    }
}

// Actual problem:
fn main() {
    let r = &b'h';
    let _: u8 = r.to_owned();
    let line: Vec<u8> = vec![b'h', b'i', b'!'];
    let counts = Counts::<u8>::new::<_, &u8>(&line);
}
```

(Sorry for the length... not sure what more I can cut and still have it fail.)

I expected to see this happen: In the above snippet, I'd expect to be able to treat `&line` as a `&[u8]`, and therefore `IntoIterator<Item=&u8>`, therefore `R` is `&u8` which should be `ToOwned<Owned=u8>` and so `T` is `u8`. 

Instead, passing a `&Vec<u8>` will only work to produce a `Count<&u8>` (elsewhere, Counts has a method which accepts `Fn(T,T)->T`, used like `|x,y| x ^ y` so `&u8` isn't acceptable.) Alternatively, I and `Counts::new(line.clone())` but that seems like it does a double copy; this is okay for my use case, but in general it's confusing.

## Meta

This behavior was exhibited today by the Rust Playground.

**Comment by sinkuu** [comment]
> `&u8` which should be `ToOwned<Owned=u8>`

No, `&u8` implements `ToOwned<Owned=&u8>`. `u8` implements `ToOwned<Owned=u8>` which has the method `fn to_owned(&u8) -> u8 { clone it }`.

You can use `Clone` for getting `T` from either `&T` or `T`.

```rust
pub fn new<L, R>(list: L) -> Counts<T>
    where L: IntoIterator<Item = R>,
            R: Borrow<T>,
            T: Clone,
{
    let mut fc = BTreeMap::new();
    let mut count = 0;
    for it in list {
        let entry = fc.entry(it.borrow().clone()).or_insert(0);
        *entry += 1;
        count += 1
    }

    Counts {
        counts: fc,
        total: count,
    }
}
```

If you don't like this solution (will be surely optimized out, but borrow and then clone!?), you can write a trait to dispatch between `T` and `&T`: https://is.gd/Wnw2E2

**Comment by nyarly** [comment]
Okay...

I think my reasoning ran like this: I could implement a "make an 'into'" trait like your `CloneOrPassthrough`, but *surely* there's a standard trait to do this, an then I found ToOwned and it sure looked like it would do what I wanted. 

Given that the docs for ToOwned describe it as a generalization of Clone, why doesn't it work as I'd assumed? Conversely, with it defined as you explain, why does `let x: u8 = (&b'x').to_value()` work?

**Comment by sinkuu** [comment]
`<T as ToOwned>::to_owned` takes `&self` (which is `&T`, not `T`) and returns `T`. By taking `&self`, both `(T).to_owned()` and `(&T).to_owned()` work through `<T as ToOwned>` instance. But `<&T as ToOwned>::to_owned` takes `&&T` as self and returns `&T`.

I'm not sure why `ToOwned` is implemented in this way. There may be reasons.

**Comment by nyarly** [comment]
It makes some sense that `ToOwned` would be defined as `fn to_owned(&self) -> Self::Borrowed`...

Okay, I've just now realized, and maybe it's useful to someone else: therefore `(&b'u8').to_owned()` is calling the `to_owned` for `u8` and ToOwned, not `&u8` Which is basically what you just said, and I'm a bit thick here.

Thanks very much for taking the time to lay that out. I'm still not sure I could've predicted it, but at least it makes sense now.
