### ISSUE TITLE
Weird error with inline assemby (invalid operand for inline asm constraint 'i')

### ISSUE THREAD

**Issue by DominusCarnufex** [rust-lang/rust#38602]
The following code

```rust
#![crate_type="rlib"]
#![crate_name = "rsc"]
#![feature(asm)]

pub enum MyEnum {
    Value1,
    Value2,
}

impl MyEnum {
    pub fn method(&self)    {
        unsafe  {
            asm!("mov rax, $0"
                : 
                : "i"(u64::from(self))
                : 
                : "intel", "volatile"
            );
        }
    }
}

impl<'a> From<&'a MyEnum> for u64   {
    fn from(s : &MyEnum) -> u64 {
        match *s    {
            MyEnum::Value1 => 0x1,
            MyEnum::Value2 => 0x2,
        }
    }
}
```

fails to compile with the following error

```
error: invalid operand for inline asm constraint 'i'
  --> lib.rs:13:13
   |
13 |               asm!("mov rax, $0"
   |  _____________^ starting here...
14 | |                 : 
15 | |                 : "i"(u64::from(self))
16 | |                 : 
17 | |                 : "intel", "volatile"
18 | |             );
   | |______________^ ...ending here
```

What is weird is :

1. Everything works perfectly fine with `#![crate_type="bin"]` and `#![crate_type="staticlib"]` but fails with `#![crate_type="rlib"]` and `#![crate_type="dylib"]`.
2. If there is only one variant in the enumeration, it compiles fine.
3. If you replace `"i"(u64::from(self))` with `"i"(0x1)`, it compiles fine.
4. If you replace the method `MyEnum::method` by the following function, it compiles fine

```rust
fn function(param : MyEnum) {
    unsafe  {
        asm!("mov rax, $0"
            : 
            : "i"(u64::from(&param))
            : 
            : "intel", "volatile"
        );
    }
}
```

5. If you replace the body of `MyEnum::method` with the following code, it fails too.

```rust
        let param : u64 = u64::from(self);

        unsafe  {
            asm!("mov rax, $0"
                : 
                : "i"(param)
                : 
                : "intel", "volatile"
            );
        }
```

Any idea what’s going on ?

**Comment by parched** [comment]
The operand for the "i" constraint must be constant, so in general this won't work.

1. The code is completely optimised away because it isn't used. For me it fails with optimisation turned on.

2. If there is only one variant it is optimised to a constant 0.

3.  A literal is a constant so that is expected. 

4.  & 5. These always fail for me.

**Comment by DominusCarnufex** [comment]
Actually, you’re right. I was trying to use this to get around a bug I was having on OS X, but I managed to find where the bug came from and to resolve it, so let’s forget this idea.

I’m closing the issue.
