### ISSUE TITLE
Can create trait objects with self-containing bounds

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#38604]
## Meta
```
rustc 1.15.0-nightly (71c06a56a 2016-12-18)
```

## STR

```Rust
trait Q<T:?Sized> {}
trait Foo where u32: Q<Self> {
    fn foo(&self);
}

impl Q<()> for u32 {}
impl Foo for () {
    fn foo(&self) {
        println!("foo!");
    }
}

fn main() {
    let _f: Box<Foo> = Box::new(());
}
```

## Expected Result

`Box<Foo>` is not well-formed, because `u32: Q<Foo>` does not hold.

## Actual Result

Code compiles.

This does not seem to cause any trouble, but is a potential future-compatibility hazard if we start elaborating these bounds.

**Comment by nikomatsakis** [comment]
Discussed in compiler team meeting. This is also an @rust-lang/lang thing, so cc @rust-lang/lang. It does seem like it'd be better to make any trait that references `Self` in bounds as being not object-safe, as much as a precautionary measure as anything else, but we decided to first run a crater run and measure impact in any case. @arielb1 has a branch that can be adapted.

**Comment by aturon** [comment]
I agree with taking this conservative step.
