### ISSUE TITLE
Spurious segfault in tests for musl

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#38618]
[First seen](https://travis-ci.org/rust-lang/rust/jobs/186801430) on Travis, the error looks like:

```
     Running build/x86_64-unknown-linux-gnu/stage2-std/x86_64-unknown-linux-musl/release/deps/coretest-a84303f8bbcf2658
running 607 tests
..........................................................................................................................................................................................................................................................................................................................ii....................................................................................................................................................................................................................................................error: process didn't exit successfully: `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-unknown-linux-musl/release/deps/coretest-a84303f8bbcf2658 --quiet` (signal: 11, SIGSEGV: invalid memory reference)
To learn more, run the command again with --verbose.
command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "-j" "4" "--target" "x86_64-unknown-linux-musl" "--release" "--frozen" "--manifest-path" "/checkout/src/rustc/std_shim/Cargo.toml" "--features" "panic-unwind jemalloc backtrace" "-p" "std_shim" "-p" "core" "-p" "std" "-p" "libc" "-p" "compiler_builtins" "-p" "unwind" "-p" "build_helper" "-p" "std_unicode" "-p" "rand" "-p" "alloc" "-p" "alloc_system" "-p" "collections" "-p" "panic_abort" "--" "--quiet"
```

cleaned up as:

```
error: process didn't exit successfully: `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-unknown-linux-musl/release/deps/coretest-a84303f8bbcf2658 --quiet` (signal: 11, SIGSEGV: invalid memory reference)
```

This means that the *test harness itself* segfaulted. Sounds quite suspicious!

**Comment by est31** [comment]
maybe the actual failing test has nothing to do with the actual issue, but counting the dots, the test that's failing is number 560, which is `test ptr::test_as_mut`.

**Comment by est31** [comment]
err, that was the last one that succeeded, the one which would come next is `ptr::test_as_ref`

**Comment by alexcrichton** [comment]
@est31 sounds plausible! Note though that tests are run in parallel so I don't think we can know for certain which test failed, unfortunately :(

I'll also note that I tried running this locally thousands of times, but none of them segfaulted :(

**Comment by alexcrichton** [comment]
Looks like [this just happened in collectionstest as well](https://travis-ci.org/rust-lang/rust/jobs/187333971). Still musl specific.

**Comment by alexcrichton** [comment]
After running all of these test suites locally thousands of times I'm still unable to reproduce. I'm not entirely sure what's going on here..

**Comment by williamtcellio** [comment]
I'm getting this error on Mac OSX with Rust stable 16.0. It is spurious, but I created a repro for it that seems to produce it about every other time I run cargo test https://github.com/saarw/testcrash/tree/master

**Comment by alexcrichton** [comment]
Debugging this a bit, I took the two most recent failures and diffed the set of tests which completed successfully from the previous successful run. The two diffs I got were:

* [diff1](https://gist.github.com/alexcrichton/78337d009c541fb874f80838f1b20dd5)
* [diff2](https://gist.github.com/alexcrichton/ee01ad3f20afeca8f97394f4ff51454f) 

I was hoping that perhaps one test was spuriously segfaulting, but that does not appear to be the case.

**Comment by alexcrichton** [comment]
FWIW I got ssh into a travis builder and reproduced this. I did not have enough time and focus to collect a core dump to debug further, unfortunately. I will attempt to do so soon.

**Comment by alexcrichton** [comment]
@Mark-Simulacrum has done some amazing work and finally got a stack trace! With the stack trace I believe this is a [bug in musl](http://www.openwall.com/lists/musl/2017/06/01/4), but I'll be staying tuned to that thread to see how it develops! I'll keep this updated with findings there.

**Comment by alexcrichton** [comment]
The bug with musl [has been confirmed](http://www.openwall.com/lists/musl/2017/06/01/6), so now we're basically just waiting on a fix.

**Comment by alexcrichton** [comment]
There's a [patch on the mailing list](http://www.openwall.com/lists/musl/2017/06/18/1) to fix this.

**Comment by alexcrichton** [comment]
Musl hasn't been updated yet, but I've heard that it's going to be fixed before the next release, although it's unclear when the next release will be.

**Comment by alexcrichton** [comment]
This hasn't shown up in quite some time now so perhaps it was indeed fixed with the last musl update!
