### ISSUE TITLE
Unhelpful error message using impl trait to return a closure.

### ISSUE THREAD

**Issue by peterjoel** [rust-lang/rust#38615]
The following code ([Rust Playground link](https://is.gd/wJ4EkR))
```Rust
fn create_recorder<'a>(log: &'a mut Vec<String>) -> impl FnMut(&'a String) {
    let handler = |msg: &String| -> () {
        log.push(format!("The messages was: {}", msg));
    };
    handler
}
```

produces the error:

```
rustc 1.15.0-nightly (71c06a56a 2016-12-18)
error[E0564]: only named lifetimes are allowed in `impl Trait`, but `` was found in the type `[closure@<anon>:4:19: 6:6 log:&mut &'a mut std::vec::Vec<std::string::String>]`
 --> <anon>:3:53
  |
3 | fn create_recorder<'a>(log: &'a mut Vec<String>) -> impl FnMut(&'a String) {
  |                                                     ^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

This error can be gotten rid of, by adding a lifetime constraint:
```
fn create_recorder<'a>(log: &'a mut Vec<String>) -> impl FnMut(&'a String) + 'a {
```
 
But that still leaves an error about borrowing the `log` reference:

```
error[E0373]: closure may outlive the current function, but it borrows `log`, which is owned by the current function
```

Fixing this (by making the closure a `move`, as is suggested) doesn't require the named lifetime, so really the error second error message should be the only one presented.

**Comment by Seeker14491** [comment]
I ran into this too, but returning an iterator. In my case adding the lifetime is required in addition to marking the closure `move`.

[Playground](https://play.rust-lang.org/?gist=856972d8f83798e4cea7e9f44bf1081d&version=nightly)

```rust
fn apply_permutation<'a, T>(
    objects: &'a [T],
    permutation: &'a [usize],
) -> impl Iterator<Item = T> + 'a
where
    T: Copy,
{
    permutation.iter().map(move |&i| objects[i])
}
```

**Comment by gnzlbg** [comment]
I ran into this too while trying to return a generator...

```rust
#![feature(generators, generator_trait, conservative_impl_trait)]
use std::ops::{Generator};

struct Stack { 
    x: i32
}

impl Stack {
    fn new(x: i32) -> Stack { Stack{x: x} }
    fn gen(& mut self) -> impl Generator<Yield=i32,Return=()> { 
 // fn gen<'a>(&'a mut self) -> impl Generator<Yield=i32,Return=()> + 'a { 
        move || { for _i in 0..10 { self.x = self.x + 1; yield self.x; } return (); } 
    }
}
```
(The commented out line is the correct signature)

The error message is not useful, at all: 

```shell
   Compiling playground v0.0.1 (file:///playground)
error[E0564]: only named lifetimes are allowed in `impl Trait`, but `` was found in the type `[generator@src/main.rs:13:9: 13:86 self:&mut Stack ((), std::ops::Range<i32>, i32, fn(std::ops::Range<i32>) -> <std::ops::Range<i32> as std::iter::IntoIterator>::IntoIter {<std::ops::Range<i32> as std::iter::IntoIterator>::into_iter}, Stack)]`
  --> src/main.rs:11:27
   |
11 |     fn gen(& mut self) -> impl Generator<Yield=i32,Return=()> { 
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This error message is so bad that it should IMO block the stabilization of conservative impl trait (@withoutboats).

Also, when I click the E0564 on the playground it sends me to a page that doesn't contain an explanation for it. Maybe that is a playground bug, and the playground should be sending me to some nightly page... Anyhow, this doesn't make this any better.

**Comment by gnzlbg** [comment]
The issues #43719 and #39722 seem to be duplicates of this one. 

I've just rechecked, and the playground does indeed have a bug (https://github.com/integer32llc/rust-playground/issues/207) in that the playground always links to the stable error explanations and not to the nightly ones when compiling with nightly. 

However, the error at hand here, E0564, doesn't have an explanation at all. 

Trying to return closures/generators, and trying to return iterators, seem to be the most common cause of triggering this error in all the issues currently filled, so maybe an explanation should cover that.

**Comment by cramertj** [comment]
This has been fixed.

**Comment by estebank** [comment]
Current output:

```
error[E0373]: closure may outlive the current function, but it borrows `log`, which is owned by the current function
 --> src/main.rs:5:19
  |
5 |     let handler = |msg: &String| -> () {
  |                   ^^^^^^^^^^^^^^^^^^^^ may outlive borrowed value `log`
6 |         log.push(format!("The messages was: {}", msg));
  |         --- `log` is borrowed here
help: to force the closure to take ownership of `log` (and any other referenced variables), use the `move` keyword
  |
5 |     let handler = move |msg: &String| -> () {
  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^
```

The suggestion is correct.
