### ISSUE TITLE
VecDeque<T> should implement PartialEq with &[T]

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#38625]
I believe this is definitely possible (comparing the iterators of each), and I suspect that there's a more efficient method as well.

See this documentation PR where it simplifies the code: https://github.com/rust-lang/rust/pull/38581/files#diff-266e22074e3b36596081857cbf5b1513R1256.

**Comment by frewsxcv** [comment]
I'm working on this.

**Comment by frewsxcv** [comment]
I ran into an issue. 

https://github.com/rust-lang/rust/blob/a9ab7788150d19e44419c3b153336aa24ad830b9/src/libcollections/vec_deque.rs#L2530-L2531

These now become errors:

```
error[E0282]: unable to infer enough type information about `_`
    --> src/libcollections/vec_deque.rs:2497:17
     |
2497 |             let expected = (0..).take(len).collect();
     |                 ^^^^^^^^ cannot infer type for `_`
     |
     = note: type annotations or generic parameter binding required

error: aborting due to previous error
```

**Comment by frewsxcv** [comment]
Is this inference issue allowed breakage?

**Comment by bluss** [comment]
It's definitely allowed, but not every allowed type inference breakage is a good idea. So it still has to be decided carefully.

**Comment by Mark-Simulacrum** [comment]
@frewsxcv Mind posting a PR? Perhaps we can find a way to fix the inference breakage.

**Comment by frewsxcv** [comment]
Opened a PR: https://github.com/rust-lang/rust/pull/38661.

**Comment by bombless** [comment]
I think that inference failure was there long before Rust 1.0
https://is.gd/j8KMA1

**Comment by frewsxcv** [comment]
It occurs because prior to this PR, the only thing you could compare `VecDeque` with was another `VecDeque`, so the compiler knew to `collect` into a `VecDeque`. Now that it can compare `VecDeque` with `VecDeque` *or* `Vec`, it doesn't know which one to choose.
