### ISSUE TITLE
Macros don't work in struct declarations

### ISSUE THREAD

**Issue by YaLTeR** [rust-lang/rust#38633]
https://is.gd/qo9P1O

```rust
macro_rules! a {
    () => (
        _field: ()
    );
}

struct S {
    a! {}
}
```

Gives an error:
```
error: expected `:`, found `!`
 --> <anon>:8:6
  |
8 |     a! {}
  |      ^
```

Expected: generated code like

```rust
struct S {
    _field: ()
}
```

**Comment by Mark-Simulacrum** [comment]
Marking as a diagnostics issue, it'd be great to give a message in this case corresponding to where macros can be used.

**Comment by Centril** [comment]
cc @petrochenkov -- I think we should close this, as it would be too hacky and arbitrary to provide good diagnostics in this case.

**Comment by petrochenkov** [comment]
I agree.
