### ISSUE TITLE
Remove deprecation warning for --crate-type=metadata

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#38640]
UPDATE: Very easy way first bug! [Mentoring instructions here.](https://github.com/rust-lang/rust/issues/38640#issuecomment-304306325)

-----

This didn't spend long in the wild, so we don't need to wait too long. But, Cargo does rely on the flag, so we should leave it in at least long enough to fix Cargo and for people to upgrade.

**Comment by Mark-Simulacrum** [comment]
It's been 5 months; nominating for compiler team discussion to remove `--crate-type=metadata`.

**Comment by nikomatsakis** [comment]
Let's remove it! All it takes, I believe, is to kill [this snippet of code found here](https://github.com/rust-lang/rust/blob/2f278c57ff4a805941f1497f34b3ad20b6f8e13b/src/librustc/session/config.rs#L1645-L1651).
