### ISSUE TITLE
s/try!/?/g in documentation examples

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#38644]
Now that `?` is stable, documentation should be updated to use it instead of `try!`. `try!`'s docs should probably have a once-over, as well.

PRs to do this in any amount will be welcome, even just one examples!

**Comment by tshepang** [comment]
am curious why the downvotes

**Comment by josephpd3** [comment]
Sorry if I'm out of place in commenting as a total stranger in the Rust repo, but I'm down to help--though I can see why it's a bit on the fence for some.

I feel if the solution to this issue (either sticking to `try` or `?` wholly or drawing the line that @fhartwig suggests) is in line with a practice to make doc examples more idiomatic. That has a sort of consistency in example I feel really builds to having more visually cohesive APIs--coming from Python myself, at least.

As I said, I would love to help if it is needed and will start on a PR, but I feel as if more discussion could only make a resolution more robust here.

**Comment by steveklabnik** [comment]
@josephpd3 https://github.com/rust-lang/rust/pull/38648 is already a PR, so I _think_ we have it covered. Reviewing that would be helpful though!

**Comment by josephpd3** [comment]
@steveklabnik gotcha! Wasn't sure if those changes to `libstd` was the extent of the desired changes or just a part of them. I should've peeked at that PR more. I'll go check it out and help review as I'm able.

**Comment by mgattozzi** [comment]
@steveklabnik did #38648 get them all or is this still open to get worked on?

**Comment by steveklabnik** [comment]
I think this got all of them; if you find an example using `try!`, please send in a PR!
