### ISSUE TITLE
`Signs` in `fmt` documenation

### ISSUE THREAD

**Issue by cbreeden** [rust-lang/rust#38677]
cf: <https://doc.rust-lang.org/std/fmt/index.html#sign0>

>  `+` - This is intended for numeric types and indicates that the sign should always be printed. Positive signs are never printed by default, and the negative sign is only printed by default for the  Signed trait. This flag indicates that the correct sign (+ or -) should always be printed.

This can't be accurate as there is no `Signed` trait anymore.  Though, it's unclear to me if `+` is even allowed in formatting, so I don't feel comfortable modifying the docs here.

**Comment by brson** [comment]
Should probably just say "for signed types".

**Comment by dbrgn** [comment]
This can be closed as #38704 is merged, right?

**Comment by cbreeden** [comment]
Yup, forgot about that, thanks!
