### ISSUE TITLE
TAGS targets (for emacs and vi integration) disappeared from Makefile

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#38678]
We used to have a collection of targets for generating so-called TAGS tables, which could then be read into one's editor for source navigation.

But with the revisions to the configure and build system to use `rustbuild` by default, those targets see to have disappeared.

**Comment by Mark-Simulacrum** [comment]
Well, these are now probably gone into git history completely; do we want these? If so, they should probably be re-added into rustbuild itself.

**Comment by kennytm** [comment]
Final appearance of the relevant file:

https://github.com/rust-lang/rust/blob/4711ac314/mk/ctags.mk

**Comment by jyn514** [comment]
@pnkfelix would you still find this useful? I don't know how many people are still using tags now that rust-analyzer works reasonably well on the compiler.

**Comment by jyn514** [comment]
I'm going to close this; people using vim or emacs can use rust-analyzer with an LSP plugin (docs: https://rustc-dev-guide.rust-lang.org/building/suggested.html#neovim).
