### ISSUE TITLE
Boxes displayed around item names in docs in nightly

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#38696]
See https://doc.rust-lang.org/nightly/std/io/trait.Read.html#method.chars. Every item has a one pixel black border that looks poor.

cc @bluss

**Comment by nagisa** [comment]
Similarly https://doc.rust-lang.org/nightly/std/io/trait.Read.html#method.read_exact has stabilisation version in a wrong place (caused by https://github.com/rust-lang/rust/pull/38329). The linked commit may be the cause of this issue too.

**Comment by ollie27** [comment]
This was my bad. It was caused by #38329. Sorry about that. It should have been by #38671.

**Comment by alexcrichton** [comment]
Closing now that https://github.com/rust-lang/rust/pull/38671 landed, thanks @ollie27!
