### ISSUE TITLE
vendored dependendencies are incomplete in the beta and nightly tarballs

### ISSUE THREAD

**Issue by dvc94ch** [rust-lang/rust#38690]
The process of creating the tarballs doesn't include .gitignore files from src/vendor. This results in a missmatched hash failure when building with vendoring enabled. Hoping to switch to rustbuild with the next rust release!

FYI: I'd be happy with the vendoring happening during the create tarball process, having enormous vendoring commits in the git history is ugly...

![screenshot from 2016-12-29 22-06-37](https://cloud.githubusercontent.com/assets/741807/21554818/16524cd6-ce13-11e6-8454-10c48b133cce.png)

**Comment by brson** [comment]
Needs to be fixed for 1.15.

**Comment by brson** [comment]
cc @alexcrichton

**Comment by brson** [comment]
Seems like the vendoring process should include a sanity check that the vendored sources hash correctly.

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rust-lang/rust/pull/38708

**Comment by dvc94ch** [comment]
Things move fast around here. Awesome thanks!
