### ISSUE TITLE
"x.py build" generates test tools for all stages, even though they are not needed

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#38705]
Often I just want to test bootstrap, and maybe the test suite on stage2. However, a recent (maybe 3 days ago - now) change has made `x.py build` generate test artifacts for all stages. I'd prefer if it didn't build them, keeping `x.py` focussed on bootstrap itself.

cc @alexcrichton

**Comment by alexcrichton** [comment]
Thanks for the report! I'm not *quite* sure I understand what you mean here, but you may be interested in https://github.com/rust-lang/rust/pull/38667. Does that solve what you're thinking of here?

**Comment by est31** [comment]
@alexcrichton its doing "Building stage1 test artifacts" now, didn't do it before.

**Comment by est31** [comment]
Mhh, seems it built before as well, I just didn't notice it.
