### ISSUE TITLE
ICE; two sources of truth on how stuff is returned do not agree with each other

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#38727]
Consider this code:

```rust
#![feature(no_core, lang_items,start)]
#![no_std]
#![no_core]
#[lang="sized"] trait Sized {}
#[lang="copy"] trait Copy {}

#[repr(u64)]
enum A {
    A = 0u64,
    B = !0u64,
}

fn cmp() -> A {
    A::B
}

#[start]
fn main(b:isize, a: *const *const u8)->isize { 0 }
```

if compiled targetting `i686` target, this ICEs with

```
error: internal compiler error: ../src/librustc_trans/mir/operand.rs:82: impossible case reached
```

---

This is because ABI code claims that this u64 enum has to be returned via value (i.e. `ret i64 %smth`):

```
FnType { args: [], ret: ArgType { kind: Direct, original_ty: i64, ty: i64, signedness: Some(false), cast: None, ... }
```

Whereas MIR only has `OperandRef(Ref(...))` because the [`common::is_immediate_type`](https://github.com/rust-lang/rust/blob/6dcf51aae61dcad1dbe7eef3766df2facef73816/src/librustc_trans/mir/operand.rs#L158) returns false for this enum. [Calling `immediate()` on this `OperandRef`](https://github.com/rust-lang/rust/blob/6dcf51aae61dcad1dbe7eef3766df2facef73816/src/librustc_trans/mir/block.rs#L223) then causes this ICE.

This is a regression from the old->MIR trans move.

**Comment by nikomatsakis** [comment]
cc @eddyb, who has done a lot of poking at this infrastructure.

@nagisa, did you have a feeling for which is correct?

**Comment by eddyb** [comment]
Ugh, `.immediate()` is so risky. IMO the correct thing to do is to force a load if it's by-ref (can't remember exactly what APIs are available atm, but worst-case it's a `match` with `bcx.load(llref)` for `Ref(llref)`).

**Comment by nagisa** [comment]
Why `common::is_immediate_type` returns false here?

**Comment by eddyb** [comment]
Both the ABI and the immediate check are correct IMO.

The problem isn't that they don't agree, the problem is that we have code that *incorrectly assumes* that they always do.

The ABI rules can be weird and we might even end up supporting several conflicting calling convention ABIs per platform, so we should just do the load there instead of trying to force it to be immediate.

**Comment by eddyb** [comment]
Yes, @Mark-Simulacrum has just started playing with it. The short version is "always load if you need an immediate instead of panicking".

**Comment by nikomatsakis** [comment]
triage: P-high
