### ISSUE TITLE
rustc --version malloc_zone_unregister failed

### ISSUE THREAD

**Issue by alexbowers** [rust-lang/rust#38728]
![image](https://cloud.githubusercontent.com/assets/842974/21575280/2e7d8a2c-ceff-11e6-80ef-9158fa415580.png)

**Comment by alexbowers** [comment]
I appeared to already have rust installed, probably from a while ago. I managed to uninstall and reinstall, and it seemed to be okay after that.

**Comment by alexcrichton** [comment]
Ah yes this was a bug that historical versions of the compiler suffered but has long since been fixed. Thanks for the report though!
