### ISSUE TITLE
Remove is_like_X flags from target specs

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#38732]
Today target specs have `is_like_openbsd`, `is_like_osx`, `is_like_solaris`, `is_like_windows`, `is_like_android`, `is_like_msvc` fields. These all seem to amount to querying `target_os`. They could instead be methods on target spec.

cc https://github.com/rust-lang/rust/issues/36900#issuecomment-269849487

**Comment by nagisa** [comment]
When I was writing https://github.com/rust-lang/rfcs/pull/1711/files#diff-e744efb4e5bbd5cb8367e92f69880075R78, it didn’t seem to me that `target_os` and `is_like*` are orthogonal. The RFC I linked here also has a proposal on how to adjust target spec to get rid of these `is_like` fields :)

**Comment by jackh726** [comment]
Going to go ahead and close this, since this might not even be possible, and is old enough that nobody will probably work on this.

**Comment by petrochenkov** [comment]
cc https://github.com/rust-lang/rust/pull/98214
