### ISSUE TITLE
document behavior of collect() for empty iterators

### ISSUE THREAD

**Issue by generalelectrix** [rust-lang/rust#38747]
Not sure where this would belong, as it certainly comes down to implementation details of different collections.  However, in the common case of collect()ing an iterator into a Vec, it would be helpful if there was documentation somewhere that makes it clear that _collecting an empty iterator into a Vec does not perform a memory allocation_.

In my case I had a happy path where the iterator would be empty, indicating an absence of error states, and I wanted to ensure that this path doesn't involve an allocation.  I was using a workaround where I'd use peekable, and peek at the first element and only .collect() in the case where I had at least one element.  I asked on IRC and they clarified that no allocation takes place for an empty iterator.

**Comment by djzin** [comment]
It appears that the docs for `Vec` already have what you describe:

```
fn new() -> Vec<T>

Constructs a new, empty Vec<T>.
The vector will not allocate until elements are pushed onto it.
```

https://doc.rust-lang.org/stable/std/vec/struct.Vec.html

It is not the iterator that allows the allocation to be skipped; but rather the implementation of `FromIterator` for `Vec<T>`. One can easily construct a container that *would* allocate when collected into:

```rust
use std::iter::FromIterator;

struct MyVec<T>(Vec<T>);

impl<T> FromIterator<T> for MyVec<T> {
    fn from_iter<I>(iter: I) -> Self 
        where I: IntoIterator<Item=T>
    {
        println!("allocating space for 100 elements");
        let mut this = MyVec(Vec::with_capacity(100));
        for elem in iter {
            this.0.push(elem);
        }
        this
    }
}

fn main() {
    let _: MyVec<i32> = None.into_iter().collect();
}
```

**Comment by generalelectrix** [comment]
Hmm, I wasn't even aware of that behavior for Vec, I still thought Vec::new() allocated immediately with a standard capacity.  Either my understanding is out of date or was just always wrong :)  Moreover, the documentation of the mechanism and how to go see how it works for the collection of your choice is part of the damn trait method signature, so really no more docs are necessary here.  Thanks!
