### ISSUE TITLE
Update Readme Instructions for 32-bit MinGW Builds

### ISSUE THREAD

**Issue by camlorn** [rust-lang/rust#38743]
I found out this was incorrect when I had to build Rust on 32-bit Windows for a failing test to do with #37429.  I want to say it was @alexcrichton who gave me the workaround of downloading the zip the CI server uses.  I mentioned updating it on IRC in the same conversation, but that doesn't seem to have happened yet, so I figured I'd open an issue.  I believe it is correct for x64, but haven't tried.

**Comment by alexcrichton** [comment]
Thanks for the report @camlorn! To clarify, what's happening here is:

* The README provides working 64-bit instructions
* The README then says "s/x86_64/i686/" if you're on 32-bit, but this is wrong.
* On 32-bit, the `gcc` compiler coming from pacman is always compiled with the pthread threading model, which Rust is incompatible with
* We need to recommend downloading a compiler with the win32 threading model and dwarf exceptions

Overall I think we should recommend MSVC first, then 64-bit GNU, then 32-bit GNU if we really need to, but ideally we could relegate this information to outside the readme as it's "weird to follow"

**Comment by camlorn** [comment]
As I read the readme, it is currently implying that you need MinGW to perform a MSVC build, as the first paragraph mentions other dependencies that are perhaps not needed.  Given that Windows is my primary platform, it is ironic that I have not yet built Rustc under MSVC.

As a concrete solution, perhaps:

- Move the MSVC section up and edit it to stop mentioning MinGW or implying that you need MinGW installed.

- Remove the bit about replacing in the MinGW section, change the header to say that it's "MinGW X64" or something, and possibly mention that we encourage Windows users to use the MSVC version whenever possible.

- Add a section about how to get a 32-bit build under MinGW working, possibly linking to another document or just telling people they need the CI 7zip.

**Comment by steveklabnik** [comment]
Triage: the README still says:

> If you're building a 32-bit compiler,  then replace "x86_64" below with "i686".

**Comment by mati865** [comment]
AFAIK 32 bit MinGW builds are fine nowadays.

**Comment by mati865** [comment]
I've build Rust with 32-bit MinGW like dozen times now and there are no issues with the README steps. We can close this I think.
