### ISSUE TITLE
Publish docs for `proc_macro` crate

### ISSUE THREAD

**Issue by abonander** [rust-lang/rust#38749]
Documentation for the `proc_macro` crate currently does not appear in nightly builds, at least for Windows. This isn't too big of a deal for now as the API is quite simple, but it would still be nice if this crate appeared in the documentation.

**Comment by est31** [comment]
Unofficial docs are available at: http://manishearth.github.io/rust-internals-docs/proc_macro/index.html

Still, I wonder how it could be stabilized without making docs available.

**Comment by steveklabnik** [comment]
Nominating, as this is supposed to be stable in 1.15, and will need a backport.

**Comment by steveklabnik** [comment]
(Tagging compiler because I imagine that this needs to be un-blacklisted somewhere or something?)

**Comment by SimonSapin** [comment]
I *think* it’s a one-liner: #39986
