### ISSUE TITLE
Question about http://rustbyexample.com/hello/print.html example

### ISSUE THREAD

**Issue by moreaki** [rust-lang/rust#38759]
The current example reads:

`println!("{} of {:b} people know binary, the other half don't", 1, 2);`

Would it be more correct to state:

`println!("{} of {:b} people know binary, the other half doesn't", 1, 2);`

Since we probably assume a binary world, half of the set is singular, which probably also means we need to adjust the wording.

**Comment by steveklabnik** [comment]
Could you file this against https://github.com/rust-lang/rust-by-example please? Thanks!

**Comment by moreaki** [comment]
My apologies, didn't realize this. Filed a new one: https://github.com/rust-lang/rust-by-example/issues/829.

Thanks for letting me know.
