### ISSUE TITLE
Could we access associated type out of a struct?

### ISSUE THREAD

**Issue by hicqu** [rust-lang/rust#38774]
here is a piece of code:
```
trait A {
    type AA;
}

struct S;

impl A for S {
    type AA = String;
}

// how to access AA out of S?
let aa_instance = S::AA::new();    // wrong
let aa_instance = (S as A)::AA::new();    // wrong
```

could you help me? Thanks!

**Comment by petrochenkov** [comment]
@hicqu 
```
let aa_instance = <S as A>::AA::new();
```

`S::AA::new()` is supposed to work too, but it's not implemented yet. It's a [long standing issue](https://github.com/rust-lang/rust/issues/19559) and the fix is non-trivial.

**Comment by steveklabnik** [comment]
@hicqu generally, http://users.rust-lang.org/ is the right place to ask for help.

Since @petrochenkov has given you an answer, I'm going to give this a close. Thanks!
