### ISSUE TITLE
"error: expected one of `,`, `.`, `?`, or an operator" list is incomplete

### ISSUE THREAD

**Issue by Timmmm** [rust-lang/rust#38777]
Take this real code I just wrote:

		let text = Text::new()
						.set("x", 200) 
						.set("y", lifetime.starting_line*20 + 20)
						.set("class", "annotation")
						.add(svg::node::Text::new(markdown::to_html(&lifetime.markdown));

It gives this error:

```
note: unclosed delimiter
   --> src\main.rs:142:11
    |
142 | 						.add(svg::node::Text::new(markdown::to_html(&lifetime.markdown));
    | 						    ^

error: expected one of `,`, `.`, `?`, or an operator, found `;`
   --> src\main.rs:142:71
    |
142 | 						.add(svg::node::Text::new(markdown::to_html(&lifetime.markdown));
    | 						                                                                ^

```

Ok so it does give me a *note* about an unclosed delimiter, but the actual error says

    error: expected one of `,`, `.`, `?`, or an operator, found `;`

I'm pretty sure `)` isn't an operator, so isn't that list wrong? Shouldn't it say

    error: expected one of `,`, `.`, `?`, `)`, or an operator, found `;`

**Comment by Crazycolorz5** [comment]
I'll look into this.

**Comment by Timmmm** [comment]
Also think about this again, if the unexpected symbol is `;` it's pretty guaranteed that it is a missing bracket so you could give a much friendlier message, and even a fixit in that case (insert an appropriate number of `)`s before the semicolon.

**Comment by Crazycolorz5** [comment]
I'm not sure how implementing a fixit would work. I can say that counting the number of appropriate )'s is nontrivial due to the recursive nature of the parser, though. But recursively inserting them to terminate sequences (to recover from an error) should be fairly simple.

**Comment by Timmmm** [comment]
Yeah I dont know how the parser works but the logic should be something like "if I found a ; but there aren't enough )'s, offer enough )'s so that they match". If that's not easy then fair enough.

**Comment by Crazycolorz5** [comment]
Well, also, I don't believe that we should accept programs with unclosed parens. I believe the current behavior of printing an error should be correct.

**Comment by Timmmm** [comment]
I didn't mean that the parser should actually add them in - it should offer a fixit.
