### ISSUE TITLE
impl AddAssign<char> for String

### ISSUE THREAD

**Issue by Timmmm** [rust-lang/rust#38784]
Is there any reason there is an `impl AddAssign<&str>` for `String`, but not `impl AddAssign<char>`? Anyway it's something I would expect.

**Comment by Stebalien** [comment]
FYI, it was implemented for `&str` because there was already a stable implementation of `Add<&str>`. See https://github.com/rust-lang/rust/pull/34890

**Comment by Mark-Simulacrum** [comment]
Seems like something we shouldn't track, but would probably accept a PR for.
