### ISSUE TITLE
Get test suite working with wasm

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#38800]
Last I looked compiletest could not deal with wasm as outputted today by rustc because the binaryen interpreter expects the wasm file to be located in a specific relative path that compiletest does not set up correctly.

I recall the fix being a matter of refactoring compiletest to pass certain paths down to the process spawning node.

**Comment by brson** [comment]
This is still a critical wasm bug, and not a difficult one to fix. Run the test suite against the wasm target to see how it's currently broken. Most should simply be failing to load the wasm correctly. It should be possible to get verbose output from the test suite, then take that output and run the node.js test command by hand to figure out the correct invocation; then modify compiletest to do it correctly.

**Comment by derekdreery** [comment]
I'm going to have a look at this but I make no promises so someone else who wants to take it should do so.

**Comment by derekdreery** [comment]
OK my strategy is

 1. Make compiletest::procsrv::run and compiletest::procsrv::run_background take an extra parameter, `current_dir: Option<String>`, and if `Some` add `cmd.current_dir` to command.
 2. Pass None to these functions everywhere that calls them
 3. For emscripten, set it to `Some(self.output_base_name().parent())` in `compiletest::runtest::program_output`

I'm away for a few days so if this looks good I'll probably do it on wednesday :)

**Comment by derekdreery** [comment]
Oh and I also had to pass "-s BINARYEN_METHOD='native-wasm,interpret-binary'" as it defaulted to just `native-wasm`, which I think isn't implemented yet (I'm still trying to understand emscripten properly).

**Comment by alexcrichton** [comment]
I believe this has largely be done and can be verified with the containers in-tree, so closing.
