### ISSUE TITLE
Set up CI testing for asm.js and wasm

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#38801]
asm.js and wasm targets only have build CI today. They need tests to be run as well in order to maintain decent support.

I think there's a good chance we will lose asm.js support, at least temporarily, when we switch to the LLVM wasm backend, but as long as we do support asm.js we might as well test it too.

This should be a matter of changing the travis config to run the tests in a new container.

**Comment by brson** [comment]
@alexcrichton has done some work on this.

**Comment by alexcrichton** [comment]
This is [done](https://github.com/rust-lang/rust/tree/master/src/ci/docker/emscripten) now for emscripten! When wasm tests are passing we can set up CI.
