### ISSUE TITLE
test run-make/atomic-lock-free fails on i686 linux

### ISSUE THREAD

**Issue by djzin** [rust-lang/rust#38818]
stderr:
```
nm: rust.metadata.bin: File format not recognized
nm: atomic_lock_free.0.bytecode.deflate: File format not recognized
nm: atomic_lock_free.0.o: File format not recognized
nm: rust.metadata.bin: File format not recognized
nm: atomic_lock_free.0.bytecode.deflate: File format not recognized
make: *** [Makefile:12: all] Error 1
```

I looked into it and it seems the reason is that gnu binutils is not compiled with `--enable-targets=all` on my system (default arch install). This means that `nm` is not able to read symbols from x86_64 binaries and so the test fails.

Seems odd to have a dependency on the way binutils was compiled, especially one where for a major distro it is not set by default.

**Comment by nagisa** [comment]
We probably should just use objdump, as it, in my experience, cares less about formats and whatnot.

**Comment by carlorosati** [comment]
I have my own binutils installed with ```--enable-targets=all``` but it still fails.

**Comment by ishitatsuyuki** [comment]
Occurence in https://travis-ci.org/rust-lang/rust/jobs/259083175.

**Comment by jackh726** [comment]
Going to close this is "probably fixed" - not even sure how to begin to dig into this.
