### ISSUE TITLE
ICE with `#[derive(Copy)]`, missing trait bound, and blanket impl

### ISSUE THREAD

**Issue by sgrif** [rust-lang/rust#38821]
I have tested this on both 1.13 and on nightly-2016-12-28. This this is the script to reproduce: https://is.gd/PWV89w

The code is invalid due to missing constraint `Col::SqlType: IntoNullable` on line 26. The expected error is:

```
error[E0277]: the trait bound `<Col as Expression>::SqlType: NotNull` is not satisfied
  --> foo.rs:25:1
   |
25 |   pub enum ColumnInsertValue<Col, Expr> where
   |  _^ starting here...
26 | |     Col: Column,
27 | |     Expr: Expression<SqlType=<Col::SqlType as IntoNullable>::Nullable>,
28 | | {
29 | |     Expression(Col, Expr),
30 | |     Default(Col),
31 | | }
   | |_^ ...ending here: the trait `NotNull` is not implemented for `<Col as Expression>::SqlType`
   |
   = help: consider adding a `where <Col as Expression>::SqlType: NotNull` bound
   = note: required because of the requirements on the impl of `IntoNullable` for `<Col as Expression>::SqlType`
```

But the compiler instead ICEs. If `#[derive(Copy)]` is removed, the compiler gives the error message as expected. If the blanket `impl<T: NotNull> IntoNullable for T` (lines 10-12 in the script) is removed, the compiler gives the error message as expected.

**Comment by sgrif** [comment]
Slightly simplified repro script: https://is.gd/HXaz0L

**Comment by Mark-Simulacrum** [comment]
Errors today, which is I think correct. E-needstest.

```
error[E0277]: the trait bound `<Col as Expression>::SqlType: NotNull` is not satisfied
  --> <anon>:16:10
   |
16 | #[derive(Copy)]
   |          ^^^^ the trait `NotNull` is not implemented for `<Col as Expression>::SqlType`
   |
   = help: consider adding a `where <Col as Expression>::SqlType: NotNull` bound
   = note: required because of the requirements on the impl of `IntoNullable` for `<Col as Expression>::SqlType`

error: aborting due to previous error

```

**Comment by venkatagiri** [comment]
@Mark-Simulacrum I want to contribute the test for this issue.
By the example you have provided, my guess would be that we need an UI test in `src/test/ui/span/` with issue-38821.rs and issue-38821.stderr files.

Is that correct?

**Comment by Mark-Simulacrum** [comment]
@venkatagiri I think a compile-fail test would be enough here; we primarily want to just make sure it doesn't ICE. To do that, I'd say that [the example code](https://gist.github.com/anonymous/58333d19f924d19bac6449b7d75d965a) needs to be put into a file in `src/test/compile-fail` and annotated with the related messages. Let me know if you have any more questions; I'd be happy to help. Please r? me on the pull request when you create it.
