### ISSUE TITLE
document field init shorthand

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#38830]
RFC 1682 added "field init shorthand" (tracking issue is https://github.com/rust-lang/rust/issues/37340), which allows you to use a shorthand in struct literals:

```rust
struct Foo { x } => struct Foo { x: x }
```

This is implemented on nightly and we would like to stabilize it, but documentation is required. Here is a list of places where the documentation would need to be updated, kindly [prepared by @havvy](https://github.com/rust-lang/rust/issues/37340#issuecomment-269110849):

* [x] The [grammar](https://github.com/rust-lang/rust/blob/master/src/doc/grammar.md#structure-expressions) needs updating (PR: https://github.com/rust-lang/rust/pull/38956)
* [x] as would adding a section to [the book](https://github.com/rust-lang/rust/blob/master/src/doc/book/structs.md) and the new book. 
* [x] The [reference](https://github.com/rust-lang/rust/blob/master/src/doc/reference.md) would need a paragraph explaining the sugar.
* [ ] Additionally, we may want to add examples to Rust By Example showing the syntax.
* [ ] A changelog entry is needed. @Havvy proposes this short entry: "Added field init shorthand syntax when the field and variable names match."

I'm marking this as E-mentor, since updating these docs seems like a pretty good starter bug.

**Comment by steveklabnik** [comment]
yes, i am very happy to mentor anyone who needs help with this.

**Comment by 747f1c** [comment]
I am very happy to fix this issue

**Comment by steveklabnik** [comment]
@hngiang great! Please let me know if you need any assistance.

**Comment by hngiang** [comment]
@steveklabnik sorry for take a while to process, please help me review document in PR #39096

**Comment by nikomatsakis** [comment]
What is the status of this work now? :)

**Comment by steveklabnik** [comment]
@nikomatsakis basically, until we have the bookshelf, we're not landing doc PRs until they're the last thing holding up stabilization. https://github.com/rust-lang/rust/pull/39096 has some outstanding issues with it as well that need to be addressed before it's mergable.

**Comment by nikomatsakis** [comment]
@steveklabnik ok. To be clear, I think that a doc PR is indeed the only thing holding up stabilization here, so once those issues are addressed, I think we ought to merge.

**Comment by steveklabnik** [comment]
Okay. so, should we be doing that right now, to land stuff before the next release? or should we be waiting until after the branch? Has the next beta been branched?

**Comment by nikomatsakis** [comment]
@steveklabnik I don't care too much about whether this makes it into the next beta or not, we don't have to stress, but I would not *delay* either.

**Comment by hngiang** [comment]
I haven't been available these days due to the big holiday in my country, so I couldn't reach the topic. At the moment, I have some troubles in work and cannot fix these problems, I will ask @phungleson for help. Thanks.

**Comment by z1mvader** [comment]
I'd like to help in this one, I don't know a lot but I'm willing to learn :)

**Comment by steveklabnik** [comment]
@z1mvader thank you! As far as docs go, https://github.com/rust-lang/rust/pull/39459 has most of the work in it; maybe take a look at that and see if it makes sense to you? Leave a comment either way 😄

**Comment by est31** [comment]
As the changelog is created always when doing releases (at least [this history](https://github.com/rust-lang/rust/commits/master/RELEASES.md) seems to indicate that), I think nothing needs to be changed in the Rust git repo, right? So only Rust by example remains for this issue to be resolved?

**Comment by chriskrycho** [comment]
Though not *required* for this, I've gone ahead and [made an example](https://github.com/rust-lang/rust-by-example/pull/844), so you can mark that item as done as well!

**Comment by steveklabnik** [comment]
we have both https://github.com/rust-lang/rust-by-example/pull/844 and https://github.com/rust-lang/rust-by-example/pull/837 so i think this is all done now!

**Comment by zeyangl** [comment]
I know this feature is already implemented and closed. I'm trying to get it to work but fails for some reason. 

`
struct Color2
{
    pub r: i32,
}

fn handle_file()
{
    let tc = Color2{0};
}

fn main()
{
    println!("started...");
    handle_file();
}`

extremely obvious code here. Whenever I compile and run it. I get this error
error: expected identifier, found `0`
  --> src/main.rs:19:21
   |
19 |     let tc = Color2{0};
   |              ------ ^ expected identifier
   |              |
   |              while parsing this struct

Is there something really obvious that i am not getting? Appreciate the help!

**Comment by Havvy** [comment]
Yes. The shorthand lets you substitute e.g. `r: r` inside of `Color2{r: r}` with just `r` so it'd be `Color2{r}`. It doesn't let you pass values anonymously, so you'd want to do `Color2{r: 0}` and not use the shorthand in your example, or if you _really_ want to use the shorthand... `let r = 0; let tc = Color2{ r };`

**Comment by est31** [comment]
Adding to that, even though this works:

```rust
struct Tea(u32, u32);

fn main() {
    let t = Tea {
        0: 2,
        1: 3,
    };
}
```

This doesn't:

```rust
struct Tea(u32, u32);

fn main() {
    let 0 = 2;
    let 1 = 3;
    let t = Tea {
        0,
        1,
    };
}
```

**Comment by steveklabnik** [comment]
> I'm trying to get it to work but fails for some reason.

Generally, users.rust-lang.org or StackOverflow are better places to get help than adding more comments on closed bugs! In this case, you got an answer though :)
