### ISSUE TITLE
Unexpected "deprecated" warning when derive attribute for enum and enum has deprecated items

### ISSUE THREAD

**Issue by Mingun** [rust-lang/rust#38832]
Let's consider the following situation: there is a enumeration in which have an deprecated element. This enumeration derives implementation of some traits. In such case rustc generates deprecation warning, but actually deprecated item never used.

As in this case there is no control over the generated code, I consider that the warning shouldn't be. It is impossible to suppress warning also because the element is marked deprecated for the reason that he shouldn't be used obviously. If to suppress him, then meaning to mark a enumaration element as deprecated is lost.

Example of problem:
```rust
#![allow(dead_code)]
#[derive(Debug)]
enum Example {
    Var1,
    #[deprecated]
    Var2,
}
fn main() {
}
```
Output:
```
rustc 1.14.0 (e8a012324 2016-12-16)
warning: use of deprecated item, #[warn(deprecated)] on by default
 --> <anon>:6:5
  |
6 |     Var2,
  |     ^^^^
```
[play-pen](https://is.gd/Dt2WZn)

**Comment by RReverser** [comment]
Not disagreeing that this should likely be the default behavior, but just a suggestion - for now you can use following workaround by allowing deprecated items on `enum` itself:

```rust
#![allow(dead_code)]

#[derive(Debug)]
#[allow(deprecated)]
enum Example {
    Var1,
    #[deprecated]
    Var2,
}

fn main() {
}
```

In that case compiler won't warn on declaration itself, but will warn on any usages of `Example::Var2` as expected.

**Comment by Mingun** [comment]
I think that the solution proposed by @RReverser is enough for a solution and if the Rust team agrees with it, then this issue can be closed

**Comment by da-x** [comment]
This can be closed - in the playpen the original issue does not reproduces with stable.
