### ISSUE TITLE
Private types publicly accessible.

### ISSUE THREAD

**Issue by Aaronepower** [rust-lang/rust#38844]
This may be some misunderstanding on my part, but this seems like a bug. If a private type is exposed through a public field in a struct, rustc will not error. The below example will compile as a lib.

### Minimal Workable Example

```
use foo::Bar;

mod foo {
    pub enum Bar {
        Baz
    }
}

pub struct BarContainer(pub Bar);
pub struct FooBarContainer {
    pub inner: Bar,
}
```

# Rust version
```
rustc 1.14.0 (e8a012324 2016-12-16)
binary: rustc
commit-hash: e8a0123241f0d397d39cd18fcc4e5e7edde22730
commit-date: 2016-12-16
host: x86_64-apple-darwin
release: 1.14.0
LLVM version: 3.9
```

**Comment by durka** [comment]
What's the problem? `Bar` is indeed `pub`.

**Comment by Aaronepower** [comment]
@durka But foo is not. I only noticed this when I released ddg it had [a struct](https://docs.rs/ddg/0.2.0/ddg/struct.DdgResponse.html) which contains types that have no documentation or links, this may be more of an error with rustdoc than rustc, also those types were ignored for a compiler flag `#[deny(missing_docs)]` until I made the mod public, which would also imply that the types are private.

**Comment by durka** [comment]
As I understand it, `pub` means the item is public to the world -- but that doesn't mean it's accessible. It's only accessible if the chain of modules containing it is all `pub`. Accessibility can be controlled with re-exports. Publicity can be controlled in a more fine-grained way with `pub(restricted)` (still unstable).

**Comment by petrochenkov** [comment]
This is the intended behavior, see https://github.com/rust-lang/rust/issues/34537 for details.
