### ISSUE TITLE
Spurious timeout on Android when starting tests

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#38851]
I've seen this quite a few times now, such as https://travis-ci.org/rust-lang/rust/builds/189211288. The output just looks like:

```
[100%] /data/tmp/check-stage2-T-arm-li...wn-linux-gnu-rand-f9c348f81b18c152.log
[100%] /data/tmp/std-a7fd86a4919990b8
No output has been received in the last 30m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

I have no idea what's going on, and after running hundreds of times locally over the past few days I haven't been able to reproduce...

**Comment by malbarbo** [comment]
Is this fixed?

**Comment by alexcrichton** [comment]
AFAIK we haven't done anything to fix this and it comes up every now and then. It's been a few weeks since we've seen it though so maybe it was "accidentally" fixed?

**Comment by alexcrichton** [comment]
We just recently restructured how Android tests are run, so I'm going to close this.
