### ISSUE TITLE
Rustc does not recommend raising the recursion limit

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#38852]
It used to be that when you reach the macro recursion limit, rustc would recommend raising it and give the attribute to do so. This has been lost.

Expected Result:

Diagnostic tells how to increase recursion limit.

Actual Result:

No note/help.

Reproduce [(playground gist)](https://play.rust-lang.org/?gist=450998d6abe14d9d90e131ef9af79796&version=nightly&backtrace=0)

```rust
macro_rules! recurse {
    () => { };
    ($t:tt $($tail:tt)*) => { recurse!($($tail)*) };
}

fn main() {
    recurse!(0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9
             0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9
             0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9
             0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9);
}
```

**Comment by bluss** [comment]
rust.godbolt.org doesn't show the help to raise the limit for historical Rust release, maybe I am mistaken that this is a regression.

**Comment by durka** [comment]
There surely was a situation in which you could get the suggestion, and it won't regress because [there is a test](https://github.com/rust-lang/rust/blob/master/src/test/compile-fail/recursion_limit.rs#L45). But maybe it never showed up for macro evaluation?

**Comment by durka** [comment]
I can work on this.
