### ISSUE TITLE
Tracking issue for 'Allow `Self` to appear in the where clause of trait impls'

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#38864]
RFC: https://github.com/rust-lang/rfcs/blob/master/text/1647-allow-self-in-where-clauses.md

RFC PR: https://github.com/rust-lang/rfcs/pull/1647

Proposes allowing the `Self` type to be used in every position in trait implementations, including where clauses and other parameters to the trait being implemented.

**Comment by sgrif** [comment]
The RFC still isn't fully implemented. In particular, this example from the RFC text still fails to compile:

```rust
impl SomeTrait for SomeType where Self::AssocType: SomeOtherTrait {
    AssocType = SomeOtherType;
}
```

**Comment by eddyb** [comment]
@sgrif What's the error?

**Comment by Mark-Simulacrum** [comment]
https://is.gd/amqdSq:

```rust
struct SomeType;
struct SomeOtherType;

trait SomeTrait {
    type AssocType;
}
trait SomeOtherTrait {}

impl SomeTrait for SomeType where Self::AssocType: SomeOtherTrait {
    type AssocType = SomeOtherType;
}
fn main() {}
```

```
rustc 1.19.0-nightly (afa1240e5 2017-04-29)
error[E0275]: overflow evaluating the requirement `<SomeType as SomeTrait>::AssocType`
 --> <anon>:9:6
  |
9 | impl SomeTrait for SomeType where Self::AssocType: SomeOtherTrait {
  |      ^^^^^^^^^
  |
  = note: required because of the requirements on the impl of `SomeTrait` for `SomeType`

error: aborting due to previous error
```

**Comment by eddyb** [comment]
Ah that's not part of the actual syntactical support (which works!), but rather the trait system.
You can reproduce by expanding `Self::AssocType` to `<SomeType as SomeTrait>::AssocType`.
This looks like it was overlooked in the RFC, and I'd suggest opening a separate issue.
I suppose we can keep this one open and depend on that issue but they're unrelated IMO.
cc @rust-lang/lang

**Comment by steveklabnik** [comment]
According to the last comment here, it seems like maybe this is finished?

**Comment by sgrif** [comment]
The issue I raised still exists. I'm not sure how it was overlooked in the RFC, the example given from the RFC itself, and the text explicitly states that we'd like to be able to reference associated types from the trait being implemented. I agree that this is a fix that needs to happen in the trait system, not just syntactic support, but it is something the RFC calls out explicitly multiple times.

**Comment by petrochenkov** [comment]
Could you open a separate ticket please, focused on that specific bug?
This is a tracking issue for the feature in general, and the feature in general was implemented and stabilized.
