### ISSUE TITLE
members of ::std::u128 module must not be stable

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#38860]
Seems that #38482, while correctly making `use ::std::u128;` unstable, accidentally made the members of that module stable. This must not happen, and it may not leak to stable/beta. E.g. [this compiles](https://play.rust-lang.org/?gist=a8500d400480355d2dc1c9e0ce1bec9a&version=nightly&backtrace=0) : `println!("{}", ::std::u128::MAX);`.

cc #35118 (tracking issue)
cc @nagisa

**Comment by nagisa** [comment]
Adding `#![unstable(...)]` on top of these modules should be sufficient, right? Why is that not the case then?

There’s even a 

```
#[unstable(feature = "i128", issue = "35118")]
#[cfg(not(stage0))]
pub use core::i128;
```

in libstd/lib.rs…

**Comment by est31** [comment]
> Adding #![unstable(...)] on top of these modules should be sufficient, right?

seems this only makes [`use ::std::u128`](https://play.rust-lang.org/?gist=56a65844d17d12b3c34def84cc51c355&version=nightly&backtrace=0) fail compilation, but not the example above.

**Comment by est31** [comment]
Edited the issue description to contain the new findings.

**Comment by ollie27** [comment]
Looks like [`int_module!`](https://github.com/rust-lang/rust/blob/master/src/libcore/num/int_macros.rs) and [`uint_module!`](https://github.com/rust-lang/rust/blob/master/src/libcore/num/uint_macros.rs) need to take a stability attribute as an argument.
