### ISSUE TITLE
Tracking issue for std::collections::binary_heap::PeekMut::pop

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#38863]

**Comment by windwardly** [comment]
I wrote something similar today, committed, pulled to tip and got a conflict with your f2cb47.

I merged, replaced in my tests, calling my function with calling yours . Works! Yay!
Thank you.

**Comment by windwardly** [comment]
Better or worse flipping the lines around? Look more like a tail call:
```
        this.sift = false;
        this.heap.pop().unwrap()
```

**Comment by sfackler** [comment]
@rfcbot fcp merge

**Comment by jhjourdan** [comment]
Any reason why the parameter of `pop` is not `self` ?

**Comment by sfackler** [comment]
@jhjourdan `PeekMut` implements `Deref` so we don't want to implement any methods on it. If the type of values in your heap had a `pop` method, you would suddenly start calling this method instead.

**Comment by jhjourdan** [comment]
Oh, right. Sorry for the noise.
