### ISSUE TITLE
Clarify documentation on std::io::read_line

### ISSUE THREAD

**Issue by d33tah** [rust-lang/rust#38888]
Take a look at this SO answer and the comments:

http://stackoverflow.com/a/41210857/1091116

**Comment by steveklabnik** [comment]
tagging p-high, @frewsxcv is gonna take this one. Not a big thing, but we'll knock it out soon.

**Comment by frewsxcv** [comment]
This seems to be already addressed in https://github.com/rust-lang/rust/pull/36851. I also opened https://github.com/rust-lang/rust/pull/40642 that should clarify the behaviors of these `BufRead` methods. So I think this can be considered done unless anyone else has an action item here.
