### ISSUE TITLE
Inline asm: rdx and rcx mixed up in output

### ISSUE THREAD

**Issue by diwic** [rust-lang/rust#38905]
The following code: 

    #![feature(asm)]
    fn rdtsc() -> i64 {
        let z: i64;
        unsafe { asm!(
        "
        rdtsc
        shl $$32, %rdx
        or %rax, %rdx
        "
        : "=r{rdx}"(z)
        :
        : "rax"); 
        }
        z
    }

Causes the following (broken) asm:

	pushq	%rbp
	movq	%rsp, %rbp
	rdtsc
	shlq	$32, %rdx
	orq	%rax, %rdx
	movq	%rcx, -24(%rbp)  // Wrong - should be %rdx
	movq	-24(%rbp), %rax
	popq	%rbp
	retq

Notice how I wanted the result to be written to rdx, but instead its taking the value in rcx?!
If I instead use rax as output register, then rax is also what's returned, so it seems specific to rdx and rcx somehow.

Playground link: https://is.gd/COIXjk
Rustc nightly, 2017-01-06
Potentially related to issue #20659?

**Comment by nagisa** [comment]
`=r{rdx}` is a constraint that allows LLVM to pick EITHER `register` or `rdx`. To require register to be specifically `rdx`, you need to make the constrait `={rdx}` only.

**Comment by diwic** [comment]
Oh. Thanks for the triage, sorry for the noise.
