### ISSUE TITLE
#[target_feature="±<feat>"] is not properly checked against whitelist

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#38900]
`#[cfg(target_feature="abcd")]` was landed with a strong requirement to have a whitelist of LLVM features that are exposed this way, mostly due to compatibility concerns with LLVM.

`#[target_feature="±abcd"]`, however does not check against the whitelist in question and allows everything through. Seems like a potential compat footgun?

**Comment by est31** [comment]
cc @BurntSushi

**Comment by BurntSushi** [comment]
It was landed to make it possible to experiment with SIMD support in Rust. I would expect this question to be resolved in the stabilization effort. (But yes, I agree, it does certainly need to be checked.)

**Comment by alexcrichton** [comment]
This was fixed for https://github.com/rust-lang/rust/issues/44839
