### ISSUE TITLE
Type checker doesn't consider trait duality when reasoning about type parameters for associated types

### ISSUE THREAD

**Issue by bholley** [rust-lang/rust#38917]
See the testcase here: https://is.gd/WZh43I

I'd normally run this by a few people before filing an issue, but #rust is quiet on a Saturday night. ;-)

@Manishearth thoughts?

**Comment by Manishearth** [comment]
Trait resolution basically doesn't know how to figure out that two types are equal in the case of "dual traits".


This is one of the inevitable issues @nox is going to hit in his Servo script bindings refactor 😉 


I do wish we had a more formalized notion of type families that could be used to better instruct the compiler in these cases. @nikomatsakis was talking about this in [his blog](http://smallcultfollowing.com/babysteps/blog/2016/11/03/associated-type-constructors-part-2-family-traits/), and I've personally found the need for a family-trait type situation more than once, both when modeling dualities and when modeling generic abstractions over sets of types like you're trying to do.

**Comment by Mark-Simulacrum** [comment]
This appears to work today; E-needstest.

**Comment by nikomatsakis** [comment]
I don't think it works necessarily -- if you remove the bound that @bholley highlighted, you still get an error.

**Comment by nikomatsakis** [comment]
The example that @bholley expected to pass (and I think he is right that it should) is [this one](https://is.gd/uLQiVI):

```rust
use std::borrow::Borrow;

trait TNode: Sized {
  type ConcreteElement: TElement<ConcreteNode = Self>;
}

trait TElement: Sized {
    type ConcreteNode: TNode<ConcreteElement = Self>;
}

trait DomTraversal<N: TNode> {
    type BorrowElement: Borrow<N::ConcreteElement>;
}

fn recalc_style_at<E, D>()
    where E: TElement,
          D: DomTraversal<E::ConcreteNode>,
{
}


fn main() {
}
```

**Comment by estebank** [comment]
Current output:

```
error[E0277]: the trait bound `<D as DomTraversal<<E as TElement>::ConcreteNode>>::BorrowElement: std::borrow::Borrow<E>` is not satisfied
  --> src/main.rs:15:1
   |
11 |   trait DomTraversal<N: TNode> {
   |   ---------------------------- required by `DomTraversal`
...
15 | / fn recalc_style_at<E, D>()
16 | |     where E: TElement,
17 | |           D: DomTraversal<E::ConcreteNode>,
   | |                                            - help: consider further restricting the associated type: `, <D as DomTraversal<<E as TElement>::ConcreteNode>>::BorrowElement: std::borrow::Borrow<E>`
18 | | {
19 | | }
   | |_^ the trait `std::borrow::Borrow<E>` is not implemented for `<D as DomTraversal<<E as TElement>::ConcreteNode>>::BorrowElement`
```
