### ISSUE TITLE
on windows, string::from_utf8 error, while on linux not

### ISSUE THREAD

**Issue by DachuanXUAN** [rust-lang/rust#38924]
run on windows, the method string::from_utf8 error occur, while on linux not,
 reading the same file encoded with utf-8, make sure by vs code,
 that file contain chinese charactor. Error info are as below:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [229, 83, 68, 67, 85], error: Utf8Error { valid_up_to: 0 } }', ../src/libcore/result.rs:837

**Comment by jonas-schievink** [comment]
can you upload or post the file somewhere?

**Comment by DachuanXUAN** [comment]
Prohandle	              		My_UCDS_Prohandle                               ;	/* UCDS子进程句柄 */

**Comment by DachuanXUAN** [comment]
my fault, I must use it wrong somwhere, i should close this

**Comment by DachuanXUAN** [comment]
my program do have bugs, I process char as u8, and put u8 together as string, but on the two platform have different behaviour should not happen.
