### ISSUE TITLE
if cfg! error on Windows

### ISSUE THREAD

**Issue by RobBlob** [rust-lang/rust#38928]
The following fragment fails to compile, from the documentation I would expect it to.
```
#[cfg(target_family="unix")]
fn should_not_run() {
    println!("Really?");
}

fn main() {
    if cfg!(target_family="unix") {
        should_not_run();
    }
}
```
(standard distribution from Rust-lang)
rustc version 1.14.0
cargo 0.15.0-nightly
Windows 10.

**Comment by est31** [comment]
This is no bug. The `cfg!` macro expands to a runtime constant, while the `#[cfg` tag above makes the function being omitted at compile time. What happens after the "cfg-phase" is that you get code like this:

```rust
fn main() {
    if false {
        should_not_run();
    }
}
```

This will obviously fail.

**Comment by RobBlob** [comment]
Thanks, maybe a doc but then, as its described as conditional compilation in Rust by Example.

Lenovo TAB 2 A8-50

On 8 Jan 2017 6:21 pm, est31 <notifications@github.com> wrote:

This is no bug. The cfg! macro expands to a runtime constant, while the #[cfg tag above makes the function being omitted at compile time. What happens after the "cfg-phase" is that you get code like this:

fn main() {
    if false {
        should_not_run();
    }
}

This will obviously fail.

-

**Comment by est31** [comment]
@RobBlob I've filed an issue: https://github.com/rust-lang/rust-by-example/issues/831
