### ISSUE TITLE
Doesn't work with Visual Studio 2017

### ISSUE THREAD

**Issue by CorruptComputer** [rust-lang/rust#38931]
I have VS 2017RC installed, and running 'cargo build' gives an error, saying I need to install Visual Studio.

**Comment by est31** [comment]
Dupe of #38584

**Comment by retep998** [comment]
Rust works fine with Visual Studio 2017, it just doesn't automatically detect it yet. Use a vcvars bat file, or the VS developer command prompt, to get the environment setup with the right environment variables so Rust can invoke the linker correctly.

Closing as dupe.
