### ISSUE TITLE
error printed twice for deref recursion limit exceeded

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#38940]
I wrote some [code](https://play.rust-lang.org/?gist=1a7491f2abf052085e8b2a67e01895d6) for a rustc test which intentionally hits the recursion limit while trying to autoderef from `&Top` to `&Bottom`.

In nightly the [error when autoderef hits the recursion limit](https://github.com/rust-lang/rust/blob/aee21e2594c0dfe07f074be0da95c95b5b65ed50/src/librustc_typeck/check/autoderef.rs#L57) is printed twice. The second time it is printed without a real span.

Stable and beta:

```
rustc 1.14.0 (e8a012324 2016-12-16)
error[E0055]: reached the recursion limit while auto-dereferencing I
  --> <anon>:60:22
   |
60 |     let x: &Bottom = &t;
   |                      ^^ deref recursion limit reached

error[E0308]: mismatched types
  --> <anon>:60:22
   |
60 |     let x: &Bottom = &t;
   |                      ^^ expected struct `Bottom`, found struct `Top`
   |
   = note: expected type `&Bottom`
   = note:    found type `&Top`

error: aborting due to 2 previous errors
```

Nightly:

```
error[E0055]: reached the recursion limit while auto-dereferencing I
  --> xx.rs:60:22
   |
60 |     let x: &Bottom = &t;
   |                      ^^ deref recursion limit reached

error[E0055]: reached the recursion limit while auto-dereferencing I

error[E0308]: mismatched types
  --> xx.rs:60:22
   |
60 |     let x: &Bottom = &t;
   |                      ^^ expected struct `Bottom`, found struct `Top`
   |
   = note: expected type `&Bottom`
   = note:    found type `&Top`

error: aborting due to 3 previous errors
```

It's clearer to see with `--error-format=json` that the second error has a dummy span attached: https://gist.github.com/durka/04031f5701b5740f0f413267fc913e87

cc @jseyfried @jonathandturner

**Comment by Mark-Simulacrum** [comment]
@jseyfried You assigned this to yourself, but I don't see any progress yet. Just checking in to make sure you're still aware of it :)

**Comment by estebank** [comment]
No longer repros. Let's add a test and close.
