### ISSUE TITLE
provide an easy way to change the path of existing cargo for bootstrapping

### ISSUE THREAD

**Issue by exi** [rust-lang/rust#38950]
The current bootstrap/bootstrap.py and bootstrap/config.rs make the assumption that cargo is installed next to rustc in the rust root. That is not universally the case.

I'm packaging rust for nixos and for rust nightly need to apply some ugly string replace hacks in python and rust code to make it take a different path to cargo because we package rustc and cargo separately and because of how nixos works, this puts them in entirely separated directory trees.

**Comment by exi** [comment]
As an addition: If we could set the cargo path for bootstrapping via environment variables, it would make the packaging so much easier.

**Comment by Mark-Simulacrum** [comment]
You can set the cargo path in config.toml via `cargo = ` (search for it), which you can copy from src/bootstrap/config.toml.example.
