### ISSUE TITLE
Provide "peek" APIs to `std::net` sockets

### ISSUE THREAD

**Issue by APTy** [rust-lang/rust#38980]
# Summary
Provide "peek" APIs to `std::net` sockets, for example:
- `UdpSocket.peek()`
- `UdpSocket.peek_from()`
- `TcpStream.peek()`

These methods enable socket reads without side-effects. That is, repeated calls to `peek()` return identical data. This can be accomplished by providing the POSIX flag `MSG_PEEK` to the underlying socket read operations.

# Motivation
This is valuable in cases where a user wishes to validate *if* new data exists in the socket, without consuming that data completely. For example, a user may wish to use `peek()` as a method of polling the socket to find out if new messages are available (or to determine the amount of data available), before deferring to another function to do the actual work of reading and parsing the socket's data.

**Comment by cseale** [comment]
This _sounds_ like a good candidate for a first PR, would you think? If so I would like to take this on, with maybe a bit of help?

**Comment by APTy** [comment]
Thanks for offering! I am planning to submit a PR for a part 1 (UdpSocket implementation), and needed an issue to reference for the feature flag. Feel free to tackle TcpStream in parallel :)

**Comment by cseale** [comment]
Cool, I give that a go!

**Comment by cseale** [comment]
Looking at your branch, it might be an aggressive commit for me for my first contribution, unless perhaps you could provide me with a bit of detail on your intended implementation or somewhere maybe I could go for reference?

**Comment by APTy** [comment]
That's okay, I went ahead and added the TcpStream implementation, since it was pretty closely related to the Socket updates I was making. Thanks anyway!

**Comment by alexcrichton** [comment]
Reopening as the tracking issue for this feature

**Comment by sfackler** [comment]
@rfcbot fcp merge

This is a pretty straightforward binding to the underlying system APIs.
