### ISSUE TITLE
Add `flush` method to I/O input types

### ISSUE THREAD

**Issue by 3442853561** [rust-lang/rust#38991]
There should be flush () for input
Just like the getch() function in C language

**Comment by oli-obk** [comment]
Do you mean that `StdIn` should flush `StdOut` before reading? Please elaborate with examples of what you expect to happen.

You can find details on how to do it manually [on stackoverflow](http://stackoverflow.com/questions/34993744/why-does-this-read-input-before-printing)

**Comment by 3442853561** [comment]
@oli-obk I hope to be able to read the input before the enter
like `getch()` in C language

**Comment by oli-obk** [comment]
There's several crates that allow you to do this: http://stackoverflow.com/questions/26321592/how-can-i-read-one-character-from-stdin-without-having-to-hit-enter/27335584#27335584

If you think they belong into the standard library, I suggest you create an [RFC](https://github.com/rust-lang/rfcs/) to move some functionality from a crate to libstd.

**Comment by 3442853561** [comment]
https://github.com/rust-lang/rfcs/issues/1885

**Comment by sfackler** [comment]
Closing in favor of the rfcs issue.
