### ISSUE TITLE
Surprising type inference failure

### ISSUE THREAD

**Issue by mglagla** [rust-lang/rust#38999]
Using the rand crate, type inference failed on this piece of code:

```
extern crate rand;

use rand::{Rng, thread_rng};

fn main() {
    let mut rng = thread_rng();
    let y: usize = rng.gen() % 5usize;
}
```

Error:
```
error[E0282]: unable to infer enough type information about `_`
  --> src/main.rs:13:24
   |
13 |     let y: usize = rng.gen() % 5usize;
   |                        ^^^ cannot infer type for `_`
   |
   = note: type annotations or generic parameter binding required

```

The surprising thing is if I remove the `% 5usize`, the code compiles fine.

**Comment by quadrupleslap** [comment]
This isn't surprising, it's expected behaviour. What if I defined my own type that implemented `std::ops::Rem<RHS = usize> + rand::Rand`? That type would also work in this situation.

**Comment by mglagla** [comment]
@quadrupleslap 
Oh yeah, I see now. Thanks!
