### ISSUE TITLE
process: doc papercut

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#39012]
I was trying to run 

    git -C /path/to/repo log

today. `std::process::Command`, however, was quoting it as 

    git "-C /path/to/repo" log

which doesn't work. I was able to solve this specific issue with `home_dir`, but more generally, seems bad, and something we should document. I'm not sure what the workaround is in the general case.

**Comment by durka** [comment]
Can you clarify this? How did you invoke `Command::new(...).arg(...)`?

**Comment by nagisa** [comment]
> however, was quoting it as

> It just passes the arguments as you give them AFAIK so I don't see how this erroneous quoting could happen

The thing @steveklabnik is complaining is not “quoting” per se, but lack of argument splitting/parsing, which makes complete sense and is usually how’d you assume it works (i.e. `Command::arg` is not a shell). Think of `Command::new(...).arg("-C").arg("/path/to/repo but has spaces in it/woaw")`. You wouldn’t want it to pass that path as multiple arguments.

**Comment by steveklabnik** [comment]
Yes, basically, what I was doing was

    .arg("-C /path/to/repo")

but what I should have been doing was

    .arg("-C")
    .arg("/path/to/repo")

or use `args` instead. I was doing the former because the builder kinda implies it to me, "do this for each argument." And this stuff is hard to debug, so I think explaining it a little more would be a good thing.

**Comment by durka** [comment]
Oh I see. I guess we can try to warn harder against this in the docs, just something like "don't expect `std::process` to handle quoting at all". The first example already shows `.arg("-c").arg("hello world")` so that's pretty explicit.

**Comment by jdhorwitz** [comment]
I will start working on this today.

**Comment by Mark-Simulacrum** [comment]
This is currently fixed: https://doc.rust-lang.org/nightly/std/process/struct.Command.html#method.arg, since we now provide an example of the case encountered in this issue.
