### ISSUE TITLE
Add -C codegen-units=num_cpus

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#39037]
For Servo I’d like to enable `-C codegen-units` by default in debug mode (https://github.com/servo/servo/pull/14995), but at the moment the best we can do is hard-code a number like 4. It’d be nicer to have that number adapt to whatever hardware is currently running the compilation.

Does this sound like something y’all would want to have? (Possibly with some other syntax.)

As to implementing it, I’ve found the relevant code in `src/librustc/session/config.rs` and a copy of the `num_cpus` crate in `src/vendor/num_cpus/`, but the latter seems to only be used from `src/bootstrap/lib.rs` so I don’t know if `src/librustc` can also use it. Although, with the Cargo-based build system, adding a `path` dependency might Just Work?

**Comment by nagisa** [comment]
Why not figure out number of optimal codegen units in your build system instead (also in cargo)?

**Comment by SimonSapin** [comment]
Yes, I considered filing a Cargo issue instead, but in case we want to make this the default (#38276) this logic would need to be in rustc.

Though, as discussed in https://github.com/servo/servo/pull/14995#issuecomment-272525504, the number of cores may not always be the best number of codegen units…

**Comment by nagisa** [comment]
Right, number of logic cores is not the best number of codegen units even if only one crate is being compiled at a time (hyperthreading is junk for this sort of work).

See also http://www.ncameron.org/blog/how-fast-can-i-build-rust/

**Comment by JordiPolo** [comment]
Ping @Mark-Simulacrum  @alexcrichton  Isn't this done already?
Not the adapting to hardware but it seems the number has been tuned to make it optimal.

**Comment by alexcrichton** [comment]
Agreed!
