### ISSUE TITLE
Spurious failure when starting docker on Travis

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#39035]
I've seen this error a number of times when docker is starting on Travis:

```
The command "if [ "$ALLOW_PR" = "" ] && [ "$TRAVIS_BRANCH" != "auto" ]; then
    echo skipping, not a full build;
elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
    travis_retry git submodule update --init &&
    src/ci/run.sh;
else
    travis_retry git submodule update --init &&
    src/ci/docker/run.sh $IMAGE;
fi
" exited with 129.
```

notably the "exited with 129"

This looks similar to https://github.com/docker/docker/issues/18948, but I haven't been able to figure out a fix for this...

Example logs:

* https://travis-ci.org/rust-lang/rust/jobs/191636571
* https://travis-ci.org/rust-lang/rust/jobs/189481553

**Comment by aidanhs** [comment]
https://github.com/docker/compose/issues/3379#issuecomment-247222298

Worth trying to remove --tty? Not sure what requires it in the rust build. It's a little odd because all these users are talking about docker exec, so might also be worth adding `set -x`.

**Comment by alexcrichton** [comment]
Interesting! My *guess* (don't know for sure) is that this is what's failing -- https://github.com/rust-lang/rust/blob/b0c52c587fe9ba287053359fff5ed886b7edb27c/src/ci/docker/run.sh#L41-L54

We could try removing `--tty`, yeah, as it's basically just there to give us pretty colors. It's not worth spurious failures though if that's the cause! @aidanhs want to send a PR removing that?

**Comment by alexcrichton** [comment]
Attempted PR to fix this is at https://github.com/rust-lang/rust/pull/39036, let's wait awhile and see if this error still pops up after that merges.

**Comment by aidanhs** [comment]
@alexcrichton seen it recently?

**Comment by alexcrichton** [comment]
Nope!

**Comment by alexcrichton** [comment]
Thanks!
