### ISSUE TITLE
Retry-on-failure for submodule doesn't seem to work

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#39051]
I've seen a failure like https://travis-ci.org/rust-lang/rust/jobs/191773475 twice now where it looks like:

1. The initial submodule clone fails due to a standard error we've been seeing a lot spuriously on Travis.
2. The submodule clone was auto-retried due to us wrapping it in `travis_retry`
3. Later on the build fails because the rust-installer submodule wasn't actually checked out

I have no idea why `git submodule update --init` doesn't seem to be updating the rust-installer submodule. It even seems to [be cloning it](https://travis-ci.org/rust-lang/rust/jobs/191773475#L115), just not checking it out.

Presumably all other submodules succeeded to get cloned because the whole build succeeded otherwise...

**Comment by brson** [comment]
Should effectively be fixed by https://github.com/rust-lang/rust/pull/39055 but maybe we should wait for a while before closing.

**Comment by alexcrichton** [comment]
Oh right I actually saw this happen (saw the retry and then saw this logic kick in). The rust-installer build then finished successfully later. As a result I'm going to close this as I think it's taken care of (thanks @aidanhs!) and we can always reopen if it turns out to still be there.
