### ISSUE TITLE
doc-tests don't work with macros 1.1

### ISSUE THREAD

**Issue by colin-kiegel** [rust-lang/rust#39064]
It looks like having `proc-macro = true` in `Cargo.toml` disables all doc-tests. However unit tests `#[test]` work fine.

# Steps to reproduce

1. `cargo new foo`

2. `edit Cargo.toml`
```toml
# ... the usual
[lib]
proc-macro = true
```

3. `edit src/lib.rs`
```rust
//! ```rust
//! fn main() { panic!() } /* <-- this test should fail */
//! ```

#![crate_type = "proc-macro"]
extern crate proc_macro;

#[proc_macro_derive(Foo)]
pub fn derive(_: proc_macro::TokenStream) -> proc_macro::TokenStream {
    unimplemented!()
}
```

4. `cargo test`
```
running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured
```

**Comment by colin-kiegel** [comment]
just linking related tickets to attract some more attention :-)

- Tracking issue for "Macros 1.1" (RFC 1681) #35900
- Allow --test to be used on proc-macro crates #38107
- 'cargo test' with proc_macro_derive fails #37480

**Comment by sanmai-NL** [comment]
@colin-kiegel: I think this should be filed at `rust-lang/cargo`, no?

**Comment by colin-kiegel** [comment]
ok, I filed it there too: https://github.com/rust-lang/cargo/issues/3545

I'm not sure if this ticket belongs here or with cargo, so I'll leave it to someone else to close one of these tickets.

**Comment by keeperofdakeys** [comment]
I'll take a look at this, it's most likely a rust bug. There is probably a codepath that isn't visited because it's a proc macro crate.

**Comment by keeperofdakeys** [comment]
From what I can see, this is both a rust bug and a cargo bug. On a proc macro crate, cargo doesn't call `rustdoc --test`, and `rustdoc --test` doesn't actually work on proc macro crates. Both should be simple to fix though.
