### ISSUE TITLE
error E0382 use of moved value could be improved

### ISSUE THREAD

**Issue by binarycrusader** [rust-lang/rust#39070]
I was writing unit tests today and spent a while looking at this error:

```
error[E0382]: use of moved value: `a`
   --> /builds/srwalker/rsdev/pkg7rust/tests/action.rs:201:16
    |
199 |     let ma = a.must_accept();
    |              - value moved here
200 |     assert_eq!(ma, false);
201 |     assert_eq!(a.must_display(), false);
    |                ^ value used here after move
    |
    = note: move occurs because `a` has type `pkg7::actions::license::LicenseAction<'_>`, which does not implement the `Copy` trait
```
This message, while probably technically correct, attempts to help in a way that requires a significant amount of reasoning, especially for those relatively new to rust .  That is, the real reason a move occurred here is because I declared `must_accept` like this:

```
pub fn must_accept(self) -> bool
```
...instead of this:

```
pub fn must_accept(&self) -> bool
```

...causing self to be consumed. For those relatively new to rust, it's easy to forget, and while the error was attempting to tell me this, plainer messaging might have saved me some time.

Perhaps the message should include something like this before the note about the copy trait?

```= note: move occurs because must_accept takes ownership of `a` instead of a reference```

**Comment by Mark-Simulacrum** [comment]
`must_accept` taking &self wouldn't help with this problem specifically though (it would cause a type error); you are passing `a` by-value, so it will be moved. As such, I'm going to close, since I don't think we should change it in this way.
