### ISSUE TITLE
Failure to upload to S3 from AppVeyor

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#39074]
Seen twice now with the failure message:

```
A WebException with status ReceiveFailure was thrown.
```

Logs:

* https://ci.appveyor.com/project/rust-lang/rust/build/1.0.1552/job/4xk7i4iwxanot5ot
* https://ci.appveyor.com/project/rust-lang/rust/build/1.0.1525/job/ps7k6254mi5f8v33
* https://ci.appveyor.com/project/rust-lang/rust/build/1.0.1649/job/0vj4vqd2u2xtk5ny

I'll probably email them about retries and such come next week, wanted to start collecting logs in the meantime.

**Comment by brson** [comment]
sigh

**Comment by alexcrichton** [comment]
We've got enough examples now I've [opened a thread with AppVeyor](http://help.appveyor.com/discussions/problems/6239-spurious-failures-uploading-to-s3) about this.

**Comment by alexcrichton** [comment]
An [upstream issue](https://github.com/appveyor/ci/issues/1387) has been created for this.
