### ISSUE TITLE
[config.toml] should not assume `ar` uses the same prefix as `cc` for target

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#39093]
If you specify `cc = "prefix-cc"`, then it will explicitly require `"prefix-ar"` to also exist, without any way to override it. Should either be overridable, or not assumed.

**Comment by metux** [comment]
In general, compiler(-frontends) should honor the $AR environment variable, and do not attempt any guessing whatsoever, when it's set (note: this is the command line, not the binary name) - distro packaging systems *need* that.

**Comment by bjorn3** [comment]
The ar path has been separately overridable since https://github.com/rust-lang/rust/pull/45191: https://github.com/rust-lang/rust/blob/10b3a0d209746e70fdc72f65e4649d492f6ed5a2/config.toml.example#L657
