### ISSUE TITLE
Wrong example in the book for Borrow<_>

### ISSUE THREAD

**Issue by gralpli** [rust-lang/rust#39103]
Chapter _5.10. Borrow and AsRef_ contains the following example:

```rust
use std::borrow::Borrow;
use std::fmt::Display;

fn foo<T: Borrow<i32> + Display>(a: T) {
    println!("a is borrowed: {}", a);
}

let mut i = 5;

foo(&i);
foo(&mut i);
```

I think this example is wrong, because the fact that ```a``` is ```Borrow<i32>``` is not used here. It also gives the impression that ```a``` needs to _be_ something borrowed, although it just needs to be something you can _borrow from_.

I would suggest the following as a better example:

```rust
use std::borrow::Borrow;

fn foo<T: Borrow<i32>>(a: T) {
    let b: &i32 = a.borrow();
    println!("{}", b);
}

let mut four = 4;

foo(four);
foo(&four);
foo(&mut four);
```

**Comment by steveklabnik** [comment]
I am not making changes to the book, as I'm working on the second edition https://github.com/rust-lang/book

If you'd like to see this change, please send in a PR. I'd happily accept one! But since we're not tracking small issues in the book like this anymore, I'm going to give it a close. Thanks!
