### ISSUE TITLE
Compiler bug on travis

### ISSUE THREAD

**Issue by hackereg35** [rust-lang/rust#39101]
Hi my kernel build on my machine with rust 1.15-nightly, 
but when building on travis i get this error 
`
$ export DEBIAN_FRONTEND=noninteractive

W: Size of file /var/lib/apt/lists/security.ubuntu.com_ubuntu_dists_precise-security_restricted_binary-amd64_Packages.gz is not what the server reported 13782 14904

W: Size of file /var/lib/apt/lists/security.ubuntu.com_ubuntu_dists_precise-security_restricted_binary-i386_Packages.gz is not what the server reported 13751 14885

W: Size of file /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_precise-updates_restricted_binary-amd64_Packages.gz is not what the server reported 19576 20785

W: Size of file /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_precise-updates_restricted_binary-i386_Packages.gz is not what the server reported 19521 20707

W: Size of file /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_precise-backports_multiverse_source_Sources.gz is not what the server reported 5886 5888

W: Size of file /var/lib/apt/lists/ppa.launchpad.net_travis-ci_zero-mq_ubuntu_dists_precise_main_binary-amd64_Packages.gz is not what the server reported 832 1195

W: Size of file /var/lib/apt/lists/ppa.launchpad.net_ubuntugis_ppa_ubuntu_dists_precise_main_binary-amd64_Packages.gz is not what the server reported 33653 36677

W: Size of file /var/lib/apt/lists/ppa.launchpad.net_ubuntugis_ppa_ubuntu_dists_precise_main_binary-i386_Packages.gz is not what the server reported 33699 36733

Reading package lists...

Building dependency tree...

Reading state information...

The following extra packages will be installed:

  libc-bin libc-dev-bin libc6-dev

Suggested packages:

  glibc-doc

The following packages will be upgraded:

  libc-bin libc-dev-bin libc6 libc6-dev

4 upgraded, 0 newly installed, 0 to remove and 266 not upgraded.

Need to get 8,840 kB of archives.

After this operation, 14.3 kB disk space will be freed.

Get:1 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libc6-dev amd64 2.15-0ubuntu10.15 [2,943 kB]

Get:2 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libc-dev-bin amd64 2.15-0ubuntu10.15 [84.7 kB]

Get:3 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libc-bin amd64 2.15-0ubuntu10.15 [1,177 kB]

Get:4 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libc6 amd64 2.15-0ubuntu10.15 [4,636 kB]

Fetched 8,840 kB in 0s (10.9 MB/s)

Preconfiguring packages ...

(Reading database ... 71420 files and directories currently installed.)

Preparing to replace libc6-dev 2.15-0ubuntu10.10 (using .../libc6-dev_2.15-0ubuntu10.15_amd64.deb) ...

Unpacking replacement libc6-dev ...

Preparing to replace libc-dev-bin 2.15-0ubuntu10.10 (using .../libc-dev-bin_2.15-0ubuntu10.15_amd64.deb) ...

Unpacking replacement libc-dev-bin ...

Preparing to replace libc-bin 2.15-0ubuntu10.10 (using .../libc-bin_2.15-0ubuntu10.15_amd64.deb) ...

Unpacking replacement libc-bin ...

Processing triggers for man-db ...

Setting up libc-bin (2.15-0ubuntu10.15) ...

(Reading database ... 71419 files and directories currently installed.)

Preparing to replace libc6 2.15-0ubuntu10.10 (using .../libc6_2.15-0ubuntu10.15_amd64.deb) ...

Unpacking replacement libc6 ...

Setting up libc6 (2.15-0ubuntu10.15) ...

Setting up libc-dev-bin (2.15-0ubuntu10.15) ...

Setting up libc6-dev (2.15-0ubuntu10.15) ...

Processing triggers for libc-bin ...

ldconfig deferred processing now taking place

$ git clone --depth=50 --branch=master https://github.com/hackereg35/rust-kernel.git hackereg35/rust-kernel

Cloning into 'hackereg35/rust-kernel'...

remote: Counting objects: 37, done.

remote: Compressing objects: 100% (26/26), done.

remote: Total 37 (delta 3), reused 34 (delta 3), pack-reused 0

Unpacking objects: 100% (37/37), done.

Checking connectivity... done.

$ cd hackereg35/rust-kernel

$ git checkout -qf 972c7970098c7cda6615b8ec80349efe01e3cfb6

This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.

If you require sudo, add 'sudo: required' to your .travis.yml

See https://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.

0.01s

rust-download

Installing Rust

0.12s$ curl -sL https://static.rust-lang.org/rustup.sh -o ~/rust-installer/rustup.sh

9.42s$ sh ~/rust-installer/rustup.sh --prefix=~/rust --spec=nightly -y --disable-sudo 2> /dev/null

rustup: gpg available. signatures will be verified

rustup: downloading manifest for 'nightly'

rustup: downloading toolchain for 'nightly'

gpg: Signature made Mon 16 Jan 2017 12:20:14 PM UTC using RSA key ID 7B3B09DC

gpg: Good signature from "Rust Language (Tag and Release Signing Key) <rust-key@rust-lang.org>"

gpg: WARNING: This key is not certified with a trusted signature!

gpg:          There is no indication that the signature belongs to the owner.

Primary key fingerprint: 108F 6620 5EAE B0AA A8DD  5E1C 85AB 96E6 FA1B E5FE

     Subkey fingerprint: C134 66B7 E169 A085 1886  3216 5CB4 A934 7B3B 09DC

rustup: installing toolchain for 'nightly'

rustup: extracting installer

install: creating uninstall script at /home/travis/rust/lib/rustlib/uninstall.sh

install: installing component 'rustc'

install: installing component 'rust-std-x86_64-unknown-linux-gnu'

install: installing component 'rust-docs'

install: installing component 'cargo'

    Rust is ready to roll.

0.01s

0.01s

0.01s

$ rustc --version

rustc 1.16.0-nightly (ff591b6dc 2017-01-15)

$ cargo --version

cargo 0.17.0-nightly (6c79cf9 2017-01-13)

13.35s$ cargo build --verbose

    Updating registry `https://github.com/rust-lang/crates.io-index`

 Downloading multiboot2 v0.1.0

 Downloading spin v0.4.5

 Downloading rlibc v0.1.5

 Downloading bitflags v0.4.0

 Downloading x86 v0.8.0

 Downloading volatile v0.1.0

 Downloading bitflags v0.7.0

 Downloading raw-cpuid v2.0.1

   Compiling x86 v0.8.0

   Compiling volatile v0.1.0

   Compiling bitflags v0.4.0

   Compiling raw-cpuid v2.0.1

   Compiling bitflags v0.7.0

   Compiling rlibc v0.1.5

   Compiling spin v0.4.5

     Running `rustc --crate-name build_script_build /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/x86-0.8.0/build.rs --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=75b9bc2ec16f1f6e -C extra-filename=-75b9bc2ec16f1f6e --out-dir /home/travis/build/hackereg35/rust-kernel/target/debug/build/x86-75b9bc2ec16f1f6e -L dependency=/home/travis/build/hackereg35/rust-kernel/target/debug/deps --cap-lints allow`

     Running `rustc --crate-name bitflags /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-0.4.0/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg 'feature="no_std"' -C metadata=2565e485d19febcf -C extra-filename=-2565e485d19febcf --out-dir /home/travis/build/hackereg35/rust-kernel/target/debug/deps -L dependency=/home/travis/build/hackereg35/rust-kernel/target/debug/deps --cap-lints allow`

     Running `rustc --crate-name volatile /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/volatile-0.1.0/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=3253c439383d95ab -C extra-filename=-3253c439383d95ab --out-dir /home/travis/build/hackereg35/rust-kernel/target/debug/deps -L dependency=/home/travis/build/hackereg35/rust-kernel/target/debug/deps --cap-lints allow`

     Running `rustc --crate-name raw_cpuid /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/raw-cpuid-2.0.1/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=723bbf57db918f42 -C extra-filename=-723bbf57db918f42 --out-dir /home/travis/build/hackereg35/rust-kernel/target/debug/deps -L dependency=/home/travis/build/hackereg35/rust-kernel/target/debug/deps --cap-lints allow`

     Running `rustc --crate-name bitflags /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-0.7.0/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=65ddff5d2b91509e -C extra-filename=-65ddff5d2b91509e --out-dir /home/travis/build/hackereg35/rust-kernel/target/debug/deps -L dependency=/home/travis/build/hackereg35/rust-kernel/target/debug/deps --cap-lints allow`

     Running `rustc --crate-name rlibc /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/rlibc-0.1.5/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=a32503b79af87730 -C extra-filename=-a32503b79af87730 --out-dir /home/travis/build/hackereg35/rust-kernel/target/debug/deps -L dependency=/home/travis/build/hackereg35/rust-kernel/target/debug/deps --cap-lints allow`

     Running `rustc --crate-name spin /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.4.5/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg 'feature="const_fn"' --cfg 'feature="once"' --cfg 'feature="default"' --cfg 'feature="asm"' --cfg 'feature="core_intrinsics"' --cfg 'feature="unstable"' -C metadata=48d0aca32942f1c4 -C extra-filename=-48d0aca32942f1c4 --out-dir /home/travis/build/hackereg35/rust-kernel/target/debug/deps -L dependency=/home/travis/build/hackereg35/rust-kernel/target/debug/deps --cap-lints allow`

   Compiling multiboot2 v0.1.0

     Running `rustc --crate-name multiboot2 /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/multiboot2-0.1.0/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=3e509ba7f3ebff44 -C extra-filename=-3e509ba7f3ebff44 --out-dir /home/travis/build/hackereg35/rust-kernel/target/debug/deps -L dependency=/home/travis/build/hackereg35/rust-kernel/target/debug/deps --extern bitflags=/home/travis/build/hackereg35/rust-kernel/target/debug/deps/libbitflags-2565e485d19febcf.rlib --cap-lints allow`

     Running `/home/travis/build/hackereg35/rust-kernel/target/debug/build/x86-75b9bc2ec16f1f6e/build-script-build`

     Running `rustc --crate-name x86 /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/x86-0.8.0/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=992be198737ab929 -C extra-filename=-992be198737ab929 --out-dir /home/travis/build/hackereg35/rust-kernel/target/debug/deps -L dependency=/home/travis/build/hackereg35/rust-kernel/target/debug/deps --extern bitflags=/home/travis/build/hackereg35/rust-kernel/target/debug/deps/libbitflags-65ddff5d2b91509e.rlib --extern raw_cpuid=/home/travis/build/hackereg35/rust-kernel/target/debug/deps/libraw_cpuid-723bbf57db918f42.rlib --cap-lints allow`

error: internal compiler error: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_trans/mir/operand.rs:83: not immediate: OperandRef(Ref((%"shared::segmentation::SegmentSelector"*:  %_4 = alloca %"shared::segmentation::SegmentSelector")) @ shared::segmentation::SegmentSelector)

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_errors/lib.rs:423

note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `x86`.

Caused by:

  process didn't exit successfully: `rustc --crate-name x86 /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/x86-0.8.0/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=992be198737ab929 -C extra-filename=-992be198737ab929 --out-dir /home/travis/build/hackereg35/rust-kernel/target/debug/deps -L dependency=/home/travis/build/hackereg35/rust-kernel/target/debug/deps --extern bitflags=/home/travis/build/hackereg35/rust-kernel/target/debug/deps/libbitflags-65ddff5d2b91509e.rlib --extern raw_cpuid=/home/travis/build/hackereg35/rust-kernel/target/debug/deps/libraw_cpuid-723bbf57db918f42.rlib --cap-lints allow` (exit code: 101)

2.37s$ cargo test --verbose

       Fresh spin v0.4.5

       Fresh bitflags v0.4.0

       Fresh rlibc v0.1.5

       Fresh bitflags v0.7.0

       Fresh volatile v0.1.0

       Fresh raw-cpuid v2.0.1

       Fresh multiboot2 v0.1.0

   Compiling x86 v0.8.0

     Running `rustc --crate-name x86 /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/x86-0.8.0/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=992be198737ab929 -C extra-filename=-992be198737ab929 --out-dir /home/travis/build/hackereg35/rust-kernel/target/debug/deps -L dependency=/home/travis/build/hackereg35/rust-kernel/target/debug/deps --extern raw_cpuid=/home/travis/build/hackereg35/rust-kernel/target/debug/deps/libraw_cpuid-723bbf57db918f42.rlib --extern bitflags=/home/travis/build/hackereg35/rust-kernel/target/debug/deps/libbitflags-65ddff5d2b91509e.rlib --cap-lints allow`

error: internal compiler error: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_trans/mir/operand.rs:83: not immediate: OperandRef(Ref((%"shared::segmentation::SegmentSelector"*:  %_4 = alloca %"shared::segmentation::SegmentSelector")) @ shared::segmentation::SegmentSelector)

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_errors/lib.rs:423

note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `x86`.

Caused by:

  process didn't exit successfully: `rustc --crate-name x86 /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/x86-0.8.0/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=992be198737ab929 -C extra-filename=-992be198737ab929 --out-dir /home/travis/build/hackereg35/rust-kernel/target/debug/deps -L dependency=/home/travis/build/hackereg35/rust-kernel/target/debug/deps --extern raw_cpuid=/home/travis/build/hackereg35/rust-kernel/target/debug/deps/libraw_cpuid-723bbf57db918f42.rlib --extern bitflags=/home/travis/build/hackereg35/rust-kernel/target/debug/deps/libbitflags-65ddff5d2b91509e.rlib --cap-lints allow` (exit code: 101)

The command "cargo test --verbose" exited with 101.

Done. Your build exited with 1.
`

[Travis build](https://travis-ci.org/hackereg35/rust-kernel/builds/192436528)

**Comment by est31** [comment]
Dupe of #39083
