### ISSUE TITLE
Irrefutable let statements in match branches

### ISSUE THREAD

**Issue by clarfonthey** [rust-lang/rust#39104]
I found this when I was writing code for [tera](https://github.com/Keats/tera/blob/869bbce6bbbe7b572ca3294ab4bdbb18df148705/src/template.rs#L47) that was designed to remove an unnecessary `clone`.

Code reproduced below:
```rust
match node {
    block @ Node::Block { .. } => {
        let string;
        let children;

        if let Node::Block { ref name, ref body } = block {
            if blocks.contains_key(name) {
                bail!("Block `{}` is duplicated", name);
            }
            string = name.to_string();
            children = body.get_children();
        } else {
            unreachable!();
        };

        blocks.insert(string, block);
        find_blocks(children, blocks)?;
    },
    // ...
}
```

Inside the match branch, an `if let` statement with an unreachable else branch is required, whereas a simple `let` binding should do.

**Comment by nagisa** [comment]
Is a hard problem to solve. Why not do this in the meantime:

```
match node {
    Node::Block { name, body } => {
        if blocks.contains_key(&name) {
            bail!("Block `{}` is duplicated", name);
        }
        let string = name.to_string();
        let children = body.get_children();

        blocks.insert(string, Node::Block { name, body });
        find_blocks(children, blocks)?;
    },
    // ...
}
```

**Comment by steveklabnik** [comment]
Triage: any chance we could get a self-contained reproduction here?

**Comment by clarfon** [comment]
@steveklabnik quick one from playground https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ddbcff7463b50dfc14abc9dffe86a15b

**Comment by clarfonthey** [comment]
This is a super old issue and I'm just going to close it as something that will either be solved by pattern types, or not at all.
