### ISSUE TITLE
privacy checker lets me smuggle a private type in a public interface through reexports

### ISSUE THREAD

**Issue by whitequark** [rust-lang/rust#39113]
Consider this code:
```rust
mod socket {
    mod set {
        /*pub*/ struct Item;
        pub struct Set {
            stuff: Vec<Item>
        }
        impl Set {
            pub fn new(stuff: Vec<Item>) -> Set {
                Set { stuff: stuff }
            }
        }
    }
    pub use self::set::Set;
}

fn main() {
    socket::Set::new(vec![]);
}
```

With the `pub` commented, rustc rejects it with <code>error[E0446]: private type `socket::set::Item` in public interface</code>. With the `pub` uncommented though rustc accepts it without as much as a warning. This is even quite usable in downstream code e.g. if the type implements Default.

Note that whether or not `pub` is present, the `socket::set::Item` type is not nameable.

**Comment by petrochenkov** [comment]
This works as expected, anything marked as `pub` is considered public by the private-in-public checker, returning unnameable types is allowed.
https://github.com/rust-lang/rfcs/blob/master/text/0136-no-privates-in-public.md#when-is-an-item-public

**Comment by whitequark** [comment]
This seems very weird but OK.

**Comment by ubsan** [comment]
@petrochenkov This seems broken. It's a public function taking a private type.

**Comment by whitequark** [comment]
Reopening at the request of @ubsan.

**Comment by petrochenkov** [comment]
@ubsan 
I can only repeat what I said in https://github.com/rust-lang/rust/issues/39113#issuecomment-273044681
This was discussed *many* times ([historical overview with links](https://github.com/jseyfried/rfcs/commit/a23a5c9fc51cabc478e6ae62da084446a1410533#commitcomment-16157895)).

**Comment by petrochenkov** [comment]
This also can't be "fixed" because a lot of code relies on
```
mod detail {
    pub struct UnnameableStruct;
    pub struct UnnameableTrait;
}

fn f<T: UnnameableTrait>() -> UnnameableStruct {}
```
pattern.

**Comment by ubsan** [comment]
@petrochenkov That's not equivalent. In the original case, you have a public function taking a private type (`Vec<Item>` - `Item` is private to that module, i.e. not-pub). You still haven't responded to the actual issue.

**Comment by ubsan** [comment]
@petrochenkov ah, I see. I misread the original post. Thanks! I am satisfied.
