### ISSUE TITLE
poor error message when colon is used instead of semicolon

### ISSUE THREAD

**Issue by tshepang** [rust-lang/rust#39126]
I get this error:

```
error: expected type, found keyword `let`
 --> src/main.rs:3:5
  |
3 |     let two_squared = two * two;
  |     ^^^
```

That's with this code:

```rust
fn main() {
    let two = 2:
    let two_squared = two * two;
}
```

**Comment by brson** [comment]
Is this because of the type ascription parser? I recall there was another issue about making the stable parser not parse unstable things.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/34255.
