### ISSUE TITLE
"does not live long enough" error only occurs with multiple fields that are references to a mutable struct

### ISSUE THREAD

**Issue by dstepanov** [rust-lang/rust#39123]
I have found some strange behavior of Rust compiler. In a case when `struct` has a few fields (at least two) that are references to a mutable `struct` with a lifetime, compiler produces `dropped here while still borrowed` error.

Error occurs only if there are at least two references to a mutable struct, removing `mut` or having only one ref makes code compile.

I would expect consistent behavior in both cases or at least some hint in the error message.

I'm new to Rust, it took me a while to fix it with multiple lifetimes, but I think it's a bug in compiler.

`rustc 1.14.0 (e8a012324 2016-12-16)`

Example with references to mutable `struct` that doesn't compile:

```rust
#[derive(Debug)]
struct A<'a> {
    name: &'a str
}

#[derive(Debug)]
struct B<'a> {
    a_ref1: &'a mut A<'a>,
    a_ref2: &'a mut A<'a>
}

fn main() {
    let mut a1 = A {
        name: "Denis"
    };
    let mut a2 = A {
        name: "Denis"
    };
    let b = B {
        a_ref1: &mut a1,
        a_ref2: &mut a2
    };
    println!("B: {:?}", b);
}
```
Error:
```
error: `a2` does not live long enough
  --> src/main.rs:24:1
   |
21 |         a_ref2: &mut a2
   |                      -- borrow occurs here
...
24 | }
   | ^ `a2` dropped here while still borrowed
   |
   = note: values in a scope are dropped in the opposite order they are created
```

Example with references to immutable `struct` that compiles without errors:

```rust
#[derive(Debug)]
struct A<'a> {
    name: &'a str
}

#[derive(Debug)]
struct B<'a> {
    a_ref1: &'a A<'a>,
    a_ref2: &'a A<'a>
}

fn main() {
    let a1 = A {
        name: "Denis"
    };
    let a2 = A {
        name: "Denis"
    };
    let b = B {
        a_ref1: &a1,
        a_ref2: &a2
    };
    println!("B: {:?}", b);
}
```

Example with only one mutable reference that compiles without problems:

```rust
#[derive(Debug)]
struct A<'a> {
    name: &'a str
}

#[derive(Debug)]
struct B<'a> {
    a_ref1: &'a mut A<'a>
}

fn main() {
    let mut a1 = A {
        name: "Denis"
    };
    let b = B {
        a_ref1: &mut a1
    };
    println!("B: {:?}", b);
}
```

**Comment by arielb1** [comment]
That's because of lifetime invariance.

This variant works well:
```Rust
#[derive(Debug)]
struct A<'a> {
    name: &'a str
}

#[derive(Debug)]
struct B<'a, 'b> {
    a_ref1: &'a mut A<'a>,
    a_ref2: &'b mut A<'b>
}

fn main() {
    let mut a1 = A {
        name: "Denis"
    };
    let mut a2 = A {
        name: "Denis"
    };
    let b = B {
        a_ref1: &mut a1,
        a_ref2: &mut a2
    };
    println!("B: {:?}", b);
}
```

**Comment by dstepanov** [comment]
Why does it work without immutable references?

**Comment by estebank** [comment]
Note: [Fixed by NLL](https://play.rust-lang.org/?gist=07ddc91c36f6c9ca47974dde01f319e2&version=nightly&mode=debug&edition=2015):

```
B: B { a_ref1: A { name: "Denis" }, a_ref2: A { name: "Denis" } }
```

**Comment by dstepanov** [comment]
Great, it was strange that there was a difference.

Issue can be closed now.
