### ISSUE TITLE
Borrow, AsRef, others suboptimal for enums / specific structs

### ISSUE THREAD

**Issue by sdroege** [rust-lang/rust#39125]
Consider something like the following two enums
````Rust
enum Foo {
  Bar(i32),
  Baz(String),
}

enum FooBorrowed<'a> {
  Bar(&'a i32),
  Baz(&'a str),
}
````

In theory one would like to be able to implement Deref, AsRef, Borrow, IntoOwned, etc for this pair of enums (or a similar pair of structs) and e.g. also use it in a Cow. However that's not possible as Deref, AsRef, Borrow explicitly return a reference from their functions. If it was instead a "normal" type, one could implement it for the above pair and still cover the existing implementations that return references.

Is there any chance to extend this by new traits, or is there another solution?

**Comment by Mark-Simulacrum** [comment]
We can't change these traits in any way today, so I'm going to close this. I'm not entirely sure what the problem here is either.

**Comment by ratijas** [comment]
The problem still exists. I'm trapped in the same situation: having two enums, one for owned data, other for borrowed counterparts. And I can't seem to be able to benefit from the `AsRef` / `Borrow` infrastructure with those. Any ideas or workarounds?

This is my particular usecase:

```rust
/// Owned wrapper for counter value.
#[derive(Clone, Debug, Ord, PartialOrd, Eq, PartialEq)]
pub enum CounterValue {
    Dword(DWORD),
    Large(ULONGLONG),
    TextUnicode(U16CString),
    TextAscii(String),
    Zero,
}

/// Borrowed wrapper for counter value.
/// It is to the `CounterValue` as a str is to the String.
#[derive(Clone, Debug, Ord, PartialOrd, Eq, PartialEq)]
pub enum CounterVal<'a> {
    Dword(DWORD),
    Large(ULONGLONG),
    TextUnicode(&'a U16CStr),
    TextAscii(&'a str),
    Zero,
}
```
