### ISSUE TITLE
Rephrase docs for Vec::drain to better clarify Drop behavior

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/rust#39134]
(This is mostly for my own benefit as I've been separated from my Rust fork and associated development environment. If someone wants to pick this up, though, it's a wonderful first dive into documentation contributions! :3)

The "Note 1" on [Vec::drain](https://doc.rust-lang.org/collections/vec/struct.Vec.html#method.drain) could be rephrased to be more clear. Something like "Note 1: The element range is removed even if the iterator is only partially consumed or not consumed at all." Some discussion in rust-beginners revealed some confusion around the current "is not consumed until the end" phrasing.

**Comment by steveklabnik** [comment]
I'm happy to mentor anyone who needs help submitting a PR for this!

**Comment by TheCycoONE** [comment]
@steveklabnik That's appreciated!

**Comment by QuietMisdreavus** [comment]
Closed by #39135.
