### ISSUE TITLE
Explicit warning on nested unsafe blocks

### ISSUE THREAD

**Issue by Wilfred** [rust-lang/rust#39144]
When refactoring code, it's easy to accidentally end up with nested `unsafe` blocks. This can lead to confusing rustc errors.

```rust
unsafe fn very_dangerous() -> u64 {
    1
}

fn main() {
    unsafe {
        // lots of code...
        
        unsafe {
            very_dangerous();
        }
    }
```

The compiler says:

```
rustc 1.16.0-nightly (ff591b6dc 2017-01-15)
warning: unnecessary `unsafe` block, #[warn(unused_unsafe)] on by default
  --> <anon>:9:9
   |
9  |           unsafe {
   |  _________^ starting here...
10 | |             very_dangerous();
11 | |         }
   | |_________^ ...ending here
```

This is surprising at first glance, since `very_dangerous` requires an `unsafe` block but the message implies otherwise. Could we warn about nested `unsafe` blocks?

**Comment by brson** [comment]
A general improvement that would accomplish the same goal might be to have a 'note' pointing to the outer unsafe declaration. The text can be specialized to say e.g. "because of this unsafe block" or "unsafe function".

**Comment by brson** [comment]
Enrich this error with span information about the reason the unsafe block is unneeded. Should be relatively simple to follow existing examples where errors have 'notes' attached. The tricky bits will be making sure it looks good and reads well, and finding the span of the original unsafe block.

**Comment by estebank** [comment]
@brson, I have PR #39202 for this, and I arrived to these two possibilities:

<img width="621" alt="" src="https://cloud.githubusercontent.com/assets/1606434/22139922/26ad468a-de9e-11e6-8884-2945be882ea8.png">

<img width="647" alt="" src="https://cloud.githubusercontent.com/assets/1606434/22140011/b73c27ac-de9e-11e6-9352-8d294b4c309c.png">
