### ISSUE TITLE
Exclude "explanation" out of a warning or an error message in JSON

### ISSUE THREAD

**Issue by KalitaAlexey** [rust-lang/rust#39154]
Hi everybody.

Currently if `--message-format json` is specified the compiler emits warnings and errors with **"explanation"** field.

It is not used at majority of cases.
If someone wants to show it to a user, the person can execute `rustc --explain`.

**It is a breaking change** because someone can rely on the field.

### Motivation
An explanation may be big enough.
It slows everything (the compiler, tools using the output).

**Comment by Mark-Simulacrum** [comment]
I suspect that the actual cost of a single extra field, even if a couple kilobytes, doesn't really slow tooling down overly much. Ideally we might want to remove it but I'm not sure we should. @nrc @jonathandturner, this seems like it might potentially affect RLS, could you comment?

**Comment by jackh726** [comment]
I agree with Mark here, it's unlikely the extra field causes any performance problems, and as you said, it probably would break things. Going to close.
