### ISSUE TITLE
clarify how attributes interact with trait methods (in particular #[inline])

### ISSUE THREAD

**Issue by anderspapitto** [rust-lang/rust#39172]
the docs (https://doc.rust-lang.org/reference.html#inline-attributes) currently don't specify when it's appropriate to place an attribute next to the declaration of a method inside a `trait` block, versus next to a definition of that method inside an `impl` block.

**Comment by Mark-Simulacrum** [comment]
Closing, if interested please file an issue here: https://github.com/rust-lang-nursery/reference/issues.
