### ISSUE TITLE
confusing error message for an invalid &mut-to-&mut cast

### ISSUE THREAD

**Issue by whitequark** [rust-lang/rust#39178]
Consider this code:
```rust
use std::path::{Path, PathBuf};

fn main() {
    let mut a: PathBuf = PathBuf::new();
    let mut b: &mut PathBuf = &mut a;
    let mut c: &mut Path = b;
}
```
It fails to compile on `rustc 1.16.0-nightly (c07a6ae77 2017-01-17)` with:
```
rustc 1.16.0-nightly (c07a6ae77 2017-01-17)
error: cannot borrow immutable borrowed content as mutable
 --> <anon>:6:28
  |
6 |     let mut c: &mut Path = b;
  |                            ^

error: aborting due to previous error
```
I don't really see any immutable borrowed content here at all. Is it because of autoref/autoderef?

**Comment by seppo0010** [comment]
It seems like PathBuf's deref returns &Path and not &mut Path, an immutable reference

https://doc.rust-lang.org/nightly/src/std/path.rs.html#1253-1259

**Comment by Mark-Simulacrum** [comment]
There's no `DerefMut` impl for `PathBuf` (nor would it make sense, I think) so this is purely a diagnostics issue -- we should indicate what the immutable borrowed content is; or possibly give a type error here.

**Comment by Dylan-DPC** [comment]
Closing this as this code compiles now,
