### ISSUE TITLE
Configure C function exports correctly for emscripten targets

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#39171]
In order to call emscriptened functions from JS one must pass `-s EXPORTED_FUNCTIONS=[...]` to emcc, with each exported symbol. ISTM that it would be consistent for rustc to do this automatically for cdylib and staticlib targets.

cc @cryze @alexcrichton

**Comment by alexcrichton** [comment]
We've already got lists of symbols that we explicitly pass to the linker to export, so this shouldn't be too hard to implement as well!

**Comment by RReverser** [comment]
I'd like to try to implement this in a PR.

**Comment by RReverser** [comment]
Kinda implemented this locally but there are two issues/caveats:

1) Apparently JS is generated only for binary target, so to export functions you still need to compile with such target and have at least empty `main` function.

2) To achieve this, I've patched `export_symbols` function in linker which seems like a proper place; however, it seems like symbols are collected from all dependent crates too, so the list of exported functions looks like:

```bash
[
    "_foo",
    "_main",
    "___udivmodti4",
    "___fixsfti",
    "___fixunsdfti",
    "___floattisf",
    "___muloti4",
    "___modti3",
    "___divti3",
    "___umodti3",
    "___udivti3",
    "___fixdfti",
    "___floatuntisf",
    "___multi3",
    "___floattidf",
    "___fixunssfti",
    "___floatuntidf",
    "___lshrti3",
    "___ashrti3",
    "___ashlti3",
    "___rust_reallocate",
    "___rust_reallocate_inplace",
    "___rust_deallocate",
    "___rust_allocate",
    "___rust_usable_size",
    "___rust_start_panic",
    "_rust_eh_personality",
    "___rust_maybe_catch_panic"
]
```

As you can see, apart from own exported `_main` (required) and `_foo` (explicitly exported), tons of others are added, and some of them are incompatible with Emscripten which makes it complain:

```
          LLVM ERROR: Function __ashlti3 has illegal integer argument
          Traceback (most recent call last):
            File "/Users/rreverser/cf-repos/rust/emsdk_portable/emscripten/incoming/emcc", line 13, in <module>
              emcc.run()
            File "/Users/rreverser/cf-repos/rust/emsdk_portable/emscripten/incoming/emcc.py", line 1647, in run
              final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
            File "/Users/rreverser/cf-repos/rust/emsdk_portable/emscripten/incoming/tools/shared.py", line 1745, in emscripten
              call_emscripten(cmdline)
            File "/Users/rreverser/cf-repos/rust/emsdk_portable/emscripten/incoming/emscripten.py", line 1836, in _main
              temp_files.run_and_clean(lambda: main(
            File "/Users/rreverser/cf-repos/rust/emsdk_portable/emscripten/incoming/tools/tempfiles.py", line 78, in run_and_clean
              return func()
            File "/Users/rreverser/cf-repos/rust/emsdk_portable/emscripten/incoming/emscripten.py", line 1841, in <lambda>
              DEBUG=DEBUG,
            File "/Users/rreverser/cf-repos/rust/emsdk_portable/emscripten/incoming/emscripten.py", line 1742, in main
              temp_files=temp_files, DEBUG=DEBUG)
            File "/Users/rreverser/cf-repos/rust/emsdk_portable/emscripten/incoming/emscripten.py", line 91, in emscript
              funcs, metadata, mem_init = get_and_parse_backend(infile, settings, temp_files, DEBUG)
            File "/Users/rreverser/cf-repos/rust/emsdk_portable/emscripten/incoming/emscripten.py", line 160, in get_and_parse_backend
              backend_output = open(temp_js).read()
```

Should we somehow filter those or even allow only top-level exports?

**Comment by CryZe** [comment]
main isn't fully required, you can add #![no_main] to your crate-level
attributes, which lets you compile it.

2017-01-22 20:26 GMT+01:00 Ingvar Stepanyan <notifications@github.com>:

**Comment by RReverser** [comment]
@CryZe I guess; anyway, that wasn't my main point, just wanted to clarify "for rustc to do this automatically for cdylib and staticlib targets" from the first comment.

**Comment by alexcrichton** [comment]
@RReverser some of those are existing bugs in the compiler (such as `___rust_reallocate`) but others like `___umodti3` are news to me! They shouldn't be in that symbol list at all in theory...

**Comment by RReverser** [comment]
@alexcrichton Apparently they're coming from libcompiler_builtins which does export them explicitly:

```
        #[export_name="__umodti3"]
        pub extern "C" fn u128_mod_(a: u128_, b: u128_) -> $cret {
            unsafe {
                let mut r = ::core::mem::zeroed();
                u128_div_mod(a, b, &mut r);
                ($conv)(r)
            }
        }
```

**Comment by alexcrichton** [comment]
@RReverser indeed! I'm working on a patch (https://github.com/alexcrichton/rust/commit/9048de63aa729b80b193be9933a541a5667f8de7) to fix this but it'll take a moment to finish testing.

**Comment by RReverser** [comment]
@alexcrichton No problem, just let me know when I should send a PR.

In the meanwhile, instead of condition in GnuLinker's export_symbols, defined a separate Linker for Emscripten with support for passing optimization levels, debug levels, and now playing to see whether I can add dynamic linking support.

**Comment by alexcrichton** [comment]
@RReverser I've [posted a PR](https://github.com/rust-lang/rust/pull/39252) for that change.

**Comment by brson** [comment]
> Apparently JS is generated only for binary target

I wonder if this is the correct behavior. Perhaps asmjs staticlibs and/or cdylibs should be .js?

**Comment by brson** [comment]
I honestly don't know what extensions we emit for all the output types for asmjs.

**Comment by brson** [comment]
It looks to me like asm.js uses the default extension types for dylibs and staticlibs, .so, and .a.

I'd say that staticlibs being .a is correct for something you are going to run through emcc, but maybe .so should be .js. Are we really emitting .so files?

**Comment by RReverser** [comment]
@brson We are not - we simply prohibit dynamically linked libs altogether AFAIK. I think what we really should do is generate them via Emscripten's SIDE_MODULE / MAIN_MODULE mechanism, but that requires a little bit more investigation.

Btw, I've left my laptop with changes at the office, will rebase & submit PR for this issue on Monday if that works for you.

**Comment by brson** [comment]
Sounds good @RReverser !
