### ISSUE TITLE
`rustc --enable-compiler-docs` does not work

### ISSUE THREAD

**Issue by alexreg** [rust-lang/rust#39187]
Docs for the `rustc` crate are not included. This is evidenced by https://manishearth.github.io/rust-internals-docs/.

CC @Manishearth

**Comment by steveklabnik** [comment]
Doc team triage: this is on purpose. It's suboptimal, but expected behavior. We'll talk about it at a future docs team meeting, tagging p-medium.

**Comment by steveklabnik** [comment]
Oh, wait. @Manishearth says that this ticket is not "why are there no docs" but "this flag no longer works". Sorry! That is not good.

**Comment by frewsxcv** [comment]
I think this might be fixed now:

https://manishearth.github.io/rust-internals-docs/rustc/index.html

**Comment by alexreg** [comment]
Yep, it looks to be fixed. I noticed that a couple of weeks ago.
