### ISSUE TITLE
#[repr(C)] silently fails depending on location in attribute collection

### ISSUE THREAD

**Issue by valarauca** [rust-lang/rust#39182]
# **Summery**

 `#[repr(C)]` won't apply to a structure depending on the order of the attributes. If `#[repr(C)]` is listed before a `#[derive(..)]` statement it will not apply, but no error is thrown at all. It just silently fails.

While if `#[derive(...)]` is listed before `#[repr(C)]` it will work as expected

This does not effect the 1.14 stable version. But it does effect the 1.16 nightly (1.16 2017-1-17)

# **Re-creation / Example**

### This example works

```rust
#[derive(Clone,Debug)]
#[repr(C)]
pub struct MetaData {
    key_offset: u64,
    data_offset: u64,
    key0: u64,
    key1: u64,
    unix_time: u64,
    hits: u64,
    key_len: u32,
    data_len: u32,
    ns_time: u32,
    timeout: u32
}
#[test]
fn test_metadata_size() {

    //passes
    assert_eq!(64, mem::size_of::<MetaData>());
}
```

### This Example Fails

```rust
#[repr(C)]
#[derive(Clone,Debug)]
pub struct MetaData {
    key_offset: u64,
    data_offset: u64,
    key0: u64,
    key1: u64,
    unix_time: u64,
    hits: u64,
    key_len: u32,
    data_len: u32,
    ns_time: u32,
    timeout: u32
}
#[test]
fn test_metadata_size() {

    //fails
    assert_eq!(64, mem::size_of::<MetaData>());
    //passes
   assert_eq!(80, mem::size_of::<MetaData>());
}
```

# **Compiler Version**

### bug exists on

```
rustc 1.16.0-nightly (c07a6ae77 2017-01-17)
binary: rustc
commit-hash: c07a6ae77cd4ceb3cf591d34c5608ca91d1f75d4
commit-date: 2017-01-17
host: x86_64-pc-windows-gnu
release: 1.16.0-nightly
LLVM version: 3.9
```

### bug doesn't exist on (both examples will correctly size the struct to 64bytes)

(stable not effected)

```
rustc 1.14.0 (e8a012324 2016-12-16)
binary: rustc
commit-hash: e8a0123241f0d397d39cd18fcc4e5e7edde22730
commit-date: 2016-12-16
host: x86_64-pc-windows-gnu
release: 1.14.0
LLVM version: 3.9
```

(beta is fine too)

```
rustc 1.15.0-beta.3 (a035041ba 2017-01-07)
binary: rustc
commit-hash: a035041ba450ce3061d78a2bdb9c446eb5321d0d
commit-date: 2017-01-07
host: x86_64-pc-windows-gnu
release: 1.15.0-beta.3
LLVM version: 3.9
```

**Comment by TimNN** [comment]
For whatever reasons, I cannot reproduce this (on either macOS, Linux or Windows/Gnu (each 64bit)). And even without any `#[repr]` attribute I'm getting a size of 64.

Are you setting any special options?

**Comment by valarauca** [comment]
This can be closed. It was my failure to understand `#[repr(C)]` doesn't imply `#[repr(packed)]`

I re-wrote the structure to pass the test and submitted that with the bug report which was just my mistake

The issue was:

```rust
#[repr(C)]
#[derive(Clone,Debug)]
pub struct MetaData {
    key_offset: u64,
    key_len: u32,
    data_offset: u64,
    data_len: u32,
    key0: u64,
    key1: u64,
    unix_time: u64,
    hits: u64,
    ns_time: u32,
    timeout: u32
}
assert_eq!(72, size_of::<MetaData>());
```

Which isn't an issue this is just standard C structure packing.
