### ISSUE TITLE
Document that std::os::unix::process::CommandExt.uid() triggers setgroups(0,0)

### ISSUE THREAD

**Issue by zackw** [rust-lang/rust#39186]
While digging around for something else I have just discovered that setting the UID for a subprocess with `CommandExt.uid()` also causes a call to `setgroups(0,0)` in the child.  This should be documented.

(Related to #38527)

**Comment by steveklabnik** [comment]
re-tagging as @rust-lang/libs ; would you like this to appear in the docs, or not? If so, we're happy to do it, but want to make sure to not over-specify.

**Comment by joshtriplett** [comment]
This seems like something we should document, yes. It's an unusual special-case that people should be aware of.

This also interacts with https://github.com/rust-lang/rust/pull/72160 .

**Comment by joshtriplett** [comment]
Ok, this is ready for a PR. I've labeled it accordingly.

**Comment by TornaxO7** [comment]
@joshtriplett hi! It may be a long time now but may I ask if this issue is still needed?
