### ISSUE TITLE
feature-gate uninhabited checks

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#39192]
Per the [discussion on internals](https://internals.rust-lang.org/t/recent-change-to-make-exhaustiveness-and-uninhabited-types-play-nicer-together/4602/), we want to ensure that the recent improvements to uninhabited types are feature-gated. There was https://github.com/rust-lang/rust/pull/39151, but that only applies to `&Void`, whereas it seems prudent to try to feature-gate the changes to uninhabited checks more broadly.

cc @eddyb @arielb1 @canndrew

**Comment by nikomatsakis** [comment]
triage: P-high

**Comment by nikomatsakis** [comment]
Marking as P-high because we want to reach a state we are all happy with before next beta.

**Comment by nikomatsakis** [comment]
I'm not sure on just what the algorithm did before the change -- I believe that it specifically handled a case where you wrote `match foo { }` and `foo` was considered uninhabited? So if we wanted to reproduce *just that*  behavior, we would disable the "new" uninhabited check, but retain the older one? 

The main case I am wondering about is stuff like where a `Void` is found inside a field that may (or may not) be accessed. e.g., is `(i32, Void)` uninhabited? Seems like that is not entirely clear in unsafe code (for same reason as `&*`). But I have to refresh my memory for the conversation and don't have a chance just now.

**Comment by arielb1** [comment]
The old algorithm regarded all types as inhabited, except that an empty match was special cased.

About uninhabitableness: I am quite sure you should not be having invalid values. Stuff like nonstandard booleans in an `(u32, bool)` will cause UB by LLVM range assert even today. That means that `(i32, Void)` is truly uninhabited.

**Comment by djzin** [comment]
I find it helpful if we think of `!` /  `Void` as not being a zero-sized type; rather it could be thought of as having "negative infinity" size, being log(0) bits in size. From this perspective `(i32, Void)` doesn't "feel" like it should exist since you are juxtaposing a type with 32 bits next to negative infinity bits, and the infinite wins out.

**Comment by nikomatsakis** [comment]
Fixed by https://github.com/rust-lang/rust/pull/39151

**Comment by nikomatsakis** [comment]
Er, https://github.com/rust-lang/rust/pull/39290

**Comment by nikomatsakis** [comment]
Not yet landed, so I'll leave it open.

**Comment by nikomatsakis** [comment]
Landed now.
