### ISSUE TITLE
Link the rustdoc documentation in the book

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#39205]
The documentation section of the book should advertise rustdoc as a tool and link to its documentation.

**Comment by steveklabnik** [comment]
We are not working on the current book anymore, since we're writing the second edition. I would happily take a PR for this, but since we're not working on it, we're not tracking these kinds of issues. as such, I'm going to give this a close. Please don't hesitate to send in a PR! Thank you!
