### ISSUE TITLE
Document why str.to_lowercase and str.to_uppercase return a String

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#39201]
I haven't checked, but I'm 95% certain that they do this because some characters expand into multiple characters when casefolding which wouldn't fit into the buffer of the `str`, so we need a new buffer. Since we don't know the size beforehand, we just return a `String`.

Probably should link to char.to_lowercase and char.to_uppercase.

**Comment by Havvy** [comment]
(With permission from @ubsan & @awygle)

```
<ubsandroid> I don't understand how they wouldn't
<ubsandroid> even in plain ASCII...
<awygle> don't those take non-mutable references to self anyway, so they couldn't do the mutate-in-place thing?
<awygle> i guess that may not be a "why", exactly...
<Havvy> ubsandroid: Wouldn't do what?
<Havvy> awygle: Well, theoretically could have been &mut str.
<ubsandroid> Havvy: wouldn't be able to return anything but String
<ubsandroid> yeah but it's to_...
<ubsandroid> which is an &T -> U conversion
<Havvy> ubsandroid: Oh, right.
<Havvy> I missed that part of the convention.
<Havvy> Should at least document that the String could have more unicode characters than it started with.
<ubsandroid> yeah
<ubsandroid> sure
```

**Comment by RReverser** [comment]
I think it's not just that, `str` is often enough immutable (static) and can be just precompiled `"str"` constant, in which case these methods would not be useful. And generally replacing original data is not a very good practice unless performance is a concern (in which case specialized version of method can be written).

For example, [`std::ascii::AsciiExt`](https://doc.rust-lang.org/std/ascii/trait.AsciiExt.html) certainly can guarantee that lowercased/uppercased version will take as much space as original character, yet still creates an owned version.
