### ISSUE TITLE
The Book: Missing basic Where clause example

### ISSUE THREAD

**Issue by StefanoD** [rust-lang/rust#39217]
[This](https://www.reddit.com/r/rust/comments/5p5t2k/im_having_a_problem_with_expressing_signature_of/) user had trouble with the Where clause, because a similar example was missing in the book.
You can't find this form of example with equality in the book:

```rust
where I: Iterator<Item = (T, usize)>
```

**Comment by steveklabnik** [comment]
I would happily accept a PR for this, but we're not updating the current book, since we're working on the second one. As such, I'm going to give this a close, but if you or anyone else wants to make this change, please go ahead and send a PR in! Thank you!
