### ISSUE TITLE
`cannot use an outer type parameter in this context`

### ISSUE THREAD

**Issue by yongqli** [rust-lang/rust#39211]
I get the error:

    error[E0402]: cannot use an outer type parameter in this context
      --> <anon>:11:17
       |
    11 |     let a = [3; M::Row::DIM];
       |                 ^^^^^^^^^^^

    error: internal compiler error: unexpected panic

    note: the compiler unexpectedly panicked. this is a bug.

https://gist.github.com/73a223aa33c081bf47d84c2bf52fcc19

**Comment by est31** [comment]
The given example is very similar to the one in #34344 , but this example ICE's on current nightly, while the other example gives a proper error.

**Comment by est31** [comment]
cc #29646

**Comment by withoutboats** [comment]
This now returns a proper error just like #34344. This should probably be closed.

**Comment by est31** [comment]
Maybe a regression test should be added?
