### ISSUE TITLE
rustbuild misses -pthread on final link

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/rust#39215]
Logs available at https://paste.rs/M2c
```
    ./configure \
        --prefix=/usr \
        --enable-ninja \
        --llvm-root=/usr \
        --disable-codegen-tests \
        --jemalloc-root=/usr/lib/libjemalloc_pic.a
# BROKEN: https://github.com/rust-lang/rust/issues/35349
#        --jemalloc-root=/usr/lib/

    export RUSTFLAGS="$RUSTFLAGS -C link-args=-lffi"
    export CFLAGS="$CFLAGS -fPIC -w"
```

**Comment by alexcrichton** [comment]
This is typically the [reponsibility of the standard library](https://github.com/rust-lang/rust/blob/a8fa31029f264988c1dac30778d9cbebdd5eb4d3/src/libstd/build.rs#L41) but I don't see `-lpthread` in the output at all... odd! What system are you on? (to help in reproducing this)

**Comment by ishitatsuyuki** [comment]
Arch amd64, with the provided compilation flags.

**Comment by ishitatsuyuki** [comment]
@alexcrichton: "-l pthread" is passed but possibly somehow truncated in the log. Sorry for the inconvenience.

Back to the topic, you're passing `-lpthread`(**wrong**), not `-pthread`(**correct**).

**Comment by sfackler** [comment]
IIRC `-pthread` only differs from `-lpthread` by changing configuration for the macro processor which is not relevant when linking.

**Comment by ishitatsuyuki** [comment]
@sfackler: -pthread is not passed even when compiling, causing it referencing to undefined symbols.

**Comment by ishitatsuyuki** [comment]
There's two way to achieve this:

1. Allow arbitrary flags in cargo:rustc-flags to add -pthread.
2. Refactor and add it in the gcc crate.

**Comment by ishitatsuyuki** [comment]
https://github.com/rust-lang/rust/blob/master/mk/cfg/x86_64-unknown-linux-gnu.mk#L13

@alexcrichton This is not by luck, this is **intended** in the old buildsystem.

**Comment by tamird** [comment]
https://github.com/rust-lang/rust/commit/829b5de9988fa71a7a585df5b9c46ea07e05a431
