### ISSUE TITLE
benchmarking test not using -O flag by default

### ISSUE THREAD

**Issue by Dowwie** [rust-lang/rust#39223]
I benchmarked the following code https://is.gd/rDGMrK and discovered a huge performance difference when the -O flag is explicitly used during compilation.  It is my impression that -O functionality was intended for default configuration and not require use of a -O flag and so I am raising this as an issue: 

**1. Without -O flag:**
*rustc --test init_parts_solution1.rs && ./init_parts_solution1 --bench*
running 1 test
test bench_this ... bench:       **5,194 ns/iter** (+/- 41)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured

**2. With -O flag:**
*rustc --test -O init_parts_solution1.rs && ./init_parts_solution1 --bench*                           
running 1 test
test bench_this ... bench:          **63 ns/iter** (+/- 0)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured

**Comment by Mark-Simulacrum** [comment]
rustc won't compile tests with optimizations by default, but `cargo bench` will, so this feels like a works as intended issue. You usually want tests (not benchmarks) to be compiled without optimizations.

**Comment by sfackler** [comment]
Yep, this is working as intended.

**Comment by Dowwie** [comment]
thanks for confirming
