### ISSUE TITLE
No rule to make target `make check-stage1-rustdocck`

### ISSUE THREAD

**Issue by jacwah** [rust-lang/rust#39256]
From Makefile.in:

```
# * make check-stage1-rustdocck: Builds rustdoc. It has the advantage to compile
#                                quite quickly since we're only using stage1
#                                executables.
```

However, this doesn't seem to work. Am I doing something wrong?

```
$ make check-stage1-rustdocck
make: *** No rule to make target `check-stage1-rustdocck'.  Stop.
```

The same also goes for `make check-stage1-std`.

**Comment by petrochenkov** [comment]
Do you pass `--disable-rustbuild` to `./configure`?
It looks like you are using `rustbuild` and it doesn't define all these `check-stage1-crate` rules.

**Comment by petrochenkov** [comment]
(FWIW, `check-stage1-rustdocck` specifically was recently broken in the `make` buildsystem as well, it builds stage2 now)

**Comment by jacwah** [comment]
No, I didn't use `--disable-rustbuild`, that must be the issue. Thanks!
