### ISSUE TITLE
sample doc code for custom allocators uses libc in a no_std crate

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#39262]
Look at the documentation for custom allocators: https://doc.rust-lang.org/book/custom-allocators.html

It gives a bare-bones set of hooks into libc's malloc/realloc/free functions (noting that the implementation is failing to uphold alignment guarantees in the comments).

However, if one were to try to use the `crates.io` version of the `libc` crate, one runs into the problem that the `libc` crate by default does not declare itself to be `#![no_std]`.

If the allocator is the *only* client of `libc`, or if all such clients can be locally enumerated in one's project, then one can work around this problem by using this in the `Cargo.toml` for all the `libc` clients (including the allocator):

```
[dependencies]
libc = { version = "0.2.17", default-features = false }
```

However, as soon as one client of `libc` lets the default-features through, it falls apart and you get a build error complaining that your allocator crate depends on a crate that depends on `alloc`.

 * (The error reporting is also not great, in that it is not feasible to track down which crates are causing the problem to arise.)

----

Anyway, from a conversation with @alexcrichton , my understanding is that the long term plan here is to change the `libc` crate to be a `#![no_std]` crate. But this is a breaking change, so it needs to wait until the libs team decides to do a major version bump on `libc`.

I just wanted to jot down this issue so that I or others can refer to it when discussing this problem with trying to adapt the existing custom allocator code.

**Comment by pnkfelix** [comment]
(The solution that I adopted after the conversation with people on the `#rust-libs` channel was to just encode the specific type and `extern fn` defintions that I needed right into my local crate. I put them into local `mod libc { ... }` so that it should be easy to switch back to `extern crate libc;` in the future (yay inline modules!).)

**Comment by steveklabnik** [comment]
The new book has nothing about this stuff, once the bookshelf RFC lands, this will be part of the nightly book, too. Just something related; it's going to make the example both less and more prominent, in a sense.

**Comment by pnkfelix** [comment]
@steveklabnik wait so where is the documentation for custom allocators going to live?

**Comment by steveklabnik** [comment]
Triage: given that this is in the old book, marking as P-low

@pnkfelix regarding your last comment, https://doc.rust-lang.org/nightly/unstable-book/allocator.html

**Comment by steveklabnik** [comment]
We have decided that we're not tracking issues for the old book anymore, therefore, gonna give this one a close. If anyone wants to send in a PR to @rust-lang/book, please do!
