### ISSUE TITLE
syntax::tokenstream::TokenStream does not implement From<String>

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#39269]
Which means it cannot be created from a `quote::Tokens` by just calling parse. The fact that we have multiple TokenStream types makes writing syntax extensions very confusing. They should at least provide a similar API, so I guess that the right fix is to implement `From<String>` for `syntax::tokenstream::TokenStream`. 

In the mean time, does anybody has a workaround for this?

**Comment by jonas-schievink** [comment]
Don't you mean the `FromStr` trait?

**Comment by chpio** [comment]
> In the mean time, does anybody has a workaround for this?

looking for a wa too, any new ideas?

**Comment by chpio** [comment]
got it working:

```rust
    let source_str = quote!(foo bar).as_str();
    let sess = ParseSess::new();
    let filemap =
        sess.codemap().new_filemap("<procmacro_lex>".to_string(), None, source_str.to_owned());
    let my_ts = filemap_to_tts(&sess, filemap).into_iter().collect();
```
copy & pasted that from the `lex` function from the removed `proc_macro_tokens` crate: https://github.com/rust-lang/rust/commit/31417efcd3e739b48c1cf78214e8c4ff82dc424f#diff-125faa3511be3d48d99690b983001c7fL18

**Comment by Mark-Simulacrum** [comment]
cc @jseyfried @nrc, what's the status of this with macros 2.0 incoming? Are we adding this impl, removing this TokenStream?

**Comment by jseyfried** [comment]
With macros 2.0, no one will use `syntax::tokenstream::TokenStream` outside the compiler, so this issue will be moot.

**Comment by Mark-Simulacrum** [comment]
Closing as per the above -- there is no meaningful use for this type outside the compiler itself and there it can be added if desired (no issue is necessary) as part of a PR.
