### ISSUE TITLE
Faulty VC++ build tools diagnostic on Windows 10

### ISSUE THREAD

**Issue by Rojetto** [rust-lang/rust#39261]
I just tried to install Rust via rustup on Windows 10 64 bit. After running rustup-init it complained about the missing VC++ build tools (as it should, I didn't have them installed).
I then downloaded and installed them with the first link it suggested (http://landinghub.visualstudio.com/visual-cpp-build-tools). After rebooting and running rustup it still complained about them allegedly missing. I then just ignored the warning and continued with the installation, which completed succesfully. The target it defaulted to and that it installed is x86_64-pc-windows-msvc. Compiling and running a simple rust program also worked, so it seems like just the diagnostic, whether the build tools are installed didn't work.

**Comment by retep998** [comment]
This issue probably belongs in https://github.com/rust-lang-nursery/rustup.rs/issues

**Comment by Rojetto** [comment]
Whoops, didn't know that was a separate repo. I opened the issue over there. I guess this can be closed?
