### ISSUE TITLE
Misplaced span for the error "does not live long enough"

### ISSUE THREAD

**Issue by KalitaAlexey** [rust-lang/rust#39268]
[Playground](https://is.gd/SdkR3U)

**Code**:

```rust
fn main() {
    let mut x = &5;
    {
        let y = 5;
        x = &y;
    }
}
```

**Compiler's output**:

```
error: `y` does not live long enough
 --> <anon>:6:5
  |
5 |         x = &y;
  |              - borrow occurs here
6 |     }
  |     ^ `y` dropped here while still borrowed
7 | }
  | - borrowed value needs to live until here

error: aborting due to previous error
```

Look at ` --> <anon>:6:5`.
It points to the `}`,
but I expected it to point to the `y`.

Look at `  |     ^ `y` dropped here while still borrowed`.
It is treated as a primary span,
but I expected `  |              - borrow occurs here` to be treated as a primary span.

It is bad for editors, i.e., VSCode.

**Comment by Mark-Simulacrum** [comment]
It's not strictly speaking obvious which span should be the primary, but probably the first one (borrow occurs here) is better.

**Comment by Mark-Simulacrum** [comment]
err, not E-needstest - this needs to be fixed.

**Comment by estebank** [comment]
This seems to have been [done on purpose](https://github.com/rust-lang/rust/blob/188cdf49/src/librustc_borrowck/borrowck/mod.rs#L765-L768). @nikomatsakis do you see any reason not to remove the `db.span = ...` reassignments? I'm leaning heavily towards doing it.
