### ISSUE TITLE
Converting integers to pointers using "as _" works, but produces error messages if a different error occurs

### ISSUE THREAD

**Issue by jmegaffin** [rust-lang/rust#39273]
This code is fine.
```
fn main() {
    let x: *const () = 0 as _;
}
```
But when the following code fails to compile because of the unresolved `foo`, an additional error message is generated for the integer-pointer conversion.
```
fn main() {
    foo();
    let x: *const () = 0 as _;
}
```
```
rustc 1.14.0 (e8a012324 2016-12-16)
error[E0425]: unresolved name `foo`
 --> <anon>:2:5
  |
2 |     foo();
  |     ^^^ unresolved name

error: non-scalar cast: `{integer}` as `*const ()`
 --> <anon>:3:24
  |
3 |     let x: *const () = 0 as _;
  |                        ^^^^^^

error: aborting due to previous error
```
This makes it very annoying to debug a large program with lots of this kind of integer-pointer conversion that fails for some other reason, as an extra message is generated for every conversion.

**Comment by nagisa** [comment]
> This code is fine.

No it is not. usize does not implicitly convert to a pointer, raw or not.

**Comment by jmegaffin** [comment]
It compiles.  If it shouldn't, well, it shouldn't.

**Comment by rkruppe** [comment]
What's your Rust version? The program does not compile on current stable, beta, or nightly playground.

**Comment by petrochenkov** [comment]
http://rust.godbolt.org has quick access to all versions since 1.0 and this code fails to compile on all of them.

**Comment by jmegaffin** [comment]
Sorry, I misrepresented the issue here.  It's really got to do with conversion using `as _`.  I've updated the original post to reflect this.

**Comment by jmesmon** [comment]
Here's the example code fixed up. Uncomment `foo()` to see the failure that emits 1 expected error and a second that dislikes the cast.

https://is.gd/goAcm7

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/35772.
