### ISSUE TITLE
Try harder to continue through errors in type checking

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#39275]
If you look at librustc_typeck/lib.rs:check_crate, you see a bunch of `tcx.sess.track_errors` and early returns with `?`. In most of these cases (perhaps all except type collection), we should be able to continue type checking instead of returning. That would mean getting more errors to the user sooner, and getting type info in more circumstances in IDEs.

**Comment by nrc** [comment]
Sometimes, this leads to multiple errors where one would be enough, this ought to be able to be addressed by changing the type of an expression to `TyErr`, but I'm not sure if that kind of mutation is possible.

**Comment by estebank** [comment]
Quite a bit of work has been put into this and we'll continue to do so. I'll close this ticket but we can reopen more focused and actionable tickets in this front.
