### ISSUE TITLE
Tracking issue: Provide Entry-like API for Option

### ISSUE THREAD

**Issue by shahn** [rust-lang/rust#39288]
Often I have code where Option is used to indicate whether a value has been initialized or not. In these instances I often have code that either wants to use the value directly or initialize it and then use the value. So what I'm looking for is similar to as_ref()/as_mut() except they should return &T/&mut T respectively, and take either a value or a closure.

I think I would call the functions get{,_mut}_or_insert{,_with}() marrying the get_ functions (for example in hashmaps) for getting references with the or_insert Entry like functions.

**Comment by Thinkofname** [comment]
Isn't this just `as_ref/mut().unwrap_or(val)` and `as_ref/mut().unwrap_or_else(|| val)` ?

**Comment by shahn** [comment]
indeed

**Comment by tbu-** [comment]
See also #25149 and #29203.

**Comment by shahn** [comment]
AIUI, this is not fixed by #39289, because this issue is referenced as the tracking issue for the implementation and should stay open until it's decided whether this is to be stabilized or backed out.

**Comment by tbu-** [comment]
Ah, right. Maybe you could put "Tracking issue" in the title.

**Comment by oberien** [comment]
As this is quite old already (over 3 months), would it be possible to stabilize these two functions soon?

**Comment by brson** [comment]
@rfcbot merge

**Comment by dtolnay** [comment]
@rfcbot reviewed

**Comment by alexcrichton** [comment]
To be clear, the APIs proposed here for stabilization are:

```rust
impl<T> Option<T> {
    fn get_or_insert(&mut self, v: T) -> &mut T;
    fn get_or_insert_with<F: FnOnce() -> T>(&mut self, f: F) -> &mut T;
}
```

**Comment by dhardy** [comment]
This isn't `Entry`-like. If it was, it would be possible to do the following:

```
match opt_value.entry() {
    VacantEntry(entry) => entry.insert(x),
    OccupiedEntry(entry) => { assert_eq!(entry.get(), x); }
}
```

**Comment by SimonSapin** [comment]
@dhardy That particular example can be written as:

```rust
match opt_value {
    ref mut entry @ None => *entry = Some(x),
    Some(ref entry) => assert_eq!(entry, x),
}

**Comment by raphlinus** [comment]
To save time for people researching this, the feature landed in stable at Rust 1.20 (source: 64c1b23).

**Comment by shepmaster** [comment]
@raphlinus I think that commit is wrong :-) The function in question doesn't show up in [the 1.20.0 docs](https://doc.rust-lang.org/1.20.0/std/option/enum.Option.html) but does in [the 1.21.0 docs](https://doc.rust-lang.org/1.21.0/std/option/enum.Option.html). GitHub also says that commit is only in the 1.21.0 tag. We should probably fix the stability annotation.

**Comment by shepmaster** [comment]
Ah, [the 1.20.0 commit was a backport](https://github.com/rust-lang/rust/commit/d85df50da05), thus why it's a different tag.
