### ISSUE TITLE
[easy] iterator documentation improvement.

### ISSUE THREAD

**Issue by iqualfragile** [rust-lang/rust#39294]
in the rust docs https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.filter_map

it says why is filter_map not equal to filter().map()

this makes no sense

it should ask

why is filter_map not equal to map().filter().

also would be nice to explain that filter_map is is basically map().filter(is_some).map(unwrap) might make it easier to grasp.

**Comment by frewsxcv** [comment]
Addressed in https://github.com/rust-lang/rust/pull/43965.
