### ISSUE TITLE
An external crate can add an impl which breaks local type inference

### ISSUE THREAD

**Issue by stepancheg** [rust-lang/rust#39308]
I've encountered a misterious problem: if crate has a `regex-syntax` dependency (actually, it was `env-logger`), type inference breaks in this case:

```
let v: Vec<u8> = Vec::new();
let b = v == Vec::new();
```

with error:

```
error[E0282]: unable to infer enough type information about `T`
  --> src/main.rs:22:18
   |
22 |     let b = v == Vec::new();
   |                  ^^^^^^^^ cannot infer type for `T`
   |
   = note: type annotations or generic parameter binding required
```

In stable, beta or nightly rust.

Apparently, it is because `regex-syntax` overrides `PartialEq<Something>` for `u8`. It took from me quite amount of time to find the cause. It looked like a complete mistery and a bug in the compiler.

Full example is here: https://github.com/stepancheg/rust-cannot-infer-type. Comment out `exten crate regex_syntax` and it starts to compile properly.

I don't know if anything can be done to improve the situation: fix type inference, or at least provide better diagnostics.

If there's nothing can be done, please close the issue.

**Comment by Mark-Simulacrum** [comment]
I believe it is considered acceptable for new impls to cause inference breakage; closing. cc @aturon -- can you confirm that's correct?

**Comment by aturon** [comment]
Yes, this is indeed a tradeoff we had to make. See [Niko's blog](http://smallcultfollowing.com/babysteps/blog/2014/09/30/multi-and-conditional-dispatch-in-traits/#crate-concatenability-and-inference) for details.
