### ISSUE TITLE
Come up with a consistent interface for rustc_driver::driver

### ISSUE THREAD

**Issue by aochagavia** [rust-lang/rust#39315]
It would be useful for [miri](https://github.com/solson/miri/) to have access to a `after_mir_passes` callback in the compile process. However, this cannot be implemented without breaking changes to the current API (we need to run the callback from inside `phase_4_translate_to_llvm`, which doesn't have access to the `CompileController`).

Maybe this is the moment to step back and review the current implementation of the `driver.rs` module. Particularly, I would like to propose making parts of the current implementation private and let the users interface with the compiler through `CompileController` only. I think we could begin by making all `phase_n_*` functions private.

**Comment by Mark-Simulacrum** [comment]
I was under the (perhaps incorrect) perception that rustc_driver and other crates in the rust tree are unstable, so breaking compatibility isn't a problem.

**Comment by aochagavia** [comment]
You are still breaking people's code, so it would be great to minimize that if possible.

**Comment by nbp** [comment]
For your information, I needed the same thing for a pet-project that I am starting, which involves generating assembly ( / LIR?) out of the MIR, and attaching this generated code back as constants on the MIR, to be consumed by the program execution.

The simplest I found was to add a new plugin interface [1] to do so.  I don't think this would solve your current issue though, but if this interface can solve both purposes, I would be happy to help.

[1] https://github.com/rust-lang/rust/compare/master...nbp:register_opt_mir_pass

**Comment by solson** [comment]
On-demand compilation is going to shake up the driver code a lot, so we might have to rethink our approach here.

@eddyb @nikomatsakis Can you weigh in on how you think the driver is going to change? (Or is it still pretty unknown?)

**Comment by eddyb** [comment]
With on-demand you'd probably want pre/post-query hooks, with post-query also seeing the value.
For values that we don't want to cache (e.g. HAIR if we built it eagerly), it could work pretty well.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this issue because I don't see it as useful: I don't think we're at the point where work on a stable-r driver API is reasonable. If you're interested in pursuing this, I'd start an internals thread with some concrete suggestions and then go from there.
