### ISSUE TITLE
rustdoc --help prints full path to arg0

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#39310]
```
brian@ip-10-145-43-250:~/dev⟫ rustdoc --help
/home/brian/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustdoc [options] <input>

Options:
    -h --help           show this help message
    -V --version        print rustdoc's version
    -v --verbose        use verbose output
    -r --input-format [rust]
```

No other rust tools do this. Just hard-code 'rustdoc' here.

**Comment by mgattozzi** [comment]
I'll take a crack at it. Quickly looking at the code this is probably where it messes up right?
https://github.com/rust-lang/rust/blob/ecff71a45c9d1aff9ba5dbc212cb1353578525ee/src/librustdoc/lib.rs#L194
