### ISSUE TITLE
Proc macro gives bad error about custom derives if regular macro with the same name is imported first

### ISSUE THREAD

**Issue by Arnavion** [rust-lang/rust#39326]
rustc 1.16.0-nightly (7821a9b99 2017-01-23)

`main.rs`

```rust
#[macro_use] extern crate derive_error_chain;
#[macro_use] extern crate error_chain;

#[derive(Debug, error_chain)]
pub enum ErrorKind {
    Msg(String),
}

fn main() {
}
```

`Cargo.toml`

```toml
[package]
name = "rust-test"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]

[dependencies]
derive-error-chain = "=0.8.0"
error-chain = "=0.8.1"
```

`cargo build` gives:

```
error: `#[derive]` for custom traits is not stable enough for use. It is deprecated and will be removed in v1.15 (see issue #29644)
 --> src\main.rs:4:17
  |
4 | #[derive(Debug, error_chain)]
  |                 ^^^^^^^^^^^
  |
  = help: add #![feature(custom_derive)] to the crate attributes to enable

error: aborting due to previous error
```

`derive-error-chain` exports a proc macro named `error_chain`. `error-chain` exports a regular macro named `error_chain`.

Everything's fine if the order of the `extern crate` statements is reversed, or `error-chain`'s import does not have `#[macro_use]`.

**Comment by keeperofdakeys** [comment]
Unfortunately macro_rules, proc-macro derives, and future proc-macros share the same namespace.

**Comment by Arnavion** [comment]
I'm not asking for a way to make this work. I'm asking for an error message that isn't misleading :)

**Comment by keeperofdakeys** [comment]
Ah, I'm actually working on a PR right now which should fix this, I'll be sure to keep it in mind https://github.com/rust-lang/rust/pull/39391.
