### ISSUE TITLE
Add suggestions for potentially misspelled #[derive] traits

### ISSUE THREAD

**Issue by elliotekj** [rust-lang/rust#39323]
I [ran into an error](https://github.com/rust-lang/book/issues/421) when compiling a program a couple of days ago that turned out to be due to a spelling mistake. It was suggested by @carols10cents that I create an issue here to discuss adding a “Did you mean X?” hint when compiling fails because of a trait's name.

For clarity's sake, the screenshot below was the error I got and this is the sort of thing I'm suggesting:

```
error: Custom traits have been depreciated.
 --> src/main.rs:1:10
  |
1 | #[derive(debug)]
  |          ^^^^^
note: Did you mean `#[derive(Debug)]`?
```

<img width="762" alt="screen shot 2017-01-24 at 21 30 21" src="https://cloud.githubusercontent.com/assets/1547124/22267744/45717970-e285-11e6-8af3-982b0185b7fc.png">

I expect this hinges somewhat on whether or not #29644 goes through.

**Comment by jseyfried** [comment]
cc @keeperofdakeys

**Comment by keeperofdakeys** [comment]
By the way, I'm currently working on fixing this.

**Comment by petrochenkov** [comment]
cc https://github.com/rust-lang/rust/issues/30197#issuecomment-272618423
