### ISSUE TITLE
Error-index tests are spewing thousands of lines of errors

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#39327]
I've noticed this recently on the Travis/AppVeyor logs, but I haven't tracked it down yet to see what caused it.

**Comment by alexcrichton** [comment]
Appears caused by https://github.com/rust-lang/rust/pull/39199. @nikomatsakis perhaps caused by https://github.com/rust-lang/rust/pull/39142?

**Comment by nikomatsakis** [comment]
@alexcrichton ummmmmmmmm *perhaps*..... the tests are not *failing* though? Do you have a link to an example?

**Comment by alexcrichton** [comment]
Oh right sorry I meant only that output is being generated, not that tests are failing. Most of the tests expect a failure which is the reason so many errors are printed.

An example is here (https://travis-ci.org/rust-lang/rust/jobs/192869604#L7886) from the logs of that PR (how nifty I can check that out!). You should be able to reproduce this locally as well via

```
./x.py test src/tools/error_index_generator
```
