### ISSUE TITLE
Doc: 'empty' documentation block causes display issues

### ISSUE THREAD

**Issue by michael-zapata** [rust-lang/rust#39339]
Using `///` blocks with whitespaces only displaces the associated declaration. This behaviour isn't displayed when no whitespaces are used.

It's fairly easy to reproduce:
```rust
// will cause display issues, note the whitespaces
///    
pub fn foo() {}

// ok, no whitespaces
///
pub fn bar() {}
```

cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Fixing it.
