### ISSUE TITLE
macros: don't `cfg`-process items before applying attribute proc macros

### ISSUE THREAD

**Issue by jseyfried** [rust-lang/rust#39336]
cc #38356

**Comment by jseyfried** [comment]
cc @abonander @keeperofdakeys

**Comment by KalitaAlexey** [comment]
@jseyfried,
I can't understand the title.
Can you make it clear please?

**Comment by jseyfried** [comment]
Suppose we have an attribute proc macro `attr`:
```rust
#[proc_macro_attribute]
fn attr(input: TokenStream) -> TokenStream { ... }
```
and an invocation of `attr`:
```rust
#[attr] fn f() { #[cfg(any())] fn g() {} }
```

Today, we `cfg`-process `fn f` (resulting in `fn f() {}`) before we apply `attr`.
In other words, the `input: TokenStream` argument is `fn f() {}`.

Instead, we want the `input` to be `fn f() { #[cfg(any())] fn g() {} }`.

**Comment by KalitaAlexey** [comment]
I got it.
*cfg-process* means processing `#[cfg]` attributes.

**Comment by jdhorwitz** [comment]
Is this still available to be picked up with a Mentor?

**Comment by jseyfried** [comment]
@jdhorwitz 
Yeah, feel free to ping me (`jseyfried`) on IRC (`#rustc`/`#rust-internals`) or ask questions here.

**Comment by shioju** [comment]
@jdhorwitz are you still working on this? If not, I'd like to take it up. Thx.

**Comment by jseyfried** [comment]
@shioju feel free to pick it up :)

**Comment by tamird** [comment]
@shioju are you still working on this?

**Comment by tmnilsson** [comment]
I have looked into this issue as a way to getting to know the rustc source code. I think I might be able to make a fix now, unless anyone is currently working on it?

**Comment by shioju** [comment]
Hey all, sorry for holding this up. Not working on this now. Please go ahead.

**Comment by kaimast** [comment]
Hey all,

I searched all over the web but cannot find an easy answer to this. If I want to process all `cfg`-attributes before applying my custom proc macro, how do I do that? Is there some function I can invoke on my `TokenStream`?

**Comment by jayvdb** [comment]
@kaimast https://github.com/rust-lang/rust/issues/39336 might be what you are looking for.
