### ISSUE TITLE
i686-pc-windows-gnu: compiler-rt warning: conflicting types for built-in function

### ISSUE THREAD

**Issue by segevfiner** [rust-lang/rust#39359]
You can see this in AppVeyor for example: https://ci.appveyor.com/project/rust-lang/rust/build/1.0.1741/job/3b169bqrprb5oitk#L261

I'm not sure if this is actually a problem or if it's benign. But it did pop up in my face while trying to build.

**Comment by Mark-Simulacrum** [comment]
I can't find this in a more recent AppVeyor build so I'm going to close.

**Comment by segevfiner** [comment]
I don't see it locally either. So it was probably fixed by either a gcc upgrade or a change in compiler-rt.
