### ISSUE TITLE
Tiny doc wording change

### ISSUE THREAD

**Issue by adrian5** [rust-lang/rust#39366]
[Sync > Condvar](https://github.com/rust-lang/rust/blob/master/src/libstd/sync/condvar.rs#L38-L39)
> The predicate is always verified inside of the mutex before determining that thread must block.

Rather "determining that **a** thread"?

[Alloc > Rc](https://github.com/rust-lang/rust/blob/master/src/liballoc/rc.rs#L15-L16)
> The type `Rc<T>` provides shared ownership of a value of type `T`, allocated in the heap.

Rather "allocated **on** the heap"? That's how it know it.

**Comment by phungleson** [comment]
Quickly did a search, seems like `in the heap` is a very common phrase in the doc.

Maybe it is a convention?

**Comment by adrian5** [comment]
Yes, I hadn't considered that. It's self-evident that things are (metaphorically) put **on**to the stack , and maybe some programmers adopted the phrase for both. For the heap, **in** works too. Is there a difference in expressing data being written (on), and residing somewhere (in)?

In the book, the section on the [stack and heap](https://github.com/rust-lang/rust/blob/master/src/doc/book/the-stack-and-the-heap.md) appears to use **on** throughout.

**Comment by phungleson** [comment]
Sorry I accidentally close this via my PR, feel free to reopen this if you want.

My unscientific checking shows that `java "on the heap"` has the same number of result with `java "in the heap"` in google so maybe they are both commonly used.
