### ISSUE TITLE
Add new io::ErrorKind - BufTooSmall and use it in Read::read_to_end

### ISSUE THREAD

**Issue by Mingun** [rust-lang/rust#39365]
I work on binding to Oracle Call Interface for Rust and faced a problem in case of implementation of reading contents of CLOB. Functions of Oracle for reading CLOB accept the buffer in which to read data on an input and return a count of readed bytes and a sign of whether there are still data for reading. At the same time data are read character-by-character -- i.e. if in the encoding utf-8 the character occupies more than one byte, then either `N` bytes, or `0` will be read.

It is natural that for the interface of reading CLOB there is a wish to provide standard Rust interface for data reading -- [`io::Read`][read]. However it means that all methods of [`io::Read`][read] shall work, as expected, in particular, [read_to_end][read_to_end] shall read all data of CLOB.

However he isn't always capable to make it as in the course of reading the buffer for reading can be reduced to such nonzero value that Oracle won't begin to read in it the character and will return value tuple `(0 bytes are read, still there are data)`. In this case it is necessary to increase the size of the buffer and to try to read once again. That it became possible, I suggest to introduce the new [`ErrorKind`][error] code -- `BufTooSmall` (this is also counterpart of `WriteZero` for read operations) and in case of its return to process this case also when in the buffer there is no place left -- increase buffer.

[read]: https://doc.rust-lang.org/std/io/trait.Read.html
[read_to_end]: https://github.com/rust-lang/rust/blob/master/src/libstd/io/mod.rs#L344-L373
[error]: https://doc.rust-lang.org/std/io/enum.ErrorKind.html

**Comment by nagisa** [comment]
`read_to_end` takes a `&mut Vec<u8>`, which pretty much screams that `read_to_end` will resize the buffer to whatever size it needs itself.

For regular `read`, a too small buffer is signified by the OS error `EINVAL` (unixes)/`ERROR_INSUFFICIENT_BUFFER` (windows).

**Comment by Mingun** [comment]
> For regular read, a too small buffer is signified by the OS error EINVAL (unixes)/ERROR_INSUFFICIENT_BUFFER (windows).

Hm... and how this help me with my issue?

> `read_to_end` takes a `&mut Vec<u8>`, which pretty much screams that `read_to_end` will resize the buffer to whatever size it needs itself.

`read_to_end` will resize buffer only when in it [no free space at all][1]. But in my case buffer HAS free space, but Oracle function not fill it because this space not enough for they work. If I return `Ok(0)` from my implementation of `Read` for CLOB `read_to_end` just stop reading, but this is incorrect because not all CLOB readed. So I need return some error, indicating that buffer need to be increased. But now any error, except `Interrupted` also stop reading. But if I return `Interrupted` where will be infinity loop, because buffer stay the same.

[1]: https://github.com/rust-lang/rust/blob/master/src/libstd/io/mod.rs#L350

**Comment by nagisa** [comment]
> Hm... and how this help me with my issue?

I’m just stating that it makes little sense to add a new variant because

1. it wouldn’t get used at all on unixes;
2. would be breaking change for anybody matching on `ErrorKind::Other` when they expect `ERROR_INSUFFICIENT_BUFFER`.

As I said in previous message, when the default implementation of `read_to_end` does not fit your needs, the solution is to implement your own `read_to_end`.

**Comment by Mingun** [comment]
>  it wouldn’t get used at all on unixes

Why? Why it is impossible to translate `EINVAL` error to new enum option? Besides, the scope of language isn't restricted to only unixes.

> would be breaking change for anybody matching on `ErrorKind::Other` when they expect `ERROR_INSUFFICIENT_BUFFER` on windows.

Only if to begin to translate `EINVAL`/`ERROR_INSUFFICIENT_BUFFER` error to new enum option. Though it will also be logical in my opinion, within this issue I don't suggest it to do, need of this step shall be discussed in the separate issue if this one will be implemented.

> As I said in previous message, when the default implementation of `read_to_end` does not fit your needs, the solution is to implement your own `read_to_end`.

`read_to_end` will be called not by me, but end-user of my library or even other library to which the end-user will transfer results from my library. So this unacceptable solution -- I can't force all to implement own `read_to_end` (or it is impossible at all in a case with third-party library which already uses standard implementation) and the more so to explain why to them to do it when there is standard one is exist.

**Comment by nagisa** [comment]
> So this unacceptable solution -- I can't force all to implement own read_to_end (or it is impossible at all in a case with third-party library which already uses standard implementation) and the more so to explain why to them to do it when there is standard one is exist.

I do not follow. `Read::read` is in exactly the same trait as `Read::read_to_end` is. If you implement a custom `Read::read` you can also implement a custom `Read::read_to_end`, no?

**Comment by Mingun** [comment]
> I do not follow. `Read::read` is in exactly the same trait as `Read::read_to_end` is. If you implement a custom `Read::read` you can also implement a custom `Read::read_to_end`, no?

Oh, really... thank you very much, I somehow didn't think of it. Though introduction of a new type of an error being still represented to me by the useful enhancement.

**Comment by Mark-Simulacrum** [comment]
I don't think there's much worth in adding the new error kind since it's not used on unixes and would be odd on windows (since the stdlib would probably not return it due to concerns over stability).
