### ISSUE TITLE
regression in diesel in recent nightlies

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#39377]
Diesel has been seeing a number of these lately: https://gitter.im/diesel-rs/diesel?at=588d2606e836bf7010a34858

Apparently it's only a problem in newer nightlies. More investigation is needed.

**Comment by sfackler** [comment]
Might be https://github.com/rust-lang/rust/issues/39347?

**Comment by jseyfried** [comment]
Yeah, this is #39347 (closing in favor of that) -- should be fixed in a day or two.
In the meantime, a workaround is to remove `#![feature(proc_macro)]`.
