### ISSUE TITLE
Why does this happens with print and println?

### ISSUE THREAD

**Issue by ericsantosbr** [rust-lang/rust#39395]
Hello! I just started to study Rust yesterday, but a while ago i have passed for some troubles. I was trying to make some code to test myself if i really learned something from the yesterday night that i passed reading and writing the code from the Rust book that the development team provides. All i did was write a code that reads the user input after a "print!" command (sorry, i don't remember the right term for that), and after that, shows the user input after a "println!" command. But, i've just noticed something. When i write the code this way, the Terminal waits for the user input in the beginning of the code, what was not supposed to happen. But, this just don't happen when i use the "println!" command, instead of the "print!". The terminal prints the words that it was supposed to print, and then waits for the user input.

I've recorded a video to explain, and i'm about to update it on YouTube, just in a moment.

(sorry if i made some mistake while writing, english is not my mother language :) )

**Comment by nagisa** [comment]
`stdout` is line-buffered. You need to flush your `stdout` for it to appear on screen immediately if there’s no newline after your message (i.e. if you’re using the `print!` macro).

```
print!("input: ");
::std::io::stdout().flush().expect("flushed");
```

should suffice.

**Comment by ericsantosbr** [comment]
Oh, thanks! That worked! But now i have one more problem: i'm confused with these parameters in the use line. But that i can resolve with the time. Thank you! :)

Oh, and one more thing! The program runned perfectly, but should i get preocupated with this return that i've got from the terminal? 

> warning: crate `outroTeste` should have a snake case name such as `outro_teste`, #[warn(non_snake_case)] on by default



`

**Comment by nagisa** [comment]
That is a style warning. You may ignore it if you don’t care about style yet.
