### ISSUE TITLE
"Use of moved value" error when two lines are combined into one

### ISSUE THREAD

**Issue by bfops** [rust-lang/rust#39398]
The following code works:

```
struct Uncopyable;

struct T {
  x : Uncopyable,
  y : Uncopyable,
}

fn main() {
  let t = Box::new(T { x: Uncopyable, y: Uncopyable });
  let t = *t;
  let T { x, y } = t;
  let _ = x;
  let _ = y;
}
```

However, if the two lines deconstructing `t` are combined into `let T { x, y } = *t;`, suddenly there's an error:

    error[E0382]: use of moved value: `t`
      --> <anon>:10:14
       |
    10 |   let T { x, y } = *t;
       |           -  ^ value used here after move
       |           |
       |           value moved here
       |
       = note: move occurs because `t.x` has type `Uncopyable`, which does not implement the     `Copy` trait
    
    error: aborting due to previous error

Is this a bug, or do these pieces of code actually express different things?

**Comment by Mark-Simulacrum** [comment]
This doesn't appear to break today on `rustc 1.19.0-dev (5dfcd85fd 2017-05-19)`. Closing.
