### ISSUE TITLE
macros: simplify `tt` matchers

### ISSUE THREAD

**Issue by jseyfried** [rust-lang/rust#39403]
Ideally, `tt` matches either a single token or delimited sequence (e.g. `{ arbitrary tokens }`).
However, the following compiles today:
```rust
macro_rules! m { ($t:tt) => {} }
m!($x);
m!($(x)*);
m!($x:ident);
```
We want to avoid leaking details of `macro_rules!` syntax into the semantics of `tt`, at least for macros 2.0.

**Comment by durka** [comment]
What does "fixing" this entail? Which examples still work?

**Comment by jseyfried** [comment]
@durka  
None of those examples will work with macros 2.0, but then macros 2.0 will allow escaping `$`.

I think fixing this means that at least the second and third examples don't work. However, we might need to continue allowing the first example for back-compat and since there isn't a good workaround without being able to escape `$`.

Also, we could enable escaping `$` in `macro_rules!` and then forbid the first example.
