### ISSUE TITLE
The `macro_rules` `path` matcher matches more than just paths

### ISSUE THREAD

**Issue by dylanede** [rust-lang/rust#39414]
The Rust grammar states that path non-terminals are defined as follows:
```text
expr_path : [ "::" ] ident [ "::" expr_path_tail ] + ;
expr_path_tail : '<' type_expr [ ',' type_expr ] + '>'
               | expr_path ;

type_path : ident [ type_path_tail ] + ;
type_path_tail : '<' type_expr [ ',' type_expr ] + '>'
               | "::" type_path ;
```

But the `path` matcher seemingly also matches things like enum variant definitions, e.g. the following macro:

```rust
macro_rules! foo {
    ($p:path) => {()};
}
```

will successfully parse when given `foo!(Baz(Option<bool>))`. This behaviour can mess up macros that rely on a failed (but recoverable) parse of a path falling through. As a work around I have been using matchers like `$($p:tt$(<$($t:ty),*>)*)::+` and `::$($p:tt$(<$($t:ty),*>)*)::+` instead.

Is this intended behaviour? It doesn't seem to be documented anywhere. It's certainly surprising.

**Comment by petrochenkov** [comment]
>`foo!(Baz(Option<bool>))`

```
foo!(Fn(Option<bool>))
```
Does this look better? :)

**Comment by petrochenkov** [comment]
`Trait(Args...) -> Ret` / `Trait(Args...)` are valid paths.

**Comment by dylanede** [comment]
Ah, of course, that sugar. Looks like the grammar needs updating.
