### ISSUE TITLE
Converting `try!()` into `?` causes a compiler error

### ISSUE THREAD

**Issue by mathstuf** [rust-lang/rust#39417]
I'm assuming this isn't meant to happen :) .

The code is FOSS, but the codebase isn't really that small and depends on un-merged code, so getting a small test case isn't readily available right now, but I'll try and get things pointed at the right git repos and upload a branch with a `Cargo.lock` tomorrow so you can test. Currently using `rustc 1.16.0-dev (463affee6 2017-01-27)` (I can try an update tomorrow); 1.14.0 doesn't like the code either.

**Comment by mathstuf** [comment]
Oh, the compiler error probably helps:

```
error[E0282]: unable to infer enough type information about `_`
   --> src/config/types.rs:608:50
    |
608 |                 let config: io::TestRefsConfig = serde_json::from_value(test_conf.config
    |                                                  ^ cannot infer type for `_`
    |
    = note: type annotations or generic parameter binding required
```

**Comment by clarcharr** [comment]
Mind showing the code too?

**Comment by mathstuf** [comment]
[This commit](https://gitlab.kitware.com/ben.boeckel/ghostflow-director/commit/1a6faaedd50e894753a788ab05c6818402e528c4) is the change which breaks. The other repos are all available under [this group](https://gitlab.kitware.com/utils) and will need `src =` changes in all of them to match how you clone them to work (the `master` branches all work together, but the tagged versions on crates.io (for those which are there) do not).

**Comment by porglezomp** [comment]
I'm pretty sure this is working as intended: `try!` only produced `Result`s, but `?` produces things that `impl Carrier`. Currently this is only `Result`, but the abstraction means that some inference fails without annotation where it succeeded with `try!`.

**Comment by mathstuf** [comment]
Ah, so the `.into()` is causing this?

**Comment by clarcharr** [comment]
That's correct.

**Comment by mathstuf** [comment]
OK, thanks.
