### ISSUE TITLE
Incorrect computation. (2 * 5 * 3) % (10 ^ 9)  is computed as 1 instead of 30.

### ISSUE THREAD

**Issue by vamsikal3** [rust-lang/rust#39421]
Here is the source code that reproduces the bug in rust 1.14.0. (for both debug and release builds).
SOURCE CODE:

fn sum_of_squares_mod_m(a : usize, m : usize) -> usize {
    let a_plus_1 = a + 1;
    let two_a_plus_1 = (2 * a) + 1;
    if (a % 2) == 0 {
        let a_1 = a / 2;
        if (a_1 % 3) == 0 {
            let a_2 = a_1 / 3;
            ((((a_2 % m)  * (a_plus_1 % m)) % m) * (two_a_plus_1 % m)) % m
        } else if (a_plus_1 % 3) == 0 {
            let a_2 = a_plus_1 / 3;
            ((((a_1 % m)  * (a_2 % m)) % m) * (two_a_plus_1 % m)) % m
        } else if (two_a_plus_1 % 3) == 0 {
            let a_2 = two_a_plus_1 / 3;
            let t = ((((a_1 % m) * (a_plus_1 % m)) % m) % (a_2 % m)) % m;
            println!("{} * {} * {} = {}", a_1, a_plus_1, a_2, t);
            ((((a_1 % m) * (a_plus_1 % m)) % m) % (a_2 % m)) % m
        } else {
            panic!("a * (a + 1) * ((2 * a) + 1) is not divisible by 6.");
        }
    } else if (a % 3) == 0 {
        let a_1 = a / 3;
        let a_2 = a_plus_1 / 2;
        ((((a_1 % m) * (a_2 % m)) % m) * (two_a_plus_1 % m)) % m
    } else {
        let a_1 = a_plus_1 / 2;
        if (a_1 % 3) == 0 {
            let a_2 = a_1 / 3;
            ((((a % m)  * (a_2 % m)) % m) * (two_a_plus_1 % m)) % m
        } else if (two_a_plus_1 % 3) == 0 {
            let a_2 = two_a_plus_1 / 3;
            ((((a % m)  * (a_1 % m)) % m) * (a_2 % m)) % m
        } else {
            panic!("a * (a + 1) * ((2 * a) + 1) is not divisible by 6.");
        }
    }
}

fn main() {
    let m = 1000000000;
    println!("sum_of_squares_mod_m({}, {}) = {}", 4, m, sum_of_squares_mod_m(4, m));
}

OUTPUT:
vamsi@vamsi-laptop:~/learn/project_euler/385_to_512/problem_401$ time ./target/release/problem_401 
2 * 5 * 3 = 1
sum_of_squares_mod_m(4, 1000000000) = 1

real    0m0.004s
user    0m0.000s
sys     0m0.000s
vamsi@vamsi-laptop:~/learn/project_euler/385_to_512/problem_401$ rustc --version
rustc 1.14.0 (e8a012324 2016-12-16)

**Comment by Guvante** [comment]
let t = ((((a_1 % m) * (a_plus_1 % m)) % m) % (a_2 % m)) % m;

You are modulousing by `a_2` here which is the source of your problem. Note that you print `2 * 5 * 3 = 1` earlier. `2 * 5 % 3 = 1` is correct.

**Comment by vamsikal3** [comment]
Thanks for looking into it. I will close this issue.
