### ISSUE TITLE
#[doc(hidden)] does not work for externally used macros

### ISSUE THREAD

**Issue by SergioBenitez** [rust-lang/rust#39436]
If a macro is imported using `use` (via the `use_extern_macros` feature), its documentation cannot be hidden. For instance, if the code is:

```rust
extern crate serde_json;

#[doc(hidden)]
pub use serde_json::json;
```

The documentation for the `json` macro will appear in the rustdocs. Of course, the expected result is that the documentation _does not_ appear.

cc @jseyfried @nrc @dtolnay

**Comment by abonander** [comment]
I'm going to tinker on this while I'm out of town over the weekend. @jseyfried bug me about this Monday evening-ish if I don't have a progress report by then.
