### ISSUE TITLE
thread::spawn with function with no return result type causes SIGSEGV

### ISSUE THREAD

**Issue by xfix** [rust-lang/rust#39432]
Messages are never printed, the program just crashes.

This only happens in release mode.

### What I did?

Ran following program in release mode.

```rust
use std::thread;

fn worker() -> ! {
    loop {
        println!("Printing messages");
    }
}

fn main() {
    thread::spawn(worker);
    loop {
        thread::park();
    }
}
```

### What was expected?

Flood of "Printing messages" messages.

### What happened instead.

SIGSEGV

## Meta

This was confirmed to happen on stable (on IRC and in playpen), however I don't have stable installed.

```
rustc 1.16.0-nightly (df8debf6d 2017-01-25)
binary: rustc
commit-hash: df8debf6d9afc431adbbd8311dcaf2b70eb9762e
commit-date: 2017-01-25
host: x86_64-unknown-linux-gnu
release: 1.16.0-nightly
LLVM version: 3.9
```

**Comment by pmarcelll** [comment]
This is probably #28728.

**Comment by nagisa** [comment]
> This is probably #28728.

It is not.

**Comment by nagisa** [comment]
More minimal:

```
fn worker() -> ! {
    panic!()
}

fn main() {
    std::panic::catch_unwind(worker);
}
```

**Comment by alexcrichton** [comment]
This is due to this causing UB:

```rust
#![feature(never_type)]

fn main() {
	unsafe {
		let a = std::mem::uninitialized::<!>();
	}
}

```

I vaguely remember there being an issue for that but I can't recall where. The precise call to this function [happens here](https://github.com/rust-lang/rust/blob/24055d0f2aa8dce5caed7544e6006aa48dceaea5/src/libstd/panicking.rs#L433).

**Comment by alexcrichton** [comment]
This is technically not a regression apparently because this was rejected in 1.11.0 and just started faulting in 1.12.0:

```rust
fn worker() -> ! {
    panic!()
}

fn main() {
    std::panic::catch_unwind(worker);
}
```

**Comment by whataloadofwhat** [comment]
Could you fix this by changing `Data<F, R>` to be a union now that they exist?
