### ISSUE TITLE
`cargo rustc -- -Zno-trans` called on `crate_type = ["cdylib"]` crates abort linker

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#39445]
The error is `/usr/bin/ld:/tmp/rustc.4i5vo9joxpv6/list:4: syntax error in VERSION script`. It doesn't happen with normal lib/bin crates and it doesn't happen without `-Zno-trans`.

**Comment by retep998** [comment]
Could this have been caused by https://github.com/rust-lang/rust/pull/38117?

**Comment by ustulation** [comment]
Hey guys, has this been confirmed/identified and do we have a fix on the way ?

**Comment by Mark-Simulacrum** [comment]
This appears to be fixed today as far as I can tell. Or, at least, I cannot reproduce.

**Comment by oli-obk** [comment]
It's not fixed yet: https://github.com/Manishearth/rust-clippy/issues/1500#issuecomment-303550726

**Comment by Mark-Simulacrum** [comment]
Hm, odd. Perhaps it's platform dependent? Or my tests weren't quite right. The latter may be more likely.

**Comment by steveklabnik** [comment]
`-Z no-trans` is effectively deprecated today, no?

**Comment by Mark-Simulacrum** [comment]
I'm not quite sure. I think it's not quite deprecated, more like "usable only on nightly." Though I personally don't know any reason to use it over --emit=metadata.

**Comment by steveklabnik** [comment]
> Though I personally don't know any reason to use it over --emit=metadata.

Yes, that's what I'm getting at.

**Comment by oli-obk** [comment]
We're using --emit=metadata now.
