### ISSUE TITLE
If guard in match 

### ISSUE THREAD

**Issue by jawline** [rust-lang/rust#39452]
When using the following code

```
match std::env::args().nth(1) {
        Some(ref x) if x == "decrypt" => {
            decrypt(&std::env::args().nth(2).unwrap(), &std::env::args().nth(3).unwrap(), &iv);
        }
}
```

I get the warning from rustc 

```
warning: unused variable: `x`, #[warn(unused_variables)] on by default
  --> src/main.rs:53:8
   |
53 | 		Some(ref x) => {warning: unused variable: `x`, #[warn(unused_variables)] on by default
  --> src/main.rs:53:8
   |
53 | 		Some(ref x) => {
```

which I would not expect, given that if x is used in the match expression. Is this a bug in the rust linter or am I incorrectly using match.

```
cargo 0.17.0-nightly (40a4ce6 2017-01-06)
rustc 1.16.0-nightly (47c8d9fdc 2017-01-08)rustc 1.16.0-nightly (47c8d9fdc 2017-01-08)
```

**Comment by est31** [comment]
No, it is a bug, but I can't reproduce it online: http://play.integer32.com/?gist=81c22eff8e31dce1625e9033a90718b8&version=nightly

Can you check whether that minimal example works for you?

**Comment by jawline** [comment]
Sorry, I think it was a mistake on my part with another case in the match. Closing the issue
