### ISSUE TITLE
Installing 1.15.0 from source fails in bootstrap.py

### ISSUE THREAD

**Issue by djc** [rust-lang/rust#39469]
While updating the Gentoo package for rust to 1.15.0, I get this error:

```python
Traceback (most recent call last):
  File "/var/tmp/portage/dev-lang/rust-1.15.0/work/rustc-1.15.0-src/src/bootstrap/bootstrap.py", line 491, in <module>
    main()
  File "/var/tmp/portage/dev-lang/rust-1.15.0/work/rustc-1.15.0-src/src/bootstrap/bootstrap.py", line 440, in main
    if os.environ['USER'] != os.environ['SUDO_USER']:
  File "/usr/lib64/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'USER'
```

This appears to have been introduced as part of 0e272de69f4a9c889e5f1a024a88b3e1f60cb6c5, the commit that switched to rustbuild by default. I don't really get what the USER != SUDO_USER heuristic is intended to protect against, but it looks a bit fishy to me. For one thing, from this failure it would seem that it has not seen testing in very diverse environments, so using `.get('USER')` and `.get('SUDO_USER')` would probably make a lot more sense here. Second, while the goal appears to be to set `enable_vendored_sources` in some situations, this code is still executed when `enable_vendored_sources` is already set. Finally, there is a typo in the help text that is printed for this case ('intall').

**Comment by durka** [comment]
Strange, Gentoo doesn't have $USER or names it something else?

**Comment by alexcrichton** [comment]
This was originally intended to detect `sudo make install` and warn you that you should do `make` first *then* `sudo make install`. There's no need for us to require these env vars, though, so a patch to use `.get` should work just fie!

**Comment by djc** [comment]
@durka I think it has it, but it's probably not available in the constrained environment set up by the package manager.

**Comment by djc** [comment]
Would it make sense to uplift this to 1.16.0? If so, how do I go about nominating it?

**Comment by alexcrichton** [comment]
@djc sure yeah, I've nominated https://github.com/rust-lang/rust/pull/39471 for a backport (tag)
