### ISSUE TITLE
Too much padding with expanded new enum-struct-fields table

### ISSUE THREAD

**Issue by nabijaczleweli** [rust-lang/rust#39464]
As illustrated in the following screenshot: ![SS](http://i.imgur.com/an9ZS2D.png)
There is too much empty space below the table.

Confirmed by @QuietMisdreavus on IRC

Rust version: 1.15 stable
UA: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0"

**Comment by Mark-Simulacrum** [comment]
I think this has been improved somewhat today, but is still non-ideal. The problem likely stems from here: https://github.com/rust-lang/rust/blob/5dfcd85fd4bae49445383baadf472fbdb414a0e6/src/librustdoc/html/static/rustdoc.css#L356.

![image](https://cloud.githubusercontent.com/assets/5047365/26275917/12619d4a-3d29-11e7-85d7-1327d25c9e02.png)

**Comment by camelid** [comment]
The layout has significantly changed over the last several years, and I think this issue is fixed now.
