### ISSUE TITLE
asmjs & -Z incremental: Option<Result<Option<()>, ()>> causes wrong results (and crashes llc)

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#39461]
The following code produces the wrong result (`Some(Ok(None))` instead of `Some(Ok(Some(())))`) and also crashes llc after linking. It does produce executable asm.js.
Tested for opt-level: s, z, 0, 1, 2. opt-level 3 is not affected.

```rust
// works
type GoodPoll = Result<Option<()>, ()>;
// does not work
type BadPoll = Option<GoodPoll>;

fn bad(f: Box<Fn() -> BadPoll>) {
    println!("bad: boxed f -> {:?}", f());
}
fn good(f: Box<Fn() -> GoodPoll>) {
    println!("good: boxed f -> {:?}", f());
}
pub fn main() {
    good(Box::new(|| Ok(Some(()))));
    bad(Box::new(|| Some(Ok(Some(())))));
}
```

rustc 1.16.0-nightly (df8debf6d 2017-01-25)

**Comment by asyncfn** [comment]
Hi,

I checked this issue. Right now I'm getting

```sh
    Finished release [optimized] target(s) in 0.00s
     Running `target/release/test_39461`
good: boxed f -> Ok(Some(()))
bad: boxed f -> Some(Ok(Some(())))
```
for cargo run --release

and

```sh
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/test_39461`
good: boxed f -> Ok(Some(()))
bad: boxed f -> Some(Ok(Some(())))
```
for cargo run

IMO problem is fixed.

@oli-obk Can I ping you on issues that can be closed? Or can you tell me who from compiler team handles outdated issues?

Best regards,
Michal

**Comment by oli-obk** [comment]
Yea I don't know how to reproduce this. Even though it mentions asm.js, there's a lot to producing that 😆 . I assume that it is indeed fixed, or we'd have gotten more reports

**Comment by asyncfn** [comment]
@oli-obk For the record I tested the scenario with sample code, not with asm.js

**Comment by oli-obk** [comment]
Oh yea, I got that, I just don't even know how to reproduce this with the information given.
