### ISSUE TITLE
Wrong `unreachable_code` in nightly/stable-2017-01-31

### ISSUE THREAD

**Issue by badboy** [rust-lang/rust#39460]
Current nightly reports [this piece of code in redis-rs](https://github.com/mitsuhiko/redis-rs/blob/master/src/parser.rs#L109) as unreachable.

Code (relevant part):
```rust
…
        while i < bytes {
            let res_nread = {
                let ref mut buf = &mut rv[i..];
                self.reader.read(buf)
            };
            match res_nread {
                Ok(nread) if nread > 0 => i += nread,
                Ok(_) => return fail!((ErrorKind::ResponseError, "Could not read enough bytes")),
                Err(e) => return Err(From::from(e)),
            }
        }
…
```

Travis Logs:
https://travis-ci.org/mitsuhiko/redis-rs/jobs/187464076#L229

Error message:
```
warning: unreachable expression, #[warn(unreachable_code)] on by default
   --> src/parser.rs:112:21
    |
112 |                     return fail!((ErrorKind::ResponseError, "Could not read enough bytes")),
    |   
```

Removing that `Ok(_)` line correctly reports `error[E0004]: non-exhaustive patterns: `Ok(_)` not covered`

Neither current stable (1.14) nor beta (1.15.0-beta.5) report this. Next stable (stable-2017-01-31, `rustc 1.15.0 (10893a9a3 2017-01-19)` however does.
I couldn't (yet) produce a more minimal example.

**Comment by rkruppe** [comment]
`fail!(expr)` is defined as `return Err(::std::convert::From::from($expr));`, so the return outside the macro invocation is redundant. Presumably that's what the lint complains about.

**Comment by badboy** [comment]
Oh damn. That explains why I couldn't reproduce it. Then it is an improvement in new versions after all. Sorry for the noise.
