### ISSUE TITLE
`std::vec::IntoIter::as_mut_slice` borrows `&self`, returns `&mut` of contents.

### ISSUE THREAD

**Issue by christophebiocca** [rust-lang/rust#39465]
`/u/dbaupp` on reddit points out that [this method](https://github.com/rust-lang/rust/blob/master/src/libcollections/vec.rs#L1961) can be called multiple times and result in getting multiple `&mut [T]` of the exact same data.

**Comment by brson** [comment]
Awesome!

**Comment by brson** [comment]
I suggest we change it to &mut and run it through crater to see the impact. We can change it or immediately deprecate it. We can make a point release or wait until 1.16.
