### ISSUE TITLE
alloc_system is linked even if a custom allocator is present

### ISSUE THREAD

**Issue by liuzix** [rust-lang/rust#39475]
rustc 1.16.0-nightly (24055d0f2 2017-01-31)
binary: rustc
commit-hash: 24055d0f2aa8dce5caed7544e6006aa48dceaea5
commit-date: 2017-01-31
host: x86_64-apple-darwin
release: 1.16.0-nightly
LLVM version: 3.9

I am writing an experimental OS in rust and of course it includes a custom allocator, so I added `#![allocator]` and implemented the allocating prototypes **__rust_allocate**, etc.
However when I build it, the linker tries to link alloc_system, which results in undefined symbol "**malloc**", because alloc_system tries to use the libc allocator. 
I temporarily made the program work by manually implementing the libc malloc prototype, but this doesn't seem like an elegant solution.
Please see if this is a bug in the linking system.

**Comment by FenrirWolf** [comment]
Does your allocator crate have the `#![allocator]` attribute set?

**Comment by liuzix** [comment]
Yes. I have `#![allocator]` set. (I have edited the problem to indicate that) @FenrirWolf

**Comment by alexcrichton** [comment]
@liuzix as described it sounds like this is a bug, but beyond that it's unclear where the bug is. Could you provide samples of code and/or reproductions to help narrow it down?

**Comment by Mark-Simulacrum** [comment]
I'm going to close due to inactivity, but please let us know if you're able to give us some steps to reproduce and we'll reopen!
