### ISSUE TITLE
no_std does not impl sqrt for f32 and f64

### ISSUE THREAD

**Issue by CasualX** [rust-lang/rust#39473]
I tried the following code (compiled as a library):

	#![no_std]
	pub trait Float {
	    fn sqrt(self) -> Self;
	}
	impl Float for f32 {
	    fn sqrt(self) -> Self { self.sqrt() }
	}
	impl Float for f64 {
	    fn sqrt(self) -> Self { self.sqrt() }
	}

I expected to see this happen: The above code working and calling the correct `sqrt` function.

The core docs for the [f32 primitive type](https://doc.rust-lang.org/stable/core/primitive.f32.html) 404s and unlike the [integer types](https://doc.rust-lang.org/stable/core/i32/index.html) does not contain a link to [f32's primitive type](https://doc.rust-lang.org/stable/core/f32/index.html) info page.

Instead this happened:

	warning: function cannot return without recurring, #[warn(unconditional_recursion)] on by default
	  --> src\unit.rs:58:2
	   |
	58 |    fn sqrt(self) -> f32 { self.sqrt() }
	   |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	   |
	note: recursive call site
	  --> src\unit.rs:58:25
	   |
	58 |    fn sqrt(self) -> f32 { self.sqrt() }
	   |                           ^^^^^^^^^^^
	   = help: a `loop` may express intention better if this is on purpose

	warning: function cannot return without recurring, #[warn(unconditional_recursion)] on by default
	  --> src\unit.rs:61:2
	   |
	61 |    fn sqrt(self) -> f64 { self.sqrt() }
	   |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	   |
	note: recursive call site
	  --> src\unit.rs:61:25
	   |
	61 |    fn sqrt(self) -> f64 { self.sqrt() }
	   |                           ^^^^^^^^^^^
	   = help: a `loop` may express intention better if this is on purpose

Is this intended?

## Meta

`rustc --version --verbose`:

	rustc 1.14.0 (e8a012324 2016-12-16)
	binary: rustc
	commit-hash: e8a0123241f0d397d39cd18fcc4e5e7edde22730
	commit-date: 2016-12-16
	host: x86_64-pc-windows-msvc
	release: 1.14.0
	LLVM version: 3.9

**Comment by nagisa** [comment]
Yes this is intended I think. `sqrt()` depends on libraries in platform in some cases and the whole point of `core` is to not depend on those.

**Comment by durka** [comment]
@nagisa the implementation of `f32::sqrt` and `f64::sqrt` in std seem to just call intrinsics.

**Comment by FenrirWolf** [comment]
From what I understand, many of those intrinsics get lowered to functions whose definitions usually live in `libm`.

**Comment by nagisa** [comment]
What @FenrirWolf said is correct.

**Comment by CasualX** [comment]
That's unfortunate but understandable.

**Comment by durka** [comment]
Maybe we could increase granularity by moving that kind of stuff to a
libmath crate that pulls in libm?

**Comment by FenrirWolf** [comment]
Better yet would be implementations of those functions in Rust, similar to the `compiler-builtins` crate for `compiler-rt` intrinsics. There is a work-in-progress [port](https://github.com/japaric/m) of openlibm with this goal in mind.

**Comment by anatol** [comment]
@FenrirWolf big plus from me. math functions like those defined in `libm` can be fully implemented in Rust. There is no strong reason to link to `libm` C library.

**Comment by nagisa** [comment]
There’s also no strong reason to include these in no_std builds -- you can link to software impls yourselves just fine by depending on a crate like [math.rs](https://github.com/nagisa/math.rs) or the already mentioned [m](https://github.com/japaric/m).

**Comment by anatol** [comment]
@nagisa thanks for the pointer to your math.rs crate. It looks like it is the most complete `math` functions implementation in Rust.

For me it would make a lot of sense to replace existing Rust `libm`-based implementation with yours from `math.rs`. Having math library implemented fully in Rust is a great step towards `C`-free libstd.

**Comment by Mark-Simulacrum** [comment]
I propose that we close this issue since this is something that is intentional for now; should we ever move to Rust implementations of math functions, most likely all functions on f32/f64 should be reevaluated for inclusion in core. cc @rust-lang/libs

**Comment by CasualX** [comment]
I completely forgot about this issue! I agree with Mark, the subject seems settled that for now this is expected behaviour due to how core works.

**Comment by jhpratt** [comment]
Any updates on this? Documentation at a minimum would be great, since it's a very odd issue to run into given the present error message.

Some of the functions, like `.abs()`, `.signum()`, etc. seem relatively trivial to rewrite in Rust. Is this something that is desired? I'd be up for a PR if so.

@Mark-Simulacrum?

**Comment by Mark-Simulacrum** [comment]
This is pretty hard -- I don't have a link handy, but there are a bunch of considerations that need to go into doing this correctly. I believe some folks are working on it though... I recall a PR or two flying by in the past couple weeks.

**Comment by lvella** [comment]
The current open issue for this is #50145.
