### ISSUE TITLE
Rust 1.15 source tarball does not contain x.py

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#39476]
The build system that we just turned on is not actually in the source code.

cc @alexcrichton

**Comment by brson** [comment]
This is on beta and nightly too.

**Comment by brson** [comment]
Reeopening until the backport is fixed because I'm putting this on the release milestone.

**Comment by alexcrichton** [comment]
Backported in https://github.com/rust-lang/rust/pull/39734 as https://github.com/rust-lang/rust/commit/c588de34ac46e885d68e16413456819bfa69ab50
