### ISSUE TITLE
Miss optimization for loop with integer less than 64bits?

### ISSUE THREAD

**Issue by ludwigpacifici** [rust-lang/rust#39483]
Consider this Rust snippet:

```
fn main() {
    let mut sum: u64 = 0;

    for i in 0..300 {
        sum += i;
    }

    println!("{}", sum) // expect: 44850
}
```

`rustc -O test.rs --emit=asm` will compute the loop at compile time. It can be checked in the asm code: `movq	$44850, (%rsp)`.

If I replace the type of the `sum` variable by an unsigned 32 bits integer: `let mut sum: u32 = 0;`, the `for` loop is not compile time computed, but it is vectorized.

```
.Ltmp0:
	.cfi_def_cfa_offset 80
	movl	$0, 4(%rsp)
	movdqa	.LCPI0_0(%rip), %xmm1
	pxor	%xmm0, %xmm0
	movl	$320, %eax
	movdqa	.LCPI0_1(%rip), %xmm2
	movdqa	.LCPI0_2(%rip), %xmm4
	movdqa	.LCPI0_3(%rip), %xmm5
	movdqa	.LCPI0_4(%rip), %xmm6
	pxor	%xmm3, %xmm3
	jmp	.LBB0_1
	.p2align	4, 0x90
.LBB0_3:
	paddd	%xmm1, %xmm0
	paddd	%xmm1, %xmm0
	paddd	%xmm1, %xmm0
	paddd	%xmm1, %xmm3
	paddd	%xmm1, %xmm3
	paddd	%xmm1, %xmm3
	paddd	%xmm4, %xmm1
	paddd	%xmm5, %xmm0
	paddd	%xmm6, %xmm3
.LBB0_1:
	paddd	%xmm1, %xmm0
	paddd	%xmm1, %xmm3
	paddd	%xmm2, %xmm3
	addl	$-32, %eax
	jne	.LBB0_3
	paddd	%xmm0, %xmm3
	pshufd	$78, %xmm3, %xmm0
	paddd	%xmm3, %xmm0
	pshufd	$229, %xmm0, %xmm1
	paddd	%xmm0, %xmm1
	movd	%xmm1, %eax
	addl	$1190, %eax
	movl	%eax, 4(%rsp)
	leaq	4(%rsp), %rax
```

I expected the `for` loop to be computed in both cases, knowing the result fits in 32 bits. Equivalent issue is there for unsigned 16 bits. 

Is it possible to make this compile time computation optimization available for whatever type?

## Meta

```
rustc 1.15.0 (10893a9a3 2017-01-19)
binary: rustc
commit-hash: 10893a9a349cdd423f2490a6984acb5b3b7c8046
commit-date: 2017-01-19
host: x86_64-unknown-linux-gnu
release: 1.15.0
LLVM version: 3.9
```

**Comment by ludwigpacifici** [comment]
Hello rust-lang/rust,

Do you have any news? Do you need more information about the issue, or should it be reported to another project?

**Comment by nikic** [comment]
Just tried this with current stable (1.30.1) for `u64`, `u32` and `u16`. The result was compile-time computed in all cases. LLVM must have become better at recognizing this pattern at some point in the meantime :)
