### ISSUE TITLE
`str::trim_left` and `str::trim_right` method names are misleading

### ISSUE THREAD

**Issue by jimblandy** [rust-lang/rust#39499]
If you're processing text in a language written from right to left, these methods do the opposite of what they claim. They really refer to the start and end of the slice.

It might be good to have `trim_start` and `trim_end` aliases (with `_matches` variants as well) to help people write clearer code in applications that typically process right-to-left text.

The rest of the API is pretty good about avoiding this mistake; the only other exception I noticed was the `std::fmt` alignment flags.

**Comment by KalitaAlexey** [comment]
@jimblandy,
Hi.
I disagree that it is misleading because any slice has the left side (its start) and the right side (its end).
str is a string. It has no direction.

**Comment by pthariensflame** [comment]
@KalitaAlexey

> str is a string. It has no direction.

For that very reason, I agree with @jimblandy’s assessment.  Since `str` has no inherent direction, we shouldn’t use direction-specific words for its API.

**Comment by KalitaAlexey** [comment]
@jimblandy, @pthariensflame,
Okay. Another problem is that renaming these functions is breaking change.
At maximum a comment may be added.

**Comment by pthariensflame** [comment]
Well, if the core team felt strongly enough, they could deprecate these names and introduce aliases with better names; [they‘ve done exactly that before already](https://doc.rust-lang.org/std/slice/trait.SliceConcatExt.html#tymethod.connect).

**Comment by jimblandy** [comment]
I should be clear that I have no experience with right-to-left scripts beyond what I've read of the Unicode specification, and what I've picked up from working on Firefox.

> I disagree that it is misleading because any slice has the left side (its start) and the right side (its end).

The Unicode standard specifies that Unicode text is always stored in "logical order", meaning the order in which the text would be read. (Unicode Standard version 9, section 2.2, subheading "Logical order".) So the Rust string `"ערב טוב"` (Hebrew for "good evening") actually stores the rightmost character `'ע'` first:
```
assert_eq!("ערב טוב".chars().next(), Some('ע'));
```
The full details are complicated, but roughly, whitespace characters inherit the direction of the characters around them that have a strong implicit direction. This means that `str::trim_left` would actually remove whitespace characters that display to the right of that phrase (assuming it's displayed in isolation). That's what I think is confusing. If the function were named `trim_start`, it would be clear which characters were to be removed regardless of the directionality of the slice's contents.

> they could deprecate these names and introduce aliases with better names

Yeah, that's the solution that makes sense to me.

**Comment by alexcrichton** [comment]
I think this may be a dupe of https://github.com/rust-lang/rust/issues/30459?

**Comment by jimblandy** [comment]
Yes, it is. Thanks!
