### ISSUE TITLE
Specifying associated type requires redundant constraints

### ISSUE THREAD

**Issue by sgrif** [rust-lang/rust#39532]
[Reproduction script](https://is.gd/c5tzso)

Expected behavior: The file compiles successfully
Actual behavior: The function `x` requires an additional `<T as Foo>::Baz: Bar<U>`. This check is entirely redundant with the trait definition, and would always have to be true for `T: Foo<Bar=U>` to hold.

This only occurs if the constraint referencing the first associated type is a parameter to the trait, not an associated type, which is why this doesn't happen for `IntoIterator`. This appears to have been an unintended side effect of [RFC 1214](https://github.com/rust-lang/rfcs/blob/master/text/1214-projections-lifetimes-and-wf.md)

**Comment by rkarp** [comment]
It looks like there are other issues with the same cause, see #40093 and #43475.

**Comment by estebank** [comment]
Current output:

```
error[E0277]: the trait bound `<T as Foo>::Baz: Bar<U>` is not satisfied
  --> src/main.rs:9:1
   |
1  |   trait Foo {
   |   --------- required by `Foo`
...
9  |   fn x<T: Foo<Bar=U>, U>(t: &T) {
   |   ^                            - help: consider further restricting the associated type: `where <T as Foo>::Baz: Bar<U>`
   |  _|
   | |
10 | | }
   | |_^ the trait `Bar<U>` is not implemented for `<T as Foo>::Baz`
```

**Comment by estebank** [comment]
This now compiles.
