### ISSUE TITLE
Add sparc64-linux-gnu as a cross-compile target

### ISSUE THREAD

**Issue by sunnystormy** [rust-lang/rust#39547]
I'm currently developing a chip using an open-source hardware framework, and would like to run Rust code on it without having to recompile Rust source on the target machine (partly due to the frequency of the FPGA being significantly less than the host machine). Is there some way we can get sparc64 integrated somehow? Thank you!

**Comment by steveklabnik** [comment]
@sunnystormy we don't really track possible architectures in the bug tracker. A post on http://internals.rust-lang.org/ might be a bit better; we're always interested in adding more architectures, but it takes some work to do, and that's a better place to get help with it 😄 Thanks!

**Comment by sunnystormy** [comment]
@steveklabnik Not a problem. Thanks for your help! :)

**Comment by jmesmon** [comment]
@sunnystormy  #39647 is related and may resolve your issue
