### ISSUE TITLE
"file not found for module" compile error doesn't have an error number

### ISSUE THREAD

**Issue by frgtn** [rust-lang/rust#39542]
"file not found for module" compile error does not have an [error number/code](https://doc.rust-lang.org/error-index.html), thus it cannot be easily identified/handled by external tools.

My use case is with Vim w0rp/ale plugin which does code checking as you type. It uses rustc to do "as-you-type" error checking and cargo check when a file is saved (see [ale-integration-rust](https://github.com/w0rp/ale/blob/a1458e9c072e1cfc425591b7616a291e99778753/doc/ale.txt#L897)). Since imports cannot be resolved with "as-you-type" checking it would make sense to ignore such errors and only show them if they're detected by cargo. But since "file not found for module" doesn't have an error code I can't ignore it.

Example code `src/main.rs`:
```
mod doesnotexist;

fn main() {
    println!("Hello world");
}

```
When compiling I expect to get an error with an error number, something like `error[E0123]: ...` but no error number is provided:
```
$ rustc src/main.rs
error: file not found for module `doesnotexist`
 --> src/main.rs:1:5
  |
1 | mod doesnotexist;
  |     ^^^^^^^^^^^^
  |
  = help: name the file either doesnotexist.rs or doesnotexist/mod.rs inside the directory "src"
```

```
$ rustc --verbose --version
rustc 1.15.0 (10893a9a3 2017-01-19)
binary: rustc
commit-hash: 10893a9a349cdd423f2490a6984acb5b3b7c8046
commit-date: 2017-01-19
host: x86_64-apple-darwin
release: 1.15.0
LLVM version: 3.9
```

**Comment by jseyfried** [comment]
@frgtn There are many errors right now that don't have error codes -- I'm not sure it would be feasible or desirable to give every error we emit today an error code.

**Comment by frgtn** [comment]
@jseyfried good point, thanks for your response. Is there some formal process that error messages are assigned codes or is it historically so that first errors have codes and the ones added later do not?

This is a very minor issue and more of a nice-to-have for language integration into IDEs and editor plugins. I think it would be good if more common errors would eventually get assigned some sort of error codes (or the messages get standardised somehow) so that tools can identify them.

**Comment by jseyfried** [comment]
@frgtn 
> Is there some formal process that error messages are assigned codes or is it historically so that first errors have codes and the ones added later do not?

I'm not aware of a formal process, it usually depends on whether the author thought it was worth it to add an error code.

> I think it would be good if more common errors would eventually get assigned some sort of error codes (or the messages get standardised somehow) so that tools can identify them.

Error codes are subject to change though, so checking the error code isn't much more stable than e.g. checking if `"file not found for module"` is a prefix the error text.

Also, I'm not sure why you are expecting `"file not found for module"` when doing "as-you-type" checking. These error happen very early in the compilation process and causes `rustc` to abort before anything interesting happens. Also, import resolution errors have the potential to cause all sorts of problems later on in type checking, etc.

Why can't imports cannot be resolved with "as-you-type" checking?

**Comment by petrochenkov** [comment]
cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
I'm going to give it a try.
