### ISSUE TITLE
Nightly rustc 1.17.0-nightly (ea7a6486a 2017-02-04) crashes

### ISSUE THREAD

**Issue by vorner** [rust-lang/rust#39569]
Today, nightly crashed on me when compiling my code: https://travis-ci.org/vorner/tokio-jsonrpc/jobs/198610271. I don't know what part of the code (https://github.com/vorner/tokio-jsonrpc/commit/3872c1f731806420f4ca732f1c0a1817e72b112c) is causing this and I don't know how to search for it.

Compilation locally works correctly, with yesterday's or today's nightly. I'm trying that `CARGO_INCREMENTAL=1` new feature.

I managed to get this version info from travis in another job:

```
rustc 1.17.0-nightly (ea7a6486a 2017-02-04)
binary: rustc
commit-hash: ea7a6486a26af085862cd7a5596bb69e83d85e12
commit-date: 2017-02-04
host: x86_64-unknown-linux-gnu
release: 1.17.0-nightly
LLVM version: 3.9
```

I guess that travis log contains all the relevant information, but if not, please tell me what you need to know.

**Comment by est31** [comment]
@vorner most likely the cause is `CARGO_INCREMENTAL`. Can you remove the target directory and rebuild without it?

**Comment by vorner** [comment]
That seems to have helped… I added `cargo clean` to the job specification and now it passes. I didn't know travis keeps the directories intact between builds.

The new log is https://travis-ci.org/vorner/tokio-jsonrpc/jobs/198619831. But I guess that makes it even harder to find out what is wrong.

**Comment by michaelwoerister** [comment]
Thanks for the bug report. This seems to be a problem with our new dependency graph reduction algorithm introduced in https://github.com/rust-lang/rust/pull/39424.

**Comment by nikomatsakis** [comment]
@vorner I believe this was fixed -- can you verify?

**Comment by vorner** [comment]
I couldn't reproduce it reliably, it only crashed from time to time, so I have no way to explicitly verify it's fixed. But I haven't seen it crash for quite some time now, so I'd say it's probably solved.

**Comment by nikomatsakis** [comment]
OK, thanks! :)
