### ISSUE TITLE
Add rust-stable-* to the distribution archives

### ISSUE THREAD

**Issue by Susurrus** [rust-lang/rust#39571]
I'm setting up a CI server and I'd like to run a minimum rust version, stable, and nightly on my code. It's easily to download the specific rust version and nightly from the rust archives, but there's no `rust-stable-*` archives that always point to the current stable. There is `rust-beta-*`, so this seems like an oversight to me rather than an intentional decision. Would it be possible to add `rust-stable-*` to the distribution archives?

**Comment by alexcrichton** [comment]
This was an intentional decision, there's `channel-rust-stable.toml` which describes the current state of the stable channel.

**Comment by Susurrus** [comment]
I don't know of a standard linux command that can parse a .toml file, and since the only thing that needs to be known is the rust semver that is currently stable, I went about it like this:
```
export RUST_STABLE_VERSION=`curl https://static.rust-lang.org/dist/channel-rust-stable | head -n 1 | cut -d"-" -f2`
export RUST_ARCHIVE=rust-$RUST_STABLE_VERSION-x86_64-unknown-linux-gnu.tar.gz
export RUST_DOWNLOAD_URL=https://static.rust-lang.org/dist/$RUST_ARCHIVE
```

So now `RUST_DOWNLOAD_URL` has the appropriate rust archive. This is far simpler than finding a .toml parser and trying to extract the appropriate value out of that.

It'd be far more convenient if there was a text file that just had the version number in it that could be grabbed. Is it done the way it is to account for different targets having different stable releases at a given time?

**Comment by alexcrichton** [comment]
We chose TOML very specifically originally to cater to the needs of the primary consumer of this metadata, rustup. The format was far more complicated than we could concoct for a text file, so we chose TOML. Adding side metadata would be possible, however.

**Comment by Susurrus** [comment]
Is one of the reasons it's complex because Rust stable versions aren't guaranteed to be the same? If they are, then what about adding a `channel-rust-stable-version.txt` file. This would contain only the semver of the current Rust version (and we'd of course add a `*.asc`, `*.sha256`, and `*.sha256.asc` files as well). This also complements the `channel-rust-stable-date.txt` file that is already generated.

I was going to look up how hard this would be to configure, but it looks like the release process is controlled by the buildbots and I don't see that code on Github. If you could point me to the relevant code I'd be happy to submit a PR.

**Comment by est31** [comment]
There is also https://static.rust-lang.org/dist/channel-rust-stable which should be easy to handle with grep and friends

**Comment by alexcrichton** [comment]
Yes extensions are possible, but @brson should weigh in as well

**Comment by Mark-Simulacrum** [comment]
I think this is effectively done with the channel-rust-stable file that @est31 mentions; that provides the specific archives which can be downloaded if needed; and only needs grep to be parseable. As such, I'm going to close, but please reopen if I'm wrong.
