### ISSUE TITLE
Derive struct with raw pointer

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/rust#39570]
https://play.rust-lang.org/?gist=cb119b5471f3c484d249d7d67b643671&version=stable&backtrace=1

`*mut T` implementation of `Clone` doesn't require `T: Clone`, but the compiler seems to treat it like `&mut T`. Same thing for Debug, Copy...

**Comment by tbu-** [comment]
Seems to be #26925.

**Comment by Yamakaky** [comment]
Thanks
