### ISSUE TITLE
The links on the book page are broken

### ISSUE THREAD

**Issue by JewsOfHazard** [rust-lang/rust#39577]
On this page: https://github.com/rust-lang/rust/tree/master/src/doc/book

These ones:

![](http://i.imgur.com/aeN6VzZ.png)

**Comment by steveklabnik** [comment]
Thanks for the report! These are only broken if you view them on GitHub, which is not where they're intended to be viewed. If you visit the page at https://doc.rust-lang.org/stable/book/, where these docs are rendered, the links do work.

There's no way to make them work for both, so unfortunately, this isn't going to be fixed. Thanks again!
