### ISSUE TITLE
"rustup doc" fails silently when docs are not installed

### ISSUE THREAD

**Issue by rspeer** [rust-lang/rust#39606]
I installed Rust on macOS 10.10 using rustup, and tried running `rustup doc` to get to the local documentation, as some recently-written instructions told me to. Nothing happened.

I Googled and found that I needed to first run `rustup component add rust-docs`. After that, `rustup doc` did what was expected, opening the local documentation in Chrome.

It would be nice if `rustup doc` could say in a message that the docs need to be installed with `rustup component add rust-docs`, instead of just saying nothing.

**Comment by sfackler** [comment]
This should probably be filed on https://github.com/rust-lang-nursery/rustup.rs

**Comment by steveklabnik** [comment]
Yes, please file over there @rspeer thanks!

**Comment by rspeer** [comment]
Thanks for the pointer, will do.
