### ISSUE TITLE
Expected type panic in parsing array type

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#39616]
fn foo(a: [0; 1]) {}
    fn main() {}

nightly-x86_64-pc-windows-gnu, rustc 1.17.0-nightly (ea7a6486a 2017-02-04)

    error: expected type, found `0`
     --> test.rs:1:12
      |
    1 | fn foo(a: [0; 1]) {}
      |            ^

    error: internal compiler error: unexpected panic
    note: the compiler unexpectedly panicked. this is a bug.

    thread 'rustc' panicked at 'internal error: entered unreachable code', C:\bot\slave\nightly-dist-rustc-win-gnu-64\build\src\libsyntax\parse\parser.rs:2649

**Comment by petrochenkov** [comment]
Stable -> beta regression.

**Comment by estebank** [comment]
[Seems like it was introduced](https://github.com/rust-lang/rust/commit/debcbf0b8#diff-da9d34ca1d0f6beee2838cf02e07345cR2719) in #39118.

Cc @jseyfried

**Comment by jseyfried** [comment]
Fixed in #39674.
