### ISSUE TITLE
Nested type parameter should not count as unconstrained

### ISSUE THREAD

**Issue by J-F-Liu** [rust-lang/rust#39614]
```rust
trait Foo<T> {
    fn method() -> T;
}

struct Bar<T>(T);

impl<A, B: Foo<A>> Bar<B> {

}
```
```
7 | impl<A, B: Foo<A>> Bar<B> {
  |      ^ unconstrained type parameter
```
When we have a value `Bar(foo)`, both A and B is known, so should not consider A is an unconstrained type parameter.

**Comment by sinkuu** [comment]
A type can have multiple impls of a parameterized trait simultaneously (`impl Foo<X> for T` and `impl Foo<Y> for T` where X!=Y, etc), hence you need to constrain `A` somehow.

If you want only one `Foo` impl to exist for a type, use associated type.

```rust
trait Foo {
    type Out;
    fn method() -> Self::Out;
}

struct Bar<T>(T)

impl<A, B: Foo<Out = A>> Bar<B> {
}
```

**Comment by J-F-Liu** [comment]
Change `trait Foo<T> {}` to `trait Foo {type Out;}` is a big change affecting lots of code and publish API.
1. What's the semantic difference between `impl<A, B: Foo<A>>` and `impl<A, B: Foo<Out = A>>`?
2. If whether A is X or Y is irrelevant in the code, can we relax the constrain checking?
3. It might be better to provide a new syntax  `impl<Foo<_>>` if nested type parameter is irrelevant.
