### ISSUE TITLE
Vec::as_ptr for empty vectors is undocumented

### ISSUE THREAD

**Issue by nbaksalyar** [rust-lang/rust#39625]
`Vec::as_ptr` returns a pointer to address `0x1` for empty vectors. As it seems, this is an internal implementation detail for [`RawVec`](https://github.com/rust-lang/rust/blob/master/src/liballoc/raw_vec.rs#L93) and [allocation](https://github.com/rust-lang/rust/blob/master/src/liballoc/heap.rs#L123-L127).

This behavior is unexpected and [not documented](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.as_ptr). In certain scenarios it might cause a segmentation fault (e.g. due to failed checks for a null pointer when dealing with FFI).

**Comment by steveklabnik** [comment]
Yes, we should document this for sure.

**Comment by Stebalien** [comment]
> due to failed checks for a null pointer when dealing with FFI

FYI, this is precisely why rust uses uses 0x1 for zero-sized things instead of 0x0 (null); it does this to distinguish between "nothing" and "something empty/zero sized".

**Comment by frewsxcv** [comment]
Would it be accurate to say that it returning `0x1` is an implementation detail?

**Comment by steveklabnik** [comment]
Yes, I would say something like "the pointer value of an empty vector is meaningless", but uh, worded better. Not after midnight 😉

**Comment by Stebalien** [comment]
Not exactly. It *can't* be 0 (null pointer optimization) and setting it to 1 ensures that most accidental dereferences will result in a segfault (most operating systems avoid mapping memory into the first few pages of address space).

**Comment by Cobrand** [comment]
This not only happen for Vec, but for other things of 0 size allocated on the heap as well, (namely Box<()>). While you might say it's pointless to do Box::new(()), it can still happen and it should be documented.

I suspect it works the same way for Rc<()> and other things like that, so a chapter in the nomicon would be great I think. At the very least, say something in Box::into_raw_ptr() about 0 size structs, and add a link from Vec::as_ptr() to this part.

**Comment by frewsxcv** [comment]
Opened a pull request here: https://github.com/rust-lang/rust/pull/39757.

In the pull request, I used the term 'meaningless' @steveklabnik mentioned above. I don't think it's a great term, but I can't think of anything better right now.

**Comment by nagisa** [comment]
There are multiple aspects to this issue:

1. You are not supposed to dereference pointer of 0-capacity vector anyway. It makes no difference whether the pointer is `0`, `1` or `0xFRESHVEGGIES`.
2. 0-sized pointer dereference (including pointer returned by `Vec<ZeroSized>::as_ptr`) is no-op and dereferencing `0`, `1` or `0xFRESHVEGGIES` are all equally valid (i.e. no-op) in current implementation, although not specified.
3. These pointers are not meaningless. You need to pass the same pointers back into `from_raw` and friends to insure the correct behaviour of structures afterwards.

In that sense the only real change that’s possible in documentation is

> This function may return non-null non-dereferenceable pointers.

**Comment by steveklabnik** [comment]
docs team triage: p-medium, still need to sort out the exact details, thanks for the above comment @nagisa

**Comment by steveklabnik** [comment]
I am going to send in a PR for this based on @nagisa 's wording.

**Comment by steveklabnik** [comment]
I have completely turned 180 on this. There are too many pitfalls, as @nagisa says. I don't think that sentence really adds enough to actually understand what's going on here. Sadly, I think this is the best we can do. Giving this a close now.
