### ISSUE TITLE
Hundreds of ignore'd tests are bitrotting in the test suite

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#3965]
`git grep -l xfail -- src/test/ | wc -l` shows 235 xfail'd tests. Some of these are using ancient language features; e.g. https://github.com/mozilla/rust/blob/master/src/test/run-fail/too-much-recursion-unwinding.rs is still making use of classes. Surely some of these tests can be updated and made to work with the current compiler.

**Comment by tamird** [comment]
```
$ git grep -l '//\s*ignore' -- src/test | wc -l
321
```

**Comment by tshepang** [comment]
git grep -l '//\s*ignore' -- src/test | wc -l

now outputs

    301

**Comment by klutzy** [comment]
cc #13745

**Comment by steveklabnik** [comment]
Looking at my previous attempts to tackle this issue, I now realize that my regular expression may have been a bit too lose: we have `ignore-test`, `ignore-pretty`, and such. It seems to me that this ticket is _mostly_ about `ignore-test`.

In that case,

    $ git grep -l '//\s*ignore-test' -- src/test head | wc -l
    57

Still a ways to go, but much shorter :)

**Comment by steveklabnik** [comment]
@bstrie now that https://github.com/rust-lang/rust/pull/26253 has landed, does that address your original ticket? we're never going to get to zero of these issues, but it seems to me the more specific ignores aren't nearly as bad as the straight-up ignored ones.

**Comment by tamird** [comment]
@steveklabnik I think this issue is asking for a systematic way to keep these tests from rotting. In the [rspec terminology](http://www.relishapp.com/rspec/rspec-core/v/3-3/docs/pending-and-skipped-examples) these tests are currently skipped, while they should be pending.

**Comment by tshepang** [comment]
git grep -l '//\s*ignore-test' -- src/test | wc -l

now outputs

    301

**Comment by BigBoneDaddy** [comment]
@tshepang Thank to your hard work we getting near the end!

**Comment by bstrie** [comment]
@tamird I'm actually fine closing this now. Not only have we excised the rotten cases from the test suite, but Rust is no longer breaking and so tests have no good reason to be ignored in the future. As @tshepang notes we still have a handful left, but this number is entirely manageable.
