### ISSUE TITLE
BTreeMap documentation improvement

### ISSUE THREAD

**Issue by Henning-K** [rust-lang/rust#39661]
On the page https://doc.rust-lang.org/std/collections/index.html there is a comparison of the collection types in the standard library and it says under "Use a BTreeMap when:" "You want a sorted map.".

It was not immediately clear to me that the map's Key/Value pairs are in fact sorted by its keys. This was only fully clarified by asking the helpful folks over on IRC.

Steve Klabnik then encouraged me to open an issue here asking for a change in the docs clarifying the point made above.

This point in the list/comparison should probably say something more like
"You want a map sorted by its keys."
to avoid any unnecessary ambiguity.

**Comment by steveklabnik** [comment]
I agree wholeheartedly, thanks for filing! I'm willing to help mentor anyone who wants to fix this bug.
