### ISSUE TITLE
linkchecker fails during build

### ISSUE THREAD

**Issue by canndrew** [rust-lang/rust#39679]
This happens to me quite often when building rustc. The build fails with

```
Linkcheck (x86_64-unknown-linux-gnu)
thread 'main' panicked at 'dir.read_dir() failed with Error { repr: Os { code: 2, message: "No such file or directory" } }', src/tools/linkchecker/main.rs:87
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

The workaround is to simply re-run whatever command I just tried to run and it will probably work the second time. I'm on 64bit NixOS if that's relevant.

**Comment by Mark-Simulacrum** [comment]
Hm, I haven't seen this but I rarely run linkcheck myself -- if I even have. I'm assuming this might be a race condition somewhere in rustbuild; I think we at least need a strace or similar log so we know what directory is not being opened successfully. From what I can tell, linkcheck is run from here: https://github.com/rust-lang/rust/blob/master/src/bootstrap/check.rs#L71. That makes me assume that some subdirectory of doc is transient; perhaps we should put in some form of retry attempt into link check itself.

**Comment by canndrew** [comment]
FWIW I haven't seen this problem in a long while so maybe it's magically fixed itself.

**Comment by Mark-Simulacrum** [comment]
Okay, I'll close for now then -- let us know if it resurfaces and we'll reopen.
