### ISSUE TITLE
x.py does not download boostrap compiler if --build differs from default `build`

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#39675]
With `build` in config.toml being commented out, running (on x86_64) following command fails:

```
$ python x.py test --host=i686-unknown-linux-gnu --stage=2 --target=i686-unknown-linux-gnu --build=i686-unknown-linux-gnu
    Finished debug [unoptimized] target(s) in 0.0 secs


failed to execute command: "./build/i686-unknown-linux-gnu/stage0/bin/rustc" "--version" "--verbose"
error: No such file or directory (os error 2)
```

**Comment by alexcrichton** [comment]
This can likely be fixed by [updating this function](https://github.com/rust-lang/rust/blob/master/src/bootstrap/bootstrap.py#L307-L324), which seems to just not have the proper support yet

**Comment by Mark-Simulacrum** [comment]
Should be fixed by https://github.com/rust-lang/rust/pull/43384.
