### ISSUE TITLE
Help people find String::as_bytes() for UTF-8

### ISSUE THREAD

**Issue by Philipp91** [rust-lang/rust#39688]
Previous discussion:
https://github.com/rust-lang/rust/issues/14131
https://github.com/rust-lang/rust/pull/17438
Still a minor thing, so probably not worth an RFC.

`as_bytes()` is a fine name, but the function is not easy to discover. I have video evidence of Rust beginners who know and use `from_utf8()`, but can't find the inverse, which is `as_bytes()`. The documentation provides no links between the two.

Possible mitigations (could even apply multiple of these):

- Offer `.as_utf8()` or `.to_utf8()`, and `.into_utf8()` and mention in the documentation that it's simply an alias.
- Put "UTF-8" or "utf8" in the documentation of `.as_bytes()` and friends, so it can at least be found through search engines. Currently, queries for "rust string to utf8" or "rust utf8 bytes from string" only take you to the `from_utf8()` function, which works the wrong way round.
- Reference `.as_bytes()` and `.from_utf8()` from each other and mention that they are (roughly) inverses (modulo error handling, modulo ownership stuff).

Currently, http://stackoverflow.com/questions/27195506/convert-an-ascii-string-literal-to-u8-in-rust#comment42877192_27195762 might be the hint that helps most people discover `as_bytes()`.

**Comment by steveklabnik** [comment]
> Reference .as_bytes() and .from_utf8() from each other and mention that they are (roughly) inverses (modulo error handling, modulo ownership stuff).

This is the way I'd want to go; I'm working with @jdhorwitz on this

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/40226 was merged, closing!
