### ISSUE TITLE
Highfive on libc provides incorrect contributing information

### ISSUE THREAD

**Issue by binarycrusader** [rust-lang/rust#39704]
As a new contributor, I was surprised to discover that running tidy via 'x.py src/tools/tidy' at the top-level was not sufficient to check changes in submodules.

Please consider adding a recursive option that understands the rules of each submodule and runs the appropriate style check.

If this already exists somehow, my apologies.

**Comment by binarycrusader** [comment]
Also, please consider updating the ["Pull Requests" section](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#pull-requests) in the contributing information to make it clear that each submodule of rust (for reasons unclear to me) has its own contribution process.

**Comment by alexcrichton** [comment]
FWIW I don't think there's much to do here for this repo specifically, we don't actually want to force our own style guidelines on all other repos we use. The [motivation for this report](https://github.com/rust-lang/libc/pull/516), however, I think is quite relevant! Namely we should probably tweak the contributing guidelines to at least mention that they're targeted at rust-lang/rust. Otherwise because rust-highfive is running on a bunch of other repos it may be confusing with the same message across all of them.

@nrc do you know if it'd be possible for rust-highfive to have a tweaked message across repositories?

**Comment by binarycrusader** [comment]
I think, at a minimum, it'd be helpful to make the relationship between rust-lang/rust and the other submodules clearer.  From a person new to contributing to rust, "it's all one project".  It's very confusing when you discover that they're not.  Briefly explaining that relationship and mentioning that each has its own contribution process would help immensely, as would tweaking the message from the bot.  Thanks for your kind consideration.

**Comment by nrc** [comment]
> do you know if it'd be possible for rust-highfive to have a tweaked message across repositories?

This would be very easy to implement

**Comment by alexcrichton** [comment]
@binarycrusader yeah definitely! 

@nrc I believe all the relevant configuration is in [your highfive repo](https://github.com/nrc/highfive) right? And it looks like the message specifically for new PRs would be [in newpr.py](https://github.com/nrc/highfive/blob/master/highfive/newpr.py)?

**Comment by nrc** [comment]
@alexcrichton yes and yes

**Comment by Mark-Simulacrum** [comment]
I believe we should add a dedicated `contributing` option to the config for libc, [here](https://github.com/nrc/highfive/blob/master/highfive/configs/libc.json). I'm uncertain how the deploy process for highfive works today though.

**Comment by JohnTitor** [comment]
Triage: highfive on libc now displays the contributing.md on the repo as expected (e.g. https://github.com/rust-lang/libc/pull/1974#issuecomment-724893909).
Also, the rustc-dev-guide, which is the contributing guide of rust-lang/rust, has some mentions about submodules e.g. https://rustc-dev-guide.rust-lang.org/contributing.html?highlight=submodule#external-dependencies-submodules
So I'm going to close this issue. If you have any thoughts about submodules, feel free to open a new issue on the rustc-dev-guide repo. Thanks!
