### ISSUE TITLE
book: nightly not updated for rustup

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#39723]
https://doc.rust-lang.org/stable/book/nightly-rust.html still shows rustup.sh

I am happy to mentor anyone who wants to tackle this.

**Comment by Aaronepower** [comment]
Oh, sorry when the person on IRC brought that up, I already went and made a PR for it. #39725

**Comment by Mark-Simulacrum** [comment]
This can be closed; PR was merged and now just needs to roll through. Unless we consider it important enough for a backport?

**Comment by steveklabnik** [comment]
Nope, thanks!
