### ISSUE TITLE
Better error message when calling an Option<Fn>

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/rust#39727]
https://play.rust-lang.org/?gist=f09dc845dad8c1c205c0142923614a8d
It should say 'expecting a function, got a Result<_, _>' or something like that.

**Comment by Mark-Simulacrum** [comment]
I believe that the concrete thing we need to do here is as @Yamakaky says, change the message to say "Expecting a function, but got {type here}.` It's possible the type information should go in a note instead of in the main message.

**Comment by estebank** [comment]
Current output:

```
error[E0618]: expected function, found `Result<fn() {empty}, ()>`
 --> src/main.rs:5:5
  |
4 |     let f: Result<_, ()> = Ok(empty);
  |         - `f` has type `Result<fn() {empty}, ()>`
5 |     f();
  |     ^--
  |     |
  |     call expression requires function
```
