### ISSUE TITLE
English syntax readability issues

### ISSUE THREAD

**Issue by cnguyen83** [rust-lang/rust#39737]
Sorry if this sounds nitpicky or is the wrong place for this (I'm new to open-source, Rust, GitHub and programming as a whole).

Just started reading The Book to learn Rust and programming in general. There are some grammar readability issues in The Book. Not sure if editing is needed, but I would love to help fix some of those as I go through The Book!

**Comment by DaseinPhaos** [comment]
I think you might want to open an issue at [repo of The Book(new edition)](https://github.com/rust-lang/book) instead.
This repo is for the language itself.

**Comment by steveklabnik** [comment]
Yes! @DaseinPhaos has it right. @cnguyen83 , if you find issues, please just send in pull requests. Thanks!
