### ISSUE TITLE
Reinstate the proc macro prelude

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#39745]
There used to be a prelude for procedural macros which was most of what a proc macro author would need to import to write a 2.0 proc macro. (It was actually kind of in two places, which was not perfect - `proc_macro_tokens::prelude` and `syntax::ext::proc_macro_shim::prelude`). We should bring this back - it is a useful tool.

cc @jseyfried @keeperofdakeys

**Comment by jseyfried** [comment]
IMO, this isn't worth it so close to landing `#[proc_macro]` and powerful `proc_macro::TokenStream` API.

**Comment by Mark-Simulacrum** [comment]
@jseyfried @nrc What are your thoughts on this? `TokenStream` has landed at least in a reduced form and macros 2.0 is starting to land slowly.
