### ISSUE TITLE
UTF-8 error unwrap when building project

### ISSUE THREAD

**Issue by Razican** [rust-lang/rust#39741]
Trying to build a small project of mine I got a panic in the compiler. Interestingly enough, I built it first by sending the project through SCP from my computer to the test server where I was going to compile it, but I saw that I was sending the compiled rlibs so I stopped the transmission, probably corrupting the files. When I ran `cargo build` the compiler panicked. I then ran `cargo clean` and `cargo build` worked as expected, so I can no longer reproduce the issue :/

## Meta

`rustc --version --verbose`:

```
rustc 1.15.1 (021bd294c 2017-02-08)
binary: rustc
commit-hash: 021bd294c039bd54aa5c4aa85bcdffb0d24bc892
commit-date: 2017-02-08
host: x86_64-unknown-linux-gnu
release: 1.15.1
LLVM version: 3.9
```

Backtrace:
Sadly I ran `cargo clean` before runing with backtrace and since then I cannot reproduce the issue. This is the output of the build, though:

```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 19 }', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `regex_tester`.
```

**Comment by durka** [comment]
I've seen similar things before when downgrading the compiler. That's an earlier compiler failing to understand a format that was changed later, so it's impossible to fix without a time machine. Without a backtrace here this is likely unactionable.

**Comment by Razican** [comment]
I will post a backtrace if I get to reproduce

**Comment by Mark-Simulacrum** [comment]
This issue is currently not actionable, so I'm going to close. If we get a backtrace, we'll reopen. Thanks!

**Comment by MarkMcCaskey** [comment]
I just ran into this issue in CI for Rust stable 1.41.0 on Ubuntu 16.04 and my error includes a back trace!

[wapm-build-rust-ice.txt](https://github.com/rust-lang/rust/files/4247289/wapm-build-rust-ice.txt)

It appears to not be easily reproducible though, retrying the build fixed it and other builds on other branches passed too.

**Comment by Mark-Simulacrum** [comment]
Interesting. The error happens in the decode implementation for `Symbol`, specifically the `read_str` call. This probably means that we're just messed up reading metadata -- i.e., we're not actually reading a string. But I'm not sure why our normal "stale metadata" checking doesn't account for this, I would expect the compiler versions to be different and for us to just not load the metadata at all.

**Comment by Nilstrieb** [comment]
This seems to be a "something went wrong with metadata" error, which are not actionable without any reproduction. Closing as unactionable, feel free to reopen if you encounter the problem again with a reproduction.
