### ISSUE TITLE
f32, f64 missing from_le, from_be, to_le, to_be, swap_bytes implementation

### ISSUE THREAD

**Issue by Timmmm** [rust-lang/rust#39742]
For all the integer primitives there are functions for converting the endianness: `from_le`, `to_le`, `from_be`, `to_be` and `swap_bytes` (they probably should be a trait but they aren't for whatever reason).

The floating point types `f32` and `f64` don't have these methods defined.

**Comment by rkruppe** [comment]
Can you explain why they *should* have those methods? Floating point types aren't a natural choice for bit twiddling. They don't even have more fundamental bit manipulation operations such as bitwise operators or shifts/rotates.

**Comment by est31** [comment]
There is also the issue of signaling NaN's. See more discussion on this in #39271.

**Comment by Timmmm** [comment]
I'm [wrapping libsoundio](https://github.com/Timmmm/soundio-rs) and that allows audio devices to support little and big endian floating point samples. These functions would be useful for converting between those.

For example I have this in a macro, which works for all the integer types, but not floating point types:

		fn from_raw_le(ptr: *const u8) -> Self {
			Self::from_le( unsafe {
				*(ptr as *const _)
			} )
		}

See also [wikipedia](https://en.wikipedia.org/wiki/Endianness#Floating_point). Finally I feel like they should be there just for completeness.

**Comment by tbu-** [comment]
This particular function would be unsafe for floats btw, arbitrary bit patterns might be signaling NaNs for floats.

**Comment by Mark-Simulacrum** [comment]
I think we could have these, though it's not clear to me that we should. They'd certainly have to be unsafe, I think.

**Comment by dtolnay** [comment]
This seems reasonable to me. I would consider a PR to add these.

**Comment by tbu-** [comment]
I think it would be better to not store floating points of nonnative endian in `f32` or `f64`, creating a wrapper type for that sounds safer (as you won't forget to cast it).

**Comment by frewsxcv** [comment]
Just to clarify my last comment, i'm talking about the implementation of `f32::swap_bytes`, just wondering the easiest way to accomplish the byte swap

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by tbu-** [comment]
@steveklabnik Since this issue was create, we have created alternative methods to convert floats from/to bytes in big/little endian: #60446.

**Comment by Timmmm** [comment]
Yeay!
