### ISSUE TITLE
unquote should work inside string literals

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#39755]
e.g.,
```
let x = ...;
quote!(println!("hello unquote x"));
```

This should expand to `println!("hello ...")` but currently expands to `println!("hello unquote x")`

cc @jseyfried

**Comment by JordiPolo** [comment]
In your example you are using the literal string "hello unquote x", it is not calling `unquote` anywhere

**Comment by jseyfried** [comment]
@nrc How would you expect this to work:
 - `x` is a `TokenStream` that gets pretty-printed into a string literal,
 - `x` is a `TokenStream` that we expect to be a single string literal token,
 - `x` is a `&str`
   - i.e. the example is equivalent to `quote!(unquote Token::str_lit(&format!("hello {}", x)))`,
 - something else?

**Comment by jseyfried** [comment]
@nrc How would you expect this to work:
 - `x` is a `TokenStream` that gets pretty-printed into a string literal
   - i.e. the example is equivalent to
`quote!(concat!("hello ", unquote Token::str_lit(&pretty_print(x))))`,
 - `x` is a `TokenStream` that we expect to be a single string literal token
   - i.e. the example is equivalent to `quote!(concat!("hello ", unquote x));`,
 - `x` is a `&str`
   - i.e. the example is equivalent to `quote!(concat!("hello ", unquote Token::str_lit(x)));`,
 - something else?

**Comment by nrc** [comment]
Hmm, I'm not sure if it is possible, but I'd hope either of the latter two would work. The first feels too magical. If we can only make one work, then the last is probably best.

The motivation here is that we need a string literal (c.f., a concatenation or whatever) for the fmt/println macros. I suppose an alternate solution would be an eager expanded string concat macro? Or we could try to provide some API for ergonomically putting together string literals.

**Comment by jseyfried** [comment]
@nrc We can use `concat!` in fmt/println/etc. ([example](https://play.rust-lang.org/?gist=970e2d4211b41cc876dd583639893383&version=nightly&backtrace=0)), i.e. my equivalent examples work today.

That being said, eager expansion within `quote!` might be nice, e.g. `quote!($!concat("foo", unquote tok))` would be a string literal. I would prefer supporting this (we implement for `concat` and other built-ins today) rather than giving `unquote` meaning in a string literal.

**Comment by steveklabnik** [comment]
Triage: does unquote even exist any more?

**Comment by Mark-Simulacrum** [comment]
I think it means `$` and @jseyfried's suggestion to use `concat!` or manual string concatenation IIRC works today, at least in proc macros, so I believe this is fixed; closing.
