### ISSUE TITLE
Installing rust using a Dockerfile fails.

### ISSUE THREAD

**Issue by timthelion** [rust-lang/rust#39764]
Hi,

I tried installing rust, just now, using a Dockerfile, and I got this:

```
Step 3 : RUN curl https://sh.rustup.rs -sSf | sh
 ---> Running in 22d3db0b0df8
info: downloading installer

sh: 94: cannot open /dev/tty: No such device or address

Removing intermediate container 22d3db0b0df8
```

**Comment by sfackler** [comment]
This should probably be filed on https://github.com/rust-lang-nursery/rustup.rs

**Comment by timthelion** [comment]
Thanks for routing me. It looks like this bug is actually a dup: https://github.com/rust-lang-nursery/rustup.rs/issues/648
