### ISSUE TITLE
Rust Book: Don't use "px" as font size unit

### ISSUE THREAD

**Issue by StefanoD** [rust-lang/rust#39768]
Displays have different resolutions, so it is not recommended using _px_ as font-size unit. It is better to use _em_ or _%_.

**Comment by carols10cents** [comment]
So @steveklabnik is [in the process](https://github.com/rust-lang/rust/pull/39633) of moving the existing book to use [mdBook](https://github.com/azerupi/mdBook/), which is what [the in-progress new book](https://github.com/rust-lang/book) already uses. Taking a quick glance, it looks like mdBook's styling uses `em`s (it did everywhere I looked at least).

So I think PR #39633 will close this (I don't have permission to close this issue though :)).

**Comment by StefanoD** [comment]
Ok, thx. For the information.
i looked at the new book version and it is almost true what you say, but I could find one font-size declaration using _px_:

```CSS
.menu-title {
  display: inline-block;
  font-weight: 200;
  font-size: 20px;
  //...
}
```
Maybe this was made on purpose, maybe not. I'm not really the web-dev guy. :)

**Comment by carols10cents** [comment]
Yeah that CSS comes from mdBook, so it would need to be fixed over there.

**Comment by StefanoD** [comment]
Ok, thx. I opened an issue on mdBook.
https://github.com/azerupi/mdBook/issues/203
