### ISSUE TITLE
Curl install Rustup on Linux Ubuntu 14.04.5 not working

### ISSUE THREAD

**Issue by danindiana** [rust-lang/rust#39771]
Curl install Rustup on Linux Ubuntu 14.04.5 not working
What can I do to install the latest version of rustup toolchain? 

> > ~$ curl https://sh.rustup.rs -sSf | sh
> > info: downloading installer
> > Cannot execute /tmp/tmp.sdsAviGobB/rustup-init (likely because of mounting /tmp as noexec).
> > Please copy the file to a location where you can execute binaries and run ./rustup-init.
> 
> > 

> speed@speed-desktop:~$ lsb_release -a
> LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
> Distributor ID:	Ubuntu
> Description:	Ubuntu 14.04.5 LTS
> Release:	14.04
> Codename:	trusty
 

rustc --version
rustc 1.3.0 (9a92aaf19 2015-09-15)

**Comment by MatejLach** [comment]
@danindiana It looks to me like a simple permission problem, (have you tried `chmod +x`?) 
Unlikely to be a `rustup` problem, as I just tried it on Arch and it works fine, which should be similar enough to Ubuntu in this scenario. 
As long as $HOME is writeable and `rust-init` has executable permissions, you should be all set.

**Comment by danindiana** [comment]
OK. That gets me further down the road. I chmod the rustup-init, and then had to uninstall the old version of rust. Finally I ran rustup-init after giving it the right permissions and this fired off: 

speed@speed-desktop:~/Downloads$ sudo ./rustup-init
error: $HOME differs from euid-obtained home directory: you may be using sudo
error: if this is what you want, restart the installation with `-y'

So my question is where should I run rusup-init from?

**Comment by durka** [comment]
You don't want to run it with sudo.

**Comment by danindiana** [comment]
Hey @durka Thanks so much!
That's all I needed to know. It's installing now as it should. This ticket should be considered resolved.

**Comment by EvanCarroll** [comment]
This is related to this issue I opened up. There is a better solution here. https://github.com/rust-lang/rust/issues/100159

**Comment by TobiasJacob** [comment]
For people being to lazy to follow the links. You just have to create a temp dir by hand.

```console
mkdir ~/tmp
export TMPDIR=~/tmp
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

works
