### ISSUE TITLE
Cannot infer type for T on Option<Box<T>> when passing None

### ISSUE THREAD

**Issue by celaus** [rust-lang/rust#39797]
Hi! 

So I am unsure if this is a bug (in my understanding it is 😁): When using a type parameter for a function (to assert a certain trait to be implemented), and then using an "optional box" instead of an optional trait object, the compiler somehow doesn't see that `None` was passed and wants/needs to infer the type for the parameter. However since `Option` is an enum with its type parameter only on `Some`, this type inference shouldn't happen? 

The use case is quite simple: 
Serde's `Serialize` trait has a type parameter and therefore can't be a trait object, which is why a type parameter on the calling function has to make sure that serde can serialize whatever is passed in. erased_serde unfortunately seems to have grown stale? It's for the CrateDB driver to avoid breaking the interface by having to specify a type explicitly...
https://github.com/celaus/rust-cratedb/blob/dev/src/lib.rs#L217-L221 

I tried this code:

```rust
trait T {
  fn m<S>(&self, s: S);
}

fn f<X: T>(t: Option<Box<X>>) {
    println!("well");
}

fn main() {
    f(None);
}
```

I expected to see this happen: 

I expected this code to compile, since `Option` is an enum and `None` doesn't have a type parameter ? 

Instead, this happened: 

``` 
/p/t/t{} 🐐  cargo run
   Compiling t v0.1.0 (file:///private/tmp/t)
error[E0282]: unable to infer enough type information about `X`
  --> src/main.rs:10:5
   |
10 |     f(None);
   |     ^ cannot infer type for `X`
   |
   = note: type annotations or generic parameter binding required

error: aborting due to previous error
```

## Meta

`rustc --version --verbose`:
```
rustc 1.15.1 (021bd294c 2017-02-08)
binary: rustc
commit-hash: 021bd294c039bd54aa5c4aa85bcdffb0d24bc892
commit-date: 2017-02-08
host: x86_64-apple-darwin
release: 1.15.1
LLVM version: 3.9
```

**Comment by durka** [comment]
There's no bug. `Option` has a type parameter, and `None` is a variant of `Option`. Even though you passed `None`, the compiler has to know what concrete type `X` you aren't passing in order to generate a correct implementation (monomorphization) of the function. You can fix it by writing `None::<Box<Foo>>` where `Foo` is some struct that you've implemented `T` for.

**Comment by celaus** [comment]
@durka Thanks! It won't be the most elegant solution but it will work 👍

**Comment by WilliamVenner** [comment]
Hi, for anyone coming across this issue, `turbonone` might interest you:

https://github.com/WilliamVenner/turbonone

https://crates.io/crates/turbonone

Here's the solution to this issue, as an example:

```rust
use turbonone::turbonone;

trait T {
  fn m<S>(&self, s: S);
}

fn f<X: T>(t: Option<Box<X>>) {
    println!("well");
}

fn main() {
    f(turbonone!(Box));
}
```

**Comment by bergkvist** [comment]
If you are explicitly writing `None` in the code, the compiler should (in theory) be able to ignore/drop all code paths that depend on the type argument to Option in the function though, right?
