### ISSUE TITLE
Anonymous constants show up as `ref.<stuff>` rather than something useful

### ISSUE THREAD

**Issue by froydnj** [rust-lang/rust#39794]
Building servo in debug mode with `rustc` 1.15.1, and then examining the servo binary with `readelf -sW`, one sees symbols like:

```
171336: 0000000006a970e1 0x1dfa0 OBJECT  LOCAL  DEFAULT   16 ref.54
487796: 00000000088ddd28 87888 OBJECT  LOCAL  DEFAULT   26 ref.Yl
471038: 00000000088b3ce8 87888 OBJECT  LOCAL  DEFAULT   26 ref.Yl
485433: 00000000076338f8 86816 OBJECT  LOCAL  DEFAULT   16 ref.2
485451: 000000000768948e 67264 OBJECT  LOCAL  DEFAULT   16 ref.1
485440: 000000000765acdc 53120 OBJECT  LOCAL  DEFAULT   16 ref.1
489142: 00000000088d1c08 49440 OBJECT  LOCAL  DEFAULT   26 ref.vK
472384: 00000000088a7bc8 49440 OBJECT  LOCAL  DEFAULT   26 ref.vK
```

which is unhelpful for identifying what symbol might be taking up space.

This also happens when compiling the Rust parts of Firefox with release optimizations (with and without LTO enabled), so I don't think it's dependent on which optimization settings are being used.

It would be ideal to have useful symbol names for these things.

**Comment by alexcrichton** [comment]
cc @michaelwoerister

**Comment by michaelwoerister** [comment]
I think those are generated for anonymous constants of which the address is taken, e.g.:
```rust
fn main() {
    let x = &42;
}
```
This results in the following in LLVM:
```llvm
@ref.0 = internal unnamed_addr constant i32 42, align 4
```

In a space-optimized build we'd probably want them have a short symbol name, as not to waste space for just storing the name. But we could emit longer symbol names (that include the name of the containing function for example) for other kinds of builds?

**Comment by froydnj** [comment]
> In a space-optimized build we'd probably want them have a short symbol name, as not to waste space for just storing the name. But we could emit longer symbol names (that include the name of the containing function for example) for other kinds of builds?

Including the name of the containing function would be great for starters!  If we could put in the name of the variable being assigned to, that would be a nice bonus.

**Comment by michaelwoerister** [comment]
@rust-lang/tools: Should we tie this to the `-C opt-level=s / -C opt-level=z`? I'm reluctant to introducing a new compiler switch just for controlling symbol name size.

**Comment by alexcrichton** [comment]
@michaelwoerister sounds reasonable to me!

**Comment by froydnj** [comment]
> Should we tie this to the -C opt-level=s / -C opt-level=z?

I would prefer that we not do this: especially when optimizing for size, it can be useful to see how code changes affect symbol sizes, and those sorts of adjustments are difficult to do if you can't tell what symbols you're looking at.  Firefox, at least, compiles things at `-Os` rather than `-O2` by default, so tying things to `-C opt-level=s` wouldn't fix the initial report from our perspective.

I think anybody who's really concerned about symbol sizes will run `strip` or the equivalent on their binaries, thus getting rid of the symbols altogether.

**Comment by michaelwoerister** [comment]
@froydnj That sounds reasonable.
@rust-lang/tools Is there a tool like this available on all platforms we are interested in?

PS. Who would have thought that typing `man strip` into a search engine would provide mostly results not pertinent to this issue ...

**Comment by alexcrichton** [comment]
AFAIK osx/linux/mingw all have `strip`, but I'm less sure about MSVC

**Comment by michaelwoerister** [comment]
Maybe @vadimcn or @retep998 know more about the MSVC situation?

**Comment by retep998** [comment]
Windows msvc binaries do not have symbol names in them except for DLL imports and exports. Anything which is used internally is just an arbitrary address with no name. All symbol names are provided by the PDB files. Hence why there is no equivalent to `strip` for MSVC.

**Comment by wesleywiser** [comment]
Revisited during wg-debugging triage. Having read through the discussion, we don't think this is actionable any longer. rustc's const evaluator will intern and deduplicate allocations so any symbol that ends up in the final binary does not necessarily represent one single value and may actually represent many different values. As such, there isn't a clear way to change the naming scheme here to make finding the source of the value easier.
