### ISSUE TITLE
`cargo doc` doesn't pick up changes to modules

### ISSUE THREAD

**Issue by SergioBenitez** [rust-lang/rust#39811]
I have a project that's structured as follows:

```
src/
    lib.rs
    module.rs
```

In lib.rs, I have:

```
mod module
```

The `git status` is:

```
Changes not staged for commit:

	deleted:    src/module.rs

Untracked files:

	src/module.rs
```

This `git status` arose from deleting `module.rs` and then renaming a file to `module.rs`.

When I make changes to `lib.rs` and run `cargo doc`, updated documentation is generated. However, if I make changes to `module.rs` and run `cargo doc`, documentation is unchanged. The correct thing, of course, is for `cargo doc` to have picked up the changes. I presume something is going on with how `cargo` is treating files that git believes are "deleted".

**Comment by sanmai-NL** [comment]
Thanks, but should be filed under [`rust-lang/cargo`](/rust-lang/cargo).

**Comment by SergioBenitez** [comment]
@sanmai-NL Thanks, you're absolutely right. Opened https://github.com/rust-lang/cargo/issues/3703.
