### ISSUE TITLE
should we make clear `std::process::ChildStdout` is non-blocking or not?

### ISSUE THREAD

**Issue by hicqu** [rust-lang/rust#39810]
I'm working with `std::process::Child::try_wait` and `std::process::ChildStdout`. Here is an example,
```rust
let mut child = cmd.spawn().unwrap();
loop {
    let mut buf = [0 as u8; 4096];
    if let Some(ref stream) = child.stdout {
        stream.read(&mut buf).unwrap();           // Will it block?
    }
    match child.try_wait() {
        // something here ...
    }
}
```
I could not find ` stream.read(&mut buf)` would block or not in API document. I test that simple code on Linux and it didn't blocking. So,

1) On other platforms, will it block or not?
2) Should we make clear that for every platform?
3) Or it's just an undefined behavor, we should set that stream blocking or nonblocking explicitly?

Please help me. Thanks very much!

**Comment by alexcrichton** [comment]
Yes on all platforms all I/O in libstd is blocking by default, if not it's a bug!

**Comment by hicqu** [comment]
This means that we should make it clear that `std::process:ChildStdout.read` is nonblocking in documents, right?

Thank you for continually improving this amazing language!

**Comment by alexcrichton** [comment]
Did you mean *blocking* as opposed to nonblocking? If so, indeed!

**Comment by hicqu** [comment]
Ok, you are right, it's *blocking* but not *nonblocking*. Thank you!
