### ISSUE TITLE
Procedural macros: attributes are not documented

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#39821]
```rust
#[proc_macro_derive(CustomDerive, attributes(custom_attr1, custom_attr2))]
fn custom_derive(...) ...
```

is not described in https://doc.rust-lang.org/stable/book/procedural-macros.html nor the reference.

I'm happy to mentor anyone who wants to fix this.

**Comment by JDemler** [comment]
I am happy to write my experience with this issue down.
Will do it either tonight or tomorrow morning.
