### ISSUE TITLE
debuginfo-gdb test failures

### ISSUE THREAD

**Issue by amboar** [rust-lang/rust#39838]
Recently I started looking at issues with the Rust test suite on powerpc64le as part of an effort to package Rust for Debian on POWER. I'm using rust-lang/rust@81bd2675eaf96396e363d63aa068b0a462ec5a6d as the basis for my testing, which contains the resolution for #39522, but I still see a large number of failures. I'm testing on Ubuntu Yakkety (16.10), both on powerpc64le and x86_64.

I made a couple of comments on #39522, but I have created a new issue to track my problem as I don't want to hijack a closed issue.

On Ubuntu Yakkety with a clean build of rust at 81bd2675eaf96396e363d63aa068b0a462ec5a6d, invoking `./x.py test src/test/debuginfo/` gives me the output [gdb-ubuntu-rust-debuginfo.txt](https://github.com/rust-lang/rust/files/776150/gdb-ubuntu-rust-debuginfo.txt), which has the summary `test result: FAILED. 54 passed; 40 failed; 13 ignored; 0 measured`.

Yakkety's `gdb` reports:

```
$ /usr/bin/gdb --version
GNU gdb (Ubuntu 7.11.90.20161005-0ubuntu1) 7.11.90.20161005-git
```

Given the issues with different `gdb` versions as outlined in #39522, I figured I'd try building gdb from the tip of binutils-gdb master, which at the time was commit 10ddfe62f8979cfe380b07c4f827e72681cc612a:

```
$ /usr/local/bin/gdb --version
GNU gdb (GDB) 7.12.50.20170213-git
```

This was built with `./configure --with-python=python3`, as is done for Ubuntu (though with many more configure options in Ubuntu's case).

Using my own gdb build I get the output [gdb-master-rust-debuginfo.txt](https://github.com/rust-lang/rust/files/776158/gdb-master-rust-debuginfo.txt) and a result summary of `test result: FAILED. 53 passed; 51 failed; 3 ignored; 0 measured`. Presumably the tests ignored by the patch for #39522 with gdb 7.11.90 are now functional as we have 10 less tests ignored.

However, the plot thickened before I realised that Ubuntu built gdb with Python support, as building a gdb with `./configure && make` gave me a binary that passed many more debuginfo tests. After jumping through several hoops I found I could simulate a lack of Python support in gdb by breaking a part of the Rust source tree with `mv -f src/etc/debugger_pretty_printers_common.py{,.disabled} && touch src/etc/debugger_pretty_printers_common.py`. With this configuration, for both the stock Ubuntu gdb and my custom build, I now get the following logs:

[gdb-ubuntu-rust-debuginfo-no-pp.txt](https://github.com/rust-lang/rust/files/776171/gdb-ubuntu-rust-debuginfo-no-pp.txt)
```
test result: FAILED. 90 passed; 4 failed; 13 ignored; 0 measured
```

[gdb-master-rust-debuginfo-no-pp.txt](https://github.com/rust-lang/rust/files/776172/gdb-master-rust-debuginfo-no-pp.txt): 
```
test result: FAILED. 98 passed; 6 failed; 3 ignored; 0 measured
```

This means one of two things

1. The `gdbr-check` annotations in the tests are out of sync with the pretty printer scripts, and the tests are expecting the wrong output. If this is the case, I have a commit at amboar/rust@67bffe3c91237b99de636109d1a54c8fdbb5451c which makes the expectations match the output. This commit was mechanically generated and the script used is included in the commit message.
2. Alternatively, gdb is loading the pretty printer scripts when it shouldn't be, and this is negatively affecting the test results.

Miscellaneous testing gotchas:

1. Rust caches the test results and won't re-run tests that succeeded previous: need to `rm -rf ./build/x86_64-unknown-linux-gnu/test/debuginfo/*`
2. Changing the gdb invoked by the test suite: Use `sed -ri '/CFG_GDB/s|/usr/bin/gdb|/usr/local/bin/gdb|' config.mk`, and switch the search and replace patterns around as necessary
3. Build gdb with Python support

**Comment by michaelwoerister** [comment]
Thanks for the detailed investigation and report!

**Comment by nodakai** [comment]
Does the fix #41877 work for you?

**Comment by amboar** [comment]
@nodakai I'll test as soon as I get an opportunity. Thanks for the prompt!

**Comment by infinity0** [comment]
Even with #41877 I still get:

~~~~
failures:
    [debuginfo-gdb] debuginfo-gdb/limited-debuginfo.rs
    [debuginfo-gdb] debuginfo-gdb/simple-struct.rs
    [debuginfo-gdb] debuginfo-gdb/simple-tuple.rs

test result: FAILED. 91 passed; 3 failed; 13 ignored; 0 measured
~~~~

~~~~
error: line not found in debugger output: fn limited_debuginfo::main();
[..]
File /home/infinity0/upstream/rustc-1.17.0-src/src/test/debuginfo/limited-debuginfo.rs:
static void limited_debuginfo::main(void);
static void limited_debuginfo::some_function(void);
static void limited_debuginfo::some_other_function(void);
static void limited_debuginfo::zzz(void);
~~~~

~~~~
error: line not found in debugger output: $1 = simple_struct::NoPadding16 {x: 1000, y: -1001}
[..]
$1 = {x = 1000, y = -1001}
~~~~

So it looks like gdb is outputting the non-rust output even with #41877.

Other failures occur on other architectures too, e.g. on [x86](https://buildd.debian.org/status/fetch.php?pkg=rustc&arch=i386&ver=1.17.0%2Bdfsg2-1&stamp=1495065772&raw=0).

**Comment by infinity0** [comment]
Oh, scratch that, this was on a build where I did not apply that patch. The tests are OK with a clean 1.17.0 plus the patch. (The x86 failures still exist but I'll investigate that separately.)

**Comment by amboar** [comment]
@nodakai testing against 554c685b0b3b25b7aa752717edf50b8d6bcab7a0 I no-longer see the failures in either release or debug builds:

```
test result: ok. 105 passed; 0 failed; 3 ignored; 0 measured; 0 filtered out
```

Closing as a consequence!
