### ISSUE TITLE
Documentation for LocalKey could be better worded

### ISSUE THREAD

**Issue by stjepang** [rust-lang/rust#39841]
Source: https://doc.rust-lang.org/std/thread/struct.LocalKey.html

"Initialization is dynamically performed on the first call to with() within a thread, and values support destructors which will be run when a thread exits."

It's unclear what's going on with destructors in this sentence.
The truth is: values that implement Drop will *probably* (on a best-effort basis) get dropped when a thread exits.

**Comment by GuillaumeGomez** [comment]
Any contribution is very welcome. Don't hesitate to give it a try! :)
