### ISSUE TITLE
Deal with outputs of subprocesses better in std::process

### ISSUE THREAD

**Issue by hicqu** [rust-lang/rust#39842]
Suppose that we need run a command in subprocess and collect its outputs(both stdout and stderr). Here is an example:
```rust
fn main() {
    // Command is `nc -l localhost -p 3333`.
    let mut cmd = Command::new("nc");
    cmd.args(&["-l", "localhost", "-p", "3333"]);
    cmd.stdout(Stdio::piped());
    cmd.stderr(Stdio::piped());

    let mut process: Child = cmd.spawn().unwrap();
    'big: loop {
        match process.try_wait() {
            Ok(Some(exit_status)) => {
                println!("sub process exit ok: {}", exit_status);
                break 'big;
            }
            Ok(None) => {
                println!("sub process not exited");
                thread::sleep(time::Duration::new(3, 0));
            }
            Err(s) => {
                println!("try wait return error: {}", s);
                break 'big;
            }
        }

        let mut buf = [0 as u8; 1024];
        process.stderr.as_mut().unwrap().read(&mut buf);
        process.stdout.as_mut().unwrap().read(&mut buf);
    }
}
```

Suppose that the subprocess will only write bytes into *stdout* but not *stderr*.

You can find that the program will never finish if you send a **big** file to it:
```bash
nc localhost 3333 < bigfile.txt -c
```

Analyse:
* the *stdout* pipe is full, so the subprocess will wait for that to finish writing, so it cannot exit.
* the subprocess can't exit, so the parent process will block on *stderr* forever, and can't fetch any bytes from *stdout*.

I think it's a deadlock, exactly. 

To resove that, 

* maybe we can fetch bytes from *stderr* and *stdout* with 2 threads simultaneously;
* or maybe we can improve **read API** on `ChildStdout` and `ChildStderr` to simlify that;
* or just use some event-driven libs like mio.

So, which way do you think is better?

**Comment by alexcrichton** [comment]
The above code is incorrect where it'll block in stdout/stderr without concurrently reading the other. Could `output` be used here (it handles that case internally)

**Comment by hicqu** [comment]
Ok, `Output` and `Child::wait_with_output` is useful most of the time.

But there are still problems. It's **hard to implement such function** with them:
```rust
fn wait_with_output_and_timeout(process: mut Child, timeout: Duration) -> Output {
    // how to implements here?
}
```

BTW, I think add this **NOTICE** into document is good:
```
If you use pipe between parent and child processes, maybe

what you really need is `wait_with_output` rather than `wait` 

because if the pipe is full, the child process maybe block forever. 
```

Thanks for your help. 👍

**Comment by alexcrichton** [comment]
Sure yeah, the "flavorful" things to do with a process are actually quite difficult! For stuff like that I'd recommend Tokio which generally makes all of this *much* easier

**Comment by Mark-Simulacrum** [comment]
As far as I can tell, this is a documentation issue. I'm not sure, but I don't recall seeing async process communication (or file IO) in Tokio, though I may have missed it.

**Comment by steveklabnik** [comment]
It's unclear to me how exactly the docs could be improved here; if someone has specifics, please open a bug with the exact details. Otherwise, seems like just an error! Closing. Thanks!
