### ISSUE TITLE
linkchecker + mdbook = :frown:

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#39856]
/cc @azerupi @rust-lang/docs 

Right now, linkchecker reads the HTML of rendered pages directly. It seems that mdBook adds anchors through javascript. This means that linkchecker can't validate links to the book, which is unfortunate.

We could replicate mdBook's logic, but I wonder if that's the best way. Let's figure it out here, and then close this bug out by implementing the solution.

**Comment by azerupi** [comment]
I think, but I am not sure anymore, that I implemented it in the JS because it was easier. If there is no other reason, I suppose it would be better to implement this at the generation time.

**Comment by ollie27** [comment]
It would be better to generate the anchors when generating the HTML. While you're at it, it would be nice if the anchors where generated the same way as rustdoc so links on external websites to the rust docs don't break.

**Comment by azerupi** [comment]
@ollie27 How are anchors generated by rustdoc?
Lowercase, strip special characters and replace blank space by a hyphen?

**Comment by ollie27** [comment]
That sounds about right, [here](https://github.com/rust-lang/rust/blob/62eb6056d332be09206dc664f2e949ae64341e64/src/librustdoc/html/markdown.rs#L342-L354) is the code that does it.

**Comment by steveklabnik** [comment]
This has been addressed upstream 🎊
