### ISSUE TITLE
Items in documentation index have strange 0.x number headings

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#39850]
https://doc.rust-lang.org/nightly/

<img width="404" alt="screen shot 2017-02-15 at 11 47 05 am" src="https://cloud.githubusercontent.com/assets/416575/22984782/7d3af82c-f374-11e6-84b4-fb6bb2b233a4.png">

**Comment by steveklabnik** [comment]
This is fixed 🎊
