### ISSUE TITLE
/lib64/ld64.so.2: version `GLIBC_2.22' and /lib64/libc.so.6: version `GLIBC_2.18' not found error on RHEL

### ISSUE THREAD

**Issue by sandipmgiri** [rust-lang/rust#39878]
Hi,

I am trying to build rust package on RHEL7.3(ppc64le) , however I am getting the following error for the command,make:

/root/rust/build/powerpc64le-unknown-linux-gnu/stage0/bin/cargo: /lib64/ld64.so.2: version `GLIBC_2.22' not found (required by /root/rust/build/powerpc64le-unknown-linux-gnu/stage0/bin/cargo)
/root/rust/build/powerpc64le-unknown-linux-gnu/stage0/bin/cargo: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /root/rust/build/powerpc64le-unknown-linux-gnu/stage0/bin/cargo)
make: *** [all] Error 1

Any way to solve this issue?

Thanks!

**Comment by alexcrichton** [comment]
The glibc requirement of the powerpc toolchains was [moved backwards](https://github.com/rust-lang/rust/pull/39382), but only pretty recently. The master branch of this repository bootstraps from the *beta* compiler, which doesn't have that patch unfortunately.

All that to say that rust should work from nightly archives (e.g. pulled down through rustup). Rust on the master branch, however, will need to wait a cycle to work to get the current nightlies as a beta.

**Comment by sandipmgiri** [comment]
Thanks for quick reply!

For me rust installed successfully on RHEL7.3 from nightly archive which is available on webpage 
https://www.rust-lang.org/en-US/other-installers.html 

I would like to know this nightly-build binaries comes from which branch ?

**Comment by alexcrichton** [comment]
Oh all the nightly builds come from `master`, but we cross-compile non-x86 binaries, which is why we can build a powerpc toolchain with an older glibc requirement without worrying about the glibc requirement of beta.

**Comment by cuviper** [comment]
@sandipmgiri FWIW stable rust for ppc64le is now available on epel7-testing:
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2017-f9554c9ddb

**Comment by sandipmgiri** [comment]
Hi @alexcrichton , 

Are you using IBM Advanced Toolkit, to cross-compile rust from master branch ? If not, then could you please explain which method you are using ?

Thanks!

**Comment by cuviper** [comment]
The cross-compile toolchains are those created in #39382, as linked earlier.  I was not aware of the IBM Advanced Toolkit when I made those changes, or I would have considered it, but we should fine with these docker images now anyway.  I've tested ppc64 and s390x on RHEL6 and ppc64le on RHEL7.

**Comment by sandipmgiri** [comment]
Thanks!

**Comment by alexcrichton** [comment]
Ok sounds like this is resolved, so closing.
