### ISSUE TITLE
Invalid Compiler Warning "is never read"

### ISSUE THREAD

**Issue by deltreey** [rust-lang/rust#39873]
Example here: https://is.gd/rJMGCO

Basically, when you call `continue` in a while loop, the compiler thinks that values set inside the loop are never read, even if they're included in the comparison logic that will stop the loop from repeating.

**Comment by deltreey** [comment]
this also happens for return values

Example here: https://is.gd/DZss6j

**Comment by TimNN** [comment]
Duplicate of #22630, I think.

**Comment by deltreey** [comment]
Looks like it to me, though I think my example is better.

On the other issue,  I feel like the linter is at least providing an important bit of information because he created an infinite loop.  In my example the loop demonstrably completes and it is side-by-side with a value that is being set in a similar way and not showing up in the linter.

**Comment by TimNN** [comment]
> I feel like the linter is at least providing an important bit of information because he created an infinite loop.

The example given in #22630 does not cause an infinite loop.

**Comment by deltreey** [comment]
*facepalm* of course.  I totally misread it.  It is a demonstration of the same message from the compiler,
