### ISSUE TITLE
Don't ship duplicate sets of libraries

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#39875]
Today when you install Rust by default you get duplicate sets of libraries at `$sysroot/lib` and `$sysroot/lib/rustlib/$host/lib`, for example:

```
$ find . -name libproc_macro-* | xargs shasum
2453aab91f0cd5e77b9f514d5df15be7b4ec965e  ./lib/libproc_macro-2641322a715c6559.dylib
2453aab91f0cd5e77b9f514d5df15be7b4ec965e  ./lib/rustlib/x86_64-apple-darwin/lib/libproc_macro-2641322a715c6559.dylib
```

We should avoid duplicating these libraries! Unfortunately I'm not sure of the best method of doing so.

**Comment by brson** [comment]
Moving to an on disk scheme that doesn't have duplicate paths to the bins seems fairly challenging, but I can easily imagine installers being smartened to remove the duplication as best they can.

**Comment by Mark-Simulacrum** [comment]
closing in favor of https://github.com/rust-lang/rust/issues/42645
