### ISSUE TITLE
Move COMPILER_TESTS.md out of the root directory

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#39896]
This has bothered me for a while. I like to keep this directory as pristine as possible, and this file looks out of context. It is not documentation one needs to see on first glance of the project, and we don't otherwise have any convention of putting docs into the root dir.

One easy change would be to put this file in src/test, though it's unlikely to be discovered there (which is a problem probably with a number of such documents in the tree). I'd prefer that to having this single document out of place in the root.

**Comment by steveklabnik** [comment]
Maybe the forge?

**Comment by danobi** [comment]
Perhaps include a link into the source tree on https://forge.rust-lang.org/test-suite.html ?

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/40086 apparently fixed this
