### ISSUE TITLE
Rewrite the COPYRIGHT file

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#39897]
This file may be more misleading than not at this point. It has not been kept up to date. I'm not sure the best thing to do here, but maintenance needs to be a concern, particularly now that the flow of crates into tree is opened. Listing the license of every single thing in tree is too hard for humans to do manually.

**Comment by xen0n** [comment]
Something like the `NOTICE` aggregation system used by AOSP should be OK. But keeping things synced in-tree may become a problem as the system generates the result `NOTICE` at build-time.

**Comment by steveklabnik** [comment]
docs team triage: tagging p-medium

**Comment by frewsxcv** [comment]
Some changes to COPYRIGHT were done in https://github.com/rust-lang/rust/pull/43498

**Comment by hsivonen** [comment]
It would be useful for people who ship compiler output but who don't ship the compiler with the output if the COPYRIGHT file clearly distinguished between licenses that apply to the compiler and licenses that apply to compiler output.

For the latter case, it would also be useful to characterize under what condition certain licenses apply to the compiler output. One would hope the if jemalloc is disabled, the jemalloc license doesn't apply and if compiling with `panic=abort`, the libbacktrace license doesn't apply. #48370 suggests this might not be as simple as one could imagine, though, which makes documenting it even more valuable to people who ship compiler output.

**Comment by BubbaSheen** [comment]
I really like the way you explained this. Extremely useful information.

**Comment by steveklabnik** [comment]
Triage: it's not clear to me what purpose COPYRIGHT serves, and what its requirements are, so it's hard to know what to do here. Some clarity from @rust-lang/core would be good.

**Comment by DevQps** [comment]
@rust-lang/core Could you maybe give us some clarity on the purpose of the COPYRIGHT file such that we can solve this issue?

**Comment by DevQps** [comment]
@steveklabnik You're the only one I know that I can ask this :) Do you know who we can ping directly to get input for this so that we can fix the issue?

**Comment by carols10cents** [comment]
I am going to add this to the core team triage agenda so that we work on getting legal advice on this.

**Comment by DevQps** [comment]
@carols10cents Thanks!

Let us know when there's something we can do :)

**Comment by Dylan-DPC** [comment]
closing this as the council issue should be good enough to keep track of this issue
