### ISSUE TITLE
Target x86 only

### ISSUE THREAD

**Issue by singam-sanjay** [rust-lang/rust#39902]
Setting LLVM_TARGETS_TO_BUILD in src/llvm/CMakeLists.txt to X86 didn't have the intended effect as the file was being reset every time I ran make or python ./x.py build even when the file permissions were manually set to 444 (read-only).

How else should I specify to target only x86 ?

**Comment by xen0n** [comment]
You'll need a [`config.toml`][toml] for that.

[toml]: https://github.com/rust-lang/rust/blob/16c94cd6733ab6aeb6ba0b76097a2934a6782345/src/bootstrap/config.toml.example#L54

**Comment by singam-sanjay** [comment]
Should I edit config,toml.example as config.toml in src/bootstrap ?

**Comment by petrochenkov** [comment]
@singam-sanjay 
You need to copy `config.toml.example` into your build directory and rename it to `config.toml`, then the build system will fetch it automatically.

**Comment by petrochenkov** [comment]
(Closing as not-an-issue.)
