### ISSUE TITLE
Unchecked indexing/slicing methods should point towards their safe counterparts

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#39911]
The following unsafe unchecked indexing / slicing methods don't refer to the safe alternatives **at all**, misleading newbies into thinking that they are the preferred way of performing that operation. There should be a big disclaimer stating what their checked counterparts are and that they are preferred.

* `str::slice_unchecked` / `str::slice_mut_unchecked`
* `[T]::get_unchecked` / `[T]::get_unchecked_mut`

**Comment by Mark-Simulacrum** [comment]
cc @rust-lang/docs, this feels like an E-easy issue to me, tagging as such -- we should add the links to the unchecked method documentations pointing to safe indexing (`get`, probably, where applicable as well as noting indexing with the `Index` trait). Does that sound good?

**Comment by GuillaumeGomez** [comment]
@Mark-Simulacrum: Yep, all good.

**Comment by citizen428** [comment]
If no-one picks it up until then I'll try to get this done over the weekend.

**Comment by GuillaumeGomez** [comment]
@citizen428: Sure, go ahead.

**Comment by citizen428** [comment]
This has been merged, so the issue should be closed.
