### ISSUE TITLE
rustdoc: functions unstable markers should be collapsable

### ISSUE THREAD

**Issue by JanZerebecki** [rust-lang/rust#39919]
In rustdoc generated documentation for a function the unstable markers should be collapsed like the rest of the description when the function they annotate is collapsed. If it is useful to differentiate unstable functions in a fully collapsed view a small unstable marker could be added next to the functions type.

I would like to view more of the trait implementations section without scrolling. One thing that currently uses space are the unstable markers.

**Comment by jsha** [comment]
This is now fixed with the recent changes to how toggles work.
