### ISSUE TITLE
`std::ffi::FromBytesWithNulError` is not an `std::error::Error`

### ISSUE THREAD

**Issue by hvenev** [rust-lang/rust#39925]
It should be.

**Comment by Insomgla** [comment]
New to Rust, but I can try working on it if noone else wants to.

**Comment by alexcrichton** [comment]
@Insomgla oh it looks like there's [already a PR for this](https://github.com/rust-lang/rust/pull/39960)!

**Comment by Insomgla** [comment]
@alexcrichton no problem ;)
