### ISSUE TITLE
lazy_static static shadowing struct

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#39926]
In [bjorn3/goodgame_empire_import](https://github.com/bjorn3/goodgame_empire_import) I have a lazy_static with the same name as its type except for the case. (`data::DATAMGR` and `data::DataMgr`)
The static overwrites the page of the struct:

```rust
lazy_static!{
    pub static ref DATAMGR: Mutex<DataMgr> = {
        Mutex::new(DataMgr::new())
    };
}

/// Data manager
#[derive(Debug, Serialize)]
pub struct DataMgr {
    /// List of castles
    pub castles: HashMap<u64, Castle>,
    pub users: HashMap<u64, User>,
}
```

**Comment by sinkuu** [comment]
Do you mean generated rustdoc is corrupted?
If so, this is a duplication of https://github.com/rust-lang/rust/issues/25879.

**Comment by bjorn3** [comment]
Yes
