### ISSUE TITLE
What causes Instant's irregularities?

### ISSUE THREAD

**Issue by Flaise** [rust-lang/rust#39920]
From the documentation for `std::time::Instant`:

> Note, however, that instants are not guaranteed to be **steady**. In other words, each tick of the underlying clock may not be the same length (e.g. some seconds may be longer than others). An instant may jump forwards or experience time dilation (slow down or speed up), but it will never go backwards.

I think I grasp what you *are* saying but what I can't find in the documentation or anywhere else online is further information about why Instants may behave in this manner. Does this happen a lot? Is it likely to be noticeable to users of real-time applications (such as games)? Can these distortions be caused by manual or automatic tampering with the system clock or by leap seconds? Are there alternatives for measuring time in Rust that don't have distortions?

**Comment by nagisa** [comment]
> Does this happen a lot? 

Yes. Namely, NTP may speed up or slow the clock slightly until it matches the time matches the time of NTP server.

> Is it likely to be noticeable to users of real-time applications (such as games)? 

Games are unlikely to notice this. There may be other hard or soft real-time applications where this may matter.

> Can these distortions be caused by manual or automatic tampering with the system clock or by leap seconds?

Yes.

> Are there alternatives for measuring time in Rust that don't have distortions?

Nothing that’s truly cross-platform – there are platforms supported by Rust but which do not support any means to query guaranteed-steady time.

**Comment by sfackler** [comment]
In particular newer versions of Linux offer `CLOCK_MONOTONIC_RAW` which is not affected by NTP adjustments. This isn't necessarily the better approach compared to `CLOCK_MONOTONIC` which is what we currently use, though, since it will be *less* accurate over longer periods of time since it misses out on the corrections NTP applies.

**Comment by Flaise** [comment]
Thanks for the information.

> This isn't necessarily the better approach compared to CLOCK_MONOTONIC which is what we currently use, though, since it will be less accurate over longer periods of time since it misses out on the corrections NTP applies.

What kind of accuracy does that approach lose? Wouldn't it depend on whether an app cares more about duration or time of day? I could seen cron and notifications and similar software wanting to use `CLOCK_MONOTONIC`, whereas games and simulations and multimedia probably care more about `CLOCK_MONOTONIC_RAW` even if their behavior is still acceptable with `CLOCK_MONOTONIC`.

**Comment by sfackler** [comment]
Quartz clocks drift by a ~second per day, and NTP is there to fix that drift periodically by talking to more accurate time sources. NTP will adjust the clock rate by up to 500 parts per million to sync with the "real" time.

**Comment by Mark-Simulacrum** [comment]
I don't believe there's a bug here, so I'm going to close. Please ask if you have any more questions though; users.rust-lang.org may have a wider audience than here :)
