### ISSUE TITLE
Tracking issue for str_checked_slicing

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#39932]
slice::get_unchecked now takes ranges, whereas str takes explicit usize. `str` does not provide an explicit method to slice unsafely with ranges either.

**Comment by alexcrichton** [comment]
Should be a relatively easy API to add! I believe this just needs to mirror slices and can likely use the same trait for abstractions.

**Comment by z1mvader** [comment]
i'd like to do it

**Comment by Mark-Simulacrum** [comment]
Nominating for libs team discussion -- I think it's reasonable to stabilize this. It's been implemented for about two cycles (PR merged March 31st), I believe. The API surface is fairly small -- extending slice `get{,_unchecked}` methods to `str`s. It's possible we should deprecate the `slice_unchecked{,_mut}` methods as we stabilize this extension -- I believe they are obsoleted by this addition.

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

Sounds good to me to stabilize!

**Comment by alexcrichton** [comment]
Note though that we should avoid deprecating stable functions until the alternative, `get_unchecked`, has hit stable.

**Comment by Mark-Simulacrum** [comment]
Wouldn't deprecating and stabilizing at the same time work? Then all code can transition immediately, right?

**Comment by alexcrichton** [comment]
@Mark-Simulacrum nah unfortunately the downside of that is that if you have a library which spans all three channels it's impossible to compile without warnings. On stable you can't use the replacement and on nightly you get warnings. The alternative is that we wait for all three channels to have the replacement, then we turn the warnings on, and that way libraries which span all three channels can immediately update to the newer methods and take action to rid the warnings.

**Comment by dtolnay** [comment]
@rfcbot reviewed

**Comment by brson** [comment]
Yeah it's best to wait to deprecate things until their replacements are stable a while. As soon as you publish a deprecation to nightly people will start migrating away from it and breaking their own downstreams, and breaking backwards compatibility. Best to leave a stable compatibility window.
