### ISSUE TITLE
fakeroot invalidates build cache

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/rust#39951]
In Arch Linux, we use fakeroot to do `make install` while packaging.

This however seems to invalidate built artifacts, building it again.

Please check the rules of invalidation. While bootstrap is preserved, anything other like stage0 is completely built from scratch.

Random notes: fakeroot preserves `HOME`, which should work well with cargo.

**Comment by Mark-Simulacrum** [comment]
Could you provide more details? A log of `RUST_LOG=cargo::metadata=info` would be helpful.

**Comment by ishitatsuyuki** [comment]
I don't think that logging will help, since the problem is probably inside rustbuild itself, resulting in cleaning the built artifacts.

**Comment by kennytm** [comment]
@ishitatsuyuki Could you provide details how to reproduce the problem? Can [this PKGBUILD file](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rust-git) reproduce it?

**Comment by ishitatsuyuki** [comment]
@kennytm [this](https://gist.github.com/ishitatsuyuki/956152c9ee2562e949f55c0181a0c5ee/65d9c9c6571132ffe97ad07bc299cd71b1d45cec) is confirmed to build twice, so probably using that helps.

I have no idea if the "official" AUR version does too. It's quite diverged.

**Comment by Mark-Simulacrum** [comment]
Okay, then a run with `RUST_LOG=bootstrap=debug` would be nice. I asked for the cargo metadata log since if it isn't inside bootstrap, it would be helpful; I don't think there are any assurances where the problem lies. I'll take a look at the script itself within a week or two probably, though I'm not sure if I have access to a platform that will work with it. Shouldn't be too hard to spin up a VM though.

**Comment by Mark-Simulacrum** [comment]
It seems that I was correct asking for a cargo fingerprint log. I reproduced the problem in a docker container with minimal trouble; the log is here: https://gist.github.com/Mark-Simulacrum/e089a2727a4f0f7ed290d17eb6330017#file-log-arch-39951-L468. The line selected is where the first stale fingerprint appears to be. I'm uncertain whether this is rustbuild's, Cargo's or the fakeroot's fault though. @alexcrichton may be able to clarify more based on the log though.

**Comment by ishitatsuyuki** [comment]
Thanks for the log.

I suspect Git submodule handling is trashing the timestamps. Will investigate why it happens.

**Comment by ishitatsuyuki** [comment]
It seems at least `git -C reset hard` ran between fakeroot rewrites (`unlink` and `open(O_WRONLY)`) every file. I feel it like file ownership, but running `git` with `sudo` doesn't yield such weird behavior. Any thoughts?

**Comment by Mark-Simulacrum** [comment]
```
INFO:cargo::ops::cargo_rustc::fingerprint: fingerprint error for compiler_builtins v0.0.0 (file:///home/mark/src/rust/src/libcompiler_builtins): mtime based components have changed: previously Some(FileTime { seconds: 1495761200, nanos: 142046176 }) now None, paths are "/home/mark/src/rust/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/build/compiler_builtins-7332fe221efc4ba8/output" and "/home/mark/src/rust/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/build/compiler_builtins-7332fe221efc4ba8/output"
```

That build output leads me to believe that maybe fakeroot maybe makes the stdlib's mtime commands not succeed? I don't really know. I can do some tests later...

**Comment by jyn514** [comment]
This seems likely to be an issue with fakeroot, not bootstrap or cargo, the timestamps really are different than before.

The issue tracker is not a support forum. For future questions please ask in one of these places:

https://discord.gg/rust-lang/
https://discord.gg/rust-lang-community/
https://users.rust-lang.org/
https://rust-lang.zulipchat.com/
