### ISSUE TITLE
Warn about lints that are disabled but not currently activated

### ISSUE THREAD

**Issue by johnthagen** [rust-lang/rust#39958]
It would be nice if `rustc` could catch an unnecessary use of `#[allow(unused_variables)]`:

```rust
#[allow(unused_variables)]
fn fun(x: u32) -> u32{
    x
}
```

Often times `#[allow(unused_variables)]` is added during development and later should be removed after all parameters are in use so that it doesn't mask a real warning in the future.

Originally this was brought up as a lint for `clippy` (https://github.com/Manishearth/rust-clippy/issues/1552) but was directed here because `clippy` does not handle `allow/warn/deny` itself.

**Comment by sanmai-NL** [comment]
Interesting idea, but what makes such an attribute _unneccessary_?

**Comment by frewsxcv** [comment]
> Interesting idea, but what makes such an attribute _unneccessary_?

Presumably because the existence of the attribute in that particular scenario doesn't result in any fewer warnings upon compilation.

**Comment by sanmai-NL** [comment]
@frewsxcv: yeah, but that context may (likely will) change between compilation runs. I would expect the programmer to put those lint check attributes in with a reason. In general, it is wise/good to check for unneeded `allow` attributes though. I personally see value in the attribute, just trying to point out the trade-off here. Giving warnings when the `allow` attribute coincidentally happens to have no effect at some point in the evolution of the source code is perhaps not desired?

**Comment by sanxiyn** [comment]
This was also discussed in internals.rust-lang.org: [Warning about disabled lints that don't need disabling?](https://internals.rust-lang.org/t/warning-about-disabled-lints-that-dont-need-disabling/4798)

**Comment by jyn514** [comment]
I think this would be covered by the `#[expect]` attribute: https://github.com/rust-lang/rust/issues/54503
