### ISSUE TITLE
rustdoc: Remove the brief of structs and traits

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/rust#39952]
Traits and structs brief should be removed: its functionality can be achieved through pressing the `[-]` button.

Things that are not expressed through the "methods/fields" doucment:

- indication of default implementation on traits: once the brief is removed, we should add an indicator instead to the function line.
- indication of private fields in a struct: we can add a note instead.

<details><summary>Original proposal (superseded)</summary>

Current:
```rust
pub struct Vec<T> { /* fields omitted */ }
```

Desired:
```rust
pub struct Vec<T> { /* fields omitted */ }

impl<T> Vec<T> {
    fn new() -> Vec<T>;
}

impl<T> IntoIterator for Vec<T>;
impl<T> Index<usize> for Vec<T>;
```

EDIT: as @sinkuu mentioned [below](https://github.com/rust-lang/rust/issues/39952#issuecomment-280896479), we have a way to display a well formatted brief by minimizing the descriptions.
We have another option, by removing the brief for traits and advertise the use of [-].
</detail>

**Comment by frewsxcv** [comment]
Do you want it to show all available methods and implementations in the code block at the top?

**Comment by ishitatsuyuki** [comment]
Yeah, scrolling and finding a method is a huge pain for large pages like `Vec`.

**Comment by sinkuu** [comment]
So you are ok with all methods listed, then doesn't pushing `[-]` on top-right of the page give you almost what you want?

![](https://pageshot.net/images/e09549dc-f6b1-45d1-99d3-11a1fe2901c5.png)

**Comment by ishitatsuyuki** [comment]
@sinkuu didn't noticed that, it's looking quite good. I originally intended to have a similar outlook like the traits; they have methods listed in the block.

I would change the topic to uniforming the two; thanks anyway.

**Comment by ishitatsuyuki** [comment]
@rust-lang/docs any interest in this?

**Comment by GuillaumeGomez** [comment]
I have to admit that I don't like the idea... Let's see what others think.

**Comment by jsha** [comment]
In #83337, we went the other direction: making the decl visible by default in more cases, but hiding its contents when it is very long. I think we should close this, since the consensus in #83337 seemed to go in the other direction.

**Comment by GuillaumeGomez** [comment]
Agreed. Just for the record: cc @Manishearth
