### ISSUE TITLE
rustup doc produces an error dialog

### ISSUE THREAD

**Issue by mark-summerfield** [rust-lang/rust#39969]
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

I installed rust using the command in the online manual:

$ curl https://sh.rustup.rs -sSf | sh

This set the path in my .profile file but that doesn't seem to be read even when I open a new console, so I copied the path command into .bashrc and opened a new console:

$ rustc --version
rustc 1.15.1 (021bd294c 2017-02-08)

$ rustup doc
This popped up an untitled message box with the following text:

Failed to open "/home/mark/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/html/index.html".
Error when getting information for file '/home/mark/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/html/index.html': No such file or directory.

$ ls .rustup/
settings.toml  tmp  toolchains  update-hashes

PS I think the docs ought to mention that installing rust creates both $HOME/.cargo *and* $HOME/.rustup

**Comment by ishitatsuyuki** [comment]
You need to install the rust-doc:
https://users.rust-lang.org/t/psa-rust-documentation-is-now-optional-and-opt-in-when-installing-via-rustup/8072

**Comment by ishitatsuyuki** [comment]
Side note: if you want a better error message, file this issue in the rustup repo instead.

**Comment by mark-summerfield** [comment]
Done: https://github.com/rust-lang-nursery/rustup.rs/issues/959
