### ISSUE TITLE
Specific Error Message or Note for Final Expression being Loop and Return not Unit

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#39968]
```rust
fn loop_ending() -> i32 {
    loop {
        if false { break; }
        return 42;
    }
}
```

produces

```
error[E0308]: mismatched types
 --> <anon>:2:5
  |
2 |       loop {
  |  _____^ starting here...
3 | |         if false { break; }
4 | |         return 42;
5 | |     }
  | |_____^ ...ending here: expected i32, found ()
  |
  = note: expected type `i32`
  = note:    found type `()`

error: aborting due to previous error
```

But the compiler can check that the final expression is a loop and must always evaluate into `()`, so we can recommend more advanced information.

This has caused [real confusion](https://www.reddit.com/r/rust/comments/5v163r/loop_has_to_return_a_stdrestultresult_since_when/).

**Comment by nikomatsakis** [comment]
What would you think we ought to suggest?

**Comment by nikomatsakis** [comment]
(In other words, I'm trying to understand what users might be going for when writing code like this... I guess we could say something like "no value returned along this control-flow path" or something?)

**Comment by Havvy** [comment]
Perhaps saying that the `i32` is the expected type because the loop is the implicit return. I forgot about `break value;` actually being a thing when I initially posted the issue, though `for` loops also have the issue.

I guess the issue might actually be that we're not showing where the i32 came from.

**Comment by nikomatsakis** [comment]
Another example (Derived from #18390):

```rust
fn main() {
    let _ = foo();
}

fn foo() -> i32 {
    let x = 5;
    match x {
        1 => {
            1
        },
        2 => {
            2
        },
        3 => {
            3
        },
        4 => {
            4
        },
        5 => {
            5
        },
        _ => {
            0
        },
    };
    match x {
        1 => {
            return 1
        },
        2 => {
            return 2
        },
        3 => {
            return 3
        },
        4 => {
            return 4
        },
        5 => {
            return 5
        },
        _ => { }
    }
}
```

gives:

```
error[E0308]: mismatched types
  --> src/main.rs:5:17
   |
5  |   fn foo() -> i32 {
   |  _________________^
6  | |     let x = 5;
7  | |     match x {
8  | |         1 => {
...  |
44 | |     }
45 | | }
   | |_^ expected i32, found ()
   |
   = note: expected type `i32`
              found type `()`
```

I guess the key point in both cases is that the user is writing more "C-style" code and not *expecting* to make use of the "implicit return" here, so the error is sort of surprising.

**Comment by nikomatsakis** [comment]
It seems to me that we could cover this by a similar rule to the one we use to suggest removing a semicolon -- in particular, if the *expected type* is not unit, but we are returning unit from a tail expression, and that tail expression is some kind of "control-flow" structure, we might point to the end of it and say something like "no return along this path":

```rust
error[E0308]: no return along this path
 --> src/main.rs:3:20
  |
3 |         if false { break; }
  |                    ^^^^^ following this path, no value is ever returned
  |
```

This will require a bit more state to be plumbed around, I imagine, not entirely sure what (and I'm not entirely sure *where* the error should be reported -- on the break, as I showed above?).

**Comment by estebank** [comment]
The current output is even worse, IMO:

```
error[E0308]: mismatched types
 --> src/main.rs:3:20
  |
3 |         if false { break; }
  |                    ^^^^^ expected (), found i32
  |
  = note: expected type `()`
             found type `i32`
```

**Comment by estebank** [comment]
Current output:

```
error[E0308]: mismatched types
 --> src/lib.rs:3:20
  |
3 |         if false { break; }
  |                    ^^^^^
  |                    |
  |                    expected i32, found ()
  |                    help: give it a value of the expected type: `break 42`
  |
  = note: expected type `i32`
             found type `()`
```
