### ISSUE TITLE
Incorrect borrow checking

### ISSUE THREAD

**Issue by ubsan** [rust-lang/rust#39963]
UPDATE: This now works in NLL land. [We just need someone to add a test.](https://github.com/rust-lang/rust/issues/39963#issuecomment-356977719)

----

https://is.gd/O6RlWi

`left.1.0` and `left.0.0` should be separate borrows into the same structure.

Note that changing `**left` to `*&mut**left` makes it borrow check, and changing `Box<Foo>` to `&'static mut Foo` in the `Foo` struct also makes it borrow check. This makes me think it's something to do with the special casing of `Box`.

**Comment by arielb1** [comment]
This is intentional. rust-lang/rfcs#130.

**Comment by ubsan** [comment]
@arielb1 no... it isn't. This is incorrect behavior.

**Comment by eddyb** [comment]
@ubsan I'm afraid @arielb1 is right, we *really* dumbed down `Box`.
Proof: [`box ref mut` makes the problem go away](https://play.rust-lang.org/?gist=376cb79ad384dd1106df39655f2bf5dc&version=nightly&backtrace=0) while [matching on `**(f: &mut Box<Foo>)` reproduces it](https://play.rust-lang.org/?gist=a1aacf332d88f3fc57db33adfa3c0da0&version=nightly&backtrace=0).

**Comment by ubsan** [comment]
@eddyb then it's a bug with the specification.

**Comment by ubsan** [comment]
given that this works: https://is.gd/clzryh

**Comment by arielb1** [comment]
Sure, the equivalent of your code with a `DerefMut` type instead of a `Box` works:
```Rust
#[derive(Clone)]
struct BoxFoo;
impl std::ops::Deref for BoxFoo {
    type Target = Foo;
    fn deref(&self) -> &Foo { panic!() }
}

impl std::ops::DerefMut for BoxFoo {
    fn deref_mut(&mut self) -> &mut Foo { panic!() }
}


#[derive(Clone)]
struct Foo(Option<BoxFoo>, Option<BoxFoo>);

fn test(f: &mut Foo) {
  match *f {
    Foo(Some(ref mut left), Some(ref mut right)) => match **left {
      Foo(Some(ref mut left), Some(ref mut right)) => panic!(),
      _ => panic!(),
    },
    _ => panic!(),
  }
}

fn main() {
}
```

The current borrowck is sort-of in maintenance mode, so this is unlikely to be fixed before MIR borrowck.

**Comment by pnkfelix** [comment]
Nominating. I suggest we retag this as C-enhancement rather than C-bug. I separately suggest that we prioritize it as P-medium. (It does not need to land as part of the initial MIR-borrowck / NLL work.)

**Comment by pnkfelix** [comment]
(looking at #23610, I am wondering: what's the difference between C-feature-request and C-enhancement? Should we collapse those two labels into one...?)

**Comment by nikomatsakis** [comment]
In the NLL / MIR borrow checker, we decided to just be smarter around `Box`. Therefore, [the code now type-checks](https://play.rust-lang.org/?gist=e37893caf7dc2cf19ca29537ffa620e8&version=nightly).

**Comment by nikomatsakis** [comment]
I think I would be happy to just add a test for this (with `#![feature(nll)]`) and close this issue.
