### ISSUE TITLE
Add Iterator::first

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#39967]
`Vec` has both `first` and `last` methods, which make the interface slightly more ergonomic, while `Iterator` only has `last`; `first` is just `nth(0)`, but it would be nice to have an alias over that.

This might be backwards incompatible, though, in which case we likely can't add it, unfortunately.

**Comment by seppo0010** [comment]
Doesn't `next` do the same thing?

**Comment by Mark-Simulacrum** [comment]
Sure, but calling `next().unwrap()` is relatively speaking less readable (at least to me) than `first().unwrap()` (or whatever the form of handling may be, other than unwrapping).

**Comment by retep998** [comment]
The next element in an iterator is not necessarily the first element ever produced by that specific iterator, therefore `first()` makes no sense to me.

**Comment by Mark-Simulacrum** [comment]
That's true. I'm going to close this in that case.

Though it may be worth considering that `nth(0)` is somewhat counterintuitive that it also returns the equivalent of `next`, not really the 0th element of the iterator.
