### ISSUE TITLE
rustc panic

### ISSUE THREAD

**Issue by apt1002** [rust-lang/rust#39970]
rustc asked me to file a bug report:

> error: internal compiler error: /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/infer/mod.rs:626: Encountered errors `[FulfillmentError(Obligation(predicate=Binder(ProjectionPredicate(ProjectionTy { trait_ref: <std::vec::Vec<f32> as array::Array<'a, usize>>, item_name: Element(610) }, _)),depth=1),MismatchedProjectionTypes(RegionsInsufficientlyPolymorphic(BrNamed(CrateNum(0):DefIndex(1030), 'a(180), WontChange), '_#0r)))]` resolving bounds after type-checking
> 
> note: the compiler unexpectedly panicked. this is a bug.
> 
> note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
> 
> thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc_errors/lib.rs:382
> note: Run with `RUST_BACKTRACE=1` for a backtrace.

Here's [a fragment of code](https://play.rust-lang.org/?gist=bd9babc03dbc57d51159eb35cc8e57c2&version=stable&backtrace=0) sufficient to trigger the bug. It's not minimal yet, sorry. The code might not be correct; I was kinda relying on the compiler to tell me. ;-)

> $ rustc --version --verbose
> rustc 1.15.1 (021bd294c 2017-02-08)
> binary: rustc
> commit-hash: 021bd294c039bd54aa5c4aa85bcdffb0d24bc892
> commit-date: 2017-02-08
> host: x86_64-unknown-linux-gnu
> release: 1.15.1
> LLVM version: 3.9

I hope you can make something of this.

**Comment by est31** [comment]
Fairly minimized: https://play.rust-lang.org/?gist=621b19255bd764d427cc9d05f2b1ba80&version=stable&backtrace=0

**Comment by est31** [comment]
Even smaller: https://play.rust-lang.org/?gist=55a654881aa050566fa44f9c0bdd011d&version=stable&backtrace=0

**Comment by apt1002** [comment]
https://play.rust-lang.org/?gist=9404547723645a7f5d9c4661be8364c5&version=stable&backtrace=0 <-- I've been minimising too!

**Comment by apt1002** [comment]
The following features seem to be essential:

- Type Element must be a reference.
- The bound "Element=V" must be present.

**Comment by est31** [comment]
I think I found it:

```rust
trait Array<'a> {
    type Element: 'a;
}

trait Visit {
    fn visit() {}
}

impl<'a> Array<'a> for () {
    type Element = &'a ();
}

impl Visit for () where
    //(): for<'a> Array<'a, Element=&'a ()>, // No ICE
    (): for<'a> Array<'a, Element=()>, // ICE
{}

fn main() {
    <() as Visit>::visit();
}
```

This gives an error message like:

```
error: internal compiler error: /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/infer/mod.rs:626: Encountered errors `[FulfillmentError(Obligation(predicate=Binder(ProjectionPredicate(ProjectionTy { trait_ref: <() as Array<'a>>, item_name: Element(83) }, ())),depth=1),MismatchedProjectionTypes(Sorts(ExpectedFound { expected: &(), found: () })))]` resolving bounds after type-checking
```

Note the `expected: &(), found: ()` here

**Comment by apt1002** [comment]
Good spot. Can also interchange () with &() to get an [even simpler version](https://play.rust-lang.org/?gist=de86ed2e419544184ea2d4978f3714e0&version=stable&backtrace=0).

**Comment by apt1002** [comment]
The <() as Visit> part seems to be essential. [No ICE](https://play.rust-lang.org/?gist=46cf1796d55251e692561a7181f92f49&version=stable&backtrace=0).

**Comment by apt1002** [comment]
Another slight [simplification](https://play.rust-lang.org/?gist=420586a8b6cf1c3d378eb667f314b9f9&version=stable&backtrace=0).

**Comment by apt1002** [comment]
I have some more evidence that I think is worth recording here. Our minimised version above crashes the compiler in a case where it should be reporting an error. I now have a version that crashes the compiler when it should be accepting the program.

I returned to my original program and specialized it to the case I care about, i.e. I instantiated all the generics. After minor fixes, [it works](https://play.rust-lang.org/?gist=aa9e6ae265abb9be35e4eb617fe8db70&version=stable&backtrace=0). However, replacing `&'a mut f32` with the equivalent `<Vec<f32> as Array<'a, usize>>::Element` crashes the compiler.

[Parially minmized](https://play.rust-lang.org/?gist=1a44b7bb239de24ae32371bff11ca6ec&version=stable&backtrace=0). [Fully minimized](https://play.rust-lang.org/?gist=445211d9359da69d9e42420a94eb7532&version=stable&backtrace=0).
