### ISSUE TITLE
RefCell should check for overflow of borrow counter

### ISSUE THREAD

**Issue by Storyyeller** [rust-lang/rust#39994]
I just noticed that [BorrowFlag](https://github.com/rust-lang/rust/blob/a17e5e2949db53c9c1e3a697e41c254e31c0bdf3/src/libcore/cell.rs#L543) says the following

```
// Values [1, MAX-1] represent the number of `Ref` active
// (will not outgrow its range since `usize` is the size of the address space)
type BorrowFlag = usize;
```

However, this is not a safe assumption due to mem::forget. I looked through the code, and I don't see any overflow checks. This means that by repeatedly borrowing and forgetting from a RefCell, you can overflow the internal counter.

Luckily, once the counter overflows, the RefCell will appear to be in the mutably borrowed state, preventing any further borrows. So I _think_ this isn't a soundness issue. But it seems like it would be better to check, just to be sure, or at least add comments explaining why it is safe so people accidently don't mess it up in the future.

Edit: I noticed that BorrowRef's clone() impl does check for overflow. Still, I think the current behavior of allowing the counter to get to WRITING before panicing is overflow error prone. RefCell might grow a method at some point which incorrectly interprets a WRITING state to mean that it is not immutably borrowed for instance.

**Comment by alexcrichton** [comment]
IIRC we acknowledged this and overflow into "now mutably borrowed" was considered acceptable. Do you  have some example memory unsafety though?

**Comment by Storyyeller** [comment]
Ah, I didn't realize it was already considered. I just happened to be looking at the RefCell code and thought it looked odd.

**Comment by alexcrichton** [comment]
If you'd like though a comment explaining this behavior would be most welcome! (in the code itself, that is)
