### ISSUE TITLE
Text formatting: a leading zero on the minimum width should really mean leading zero

### ISSUE THREAD

**Issue by jimblandy** [rust-lang/rust#39997]
In a string format, the leading zero on a minimum width is treated as a padding character. It would make more sense for it to be treated strictly as a leading zero. The status quo permits strange things like this:
```
assert_eq!(format!("{:<04}", 1), "1000");
```
Either `"   1"` or `"0001"` would be better answers than one that changes the numeric value.

Just to be clear, I agree that this behavior is correct:
```
assert_eq!(format!("{:0<4}", 1), "1000");
```
This case uses `0` as its padding character, so you deserve whatever you get.

**Comment by alexcrichton** [comment]
Seems reasonable to me, as documented:

> 0 - This is used to indicate for integer formats that the padding should both be done with a 0 character as well as be sign-aware. A format like {:08} would yield 00000001 for the integer 1, while the same format would yield -0000001 for the integer -1. Notice that the negative version has one fewer zero than the positive version.

The precise definition of "sign aware" isn't really specified and this seems like a great interpretation to me (changing the first example above to `0001`)

**Comment by hirschenberger** [comment]
#40729 is related and can be closed.
