### ISSUE TITLE
Consider implementing AsRawFd for Stdout, Stdin and Stderr

### ISSUE THREAD

**Issue by malbarbo** [rust-lang/rust#40007]

**Comment by nagisa** [comment]
This cannot happen, because `Stdout` and `Stderr` may be replaced by arbitrary instance of `Write` internally.

**Comment by malbarbo** [comment]
@nagisa 
> This cannot happen, because Stdout and Stderr may be replaced by arbitrary instance of Write internally.

How can Stdout be replaced by an arbitrary instance?

Note that the trait `AsRawFd` is an extension trait defined in some platforms, like [unix](https://doc.rust-lang.org/stable/std/os/unix/io/trait.AsRawFd.html), in platforms that does not define  `AsRawFd` trait or does not have a reasonable implementation of `AsRawFd` for `Stdout`, the implementation would be missing.

**Comment by nagisa** [comment]
Its private API to [libstd](https://github.com/rust-lang/rust/blob/8a1ce4020c480e455ec902e3616843a3dd5fe489/src/libstd/io/stdio.rs#L639-L660).

**Comment by jmesmon** [comment]
Due to the `Send` bound, it seems like one only needs threads + pipes to implement `AsRawFd`.

**Comment by alexcrichton** [comment]
Done in https://github.com/rust-lang/rust/pull/43459!
