### ISSUE TITLE
Poor parser error message when item category missing (assumes input is a macro)

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#40006]
Consider this code ([playpen](https://is.gd/AkFshR)): 

```rust
struct S;
impl S { pub hello_method(&self) { println!("Hello"); } }
fn main() { S.hello_method(); }
```

It yields this error today: 

```
rustc 1.17.0-nightly (a17e5e294 2017-02-20)
error: can't qualify macro invocation with `pub`
 --> <anon>:2:10
  |
2 | impl S { pub hello_method(&self) { println!("Hello"); } }
  |          ^^^
  |
  = help: try adjusting the macro to put `pub` inside the invocation

error: expected one of `!` or `::`, found `(`
 --> <anon>:2:26
  |
2 | impl S { pub hello_method(&self) { println!("Hello"); } }
  |                          ^

error: aborting due to previous error
```

In this case, the actual error is that the user left out the keyword after the visibility to indicate which kind of item they are trying to define here.

Our parser should be able to do a better job here. At the very least, if there is no trailing `!`, then instead of assuming that the input was a macro invocation, it should instead assume it was *some* item definition that is missing its keyword.

**Comment by timthelion** [comment]
I ran into what seems to be a very similar case. If you don't put a `;` at the end of a `match` block, then the compiler tells you very unrelated things: https://play.rust-lang.org/?gist=ab74d4c0f3dce8c095f79469bc69b072&version=nightly&backtrace=0

**Comment by sanxiyn** [comment]
@timthelion Can you file that as a separate bug? Thanks!

**Comment by timthelion** [comment]
@sanxiyn as you wish.
