### ISSUE TITLE
rustdoc error on file not found cites wrong filepath

### ISSUE THREAD

**Issue by Zteve** [rust-lang/rust#40005]
While at the same level as `src` and with a `doc` directory, too:
```
$ rustdoc src/design.md
rustdoc: doc/design.html: No such file or directory (os error 2)
```
This seems like the wrong filename and the wrong directory in the output message.  The file `src/design.md` doesn't exist, by the way.

Mac OS  and rustdoc 1.15.0 (10893a9a3 2017-01-19)

**Comment by durka** [comment]
It looks like if you don't specify an output path, rustdoc defaults to a `doc` directory. You get this error if that directory doesn't exist.

**Comment by Zteve** [comment]
Hmm; but it is the `src/design.md` that doesn't exist.  I suppose the message could be a little smarter.

**Comment by Zteve** [comment]
Strange, I seem to get a different (correct) error today (same version), whether `doc\` exists or not:
`error reading 'src/design.md': No such file or directory (os error 2)`.
It is a puzzle.

**Comment by durka** [comment]
Wait are you sure `src/design.md` doesn't exist? For that I get an error that refers to the file. It's when the source file does exist but the `doc` directory doesn't, that the error message fails to mention _what_ doesn't exist. Perhaps you weren't in the directory you thought you were when running the original command?

**Comment by durka** [comment]
I'm not on Windows though, so there could be something weirder going on.

**Comment by Zteve** [comment]
OK I'm not able to reproduce this, so closing this. Thanks for the time.
