### ISSUE TITLE
Add Iterator trait to numeric literals

### ISSUE THREAD

**Issue by amosbird** [rust-lang/rust#40004]
This makes `1.iter().chain(...)` possible which is cleaner than other ways.

**Comment by bluss** [comment]
Hi, wishes for new features (things that are not bugs) are filed in the [rust-lang/rfcs](https://github.com/rust-lang/rfcs) repo.

I think the most successful way to get a new feature into Rust would be something like:

1. Sound it out in the https://internals.rust-lang.org/ forum. They will know if a PR or [RFC](https://github.com/rust-lang/rfcs#when-you-need-to-follow-this-process) is the best way to go. For RFCs I really recommend posting them as Pre-RFC threads on internals before filing the real thing.
2. File appropriate PR or RFC

I'll close this issue with that information.
