### ISSUE TITLE
Nightly/beta regression? Sized + UnwindSafe

### ISSUE THREAD

**Issue by dpc** [rust-lang/rust#40011]
```
use std::panic::UnwindSafe;

fn is_unwind_safe<T: UnwindSafe>() {}

trait Foo: UnwindSafe {}

fn main() {
    is_unwind_safe::<Box<[u8]>>();
    is_unwind_safe::<Box<Foo>>();
}
```

https://is.gd/xWwNn6

Compiles on stable, but fails on beta and nightly.

**Comment by alexcrichton** [comment]
I don't recall any changes on the libs side offhand, but @rust-lang/compiler does this look familiar?

**Comment by TimNN** [comment]
Introduced between `nightly-2017-01-26` and `nightly-2017-02-02` ([Changes](http://github.com/rust-lang/rust/compare/df8debf6d...24055d0f2)) (Sadly, no nightlies in between.

**Comment by eddyb** [comment]
This is actually @petrochenkov's #39230 exposing [a library bug](https://github.com/rust-lang/rust/blob/8a1ce4020c480e455ec902e3616843a3dd5fe489/src/libstd/panic.rs#L201) (missing `?Sized`):
```rust
impl<T: UnwindSafe> UnwindSafe for Unique<T> {}
```

**Comment by alexcrichton** [comment]
Thanks for the investigation @eddyb!

**Comment by alexcrichton** [comment]
Sent a fix as https://github.com/rust-lang/rust/pull/40020
