### ISSUE TITLE
rustbuild: `test --stage 1 src/test/ui` builds "stage1 compiler artifacts"

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#40016]
while other useful stage 1 tests like `compile-fail` or `run-pass` will happily run after building only "stage1 std artifacts".

`compile-fail` and `ui` are inseparable and need to be tested together and building "stage1 compiler artifacts" makes the edit-compile-test cycle ~twice longer.

**Comment by alexcrichton** [comment]
To do this we'd have to split the ui test suite between "requires only std" and "requires more than std". I believe there's one test which requires plugins, which needs to build the whole compiler

**Comment by petrochenkov** [comment]
Like `compile-fail-fulldeps`, but `ui-fulldeps`? (If understand the purpose of fulldeps tests correctly.)

**Comment by alexcrichton** [comment]
Indeed!
