### ISSUE TITLE
use the new "unconstrained type parameter" callbacks more often

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#40013]
https://github.com/rust-lang/rust/pull/39361 improved our error messages around uninferable types, but there is still room to do better. For one thing, as @arielb1 pointed out, we currently detect these errors in a kind of odd place (when a `Sized` obligation is not matchable). ~~We could generalize this to **any** obligation that includes an unresolved inference variable, I suspect.~~ Moreover, there are cases where we don't encounter the error about an unconstrained inference variable until writeback:

```rust
fn main() {
    let x = [];
}
```

Therefore, the [error reporting for unknown types in writeback](https://github.com/rust-lang/rust/blob/a7f63d12a701f8d2c7b975ef605a50bb83318b90/src/librustc_typeck/check/writeback.rs#L585) ought to use the new helpers introduced in #39361

cc @cengizIO -- would you like to keep on working on this?

UPDATE: I was wrong to say this behavior applies any time we have an unresolved obligation. Sometimes it does, but not always.

**Comment by cengizIO** [comment]
Sure! Would love to help!

**Comment by cengizIO** [comment]
Well that wasn't as easy as I predicted 😝 

But I think it's finally done. 

Currently waiting for @nikomatsakis's approval
