### ISSUE TITLE
Incremental builds of staticlibs omit external libs (libcore, deps, etc)

### ISSUE THREAD

**Issue by gamozolabs** [rust-lang/rust#40034]
I wrote up a little test project to isolate the case. When build non-incrementally it successfully builds. When built incrementally it fails to link due to a missing reference to libcore. This issue only seems to occur when there are multiple files in a project, if the contents of fleeb.rs are integrated into lib.rs it builds just fine.

Sadly I'm not familiar enough with the internals of rustc yet to try to root cause it.

https://github.com/gamozolabs/rust_incremental_bug_maybe

**Comment by rkruppe** [comment]
cc @michaelwoerister

**Comment by gamozolabs** [comment]
Further it seems this issue only happens when lto=true. Forgot to include this info in the original issue.

-B

**Comment by jonhoo** [comment]
Interestingly enough, this problem also affects https://github.com/jwilm/alacritty. Compiles fine with incremental compilation turned off, but when it's enabled I get thousands of linking errors saying `undefined reference to` various functions in `core`, `std`, and `alloc`.

**Comment by pornel** [comment]
I have potentially the same problem. It happens frequently when using release builds, but oddly enough, not in debug builds.

> = note: Undefined symbols for architecture x86_64:
            "collections::str::_$LT$impl$u20$collections..borrow..ToOwned$u20$for$u20$str$GT$::to_owned::h08a3d146c463694a", referenced from:
                _$LT$collections..borrow..Cow$LT$$u27$a$C$$u20$B$GT$$GT$::into_owned::he0675971eb5116d2 in libmozjpeg-dd7ce246ca2126d4.rlib(mozjpeg-dd7ce246ca2126d4.collections-borrow.volatile.o)
            > "core::fmt::num::_$LT$impl$u20$core..fmt..Display$u20$for$u20$i32$GT$::fmt::hbe590fcca6b93469", referenced from:
                mozjpeg::errormgr::PanicingErrorMgr::panic_error_exit::hbb39fb4904e56816 in libmozjpeg-dd7ce246ca2126d4.rlib(mozjpeg-dd7ce246ca2126d4.mozjpeg_sys.volatile.o)
> …
>             "lcms2::profile::_$LT$impl$u20$lcms2..Profile$GT$::new_icc::h522828e4ca0ccfa7", referenced from:
                load_image::png::_$LT$impl$u20$load_image..loader..Loader$GT$::load_png::h16040172d52c757d in libload_image-f8cddceb9933ae99.rlib(load_image-f8cddceb9933ae99.load_image-loader.o)
> …
>             "___rust_allocate", referenced from:
                _$LT$alloc..raw_vec..RawVec$LT$T$GT$$GT$::double::h311abe36b71fcc64 in xxx-bce34e70fd36ec1e.alloc-raw_vec.volatile.o
                _$LT$alloc..raw_vec..RawVec$LT$T$GT$$GT$::double::hed3b04343805c4a1 in xxx-bce34e70fd36ec1e.alloc-raw_vec.volatile.o
                _$LT$alloc..raw_vec..RawVec$LT$T$GT$$GT$::reserve::h25e8833868f52d0d in xxx-bce34e70fd36ec1e.alloc-raw_vec.volatile.o
> …
>            "_rust_eh_personality", referenced from:
                Dwarf Exception Unwind Info (__eh_frame) in xxx-bce34e70fd36ec1e.alloc-arc.volatile.o
                Dwarf Exception Unwind Info (__eh_frame) in xxx-bce34e70fd36ec1e.c_vec.volatile.o
                Dwarf Exception Unwind Info (__eh_frame) in xxx-bce34e70fd36ec1e.clap-app.volatile.o
                Dwarf Exception Unwind Info (__eh_frame) in xxx-bce34e70fd36ec1e.clap-args-arg.volatile.o

**Comment by daboross** [comment]
I'm getting this with just regular binaries (not making staticlib), whenever using both `lto` and `CARGO_INCREMENTAL=1`.

**Comment by alexcrichton** [comment]
Today when compiling incrementally with LTO you get "error: can't perform LTO when compiling incrementally", so I'm going to close this

**Comment by MaikKlein** [comment]
I am getting this error even without `lto` pretty often. `cargo clean` temporarily solves this.

**Comment by michaelwoerister** [comment]
@MaikKlein Do you have a test case that re-produces the problem on the latest nightly?

**Comment by michaelwoerister** [comment]
@MaikKlein That makes sense. Thanks for opening the more targeted issue!
