### ISSUE TITLE
Poor user experience installing Rust on Windows 7

### ISSUE THREAD

**Issue by mark-summerfield** [rust-lang/rust#40054]
I tried to install Rust on Windows 7.
I downloaded rustup-init.exe and ran it, but it told me I needed the
MSVC++ Build Tools. So I downloaded visualcppbuildtools_full.exe from
Microsoft's site and ran it, but it told me I needed at least .Net
Framework 4.5.1. So I downloaded NDP451-KB2859818-Web.exe from Microsoft's
site and ran it. This worked, so I then ran visualcppbuildtools_full.exe
which also worked and then ran rustup-init.exe.
But during rustup-init.exe's execution it popped up an error message
saying I needed MSVCR120.dll. I got an official link for this from the rust IRC channel and after installing it rust & cargo seem to be working.

But having to install 3 Microsoft exe files -- all found in different places on the Microsoft site is a poor user experience. Surely the installer could be smarter about its dependencies and grab what it needs that's missing?

**Comment by leonardo-m** [comment]
There is also the Windows-GNU channel.

**Comment by mark-summerfield** [comment]
Sure, but that won't help with people building rust applications that need to access third-party DLLs built with the MSVC toolchain. And is a bit besides the point. Rust is really easy to install on Linux and does a local install that doesn't interfere with anything else so all you need to do is add it to your PATH. Ironically I'm happy to build things on Linux but I hate building on WIndows (and I'm not alone in that) so for Windows would expect a smooth and easy installation process.

**Comment by steveklabnik** [comment]
Hi @mark-summerfield thanks for this report! We do want to make sure things are smooth on windows.

However, this report would be better filed on rustup itself: https://github.com/rust-lang-nursery/rustup.rs/ would you mind re-filing over there, please? Thank you!

**Comment by mark-summerfield** [comment]
Done: https://github.com/rust-lang-nursery/rustup.rs/issues/961
