### ISSUE TITLE
with asmjs target, argument is zero'd if fn returns *mut str

### ISSUE THREAD

**Issue by donhcd** [rust-lang/rust#40068]
In some cases, the argument to my rust function gets to be read as 0 when I pass a non-zero argument to it in javascript. It definitely happens when the return type is `*mut str` but not when it is `*mut u8`.

main.rs:
```
#[link_args = "-s EXPORTED_FUNCTIONS=['_wat7','_wat9']"]
#[link_args = "--memory-init-file 0"]
#[link_args = "-g1"]
#[link_args = "-s DISABLE_EXCEPTION_CATCHING=1"]
#[link_args = "-s ASSERTIONS=1"]
#[link_args = "-s ELIMINATE_DUPLICATE_FUNCTIONS=1"]
#[link_args = "--llvm-lto 1"]
#[link_args = "-Oz"]
extern "C" {}

fn main() {}

#[no_mangle]
pub extern "C" fn wat7(p: *mut str) -> *mut str {
    println!("input: {:?}", p);
    p
}
#[no_mangle]
pub extern "C" fn wat9(p: *mut str) -> *mut u8 {
    println!("input: {:?}", p);
    p as *mut u8
}
```

chrome debugger console:
![screen shot 2017-02-23 at 4 44 45 pm](https://cloud.githubusercontent.com/assets/902007/23285647/6b6a4930-f9e7-11e6-8a99-82dedb8d0792.png)

I expected the two functions to have identical behavior.

## Meta

`rustc --version --verbose`:
```
rustc 1.17.0-nightly (0f34b532a 2017-02-21)
binary: rustc
commit-hash: 0f34b532af590d25e9178f87c620931dd671cc2e
commit-date: 2017-02-21
host: x86_64-apple-darwin
release: 1.17.0-nightly
LLVM version: 3.9
```

**Comment by cramertj** [comment]
`*mut str` is a fat pointer since `str` is unsized, so it takes up more than just a single word.

**Comment by donhcd** [comment]
hm, I didn't know about fat pointers. I don't quite see the connection with the behavior I'm seeing though

**Comment by cramertj** [comment]
By calling the function with a single integer when it's expecting a fat pointer (two integers) you're essentially lying to JavaScript about the type signature of the function. When calling Rust functions from JavaScript without using `ccall`/`cwrap` or `Runtime.dynCall` (my preferred methods), use [this guide to calling C/C++ "directly" from JavaScript.](https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#interacting-with-code-direct-function-calls)

**Comment by donhcd** [comment]
Yes, I've read that - I was attempting to make a minimal example so I didn't use `cwrap` and I made the argument a `*mut str`. I'm pretty sure the same thing happens if the argument is a `*mut u8` or any non-fat pointer.

I think I understand what you're saying about lying about the type signature, but I don't see how that leads the behavior I'm seeing, where in one case the argument is read to be 0 and in the other case it is read to be 1234.

**Comment by cramertj** [comment]
Returning `*mut str` directly isn't possible (AFAIK) because it isn't the same size as any of the accepted types ("number", "string" or "array") which are all pointer sized.

What I suspect is happening is that Rust is expecting two registers / stack slots to be used for the return value, except that JavaScript only thinks one of those is for the return value. This is causing your arguments to be in the wrong registers / stack slots.

**Comment by cramertj** [comment]
Bottom line: values passed between JavaScript and Rust should be 32-bit. Passing objects of other sizes directly isn't supported. You have to pass pointers to them, or pass them as multiple 32-bit arguments.

**Comment by donhcd** [comment]
thanks a ton for explaining @cramertj!

do you think it'd make more sense to make an bug that goes something like this? "rustc should error if you try to compile to asmjs rust functions that take non-32-bit args and return non-32-bit values"

**Comment by cramertj** [comment]
@donhcd No problem. I agree, a warning would be nice. However, I'm not sure how this would work in practice. Accepting large arguments is only an issue for functions that are called from JavaScript. In general, it's perfectly okay to have an extern function that accepts larger arguments, and there are many perfectly legitimate reasons for doing so (even when targeting asm.js).

**Comment by tlively** [comment]
@alexcrichton Besides offering the explanation given above, I'm not sure there's anything to be done about users manually calling from JS into their Rust modules and getting burned by unintuitive ABI signatures. I think this issue can be closed.
