### ISSUE TITLE
Only subset of errors printed

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#40067]
When trying to add a gate test for #40025 I saw that rustc only prints a subset of errors. See [this](https://play.rust-lang.org/?gist=5708488205bd08613ab6fa4c38a469ec&version=nightly&backtrace=0) example to reproduce. It only prints you two errors, while it should print 4. If you comment out the FOO and BAR parts, it will print the other two, but never all errors the same time.

I've worked around this issue in #40025 by using revisions, but that's not a really nice solution.

If this is done to not overwhelm users with a wall of text or something (which is clearly not working well here, 4 errors are nothing bad) then it should still be turned off for json output. Or at least some special flag should be added to print all errors, and it should be used for the rustc test suite runners.

**Comment by Mark-Simulacrum** [comment]
The example given prints 4 errors today so I guess this has been fixed? I don't really know. Closing though since at least this particular case seems fixed.
