### ISSUE TITLE
Compiler error depending on whether a type alias or the trait it aliases is used.

### ISSUE THREAD

**Issue by cpralea** [rust-lang/rust#40075]
Depending on whether a type alias is used, the following code generates an error that has to do with compiler's inability to infer lifetime (https://is.gd/z3weMW).

```
trait MyTrait<'a, T> {}
struct MyStruct {}
type MyAlias<'a> = MyTrait<'a, MyStruct>;

struct X {}
struct Y<'a> {
    x: &'a X,
}

impl X {
    fn f<'a>(&'a self) -> Y<'a> {
        Y { x: self }
    }
}
impl<'a> MyTrait<'a, MyStruct> for Y<'a> {}

fn g<'a>(_: &MyAlias<'a>) {}
fn h<'a>(p: &'a X) {
    g(&p.f());
}

fn main() {}

```

`error[E0495]: cannot infer an appropriate lifetime for autoref due to conflicting requirements`

However, if the underlying trait is used to define the type of the g() function parameter instead of the alias, no error is generated by the compiler (https://is.gd/m7P4fM).

**Comment by Mark-Simulacrum** [comment]
The type alias I believe resolves to `MyTrait<'a, MyStruct> + 'static` which leads to this problem. @rust-lang/compiler Is this expected?

**Comment by cjgillot** [comment]
Closing as expected behaviour per https://doc.rust-lang.org/reference/lifetime-elision.html#default-trait-object-lifetimes.
