### ISSUE TITLE
Explain difference between nightly build and stable

### ISSUE THREAD

**Issue by evelynmitchell** [rust-lang/rust#40079]
Add mention of differences between nightly build and stable:

      skade (#rust-docs): "I see people constantly falling into the trap that "nightly is just stable with features" (like, LLVM assertions activated in nightly, adding to compile times), well, there's also misconceptions about the level of stability features have (like, some have:  "never") written next to them, etc., also that there are two kind of feature flags and codegen features usually hide behind -Z

**Comment by steveklabnik** [comment]
We do have some of this today https://doc.rust-lang.org/stable/book/nightly-rust.html

It's moving out though, so the book will be entirely stable.

**Comment by steveklabnik** [comment]
doc team triage: p-medium, still need to come up with a plan.

**Comment by steveklabnik** [comment]
@evelynmitchell the book is now in its own repo, over at https://github.com/rust-lang/book/issues/new

Would you mind re-opening this over there? I'd like to figure out how to fit it into the second edition of the book. Thank you!

**Comment by evelynmitchell** [comment]
https://github.com/rust-lang/book/issues/559 opened
This one can now be closed.
