### ISSUE TITLE
Reference doc: table of contents within a chapter

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#40087]
It looks like https://doc.rust-lang.org/nightly/reference.html hasn’t been updated yet as of this writing, but in my local copy of the docs `reference.html` says “We've split up the reference into chapters. Please find it at its new home here.” with a link to `reference/index.html`.

This new format has a side bar with a table of content, but that ToC has coarser granularity than it used to. As far as I can tell, it has a link for each “chapter” (part of the book that requires navigation to another URL), but I can’t find a ToC for sections within a chapter. `reference/expressions.html` for example has many sub-sections, to a per-chapter ToC would help a lot.

This is probably a feature request for tool that generates this kind of documentation, but I’m not sure what it is. I’ve vaguely heard of rustboot and mdbook, is this one on these? Are they related? Which issue tracker should be used?

CC @steveklabnik

**Comment by frewsxcv** [comment]
Relevant PR: https://github.com/rust-lang/rust/pull/39855

**Comment by steveklabnik** [comment]
It's mdbook, and yes, it would have to be filed there, I think.

Soon, we'll be pulling the reference out into its own repo, so this bug would be filed there.

**Comment by steveklabnik** [comment]
moved https://github.com/rust-lang-nursery/reference/issues/15
