### ISSUE TITLE
Indexing via `[v]` does not cast fn items to fn pointers

### ISSUE THREAD

**Issue by aidanhs** [rust-lang/rust#40085]
```
use std::ops::Index;
fn bar() {}
static UNIT: () = ();
struct S;
impl Index<fn()> for S {
    type Output = ();
    fn index(&self, f: fn()) -> &() { f(); &UNIT }
}
fn main() {
    *S.index(bar);
    // S[bar];
    // ^^^^^^ expected fn pointer, found fn item
}
```
https://is.gd/R97Dc7

The docs for `Index` (https://doc.rust-lang.org/std/ops/trait.Index.html) say:

> `container[index]` is actually syntactic sugar for `*container.index(index)`

but the error above indicates that this isn't true.

**Comment by est31** [comment]
Seems its not doing the coercion. This works:

```rust
    let b :fn() = bar;
    S[b];
```

**Comment by aidanhs** [comment]
Suspect it has something to do with this line - https://github.com/rust-lang/rust/blob/1.15.1/src/librustc_typeck/check/mod.rs#L3978

Going to try and work on a patch.
