### ISSUE TITLE
Allow proc-macro crates to export macro_rules macros

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#40090]
In rustc 1.17.0-nightly (413a975e3 2017-02-23), this

```rust
#![crate_type = "proc-macro"]

#[macro_export]
macro_rules! foo {
    () => {}
}
```

causes a compiler error:

```
error: cannot export macro_rules! macros from a `proc-macro` crate type currently
```

As far as I understand, proc-macro crates can currently only export procedural macros because when cross-compiling they’re compiler for the host whereas "normal" crates are compiler for the target, and items such as functions or types defined in a proc-macro crate would also need to be compiler for the target when used (through a dependency) on a "normal" crate. But this is not a problem for `macro_rules` which is purely compile-time.

So it seems that lifting this restriction for `macro_rules` might require less implementation effort than lifting it for every kind of item?

**Comment by abonander** [comment]
Do plugin crates allow exporting macros? The implementation is similar.

**Comment by jseyfried** [comment]
cc @nrc

**Comment by SimonSapin** [comment]
I’ve realized that I can do this the other way around, which is even better: re-export procedural macros from a library crate:

```rust
// In cssparser’s lib.rs
#[macro_use] extern crate cssparser_macros;
pub use cssparser_macros::*;
```

Crates using this library only need one `extern crate` line:

```rust
// Import both cssparser_macros::* and macro_rules! macro exported by cssparser itself.
#[macro_use] extern crate cssparser;
```

-----

Although it would be nice for this issue to be fixed eventually, for me the above removes any desire to see it prioritized.

**Comment by jseyfried** [comment]
I'm not sure this is a good idea in the first place -- since we don't allow exporting an item (e.g. `pub fn`) then I don't think we should allow exporting a `macro_rules!` either for symmetry.

Eventually, we might allow exporting arbitrary items, but we'll probably need a story for phases first (quite a ways down the road).
