### ISSUE TITLE
Consider checking for formattee errors in ToString::to_string and format!()

### ISSUE THREAD

**Issue by nox** [rust-lang/rust#40103]
In both `ToString` for `T: Display` and `format!()`, it is assumed that no `Display` implementation will ever return `Err(_)` because none of the methods of `Write` for `String` do.

Given the `Display` trait does not document that it should not fail on its own, I think both `ToString` for `T: Display` types and `format!()` should unwrap the calls to `Write::write_fmt` instead of completely ignoring their result.

**Comment by SimonSapin** [comment]
I think it is an error for an implementation of `Display` (or other trait of that family) to return `Err` for a reason other than because `Formatter::write_*` did. If it’s not in the documentation, we should add it.

**Comment by SimonSapin** [comment]
> I think it is an error

Error as in programmer mistake, a bug. Not a `Result::Err(_)`. (Overloaded terminology…)

**Comment by ollie27** [comment]
It's documented [here](https://doc.rust-lang.org/nightly/std/fmt/index.html#formatting-traits):

> Formatting implementations should ensure that they propagate errors from the Formatter (e.g., when calling write!) however, they should never return errors spuriously. That is, a formatting implementation must and may only return an error if the passed-in Formatter returns an error. This is because, contrary to what the function signature might suggest, string formatting is an infallible operation. This function only returns a result because writing to the underlying stream might fail and it must provide a way to propagate the fact that an error has occurred back up the stack.

**Comment by nox** [comment]
@ollie27 Oh thanks.

**Comment by SimonSapin** [comment]
@alexcrichton, you replaced `.unwrap()` with `let _ =` in #14115 / https://github.com/rust-lang/rust/commit/1de4b65d2a88e88201026485f9622916c5717555#diff-1d71e11e042c3b99e8acdff366825e70L552, but it’s part of a larger commit and the commit message doesn’t mention this. Do you remember why?

**Comment by alexcrichton** [comment]
@SimonSapin that was also three years ago as part of a 6kloc PR. Unfortunately no, I don't remember why that particular line is that way. It was likely because at the time I assumed that no one would ever manufacture `fmt::Error`, I was only considering I/O errors translating to `fmt::Error`
