### ISSUE TITLE
nightly is broken

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#40106]
```
cmr@roger ~/s/rls> rustup update nightly
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
error: server sent a broken manifest: missing package for component rust-analysis-aarch64-apple-ios
info: caused by: package not found: 'rust-analysis'
```

**Comment by KodrAus** [comment]
Maybe related to https://github.com/rust-lang-nursery/rustup.rs/issues/268

**Comment by est31** [comment]
See also https://github.com/rust-lang/rust/pull/40026#issuecomment-282531359

**Comment by SirVer** [comment]
Does this take time to roll out? I still see the same error.

**Comment by est31** [comment]
@SirVer yes. this specific one nightly will probably always be broken (unless the manifest gets removed from static.rlo), but the future nightlies wont be broken. It will take one day until it will be available, maybe more if the build fails. This page can be used to check whether a new nightly is available: http://rusty-dash.com/nightlies

**Comment by TomasHubelbauer** [comment]
For the record, one can go `rustup install nightly-2017-02-25` to get around the latest nightly not working. Took a bit for me to realize, so I thought I'd share.
