### ISSUE TITLE
Unclear if From<Ipv4Addr> for u32 is network order or not

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#40118]
The conversion traits are implemented for conversion between `u32` and `Ipv4Addr`, but it is not clear what byte order is used.

**Comment by sfackler** [comment]
It is network order, but that should be documented on the impl.

**Comment by steveklabnik** [comment]
doc team triage: this would make a great first PR. I am happy to mentor anyone who wants to tackle this issue.

**Comment by z1mvader** [comment]
@steveklabnik I'd like to, is someone else working on this?

**Comment by steveklabnik** [comment]
@z1mvader nope, please do! Ping me if you need any help 😄
