### ISSUE TITLE
Bad diagnostics/docs around read_dir and filtering for type

### ISSUE THREAD

**Issue by killercup** [rust-lang/rust#40127]
I was (offline) writing a few lines of code to traverse a directory and find all subdirectories (find fixtures for tests). This was harder than expected, as I wanted to not write a for-loop for this.

Especially frustrating was this diagnostics message:

```
error[E0507]: cannot move out of borrowed content
 --> /Users/pascal/Projekte/brendan/hfst-rs/tests/all.rs:6:21
  |
6 |         .filter(|x| x.unwrap().path().is_dir());
  |                     ^ cannot move out of borrowed content
```

I expected to get a suggestion there, or at least a bit more context (where what was borrowed). (I think a problem is that `std::fs::DirEntry` does not implement `Clone`.)

At the same time, this is also a pretty basic thing, which would be a good example to add to `std::fs::read_dir`.

By the way, what I ended up with is:

```rust
let tests: Vec<_> = read_dir("tests/fixtures/").unwrap()
    .filter(|x| x.iter().map(|x| x.path().is_dir()).next().unwrap())
    .filter_map(|x| x.ok())
    .collect();
```

I'm sure there are nicer versions.

**Comment by TimNN** [comment]
The issue here is that `x` is an `&Result<DirEntry, Error>` I think. Which means that the real problem is, I guess, that `cannot move out of borrowed content` is especially unhelpful if the type of `x` is non obvious from the context. In this case one needs to know the exact signature of `.filter`.

> I'm sure there are nicer versions.

I think something like `.filter(|x| x.as_ref().unwrap().path().is_dir())` should work (or do a `.map(|x| x.unwrap())` / `.filter_map(|x| x.ok())` first and then `.filter(|x| x.path().is_dir())`).

**Comment by Mark-Simulacrum** [comment]
This code allows reproducing the original error:

```
use std::fs::read_dir;

fn foo() {
    let tests: Vec<_> = read_dir("tests/fixtures/").unwrap()
        .filter(|x| x.unwrap().path().is_dir())
        .collect();
}
```

**Comment by estebank** [comment]
The output is now

```
error[E0507]: cannot move out of `*x` which is behind a shared reference
 --> src/main.rs:5:21
  |
5 |         .filter(|x| x.unwrap().path().is_dir())
  |                     ^
  |                     |
  |                     move occurs because `*x` has type `std::result::Result<std::fs::DirEntry, std::io::Error>`, which does not implement the `Copy` trait
  |                     help: consider borrowing the `Result`'s content: `x.as_ref()`
```
