### ISSUE TITLE
SIMD operations in Rust? 

### ISSUE THREAD

**Issue by acterhd** [rust-lang/rust#40140]
Hello, where SIMD for modern rust?

**Comment by frewsxcv** [comment]
https://github.com/rust-lang/rfcs/issues/1639

**Comment by Aatch** [comment]
See #27731.

Also, please be aware that the issue tracker is for, well, issues, not general support. Please use IRC, users.rust-lang.org and/or reddit.com/r/rust for these kinds of questions.
