### ISSUE TITLE
Slash (/) in diagnostic's path on Windows

### ISSUE THREAD

**Issue by KalitaAlexey** [rust-lang/rust#40149]
```
cargo new app
```

src/lib.rs: `mod f;`

src/f/mod.rs: `f`

```
cargo build
```

```
error: expected one of `!` or `::`, found `<eof>`
 --> src\f/mod.rs:1:1
```

It must be src\f **\\** mod.rs, but it is src\f **/** mod.rs

src/f/mod.rs: `mod g;`

src/f/g/mod.rs: `g`

```
cargo build
```

```
error: expected one of `!` or `::`, found `<eof>`
 --> src\f\g/mod.rs:1:1
```

**Comment by retep998** [comment]
Is some code in rustc somewhere hardcoding `/` instead of using `std::path::MAIN_SEPARATOR` (or just joining paths the normal way)?

**Comment by KalitaAlexey** [comment]
@retep998,
Probably it is.

**Comment by steveklabnik** [comment]
Seeing this myself.

**Comment by retep998** [comment]
Could it be the fault of this line? https://github.com/rust-lang/rust/blob/master/src/libsyntax/parse/parser.rs#L5148
```Rust
let secondary_path_str = format!("{}/mod.rs", mod_name);
```

**Comment by KalitaAlexey** [comment]
I suppose we need to add some tests to check it.

**Comment by radix** [comment]
@retep998 it's not just that, since I also see it for non-mod.rs cases.

**Comment by adchilds** [comment]
Looks like the issue @radix is seeing may be caused by https://github.com/rust-lang/rust/blob/master/src/libstd/sys_common/backtrace.rs#L265

**Comment by retep998** [comment]
So now someone just needs to write a PR to fix those two spots!

**Comment by laumann** [comment]
Would https://github.com/rust-lang/rust/blob/master/src/libsyntax/parse/parser.rs#L5307 also qualify?

**Comment by retep998** [comment]
@laumann Yes.

**Comment by laumann** [comment]
@retep998 Included
