### ISSUE TITLE
Debug implemented for __cdecl, but not for __stdcall

### ISSUE THREAD

**Issue by Dushistov** [rust-lang/rust#40158]
rustc 1.17.0-nightly (60a0edc6c 2017-02-26)

Such code compiles fine:

```rust
#[repr(C)]
#[derive(Debug)]
pub struct JNINativeInterface_ {
    pub GetVersion: ::std::option::Option<unsafe extern "C" fn(env:
                                                                   *mut ::std::os::raw::c_void)
                                              -> ::std::os::raw::c_int>,
}

fn main() {
}

```
But if I change **"C"** to **"stdcall"** then:

> error[E0277]: the trait bound `unsafe extern "stdcall" fn(*mut std::os::raw::c_v
> oid) -> i32: std::fmt::Debug` is not satisfied

**Comment by petrochenkov** [comment]
The reason: https://github.com/rust-lang/rust/issues/38848#issuecomment-270906268

**Comment by jethrogb** [comment]
Close this in favor of more general #40710?
