### ISSUE TITLE
long line breaks span note formatting

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#40157]
The note after line 5 is supposed to say `` `foo` dropped here while still borrowed``.

```rust
$ cargo script -e 'println!("{:?}", match { let foo = vec![1, 2]; foo.get(1) } { x => x });'
   Compiling expr v0.1.0 (file:///Users/alex/.cargo/.cargo/script-cache/expr-fbc7431f17311f94)
error: `foo` does not live long enough
 --> /Users/alex/.cargo/.cargo/script-cache/expr-fbc7431f17311f94/expr.rs:5:60
  |
5 | {println!("{:?}", match { let foo = vec![1, 2]; foo.get(1) } { x => x });}
  |  ----------------------------------------------------------^-------------d here while still borrowed
  |  |                                              |
  |  |                                              |
  |  |                                              borrow occurs here
  |  borrowed value needs to live until here
  |
  = note: this error originates in a macro outside of the current crate
```

cc @jonathandturner

**Comment by jonathandturner** [comment]
I have a sneaking suspicion that this will require detecting the case where we're about to overwrite the message.

**Comment by jonathandturner** [comment]
I'm not sure if we can detect the width of the terminal in a cross platform way.  If we can, maybe we can use that to factor in how we draw the message

**Comment by estebank** [comment]
I don't think this is a problem with terminal width, but rather a bug in the [positioning of the labels](https://github.com/rust-lang/rust/pull/37369/files#diff-4d5b8cff35812b800ff77376382671a7R510).
