### ISSUE TITLE
It is not obvious how to construct a path from components

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#40159]
The only really cross-platform method to construct a path, is to construct one from components. For example `os.path.join` is a well known way to do so in Python.

In Rust is not as obvious how to do that in a convenient manner. You could `push` components one-by-one into a `PathBuf`, but that sounds sort of inconvenient. There’s a 

```
impl<P: AsRef<Path>> FromIterator<P> for PathBuf
```

implementation exactly for that, but it is extremely difficult to discover. Perhaps what we need is a in-your-face example on `PathBuf` that explains the only really correct way to construct a multi-component PathBuf?

**Comment by durka** [comment]
Is `["a", "b"].iter().collect::<PathBuf>()` the best way?

**Comment by steveklabnik** [comment]
docs team triage: second @durka 's question, @nagisa , that's what you're referring to?

**Comment by nagisa** [comment]
That’s the only way to construct a path with arbitrary number of components in a single statement without reallocating for every component that I could find. The other approach is to use `Path::join`, which will allocate a new `PathBuf` every time it is called, and therefore is to be avoided for this purpose. `PathBuf::push` needs a statement for each component.

**Comment by durka** [comment]
Yeah let's put an example in the `Path` and `PathBuf` docs. `p.join("x").join("y").join("z")` sounds like a candidate for a Clippy lint.

**Comment by jdhorwitz** [comment]
I will start working on this today.
