### ISSUE TITLE
CStr::from_bytes_with_nul(b"\0") return value changes when compiling with LTO

### ISSUE THREAD

**Issue by aprilwade** [rust-lang/rust#40165]
When compiling with LTO enabled, CStr::from_bytes_with_nul(b"\0") returns an error. Without LTO, it returns Ok. The former result seems incorrect. The following terminal session should help illustrate:

```
% cat testing.rs
use std::ffi::CStr;
fn main()
{
    println!("{:?}", CStr::from_bytes_with_nul(b"\0"));
}

% rustc testing.rs -C opt-level=3 -C lto

% ./testing
Err(FromBytesWithNulError { _a: () })

% rustc testing.rs -C opt-level=3

% ./testing
Ok("")

% rustc --version
rustc 1.15.1 (021bd294c 2017-02-08)
```

**Comment by alexcrichton** [comment]
I believe this is an [upstream LLVM bug](https://bugs.llvm.org/show_bug.cgi?id=32124), unfortunately

**Comment by arielb1** [comment]
LLVM PR https://bugs.llvm.org/show_bug.cgi?id=32124

**Comment by Mark-Simulacrum** [comment]
The bug was fixed in LLVM recently; do we want to do a backport of their patch?

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rust-lang/rust/pull/47828
