### ISSUE TITLE
Failed to get sha256

### ISSUE THREAD

**Issue by Wetitpig** [rust-lang/rust#40172]
How to solve this?

failed to run: curl -s --retry 3 -Sf -o /data/data/com.termux/files/usr/tmp/tmplPjNRC.sha256 https://static.rust-lang.org/dist/2017-02-01/rust-std-beta-armv8-unknown-linux-gnueabihf.tar.gz.sha256

Thanks

**Comment by alexcrichton** [comment]
It looks like you're bootstrapping for a target that doesn't have a compiler, armv8-unknown-linux-gnueabihf. Did you mean aarch64-unknown-linux-gnu?

**Comment by Wetitpig** [comment]
No. Maybe my mahine is incompatible.

**Comment by MeinFuehrer** [comment]
If you're an experienced termux user you could unpack a rustc tarball manually and see why it doesn't work :) You will probably need the armv7 version.

**Comment by Wetitpig** [comment]
Let's see

**Comment by Mark-Simulacrum** [comment]
Yes, this is simply an unsupported platform so I don't think there's anything to fix here really.
