### ISSUE TITLE
add `abi_x86_interrupt` to the unstable book

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#40181]
see https://github.com/rust-lang/rust/issues/40180

I'm happy to help mentor anyone who wants to fix this issue.

**Comment by topecongiro** [comment]
Hello, I would like to work on this issue.

**Comment by jdhorwitz** [comment]
I would love to work on this and be mentored as well in case topecongiro can not.  Thank you!

**Comment by steveklabnik** [comment]
@jdhorwitz https://github.com/rust-lang/rust/pull/40191 got sent in, so maybe we can work together on some other issue? 😄 Just let me know, happy to help you help me.

**Comment by jdhorwitz** [comment]
@steveklabnik That would be great, thank you so much would love to work with you.

**Comment by steveklabnik** [comment]
@jdhorwitz Awesome. Maybe jump on IRC and message me? Or comment in another issue marked E-mentor? Whatever works 👍

**Comment by jdhorwitz** [comment]
@steveklabnik Awesome! What is your nick on IRC? Mine is jhorwitz

**Comment by steveklabnik** [comment]
same as github: steveklabnik
