### ISSUE TITLE
Bound required by coercion to trait object loses track of its origin

### ISSUE THREAD

**Issue by luser** [rust-lang/rust#40182]
I had a bug in [some code I was writing](https://gist.github.com/luser/859206ae83767bbea821e832993e8b1c), and it produced a very confusing (to me, at least) [error message](https://gist.github.com/luser/0394c335826de84b73d957a91488eecb).

The source of the error is that I had an if/else conditional where the if branch returned a `Box<Future<...>>` by doing `Box::new(some_future)` and the else branch returned a `Box<Future<...> + Send>` by doing `futures::ok(...).boxed()`, and some part of the type in the if branch was *not* `Send`, so the compiler complains about that. What was confusing to me is that I did not realize where the `Send` bound was coming from, so I spent a bunch of time spinning my wheels on it.

Here's a simpler set of code that produces the same error:
https://is.gd/Gl1Zon

The error is also much simpler when you don't have complicated type signatures involving `Future`, but that's just par for the course.

**Comment by eddyb** [comment]
So the reason this is a problem at all is because of "LUB coercion", where the compiler will try to reconcile if-else/match branches or array elements so they all have the same type, but it never shows all the spans of the expressions in question, because *there are two* (the expression to be coerced, and the expression the type to coerce *came from* - the latter of which is not always available in the compiler right now).

**Comment by eddyb** [comment]
cc @nikomatsakis @jonathandturner

**Comment by luser** [comment]
I forgot to mention, but thanks to @eddyb for listening to me complain on #rust-internals and suggesting the issue title. :)

**Comment by nikomatsakis** [comment]
Interesting. It seems entirely doable to track the information we need, but I think it's going to be tricky to find the best way to present it all.

**Comment by cjgillot** [comment]
Initial report now errors with
```
error[E0277]: `Rc<u32>` cannot be sent between threads safely
 --> src/main.rs:9:53
  |
9 |     let x = if b { Box::new(Rc::new(1u32)) } else { Box::new(0u32) as Box<dyn T + Send> };
  |                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `Rc<u32>` cannot be sent between threads safely
  |
  = help: the trait `Send` is not implemented for `Rc<u32>`
  = note: required for the cast to the object type `dyn T + Send`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground` due to previous error
```
