### ISSUE TITLE
Bizarre heisenbug on ioctl with unsafe rust

### ISSUE THREAD

**Issue by rlupton20** [rust-lang/rust#40196]
```
$ rustc --version
rustc 1.11.0

$ cargo --version
cargo 0.12.0 (built 2016-12-03)
```
(installed using nix on nixos 16.09 stable channel).

I've been playing with `libc` to construct a basic rust tun/tap driver so I can play around with network protocols, and noticed at some point after refactoring my little toy, my call to `ioctl` stopped working (returning a `-1` error rather than expected `0`).

I dropped back through my commits to find an early working version, and compared the values being passed to `ioctl` and verified that they were the same. Interestingly however, I noticed that adding a simple `println!` call before the `ioctl` on the previously succeeding version caused it to fail.

For instance:
```
fn main() {
    let mut ifreq : IfReq = IfReq::from_name("toytap").unwrap();
    ifreq.ifr_flags(IFFTAP | IFF_NO_PI);

    match OpenOptions::new().write(true).open("/dev/net/tun") {
        Ok(t) => {
            unsafe {
                let fd : c_int = t.into_raw_fd();
                let rc : i32 = ioctl(fd, TUNSETIFF, ifreq);
                println!("{}", rc);
            }
        }
        Err(e) => println!("Failed to open tun device: {}", e)
    }

}
```
prints `rc` out as `0`

while

```
fn main() {
    let mut ifreq : IfReq = IfReq::from_name("toytap").unwrap();
    ifreq.ifr_flags(IFFTAP | IFF_NO_PI);

    match OpenOptions::new().write(true).open("/dev/net/tun") {
        Ok(t) => {
            unsafe {
                let fd : c_int = t.into_raw_fd();
                println!("One day I'll catch you!");
                let rc : i32 = ioctl(fd, TUNSETIFF, ifreq);
                println!("{}", rc);
            }
        }
        Err(e) => println!("Failed to open tun device: {}", e)
    }

}
```
prints out `rc` as `-1`. A real life heisenbug!

I can see there is a possibility this is an issue with `libc`, yet I somehow doubt it. Also, I understand there may well be quirks with unsafe rust which I've blindly stumbled into here, but I would only expect that if I were to start mangling bits of memory explicitly, and the above just doesn't look suspicious enough to me.

Unfortunately this means my nice (to my eye anyway) rust code isn't working, so I'll give my little evening-hack version below if anyone is interested in reproducing it. It assumes a TAP device named `toytap` to be available for use by the user - adjust as necessary.

```
extern crate libc;

use std::fs::OpenOptions;
use std::os::unix::io::IntoRawFd;
use libc::{c_int, c_char, c_short, ioctl, IF_NAMESIZE};

static IFFTAP : c_short = 2;
static IFF_NO_PI : c_short = 4096;
static TUNSETIFF : u64 = 1074025674; // Need to check this

#[repr(C)]
struct IfReq {
    ifr_name : [c_char; IF_NAMESIZE],
    union : [u8; 24]
}

impl IfReq {
    fn ifr_flags(&mut self, flags : c_short) {
        // Zero the flags and copy the two bytes of flags
        self.union = [0; 24];
        self.union[0] = flags as u8;
        self.union[1] = (flags << 8) as u8;
    }

    fn new() -> Self {
        let name : [c_char ; IF_NAMESIZE] = [0 as c_char ; IF_NAMESIZE];
        IfReq {
            ifr_name : name,
            union : [0 ; 24]
        }
    }

    fn from_name(name : &str) -> Option<IfReq> {
        if name.len() >= IF_NAMESIZE {
            None
        }
        else {
            let mut ifreq : IfReq = IfReq::new();
            for (i,c) in name.as_bytes().iter().enumerate() {
                ifreq.ifr_name[i] = *c as c_char;
            }
            Some(ifreq)
        }
    }
}



fn main() {
    let mut ifreq : IfReq = IfReq::from_name("toytap").unwrap();
    ifreq.ifr_flags(IFFTAP | IFF_NO_PI);

    match OpenOptions::new().write(true).open("/dev/net/tun") {
        Ok(t) => {
            unsafe {
                let fd : c_int = t.into_raw_fd();
                // INSERT PRINT STATEMENT HERE
                let rc : i32 = ioctl(fd, TUNSETIFF, ifreq);
                println!("{}", rc);
            }
        }
        Err(e) => println!("Failed to open tun device: {}", e)
    }

}

```

**Comment by rlupton20** [comment]
Looking in `journalctl -xe` suggests it really is failing when returning `-1`, and that when returning `0` it really is succeeding.

**Comment by sfackler** [comment]
What does strace output look like?

**Comment by ishitatsuyuki** [comment]
Pro tip:
* try upgrading Rust.
* try valgrind.

**Comment by rlupton20** [comment]
I'll try these things this evening (strace and upgrade were in my mind, valgrind is a sensible suggestion).

**Comment by rlupton20** [comment]
Reproduces with `rustc` version `1.15.1`. Will look into the details now.

**Comment by rlupton20** [comment]
(Just using this as a record so I can do the analysis)

`strace` of successful:
```
sigaltstack({ss_sp=0x7fe1f6861000, ss_flags=0, ss_size=8192}, NULL) = 0
open("/dev/net/tun", O_WRONLY|O_CLOEXEC) = 4
ioctl(4, FIOCLEX)                       = 0
ioctl(4, TUNSETIFF, 0x7ffdc5395d90)     = 0
write(1, "0\n", 20
)                      = 2
sigaltstack({ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=8192}, NULL) = 0
munmap(0x7fe1f6861000, 8192)            = 0
exit_group(0)                           = ?
+++ exited with 0 +++
```

`strace` of unsuccessful:
```
open("/dev/net/tun", O_WRONLY|O_CLOEXEC) = 4
ioctl(4, FIOCLEX)                       = 0
write(1, "One day I'll catch you!\n", 24One day I'll catch you!
) = 24
ioctl(4, TUNSETIFF, 0)                  = -1 EFAULT (Bad address)
write(1, "-1\n", 3-1
)                     = 3
sigaltstack({ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=8192}, NULL) = 0
munmap(0x7fd76aa0f000, 8192)            = 0
exit_group(0)                           = ?
+++ exited with 0 +++
```

the `ioctl` has very different 3rd input in each case.

**Comment by rlupton20** [comment]
Ah and now I see the problem, and it's my error! Damn! I was passing in my `ifrreq` structure when I should have been passing in a pointer to it.

Well, now, there is an introduction to unsafe rust... Can't believe I missed that!

I'm just going to go and hide in a dark corner. It's not entirely clear why this should be zero in the above failure case, but it's quite clear this is the error.
