### ISSUE TITLE
LLVM ERROR compiling Clap on 1.17.0 Nightly

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#40214]
As reported here:
https://users.rust-lang.org/t/mandel-rust-v0-4/7481/3

Compiling this little project:
https://github.com/willi-kappler/mandel-rust

On x86_64-pc-windows-gnu, rustc 1.17.0-nightly, 691eba135 2017-03-01:

Instruction does not dominate all uses!
  %27 = load i32, i32* %26, !range !2
  %71 = icmp eq i32 %27, 60
LLVM ERROR: Broken function found, compilation aborted!
error: Could not compile `clap`.

Further notes:

> I can confirm this on MacOS and Linux. Stable and beta ran fine, but nightly has problems on both platforms

**Comment by TimNN** [comment]
Only happens with `--release` for me on macOS.

**Comment by nagisa** [comment]
First bad: `1572bf104 2017-02-25`
Last good: `08230775a 2017-02-24`

[Changes](https://github.com/rust-lang/rust/compare/08230775a...1572bf104)

**Comment by TimNN** [comment]
Note that while the error does not occur when everything is compiled in debug mode, it does occur when clap itself is compiled with `-Copt-level=0` but all the dependencies are `-Copt-level=3`.

**Comment by nagisa** [comment]
It also sounds a lot like an LLVM bug, since the issue happens during LLVM passes – should check if LLVM 4.0 works or not. Us giving LLVM more information is most likely the trigger.

**Comment by TimNN** [comment]
@nagisa: This also fails with LLVM 4.0

**Comment by nagisa** [comment]
Minimal-ish reproducer:

```rust
pub fn name(mut chars: Chars<'static>, c: char) -> bool {
    while let Some(c) = chars.next() {
        if c == ']' {
            break;
        }
    }
    c == '['
}
```

Another interesting case is

```rust
pub fn name(mut chars: Chars<'static>, c: char) -> bool {
    while let Some(c) = chars.next() {
        if c == ']' {}
    }
    c == '['
}
```

Which ICEs:

```
error: internal compiler error: /checkout/src/librustc_trans/mir/operand.rs:189: use of _12 before def
```

**Comment by nagisa** [comment]
cc @cramertj

**Comment by nikomatsakis** [comment]
cc me

**Comment by cramertj** [comment]
Is this a dup of #40235? (Fixed in https://github.com/rust-lang/rust/pull/40242)

**Comment by nagisa** [comment]
It reproduces with the nightly I updated to yesterday so probably not?

**Comment by nagisa** [comment]
Reproduced, rather. I recommend trying to re-reproduce.

**Comment by cramertj** [comment]
@nagisa Doing that now. The easy way to check if you have the bugfix from #40242 is to see if this compiles (it did before the bugfix):

```rust
pub fn name(c: char) -> char {
    while let Some(t) = Some('[') {
        break;
    }
    t
}
```

**Comment by nagisa** [comment]
Seems to be fixed in master.

**Comment by cramertj** [comment]
That was what I found, too. Sorry, forgot to post my results.

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/issues/40214#issuecomment-285462234 does not reproduce on the current nightly. closing!
