### ISSUE TITLE
Cargo-vendor fails to link to libgit2 when compiling rust from source 

### ISSUE THREAD

**Issue by TyanNN** [rust-lang/rust#40228]
```
running: "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "install" "--force" "--verbose" "--debug" "--ver
s" "0.1.4" "cargo-vendor"
Running `/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage0/bin/rustc --crate-name libgit2_sys /tmp/portage/dev-lang/rust-9999/homedir/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.6/lib.rs --crate-type lib -g --cfg feature=\"https\" --cfg feature=\"ssh\" --cfg feature=\"curl\" --cfg feature=\"curl-sys\" --cfg feature=\"openssl-sys\" --cfg feature=\"libssh2-sys\" -C metadata=55dc646ad12fdaeb -C extra-filename=-55dc646ad12fdaeb --out-dir /tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj/debug/deps --emit=dep-info,link -L dependency=/tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj/debug/deps --extern libssh2_sys=/tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj/debug/deps/liblibssh2_sys-1c8426da8efdab7a.rlib --extern curl_sys=/tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj/debug/deps/libcurl_sys-1838572cde66848e.rlib --extern openssl_sys=/tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj/debug/deps/libopenssl_sys-e89179dab904d606.rlib --extern libz_sys=/tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj/debug/deps/liblibz_sys-57beb9d53e752aa8.rlib --extern libc=/tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj/debug/deps/liblibc-83c2bd88b43ecde3.rlib --cap-lints allow -L native=/tmp/portage/dev-lang/rust-9999/temp/cargo-install.FLHiZdEvovMj/debug/build/libgit2-sys-294bff880f16dcf0/out/lib -l static=git2 -L native=/usr/lib64 -L native=/usr/lib64 -L native=/usr/lib64`
error: could not find native static library `git2`, perhaps an -L flag is missing?

Build failed, waiting for other jobs to finish...
```
Also, it can't find libgit2 even if it's installed system-wide
It seems like it also can be reproduced with Arch PKGBUILD

**Comment by Randl** [comment]
https://github.com/gentoo/gentoo-rust/issues/230

**Comment by alexcrichton** [comment]
Is this suspected to be a Cargo bug? Or a packaging bug?

If the former, could you provide some more information about how to reproduce?

**Comment by TyanNN** [comment]
@alexcrichton, It seems like what happens is that cargo's `build.rs` can't find libgit2 (which is actually a submodule) due to disabling submodules in ebuild/pkgbuild (because they have their own ways to deal with them)

**Comment by jmesmon** [comment]
Related to the system-wide libgit2 usage: alexcrichton/git2-rs#68

If libgit2's ABI has stabilized enough, the packaging scripts could export that env variable to enable use of pkg-config. (And if it has stabilized, it's likely pkg-config should be enabled by default). We do this export in [meta-rust's cargo recipe](https://github.com/meta-rust/meta-rust/blob/master/recipes-devtools/cargo/cargo.inc#L17-L18)

Ideally, we'd have a better way of selecting and prioritizing methods for "locating" libraries than an env var, though.

**Comment by Randl** [comment]
Using systemwide version of libgit2, at least aster checking the version, sounds like a sane thing to do

**Comment by TyanNN** [comment]
It _seems_ like this can be fixed by running `make dist` after `make`, was `make dist` inroduced recently?
