### ISSUE TITLE
How to set environment variables on windows?

### ISSUE THREAD

**Issue by XiuyeXYE** [rust-lang/rust#40223]
# I compile the "xxx.rs" file by command that is "rustc xxx.rs -L C:\rust\lib"
# If "-L C:\rust\lib" is not there,the errors will come on your "cmd" screen.That is "error[E0463]: can't find crate for `std` error: aborting due to previous error"
# Are there some default environment variables on windows which can be set?
# I want to compile the source file in a short command that is "rustc xxx.rs".Is it not brief?

**Comment by niconii** [comment]
Normally `rustc xxx.rs` should work. It sounds like your installation of Rust is broken in some way. Could you try reinstalling Rust?

**Comment by retep998** [comment]
It looks like you manually extracted the rustc and rust-std components instead of installing Rust the recommended way using rustup. https://rustup.rs/

**Comment by XiuyeXYE** [comment]
@niconii 
@retep998 
Can it set the environment variables pointing to lib directory to compile the source file and link obj files with libraries on windows?
It's like vc++ compiler linking the some ".obj" files through environment variable "lib" that point out library directory.

**Comment by retep998** [comment]
If you install Rust correctly, rustc will automatically find the standard library correctly. There's no environment variables to fix this, you just need to install Rust correctly. Please remove your existing Rust installation and install Rust using rustup.

**Comment by XiuyeXYE** [comment]
@retep998 
I solved this small problem about linking defualt library automatically.
Rustc can automatically find the standard library,but it has to create the lib path(directory) like "lib\rustlib\i686-pc-windows-msvc\lib" in rust root path on windows.It can compile the source file with a short command "rustc xxx.rs".
