### ISSUE TITLE
Spurious failures in sccache

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#40240]
# Outstandling failures:

### Failed to spawn child broken pipe

~~maybe fixed in https://github.com/rust-lang/rust/pull/40809?~~

* https://travis-ci.org/rust-lang/rust/jobs/210449425
* https://travis-ci.org/rust-lang/rust/jobs/210356090
* https://travis-ci.org/rust-lang/rust/jobs/210674231
* https://travis-ci.org/rust-lang/rust/jobs/217614672
* https://travis-ci.org/rust-lang/rust/jobs/217513855
* https://travis-ci.org/rust-lang/rust/jobs/217609418

```
error: failed to execute compile
caused by: failed to spawn child
caused by: Broken pipe (os error 32)
make[3]: *** [bin/llvm-config] Error 2
```

Notes:

* ~~no theories~~ maybe https://github.com/carllerche/mio/issues/582?
* Always OSX so far
* Both 32 and 64 bit 
* presumably happens [here](https://github.com/mozilla/sccache/blob/5c77c337356951cb7bde5c40d6845f459dfc8312/src/compiler/compiler.rs#L639-L645)

### Error 254

Suspected bug in sccache. Hidden by https://github.com/mozilla/sccache/pull/82 by accident. Sccache update in https://github.com/rust-lang/rust/pull/40676

maybe fixed in https://github.com/rust-lang/rust/pull/40809?

* https://travis-ci.org/rust-lang/rust/jobs/208053065
* https://travis-ci.org/rust-lang/rust/jobs/208060953
* https://travis-ci.org/rust-lang/rust/jobs/209158635
* https://travis-ci.org/rust-lang/rust/jobs/209740993
* https://travis-ci.org/rust-lang/rust/jobs/213667930

notes:

* [One job](https://travis-ci.org/rust-lang/rust/jobs/213667930) failed nul bytes in env, args, or program passed to `Command` when creating preprocessor. This seems crazy. Memory corruption?
* OSX or Linux so far, no Windows.
* Most indicate just one compilation failing, the last log indicates the entire server crashed w/ a segfault or something

# Fixed failures

### Unexpected EOF

Hoping to be fixed by https://github.com/mozilla/sccache/pull/79

* https://travis-ci.org/rust-lang/rust/jobs/210484803
* https://travis-ci.org/rust-lang/rust/jobs/207425298
* https://travis-ci.org/rust-lang/rust/jobs/207606309
* https://travis-ci.org/rust-lang/rust/jobs/208643512
* https://travis-ci.org/rust-lang/rust/jobs/208893289
* https://travis-ci.org/rust-lang/rust/jobs/208849166
* https://travis-ci.org/rust-lang/rust/jobs/209162867
* https://travis-ci.org/rust-lang/rust/jobs/210063204
* https://travis-ci.org/rust-lang/rust/jobs/210145670
* https://travis-ci.org/rust-lang/rust/jobs/210484803
* https://travis-ci.org/rust-lang/rust/jobs/210685018
* https://travis-ci.org/rust-lang/rust/jobs/211605305
* https://travis-ci.org/rust-lang/rust/jobs/211341835
* https://travis-ci.org/rust-lang/rust/jobs/211214150
* https://travis-ci.org/rust-lang/rust/jobs/211758389
* https://travis-ci.org/rust-lang/rust/jobs/212004583

```
error: failed to execute compile
caused by: error reading compile response from server
caused by: IoError(Error { repr: Custom(Custom { kind: Other, error: StringError("unexpected EOF") }) })
caused by: unexpected EOF
make[3]: *** [tools/llvm-readobj/CMakeFiles/llvm-readobj.dir/ELFDumper.cpp.o] Error 2
```

### Forcibly closed by remote host

Suspected fixed in https://github.com/mozilla/sccache/commit/5f6932b6b6fc22528f7cb0a02385b02b80ca7fef

PR sent in https://github.com/rust-lang/rust/pull/40676

* https://ci.appveyor.com/project/rust-lang/rust/build/1.0.2344/job/6ky8r85djtr9l202
* https://ci.appveyor.com/project/rust-lang/rust/build/1.0.2366/job/xnj3xxp6plfqig8p
* https://ci.appveyor.com/project/rust-lang/rust/build/1.0.2368/job/4x9x6h3an4cb331c
* https://ci.appveyor.com/project/rust-lang/rust/build/1.0.2377/job/e0s6p5yx4abub3hw
* https://ci.appveyor.com/project/rust-lang/rust/build/1.0.2474/job/8x4h54hyj4uh16td

```
error: failed to execute compile
caused by: Failed to send data to or receive data from server
caused by: IoError(Error { reprError { : Os { code: 10054repr: Os { code: 10054, message: "An existing connection was forcibly closed by the remote host." } })
```

notes:

* Only windows so far
* Both 32 and 64 bit
* Ignore segfaults, they're likely https://github.com/mozilla/sccache/pull/83
* Both beginning and end of the build
* appears that the server process is crashing
* suspect, crossbeam segfaulting (there are known segfaults in there)

### Wedged in build logs

wedged in mio, likely fixed in https://github.com/rust-lang/rust/pull/40809

* https://travis-ci.org/rust-lang/rust/jobs/214641046
* https://travis-ci.org/rust-lang/rust/jobs/214659698

# Errors not at the fault of sccache

### ar.exe/ranlib errors

More tracked at https://github.com/rust-lang/rust/issues/40546 suspected to be unrelated to sccache and instead related to MinGW makefiles (and how they're not always the best...)

Hoping to be fixed by https://github.com/rust-lang/rust/pull/40548

* https://ci.appveyor.com/project/rust-lang/rust/build/1.0.2279/job/28y2keij5k2nggbm - ranlib file format not recognized
* https://ci.appveyor.com/project/rust-lang/rust/build/1.0.2286/job/9f765q3opo03djpo - ar.exe no such file or directory
* https://ci.appveyor.com/project/rust-lang/rust/build/1.0.2305/job/k56s0ybh90dbtl0j - ar.exe unable to rename
* https://ci.appveyor.com/project/rust-lang/rust/build/1.0.2314/job/4u931mk93qpx78e3 - ar.exe unable to rename
* https://ci.appveyor.com/project/rust-lang/rust/build/1.0.2325/job/s8x6tfi1hs2tfl48 - ar.exe permission denied
* https://ci.appveyor.com/project/rust-lang/rust/build/1.0.2397/job/xmn5g0alr50n86uv - ar.exe permission denied

**Comment by alexcrichton** [comment]
First attempt to debug this landed in https://github.com/rust-lang/rust/issues/40240, although that didn't cover OSX/Windows which seem to be failing a lot as well. Second attempt to debug this is https://github.com/rust-lang/rust/pull/40442

**Comment by alexcrichton** [comment]
I've [made a PR](https://github.com/mozilla/sccache/pull/79) to sccache to hopefully squash at least some of the spurious failures we've been seeing (I don't think it will fix all of them though)

**Comment by alexcrichton** [comment]
The first failure above is getting an EPIPE on [this line](https://github.com/mozilla/sccache/blob/1e6c6fc1e7cfdde6571215b1e03aa88a4ef93686/src/compiler/compiler.rs#L644) which baffles me. I have no idea how an EPIPE would arise during *process creation*.

**Comment by Mark-Simulacrum** [comment]
Looking at the two lines above, there's `Stdio::piped()`, which implies that during process creation we're opening the stdout and stderr file descriptors as pipes, which may be the cause of these problems. Not sure if that's the case though.

**Comment by alexcrichton** [comment]
I've found [a segfault](https://github.com/mozilla/sccache/pull/83) in sccache, but I don't think it's affected the bots all that much. I've seen a segfault here and there but not nearly as commonly as the above error conditions.

**Comment by luser** [comment]
> The first failure above is getting an EPIPE on this line which baffles me. I have no idea how an EPIPE would arise during process creation.

There's also [the pipe that's created in `Command::spawn`](https://github.com/rust-lang/rust/blob/cab4bff3de1a61472f3c2e7752ef54b87344d1c9/src/libstd/sys/unix/process/process_unix.rs#L36) to report failures back from `exec`.

**Comment by alexcrichton** [comment]
[These logs](https://travis-ci.org/rust-lang/rust/builds/213667917) are brand new with all sccache fixes I know of so far.

My guess is memory corruption somewhere, which would also explain EPIPE I think.

@luser yeah the problem with that pipe though is that I don't know how it's possible for the parent process to receive EPIPE :\. If we're randomly rewriting what fd you're writing to though (or randomly rewriting the error coming out) then I could see this being a problem...

**Comment by aturon** [comment]
Just saw this one:

```
mkdir C:\cache\rustsrc
A subdirectory or file C:\cache\rustsrc already exists.
Command exited with code 1
cat %CD%/sccache.log
cat: 'C:\projects\rust/sccache.log': No such file or directory
Command exited with code 1
```

https://github.com/rust-lang/rust/pull/40842

**Comment by aturon** [comment]
Nevermind that latest, it was introduced in https://github.com/rust-lang/rust/pull/40911/commits/0347ff58230af512c9521bdda7877b8bef9e9d34

**Comment by alexcrichton** [comment]
I have not seen any failures related to sccache over the past ~24 hrs, let's keep this open though just to make sure.

**Comment by alexcrichton** [comment]
broken pipe may be a bug in mio, I don't think it's [handling this](https://github.com/libevent/libevent/blob/2e52bace9f9998826bd3819af328efc8d18decf9/kqueue.c#L363-L380)

**Comment by alexcrichton** [comment]
That was added in https://github.com/libevent/libevent/commit/1fd34ab424b45f48dfeece108910978c79a8b7f6, but doesn't mention OSX...

**Comment by alexcrichton** [comment]
Looks like "broken pipe" errors are indeed coming from kevent, confirmed now that I've tested on an older mac. https://github.com/carllerche/mio/pull/583 should fix.

**Comment by alexcrichton** [comment]
Haven't seen any new issues in the past week or so, so assuming that we can close this now. Yay!

**Comment by TimNN** [comment]
Again a broken pipe spawn :(

```
ERROR:sccache::server: [Error(Msg("failed to spawn child"), State { next_error: Some(Error { repr: Os { code: 32, message: "Broken pipe" } }) })] 	SearchForAddressOfSpecialSymbol.cpp.o
ERROR:sccache::server: [Error { repr: Os { code: 32, message: "Broken pipe" } }] 	SearchForAddressOfSpecialSymbol.cpp.o
```

https://travis-ci.org/rust-lang/rust/jobs/226778218

**Comment by alexcrichton** [comment]
Oh oops, the [fix in mio](https://github.com/carllerche/mio/commit/fe551aa8f80e796321177e542b74ff46b7f9552f) wasn't actually released until mio 0.6.7 came out on crates.io. I was using a local override previously but when I recently rebuilt sccache I used the crates.io version and forgot that.

To fix that we need to update sccache's Cargo.lock to pull in an updated mio, make new binaries, upload them, and then make a PR.

@TimNN you scared me, my weekend was almost ruined! :)

**Comment by alexcrichton** [comment]
I've [updated sccache's mio](https://github.com/mozilla/sccache/commit/ef0d77543fdfef2e09df5fbdeb055a5a1eb8fe89), next step is binaries.

I'll be flying for the next ~20 hours and won't have the ability to do so until I land unfortunately :(

**Comment by alexcrichton** [comment]
oops didn't mean to close

**Comment by kennytm** [comment]
There has been two sccache failure this week, both talking about invalid checksum. 

43652 (failure on Linux):

```
ERROR:sccache::server: ["ARMFastISel.cpp.o"] fatal error: Error(Io(Error { repr: Custom(Custom { kind: Other, error: StringError("Invalid checksum") }) }), State { next_error: None })
```

43732 (failure on Windows):

```
ERROR:sccache::server: ["LoopInfo.cpp.obj"] fatal error: Error(Io(Error { repr: Custom(Custom { kind: Other, error: StringError("Invalid checksum") }) }), State { next_error: None })
```

Reopen?

**Comment by alexcrichton** [comment]
I think this issue is probably no longer useful, @kennytm mind opening a new issue? You can cc https://github.com/mozilla/sccache/issues/171, the upstream report tracking this.

**Comment by kennytm** [comment]
@alexcrichton Opened #43775.

**Comment by alexcrichton** [comment]
Thanks!
