### ISSUE TITLE
overriding '/MT' with '/MD'

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#40246]
Here's an excerpt from building rustc:

```rust
Building stage1 compiler artifacts (x86_64-pc-windows-msvc -> x86_64-pc-windows-msvc)
   Compiling graphviz v0.0.0 (file:///C:/Users/steve/src/rust/src/libgraphviz)
   Compiling log v0.0.0 (file:///C:/Users/steve/src/rust/src/liblog)
   Compiling arena v0.0.0 (file:///C:/Users/steve/src/rust/src/libarena)
   Compiling gcc v0.3.43
   Compiling rustc_platform_intrinsics v0.0.0 (file:///C:/Users/steve/src/rust/src/librustc_platform_intrinsics)
   Compiling rustc_bitflags v0.0.0 (file:///C:/Users/steve/src/rust/src/librustc_bitflags)
   Compiling serialize v0.0.0 (file:///C:/Users/steve/src/rust/src/libserialize)
   Compiling fmt_macros v0.0.0 (file:///C:/Users/steve/src/rust/src/libfmt_macros)
   Compiling libc v0.2.20
   Compiling filetime v0.1.10
   Compiling build_helper v0.1.0 (file:///C:/Users/steve/src/rust/src/build_helper)
   Compiling flate v0.0.0 (file:///C:/Users/steve/src/rust/src/libflate)
   Compiling rustdoc v0.0.0 (file:///C:/Users/steve/src/rust/src/librustdoc)
   Compiling rustc_llvm v0.0.0 (file:///C:/Users/steve/src/rust/src/librustc_llvm)
   Compiling syntax_pos v0.0.0 (file:///C:/Users/steve/src/rust/src/libsyntax_pos)
   Compiling rustc_data_structures v0.0.0 (file:///C:/Users/steve/src/rust/src/librustc_data_structures)
   Compiling rustc_errors v0.0.0 (file:///C:/Users/steve/src/rust/src/librustc_errors)
warning: cl : Command line warning D9025 : overriding '/MT' with '/MD'
warning: cl : Command line warning D9025 : overriding '/MD' with '/MT'
warning: cl : Command line warning D9025 : overriding '/MT' with '/MD'
warning: cl : Command line warning D9025 : overriding '/MD' with '/MT'
warning: cl : Command line warning D9025 : overriding '/MT' with '/MD'
warning: cl : Command line warning D9025 : overriding '/MD' with '/MT'
   Compiling syntax v0.0.0 (file:///C:/Users/steve/src/rust/src/libsyntax)
```

I don't know what these warnings are, and the build seems to work, but seems bad maybe?

**Comment by luser** [comment]
[These switches](https://msdn.microsoft.com/en-us/library/2kzt1wy3(v=vs.100).aspx) select either the static or DLL version of the CRT. If you try to mix code that was compiled with different settings you'll usually get a linker error, so that must not be happening.

**Comment by retep998** [comment]
This is very likely due to https://github.com/rust-lang/rust/pull/39837

cc @alexcrichton

**Comment by alexcrichton** [comment]
I believe the last time I checked this was because LLVM passes /MD unconditionally, we then configure it to pass /MT so it passes that later. We then ourselves also pass /MT ahead of things which ends up with:

* Our /MT is first
* LLVM's /MD is next, unsure how to remove this
* LLVM's /MT is last

The last one wins, which is what we care about, but it'd be great to fix this! I may also be wrong in this diagnosis, this is just from memory.

**Comment by liranringel** [comment]
@alexcrichton is right, llvm passed /MD.
I added the following lines to llvm-config/CMakeLists.txt, after `LLVM_CFLAGS` and `LLVM_CXXFLAGS` are set:

>set(CompilerFlags
        LLVM_CFLAGS
        LLVM_CXXFLAGS
        )
foreach(CompilerFlag ${CompilerFlags})
  string(REPLACE "/MD" "/MT" ${CompilerFlag} "${${CompilerFlag}}")
endforeach()


That indeed resolved the issue, but it probably be better if we could achieve that by editing the `cmake::Config` in `src/bootstrap/native.rs`. I hope I'll have time to check that later today.

**Comment by retep998** [comment]
This should remain open until the version of gcc and cmake that Rust itself uses are updated.

**Comment by retep998** [comment]
This should remain open until https://github.com/rust-lang/rust/pull/41959 lands.
