### ISSUE TITLE
No equivalent of into_boxed_str for CString/CStr

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust#40248]
I'm working on implementing `serde::Deserialize` for `CStr` (in https://github.com/serde-rs/serde/pull/801), and am running into the need for an equivalent of [`String::into_boxed_str`](https://doc.rust-lang.org/std/string/struct.String.html#method.into_boxed_str) for `CString`/`CStr`. With the current internals for `CStr`, I believe the implementation could be very similar; namely:
```rust
pub fn into_boxed_cstr(self) -> Box<CStr> {
    unsafe { mem::transmute::<Box<[u8]>, Box<CStr>>(self.inner) }
}
```
Is this something that could be added in line with https://github.com/rust-lang/rust/issues/18283 ?

**Comment by alexcrichton** [comment]
I think this was added in https://github.com/rust-lang/rust/pull/39594, but can you confirm that the one you're looking for was there?

**Comment by jonhoo** [comment]
Ah, yes, that looks perfect! Thanks.
