### ISSUE TITLE
1.15.1 (and earlier) armhf failing Items_and_attributes_15 doc test, passes on other architectures

### ISSUE THREAD

**Issue by infinity0** [rust-lang/rust#40260]
8 months ago back in version 1.10.0 this test was called Items_and_attributes_14 and it hung rather than failed, here is a [stacktrace](https://gist.github.com/infinity0/2f5452d4ee9deb2f1bacb8b39c987c9c).

We can ignore it with this patch:
~~~~
--- rustc.git.orig/src/doc/reference.md
+++ rustc.git/src/doc/reference.md
@@ -1133,7 +1133,7 @@ bodies defined in Rust code _can be call
 in the same way as any other Rust function, except that they have the `extern`
 modifier.
 
-```
+```{.ignore}
 // Declares an extern fn, the ABI defaults to "C"
 extern fn new_i32() -> i32 { 0 }
 
~~~~

**Comment by Mark-Simulacrum** [comment]
@infinity0 I'm not sure what the bug is here. Is the test (now [here](https://github.com/rust-lang-nursery/reference/blob/master/src/items.md#extern-functions)) hanging, crashing, or failing today?

**Comment by infinity0** [comment]
Still failing today with 1.17.0 armv7, I tested on [asachi.debian.org](https://db.debian.org/machines.cgi?host=asachi) in a armv8l 32-bit chroot, with a [clean upstream tarball]((https://static.rust-lang.org/dist/rustc-1.17.0-src.tar.gz)) (i.e. not the Debian package).

~~~~
failures:

---- /home/infinity0/upstream/rustc-1.17.0-src/src/doc/reference/src/items.md - Items (line 425) stdout ----
        error[E0570]: The ABI `"stdcall"` is not supported for the current target
 --> <anon>:6:1
  |
6 | extern "stdcall" fn new_i32_stdcall() -> i32 { 0 }
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error(s)

thread 'rustc' panicked at 'Box<Any>', src/librustc/session/mod.rs:203
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    /home/infinity0/upstream/rustc-1.17.0-src/src/doc/reference/src/items.md - Items (line 425)

test result: FAILED. 37 passed; 1 failed; 11 ignored; 0 measured



command did not execute successfully: "/home/infinity0/upstream/rustc-1.17.0-src/build/armv7-unknown-linux-gnueabihf/stage2/bin/rustdoc" "--test" "/home/infinity0/upstream/rustc-1.17.0-src/src/doc/reference/src/items.md" "--test-args" ""
expected success, got: exit code: 101
~~~~

Due to #41291 I can't use rust's own 1.16 as stage0, I'm using Debian's 1.16 dynamically linked against LLVM, which recently has had the fix for #41291 backported into it. I don't think this would be affecting this issue, but in case it is, here is my ./configure line:

~~~~
rustc-1.17.0-src$ ./configure --enable-llvm-link-shared --llvm-root=/usr/lib/llvm-3.9 --enable-local-rust
~~~~

and to make the build work I have to use these patches:

- 5c0c3e803d6070cc4d1ce0362e0ae3bae4962720
- https://anonscm.debian.org/cgit/pkg-rust/rust.git/tree/debian/patches/d-raise-min-llvm-version.patch?h=debian/experimental
- d23a65077add9da538e7ba2c2d3c3baae7a8597e
- https://anonscm.debian.org/cgit/pkg-rust/rust.git/tree/debian/patches/u-ignoretest-armhf_05.patch?h=debian/experimental

**Comment by arielb1** [comment]
The problematic test is:

```rust
// Declares an extern fn, the ABI defaults to "C"
extern fn new_i32() -> i32 { 0 }

// Declares an extern fn with "stdcall" ABI
extern "stdcall" fn new_i32_stdcall() -> i32 { 0 }
```

`"stdcall"` only exists on x86. Looks like the test needs to be marked as `rust,ignore`.

**Comment by arielb1** [comment]
That is supposed to hide the test from the docs. I'll try open a PR early next week if you won't open one before.

**Comment by infinity0** [comment]
I'm actually already marking this as `rust,ignore` on Debian, but this makes the test not run even on stdcall platforms.

There are other places in the rust code where similar stdcall-only tests exist and there's some sort of conditional so it only runs on the relevant platforms. I wasn't sure how to do that in the doc tests, however.

**Comment by infinity0** [comment]
The `#[cfg]` guard could work yes, but this type of problem (ABI mismatch vs architecture) has come up before, e.g. #24958 and we have `ignore-arm`, `ignore-aarch64` in `src/test/debuginfo/type-names.rs`.

Apparently there was some work done (#36421) to define which architectures support / don't support which ABIs and then this information could be used by the test runners to automatically ignore certain tests like this. I don't know what the progress is though, I only skimmed the ticket.

**Comment by arielb1** [comment]
Test runners are not supposed to automatically ignore tests.

**Comment by infinity0** [comment]
Then perhaps one could extend #36421 to support a `#[cfg(target_abi.contains("XXX"))]` gate instead of hard-coding arch/ABI assumptions everywhere?

**Comment by arielb1** [comment]
Local problems, local fixes.

**Comment by infinity0** [comment]
I understand. It would have wider applications, outside of disabling tests in rustc though. Suppose I want to write a `-sys` crate that links against some non-rust library. Then I could use this, instead of having to hard-code `target_arch` gates and having to maintain and update these for new architectures. Maybe something to consider for the future.

**Comment by arielb1** [comment]
@infinity0 

Such a change would definitely require an RFC (in https://github.com/rust-lang/rfcs). Feel free to write one, but it will take at least half a year or so to get implemented.
