### ISSUE TITLE
Running ./x.py dist --install fails

### ISSUE THREAD

**Issue by jrmuizel** [rust-lang/rust#40263]
I get the following error:
gen-install-script:
gen-install-script: CFG_PRODUCT_NAME     := Rust
gen-install-script: CFG_REL_MANIFEST_DIR := rustlib
gen-install-script: CFG_SUCCESS_MESSAGE  := Rust-is-ready-to-roll.
gen-install-script: CFG_OUTPUT_SCRIPT    := /home/jrmuizel/src/rust/build/tmp/d ...
gen-install-script: CFG_LEGACY_MANIFEST_DIRS := rustlib,cargo
gen-install-script:
gen-install-script: validating arguments
gen-install-script:
Dist src
error: failed to sync

Caused by:
  failed to parse manifest at `/home/jrmuizel/src/rust/build/tmp/dist/rust-src-1.17.0-dev-image/lib/rustlib/src/rust/src/librustc_plugin/Cargo.toml`

Caused by:
  expected a value of type `string`, but found a value of type `boolean` for the key `package.build`

command did not execute successfully: "/home/jrmuizel/src/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "vendor"
expected success, got: exit code: 101

**Comment by est31** [comment]
running `git submodule update --init` solved the issue for me.

**Comment by alexcrichton** [comment]
@jrmuizel this may have been due to an outdated version of `cargo-vendor` perhaps, can you try running `cargo install -f cargo-vendor` locally and see if that fixes the issue?

@est31 I think that may have been a different problem?

**Comment by est31** [comment]
@alexcrichton yeah, I was wrong. Its a different problem indeed.

**Comment by Mark-Simulacrum** [comment]
@jrmuizel Is there a chance you could check with an updated version of cargo-vendor like @alexcrichton suggests?

**Comment by ewongbb** [comment]
pardon me, but might this related to something from https://github.com/pwoolcoc/cargo/commit/952b0ab3e12b332fcc4237f5e4b87caf962e591b ?

**Comment by steveklabnik** [comment]
Triage: seems like this may be a stale issue; @jrmuizel if you're still seeing this, please let me know! Until then, I'm gonna give it a close.
