### ISSUE TITLE
Run button for playground missing from books

### ISSUE THREAD

**Issue by ollie27** [rust-lang/rust#40271]
Since the move to mdBook (part of  #39588) the "Run" button to run code example in the playground is missing from the book, nomicon and reference.

[before](https://doc.rust-lang.org/1.15.0/book/if.html) [after](https://doc.rust-lang.org/nightly/book/if.html)

**Comment by steveklabnik** [comment]
Yes, this requires PRs to fix. I'm working on it.

Please file these issues against the respective repositories for them, thanks! (Or, in this case, don't worry about it, as I'm already doing it.)

**Comment by ollie27** [comment]
This is a regression in rustbook which is in this repository...

**Comment by carols10cents** [comment]
@ollie27 Rustbook is now a thin layer on top of [mdBook](https://github.com/azerupi/mdBook), and [mdbook has not implemented playground integration yet](https://github.com/azerupi/mdBook/issues/29).

**Comment by steveklabnik** [comment]
... it is partially implemented, and we can make it work.

I already had a PR in the works until I trashed my linux partition. :(

Regardless, it involves changing the text of the actual books. It's gonna be really nice! I'm hoping to knock it all out monday.
