### ISSUE TITLE
Methods take an insanely long time to compile

### ISSUE THREAD

**Issue by tomaka** [rust-lang/rust#40280]
[This commit](https://github.com/tomaka/vulkano/commit/a56e64cc31e75ce920fd79269bd2336911b396bf) takes an insane amount of time to compile. Before the commit, the crate takes about 15 seconds to compile. After the commit, I stopped after around 15 minutes. EDIT: estimates would be about 2 hours.

I've isolated the problem to [this code](https://github.com/tomaka/vulkano/blob/a56e64cc31e75ce920fd79269bd2336911b396bf/vulkano/src/descriptor/descriptor_set/collection.rs#L195-L213). These are two methods implemented on tuples. They should expand to roughly something like this:

```rust
let &(first, B, C, D, E, F, G, H) = self;
let iter = first.buffers_list();
let iter = iter.chain(B.buffers_list());
let iter = iter.chain(C.buffers_list());
let iter = iter.chain(D.buffers_list());
let iter = iter.chain(E.buffers_list());
let iter = iter.chain(F.buffers_list());
let iter = iter.chain(G.buffers_list());
let iter = iter.chain(H.buffers_list());
Box::new(iter)
```

If I reduce the maximum size of the tuple [here](https://github.com/tomaka/vulkano/blob/a56e64cc31e75ce920fd79269bd2336911b396bf/vulkano/src/descriptor/descriptor_set/collection.rs#L222) to only 16 elements, the item-bodies checking pass takes about 11 seconds. With 17 elements, it takes about 18 seconds. With 18 elements, it takes about 33 seconds. With 19 elements, about 60 seconds.

cc @eddyb

**Comment by eddyb** [comment]
I think this has to do with the depth of the nested `Chain` type.
cc @arielb1 @nikomatsakis Is it likely that the new trait system will solve this?

**Comment by durka** [comment]
Is this #22204?

**Comment by nikomatsakis** [comment]
Nominating for triage. Seems *likely* to be related to #22204, haven't had time to investigate.

**Comment by nikomatsakis** [comment]
Another issue that is basically the same: https://github.com/rust-lang/rust/issues/38528

**Comment by nikomatsakis** [comment]
Going to close in favor of #38528, I'll copy the example there.
