### ISSUE TITLE
error: failed to read src/tools/cargo/Cargo.toml

### ISSUE THREAD

**Issue by cesarb** [rust-lang/rust#40284]
```
$ make -j4 && make install
error: failed to read `/home/cesarb/opt/rust-git/src/rust/src/tools/cargo/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
Build completed unsuccessfully in 0:00:00
Makefile:24: recipe for target 'all' failed
make: *** [all] Error 101
$ git rev-parse --short HEAD
65e2a14
$ ls src/tools/cargo
$ 
```

The `src/tools/cargo` directory is empty. Cleaning the checkout (with `git clean -f -x -d`) and running `configure` again didn't fix it.

Configure command line: `./configure --prefix=/home/cesarb/opt/rust-git --android-cross-path=/home/cesarb/android-sdks/temp/arm-linux-androideabi --target=x86_64-unknown-linux-gnu,i686-unknown-linux-gnu,x86_64-pc-windows-gnu,arm-linux-androideabi,armv7-linux-androideabi`

**Comment by petrochenkov** [comment]
Can be fixed by
```
git submodule update --init
```
See https://github.com/rust-lang/rust/pull/39917#issuecomment-284126888

**Comment by alexcrichton** [comment]
I've sent [a PR to fix this](https://github.com/rust-lang/rust/pull/40297)
