### ISSUE TITLE
Build doesn't honour CFG_CC/CFG_CXX.

### ISSUE THREAD

**Issue by vext01** [rust-lang/rust#40295]
Hi,

CC @semarie 

I notice that the rust build doesn't pass down the gcc/g++ binary chosen at configure time down to the later stages of the build.

```
$ CFG_CC=egcc CFG_CXX=eg++ ./configure --prefix=`pwd`/inst --enable-local-rust --local-rust-root=...
...
configure: CFG_CC               := egcc
configure: CFG_CXX              := eg++
...
```

Which suggests I successfully chose an alternative compiler.

```
$ egcc --version
egcc (GCC) 4.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ eg++ --version
eg++ (GCC) 4.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
$ gmake
...
CMake Error at cmake/modules/CheckCompilerVersion.cmake:12 (message):         
  Host GCC version must be at least 4.7!
```

So I think it has incorrectly used `gcc` instead of `egcc`:

```
$ gcc --version
gcc (GCC) 4.2.1 20070719 
```

A workaround is to make symlinks to `egcc` and `eg++` and put the dir in the path first. 

System is OpenBSD. Today's rust master.

Thanks.

**Comment by semarie** [comment]
@edd please use `CC` and `CXX` env variable and pass them to `gmake` too.

```
env CC=egcc CXX=eg++ ./configure ...
env CC=egcc CXX=eg++ gmake
```

**Comment by semarie** [comment]
it is due because even if configure write `CFG_CC`, rustbuild doesn't read the compiler path from `config.mk`, but always from `gcc` crate, so at runtime.

**Comment by vext01** [comment]
Thanks. This seems to be working.

I guess I was caught out, as usually the compiler found by `configure` is used without having to set `CC` and `CXX` for the make part.

**Comment by alexcrichton** [comment]
FWIW [rustbulid attempts to do this detection](https://github.com/rust-lang/rust/blob/master/src/bootstrap/cc.rs#L99-L121), and if that's failing then PRs are of course always welcome!

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/42255.
