### ISSUE TITLE
Extend the atomic ordering documentation.

### ISSUE THREAD

**Issue by ticki** [rust-lang/rust#40306]
[The LLVM docs](http://llvm.org/docs/LangRef.html#memory-model-for-concurrent-operations) explains is pretty well, but it would be handy if the Rust docs were more detailed.

I'm not sure about the license of the LLVM docs.

tag @steveklabnik

**Comment by ericfindlay** [comment]
There's also quite a bit of detail in the [Atomics](https://doc.rust-lang.org/nomicon/atomics.html) section of Rustonomicon.

**Comment by steveklabnik** [comment]
docs team triage: p-medium

**Comment by DevQps** [comment]
@ticki I was browsing around a bit and saw the [`std::sync::atomic::Ordering`](https://doc.rust-lang.org/std/sync/atomic/enum.Ordering.html) now does quite a good job at explaining the different types of atomic orderings! It even links to the LLVM pages that you provided as well and matches the displayed Ordering with the associated LLVM ones. As has been mentioned by the deleted user, the [ nomicon](https://doc.rust-lang.org/nomicon/atomics.html) also contains some good documentation as well, which seems to be more in depth.

@steveklabnik @ticki I think if you all agree we can close this one now!

**Comment by steveklabnik** [comment]
Ticki doens't do open source anymore, and yeah. Without specific improvements suggested, and both other people in this thread no longer around, I think we can close. Thanks!
