### ISSUE TITLE
rustdoc does not highlight code blocks in other languages

### ISSUE THREAD

**Issue by jorendorff** [rust-lang/rust#40301]
The "Documentation" chapter of the Rust book says:

> If you want something that's not Rust code, you can add an annotation:
>
> ```rust
> /// ```c
> /// printf("Hello, world\n");
> /// ```
> ```
>
> This will highlight according to whatever language you're showing off. 

This doesn't work for me. I asked Steve about it on IRC:

```text
<jorendorff> steveklabnik: Is this true?
<steveklabnik> jorendorff: as long as highlight.js or whatever knows how to do it, yeah, and
    there's a lot of them. like x86asm.
<jorendorff> steveklabnik: huh. i just tried it out locally and i'm not getting any highlighting...
<steveklabnik> weird
<jorendorff> steveklabnik: My devtools network tab doesn't show it trying to load highlight.js.
<jorendorff> the output HTML does contain `<code class="language-c">` and such...
<steveklabnik> i dunno then, maybe file a bug?
<steveklabnik> my understanding is that it's supposed to
<jorendorff> steveklabnik: a bug against rust, or the book? or both? I'm trying to find
    evidence in librustdoc that this feature exists, no luck
<steveklabnik> file it against rust, becuase we should determine if this feature was intended
    to exist or not first
<steveklabnik> it might end up being one against the book if that was wrong
<steveklabnik> but this might be a regression 
<steveklabnik> i dunno
```

**Comment by jorendorff** [comment]
@steveklabnik

**Comment by steveklabnik** [comment]
I thought this was a rustdoc feature, but now am not so sure. I thought we used highlight.js and so inherited everything it uses.

If this is not true, we should decide which is broken: the docs or rustdoc.

/cc @rust-lang/tools @rust-lang/docs

**Comment by alexcrichton** [comment]
Currently code is highlighted using the actual libsyntax lexer, which in turn is why no other language is supported (we only lex rust!)

**Comment by alexcrichton** [comment]
(at least that's what it originally did, unsure if it still does that...)

**Comment by GuillaumeGomez** [comment]
No, it's still the case. Should we use highlightjs or any equivalent instead?

**Comment by nrc** [comment]
I'd be happy to keep using a custom highlighter - it is nice to have a highlighter written in Rust (I use it rustw for example) and it allows us to be in control and ensure quality highlighting. I suspect it is uncommon for rustdoc to need to highlight non-Rust code.

**Comment by steveklabnik** [comment]
Okay, let's change this into a docs bug to fix the book.

**Comment by steveklabnik** [comment]
fixed by https://github.com/rust-lang/rust/pull/40466
