### ISSUE TITLE
Change error `contains interior mutability` to `may contain interior mutability`?

### ISSUE THREAD

**Issue by dpc** [rust-lang/rust#40313]
The following error is a bit misleading:

`the type SomeTrait + 'static contains interior mutability and a reference may not be safely transferrable 
across a catch_unwind boundary`

Since `SomeTrait` is a trait object, it seems to me `may contain (...)` is more precise.

**Comment by Mark-Simulacrum** [comment]
@rust-lang/lang: Do we want to make this change? If so, E-easy and E-mentor on me. I think it makes sense to edit the language; unfortunately I don't think we can do it only when referencing a trait object.

[This message](https://github.com/rust-lang/rust/blob/a11c26f6acb1b8890c36196e88371840c01e201d/src/libstd/panic.rs#L115) needs to be updated to the new language and src/test/compile-fail/issue-17718-const-borrow.rs and src/librustc_mir/diagnostics.rs need updating as of the time of writing this.

**Comment by nikomatsakis** [comment]
`may contain` seems fine. We are perhaps a bit inconsistent on this -- it often happens that we make static approximations, and hence all the compiler's conclusions are sort of (implicitly) "may contain foo". Seems like it's probably better to try to be explicit about that in our phrasing, though, since it can really throw people otherwise.

**Comment by Mark-Simulacrum** [comment]
Okay, I've marked as E-easy and E-mentor; initial instructions are [here](https://github.com/rust-lang/rust/issues/40313#issuecomment-304456693). Let us know if you'd like to work on this or have any questions, we'd be happy to help.

**Comment by gaurikholkar** [comment]
I'd like to take this up

**Comment by Mark-Simulacrum** [comment]
Go ahead! Let us know if you'd like any assistance.

**Comment by gaurikholkar** [comment]
So we aren't doing it only while referencing a `TraitObject` right?

**Comment by Mark-Simulacrum** [comment]
No, since that'd require doing this inside the compiler; we can get 95% of the way there by just changing the error message. There's not a good way to check in the annotation if the Self type is a trait object.

**Comment by gaurikholkar** [comment]
Here's a link to my [local branch](https://github.com/gaurikholkar/rust/commit/ab7eb521776d6aa0797f7b66ecdb607a0ccabe84). I've made the changes as you suggested followed by a `./x.py build --stage 0` and `./x.py build --stage 1`. But the [compile-fail test](https://github.com/gaurikholkar/rust/blob/master/src/test/compile-fail/issue-17718-const-borrow.rs#L17) seems to be failing.

**Comment by Mark-Simulacrum** [comment]
Could you post a build log? By the way, I think to test you should run `./x.py test --incremental src/test/compile-fail` in this case and that should be good.

**Comment by eddyb** [comment]
You changed `RefUnwindSafe`'s `on_unimplemented` message, which is relevant to this issue, but none of the testcases you changed *actually use `RefUnwindSafe`* (they just *happen* to have similar phrasing, but they're about borrowing values with `UnsafeCell` in them, in constants).

**Comment by gaurikholkar** [comment]
@eddyb thanks! I happened to not notice that these two were indeed different. The error message regarding borrowing values appears [here](https://github.com/rust-lang/rust/blob/107bd67ef7fb3e8027d7234d687cdd27c3efaa0d/src/librustc_mir/transform/qualify_consts.rs#L665) . That'll make the `compile-fail` test work. I'll write a new ui test for the `RefUnwindSafe` case as discussed with @nikomatsakis .

**Comment by gaurikholkar** [comment]
Updated the code [here](https://github.com/gaurikholkar/rust/commit/c1866fb7803981a33cca463c5bc1773c3ac667a4)
`./x.py test src/test/compile-fail` works 
`./x.py test src/test/ui` works

**Comment by eddyb** [comment]
@gaurikholkar Yupp, looks great!
