### ISSUE TITLE
document `pub(restricted)` syntax

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#40334]
Before we can [stabilize `pub(restricted)`](https://github.com/rust-lang/rust/issues/32409), it needs to be documented. 

cc @rust-lang/docs -- can one of you elaborate on this issue to spell out the steps needed? Even better, update the stabilization guide recently added to https://forge.rust-lang.org/ while you are at it.

**Comment by steveklabnik** [comment]
I will send in a PR to update the guide.

TL;DR:

* remove flag from the unstable book
* integrate any docs there into other docs as appropriate.

**Comment by nikomatsakis** [comment]
PRs from @cramertj:

- https://github.com/rust-lang-nursery/reference/pull/12
- https://github.com/rust-lang/rust-by-example/pull/856

**Comment by steveklabnik** [comment]
I *believe* all of this has landed?

**Comment by petrochenkov** [comment]
>The RBE PR can't land until the release happens, so it being open is enough. 

👍
