### ISSUE TITLE
Double `use *` breaks import system

### ISSUE THREAD

**Issue by shanegibbs** [rust-lang/rust#40330]
Given the following code:

```rust
extern crate rand;

mod c {
    // unresolved import?
    use rand;
}

fn main() {}
use a::*;
use b::*;
```

https://is.gd/klWce8

I expect the compiler to tell me that module `a` and/or `b` do not exist.

But what I get is:

```
error[E0432]: unresolved import
 --> <anon>:6:9
  |
6 |     use rand;
  |         ^^^^
```

This code compiles if the last two lines are removed.

This happened in the middle of a refactor. These two lines were left behind after the modules were removed. In my case, those two lines took a long time to find.

**Comment by gilescope** [comment]
See playground against latest nightly: 
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=69dfef35c69b6160f5fb5e5d5b6ffb2b

The error is now a warning of an unused import. 
Move to close? @Mark-Simulacrum
