### ISSUE TITLE
associated_item table is not populated after type error.

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#40343]
This is the underlying cause of the ICE in #39957. I worked around it in save-analysis, but @eddyb (cc) asked me to file an issue since it might cause bugs elsewhere.

Example code:

```rust
#![feature(try_from)]
use std::convert::TryFrom;

struct Test;
impl Test {
    fn foo(&self) -> &'static str {
        "asdf"
    }
}

impl TryFrom for Test {} //~ ERROR: wrong number of type arguments: expected 1, found 0
```

Because of the error on the last line, we never create the `associated_item` table on the tcx, which means that both `impl_of_method` and `trait_of_item` return `None` for `foo`.

**Comment by arielb1** [comment]
`associated_item` is constructed on demand: https://github.com/rust-lang/rust/blob/042728e7ff27e305130747c0d1f19d4a67587863/src/librustc/ty/mod.rs#L2051, so I wonder what is going on here.

**Comment by eddyb** [comment]
@arielb1 The solution proposed on IRC is to remove both of those and instead have a way of checking if a an *arbitrary* `DefId` is an associated item and/or get an `Option<ty::AssociatedItem>` from it.
It's fairly simple, for cross-crate you check `describe_def` and locally the variant of `hir::map::Node`.

**Comment by arielb1** [comment]
@eddyb

Well, now that we have "HIR" `AssociatedItem`, we can move it to the HIR map.

**Comment by eddyb** [comment]
Right, that'd make sense. There's a bunch of these that should be moved to HIR.
