### ISSUE TITLE
Hygiene for function-like procedural macros

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rust#40356]
Hello.
I wonder how the hygiene works for function-like procedural macros.
I made a test with these macros that you can find [here](https://github.com/antoyo/function-proc-macro).

However, it does not compile.
I get the following error:
```rust
error[E0425]: cannot find value `vector` in this scope
 --> src/main.rs:9:5
  |
9 |     pp!(vector);
  |     ^^^^^^^^^^^^ not found in this scope
```
while if the call is:
```rust
pp!(vec![1, 2, 3]);
```
it will compile and works.

Is this an issue with hygiene?

Thanks.

**Comment by abonander** [comment]
There is no hygiene support for procedural macros yet. @jseyfried is working on this, though.

**Comment by petrochenkov** [comment]
Closing as a duplicate of https://github.com/rust-lang/rust/issues/54724.
