### ISSUE TITLE
Enum inside enum - assertion failed: !self.in_variant

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#40350]
```
$ rustc --version
rustc 1.17.0-nightly (b1e31766d 2017-03-03)
```

```rust
enum E {
    A = {
        enum F { B }
        0
    }
}
```

```
thread 'rustc' panicked at 'assertion failed: !self.in_variant', /checkout/src/librustc_lint/builtin.rs:472
```

https://github.com/rust-lang/rust/blob/b04ebef43242ade6be8968694caf56a0fb00a4d3/src/librustc_lint/builtin.rs#L472

**Comment by TimNN** [comment]
Taking a quick look at the source, the fix here is probably to turn `MissingDoc::in_variant` into a depth counter and increment / decrement instead of setting to `true` / `false`.
