### ISSUE TITLE
Inform dep-info users about used environment variables

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#40364]
It'd be great for caching servers like sccache if the compiler could inform them about used environment variables for the compilation through macros like `env!` and `option_env!`. I'm not precisely sure what the format would look like, but via some means would be great!

**Comment by luser** [comment]
I don't have any great ideas, but if we could get this out of the compiler in the same invocation where we get dep-info that would be ideal. Whether it goes to a separate file or is mixed into the dep-info somehow is not particularly important to me.

**Comment by alexcrichton** [comment]
Right now `foo.d` (the output of dep-info) is makefile syntax (intentionally). We could perhaps consider just throwing in something like:

```
# env-dep: FOO
# env-dep: BAR
foo.d: ...

a.rs:
b.rs:
```

A bit of a hack, but could get the job done.
