### ISSUE TITLE
rustdoc bug rendering constant section

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#40370]
https://api.rocket.rs/rocket/http/struct.ContentType.html

<img width="995" alt="screen shot 2017-03-08 at 2 54 30 pm" src="https://cloud.githubusercontent.com/assets/416575/23721238/25ea94e6-040f-11e7-939b-bb7875b79cde.png">

cc @GuillaumeGomez @SergioBenitez

**Comment by clarcharr** [comment]
May be related: on the latest nightly I'm noticing that double quotes are no longer on `implementors/**.js`. However, I'm noticing that on master they *appear* to be escaped. Perhaps something changed recently?

**Comment by ollie27** [comment]
@clarcharr that was indeed also triggered by #39944, I've submitted a fix for that: #40451.
