### ISSUE TITLE
How can I stop rustc including system specific information such as absolute file paths of the source it's compiled from in the binaries it generates?

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#40374]
`/checkout/src/libcore/option.rs`
`/home/kfairmasterz/.cargo/registry/src/github.com-1ecc6299db9ec823/typeable-0.1.2/src/lib.rs`
`/home/kfairmasterz/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.7/src/ssl/bio.rs`

**Comment by kfairmasterz** [comment]
I tried: -Cdebuginfo=0 -Zno-landing-pads -C opt-level=3 -C panic=abort -C lto

It still exists panic message in binary:
```
╭─kfairmasterz@Android /tmp/tst  ‹master*› 
╰─➤  LC_ALL=en_US.UTF8 grep -in "checkout" target/i686-unknown-linux-gnu/release/tst infomation
Binary file target/i686-unknown-linux-gnu/release/tst matches
╭─kfairmasterz@Android /tmp/tst  ‹master*› 
╰─➤  LC_ALL=en_US.UTF8 grep -in "home/kfairmasterz" target/i686-unknown-linux-gnu/release/tst
Binary file target/i686-unknown-linux-gnu/release/tst matches
```

What should I do?

**Comment by kfairmasterz** [comment]
I see, they are hardcoded in libstd.

https://doc.rust-lang.org/nightly/src/std/macros.rs.html#39-60

```rust
#[macro_export]
#[stable(feature = "rust1", since = "1.0.0")]
#[allow_internal_unstable]
macro_rules! panic {
    () => ({
        panic!("explicit panic")
    });
    ($msg:expr) => ({
        $crate::rt::begin_panic($msg, {
            // static requires less code at runtime, more constant data
            static _FILE_LINE: (&'static str, u32) = (file!(), line!());
            &_FILE_LINE
        })
    });
    ($fmt:expr, $($arg:tt)+) => ({
        $crate::rt::begin_panic_fmt(&format_args!($fmt, $($arg)+), {
            // The leading _'s are to avoid dead code warnings if this is
            // used inside a dead function. Just `#[allow(dead_code)]` is
            // insufficient, since the user may have
            // `#[forbid(dead_code)]` and which cannot be overridden.
            static _FILE_LINE: (&'static str, u32) = (file!(), line!());
            &_FILE_LINE
        })
    });
}
```

I know how to fix it for now.

**Comment by kfairmasterz** [comment]
No, It's doesn't work. I had to find another way out.

**Comment by kfairmasterz** [comment]
Almost I am given up. The strange local file path string where are they come from?
https://github.com/kfairmasterz/wtf

**Comment by steveklabnik** [comment]
It is unclear what your question is. These paths point to where things were compiled, which in the case of libstd, is not on your computer, but on our build machines.

**Comment by kfairmasterz** [comment]
How to do not let rustc writing that local source file path string in the final compiled binary program?

I am sorry about the unclear question.

**Comment by steveklabnik** [comment]
I believe you can run `strip`; I am not aware of a flag or anything to turn this off, though I may be wrong.

**Comment by kfairmasterz** [comment]
@steveklabnik  I tried. 
```bash
cd /tmp
git clone https://github.com/kfairmasterz/wtf
cd wtf
cargo build --release
strip ./target/release/wtf
objdump -s -j .rodata ./target/release/wtf
```

**Comment by alexcrichton** [comment]
These paths are coming through calls to `panic!` most likely, and cannot be stripped out easily. Currently there is no way to instruct the panic macro to not encode local paths.

**Comment by kfairmasterz** [comment]
@alexcrichton I tried mask the macro {libcore,libstd}/panic! inside `file!` `line` as `""` `0`, Then `xargo build --release`, it still exists such of path strings.

**Comment by kfairmasterz** [comment]
https://github.com/kfairmasterz/hello_https/tree/master
There is. (Sample repository)

**Comment by rohitjoshi** [comment]
👍

**Comment by kfairmasterz** [comment]
Unfortunately, Nobody one tries tell me there is better way how to do.

> LLVM IR

**Comment by kfairmasterz** [comment]
Now I see How to solve it now.

**Comment by kfairmasterz** [comment]
As finally trace out, I believe there is the source code about how inject the local source file location now.
https://github.com/rust-lang/rust/blob/master/src/librustc_trans/mir/block.rs#L279-L327

Question is, How to modify it.

**Comment by kfairmasterz** [comment]
Oh I see hints for define a option/flag;
https://github.com/rust-lang/rust/blob/master/src/librustc_trans/mir/block.rs#L123
`if !bcx.sess().target.target.options.custom_unwind_resume {`

**Comment by kfairmasterz** [comment]
Solved.

**Comment by steveklabnik** [comment]
Great, let's close then.
