### ISSUE TITLE
0e+10 is invalid whereas 00e+10 is valid

### ISSUE THREAD

**Issue by qnighy** [rust-lang/rust#40408]
I found [this line in the lexer](https://github.com/rust-lang/rust/blob/1.15.1/src/libsyntax/parse/lexer/mod.rs#L749) prevents `0e+10` to be parsed as a float, whereas `00e+10` is allowed anyway. Is this a bug or an intended behavior?

This is a code [I tested on Rust Playground](https://is.gd/TPL4jn):
```rust
fn main() {
  // OK
  println!("{}", 0);
  // OK
  println!("{}", 00e+10);
  // Parse Error
  println!("{}", 0e+10);
}
```

It seems natural that both of them are banned or both of them are allowed.

**Comment by nagisa** [comment]
It is a bug.

**Comment by nagisa** [comment]
IIRC at least.

**Comment by nagisa** [comment]
This is the relevant section in the reference: https://doc.rust-lang.org/reference.html#floating-point-literals

It says:

> A floating-point literal has one of two forms:
> * A decimal literal followed by a period character U+002E (.). This is optionally followed by another decimal literal, with an optional exponent.
> * A single decimal literal followed by an exponent.

and

> A decimal literal starts with a decimal digit and continues with any mixture of decimal digits and underscores.

i.e.

```
LIT_DECIMAL := DEC_DIGIT (DEC_DIGIT | "_")+
EXPONENT := /* snip */
LIT_FLOAT_FORM1 := LIT_DECIMAL "." [LIT_DECIMAL [EXPONENT]]
LIT_FLOAT_FORM2 := LIT_DECIMAL EXPONENT
LIT_FLOAT := LIT_FLOAT_FORM1 | LIT_FLOAT_FORM2
```

so all forms should parse.

**Comment by qnighy** [comment]
I'm going to close this issue, because #40589 fixed it.
