### ISSUE TITLE
Literals don't have static lifetime

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#40405]
OK:
```rust
fn get_slice_ok() -> &'static [u8] {
    const CONST: &'static [u8] = &[0];
    CONST
}
```
Borrowck error:
```rust
fn get_slice_error() -> &'static [u8] {
    &[0]
}
```
But consts and literals are basically the same thing, so I'd expect this to work.

**Comment by durka** [comment]
It's not about slices: `let _: &'static [u8] = &42;` doesn't work either.

**Comment by jethrogb** [comment]
Related #18852

**Comment by cramertj** [comment]
IIRC #38865 should fix this.

**Comment by jethrogb** [comment]
Huzzah!

From [RFC 1414](https://github.com/rust-lang/rfcs/blob/master/text/1414-rvalue_static_promotion.md):

> # Summary
> Promote constexpr rvalues to values in static memory instead of stack slots, and expose those in the language by being able to directly create 'static references to them. This would allow code like `let x: &'static u32 = &42` to work.

**Comment by jethrogb** [comment]
I'm going to close this in favor of the tracking issue.
