### ISSUE TITLE
clean up visuals on error index

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#40425]
Specifically, the notice about not being emitted anymore

<img width="535" alt="untitled" src="https://cloud.githubusercontent.com/assets/27786/23809290/1ba199a2-059b-11e7-943e-14f147117e84.png">

This is functional, but could look much nicer.

**Comment by jdhorwitz** [comment]
@steveklabnik I could take this one and start working on it.

**Comment by steveklabnik** [comment]
That'd be great!

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/40502 will fix this

**Comment by steveklabnik** [comment]
PR was merged, this can be closed!
