### ISSUE TITLE
Conservative impl trait + named lifetimes gives access to invalid memory.

### ISSUE THREAD

**Issue by P-E-Meunier** [rust-lang/rust#40430]
I've just noticed a really unsound behavior with the latest nightly rustc (might have been present before).

Despite several hours of trying, I've not yet found a way to reproduce on a minimal example, because it took several layers of "Handler traits" (I'm writing a server) with methods that call functions returning `impl Future<…>` (conservative impl trait).

Still, I thought this was worth reporting because I've been given access to dropped memory, and that scared me.

Basically, I had a buffer (a `Vec<u8>`), and I managed to give a borrow on that buffer, to a deeply nested closure (using futures/tokio). My understanding of the problem is that Tokio returns immediately (because some IO blocks), the buffer gets deallocated, but the borrow is still accessible from the closure on the next `poll()`.

On most smaller examples I've tried, Rust prevents me from doing this, but the error locations are (rightfully) in the closure.

My server then calls `debug!` on that buffer, and prints parts of the buffer, overwritten by subsequent writes.

In my case, this could not happen when I started threading the `Request` buffer through the closures, and have my server return `(Request, Response)` (I needed the `Request` anyway), instead of just `Response`.

**Comment by retep998** [comment]
Could this possibly be a bug with futures or tokio?

**Comment by P-E-Meunier** [comment]
I don't know. One weird thing is that I had two functions:

```
fn handle(request: &Request, response: Response) -> impl Future<…> {
   match … {
        Case::Case => sub_handle(request, response)
   }
}
fn sub_handle(request: &Request, response: Response) -> impl Future<…> {
    future.and_then(|x| {
         look_at_(request)
   })
}
```

Rustc told me that `sub_handle` needed named lifetimes, I satisfied that complaint (`request:&'a Request`). But I believe I should have been told about that in `handle` also, and I haven't.

**Comment by frewsxcv** [comment]
Not too sure, but it might be helpful to set `export RUSTFLAGS="-Cllvm-args=-sanitizer-coverage-level=3 -Zsanitizer=address"` before compiling your program, running it, and see if address sanitizer reports anything

**Comment by Mark-Simulacrum** [comment]
@rust-lang/compiler If this is really unsound behavior, we should probably P-high to investigate. Unfortunately, I don't see any code in this issue which makes investigating challenging.

**Comment by nikomatsakis** [comment]
@P-E-Meunier this does sound scary-ish, but I agree there's not much to go on here. @P-E-Meunier can you give us any kind of link to the code in question?

(There are a number of open soundness issues, so it could well be one of those.)

**Comment by P-E-Meunier** [comment]
Oops, even that code has changed a lot since then, I'm afraid I can't reproduce.

One thing I've noticed though, is that at the time it was allowed to do the following:

```
#![feature(conservative_impl_trait)]
extern crate tokio_core;
extern crate futures;
use tokio_core::reactor::{Handle, Core, Timeout};
use futures::{finished, Future};

fn f<'a>(l: Handle, s: &'a str) -> impl Future<Item = (), Error = std::io::Error> {
    Timeout::new(std::time::Duration::from_secs(1), &l).unwrap().and_then(move |_| {
        println!("{}", s);
        finished(())
    })
}

fn main() {
    let s = "foo".to_string();
    let mut l = Core::new().unwrap();
    let h = l.handle();
    struct S<F> {
        s: String,
        f: F
    }
    let s = S {
        s: s,
        f: f(h, &s)
    };
}
```

Which is what I was doing, and this is not allowed anymore. I guess this issue can be closed then.
