### ISSUE TITLE
rustdoc sidebar styling doesn't extend to bottom of page if content is taller than sidebar

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#40459]
Introduced in https://github.com/rust-lang/rust/pull/40265

![fireshot capture 2 - std - rust - https___doc rust-lang org_nightly_std_](https://cloud.githubusercontent.com/assets/416575/23835636/246807b8-0741-11e7-84bc-a40145863821.png)

**Comment by frewsxcv** [comment]
cc @wesleywiser

**Comment by frewsxcv** [comment]
Might be able to fix this using flexbox?

**Comment by steveklabnik** [comment]
I actually don't hate this, but would be fine with it changing too.

**Comment by wesleywiser** [comment]
I can't seem to repro this. What browser are you using?

**Comment by frewsxcv** [comment]
Firefox 51.0.1

**Comment by wesleywiser** [comment]
Hmm... I'm not seeing it on FF 52 on macOS

**Comment by frewsxcv** [comment]
Since I didn't specify earlier, the page in the screenshot above is: https://doc.rust-lang.org/nightly/std/

**Comment by frewsxcv** [comment]
In case there was any concern about version differences, I just upgraded to version 52.0 and can still reproduce the screenshot.

**Comment by wesleywiser** [comment]
I can see it on that page. I was testing my local build which doesn't seem to be experiencing the issue.

**Comment by wesleywiser** [comment]
For some reason, my local copy has 

```
.sidebar {
    width: 100%;
}
```

instead of 

```
.sidebar {
    width: 100vh;
}
```

I'm not sure why it's different but that fixes the issue.
