### ISSUE TITLE
--pretty=expanded makes some unexpected results

### ISSUE THREAD

**Issue by jeiea** [rust-lang/rust#40462]
First sorry for not preparing minimal example caused from my inexperience to rust.

Full tried code and description are uploaded on this [github repo](https://github.com/jeiea/rust-issue-prettyexpanded).

I tried [this example](https://github.com/Jascha-N/minhook-rs#example) and it caused build failure and I tried inspecting it by appending `-Z unstable-options --pretty=expanded` to cargo's command.

At the result, line comments like `// Create a hook for user32::MessageBoxA.` appears higher line than expected. I think line comments' position remained intact despite of macro expansion.

With another attempt I tried building above expanded form. One of error messages of it is
```
error[E0412]: cannot find type `StaticHook` in the crate root
  --> src/expanded.rs:14:8
   |
14 |          ::StaticHook<unsafe extern "system" fn(HWND, LPCSTR, LPCSTR, UINT)
   |  ________^ starting here...
15 | |                         -> c_int> =
   | |_________________________________^ ...ending here: not found in the crate root
   |
   = help: possible candidate is found in another module, you can import it into scope:
             `use minhook::StaticHook;`
```
It seems `$crate` isn't resolved well.

## Meta
```
$ rustc --version --verbose
rustc 1.17.0-dev (ec8792532 2017-03-09)
binary: rustc
commit-hash: ec87925325c005922977ebf9b10dc9e98d8a6d40
commit-date: 2017-03-09
host: x86_64-pc-windows-gnu
release: 1.17.0-dev
LLVM version: 3.9
```

**Comment by Mark-Simulacrum** [comment]
Based on the following code, I think this has been fixed. I unfortunately can't test the provided repo due to lacking a windows machine (minhook doesn't compile on linux), so closing.

```rust
// rustc test.rs --crate-type=lib -Zunstable-options --pretty=expanded | rustc -
macro_rules! a {
    () => {
        $crate::main()
    }
}
fn main() {
}

mod b {
    fn f() {
        a!();
    }
}
```
