### ISSUE TITLE
Current beta displays incorrect version

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#40464]
This is what the current beta prints:

```
rustc 1.16.0 (30cf806ef 2017-03-10)
```

It's the correct commit. I have no idea why it would not be displaying the beta information.

cc @alexcrichton

**Comment by alexcrichton** [comment]
@brson heh I have quite a bit to recount from this weekend :)

**Comment by Mark-Simulacrum** [comment]
Closing.

```
$ rustc +beta --version
rustc 1.19.0-beta.1 (a87984118 2017-06-06)
```
