### ISSUE TITLE
MIR inlining inlines default trait methods

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#40473]
## STR

```
$ cat mirline.rs
pub trait Foo {
    fn bar(&self) {}
}

impl Foo for () {
    fn bar(&self) { println!("Hello, World!"); }
}

pub fn main() {
    ().bar();
}
$ rustc mirline.rs -Z mir-opt-level=2
$ ./mirline
```

## Expected Result

Code should print "Hello, World!"

## Actual Result

Code does not print anything, because the empty default implementation is inlined.

cc @Aatch

**Comment by Xaeroxe** [comment]
Honest question, why is this legal Rust syntax?

```Rust
impl Foo for () {
    fn bar(&self) { println!("Hello, World!"); }
}
```

I only see gross potential for misuse of implementing traits for the unit type.

**Comment by wesleywiser** [comment]
Is this just a matter of preventing the inliner from inlining trait default methods?

**Comment by arielb1** [comment]
1.17 is now beta.

**Comment by nikomatsakis** [comment]
triage: P-medium

Marking this as medium because it requires you to opt-in to the higher "MIR opt level", which is unstable, but we should definitely fix this.

**Comment by brson** [comment]
cc @Aatch @nikomatsakis just pinging for an update.

**Comment by arielb1** [comment]
1.17 is now stable. This is a nightly -> nightly regression affecting only `-Z mir-opt-level`.

**Comment by nikomatsakis** [comment]
triage: P-medium

**Comment by nikomatsakis** [comment]
I have been talking to @qmx, who is going to take a look at implementing this. I'll leave some mentoring instructions shortly!

**Comment by nikomatsakis** [comment]
So #44383 will fix this by just not inlining trait calls -- the simplest possible fix. I just opened https://github.com/rust-lang/rust/issues/44389 as an enhancement issue to track a more complete fix.
