### ISSUE TITLE
A "Design FAQ" document

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#4047]
In the vein of the [Project FAQ](https://github.com/mozilla/rust/wiki/Doc-project-FAQ) and the [Language FAQ](https://github.com/mozilla/rust/wiki/Doc-language-FAQ).

In addition to being really interesting, this would save a lot of time and divert a lot of potential questions in the long run. Some topics to discuss:

* Why was typestate removed?
* Why are some types nominal instead of structural?
* Why do I have to declare impls in the same crate as a type or trait?
* Why is trait inheritance the only means of inheritance?
* Why doesn't Rust do tail-call optimization?
   (see e.g. [rust-dev post](https://mail.mozilla.org/pipermail/rust-dev/2013-April/003557.html).)

Explanations should be technical and include code examples wherever possible.

Some of the questions of this nature overlap with the latter half of the Language FAQ, but not all, e.g. "Can Rust code call C code?" and "What is the difference between a managed pointer and an owned pointer?" do not belong. The document should focus on large-scale design decisions and tradeoffs; think "Why split stacks?" rather than "How do split stacks work?".

If you think of good questions, add them in the comments here. There are probably a lot of ripe areas for explanation, especially with regard to mutability and regions.

**Comment by alexchandel** [comment]
"Why is `i32` the default?" and "Why aren't `isize` and `usize` named after C's `intptr_t` and `uintptr_t`?"

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#615

**Comment by pnkfelix** [comment]
Oh no!  It was really nice that this list was all in one place!

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#891

**Comment by alexchandel** [comment]
I guess closing all your issues is a nice way to pretend they're not issues. Adding an FAQ shouldn't need to go through the RFC process.

**Comment by steveklabnik** [comment]
@alexchandel the RFC repo issues are not just for things going through the process. It's also full of suggestions for things like community libraries that could be done. The result of this won't need to go through the RFC process, it's just that I don't plan on writing this any time soon.

**Comment by pnkfelix** [comment]
Note also that there *are* prototype FAQ documents already in `src/doc`:

 * https://github.com/rust-lang/rust/blob/master/src/doc/complement-design-faq.md
 * https://github.com/rust-lang/rust/blob/master/src/doc/complement-lang-faq.md
 * https://github.com/rust-lang/rust/blob/master/src/doc/complement-project-faq.md

(Nonetheless, these tickets remain worthwhile catch-all lists of questions that may not yet have answers on any of those three documents.  I'm still not thrilled with the pseudo-migration to the RFC repo.)

**Comment by steveklabnik** [comment]
Yes, I'm not exactly psyched about those ones, either, to be honest.

**Comment by pnkfelix** [comment]
> Why can't I do destructuring-bind in a trait default method?

See discussion from [2013-09-10](https://github.com/rust-lang/meeting-minutes/blob/master/weekly-meetings/2013-09-10.md#patterns-traits-and-default-methods), though it seems like the "decision" there was never implemented (and likely never will at this point?)
