### ISSUE TITLE
Cursor not reading underlying vec when written to

### ISSUE THREAD

**Issue by viperscape** [rust-lang/rust#40478]
When using a Cursor, I noticed that if I write to it then read from it, nothing is read from the inner contents. Expected behavior is to be able to read the cursor data after write. 

See code example that fails: https://is.gd/NkqhOD
```rust
use std::io::prelude::*;
use std::io::Cursor;

fn main() {
    let mut s = Cursor::new(vec![]);
    
    let _ = s.write_all(&[1,2,3]);
    assert_eq!(s.get_ref().len(), 3); //confirms write success
    
    let mut b = [0u8];
    let r = s.read_exact(&mut b);
    assert!(r.is_ok()); // fails
}
```

**Comment by jmesmon** [comment]
`.write_all()` advances the cursor to immediately past the written data. To read previously written data, you'll need to use `Seek` to move the cursor backwards.

**Comment by viperscape** [comment]
Ah I just figured this out too, feel pretty stupid all of a sudden ;-) thanks for clearing this up!
