### ISSUE TITLE
Irritating error when trait is not in scope

### ISSUE THREAD

**Issue by s3bk** [rust-lang/rust#40472]
Trying to use `map` on `Box<Future<Item=_, Error=_>>` without the `Future` trait in scope leads to a very confusing error:

```
f.map(|_| 3);
  ^^^ the trait `std::marker::Sized` is not implemented for `futures::Future<Error=(), Item=()>`
```

full code:
```rust
extern crate futures;

mod helper {
    use futures::{Future, future};
    pub fn make_a_boxed_future() -> Box<Future<Item=(), Error=()>> {
        Box::new(future::ok(()))
    }
}

fn main() {
    let f = helper::make_a_boxed_future();
    f.map(|_| 3);
}
```

**Comment by sfackler** [comment]
I seem to recall this showing up for the first time in 1.15 or thereabouts. It is definitely annoying.

**Comment by nikomatsakis** [comment]
Is this specific to `Future`? Or does it apply to all traits?

**Comment by s3bk** [comment]
It looks like it applies to all traits:
[Playground link](https://play.rust-lang.org/?gist=1fd66cb7beccd3e1d4b55f9bf6115546&version=stable&backtrace=0)

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/35976.
