### ISSUE TITLE
tidy doesn't play nicely with autocrlf

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#40485]
I have `git` on windows set up with [`autocrlf`](https://git-scm.com/book/be/v2/Customizing-Git-Git-Configuration#__code_core_autocrlf_code) to make sure stuff ends up okay.

Tidy doesn't understand this, since it loads the files directly, and so fails spectacularly. It'd be nice if it Just Worked.

**Comment by Enselic** [comment]
Triage: Is this still a problem? Wanted to check since 6 years have passed and circumstances might have changed.

**Comment by steveklabnik** [comment]
I was told by moderation to stop commenting on issues, but since I am the only person here: nobody else has commented, and I won't be returning to Rust development any time soon, so let's just assume this is either fixed or is a wontfix.
