### ISSUE TITLE
Bounds in for<...> are ignored

### ISSUE THREAD

**Issue by jhjourdan** [rust-lang/rust#40486]
When writing `for<'a : 'b> fn(...) -> ...`, the constraint `'a : 'b` is completely ignored by borrowcheck.

This makes it possible to write the following function, which is weird:

```
fn g<'b>(f : for<'c : 'b> fn(&'c mut i32) -> &'b mut i32) -> &'b mut i32 {
    let f2 : for<'c> fn(&'c mut i32) -> &'b mut i32 =
      f ; // WTF, we are dropping the constraint 'c : 'b ?
}
```

**Comment by eddyb** [comment]
cc @nikomatsakis

**Comment by petrochenkov** [comment]
Same as https://github.com/rust-lang/rust/issues/23051

**Comment by eddyb** [comment]
@petrochenkov Ahh I tried looking for an existing issue but I couldn't (wrong keywords used), thanks!

**Comment by jhjourdan** [comment]
Ah, indeed. Sorry for the noise. Closing.
