### ISSUE TITLE
`as_mut_ptr` causes "cannot borrow immutable borrowed content as mutable" error

### ISSUE THREAD

**Issue by Ryan1729** [rust-lang/rust#40511]
Given the following `static` is defined:

```rust
static mut API_STR: &'static [u8; 22] = b"A C API wants a char*\0";
```

The following code compiles just fine:
```rust
    unsafe {
        let a = API_STR.as_ptr() as *mut i8;
    }
```
but this code:

```rust
    unsafe {
        let a = API_STR.as_mut_ptr() as *mut i8;
    }
```

causes the following error:

```
error: cannot borrow immutable borrowed content as mutable
 --> src/main.rs:6:17
  |
6 |         let a = API_STR.as_mut_ptr() as *mut i8;
  |                 ^^^^^^^
```

If there's a good reason for this, at the very least the error message could be improved.

## Meta

`rustc --version --verbose`:
```
rustc 1.15.0 (10893a9a3 2017-01-19)
binary: rustc
commit-hash: 10893a9a349cdd423f2490a6984acb5b3b7c8046
commit-date: 2017-01-19
host: x86_64-unknown-linux-gnu
release: 1.15.0
LLVM version: 3.9
```

**Comment by bluss** [comment]
By the rules of Rust, there is a good reason.

The data is static to the program, and we have an *immutable* reference to it: `&'static [u8; 22]`.

The reference is stored in a mutable static. That means that we could change which reference is stored, does not mean we can mutate the data the reference points to.

**Comment by Ryan1729** [comment]
Ah, that makes sense. It would still be really neat if the compiler could recognize that this error is happening on an immutable reference stored in a mutable variable and in that case point out the part of the definition that is causing the problem.  Or if it is easier, maybe it could just unconditionally point to the part of the definition that would need to change as well as the usage in cases where a change in either may be the correct choice.

**Comment by bluss** [comment]
Best report a new issue for that or reformulate this one for clarity? (Issues should have a clear formulation of what the problem is/how they can be resolved.)

In this case you'd first consider if you can use something without `unsafe`, so not `static mut`, maybe you can use `CString` if you have access to libstd.

If you want mutable static data you'd store it directly:

```rust
static mut API_STR: [u8; 22] = *b"A C API wants a char*\0";
```
