### ISSUE TITLE
References/borrows of const values don't have `'static` lifetime

### ISSUE THREAD

**Issue by mzji** [rust-lang/rust#40522]
Example:
```rust
const FOO: usize = 0;

fn bar() -> &'static usize {
    &FOO
}

fn main() {
    bar();
}
```
Get error:
```
rustc 1.17.0-nightly (b1e31766d 2017-03-03)
error: borrowed value does not live long enough
 --> <anon>:5:6
  |
5 |     &FOO
  |      ^^^ does not live long enough
6 | }
  | - temporary value only lives until here
  |
  = note: borrowed value must be valid for the static lifetime...

error: aborting due to previous error
```

**Comment by jmesmon** [comment]
This is expected. From the signature of `bar()`, we can't know that `FOO` will have been borrowed afterwards.

Borrows will always be scoped by their inner-most block (like the function body).

You can, however, do this:
```
const FOO_: usize = 0;
const FOO: &'static usize = &FOO_;

fn bar() -> &'static usize {
    FOO
}

fn main() {
    bar();
}
```

**Comment by mzji** [comment]
@jmesmon Thanks for the solution! Actually I just solve my problem with this pattern. However I have a question: could we do inference here to give the reference a `'static` lifetime?

**Comment by Stebalien** [comment]
The problem here is [static promotion](https://github.com/rust-lang/rfcs/pull/1414). You can fix this by using `static`, instead of `const`:

```rust
static FOO: usize = 0;

fn bar() -> &'static usize {
    &FOO
}

fn main() {
    bar();
}
```

Basically, compile-time only so `&FOO` gets evaluated to `&0` (where `0` is a temporary) at compile-time.

**Comment by mzji** [comment]
After reading [the book](https://doc.rust-lang.org/book/const-and-static.html), I think I know the point showed by @Stebalien 's code. Thank you all!
