### ISSUE TITLE
Tracking issue for addition of eprint/eprintln macros

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#40528]
Tracking issue for for https://github.com/rust-lang/rfcs/pull/1869

@zackw would you be interested in sending a PR?

**Comment by zackw** [comment]
`>.>` Reopen #39229 and proceed from there?

**Comment by alexcrichton** [comment]
Sure yeah, want to resubmit that as a new PR?

**Comment by zackw** [comment]
Is it actually necessary to resubmit? Couldn't you just reopen the existing one?

**Comment by alexcrichton** [comment]
Let's stick with a new PR, easier on bors in general

**Comment by steveklabnik** [comment]
@zackw when you make your new PR, mind also adding an entry to https://github.com/rust-lang/rust/tree/master/src/doc/unstable-book ? It doesn't need to actually have docs in it. Check out any of the chapters for the little template.

**Comment by Mark-Simulacrum** [comment]
I think this was stabilized, though I don't see any discussion here. @alexcrichton Any idea where that happened? Closing anyway..

**Comment by zackw** [comment]
For the record, the code change was merged in #41192.

**Comment by alexcrichton** [comment]
Ah yes macros IIRC can't be stabilized in the same way as other items, so we added these as insta-stable.
