### ISSUE TITLE
Setting cxx in cargo.toml doesn't pass through to build.rs scripts such as in rustc_llvm

### ISSUE THREAD

**Issue by mstewartgallus** [rust-lang/rust#40534]
`rustc_llvm` has a custom `build.rs` script that calls the `gcc` crate and compiles bindings to LLVM. However, this doesn't call the C++ compiler passed in the cxx option in the cargo.toml configuration. Instead it just calls the default of `c++`. This ends up breaking builds for me because I want to use an up to date clang to compile rust instead of my distribution provided gcc which is too old. My current hacky workaround is to run `env CXX=clang++-3.8 CC=clang-3.8 ./x.py build`.

**Comment by Mark-Simulacrum** [comment]
This should be fixed if/when https://github.com/rust-lang/rust/pull/42206 is merged. Also, cc https://github.com/rust-lang/rust/issues/42255.

**Comment by jyn514** [comment]
This seems to have been fixed: https://github.com/rust-lang/rust/blob/9ef84076109ca9b6dd87fca7040781d778eb7605/src/bootstrap/native.rs#L645
