### ISSUE TITLE
LLVM memcpyopt

### ISSUE THREAD

**Issue by arthurprs** [rust-lang/rust#40553]
I can't open issues on rust-lang/llvm so I decided to open it here.

This llvm bug https://bugs.llvm.org//show_bug.cgi?id=28958#c5 and review https://reviews.llvm.org/D23470 looks abandoned even if the results looked surprisingly good.

I understand the reasons not to merge in llvm upstream but given the results on rustc alone it's probably worth merging it into rust-lang/llvm fork. It's small enough to be maintained across llvm updates.

**Comment by nagisa** [comment]
The PR wasn’t complete and the author concluded it would be easier to do the same within rustc, which we do now.

**Comment by nagisa** [comment]
https://github.com/rust-lang/rust/pull/36388

**Comment by arthurprs** [comment]
Very interesting, thank you.
