### ISSUE TITLE
rustdoc bug rendering constant section

### ISSUE THREAD

**Issue by SergioBenitez** [rust-lang/rust#40568]
This is a reopening of #40370, which is still not entirely fixed:

![screen shot 2017-03-15 at 9 53 57 pm](https://cloud.githubusercontent.com/assets/1480321/23982310/01077660-09ca-11e7-96ee-bd814df03826.png)

The type is `ContentType` without the `AngleBracketed { lifetimes: [], types: [], bindings: [] }`.

@GuillaumeGomez, @frewsxcv

**Comment by GuillaumeGomez** [comment]
This const thing will drive me crazy. :-/

Checking what's wrong.
