### ISSUE TITLE
rustdoc: should expect and interpret valid Markdown

### ISSUE THREAD

**Issue by projektir** [rust-lang/rust#40560]
rustdoc currently expects all Markdown files to start with the `%` symbol, turning that line into an `<h1>` heading with the corresponding title. The `%` symbol is not part of Markdown, and this notation seems unnecessary.

Instead, rustdoc should be able to read `#`, `##`, and so on, as expected, turning them into `<h1>`, `<h2>`, respectively, and then correctly numbering the child headings. The first heading in the file can be used for the title and table of contents parenting. This should fix #39850.

This will change rustdoc to additionally process the first `#` heading (or any first heading?) the way it currently processes the `%` heading.

I plan to work on this issue, but if anyone knows something about the history of `%` that could be useful information.

**Comment by steveklabnik** [comment]
> I plan to work on this issue, but if anyone knows something about the history of % that could be useful information.

I don't know why I want to say @cmr may, but maybe?

**Comment by Mark-Simulacrum** [comment]
I believe this is handled correctly today, closing.
