### ISSUE TITLE
Reducing build time under 2 hours for CircleCI

### ISSUE THREAD

**Issue by sjackman** [rust-lang/rust#40579]
I'm hoping to compile `rust` from source on CircleCI to build precompiled binary bottles of `rust` for Linuxbrew. Compiling using 13 threads exceeds the 4 GB memory limit of CircleCI, and compiling with 12 threads exceeds the 2 hour time limit. Any thoughts on reducing the build time of rust? Here's the compilation script (called a formula in Homebrew parlance):
https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/rust.rb#L86

Here's the downstream Linuxbrew PR: https://github.com/Linuxbrew/homebrew-core/pull/1953

Here's the failed CircleCI build runs: https://circleci.com/gh/Linuxbrew/homebrew-core/tree/pull/1953

**Comment by alexcrichton** [comment]
Currently we run the full test suite on all PRs (including bootstrap) and this currenly [takes ~1hr](https://travis-ci.org/rust-lang/rust/builds/211613647). I'd recommend taking a look at that configuration to see how we configure the build and such.

In general we're always open for build time improvements, but we've currently implemented everywhing we can think of, so I'm going to close this (as there's nothing outstanding we know of we can do)

**Comment by sjackman** [comment]
Thanks for your quick response, Alex, and the link to your Travis config. I'll take a look at it.

**Comment by sjackman** [comment]
@alexcrichton Can you tell me how many cores and how much memory is available to your TravisCI build?

**Comment by alexcrichton** [comment]
I believe on [this page](https://cloud.google.com/compute/docs/machine-types) we're with `n1-standard-4`, altough I'm not certain of that.

**Comment by sjackman** [comment]
> Standard 4 CPU machine type with 4 virtual CPUs and 15 GB of memory.

Hmm. I wonder why CircleCI is take more than 2 hours with 12 CPUs.
