### ISSUE TITLE
Travis: Add a tool to print timestamp in front of log messages

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#40577]
Often when debugging travis logs it's difficult to see how long everything is taking as we only time some steps, not all. Additionally there's not a lot of information to see how long it takes between steps.

It'd be awesome if we had a tool where we basically wrapped the entire build (`src/ci/run.sh`) in a process that simply prepended all stdout/stderr messages with a relative timestamp. AppVeyor does this by default (has a timestamp for each log line message) but unfortunately Travis doesn't.

Apparently [Julia has something like this](https://github.com/JuliaLang/julia/blob/102800a54343f58e798b97fd8946437ca95f2352/.travis.yml#L116) which ends up looking like https://travis-ci.org/JuliaLang/julia/jobs/211627387#L370 which is basically exactly what we'd want.

**Comment by tfheen** [comment]
You probably just want to use `ts` from moreutils for this. (This is what Julia does.)
