### ISSUE TITLE
Tracking issue for unstable sort in libcore

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#40585]
Tracking issue for https://github.com/rust-lang/rfcs/pull/1884

**Comment by scottmcm** [comment]
Is there any work needed here before stabilization?

**Comment by stjepang** [comment]
@scottmcm There isn't. The feature is implemented and documented.

The final stabilization PR will just have to add one sentence to the docs, that's it (see the FIXMEs in the code).

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

**Comment by dtolnay** [comment]
@rfcbot reviewed

**Comment by AurevoirXavier** [comment]
I'm curious if I compile it to native and wasm. I'll get the same ouput?
