### ISSUE TITLE
Subpar error message on `pub (ident) fn foo`

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#40599]
Someone who had code with the old `pub_restricted` feature is going to get pretty bad error message feedback:

```rust
#![feature(pub_restricted)]
mod a { pub (a) fn foo() -> i32 { 13 } }

fn main() {}
```

Here's the message you get (ever since `pub(in path)` was implemented, sometime after March 4th:

```
error: unmatched visibility `pub`
 --> pub_restricted.rs:2:9
  |
2 | mod a { pub (a) fn foo() -> i32 { 13 } }
  |         ^^^
```

(At the very least, it would be good if it highlighted `pub (a)` in its entirety, not just `pub`...)

Also, someone who *doesn't* know about pub restricted and just has a syntactic typo is also going to have problems here, since it is very confusing that the compiler seems to be saying that it doesn't know about the `pub` visibility, when that *is* one of the most fundamental visibilities.

**Comment by estebank** [comment]
#40627 proposes the following output for a given statement `pub (a) fn afn() {}`:

```rust
error: incorrect restriction in `pub`
  --> file.rs:15:1
   |
15 | pub (a) fn afn() {}
   | ^^^^^^^
   |
   = help: valid visibility restrictions are:
            - `pub`: visible on every module that imports this module
            - `pub(crate)`: visible only on the current crate
            - `pub(super)`: visible only in the current module's parent
            - `pub(in path::to::module)`: visible only on the specified path
            - `pub(self)` or ``: visible only in the current module
help: to make this visible only to module `a`, add `in` before the path:
   | pub (in a) fn afn() {}
```
