### ISSUE TITLE
Can't build from source

### ISSUE THREAD

**Issue by yongqli** [rust-lang/rust#40622]
Installing from source using `./x.py build && sudo ./x.py dist --install`, I get:

    Build completed successfully in 0:29:55
    Password:
    info: looks like you are running this command under `sudo`
          and so in order to preserve your $HOME this will now
          use vendored sources by default. Note that if this
          does not work you should run a normal build first
          before running a command like `sudo make install`
    error: failed to load source for a dependency on `num_cpus`

    Caused by:
      Unable to update registry https://github.com/rust-lang/crates.io-index

    Caused by:
      failed to update replaced source `registry https://github.com/rust-lang/crates.io-index`

    Caused by:
      failed to read root of directory source: /Users/yongqli/projects/rust/src/vendor

**Comment by russmack** [comment]
Similar to [https://github.com/rust-lang/rust/issues/40108](https://github.com/rust-lang/rust/issues/40108)

**Comment by Mark-Simulacrum** [comment]
Closing in favor of #40108.
