### ISSUE TITLE
`--emit=metadata` appears to override `--out-dir` if the latter is supplied first

### ISSUE THREAD

**Issue by abonander** [rust-lang/rust#40623]
See https://github.com/rust-lang/rust/pull/40542

Explicitly adding `--out-dir=$(TMPDIR)` (supposedly redundant) after `--emit=metadata` appeared to fix the problem, suggesting that `--emit=metadata` overwrites `--out-dir` (which is included in `$(RUSTC)`) with the current directory (?).

This may not depend on the exact value of `--emit`; Cargo always appears to write `--out-dir` after `--emit`, so that might explain why this hasn't really come up before.

**Comment by steveklabnik** [comment]
Triage: I'm pretty sure that I know how to do this, but any chance you could add exact steps to reproduce here, @abonander ?

**Comment by Enselic** [comment]
Triage: I'll go ahead and close this as I think it is reasonable to require bug reports like these to have step-by-step instructions on how to reproduce. Of course feel free to re-open after providing reproduction steps!
