### ISSUE TITLE
`".e0".parse()` returns `Ok(0.0)`

### ISSUE THREAD

**Issue by lifthrasiir** [rust-lang/rust#40654]
Yes, another incarnation of #30344. `+.e0` and `-.e0` also have this issue. Note that `".".parse()` *is* an error and has a test for it.

cc #32243

**Comment by rkruppe** [comment]
Does this also date back to 1.0, like #30344 did?

**Comment by lifthrasiir** [comment]
@rkruppe Yes. The fix would be technically a breaking change.
