### ISSUE TITLE
Block comment grammar

### ISSUE THREAD

**Issue by adiba** [rust-lang/rust#40650]
In all other languages such as C++, the first occurrence of `*/` marks the end of the block comment.
However, the compiler throws an error on the code below (`error: unterminated block comment`)
```
/* open 1
/* open 2
*/ close 1
// code
fn main(){
    //...
}
```

**Comment by djzin** [comment]
This is by design I believe. Basically if you are commenting out a large section of code that contains block comments, in rust it will work. If your editor is not highlighting it properly, I would contact whoever does the syntax highlighting (it works on the playground).

**Comment by adiba** [comment]
The playground works exactly the same. It's the _compiler_ that throws the error.
I'm actually happy with this design choice, it's just unusual :)
