### ISSUE TITLE
"use of undeclared lifetime name `'static`" is misleading

### ISSUE THREAD

**Issue by solson** [rust-lang/rust#40661]
**Code:** https://is.gd/6L8tEl

```rust
fn foo<'a: 'static>() {}
```

**Output:**

```
rustc 1.17.0-nightly (b1e31766d 2017-03-03)
error[E0261]: use of undeclared lifetime name `'static`
 --> <anon>:1:12
  |
1 | fn foo<'a: 'static>() {}
  |            ^^^^^^^ undeclared lifetime
```

**Expectation:**

`<'a: 'static>` is unnecessary (you can just use `'static` in place of `'a`), but maybe we should accept it? At any rate, the error message is misleading - `'static` is the one globally declared lifetime. If we want to reject this code, the error message should not imply `'static` is undefined, but rather that you just don't need the `'a` lifetime.

**Comment by jseyfried** [comment]
I believe we'll want to check for `'static` [here](https://github.com/rust-lang/rust/blob/b5c4244c6c46df22bb55531b629f4c314fe2ab22/src/librustc/middle/resolve_lifetime.rs#L920).

**Comment by eugene-bulkin** [comment]
The right move here would be to reject `'static` here because `'a` is superfluous in that scenario, right? I'm not entirely sure what the performance implications would be of just accepting it since it's the same as doing `foo<'static>`. 

Since it would be unnecessary, would be more appropriate to reject the code telling the user to just use `'static` instead?

**Comment by adamransom** [comment]
I'd like to work on this, if it is still open (and/or available for mentoring)!

**Comment by jseyfried** [comment]
@adamransom 
Yeah, go ahead! Feel free to ask questions here or ping me on IRC (`jseyfried` in `#rustc` or `#rust-internals`).

**Comment by jseyfried** [comment]
@eugene-bulkin 
> it's the same as doing `foo<'static>`

`fn foo<'static>() {}` [isn't allowed](https://play.rust-lang.org/?gist=3259c4c94ac641eb56730e1c8e8dd47a&version=nightly&backtrace=0).

> would [it] be more appropriate to reject the code telling the user to just use 'static instead?

I think it would appropriate to reject the code and tell the user not to use a lifetime parameter at all -- there's never a need for a parameter that must always be `'static`.

That being said, we also might want to allow it for consistency, perhaps with a warning (lint).
cc @rust-lang/lang @petrochenkov

**Comment by eugene-bulkin** [comment]
> `fn foo<'static>() {}` isn't allowed.

Oh, well in that case it makes even more sense to just warn the user that the parameter is unnecessary; an error might be overkill, but a warning would seem reasonable.

**Comment by adamransom** [comment]
@jseyfried Great, I'll work on adding a warning as we discussed in IRC.

**Comment by petrochenkov** [comment]
>I think it would appropriate to reject the code and tell the user not to use a lifetime parameter at all -- there's never a need for a parameter that must always be 'static.
>That being said, we also might want to allow it for consistency, perhaps with a warning (lint).

Both seems reasonable.
Maybe this warning can be shoehorned into some existing lint? Creating a new one just for this seems wasteful. (Maybe this should be an error just to avoid adding a new lint.)
