### ISSUE TITLE
doc.rust-lang.org - old versions of the documentation appear in Google

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust#40677]
Currently for the search: https://www.google.co.uk/search?q=rust+duration the first result links to docs from 1.6.0 where this feature was incomplete and unstable.

https://doc.rust-lang.org/robots.txt already excludes docs for pre-1.0 versions. Perhaps old post-1.0 version can be excluded too?

**Comment by GuillaumeGomez** [comment]
cc @steveklabnik

**Comment by steveklabnik** [comment]
I know nothing about how our robots.txt is managed.

https://github.com/rust-lang/rfcs/pull/1826 is related, as this will show a banner

**Comment by steveklabnik** [comment]
Closing this in favor of that RFC.
