### ISSUE TITLE
OSX builds on Travis sometimes aren't scheduled

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#40672]
Examples:

* https://travis-ci.org/rust-lang/rust/builds/212689339
* https://travis-ci.org/rust-lang/rust/builds/212947771

**Comment by CleanCut** [comment]
@alexcrichton  

Question: As an authorized TravisCI user, do you see a "Build" or "Rebuild" button on an individual OSX build that failed to run?  For example, on this page: https://travis-ci.org/rust-lang/rust/jobs/212689371

**Comment by CleanCut** [comment]
In both of the example links, there are both Linux and macOS builds that *started*, but were cancelled while running.  In addition, there are macOS builds that never started.

It appears that this may be a case of the entire build being cancelled before running to completion, and there were just more macOS builds at the end of the list...so they weren't started before the build was started.

I can't see from my public user whether the build was cancelled by a specific person, or by a feature like [auto cancellation](https://blog.travis-ci.com/2017-03-22-introducing-auto-cancellation), or something else.  I don't even know if TravisCI presents that information to privileged users.

**Comment by alexcrichton** [comment]
Oh thanks for the re-ping @CleanCut! So the problem here ended up being an upstream Travis issue which has since been fixed, so I'm going to close this.

To answer your questions, though, yeah we can definitely retry/cancel individual builds if necessary. The problem here was that the build was scheduled for a VM but some (presumably Travis) bug ended up making it so the build made no progress. That clogged our whole parallelism capacity with "queued" builds but nothing was making progress.

I've enabled auto cancellation as well now for PRs and branches, but unfortunately that probably wouldn't have helped this much :(

**Comment by CleanCut** [comment]
Okay, cool.  It's always nice when it's upstream's fault AND they fix it. ;-)

**Comment by Mark-Simulacrum** [comment]
I'm going to go ahead and reopen this because we've seen at least once, and I seem to recall more, that the OS X builders just don't start (e.g., #40672).

**Comment by kennytm** [comment]
@Mark-Simulacrum The PR link is wrong 😄 

The macOS machines typically [take more than 1 minutes to boot](https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments), and at most 216 builds can run simultaneously for the whole Travis (compared with the Linux ones which support over concurrent 700 builds). So probably the macOS doesn't start simply because is the queue is too long.

**Comment by Mark-Simulacrum** [comment]
Fixed the PR link. It's certainly possible that this is entirely out of our hands, but it'd be nice to track it anyway, I think.

**Comment by alexcrichton** [comment]
Ok, let's try to collect some samples over time to get an idea of frequency (along with concrete logs) and then we can look into emailing Travis.

**Comment by carols10cents** [comment]
I think I'm seeing some instances of this. Not sure if these links will stick around so taking screenshots.

On [Build #52099](https://travis-ci.org/rust-lang/rust/builds/228742236), I see 4 apple builds with a ❗️ status:

<img width="957" alt="screen shot 2017-05-08 at 10 12 50 am" src="https://cloud.githubusercontent.com/assets/193874/25808077/f603cec6-33d6-11e7-99ae-fca45a7650a4.png">

[Job #52099.37](https://travis-ci.org/rust-lang/rust/jobs/228742285) looks like this when I click into it:

<img width="963" alt="screen shot 2017-05-08 at 10 10 33 am" src="https://cloud.githubusercontent.com/assets/193874/25808129/2006a9e6-33d7-11e7-93a1-04a7d6b6d0ad.png">

The other 3 look the same as well. It just looks like they never started?

**Comment by carols10cents** [comment]
Saw 2 more of these in https://travis-ci.org/rust-lang/rust/builds/234609993 for #42142.

**Comment by ishitatsuyuki** [comment]
Another occurrence in #42167, without any backlog on status page.

**Comment by Mark-Simulacrum** [comment]
More cases in https://github.com/rust-lang/rust/pull/42275's normal PR run (w/o r+): xcode8.2, and all three xcode7 builders didn't start with the `!`.

**Comment by MaulingMonkey** [comment]
More cases in https://github.com/rust-lang/rust/pull/43221 (PR w/o r+) , 3 of 5 xcode builds `!`ed with blank logs:
* https://travis-ci.org/rust-lang/rust/builds/255471146
* https://travis-ci.org/rust-lang/rust/builds/256007222

**Comment by aidanhs** [comment]
https://travis-ci.org/rust-lang/rust/builds/266074368
https://travis-ci.org/rust-lang/rust/builds/266074915

I've dropped Travis an e-mail. Please nobody cancel the above, I'm hoping a live example might help them fix, and since it's RustConf I figure the PR queue might be slow for a few days :)

**Comment by aidanhs** [comment]
The upstream infra provider for travis has restarted a faulty host. Apparently this should improve things and any builds from this point on should not hang on starting OSX (already-started builds may stay hanging). I guess now we wait and see.

**Comment by aidanhs** [comment]
Not seen this for a while, closing.
