### ISSUE TITLE
Incorrect FileCheck path on msvc and RelWithDbgInfo

### ISSUE THREAD

**Issue by TimNN** [rust-lang/rust#40680]
When compiling for msvc and using a `RelWithDbgInfo` LLVM, an incorrect path to `FileCheck.exe` is used ([hardcoded to `Release/bin`](https://github.com/rust-lang/rust/blob/master/src/bootstrap/lib.rs#L773)).

I find the exact conditions which determine the directory to use a bit confusing.

**Comment by alexcrichton** [comment]
I also find the directory layout of an LLVM build confusing ;_;

**Comment by wesleywiser** [comment]
Looks like this was fixed in #50961.

https://github.com/rust-lang/rust/blob/256721ee519f6ff15dc5c1cfaf3ebf9af75efa4a/src/bootstrap/lib.rs#L803-L815
