### ISSUE TITLE
Rustdoc: Visual indentation of function return type looks funky

### ISSUE THREAD

**Issue by killercup** [rust-lang/rust#40687]
I have [a function](https://docs.rs/waltz/0.3.0/waltz/fn.extract_code_blocks.html) with this signature:

```rust
pub fn extract_code_blocks<'md, I: Iterator<Item=Event<'md>>>(md_events: I) -> Result<Vec<CodeBlock>, Error>
```

So far so good. In the original source, it's all on one line, but Rustdoc uses quite a large font, so it makes sense to split it up. The problem is with the way it tries to reformat the signature, i.e., by putting the return type directly beneath the opening bracket of the arguments:

<img width="920" alt="bildschirmfoto 2017-03-20 um 22 05 26" src="https://cloud.githubusercontent.com/assets/20063/24122359/d5473bfa-0dbb-11e7-9c4c-1397c8049d46.png">

And while it doesn't look great on a wide screen, resizing the window makes it look just broken:

<img width="673" alt="bildschirmfoto 2017-03-20 um 22 05 31" src="https://cloud.githubusercontent.com/assets/20063/24122376/e88cb9c4-0dbb-11e7-9bd7-ce6f9120245d.png">

<img width="485" alt="bildschirmfoto 2017-03-20 um 22 05 38" src="https://cloud.githubusercontent.com/assets/20063/24122377/e8aef8a4-0dbb-11e7-9196-d7d48e2f412f.png">

To get a good idea how to format functions it might be wise to check the discussion of the fmt team in <https://github.com/rust-lang-nursery/fmt-rfcs/issues/39>, but I don't think Rustdoc has the same constraints as rustfmt.

In particular, I would render the function signature quoted above as:

```rust
pub fn extract_code_blocks<'md, I: Iterator<Item=Event<'md>>>(
    md_events: I,
) -> Result<Vec<CodeBlock>, Error>
```

alternatively,

```rust
pub fn extract_code_blocks<'md, I: Iterator<Item=Event<'md>>>
    (md_events: I)
    -> Result<Vec<CodeBlock>, Error>
```

or even (introducing where clauses):

```rust
pub fn extract_code_blocks<'md, I>(md_events: I)
    -> Result<Vec<CodeBlock>, Error>
    where I: Iterator<Item=Event<'md>>
```

**Comment by GuillaumeGomez** [comment]
```rust
pub fn extract_code_blocks<'md, I: Iterator<Item=Event<'md>>>(
    md_events: I)
    -> Result<Vec<CodeBlock>, Error>
```

I propose this one (because I don't like when ')' starts a new line).

**Comment by QuietMisdreavus** [comment]
After some discussion in #rust-docs, I noticed that the first style mentioned is pretty close to [how the fmt-rfcs issue about function signatures](https://github.com/rust-lang-nursery/fmt-rfcs/issues/39#issuecomment-278544439) wound up. It's also suspiciously close to my initial implementation when I first put that indentation code in. I'll see about sketching out this change.

**Comment by retep998** [comment]
That first alternative is in fact block indentation which is what that rustfmt RFC agreed on. As a result, rustdoc should reflect that decision and switch to block indentation for all function definitions in generated documentation.

**Comment by QuietMisdreavus** [comment]
Got an initial implementation sketched out. Should I adjust where clause indentation at the same time, since those guidelines have changed since that implementation?

![rustdoc fn redux](https://cloud.githubusercontent.com/assets/5217170/24208314/505aa92c-0ef1-11e7-9614-afd03190ced4.PNG)

**Comment by GuillaumeGomez** [comment]
@QuietMisdreavus: Since you're already on it, try to catch up the format RFC. :)

**Comment by killercup** [comment]
> Should I adjust where clause indentation at the same time, since those guidelines have changed since that implementation?

I'd say go for it, the current style is shown out [here](https://users.rust-lang.org/t/new-style-guidelines/10037), or [in this example](https://github.com/rust-lang-nursery/fmt-rfcs/blob/f82ba2077f813f003b3507801135beda5634b43b/example/lists-elided.rs#L89-L98).

**Comment by Mark-Simulacrum** [comment]
I believe this is fixed today.

![image](https://user-images.githubusercontent.com/5047365/27093438-ebe0700c-5023-11e7-9153-4b8c2afab6ee.png)
![image](https://user-images.githubusercontent.com/5047365/27093456-fd90452a-5023-11e7-9423-eb8d582e9271.png)
