### ISSUE TITLE
Building rocket-codegen 0.2.2 fails on latest nightly (2017-03-21)

### ISSUE THREAD

**Issue by Jaspi10** [rust-lang/rust#40695]
Could successfully build it on 2017-03-19, but also does not work an 03-20.

Log from `cargo run --verbose`:

[cargo run --verbose .txt](https://github.com/rust-lang/rust/files/857218/cargo.run.--verbose.txt)

**Comment by est31** [comment]
I think this is rather an issue with Rocket, as it relies on unstable features, and judging from the error an API just changed, which is normal with unstable features.

Instead you should try filing an issue on the tracker of Rocket: https://github.com/SergioBenitez/Rocket/issues

cc @SergioBenitez

**Comment by est31** [comment]
Mhh maybe this issue is related: https://github.com/SergioBenitez/Rocket/issues/235

**Comment by SergioBenitez** [comment]
There's a bug (https://github.com/rust-lang/rust/issues/40663, fixed in unmerged https://github.com/rust-lang/rust/pull/40664) in the latest nightly preventing a meaningful fix for this. See https://github.com/SergioBenitez/Rocket/issues/235#issuecomment-287714276 for more details.

**Comment by SergioBenitez** [comment]
This is no longer relevant as the latest nightly/Rocket work well together.
