### ISSUE TITLE
API to split owned Vec into owned Vec chunks

### ISSUE THREAD

**Issue by NeoLegends** [rust-lang/rust#40708]
I just came across the situation where it would be very useful to be able to split a `Vec` into several owned chunks just like `std::slice::Chunks` without an additional allocation. It seems to me like one would only have to update some pointers and lengths. `split_off` (unfortunately) allocates, so it cannot really be used for performance-critical paths.

How are your thoughts on such an API? Is this even possible with most allocators?

**Comment by sfackler** [comment]
I don't believe this is possible with any allocator Rust currently supports.

**Comment by jmesmon** [comment]
It _might_ be possible without breaking Vec's current public API, but consider that we'd need to ref-count the memory allocation backing the Vec (as multiple Vec's now can refer to (different pieces of) the same memory allocation). And further accounting about what is still in use would need to be kept for more efficient memory utilization (ie: to prevent us from having 1 ref left keeping a massive allocation alive).

There may be a place for a data structure that supports that (perhaps as simple as `{offs: usize, len: usize, data: Arc<Vec<T>>}`), but it doesn't seem like it would be `Vec` itself.

**Comment by NeoLegends** [comment]
Ah, so it's not possible to yield (nomoverlapping) fragments of a previous allocation back to the allocator?

**Comment by sfackler** [comment]
Yep. The only pointers you can pass to free are those returned from malloc.

**Comment by NeoLegends** [comment]
So do you wanna close this or keep it in the backlog?

**Comment by steveklabnik** [comment]
We don't usually let minor feature requests like this stay open, as adding them is "send in a PR please!" and that's not possible. So I'm gonna give it a close. Someday maybe though! 😄

**Comment by NeoLegends** [comment]
Yeah I was just wondering because you moved some labels around. I might come back to this once its possible and once I am in need of something like this again. ;) In the meantime, I think I'll stick to [bytes](https://crates.io/crates/bytes) instead.
