### ISSUE TITLE
Move the main respo to GitLab + additional mirrors?

### ISSUE THREAD

**Issue by ROCKNROLLKID** [rust-lang/rust#40716]
Hello.

I am really enjoying Rust language and it's starting to turn out to be a great alternative to C. I love how everything you do, you release a source code, but I must admit it is a bit of a shame that you use GitHub as the main respo. What about moving the main respo to GitLab, which is open-source and it's very similar to GitHub in almost every way, if not better, and just keeping GitHub as a mirror instead.

Also, maybe you could mirror the project to SourceForge and CodePlex. SourceForge still has a pretty decent community, even after the admin disaster and CodePlex gives a portion of ad money to the projects, so as long as the ads were clicked on your project page. I know a lot of people use ad blockers these days, but you never know maybe some people would be willing to click on a few to help out.

Just a suggestion which I would think would help Rust out some.

**Comment by cuviper** [comment]
FWIW, many of the repos are already mirrored on GitLab: https://gitlab.com/rust-lang/
(unofficial, currently owned by @carols10cents and @frewsxcv )

**Comment by bstrie** [comment]
We're on Github for the network effects, the benefits of which are easily visible (compare rust-lang/rust to golang/go, the latter of which has fewer than half as many unique contributors, which I believe is a symptom of spending most of its life on Google Code). I do believe that we should support open source projects, and I also believe it's valuable to have an escape route plotted in case something catastrophic happens, but for the moment it would just be counterproductive and extremely disruptive to migrate off of Github (especially considering all the other infrastructure changes recently which we can barely absorb).

**Comment by steveklabnik** [comment]
hi @ROCKNROLLKID ! We try to keep the issues tracker for bugs only, and not discussion issues like this. A major change like this would require an RFC, but the best thing to do would be to open a topic on the internals forum, https://internals.rust-lang.org/ to have this discussion, and then if it's received positively, write the RFC after. Thanks!
