### ISSUE TITLE
AsciiExt docs are incorrect

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#40714]
https://doc.rust-lang.org/stable/std/ascii/trait.AsciiExt.html

> Extension methods for ASCII-subset only operations on string slices.

but at the bottom

```rust
    impl AsciiExt for str
    impl AsciiExt for [u8]
    impl AsciiExt for u8
    impl AsciiExt for char
```

That is, they are not just for string slices, but also for `u8` slices, `u8`, and `char`.

I'm not sure what the right wording is here, exactly, maybe just drop the whole 'on string slices' bit.

I'm happy to mentor anyone who wants to tackle this issue.

**Comment by alanstoate** [comment]
I'm interested in working on this

**Comment by steveklabnik** [comment]
@alanstoate awesome! please let me know if you need any help at all, very happy to do so.

**Comment by alanstoate** [comment]
@steveklabnik since all the examples on that page are using char's would it be worth updating one or two to show other types being used? 

e.g
```rust
let ascii_uint = 97;         // 97 represents ascii 'a'

assert_eq!(65, ascii_uint.to_ascii_uppercase()) // 65 represents ascii 'A'
```

**Comment by steveklabnik** [comment]
That'd be nice as well, yeah

**Comment by mrhota** [comment]
@steveklabnik looks like the linked PR is merged, so maybe you can close this?
