### ISSUE TITLE
Standard traits not derived for function pointers with different calling conventions

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#40710]
```rust
use std::fmt::Debug;
use std::hash::Hash;

fn a<T: Hash + Ord + Eq + Clone + Debug>() {}

fn main() {
    a::<fn()>(); //OK
    a::<extern fn()>(); //OK
    a::<extern "C" fn()>(); //OK
    a::<extern "win64" fn()>(); //Error
    a::<extern "system" fn()>(); //Error
}
```

Errors:

```
error[E0277]: the trait bound `extern "win64" fn(): std::clone::Clone` is not satisfied
error[E0277]: the trait bound `extern "win64" fn(): std::cmp::Eq` is not satisfied
error[E0277]: the trait bound `extern "win64" fn(): std::cmp::Ord` is not satisfied
error[E0277]: the trait bound `extern "win64" fn(): std::fmt::Debug` is not satisfied
error[E0277]: the trait bound `extern "win64" fn(): std::hash::Hash` is not satisfied
error[E0277]: the trait bound `extern "system" fn(): std::clone::Clone` is not satisfied
error[E0277]: the trait bound `extern "system" fn(): std::cmp::Eq` is not satisfied
error[E0277]: the trait bound `extern "system" fn(): std::cmp::Ord` is not satisfied
error[E0277]: the trait bound `extern "system" fn(): std::fmt::Debug` is not satisfied
error[E0277]: the trait bound `extern "system" fn(): std::hash::Hash` is not satisfied
```

**Comment by petrochenkov** [comment]
See https://github.com/rust-lang/rust/issues/38848#issuecomment-270906268 for the reasons.

**Comment by jethrogb** [comment]
I guess the cause for this is similar to reasons that various traits are not defined for very long tuples, arrays over 32 elements, etc. Should the compiler insert the necessary definitions automatically when needed?

**Comment by jonas-schievink** [comment]
The tuple case can be handled via variadic generics. The fn pointer case, not so much (unless all of them implement a suitable common trait by magic).

**Comment by jethrogb** [comment]
fn-pointer case could also be handled by variadic generics, for the argument list at least. Then you just need one entry per calling convention which hopefully doesn't result in too much bloat. Array case could of course be handled by integer generics.

Are variadic generics something that is seriously considered for Rust's future? If so, we probably still need some kind of stop-gap measure here. If not, we'll need a more definitive solution here.

**Comment by jonas-schievink** [comment]
> Are variadic generics something that is seriously considered for Rust's future?

Well, there's https://github.com/rust-lang/rfcs/pull/1935

**Comment by asquared31415** [comment]
Update: the example code now compiles.
