### ISSUE TITLE
Rustdoc sidebar style change negatively impacts `src` view

### ISSUE THREAD

**Issue by Cldfire** [rust-lang/rust#40724]
What it looks like on [nightly docs](https://doc.rust-lang.org/nightly/src/std/lib.rs.html):

![top_nightly](https://cloud.githubusercontent.com/assets/13814214/24180888/e53ca784-0e8d-11e7-999e-9c679b2004b6.png)

![bottom_nightly](https://cloud.githubusercontent.com/assets/13814214/24180898/f647b6f4-0e8d-11e7-81a7-9203409d0f6b.png)

The strange color change on the side with the new sidebar style looks kind of tacky (especially at the bottom) and was probably not intended.

Currently on [stable docs](https://doc.rust-lang.org/src/std/lib.rs.html):

![top_stable](https://cloud.githubusercontent.com/assets/13814214/24180911/1405c35c-0e8e-11e7-8513-b9619ff1f77d.png)

![bottom_stable](https://cloud.githubusercontent.com/assets/13814214/24180916/201b5896-0e8e-11e7-9a96-2b489bd98ff4.png)

**Comment by steveklabnik** [comment]
This is also broken on beta, tagging as such.

**Comment by wesleywiser** [comment]
I'm looking into this. I see three potential options:

1. Make the sidebar white on the src pages. This would look the same as the old styling.
2. Shrink the width of the src view so it doesn't overlap with the sidebar. The sidebar is empty on src pages though so this looks kind of weird. If the sidebar retained its items from the other doc pages, this might look nice.
3. Make the sidebar color and the background of the code block match so there isn't slightly different shades of grey on top of each other. 

I'm leaning toward option 1 for now but I think option 2 might be worth considering in the future. Thoughts?

**Comment by Cldfire** [comment]
While I am certainly not the most qualified to weigh in on this, my thoughts would be that 3 is less than desirable (having a random grey stripe on the left side looks out-of-place regardless of whether the color matches or not), 2 would unnecessarily decrease the usability of `src` pages by decreasing the amount of horizontal space available to the code, and 1 is likely the best option.

**Comment by steveklabnik** [comment]
1 seems good

**Comment by wesleywiser** [comment]
Ok. Option 1 it is!
