### ISSUE TITLE
Run non-native tests on real device?

### ISSUE THREAD

**Issue by mmatyas** [rust-lang/rust#40733]
I see there is now support for running the test suites in QEMU emulators (#39400). Unfortunately, multithreaded tests tend to throw panics, so instead of a rootfs, I'd like to send them to a real hardware for better results. Would this be possible? I'm mainly thinking about generic ARM/Linux devices, not something like Android phones.

cc @alexcrichton

**Comment by alexcrichton** [comment]
Right now we're unfortunately not really equipped to deal with this right now infrastructure-wise. We have pretty strict uptime requirements on our infrastructure in the sense of if anything goes down then nothing can make progress.

If we really do want to go down this route it would look like:

1. Develop a daemon to schedule builds
2. Hook the daemon up to github webhooks
3. Implement the daemon updating the commit status through the github API
4. Hook the build up to the bors queue, don't gate on it
5. Watch it work for a few weeks
6. Turn on gating by default if we're comfortable

Unfortunately that's quite a lot of work, and the payoff doesn't seem to be proportional to the investment required right now.

**Comment by alexcrichton** [comment]
At this time this is such an ambitious project (and such a massive investment on our part) that I don't think it will be facilitated by having an issue open for this unfortunately. We also do not have immediate plans for implementing and supporting this, so I'm going to close this.
