### ISSUE TITLE
An improvement of box syntax

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#40741]
I'd like this code to be supported:

```
#![feature(box_syntax)]
type ArrType = [u32; 100];
fn main() {
    let a = box ArrType;
}
```

Currently you have to use something like this (it's not DRY because you have to repeat [0;100] on the right, making the definition of the ArrType type kind of useless):
```

#![feature(box_syntax)]
type ArrType = [u32; 100];
fn main() {
    let a: Box<ArrType> = box [0; 100];
}
```

**Comment by krdln** [comment]
```rust
let a: Box<ArrType> = Default::default()
```

should work. Unfortunately only for array sizes up to 32. This will be fixed in the future though.

**Comment by durka** [comment]
@krdln that could be shorter

```rust
let a = box ArrType::default();
```

Another possibility (without `Default`) is this:

```rust
type ArrType = [u32; 100];
const ARR_TYPE_INIT: ArrType = [0; 100];

let a = box ARR_TYPE_INIT;
```

**Comment by leonardo-m** [comment]
I didn't know default() is so capable. Once Rust supports arbitrarily sized fixed-sized arrays this syntax becomes acceptable (but I didn't see this syntax in the Rust manual. If it's absent then it's worth adding):

`let a: Box<ArrType> = Default::default();`

So I close down the issue.
