### ISSUE TITLE
Macros show up in rust docs when `pub use`'d

### ISSUE THREAD

**Issue by jrobsonchase** [rust-lang/rust#40768]
From my understanding, macro re-export is unstable and feature-gated, but macros are showing up in rust docs when, for example, I have:

```rust
#[macro_use]
extern crate log;
pub use log::*;
```

Which would seem to imply that they should be accessible from other crates, even though they can't.

rustc version:
    rustc 1.17.0-nightly (134c4a0f0 2017-03-20)

cc @jseyfried

**Comment by jseyfried** [comment]
@Pursuit92 
`use` with macros should be feature-gated, but glob imports can bypass the feature gate (this is a bug -- the feature gate only got implemented for single imports).

That being said, we want to stabilize `#![feature(use_extern_macros)]` as is this cycle, so I don't think this is worth gating this gating today and breaking [procedural-masquerade](https://github.com/rust-lang/rfcs/pull/1913#issuecomment-282900156).

**Comment by brson** [comment]
Apparently this [allows stable reexport of macro_rules macros](https://github.com/rust-lang/rust/issues/29638#issuecomment-298517765), not on purpose. Seems like this should be addressed.

**Comment by SimonSapin** [comment]
We have been shipping for several months code that relies on stable reexporting of macro_rules macros. Please don’t break this now.

**Comment by jechas01** [comment]
I disagree with the notion that we shouldn't fix bugs just because there might be code that relies on the incorrect behavior. That's how we end up with windows-esque insanity where bugs from back in the DOS days get forward ported rather than fixed to actually match the spec.

**Comment by SimonSapin** [comment]
> there might be code

There definitely is, this is not theoretical.

> the incorrect behavior

This behavior is not incorrect: it is working perfectly as intended. The only part that wasn’t intended is making that behavior available on the stable channel yet.

There is also no other way to achieve this on today’s stable rust, so "fixing" this accidental stabilization would be a regression in functionality.

**Comment by jechas01** [comment]
There was also some code in existence (some of mine included) that relied on Go's built-in hashmaps being consistently ordered between separate `range` iterations, even though the spec explicitly said that iteration order was not guaranteed and should be considered random. That doesn't mean, IMO, that it was a mistake to change iteration order to truly be random and break everything that depended on it. They were just wrong in their reliance on an implementation detail.

And there are plenty of things that aren't possible in stable rust. The fact that something was made possible by mistake is no reason to get stuck with a feature design that may or may not be how it would eventually end up.

**Comment by jseyfried** [comment]
@jechas01 
> no reason to get stuck with a feature design that may or may not be how it would eventually end up.

There's wide agreement that this is how it will end up, so there's very little risk of this. We almost stabilized `use_extern_macros` a couple of release cycles ago but wanted to avoid advertising it until declarative macros 2.0 was further along (we could re-evaluate now that declarative macros 2.0 is landed behind a feature gate).

**Comment by nikomatsakis** [comment]
I don't really know what's going on. @jseyfried -- what is your recommended course of action here?

**Comment by jseyfried** [comment]
Recommended course of action is to stabilize `#![feature(use_extern_macros)]`, but there's no hurry.

**Comment by nikomatsakis** [comment]
Recategorizing as a @rust-lang/t-dev-tools-docs issue, since this appears to be a rustdoc limitation, though I think @jseyfried's recommendation (that we stabilize the underlying feature) may be wise. @jseyfried -- what is the relevant tracking issue?

**Comment by arielb1** [comment]
See https://github.com/rust-lang/rust/issues/40768#issuecomment-315887709

**Comment by nikomatsakis** [comment]
Er, I take it back, sorry doc-tools team =)

**Comment by aturon** [comment]
Lang team discussed in meeting. Conclusion was: we don't want to break code working today, and would prefer to push toward stabilization of re-exports. @withoutboats will take action on the applicable tracking issue.

**Comment by jseyfried** [comment]
Most relevant tracking issue is https://github.com/rust-lang/rust/issues/35896.

**Comment by jrobsonchase** [comment]
No longer relevant as of the stable 1.30 release, closing!
