### ISSUE TITLE
I found a HUGE BUG WALLHACK 

### ISSUE THREAD

**Issue by franco2k17** [rust-lang/rust#40784]
Hi Plz contact me in twitter Its a huge Wallhack bug My brother is a spanish youtuber and his making a video about it

Contact me in twitter fast!   @francoocerro

Thanks hope i can fast (This bug works for everyone but its not that ez to find it contact me fast plz)

**Comment by franco2k17** [comment]
I can pass you the video + photos

**Comment by retep998** [comment]
This repo is for Rust the _programming language_. Wallhack sounds like you're talking about Rust the _game_ which is very different.

**Comment by franco2k17** [comment]
Its a bug that you can see thru walls i can pass video + photos Plz Talk to my twitter i don't feel like saying it here because everyone is going to know , I want to owner to reply me this is a big bug problem that they have to fix

**Comment by franco2k17** [comment]
Tellme where do i report plz!

**Comment by retep998** [comment]
Probably https://support.facepunchstudios.com/hc/en-us/requests/new

**Comment by franco2k17** [comment]
you got any idea if i can be paid by finding a bug?

**Comment by retep998** [comment]
I have no idea because I have no relation whatsoever to Rust the game. I only deal with Rust the programming language which does not have bug bounties at the moment.

**Comment by franco2k17** [comment]
Ok Hopefully they talk to me as soon as posible its a huge bug

**Comment by haniokasai** [comment]
XD
