### ISSUE TITLE
Exclude internal benches from rustc test harness

### ISSUE THREAD

**Issue by Robbepop** [rust-lang/rust#40781]
This is a re-post from [this](https://github.com/rust-lang/cargo/issues/3853) Cargo issue as [alex c.](https://github.com/alexcrichton) pointed me to file an issue here.  

**The Problem**

Currently `rustc --test` excludes benches in the `benches/` folder and includes internal benches within the crate.

Besides this assymetric behaviour functions annotated with `#[bench]` may be very compute intense, by definition and should be excluded from cargo test by default since they add high overhead whenever the test suite is running.

**Conflicting ...**

This issue conflicts with [#2984](https://github.com/rust-lang/cargo/issues/2984) that proposes to include benches in the `benches/` directory for cargo test which I am strictly against! To solve the problems issue [#2984](https://github.com/rust-lang/cargo/issues/2984) tries to target it should be possible to mark `#[bench]` tests with an additional `#[test]` attribute in order to include them for cargo test:

```rust
#[bench] #[test]
fn foo(b: &mut Bencher) { .. }
```

A current ugly work around to exclude benches from running with `cargo test` is to add a crate feature (e.g. a feature called `run_internal_benches`) and invoke `cargo bench` as `cargo bench --features run_internal_benches`. This works as intended but is ugly. An example crate can be found [here](https://github.com/Robbepop/prophet).

**Alternative**

Another thing we could think about is to introduce a flag for cargo test to include benches while the default should be set to exclude them.

 **Do not confuse testing with benchmarking:**

- Tests are for testing the functionality of the system and should be performed often and should be as low-overhead as possible.
- Benchmarks are often high-overhead and should be run whenever performance critical changes have been made.

**Comment by Enselic** [comment]
Triage: Closing since
* changing this would be a breaking change with a lot of process overhead to change
* it is in many cases easy to avoid benches from being run with `--test` by putting them in `benches/` instead
* if we don't close this issue now it is likely to just stay open year after year with nothing happening, distracting from triage of other issues
* the referenced cargo issue was closed as "won't fix"
