### ISSUE TITLE
Borrowchecker README.md

### ISSUE THREAD

**Issue by GAJaloyan** [rust-lang/rust#40793]
Hi,

While going through the documentation of the [borrowchecker](https://github.com/rust-lang/rust/blob/master/src/librustc_borrowck/borrowck/README.md), I found that the section **Checking mutability of immutable pointer types** is repeated twice, which is probably a mistake (the second one should be aliasability). Same thing for mutable pointer types.

Is it a mistake or is it intended ?

I was also wondering if there is some newer documentation about Rust's borrow checker and where it is available (this one dates from 2015).

Thanks in advance.

**Comment by steveklabnik** [comment]
Seems like a mistake, yes.

> I was also wondering if there is some newer documentation about Rust's borrow checker and where it is available (this one dates from 2015).

The book is the only other thing, officially.

**Comment by GAJaloyan** [comment]
All right, I created a pull request for the README.md

> The book is the only other thing, officially.

I'll be going through the code then. Thanks for the info.

**Comment by steveklabnik** [comment]
PR was merged, this can be closed.
