### ISSUE TITLE
Debuginfo tests spurious failures on MinGW

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#40835]
## Hangs forever

* https://ci.appveyor.com/project/rust-lang/rust/build/1.0.2565/job/scag42v11o50nymd
* https://ci.appveyor.com/project/rust-lang/rust/build/1.0.2561/job/6rc6qx2aqfrev0xc

Likely #40777 (or at least, the part of it that is a fix to #40184).

## `ContinueDebugEvent failed`

* https://ci.appveyor.com/project/rust-lang/rust/build/1.0.2585/job/xj2um43xtyckj505

**Comment by alexcrichton** [comment]
Agreed that https://github.com/rust-lang/rust/pull/40777 seems very suspect here.

**Comment by alexcrichton** [comment]
I'm gonna retitle this to other issues we're seeing on debuginfo for MinGW as well
