### ISSUE TITLE
Add switch "--std=some-rust-version" to guarantee compatibility

### ISSUE THREAD

**Issue by ibotty** [rust-lang/rust#40843]
AFAIK, there has not been a breaking change after rust 1.0, and none is planned. And I know you are taking backward compatibility very serious. So that issue is only about external confidence in that guarantee.

I expect that there will be a time when a breaking change has to be done (working with Haskell has taught me that much). Now if the compiler could guarantee that it will have a switch to guarantee "at least"-behavior (i.e. might accept later additions to the language, but not language changes), there will be a huge boost in confidence in rust's backward compatibility story.

So if you compile with rust 1.16 today any new compiler should support that code with that switch. It would be great to codify an "We only guarantee 20 years of rust backwards compatibility" to be able to remove code at one point though.

NB: A [random reddit comment complaining about backwards compatibility guarantees](https://np.reddit.com/r/cpp/comments/61mbgy/things_i_love_about_rust_while_being_a_c/dffpk4i/) inspired that issue.

**Comment by retep998** [comment]
>AFAIK, there has not been a breaking change after rust 1.0

False, there have multiple breaking changes in Rust since 1.0.

Anyway, if you'd like to propose a new feature, this is the wrong place to do so. You'd want to either do it in the [RFCS repo](https://github.com/rust-lang/rfcs) or on [IRLO](https://internals.rust-lang.org/).
