### ISSUE TITLE
Nonexisting macro is silently accepted in trait definition block

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#40845]
This compiles successfully on beta and nightly, but it should be an error.

```rust
trait Trait {
    wut!{ }
}

fn main() {
}
```
[(playground link)](https://play.rust-lang.org/?gist=c77a24bd3f8d440c5808dd348a0793f1&version=nightly&backtrace=0)

### Actual Result:

The program compiles successfully.

### Expected Result:

Compilation error (Rust 1.16 does this correctly)

```rust
rustc 1.16.0 (30cf806ef 2017-03-10)
error: macro undefined: 'wut!'
```

**Comment by jseyfried** [comment]
Fixed in #40849.
