### ISSUE TITLE
Floating Point Rounding Issue

### ISSUE THREAD

**Issue by centrual** [rust-lang/rust#40868]
Hello rust family;

I tried rust in https://www.rust-lang.org/en-US/ but the last result is not right. It must be 1.5 also if it's automatically rounds than 1.5 must be round to 2 default. Test code:

```
fn main() {
    // A simple integer calculator:
    // `+` or `-` means add or subtract by 1
    // `*` or `/` means multiply or divide by 2

    let program = "+ + * - /";
    let mut accumulator = 0;

    for token in program.chars() {
        let action_val = if token == '+' || token == '-' { 1 } else if token == '/' || token == '*' { 2 } else {0};
        
        if action_val != 0 {
          println!("accumulator({}) {} {} =", accumulator, token, action_val);
        }
        
        match token {
            '+' => accumulator += 1,
            '-' => accumulator -= 1,
            '*' => accumulator *= 2,
            '/' => accumulator /= 2,
            _ => { /* ignore everything else */ }
        }
        
        if action_val != 0 {
          println!("{}", accumulator)
        }
    }

    println!("The program \"{}\" calculates the value {}",
              program, accumulator);
}
```

**Comment by ranma42** [comment]
The very first comment in the file mentions that it is
```
// A simple integer calculator:
```
It does not perform floating point computations.

**Comment by centrual** [comment]
I know it is integer calculator, my point is `round( 1.5 )` must be `2` not `1`

**Comment by retep998** [comment]
The program `+ + * - /` corresponds to `((0+1+1)*2-1)/2` which simplifies down to `3/2`. Since this is *integer* division we are doing here, that means division *truncates* down to `1`, it does not round up to `2`. This is intended behavior.

**Comment by dns2utf8** [comment]
Hello @centrual 

Pure integer division does not have any rounding inplace per defintion.
I made an example, where I balanced the rounding error for the case where the division lands on `X.5` and introduced rounding in all other cases: [Run on Play](https://play.rust-lang.org/?gist=4e19cc5120094fc29375f7f847eea3f0&version=stable)
Introducing floating point numbers introduces problems on their own, read this [very good article](http://blog.reverberate.org/2014/09/what-every-computer-programmer-should.html) if you would like.

Regards

**Comment by niconii** [comment]
@centrual This definition of integer division (truncation rather than rounding) is standard for computers. There are a few reasons why this is the case, but it might make more sense if you consider the `%` operator, which calculates a remainder.

```rust
fn main() {
    let s = 599;

    println!("{} seconds = {} minutes {} seconds", s, s / 60, s % 60);
}
```

This code prints `599 seconds = 9 minutes 59 seconds`.

If `599 / 60` produced `10` by rounding, this would incorrectly read `599 seconds = 10 minutes 59 seconds` instead.

**Comment by centrual** [comment]
Thank you so much for explanation. I started with C# (~1 year) and continued with php(~10 years). I think i missed the concepts of real computer languages ☺️  I learned one more thing.

This language is amazing by the way. It's like combination of C# and php. High speed, easy to learn. So great job!
