### ISSUE TITLE
Repeated coercion ICE for an erroring indexing expression since 1.9.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#40861]
```rust
fn f(_: &[f32]) {}
fn main() {
    ()[f(&[1.0])];
}
```
```
error: internal compiler error: /checkout/src/librustc_typeck/check/coercion.rs:693:
    expr already has an adjustment on it!
```
[Regressed between 1.8 and 1.9](https://godbolt.org/g/QueMNk) and found by @kennytm in #40610.
Like #40610, it only happens when there's already an error, possibly from a suggestion attempt.

Meta: perhaps there should be a label for ICE-on-error.

**Comment by arielb1** [comment]
Looks like a double call to `check_expr_has_type` (https://github.com/rust-lang/rust/blob/ccce2c6eb914a66571f60fa0afe8a46faa9fb3bd/src/librustc_typeck/check/mod.rs#L3808) introduced in #24475.
