### ISSUE TITLE
use platform-native barriers for std::sync::Barrier

### ISSUE THREAD

**Issue by froydnj** [rust-lang/rust#40875]
pthreads provides [pthread_barrier_t](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_barrier_init.html).  Windows provides [synchronization barriers](https://msdn.microsoft.com/en-us/library/windows/desktop/hh706897(v=vs.85).aspx), albeit only on Windows 8 and above.

Using platform-native barriers may be smaller (e.g. on Linux/glibc, a barrier is ~third of the size of a mutex+condvar), require fewer allocations (only one `Box` for the underlying barrier, rather than separate boxes for an underlying `sys::Mutex` and `sys::Condvar`), and may take advantage of system-specific optimizations that would render them faster.

**Comment by Mark-Simulacrum** [comment]
Mutex/Condvar, etc. aren't boxed on Linux -- we directly use futexes now for the underlying implementation. Barrier is now `u32 (mutex) + u32 (condvar) + usize`. I believe the story is similar on Windows too.

I think this is probably good enough, so I'm going to go ahead and close this.
