### ISSUE TITLE
E0495 error explanation: dead link on doc.rust-lang.org

### ISSUE THREAD

**Issue by Songbird0** [rust-lang/rust#40877]
Hi all,

There's a dead link to [E0495 error explanation](https://doc.rust-lang.org/error-index.html#E0495).

On [play.rust-lang.org](play.rust-lang.org): 

![image](https://cloud.githubusercontent.com/assets/13397428/24410699/074efafc-13d4-11e7-9428-e6357702bc2c.png)

Thanks!

**Comment by steveklabnik** [comment]
Yes, while a link is always generated on the playpen, not all errors have full descriptions, and so this is expected. Maybe the playpen shouldn't generate the link in the first place, of course. Would you mind filing this on its tracker? https://github.com/rust-lang/rust-playpen Thanks!
