### ISSUE TITLE
Allow trait objects for traits with methods that have no receiver (static methods)

### ISSUE THREAD

**Issue by jorendorff** [rust-lang/rust#40874]
```rust
trait StringSet {
    fn new() -> Self;
    fn has(&self, s: &str) -> bool;
    fn add(&self, s: &str);
}

fn f(s: &StringSet) { s.add("hello"); }

fn main() {}
```

This isn't allowed:

```console
rustc 1.16.0 (30cf806ef 2017-03-10)
error[E0038]: the trait `StringSet` cannot be made into an object
 --> <anon>:7:1
  |
7 | fn f(s: &StringSet) { s.add("hello"); }
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `StringSet` cannot be made into an object
  |
  = note: method `new` has no receiver
```

Why not? It seems OK for a trait to have some features that can't be dynamically dispatched through a trait object.

In C++, you can have a base class with both virtual methods and static methods, even though there's no such thing as a virtual static method, and no way to dynamically dispatch static methods.

**Comment by pyfisch** [comment]
Maybe you have already found it but the Rust compiler error index it has quite a [long explanation](https://doc.rust-lang.org/error-index.html#method-references-the-self-type-in-its-arguments-or-return-type) about this specific case. Did this explanation help? Or what is still unclear?

**Comment by jorendorff** [comment]
Yes, the explanation is here: https://doc.rust-lang.org/error-index.html#method-has-no-receiver

The workaround is nice to know. I'll close this.

**Comment by nifker** [comment]
@jorendorff Why cant this be inferred?
