### ISSUE TITLE
Tracking issue for the addition of the compile_error! macro

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#40872]
https://github.com/rust-lang/rfcs/pull/1695

**Comment by sfackler** [comment]
cc @sgrif

**Comment by est31** [comment]
On IRC, @moonheart08 has expressed desire to implement this. I've helped a little bit, can continue to mentoring.

**Comment by wesleywiser** [comment]
@est31 do you know if @moonheart08 is still interested in working on this? If not, I'd love to work on it.

**Comment by est31** [comment]
I have heard about them wanting to submit their changes it about a week ago or so. Lets wait one week more.

**Comment by wesleywiser** [comment]
Ok, sounds good.

**Comment by lu-zero** [comment]
I implemented it as compiler plugin a while ago, maybe I could try to see how hard would be to move it in the right place?

https://github.com/lu-zero/compiler_error

**Comment by Geal** [comment]
FYI, there's a crate that does it as a compiler plugin, in the meantime: [compiler_error](https://crates.io/crates/compiler_error)
(for people like me who come to this issue and need it right now)

**Comment by sfackler** [comment]
The feature here is pretty straightforward, so let's stabilize it!

@rfcbot fcp merge

**Comment by dtolnay** [comment]
@rfcbot reviewed
