### ISSUE TITLE
Move all compile-fail tests to ui tests

### ISSUE THREAD

**Issue by cengizIO** [rust-lang/rust#40882]
Hello, 

This issue is for tracking following proposal by @nikomatsakis:
https://internals.rust-lang.org/t/consolidating-compile-fail-and-ui-testing-and-possibly-others-as-well/4896

Please note that this issue represents only a part of the whole process.

**Comment by petrochenkov** [comment]
https://github.com/rust-lang/rust/issues/44844 currently tracks the progress.
Closing this as a duplicate.
