### ISSUE TITLE
Limitations of Variance with HashMap Removes

### ISSUE THREAD

**Issue by mitsuhiko** [rust-lang/rust#40881]
I have a weird case which I think is interesting in showing some limitations of the language currently.

I have effectively a `HashMap<Foo<'static>, V>` but that this is a static lifetime is largely hidden from the outside world. As far as the public API is concerned everything is `Foo<'a>`. Upon insertion into the hash map the key object is cloned and becomes `Foo<'static>` so that is fine.

All the read only interfaces to the `HashMap` also work out because I believe a `&HashMap<Foo<'static>, V>` becomes a `&HashMap<Foo<'a>, V>` automatically.

The issue comes up with `HashMap::remove` which is mutable. There this coercion does not happen because obviously the intention is to stop people from putting a `Foo<'a>` into the hashmap. Because I do not want to do the expensive clone of the key value to make it static upon removal I currently have to unsafe coerce the `&Foo<'a>` into a `&Foo<'static>` for removal which is not great.

I'm not sure if this is a bug and if it is, where it is. But I figured I raise it anyways.

(Also I'm not sure about any of the terms to refer to these concepts)

**Comment by stephaneyfx** [comment]
`impl<'a> Borrow<Foo<'a>> for Foo<'static>` conflicts with an std implementation, but a wrapper type comes to the rescue. This allows to remove an element without cloning the `Foo<'a>` key.
[playground](https://play.rust-lang.org/?gist=bcc7c485b3ba14496929df1155c5e735&version=stable&backtrace=0)
```rust
use std::borrow::Borrow;
use std::collections::HashMap;
use std::marker::PhantomData;

#[derive(Debug, Eq, Hash, PartialEq)]
struct Foo<'a> {
    val: i32,
    phantom: PhantomData<&'a ()>,
}

impl<'a> Foo<'a> {
    fn new(i: &'a i32) -> Self {
        Foo {val: *i, phantom: PhantomData}
    }
}

#[derive(Debug, Eq, Hash, PartialEq)]
struct Key(Foo<'static>);

impl Key {
    fn new(x: Foo) -> Key {
        Key(Foo {val: x.val, phantom: PhantomData})
    }
}

impl<'a> Borrow<Foo<'a>> for Key {
    fn borrow(&self) -> &Foo<'a> {
        &self.0
    }
}

fn main() {
    let mut map: HashMap<Key, i32> = HashMap::new();
    map.insert(Key::new(Foo::new(&4)), 5);
    assert!(map.get(&Foo::new(&4)).is_some());
    println!("{:?}", map);
    assert!(map.remove(&Foo::new(&4)).is_some());
    println!("{:?}", map);
}
```

**Comment by steveklabnik** [comment]
Triage; there's been no discussion in a bit over two years. The last comment seems to indicate that this isn't a bug, and provides a workaround. So I'm gonna give this a close. @mitsuhiko let me know if you think this should stay open
