### ISSUE TITLE
Tracking issue for the FromUtf8Error::as_bytes

### ISSUE THREAD

**Issue by 3Hren** [rust-lang/rust#40895]
Added in https://github.com/rust-lang/rust/pull/40290 under the `from_utf8_error_as_bytes` feature flag.

**Comment by Mark-Simulacrum** [comment]
@rust-lang/libs Nominating for stabilization. Seems like a good addition with no (known) blockers.

**Comment by sfackler** [comment]
@rfcbot fcp merge

**Comment by ErichDonGubler** [comment]
How does one contribute after the FCP has gone through for stabilization? I'm not familiar with it and want to learn. :) Is that something the community contributes, or do we have a big stabilization PR like [this one](https://github.com/rust-lang/rust/pull/43373)?

**Comment by SimonSapin** [comment]
Both are possible. In this case I see that https://github.com/rust-lang/rust/pull/49121 has already been submitted.
