### ISSUE TITLE
Current nightly is 1.17 but should be 1.18?

### ISSUE THREAD

**Issue by michaelsproul** [rust-lang/rust#40890]
I just fetched the latest nightly with rustup, and was surprised to see that its version number is 1.17.0 instead of 1.18.0.

```
$ rustc --verbose --version
rustc 1.17.0-nightly (ccce2c6eb 2017-03-27)
binary: rustc
commit-hash: ccce2c6eb914a66571f60fa0afe8a46faa9fb3bd
commit-date: 2017-03-27
host: x86_64-apple-darwin
release: 1.17.0-nightly
LLVM version: 3.9
```

Has there been a change to the way the release trains work, or is the `CFG_RELEASE_NUM` string out of date? https://github.com/rust-lang/rust/blob/master/src/bootstrap/channel.rs#L26

I observed the same thing with the "Nightly (1.18)" `.tar.gz` from https://www.rust-lang.org/en-US/other-installers.html

**Comment by est31** [comment]
Bumping the version number is being worked on, see #40524

**Comment by michaelsproul** [comment]
Ok, awesome! Guess I can close this then!
