### ISSUE TITLE
error messages for semicolon issues

### ISSUE THREAD

**Issue by dherman** [rust-lang/rust#40891]
When you have a void function that omits a final semicolon or a non-void function that accidentally has a final semicolon, the type error message should be able to be more clever and give you a more helpful "did you mean...?" kind of message.

**Comment by dherman** [comment]
Example of a missing semicolon: https://is.gd/gojgTu

Inline:

```rust
fn has_a_side_effect_and_returns_something() -> i32 {
    println!("I am a super useful and awesome side effect");
    42
}

fn do_a_thing() {
    has_a_side_effect_and_returns_something();
    has_a_side_effect_and_returns_something()
}

fn main() {
    do_a_thing();
}
```

**Comment by Mark-Simulacrum** [comment]
I'm going to close this in favor of https://github.com/rust-lang/rust/issues/25228 which is more targeted. Feel free to add or comment there with specific cases!
