### ISSUE TITLE
Panic caused by Markdown in latest nightly

### ISSUE THREAD

**Issue by SergioBenitez** [rust-lang/rust#40918]
`rustc` is panicking on markdown that previously parsed. This appears to be caused by the transition from hoedown to pulldown-cmark (#40912, #40338):

```
---- src/request/form/from_form_value.rs - request::form::from_form_value::FromFormValue (line 59) stdout ----
	error: unknown start of token: `
 --> <anon>:2:42
  |
2 | A value is validated successfully if the `from_str` method for the given
  |                                          ^

thread 'rustc' panicked at 'Box<Any>', /checkout/src/libsyntax/parse/lexer/mod.rs:81
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'rustc' panicked at 'couldn't compile the test', /checkout/src/librustdoc/test.rs:270
```

The markdown being referenced in the error looks like this:

```markdown
/// Rocket implements `FromFormValue` for many standard library types. Their
/// behavior is documented here.
///
///   * **f32, f64, isize, i8, i16, i32, i64, usize, u8, u16, u32, u64**
///
///   **IpAddr, Ipv4Addr, Ipv6Addr, SocketAddrV4, SocketAddrV6, SocketAddr**
///
///     A value is validated successfully if the `from_str` method for the given
///     type returns successfully. Otherwise, the raw form value is returned as
///     the `Err` value.
```

cc @steveklabnik @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
The problem is that this block:

> ///     A value is validated successfully if the `from_str` method for the given
> ///     type returns successfully. Otherwise, the raw form value is returned as
> ///     the `Err` value.

Is considered as code. I wonder what would be a good solution for this...

**Comment by SergioBenitez** [comment]
I don't think it should be...should it? It wasn't prior to this: https://api.rocket.rs/rocket/request/trait.FromFormValue.html#provided-implementations

**Comment by GuillaumeGomez** [comment]
Yes but before, hoedown wasn't *really* markdown compliant. You can see by yourself how your code is interpreted by the markdown [here](http://spec.commonmark.org/dingus/?text=Rocket%20implements%20%60FromFormValue%60%20for%20many%20standard%20library%20types.%20Their%0Abehavior%20is%20documented%20here.%0A%0A%20%20%20*%20**f32%2C%20f64%2C%20isize%2C%20i8%2C%20i16%2C%20i32%2C%20i64%2C%20usize%2C%20u8%2C%20u16%2C%20u32%2C%20u64**%0A%0A%20%20%20**IpAddr%2C%20Ipv4Addr%2C%20Ipv6Addr%2C%20SocketAddrV4%2C%20SocketAddrV6%2C%20SocketAddr**%0A%0A%20%20%20%20%20A%20value%20is%20validated%20successfully%20if%20the%20%60from_str%60%20method%20for%20the%20given%0A%20%20%20%20%20type%20returns%20successfully.%20Otherwise%2C%20the%20raw%20form%20value%20is%20returned%20as%0A%20%20%20%20%20the%20%60Err%60%20value.).

**Comment by steveklabnik** [comment]
(not giving this all the tags because it's linked in to the tracking issue

**Comment by steveklabnik** [comment]
> rustc is panicking on markdown that previously parsed.

To be clear, this is a test failure, not an ICE, correct?

**Comment by GuillaumeGomez** [comment]
> To be clear, this is a test failure, not an ICE, correct?

Yes.

**Comment by steveklabnik** [comment]
Right. So this is more of expected breakages caused by a bugfix.

@SergioBenitez are you running off rustc master? I wasn't even aware this was in nightly yet, I thought it missed the cutoff. As I mentioned in the other issue, I was planning on publicizing this tomorrow.

**Comment by SergioBenitez** [comment]
@steveklabnik Looks like this made it into today's nightly.

Okay, so after discussing this a bit on IRC and playing with the `commonmark.js` script, the issue stems from a difference in how `hoedown` and `pulldown-cmark` interpret text to be inside of a list item:

```markdown
Leading text:

  * List Item Heading

  This is considered to be part of the list item in `hoedown` but not `pulldown-cmark`.

    This is still inside the list item in `hoedown` but is a new code block in `pulldown-cmark`.
```

As shown above, text that `hoedown` treated as being inside of a list item is now treated by `pulldown-cmark` to be a code block. `rustdoc` tries to compile each code block as Rust code, and since this is clearly not Rust, compilation fails, and we see the `panic!` from the failed compilation.

While this isn't a bug in `rustc`, it is a breaking change. I'd suggest that a crater run is done to catch any more of these and potentially notify the authors. Alternatively, some of these peculiarities can be "forward-ported" into the new parsing.

**Comment by steveklabnik** [comment]
Huh. Well, better make that post for sure, I guess. (The nightly)

Crater wouldn't catch this, it doesn't run tests.

**Comment by nagisa** [comment]
```
///   * **f32, f64, isize, i8, i16, i32, i64, usize, u8, u16, u32, u64**
///
///     **IpAddr, Ipv4Addr, Ipv6Addr, SocketAddrV4, SocketAddrV6, SocketAddr**
///
///     A value is validated successfully if the `from_str` method for the given
///     type returns successfully. Otherwise, the raw form value is returned as
///     the `Err` value.
```

Should work. The prior behaviour seems like a bug to me even considering the original markdown, and I think this is not easily fixable without making the markdown parser non-compliant.

**Comment by steveklabnik** [comment]
I'm giving this one a close since it's expected behavior. Thanks all!
