### ISSUE TITLE
Allow unstable features for the unstable book

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#40931]
The home page of the Unstable book shows an example with the box syntax. But if I try to run it in the page, the compilation fails because unstable features are not supported.
(I have not found a way to upload an image here of the error).

**Comment by steveklabnik** [comment]
Could you file this against https://github.com/azerupi/mdBook please? it's actually an upstream issue; we need some way to send along a parameter for nightly examples.

**Comment by est31** [comment]
got moved into https://github.com/azerupi/mdBook/issues/241
