### ISSUE TITLE
Add notification when build ended

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#40937]
It might be nice/interesting to add an optional (<- important!) module like they do in servo.

**Comment by jdm** [comment]
https://github.com/servo/servo/blob/325713af3877eb7c51745e7b626952f5d74dc76f/python/servo/build_commands.py#L35-L135

**Comment by GuillaumeGomez** [comment]
@jdm: That's exactly the code I took (with very few improvements/changes).

**Comment by Mark-Simulacrum** [comment]
Presumably this is intended for rustbuild, so tagging as such, though I'm inclined to close it (seems like this shouldn't be our responsibility) myself.

**Comment by GuillaumeGomez** [comment]
Yes, the PR was refused so I guess it should be closed.
