### ISSUE TITLE
Error uses parameter name out of context: cannot infer type for `U`

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust#40944]
The message is technically correct, but it refers to a generic name `U` that is not present in user's source code, and has no meaning in the current context.

```rust
fn main() {
    assert_eq!("bar".into(), "foo".into());
}
```

> error[E0282]: unable to infer enough type information about `U`
>  cannot infer type for `U`

It's even weirder that the type `U` is [not in `Into<T>`'s definition](https://doc.rust-lang.org/std/convert/trait.Into.html), but comes from somewhere else inside stdlib.

```rust
pub trait Into<T> {
    fn into(self) -> T;
}
```

It would be clearer if rustc has shown `Into<U>` instead, or perhaps the stdlib implementation could rename the cryptic `U` to something self-explanatory like `TypeToBeConvertedInto`.

**Comment by tatref** [comment]
I this this can be troublesome for beginners, since this can pop up anywhere. Other example:
```
fn main() {
   use std::collections::HashMap;
   
   let h = HashMap::new();
}
```

Error message:
```
error[E0282]: type annotations needed
 --> <anon>:4:12
  |
4 |    let h = HashMap::new();
  |        -   ^^^^^^^^^^^^ cannot infer type for `K`
  |        |
  |        consider giving `h` a type
```

**Comment by Mark-Simulacrum** [comment]
I'm going to close this in favor of https://github.com/rust-lang/rust/issues/25633.
