### ISSUE TITLE
Cargo running on Msys2 terminal defaults to no color

### ISSUE THREAD

**Issue by cetra3** [rust-lang/rust#40940]
Not sure if I'm doing something wrong here, but when running cargo within an Msys2 terminal I have to specify `--color always` otherwise it doesn't pick up that it's a coloured terminal.

I also can't seem to force this all the time by `echo "color = 'always'" > ~/.cargo/config`

**Comment by Mark-Simulacrum** [comment]
I believe this is https://github.com/rust-lang/cargo/issues/3077 (which is really https://github.com/Stebalien/term/issues/58).

**Comment by kennytm** [comment]
Since `cargo` switched to `termcolor` recently (rust-lang/cargo#4162) this should have been fixed for MSYS2 with the latest nightly.
