### ISSUE TITLE
Broken formatting on Error Index E0422

### ISSUE THREAD

**Issue by irfanhudda** [rust-lang/rust#40945]
On page https://doc.rust-lang.org/error-index.html#E0422 code formatting appears to be broken

![e0422](https://cloud.githubusercontent.com/assets/1755089/24551982/5688e5d6-1642-11e7-85f3-6b8a9167129a.png)

**Comment by steveklabnik** [comment]
This has already been fixed; see https://doc.rust-lang.org/nightly/error-index.html#E0422 . Thank you for reporting though!

**Comment by irfanhudda** [comment]
Oh. Didn't know about nightly docs. Thanks.
