### ISSUE TITLE
beta regression: assembunny-plus 0.0.3

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#40951]
The [assembunny-plus crate](https://github.com/broad-well/assembunny-plus) has regressed on beta:

```
   Compiling assembunny_plus v0.0.3 (file:///home/alex/code/assembunny-plus)
error: borrowed value does not live long enough
   --> src/parser.rs:309:98
    |
309 |     let mut output: Vec<Token> = vec![Token::new(TokenType::KEYWORD, index_of(&KEYWORD_INDEX, &&*str_toks[0].to_lowercase()).unwrap() as i32)];
    |                                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^                   - temporary value only lives until here
    |                                                                                                  |
    |                                                                                                  does not live long enough
    |
    = note: borrowed value must be valid for the static lifetime...
    = note: consider using a `let` binding to increase its lifetime

error: aborting due to previous error

error: Could not compile `assembunny_plus`.

To learn more, run the command again with --verbose.
```

cc @broad-well

https://github.com/broad-well/assembunny-plus/commit/4ed0f0dbb67f60732f512a4859689659d1e0ab2b

```
rustc 1.17.0-beta.2 (b7c276653 2017-03-20)
binary: rustc
commit-hash: b7c27665307704a9b158fe242e88e83914029415
commit-date: 2017-03-20
host: x86_64-unknown-linux-gnu
release: 1.17.0-beta.2
LLVM version: 3.9
```

**Comment by nikomatsakis** [comment]
OK, I did some digging around. I believe this regression is a bug. Here is a minimal test case:

```rust
const FOO: [&'static str; 1] = ["foo"];

fn find<T: PartialEq>(t: &[T], element: &T) { }

fn main() {
    let x = format!("hi");
    find(&FOO, &&*x);
}
```

Specifically what is happening is that we used to infer the `T` in `find` to `&'x str` for some `'x`, but we now infer it to `&'static` str. I suspect this is related to the soundness fix around unsized  coercions.  You can make the code compile in various ways, e.g. `find::<&str>` or `&FOO[..]`, all of which kind of sidestep that aspect of type inference.

cc @eddyb

**Comment by nikomatsakis** [comment]
(Nominating for compiler team discussion.)

**Comment by eddyb** [comment]
There should be enough subtyping to make that work, I'm not sure where it goes wrong. It's broken on nightly too, right?

**Comment by nikomatsakis** [comment]
This is actually #18653. I will see about fixing that.

**Comment by nikomatsakis** [comment]
I'm going to mark this as P-high and assign myself. I am investigating.

**Comment by nikomatsakis** [comment]
triage: P-high

**Comment by pnkfelix** [comment]
assigning niko to hold him to his earlier comment. 😄

**Comment by brson** [comment]
Backports are best in by this friday, next thursday is the absolute deadline. cc @nikomatsakis

**Comment by nikomatsakis** [comment]
@brson working on it :)

**Comment by nikomatsakis** [comment]
OK, this is fixed be #40570, but I think I also have a more tailored fix that we can backport to beta.

**Comment by nikomatsakis** [comment]
Status: 

- Fixed on nightly through #40570 
- Pending PR for beta (#41269) but it is unclear if it makes sense to backport, since the changes are non-trivial, and the impact is not huge. (One crate that I am aware of.)

**Comment by nikomatsakis** [comment]
After discussion in the @rust-lang/compiler meeting, we decided **not** to backport the fix for this to beta, as it is non-trivial. The problem is fixed on nightly, and I'll offer a patch to the `assembunny`  crate.

**Comment by alexcrichton** [comment]
Looks [fixed on nightly in assembunny-plus](https://github.com/broad-well/assembunny-plus/commit/e58d7a7c8a12834866ef0e125e1d6f6446bc00bd) as well, and due to decision to not backport closing.

Thanks for the fixes @nikomatsakis!
