### ISSUE TITLE
Rust 1.17 regression - named-block  0.3.1

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#40959]
```
   Compiling named-block v0.3.1 (file:///home/alex/code/named-block)
   Compiling static-cond v0.1.1
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:323
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `named-block`.

To learn more, run the command again with --verbose.
```

Only regresses against beta, fixed in nightly. Do we have a PR tagged with a backport to fix this?

**Comment by alexcrichton** [comment]
cc @rust-lang/compiler

**Comment by alexcrichton** [comment]
May also [affect](https://brson.github.io/cargobomb-reports/stable-v-nightly-2017-03-29/res/nightly/reg/rustasm6502-0.1.2/log.txt) [rustasm6502](https://crates.io/crates/rustasm6502)

cc @jonas-schievink

**Comment by alexcrichton** [comment]
Likely [also](https://brson.github.io/cargobomb-reports/stable-v-nightly-2017-03-29/res/nightly/reg/uom-0.11.0/log.txt) [uom](https://github.com/iliekturtles/uom)

cc @iliekturtles

**Comment by durka** [comment]
cc me :)

**Comment by iliekturtles** [comment]
Looks like #40813. There are nested macro_rules in `static-cond`. Since landing in nightly `uom` is building again.

**Comment by alexcrichton** [comment]
@jseyfried can you confirm #40813 fixes this? If so then we can close as that's nominated for a backport

**Comment by alexcrichton** [comment]
er, didn't mean to close yet

**Comment by durka** [comment]
I can confirm that cherry-picking #40813 on top of the beta branch fixes `named-block`.

**Comment by alexcrichton** [comment]
Thanks @durka!

In that case we'll track this with the other backports.
