### ISSUE TITLE
Regresion in rustls-0.5.7, Rust 1.17

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#40963]
https://github.com/ctz/rustls

```
130 brian@ip-10-145-43-250:~/dev/rustls⟫ git log -1
commit b149eb78187b97f057e3ee1aade6be67bf093229
Author: Joseph Birr-Pixton <jpixton@gmail.com>
Date:   Mon Feb 27 19:30:00 2017 +0000

    0.5.7

```

```
brian@ip-10-145-43-250:/mnt2/dev⟫ rustc +nightly -Vv
rustc 1.18.0-nightly (5c94997b6 2017-03-30)
binary: rustc
commit-hash: 5c94997b6b1cca3e65ecfc5ba40c033d6838019b
commit-date: 2017-03-30
host: x86_64-unknown-linux-gnu
release: 1.18.0-nightly
LLVM version: 3.9

```

```
brian@ip-10-145-43-250:~/dev/rustls⟫ cargo +nightly test
   Compiling rustls v0.5.7 (file:///mnt2/dev/rustls)
error: The attribute `export_macro` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
 --> src/msgs/macros.rs:3:1
  |
3 | #[export_macro]
  | ^^^^^^^^^^^^^^^
  |
  = help: add #![feature(custom_attribute)] to the crate attributes to enable

error: aborting due to previous error

error: Could not compile `rustls`.
Build failed, waiting for other jobs to finish...
error: The attribute `export_macro` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
 --> src/msgs/macros.rs:3:1
  |
3 | #[export_macro]
  | ^^^^^^^^^^^^^^^
  |
  = help: add #![feature(custom_attribute)] to the crate attributes to enable

error: aborting due to previous error

error: build failed

```

cc @cristicbz

**Comment by cristicbz** [comment]
@brson I think you meant @ctz

**Comment by ctz** [comment]
This was #40487 and https://github.com/ctz/rustls/issues/57, fixed in rustls 0.5.8

**Comment by alexcrichton** [comment]
Out of curiosity, do we know the PR to rust that caused this regression?

**Comment by brson** [comment]
@jseyfried look  familiar?

**Comment by brson** [comment]
Would be good to have the PR that caused this.

**Comment by brson** [comment]
@nagisa says this is on beta too.

**Comment by withoutboats** [comment]
@jseyfried I don't understand the connection between the PR you linked to and this regression. Can you explain more?

**Comment by jseyfried** [comment]
@withoutboats Whoops, though I was commenting on #40966 -- moved the comment [there](https://github.com/rust-lang/rust/issues/40966#issuecomment-291767140).

**Comment by nikomatsakis** [comment]
I'm confused why this would have ever worked? Isn't the correct name `#[macro_export]`?

**Comment by nagisa** [comment]
My guess would be "for some reason the check for unused attributes used to not work within that context for some reason before."

**Comment by nagisa** [comment]
IMO removing the error is hardly justifiable, and should be considered a bug fix.

**Comment by nikomatsakis** [comment]
@nagisa 

> IMO removing the error is hardly justifiable, and should be considered a bug fix.

By this do you mean "it's ok that we fixed this bug, even though it caused a regression"? If so, I am inclined to agree; plausible we could use a warning period, but maybe not worth it if only this crate is affected.

**Comment by pnkfelix** [comment]
As discussed above, this outcome is the result of a bug fix (where a use of an unknown attribute is now being rejected by the compiler).

Compiler team has decided that Adding a warning cycle for this bug at this point is not warranted
