### ISSUE TITLE
Nonfatal rustdoc error on cssparser-macros

### ISSUE THREAD

**Issue by jdm** [rust-lang/rust#40978]
The new markdown parser does not like this code block: https://github.com/servo/rust-cssparser/blob/20b509a7d3ca6c432281ebd00680bb0c3f5aadef/macros/lib.rs#L60-L67
I see:
```
error: unknown start of token: \u{2026}
 --> <stdin>:1:72
  |
1 | static MAP: &'static ::cssparser::phf::Map<&'static str, $ValueType> = …;
  |                                                                        ^

warning: Backing out of syntax highlighting
  |
  = note: You probably did not intend to render this as a rust code-block
```

**Comment by zackmdavis** [comment]
`\u{2026}` is the ellipsis (…). One _could_ argue that the parser is correct to notice that  `…` can't be the first codepoint of a token in valid Rust? (Although this consideration is probably outweighed by the manifest convenience of using an ellipsis to indicate that part of a doc example is irrelevant.)

**Comment by steveklabnik** [comment]
I put a link in the tracking issue; I basically agree with @zackmdavis on both counts here. I see this has already been fixed upstream, but let's talk about if this is the actual behavior we want or not.

**Comment by GuillaumeGomez** [comment]
@jdm: That's because every code block is considered being rust code and therefore is tested. Hoedown didn't consider such block as code blocks before, you just need to add `ignore` flags to this code block (or `text`).

**Comment by GuillaumeGomez** [comment]
Since this is expected, I'll close it. Don't hesitate to reopen it if I missed anything.
