### ISSUE TITLE
Rust fails to build with gcc5

### ISSUE THREAD

**Issue by matklad** [rust-lang/rust#40974]
Hi! I've tried `./x.py bulid` today and the build failed while building `compiler-rt` with

```
Assumed value of MB_LEN_MAX wrong
```

in `stdint.h`. Looks like this is related to the fact that gcc5 is the default compiler for me (NixOS 17.03). Switching to gcc4 fixed this issue.

So, if rust indeed does not work with gcc5, it would be great to provide a better error message during the build.

**Comment by nagisa** [comment]
For all its worth Arch uses `gcc (GCC) 6.3.1 20170306` which works just fine.

**Comment by nagisa** [comment]
So I encountered this same issue too on NixOS. It was because I had CC=clang and CXX=clang++ set.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this; if we think that we should be responsible for fixing LLVM's incompatibility with various newer GCC versions we can open a meta bug to track it and fix as we go, in general this feels like the kind of fix that we might want to just leave for "file a PR".
