### ISSUE TITLE
Wrong branch of if statement executed

### ISSUE THREAD

**Issue by cheezgi** [rust-lang/rust#40982]
I've been working on an esoteric programming language for my AP CSP create task but I hit a brick wall about an hour ago. I was working on implementing mathematical operations in my language, but the entirely wrong branch of an if statement is being executed, including when the condition is true.

There are a lot of moving parts in the interpreter so I couldn't get it trimmed down, but the [full repository lives on GitLab](https://gitlab.com/cheezgi/juggle/tree/master/src). The if statement in question is in [this match arm](https://gitlab.com/cheezgi/juggle/blob/master/src/main.rs#L122).

I have a call to `unreachable!()` in the else body, which is getting triggered.

**I expected this to happen:** Well, I think we can all see what the problem here is. The body of the if, rather than the else, should have been executed.

**Instead, this happened:** The body of the else was executed rather than the body of the if.

`rustc --version --verbose`

```
rustc 1.17.0-nightly (ccce2c6eb 2017-03-27)
binary: rustc
commit-hash: ccce2c6eb914a66571f60fa0afe8a46faa9fb3bd
commit-date: 2017-03-27
host: x86_64-unknown-linux-gnu
release: 1.17.0-nightly
LLVM version: 3.9
```

This bug affects stable, beta, and nightly. I cloned it on a separate part of my machine and on my Windows machine, and it's the same story with both of those.

**Comment by jdm** [comment]
https://gitlab.com/cheezgi/juggle/blob/master/src/main.rs#L127-138 is not an if/else statement. It's an if statement followed by another block that will be executed unconditionally. The else keyword is missing entirely.

**Comment by cheezgi** [comment]
@jdm Today I learned I was blind.
