### ISSUE TITLE
Stop forcing `i1` booleans to `i8` for comparison when LLVM is fixed

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#40980]
The current behavior introduced by https://github.com/rust-lang/rust/pull/36958 is a workaround for the bug at https://github.com/rust-lang/rust/issues/36856 . In the comment at https://github.com/rust-lang/rust/pull/36958#issuecomment-255461415 Niko mentions that this is worth removing when the upstream LLVM bug is fixed (per that comment's suggestion I'm also presumptuously tagging this as P-medium). I know we have an upgrade to LLVM 4.0 in the works ( https://github.com/rust-lang/rust/issues/37609 ), so that may fix it. **However**, what is our policy on compiling on old versions of LLVM, for the sake of rustc distribution in distros that ship their own LLVM? If we need to remain compatible with old versions of LLVM, then the workaround may need to exist for quite a long time.

**Comment by nagisa** [comment]
> However, what is our policy on compiling on old versions of LLVM, for the sake of rustc distribution in distros that ship their own LLVM?

We still support 3.7.

**Comment by bstrie** [comment]
The LLVM bug in question appears to be https://bugs.llvm.org/show_bug.cgi?id=30579 , which is now marked resolved. Presumably the workaround in #36958 can now be removed, so I'm marking this E-easy. However, don't just revert the commit itself; leave its test case intact.

**Comment by rkruppe** [comment]
Command 2 on the LLVM bug indicates the fix is in LLVM 4.0, but we still support LLVM 3.9, so we can't actually do this just yet.

**Comment by rkruppe** [comment]
I'm not aware of any changes. Indeed we still have a CI image that builds with LLVM 3.9.

**Comment by rkruppe** [comment]
Huh, I've only just seen https://bugs.llvm.org/show_bug.cgi?id=30579#c3 -- if this is correct, there was never any need to work around it, we could have just dropped our (incorrect) FastISel patch. Does someone have to have a (non-rustc) LLVM 3.9 build available to try and reproduce?

**Comment by rkruppe** [comment]
@nox was so kind as to check, and indeed stock LLVM 3.9 doesn't have the bug.
