### ISSUE TITLE
std::process::Command::{stdin,stdout,stderr} should specify default behavior

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#40983]
* https://doc.rust-lang.org/std/process/struct.Command.html#method.stdin
* https://doc.rust-lang.org/std/process/struct.Command.html#method.stdout
* https://doc.rust-lang.org/std/process/struct.Command.html#method.stderr

These should specify what the default behavior is if they aren't explicitly called.

**Comment by retep998** [comment]
Note that the default behavior depends on whether the child process is using the console subsystem or windows subsystem. Console subsystem apps will inherit your stdout/stdin/stderr while windows subsystem apps will start with no stdout/stdin/stderr unless you explicitly assign them.

**Comment by steveklabnik** [comment]
I've folded this into https://github.com/rust-lang/rust/issues/29370, let's close this one
