### ISSUE TITLE
-o no longer works as expected for multiple output types

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#40993]
```
$ rustc test.rs --emit=asm,llvm-ir -O --crate-type=rlib -o testold
```

emits single file `testold` with LLVM-IR in it. Previously it used to emit `testold.s` and `testold.ll`.

This is a stable→stable regression. 1.14.0 works as expected, 1.16.0 does not. Did not test 1.15.0.

**Comment by arielb1** [comment]
"Intentional" change - #38440. Not marked relnotes. cc @nrc

**Comment by alexcrichton** [comment]
@arielb1 did you perhaps mean to link a different PR?

**Comment by brson** [comment]
#38840

**Comment by brson** [comment]
I took the liberty of P-high, but somebody needs to be assigned cc @rust-lang/compiler @rust-lang/tools
