### ISSUE TITLE
Howto build stage0 rust compiler

### ISSUE THREAD

**Issue by joerg-krause** [rust-lang/rust#40991]
For Linux build systems it would be desirable to not download the stage0 compiler, but to build it from scratch. How can this be done? `./x.py build --stage 0` only starts downloading the tarball...

**Comment by est31** [comment]
The Rust compiler is written in Rust, and therefore needs a rust compiler to compile itself. This is not unusual, some other languages do this as well. Of course, you can't start with a Rust compiler when you don't have one yet, so in the early days, rustc was written in ocaml. Its still inside the history of the repo, and graydon's github account has history reaching back even further. In theory you could compile the oldest ocaml rustc and then re-compile rustc a few times until you reach at modern day rustc, but its a quite long and involved process as you can imagine, as the rustc stage0 has been replaced quite often

There is an upcoming alternative rust compiler, mrustc, which is written in C++ though, which could help to break this circle. Its not ready yet though. See https://github.com/thepowersgang/mrustc/issues/2

**Comment by joerg-krause** [comment]
@est31 I see! Many thanks for the explanation and the link to mrustc. So, the best option is indeed to fetch the stage0 compiler binary (preferable the previous stable release) and use this to build the rust compiler.
