### ISSUE TITLE
confusing error "ambiguous associated type" on missing enum variants

### ISSUE THREAD

**Issue by geofft** [rust-lang/rust#41003]
If I compile something like 

```rust
enum Foo {
    Bar {n: i32}
}

fn main() {
    let x: Foo = Foo::Baz {n: 15};
}
```

I get this error:

```
error[E0223]: ambiguous associated type
 --> <anon>:6:18
  |
6 |     let x: Foo = Foo::Baz {n: 15};
  |                  ^^^^^^^^ ambiguous associated type
  |
  = note: specify the type using the syntax `<Foo as Trait>::Baz`
```

(see [play](https://is.gd/OzylcV))

This seems to me to be highly misleading, since no traits are involved, and the [longer description](https://doc.rust-lang.org/error-index.html#E0223) is worse. Is it possible to give an error that suggests "You might have just made a typo"?

**Comment by pnkfelix** [comment]
This same confusing error also comes up when the mistyped variant occurs in a pattern (rather than a construction expression).

In both cases, its an especially strange error, since I would only expect to see such an error in a context expecting an arbitrary type, but (I think) we should be able to infer that this context expects a path to a struct or variant.

**Comment by rukai** [comment]
Also occurs with structs:
```rust
fn main() {
    let a = Foo::Bar { }; // occurs here
    let b = Foo::bar();   // doesn't occur here
}

struct Baz {
    bar: Foo::Bar // occurs here
}

struct Foo { }
```

**Comment by chriskrycho** [comment]
This just bit me; it's *extremely* confusing. I'd be happy if someone has the time to help to mentor a bit to tackle this while I'm at Rust Belt Rust today and free on Saturday as well. (Back to the grind after that…)

**Comment by makoConstruct** [comment]
Another example of where a learning Rust programmer would encounter it and just be utterly mislead by the error

```rust
fn main() {
    let a: Foo::Item;
}

struct Foo<Item = usize>{
    phan:std::marker::PhantomData<Item>,
}
```
https://play.rust-lang.org/?gist=5b08c55cf63a625ced0cbaf83b4db0de&version=stable

So, it tells you that the reason you can't refer to the type parameter `Item` is that it's ambiguous. This is not factual. The reason you can't refer to the type parameter is that you can't in general refer to type parameters as if they're members(is there a design reason for that?), even after they've been bound to a particular value. It is not "ambiguous". It is nonexistent. The compiler is telling the user there's a way to make it work, even telling them how to write it (the suggestion does not work, and it fails in a way that doesn't clarify the problem.)

**Comment by treeman1111** [comment]
I'm working as a teaching assistant in a university course taught in Rust. This is the first time most of the students have been exposed to the language. Several have encountered the same cryptic message and been very confused - it would be great to see it replaced by a more useful message.

**Comment by estebank** [comment]
Current output in stable

```
error: no variant `Baz` on enum `Foo`
 --> src/main.rs:6:18
  |
6 |     let x: Foo = Foo::Baz {n: 15};
  |                  ^^^^^^^^ help: did you mean: `Foo::Bar`
```

Don't see how we can improve over it.

@treeman1111 what version of rustc are you using in your classes? I'd advice tracking at the very least the latest stable, as error messages are improving all the time for the benefit of newcomers like your students.

**Comment by treeman1111** [comment]
@estebank Sorry for the late reply...we're using 1.32.0 or thereabouts. The new error message looks much nicer!
