### ISSUE TITLE
Box<Fn(&'a ())> not behaving contravariantly in 'a

### ISSUE THREAD

**Issue by andersk** [rust-lang/rust#41013]
`&fn(&'a ())`, `Box<fn(&'a ())>`, and `&Fn(&'a ())` are all contravariant in `'a`. Shouldn’t `Box<Fn<&'a ()>>` be as well?

```rust
fn test1<'a, 'b: 'a>(f: &'b fn(&'a ())) -> &'b fn(&'b ()) {
    f  // ok
}

fn test2<'a, 'b: 'a>(f: Box<fn(&'a ())>) -> Box<fn(&'b ())> {
    f  // ok
}

fn test3<'a, 'b: 'a>(f: &'b Fn(&'a ())) -> &'b Fn(&'b ()) {
    f  // ok
}

fn test4<'a, 'b: 'a>(f: Box<Fn(&'a ())>) -> Box<Fn(&'b ())> {
    f  // error
}
```

```
error[E0308]: mismatched types
  --> /tmp/test.rs:14:5
   |
14 |     f
   |     ^ lifetime mismatch
   |
   = note: expected type `std::ops::Fn(&'b ()) + 'static`
              found type `std::ops::Fn(&'a ()) + 'static`
note: the lifetime 'a as defined on the body at 13:60...
  --> /tmp/test.rs:13:61
   |
13 |   fn test4<'a, 'b: 'a>(f: Box<Fn(&'a ())>) -> Box<Fn(&'b ())> {
   |  _____________________________________________________________^ starting here...
14 | |     f
15 | | }
   | |_^ ...ending here
note: ...does not necessarily outlive the lifetime 'b as defined on the body at 13:60
  --> /tmp/test.rs:13:61
   |
13 |   fn test4<'a, 'b: 'a>(f: Box<Fn(&'a ())>) -> Box<Fn(&'b ())> {
   |  _____________________________________________________________^ starting here...
14 | |     f
15 | | }
   | |_^ ...ending here

error: aborting due to previous error
```

(Possibly related to #36667?)

**Comment by bluss** [comment]
This is expected behaviour as Rust is today, like the linked issue says, Trait object types are invariant in their type parameters.

**Comment by andersk** [comment]
@bluss But if that were the full story, wouldn’t you also expect `test3` to fail, along with these two covariant examples?

```rust
fn test5<'b, 'a: 'b, 'c>(f: &'c Fn() -> &'a ()) -> &'c Fn() -> &'b () {
    f  // ok
}

fn test6<'b, 'a: 'b>(f: Box<Fn() -> &'a ()>) -> Box<Fn() -> &'b ()> {
    f  // ok
}
```

**Comment by bluss** [comment]
Oh the nomicon even mentions this

> Fn(T) -> U is invariant over T, but variant over U

(The return type is an associated type, not a type parameter of the `Fn` trait.)

**Comment by andersk** [comment]
I was going to ask about `test3` again, but I think I’ve figured out that `test3` doesn’t actually demonstrate contravariance, but rather a funny rule where `'b: 'a` entails a coercion from `&'b Foo<'a>` to `&'b Foo<'b>` regardless of variance. I’m still curious what’s going on there, but I’m no longer convinced there’s an actual bug being shown—closing.
