### ISSUE TITLE
Rustdoc: odd wrapping in code blocks

### ISSUE THREAD

**Issue by stjepang** [rust-lang/rust#41025]
Link to docs: https://doc.rust-lang.org/nightly/std/borrow/trait.Borrow.html
How it looks on my machine:
![](http://i.imgur.com/j0N9CW9.png)

Notice the space before `{`. Also, that indentation: `where` is seemingly indented by two spaces, while `fn` is indented by four. However, if I copy the code and paste here, it looks normal:

```rust
pub trait Borrow<Borrowed> where Borrowed: ?Sized {
    fn borrow(&self) -> &Borrowed;
}
```

**Comment by QuietMisdreavus** [comment]
I'm in the process of modifying rustdoc's formatting to match the fmt-rfcs for [where clauses](https://github.com/rust-lang-nursery/fmt-rfcs/issues/38) and [function definitions](https://github.com/rust-lang-nursery/fmt-rfcs/issues/39). The indentation of the top-level where clause should be modified by this change, but it looks like I still need to look into why that's getting an extra space before that one curly braace. For reference, here's what it looks like on my local rustdoc:

![rustdoc new borrow format](https://cloud.githubusercontent.com/assets/5217170/24614638/786b8af8-1851-11e7-9b20-d705bf081a55.PNG)

**Comment by QuietMisdreavus** [comment]
Note to self: This is because `item_trait` in `src/librustdoc/html/render.rs` prints a space after the leading where clause, regardless of whether it exists. But if it exists, then the where clause itself prints a newline. The space is there so that traits without where clauses can put their opening brace on the same line as the trait name.

**Comment by bluss** [comment]
It looks like the `pre` blocks on top of struct/trait pages now use `where` with `display: block;` which I think was an unintended change (intended only for method items).
