### ISSUE TITLE
Walking or consuming the then-expr of an if-expression ?

### ISSUE THREAD

**Issue by GAJaloyan** [rust-lang/rust#41033]
Hi everybody,

I found something strange in the Rust compiler about walk_expr and consume_expr  (which does a delegate_consume and then calls walk_expr) in the file https://github.com/rust-lang/rust/blob/master/src/librustc/middle/expr_use_visitor.rs at line 419:

```Rust
hir::ExprIf(ref cond_expr, ref then_expr, ref opt_else_expr) => {
   self.consume_expr(&cond_expr);
   self.walk_expr(&then_expr);
   if let Some(ref else_expr) = *opt_else_expr {
      self.consume_expr(&else_expr);
   }
}
```

The fact is that we never call consume_expr on the then_expr and instead just walk on it, while we consume the else_expr immediately if it exists. It seems that either the consume_expr can be turned to walk_expr (which could possibly increase the soundness of the analysis) or the walk_expr should be turned to consume_expr (in this case it could be a bug).
Any idea on it ? Thanks in advance.

PS: and on another note: what is the purpose of the select_from_expr function ? Why not just inline it ?

**Comment by Mark-Simulacrum** [comment]
Please ask questions on internals.rust-lang.org; it's unlikely they'll get seen or noticed here, and we try to keep the issue tracker solely for issues.
