### ISSUE TITLE
Missing O_EXEC and O_SEARCH in liblibc

### ISSUE THREAD

**Issue by amosonn** [rust-lang/rust#41031]
As written in the title. On some platforms, `O_ACCMODE` isn't limited just to `O_RDONLY | O_WRONLY | O_RDWR`, but has also other options, such as `O_EXEC` and `O_SEARCH`. The constants for these are currently missing from all platforms (except `O_SEARCH` on netbsd).
Looking through `O_ACCMODE`-s which are not `3`, it seems these are musl and solaris. Surprisingly, netbsd does have `O_ACCMODE = 3`.
Solaris [definitely](https://docs.oracle.com/cd/E26502_01/html/E29032/open-2.html) has both `O_EXEC` and `O_SEARCH`, musl [seems](http://www.openwall.com/lists/musl/2014/07/01/10) to have only `O_SEARCH`.

**Comment by nagisa** [comment]
https://github.com/rust-lang/libc

**Comment by amosonn** [comment]
Sorry, reposting there.
