### ISSUE TITLE
Rustdoc renders type alias in a wrong way

### ISSUE THREAD

**Issue by killercup** [rust-lang/rust#41036]
'Complex' type aliases get rendered incorrectly by Rustdoc.

E.g., `diesel::expression::helper_types::AsExprOf` is [defined here](https://github.com/diesel-rs/diesel/blob/54a99472ed155ac92587970d1a06613eee5b5c89/diesel/src/expression/helper_types.rs#L9) as:

```rust
pub type AsExprOf<Item, Type> = <Item as AsExpression<Type>>::Expression;
```

Rustdoc (from Rust 1.16 stable, rendered on Travis), however renders it like this (can be seen [here](https://docs.rs/diesel/0.12.0/diesel/expression/helper_types/type.AsExprOf.html)):

```rust
type AsExprOf<Item, Type> = Item::Expression;
```

**Comment by GuillaumeGomez** [comment]
Once the current rustdoc switch is done, I'll try to work on this one.

**Comment by GuillaumeGomez** [comment]
Switch is now done. Taking a look.
