### ISSUE TITLE
rustbuild shouldn't require cargo-vendor when building from tarballs

### ISSUE THREAD

**Issue by cuviper** [rust-lang/rust#41042]
Rustbuild uses cargo-vendor to get complete sources for the `dist-src` target, but this isn't needed when building from tarballs rather than git, as everything is already vendored.  It breaks distro builds when it tries to install cargo-vendor, as we have no network access allowed.  I see this on 1.17-beta, but 1.16 didn't deal with cargo-vendor.

I don't really even need the `dist-src` target anyway, as I just want to install binaries and docs, but `./x.py dist --install` always requires it AFAICT, even when explicit paths are specified.
(e.g. `./x.py dist --install src/librustc src/libstd src/doc`)

**Comment by est31** [comment]
cc @alexcrichton

**Comment by cuviper** [comment]
I was talking to @alexcrichton about this on IRC already.  I have a PR for this ready in just a moment.

**Comment by arielb1** [comment]
This sounds like a regression? (should we beta-nominate the fix)?
