### ISSUE TITLE
Fixing spelling typos in comments (.rs files - 'src' directory)

### ISSUE THREAD

**Issue by Fourchaux** [rust-lang/rust#41088]
Reading comments in the .rs files ('src' directory)
I observed around 200 very basic spelling typos.
(e.g. beacuse, colunmn, errror, wehther ...)

I could make a PR with corrections of these small typos.

Would you accept this kind of PR?

**Note :**
To respect your RFC#505, need the following words (unchanged for the time being) to be corrected, and how ?

- -ise vs. -ize

analyses
customise_customising
finalises
generalise_generalising
initialise_initialised_initialiser_initialising
normalised
optimise_optimises_optimiser_optimising
realise_realising
recognise_recognised
serialisation_serialising
stabilised
summarised
uniformised
unrecognised

- -our vs. -or

Behaviour / Behavior
flavours / flavors

- d vs. dd

override / overridde
overriden / overridden
overriding / overridding

- l vs. ll

cancelled / canceled
labelled / labeled
lazilly / lazily
signalling / signaling

- t vs. tt

formatted / formated
targetted / targeted
targetting / targeting
transmutting / transmuting

- Varii

javascript - javaScript
json - Json - JSON
NaN - NAN
nonascii - non-ASCII - non-ascii
parentheses - parenthesis
SHA1 - SHA-1
mutexs - mutexes
zeros - zeroes

**Comment by Mark-Simulacrum** [comment]
We'd be happy to accept a PR for this, but I don't think the issue itself is going to help much in this case, so I'm going to close. Would love to see a PR though!
