### ISSUE TITLE
Tracking issue for `str_mut_extras` and `str_box_extras`

### ISSUE THREAD

**Issue by clarcharr** [rust-lang/rust#41119]
cc @alexcrichton @sfackler 

PRs: #41096 and #41258 respectively

Notes:

* Are the naming conventions for these methods correct?

**Comment by alexbool** [comment]
What holds stabilization of these methods right now?

**Comment by SimonSapin** [comment]
@aturon @alexcrichton FCP to stabilize?

**Comment by aturon** [comment]
@rfcbot fcp merge

Covered APIs include:

- `as_bytes_mut`
- `from_utf8_mut`
- `from_utf8_unchecked_mut`
- `<Box<str>>::into_boxed_bytes` (just calls `Into::into`)
- `from_boxed_utf8` and `from_boxed_utf8_unchecked`, defined in `alloc:str`, exported in `collections::str`
- exports `from_utf8_mut` in `collections::str` (missed from previous PR)

**Comment by dtolnay** [comment]
`from_boxed_utf8` no longer exists. https://github.com/rust-lang/rust/pull/41258#issuecomment-296212875

@rfcbot reviewed
