### ISSUE TITLE
When nested subfield of a union is moved, move checker incorrectly permits access to its "uncle" fields

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#41126]
```rust
#![feature(untagged_unions)]
#![allow(unused)]

#[allow(unions_with_drop_fields)]
union U {
    x: (Vec<u8>, Vec<u8>),
    y: Vec<u8>,
}

fn main() { unsafe {
    let u = U { x: (Vec::new(), Vec::new()) };
    let a = u.x.0;
    let a = u.y; // This is incorrectly accepted despite u.y being "collaterally moved"
}}
```

When implementing move checking for unions I incorrectly assumed that moves automatically "propagate" to parent "loan paths", like in borrow checker, e.g.
```rust
    let a = &mut u.x.0;
    let a = &u.y; // This currently gives correct error due to u.y being "collaterally borrowed"
```
, this turns out to not be the case.
This case was missed in tests, so the error went unnoticed.

I have some quick fix, will submit tomorrow.

**Comment by arielb1** [comment]
I think we want more consensus on the interaction of unions and the borrow checker. I didn't see any discussion of it on the RFC (rust-lang/rfcs#1897).
