### ISSUE TITLE
Only random tests are run when building rustc-1.16.0

### ISSUE THREAD

**Issue by zarniwhoop73** [rust-lang/rust#41127]
#38435 points out that the tests are run in a random order, but while exploring build methods (make/ninja, shipped llvm or an added system llvm3) I noticed that the tests took random amounts of time.

At first I noticed that (without gdb) I was seeing 104 failures from gdb tests (and some failures from them if I added it). But then I noticed some runs of the tests took really long times - and when I looked back at an untimed run from the system build, although it too ended in error, it was a completely differnet single failure.

So then I saved the source after completing the build, and restored that for a rerun of the tests. By logging the results, and then using a bit of awk -

 cat thetestlog |
 grep result: |
 awk '{ passed+=$4 ; failed+=$6 ; ignored+=8; measured+=$10 } END {print "Passed:" passed " Failed:  " failed " ignored: " ignored}'

I got the following sets of results.

1. untimed, from the system build from source, system llvm and ninja
Passed:4563 Failed: 1 ignored: 1560
The test which failed was compile-fail/issue-37131.rs, that test does not seem to have been run in any other of the tests on this machine. This run did not run the debuginfo-gdb tests.

2.  fresh build, shipped llvm with ninja, 8m48 for the tests
Passed: 3322 Failed: 104 ignored: 1216
For this and the later tests, the failures were in debuginfo-gdb (3 tests there were ignored).

3, the same build files restored, rerun: 39m21 for the tests
Passed:153 Failed: 104 ignored: 80

4. a different build, shipped llvm without ninja, 26m29 for the tests
Passed:11591 Failed: 104 ignored: 2120

5. the same build, files restored, rerun: 54m26 for the tests
Passed:5295 Failed: 104 ignored: 816

**Comment by Mark-Simulacrum** [comment]
Closing. Let us know if this is still a problem (either here or in a new issue) and please provide full build logs (with `./x.py -vv build`) that you saw when reproducing the problem. Thanks!
