### ISSUE TITLE
Attribute(?) to selectively disable "unreachable pattern" errors

### ISSUE THREAD

**Issue by rntz** [rust-lang/rust#4112]
When writing macros that expand to "match" expressions, it can be hard to guarantee that all cases of the match will be necessary. Consider the following macro:

```
macro_rules! case(
  ($e:expr, $p:pat where $cond:expr => $thn:expr, $els:expr) => (
    match $e {
      $p => if $cond { $thn } else { $els },
      _ => $els
    }
  )
)
```

An example use of this macro would be `case!(some_expr, x where x > 3 => x, 3)`, which is equivalent to `max(3, some_expr)` (a silly example, but still).

Unfortunately, this example fails to compile because it expands to

```
match some_expr {
  x => if x > 3 { x } else { 3 },
  _ => 3
}
```

The last case of the match is redundant. However, there are also uses of the macro where the last case will not be redundant, eg. `case!(some_expr, x@1..10 where x % 2 == 0 => true, false)`.

It would be nice if there were some way to mark that a particular `match` expression is allowed to have unreachable cases, or (better yet) that a particular case was allowed to be unreachable.

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by jonas-schievink** [comment]
To anyone needing this now:

```rust
match 0 {
    1 ... 3 => {}
    x if true => {}
    _ => {}
}
```

**Comment by tbu-** [comment]
There's an easy work-around, don't think an attribute is necessary here.

**Comment by steveklabnik** [comment]
Since new lints have a big impact on users of rustc, the policy is that they should go through the RFC process like other user-facing changes. As such, I'm going to give this one a close, but if anyone comes across this ticket and wants this lint, consider adding it to clippy and/or writing up an RFC. Thanks!
