### ISSUE TITLE
Undefined symbol error while loading plugin on NixOS

### ISSUE THREAD

**Issue by SergioBenitez** [rust-lang/rust#41128]
## Overview

When loading the [`rocket_codegen`](https://github.com/SergioBenitez/Rocket) plugin via the `#[plugin(rocket_codegen)]` crate attribute on NixOS (17.03), the following error is emitted:

```sh
$ cargo build
   Compiling rocket-test v0.1.0 (file:///home/sbenitez/rocket-test)
error: /home/sbenitez/rocket-test/target/debug/deps/librocket_codegen-cd9174ccf3d9f83e.so: undefined symbol: GFp_RAND_bytes
 --> src/main.rs:2:11
  |
2 | #![plugin(rocket_codegen)]
  |           ^^^^^^^^^^^^^^

error: Could not compile `rocket-test`.
```

The symbol `GFp_RAND_bytes` is from [`ring`'s source](https://github.com/briansmith/ring/blob/e9cd812d10f241c115575e5b7b2cb3e20bbec0a6/src/rand.rs#L263). Note that the symbol is marked `#[cfg(test)]`.

## Reproducing

This issue can be reliably reproduced on NixOS by using the [nightly overlay](https://nixos.org/nixpkgs/manual/#using-the-rust-nightlies-overlay) and the following dependencies in `Cargo.toml` and the following `src/main.rs` file:

```toml
[dependencies]
rocket_codegen = { git = "https://github.com/SergioBenitez/Rocket" }
```

```rust
#![feature(plugin)]
#![plugin(rocket_codegen)]
fn main() { }
```

## Notes

`ring` is a dependency of `rocket`, which itself is a dependency of `rocket_codegen`. `rocket_codegen` is a dependency of the `rocket_test` crate above. `rocket` and `rocket_codegen` build successfully on NixOS. The dependency itself is not the issue. **The problem does not occur if the `#[plugin(rocket_codegen)]` line is removed.** 

Based on this, and because the error arises from the `.so` file, it appears that the issue occurs when the plugin is dynamically loaded at compile-time. Looking at the symbol table in the `.so` reveals that the shared object file expects the symbol `GFp_RAND_bytes`. Given that [`ring`'s `GFp_RAND_bytes` `fn`](https://github.com/briansmith/ring/blob/e9cd812d10f241c115575e5b7b2cb3e20bbec0a6/src/rand.rs#L263) is only compiled under `#[cfg(test)]`, the presence of this symbol is somewhat unexpected. Perhaps this is indeed the expected result; I'm not sure.

This issue does not occur on OS X, Debian, CoreOS, Ubuntu, or Windows. This was initially reported in https://github.com/SergioBenitez/Rocket/issues/251.

**Comment by SergioBenitez** [comment]
Just to follow-up: the issue goes away when the `GFp_RAND_bytes` `fn` is removed from `ring`, as is the case in `ring 0.7.4`. As such, to reproduce the issue, please use `ring 0.7.3`.

**Comment by bjorn3** [comment]
Rustc plugins are no longer supported. (with the exception of lint plugins, but those are deprecated and basically only still exist for Servo's GC root checker) Rocket no longer uses a rustc plugin either.
