### ISSUE TITLE
Self overlapping error message ("unexpected tokenxpected")

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#41155]
This (invalid) code:

```rust
impl S {
	pub
}
```

Produces the following, okay error message on beta:

```
rustc 1.17.0-beta.3 (ca3d11832 2017-04-05)
error: expected one of `(`, `const`, `default`, `extern`, `fn`, `type`, or `unsafe`, found `}`
 --> <anon>:3:1
  |
3 | }
  | ^

error: aborting due to previous error
```
But on nightly, you get a bad, self overriding one:
```
rustc 1.18.0-nightly (50c186419 2017-04-06)
error: expected one of `(`, `const`, `default`, `extern`, `fn`, `type`, or `unsafe`, found `}`
 --> <anon>:3:1
  |
2 |   	pub
  |  _____- starting here...
3 | | }
  | | ^.unexpected tokenxpected one of 7 possible tokens here

error: aborting due to previous error
```

Note the "unexpected tokenxpected one of 7 possible tokens here". Possibly the "starting here" is not required either.

cc @estebank

**Comment by estebank** [comment]
There are two problems:

* [`Span::next_point`](https://github.com/rust-lang/rust/blob/547c12b8a61d7d0c047649c236f84b59ca2d2cc9/src/libsyntax_pos/lib.rs#L89-L93) is not correct.
* The [label renderer](https://github.com/rust-lang/rust/blob/547c12b8a61d7d0c047649c236f84b59ca2d2cc9/src/librustc_errors/emitter.rs#L545-L573) isn't [properly accounting for malformed spans](https://github.com/rust-lang/rust/blob/547c12b8a61d7d0c047649c236f84b59ca2d2cc9/src/librustc_errors/emitter.rs#L296-L408) like the one being used here.

**Comment by ben0x539** [comment]
Ran into this with what minifies to
```
  ()
  let _ = ();
```
```
  |
2 |       ()
  |  _______- starting here...
3 | |     let _ = ();
  | |  ...^^^iunexpected tokend one of `.`, `;`, `?`, `}`, or an operator here
```

or

```
  f()
  g();
```

```
2 |       f()
  |  ________- starting here...
3 | |     g();
  | |  ...^nunexpected tokented one of `.`, `;`, `?`, `}`, or an operator here
```

Adding these because I almost filed a duplicate issue because searching for "iunexpected tokend" didn't give any results.

**Comment by est31** [comment]
Thanks @estebank for the quick fix!
