### ISSUE TITLE
Trailing `+` in bounds are allowed

### ISSUE THREAD

**Issue by qnighy** [rust-lang/rust#41158]
Current parser [allows ty/lt bounds have extra `+`](https://github.com/rust-lang/rust/blob/1.16.0/src/libsyntax/parse/parser.rs#L4025-L4072). However, the comments on the parser suggest they shouldn't be allowed. [grammar.md](https://github.com/rust-lang/rust/blob/1.16.0/src/doc/grammar.md) also suggests they shouldn't.

## Expected behavior

Both the first and second lines should lead to parse error.

```rust
fn f<'a>() where 'a: 'a + {}
fn g<'a, X>() where X: 'a + {}
fn main() {
}
```

## Current behavior

The current stable and nightly compilers allow the above code.

## Meta

Tested on Rust Playground.

stable

```
rustc 1.16.0 (30cf806ef 2017-03-10)
```

nightly

```
rustc 1.18.0-nightly (50c186419 2017-04-06)
```

**Comment by petrochenkov** [comment]
This works as expected, see https://github.com/rust-lang/rust/pull/39158 for the discussion.

>However, the comments on the parser suggest they shouldn't be allowed.
>grammar.md also suggests they shouldn't.

I forgot to update the comment :(
grammar.md seems to be largely unmaintained.

Marking this as a documentation issue so someone could this the comment and grammar.md.

**Comment by alexeyzab** [comment]
Hi there!

I'd like to fix this. I'll remove the `without trailing '+'` part from the comment, but I am not sure which part to edit in the grammar.md. I am assuming it has to be [somewhere here](https://github.com/rust-lang/rust/blob/master/src/doc/grammar.md#closure-types), the `bound-list` section probably?

**Comment by petrochenkov** [comment]
@alexeyzab 
Placing the bounds grammar into the closure grammar seems strange (https://github.com/rust-lang/rust/blob/master/src/doc/grammar.md#closure-types is also very outdated), I'd create a new separate  paragraph for it.
The current grammar for bounds can be found [here](https://github.com/rust-lang/rust/blob/910c4816fdee01a1299d11a5e85ebb4aceee6d1a/src/libsyntax/parse/parser.rs#L4073).
There are also two places mentioning "without trailing '+'", the second one needs to be fixed as well.

**Comment by alexeyzab** [comment]
@petrochenkov Good point, my bad. Thanks for pointing that out!

**Comment by alexeyzab** [comment]
Adjusted the comment and made a new paragraph for the current grammar. Let me know if this is okay.
