### ISSUE TITLE
Rustdoc no longer processes `text, no_run` code blocks 

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#41167]
With Rust 1.16.0, the following snippet is parsed correctly by `rustdoc`:

    //! ```text, no_run
    //! 'aa'
    //! ```

However, this appears to be broken on the latest `nightly` (tested on `53f4bc311 2017-04-07`). The code block appears to be interpreted as rust code, giving this error:

```
error: character literal may only contain one codepoint: 'aa'
 --> <stdin>:1:1
  |
1 | 'aa'
  | ^^^^

```

**Comment by GuillaumeGomez** [comment]
Taking a look.

**Comment by steveklabnik** [comment]
So, here's something interesting: the space after the `,` matters. That is, on stable

    //! ```text, no_run

passes but

    //! ```text,no_run

fails.

This might be considered a bugfix; it really depends. `text,no_run` is pretty incoherent as a combination of attributes, semantically speaking.

We should talk about this at the @rust-lang/docs meeting

**Comment by GuillaumeGomez** [comment]
@steveklabnik: We handle whitespaces strangely, I fix it.

**Comment by GuillaumeGomez** [comment]
@steveklabnik: I fixed the problem in the second commit.
