### ISSUE TITLE
rustup doesn't check all dependancies

### ISSUE THREAD

**Issue by fox8091** [rust-lang/rust#41176]
rustup doesn't check for the existence of Visual C++ Redistributable Packages for Visual Studio 2013 upon install, which rustc relies on.

**Comment by retep998** [comment]
This issue is for rustup and hence belongs on https://github.com/rust-lang-nursery/rustup.rs

Also, current rustc no longer relies on the VC++ redistributable.

**Comment by fox8091** [comment]
My bad, I didn't know there were separate repos. Also, I believe it does, unless that's fixed in a non-stable build? It still pulls msvcr120.dll on stable.
