### ISSUE TITLE
incr.comp.: Lints and other error messages are not included in the ICH

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#41184]
Once https://github.com/rust-lang/rust/pull/41141 lands, the compiler will compute the ICH for `TypeCheckTables` but when doing so, it will ignore the `lints` field. This is not a problem yet since we currently still unconditionally re-run type checking in incremental mode -- but in the future this could lead to wrong or dropped linting messages.

This should be addressed as part of refactoring the linting and error messaging system to better integrate with "on-demand" compilation.

**Comment by nikomatsakis** [comment]
See also #42511 (refactor lint handling to be more eager) and #42513 (capture diagnostic output in queries). I think we would ultimately be hashing the "diagnostic" structures, not the existing lint stuff (as described in #42513).

**Comment by michaelwoerister** [comment]
This is not a problem anymore.
