### ISSUE TITLE
RLS should use the in-tree copy of Cargo

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#41198]
Right now the RLS we build as part of releases will build a version of Cargo from crates.io, but we should use the vendored copy in this repository to guarantee they're the same version.

cc https://github.com/rust-lang/rust/pull/40584, @nrc, @jonathandturner

**Comment by nrc** [comment]
AIUI, this is closed by https://github.com/rust-lang/rust/pull/41639
