### ISSUE TITLE
Support `rls --version`

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#41197]
Right now the `rls` executable we're going to start shipping doesn't support `rls --version`, but we've got a relatively standard format between rls/cargo that should be supported. Cargo's [looks like this](https://github.com/rust-lang/cargo/blob/da4fadf6be3ef5030e411d3360244cf685617a58/src/cargo/lib.rs#L230-L270) and we probably want the RLS logic to look similar.

**Comment by alexcrichton** [comment]
cc https://github.com/rust-lang/rust/pull/40584, @nrc, @jonathandturner 

(you may wish to open a tracking issue in the rls repo to track this)

**Comment by jonathandturner** [comment]
The RLS currently has a --version flag. Is this bug tracking it landing in rustup?

**Comment by jonathandturner** [comment]
(lol, just noticed the date of the bug...)

**Comment by alexcrichton** [comment]
Aha yep! Just ran this:

```
$ rls +nightly --version
rls 0.1.0 (38ca9b7 2017-05-14)
```

Looks great to me! The only missing piece I believe is the "-nightly" or "-beta" piece. @jonathandturner do you know the right person to cc about that?

**Comment by jonathandturner** [comment]
I'd CC @nrc since he's overseeing RLS and can handle it

**Comment by nrc** [comment]
I added `-nightly` to the version string. The RLS is always nightly for now since we are not going though beta, etc. at the moment. Is that going to work for Rustbuild?

> The RLS currently has a --version flag. Is this bug tracking it landing in rustup?

AIUI Rustbuild should actually use the flag, rather than do whatever placeholder thing it does at the moment.

**Comment by alexcrichton** [comment]
Ok thanks @nrc! It sounds like we're going to discuss more of the stability story for the rls soon anyway? May be best to defer some of this to then if so.
