### ISSUE TITLE
Linker script does not get saved with -C save-temps

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#41208]
I ran into this error after upgrading to a more recent Rust version while using a linker script.

This script here is just to trigger the linker error so you can see the linker command line:
```
# lkr.scr
{ global: X; local: *; };
```

<pre>
$ rustc --version
rustc 1.16.0 (30cf806ef 2017-03-10)
$ rustc /dev/null --crate-type cdylib <i><b>-C save-temps</b></i> -C link-args=-Wl,--version-script=lkr.scr 
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" 
		  "/home/jethro/.multirust/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" 
		  "null.0.o" "-o" "libnull.so" 
		  "-Wl,--version-script=<i><b>/tmp/rustc.YcKvz9S1aalw/list</b></i>" 
		  "-Wl,--gc-sections" "-nodefaultlibs" "-L" 
		  "/home/jethro/.multirust/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" 
		  "-Wl,-Bstatic" "-Wl,-Bdynamic" 
		  "/home/jethro/.multirust/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-13f36e2630c2d79b.rlib" 
		  "/home/jethro/.multirust/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-a2ef7979b4b3e1d5.rlib" 
		  "/home/jethro/.multirust/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-d22754c8c52de3a1.rlib" 
		  "/home/jethro/.multirust/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_unicode-1cc5fcd37568ebc4.rlib" 
		  "/home/jethro/.multirust/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-3b9d178f1de89528.rlib" 
		  "/home/jethro/.multirust/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-93bb403c9fc56f72.rlib" 
		  "/home/jethro/.multirust/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-c53f99154bf815c4.rlib" 
		  "/home/jethro/.multirust/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_system-17a71bb92a82956c.rlib" 
		  "/home/jethro/.multirust/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-739908a2e215dd88.rlib" 
		  "/home/jethro/.multirust/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-3f4289353c600297.rlib" 
		  "/home/jethro/.multirust/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-07bfb3bcb2a51da0.rlib" 
		  "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" 
		  "c" "-l" "m" "-l" "rt" "-l" "util" "-shared" 
		  "-Wl,--version-script=lkr.scr"
  = note: /usr/bin/ld: anonymous version tag cannot be combined with other version tags
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

$ cat /tmp/rustc.YcKvz9S1aalw/list
cat: <i><b>/tmp/rustc.YcKvz9S1aalw/list: No such file or directory</b></i>
$ 
</pre>

**Comment by michaelwoerister** [comment]
Thanks for the report! So do I understand this correctly: You'd like that the linker script, that the compiler always creates, to not be automatically deleted when `-C save-temps` is specified?

**Comment by jethrogb** [comment]
Yes

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/38068 as it will be fixed by it (that's marked as E-mentor and E-easy by the way!).
