### ISSUE TITLE
Provide better documentation for procedural macros

### ISSUE THREAD

**Issue by torkleyy** [rust-lang/rust#41218]
For example, additional attributes are not documented at all.

**Comment by steveklabnik** [comment]
I believe that this is because those are a hack, rather than something that's really supposed to be done. @nrc?

**Comment by torkleyy** [comment]
@steveklabnik attributes in `#[derive]`d structs are a hack? :cry: I wouldn't use procedural macros if they didn't provide this feature.

**Comment by steveklabnik** [comment]
In general, Macros 1.1 is a hack. Full on Macros 2.0 will have real support for this in a non-hacky way.

**Comment by steveklabnik** [comment]
So yes, we'll have better and full docs here once we stabilize macros 2.0; until then, this is the level of docs we're comfortable with. Don't worry @torkleyy , we'll get there!
