### ISSUE TITLE
assertion failure in rustc (f64 as f64)

### ISSUE THREAD

**Issue by SetTheorist** [rust-lang/rust#41225]
Get a rustc assertion failure when compiling this short bit of code.

I tried this code:

fn main() {
    let n = &lt;f64 as f64&gt;::consts::NAN;
}

I get a compiler panic:

thread 'rustc' panicked at 'assertion failed: `(left == right)` (left: `Some(f64)`, right: `None`)', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc_typeck/astconv.rs:1515
stack backtrace:
   1:     0x7fe2f56433fa - std::sys::imp::backtrace::tracing::imp::write::h3188f035833a2635
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
(etc.)

## Meta

`rustc --version --verbose`:
rustc 1.15.0 (10893a9a3 2017-01-19)
binary: rustc
commit-hash: 10893a9a349cdd423f2490a6984acb5b3b7c8046
commit-date: 2017-01-19
host: x86_64-unknown-linux-gnu
release: 1.15.0
LLVM version: 3.9

Backtrace:
thread 'rustc' panicked at 'assertion failed: `(left == right)` (left: `Some(f64)`, right: `None`)', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc_typeck/astcon
v.rs:1515
stack backtrace:
   1:     0x7fe2f56433fa - std::sys::imp::backtrace::tracing::imp::write::h3188f035833a2635
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7fe2f565175f - std::panicking::default_hook::{{closure}}::h6385b6959a2dd25b
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:349
   3:     0x7fe2f56512fd - std::panicking::default_hook::he4f3b61755d7fa95
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:359
   4:     0x7fe2f5651c07 - std::panicking::rust_panic_with_hook::hf00b8130f73095ec
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:553
   5:     0x7fe2f5651a44 - std::panicking::begin_panic::h6227f62cb2cdaeb4
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:515
   6:     0x7fe2f56519b9 - std::panicking::begin_panic_fmt::h173eadd80ae64bec
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:499
   7:     0x7fe2f30c6c79 - <rustc_typeck::astconv::AstConv<'gcx, 'tcx> + 'o>::def_to_ty::h27e1d21802d9f007
   8:     0x7fe2f30c826c - <rustc_typeck::astconv::AstConv<'gcx, 'tcx> + 'o>::ast_ty_to_ty::h7a63a0a28ca42f96
   9:     0x7fe2f30c7aac - <rustc_typeck::astconv::AstConv<'gcx, 'tcx> + 'o>::ast_ty_to_ty::h7a63a0a28ca42f96
  10:     0x7fe2f30b0626 - rustc_typeck::check::FnCtxt::resolve_ty_and_def_ufcs::h85cd09cbccf4cb21
  11:     0x7fe2f309f63c - rustc_typeck::check::FnCtxt::check_expr_kind::h9af623bd4cd5cf75
  12:     0x7fe2f309e1cd - rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_lvalue_pref::h7c0abbe0f65b3569
  13:     0x7fe2f30b0a6d - rustc_typeck::check::FnCtxt::check_decl_initializer::hd4fefcf02b5a68f1
  14:     0x7fe2f30b0b74 - rustc_typeck::check::FnCtxt::check_decl_local::hec3d11a098e4381c
  15:     0x7fe2f30b0e9b - rustc_typeck::check::FnCtxt::check_stmt::hc84de4ff90060c01
  16:     0x7fe2f30b11ee - rustc_typeck::check::FnCtxt::check_block_with_expected::hcae0b63d8cfe7d18
  17:     0x7fe2f309e6bf - rustc_typeck::check::FnCtxt::check_expr_kind::h9af623bd4cd5cf75
  18:     0x7fe2f309e1cd - rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_lvalue_pref::h7c0abbe0f65b3569
  19:     0x7fe2f30840e0 - rustc_typeck::check::check_fn::hb8e4334cc9f9cc73
  20:     0x7fe2f3082d1a - rustc_typeck::check::check_bare_fn::h78fbe3464dc1e9cd
  21:     0x7fe2f3085c77 - rustc_typeck::check::check_item_body::h3991048ef9b95022
  22:     0x7fe2f308028e - rustc_typeck::check::check_item_bodies::ha44891fb199f492f
  23:     0x7fe2f30f2897 - rustc_typeck::check_crate::h04221c3337f6c701
  24:     0x7fe2f59e5767 - rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::h16429aca33e82f30
  25:     0x7fe2f59d25fe - rustc_driver::driver::phase_3_run_analysis_passes::h1b30709031b4f637
  26:     0x7fe2f59c1775 - rustc_driver::driver::compile_input::h71ecf4df05846d25
  27:     0x7fe2f5a0ab62 - rustc_driver::run_compiler::h180324a0694503f7
  28:     0x7fe2f591f47b - std::panicking::try::do_call::ha2c776608407d6f3
  29:     0x7fe2f565a42a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  30:     0x7fe2f5941021 - <F as alloc::boxed::FnBox<A>>::call_box::h08c51ed50888bb2f
  31:     0x7fe2f56505c4 - std::sys::imp::thread::Thread::new::thread_start::he018521f53b24939
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/liballoc/boxed.rs:615
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  32:     0x7fe2ee4bba03 - start_thread
  33:     0x7fe2f53407bc - <unknown>

**Comment by TimNN** [comment]
This seems to be fixed in 1.16.0.

**Comment by SetTheorist** [comment]
Oops, looks like you're right.
