### ISSUE TITLE
Add get_pagesize function

### ISSUE THREAD

**Issue by joshlf** [rust-lang/rust#41220]
It would be useful to have `std` support a `get_pagesize` function to make it easier to get the runtime-specific page size in a way that, for the caller, is platform-agnostic. Alternatively, it could also get more information such as all available page sizes (in addition to the default). This is already [supported internally by the allocator](https://doc.rust-lang.org/alloc/heap/fn.allocate.html):

> The alignment must be no larger than the largest supported page size on the platform.

**Comment by joshlf** [comment]
This is now supported by the [sysconf](https://crates.io/crates/sysconf) crate.

**Comment by dtolnay** [comment]
I believe this is going to require an [RFC](https://github.com/rust-lang/rfcs/blob/master/libs_changes.md). If there is an advantage to the sysconf crate's implementation being provided by the standard library, someone will need to propose a concrete API for exposing it and address any differences in implementation across platforms.
