### ISSUE TITLE
rustbuild check does not support “keep going” (-k)

### ISSUE THREAD

**Issue by jirutka** [rust-lang/rust#41248]
When using `--enable-rustbuild`, `make check -k` does not run _all_ tests regardless of failures.

https://github.com/rust-lang/rust/issues/31322#issuecomment-238029285:
> It seems it [rustbuild] doesn't support the -k (keep going) flag (that should be reported on the issue tracker if it's not there already), which should continue running the full test suite even if some individual test fails.

**Comment by eddyb** [comment]
cc @rust-lang/tools

**Comment by jirutka** [comment]
This is actually duplication of #40219, I found it just now.

**Comment by alexcrichton** [comment]
Indeed! Closing in favor of that.
