### ISSUE TITLE
[incremental] remove unnecessary passes

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#41251]
This is a sub-issue of #40746. The follow list of tasks are all executed for side-effects. I believe they can all be straight-up **removed** (that is, we just don't create a task at all). The idea is to remove the call to `with_task` or `in_task` as well as the associated  `DepNode` variant and see what happens -- if you get assertion failures, it may mean that they are writing to shared state, in which case we'll want to keep the task and refactor it in some other way. 

An example PR is https://github.com/rust-lang/rust/pull/41063. See e.g. [the first commit](https://github.com/rust-lang/rust/pull/41063/commits/768e7078785dd418968f26d79b1ff323403999ef) which removed the `CheckLoops` stuff.

- [x] `src/librustc_passes/loops.rs:53:    let _task = map.dep_graph.in_task(DepNode::CheckLoops);`
- [x] `src/librustc_passes/static_recursion.rs:91:    let _task = hir_map.dep_graph.in_task(DepNode::CheckStaticRecursion);` 
- [x] `src/librustc_borrowck/borrowck/mod.rs:64:    tcx.dep_graph.with_task(DepNode::BorrowCheckKrate, tcx, (), check_crate_task);`
- [x] `src/librustc/middle/effect.rs:244:    let _task = tcx.dep_graph.in_task(DepNode::EffectCheck);`
- [x] `src/librustc/middle/liveness.rs:199:    let _task = tcx.dep_graph.in_task(DepNode::Liveness);`
- [x] `src/librustc_typeck/check_unused.rs:65:    let _task = tcx.dep_graph.in_task(DepNode::UnusedTraitCheck);`
- [x] `src/librustc/middle/dead.rs:597:    let _task = tcx.dep_graph.in_task(DepNode::DeadCheck);`
     - this would use the `AccessLevels` query described elsewhere
- [x] `src/librustc_typeck/coherence/mod.rs:135:    let _task = tcx.dep_graph.in_task(DepNode::Coherence);`
- [x] `src/librustc_typeck/coherence/overlap.rs:42:        tcx.dep_graph.in_task(DepNode::CoherenceOverlapCheck(trait_def_id));`
- [x] `src/librustc_typeck/collect.rs:171:        self.tcx.dep_graph.with_task(DepNode::CollectItemSig(def_id), self.tcx, id, op);`

**Comment by nikomatsakis** [comment]
@aochagavia expressed interest in this from #40746

**Comment by aochagavia** [comment]
Great! I will give this a try next week.

**Comment by aochagavia** [comment]
By the way, in the issue you mention that `src/librustc/middle/dead.rs:597` needs to use an `AccessLevels` query. However, it seems that it is already being used on line 598: `let access_levels = &ty::queries::privacy_access_levels::get(tcx, DUMMY_SP, LOCAL_CRATE);`

**Comment by aochagavia** [comment]
@nikomatsakis I have a [commit](https://github.com/aochagavia/rust/commit/02ad86512b168d2f7253f8cba5f934909deb4b07) where I remove 4 of the 5 passes listed here. However, now I am blocked by the following question:

The pass in `src/librustc_typeck/coherence/mod.rs:135` used the `DepNode::Coherence` variant. After deleting the pass, I wanted to delete `DepNode::Coherence` as well, but I discovered that it is being used in multiple places. Particularly, it is being used by [this function](https://github.com/rust-lang/rust/blob/fef1026bae4a0cc59c4bd204021eea4e1a976b4f/src/librustc/ty/maps.rs#L460), which in turn is being used for something related to maps in `rustc/ty/maps.rs` (check out [this line](https://github.com/rust-lang/rust/blob/fef1026bae4a0cc59c4bd204021eea4e1a976b4f/src/librustc/ty/maps.rs#L437)). Should those maps also be removed? I am unable to see if they are somehow related to the task I just deleted. Maybe I should just let `DepNode::Coherence` alone.

**Comment by aochagavia** [comment]
Also, the pass in `src/librustc_typeck/collect.rs:171` is part of a [function](https://github.com/rust-lang/rust/blob/fef1026bae4a0cc59c4bd204021eea4e1a976b4f/src/librustc_typeck/collect.rs#L169) that clearly has side effects. In fact, removing the pass would leave the function body empty. What course of action would you suggest here?

**Comment by eddyb** [comment]
Yeah, don't remove nodes used by maps. Those are on-demand queries.

**Comment by aochagavia** [comment]
@eddyb do you have any ideas regarding my second question?

**Comment by eddyb** [comment]
@aochagavia I think you'd want to call `op` instead of removing it altogether, i.e.:
```rust
        self.with_collect_item_sig(item.id, convert_item);
// becomes
        convert_item(self.tcx, item.id);
```

**Comment by nikomatsakis** [comment]
@aochagavia argh, just saw your comments here. All resolved? 

I've been behind on notifications. I wound up accidentally doing some of this work in #41360, actually. Sorry if I stepped on your toes with that. :(

**Comment by aochagavia** [comment]
@nikomatsakis There is indeed some overlap, so I will have to rebase once your changes land. On the other hand, if changes need to happen fast here maybe I could work on other parts of the compiler (for instance, [this issue](https://github.com/rust-lang/rust/issues/41058))

**Comment by Mark-Simulacrum** [comment]
@nikomatsakis All the items in the issue are marked off, does that indicate this is done? If not, maybe OP should be updated with more items or a note added that there are more issues as well.

**Comment by nikomatsakis** [comment]
I think this is done -- @aochagavia, you agree?

**Comment by aochagavia** [comment]
@nikomatsakis I don't understand the question. What should I agree on? If this is done, it is done, right?

**Comment by nikomatsakis** [comment]
@aochagavia true. =) I'm not sure precisely what I was asking for. (I guess if you had noticed anything I overlooked, but if so, we'll find it sooner or later...)
