### ISSUE TITLE
assert_eq!() Should be able to compare &str with String

### ISSUE THREAD

**Issue by mcandre** [rust-lang/rust#41254]
Hey, could the `assert_eq!()` macro become more helpful, in particular allowing comparisons between `&str`'s and `String`'s?

**Comment by qnighy** [comment]
Just one `&` allows such comparison, I suppose.

```rust
fn main() {
    let mut s = String::from("foo");
    assert_eq!(&s, "foo");
    s.push_str("bar");
    assert_eq!(&s, "foobar");
    s.push_str("baz");
    assert_ne!(&s, "foobarbar");
}
```

**Comment by leoschwarz** [comment]
Would it be actually good if `assert_eq!` would test values as equal which `==` wouldn't?

Like I can see it making writing tests more easy but at the same time it might be potentially confusing.

**Comment by dtolnay** [comment]
The standard library provides all of the following impls so I believe this is supported now.

<sub>lhs</sub> \\ <sup>rhs</sup> | `str` | `&str` | `String` | `Cow<str>`
--- | --- | --- | --- | ---
**`str`** | ✔️ | |  ✔️ | ✔️
**`&str`** | |  ✔️ | ✔️ | ✔️
**`String`** | ✔️ | ✔️ | ✔️ | ✔️
**`Cow<str>`** | ✔️ | ✔️ | ✔️ | ✔️

```rust
fn main() {
    let s = String::new();
    assert_eq!(s, "");
    assert_eq!("", s);
}
```
