### ISSUE TITLE
Stop zeroing out the scratch buffer in float_to_decimal_common

### ISSUE THREAD

**Issue by bzbarsky** [rust-lang/rust#41259]
float_to_decimal_common in src/libcore/fmt/float.rs does this:

    let mut buf = [0; 1024];

which zeroes out the big buffer.  Given that it's a scratch buffer, there shouldn't be a reason to do that, I would think.

**Comment by eddyb** [comment]
[Link to the code in question](https://github.com/rust-lang/rust/blob/910c4816fdee01a1299d11a5e85ebb4aceee6d1a/src/libcore/fmt/float.rs#L26). IMO we should start using `ArrayVec` and variations of it (including ring buffers and even arbitrary number of ranges or other "partial initialization patterns") throughout the libs.

cc @rust-lang/libs

**Comment by sfackler** [comment]
Is there a concrete performance issue that this is proposing to tackle? I would like to avoid moving from use of initialized to uninitialized memory "just because".

**Comment by eddyb** [comment]
@sfackler It came up in a Servo profile. But regardless, I would like to use safe abstractions over partial initialization of stack arrays, to better represent the semantics involved.

**Comment by bzbarsky** [comment]
> Is there a concrete performance issue that this is proposing to tackle?

Yes.  The zeroing out was about 5% of the time taken in a "get the specified value of `top`" microbenchmark for stylo.

Or another way to think of it is that it's 15% of the time Safari takes to execute the entire operation.  ;)

**Comment by sfackler** [comment]
Cool, seems worth fixing then 👍
