### ISSUE TITLE
Better type system support for describing closure signatures

### ISSUE THREAD

**Issue by mcandre** [rust-lang/rust#41257]
In rustc v1.16.0, I cannot describe the full type of an Iterator `.map()` return value, as the type system fails at describing closures.

As a workaround, I can use blanks, e.g. `Map<_, _>`. But I'd really like to use a more meaningful type for this return value.

Example:

https://github.com/mcandre/ios7crypt-rs/blob/256b47ee19d80c972d9e227fc380db2080495d39/src/lib/ios7crypt.rs#L79-L82

**Comment by steveklabnik** [comment]
Hey @mcandre ! Larger changes and big features belong in the RFC repo, not as bugs on `rust-lang/rust`. You should pursue this over there: https://github.com/rust-lang/rfcs

Thanks!
