### ISSUE TITLE
Tracking issue for `ToOwned::clone_into` (`toowned_clone_into`)

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#41263]
Feature added in PR https://github.com/rust-lang/rust/pull/41009

Questions raised in the PR:

- [ ] The directionality is weird. In clone_from and assignment, the data moves right-to-left, but this moves it left-to-right. And that means that autoref doesn't work well, usually forcing you to write &mut.

- [ ] But fixing that would mean putting it somewhere else, since the Self in ToOwned is the wrong type for what this needs to be. And moving it while still being overridable and providing a default is hard.

**Comment by SimonSapin** [comment]
In nightly for 11 months with no reported issues since. Let’s stabilize.

@rfcbot fcp merge

**Comment by scottmcm** [comment]
Hmm, I was bad at creating tracking issues a year ago :sweat_smile: 

This is _sufficient_, but still feels suboptimal for the reasons from https://github.com/rust-lang/rust/pull/41009#issue-113803675:

- The directionality is weird.  In `clone_from` and assignment, the data moves right-to-left, but this moves it left-to-right.  And that means that autoref doesn't work well, usually forcing you to write `&mut`.

- But fixing that would mean putting it somewhere else, since the `Self` in `ToOwned` is the wrong type for what this needs to be.  And moving it while still being overridable and providing a default is hard.

Any good ideas?

**Comment by alexcrichton** [comment]
@rfcbot concern direction

formally registering @scottmcm's [concern](https://github.com/rust-lang/rust/issues/41263#issuecomment-374498676)

**Comment by scottmcm** [comment]
I feel bad seeing this in TWiR every week now.  Anything I can do to help it get somewhere productive?

**Comment by kennytm** [comment]
Nominating for discussion. ↑.

**Comment by SimonSapin** [comment]
It looks like this still needs some API some design work, so we’re not actually ready to stabilize.

@rfcbot fcp cancel

This probably needs someone to champion a new API proposal.

**Comment by m-ou-se** [comment]
This was discussed in the libs-api meeting just now. We discussed how this method is used in Cow's clone_from implementation, and how that seems to be a good reason to stabilize this function and allow others to imlement it.

@rfcbot merge

**Comment by scottmcm** [comment]
Friendly one-month pFCP ping, @Amanieu @BurntSushi @joshtriplett
