### ISSUE TITLE
Tidy feature: deny commits with a tracking issue of 0

### ISSUE THREAD

**Issue by clarfon** [rust-lang/rust#41260]
A reasonable number of commits get pushed that forget a tracking issue, so, I think that this would be useful to have. Additionally, it'd be nice if any `#[unstable]` attributes got checked to make sure that the tracking issues are all the same.

 This should also check links in the unstable book.

**Comment by GuillaumeGomez** [comment]
I'm against it. A lot of commits/improvements don't have an issue because it has been discussed outside github.

**Comment by varkor** [comment]
As discussed in https://github.com/rust-lang/rust/pull/49985#issuecomment-383728579, the way forward here is making the `issue` field optional. This should be easy to fix. You can probably just remove this branch:
https://github.com/rust-lang/rust/blob/6d599337fa7047307ba72786bbabe6b9c9e4daac/src/libsyntax/attr/builtin.rs#L363-L366
and remove any existing `issue = "0"` fields.

**Comment by Julius-Beides** [comment]
I have looked into this and the easiest way to do it is to internally use 0 as the issue number if it wasn't given. 
This feels a bit hacky. Should I try to change the type in `StabilityLevel::Unstable` from `issue: i32` to `issue: Option<i32>` instead?

**Comment by varkor** [comment]
> Should I try to change the type in `StabilityLevel::Unstable` from `issue: i32` to `issue: Option<i32>` instead?

Yes, that's right. `0` should not be used to encode an issue anywhere; we should be using `Option` instead.

**Comment by Julius-Beides** [comment]
Ok, the types were changed to `issue: Option<i32>` in a few places and I added a basic ui test. It turned out that issue fields were already `Option<i32>` in most places. 

Tomorrow I'll try to fix the 79 `#[unstable(... , issue = "0")]` I found. (And make a proper warning)
