### ISSUE TITLE
Code wrongly optimized away

### ISSUE THREAD

**Issue by th0rex** [rust-lang/rust#41271]
Sorry for the lack of a better title, I really don't know how to describe this in a short way.

I'm trying to set the `__malloc_hook` global variable from libc to a custom function written in Rust, so that I can track memory allocations. On a debug build, everything is fine, but on a release build that is a bit different. If I add random `println!` the release build is fine, if I don't the release build is broken (that means the generated assembly code is wrong/not generated).

This is my code:
```rust
#[macro_use]
extern crate lazy_static;
extern crate libc;

use std::sync::Mutex;
use std::os::raw::c_void;

type Malloc = extern "C" fn(size: usize) -> *mut c_void;

extern "C" {
    static mut __malloc_hook: Malloc;

    fn malloc(size: usize) -> *mut c_void;
}

#[derive(Clone, PartialEq)]
struct HookState {
    malloc: Malloc,
}

impl HookState {
    fn from_current() -> HookState {
        HookState {
            malloc: unsafe { __malloc_hook },
        }
    }

    fn from_overrides() -> HookState {
        HookState {
            malloc: my_malloc,
        }
    }

    fn to_globals(&self) {
        unsafe {
            __malloc_hook = self.malloc;
        }
    }
}

lazy_static! {
    static ref ORIGINAL_STATE: Mutex<HookState> = Mutex::new(HookState::from_overrides());
}

#[no_mangle]
pub extern "C" fn heap_iter_static_init() {
    let mut state = ORIGINAL_STATE.lock().unwrap();
    *state = HookState::from_current();
    // Setup hooks
    HookState::from_overrides().to_globals();
}

extern "C" fn my_malloc(size: usize) -> *mut c_void {
    let state = ORIGINAL_STATE.lock().unwrap();
    // Restore original hooks
    state.to_globals();
    let p = unsafe { malloc(size) };
    //println!("malloc(size={})={:?}", size, p);
    //println!("wtf");
    HookState::from_overrides().to_globals();
    p
}
```
I set the cratetype to `cdylib` in `Cargo.toml` so that a shared object file is generated.

The function `heap_iter_static_init` is called by another shared object and just saves the current hooks and sets them to my custom functions. 

`my_malloc` then first restores the hooks, does the malloc, and overrides the hooks again. In debug builds this is working fine. In release builds the hooks are NOT restored (even tho my code restores them), which results in `my_malloc` getting called again by the call to `malloc` and thus a deadlock. 

However, if I uncomment any of the two `println!` lines in the `my_malloc` function, the code does work and the hooks are actually restored to their old state. I really don't know how to further debug this.

I also looked at the assembly output. I won't include the debug assembly, because that is fine.

The working version refers to the version with any of the two `println!` lines uncommented and compiling in release mode and the non working version refers to the version with no `println!` after the malloc and compiling in release mode. The assembly code is taken from a nightly compiler.

This is the relevant assembly of the non working version: [not working](https://ibb.co/dnMyD5)
This is the relevant assembly of the working version: [working](https://ibb.co/kxJjmQ)

Note the additional lines
```asm
mov rax, qword [rbp + arg_10h]
mov rbx, qword [reloc.__cxa_finalize_184]
mov qword[rbx], rax
```
in the working version right before the call to `malloc`, which are completly missing in the non working version and those are the instructions that actually set the `__malloc_hook` variable.

So to summarize this:
* debug build: everything fine
* release build without the println: code not generated
* release build with the println: code is generated, everything fine

I thus guess that either llvm is broken or the rust compiler is broken (or my code actually is wrong/not valid), but I have no idea where to start figuring out what actually causes this.

## Meta
This was tested with the following compilers:
1. Kinda old nightly
```
rustc 1.18.0-nightly (2564711e8 2017-04-04)
binary: rustc
commit-hash: 2564711e803f62e04bebf10408cc1c11297c0caf
commit-date: 2017-04-04
host: x86_64-unknown-linux-gnu
release: 1.18.0-nightly
LLVM version: 3.9
```
2. Current nightly version I can download (as `rustup update` seems to be broken)
```
rustc 1.18.0-nightly (3b5754e5c 2017-04-10)
binary: rustc
commit-hash: 3b5754e5ce73d24c6684b3ed0c68a557dfdd2f52
commit-date: 2017-04-10
host: x86_64-unknown-linux-gnu
release: 1.18.0-nightly
LLVM version: 3.9
```
3. Stable
```
rustc 1.16.0 (30cf806ef 2017-03-10)
binary: rustc
commit-hash: 30cf806ef8881c41821fbd43e5cf3699c5290c16
commit-date: 2017-03-10
host: x86_64-unknown-linux-gnu
release: 1.16.0
LLVM version: 3.9
```
All 3 versions have the same behaviour.

**Comment by jonas-schievink** [comment]
Function references may never be null, otherwise you cause undefined behaviour

**Comment by th0rex** [comment]
Ok, thanks for the hint. I updated the code and this doesn't change anything about the issue.

**Comment by arielb1** [comment]
@th0rex 

You should have
```Rust
    static mut __malloc_hook: Option<Malloc>;
```

Having a `static` function pointer with a null value is UB - the compiler can do whatever it wants (for example, `Some(__malloc_hook) == None`).

**Comment by th0rex** [comment]
As I've said `__malloc_hook` is a global variable defined in libc, I'm just linking against that. Thus I can't change the type and as far as I can tell that should be valid. If that's not valid, how do I link against global function pointers in C libraries then ?

**Comment by arielb1** [comment]
@th0rex 

The Rust type `Option<Malloc>` is compatible with the C type `void *(*foo)(size_t)`. Just use it.

**Comment by th0rex** [comment]
Thank you very much, that fixes it! I didn't know that `Option` was compatible with that.
