### ISSUE TITLE
if clauses following an if let are compiled to match guards

### ISSUE THREAD

**Issue by nox** [rust-lang/rust#41272]
https://is.gd/2ZnMND

is this code:

```rust
struct Foo;

impl Foo {
    fn bar(&mut self) -> bool { true }
}

fn error(foo: &mut Foo) {
    if let Some(_) = Some(true) {
    } else if foo.bar() {}
}

fn ok(foo: &mut Foo) {
    if let Some(_) = Some(true) {
    } else {
        if foo.bar() {}
    }
}

fn main() {}
```

yielding:

```
rustc 1.16.0 (30cf806ef 2017-03-10)
error[E0301]: cannot mutably borrow in a pattern guard
 --> <anon>:9:15
  |
9 |     } else if foo.bar() {}
  |               ^^^ borrowed mutably in pattern guard
```

**Comment by eddyb** [comment]
[Where this happens](https://github.com/rust-lang/rust/blob/43ef63d5b4279ef97ed921338a69b0d62101ca83/src/librustc/hir/lowering.rs#L2036). I don't know why we do this, the "else" part of "if" or "if-let" is an arbitrary expression:
```rust
if let pat = expr1 {...} else expr2
// can be lowered to
match expr1 {
    pat => {...}
    _ => expr2
}
```
This seems simpler, less error prone and it won't hit arbitrary limitations specific to `match` guards.

**Comment by nikomatsakis** [comment]
The RFC states:

> Optionally, one or more else if (not else if let) blocks can be placed in the same match using pattern guards on _. This could be done to simplify the code when pretty-printing the expansion result. Otherwise, this is an unnecessary transformation.

I would call this a bug.

**Comment by nikomatsakis** [comment]
triage: P-medium

**Comment by nikomatsakis** [comment]
This is a great mentoring bug! I'm going to write up some **very** quick pointers for now. Please reach out for more details. In short, the code that needs to be changed is in the "HIR lowering", which converts from the AST (what the user wrote) to the compiler's internal HIR (also an abstract syntax tree, but somewhat desugared). The code in question is in [lowering.rs](https://github.com/rust-lang/rust/blob/master/src/librustc/hir/lowering.rs), specifically right [around here](https://github.com/rust-lang/rust/blob/master/src/librustc/hir/lowering.rs#L2031-L2149). There is also some more logic. You'll want to change how it is desugaring along the lines that @eddyb suggested [in this comment](https://github.com/rust-lang/rust/issues/41272#issuecomment-293938986).

**Comment by cuviper** [comment]
I'm interested in taking this bug.

**Comment by suchithjn225** [comment]
@nikomatsakis @eddyb @nox   Hello I'm new to open source and Rust project. I wanted to contribute to the project. May I work on this bug?

**Comment by suchithjn225** [comment]
@nikomatsakis @eddyb @nox Hello I'm new to open source and Rust project. I wanted to contribute to the project. May I work on this bug?

**Comment by eddyb** [comment]
@suchithjn225 Sure thing! Let us know how far you get with https://github.com/rust-lang/rust/issues/41272#issuecomment-294011545. We're also on IRC.

**Comment by cuviper** [comment]
@suchithjn225 I'll yield to you -- good luck!

**Comment by suchithjn225** [comment]
```rust
struct Foo;

impl Foo {
    fn bar(&mut self) -> bool { true }
}

fn error(foo: &mut Foo) {
    if let Some(_) = Some(true) {
    } else if foo.bar() {}
}

fn desugar_test(foo: &mut Foo) {
	let x = Some(true);
	match x {
		Some(_) => {},
		_ => {
			if foo.bar() { }
		}
	}
}

fn desugar_error(foo: &mut Foo) {
	let x = Some(true);
	match x {
		Some(_) => {},
		_ if foo.bar() => {},
		_ => {}
	}
}

fn ok(foo: &mut Foo) {
    if let Some(_) = Some(true) {
    } else {
        if foo.bar() {}
    }
}

fn main() {}
```

If IfLet expression is desugared to the one shown in desugar_test() then it works as suggested by @eddyb
