### ISSUE TITLE
rustbuild: using configure script makes --target and --host always set when running x.py 

### ISSUE THREAD

**Issue by malbarbo** [rust-lang/rust#41278]
For example, generating `config.mk` with the command `./configure --target=i686-unknown-linux-gnu --host=i686-unknown-linux-gnu` and running `./x build --target=i686-unknown-linux-gnu` will also build `rustc` for `i686-unknown-linux-gnu` because `--host=i686-unknown-linux-gnu` is loaded from `config.mk`. I'm reporting this because all docker ci builders are passing `--target` or/and `--host` to `x.py`, but they have no affect because the ci builders are using `./configure` and so this args are loaded from  `config.mk`.

@alexcrichton Is this the intended behavior? Is there a way to avoid this (using configure instead of config.toml)?

**Comment by alexcrichton** [comment]
AFAIK ./configure vs config.toml is a red herring here, they have the same affect in how rustbuild loads configuration.

Currently the set of artifacts compiled is intended behavior, but in some circumstances it is indeed confusing!

**Comment by malbarbo** [comment]
Should we close this issue? Should another issue be opened regarding removing target and host parameters to x.py in the ci builders?

**Comment by alexcrichton** [comment]
Ok sure yeah, we can close, and feel free to file a separate issue!
