### ISSUE TITLE
Create sections inside the unstable book

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#41289]
I think for greater categorisation, the unstable book should be divided into sections.

A proposal:

* Compiler internal lang features ("not intended for general use")
* Permanently unstable features that are not compiler internal (like the llvm intrinsics)
* Novel lang features (with intent to stabilize them some day)
* Library features
* ??

Some sections should have a higher standard of documentation, like the novel lang features, others like the library features already have documentation in rustdoc (see #41288), so their documentation should be limited to a link to the tracking issue (and maybe their rustdoc), and the "not intended for general use" features can get a lower priority to be documented as well.

**Comment by frewsxcv** [comment]
Folding this into https://github.com/rust-lang/rust/issues/41142

**Comment by frewsxcv** [comment]
Or if you feel that issue is different than what you're proposing, feel free to reopen.

**Comment by frewsxcv** [comment]
I guess it's sufficiently different.

**Comment by est31** [comment]
Oh so you made PR #41295 ... only discovered it now. It has rougher categories than what was suggested by me, but I think its a good compromise. Thanks! Closing.
