### ISSUE TITLE
Limit documentation of library features in the unstable book

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#41288]
I think documentation for library/std features should be put into rustdoc instead of the unstable book, as that is the most likely place to read about the functionality, and best suited in various ways. I propose to only include minimal documentation for them, like name, a link to the tracking issue, and maybe a link to the rustdoc of the places its used.

Also, they should be in their own section, and the tidy lints should enforce it.

**Comment by steveklabnik** [comment]
I'm going to consider this one a dup of https://github.com/rust-lang/rust/issues/41142; that is, it'd be better to talk about this in that issue (or really, an internals thread, but we *already* have multiple issues here) than spread this out everywhere.
