### ISSUE TITLE
Move traits/error_reporting to its own module

### ISSUE THREAD

**Issue by cengizIO** [rust-lang/rust#41284]
Hello @nikomatsakis 
As you suggested, we should move [traits/error_reporting.rs](https://github.com/rust-lang/rust/blob/master/src/librustc/traits/error_reporting.rs) to a separate file.

This issue is created to serve as a reminder.

**Comment by Mark-Simulacrum** [comment]
Note: This issue is about moving specific functions out of the error reporting file, see [this comment](https://github.com/rust-lang/rust/pull/41236#discussion_r111243014) for more details.

**Comment by Mark-Simulacrum** [comment]
This was done in 7b9519a5d47879c37f0ac6871cee2e1cb8eca1cc.
