### ISSUE TITLE
grammar/README.md is outdated

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#41326]
[src/grammar/README.md](https://github.com/rust-lang/rust/blob/577497b541110f814c8385eff86a2d2e4b935585/src/grammar/README.md) is outdated. First, it still contains mentions of the legacy make system. Also, while make and make tidy technically might work, `make check-build-lexer-verifier` doesn't work at least since commit 9ab8090bd4c8fed848cfebe2ab818a91e43e225c and the claim that make tidy includes the check is wrong even longer (d3b050c3084f12545a8c224f8d88813b25f46c80).

It should be updated. Most likely the the checks have to be ported over to the new system as well.

**Comment by kennytm** [comment]
`make` and `make tidy` still works with rustbuild (the latter calls `x.py test src/tools/tidy`).

**Comment by est31** [comment]
@kennytm still, `make check-build-lexer-verifier` does not work (probably) since commit 9ab8090bd4c8fed848cfebe2ab818a91e43e225c and the claim the lexer verifier is built during make tidy is wrong even longer, since commit d3b050c3084f12545a8c224f8d88813b25f46c80 . 

The file is simply outdated and should be updated.

**Comment by est31** [comment]
I'll edit the description to fit the problems more closely.

**Comment by steveklabnik** [comment]
Grammar stuff is in the reference now; we should remove the stuff in-tree.

**Comment by est31** [comment]
In fact the file in question was removed by commit c3781e620084b2e2eba7e8a31b8248410ddca347 (PR  #41705). There's still grammar stuff in tree but that should be tracked by a separate issue. Closing.
