### ISSUE TITLE
Can't use const fn directly as inline assembly constant input

### ISSUE THREAD

**Issue by parched** [rust-lang/rust#41337]
I hoped this would work
```
const fn get_3() -> u32
{
    3
}

pub unsafe fn use_get_3()
{
    asm!("" : : "i"(get_3()))
}
```
but it generates (without optimizations)
```
  %0 = call i32 @_ZN8rust_out5get_317hccb90954bf88bf3cE()
  call void asm "", "i,~{dirflag},~{fpsr},~{flags}"(i32 %0)
```
giving `error: invalid operand for inline asm constraint 'i'`.

The current solution seems to be
```
pub unsafe fn use_three()
{
    const THREE: u32 = get_3();
    asm!("" : : "i"(THREE))
}
```
which generates
```
  call void asm "", "i,~{dirflag},~{fpsr},~{flags}"(i32 3)
```
like I hoped the first case would.

Could we make the first case guaranteed to work?

**Comment by eddyb** [comment]
We could make this work the same we did for SIMD intrinsics:
https://github.com/rust-lang/rust/blob/54b7d21f59a363e53eb1c31d76b40af2ff99321c/src/librustc_mir/transform/promote_consts.rs#L219-L238

cc @Amanieu @oli-obk @ecstatic-morse

**Comment by hanna-kruppe** [comment]
Note that the current proposal for inline assembly includes `const <expr>` operands that explicitly are constant expressions, and [the prototype implementation treats them more or less as you describe](https://github.com/rust-lang/rust/pull/69171/commits/934ac1ca1eac86254c9592c903dcdc9ee10fdee4). I don't think it's worth doing the same for "legacy" inline asm.

**Comment by eddyb** [comment]
Oh, nice, for some reason I expected if that were the case we'd get a comment on these issues stating it, I should've checked first.

**Comment by Amanieu** [comment]
This issue does not apply to the new `asm!` ([RFC 2850](https://github.com/rust-lang/rfcs/pull/2850)) which has proper support for `const` operands.

The legacy `llvm_asm!` is deprecated and is no longer maintained.
