### ISSUE TITLE
Trying to debug print the difference of two BTreeSets goes into endless print loop.

### ISSUE THREAD

**Issue by CajetanP** [rust-lang/rust#41338]
I tried printing difference of two BTreeSets using the debug print, but instead of printing anything useful it went into some weird recursive loop printing Difference(Difference(Difference endlessly.

I tried this code:

```Rust
let mut a = BTreeSet::new();
a.insert(1);
a.insert(2);

let mut b = BTreeSet::new();
b.insert(2);
b.insert(3);

println!("{:?}", a.difference(&b));
```

I obviously expected it to print something like Difference(*contents*) just like when debug printing some vec.iter().

Instead, it started printing this:

>Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference(Difference

It wouldn't stop until I killed the process.

I read the source file set.rs and I couldn't find any Debug implementation or derivation for Difference struct so I think it might be related somehow. I don't really know how it compiles without Debug being implemented / derived on this struct but I don't understand how language intrinsics work just yet.

## Meta

`rustc --version --verbose
rustc 1.18.0-nightly (28a742997 2017-04-13)
binary: rustc
commit-hash: 28a74299778cdad4ea999e4ee8f8c1ef793338bd
commit-date: 2017-04-13
host: x86_64-apple-darwin
release: 1.18.0-nightly
LLVM version: 3.9'

It doesn't panic so there's no backtrace to put here.

**Comment by sfackler** [comment]
`Debug` is implemented here: https://github.com/rust-lang/rust/blob/master/src/libcollections/btree/set.rs#L141. Seems like a pretty straightforward infinite recursion to me. Added in #39002 - cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Oh indeed, my bad. Fixing it.

**Comment by TimNN** [comment]
This effects beta as well.
