### ISSUE TITLE
missing closure bracket

### ISSUE THREAD

**Issue by Netzcream** [rust-lang/rust#41341]
In the last update, players.json have a missing closure bracket for each player at the end of the record.
![image](https://cloud.githubusercontent.com/assets/8697981/25093820/61c55c42-236a-11e7-8d59-03e361e1f9df.png)

Actual:
[
{"id":"xx","name":"xx","position":{"x":372,"y":20,"z":22},"rotation":88,"time":1492423301,"ip":"68.102.70.138:53362",
"inventory":{
"main":[{"name":"arrow.wooden","amount":40}],
"belt":[{"name":"bow.hunting","amount":1,"condition":87}],
"wear":[{"name":"tshirt.long","amount":1}]
}]

Must Be:
[
{"id":"xx","name":"xx","position":{"x":372,"y":20,"z":22},"rotation":88,"time":1492423301,"ip":"68.102.70.138:53362",
"inventory":{
"main":[{"name":"arrow.wooden","amount":40}],
"belt":[{"name":"bow.hunting","amount":1,"condition":87}],
"wear":[{"name":"tshirt.long","amount":1}]
}**_}_**]

Thanks.

**Comment by steveklabnik** [comment]
Sorry, what is `players.json`?

**Comment by Netzcream** [comment]
Sorry, not for this git, my mistake...
how can i delete this?

**Comment by steveklabnik** [comment]
No worries! No need to delete it, I can just close it.
