### ISSUE TITLE
Spurious unused import warning with trait used transitively via use super::*

### ISSUE THREAD

**Issue by khuey** [rust-lang/rust#41358]
```rust
use std::rc::Rc;
use std::ops::Deref;

mod foo {
    use super::*;

    pub struct Bar {
        pub thing: Rc<u32>,
    }
    
    impl Bar {
        pub fn baz(&self) -> &u32 {
            self.thing.deref()
        }
    }
}

fn main() {
    let use_bar = foo::Bar {
        thing: Rc::new(42),
    };
    println!("value {}", use_bar.baz());
}
```

triggers
```
warning: unused import: `std::ops::Deref`, #[warn(unused_imports)] on by default
 --> <anon>:2:5
  |
2 | use std::ops::Deref;
  |     ^^^^^^^^^^^^^^^
```

This happens on both stable and nightly.  The warning goes away if `use super::*` is replaced by `use super::{Rc, Deref}`.  And the sample of course fails to compile if you remove the `use std::ops::Deref`.

I ran into this while trying to take advantage of serde-rs/serde#765 by defining a bunch of modules with a common set of imports and a `use super::*` in each module for simplicity.

**Comment by Wolvereness** [comment]
I also ran across this with the write trait if another example is needed, https://play.rust-lang.org/?gist=296cf1f7d10dbc7a31509e531ac4760f&version=stable

**Comment by tjpalmer** [comment]
I also ran across this problem while trying out this code: https://github.com/KeepCalmAndLearnRust/pratt-parser

A compiler that cries wolf can break trust.

**Comment by ExpHP** [comment]
Same as #45268.  I'm building a list of linkbacks there for whoever wants to add half a dozen bug reports to their trophy case.

(too bad I chose that issue, this one has a much more accurate title!)

**Comment by sanxiyn** [comment]
Yes, this is a much better title, so I retitled the merged issue. Closing as a duplicate.
