### ISSUE TITLE
Cannot add racer using rustup for nightly

### ISSUE THREAD

**Issue by rjammala** [rust-lang/rust#41359]
I tried adding the racer component to rustup/nightly and get the following error:

$ rustup component add racer
error: toolchain 'nightly-x86_64-unknown-linux-gnu' does not contain component 'racer' for target 'x86_64-unknown-linux-gnu'

**Comment by rjammala** [comment]
$ rustc --version
rustc 1.18.0-nightly (7627e3d31 2017-04-16)

**Comment by KalitaAlexey** [comment]
First of all it is a wrong repository. [The right one](https://github.com/rust-lang-nursery/rustup.rs)
Secondly, [racer is a standalone binary](https://github.com/phildawes/racer)
Execute `cargo install racer` in order to install it.

**Comment by rjammala** [comment]
Sorry, my mistake.

**Comment by KalitaAlexey** [comment]
@rjammala,
It's fine. Everyone makes mistakes.
