### ISSUE TITLE
Compiler panics on missing 'fn'.

### ISSUE THREAD

**Issue by ericfindlay** [rust-lang/rust#41389]
Lets say you want to write this:
```
struct A {
    n: i32,
}

impl A {
    fn n(&self) -> i32 {
        self.n
    }
}
```
but you forget the ```fn```

```
struct A {
    n: i32,
}

impl A {
    n(&self) -> i32 {
        self.n
    }
}
```
then the compiler responds with "note: the compiler unexpectedly panicked. this is a bug." I don't know if its possible but a "missing fn" message would be ideal or at least a "expected one of `!` or `::`, found `(`"

**Comment by petrochenkov** [comment]
This should be fixed in https://github.com/rust-lang/rust/pull/41282 and the fix is going to appear in the next nightly.
