### ISSUE TITLE
Vec should implement From<&mut [T]>

### ISSUE THREAD

**Issue by adamcrume** [rust-lang/rust#41386]
`Vec` already has:

    impl<'a, T> From<&'a [T]> for Vec<T> where T: Clone

but it should also have:

    impl<'a, T> From<&'a mut [T]> for Vec<T> where T: Clone

A workaround is to use `Vec::from(my_mut_ref as &[T])`.

**Comment by Twey** [comment]
Or `my_mut_ref.to_vec()`.  Though the instance would be nice for genericity, of course.
