### ISSUE TITLE
doc: In the book on the "Conditional Compilation" page should be a link to the Rust Reference

### ISSUE THREAD

**Issue by KalitaAlexey** [rust-lang/rust#41388]
[Conditional Compilation](https://doc.rust-lang.org/book/conditional-compilation.html) does not contain a link to [Rust Reference](https://doc.rust-lang.org/reference.html#conditional-compilation).

I am raising this issue because I suppose #41223 was created because the author hadn't know how to do that.

**Comment by KalitaAlexey** [comment]
I have opened this issue to track what I am going to do.
If you are willing to take it, write a comment please.

**Comment by steveklabnik** [comment]
Hey @KalitaAlexey ! Two things:

1. The book is now in its own repo, so bugs for the book should go there: https://github.com/rust-lang/book
2. We aren't tracking bugs for the first edition of the book: if you'd like to make this change, please send a PR to make it. We're happy to merge PRs but aren't spending time on it ourselves.

Thanks!

**Comment by KalitaAlexey** [comment]
Oh. I didn't know it.
