### ISSUE TITLE
(eg) TcpStream::shutdown() can't interrupt pending I/O

### ISSUE THREAD

**Issue by dimbleby** [rust-lang/rust#41399]
Not sure whether this one is only confusing docs, or a more serious awkwardness, or possibly just my misunderstanding.

Docs for `TcpStream::shutdown()`, eg [here](https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.shutdown), claim that "This function will cause all pending and future I/O on the specified portions to return immediately".

But is it possible for there even to be any pending I/O?  Both `read()` and `write()` take `&mut self`: so if there were pending I/O, then it would be impossible to have a reference on which to call `shutdown()` - right?

(I suppose if we're being super-pedantic, it's strictly correct to say that all of "no things" will return immediately, but it's not very helpful!)

If I haven't misunderstood then this is at least a docs infelicity.  But perhaps it's worse than that - wouldn't it be useful to be able to call `shutdown()` on a `TcpStream`, precisely so as to interrupt `read()` or `write()` calls?

(Same for other similar things eg `UdpStream`, `UnixStream`, any others that I've not thought of).

**Comment by rkruppe** [comment]
`Read` and `Write` are also implemented on `&TcpStream`.

**Comment by dimbleby** [comment]
does that help?  I still can't get both `&mut T` and `T` simultaneously, even when `T` is `&TcpStream` - can I?  (my head hurts!)

**Comment by rkruppe** [comment]
You can have multiple `&TcpStream` that refer to the same `TcpStream` object:

```
let stream: TcpStream = ...;
let stream1 = &stream;
let stream2 = &stream;
```

**Comment by dimbleby** [comment]
gotcha, thanks for putting me right!
