### ISSUE TITLE
cdylib on Windows provides only the .dll without the associated .lib import library

### ISSUE THREAD

**Issue by cpralea** [rust-lang/rust#41393]
On Windows, runing `cargo build` on a cdylib crate produces only the .dll in `target/{debug,release}` while the associated .lib import library is missing.

It would be useful to have both the .dll and the .lib so that load-time dynamic linking can be used.

**Comment by steveatinfincia** [comment]
@cpralea is the `.lib` present in `target/deps` but simply not being lifted into `target` at the end of the build?

**Comment by retep998** [comment]
I'm pretty sure this issue should belong in https://github.com/rust-lang/cargo since it is cargo which is failing to copy over important associated files such as import libraries and pdb files.

**Comment by cpralea** [comment]
@steveatinfincia the following files are present under `target/{debug,release}/deps`:
- `<name>-<hash>.dll`
- `<name>-<hash>.dll.lib`
- `<name>-<hash>.dll.exp`
- `<name>-<hash>.pdb`

Using `dumpbin` to examine the `<name>-<hash>.dll.lib` shows it references `<name>-<hash>.dll` and not `<name>.dll`. Therefore I think this `.lib` file cannot simply be lifted into `target` and have it work with `<name>.dll` that is already in there.

The `cargo` and `rustc` versions in use are:
- `cargo-0.17.0-nightly (f9e5481 2017-03-03)`
- `rustc 1.16.0 (30cf806ef 2017-03-10)`

**Comment by cpralea** [comment]
@retep998 I agree this most likely is related to cargo so I opened https://github.com/rust-lang/cargo/issues/3934. Closing this one.
