### ISSUE TITLE
Fuschia builds are going to block beta backports

### ISSUE THREAD

**Issue by aidanhs** [rust-lang/rust#41396]
In https://github.com/rust-lang/rust/pull/41365 we saw a travis failure because a URL was not a valid gz - https://travis-ci.org/rust-lang/rust/jobs/223417092#L991.

https://fuchsia.googlesource.com/third_party/llvm/+archive/5463083.tar.gz seems dead.

While the docker image is reused from the cache we can get by, but this is probably going to start blocking the queue shortly (I'm not currently clear what caused the linked PR to do the rebuild).

ping @tedsta @raphlinus

**Comment by aidanhs** [comment]
Ah, looks like it's because this was a PR to beta. So #41130 needs backporting as well (or the url needs restoring) or beta backports are going to be blocked, ping @petrhosek

**Comment by petrhosek** [comment]
Would it be possible to backport #41130?

**Comment by aidanhs** [comment]
Yeah that's what we're going to try in #41397

**Comment by frewsxcv** [comment]
Presumably resolved in https://github.com/rust-lang/rust/issues/41397
