### ISSUE TITLE
Add rustfmt support for attribute on struct literal field

### ISSUE THREAD

**Issue by joshlf** [rust-lang/rust#41392]
`rustfmt` is currently unable to format code which uses the new (and unstable) [attributes on struct fields](https://github.com/rust-lang/rust/pull/38814) feature. Demonstration:

```text
$ echo '
> struct Foo {
>     foo: usize,
>     #[cfg(feature = "include-bar")]
>     bar: usize,
> }
> 
> fn new_foo() -> Foo {
>     Foo { 
>         foo: 0,
>         #[cfg(feature = "include-bar")]
>         bar: 0,
>     }
> }
> ' | rustfmt
error: expected identifier, found `#`
  --> stdin:14:9
   |
14 |         #[cfg(feature = "include-bar")]
   |         ^
```

Interestingly, [the same code](https://is.gd/AJVWLD) on the Rust playground is simply formatted to remove the `#[cfg(feature = "include-bar")]` annotation, producing:

```
struct Foo {
    foo: usize,
    #[cfg(feature = "include-bar")]
    bar: usize,
}

fn new_foo() -> Foo {
    Foo { foo: 0, bar: 0 }
}
```

**Comment by sfackler** [comment]
This should probably be filed on https://github.com/rust-lang-nursery/rustfmt.

**Comment by steveklabnik** [comment]
yes, please file it over there, thanks!
