### ISSUE TITLE
incr.comp.: Crate Metadata not corresponding to a DefId is untracked.

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#41417]
**Mentoring update:** Mentoring instructions [can be found here](https://github.com/rust-lang/rust/issues/41417#issuecomment-296681763)

----

There are many things in crate metadata that are not covered by dependency tracking (basically everything below [this line](https://github.com/rust-lang/rust/blob/1bb1530239c801bb46b705eb2874ac4e5b213e54/src/librustc/middle/cstore.rs#L213)). Those are things that are unlikely to change in an upstream crate, which is why this has not caused problems yet, but we'll not want to rely on that.

The best way to solve this is probably to create separate "input" DepNodes for these.

cc @nikomatsakis

**Comment by nikomatsakis** [comment]
Yes, I want to refactor how this stuff is handled. Ultimately, I think that metadata should just be a bunch of (key, value) pairs where the `key` is some query, and there should be no more "crate store" trait (except for the "connect providers" method).

However, it occurs to me that once we get the red-green system, we *could* just have a single "metadata" node corresponding to the entire crate, and then let the red/green caching remember what the values of specific metadata queries were.

**Comment by nikomatsakis** [comment]
After some discussion on IRC, @michaelwoerister and I were thinking that the best *immediate* way  to make progress here is going to involve converting all `CrateStore` methods into queries. The main sticking point will be resolve, which we will leave 'as is' for now.

To that end, here is a checklist of `CrateStore` methods. Let's see if we can convert them all to queries. I've checked some off that probably don't make sense at this juncture.

- [ ] `fn describe_def(&self, def: DefId) -> Option<Def>;`
- [ ] `fn def_span(&self, sess: &Session, def: DefId) -> Span;`
- [ ] `fn stability(&self, def: DefId) -> Option<attr::Stability>;`
- [ ] `fn deprecation(&self, def: DefId) -> Option<attr::Deprecation>;`
- [ ] `fn visibility(&self, def: DefId) -> ty::Visibility;`
- [ ] `fn visible_parent_map<'a>(&'a self) -> ::std::cell::Ref<'a, DefIdMap<DefId>>;`
- [ ] `fn item_generics_cloned(&self, def: DefId) -> ty::Generics;`
- [ ] `fn item_attrs(&self, def_id: DefId) -> Vec<ast::Attribute>;`
- [ ] `fn fn_arg_names(&self, did: DefId) -> Vec<ast::Name>;`
- [ ] `fn implementations_of_trait(&self, filter: Option<DefId>) -> Vec<DefId>;`
- [ ] `fn impl_polarity(&self, def: DefId) -> hir::ImplPolarity;`
- [ ] `fn impl_parent(&self, impl_def_id: DefId) -> Option<DefId>;`
- [ ] `fn trait_of_item(&self, def_id: DefId) -> Option<DefId>;`
- [ ] `fn associated_item_cloned(&self, def: DefId) -> ty::AssociatedItem;`
- [ ] `fn is_const_fn(&self, did: DefId) -> bool;`
- [ ] `fn is_default_impl(&self, impl_did: DefId) -> bool;`
- [ ] `fn is_foreign_item(&self, did: DefId) -> bool;`
- [ ] `fn is_dllimport_foreign_item(&self, def: DefId) -> bool;`
- [ ] `fn is_statically_included_foreign_item(&self, def_id: DefId) -> bool;`
- [ ] `fn is_exported_symbol(&self, def_id: DefId) -> bool;`
- [ ] `fn dylib_dependency_formats(&self, cnum: CrateNum) -> Vec<(CrateNum, LinkagePreference)>;`
- [ ] `fn dep_kind(&self, cnum: CrateNum) -> DepKind;`
- [ ] `fn export_macros(&self, cnum: CrateNum);`
- [ ] `fn lang_items(&self, cnum: CrateNum) -> Vec<(DefIndex, usize)>;`
- [ ] `fn missing_lang_items(&self, cnum: CrateNum) -> Vec<lang_items::LangItem>;`
- [ ] `fn is_staged_api(&self, cnum: CrateNum) -> bool;`
- [ ] `fn is_allocator(&self, cnum: CrateNum) -> bool;`
- [ ] `fn is_panic_runtime(&self, cnum: CrateNum) -> bool;`
- [ ] `fn is_compiler_builtins(&self, cnum: CrateNum) -> bool;`
- [ ] `fn is_sanitizer_runtime(&self, cnum: CrateNum) -> bool;`
- [ ] `fn panic_strategy(&self, cnum: CrateNum) -> PanicStrategy;`
- [ ] `fn extern_crate(&self, cnum: CrateNum) -> Option<ExternCrate>;`
- [ ] `fn crate_name(&self, cnum: CrateNum) -> Symbol;`
- [ ] `fn original_crate_name(&self, cnum: CrateNum) -> Symbol;`
- [ ] `fn crate_hash(&self, cnum: CrateNum) -> Svh;`
- [ ] `fn crate_disambiguator(&self, cnum: CrateNum) -> Symbol;`
- [ ] `fn plugin_registrar_fn(&self, cnum: CrateNum) -> Option<DefId>;`
- [ ] `fn derive_registrar_fn(&self, cnum: CrateNum) -> Option<DefId>;`
- [ ] `fn native_libraries(&self, cnum: CrateNum) -> Vec<NativeLibrary>;`
- [ ] `fn exported_symbols(&self, cnum: CrateNum) -> Vec<DefId>;`
- [ ] `fn is_no_builtins(&self, cnum: CrateNum) -> bool;`
- [ ] `fn retrace_path(&self, cnum: CrateNum, path_data: &[DisambiguatedDefPathData]) -> Option<DefId>;`
- [ ] `fn def_key(&self, def: DefId) -> DefKey;`
- [ ] `fn def_path(&self, def: DefId) -> hir_map::DefPath;`
- [ ] `fn def_path_hash(&self, def: DefId) -> u64;`
- [ ] `fn struct_field_names(&self, def: DefId) -> Vec<ast::Name>;`
- [ ] `fn item_children(&self, did: DefId) -> Vec<def::Export>;`
- [ ] `fn load_macro(&self, did: DefId, sess: &Session) -> LoadedMacro;`
- [ ] `fn maybe_get_item_body<'a, 'tcx>(&self, tcx: TyCtxt<'a, 'tcx, 'tcx>, def: DefId) -> Option<&'tcx hir::Body>;`
- [ ] `fn item_body_nested_bodies(&self, def: DefId) -> BTreeMap<hir::BodyId, hir::Body>;`
- [ ] `fn const_is_rvalue_promotable_to_static(&self, def: DefId) -> bool;`
- [ ] `fn is_item_mir_available(&self, def: DefId) -> bool;`
- [ ] `fn crates(&self) -> Vec<CrateNum>;`
- [ ] `fn used_libraries(&self) -> Vec<NativeLibrary>;`
- [ ] `fn used_link_args(&self) -> Vec<String>;`
- [ ] `fn metadata_filename(&self) -> &str;`
- [ ] `fn metadata_section_name(&self, target: &Target) -> &str;`
- [ ] `fn used_crates(&self, prefer: LinkagePreference) -> Vec<(CrateNum, LibSource)>;`
- [ ] `fn used_crate_source(&self, cnum: CrateNum) -> CrateSource;`
- [ ] `fn extern_mod_stmt_cnum(&self, emod_id: ast::NodeId) -> Option<CrateNum>;`
- [ ] `fn encode_metadata<'a, 'tcx>(&self, tcx: TyCtxt<'a, 'tcx, 'tcx>, link_meta: &LinkMeta, reachable: &NodeSet) -> EncodedMetadata;`
- [ ] `fn metadata_encoding_version(&self) -> &[u8];`

**Comment by nikomatsakis** [comment]
cc @cramertj @aochagavia -- you interested in tackling some of these? In some cases, queries actually exist already, and we just have to convert code to use them exclusively (e.g., `is_foreign_item`)

**Comment by nikomatsakis** [comment]
**Mentoring instructions:** The current step in resolving this is to move methods from the `CrateStore` trait and convert them into queries. The `CrateStore` trait serves as the "abstract interface" to the metadata -- it is defined in `librustc`, but implemented in `librustc_metadata` (exactly once, though there exists a second, dummy impl). 

The idea then for a PR is to:

- pick a method in the list
- find uses of it:
    - if it is used in resolve, you can skip it for now and move on to another
- otherwise:
    - add a query to [the `src/librustc/ty/maps.rs` file](https://github.com/rust-lang/rust/blob/d3476f4b7694b8453cf52268880057a9df938089/src/librustc/ty/maps.rs) for this method
    - convert the method into [a crate metadata provider](https://github.com/rust-lang/rust/blob/d3476f4b7694b8453cf52268880057a9df938089/src/librustc/ty/maps.rs#L381)
    - convert all calls to the method to use the query (typically by doing `ty::queries::QUERY::get(tcx, DUMMY_SP, def_id)`

**Comment by achernyak** [comment]
I would love to get started on this. I will try to have an implementation for one of the items up in a couple days to align on direction.

**Comment by cramertj** [comment]
Yeah, I can take a look at some of these tonight or tomorrow.

**Comment by achernyak** [comment]
@cramertj I was planning on taking a look at the couple of the first ones today or tomorrow morning if you want to start a little further down the list. 

Wouldn't want us stepping on each other's toes 😄

**Comment by cramertj** [comment]
@achernyak Sounds great! Thanks.

**Comment by nikomatsakis** [comment]
@cramertj @achernyak great! =)

**Comment by michaelwoerister** [comment]
> However, it occurs to me that once we get the red-green system, we could just have a single "metadata" node corresponding to the entire crate, and then let the red/green caching remember what the values of specific metadata queries were.

One downside of this approach, that came up during discussion, is that this would mean that we would have to load and deserialize each value just to find out if it has changed or not. Currently we directly load fingerprints to do this check.

**Comment by arielb1** [comment]
> One downside of this approach, that came up during discussion, is that this would mean that we would have to load and deserialize each value just to find out if it has changed or not. Currently we directly load fingerprints to do this check.

Can't we save fingerprints in the parent crate metadata and copy the expected fingerprints into the child crate IC-info?

**Comment by nikomatsakis** [comment]
@arielb1 

> Can't we save fingerprints in the parent crate metadata and copy the expected fingerprints into the child crate IC-info?

Yes, we could presumably special-case this code somewhat, though I think that -- for this to really work well -- we would want to align the metadata and queries so that they have a 1:1 relationship (refactoring the `CrateStore` methods away gets us closer to this vision). That said, I've been wondering if we will ever want more stability in our metadata format, in which case tying it directly to the current set of queries may or may not be wise. Probably not worth worrying about right now.

**Comment by cramertj** [comment]
Sorry for the delay on my end here-- trying to go through my new employer's official OSS patch submitting process...

**Comment by cramertj** [comment]
Many of these methods don't take `DefId` as an argument, but the `provide` macro at the top of `src/librustc_metadata/cstore_impl.rs` assumes that they do-- should I change the macro to allow specifying the input type, or is there another way you think I should provide those methods?

**Comment by nikomatsakis** [comment]
@cramertj good point. I'd prefer to change the macro, but I'm not sure how easy that would be to do. I guess you can leverage the `Key` trait (not public, but it could be -- and in fact on one of my upcoming branches I made it public) in the `maps` crate to extract the krate number from any kind of legal key.

**Comment by achernyak** [comment]
@cramertj in the short term, I think most of these can be handled but using a tuple like `const_eval_dep_node` does, or by pulling the needed information off the `TyCtxt` itself. For example, for `def_span` the `Session` is available on `TyCtxt` and that's actually how it was passed in `&tcx.sess`.

Also `CrateNumber`, which is the other major one, is supported by the query already i.e. `typecheck_item_body` takes a `CrateNumber` already.

**Comment by achernyak** [comment]
`fn visibility(&self, def: DefId) -> ty::Visibility;` is used in resolve. In case you want to mark it to keep track.

**Comment by achernyak** [comment]
@nikomatsakis I was just looking at `visible_parent_map` and has a fairly substantial implementation inside the `cstore::CStore`. Moving that into a provider would require modifying the `CrateStore` trait to expose new methods. Is this something we want to take on as part of this PR?

**Comment by nikomatsakis** [comment]
@achernyak 

> I was just looking at visible_parent_map and has a fairly substantial implementation inside the cstore::CStore. Moving that into a provider would require modifying the CrateStore trait to expose new methods. Is this something we want to take on as part of this PR?

wowsers, that *is* complex. And it even returns a `Ref`. Yeah, I don't really think we want to put that into a query just "as is". I wonder if we can break it down somehow.

**Comment by cramertj** [comment]
@nikomatsakis If you get a chance, can you update the checklist above? I'm not entirely sure which sections have been finished since we've both been working on it and there are a couple of PRs open rn. If you'd like, I'd be happy to post the list of all the ones I think we've done so we can double-check.

**Comment by cramertj** [comment]
It would also be useful to mark off or otherwise indicate which ones were skipped because they're used in `librustc_resolve`.

**Comment by cramertj** [comment]
Used in `librustc_resolve`:
-`visibility`
-`associated_item_cloned`
-`dep_kind`
-`export_macros`
-`crate_name`
-`struct_field_names`
-`item_children`
-`load_macro`
-`extern_mod_stmt_cnum`

**Comment by nikomatsakis** [comment]
@cramertj will do! I'll do a sweep with what I can find, and you can compare.

**Comment by nikomatsakis** [comment]
Updated -- I tagged with all the PRs.

**Comment by cramertj** [comment]
@nikomatsakis Great, thanks! It looks like almost all the rest are ones I put off because they don't have a single `DefId` argument. I'll plan to have a PR out tonight updating the `provide` macro to allow for other arguments.

**Comment by achernyak** [comment]
@cramertj from looking into this a bit. It looks like the windows error in your other pr was thrown by the implementation for `is_dllimport_foreign_item`. Have you tried removing that and seeing if everything else works?

**Comment by nikomatsakis** [comment]
@achernyak 

> I think the last of this issue is blocked by #41780

that's a closed PR? Is that what you meant to link to?

**Comment by achernyak** [comment]
@nikomatsakis, that PR was closed due to a windows build issue in #41766 which was taking too long to resolved. I believe @cramertj closed both of these to not keep the PRs open for an extended period of time.

**Comment by cramertj** [comment]
Finally getting back to this-- I'm opening a PR with a few new ones. I also looked at `lang_items` and `missing_lang_items`. I discovered those are currently  calculated before `tcx` is made and then stored in a field. They're accessed all over the place, so that'll require a large-scale refactor. I'm not sure how often the list of lang items changes, but if we want incremental results to be valid across lang-item-list changes, the lang-item list will need to be broken up similar to what @nikomatsakis did for the region maps (https://github.com/rust-lang/rust/pull/41662).

**Comment by michaelwoerister** [comment]
@cramertj Anything that is wrapped in a [Tracked<T>](https://github.com/rust-lang/rust/blob/e7fffa2211f3145e444c2d90321a0e39d6150b42/src/librustc_metadata/schema.rs#L191) (like [lang_items](https://github.com/rust-lang/rust/blob/e7fffa2211f3145e444c2d90321a0e39d6150b42/src/librustc_metadata/schema.rs#L251)) you don't need to worry about. Those things can only be accessed when specifying a `DepNode` (or at least one has to explicitly work around tracking if it's really necessary).

**Comment by cramertj** [comment]
@michaelwoerister Oh, good to know. We should check those ones off on the list, then. I'll put together a list of them later today.

**Comment by michaelwoerister** [comment]
@cramertj Excellent, thank you!

**Comment by cramertj** [comment]
Out of the list above, I see these included as `Tracked`:
- `lang_items`
- `missing_lang_items`
- `native_libraries`
- `implementations_of_trait` above is backed by the [`get_implementations_for_trait`](https://github.com/rust-lang/rust/blob/3f8b93693da78c2cfe1d7f1dc6834c5ba61e0cc0/src/librustc_metadata/decoder.rs#L946) method on cdata, which appears to just be a filter on top of `CrateRoot.impls`, which is `Tracked<LazySeq<TraitImpls>>`. I'm not sure whether or not to count this-- I guess it depends on whether or not we want to directly track the filtered result of `get_implementations_for_trait` separately from the overall list of trait impls. I'd expect we probably would want to. If that's the case, it should _not_ be checked off until this has been done.
- `exported symbols`
- `dllimport_foreign_items` is `Tracked`, but like `implementations_of_trait` I'd expect we probably still want to track `is_dllimport_foreign_item` (which should be unchecked, BTW, as the linked PR for it was closed, not merged).
- `panic_strategy`
- `dylib_dependency_formats`

**Comment by cramertj** [comment]
`item_generics_cloned` should also be checked off -- it's used in `librustc/middle/resolve_lifetime.rs`, and only has access to a `Session`.

**Comment by kennytm** [comment]
Could the list in https://github.com/rust-lang/rust/issues/41417#issuecomment-296678068 be updated? #41766 was closed, and some are done in later PRs. Specifically,

* [x] `is_const_fn` is done in #42598
* [x] `is_default_impl` is done in #41917
* [ ] `is_dllimport_foreign_item` [*should be unchecked*](https://github.com/rust-lang/rust/issues/41417#issuecomment-308487161).

Also,

* [x] `impl_polarity` is done in #41469
* [ ] `impl_defaultness` is missing
* [x] `is_staged_api` has been deleted in #41847
* [x] `is_allocator` is done in #42598
* [x] `is_panic_runtime` is done in #42598
* [ ] `is_profiler_runtime` is missing
* [x] `extern_crate` is done in #42598
* [x] `retrace_path` has been deleted in #43361
* [ ] `maybe_get_item_body` is renamed to `item_body` in #41408
* [x] `metadata_filename` has been deleted in #41565, replaced by `metadata_loader`.
* [x] `metadata_section_name` has been deleted in #41565, replaced by `metadata_loader`.
* [ ] `metadata_loader` is missing
