### ISSUE TITLE
Support use Trait::method and/or Type::method?

### ISSUE THREAD

**Issue by Rufflewind** [rust-lang/rust#41453]
Currently Rust doesn’t support any of the following:

```rust
// Example A
use Default::default;
use f64::sin;
```

This means one can never write `default()` or `sin(3.14)` without qualification as individual methods can never be imported in isolation.  The workaround is to have a prelude-like module where you write wrappers for such static methods as free functions:

```rust
// Example B
pub fn default<T: Default>() -> T { T::default() }
pub fn sin(x: f64) -> f64 { f64::sin(x) }
```

This is a lot of boilerplate.  Perhaps it would useful to make Example A “just work”?

For static methods, the intent is pretty clear: it would enable

    static_method(arg1, arg2, …)

This would be just a shorthand for calling `Trait::static_method`.  It won’t work if `Self` is ambiguous.

For non-static methods, it’s not obvious what `use Trait::method` would do.  Which among these would it enable?  (Either or both?)

    method(obj, arg1, arg2, …)
    obj.method(arg1, arg2, …)

**Comment by abonander** [comment]
For what it's worth, `sin()`, `cos()` and `tan()` are all inherent methods, so you can do `3.14f64.sin()`.

**Comment by petrochenkov** [comment]
This is more an RFC material rather than a rust-lang/rust issue.

Adding `use Trait::AssocItem;` should be simple, it mostly needs motivation and decision.
`use Type::AssocItem;` is not possible with current organization of compilation stages.

**Comment by Rufflewind** [comment]
@petrochenkov Oops my bad.  I thought this was the rfcs repository.  Should I move the issue over there?

**Comment by Rufflewind** [comment]
Moved to: https://github.com/rust-lang/rfcs/issues/1995
