### ISSUE TITLE
Order of parameters matter when processing an unsigned value?

### ISSUE THREAD

**Issue by lfiolhais** [rust-lang/rust#41468]
I'm not sure if this is intended behavior. I searched for similar issues but couldn't find any, sorry if this is duplicate.

When processing an expression that is going to be stored in an unsigned type where intermediary results overflow but the final result doesn't causes the program to panic. For example:
```rust
fn main() {
    let var: usize = 1 - 0 - 2 + 1;
    println!("My var: {:#?}", var);
}
```
The compiler issues four warnings:
```
warning: attempt to subtract with overflow, #[warn(const_err)] on by default
 --> src/main.rs:2:22
  |
2 |     let var: usize = 1 - 0 - 2 + 1;
  |                      ^^^^^^^^^

warning: attempt to subtract with overflow, #[warn(const_err)] on by default
 --> src/main.rs:2:22
  |
2 |     let var: usize = 1 - 0 - 2 + 1;
  |                      ^^^^^^^^^

warning: this expression will panic at run-time
 --> src/main.rs:2:22
  |
2 |     let var: usize = 1 - 0 - 2 + 1;
  |                      ^^^^^^^^^ attempt to subtract with overflow

warning: this expression will panic at run-time
 --> src/main.rs:2:22
  |
2 |     let var: usize = 1 - 0 - 2 + 1;
  |                      ^^^^^^^^^^^^^ attempt to add with overflow

```
Then the program panics on runtime with `attempt to subtract with overflow` and this backtrace:
```
thread 'main' panicked at 'attempt to subtract with overflow', src/main.rs:2
stack backtrace:
   1:        0x10421ddbc - std::sys::imp::backtrace::tracing::imp::write::h21ca2762819c7ae8
   2:        0x10421f29e - std::panicking::default_hook::{{closure}}::h38f99a37d00bb19b
   3:        0x10421ef40 - std::panicking::default_hook::ha2186ee24b50729c
   4:        0x10421f697 - std::panicking::rust_panic_with_hook::h979db19ee91d2a53
   5:        0x10421f544 - std::panicking::begin_panic::h6a69f5b54391c64d
   6:        0x10421f462 - std::panicking::begin_panic_fmt::h9de2343580b3c2c4
   7:        0x10421f3c7 - rust_begin_unwind
   8:        0x1042414f0 - core::panicking::panic_fmt::haa2997386017a96f
   9:        0x1042413f4 - core::panicking::panic::h2349bf4700260ab6
  10:        0x1042177fe - bug_test::main::h2f392d20ef902ff9
  11:        0x1042210ba - __rust_maybe_catch_panic
  12:        0x10421f916 - std::rt::lang_start::hfc9882558f9403bf
  13:        0x104217839 - main
```

However, the following programs won't panic or issue any warnings:
```rust
fn main() {
    let var: usize = 1 - 0 - (2 - 1);
    println!("My var: {:#?}", var);
}
```
and
```rust
fn main() {
    let var: usize = 1 + 1 - 0 - 2;
    println!("My var: {:#?}", var);
}
```

I managed to reproduce this on stable, beta and the latest nightly (1785bca51 2017-04-21). I'm confused because all of these representations are equivalent mathematically. The result is always zero.
What is even weirder to me is that the order of the operands matter, is this the case (I didn't look at the code)? Furthermore, putting part of the expression in parentheses negates the issue.

If this is intended behavior could you please explain why?

## Meta
* Stable
```
rustc 1.16.0 (30cf806ef 2017-03-10)
binary: rustc
commit-hash: 30cf806ef8881c41821fbd43e5cf3699c5290c16
commit-date: 2017-03-10
host: x86_64-apple-darwin
release: 1.16.0
LLVM version: 3.9
```

This is my first Rust issue so if anything is missing or poorly explained I apologize in advance. 😄

**Comment by sfackler** [comment]
`+` and `-` are left associative - without parentheses it's equivalent to `(((1 - 0) - 2) +1)` which underflows in the second calculation. That behavior is maintained even when constant folding that down to 0.

**Comment by lfiolhais** [comment]
Good to know! That is not the behavior that I would expect, though. Closing as it is working as intended.
