### ISSUE TITLE
librustc should not depend on librustc_llvm

### ISSUE THREAD

**Issue by whitequark** [rust-lang/rust#41473]
I'm adding something to librustc_llvm and changing it rebuilds a lot of rustc libraries. @eddyb said this should not be the case.

**Comment by eddyb** [comment]
Indeed, only `librustc_trans` actually *needs* LLVM, in fact I'd really love to combine the two, since LLVM is only used for the one backend, even if it happens to be our only official one.

**Comment by whitequark** [comment]
Wouldn't that degrade compile times on rebuild?

**Comment by eddyb** [comment]
Does `librustc_llvm` actually take a long time to build? Or is linking LLVM super slow?

**Comment by whitequark** [comment]
I think it's nontrivial, and statically linking LLVM (I dynamically link, personally) can take a *lot* of time with the default set of targets (I recall linking it for straight *minutes*).

**Comment by eddyb** [comment]
@whitequark Yeah we can still separate that out I think, but move anything that's not imports into what is currently `librustc_trans` - if we can have the crate empty (just link), even better.

**Comment by arielb1** [comment]
Currently, `librustc_metadata` depends on LLVM for its archive reader, so we'll first have to split that out.

**Comment by eddyb** [comment]
@arielb1 Yeah I think we want to split it so the backend provides file -> metadata blob functionality, and `librustc_metadata` handles both finding the files and decoding the blob.

**Comment by arielb1** [comment]
@eddyb 

Yeah. That would also be the Right Thing for targets with "unconventional linking".

**Comment by rkruppe** [comment]
This impacts me a lot, as essentially all my rustc work for the next few weeks or more consists of modifying LLVM, occasionally librustc_llvm, and rarely librustc_trans. So I'd volunteer to fix it. I could use some details on what this "file -> metadata blob" API should look like, though. Please elaborate here or ping me on IRC.

**Comment by nagisa** [comment]
@rkruppe maybe something like this?

```
// in metadata
trait MetadataStore {
    fn get_metadata(&self) -> Result<MetadataBlob, String>;
    ...
}

// in trans or somewhere else
impl MetadataStore for LlvmMetadataStore { ... }

// in driver
session.metadata_store_impl: Box<MetadataStore> = Box::new(LlvmMetadataStore);  // or something like that
```
