### ISSUE TITLE
Use `diff` crate while evaluating `compile-fail` tests

### ISSUE THREAD

**Issue by cengizIO** [rust-lang/rust#41474]
Hello,

Currently we're using some internal functionality for comparing `compile-fail` results.

We should be using [diff](https://crates.io/crates/diff) instead.

Thanks @nikomatsakis for suggesting this. 

I'm working on this now.

**Comment by nikomatsakis** [comment]
👍

**Comment by cengizIO** [comment]
Previously, we were dumping the differences between expected and actual compile-fail output like this

```
  0 - |E0282: type annotations needed|
    + |E0282: testing testing testing|
```

Now, it's something like this.

```
-E0282: type annotations needed
+E0282: testing testing testing
```
So, output-wise, no breaking/confusing changes introduced by this implementation change.
