### ISSUE TITLE
Tracking issue for 'more_io_inner_methods'

### ISSUE THREAD

**Issue by SergioBenitez** [rust-lang/rust#41519]
Feature was added in #41463, resolving #29067.

This feature enables several internal accessor methods on structures in `std::io` including `Take::{get_ref, get_mut}` and `Chain::{into_inner, get_ref, get_mut}`.

cc @alexcrichton

**Comment by SergioBenitez** [comment]
I'd like to propose that this be stabilized for 1.20. The added methods are rather uncontroversial: they simply expose the same type of behavior already exposed by other structures. As such, stabilizing these has little to no drawback. @brson, @alexcrichton

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

**Comment by dtolnay** [comment]
@rfcbot reviewed

**Comment by SergioBenitez** [comment]
Stabilization PR is incoming.
