### ISSUE TITLE
Unexpected inference error

### ISSUE THREAD

**Issue by TheJare** [rust-lang/rust#41521]
An error in the source code causes the correct compile error, but rustc then emits an additional compile error in unrelated, completely correct code.

I tried this code:

fn main() {
    for xx in 0..11 { print!("{}", xx as f64) };
    kk = 666 // Error here triggers inference error in previous line
}

I expected to see this happen:

    error[E0425]: cannot find value `kk` in this scope
     --> <anon>:3:5
      |
    3 |     kk = 666
      |     ^^ did you mean `Ok`?

But in addition, this happened too:

    error: non-scalar cast: `{integer}` as `f64`
     --> <anon>:2:36
      |
    2 |     for xx in 0..11 { print!("{}", xx as f64) };
      |                                    ^^^^^^^^^

If the line containing the legitimate error is removed, the unrelated code compiles correctly as expected, and the additional, incorrect error will no longer show up.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/35772.
