### ISSUE TITLE
crates.io responded with 500 instead of 200 when downloading crate

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#41545]
Possibly just network failure (#40474), but we did get some response, so presumably not that.

First instance here: https://github.com/rust-lang/rust/pull/41332#issuecomment-297195502.

Log from that:

```
error: unable to get packages from source
Caused by:
  failed to get 200 response from `https://crates.io/api/v1/crates/utf8-ranges/0.1.3/download`, got 500
thread 'main' panicked at 'tests failed for https://github.com/BurntSushi/xsv', src\tools\cargotest\main.rs:78
note: Run with `RUST_BACKTRACE=1` for a backtrace.
command did not execute successfully: "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage0-tools\\x86_64-pc-windows-msvc\\release\\cargotest.exe" "C:\\projects\\rust\\build\\x86_64-pc-windows-msvc\\stage0/bin\\cargo.exe" "C:\\projects\\rust\\build\\ct"
expected success, got: exit code: 101
```

**Comment by alexcrichton** [comment]
Ah yeah I've been lumping these in with #40474, there's been a few others of these from time to time.

**Comment by carols10cents** [comment]
FWIW I just tried to search in crates.io's logs for utf8-ranges/0.1.3 with status 500 and I didn't see anything... wonder if that was from S3....?

**Comment by alexcrichton** [comment]
@carols10cents oh I was investigating this a long time ago and ended up reaching the same conclusion, that the 500 code was from S3. I think that's a normal ocurrance.

The "solution" here is to likely bake in an auto-retry into Cargo itself when it gets a 500 from S3 which is even [officially recommended](http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html)

**Comment by carols10cents** [comment]
It looks like cargo [has network retry logic](https://github.com/rust-lang/cargo/pull/2396) but it's only being used for git sources? I'm going to file an issue for using that logic for other sources as well

**Comment by alexcrichton** [comment]
Oh Cargo has [retry logic](https://github.com/rust-lang/cargo/blob/fa7584c1495c2d9c04a6416f8e7b546abfa88a52/src/cargo/sources/registry/remote.rs#L161-L171) for the registry, it just only retries if the [error claims its spurious](https://github.com/rust-lang/cargo/blob/fa7584c1495c2d9c04a6416f8e7b546abfa88a52/src/cargo/util/network.rs#L24) and a 500 isn't a [`curl::Error`](https://github.com/rust-lang/cargo/blob/fa7584c1495c2d9c04a6416f8e7b546abfa88a52/src/cargo/util/errors.rs#L337-L345) but rather is checked [just below](https://github.com/rust-lang/cargo/blob/fa7584c1495c2d9c04a6416f8e7b546abfa88a52/src/cargo/sources/registry/remote.rs#L173-L175).

I think we'd just need to tweak the retry logic here.

**Comment by carols10cents** [comment]
oooooohhhh. Yeah was just coming to the conclusion that with_retry IS being used for all sources. Will change what bug I'm filing to be about tweaking the retry logic :)

**Comment by carols10cents** [comment]
Issue filed! https://github.com/rust-lang/cargo/issues/3962

**Comment by Mark-Simulacrum** [comment]
In theory this was solved upstream, and either way, closing in favor of #42118.
