### ISSUE TITLE
Rewrite make-win-dist.py in Rust

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#41568]
We've got a now-ancient [Python script](https://github.com/rust-lang/rust/blob/036983201d4e9aeb5c5e56e47c305971972b2569/src/etc/make-win-dist.py) in the repository which has historically served the purpose of assembling the components of the rust-mingw package that we produce. Historically this was invoked from `make`, and implementing that script in `make` would be a nightmare!

Nowadays we've got rustbuild, a build system in Rust, so let's keep leveraging it! This script is called from [one location](https://github.com/rust-lang/rust/blob/036983201d4e9aeb5c5e56e47c305971972b2569/src/bootstrap/dist.rs#L114-L125) and should be relatively easy rewrite it directly inline. The Rust standard library should have all the tools needed to implement this script.

I'm tagging this as E-easy and E-mentor, please reach out to me if you'd like to take this on and need assistance!

**Comment by wesleywiser** [comment]
I'd like to take this, if that's ok.

**Comment by alexcrichton** [comment]
@wesleywiser sure thing! Let me know if you need any assistance

**Comment by wesleywiser** [comment]
@alexcrichton How should I test my change? I tried running `./x.py dist src\librustc` but it fails with:

```
thread 'main' panicked at '

couldn't find required command: "gcc.exe"

', src\bootstrap\sanity.rs:62

```

and I'm not sure how to install `gcc.exe` on Windows.

**Comment by retep998** [comment]
@wesleywiser You'd follow the instructions in the readme to install msys2 and use that to acquire MinGW.

https://github.com/rust-lang/rust/blob/master/README.md#mingw

**Comment by alexcrichton** [comment]
@wesleywiser my recommendation would probably be to just run it directly in the sense that I'd run the old script and then the new script. If the outputs are the same then we should be good to go!

**Comment by F001** [comment]
@alexcrichton , Are there other scripts need to be rewritten? I am glad to contribute too.

**Comment by alexcrichton** [comment]
@F001 if you're *super ambitious* there's also `src/etc/platform-intrinsics/generator.py`. That's a relatively complicated script and generates the `src/librustc_platform_intrinsics` crate, although with Cargo and build scripts now we could generate that all at build time instead of checking in generated sources. 

If you're interested in tackling that one I could make a tracking issue separately to follow that if you'd like!

**Comment by F001** [comment]
@alexcrichton ,  it sounds great! I'm excited to tackle this one.

**Comment by alexcrichton** [comment]
@F001 awesome! I've [opened an issue](https://github.com/rust-lang/rust/issues/41885) to help track that script.
