### ISSUE TITLE
Rewrite the rust-installer submodule in Rust

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#41569]
The [rust-installer repository](https://github.com/rust-lang/rust-installer) has long served the purpose of generating manifests and installers for all of our standard artifacts. Over time though it's unfortunately really showing its age as it's become more and more difficult to maintain over time. With rustbuild nowadays let's take this opportunity to rewrite it into Rust!

This transition would most likely look like:

* Add a new tool, `src/tools/installer`
* Add appropriate crates.io dependencies to `src/tools/installer/Cargo.toml`
* Reimplement the installer in Rust, including various commands and scripts.
* Replace all calls in [`dist.rs`](https://github.com/rust-lang/rust/blob/036983201d4e9aeb5c5e56e47c305971972b2569/src/bootstrap/dist.rs) to `rust-installer/*.sh` to calls into this new project. For an example of invoking a tool written in Rust, you can see how we [call `cargotest`](https://github.com/rust-lang/rust/blob/036983201d4e9aeb5c5e56e47c305971972b2569/src/bootstrap/check.rs#L88-L93)

This'd be a great opportunity for anyone looking to get their feet wet with Rust's distribution infrastructure and build system! It's also a relatively meaty project to boot :)

**Comment by cuviper** [comment]
I understand writing the package generators in Rust, but how can you do that for the installer itself?  Doesn't that need to be platform-neutral?
(but then, I don't know how Windows deals with `install.sh` even today...)

**Comment by alexcrichton** [comment]
Oh sorry right I should clarify! I definitely do *not* think we should rewrite `install.sh`. I'm just thinking the `gen-installer.sh` and `combine-installers.sh` scripts could be rewritten. Those are just used in tarball generation. The tarballs themselves should not change as a result of this issue.

**Comment by cuviper** [comment]
Great, makes sense.  I'd like to work on this, if you don't already have someone else...

**Comment by alexcrichton** [comment]
Nah you're definitely more than welcome!

**Comment by Diggsey** [comment]
@cuviper the "installer" logic is technically ported to rust already, it's built into rustup (`install.sh` is not used for rustup installs, which is also why you can install rust on windows!)

**Comment by cuviper** [comment]
Ah, thanks!

**Comment by cuviper** [comment]
Here's my work in progress: https://github.com/cuviper/rust-installer/tree/oxidize

One script down (`gen-installer.sh`), three to go...

**Comment by cuviper** [comment]
OK, I think that branch is ready to start reviewing.

@alexcrichton I did this as an in-place port, but re-reading your original description, it sounds like you envisioned something entirely new.  Well, from here we can take this whatever direction you want.  Do you think this should still be used as a rust-installer submodule, or a new crate pulled into rust's own repo?

Either way, we should be able to get rustbuild using this as a library, doing everything in-process.  I haven't started on that yet, but the `rust-installer/*.sh` scripts are now shims to the new crate binary, so we can probably try dropping this right in place.

**Comment by Mark-Simulacrum** [comment]
It's probably easiest to review if you put up the code as a PR. Could you do that?

**Comment by cuviper** [comment]
OK, see rust-lang/rust-installer#62.
