### ISSUE TITLE
Rewrite save-analysis from scratch and/or hook RLS more directly.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#41562]
Every single time `librustc_save_analysis` makes what would be an easy change in the compiler a *massive* time sink I'm reminded that it *was never designed* to do anything it's being used for right now, even if it may work well enough for DXR.

I'm creating this issue to assign it to all the places where I have to work around its impedance mismatch, not only with the Rust compiler, *but with the semantics of the language itself*.

Also, *getting the design right* could benefit rustdoc too, so we could stop running in circles.

**Comment by alexcrichton** [comment]
cc @nrc

**Comment by eddyb** [comment]
The irony, of course, is that I was trying to remove some baseline cost that isn't that visible outside of tools like `cargo check` and RLS, when ran often (even each keypress) while editing.
