### ISSUE TITLE
SliceExt::binary_search has a different signature than slice::binary_search

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#41561]
`SliceExt` parameterizes `Self::Item` over `Borrow`, but slices don't have that parameterization. This makes the core slice API different from the std slice API, which is not supposed to be the case.

[PR where this change was made](https://github.com/rust-lang/rust/pull/37761).

**Comment by alexcrichton** [comment]
This was attempted to get generalized in libstd in https://github.com/rust-lang/rust/pull/41590, but unfortunately it caused too much breakage so the libs team has decided to not land that PR. An alternate route to fixing this though would be to *de-generalize* the signature in libcore. This is of course a breaking change but we may be lucky and have few users of this function in libcore, so we may be able to get away with it. The libs team would be interested in seeing a PR to de-generalize in libcore (make it the same as libstd's signature) and then have a crater run to evaluate the impact. From that point we can evaluate what to do next.

**Comment by alexcrichton** [comment]
cc https://github.com/rust-lang/rust/issues/32632
