### ISSUE TITLE
Rust never lets you know about RUST_BACKTRACE=full

### ISSUE THREAD

**Issue by CryZe** [rust-lang/rust#41584]
Ever since RUST_BACKTRACE got split up into a short and full backtrace, there used to be a message that tells you about the full backtrace when you are seeing the shortened one. The message however only comes up when stack frames are omitted [See here](https://github.com/rust-lang/rust/blob/9f2abadca2d065bf81772cb84981d0a22d8e98b3/src/libstd/sys_common/backtrace.rs#L74). This used to be the case for the shortened backtrace, but since the frame pruning logic got reverted by #41364, this message is now dead code until frame pruning is implemented again (#40264). However it might also make sense to just always show this message for a short backtrace instead of counting the amount of omitted frames.

**Comment by petrochenkov** [comment]
If no frames are omitted, then full and short backtraces are equivalent.
No reason to spend people's time and recommend using `full` if the result will be the same.

**Comment by CryZe** [comment]
The short backtrace hides other information like the addresses and the function hashes though.

**Comment by CryZe** [comment]
Looks like it's intentional, so I'm closing this.
