### ISSUE TITLE
Linker error due to undefined rust_begin_unwind when creating an importlib on Windows

### ISSUE THREAD

**Issue by urschrei** [rust-lang/rust#41609]
I'm generating an importlib using latest stable on Appveyor using [`-C target-cpu=native -C link-args=-Wl,--out-implib,polylabel.a`](https://ci.appveyor.com/project/urschrei/polylabel-rs/build/1.0.90/job/b5a9e56duawvtxks#L60), but switching from dylib to cdylib now causes a linker error, saying there's an undefined reference to `rust_begin_unwind`. The [crate](https://github.com/urschrei/polylabel-rs) *isn't* `#![no_main]` \ `#![no_std]`, and I'm not doing anything unusual AFAIK.

**Comment by Mark-Simulacrum** [comment]
I believe this is #18807 based on discussion in #38281, so closing in favor of #18807. See https://github.com/rust-lang/rust/issues/38281#issuecomment-298190854.
