### ISSUE TITLE
Compile problem with rust 1.17.0

### ISSUE THREAD

**Issue by beingalink** [rust-lang/rust#41610]
This is a folluw up to [this issue](https://github.com/nabijaczleweli/cargo-update/issues/27).

I was trying to cargo install `cargo-update` but it errors out when compiling `serde_derive`:
```
   Compiling serde_derive v0.9.15
error: proc-macro derive panicked
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/cargo-update-0.8.1/src/ops/config.rs:43:73
   |
43 | #[derive(Debug, Clone, Hash, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
   |                                                                         ^^^^^^^^^^^
   |
   = help: message: proc_macro::__internal::with_parse_sess() called before set_parse_sess()!

error: failed to compile `cargo-update v0.8.1`, intermediate artifacts can be found at `/var/folders/5m/qk85bf793gzdmrgxpd2qrl4m0000gn/T/cargo-install.f94WA1eo7V4Z`
```
I'm on macOS 10.12.4 and Rust 1.17.0 installed with homebrew.

**Comment by dtolnay** [comment]
This is #39870. The homebrew packaging for Rust is screwed up. Uninstall it with homebrew and reinstall it with https://rustup.rs/ to fix this.

**Comment by beingalink** [comment]
Installing with rustup fixed it. Thank you!

**Comment by ilovezfs** [comment]
This should no longer be a problem in Homebrew due to https://github.com/Homebrew/homebrew-core/pull/14490.
