### ISSUE TITLE
Reference and Nomicon don't mention that dereferencing an unaligned pointer is UB

### ISSUE THREAD

**Issue by jimblandy** [rust-lang/rust#41633]
The Nomicon and the Reference don't say that dereferencing a misaligned pointer is undefined behavior, but I certainly would expect it to be. Checked with @gankro on IRC and he agreed.

To verify, I compiled the following:
```
extern {
    fn f() -> *const i32;
}

fn main() {
    println!("{}", unsafe { *f() + 1 });
}
```

This produces LLVM IR containing the following code for the call:

```
  %3 = tail call i32* @f()
  %4 = load i32, i32* %3, align 4
  %5 = add i32 %4, 1
```

The `align 4` in the `load` instruction indicates that LLVM should assume that the pointer is aligned on a four-byte boundary. The LLVM IR docs for `load` say, "Overestimating the alignment results in undefined behavior."

**Comment by steveklabnik** [comment]
We now have https://github.com/rust-lang-nursery/reference and https://github.com/rust-lang-nursery/nomicon, would you mind filing this at both of them please? Sorry about that!

(I guess duplication is the proper thing here, but this is now the wrong repo for sure)
