### ISSUE TITLE
`rustc --version` displays incorrect version

### ISSUE THREAD

**Issue by lorenzoi** [rust-lang/rust#41635]
When you write `rustc --version` in your terminal you should receive `rustc 1.18.0-nightly (128aa262e 2017-04-28)`

Just me pointing things out...

**Comment by durka** [comment]
What's the issue here?

**Comment by est31** [comment]
The bump of the nightly compiler version doesn't happen immediately when the new stable gets released, but in a separate PR for the bump to 1.19 its #41544.

**Comment by steveklabnik** [comment]
Yes, there's some delay here, but https://github.com/rust-lang/rust/pull/41544 should fix it.

Thank you @lorenzoi !
