### ISSUE TITLE
ARM installation

### ISSUE THREAD

**Issue by andrewufrank** [rust-lang/rust#41645]
the automatic installation on an ARM computer (actually Odroid XU4 running debian jessie with xfce) lacks three files: 
    apt-get install llvm gcc build-essentials
the error message was ' could not exec the linker cc' and `linking with cc`.
could this be automated or at least an error message generated?
now hello world and cargo works.

**Comment by Mark-Simulacrum** [comment]
Filed https://github.com/rust-lang-nursery/rustup.rs/issues/1175 to track this, closing this in favor of that. Thanks!
