### ISSUE TITLE
Provide a guide to standard traits in the documentation

### ISSUE THREAD

**Issue by HadrienG2** [rust-lang/rust#41671]
When learning Rust, it can be difficult to get acquainted with the standard Rust traits, as their documentation is scattered in many places.

Some are introduced gradually over the course of the Book, some are reviewed in more details in the Nomicon, some are discussed in the Reference, and most are just scattered around the std crates (std::ops, std::marker and many others) with a description that ranges from fine (e.g. Clone) to minimalistic (e.g. bitwise operations).

This makes it difficult for Rust newcomers to properly implement new types in libraries, as picking which traits they should implement can be a challenge. Even experts seem to get it wrong, as well-respected libraries like num_complex and nalgebra can be missing common traits like MulAssign or Sum.

I think it would be nice to have, somewhere in the standard Rust documentation, a centralized glossary of standard Rust traits which provides a short description of each of them and links to more extensive documentation whenever necessary (e.g. to the Nomicon for Send/Sync).

A very good starting point would be https://llogiq.github.io/2015/07/30/traits.html . Here is what I would do before integration in the standard documentation:

- Get the author's permission to reuse the original text: no need to reinvent the wheel :)
- Add a lexicographically ordered index at the top or in a sidebar.
- Decide how much detail we want to put in there, versus how much we want to link to more detailed references like the llogiq blog post.
- Clarify that "Rem" may not work like C/++ developers would expect.
- Add documentation of the XyzAssign traits, Product/Sum, and any other trait we can find in the std reference which is not covered there already.
- Maybe add or link to a more extensive discussion of Rust iterators when discussion the various Iterator traits.

Is there anything else that comes to someone's mind?

**Comment by leoschwarz** [comment]
It might be better to move the issue to https://github.com/rust-lang/book/issues . Essentially appendix "B - Operators" in the second edition of the book already seems to be covering a bit of what you mentioned.

**Comment by HadrienG2** [comment]
@leoschwarz : Sorry for the slow reply. @GuillaumeGomez initially suggested that I post this here, but I can be convinced to move/link this issue in the book bugtracker if you think that's where such documentation should be located.

Another possible place which I was thinking about is the Reference, which also already has some quick discussion of standard traits, e.g. when discussing operatros... I guess that's some of the feedback which I would be looking for here: where would you put such a trait glossary?

**Comment by steveklabnik** [comment]
Marking this as p-low; it's unclear where this should go, it's unclear who can do this work. It'd be nice to have, but not sure when we're gonna get around to it.

**Comment by steveklabnik** [comment]
Triage: over a year later, it's still not clear what we should do here, if anything. As such I'm going to give this a close; if anyone feels like they have a plan here, please get in touch and we can talk about it. Thanks!
