### ISSUE TITLE
Suggest `!` for bitwise negation when encountering a `~`

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#41679]
Here's a program:
```rust
fn main() {
    let x = ~1;
}
```
Its output:
```
error: expected expression, found `~`
 --> <anon>:2:13
  |
2 |     let x = ~1;
  |             ^

error: aborting due to previous error
```
Given that this is our only deviation from C-style bitwise operator syntax, it would be nice to have a note of some kind to suggest `!` here.

Ideally the note would only appear when the `~` looks like it's being applied as a unary operator on a numeric type, but if that would require too much machinery then something simpler will suffice.

**Comment by bstrie** [comment]
And no, I'm not concerned about potential confusion with the ancient owned pointer syntax. :P

**Comment by estebank** [comment]
If anyone wants to tackle this, you'll need to modify [`libsyntax/parse/parser.rs`](https://github.com/rust-lang/rust/blob/de4bdd20f87d95d164c883dc141a2763e4df155a/src/libsyntax/parse/parser.rs#L2738).

**Comment by bstrie** [comment]
@F001 Worth asking on #rust-internals on irc.mozilla.org, or internals.rust-lang.org if you'd prefer something other than IRC.
