### ISSUE TITLE
Borrow issue inside a for loop

### ISSUE THREAD

**Issue by krishnakumar4a4** [rust-lang/rust#41675]
I am trying to push a string into a vector. The string is obtained from splitting each entry of a vector.
While compiling, shows the borrow is ouliving the scope of for loop.
```rust
fn to_flame_graph(callReturnVec: &mut Vec<String>,ReturnVec: Vec<String>){
	//let mut CallString;
	println!("printing to flamegraph");
	let mut flameStackVec = Vec::new();
	let mut RefCounterVec = Vec::new();
	for i in ReturnVec.iter(){
		flameStackVec.push(i);
		for j in flameStackVec.iter(){
			print!("{:?};", j);
		}
		print!("\n");
	}
	let ReturnVeclength = flameStackVec.len();
	let callReturnVeclength = callReturnVec.len();
	println!("callReturnVeclength: {:?}", callReturnVeclength);
	for i in 0..callReturnVeclength{
		let mut CallReturnMapVectorTokens = callReturnVec[callReturnVeclength-1-i].split(';');
		println!("calltoken {:?}", CallReturnMapVectorTokens.nth(0));
		//Getting the call tuple string
		let CallMapVector: Vec<&str> = CallReturnMapVectorTokens.nth(0).unwrap().split(',').collect();
		//Getting the return tuple string
		let ReturnMapVector: Vec<&str> = CallReturnMapVectorTokens.nth(1).unwrap().split(',').collect();
		let StartTime = CallMapVector[1].parse::<u32>();
		let EndTime = ReturnMapVector[1].parse::<u32>();
		let TimeDiff;
		//Time difference between call and its return
		TimeDiff = EndTime.unwrap() - StartTime.unwrap();
		println!("call start {},returns {}", CallMapVector[1],ReturnMapVector[1]);
		println!("Time difference {:?}", TimeDiff);


		let CallString;
		CallString = CallReturnMapVectorTokens.nth(0).unwrap().to_string().clone();
		println!("{:?}", CallString);
		flameStackVec.push(&CallString);


		RefCounterVec.push(TimeDiff);
		for i in flameStackVec.iter(){
			print!("{:?}", i);
		}
		println!("");
	}
}
```

Here is the error while compiling:
```rust
error: `CallString` does not live long enough
   --> src/main.rs:176:2
    |
167 |                 flameStackVec.push(&CallString);
    |                                ---------- borrow occurs here
...
176 |         }
    |    ^ `CallString` dropped here while still borrowed
177 | }
    | -       borrowed value needs to live until here

error: aborting due to previous error
```

I am not able to workaround this problem, can someone help me? What am I missing?

**Comment by whoisj** [comment]
I'm not a Rust expert, but it seems to me you do the following:

1. Allocate a collection to borrow reference (`flameStackVec`)
2. Iterate a collection in a loop, and with in each iteration:
    1. Take an item
    2. Break it's contents up in to borrowed, local-scope variables
    3. Push the borrowed, scoped reference into a collection defined in the outer scope.

This seems invalid as the borrowed references likely will not outlive the innerscope - the compiler is helping you here. Seems to me that you need to align the lifetimes of the inner and outer scope variables to make this work - and that I have no idea how to do. As I said, I am no Rust expert.

**Comment by krishnakumar4a4** [comment]
In that case, the top for loop runs great without complaining when I say push. Why do you think it is only giving problem with the second loop.
If you say borrowed references are causing this problem, how should I actually push a string into the outer scope variable flameStackVec without violating this borrow. I have tried using clone before push, but it didn't help.
Just curious, How can someone solve problem like this, is there good documentation available? I am actually a newbie to rust.

**Comment by whoisj** [comment]
Seems to me that the compiler is complaining that the outer loop's collection has a greater lifetime than the elements you're pushing into it from the inner loop. Is there a way to inform the compile the elements from the inner loop have a lifetime that matches the outer loop?

Hrm... [docs](https://doc.rust-lang.org/book/lifetimes.html)!

**Comment by Thinkofname** [comment]
https://is.gd/bEBDSM

This line `CallString = CallReturnMapVectorTokens.nth(0).unwrap().to_string().clone();` in your original was allocating a new `String` which only lived during the for loop. Removing the allocation and changing the vector to storing `&str` instead of `&String` solves this

**Comment by bluss** [comment]
Closing since the question has been resolved. http://stackoverflow.com/questions/tagged/rust or http://users.rust-lang.org/ are good places to discuss issues like this, for future reference.
