### ISSUE TITLE
impl LowerHex, UpperHex for `&[u8]`

### ISSUE THREAD

**Issue by luser** [rust-lang/rust#41674]
I've found myself writing some version of `bytes_to_hex` [more](https://github.com/luser/rust-minidump/blob/e420ae4700bacd2505e8ece2955cc2adb291fd77/src/minidump.rs#L256) [than](https://github.com/luser/read-process-memory/blob/42e163c2fb5ea940dadc7619f261781b7b148ed9/examples/read-process-bytes.rs#L7) once, and it looks like I'm not the only one:
https://github.com/search?l=Rust&q=bytes_to_hex&type=Code&utf8=%E2%9C%93

I think a nice addition would be to impl `LowerHex` and `UpperHex` for `&[u8]`, so that you could simply do `format!("{:x}", bytes)`.

**Comment by ollie27** [comment]
Dupe of #33127, rust-lang/rfcs#1916.

**Comment by luser** [comment]
Thanks, should have looked harder!
