### ISSUE TITLE
The document of process exit code in `std::process::exit()` is wrong

### ISSUE THREAD

**Issue by mzji** [rust-lang/rust#41682]
The document said:
```
/// Due to [platform-specific behavior], the exit code for this example will be
/// `0` on Linux, but `256` on Windows:
///
/// ```no_run
/// use std::process;
///
/// process::exit(0x0f00);
/// ```
```
However from the text above, line `process::exit(0x0f00);` should be changed to `process::exit(0x0100);` . On Windows, all 32 bits of the exit code is available. See [the document of `ExitProcess()`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682658(v=vs.85).aspx) for more details. (The parameter of `ExitProcess()` is a `UINT`, which maps to a C `unsigned int` on Windows platforms, which usually is a 32-bit unsigned integer today. The 32-bit 0x0f00 is 3840, not 256.)

**Comment by retep998** [comment]
@frewsxcv Since you wrote that example in https://github.com/rust-lang/rust/pull/38397, care to explain why you wrote it like that? 😛

**Comment by frewsxcv** [comment]
woops, that's just a typo. Feel free to submit a pull request, or I can later

**Comment by frewsxcv** [comment]
opened a pr: https://github.com/rust-lang/rust/pull/41688
