### ISSUE TITLE
tokei 6.0.0 won't compile on nightly

### ISSUE THREAD

**Issue by mzji** [rust-lang/rust#41685]
OS: Win10 Home x64 version 1607 / build 10.0.14393, Build Tools for Visual Studio 2017
rustc metadata:
```
C:\>rustc -vV
rustc 1.19.0-nightly (06fb4d256 2017-04-30)
binary: rustc
commit-hash: 06fb4d25642a3f223db1441972dd5962085cfba1
commit-date: 2017-04-30
host: x86_64-pc-windows-msvc
release: 1.19.0-nightly
LLVM version: 4.0
```
Error messages during installing tokei via cargo:
```
(unreleated lines removed)
   Compiling tokei v6.0.0
LLVM ERROR: No open Win64 EH frame function!
error: failed to compile `tokei v6.0.0`, intermediate artifacts can be found at `C:\Users\USERNAME\AppData\Local\Temp\cargo-install.APq02cIhSEk9`

Caused by:
  Could not compile `tokei`.

To learn more, run the command again with --verbose.
```

**Comment by TimNN** [comment]
Potentially related to #41630.

Looks like https://bugs.llvm.org/show_bug.cgi?id=32335, in which case this should be fixed by https://github.com/llvm-mirror/llvm/commit/3993050daa60a8d5265c64800157c64585495fcc.

I see if backporting that patch fixes the issue.

**Comment by brson** [comment]
Needs verification after llvm backport lands.

**Comment by TimNN** [comment]
@mzji: Can you try again with the latest nightly? That should fix the issue.

**Comment by mzji** [comment]
@TimNN Ok, I'm testing now
