### ISSUE TITLE
Regression in -Z dump-mir=all

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#41697]
running `rustc -Z dump-mir=all src/test/run-pass/issue-33387.rs`

yields

```
error[E0391]: unsupported cyclic reference between types/traits detected
  --> ../rust/src/test/run-pass/issue-33387.rs:19:1
   |
19 | / impl Foo for [u8; 2] {
20 | |     fn get(&self) -> [u8; 2] {
21 | |         *self
22 | |     }
23 | | }
   | |_^ cyclic reference
   |
note: the cycle begins when processing `<impl at ../rust/src/test/run-pass/issue-33387.rs:19:1: 23:2>`...
  --> ../rust/src/test/run-pass/issue-33387.rs:19:1
   |
19 | / impl Foo for [u8; 2] {
20 | |     fn get(&self) -> [u8; 2] {
21 | |         *self
22 | |     }
23 | | }
   | |_^
note: ...which then requires const-evaluating `<impl at ../rust/src/test/run-pass/issue-33387.rs:19:1: 23:2>::{{initializer}}`...
  --> ../rust/src/test/run-pass/issue-33387.rs:19:19
   |
19 | impl Foo for [u8; 2] {
   |                   ^
note: ...which then requires processing `<impl at ../rust/src/test/run-pass/issue-33387.rs:19:1: 23:2>::{{initializer}}`...
  --> ../rust/src/test/run-pass/issue-33387.rs:19:19
   |
19 | impl Foo for [u8; 2] {
   |                   ^
note: ...which then requires processing `<impl at ../rust/src/test/run-pass/issue-33387.rs:19:1: 23:2>::{{initializer}}`...
  --> ../rust/src/test/run-pass/issue-33387.rs:19:19
   |
19 | impl Foo for [u8; 2] {
   |                   ^
note: ...which then requires processing `<impl at ../rust/src/test/run-pass/issue-33387.rs:19:1: 23:2>`...
  --> ../rust/src/test/run-pass/issue-33387.rs:19:1
   |
19 | / impl Foo for [u8; 2] {
20 | |     fn get(&self) -> [u8; 2] {
21 | |         *self
22 | |     }
23 | | }
   | |_^
   = note: ...which then again requires processing `<impl at ../rust/src/test/run-pass/issue-33387.rs:19:1: 23:2>`, completing the cycle.
```

Happening on `rustc 1.19.0-nightly (777ee2079 2017-05-01)`. Did not happen on the latest nightly available through rustup on 27.04.2017.

**Comment by est31** [comment]
Last working nightly: `rustc 1.18.0-nightly (94e884b63 2017-04-27)`
First broken nightly: `rustc 1.18.0-nightly (128aa262e 2017-04-28)`
[list of commits in between](https://github.com/rust-lang/rust/compare/94e884b6307a59f1e6e64aa7ebc1996b651a7629...128aa262e8fe445f5c4d5c1f15dd28a2007c0234).

**Comment by est31** [comment]
maybe it was #41368 ? cc @nikomatsakis

**Comment by nikomatsakis** [comment]
could be. let me try it on my big MIR refactoring branch =)

**Comment by dwrensha** [comment]
I confirm that the error occurs at https://github.com/rust-lang/rust/commit/128aa262e8fe445f5c4d5c1f15dd28a2007c0234 but not at https://github.com/rust-lang/rust/commit/ad1461efb92ae85ce8227f52ca79149e368529d1. So it looks to me #41368 is indeed the culprit.

**Comment by nikomatsakis** [comment]
Yes. I can reproduce. Will investigate.

**Comment by nikomatsakis** [comment]
I see the problem. PR coming soon.

**Comment by nikomatsakis** [comment]
Fix at #41777

**Comment by dwrensha** [comment]
I'm still seeing this issue, on the latest nightly and on master.

**Comment by nikomatsakis** [comment]
@dwrensha can you give more details of how you are reproducing the problem? (I added a test for the precise scenario reported, so I'm reasonably sure it's not that case anymore.)

**Comment by dwrensha** [comment]
```
$ rustc --version
rustc 1.19.0-nightly (978d2cfee 2017-05-10)
$ rustc -Z dump-mir=all src/test/run-pass/issue-33387.rs
error[E0391]: unsupported cyclic reference between types/traits detected
[...]
```

**Comment by nikomatsakis** [comment]
Hmm, perhaps my regression test wasn't sufficient. I see I used `-Zdump-mir=NEVER_MATCHED`; I remember that the test did fail, but I guess that it passing doesn't prove all issues are resolved. =)

**Comment by dwrensha** [comment]
The earliest commit where I can reproduce this problem is https://github.com/rust-lang/rust/commit/2cca2567d9a39f159e392c47c8be6d94087242c9.
