### ISSUE TITLE
Be consistent about whether the span label duplicates info in an error message

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#41695]
Often an error message has two parts - the heading and a label on a span. E.g.,

```
error[E0425]: cannot find value `labe` in this scope
   --> src/actions/compiler_message_parsing.rs:116:30
    |
116 |             message.push_str(labe);
    |                              ^^^^ did you mean `label`?
```

Here the heading is `cannot find value `labe` in this scope` and the label on the span is `did you mean `label`?` In this case the two contain different information.

However, in some cases, the info is duplicated, e.g.,

```
error[E0061]: this function takes 1 parameter but 0 parameters were supplied
   --> src/actions/compiler_message_parsing.rs:116:21
    |
116 |             message.push_str();
    |                     ^^^^^^^^ expected 1 parameter
```

This is a problem for IDEs because all errors are on spans and we must choose to either show both pieces of text (which looks weird and redundant in the second example) or just the heading (which elides information in the first example).

Alternatively, we could add some flag to the JSON error structure to indicate whether a label is redundant or not.

cc @jonathandturner

**Comment by Mark-Simulacrum** [comment]
Nominating for compiler discussion (though perhaps this is a dev tools question?). We should decide on this sooner rather than later, since new diagnostics or updates to past ones should take it
 into account.

**Comment by nikomatsakis** [comment]
Yeah, this is a tricky one. I think I've come to prefer that the main error message be somewhat generic, without a lot of specific detail, and that we give the specific detail in labels. But that's a mildly separate question I guess.

**Comment by nikomatsakis** [comment]
To clarify what I meant, the message that @nrc gave might be:

```
error[E0061]: wrong number of parameters supplied
   --> src/actions/compiler_message_parsing.rs:116:21
    |
116 |             message.push_str();
    |                     ^^^^^^^^ expected 1 parameter, found 0 parameters
```

Here the "error" part is fairly generic, and the details are in the body.

**Comment by nikomatsakis** [comment]
cc @rust-lang/dev-tools @rust-lang/docs -- thoughts?

**Comment by nagisa** [comment]
We cannot get rid of the proper error messages, because we also have the different “non-pretty” error output styles which have to present all the relevant information.

The solution from the implementation standpoint would be having “structured” errors. As in, each error would be a proper structure describing the error, rather than a collection of strings; the presentation layer then would figure out how to present each of the errors properly itself.

**Comment by oli-obk** [comment]
We could go half way to structured errors by only making this case explicit in the diagnostics structures and api

**Comment by estebank** [comment]
I believe both the message and main label should contain relevant information. The message should be readable and understandable enough when rustc is displaying the one line output, while the label should short, be understandable on its own and useful for third party tools. IDEs should be able to rely on the labels to be enough to represent the error. The only caveat would be suggestions (which are already separated in the json output), and span labels that _should_ be suggestions but haven't been changed yet.

**Comment by nikomatsakis** [comment]
I think a key question is whether the span-labels should be completely understandable *without* the main message.

@estebank I think it would be helpful to give some examples that follow (and some that do not follow) your proposed guidelines.

**Comment by estebank** [comment]
I have a few things that I've been working towards.

No primary span without label:

```
error: expected expression, found `}`
  --> $DIR/issue-10636-2.rs:18:1
   |
LL | }
   | ^ expected expression
```

vs

```
error: expected expression, found `}`
  --> $DIR/issue-10636-2.rs:18:1
   |
LL | }
   | ^
```

This was pervasive throughout the parser errors. There should be few cases left. The reasoning behind this is that we have been (perhaps unwittingly) users to look at the span label instead of the error message (I know that this is the case for me, my eyes are attracted by the colorful underlines and labels).

To avoid repetition between the message and the label, we don't show information that is contained in the span (the found token in the example, the ADT name in others).

The message should make sense on its own:

```
$DIR/issue-10636-2.rs:18:1 - error: expected expression, found `}`
```

The label should also make sense on its own so that IDEs can rely on it for presentation. The rationale is that we have already made the effort to write the label in a meaningful way when presented embedded in the code.

Also, it is already the case that error message is not enough to understand the error, so you need to read the label and/or notes:

```
error[E0308]: mismatched types
  --> $DIR/numeric-cast.rs:29:18
   |
LL |     foo::<usize>(x_u64);
   |                  ^^^^^ expected usize, found u64
```

There _are_ cases where the primary label is only a suggestion or there's no primary label:

```
error[E0689]: can't call method `powi` on ambiguous numeric type `{float}`
  --> $DIR/method-on-ambiguous-numeric-type.rs:12:17
   |
LL |     let x = 2.0.powi(2);
   |                 ^^^^
help: you must specify a concrete type for this numeric value, like `f32`
   |
LL |     let x = 2.0_f32.powi(2);
   |             ^^^^^^^
```

```
error[E0594]: cannot assign to captured outer variable in an `FnMut` closure
  --> $DIR/closure-immutable-outer-variable.rs:19:26
   |
LL |     let y = true;
   |         - help: consider making `y` mutable: `mut y`
LL |     foo(Box::new(move || y = false) as Box<_>);
   |                          ^^^^^^^^^
```

```
error: const items should never be #[no_mangle]
  --> $DIR/issue-45562.rs:11:14
   |
LL | #[no_mangle] pub const RAH: usize = 5;
   |              ---------^^^^^^^^^^^^^^^^
   |              |
   |              help: try a static value: `pub static`
   |
   = note: #[deny(no_mangle_const_items)] on by default
```

but we should revamp these to include a relevant label:

```
error[E0689]: can't call method `powi` on ambiguous numeric type `{float}`
  --> $DIR/method-on-ambiguous-numeric-type.rs:12:17
   |
LL |     let x = 2.0.powi(2);
   |                 ^^^^ can't call this on ambiguous numeric type `{float}`
help: you must specify a concrete type for this numeric value, like `f32`
   |
LL |     let x = 2.0_f32.powi(2);
   |             ^^^^^^^
```

```
error[E0594]: cannot assign to captured outer variable in an `FnMut` closure
  --> $DIR/closure-immutable-outer-variable.rs:19:26
   |
LL |     let y = true;
   |         - help: consider making `y` mutable: `mut y`
LL |     foo(Box::new(move || y = false) as Box<_>);
   |                          ^^^^^^^^^ cannot assign to captured outer variable in an `FnMut` closure
```

```
error: const items should never be `#[no_mangle]`
  --> $DIR/issue-45562.rs:11:14
   |
LL | #[no_mangle] pub const RAH: usize = 5;
   |              ---------^^^^^^^^^^^^^^^^ const items shouldn't be `#[no_mangle]`
   |              |
   |              help: try a static value: `pub static`
   |
   = note: #[deny(no_mangle_const_items)] on by default
```

like we already do for type mismatches:

```
error[E0308]: mismatched types
  --> $DIR/issue-46756-consider-borrowing-cast-or-binexpr.rs:20:42
   |
LL |     light_flows_our_war_of_mocking_words(behold as usize);
   |                                          ^^^^^^^^^^^^^^^
   |                                          |
   |                                          expected &usize, found usize
   |                                          help: consider borrowing here: `&(behold as usize)`
   |
   = note: expected type `&usize`
              found type `usize`
```

**Comment by nikomatsakis** [comment]
@estebank that helps, thanks =)

**Comment by estebank** [comment]
Closing as I believe we're already in a much better state than we were a year ago. Feel free to reopen if you disagree.
