### ISSUE TITLE
Tail Recursion Optimization 

### ISSUE THREAD

**Issue by i-m-v-j** [rust-lang/rust#41694]
Hello, i think memory management and borrowing becomes easy when we use recursion in rustlang. but as i have observed there is very poor support for recursion in rust. that is what making rust for beginner to come and start doing stuff. this is my honest opinion. The solution is if in rust, we provide tail recursion optimization then there will be no need to implement drop trait for those custom data structures, which is again confusing and kinda complex.why i am telling you is lot of my friends leave rust because these issues are killing productivity and at the end of the day people want to be productive. i love rust a lot a lot 
a lot. that is why i am doing all of these to make sure, these kinda end user issues gets solved.

I hope you guys will consider this rookie's request and may be think about it.

**Comment by oli-obk** [comment]
There's a postponed RFC for that: https://github.com/rust-lang/rfcs/issues/271

Feature requests of this magnitude generally belong to the RFC repository ;)

**Comment by i-m-v-j** [comment]
it got opened in 2014. i think this is critical than it sounds. why ? because this is stopping lot of new comers to get into systems programming faster because, new comers won't know to manage this lower level when they are getting into systems programming. i hope you guys will give bit more importance to this problem, because this problem can solve some other problems out of the box.

**Comment by oli-obk** [comment]
@i-m-v-j feel free to open a new RFC. That is the fastest way to get your way! The last RFC was postponed because it wasn't ready for Rust 1.0, but I think a well motivated and detailed RFC has a good chance today, since guaranteed tail recursion could be implemented in MIR

**Comment by rkruppe** [comment]
Note that there *is* a new RFC on (explicit) tail calls: https://github.com/rust-lang/rfcs/pull/1888

**Comment by steveklabnik** [comment]
Hello! As mentioned above, this is not the right place for this discussion. We keep the issue tracker for bugs only. As such, I'm going to give this a close. Please weigh in on that RFC! Thanks.
