### ISSUE TITLE
change `internalize_symbols` to work per-CGU

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#41707]
Right now `internalize_symbols()` walks over all of the generated LLVM IR to decide what is internal. This only happens in non-incremental mode. However, it is a blocker to moving to a pipelined setup, because it requires all of the modules to be in a big array. Ideally, we would refactor things so that we figure out during trans item collection what may be marked internal or not (though in incremental mode we may prefer to mark everything public so as to have more reuse). However, another alternative would be to hack something up so that we disable pipelining when not in incremental mode. 

cc @michaelwoerister

**Comment by michaelwoerister** [comment]
cc #39280

**Comment by michaelwoerister** [comment]
Implemented in https://github.com/rust-lang/rust/pull/43183.
