### ISSUE TITLE
Move attributes from crate source into Cargo.toml where appropriate

### ISSUE THREAD

**Issue by rkruppe** [rust-lang/rust#41701]
The compiler and std crates in-tree have a few attributes in their source code (lib.rs) that are conventionally set in the Cargo.toml file. I'd say this just wasn't cleaned up when rustbuild became the only build system, and should be cleaned up.

Possibly incomplete list of such attributes:

- `#![crate_name]`
- `#![crate_type]`

Note that some crates have different crate types in between Cargo.toml than in lib.rs (e.g., compiler crates seem to have only dylib in Cargo.toml, dylib and rlib in the source code). I'm not sure which one takes precedence, but my build directory seems to contain only dylibs and not rlibs for those crates, so I assume the Cargo.toml wins.

cc @alexcrichton -- is the above correct?

**Comment by neosilky** [comment]
If this is correct, I'd like to take this.

**Comment by alexcrichton** [comment]
Sounds good to me! I think that because Cargo unconditionally passes `--crate-type` and `--crate-name` that all the annotations in the source can just be deleted, they should all already be in as much sync as they need to be.

**Comment by zombiefungus** [comment]
isn't this issue closed now?

**Comment by Mark-Simulacrum** [comment]
Oh, wait, not the pull request is still open.
