### ISSUE TITLE
Allow less than all the generic parameters to be specified

### ISSUE THREAD

**Issue by ubsan** [rust-lang/rust#41718]
```rust
fn foo<T, U>(u: U) -> T
  where T: From<U>
{
  From::from(u)
}

fn main() {
  println!("{}", foo(0u16): u16); // works
  println!("{}", foo::<u16>(0u16)); // doesn't work
  println!("{}", foo::<u16, u16>(0u16)); // works
}
```

I want the middle one to work. There's no real reason for it not to, and it *does* work in C++.

**Comment by abonander** [comment]
Being a language change, this belongs in https://github.com/rust-lang/rfcs.

Otherwise, you can also do this: `foo::<u16, _>(0u16)`

**Comment by leonardo-m** [comment]
Partial type application?

**Comment by retep998** [comment]
What about `println!("{}", foo::<u16, _>(0u16));`?

**Comment by ubsan** [comment]
opened at https://github.com/rust-lang/rfcs/issues/1989
