### ISSUE TITLE
-Zdebug-macros should either be the default or continue to be available on release-channel compiler

### ISSUE THREAD

**Issue by hsivonen** [rust-lang/rust#41743]
Firefox is built with release-channel Rust, and `-Zdebug-macros` is [needed](https://bugzilla.mozilla.org/show_bug.cgi?id=1360497) to get useful debuggability, crash/panic reporting and profiling attributability for Rust code in Firefox.

According to build-time output, [the option is going to go away from the release-channel compiler](https://github.com/rust-lang/rust/issues/31847). It [seems](https://github.com/rust-lang/rust/issues/39153#issuecomment-297919861) that the option isn't on track to becoming the default, either.

If it's not made the default, please continue keeping the option (under some name) available to release-channel Rust.

**Comment by LucasFA** [comment]
As I understand it, #100758 closes this. @rustbot label +F-collapse_debuginfo +A-debuginfo.
