### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'pretty_printers'

### ISSUE THREAD

**Issue by nateozem** [rust-lang/rust#41748]
I'll get the following error when trying to source 'gdb_load_rust_pretty_printers.py' file from within `gdb`

	$ sudo rust-gdb
	GNU gdb (GDB) 7.12.1
	Copyright (C) 2017 Free Software Foundation, Inc.
	License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
	This is free software: you are free to change and redistribute it.
	There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
	and "show warranty" for details.
	This GDB was configured as "x86_64-apple-darwin".
	Type "show configuration" for configuration details.
	For bug reporting instructions, please see:
	<http://www.gnu.org/software/gdb/bugs/>.
	Find the GDB manual and other documentation resources online at:
	<http://www.gnu.org/software/gdb/documentation/>.
	For help, type "help".
	Type "apropos word" to search for commands related to "word".
	Printing of array indexes is on.

	(gdb) source ~/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/etc/gdb_load_rust_pretty_printers.py
	Traceback (most recent call last):
	  File "~/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/etc/gdb_load_rust_pretty_printers.py", line 12, in <module>
		gdb_rust_pretty_printing.register_printers(gdb.current_objfile())
	  File "~/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/etc/gdb_rust_pretty_printing.py", line 90, in register_printers
		objfile.pretty_printers.append(rust_pretty_printer_lookup_function)
	AttributeError: 'NoneType' object has no attribute 'pretty_printers'

	(gdb) 

If I change `gdb_load_rust_pretty_printers.py` file by removing
`current_objfile()`, it'll work. So the new change would look like this:

	import gdb_rust_pretty_printing
	gdb_rust_pretty_printing.register_printers(gdb)

However it was mention that this is not a good idea as this will affect when
debugging various languages.

The only way I know that `current_objfile()` wouldn't return `NoneType` is by
autoloading `gdb_load_rust_pretty_printers.py` for `gdb`. This is done by
placing the file in the same directory as the executable and changing the file
name as `<executable_name>-gdb.py`. so the directory would look like so

	./
	 main.rs
	 main
	 main-gdb.py

By this, `gdb` will autoload `main-gdb.py` for me and I wouldn't have to try to
`source` it.

This is another way to make this easier and intuitive than copying and rename
the python file to get the script working?

**Comment by tromey** [comment]
Normally `rust-gdb` arranges things so that the auto-loading works.

It's relatively normal in these scripts to have the registration function accept `None` to mean `gdb`, though, for situations where one ends up needing to use `source`.  I think that would be a harmless change.

**Comment by tromey** [comment]
I wrote a patch to allow `None` but I was thinking about:

> This is done by placing the file in the same directory as the executable

and wondering whether this is something that `cargo` ought to do for debug builds.

**Comment by tromey** [comment]
I'm closing this.  Using `rust-gdb` is the normal approach here.  I decided not to submit my `None` patch, either, because it it easy enough to run `rust-gdb` in the build tree when working on the pretty-printers themselves.
