### ISSUE TITLE
ERROR_ON_UNDEFINED_SYMBOLS=1 always passed for emcc effectively prevents any dynamic linking

### ISSUE THREAD

**Issue by NikVolf** [rust-lang/rust#41750]
the following rust code is failing to compile using wasm32-unknown-emscripten target

```rust
extern {
  #[link(name="env")]
  fn log_event(id: *const u8);
}

fn main() {
    unsafe { log_event(::std::ptr::null()); }
}
```

with
```
  error: unresolved symbol: log_event
```

correct me if I'm wrong, I might be terrible wrong with this, but `#[link]` without `kind=static` implies dynamic linking, and the above code should not fail to compile?

As for emscripten itself, it has no problem compiling C code like this:
```c
extern void log_event(void* ptr);

int main() {
    log_event(0);
}
```

with `emcc <source above.c> -O3 -s WASM=1 -s SIDE_MODULE=1 -o result.wasm`
producing nice import entry in the result.wasm

```
  (import "env" "_log_event" (func (;0;) (type 0)))
```

So, the question is, is there is any option to have dynamic symbols in the resulting wasm? Or at least override this linker `ERROR_ON_UNDEFINED_SYMBOLS` argument at some point?

source link would be:
https://github.com/rust-lang/rust/blob/ec27aa97b921957711b96e578c7c197ff28553ac/src/librustc_back/target/wasm32_unknown_emscripten.rs#L21

**Comment by pepyakin** [comment]
@NikVolf actually you can override emcc arguments with help of `EMMAKEN_CFLAGS` environment variable. 
(assuming your filename is `main.rs`)
```shell
export EMMAKEN_CFLAGS="-s ERROR_ON_UNDEFINED_SYMBOLS=0" 
rustc --target=wasm32-unknown-emscripten main.rs
```

**Comment by tmarkovski** [comment]
> @NikVolf actually you can override emcc arguments with help of `EMMAKEN_CFLAGS` environment variable. (assuming your filename is `main.rs`)
> 
> ```shell
> export EMMAKEN_CFLAGS="-s ERROR_ON_UNDEFINED_SYMBOLS=0" 
> rustc --target=wasm32-unknown-emscripten main.rs
> ```

Thank you for this, it saved me so much time.
I have previously tried to override this in the `.cargo/config` file by adding

```
rustflags = [
    "-C", "link-args=--no-entry",
    "-C", "link-args=-s",
    "-C", "link-args=ERROR_ON_UNDEFINED_SYMBOLS=0" ]
```

but they ended up being overriden.

**Comment by nedv-eu** [comment]
As far as I know wasm32 targets by default do not support dynamic linking as there is no dynamic linker available on the platform. Ignoring error on undefined symbols may lead to hard to find runtime errors. This is a chapter from emscripten doc about dynamic linking, are you sure you really want to use the experimental dynamic linking?

Dynamic linking

Emscripten’s goal is to generate the fastest and smallest possible code, and for that reason it focuses on generating a single JavaScript file for an entire project. For that reason, dynamic linking should be avoided when possible.

By default, Emscripten .so files are the same as regular .o object files. Dynamic libraries that you specify in the final build stage (when generating JavaScript or HTML) are linked in as static libraries. Emcc ignores commands to dynamically link libraries during the compile stage (i.e., not in the final build stage). This is to ensure that the same dynamic library is not linked multiple times in intermediate build stages, which would result in duplicate symbol errors.

There is experimental support for true dynamic libraries, loaded as runtime, either via dlopen or as a shared library. See that link [https://github.com/emscripten-core/emscripten/wiki/Linking] for the details and limitations.

**Comment by sbc100** [comment]
`-sERROR_ON_UNDEFINED_SYMBOLS=1` should not be needed anymore.  Its on my default when it makes sense to be these days.   I believe it was also recently removed from the rust toolchain so I think this issue can be closes yes.

**Comment by hoodmane** [comment]
The author asserts that there is an incompatibility between `-sSIDE_MODULE` and `-sERROR_ON_UNDEFINED_SYMBOLS` which I think at least hasn't been true recently (though they are kind of contradictory).

**Comment by sbc100** [comment]
Its true that most users don't want `-sERROR_ON_UNDEFINED_SYMBOLS=1` in combination with `-sSIDE_MODULE`.

But emcc will take care of setting the default value of `ERROR_ON_UNDEFINED_SYMBOLS` correctly in both cases.  So simply not specifying this option does the right thing in most cases, which is why I recommended removing this from the default set of rustc options:

https://github.com/emscripten-core/emscripten/blob/f677b2672fa0d3a216068feb0f5ab76192c7d75d/emcc.py#L2101-L2105

**Comment by sbc100** [comment]
Indeed.   But I guess this bug I believe should still be marked as fixed?  (since it is now fixed as HEAD, and no further action is planned/needed).

**Comment by workingjubilee** [comment]
Thank you! This does indeed seem to be fixed, or if there is a problem still, it probably is better covered by another issue, so I am closing this!
