### ISSUE TITLE
Test generated manifests against rustup

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust#41767]
Several times, PRs have changed the format of the manifests in such a way that they can no longer be installed by rustup. This results in the corresponding nightlies being uninstallable, and doesn't give much time to fix it before the next nightly: https://github.com/rust-lang-nursery/rustup.rs/issues/1092#issuecomment-299374487

We should add tests to catch these problems before they occur.

cc @brson @alexcrichton

**Comment by ranma42** [comment]
cc me

**Comment by alexcrichton** [comment]
Seems like a good idea! The best location for this may actually be the final integration point, [rust-central-station](https://github.com/alexcrichton/rust-central-station) as that's where the manifest is actually generated. If someone would like to implement this I can try to help guide you through the steps!

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust-central-station/issues/17
