### ISSUE TITLE
Missing environment variable `TARGET`

### ISSUE THREAD

**Issue by MasonRemaley** [rust-lang/rust#41778]
I'm trying to log the target triple when my application starts up, and according to [the cargo docs](http://doc.crates.io/environment-variables.html#environment-variables-cargo-sets-for-build-scripts) I should be able to get it from an environment variable named `TARGET`. However, this variable does not seem to be set. I'm not sure if this is a rustc bug or a Cargo bug, or if I'm just misunderstanding something.

I tried [this code](https://play.rust-lang.org/?code=fn%20main()%20%7B%0A%20%20%20%20println!(%22%7B%7D%22%2C%20env!(%22TARGET%22))%3B%0A%7D&version=stable&backtrace=0):
```rust
fn main() {
    println!("{}", env!("TARGET"));
}
```

I expected to see this happen: The target triple to be printed to the console.

Instead, this happened: I got a compiler error saying that the environment variable `TARGET` is not set.

## Meta

`rustc --version --verbose`:
```
rustc 1.19.0-nightly (2d4ed8e0c 2017-05-03)
binary: rustc
commit-hash: 2d4ed8e0cbe2c5f3763273a5d8f6b15119473ba7
commit-date: 2017-05-03
host: x86_64-apple-darwin
release: 1.19.0-nightly
LLVM version: 4.0
```

(Also tried on nightly stable and beta versions on [play.rust-lang.org](https://play.rust-lang.org/?code=fn%20main()%20%7B%0A%20%20%20%20println!(%22%7B%7D%22%2C%20env!(%22TARGET%22))%3B%0A%7D&version=stable&backtrace=0))

Compiler Error:
```
rustc 1.17.0 (56124baa9 2017-04-24)
error: environment variable `TARGET` not defined
 --> <anon>:2:20
  |
2 |     println!("{}", env!("TARGET"));
  |                    ^^^^^^^^^^^^^^

error: aborting due to previous error
```

**Comment by jmesmon** [comment]
Those environment variables are for build scripts only.

Also, note that they are set when the build script is executed, not compiled, so one will want to use `std::env::var` or `std::env::var_os` instead of `env!`

**Comment by MasonRemaley** [comment]
Heh it does say that in the section of the docs I linked doesn't it. :) Makes sense, thanks!
