### ISSUE TITLE
No way to not comment a line beginning with a # in rustdoc

### ISSUE THREAD

**Issue by jFransham** [rust-lang/rust#41783]
I have a doctest in my [`shell_parse`](https://github.com/jFransham/shell_parse) crate that includes a shell-style comment at the start of a line, inside a code block. Minimal example:

```rust
/// ```rust
/// let test_string = r#"
/// # Help me
/// "#;
/// ```
```

This causes the hash to be stripped out in `cargo doc` output (which is annoying, because it's part of the example), and causes the parsing to fail and the doctest to fail as a result. Using the same code in a normal test does not fail, and replacing the `#` with `##` causes it to appear in documentation output and the test to succeed. This is the approach I've taken as a workaround, but it's not what I actually want.

**Comment by Mark-Simulacrum** [comment]
This behavior is actually intentional. rustdoc strips out lines that begin with `#` to make it easier to write partial examples (e.g., without showing `fn main` or helper functions that were perhaps shown in examples given before the current one). Does that make sense?

**Comment by jFransham** [comment]
Ok, but there doesn't seem to be a way to _intentionally_ include lines beginning with a single hash, either with `##` or with `\#`, both interpolate that literal string into the output.

**Comment by jFransham** [comment]
That's a great fix, thanks a lot.
