### ISSUE TITLE
Long build times for the crate `gltf`

### ISSUE THREAD

**Issue by MaikKlein** [rust-lang/rust#41782]
I created a simple repository to reproduce this

https://github.com/MaikKlein/buildtimes

Rebuilding this simple example takes 20 seconds on my machine.  My project jumps from 4 to 25 seconds if I use `Gltf::open`. This seems very high, could it be some kind of regression?

I tested it with the current stable and nightly version of rustc. I am on ubuntu 16.04

**Comment by Binero** [comment]
Takes 2:22 minutes on my machine, dependencies not included.

**Comment by MaikKlein** [comment]
I don't think it is a bug with rust anymore. The crate had a generic method `open` inside the big Gltf struct which restricted it from being compiled ahead of time.

Here is the fix if you care

https://github.com/MaikKlein/buildtimes/tree/faster-compiles
