### ISSUE TITLE
Rust 1.18 regression - ieee754-0.2.1, from_bits

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#41793]
```
error: use of unstable library feature 'float_bits_conv': recently added (see issue #40470)
   --> src/lib.rs:417:17
    |
417 |                 Self::from_bits(bits)
    |                 ^^^^^^^^^^^^^^^
...
609 | mk_impl!(f32, u32, i16, u8, u32, 8, 23);
    | ---------------------------------------- in this macro invocation

error: use of unstable library feature 'float_bits_conv': recently added (see issue #40470)
   --> src/lib.rs:417:17
    |
417 |                 Self::from_bits(bits)
    |                 ^^^^^^^^^^^^^^^
...
610 | mk_impl!(f64, u64, i16, u16, u64, 11, 52);
    | ------------------------------------------ in this macro invocation

error: use of unstable library feature 'float_bits_conv': recently added (see issue #40470)
   --> src/lib.rs:431:17
    |
431 |                 Self::from_bits(bits)
    |                 ^^^^^^^^^^^^^^^
...
609 | mk_impl!(f32, u32, i16, u8, u32, 8, 23);
    | ---------------------------------------- in this macro invocation

error: use of unstable library feature 'float_bits_conv': recently added (see issue #40470)
   --> src/lib.rs:431:17
    |
431 |                 Self::from_bits(bits)
    |                 ^^^^^^^^^^^^^^^
...
610 | mk_impl!(f64, u64, i16, u16, u64, 11, 52);
    | ------------------------------------------ in this macro invocation

error: use of unstable library feature 'float_bits_conv': recently added (see issue #40470)
   --> src/lib.rs:458:17
    |
458 |                 Self::from_bits(
    |                 ^^^^^^^^^^^^^^^
...
609 | mk_impl!(f32, u32, i16, u8, u32, 8, 23);
    | ---------------------------------------- in this macro invocation

error: use of unstable library feature 'float_bits_conv': recently added (see issue #40470)
   --> src/lib.rs:458:17
    |
458 |                 Self::from_bits(
    |                 ^^^^^^^^^^^^^^^
...
610 | mk_impl!(f64, u64, i16, u16, u64, 11, 52);
    | ------------------------------------------ in this macro invocation

error: aborting due to 6 previous errors

error: build failed
```

This is due to a new unstable inherent method introduced in https://github.com/rust-lang/rust/pull/39271.

Mentioned already [here](https://github.com/rust-lang/rust/issues/40470#issuecomment-295313690).

cc @est31 @huonw

**Comment by brson** [comment]
Also affects audrey-0.1.0 cc @mitchmindtree

**Comment by est31** [comment]
`lewton` 0.5.1 stops depending on ieee754. audrey afaik only needs the crate due to lewton, so afaik the problem should be resolved for audrey, given a Cargo.lock update.

**Comment by nagisa** [comment]
XIB. We could consider an alternative name.

**Comment by est31** [comment]
Quoting @rkruppe 's comment from the linked thread:

> RFC 1105 laid out that [adding inherent methods is a minor change](https://github.com/rust-lang/rfcs/blob/master/text/1105-api-evolution.md#minor-change-adding-any-inherent-items) so it's up to the team(s) to decide whether we're okay with the practical impact of the change.

When implementing the feature, I was inspired by the name, but didn't think it would cause breakage, instead the ieee754 crate would shadow it. Sorry for that!

I think `from_bits` is the best name for it, but given the breakage its choice causes I'm neutral.

**Comment by brson** [comment]
XIB = "expected interface breakage"

**Comment by nagisa** [comment]
It seems to me like the ideal fix would be expedited stabilisation of the function in question. The behaviour of implementation in the crate is mildly different from the implementation in libstd, but it doesn’t seem to me like that would alter functionality of the crate in a detrimental way.

Of course, if we do that,  we must keep in mind that fixing this by stabilising a somewhat incompatible (albeit better) method is threading a potentially thin line between "silently breaks code" and "seamless upgrade".

**Comment by est31** [comment]
> It seems to me like the ideal fix would be expedited stabilisation of the function in question.

@BurntSushi wanted to review the function before that happens.

**Comment by brson** [comment]
Also affects radix-heap 0.2.0 cc @Noctune

**Comment by alexcrichton** [comment]
Discussed this at libs triage our conclusion was that we're unlikley to back out these methods, but if any crates have difficulty updating we can reconsider!

**Comment by crypto-universe** [comment]
Affects ramp 0.3.3 cc @Aatch

**Comment by nagisa** [comment]
Lets make sure to mention this in the release notes.
