### ISSUE TITLE
CString should implement FromIterator

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#41819]
So one could collect bytes into it.

**Comment by frewsxcv** [comment]
what happens if the last item isn't a null byte?

**Comment by durka** [comment]
@frewsxcv I assume it would add one, just like `CString::new` does.

**Comment by nagisa** [comment]
In fact, I believe that it should mirror the behaviour of `CString::new` and panic if iterator yields any null bytes at all.

**Comment by durka** [comment]
Yeah, `CString::new` returns an error actually, so it kinda sucks if the `FromIterator` impl has to panic. We can't `impl FromIterator for Result<CString, NulError>`, can we?

**Comment by nagisa** [comment]
I wonder. We have a way to collect into `Result<_, _>`. Might conflict with that one.

**Comment by durka** [comment]
Seems to be incoherent, unfortunately.

**Comment by durka** [comment]
Nevermind, if the impl were in `core::iter` it [seems to work](https://is.gd/T0QSJz).

**Comment by durka** [comment]
Thinking about it more, that doesn't seem quite fair to crates. We might want a `TryFromIterator` RFC.

**Comment by dtolnay** [comment]
This is a neat idea but it sounds like there is some more design work involved. I believe an [RFC](https://github.com/rust-lang/rfcs/blob/master/libs_changes.md) would be the best way to follow up.
