### ISSUE TITLE
Compiler panics when generating documentation on full disk

### ISSUE THREAD

**Issue by Kixunil** [rust-lang/rust#41813]
When running cargo doc, rustc panics if disk is full. Not a huge issue, just an invalid call of `.unwrap()` and since the message says it's a bug, I'm filling a report.

Error message (with removed file path):
```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'failed to generate documentation: Error { file: <path removed>", error: Error { repr: Os { code: 28, message: "No space left on device" } } }', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Might be related to #20438 somehow?

```
$ rustc --version
rustc 1.17.0 (56124baa9 2017-04-24)
```

**Comment by ishanjain28** [comment]
This also happened with me today. 
The compiler starts panicing if you try to, Generate Documentation, Run, Compile or run `cargo check`. 

Maybe It should print a clear message and exit instead of panicing like that.

Rust Version: `1.21.0`
