### ISSUE TITLE
[minor] replace libtest/lib.rs:FnBox by std::boxed::FnBox

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/rust#41810]
https://github.com/rust-lang/rust/blob/master/src/libtest/lib.rs#L134-L142

https://doc.rust-lang.org/std/boxed/trait.FnBox.html

I can do it if wanted

**Comment by GuillaumeGomez** [comment]
Then go ahead. :)

**Comment by Yamakaky** [comment]
Waiting for https://github.com/rust-lang/rust/pull/41815 to be merged
