### ISSUE TITLE
src/bootstrap/cc.rs: Support specifying AR in config or via environment variable

### ISSUE THREAD

**Issue by devurandom** [rust-lang/rust#41821]
`src/bootstrap/cc.rs` currently derives `AR` from `CC` via `build_helper.cc2ar()`. However, it would be very helpful if `AR` could be specified in `config.toml`, like `CC` can. Alternatively, it would be desirable to be able to provide the binary name via a environment variable.

**Comment by alexcrichton** [comment]
Makes sense to me! Should be relatively easy to implement, and if anyone's interested in doing so I don't mind helping out!

**Comment by petrochenkov** [comment]
I have a branch on which archiver and linker can be supplied to rustbuild explicitly, will send a PR soon.
