### ISSUE TITLE
std::process::Child should provide a way to ask it to exit gracefully

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#41822]
Currently the only way to terminate children processes early is to use `kill` which is specified to send `SIGKILL`. Sending `SIGKILL` is way overkill and in most cases should not be done. Instead `SIGTERM` should be used.

A method which terminates children processes gracefully should be provided.

**Comment by retep998** [comment]
Would this API be cross platform, and if so, how would it be implemented on Windows?

**Comment by nagisa** [comment]
I’m not sure, but I’m sure Windows’ task manager has both ability to "kill" the process (equivalent of SIGKILL) and "terminate" the process (equivalent of SIGTERM).

**Comment by nagisa** [comment]
Hmm, I might be misremembering something, because I do not see anything similar anymore, but I’m sure there were at least two ways to "terminate" a process in task manager.

**Comment by durka** [comment]
At least there used to be separate "End Task" and "End Process" options. It seems the difference is [closing windows vs terminating the process](https://serverfault.com/a/151788).

**Comment by nagisa** [comment]
So, let me describe the primary difference between SIGKILL and SIGTERM. SIGTERM and SIGKILL by default both terminate the process immediately. The difference between them, however, is that you can register a signal handler for SIGTERM and ignore the signal (or do some cleanup before quitting). You cannot register a signal handler for SIGKILL.

In that sense [`TerminateProcess`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686714(v=vs.85).aspx) sounds a lot like SIGKILL. It seems like [`ExitProcess`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682658(v=vs.85).aspx) is intended to be a less strict version of `TerminateProcess`, but I’m not sure if it is the appropriate function to use.

Maybe check what happens when sigterm is signalled on WSL?

**Comment by retep998** [comment]
The problem with `ExitProcess` is that you cannot invoke it on another process. Sending a `WM_CLOSE` if the application has a window registered, or generating a console ctrl event if it doesn't, is probably the best option for requesting that the application exit.

**Comment by nagisa** [comment]
@retep998 it is still windows kernel that is ultimately running these processes and difference in handling `SIGTERM` and `SIGKILL` *has* to be handled somehow.

**Comment by retep998** [comment]
@nagisa The windows kernel itself does practically nothing. The Windows executive will destroy the process object when asked via `NtTerminateProcess`, but to do a softer request for the process to gracefully exit involves the win32 or WSL subsystem. The win32 subsystem is where `WM_CLOSE` and console ctrl events are handled, and the WSL subsystem is where signals are handled.

**Comment by tmccombs** [comment]
I don't know enough about Windows to know if such a distinction is possible in Windows. But I do think that there could be a function to perform a graceful shutdown, which may or may not do the same thing as the `kill` function depending on if the system supports a distinction. 

I'm curious why SIGKILL was chosen for the `kill` method on unix systems, since SIGTERM is usually what you want. In my experience a SIGKILL is generally only used when a SIGTERM has already been tried and failed to terminate the process. Of course, changing it now would break backwards compatibility, so it is water under the bridge.

**Comment by dtolnay** [comment]
I believe there is some design work remaining here so this is going to require an [RFC](https://github.com/rust-lang/rfcs/blob/master/libs_changes.md). Someone will need to propose a concrete way for this to be exposed in a platform-independent way or a platform-specific way (`std::os`) and justify why that is the best way for the standard library to expose it.

**Comment by Mygod** [comment]
Any progress on this? How about adding a `std::process::Child::terminate`?
