### ISSUE TITLE
Rust 1.19 regression: compiler hangs at 100% CPU compiling syntex

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#41832]
Reported here: https://github.com/rust-lang-nursery/rustfmt/issues/1517

Hangs at env_logger when compiling Rustfmt, I suspect it is one of the syntex crates, rather than env_logger causing problems. Reported on x64 and ARM (both Linux). I couldn't reproduce on x64 Linux.

**Comment by alexcrichton** [comment]
Hm are we sure that's a regression? It looks a lot like the "this is actually compiling syntex_syntax and that takes forever" rather than hanging at env_logger

**Comment by juanibiapina** [comment]
Found this issue but when I came back to the terminal I saw that the compilation had finished after about 6 minutes.

**Comment by crumblingstatue** [comment]
I strongly suspect this is just syntex_syntax taking forever to compile. Cargo should really give better information on what is currently compiling and what finished.
