### ISSUE TITLE
Avoid having both primary and secondary underlines on the same spans by supporting multiple primary errors.

### ISSUE THREAD

**Issue by Nickforall** [rust-lang/rust#41850]
While working on #41256, @jonathandturner proposed a specific syntax for having multiple primary errors on one line, like the example below. This required changes to the way the `DiagnosticBuilder` works and since I don't have enough knowledge of the codebase I am writing this follow-up issue.

An error with multiple unused arguments will look like the example below after merging #41256.

```
error: multiple unused formatting arguments
  -->  /Users/nickvernij/Programming/rust/src/test/ui/macros/format-foreign.rs:12:5
   |
12 |     println!("%.*3$s %s!/n", "Hello,", "World", 4);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^--------^^-------^^-^^
   |                              |         |        |
   |                              |         |        unused
   |                              |         unused
   |                              unused
   |
```

This example is having the same kind of error multiple times in one expression, and would ultimately look something like the example below since we try to avoid having both primary and secondary underlines on the same spans:

```
error: multiple unused formatting arguments
  -->  /Users/nickvernij/Programming/rust/src/test/ui/macros/format-foreign.rs:12:5
   |
12 |     println!("%.*3$s %s!/n", "Hello,", "World", 4);
   |                              ^^^^^^^^  ^^^^^^^  ^  
   |                              |         |        |
   |                              ------------------------- unused
```

**Comment by estebank** [comment]
Multiple primary spans are supported by using a `MultipSpan` as the primary span, but we won't add support to have a label apply to multiple spans at the same time (as the ascii art required for it doesn't compose well). I believe that the current output for this case in particular looks as good as we can get, but today we can also have:

```
error: multiple unused formatting arguments
  -->  /Users/nickvernij/Programming/rust/src/test/ui/macros/format-foreign.rs:12:5
   |
12 |     println!("%.*3$s %s!/n", "Hello,", "World", 4);
   |                              ^^^^^^^^  ^^^^^^^  ^ unused
```
