### ISSUE TITLE
Collecting into a PathBuf from Iterator<Item=Component> is hard.

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#41866]
See discussion here: https://github.com/rust-lang/rust/pull/41531.

To summarize, the following should work, but currently doesn't. It's likely that implementing `impl<P: AsRef<OsStr>> FromIterator<P> for PathBuf` would solve this, but I haven't tested.

```rust
use std::path::{PathBuf, Path};

fn main() {
    let path = Path::new("a/b/c/d");
    println!("{:?}", path.components().filter(|c| c.as_os_str() != "b").collect::<PathBuf>());
}
```

**Comment by ollie27** [comment]
The following already works fine:

```rust
use std::path::{Component, PathBuf, Path};

fn main() {
    let path = Path::new("a/b/c/d");
    println!("{:?}", path.components().map(Component::as_os_str).filter(|c| *c != "b").collect::<PathBuf>());
}
```

Maybe `Component` should implement `AsRef<Path>` as it already implements `AsRef<OsStr>` and `OsStr` implements `AsRef<Path>`.

**Comment by Mark-Simulacrum** [comment]
Component implementing `AsRef<Path>` seems like a good idea.

**Comment by dtolnay** [comment]
Sounds good to me, let's do it.
