### ISSUE TITLE
Nightly docs lack search bar

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#41867]
I believe due to the jQuery removal, nightly docs no longer have a search bar.

See https://doc.rust-lang.org/nightly/std/, for example, which has no search bar.

cc @GuillaumeGomez (I think you removed jQuery, but not sure)

**Comment by ollie27** [comment]
Works fine for me in Firefox 53.0.2 on Window 10, what browser are you using?

**Comment by Mark-Simulacrum** [comment]
Chrome Version 58.0.3029.96 (64-bit) on macOS. Note the errors in console below as well as the lack of a search bar.

![image](https://cloud.githubusercontent.com/assets/5047365/25877446/bf41e5b6-34e0-11e7-828b-b53d12a7f87d.png)

**Comment by kennytm** [comment]
@Mark-Simulacrum Have you tried force-refreshing?

**Comment by StefanoChiodino** [comment]
Works for me on MacOS with Chrome v 58.0.3029.96 (64-bit) even after hard refresh

**Comment by GuillaumeGomez** [comment]
@Mark-Simulacrum: Funny, you seem to have old js code with new html one. Try a force refresh like suggested above.

**Comment by Mark-Simulacrum** [comment]
Yeah, that fixed it. Closing the issue.
