### ISSUE TITLE
Two variant enum null value optimization

### ISSUE THREAD

**Issue by xfix** [rust-lang/rust#41874]
Language could optimize enums with two variants where at least one of variants stores a value that cannot be 0 (that would be affected by `Option<T>` optimization). For instance, the following `enum`.

```rust
enum Name {
   One(usize),
   Many(Box<[usize]>),
}
```

Is currently represented as:

1. tag (0 - `One`, 1 - `Many`)
2. `One`: usize, `Many`: pointer
3. `One`: unused, `Many`: length

This can be optimized as such:

1. `One` when 0, otherwise pointer of `Many`
2. `One`: usize, `Many`: length

This can save up to 8 bytes in an enum, while still allowing valid references to inner structures to be obtained.

**Comment by oli-obk** [comment]
This is already tracked in https://github.com/rust-lang/rfcs/issues/1230

**Comment by steveklabnik** [comment]
Yes, @oli-obk is right. Discussing this over there is the right place, I'm going to give this a close. Thank you!
