### ISSUE TITLE
Rewrite platform intrinsic generation as a build script

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#41885]
Right now the compiler has a [`rustc_platform_intrinsics` crate](https://github.com/rust-lang/rust/tree/master/src/librustc_platform_intrinsics) which is basically a database of all platform intrinsics with their inputs/outputs and LLVM names, etc. This is the information the compiler uses to typecheck all intrinsics and also generate code for them with LLVM. An example generated file looks like [`aarch64.rs`](https://github.com/rust-lang/rust/blob/25a161765fb90f2bfc78bda8fef944048e72bd26/src/librustc_platform_intrinsics/aarch64.rs).

These files are all generated by a [`generator.py`](https://github.com/rust-lang/rust/blob/25a161765fb90f2bfc78bda8fef944048e72bd26/src/etc/platform-intrinsics/generator.py) script in the `src/etc` dir. This generator slurps up a ton of JSON definitions, for example all the files in [`src/etc/platform-intrinsics/x86`](https://github.com/rust-lang/rust/tree/25a161765fb90f2bfc78bda8fef944048e72bd26/src/etc/platform-intrinsics/x86) and then generates these Rust files.

Now that we're using Cargo as a build system we can avoid checking in these generated source files. Instead we can translate `generator.py` into Rust as a build script and use build-time code generation to generate all of these files.

This isn't necessarily an easy task because `generator.py` is not exactly a trivial script, but I'm more than willing to help out if anyone's got any questions!

**Comment by tommyip** [comment]
I would like to work on this issue!

**Comment by alexcrichton** [comment]
@tommyip oh I believe @F001 in also expressed interest earlier in https://github.com/rust-lang/rust/issues/41568 for this issue. Just in that y'all may want to coordinate to make sure no toes are stepped on!

**Comment by alexcrichton** [comment]
(not sure why that issue link didn't show up...), also sorry, should have mentioned that in the issue earlier!

**Comment by tommyip** [comment]
ok no problem, I guess I should leave this to @F001 .

**Comment by F001** [comment]
Thanks. I will work on this.

**Comment by theduke** [comment]
@F001 are you still working on this?

**Comment by F001** [comment]
@theduke I'm sorry, I have not wok on this for more than two months. And I guess I won't have enough time for the comming 2 months. I have updated my code on https://github.com/F001/librustc_platform_intrinsics, in a very early stage. 

If anyone want to take this, that's OK. You can start from scratch or base on my project, it's your choice. I will probably come back to this issue at least 2 months later, if no one finish this task at that time.

**Comment by laumann** [comment]
I see this was taken out of "impl period", but it is a desirable thing to have implemented at the moment? It looks interesting, and I think I have time to look into it, so I'd be happy to give it a go (unless @tommyip wants a go first :smile:).

I also have some questions: the `generator.py` script takes some command-line parameters, and as this is not possible in build scripts, how should the generated code be built correctly? I'm guessing the parameters should be passed through env variables. Also, how should the code then be included? Is that any different than how it is now? (Now that I'm writing it, I guess I'm wondering where the code generation is triggered from and where the generated code is included.)

**Comment by tommyip** [comment]
@laumann go for it! I am kinda busy at the moment.

**Comment by alexcrichton** [comment]
@laumann oh awesome! We may not want to do a straight translation of `generator.py` 1:1 in the sense that there may be no need to define JSON when we could just have plain old Rust or a macro of some form. Additionally it's ok to avoid command line options and just always build all intrinsics unconditionally most likely?

**Comment by laumann** [comment]
@tommyip Cool :+1: 

@alexcrichton I think I'm wondering where in the build process this should be hooked in. Is the idea that the `librustc_platform_intrinsics` crate should just generate the right files when it's compiled? At this point the target architecture should be available (the `TARGET` env variable), so it should be possible to generate just the intrinsics needed, but just generate them all should work too.

Are you thinking of something specific that'd be easier with a macro rather than the JSON?

**Comment by alexcrichton** [comment]
@laumann ah yeah as a build script this'll just get naturally run and compiled whenever the crate's built. I don't think you'll need to take `TARGET` into account though as this includes the intrinsic definitions for all platforms all the time.

Oh whatever's easiest should be fine, I'd just imagine that long-term JSON isn't really necessary, it was probably just easy for Python.

**Comment by laumann** [comment]
@alexcrichton So I've been working on this [here](https://github.com/laumann/librustc_platform_intrinsics) (btw, so sorry I never got to say hi at RöstiFest!). I forked @F001's project as a starting point. Status is that it seems mostly complete, except for values that need to be plugged into the generated match arms.

@F001 I wanted to ask why the width is an `i32` and not a `u32`? Can it ever be negative?

**Comment by alexcrichton** [comment]
Gah sorry I missed you @laumann! But nice job on the work here so far!

**Comment by laumann** [comment]
No problem, you were kinda mobbed most of the time :smile:

**Comment by steveklabnik** [comment]
Triage: https://github.com/rust-lang/rust/pull/57416 fixed this bug 🎊
