### ISSUE TITLE
Allow rustdoc to generate noindex meta tags for a library

### ISSUE THREAD

**Issue by skade** [rust-lang/rust#41882]
There's currently a problem that when searching for the documentation of a crate in any search engine, chances are you find the documentation of a _different_ project that publishes their full documentation along with all dependencies.

To avoid that, allow rustdoc to generate the following meta tag for all documentation of a library:

```rust
<meta name="robots" content="noindex">
```

This makes most crawlers not index the page. The feature could be implemented behind a flag.

rel="canonical" would be preferably, but the correct URL is hard to derive.

**Comment by steveklabnik** [comment]
> rel="canonical" would be preferably, but the correct URL is hard to derive.

That's https://github.com/rust-lang/rust/issues/9461

**Comment by skade** [comment]
Thinking this further through, a blanket "noindex" for dependencies might lead to problems, though, if a project publishes docs for set of crates on the same domain, buy just building the topmost one.

**Comment by steveklabnik** [comment]
Triage: there's been no comments in two years. Additionally, we did accept an RFC that will fix this issue, and it is being tracked in https://github.com/rust-lang/rust/issues/44687. Closing.
