### ISSUE TITLE
Functions and closures with incorrect return types should have better diagnostics

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#41897]
We should do better on the diagnostic in this case, since presumably the author of the code meant to return the 10, so we should suggest that the function needs a return type, somewhat as we currently give the "remove `;`" suggestion.

```rust
fn foo() {
   10
}
```

```
error[E0308]: mismatched types
 --> test.rs:2:5
  |
2 |     10
  |     ^^ expected (), found integral variable
  |
  = note: expected type `()`
             found type `{integer}`

error: aborting due to previous error
```

Filing this to close out https://github.com/rust-lang/rust/issues/35478, https://github.com/rust-lang/rust/issues/21838, https://github.com/rust-lang/rust/issues/22216, https://github.com/rust-lang/rust/issues/18595 as duplicates of this.

**Comment by estebank** [comment]
Previous stab at this: #39231.

**Comment by estebank** [comment]
We do this [now](https://play.rust-lang.org/?gist=c8bad65ef8de56e75bf54d750e0ece90&version=nightly).
