### ISSUE TITLE
Tracking issue for slice_rotate

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#41891]
Implemented in https://github.com/rust-lang/rust/pull/41670; merged 2017-06-02.

**Comment by mbrubeck** [comment]
I suggest renaming the method from `rotate` to `rotate_left`; otherwise I have trouble remembering exactly what it does either when writing code or when reading it.  (If we do this, it would probably also be logical to add a `rotate_right` method.)

**Comment by scottmcm** [comment]
Bikeshed:

- `rotate`, following [Stepanov and McJones](http://elementsofprogramming.com/), like [in C++](http://en.cppreference.com/w/cpp/algorithm/rotate)
- `rotate_left`+`rotate_right`
- `bring_to_front`, like [in D](https://dlang.org/library/std/algorithm/mutation/bring_to_front.html)
- `slide`, from [Parent](https://youtu.be/qH6sSOr-yk8?t=560), `fn(&mut [T], impl RangeArgument, usize) -> Range<usize>` (often a nicer signature, but easy to implement using rotate on a subslice, so not necessarily the best primitive)

**Comment by mbrubeck** [comment]
More comparison notes:

* `collections.deque.rotate` in Python rotates to the right
* `rotate_left` and `rotate_right` are used in Rust for bitwise rotation

**Comment by jethrogb** [comment]
The doc text links to non-free documentation. Can we find a publicly available source to link to?

**Comment by frewsxcv** [comment]
Opened a pull request for introducing `rotate_{left,right}`: https://github.com/rust-lang/rust/pull/46777

**Comment by whitequark** [comment]
What's the timeline for stabilizing this?

**Comment by scottmcm** [comment]
I think @frewsxcv's PR resolved the questions from the original implementation (naming, return value, and docs), so maybe as soon as someone makes a stabilization PR (for 1.26, I guess?).

**Comment by frewsxcv** [comment]
stabilization pr: https://github.com/rust-lang/rust/pull/48450

**Comment by frewsxcv** [comment]
stabilization pull request just merged, so i _think_ this can be closed now
