### ISSUE TITLE
Feature proposal: named return variables

### ISSUE THREAD

**Issue by IvankoB** [rust-lang/rust#41895]
Possibly with default return values, to achive functionality of Delphi's function "Result" auto variable or as shown in the below "Go" code:
-------------------------
func OpenPrinter(name string) (success bool, printer HANDLE) {
	openPrinter := winspool.NewProc("OpenPrinterA")
	Cname := unsafe.Pointer(C.CString(strToAnsi(name)))
	defer C.free(Cname)
	Cret, _, _ := openPrinter.Call(uintptr(Cname), uintptr(unsafe.Pointer(&printer)), uintptr(0 /*Cnil*/))
	success = (int(Cret) != 0)
	return
}
Note the usage of return varibales "success" & "printer" within the function body. Very handy & clear.

The current "Rust" code for this function is as follows :
----------------------------
fn open_printer(name: String) -> (bool, HANDLE) {
    let h: HANDLE = ptr::null_mut();
    unsafe { 
        (OpenPrinterW(str2wcstr(&*name).as_ptr(), &h, std::ptr::null_mut()) == TRUE, h) 
    }
}

**Comment by Mark-Simulacrum** [comment]
This would best go on the rust-lang/rfcs repository. Could you open an issue there?

**Comment by IvankoB** [comment]
Opened there. Thanx.
