### ISSUE TITLE
Moving function into a separate crate results in a more effective code for some reason

### ISSUE THREAD

**Issue by newpavlov** [rust-lang/rust#41894]
While working on optimizations for [crypto-hashes](https://github.com/RustCrypto/hashes) I've notice a very strange behaviour described in the title. I've isolated the relevant code into this [repository](https://github.com/newpavlov/md5-optimization), so you can run it yourself.

Enabling lto produces the same slow result for separate case as for in-crate one. Optimal code generated only if `#[inline]` or `#[inline(always)]` used for compress function. Also generated assembly for two cases is quite different despite the identical code.

Probably it's due to some mis-optimization which gets turned off when function is in a different crate, but available for inlining.

UPD: It was reported on the reddit that 64-bit ARM shows the same performance for both cases.

**Comment by newpavlov** [comment]
Citing [doener](https://www.reddit.com/r/rust/comments/6ae7a2/moving_function_into_a_separate_crate_results_in/dhf0paj/):
>It's tied to the RC array. Moving just out of the original crate makes all the difference. Not sure why (yet).
 
> OK, so with the array values available, LLVM can collapse two add instructions into a single lea instruction.
> For example:
> 
> ```asm
> add    0x4(%r10),%edx # %r10 is the base address of RC
> add    %ecx,%edx
> ```
> 
> Becomes:
> 
> ```asm
> lea    -0x173848aa(%rdi,%rax,1),%eax
> ```
> 
> Now the problem is that this causes frontend stalls. perf stat shows:
> 
>  `1,946,734,091      stalled-cycles-frontend   #   65.05% frontend cycles idle     ( +- 15.66% )`
> 
> vs.
> 
>  `1,062,250,896      stalled-cycles-frontend   #   44.28% frontend cycles idle     ( +- 21.81% )`
> 
> Which is an issue in Intel CPUs since Sandy Bridge, where the three operand LEA instruction has higher latency and limited dispatch port choices, see https://software.intel.com/en-us/node/544484

**Comment by samlh** [comment]
Possible LLVM fix: https://reviews.llvm.org/rL303333

**Comment by newpavlov** [comment]
The issue is still reproducible on Nightly 2018-10-28.

**Comment by newpavlov** [comment]
The issue is no longer reproducible.
