### ISSUE TITLE
Debug impl for HashMap::keys should not require values to be Debug

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust#41924]
#39002 landed `Debug` implementations for a number of derived types in collections, but imposes overly strict requirements. For example, for [`std::collections::hash_map::Keys`](https://doc.rust-lang.org/std/collections/hash_map/struct.Keys.html):
```rust
impl<'a, K: Debug, V: Debug> Debug for Keys<'a, K, V> { /* ... */ }
```
Given that only the keys are printed, we should only require `K: Debug`, not *also* `V: Debug` (unless I'm mistaken?).

**Comment by sfackler** [comment]
Yep, seems overly restrictive.

**Comment by jonhoo** [comment]
While we're on it, `Values` should only require `V: Debug`, and the same change should be applied to `BTreeMap` and friends.
