### ISSUE TITLE
book: no-stdlib example doesn't need to use no_mangle for lang items

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rust#41925]
The examples in https://doc.rust-lang.org/book/no-stdlib.html use no_mangle for all of the items; however, some discussion on IRC suggested that the language items (everything other than the start symbol) don't actually need no_mangle.  Could we simplify the example to use only the minimal directives and unstable features required?

That'll also help to evaluate what features would need to be stabilized to make this work on stable Rust.

**Comment by steveklabnik** [comment]
Two things:

1. The book now lives at https://github.com/rust-lang/book so issues should be filed there.
2. We aren't tracking issues on the old book anymore; if you want to do this, please send in a PR! Thanks 😄
