### ISSUE TITLE
UI test output should be `patch` compatible

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#41948]
@eddyb made the good point that it'd be nice if the diff produced by UI tests were something one could easily feed into `patch`. Also, the role of `-` as "expected" and `+` as "actual" is correct, but the ordering is backwards from what diff uses. It'd be nice to change the call to diff so that instead of doing `diff_lines(actual, expected)` it did `diff_lines(expected, actual)` (and then making "left" print `-` etc). 

(Another question, can we add unit tests here somehow?)

cc @cengizIO

**Comment by cengizIO** [comment]
This can be closed since #42144 has landed.
