### ISSUE TITLE
rustc hangs where there are lots of compilation warnings

### ISSUE THREAD

**Issue by boblehest** [rust-lang/rust#41956]
I tried to compile [this](https://play.rust-lang.org/?gist=247f44a41f2d945d25f4951a9cfcf7a3) and it causes rustc to freeze both on stable and nightly on my computer. Playground handles it without any issues.

Using strace shows that it's blocking on write(). Full strace output [here](https://gist.github.com/boblehest/76e9858d87bde9f88dee74ae6e1a0255).

## Meta

Stable:
```
rustc 1.17.0 (56124baa9 2017-04-24)
binary: rustc
commit-hash: 56124baa9e73f28c0709e59e74783cf234a978cf
commit-date: 2017-04-24
host: x86_64-unknown-linux-gnu
release: 1.17.0
LLVM version: 3.9
```

Nightly:
```
rustc 1.19.0-nightly (e40beb3af 2017-05-11)
binary: rustc
commit-hash: e40beb3af162e676e40704854dd6547ee8d4cf60
commit-date: 2017-05-11
host: x86_64-unknown-linux-gnu
release: 1.19.0-nightly
LLVM version: 4.0
```

**Comment by boblehest** [comment]
I compiled this from source (same revision as the nightly I'm running), and it does _not_ exhibit the same behavior (the test file compiles successfully.)

```
rustc 1.19.0-dev (e40beb3af 2017-05-11)
binary: rustc
commit-hash: e40beb3af162e676e40704854dd6547ee8d4cf60
commit-date: 2017-05-11
host: x86_64-unknown-linux-gnu
release: 1.19.0-dev
LLVM version: 4.0
```

**Comment by TimNN** [comment]
Which `rustup --version` were you using?

This reminds me of a rustup bug quite some time ago which occurred when telemetry was enabled.

**Comment by boblehest** [comment]
`rustup 0.3.0 (7d7fed2 2016-07-14)`

Interesting. The rustup package itself (installed from AUR) says version 1.2.0-6. `rustup self update` just gives me an error. I'll try to update it then, thanks. :)
