### ISSUE TITLE
rust-src component is incomplete in recent nightlies

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#41952]
The component is missing compiler-rt, jemalloc and other git submodules required to compile the `std` crate. This broke Xargo's use case of cross compiling the `std` crate.

Affected version: `nightly-2017-05-04` and newer

### Workaround

Switch to an older nightly version:

Known good version: `nightly-2017-04-27` (still bisecting)

cc @brson @alexcrichton Do you know of any changes that may have caused this? It seems that the `rust-src` component has been trimmed to not include rustc source?

**Comment by alexcrichton** [comment]
cc @cuviper, maybe related to https://github.com/rust-lang/rust/pull/41546?

**Comment by cuviper** [comment]
Yeah, it's surely related.  If we want this to work, we'll have to augment [`std_src_dirs`](https://github.com/rust-lang/rust/blob/e19ccb71c8427135a69d874623af68422aeeb9e9/src/bootstrap/dist.rs#L495) with more paths, and maybe do a full compilation in the [`distcheck`](https://github.com/rust-lang/rust/blob/e19ccb71c8427135a69d874623af68422aeeb9e9/src/bootstrap/check.rs#L612).

At first glance, we'll need at least `compiler-rt`, `jemalloc`, and `libbacktrace`.  I'm a little sad to add `compiler-rt` as that's 35M added to the current 8.4M.  But 28M of that is `compiler-rt/test`, so maybe it can be pruned.  There's only 1.5M in `compiler-rt/lib/builtins`.

**Comment by RalfJung** [comment]
So, say I wanted to try and fix this -- how would I go about testing the fix?  Is there a way to (a) create that rust-src package locally (`./x.py dist src` or `./x.py dist`, I guess), and (b) tell rustup to install this package such that one could actually see whether xargo works now?

**Comment by ids1024** [comment]
> (b) tell rustup to install this package such that one could actually see whether xargo works now?

You can set `$XARGO_RUST_SRC` to tell xargo where to find the source for Rust, instead of messing with rustup.

**Comment by cuviper** [comment]
Yes, `./x.py dist src` will suffice.  I don't know how to get rustup to install it, but you can manually extract it and run `./install.sh --prefix ~/.rustup/toolchains/nightly-$TARGET`.

**Comment by RalfJung** [comment]
Thanks, sounds like I have two options to play with then :)
I'm still fighting other issues though; right now, a working xargo wouldn't even help. If I manage to solve them, I will come back to this one, but please don't hold your breath.

**Comment by RalfJung** [comment]
All right, I got things to work with xargo on old Rust nightlies, so I submitted #42214 to fix this bug.
