### ISSUE TITLE
Warn on unused lifetime parameters

### ISSUE THREAD

**Issue by clarfonthey** [rust-lang/rust#41960]
Somehow this made it into master without being warned:

```
#[stable(feature = "os_string_from_box", since = "1.17.0")]
impl<'a> From<Box<OsStr>> for OsString {
    fn from(boxed: Box<OsStr>) -> OsString {
        boxed.into_os_string()
    }
}
```

This should definitely trigger a warning.

**Comment by Thiez** [comment]
Yikes, no warnings at all.

```rust
fn main() {
    trait T {}
    impl<'a> T for u8 {}
}
```

**Comment by estebank** [comment]
Triage: no change.

**Comment by varkor** [comment]
Note that this is currently intentional behaviour:
https://github.com/rust-lang/rust/blob/e57577314120bb5504d5ce4b180fb6befc86f672/src/librustc_typeck/impl_wf_check.rs#L115
https://github.com/rust-lang/rust/blob/e57577314120bb5504d5ce4b180fb6befc86f672/src/librustc_typeck/impl_wf_check.rs#L139-L156

**Comment by clarcharr** [comment]
@varkor they should be accepted, just linted.

**Comment by scottmcm** [comment]
I think this still needs a warn-by-default lint, because I just spotted this in liballoc:

https://github.com/rust-lang/rust/blob/9a3392e174a432a5f06c1157befc1ce0fae74bec/src/liballoc/collections/vec_deque.rs#L2227-L2236

**Comment by JustAPerson** [comment]
```
pub type UnusedHrtb = for<'a> fn();
```
Found something like this in my codebase today. No warning from rustc or clippy.

**Comment by clarfon** [comment]
Any plans to add a warn-by-default lint?

**Comment by Mark-Simulacrum** [comment]
We have an `unused_lifetimes` lint now.

**Comment by estebank** [comment]
@Mark-Simulacrum it is not warn by default and I think it probably should be (gated may be on ecosystem prevalence).

**Comment by Mark-Simulacrum** [comment]
Hm, yeah, that makes sense. Reopening. I personally think we can probably "just" land this as a PR with FCP T-lang.

**Comment by varkor** [comment]
https://github.com/rust-lang/rust/issues/64493 should be considered blocking for making this warn-by-default.

**Comment by tmandry** [comment]
#86615 should also be considered blocking.

**Comment by Aaron1011** [comment]
With https://github.com/rust-lang/rust/issues/86615 now fixed on the latest nightly, is there anything blocking this?

**Comment by obi1kenobi** [comment]
I was assuming there aren't any blockers so I started looking into it a little bit, but I'm new to the codebase so it might take me a while especially given the holidays. If you'd like to take it over, be my guest!

There's no shortage of open issues, and I'm sure I can both find something else to work on and also learn from reading the PR that fixes this issue 😃

**Comment by Mark-Simulacrum** [comment]
Closing this in favor of https://github.com/rust-lang/rust/issues/94038, which is tracking the enabling of this by default -- I opted to file a new issue so that we have a cleaner history given its tracking status.
