### ISSUE TITLE
Inference for binary operators is order dependent

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#41976]
```rust
fn f<T>() -> T {
    unimplemented!()
}

fn main() {
    assert_eq!(f(), 100u8); // failed: cannot infer type for `_`
    assert_eq!(100u8, f()); // passed successfully
}
```

**Comment by arielb1** [comment]
That's the trait resolution limitation where `_ as Foo<X, Y, Z>` can't be resolved to any impl, because it can "theoretically" be a projection from a type parameter and we don't want to introduce unnecessary instability.

**Comment by arielb1** [comment]
That's it,

That's it:
```Rust
trait Xyz {
    type Out: Add<u8>;
}

trait Uvw { /* ... */ }

fn f<T>() -> T {
    unimplemented!()
}

fn foo<T: Uvw>() {
    assert_eq!(f(), 100u8); // failed: cannot infer type for `_`
    assert_eq!(100u8, f()); // passed successfully
}
```

and now we don't want to "automagically" pick the type to be `u8` only if there is no `impl<T: Uvw> Xyz for T`.

**Comment by Mark-Simulacrum** [comment]
@arielb1 So this isn't actually a bug and we should close?

**Comment by arielb1** [comment]
Yeah. Maybe Chalk will change things around, but I don't think there's any point in leaving a bug open.
