### ISSUE TITLE
fs::Permissions set_readonly is odd on Unix.

### ISSUE THREAD

**Issue by twmb** [rust-lang/rust#41984]
- `set_readonly(true)` wipes out write permissions, leaving existing executable permissions in place. This seems contrary to what I would expect this function to do: make something _only_ readable. I would expect `set_readonly(true)` to set the permissions to `0o444`.

- `set_readonly(false)` _adds_ write permissions to make permissions _not_ readonly, as opposed to wiping out read permissions. Setting permissions to not readonly itself is a bit odd to begin with. Any combination of permissions that are not just read is technically not read only. I don't have a good solution to this, but I think more clarifying documentation would suffice.

**Comment by retep998** [comment]
The current behavior matches the behavior on Windows (where the readonly file attribute prevents writes but has no effect on ability to read or execute). Changing the behavior on Unix would thus cause a significant difference in behavior across platforms, nevermind being a breaking behavior change in a stable function. However, improving the documentation to clarify the current behavior is a worthwhile goal.

**Comment by frewsxcv** [comment]
Opened a PR for this https://github.com/rust-lang/rust/pull/43883
