### ISSUE TITLE
Incorrect missing docs lint for proc-macro-lib crates

### ISSUE THREAD

**Issue by mthebridge** [rust-lang/rust#42008]
`proc-macro-lib` crates, when compiled with `-W missing-docs`, generate invalid warnings about missing documentation.  

The following simple crate demonstrates the error.

`src/lib.rs`:
```rust
//! Custom derive module
extern crate proc_macro;

use proc_macro::TokenStream;

/// Derive IntoIterator
#[proc_macro_derive(IntoIterator)]
pub fn into_iterator(_input: TokenStream) -> TokenStream {
    unimplemented!()
}
```

` Cargo.toml `:

```toml
[package]
name = "tmp"
version = "0.1.0"

[lib]
proc-macro = true
```

I expect this to compile cleanly since there is a crate-level doc comment and a doc comment for the public function.

Instead, compiling gives:
```
warning: missing documentation for a module [-W missing-docs]
 --> src/lib.rs:1:1
  |
1 | //! Custom derive module
  | ^

warning: missing documentation for a function [-W missing-docs]
 --> src/lib.rs:1:1
  |
1 | //! Custom derive module
  | ^
```
which makes no sense since line 1 *is* a comment.

Compiler version - latest stable, but fails on yesterday's nightly (2017-05-14) too:

`rustc --version --verbose`:
```
rustc 1.17.0 (56124baa9 2017-04-24)
binary: rustc
commit-hash: 56124baa9e73f28c0709e59e74783cf234a978cf
commit-date: 2017-04-24
host: x86_64-unknown-linux-gnu
release: 1.17.0
LLVM version: 3.9
```

**Comment by Mark-Simulacrum** [comment]
cc https://github.com/rust-lang/rust/issues/38356 (tracking issue)

**Comment by d-e-s-o** [comment]
I am hitting the same problem. This issue is preventing `#![deny(missing_docs)]` for proc-macro crates (I haven't found a work around). That's pretty annoying :-/ Rust 1.24.1.

**Comment by H2CO3** [comment]
Same here. Is there a fix for this?

**Comment by JeanMertz** [comment]
Seems to still be happening.

**Comment by rep-nop** [comment]
Fails on stable, beta, and nightly still.

**Comment by dbeckwith** [comment]
On a proc-macro crate in `nightly-2019-01-02`, I'm getting two warnings: `missing documentation for a module` and `missing documentation for a static` with no line numbers.

**Comment by iliekturtles** [comment]
`cargo +nightly expand` shows that the compiler is inserting a `pub mod` with a `pub static`. I didn't find the code that does the insertion in a very brief search.

```rust
//your proc_macro's mod.rs code...

pub mod decls {
    extern crate proc_macro;
    #[rustc_proc_macro_decls]
    pub static _DECLS: &[proc_macro::bridge::client::ProcMacro] =
        &[proc_macro::bridge::client::ProcMacro::bang(
            "your_proc_macro",
            crate::your_proc_macro,
        )];
}
```

**Comment by remexre** [comment]
So I guess the low-effort fix here is slapping `#[doc(hidden)]` on that `mod`?

**Comment by iliekturtles** [comment]
Thanks @remexre! Turns out my working copy wasn't updated like I thought so searching through it didn't work. PR #60562 just submitted.
