### ISSUE TITLE
rustdoc adds extra spaces where it shouldn't

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#42013]
As seen here: https://doc.rust-lang.org/std/sync/struct.Weak.html

These docs:

    /// pointer, which returns an [`Option`]`<`[`Arc`]`<T>>`.

render like this:

<img width="121" alt="optionarc" src="https://cloud.githubusercontent.com/assets/27786/26066409/b8335fe2-3964-11e7-8cba-b446ddb87bd3.png">

Those extra spaces shouldn't be there.

**Comment by Mark-Simulacrum** [comment]
https://doc.rust-lang.org/nightly/std/sync/struct.Weak.html is a better link, I think -- stable doesn't have this documentation quite yet.

**Comment by steveklabnik** [comment]
gah, yes, thank you

**Comment by tommyip** [comment]
I would like work on this

**Comment by tommyip** [comment]
Seems like a problem with CSS padding of the `a` tag. I think the best way to fix this is to have `<a>` tag inside `<code>` blocks instead of the reverse.

**Comment by GuillaumeGomez** [comment]
That's wanted. I added it this way to make easier to spot if different types are present.

**Comment by joshtriplett** [comment]
:+1: for fixing this spacing.

**Comment by GuillaumeGomez** [comment]
Ok, I'll reduce it (but won't remove it).
