### ISSUE TITLE
EXC_BAD_ACCESS comparing a vector and a const [u8; 2]

### ISSUE THREAD

**Issue by ttaubert** [rust-lang/rust#42031]
I can reproduce this bug reliably on my machine, using rustc stable and nightly. Unfortunately I couldn't come up with a reduced test case.

You will need macOS and a YubiKey inserted.

```
cd /tmp
git clone https://github.com/ttaubert/rust-compiler-bug
git clone https://github.com/jcjones/core-foundation-rs
cd rust-compiler-bug
cargo run
```

If you run this with lldb you'll see the following:

```
Process 8290 stopped
* thread #3, stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000000000000000
error: memory read failed for 0x0
```

The failure is here:

https://github.com/ttaubert/rust-compiler-bug/blob/master/src/lib.rs#L273

If I save the result of the comparison to a variable and return `Ok(rv)` the program doesn't crash.

**Comment by ttaubert** [comment]
The bug doesn't occur when built/run with `--release`.

**Comment by ttaubert** [comment]
> If I save the result of the comparison to a variable and return Ok(rv) the program doesn't crash.

Sorry, this is wrong. What works is the following:

```
let sign_resp = send_apdu(dev, U2F_AUTHENTICATE, flags, &sign_data)?;
Ok(&sign_resp[0..2] == SW_CONDITIONS_NOT_SATISFIED)
```

**Comment by jonas-schievink** [comment]
There's some pretty dubious unsafe code in there, are you sure that's not the issue?

**Comment by ttaubert** [comment]
Not entirely sure of course. But if turning on the optimizer and/or rewriting two lines of code remove a reproducible crash I'd think that rather points to a compiler issue, no?

**Comment by jonas-schievink** [comment]
No, if you cause undefined behaviour in your unsafe code, all bets are off. Anything can happen, optimizations or a simple reorganization of your code may expose or mask the problem.

**Comment by Mark-Simulacrum** [comment]
Well, the relevant repository doesn't exist anymore. So I'm not sure keeping this open is worth it...

**Comment by ttaubert** [comment]
I'll reopen or file a new issue if I see it again.
