### ISSUE TITLE
Google search links to past version of rust-lang

### ISSUE THREAD

**Issue by MI53RE** [rust-lang/rust#42035]
Wanted to start into Rust language and found out that google use old links to redirect user
instead of:
https://www.rust-lang.org/fr-FR/

I was redirected to:
https://www.rust-lang.org/fr/

Which contains the rust installator from December 22nd 2016 
instead of the current one from April 27th 2017

Did try "es" and "es-ES" and got the same result (though "es" didn't had css applied)

**Comment by steveklabnik** [comment]
could you re-file this against https://github.com/rust-lang/rust-www please? Thanks!

**Comment by MI53RE** [comment]
Sure thing! My bad if that I filled it in the wrong place !!
