### ISSUE TITLE
Overly strict lifetime reqs when unpacking structs

### ISSUE THREAD

**Issue by Xion** [rust-lang/rust#42045]
Playground link: https://is.gd/M1ruXP
```rust
use std::borrow::Cow;

pub struct Foo<'a> {
    foo: Cow<'a, str>,
    bar: u8,
}

fn make_owned<'a>(borrowed_foo: Foo<'a>) -> Foo<'static> {
    // error: cannot infer lifetime 'a (required 'a: 'static apparently)
    // Foo{
    //     foo: "".to_owned().into(),
    //     ..borrowed_foo
    // }

    // but this of course works
    Foo{
        foo: "".to_owned().into(),
        bar: borrowed_foo.bar,
    }
}

pub fn main() {
    let s = "string";
    let borrowed_foo = Foo{foo: s.into(), bar: 42};
    make_owned(borrowed_foo);
}
```

I've encountered this issue when trying to "copy" [this structure](https://docs.rs/gif/0.9.1/gif/struct.Frame.html) (`gif::Frame<'a>`) into a `'static` equivalent that replaces a borrowed buffer with an owned (empty) one, because I was only interested in the remaining fields.
But unfortunately, because unpacking such as above is incorrect, I had to meticulously [copy all the fields by hand](https://github.com/Xion/rofld/blob/2e3c01d953e855bcfd7b11c89f61aa0eaae75e26/src/util/animated_gif.rs#L64), even if I'm only using some of them.

As far as I understand, the limitation is that the unpacked & target type need to match exactly. This could perhaps be relaxed to follow the lifetime inheritance rules, in which case `'static: 'a` (specific `'a`) would imply that unpacking is, in fact, possible.

**Comment by Spoonbender** [comment]
Triage: no change

**Comment by Dylan-DPC** [comment]
Closing this as the code compiles now.
