### ISSUE TITLE
Better error message than E0573 when you typo a colon in place of a semicolon

### ISSUE THREAD

**Issue by luser** [rust-lang/rust#42057]
I made this typo in some code I was writing just now, a colon in place of a semicolon after a function call, with another function call on the next line:
```rust
fn f() {}

fn main() {
    f():
    f();
}
```

[Run it on play](https://play.rust-lang.org/?gist=8dcb2993683495112686576d6766edfc&version=stable&backtrace=0).

The compiler errors with:
```
rustc 1.17.0 (56124baa9 2017-04-24)
error[E0573]: expected type, found function `f`
 --> <anon>:5:5
  |
5 |     f();
  |     ^^^ not a type
```

This is technically correct, but it was confusing and it took me a few minutes to realize what I had done. It would be nicer if we could guess in some circumstances that the user probably meant to put a semicolon there and say something to that effect.

**Comment by wesleywiser** [comment]
Related to #41928 but not the same error message.

**Comment by luser** [comment]
Oh! I looked for other issues but didn't find anything obvious. I'm happy to close this in favor of that. Could you put some of the keywords from my issue title into yours? Perhaps at least the error number, 'colon' and 'semicolon'.

**Comment by wesleywiser** [comment]
I think they are separate issues since mine involves a macro. My test case doesn't actually generate an error number: [playground link](https://is.gd/EcktYE)
