### ISSUE TITLE
trait/struct name conflict error confusingly worded

### ISSUE THREAD

**Issue by Gankro** [rust-lang/rust#42061]
```rust
trait Foo { }
struct Foo { }

fn main() {}
```

```
error[E0428]: a trait named `Foo` has already been defined in this module
 --> <anon>:2:1
  |
1 | trait Foo { }
  | ------------- previous definition of `Foo` here
2 | struct Foo { }
  | ^^^^^^^^^^^^^^ `Foo` already defined
```

Two things are confusing here:

* Using "already" here is confusing because it makes you think that the compiler is talking about two conflicting traits, when the conflict is that we're declaring a struct with the same name as a trait.

* "`Foo` already defined" looks like it's trying to indicate the place of the first definition, and not the place of the second.

Random recommendation:

* "Two definitions with the name `Foo`"
* `Foo` redefined here

**Comment by alex-ozdemir** [comment]
My thought is the following:

* The error message should be "the name `Foo` is defined twice in this `module`".
* The note at the original definition/import should read "previous {`definition`/`import`} of the {`value`,`type`,`module`,...} `Foo` here".
* The note at the second definition/import should read "`Foo` {`redefined`/`reimported`} here"

Downsides: we say "defined twice" when we really mean "defined or imported". We could say "bound twice", but that would probably just confuse people.
