### ISSUE TITLE
x.py no longer works with Python 3

### ISSUE THREAD

**Issue by mjkillough** [rust-lang/rust#42085]
Recent changes to `x.py` have stopped it from working when run with Python 3:

```
[rust] $ python x.py
Updating submodules
Traceback (most recent call last):
  File "x.py", line 20, in <module>
    bootstrap.main()
  File "/home/mjk/Code/rust/src/bootstrap/bootstrap.py", line 684, in main
    bootstrap()
  File "/home/mjk/Code/rust/src/bootstrap/bootstrap.py", line 662, in bootstrap
    rb.update_submodules()
  File "/home/mjk/Code/rust/src/bootstrap/bootstrap.py", line 566, in update_submodules
    path = line[1:].split(' ')[1]
TypeError: a bytes-like object is required, not 'str'
[rust] $ python --version
Python 3.6.1
[rust] $ git rev-parse HEAD
6af8c6c7d1173f68addbf51560e6a009b30c9a93
```

It works when run with Python 2.

I had a quick look at fixing it, but it looks like the fix would need testing on Windows (due to console encoding shenanigans) and I don't have a Windows machine available right now.

**Comment by steveklabnik** [comment]
I'd be happy to test on windows if you can send over the patch

**Comment by projektir** [comment]
@mjkillough I'm curious, have you been successful using Python 3 in general? I was never able to get the full test suite to work when using Python 3, and there seemed a decent amount of work to do to have both Python 2 and 3 supported for the entire suite.

**Comment by mjkillough** [comment]
@steveklabnik - Thanks, but @nagisa has beat me to it.

@projektir - I think I was able to build and run the full test suite, but you've made me doubt myself. :) I'll double-check when I'm back at my computer.

**Comment by mjkillough** [comment]
@projektir - FWIW, with the PR that fixes `x.py, `python3 x.py test` seems to succeed apart from this: 

```
tidy check (x86_64-unknown-linux-gnu)


command did not execute successfully: "/home/mjk/Code/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/tidy" "/home/mjk/Code/rust/src" "--no-vendor"
expected success, got: exit code: 1
```

I'm not sure what's going on there, but I don't think it's related to Python.

**Comment by projektir** [comment]
@mjkillough interesting. Those are tidy failures, I got them too when I tried a different run, they're indeed unrelated (probably). Btw, why are you using `python3` here, when, previously, you were using `python`, and it had version `Python 3.6.1`?

**Comment by mjkillough** [comment]
@projektir - I am not sure why I used python3. Both python and python3 are the same 3.6.1 binary on my system.
