### ISSUE TITLE
Make fails when attempting to compile for various Apple & iOS targets

### ISSUE THREAD

**Issue by AdamCampbell** [rust-lang/rust#42084]
I am trying to follow this [guide](https://www.bignerdranch.com/blog/building-an-ios-app-in-rust-part-1/)
It's a little outdated but I have checked out repo in order to manually compile for these targets.

I have run:
```
configure --target=armv7-apple-ios,armv7s-apple-ios,i386-apple-ios,aarch64-apple-ios,x86_64-apple-ios --prefix=$HOME/rustc-ios
make -j8 && make install
```

However I think the ordering in the makefile is wrong as it tries to run an install.sh that does not exist.

[rust-compile-log.txt](https://github.com/rust-lang/rust/files/1011074/rust-compile-log.txt)
Log of failed installation is attached with the main issue being:
```
Install std stage2 (armv7-apple-ios)
sh: /Users/adam/Development/rust/build/build/tmp/dist/rust-std-1.19.0-dev-armv7-apple-ios/install.sh: No such file or directory
```

**Comment by kennytm** [comment]
Nowadays you don't need to build a cross-compiler from source yourself. `rustup` is enough to setup everything for iOS (and Android) development. The whole "Installing Rust with multirust" should be replaced by "Install [rustup](https://www.rustup.rs/)." 

```sh
curl https://sh.rustup.rs -sSf | sh
```

and the whole "Building a Cross Compiler" should be replaced by

```sh
rustup target add aarch64-apple-ios 
rustup target add armv7-apple-ios 
rustup target add armv7s-apple-ios 
rustup target add x86_64-apple-ios 
rustup target add i386-apple-ios
```

then go on from "Hello, World: Building the Rust Library" (but ignore the `multirust override ios` step).

cc @jgallagher

**Comment by AdamCampbell** [comment]
Oh awesome thanks @kennytm that should make things much easier.
May as well leave this issue open for now, don't know if this compilation log represents a compiler error or user error now since so much has changed.

**Comment by piaojin** [comment]
@kennytm 
```Rust
curl https://sh.rustup.rs -sSf | sh
and the whole "Building a Cross Compiler" should be replaced by

rustup target add aarch64-apple-ios 
rustup target add armv7-apple-ios 
rustup target add armv7s-apple-ios 
rustup target add x86_64-apple-ios 
rustup target add i386-apple-ios
```

work for me, thanks!

**Comment by ppamorim** [comment]
I am getting `component 'rust-std' for target 'i386-apple-ios' is unavailable for download for channel stable` when running the commands above, only the target `aarch64-apple-ios` works.

**Comment by kennytm** [comment]
@ppamorim  All 32-bit Apple targets have been removed since 1.42.0. You could just leave those targets out. See https://blog.rust-lang.org/2020/01/03/reducing-support-for-32-bit-apple-targets.html for details.

**Comment by madsmtm** [comment]
Triage: There is nothing to be done here, so I suggest that we close this issue, and direct questions to [the users forum](https://users.rust-lang.org/).
