### ISSUE TITLE
Repeated "mutable/immutable borrow" error messages

### ISSUE THREAD

**Issue by tommyip** [rust-lang/rust#42106]
Minimal example:
```rust
fn do_something<T>(collection: &mut Vec<T>) {
    let a = &collection;
    collection.swap(1, 2);
}
```

Error message (ran in playground):
```
rustc 1.17.0 (56124baa9 2017-04-24)
error[E0502]: cannot borrow `*collection` as mutable because `collection` is also borrowed as immutable
 --> <anon>:3:5
  |
2 |     let a = &collection;
  |              ---------- immutable borrow occurs here
3 |     collection.swap(1, 2);
  |     ^^^^^^^^^^ mutable borrow occurs here
4 | }
  | - immutable borrow ends here

error[E0502]: cannot borrow `*collection` as mutable because `collection` is also borrowed as immutable
 --> <anon>:3:5
  |
2 |     let a = &collection;
  |              ---------- immutable borrow occurs here
3 |     collection.swap(1, 2);
  |     ^^^^^^^^^^ mutable borrow occurs here
4 | }
  | - immutable borrow ends here

error: aborting due to 2 previous errors

Compilation failed.
```

Tested on nightly as well (`rustc 1.19.0-nightly (0ed1ec9f9 2017-05-18)`)

**Comment by est31** [comment]
Related: #40067

**Comment by estebank** [comment]
[`report_error_if_loans_conflict `](https://github.com/rust-lang/rust/blob/0f0f5db465de96b6c12e71f0c7d3e475f618b104/src/librustc_borrowck/borrowck/check_loans.rs#L377-L396) calls [`report_error_if_loan_conflicts_with_restriction`](https://github.com/rust-lang/rust/blob/0f0f5db465de96b6c12e71f0c7d3e475f618b104/src/librustc_borrowck/borrowck/check_loans.rs#L398-L403) twice without checking the return value. Modify it to return `Result<(), DiagnosticBuilder<'a>>` and check where it is being called ether both calls have returned an (cancel one, emit the other, return `false`), wether only one was created (emit it, return `false`) or none has (return `true`).

**Comment by tommyip** [comment]
I'll fix this, thanks for the instruction!

**Comment by lochsh** [comment]
I would happily have a go at this, if that's ok with @tommyip  😄

**Comment by tommyip** [comment]
Sure @lochsh go for it!

**Comment by joshleeb** [comment]
@lochsh have you had time to work on this? If not could I give it a go? :)

**Comment by lochsh** [comment]
@joshleeb I totally thought I was going to have time, but I had a crazy week at work this week.  Go ahead and give it a go :)  I'll find another bug to work on when I definitely have time 👍

**Comment by dsheets** [comment]
It looks like the PR to fix this was merged but has a few dangling threads. There seems to be some confusion about short-circuiting functionality and the necessity of the patch and also the error count still reads 2 rather than 1. Should a new issue be opened with those issues and this issue closed?
