### ISSUE TITLE
You typed `channels`. Did you mean to type `channels`?

### ISSUE THREAD

**Issue by legolord208** [rust-lang/rust#42119]
![Image](https://cdn.discordapp.com/attachments/275192340979646464/315478039037476864/unknown.png)

Related code:

```Rust
for server in state.servers() {
	for channel in server.channels() { // Line 205
		if channel.name == name {
			return Some(ChannelRef::Public(server, channel));
		}
	}
}
```

EDIT: `channels` is a thing, but it's not a function. It's a variable.

**Comment by Mark-Simulacrum** [comment]
I'm not quite sure what's wrong here -- it's suggesting `server.channels`, instead of the current `server.channels()`.

**Comment by legolord208** [comment]
Oh, I thought this was supposed to be the corrected thing

![image](https://cloud.githubusercontent.com/assets/12830969/26276174/5079befc-3d72-11e7-8f23-c55d0a0d0717.png)

Welp, apparently not. Sorry for wasting your time

**Comment by Mark-Simulacrum** [comment]
Not a waste of time! We always want to hear about concerns with our diagnostics, improving them makes for a better experience with Rust for everyone.
