### ISSUE TITLE
Lifetime parameters are silently deleted

### ISSUE THREAD

**Issue by djzin** [rust-lang/rust#42115]
This compiles:

```rust
fn lifetime<'a>()
    where &'a (): 'a
{
    /* do nothing */
}

fn main() {
    lifetime::<'static>()
}
```

as does this:
```rust
fn lifetime<'a>() {} 
fn main() {
    lifetime();
}
```

but this fails:
```rust
fn lifetime<'a>() {}
fn main() {
    lifetime::<'static>();
}
```

```
rustc 1.19.0-nightly (5dfcd85fd 2017-05-19)
error[E0088]: too many lifetime parameters provided: expected at most 0 lifetime parameters, found 1 lifetime parameter
 --> <anon>:3:5
  |
3 |     lifetime::<'static>();
  |     ^^^^^^^^^^^^^^^^^^^ expected 0 lifetime parameters

error: aborting due to previous error
```

**Comment by eddyb** [comment]
They become late-bound when not used in bounds or are used only the return type.
cc @nikomatsakis We should really do something about this.

**Comment by nikomatsakis** [comment]
Yeah the current situation is pretty goofy. It'd probably be best if we could report an error when providing lifetimes unless you provide *all* of them (late and early bound) -- at minimum, for now, we could just make it an error to specify lifetimes if any of them are late bound. 

Nominating so this doesn't get lost. I'm a bit nervous because of backwards compatibility. (In fact, I already recommended to @jdm a hack that relied on the current behavior.)

**Comment by nikomatsakis** [comment]
Purpose of nomination is to try and decide how we should handle this and how to prioritize.

**Comment by nikomatsakis** [comment]
triage: P-medium

This situation has been a problem for a long time in various forms, and is a bit obscure, but nonetheless current situation is not great. To some extent this is also a @rust-lang/lang question.

**Comment by nikomatsakis** [comment]
I'm going to change to T-lang. There are definitely some thorny questions here.

**Comment by nikomatsakis** [comment]
Discussed in the @rust-lang/lang meeting -- we agree that restricting to 100% early-bound is the right thing here. As proposed in https://github.com/rust-lang/rust/pull/42492

**Comment by nikomatsakis** [comment]
triage: P-high

**Comment by nikomatsakis** [comment]
@petrochenkov since you agreed to take a stab at that lint, I'm assigning you to the issue for now :) hope that's ok
