### ISSUE TITLE
Nightly Windows tarballs may not be installable on Unix

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#42121]
I got [two errors](https://travis-ci.org/alexcrichton/port-of-rust/builds/234251285) in a project of mine for recent nightlies which I think are releated to the rustification of rust-installer but I'm not 100% certain:

* [install.sh scripts may not be executable](https://travis-ci.org/alexcrichton/port-of-rust/jobs/234251291#L834)
* [I think backslashes may be causing installation failures](https://travis-ci.org/alexcrichton/port-of-rust/jobs/234251298#L767)

@cuviper does this sound familiar to you?

**Comment by alexcrichton** [comment]
Oh looks like https://github.com/rust-lang/rust-installer/issues/65 and https://github.com/rust-lang-nursery/rustup.rs/issues/1127 are all related to this as well.

**Comment by cuviper** [comment]
Ah, yes, backslashes in the manifest are an easily understood problem.

Executable install.sh is harder.  At least I left a note about that [here](https://github.com/rust-lang/rust-installer/blob/655a137a8bd0dda1cc71fb82661446e215563d6f/src/util.rs#L19). :)  Since Windows doesn't really have such flags, I suspect it must have worked on some MSYS tricks with ACLs before.  Maybe we should make a special case for this when writing the tarball, like writing known-executable file names with manually-tweaked metadata?

**Comment by alexcrichton** [comment]
Yeah I think we'll probably just want to special case everything going into the tarballs and manually set the metadata for the various bits and pieces. I'm... not entirely sure how this worked with MSYS, but presumably there's some weird translation layer which we're not aware of and isn't surfaced through winapi things...

**Comment by cuviper** [comment]
OK, so #42132 should fix up the manifests at least.

Researching the file modes, I first wondered whether the `tar` crate should read the advanced ACLs for `FILE_EXECUTE`, as right now it just [approximates the mode](https://github.com/alexcrichton/tar-rs/blob/babe0c8118a8d58c1c5e25a7663560153a78e51d/src/header.rs#L685-L696).  But it looks like *all* created files have "execute" privileges anyway -- e.g. even `icacls manifest.in` includes `Everyone:(RX)`.  You can remove that with `chmod` in MSYS/Cygwin/etc., but it appears atypical for a file _not_ to be executable.

The good news is that `tar` also doesn't care about execute when unpacking on Windows, just [checking for readonly](https://github.com/alexcrichton/tar-rs/blob/babe0c8118a8d58c1c5e25a7663560153a78e51d/src/entry.rs#L489-L494).  The rest will follow the defaults of `File::create`, still with executable ACLs.  So I think the permissions created by rustup will be fine, but I guess if one manually unpacks with MSYS/Cygwin tar they may get non-executable `rustc.exe` etc.

@alexcrichton The quickest hack for you would be to just change this:

    Step 7 : RUN /tmp/rust-mingw-nightly-i686-pc-windows-gnu/install.sh --prefix=`rustc --print sysroot`

... to invoke `sh install.sh` instead, which doesn't care about execute privileges. :)

**Comment by alexcrichton** [comment]
Ah yeah I don't think there's a great way to flag a file on Windows as executable/not-executable, I'm basically just thinking that we have a whitelist of files/patterns that will get listed as executable in the tarball (as the tarball stores unix modes) and we'd just follow that.
