### ISSUE TITLE
rustc failed with malloc_zone_unregister

### ISSUE THREAD

**Issue by zsounder** [rust-lang/rust#42138]
Running rustc on osx 10.12.4, got error message:
`rustc(27086,0x7fffad1ad3c0) malloc: *** malloc_zone_unregister() failed for 0x7fffad1a3000`

**Comment by kennytm** [comment]
Hi, could you provide details on how did you install the `rustc`?

**Comment by zsounder** [comment]
solved after reinstall 1.17.0 by brew
