### ISSUE TITLE
Teach .pkg, .msi, .exe installers about RLS

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#42157]
RLS can be installed via rustup, but not the other methods yet. We really can't claim RLS is released without.

I'm putting this on the 1.19 milestone because I don't see it being fixed in 1.18 at this point.

cc @nrc

**Comment by brson** [comment]
Help would be appreciated for any of the three packaging solutions. RLS should be a non-default component.

**Comment by efyang** [comment]
So if I'm looking at this right the main files that would need to be changed are `src/bootstrap/dist.rs` and the manifests in `src/etc/installer/`. Could I try taking up this issue?

**Comment by o01eg** [comment]
Can it be related to https://github.com/gentoo/gentoo-rust/issues/255 ?

**Comment by efyang** [comment]
Would it make more sense to have the analysis module be a child "feature" of the RLS or just entirely bundled with the RLS?

**Comment by nagisa** [comment]
Why not just ship two installers?

**Comment by brson** [comment]
Thanks so much for tackling all three of them @efyang!

Sadly we're going to need to revert temporarily per https://github.com/rust-lang/rust/issues/42357 until we make some more decisions about how we want to message rls stability. RLS is not going to happen for 1.19.

**Comment by alexcrichton** [comment]
Tis was done awhile ago!
