### ISSUE TITLE
"field expressions may not have type parameters" error missing hint

### ISSUE THREAD

**Issue by spikefoo** [rust-lang/rust#42153]
The compiler fails to show the ```= help: maybe a `()` to call it is missing? If not, try an anonymous function``` hint for the [following code](https://is.gd/Ts6OPP):

```rust
v.iter().collect::<Vec<_>>; /* missing () */
```

The hint does show when not using the turbo fish syntax: ([code](https://is.gd/KRFcsU))

```rust
v.iter().collect; /* missing () */
```

**Comment by Mark-Simulacrum** [comment]
This appears to work today; closing.
