### ISSUE TITLE
man page for rustdoc is out of date

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/rust#42158]
[the man page in question](https://github.com/rust-lang/rust/blob/master/man/rustdoc.1)

For example, it still talks about json output, which hasn't been a thing in a long time. There are probably some remarks that could be made about command line arguments, as well. For example, it could include a note about how you can change the passes used to render documentation for private items.

**Comment by Mark-Simulacrum** [comment]
All of the manpages, to my knowledge, are out of date; see https://github.com/rust-lang/rust/issues/25689.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of #25689 - we need to figure out a general strategy for these.
