### ISSUE TITLE
Recursive type error could be made more ergonomic in simple cases

### ISSUE THREAD

**Issue by P-E-Meunier** [rust-lang/rust#42154]
I suspect this is probably undecidable in the general case, but in my simple case it is decidable.
The following code defines a simple function, with a fairly common pattern of taking an `FnMut`, and threading it through a for loop, recursing at each iteration.

```
fn fold<F:FnMut(usize, u8) -> usize>(recurse: bool, mut init: usize, mut f: F) -> usize {
    if recurse {
        for i in 0..2 {
            init = f(init, i);
            init = fold(false, init, &mut f)
        }
        init
    } else {
        init
    }
}

fn main() {
    fold(true, 0, |a, b| a + (b as usize));
}
```

This causes rustc to loop and dump its "requirement trace".
Would it be possible to either:

- Print a single step of the trace, possibly adding an option to print it all.
- Or (even better) detect "borrow cycles".

I'm obviously no compiler expert, and I have absolutely no clue as to whether this is possible, and I'd be interested in the answer.

**Comment by estebank** [comment]
[Current output](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=d927acc98ace18d42039e03d1bf4717a):

```
error: reached the recursion limit while instantiating `fold::<&mut &mut &mut &mut &mut ...osure@src/main.rs:14:19: 14:25]>`
 --> src/main.rs:5:20
  |
5 |             init = fold(false, init, &mut f)
  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
note: `fold` defined here
 --> src/main.rs:1:1
  |
1 | fn fold<F:FnMut(usize, u8) -> usize>(recurse: bool, mut init: usize, mut f: F) -> usize {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = note: the full type name has been written to '/playground/target/debug/deps/playground-07b5fd22867752b9.long-type.txt'
```

We still don't provide guidance on what to do.
