### ISSUE TITLE
Document why std::process::Child methods return Results

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#42166]
The documentation text of the methods for [std::process::Child](https://doc.rust-lang.org/nightly/std/process/index.html) don't say why the methods return results. The examples do contain `.expect("command wasn't running")`. From this, I ask these questions: Is that the only reason these methods can fail? Why can the process spawn, but the command "wasn't" running? Does "wasn't" mean at the time the method was called, or ever? Will it return an Ok(_) if it starts running? Can it start running?

**Comment by sfackler** [comment]
"command wasn't running" is not really the right message there - at least on Unix systems waitpid will fail if that child's exit was already collected by something else in the process.

**Comment by frewsxcv** [comment]
For reference, here are the Windows and unix implementations of `wait`:

* [unix](https://github.com/rust-lang/rust/blob/6f4ab9458a7ad06c8ce630604f533c8c0c0acef4/src/libstd/sys/unix/process/process_unix.rs#L250-L259)
* [windows](https://github.com/rust-lang/rust/blob/6f4ab9458a7ad06c8ce630604f533c8c0c0acef4/src/libstd/sys/windows/process.rs#L348-L358)

**Comment by frewsxcv** [comment]
Is anyone aware of not-unsafe Rust code that would trigger an `Err` to be returned from `wait`?

**Comment by DevQps** [comment]
@frewsxcv @steveklabnik @sfackler What do you think about my previous comment? Personally, I believe it is better to close this issue, since it is platform specific and the unclear ```expect``` text in the example was already adjusted.

**Comment by frewsxcv** [comment]
> - An error can occur when the passed string contains a null-character somewhere in between.
> - When something went wrong linking stdio and stdout together. Not sure if this can ever go wrong in a normal program? I have no idea if a program can somehow close stdin and stdout, which prevents these to be linked / unable to communicate. I got this from [`sys::unix::process::process_unix`](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/process/process_unix.rs).

@DevQps Thanks for looking into this! Do you recall where these checks happen in the codebase? I saw you linked to `process_unix.rs`, but I'm not seeing anything about linking in that file

**Comment by DevQps** [comment]
@frewsxcv I had to dive into it once more (because I more or less forgot haha)

But upon calling `.output` on a `Command` as described in the example on [`std::process`](https://doc.rust-lang.org/nightly/std/process/index.html) we have the following code (this is in [process_unix.rs](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/process/process_unix.rs):

```
    pub fn output(&mut self) -> io::Result<Output> {
        self.inner.spawn(imp::Stdio::MakePipe, false).map(Child::from_inner)
            .and_then(|p| p.wait_with_output())
    }
```
which then calls `spawn`. 

In the spawn function we have this line for the null check:
```
if self.saw_nul() {
            return Err(io::Error::new(ErrorKind::InvalidInput,
                                      "nul byte found in provided data"));
        }
```

I see also this check in `spawn`:

```
// loop to handle EINTR
        loop {
            match input.read(&mut bytes) {
                Ok(0) => return Ok((p, ours)),
                Ok(8) => {
                    assert!(combine(CLOEXEC_MSG_FOOTER) == combine(&bytes[4.. 8]),
                            "Validation on the CLOEXEC pipe failed: {:?}", bytes);
                    let errno = combine(&bytes[0.. 4]);
                    assert!(p.wait().is_ok(),
                            "wait() should either return Ok or panic");
                    return Err(Error::from_raw_os_error(errno))
                }
                Err(ref e) if e.kind() == ErrorKind::Interrupted => {}
                Err(e) => {
                    assert!(p.wait().is_ok(),
                            "wait() should either return Ok or panic");
                    panic!("the CLOEXEC pipe failed: {:?}", e)
                },
                Ok(..) => { // pipe I/O up to PIPE_BUF bytes should be atomic
                    assert!(p.wait().is_ok(),
                            "wait() should either return Ok or panic");
                    panic!("short read on the CLOEXEC pipe")
                }
            }
        }
```
Which seems to be for handling EINTR.

Technically it can also fail at a few other parts if too little memory would exist. But I guess that would be true for almost any function.

About failing to link the different pipes of the child and parent process, I think that was a mistake on my part! They do something with pipes in `do_exec` but that method returns an error anyway, so I don't think that is too relevant.

**Comment by DevQps** [comment]
But of course this is only for UNIX processes. I think for Windows and other platforms this might be different. But I think memory constraints or invalid arguments are probably common on all platforms.

**Comment by steveklabnik** [comment]
Yes, let's just close. Thanks!
