### ISSUE TITLE
Allow limiting the number of benchmark iterations

### ISSUE THREAD

**Issue by torkleyy** [rust-lang/rust#42176]
I'd like to have a limit for benchmarks, because sometimes they execute the closure too often.

Maybe we could expose `BenchMode` and add a variant `Constant(usize)` to it?

**Comment by Mark-Simulacrum** [comment]
Closing in favor of duplicate https://github.com/rust-lang/rust/issues/11010; realistically we want to do this automatically. I've added a note there that a limit for the time being may be a good idea.
