### ISSUE TITLE
E0493 is missing from https://doc.rust-lang.org/error-index.html

### ISSUE THREAD

**Issue by glyn** [rust-lang/rust#42170]
This [example](https://is.gd/2oBXp7) (correctly) fails to compile with "error[E0493]: destructors in statics are an unstable feature", but https://doc.rust-lang.org/error-index.html#E0493 is not found.

There is however some documentation in [librustc_mir/diagnostics.rs](https://github.com/rust-lang/rust/blob/910c4816fdee01a1299d11a5e85ebb4aceee6d1a/src/librustc_mir/diagnostics.rs#L382):
```
E0493: r##"
A type with a destructor was assigned to an invalid type of variable. Erroneous
code example:

struct Foo {
    a: u32
}
impl Drop for Foo {
    fn drop(&mut self) {}
}
const F : Foo = Foo { a : 0 };
// error: constants are not allowed to have destructors
static S : Foo = Foo { a : 0 };
// error: destructors in statics are an unstable feature

To solve this issue, please use a type which does allow the usage of type with
destructors.
"##,
```

**Comment by Mark-Simulacrum** [comment]
I'm going to close this in favor of https://github.com/rust-lang/rust/issues/34588 which tracks the larger issue of the error index being insufficiently tested as well as not really processed in full. Thanks; this has reminded me that I wanted to devote some time to fixing this 'soon.'

**Comment by glyn** [comment]
@Mark-Simulacrum Thanks. I was hoping for an outcome along those lines. :-)
