### ISSUE TITLE
Bounds in HRTB are ignored

### ISSUE THREAD

**Issue by djzin** [rust-lang/rust#42181]
The syntax `where for<'b: 'a> ...` is permitted without warning, however the `: 'a` bound is not used to prove the identity; I would expect the following to compile:

```rust
trait Trait {}

impl Trait for &'static () {}

fn f<'a>(_: &'a ()) where for<'b: 'a> &'b () : Trait {}

fn main() {
    static X: &'static () = &();
    f::<'static>(X)
}
```

but it fails with

```
rustc 1.17.0 (56124baa9 2017-04-24)
error[E0277]: the trait bound `for<'b> &'b (): Trait` is not satisfied
 --> <anon>:9:5
  |
9 |     f::<'static>(X)
  |     ^^^^^^^^^^^^ the trait `for<'b> Trait` is not implemented for `&'b ()`
  |
  = help: the following implementations were found:
            <&'static () as Trait>
  = note: required by `f`

error: aborting due to previous error
```

**Comment by eddyb** [comment]
This might be a dupe - either way, potentially dangerous if we make it do anything. cc @nikomatsakis

**Comment by nikomatsakis** [comment]
Yes, we should deal with this. Errors are best for now, though I hope to extend HRTB to support where-clauses.

**Comment by nikomatsakis** [comment]
triage: P-medium

This is old. But let's fix it. Might be a good E-mentor candidate. I'll try to write-up some instructions.

**Comment by RalfJung** [comment]
Bounds in type aliases are similarily ignored:
```rust
type Test<'a, 'b: 'static> = &'a mut &'b mut i32;

fn main() {
    let x : Test = &mut &mut 0;
}
```
Is that a separate bug? This seems closer to whatever lead to E0122 being added, which however seems to have happened long ago.
(Funny enough, the compiler even tries to be helpful and tells me that I can just remove `'b` and replace it by `'static` -- which doesn't match how the `Test` type actually behaves.)

**Comment by eddyb** [comment]
> (Funny enough, the compiler even tries to be helpful and tells me that I can just remove `'b` and replace it by `'static` -- which doesn't match how the Test type actually behaves.)

It only doesn't behave that way because the bounds are forgotten... which is a real shame.
IMO possibly the best path forward is to add more projections, including one for type aliases. That would allow recovering the bounds.

**Comment by eddyb** [comment]
@RalfJung Right now we only have `<T as Trait>::Assoc` projections. We could add a type alias projection, which would turn into the type being aliased at the first occasion, *while* producing the obligations from the bounds of the type alias.

**Comment by RalfJung** [comment]
AH so you're not talking about a new syntax, just a different implementation strategy.

**Comment by eddyb** [comment]
@RalfJung Right. The compiler has everything it needs, there just isn't a way to get the information to the uses. Inside functions it's not that hard, but outside there isn't really where to store it.
