### ISSUE TITLE
"Undeclared type or module" could use some love.

### ISSUE THREAD

**Issue by jD91mZM2** [rust-lang/rust#42188]
So, this error

![image](https://cloud.githubusercontent.com/assets/12830969/26398612/4f36efd2-407a-11e7-9b99-4043ab31d409.png)
is here because the type `std` isn't in the current mod - it's in the main one.  
It's really easy to fix, I'd just use `::std` instead.

Maybe this error could give any hint about this?

**Comment by Mark-Simulacrum** [comment]
Hm, I'm not sure I'd want to provide a hint about `::std::io::Error` being possible, as I sort of don't like that syntax; it hides the fact that the module uses `std::io::Error`.

@nrc, I can't seem to ping the style team, but do you know if you've come up with any guidelines in this area?

**Comment by legolord208** [comment]
(I don't use `std::io::Error` anymore in my code - I was just playing around)

**Comment by Mark-Simulacrum** [comment]
2018 edition mostly deals with this as `std::io::Error` is valid now, along with other similar paths as well I believe.
