### ISSUE TITLE
[Windows] libpthread missing exports, so I can not link

### ISSUE THREAD

**Issue by ctaggart** [rust-lang/rust#42194]
I posted [How do I use a different libstdc++.a with Rust?](https://stackoverflow.com/questions/44157157/how-do-i-use-a-different-libstdc-a-with-rust), but after some [more debugging](https://github.com/ctaggart/octh/issues/18#issuecomment-303691573), it looks like libpthread doesn't have any exports. Why doesn't it?

```
dumpbin /exports "C:\Users\camer\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libpthread.a"
```

I was expecting it to have exports like other libraries in the directory do:
```
dumpbin /exports "C:\Users\camer\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libcrypt32.a"
```

I was expecting it to have the same exports as other libpthread libraries:
```
dumpbin /exports "C:\Octave\Octave-4.2.1\lib\libpthread.dll.a"
```

Looking around at the issues here, it looks like it may be related to:
* [Windows] Enable building rustc with "pthreads" flavor of mingw. #40805

**Comment by alexcrichton** [comment]
cc @vadimcn

**Comment by vadimcn** [comment]
@ctaggart: that one is a static lib, did you try `dumpbin /symbols ...`?

**Comment by ctaggart** [comment]
@vadimcn, that would explain it.  `dumpbin /symbols` does show the functions that the linker complains about. I'm still not sure why I can't link, but I'll now take a closer look at static vs dynamic dependencies with the `"-Wl,-Bstatic"` and  `"-Wl,-Bdynamic"` options being passed in to see if I can figure out [these errors](https://gist.github.com/ctaggart/0a2676c24844890c161d6e5720a6b91f).

**Comment by vadimcn** [comment]
I'd try setting `RUSTFLAGS=-Clink-arg=-v` to see what switches gcc gives to ld.
