### ISSUE TITLE
install.sh not marked executable in windows rustup packages

### ISSUE THREAD

**Issue by rillian** [rust-lang/rust#42205]
Trying to repackage today's nightly rust I hit a permission error because the `install.sh` script included with the published packages used by rustup is no longer marked executable for windows targets. It's still executable for macOS.

I an work around by passing it to `/bin/sh` but the inconsistency surprised me and I wanted to make sure it was intentional. The documentation still refers to invoking `install.sh` directly.

**Comment by rillian** [comment]
@Keruspe Thanks for fixing the sysconfdir issue. Any idea what's changed with this one?

**Comment by alexcrichton** [comment]
I believe this is a dupe of https://github.com/rust-lang/rust/issues/42121, so closing in favor of that, but thanks for the report of course!
