### ISSUE TITLE
Add error codes for all errors

### ISSUE THREAD

**Issue by Susurrus** [rust-lang/rust#42229]
This is related to work for adding explanations for all errors (#32777) and updating all errors to the new error format (#35233). Unfortunately not all errors have error codes. This is a tracking issue for those errors. I'd think eventually we'd want error codes for all errors so that they're easy to reference.

- [x] Field unknown: `attempted access of field _ on type _, but no field with that name was found`
- [x] Doesn't live long enough: `_ does not live long enough`
- [x] Temporary doesn't live long enough: `borrowed value does not live long enough`
- [x] Better mutability: `cannot borrow immutable borrowed content _ as mutable`
- [x] Type unknown: `the type of this value must be known in this context`
- [x] Non-scalar cast: `non-scalar cast: _ as _`
- [x] No associated item: `no associated item named _ found for type _ in the current scope`

cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Ah nice, I'll work on it then!

**Comment by kennytm** [comment]
@Susurrus (meta) you can turn those `[ ]` into checkboxes by making them a list. 

```markdown
...

- [ ] like 
- [ ] this

...
```

- [ ] like 
- [ ] this

**Comment by GuillaumeGomez** [comment]
All done in here!

**Comment by Susurrus** [comment]
Awesome, thanks for your hard work on all these changes @GuillaumeGomez!
