### ISSUE TITLE
Ampersand rendered incorrectly in rust playground.

### ISSUE THREAD

**Issue by moxian** [rust-lang/rust#42231]
In https://play.rust-lang.org/ ampersands are rendered as thin tall black rectangles - see http://i.imgur.com/7EDtQD9.png

This sounds exactly like #24355, but this time in playground rather than in rust docs. Would it be feasible to apply the same fix here (forbid usage of local font)?

Win7, Firefox 53.0.3 64 bit here.

**Comment by kennytm** [comment]
Playpen issues should be filed at https://github.com/rust-lang/rust-playpen.

This sounds like the same as rust-lang/rust-playpen#47 though.

**Comment by moxian** [comment]
Sorry, the abundance of rust repos is confusing. Will post to rust-playpen.
And, yes, that is the same issue.
