### ISSUE TITLE
Spans for errors in try operator expressions are not great

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#42234]
E.g.,

```
error: the type of this value must be known in this context
   --> src/librustc_save_analysis/sig.rs:281:39
    |
281 |             let generics: Signature = generics.make(offset + text.len(), id, scx)?;
    |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

the expression with unknown type is the variable use `generics`, but the error highlight covers the entire sub-expression of `expr?`. I assume this is due to us doing something sub-optimal with the spans here in the HIR lowering.

**Comment by aturon** [comment]
@nrc is worried that similar issues are arising with other desugarings, i.e. that this might be an across-the-board regression. Worth investigating.

**Comment by nikomatsakis** [comment]
Standalone example:

```rust
fn foo() -> Result<(), ()> {
    let x = None;
    Ok(x.unwrap().make()?)
}

fn main() { }
```

gives

```
rustc 1.17.0 (56124baa9 2017-04-24)
error: the type of this value must be known in this context
 --> <anon>:3:8
  |
3 |     Ok(x.unwrap().make()?)
  |        ^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

**Comment by nikomatsakis** [comment]
triage: P-medium

Doesn't seem like a "stop everything" sort of problem, but would be good to figure it out. However, it does not appear to be a regression: e.g., the above test case behaves the same in 1.16.0 as well.
