### ISSUE TITLE
The compiler counts moving inside dead if branch

### ISSUE THREAD

**Issue by vasily-kirichenko** [rust-lang/rust#42243]
```rust
fn main() {
    let v = vec![1, 2, 3];
    if false {
        let _x = v;
    }

    println!("{:?}", v);
}
```
results with
```
error[E0382]: use of moved value: `v`
 --> src\main.rs:9:22
  |
6 |         let _x = v;
  |             -- value moved here
...
9 |     println!("{:?}", v);
  |                      ^ value used here after move
  |
  = note: move occurs because `v` has type `std::vec::Vec<i32>`, which does not implement the `Copy` trait
```
However the moving is done in a dead if branch, known at compile time.

**Comment by Gankro** [comment]
This is expected/correct behaviour. Many of our analyses assume the input source has been completely cleaned of all junk like unused-mut and dead-code. Anything else would just slow them down for no real benefit.

More broadly this is sometimes useful for people learning/exploring the language. They can insert garbage branches to emulate a complex function and we won't "outsmart" them.

**Comment by vasily-kirichenko** [comment]
I see, it's by design (what those tumb downs could possibly mean in this repo, btw?)
