### ISSUE TITLE
format_args appears to be unusable

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#42253]
This appears to reproduce across stable/beta/nightly, and basically makes `format_args!` unusable as far as I can tell. Nothing I've managed to pass in has compiled, though I have not experimented extensively. I've also included the expanded code (`rustc -Zunstable-options --pretty=expanded`) which shows why this is the case.

```rust
fn a() {
    let a = 10;
    let msg = format_args!("{}", a);
}
```

fails with:

```
error: borrowed value does not live long enough
 --> test.rs:3:36
  |
3 |     let msg = format_args!("{}", a);
  |                            ----    ^ temporary value dropped here while still borrowed
  |                            |
  |                            temporary value created here
4 | }
  | - temporary value needs to live until here
  |
  = note: consider using a `let` binding to increase its lifetime
```

expanded:
```rust
fn a() {
    let a = 10;
    let msg =
        ::std::fmt::Arguments::new_v1({
                                          static __STATIC_FMTSTR:
                                                 &'static [&'static str] =
                                              &[""];
                                          __STATIC_FMTSTR
                                      },
                                      &match (&a,) { // I believe the problem is here
                                           (__arg0,) =>
                                           [::std::fmt::ArgumentV1::new(__arg0,
                                                                        ::std::fmt::Display::fmt)],
                                       });
}
```

**Comment by sfackler** [comment]
format_args! works fine as long as the value is passed directly into whatever's going to consume the `fmt::Arguments`.

**Comment by Mark-Simulacrum** [comment]
Could you give an example? I'm not quite sure I follow.

**Comment by sfackler** [comment]
https://github.com/rust-lang-nursery/log/blob/master/src/macros.rs#L44

or any of the in-tree usage:

https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=format_args%21&type=

**Comment by Mark-Simulacrum** [comment]
Hm, okay. I'll close this then; I don't think we need to do anything in that case.

**Comment by piegamesde** [comment]
Please reopen. I'd really like to have the option to store `fmt::Arguments` in a variable without running into these lifetimes issues.

A selection people who ran into this as well:

- https://docs.rs/fern/0.6.0/fern/struct.FormatCallback.html
- https://stackoverflow.com/questions/56304313/cannot-use-format-args-due-to-temporary-value-is-freed-at-the-end-of-this-state
- https://users.rust-lang.org/t/using-format-args-and-log-builder/22695
