### ISSUE TITLE
configure's config.mk ignores some fields during parsing

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#42255]
grepping for CFG_ in config.mk after running ./configure yields the following, after removing those that rustbuild currently looks for. The rest should either be removed from configure itself (since creating them is pointless) or parsed into rustbuild.

cc @rust-lang/infra 

```
CFG_LOCALSTATEDIR
CFG_DATADIR
CFG_INFODIR
CFG_ANDROID_CROSS_PATH
CFG_NACL_CROSS_PATH
CFG_EXTRA_FILENAME
CFG_CURL
CFG_DISABLE_VALGRIND_RPASS
CFG_SRC_DIR_RELATIVE
CFG_BUILD_DIR
CFG_OSTYPE
CFG_CPUTYPE
CFG_NACL_CROSS_PATH
CFG_USING_LIBCPP
```

**Comment by cuviper** [comment]
> yields the following, after removing those that rustbuild currently looks for.

A lot of those remaining in your list are parsed [here](https://github.com/rust-lang/rust/blob/f89d8d184490ecb3cf91f7b6bb7296d649f931ba/src/bootstrap/config.rs#L478).

**Comment by Mark-Simulacrum** [comment]
Ah.. yeah. I'm not sure what went wrong; I've updated the list in the original comment. I suspect I started deleting things that I should've kept and keeping things that should've been deleted.

The current list was produced with this command:
```
for l in `rg CFG_ config.mk | awk '{ print $1 }'`; do rg -q $l src/bootstrap/ || echo "$l" ; done
```

**Comment by Mark-Simulacrum** [comment]
Nominating this for discussion at the infra meeting -- I want to decide on a direction here. Do we need a deprecation cycle for options to configure?

**Comment by cuviper** [comment]
For Fedora, I use `--disable-option-checking` because the rpm `%configure` macro sets a lot of options that aren't known here.  So at least from that perspective, changing some options from "known but useless" to "unknown and ignored" doesn't make any difference. :)

**Comment by aidanhs** [comment]
There are others like `--dist-host-only` which aren't on your list but (last time I checked) had their meaning lost in a refactoring while the makefiles still existed.
