### ISSUE TITLE
Semicolon is unnecessary after `use prefix::{a, b, c}`

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#42256]
```rust
use prefix::{a, b, c}; // <- Hmm, why `;` is actually here?
```

No other curly-braced items require (or allow) semicolons after them. Compare:
```rust
#![allow(unused)]

macro_rules! m {
    () => { /*something*/ }
} 

struct S1;
struct S2(u8);
struct S3 { a: u8 } // No semicolon

m!();
m!{} // No semicolon

// No semicolon
trait Tr {}
enum E {}
extern "C" {}
/* etc */

use std::mem;
use std::{vec}; // Semicolon?!

fn main() {}
```

The syntax was implemented back in 2012 by @catamorphism without much discussion :)
See https://github.com/rust-lang/rust/issues/1426 and https://github.com/rust-lang/rust/commit/9dc59e15061827122dc0f08d3f66acd17ba329dc for details.

Proposal:
Make the semicolon optional marginally improving consistency and reducing syntactic noise.
```rust
use prefix::{a, b, c} // OK
use prefix::{a, b, c}; // OK too
```

**Comment by qnighy** [comment]
To me it seems like this kind of construct.

```rust
struct Point {
    x: i32,
    y: i32,
}
static ORIGIN : Point = Point {
    x: 0,
    y: 0,
};
```

Here curly braces are a part of an expression. The list importer looks like a part of a path too, although it isn't actually.

Blocks in expr-stmt would be an exception, but list importer seems to me more like a "one-liner" kind.

**Comment by est31** [comment]
I think allowing no ; after braces in use would increase inconsistency, not decrease it, as often you are grouping use declarations at the start of the file, and you will be getting lines with semicolons and lines without.

All the other examples of macro and struct declarations quoted are in most cases multiline, while use declarations are in many cases single line.

**Comment by xfix** [comment]
My interpretation is that this syntax is comparable to brace expansion in shell languages. For instance, in shells you can write this.

```sh
rm dir/{a,b,c}
```

However, you can also write this.

```sh
rm dir/{a,b,c}/file
```

As in, braces aren't part of statement or so, but rather part of path component. Considering the no semicolon rule is about statements, this is consistent. Here is an example of statement ending with a semicolon.

```rust
struct Structure {}

const CONSTANT: Structure = Structure {};
```

It's the `const` rule that requires a semicolon, not `Structure {}` expression.

**Comment by steveklabnik** [comment]
I am pretty sure this would require an RFC; @rust-lang/lang what do you say?

**Comment by nikomatsakis** [comment]
I think this would require an RFC, yes. I'm also (personally) not keen on it. I find it hard to enumerate exactly *why* but I definitely expect a `;` here. I guess I expect the `;` to not be required for things of the form `keyword Name { ... }` (e.g., `struct`, `enum`, `trait`). I don't consider a `use` statement to have that form.

**Comment by nikomatsakis** [comment]
(Well, I guess it's a grey area for the RFC; we have sometimes made small tweaks to the grammar without RFCs, or have considered doing so. I'm not sure if that's best practices or not though, myself.)

**Comment by joshtriplett** [comment]
I believe that if `use foo;` requires a semicolon, `use foo::{a,b,c};` should as well. That we *can* infer the semicolon does not mean we *should*.

**Comment by withoutboats** [comment]
I don't think we should do this.

I think its good to compare the syntax here with struct:

```rust
struct Foo;
struct Foo { }
```

A `use` isn't replacing a semicolon with a block: if it were, you would write `use foo::bar::;` instead of `use foo::bar;`. Instead, its replacing an ident with a block. I agree with @xflix's interpretation of this grammar.

**Comment by petrochenkov** [comment]
Looks like there's not enough interest, closing.
