### ISSUE TITLE
IntoIterator and FromIterator say "module level documentation" but link to traits

### ISSUE THREAD

**Issue by daboross** [rust-lang/rust#42267]
At https://github.com/rust-lang/rust/blob/master/src/libcore/iter/traits.rs#L112 and https://github.com/rust-lang/rust/blob/master/src/libcore/iter/traits.rs#L220, there's text:

```
See the [module-level documentation] for more.
```

However, the links go to `trait.FromIterator.html` and `trait.IntoIterator.html`.

Would it be an alright change to have these say `See the [trait-level documentation] for more information.` instead?

**Comment by GuillaumeGomez** [comment]
I think it's the opposite: it should really link to the iterator module level, not to the traits.

**Comment by steveklabnik** [comment]
Yes, I second @GuillaumeGomez here

**Comment by rap2hpoutre** [comment]
Ok, I could make a PR (I'm happy once again to be mentored!). Just to be sure before fixing link: does the "module-level" refers to https://doc.rust-lang.org/stable/std/iter/ (i.e replacing `trait.IntoIterator.html` and `trait.FromIterator.html` by `index.html` in code comment)?

**Comment by steveklabnik** [comment]
You did it right 👍

**Comment by rap2hpoutre** [comment]
Should we close this issue?

**Comment by GuillaumeGomez** [comment]
Yes!
