### ISSUE TITLE
error: internal compiler error: src/librustc_const_eval/pattern.rs:283: encountered errors lowering pattern

### ISSUE THREAD

**Issue by U-007D** [rust-lang/rust#42285]
I was trying to do something admittedly a little weird.  1) `match foo.into() { }` where `foo` is `Into<String>`. 2) Declare a const empty string to avoid creating a local temporary to match against (defined in a different module): `pub const EMPTY_STRING: String = String::new();`.

The offending code:
```
pub struct HexByteString(String);

impl HexByteString {
    pub fn new<T: Into<String>>(init_value: T) -> Result<HexByteString> {
        match init_value.into() {
            consts::EMPTY_STRING => Err(Error::EmptyValue(msgs::ERR_EMPTY_VALUE.to_string())),
            s @ _ => Ok(HexByteString(s)),
        }
    }
}
```

**Comment by kennytm** [comment]
Reduced:

```rust
const EMPTY_STRING: String = String::new();

fn main() {
    let init_value = "".to_owned();
    if let EMPTY_STRING = init_value {}
}
```

ICE happens since 1.18 (no ICE on 1.17, only compile-error).

**Comment by Mark-Simulacrum** [comment]
Bisected to 23de823e93dc19ef1b9cb65b48860a892cd6ff18 -- #41408, cc @eddyb

**Comment by eddyb** [comment]
People keep using `const fn` and expecting it to work with patterns. The lack of an ICE before was purely an accident. I've tried to fix this but the only real solution in sight is actually miri.
I hear @oli-obk is working on it, though!

**Comment by Mark-Simulacrum** [comment]
Same problem as https://github.com/rust-lang/rust/issues/38180.
