### ISSUE TITLE
Document compile_fail for doc tests

### ISSUE THREAD

**Issue by clarcharr** [rust-lang/rust#42288]
You can mark doctests as `compile_fail` but this isn't actually documented anywhere in the Rust book, even though it should be.

**Comment by frewsxcv** [comment]
`should_panic` is documented, `compile_fail` is not

https://doc.rust-lang.org/book/documentation.html#running-documentation-tests

**Comment by clarcharr** [comment]
Updated the OP.

**Comment by steveklabnik** [comment]
probably part of https://github.com/rust-lang/rust/issues/42322

**Comment by kennytm** [comment]
There is also ` ```test_harness `, currently only used in [The Book second edition](https://github.com/rust-lang/book/blame/325c3da0814f44916bef00ff225f934f2d613203/second-edition/src/ch13-02-iterators.md#L97).

**Comment by clarcharr** [comment]
Is there actually a way for people to make `compile_fail` tests outside of documentation for non-rustc crates?

**Comment by Mark-Simulacrum** [comment]
The compiletest crate will allow writing them.

**Comment by clarcharr** [comment]
@Mark-Simulacrum makes sense! To me it seems reasonable that you'd be able to create a test using an attribute like this:

```
#[compile_fail]
fn bad() {
    fn my_clone<T>(v: Vec<T>) -> Vec<T> {
        v.clone()
    }
}
```

Which would cover most use cases. To me it seems like this inconsistency in doc / other tests should be either addressed or more properly documented.

**Comment by frewsxcv** [comment]
There is a PR open for this: https://github.com/rust-lang/rust/pull/43949.

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/43949 fixed this!
