### ISSUE TITLE
rustdoc: comments in doc code samples are invisible when viewing in mobile safari

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/rust#42290]
It seems when viewing a rustdoc rendering from Mobile Safari on an iPad, the comments in code samples are invisible.

iPad, mobile safari:

![rustdoc ipad](https://cloud.githubusercontent.com/assets/5217170/26532798/66db61e6-43d0-11e7-8390-e9696944f55b.PNG)

For comparison, Windows 10, Firefox:

![rustdoc firefox](https://cloud.githubusercontent.com/assets/5217170/26532799/66e2e72c-43d0-11e7-81e4-4ccb046e948c.PNG)

I've confirmed the same rendering issues happen when rendered with `rustdoc 1.19.0-nightly (28fd1e519 2017-05-27)`.

**Comment by GuillaumeGomez** [comment]
I'll take a look.

**Comment by GuillaumeGomez** [comment]
I tried with iOS 8.1 and 10.2 on iPad, everything worked fine.

**Comment by QuietMisdreavus** [comment]
Turns out, this was not the fault of iOS! I have 1Blocker on my iPad, and one of the sections of rules it has is a spot to hide article comments, including elements with the class "comment", which these comments use. By reloading without the content blockers (and ultimately digging into the 1Blocker settings and turning off the ".comment" rule) the comments show up as intended.
