### ISSUE TITLE
Slice patterns don't work well with ref mut

### ISSUE THREAD

**Issue by clarcharr** [rust-lang/rust#42291]
Minimal example: https://is.gd/40m1am

```rust
#![feature(slice_patterns)]
fn main() {
    let mut buf = [0, 1];
    let [ref mut a, ref mut b] = buf;
}
```

This will complain about multiple mutable borrows, even though it should be valid.

**Comment by Stebalien** [comment]
Noted in https://github.com/rust-lang/rust/issues/8636#issuecomment-29184137 (but may deserve a separate bug report?).

(FYI, slice patterns are unstable for a reason; they're pretty buggy at the moment).

**Comment by mikhail-m1** [comment]
should be closed after MIR borrowck will be by default
