### ISSUE TITLE
Missing parentheses around trait object in rustdoc

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#42299]
```rust
pub fn f(_: &(ToString + 'static)) {}
```

This function is documented as:

> ![selection_055](https://cloud.githubusercontent.com/assets/1940490/26559735/46f186a8-4466-11e7-8c34-43188706b6b9.png)

The parentheses are missing and the function would not compile without them:

```
error[E0178]: expected a path on the left-hand side of `+`, not `&ToString`
 --> src/main.rs:1:13
  |
1 | pub fn f(_: &ToString + 'static) {}
  |             ^^^^^^^^^^^^^^^^^^^ help: try adding parentheses: `&(ToString + 'static)`
```

**Comment by GuillaumeGomez** [comment]
Well found! Taking a look.
