### ISSUE TITLE
Unterminated string literal in Some('')

### ISSUE THREAD

**Issue by Z34O** [rust-lang/rust#42325]
if str.chars().nth(index) != Some('') {
      //Returns an error: unterminated string literal ('\')
}

**Comment by kennytm** [comment]
What do you want to check? There is no such thing as an empty char.

**Comment by nagisa** [comment]
This error is correct. You may not have an empty char literal. Closing.

**Comment by Z34O** [comment]
Oh alright I thought it was a bug, it was showing '/' instead of ''
