### ISSUE TITLE
Stop writing everything to STDERR

### ISSUE THREAD

**Issue by legolord208** [rust-lang/rust#42339]

**Comment by Mark-Simulacrum** [comment]
Most output in general goes to stderr since it's warning/error related (and as such should go to stderr); could you specify what output you would expect not to be on stderr?

**Comment by Stebalien** [comment]
Note: Both gcc and clang do the same.

**Comment by legolord208** [comment]
Well, this program does the complete opposite. "Compiling ..." messages go to STDERR, while the errror details go to STDOUT.

**Comment by sfackler** [comment]
The issue description says that "everything" apparently goes to STDERR - is that not the case then?

**Comment by legolord208** [comment]
Sorry, that was overstating. Most things are written to STDERR, while the things that SHOULD be written there are written to STDOUT.

So, for example

`Compiling some_crate v1.2.3` (STDERR)  
```
[error] Can't eat cookie since cookie is already consumed
  |cookie.eat();
2 | cookie.eat();
   ^^^^^^^^^^^^^
```
(STDOUT)

**Comment by Mark-Simulacrum** [comment]
I can't seem to reproduce that behavior; perhaps it's not coming from the compiler? `cargo build 2>/dev/null` shows me no output (despite there being compiler errors). Could you tell us the exact commands you are running?

**Comment by legolord208** [comment]
~~I used [stderred](https://github.com/sickill/stderred), which showed everything except that as red. Perhaps I was wrong though~~

Exactly. `2>/dev/null`. 2 is STDERR. I might have been wrong when I stated not everything was STDERR though.

**Comment by Mark-Simulacrum** [comment]
Sure, but all build output for my build wasn't supposed to go to stdout; it was errors and progress messages that shouldn't be on stdout by convention; what did you expect to be on stdout?

**Comment by legolord208** [comment]
I expect `Compiling ...` messages to be on STDOUT.

**Comment by Mark-Simulacrum** [comment]
Ah. I'm not sure that's something we'd want, but you'll need to file an issue at https://github.com/rust-lang/cargo about that; those messages don't come from the rust compiler itself, but rather Cargo. I'd personally not want the `Compiling` messages on stdout since then piping stdout into a file (currently, program output) would become more complex.

**Comment by legolord208** [comment]
Yeah, you're right. Sorry. I'm an idiot.
