### ISSUE TITLE
Procedural derive macros on traits

### ISSUE THREAD

**Issue by dylanede** [rust-lang/rust#42352]
I would like to be able to write

```rust
#[derive(MyTrait)]
trait Foo {
    fn foo();
}
```

This doesn't seem to be in the feature set of procedural macros at the moment. Are there any plans for adding this? At the moment I get the error "proc-macro derives may only be applied to struct/enum items". As far as I can see there don't seem to be any fundamental differences in supporting this than the existing support for structs and enums.

**Comment by abonander** [comment]
You may be interested in [procedural attribute macros](https://doc.rust-lang.org/nightly/unstable-book/language-features/proc-macro.html#attribute-like-procedural-macros), which can be applied to any item.

**Comment by Mark-Simulacrum** [comment]
Yes, you'll need to use a proc macro for this. Derive is intended for adding Traits to structs/enums/unions(?) and so won't work for this; and I don't think we want it to -- if you disagree, this would need an RFC -- please follow the process here https://github.com/rust-lang/rfcs#before-creating-an-rfc.
