### ISSUE TITLE
Taking the address of a method on a trait object

### ISSUE THREAD

**Issue by dylanede** [rust-lang/rust#42351]
If I have a trait object, there doesn't appear to be a way at the moment of taking the address of a method on it, i.e. it would be nice to be able to do

```rust
trait Foo {
    fn foo(&self);
}
let x: &Foo = unimplemented!();
// unsafe fn as it is no longer tied to the underlying type.
let foo_for_x: unsafe fn(*const Foo) = x.foo; // error: attempted to use method as a value
```

Is there any way of achieving this (getting the address of a method from a trait object or its vtable) in Rust at the moment?

**Comment by petrochenkov** [comment]
You can use UFCS if you can write the type of `x` in `x.foo`
```rust
trait Foo {
    fn foo(&self);
}

impl Foo for u8 {
    fn foo(&self) {}
}

fn main() {
    let foo_foo_explicit = <Foo as Foo>::foo;
    let foo_foo_shortcut = <Foo>::foo;
    let foo_u8 = <u8 as Foo>::foo;
    println!("foo_foo_explicit {:?}", foo_foo_explicit as usize);
    println!("foo_foo_shortcut {:?}", foo_foo_shortcut as usize);
    println!("foo_u8 {:?}", foo_u8 as usize);
}
```
```
rustc 1.19.0-nightly (e0cc22b4b 2017-05-31)
foo_foo_explicit 94874093985488
foo_foo_shortcut 94874093985488
foo_u8 94874093985536
```
It looks like `<Foo>::foo` returns the address of some kind of shim though, not the address of the method on the actual underlying type (which is unknown without `x`).

**Comment by eddyb** [comment]
@petrochenkov Btw, if you cast to `fn(_)` instead, you get hex pointer formatting.

**Comment by Mark-Simulacrum** [comment]
I believe @petrochenkov's comment answers this question, closing.
