### ISSUE TITLE
 "File name too long" error at 4096 bytes

### ISSUE THREAD

**Issue by vandenoever** [rust-lang/rust#42350]
Rust cannot handle long paths on Linux. It fails on paths longer than 4096 bytes.

```rust
use std::fs::{create_dir, read_dir};
use std::env::{current_dir, set_current_dir};

fn main() {
    let dir = current_dir().unwrap();
    let name = "a";
    for i in 0..2200 {
        if i % 100 == 0 {
            println!("Create dir at level {}.", i);
        }
        let d = current_dir().unwrap();
        read_dir(d).unwrap(); // fails for long paths
        create_dir(name).unwrap();
        set_current_dir(name).unwrap();
    }
}
```

**Comment by vandenoever** [comment]
This is a limitation of the operating system. On Linux, you can find out the maximal length for a relative path with `getconf PATH_MAX /` on the command-line or with the POSIX function `pathconf("/", _PC_PATH_MAX)`.

**Comment by iology** [comment]
Coming from BurntSushi/walkdir/23

I hope you reopen this issue since the doc doesn't specify the detailed implementation of this function. Maybe there could be an improvement? Have people already discussed this topic somewhere?
