### ISSUE TITLE
Incorrect hyperlink in API doc comment?

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#42373]
someone in IRC mentioned [this](https://github.com/rust-lang/rust/blob/2bdf368bdec589c689950e88eec973cd5df658fc/src/libstd/sys_common/poison.rs#L101) should actually point to [`PoisonError::into_inner`](https://doc.rust-lang.org/std/sync/struct.PoisonError.html#method.into_inner). i would fix it myself, i don't really understand what the sentence means that uses that link (but i'm also pretty tired).

**Comment by GuillaumeGomez** [comment]
It doesn't seem logical to me: this is returned from a `Mutex` method, so it's normal that we're talking about the `Method::into_inner` method, no?

**Comment by steveklabnik** [comment]
So, https://doc.rust-lang.org/stable/std/sync/struct.Mutex.html#method.into_inner *is* how you get a `LockResult`, but that sentence is trying to point to `PoisonError`.

**Comment by GuillaumeGomez** [comment]
Then we just rephrase it in order to make it sound more logical. :)
