### ISSUE TITLE
Non-string format strings for assert! are pointless without warning

### ISSUE THREAD

**Issue by BenWiederhake** [rust-lang/rust#42395]
[Example](https://is.gd/HdfT8r):
```Rust
fn main() {
    let actual = 42;
    assert!(actual > 150, actual);  // Compiles, but just prints "Box<Any>" as value
    // assert_eq!(actual, 100, actual);  // Rightfully does not compile
}
```

Actual behavior: the correct panic during runtime, but with a very unhelpful error:
```
thread 'main' panicked at 'Box<Any>', <anon>:6
```

Expected behavior: any out of:
1. Fails to compile
2. Compiles with a warning with "actual" output (see above)
3. Compiles without a warning, and the output `thread 'main' panicked at '42', <anon>:6`

There does not appear to be a similar issue yet.

I propose that the compiler should throw an error, for consistency with `assert_eq!`.

## Meta

This happens independently of compiler version or configuration.  See the playpen link.  I tested it with:
- `rustc 1.19.0-nightly (4ed2edaaf 2017-06-01) / Debug`
- `rustc 1.19.0-nightly (4ed2edaaf 2017-06-01) / Release`
- `rustc 1.17.0 (56124baa9 2017-04-24) / Debug`
- `rustc 1.17.0 (56124baa9 2017-04-24) / Release`

**Comment by sfackler** [comment]
`Box<Any>` panics are not pointless - the spawning thread can downcast the `Any` to get the underlying value out.

**Comment by BenWiederhake** [comment]
Is this really used as a feature? Shouldn't then `assert_eq!` also allow it?

**Comment by sfackler** [comment]
assert_eq doesn't because it explicitly builds a string panic message: https://github.com/rust-lang/rust/blob/master/src/libcore/macros.rs#L124

**Comment by Mark-Simulacrum** [comment]
Expected behavior. If you'd like, I could see Clippy adding a lint for this, but nothing we want to do in rustc itself, I think.
