### ISSUE TITLE
Patterns documentation should explicitly state the difference between () and {} somewhere

### ISSUE THREAD

**Issue by daboross** [rust-lang/rust#42416]
This came up in the #rust-beginners IRC today - someone was unsure exactly why matching a tuple-like enum variant with `Enum::Name { field }` wasn't working, and hadn't found any reference to this in the documentation.

I think it'd be awesome if https://doc.rust-lang.org/book/patterns.html briefly touched on the difference between tuple-like things and struct-like things, and how that relates to patterns - or if it just included a note with a link to another page where tuple-struct vs. struct and tuple-enum vs struct-enum is covered more in detail.

Edit: doesn't seem like this case is really covered in https://doc.rust-lang.org/nightly/book/second-edition/ch06-02-match.html either at the moment.

**Comment by petrochenkov** [comment]
>or if it just included a note with a link to another page where tuple-struct vs. struct and tuple-enum vs struct-enum is covered more in detail

https://github.com/rust-lang/rfcs/blob/master/text/1506-adt-kinds.md

**Comment by steveklabnik** [comment]
Could you move this to https://github.com/rust-lang/book please? Thanks!

**Comment by daboross** [comment]
Thanks! Created https://github.com/rust-lang/book/issues/757.
