### ISSUE TITLE
Incorporate @raphlinus' container cheat sheet into the std::collections module docs

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/rust#42412]
The suggestion to incorporate [@raphlinus' container cheat sheet](https://docs.google.com/presentation/d/1q-c7UAyrUlM-eZyTo1pd8SZ0qwA_wYxmPZVOQkoDmH4/edit#slide=id.p) was made by @leonardo-m over on https://github.com/rust-lang/book/issues/741, and @steveklabnik and I agree that it's a better fit for the API docs rather than the book (since the book is aiming to be a narrative intro to Rust, not a comprehensive reference). 

Raph has noted that the cheat sheet is Copyright 2017 Google Inc., released under Creative Commons BY, so I don't think that should be a problem for us to incorporate as long as we note those things (but IANAL)

**Comment by nagisa** [comment]
This is documenting (read: semi-stabilises) internal implementation details which could change at any time.

**Comment by leonardo-m** [comment]
Note that cheat sheet contains some small mistakes and imprecisions.

Regarding the problem of documenting internal implementation details, when those details change, the sheet should be updated. The purpose of those images is to help a Rust programmer know what she or he is using. If you don't know those things you can't program well in Rust.

**Comment by nagisa** [comment]
Well I’m all fine with it, as long as people do not `transmute` the types/do some other black magic and then come over crying because it was “documented”.

**Comment by leonardo-m** [comment]
But I agree it's surely a risk, even if you write very well in the page that those images are not meant to be used that way, etc.

**Comment by steveklabnik** [comment]
@rust-lang/libs, should we do this or not? I share @nagisa 's concerns.

**Comment by Kixunil** [comment]
There was a [question regarding references](https://www.reddit.com/r/rust/comments/7e9id4/fat_pointers_vs_string_slices_vs_slices/) on Reddit recently. I believe this (or similar) visualization would be very helpful for beginners.

There should be a big warning about not transmuting stuff and not relying on that layout. If someone will ignore that, he will probably ignore many other things.

**Comment by huhlig** [comment]
The current version needs a touch of updating before inclusion though.

**Comment by pickfire** [comment]
This is also available in https://cheats.rs/#standard-library-types

**Comment by pickfire** [comment]
@Dylan-DPC Maybe we can label `hacktoberfest`?

**Comment by Dylan-DPC** [comment]
we normally don't label issues for hacktoberfest :P

**Comment by the8472** [comment]
std already has several pieces of documentation that exempt themselves from stability guarantees. E.g. 

* https://doc.rust-lang.org/std/net/struct.Ipv4Addr.html#method.is_reserved
* https://doc.rust-lang.org/std/fs/fn.copy.html#platform-specific-behavior

Maybe it would make sense to have a standard marker for these kinds of things. E.g. w3c specs oven have special [non-normative sections](https://www.w3.org/TR/html52/introduction.html#typographic-conventions). Similarly java docs have [special annotations for implementation notes that are subject to change](https://openjdk.java.net/jeps/8068562#Description)

**Comment by joshtriplett** [comment]
We reviewed this in today's @rust-lang/libs meeting.

This is a great piece of documentation, but it's focused on data structure internals, not on user-visible properties or uses. As a result, we don't think this is a good fit for user-focused documentation.

It might make sense to link to it from documentation about developing the standard library, but we don't want to add this to the collections documentation.

**Comment by Kixunil** [comment]
@joshtriplett perhaps the Book would be a better place? I believe that in systems language knowing about performance characteristics is just as important as knowing the API. E.g. why not just use `Option<Arc<Mutex<Vec<T>>>>` everywhere?

**Comment by carols10cents** [comment]
@Kixunil this started over at the book. From the issue text:

> The suggestion to incorporate [@raphlinus' container cheat sheet](https://docs.google.com/presentation/d/1q-c7UAyrUlM-eZyTo1pd8SZ0qwA_wYxmPZVOQkoDmH4/edit#slide=id.p) was made by @leonardo-m over on [rust-lang/book#741](https://github.com/rust-lang/book/issues/741), and @steveklabnik and I agree that it's a better fit for the API docs rather than the book (since the book is aiming to be a narrative intro to Rust, not a comprehensive reference).

**Comment by Kixunil** [comment]
OK then, adding "Write a book about professional Rust development" to my infinite TODO list. :)
