### ISSUE TITLE
Remove support for the deprecated PNaCl technology

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#42420]
Rust had nacl/PNaCl support since a while (#28355, #29289), but as Google has [recently announced](https://blog.chromium.org/2017/05/goodbye-pnacl-hello-webassembly.html) the deprecation of their pnacl technology, support for it should be removed from the compiler sooner or later.

**Comment by dsprenkels** [comment]
The following code triggers the same error on `rustc 1.21.0-nightly (d692a91fa 2017-08-04)`:

```rust
#![feature(catch_expr)]

pub struct X;

pub fn new_x() -> Result<X, ()> {
    return Ok(X);
}

fn main() {
    do catch {
        let x_result: X = new_x()?;
        Ok(())
    };
}
```

**Comment by tlively** [comment]
@est31 My understanding is that PNaCl is deprecated but NaCl is not. Does this issue suggest removing support for NaCl in addition to PNaCl? If not, how does keeping NaCl support affect #44006?

**Comment by est31** [comment]
> Does this issue suggest removing support for NaCl in addition to PNaCl?

The two terms are a bit confusing. From what I understand is that NaCl is a sandboxing technology while PNaCl is a technology that is both a sandbox around code, and a portable binary format, just like wasm. You are right, the Google blog post I've linked only refers to PNaCl.

Now rustc has a target called `le32-unknown-nacl`. That's the one I'm proposing to remove. The target itself only refers to NaCl, however its actually compiling to the PNaCl binary format (otherwise you'd need x86, ARM, MIPS variants for NaCl). I'm not the only one confused here!

Now I couldn't find any support in rustc for NaCl itself. I don't know whether a compiler needs special support for NaCl *at all*, but I suppose there is no need for special support.

I'll file a PR to remove PNaCl support and CC you.

**Comment by tlively** [comment]
Sounds good. Probably best to cc @eholk as well. Hopefully he will be able to shine some light on the PNaCl vs NaCl situation.

**Comment by eholk** [comment]
That's correct that the PNaCl deprecation announcement is specific to PNaCl.

As far as PNaCl vs NaCl, NaCl is a sandboxing technology that uses a combination of OS sandboxing techniques and assembly validation. NaCl uses the underlying CPU's native instruction set, meaning you have to provide x64, ARM, etc. if you want to support different platforms.

PNaCl is a portable format on top of NaCl. It is based on LLVM bitcode. Before running the executable, the PNaCl translator takes the bitcode and translates it into a NaCl executable that then runs under the NaCl sandbox.

I don't know the Rust PNaCl target directly, but I gather that `le32-unknown-nacl` might be better called `le32-unknown-pnacl`.

I think NaCl has gotten some use outside the browser, so I could imagine a case for still supporting NaCl in Rust. It's probably only worth doing if there are current users of it though.
