### ISSUE TITLE
Deprecate rustc-serialize attribute

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#42449]
AFAIK the attribute itself is still undeprecated. Just filing an issue to track it.

**Comment by brson** [comment]
Can this be don for 1.20?

**Comment by eddyb** [comment]
Do you mean the `RustcEncodable` and `RustcDecodable` derives? Or something else?

**Comment by brson** [comment]
@eddyb Er yes that's what I mean.

**Comment by Mark-Simulacrum** [comment]
I believe on the implementation side technically https://github.com/rust-lang/rust/blob/master/src/libsyntax_ext/deriving/mod.rs#L119 is what needs to change, but it's worth noting that the Rust compiler itself rather extensively uses these attributes: ~430 of each excluding tests currently, I believe. Maybe it is too early to do this? Or perhaps these attributes are different in some way?

**Comment by eddyb** [comment]
If the traits from the crates.io library are deprecated instead of the derives, and rustc's copy of the library is left untouched, I believe the derives will trigger the deprecation warnings.

**Comment by Geemili** [comment]
Is this still an issue?

**Comment by Centril** [comment]
Closing in favor of https://github.com/rust-lang-deprecated/rustc-serialize/issues/193.
