### ISSUE TITLE
Not all trait implementations are documented

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#42440]
When implementing traits with type parameters (with your types) for types outside your crate, these aren't documented anywhere.

For example:

```rust
pub struct A;

impl From<A> for std::io::Error {
    fn from(a: A) -> Self {
        unimplemented!()
    }
}
```

This isn't documented in my crate, and it of course can't be documented in `std`, because `std` doesn't know about my type.

**Comment by QuietMisdreavus** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/25264 (at least my understanding of that issue)
