### ISSUE TITLE
Don't rebuild LLVM on non-related changes to config.toml

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#42444]
#42429 closed https://github.com/rust-lang/rust/issues/35199; but ideally we don't want to rebuild LLVM no matter what; since that has a high overhead for changes that aren't related. See the pull request for more details (https://github.com/rust-lang/rust/pull/42429#issuecomment-306061941).

**Comment by venkatagiri** [comment]
@Mark-Simulacrum Now that https://github.com/rust-lang/cargo/pull/4125 has landed, would below solution work to fix this issue?
In `bootstrap`, set env var `CFG_LLVM_CONFIG` to `llvm-config` path specified in `config.toml` and in `rustc_llvm`, print `cargo:rerun-if-env-changed=CFG_LLVM_CONFIG`?

**Comment by Mark-Simulacrum** [comment]
Sounds reasonable! I think we'd need to be careful we only read the llvm-config path, but I believe that's true today. Would you like to make a PR?

**Comment by venkatagiri** [comment]
Yes. I will. Looking at the code again, I feel we can use the [`LLVM_CONFIG`](https://github.com/rust-lang/rust/blob/master/src/bootstrap/compile.rs#L283) env var (which points to `llvm-config` based on config.toml or custom llvm build) to trigger llvm rebuild by printing `cargo:rerun-if-env-changed=LLVM_CONFIG` and removing all changes done in #42429.
