### ISSUE TITLE
Do shallow clones of submodules in x.py

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#42442]
https://git-scm.com/docs/git-submodule#git-submodule---depth

**Comment by est31** [comment]
I think that has been tried but was abandoned because switching back to some older revision didn't work well.

**Comment by est31** [comment]
cc #42208

**Comment by Mark-Simulacrum** [comment]
Yeah, this wouldn't really work since we don't know what depth we need to get the commit we want in each submodule. I don't think this is viable -- and we should probably just close it, though if anyone has ideas I want to hear them so I'll leave it open for now.

**Comment by Mark-Simulacrum** [comment]
Closing -- this doesn't work in practice.
