### ISSUE TITLE
Proposal: UnsafeDefault

### ISSUE THREAD

**Issue by joshlf** [rust-lang/rust#42441]
Currently, we have the [`Default`](https://doc.rust-lang.org/core/default/trait.Default.html) trait that allows a type to construct a default instance of itself:

```rust
pub trait Default {
    fn default() -> Self;
}
```

I've been working on an object allocator crate, and I've found it very useful to have a similar trait that, instead of returning a value, initializes a value at a location in memory: `UnsafeDefault`:

```rust
pub unsafe trait UnsafeDefault {
    unsafe fn unsafe_default(ptr: *mut Self);
}
```

The contract is that `ptr` points to an uninitialized region of memory large enough to hold an instance of the type, and when `unsafe_default` has returned, that memory is initialized to a valid instance of the type. For example:

```rust
impl<T: UnsafeDefault> Default for T {
    fn default() -> T {
        unsafe {
            use core::mem::uninitialized;
            let mut t = uninitialized();
            Self::unsafe_default(&mut t);
            t
        }
    }
}
```

I've found `UnsafeDefault` to be a very useful primitive to have in implementing allocators - both for ergonomics and for performance. I think adding it to `core` and `std` could be very useful - especially as we try to clean up the story around custom allocators (which, in my experience, can benefit from using `UnsafeDefault` in their public APIs).

**Comment by sfackler** [comment]
This sounds a lot like a special case of the Placer/placement new stuff?

**Comment by joshlf** [comment]
@sfackler It's similar, but it differs in two key ways:
* There's no [`Placer`](https://doc.rust-lang.org/std/ops/trait.Placer.html) requirement. In the design of the placement stuff, the `Placer` is, e.g., the heap, which in turn produces a [`Place`](https://doc.rust-lang.org/std/ops/trait.Place.html) (e.g., via allocation). In what I'm proposing, the memory location already exists, but is uninitialized.
* While some notion of finalization should probably be supported in case a panic occurs in the middle of a call to `unsafe_default` (or, alternatively, `unsafe_default` should return a bool indicating whether it succeeded, and is responsible for ensuring that it cleans up any intermediate state if it returns false, and can never panic), the placement stuff goes further and has [`InPlace`](https://doc.rust-lang.org/std/ops/trait.InPlace.html) return an [`Owner`](https://doc.rust-lang.org/std/ops/trait.InPlace.html#associatedtype.Owner). In my case, the code calling `unsafe_default` is already the owner, so creating a second owner doesn't make any sense.

Another possibility is that something like `UnsafeDefault` could actually be a lower-level primitive on top of which the placement stuff is implemented.

**Comment by joshlf** [comment]
Actually, I realized that the clean-up requirement isn't even an issue. Since `unsafe_default` is an `unsafe` function, it's its responsibility to ensure [exception safety](https://doc.rust-lang.org/nomicon/exception-safety.html). For values without any custom drop logic (e.g., most primitives), this isn't a concern. For values with a custom drop, either:
* Do all initialization that *could* unwind in safe local variables before moving them into the memory being initialized (this way, any unwinding will cause all drops to be called, and writing the memory itself is guaranteed not to unwind, so it's safe to write the memory, `mem::forget` the temporary values, and return)
* Initialize directly into the memory (e.g., don't use safe local variables, so the compiler won't know there's anything to drop in the case of an unwind) but catch the unwind (`catch_panic`) and handle it

Even if there's a flaw in my logic for how this might be done safely, the point is that it's Not Rust's Problem (TM) since `unsafe_default` is `unsafe`. So long as there exists *some* way of doing it correctly (and obviously there does - stdlib code does this all the time) we're OK.

**Comment by rkruppe** [comment]
Can you elaborate some more on the motivation for having this trait? It seems to apply only to relatively narrow circumstances (only when you want to initialize some memory to `Default::default`, which isn't *terribly* common in my experience). Furthermore, even in those circumstances it seems to me that combining the existing trait with the placement protocol works perfectly (and is more general).

For the latter, note that `Placer` doesn't have to be "the heap" or anything so general, and a `Place` doesn't have to be tied to allocating memory right in that moment. Both could just be newtype wrappers around a pointer you already have. This allows writing something like like `PointerPlacer(ptr) <- Default::default()` and that should be (1) equally fast, (2) at least as convenient, and (3) easier to make exception-safe (even if that is "Not Rust's Problem", someone has to do it and it's good if they don't have to work as hard for it).

**Comment by joshlf** [comment]
@rkruppe I realized that I've been letting this languish. Your points are valid, and the use case that motivated this has subsided, so I think it's time to admit that this is no longer a well-motivated proposal. Closing.
