### ISSUE TITLE
Rust AVR backend

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#42450]
Tracking issue so we have something to link to.

cc @dylanmckay @shepmaster. What's the status today?

**Comment by shepmaster** [comment]
With the LLVM 4 merge, changes we make to LLVM are easier to circle back into Rust for testing, but there's a lot of work to be done to address mis-generated code.

We are tracking what we know in the [avr-rust issues](https://github.com/avr-rust/rust/issues). We also have a set of patches that have been applied to LLVM which we have cherry-picked into our fork of Rust's fork of Emscripten's fork of LLVM.

Most of the work now centers around trying to compile a piece of code and figuring out why it didn't.

We have also set up [a gitter](https://gitter.im/avr-rust/Lobby) for communication in addition to the issue tracker.

Any other details you'd be interested in?

**Comment by brson** [comment]
Thanks @shepmaster. Seems like there's enough bugs left for the timeline to merge into Rust to be indeterminate.

**Comment by shepmaster** [comment]
I'm going to close this in favor of #44052; which will likely spawn another tracking issue in the future!
