### ISSUE TITLE
When does LineWriter flush?

### ISSUE THREAD

**Issue by 8573** [rust-lang/rust#42468]
It seems unclear to me from [its documentation][1] when exactly
`std::io::LineWriter` will flush.

The documentation of the struct says that it flushes "whenever a
newline […] is detected", but the existence and documentation of the
constructor `with_capacity` suggests that `LineWriter` has an internal
buffer of some set capacity.

What happens if a line written to the `LineWriter` exceeds the
capacity of the internal buffer? Can `LineWriter` also flush *before*
a newline is detected?

[1]: <https://doc.rust-lang.org/std/io/struct.LineWriter.html>

**Comment by retep998** [comment]
Yes, `LineWriter` will also flush whenever the internal buffer is full (1024 bytes last I checked).
