### ISSUE TITLE
Converting Box<T> to Rc<T>, Arc<T>, ...

### ISSUE THREAD

**Issue by Yoric** [rust-lang/rust#42478]
As far as I can gather, the stdlib does not provide any generic way to upgrade a `Box<T>` to `Rc<T>`, `Arc<T>`, etc. This would be useful.

**Comment by CensoredUsername** [comment]
Is there any reason you can't just do `Rc::new(*boxed_value)`? As far as I'm aware the memory layouts for these types are incompatible (`Rc<T>` doesn't have a `Box<T>` internally) so such a method wouldn't have any advantage over just doing it that way.

**Comment by Yoric** [comment]
No, you are right. For some reason, I assumed that this wouldn't work with unsized types.

My bad.

**Comment by qnighy** [comment]
I don't think it works with unsized types.

```rust
use std::rc::Rc;
use std::fmt::Debug;

fn main() {
    // convert to Rc, then unsize (OK)
    let b1 = Box::new((42, 82));
    let p1 : Rc<Debug> = Rc::new(*b1);

    // unsize, then convert to Rc (fails)
    let b2 : Box<Debug> = Box::new((42, 82));
    let p2 = Rc::new(*b2); // Error
}
```

**Comment by BrandonDyer64** [comment]
`Rc` includes an `impl From<Box<T>>`

```rust
use std::rc::Rc;
use std::fmt::Debug;

fn main() {
    // unsize, then convert to Rc
    let b2: Box<dyn Debug> = Box::new((42, 82));
    let p2: Rc<dyn Debug> = Rc::from(b2);
}
```
