### ISSUE TITLE
rustdoc: Add src links to trait implemenation section

### ISSUE THREAD

**Issue by jrmuizel** [rust-lang/rust#42488]
It would be very handy to provide links to the implementation source for each implementation of a trait. For example, on https://doc.rust-lang.org/std/io/trait.BufRead.html it's not clear where the implementation of impl<'a, B: BufRead + ?Sized> BufRead for &'a mut B lives.

**Comment by ollie27** [comment]
Dupe of #39938?

**Comment by Mark-Simulacrum** [comment]
Agreed; closing as a duplicate.
