### ISSUE TITLE
Add information on how to run builds to CONTRIBUTING.md

### ISSUE THREAD

**Issue by jrmuizel** [rust-lang/rust#42484]
CONTRIBUTING.md talks about producing builds but not how to use them. i.e. do they need to packaged and installed someplace? Where is this? How do use multiple ones at the same time? etc.

**Comment by QuietMisdreavus** [comment]
So right now, the CONTRIBUTING.md includes a little note about `rustup toolchain link <name> build/<host-triple>/<stage>`, including a link to [a section in the rustup readme](https://github.com/rust-lang-nursery/rustup.rs#working-with-custom-toolchains-and-local-builds) about the linked toolchain feature. I'll take the opportunity to expand the note into its own section, though.

**Comment by QuietMisdreavus** [comment]
I've opened up https://github.com/rust-lang/rust/pull/44194 to expand the rustup note into its own section.
