### ISSUE TITLE
Extending `match` to take notes

### ISSUE THREAD

**Issue by Yoric** [rust-lang/rust#42506]
Consider the following snippet:

```rust

enum Foo {
   Case1(Bar),
   Case2(Bar),
   Case3(Bar),
   SomethingElseEntirely
}

fn walk_through(foo: &Foo) {
  match *foo {
    Case1(ref bar) => { println!("This is Case1"); some_complex_expression(bar) }
    Case2(ref bar) => { println!("This is Case2"); some_complex_expression(bar) }
    Case3(ref bar) => { println!("This is Case3"); some_complex_expression(bar) }
    SomethingElseEntirely => ...
  }
}
```

Here, the branches attached to `Case1`, `Case2`, `Case3` are essentially the same. Indeed, the only difference is in the `println`. However, this difference is sufficient that we cannot merge the branches.

In this specific case, we could rewrite the shared part of the code as a closure or a function, but this is not always possible/desirable. For instance, when writing an AST serializer, there may be dozens of `enum` cases and moving the code to a closure may hurt readability.

What I suggest here is some kind of construction that would let me write:

```rust
fn walk_through(foo: &Foo) {
  match *foo {
    Case1(ref bar) where let message = "This is Case1" |
    Case2(ref bar) where let message = "This is Case2" |
    Case3(ref bar) where let message = "This is Case3" => {
      println!("{}", message);
      some_complex_expression(bar)
    }
    SomethingElseEntirely => ...
  }
}
```

**Comment by Mark-Simulacrum** [comment]
I don't think I'd be opposed to the idea at least at first glance, but this is certainly a request that would require an RFC, since it extends the language in a relatively new direction.

**Comment by Yoric** [comment]
I'll try and draft one.

**Comment by steveklabnik** [comment]
Yes, this is very much an RFC thing. Thanks!
