### ISSUE TITLE
`DeprecatedStepBy<A, RangeInclusive<A>>` gives bad size hints

### ISSUE THREAD

**Issue by cuviper** [rust-lang/rust#42514]
`DeprecatedStepBy` being the old unstable `core::iter::range::StepBy`.  cc #27741

Its [`size_hint`](https://github.com/rust-lang/rust/blob/f062832b208e94f2f0f26ed7fb5c48c172069fbe/src/libcore/iter/range.rs#L446-L453) over-optimistically adds 1 to `Step::steps_between`.  That works if the step exactly lands on the end condition, a perfect multiple, but otherwise:

```rust
    let i = (0...9).step_by(2);
    let v: Vec<_> = i.clone().collect();
    assert_eq!(v.len(), 5); // OK
    assert_eq!(i.size_hint(), (5, Some(5))); // FAILED, gives `(6, Some(6))`
```

Or if the iterator is already exhausted:

```rust
    let mut i = (0...9).step_by(2);
    let v: Vec<_> = i.by_ref().collect();
    assert_eq!(v.len(), 5); // OK
    assert_eq!(i.size_hint(), (0, Some(0))); // FAILED, gives `(1, Some(1))`
```

At least it doesn't implement `TrustedLen`.

**Comment by scottmcm** [comment]
Dup of https://github.com/rust-lang/rust/issues/41477?

**Comment by cuviper** [comment]
Yep.
