### ISSUE TITLE
improve case with one named, one anonymous lifetime parameter

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#42517]
@gaurikholkar is working on a patch to address the case of conflict between one named and one anonymous lifetime parameter. Driving example (with the rough error message that we want displayed inline):

```
fn foo<'a>(x: &'a i32, y: &i32) -> &'a i32 {
                       - consider changing the type of `y` to `&'a i32`
    if x > y { x } else { y }
                          ^ this reference must have lifetime 'a
}
```

**Comment by gaurikholkar** [comment]
#43434

**Comment by gaurikholkar** [comment]
#43433

**Comment by gaurikholkar** [comment]
@nikomatsakis, we aren't handling Impls here

**Comment by estebank** [comment]
This case seems to be correctly handled now, and the other linked issues cover other improvements over this.
