### ISSUE TITLE
capture diagnostic output in queries

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#42513]
Right now, queries produce results, but as a side-effect they may issue diagnostics. For incremental compilation, if we are going to (e.g.) skip typeck, but still produce the same output, we really need to capture this output so that we can replay it.

Right now, to issue a diagnostic, you basically directly invoke methods on the session, [such as `span_err` and friends](https://github.com/rust-lang/rust/blob/f062832b208e94f2f0f26ed7fb5c48c172069fbe/src/librustc/session/mod.rs#L158-L232). When `emit()` is called, these just directly dump out to stderr.

To fix this issue, we would want to record those diagnostics. There *is* already a [diagnostics object that is created](https://github.com/rust-lang/rust/blob/f062832b208e94f2f0f26ed7fb5c48c172069fbe/src/librustc_errors/diagnostic.rs#L19-L28) (and thus can in principle be saved) -- but we'd have to find the right place to save it (in the query tables, presumably).

We also have to figure out how to recover the tcx. The easiest way to handle this would be to check the TLS for the current tcx (using `ty::tls::with()`) and record it that way. We generally discourage using TLS to get the tcx except in specific scenarios, but this may fall under that category.

I'm tagging this for mentoring without instructions. There is still some amount of pending design work here that will require experimentation. Plus, once the work is done, we'll have to figure out (separately) how to actually **save** the errors to disk and replay them etc.

**Comment by nikomatsakis** [comment]
cc @eddyb @michaelwoerister

**Comment by eddyb** [comment]
> We also have to figure out how to recover the tcx.

No need! Everything already passes `tcx.sess`, just make it work on `tcx` instead.
(If that is too cumbersome, `Session` could also do the tracking for the query engine)

**Comment by nikomatsakis** [comment]
@eddyb well, we issue diagnostics directly on the session sometimes, when the tcx is not available yet, right? I was nervous about that. At minimum, we'd have to move the methods to some new place, so that we can be sure that all existing code uses the `tcx` methods when it should.

**Comment by eddyb** [comment]
I am aware of nothing that has `&Session` but no `TyCtxt` *when the former came from the latter*.

**Comment by nikomatsakis** [comment]
@eddyb the point is that if you have the methods available on `sess`, then people might (by accident) do `tcx.sess.span_err()`, so we don't want that to "skip past" the recording of side-effects.

**Comment by eddyb** [comment]
Then we can have the query engine mess with the `Session` and manually save/restore diagnostic records.

**Comment by nikomatsakis** [comment]
@eddyb yes that would be fine
