### ISSUE TITLE
Feature request: aarch64-unknown-linux-musl and powerpc-unknown-linux-musl binaries

### ISSUE THREAD

**Issue by rqou** [rust-lang/rust#42520]
Other Linux targets like ARM/x86/MIPS have -musl variants in addition to -gnu variants. It'd be nice to have this for PPC and AARCH64 as well.

**Comment by smaeul** [comment]
Both of these have been merged (as well as `powerpc64` and `powerpc64le`). Can this be closed?

**Comment by jonas-schievink** [comment]
@smaeul PowerPC seems to only have GNU targets, this is about adding musl targets. https://github.com/rust-lang/rust/pull/45422 was closed, unfortunately, but feel free to revive that!

**Comment by smaeul** [comment]
@jonas-schievink I see https://github.com/rust-lang/rust/blob/master/src/librustc_target/spec/powerpc_unknown_linux_musl.rs ?

**Comment by jonas-schievink** [comment]
@smaeul Oh, interesting. According to https://forge.rust-lang.org/platform-support.html they're not supported, but the forge is often outdated. Closing as fixed.

**Comment by halvors** [comment]
What happened to this feature request? Seems this was left as a tier 3 target? See https://github.com/rust-lang/rust/issues/106932

**Comment by workingjubilee** [comment]
Please do not try to resume conversations on long-closed issues.
