### ISSUE TITLE
Errors not displaying properly on Ubuntu

### ISSUE THREAD

**Issue by Neverminder** [rust-lang/rust#42530]
I have a vanilla Ubuntu setup with default XTerm terminal colors and I can no longer see parts of the error produced, specifically "expected type" and "found type", because it's in black on a black background. Rust v1.17, screenshot included below.

![screenshot from 2017-06-08 10-18-59](https://user-images.githubusercontent.com/5731929/26921615-8b2022aa-4c34-11e7-80a2-c5887ec5915d.png)

**Comment by pmarcelll** [comment]
Are you sure you didn't change the terminal settings? The parts that are missing are printed in bold. I don't think rustc treats bold characters differently than other programs and I can't find anything related on the internet.

**Comment by Dylan-DPC** [comment]
Closing this to clear up the issue tracker. If you or anyone reading this still needs help you can consult the forums, discords, etc for help. Thanks
