### ISSUE TITLE
Allow packed enums

### ISSUE THREAD

**Issue by main--** [rust-lang/rust#42547]
```rust
use std::mem::size_of;

struct Foo {
    id: u32,
    tag: u32,
    inner: FooInner,
}

union FooInner {
    a: u64,
    b: u64,
}

#[repr(packed)]
struct Bar {
    id: u32,
    inner: BarInner,
}

#[repr(u32)]
enum BarInner {
    A(u64),
    B(u64),
}

fn main() {
    println!("{} vs {}", size_of::<Foo>(), size_of::<Bar>());
}
```

Because its members have 8-byte alignment, the enum always insists on inserting up to 7 bytes of padding, depending on the discriminant size (4 here). This is usually correct - except in cases like this one where I just **know** that this enum will always be inside a wrapper that ensures correct alignment. Without the `packed` attribute, `Bar` now has `id` followed by 4 padding bytes, then the enum discriminant and *another 4 bytes of padding* even though all the data would neatly fit into 16 bytes, as `Foo` shows.

The `#[repr(packed)]` on `Bar` successfully gets rid of the first padding but there's no way to do the same for the second one as packed enums aren't allowed.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rfcs/issues/1230.

**Comment by main--** [comment]
I understand that this might require an RFC but rust-lang/rfcs#1230 is about something else.

This issue is very definitely **not** about enum layout optimization in general, _just like packed structs are not about layout optimization either_. Doing it in general is even **wrong** because as I explained above, the padding is required to ensure correct alignment *unless I know for sure that it's not*.

What this really is about is precise control over struct/enum layout.

So if this requires an RFC, just tell me and I'll write one. If not, please reopen.

**Comment by Mark-Simulacrum** [comment]
If you want to extend `#[repr(packed)]` to enums, yes, that'll need an RFC -- is that what you're suggesting?

**Comment by main--** [comment]
Yes.

**Comment by main--** [comment]
I changed my mind. Since packed enums would have to carry the same restrictions as packed structs (field references are unsafe) they are, sadly, much less useful than I was hoping given that matching by reference becomes unsafe as well.
