### ISSUE TITLE
Weird help message suggest to place `use` randomly, when a macro is called in scope

### ISSUE THREAD

**Issue by kennytm** [rust-lang/rust#42548]
Repro case (1.19.0-beta.1 as well as nightly):

```rust
macro_rules! y {
    () => {}
}
mod m {
    pub const A: i32 = 0;
}
fn main() {
    y!();
    let _ = A;
}
```

When running it in nightly, it produces a weird error message:

```
error[E0425]: cannot find value `A` in this scope
 --> 1.rs:9:13
  |
9 |     let _ = A;
  |             ^ not found in this scope
  |
help: possible candidate is found in another module, you can import it into scope
  | fn main() use m::A;

error: aborting due to previous error(s)
```

<details><summary>No repro on 1.18 or before</summary>

```
error[E0425]: cannot find value `A` in this scope
 --> <source>:9:13
  |
9 |     let _ = A;
  |             ^ not found in this scope
  |
  = help: possible candidate is found in another module, you can import it into scope:
            `use m::A;`
error: aborting due to previous error
```

</details>

<details><summary>Version</summary>

```
rustc 1.19.0-nightly (f062832b2 2017-06-07)
binary: rustc
commit-hash: f062832b208e94f2f0f26ed7fb5c48c172069fbe
commit-date: 2017-06-07
host: x86_64-apple-darwin
release: 1.19.0-nightly
LLVM version: 4.0
```

</details>

**Comment by oli-obk** [comment]
This is due to #41876 

The suggestion placement span is unfortunate. It seems the opening brace belongs to the span of the scope where the import failed. The suggestion should be placed after the opening brace.

**Comment by Mark-Simulacrum** [comment]
@oli-obk Do you know why the suggestion puts `fn main()` in? I'm worried that new users will find that surprising and odd; perhaps we should revert some part (or all of) #41876 for now?

**Comment by oli-obk** [comment]
The issue only occurs with macros or desugarings at the beginning of the function. I plan a general fix to improve the placement, this should simply get fixed in the process
