### ISSUE TITLE
Nightly fails to find gcc on Windows

### ISSUE THREAD

**Issue by Geobert** [rust-lang/rust#42549]
since this version: nightly-2017-06-04-x86_64-pc-windows-gnu unchanged - rustc 1.19.0-nightly (6684d176c 2017-06-03)

I get:
could not exec the linker `gcc`: The system cannot find the file specified. (os error 2)

the nightly before works fine

**Comment by retep998** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/42422 which was just fixed and will land in nightly soon.
