### ISSUE TITLE
New book on Rust published by Packt

### ISSUE THREAD

**Issue by packtpartner** [rust-lang/rust#42557]
Hi,

Packt has published a new book on Rust last month.
[Mastering Rust](https://www.packtpub.com/application-development/mastering-rust) written by Vesa Kaihlavirta
_The book contains a mix of theory interspersed with hands-on tasks, so you acquire the skills as well as the knowledge. Improving performance, using generics, building macros, and working with threads are just some of the topics we’ll cover. We’ll talk about the official toolsets and ways to discover more._ 

Can this book be featured on the [Documentation page](https://www.rust-lang.org/en-US/documentation.html) under Learning Rust?
I think it would be a good learning resource.

**Comment by steveklabnik** [comment]
Hi! This is the wrong repository, can you file against https://github.com/rust-lang/rust-www please? Thanks.
