### ISSUE TITLE
Bad documentation formatting in std::process::Command

### ISSUE THREAD

**Issue by johnthagen** [rust-lang/rust#42564]
At: https://doc.rust-lang.org/std/process/struct.Command.html#examples-4

The example Markdown is not parsed correctly:

```
```no_run use std::process::{Command, Stdio}; use std::env; use std::collections::HashMap;
let filtered_env : HashMap = env::vars().filter(|&(ref k, _)| k == "TERM" || k == "TZ" || k == "LANG" || k == "PATH" ).collect();
Command::new("printenv") .stdin(Stdio::null()) .stdout(Stdio::inherit()) .env_clear() .envs(&filtered_env) .spawn() .expect("printenv failed to start"); ```
```

**Comment by steveklabnik** [comment]
<img width="404" alt="screenshot" src="https://user-images.githubusercontent.com/27786/26984515-a6625aae-4d0d-11e7-9cc6-40412be70ab9.png">

Hm, I am not seeing that.

**Comment by johnthagen** [comment]
Hmm. Strangely I can't reproduce it now. I should have taken a screenshot. But basically what I saw was the raw markdown I pasted in the original comment in the webpage.

I'm fine with closing this issue for now. If I notice it again, I'll be sure to reproduce it better. I just thought it was an easy/obvious fix but apparently might not have been a problem all along?

**Comment by ollie27** [comment]
It looks like that was a problem in [1.17.0](https://doc.rust-lang.org/1.17.0/std/process/struct.Command.html#examples-4) but it's now fixed.

**Comment by steveklabnik** [comment]
Ah ha! That looks correct. Closing!
