### ISSUE TITLE
Compiling code with dereferenced references causes panic

### ISSUE THREAD

**Issue by TheSchemm** [rust-lang/rust#42577]
Code (Redox OS ihdad code I have been working on):
`
		

		// Pin enable
		// self.send_command(Self::node_command(0x00, 0xC, 0x707, 0x40));
		// let mut response: u32 = (self.read_response() & 0xFFFFFFFF) as u32;

		self.cmd.cmd12(0x00, 0xC, 0x707, 0x40);
		

		// EAPD enable
		// self.send_command(Self::node_command(0x00, 0xC, 0x70C, 2));
		// response = (self.read_response() & 0xFFFFFFFF) as u32;

		self.cmd.cmd12(0x00, 0xC, 0x70C, 2);

		self.set_stream_channel(0x3, 1, 0);

		// self.create_sound_buffers();
		self.update_sound_buffers();

		print!("Supported Formats: {:08X}\n", self.get_supported_formats(0x1));
		print!("Capabilities: {:08X}\n", self.get_capabilities(0x3));

		let output = self.get_output_stream_descriptor(0).unwrap();
		
		output.set_address(self.buff_desc_phys);

		output.set_pcm_format(&super::SR_44_1, BitsPerSample::Bits16, 2);
		output.set_cyclic_buffer_length(0x8000); // number of samples
		output.set_stream_number(1);
		output.set_last_valid_index(1);
		output.set_interrupt_on_completion(true);

		self.set_power_state(0x3, 0); // Power state 0 is fully on
		self.set_converter_format(0x3, &super::SR_44_1, BitsPerSample::Bits16, 2);
		

	
		// self.send_command(Self::node_command(0x00, 0x3, 0xA00, 0));
		// response = (self.read_response() & 0xFFFFFFFF) as u32;
		
		self.cmd.cmd12(0x00, 0x3, 0xA00, 0);

		// Unmute and set gain for pin complex and DAC
		self.set_amplifier_gain_mute(0x3, true, true, true, true, 0, false, 0x7f);
		self.set_amplifier_gain_mute(0xC, true, true, true, true, 0, false, 0x7f);

		`

Backtrace:
`thread 'rustc' panicked at 'failed to emit error: Resource temporarily unavailable (os error 11)', /checkout/src/librustc_errors/emitter.rs:1141
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:365
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: <rustc_errors::emitter::EmitterWriter as rustc_errors::emitter::Emitter>::emit
   8: rustc_errors::diagnostic_builder::DiagnosticBuilder::emit
   9: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_id
  10: rustc::hir::intravisit::walk_struct_field
  11: rustc::lint::context::LintContext::with_lint_attrs
  12: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_variant_data
  13: rustc::hir::intravisit::walk_item
  14: rustc::lint::context::LintContext::with_lint_attrs
  15: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod
  16: rustc::hir::intravisit::walk_item
  17: rustc::lint::context::LintContext::with_lint_attrs
  18: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod
  19: rustc::hir::intravisit::walk_item
  20: rustc::lint::context::LintContext::with_lint_attrs
  21: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod
  22: rustc::lint::context::check_crate
  23: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}
  24: rustc_driver::driver::phase_3_run_analysis_passes
  25: rustc_driver::driver::compile_input
  26: rustc_driver::run_compiler
  27: std::panicking::try::do_call
  28: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  29: <F as alloc::boxed::FnBox<A>>::call_box
  30: std::sys::imp::thread::Thread::new::thread_start
             at /checkout/src/liballoc/boxed.rs:658
             at /checkout/src/libstd/sys_common/thread.rs:21
             at /checkout/src/libstd/sys/unix/thread.rs:84
  31: start_thread
  32: __clone
`

**Comment by oli-obk** [comment]
I can see how it is hard to create a minimal example from the redox code, bur could you include reproduction instructions? Like a specific commit to compile? And the OS you're compiling under?

**Comment by steveklabnik** [comment]
Without reproduction instructions, we cannot help. Closing!
