### ISSUE TITLE
Some links in the API documentation point to the older URL of the Book

### ISSUE THREAD

**Issue by VBChunguk** [rust-lang/rust#42589]
The first edition of the Book is moved from `/book` into `/book/first-edition`, but some links in the API documentation are not following the change. For example, in [`core::ops::Deref`][deref] documentation, there is a link to the '`Deref` coercions' page of the first edition, with older URL structure.

[deref]: https://doc.rust-lang.org/core/ops/trait.Deref.html

This makes kind of "broken link" in the documentation, though it's not a real broken link, because the pages under the older URL suggest that we try with the namespace added. However, it does add additional link that visitors should follow, which probably isn't what they want.

I think the solution is simple; adding `first-edition` namespace if the link pointing to the Book does not have any namespace. May I work on this issue?

**Comment by steveklabnik** [comment]
> I think the solution is simple; adding first-edition namespace if the link pointing to the Book does not have any namespace. May I work on this issue?

yes, this is a great initial fix! A slightly better one would be to update them to the appropriate spot in the second edition, but that's going to be harder.

**Comment by VBChunguk** [comment]
I noticed that not all documents are moved into `first-edition`; some documents are moved into the Unstable Book. Fixing the broken links would be harder than I thought...

**Comment by steveklabnik** [comment]
Yeah, that should be the only real thing. I'd imagine.
