### ISSUE TITLE
An error message should not contain a keyword x such that searching rust + x has 0 relevant results on the first page 

### ISSUE THREAD

**Issue by SRGOM** [rust-lang/rust#42603]
Case in point: I get an error:

```
the trait `Foo` cannot be made into an object
....
method add has no receiver
```

I looked up `rust receiver` but couldn't find any relevant results. Upon investigating further, in this case, `method add does not have a self parameter` would be more appropriate.

**Comment by frewsxcv** [comment]
Is it possible you could share the code that results in this error?

**Comment by jonas-schievink** [comment]
Anything like this'll work:

```rust
trait Tr { fn recv(); }

fn main() {
    let t: &Tr = panic!();
}
```

**Comment by SRGOM** [comment]
What @jonas-schievink said, my code: 
```

trait Foo{
    fn add( s: Self, o: Self ) -> Self;
}

impl Foo for i32{
    fn add( s: Self, o: Self ) -> Self {
        s + o
    }
}

fn scratchpad()
{
     let a: &Foo = &99;
}

```

**Comment by estebank** [comment]
For _me_ the fourth result for "rust method has no receiver" is the [Error Index](https://doc.rust-lang.org/error-index.html), where there's a full explanation of error [E0038](https://doc.rust-lang.org/error-index.html#E0038) (which you can also see using `rustc --explain E0038`). That explanation has a subsection titled ["Method has no receiver"](https://doc.rust-lang.org/error-index.html#method-has-no-receiver) which explain this case and proposes a solution:

> Adding a `Self: Sized` bound to these methods will generally make this compile.

**Comment by SRGOM** [comment]
@estebank I hit 1st and 3rd results on that one and they were irrelevant so I figured i'll try to understand the problem from the bottom. That's why I searched "Rust receiver" (without quotes) as the issue title says.

**Comment by durka** [comment]
I think "receiver" is the correct term here and as mentioned, `rustc --explain E0038` has a good amount of explanation. So I understand @SRGOM's frustration but I don't think there is really anything to do here, besides maybe adding a section to the Book along [these lines](https://tour.golang.org/methods/1).

**Comment by nikomatsakis** [comment]
The receiver term is pretty standard "OO jargon", but I think that it would be clearer still for us to say "no `self` parameter".

**Comment by nikomatsakis** [comment]
Also, in my opinion, an associated function without a parameter named `self` is not a method at all, but just a function; so I'd probably say something like "the function `add` has no self parameter")
