### ISSUE TITLE
HashSet::hasher: Malformed weblink to BuildHasher

### ISSUE THREAD

**Issue by mglagla** [rust-lang/rust#42600]
The link to BuildHasher in the documentation of HashSet::hasher is broken and returns a "Not Found" page.

**Comment by est31** [comment]
This is known and [included as exception](https://github.com/rust-lang/rust/blob/d4f20eb7e32bad9049663d30cfcb0e246ef2e031/src/tools/linkchecker/main.rs#L129) in the linkchecker code. The code references issue #32130 for this, not sure whether this issue should be closed as dupe or not...

**Comment by Mark-Simulacrum** [comment]
Yes, I don't see a reason to track this separately.
