### ISSUE TITLE
Rustdoc should pick up docs for tuple struct and enum fields

### ISSUE THREAD

**Issue by TedDriggs** [rust-lang/rust#42615]
Rustdoc should expose doc comments written on tuple fields:

```rust
pub struct Foo(
    /// Hello docs
    String
);
```

Tagging @QuietMisdreavus @GuillaumeGomez based on conversation on IRC.

**Comment by hcpl** [comment]
This issue also applies to tuple variant fields:
```rust
pub enum Bar {
    BarVariant(
        /// Hello docs
        String
    ),
}
```

**Comment by GuillaumeGomez** [comment]
It promises to be very interesting from a design point of view. We'll to think about how to render this nicely.
