### ISSUE TITLE
Detect SystemTime overflow in debug mode

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#42622]
```rust
use std::time::{Duration, UNIX_EPOCH};
use std::u64;

fn main() {
    let t = UNIX_EPOCH + Duration::new(u64::MAX, 0) + Duration::new(2, 0);
    println!("{}", t.duration_since(UNIX_EPOCH).unwrap().as_secs()); // 1
}
```

For me (Linux + Rust 1.19.0-nightly) this program prints 1. In debug mode I would expect this overflow to be caught and panic, similar to `u64::MAX + 2`.

**Comment by cuviper** [comment]
There are explicit checks regardless of debug mode, but the overflow occurs silently when `add_duration` first converts your `u64::MAX` to `i64`.  So it basically sees the signed addition `UNIX_EPOCH + (-1) + 2 = 1`.

Your example starting with `i64::MAX` instead does panic, "overflow when adding duration to time".
