### ISSUE TITLE
Extend 'unimplemented!' API docs to mention new parameter functionality

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#42628]
Follow-up to https://github.com/rust-lang/rust/pull/42155

**Comment by steveklabnik** [comment]
I'd be happy to mentor anyone who wants to take this on! It mostly involves adding a small example to the docs, a great first issue!

**Comment by MarkMcCaskey** [comment]
@steveklabnik I'd be interested!  Thanks!

**Comment by toidiu** [comment]
@MarkMcCaskey are you still working on this?

**Comment by kennytm** [comment]
@toidiu already implemented as #44206, currently waiting to be merged.

**Comment by toidiu** [comment]
@kennytm oops sry missed that
