### ISSUE TITLE
"The Rust Programming Language Has Moved" page instead of useful content appears in Google

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust#42632]
When I google Rust-related topics I often land on the dead links from the old book, e.g.:

https://www.google.co.uk/search?q=rust+enum

for me the first result is:

https://doc.rust-lang.org/book/enums.html

It even has a relevant (out of date?) description:

> Enums. An enum in Rust is a type that represents data that is one of several possible variants. Each variant in the enum can optionally have data associated with ...

but the page itself **looks like a 404**. It does not contain the content I searched for. There is a link to the book page in the block of text, but landing on that page gives such an off-putting "dead-end" impression that I didn't notice it until half way of writing this bug.

Can you remove these "redirect" pages with robots.txt? (or HTTP redirect straight to `/first-edition`) 

Having such pages on the official domain makes a very negative impression — it looks like a combination of a broken link and abandoned out of date documentation.

**Comment by steveklabnik** [comment]
I see this

<img width="531" alt="moved" src="https://user-images.githubusercontent.com/27786/27091586-953aa42e-502e-11e7-93ee-399f73bf4ddb.png">

**Comment by steveklabnik** [comment]
I see this:

<img width="531" alt="moved" src="https://user-images.githubusercontent.com/27786/27091621-b15216d8-502e-11e7-9b5c-2ca6c39066ac.png">

nothing about enums there?

**Comment by pornel** [comment]
That's the same thing I see. And nothing about enums is exaclty the problem. This page is shown as the first result for "rust enum" search query, so it should be all about enums.

**Comment by steveklabnik** [comment]
I have no idea what our capacity for redirects are; this is how we've done it for years. @rust-lang/infra ?

**Comment by alexcrichton** [comment]
We've mostly done this historically with robots.txt but in general we need a lot of SEO love, it's not just this. I unfortunately know of no silver bullet here.

**Comment by shepmaster** [comment]
> with robots.txt 

I didn't think that robots.txt had anything to do with redirects. 

Is it possible to get a list of the URLs from the first edition of the book (e.g. `/stable/book/first-edition/syntax-and-semantics.html`) and set up redirects from the old location (`/stable/book/syntax-and-semantics.html` -> `/stable/book/first-edition/syntax-and-semantics.html`)?

> we need a lot of SEO love

This goes beyond SEO. Every single link to the book from the entire internet is broken, except for the rare case where people explicitly included the version in the URL.  A rough query shows that 400+ of the 6800 Rust questions now have broken links to the documentation.

**Comment by steveklabnik** [comment]
> Is it possible to get a list of the URLs from the first edition of the book (e.g. /stable/book/first-edition/syntax-and-semantics.html) and set up redirects from the old location (/stable/book/syntax-and-semantics.html -> /stable/book/first-edition/syntax-and-semantics.html)?

To be clear, each of these pages has redirects, just not automatic ones; you have to click the link.

**Comment by tomprince** [comment]
I don't have any experience doing anything suggested in it, but https://support.google.com/webmasters/answer/139066 might have some ideas on how to get google to prefer newer URLs.

**Comment by shepmaster** [comment]
> you have to click the link.

Being transparent, I did not understand that from the text

> you probably want to visit first-edition/

To me, that looks like it's going to to take me to `https://doc.rust-lang.org/book/first-edition/` (especially because of the trailing slash), not `https://doc.rust-lang.org/book/first-edition/enums.html`. I didn't think to hover over the link to figure out where it was going to take me beyond that.

I still think I'd prefer for the links to redirect `/stable/book/syntax-and-semantics.html` -> `/stable/book/first-edition/syntax-and-semantics.html` and then have a header on each of the pages of the old book that encourages people to see the new one: 

>  if you're trying to learn Rust, checking out the second edition might be a better choice

As a single point of confirmation, [Webpack 2 is doing something like this](https://webpack.github.io/docs/webpack-dev-server.html):

![image](https://user-images.githubusercontent.com/174509/27103862-2196ec10-5058-11e7-8683-4ccddcb739d5.png)

**Comment by bstrie** [comment]
I was just bitten by this today, came to file this same issue. I searched for "rust unsafe keyword", the first result was https://doc.rust-lang.org/book/unsafe.html , and from the landing page there it was 100% unclear to me that clicking "first-edition/" would take me to the relevant page in the original book. We really need to do something here, I can't imagine how many people are being frustrated by this.

**Comment by pornel** [comment]
I suggest changing it to something short, with very prominent links:

----

# There is a new edition of the book

This is an old link. You can [continue to the exact older page][1]. If you're trying to learn Rust, checking out [the second edition][2] might be a better choice.

* [This page in the first edition of the The Rust Programming Language][1]

* [Index of the second edition of The Rust Programming Language][2]

[1]: first-edition/unsafe.html
[2]: second-edition/index.html
