### ISSUE TITLE
Enable testing wasm32-unknown-emscripten on travis

### ISSUE THREAD

**Issue by malbarbo** [rust-lang/rust#42646]
A disabled image was added in https://github.com/rust-lang/rust/pull/42631. We should enable it when we get some capacity on travis.

**Comment by lilianmoraru** [comment]
@alexcrichton Can we re-enable `wasm32` in Travis now?

**Comment by alexcrichton** [comment]
Unfortunately wasm32 is a "big enough" builder that it requires its own builder, which is much more of a significant investment than just having a standard library.

Did this regress though? I'd imagine that for all practical purposes having CI for asmjs is basically equivalent to CI for wasm

**Comment by lilianmoraru** [comment]
@alexcrichton In my case, the asserts were failing only on `wasm32`: https://github.com/rust-lang/rust/issues/42518

**Comment by alexcrichton** [comment]
Was that ever working though? In the sense that would we have caught a regression if we were running CI?

**Comment by lilianmoraru** [comment]
@alexcrichton I was just pointing that `asmjs` and `wasm32` are not equivalent - I myself hit an issue that was specific to `wasm32` only.
I can't answer if this would of caught a regression, though.

**Comment by alexcrichton** [comment]
Oh yeah sure definitely!

I'm sure we'd catch bugs over time, but I'd personally sort of prefer to wait until we can make wasm a "true" tier 1 target by using the LLVM backend instead of going through emscripten, that may just take awhile :(

**Comment by alexcrichton** [comment]
This is done now for wasm32-unknown-unknown which I think is exercising LLVM's backend (the goal here), so I'm going to close.
