### ISSUE TITLE
rustc docs are sparse

### ISSUE THREAD

**Issue by marcoms** [rust-lang/rust#42647]
I've generally found that while Rust docs are excellent, the docs for rustc are sparse or seem less complete. 

For example, various places say to use `-C panic=abort` for some size reduction, but I'm only able to access possible values for the panic option by providing an invalid option:

```
$ rustc -C panic=help
error: codegen option `panic` requires either `panic` or `abort` (C panic=<value>)
```

I guess it works but obviously it isn't ideal - even that message doesn't explain the difference.

Another example, I could only find out through IRC that I should by using `--crate-type=cdylib` for better language interoperability vs. what I expected to be `lib` or `dylib` (which is apparently Rust specific).

AFAIK stuff like this doesn't have any official central docs, in the same way as https://doc.rust-lang.org

**Comment by rthomas** [comment]
The codegen options can be displayed with `$ rustc -C help` but I do agree that the help values could be expanded - as well as there being a central place for some compiler documentation.

**Comment by steveklabnik** [comment]
As of the next release, we'll have https://doc.rust-lang.org/beta/rustc/, which covers this stuff. Since it exists, I'm going to give this a close; specific improvements deserver their own individual issues. Thanks!
