### ISSUE TITLE
rustdoc sometimes generates invalid script tags

### ISSUE THREAD

**Issue by Darksonn** [rust-lang/rust#42658]
To see examples of these in the wild, you can look at the source of the following web pages:

    https://docs.serde.rs/serde/de/trait.VariantAccess.html line 145
    https://docs.rs/serde/1.0.8/serde/trait.Serializer.html line 1113
    https://docs.rs/hyper/0.10.10/hyper/net/trait.SslServer.html line 438

This is the tag from the last example:

    <script type="text/javascript" async
                             src="../../implementors/hyper/net/trait.SslServer.js">
                     </script>

I found them while checking my crate's documentation for broken links. In order to find these tags, you can do the following:

 1. Create a new crate (or pick any existing crate) that depends on the crates you wish to check for these invalid scripts. There are definitely examples in serde v1.0.8 and hyper v0.10.10.
 2. Generate the documentation with `cargo doc`.
 3. Copy the `target/doc` folder to any web server.
 4. Run the command `wget --spider -r -nd -nv  -l 100 -e robots=off -o run1.log http://server/path/to/doc/index.html`
 5. Now inspect the log of the web server or the `run1.log` file for 404s of .js files. If you use the log of the web server, the Referrer should be the page with the broken tag (this is not printed in the wget log), but in all the cases I've found, the script has the same name as the web page it was found on.

In all cases I've seen, the script tag is right after a `</ul>` tag and has a line break after `async` and before the `</script>`.

**Comment by Darksonn** [comment]
I was checking my old issues and have confirmed that this still happens. See e.g. [here][1].

It looks like the problem occurs on pages with a trait where the Implementors section is empty.

[1]: https://docs.rs/serde/1.0.99/serde/trait.Serializer.html

**Comment by GuillaumeGomez** [comment]
Seems like it's not the case anymore in https://docs.rs/serde/1.0.136/serde/trait.Serializer.html. Closing then!
