### ISSUE TITLE
Rustbuild: No rule to make "rust/src/liballoc_jemalloc/../jemalloc/include/jemalloc/internal/ph.h"

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#42652]
I've recently done a source update of rustc, and have been greeted by an error like "No rule to make target `src/liballoc_jemalloc/../jemalloc/include/jemalloc/internal/ph.h`, needed by `src/jemalloc.o`".

I could work around the issue by removing the `build/x86_64-unknown-linux-gnu/native/jemalloc/` directory and rebuilding, but its a build system issue if that is not done for me, or if the makefile is not regenerated.

**Comment by est31** [comment]
Hmm seems this was caused by #42566 ...

**Comment by VBChunguk** [comment]
I encountered the same issue, and rebuilding after `./x.py clean` solved it.

**Comment by petrochenkov** [comment]
I encountered this as well, It's some jemalloc build system issue - it can't reconfigure correctly in a dirty build directory if some huge changes like https://github.com/rust-lang/rust/pull/41861 or https://github.com/rust-lang/rust/pull/42566 happen.
The minimal fix is to delete the jemalloc build directory `build\<target>\native\jemalloc` and build again.

**Comment by est31** [comment]
@petrochenkov can this be kept open for a while to prevent dupes from being filed? most people only search for open bugs.

**Comment by est31** [comment]
Okay, it has been open long enough.
