### ISSUE TITLE
Redundant oom branches not being eliminated

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#42666]
Original report: https://bugzilla.mozilla.org/show_bug.cgi?id=1369420

From that report:

"In the disassembly of style::properties::PropertyDeclaration::parse_into, at the end there is an area with hundreds of repetitions of:"

```
142476 00000001`80437946 e8b5490f00      call    xul!alloc::oom::oom (00000001`8052c300)
142476 00000001`8043794b 0f0b            ud2
142476 00000001`8043794d e8ae490f00      call    xul!alloc::oom::oom (00000001`8052c300)
142476 00000001`80437952 0f0b            ud2
142476 00000001`80437954 e8a7490f00      call    xul!alloc::oom::oom (00000001`8052c300)
142476 00000001`80437959 0f0b            ud2
```

"I'm guessing what's happening is that the compiler places unlikely fatal codepaths at the end of the function, outside of the normal control flow (which is good) but it would be good if it could recognize when several of these paths will lead to the same place and collapse them to save space."

If what's going on here is as simple as it seems, this could be a nice easy win.

cc @arielb1 seems like something that might interest you.

**Comment by nagisa** [comment]
See https://reviews.llvm.org/D30774

**Comment by upsuper** [comment]
> See https://reviews.llvm.org/D30774

This LLVM patch seems to have been abandoned.

**Comment by workingjubilee** [comment]
From the current state of this bug report, I am not sure where I would begin with reproducing this today in order to resolve it. The way we handle allocators in particular has changed enough since this was opened that I am hesitant to draw conclusions.

**Comment by bholley** [comment]
@workingjubilee 

If you're interested in fixing this on the rustc/llvm side, I'd be happy to connect you to a Firefox engineer who can verify that the issue still reproduces and if so, help you do so.

**Comment by workingjubilee** [comment]
I have been periodically examining codegen issues lately. I would be happy to at least take a closer look given something MCVE-ish to work off of.

**Comment by glandium** [comment]
It doesn't look like to be happening anymore.

**Comment by workingjubilee** [comment]
Ah, excellent! Then this can be closed. Thank you!
