### ISSUE TITLE
libsyntax not in 1.20 nightly rust-src component?

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#42667]
Per a [rustup report](https://github.com/rust-lang-nursery/rustup.rs/issues/1165), are the nightly rust-src packages not including libsyntax?

**Comment by brson** [comment]
cc @gbip

**Comment by ishitatsuyuki** [comment]
Yes, since they're rustc source, and only libstd source is needed for racer.

Blame #41546

**Comment by nrc** [comment]
We discussed at the dev-tools meeting today, consensus was that this is by design and the decision to remove was good

**Comment by nrc** [comment]
Further, we thought that for users who want the compiler sources, we should make available a separate rust-src-internals with the source for the compiler including libsyntax.

**Comment by alexcrichton** [comment]
Untagging as a regression due to [previous comment](https://github.com/rust-lang/rust/issues/42667#issuecomment-309558390)

**Comment by sanmai-NL** [comment]
@alexcrichton: can this be closed?

**Comment by oli-obk** [comment]
fixed in https://github.com/rust-lang/rust/pull/58269
