### ISSUE TITLE
rustbuild: neither `./x.py doc --stage 0` nor `./x.py doc --stage 1 --keep-stage 0` regenerate api docs if only rustdoc changed

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/rust#42686]
If i want to test a change to rustdoc by re-rendering the std docs, i could combine the "rebuild rustdoc" and "render api docs" steps into an `./x.py doc` command. If i wanted to avoid rebuilding all of stage1, then i could try `./x.py doc --stage 0`, but that doesn't actually re-render the documentation! It gets to that step, sees that the documentation output is newer than the source files for libstd, then skips it. (The same problem occurs with `./x.py doc --stage 1 --keep-stage 0`, on a related note.) This requires a rustdoc contributor to rebuild an entire stage to be able to test their change on a rendering of std. (Testing it by rendering a separate crate is still possible, i suppose, but also requires the additional step of linking the toolchain in rustup or using the test rustdoc/rustc by a different means.)

**Comment by QuietMisdreavus** [comment]
This is kinda related to #38318, but not precisely. I'd made [a comment in there](https://github.com/rust-lang/rust/issues/38318#issuecomment-290829043) explaining my findings when i first saw this behavior. However, looking back at that issue, that seems to be more about how `--keep-stage` isn't enabled by default, rather than not considering generated docs to need regeneration after a rustdoc change.

**Comment by jyn514** [comment]
I don't think this is still an issue, I remember using `x doc --stage 1 library/std` with success (and I think @GuillaumeGomez uses `x doc std` pretty regularly).

**Comment by GuillaumeGomez** [comment]
I confirm it works as expected.
