### ISSUE TITLE
test_process_mask fails because read() doesn't fail

### ISSUE THREAD

**Issue by daym** [rust-lang/rust#42680]
We are trying to enable rustc tests in the Guix distribution and are now down to two test failures total.

One test failure is in test_process_mask.  The read() at the end doesn't fail.

We build all packages in an isolated container each (for reproducibility).

Now I'd like to find out what exactly goes wrong. How can I rerun just this one test?

I tried to copy out just `./src/libstd/sys/unix/process/process_common.rs` and fix up the `use` declarations and compile that but I get some errors regarding `sys::pipe`.

The tester executable is `x86_64-unknown-linux-gnu/stage2/test/stdtest-x86_64-unknown-linux-gnu`.

**Comment by daym** [comment]
i've tried this Python program that's hopefully equivalent:

```python
#!/usr/bin/env python3

import os
import subprocess
import signal

signal.pthread_sigmask(signal.SIG_BLOCK, [signal.SIGINT])

p = subprocess.Popen(["cat"], stdin=subprocess.PIPE, stdout=subprocess.PIPE)

signal.pthread_sigmask(signal.SIG_UNBLOCK, [signal.SIGINT])

os.kill(p.pid, signal.SIGINT)
stdout, stderr = p.communicate(b"hello\n", timeout=1)
assert stdout == b""
p.wait()
```

Also fails.

**Comment by Mark-Simulacrum** [comment]
`./x.py test src/libstd --test-args process_mask` should allow you to run just that test.

**Comment by sanxiyn** [comment]
@daym, can you just run that one test as @Mark-Simulacrum showed?

**Comment by ipetkov** [comment]
Not sure if this issue is still relevant, today Guix bootstraps rust starting with 1.19 (1.16 isn't built anywhere).

**Comment by sanxiyn** [comment]
Does test_process_mask fail on current Guix?

**Comment by daym** [comment]
Yes, same situation with rust 1.31.1.

**Comment by daym** [comment]
A corresponding C program doesn't do the same, neither inside or outside the build container.

```
#include <stdio.h>
#include <stdlib.h>
#include <spawn.h>
#include <unistd.h>
#include <sys/types.h>
#include <signal.h>
#include <errno.h>
#include <string.h>

int main() {
	char buf[401];
	sigset_t s;
	sigset_t olds;
	posix_spawn_file_actions_t action;
	int cout_pipe[2];
	int cin_pipe[2];
	pid_t child;
	char* args[] = {
		"cat",
		NULL,
	};

	sigemptyset(&s);
	sigaddset(&s, SIGINT);
	pthread_sigmask(SIG_SETMASK, &s, &olds);
	if (pipe(cout_pipe))
		return 1;
	if (pipe(cin_pipe))
		return 1;
	posix_spawn_file_actions_init(&action);
	posix_spawn_file_actions_addclose(&action, cout_pipe[0]);
	posix_spawn_file_actions_adddup2(&action, cout_pipe[1], 1);
	posix_spawn_file_actions_addclose(&action, cin_pipe[1]);
	posix_spawn_file_actions_adddup2(&action, cin_pipe[0], 0);

	if(posix_spawnp(&child, "cat", &action, NULL, args, NULL) != 0) {
		perror("posix_spawnp");
		return 2;
	}
	close(cout_pipe[1]);
	close(cin_pipe[0]);

	kill(child, SIGINT);

	write(cin_pipe[1], "Hello", strlen("Hello"));
	close(cin_pipe[1]);
	int rc = read(cout_pipe[0], buf, 400);
	if (rc == -1) {
		if(errno != EPIPE) {
			perror("read");
			return 3;
		}
	} else if (rc != 0) {
		printf("test failure: read %d\n", rc);
		return 4;
	}
	return 0;
}
```

I get a test failure, with rc==4.

**Comment by jieyouxu** [comment]
Triage: I don't think we can do much about this if the C-version also fails.
