### ISSUE TITLE
Support a --keep-going option when running tests

### ISSUE THREAD

**Issue by infinity0** [rust-lang/rust#42683]
This would be helpful for distros when running tests, both for (a) distros that ignore a failed test run and (b) for distros that try to keep a clean test run.

When a suite fails, rustbuild won't run further test suites. In the case of (a) any subsequent failures are hidden, which might be important ones that mean the built compiler is dangerous, and in the case of (b) it takes a lot of time to patch out this failure, re-run the whole build to see what the next failure is, and repeat this until there are no unpatched failures left.

If rustbuild runs all test suites even if one of them fails, then all failures in all test suites would be reported and people can see the status of their package better, as well as fix things in a much shorter amount of time.

**Comment by petrochenkov** [comment]
Do you mean something like https://github.com/rust-lang/rust/pull/42363?

**Comment by infinity0** [comment]
Yes, exactly! Sorry for the noise, I'm still a release behind in Debian.
