### ISSUE TITLE
Spurious `gdb failed to execute` on Windows

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#42693]
First seen in #41840 - https://ci.appveyor.com/project/rust-lang/rust/build/1.0.3595/job/4s8ofgv42um1t8b2:

```
failures:
---- [debuginfo-gdb] debuginfo-gdb\borrowed-c-style-enum.rs stdout ----
	NOTE: compiletest thinks it is using GDB without native rust support
NOTE: compiletest thinks it is using GDB version 7010001
error: gdb failed to execute
thread '[debuginfo-gdb] debuginfo-gdb\borrowed-c-style-enum.rs' panicked at 'explicit panic', src\tools\compiletest\src\runtest.rs:1651
```

**Comment by kennytm** [comment]
The error code from #44261 is `1816`, which is [`ERROR_NOT_ENOUGH_QUOTA`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681386.aspx#ERROR_NOT_ENOUGH_QUOTA) (Not enough quota is available to process this command.)
