### ISSUE TITLE
Assorted rust tools emit terminal codes to non-ttys

### ISSUE THREAD

**Issue by mcandre** [rust-lang/rust#42707]
Some rust tools, inclusing rustc and cargo, emit terminal codes when the terminal is not an interactive user session. For example, rustc may be run from within a vi or emacs terminal, or cargo may be piped to `less`.

In general, command line tools should disable terminal codes when !tty(), so that the output can be better processed.

**Comment by Mark-Simulacrum** [comment]
This is attempted to be done today. Can you tell us exactly what case is going wrong for you?
