### ISSUE TITLE
Improve case with one named, one anonymous lifetime parameter - SubSupConflict Errors

### ISSUE THREAD

**Issue by gaurikholkar** [rust-lang/rust#42701]
Currently in  #42669, we are handling only ConcreteFailure RegionResolution Errors.  We need to detect and improve the error message for SubSupConflict Error as well.
```rust
struct Foo {
  field: i32
}
impl Foo{

  fn foo2<'a>(&self, x: &'a i32) -> &'a i32 {
    if true { &self.field } else { x }
  }
}
```
cc @nikomatsakis

**Comment by cengizIO** [comment]
I'd like to start working on this if noone else is assigned.

**Comment by nikomatsakis** [comment]
@cengizIO expressed some interest in taking a look at this. @cengizIO, here are some rough instructions for what would have to be done. Currently, when reporting region errors, we [check for the special case of a "named-anon conflict"](https://github.com/rust-lang/rust/blob/0926f9b72fc3deed0e9d06261b08646425a158f8/src/librustc/infer/error_reporting/mod.rs#L273). If you look into this function, you'll see that it [first tests for `ConcreteFailure`](https://github.com/rust-lang/rust/blob/0926f9b72fc3deed0e9d06261b08646425a158f8/src/librustc/infer/error_reporting/named_anon_conflict.rs#L78-L81). The basic task here is to extend that also work for `SubSupConflict`. I think, in this case, that is probably as easy as extracting the sub and sup regions involved (as well as the "main span") and returning them, and then checking what impact that has on the tests involved and making sure everything still looks ok. It's a good opportunity though to read over the code and understand what it does.

**Comment by gaurikholkar** [comment]
You can read up my blogs [here](https://medium.com/@geekytwoshoes11/once-upon-a-rust-lifetime-782bd7c86910).

**Comment by cengizIO** [comment]
Ping: I was busy with other stuff since I've signed up to this. Now that they are over, I'm diving into it.

**Comment by nikomatsakis** [comment]
I think this is a good test case:

```rust
struct Foo {
    field: i32,
}

fn foo2<'a>(a: &'a Foo, x: &i32) -> &'a i32 {
    if true {
        let p: &i32 = &a.field;
        &*p
    } else {
        &*x
    }
}

fn main() { }
```

**Comment by cengizIO** [comment]
Hello @gaurikholkar I was in LOA during last week, just returned. Will revise my PR tomorrow.

**Comment by cengizIO** [comment]
I've removed the redundant test case and updated the sample input with the provided one up in https://github.com/rust-lang/rust/issues/42701#issuecomment-326091615

**Comment by nikomatsakis** [comment]
[Perf results look fairly even.](http://perf.rust-lang.org/compare.html?start=fc77b623d3072005f35e320e652f2b31695d493c&end=44a477ee0833eef8007499fec6ebd88c5289da8a&stat=instructions%3Au)
