### ISSUE TITLE
operator overloading - suggestion - generalise comparison operator output

### ISSUE THREAD

**Issue by dobkeratops** [rust-lang/rust#42715]
Could the comparision operators `fn gt()  fn lt()` etc  be generalised to use an over-rideable output type (which defaults to 'bool'), e.g. allowing    `fn gt(&self,&Vec4<f32>) -> Vec4<BoolMask32>`  or whatever.

Would this need the `PartialOrd` constraint to also be parameterised  to keep existing code working, or would the operators themselves have to be extracted into new dedicated traits, and `PartialOrd` depends on specifically bool-operator outputs. (i.e. vectorized bool no longer satisfies PartialOrd in any way).

**Motivation:**

I think It would be more consistent when making a vectorized operator library to allow *all* operators to return vectorized results, even if this breaks the ability to use such types in traditional 'branchy' code (as this is sometimes the point of a vectorized library, e.g. for SIMD, predicted SIMD).

Being a systems language,  Rust surely wants to surely handle the use cases of C++, and there are many devices where routine use of vectorized types is important for performance. (a real world example  I dealt with was making vector operators easy to use, but also constraining their ability to be used in branchy code because that was expensive .. e.g. a branch costed more than matrix multiplies or whatever).

What I imagine is the vectorized select masks would have methods '.any()', '.all()' (horizontal bitor / bitand) to produce straightforward bools to slot into 'if' etc.

This example does not break safety.  The trait system should allow more opportunity for a library to guide the user with meaningful error messages, so confusion should not be a hazard here.

**Comment by kennytm** [comment]
How would this affect PartialEq?

**Comment by dobkeratops** [comment]
that would need the same generalization. I'm   a little hazy on whether or not the concepts Ord/PartialOrd etc explicitely need a bool output (i.e. they're for things that are sortable) in which case we'd need to separate the trait for sortability from the raw operator support. ('sortable means having comparison operators that return bool')

**Comment by oli-obk** [comment]
While your use case would not be abuse of such a system, every single other usage without a bool  return type would be. The basic operators are meant to have clear semantics.

Anyway. This belongs on the RFC repository's issue list, since it is a nontrivial feature request.

**Comment by steveklabnik** [comment]
> Anyway. This belongs on the RFC repository's issue list, since it is a nontrivial feature request.

Agreed! Please move this over there :) Thanks!
