### ISSUE TITLE
Improve unused_assignments message

### ISSUE THREAD

**Issue by jD91mZM2** [rust-lang/rust#42748]
I get this error:

```
warning: value assigned to `tempdir` is never read
  --> video.rs:51:6
   |
51 |    let mut tempdir = None;
   |        ^^^^^^^^^^^
   |
   = note: #[warn(unused_assignments)] on by default
```

But I need to assign it so it doesn't go out of scope!

EDIT: We can use a "rich lint" to add suggestion of renaming `tempdir` to `_tempdir`.

[Playground Example](https://is.gd/pYK124)

**Comment by VBChunguk** [comment]
You can make an explicit call to `drop` to silence the warning:

```rust
let mut tempdir = None;
// some use of tempdir
drop(tempdir);
```

**Comment by arielb1** [comment]
Or you could make the variable's name start with an underscore to silence the warning - that's the convention I know of. BTW, you don't need to initialize the value to `None`.

```Rust
struct Test;
impl Drop for Test {
    fn drop(&mut self) {
        println!("World");
    }
}

fn main() {
    let _keep_alive;

    if true { //condition
        let may_exist = Test;
        _keep_alive = may_exist; // Can't let this go out of scope yet!
    }

    println!("Hello");
}
```

**Comment by legolord208** [comment]
Thanks a lot for the help! :smile:

I'll keep the issue open as the message could be improved, like you suggested?

**Comment by estebank** [comment]
[Current output](https://play.rust-lang.org/?gist=d47e4b7f37f40dbae50d7131c6b1c004&version=nightly) includes a suggestion use a leading underscore:

```
warning: variable `keep_alive` is assigned to, but never used
 --> src/main.rs:9:9
  |
9 |     let mut keep_alive = None;
  |         ^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_variables)] on by default
  = note: to avoid this warning, consider using `_keep_alive` instead
```
