### ISSUE TITLE
Associated constant formatting in docs should mirror source

### ISSUE THREAD

**Issue by SergioBenitez** [rust-lang/rust#42759]
In my source code, I've declared an associated constant as follows:

```rust
struct MyStruct(u8);

impl MyStruct {
    pub const KIND: MyStruct = MyStruct(0b0100);
}
```

If I render the rustdocs for `MyStruct`, the following is displayed:

```rust
KIND: MyStruct = MyStruct(4)
```

Instead, I would like to see:

```rust
KIND: MyStruct = MyStruct(0b0100)
```

Or, at the very least:

```rust
KIND: MyStruct = MyStruct(0b100)
```

I've declared the `KIND` constant as a binary number because it serves as a mask. I want the rustdocs to reflect this. Said another way, the representation used in the source code is meaningful, and the rustdocs should preserve that meaning. Note that this should also apply to other representations including hexadecimal. This format-preserving behavior should also apply to other constants, not just associated constants.

**Comment by ollie27** [comment]
Fixed by #53409. We don't show the values of consts anymore.
