### ISSUE TITLE
Page fault on Redox accessing invalid TLS address

### ISSUE THREAD

**Issue by jackpot51** [rust-lang/rust#42761]
Something in this commit range is causing the TLS size to be calculated incorrectly, and the code accesses TLS addresses slightly beyond the size of the TLS:

The first commit and last commit in this range have been tested, with the first working and the last not working:
https://github.com/rust-lang/rust/compare/4bf5c99afc75f411a4e064150781eefc749c10df...0389d40ce0a891bc7d37ca15c12e23df79d71524

For example, `Command::new` attempts to access offset `0x100`, but the TLS is only `0xF0`

**Comment by jackpot51** [comment]
I have now narrowed it down to this: https://github.com/rust-lang/rust/compare/4bf5c99afc75f411a4e064150781eefc749c10df...27650ee8ab612cc3d5f4e3439b56b3a352177f44

**Comment by jackpot51** [comment]
So, the failure is as follows:
`Page fault: 04:000001FFFFFFFFF0 at 23:000000000040CF4A`

Where `0x1FFFFFFFFF0` is exactly 16 bytes beyond the end of TLS.

The readelf seems to indicate that the TLS is `0xF0` bytes in length:
```
Elf file type is EXEC (Executable file)
Entry point 0x400130
There are 4 program headers, starting at offset 64

Program Headers:
  Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
  LOAD           0x000000 0x0000000000400000 0x0000000000400000 0x02432c 0x02432c R E 0x200000
  LOAD           0x024340 0x0000000000624340 0x0000000000624340 0x001130 0x001230 RW  0x200000
  TLS            0x024340 0x0000000000624340 0x0000000000624340 0x0000e8 0x0000f0 R   0x20
  GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RW  0x10

 Section to Segment mapping:
  Segment Sections...
   00     .init .text .fini .rodata .eh_frame 
   01     .tdata .ctors .dtors .data .bss 
   02     .tdata .tbss 
   03  
```

Yet, it attempts to access address `0x100` in the TLS:
```
  40cf41:       64 48 8b 04 25 00 00 00 00    mov    rax,QWORD PTR fs:0x0
  40cf4a:       48 83 b8 00 ff ff ff 00      cmp    QWORD PTR [rax-0x100],0x0
```

Here you can find the good and bad binaries:
[init-test.tar.gz](https://github.com/rust-lang/rust/files/1086861/init-test.tar.gz)

**Comment by jackpot51** [comment]
I have opened this PR to temporarily fix this issue: https://github.com/rust-lang/rust/pull/42762

**Comment by steveklabnik** [comment]
Triage: this issue is very old. @jackpot51 is it still relevant?

**Comment by jackpot51** [comment]
It hasn't come up again, so maybe not
