### ISSUE TITLE
Documentation and search engines

### ISSUE THREAD

**Issue by Gedweb** [rust-lang/rust#42767]
After latest changes on doc.rust-lang.org, some documentation pages has been moved.
Search engins will give wrong results for a while we have pages like this https://doc.rust-lang.org/book/compiler-plugins.html with direct `200 OK` HTTP-status.
So need a send `301 Moved Permanently` for a search reindexation.

**Comment by frewsxcv** [comment]
https://github.com/rust-lang/rust/issues/42632

**Comment by Gedweb** [comment]
Second edition is partly incomplete.
A showing "choose page" is ugly way, if you look from SEO side - search engins can't handle it. We loose useful links on search positions and break brains of new programmers.

**Comment by steveklabnik** [comment]
The book has its own repo, and has this issue already: https://github.com/rust-lang/book/issues/760

Closing in favor of that, thank you!
