### ISSUE TITLE
Naked functions with arguments generate a prologue

### ISSUE THREAD

**Issue by Ekleog** [rust-lang/rust#42779]
When compiling

```rust
#[naked]
pub extern fn naked_test(_fubar: u64) {
    unsafe { asm!("int3") }
}
```
(https://is.gd/Q03g7b)

The generated assembly includes a prologue with unexpected `mov`'s (as well as a trailing `ret`, already reported in https://github.com/rust-lang/rust/issues/32487)

Expected behaviour would be to have no prologue (and prevent compilation of a `#[naked]` function that is not `extern` as this would require implementing an undefined ABI, contrarily to what seems to happen https://is.gd/sQFBIy).

This is treacherous, as it dereferences some memory locations that may not be accessible, as happened to me and led to hours of debugging to finally figure out the compiled function was not the one defined.

cc https://github.com/rust-lang/rust/issues/32408

**Comment by alexcrichton** [comment]
IIRC this is invalid and rustc should reject such a function, naked functions can't take arguments and the compiler should probably enforce that.

**Comment by Ekleog** [comment]
Hmm, my understanding of the RFC (“The following variant is not an error because the C calling convention is well-defined and it is thus possible for the programmer to write a conforming function”, even if the example is not with an argument) would mean that if the function is declared `extern`, then the function can actually respect the said ABI, thus should be well-formed?

**Comment by alistair23** [comment]
Is there an update on this?

I was hit by this issue as well. I hit the problem when compiling a tock app (baremetal-ish and jumped to by the tock OS)

A naked function with arguments would produce this prolog (RV32):

> 20430040 <_start>:
> #[cfg(target_arch = "riscv32")]
> #[doc(hidden)]
> #[no_mangle]
> #[naked]
> #[link_section = ".start"]
> pub unsafe extern "C" fn _start(
> 20430040:       fec42823                sw      a2,-16(s0)
> 20430044:       feb42623                sw      a1,-20(s0)
> 20430048:       fea42423                sw      a0,-24(s0)
> 2043004c:       fed42a23                sw      a3,-12(s0)
>     mem_start: usize,

Which would result in an invalid access as s0 would be 0.

Removing the arguments would remove the prologue and fix the problem.

Removing the naked cfg would also work as teh stack pointer was already setup by the OS and result in this.

> 20430040 <_start>:
> /// the stack then calls rust_start() for the remainder of setup.
> #[cfg(target_arch = "riscv32")]
> #[doc(hidden)]
> #[no_mangle]
> #[link_section = ".start"]
> pub unsafe extern "C" fn _start(
> 20430040:       1101                    addi    sp,sp,-32
> 20430042:       ce06                    sw      ra,28(sp)
> 20430044:       cc22                    sw      s0,24(sp)
> 20430046:       1000                    addi    s0,sp,32
> 20430048:       fec42823                sw      a2,-16(s0)
> 2043004c:       feb42623                sw      a1,-20(s0)
> 20430050:       fea42423                sw      a0,-24(s0)
> 20430054:       fed42a23                sw      a3,-12(s0)

If arguments with naked functions aren't supported rustc should generate an error as this is a difficult problem to debug.

**Comment by comex** [comment]
This is an LLVM bug.  Has it been reported upstream?
