### ISSUE TITLE
Some test folder contains too many test cases

### ISSUE THREAD

**Issue by earthengine** [rust-lang/rust#42770]
As a folder is a minimal unit of test case sets, it might takes too long to finish test if there are too many files and we want to add a single test into that folder and test for the new folder.

For example, src/test/run-pass contains 2500+ tests and took almost 20 mins to run through.

Test cases should be organised better and so we don't take too long to add a new test and verify a minimal set that includes the new test.

**Comment by sanxiyn** [comment]
See #20796 for the previous discussion.

**Comment by durka** [comment]
Is it useful to consider a folder as a "minimal unit" of tests? Where did you see that suggestion. You can run a single test: `./x.py test src/test/run-pass --stage 1 --test-args name_of_test.rs`.

**Comment by Mark-Simulacrum** [comment]
I don't really see it as feasible for us to split up tests (indeed, I've wanted more tests in the same folder but different categories before to make it easier to write and move them).

**Comment by Mark-Simulacrum** [comment]
I'm going to close this. I don't think we're moving to split test cases into folders, much, though I imagine a PR which grouped up test cases would maybe be accepted.
