### ISSUE TITLE
Current libc integration is a huge hack

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#42773]
Currently, the integration of the libc crate is very very hacky.

1. Its integrated as git submodule, and not as cargo dependency. 
2. It is used via a shim (`src/rustc/libc_shim`) for the sole purpose of passing a cfg flag `stdbuild` to the crate.

I propose we revive the `rustbuild` feature that has been removed by #42495 and:

1. Use libc from crates.io, without a shim, and removing the submodule
2. Either use cargo features, or revive the `rustbuild` cfg flag removed by #42495 and use it instead of `stdbuild`

**Comment by kennytm** [comment]
Is the `rustc_private` feature introduced by #41847 sufficient to replace the `rustbuild`/`stdbuild` feature?

**Comment by est31** [comment]
> Is the rustc_private feature introduced by #41847 sufficient to replace the rustbuild/stdbuild feature?

No its only a feature, it can't be used for conditional compilation. The libc crate [needs actual conditional compilation](https://github.com/rust-lang/libc/blob/master/src/lib.rs#L77-L79) (we can remove those last 3 lines probably, but not the 3 I marked).

**Comment by kennytm** [comment]
@est31 Ah right. Sorry. What about `cfg(any(stage0, stage1, stage2))`? 😄

(BTW is [this piece of code in `src/bootstrap/bin/rustdoc.rs`](https://github.com/rust-lang/rust/blob/380100c568c1c390c837caf98338d07c4d8a0462/src/bootstrap/bin/rustdoc.rs#L44-L49) just an oversight from #42495?)

**Comment by est31** [comment]
> What about cfg(any(stage0, stage1, stage2))?

Lol, lets not do *that*.

> (BTW is this piece of code in src/bootstrap/bin/rustdoc.rs just an oversight from #42495?)

I think so, yes.

**Comment by est31** [comment]
Okay I'll close this per discussion with @alexcrichton on IRC -- currently there seems no better way to solve this, due to dependencies on libcore/libstd.
