### ISSUE TITLE
Add builders to verify that packaging rust in a typical configuration works

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#42786]
This is intended to prevent issues such as https://github.com/rust-lang/rust/issues/42543. Ideally, we would run this as a Travis bot -- probably doesn't need to run tests, but uncertain.

Specifically, `--enable-local-rust`.

**Comment by est31** [comment]
In such an environment, we should also make sure that we don't depend on the network, to prevent bugs like #42719.

**Comment by Mark-Simulacrum** [comment]
Discussed during meeting: We think this is generally a good idea but specifics need to be worked out. Right now, our plan is to ask some distro (perhaps debian) for their configuration and test that stage0 bootstrap works with it. cc @alexcrichton

**Comment by est31** [comment]
One can apparently turn off network access via unshare: https://github.com/rust-lang/cargo/pull/4770#issuecomment-352872947

**Comment by Mark-Simulacrum** [comment]
We discussed this some more today and generally decided that we don't believe this is too viable to do today and is likely not too beneficial in general. We may revisit this in a more targeted manner later down the line (after CI migration concludes).
