### ISSUE TITLE
Tracking issue for std::io::Take::set_limit (take_set_limit)

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#42781]
Filing for https://github.com/rust-lang/rust/pull/42697 in the presumption that approval will go through.

**Comment by Mark-Simulacrum** [comment]
@rust-lang/libs Nominating for stabilization. Small, somewhat useful piece of functionality. Can be duplicated through `into_inner().take(N)`, so arguably we might not want this function since it adds needless complexity.

**Comment by sfackler** [comment]
@rfcbot fcp merge
