### ISSUE TITLE
request: report the number of compilation errors

### ISSUE THREAD

**Issue by hinaria** [rust-lang/rust#42793]
when i make a change and refactor some code, that single change sometimes results in 50 or 500 errors (at all call sites), and i'd like to have an idea of how many errors the change has caused.

right now, the only thing i can see is that my compilation failed, but i cannot tell whether i had 10 errors, 50 errors, or 500 errors because the compiler just says `error: aborting due to previous error(s)` . it is not possible to manually count this number - each error produces 10 - 15 lines of output, so 10 errors produces up to 150 lines of output, 50 errors 750.

thus, when i begin to fix errors i cannot tell how much progress i've made or how many remain since it's not reported! when i use other languages, i use the number of (remaining) errors all the time, even when i'm not refactoring. so this is an important quality of life item for me.

would we be open to including this number back into rust to say `aborting due to 52 error(s)` instead of some faceless amount?

---

- it appears rust previously did report the number of compilation errors, but it could be inaccurate (#33525)
- pr [#42150](https://github.com/rust-lang/rust/pull/42150/files) "fixed" this problem by hiding number of reported errors, instead opting to use a generic message that just says "errors exist"
- the machinery to count errors still remains, and that count is propagated all the way up to the point where we abort with a message. the only difference is that the abort message now ignores it.
- this is a personal opinion and i'm not sure if it would fly in the community, but i wouldn't mind if it only counts errors from the last pass. that's still much better than nothing. changes due to refactoring also mostly affect one pass at first, anyway.

**Comment by Mark-Simulacrum** [comment]
Nominating for compiler team: we should make a decision here and stick to it, and I'm inclined to say that restoring the old functionality also leads to reports of incorrect numbering. If we can fix the numbering (easily) then I'm all for it though, but last I looked this wasn't an easy task.

**Comment by Ixrec** [comment]
If completely fixing the numbers is non-trivial, is it feasible/acceptable to report "There were **at least** 10 errors"? Or is the count so buggy we don't even know a minimum?

**Comment by hinaria** [comment]
according to https://github.com/rust-lang/rust/issues/33525, the current implementation returns the number of errors in the last pass only.

so we do at least have a minimum!

**Comment by Mark-Simulacrum** [comment]
IIRC, I saw an issue recently about the returned value being 3 where it should've been 1, so I don't think that's true. It's possible that was due to old code though.

**Comment by nikomatsakis** [comment]
triage: P-medium

My feeling is that if we can get a correct count, that would be good. This doesn't seem too hard in principle, but I guess there are... obstacles.
