### ISSUE TITLE
Tracking issue for ptr::swap_nonoverlapping (library feature swap_nonoverlapping)

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#42818]
Proposed in PR https://github.com/rust-lang/rust/pull/42819.

This is semantically the same as a loop over ptr::swap, but with manual vectorization (from PR https://github.com/rust-lang/rust/pull/40454) to make it faster for cases (like `T == String`) where LLVM doesn't.

**Comment by SimonSapin** [comment]
In Nightly for 8 months, let’s stabilize.

@rfcbot fcp merge
