### ISSUE TITLE
Wrong ptr dereferencing in Alloc::alloc_one 

### ISSUE THREAD

**Issue by lseugene** [rust-lang/rust#42827]
```
    fn alloc_one<T>(&mut self) -> Result<Unique<T>, AllocErr>
        where Self: Sized
    {
        let k = Layout::new::<T>();
        if k.size() > 0 {
            unsafe { self.alloc(k).map(|p|Unique::new(*p as *mut T)) }
        } else {
            Err(AllocErr::invalid_input("zero-sized type invalid for alloc_one"))
        }
    }
```
@pnkfelix

**Comment by Mark-Simulacrum** [comment]
For context: https://github.com/rust-lang/rust/blob/74fa27928aceda1362a2266d9b9bf129999bc00a/src/liballoc/allocator.rs#L871-L880.

**Comment by sfackler** [comment]
Could you clarify what specifically is the problem with that implementation?

**Comment by lseugene** [comment]
I guess it's just typo.
We don't need to deref raw pointer p before cast it in ```Unique::new(*p as *mut T)```

**Comment by sfackler** [comment]
`p` isn't a raw pointer - it's a `Unique<T>`.

**Comment by lseugene** [comment]
Underlying alloc: https://github.com/rust-lang/rust/blob/74fa27928aceda1362a2266d9b9bf129999bc00a/src/liballoc/allocator.rs#L481
returns raw pointer *mut u8. alloc_one should just cast it to *mut T and wrap in Unique.
Please see correct implementation in alloc_array: https://github.com/rust-lang/rust/blob/74fa27928aceda1362a2266d9b9bf129999bc00a/src/liballoc/allocator.rs#L947
the diff and bug is in ```Unique::new(*p as *mut T) vs Unique::new(p as *mut T)```

**Comment by sfackler** [comment]
Oh no, casts `u8 to *mut T` strike again! :(
