### ISSUE TITLE
Import suggestions suggest inserting imports in the wrong place

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#42835]
For this kind of error:

```
pub mod foo {
    struct Foo;
}

fn main() {
    let a = Foo;
}
```

We get an error like

```
error[E0425]: cannot find value `Foo` in this scope
  --> <anon>:10:14
   |
10 |     let a = Foo;
   |             ^^^ not found in this scope
   |
help: possible candidate is found in another module, you can import it into scope
   | use foo::Foo;
```

Which is good. But if you put this whole example in a submodule and then look at the json error, the suggestion is add the import to the enclosing module, not the submodule, which is incorrect.

cc #42823, @oli-obk

**Comment by nrc** [comment]
And even in top level module the location for insertion is not great. I'm not sure how it chooses, it seems to change depending on the module layout. In some cases it inserts it at the start of the file (after any comments), which then breaks any inner attributes. IMO, it should find the last `use` in the current module and insert it after that. If there are no `use`s, then it should insert after any `extern crate` or `mod` statements and after any inner attributes.

**Comment by oli-obk** [comment]
The impl simply asks the current module for its inner span. I can check if it's also possible to get the AST of the module, so we can iterate through its items to find a good spot
