### ISSUE TITLE
libc.so.6 in project directory causes major problems

### ISSUE THREAD

**Issue by m4b** [rust-lang/rust#42851]
```
rustc --version
rustc 1.19.0-nightly (fe7227f6c 2017-06-16)
cargo --version
cargo 0.20.0-nightly (bbfe9b3a9 2017-06-05)
```

Steps to repro:

1. `cp` a `libc.so.6` to your project directory
2. run `cargo test` or `cargo build`

This might require an older libc.so.6, or something; looks like something is trying `dlopen`  the version in my directory (also, why?), and the ABI is bad for whatever reason (just guessing).

```
m4b@efrit ::  [ ~/git/panopticon ] cp libc.so.6 ~/projects/scroll
m4b@efrit ::  [ ~/git/panopticon ] cd
m4b@efrit ::  [ ~ ] cd projects/scroll
m4b@efrit ::  [ ~/projects/scroll ] cargo test
   Compiling scroll v0.6.0 (file:///home/m4b/projects/scroll)
rustc: error while loading shared libraries: __vdso_time: invalid mode for dlopen(): Invalid argument
error: Could not compile `scroll`.
Build failed, waiting for other jobs to finish...
rustc: error while loading shared libraries: __vdso_time: invalid mode for dlopen(): Invalid argument
error: Could not compile `scroll`.

To learn more, run the command again with --verbose.
```

Original issue: https://github.com/das-labor/panopticon/issues/304

**Comment by metux** [comment]
Why does the compile dlopen() anything from the source tree ?
And why does anything dlopen() libc ?

**Comment by m4b** [comment]
I had similar questions :laughing:

I wonder if I could ship a libc in a crates.io crate with a rewritten stub to the function it's trying to open to do random stuff on some users computer.

**Comment by sfackler** [comment]
Do you have `.` in your `LD_LIBRARY_PATH`?

**Comment by sfackler** [comment]
It's not clear to me why the assumption is that this is coming from a `dlopen` call. Why couldn't it be `ld.so`? You can try setting `LD_DEBUG=all` to have the dynamic linker print out info about what it's doing.

**Comment by m4b** [comment]
No I do not have "." in my LD_LIBRARY. 

To make this even easier, please copy your libc.so.6 to some new cargo project, open this new libc in your favorite hex editor, zero out the elf header, run cargo clean followed by cargo build and it will report that libc.so.6 has an invalid header...

**Comment by m4b** [comment]
I believe in this case it was assumed that dlopen was called because in the original report dlopen is explicitly mentioned as having a bad argument by rustc.

Of course it may be some side effect, etc. But on two separate machines I can repro this fairly worrisome issue (e.g. Local libc used without messing with LD env variables), which suggests that dlopen is used

**Comment by sfackler** [comment]
What does the output of `cargo clean && env LD_DEBUG=libs cargo build` say?

**Comment by m4b** [comment]
Ah I'm pretty sure this is caused by rustc using RPATH in dynamic array.

Also I think this might be a security vulnerability

**Comment by sfackler** [comment]
I do not see this behavior with a stock x86_64-unknown-linux-gnu 1.18 release, for reference.

```
        55:	find library=libc.so.6 [0]; searching
        55:	 search path=/usr/local/bin/../lib		(RPATH from file rustc)
        55:	  trying file=/usr/local/bin/../lib/libc.so.6
        55:	 search path=/tmp/foo/target/debug/deps/tls/x86_64:/tmp/foo/target/debug/deps/tls:/tmp/foo/target/debug/deps/x86_64:/tmp/foo/target/debug/deps		(LD_LIBRARY_PATH)
        55:	  trying file=/tmp/foo/target/debug/deps/tls/x86_64/libc.so.6
        55:	  trying file=/tmp/foo/target/debug/deps/tls/libc.so.6
        55:	  trying file=/tmp/foo/target/debug/deps/x86_64/libc.so.6
        55:	  trying file=/tmp/foo/target/debug/deps/libc.so.6
        55:	 search cache=/etc/ld.so.cache
        55:	  trying file=/lib64/libc.so.6
```

**Comment by m4b** [comment]
Something is setting LD path and it is not me. I believe it is cargo. Running strings on cargo shows that LD_LIB env variable is in the binary, and briefly grepping through source shows that it does collect a set of env variables, and LD_LIB is amongst them, which is even more worrisome.

Unfortunately not in front of a computer at the moment, so can't paste output but someone sets LD variable to the rustup nightly toolchain (amongst other things)

@sfackler are you not able to repro this ?

**Comment by m4b** [comment]
What about nightly cargo ?

**Comment by jmesmon** [comment]
```
% rustc -V
rustc 1.20.0-nightly (9475ae477 2017-07-11)
% cargo -V
cargo 0.21.0-nightly (eb6cf012a 2017-07-02)
% rustup -V
rustup 1.5.0
% cp /usr/lib/libSegFault.so libc.so.6
% cargo clean && env LD_DEBUG=libs cargo build
[...]
rustc: relocation error: libc.so.6: symbol getenv, version GLIBC_2.2.5 not defined in file libc.so.6 with link time reference
error: Could not compile `byteorder`.
[...]
```

And some output filtered to `libc.so` mentions:

```
      8694:	find library=libc.so.6 [0]; searching
      8694:	  trying file=/home/cody/g/vblock/target/debug/deps/libc.so.6
      8694:	  trying file=tls/x86_64/libc.so.6
      8694:	  trying file=tls/libc.so.6
      8694:	  trying file=x86_64/libc.so.6
      8694:	  trying file=libc.so.6
```

**Comment by m4b** [comment]
@sfackler could you paste entire output of LD_DEBUG=libs with and without libc.so.6 in project root directory ?

**Comment by m4b** [comment]
@jmesmon thank you, I was starting to think I was losing my mind ;)

I'm sure it's a nightly issue now (cannot repro on stable) and that someone (cargo I'm looking at you since the variable mysteriously appears after control is transferred to the one in rustup directory) is setting the env variable

**Comment by sfackler** [comment]
Ok yeah it does look like nightly cargo is messing this up:

```
      1325:	find library=libc.so.6 [0]; searching
      1325:	 search path=/tmp/foo/target/debug/deps:tls/x86_64:tls:x86_64::/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib		(LD_LIBRARY_PATH)
      1325:	  trying file=/tmp/foo/target/debug/deps/libc.so.6
      1325:	  trying file=tls/x86_64/libc.so.6
      1325:	  trying file=tls/libc.so.6
      1325:	  trying file=x86_64/libc.so.6
      1325:	  trying file=libc.so.6
rustc: error while loading shared libraries: libc.so.6: file too short
```

@alexcrichton

**Comment by alexcrichton** [comment]
Sorry I don't really understand anything here, not sure how much help I'll be

**Comment by sfackler** [comment]
@alexcrichton the root of the issue is that cargo's started producing a weird LD_LIBRARY_PATH:

```
/tmp/foo/target/debug/deps:tls/x86_64:tls:x86_64::/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib
```

This in particular includes `` (i.e. the current directory), as well as `tls` and `tls/x86_64`.

**Comment by sfackler** [comment]
In contrast, stable Cargo produces this LD_LIBRARY_PATH:

```
/tmp/foo/target/debug/deps/tls/x86_64:/tmp/foo/target/debug/deps/tls:/tmp/foo/target/debug/deps/x86_64:/tmp/foo/target/debug/deps
```

The fact that those `tls` and `x86_64` directories are involved at all is weird, but the specific bug here is the non-absolute paths.

**Comment by m4b** [comment]
I believe the tls and x86_64 prefixes can be ignored; I think it's the dynamic linker appending them, as I see the same issue when compiling a C program and passing `LD_LIBRARY_PATH=merp`

**Comment by sfackler** [comment]
Oh, weird!

**Comment by sfackler** [comment]
This is also present on beta

**Comment by brson** [comment]
@Mark-Simulacrum can you bisect cargo prs?

**Comment by mbrubeck** [comment]
I suspect #4006, which added lines like [this](https://github.com/mcgoo/cargo/blob/d773d7bb9391f1bdab442a070235ac2acb4adbb3/src/cargo/ops/cargo_rustc/compilation.rs#L110):

```rust
 search_path.push(self.host_dylib_path.iter().collect());
```

where `search_path` is a `Vec<PathBuf>` and `self.host_dylib_path` is an `Option<PathBuf>`.  If `self.host_dylib_path` is set to `None` then this will push an empty path into the search path.

**Comment by est31** [comment]
I've "bisected" the change to #41978 , which did [this update](https://github.com/rust-lang/cargo/compare/cf17c9f7118f544ec304ed6f50d92b3759487123...13d92c64d0153d95dbabeb49b828bbbef4b1bb34) of cargo, which seems to confirm @mbrubeck 's suspicion.

**Comment by est31** [comment]
Note that when running without rustup, I can't reproduce the bug.

**Comment by mbrubeck** [comment]
Submitted PR rust-lang/cargo#4278.

**Comment by brson** [comment]
Should be fixed on current beta. Can anyone confirm?

**Comment by m4b** [comment]
:thumbs_up:

Fixed for me! Great work!
