### ISSUE TITLE
libc rust library is not supported on ppc64le

### ISSUE THREAD

**Issue by seth-priya** [rust-lang/rust#42858]
Hi, 

I am trying to build a rust based package tikv,
https://github.com/pingcap/tikv on ppc64le. 

This package has a dependency on the libc rust library
https://github.com/pingcap/tikv/blob/master/Cargo.toml

Looking at the libc code, specifically 
https://github.com/rust-lang/libc/blob/2015cf17a6a2a2280e93d9c57214ba92dbbaf42f/src/lib.rs
it looks like libc is not supported on ppc64le arch.

To that end, I was trying to understand what all would be required to add the support and had a few questions.

1- It looks like, we will need to have crate doc available for ppc64le, something similar to the one for x86_64 here:
http://rust-lang.github.io/libc/x86_64-unknown-linux-gnu/libc/index.html
The query I had was around generating the information in this specific format. Is there a specific tool or generator that can generate this document for a given arch?

2- Once, I have this crate doc in place and have made the necessary changes to lib.rs, would any additional changes be required elsewhere to add support for the new arch?

3 - Once, support has been added locally, is there a way to test my app (tikv) with the local changes? It seems that re-building and re-installing rust might not be sufficient as libc is fetched at runtime from a registry (https://github.com/rust-lang/crates.io-index?) and the lib.rs that gets installed on the system is quite different from the one that is present in the source code?

Any pointers on the above queries would be of great help in proceeding with this. Thanks in advance!

Regards,
Priya

**Comment by cuviper** [comment]
It doesn't have published documentation, nor CI testing, but powerpc64le libc does work from the support in [powerpc64.rs](https://github.com/rust-lang/libc/blob/2015cf17a6a2a2280e93d9c57214ba92dbbaf42f/src/unix/notbsd/linux/other/b64/powerpc64.rs) for both endians.  However, that's in libc 0.2, and tikv has an indirect dependency on libc 0.1 via utime 0.1 [here](https://github.com/pingcap/tikv/blob/1974ab261292bdcb190966aaf1f69d5910a70acb/Cargo.lock#L1020).  If they update to utime 0.2, then it should use the newer libc all around.

**Comment by cuviper** [comment]
FWIW, I tried updating just tikv's utime, and then it fails compiling nix.  It looks like newer nix does have ppc64 support, but it will require updating a few more tikv dependencies to get there.  I suggest filing an issue with tikv to get everything updated for better platform compatibility.

**Comment by alexcrichton** [comment]
Ah yes the `libc` crate does indeed have support for ppc64le, so it sounds like this is an upstream issue in perhaps nix or older dependencies, so closing.

**Comment by seth-priya** [comment]
@cuviper and @alexcrichton - Thanks a lot for looking into this and responding. I will take this up further with the tikv community.
