### ISSUE TITLE
Deflate settings changed when replacing in-tree flate with flate2

### ISSUE THREAD

**Issue by oyvindln** [rust-lang/rust#42879]
In the [pr](https://github.com/rust-lang/rust/pull/42664) that replaced the in-tree flate library, with flate2, there were some changes to how the compression was used, that may not have been intentional. I was suggested to make an issue after commenting there as the PR was already merged.

Is using the [`Compression::Default`](https://github.com/rust-lang/rust/pull/42664/commits/a4024c58e1e5c92cfe3ed39ed9f5b96f3f38122e#diff-1b71e145dde424ac83e674eef22373d8R575) compression level intended? The flate functions were changed to use a faster compression level some time ago (see #37298), going back to a higher compression setting could cause some performance regressions. I think the previous settings would be equal to using the `Compression::Fast` setting in flate2.

Also, the old functions [didn't use a zlib wrapper](https://github.com/rust-lang/rust/pull/42664/commits/a4024c58e1e5c92cfe3ed39ed9f5b96f3f38122e#diff-0d79b8268f4ae23d86e5c04fe8a3f502L98) from what I can see (there is a flag for that), but the new code [does](https://github.com/rust-lang/rust/pull/42664/commits/a4024c58e1e5c92cfe3ed39ed9f5b96f3f38122e#diff-70b2d0110e1bf5edce7452fb1e35ec9bR865). Don't know if this could cause some issues when trying to use libs from different versions, though at least it adds 6 bytes of overhead due to the header and checksum.

**Comment by Mark-Simulacrum** [comment]
cc @alexcrichton 

Seems like going back to a lower compression level here is a good idea at least. I don't know if worrying about the zlib wrapper is too important though.

**Comment by oyvindln** [comment]
The zlib wrapper could cause problems if trying to compress data with the zlib wrapper using the functions that don't expect it, and vice versa. I don't know if rustc will read the rlib files from a different version though, so this may or may not be an issue. Changing this back to the old behaviour is just changing to use the reader/writers that operate on raw deflate streams so it would be very easy to change if it's needed.

**Comment by alexcrichton** [comment]
Ah yes no functional changes were intended! Should be easy to switch back to the deflate scheme and switch the compression level!
