### ISSUE TITLE
AsMut<T> should have AsRef<T> as a supertrait

### ISSUE THREAD

**Issue by whitequark** [rust-lang/rust#42878]
I'm not sure why isn't it already so; `BorrowMut<T>` has `Borrow<T>` as a supertrait so `AsMut`/`AsRef` seem like they should be obviously the same.

I couldn't find any issues, PRs or RFCs discussing this so I'm opening an issue here to discuss. This is strictly backwards incompatible, of course, but it also seems extremely unlikely to break any code in the wild, so how about making a crater run with this change? What's the process here?

**Comment by Mark-Simulacrum** [comment]
Unfortunately I don't think this'll be a backwards compatible change today, though in principle it does seem correct.

**Comment by tbu-** [comment]
`Mutex` can implement `AsMut` but not `AsRef`.

**Comment by whitequark** [comment]
@tbu- `AsMut` and `AsRef` may not fail. How can `Mutex` possibly implement them?

**Comment by tbu-** [comment]
Forgot that they can be poisoned, but a `Mutex` that cannot be poisoned can implement `AsMut`: [`Mutex::get_mut`](https://doc.rust-lang.org/std/sync/struct.Mutex.html#method.get_mut).

`AtomicUsize` can implement `AsMut` but not `AsRef`.

**Comment by whitequark** [comment]
@tbu- If you are holding a `&mut Mutex<T>` then it is safe to get as many `&T` from it as you want. Similar for AtomicUsize. In both cases the synchronization part of the primitive might as well not exist because a stronger guarantee is statically provided by the borrow checker.

**Comment by whitequark** [comment]
Nevermind my previous comment, it was wrong.

**Comment by whitequark** [comment]
@tbu- While I acknowledge that it would be legal to add the impls you suggest I think the same ought to apply to Borrow/BorrowMut. Why would it not be? Why should we not remove the Borrow supertrait from BorrowMut (which I believe is backwards-compatible)?

**Comment by tbu-** [comment]
Mh. I agree that `BorrowMut` and `Borrow` ought to be the same. Which one (inheriting or not) is not clear to me though.

Unfortunately, the other way is also not backwards-compatible, if you have a `T: BorrowMut`, you can also use the `Borrow` functions.

**Comment by dtolnay** [comment]
I don't know whether BorrowMut is correct with its supertrait or AsMut is correct without, but I also don't know why it would be correct for them to be different. In any case basically anything we change here would be backward incompatible so this is going on the rust-2-breakage-wishlist.
