### ISSUE TITLE
wrong code regression: HashSet initialization

### ISSUE THREAD

**Issue by Dushistov** [rust-lang/rust#42918]
Idea of bug is simple:

```rust
use std::collections::HashSet;

#[derive(PartialEq, Debug, Hash, Eq, Clone)]
enum SentenceType {
    None,
    AAM,
    //...many
    RMC,
    GGA,
    //..many
}

fn f(s: HashSet<SentenceType>) {
    println!("s: {:?}", s);
}

fn main() {
    f([SentenceType::RMC, SentenceType::GGA]
          .iter()
          .cloned()
          .collect());
}
```

On stable today compiler `rustc 1.18.0 (03fc9d622 2017-06-06)` it print as expected `{RMC, GGA}`, but if use beta/nightly it prints all variants from `SentenceType`.

**Note**: that the code above  is just sketch, to realy reproduce problem you need android/arm cpu (may be works with other/arm, but I not able to check right now),
and two crates, in attachment crate that reproduce problem,
to run it you may use such commands:

```sh
adb shell mkdir /data/sample
cargo build   --target=arm-linux-androideabi --release
adb push target/arm-linux-androideabi/release/hashset_bug /data/sample/
adb shell 'RUST_LOG=debug /data/sample/hashset_bug'
```
With stable it produces such output:
```
DEBUG:hashset_bug: Hello, world!
DEBUG:nmea: create_for_navigation-beta: arg {RMC, GGA}
DEBUG:nmea: create_for_navigation: our {RMC, GGA}
```
with beta/nightly it prodcues such output:
```
DEBUG:hashset_bug: Hello, world!
DEBUG:nmea: create_for_navigation-beta: arg {MTW, GTD, DSI, ZDL, RMB, MWD, DSR, TUT, ZDA, RSA, HSC, CUR, RSD, OLN, XDR, RTE, ABK, DBK, SFI, HDG, BWR, GRS, DTM, LRF, MWV, ACA, TLB, HTD, SSD, GSV, RMA, MSK, APB, MSS, GLC, HDT, WCV, VHW, ACK, MLA, ASD, GXA, RMC, APA, ZFO, LR3, GNS, AAM, ZTG, GGA, FSI, BWW, XTR, VPW, AIR, VWR, XTE, BWC, LRI, BEC, TTM, LR2, LCD, ROT, VDO, GBS, GMP, VDR, GSA, RPM, ALM, VSD, GST, TRF, LR1, DCN, VDM, DPT, TXT, VLW, HMR, DSE, None, VBW, BOD, GLL, VTG, DBS, WNC, TLL, ACS, DSC, ALR, STN, DBT, HMS, HDM}
DEBUG:nmea: create_for_navigation: our {MTW, GTD, DSI, ZDL, RMB, MWD, DSR, TUT, ZDA, RSA, HSC, CUR, RSD, OLN, XDR, RTE, ABK, DBK, SFI, HDG, BWR, GRS, DTM, LRF, MWV, ACA, TLB, HTD, SSD, GSV, RMA, MSK, APB, MSS, GLC, HDT, WCV, VHW, ACK, MLA, ASD, GXA, RMC, APA, ZFO, LR3, GNS, AAM, ZTG, GGA, FSI, BWW, XTR, VPW, AIR, VWR, XTE, BWC, LRI, BEC, TTM, LR2, LCD, ROT, VDO, GBS, GMP, VDR, GSA, RPM, ALM, VSD, GST, TRF, LR1, DCN, VDM, DPT, TXT, VLW, HMR, DSE, None, VBW, BOD, GLL, VTG, DBS, WNC, TLL, ACS, DSC, ALR, STN, DBT, HMS, HDM}
```
[hashset_bug.zip](https://github.com/rust-lang/rust/files/1103480/hashset_bug.zip)

**Comment by nikomatsakis** [comment]
Nominating. cc @rust-lang/compiler -- anybody have any ideas what's going on with this ARM codegen regression?

**Comment by Mark-Simulacrum** [comment]
So we've updated to LLVM 4.1 since then (https://github.com/rust-lang/rust/pull/42930) -- I suspect that may well have fixed this problem. Perhaps @Dushistov could check on a recent nightly? In case the problem isn't quite fixed, cc @arielb1

**Comment by Dushistov** [comment]
@Mark-Simulacrum 

>So we've updated to LLVM 4.1 since then (#42930) -- I suspect that may well have fixed this problem. 

Yes, with rustc `1.20.0-nightly (696412de7 2017-07-06)` all ok.

At now only `1.19.0-beta.2 (a175ee509 2017-06-15)` FAILED.

**Comment by Mark-Simulacrum** [comment]
I believe that the fix is backported, just we haven't released a new beta yet.

**Comment by brson** [comment]
It looks to me like the llvm patch has not been backported yet. I will do so today.

**Comment by Mark-Simulacrum** [comment]
@brson https://github.com/rust-lang/rust/pull/42948 appears to be the backport?

**Comment by brson** [comment]
@Mark-Simulacrum hm so it is. it is tagged incorrectly.

**Comment by brson** [comment]
beta.3 is out with the LLVM backport. Can anyone confirm a fix?

**Comment by Dushistov** [comment]
@brson `rustc 1.19.0-beta.3 (4b6f4f353 2017-07-07)` fix issue. Any ideas how to reduce test case, or it is small enough for regression test?

**Comment by brson** [comment]
Thanks for confirming @Dushistov. I don't offhand know how to reduce the test case though. Sorry!

**Comment by Dushistov** [comment]
I was able to reduce the test to this code:

```rust
use std::collections::HashSet;

#[derive(PartialEq, Debug, Hash, Eq, Clone)]
enum MyEnum {
    E0,

    E1,

    E2,
    E3,
    E4,

    E5,
    E6,
    E7,
}


fn main() {
    let s: HashSet<_> = [MyEnum::E4, MyEnum::E1].iter().cloned().collect();

    println!("Expect only E1+E4 got {:?}", s);
}
```

it prints
> Expect only E1+E4 got {E4, E0, E6, E3, E7, E1, E2, E5}
on buggy compier
