### ISSUE TITLE
Bounds for `RwLock<T>: Send` are unnecessarily restrictive

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#42934]
Currently, `RwLock<T>: Send` requires `T: Send` *and* `T: Sync`. It would be sufficient to requires `T: Send`. (Transmitting an `RwLock` can't move an `&T` across thread boundaries.)

Is there interest in relaxing these kinds of bounds? Or, maybe, at least document the fact that the bounds could be more relaxed in the source?

**Comment by dtolnay** [comment]
This bound was relaxed in #45267.
