### ISSUE TITLE
for x in 0..4294967296 

### ISSUE THREAD

**Issue by mabels** [rust-lang/rust#42937]
Hello,

is this behaviour intended? 
This loop "for x in 0..4294967296 " does nothing?
And there is no warning no nothing?

thx in advance

meno

**Comment by kennytm** [comment]
😕 There is a warning...

```rust
warning: literal out of range for i32
 --> <anon>:2:17
  |
2 |     for x in 0..4294967296 {
  |                 ^^^^^^^^^^
  |
  = note: #[warn(overflowing_literals)] on by default
```

The number will be wrapped to `0` and the compile sees the range as `0 .. 0` i.e. empty.

**Comment by mabels** [comment]
sorry, i looked twice an overlooked it twice.
