### ISSUE TITLE
can't find crate for `core`

### ISSUE THREAD

**Issue by jesse99** [rust-lang/rust#4294]
This error can happen when a crate depends upon another crate which depends upon a different version of a crate they both share. It's a very poor error message though because:

* It's misleading (the problem is that the crates were incompatible not that core could not be found: both versions of core were present).
* It doesn't provide any context. Which crates are involved? What are the version numbers of the incompatible crates?

One way to debug this is to do `rustc --ls` on each crate you depend upon and see if the common crate version numbers match up.

**Comment by steveklabnik** [comment]
Can anyone provide a way to reproduce this kind of issue?

**Comment by steveklabnik** [comment]
Well, it's been a few months. With our current installers and such, I think we should try to handle specific instances of this issue, but I don't think that there's anything specifically actionable here.
