### ISSUE TITLE
Wrong "possible better candidate is found in another module" suggestion

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#42944]
For this code:

```rust
mod foo {
    pub struct B(());
}
mod bar {
    use foo::B;
    fn foo() {
        B(());
    }
}
```

You get the following error message:

```
error[E0423]: expected function, found struct `B`
 --> <anon>:7:9
  |
7 |         B(());
  |         ^
  |         |
  |         did you mean `B { /* fields */ }`?
  |         constructor is not visible here due to private fields
  |
help: possible better candidate is found in another module, you can import it into scope
  | use foo::B;
```

The suggestion may be excused to be not 100% perfect, but here it suggests to add an use statement despite that same item being imported already. What I want is this exactly: that it removes stuff from the suggestion list that is already being imported.

Note that changing the glob import to a non glob one doesn't change anything.

**Comment by est31** [comment]
cc @estebank

**Comment by oli-obk** [comment]
Why is that even an error?

**Comment by est31** [comment]
@oli-obk tuple structs have private fields by default, you can't construct instances of B outside of the foo module.

**Comment by oli-obk** [comment]
oh ^^ maybe we should simply modify this error message then to say that the "function" is private?

**Comment by est31** [comment]
It already says "constructor is not visible here due to private fields". That's okay, but maybe you might have meant another B from another module or something. However, the candidate offered is not any better as its the same one you are attempting to use.

**Comment by estebank** [comment]
Reopening to track "removal of suggestion" work for pub tuple structs with private fields.
