### ISSUE TITLE
E0613 needs to be merged into E0609 now

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#42945]
With RFC 1506 merged and stabilized, handling `E0613` separate from `E0609` is not the correct behaviour any more.

For context, you get `E0613` when doing something like `let _ = "hi".0;`:

```
error[E0613]: attempted to access tuple index `0` on type `&'static str`, but the type was not a tuple or tuple struct
```

And you get `E0609` when doing something like `let _ = "hi".foo;`:

```
error[E0609]: no field `foo` on type `&'static str`
```

[RFC 1506 "clarified ADT kinds"](https://github.com/rust-lang/rfcs/pull/1506) ([Rendered](https://github.com/rust-lang/rfcs/blob/master/text/1506-adt-kinds.md), [tracking issue](https://github.com/rust-lang/rust/issues/35626)) allowed all structs to contain fields with integral names like `0` or `1`, etc. This makes the error message for `E0613` outdated, as the type may be a non tuple struct, and calling `0` a "tuple index" sounds wrong as well.

So I propose `E0613` to be merged into `E0609`, as `E0609` is now better suiting, and also because its "in the spirit" of the RFC.

The proposed new output for `let _ = "hi".0;` is:
 
```
error[E0609]: no field `0` on type `&'static str`
```

**Comment by nikomatsakis** [comment]
Makes sense to me!

**Comment by nikomatsakis** [comment]
Here are some brief mentoring instructions:

- E0613 is issued [here, in librustc_typeck](https://github.com/rust-lang/rust/blob/33ecf72e8e26b5bf5449ae27297e83c9f78aa3ad/src/librustc_typeck/check/mod.rs#L3085-L3088).
- E0609 is issued [here](https://github.com/rust-lang/rust/blob/33ecf72e8e26b5bf5449ae27297e83c9f78aa3ad/src/librustc_typeck/check/mod.rs#L2966-L2968).
- We basically need to introduce a common helper function and call it from both places. A helper is needed because you can't have more than one place in the source code that uses a single error code (in this case, E0609).

**Comment by Boreeas** [comment]
Hi! I'd like to take this issue, if no one minds?

**Comment by Mark-Simulacrum** [comment]
Go right ahead! Let us know if you'd like additional instructions and we'll try to connect you with @nikomatsakis or someone else from the compiler team.

**Comment by GuillaumeGomez** [comment]
Or I can as well since I'm the one who added these two error codes.

**Comment by Boreeas** [comment]
While I'm at it, E0612 looks like it could be folded into E0609 too. Should I go ahead and do that?

**Comment by est31** [comment]
> While I'm at it, E0612 looks like it could be folded into E0609 too.

I can be, not sure whether it should. It seems we can actually recognize when we have a tuple struct, so we won't generate the error if it is wrongly placed. However it might be against the spirit of the RFC. @petrochenkov as author of the RFC, what do you think, should E0612 be merged into E0609?

**Comment by petrochenkov** [comment]
@est31 
I'd say yes, because I'm generally for removing code and special cases in case of doubt, but people managing diagnostics often hold the opposite position.

**Comment by Boreeas** [comment]
Should unused diagnostic codes just be removed, or commented out with a reference that the diagnostic has been folded into another?
