### ISSUE TITLE
constexpressions for floating values are not checked against size of constant

### ISSUE THREAD

**Issue by amarao** [rust-lang/rust#42943]
rustc 1.17.0

If constexpression for floating couldn't fit in a given type, rustc prints no warning.
```
fn main() {
    const X: f32 = 0.00000000000000001/100000000000000000000000000000.0;
    println!("The value of x is: {}", X);
}
```

Expected: warning: literal (constexpr?) out of range for f32
Actual: success, output is 0.

**Comment by est31** [comment]
The non special values of 32 and 64 bit floats are a finite subset of the real numbers. You can visualize them as a bunch of dots on the number line, each dot representing a possible float value. All points on the number line that are not dots can't be represented as float. Some numbers can't be represented, and for such you chose the closest dot to represent it. Now, your example is one of such numbers: it can't represent a fraction this small, so it chooses 0 as the "closest dot" to represent the result.

This kind of behaviour is expected, and normal. You also can't just simply turn it off in the constexpr context and error every time you need to do such a "take the closest dot" approximation, as many numbers that seem simple to you aren't, [like 0.1](http://www.exploringbinary.com/why-0-point-1-does-not-exist-in-floating-point/) and would error in such a case.

**Comment by amarao** [comment]
But at the same time Rust warns when one tries to store too small or too big number in float: `warning: literal out of range for f32`.

**Comment by oli-obk** [comment]
With const eval becoming more general purpose it is basically impossible to figure out whether the situation is an expected lossy operation or an unexpected one. I don't think we can act on this issue. I don't know if checked float math libraries exist like the `checked_add` the libstd has for for integer types, but I'd think that this should be solved in a library (if at all).

There's some related discussion in https://github.com/rust-lang/rust/issues/77745 and https://rust-lang.zulipchat.com/#narrow/stream/146212-t-compiler.2Fconst-eval/topic/const.20eval.20of.20SIMD.20ops/near/214507879
