### ISSUE TITLE
Use non-capturing closure to fn conversion when 1.19 released

### ISSUE THREAD

**Issue by stepancheg** [rust-lang/rust#42942]
Code like this:

```
fn foo() {}

fn main() {
    let a: fn() = || {};
}
```

is allowed since rust 1.19.

As soon as 1.19 becomes stable, generated code should start using non-capturing closures instead of functions like `get_xxx_for_reflect`.

**Comment by Mark-Simulacrum** [comment]
Could you clarify what this is about specifically? I can't find `get.*for_reflect` in the compiler source. Also, I'm not sure this is a good idea -- accidentally sneaking in a capture into a closure seems more likely (it'll fail at compile time, but the message might be worse).

**Comment by stepancheg** [comment]
Oops, I'm sorry, I've opened the issue in the wrong project.

**Comment by stepancheg** [comment]
> Also, I'm not sure this is a good idea -- accidentally sneaking in a capture into a closure seems more likely (it'll fail at compile time, but the message might be worse).

JFYI, it is to simply to reduce generated code side which is currently too large.
