### ISSUE TITLE
#[repr(align(x))] is limited to 32768

### ISSUE THREAD

**Issue by Ekleog** [rust-lang/rust#42960]
In some cases, the hardware imposes natural alignment for some data (ie. data aligned to its length). For example, the ARM Memory Protection Unit.

This can happen even when handling large structs (eg. `0x10000`-sized buffers). These buffers would thus require an alignment of `0x10000`. Which appears not to be possible with `#[repr(align(x))]`, that appears limited to 32768.

I'm currently using the following (ugly, esp. because of the absence of type-level integers) workaround to get the aligned data I need:
```rust
pub struct Aligned {                                                        
   unaligned: [u8; 0x100000]                                                    
}                                                                                
pub static mut DATA: Aligned = Aligned { unaligned: [0; 0x100000] };
impl Aligned {                                                              
   pub fn get(&self) -> &[u8] {                                                  
       let begin_addr = &self.unaligned[0] as *const _ as usize;                
       let aligned_begin_addr = (begin_addr & !0x7FFFF) + 0x80000;              
       let offset = aligned_begin_addr - begin_addr;                            
       &self.unaligned[offset..(offset+0x80000)]                                
   }                                                                            
   pub fn get_mut(&mut self) -> &mut [u8] {                                      
       let begin_addr = &self.unaligned[0] as *const _ as usize;                
       let aligned_begin_addr = (begin_addr & !0x7FFFF) + 0x80000;              
       let offset = aligned_begin_addr - begin_addr;                            
       &mut self.unaligned[offset..(offset+0x80000)]                            
   }                                                                            
}  
```

If I can manually do it, I don't really get why rustc wouldn't be able to do it (esp. with http://www.cs.brandeis.edu/~cs146a/rust/doc-02-21-2015/rustc/lib/llvm/fn.LLVMSetAlignment.html taking an u32 as input)?

Is there a technical issue or is this just a current implementation limitation?

As this behaviour is not specified in RFC1358, cc'ing https://github.com/rust-lang/rust/issues/33626

Disclaimer: I'm not actually running this code on an ARM MPU-enabled chip, but explaining the actual use case would be too long and complex and the issue is exactly the same, so I just picked this example.

**Comment by mattico** [comment]
Interesting. I wonder if this limitation is specific to ARM? If https://github.com/rust-lang/rust/issues/30170 is still current (and it seems to be: https://github.com/rust-lang/rust/issues/32838) then you should be able to use huge alignments. If you couldn't then you wouldn't be able to trigger the buggy behavior in the OSX allocator.

**Comment by Ekleog** [comment]
#30170 appears to be only for alignment using the allocator, so not covering all the cases of `#[repr(align(x))]` (which also covers the “on the stack” case).

I have been pointed to https://github.com/rust-lang/rust/blob/9b5b514c8dfe241fe88420c668eb040e2c36c686/src/librustc/ty/mod.rs#L1389 ; so I guess it's at least in part an issue in the types used (u16's biggest power-of-two value being 32768)?

**Comment by PlasmaPower** [comment]
The limit comes from here: https://github.com/rust-lang/rust/blob/686ec28ceaedb2a26423d48b90da210d491915cc/src/librustc/ty/layout.rs#L287-L289

**Comment by Ekleog** [comment]
Thanks! So, the blame seems to show it all came from the same commit that introduced the `layout` module.

Could that be premature optimization, or do you think there is a strong performance case for having the alignment restricted this way?

**Comment by PlasmaPower** [comment]
No idea, I just traced the alignment variable through the code. I can try to change it, but I don't know much about this stuff. I'm assuming 2^31 would be more than enough?

**Comment by sfackler** [comment]
@Ekleog It looks like it's just trying to optimize compiler memory usage by keeping the size of the alignment info small. We should just be able to bump that to `u16` or whatever's necessary.

**Comment by PlasmaPower** [comment]
@sfackler I'm currently working on that.

**Comment by Ekleog** [comment]
Yeah, 2^31 is ~2GB, I think it would be enough for all practical purposes (the only cases I know of required natural alignment for large arrays are for embedded devices, which don't have that much memory anyway -- while 2^15 is 32kB which stays under the “existing” limit)

Thanks @PlasmaPower !

**Comment by PlasmaPower** [comment]
I understand the code a bit better now. It was dividing a u8 into 2 nibbles, for the abi and preferred alignments. Instead of using a u16, I'm just using 2 `u8`s.

PR should be up shortly, currently working on tests.

**Comment by PlasmaPower** [comment]
#43097 created to fix this.

**Comment by Ekleog** [comment]
Thanks!
