### ISSUE TITLE
“error: invalid operand for inline asm constraint 'i'” with enum members

### ISSUE THREAD

**Issue by Ekleog** [rust-lang/rust#42974]
Hello,

It looks like in some cases (ie. not enough optimizations turned on), enum members cannot be used as 'i' operands for inline assembly:
```rust
#![feature(asm)]

#[repr(usize)]
enum Foo {
    Bar = 1,
}

fn main() {
    unsafe {
        asm!("" :: "i" (9isize), "i" (Foo::Bar));
    }
}
```
http://play.integer32.com/?gist=befc6872b583ffaa1609f081b7536b50&version=nightly

Given this is (with macros, maybe?) the only use I can think of 'i' operands, I think it is reasonable to say the 'i' operand is currently broken.

This would be solved by even the slightest level of constant folding, so I think even in debug mode it should actually constant fold to something that builds, and not have successful compilation be dependent of the specific compiler version and flags used (as is currently the case).

**Comment by parched** [comment]
Same underlying issue as  https://github.com/rust-lang/rust/issues/41337 I guess.

**Comment by eddyb** [comment]
Fix might be easy, see https://github.com/rust-lang/rust/blob/54b7d21f59a363e53eb1c31d76b40af2ff99321c/src/librustc_mir/transform/promote_consts.rs#L219-L238.

**Comment by Amanieu** [comment]
This issue does not apply to the new `asm!` ([RFC 2850](https://github.com/rust-lang/rfcs/pull/2850)) which has stricter checks on the types that can be used as asm operands.

The legacy `llvm_asm!` is deprecated and is no longer maintained.
