### ISSUE TITLE
rustup-init.exe: Update Visual Studio C++ build tools

### ISSUE THREAD

**Issue by mcandre** [rust-lang/rust#42970]
Could we update the rustup-init.exe installer for Windows? It recommends that users install an older set of build tools, the 2015 ones, whereas Microsoft has since released a 2017 set of build tools.

**Comment by mattico** [comment]
The repo for rustup is over here: https://github.com/rust-lang-nursery/rustup.rs

As to your suggestion, I'd probably wait to update the message until the 2017 build tools are supported by rust stable. The support for them was [added recently](https://github.com/rust-lang/rust/pull/42225), I think they'll be in 1.20.0

**Comment by steveklabnik** [comment]
That's all correct. Thanks!
