### ISSUE TITLE
inefficient abstraction for max and min iterators

### ISSUE THREAD

**Issue by jaupe** [rust-lang/rust#42980]
I have been benchmarking aggregations in Rust and empirically discovered that the max and min iterators appear to be inefficient abstractions. I noticed that they are roughly double the time compared to a hand-written for loop

```
#[inline]
fn vec_max<T: Ord + Copy>(v: &[T]) -> Option<T> {
    if v.is_empty() {
        return None;
    }
    let mut max_val = v[0];
    if v.len() == 1 {
        return Some(max_val);
    }
    for val in &v[1..] {
        if *val > max_val {
            max_val = *val;
        }
    }
    Some(max_val)
}

test engine::tests::bench_vec_iter_max     ... bench:  36,254,272 ns/iter (+/- 3,841,473)
test engine::tests::bench_vec_max          ... bench:  12,162,150 ns/iter (+/- 2,757,891)
```

It looks like this abstraction is not efficient:

```
    // start with the first element as our selection. This avoids
    // having to use `Option`s inside the loop, translating to a
    // sizeable performance gain (6x in one case).
    it.next().map(|mut sel| {
        let mut sel_p = f_proj(&sel);

        for x in it {
            let x_p = f_proj(&x);
            if f_cmp(&sel_p, &sel, &x_p, &x) {
                sel = x;
                sel_p = x_p;
            }
        }
        (sel_p, sel)
    })
```

I will have a look into what's being produced and see if it can be made equivalent to a hand-written for loop.

**Comment by Mark-Simulacrum** [comment]
Can you post the full benchmark code (both the iterator and non-iterator versions)? That would help with testing locally and trying to find the problem.

**Comment by leonardo-m** [comment]
Some time ago I've seen a difference:

    #![feature(ord_max_min)]
    #![allow(private_no_mangle_fns)]

    #[inline(never)]
    #[no_mangle]
    fn foo1(a: u32, b: u32, c: u32) -> u32 {
        *[a, b, c].iter().min().unwrap()
    }

    #[inline(never)]
    #[no_mangle]
    fn foo2(a: u32, b: u32, c: u32) -> u32 {
        [a, b, c].iter().cloned().min().unwrap()
    }

    #[inline(never)]
    #[no_mangle]
    fn foo3(a: u32, b: u32, c: u32) -> u32 {
        a.min(b).min(c)
    }

    fn main() {
        println!("{}", foo1(1,2,3));
        println!("{}", foo1(10,20,5));
        println!("{}", foo2(1,2,3));
        println!("{}", foo2(10,20,5));
        println!("{}", foo3(1,2,3));
        println!("{}", foo3(10,20,5));
    }

    /*
    foo1:
        subq    $16, %rsp
        movl    %ecx, 4(%rsp)
        leaq    8(%rsp), %rax
        movl    %edx, 8(%rsp)
        leaq    12(%rsp), %r9
        movl    %r8d, 12(%rsp)
        cmpl    %edx, %ecx
        leaq    4(%rsp), %rcx
        cmovaq  %rax, %rcx
        cmpl    %r8d, (%rcx)
        cmovaq  %r9, %rcx
        movl    (%rcx), %eax
        addq    $16, %rsp
        retq


    foo2:
        cmpl    %edx, %ecx
        cmoval  %edx, %ecx
        cmpl    %r8d, %ecx
        cmoval  %r8d, %ecx
        movl    %ecx, %eax
        retq


    foo3:
        cmpl    %edx, %ecx
        cmovbel %ecx, %edx
        cmpl    %r8d, %edx
        cmoval  %r8d, %edx
        movl    %edx, %eax
        retq

    */

**Comment by jaupe** [comment]
So here's the code to replicated the benchmarks 

```
    #[bench]
    fn bench_vec_iter_max(b: &mut Bencher) {
        let n = 5;
        let v: Vec<i32> = (0..n).map(|x| x as i32).collect();
        b.iter(|| v.iter().max())
    } 

    #[bench]
    fn bench_vec_max(b: &mut Bencher) {
        let n = 5;
        let v: Vec<i32> = (0..n).map(|x| x as i32).collect();
        b.iter(|| vec_max(&v))
    }

#[inline]
fn vec_max<T: Ord + Copy>(v: &[T]) -> Option<T> {
    if v.is_empty() {
        return None;
    }
    let mut max_val = v[0];
    if v.len() == 1 {
        return Some(max_val);
    }
    for val in &v[1..] {
        if *val > max_val {
            max_val = *val;
        }
    }
    Some(max_val)
}
```

**Comment by ljedrz** [comment]
I just ran the above benchmarks and didn't see any difference:
```
test bench_vec_iter_max ... bench:           3 ns/iter (+/- 0)
test bench_vec_max      ... bench:           3 ns/iter (+/- 0)
```
It appears that the aforementioned abstraction was changed to a `fold`.

@Mark-Simulacrum `E-needstest` / close?
