### ISSUE TITLE
It is hard to distinguish between functions in Rustdoc style using the new RFC style

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/rust#42988]
Looking at [the docs for trust-dns' 0.10.4 `trust_dns::client::Client`](https://docs.rs/trust-dns/0.10.4/trust_dns/client/trait.Client.html):

![image](https://user-images.githubusercontent.com/174509/27747280-6365f27e-5d7f-11e7-92e1-3a79a3fde733.png)

All of the function headers kind of run together and it's hard to determine where they stop. Perhaps the "fix" is just to add a bit of spacing between them.

**Comment by retep998** [comment]
Why is there a space between `get_client_handle` and `query` and not between the other functions? I'm in favor of simply adding some space between the function definitions.

**Comment by shepmaster** [comment]
> space between `get_client_handle` and `query`

I assume that there's a division between *required* methods and *provided* methods. FWIW, I think that differentiating between them is useful in the general sense.

**Comment by PlasmaPower** [comment]
Do we want a full newline between long functions or just a bit of space? Looking at the generated HTML, just a bit of space might be hard since each function doesn't have its own tag. We can change that of course.

**Comment by GuillaumeGomez** [comment]
I'm on it.
