### ISSUE TITLE
On FreeBSD std::fs::metadata(".").is_dir() returns false

### ISSUE THREAD

**Issue by kirillrdy** [rust-lang/rust#43005]
I found this by trying glob crate. going through call stack I determied that that issue is on FreeBSD std::fs:metadata(".").unwrap().is_dir() returns false, but on linux it returns true.
Here is code i used to test
```rust
use std::fs;

fn main() {
    let dir = fs::metadata(".").unwrap().is_dir();
    println!("{}", dir);
}
```
I am running FreeBSD-12.0-CURRENT but i hope its not the issue.
I suspect that FreeBSD was just not included in one of targets for function that should work on FreeBSD.

I am happy to provide any/all required information to help fix this,
Cheers, 
Kirill R

**Comment by kirillrdy** [comment]
sorry I there was missing information in the title of the issue :-)

**Comment by sfackler** [comment]
This is probably due to #42681.

**Comment by kirillrdy** [comment]
ok, thanks for you reply. 
I guess if there is a master issue for this, you can close this one.

**Comment by alexcrichton** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/42681
