### ISSUE TITLE
This error message could be clearer

### ISSUE THREAD

**Issue by ketsuban** [rust-lang/rust#43004]
Here's an error message which I found confusing at first. (`quick_main` is from the `error-chain` crate.)

```
error: `phi::spawn("Video Game", |_| <Box>::new(views::ViewA))` is being called, but it is not a function
 --> src/main.rs:8:1
  |
8 | quick_main!(phi::spawn("Video Game", |_| Box::new(views::ViewA)));
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: did you mean to write `phi::spawn("Video Game", |_| <Box>::new(views::ViewA))`?
  = note: this error originates in a macro outside of the current crate

error: aborting due to previous error
```

I was initially puzzled - `phi::spawn` is absolutely a function. Then I realised the problem is the *return value* of the function (which is not a function) is being called - the solution is to wrap the `phi::spawn` call in a closure. (The help is kind of useless too, but that's neither here nor there.)

**Comment by oli-obk** [comment]
The help needs a macro check. I don't know if rustc has macro checks for its lints anywhere.

**Comment by Mark-Simulacrum** [comment]
I can't reproduce with a simple test case, so I'm going to close; we can reopen if there's a reproduction for this issue.

```
macro_rules! call {
    ($e:expr) => {
        ($e)();
    };
}

fn do_thing() {}

fn main() {
    call!(do_thing());
}
```
