### ISSUE TITLE
Extremely long compile times with an infinitely recursive macro

### ISSUE THREAD

**Issue by pengowen123** [rust-lang/rust#43016]
With a recursive macro that takes any amount of tokens, and calls itself while increasing the amount of tokens exponentially, `rustc` takes a very long time to compile:

```rust
#![recursion_limit="64"]

macro_rules! foo {
    ($($bound:tt)*) => {
        foo!($($bound $bound)*);
    };
}

foo!(foo);

fn main() {}
```

With a recursion limit of 64, `rustc` won't stop running, and uses 100% cpu. If the recursion is set to a small number like 10, `rustc` will terminate with a recursion limit error as expected. If the recursion limit is increased to a slightly larger number like 16, `rustc` will terminate with the same error, but takes a few seconds on my machine.

I'm not sure what could be done here, as this feels like expected behavior.

**Comment by sfackler** [comment]
It seems expected to me that it takes an exponentially longer amount of time to process an exponentially larger set of tokens?

**Comment by Mark-Simulacrum** [comment]
Yeah, I believe that this is expected behavior. In most cases, expansion is quite fast (though there's always room for more optimizations).

I'm somewhat confused why you expect different behavior? Perhaps you can explain?

**Comment by pengowen123** [comment]
I ran into this while making a macro, and thought the compiler was just hanging because no errors appeared. I usually rely on the recursion limit being reached, so it just felt strange as I've never seen this happen before.

Now that I think about it, this can't be solved without enough optimization to allow the recursion error to happen. I'll just close the issue.
