### ISSUE TITLE
Thread guard panics with release optimizations

### ISSUE THREAD

**Issue by putc** [rust-lang/rust#43014]
Optimization of function with empty loop causes panic when setting up thread guard for main thread

I tried this code:

In a new cargo (0.19.0) crate I replace `main.rs` with the following code and run `cargo run --release`:

    fn wait() {
        loop {}
    }

    fn main() {
        wait();
        println!("Hello, world!");
    }

I expected to see this happen:

- Either the program does not terminate if the function call is not optimized away or
- The program immediately prints and terminates

Instead, this happened:

`lang_start` panics while settings up the guard for the main thread.

## Meta

`rustc --version --verbose`:
rustc 1.18.0 (03fc9d622 2017-06-06)
binary: rustc
commit-hash: 03fc9d622e0ea26a3d37f5ab030737fcca6928b9
commit-date: 2017-06-06
host: x86_64-unknown-linux-gnu
release: 1.18.0
LLVM version: 3.9

Backtrace:
thread 'main' panicked at 'assertion failed: c.borrow().is_none()', /checkout/src/libstd/sys_common/thread_info.rs:51
stack backtrace:
   0: std::sys:: imp ::backtrace::tracing:: imp ::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49 (Added spacing to remove emojis for imp)
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::sys_common::thread_info::set
             at /checkout/src/libstd/sys_common/thread_info.rs:51
             at /checkout/src/libstd/thread/local.rs:253
             at /checkout/src/libstd/sys_common/thread_info.rs:51
   7: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:51
   8: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
   9: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:57
  10: __libc_start_main
  11: _start

**Comment by jonas-schievink** [comment]
#28728

**Comment by putc** [comment]
@jonas-schievink I don't think I have really understood why optimization of that loop is causing this behaviour here, but yes seems to be the same thing
