### ISSUE TITLE
Unexpected panic when running RLS

### ISSUE THREAD

**Issue by Gilnaa** [rust-lang/rust#43032]
I am running _1.20.0-nightly (067971139 2017-07-02) on x86_64-pc-windows-msvc_

My [code](https://gist.github.com/Gilnaa/56ab12a4930af69ab738582aa91cd1ed) compiles and passes the tests, but VSCode popped up its output-pane. delivering a heart-breaking message from rustc:

```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.20.0-nightly (067971139 2017-07-02) running on x86_64-pc-windows-msvc

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:335:20
```

I assume it is somehow RLS-related since running `cargo build` & `cargo test` completes successfully. I'm not sure what more debug information I can provide, but would love to supply anything.

**Edit:** It seems as if src\libcore\option.rs:335:20 is a comment, and I am utterly confused

**Comment by ConorLPBoyle** [comment]
It should be what it says on the tin: This is a runtime bug caused by you (or some other code you depend on) trying to call .unwrap() on a None value. The line in question is https://github.com/rust-lang/rust/blob/master/src/libcore/option.rs#L335 . Run the program with environment variable RUST_BACKTRACE=1 to see where exactly this call is being made.

As the comment above states,

```
/// In general, because this function may panic, its use is discouraged.
/// Instead, prefer to use pattern matching and handle the [`None`]
/// case explicitly.
```

**Comment by mstange** [comment]
This panic occurs inside RLS, not in @Gilnaa's code.

**Comment by ConorLPBoyle** [comment]
In that case this issue should be opened at [the rls repository](https://github.com/rust-lang-nursery/rls).

**Comment by Mark-Simulacrum** [comment]
Yeah, this seems like it's probably either no longer a bug or something on RLS' side... I cannot reproduce with `-Zsave-analysis` or a normal build. Either way, a run with `RUST_BACKTRACE=1` would be useful..

**Comment by steveklabnik** [comment]
It's been quite a while, and a lot has changed. @Gilnaa if you're still seeing this, please let us know! I'm going to close until then.
