### ISSUE TITLE
Rust 1.20.0-nightly ICE with never_type: Broken MIR

### ISSUE THREAD

**Issue by ngc0202** [rust-lang/rust#43061]
The following error results from dereferencing a `*const !` as in this code: [https://is.gd/SsSDiG](https://is.gd/SsSDiG)

```
rustc 1.20.0-nightly (734c83642 2017-07-03)
error: internal compiler error: broken MIR (_3 = ()): bad assignment (! = ()): Sorts(ExpectedFound { expected: !, found: () })
 --> <anon>:4:5
  |
4 | /     unsafe {
5 | |         *x;
6 | |     }
  | |_____^

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.20.0-nightly (734c83642 2017-07-03) running on x86_64-unknown-linux-gnu

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:426:8
```

**Comment by SimonSapin** [comment]
What’s the correct fix? Compiler error with a nice error message?

**Comment by arielb1** [comment]
@SimonSapin

I think this should compile and UB, but a lint against this is probably a good idea.

**Comment by varkor** [comment]
Reduced test case:
```rust
// error: internal compiler error: broken MIR in NodeId(4) (_2 = ()): bad assignment (! = ()): Sorts(ExpectedFound { expected: !, found: () })
fn blah(x: !) {
    x;
}
```

**Comment by varkor** [comment]
I'm working on a fix for this. Progress on [this branch](https://github.com/varkor/rust/tree/unreachable-never-patterns). The idea is to avoid the typing issues entirely by terminating the blocks with `unreachable` as soon as a `!`-value is constructed. Currently the examples given here are fixed, but some more convoluted examples still crash.
