### ISSUE TITLE
Rustc does not emit assembly for msp430 backend

### ISSUE THREAD

**Issue by cr1901** [rust-lang/rust#43080]
I had a need to check the generated assembly for a project I'm working on using the msp430 backend, but I am unable to get rustc to generate an assembly file with certain flags.

## Problem

Using `rustc` to emit assembly causes the following error on the msp430 backend:

```
William@William-THINK MINGW32 ~/prj/Legacy/PC/HARDWARE/AT2XT
$ xargo rustc --release --target msp430 -v -- --emit=asm
+ "rustc" "--print" "sysroot"
+ "rustc" "--print" "target-list"
+ "cargo" "rustc" "--release" "--target" "msp430" "-v" "--" "--emit=asm"
       Fresh volatile-register v0.1.2
       Fresh bit_reverse v0.1.6-pre (https://github.com/cr1901/bit_reverse?branch=patch-1#ea57cab8)
   Compiling at2xt v0.1.0 (file:///C:/msys64/home/William/prj/Legacy/PC/HARDWARE/AT2XT)
     Running `rustc --crate-name at2xt 'src\main.rs' --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C debuginfo=2 --emit=asm -C metadata=2cff10aa3a17e8e8 -C extra-filename=-2cff10aa3a17e8e8 --out-dir 'C:\msys64\home\William\prj\Legacy\PC\HARDWARE\AT2XT\target\msp430\release\deps' --target msp430 -L 'dependency=C:\msys64\home\William\prj\Legacy\PC\HARDWARE\AT2XT\target\msp430\release\deps' -L 'dependency=C:\msys64\home\William\prj\Legacy\PC\HARDWARE\AT2XT\target\release\deps' --extern 'volatile_register=C:\msys64\home\William\prj\Legacy\PC\HARDWARE\AT2XT\target\msp430\release\deps\libvolatile_register-6cd680bd4718bf91.rlib' --extern 'bit_reverse=C:\msys64\home\William\prj\Legacy\PC\HARDWARE\AT2XT\target\msp430\release\deps\libbit_reverse-f0ca07b3a5660ef3.rlib' -C link-arg=-Tmsp430g2211.ld -C link-arg=-mmcu=msp430g2211 -C link-arg=-nostartfiles --sysroot 'C:\msys64\home\William\.xargo' -L 'C:\msys64\home\William\prj\Legacy\PC\HARDWARE\AT2XT\target\msp430\release\build\at2xt-68587409a68b5cea\out'`

snip a bunch of warnings...

error: failed to remove C:\msys64\home\William\prj\Legacy\PC\HARDWARE\AT2XT\target\msp430\release\deps\at2xt-2cff10aa3a17e8e8.crate.metadata.o: The system cannot find the file specified. (os error 2)

    Finished release [optimized + debuginfo] target(s) in 1.55 secs
```

Subsequent runs of `xargo` or `cargo` succeed, but no output assembly file is generated. Running `rustc` directly always results in a file not found error.

@japaric encountered the same issue with missing crate metadata when compiling his [msp430-quickstart](https://github.com/japaric/msp430-quickstart) repository with the following settings (I am unable to compile the linked repo for unrelated reasons, currently):

`xargo rustc --release --example blinky -- --emit=asm`

However, an assembly file is successfully generated with the following command line:
`rustc --target msp430-none-elf --emit=asm empty.rs --sysroot ~/.xargo -g`

## Expected

I would expect the output assembly file to be under the target directory (when using `cargo`), regardless of the flags beside --emit=asm I pass `rustc`.

## Meta 

```
rustc --version --verbose
rustc 1.19.0-nightly (e2eaef849 2017-06-11)
binary: rustc
commit-hash: e2eaef8497bd212694840515a568d592b17d0e07
commit-date: 2017-06-11
host: x86_64-pc-windows-gnu
release: 1.19.0-nightly
LLVM version: 4.0
```

Backtrace does not print any extra information.

**Comment by workingjubilee** [comment]
pardon, is this still an issue in 2022?

**Comment by cr1901** [comment]
`--emit=asm` works fine when combined with `-Z build-std=core`. I do not use `xargo` anymore, so I'm not able to test the exact conditions.

**Comment by workingjubilee** [comment]
I'm going to mark this as "good enough" then! Thank you for following up!
