### ISSUE TITLE
Is (cross-)compiling with an "alt" compiler and "non-alt" standard library supported?

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#43085]
https://github.com/rust-lang/rust/pull/39754 added “alternate” builds for a small number of platforms. They disable LLVM assertions, significantly improving compile times compared to Nightly. More background: https://internals.rust-lang.org/t/disabling-llvm-assertions-in-nightly-builds/5388

Servo uses these by default when available. Them being only available for a small number of platforms is ok because that covers platforms most developers use, and we can fall back to "normal" slower Nightly compilers.

In https://github.com/rust-lang/rust/issues/42967 we ran into an issue that only occurred on OS X, when compiling crates that depend on procedural macro crates, when using an "alt" compiler with a "non-alt" standard library. It seems in theory that enabling or disabling LLVM assertions in rustc should not have any effect on standard libraries, but we worked around that issue in https://github.com/servo/servo/pull/17575 by making sure we download an std of the same kind as rustc.

It gets tricky when cross-compiling (for example to Android), since "alt" standard libraries are not necessarily available for the target platform even when they are for the host. In https://github.com/servo/servo/pull/17604 we might need to rewrite our `mach` configuration handling and Rust bootstrapping to be able to support selecting an "alt" vs "non-alt" compiler depending on the cross-compilation target.

But do we really need to? Or is https://github.com/rust-lang/rust/issues/42967 a rustc bug after all? "Should" it work to use an "alt" rustc with "non-alt" std?

CC @aturon since I don’t know are the appropriate people to ask, please redirect.

**Comment by metajack** [comment]
cc @jonathandturner

**Comment by SimonSapin** [comment]
[Disabling LLVM assertions in Nightly](https://internals.rust-lang.org/t/disabling-llvm-assertions-in-nightly-builds/5388) would make this whole issue go away since alternate compiler builds would become unnecessary.

**Comment by Mark-Simulacrum** [comment]
cc @alexcrichton

**Comment by alexcrichton** [comment]
I believe the tl;dr; is basically "no, this is not a supported configuration". The intention was that these builds would be for developer-only machines which didn't need the full power of the rest of the toolchain.

**Comment by SimonSapin** [comment]
Developers working on platform-specific issues or features need to cross-compile. We don’t need full toolchains for target (as opposed to host) platforms, only `std`.

We can probably rework bootstrapping on our side so that "non-alt" builds are used for cross-compiling, but if fixing https://github.com/rust-lang/rust/issues/42967 on the rustc side is reasonably feasible that would be nicer.

**Comment by jonathandturner** [comment]
@SimonSapin - iirc, the way alt builds were added was kind of a hack to begin with, intended as a way to get Servo a build without assertions.  It was acknowledged at the time it wasn't the best solution, but we hoped that it would be good enough.

It sounds like we're saying now that the hack didn't end up being good enough.  If that's the case, sounds like we should get people together again to see if we can come up with another solution.

**Comment by SimonSapin** [comment]
I’m not sure “not good enough” applies. There is one known issue. I don’t know if that makes the whole approach flawed or if it’s “just” a bug/regression that can be fixed.

(Specifically, when loading a procedural macro crate, the hash/filename expected by that crate for `std` didn’t match the one available on disk. On OS X only.)

**Comment by jonathandturner** [comment]
@alexcrichton - is there a way to address this hash/filename issue on macOS?  Is it possible it's just a bug that hasn't gotten fixed yet?

**Comment by SimonSapin** [comment]
I bisected #42967. I can reproduce it in dfa7e21e4ee555d04c0fb86069f5acffee3550ad but not in e40ef964fe491b19c22dfb8dd36d1eab14223c36, leaving https://github.com/rust-lang/rust/pull/42433 as the only change.

**Comment by SimonSapin** [comment]
That PR adds ` --enable-profiler` to the configuration of most builds but not "alternate" ones. Could that affect the hash of `std`? Is there a reason not to? I think enabling it everywhere might fix the issue.

**Comment by SimonSapin** [comment]
Opened https://github.com/rust-lang/rust/pull/43167

**Comment by Mark-Simulacrum** [comment]
Closing as per https://github.com/rust-lang/rust/issues/43085#issuecomment-313439621. We should try to keep these in sync when possible, I guess, though...

**Comment by SimonSapin** [comment]
Ah, yes. I meant for #43167 to close this. We moved Servo back to using alt rustc with normal std in https://github.com/servo/servo/pull/17727.
