### ISSUE TITLE
Should the sets of library and language features be disjoint?

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#43089]
Currently, there [is a check](https://github.com/rust-lang/rust/blob/c6afde6c46d167c9c75389b887f1d2498aeef3e4/src/tools/tidy/src/features.rs#L248-L250) in tidy that ensures that there is no library feature and language feature of the same name. Its presence [is also mentioned](https://github.com/rust-lang/rust/blob/c6afde6c46d167c9c75389b887f1d2498aeef3e4/src/tools/tidy/src/features.rs#L16) in the documentation above.

This check [was present](https://github.com/rust-lang/rust/pull/21248/commits/11f4d62a062a5c80fad414c457e2a7dbc9a1d6cc#diff-eb84472009c2f21296e20169c0691318R119) since #21248, and has caused multiple additions that have both library and language components to be split up:

* `i128` / `i128_type`
* `inclusive_range` / `inclusive_range_syntax`
* `profiler_runtime` / `profiler_runtime_lib`

PR #40939 has challenged the status quo, by reusing the lang feature `proc_macro` inside libraries provided to programs. It actually [added an exception](https://github.com/rust-lang/rust/commit/e42836b2085233323339bacb636ecf9c28e8422e#diff-e7f0adcf2688b6a55b1f70d117ed7e17L248) to the tidy check in order to get it passing.

There has been [discussion](https://github.com/rust-lang/rust/pull/40939#issuecomment-296422560) about this in the thread of #40939 and the resolution was to allow `proc_macro` to share the feature gate.

So my question is: which purpose does this check serve? should the check be present, or should it be abolished? Should the `proc_macro` feature gate be split up into a library component and a lang component?

**Comment by durka** [comment]
IMO we should just kill the tidy check. For inclusive ranges we are stabilizing the lib and syntax separately, but if they had been under the same gate it would have been easy to split them up, like we are doing for const fn.

**Comment by nikomatsakis** [comment]
I too think we should lump things that are "the same underlying concept" under one feature gate.

**Comment by aidanhs** [comment]
Looks like the original code allowed for a 'joint features' whitelist, so it seems like it might have just been a sanity check that any intersection was intentional. Indeed, that script actually says that it's for doing some sanity checks.

If for some reason that sanity check is still desirable, at minimum I'd be +1 to creating a `joint_features` whitelist rather than ad-hoc growing the if condition.

**Comment by est31** [comment]
> it seems like it might have just been a sanity check that any intersection was intentional

We can guard from that by doing a check for any joint features whether the tracking issue and stability status (stable or unstable) matches between lib and lang features.
