### ISSUE TITLE
`#[link_args]` was accidentally stabilized; were other attributes as well?

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#43106]
A [comment](https://github.com/rust-lang/rust/issues/29596#issuecomment-310288094) in the tracking issue for `#[link_args]` points out that the attribute was accidentally stabilized (quite a long time ago).

I think it will be easy to fix the particular case of `#[link_args]`; the infrastructure [here](https://github.com/rust-lang/rust/blob/1685c92/src/libsyntax/feature_gate.rs#L524) is pretty nice. But it does raise the question: Were other attributes accidentally stabilized at the same time?

This issue has two goals: 1. correct the `#[link_args]` feature gate, and 2. double-check whether other attributes in the `BUILTIN_ATTRIBUTES` array need similar treatment.

**Comment by retep998** [comment]
In particular, try to check by using the attribute in places where it was *not* intended to be used. As an example `#[link_args]` is still unstable when used on an extern block (which is even [tested](https://github.com/rust-lang/rust/blob/master/src/test/compile-fail/gated-link-args.rs)), but if you do a crate level `#![link_args]` then it is stable.

**Comment by pnkfelix** [comment]
(So PR #43109 is intended to address item 1 in the description, but I want to keep this issue open until we have double-checked 2. and potentially added corresponding unit tests.)

**Comment by pnkfelix** [comment]
Another detail that I had not digested before about this bug: We are even emitting a lint claiming that the `link_args` attribute is unused when it appears in these other contexts that elude the current feature gate.

This led me to think that this bug was not *so* bad, since I inferred from the emission of the `unused_attribute` warning that the directive to `link_args` was being ignored in those other contexts.

However, as @retep998 states, the `link_args` directive *is* included in the linker invocation when `link_args` occurs elsewhere, *despite* the compiler claiming that the occurrence of the attribute is unused.

So the compiler is not merely failing to stop us from putting in a useless occurrence of an unstable attribue in such cases; it is in fact actively lying regarding the effect of the occurrence of the attribute.

**Comment by petrochenkov** [comment]
`#[link_args]` is feature-gated now.

Regarding the "were other attributes as well?" part, the list of built-in attributes is currently in `src\librustc_feature\builtin_attrs.rs` for anyone to audit.
Looks like the audit was already done since 2017 because the accidentally stabilized attributes are either unstabilized or marked with FIXMEs.
