### ISSUE TITLE
Warning about "type alias never used", but alias is used for impl block

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#43123]
The following code
```rust
enum MyOption<T> { None, Some(T) }
use MyOption::*;

type MyType = MyOption<i32>;

impl MyType {
    fn foo(self) -> Self {
        None
    }
}

fn main() {
    Some(3).foo();
}
```
issues a warning in current stable and nightly:
```
rustc 1.18.0 (03fc9d622 2017-06-06)
warning: type alias is never used: `MyType`
 --> <anon>:4:1
  |
4 | type MyType = MyOption<i32>;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(dead_code)] on by default
```

However, the type alias is actually used -- if I remove it, the code stops compiling because the `impl` block references the alias. Hence, there should be no warning.

**Comment by durka** [comment]
Nothing is public so I believe this is intentional. I complained about a similar case in the past, with enum variants used in private functions, and was told the `dead_code` lint is _not_ supposed to be a general-purpose "you may delete this code".

**Comment by durka** [comment]
However, a duplicate is https://github.com/rust-lang/rust/issues/39531.

**Comment by RalfJung** [comment]
I don't think that's a duplicate... in #39531, the functions indeed don't get used, to if you remove all of what "dead code" complains about, the resulting program still works.

Here, I would need to refactor to make the lint go away. That seems silly.

It not being public can't be the point either. Just adding a `let _x : MyType;` somewhere makes the warning go away, and still nothing is public.

**Comment by cramertj** [comment]
As I initially reported in #43328, type alias uses in struct definitions also aren't considered.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/18290.
