### ISSUE TITLE
x.py test with non-existent test directory should error

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#43121]
`./x.py test does-not-exist` should spit out an error instead of being successful.

cc @GuillaumeGomez

**Comment by PlasmaPower** [comment]
This was confusing to me when I tried to specify a file for `./x.py test` and it did nothing. :+1:

**Comment by GuillaumeGomez** [comment]
@Mark-Simulacrum: Still no news on this?

**Comment by Mark-Simulacrum** [comment]
Well, I believe it'll be fixed within https://github.com/rust-lang/rust/pull/43059. However, if someone would like to implement this, adding logic here https://github.com/rust-lang/rust/blob/master/src/bootstrap/step.rs#L1212 to check that all indices in the path array were visited seems fairly straightforward. I'll mark as E-mentor and unassign myself.

**Comment by GuillaumeGomez** [comment]
Well, I wanted to do it myself. :p
