### ISSUE TITLE
ThreadRng performance bug

### ISSUE THREAD

**Issue by SharplEr** [rust-lang/rust#43120]
ThreadRng works 5 times slower than ThreadLocalRandom in Java.

I run this benchmark in Rust:

```Rust
#[bench]
fn bench_rnd(b: &mut Bencher) {
    b.iter(|| rand::thread_rng().gen_range::<f64>(2.0, 100.0));
}
```
On my laptop the result is:
test tests::bench_rnd             ... bench:          49 ns/iter (+/- 1)

But if I run the same benchmark on JHM:

```Java
@Benchmark
public double testRnd() {
    return ThreadLocalRandom.current().nextDouble(2, 100);
}
```
On my laptop the result is:
Benchmark     Mode  Cnt  Score   Error  Units
Main.testRnd  avgt   20  9,018 ± 0,094  ns/op

So the difference is 5.44 times looks like performance bug.

## Meta
Rust:

rbose
rustc 1.20.0-nightly (c9bb93576 2017-06-24)
binary: rustc
commit-hash: c9bb93576d4484edd1b3c40eb2aea0dfa0788851
commit-date: 2017-06-24
host: x86_64-unknown-linux-gnu
release: 1.20.0-nightly
LLVM version: 4.0

Java:
OpenJDK 1.8.131

**Comment by retep998** [comment]
Since `rand` is an external crate with its own repository, this issue probably belongs [there](https://github.com/rust-lang-nursery/rand), unless you're able to somehow demonstrate that this is Rust's fault, and not `rand`'s fault.

**Comment by kennytm** [comment]
Also note that Java's `ThreadLocalRandom` is an extremely simple [linear congruential PRNG](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ThreadLocalRandom.html#next-int-), while Rust's `rand`'s [`thread_rng()`](https://docs.rs/rand/0.3.15/rand/fn.thread_rng.html) is based on [the ISAAC (claimed-to-be) cryptographically secure PRNG](https://en.wikipedia.org/wiki/ISAAC_(cipher)) which is more expensive, so this benchmark is not an exactly apple-to-apple comparison.

**Comment by SharplEr** [comment]
Thank you a lot for the explanation.
