### ISSUE TITLE
Process ids are i32 in Linux, std::process::Child::id uses u32

### ISSUE THREAD

**Issue by marmistrz** [rust-lang/rust#43139]
See the original report against the `nix` crate here: https://github.com/nix-rust/nix/issues/656

**Comment by retep998** [comment]
Does this really matter, especially since that method is *stable*? It is trivial to cast between `i32` and `u32` and there's no information loss, so this doesn't seem like enough of a problem to warrant a breaking change in an API that has been stable since Rust 1.3

**Comment by GuillaumeGomez** [comment]
We could just add a wrapper around it?

**Comment by GuillaumeGomez** [comment]
So I opened a PR to show what it'd look like. But since it's a stable API...

**Comment by kennytm** [comment]
You could [compare branches without opening a PR](https://github.com/rust-lang/rust/compare/master...GuillaumeGomez:process-id).

**Comment by GuillaumeGomez** [comment]
@kennytm: Ah my bad. Well now it's done...

**Comment by alexcrichton** [comment]
Thanks for the report, but this was an intentional decision and as a stable method we can't change it, so closing.

**Comment by marmistrz** [comment]
@alexcrichton what was the intention behind it? Why not keep it open with milestone Rust 2.0 (i.e. when we go so far that we have to break the source API, we'll fix that by the way)

**Comment by kennytm** [comment]
@marmistrz Those feature requests are still closed, but tagged as [<kbd>rust-2-breakage-wishlist</kbd>](https://github.com/rust-lang/rust/issues?utf8=%E2%9C%93&q=label%3Arust-2-breakage-wishlist).

**Comment by alexcrichton** [comment]
@marmistrz no known valid pids are negative and I believe Windows uses `u32` natively, so we chose to use u32 across the board.

**Comment by marmistrz** [comment]
That's not true, for example on Minix: http://wiki.minix3.org/doku.php?id=gentleintroduction

**Comment by alexcrichton** [comment]
Can a kernel process be a child process?

**Comment by marmistrz** [comment]
It won't be a problem in Minix:
```
<marmistrz> I'm wondering if there's a slightest possibility of this affecting any user space processes
<Saturn> it is not. kernel tasks do not have pids at all
<Saturn> the wiki page you linked is talking strictly about what ps is showing, which is no longer true anyway
```
