### ISSUE TITLE
Regression on nightly-2017-07-08 and nightly-2017-07-09

### ISSUE THREAD

**Issue by lakinwecker** [rust-lang/rust#43131]
I have to use nightly for a few other libraries, but the nightlies listed in the title will not compile slog-async 2.0.1. nightly-2017-07-07 does compile it. 

The errors in compilation look like this: 

https://gist.github.com/lakinwecker/72839075f2a671750e89b4be190641de

I was unsure if this is an issue for the library maintainer or rust, so I filed a github issue for the library first: https://github.com/slog-rs/async/issues/2 and was asked to file one here. Hopefully this is the right place and has enough information. 

The repo/issue for the library is here: https://github.com/slog-rs/async/issues/2

**Comment by Mark-Simulacrum** [comment]
Could you try running `cargo update`? I suspect that @petrochenkov fixed this in slog here https://github.com/slog-rs/slog/pull/139... cc tracking issue https://github.com/rust-lang/rust/issues/34537.

**Comment by lakinwecker** [comment]
Yes, that worked. Sorry for using this as a support forum. I was not aware of `cargo update`. My bad. 👍
