### ISSUE TITLE
#![no_builtins] attribute occurs twice on BUILTIN_ATTRIBUTES list

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#43148]
(spawned off of #43106) 

As the title says, there are two entries for `"no_builtins"`.

They look like:

```rust
...
    ("no_builtins", Whitelisted, Ungated),
...
    ("no_builtins", CrateLevel, Ungated),
...
```

I doubt the duplicate differing entries are a deliberate choice.

I suspect this may be hiding a small bug, since I currently do not get an error from the compiler (including on the stable channel) when I hand it code like this:

```rust
#[no_builtins = "0300"]
mod no_builtins { mod inner { #![no_builtins="0200"] }
}

fn main() { }
```

**Comment by Centril** [comment]
This is no longer the case.
