### ISSUE TITLE
Add a function to get the key from a HashMap

### ISSUE THREAD

**Issue by iqualfragile** [rust-lang/rust#43143]
Basically just
```
pub fn get_both<Q: ?Sized>(&self, k: &Q) -> Option<(&K,&V)>
        where K: Borrow<Q>,
              Q: Hash + Eq
    {
        self.search(k).into_occupied_bucket().map(|bucket| bucket.into_refs())
}
```
sometimes you need a reference to a key with the lifetime of the collection.

**Comment by oli-obk** [comment]
If `OccupiedEntry::key` returned the reference with the proper lifetime, we could already do this in usercode.

**Comment by iqualfragile** [comment]
@oli-obk the entry api would not work, because it requires &mut, this usecase would require the ability to have multiple references and therefore just &

**Comment by dtolnay** [comment]
I don't love the name `get_both` but I agree that this is basic functionality that HashMap should expose. I would welcome a PR and we can refine the name separately.
