### ISSUE TITLE
infinite while loops are treated differently from infinite (loop) loops.

### ISSUE THREAD

**Issue by hinaria** [rust-lang/rust#43154]
hi there!

these two loops, one using `loop` and the other using `while true` are equivalent, but the `while true` version does not compile.

rust is expecting a final return after the `while true { ... }` expression, but it does not for the `loop { ... }`.

i couldn't find any mention of this in the [rust reference](https://doc.rust-lang.org/reference/), so i'm not sure if this is intended. i'd like to submit an issue just in case it's a bug.

```rust
// this compiles.
fn hello() -> bool {
    loop {
        return true;
    }
}
```
```rust
// this does not compile, because it is expecting a final return after `while true`.
fn hello() -> bool {
    while true {
        return true;
    }
}
```
```rust
rustc 1.20.0-nightly (d84693b93 2017-07-09)
error[E0308]: mismatched types
 --> <anon>:2:5
  |
2 | /     while true {
3 | |         return true;
4 | |     }
  | |_____^ expected bool, found ()
  |
  = note: expected type `bool`
             found type `()`

error: aborting due to previous error

```

**Comment by leonardo-m** [comment]
Unfortunately it's intended... See this thread of mine: https://users.rust-lang.org/t/the-loop-keyword-doesnt-carry-its-weight/4872

**Comment by Ophirr33** [comment]
They kind of mention it [here](https://doc.rust-lang.org/1.1.0/book/while-loops.html). 

> Rust’s control-flow analysis treats this construct differently than a while true, since we know that it will always loop. In general, the more information we can give to the compiler, the better it can do with safety and code generation, so you should always prefer loop when you plan to loop infinitely.

**Comment by hinaria** [comment]
oh i see, thank you. if that behaviour is intended, i'm happy to close.

saying that rust's flow analysis "treats this construct differently", to me, does not also imply that the `while true` example above should fail.

that wording also happens to be gone from the second edition of the book, and the rust reference makes no mention of it. i wasn't sure if this is intentional, or if it has been been an oversight.

**Comment by sfackler** [comment]
cc @rust-lang/docs

**Comment by GuillaumeGomez** [comment]
Maybe it might be worth it to mention it in more places. Maybe in The Book or in the docs directly?

cc @steveklabnik

**Comment by 3442853561** [comment]
Here's a suggestion, how about give a warning first when we use while true.

**Comment by jmesmon** [comment]
@3442853561 that would still change the validity of rust code based on the optimization ability of the compiler, so I don't think it would be a good idea.

**Comment by steveklabnik** [comment]
Since this is mentioned in the book already, I'm giving it a close. Thank you, and sorry for the confusion!
