### ISSUE TITLE
cfg(target_env) is not set correctly in build script

### ISSUE THREAD

**Issue by kanerogers** [rust-lang/rust#43163]
I am attempting to use `cfg(target_env)` to build my program differently if the `target_env` is `musl`. I am new to using build scripts, so please point me in the right direction if I have missed something obvious or have made incorrect assumptions. 😄 

Unfortunately, the `target_env` is being erroneously set to `gnu`, but only in `build.rs`. In my program proper, the flag does seem to function correctly.

Curiously, `CARGO_CFG_TARGET_ENV` does seem to be set correctly, as seen in this example:

```
extern crate gcc;

use std::env;

#[cfg(target_env="musl")]
fn main() {
    println!("Target Env is MUSL");
    let var = env::var("CARGO_CFG_TARGET_ENV").unwrap();
    println!("ENV: {}", var);
}

#[cfg(target_env="gnu")]
fn main() {
    println!("TARGET ENV IS GNU");

    let var = env::var("CARGO_CFG_TARGET_ENV").unwrap();
    println!("ENV: {}", var);
}
```

Output: (when run with `cargo build --target x86_64-unknown-linux-musl -vv`)

```
TARGET ENV IS GNU
ENV: musl
```

## Meta

`rustc --version --verbose`:

```
rustc 1.20.0-nightly (720c596ec 2017-07-08)
binary: rustc
commit-hash: 720c596ec62e8fec855c2953f21b0118ae408bdd
commit-date: 2017-07-08
host: x86_64-unknown-linux-gnu
release: 1.20.0-nightly
LLVM version: 4.0
```

cat ~/.cargo/config
```
[build]
# Target musl-libc by default when running Cargo.
target = "x86_64-unknown-linux-musl"
```

rustup show
```
Default host: x86_64-unknown-linux-gnu

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

installed targets for active toolchain
--------------------------------------

x86_64-unknown-linux-gnu
x86_64-unknown-linux-musl

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.20.0-nightly (720c596ec 2017-07-08)
```

**Comment by jmesmon** [comment]
build scripts are built for you build system. `#[cfg]` always corresponds to the system being targeted by the current rustc invocation. In the case of the build script, the target for rustc is your build system (`x86_64-unknown-linux-gnu`).

As you've discovered, the environment variables from cargo tell your build script what the target will be.

**Comment by kanerogers** [comment]
Ah! That does make sense in hindsight. 😅 

Thanks for the lightning fast response - greatly appreciated!
