### ISSUE TITLE
Type system loophole: i32 > 256 converts to u8 converts to char, leading to crash

### ISSUE THREAD

**Issue by christopherdumas** [rust-lang/rust#43171]
I have a playground MCVE [here](https://play.rust-lang.org/?gist=6eb52d0f6fa8f43627898e58b8b5e0c7&version=stable&backtrace=0). Essentially, you can case an integer that is over 256, or greater than `char` can represent, to a `u8` and then to a `char`, and get an overflow wraparound, or in my case, for some reason, a crash. My code looks like this in case you don't want to look at the playground:
```rust
fn main () {
    let base: i32 = 255;
    let foo: char = (base + 128) as u8 as char;
    println!("{:?}", foo); // Overflow: `\u{7f}' (integer value 127)
}
```
I'm not sure if this is intended, it has caused a runtime crash for me so I don't think it is. Hope this helps!

**Comment by jonas-schievink** [comment]
Looks correct. `(base + 128) as u8` is `127` (`as` casts are defined to wrap around). What sort of crash are you getting (panic, segfault)? How can we reproduce it?

**Comment by christopherdumas** [comment]
Never mind, I misunderstood the cause of the segfault, it was not related to i32 -> u8 -> char at all, since char can contain a positive u8. I was thinking like a C++ programmer. My apologies.
