### ISSUE TITLE
no_std dylib fails to compile, seems to be missing libcore

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#43182]
a.rs:
```rust
#![no_std]
```
`rustc a.rs --crate-type=dylib` with 1.20.0-nightly (bf0a9e0b4 2017-07-10):
```rust
error: language item required, but not found: `panic_fmt`

error: language item required, but not found: `eh_personality`

error: aborting due to 2 previous errors
```

**Comment by SimonSapin** [comment]
Never mind, I just remembered that these two lang items are not in libcore and `no_std` programs need to define them themselves.

**Comment by crazyboycjr** [comment]
Hi @SimonSapin. I still have questions about this. I can understand an executable needs these two lang items, but for a dynamic library, why do I need to provide them? Would they conflict with the one in libstd when I have an executable link with the dynamic library?
