### ISSUE TITLE
Github's license detection is messed up

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#43188]
https://github.com/rust-lang/rust/community links to https://github.com/rust-lang/rust/blob/master/COPYRIGHT

[The docs](https://help.github.com/articles/adding-a-license-to-a-repository/) don't make any mention of looking for `COPYRIGHT`.

https://github.com/rust-lang/rust/issues/39897 suggests re-writing COPYRIGHT anyway.

I'd argue that we should

1. Remove the `COPYRIGHT` file.
2. replace it with a `LICENSE.md` file
3. The contents of such should point to our other license files.

This would not totally solve #39897, but it's a start. Hence this separate ticket.

What do you think, @rust-lang/core ?

**Comment by est31** [comment]
Github doesn't support dual licenses, so if we'd get it to display a license, it'd be not accurate. eg https://github.com/steveklabnik/rustdoc shows up as "Apache-2.0". I'm not sure whether that's wanted.

**Comment by jmesmon** [comment]
https://github.com/blog/1964-open-source-license-usage-on-github-com

> To detect what license, if any, a project is licensed under, we used an open source Ruby gem called [Licensee](https://github.com/benbalter/licensee)

**Comment by steveklabnik** [comment]
> eg https://github.com/steveklabnik/rustdoc shows up as "Apache-2.0". 

heh yeah I wanted to tackle that after I tackle this.

Oh thanks @jmesmon !

**Comment by steveklabnik** [comment]
cc https://github.com/benbalter/licensee/pull/203

**Comment by steveklabnik** [comment]
also cc https://github.com/benbalter/licensee/issues/114#issuecomment-307593884

**Comment by frewsxcv** [comment]
GitHub no longer incorrectly reports this repo as Apache-2.0. Should we fold this issue into https://github.com/rust-lang/rust/issues/39897 ?

**Comment by steveklabnik** [comment]
Yup!
