### ISSUE TITLE
rustc guesses wrong so name

### ISSUE THREAD

**Issue by metux** [rust-lang/rust#43186]
make[1]: Entering directory '/home/nekrad/src/cargo/syn/synom'
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m32" "-L" "/home/nekrad/.usr/rust/lib/rustlib/i686-unknown-linux-gnu/lib" "libsynom.so.0.0.o" "-o" "libsynom.so.0.11.3" "libsynom.so.0.crate.metadata.o" "libsynom.so.0.crate.allocator.o" "-nodefaultlibs" "-L" "/home/nekrad/.usr/rust/lib" "-L" "/home/nekrad/.usr/rust/lib/rustlib/i686-unknown-linux-gnu/lib" "-L" "/home/nekrad/.usr/rust/lib" "-l" "proc_macro2.so.0.1" "-L" "/home/nekrad/.usr/rust/lib" "-l" "proc_macro-7851475180fdb1f7" "-Wl,-Bstatic" "-Wl,--whole-archive" "/tmp/rustc.TEFOVI3giDJA/libunicode_xid.rlib" "-Wl,--no-whole-archive" "-L" "/home/nekrad/.usr/rust/lib/rustlib/i686-unknown-linux-gnu/lib" "-Wl,-Bdynamic" "-l" "syntax-e5b6553f677063a9" "-L" "/home/nekrad/.usr/rust/lib" "-l" "rustc_errors-e69765288cfd7b4e" "-L" "/home/nekrad/.usr/rust/lib/rustlib/i686-unknown-linux-gnu/lib" "-l" "syntax_pos-192c5ddcc2211914" "-L" "/home/nekrad/.usr/rust/lib/rustlib/i686-unknown-linux-gnu/lib" "-l" "rustc_data_structures-917e1876a1c4769e" "-L" "/home/nekrad/.usr/rust/lib/rustlib/i686-unknown-linux-gnu/lib" "-l" "serialize-014a1921f193044d" "-L" "/home/nekrad/.usr/rust/lib/rustlib/i686-unknown-linux-gnu/lib" "-l" "term-7e2934a80df08822" "-L" "/home/nekrad/.usr/rust/lib" "-l" "std-706fd3787feff92a" "-Wl,-Bstatic" "/tmp/rustc.TEFOVI3giDJA/libcompiler_builtins-e68fb6d1557bb085.rlib" "-Wl,-Bdynamic" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util" "-shared"
  = note: /usr/bin/ld: cannot find -lproc_macro2.so.0.1
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

The .so, of course, is named in unix/elf conformant way (libproc_macro2.so.0.1.0) w/ proper symlinks (-> libproc_macro2.so.0.1 -> libproc_macro2.so.0 -> libproc_macro2.so.0). 

Obviously, rustc tries to be clever about guessing actual library names, instead of just letting ld do its job, and fails.

The correct behaviour would be just passing -l<libname> (eg. -lproc_macro2), w/o any additional garbage.

**Comment by cuviper** [comment]
`rustc` generally doesn't deal with sonames, and shouldn't IMO since semver only promises API compatibility, not ABI.  But I don't know where that's coming from in your configuration...

**Comment by alexcrichton** [comment]
Ah yeah this looks like a local configuration problem b/c rustc itself doesn't deal with these at all currently, so closing.
