### ISSUE TITLE
Warn when doc comment doesn't provide code example?

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#43193]
It was during the last rustdoc reunion, I emitted the following idea:

> if a doc comment doesn't have a block code (aka code example), then it emits a warning
> (but only when running rustdoc)

So we have the two following ideas for the implementation:

 *  `rustdoc --check`
 * Add another lint disabled by default (activating with `#[warn(docs_without_examples)]`)

Any preference?

cc @rust-lang/docs 
cc @ubsan

**Comment by kennytm** [comment]
The lint/check should be exclude struct fields and enum variants. Maybe const and type alias as well.

Doc comments on private items should also be exempt.

I'm afraid there will still be a lot of `#[allow(docs_without_examples)]`, like adding an example to  `std::ops::Add::add` in additional to `std::ops::Add` would be just noise.

This should be doable in Clippy.

**Comment by mcarton** [comment]
I had started something like that and also other Rust guidelines for documentation in Clippy a few weeks ago, never had the time to finish 😕 
@kennytm makes a good point about `Add` vs. `Add::add` though.

**Comment by clarcharr** [comment]
See rust-lang-nursery/clippy#1454

**Comment by steveklabnik** [comment]
Triage: nominating for future docs team discussion; people are very split about if this should be in rustdoc or clippy

**Comment by QuietMisdreavus** [comment]
We talked about this in the docs team meeting today, and decided this would be better served as a lint in clippy, rather than trying to pull it into rustc immediately, or adding an entirely new interaction mode to rustdoc. As such, I'll close this issue in favor of the clippy issue @clarcharr linked earlier.
