### ISSUE TITLE
rustc needs parameter for soname (or ld flags in general) 

### ISSUE THREAD

**Issue by metux** [rust-lang/rust#43190]
rustc currently doesn't add, and doesn't allow specifying the library soname.
Thus, ld cannot differenciate between binary versions, which makes it extremley hard to have multiple versions coexist (requires horrible LD_LIBRARY_PATH games), and therefore causes bad headaches for distro packaging.

Actually, it doesn't even allow passing any linker flags at all.

**Comment by cuviper** [comment]
You can use `rustc -Clink-arg=-Wl,-soname=foo.so.1`.

But as I mentioned in #43186, I don't think one *should* do this without actually ensuring the ABI stability that this implies.  It's not there at all for Rust APIs -- rust-lang/rfcs#600 -- and even if it were it would probably still take some effort by the library author to do it right.

It could make sense for a cdylib, if you do make sure to keep that ABI stable.

**Comment by jmesmon** [comment]
In the context of cargo, that could be `RUSTFLAGS="-Clink-arg=-Wl,-soname=foo.so.1" cargo build`, but it seems likely that this will pass the `-soname` arg in more places than desirable (to dependencies, non-cdylib crates in the package, etc).

**Comment by Mark-Simulacrum** [comment]
This feels like this is perhaps a Cargo issue, since I think -Clink-arg on Rust's side is sufficient based on discussion here. This may need an RFC, though.
