### ISSUE TITLE
Disable RLS packaging for 1.20

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#43200]
RLS is still not shipping but is in tree. In 1.19 it was disabled in a backport, so that needs to be done again for 1.20. I might prefer that it is disabled on master and then backported.

cc https://github.com/rust-lang/rust/issues/42357

**Comment by alexcrichton** [comment]
Handled in https://github.com/rust-lang/rust/pull/43307, specifically https://github.com/rust-lang/rust/pull/43307/commits/b15382fe2b3ae4d7e01774255cc3cce5046ddb85.

@cuviper if this is still an issue in packaging though please feel free to reopen!
