### ISSUE TITLE
Access bencher.summary in benchmark functions

### ISSUE THREAD

**Issue by Sekuraz** [rust-lang/rust#43213]
I'd like to not only print the benchmark results but to also do some computation with them. Therefore it would be great if i could simply write 

```rust
fn bench_256x256_256x256(bencher: &mut test::Bencher) {
    bencher.iter(|| {
        1+1;
     });
     let result = bencher.summary.unwrap();
}
```
Especially since everything besides Bencher.summary is already pub.

Otherwise all of the values that are computed and stored in Bencher.summary would be pointless. Changing the api should not be a problem, because Bencher is considered unstable.

**Comment by dtolnay** [comment]
I can see how accessing the summary would be useful! I believe this is going to require an [RFC](https://github.com/rust-lang/rfcs/blob/master/libs_changes.md) to explore the best way to expose the information you need.

Let's actually roll this into https://github.com/rust-lang/rfcs/issues/816 -- that way we keep the standard test framework minimal while allowing libraries to develop more sophisticated custom test frameworks that expose summary information or other nice things.
