### ISSUE TITLE
Unnecessary use of #[reexport_test_harness_main] in test

### ISSUE THREAD

**Issue by cptroot** [rust-lang/rust#43219]
While trying to figure out what the `#[reexport_test_harness_main]` attribute did, I ran across this line of code.

https://github.com/rust-lang/rust/blob/master/src/test/run-pass/core-run-destroy.rs#L18

Near as I can tell, the reference to `#[reexport_test_harness_main]` here doesn't do anything, and can be removed for clarity.

**Comment by Mark-Simulacrum** [comment]
Marking as an easy issue since it seems that removing that line is all that would need to be done here, and then if CI passes, great, if not, then we shouldn't remove it. Willing to mentor as well.

**Comment by shivanth** [comment]
I take this up 😄

**Comment by marioidival** [comment]
@Mark-Simulacrum close?
