### ISSUE TITLE
ICE calling unwrap on error value result.rs when working on network drive

### ISSUE THREAD

**Issue by JJStrath** [rust-lang/rust#43215]
Trying to use the csv crate by @BurntSushi and the memchr dependency fails to compile. *This only seems to happen when I'm working on a network drive* 

The code in this program is just the auto generated "Hello World" code. I am just attempting to go through the CSV tutorial, and had this at the first hurdle.

Thanks for your time! Backtrace included below:

### Edit 1 - Replace old output snippet with backtrace
```
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { c
ode: 5, message: "Access is denied." } }', src\libcore\result.rs:860:4
stack backtrace:
   0: _rdl_shrink_in_place
   1: std::panicking::Location::column
   2: std::panicking::Location::column
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic_fmt
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: <rustc_metadata::encoder::ImplVisitor<'a, 'tcx> as rustc::hir::itemlikevisit::ItemLikeV
isitor<'v>>::visit_impl_item
   9: rustc_metadata::locator::Context::report_errs
  10: rustc_metadata::creader::CrateLoader::new
  11: rustc_metadata::creader::CrateLoader::new
  12: <rustc_metadata::creader::CrateLoader<'a> as rustc::middle::cstore::CrateLoader>::proce
ss_item
  13: rustc_resolve::build_reduced_graph::<impl rustc_resolve::ToNameBinding<'a> for (rustc::
hir::def::Def, rustc::ty::Visibility, syntax_pos::Span, syntax_pos::hygiene::Mark)>::to_name_
binding
  14: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b> as syntax::visit:
:Visitor<'a>>::visit_item
  15: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b> as syntax::visit:
:Visitor<'a>>::visit_item
  16: rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a
>>::visit_expansion
  17: syntax::ext::expand::MacroExpander::expand_crate
  18: syntax::ext::expand::MacroExpander::expand_crate
  19: syntax::ext::expand::MacroExpander::expand_crate
  20: rustc_driver::driver::count_nodes
  21: rustc_driver::driver::count_nodes
  22: rustc_driver::driver::compile_input
  23: rustc_driver::run_compiler
  24: <unknown>
  25: _rust_maybe_catch_panic
  26: <rustc_driver::derive_registrar::Finder as rustc::hir::itemlikevisit::ItemLikeVisitor<'
v>>::visit_trait_item
  27: std::sys::imp::thread::Thread::new
  28: BaseThreadInitThunk
```

## Meta
rustc 1.18.0 (03fc9d622 2017-06-06)
binary: rustc
commit-hash: 03fc9d622e0ea26a3d37f5ab030737fcca6928b9
commit-date: 2017-06-06
host: x86_64-pc-windows-msvc
release: 1.18.0
LLVM version: 3.9

**Comment by durka** [comment]
Please do as suggested

> ```note: Run with `RUST_BACKTRACE=1` for a backtrace.```

Without that nobody can guess at the source of the error.

**Comment by JJStrath** [comment]
Thanks for the response, @durka. I didn't realise I could use backtrace when using cargo build, so thanks for the advice.

'''
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { c
ode: 5, message: "Access is denied." } }', src\libcore\result.rs:860:4
stack backtrace:
   0: _rdl_shrink_in_place
   1: std::panicking::Location::column
   2: std::panicking::Location::column
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic_fmt
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: <rustc_metadata::encoder::ImplVisitor<'a, 'tcx> as rustc::hir::itemlikevisit::ItemLikeV
isitor<'v>>::visit_impl_item
   9: rustc_metadata::locator::Context::report_errs
  10: rustc_metadata::creader::CrateLoader::new
  11: rustc_metadata::creader::CrateLoader::new
  12: <rustc_metadata::creader::CrateLoader<'a> as rustc::middle::cstore::CrateLoader>::proce
ss_item
  13: rustc_resolve::build_reduced_graph::<impl rustc_resolve::ToNameBinding<'a> for (rustc::
hir::def::Def, rustc::ty::Visibility, syntax_pos::Span, syntax_pos::hygiene::Mark)>::to_name_
binding
  14: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b> as syntax::visit:
:Visitor<'a>>::visit_item
  15: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b> as syntax::visit:
:Visitor<'a>>::visit_item
  16: rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a
>>::visit_expansion
  17: syntax::ext::expand::MacroExpander::expand_crate
  18: syntax::ext::expand::MacroExpander::expand_crate
  19: syntax::ext::expand::MacroExpander::expand_crate
  20: rustc_driver::driver::count_nodes
  21: rustc_driver::driver::count_nodes
  22: rustc_driver::driver::compile_input
  23: rustc_driver::run_compiler
  24: <unknown>
  25: _rust_maybe_catch_panic
  26: <rustc_driver::derive_registrar::Finder as rustc::hir::itemlikevisit::ItemLikeVisitor<'
v>>::visit_trait_item
  27: std::sys::imp::thread::Thread::new
  28: BaseThreadInitThunk
'''

I'll edit the main part to add this also.

**Comment by Mark-Simulacrum** [comment]
Could you provide the exact steps to reproduce? That is, it'd be helpful to have a Github repository or something like it that can be cloned to reproduce the problem. I suspect this is the typical difficulty Rust has with network drives, though.

**Comment by steveklabnik** [comment]
Triage: with no steps to reproduce, we cannot fix this. Closing until we can reproduce.
