### ISSUE TITLE
Deal with RLS vendoring on 1.20

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#43218]
In https://github.com/rust-lang/rust/issues/42719 we disabled RLS for 1.19 to solve a problem. May need to do this again in 1.20.

**Comment by alexcrichton** [comment]
Handled in https://github.com/rust-lang/rust/pull/43307, specifically https://github.com/rust-lang/rust/pull/43307/commits/b15382fe2b3ae4d7e01774255cc3cce5046ddb85.
