### ISSUE TITLE
"git commit" or just waiting a night results in bad stage2: "`std` compiled by an incompatible version of rustc"

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#43231]
# Steps to reproduce

* Get a clean full build directory: `./x.py clean && ./x.py build`
* Do some edits `src/librustc_mir`
* Do *either* `git commit -a` *or* wait until it is the next day
* `./x.py build`

# Expected behavior

I should get a working compiler both in stage1 and stage2.

# Actual behavior

The stage1 compiler is fine, but using the stage2 compiler results in
```
error[E0514]: found crate `std` compiled by an incompatible version of rustc
  |
  = help: please recompile that crate using this compiler (rustc 1.20.0-dev (2ea782c9b 2017-07-13))
  = note: crate `std` path #1: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_unicode-4a6846d7d8ce6979.rlib compiled by "rustc 1.20.0-dev (8a60e8605 2017-07-13)"
  = note: crate `std` path #2: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-8bdeae220109d9a1.rlib compiled by "rustc 1.20.0-dev (8a60e8605 2017-07-13)"
  = note: crate `std` path #3: /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-8bdeae220109d9a1.so compiled by "rustc 1.20.0-dev (8a60e8605 2017-07-13)"
```

The fact that this also happens when waiting until the next day makes this particularly annoying, it means I have to remember to always do a full build of all stages when I did some patching some day.

Also, "git commit" cannot be entirely avoided when doing compiler development, not everything you do is one huge commit that you can commit and push after testing everything.

**Comment by RalfJung** [comment]
@arielb1 suggested to do `touch src/librustc_metadata/lib.rs && ./x.py build`; I am trying this right now. Of course, this means I have to wait *again* for 20min.

**Comment by est31** [comment]
Known (and sadly old) bug: #39751

**Comment by est31** [comment]
@Mark-Simulacrum  can this be closed? https://github.com/rust-lang/rust/issues/39751#issuecomment-318228931

**Comment by Mark-Simulacrum** [comment]
Yep. Unfortunately it doesn't fix the problem of waiting to recompile after just making a commit, but there's no clear fix there -- I have some ideas, but nothing concrete yet, and I don't think we need to track it.
