### ISSUE TITLE
Too much large error span for sum()

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#43233]
This code:

```
fn sum_and_show(data: &[u32]) -> String {
    data.iter().sum().to_string()
}
fn main() {
    let s: String = sum_and_show(&[1, 2, 3]);
}
```

In rustc 1.20.0-nightly (b2c070787 2017-07-13) gives the error message:

```
error[E0619]: the type of this value must be known in this context
 --> ...\test.rs:2:5
  |
2 |     data.iter().sum().to_string()
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
The error message doesn't point to the exact location of the problem. The correct code is:

`data.iter().sum::<u32>().to_string()`

So probably I'd like an error message like:

```
error[E0619]: the type of this value must be known in this context
 --> ...\test.rs:2:5
  |
2 |     data.iter().sum().to_string()
  |                 ^^^^^
```

Even better: I'd like Rustc to infer the right type for sum(), not require a type hint there and compile the original code.

**Comment by kennytm** [comment]
I think rustc cannot confidently infer the type of `sum()`, because one could legally `impl Sum<&u32> for MyType` which produces a different `to_string()`

**Comment by zackmdavis** [comment]
Maybe related? #42234

**Comment by Mark-Simulacrum** [comment]
Going to go ahead and close in favor of https://github.com/rust-lang/rust/issues/36598. Not, perhaps, an exact duplicate but I think it's the same problem.
