### ISSUE TITLE
`impl<A, B> FromIterator<(A, B)> for (Vec<A>, Vec<B>)`?

### ISSUE THREAD

**Issue by Kixunil** [rust-lang/rust#43242]
Recently [/u/shortstomp](https://www.reddit.com/user/shortstomp) [asked on Reddit](https://www.reddit.com/r/rust/comments/6n8c6l/wondering_why_this_trait_isnt_implemented/) about [this example](https://play.rust-lang.org/?gist=4a93925c9f344567a66a1c120fe44696&version=stable).

The impl seems useful to me and I'm willing to implement it (possibly with more fields, e.g. A..J) if it's considered a good idea.

I've never tried hacking `std`, so why not try it? :)

**Comment by petrochenkov** [comment]
This is pretty much https://github.com/rust-lang/rfcs/pull/870 https://github.com/rust-lang/rfcs/issues/930.
It would be really nice to revive that RFC as a part of the ergonomic initiative.

**Comment by Kixunil** [comment]
Yeah, this is practically the opposite of  rust-lang/rfcs#870.

**Comment by Mark-Simulacrum** [comment]
Going to go ahead and close since I think this would need an RFC, see https://github.com/rust-lang/rfcs/issues/930 for the RFC tracking issue.
