### ISSUE TITLE
ICE: "encountered errors lowering pattern: [ConstEval(ConstEvalErr { ... kind: NonConstPath })]"

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#43250]
Following (wrong) code gives an error on beta 1.19 and stable 1.18, but ICEs on current nightly:

```rust
fn main() {
	let mut y;
	macro_rules! m {
		($a:expr) => {
			let $a = 0;
		}
	}
	m!(y);
}
```

The error (expected behaviour):
```
error: expected pattern, found `y`
```

The ICE message (new behaviour):
```
internal compiler error: /checkout/src/librustc_const_eval/pattern.rs:282: encountered errors lowering pattern: [ConstEval(ConstEvalErr { span: src/main.rs:8:5: 8:6, kind: NonConstPath })]
```

Nightly (soon beta) regression. Bisected using rust-bisect to #42964 (7acce3724d6ba5cb84d6eef6d6847f8573a1fe5a).

**Comment by est31** [comment]
One possible cause is #42886 . cc @durka @petrochenkov

**Comment by alexcrichton** [comment]
cc @rust-lang/compiler

**Comment by Mark-Simulacrum** [comment]
Also cc @eddyb specifically, looks CTFE related.

**Comment by eddyb** [comment]
What's surprising is that there's no name resolution error. Patterns shouldn't be able to refer to variables, *even* when there's macro treachery afoot.

**Comment by arielb1** [comment]
Why would there be a name-resolution error?

You can reach this in stable with range patterns:
```Rust
fn main() {
	let y: usize = 1;
	let 0...y = 1;
}
```

**Comment by eddyb** [comment]
We solved this in name resolution in other situations, didn't we? Like, if you have an array length that's a variable in scope.

**Comment by alexcrichton** [comment]
ping @eddyb and @arielb1, did y'all get any further in taking a look at this?

**Comment by eddyb** [comment]
@alexcrichton We don't agree on the solution. IMO name resolution should not see variables in scope from that position, only constant items.

**Comment by alexcrichton** [comment]
Hm ok, I guess in that sense this is a reminder that 1.20 is released in less than 3 weeks now, so the clock is ticking for getting *some* solution into the compiler.
