### ISSUE TITLE
improve case with both anonymous lifetime parameters

### ISSUE THREAD

**Issue by gaurikholkar** [rust-lang/rust#43269]
Address the case where both the regions are anonymous.
Driving example for this case is
```
12 |   fn foo(x: &mut Vec<&u8>, y:&u8) {
   |                      ---     --- these references must have the same lifetime
13 | 
14 |     x.push(y);
   |            ^ data from `y` flows into `x` here
```

cc @nikomatsakis

**Comment by nikomatsakis** [comment]
cc #42516 -- I believe @gaurikholkar is already pretty far along in this particular patch.

**Comment by nikomatsakis** [comment]
So I was talking to @aturon and @jonathandturner and they both mentioned that the current message feels a bit confused to them. @jonathandturner turner wrote (hope he doesn't mind me quoting), "my naive brain goes 'can't the compiler magic up the constraint that the lifetimes match if it's inferring them anyway?'"

Anyway, I was thinking that it might be an improvement to change the wording to:

```
error[E0623]: lifetime mismatch
  --> $DIR/ex3-both-anon-regions.rs:12:12
   |
11 | fn foo(x: &mut Vec<&u8>, y: &u8) {
   |                    ---      --- these references are not declared with the same lifetime...
12 |     x.push(y);
   |            ^ ...but data from `y` flows into `x` here

error: aborting due to previous error
```

**Comment by gaurikholkar** [comment]
Opened up a PR #43541

**Comment by gaurikholkar** [comment]
Working on this now #43877

**Comment by nikomatsakis** [comment]
This works now, no? Closing.
