### ISSUE TITLE
Is there a safe way of constraining FromStr::Err to implement Debug?

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/rust#43262]
The `std::str::FromStr` trait takes a `type` field which specifies the type of error it will return if a conversion cannot be made; it also has a function that returns `Result<T, Self::Err>`.

In a generic function with generic `T` constrained by `where T: std::str::FromStr`, the result of `T::from_str(...)` cannot be unwrapped unless an additional constraint `,std::fmt::Debug` is applied to the the error type of T passed to the generic function because unwrap requires the error type implement `std::fmt::Debug`.

e.g. this will not compile:
```rust
fn value_from_string<T>(s: &str) -> T
where T: std::str::FromStr
{
    return T::from_str(s).unwrap();
}
```

and one must always use this additional constraint instead:
```rust
fn value_from_string<T>(s: &str) -> T
where T: std::str::FromStr, <T as std::str::FromStr>::Err : std::fmt::Debug
{
    return T::from_str(s).unwrap();
}
```

Since `FromStr` will *always* require (in practice) that T::Err implement `std::fmt::Debug` in order to actually unwrap the result, is there a safe way to introduce this constraint into `FromStr` that does not break the language?

**Comment by mqudsi** [comment]
This stems from an assumption that Result<T,E> should always have E implement std::fmt::Debug, which is not the case.

**Comment by surphury** [comment]
Thanks for this!!!
