### ISSUE TITLE
Wrong explanation in the E0303 extended error message

### ISSUE THREAD

**Issue by nodakai** [rust-lang/rust#43265]
* https://doc.rust-lang.org/error-index.html#E0303

> The `op_string_ref` binding has type `&Option<&String>` in both cases.

No, in the first case one would expect it to be of type `&Option<String>` (note the lack of the second `&`) as illustrated by this sample code (to intentionally generate a type mismatch):

```rust
fn main() {
match Some("hi".to_string()) {
    ref op_string_ref @ Some(_) => { let () = op_string_ref; },
    None => {},
}
}
```

```
  |
3 |     ref op_string_ref @ Some(_) => { let () = op_string_ref; },
  |                                          ^^ expected reference, found ()
  |
  = note: expected type `&std::option::Option<std::string::String>`
             found type `()`
```

* https://play.rust-lang.org/?gist=92825525e0709d040abcebaf4cb1e4cb&version=stable

CC @michaelsproul @GuillaumeGomez according to git-blame

**Comment by michaelsproul** [comment]
Yeah, you're right that it is confusing. I noticed that error E0009 is also generated before E0303 and the note for E0009 suggests changing the `Some(s)` into `Some(ref s)`, which would then make `op_string_ref` almost have type `&Option<&String>` in the first example.

First example here: https://play.rust-lang.org/?gist=ebb9cd511e785d055a5ec3b97f82e4cb&version=stable
With `Some(ref s)` here: https://play.rust-lang.org/?gist=4c0007efcfbbc79c00126785415b35e0&version=stable

Perhaps we should just update the first example so it has the `Some(ref s)`

**Comment by GuillaumeGomez** [comment]
Taking a look.

**Comment by BGR360** [comment]
This diagnostic is no longer emitted by the compiler. Can we close this?
