### ISSUE TITLE
improve case with both anonymous lifetime parameters in functions and trait objects.

### ISSUE THREAD

**Issue by gaurikholkar** [rust-lang/rust#43276]
An example of the above iss
```rust
fn foo(x:  fn(&u8, &u8), mut y: Vec<&u8>, z: &u8) {
  y.push(z); 
}
```
cc @nikomatsakis

**Comment by nikomatsakis** [comment]
So, this particular example is a special-case of https://github.com/rust-lang/rust/issues/43269 -- but I think that there is [an analogous version](https://play.rust-lang.org/?gist=911d5a3c83c07a38a8a8d5e5008ea0d8&version=nightly) where the user already has given a name:

```rust
fn foo<'a>(x:  fn(&u8, &u8), mut y: Vec<&u8>, z: &'a u8) {
  y.push(z); 
}

fn main() { }
```

This seem to give the correct error message, though, so I guess we just need a test:

```
error[E0621]: explicit lifetime required in the type of `y`
 --> src/main.rs:2:10
  |
1 | fn foo<'a>(x:  fn(&u8, &u8), y: Vec<&u8>, z: &'a u8) {
  |                              - consider changing the type of `y` to `std::vec::Vec<&'a u8>`
2 |   y.push(z); 
  |          ^ lifetime `'a` required
```

**Comment by gaurikholkar** [comment]
Done in #44516. Closing the issue.
cc @nikomatsakis
