### ISSUE TITLE
jemalloc still pulled in with `extern crate alloc_system` on nightlies >= 2017-07-07

### ISSUE THREAD

**Issue by chenxiaolong** [rust-lang/rust#43277]
It seems that ever since the 2017-07-07 nightly, using the `alloc_system` crate causes jemalloc to be linked in. For example, if I change the default hello world sample crate to the following:

```rust
#![feature(alloc_system)]
extern crate alloc_system;

fn main() {
    println!("Hello, world!");
}
```

then the binary built by the 2017-07-07 toolchain contains jemalloc symbols, while the binary built by the 2017-07-06 toolchain does not.

```
[hello] rm -rf target/release; cargo +nightly-2017-07-06 build --release; strings target/release/hello | grep -c jemalloc
   Compiling hello v0.1.0 (file:///tmp/rust/hello)
    Finished release [optimized] target(s) in 0.32 secs
0
[hello] rm -rf target/release; cargo +nightly-2017-07-07 build --release; strings target/release/hello | grep -c jemalloc
   Compiling hello v0.1.0 (file:///tmp/rust/hello)
    Finished release [optimized] target(s) in 0.42 secs
269
```

Could this be related to the allocator PRs that have been merged recently? Or perhaps the code above is no longer the way to select the system allocator?

---

Versions:
* `nightly-2017-07-06-x86_64-unknown-linux-gnu` (`rustc 1.20.0-nightly (3610a70ce 2017-07-05)`)
* `nightly-2017-07-07-x86_64-unknown-linux-gnu` (`rustc 1.20.0-nightly (696412de7 2017-07-06)`)

**Comment by Mark-Simulacrum** [comment]
cc @alexcrichton

**Comment by alexcrichton** [comment]
Ah yeah this is intended behavior as the implementation of global allocators changed in https://github.com/rust-lang/rust/pull/42727, and you should be able to see the current state of affairs at the top of https://github.com/rust-lang/rust/issues/27389

**Comment by chenxiaolong** [comment]
@alexcrichton Thanks for the info!

Forgive my ignorance, but with the new global allocators implementation, is there an easy way to specify that the system allocator should be used? What would I need to specify in the code?

**Comment by alexcrichton** [comment]
Oh sure yeah, to specify the system allocator as the global allocator:

```rust
use std::heap::System;

#[global_allocator]
static ALLOCATOR: System = System;
```

**Comment by chenxiaolong** [comment]
Thanks! That worked perfectly. For reference, I tested with:

```rust
#![feature(global_allocator)]
#![feature(allocator_api)]

use std::heap::System;

#[global_allocator]
static ALLOCATOR: System = System;

fn main() {
    println!("Hello, world!");
}
```

**Comment by alexchandel** [comment]
For future seekers, this has moved to `std::alloc::System` as of ≤1.31. Try:

```rust
use std::alloc::System;

#[global_allocator]
static ALLOCATOR: System = System;
```
