### ISSUE TITLE
Trivial vec![] creation then iteration doesn't optimize out the allocation

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#43272]
Rustc used to be able to replace `vec![1, 2, 3].iter().sum::<i32>()` with a constant when optimizing, not at the moment. It simply looks like a Layout method that is not inlinable.

(This is a regression strictly speaking — stable & beta can do this optimization, but not nightly.)

Code to reproduce:

[playground link](https://play.rust-lang.org/?gist=28cace98ef0d7677127ce1f4f72f2d5e&version=nightly)

```rust
pub fn sum_me() -> i32 {
    vec![1, 2, 3].iter().sum::<i32>()
}
```

**Comment by nodakai** [comment]
Are there any ways to write automated tests to check for "regressions" like this? Assertions against LLVM bitcode?

**Comment by kennytm** [comment]
@nodakai Yes [`codegen` tests](https://brson.github.io/2017/07/10/how-rust-is-tested#codegen) can be used for this, e.g. https://github.com/rust-lang/rust/blob/master/src/test/codegen/alloc-optimisation.rs

**Comment by Mark-Simulacrum** [comment]
cc @arielb1 -- seems LLVM related

**Comment by arielb1** [comment]
Nope. Just `Layout::repeat` (https://github.com/rust-lang/rust/blob/0565653eecd7d667dbb28bb5d3008e783950892a/src/liballoc/allocator.rs#L210) that is not marked as inline.

**Comment by arielb1** [comment]
cc @alexcrichton

**Comment by arielb1** [comment]
I didn't confirm that making Layout::repeat as inline fixes this, so please confirm that/add a test before closing.
