### ISSUE TITLE
Create a helpful error message when typing "mut ref" instead of "ref mut"

### ISSUE THREAD

**Issue by locka99** [rust-lang/rust#43286]
I've gotten the order of mut and ref mixed up a few times like this:

let mut ref y = &x;

This generates a "error: expected identifier, found keyword `ref`" error which isn't too helpful for people used to languages that allows the order of keywords to be mixed e.g. static and const in C/C++.

The compiler should suggest "did you mean 'ref mut'?" for the above.

**Comment by GuillaumeGomez** [comment]
Taking a look.
