### ISSUE TITLE
rustbuild: default values from config.mk now effectively override config.toml

### ISSUE THREAD

**Issue by infinity0** [rust-lang/rust#43295]
#42543 was fixed by unconditionally reading config.mk. However, sometimes this is populated by default values that the user did *not* give on the command line, for example

~~~~
CFG_RELEASE_CHANNEL  := dev
~~~~

when running from a location with a `.git` subdirectory (such as the Debian rustc git repo). This has the effect of rendering the corresponding command-line flags to `x.py` useless. For example even if I have

~~~~
[rust]
channel = "stable"
~~~~

and run

~~~~
$ ./x.py build --config myconfig.toml
~~~~

this will get ignored and the value from `config.mk` (which I did not set) takes precedence.

I can work around this by explicitly passing `--release-channel` to `./configure` but this behaviour does not help rust's overall goal of eventually phasing out this file.

Other flags affected include possibly `CFG_PREFIX`, but probably not `CFG_ENABLE_DEBUGINFO_*` as `bootstrap/config.rs` does not appear to read them.

cc @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
I'm going to mark as P-medium, cc @alexcrichton and @aidanhs. I think this should hopefully resolve to merging the defaults in before we parse command line params. Not sure if I'll have time to investigate in the short term, though, but certainly within a few days I hope.

**Comment by retep998** [comment]
Would this be fixed by simply not using `config.mk` at all and having `configure` create `config.toml` instead? https://github.com/rust-lang/rust/issues/40730

**Comment by infinity0** [comment]
That would probably work, yes.

**Comment by infinity0** [comment]
As an amendment, this bug *does* affect `CFG_ENABLE_DEBUGINFO_*` etc, I was grepping for the full name and didn't notice [this part](https://github.com/rust-lang/rust/blob/master/src/bootstrap/config.rs#L484).
