### ISSUE TITLE
ICE: Struct cannot be packed and aligned

### ISSUE THREAD

**Issue by Boddlnagg** [rust-lang/rust#43317]
The following code ([playground](https://play.rust-lang.org/?gist=fa2135f4f52eb9d31c3f41a95b28b08c&version=nightly)) ICEs with `error: internal compiler error: /checkout/src/librustc/ty/layout.rs:603: Struct cannot be packed and aligned`:

```rust
#![feature(repr_align, attr_literals)]

#[repr(packed)]
#[repr(align(4))]
pub struct BadStruct {
    foo: i32
}

fn main() {
    BadStruct { foo: 0 };
}
```

It's probably correct that this is an error, but it should not be an ICE. Also, the ICE only appears when the struct is actually instantiated, only defining it is not sufficient, but should also result in an error.

**Comment by bitshifter** [comment]
Interesting, if you change the repr to a one liner ([playground](https://play.rust-lang.org/?gist=fa2135f4f52eb9d31c3f41a95b28b08c&version=nightly)) you get a compile error as expected (tested https://github.com/rust-lang/rust/blob/master/src/test/compile-fail/conflicting-repr-hints.rs#L30). I didn't realise that the behaviour would be different if the repr statements were split. I'll take a look.

**Comment by bitshifter** [comment]
The other compile fail tests in that file don't work if the representation hints are split also. I assume that's not a good thing.
