### ISSUE TITLE
`home_dir` incorrectly considers `HOME` environment variable on Windows

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#43321]
The definition of `home_dir` provided by the standard library is incorrect because it considers the `HOME` environment variable on Windows. This causes surprising situations where a Rust program will behave differently depending on whether it is run under a Unix emulation environment like Cygwin or MinGW. Neither Cargo nor rustup use the standard libraries definition - they use the definition [here](https://github.com/brson/home).

I don't see an existing issue for this.

**Comment by durka** [comment]
#28940 #40320

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/28940.
