### ISSUE TITLE
`time::Instant` is a different size of different platforms

### ISSUE THREAD

**Issue by Thomasdezeeuw** [rust-lang/rust#43332]
`time::Instant` on Linux is 16 bytes, while it is 8 bytes on MacOs. This makes it hard to assert the size of any structs using it.

[Playground link](https://play.rust-lang.org/?gist=832cbc8b85cafb35eb01bf7187c7debc&version=stable)
```rust
use std::mem;
use std::time::Instant;

fn assert_size<T>(want: usize) {
    assert_eq!(mem::size_of::<T>(), want);
}

fn main() {
    // This is 16 on Linux, but 8 on MacOS (and Windows?).
    assert_size::<Instant>(16);

    // This is 24 on Linux, but 16 on MacOS (and Windows?).
    assert_size::<Option<Instant>>(24);
}
```

**Comment by sfackler** [comment]
Why do you want to make assertions about the size of a struct with an `Instant` in it?

**Comment by Thomasdezeeuw** [comment]
I’m using it as a deadline. And I want to make sure the struct doesn’t grow in the future, it’s big enough already.

Met vriendelijke groet,

Thomas de Zeeuw
https://thomasdezeeuw.nl <https://thomasdezeeuw.nl/>
thomasdezeeuw@gmail.com <mailto:thomasdezeeuw@gmail.com>

**Comment by Mark-Simulacrum** [comment]
Perhaps you could use `#[cfg(unix)]`? I don't think it's likely that we'll change anything to increase or decrease the size of Instant based on platform... On OS X today, an Instant is defined by `u64` whereas on other unix platforms it's a `libc::timespec`... I would presume that this is correct and won't change.

**Comment by Thomasdezeeuw** [comment]
That is what I’m currently using. It just seemed odd so I filed this bug for it. But if no change is possible or desired it might be worth documenting it?

Met vriendelijke groet,

Thomas de Zeeuw
https://thomasdezeeuw.nl <https://thomasdezeeuw.nl/>
thomasdezeeuw@gmail.com <mailto:thomasdezeeuw@gmail.com>

**Comment by Mark-Simulacrum** [comment]
Hm, well, I'll nominate for libs team, but I personally don't think documenting differences in size really makes sense today.

**Comment by durka** [comment]
@Mark-Simulacrum stuff like this could be a good candidate for the "portability lint" [discussed here](https://github.com/rust-lang/rfcs/blob/master/text/1868-portability-lint.md) and [here](https://github.com/rust-lang/rfcs/issues/1748).

**Comment by alexcrichton** [comment]
The libs team decided that we're not going to make any guarantees about sizes of structs, and we've opened https://github.com/rust-lang/rust/issues/43601 to track documenting that the sizes may be different.

**Comment by Thomasdezeeuw** [comment]
Sounds good to me.
