### ISSUE TITLE
Consider reordering unreached code and unused variable warnings

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/rust#43349]
When compiling code that has an unreachable variable that is the only use of a previously declared section, rustc emits (at least in this case) the warnings about unused variables prior to the warnings about the unreachable code.

In many cases (esp. in IDEs or in vim's quickfix) errors/warnings are considered in the order they are seen (or the compiler is configured to stop after one error). In this case, it can lead one to waste time trying to find out how a variable is unused (in my case: look for shadow declarations) when in reality, it's just that the usage is unreachable.

```
src/main.rs|164 col 43 warning| unused variable: `stats_tx`
||     |
|| 164 | fn worker_thread(params: Arc<Parameters>, stats_tx: mpsc::Sender<Statistics>, rx: chan::Receiver<ThreadParam>) {
||     |                                           ^^^^^^^^
||     |
||     = note: #[warn(unused_variables)] on by default
src/main.rs|220 col 5 warning| unused result which must be used
||     |
|| 220 |     stats_tx.send(local_stats);
||     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
||     |
||     = note: #[warn(unused_must_use)] on by default
src/main.rs|220 col 5 warning| unreachable statement
||     |
|| 220 |     stats_tx.send(local_stats);
||     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
||     |
||     = note: #[warn(unreachable_code)] on by default
```

**Comment by oli-obk** [comment]
This won't help for IDEs that display diagnostics inline.

Why is `unused_variables` even triggered for a variable used in dead code?  Fixing that would solve this issue, too I think?

**Comment by Enselic** [comment]
Triage: In [this ](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6e1c7a9ae3ba2abab2a5f5d75d362e71)code the unreachability warning comes first:

```rust
fn main() {
    let unused = 42;
    panic!();
    println!("Hello, world! {unused}");
}
```

What does the code need to look like for the order to be reversed?

**Comment by jackh726** [comment]
I'm going to close this, as it's not clear there's still a problem (and in reality I think it's hard to make guarantees about order of diagnostics anyways).
