### ISSUE TITLE
rustc 1.20.0-beta.1 breaks rustup

### ISSUE THREAD

**Issue by CryZe** [rust-lang/rust#43341]
rustc 1.20.0-beta.1 (e93aa3aa8 2017-07-18) on x86_64-unknown-linux-gnu breaks rustup for some reason. All(?) of its commands seem to exit with error code 1. At least this is what's happening in 3 independent instances:

https://travis-ci.org/racer-rust/racer/jobs/255346964
https://travis-ci.org/CryZe/livesplit-core/jobs/255302701
https://travis-ci.org/integer32llc/rust-playground/jobs/255088861

```
$ rustup component add rust-src
error: missing key: 'url'
The command "rustup component add rust-src" failed and exited with 1 during .
```

**Comment by Mark-Simulacrum** [comment]
I can't seem to reproduce on macOS or Ubuntu:

```
$ rustup update beta
info: syncing channel updates for 'beta-x86_64-unknown-linux-gnu'

  beta-x86_64-unknown-linux-gnu unchanged - rustc 1.20.0-beta.1 (e93aa3aa8 2017-07-18)

$ rustup component add --toolchain beta rust-src
info: downloading component 'rust-src'
  2.8 MiB /   2.8 MiB (100 %)   1.6 MiB/s ETA:   0 s
info: installing component 'rust-src'
```

**Comment by CryZe** [comment]
Mmh, I can't seem to be able to reproduce it locally either. But it seems to always happen on Travis, even when completely wiping the CI Cache.

**Comment by Mark-Simulacrum** [comment]
Hm. Interesting. I wonder if Travis is somehow using an old rustup or something.... I worry that this'll be hard to debug though if it only fails in Travis.

**Comment by sfackler** [comment]
It looks like Travis's rustup install logic pulls their own version of `rustup-init.sh` - they could be installing an old version of rustup that doesn't understand newer manifests?

**Comment by CryZe** [comment]
Diffing the 2 rustup-init.sh's showed no change whatsoever, but I suspect there must still be a reason they are using their own rustup-init.sh

**Comment by CryZe** [comment]
Yup, looks like they are still on rustup 1.4.0, which is apparently incompatible with the latest beta?!

**Comment by kennytm** [comment]
Given the response on travis-ci/travis-ci#8124, that this happens due to bad cache handling on Travis, I think this should be closed?

**Comment by CryZe** [comment]
Yeah this can be closed as it is solely a Travis issue that is mostly resolved.
