### ISSUE TITLE
Closure/lifetime errors could be more informative/user friendly

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#43353]
In particular, they could tell you which captured variable(s) cause the lifetime issue

E.g.,

```
error[E0477]: the type `[closure@src/build/rustc.rs:60:13: 66:10 args:&[std::string::String], controller:build::rustc::RlsRustcCalls, changed:std::collections::HashMap<std::path::PathBuf, std::string::String>, buf:std::sync::Arc<std::sync::Mutex<std::vec::Vec<u8>>>]` does not fulfill the required lifetime
  --> src/build/rustc.rs:60:9
   |
60 |         run(move || {
   |         ^^^
   |
   = note: type must satisfy the static lifetime
```

In this case `args` is the issue, but this is not described in the error.

In general, I think we could do much better here by specialising the error message for closures and deconstructing the type, rather than using the hidden struct type. I.e., given information about captured variables. The current message means you need to understand the implementation of closures to make sense of the error.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this as there's not a reproducible example and we have plenty of "closures and {lifetimes, inference, etc} can be better" issues so I'm fairly certain it's covered by one of them.
