### ISSUE TITLE
Visibility errors on nightly

### ISSUE THREAD

**Issue by mrmonday** [rust-lang/rust#43365]
With the following code:

```rust
#[repr(C)]
struct _IP_ADDRESS_STRING {
    pub String: [libc::c_char; 4 * 4],
}

pub type IP_ADDRESS_STRING = _IP_ADDRESS_STRING;
```
Context: https://github.com/libpnet/libpnet/blob/ae54597201eda692d5c4a7358ab826f22458dfbe/src/bindings/winpcap.rs#L58-L63

I get errors like:
```
error: type `bindings::winpcap::_IP_ADDRESS_STRING` is private
   --> src\datalink\winpcap.rs:388:24
    |
388 |     let mask_str_ptr = unsafe { &(*ip_cursor) }.IpMask.String.as_ptr() as *const i8;
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Full set of errors: https://ci.appveyor.com/project/mrmonday/libpnet/build/1.0.553/job/u3cufry4pcqbrn8x#L632

That is, defining a private type, and a public alias to it, using that public alias in a structure, then accessing the structure, gives the error(s) above.

This code has worked since pre-1.0, but is broken on the latest nightly builds.

I've noticed that there were some recent breaking changes to visibility - https://github.com/rust-lang/rust/commit/b80b659d674fa19b2b48142e4f7974544bc8d5f6 - and am wondering if this was an intentional breakage, or if I should change my code.

**Comment by petrochenkov** [comment]
This is intentional, the type `_IP_ADDRESS_STRING` is private and therefore it can't be used outside of the module `winpcap` in which it's defined.

>This code has worked since pre-1.0, but is broken on the latest nightly builds.

This code worked until the fall of 2015 due to holes in the privacy checker, after that the holes were fixed and `pub type IP_ADDRESS_STRING = _IP_ADDRESS_STRING;` was reported as deprecated.
I'm not sure why this wasn't fixed in `libpnet` since then (it's also strange that it wasn't caught by our regression testing).

**Comment by TimNN** [comment]
> (it's also strange that it wasn't caught by our regression testing, I'd send a fix if it was).

Based on the name of the module (`_win_pcap`) containing the problematic line, I would assume that this wasn't caught because it occurred in windows specific code, which AFAIK neither crater nor cargobomb check.

**Comment by mrmonday** [comment]
> This code worked until the fall of 2015

That can't be right - the code works on stable and beta channels - https://ci.appveyor.com/project/mrmonday/libpnet

**Comment by TimNN** [comment]
> > This code worked until the fall of 2015
>
> That can't be right - the code works on stable and beta channels 

I think "worked" meant "worked without warnings" in this context. Both `beta` and `1.15.0` produce lots of warnings like this:

```
warning: private type `bindings::winpcap::_PACKET` in public interface (error E0446), #[warn(private_in_public)] on by default
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
```

**Comment by mrmonday** [comment]
While I'm here, is there a flag I can pass to cargo to make my CI builds treat warnings as errors?

**Comment by TimNN** [comment]
@mrmonday: One thing you can do is add `#![deny(warnings)]` to your crate, although that will be active locally as well. If you want to pass a flag to cargo, either `cargo rustc -- --deny warnings` or `RUSTFLAGS=--deny warnings"` should work, I think.

**Comment by mrmonday** [comment]
Thanks for your help. I'll close this, since it's expected behaviour.
