### ISSUE TITLE
Unlist outdated Rust pages from search engines

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#43385]
https://doc.rust-lang.org/1.0.0/book/installing-rust.html is the third result for "windows rust install" on duckduckgo

Could either outdated pages be marked as such so search engines start to move them down or the links adjusted, so even if someone ends up on that page they notice it's outdated? I'm not sure what the correct policy on that is, but something should be done about it. That page lists direct links to `1.0.0` beta installers

EDIT: the best solution might be something like what `boost` does: place a big banner on the top of the page noting that the page is outdated and offer a link to the current page.

**Comment by sfackler** [comment]
cc @steveklabnik

**Comment by steveklabnik** [comment]
See https://github.com/rust-lang/rfcs/pull/1826 and tons of other issues already on the tracker.

I'm going to close this in favor of those, thanks!
