### ISSUE TITLE
Support different backend for testing

### ISSUE THREAD

**Issue by farodin91** [rust-lang/rust#43381]
I like how the test works in rust, but I want to integrate them into intellij-rust/intellij-rust#1485. Therefore it would be cool to get test results in a different format like JSON.

This could be done by each test returns a single line JSON object and a single line conclusion at the end.

**Comment by mkaput** [comment]
For IntelliJ Rust, actually [TeamCity Service Messages](https://confluence.jetbrains.com/display/TCD10/Build+Script+Interaction+with+TeamCity) would be perfect :)

**Comment by gilescope** [comment]
Yep, agreed. I like how NUnit3 does it. They have a '-teamcity' command line flag that turns on the service messages. This would make integration with enterprise teamcity instances a doddle. Should be really quite easy functionallity to add and for the utility it brings it seems a no-brainer for me. (I suspect TeamCity isn't the only CI that interprets the TeamCity Service Messages).

**Comment by gilescope** [comment]
Should have a PR ready for review in a few days to support the TeamCity service messages. Need to test it with TeamCity first and ensure there's tests around it.

**Comment by dtolnay** [comment]
I would love to support this but as discussed in https://github.com/rust-lang/rust/pull/44813 let's track this as part of https://github.com/rust-lang/rfcs/issues/816.
