### ISSUE TITLE
rustbuild: bootstrap is rebuilt when building with multiple build compilers in the same tree

### ISSUE THREAD

**Issue by segevfiner** [rust-lang/rust#43390]
If you use multiple `build` compilers in the same Rust source tree, rustbuild/bootstrap is rebuilt when you switch between them. Wouldn't it make sense to keep multiple built bootstrap copies per `build` compiler to avoid this? It might have been a conscious decision not to do this though.

Essentially rustbuild/bootstrap is built into `build/bootstrap` and you can probably add a `build` specific directory in there. But note that the directories under the build directory are per `target` and this one is per `build`, I think...

**Comment by Mark-Simulacrum** [comment]
It feels unnecessarily complicated to maintain different bootstrap's for each `build`. In all cases that I can think, it should be sufficient to not rebuild bootstrap if it's already been built...

**Comment by Mark-Simulacrum** [comment]
I don't think this is something we're likely to implement as it'll increase implementation complexity and I imagine switching `build` compilers happens fairly rarely (there's no real reason to do so).
