### ISSUE TITLE
As of 1.19 it is not possible to accurately measure unit test coverage

### ISSUE THREAD

**Issue by ctz** [rust-lang/rust#43410]
1.19 prevents access to `-Zno-landing-pads`. I was using that to get accurate test coverage; without it all landing pads appear as uncovered code at the start and end of every function.

`-Cpanic=abort` is intended to be the stable replacement for `-Zno-landing-pads` but unfortunately that isn't supported for unit tests (apparently, because libtest requires unwinding support).

I'd like a way to do any of the following on stable:

- restore `no-landing-pads` behaviour, or,
- have `panic=abort` work for unit tests. Note that I don't much care that `should_panic` tests wouldn't work.

Is there some combination of cargo/rustc options that might achieve that?

**Comment by rkruppe** [comment]
`#[should_panic]` tests not working seems like a pretty big downside. Even if you don't care, the usefulness of coverage info seems entirely independent from whether you have `#[should_panic]` tests. Perhaps there's a better solution, e.g.,

- Not having landing pads mess up coverage information (how do C++ tools solve this?)
- Having a mode in libtest that runs tests in a child process, to be able to detect and handle panics

**Comment by kennytm** [comment]
@rkruppe 

C++ tools solve this by:

1. In GCC, the generated `*.gcno` will encode whether an edge in the control-flow graph is exceptional or not, via the `GCOV_ARC_FAKE` flag. Coverage analyzer can choose to ignore these edges. LLVM's `insert-gcov-profiling` pass [does not provide any of these information](https://github.com/llvm-mirror/llvm/blob/2c420717ff9ce931dd9ac120e0f7c66a2131be55/lib/Transforms/Instrumentation/GCOVProfiling.cpp#L401).

2. clang uses instrprof (#34701) instead of GCOV.

**Comment by marco-c** [comment]
I guess we could try to add support for GCOV_ARC_FAKE in LLVM's gcov instrumentation.

**Comment by marco-c** [comment]
The tracking issue for -Zprofile is #42524.

I think in the meantime, until this is fixed in LLVM, you can keep using -Zno-landing-pads as a workaround.

**Comment by ctz** [comment]
Note #43410 removes -Zno-landing-pads

**Comment by sanmai-NL** [comment]
@ctz: that's this issue, I think you mean a PR.

**Comment by ctz** [comment]
Derp. I meant #70175

**Comment by marco-c** [comment]
Another workaround can be https://github.com/mozilla/grcov/issues/427#issuecomment-623995594:
> I managed to run tests for pyo3 in using `-Cpanic=abort -Zpanic_abort_tests` in `RUSTFLAGS`.
The doc tests were failing with that so adding an extra `RUSTDOCFLAGS="-Cpanic=abort"` fixes failures.

**Comment by rivy** [comment]
Alternatively, pinning the rust version to `nightly-2020-04-29` for code coverage also works, without altering flags or resultant coverage.

**Comment by workingjubilee** [comment]
We no longer support gcov-based profiling.
