### ISSUE TITLE
Latest Rust nightly does not work on FreeBSD

### ISSUE THREAD

**Issue by alexreg** [rust-lang/rust#43427]
I'm not sure when exactly it broke, but I suspect within the last few days. When I run `rustc` now, I get:

```
$ rustc
ELF binary type "0" not known.
/home/alexuk/.rustup/toolchains/nightly-x86_64-unknown-freebsd/bin/rustc: ELF: not found
/home/alexuk/.rustup/toolchains/nightly-x86_64-unknown-freebsd/bin/rustc: ?gߓ?4????O06???: not found
/home/alexuk/.rustup/toolchains/nightly-x86_64-unknown-freebsd/bin/rustc: DD: not found
/home/alexuk/.rustup/toolchains/nightly-x86_64-unknown-freebsd/bin/rustc: ?T: not found
/home/alexuk/.rustup/toolchains/nightly-x86_64-unknown-freebsd/bin/rustc: Wui: not found
/home/alexuk/.rustup/toolchains/nightly-x86_64-unknown-freebsd/bin/rustc: 6: Syntax error: ")" unexpected
```

And the output of `readelf -h $(which rustc)` is the following:

```
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 09 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - FreeBSD
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0xa4420
  Start of program headers:          64 (bytes into file)
  Start of section headers:          11889304 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         9
  Size of section headers:           64 (bytes)
  Number of section headers:         44
  Section header string table index: 41
```

I'm using the latest version of Rustup, if it makes a difference. Did the build script get botched recently, or something?

**Comment by Mark-Simulacrum** [comment]
I'm guessing it's likely this is because of the rustbuild changes, though I'm not sure yet. Attempting to bisect...

**Comment by alexreg** [comment]
Okay, thanks for getting on this quickly @Mark-Simulacrum.

**Comment by Mark-Simulacrum** [comment]
For the time being, `rustup install nightly-2017-07-22` should work.

**Comment by beatgammit** [comment]
For me it seems like a problem with rustup. When I run `rustc`, I get the error, but if I run it directly `~/.rustup/.../nightly.../bin/rustc`,, it works fine. I'm going to try updating `rustup`.

**Comment by Mark-Simulacrum** [comment]
I'm hopeful that #43430 will fix this, so tomorrow's nightly should hopefully work again. Will ping here once it lands.

**Comment by Others** [comment]
I had a very similar problem on a fresh Ubuntu VM, and `rustup install nightly-2017-07-22` fixed the problem. (So I think it's probably the same issue.)

**Comment by Mark-Simulacrum** [comment]
Please let me know if tomorrow's nightly works on FreeBSD and if not we'll reopen.

**Comment by beatgammit** [comment]
I just built on last night's nightly (2017-07-24) and it worked for me. I intended to test this yesterday but got busy.

Thanks for the timely patch!

**Comment by alexreg** [comment]
Thanks @Mark-Simulacrum, looks all good for me too. :-)
