### ISSUE TITLE
x86_mm256_sad_epu8 intrinsic has incorrect return type

### ISSUE THREAD

**Issue by the8472** [rust-lang/rust#43439]
According to [intel documentation](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#techs=AVX,AVX2&expand=2800,362,4676,4678,2880,532,533,4726,4535&text=sad) the return type should be `64x4` but rustc expects a `8x32`

Test case:

```rust
#![feature(platform_intrinsics)]
#![feature(repr_simd)] 

#[repr(simd)]
struct u8x32(u8,u8,u8,u8,u8,u8,u8,u8,u8,u8,u8,u8,u8,u8,u8,u8,u8,u8,u8,u8,u8,u8,u8,u8,u8,u8,u8,u8,u8,u8,u8,u8,);
#[repr(simd)]
struct u64x4(u64,u64,u64,u64,);

extern "platform-intrinsic" {
 fn x86_mm256_sad_epu8(x: u8x32, y: u8x32) -> u64x4;
}

fn main() {}
```

Compiler error:

```
error[E0442]: intrinsic return value has wrong type: found vector with length 4, expected length 32
  --> src/main.rs:10:2
   |
10 |  fn x86_mm256_sad_epu8(x: u8x32, y: u8x32) -> u64x4;
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by alexcrichton** [comment]
cc @BurntSushi

**Comment by BurntSushi** [comment]
I think the [`platform-intrinsic` definition](https://github.com/rust-lang/rust/blob/152055451c552121be35a179bb77194e02800baa/src/etc/platform-intrinsics/x86/avx2.json#L173-L179) has an incorrect return type?
