### ISSUE TITLE
error: internal compiler error: /checkout/src/librustc_typeck/check/mod.rs:4419: impossible case reached

### ISSUE THREAD

**Issue by mwchase** [rust-lang/rust#43431]
Encountered doing ill-advised type manipulations in the playground. By (mis)using some combination of universal function call syntax, the Fn trait, and other language features, I got an internal compiler error. I then simplified it to the point where it wouldn't make sense even if it didn't hit the error.

Code to reproduce the error:
```
trait CallSingle<A, B> {
    fn call(&self, a: A) -> B where Self: Fn(A) -> B;
}

impl<A, B, F: Fn(A) -> B> CallSingle<A, B> for F {
    fn call(&self, a: A) -> B {
        <Self as Fn(A) -> B>::call
    }
}
```

I'm not sure there should be any error it emits beyond what it already does, but this does panic the compiler: `error: internal compiler error: /checkout/src/librustc_typeck/check/mod.rs:4419: impossible case reached`

**Comment by estebank** [comment]
[This match arm is reached](https://github.com/rust-lang/rust/blob/b5e8a8ef97abef8a69a9c72de74fed779b401d73/src/librustc_typeck/check/mod.rs#L4547).

**Comment by petrochenkov** [comment]
I have a fix in progress (accidentally), will submit this weekend.

**Comment by petrochenkov** [comment]
https://github.com/rust-lang/rust/pull/43532 fixes the ICE, but the code still doesn't compile.
For some reason associated type bindings are prohibited in UFCS-style paths
```rust
<Type as Trait<T = u8 /* <-- can't do this */>>::AssocItem
```
and `B` in `Fn(A) -> B` is exactly an associated type binding
```rust
<Self as Fn(A) -> B>::call
// Desugars to
<Self as Fn<(A,), Output = B>>::call
```

**Comment by petrochenkov** [comment]
Current output:
```rust
#![feature(fn_traits)]

trait CallSingle<A, B> {
    fn call(&self, a: A) -> B where Self: Fn(A) -> B;
}

impl<A, B, F: Fn(A) -> B> CallSingle<A, B> for F {
    fn call(&self, a: A) -> B {
        <Self as Fn(A) -> B>::call(self, (a,))
    }
}

fn main() {}

---

   Compiling playground v0.0.1 (file:///playground)
error[E0229]: associated type bindings are not allowed here
 --> src/main.rs:9:27
  |
9 |         <Self as Fn(A) -> B>::call(self, (a,))
  |                           ^ associated type not allowed here

error: aborting due to previous error
```

I'm closing this because the ICE is fixed and supporting type bindings in value paths (`let x = Trait<AssocTy = u8>::method();`) is a separate problem, please open a new lang-team issue if you are interested in supporting it.
