### ISSUE TITLE
std::thread::spawn documentation: Incorrect grammar

### ISSUE THREAD

**Issue by joshlf** [rust-lang/rust#43435]
The documentation for [`std::thread::spawn`](https://doc.rust-lang.org/std/thread/fn.spawn.html) contains the following sentence:

> As a reminder, the Send marker trait, expresses that it is safe to be passed from thread to thread.

The second comma is grammatically incorrect; the sentence should read:

> As a reminder, the Send marker trait expresses that it is safe to be passed from thread to thread.

**Comment by steveklabnik** [comment]
Yup, sounds good! Someone who wants to fix this would modify https://github.com/rust-lang/rust/blob/b2c0707872082c890f332178f59fd02eea5b98f3/src/libstd/thread/mod.rs#L416

**Comment by joshlf** [comment]
I'm happy to do the PR myself, but I'm also happy to leave it as somebody's first PR.

**Comment by steveklabnik** [comment]
Either way is fine by me! 👍
