### ISSUE TITLE
No error explanation when calling a private method in another module

### ISSUE THREAD

**Issue by ElGoreLoco** [rust-lang/rust#43440]
When you don't make public a method and use it in another module, the program won't compile but `rustc` and `cargo` won't give you any error explanation.

I tried the code in [this gist](https://gist.github.com/ElGoreLoco/08c7e1195b5dfba665be672ffd31431f) (src_ means it is in the `src` subdirectory)

`rustc src/main.rs` doesn't print anything and `cargo run --verbose` prints this:
```
   Compiling tmprs v0.1.0 (file:///home/jorge/tmp/tmprs)
     Running `rustc --crate-name tmprs src/main.rs --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=7e13e15d92254a34 -C extra-filename=-7e13e15d92254a34 --out-dir /home/jorge/tmp/tmprs/target/debug/deps -L dependency=/home/jorge/tmp/tmprs/target/debug/deps`
error: Could not compile `tmprs`.

Caused by:
  process didn't exit successfully: `rustc --crate-name tmprs src/main.rs --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=7e13e15d92254a34 -C extra-filename=-7e13e15d92254a34 --out-dir /home/jorge/tmp/tmprs/target/debug/deps -L dependency=/home/jorge/tmp/tmprs/target/debug/deps` (exit code: 1)
```

## Meta

`rustc --version --verbose`:
rustc 1.19.0 (0ade33941 2017-07-17)
binary: rustc
commit-hash: 0ade339411587887bf01bcfa2e9ae4414c8900d4
commit-date: 2017-07-17
host: x86_64-unknown-linux-gnu
release: 1.19.0
LLVM version: 4.0

**Comment by durka** [comment]
I cannot reproduce with latest nightly (afe145d22 2017-07-23) on OSX.

```
$ rustc src/main.rs
error: method `new` is private
 --> src/main.rs:4:22
  |
4 |     println!("{:?}", test::Test::new(String::from("test")));
  |                      ^^^^^^^^^^^^^^^

error: aborting due to previous error
```

**Comment by Mark-Simulacrum** [comment]
I'm going to close for now, but let us know if you can still reproduce on nightly; we'll reopen.

**Comment by ElGoreLoco** [comment]
Nightly shows the correct error. Next time I will use nightly right away.
