### ISSUE TITLE
Implement From<(u8, u8, u8, u8)> for IpAddr

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#43460]
This works:

    let x: std::net::IpAddr = [0,0,0,0].into();

This should work too:

    let x: std::net::IpAddr = (0,0,0,0).into();

**Comment by alexcrichton** [comment]
The libs team [has decided](https://github.com/rust-lang/rust/pull/43464#issuecomment-319510655) to not accept this feature into libstd.
