### ISSUE TITLE
std::sync::Once: Should Once be UnwindSafe or RefUnwindSafe?

### ISSUE THREAD

**Issue by joshlf** [rust-lang/rust#43469]
Currently, the following program [will not compile](https://play.rust-lang.org/?gist=b2be5c6728418ded9d6a559c780779b7&version=stable) because `Once` isn't `RefUnwindSafe`. Is this the desired behavior, or should we consider making it `RefUnwindSafe` or `UnwindSafe`?

```rust
use std::sync::Once;
use std::panic::catch_unwind;

fn main() {
    let o = Once::new();
    catch_unwind(|| o.call_once(|| panic!("foo")));
}
```

**Comment by alexcrichton** [comment]
It also won't compile because `call_once` [requires `'static self`](https://doc.rust-lang.org/std/sync/struct.Once.html#method.call_once)?

**Comment by joshlf** [comment]
Ah, right you are. [This works](https://play.rust-lang.org/?gist=09cb588aabf7f0fbfa3c0d2463eab74e&version=nightly):

```rust
use std::sync::Once;
use std::panic::catch_unwind;

static o: Once = Once::new();

fn main() {
    catch_unwind(|| o.call_once(|| panic!("foo")));
}
```

**Comment by Milo123459** [comment]
@rustbot claim

Going to take a stab at this one.
