### ISSUE TITLE
Associated type bound isn't always present for checking

### ISSUE THREAD

**Issue by Twey** [rust-lang/rust#43475]
Trait bounds on associated types seem to be *required*, not *implied*, when the trait in question mentions an associated type on a type parameter.

Concretely, this code (or [playground](https://play.rust-lang.org/?gist=852e99562fe96381dd9ff14635081e0e&version=stable)) produces an error:
```
trait Foo { type FooT: Foo; }
impl Foo for () { type FooT = (); }
trait Bar<T: Foo> { type BarT: Bar<T::FooT>; }
impl Bar<()> for () { type BarT = (); }

fn test<C: Bar<()>>() { }
```

```
error[E0277]: the trait bound `<C as Bar<()>>::BarT: Bar<()>` is not satisfied
 --> src/main.rs:6:1
  |
6 | fn test<C: Bar<()>>() { }
  | ^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Bar<()>` is not implemented for `<C as Bar<()>>::BarT`
  |
  = help: consider adding a `where <C as Bar<()>>::BarT: Bar<()>` bound
  = note: required by `Bar`
```
despite the `C::BarT: Bar<()>` bound being required by the definition of `Bar` itself, and in fact this means that the trait `Bar<T>` can never be mentioned.

This similar example ([playground](https://play.rust-lang.org/?gist=c70e905d4f3aa5d038dda6c0ea5a33fa&version=stable)) that doesn't use an associated type in the trait parameter compiles:
```
trait Foo { type FooT: Foo; }
impl Foo for () { type FooT = (); }
trait Bar<T: Foo> { type BarT: Bar<T>; }
impl Bar<()> for () { type BarT = (); }

fn test<C: Bar<()>>() { }
```

while this version ([playground](https://play.rust-lang.org/?gist=74b0aacc13661da235b55185f17c2f55&version=stable)), which uses a third trait to avoid the self-reference, does not:
```
trait Foo { type FooT: Foo; }
impl Foo for () { type FooT = (); }
trait Bar<T: Foo> { type BarT: Baz<T::FooT>; }
impl Bar<()> for () { type BarT = (); }
trait Baz<T: Foo> { }
impl Baz<()> for () { }

fn test<C: Bar<()>>() { }
```

Is this just a missing normalization step?

**Comment by Marwes** [comment]
Pretty sure I encountered the same bug when specifying an associated type explicitly in a signature.

```rust

pub trait Param<P> {
    fn param(p: P) -> Self;
}

pub trait Test: Sized {
    type T: Param<Self::Item>;
    type Item;
}

// Compiles
fn test<T: Test>(p: T::Item) -> T::T {
    T::T::param(p)
}

// Does not compile
fn test2<T: Test<Item = u8>>(p: T::Item) -> T::T {
    T::T::param(p)
}

fn main() {
}
```

https://play.rust-lang.org/?gist=20c9d87e34aecc76754bc687734e00c5&version=nightly

**Comment by rkarp** [comment]
I've just run into this as well, it seems. Here's a very simple example:
```rust
trait Foo {
    type Item;
    type FnOfItem: Fn(Self::Item);
}

fn test<T>()
where
    T: Foo<Item = usize>,
    //T::FnOfItem: Fn(T::Item), // <-- Compile error without this
{}

fn main() {}
```
https://play.rust-lang.org/?gist=add5141b26dc781bd27c5b09c8c14f2d&version=nightly
