### ISSUE TITLE
Poor error message for type definitions in `extern` blocks

### ISSUE THREAD

**Issue by jimblandy** [rust-lang/rust#43495]
Although work on [RFC 1861][1] for extern types has begun in issue #43467, it's not complete, and in the mean time, Rust gives very strange messages if one accidentally includes a type in an `extern` block. For example:
```
use std::ffi::CString;
use std::os::raw::c_char;

extern {
    fn strlen(s: *const c_char) -> usize;
    pub struct S(c_char); 
}

fn main() {
    println!("{}", unsafe { strlen(CString::new("foo").unwrap().as_ptr()) });
}
```
On nightly, this elicits the following message:
```
   Compiling playground v0.0.1 (file:///playground)
error: unmatched visibility `pub`
 --> src/main.rs:7:5
  |
7 |     pub struct S(c_char); 
  |     ^^^
```
A reader of our book came across this error message by accident and asked me about it. We were both mystified.

[1]: https://github.com/rust-lang/rfcs/pull/1861

**Comment by jimblandy** [comment]
Possibly related to issue #40599.

Perhaps this is deliberate, as the [parse-fail/duplicate-visibility.rs test][1] expects it. But I still think it's unclear.

[1]: https://github.com/rust-lang/rust/blob/2fc3aec4316a76429a5a0c8d2eccb19bf81982d6/src/test/parse-fail/duplicate-visibility.rs#L13-L16

**Comment by steveklabnik** [comment]
Triage: this error message got weirder:

```
error: expected one of `(`, `fn`, `static`, or `type`, found keyword `struct`
 --> src/main.rs:6:9
  |
6 |     pub struct S(c_char); 
  |         ^^^^^^ expected one of `(`, `fn`, `static`, or `type` here

```

**Comment by Centril** [comment]
We now recognize this as a struct and emit a good error:
```
error: struct is not supported in `extern` blocks
 --> src/main.rs:6:5
  |
6 |     pub struct S(c_char); 
  |     ^^^^^^^^^^^^^^^^^^^^^
```
