### ISSUE TITLE
erroneous behavior with #[cfg]

### ISSUE THREAD

**Issue by joshlf** [rust-lang/rust#43494]
The [following code](https://play.rust-lang.org/?gist=ea56ff73d5f43673d711772825fcac1c&version=stable) results in a parsing error where the `0` character is unexpected.

```rust
fn get_usize() -> usize {
        #[cfg(not(debug_assertions))]
        0
        
        #[cfg(debug_assertions)]
        1
}
```

However, the following code works fine:

```rust
fn get_usize_return() -> usize {
        #[cfg(not(debug_assertions))]
        return 0;
        
        #[cfg(debug_assertions)]
        1
}
```

I think this is a bug in the parser?

**Comment by sinkuu** [comment]
Duplication of #38337.

**Comment by Mark-Simulacrum** [comment]
Yes, closing.
