### ISSUE TITLE
`Self` treated differently than named type in trait bounds

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rust#43502]
Example:
```rust
trait Bar {}

// Allowed
trait Foo where Box<Self>: Bar {}

// Error: the trait bound `Box<Foo2 + 'static>: Bar` is not satisfied
trait Foo2 where Box<Foo2>: Bar {}
```
[Playground link](https://play.rust-lang.org/?gist=d952286ccaf066f820a929d0e409739d&version=stable)

I'm not sure if this is intentional, but it certainly *seems* wrong.

**Comment by petrochenkov** [comment]
`Self` in a trait doesn't refer to the trait, but to the type for which the trait is implemented (which is an implicit type parameter of the trait).
Imagine what would happened if `Self` resolved to a trait in this example:
```rust
trait Clone {
    fn clone(&self) -> Self; // The method returns a trait object `Clone`?!
}
```

**Comment by cramertj** [comment]
Ah, of course. Thanks @petrochenkov .
