### ISSUE TITLE
Match complains about multiple mutable borrow when giving a catch-all case a name

### ISSUE THREAD

**Issue by jdm** [rust-lang/rust#43508]
Consider this program which compiles without any errors:
```rust
struct S {
    s: String,
}

impl S {
    fn next(&mut self) -> &str {
        self.s.push('a');
        &self.s
    }
}

fn main() {
    let mut s = S { s: "".to_owned() };
    match s.next() {
        "foo" => s.next(),
        _ => "hi"
    };
}
```

However, if we replace the `_` with `_s`, we get the following error:
```
error[E0499]: cannot borrow `s` as mutable more than once at a time
  --> src/main.rs:15:18
   |
14 |     match s.next() {
   |           - first mutable borrow occurs here
15 |         "foo" => s.next(),
   |                  ^ second mutable borrow occurs here
16 |         _s => "hi"
17 |     };
   |     - first borrow ends here
```

I find this behaviour very surprising.

**Comment by nikomatsakis** [comment]
This is a combination of `_` meaning "ignore" (whereas `_s` makes a binding, and hence extends the lifetime of the borrow) with non-lexical lifetimes. I'm inclined to close as "working as designed" (for now).

**Comment by nikomatsakis** [comment]
(Feel free to re-open...)

**Comment by jdm** [comment]
So to sum up:
* the literal value "foo" is matched, and then the borrowed value is not bound when we enter the first match arm, meaning that there is no borrow conflict
* when we ignore the matched value in the remaining arm with `_`, the borrowed value is not bound when we enter the match arm so there is no borrow conflict
* when we name the matched value instead, the borrowed value is bound, and therefore the borrow is extended into all of the match arms, not just the one that was changed, due to lexical borrow rules. This means that there is now a borrow conflict.

Am I correct?

**Comment by nikomatsakis** [comment]
@jdm correct
