### ISSUE TITLE
Extend the "nullable pointer optimization" to two different size variants

### ISSUE THREAD

**Issue by ordian** [rust-lang/rust#43507]
[Play](https://play.rust-lang.org/?gist=2c9085934e112a66fc0583e681493bf0&version=nightly?):

```rust
#[allow(dead_code)]
enum StrOrChar<'a> {
    Str(&'a str),
    Char(char),
}

fn main() {
    println!("{}", std::mem::size_of::<&str>());
    println!("{}", std::mem::size_of::<Option<&str>>()); // current optimization
    println!("{}", std::mem::size_of::<StrOrChar>());   // proposed optimization
}
```

currently prints (on x86_64) 16, 16 and 24. But it could potentially be 16, 16 and 16. 

This optimization should be possible if we have an enum with two variants `a` and `b`, the `a` variant contains non-nullable field and the size of a is greater than the size of b (probably size of b should be a divisor of size of a or 0 for alignment). 

The current ["nullable pointer optimization"](https://doc.rust-lang.org/nightly/book/first-edition/ffi.html#the-nullable-pointer-optimization) is  a special case with size of b equal to 0.

[src link](https://github.com/rust-lang/rust/blob/master/src/librustc/ty/layout.rs#L1359)

**Comment by oli-obk** [comment]
So basically the char would just occupy the same memory as the length field of the slice? I think the example should use a `u32`, because a `char` enables so many other optimizations it could cause confusion.

Also I think this needs an RFC. Also note the related RFC issue: https://github.com/rust-lang/rfcs/issues/1230

**Comment by ordian** [comment]
> So basically the char would just occupy the same memory as the length field of the slice? I think the example should use a u32, because a char enables so many other optimizations it could cause confusion.

Right.
> Also note the related RFC issue: rust-lang/rfcs#1230

Thanks for the link. Should I close this issue in favor of rust-lang/rfcs#1230? This optimization was mentioned in the [comment](https://github.com/rust-lang/rfcs/issues/1230#issuecomment-312686238).

**Comment by Mark-Simulacrum** [comment]
Yes, I think this is best tracked there -- we need an RFC to make changes in this area, I believe.
