### ISSUE TITLE
Trying to read directory with BufReader::lines while filtering errors consumes 100% CPU

### ISSUE THREAD

**Issue by mkpankov** [rust-lang/rust#43504]
If we `File::open()` a directory, then wrap it in `BufReader`, call `lines()` and then `filter_map()` only successful reads, the programs never finishes:

```rust
use std::fs::File;
use std::io::{BufRead, BufReader};

fn main() {
    let file = File::open(".").unwrap();
    let reader = BufReader::new(file);
    let lines = reader.lines();
    // Comment to make it output infinite errors
    let lines = lines.filter_map(|s| s.ok());
    for line in lines {
        println!("Line: {:?}", line);
    }
    println!("Finished");
}
```

"Finished" is never printed. No "Line: ..." lines are printed. Instead 100% CPU is consumed.

Commenting the `filter_map()` line makes it output infinite `Line: Err(Error { repr: Os { code: 21, message: "Is a directory" } })`.

https://play.rust-lang.org/?gist=f6f0fdbcc83b9630b493c025e3432d31&version=stable

Looks similar to #34703, but not sure it's because of same reasons.

Not sure what would a proper fix would be, but I think I'd prefer `lines()` to output a single item with error instead of spamming it.

**Comment by TimNN** [comment]
That behaviour is expected, as far as I can tell:

* Opening the directory is fine
* Whenever you attempt to read from the opened directory (here: whenever you attempt to read a line), the OS returns an error (as expected)
* You ignore the produced errors (`.filter_map`, `.ok()`)

Thus the only thing this program does, is ignoring errors as fast as the OS can produce them, leading to 100% CPU consumption.

**Comment by arielb1** [comment]
This is the expected behavior of `filter_map`. It keeps on trying (to read from the directory) until it would succeed (aka never). You might want to use `.take_while(|x| x.is_ok()).map(|x| x.unwrap())`, or just a for-loop, to stop after the first error.
