### ISSUE TITLE
stage0 libstd fails to build when jemalloc is disabled

### ISSUE THREAD

**Issue by cuviper** [rust-lang/rust#43510]
Since #43320 bumped the bootstrap compiler, stage0 libstd fails to build when jemalloc is disabled:

```text
error[E0463]: can't find crate for `alloc_jemalloc`

error: aborting due to previous error

error: Could not compile `std`.
```

I believe it needs to restore the logic removed here:
https://github.com/rust-lang/rust/pull/42727/files#diff-242481015141f373dcb178e93cffa850L236

I tried to add this to `libstd/lib.rs`:

```rust
// Always use alloc_system during stage0 since we don't know if the alloc_*
// crate the stage0 compiler will pick by default is available (most
// obviously, if the user has disabled jemalloc in `./configure`).
#![cfg_attr(any(stage0, feature = "force_alloc_system"), feature(global_allocator))]
#![cfg(any(stage0, feature = "force_alloc_system"))]
#[global_allocator]
static ALLOC: alloc_system::System = alloc_system::System;
```

Then stage0 passed, but stage1 std failed like:

```text
error[E0463]: can't find crate for `std`

error: aborting due to previous error

error: Could not compile `std`.
```

😕

**Comment by Mark-Simulacrum** [comment]
cc @alexcrichton

**Comment by alexcrichton** [comment]
We should probably add a builder for this...

**Comment by cuviper** [comment]
or just get on with evicting jemalloc... 😉

**Comment by aidanhs** [comment]
`force_alloc_system` is not the right way to fix this - I added that so I could build rust with a local rust that does not have jemalloc (i.e. if you're not using a local rust, or if your local rust has jemalloc, it's irrelevant).

**Comment by aidanhs** [comment]
Interesting, I kinda figured I was the only one! Rereading #39086, I see I'm wrong about my two conditions above - it actually applies when trying to build something without jemalloc, from something that defaults to it.

Anyway, it should all be fixed soonish...
