### ISSUE TITLE
25% regression in compile time of issue-20936-deep-vector benchmark

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#43511]
[According to perf.rust-lang.org](https://perf.rust-lang.org/graphs.html?start=2017-06-15T00%3A00%3A00%2B00%3A00&end=2017-06-22T00%3A00%3A00%2B00%3A00&crates=%7B%22list%22%3A%22List%22%2C%22content%22%3A%5B%22issue-20936-deep-vector%22%5D%7D&phases=%7B%22list%22%3A%22All%22%2C%22content%22%3Anull%7D&group_by=crate&type=time&yaxis=pct) this benchmarked experienced a >25% regressoin in compile time due to https://github.com/rust-lang/rust/pull/39409

Seems bad!

cc @pnkfelix, @rust-lang/compiler

**Comment by nikomatsakis** [comment]
triage: P-medium

We got a lot of stuff on our plate, and lacking evidence that this regression is more widespread, we'll consider this p-medium for now. The cause is certainly that EndRegion added a bunch of MIR statements. We can perhaps fix by adding some filtering?

**Comment by alexcrichton** [comment]
Looking at some data again, it's worth nothing that #39409 [regressed almost all benchmarks](https://perf.rust-lang.org/graphs.html?start=2017-06-18T00%3A00%3A00%2B00%3A00&end=2017-06-21T00%3A00%3A00%2B00%3A00&crates=%7B%22list%22%3A%22All%22%2C%22content%22%3Anull%7D&phases=%7B%22list%22%3A%22All%22%2C%22content%22%3Anull%7D&group_by=crate&type=time&yaxis=pct), much more so than https://github.com/rust-lang/rust/issues/42808 which is also perceived as a relatively high-priority regression.

**Comment by alexcrichton** [comment]
FWIW the [perf graph](https://perf.rust-lang.org/graphs.html?start=2017-06-12T00%3A00%3A00%2B00%3A00&end=2017-09-04T00%3A00%3A00%2B00%3A00&crates=%7B%22list%22%3A%22List%22%2C%22content%22%3A%5B%22issue-20936-deep-vector%22%5D%7D&phases=%7B%22list%22%3A%22All%22%2C%22content%22%3Anull%7D&group_by=crate&type=time&yaxis=pct) here shows that we recovered almost all of the performance here, but there's still a 10% regression from before #39409. @arielb1 do you think it's worth opening another issue for that?
