### ISSUE TITLE
Save-analysis data should indicate whether an item is visible from the crate root

### ISSUE THREAD

**Issue by euclio** [rust-lang/rust#43521]
This is needed for tools like the new rustdoc prototype at steveklabnik/rustdoc, where it's required to only document items that can be used by the library consumer.

This should also take `pub use` into account.

cc https://github.com/nrc/rls-analysis/issues/79

**Comment by nrc** [comment]
cc me

To be clear, I think we should be able to *filter* data based on whether it is visible, I don't think save-analysis needs to contain that info.

**Comment by euclio** [comment]
@nrc

I've started working on this. I wonder if you can offer any advice around how to correctly handle `pub use`. I'm thinking something along the lines of: on encountering a `pub use`, I should additionally see if the `use`d item is reachable. If it is, dump the item even if it's not reachable.
