### ISSUE TITLE
rustdoc: unions and consts are not color-coded

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/rust#43523]
All the various kinds of item in rust are given a color in rustdoc's CSS, but consts and unions never got one. Fixing should just be a matter of collecting the class name that these items use, and adding a couple rules to rustdoc.css to apply some color to them. The question of *which* color is another matter entirely. `>_>`

**Comment by GuillaumeGomez** [comment]
I'll propose something out. :)
