### ISSUE TITLE
unused_mut lint doesn't cover every case

### ISSUE THREAD

**Issue by CryZe** [rust-lang/rust#43526]
```rust
fn main() {
    let mut x = &mut 5;
    *x = 4;
    println!("{}", x);
}
```
[Playground](https://play.rust-lang.org/?gist=d96ae9e92905c57405485b7251d2a9f4&version=stable)

This does not print a warning that x doesn't need to be mutable, even though the binding never changes.

**Comment by oli-obk** [comment]
Isn't that essentially the same as https://github.com/rust-lang/rust/issues/25049 ?
