### ISSUE TITLE
Fast isel dislikes switch, which pattern matching can generate

### ISSUE THREAD

**Issue by pcwalton** [rust-lang/rust#4353]
We should use the compare mode otherwise.

**Comment by steveklabnik** [comment]
Today, compiling with `rustc -O --emit=llvm-ir hello.rs`, I get

```
define i64 @main(i64, i8**) unnamed_addr #1 {
top:
  %2 = tail call i64 @_ZN2rt10lang_start20he050f8de3bcc02b7VRIE(i8* bitcast (void ()* @_ZN4main20h04abfe0370f26946eaaE to i8*), i64 %0, i8** %1)
  ret i64 %2
}

```

No more `case`. Is this resolved, or does some other code still generate poorly?

**Comment by huonw** [comment]
I think fast isel is only ever attempted to be used when optimisations are off. Using fast isel makes compilation faster and so we want to ensure we're using with `opt-level=0` as much as possible. I don't how one can detect if fast isel is being used by LLVM.

**Comment by steveklabnik** [comment]
Ah, gotcha, that makes sense. Given that it's an optimization, I assumed that it would be with optimizations on. :)

**Comment by jonas-schievink** [comment]
FastISel still dislikes `switch`, and the MIR translator generates it as well. Fixing this with MIR is much easier, we could replace unneeded `SwitchInt`s in the SimplifyCfg pass or write another pass for this.

(you can check for FastISel by running the LLVM IR through `llc -O0 -fast-isel -fast-isel-abort 1 test.ll` - preferrably using the `llc` compiled from Rust's LLVM submodule, which is located in `./x86_64-unknown-linux-gnu/llvm/Release/bin/llc`)

**Comment by arielb1** [comment]
@jonas-schievink 

We may want to do this in the lowering for `SwitchInt`.

**Comment by nagisa** [comment]
This ticket is still useful. That being said, benefits of fixing this are comparatively minor and there are bigger fish to catch.

**Comment by scottmcm** [comment]
I think this needs a new repro, as the one above appears to have been fixed by https://github.com/rust-lang/rust/pull/51323: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=5a29683164b1399f1a2418dd9f6718ee

As an attempt, the following does generate a `switch`:
```rust
pub fn foo(c: i32) -> i32 {
    match c {
        0 => 1,
        1 => 7,
        _ => 2,
    }
}
```

How were you thinking of fixing this?  Should there be a opt-level-zero-only MIR ~~optimiz~~transformation to replace multi-way `switchInt`s with two-way ones and extra blocks?  Or did you want it to happen in codegen?

**Comment by workingjubilee** [comment]
Closing per the same judgement as this sibling issue: https://github.com/rust-lang/rust/issues/26600#issuecomment-1059263429
