### ISSUE TITLE
cell::BorrowRef can overflow borrow counter into WRITING

### ISSUE THREAD

**Issue by H2CO3** [rust-lang/rust#43557]
From https://doc.rust-lang.org/src/core/cell.rs.html#860-872:

```rust
impl<'b> Clone for BorrowRef<'b> {
    #[inline]
    fn clone(&self) -> BorrowRef<'b> {
        // Since this Ref exists, we know the borrow flag
        // is not set to WRITING.
        let borrow = self.borrow.get();
        debug_assert!(borrow != UNUSED);
        // Prevent the borrow counter from overflowing.
        assert!(borrow != WRITING);
        self.borrow.set(borrow + 1);
        BorrowRef { borrow: self.borrow }
    }
}
```

When the `borrow` counter equals `WRITING - 1`, i.e. `~0usize - 1`, then it will end up in the `WRITING` state after incrementing it.

Proposed resolution:

```rust
assert!(borrow != WRITING - 1 && borrow != WRITING)
```
The same issue is present in `BorrowRef::new()` (https://doc.rust-lang.org/src/core/cell.rs.html#839-848):

```rust
impl<'b> BorrowRef<'b> {
    #[inline]
    fn new(borrow: &'b Cell<BorrowFlag>) -> Option<BorrowRef<'b>> {
        match borrow.get() {
            WRITING => None,
            b => {
                borrow.set(b + 1);
                Some(BorrowRef { borrow: borrow })
            },
        }
    }
}
```

Here, matching `WRITING - 1` could either explicitly `panic!()` or return `None` (the former being preferred, as `None` is already being used for indicating an outstanding mutable loan).

**Comment by H2CO3** [comment]
(Just for clarity, I do realize that `BorrowRef::drop()` checks for `borrow != WRITING`, although I think it would be more robust, informative, and appropriate to detect and explicitly handle the error at the point of its inception rather than deferring it until a quite arbitrary point in time, namely the end of the borrow's lifetime.)

**Comment by Mark-Simulacrum** [comment]
AFAICT the current implementation of new checks appropriately for overflow and doesn't increment so I'm going to close this.
