### ISSUE TITLE
getFeatureTable() doesn't exist in LLVM 4.x

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/rust#43555]
Blame: https://github.com/rust-lang/rust/commit/c4710203c098b68b5f80b1507e889ad894855729
Arch Linux, LLVM 4.0.1-5 (using system llvm shared)

```
cargo:warning=../rustllvm/PassWrapper.cpp: In function ‘bool LLVMRustHasFeature(LLVMTargetMachineRef, const char*)’:
cargo:warning=../rustllvm/PassWrapper.cpp:185:58: error: ‘const class llvm::MCSubtargetInfo’ has no member named ‘getFeatureTable’; did you mean ‘getFeatureBits’?
cargo:warning=   const ArrayRef<SubtargetFeatureKV> FeatTable = MCInfo->getFeatureTable();
cargo:warning=                                                          ^~~~~~~~~~~~~~~
cargo:warning=                                                          getFeatureBits
```

**Comment by TimNN** [comment]
The problem is likely that `getFeatureTable()` is provided by a custom path to the rust LLVM fork: https://github.com/rust-lang/llvm/commit/68e1e29618b2bd094d82faac16cf8e89959bbd68

**Comment by alexcrichton** [comment]
cc @lu-zero, mind taking a look here?

**Comment by lu-zero** [comment]
Sure, I misread the guards somehow and now I'm much sleepier so I guess I'll send PR with the correct guard in ~10 hours from now.
