### ISSUE TITLE
Add IRC's `!union union` as a test

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#43553]
The factoid `union union` has playbot run this code: `#![allow(bad_style)] union union<'union> { union: &'union union<'union>, }`. It should be added as a test in `src/test/run-pass/wierd-exprs.rs`.

**Comment by Havvy** [comment]
Requesting tag for "E-Easy" and whatever the good first bug one is if it's not E-Easy.

**Comment by kennytm** [comment]
I wonder if we will get similar tests for `default` and `catch`...

**Comment by arshiamufti** [comment]
I'm going to work on this with @steveklabnik 🎉

**Comment by tamird** [comment]
Fixed in #43752. @steveklabnik @sfackler?
