### ISSUE TITLE
Lint for bool-valued if conditional

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rust#43569]
I think we should have a lint for conditionals like `if cond { true } else { false }`, and conversely `if cond { false } else { true }`; the lint should suggest changing those to `cond` and `!cond`, respectively.

**Comment by kennytm** [comment]
This is the clippy lint [`needless_bool`](https://github.com/rust-lang-nursery/rust-clippy/wiki#needless_bool). Why this should be moved into rustc?

**Comment by joshtriplett** [comment]
@kennytm Good to know; I wasn't aware of that.

This came up in the context of another issue, and the sample code provided for that issue. I do think it makes sense for this lint to exist *somewhere*, and I'm glad to hear that it exists in clippy. I'd love to see it in rustc so that it's available by default, but if that's not desirable for some reason, fair enough.

**Comment by nagisa** [comment]
Generally our policy wrt lints is that they need an RFC, so closing.
