### ISSUE TITLE
Rustdoc responsive design makes suboptimal tradeoffs, especially on tall windows

### ISSUE THREAD

**Issue by the8472** [rust-lang/rust#43571]
When displaying IDE and a browser showing rustdocs side by side I can easily end up with a 800x1400 viewport. At that resolution the sidebar takes up a large fraction of the space, forcing unnecessary linebreaks.

At lower widths (<700px) media queries use a different layout without the sidebar, but that also has problems. For one it hides the `[-]` toggle on the top right which I like to use to get a more compact overview due to the lack of method indexes (#40273). Secondly, it mostly removes the sidebar's content. With enough vertical screen estate it might make more sense to just move it to the top or bottom.

![viewport](https://user-images.githubusercontent.com/1065730/28788165-a4cad082-761f-11e7-9862-74d373e24aae.png)

**Comment by GuillaumeGomez** [comment]
The UI has been greatly reworked, preventing this issue from happening anymore. I'm closing it but if you still have some issues around the "responsiveness", please reopen it.
