### ISSUE TITLE
6x slower compilation for "simple" file than C

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#43578]
In attempting to find some local hot spots in rustc I've been playing around with various benchmarks. If you use this script to generate a Rust and a C file (which should be equivalent)

```sh
N=200000

echo > lots-of-used.rs
for i in `seq 1 $N`; do
  echo "pub fn foo$i() {}" >> lots-of-used.rs
done
echo 'fn main() {' >> lots-of-used.rs
for i in `seq 1 $N`; do
  echo "foo$i();" >> lots-of-used.rs
done
echo '}' >> lots-of-used.rs

echo > lots-of-used.c
for i in `seq 1 $N`; do
  echo "static void foo$i() {}" >> lots-of-used.c
done
echo 'void foo() {' >> lots-of-used.c
for i in `seq 1 $N`; do
  echo "foo$i();" >> lots-of-used.c
done
echo '}' >> lots-of-used.c
```

I've benchmarked with:

```sh
$ rustc +beta -V
rustc 1.20.0-beta.1 (e93aa3aa8 2017-07-18)
$ sh foo.sh
$ time clang -c lots-of-used.c
clang -c lots-of-used.c  14.90s user 0.36s system 99% cpu 15.259 total
$ time rustc +beta lots-of-used.rs --emit obj --crate-type rlib
rustc +beta lots-of-used.rs --emit obj --crate-type rlib  49.62s user 37.03s system 99% cpu 1:26.96 total
```

The [`-Z time-passes` output](https://gist.github.com/alexcrichton/f59345928020c7b06b00bb43c3bf4bf1) is particularly illuminating, the highest portions being:

```
time: 57.439; rss: 2890MB translation
  time: 51.813; rss: 2497MB translation item collection
time: 10.094; rss: 534MB LLVM passes
  time: 9.238; rss: 536MB       codegen passes [1]
time: 5.100; rss: 2405MB borrow checking
time: 4.029; rss: 1656MB        item-bodies checking
time: 2.166; rss: 1781MB const checking
time: 1.543; rss: 1069MB wf checking
``` 

![https://i.imgur.com/IRBwT69.png](https://i.imgur.com/IRBwT69.png)

It looks like the main slowdown of the the translation item collection is related to the `ElaborateDrops` pass?

**Comment by alexcrichton** [comment]
I fixed an "obvious omission" in https://github.com/rust-lang/rust/pull/43581 but I'm not sure why we're creating such massive bit sets in the first place

**Comment by alexcrichton** [comment]
This also peaks at using 32GB (!) of memory, a [massif dump here](https://gist.github.com/alexcrichton/f7c9b040b82edb884bec83e4e4607315), the peak of which [looks like this](https://gist.github.com/8343b5dcffd66bdcf4e0714d0e125be2)

**Comment by michaelwoerister** [comment]
cc @arielb1 because of ElaborateDrops.

Oh interesting, optimizing MIR now shows up as part of item collection because of on-demand.

**Comment by Mark-Simulacrum** [comment]
Nightly rustc takes 16 seconds, vs. 12 seconds with clang-14. Looking over a profile I don't see any clear hot spots where we're doing obviously wasted/unnecessary work, so I think we can probably close this as no longer an interesting case study.
