### ISSUE TITLE
f32/f64 MIN_EXP is either wrong or badly documented.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#43583]
They are both `-MAX_EXP + 3` while `core::num::dec2flt::RawFloat` uses `-MAX_EXP + 1`.
Also, APFloat (being ported to Rust in #43554) uses the same `-MAX_EXP + 1` value.
That is the value of the exponent for the smallest normal, AFAIK.

cc @rust-lang/libs @est31 @nagisa @lifthrasiir @rkruppe

**Comment by rkruppe** [comment]
I chased the blame chain and apparently `-MAX_EXP + 3` matches, and [historically stems from](https://github.com/rust-lang/rust/blob/494ad4e601834f1b28e58c1c0ba579c2972c9a27/src/etc/cmathconsts.c) C's (or at least GCC's) `FLT_MIN_EXP` 🤔

**Comment by kennytm** [comment]
MIN_EXP is "*One greater than the minimum possible normal power of 2 exponent*". For f64, the smallest normal number is 2<sup>-1022</sup>, so MIN_EXP = -1022 + 1 = -1021 as expected.

I don't know why such a strange definition is picked, but this follows how ***_MIN_EXP is defined in C and [C++](http://en.cppreference.com/w/cpp/types/numeric_limits/min_exponent).

**Comment by eddyb** [comment]
@kennytm That doesn't add up. `APFloat` has 2<sup>MIN_EXP</sup> as the smallest normal number.
So 2<sup>-1023</sup> for `f64`, which would make `std::f64::MIN_EXP` -1022. What am I missing?

**Comment by rkruppe** [comment]
Uhh, the smallest normal f64 is indeed 2<sup>-1022</sup>, not 2^<sup>-1023</sup>.

**Comment by eddyb** [comment]
Oh, figured it out. `APFloat` `MIN_EXP` is indeed `-1022`. What I had in mind was that it was defined as `-MAX_EXP + 1` which *is true* but `MAX_EXP` *also* is off-by-one.
`rawfp` uses the same values as `APFloat`, so this is only some C nonsense. My bad.
