### ISSUE TITLE
Link jemalloc with C++ stdlib

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/rust#43586]
The new jemalloc is causing issue with dylib linking. It's missing one of the libstdc++ symbols.

```
/tmp/rustdoctest.FVvtw8VcGTYm/rust_out: symbol lookup error: /usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libstd-0fc58a047151a831.so: undefined symbol: __cxa_end_catch
```

C++ matters were added to jemalloc ["recently"](https://github.com/jemalloc/jemalloc/commit/2319152d9f5d9b33eebc36a50ccf4239f31c1ad9), but Rust haven't merged that yet. That's why it can be only reproduced on Arch, which uses system up-to-date jemalloc.

One of the effects: https://github.com/nix-rust/nix/issues/708

Some solutions I can think:
- link system jemalloc dynamically.
- link jemalloc with stdlib.
- building with the `--disable-cxx` flag. This however doesn't allow existing system library built with C++ extensions.

**Comment by alexcrichton** [comment]
Jemalloc is now removed from libstd by default in https://github.com/rust-lang/rust/pull/55238 so closing
