### ISSUE TITLE
error: internal compiler error: src/librustc_typeck/astconv.rs:1267: anonymous bound region BrAnon(1) in return but not args

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#43594]
```rust
extern "C" {
    pub fn ICE(node: &u8) -> &u8;
}
```

produces

```
error: internal compiler error: src/librustc_typeck/astconv.rs:1267: anonymous bound region BrAnon(1) in return but not args
 --> test.rs:3:30
  |
3 |     pub fn ICE(node: &u8) -> &u8;
  |                              ^^^

```

It goes away if you stop relying on elision and put an explicit lifetime there.

This breaks stylo. (We can't work around this, we use lifetimes in FFI for additional safety and we need elision because bindgen doesn't know enough to insert manual lifetimes)

cc @eddyb @nikomatsakis

**Comment by eddyb** [comment]
@Manishearth I thought we couldn't fix this without breaking some code (@nikomatsakis do you remember?). It was supposed to be unbound but I suppose `astconv` enforces soundness.

**Comment by Mark-Simulacrum** [comment]
I believe this is https://github.com/rust-lang/rust/issues/43567, closing.
