### ISSUE TITLE
calling libc::res_init from multiple threads is unsafe on at least OSX

### ISSUE THREAD

**Issue by oconnor663** [rust-lang/rust#43592]
We recently started calling `res_init` on DNS failure to fix a glibc bug, and there was [some worry](https://github.com/rust-lang/rust/pull/41582#issuecomment-315398074) that we might be calling a function that isn't threadsafe. It looked like we might not have any thread safety issues with glibc specifically, but now I'm convinced that we do have them in libc on OSX. I haven't repro'd the issue in Rust yet, but I'm able to produce very scary crashes with the following Go program if I run it on OSX (but not on Linux):

```go
package main

// #cgo LDFLAGS: -lresolv
// #include<sys/types.h>
// #include<netinet/in.h>
// #include<arpa/nameser.h>
// #include<resolv.h>
import "C"
import "fmt"

func main() {
	// Loop on res_init() in a background goroutine...
	go func() {
		for {
			fmt.Println("background res_init")
			C.res_init()
		}
	}()
	// ...and also loop on it in the main thread.
	for {
		fmt.Println("foreground res_init")
		C.res_init()
	}
}
```

The result is inconsistent, but here are a couple examples:

```
fatal error: unexpected signal during runtime execution
foreground res_init
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7fffddf6705d]
```

```
test(30623,0x70000b910000) malloc: *** error for object 0x4601510: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
foreground res_init
foreground res_init
SIGABRT: abort
PC=0x7fffde988d42 m=3 sigcode=0
signal arrived during cgo execution
```

It might be that the best workaround is to limit our calls to `res_init` to when we know we're linking against glibc? That way we could still fix the original bug (stale `/etc/resolv.conf` data in glibc specifically), take advantage of the thread safety that glibc seems to have here (we might want to audit it more carefully than I'm able to), and not worry about breaking any other platforms.

**Comment by jonhoo** [comment]
Your proposed workaround of only calling `res_init` when linking with glibc seems reasonable, also because only glibc has this problem. The other libc implementations *will* update the nameservers when the network changes. I don't exactly know how to implement that. Linux only seems too strict and *also* too weak? As mentioned in https://github.com/rust-lang/rust/pull/41582#issuecomment-315409026, it should be possible to switch to `res_ninit`, but it would require figuring out the exact symbol use by the per-thread `_res` symbol, which I suspect will a) be tricky from within Rust, and b) is probably libc dependent :/

**Comment by oconnor663** [comment]
Can we detect at runtime whether the symbol `gnu_get_libc_version` exists, and call it if so? I think we do something similar at https://github.com/rust-lang/rust/blob/1.19.0/src/libstd/sys/unix/weak.rs#L73-L79, though I don't know how _happy_ we are about doing that :|

**Comment by oconnor663** [comment]
This kinda sorta seems to work (in libstd we'd probably replace most of the machinery with the existing `weak!` macro):

```rust
extern crate libc;

use std::ffi::CStr;
use std::mem;

fn glibc_version() -> Option<&'static CStr> {
    unsafe {
        let funcptr = libc::dlsym(
            libc::RTLD_DEFAULT,
            "gnu_get_libc_version\0".as_ptr() as *const libc::c_char,
        );
        if !funcptr.is_null() {
            type CharstarFn = extern "C" fn() -> *const libc::c_char;
            let gnu_get_libc_version: CharstarFn = mem::transmute(funcptr);
            Some(CStr::from_ptr(gnu_get_libc_version()))
        } else {
            None
        }
    }
}

fn main() {
    println!("{:?}", glibc_version());
}
```

For me, `cargo run` prints `Some("2.25")`, and `cargo run --target=x86_64-unknown-linux-musl` prints `None`.

**Comment by alex** [comment]
FWIW, I just hit a crash on macOS that appears to possibly be this.

**Comment by oconnor663** [comment]
I just put up a PR with a possible workaround, similar to the `glibc_version` example above. There's a _very_ good chance I did something wrong, so @jonhoo please let me know what you think.

**Comment by oconnor663** [comment]
The fix just landed in master. @alex, any chance you can test it after the next nighty comes out?

**Comment by alex** [comment]
Will do. (Although I haven't seen this error in a few days, probably because race conditions :-/)

**Comment by oconnor663** [comment]
Btw, n00b question for you @alex. How do you figure out from `std::sys_common::net::{{impl}}::drop at net.rs:160` that it's actually line 181 or whatever that's to blame? Are there other tools that tell you who wrote to what memory?

**Comment by alex** [comment]
I didn't, at least not conclusively. I hit this crash, @Manishearth pointed me to this bug, and since it was crashing in "the right place", it seemed that with high probability this was the right diagnosis :-)

If I hadn't been pointed at this issue, I probably would have compiled with ASAN and seen what I hit.

**Comment by oconnor663** [comment]
Closing this since https://github.com/rust-lang/rust/pull/44965 landed a while ago.
