### ISSUE TITLE
Document os-specific types in libstd may have different representations

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#43601]
Spawned off https://github.com/rust-lang/rust/issues/43332 it was decided that we should document that OS-specific types may have different representations in the standard library. Things like `size_of` and `align_of` may be different depending on the platform you're working on.

**Comment by steveklabnik** [comment]
triage: tagging p-medium, we should review these docs

**Comment by Phlosioneer** [comment]
Made a PR for this; comments welcome!
