### ISSUE TITLE
Inconsistent current_exe behavior for symlinks on different platforms

### ISSUE THREAD

**Issue by jeffweiss** [rust-lang/rust#43617]
## Background

I was attempting to use `std::env::current_exe()` to figure out how my program was invoked so I could respond with convenience code paths (analogous to how `gpgv` is basically a shortcut/alias for `gpg --verify`) when I noticed inconsistent behavior between OS X and Linux when the program was invoked via a symbolic link.

## Steps to Reproduce

`test.rs`
```rust
fn main() {
    println!("{:?}", std::env::current_exe());
}
```
```bash
$ rustc test.rs
$ ln test one
$ ln -s test two
$ ./test
$ ./one
$ ./two
```
For convenience I have bundled these in a repo: [jeffweiss/rust-current_exe](https://github.com/jeffweiss/rust-current_exe)

## Rust Version
rustc 1.19.0 (0ade33941 2017-07-17)

## Expected Behavior

On all platforms, I would expect to get:
```
Ok("/home/jweiss/devel/jeffweiss/rust-current_exe/test")
Ok("/home/jweiss/devel/jeffweiss/rust-current_exe/one")
Ok("/home/jweiss/devel/jeffweiss/rust-current_exe/two")
```

## Actual Behavior

On Mac OS X, I get:
```
Ok("/home/jweiss/devel/jeffweiss/rust-current_exe/test")
Ok("/home/jweiss/devel/jeffweiss/rust-current_exe/one")
Ok("/home/jweiss/devel/jeffweiss/rust-current_exe/two")
```

On Linux, I get:
```
Ok("/home/jweiss/devel/jeffweiss/rust-current_exe/test")
Ok("/home/jweiss/devel/jeffweiss/rust-current_exe/one")
Ok("/home/jweiss/devel/jeffweiss/rust-current_exe/test")
```

## Related Documentation

The [documentation](https://github.com/rust-lang/rust/blob/7acce3724d6ba5cb84d6eef6d6847f8573a1fe5a/src/libstd/env.rs#L602-L614) for `std::env::current_exe` implies that if you run `current_exe` from the symlink, you'll get the name of the symlink, not the dereferenced target of the symlink; however, the documentation's example does not actually include a symbolic link (`ln -s`), but rather a hard link (`ln`).

**Comment by aidanhs** [comment]
I suspect this will have to be fixed in documentation (probably by just being more vague about what different platforms return) since I'm not sure there's a way to get what you want in Linux:
```
$ ln -s /bin/ls /tmp/some-test-ls
$ /tmp/some-test-ls -l /proc/self/exe
lrwxrwxrwx 1 aidanhs aidanhs 0 Aug  4 00:24 /proc/self/exe -> /bin/ls
```

I note that the busybox docker container uses hardlinks in `/bin`, presumably due to the same problem (it's a multi-call binary, as you want to provide).

Putting aside `current_exe`, you can possibly solve your use-case with the first element of `std::env::args()` instead.

**Comment by retep998** [comment]
Behavior on Windows is similar to the behavior on OS X.
```
Ok("D:\\Test\\link.exe")
Ok("D:\\Test\\one.exe")
Ok("D:\\Test\\two.exe")
```

**Comment by frewsxcv** [comment]
opened a pr for this: https://github.com/rust-lang/rust/pull/46987
