### ISSUE TITLE
unicode_chars.rs should be updated to match the latest confusables document

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#43629]
`src/libsyntax/parse/lexer/unicode_chars.rs` contains a list of confusable characters (see #25957). Its comments mention that it bases on a [document](http://www.unicode.org/Public/security/revision-06/confusables.txt). Of this document, a newer revision has been published ([link](http://www.unicode.org/Public/security/10.0.0/confusables.txt)). It contains many more confusables, e.g. ᐸ (canadian syllabics Pa). We should update unicode_chars.rs to include the newly listed confusables as well.

Bug report inspired by [this reddit post](https://www.reddit.com/r/rustjerk/comments/6c7ym4/when_the_compiler_has_your_back/disnn7g/).

**Comment by est31** [comment]
As there has been #33128, the person fixing this bug shouldn't just apply a script and regenerate from scratch, but go through the new confusables.txt and add the new characters manually.

**Comment by MaloJaffre** [comment]
I will try to work on this, because I have a lot of patience 😄
