### ISSUE TITLE
Rust windows installer failed when not run with admin privilege

### ISSUE THREAD

**Issue by buckle2000** [rust-lang/rust#43654]
Installer: `rustup-init.exe`

# How to reproduce this bug

1. start installer without admin privilege
Wait for download
When download of component `rustc` is completed, the installer says `Access denied` and halts.

2. start installer with admin privilege
the download is now complete, but the installer will request byte range of size 0 from the server, results in error `Cannot get multi-part...`.
`.multirust/` must be deleted to correct and restart installation

**Comment by mattico** [comment]
Would you mind opening this issue over at https://github.com/rust-lang-nursery/rustup.rs? That's the proper repo for rustup.

**Comment by buckle2000** [comment]
Moved to https://github.com/rust-lang-nursery/rustup.rs/issues/1223
