### ISSUE TITLE
Performance: fails to inline struct field access and keep it in the register.

### ISSUE THREAD

**Issue by dpc** [rust-lang/rust#43653]
I'm working on optimizing rolling checksum and CDC algorithms in `rsroll` package.

The Gear algorithm which is AFAIK the fastest rolling checksum  for CDCs known, with very tight and simple loop, basically rolls over each byte [like that](https://github.com/dpc/rsroll/blob/cd2592845dfe8a687a3e1d1f1ec9186ecda9e08e/src/gear.rs#L32):

```
    fn roll_byte(&mut self, b: u8) {
        self.digest = (self.digest << 1).wrapping_add(unsafe { *G.get_unchecked(b as usize) });
    }
```

where `G : [u64; 256]` with random numbers that keep being used to update `digest`, that is checked afterwards for some condition with a binary mask.

Since this loop is so tight it is basically memory access bound. Unfortunately, the generated code keeps reading and storing `self.digest` through a `r12` pointer:

```
   107a5:       49 8b 14 24             mov    (%r12),%rdx   /// read self.digest
   107a9:       48 01 d2                add    %rdx,%rdx
   107ac:       0f b6 30                movzbl (%rax),%esi
   107af:       48 ff c0                inc    %rax
   107b2:       48 03 14 f7             add    (%rdi,%rsi,8),%rdx
   107b6:       49 89 14 24             mov    %rdx,(%r12)  // store self.digest
   107ba:       48 ff c3                inc    %rbx
   107bd:       49 85 d6                test   %rdx,%r14
   107c0:       75 de                   jne    107a0 
```

We do have an alternative implementation, where this loop is very similar but there are no abstractions, and `digest` is a local variable in a function implementing everything and not a field on `struct Gear` that implements `trait RollingHash` like here. No amount of `#[inline]` or `#[inline(always)]` is able to convince the compiler to change its mind.

I am wondering if there is any workaround or fundamental reason this code (https://github.com/dpc/rsroll/blob/cd2592845dfe8a687a3e1d1f1ec9186ecda9e08e/src/gear.rs) fails to optimized better. The actual benchmark used is: https://github.com/dpc/rsroll/blob/cd2592845dfe8a687a3e1d1f1ec9186ecda9e08e/src/gear.rs#L129 and `objdump` is used to annalyze the resulting binary.

**Comment by nagisa** [comment]
This is probably the same bug as any other related to &mut not being noalias, but I can’t seem to find the issue to reference here, though.

**Comment by kennytm** [comment]
#31681?

**Comment by dpc** [comment]
It is all inlined though. LLVM should be able to see through it.

**Comment by dpc** [comment]
I have confirmed that inlining manually and thus removin the `&mut self` call, does fix the issue.

**Comment by dpc** [comment]
Closing as a dup of #31681

**Comment by dpc** [comment]
Actually, I don't know if it's only the problem with `&mut`. Since everything is being inlined, it should not matter that the argument is passed by `&mut`.

**Comment by arielb1** [comment]
@dpc 

It's still a problem. LLVM can't be sure that `G` does not overlap with `Self`, so it has to store the `digest` on each loop iteration.

**Comment by dpc** [comment]
`G` is a static array in the same crate. Shouldn't it help? I mean `Self` is created, used, destroyed on the stack through the whole, one, inlined function. :/

**Comment by philipc** [comment]
> I have confirmed that inlining manually and thus removin the &mut self call, does fix the issue.

Did you mean as in [this change](https://github.com/dpc/rsroll/commit/89010c1c9ac1a4043d8fc84cfa909a206ffae849)? You did more than inline it manually there: you also switched to using a local variable. Simply inlining didn't fix the issue in my tests.

Changing the code to simply add `b` instead of using `G` doesn't affect the problem.

Deleting the `if self.digest() & mask == 0 { ... }` conditional inside the loop avoids the extra loads, but it still does the stores inside the loop.

I tried converting the code to C with `restrict` pointers, and couldn't get gcc or clang to perform the optimization either.

**Comment by dpc** [comment]
Yes. By manually inlining, I meant I pasted the function logic directly to calling function as well as I could. Are you using clang or gcc to test?

**Comment by philipc** [comment]
> Are you using clang or gcc to test?

I tried both.

**Comment by Kobzol** [comment]
Looks like LLVM now keeps the field in a register (`r9` here) across the loop:
```asm
  30:	48 39 c8             	cmp    rax,rcx
  33:	74 3d                	je     72 <_ZN52_$LT$rollsum..gear..Gear$u20$as$u20$rollsum..CDC$GT$10find_chunk17h2013b458cc81225bE+0x72>

        for (i, &b) in buf.iter().enumerate() {
  35:	44 0f b6 1c 0a       	movzx  r11d,BYTE PTR [rdx+rcx*1]
  3a:	48 ff c1             	inc    rcx
        self.digest = (self.digest << 1).wrapping_add(unsafe { *G.get_unchecked(b as usize) });
  3d:	4d 01 c9             	add    r9,r9
  40:	4f 03 0c da          	add    r9,QWORD PTR [r10+r11*8]
  44:	4c 89 0e             	mov    QWORD PTR [rsi],r9
            self.roll_byte(b);

            if self.digest() & mask == 0 {
  47:	4d 85 c1             	test   r9,r8
  4a:	75 e4                	jne    30 <_ZN52_$LT$rollsum..gear..Gear$u20$as$u20$rollsum..CDC$GT$10find_chunk17h2013b458cc81225bE+0x30>
        *self = Gear {
  4c:	48 c7 06 00 00 00 00 	mov    QWORD PTR [rsi],0x0
  53:	48 39 c1             	cmp    rcx,rax
  56:	77 26                	ja     7e <_ZN52_$LT$rollsum..gear..Gear$u20$as$u20$rollsum..CDC$GT$10find_chunk17h2013b458cc81225bE+0x7e>
  58:	48 29 c8             	sub    rax,rcx
                self.reset();
                return Some((&buf[..i+1], &buf[i+1..]));
  5b:	48 89 17             	mov    QWORD PTR [rdi],rdx
  5e:	48 01 ca             	add    rdx,rcx
  61:	48 89 4f 08          	mov    QWORD PTR [rdi+0x8],rcx
  65:	48 89 57 10          	mov    QWORD PTR [rdi+0x10],rdx
  69:	48 89 47 18          	mov    QWORD PTR [rdi+0x18],rax
            }
        }
        None
    }
```

**Comment by dpc** [comment]
I have long forgotten about the issue, but it's good to hear it got better. Closing, as it's not really actionable in Rust project anyway.
