### ISSUE TITLE
nightly-rust beta regression (via slog-async-2.0.1)

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#43686]
[slog-async](https://crates.io/crates/slog-async) version 2.0.1 regressed from stable to beta ([full log](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.1/beta-2017-07-18/gh/mgattozzi.nightly-rust.35b0a2d6d2adb7d60291e41833f2ab3e0c33439e/log.txt)):

```
Aug 04 12:03:37.632 INFO kablam! error: type `slog::NeverStruct` is private
Aug 04 12:03:37.632 INFO kablam!    --> /cargo-home/registry/src/github.com-1ecc6299db9ec823/slog-async-2.0.1/lib.rs:178:1
Aug 04 12:03:37.633 INFO kablam!     |
Aug 04 12:03:37.633 INFO kablam! 178 | / pub struct AsyncCoreBuilder<D>
Aug 04 12:03:37.633 INFO kablam! 179 | |     where D: slog::Drain<Err = slog::Never, Ok = ()> + Send + 'static
Aug 04 12:03:37.634 INFO kablam! 180 | | {
Aug 04 12:03:37.634 INFO kablam! 181 | |     chan_size: usize,
Aug 04 12:03:37.635 INFO kablam! 182 | |     drain: D,
Aug 04 12:03:37.635 INFO kablam! 183 | | }
Aug 04 12:03:37.635 INFO kablam!     | |_^
```
cc @dpc

Also broke @mgattozzi 's https://github.com/mgattozzi/nightly-rust at commit https://github.com/mgattozzi/nightly-rust/commit/35b0a2d6d2adb7d60291e41833f2ab3e0c33439e

**Comment by arielb1** [comment]
- rust-lang/rust#42125

**Comment by dpc** [comment]
Does it mean we can close?

**Comment by arielb1** [comment]
@mgattozzi's library will be broken until he updates his `Cargo.lock`. Waiting to a response from him.

**Comment by dpc** [comment]
Well, I can't fix other project's `Cargo.lock`, neither I can fix an immutable version that was published. No actionable items means, I'm closing. Feel free to keep commenting, or reopen if any need arises.

**Comment by dpc** [comment]
Oh. I thought this issue is filled against `slog`.

**Comment by mgattozzi** [comment]
@arielb1 I haven't had to update it in awhile since I haven't had to update the bot in forever. A testament to Rust's stability. I can update the program and push a change.

**Comment by mgattozzi** [comment]
Updated the code so the fix is in. Thanks for the notification.
https://github.com/mgattozzi/nightly-rust/commit/af4b8c7c6477f2f16cd08bd8b85f788ccba4c105

If this issue isn't needed anymore I think you can close this.

**Comment by est31** [comment]
@mgattozzi thanks!

**Comment by mgattozzi** [comment]
You're welcome @est31!
