### ISSUE TITLE
statrs 0.6.0 and 0.7.0 beta regression

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#43680]
[statrs](https://crates.io/crates/statrs) versions 0.6.0 and 0.7.0 regressed from stable to beta ([full log 1](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.1/beta-2017-07-18/reg/statrs-0.6.0/log.txt), [full log 2](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.1/beta-2017-07-18/reg/statrs-0.7.0/log.txt)):

```
Aug 03 23:18:26.668 INFO blam! error[E0061]: this function takes 1 parameter but 0 parameters were supplied
Aug 03 23:18:26.668 INFO blam!  --> <anon>:7:11
Aug 03 23:18:26.668 INFO blam!   |
Aug 03 23:18:26.668 INFO blam! 7 | assert!(x.max().is_nan());
Aug 03 23:18:26.668 INFO blam!   |           ^^^ expected 1 parameter
Aug 03 23:18:26.668 INFO blam! 
Aug 03 23:18:26.668 INFO blam! error[E0599]: no method named `is_nan` found for type `[_; 0]` in the current scope
Aug 03 23:18:26.668 INFO blam!  --> <anon>:7:17
Aug 03 23:18:26.668 INFO blam!   |
Aug 03 23:18:26.668 INFO blam! 7 | assert!(x.max().is_nan());
Aug 03 23:18:26.668 INFO blam!   |                 ^^^^^^
Aug 03 23:18:26.668 INFO blam! 

```
cc @boxtown

**Comment by arielb1** [comment]
- #42496 - The functions `Ord::min` and `Ord::max` were added.

This conflicts with functions with the same name being implemented by other traits, e.g. by `trait Statistics` defined in https://github.com/boxtown/statrs/blob/v0.7.0/src/statistics/statistics.rs

To fix this, either rename the conflicting functions, or call them using UFCS notation (`Statistics::max(x).is_nan()`). This is unfortunate.

**Comment by boxtown** [comment]
Thanks for the heads up, I'll address this ASAP. It'll make it to the 0.8.0
release which I'm hoping to cut by Monday

**Comment by alexcrichton** [comment]
@boxtown note that the change here seems to have caused more breakage than intended, so if you've got difficulty fixing this please let us know!

**Comment by boxtown** [comment]
Regression fix is in place in master (see boxtown/statrs@e728aac) and will be released with 0.8.0. It was only a small regression affecting doc tests for empty slices and can be easily resolved by pinning the type of the slice to `[f64; 0]` e.g. `let x: [f64; 0] = [];`. No API or code changes were necessary

**Comment by alexcrichton** [comment]
Ok thanks for the info @boxtown!

**Comment by boxtown** [comment]
0.8.0 was just released yesterday so this issue can probably be closed

**Comment by est31** [comment]
Thanks!
