### ISSUE TITLE
Extremely slow macro expansion

### ISSUE THREAD

**Issue by mikebenfield** [rust-lang/rust#43704]
See [this gist](https://gist.github.com/mikebenfield/bb2cc55da71352e78aa611f0fcdee219). 

Here is a chart giving `real` time output from `time rustc main.rs -o out` with `n` of the lines of the form `[0xDD, 0xCB, d, 0x00 ]` uncommented.

n       | sec    |
--------|--------|
| 100   | 0.561  |
| 200   | 1.457  |
| 300   | 3.042  |
| 400   | 5.474  |
| 500   | 8.061  |
| 600   | 12.364  |
| 700   | 17.520  |
| 800   | 25.105  |
| 900   | 37.410  |
| 1000  | 48.006  |
| 1100  | 72.33  |

With this gist I've tried to create a fairly minimal example. It's not as minimal as maybe it could be because it's a little tricky to figure out what's causing the slow compiles and I've spent as much time as I can on this right now. It's very sensitive to seemingly irrelevant changes in the code. If I remove the unused `count` variable, compile times dramatically improve. If I remove the empty `for` loop, compile times dramatically improve.

On my actual project, I am getting compile times in excess of 20 minutes. To compile a few thousand lines of code.

**Comment by arielb1** [comment]
cc @jseyfried

**Comment by arielb1** [comment]
Umm this is not an expansion problem but rather a borrowck problem - dataflow somehow takes O(n) iterations to converge.
