### ISSUE TITLE
librustdoc no longer part of distributable

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#43729]
librustdoc used to be distributed with other compiler crates and could be found in the sysroot. This is no longer the case which breaks any crate which does `extern crate rustdoc;`.

I assume this wasn't intentional and is due to the changes with how rustdoc is being built.

cc @Mark-Simulacrum @alexcrichton

**Comment by alexcrichton** [comment]
Hm this was indeed intentional, all due to https://github.com/rust-lang/rust/pull/43482. That being said, it wasn't intended to break things!

@nrc did you have tools using `extern crate rustdoc` out of tree? That's sort of something I'd hope that we wouldn't have to keep working :(

**Comment by Mark-Simulacrum** [comment]
Yes, this was indeed intentional. We can technically fix this I think if we need to, but I'd prefer not to -- it'd be a bit of a hack.

**Comment by nrc** [comment]
> did you have tools using extern crate rustdoc out of tree?

Yes, rustw does. It only uses its markdown rendering though. I'd assume I could pull that into an external crate, but iirc, the last time I tried that it was tied into rustdoc and compiler internals in weird ways.

I'll look into that - I assume Steve will have to solve a similar problem for new rustdoc, so maybe I can use that?

**Comment by Mark-Simulacrum** [comment]
Well, if it's not working out to migrate to either the new rustdoc or otherwise solve the problem, let us know and we can discuss making librustdoc remain in the sysroot.

**Comment by Mark-Simulacrum** [comment]
@rfcbot fcp close

Let's see if this works...

If not, I'll just close; I don't think this is going to change. rustdoc is unstable, and shouldn't really be used for markdown rendering anyway...

**Comment by Mark-Simulacrum** [comment]
Closing as per concluded FCP.
