### ISSUE TITLE
Explicit return compiles when an implicit return does not

### ISSUE THREAD

**Issue by mister-walter** [rust-lang/rust#43755]
I first posted this issue [on Reddit](https://www.reddit.com/r/rust/comments/6sipsb/explicit_vs_implicit_return/), and someone there suggested that it might be incorrect behavior, and that I file a bug report.

I installed Clippy and was fixing warnings that it emitted in a project I've been working on. Clippy suggested that I replace `return val.borrow().is_empty();` with `val.borrow().is_empty()` in the following function `foo`, saying that it is an `unneeded return statement`.

```
fn foo(x: Option<Weak<RefCell<String>>>) -> bool {
    match x {
        Some(ref weak_ref) => {
            let val = weak_ref.upgrade().unwrap();
            return val.borrow().is_empty();
        },
        None => false
    }
}
```

So I do so, and produce the following function `bar`.

```
fn bar(x: Option<Weak<RefCell<String>>>) -> bool {
    match x {
        Some(ref weak_ref) => {
            let val = weak_ref.upgrade().unwrap();
            val.borrow().is_empty()
        },
        None => false
    }
}
```

But now the compiler complains!

```
error[E0597]: `val` does not live long enough
   |             val.borrow().is_empty()
   |             --- borrow occurs here
   |         },
   |         ^ `val` dropped here while still borrowed
```

Not sure if this is a bug, a limitation of the borrow checker, or something else entirely! 

I would expect: replacing an implicit return with an explicit return wouldn't result in a compile error

Note that the following variation of the function does compile:
```
fn foobar(x: Option<Weak<RefCell<String>>>) -> bool {
    match x {
        Some(ref weak_ref) => {
            let val = weak_ref.upgrade().unwrap();
            let ret = val.borrow().is_empty();
            ret
        },
        None => false
    }
}
```

## Meta

`rustc --version --verbose`:
```
rustc 1.21.0-nightly (ba1d065ff 2017-08-06)
binary: rustc
commit-hash: ba1d065ffa3606b61201ef69fec3ad0bfc5b2f7b
commit-date: 2017-08-06
host: x86_64-apple-darwin
release: 1.21.0-nightly
LLVM version: 4.0
```

**Comment by sfackler** [comment]
I think this is an instance of #21114.

**Comment by mister-walter** [comment]
Sorry about that, yeah this seems to be a duplicate of #21114.
