### ISSUE TITLE
doc does not correctly display macro match arms if they are created inside of a proc macro

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#43759]
When creating a macro tagged with `#[macro_export]` inside of a `proc_macro_derive` the documentation incorrectly displays the name of the derive instead of the match pattern.

I tried this code: (everything is the same as [here](https://doc.rust-lang.org/beta/book/first-edition/procedural-macros.html) except for "main.rs" and "impl_hello_world()").

main.rs:
```rust
#[macro_use]
extern crate hello_world_derive;

#[derive(HelloWorld)]
struct Foo {
}

fn main() {
    Foo!("Hi");
}
```
hello-world-derive/src/lib.rs:

```rust
/* ... */

fn impl_hello_world(ast: &syn::DeriveInput) -> quote::Tokens {
    let name = &ast.ident;
    quote! {
        #[macro_export]
        macro_rules! #name {
            ($expr:expr) => {
                println!("expr: {}", $expr);
            }
        }
    }
}
```

When opening the automatic documentation(`cargo doc --open`) I expected `Foo!` to look like this: 
```rust
macro_rules! Foo {
    ($expr:expr) => { ... };
}
```

Instead, Foo looked like this: ( the name of the derive instead of the actual match pattern.)
```rust
macro_rules! Foo {
    HelloWorld => { ... };
}
```

In case the created macro has more than 1 match arm it looks like this:
```rust
macro_rules! Foo {
    HelloWorld => { ... };
    HelloWorld => { ... };
}
```
## Meta

`rustc --version --verbose`:

> rustc 1.19.0 (0ade33941 2017-07-17)
> binary: rustc
> commit-hash: 0ade339411587887bf01bcfa2e9ae4414c8900d4
> commit-date: 2017-07-17
> host: x86_64-pc-windows-msvc
> release: 1.19.0
> LLVM version: 4.0

**Comment by camelid** [comment]
I tested this, and it is fixed now. I believe it was fixed in #86282.

Updated proc-macro code based on modern Rust:

```
use proc_macro::TokenStream;
use quote::quote;

#[proc_macro_derive(HelloWorld)]
pub fn impl_hello_world(input: TokenStream) -> TokenStream {
    let ast: syn::DeriveInput = syn::parse(input).unwrap();
    let name = &ast.ident;
    quote! {
        #[macro_export]
        macro_rules! #name {
            ($expr:expr) => {
                println!("expr: {}", $expr);
            }
        }
    }.into()
}
```

![image](https://github.com/rust-lang/rust/assets/37223377/7e20ed19-421a-4691-97f7-a027b900646d)
