### ISSUE TITLE
Rewrite compiletest to use `Command` liberally

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#43762]
Believe it or not but the `compiletest` project predates the usage of `Command` in the standard library. We currently pass through tons of variables in tons of places, eventually culminating in creating a `Command` at the very end. We should instead thread through a `Command` everywhere to make argument passing much nicer!

That way we also don't need [functions with seven arguments](https://github.com/rust-lang/rust/blob/master/src/tools/compiletest/src/procsrv.rs#L70-L77)!

**Comment by euclio** [comment]
I'd like to work on this.

**Comment by alexcrichton** [comment]
Awesome thanks @euclio! If you've got any questions please don't hesitate to ask!
