### ISSUE TITLE
Hasher::finish() does not reset the hasher.

### ISSUE THREAD

**Issue by partim** [rust-lang/rust#43763]
At least for `HashMap`’s default hasher, a call to `Hasher::finish()` will not reset the hasher’s internal state. Instead, additional `write()`s will modify the hasher’s existing state as if `finish()` had never been called:

```
use std::hash::{Hash, Hasher};
use std::collections::hash_map::DefaultHasher;

fn main() {
    let mut hasher = DefaultHasher::new();
    0u8.hash(&mut hasher);
    let h1 = hasher.finish();
    0u8.hash(&mut hasher);
    let h2 = hasher.finish();
    println!("h1: {}\nh2: {}", h1, h2);
}
```

will produce

```
h1: 7541581120933061747
h2: 6165216591721696495
```

Is this intended behavior? If so, this should probably mentioned in the documentation as it is somewhat surprising given the name of the method. I am happy to create a PR but wanted to check first.

**Comment by bluss** [comment]
Finish has a signature with `&self` so immutability in it is more or less enforced by the trait. The remaining decision is how this should be documented on the trait; as a guarantee or just rule of thumb. The latter seems closest since it doesn't add a contract to an existing trait.

**Comment by partim** [comment]
Oh, fair point about the `&self` argument. Totally missed that.

So, I propose to modify the documentation for `Hasher::finish()` pointing out more clearly the function really only extracts the current hash value and that if one wishes to create the hash of a new value one needs to create a new hasher for that. I’ll submit a PR later.
