### ISSUE TITLE
Handle git info in rustbuild differently

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#43771]
Right now we encode git information directly into the rustc binary that we build during the normal build process, and this information powers `rustc -vV` and such. At this time, however, this git information is loaded from the git repository every time you execute `./x.py build`. Consequently, whenever a new commit is made, lots of rustc libs need to be rebuilt!

My personal workflow consists of making commits over time as I fix things (especially tests), and having everything get rebuilt every time I make a commit is a bit of a bummer! I think a better strategy here would be to cache git information from the first time of invocation of rustbuild into the out directory. That way we keep reporting the same commit (even though it may not exist or be the actual commit) when there's a persisted build directory.

I believe a strategy like this won't affect the builds on CI, but may hopefully improve the developer experience!

**Comment by est31** [comment]
What about not tracking git info for the dev profile? No git commit is better than a wrong one imo.

**Comment by alexcrichton** [comment]
@est31 oh that's an even better idea! I'm 👍 to doing that.

**Comment by Mark-Simulacrum** [comment]
My pull request with fixes to rustbuild has a flag (ignore-git) that just ignores git info; making it default to true is maybe not ideal, but seems fine for the dev profile.

**Comment by alexcrichton** [comment]
Oh right, awesome! Once that lands I'll tag this as E-easy.

**Comment by Mark-Simulacrum** [comment]
The relevant PR landed, so tagging this as E-easy and E-mentor. I believe what needs to happen is `config.ignore_git` needs to be set to true if `config.channel` is equal to dev, but this can only happen after [the line that loads it](https://github.com/rust-lang/rust/blob/master/src/bootstrap/config.rs#L421). Should be a relatively easy change to make, but don't forget to document it in `config.toml.example` in the root of the tree. Let us know if you need any help with this!

**Comment by JeremySorensen** [comment]
I would like to try to take this on, if that's OK. I have a question right out of the gate however; looking at these lines:
```
set(&mut config.channel, rust.channel.clone());
set(&mut config.ignore_git, rust.ignore_git);
```
In the case `that config.channel` is equal to `dev`, do we force `config.ignore_git` to true, or only set it to true if it is not present in the `rust` variable with the deserialized toml?

It seems like either way I would add code to set `config.ignore_git` to true if `config.channel` is `dev`, but if it is a force override I would put it after `set(&mut config.ignore_git, rust.ignore_git);` and if it is a default, I would just put it before that line.

**Comment by alexcrichton** [comment]
Oh sorry about this @JeremySorensen, I think I [made a PR](https://github.com/rust-lang/rust/pull/43873) *just* before you commented! That being said, @Mark-Simulacrum had some comments on that PR and it looks like what you're thinking is more along the lines of what he's thinking, so I'm gonna close that PR and let you take over if you'd like.

I believe what you're thinking is spot on though!

**Comment by JeremySorensen** [comment]
@alexcrichton Thanks for letting me take a crack at this!
