### ISSUE TITLE
panic=abort compatible test harness

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#43788]
Right now developing a `panic=abort` project can be relatively painful when running tests. A `cargo build` will compile everything with `panic=abort` but a `cargo test` will recompile everything with `panic=unwind`. This is currently due to the fact that libtest *requires* panic=unwind to correctly operate. Otherwise it can't catch test failures!

We may wish to explore a panic=abort compatible test harness to [remove Cargo's special casing](https://github.com/rust-lang/cargo/blob/8720d63bc14e64b66e6f866b37cddd620c01b057/src/cargo/util/toml/mod.rs#L1031-L1036). Some possible ways to implement this may be:

* Instead of starting a thread for all tests we could instead start a process. This process could be a re-execution of the executable itself and we'd just do that once per test. The downside of this is that it may be super slow.
* We could continue to start a thread for each test but override the panic handler for the process. This panic handler would do "test related things" and provide an opportunity for a "clean exit". The downside of this is that you wouldn't get a set of all tests that failed, just the first few (maybe)

I think that we'll also need support in the compiler for this, we'd have to inject different test frameworks or backends depending on the `-C panic=...` configured mode.

**Comment by Mark-Simulacrum** [comment]
I believe this is https://github.com/rust-lang/rust/issues/32512, closing in favor of that. I agree that this would be good, though I think it's more of a feature than an enhancement (but it's a fine line that doesn't matter that much).

**Comment by alexcrichton** [comment]
Aha indeed!
