### ISSUE TITLE
Error message references non-existent Rust version

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang/rust#43780]
The text for https://doc.rust-lang.org/error-index.html#E0106 references a non-existent Rust version.

"Here's an example that is currently an error, but may work in a future version of Rust:"

This isn't really helpful for understanding the error, and isn't that helpful of a predictor of Rust's future.

Reported by https://twitter.com/xernobyl/status/895450156627238912

**Comment by durka** [comment]
The text after the example

> Lifetime elision in implementation headers was part of the lifetime elision RFC. It is, however, currently unimplemented.

is instructive. In theory, if you read the RFC, then you'd expect that code to work.

**Comment by jonathandturner** [comment]
@durka - we shouldn't reference non-existent versions of Rust in our error codes.  It's confusing (as pointed to by the link I shared).

It's fine to talk about them in other RFCs, but not anything a new user might encounter.

**Comment by frewsxcv** [comment]
Opened a PR for this: https://github.com/rust-lang/rust/pull/45585
