### ISSUE TITLE
Are we able to document the default stack size for threads?

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#43805]
One can specify the stack size of a thread via [`thread::Builder::stack_size`](https://doc.rust-lang.org/std/thread/struct.Builder.html#method.stack_size). If one does _not_ use this method when building a thread, it uses some default value, which is specified in [`util::min_stack`](https://github.com/rust-lang/rust/blob/0ca9967af75f7a279dcf4921f119b2602b41dd71/src/libstd/sys_common/util.rs#L18-L30).

It looks like `util::min_stack` looks at the `RUST_MIN_STACK` env var and attempts to parse it into an integer. If it's not specified or can't parse, it falls back to 2MB.

Should we update the thread documentation to mention what the default stack size is and mention that environment variable?

**Comment by frewsxcv** [comment]
Relevant discussion on IRC https://botbot.me/mozilla/rust-docs/2017-08-11/?msg=89704992&page=1

**Comment by retep998** [comment]
Don't forget that the stack size of the main thread is *not* determined by Rust.

**Comment by frewsxcv** [comment]
Opened a PR: https://github.com/rust-lang/rust/pull/43848
