### ISSUE TITLE
Error in derived PartialOrd impl on structs with mut reference fields

### ISSUE THREAD

**Issue by arkeet** [rust-lang/rust#43816]
This fails to compile, with a rather cryptic error message: [[playground](https://play.rust-lang.org/?gist=7cdb527ccc2deb676421d8d53fc49129&version=nightly)]

```rust
#[derive(PartialEq, PartialOrd)]
struct Bad<'a>(&'a mut u8);
```

This is one of the errors in the expanded code (the rest are similar):
```rust
// error[E0389]: cannot borrow data mutably in a `&` reference
fn lt(&self, __arg_0: &Bad<'a>) -> bool {
    match *__arg_0 {
        Bad(ref __self_1_0) =>
//          -------------- consider changing this to `ref mut __self_1_0`
        match *self {
            Bad(ref __self_0_0) =>
            (*__self_0_0) < (*__self_1_0) ||
//                          ^^^^^^^^^^^^^ assignment into an immutable reference
                !((*__self_1_0) < (*__self_0_0)) && false,
        },
    }
}
```

Seems quite similar to #15689.

**Comment by durka** [comment]
Why is the derive code dereferencing the captures‽ There's a forwarding impl! https://github.com/rust-lang/rust/blob/1e60a477a3f28ec5dc6e93e2714320d829bd7942/src/libcore/cmp.rs#L943-L951

**Comment by Mark-Simulacrum** [comment]
Appears to work today. Closing.
