### ISSUE TITLE
return x; and x not equivalent at end of function?

### ISSUE THREAD

**Issue by lheckemann** [rust-lang/rust#43837]
I have [some code which the borrow checker doesn't agree with](https://play.rust-lang.org/?gist=ea9e2492053ebb69ef80915500d696e3&version=stable). However, it works fine if I [replace the expression at the end of the function with a return statement containing the same expression](https://play.rust-lang.org/?gist=ea9e2492053ebb69ef80915500d696e3&version=stable). I believed that `return x;` was fully equivalent to `x` at the end of a function, but apparently not? Not sure if this is a documentation issue or a compiler bug, but after raising this on #rust-beginners it was recommended that I raise it here :)

**Comment by arielb1** [comment]
They are not equivalent. The destructor for `possible.drain()` runs earlier in the `return` version and later (too later) in the no-`return` version.

**Comment by lheckemann** [comment]
In that case I think this is a documentation issue. https://doc.rust-lang.org/reference/items.html#functions suggests that they are equivalent:

>Every control path in a function logically ends with a return expression or a diverging expression. If the outermost block of a function has a value-producing expression in its final-expression position, that expression is interpreted as an implicit return expression applied to the final-expression.

**Comment by arielb1** [comment]
That paragraph is actually sort-of correct - what matters is whether there's a semicolon (making for a return statement) or not (see https://play.rust-lang.org/?gist=763b754c7393eb72d3d8b79721dba3ba&version=stable - a non-semicoloned return expression.

OTOH, that reference section is entirely a lie for several reasons. Let's fix it

**Comment by xftroxgpx** [comment]
> The destructor for possible.drain() runs earlier in the return version and later (too later) in the no-return version.

But why isn't this applied though?
`note: values in a scope are dropped in the opposite order they are created`

If it happens that the lifetimes of both 'possible' and 'possible.drain()' end at the same point(when function scope ends?), then shouldn't they be `dropped in the opposite order they are created`.

Why does `The destructor for possible.drain()` run `later (too later) in the no-return version.` ?

**Comment by xftroxgpx** [comment]
the [code in OP](https://play.rust-lang.org/?gist=ea9e2492053ebb69ef80915500d696e3&version=stable) is now [working](https://play.rust-lang.org/?gist=073120a96fbc4fd6ebacd5ea0cdb1313&version=nightly) by prepending the line `#![feature(nll)]` (Rust nightly required, currently)

now, let me just take a moment to praise the [NLL](https://github.com/rust-lang/rust/issues/43234) gods... :1st_place_medal:
