### ISSUE TITLE
20% compiler memory usage regression in syntex_syntax incremental compile

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#43835]
[According to perf.rust-lang.org](https://perf.rust-lang.org/graphs.html?start=2017-07-07T00%3A00%3A00%2B00%3A00&end=2017-07-16T00%3A00%3A00%2B00%3A00&crates=%7B%22list%22%3A%22List%22%2C%22content%22%3A%5B%22syntex-0.42.2%40020-clean%22%5D%7D&phases=%7B%22list%22%3A%22All%22%2C%22content%22%3Anull%7D&group_by=crate&type=rss&yaxis=pct) the syntex_syntax benchmark for a clean incremental compile regressed 20% in compiler memory usage due to https://github.com/rust-lang/rust/pull/43028.

@michaelwoerister is it helpful to track "regressions" for incremental compilation right now? Or is enough in flux that we should not worry about it just yet?

**Comment by michaelwoerister** [comment]
I'd say, not quite yet as there are some big changes around the corner. Also, I'm not sure how reliable perf.rlo is for anything after https://github.com/rust-lang/rust/pull/43506. (@Mark-Simulacrum would know more about the current state there).

**Comment by alexcrichton** [comment]
Ok sounds like we shouldn't track incremental-related regressions yet, so I'll close.
