### ISSUE TITLE
I/O Read functions are very slow

### ISSUE THREAD

**Issue by oldaniel** [rust-lang/rust#43845]
So, I am currently coding with **iron** (the web framework), since it is web stuff I want to read the users request body. And that's where I ran into damn big issues.

Wether I use `io::Read` or `io::BufReader`, wether I use `.read()`, `.read_to_end()` or `.read_to_string()`, my benchmark went from ~290k (without read) down to ~112 requests per second.

Example code:
```rust
fn hello(req: &mut Request) -> IronResult<Response> {
    let mut body = String::new();
    let mut bytes = Vec::new();
    let mut lbytes = vec![0;100];

    // NOTICE: I checked, those reads are successful and return the correct value.
    req.body.read_to_end(&mut bytes).unwrap();
    // Or
    req.body.read(&mut lbytes).unwrap();
    // Or
    req.body.read_to_string(&mut body).unwrap();

    Ok(Response::with((status::Ok, "Hello World!")))
}
```

**Does anyone have a workaround for the same issues? Is there maybe a duplicate question I didn't found? Is this issue known?**

**Comment by sfackler** [comment]
The standard library's Read functions directly call into the standard C APIs.  It might make more sense to file this with Iron or Hyper.

**Comment by oldaniel** [comment]
I just wondered, because the Iron Request object, or better said the body
field of it refers to a io::Read object. I thought this would be maybe
something to issue at Rust.

Sorry for that

Am 13.08.2017 18:10 schrieb "Steven Fackler" <notifications@github.com>:
