### ISSUE TITLE
Documentation: Bullet list in Deref documentation not working, causing confusing

### ISSUE THREAD

**Issue by kumbayo** [rust-lang/rust#43866]
The documentation of Deref/DerefMut wants to show a list with 3 bullet points.
https://doc.rust-lang.org/nightly/std/ops/trait.Deref.html#more-on-deref-coercion

But instead all 3 list entries are squashed together into a single block separated by 3 * characters.

![deref_strange_list](https://user-images.githubusercontent.com/1041267/29287688-9f35b89a-8136-11e7-9c3f-9a532c49e446.png)

This * character is a bit confusing in the context of dereferencing operations which uses the `*`.

In other parts of the documentation, bullet list seem to work normally.
https://doc.rust-lang.org/nightly/std/primitive.f32.html#method.atan2
Not sure what the difference is here.

CC @lukaramu You seem to have added these in 5990be523d00edaf69cfd6d3e28d9fb78eb67bcd

**Comment by steveklabnik** [comment]
see https://github.com/rust-lang/rust/blob/master/src/libcore/ops/deref.rs#L29-L33

vs https://github.com/rust-lang/rust/blob/af049cd08b58520af2dd202f15d00f67f9748322/src/libstd/f32.rs#L870-L873

I have a hunch that you need an extra line of whitespace before the list. We should do it anyway, but that may or may not also fix this issue.

**Comment by lukaramu** [comment]
That was probably caused by me being used to GitHub's markdown implementation, in which the extra whitespace line is not required :sweat_smile: 

I'll send out a fix PR!
