### ISSUE TITLE
Extend E0623 for fn and trait objects WIP

### ISSUE THREAD

**Issue by gaurikholkar** [rust-lang/rust#43877]
Examples
```
fn foo<'a,'b>(x:  for<'c, 'd> fn(&'c u8, &'d u8), y: Vec<&'a u8>, z: &'b u8) {
  y.push(z); // index will be zero or one
}
```
cc @nikomatsakis @estebank @arielb1 @GuillaumeGomez

**Comment by gaurikholkar** [comment]
An extension of #43269

**Comment by gaurikholkar** [comment]
Made basic changes in this [commit](https://github.com/gaurikholkar/rust/commit/7a2fc5cbacf55c9f10db7a22b2bff0b76c134a8b).
Gives me the following [error](https://gist.github.com/gaurikholkar/1cb59243cacefff4a268710bbd263d50#file-error-md)

**Comment by gaurikholkar** [comment]
This has been taken care in #44516

**Comment by estebank** [comment]
Closing as per #44516.
