### ISSUE TITLE
Tracking issue for `String::retain`

### ISSUE THREAD

**Issue by murarth** [rust-lang/rust#43874]
Tracking issue for method `String::retain`, introduced in #43500.

**Comment by alercah** [comment]
Any reason not to stabilize?

**Comment by Mark-Simulacrum** [comment]
@rust-lang/libs -- nominating for stabilization. This API was introduced about half a year ago and seems reasonable to stabilize.

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

Sounds good to me!
