### ISSUE TITLE
Add option to clear the CPU caches while benchmarking

### ISSUE THREAD

**Issue by Vurich** [rust-lang/rust#43885]
Often a more representative view of a piece of code's performance is on a cold cache, especially when it does a lot of reading of statics (which will be allocated in the same place each time and so will stay warm between benching rounds). It's pretty simple to clear the CPU cache in single-threaded code - just read a massive array using `test::black_box()` or suchlike, and possibly run some straight-line explicit `asm` to clear the instruction cache. The only unanswered question is how to reliably time it.

This should probably not be incorporated into the standard benching functions since it will significantly slow down pretty much every benchmark, but for some use-cases it's invaluable.

**Comment by dtolnay** [comment]
Thanks! I agree this seems important to support in a convenient way.

I would prefer to track this as part of https://github.com/rust-lang/rfcs/issues/816 -- that way we keep the standard test framework minimal while allowing libraries to develop more sophisticated custom test frameworks with advanced control of CPU caches and other nice things.
