### ISSUE TITLE
Can not access buildbot.rust-lang.org

### ISSUE THREAD

**Issue by netroby** [rust-lang/rust#43898]
This page isn’t working

buildbot.rust-lang.org is currently unable to handle this request.
HTTP ERROR 503

http://buildbot.rust-lang.org/

**Comment by zackmdavis** [comment]
The bot got moved at some point; try https://buildbot2.rust-lang.org/homu/queue/rust? Are there some docs that need to be updated?

**Comment by netroby** [comment]
Or how about made 302 redirect to the new target url?

**Comment by petrochenkov** [comment]
>Are there some docs that need to be updated?

There are few references to the old address in the rust repo, including `CONTRIBUTING.md` (all can be found by searching "buildbot").

**Comment by frewsxcv** [comment]
Fixed the broken link in https://github.com/rust-lang/rust/pull/44004 so I'm going to remove the `T-doc` issue tag here.

It would be nice if there was a https://queue.rust-lang.org or something that was a GitHub Pages site that had an `<iframe>` for buildbot2.rust-lang.org and whatever else relevant resources for maintaining the queue. It'd be easy to change if the homu link changes again in the future.

**Comment by alexcrichton** [comment]
I [wrote up instructions](http://logs.glob.uno/?c=mozilla%23rust-infra&s=27+Apr+2017&e=27+Apr+2017&h=buildbot2.rust-lang.org#c4179) on IRC how to do this awhile ago, and I believe they're still basically applicable today.

If anyone would like to help implement this and still has questions please just let me know!
