### ISSUE TITLE
Rust thinks u64 and f64 have 4 byte alignment on Linux 32bit

### ISSUE THREAD

**Issue by upsuper** [rust-lang/rust#43899]
The following code:
```rust
use std::mem;
fn main() {
    println!("sizeof u64: {}, alignof u64: {}",
             mem::size_of::<u64>(), mem::align_of::<u64>());
    println!("sizeof f64: {}, alignof f64: {}",
             mem::size_of::<f64>(), mem::align_of::<f64>());
}
```
with
```
rustc test.rs --target=i686-unknown-linux-gnu
```

The generated executable outputs:
```
sizeof u64: 8, alignof u64: 4
sizeof f64: 8, alignof f64: 4
```
which matches neither gcc nor clang.

And this issue seems to block linux32-stylo.

**Comment by upsuper** [comment]
cc @emilio

**Comment by sfackler** [comment]
According to the i386 System V ABI, u64 and f64 are 4 byte aligned - see Table 2.1 in https://www.uclibc.org/docs/psABI-i386.pdf.

**Comment by emilio** [comment]
Yes, but C++ compilers seem to disagree with that, apparently, which causes trouble :(

**Comment by sfackler** [comment]
C++ doesn't have a stable ABI, it has "whatever gcc and clang decided to do".

**Comment by emilio** [comment]
So, some relevant bugs:

 * https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69763
 * https://gcc.gnu.org/bugzilla/show_bug.cgi?id=79024
 * https://bugs.llvm.org/show_bug.cgi?id=26547

**Comment by nagisa** [comment]
Seems to match C in both gcc and clang just fine:

```
#include<inttypes.h>

#define alignof(type) (unsigned)((&((struct { char c; type d; } *)0)->d))

int main(void) {
    printf("%u %u %u %u\n", sizeof(uint64_t), alignof(uint64_t), sizeof(double), alignof(double));
    return 0;
}
```

where both output `8 4 8 4`.

**Comment by upsuper** [comment]
Actually even in C++, something like
```c++
struct Test1 { char c; uint64_t u; };
```
would have the second field aligned to 4 bytes rather than 8 bytes, as can be found in [my bug report to gcc](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=79024).

So the behavior really is, when the type are the first field of a struct, or they are on themselves, they have a different alignment.

**Comment by upsuper** [comment]
OK, so I don't think this is really a valid issue. It is reasonable that `u64` and `f64` have 4byte alignment on 32bit Linux (actually they should).

There may be problem when passing `u64` and `f64` through FFI since if IIUC, the 8byte alignment is used for that. But that's a different issue, though.

So the real problem here is actually a mix of bindgen issue and lack of language support from Rust side when manual alignment (`alignas`/`alignof`) is used in C++.
