### ISSUE TITLE
RUST_BACKTRACE starts at map_err

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/rust#43892]
When using `RUST_BACKTRACE` to obtain a stack trace in the event of a panic, if `map_err` was used to manipulate the type of the error being generated, the backtrace considers the transform function the origin of the error rather than going to the line where `map_err` was called.

Obviously, if the transform passed to `map_err` is a lambda, this is no problem. But if `map_err` is passed a function, this function is where `RUST_BACKTRACE` reports the error as originating.

**Comment by sfackler** [comment]
Could you give an example? I'm not sure I understand why there is expected to be a difference between a lambda and a function.

**Comment by mqudsi** [comment]
I was under the impression that the `Result` tuple included a backtrace. I now understand that is not the case, and certain error types include their own backtrace functionality.
