### ISSUE TITLE
rustdoc: Duplicated trait entries if re-exported from multiple modules

### ISSUE THREAD

**Issue by sdroege** [rust-lang/rust#43934]
If you generate the docs of
  https://github.com/sdroege/gstreamer-rs/tree/50a1535771d711b419eee499fb6b7c48d72edd86
there will be multiple entries linking to the same traits on the main page of the docs.

Reason here is that the traits are re-exported in lib.rs from `auto::*` and `auto::traits::*`. Removing the latter fixes it and has no negative side effects in this specific case, but having the entries there twice was confusing nonetheless.

@GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
An easy code to reproduce this error:

```rust
mod foo {
    pub use bar::*;
    pub mod bar {
        pub trait Foo {
            fn foo();
        }
    }
}

pub use foo::bar::*;
pub use foo::*;
```
