### ISSUE TITLE
Tracking issue for Unsafe Pointer Methods reform

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#43941]
This is a tracking issue for https://github.com/rust-lang/rfcs/pull/1966

@Gankro mind filling in this issue with a checklist of work items?

**Comment by Gankro** [comment]
Working on impl

**Comment by tinaun** [comment]
is there anything blocking stabilization? its been a few cycles

**Comment by Gankro** [comment]
This is probably safe to nominate for stabilization now. I would certainly love to use this.

**Comment by Mark-Simulacrum** [comment]
Nominating for stabilization. I believe the relevant methods can all be found [on this page](https://doc.rust-lang.org/nightly/std/primitive.pointer.html) of the documentation under the `pointer_methods` feature.

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

**Comment by SimonSapin** [comment]
Ping @Kimundi
