### ISSUE TITLE
Implement `std::iter::Iterator` for arrays?

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/rust#43946]
Is it possible to implement a zero-cost, safe, and doesn't-conflict-with-anything-else `std::iter::Iterator` for arrays, such that it is no longer required to called `.iter()` to get an iterator out of an array?

e.g. is it possible to use

```rust
for value in ["foo", "bar"] {
   ....
}
```

instead of needing to manually add the `.iter()`:

```rust
for value in ["foo", "bar"].iter() {
    ....
}
```

**Comment by cuviper** [comment]
You can get the same effect as `iter()` like this:

```rust
for value in &["foo", "bar"] {
   ....
}
```

This uses the `IntoIterator` implementation for `&[T]`.

It would also be nice to iterate arrays by value, which your first example would do, but this is waiting on newer compiler features -- see #32871.

**Comment by mqudsi** [comment]
If #32871 goes through, then that would moot this discussion since the plain syntax would have the (expected) move semantics. Thanks!
