### ISSUE TITLE
Mistake in Path documentation

### ISSUE THREAD

**Issue by SynthScore** [rust-lang/rust#43951]
I hope this is not a duplicate, but the description of the `.is_relative()` method for the `Path` struct states the following:

> Return false if the Path is relative, i.e. not absolute.

That "false" should become "true". Of course this doesn't really pose any problem since the mistake is pretty obvious, it's just for sake of correctness :)

**Comment by frewsxcv** [comment]
Looks like this fixed in https://github.com/rust-lang/rust/pull/43229 which can be seen in the nightly docs: https://doc.rust-lang.org/nightly/std/path/struct.Path.html#method.is_relative

Thanks for reporting though!
