### ISSUE TITLE
sozu-lib beta regression

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#43959]
[sozu-lib](https://crates.io/crates/sozu-lib) version 0.1.1 test-regressed from stable to beta ([full log](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.2/beta-2017-08-13/reg/sozu-lib-0.1.1/log.txt)):

```
Aug 16 22:18:52.510 INFO blam! ---- network::tcp::tests::mi stdout ----
Aug 16 22:18:52.511 INFO blam! 	thread 'network::tcp::tests::mi' panicked at 'could not parse address: Error { repr: Os { code: 111, message: "Connection refused" } }', /checkout/src/libcore/result.rs:860:4
Aug 16 22:18:52.511 INFO blam! note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
cc @Geal

**Comment by alexcrichton** [comment]
This has a sleep in the test for 300ms, racy test.
