### ISSUE TITLE
spiro-server beta regression

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#43956]
[spiro-server](https://github.com/tokio-hacknight/spiro-server) commit https://github.com/tokio-hacknight/spiro-server/commit/0f0991b50ffbbdee981edd02bc6afea70da87684 regressed from stable to beta ([full log](http://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.2/beta-2017-08-13/gh/tokio-hacknight.spiro-server.0f0991b50ffbbdee981edd02bc6afea70da87684/log.txt)):

```
Aug 17 13:41:58.360 INFO kablam! error[E0034]: multiple applicable items in scope
Aug 17 13:41:58.361 INFO kablam!    --> /cargo-home/registry/src/github.com-1ecc6299db9ec823/petgraph-0.2.9/src/graph.rs:421:17
Aug 17 13:41:58.361 INFO kablam!     |
Aug 17 13:41:58.361 INFO kablam! 421 |         assert!(Ix::max().index() == !0 || NodeIndex::end() != node_idx);
Aug 17 13:41:58.362 INFO kablam!     |                 ^^^^^^^ multiple `max` found
Aug 17 13:41:58.362 INFO kablam!     |
```
cc @tokio-hacknight

**Comment by est31** [comment]
I guess this is similar to #43677 , so can be closed?

**Comment by Mark-Simulacrum** [comment]
Agreed that this seems expected; closing.

**Comment by sfackler** [comment]
Yep.
