### ISSUE TITLE
statsd beta regression

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#43958]
[statsd](https://crates.io/crates/statsd) version 0.9.1 test-regressed from stable to beta ([full log](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.2/beta-2017-08-13/reg/statsd-0.9.1/log.txt)):

```
Aug 16 22:46:55.929 INFO blam! ---- client::test::test_sending_decr stdout ----
Aug 16 22:46:55.929 INFO blam! 	thread 'client::test::test_sending_decr' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20
Aug 16 22:46:55.929 INFO blam! note: Run with `RUST_BACKTRACE=1` for a backtrace.
Aug 16 22:46:55.929 INFO blam! 
```
cc @markstory

**Comment by alexcrichton** [comment]
This is a spuroiusly failing test, fails both on stable and beta.
