### ISSUE TITLE
twists beta regression

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#43955]
[twists](https://github.com/rustyhorde/twists) commit https://github.com/rustyhorde/twists/commit/4490db4201265c28c9f05f469d0d010181f65b22 regressed from stable to beta ([full log](http://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.2/beta-2017-08-13/gh/rustyhorde.twists.4490db4201265c28c9f05f469d0d010181f65b22/log.txt)):

```
Aug 17 12:50:15.558 INFO kablam! error: type `slog::NeverStruct` is private
Aug 17 12:50:15.558 INFO kablam!   --> /cargo-home/registry/src/github.com-1ecc6299db9ec823/twist-jwt-0.3.1/src/client.rs:16:5
Aug 17 12:50:15.559 INFO kablam!    |
Aug 17 12:50:15.559 INFO kablam! 16 |     stdout: Option<Logger>,
Aug 17 12:50:15.559 INFO kablam!    |     ^^^^^^^^^^^^^^^^^^^^^^
Aug 17 12:50:15.559 INFO kablam! 
```
cc @rustyhorde

**Comment by est31** [comment]
Similarly for [twisty](https://github.com/rustyhorde/twisty) ([log](http://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.2/beta-2017-08-13/gh/rustyhorde.twisty.d66226502f74e044e79e48d437c205f000e839f4/log.txt)).

**Comment by alexcrichton** [comment]
I believe the compiler/lang teams won't be reverting https://github.com/rust-lang/rust/pull/42125, so I'm going to close this regression tracker.
