### ISSUE TITLE
phage beta regression

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#43954]
[phage](https://github.com/rsaarelm/phage) commit https://github.com/rsaarelm/phage/commit/c2bbb724c8c7c66a9dc0336e43ee5b3fa7a1cbf3 regressed from stable to beta ([full log](http://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.2/beta-2017-08-13/gh/rsaarelm.phage.c2bbb724c8c7c66a9dc0336e43ee5b3fa7a1cbf3/log.txt)):

```
Aug 17 12:37:45.657 INFO kablam! error: type `sprite::WorldSprite + 'static` is private
Aug 17 12:37:45.657 INFO kablam!    --> src/gamestate.rs:129:36
Aug 17 12:37:45.657 INFO kablam!     |
Aug 17 12:37:45.657 INFO kablam! 129 |                     self.world_spr.add(Box::new(GibSprite::new(loc)));
Aug 17 12:37:45.657 INFO kablam!     |                                    ^^^
Aug 17 12:37:45.657 INFO kablam! 
```
cc @rsaarelm

**Comment by alexcrichton** [comment]
I believe the compiler/lang teams won't be reverting https://github.com/rust-lang/rust/pull/42125, so I'm going to close this regression tracker.
