### ISSUE TITLE
slate beta regression

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#43960]
[slate](https://crates.io/crates/slate) version 1.3.0 test-regressed from stable to beta ([full log](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.2/beta-2017-08-13/reg/slate-1.3.0/log.txt)):

```
Aug 16 21:51:06.438 INFO blam! ---- config::tests::it_uses_the_homedir_as_default_path stdout ----
Aug 16 21:51:06.439 INFO blam! 	thread 'config::tests::it_uses_the_homedir_as_default_path' panicked at 'assertion failed: `(left == right)`
Aug 16 21:51:06.439 INFO blam!   left: `"/home/cargobomb/.slate"`,
Aug 16 21:51:06.439 INFO blam!  right: `"/tmp/slate"`', src/config.rs:87:8
Aug 16 21:51:06.439 INFO blam! note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
cc @jhbabon

**Comment by alexcrichton** [comment]
Racy test, global state with environment variables.

**Comment by jhbabon** [comment]
Yes, sorry about that. I'll try to fix the test so it doesn't happen again.
