### ISSUE TITLE
simple-munin-plugin beta regression

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#43961]
[simple-munin-plugin](https://crates.io/crates/simple-munin-plugin) version 0.1.0 test-regressed from stable to beta ([full log](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.2/beta-2017-08-13/reg/simple-munin-plugin-0.1.0/log.txt)):

```
Aug 16 21:31:15.784 INFO blam! ---- tests::test_get_env_threshold_as_number stdout ----
Aug 16 21:31:15.784 INFO blam! 	thread 'tests::test_get_env_threshold_as_number' panicked at 'assertion failed: `(left == right)`
Aug 16 21:31:15.785 INFO blam!   left: `Some(2.5)`,
Aug 16 21:31:15.785 INFO blam!  right: `Some(10)`', src/lib.rs:134:8
Aug 16 21:31:15.785 INFO blam! note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
cc @yshryk

**Comment by alexcrichton** [comment]
Test uses environment variables, buggy test.
