### ISSUE TITLE
Tracking issue for Spurious failure for "InnoSetup not installed" on AppVeyor

### ISSUE THREAD

**Issue by kennytm** [rust-lang/rust#43985]
### Example: Operation timed out when contacting Chocolatey

Contains messages like

```
[NuGet] An error occurred while loading packages from 'https://chocolatey.org/api/v2/': The operation has timed out
InnoSetup not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "https://chocolatey.org/api/v2/"
```

### Example: Operation timed out when downloading `chocolatey-core.extension`

```
Progress: Downloading chocolatey-core.extension 1.3.1... 100%
InnoSetup not installed. An error occurred during installation:
 The operation has timed out
```

Possible cause: http://help.appveyor.com/discussions/problems/7409-chocolatey-timeout-when-installing-openssh

**Comment by kennytm** [comment]
Seems no longer happen. Will close once all linked PRs are merged.

**Comment by alexcrichton** [comment]
IIRC this isn't the first time this has happened. We should probably just mirror whatever we need locally in our S3 mirror. If someone's willing to figure out how to change the build to not hit `choco install` but hit a custom download, I'd be more than willing to upload some artifacts!
