### ISSUE TITLE
rustllvm: Use report_fatal_error instead of llvm_unreachable

### ISSUE THREAD

**Issue by rkruppe** [rust-lang/rust#44020]
Some functions in rustllvm rely on `llvm_unreachable` to catch errors. However, in release mode `llvm_unreachable` expands to the C++ compiler's equivalent of `intrinsics::unreachable()` (i.e., it's a hint to the optimizer and UB to execute). This subverts the intent of several functions, causing us to execute UB instead of crashing as intended. All uses of `llvm_unreachable` in rustllvm should be audited and replaced with `report_fatal_error` unless the potential-UB is intended.

**Comment by Mark-Simulacrum** [comment]
Nominating for prioritization. I feel like this might be somewhat severe, and as such should get P-med/P-high but I don't really know what the effects of this can be.

**Comment by rkruppe** [comment]
In practice, it's been fine so far, so it'll probably be fine for a while longer. I don't think P-high is warranted, honestly. Most uses of `llvm_unreachable` that I recall are in code that specifically translates between C++ enums and Rust enums to ensure we don't get UB from C++ adding extending their enums without us noticing. That code will actually be fine as long as the corresponding C++ enums don't change.

Besides, instead of "release mode" I should have said "without assertions" (the macro definition depends on `NDEBUG`). That is, Release+Assert builds (as nightlies currently are, IIRC?) will also crash instead of causing UB.

Still, it's an easy fix, so someone with a little bit of time (*cough*not me*cough*) should do it.

**Comment by nikomatsakis** [comment]
triage: P-medium

Would be good to do!
