### ISSUE TITLE
Tracking issue for [T]::swap_with_slice feature

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#44030]
Exposes the simd-optimized `ptr::swap_nonoverlapping` in a safe API.

Pre-stabilization todo list:

- [ ] Bikeshed: should it maybe be `swap_slice` instead?  (See discussion in #44031)

**Comment by SimonSapin** [comment]
Let’s get consensus to stabilize modulo naming:

@rfcbot fcp merge

In #44031 it seems like everyone is fine with both `swap_with_slice` and `swap_slice`, I tend to agree. Another option could be `swap_slices`, plural.

**Comment by sfackler** [comment]
The current name of swap_with_slice seems reasonable to me.
