### ISSUE TITLE
Difference in error mentioned in the book vs running the program

### ISSUE THREAD

**Issue by kamathe** [rust-lang/rust#44035]
Running a small Rust snippet from "The Rust Programming Language" Book

https://doc.rust-lang.org/book/second-edition/ch03-03-how-functions-work.html

As per docs the following error is expected

Running this code produces an error, as follows:

```
error[E0308]: mismatched types
--> src/main.rs:7:28
  |
7 |   fn plus_one(x: i32) -> i32 {
  |  ____________________________^
8 | |     x + 1;
9 | | }
  | |_^ expected i32, found ()                     <<<<<<<<<<<<<<<<<<
  |
  = note: expected type `i32`                      <<<<<<<<<<<<<<<<<
             found type `()`
help: consider removing this semicolon:
--> src/main.rs:8:10
  |
8 |     x + 1;
  |
```

Actually running this on the system, notice how the "expected" is reversed
In the Book example it says "expect i32, found()" which is correct
Whereas on the system the error says "expected (), found i32" which is wrong

```
error[E0308]: mismatched types
--> src/main.rs:6:28
  |
6 |   fn plus_one(x: i32) -> i32 {
  |  ____________________________^
7 | |     x + 1;
8 | | }
  | |_^ expected (), found i32                                                                      <<<<<<<<<<<<<<<
  |
  = note: expected type `()`                                                                          <<<<<<<<<<<<<<<
             found type `i32`
help: consider removing this semicolon:
--> src/main.rs:7:10
  |
7 |     x + 1;
  |          ^
```

Version Information
=============

rustc --version
rustc 1.18.0 (03fc9d622 2017-06-06)

cargo --version
cargo 0.19.0 (28d1d60d4 2017-05-16)

**Comment by Mark-Simulacrum** [comment]
cc @steveklabnik -- should this be on the book repo?

**Comment by kamathe** [comment]
@Mark-Simulacrum seems book output is correct, whereas rustc/cargo output seems incorrect  ?
I am not sure though

**Comment by shepmaster** [comment]
This appears to be an issue that was already fixed between Rust 1.18.0 and Rust 1.19.0. Sorry for the inconvienience, but please consider upgrading 😸 

```
charybdis:tmp shep$ rustc +1.18.0 what.rs
error[E0308]: mismatched types
 --> what.rs:7:28
  |
7 |   fn plus_one(x: i32) -> i32 {
  |  ____________________________^
8 | |     x + 1;
9 | | }
  | |_^ expected (), found i32
  |
  = note: expected type `()`
             found type `i32`
help: consider removing this semicolon:
 --> what.rs:8:10
  |
8 |     x + 1;
  |          ^

error: aborting due to previous error
```

```
charybdis:tmp shep$ rustc +stable what.rs
error[E0308]: mismatched types
 --> what.rs:7:28
  |
7 |   fn plus_one(x: i32) -> i32 {
  |  ____________________________^
8 | |     x + 1;
9 | | }
  | |_^ expected i32, found ()
  |
  = note: expected type `i32`
             found type `()`
help: consider removing this semicolon:
 --> what.rs:8:10
  |
8 |     x + 1;
  |          ^
```

**Comment by kamathe** [comment]
Thanks @shepmaster if possible could you please point me to the pull request which was used to fix this, i am curious as to how things are fixed

**Comment by shepmaster** [comment]
> point me to the pull request

I don't know it offhand, sorry. You can fetch the Rust repository and start with `git log 1.18.0..1.19.0 --no-merges`. There's only 800 or so commits to read through.
