### ISSUE TITLE
rust-std component filled with unnecessary rlibs

### ISSUE THREAD

**Issue by retep998** [rust-lang/rust#44037]
I'm pretty sure over half the rlibs in this list are completely useless. Normal crates would only need libstd and its dependencies, while plugins don't use rlibs at all.
![](http://i.imgur.com/7bWZqzz.png)

**Comment by Mark-Simulacrum** [comment]
@alexcrichton We can certainly remove these rlibs, but I think they are necessary for something -- maybe regular crates with `extern crate rustc_serialize;` or something like that?

**Comment by alexcrichton** [comment]
These are needed for plugins, when you `extern crate proc_macro` it needs to transitively load all of that crate's dependencies, even if they're rlibs. In this case that pulls in some crates.io rlibs.

Everything that's *not* transitively a dependency of `proc_macro` is then still required for unstable plugins, so closing.

**Comment by retep998** [comment]
But `proc_macro` is only available as a dylib, not an rlib, which means transitive dependencies are being linked in as dylibs too, which means those rlibs definitely are not needed for `proc_macro`! Ditto for plugins, they pull in everything as dylibs, not rlibs!
