### ISSUE TITLE
Fill out missing Android runtime functions

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#4405]
`src/rt/rust_android_dummy.cpp` contains a bunch of empty stubs for functions that don't exist in bionic.

**Comment by lahwran** [comment]
What does this affect? How is android code limited by this?

**Comment by alexcrichton** [comment]
@lahwran we [still have](https://github.com/rust-lang/rust/blob/master/src/rt/rust_android_dummy.c) a file of stubs and presumably if you use one of those functions you're going to get... some interesting results!

**Comment by lahwran** [comment]
yes, but what actually uses those in the rust stdlib? what should I avoid?

**Comment by huonw** [comment]
These files are gone (https://github.com/rust-lang/rust/pull/30175 & https://github.com/rust-lang/rust/pull/30529), closing.
