### ISSUE TITLE
Improve documentation for `TcpStream::set_nonblocking`

### ISSUE THREAD

**Issue by mbrubeck** [rust-lang/rust#44050]
These docs currently just refer to POSIX and Win32 APIs, without explaining what they do (or even linking to docs for the corresponding platform APIs):

https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.set_nonblocking

I'd like to have more information here about how other TcpStream methods change their behavior after calling this, possibly with an example.

**Comment by frewsxcv** [comment]
I'd be happy to make the changes, though I actually don't know what the effects of using `set_nonblocking` are. If anyone knows, would be great if you could share

**Comment by tbu-** [comment]
This will result in `read`, `write`, `recv` and `send` operations not blocking, i.e. immediately returning from their calls. If the IO operation could be completed correctly, no further action is required. If it could not, `EAGAIN` or `EWOULDBLOCK` are returned on Unix platforms and `WSAEWOULDBLOCK` is returned on Windows. All of these are mapped to `io::ErrorKind::WouldBlock`, so on the Rust side of the things, you can simply check whether the return value of the IO operation has kind `io::ErrorKind::WouldBlock`, and in this case take the appropriate action.

**Comment by frewsxcv** [comment]
Opened a PR for TCP methods: https://github.com/rust-lang/rust/pull/45227

I'll do another PR for the UDP instance of this in a follow-up PR when I have some more time.
