### ISSUE TITLE
parameterized index for RawVec

### ISSUE THREAD

**Issue by dobkeratops** [rust-lang/rust#44068]
Suggestion:-

could we parameterise the 'RawVec' with an index/size type, to make allocators for limited sizes easier - there are many scenarios (clustered data, and memories between bit-sizes*) where a limited number of bits are useful. (for example 'number of bones' being 8 or 16 bits whilst 'number of vertices' might be 16 or 32bits).

Even Further customisation might be possible with policy objects, e.g. controlling how capacity is stored/calculated (how about a growable vector that only allows power-of-2 capacities, hence it only needs a byte to store a shift value..).. but thats too big a change right now.
Another issue is usize vs  isize, bjarne and others now think 'unsigned indices' are a mistake.

My full intent is to make a parameterized replacement for ```Vec<T>``` (ie. ```Vec<T,INDEX=usize>``` ), but just having this internal utility generalised would simplify rolling that 'front end' with less cut-paste repetition, and without changing the user-facing interface in the stdlib (even then, having the default being usize should mean no visible/breaking change)

Proposed change:-
```
#[allow(missing_debug_implementations)]
pub struct RawVec<T, A: Alloc = Heap, INDEX=usize> {
    ptr: Unique<T>,
    cap: INDEX,
    a: A,
}
// follow through in all code working on RawVec, 
// some further thought maybe required e.g. panics for capacity overflow?
```

the type-param here is called 'INDEX' but it might also be SIZE.. not sure which the clearest name is.

r.e. 'memories between bit sizes': I'm alluding to the phenomenon that made intel do 'segmentation' in the middle ground between 16 and 32bits. 
Similarly, today, we have many devices with memories in the range 4-32gb of RAM for which 64bits of address or index are overkill, 32bits are insufficient, but 32bits *as a scaled Index* is easily enough.

 (e.g. it's very unlikely you'd fill the whole of that with one array of objects under 16bytes each, so a 32bit index is fine. in graphics, you typically fill memory with 2d information (textures).. (you'll never have a 8billion x 1 pixel texture) and vertices (~16+ bytes each),and you'd never fill the whole of memory with just one object (in that rare scenario , if it's parameterized you can choose i64). A lot of data is explicitely clustered into chunks to reduce the bit-requirement of indexing (and provide greater locality)... there is synergy between these (greater locality = reduced address bits)

**Comment by leonardo-m** [comment]
> Another issue is usize vs isize, bjarne and others now think 'unsigned indices' are a mistake.

Bjarne is talking about C++. The Rust situation is different because it has stronger typing, you can't assign signed<->unsigned.

**Comment by dobkeratops** [comment]
Note I am suggesting keeping the default as usize.

> you can't assign signed<->unsigned.

you still get signed/unsigned warnings in C++.
the same issue applies: having to switch between signed and unsigned when dealing with index arithmetic. symetry between addition and subtraction.

the use cases of a full 64bits of index don't justify the extra cost of dealing with with two types and flipping between them . I'm not the only person to note this.

Are you disagreeing with my use case of 32bit indices on a 64bit system? if so have you any idea how infuriating this is? - just because YOU don't need it, it doesn't mean the need doesn't arise. if you are serious about Rust being a viable replacement for C/C++, you need to handle all the niches.

Every project i've worked on has required shaving off every last byte toward the end. You only use a 64bit index if you absolutely know you're going to need more than 4billion items, otherwise it's a waste.

**Comment by leonardo-m** [comment]
> you still get signed/unsigned warnings in C++, and many people choose 'warnings=errors'.

And lot of people do not, and don't use a lint. Warnings like this are signs of a design mistake of the language.

> Are you disagreeing with my use case of 32bit indices on a 64bit system?

I am not. I think in Rust arrays/slices/vectors should accept u8/u16/u32/usize as indexes (and perhaps u64 too on 64 bit systems only).

**Comment by kennytm** [comment]
> (and perhaps u64 too on 64 bit systems only)

Wouldn't this be a portability hazard? This is the whole reason why we don't have `impl From<u32> for usize` because 16-bit target exists.

**Comment by dobkeratops** [comment]
> Wouldn't this be a portability hazard?

perhaps; in the use cases I have in mind the choice may well be platform (or 'generation') specific (e.g. choosing an optimum cluster size, which has indeed varied between generations). I'm not suggesting anything that will introduce 'ad-hoc conversions'.. just the ability to control what type is expected and propagated, and defaulting to current behaviour.

**Comment by arielb1** [comment]
> The use cases of a full 64bits of index don't justify the extra cost of dealing with with two types and flipping between them . I'm not the only person to note this.

Using unsigned integers is the preferred Rust style for dealing with counts of things (that obviously can't be negative). This ensures that any accident that creates a negative number causes a panic in debug mode, and avoids any API ambiguities about the handling of negative numbers.

**Comment by leonardo-m** [comment]
@kennytm > Wouldn't this be a portability hazard?

A compile-time error could be better than bug-prone "as" casts.

@dobkeratops  > The use cases of a full 64bits of index don't justify the extra cost of dealing with with two types and flipping between them . I'm not the only person to note this.

Later in this thread I've explained that it's not just the u64. I think it's perhaps a good idea to allow array/slices/vectors indexes as u8/u16/u32/usize and perhaps u64 too.

**Comment by oyvindln** [comment]
Are there barriers to implementing something like this as a library at first at the moment? (Allocation?) If there is maybe those need to be explored first.

This does seem like a feature that could be useful in some situations, so at least having the ability to implement it sounds reasonable.

**Comment by dtolnay** [comment]
I agree with @oyvindln and would prefer to see this idea explored in a library on crates.io. `RawVec` is useful for some data structures but is opinionated in many ways and not intended to solve every use case that involves allocating contiguous data.

> if you are serious about Rust being a viable replacement for C/C++, you need to handle all the niches.

If you run into barriers implementing something like this outside of the standard library, please file issues for those. Rust absolutely is serious about making it possible to implement something like `RawVec` parameterized over index type.
