### ISSUE TITLE
Rustdoc - Section Symbol in Wrong Location on Impls w/ Where Clauses

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#44120]
Real time example: Hover over [this impl on vec](https://doc.rust-lang.org/nightly/std/vec/struct.Vec.html#impl-1).

The section symbol appears on its own line instead of somewhere on the impl itself.

cc @QuietMisdreavus @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Hum... Do you have an idea since when? It could help to understand where the issue is coming from instead of just fixing it.

**Comment by Havvy** [comment]
I don't know when it started. I don't remember the last time I looked at the nightly docs. Tuesday was the latest possible time, but 🤷‍♂️.

**Comment by kennytm** [comment]
@GuillaumeGomez  The § thing doesn't appear in beta, so likely a bug in the initial implementation (I guess #43747).

**Comment by ollie27** [comment]
#43979 added the § for impls.

**Comment by GuillaumeGomez** [comment]
Thanks @ollie27! Taking a look this evening.
