### ISSUE TITLE
CI is bootstrapping rustc too many times on cross builds

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#44132]
I just looked at a [recent build](https://travis-ci.org/rust-lang/rust/jobs/269265187), specifically for `dist-s390x-linux`, which was taking much longer than expected! I specifically noticed that the compiler is getting bootstrapped more than I would have expected.

All we should be building is a stage0 x86_64, stage1 x86_64, and stage1 s390x. Instead though we also see:

* `Building stage2 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)`
* `Building stage0 compiler artifacts (x86_64-unknown-linux-gnu -> s390x-unknown-linux-gnu)`

That's two whole extra compiler we shouldn't need!

**Comment by alexcrichton** [comment]
cc @Mark-Simulacrum, @kennytm

**Comment by kennytm** [comment]
From the log, the compiler is built 5 times:

1. Build stage0-rustc (x64 → x64) at 00:07:28, this is normal.
2. Build stage1-rustc (x64 → x64) at 00:22:26, this is normal.
3. **Build stage2-rustc (x64 → x64) at 00:45:54**, required to build the stage2 rustdoc (x64) to document libstd at stage2. Maybe we should document at stage1? Does it work when `rustdoc` starts to depend on proc-macro crates?
4. Build stage1-rustc (x64 → s390x) at 01:09:38, this is normal.
5. **Build stage0-rustc (x64 → s390x) at 01:29:17**, seems to be needed to extract the error index (s390x) judging from the step immediately after??

**Comment by alexcrichton** [comment]
Yeah the (3) and (5) in your list there shouldn't be necessary, although this may take some rearchitecting of the build slightly to get that working.

**Comment by Mark-Simulacrum** [comment]
Yeah, I've been meaning to work on having the build less split up into stages. Most of the things we build don't care about what stage they're associated with but it's also not always clear what stage and host triple they want to be associated with. It's going to require some thought and work, but I hope to get a plan soon.
