### ISSUE TITLE
Standard library masks away bits in permissions struct

### ISSUE THREAD

**Issue by tmerr** [rust-lang/rust#44147]
## Behavior

On linux, `mkdir mydir`, `chmod 2777 mydir` then run:

```
fn main() {
  let path = "mydir";
  let perms = std::fs::metadata(path).unwrap().permissions();
  std::fs::set_permissions(path, perms).unwrap();
}
```

This changes the permissions of `mydir` to `777`. Is this expected?

## The cause

`Metadata.permissions()` masks away everything other than the lower 3 triads when it calls out to this code:

https://github.com/rust-lang/rust/blob/d2d50691aadfb9e25c8c3d9a1d71a8c79607c5b2/src/libstd/sys/unix/fs.rs#L95-L97

Then `std::fs::set_permissions` sends these mode bits into into chmod which considers four triads, not three. Possibly useful references: [chmod](http://pubs.opengroup.org/onlinepubs/9699919799/functions/chmod.html) and [mode_t](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_stat.h.html)

Should we change Metadata.permissions to preserve that triad, maybe by masking with `0o7777` instead of `0o777`?

**Comment by tmerr** [comment]
I guess the solution depends on whether Unix's std::fs::Permissions is supposed to care about 9 bits or 12 (this is not an implementation detail since it's exposed to the programmer via `Permissions.mode()` of PermissionsExt).  @alexcrichton do you have any thoughts on this?

**Comment by sfackler** [comment]
It seems to me like we should extend the mask to the full 12 bits.

**Comment by alexcrichton** [comment]
Seems reasonable to me to avoid masking where it makes sense!
