### ISSUE TITLE
change `define_maps!` syntax to include `fn` preceding `$name`

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#44161]
In this macro:
https://github.com/rust-lang/rust/blob/faf477a8c232d0442d16a4025f49d3ae1519131e/src/librustc/ty/maps.rs#L566-L569

This will make it easier to grep for a symbol without knowing whether it is a regular function or a query.

Also consider changing the name from `define_maps!` to `define_queries!` (and the module name as well?).

As discussed on IRC with @eddyb and @nikomatsakis.

**Comment by durka** [comment]
There is this `$modifiers` thing, but it seems to be always empty in the current usage of `define_maps!`. Is it an artifact of history that should be removed?

**Comment by nikomatsakis** [comment]
@durka my expectation is still that we *will* use it, that's why it's not been removed yet, but I'm also ok removing it and adding it back later when we want it.
