### ISSUE TITLE
Support `?` operator in `for` loops

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#44170]
Should the following be allowed?

```rust
for item? in my_iter {
    ...
}
```

Every now and then I encounter the need to iterate over `Result`s and end up having to write the following, which isn't onerous but is not ergonomic:

```rust
for item in my_iter {
    let item = item?;
    ...
}
```

**Comment by ids1024** [comment]
This has been requested before: https://github.com/rust-lang/rfcs/issues/2012

**Comment by estebank** [comment]
@ids1024 thanks for linking to it! I'll close this ticket in favor of that RFC.
