### ISSUE TITLE
Stable documentation contains broken links to nightly documentation

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#44175]
On the stable [std::fmt::Debug](https://doc.rust-lang.org/stable/std/fmt/trait.Debug.html#implementors) page, under implementors, there's a bunch of links to the nightly documentation of the in-tree rand crate. What's more, the links don't work.

This first appeared in the [1.16 docs](https://doc.rust-lang.org/1.16.0/std/fmt/trait.Debug.html#implementors). Problem still exists in [beta](https://doc.rust-lang.org/beta/std/fmt/trait.Debug.html#implementors) as of the 1.20 release candidate.

**Comment by kennytm** [comment]
Duplicate of #43701.

**Comment by shepmaster** [comment]
Closing as duplicate
