### ISSUE TITLE
Unclear error message on trailing semicolon in assignment block

### ISSUE THREAD

**Issue by zmanian** [rust-lang/rust#44173]
Consider this case
```rust

fn main() {

    let x = {
        println!("foo");
        "bar";
    };
    println!("{}",x)
}

```

this results in the type checking error.

```
error[E0277]: the trait bound `(): std::fmt::Display` is not satisfied
 --> src/main.rs:8:19
  |
8 |     println!("{}",x)
  |                   ^ `()` cannot be formatted with the default formatter; try using `:?` instead if you are using a format string
  |
  = help: the trait `std::fmt::Display` is not implemented for `()`
  = note: required by `std::fmt::Display::fmt`

```

when the actual error is the trailing semicolon in `"bar";`

This is similar to #30497 but that handles the case of a function type signature not an assignment.

@Manishearth mentioned it might be easiest to introduce a lint. Looking for mentorship on contributing a fix.

**Comment by Manishearth** [comment]
The way I see it there are two ways to go around this.

One is to introduce a function that will check if a def is an assignment and check if it's of this kind, and introduce it to every type error that this may affect (a lot of them).

Alternatively, just introduce an early lint that catches all assignments to a block evaluating to `()`. I don't think there are any good use cases of this outside of macros (which we can macro-check for).

 I can mentor this, but AIUI we're pretty strict about adding lints. (@nrc ?)

We could make this a clippy lint but this particular thing is a major newbie stumbling block and should probably be built in.

**Comment by oli-obk** [comment]
We already have this lint in clippy: https://github.com/rust-lang-nursery/rust-clippy/wiki#let_unit_value

So it just needs to be moved to rustc

**Comment by Manishearth** [comment]
That lint's not useful here, it's post typecheck.

We need an early lint that checks the AST.
