### ISSUE TITLE
There is a typo in the document

### ISSUE THREAD

**Issue by zuijiaoluo** [rust-lang/rust#44177]
This is not a big bug, but we hope to be rigorous. Please don’t take offense.
![image](https://user-images.githubusercontent.com/22735208/29859180-6aa95e88-8d93-11e7-9401-6c13f53a7ceb.png)

**Comment by kennytm** [comment]
The typo is in https://www.rust-lang.org/zh-CN/faq.html.

The issue should better be filed on [rust-lang/rust-www](https://github.com/rust-lang/rust-www/issues). Or even better, you could simply edit https://github.com/rust-lang/rust-www/blob/master/zh-CN/faq.md and submit a pull request there 😄.

**Comment by steveklabnik** [comment]
Yup! @zuijiaoluo thank you for pointing this out, but this is the wrong place, as @kennytm mentions. A bug over there or a PR would be great, thank you!
