### ISSUE TITLE
Bad output of variants in Rustdoc

### ISSUE THREAD

**Issue by Keats** [rust-lang/rust#44180]
See https://docs.rs/pest/1.0.0-beta.7/pest/enum.Error.html for example and a screenshot below

![2017-08-30-183517_758x350_scrot](https://user-images.githubusercontent.com/680355/29865992-fecdef20-8db1-11e7-9d74-8ae5c5d5b2a1.png)

This happens on both Chrome and Firefox. The alignment between the [-] and the text is also off but it could be due to other CSS issues as the [+] is correctly aligned.

**Comment by steveklabnik** [comment]
Which version of `rustdoc` did you use to generate these docs?

**Comment by kennytm** [comment]
This should be fixed in #43862...

**Comment by Keats** [comment]
Ah I only looked at the doc.rs output, I generated docs on nightly and it looks fine. On stable (1.19) the output is different but working as well.
Sorry for the noise!
