### ISSUE TITLE
{MutexGuard, RwLockReadGuard, RwLockWriteGuard}::map

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/rust#44189]
Currently, the RefCell borrow guards have a function called [`map`](https://doc.rust-lang.org/nightly/std/cell/struct.RefMut.html#method.map) which allows you to transform a borrow of a whole struct to a borrow of one of its fields (or of some related reference with the same lifetime). Would it be possible to add these methods to Mutex and RwLock?

**Comment by sfackler** [comment]
It's come up before, but is unsound: https://github.com/rust-lang/rust/pull/30834#issuecomment-180284290.

**Comment by QuietMisdreavus** [comment]
Ah, curses. Thanks for the link; i'll go ahead and close this out then.

**Comment by jonas-schievink** [comment]
The linked comment only says that `MutexGuard::map` would be unsound, not the `RwLock*::map` methods (which I could use right now) - can you reopen, @QuietMisdreavus?

**Comment by jonas-schievink** [comment]
Ah I see this was already discussed in https://github.com/rust-lang/rust/issues/27746#issuecomment-180458770, so nevermind

**Comment by xmo-odoo** [comment]
> Ah I see this was already discussed in [#27746 (comment)](https://github.com/rust-lang/rust/issues/27746#issuecomment-180458770), so nevermind
> 
> EDIT: That said, `map` could simply return a `MappedMutexGuard` or `MappedRwLock*Guard` to fix the soundness problems.

For any reader stumbling upon this issue, that seems to be the option `parking_lot` uses: its rw guards are mappable and return a dedicated `MappedGuard` structure.
