### ISSUE TITLE
rustdoc doesn't render constness of bare functions on nightly

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/rust#44187]
On today's nightly docs for `std::mem::size_of`:

![image](https://user-images.githubusercontent.com/5217170/29883676-a2ead6f4-8d76-11e7-9207-c05aa4bece97.png)

But if you click `[src]`, you can see that it's supposed to be const:

![image](https://user-images.githubusercontent.com/5217170/29883701-b1fcc31e-8d76-11e7-8230-8ea2e6f0f19f.png)

Rustdoc is supposed to print the constness of functions on nightly. It currently works for associated functions (e.g. `AtomicBool::new`) but bare functions like `size_of` are currently not working.

**Comment by GuillaumeGomez** [comment]
Taking a look.
