### ISSUE TITLE
Add lint suggestion for integer to char cast

### ISSUE THREAD

**Issue by mattico** [rust-lang/rust#44193]
Currently, code like `0xEF8888 as char` will give a generic `warning: literal out of range for u8` warning. It would be helpful to add a suggestion to use [from_u32](https://doc.rust-lang.org/std/char/fn.from_u32.html).

Inspired by this reddit post: https://www.reddit.com/r/rust/comments/6x1us8/literal_out_of_range_for_u8/

**Comment by oli-obk** [comment]
duplicate of #44201

**Comment by mattico** [comment]
Yep!
