### ISSUE TITLE
incremental: Hide lang_items behind a query in the TyCtxt

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#44190]
Right now this is calculated and passed into the TyCtxt, let's convert this to a query and then calculate it on-demand!

This'll also allow us to remove `CrateStore::{lang_items, missing_lang_items}` and convert them to queries as well.

**Comment by nikomatsakis** [comment]
cc me

**Comment by alexcrichton** [comment]
I've implemented this on a local branch, will post it soon
