### ISSUE TITLE
Remove stage0 allocator logic from MSVC in libstd

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#44217]
We're updating the bootstrap compiler in https://github.com/rust-lang/rust/pull/44154 which attempted to remove the MSVC-specific logic [here](https://github.com/rust-lang/rust/blob/97b01abf3d222523d0db4f79c13ed45e7fef27e3/src/libstd/lib.rs#L320-L334) (added in https://github.com/rust-lang/rust/pull/43589) but I believe that caused [this failure](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.4481/job/b40c65097i0444tq).

No time to debug just yet, but we should remove this one day!

**Comment by alexcrichton** [comment]
cc @aidanhs

**Comment by aidanhs** [comment]
Well beta-2017-08-29 does seem to have the code in it, so...hmm - https://github.com/rust-lang/rust/blob/198109911681d6dc947bb1b05e77751733198f57/src/librustc_trans/back/symbol_export.rs#L87-L93

**Comment by alexcrichton** [comment]
Oh I should also clarify that I'm not even sure this is the actual bug. I'm likely to close this after further investigation of updating the bootstrap compiler...

**Comment by alexcrichton** [comment]
Ok opening a new bug

**Comment by alexcrichton** [comment]
I opened up https://github.com/rust-lang/rust/issues/44236, I think this *may* mean that `__rust` prefixes are the wrong ones and we're supposed to use the `__rg` ones, but there's no real motivation to fix this immediately so I'm not going to investigate further.
