### ISSUE TITLE
Receiver::recv_timeout() returns instantly when duration overflows

### ISSUE THREAD

**Issue by vandenoever** [rust-lang/rust#44216]
When Receiver::recv_timeout receives certain large values, it returns immediately. This is probably due to an overflowing value. Instead, when there is overflow, it should fall back to Receiver::recv.

```rust
use std::sync::mpsc::Receiver;
use std::time::Duration;

let max = Duration::from_secs(u64::max_value());
receiver.recv_timeout(max);
```

Instant should probably not overflow like this:

```rust
let now = Instant::now();
let end_of_time = Instant::now() + Duration::from_secs(u64::max_value());
println!("{:?}", now);
println!("{:?}", end_of_time);
println!("did we pass end of time? {}", now > end_of_time);
```

**Comment by kennytm** [comment]
The Instance addition should panic on overflow (try `u64::max_value()/2` instead of `u64::max_value()`). It seems there is some bug causing the panic not trigger.

**Comment by vandenoever** [comment]
u64::max_value()/2 panics. u64::max_value()/4 is fine.

**Comment by kennytm** [comment]
Oops.

https://github.com/rust-lang/rust/blob/97b01abf3d222523d0db4f79c13ed45e7fef27e3/src/libstd/sys/unix/time.rs#L43-L45

If only we have `checked_cast`...

**Comment by vandenoever** [comment]
Why is it casting to i64?

**Comment by kennytm** [comment]
@vandenoever An `Instant` can represent time before the epoch, thus the number of seconds is a signed value. Arithmetic in Rust can only be performed between values of the same type, so the duration is cast to `i64`.

**Comment by vandenoever** [comment]
@kennytm I see. And the other cast `self.t.tv_sec as i64` is not usually a cast because tv_sec is time_t which is (usually?) i64.
