### ISSUE TITLE
Switch the 'rls' component in the manifest to 'rls-preview'

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#44226]
This is a tracking issue for work we should do in a few weeks time. Rustup recently gained the ability to support renames of components seamlessly. We're waiting for that support to propagate.

Once that's propagated (a few weeks from now) we'll change the name of the `rls` component to `rls-preview` on the nightly channel via a rename in the manifest.

I'm tagging this as a regression so we don't forget about it, but it's not actually a regression!

cc @nrc

**Comment by Mark-Simulacrum** [comment]
@alexcrichton @nrc -- Any movement on this? If not, release is next week -- this needs to be prioritized.

**Comment by nrc** [comment]
This is done.
