### ISSUE TITLE
Spurious failure with stalled macOS builds (specifically the `check i686-apple-darwin` job)

### ISSUE THREAD

**Issue by kennytm** [rust-lang/rust#44221]
First seen on 2017 Aug 31st in:

* https://github.com/rust-lang/rust/pull/44129#issuecomment-326335465 (check i686)
* https://github.com/rust-lang/rust/pull/44171#issuecomment-326358984 (check i686)
* https://github.com/rust-lang/rust/pull/44129#issuecomment-326374205 (check i686 again)

**Symptom:** 

The job just stopped in the middle with no output in 30 minutes without any reason. End of the log looks like:

```
[00:40:25] [m[m[32m[1m   Compiling[m rustc_llvm v0.0.0 (file:///Users/travis/build/rust-lang/rust/src/librustc_llvm)
[00:40:31] [m[m[32m[1m   Compiling[m flate2 v0.2.19
[00:40:34] [m[m[32m[1m   Compiling[m rustc_errors v0.0.0 (file:///Users/travis/build/rust-lang/rust/src/librustc_errors)



No output has been received in the last 30m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

Status of Travis and MacStadium are both green on 2017 Aug 31st. Not sure if unreported upstream issue or something else.

**Comment by ssbarnea** [comment]
Well, I was hit by the same issue using `brew upgrade` ....

**Comment by alexcrichton** [comment]
I talked with Travis yesterday and got:

> both your mac pros are healthy, once has two VMs and the other has three 
> both our networking and SAN stuff is hitting some limits, so it may be one of those, unfortunately. 

which makes me think it's probably upstream issues and we don't really have a way to work around :(

**Comment by kennytm** [comment]
Not sure if Travis CI is aware of this, but the problem is very likely in the connection to the log collector or RabbitMQ, not the VMs themselves (yeah not something we can fix).

I'm currently monitoring https://travis-ci.org/rust-lang/rust/jobs/272020017, and logs are being written out if you "Follow log" at the web interface, but opening it again the logs will be all gone.

![screenshot_2017-09-05 20 30 20_gfnuzu-fs8](https://user-images.githubusercontent.com/103023/30061306-747578f8-9279-11e7-91bc-b7ac7722173e.png)

**Comment by kennytm** [comment]
Incident notice: https://www.traviscistatus.com/incidents/2f0443bbphld

> We’re investigating an increased rate of internal restarts of macOS builds, resulting in longer boot times for both public and private repositories. This has resulted in an increased backlog for macOS builds at travis-ci.org 
>
>  Sep 6, 09:00 UTC
