### ISSUE TITLE
BoxColliders does not support negative scale or size.

### ISSUE THREAD

**Issue by PryMary** [rust-lang/rust#44245]
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "assets/prefabs/deployable/repair bench/repairbench_deployed.prefab"

**Comment by sfackler** [comment]
This is the issue tracker for the Rust programming language, not the Rust video game. You may be looking for http://jira.facepunch.com/browse/RUST-1708.

**Comment by kennytm** [comment]
Hello. This is the issue reporter for [a programming language called Rust](http://rust-lang.org/). It seems you are reporting bugs about [the game Rust](http://playrust.com/), which we can't help. If the bug is about the Oxide mod, you may get support from http://oxidemod.org/.

**Comment by PryMary** [comment]
woops my bad... cheers google!
