### ISSUE TITLE
`f32::from_str` and `f64::from_str`: parser returned error on just a '.' (a dot)

### ISSUE THREAD

**Issue by kamarkiewicz** [rust-lang/rust#44242]
Hi! I found a mismatch between documentation and behavior of stable Rust.
When I tried to parse a string equal `"."` `f32/f64::from_str` returned `Err(...)` instead of `Ok(0.0)`, as it states in official documentation [here](https://doc.rust-lang.org/std/primitive.f64.html).

### Tests (based on mentioned doc)
`f32`: https://play.rust-lang.org/?gist=c7495df140e0991473fb914b0b468b34&version=stable
`f64`: https://play.rust-lang.org/?gist=c319d2f10762767b9983907cb9d7f2dc&version=stable

**Comment by rkruppe** [comment]
This is a docs issue. The libs team decided in https://github.com/rust-lang/rust/issues/30344 to consider `"."` an invalid input instead of parsing it as 0.

**Comment by steveklabnik** [comment]
I'd be happy to mentor anyone who wants to fix this, it'd be a great first bug!

**Comment by mcomstock** [comment]
I'd like to work on this.

**Comment by Freyskeyd** [comment]
@mcomstock are you fixing this?

**Comment by mcomstock** [comment]
Yeah! Sorry for the delay.

**Comment by Freyskeyd** [comment]
@mcomstock ok let me know if you need help
