### ISSUE TITLE
TokenStream should implement Extend

### ISSUE THREAD

**Issue by nox** [rust-lang/rust#44241]
```rust
impl<T> Extend<T> for TokenStream
where
    T: Into<TokenStream>;
```

This would allow https://github.com/servo/servo/pull/18340 to be written in a slightly better way.

**Comment by Arnavion** [comment]
https://github.com/rust-lang/rust/pull/53304 added `Extend<TokenTree>` and `Extend<TokenStream>`

**Comment by SimonSapin** [comment]
Closing as I think https://github.com/rust-lang/rust/pull/53304 would be good enough for https://github.com/servo/servo/pull/18340. @nox, feel free to re-open or comment if you think the more generic form would still be useful.
