### ISSUE TITLE
Simplify and optimize FileMap's line/column mapping computation.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#44264]
Right now this is done while lexing: https://github.com/rust-lang/rust/blob/f861b6ee46465097eec266c160ac53e230df7cf0/src/libsyntax/parse/lexer/mod.rs#L423-L435

While that may seem like it avoids going twice over the file contents, lexing is *slow*, while newline and non-width-1 (which is also improperly computed by means of multi-byte characters, instead of the `unicode-width` library) character finding can be optimized one way or another.

Cleaning this up would get rid of hacks such as the `save_new_lines_and_multibyte` flag in the code linked above and having to reimplement this in anything else using `CodeMap` outside of libsyntax.

**Comment by wesleywiser** [comment]
I think @michaelwoerister made these changes in #50997. @eddyb do you think this can be closed or is there still more to do?

**Comment by michaelwoerister** [comment]
I think this should be pretty much fixed. Good catch, @wesleywiser!
