### ISSUE TITLE
`HashMap` should not take ownership of its keys

### ISSUE THREAD

**Issue by Binero** [rust-lang/rust#44271]
Right now, to insert a new value into a `std::collections::HashMap`, one _must_ transfer ownership of the key to the map. The map however does not seem to require ownership of the key. 

The `HashMap` does not keep around a copy of the key however. It only stores its hash. This means that there is no way to get the key out of the `HashMap` again. 

For example, take the signature of the insert method:

```rust
fn insert(&mut self, k: K, v: V) -> Option<V>
```

If the value is updated, it returns the old value, thus giving the user ownership of said value again. The key however, is lost forever. There is no way to get it back.

**Comment by jmesmon** [comment]
HashMap does store the key, and it can be retrieved using `HashMap::entry()` and `HashMap::keys()`.

One can use the `HashMap::entry()` api to retrieve the stored key on removal as well with `remove_entry`(https://doc.rust-lang.org/std/collections/hash_map/struct.OccupiedEntry.html#method.remove_entry).

That said, getting an entry current requires another owned key to pass to `entry()`. There is an [rfc](https://github.com/rust-lang/rfcs/pull/1769) working on fixing that.

**Comment by Binero** [comment]
Aha, my bad. I got confused just now because surely it must store the key SOMEWHERE, otherwise the HashMap wouldn't be able to check within a bucket. The entry is exactly what I was looking for, thanks a ton!
