### ISSUE TITLE
Types from `syntax` leaked into `std` docs

### ISSUE THREAD

**Issue by mcarton** [rust-lang/rust#44289]
The documentation for [`std::convert::Into`](https://doc.rust-lang.org/std/convert/trait.Into.html) contains some types from the `syntax` crate that should not be there:

```rust
impl Into<Option<P<PathParameters>>> for AngleBracketedParameterData
impl Into<Vec<Annotatable>> for Annotatable
impl<T> Into<Vec<T>> for ThinVec<T>
impl<T> Into<Vec<T>> for P<[T]>
```

all of those are dead links (eg. for [`syntax::ptr::P`](https://doc.rust-lang.org/nightly/syntax/ptr/struct.P.html)).

**Comment by ollie27** [comment]
This was fixed by #43736 see https://doc.rust-lang.org/nightly/std/convert/trait.Into.html#implementors

**Comment by mcarton** [comment]
Ah, nice. Just need to wait for it to go to stable then. I should not have limited the search to `is:open` :smile:

**Comment by mcarton** [comment]
Well, actually the issue is still opened, I must not have searched hard enough…
