### ISSUE TITLE
`std::convert::Into<usize>` for `u16` is not implemented

### ISSUE THREAD

**Issue by mcarton** [rust-lang/rust#44290]
As far as I understand `target_pointer_width` is at least 16 so `<usize as std::convert::From<u8>>` and `std::convert::Into<usize>` for `u16` could exist.

**Comment by ollie27** [comment]
This has been proposed before: #29220 #37423. I believe this is one of the many things blocked by #41619.

**Comment by clarcharr** [comment]
This has been fixed.
