### ISSUE TITLE
Poor error when passing "string" instead of b"string"

### ISSUE THREAD

**Issue by clarcharr** [rust-lang/rust#44307]
Playground: https://play.rust-lang.org/?gist=935daee28b05c2afcdf61423fdfb40f8&version=stable

```
fn parse_bytes(s: &[u8]) {
    // do something
}

fn main() {
    parse_bytes("hello");
}
```

This includes the error:

```
error[E0308]: mismatched types
 --> src/main.rs:6:17
  |
6 |     parse_bytes("hello");
  |                 ^^^^^^^ expected slice, found str
  |
  = note: expected type `&[u8]`
             found type `&'static str`
  = help: here are some functions which might fulfill your needs:
          - .as_bytes()
```

Whereas it could be much better suggesting the user to type `b"hello"` instead of supplying `"hello".as_bytes()`.

**Comment by mcarton** [comment]
Clippy has [a lint](https://rust-lang-nursery.github.io/rust-clippy/v0.0.157/index.html#string_lit_as_bytes) for this exact problem.
