### ISSUE TITLE
slice::split_at_mut doc example should demonstrate mutability

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#44314]
https://doc.rust-lang.org/std/primitive.slice.html#method.split_at_mut

The doc example should demonstrate the effect of mutation element(s) in the slice

**Comment by nielsegberts** [comment]
Do you mean to add an example like this?

```
let mut v2 = [1, 0, 3, 0, 5, 6];
{
    let (left, right) = v2.split_at_mut(2);
    left[1] = 2;
    right[1] = 4;
}
assert!(v2 == [1, 2, 3, 4, 5, 6]);
```

**Comment by frewsxcv** [comment]
Yep, that looks great!

**Comment by nielsegberts** [comment]
I'm happy to create a PR to update the documentation.

I think it might be best to move some examples to split_at() and focus on the mutability in split_at_mut().

**Comment by frewsxcv** [comment]
> I'm happy to create a PR to update the documentation.

Go for it 👍 

> I think it might be best to move some examples to split_at() and focus on the mutability in split_at_mut().

Agreed, sounds good to me

**Comment by frewsxcv** [comment]
Fixed in https://github.com/rust-lang/rust/pull/44325
