### ISSUE TITLE
Mentions of builtin types mark an import with the same name as used.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#44311]
Found when implementing #44240: turns out `panic!()` in a module marks `std::u32` imports as used, even if they aren't actually needed.
Simple testcase:
```rust
// This should always warn:
use std::u32;
// If only the builtin type is used:
fn main() { let _: u32; }
```
cc @petrochenkov

**Comment by ollie27** [comment]
Duplicate of #40774

**Comment by Mark-Simulacrum** [comment]
Closing as a duplicate.
