### ISSUE TITLE
Compile time regression in #44186 

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#44323]
Up to a 6% regression in performance is hiding somewhere in this range: https://github.com/rust-lang/rust/compare/7eeac1b81446c6327f1827ef334eca2db7fe28f7...890c87b643264120dc1064ed73df6def974e02f. I suspect https://github.com/rust-lang/rust/commit/5c279a40aeba4c3df968aa2d7c2ccc37f3dfd9df, but it could be something else as well -- that's the only one that stands out to me though.
cc @alexcrichton

**Comment by arielb1** [comment]
Looks like 5c279a4 - we're hashing the in-scope traits for a bunch of more things in `<NodeId as HashStable>::hash_stable`

**Comment by arielb1** [comment]
Umm no the problem is that we're hashing literally every HirId ever
