### ISSUE TITLE
Make sure that calls to Fingerprint::combine do not undermine collision safety

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#44337]
`Fingerprint::combine` is not a cryptographic hash, so when we use it we might lose the "cryptographic" guarantee of collision safety. Potentially even worse, `Fingerprint::combine` is associative: `Fingerprint::combine(Fingerprint::combine(a, b), c) = Fingerprint::combine(a, Fingerprint::combine(b, c))`, and that might cause "algebraic" collisions in some cases.

For example:
https://github.com/rust-lang/rust/blob/2f1ef9ef1181298d46e79d5dde6bafeb6483926f/src/librustc/dep_graph/dep_node.rs#L595
https://github.com/rust-lang/rust/blob/2f1ef9ef1181298d46e79d5dde6bafeb6483926f/src/librustc/dep_graph/dep_node.rs#L614-L623
And another case added by my PR:
https://github.com/arielb1/rust/blob/d14ed92f6b5aa23fd06f8affe4554f2c370bc79d/src/librustc/dep_graph/dep_node.rs#L647-L657

I believe the only requirement for `DepNode` is that the map from `QueryKey -> (DepKind, Fingerprint)` is injective. It might be a good idea to have a good sense of the requirements there to avoid accidental collisions.

**Comment by michaelwoerister** [comment]
Just to clarify, we do not require these `Fingerprint` values to be cryptographically secure in any way. We just need them to be (roughly) as unlikely to collide as random 128 bit numbers would be.

**Comment by arielb1** [comment]
@michaelwoerister 

But cryptographic collision-resistance is a nice property, because it is fairly robust and implies we don't have to worry about odd interactions.

**Comment by Enselic** [comment]
Triage: Closing as won't fix since I don't see how keeping this open can lead anywhere. Making a case for cryptographic collision-resistance of these hashes is probably better done in an RFC or perhaps even better in Zulip.
