### ISSUE TITLE
Collector in trans is private

### ISSUE THREAD

**Issue by MaikKlein** [rust-lang/rust#44334]
I am currently trying to create a SPIR-V backend but I am running into a few problems.

For example https://github.com/rust-lang/rust/blob/master/src/librustc_trans/collector.rs is private https://github.com/rust-lang/rust/blob/master/src/librustc_trans/lib.rs#L108

It seems that a lot of useful functionality is inside `collector.rs`. Would it be possible to make some functionality public? I would be happy to provide a PR.

**Comment by eddyb** [comment]
It should be moved to to `librustc_mir`. cc @nikomatsakis @michaelwoerister

**Comment by michaelwoerister** [comment]
I think we'll need to turn it into a query soon anyway.

**Comment by eddyb** [comment]
That doesn't help, IMO. It should be a reusable piece of code. `librustc_trans` is the LLVM backend and therefore non-reusable.

**Comment by MaikKlein** [comment]
I talked with eddyb on irc about this issue.

* moving the collector to src/librustc_mir/monomorphize/collector.rs
* changing terminology from "trans collector" to "monomorphization collector"

I am happy to do provide a PR myself.

**Comment by MaikKlein** [comment]
Resolved by https://github.com/rust-lang/rust/pull/45525
