### ISSUE TITLE
Rustdoc renders associated constants poorly

### ISSUE THREAD

**Issue by sgrif** [rust-lang/rust#44348]
We recently changed Diesel to use associated constants in a few places, and noticed that our docs look a lot worse as a result.

<img width="1010" alt="screen shot 2017-09-05 at 1 12 41 pm" src="https://user-images.githubusercontent.com/1529387/30079223-ba8950c2-923c-11e7-948e-72816bc99b96.png">

It stands out far too much, and looks nothing like any other section of the docs related to traits. It'd be great if the definition could be inlined and look the same as it does for associated types.

**Comment by killercup** [comment]
FTR, original implementation was in https://github.com/rust-lang/rust/pull/39944 and current design suggested in https://github.com/rust-lang/rust/pull/39944#issuecomment-281197711

**Comment by GuillaumeGomez** [comment]
Seems like it has been fixed by #39944 so I close.

**Comment by sgrif** [comment]
@GuillaumeGomez That was the pull request that introduced this bug, not the one that fixed it. Please re-open this issue.

**Comment by nox** [comment]
Why are definitions of constants even printed? This leaks implementation details about how opaque wrappers etc are defined. Could we instead display them only if `--document-private-items` is on?

**Comment by ollie27** [comment]
I think we can consider this fixed by #53409.
