### ISSUE TITLE
Nightly regression: Unable to create array temporary in static

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#44373]
This code snippet:

```rust
struct Foo<'a>(&'a [&'a bool]);

static TEST: bool = true;
static FOO: Foo = Foo(&[&TEST]);

fn main() {}
```

compiles on stable rust `rustc 1.20.0 (f3d6973f4 2017-08-27)`, but not on `rustc 1.22.0-nightly (2f1ef9ef1 2017-09-05)`.

[Playground link](https://play.rust-lang.org/?gist=64728fb0e32cc38b0ca6b813b95c04f3&version=undefined)

**Comment by Aaron1011** [comment]
I'd like to work on this issue.

**Comment by Mark-Simulacrum** [comment]
cc @eddyb -- this seems related to the work you've been recently doing

**Comment by eddyb** [comment]
Hmm, this looks like an rvalue promotion failure. @Aaron1011 can you try, on this line: https://github.com/rust-lang/rust/blob/a20953906056f85f71896795e762ac242e1891aa/src/librustc_mir/transform/qualify_consts.rs#L69
adding ` & !Qualif::STATIC_REF.bits`?

That should allow `&[&TEST]` to promote and thus let the code compile again.
The limitations around `static` are completely artificial given a correct implementation, and will hopefully removed when `miri` starts being used for evaluating these constants.

**Comment by nikomatsakis** [comment]
triage: P-high

Assigning to @eddyb to mentor @Aaron1011 towards a fix!

**Comment by eddyb** [comment]
I just realized I *may have never* seen the actual error emitted, I thought it was MIR constant checking that was banning a reference to a `static`. But `static` lvalue is not an rvalue so this should be impossible to reach.

**Comment by Aaron1011** [comment]
My fix has been merged, and is included in the latest nightly.
