### ISSUE TITLE
allow standard library functions to check expensive pre-/postconditions

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#44371]
See also: https://github.com/rust-lang/rust/issues/44370

There should be a way for standard library functions to check expensive pre-/postconditions, by which I mean preconditions that change the complexity of the standard algorithms (e.g. by making a `O(1)` algorithm `O(log N)`). 

Example: `binary_search` requires the input slice to be sorted, otherwise the result is unspecified. Checking if the input slice is sorted makes `binary_search` `O(N)` instead of `O(log N)` (*) defeating the purpose of binary search. Still, such a check is useful to detect logic errors in user programs: it is a violated precondition after all.

So we are at an impasse. What could we do?

We could:
- [ ] add a `expensive_assert!` macro to `std`
- [ ] allow users to configure `std` with different features (and make this easy to use via cargo)
- [ ] add `expensive_assert!(input_slice.is_sorted())` to `binary_search` 

An alternative would be to perform this test using `debug_assert!`. However, making all debug builds exponentially slower is unacceptable.

(*) Since the standard library does not guarantee the complexity of anything, we can actually make `binary_search` O(N) in debug builds and that would be a backwards compatible change...

**Comment by arielb1** [comment]
We also shouldn't change `binary_search` to be `O(n)` on debug-assertions builds - debug-assertions should be for the last 2x of performance, not for potential order-of-magnitude slowdowns.

**Comment by gnzlbg** [comment]
@steveklabnik is it ok to discuss this as a pre-RFC here then or should I post this in the internals forum?

**Comment by steveklabnik** [comment]
> I really don't know what the design space is

Yeah, this makes it not a good issue; issues should have a clear way to resolve them.

A post on the internals forum would be perfect. Thanks!

**Comment by gnzlbg** [comment]
FWIW: https://internals.rust-lang.org/t/pre-rfc-expensive-pre-postcondition-checks-in-std/5871
