### ISSUE TITLE
str::get_mut doc example should demonstrate mutability

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#44382]
https://doc.rust-lang.org/nightly/std/primitive.str.html#method.get_mut

The doc example should demonstrate the effects of mutating the resulting string slice.

The easiest way I've found to demonstrate mutability with doc examples for `str` is to use `AsciiExt`: https://doc.rust-lang.org/nightly/std/primitive.str.html#method.split_at_mut

**Comment by toidiu** [comment]
I would like to attempt this.

**Comment by frewsxcv** [comment]
Long time no see @toidiu :wave: Let me know if you need any help with this or have any questions

**Comment by toidiu** [comment]
@frewsxcv  🖖  

I had a thought about how to implement this better. The current example uses the string 🗻∈🌏 where the characters have a variable byte length. This was a source of confusing when I first looked at the example (its not super obvious that 🗻 is 4 bytes). 

I was thinking of changing the string to something more uniform like `hello` which is 1 byte per char and then applying `make_ascii_uppercase()`. This could also be applied to other examples.

**Comment by frewsxcv** [comment]
> I was thinking of changing the string to something more uniform like hello which is 1 byte per char and then applying make_ascii_uppercase(). This could also be applied to other examples.

yep, this makes sense to me 👌

**Comment by frewsxcv** [comment]
Completed in https://github.com/rust-lang/rust/pull/44467
