### ISSUE TITLE
rustc doesn't list `native` as a cpu option

### ISSUE THREAD

**Issue by valarauca** [rust-lang/rust#44393]
## short summary of the bug

```
$ rustc -Ctarget-cpu=help
```

Doesn't list the `native` as an option.

## I expected to see this happen: 

I was informed, [on reddit](https://www.reddit.com/r/rust/comments/6ynm53/a_simple_tip_to_improve_rust_program_speed/dmotelg/?context=3) that `rustc -C target-cpu=native` was a valid option, but I could not see it listed in the help menu.

## Meta

I see this issues on

```
rustc 1.22.0-nightly (088216fb9 2017-09-04) #current nightly
rustc 1.20.0 (f3d6973f4 2017-08-27) #stable
```

## How to reproduce

```
$ rustc -C target-cpu=help | grep native | wc -l
0
$ rustc -C target-cpu=native
error: no input filename given
```

**Comment by mattico** [comment]
I've got a fix for this ready, just waiting for rustc to build...
