### ISSUE TITLE
Give nice errors on merge conflict markers

### ISSUE THREAD

**Issue by chris-morgan** [rust-lang/rust#44403]
Take code like this:
```
<<<<<<< HEAD
fn foo() -> Foo { }
=======
pub fn foo() -> Foo { }
>>>>>>> something
```

Outside macros and strings, this kind of thing will always fail to parse (seven equals signs in a row is always illegal), though the precise errors it will fail with will vary depends on the context.

It’d be nice if the compiler, on detecting a syntax error caused by merge conflict markers, gave a friendlier error message, something like this:

```
error: file contains merge conflict markers
  --> <anon>:1:1
   |
1  | <<<<<<< HEAD
   | ^^^^^^^ merge conflict marker here
```

(Inspiration: Perl 5.26.0 produces a syntax error like “Version control conflict marker at line 123” thanks to https://rt.perl.org/Public/Bug/Display.html?id=127993.)

**Comment by jonas-schievink** [comment]
Duplicate of #36879

**Comment by chris-morgan** [comment]
Sigh. I thought I searched for a duplicate before filing this but that was another thing that I did just before.
