### ISSUE TITLE
rustdoc --test ignores --target

### ISSUE THREAD

**Issue by asomers** [rust-lang/rust#44404]
`rustdoc`'s `--target` option works when building documentation, but it seems to be ignored when running tests.  At the very least, using both options together should result in an error.  Ideally, `rustdoc` would invoke a cross compiler in this case.  It can be useful, for example, to execute doc tests in 32-bit mode on a 64-bit host.

To reproduce: Running `rustdoc --target=itanium-multics-gnu --test <more valid options>` should result in an error, but instead the doc tests run fine.

**Comment by ehuss** [comment]
Closing in favor of the tracking issues #64245 and https://github.com/rust-lang/cargo/issues/7040.
