### ISSUE TITLE
Consider adding a from_micros for `std::time::Duration`

### ISSUE THREAD

**Issue by MicroJoe** [rust-lang/rust#44400]
During the write of an embedded library I needed to make a pause of 10 microseconds. Looking over the [Nightly `std::time::Duration` documentation page](https://doc.rust-lang.org/nightly/std/time/struct.Duration.html) I understood that I had to use the following construction:

```rust
// Wait 10 microseconds
thread::sleep(Duration::new(0, 10_000));
```

The sad part is that this is less clear to me than `Duration::from_micros(10)`. Currently the `from_millis` and `from_secs` functions are implemented but not `from_micros` which could help write cleaner code IMO.

The fix seems pretty easy, maybe if you judge this useful I can try to write my first pull request to the Rust project!

**Comment by steveklabnik** [comment]
> The fix seems pretty easy, maybe if you judge this useful I can try to write my first pull request to the Rust project!

In general, this is how @rust-lang/libs works; small additions can just be a PR, larger additions need an RFC. So, I'd suggest that you send in a PR implementing this.

**Comment by dtolnay** [comment]
Adding `from_micros` sounds okay to me.

**Comment by sfackler** [comment]
Yeah, I'd be on board with a PR.

**Comment by nagisa** [comment]
This is now a tracking issue for the function added in the previously referenced PR.

**Comment by SimonSapin** [comment]
Looks good to me to stabilize.

@rfcbot fcp merge
