### ISSUE TITLE
Feature Request: Rust support function override

### ISSUE THREAD

**Issue by netroby** [rust-lang/rust#44408]
I hope rust can support function override, In real development world. we import a library, and may be want to override one function of the library.

Example origin func
```
fn add_one(x: i32) -> i32 {
    x + 1
}

```

we want to add log in the function

```
fn add_one(x: i32) -> i32 {
   log('The input number was {} ', x);
   x + 1
}
```

We only want to override the function , not want to fork the whole library and modify the library.

**Comment by sfackler** [comment]
Feature requests should be made on https://github.com/rust-lang/rfcs.

**Comment by steveklabnik** [comment]
Yes, please file over there. Thanks!
