### ISSUE TITLE
Add support for either `const` or constexpr-like constraint for function and macro parameters

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/rust#44401]
This isn't a proposal that I've thoroughly fleshed out, but there should be some way to specify to the compiler that a parameter should have a compile-time value so that it can be used in place of the literal constraint.

While not fully fleshed out, the idea is to enable macros like `println!` to handle a wider range of inputs that can be proved safe, without requiring a literal argument as the first parameter.

For example, 

```rust
fn foo() {
    //type explicitly provided for illustration purposes
    let s: &'static str = "hello, world";
    println!(s);
}
```

(for future reference, rustc 1.20.0 prints the following:)

```rust
error: expected a literal
 --> src/main.rs:4:14
  |
4 |     println!(s);
  |              ^
```

If not full-blown constexpr-like support, then at least a way for macros to stipulate that a parameter should be constant, so that _this_ would at least work:

```rust
fn foo() {
    //type explicitly provided for illustration purposes
    const s: &'static str = "hello, world";
    println!(s);
}
```

(for future reference, rustc 1.20.0 prints the following error:)

```rust
error: expected a literal
 --> src/main.rs:4:14
  |
4 |     println!(s);
  |              ^
```

**Comment by Mark-Simulacrum** [comment]
Closing -- this should be fleshed out in the rfcs repository and/or discussed on internals.rust-lang.org before filing here.
