### ISSUE TITLE
inhabitedness cache handles cycles incorrectly

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#44402]
In [this example](https://play.rust-lang.org/?gist=da68f9d467ec5ee3e7135088a28aab68&version=nightly), I get an (incorrect) compilation error:

```
#![feature(never_type)]

struct Foo { 
    field1: !,
    field2: Option<&'static Bar>,
}

struct Bar {
    field1: &'static Foo
}

fn test_a() {
  let x: Option<Foo> = None;
  match x { None => () }
}

fn test_b() {
  let x: Option<Bar> = None;
  match x { None => () }
}
    
fn main() { }
```

But if you comment out `test_a`, you don't. This is because the inhabitedness code, if it starts from `Foo`, incorrectly caches a result for `Bar` -- the result is incorrect because `Bar` did not fully explore `Foo`, since we found a cycle.

Encountered while fixing #44137 -- I will fix en passante.

**Comment by bstrie** [comment]
I know the text of the bug implies that this will be fixed relatively soon, yet I'm still nominating because of my perpetual quest to let no soundness bug go unprioritized. :) If this happens to get closed before you get around to discussing it, all the better!

**Comment by nikomatsakis** [comment]
Will be fixed by https://github.com/rust-lang/rust/pull/44501. I'm going to categorize this as P-medium -- I think it only affects unstable code, and I *think* it just causes things to fail to compile that should have compiled.

**Comment by nikomatsakis** [comment]
triage: P-medium
