### ISSUE TITLE
incr.comp.: Refactor in_scope_traits query to take DefId instead of HirId as query-key

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#44414]
It must be possible for all "input" queries to reconstruct their query-key from their `DepNode`. The easiest way to accomplish this is to make the query-key a `DefId`.

The `in_scope_traits` query violates this condition at the moment. A simple way to fix this would be to make it a two-level map: The query returns a per-item map that is indexed by `ItemLocalId`. The query-key would be the `HirId::owner`. 

cc @alexcrichton @nikomatsakis

**Comment by alexcrichton** [comment]
Oh is `HirId` not a suitable key for queries? Apologies if I mistakenly thought it was!

There's a few other queries that use `HirId` right now as well, and will those need to be fixed as well?

**Comment by michaelwoerister** [comment]
Well, let's say `DefId` is better because in that case we can reconstruct the query-key from the `DepNode`. If it's really needed we could provide that same support for `HirId`, but that would mean that we have to always build a `Fingerprint -> HirId` table during HIR lowering (we already do something like that for `DefPathHash -> DefId`).

**Comment by alexcrichton** [comment]
I took a slightly different approach in https://github.com/rust-lang/rust/pull/44435 which just blanket converts to `DefId`, but let me know if that's in error! (there was quite a few new queries using `HirId` which also needed to change and it didn't seem so obvious for a two-level cache)

**Comment by michaelwoerister** [comment]
See https://github.com/rust-lang/rust/pull/44435#issuecomment-328285364. I have not yet looked at the other queries that use `HirId` as key.
