### ISSUE TITLE
str::into_boxed_bytes should have a doc example

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#44423]
https://doc.rust-lang.org/nightly/std/primitive.str.html#method.into_boxed_bytes

If anyone anyone wants to work on this, just mention it in a comment to prevent duplicate work. If you need any help or have any questions, don't hesitate to ping me :)

**Comment by 42triangles** [comment]
I'd like to do it. Would something like
```
let s = "this is a string";
let boxed = s.to_owned().into_boxed_str().into_boxed_bytes();
assert_eq!(*boxed, *s.as_bytes());
```
suffice?

**Comment by frewsxcv** [comment]
@42triangles yep, that looks good to me! if you want to separate it into multiple declarations, go for it. most doc examples _don't_ have the type information explicitly attached, but if you think it helps understand the API, then feel free to incorporate it.

**Comment by frewsxcv** [comment]
Resolved in https://github.com/rust-lang/rust/pull/44485
