### ISSUE TITLE
Why does dedup_by/by_key needs &mut T to check equality ?

### ISSUE THREAD

**Issue by Kerollmops** [rust-lang/rust#44425]
The two functions [`dedup_by`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.dedup_by) and [`dedup_by_key`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.dedup_by_key) needs `FnMut(&mut T, &mut T) -> bool` and `F: FnMut(&mut T) -> K` respectivily.

Why does these functions need mutable references to the data and not only `&T`, `FnMut(&T, &T) -> bool` and `F: FnMut(&T) -> K` ?

**Comment by sfackler** [comment]
It's strictly more flexible to provide a mutable reference than a shared reference.

**Comment by Mark-Simulacrum** [comment]
Closing -- this isn't something we can change today anyway and I don't believe it's limiting existing code in the wild.
