### ISSUE TITLE
I like numbers

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#44444]
:+1: if you like numbers as well.

Have a steve:

![steve](https://user-images.githubusercontent.com/8872119/30236465-1a0354b4-951a-11e7-9cf2-20d3798a5feb.png)

**Comment by Restioson** [comment]
ok

**Comment by L117** [comment]
ok x2

**Comment by SuperCuber** [comment]
ok x3

**Comment by kennytm** [comment]
ok ×44444

**Comment by steveklabnik** [comment]
Let's not, please.
