### ISSUE TITLE
prime_suspects beta regression

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#44448]
The tests of the [prime_suspects](https://crates.io/crates/prime_suspects) crate version 0.2.0 fail on latest beta 1.21, while they work on stable. The error output (full [log](http://cargobomb-reports.s3.amazonaws.com/stable-1.20-beta-1.21.0-beta.1/beta-2017-09-02/reg/prime_suspects-0.2.0/log.txt)):

```
---- src/lib.rs - segmented_sieve_parallel (line 146) stdout ----
	thread 'rustc' panicked at 'test executable failed:

thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `[65521, 65519, 65497]`,
 right: `[64763, 64747, 64717]`', src/lib.rs:3:0
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

cc @bright-star

**Comment by est31** [comment]
The tests are flaky. Not a Rust issue.

**Comment by bright-star** [comment]
@est31 That's interesting that the output has changed, I haven't checked the crate in a long time. If you're interested please file a ticket and I'll take a look.

**Comment by est31** [comment]
@bright-star filed one! https://github.com/bright-star/prime-suspects/issues/1
