### ISSUE TITLE
unsoundness relating to WF requirements on trait object types

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#44454]
So @scalexm pointed me at this [curious example](https://play.rust-lang.org/?gist=d68b1c79fa99bf17a18afb3f4649ca77&version=undefined):

```rust
trait Animal<X>: 'static { }

fn foo<Y, X>() where Y: Animal<X> + ?Sized {
    // `Y` implements `Animal<X>` so `Y` is 'static.
    baz::<Y>()
}

fn bar<'a>(arg: &'a i32) {
    foo::<Animal<&'a i32>, &'a i32>()
    
    // If you uncomment this line, you will get an error.
    //baz::<Animal<&'a i32>>()
}

fn baz<T: 'static + ?Sized>() {
}

fn main() {
    let a = 5;
    bar(&a);
}
```

There's a lot going on here, but the key point is that, in the call to `foo::<Animal<&'a i32>, &'a i32>`, we assume that `Animal<&'a i32>: Animal<&'a i32>`. This is *reasonable*, since it's a trait object type -- however, it is a malformed trait object type, and hence one where no impl could ever exist (i.e., we could never make an instance of this type). Interestingly, we are not smart enough to extend this to the case where the `'static` bound is applied *directly* (hence the commented out call to `baz::<Animal<&'a i32>>`.

At the very least, this is inconsistent behavior, but I *feel* like there is an unsoundness lurking here. What makes me nervous is that we say that a projection type `<P0 as Trait<P1...Pn>>::Foo` outlives `'a` if `Pi: 'a` for all `i`. I am worried that you could use an impl like this:

```rust
trait Projector { type Foo; }

impl<X> Projector for Animal<X> {
  type Foo = X;
}
```

to prove then that `<Animal<&'a i32> as Projector>::Foo` outlives `'static` (say). I have not yet quite managed to weaponize this, but I got [pretty close](https://play.rust-lang.org/?gist=e236ed5a041ad6864fc1e5e401d9bd36&version=stable) -- that's a gist in which we invoke a function `is_static<U: 'static>(u: U)` where `U` will be of type `&'a i32` when monomophized. If rustc were as smart as chalk, I suspect we could easily craft a transmute of some kind to `&'static i32`. There may be a way to do it within current rustc too.

I'm not sure what's the best fix here. I *suspect* we should require that trait object types meet the WF requirements declared on the trait; and yet, I think the reason we did not is because we don't know the `Self` type, which means we can't fully validate that. =) This also feels a mite inconsistent with implied bounds. (Perhaps most likely is that we could tweak the WF rules for trait objects to specifically target lifetime bounds, but I have to think about that, feels .. hacky?)

We could tweak the notion of what type parameters are *constrained* -- or at least which may appear in a projection. e.g., we could disallow that impl of `Projector` for `Animal<X>`, because `X` would not be considered "sufficiently" constrained to appear in `type Foo = ...`. Backwards incompatible, obviously, and feels unfortunate.

---

This causes [actual unsoundness](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=21ac29bdd059c4ba91e23c52d267f4b4), as discovered by @scalexm in https://github.com/rust-lang/rust/issues/44454#issuecomment-328283082;

```rust
use std::any::Any;

trait Animal<X>: 'static { }

trait Projector {
  type Foo;
}

impl<X> Projector for dyn Animal<X> {
  type Foo = X;
}

fn make_static<'a, T>(t: &'a T) -> &'static T {
    let x: <dyn Animal<&'a T> as Projector>::Foo = t;
    let any = generic::<dyn Animal<&'a T>, &'a T>(x);
    any.downcast_ref::<&'static T>().unwrap()
}

fn generic<T: Projector + Animal<U> + ?Sized, U>(x: <T as Projector>::Foo)
    -> Box<dyn Any>
{
    make_static_any(x)
}

fn make_static_any<U: 'static>(u: U) -> Box<dyn Any> {
    Box::new(u)
}

fn main() {
    let a = make_static(&"salut".to_string());
    println!("{}", *a);
}
```

cc @arielb1 @aturon

**Comment by nikomatsakis** [comment]
Actually, thinking about this more, the problem is maybe not quite how I was thinking of it. That is, it seems like the problem lies in the definition of object safety. That is, if you imagine that you had to write the impl for `Animal<X>` by hand, it would look like:

```rust
impl<X> Animal<X> for Animal<X> { ... }
```

and this would fail the well-formedness checks because `Animal<X>: 'static` does not hold, at least not without relying on the impl we are writing =).

**Comment by scalexm** [comment]
Here is an actual unsoundness, using `std::any::Any`:
https://play.rust-lang.org/?gist=1385ed4e051354b305ea2d2413f8724f&version=stable

**Comment by arielb1** [comment]
This looks similar to #27675 - in both cases we have a trait object that is not WF.

I *think* a reasonable way to solve this would be to have a trait object predicate depend on a `WF(Self)` predicate, so we basically have the rule
```Rust
'λ₀...'λₙ lifetimes
τ₀...τₙ types
Trait object-safe
WF(for<...> Trait<'λ₀...'λₙ, τ₀...τₙ>: for<...> Trait<'λ₀...'λₙ, τ₀...τₙ>)
--------
for<...> Trait<'λ₀...'λₙ, τ₀...τₙ>: for<...> Trait<'λ₀...'λₙ, τ₀...τₙ>
```

**Comment by arielb1** [comment]
The "this part is new" part is actually more subtle than I realized.

Object types (aka `dyn Trait<'λ₀...'λₙ, τ₀...τₙ>`, to avoid confusion) are actually a funny way of writing
```
exists<σ> (σ, for<...> WF(dyn Trait<'λ₀...'λₙ, τ₀...τₙ>: Trait<'λ₀...'λₙ, τ₀...τₙ>) → σ: Trait<'λ₀...'λₙ, τ₀...τₙ>)
```

And the idea is that if the trait is object-safe, we can write a "compiler impl"
```Rust
impl<'λ₀...'λₙ, τ₀...τₙ> Trait for dyn Trait<'λ₀...'λₙ, τ₀...τₙ> {
    // ...
}
```

If we want to write such an impl, we need the where-clauses on the trait (both associated types and others) to hold. For supertraits, this follows by obvious induction. For other constraints, this is something that won't hold by itself.

Therefore, we probably need to add these other predicates as conditions on the impl.

**Comment by nikomatsakis** [comment]
I agree that it is the same as #27675. As we said on IRC, I think that the current fix is roughly [as I described here](https://github.com/rust-lang/rust/issues/44454#issuecomment-328274942) -- in particular, when we check that `dyn Trait<P...>: Trait<P...>`, we need to also check that the where-clauses declared on `Trait` hold for `dyn Trait<P...>`. This subsumes some of the object safety checks (e.g. the search for `where Self: Sized`).

**Comment by bstrie** [comment]
> I agree that it is the same as #27675.

Shall we close this as a dupe, then?

**Comment by nikomatsakis** [comment]
ping @arielb1 -- whatever happened with your branch here? I remember we had some discussions about cycles and don't recall how (if at all) they were resolved.

**Comment by aturon** [comment]
Marking P-medium. While there's overlap with #27675, this issue has more in-depth information. We plan to keep them both open until fixed.

**Comment by Eallaneg46** [comment]
OK well I have a laptop it was working until Kevin Corley Deadeye was helping me download windows 10 well it didn't work My laptop turns on been doesn't open to anything  know .His computer works real good .He downloaded windows 10.He has been using his computer to hack into everything of mine
Google, Facebook ,windows, outlook ,me cell phone.I know he s been talking to someone else every night 
 after dinner.He doesn't move from his computer until he comes to bed about 12:00.

**Comment by Eallaneg46** [comment]
Anyways he thinks I have been cheating I havent.One night about a week ago I started to give Kevin a blow job, I smelled pussy on him It wasnt my pussy cause we hadn't had sex in  three days.

**Comment by Eallaneg46** [comment]
Kevin is the one who's cheating .I don't know what else to do other than leave him.

**Comment by Eallaneg46** [comment]
Any how  I'm having problems understanding this technology so back with me.Thank You

**Comment by Aaron1011** [comment]
Since https://github.com/rust-lang/rust/issues/27675 was fixed, can this issue be closed?

**Comment by scalexm** [comment]
We agreed that this issue and #27675 shared a similar root cause, but my [weaponized example](https://github.com/rust-lang/rust/issues/44454#issuecomment-328283082) still compiles on both stable and nightly and is still unsound.

I did not know about #73905 until now, but it seems to only have fixed the case of `Trait<Item = &'a i32>` when `Item` is supposed to be `'static`. It’s quite obvious why this case was incorrect in the first place.

Conversely, it’s less obvious why there should be a problem with `dyn Animal<&'a i32> + 'static` in my initial example. After all, it’s possible to implement `Animal<&'a i32>` for `SomeType: 'static`.

The reason being that lifetime requirements are syntactic and if you allow `dyn Animal<&'a i32>: Animal<&'a i32>` in conjunction with implied bounds, you can derive contradictory things. It’s the same reason why the type `fn(&'a i32)` is *not* considered to outlive `'static`, even if the underlying object is just a function pointer.

https://github.com/rust-lang/chalk/issues/203 describes a formal solution under the full implied bounds setting (it would need to be slightly adapted for [RFC 2027](https://rust-lang.github.io/rfcs/2027-object_safe_for_dispatch.html) ).

I think an easy fix with the current limited form of implied bounds would just be to collect all lifetimes appearing in `dyn Trait<…> + 'a`, and check that they verify the outlive clauses transitively required by `Trait`. If the check fails, we still allow using the type, but we say that`dyn Trait<…>: Trait<…>` does *not* hold. I believe this would be sufficient to fix the soundness bug, and would be compatible with [RFC 2027](https://rust-lang.github.io/rfcs/2027-object_safe_for_dispatch.html).

**Comment by lcnr** [comment]
another repro for the same issue
```rust
trait Trait<ARG: 'static>: 'static {
    type Assoc: AsRef<str>;
}

fn hr_shit<T: ?Sized, ARG>(x: T::Assoc) -> Box<dyn AsRef<str> + 'static>
where
    T: Trait<ARG>
{
    Box::new(x)
}

fn extend_lt<'a>(x: &'a str) -> Box<dyn AsRef<str> + 'static> {
    type DynTrait = dyn for<'a> Trait<&'a str, Assoc = &'a str>;
    hr_shit::<DynTrait, _>(x)
} 

fn main() {
    let extended = extend_lt(&String::from("hello"));
    println!("{}", extended.as_ref().as_ref());
}
```

**Comment by nikomatsakis** [comment]
We looked at this in the types meeting -- none of the the existing reproductions compile anymore -- but we're not sure if this is *truly* fixed or not. It's not clear what made them stop compile. 

A good first step would be bisecting to see what PR fixed this example:

https://github.com/rust-lang/rust/issues/44454#issuecomment-1175925928

**Comment by Nilstrieb** [comment]
searched nightlies: from nightly-2020-01-01 to nightly-2022-11-30
regressed nightly: nightly-2022-08-10
searched commit range: https://github.com/rust-lang/rust/compare/f03ce30962cf1b2a5158667eabae8bf6e8d1cb03...34a6cae28e7013ff0e640026a8e46f315426829d
regressed commit: https://github.com/rust-lang/rust/commit/63e4312e6bd50ec9859c363402209809fb8155d5

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.4</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --access github --regress error
```
</details>

**Comment by lcnr** [comment]
it looks like the original unsoundness was fixed before #99217, it seems like that stopped compiling in 1.61. @Nilstrieb can I get you to bisect this one as well?
```rust
use std::any::Any;

trait Animal<X>: 'static { }

trait Projector {
  type Foo;
}

impl<X> Projector for dyn Animal<X> {
  type Foo = X;
}

fn make_static<'a, T>(t: &'a T) -> &'static T {
    let x: <dyn Animal<&'a T> as Projector>::Foo = t;
    let any = generic::<dyn Animal<&'a T>, &'a T>(x);
    any.downcast_ref::<&'static T>().unwrap()
}

fn generic<T: Projector + Animal<U> + ?Sized, U>(x: <T as Projector>::Foo)
    -> Box<dyn Any>
{
    make_static_any(x)
}

fn make_static_any<U: 'static>(u: U) -> Box<dyn Any> {
    Box::new(u)
}

fn main() {
    let a = make_static(&"salut".to_string());
    println!("{}", *a);
}
```

**Comment by albertlarsan68** [comment]
I got `Regression in nightly-2022-03-16`, which maps to
```
2022-03-14UTC: Auto merge of #94929 - flip1995:clippyup, r=Manishearth
2022-03-14UTC: Auto merge of #94935 - matthiaskrgr:rollup-2o2kyz6, r=matthiaskrgr
2022-03-15UTC: Auto merge of #92285 - compiler-errors:dyn-proj-bounds, r=nikomatsakis
2022-03-15UTC: Auto merge of #94584 - pnkfelix:inject-use-suggestion-sites, r=ekuber
2022-03-15UTC: Auto merge of #94938 - lnicola:rust-analyzer-2022-03-14, r=lnicola
2022-03-15UTC: Auto merge of #94261 - michaelwoerister:debuginfo-types-refactor, r=wesleywiser
2022-03-15UTC: Auto merge of #94928 - lcnr:inline-as_substs, r=michaelwoerister
2022-03-15UTC: Auto merge of #94966 - matthiaskrgr:rollup-iqzswh3, r=matthiaskrgr
2022-03-15UTC: Auto merge of #94973 - GuillaumeGomez:more-gui-tests, r=notriddle
```

Unfortunately, there is no CI builds anymore for this range, and I do not have the power to bisect those commit myself now.

Reproduce with `cargo bisect-rustc --access=github --end 1.61.0 -- check`

**Comment by oli-obk** [comment]
I'm guessing it was @compiler-errors' https://github.com/rust-lang/rust/pull/92285

**Comment by lcnr** [comment]
that's cool, looks like we only need the add ui tests and can then close this issue 🎉
