### ISSUE TITLE
Possible codegen bug leading to segfaults introduced in 1.20.0

### ISSUE THREAD

**Issue by dennishamester** [rust-lang/rust#44471]
The following program works fine with `rustc 1.19.0 (0ade33941 2017-07-17)` but segfaults with `rustc 1.20.0 (f3d6973f4 2017-08-27)` if compiled with optimizations and debug symbols (`rustc -g -O`). I have tested this only on Linux x86_64. The current master branch (as of commit 18366f4e8aaec1d46282cf0a6e0fe1a0ab202530) is still affected.

```rust
// Compile with: rustc -g -O
// Without -g, the program panics instead in
// std::sys_common::thread_info::set

struct A {
    a1: unsafe extern fn(),
    a2: (),
}

impl A {
    fn new() -> Self {
        A {
            a1: unsafe { ::std::mem::transmute(0usize) },
            a2: (),
        }
    }
}

fn main() {
    A::new();
}
```

The segfault happens in `core::mem::zeroed::<libc::unix::notbsd::linux::other::b64::x86_64::pthread_attr_t>()`. At least, that's the last stack frame.

A bisect leads to ecf62e4cdcbe9fe59e2e1280739d15953cc0e500 as the first bad commit. I further bisected llvm to the commit rust-lang/llvm@7d1c3d4881647e53d0e317e21f3b31349120062f which was introduced in the merge commit rust-lang/llvm@a5ef0696d7c103006d3cb1f4263bad0ca13adca8.

Reverting all commits of that merge (rust-lang/llvm@a5ef0696d7c103006d3cb1f4263bad0ca13adca8) on the rust master branch fixes the problems.

I think this is some kind of codegen bug in llvm. Unfortunately, I'm not at all familiar with the llvm codebase (or rust's codebase for that matter) to understand what's causing this. The generated code for the snippet above seems to be correct with and without rust-lang/llvm@a5ef0696d7c103006d3cb1f4263bad0ca13adca8. I haven't looked at the code generated for `libcore` yet.

**Comment by plietar** [comment]
Function pointers in Rust can never be null, so that snippet is undefined behaviour and llvm is free to do what it wants.

The following does the same thing with no space overhead :
```rust

struct A {
    a1: Option<unsafe extern fn()>,
    a2: (),
}

impl A {
    fn new() -> Self {
        A {
            a1: None,
            a2: (),
        }
    }
}

fn main() {
    A::new();
}
```

**Comment by dennishamester** [comment]
Yes you're right. Admittedly, I haven't thought about that this is or might be undefined behavior. Is this specified somewhere?

**Comment by petrochenkov** [comment]
@dennishamester 
>Is this specified somewhere?

Yes, here - https://doc.rust-lang.org/nightly/std/primitive.fn.html (maybe in other places as well).

**Comment by dennishamester** [comment]
Many thanks for pointing this out. I'm closing this issue as it is not actually a bug in the compiler.
