### ISSUE TITLE
[docs] Drain filter pseudo code incorrect

### ISSUE THREAD

**Issue by adudney** [rust-lang/rust#44499]
https://doc.rust-lang.org/nightly/std/vec/struct.Vec.html#method.drain_filter

It appears that i should not be incremented if a value is removed from the array, as that'll cause values to be skipped and perhaps out of bounds access (say if the last element is removed, i will be incremented and one past the end of the array will be accessed)

**Comment by Gankro** [comment]
Easy patch to start contributing with :)
