### ISSUE TITLE
Please mark future HashMap::try_entry and Vec::try_push as #[inline(always)]

### ISSUE THREAD

**Issue by julian-seward1** [rust-lang/rust#44517]
For the Stylo embedding in Gecko we wound up making local copies of
std::HashMap and a wrapper around std::Vec, so as to support fallible
allocations.  The long term goal is to remove these once std:: acquires
fallible support of its own.

In the process, we marked (our copy of) HashMap::try_entry and Vec::try_push
as #[inline(always)].  This gave a measurable performance improvement -- see
https://bugzilla.mozilla.org/show_bug.cgi?id=1398593#c2.

Consequently it would be helpful if, when HashMap::try_entry and
Vec::try_push become available in std::, they also are marked
#[inline(always)], in order to avoid a Stylo perf loss when we transition
back to std::.

**Comment by jonas-schievink** [comment]
Those are already inlineable, is a regular inline hint not enough?

**Comment by julian-seward1** [comment]
I can't say for the current std:: versions.  But from my profiling of our clones
yesterday, I saw that they are not inlined, even with #[inline].  They needed
the (always) variant to get inlined.

**Comment by Mark-Simulacrum** [comment]
I personally feel like having an issue open for a perf win on a _future_ addition to std is pretty odd, particularly one that has ~no impact on API design and such so can be added anytime. As such, I'm going to close this.
