### ISSUE TITLE
Wrong formatting with `format_args`

### ISSUE THREAD

**Issue by werner-matthias** [rust-lang/rust#44538]
Formating yields incorrect result.
I tried this code at a bare metal Raspberry Pi (`no_std`):

```
    let foo: u32 = 13;
    kprint::fkprint(format_args!("foo = {} = {:?} = {:x} = {:b}\n",foo,foo,foo,foo));
```
`kprint::fkprint` writes to the frame buffer using the `Write` trait.

I expected to see this output: 

> foo = 13 = 13 = d = 1101

Instead, the output is:

> foo = 21 = 21 = d = 1101

## Meta
I'm using rustc 1.22.0-nightly (dd08c3070 2017-09-12) with `xargo`, i.e., `core` is newly built.

**Comment by werner-matthias** [comment]
Actually, it seems to be a more general problem with the alignment at ARM.
In `libcore/fmt/num.rs`,  ``ptr::copy_nonoverlapping(lut_ptr.offset(d1), buf_ptr.offset(curr), 2);``
fails to address the correct bytes within ``DEC_DIGITS_LUT``.

Since everything was okay a couple of weeks ago, there must be a breaking change in the meantime.
I could imagine several places where such change might happened: at the llvm (thus, I would have to update the target description), at the rust compiler, or indeed in the libcore. Could anybody give a hint?

**Comment by alexcrichton** [comment]
@werner-matthias this looks like it'll be pretty difficult for someone else to investigate (difficult to reproduce), do you think you can help narrow down the regression range if possible?

All target descriptions are in `src/librustc_back/target`, although this may or may not be related to that. A more narrow range for the regression would certainly help track this down!

**Comment by werner-matthias** [comment]
I could narrow it a bit: the change is somewhere around the 10th of September. Version ddd123ed9 works, ca94c75c5 does not.

**Comment by alexcrichton** [comment]
Ok [this is the range of commits between there](https://github.com/rust-lang/rust/compare/ddd123ed9a35ec76103d42cecf322ee8d2896bf9...ca94c75c527006be0824c764773380bbeea6030b). The only thing that looks even slightly suspect there is https://github.com/rust-lang/rust/pull/44312, @eddyb do you know if that'd affect this?

Or maybe if there's bug with rvalue promotion?

**Comment by eddyb** [comment]
Rvalue promotion works a lot like regular `static`s, I fail to see a distinction.

@werner-matthias by "fails to address the correct bytes within `DEC_DIGITS_LUT`.", can you talk about exact addresses? It'd help to see what exact mismatch is occurring.
It's possible `static` was put in a different section or was accidentally having a higher alignment.

**Comment by werner-matthias** [comment]
From the patterns I observed, I would guess that there is an offset of -1. Thus, e.g., instead to address  `b"00010203040506070809101112`**13**`14151617181`... for `13` it comes up with `b"0001020304050607080910111`**21**`314151617181`... .

**Comment by eddyb** [comment]
If it loads with 2-byte alignment that seems wrong libcore code, since `b"..."` is unaligned. Or is there a minimum alignment on that architecture that we're not respecting?

**Comment by werner-matthias** [comment]
ARM (unless it is deactivated) has an minimum alignment of 2.

**Comment by eddyb** [comment]
Ah that seems like something rustc doesn't know about. See #44440 - can you try setting that for your target?

**Comment by alexcrichton** [comment]
We *just* added support for global minimum alignment (https://github.com/rust-lang/rust/pull/44440), but I'm surprised this hasn't come up before!

@werner-matthias is this global minimum alignment something we should set for all our ARM targets? Or just the one you're working on?

**Comment by werner-matthias** [comment]
IHMO llvm cares about alignment, if the target description is correct, especially the data layout. I use Japaric's target description for ARM.

**Comment by eddyb** [comment]
From what we've seen this extra property is not in the data layout.

**Comment by werner-matthias** [comment]
A wild guess: Could the introduced global minimum alignment be exactly  the reason. since it possibly overwrites the architecture's defaults?

**Comment by eddyb** [comment]
It's not in that range though? My change is capable of breaking things that only worked by accident before.

**Comment by parched** [comment]
Hi @werner-matthias which raspberry pi 1,2 or 3? Could you please paste or link your exact target description?

**Comment by parched** [comment]
Oh actually I think I found [it](https://github.com/werner-matthias/aihPOS/blob/75a1050b86fa67a11310297593bc9d7b917e8183/kernel/arm-none-eabihf.json). Looks like raspi 1. You should also add the `+strict-align` feature unless you have set unaligned accesses allowed in SCTLR.

**Comment by werner-matthias** [comment]
@parched: You are right, `+strict-align` does the job also for ca94c75c5. Kudos!

**Comment by Mark-Simulacrum** [comment]
@eddyb I'm not entirely clear on whether this is a bug in Rust, so perhaps we can close?

**Comment by parched** [comment]
It would hurt enabling strict-align for arm-unknown-linux-gnueabi(hf), clang does for Armv6 Linux but not for Apple and bad. I'm not sure if it's strictly required, at least for Linux on the raspi I'm pretty sure it's not. From memory there's some comments in the clang source about but I'm not sure how accurate and up to date they are. I'll try and find a link when I get a minute.

**Comment by japaric** [comment]
I found [this document](https://github.com/torvalds/linux/blob/v4.13/Documentation/arm/mem_alignment) in the Linux kernel code -- I don't know how old / valid is though -- and it says that the kernel will (try to) fix unaligned memory access, at some cost, if the bit 1 of `/proc/cpu/alignment` is set. The exact text is quoted below:

> The kernel will attempt to fix up the user process performing the unaligned access.  This is of course slow (think about the floating point emulator) and not recommended for production use.

If that bit is set by default on all ARMv6 Linux devices then our current settings won't (or shouldn't) cause crashes. Though there's a performance penalty for having the kernel step in to fix the unaligned memory access.

> It would hurt enabling strict-align for arm-unknown-linux-gnueabi(hf)

But would it hurt more than having the kernel fix things?

**Comment by japaric** [comment]
> My guess is that since @werner-matthias's target spec does not have that option it's probably now defaulting to 1 whereas before llvm was providing it: it probably was 2. I need to confirm this.

Checking further this can't be the cause of the regression because (1) is not in the reported commit range and (2) if min-global-align is missing in the target spec we'll get the (right) alignment value from LLVM, which is what we have always been doing.

So no idea about the regression in the custom target spec.

**Comment by parched** [comment]
> But would it hurt more than having the kernel fix things?

Sorry I meant to type _wouldn't_. So I agree we should add it.

**Comment by parched** [comment]
Here's the clang comment I was remembering.

> Assume pre-ARMv6 doesn't support unaligned accesses.
>
> ARMv6 may or may not support unaligned accesses depending on the
> SCTLR.U bit, which is architecture-specific. We assume ARMv6
> Darwin and NetBSD targets support unaligned accesses, and others don't.
>
> ARMv7 always has SCTLR.U set to 1, but it has a new SCTLR.A bit
> which raises an alignment fault on unaligned accesses. Linux
> defaults this bit to 0 and handles it as a system-wide (not
> per-process) setting. It is therefore safe to assume that ARMv7+
> Linux targets support unaligned accesses. The same goes for NaCl.
>
> The above behavior is consistent with GCC.

https://github.com/llvm-mirror/clang/blob/0810e2be8fa9a97519b8e3406e8f67645738c29b/lib/Driver/ToolChains/Arch/ARM.cpp#L462-L474

**Comment by cuviper** [comment]
The intention of #44440 is only to *increase* alignment, and only for global symbols, not memory access in general.  Targets that don't set min-global-align should not see any effect at all.

**Comment by nikomatsakis** [comment]
Checking in from the @rust-lang/compiler meeting -- can someone summarize what action on our part is needed, if any? Or is that still undetermined?

**Comment by arielb1** [comment]
@japaric 

I *think* this just used to work by accident before. Could you please open a PR for fixing the minimum alignment target spec?

**Comment by parched** [comment]
@nikomatsakis @arielb1 There's no bug in rustc here, the bug was in the out of tree target spec that was used. The take away from some of the discussion though is, we should probably add `+strict-align` to the in tree Armv6 targets for _performance_, not correctness, reasons. Do you agree @japaric?

**Comment by japaric** [comment]
> we should probably add +strict-align to the in tree Armv6 targets for performance, not correctness, reasons

Yeah, I agree. The Cortex-M target already has that feature enabled for correctness (otherwise programs crash) but all the other ARM Linux targets should see perf improvements. I'd be interested in seeing an after vs before RPi benchmark -- just to get an idea of the perf "penalty" the current targets have.

**Comment by japaric** [comment]
PR #45094 adds +strict-align to all the ARMv6 targets
