### ISSUE TITLE
Confusing `*` behavior on smart pointer types

### ISSUE THREAD

**Issue by Piping** [rust-lang/rust#44547]
Hi,

I am wondering why the rust language choose to automatically call `box.deref()` when using `*box` and `box` is a smart pointer. Because box is actually not a reference (& or &mut).

When I glance through rust code, it often leads to confusion whether I am looking at a typical borrow reference or a smart pointer type. 

Is there any plan or way to set the default behavior of *box back to *box.deref()??

**Comment by steveklabnik** [comment]
Hi @Piping !

We try to keep the issues tracker open for bugs only. This kind of question is better suited to https://internals.rust-lang.org/, please re-post this over there. Thanks!
