### ISSUE TITLE
Whitelist aes and sha target_features?

### ISSUE THREAD

**Issue by newpavlov** [rust-lang/rust#44544]
I would like to use them in the [RustCrypto](https://github.com/RustCrypto) project for conditional compilation. So if there is no particular reason against including them, it would be nice to have them.

This code currently does not work as intended:
```Rust
#[cfg(target_feature="aes")]
fn main() {
    println!("aes enabled");
}

#[cfg(not(target_feature="aes"))]
fn main() {
    println!("aes disabled");
}
```

Related: #29717

**Comment by Mark-Simulacrum** [comment]
cc @BurntSushi and @alexcrichton

**Comment by alexcrichton** [comment]
Seems plausible to me!
