### ISSUE TITLE
Improve eagerly evaluating an iterator for its side-effects

### ISSUE THREAD

**Issue by mattico** [rust-lang/rust#44546]
0b_0101_001_1010 had a good idea [on Reddit](https://www.reddit.com/r/rust/comments/6zq1jn/rust_benchmarking_forloops_map_and_rayon/dmxux5z/). I'll paraphrase it here.

The only way to eagerly consume an iterator, e.g., for its side-effects, on stable Rust is to call `.collect` or `.count` (`.for_each` is nightly only). Most beginners don't associate `.count` with this, so they use `.collect`, which is horrible.

There are a few things we could do to help make it more obvious what the correct thing to do is:

- make `.collect`'s result `#[must_use]`. If you are throwing `.collect`'s result away, you are doing it wrong, and should not have used `.collect` in the first place. A loop or `.for_each` would do.
- make `.count`'s result `#[must_use]`: while `.count` is "efficent" (when compared to `.collect`) it doesn't convey what the code is actually doing
- add an `.eval()` == `.for_each(|_|)`: because `.for_each(|_|)` is also ugly
- address this in docs: `.collect` means copy the results of the iterator into a collection, not "eagerly evaluate", or similar

**Comment by Mark-Simulacrum** [comment]
Making collect `must_use` seems reasonable. I don't think it'll be a common accident in practice, but might help beginners out -- `for _ in iter {}` seems reasonable enough for the edge case where you have a side-effect causing iterator. IMO, it's an antipattern for an iterator to cause side effects anyway...

**Comment by cuviper** [comment]
> - add an `.eval() == .for_each(|_|)`: because `.for_each(|_|)` is also ugly

I suspect that most of the time you might reach for this, there will probably be a `.map(f)` right before that can become `.for_each(f)` instead.

> IMO, it's an antipattern for an iterator to cause side effects anyway...

It's not an antipattern for an `iter_mut()`, where the primary side effect is to update items.

**Comment by stjepang** [comment]
Just a comment on naming... 🚲 🚲 🚲
I think `.drain()` would be more idiomatic than `.eval()`.

**Comment by bluss** [comment]
.exhaust() is my favourite name (by @tbu-). On balance I think this method would be a win, although I am also hoping that `.for_each` will simply fill this role.

See also previous discussion in bluss/rust-itertools/pull/131

**Comment by tbu-** [comment]
I think we should have a dedicated name for this, even `for_each(|_| ())` is a bit annoying to type, to just evaluate the iterator.

**Comment by dtolnay** [comment]
As of #45379 there is `collect::<()>()`.

```rust
let mut sum = 0;
(0..10).map(|x| sum += x).collect::<()>();
println!("{}", sum);
```

It is slightly more handy than `exhaust()` because you get all the usual folding you get with `FromIterator`, such as running through a sequence of `Result`s until the first failure if any.

```rust
use std::io::*;
let res: Result<()> = (0..10)
    .map(|x| writeln!(stdout(), "{}", x))
    .collect();
assert!(res.is_ok());
```

Does that address the request in this issue or do we feel that there is more room for improvement?

**Comment by tbu-** [comment]
I'd still say that it's annoying to type, compare `collect::<()>()` to `exhaust()`.

**Comment by bluss** [comment]
And collect to unit is hard to discover, too, isn't it? (It is kind of automatically available if one calls collect(); maybe that would be the only intuitive entry.)

**Comment by dtolnay** [comment]
I would be prepared to consider a PR for `Iterator::exhaust`.

**Comment by kennytm** [comment]
So basically revive #45168 and change the name to `exhaust` 🙂

**Comment by varkor** [comment]
Closed by https://github.com/rust-lang/rust/pull/48945, where it was decided that `iter.for_each(drop)` was a better alternative to a new iterator method.
