### ISSUE TITLE
rustdoc: fixed arrays are printing with const-eval debug info

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/rust#44555]
From the current nightly docs for AsRef:

![image](https://user-images.githubusercontent.com/5217170/30403623-3597fee6-98a8-11e7-9a21-211c7d6abf51.png)

Looks like this was introduced in https://github.com/rust-lang/rust/pull/44275.

**Comment by eddyb** [comment]
Linking an issue number doesn't cc anyone, sadly.

Fix incoming.
