### ISSUE TITLE
Match statement arms should support extern statics

### ISSUE THREAD

**Issue by PlasmaPower** [rust-lang/rust#44571]
There may be a good reason why they currently don't, but I suspect it might be an oversight in the design. Supporting them would also not be a breaking change, as match arms cannot overshadow statics (even extern statics). Like other uses of extern statics, it would be unsafe.

**Comment by Mark-Simulacrum** [comment]
This change seems significant enough that it will require an RFC. Please follow the RFC process here https://github.com/rust-lang/rfcs#before-creating-an-rfc.
