### ISSUE TITLE
'rustc' panicked at 'Box<Any>', when const expr evaluation panics

### ISSUE THREAD

**Issue by Kixunil** [rust-lang/rust#44578]
After seeing this [amusing workaround](https://github.com/rust-lang/rfcs/issues/322#issuecomment-263056187) for conditions in const expr, I decided to try it out. Then I was wondering what would happen if I caused index out-of-bounds. That led me to [this code](https://play.rust-lang.org/?gist=dd415f8327763b943a20fcfc7e1e87e4&version=stable).

While it correctly points to the error, it also says "the compiler unexpectedly panicked. this is a bug." and asks for reporting, so I'm reporting here.

**Comment by Mark-Simulacrum** [comment]
cc @eddyb

**Comment by eddyb** [comment]
Works correctly on beta and nightly, doesn't it?

**Comment by Kixunil** [comment]
@eddyb I totally forgot to check nightly. Indeed, it's correct there.
