### ISSUE TITLE
10% regression in the `issue-43572-unused-uses` test case

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#44575]
The perf website shows a 10% regression in the `issue-43572-unused-uses` test case as a result of #44435 ([diff](https://github.com/rust-lang/rust/compare/19d30fcdb28c2a4f57774b827b1a17ee156b5c56...efa3ec67e28ab8a4c3377a039095cd464713cdfd)).

Maybe not a big deal, but worth doing a quick profile to see if something can be done!

cc @alexcrichton

**Comment by alexcrichton** [comment]
[graph](https://perf.rust-lang.org/?start=2017-09-07T00%3A00%3A00%2B00%3A00&end=2017-09-13T00%3A00%3A00%2B00%3A00&crates=%5B%22issue-43572-unused-uses%22%5D&stat=instructions%3Au)

**Comment by alexcrichton** [comment]
Looking at a profile the numbers are pretty close together, but I *think* it basically says that we're hashing more in blake2b

**Comment by alexcrichton** [comment]
I'm not 100% sure, but https://github.com/rust-lang/rust/pull/44584 may be the culprit here

**Comment by nikomatsakis** [comment]
The fix that @alexcrichton landed improved things, as you can see from [this graph](https://perf.rust-lang.org/?start=2017-09-07T00%3A00%3A00%2B00%3A00&end=2017-09-30T00%3A00%3A00%2B00%3A00&crates=%5B%22issue-43572-unused-uses%22%5D&stat=instructions%3Au), but it's not *completely* resolved.

**Comment by nikomatsakis** [comment]
triage: P-high

Calling this P-high as we investigate.

**Comment by alexcrichton** [comment]
Given [this new graph](https://perf.rust-lang.org/?start=2017-09-11T00%3A00%3A00%2B00%3A00&end=2017-09-25T00%3A00%3A00%2B00%3A00&crates=%5B%22issue-43572-unused-uses%22%5D&stat=instructions%3Au) looks like https://github.com/rust-lang/rust/pull/44696 recovered any missing losses here, so closing.
