### ISSUE TITLE
Long modules path break layout of rustdoc in Safari

### ISSUE THREAD

**Issue by nox** [rust-lang/rust#44588]
<img width="382" alt="capture d ecran 2017-09-15 a 10 03 37" src="https://user-images.githubusercontent.com/123095/30472531-2b1fe068-99fd-11e7-9c3f-a58587b8c5e0.png">

https://doc.servo.org/script/dom/bindings/codegen/Bindings/HTMLMediaElementBinding/enum.CanPlayTypeResult.html

**Comment by GuillaumeGomez** [comment]
Not in my safari... Which version? (safari, rustdoc)

**Comment by nox** [comment]
This seems fixed now.
