### ISSUE TITLE
Display impl for u128 and i128 is slow

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#44583]
@henninglive has a significantly faster one in https://github.com/dtolnay/itoa/pull/10#issuecomment-329645595. Let's provide the faster one in std::fmt!

```
Unoptimized:
	test bench_itoa::bench_u128_max ... bench:       3,009 ns/iter (+/- 99)

Manual linking:
	test bench_itoa::bench_u128_max ... bench:       1,537 ns/iter (+/- 59)

Inlined:
	test bench_itoa::bench_u128_max ... bench:       1,289 ns/iter (+/- 54)
```

**Comment by henninglive** [comment]
The implementation is copied form `std::fmt`, the only change is that I have inlined the `__udivmodti4()` call to work around #44545 until LLVM is smart enough combine the calls. This is probably not relevant for std.

**Comment by dtolnay** [comment]
I guess I haven't looked at the two implementations carefully. Can we not inline `__udivmodti4()` in std?

**Comment by henninglive** [comment]
It’s possible, but we properly don’t want to do that. `__udivmodti4()` is an intrinsic passed to LLVM to be used to implement division for i128/u128 on architectures without native support. Rustc treats 128bit types mostly the same as other integer types.

**Comment by cuviper** [comment]
For platforms that don't have native 128-bit division, it may be faster to break it into parts that can do native division from there.  Bases 2, 8, and 16 can split directly to 64-bit parts, and base-10 can split into three base-10<sup>13</sup> parts.  If some 32-bit targets don't have native 64-bit division, they may do even better with 5 base-10<sup>8</sup> parts stored in 32-bit, etc.

**Comment by cuviper** [comment]
Hmm, I just read the implementation, and it already chunks it by 10000, so that much is probably pretty good already.

**Comment by henninglive** [comment]
I haven’t tried it, but I believe the current implementation is going to be pretty terrible on platforms without u64. If I understand this [code](https://github.com/rust-lang-nursery/compiler-builtins/tree/35dec6bd8ab1214078e6284d58e9ba62271e2fb9/src/int) correctly, the `__udivmodti4()` implementation as going use `__udivmoddi4` and its brothers to do u64 operations, which a lot of non inlined functions calls to divide two u128s.

**Comment by dtolnay** [comment]
I have yet another implementation in https://github.com/dtolnay/itoa/pull/12. This one is 13x faster than std::fmt on my machine.

**Comment by steveklabnik** [comment]
Triage: this appears to have gotten even more extreme over time:

```text
running 2 tests
test itoa   ... bench:         216 ns/iter (+/- 28)
test stdlib ... bench:       1,377 ns/iter (+/- 123)
```

The reproduction involves cargo features and so cannot be done on the playground, details below.

<details>

`Cargo.toml`:

```toml
[package]
name = "itoatest"
version = "0.1.0"
authors = ["Steve Klabnik <steve@steveklabnik.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.itoa]
version = "*"
features = ["std", "i128"]
```

in `benches/bench.rs`:

```rust
#![feature(test)]
extern crate test;
extern crate itoa;

use test::Bencher;

#[bench]
fn stdlib(b: &mut Bencher) {
    b.iter(|| {
        let s = format!("{}", u128::max_value());
        std::hint::black_box(s);
    });
}

#[bench]
fn itoa(b: &mut Bencher) {

    b.iter(|| {
        let mut s = String::new();
        itoa::fmt(&mut s, u128::max_value()).unwrap();
        std::hint::black_box(s);
    });
}
```

</details>

**Comment by mdibaiee** [comment]
Is this still an open issue? I see a PR for this has been merged.

**Comment by mati865** [comment]
Using @steveklabnik example (with added `#![feature(bench_black_box)]`) I've got this:
```
running 2 tests
test itoa   ... bench:          34 ns/iter (+/- 0)
test stdlib ... bench:          54 ns/iter (+/- 0)
```
I think there is still some room for improvements but it's much better now.

**Comment by dtolnay** [comment]
That's likely the best std::fmt can do. The remaining 20ns discrepancy is not algorithmic, it is the overhead of the Formatter machinery.
