### ISSUE TITLE
install.sh in distribution tarballs does not preserve executable bit

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#44594]
## Steps to reproduce:
* `./x.py dist`
* `cd $SOMEWHERE`
* `tar -xzvf $RUSTC/build/dist/rust-src-1.22.0-dev.tar.gz`
* `ls -lah rust-src-1.22.dev/rust-src/lib/rustlib/src/rust/src/jemalloc/include/jemalloc/`
  Observe how some files here are executable.
* `mkdir foo && ./install.sh --prefix=foo`
* `ls -lah foo/lib/rustlib/src/rust/src/jemalloc/include/jemalloc/`

## Expected behavior

The same files should be executable.

## Actual behavior

No file is executable.

It seems rustup blissfully ignores the installer scripts here anyway, because rustup does preserve executable bits. This makes me wonder what the point of these scripts is, anyway...

**Comment by RalfJung** [comment]
The fix has landed in rust-installer and will arrive here with the next submodule update. (No idea how frequently these are usually done.)

**Comment by alexcrichton** [comment]
No submodule is updated on a regular cadence, feel free to send a PR to update it!

**Comment by RalfJung** [comment]
All right, will do.
