### ISSUE TITLE
Tracking issue for Rc::downcast (`rc_downcast` feature)

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#44608]
Tracking issue for the `Rc::downcast` method implemented in #44273

**Comment by SimonSapin** [comment]
Looks good to me to stabilize.

@rfcbot fcp merge

**Comment by alexcrichton** [comment]
@rfcbot concern arc

We should add to `Arc` as well for consistency, right?

**Comment by SimonSapin** [comment]
On the implementation PR:

> > Arc is skipped because Any itself has no downcast for the case that makes most sense: Any + Send + Sync
>
> Why we don't implement downcast for `Any + Send + Sync`? Other than [it isn't terribly necessary](https://github.com/rust-lang/rust/issues/44064#issuecomment-324412204).

We can still do that.

**Comment by alexcrichton** [comment]
Indeed!

**Comment by bluss** [comment]
Hehe, I can't quite find the right way to pick the right implementations.

All four combinations are "Trait", "Trait + Send", "Trait + Sync", "Trait + Send + Sync".

The frugal approach is just the first one for Rc and just the last one for Arc. The perfect would be to write just one that covered them all, for each of Rc and Arc. I think the pragmatic would be all four for both Rc and Arc.

**Comment by alexcrichton** [comment]
@bluss I'd be ok conservatively just doing `Arc<Any + Send + Sync>` as I doubt most other combinations don't actually show up that often in practice

**Comment by jsgf** [comment]
Hi! I ran into this today. Any objections if I put together a PR for `Arc<Any + Send + Sync>`?

**Comment by sfackler** [comment]
SGTM

**Comment by jsgf** [comment]
Should I reuse this issue and `rc_downcast`, or create new ones?

**Comment by SimonSapin** [comment]
Using the same tracking issue sounds fine: it’s a identical copy of a fairly small function. By the way, I think you can also remove an `unsafe` block by using the (relatively) new `cast` method of `NonNull`, instead of `NonNull::new_unchecked`.

**Comment by jsgf** [comment]
I also need to add `Any + Send + Sync` implementations for `is`, `downcast_ref` and  `Debug` to `std::any::Any`. Do they need feature guards, or can I just insta-stable them? If so, what version would I put in `since = "..."`?

**Comment by SimonSapin** [comment]
@rfcbot resolve arc

The requested feature was implemented in https://github.com/rust-lang/rust/pull/50836.

**Comment by SimonSapin** [comment]
Hmm it looks like only @alexcrichton can tell rfcbot to resolve the concern here, but I think we can consider the spirit of the process to be satisfied (if not the letter) and I would accept a stabilization PR.

**Comment by alexcrichton** [comment]
@rfcbot resolved arc
