### ISSUE TITLE
IntoIterator docs should show its usage as a bound

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#44600]
IntoIterator has a complex set of associated types, and is commonly used as a bound on functions, but does not show its usage *at all*.

I'd be happy to help anyone out to make this better! Fundamentally, we should show a function that takes a generic argument that has a bound with `IntoIterator`.

**Comment by iwillspeak** [comment]
I'd like to have a go at this if that's OK. I'll open a pull request.

**Comment by peter-b** [comment]
@steveklabnik @alexcrichton Should this be closed now that #44668 has been merged?

**Comment by alexcrichton** [comment]
Indeed!
