### ISSUE TITLE
release mode is optimizing away important functionality

### ISSUE THREAD

**Issue by vitiral** [rust-lang/rust#44615]
The crate enigo, which allows rust programs to type arbitrary unicode using the keyboard, has hit a snag: in `--release` mode it doesn't work

- enigo-rs/enigo#37

Even worse, I cannot find a way to disable release optimizations for just this crate, or the functions it provides.

Some questions:
- Is there a way to disable optimizations for a single function or even a whole crate? I have tried marking all functions as both `#[no_mangle]` and `#[inline(never)]`, but neither had any effect.
- Does anyone have a *guess* at what might be causing this? A lot of the functionality relies on calls to a C library -- is there some reason rust might be optimizing that away?

We are both pretty confused by the behavior.

Edit: It fails for both of these
```
$ rustc --version --verbose                                                       
rustc 1.21.0-nightly (7eeac1b81 2017-08-30)          
binary: rustc             
commit-hash: 7eeac1b81446c6327f1827ef334eca2db7fe28f7                                                     
commit-date: 2017-08-30   
host: x86_64-unknown-linux-gnu                       
release: 1.21.0-nightly   
LLVM version: 4.0
```

```
rustc --version --verbose                                                                                                                                                                
rustc 1.19.0 (0ade33941 2017-07-17)                                                                                                                                                                                
binary: rustc
commit-hash: 0ade339411587887bf01bcfa2e9ae4414c8900d4
commit-date: 2017-07-17
host: x86_64-unknown-linux-gnu
release: 1.19.0
LLVM version: 4.0
```

**Comment by vitiral** [comment]
it looks like this might actually be our fault. It appears we might have a dangling pointer. Closing for now.

**Comment by jD91mZM2** [comment]
I doubt a dangling pointer would make the optimizer optimize away important functions though...

**Comment by vitiral** [comment]
I'm re-openeing, because they found the fix ([commit](https://github.com/enigo-rs/enigo/commit/f3a7b6b97bf28c223f8ab0d5e31fff512baee084))

change
```
let keysym_list = [keysym, keysym].as_ptr();
```

to this:
```
let keysym_list = [keysym, keysym];
let keysym_list = keysym_list.as_ptr();
```

**Comment by ollie27** [comment]
I'm pretty sure there is no bug here. A lint would be helpful though, this could be covered by rust-lang-nursery/rust-clippy#2045.

**Comment by jonas-schievink** [comment]
This is not a Rust bug, you were trying to use a dangling pointer.

**Comment by jD91mZM2** [comment]
You could argue about if it's a bug or not.
I would say it's one since [references](https://play.rust-lang.org/?gist=14f2d4afba522efce5e11f86fdb9d2c9&version=stable) work, plus it works fine in debug mode.

**Comment by sfackler** [comment]
@jD91mZM2 that's now undefined behavior works - the optimizer is the thing that makes assumptions based on what is and is not defined.

**Comment by jD91mZM2** [comment]
Hmmm... I guess that's true.

**Comment by arielb1** [comment]
This is a textbook case of undefined behavior, there's already an issue on the Clippy repo about a lint that would detect this (rust-lang-nursery/rust-clippy#2045), and as policy we're unlikely to introduce such a new lint to rustc, at least before it's iterated on in Clippy.

Closed.
