### ISSUE TITLE
Segfault using result of `place_back()` as a `Place`

### ISSUE THREAD

**Issue by andy-hanson** [rust-lang/rust#44637]
When trying to write a data structure that wraps a `Vec` and is a `Placer`, I got a segfault when trying to use the result of `place_back()` as a `Place`.

I tried this code:

```rust
#![feature(collection_placement)]
#![feature(placement_in_syntax)]
#![feature(placement_new_protocol)]

use std::ops::Placer;
use std::vec::PlaceBack;

fn main() {
	let mut stack = Stack::new();
	&mut stack <- 1;
	println!("Doesn't get here!");
}

pub struct Stack(Vec<u32>);
impl Stack {
	pub fn new() -> Self {
		Stack(Vec::new())
	}
}
impl<'a> Placer<u32> for &'a mut Stack {
	type Place = PlaceBack<'a, u32>;

	fn make_place(self) -> Self::Place {
		self.0.place_back() //.make_place()
	}
}
```

I expected to see this happen: Prints "Doesn't get here!", and exits with code 0.

Instead, this happened: Prints "Segmentation fault", and exits with code 139.

The error is fixed by uncommenting `.make_place()`.

## Meta

`rustc --version --verbose`:

rustc 1.22.0-nightly (fd4bef54a 2017-09-15)
binary: rustc
commit-hash: fd4bef54abafe6d93ec3c87498de696da6ef5819
commit-date: 2017-09-15
host: x86_64-unknown-linux-gnu
release: 1.22.0-nightly
LLVM version: 4.0

Backtrace:

N/A?

**Comment by arielb1** [comment]
I don't think it's an essential unsoundness - `PlaceBack` is for some reason both a `Placer` and a `Place`, and if you call `make_place` and `pointer` in the wrong order, you can access the `vec` out of bounds and segfault.

**Comment by alexcrichton** [comment]
cc https://github.com/rust-lang/rust/issues/27779, the tracking issue for this as well

**Comment by mattico** [comment]
Is the fix for this just to make separate types for `Placer` and `Place` so that you have to call `make_place` to actually get a `Place`?

**Comment by leodasvacas** [comment]
Triage: placement new has been unaccepted, this issue can be closed.
