### ISSUE TITLE
 `this function takes 1 parameter but 3 parameters were supplied: defined here` points to the wrong place.

### ISSUE THREAD

**Issue by dpc** [rust-lang/rust#44638]
`rustc` output must have changed, and now every time I compile my code and call a method with a wrong number of arguments, Vim will jump to the definition of the function that is called incorrectly, and not the place where it is being called.

It seems to me that the output of the compiler is wrong in the first place: the main error `file:line` message should point to the broken code, not the definition of the function that is called (which is useful, but secondary). Ideally, I'd like `rust.vim` to be able to display both in the compilation error list, so I opened: https://github.com/rust-lang/rust.vim/issues/174 there as well.

**Comment by TimNN** [comment]
I experimented a bit [on the playground](https://play.rust-lang.org/?gist=90ac0be7518268006c9db644d35cf2d4&version=nightly):

* the main error location is always given for the line of the caller
* if caller and definition locations are in the same file, the order in which they are displayed depends on their order in that file

I believe that this is an issue purely with `rust-lang/rust.vim`.

**Comment by estebank** [comment]
I'm closing this ticket as this falls entirely under https://github.com/rust-lang/rust.vim/issues/174. We'll keep the compiler output as it is (at least for now) as it seems to me that keeping labels in the same order as the code is more intuitive when looking at the error message. Tools that use the compiler output should differentiate between primary and secondary spans.
