### ISSUE TITLE
Cannot cross compile with cargo

### ISSUE THREAD

**Issue by speusippo** [rust-lang/rust#44635]
I'm trying to compile geckodriver for armv6 (raspberry pi zero w). I have installed rust and cargo, with toolchain for arm6 but I got this error:

pi@raspberrypi:~ $ rustup toolchain install stable-arm-unknown-linux-gnueabi
info: syncing channel updates for 'stable-arm-unknown-linux-gnueabi'
info: latest update on 2017-08-31, rust version 1.20.0 (f3d6973f4 2017-08-27)
info: downloading component 'rustc'
 37.2 MiB /  37.2 MiB (100 %) 515.2 KiB/s ETA:   0 s                
info: downloading component 'rust-std'
 51.5 MiB /  51.5 MiB (100 %) 871.5 KiB/s ETA:   0 s                
info: downloading component 'cargo'
  3.2 MiB /   3.2 MiB (100 %) 567.2 KiB/s ETA:   0 s                
info: downloading component 'rust-docs'
  3.7 MiB /   3.7 MiB (100 %) 364.1 KiB/s ETA:   0 s                
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'cargo'
info: installing component 'rust-docs'

  stable-arm-unknown-linux-gnueabi installed - (error reading rustc version)

And when I try to cargo geckodriver I got this error:
pi@raspberrypi:~/geckodriver-0.18.0 $ cargo build
error: process didn't exit successfully: `rustc -vV` (exit code: 127)
--- stderr
/home/pi/.rustup/toolchains/stable-arm-unknown-linux-gnueabi/bin/rustc: error while loading shared libraries: librustc_driver-6fdeae3afabd119a.so: cannot open shared object file: No such file or directory

**Comment by bjorn3** [comment]
You need to use `rustup target add arm-unknown-linux-gnueabi` instead of `rustup toolchain install stable-arm-unknown-linux-gnueabi`. The former adds a cross-compilation target, while the later installs a compiler which only runs on `arm-unknown-linux-gnueabi` itself.
