### ISSUE TITLE
Document the new individual const fn feature gates

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#44644]
Introduced in #43017. Do they need individual tracking issues as well?

**Comment by durka** [comment]
Also, this information should be exposed in rustdoc somehow. cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
I'm not sure how though...

**Comment by est31** [comment]
@durka features can share tracking issues. The other way doesn't work though, a feature can only have at most one tracking issue.

**Comment by durka** [comment]
@est31 these aren't normal features so we can do whatever we want :) My plan is to create one tracking issue for all of them, and if one function turns out to need a lot of discussion it can be split off.

**Comment by est31** [comment]
@durka all I'm saying that there is precedent for features sharing tracking issues, but there is no precedent for features having multiple tracking issues. Why would that make sense in the first place? It would just confuse people to have multiple tracking issues for one feature gate. Anyway, I definitely agree with having one tracking issue for all the const fn feature gates.

**Comment by durka** [comment]
Right. Maybe it should just stay as #24111 if we can edit the top post.

**Comment by steveklabnik** [comment]
I'm a bit confused; introducing new features should require new pages in the unstable book, it doesn't seem like they exist though?

tagging as medium to sort this out

**Comment by est31** [comment]
@steveklabnik it autogenerates missing files during doc generation, in a step before the actual md is converted to html so the stub shows up in the rendered output. This makes contributing to the compiler easier because its less red tape to add a new feature. Users will still see the stub, so nothing has changed for them. If autogeneration doesn't work, please ping me!

**Comment by steveklabnik** [comment]
> If autogeneration doesn't work, please ping me!

Yes, I think that's the problem, as we're not seeing pages for those feature gates.

**Comment by durka** [comment]
They aren't real feature gates, they are the new `#[rustc_const_unstable] `
attribute, so likely they never got added to the tooling/lints.

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/45671 should have made this possible, and we don't require docs for any particular flags, so closing!
