### ISSUE TITLE
Can offset be called on a null pointer?

### ISSUE THREAD

**Issue by joshlf** [rust-lang/rust#44681]
The [`offset`](https://doc.rust-lang.org/std/primitive.pointer.html#method.offset) method on raw pointers produces a new pointer `count * size_of::<T>()` bytes beyond the receiver.

Is it safe to call on a null pointer? The docs don't mention it, but LLVM defines dereferencing a null pointer as UB, so I'm wondering whether it would be well-defined.

**Comment by kennytm** [comment]
> Both the starting and resulting pointer must be either in bounds or one byte past the end of an allocated object.

The null pointer is not in bounds of any allocated objects. Thus UB.

---


Also, it is UB in C and C++.

https://stackoverflow.com/questions/15608366/is-performing-arithmetic-on-a-null-pointer-undefined-behavior

**Comment by joshlf** [comment]
Does that imply that you can't use `offset` to implement an allocator? Because that's how I'm using it. I wonder if there's a way to explain those restrictions without referring to allocated objects. I presume LLVM doesn't actually care about allocated objects, but rather cares about some more subtle conditions involving aliasing and whatnot?

**Comment by kennytm** [comment]
There's `wrapping_offset` which is safe...

**Comment by joshlf** [comment]
Ah, gotcha. That answers my question; closing.
