### ISSUE TITLE
Tracking issue for impl trait in const/static/let

### ISSUE THREAD

**Issue by withoutboats** [rust-lang/rust#44686]
This is a tracking issue for `impl Trait` in the types of consts, statics, and lets, a part of rust-lang/rfcs#2071

Blocking stabilization:

- [ ] Implement
- [ ] Document

**Comment by nikomatsakis** [comment]
I am closing this as a duplicate of https://github.com/rust-lang/rust/issues/34511

**Comment by Centril** [comment]
New tracking issue: https://github.com/rust-lang/rust/issues/63065
