### ISSUE TITLE
support singleton queries

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#44699]
I was talking to @michaelwoerister the other day and he observed that a lot of our queries wind up (a) taking a `CrateNum` as argument and (b) only being valid for the `LOCAL_CRATE`. 

Some examples:

- `crate_variances`
- `typeck_item_bodies`
- `borrowck`
- `crate_inherent_impls`
- `crate_inherent_impls_overlap_check`

It seems like it might be nice to support *singleton* queries, where there is no key at all. These queries could forego the hashmap and just be stored in a `RefCell<Option<...>>`. They would be invoked like `tcx.crate_variances()`. 

[Mentoring instructions here.](https://github.com/rust-lang/rust/issues/44699#issuecomment-330908814)

**Comment by euclio** [comment]
I'd be interested in working on this. Heads up that I haven't worked on this part of the compiler before.

**Comment by nikomatsakis** [comment]
@euclio great! I don't have time for *super* detailed notes, but let me leave a few tips to maybe help get you started. First off, you should read up on [how queries work](https://github.com/rust-lang/rust/tree/master/src/librustc/ty/maps) and take a look at [the macro that generates them](https://github.com/rust-lang/rust/blob/master/src/librustc/ty/maps/plumbing.rs#L141).

This is going to take just a *touch* of macro hacking, so hopefully you're a bit familiar with that. In particular, right now queries [*always* takes a key](https://github.com/rust-lang/rust/blob/master/src/librustc/ty/maps/plumbing.rs#L144) -- that's the `$K:ty` business there. I think the ideal syntax here would be that you can write `[] fn foo() -> Type`, i.e., no key type at all. This will then require changing the macro from `$K:ty` to something like `$($K:ty)?` -- i.e., to make the key optional. You'll then have to chase through the places that it expands to make it work out. (How familiar are you with macro-rules?)

**Comment by euclio** [comment]
I've done a fair amount with macro_rules, so I don't think that will be a problem. This should be enough for me to get started, thanks!

**Comment by euclio** [comment]
Haven't had a chance to work on this, sorry. If someone else wants to work on it, go ahead!

**Comment by versusvoid** [comment]
@nikomatsakis 
I'm looking into problem and have couple of questions:

1. `borrowck` at [master](https://github.com/rust-lang/rust/blob/968b6206cb140a51f2e3cc3d7841aed51b0d64d9/src/librustc/ty/maps/mod.rs#L198) takes `DefId` as key, which doesn't look constant in invocations I found. Should it be left as is?
2. Should new macro support only one hard-coded default value `LOCAL_CRATE`, or potentially any?

I already have compiling solution and will make PR after some polishing.

**Comment by michaelwoerister** [comment]
@versusvoid I can at least answer question (1): Yes, `borrowck` should be left as is. Maybe @nikomatsakis meant something else there?

**Comment by nikomatsakis** [comment]
@versusvoid 

> `borrowck` at master takes DefId as key, which doesn't look constant in invocations I found. Should it be left as is?

Yeah, sorry, the `borrowck` query is not a singleton query. Not sure why I added it to the list. 

> Should new macro support only one hard-coded default value `LOCAL_CRATE`, or potentially any?

I'm not sure I understand this. Eventually anyway I'd prefer to see no key at all. That is, the provider would just have the type `fn(TyCtxt<..>)`. However, maybe it's worth -- as a first step -- making a kind of "key w default value", in which case hard-coding `LOCAL_CRATE` seems fine.

> Should I remove key argument from corresponding functions in Providers?

Yes.

> I already have compiling solution and will make PR after some polishing.

Oh, nice!

**Comment by versusvoid** [comment]
> I'm not sure I understand this.

Macro generates calls to functions `dep_graph.with_eval_always_task()` and `dep_graph.with_task()` which take `key` as argument. I can:
1. Hard-code `LOCAL_CRATE` for singleton queries
2. Add default key like `$($default_key:expr)*` to query definition signature

**Comment by eddyb** [comment]
I disagree with this, see https://github.com/rust-lang/rust/pull/46165#issuecomment-346156732.

**Comment by steveklabnik** [comment]
Triage: no idea.

**Comment by pnkfelix** [comment]
discussed in today's wg-incr-comp meeting.

This remains an interesting idea.

Reading the thread at https://github.com/rust-lang/rust/pull/46165#issuecomment-346156732 , it is clear that there are various design choices to be made in how to go about this; the outline written in the description above is probably *not* the way that the stakeholders from T-compiler want it to be done.

So, I'd suggest that anyone who wants to do this (as a mentorship issue) should read that thread, come up with a design based on that thread, and then file an MCP with T-compiler to give it plenty of visibility.

**Comment by cjgillot** [comment]
We now support using `()` as a query key.
