### ISSUE TITLE
Hangs on derive macro invoked by format string macro

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#44692]
The compiler hangs when compiling the following code.

```rust
macro_rules! hang {
    () => {
        {
            #[derive(Clone)]
            struct S;

            ""
        }
    }
}

fn main() {
    format_args!(hang!());
}
```

This is a regression in 1.20.0. The same code terminates with an error "format argument must be a string literal" in 1.19.0, which is the correct behavior.

**Comment by dtolnay** [comment]
According to @steffengy in https://github.com/rust-lang/rust/issues/47188#issuecomment-357345082 -- this is hitting an infinite loop in [libsyntax_pos/lib.rs#macro_backtrace](https://github.com/rust-lang/rust/blob/0258c6dacaa6e187ae9bf744fd3184e79f78f2ef/src/libsyntax_pos/lib.rs#L333). See that comment for details.

**Comment by dtolnay** [comment]
Transferring nomination by @jonas-schievink in #62167.

**Comment by pnkfelix** [comment]
triage: P-high. Removing nomination. Assigning to @petrochenkov for primary investigation, and to myself to follow up on it.

**Comment by petrochenkov** [comment]
Accidentally fixed in https://github.com/rust-lang/rust/pull/62476.
