### ISSUE TITLE
Book 2nd edition is broken on stable and beta

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#44704]
The current stable and beta docs are missing a single javascript file, `store.js`.

Stable rust builds with `mdbook=0.0.22` In `0.0.23`, `mdbook` introduced a new javascript file, `store.js`. The Book second edition uses a custom template in order to display the "this is a draft" banner, and so, we updated it to include the new file https://github.com/rust-lang/book/pull/783. However, this was wrong; it shouldn't have been done until `mdbook` was updated in the main repository. As such, things are now very broken:

<img width="775" alt="book" src="https://user-images.githubusercontent.com/27786/30607860-81f0bf1c-9d44-11e7-8357-720cfaca6e79.png">

As nightly has updated `mdbook`, this has been fixed, but having the main way of learning Rust broken for ~10 weeks isn't great.

### For stable

We could fix the online docs by just uploading `store.js` to the appropriate place. I am normally very against changing what we distribute after the fact, but simply adding a file seems very minimal.

While this regression is in some sense very serious, I don't think it's worth cutting a new stable for, with this workaround.

### For beta

In my opinion, we should send in a backport fix to beta. This involves upgrading mdbook on beta.

----------------------------------

Tagging as "regression from stable to nightly" even though it's been fixed in nightly; this is about what to do for stable and beta. Tagging @rust-lang/infra for the stable fix, tagging @rust-lang/docs for the beta fix.

**Comment by carols10cents** [comment]
We could also remove the line that was added in https://github.com/rust-lang/book/pull/783/files from all the HTML files for the book for all the versions...... which is arguably "more correct", but also more work.

**Comment by carols10cents** [comment]
@steveklabnik have you confirmed that adding the store.js file to a book built with mdbook 0.22 fixes the styling?

**Comment by steveklabnik** [comment]
> We could also remove the line that was added in https://github.com/rust-lang/book/pull/783/files from all the HTML files for the book for all the versions...... which is arguably "more correct", but also more work.

That is modifying the code we released, which is against immutable releases, which I am pretty against.

> have you confirmed that adding the store.js file to a book built with mdbook 0.22 fixes the styling?

I am doing so right now.

**Comment by steveklabnik** [comment]
Every version ever published with mdbook now looks broken https://doc.rust-lang.org/1.17.0/book/

I remember checking this before release; there's no way that the book has been broken for three releases and nobody has noticed.

**Comment by aturon** [comment]
cc @rust-lang/infra

**Comment by steveklabnik** [comment]
(@ashelygwilliams and I are debugging this right now)

**Comment by steveklabnik** [comment]
So, @ashleygwilliams figured it out:

    <body class=""light"">

Yes, there are extra quotes in there. However, they're not in view-source, only in the final output. This makes me suspect JavaScript.

But it's still extremely suspicious that not one person noticed this, not sure *why* this is happening.

**Comment by ashleygwilliams** [comment]
if you change the theme, the error disappears. so that's a quick fix to offer people.

taking a look at the old javascript to see if i can discern what's up.

**Comment by steveklabnik** [comment]
Okay! We think we've got it.

mdbook stores the current theme in localstorage. This *did* change in newer/older mdbook, but it looks like this, basically:

```
    var theme = localStorage.getItem('theme');
    if (theme === null) { theme = 'light'; }
```

However, if you visit the nightly docs, and run this in your JS console:

```text
>> localStorage.getItem("theme")
"\"light\""
```

See the quotes?  If you go back to stable docs, and delete the theme from localstorage, and then refresh, it works, and

```text
>> localStorage.getItem("theme")
"light"
```

So: TL;DR: this is an mdBook bug. It only manifests if you read the nightly docs, then go back and look at the stable docs.

So, the solution is, fix the bug in mdBook, update, and backport to beta.

**Comment by steveklabnik** [comment]
> So, the solution is, fix the bug in mdBook, update, and backport to beta.

Correction: only nightly needs to be fixed; it's what's poisoning localstorage. No need to update the `store.js` file either, so un-tagging @rust-lang/infra . 

Whew! This bug was nasty.

**Comment by carols10cents** [comment]
😱🙀😱🙀😱🙀😱🙀

**Comment by frewsxcv** [comment]
Was this resolved upstream with https://github.com/azerupi/mdBook/pull/449 ? If so, is the next step here just an mdbook bump?

**Comment by steveklabnik** [comment]
Yes, we need an mdbook release and then bump the version here.

**Comment by ExpHP** [comment]
To my understanding this fix has prevented new cases of corrupted local storage from being created, but does not help the existing cases.  From what I gather, [localStorage never expires](https://stackoverflow.com/a/2327030/166765), so users who do not regularly clear their data may remain affected for arbitrarily long.

**Comment by steveklabnik** [comment]
Yes. To be clear, fixing your localStorage is trivial: change to another theme and then change back to the theme you wanted, and all will be well.

**Comment by XX** [comment]
@steveklabnik I confirm. But I chose the same theme (Light) and the styles were restored immediately.

**Comment by steveklabnik** [comment]
Yeah, any theme choice should do it. Thanks for the clarification :)
