### ISSUE TITLE
Actually highlight the ? operator in rendered code

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#44706]
About one year after the ? operator was stabilized with the [promise](https://github.com/rust-lang/rust/issues/31436#issuecomment-251681299) that it will get highlighting when being rendered, work on getting hightlighting of ? into text editors and renderers has stalled.

I've done work on this for rustdoc in #37102. For (current, non rewritten) rustdoc, it looks like this:

![image](https://user-images.githubusercontent.com/8872119/30611812-d2dde6e6-9d82-11e7-83af-0d430aff725a.png)

But I've found a couple of places where there is still no highlighting:

- [ ] [Sublime text](https://github.com/sublimehq/Packages/blob/master/Rust/Rust.sublime-syntax) (This is a [screenshot](https://imgur.com/clfUtkm) of how its rendered using syntect)
- [ ] [mdbook](https://github.com/azerupi/mdBook) (see it in action [here](https://web.archive.org/web/20170919192335/https://doc.rust-lang.org/book/second-edition/ch09-02-recoverable-errors-with-result.html#a-shortcut-for-propagating-errors-), [backup](https://web.archive.org/web/20170919192335/https://doc.rust-lang.org/book/second-edition/ch09-02-recoverable-errors-with-result.html#a-shortcut-for-propagating-errors-))
- [ ] [kate](https://cgit.kde.org/syntax-highlighting.git/tree/data/syntax/rust.xml) ([screenshot here](https://imgur.com/a/7iSNZ))
- [ ] [rust playground](https://github.com/integer32llc/rust-playground)
- [ ] [vim](https://github.com/rust-lang/rust.vim)
- [ ] RustyCode VSCode plugin

If you stumble across additional cases, please mention them here!

I know these projects are separate from Rust itself, but its important to get ? highlighted consistently so that it can't be overlooked.

cc @Stebalien @eddyb @GuillaumeGomez

**Comment by eddyb** [comment]
I believe I locally hacked this into my kate syntax highlighting files:
```xml
<DetectChar char="?" attribute="QM" context="#stay"/>
```
```xml
<itemData name="QM" defStyleNum="dsError" bold="true" underline="false"/>
```

**Comment by cramertj** [comment]
> If you stumble across additional cases
The VIM plugin (using 'rust-lang/rust.vim') and the RustyCode VSCode plugin don't highlight `?`.

**Comment by ishitatsuyuki** [comment]
Given that most IDEs have moved to RLS, is this still a thing?
