### ISSUE TITLE
Enormous perf.rlo regression from a single commit on September 18

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#44719]
perf.rust-lang.org is showing a huge regression. Syntex regressed by 100%, while about eight others regressed by 10% to 50%. Mousing over the graph, the commit that exhibits this regression is https://github.com/rust-lang/rust/commit/0701b37 , which is difficult to immediately diagnose as it's a rollup.

**Comment by Mark-Simulacrum** [comment]
cc @rust-lang/compiler: Nominating for assignment.

**Comment by eddyb** [comment]
Looking at the PR list, #44364 looks most likely, cc @michaelwoerister @nikomatsakis @alexcrichton

**Comment by alexcrichton** [comment]
This was [discussed on the PR](https://github.com/rust-lang/rust/pull/44364#issuecomment-330414538) and concluded as "no action needed", so closing.
