### ISSUE TITLE
filter lifetimes in impl Trait

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#44725]
currently, `impl Trait` usages capture all lifetimes that are in scope (and this kind of fails around late-bound lifetimes). In the newer RFC, the proposal was that they should only capture those lifetimes that are used in the impl trait itself.

[Here are some mentoring instructions I wrote-up from before on how one might do this.](https://github.com/rust-lang/rust/issues/34511#issuecomment-330347601) But another way to think about this might be to think about implementing `abstract type` (perhaps in a limited form) and desugaring to that.

However, work on this issue is blocked on #44727.

**Comment by nikomatsakis** [comment]
See also: https://github.com/rust-lang/rust/issues/44727

**Comment by ErichDonGubler** [comment]
This issue is now ready to be worked on, right? :)

**Comment by Yoric** [comment]
Since #44727 is closed, I'm interested in working on this. @nikomatsakis a few pointers on which files I'm supposed to dig into would be helpful, though.

**Comment by nikomatsakis** [comment]
Er, sorry, this is done actually. =)
