### ISSUE TITLE
Duplicate warnings in Visual Studio Code with Rust (rls) plugin.

### ISSUE THREAD

**Issue by objectref** [rust-lang/rust#44744]
Hi to all here.

I installed Rust in macOS Sierra MBP machine by using the "curl hdttps://sh.rustup.rs -sSf | sh" command. Then i installed the Rust (rls) plugin and the LLDB Debugger one. The Rust plugin asked me if i wanted to install nightly builds and as i recall that it needs that at this time, i said yes and it did it's thing. 

I can successfully build and run a rust program from inside VS Code. I just noticed (as you can see in the attached picture) that any warning is reported twice.
![rustissue](https://user-images.githubusercontent.com/21091147/30702792-97339b0c-9ef6-11e7-8c8e-60fba4c8ee5f.jpeg)

And if i do a "dustup update" in a terminal, i see one entry for
"stable-x86_64-apple-darwin unchanged - rustc 1.20.0 (f3d6973f4 2017-08-27)"

and another one with:
" nightly-x86_64-apple-darwin unchanged - rustc 1.22.0-nightly (01c65cb15 2017-09-20)"

Does this mean i end up with 2 versions of the compiler and thus the duplicated warning or not?

Thanks a lot for any help in a newbie in Rust!

Anthony

**Comment by objectref** [comment]
Hhmm..i think i figured out what is happening: This happens when i compile (F6), so i imagine that the first warning is reported from the RLS and the second from the compiler (as it says there). The way to program for now is to watch from warnings/errors at the RLS level first, i think. And when ok, then i do a full compilation.

But what about these 2 rust compilers i see when running rustup update? Is the one being used internally by the RLS Service (v 1.22.0 nightly) and the other (v. 1.20.0) when i compile from inside VS Code?

Thank you, again!

**Comment by Mark-Simulacrum** [comment]
cc @nrc

**Comment by workingjubilee** [comment]
RLS has been deprecated so this issue has been "fixed". :sweat_smile:

Please report any issues you have with [rust-analyzer](https://github.com/rust-lang/rust-analyzer) as new issues!
