### ISSUE TITLE
rustdoc: Masked functions still appear in the search result.

### ISSUE THREAD

**Issue by kennytm** [rust-lang/rust#44740]
Repro:

1. Go to nightly docs
2. Search for "aborting" (or just go to https://doc.rust-lang.org/nightly/std/?search=aborting)
3. Note that the functions `aborting_div` and `aborting_rem` appeared.
4. Clicking into the result will not jump to any functions.

Expected: `aborting_div` and `aborting_rem` should not appear in the search result.

The `aborting_div` and [`aborting_rem`](https://doc.rust-lang.org/1.20.0/std/primitive.u32.html#method.aborting_rem) methods are part of the `Int` trait in `compiler_builtins` which is not supposed to be exposed. The documentation about this trait is successfully hidden thanks to #44026, but the search entry still exists.

cc @QuietMisdreavus

**Comment by GuillaumeGomez** [comment]
Taking a look.

**Comment by GuillaumeGomez** [comment]
Hum, I thought a check was missing but it doesn't seem to be the case, will require a deeper look.
