### ISSUE TITLE
Importing macros using glob imports works without the `use_extern_macros` feature flag.

### ISSUE THREAD

**Issue by Lymia** [rust-lang/rust#44750]
As [this code](https://play.rust-lang.org/?gist=fed88ff8a264256e703f202c1096968b&version=stable) demonstrates, you can currently import macros using `use crate_name::*;` rather than `#[macro_use]` even on stable Rust.

My understanding is that this functionality is part of `use_extern_macros` which is currently not stabilized.

**Comment by abonander** [comment]
Some discussion concerning this bug has popped up on Reddit: https://www.reddit.com/r/rust/comments/85he4j/hey_rustaceans_got_an_easy_question_ask_here/dw6b71d/

**Comment by petrochenkov** [comment]
`use_extern_macros` was stabilized in 1.30, so this issue is no longer relevant.
