### ISSUE TITLE
Weird behavior with function pointers and type inference

### ISSUE THREAD

**Issue by alekratz** [rust-lang/rust#44756]
I've been using `std::collections::HashMap` for using some arbitrary key type to map to function pointer values. A minimal example:

```rust
use std::collections::HashMap;
fn foo(arg: usize) {
    println!("you called foo with {}", arg);
}
fn bar(arg: usize) {
    println!("you called bar with {}", arg);
}
fn baz(arg: usize) {
    println!("you called baz with {}", arg);
}
fn main() {
    let mut funs = HashMap::new();
    funs.insert("foo", foo as fn(usize));  // A
    funs.insert("bar", bar);
    funs.insert("baz", baz);
    funs["bar"](333);
}
```

Note the explicit cast on the line marked A. If you remove the explicit cast, compilation fails with:

```
error[E0308]: mismatched types
  --> main.rs:18:24
   |
18 |     funs.insert("bar", bar);
   |                        ^^^ expected fn item, found a different fn item
   |
   = note: expected type `fn(usize) {foo}`
              found type `fn(usize) {bar}`

(and also an error about baz; omitted for brevity)
```

You can always rectify this with setting the explicit type (e.g. `let mut funs: HashMap<&'static str, fn(usize)> = HashMap::new();`) but this isn't an option when using macros that construct hashmaps, like `hashmap!` from the `maplit` crate; I have to fall back to using an explicit cast to nudge the type inference in the right direction.

**My main question is, is this expected behavior, or is it a bug?**

**Comment by jonas-schievink** [comment]
This is expected, as the value stored in the HashMap needs to be inferred (the `V` type parameter).

The first thing that hints at the correct type is the value passed to the first `insert` call. When this is `foo`, the compiler uses the type of `foo` for `V`, which is a type specific to the function `foo` (like the error message says). The next `insert` call then passes an incompatible type (the compiler will try to apply coercions, but no coercion results in `fn(usize) {foo}`).

When you cast the value first, the compiler will use the type `fn(usize)` for `V` - a function pointer. All values passed to the next `insert` calls can be coerced to such a function pointer, so all is well.

**Comment by alekratz** [comment]
I see. Obviously this isn't a bug then. Out of curiosity, why do individual functions get their own unique, incompatible types, even when their signature matches?

**Comment by jonas-schievink** [comment]
I believe that was mostly done to mirror the behaviour of closures, which also get their own anonymous type.

A neat side-effect of this is that you can pass functions to methods that expect any `F: Fn...`, and the method will be monomorphized for each individual function it's used with (like with closures). Whether that's important for performance, I don't know.
