### ISSUE TITLE
Fails to build without config.toml

### ISSUE THREAD

**Issue by diwic** [rust-lang/rust#44768]
$ ./x.py build
    Traceback (most recent call last):
      File "./x.py", line 20, in <module>
        bootstrap.main()
      File ".../rustc/src/bootstrap/bootstrap.py", line 756, in main
        bootstrap()
      File ".../rustc/src/bootstrap/bootstrap.py", line 683, in bootstrap
        with open(args.config or 'config.toml') as config:
    IOError: [Errno 2] No such file or directory: 'config.toml'

`cp config.toml.example config.toml` fixes the issue, but is this intended to be a required step? According to README.md and CONTRIBUTING.md it seems like you're only supposed to have to do this in case you actually want to change something in the configuration.

(This is from git master @ 2017-09-22)

**Comment by Mark-Simulacrum** [comment]
Should be fixed once #44754 lands; prioritized.

**Comment by ashtneoi** [comment]
This seems to be fixed. (#44754 was merged way back in 2017, and I tested it myself with `1.25.0` just now.)
