### ISSUE TITLE
Fix Debug implementations that hardcode the representation of a struct

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#44771]
The `Debug` implementation for `Mutex` looks like this:

```rust
write!(f, "Mutex {{ data: {:?} }}", &*guard)
```

This is bad because it does not honor the `#` pretty-print modifier.

```rust
println!("{:#?}", std::sync::Mutex::new(5));
```

It prints

```
Mutex { data: 5 }
```

instead of

```
Mutex {
    data: 5
}
```

A correct implementation would use `debug_struct`.

```rust
f.debug_struct("Mutex").field("data", &*guard).finish()
```

There seem to be lots of instances of this in the standard library. The following search is a good place to start.

```
grep -r ' {{ ' libcore libstd
```

**Comment by MaloJaffre** [comment]
I'll try to tackle and fix this issue.
