### ISSUE TITLE
There is no easy way to convert locally-encoded string to `str`

### ISSUE THREAD

**Issue by uzytkownik** [rust-lang/rust#44793]
While encoding is invisible for Rust on modern Linux as everything is UTF-8 encoded some legacy systems and Windows is not. There seems to be no easy way to convert `&[u8]` into `&str` if `&[u8]` is locally encoded (`OsString` comes close but method is unix-specific).

**Comment by kennytm** [comment]
You need to use the [encoding](https://docs.rs/encoding/0.2.33/encoding/) crate for this.

**Comment by uzytkownik** [comment]
@kennytm Even with encoding package I need to somehow guess the current encoding. For example for WinAPI I need to call [GetAPC](https://msdn.microsoft.com/en-us/library/dd318070(VS.85).aspx) and have a switch to correlate and on Linux I need to call [localeconv(3)](http://man7.org/linux/man-pages/man3/localeconv.3.html). This seems to be way too low-level code for cross-platform to deal with and it is required for basic I/O:

    fn main() {
        // Does this works? Who knows, let's hope it's not on Chinese compute. Who needs i18n anyway.
        std::io::stdout().write("foo".as_slice());
        let mut file = std::fs::File::new(".local_file");
        let vec = std::vec::Vec::new();
        file.read_to_end(vec);
        // And now what? How can I convert to str if I don't know local encoding?
    }

**Comment by bluss** [comment]
You can use the same logic as usual, using the locale's encoding and so on, by having libraries supply the implementation. Rust's standard library does not ship with encoding or locale support.

It's true that C has some features out of the box that Rust doesn't have. Rust is gaining features all the time, so maybe you want to look into the Rust RFC process to see how one can take part in that.

**Comment by uzytkownik** [comment]
> You can use the same logic as usual, using the locale's encoding and so on, by having libraries supply the implementation. Rust's standard library does not ship with encoding or locale support.

Fair enough but Rust made a choice about encoding making it essential for i18n. It might not be visible on Linux and on US computers because the encoding happens to be compatible (UTF-8 and ASCII respectively) but I would guess vast majority of programs written in Rust is incorrect because of it. Compare it with glib which made similar choice to store strings in UTF-8 but provided [g_locale_from_utf8](https://developer.gnome.org/glib/2.54/glib-Character-Set-Conversion.html#g-locale-to-utf8) and [g_filename_to_utf8](https://developer.gnome.org/glib/2.54/glib-Character-Set-Conversion.html#g-filename-to-utf8).

> It's true that C has some features out of the box that Rust doesn't have.

I think it is more of a case of Rust having more features than C in this particular case because it does care about encoding. C on the other hand have much low level handling of strings and can get away with avoiding the issue.

It's no different than potential errors/missing features in borrowing analyzer - it's not that Rust has less features but that features it has cause a limitations (in addition to large amount of benefits - don't get me wrong, I applaud choice of UTF-8, it is just that it made interop with filesystem harder).

> Rust is gaining features all the time, so maybe you want to look into the Rust RFC process to see how one can take part in that.

Yeah. That's why I filled this issue - for Rust to get a new feature. AFAIK RFC process is much more formal and details an actual implementation as oppose to just an issue. I might post an RFC but that's a separate step.

**Comment by Ixrec** [comment]
What's the exact use case you're looking for that you're saying C handles better? Some parts of your comments make it sound like you just want to pass a "string" of arbitrary foreign bytes around without worrying about what encoding it has, and others make it sound like you want a way to guess what the encoding is for some arbitrary bytes. If it's the former, I think the answer is just "use `std::ffi::CStr`".

**Comment by uzytkownik** [comment]
@Ixrec sort of kind of no. The problem is that `std::ffi::CStr` and `str` live in two different worlds and essentially cannot interact in rust. This is a big problem as they must and do interact in Rust and it creates situation where Rust essentially _pretends_ to care about encoding leaving most of the details to programmers which might not even know there is an issue.

Take `std::io` - it assumes all files are in sane encoding also known as UTF-8. It will work on modern Linux distributions. It will work as long as you are American and don't care about anything beyond 127 characters. However if you try to use Rust on older Linux installation or non-American Windows you are up to surprise as you can get garbage out of `println!`. 

For example lets assume Grzegorz Brzęczyszczykiewicz (yes, it is a joke name but problem is real) is using CP-1250 encoding as he is using Windows. He expects the following program in Rust:

    fn main() {
        println!("Hello Grzegorz Brzęczyszczykiewicz");
    }

To print `Hello Grzegorz Brzęczyszczykiewicz`. However as Rust is using UTF-8 the output would be `47727a65676f727a2042727ac499637a79737a637a796b69657769637a` not `47727a65676f727a2042727aea637a79737a637a796b69657769637a` causing the program to dutifully print `Hello Grzegorz BrzÄ™czyszczykiewicz` on screen (if source file was saved in UTF-8) or fail to compile due to invalid continuation bytes (if source file was saved in CP-1250). This is not limited to console but also to any file which is in local encoding. [I don't have a CP-1250 system with me at this time so it is conjured from reading source code, not proven]

Now I discovered this encoding blindness when wrapping an API which transfers strings in local encoding (just as any other C program/library does). I personally happen not to see the issue as my local encoding is UTF-8. After trying to look into it I found no way to actually convert to/from local encoding. That means that following tasks are impossible:

 - I have a file F. I want to read a string and check if it is "Grzegorz Brzęczyszczykiewicz"
 - I have a file F. I want to append string "Grzegorz Brzęczyszczykiewicz"" (or get an error if that's impossible)
 - I have a string "Grzegorz Brzęczyszczykiewicz". I want to print it on screen.
 - Someone wrote "Grzegorz Brzęczyszczykiewicz" on stdin. I want to read it to String

Unless we assume we happen to be on Linux with UTF-8 encoding (instead of say system installed at the beginning of century encoded in ISO-8859-2) currently none of those task are possible with pure `libstd` due to encoding issues - or even `libstd` + `encoding` as we need to somehow know local encoding and list in `encoding` is hardly exhaustive. 

As C does not care about encoding reading and writing just works as bytes are bytes. In Rust we would fail checks in `std::str::from_utf8` (for good reason as what we try to read is not UTF-8) on input. 

**I'm sorry for saying this as it is unfair for rust dev** who put a lot of into this language but it seems that internationalization on non-Linux platforms in Rust is broken with current API and probably most libraries are handling it incorrectly just as `std::io` does. Rust alludes to it in [`OsString` implementation](https://doc.rust-lang.org/nightly/std/ffi/struct.OsString.html) but at the end of the day all its convertion function disregard local encoding and if anyone had an `OsString` which happend to contain "Ä™" (C499) on CP-1250 system `.into_system` would be read as "ę" (C499) instead of "Ä™" (c384e284a2).

**Comment by dtolnay** [comment]
I agree that the concept of "contiguous bytes representing a string encoded in the system's current locale" is not solved by what is available in the standard library. Thanks for raising this issue!

From what has been discussed in this thread, this sounds like a complicated domain with plenty of tradeoffs. I don't believe the libs team has the right expertise to arrive at the best solution here, so I would prefer to see this explored in a library on crates.io. Once there is a high-quality library that we can agree solves the use cases discussed in this issue, I would be open to considering what parts make sense to incorporate into the standard library.

**Comment by uzytkownik** [comment]
? I agree that the concept of "contiguous bytes representing a string encoded in the system's current locale" is not solved by what is available in the standard library. Thanks for raising this issue!

@dtolnay  See the thread. I think the problem goes way beyond 'contiguous bytes representing a string encoded in the system's current locale' as this affects all strings going to/from Rust program. 

> From what has been discussed in this thread, this sounds like a complicated domain with plenty of tradeoffs.

Could you elaborate? Since this request is for local encoding -> UTF8 back conversion it seems rather limited compared to full i18n. Furthermore it seems to be very important for correctness (see my last comment). Implementation seems to be rather straightforward as I was able to write conversion function for POSIX in about an hour. I haven't tested it but it should take at most a few more.

It might be good to think where those two functions should exists in Rust ecosystem - I guess they should be part of OsStr/OsString and replace 'useless' to_str functions but I don't feel competent in that aspect.

However the real problem is that such libraries wouldn't be widely adopted as:

 1. Most people don't know about problem as they are using English and/or Linux
 2. The usage of such library would be horrible. See example below

```
// This is kind of correct/portable Rust program:
extern crate localencoding;

fn main() {
    let str: Cow<'static, [u8]> = localencoding::encode("Hello Grzegorz Brzęczyszczykiewicz");
    std::io::stdout().write(str.borrow());
}

// This program is not portable

fn main() {
    println!("Hello Grzegorz Brzęczyszczykiewicz");
}
```

**Comment by beroal** [comment]
> Once there is a high-quality library that we can agree solves the use cases discussed in this issue, I would be open to considering what parts make sense to incorporate into the standard library.

As far as I understand, if you plan to solve the issue with a new library, not only the new library should replicate `std::io`, but you need to convince everybody to move to the new library. It would be easier for everyone if `std::io` converted data with the current OS locale.
