### ISSUE TITLE
It's not possible to have a recursive interaction with C glue without dynamic dispatch

### ISSUE THREAD

**Issue by uzytkownik** [rust-lang/rust#44799]
I tried to avoid double dynamic dispatch when writing binding to C++ library. I tried to write following code:

    cpp!{{
        #include <library.h>
        extern void __rust_foo_foo(void *hnd, char *str);
        class Foo : Base {
            void *hnd;
            Foo(void *hnd) : hdn(hnd) {}
            void foo(StringArray &strarr) { // Overload of a method
                String string;
                for (int i = 0; StringArray.Has(i, &string); i++) {
                    __rust_foo_foo(hnd, string.Text());
                }
            }
        }
    }}
    
    #[no_mangle]
    pub extern fn __rust_foo_foo(vec: &mut std::vec::Vec<*mut u8>, chr: *mut u8) {
        vec.push_back(chr);
    }

    pub fn run_foo() -> std::vec::Vec<*mut u8> {
        let mut vec = std::vec::Vec::new();
        {
            let vec_ref = &mut vec;
            cpp!([vec_ref as "void *"] -> {
                Foo foo(vec_ref);
                foo.do_something(); // calls foo internally
            });
        }
        vec
    }

Unfortunately it results in undefined references to `__rust_foo_foo` (despite it being an exported object as shown by nm) if I try to link binding to executable. This has a number of drowbacks with regard to siplicity/performance.

    cpp!{{
        #include <library.h>
        typedef void (*__rust_foo_foo)(void *hnd, char *str);
        class Foo : Base {
            void *hnd;
            __rust_foo_foo func;
            Foo(void *hnd, __rust_foo_foo func) : hdn(hnd) {}
            void foo(char *str) { // Overload of a method
                String string;
                for (int i = 0; StringArray.Has(i, &string); i++) {
                    __rust_foo_foo(hnd, string.Text());
                }
            }
        }
    }}
    
    #[no_mangle]
    extern fn __rust_foo_foo(vec: &mut std::vec::Vec<*mut u8>, chr: *mut u8) {
        vec.push_back(chr);
    }
    
    pub fn run_foo() -> std::vec::Vec<*mut u8> {
        let mut vec = std::vec::Vec::new();
        {
            let vec_ref = &mut vec;
            let func = __rust_foo_foo;
            cpp!([vec_ref as "void *", func as "__rust_foo_foo"] -> {
                Foo foo(vec_ref, func);
                foo.do_something(); // calls foo internally
            });
        }
        vec
    }

**Comment by rkruppe** [comment]
Are you really seeing an undefined reference really to `__rust_foo_foo`? I would expect an undefined reference to the name-mangled version of `__rust_foo_foo(void *, char *)`. Try to wrap the C++ declaration of `__rust_foo_foo` in an `extern "C"` block.

**Comment by uzytkownik** [comment]
@rkruppe Sorry. I'm an idiot (or rather I haven't written in C++ in a long time and forgot about mangling. C doesn't have those problems).
