### ISSUE TITLE
run-pass-valgrind tests don't actually run in valgrind

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#44816]
compiletest requires the `--valgrind-path` parameter to be set or it treats run-pass-valgrind tests as normal run-pass tests. It doesn't appear that the build infrastructure ever actually sets this, though.

**Comment by jyn514** [comment]
Mentoring instructions: Add the --valgrind-path arg somewhere around https://github.com/rust-lang/rust/blob/e9e09083674a58d361cd805877be55b5856d2806/src/bootstrap/test.rs#L1429-L1435
You may need to also install valgrind on the CI builders.

**Comment by jyn514** [comment]
Please also add `--force-valgrind` at the same time to avoid issues like this happening again (in fact maybe we should just remove that argument and have it on unconditionally?)
