### ISSUE TITLE
[rustup doc] Make it really local

### ISSUE THREAD

**Issue by JekoTronik** [rust-lang/rust#44826]
Hi Rustaceans !

Today I was in the train, connected to internet throw my tethering phone. In the sub, I don't have internet but I am still connected !
 When I do `rustup doc` my Firefox then pops up and try to reach 

> code.jquery.com
> maxcdn.bootstrapcdn.com
> ...

And so the book takes minutes to load.
Could it be a bit web-less ?

Thank you for considering
Cheers

**Comment by steveklabnik** [comment]
> the book 

This is just the book? Or other parts of the docs?

**Comment by JekoTronik** [comment]
Hi @steveklabnik !
I've faced this behavior mainly with all the links in the "3 The Rust Bookshelf" category.

**Comment by JekoTronik** [comment]
Awesome !
Thank you @steveklabnik !

**Comment by steveklabnik** [comment]
Given that we have the upstream issue, I'm going to close this; it will be fixed next time we upgrade after they fix it 😄 

Thanks again!
