### ISSUE TITLE
MIR-borrowck: Add support for `union` types

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#44831]
The MIR-borrowck prototype code left out support for `union`. Luckily we have test cases that illustrate the omission.
 * You can see list of such tests in the [discrepancy spreadsheet](https://docs.google.com/spreadsheets/d/11RfQxTBpdcQW8y7S2ASHv6Wkljj9j2kQ81eJNxTl3KE/edit?usp=sharing).
 * But for ease of reference, I am also transcribing that list into the first comment on this issue.

So the next step is to  incorporate support for `union` into `librustc_mir/borrow_check.rs`.

**Comment by pnkfelix** [comment]
Transcription of relevant tests according to the [discrepancy spreadsheet](https://docs.google.com/spreadsheets/d/11RfQxTBpdcQW8y7S2ASHv6Wkljj9j2kQ81eJNxTl3KE/edit?usp=sharing). (caveat: data is based on out-of-date pnkfelix/mir-borrowck4 branch)

<details>

| tests failing with ICE: could not find BorrowIndexes for region scope ... |
| ------------- |
| borrowck-union-borrow-nested.rs |
| borrowck-union-borrow.rs |
| borrowck-union-uninitialized.rs |

</details>

**Comment by KiChjang** [comment]
I'm interested in tackling this.

**Comment by arielb1** [comment]
@KiChjang 

So I think a useful first step would be to integrate the spec for borrowing unions here:
https://github.com/rust-lang/rfcs/blob/master/text/1444-union.md#borrowing-union-fields

into the main borrowck spec (yes I know it's called "nll", but it also applies to MIR borrowck) - preferably as a PR against rust-lang/rfcs:
https://github.com/rust-lang/rfcs/blob/master/text/2094-nll.md#borrow-checker-phase-2-reporting-errors

**Comment by KiChjang** [comment]
PR to make changes to the RFC: https://github.com/rust-lang/rfcs/pull/2168

**Comment by Phlosioneer** [comment]
@arielb1 You left a note when ignoring this test:
https://github.com/rust-lang/rust/blob/cf30759a8409bee031ac252ee207452ab4804467/src/test/compile-fail/borrowck/borrowck-thread-local-static-borrow-outlives-fn.rs#L10-L24

When / under what conditions will this be fixed? Can we make an issue to track it or a more descriptive comment, so future issue triage knows what's going on?

**Comment by Phlosioneer** [comment]
Pubmitted a PR. Thanks!
