### ISSUE TITLE
MIR-borrowck: ICE: broken MIR moving out of Lvalue

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#44830]
There are many tests in `compile-fail/borrowck/` that ICE with the same failure: "broken MIR moving out of Lvalue"
 * You can see list of such tests in the [discrepancy spreadsheet](https://docs.google.com/spreadsheets/d/11RfQxTBpdcQW8y7S2ASHv6Wkljj9j2kQ81eJNxTl3KE/edit?usp=sharing).
 * But for ease of reference, I am also transcribing that list into the first comment on this issue.

pnkfelix believes the origin of this problem is that some code processing MIR (probably MIR dataflow) was written under the assumption that all valid MIR will not have moves out of Lvalues, at least for non-`Copy` values. But of course such an assumption only holds for MIR that has actually passed the borrowck analysis (at least under our current separation of concerns in the static analyses of `rustc`), and therefore any dataflow code running *prior to* borrowck on some (erroneous) Rust source file is going to potentially encounter such MIR.
 * Zoxc has pointed out that it is probably `librustc_mir/dataflow/move_paths/builder.rs` that is the culprit here.

The answer here is not to panic from `rustc`, but instead to fail gracefully in some manner and report a nice error diagnostic to the user.

**Comment by pnkfelix** [comment]
Transcription of relevant tests according to the [discrepancy spreadsheet](https://docs.google.com/spreadsheets/d/11RfQxTBpdcQW8y7S2ASHv6Wkljj9j2kQ81eJNxTl3KE/edit?usp=sharing). (caveat: data is based on out-of-date pnkfelix/mir-borrowck4 branch)

<details>

| tests failing with ICE: broken MIR moving out of Lvalue ... |
| ------------- |

**Comment by pnkfelix** [comment]
I'm going to focus on this bug.

**Comment by arielb1** [comment]
This shouldn't be so hard. You'll need to remove the ICE and replace it with proper permission checking that emits the correct errors.

**Comment by pnkfelix** [comment]
Yeah, the biggest part is probably just the refactoring of the existing errors being collected and emitted within AST borrowck, and moving those to the common diagnostics that live in `rustc_mir::util::borrowck_errors`.

**Comment by pnkfelix** [comment]
(my basic goal at this point is to remove all of the ICE's first so that we can then focus on the more interesting places where mir-borrowck is actually producing wrong answers.)
