### ISSUE TITLE
Adding trait impl causes lint on unrelated code to fail

### ISSUE THREAD

**Issue by sgrif** [rust-lang/rust#44850]
Applying this patch:

```patch
diff --git a/diesel/src/macros/mod.rs b/diesel/src/macros/mod.rs
index 349868f..c13a887 100644
--- a/diesel/src/macros/mod.rs
+++ b/diesel/src/macros/mod.rs
@@ -745,6 +745,10 @@ macro_rules! table_body {
                 type Count = Once;
             }
 
+            impl AppearsInFromClause<table> for () {
+                type Count = Once;
+            }
+
             impl<T> AppearsInFromClause<T> for table where
                 T: Table + JoinTo<table>,
             {
```

 to [diesel's codebase as of commit 1fd6be6](https://github.com/diesel-rs/diesel/tree/1fd6be64510684ca4a738ddd207674700fcf8d9f) and running `cargo test --features "sqlite"` causes the following build failure:

<img width="747" alt="screen shot 2017-09-25 at 1 50 25 pm" src="https://user-images.githubusercontent.com/1529387/30827865-d3c14c4a-a1f8-11e7-95c6-8323ddc1870a.png">

That lint should have always been failing, but it seems bad that changing unrelated code caused it to start failing. I unfortunately don't have a more isolated reproduction case

**Comment by Enselic** [comment]
It is tricky to reproduce the original problem since the code is so old. I tried but failed.

@rustbot label +E-needs-mcve

**Comment by jackh726** [comment]
Closing since the reproduction didn't work.
