### ISSUE TITLE
ICE when abusing CoerceUnsized through specialization

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#44861]
I was attempting to figure out the feature landscape for #27941, and I found this ICE when playing with it and specialization:

## Code

```Rust
#![feature(specialization)]
#![feature(unsize, coerce_unsized)]

use std::ops::CoerceUnsized;
use std::marker::Unsize;

pub struct SmartassPtr<A: Smartass+?Sized>(A::Data);

pub trait Smartass {
    type Data;
    type Data2: CoerceUnsized<*const [u8]>;
}

pub trait MaybeObjectSafe {
// fn not_object_safe(self: SmartassPtr<Self>);
}

impl MaybeObjectSafe for () {}

impl<T> Smartass for T {
    type Data = <Self as Smartass>::Data2;
    default type Data2 = ();
}

impl Smartass for () {
    type Data2 = *const [u8; 1];
}

impl Smartass for MaybeObjectSafe {
    type Data = *const [u8];
    type Data2 = *const [u8; 0];
}

impl<U: Smartass+?Sized, T: Smartass+?Sized> CoerceUnsized<SmartassPtr<T>> for SmartassPtr<U>
    where <U as Smartass>::Data: std::ops::CoerceUnsized<<T as Smartass>::Data>
{}

pub fn conv(s: SmartassPtr<()>) -> SmartassPtr<MaybeObjectSafe> {
    s
}

fn main() {
}
```

## ICE:
```
error: internal compiler error: /checkout/src/librustc_trans/collector.rs:820: find_vtable_types_for_unsizing: invalid coercion <() as Smartass>::Data -> <MaybeObjectSafe as Smartass>::Data

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.22.0-nightly (6c476ce46 2017-09-25) running on x86_64-unknown-linux-gnu

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:492:8
note: Run with `RUST_BACKTRACE=1` for a backtrace
```

**Comment by Seeker14491** [comment]
The given code builds fine on current nightly.

**Comment by JohnTitor** [comment]
This is still an ICE on current nightly when not `cargo run`. [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=bdd59503a0dc2d33c60a949fc7c57633)

**Comment by Seeker14491** [comment]
This code compiles without a problem whether I do `cargo build` or `cargo run` using current nightly: `rustc 1.40.0-nightly (1721c9685 2019-10-12)`. Tested on Windows 10 x64 and Ubuntu x64.

**Comment by JohnTitor** [comment]
@Seeker14491 Really? But on the playground, the ICE still appears. Can you check the above link?

**Comment by Seeker14491** [comment]
Yes, I get an ICE in the playground when I just build.

**Comment by mati865** [comment]
It doesn't ICE on the [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=bdd59503a0dc2d33c60a949fc7c57633) any more.

**Comment by JohnTitor** [comment]
@mati865 You need `cargo build` or `cargo test`, not `cargo run`. It seems like a still ICE to me.

**Comment by JohnTitor** [comment]
Triage: the latest nightly rejects the code without an ICE. Marking as E-needs-test.
