### ISSUE TITLE
Application fails to run on Windows XP

### ISSUE THREAD

**Issue by gstar4** [rust-lang/rust#44873]
I am trying to create a simple HTTP client that runs on all versions of Windows XP and newer.

Windows XP is currently officially [supported as a tier 3 platform in Rust](https://forge.rust-lang.org/platform-support.html).

Support for XP was added to `std` in #24776

The sample code I am trying to compile is:

```rust
extern crate reqwest; // version 0.7.3 specified in Cargo.toml

fn main() {
    reqwest::get("https://www.rust-lang.org")
}
```

I am following the following steps to build a portable Windows XP and newer compatible Rust binary. I am building from a Windows 10 x64 host.

Set `RUSTFLAGS` environment variable to 

```
-C target-feature=+crt-static -C link-arg=/SUBSYSTEM:CONSOLE,5.01
```

Build with 32-bit toolchain

```bash
$ rustup toolchain install stable-i686-pc-windows-msvc

$ cargo +stable-i686-pc-windows-msvc build --release
```

The resulting binary is linked to

```
secur32.dll
crypt32.dll
advapi32.dll
ws2_32.dll
kernel32.dll
```

and is properly listed with NT 5.1 as the operating system in the PE header.

When run on Windows XP SP3 32-bit an error is shown:

```
The procedure entry point SetFileCompletionNotificationModes could not be located in the dynamic link 
library KERNEL32.dll.
```

Following these same steps, a "Hello, World!" executable does execute properly on Windows XP SP3.

Is this a problem with `std`? One of the dependancies? Is there a way to instruct Cargo/rustc/MSVC linker to avoid this call to KERNEL32.dll?

cc Windows Bunny Master @retep998

**Comment by sfackler** [comment]
That function is being called by the mio library - I would file this against that project: https://github.com/carllerche/mio/blob/8078b9034dfbe4e93277877a34ea803b55c7e3a9/src/sys/windows/mod.rs#L181

**Comment by gstar4** [comment]
Thank you @sfackler, cross posted to: https://github.com/carllerche/mio/issues/735
