### ISSUE TITLE
[NLL] store a value for each region

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#44870]
The [NLL code](https://github.com/SimonSapin/rust/blob/20d4c0fab418edf036b7e0f1910053d3437da269/src/librustc_mir/transform/nll/mod.rs) currently contains code to renumber all regions into fresh region variables, but it contains no map storing the **value** of those region variables.

We should define a struct `Region` that will store the value of a non-lexical region. This struct would resemble `Region` from the NLL prototype and basically play the same role. I think it can initially look something like this:

```rust
#[derive(Clone, Debug, Default, Hash, PartialEq, Eq)]
struct Region {
    points: FxHashSet<Location>,
}
```

The `Location` struct is [defined in `librustc/mir`](https://github.com/SimonSapin/rust/blob/20d4c0fab418edf036b7e0f1910053d3437da269/src/librustc/mir/mod.rs#L1627-L1635) and it is basically a "point" -- basic block + statement index.

Then we should add to [the `NLLVisitor` struct](https://github.com/SimonSapin/rust/blob/20d4c0fab418edf036b7e0f1910053d3437da269/src/librustc_mir/transform/nll/mod.rs#L23) a field like `region_values: Vec<Region>`. Each time that [we create a new region variable](https://github.com/SimonSapin/rust/blob/20d4c0fab418edf036b7e0f1910053d3437da269/src/librustc_mir/transform/nll/mod.rs#L41), we will also push a `Region::default()` onto the vector to serve as its (initially empty) value.

Eventually, this struct will also want to contain free regions. but I figure we can start without them, while we debate how best to represent free regions here. (Probably `ty::Region<'tcx>` for now, but I think we can ignore it for now and just target "intra-function" cases.)

**Comment by chrisvittal** [comment]
I am interested in working on this! It looks like that for now, all the work will be done in `librustc_mir/transform/nll/mod.rs`?

**Comment by nikomatsakis** [comment]
This is long since done.
