### ISSUE TITLE
 Improve lifetime error with return value

### ISSUE THREAD

**Issue by cengizIO** [rust-lang/rust#44875]
Hello!

(this shall be considered an item under https://github.com/rust-lang/rust/issues/42516)

While me and @nikomatsakis were working on #42701 we've discovered that this case is not handled properly. (properly: didn't use new lifetime error messages)

```rust
struct Foo {
    field: i32,
}
fn foo2<'a, 'b>(a: &'a Foo, x: &'b i32) -> &'a i32 {
    if true {
        let p: &i32 = &a.field;
        &*p
    } else {
        &*x
    }
}
fn main() {}
```

This currently shows a `error[E0495]: cannot infer an appropriate lifetime for borrow expression due to conflicting requirements`. It should show one of the `E06XX` errors instead. 

@nikomatsakis said that fix might be dependent on this: https://github.com/rust-lang/rust/issues/44124

So, this issue is a reminder for us to fix that case. Any help is more than welcome!

🍻

**Comment by estebank** [comment]
[Current output](https://play.rust-lang.org/?gist=b6eadcd35aaa7a7299b6ace73da4fd98&version=nightly):

```
error[E0623]: lifetime mismatch
 --> src/main.rs:9:9
  |
4 | fn foo2<'a, 'b>(a: &'a Foo, x: &'b i32) -> &'a i32 {
  |                                -------     -------
  |                                |
  |                                this parameter and the return type are declared with different lifetimes...
...
9 |         &*x
  |         ^^^ ...but data from `x` is returned here
```
