### ISSUE TITLE
char::FromStr cannot parse hexadecimal / unicode notations

### ISSUE THREAD

**Issue by jice-nospam** [rust-lang/rust#44883]
Both of these fail with a `ParseCharError { kind: TooManyChars }`
```
    assert_eq!(r"\u{2764}".parse::<char>().unwrap(), '\u{2764}');
    assert_eq!(r"\x40".parse::<char>().unwrap(), '\x40');
```
Is this a missing feature or impossible to implement ?

**Comment by stephaneyfx** [comment]
This works correctly if the input strings are not raw [playground](https://play.rust-lang.org/?gist=6f21c8b4db9ca49f047b15b6cab2c4dc&version=stable):

```rust
assert_eq!("\u{2764}".parse::<char>().unwrap(), '\u{2764}');
assert_eq!("\x40".parse::<char>().unwrap(), '\x40');
```

These escape sequences are specific to rust source code and I don't think the implementation of `FromStr` should consider/favor these escape sequences as it may be used to parse strings containing something else than rust code.

**Comment by jice-nospam** [comment]
Since the implementation is already somewhere in the compiler, I was hoping it was available in the language, but indeed, it does not make sense as there are lots of other ways to encode chars. I'm closing the issue.

**Comment by stephaneyfx** [comment]
Unfortunately this functionality of parsing rust escape sequences does not seem to be offered as part of the standard library or a crate ([related stackoverflow entry](https://stackoverflow.com/questions/40055279/parse-a-string-containing-a-unicode-number-into-the-corresponding-unicode-charac)).
