### ISSUE TITLE
prototype NLL inference infrastructure

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#44904]
Building on https://github.com/rust-lang/rust/pull/44878, 

In the nascent NLL code, we need to define the inference infrastructure. This is basically the code embodied by [`infer.rs` in the prototype](https://github.com/nikomatsakis/nll/blob/master/nll/src/infer.rs). In particular, this inference context ought to take ownership of the region values that were added in #44878. It would then also collect a series of **constraints**. In the prototype, those constraints take two forms:

- **Liveness** constraints, which basically just insert a single point into a region. [In the prototype](https://github.com/nikomatsakis/nll/blob/master/nll/src/infer.rs#L82-L90), these are inserted directly into the value for the region as soon as the constraint is added. In the RFC, these are expressed in terms of outlives constraints that relate a region variable R to a singleton region (e.g., `R: {P} @ P`).
- **Outlives** constraints, which relate two region variables at a particular point. [In the prototype](https://github.com/nikomatsakis/nll/blob/master/nll/src/infer.rs#L95), these are accumulated into a vector. The [solve routine](https://github.com/nikomatsakis/nll/blob/master/nll/src/infer.rs#L102-L141) then propagates values between variables according to these constraints.

In the **prototype**, everything is a region variable, but some variables can [**capped**](https://github.com/nikomatsakis/nll/blob/master/nll/src/infer.rs#L77), which means that it is an error if they grow. Effectively those variables then become constants. We might want to code things up a bit differently, so that outlives constraints can encode constants as well. In particular, this is needed to report hard errors relating to free regions.

**Comment by spastorino** [comment]
Cool, I will start working on this one.

**Comment by nikomatsakis** [comment]
In progress PR: https://github.com/rust-lang/rust/pull/45155

**Comment by nikomatsakis** [comment]
Long since done.
