### ISSUE TITLE
Publish Cargo Manual on the bookshelf

### ISSUE THREAD

**Issue by behnam** [rust-lang/rust#44910]
# Background
In <https://github.com/rust-lang/cargo/issues/4040>, we re-organized Cargo documentations into one single in-repo mdBook, called "Cargo Manual". The preview is available on <http://doc.crates.io/book/>

# Now
The last step is to publish the book on <https://doc.rust-lang.org/cargo/>, which requires work in this repo (`rust`).

# Follow-up
After this, we should create a new tracker issue in Cargo to deprecate `doc.crates.io` and redirect them to `doc.rust-lang.org`. [<https://github.com/rust-lang/cargo/issues/4694>]

Part of <https://github.com/rust-lang/rust/issues/39588>

**Comment by steveklabnik** [comment]
I took a stab at this today, but didn't get it working; our book build system generally expects for the book to be in the `src\doc` directory, trying to build from a different one seems to confuse it. More investigation tomorrow!

**Comment by behnam** [comment]
Yeah, I ended up in a similar situation and started touching many functions to make them flexible enough to handle this case.

If you think it's better to make changes on the `cargo` repo side to make it easier to adapt here, I can help with it. One solution would be to move the old docs into `cargo/src/doc-old/` and move `cargo/src/doc/book/` into `cargo/src/doc/`.

**Comment by steveklabnik** [comment]
Let me give it another go before we try that; I'm not totally sure that helps a ton.

**Comment by steveklabnik** [comment]
I did it! PR incoming.

**Comment by behnam** [comment]
Awesome, @steveklabnik!

I created a follow up task on Cargo to finish the migration: https://github.com/rust-lang/cargo/issues/4694
