### ISSUE TITLE
Confusing docs: Command::output claims to "capture" stdin

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust#44929]
> [By default, **stdin**, stdout and stderr are captured (and used to provide the resulting output).](https://doc.rust-lang.org/nightly/std/process/struct.Command.html#method.output)

"capture" makes it sound like the data is stored somewhere for later inspection.  There is no `stdin` field in [process::Output](https://doc.rust-lang.org/nightly/std/process/struct.Output.html).

I did some looking into the implementation, and to me it seems that the child's stdin is simply closed before waiting. @talchas on IRC told me that it's made to be [`Stdio::null()`](https://doc.rust-lang.org/nightly/std/process/struct.Stdio.html#method.null).

In any case, this should be clarified.

cc @steveklabnik

**Comment by frewsxcv** [comment]
Opened a pull request for this: https://github.com/rust-lang/rust/pull/46220
