### ISSUE TITLE
Tracking issue for RFC #2094: non-lexical lifetimes 

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#44928]
This is a tracking issue for the RFC "non-lexical lifetimes" (rust-lang/rfcs#2094).

**Comment by aturon** [comment]
Work is already underway as part of the impl period; I will let @nikomatsakis adjust the issue description with whatever checklist makes the most sense.

**Comment by Manishearth** [comment]
Initial infrastructure: https://github.com/rust-lang/rust/pull/45538

**Comment by mark-i-m** [comment]
Prototype: #43234

**Comment by nikomatsakis** [comment]
closing in favor of #43234
