### ISSUE TITLE
File Not Found : Meaningful error messages to identify exact issue

### ISSUE THREAD

**Issue by dumindu** [rust-lang/rust#44938]
# Folder structure

```
├── Cargo.toml
└── src
   ├── hello.txt
   └── main.rs
```

# main.rs

```
use std::fs::File;

fn main() {
    let _file = File::open("hello.txt").expect("file not found");
    println!("{}", "Hello World!");
}
```

# Error

```
Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
Running `target/debug/read_file`

thread 'main' panicked at 'file not found: Error { repr: Os { code: 2, message: "No such file or directory" } }', src/libcore/result.rs:906:4
stack backtrace:
   0:        0x10c4135f3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h3160619f5df0b429
   1:        0x10c40fe30 - std::sys_common::backtrace::_print::h1120036038320f80
   2:        0x10c4149e3 - std::panicking::default_hook::{{closure}}::hb299632e05329bb5
   3:        0x10c4146e2 - std::panicking::default_hook::h00107bf0a85963b4
   4:        0x10c414e32 - std::panicking::rust_panic_with_hook::hd9c6ad24a775c34c
   5:        0x10c414d14 - std::panicking::begin_panic::h49e0d0a8e06c5478
   6:        0x10c414be2 - std::panicking::begin_panic_fmt::h1694ee0907f92803
   7:        0x10c414b4a - rust_begin_unwind
   8:        0x10c4462c3 - core::panicking::panic_fmt::h2d82c8387bfa11ba
   9:        0x10c407c4c - core::result::unwrap_failed::he129861d908021e0
  10:        0x10c407f28 - <core::result::Result<T, E>>::expect::h1db24ec21ca210c8
  11:        0x10c40841e - read_file::main::hfb1b70fb4d7706fb
  12:        0x10c444edc - __rust_maybe_catch_panic
  13:        0x10c415128 - std::rt::lang_start::h3fa27024f6a74294
  14:        0x10c408509 - main

Process finished with exit code 101

```

# Expected error message

No such file in `<absolute path>`

**Comment by abonander** [comment]
This could be expanded to other error messages as well. This will probably need to be done separately for each platform.

**Comment by dumindu** [comment]
```
fn main() {
    let content = include_str!("not_existing_file.txt");
    println!("{}", content);
}
```
gives 
error: couldn't read src/not_existing_file.txt: No such file or directory (os error 2). 
At least it gives the root directory

**Comment by KasMA1990** [comment]
[Here](https://internals.rust-lang.org/t/add-filename-information-to-io-error/5120/12) is some prior discussion of the same issue :)

**Comment by ssokolow** [comment]
I'd prefer if, rather than "No such file on `<absolute path>`", it left the message unaltered and appended something like "(With working directory `<absolute path`)" to the end.

That way, it doesn't disadvantage situations where the greppability of the error string or the requested path are significant to how easy it is to debug.

**Comment by dtolnay** [comment]
There are a lot of good points for either side in [Add filename information to io::Error](https://internals.rust-lang.org/t/add-filename-information-to-io-error/5120). I am not confident that we will be able to reach a consensus here, so I would prefer to follow up in an [RFC](https://github.com/rust-lang/rfcs/blob/master/libs_changes.md). I think the most likely way to make progress on this would be to do a thorough and balanced writeup of the tradeoffs, survey how libraries are using io::Error in practice, develop a prototype implementation, provide benchmarks and an assessment of how those impact various use cases, and make a concrete recommendation for what approach to pursue in the standard library that balances everybody's needs.
