### ISSUE TITLE
ICE: After undeclared module error

### ISSUE THREAD

**Issue by jgouly** [rust-lang/rust#44946]
This short code produces an ICE after correctly reporting an error:
    
    const A: usize = C::D::<u32>();

No special options needed:
    
    $ rustc 44946.rs

Rust version:

    $ rustc --version --verbose
    rustc 1.22.0-nightly (1ed7d41d8 2017-09-24)  
    binary: rustc 
    commit-hash: 1ed7d41d8849d930f0622eaf54049f66fff0ca2a
    commit-date: 2017-09-24  
    host: x86_64-unknown-linux-gnu
    release: 1.22.0-nightly
    LLVM version: 4.0

**Comment by petrochenkov** [comment]
Very similar to https://github.com/rust-lang/rust/issues/44858, fixed in https://github.com/rust-lang/rust/pull/44945

**Comment by jgouly** [comment]
Thanks @petrochenkov!
