### ISSUE TITLE
Migrate liblibc from submodule to crates.io

### ISSUE THREAD

**Issue by dns2utf8** [rust-lang/rust#44986]
Pro: use local cargo cache and one single location for the source
Con: maybe the build process?

What do you think?

**Comment by sfackler** [comment]
We've already migrated most other dependencies out to the normal crates.io versions (e.g. log). Not sure why liblibc is still a submodule, bit it seems like it can probably move as well.

**Comment by Mark-Simulacrum** [comment]
This has since been done AFAICT.
