### ISSUE TITLE
Suggest `if let` when a failed `if` block could be parsed as one

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#44990]
When writing `if Some(x) = foo {}`, attempt to parse as `if let Some(x) = foo {}` for better diagnostic output and if successful provide a suggestion to add the `let`.

**Comment by cramertj** [comment]
Is this possible to accomplish within the parser? I'd think you'd need some amount of name resolution information, since this code is perfectly valid:

```rust
fn main() {
    let x = 0;
    let foo = Some(0);
    if Some(x) == foo {}
}
```

**Comment by estebank** [comment]
I think it would if `x` wasn't in the scope. We can't know that during parsing, but the errors for

```rust
fn main() {
    let foo = Some(0);
    if Some(x) = foo {}
}
```

are

```
error[E0425]: cannot find value `x` in this scope
 --> src/main.rs:3:13
  |
3 |     if Some(x) = foo {}
  |             ^ not found in this scope

error[E0308]: mismatched types
 --> src/main.rs:3:8
  |
3 |     if Some(x) = foo {}
  |        ^^^^^^^^^^^^^
  |        |
  |        help: did you mean to compare equality?: `Some(x) == foo`
  |        expected bool, found ()
  |
  = note: expected type `bool`
             found type `()`
```

Which tells me we could catch `not found in this scope` errors that occur on if conditions and try them as `if let`. If it succeeds to parse the rest of the block, then emit the original error with an extra suggestion.

For the case where `let x = 0` is in the code, the output is only the mismatched types error.

**Comment by estebank** [comment]
cc @Centril, given the recent `it let` desugaring work.

**Comment by Centril** [comment]
@estebank Added to the tracking issue for list of potential issues to work on; tho since it is preexisting, not as a blocker but a nice-to-have.
