### ISSUE TITLE
No shared conversions for other string-like types (Path, OsStr, CStr)

### ISSUE THREAD

**Issue by parkovski** [rust-lang/rust#45008]
Conversions for `Rc<str>`, `Arc<str>`, `Rc<[T]>`, and `Arc<[T]>` were added in #42565, but it is still not possible to make a shared container for other string-like types - you still need to use double allocated containers like `Rc<PathBuf>`. It looks like the only types this is missing for are `Path`, `OsStr`, and `CStr`.

**Comment by dtolnay** [comment]
Seems reasonable. @murarth or @clarcharr would you be interested in figuring out an API for this?

**Comment by murarth** [comment]
I believe impls of `From<CStr> for Rc<CStr>`, etc. should work just fine. I'll have a PR ready shortly.
