### ISSUE TITLE
incr.comp.: Implement force_from_dep_node() in a macro.

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#45015]
The `ty::maps::plumbing::force_from_dep_node()` procedure (introduced in https://github.com/rust-lang/rust/pull/44901) is manually implemented right now. This is unfortunate, since it contains an exhaustive match over all `DepKinds` and the implementation could be done almost mechanically. We should try to move the implementation into `define_maps!` or `define_dep_nodes!`.

**Comment by cjgillot** [comment]
This can be closed now.
