### ISSUE TITLE
FAQ describes something from 1½ years ago as “recent”

### ISSUE THREAD

**Issue by chris-morgan** [rust-lang/rust#45061]
https://www.rust-lang.org/en-US/faq.html#why-do-rust-programs-have-larger-binary-sizes-than-C-programs:

> An alternative optimization level (called `s` or `z`) [has recently landed](https://github.com/rust-lang/rust/pull/32386) and tells the compiler to optimize for size rather than performance.

That “recent” was almost a year and a half ago. Presuming it’s been stable since then (I haven’t investigated deeply and am going to bed right now), I think it’s time to reword it.

**Comment by kennytm** [comment]
It is not yet stable, see #35784.

**Comment by euclio** [comment]
This FAQ doesn't seem to exist on the new website. I'm guessing this can be closed?

**Comment by steveklabnik** [comment]
Even if it were, it would be on the website repo, not this repo.
