### ISSUE TITLE
Functions are mangled even if the link_name attribute is specified

### ISSUE THREAD

**Issue by liranringel** [rust-lang/rust#45073]
I'm trying to use bindgen.
When targeting `i686-pc-windows-msvc` on 64-bit windows host, I noticed that the generated function symbol is mangled even if the `link_name` attribute is specified. Bindgen already mangles the function and passes it as a value to the `link_name` attribute, so the function is mangled twice (which is wrong and produce a link error).

For example, with the following header:
```
int _stdcall foo();
```

Bindgen will produce:

```
extern "stdcall" {
    #[link_name = "_foo@0"]
    pub fn foo() -> ::std::os::raw::c_int;
}
```

But when I use it, I get the following linker error:
`error LNK2019: unresolved external symbol __foo@0@0 referenced in function`...
As you can see, the function is mangled twice. If I remove the `link_name` attribute, it works.

**Comment by jjpe** [comment]
Could you give the `#[no_mangle]` attribute a try instead of `#[link_name  = "..."]`, see if that works?

**Comment by retep998** [comment]
LLVM automatically performs calling convention decoration on symbols. This sounds like a simple case where `bindgen` should just not emit `link_name`, but if you *really* want to explicitly specify the calling convention decoration yourself then I believe prefixing the name with `\x01` should tell LLVM to not automatically decorate symbols.

**Comment by liranringel** [comment]
@retep998 thanks
