### ISSUE TITLE
Adding more favicons to support more platforms including Firefox new tab page

### ISSUE THREAD

**Issue by dumindu** [rust-lang/rust#45078]
This is top sites thumbnail previews of Firefox new tab page. Most of official Rust websites are missing bigger favicons. 
<img width="519" alt="screen shot 2017-10-07 at 10 46 09 am" src="https://user-images.githubusercontent.com/1280428/31304522-fb8c5e56-ab4c-11e7-97a9-18f86c836968.png">

**Comment by steveklabnik** [comment]
Sorry, I'm a bit confused about this. They should all look like doc.rust-lang.org, that is, only a favicon? It seems like the other three have them. (also docs.rs is not part of the project so you'll have to talk to them individually.)

Do you have any link explaining this stuff and what we need to do?

**Comment by dumindu** [comment]
Hi @steveklabnik,
Sorry for the confusion, my mistake. This is for [Firefox Quantum](https://www.mozilla.org/en-US/firefox/quantum/) which is going to release on November 14 2017 to main stream. 

This can be tested on Firefox 57+(beta-nightly), on new tab page under top sites. The image is captured from bigger favicons but don't know what is the minimum accepted size.

And also many other platforms uses large favicons on new tab pages and on Home screens. So it's better we can add more favicons.

**Comment by estebank** [comment]
Triage:

<img width="508" alt="" src="https://user-images.githubusercontent.com/1606434/57662429-5acd4880-75a4-11e9-85a2-8536f1940e1f.png">
