### ISSUE TITLE
rustc recommends specialization for type parameters inside an extern block

### ISSUE THREAD

**Issue by MaikKlein** [rust-lang/rust#45092]
```
extern {
    fn sqrt<T>(f: T) -> T;
}

fn main(){}

```
[playground](https://play.rust-lang.org/?gist=ee8dd6782e34cc6929014c4a7323afa4&version=stable)
> help: consider using specialization instead of type parameters

**Comment by MaikKlein** [comment]
I just realized that rustc doesn't refer to the feature specialization but 'manual' specialization.

rustc --explain E0044

---

You can't use type parameters on foreign items. Example of erroneous code:
```
extern { fn some_func<T>(x: T); }
```
To fix this, replace the type parameter with the specializations that you
need:
```
extern { fn some_func_i32(x: i32); }
extern { fn some_func_i64(x: i64); }

**Comment by oli-obk** [comment]
Diagnostics triage: just needs changing the wording to something that gives a clearer message.

**Comment by iluuu1994** [comment]
E0044 has been reworded in https://github.com/rust-lang/rust/pull/48138.

```
error[E0044]: foreign items may not have type parameters
 --> src/main.rs:2:5
  |
2 |     fn sqrt<T>(f: T) -> T;
  |     ^^^^^^^^^^^^^^^^^^^^^^ can't have type parameters
  |
  = help: use specialization instead of type parameters by replacing them with concrete types like `u32`
```

This can be closed.
