### ISSUE TITLE
Support running bootstrap.py with Python 3

### ISSUE THREAD

**Issue by johnthagen** [rust-lang/rust#45114]
From the [README](https://github.com/johnthagen/rust#building-from-source):

> 1. Make sure you have installed the dependencies:
> `python` 2.7 (but not 3.x)

I suggest that the Python portions of building rustc be made compatible with Python 2.7 and 3.4+.

- Python 2.7 [will not be maintained upstream after 2020](https://www.python.org/dev/peps/pep-0373/#update) (less than three years away)
- On Ubuntu [the plan is to only have Python 3 installed by default](https://wiki.ubuntu.com/Python/3)
- [Python 3 became default stack in Fedora starting in Fedora 23](https://fedoraproject.org/wiki/Changes/Python_3_as_Default)

While Python 2 still has a large user base, the trend is moving towards Python 3 becoming the default version, and the only one preinstalled on certain popular Linux distros.

Doing a cursory look at the code, I don't see any glaring Python 2-only-isms, so it may just work or only require a relatively small amount of effort.

Would PRs for Python 3 compatibility (which retain compatibility with Python 2) be accepted?

**Comment by sfackler** [comment]
I believe bootstrap supports Python 3 but LLVM's build infrastructure doesn't.

**Comment by Mark-Simulacrum** [comment]
We gladly take patches for Python 3 compatibility for rustc's infrastructure; LLVM patches would have to be taken up with them. Python 2.7 is "guaranteed" to work (what the build infrastructure uses) whereas python 3 isn't, which is why the documentation suggests using 2.7.
