### ISSUE TITLE
MIR-borrowck: paths off of statics should not be borrow-checked

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#45129]
Paths off of statics should not be borrow-checked, as they already require `unsafe`. But currently MIR-borrowck is flagging errors for them, while AST-borrowck lets them through without complaint.

(Spawned off of https://github.com/rust-lang/rust/pull/44985#pullrequestreview-67919938)

**Comment by KiChjang** [comment]
I'm taking a look at this.

**Comment by nikomatsakis** [comment]
struct Foo { x: usize }

static mut SFOO : Foo = Foo{x: 23 }; 

impl Foo {
    fn x(&mut self) -> &mut usize { &mut self.x }
}

fn main() {
    unsafe {
        let x = SFOO.x();
        SFOO.x += 1; // ?
        *x += 1; 
    }
}

**Comment by nikomatsakis** [comment]
I think we should at least warn about this scenario. We could do this by looking at the borrow path during the access checks to see if it was a borrow of a static.

**Comment by nikomatsakis** [comment]
After some discussion on gitter, decided that we should leave warning for later consideration, and just match AST borrowck in this case for now. This is not a **bug fix**, no need to deviate right now.

**Comment by pnkfelix** [comment]
Note for those reading this bug in future: the example test written in [above comment](https://github.com/rust-lang/rust/issues/45129#issuecomment-344867514) is actually [UB](https://github.com/rust-lang/rust/pull/46032#discussion_r151397245), because it is creating two simultaneous `&mut` references that point to the same location.
