### ISSUE TITLE
rustdoc: add [src] links to provided methods on a trait's page

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/rust#45150]
For example, here's a method on Iterator right now:

![image](https://user-images.githubusercontent.com/5217170/31353027-8f3cbd80-acf6-11e7-9775-7b6cd6766220.png)

Since this is a provided method, there's a worthwhile implementation to link to, so it would be nice to be able to link to it's implementation, by adding a `[src]` link to the method header here.

**Comment by QuietMisdreavus** [comment]
(Note: I created this issue just so i could mentor someone on it, so consider it claimed!)

**Comment by timotree3** [comment]
@QuietMisdreavus I want to take this on. I'm gonna start looking for the relevant parts of the code.

**Comment by timotree3** [comment]
I think the fix belongs somewhere in `fn doc_impl_item`, but I don't fully understand the function yet.

**Comment by timotree3** [comment]
My bad, I guess you mean that there is a specific person you're mentoring on it. Not that you want to mentor whoever takes it on.

**Comment by jyn514** [comment]
Since it's been a few years, I think we can safely assume this issue is unclaimed.
