### ISSUE TITLE
Borrow checker unsoundness with unions

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#45157]
```rust
#![allow(unused)]

#[derive(Clone, Copy, Default)]
struct S {
    a: u8,
    b: u8,
}
#[derive(Clone, Copy, Default)]
struct Z {
    c: u8,
    d: u8,
}

union U {
    s: S,
    z: Z,
}

fn main() { unsafe {
    let mut u = U { s: Default::default() };
    
    let mref = &mut u.s.a;
    let err = &u.z.c; // This line compiles, but it certainly shouldn't ...
    drop(mref); // ... (at least if `mref` is used after `err`)
}}
```

"Cousins" of borrowed union sub-fields (and their further children) are not marked as borrowed.
~~The same bug should happen with move checking as well, but I haven't made an example yet.~~

**Comment by nikomatsakis** [comment]
This is [still true in NLL](https://play.rust-lang.org/?gist=473568c2cb2fe3efcbe032b331fb46ba&version=nightly), though I sort of thought we had tried to fix this.

**Comment by nikomatsakis** [comment]
I'm tagging this as WG-compiler-nll; I think it's something we should fix there.

**Comment by joshtriplett** [comment]
For the sake of potential testsuite additions: this also should not compile with a simultaneous borrow of `u.s.a` and `u.z.d`.

**Comment by davidtwco** [comment]
I'll take a look at this one.

**Comment by nikomatsakis** [comment]
So it seems like I forgot about how smart the compiler is now. This version of the test *does* error, as expected:

https://play.rust-lang.org/?gist=86c25066ab9197ebfd7a91b573f97595&version=nightly

**Comment by nikomatsakis** [comment]
I think the policy is that we will keep this bug open, but file it under https://github.com/rust-lang/rust/issues/47366

**Comment by nikomatsakis** [comment]
(Since it is only fixed when NLL is enabled)

**Comment by Centril** [comment]
@nikomatsakis should this be `NLL-fixed-by-NLL`?

**Comment by arielb1** [comment]
Note that to get an NLL test failure, you have to *use* `mref` after declaring `err`:

```Rust
#![allow(unused)]

#[derive(Clone, Copy, Default)]
struct S {
    a: u8,
    b: u8,
}
#[derive(Clone, Copy, Default)]
struct Z {
    c: u8,
    d: u8,
}

union U {
    s: S,
    z: Z,
}



fn main() { unsafe {
    let mut u = U { s: Default::default() };
    
    let mref = &mut u.s.a;
    let err = &u.z.c; // This line compiles, but it certainly shouldn't 
    drop(mref);
}}
```

**Comment by pnkfelix** [comment]
NLL (migrate mode) is enabled in all editions as of PR #59114.

The only policy question is that, under migrate mode, we only emit a warning on this (unsound) test case. Therefore, I am not 100% sure whether we should close this until that warning has been turned into a hard-error under our (still in development) future-compatibility lint policy.
