### ISSUE TITLE
Add cfg for crate_type?

### ISSUE THREAD

**Issue by joshlf** [rust-lang/rust#45182]
I have some code that needs to be conditionally compiled only when the artifact that's being produced is a dynamic library, and the target platform is Mac ([here's the code](https://github.com/ezrosent/allocators-rs/blob/8e835ee953f1e59755f96400c980c67fb849283e/alloc-tls/src/lib.rs#L222)). Right now, I'm accomplishing that by providing a `dylib` feature that the crate's user is responsible for enabling if they're compiling a dynamic library.

This is ugly from a UX perspective, and introduces the possibility of bugs if the user fails to enable the feature when they should. It'd be better if there were a `cfg` setting that indicated the value of the `crate_type` so I could do this automatically without user help.

**Comment by rkruppe** [comment]
It is possible to set multiple crate types at once and get artifacts for all of them in one compilation session. That makes it kind of difficult to provide a single `crate_type="foo"` cfg, though perhaps there could still be a set of flags like `cfg_crate_type_cdylib`, `cfg_crate_staticlib`, etc.?

**Comment by joshlf** [comment]
Yeah, I think that'd work. Something like `#[cfg(crate_type = "cdylib")]`, `#[cfg(crate_type = "staticlib")]`, etc (where multiple could be true at once similar to `#[cfg(feature = "...")]`).

In my particular use case, I'd probably need to ensure that only a single artifact was generated at a time by doing something like:

```rust
#[cfg(all(crate_type = "cdylib", any(crate_type = "staticlib", ...)))]
compile_fail!(...);
```

But yeah that'd work for me.

**Comment by glandium** [comment]
> where multiple could be true at once

Interestingly, that would not be useful in some use cases. Specifically, I was looking at building a crate as both a cdylib and staticlib today, and needed both to export a function under a different name... I tried `#[cfg(crate_type = "cdylib")]` on function with one name and `#[cfg(crate_type = "staticlib")]` on another, but that (annoyingly, I must say) silently exposed none of them. This use case would not be fulfillable if multiple could be true at once.

**Comment by retep998** [comment]
Why don't we just allow a cargo package to have multiple `cdylib` and `staticlib` crates distinct from the primary library crate? Then you could just put all the common stuff in the library crate and the `cdylib`/`staticlib` crates would have the stuff specific to them, so you wouldn't have to cfg based on how the crate is being built.

**Comment by joshlf** [comment]
My concern would be that it'd require publishing the common crate which
would need to expose internal functionality in order to be used by the
cdylib and staticlib crates. You might not want to actually publish that
stuff.

**Comment by retep998** [comment]
Ah, but you could have a shared *module*. Two separate crates can both include the same module, and that could define the common *private* functionality.

**Comment by glandium** [comment]
How can two separate crates share a module?

**Comment by glandium** [comment]
Ah! `#[path]`.

**Comment by Mark-Simulacrum** [comment]
I'm going to loosely say this is probably RFC-worthy territory and close this issue (it's definitely not a rustbuild bug).
