### ISSUE TITLE
MIR-borrowck: dereferences are printed wrapped in parens 

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#45185]
MIR-borrowck: In error diagnostics, derefencing expressions are printed with parentheses around them.

 For example, for `borrowck-borrow-mut-object-twice.rs`, AST-borrowck reports:
```
cannot borrow `*x` as mutable more than once at a time (Ast)
```
while MIR-borrowck reports:
```
cannot borrow `(*x)` as mutable more than once at a time (Mir)
```

(This is hopefully relatively simple to resolve; is there any case where we *need* the parentheses, given that we already elide dereferences when printing field accessor expressions?)

**Comment by nikomatsakis** [comment]
@zilbuz are you looking at this?

**Comment by zilbuz** [comment]
@nikomatsakis Yes I am :)
