### ISSUE TITLE
pretty print during tracing macros

### ISSUE THREAD

**Issue by uzytkownik** [rust-lang/rust#45196]
It would be nice if rust considered syntax structure while printing macros during logging and tracing.

```
# Current output of log_syntax!:
struct => PRIV struct Params [ @ app test ::std::string::ParseError ] [
subcommands => {  } params => {
( PRIV quiet QUIET bool { q } {  } { flag } ) (
PRIV verbose VERBOSE bool { v } {  } { flag } ) (
PRIV cfg CFG String { c } {  } { default String::from("") } ) (
PRIV path PATH String { p } {  } { required } ) (
PRIV foo FOO Option<String> {  } { foo } { optional } ) (
PRIV n N Option<u32> { n } {  } { option map (|v: Option<&str>| v.map(|_| 3))
} ) ( PRIV x X u32 { x } {  } { map (|v| 4) } ) } ]
```
```
# Pretty output
struct => PRIV struct Params [ @ app test ::std::string::ParseError ]
[
    subcommands => {  }
    params => {
        ( PRIV quiet QUIET bool { q } {  } { flag } )
        ( PRIV verbose VERBOSE bool { v } {  } { flag } )
        ( PRIV cfg CFG String { c } {  } { default String::from("") } )
        ( PRIV path PATH String { p } {  } { required } )
        ( PRIV foo FOO Option<String> {  } { foo } { optional } )
        ( PRIV n N Option<u32> { n } {  } {
            option map (|v: Option<&str>| v.map(|_| 3))
        } )
        ( PRIV x X u32 { x } {  } { map (|v| 4) } )
    }
]
```

**Comment by durka** [comment]
I'll give this a shot. Not sure if it should be a separate flag since it will bloat the output.

**Comment by uzytkownik** [comment]
> I'll give this a shot. Not sure if it should be a separate flag since it will bloat the output.

TBH I'm not sure if that is a problem. It's already behind a flag and after reading few hundreds (700-800) lines of output for my toy examples each time I issue rustc the size is not a problem - readability is (and currently this is the only way I think to debug macros - ok my problem might be more suitable for procedural ones but so far they don't seem to be included in stable anytime soon).

**Comment by durka** [comment]
Any ideas on what heuristics should be used for pretty-printing? I'm thinking along these lines:

- if there's a pair of a brackets containing more than N tts
  - split each tt on its own line
    - except commas (if present) go at the end of the line

What else? I don't know if there's a good way to turn `String :: from ( "" )` back into `String::from("")` because we don't know what parts of the token stream might be parseable.

**Comment by uzytkownik** [comment]
I don't mind having spaces in `String :: from ( "" )`.

I think it's better to count per character then token trees. Maybe something like that:

 - Recursively from bottom up (aka postorder)
 - If any child node is split so is parent
 - Otherwise if output would be wider then terminal/72/80 characters/some magic number taken from somewhere split the parent

Split printing is done as:
 - Put all children which are proper trees themselves in new, intended, line. Proper tree is one which has more than one node.
    - If children is longer than one line make it pretty print according to some rule: make start and last token a separate lines, or append/prepend to previous lines etc.
 - Take all remaining lines which are longer (with indentation) then threshold repeat until there is none
    - If they contain a 'breaking' character break lines after last breaking character before threshold
    - If there are no remaining lines which can be break at preferred character, break after last token before threshold
    - If there is no such character (single token with indentation is longer than threshold) ignore line and print it as full

**Comment by durka** [comment]
OK, let's prototype out-of-tree because building the compiler is lame. I created a skeleton here with your example as the test case: https://github.com/durka/trace-pretty

I'll try to hack something together this weekend, but feel free to PR.

**Comment by Mark-Simulacrum** [comment]
This seems like something that would be best implemented via PR, and discussion can happen on internals.
