### ISSUE TITLE
rustdoc non-test examples usage is undocumented

### ISSUE THREAD

**Issue by uzytkownik** [rust-lang/rust#45206]
I tried to exclude an example from being run as a test. I tried several attributes I found on the internet/in documentations such as `rust,no_run`, `rust, no_run`, `no_run` but none of them worked. `ignore` did worked but doesn't seem to be documented anywhere.

**Comment by steveklabnik** [comment]
These are documented at https://doc.rust-lang.org/beta/rustdoc/documentation-tests.html, which hits stable tomorrow! Before that, they were covered in the book.

Anyway, sorry that was hard to find, but it is there, so I'm going to give it a close.

**Comment by uzytkownik** [comment]
@steveklabnik They document `no_run` which doesn't seem to work...

**Comment by kennytm** [comment]
@uzytkownik Hi, could you clarify what is meant by "does not work"? Note that rustdoc will still try to compile ` ```no_run ` code, but won't run it.

**Comment by uzytkownik** [comment]
@kennytm I missed that. So if I don't want to compile test I should use `ignore`?

**Comment by kennytm** [comment]
@uzytkownik Hmm yes. But if you want to ensure the code is never compilable, you should use ` ```compile_fail ` instead of ` ```ignore `. (` ```compile_fail ` will be stabilized in 1.22.)
