### ISSUE TITLE
std::collections::hash_map::{Entry, OccupiedEntry, VacantEntry} are never Send/Sync

### ISSUE THREAD

**Issue by sdleffler** [rust-lang/rust#45219]
Currently, the `HashMap` entry types are never `Send` or `Sync`. It seems to me that the `Entry` types should be `Send` whenever their key/value types are `Send` and `Sync` whenever their key/value types are `Sync`. Properly implementing `Send`/`Sync` for `OccupiedEntry` and `VacantEntry` will solve the problem for `Entry` as well. Is there any known reason why `Entry` and friends should *not* be `Send` or `Sync`?

**Comment by cuviper** [comment]
For comparison, `btree_map::Entry` has both `Send` and `Sync` -- manually implemented on `NodeRef` and then automatically propagating up.  The similar low level for `HashMap` would be the `RawBucket`.

**Comment by nox** [comment]
It's not clear to me whether propagating from `RawBucket` is a good idea, given that if the `Send` impl of `hash_map::Iter` is removed, `hash_map::Iter` would then implement `Send` where `K: Send, V: Send` instead of `K: Sync, V: Sync`.
