### ISSUE TITLE
[incremental] Isolate the "used trait imports" part of typeck tables into a distinct query

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#45214]
As part of https://github.com/rust-lang/rust/issues/45208, one place where `typeck_tables_of` is used that cannot easily be removed is [this call from `check_unused`](https://github.com/rust-lang/rust/blob/72d65019c789138f555c7cf7139508d2f9f0dffe/src/librustc_typeck/check_unused.rs#L69). What this code is doing is aggregating the set of trait imports that are used by all the function bodies in the crate. Due to glob imports and the like, it is hard to isolate which function body may make use of which trait import. Also, this information is only available from type-checking. So this will require serializing **some** amount of incremental data in between sessions. But since we don't want to save all of the typeck data, we can at least minimize the amount of data.

The idea is to introduce a new intermediate query `used_trait_imports(D)` for some def-id D. It will have the return type `Rc<DefIdSet>` and will return the [`used_trait_imports` field from `typeck_tables_of(D)`](https://github.com/rust-lang/rust/blob/72d65019c789138f555c7cf7139508d2f9f0dffe/src/librustc/ty/context.rs#L391).

The steps are as follows:

- Change the type of `used_trait_imports` to be `Rc<DefIdSet>` so it can be cheaply cloned. Make the code compiled.
- Introduce the `used_trait_imports` query as defined above; it should return `tcx.typeck_tables_of(key).used_trait_imports.clone()`.
- Modify [these lines](https://github.com/rust-lang/rust/blob/72d65019c789138f555c7cf7139508d2f9f0dffe/src/librustc_typeck/check_unused.rs#L69-L72) to use your new query instead of `typeck_tables_of`.

**Comment by cjkenn** [comment]
I think I'd like to take this on! Would be my first contribution to rust but you've laid the steps out pretty clearly and provided a lot of context so I think I would be able to work on it

**Comment by wesleywiser** [comment]
I think this issue can be closed now.
