### ISSUE TITLE
Provide better guidance for `Error::description`

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#45249]
https://doc.rust-lang.org/stable/std/error/trait.Error.html#tymethod.description

We don't do enough to explain this method at the moment; we allude to it with the `Display` mention, but should provide better guidance.

1. this is basically regarded as a bad API
2. it's really only usable with literals
3. as such, it should contain a really simple description at best
4. `Display` on the error is much more flexible and can provide a richer error message

**Comment by durka** [comment]
Re (1) should we discuss deprecating it?

**Comment by Mark-Simulacrum** [comment]
cc @rust-lang/libs

**Comment by alexcrichton** [comment]
cc @withoutboats

**Comment by pornel** [comment]
RFC for de-facto deprecation: https://github.com/rust-lang/rfcs/pull/2230

**Comment by GuillaumeGomez** [comment]
Considering the RFC has been merged, we can close this issue.
