### ISSUE TITLE
jemalloc in 1.21.0 doesn't work on iOS

### ISSUE THREAD

**Issue by michaelfairley** [rust-lang/rust#45262]
Jemalloc 4.5.0 (first included in 1.21.0) immediately aborts when run on ARM iOS devices. ([Upstream issue](https://github.com/jemalloc/jemalloc/issues/608)). Fortunately, the underlying issue seems to have been fixed in jemalloc 5.0.0 and onwards. (Unfortunately, a Rust PR to upgrade to 5.0.1 just got closed: https://github.com/rust-lang/rust/pull/45163).

Using the system allocator is an okay workaround for now (though, it requires using nightly).

**Comment by sfackler** [comment]
It sounds like you tracked the commit that fixed it down? We may be able to cherry-pick that onto our 4.5.0 fork to avoid having to go debug Android.

**Comment by arthurprs** [comment]
I don't think that change can be backported  easily. I guess the best option would be to use system allocator in this platform.

**Comment by kali** [comment]
Should we consider just disabling jemalloc for iOS ? My understanding is that the only real use-case for iOS rust executables is tests and bench using dinghy or some other contraption of the same kind so the impact feels minimal.

**Comment by michaelfairley** [comment]
> My understanding is that the only real use-case for iOS rust executables is tests and bench...

I definitely ship apps with rust executables to the App Store. 😐 

I'd be fine with disabling jemalloc in lieu of the system allocator until some future jemalloc upgrade.

**Comment by kali** [comment]
Ha, good to know :) We only ship libraries, but we do like our tests... I am working on a PR with jemalloc disabled.

**Comment by SimonSapin** [comment]
@michaelfairley Should this be closed, after https://github.com/rust-lang/rust/pull/46211 ?

**Comment by michaelfairley** [comment]
I suppose! #46211 definitely has me running and happy.

It's probably worth tracking this _somewhere_ though, since it's probably ideal to reenable jemalloc on iOS after a future jemalloc upgrade.

**Comment by SimonSapin** [comment]
Ok, thanks! Closing.

Per https://github.com/rust-lang/rust/issues/36963 the plan is to remove jemalloc from the standard library, so this will become a non-issue there. Try https://crates.io/crates/jemallocator and see if it works for you? I think these days it uses jemalloc 5.0.x
