### ISSUE TITLE
rustdoc search engine: tab key should iterate over "Types/modules", "As parameters" and "As return value"

### ISSUE THREAD

**Issue by dns2utf8** [rust-lang/rust#45279]
Maybe shift+tab should jump reverse.

The arrow keys up and down are currently used to walk through the results and left right are for navigating the query. To me this feels natural so I would keep it.

cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
I like this idea so I implement it!

**Comment by dns2utf8** [comment]
Cool, I think #45288 fixes that

**Comment by GuillaumeGomez** [comment]
It does. :)
