### ISSUE TITLE
Structure query engine caches around DefId being a CrateNum & intra-crate DefIndex.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#45275]
Per-crate cache maps keyed on `DefIndex` may be more efficient and/or allow us to use `Vec` for queries keyed on `DefId` instead of `HashMap`.
We can use specialization (e.g. for splitting `(DefId, T)` into `CrateNum` and `(DefIndex, T)`), I think.

cc @nikomatsakis @michaelwoerister

**Comment by michaelwoerister** [comment]
Sounds like a good idea if the lookup array ends up being densely populated enough. In general, we should provide a way to implement customized in-memory caching for specific queries.
