### ISSUE TITLE
Remove librustc_codegen_utils.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#45276]
Added by #44085, doesn't serve a real purpose. Common utility functions belong in `librustc`.

**Comment by eddyb** [comment]
Second offender: #45381.

**Comment by kzys** [comment]
Seems we don't have librustc_trans_utils anymore?

**Comment by eddyb** [comment]
@kzys It got renamed in the meanwhile.

**Comment by cjgillot** [comment]
I believe this should be closed by https://github.com/rust-lang/rust/pull/69965
