### ISSUE TITLE
subtract with overflow in release mode

### ISSUE THREAD

**Issue by ZhangHanDong** [rust-lang/rust#45287]
The following code attempt to subtract with overflow in release mode.

```rust
fn main() {
    let data  = [0, 1, 2, 3];
    for i in 0..data.len() {
        if data[i] == 0 {
             println!("{}", i - 1); // 18446744073709551615
        }
    }
}
```
[playground link](https://play.rust-lang.org/?gist=4b433e4c29ce7e992302a232038c0198&version=stable)

**Comment by sfackler** [comment]
What is the problem here? Overflow checks are only present in debug mode.

**Comment by ZhangHanDong** [comment]
@sfackler I see, thanks.

**Comment by ZhangHanDong** [comment]
@sfackler  The problem is that the following code didn't overflow checks in debug mode.

```rust
// data.rs
fn main() {
    let data  = [0, 1, 2, 3];
    for i in 0..data.len() {
        if data[i] == 0 {
             println!("{}", i - 1); 
        }
    }
}
```
 Normal compilation , but it should be emit  warning info: 
```rust
$  rustc  data.rs
```
But  it will be panic when run .
[playgroud](https://play.rust-lang.org/?gist=14ddffe90a6769c8b49822c974f80173&version=stable)

**Comment by sfackler** [comment]
The panic is the overflow check.

**Comment by ZhangHanDong** [comment]
@sfackler  overflow check in runtime?

**Comment by sfackler** [comment]
Yes.

**Comment by ZhangHanDong** [comment]
the following code will be emit warning info in compile time.

```rust
fn main(){
    let m : usize= 0;
    m - 1;
}
```
like this:

```rust
warning: this expression will panic at run-time
  |
3 |     m - 1;
  |     ^^^^^ attempt to subtract with overflow
```

**Comment by ZhangHanDong** [comment]
@sfackler  I got it.  thanks.
