### ISSUE TITLE
rustdoc help function breaks exit when typing

### ISSUE THREAD

**Issue by dns2utf8** [rust-lang/rust#45286]
Steps to reproduce:

1. open [the docs](https://doc.rust-lang.org/nightly/std)
2. klick somewhere so the focus goes away from the search bar
3. press `?`
4. start typing letters or numbers, more than 3
5. see the query change in the blurred background
6. pressing `Esc` does no longer close the dialog

cc: @GuillaumeGomez

**Comment by kennytm** [comment]
Step 4 should should be "press <kbd>S</kbd>".

As a workaround, you could close by pressing <kbd>Tab</kbd> then <kbd>Esc</kbd>.

**Comment by dns2utf8** [comment]
The problem is that after you press `?` you get the overlay with the help text and should not be able to submit keystrokes to the main UI. Maybe the help should close on the first keystroke.

**Comment by GuillaumeGomez** [comment]
I'm gonna fix it soon.

**Comment by dns2utf8** [comment]
@kennytm yes you are right. I was hammering over "S" too
