### ISSUE TITLE
Path::new(".").is_dir() and Path::new("..").is_dir() always return true?

### ISSUE THREAD

**Issue by vyings** [rust-lang/rust#45302]
It seems this problem originates in the underlying system `stat`. What is the recommended method to check their existence? Is this considered a bug?

**Comment by retep998** [comment]
This is a unix specific issue. The current directory on Windows always has an open handle and as such always exists.

**Comment by goffrie** [comment]
This isn't a bug - `.` is indeed always a directory, even if it's been deleted. The inode hangs around until all references (processes' working directories count as references) are gone.

**Comment by iology** [comment]
I can understand the result is not intuitive. Currently I combine is_dir() and cononicalize() to check both of them. Need a documentation update?

**Comment by iology** [comment]
Please note that if you check with the absolute path `Path::new("/path/to/directory").is_dir()`, then the result is "correct".

**Comment by Dylan-DPC** [comment]
Closing this as this is intended behaviour and I don't think there is anything we can do here.
