### ISSUE TITLE
The macro_rules treat `Ok(n)` as not a pattern

### ISSUE THREAD

**Issue by vakimov** [rust-lang/rust#45314]
The macro_rules treat `Ok(n)` as not a pattern

Macro for example:

```rust
macro_rules! foo {
    ($expr:expr) => (
        match "1".parse::<i32>() {
            $expr => println!("{}", n),
            _ => println!("wrong"),
        }
    );
}

foo!(Ok(n));
```

Compilation error:

```
error: expected pattern, found `Ok(n)`
   --> src/main.rs:195:17
    |
195 |                 $expr => println!("{}", n),
    |                 ^^^^^
```

**Comment by cramertj** [comment]
In this line:
> ($expr:expr) => (

You've told the compiler to parse `$expr` as an expression. You want to parse it as a pattern-- try `$(my_pattern:pat)` instead. For more information, check out the [Little Book of Rust Macros section on `macro_rules!`](https://danielkeep.github.io/tlborm/book/mbe-macro-rules.html).

**Comment by vakimov** [comment]
Thx, my bad
