### ISSUE TITLE
./configure options not supported by config.toml

### ISSUE THREAD

**Issue by infinity0** [rust-lang/rust#45313]
At the moment we're forced to use both ./configure and config.toml because the latter doesn't contain everything we need:

~~~~
$ grep DEB_CONFIGURE_FLAGS debian/rules 
DEB_CONFIGURE_FLAGS = --enable-llvm-link-shared --disable-dist-src --prefix=/usr --release-channel=$(RELEASE_CHANNEL) --disable-debuginfo-only-std
DEB_CONFIGURE_FLAGS += --llvm-root=$(LLVM_DESTDIR)/usr/lib/llvm-$(LLVM_VERSION)
        DEB_CONFIGURE_FLAGS += --enable-local-rust --local-rust-root=/usr
  DEB_CONFIGURE_FLAGS += --disable-docs
  DEB_CONFIGURE_FLAGS += --disable-optimize --disable-optimize-cxx --disable-optimize-llvm
~~~~

**Comment by alexcrichton** [comment]
This should be fixed on master, where config.mk/configure are "no longer a thing" and there's only one configuration system through config.toml (which the configure script now generates)

**Comment by infinity0** [comment]
Oh that looks good, closing and sorry for the noise. Looks like --local-rust-root has been replaced by "rustc" and "cargo" and --llvm-root by "llvm-config".

**Comment by alexcrichton** [comment]
Ah yeah a few options may have changed, but it should be easy enough to add them back if needed!
