### ISSUE TITLE
BufReader/Writer extension methods: is_empty, buffer

### ISSUE THREAD

**Issue by fintelia** [rust-lang/rust#45323]
**Update:** this is the tracking issue for:

```rust
impl<R: Read> BufReader<R> {
    pub fn buffer(&self) -> &[u8] {…}

    #[rustc_deprecated(since = "1.26.0", reason = "use .buffer().is_empty() instead")]
    pub fn is_empty(&self) -> bool {…}
}
```

`is_empty` is both unstable and deprecated, it should be removed.

----

There is currently no way to tell whether there is any data buffered inside a BufReader. This is unfortunate because it means that an application has no way to know whether calls to read() and fill_buffer() will return instantly or trigger a potentially expensive call to the underlying Reader. I propose adding an is_empty() method to BufReader to fill this gap.

**Comment by jonhoo** [comment]
@kennytm now that #45369 has been merged, I'm guessing this should get the `C-tracking-issue` label?

**Comment by dbrgn** [comment]
What's left for this to stabilize?

I'm parsing bytes from a `BufReader` to MsgPack using [read_value](https://docs.rs/rmpv/0.4.0/rmpv/decode/value/fn.read_value.html). The function will stop parsing once a valid MsgPack value has been found. But in my application the parsing should fail if the buffer hasn't been consumed completely. Checking `buf.is_empty()` would probably be the cleanest way to do so.

**Comment by jonhoo** [comment]
@dbrgn the `BufReader::buf_bytes` method proposed in https://github.com/rust-lang/rust/issues/48022 may also be useful for that purpose, though that may take even longer to land.

**Comment by SimonSapin** [comment]
This is the tracking issue for:

```rust
impl<R: Read> BufReader<R> {
    pub fn is_empty(&self) -> bool { /*…*/ }
}
```

Looks good to me to stabilize.

@rfcbot fcp merge

**Comment by sfackler** [comment]
This seems fine to stabilize, but it seems like it'd be more useful to know how many bytes are buffered, rather than just that there are some number of bytes.

**Comment by SimonSapin** [comment]
Why not both? Slices have `is_empty` even though it’s somewhat redundant with `len`.

**Comment by sfackler** [comment]
For sure. Would it be reasonable to try to squeeze that into this stabilization?

**Comment by SimonSapin** [comment]
Sounds ok to me, though we should probably (re)start FCP after the implementation is merged.

**Comment by sfackler** [comment]
Naming wise, I don't think `len` fits since that seems to me like it'd refer to the length of the entire reader rather than just the current buffered data (similarly `is_empty` is a bit confusing). How about `buffered_len` and `buffer_is_empty`?

**Comment by SimonSapin** [comment]
Agreed. Sounds good to me.

**Comment by sfackler** [comment]
Alternatively, we could add `fn buffer(&self) -> &[u8]` to just return the buffer, which is also a thing people want separately from this issue. At that point `r.buffer().len()` seems not much worse than `r.buffer_len()` so we could have one method instead of three.

**Comment by sfackler** [comment]
#49139 adds `buffer` and deprecates `is_empty`.

**Comment by fintelia** [comment]
With @sfackler's alternative (and IMO better) proposal just introduced, should this still be going into its final comment period?

**Comment by SimonSapin** [comment]
@rfcbot fcp cancel

Let’s start again after `buffer()` has landed.

**Comment by jonhoo** [comment]
We should likely also add a `.buffer()` method to `BufWriter` for consistency?

**Comment by sfackler** [comment]
That can't be done backwards compatibly.

**Comment by jonhoo** [comment]
@sfackler why not? It's just a `struct`, right? Just like `BufReader`.

**Comment by sfackler** [comment]
Oh derp I somehow read that as `BufWrite`.

**Comment by jonhoo** [comment]
Haha, no worries. Is there even a `BufWrite` trait?

**Comment by sfackler** [comment]
No there isn't >_>

Off of the topic of me needing more caffeine, it definitely seems reasonable to add `buffer` to `BufWriter`, and fold it into the same feature gate as `BufReader`'s.

**Comment by fintelia** [comment]
It has been a while since `buffer` landed. Is this ready to stabilize?

**Comment by SimonSapin** [comment]
`BufReader::buffer` is implemented, but `BufWriter::buffer` discussed above is not. (I’ve updated the issue’s description with the current status.)

**Comment by fintelia** [comment]
Wait, we aren't proposing to stabilize the (already deprecated) is_empty method are we?

**Comment by SimonSapin** [comment]
No, sorry I didn’t clarify. An API marked both unstable and deprecated is to be removed (after something like a couple release cycles of deprecation period, which we’re at in this case).

**Comment by zslayton** [comment]
I'm excited to see that this is so close to landing. Is this still waiting on an implementation of `BufWriter::buffer`? Would it be possible to track that feature separately to unblock this one?

**Comment by fintelia** [comment]
Bump. Is there anything else blocking stabilization?

**Comment by edef1c** [comment]
Is there any particular reason not to add `fn buffer(&self) -> &[u8] { &[] }` to `BufWrite`?
It seems like a useful enough general-purpose API: "get me however many bytes you can easily give me".
Individual implementations could make stricter guarantees about the lower bounds, of which "at least the unconsumed fraction of the last `fill_buf`" would be a common one.

**Comment by fintelia** [comment]
Yeah, this has been a while. @SimonSapin @sfackler is this ready for a vote to merge?

**Comment by fintelia** [comment]
This issue seems to have been stuck in a strange limbo state for quite a while now. Pinging more people the rfcbot mentioned...  @alexcrichton @aturon @dtolnay @withoutboats

**Comment by SimonSapin** [comment]
Sorry we dropped the ball here. This is now one method on the `BufReader` and `BufWriter` structs. 

```rust
impl<R> BufReader<R> {
    pub fn buffer(&self) -> &[u8] {…}
}
impl<W: Write> BufWriter<W> {
    pub fn buffer(&self) -> &[u8] {…}
}
```

@rfcbot fcp merge

**Comment by SimonSapin** [comment]
@edef1c There is nothing called `BufWrite` in std. Did you mean the `BufRead` trait? A downside is that to add it now we would have to make it a default method, which would (at first) have an inconsistent behavior with `fill_buf` for existing impls. We can update impls in std at the same time, but that leaves impls in other crates.

**Comment by edef1c** [comment]
@SimonSapin Sorry, yes, I meant `BufRead`. For my use cases, not having a lower bound is fine. Anything that does can use a marker subtrait that encompasses that guarantee.
I think the only stipulation should be that it not provide *more* than `fill_buf`, but less is fine. For example, an implementation might copy existing data around on `fill_buf` to make a larger contiguous segment, but can't/shouldn't do so in `buffer` (I think it should be a cheap conversion, `as_buffer` wouldn't have been an unreasonable name).

**Comment by jonhoo** [comment]
Should this be tagged `relnotes`?
