### ISSUE TITLE
docs for str::find say closure but don't use a closuer

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#45327]
https://doc.rust-lang.org/stable/std/primitive.str.html#examples-21

> More complex patterns with closures:

... but it uses point-free style, not closures.

We should probably show both.

**Comment by christianpoveda** [comment]
I'd like to take care of this one

**Comment by steveklabnik** [comment]
@christianpoveda that'd be great! Do you know what needs to be done, or do you need some help/advice?

**Comment by christianpoveda** [comment]
If I understand, you want to change `s.find(char::foo)` by

**Comment by christianpoveda** [comment]
If I understand, you want to change `s.find(char::foo)` by `s.find(|x| x.foo())`, right?

**Comment by LeopoldArkham** [comment]
It would be nice to have both so people still know they can use UFCS syntax (as long as it  takes a char and returns a boolean) which is cleaner in trivial cases.
Perhaps add an example that looks for a delimiter symbol (`-/_.`)

**Comment by steveklabnik** [comment]
> If I understand, you want to change s.find(char::foo) by s.find(|x| x.foo()), right?

I'd say "add" rather than change, it's nice to show both.

@LeopoldArkham just so you know, it's not UFCS anymore, but [fully qualified syntax](https://doc.rust-lang.org/book/second-edition/ch19-03-advanced-traits.html#fully-qualified-syntax-for-disambiguation).

**Comment by LeopoldArkham** [comment]
TIL; Thank you steve!
