### ISSUE TITLE
Implement `std::fmt::Display` for `()`

### ISSUE THREAD

**Issue by bvssvni** [rust-lang/rust#45341]
In generic code, I `()` as a "default type". I would like to write code which represents a custom `Display` with special behavior for `()` and default behavior for other types. The check can be done using `TypeId`, but since `()` does not implement `Display` it can not be used as constraint on the type parameter.

[Link to playground example](https://play.rust-lang.org/?gist=5de086aabfe18e03c4359bee9156f439&version=undefined)

```rust
use std::fmt;

pub struct Foo<T>(T);

impl<T: 'static + fmt::Display> fmt::Display for Foo<T> {
    fn fmt(&self, fmt: &mut fmt::Formatter) -> fmt::Result {
        use std::any::TypeId;
    
        if TypeId::of::<()>() == TypeId::of::<T>() {
            write!(fmt, "{}", self.0)?;
        } else {
            write!(fmt, "(empty)")?;
        }
        Ok(())
    }
}

fn main() {
    let foo = Foo(());
    println!("{}", foo);
}
```

**Comment by durka** [comment]
What should it print? `""`? It sounds like you might want to use specialization.

**Comment by dtolnay** [comment]
Display is for user-facing output, and there is not a universally appropriate user-facing representation of `()` that it could print.

Can you say more about your real use case? It is hard to give a good recommendation knowing nothing about `Foo` but here are some ideas. You could define your own sentinel type instead of using `()`:

```rust
struct Empty;

impl Display for Empty {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("(empty)")
    }
}

impl<T: Display> Display for Foo<T> {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        Display::fmt(&self.0, f)
    }
}
```

Or `Foo` could be an enum with a variant representing the empty state:

```rust
enum Foo<T> {
    T(T),
    Empty,
}

impl<T: Display> Display for Foo<T> {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match *self {
            Foo::T(ref t) => Display::fmt(t, f),
            Foo::Empty => f.write_str("(empty)"),
        }
    }
}
```
