### ISSUE TITLE
Rustdoc missing where-clause for <*const T>::offset

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#45389]
https://doc.rust-lang.org/nightly/std/primitive.pointer.html#method.offset

The implementation looks like:

```rust
pub unsafe fn offset(self, count: isize) -> *const T where T: Sized
```

But rustdoc only shows:

```rust
unsafe fn offset(self, count: isize) -> *const T
```

I tried to reproduce this with a struct type, but rustdoc seemed to do the right thing for this case.

```rust
pub struct Ptr<T: ?Sized>(*const T);

impl<T: ?Sized> Ptr<T> {
    pub fn offset(self, count: isize) -> Ptr<T> where T: Sized {
        unimplemented!()
    }
}
```

**Comment by ollie27** [comment]
I believe this is a duplicate of #24183.

**Comment by dtolnay** [comment]
Indeed, thank you.
