### ISSUE TITLE
invalid expression !808 = !DIExpression(6, 34, 0, 6)

### ISSUE THREAD

**Issue by Laaas** [rust-lang/rust#45387]
`rustc --version --verbose`
```
rustc 1.21.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.21.0
LLVM version: 5.0
```

This happens when building a specific program with `rustc -g`

The program:
```rust
use std::io::Read;

fn main() {
    let mut s = String::new();
    let stdin = std::io::stdin();
    let _ = stdin.lock().read_to_string(&mut s);
}
```

stderr:
```
invalid expression
!808 = !DIExpression(6, 34, 0, 6)
```

This started happening after updating to rust 1.21 today.

**Comment by Laaas** [comment]
Can anyone tell me if this bug has any major implications? Because the program generated still works.

**Comment by kennytm** [comment]
@Laaas Rust does not support LLVM 5 yet. If you are building rustc yourself, try to target LLVM 4 instead. The error you see should be the same as https://github.com/rust-lang/rust/issues/43370#issuecomment-321647649.

**Comment by TimNN** [comment]
As this is a known issue of the LLVM 5.0 upgrade, I'm gonna close this issue.
