### ISSUE TITLE
target_env for x86_64-unknown-linux-gnux32

### ISSUE THREAD

**Issue by malbarbo** [rust-lang/rust#45390]
The target `x86_64-unknown-linux-gnux32` was [added](https://github.com/rust-lang/rust/pull/45224) to rustc with `target_env = "gnu"`. 

I was wondering if it should be `"gnux32"` because of [this](https://github.com/rust-lang/llvm/blob/2e9f0d21fe321849a4759a01fc28eae82ef196d6/include/llvm/ADT/Triple.h#L115) llvm definition.

Here are the `target_env` for some rustc targets:

```
mips-unknown-linux-uclibc -> uclibc
x86_64-unknown-linux-musl -> musl
mips64el-unknown-linux-gnuabi64 -> gnu
armv7-unknown-linux-gnueabihf -> gnu
```

What do you think?

**Comment by alexcrichton** [comment]
I'd probably stick with "gnu" as this is differentiated by `target_pointer_width`, and otherwise anything with `target_env = "gnu"` is basically just going to get a new cfg for `gnux32` as well (if we add it)

**Comment by malbarbo** [comment]
Thanks @alexcrichton. Let's keep "gnu" then.
