### ISSUE TITLE
llvm UNREACHABLE for x86_64-unknown-linux-gnux32  target

### ISSUE THREAD

**Issue by malbarbo** [rust-lang/rust#45417]
```
> rustc --version --verbose
rustc 1.22.0-nightly (4750c1ec0 2017-10-19)
binary: rustc
commit-hash: 4750c1ec047f18bc0e33823182e09711a3826fb5
commit-date: 2017-10-19
host: x86_64-unknown-linux-gnu
release: 1.22.0-nightly
LLVM version: 4.0
```

Trying

```
echo "fn main() { println!() }" | rustc --target x86_64-unknown-linux-gnux32 -
```

rustc is aborted with the error

```
Cannot emit physreg copy instruction
UNREACHABLE executed at /checkout/src/llvm/lib/Target/X86/X86InstrInfo.cpp:5778!
```

Which also appears in https://github.com/rust-lang/rust/issues/45416 and https://github.com/rust-lang/rust/issues/37976.

Using the docker image to build https://github.com/rust-lang/rust/pull/45391 I got the same errors, but using a rustc built without the docker container (using debian9) I can build many programs - but running the programs generates a SIGBUS or SIGTRAP, which seems to indicate stack problems (as [suggested](https://github.com/rust-lang/rust/pull/45391#issuecomment-338087194) by @alexcrichton). Note that inside docker many tests are build and run fine!

**Comment by malbarbo** [comment]
Passing `-O` fix the problem

```
echo "fn main() { println!() }" | rustc -O --target x86_64-unknown-linux-gnux32 -
```

**Comment by tormol** [comment]
I cannot reproduce this with Rust 1.33.0 and LLVM 8.0

However I've run into other issues with `println!` on x86_64-unknown-linux-gnux32 that also only happen in debug-mode, but they happen at run-time and felt different enough that I've opened a new issue: #59220
