### ISSUE TITLE
Footnotes don't display properly under CommonMark

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#45420]
[This footnote](https://github.com/rust-lang/rust/blob/87a8e8e07387f99ffe931b1f2bbc4c0585b16ccc/src/libcore/lib.rs#L13) generates different HTML under `--enable-commonmark` and not. Not only does this trigger what's effectively a spurious warning, but it doesn't render correctly either.

cc @QuietMisdreavus @GuillaumeGomez , marking this as p-high

**Comment by ollie27** [comment]
This was fixed by google/pulldown-cmark#21 rustdoc just needs to update its version of pulldown-cmark.

**Comment by QuietMisdreavus** [comment]
The thread in that issue says it was released in 0.0.15. [According to the lockfile](https://github.com/rust-lang/rust/blob/87a8e8e07387f99ffe931b1f2bbc4c0585b16ccc/src/Cargo.lock#L1224-L1239) we're pulling in 0.0.14 for rustdoc, but also 0.1.0 for mdbook. I'll see if i can update the dependency for rustdoc and pull it in.

**Comment by QuietMisdreavus** [comment]
https://github.com/rust-lang/rust/pull/45421 updates Pulldown for rustdoc and fixes this.

**Comment by steveklabnik** [comment]
I am not sure this actually fixes the warnings, as they use different IDs and such.

I'm testing this locally right now though; expect an update in ~20 minutes
