### ISSUE TITLE
likely/unlikely intrinsics don't need unsafe

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#45445]
Minor paper-cut, but these intrinsics are safe.

**Comment by gnzlbg** [comment]
Relates to #45440. If we can get them to propagate properly through inline(always) functions, we would be able to write a "safe" wrapper around them that we can stabilize.

**Comment by rkruppe** [comment]
These are far from the only intrinsics that are safe, but there's currently no way to make intrinsics safe (short of a safe wrapper). I think I saw an issue about this at some point but I can't find it now.

**Comment by est31** [comment]
For safe wrappers for likely/unlikely intrinsics, one can also do macros with `allow_internal_unsafe`: [see it live](https://rust.godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(j:1,source:%27%23!!%5Bfeature(core_intrinsics)%5D%0Aextern+crate+core%3B%0Ause+core::intrinsics::unlikely%3B%0A%0A%23%5Binline(always)%5D%0Afn+test(x:+bool)+-%3E+bool+%7B%0A++++unsafe+%7B%0A++++++++unlikely(x)%0A++++%7D%0A%7D%0A%0Apub+fn+foo(x:+u32)+-%3E+u32+%7B%0A++if+test(x+%3D%3D+0)+%7B+1+%7D+else+%7B+x+*+2+%7D+%0A%7D%0A%0Apub+fn+foo2(x:+u32)+-%3E+u32+%7B%0A++unsafe+%7B%0A++let+c+%3D+unlikely(x+%3D%3D+0)%3B%0A++if+c+%7B+1+%7D+else+%7B+x+*+2+%7D+%0A++%7D%0A%7D%0A%0Apub+fn+bar(x:+u32)+-%3E+u32+%7B%0A++if+x+%3D%3D+0+%7B+1+%7D+else+%7B+x+*+2+%7D+%0A%7D%27),l:%275%27,n:%270%27,o:%27Rust+source+%231%27,t:%270%27)),k:33.333333333333336,l:%274%27,n:%270%27,o:%27%27,s:0,t:%270%27),(g:!((h:compiler,i:(compiler:nightly,filters:(___0:(),b:%270%27,binary:%271%27,commentOnly:%270%27,demangle:%270%27,directives:%270%27,execute:%271%27,intel:%270%27,jquery:%273.2.1%27,length:1,prevObject:(___0:(sizzle1505479566317:(undefined:(legend:!(5,0,%271%27)))),length:1,prevObject:(___0:(jQuery3210103775392123826471:(display:%27%27),sizzle1505479566317:(undefined:(legend:!(5,0,%271%27)))),length:1)),trim:%271%27),libs:!(),options:%27-C+opt-level%3D3+-C+target-cpu%3Dcore2%27,source:1),l:%275%27,n:%270%27,o:%27rustc+nightly+(Editor+%231,+Compiler+%231)%27,t:%270%27)),k:33.333333333333336,l:%274%27,n:%270%27,o:%27%27,s:0,t:%270%27),(g:!((h:output,i:(compiler:1,editor:1),l:%275%27,n:%270%27,o:%27%231+with+rustc+nightly%27,t:%270%27)),k:33.33333333333333,l:%274%27,n:%270%27,o:%27%27,s:0,t:%270%27)),l:%272%27,n:%270%27,o:%27%27,t:%270%27)),version:4):

```rust
#[allow_internal_unsafe]
macro_rules! unlikely {
  ($e:expr) => {
    unsafe {
      unlikely($e)
    }
  };
}
```

You can pair it with `allow_internal_unstable` to expose stable `unlikely`/`likely` macros!

**Comment by jbayardo** [comment]
The snippet by @est31 should be:

```
#[allow_internal_unsafe]
macro_rules! unlikely {
  ($e:expr) => {
    #[allow(unused_unsafe)]
    unsafe {
      std::intrinsics::unlikely($e)
    }
  };
}
```

And requires

```
#![feature(core_intrinsics)]
#![feature(allow_internal_unsafe)]
#![feature(stmt_expr_attributes)]
```

In order to work seamlessly as of today's nightly.

**Comment by est31** [comment]
@jbayardo AFAIK you can also attach the `#[allow(unused_unsafe)]` to the macro declaration, it should work too. The entire macro can theoretically be exposed by the standard library.

**Comment by jbayardo** [comment]
That did not work for me. I believe this shouldn't be a macro though, the likely/unlikely intrinsics should just be safe; the `#allow(unused_unsafe)` won't warn you in cases like

```rust
unsafe {
  ...
  if likely!(unsafe { ... }) {
    ...
  } else {
    ...
  }
}
```

**Comment by rkruppe** [comment]
You can't just mark intrinsics safe, because all intrinsics are `extern "rust-intrinsic"` functions and extern functions are always unsafe to call. Changing that would require some new language feature, e.g., as proposed by #1248.

**Comment by dtolnay** [comment]
As mentioned, there are many other intrinsics that should not require unsafe. This is going to need an RFC around how to expose intrinsics that are safe to call. One previous RFC on this topic was closed https://github.com/rust-lang/rfcs/pull/1248#issuecomment-260061132 but the lang team plans to follow up by merging the idea of "intrinsic" and "lang item", at which point `likely` and `unlikely` would be exposed as safe to call.
