### ISSUE TITLE
Simple-looking code change causes massive memory usage, OOM when using LTO

### ISSUE THREAD

**Issue by rqou** [rust-lang/rust#45457]
If I perform a release build of [this code](https://github.com/azonenberg/openfpga/commit/d39ad244f0f376a9c3cf9772750b7aa357fad824), the build completes in a reasonable amount of time using 1GB of memory or less. If I build the [next commit](https://github.com/azonenberg/openfpga/commit/7d634ccc5ba53d9fdf1110ecef8276a568e2ed59), rustc will start consuming more and more memory until it eventually consumes 20-30GB and gets OOM-killed. Both builds are done by running `cargo build --release` in the `src/xc2bit` subdirectory. Disabling LTO gets the memory usage back to a reasonable amount.

This happens with both stable and nightly.

```
$ rustc --version --verbose
rustc 1.20.0 (f3d6973f4 2017-08-27)
binary: rustc
commit-hash: f3d6973f41a7d1fb83029c9c0ceaf0f5d4fd7208
commit-date: 2017-08-27
host: x86_64-unknown-linux-gnu
release: 1.20.0
LLVM version: 4.0
```

**Comment by jonas-schievink** [comment]
Unsurprisingly, according to `-Ztime-passes` it happens during "LTO passes", but not while building all binaries (`xc2crbit2jed.rs` compiles fine, `xc2jed2crbit.rs` and `xc2jed2json.rs` do not).

**Comment by nikomatsakis** [comment]
triage: P-medium

**Comment by rqou** [comment]
WIth today's release of Rust 1.25, this problem seems to have fixed itself! Now after compiling for a very very long time (`208.89 secs` in one run) this eventually does succeed without OOMing.
