### ISSUE TITLE
Document more about the closure traits

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#45460]
Rust has a multitude of traits for closures: `Fn`, `FnMut`, `FnOnce`. The documentation for the three closures seems to be lacking in two points:

* Why does Rust have to differ between the three closure traits? It feels very bad if you have to follow by some rules you don't know why they are present!
* Which closure trait should you prefer if you just want to write an API that accepts some closure?

**Comment by steveklabnik** [comment]
Does the section in the book answer these questions? Should we model it after that?

**Comment by est31** [comment]
There is already a link in the rustdoc of the traits to the second edition of the book. While covering a wide range of topics regarding closures, I only see a description of what the traits represent, but not which one you should use for your APIs and why. Also, the section of the book seems to not contain any info on the *why* (my first point).
