### ISSUE TITLE
simplify variance

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#45471]
Before red-green, the incremental tracking for variance computation had to do [some complex stuff, as described here](https://github.com/rust-lang/rust/tree/6db27d9f90223693e84d230e5654d4c1a5afe700/src/librustc_typeck/variance#dependency-graph-management). This can be removed now. This means ripping out the [`dependencies` field](https://github.com/rust-lang/rust/blob/6db27d9f90223693e84d230e5654d4c1a5afe700/src/librustc_typeck/variance/constraints.rs#L45) and the various bits of code that were needed to keep it updated. We should also be able to remove [this block of code that injects "extra" dependencies](https://github.com/rust-lang/rust/blob/6db27d9f90223693e84d230e5654d4c1a5afe700/src/librustc_typeck/variance/mod.rs#L102-L110) and -- crucially -- [the `with_ignore` call on this line](https://github.com/rust-lang/rust/blob/6db27d9f90223693e84d230e5654d4c1a5afe700/src/librustc_typeck/variance/mod.rs#L99).

**Comment by SimonSapin** [comment]
I’ll work on this.

**Comment by power10dan** [comment]
Hi, I don't know if this is the right place, but I would also like to give this issue a try. 
Is there any way that I can get started?

**Comment by SimonSapin** [comment]
Hi @power10dan. Instructions are in the original message, but this issue already has a PR: https://github.com/rust-lang/rust/pull/45473

**Comment by power10dan** [comment]
Oh got it! Thanks for letting me know!
