### ISSUE TITLE
Type inference regression on beta using `as _`

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#45480]
Spotted by @Gankro : 
```rust
fn main() {
    let mut x: u64 = 0;
    let y: u32 = 0;
    x += y as _;   // Compiles on stable, fails on beta/nightly
}
```

**Comment by ollie27** [comment]
I believe this is expected breakage from #44287.

**Comment by jrmuizel** [comment]
It would be valuable to have a list breaking changes that's updated whenever something breaking lands.

**Comment by pietroalbini** [comment]
This also happens when using methods like `parse`:

```rust
fn main() {
    let mut var = 0;
    let other = "10".parse().unwrap();  // Fails on beta/nightly
    var += other;
}
```

**Comment by Mark-Simulacrum** [comment]
Also occurs in [average-0.6.2](http://cargobomb-reports.s3.amazonaws.com/stable-1.21.0-beta-1.22.0-beta.3/beta-2017-11-13/reg/average-0.6.2/log.txt) cc @vks

**Comment by Mark-Simulacrum** [comment]
As well as:
 [minions-0.2.8](https://crates.io/crates/minions/0.2.8) [log](http://cargobomb-reports.s3.amazonaws.com/stable-1.21.0-beta-1.22.0-beta.3/beta-2017-11-13/reg/minions-0.2.8/log.txt) cc @dbeck
[netlink-rs-0.0.3](http://cargobomb-reports.s3.amazonaws.com/stable-1.21.0-beta-1.22.0-beta.3/beta-2017-11-13/reg/netlink-rs-0.0.3/log.txt) cc @crhino 
[odds-0.2.25](http://cargobomb-reports.s3.amazonaws.com/stable-1.21.0-beta-1.22.0-beta.3/beta-2017-11-13/reg/odds-0.2.25/log.txt) cc @bluss
[pbr-demo](https://github.com/samsartor/pbr-demo#8cb72ed951165f4f9f73096d2e275f502d3a6635) [log](http://cargobomb-reports.s3.amazonaws.com/stable-1.21.0-beta-1.22.0-beta.3/beta-2017-11-13/gh/samsartor.pbr-demo.8cb72ed951165f4f9f73096d2e275f502d3a6635/log.txt) cc @samsartor

**Comment by Mark-Simulacrum** [comment]
And also [whiteread-0.4.3](http://cargobomb-reports.s3.amazonaws.com/stable-1.21.0-beta-1.22.0-beta.3/beta-2017-11-13/reg/whiteread-0.4.3/log.txt) cc @krdln

**Comment by vks** [comment]
Thanks for the heads-up, this was fixed in average-0.6.3.

**Comment by egilburg** [comment]
Just wondering, should `as` be at all needed in the above example? if `x` is `u64` and `y` is `u32`, it seems the only choice is to upcast `y` to `x`, it's not something that's ambiguous or could be hand-coded any better. Could the compiler detect that and make just `x += y` compile without manual upcast, in the same spirit as making `x += &y` work without manual deref?

**Comment by lilianmoraru** [comment]
Yep, this looks really bad:
```
result += "10".parse().unwrap();  // Fails on beta/nightly
println!("{}", result);
```

**Comment by Mark-Simulacrum** [comment]
@rust-lang/libs: Closing this as we can't revert now as this has leaked onto stable. Ideally we'd probably have type defaults or something to avoid this in the future.
