### ISSUE TITLE
graphiz: improve DepNode dependency graph

### ISSUE THREAD

**Issue by vitiral** [rust-lang/rust#45490]
**Note: Work In Progress**

cc @michaelwoerister @nikomatsakis 

## Notes
- [docs on existing dependency graph](https://github.com/rust-lang/rust/blob/master/src/librustc/dep_graph/README.md#debugging-the-dependency-graph)

## Summary
The existing dependency graph often "sqashes" the graphs into a hard to read layout and we can probably do better. I will be investigating and recording thoughts in this issue and hopefully come up with a better overall approach.

**Comment by Mark-Simulacrum** [comment]
I'm going to go ahead and close this as it's rather light on content and isn't quite clear as to what is intended here.
