### ISSUE TITLE
rust crashes on mac nightly when running test that have should_panic

### ISSUE THREAD

**Issue by sagiegurari** [rust-lang/rust#45494]
I found that when running tests that should panic (and have the should panic annotation defined), the thing crashes only on mac and only in nightly rust.
This started around 2-3 days ago.

Sample Code:

````rust
fn main() {
    println!("test");
}

#[cfg(test)]
mod test {
    #[test]
    fn bool_test() {
        assert!(true);
    }

    #[test]
    #[should_panic]
    fn test_panic() {
        panic!("test");
    }
}
````

Travis build logs as an example:
https://travis-ci.org/sagiegurari/misc-test/builds/292137566
specially:
https://travis-ci.org/sagiegurari/misc-test/jobs/292137568#L75

Sample branch:
https://github.com/sagiegurari/misc-test/tree/rust_mac

**Comment by sagiegurari** [comment]
Is there some ETA regarding this one?

**Comment by arielb1** [comment]
Can someone with a mac test this?

**Comment by sagiegurari** [comment]
Looks like this one was fixed yesterday. Thanks.
