### ISSUE TITLE
Unhelpful error message when trying to add elements to hash map

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#45491]
The following code [works fine](https://godbolt.org/g/FoYDUM) in cpp:

```cpp
    std::map<int, int> m;
    m[0] = 0;
```

In Rust however, you are getting an error:

```rust
    let mut f :HashMap<u8, u8> = HashMap::new();
    f[&0] = 0;
```

```
error[E0594]: cannot assign to immutable indexed content
 --> src/main.rs:4:2
  |
4 | 	f[&0] = 0;
  | 	^^^^^^^^^ cannot borrow as mutable
```

The error doesn't really tell you what is indexed immutably. IMO it should explain that hashmaps have the insert function instead and maybe even should suggest it.

**Comment by leonardo-m** [comment]
That functionality was removed:
https://github.com/rust-lang/rust/pull/23559

>This commit removes the IndexMut impls on HashMap and BTreeMap, in order to future-proof the API against the eventual inclusion of an
IndexSet trait.

Do you know if there's a enhancement request for IndexSet trait? Or a RFC.

**Comment by est31** [comment]
@leonardo-m there are [multiple](https://github.com/rust-lang/rfcs/pull/1129) [discussions](https://github.com/rust-lang/rfcs/issues/997) about IndexAssign, but I don't want to change the language, I just want the compiler output to be nicer.
