### ISSUE TITLE
Cross compilation to 32-bit may be broken on recent nightlies

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#45500]
As of a few nights ago I've noticed that a good bit of the Travis CI runs I've got that cross compile to 32-bit are now broken due to odd linker errors, for example https://travis-ci.org/alexcrichton/cc-rs/builds/290881204.

I bisected nightlies to [this range](https://github.com/rust-lang/rust/compare/4750c1ec047f18bc0e33823182e09711a3826fb5...b633341c49498488b6e3fce501e23e9f9f8fadec), and @michaelwoerister I wonder if this is related to the change to sip128? Do you know of anything there that would cause linker errors?

Unfortunately I haven't been able to reproduce on Linux, I've just seen this on [OSX](https://travis-ci.org/alexcrichton/jemallocator/jobs/291654312) and [Windows](https://ci.appveyor.com/project/rust-lang-libs/cargo/build/1.0.2941)

**Comment by carols10cents** [comment]
manifests as the CI failures in cargo: https://github.com/rust-lang/cargo/pull/4658

**Comment by alexcrichton** [comment]
Cc @michaelwoerister

**Comment by michaelwoerister** [comment]
Yes, when switching to SipHash I also switched away from using `leb128` for all integers. That might introduce a difference for `isize` and `usize`. I'll take a look.

**Comment by shaleh** [comment]
A simple Docker based test case fails with link issues. I made no edits to the generated code. This is just hello world.

    rustup install nightly
    rustup default nightly
    cargo init test32bit --bin
    cd test32bit
    cargo build

I used https://github.com/ioft/dockerhub/i386-ubuntu/Dockerfile to test this. Note it makes an i686, not i386 but it is still 32 bit linux.

The failed output looks like this:

= note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m32" "-L" "/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib" "/root/test32bit/target/debug/deps/test32bit-4197078e3788cd4f.test32bit0.rust-cgu.o" "/root/test32bit/target/debug/deps/test32bit-4197078e3788cd4f.test32bit1.rust-cgu.o" "-o" "/root/test32bit/target/debug/deps/test32bit-4197078e3788cd4f" "/root/test32bit/target/debug/deps/test32bit-4197078e3788cd4f.crate.allocator.rust-cgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs" "-L" "/root/test32bit/target/debug/deps" "-L" "/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libstd-f64e65221ded4189.rlib" "/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/liballoc_jemalloc-15603b85f9b07db5.rlib" "/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/liballoc_system-7f202905b2f90235.rlib" "/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libpanic_unwind-fd7102ed26e1ee75.rlib" "/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/librand-b2608977e05bf703.rlib" "/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libunwind-3d18fc673b5da13d.rlib" "/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/liblibc-390d7866de44001e.rlib" "/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/liballoc-28619888b40bbbe2.rlib" "/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libstd_unicode-6e3e1588214a0702.rlib" "/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libcore-a30e14812908fc60.rlib" "/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libcompiler_builtins-20161fbf48c6c15f.rlib" "-Wl,-Bdynamic" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util" "-l" "util"
= note: /root/test32bit/target/debug/deps/test32bit-4197078e3788cd4f.test32bit0.rust-cgu.o: In function test32bit::main': /root/test32bit/src/main.rs:2: undefined reference tostd::io::stdio::_print::h6c953456faaea52a'
/root/test32bit/target/debug/deps/test32bit-4197078e3788cd4f.test32bit0.rust-cgu.o: In function main': /root/test32bit/src/main.rs:(.text.main+0x37): undefined reference tostd::rt::lang_start::hb4e4c925bf3928b1'
collect2: error: ld returned 1 exit status

**Comment by shaleh** [comment]
In a bigger project I see LOTS of linker errors. It cannot find core::panic, fmt macros, and on and on.

**Comment by michaelwoerister** [comment]
The latest nightly should contain a potential fix to this problem. @shaleh, would you mind re-testing your case?

**Comment by shaleh** [comment]
@michaelwoerister I will not not until Tuesday or Wednesday.

**Comment by nikomatsakis** [comment]
triage: P-high

**Comment by shaleh** [comment]
Success!

cargo new test32 --bin
     Created binary (application) `test32` project
root@cc25a7d3570a:~# cd test32/
root@cc25a7d3570a:~/test32# ls
Cargo.toml  src
root@cc25a7d3570a:~/test32# cargo build
   Compiling test32 v0.1.0 (file:///root/test32)
    Finished dev [unoptimized + debuginfo] target(s) in 0.38 secs
root@cc25a7d3570a:~/test32# cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/test32`
Hello, world!

**Comment by michaelwoerister** [comment]
Thanks a lot for confirming, @shaleh!

I'm going to close this issue. Please re-open if there's still a case that isn't fixed.
