### ISSUE TITLE
how to resolve this issue: std::rt::lang_start undefined reference

### ISSUE THREAD

**Issue by xianghx** [rust-lang/rust#45517]
uname --a
Linux sky 3.13.0-117-generic #164-Ubuntu SMP Fri Apr 7 11:06:36 UTC 2017 i686 i686 i686 GNU/Linux

cc --version
cc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

rustc --version
rustc 1.22.0-nightly (4c053db23 2017-10-22)

rustc hello.rs
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m32" "-L" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib" "hello.hello0.rust-cgu.o" "-o" "hello" "hello.crate.allocator.rust-cgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs" "-L" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libstd-f64e65221ded4189.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/liballoc_jemalloc-15603b85f9b07db5.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/liballoc_system-7f202905b2f90235.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libpanic_unwind-fd7102ed26e1ee75.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/librand-b2608977e05bf703.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libunwind-3d18fc673b5da13d.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/liblibc-390d7866de44001e.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/liballoc-28619888b40bbbe2.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libstd_unicode-6e3e1588214a0702.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libcore-a30e14812908fc60.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libcompiler_builtins-20161fbf48c6c15f.rlib" "-Wl,-Bdynamic" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util" "-l" "util"
  = note: hello.hello0.rust-cgu.o：在函数‘main’中：(note: in the function main)
          hello0-e36fee694dd79ad6eb28a0e541972798-exe.rs:(.text.main+0x2d)：对‘std::rt::lang_start::hb4e4c925bf3928b1’未定义的引用 (note: undefined reference)
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

**Comment by oli-obk** [comment]
What's the content of `hello.rs`?

Is this only happening on a recent `nightly`? Or did it happen before?

Does `stable` produce the same error?

**Comment by xianghx** [comment]
stable ok.
maybe 2007-10-14 nightly ok.

then, rustup update nightly , doesn't work.

hello.rs 
fn main() {}

**Comment by xianghx** [comment]
raphlinus commented 2 days ago 

This looks like something wrong in your build environment, not with pulldown-cmark itself. rust-lang/rust#42239 is a similar error. Are you able to compile other programs?
--
see https://github.com/google/pulldown-cmark/issues/101

**Comment by oli-obk** [comment]
Have you tried updating nightly again?

**Comment by xianghx** [comment]
rustup update nightly
info: syncing channel updates for 'nightly-i686-unknown-linux-gnu'

  nightly-i686-unknown-linux-gnu unchanged - rustc 1.22.0-nightly (4c053db23 2017-10-22)

**Comment by xianghx** [comment]
I don't know why it does not 2007-10-25.

**Comment by Mark-Simulacrum** [comment]
@alexcrichton Possibly related to the recent breakage of 32-bit cross compiles on nightlies?

**Comment by alexcrichton** [comment]
Seems quite likely, yes, that this is https://github.com/rust-lang/rust/issues/45500
