### ISSUE TITLE
rustdoc: Display collapse button on mobile

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/rust#45520]
The collapse button is extremely useful for briefing, and as #45502 is adding the second button, we should show the +/- button as well.

cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
The +/- buttons are there as well. Which ones are you talking about?

**Comment by ishitatsuyuki** [comment]
Uh, I mean the master "collapse all" button.

**Comment by GuillaumeGomez** [comment]
Oh I see. I'll give it a look.

**Comment by GuillaumeGomez** [comment]
The master "collapse all" button is already displayed as well (on nightly). I'll close this issue then!
