### ISSUE TITLE
rustc should print an unambiguous error message when building no_std binaries with panic=unwind

### ISSUE THREAD

**Issue by Trolldemorted** [rust-lang/rust#45533]
As we have found out in #45492, rustc cannot (yet) build a `no_std` binary when compiling with panic=unwind.

Instead of aborting and printing an error message, rustc builds objects that have external dependencies, in msvc's case `__CxxFrameHandler3`.

**Comment by Mark-Simulacrum** [comment]
Today we say "error: `#[panic_handler]` function required, but not found" which seems basically perfect since that'll lead you to https://doc.rust-lang.org/nomicon/panic-handler.html which'll hopefully make it mostly clear what needs to happen.
