### ISSUE TITLE
std::net::UdpSocket semantics are not user friendly

### ISSUE THREAD

**Issue by achanda** [rust-lang/rust#45539]
According to the documentation [1], a caller needs to first bind to a local socket and then call connect with the server's address before sending data. In most cases, the kernel should be able to allocate a source port and the first bind should not be necessary. This makes the API unnecessarily complex. Equivalent C code

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <netinet/in.h>

int main( void )
{
    int fd;
    if ( (fd = socket(AF_INET, SOCK_DGRAM, 0)) < 0 ) {
        perror("socket failed");
        return 1;
    }

    struct sockaddr_in serveraddr;
    memset( &serveraddr, 0, sizeof(serveraddr) );
    serveraddr.sin_family = AF_INET;
    serveraddr.sin_port = htons( 50037 );
    serveraddr.sin_addr.s_addr = htonl( 0x7f000001 );

    for ( int i = 0; i < 4; i++ ) {
        if (sendto( fd, "hello", 5, 0, (struct sockaddr *)&serveraddr, sizeof(serveraddr)) < 0 ) {
            perror( "sendto failed" );
            break;
        }
        printf( "message sent\n" );
    }

    close( fd );
}
```

The only way to achieve this currently is to use the `libc` or `nix` crate and call `socket(2)` in a similar way. This is not ergonomic.

[1] https://doc.rust-lang.org/std/net/struct.UdpSocket.html#method.connect

**Comment by canndrew** [comment]
You don't have to call connect. `UdpSocket` has a `send_to` method as well.

```rust
let socket = UdpSocket::bind("0.0.0.0:0")?;
socket.send_to(data, "127.0.0.1:456")?;
```

**Comment by canndrew** [comment]
If you bind to port 0 the operating system will choose a source port for you.

**Comment by Mark-Simulacrum** [comment]
Closing since we seem to provide a way to do this. Thanks!
