### ISSUE TITLE
io::IntoInnerError should have a .into_error

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#45547]
If you don't care about the underlying writer after an error, it'd be nice to be able to grab the io::Error out.

**Comment by dtolnay** [comment]
Seems good to me.

```diff
  pub struct IntoInnerError<W>(W, Error);

  impl<W> IntoInnerError<W> {
      pub fn error(&self) -> &Error;
+     pub fn into_error(self) -> Error;
      pub fn into_inner(self) -> W;
  }
```

**Comment by sfackler** [comment]
There's already a `From<IntoInnerError> for io::Error` implementation, so this isn't necessary.
