### ISSUE TITLE
Tracking issue for `core::ptr::dangling/_mut` (feature `ptr_dangling`)

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#45557]
Tracking issue for `core::ptr::dangling/_mut` (feature `ptr_dangling`)

- (To be) Implemented in PR #45527

**Comment by nagisa** [comment]
One issue I can see with this function is that it might return pointers that actually point somewhere even on systems where the 0th page is considered to be always unmapped.

**Comment by petrochenkov** [comment]
As I understand it the point of the function is to return something non-null and aligned, so it doesn't matter whether it's a valid pointer or not.
We can just specify that you are not allowed to dereference the pointer returned by `ptr::dangling` without guaranteeing anything about it validity (i.e. equality to other existing valid pointers).

**Comment by nagisa** [comment]
That seems fine. I was concerned because IIRC the PR specifically said
something about them being valid and the documentation for the function
also said something similar.

**Comment by nagisa** [comment]
Ah the mornings.

The PR description had a proposal to name the function invalid_... And the
description specifically claims it will not point to any object.

I'd like the documentation changed so it doesn't attempt to guarantee the
function will always return an address that's not pointing to a valid
object.

**Comment by bluss** [comment]
If you want changes in the PR #45527, please write about them over there.

**Comment by SimonSapin** [comment]
This feature never landed and the implementation PR is closed. Closing this as well, feel free to reopen as appropriate.
