### ISSUE TITLE
TRPL - print button not working in beta or nightly

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/rust#45552]
Possibly related to https://github.com/rust-lang/rust/issues/44704, not sure yet. Mdbook related, not rustdoc. Possibly due to customizations we've made, not sure if mdbook bug or not yet.

If I visit https://doc.rust-lang.org/beta/book/second-edition/ or https://doc.rust-lang.org/nightly/book/second-edition/ and click the print button, nothing happens. Same non-behavior in firefox nightly and chrome.

What I expect to happen does happen on https://doc.rust-lang.org/stable/book/second-edition/, which is that I am taken to https://doc.rust-lang.org/stable/book/second-edition/print.html and a print dialog comes up.

cc @steveklabnik 

Poking at this slowly, not super high priority but we should figure it out before the next release

* Stable is using mdbook 0.0.22 https://github.com/rust-lang/rust/blob/3b72af97e42989b2fe104d8edbaee123cdf7c58f/src/tools/rustbook/Cargo.toml#L11
* Beta is using mdbook 0.0.26 https://github.com/rust-lang/rust/blob/f72478185b9ce5bdb37c3f5acc5c875be18e3ab1/src/tools/rustbook/Cargo.toml#L11
* Nightly is also on mdbook 0.0.26 https://github.com/rust-lang/rust/blob/e0febe71449008fd35ccc762b0a42d106aa8e4f7/src/tools/rustbook/Cargo.toml#L11

I am able to reproduce locally with mdbook 0.0.26
I am not able to reproduce locally with mdbook 0.0.25
I am able to reproduce locally with mdbook cd711bfb

**Comment by kennytm** [comment]
https://github.com/azerupi/mdBook/compare/0.0.25...0.0.26

Probably caused by azerupi/mdBook#439. Note that the PR introduced the diff:

```diff
diff --git a/src/theme/index.hbs b/src/theme/index.hbs
index 9f735e6cd..3b4dbd12c 100644
--- a/src/theme/index.hbs
+++ b/src/theme/index.hbs
@@ -88,7 +88,9 @@
                     <h1 class="menu-title">{{ book_title }}</h1>
 
                     <div class="right-buttons">
-                        <i id="print-button" class="fa fa-print" title="Print this book"></i>
+                        <a href="print.html">
+                            <i id="print-button" class="fa fa-print" title="Print this book"></i>
+                        </a>
                     </div>
                 </div>
```

But I can't see that `<a>` tag in the beta/nightly book.

**Comment by carols10cents** [comment]
AHA!! Nice catch @kennytm !!! We indeed customize index.hbs in the book, so that's probably the issue.
