### ISSUE TITLE
Comment generate error

### ISSUE THREAD

**Issue by vbextreme** [rust-lang/rust#45553]
`println!("hello world"/*//*/);`
This code generate error, in C are valid syntax.
```
Compiling playground v0.0.1 (file:///playground)
error: unterminated block comment
 --> src/main.rs:5:9
  |
5 |   /*co*/);/*//*/ }; 
  |  _________^
6 | |  println!("{:?}",x); }  
  | |________________________^

error: aborting due to previous error

error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```
I'm not a rust programmer, sorry for intrusion

Have a good life

**Comment by kennytm** [comment]
In Rust, unlike C, block comments can be nested:

```rust
fn /* outside
   /* inside */
*/ main() {}
```

Your example is thus tokenized as: `/*` `/` `/*` `/` — two opening block comments. The error is expected.

**Comment by vbextreme** [comment]
But comment in comment is a comment, at least that's what logic tells me.
I can't find the meaning but ok, thanks for the clarification and  for the time dedicated to me.

Have a good life.

**Comment by vbextreme** [comment]
` /* /* */ `
This have the same error, and not because have only opened the comment.
In C, unlike rust,  is only a warning and I can build.

**Comment by kennytm** [comment]
You have two `/*`, thus you need two `*/` to balance it.

`/* /* */ */`
