### ISSUE TITLE
Inferred type parameters do not have their type inference information carried over into closures 

### ISSUE THREAD

**Issue by KiChjang** [rust-lang/rust#45587]
Given this piece of code that compiles:

```rust
use std::collections::BTreeMap;

fn foo(_qux: &BTreeMap<&'static str, &'static str>) -> Option<String> {
    Some("baz".to_owned())
}

fn main() {
    let mut map = BTreeMap::new();
    
    map.insert("foo", "bar");
    foo(&map).and_then(|baz| {
        let mut map = map;
        map.insert("sign", &baz);
        Some(())
    });
}
```
https://play.rust-lang.org/?gist=593734bf5330b827466cb35bb7f68299&version=stable

Removing the `let mut map = map;` line would cause it to fail, and adding a `move` keyword right before `|baz|` does not resolve the problem.

(Link to the `move` version: https://play.rust-lang.org/?gist=cffef6eb08d8dd4be26d7699e61d0ac1&version=stable)

**Comment by KiChjang** [comment]
I _think_ I found the problem - the `map` variable is declared in the main function scope, and type inference can easily conclude that both K and V must have a static lifetime.

However, once it is moved into the closure using `let mut map = map;`, the `map` at this point is considered a new `BTreeMap`, and previous type inferrence on the outer `map` does not carry over to the new `map` variable inside the closure, hence allowing a shorter-than-static `&baz` lifetime.

**Comment by KiChjang** [comment]
So I think the surprise/feature/bug here is that in the main function scope, the `map` is inferenced to be `BTreeMap<&'static str, &'static str>`, but having the map type-inferred again in the closure as `BTreeMap<&'static str, &'a str>` simply by rebinding to get another type inference on the same struct.

**Comment by Lymia** [comment]
More specifically, you can move a `BTreeMap<&'static str, &'static str>` into a `BTreeMap<&'static str, &'a str>`, and it's perfectly sound because you can't go the other way after a move.

The type inference must have seen that this is possible, and hence, that this code would compile if the `map` variable in the inner scope was that type.

**Comment by DaseinPhaos** [comment]
@Lymia has this behavior been documented anywhere yet?

**Comment by arielb1** [comment]
@DaseinPhaos 

https://doc.rust-lang.org/reference/subtyping.html
