### ISSUE TITLE
rustbuild and bootstrapping failure

### ISSUE THREAD

**Issue by daym** [rust-lang/rust#45593]
Hi,

we at the Guix distribution are trying to update Rust to newer versions which use a rustbuild-based build. The Makefile-based build worked fine - but rustbuild fails at bootstrapping mostly because of x86_64 vs. i686 mixups.

What kind of build environment should we provide (in the chroot) for bootstrapping to succeed? Also, when should we switch to the normal (non-bootstrapping) gcc compiler and ld?

We tried: host&target i686 gcc & ld, host&target x86_64 gcc & ld, cross compiler with i686 host and x86_64 target, cross compiler with x86_64 host and i686 target.

Problems were: Picking up the wrong glibc, picking up the wrong crt, picking up the wrong ld; (failure usually when trying to build the "bootstrap" crate).

**Comment by est31** [comment]
@daym Have you tried building Rust with exactly one version before? Rust version 1.x *only* supports bootstrapping from version 1.(x-1), not 1.(x-2) or below, and also not 1.x or newer. And can you maybe paste an error somewhere?

**Comment by daym** [comment]
Yes, I built it with one version before. There are many error logs, I saved them. Which one?

**Comment by ipetkov** [comment]
@daym is this issue still relevant?

We've had plenty of version of rust building in Guix with rustbuild so this issue may be out of date

**Comment by daym** [comment]
No, it's from the 1.16.0 time where rustbuild was seriously rough at the edges. Works fine now and I guess one could always not use rustbuild for rust 1.16.0.
