### ISSUE TITLE
Running cargo check on webrender takes too long

### ISSUE THREAD

**Issue by jrmuizel** [rust-lang/rust#45596]
STR: touch webrender/src/glyph_cache.rs && cargo check
This takes about 4.8 seconds

A profile of it looks roughly as follows:
```
 - 77% type checking
   - 43.3% typeck::check_crate
   - 16.1% borrowck::check_crate
   - 5.1% driver::compile_input
 - 14% confugure and expand
 - 3.5% parse_input
```

**Comment by jrmuizel** [comment]
@aturon improving this would help with iterations times working on webrender.

**Comment by aturon** [comment]
cc @rust-lang/compiler @Mark-Simulacrum, this may be an interesting target to focus on.

**Comment by Mark-Simulacrum** [comment]
I'll note it down for potential benchmarks to add.

**Comment by michaelwoerister** [comment]
Good idea.

**Comment by michaelwoerister** [comment]
I did some benchmarking with the current nightly and incremental compilation activated. It shows a noticeable improvement:

```
$ touch webrender/src/glyph_cache.rs && CARGO_INCREMENTAL=1 cargo check
    Finished dev [unoptimized + debuginfo] target(s) in 3.55 secs
    Finished dev [unoptimized + debuginfo] target(s) in 3.40 secs
    Finished dev [unoptimized + debuginfo] target(s) in 3.42 secs
```

```
$ touch webrender/src/glyph_cache.rs && cargo check
    Finished dev [unoptimized + debuginfo] target(s) in 5.8 secs
    Finished dev [unoptimized + debuginfo] target(s) in 5.5 secs
    Finished dev [unoptimized + debuginfo] target(s) in 5.6 secs
```

Still by far not as fast as I'd like it to be.

**Comment by jackh726** [comment]
Retagging as WG-compiler-performance; this might not stay for long, but arguably a better tag for now

**Comment by Mark-Simulacrum** [comment]
perf.rlo suggests webrender-wrench and webrender both have sub-second wall times on recompile, so I'm going to go ahead and close.
