### ISSUE TITLE
Linking issue with rust nightly

### ISSUE THREAD

**Issue by jrozner** [rust-lang/rust#45607]
As of nightly-2017-10-28 I'm getting linking failures on OS X. Don't have rust setup on any other platforms to see if it occurs there as well but I'm getting the following error message while attempting to run `cargo build`.

```
error: failed to link or copy `/Users/joe/bug/target/debug/deps/bug-bfd5e2b3eb22d858.dSYM` to `/Users/joe/bug/target/debug/bug.dSYM`

Caused by:
  the source path is not an existing regular file
```

The code to recreate this test can be created simply by running `cargo new --bin bug`. Rolling back to 2017-10-24 results in a working compiler again.

**Comment by messense** [comment]
Same issue on macOS 10.13 with `rustc 1.23.0-nightly (269cf5026 2017-10-28)`

**Comment by sinkuu** [comment]
This seems to be the same issue as https://github.com/rust-lang/cargo/issues/4671

**Comment by lucasem** [comment]
You can revert to an older nightly where this isn't an issue using rustup:

```sh
rustup install nightly-2017-10-24
rustup override set nightly-2017-10-24
```
