### ISSUE TITLE
Cannot install rust using rustup-init.exe

### ISSUE THREAD

**Issue by neoedmund** [rust-lang/rust#45604]
> info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
> error: could not download file from 'https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256' to 'C:\Users\neoe\.rustup\tmp\me_a5xy3ylu4k7sb_file'
> info: caused by: error during download
> info: caused by: [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) -  ���ڵ������������ѻ������������޷���������)
> 
> Press the Enter key to continue.
or

> info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
> error: could not download file from 'https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256' to 'C:\Users\neoe\.rustup\tmp\ya_w77tm_fbinn_c_file'
> info: caused by: error during download
> info: caused by: [7] Couldn't connect to server (Failed to connect to static.rust-lang.org port 443: Timed out)

Please stop using foolish rustup-init, instead use download a full-sized exe(case on Windows) and one click install process.

**Comment by retep998** [comment]
If you want plain and simple standalone installers for Rust, you can get them from https://www.rust-lang.org/en-US/other-installers.html

Rustup is designed as a convenient way of installing and upgrading and managing multiple Rust toolchains simultaneously, and to do that rustup needs to be able to download various components itself. If you don't want that, then use the standalone installers.

**Comment by Mark-Simulacrum** [comment]
I'm not sure: is this an error in rustup, or does the network not allow connecting to static.r-l.o? If it's the latter, we should probably close this...

**Comment by neoedmund** [comment]
It should be connection problems. But I can use something like cargo update from rush servers after using standalone installer. Maybe the rustup-init and cargo update use different servers?
