### ISSUE TITLE
[rustdoc] Various issues with search tabs

### ISSUE THREAD

**Issue by Seeker14491** [rust-lang/rust#45608]
I've come across several issues related to the search tabs:
* While on the search results screen, if you click on the "As parameters" or "As return value" tabs, then type in a query, the results shown are from the "Types/modules" tab.
* The "As parameters" and "As return value" tabs only show results that have the query string in its name or path. Even then it's missing results. For example, `std::thread::current` has signature `pub fn current() -> Thread`, yet doesn't show up in the "As return value" tab when searching for "Thread".
* When searching, functions whose name is the same as its return type are not shown on the "Types/modules" tab. (details in my second post)
* I think the first tab shouldn't be labeled "Types/modules", as it also shows functions and macros.

[Link to the recent pull request implementing the search tabs](https://github.com/rust-lang/rust/pull/45055)

cc @GuillaumeGomez

**Comment by Seeker14491** [comment]
This is the original issue I was going to post about.

When searching, functions whose name is the same as its return type are not shown. For example, the [zip method](https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.zip) of the iterator trait returns a struct called [Zip](https://doc.rust-lang.org/nightly/std/iter/struct.Zip.html). When you search for "zip" in the search bar, the zip function is absent from the default "Types/modules" tab of the results:
![tmp1](https://user-images.githubusercontent.com/6490497/32140840-eccb4106-bc3c-11e7-97db-258d7ece11d8.PNG)

It only appears in the "As return value" tab:
![tmp2](https://user-images.githubusercontent.com/6490497/32140843-04ebbe64-bc3d-11e7-84ec-60aebed9513a.PNG)

I think the correct behavior should be the function appearing in both places.

I had a look at the source, and I believe the problem is [here](https://github.com/rust-lang/rust/blob/1fdcf52df48c6a16dab57337f311275f0d8995da/src/librustdoc/html/static/main.js#L954):

```javascript
if (results['others'].length < maxResults && ((query.search && obj.name.indexOf(query.search)) || added === false))
{
    results['others'].push(obj);
}
```

Adding ` != -1` so the code looks like this fixes the issue:

```javascript
if (results['others'].length < maxResults && ((query.search && obj.name.indexOf(query.search) != -1) || added === false))
{
    results['others'].push(obj);
}
```

I don't understand the code very well though.

**Comment by GuillaumeGomez** [comment]
Oh nice, thanks for the feedback! I'll fix it today.

**Comment by Seeker14491** [comment]
Great work! The last point hasn't been addressed though. I think something like "In name" would be a better label. Thoughts?

**Comment by GuillaumeGomez** [comment]
No clue... Might be worth opening a new issue so we can discuss about it.

**Comment by Seeker14491** [comment]
Ok, opened #45787.

**Comment by GuillaumeGomez** [comment]
Thanks!
