### ISSUE TITLE
Clojure with no argument

### ISSUE THREAD

**Issue by GildedHonour** [rust-lang/rust#45625]
When creating a clojure, I propose that we use |_| instead of || when there's no argument.

**Comment by Mark-Simulacrum** [comment]
This currently would be a backwards incompatible change, as `|_|` works today (and is equivalent to the function form: `fn name(_: T)`) where the argument is immediately dropped. As such, I am closing -- please file an RFC at rust-lang/rfcs if you'd like to further this change, or discuss on internals.r-l.o. I think it's relatively unlikely that such a change would be accepted at this point, though.
