### ISSUE TITLE
Confusing lifetime error focusing on returned object lifetime rather than inference due to subsequent use

### ISSUE THREAD

**Issue by marcianx** [rust-lang/rust#45627]
I just spent over an hour in a much more complex example trying to work around lifetime issues because the error was pointing at the wrong mistake. When I figured it out, the problem and the fist was painfully obvious; I don't know whether anything can be done to improve the errors. Again, the actual code is far more complex and after a lot of trial and error, I finally got down to the dramatically simplified example until the underlying cause finally clicked.

```rust
#[derive(Copy, Clone, PartialEq, Eq)]
pub struct Source<'a>(&'a str);

pub fn combine<'b, 'c>(
    first: &fn() -> Source<'b>,
    second: &fn() -> Source<'c>,
) -> Option<Source<'b>> {
    let loc1 = first();
    let loc2 = second();
    if loc1 == loc2 {
        Some(loc1)
    } else {
        None
    }
}
```
[Playground](https://play.rust-lang.org/?gist=a5bf522b0c5d1852db82ec40f1f58cb1&version=stable)

Error
```
   Compiling playground v0.0.1 (file:///playground)
error[E0495]: cannot infer an appropriate lifetime due to conflicting requirements
 --> src/main.rs:9:16
  |
9 |     let loc2 = second();
  |                ^^^^^^^^
  |
note: first, the lifetime cannot outlive the lifetime 'c as defined on the function body at 4:1...
 --> src/main.rs:4:1
  |
4 | / pub fn combine<'b, 'c>(
5 | |     first: &fn() -> Source<'b>,
6 | |     second: &fn() -> Source<'c>,
7 | | ) -> Option<Source<'b>> {
... |
14| |     }
15| | }
  | |_^
note: ...so that expression is assignable (expected Source<'_>, found Source<'c>)
 --> src/main.rs:9:16
  |
9 |     let loc2 = second();
  |                ^^^^^^^^
note: but, the lifetime must be valid for the lifetime 'b as defined on the function body at 4:1...
 --> src/main.rs:4:1
  |
4 | / pub fn combine<'b, 'c>(
5 | |     first: &fn() -> Source<'b>,
6 | |     second: &fn() -> Source<'c>,
7 | | ) -> Option<Source<'b>> {
... |
14| |     }
15| | }
  | |_^
note: ...so that expression is assignable (expected std::option::Option<Source<'b>>, found std::option::Option<Source<'_>>)
 --> src/main.rs:11:9
  |
11|         Some(loc1)
  |         ^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```
See if you can figure out without the hints.

**Hint 1:** Replacing `Source<'a>` with `&'a str` works.

**Hint 2:** Look at the issue title again.

**Hint 3:** Removing the `if` conditional also makes it compile.

**Answer:** The real problem is not at `second()` where most of my efforts at comprehending the compiler's mental model were (again, in a far more complex example). It's that the auto-derived `PartialEq` cannot compare two `Source` objects with unrelated lifetimes, as I do in `if loc1 == loc2` which is not mentioned in any of the error messages whatsoever. I just had to implement a more general `PartialEq`: `impl<a, b> PartialEq<Source<'b>> for Source<'a>` to get this working.

**Comment by estebank** [comment]
Just for reference, the following code would work:

```rust
#[derive(Copy, Clone, PartialEq, Eq)]
pub struct Source<'a>(&'a str);

pub fn combine<'b, 'c: 'b>(  // Note the bounding of lifetime `'c` with `'b`
    first: &fn() -> Source<'b>,
    second: &fn() -> Source<'c>,
) -> Option<Source<'b>> {
    let loc1 = first();
    let loc2 = second();
    if loc1 == loc2 {
        Some(loc1)
    } else {
        None
    }
}

fn main() {}
```

**Comment by estebank** [comment]
The code now compiles successfully in the beta without code changes.

**Comment by marcianx** [comment]
Wow! That's _way_ better than what I was suggesting/expecting. :D
