### ISSUE TITLE
weird span for E0595 with closure

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#45622]
The [following code](https://play.rust-lang.org/?gist=44f719f80bdf349eab0779b4e8bbaaa9&version=nightly) generates an error:

```rust
fn foo(x: &mut i32) {
    fn process(_: &mut i32) {}

    (|| {
        process(&mut x);
    })();
}
```

```
error[E0595]: closure cannot assign to immutable argument `x`
 --> src/main.rs:4:6
  |
1 | fn foo(x: &mut i32) {
  |        - consider changing this to `mut x`
...
4 |     (|| {
  |      ^^ cannot borrow mutably
```

The error is right (well, sort of -- it says "assign" which is inaccurate), but the span pointing at the closure head doesn't make a lot of sense. If the closure has arguments and/or a return type, the span covers those as well, but they are irrelevant.

**Comment by durka** [comment]
This might be a duplicate of #18330.

**Comment by Mark-Simulacrum** [comment]
Yeah, I'm going to close in favor of #18330 -- seems like this is something we'd either fix at the same time or just at some point down the road.

**Comment by estebank** [comment]
The output should point out at the use of `x` in some way, as well as changing the wording slightly (it is not an assignment):

```
error[E0595]: closure cannot modify immutable argument `x`
 --> src/main.rs:4:6
  |
1 | fn foo(x: &mut i32) {
  |        - consider changing this to `mut x`
...
4 |     (|| {
  |      ^^ cannot borrow mutably
5 |        process(&mut x);
  |                     - `x` used here
```
