### ISSUE TITLE
Example in docs of swap_with_slice()

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#45636]
The recently introduced slice method swap_with_slice() can't be used to swap two nonoverlapping parts of a single slice. But when you reshuffle parts of a single slice I think it could be useful. So I suggest to offer a slice function that performs this operation safely:

`v.swap_nonoverlapping(i, j, n);`

That's just a wrapper around (plus panics):

```
use std::ptr::swap_nonoverlapping;
swap_nonoverlapping(v[i ..].as_mut_ptr(), v[j ..].as_mut_ptr(), n);
```

**Comment by Thiez** [comment]
> The recently introduced slice method swap_with_slice() can't be used to swap two nonoverlapping parts of a single slice.

Sure it can be:

```rust
#![feature(swap_with_slice)]
fn main() {
    let mut slice = [3, 4, 1, 2];
    {
        let (fst, snd) = slice.split_at_mut(2);
        fst.swap_with_slice(snd);
    }
    println!("{:?}", slice); // prints [1, 2, 3, 4]
}
```

**Comment by leonardo-m** [comment]
Nice solution... so do you suggest me to close down this enhancement request?

**Comment by Thiez** [comment]
I am not part of the official Rust project, so I have no authority to tell you to do anything 😄. If you think the code I've shown is good enough that you feel your proposed enhancement is no longer relevant, then sure, close the issue. But if you still think a `swap_nonoverlapping` method would be a good idea, then by all means continue. However, the usual way of getting additions to the standard library is to go through the [RFC](https://github.com/rust-lang/rfcs/) process. Be warned, it's quite a lot of work.

**Comment by leonardo-m** [comment]
I think your solution is good enough for my problem. But I think eventually we'll need a solution for the discoverability of similar solutions combining two or three functions of the std library ::-) It's a matter of documentation... So I keep this issue open, but I suggest the addition of your solution to the docs of swap_with_slice().

**Comment by scottmcm** [comment]
It would be great to get a doc PR for all of `copy_from_slice`, `clone_from_slice`, and `swap_with_slice` that demonstrate using range indexing and `split_at` to work with sub-slices.  A few people have shown up on IRC asking about that after getting panics for different lengths and not knowing what to do.

**Comment by frewsxcv** [comment]
Opened a PR for this: https://github.com/rust-lang/rust/pull/46219
