### ISSUE TITLE
MIR-borrowck: assignment to static mut shouldn't be an error

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#45641]
MIR borrowck errors out on assignments to mutable statics, which should be allowed (in unsafe code) e.g.

```Rust
static mut Y: u32 = 0;

unsafe fn should_ok() {
    Y = 1;
}

fn main() {}
```

which causes:
```
$ rustc x.rs -Z borrowck-mir
error: cannot assign to immutable static item Y (Mir)
 --> x.rs:5:5
  |
5 |     Y = 1;
  |     ^^^^^

error: aborting due to previous error
```

**Comment by nikomatsakis** [comment]
Seems like this ought to fall out from permissions checking (https://github.com/rust-lang/rust/issues/44837), right?

**Comment by arielb1** [comment]
Nope, still broken in 88a28ff6028cf197ed6b4185d8cd4887f05e3e07

**Comment by KiChjang** [comment]
Looking at this as well. I believe the error comes from the improper static check in `check_if_reassignment_to_immutable_state`.
