### ISSUE TITLE
When seeing `x<-y` in a boolean expression, suggest `x < -y`.

### ISSUE THREAD

**Issue by kennytm** [rust-lang/rust#45651]
* Rationale: https://stackoverflow.com/q/47028390

[Test case](https://play.rust-lang.org/?gist=ac3b3d90d2c654dbc49a21c6c2ea0a1f&version=nightly):

```rust
fn main() {
    let x = -5;
    if x<-1 {
        println!("ok");
    }
}
```

The error currently looks like:

```
error: placement-in expression syntax is experimental and subject to change. (see issue #27779)
 --> src/main.rs:3:8
  |
3 |     if x<-1 {
  |        ^^^^
  |
  = help: add #![feature(placement_in_syntax)] to the crate attributes to enable
```

but the intent was not to use the placement-in, the suggestion is just confusing the user. If we do add `#![feature(placement_in_syntax)]` [the error message would be even worse](https://play.rust-lang.org/?gist=7132b050c3243ccb08b5b1ece9831376&version=nightly):

```
error[E0277]: the trait bound `{integer}: std::ops::Placer<_>` is not satisfied
 --> src/main.rs:5:8
  |
5 |     if x<-1 {
  |        ----
  |        |
  |        the trait `std::ops::Placer<_>` is not implemented for `{integer}`
  |        in this macro invocation
  |
  = help: the following implementations were found:
            <std::collections::linked_list::BackPlace<'a, T> as std::ops::Placer<T>>
            <std::collections::vec_deque::PlaceBack<'a, T> as std::ops::Placer<T>>
            <std::collections::hash_map::Entry<'a, K, V> as std::ops::Placer<V>>
            <&'a mut std::collections::BinaryHeap<T> as std::ops::Placer<T>>
          and 4 others
  = note: required by `std::ops::Placer::make_place`
```

The suggestion should actually mention inserting a space between `<` and `-` if a comparison with a negative number is intended, e.g.

```
error: placement-in expression syntax is experimental and subject to change. (see issue #27779)
 --> src/main.rs:3:8
  |
3 |     if x<-1 {
  |        ^^^^
  |        hint: for less-than comparison, try to add some spaces: `x < -1`
  |
  = help: add #![feature(placement_in_syntax)] to the crate attributes to enable
```

**Comment by estebank** [comment]
Should expand the following code:
https://github.com/rust-lang/rust/blob/442b7bd10ab1955832fac39e47671327747033c6/src/libsyntax/feature_gate.rs#L1518-L1519
to have a version `gate_feature_post!` that accepts extra notes, and add a note that if you meant to compare `x` with `1` you should add a space between `<` and `-` (you can get the spans from the two fields in `InPlace(expr, expr)`.

**Comment by arshiamufti** [comment]
Can I take this on? I have some time in the latter half of this month.

**Comment by estebank** [comment]
@arshiamufti [feel free to do so](https://forge.rust-lang.org/x-py.html) and to ask for help!

**Comment by PramodBisht** [comment]
@estebank Hi, Can I take this one? if yes, then I will need your guidance.

**Comment by arshiamufti** [comment]
hi @PramodBisht -- i'm actually going to work on this sometime in the near future :)

**Comment by PramodBisht** [comment]
@arshiamufti sure!
