### ISSUE TITLE
incr.comp.: Directly accessing attributes for `compile_codegen_unit()` might lead to surprising re-compilations

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#45653]
There are quite a few places in `trans` that will directly access the list of attributes of an item. Since doc comments are also represented as attributes internally, this might lead to a codegen unit surprisingly being re-translated although it was "just a comment" that has been changed.

The good news is that this can easily be prevented by wrapping the attribute access in a targeted query so that the red-green system has the chance of marking the attribute/doc change as non-essential to translation.

To solve this issue:
* Find all instances in `compile_codegen_unit` where attributes are accessed directly.
* Wrap those instances in new queries (or replace them by using existing queries).
* Write a regression test that makes sure that changing a doc comment does not cause the containing compilation unit to be re-compiled.

**Comment by wesleywiser** [comment]
I'm working on this.

**Comment by michaelwoerister** [comment]
This might be a bit harder to fix than I originally thought: Attributes influence the fingerprint not only of the `item_attrs()` query but also of the `Hir` and `HirBody` nodes which are accessed from lots of places (`TyCtxt::get_attrs()` but also pretty much everything in `tcx.hir`). 

A complete fix would involve splitting attributes out of the regular HIR nodes and introducing a separate `DepKind` for them. This isn't entirely trivial either since attributes can be attached to many kinds of things not only "item-likes". 

Since this is an optimization for a niche case I'm inclined to close this as a no-fix. Would do you say, @wesleywiser & @nikomatsakis?

**Comment by wesleywiser** [comment]
That's ok with me

**Comment by pnkfelix** [comment]
@michaelwoerister are you still planning to just close this?

**Comment by michaelwoerister** [comment]
Yes, let's close it. There's not much here that's actionable still.
