### ISSUE TITLE
enable elision in where-clauses on functions

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#45667]
The following test case does not presently work, but ought to:

```rust
trait Trait<'a> { }

// Supporting `'_` here is #15872:
impl<T> Trait<'_> for T { }

// Supporting `'_` here is this issue:
fn foo<T>(t: T)
where T: Trait<'_>
{ 
}

fn main() { 
  foo(22);
}
```

This is, I believe, blocked on #15872, because the same work that enables `'_` to expand to an early-bound region in that work ought to make supporting `'_` in functions fairly straightforward.

**Comment by nikomatsakis** [comment]
Actually, I thought we maybe didn't want to permit `'_` in this position, since we had not yet decided on what it means -- e.g., does it mean "some fresh lifetime name" or does it mean `for<'a> T: Trait<'a>`?

**Comment by nikomatsakis** [comment]
It turns out we accidentally started accepting `'_` in some of these positions; this was discovered in https://github.com/rust-lang/rust/issues/54902

**Comment by nikomatsakis** [comment]
It will become a hard-error again

**Comment by jackh726** [comment]
Retagging as wg-traits; supporting elision feels trait-y to me

**Comment by jackh726** [comment]
Visiting for types triage. This feels a bit dated to us. If this is something that is desired in the future, this should probably go throug an RFC.

**Comment by nikomatsakis** [comment]
A few thoughts here:

I think we need to draft up a coherent RFC about what `'_` means in all the places. I am of the opinion that it should mean "add a region to the innermost potential binder spot", which in this case would mean `where T: Trait<'_>` would mean `where T: for<'a> Trait<'a>`. I also think `impl Foo` should follow the same rules, so that `T: Trait<'_, impl Debug>` would be short for `T: for<'a, T: Debug> Trait<'a, T>`. But the topic is complex and hence the need for a lang team initiative to pursue
