### ISSUE TITLE
add 'make bench' target for pastebin/parseable formatted results

### ISSUE THREAD

**Issue by quentusrex** [rust-lang/rust#4566]
Run a series of standard benchmarks to be able to compare performance on different hardware, and from release to release(or patch to patch).

**Comment by steveklabnik** [comment]
triage: this is an enhancement, nothing has really changed.

**Comment by steveklabnik** [comment]
triage: no changes

**Comment by alexcrichton** [comment]
This is a pretty old bug at this point, and we now have http://perf.rust-lang.org/ for tracking perf, so I'm going to close this.
