### ISSUE TITLE
add timestamp to Rust Forge page

### ISSUE THREAD

**Issue by apopiak** [rust-lang/rust#45687]
When checking [the platform support page](https://forge.rust-lang.org/platform-support.html) for e.g. Solaris, it would be really great if one could see when the information was last updated. E.g. at which time and with which rust version was cargo built on `x86_64-sun-solaris`?
A minimal version would be to just add a timestamp to the Tier 3 section.

**Comment by steveklabnik** [comment]
Could you file this against the forge repo? https://github.com/rust-lang-nursery/rust-forge

Thanks!
