### ISSUE TITLE
bootstrap fails on NetBSD

### ISSUE THREAD

**Issue by MartinHusemann** [rust-lang/rust#45686]
Trying to boostrap rust on NetBSD/amd64 fails:

```
    Compiling toml v0.4.5
    Compiling bootstrap v0.0.0 (file:///work/rust/rust/src/bootstrap)
 error: Shared object "libproc_macro-33f3fe1937fc08f8.so" not found
    --> /work/rust/rust/src/bootstrap/lib.rs:123:1
     |
 123 | extern crate serde_derive;
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^
 error: Could not compile `bootstrap`.
```

**Comment by Mark-Simulacrum** [comment]
This looks like a problem with the rustc being used... @alexcrichton Might this mean that we don't have working beta for NetBSD currently?

**Comment by alexcrichton** [comment]
Maybe? No idea.

**Comment by MartinHusemann** [comment]
I started from scratch, so it downloaded the official beta. How can I help analysing?
Where is the libproc_macro reference coming from?
(@jakllsch - could you help?)

**Comment by Mark-Simulacrum** [comment]
Bootstrap depends on libproc_macro through serde_derive. I'll try and get some instructions for how to diagnose further typed up soon.

**Comment by jakllsch** [comment]
I bet it's something to do with `std::env::current_exe()` not actually being relaible on NetBSD.

If I let the bootstrap build fail, then execute:
```
ln -s /sd0a/jakllsch/rust/obj/build/x86_64-unknown-netbsd/stage0/lib/*.so build/bootstrap/debug/deps/
ln -s /sd0a/jakllsch/rust/obj/build/x86_64-unknown-netbsd/stage0/lib/*.rlib build/bootstrap/debug/deps/
```
After this resuming the bootstrap build succeeds, and it seems to be progressing to the rest of the build.

**Comment by MartinHusemann** [comment]
Thanks, I'll look at the NetBSD side of std::env::current_exe(), maybe we can do something to improve its reliability.

**Comment by MartinHusemann** [comment]
I instrumented access to /proc/curproc/exe and am pretty sure that this is not the reason for failure.
I get:
 > ../rust/x.py build |& tee /tmp/rust.log
Updating submodules
   Compiling bootstrap v0.0.0 (file:///work/rust/rust/src/bootstrap)
error: Shared object "libproc_macro-33f3fe1937fc08f8.so" not found
   --> /work/rust/rust/src/bootstrap/lib.rs:123:1
    |
123 | extern crate serde_derive;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: Could not compile `bootstrap`.

and during that try, the kernel logs:

rustc: exe is /work/rust/build/build/x86_64-unknown-netbsd/stage0/bin/rustc
cargo: exe is /work/rust/build/build/x86_64-unknown-netbsd/stage0/bin/cargo
rustc: exe is /work/rust/build/build/x86_64-unknown-netbsd/stage0/bin/rustc

so to me it looks like current_exe() is working just fine.

**Comment by Mark-Simulacrum** [comment]
If you run something like `find build -name 'libproc_macro*'`, what output do you get? I'm trying to see if the file actually doesn't exist, or whether we're just not finding it?

**Comment by MartinHusemann** [comment]
I have it twice (they are identitcal):

build/x86_64-unknown-netbsd/stage0/lib/rustlib/x86_64-unknown-netbsd/lib/libproc_macro-33f3fe1937fc08f8.so
build/x86_64-unknown-netbsd/stage0/lib/libproc_macro-33f3fe1937fc08f8.so

I traced the rustc process and extracted all attempts to open .so files.

The fun part is at the end. While it properly looks at the various paths for
others, it only trys /usr/lib for libproc_macro.

The .so has a $ORIGIN RPATH:

Dynamic section at offset 0x3e988 contains 29 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libsyntax-053c42242cf7fae8.so]
 0x0000000000000001 (NEEDED)             Shared library: [librustc_errors-3a43c9700ef50f60.so]
 0x0000000000000001 (NEEDED)             Shared library: [libsyntax_pos-c0a71a00b1235fd2.so]
 0x0000000000000001 (NEEDED)             Shared library: [libstd-61b5b9f1c88c205d.so]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.12]
 0x000000000000000f (RPATH)              Library rpath: [$ORIGIN/../lib]

I think we try to avoid that on NetBSD in general.

Many other .so have that RPATH, but libserde_derive does not:

  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libproc_macro-33f3fe1937fc08f8.so]
 0x0000000000000001 (NEEDED)             Shared library: [libstd-61b5b9f1c88c205d.so]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.12]
 0x000000000000000c (INIT)               0x12bd0
 0x000000000000000d (FINI)               0x1d0ee0


Martin
[rust-so-access.txt](https://github.com/rust-lang/rust/files/1443936/rust-so-access.txt)

**Comment by Mark-Simulacrum** [comment]
I'm not familiar enough with the dylib loading process unfortunately to be able to comment on this -- it seems like perhaps our loading calls are wrong...

**Comment by MartinHusemann** [comment]
The runtime loading itself is fine, something in the build process is broken so libserde_derive*.so does not get the expected RPATH (but maybe that is what you meant and I misunderstood)

**Comment by MartinHusemann** [comment]
Would you happen to have any idea who could give me a pointer where to look?
Is this a bug in the toml file in the crate or in cargo?

**Comment by jakllsch** [comment]
I see where src/bootstrap/bin/rustc.rs has bits that insert the $ORIGIN rpath.  I also see where src/bootstrap/tool.rs#389 vaguely suggests that it might not be using the aforementioned bootstrap rustc wrapper when it builds cargo and its dependencies.

Unfortunately, the bootstrap stuff is a bit too abstract for me to fully comprehend at this point.

Is it possible that we're trying to use a serde_derive and/or proc_macro binary library object from the stage0 bootstrap kit to compile `src/bootstrap` stuff, instead of building these libraries with the provided stage0 kit specifically for the new local build of `bootstrap`?  Or is it possible that we are already building these as fresh dependencies, but we're failing to find the correct instance (that is, the fresh one) of the binary?

**Comment by jakllsch** [comment]
Additional datapoint: Adding `rpath = true` to the `[profile.dev]` section in `src/Cargo.toml` gets bootstrap building for me.

**Comment by MartinHusemann** [comment]
I added that to all [profile.*] entries and now get a serde_derive-....so with a RUNPATH including $ORIGIN/../...

Why not RPATH ?

**Comment by MartinHusemann** [comment]
The fix is trivial, but creating a pull request for takes ages. I definitively hate git.

commit b5f81ba50c5bdcb0a3c0cf8f87f04c8ddd3f5246
Author: Martin Husemann <martin@NetBSD.org>
Date:   Thu Nov 23 10:20:38 2017 +0100

    RUNPATH is a Linuxism, so only use it there.
    RPATH is working fine on most other OSes.

diff --git a/src/librustc_trans/back/rpath.rs b/src/librustc_trans/back/rpath.rs
index 8e5e7d3764..719fa8a58e 100644
--- a/src/librustc_trans/back/rpath.rs
+++ b/src/librustc_trans/back/rpath.rs
@@ -41,7 +41,7 @@ pub fn get_rpath_flags(config: &mut RPathConfig) -> Vec<String> {
     flags.extend_from_slice(&rpaths_to_flags(&rpaths));
 
     // Use DT_RUNPATH instead of DT_RPATH if available
-    if config.linker_is_gnu {
+    if config.linker_is_gnu && target.target_os == "linux" {
         flags.push("-Wl,--enable-new-dtags".to_string());
     }

**Comment by MartinHusemann** [comment]
Trying to be helpfull, so I did it anyway: https://github.com/rust-lang/rust/pull/46202

**Comment by jyn514** [comment]
@MartinHusemann are you still running into this issue?

**Comment by he32** [comment]
The pkgsrc package for rust still to this day has

```
BUILDLINK_TRANSFORM.NetBSD+=   rm:-Wl,--enable-new-dtags
```

in the package Makefile, which means "remove this option from the command line before executing it".
So I would surmise that this is still an issue.

**Comment by MartinHusemann** [comment]
I checked again and it was only fixed for netbsd-9 and newer, while pkgsrc still (for a few more months to go) supports netbsd-8.
Why the fix never made it to netbsd-8 is unclear to me, but maybe the linker in there is plain too old? Seems to be binutils 2.27.
Anyway, the pkgsrc fix sounds fine as long as it is needed, so no further action required here, do you agree he32?

**Comment by jyn514** [comment]
I'm going to close this as not an upstream bug by the same rationale as https://github.com/rust-lang/rust/issues/46204#issuecomment-1415793093.
