### ISSUE TITLE
Compile error: clippy_lints does not support feature(macro_vis_matcher)

### ISSUE THREAD

**Issue by follitude** [rust-lang/rust#45680]
branch: master 
   Compiling cargo_metadata v0.2.3
   Compiling clippy_lints v0.0.166 (file:///home/ryan/git/rust/src/tools/clippy/clippy_lints)
error: :vis fragment specifier is experimental and subject to change (see issue #41022)
 --> <declare_lint macros>:1:3
  |
1 | ( $ vis : vis $ NAME : ident , $ Level : ident , $ desc : expr ) => (
  |   ^^^^^^^^^^^
  |
  = help: add #![feature(macro_vis_matcher)] to the crate attributes to enable

error: :vis fragment specifier is experimental and subject to change (see issue #41022)
 --> <declare_lint macros>:1:3
  |
1 | ( $ vis : vis $ NAME : ident , $ Level : ident , $ desc : expr ) => (
  |   ^^^^^^^^^^^
  |
  = help: add #![feature(macro_vis_matcher)] to the crate attributes to enable

error: aborting due to previous error

error: aborting due to previous error

error: Could not compile `clippy_lints`.
warning: build failed, waiting for other jobs to finish...
error: Could not compile `clippy_lints`.
warning: build failed, waiting for other jobs to finish...
error: build failed
This failure is expected (see `src/tools/toolstate.toml`)
Build completed successfully in 1:46:49

**Comment by Mark-Simulacrum** [comment]
Everything is actually fine, as you can see by the last two lines of the log. I hope to remove the error log if the failure is expected in the future, but not sure yet how best to do that.

```
This failure is expected (see src/tools/toolstate.toml)
Build completed successfully in 1:46:49
```

**Comment by follitude** [comment]
Is it related to [https://github.com/rust-lang-nursery/rust-clippy/issues/2192](url)?
