### ISSUE TITLE
Could not call emscripten_asm_const_int with the result of stringify

### ISSUE THREAD

**Issue by kryptan** [rust-lang/rust#45706]
I'm using Emscripten and trying to embed js. I declared Emscripten intrinsic `emscripten_asm_const_int`:

```Rust
extern "C" {
    fn emscripten_asm_const_int(code: *const u8, ...) -> i32;
}
```

And then tried to use it:

```Rust
emscripten_asm_const_int(concat!(stringify!(
    var aaaaaaaaaaaa = 0;
    aaaaaaaaaaaa = 0;
    aaaaaaaaaaaa = 0;
    aaaaaaaaaaaa = 0;
), '\0') as *const str as *const u8);
```

This fails to compile:

```
...
imdBool32x4": 0,"simdBool64x2": 0,"maxGlobalAlign": 8,"namedGlobals": {},"asmConsts": {"0": ["var aaaaaaaaaaaa = 0 ; aaaaaaaaaaaa = 0 ; aaaaaaaaaaaa = 0 ; aaaaaaaaaaaa = 0
          ;", ["i"]]}
          }

          Traceback (most recent call last):
            File "/home/user/.emsdk/emscripten/1.37.22/emcc", line 13, in <module>
              emcc.run()
            File "/home/user/.emsdk/emscripten/1.37.22/emcc.py", line 1540, in run
              final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
            File "/home/user/.emsdk/emscripten/1.37.22/tools/shared.py", line 2020, in emscripten
              call_emscripten(cmdline)
            File "/home/user/.emsdk/emscripten/1.37.22/emscripten.py", line 2246, in _main
              temp_files.run_and_clean(lambda: main(
            File "/home/user/.emsdk/emscripten/1.37.22/tools/tempfiles.py", line 78, in run_and_clean
              return func()
            File "/home/user/.emsdk/emscripten/1.37.22/emscripten.py", line 2251, in <lambda>
              DEBUG=DEBUG,
            File "/home/user/.emsdk/emscripten/1.37.22/emscripten.py", line 2151, in main
              temp_files=temp_files, DEBUG=DEBUG)
            File "/home/user/.emsdk/emscripten/1.37.22/emscripten.py", line 94, in emscript
              funcs, metadata, mem_init = parse_backend_output(backend_output, DEBUG)
            File "/home/user/.emsdk/emscripten/1.37.22/emscripten.py", line 150, in parse_backend_output
              raise e
          ValueError: Invalid control character at: line 22 column 460 (char 137022)
```

The issue here is that `stringify!` macro generates newlines and Emscripten doesn't seem to like newlines in this intrinsic. Not sure where it should be fixed, in Rust or Emscripten.

cc @alexcrichton @kripken

**Comment by kripken** [comment]
What does the LLVM IR look like? Could help figure this out.

(oddly in that python stack trace, it looks like most of the newlines were not a problem, except perhaps for one near the end, where it cuts off weirdly)

**Comment by kryptan** [comment]
[Here it is](https://gist.github.com/kryptan/b0b9c006791dadd1d8dba511f986b6b9)

There is a newline in the string:

    @str.0 = internal constant [80 x i8] c"var aaaaaaaaaaaa = 0 ; aaaaaaaaaaaa = 0 ; aaaaaaaaaaaa = 0 ; aaaaaaaaaaaa = 0\0A;\00"

**Comment by kripken** [comment]
That last newline is odd, especially since it's between the `0` and the `;`. Looks like something's going wrong in the rust=>ir stage, then.

For comparison, with this C++
````
#include <emscripten.h>
int main() {
  EM_ASM(
    var aaaaaaaaaaaa = 0;
    aaaaaaaaaaaa = 0;
    aaaaaaaaaaaa = 0;
    aaaaaaaaaaaa = 0;
  );
}
````
the string is
````
@.str = private unnamed_addr constant [76 x i8] c"var aaaaaaaaaaaa = 0; aaaaaaaaaaaa = 0; aaaaaaaaaaaa = 0; aaaaaaaaaaaa = 0;\00", align 1
````

**Comment by nagisa** [comment]
The newline is inserted by `stringify` so no line exceeds 80 symbols (provided there are no tokens longer than 80 symbols). I’m amused by the fact that the `stringify` uses the pretty printer (and therefore bothers to insert these newlines), but I would not consider it doing so a bug.

Rather, you should not use `stringify!` for javascript code, because this macro first interprets the string as Rust tokens, which is not likely to be correct for javascript code. Consider using the `include_bytes!` macro and putting javascript code into a separate file instead.

**Comment by alexcrichton** [comment]
A pretty huge amount has changed since this was first opened, so I'm going to close this as "pretty likely stale". If it reproduces still though feel free to reopen!
