### ISSUE TITLE
Tracking issue for `slice::from_ref` and `slice::from_ref_mut`

### ISSUE THREAD

**Issue by whitequark** [rust-lang/rust#45703]
Tracking issue for feature `from_ref`

```rust
// std::slice
pub fn from_ref<T>(s: &T) -> &[T];
pub fn from_ref_mut<T>(s: &mut T) -> &mut [T];
```

  * Implemented in https://github.com/rust-lang/rust/pull/45306

**Comment by SimonSapin** [comment]
For archeology purpose: these were added to the standard library in 2014 419ac4a1b899ba88fb360b4c71c08f3610564cd4, then deprecated and moved to crates.io in 2015: https://github.com/rust-lang/rust/issues/27774.

Now that we’ve decided to bring them back and are going through the process motions, can we start FCP to stabilize? CC @rust-lang/libs

**Comment by dtolnay** [comment]
Is there anything else in the standard library that uses "ref_mut" to refer to `&mut T`? In [RFC 199](https://github.com/rust-lang/rfcs/blob/master/text/0199-ownership-variants.md#why-mut-rather-then-mut_ref) we went the opposite way.

Is it intended to be understood as (from\_ref)\_mut or from\_(ref\_mut)?

`slice::from_mut` wouldn't seem accurate to me but is there a different naming that works better with `_ref` and `_mut` suffixes?

**Comment by whitequark** [comment]
> Is it intended to be understood as (from_ref)_mut or from_(ref_mut)?

The latter. I think `slice::from_mut` is better here, too. I did not realize this in my initial PR.

**Comment by steveklabnik** [comment]
I had left a brief comment in the original PR, but I didn't see anyone reply: my crate has two extra `Option` based versions as well, I don't know if we want to pull them in, or if my crate will still have some small use for those variants.

**Comment by SimonSapin** [comment]
`opt_slice(x)` can be written as `x.as_ref().map(ref_slice)` which does not use `unsafe` (and is fairly standard `Option` manipulation code). So I think the need to include it is less pressing.

**Comment by whitequark** [comment]
@steveklabnik I replied to you: https://github.com/rust-lang/rust/pull/45306#issuecomment-340523116

**Comment by steveklabnik** [comment]
Gah! Thanks both! Seems great, I must have missed them in all the
notifications <3

**Comment by SimonSapin** [comment]
Looks good to me to stabilize.

@rfcbot fcp merge

**Comment by dtolnay** [comment]
Given that we have [`Option::get_ref`](https://doc.rust-lang.org/std/option/enum.Option.html#method.as_ref) and [`Option::get_mut`](https://doc.rust-lang.org/std/option/enum.Option.html#method.as_mut) which is not called `get_ref_mut`, I think here it should be `from_ref` and `from_mut` rather than `from_ref_mut`.

**Comment by SimonSapin** [comment]
Makes sense. Let’s say stabilize with that change.

**Comment by stjepang** [comment]
Just one more last-minute question before stabilization: Why does `slice::from_ref` return a `&[T]`?

Wouldn't it be more useful to return a `&[T; 1]`, which can be coerced into `&[T]`?
Are we going to add such a function later as `array::from_ref`?

**Comment by Kimundi** [comment]
I could image that implementing this with `From` impls might have negative inference or derfer-coercion effects, since passing a `&Vec<T>` for example might end in a `&[Vec<T>]` instead of a `&[T]`

**Comment by SimonSapin** [comment]
Right, adding another for `x.into()` for every `x: &T` would probably make inference impractical.
