### ISSUE TITLE
rustdoctest: `--nocapture` still hides the output for successful tests

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/rust#45724]
![image](https://user-images.githubusercontent.com/5217170/32335922-f1932244-bfbb-11e7-9fa2-cc3c4981c12f.png)

This is from my crate `synchronoise`. In this case, `tests::signal_doctest` and the doctest for `SignalEvent` are the same code - i needed to copy the doctest into a regular unit test to see the output.

**Comment by woshilapin** [comment]
Looks like a duplicate of #26309.
