### ISSUE TITLE
Rustdoc: Hide trait impl fn:s on pressing + for types

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#45720]
When pressing the `+` hotkey on type's documentation such as on the [documentation of Option<T>](https://doc.rust-lang.org/nightly/std/option/enum.Option.html), the methods of the `impl` are still shown. This is however mostly useless information that gets in the way of scrolling to see what traits a type implements.

It would be more ergonomic if `+` would hide every method of every trait `impl` but still show all associated items (types and consts) for each `impl` (since they carry useful information).

In addition, a `[+]`/`[-]` link should be added on all the `impl`s (including non-trait impls) either besides `[src]` or to the left of the `impl` (as done with `fn`s this expands and collapses the impls but keeps associated items shown.

**Comment by Centril** [comment]
I can rewrite this as an RFC if required, but I was unsure about the protocol wrt. rustdoc.

**Comment by pornel** [comment]
Similar request: https://github.com/rust-lang/rust/issues/40363

**Comment by Centril** [comment]
Closing as resolved.
