### ISSUE TITLE
Too big array size wraps around; expected error

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#45745]
The following compiles on 64-bit usize platforms, albeit with a warning:

It compiles because it ends up with `[u8; 0]` implementing `Foo`.

```rust
trait Foo { }

impl Foo for [u8; 0x1_0000_0000_0000_0000] { }

fn main() {
    let _b = Box::new([]) as Box<Foo>;
}
```

The warning is right:

```
warning: literal out of range for usize
```

Rustc should consider making this a hard error.

Rust version: rustc 1.23.0-nightly (e340996ff 2017-11-02)

**Comment by bluss** [comment]
cc @oli-obk

**Comment by oli-obk** [comment]
We could simply upgrade it to `deny`-by-default. I don't think anyone is seriously `allow`ing that lint.

**Comment by bluss** [comment]
I'd agree if it was restricted to array sizes and equivalent.

**Comment by rylev** [comment]
This is now an error due to literals overflowing is now deny-by-default. Of course, if users turn that to allow, they will run into this issue.

**Comment by oli-obk** [comment]
Yea I don't think we can take further actions here
