### ISSUE TITLE
rustdoctest: no `allow` lints are put in doctests, contradicting Rustdoc Book

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/rust#45750]
![image](https://user-images.githubusercontent.com/5217170/32396309-a4e44584-c0b2-11e7-9ecd-58f3d493172a.png)

In [the current Rustdoc Book](https://doc.rust-lang.org/nightly/rustdoc/documentation-tests.html#pre-processing-examples), it mentions that a few lints are automatically `allow`ed in doctests:

> Some common `allow` attributes are inserted, including `unused_variables`, `unused_assignments`, `unused_mut`, `unused_attributes`, and `dead_code`. Small examples often trigger these lints.

However, as the image above demonstrates, this does not seem to be the case. I have not added any `#![doc(test(attr(warn(unused))))]` or similar attributes to my crate, which would override such behavior. These warnings are usually suppressed, but adding `--nocapture` when running tests shows these warnings. (It also shows more important warnings, like `unused_must_use`, which helped in a different library of mine.)

@rust-lang/docs @rust-lang/dev-tools - Is this a docs issue (which would mean removing this entry from the Rustdoc Book) or a rustdoc issue (which would mean making sure these items are added)?

**Comment by GuillaumeGomez** [comment]
I think it should be added into rustdoc instead (but I was sure it was already...).

**Comment by QuietMisdreavus** [comment]
I've opened https://github.com/rust-lang/rust/pull/45764 to add a blanket `#![allow(unused)]` when a crate doesn't specify any attributes via `#![doc(test(attr(...)))]`. I also opened https://github.com/rust-lang/rust/pull/45767 to document `#![doc(test(attr(...)))]` itself.
