### ISSUE TITLE
newtype_index macro `DEBUG_FORMAT = custom` not working

### ISSUE THREAD

**Issue by spastorino** [rust-lang/rust#45763]
I'm trying to change `DefIndex` to be defined using newtype_index and calling newtype_index macro this way ...

```rust
newtype_index!(DefIndex
    {
        DEBUG_FORMAT = custom

        const DEF_INDEX_HI_START = 1 << 31,

        const CRATE_DEF_INDEX = 0,
    });
```

Does not work.

/cc @Nashenas88 @nikomatsakis

**Comment by durka** [comment]
Are you just missing a comma after the `DEBUG_FORMAT` line? It seems to be expected: https://github.com/rust-lang/rust/blob/98e4b6845f111d297fa2bff759b6f15855280161/src/librustc_data_structures/indexed_vec.rs#L289-L296

**Comment by spastorino** [comment]
Yeah I wasn't paying a lot of attention to the macro definition, anyway ... with comma ...

```
error: format argument must be a string literal.
  --> src/librustc/hir/def_id.rs:91:24
   |
91 |         DEBUG_FORMAT = custom,
   |                        ^^^^^^
```

With comma and making custom a string ....

```
error: argument never used
  --> src/librustc/hir/def_id.rs:89:1
   |
89 | / newtype_index!(DefIndex
90 | |     {
91 | |         DEBUG_FORMAT = "custom",
92 | |
...  |
95 | |         const CRATE_DEF_INDEX = 0,
96 | |     });
   | |_______^
```

**Comment by spastorino** [comment]
So ... or either I don't understand how to use the macro or there's a bug somewhere.

**Comment by durka** [comment]
Yes, I think there is a bug. There is a base case for custom debug format (https://github.com/rust-lang/rust/blob/98e4b6845f111d297fa2bff759b6f15855280161/src/librustc_data_structures/indexed_vec.rs#L93-L97) but no rule for parsing that from the macro input.

**Comment by spastorino** [comment]
@durka, actually after checking, the case you mentioned is not the right match arm.

We should be going through https://github.com/rust-lang/rust/blob/98e4b684/src/librustc_data_structures/indexed_vec.rs#L93-L97

**Comment by durka** [comment]
Yeah that is the one I linked. But that's the end of the macro, there needs to be another parsing rule that eats `DEBUG_FORMAT = custom,`.

**Comment by spastorino** [comment]
@durka exactly!

**Comment by durka** [comment]
OK, I figured out what the issue is. [Parsing `DEBUG_FORMAT = custom`](https://github.com/rust-lang/rust/blob/98e4b6845f111d297fa2bff759b6f15855280161/src/librustc_data_structures/indexed_vec.rs#L295) is actually fine since `custom` is a valid `expr`. However once you've parsed something into an `expr` you can't "look inside" it again -- matching it against the ident `custom` on line 97 doesn't work.

What needs to be done I believe is changing `$debug_format:expr` to `$debug_format:tt` everywhere in the macro. This should still work as a string literal is a single token, and it will preserve `custom` as a token that can be matched again.

**Comment by spastorino** [comment]
After doing what you've said I'm getting ...

```
error: no rules expected the token `derives`
  --> src/librustc/hir/def_id.rs:89:1
   |
89 | / newtype_index!(DefIndex
90 | |     {
91 | |         DEBUG_FORMAT custom
92 | |
...  |
98 | |         const CRATE_DEF_INDEX = 0,
99 | |     });
   | |_______^
   |
   = note: this error originates in a macro outside of the current crate

error: duplicated bind name: debug_format
  --> <newtype_index macros>:98:18
   |
98 | ] DEBUG_FORMAT = $ debug_format : tt , $ ( $ tokens : tt ) * ) => (
   |                  ^^^^^^^^^^^^^^^^^^^
```

**Comment by spastorino** [comment]
After changing what you've said I'm getting ...

```
error: no rules expected the token `derives`
  --> src/librustc/hir/def_id.rs:89:1
   |
89 | / newtype_index!(DefIndex
90 | |     {
91 | |         DEBUG_FORMAT custom
92 | |
...  |
98 | |         const CRATE_DEF_INDEX = 0,
99 | |     });
   | |_______^
   |
   = note: this error originates in a macro outside of the current crate

error: aborting due to previous error

error: Could not compile `rustc`.
```

**Comment by durka** [comment]
Now you have `DEBUG_FORMAT custom` instead of `DEBUG_FORMAT = custom,`? Or the error output is just mangling your source? I can take a look at your branch directly if you want.

**Comment by spastorino** [comment]
Hey @durka, thanks, I think it's working now. I'm testing it and will open a PR if everything is OK. Thanks for the tips, at some point I'd need to read at least something about macros ;).
