### ISSUE TITLE
`rustc --test` produces size zero `dSYM` image on macOS

### ISSUE THREAD

**Issue by JohnColanduoni** [rust-lang/rust#45768]
Running `rustc --test -g main.rs` with any of the following in `main.rs` on macOS:

```
#[test]
fn test_1() {
    assert!(false);
}
```

```
fn main() {
}
```

```
// Empty
```

Produces a `main.dSYM` containing an empty file at `main.dSYM/Contents/Resources/DWARF/main`. A bug in Rust's libbacktrace (courtesy of myself) causes any attempt to take a backtrace while such a `dSYM` file is present in the same directory as the executable (even if it is not produced from that executable) to die of `SIGBUS`. Even without that, this prevents both panic backtraces and debugging from taking advantage of debug data with executables containing test harnesses on macOS. As @alexcrichton [determined](https://github.com/rust-lang/rust/issues/45731#issuecomment-341903516), this is a regression in the range https://github.com/rust-lang/rust/compare/4279e2b4c...8493813cd and likely related to https://github.com/rust-lang/rust/issues/45511.

cc @alexcrichton @kennytm

**Comment by alexcrichton** [comment]
Hmm... An empty file sound suspiciously not like an LLVM bug. I believe we run, after the fact, `dsymutil` when linking is complete. I wonder if that program is generating an error which rustc is squelching by accident? Mind seeing if `dsymutil` is aborting and/or dying?

**Comment by Xudong-Huang** [comment]
I saw a lot of llvm-dsymutil core dumps during runing `cargo test`
my system info

```sh
$ cd ~/Library/Logs/DiagnosticReports
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1036

$ clang --version
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$ rustup show
Default host: x86_64-apple-darwin

installed toolchains
--------------------

stable-x86_64-apple-darwin
nightly-x86_64-apple-darwin (default)

active toolchain
----------------

nightly-x86_64-apple-darwin (default)
rustc 1.23.0-nightly (bd0e45a32 2017-11-06)

$ rustc --version
rustc 1.23.0-nightly (bd0e45a32 2017-11-06)

$ ll
total 112
-rw-------@ 1 huangxudong  staff    27K Nov  8 15:36 llvm-dsymutil_2017-11-08-153625_huangxudongs-Mac-Book-Pro.crash
-rw-------@ 1 huangxudong  staff    27K Nov  8 15:36 llvm-dsymutil_2017-11-08-153627_huangxudongs-Mac-Book-Pro.crash
```

**Comment by JohnColanduoni** [comment]
This is no longer happening for me on current master (https://github.com/rust-lang/rust/commit/e177df3d5c4a5a9432f33f54ee459ea25bf7f2d2).

**Comment by nikomatsakis** [comment]
triage: P-high

Do we believe this is fixed?

**Comment by nikomatsakis** [comment]
Assigning to @alexcrichton since probably related to ThinLTO.

**Comment by alexcrichton** [comment]
I've posted a fix for this as https://github.com/rust-lang/rust/pull/45908, we can reenable ThinLTO when https://github.com/rust-lang/rust/issues/45511 is fixed
