### ISSUE TITLE
Map::from_iter doesn't allow initialization from iter

### ISSUE THREAD

**Issue by Yanpas** [rust-lang/rust#45786]
This code is valid:
```
let vals2 = [1,2,3];
let foo2 = BTreeSet::from_iter(vals2.iter());
```
And this is not:
```
let vals = [('a', 4), ('b', 5)];
let foo = BTreeMap::from_iter(vals.iter());
```

> error[E0271]: type mismatch resolving `<std::slice::Iter<'_, (char, {integer})> as std::iter::IntoIterator>::Item == (_, _)`

BTreeMap for some reason requires iteration over `T`, not `&T`. I guess initialization of any dictionary-like structure from list of tuples is essential, but currently it is possible only with dynamically allocated Vec

Same applies to HashMap

**Comment by sfackler** [comment]
```rust
let vals = [('a', 4), ('b', 5)];
let foo = BTreeMap::from_iter(vals.iter().cloned());
```

**Comment by Yanpas** [comment]
Oh, thanks for suggestion!

Correct option will be: `BTreeMap::<char, i32>::from_iter(vals.iter().cloned());` since rustc fails to infer type in this case.

Still, is there any reason for map iterator to behave different from other collections?

**Comment by sfackler** [comment]
What is the difference here? If you collect an `Iterator<Item = &T>` into a `Vec`, you get a `Vec<&T>`. If you collect an `Iterator<Item = (&T, &V)>` into a `BTreeMap`, you get a `BTreeMap<&T, &V>`.

**Comment by Yanpas** [comment]
Only now I've noticed that I was getting collections of references, not values... So .cloned is "must have" for other collections too. I guess the issue is resolved.
