### ISSUE TITLE
`sh.rustup.rs` fails to install rust 1.21.0

### ISSUE THREAD

**Issue by vkatsikaros** [rust-lang/rust#45780]
According to the current https://www.rust-lang.org/en-US/install.html, Rust 1.21.0 is the latest version. I follow the instructions to install rust, but I can't make it install the latest version
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
```
Steps to reproduce
```
$ rustc --version
rustc 1.20.0 (f3d6973f4 2017-08-27)

$ sudo curl https://sh.rustup.rs -sSf | sh
[sudo] password for vag: 
info: downloading installer

Welcome to Rust!

This will download and install the official compiler for the Rust programming 
language, and its package manager, Cargo.

It will add the cargo, rustc, rustup and other commands to Cargo's bin 
directory, located at:

  /home/vag/.cargo/bin

This path will then be added to your PATH environment variable by modifying the
profile file located at:

  /home/vag/.profile

You can uninstall at any time with rustup self uninstall and these changes will
be reverted.

Current installation options:

   default host triple: x86_64-unknown-linux-gnu
     default toolchain: stable
  modify PATH variable: yes

1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
1

info: updating existing rustup installation


Rust is installed now. Great!

To get started you need Cargo's bin directory ($HOME/.cargo/bin) in your PATH 
environment variable. Next time you log in this will be done automatically.

To configure your current shell run source $HOME/.cargo/env

$ ~/.cargo/bin/rustc --version
rustc 1.20.0 (f3d6973f4 2017-08-27)
```
In the end I still see rustc 1.20.0 installed, but I would expect 1.21.0 to be installed.

**Comment by kennytm** [comment]
> ```
> $ sudo curl https://sh.rustup.rs -sSf | sh
> ```


Try to remove the `sudo`.

**Comment by vkatsikaros** [comment]
@kennytm I tried without sudo but the result is the same :( However, the `rustup update` you suggested worked fine!

Let me know if I can provide any other info, otherwise feel free to close the issue

**Comment by kennytm** [comment]
Thanks for the info :)

I guess `rustup` sees you have already installed `rustup` before and so doesn't override anything. If you think reinstalling `rustup` should update, you may file an issue to https://github.com/rust-lang-nursery/rustup.rs/issues.

(Closing, as problem is solved and it is a rustup issue not a rustc issue.)
