### ISSUE TITLE
[rustdoc] Improve "Types/modules" label on the search results page

### ISSUE THREAD

**Issue by Seeker14491** [rust-lang/rust#45787]
The first tab on the search results page is labeled "Types/modules", but the search results include items which are neither, such as functions and macros:

![results for file](https://user-images.githubusercontent.com/6490497/32418337-72ae7b12-c22d-11e7-8362-4538ba86f6a0.PNG)

I suggest changing the label to something like "In name".

**Comment by JRegimbal** [comment]
Maybe "As name" would be better to just match the other tabs?

**Comment by Seeker14491** [comment]
The "As parameters" and "As return value" tabs only return results that match the whole search text exactly, while the first tab also returns items that partially match the search text. Because of this distinction, I prefer "in" over "as".

**Comment by JRegimbal** [comment]
Ah my bad I didn't understand the difference between the name search and the parameter/return value searches.

**Comment by QuietMisdreavus** [comment]
Fixed in https://github.com/rust-lang/rust/pull/45898
