### ISSUE TITLE
[resolve] use rename suggestion is not well-formatted

### ISSUE THREAD

**Issue by behnam** [rust-lang/rust#45799]
https://github.com/rust-lang/rust/blob/44990e5b14fc7901071b26aa98b281675459176e/src/librustc_resolve/lib.rs#L3703-L3706

Trying to re-import `std` or any other crate, I get a suggestion like this:

```rust
14 | extern crate std;
   | ^^^^^^^^^^^^^^^^^ `std` reimported here
   |
   = note: `std` must be defined only once in the type namespace of this module
help: You can use `as` to change the binding name of the import
   |
14 | extern crate std; as Otherstd
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The problem is in the formatting of the suggestion, where SEMICOLON (`;`) is placed before the `as` keyword, like this `extern crate std; as Otherstd` instead of `extern crate std as Otherstd;`.

The suggestion doesn't exist in stable or beta, so this affects only nightly at the moment.

Original commit: https://github.com/rust-lang/rust/commit/ff832405d07d6c34ee060e26acf0aa6143b79d3f
Original PR: https://github.com/rust-lang/rust/pull/45660

/cc @Cldfire

**Comment by behnam** [comment]
Looks like the feature works fine for `use` statements, but has this bug for `extern crate` ones. Maybe worth adding a test case for `extern crate`, too.

**Comment by Cldfire** [comment]
Whoops! Thanks for noticing that.

I should be able to look into fixing this tonight (~12 hours from now) or tomorrow.

**Comment by estebank** [comment]
@cldfire what I would do is change the `binding.span` for `extern crate` statements to not include the semicolon. To do so, it is probably enough to modify `parse_item_extern_crate` in `libsyntax/parse/parser.rs` to take the `self.prev_span` before parsing the semicolon. That change would probably affect other ui tests as it would change underlines involving `extern crate` statements, and you should check if there're any regressions doing that change.

**Comment by Cldfire** [comment]
Gotcha, thanks for the advice.
