### ISSUE TITLE
[rustdoc] Some left panel links don't work on search results page

### ISSUE THREAD

**Issue by Seeker14491** [rust-lang/rust#45790]
It's the first set of links that don't work; the ones that jump to specific items on the current page:

![search sidebar](https://user-images.githubusercontent.com/6490497/32418584-5ae5fd48-c232-11e7-8b7f-bb0e5410284f.PNG)

Clicking on them seems to just repeat the search.

cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
I think it's search related. Investigating when I have time.
