### ISSUE TITLE
Docs for Macro `core::write` are not applicable to no_std

### ISSUE THREAD

**Issue by behnam** [rust-lang/rust#45797]
Stable: https://doc.rust-lang.org/core/macro.write.html
Nightly: https://doc.rust-lang.org/nightly/core/macro.write.html

Looks like the docs are shared between `core` and `std`, because of the implementation details. But, the problem is that the examples provided for the `core` macro won't be working in `no_std` setup.

I think it's better to either add a note about this or have accurate docs that would actually work. I can't think of a quick fix, though. Any ideas?

**Comment by steveklabnik** [comment]
The only way is to write a note about the different context.

**Comment by jdhorwitz** [comment]
@steveklabnik I can take this one and work on this.

**Comment by steveklabnik** [comment]
Great! Let me know if you need anything :)

**Comment by steveklabnik** [comment]
@jdhorwitz did you ever do this? No worries if not, but If so, I'd like to close it, and if not, we should get someone else to do it, unless you're still willing :)

**Comment by MagnumOpus21** [comment]
If no one's looking at this currenty, I can contribute to this 😁 . Just need a few pointers on what needs to be accomplished.

**Comment by steveklabnik** [comment]
@MagnumOpus21 that'd be great! The docs live here: https://github.com/rust-lang/rust/blob/3b7720399a9006d9d7b89c251fa37ead46f9db7a/src/libcore/macros.rs#L309-L351

The docs need to have a note added to mention that this can be used without the standard library, and an example showing that usage. That's the high level overview, if you need more help than that, I'm happy to elaborate further!

**Comment by MagnumOpus21** [comment]
Awesome will get started @steveklabnik .

**Comment by MagnumOpus21** [comment]
The core crate doesn't support vector at all, so if I have to make it support a mutable string reference should I write a trait for `&str`? Or is there a simple way to show case the working of `write!` from the `core` crate?

**Comment by MagnumOpus21** [comment]
When I try to use the `write!` macro, I get two consistent errors, 
`error: language item required, but not found: panic_fmt`
`error: language item required, but not found: eh_personality`.
I've am stumped here 😞

**Comment by MagnumOpus21** [comment]
@steveklabnik When I run `./x.py test src/libcore/macros.rs` it fails, even before the addition of my changes to the macros file. Is it ok to open a PR with that? I can add the error message here if you insist.
