### ISSUE TITLE
`Error::description` could use a better example

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#45793]
The current example only shows how to call `description()` - pretty useless, since calling a method isn't exactly rocket science.
A better example would show how to actually *implement* this method in a common case like when you have a library that's defining its own error type (possibly wrapping another error, like `std::io::Error`, since this happens in almost all libraries). I am not sure what the conventions for such an impl actually *are* (should it forward the `.description()` call to the contained error or just describe the kind of error that occurred ("I/O error")?) so I'm opening this issue.

**Comment by kennytm** [comment]
See #45249, #44842.

**Comment by jonas-schievink** [comment]
Yeah that basically sums this issue up, too. Closing as a duplicate.
