### ISSUE TITLE
Link error with incremental and impl trait

### ISSUE THREAD

**Issue by MaikKlein** [rust-lang/rust#45800]
I was able to reproduce the link error reliably on my machine.

https://github.com/MaikKlein/spire-lang/tree/e0ca3221776f0ce35c1b49f7fdef413512efc656

`CARGO_INCREMENTAL=1 cargo build --release`

Then go and change this [line](https://github.com/MaikKlein/spire-lang/blob/e0ca3221776f0ce35c1b49f7fdef413512efc656/src/lib.rs#L100) from

`many(ast_object.or(ast_data).skip(whitespace()))`

to

`many(ast_object.or(ast_data))`

And do another `CARGO_INCREMENTAL=1 cargo build --release`

[error gist](https://gist.github.com/MaikKlein/40058b5a98ef3821002a1f15c5f21bef)

Os: Ubuntu 16.04 x64

```
rustc 1.23.0-nightly (3b82e4c74 2017-11-05)
binary: rustc
commit-hash: 3b82e4c74d43fc1273244532c3a90bf9912061cf
commit-date: 2017-11-05
host: x86_64-unknown-linux-gnu
release: 1.23.0-nightly
LLVM version: 4.0
```

**Comment by MaikKlein** [comment]
cc @michaelwoerister

**Comment by michaelwoerister** [comment]
Thanks for the bug report, @MaikKlein!

Does this also occur when you compile the code non-incrementally but with `-Ccodegen-units=9999`?

**Comment by MaikKlein** [comment]
@michaelwoerister Yes this also happens with `-Ccodegen-units=9999`.

**Comment by michaelwoerister** [comment]
Thanks! Might be another hole in the reachability pass. cc @eddyb

**Comment by MaikKlein** [comment]
@michaelwoerister I just tested it again with 

```
rustc 1.24.0-nightly (7eb64b86c 2017-12-20)
binary: rustc
commit-hash: 7eb64b86ce44cc1828dd176a8b981e37ea08fc38
commit-date: 2017-12-20
host: x86_64-unknown-linux-gnu
release: 1.24.0-nightly
LLVM version: 4.0
```

And I can't reproduce it anymore. It seems to be fixed.

**Comment by michaelwoerister** [comment]
Thanks for checking back, @MaikKlein! I'll close for now. Feel free to open another issue if the problem re-appears.
