### ISSUE TITLE
missing 'retq` instruction in opt-level=2 codegen with a certain unsafe+transmute usage

### ISSUE THREAD

**Issue by da-x** [rust-lang/rust#45823]
While converting null const pointers to static references seems to work in debug builds, under an optimization build there is some odd codegen taking place.

(Yes, I know about `unsafe` casts and `std::ptr::null()`, but I am worried that this issue is indicative for an actual bug)

Consider this program:

```rust
fn main()
{
    unsafe { ::std::mem::transmute::<_, &'static usize>(0 as *const usize) };
}
```

Compile with:
```sh
rustc  test.rs --emit asm -C opt-level=2
```

There supposed to be a `retq` instruction just before the first `.cfi_endproc`:

```gasm
        .text
        .file   "a.cgu-0.rs"
        .section        .text._ZN1a4main17h02c39649d43f7637E,"ax",@progbits
        .p2align        4, 0x90
        .type   _ZN1a4main17h02c39649d43f7637E,@function
_ZN1a4main17h02c39649d43f7637E:
        .cfi_startproc
.Lfunc_end0:
        .size   _ZN1a4main17h02c39649d43f7637E, .Lfunc_end0-_ZN1a4main17h02c39649d43f7637E
        .cfi_endproc

        .section        .text.main,"ax",@progbits
        .globl  main
        .p2align        4, 0x90
        .type   main,@function
main:
        .cfi_startproc
        movq    %rsi, %rax
        movq    %rdi, %rcx
        leaq    _ZN1a4main17h02c39649d43f7637E(%rip), %rdi
        movq    %rcx, %rsi
        movq    %rax, %rdx
        jmp     _ZN3std2rt10lang_start17hdcba96cc6d0f043dE@PLT
.Lfunc_end1:
        .size   main, .Lfunc_end1-main
        .cfi_endproc

        .section        ".note.GNU-stack","",@progbits
```

With that `retq` missing, the execution of the actual main function `_ZN1a4main17h02c39649d43f7637E` (which was optimized to nothing in this case) overflows and the rust run-time is being initialized for the second time, tripping over a borrow, unsurprisingly:

```
thread 'main' panicked at 'assertion failed: c.borrow().is_none()', /checkout/src/libstd/sys_common/thread_info.rs:46:25
```

Problem reproduces with `stable` and `nightly`.

**Comment by arielb1** [comment]
@da-x 

Your code creates a null reference, which is undefined behavior (even if you don't dereference it). Therefore, the compiler can compile it to whatever it wants.
