### ISSUE TITLE
Rustdoc: Add "-" shortcut that does same as "+"

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#45847]
"+" on rustdoc expands or collapses all sections on the page. It'd be nice if "-" does too. At least on US keywords, it requires a shift for "+" but not for "-".

**Comment by GuillaumeGomez** [comment]
Ok, here you go.

**Comment by raggi** [comment]
I'd also like a way to make this sticky (e.g. ctrl+- -> writes a local storage / cookie that persists the state)

**Comment by GuillaumeGomez** [comment]
Not sure to understand what you're asking.

**Comment by raggi** [comment]
I'm asking that I can press: `CTRL -` and then load a new doc page, and the page will load collapsed. If I press `-` or `+` it will toggle the collapse state. If I press `CTRL -` or `CTRL +` it will toggle the *persistent* state.

**Comment by GuillaumeGomez** [comment]
I see. Hum... Do you mind opening another issue for this please? I think it'll require a bit of discussion before that (because `ctrl +` / `ctrl -` are also used to zoom in/out in a browser).
