### ISSUE TITLE
Tracking issue for Option::filter (feature `option_filter`)

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#45860]
This is a tracking issue for `Option::filter`.

- Proposed in https://github.com/rust-lang/rfcs/issues/1485
- RFC written in https://github.com/rust-lang/rfcs/pull/2124
- Initial implementation in #44996 (not merged)
- Resubmitted in #45863

Unresolved questions: 

- [ ] decide on name (`filter` vs `and_if` vs …)

**Comment by LukasKalbertodt** [comment]
@dtolnay Could you add a task "decide on the name (`filter()` vs. `and_then()` vs. ???)" to your comment? Also: the PR is ready now.

**Comment by kennytm** [comment]
@LukasKalbertodt @dtolnay Updated.

**Comment by dtolnay** [comment]
I think `and_if` is a brilliant name. Really great idea and strong contender. At this point I would still lean toward `filter`.

I find that the `and`/`or` methods on Option make perfect sense and the names reflect what the method does, but it still takes me multiple seconds when I see something like `or_else` or `map_or` to reverse engineer what that means in terms of argument types and return types and pattern matching and behavior of my code.

In contrast, `filter` is strongly immediately associated with taking a filter function `&T -> bool` and using it to decide whether to keep the values in self. A short name with that sort of immediate strong association was not available for the things the `and`/`or` family of methods do, or they would have been called something different.

**Comment by nvzqz** [comment]
As I mentioned in #45863, I have a question regarding the signature of this method:

Wouldn't this method be more flexible if the `FnOnce` took `&mut T`?

My suggested change would differ from `Vec::retain`, which this method acts similarly to (except not in-place). Perhaps it would be worth considering changing the signature of `Vec::retain` too?

I understand that this method is essentially shorthand for `option.iter().filter(predicate).next()`. My suggested change would be equivalent to `option.iter_mut().filter(predicate).next()`.

**Comment by netvl** [comment]
+1 for `filter()` - this also has precedents in other languages:
* [Java: `Optional.filter()`](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html#filter-java.util.function.Predicate-)
* [Scala: `Option.filter()`](http://www.scala-lang.org/api/current/scala/Option.html#filter(p:A=%3EBoolean):Option[A])
* [Haskell: `mfilter`](https://stackoverflow.com/a/45329288/788207) (a more generic function defined for the `MonadPlus` type class, but the name is still `filter`-based)

**Comment by LukasKalbertodt** [comment]
@nvzqz Do you have a specific use case in mind? Yes, the method would be more flexible with `FnOnce(&mut T) -> bool` as predicate, but we don't necessarily want this flexibility. Simple example: Rust variables are immutable by default in order to limit what you can do -- more flexibility/possibilities are not *always* a good thing.

So without good use case in mind, I would keep the signature as is: I don't think anyone would expect a *predicate* of a method called `filter()` to change the inner value.

**Comment by LukasKalbertodt** [comment]
About the name: please note that the RFC thread already contains quite a few arguments for and against certain names. I'll try to summarize the most important points here:

---

The two competing names are `filter` and `and_if`. One [comment](https://github.com/rust-lang/rfcs/pull/2124#issuecomment-338526115) on their differences:

> In other words, `.and_if` describes how it does X, `.filter` describes what X is. This is the distinction between imperative and declarative programming where the `.filter` is declarative.

Comparing the two:

<table>
  <thead>
    <tr><th></th><th width="35%">Advantages</th><th>Disadvantages</th></tr>
  </thead>
  <tbody>
    <tr>
<td><code>filter</code></td>
<td><ul>
  <li>Same as in most other languages</li>
  <li>Same as in <code>Iterator</code></li>
</ul></td>
<td><ul>
  <li><a href="https://github.com/rust-lang/rfcs/pull/2124#issuecomment-325047426">Makes you expect <code>filter_map</code> on <code>Option</code></a></li>
  <li><a href="https://github.com/rust-lang/rfcs/pull/2124#issuecomment-338728805">Possible confusion about filter-in vs. filter-out</a> (although in other languages, it's pretty much always filter-in)</li>
</ul></td>
</tr>
    <tr>
<td><code>and_if</code></td>
<td><ul>
  <li>Fits other methods of <code>Option</code> more closely</li>
  <li>More descriptive in the context of control flow</li>
</ul></td>
<td><ul>
  <li>Name is not well known in the FP world</li>
  <li><a href="https://github.com/rust-lang/rfcs/pull/2124#issuecomment-338526115">Less descriptive in the context of data flow</a></li>
  <li><a href="https://github.com/rust-lang/rust/issues/45860#issuecomment-342892016">Signature not immediately clear from the name</a></li> 
</ul></td>
</tr>
</tbody>
</table>


---

How this method is called in other languages:


- Haskell: [`mfilter`](https://hackage.haskell.org/package/base-4.10.0.0/docs/Control-Monad.html#v:mfilter)
- Scala: [`filter`](http://www.scala-lang.org/api/2.7.0/scala/Option.html#filter%28%28A%29%3D%3EBoolean%29)
- C++17: *no such method* (right?)
- `boost::optional`: *no such method* (right?)
- Idris: *no such method* (right?)
- Nim: [`filter`](https://nim-lang.org/docs/options.html#filter)
- Java8: [`filter`](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html#filter-java.util.function.Predicate-)
- Swift: *no such method* (right?)
- Python: `filter` ([kind of](https://github.com/rust-lang/rfcs/pull/2124#issuecomment-338757730))

**Comment by KodrAus** [comment]
It looks like we're still in the bikeshedding phase here, so just leaving a note to say I found my way here after typing `.filter` automatically and discovering the method exists and is unstable :)

**Comment by bb010g** [comment]
@LukasKalbertodt `FnOnce(&mut T) -> bool` would be useful when dealing with data structures that cache by mutating themselves on otherwise normal accessors. (Although you could cover this in some cases with a `Cell`.)

**Comment by LukasKalbertodt** [comment]
@bb010g Good point. However, I think I still tend to keep the closure as it is right now. A few reasons:

- The closure of `Iterator::filter` also takes immutable references. I guess your argument would also apply to that function, but for for the sake of consistency I'd use the same signature for `Option::filter`.
- Maybe a data structure as you proposed it should really use cells inside such that its API reflects the *logical* mutability-properties?
- I can't quite imagine that one would call `filter` on an `Option<DataStructure>` directly: if the closure returns `false`, we throw away the entire data structure.

However, I'm not quite sure and don't have a very strong opinion on this decision.

**Comment by bb010g** [comment]
You'd probably want `filter_mut` for consistency with `Iterator`. You can't always use `Cell` due to the `Copy` constraint. As for dropping the structure, this may be desirable when working with types like `Arc` a lot in a concurrent environment.

**Comment by LukasKalbertodt** [comment]
So I guess we keep this issue just for `filter`. Adding `filter_mut` or something similar can then be proposed via another RFC, I'd say.

Then there's only the naming issue left. Here again, I don't have a strong opinion. I like both names a lot and would be happy either way.

**Comment by Emerentius** [comment]
There are not very many `and_*` functions. It's only `and` and `and_then` and one of those was a poor choice. `and` is fitting in the logical sense of the word. `and_then` loses that meaning and is purely temporal. It could have just as well been used for `map`. The proper name for `and_then` is `flat_map`.
The `and_if` name evokes no meaning in my head. And if X then what? The name works only with convention but that convention doesn't exist. `filter` is well established already. We would need good reasons to deviate from this.

There are a bunch of `*_or*` variants of other functions and for all of them it's immediately obvious what they do and what kind of data they expect from the operation they extend.

**Comment by SimonSapin** [comment]
> the RFC thread already contains quite a few arguments for and against certain names

As it seems unlikely that more time will produce new arguments either way, I’d like to propose stabilizing this feature as it currently is in Nightly.

@rfcbot fcp merge
