### ISSUE TITLE
Enhance compiler errors with return types

### ISSUE THREAD

**Issue by xhallix** [rust-lang/rust#45871]
I want to return an object containing a specific type

I tried this code:

```
fn get_file_parser() {
    let file = File::open("/Users/me/dev/rust/foobar/examples/books.xml").unwrap();
    let file = BufReader::new(file);
    EventReader::new(file)
}
```
I expected to see this happen:

This could be a better suggestion
```
fn get_file_parser() -> xml::EventReader<std::io::BufReader<std::fs::File>> {
```

Instead, this happened: 

```
error[E0308]: mismatched types
  --> src/lib.rs:23:5
   |
23 |     EventReader::new(file)
   |     ^^^^^^^^^^^^^^^^^^^^^^ expected (), found struct `xml::EventReader`
   |
   = note: expected type `()`
              found type `xml::EventReader<std::io::BufReader<std::fs::File>>`
help: try adding a semicolon
   |
23 |     EventReader::new(file);
   |                           ^
help: try adding a return type
   |
20 | fn get_file_parser<T: std::io::Read>() -> xml::EventReader<_> {
   |                                        ^^^^^^^^^^^^^^^^^^^^^^
```

## Meta

`rustc --version --verbose`:

Backtrace:
rustc 1.21.0 (3b72af97e 2017-10-09)
binary: rustc
commit-hash: 3b72af97e42989b2fe104d8edbaee123cdf7c58f
commit-date: 2017-10-09
host: x86_64-apple-darwin
release: 1.21.0
LLVM version: 4.0

**Comment by durka** [comment]
What specifically would make the suggestion better?

**Comment by xhallix** [comment]
An improvement could be, to propose the correct type, `<std::io::BufReader<std::fs::File>` instead of `<_>` , since this is known to the compiler.
Another thing might be, if we have 2 different suggestion, they could be marked as such.
I really like the compiler and the hint it provides, so this is a small enhancement, which will especially help newcomers
