### ISSUE TITLE
Using x86 SIMD produces "LLVM ERROR" inside doc tests, but not in other code

### ISSUE THREAD

**Issue by marshallpierce** [rust-lang/rust#45874]
I have some code (x86 SIMD) that requires `target-feature`, but that code is optional and only used when the relevant `feature`s are enabled. This works fine in library code, tests, and benchmarks, but not in doc tests, where I get an "LLVM ERROR" when SIMD code is used. 

I've created a branch of the state of my project showing the issue: https://bitbucket.org/marshallpierce/stream-vbyte-rust/branch/rust-doc-llvm-error. The interesting test is here: https://bitbucket.org/marshallpierce/stream-vbyte-rust/src/20a8d010514f135ac2889b849d13fa6144c161c9/src/cursor.rs?at=rust-doc-llvm-error&fileviewer=file-view-default#cursor.rs-30. It is attempting to show how you can use the x86 SSE type `__m128i` if it is available.

In that branch (at `20a8d01`), running `cargo test --doc` runs the doc tests normally. Running `RUST_BACKTRACE=1 RUSTFLAGS='-C target-feature=+ssse3,+sse4.1' cargo +nightly test --all-features --doc -- --nocapture` (on a modern x86) exhibits the failure.

I expected to see this happen:

The doc test should compile and run using the `use_x86_simd_if_available` implementation corresponding to the enabled feature.

Instead, this happened: 

```
   Compiling stream-vbyte v0.3.2 (file:///home/mbp/dev/opensource/stream-vbyte-rust)
    Finished dev [unoptimized + debuginfo] target(s) in 0.40 secs
   Doc-tests stream-vbyte

running 2 tests
LLVM ERROR: Cannot select: t9: v16i8 = X86ISD::PSHUFB t3, t5
  t3: v16i8,ch = CopyFromReg t0, Register:v16i8 %vreg8
    t2: v16i8 = Register %vreg8
  t5: v16i8,ch = CopyFromReg t0, Register:v16i8 %vreg9
    t4: v16i8 = Register %vreg9
In function: _ZN9x86intrin5ssse315mm_shuffle_epi817h05d8a2ce7899d9b6E
```

`rustc --version --verbose`:

```
rustc 1.21.0 (3b72af97e 2017-10-09)
binary: rustc
commit-hash: 3b72af97e42989b2fe104d8edbaee123cdf7c58f
commit-date: 2017-10-09
host: x86_64-unknown-linux-gnu
release: 1.21.0
LLVM version: 4.0
```

**Comment by workingjubilee** [comment]
No repro in 2021, so it seems this has been fixed. Apologies if I am wrong, but I am closing this on that assumption.
