### ISSUE TITLE
incr.comp.: Explore delayed read-edge deduplication or getting rid of it entirely.

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#45873]
At the moment the compiler will always eagerly deduplicate read-edges in `CurrentDepGraph::read_index`. In order to be able to do this the compiler has to allocate a `HashSet` for each task. My suspicion is that there is not much duplication to begin with and that there's potential for optimization here:
- If there is not much duplication to begin with we could skip deduplication entirely for non-anonymous nodes. There should be no semantic difference and a slight performance hit only for actually duplicated nodes.
- If deduplication seems like a good idea, doing so during serialization instead of immediately has a few potential benefits:
  - Dep-graph serialization happens while LLVM is running in parallel, so more often than not any work done there might not add to the actual compile-time.
  - When compilation exits early with an error, we don't save the dep-graph at all and the work for deduplication has been wasted. If compilation already reached dep-graph serialization, the chances are high that it will succeed.
  - When we already have the whole dep-graph we can implement deduplication more efficiently because we know when we don't even have to allocate a hash set at all or, if we have to, we know which capacity will suffice.

So the first step would be to collect some data on how much read-edge duplication there even is. This is most easily done by modifying the compiler to count duplicates (in `librustc/dep_graph/graph.rs`) and print the number/percentage in `-Zincremental-info`. This modified compiler can then be used to compile a number of crates to get an idea what's going on. 

If duplication is low (e.g. less than 2% of reads got filtered out), then we could just remove de-duplication and test the effect with a try-build. Otherwise, we can move deduplication to `DepGraph::serialize()` and measure the performance impact of that.

**Comment by wesleywiser** [comment]
I'm working on this.

**Comment by wesleywiser** [comment]
I've collected some data from a few crates. It appears that duplicate reads happen much more frequently than originally thought. Of the crates I tested, the lowest was 19.2% duplicated reads. @michaelwoerister since this doesn't match what you were expecting, would you mind looking at my changes and verifying that I didn't do something wrong? My changes are available in my [incr_duplicate_read_stats](https://github.com/wesleywiser/rust/tree/incr_duplicate_read_stats) branch ([diff](https://github.com/rust-lang/rust/compare/master...wesleywiser:incr_duplicate_read_stats)). 

[Full results here](https://gist.github.com/wesleywiser/2647db70801422a665580d296af9eb18)

**Comment by michaelwoerister** [comment]
Huh, this is very interesting. Thank you so much for collecting this data. Goes to show again that one should always measure before assuming anything.

The data collection in your branch looks correct, except for one thing: For anonymous nodes we can't really make deduplication delayed, so counting them too will skew the assessment of what effect the proposed optimization would have. Sorry for not mentioning this earlier. Would you mind adapting your code so that it uses a separate counter for anonymous nodes? 

I'm not going to make a prediction on how this will affect the numbers `:)`

**Comment by wesleywiser** [comment]
Reran the same tests with the [updated code](https://github.com/rust-lang/rust/compare/master...wesleywiser:incr_duplicate_read_stats). The results aren't significantly different (the above "Full results here" link now points to the updated results).

**Comment by michaelwoerister** [comment]
Thanks, @wesleywiser!

OK, let's see, `Cargo` is the most resource intensive case here with `10,260,175` reads total and `1,173,234` of those after filtering. Each read costs 4 bytes to store, so keeping around all reads would cost about 40MB while when deduplicating immediately we only need 4.5MB. That's a pretty big difference but in absolute numbers it doesn't seem like a showstopper. OTOH, since we are storing so much more data in the `reads` vectors, the cost of re-allocations during vector growth might eat up any wins we get from delaying deduplication. 

I see two options on how to proceed:
- Leave things as they are for now and just merge stats collection.
- Go ahead and implement delayed deduplication in order to find out how it performs. 

I'll let you decide, @wesleywiser `:)`

**Comment by wesleywiser** [comment]
I'm game to implement delayed duplication and see how it performs. Do you mind if I go ahead and push up a PR for the stats collection? 

Also, what's the best way to measure the performance before and after the change? Just use `time`?

**Comment by michaelwoerister** [comment]
> I'm game to implement delayed duplication and see how it performs.

Cool, I'm really curious how it will do.

>  Do you mind if I go ahead and push up a PR for the stats collection?

No, please go ahead!

> Also, what's the best way to measure the performance before and after the change? 

I usually use `cargo` with a custom `rustup` toolchain. Since `cargo` already prints compile times, I don't need anything else. But `time` is fine too. 

That's for local testing. Once you have a version that you think is optimized enough, you can open a PR and @Mark-Simulacrum will trigger a perf.rust-lang.org measurement for us. That will give us a good idea on what performance will look like.

**Comment by wesleywiser** [comment]
@michaelwoerister I've tried delaying deduplication until serialization but I'm not seeing much of a difference in compilation time. I've set a `rustup override` that points to a custom toolchain in my `stage2` folder and I'm compiling with `CARGO_INCREMENTAL=1 cargo build`. That's the right command right?

If the issue is reallocations, would preallocating the `reads` vector help? 

(For reference purposes, my code is in my [incr_delay_dedup branch](https://github.com/rust-lang/rust/compare/master...wesleywiser:incr_delay_dedup))

**Comment by michaelwoerister** [comment]
> I've tried delaying deduplication until serialization but I'm not seeing much of a difference in compilation time.

I think the potential for improvement here is about 2% for a debug build with an empty cache. For a rebuild this might actually slow things down, since we'll be deduplicating already deduplicated vectors `:/` We'd have to store a flag with each vector that indicates whether it needs deduplication.

> I've set a rustup override that points to a custom toolchain in my stage2 folder and I'm compiling with CARGO_INCREMENTAL=1 cargo build. That's the right command right?

Pretty much, but you have to be careful to measure the correct thing. A few remarks:
* You usually don't need a stage2 compiler and unless you want to compile something with procedural macros or plugins in it, you don't even need a full stage1 compiler. Point your custom toolchain to the `stage1` folder and compile either with `./x.py build --stage 1 src/libtest` for a limited compiler (which can still compile crates like `regex` or `ripgrep`). That should cut down massively on your cycle time.
* Make sure that you're test compiler will have comparable performance to the compiler we'll be shipping to users. In order to do that set `debug-assertions = false` and `codegen-units = 1` in your `config.toml`.
* We want to measure the two extreme cases:
  1. Re-compiling the local crates of a project with an empty cache (compiling the dependencies from crates.io would just add noise). In order to do this, you have to run `rm -rf ./target/debug/incremental && touch ./src/lib.rs && CARGO_INCREMENTAL=1 cargo build` a few times. This will delete the incr. comp. cache but not the already compiled dependencies from `crates.io`. So the first measurement will be longer and the subsequent ones will measure what we are interested in. If the project you are compiling is an executable, you'll have to `touch ./src/main.rs` instead.
  2. Re-compiling the local crates of a project with a full cache and no changes. For that you just have to run `touch ./src/lib.rs && CARGO_INCREMENTAL=1 cargo build` a few times. It's the same as above, just without deleting the cache in between runs.

> If the issue is reallocations, would preallocating the reads vector help?

There are a few things in our implementation that can be improved:
* Don't use a `BTreeSet` for deduplication. In my measurements `FxHashSet` has always been faster, even for tiny collection sizes.
* Don't use a set at all when the `Vec` of edges to deduplicate is short:
  * If the `Vec` has a length smaller than or equal to 1 then there is no need to allocate a set. Just copy the data.
  * If the length is 2, just directly compare the two elements.
  * If the length is greater, use `HashSet::with_capacity(vec.len())` in order to avoid re-allocations.
* Don't copy the whole graph just for deduplication is you do here: https://github.com/wesleywiser/rust/blob/413211a05ae1e283350213e758a5798cd99b24b9/src/librustc/dep_graph/graph.rs#L434-L443 Instead, deduplicate as you write to the "serialized" version in this loop: https://github.com/rust-lang/rust/blob/77ab3a1d5ff69c0cb3eb85a75ef734eaf7429f1b/src/librustc/dep_graph/graph.rs#L440-L448 Note that we cannot know the correct `total_edge_count` beforehand anymore. You can just remove it. It was mostly an optimization to avoid having to grow the `edge_list_data` vector during the loop. It might make sense to start out with a capacity of something like `nodes.len() * 10` for `edge_list_data` though.

**Comment by wesleywiser** [comment]
Thanks, that's really helpful! I implemented your feedback but the [results](https://gist.github.com/wesleywiser/824d99aa567b5e52dadda27e90d1af9c) don't look very good. (The source is available in the branch I linked above)

**Comment by michaelwoerister** [comment]
Well, that's sad. But your implementation looks correct (except for not preserving edge order in the `len() > 2` case, but that should have no impact on performance) and I can't think of any more optimizations that would potentially make a big difference here.

I hope you still found it interesting to try a few things out! I"ll make sure to mention your efforts on the next impl period newsletter.

**Comment by wesleywiser** [comment]
Thanks! One thing I'm left wondering is if the time saved by delaying the deduplication is getting eaten by resizing the `reads` vec. Perhaps collecting some data about the most common size for it and preallocating to that size would improve the performance?

**Comment by michaelwoerister** [comment]
If you are up for that you can certainly try.

**Comment by wesleywiser** [comment]
Ok! I'll try to collect some data and report back.

**Comment by wesleywiser** [comment]
Here's what I've found:

![graph](https://user-images.githubusercontent.com/831192/33517618-61d84b64-d755-11e7-8169-e387a0bbb474.png)
![graph](https://user-images.githubusercontent.com/831192/33517624-717cf506-d755-11e7-8834-492a190a0902.png)
![graph](https://user-images.githubusercontent.com/831192/33517626-782359ea-d755-11e7-95d1-08de55fcffb3.png)
![graph](https://user-images.githubusercontent.com/831192/33517630-7d96097c-d755-11e7-98c6-664523292fa6.png)

**Comment by arielb1** [comment]
@wesleywiser 

This graph looks like it's missing some axes. Could you upload the raw data?

**Comment by wesleywiser** [comment]
@arielb1 Sure! The graphs are line plots of the values observed for `edges.len()` during serialization. The stacking in the first image indicates a huge number of duplicate values. 

The raw data is available [here](https://drive.google.com/file/d/1cPj0ejMZIhpbHxjiU0-doJngudr6iO2F/view?usp=sharing). There's one line for each iteration of [this loop](https://github.com/wesleywiser/rust/blob/368dc4b1e3a8c5eae394b80610c7bfc52aa18a59/src/librustc/dep_graph/graph.rs#L436).

**Comment by wesleywiser** [comment]
@michaelwoerister Given the huge number of empty vectors, I think preallocating would probably cause a huge memory blowup. Unless you have any ideas, I think we can probably close this issue.

**Comment by michaelwoerister** [comment]
@wesleywiser Yeah. Also, pre-allocating isn't free either. 

Thanks again for all your work on this!
