### ISSUE TITLE
Questions related toolchain for cross-compiling on Windows for Linux

### ISSUE THREAD

**Issue by avkonst** [rust-lang/rust#45883]
I have searched and read number of posts, Q&As and forums, but can not find solid working answer to the following questions. Could you please let me know if it is possible and if there is any documentation available. Sorry, I am bit new to this.

**Question 1**: I have found that it is relatively easy to compile from Linux to Windows using mingw. Is there an analogy to cross-compile from Windows to Linux? compilation on windows for windows requires VS C++ build tool chain, what should be installed for compilation on Windows for Linux?

**Question 2**: Visual Studio 2017 has got a component with Linux targeted toolchain (i.e. it builds C/C++ on Windows for Linux). I understand cargo/rustup do not pick it up automatically... Is this toolchain going to be supported?

**Comment by tinaun** [comment]
if you have wsl installed, compiling for linux is as simple as installing rust and cargo on wsl and running ‘cargo build’ in wsl bash. I don’t know how vs works, but in vs code it’s pretty easy to set up tasks that call commands through wsl. 

I don’t know if a windows install of cargo will ever detect toolchains installed in wsl, as the file system differences make looking at wsl through windows directly is fragile.

**Comment by rkarp** [comment]
You can use LLVM's LLD linker to cross-compile pure Rust crates on Windows with one of the `linux-musl` targets, see japaric/rust-cross#33.

**Comment by timClicks** [comment]
@rkarp does this require a local pre-compiled musl build or will cargo/rustc know to build that also?

**Comment by rkarp** [comment]
As long as all of your dependencies (and their dependencies) are pure Rust crates, it should work immediately, without you having to play around with musl. If there are any C sources, it gets trickier and you'll have to prepare the musl sources, but it can still be doable (depending on how the C sources have to be built).

**Comment by pietroalbini** [comment]
This issue tracker is for bugs or enhancements to the rust language, so questions are a bit out of place here. I recommend you to post this on [users.rust-lang.org](https://users.rust-lang.org) though, so all the expert people over there can help you!
