### ISSUE TITLE
stdlib docs still link to the first edition of the book

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#45891]
For example, the documentation for `Iterator::for_each` still links to the page on `for`-loops in the first edition of the book: https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.for_each . Fortunately, it should be easy to grep for all links to the book. Find all such links and replace them with links to the relevant pages in the second edition of the book (note that due to reorganization it's not as simple as just replacing "first-edition" with "second-edition" in the URL). This should be a very good task for beginners (as long as @steveklabnik and @carols10cents concur that the second edition is ready to be linked to).

**Comment by est31** [comment]
The second edition still has a big red notice "You are reading a **draft** of the next edition of TRPL.". If it is ready to be switched to that notice should maybe be removed.

**Comment by steveklabnik** [comment]
Yes; this is not ready to actually do. We can re-open this once it is.
