### ISSUE TITLE
compiler: recursion limit on recursive function when borrowing

### ISSUE THREAD

**Issue by prasannavl** [rust-lang/rust#45926]
Here's a simple merge sort with recursion:
https://play.rust-lang.org/?gist=ff2c804288593292cba30ff9e06facaa&version=stable

However, the compiler doesn't seem to compile this:
```
Compiling playground v0.0.1 (file:///playground)
error: reached the recursion limit while instantiating `merge_sort_with_buf::<i32, &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&[closure@src/main.rs:8:24: 8:51]>`
  --> src/main.rs:32:1
```

I can make it work by changing the signature of `merge_sort_with_buf` method to take a reference to `compare` instead, and changing recursive call to use `compare` instead of `&compare`. But I'm confused, shouldn't the compiler be able to handle this, without a signature change?

**Comment by TimNN** [comment]
No, the problem is that during the first recursive call, the type of "F" is just "F". Then it is "&F". Then "&&F". And so on. For each of these the compiler will generate a different version of the `merge_sort_with_buf`. Since it doesn't know when to stop, it would have to generate an infinite number of versions of the function, which it of course cannot do.

**Comment by prasannavl** [comment]
Ah. Got it. Thanks for the explanation. :)

**Comment by tclh123** [comment]
> No, the problem is that during the first recursive call, the type of "F" is just "F". Then it is "&F". Then "&&F". And so on. For each of these the compiler will generate a different version of the `merge_sort_with_buf`. Since it doesn't know when to stop, it would have to generate an infinite number of versions of the function, which it of course cannot do.

Shouldn't the compiler throw error immediately when it find type mismatch? (F != &F)
