### ISSUE TITLE
Missing `raw_string_body` rule in grammar doc

### ISSUE THREAD

**Issue by jturner314** [rust-lang/rust#45935]
In [`src/doc/grammar.md`](https://github.com/rust-lang/rust/blob/master/src/doc/grammar.md), a `raw_string_body` rule is used in the definition of the `raw_string` rule, but the definition of `raw_string_body` is missing.

Is it even possible to define `raw_string_body` using the EBNF dialect in the grammar document? (It depends on the number of `#` chars surrounding the raw string.) If not, there should at least be text describing its definition.

**Comment by fmease** [comment]
The Reference (the successor to `src/doc/grammar.md`) contains the following grammar snippet ([src](https://doc.rust-lang.org/reference/tokens.html#raw-string-literals)):

> **<sup>Lexer</sup>**\
> RAW_STRING_LITERAL :\
> &nbsp;&nbsp; `r` RAW_STRING_CONTENT SUFFIX<sup>?</sup>
>
> RAW_STRING_CONTENT :\
> &nbsp;&nbsp; &nbsp;&nbsp; `"` ( ~ _IsolatedCR_ )<sup>* (non-greedy)</sup> `"`\
> &nbsp;&nbsp; | `#` RAW_STRING_CONTENT `#`

As you can see, `RAW_STRING_CONTENT` (the successor of `raw_string_body`) is not only used but also defined.

Closing as completed.
