### ISSUE TITLE
Bounds check not optimized out after {r}position on a slice

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#45964]
All the unrolling makes it hard for llvm to optimize it out. Sample: https://godbolt.org/g/R9nLvC

#45501 has a fix that involves `assume(index < len)` but we couldn't quite get it to pass tests. Will need to give it another try with some fresh eyes.

**Comment by kennytm** [comment]
According to https://github.com/rust-lang/rust/issues/44899#issuecomment-342487870 there was a fix in upstream LLVM. We may reopen the PR if we backport the fix.

**Comment by arielb1** [comment]
@kennytm 

I already backported the fix, it's just that someone needs to make an "up the LLVM" PR that includes it.

**Comment by kennytm** [comment]
Reopening this because of #48209.

**Comment by scottmcm** [comment]
It's possible https://github.com/rust-lang/rust/pull/49551 could help with this, as it should make it easier for LLVM to understand the length of a slice iterator :crossed_fingers:

**Comment by arthurprs** [comment]
I think this can be closed, they put the assume back after patching LLVM.

**Comment by arielb1** [comment]
Could we have a codegen test? I'm marking this as E-needstest.
