### ISSUE TITLE
Error in CSS file for https://doc.rust-lang.org/book/

### ISSUE THREAD

**Issue by mike155** [rust-lang/rust#45974]
Web fonts don't work on this page: https://doc.rust-lang.org/book/ - at least not in Firefox.

Reason: @font-face definitions in CSS file "rust.css" are referring to the wrong level of the file system. The Woff files are stored in "/" -- and not in "/book".

Current (wrong) definition: 
`src: local('Fira Sans'), url("FiraSans-Regular.woff") format('woff');`

It should be:
`src: local('Fira Sans'), url("/FiraSans-Regular.woff") format('woff');`

Or even better:
`src: local('Fira Sans'), url("https://doc.rust-lang.org/FiraSans-Regular.woff") format('woff');`

The same is true for all @font-face definitions in the CSS file.

**Comment by ollie27** [comment]
#45998 should fix it.
