### ISSUE TITLE
`--error-format=short` should be an unstable option

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#45995]
i.e., require `-Zunstable-features`. This should be backported to beta if necessary.

cc @GuillaumeGomez @alexcrichton @estebank

**Comment by Mark-Simulacrum** [comment]
Setting priority to medium -- ideally we'd get this done before beta branched, but it definitely needs to land before 1.23 stable releases.

**Comment by GuillaumeGomez** [comment]
I'll add it very soon.

**Comment by nikomatsakis** [comment]
triage: P-high (I'd prefer to keep my eye on this)

But looks like @GuillaumeGomez is all over it. Thanks @GuillaumeGomez.

**Comment by GuillaumeGomez** [comment]
It's being merged (the PR is complete). I'll give it a high priority.
