### ISSUE TITLE
[refactoring] MIR stores the `return_ty` field in two places!

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#46001]
Right now, the MIR has a special field, `return_ty`:

https://github.com/rust-lang/rust/blob/f93a4928c2168bcc475b4fe77ba9f9e5494ffe1c/src/librustc/mir/mod.rs#L85-L86

However, the MIR *also* has an array of locals, and the 0th local is the "return slot". Its type is the return type:

https://github.com/rust-lang/rust/blob/f93a4928c2168bcc475b4fe77ba9f9e5494ffe1c/src/librustc/mir/mod.rs#L97-L102

It would be nice to eliminate the redundancy. My preference would be to remove the `return_ty` field, perhaps adding an accessor to `Mir<'tcx>` like:

```rust
fn return_ty(&self) -> Ty<'tcx> {
    self.local_vars[RETURN_POINTER].ty
}
```

**Comment by nikomatsakis** [comment]
I marked this as E-mentor, the mentoring instructions are inline above. Just remove the field in question and follow the thread of the compiler. Feel free to pop in [on gitter](https://gitter.im/rust-impl-period/WG-compiler-middle) with any questions that come up!

**Comment by j-haj** [comment]
I would like to give this a shot

**Comment by sodiumjoe** [comment]
looks like this is done and can be closed?
