### ISSUE TITLE
padding in format args doesn't work with debug impls

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#46006]
This:

```rust
fn main() {
    println!("Hello {0:5}!", "x");
}
```

prints what I expect:

```
Hello x    !
```

But this:

```rust
fn main() {
    println!("Hello {0:5?}!", "x");
}
```

prints `Hello "x"!` ([play](https://play.rust-lang.org/?gist=6f746b24ac615c640c68aac7c534838c&version=stable)), not:

```
Hello "x"  !
```

Is this intentional? If so, the format docs are pretty misleading. Otherwise, a regression perhaps? I'm not sure what is...T-libs?

cc @alexcrichton

**Comment by sfackler** [comment]
Each implementation of a `fmt::*` trait needs to individually decide if and how it's going to handle formatting flags. `Debug` impls tend to not handle them in general.

**Comment by alexcrichton** [comment]
Yeah this is "intentional" in the sense that it's not expected to work. We likely want to be more clear about this in the documentation though

**Comment by nikomatsakis** [comment]
Oh, interesting. I thought padding was imposed externally. OK, that's a shame. It'd be useful I think to have in std::fmt some wrappers that "impose" formatting from the outside -- e.g., I often wish that instead of using a flag like `{:22$}` I could do this:

```rust
use std::fmt;
...
format!("{}", fmt::padded(&foo, 22))
```

where `fmt::padded` takes the output of `foo.fmt()` and pads it to be of the given width. These could then be readily composed, so `{:22$?}` would be:

```rust
use std::fmt;
....
format!("{}", fmt::padded(fmt::debug(&foo), 22))
```

I should just make some things like this in the compiler I guess. Anyway. I'll close then!

**Comment by sourcefrog** [comment]
https://github.com/rust-lang/rust/pull/59933 mentions this in the docs.
