### ISSUE TITLE
cfg! branches not applicable to the current build are still type-checked

### ISSUE THREAD

**Issue by zacps** [rust-lang/rust#46013]
The issue is if there's a very long function that should be *almost* identical between two platforms/features the easiest way to make a small change is to use `cfg!`. However, if it created a type error because an identifier isn't available on the target platform/feature it will still create a compiler error even though it will never be executed.

For example say we had this situation:
```rust
#[cfg(unix)]
fn do_unix_stuff() {}

fn f() {
    do_stuff();
    do_unix_stuff();
}
```
And we wanted to make `f` win32 compatible, in this case we could just replace `f` entirely but if it was substantially longer the easiest way is to use `cfg!`.
```rust
fn f() {
    do_stuff();
    if cfg!(unix) {
        do_unix_stuff();
    }
}
```
However this will fail when building on windows because `do_unix_stuff` is not defined. If type checking was disabled for branches that will never be executed on the current build this situation would work fine.

This also makes the `cfg!` macro's behaviour more similar to the `cfg` attribute's behaviour.

**Comment by sfackler** [comment]
`cfg!(..)` just expands into `true` or `false`. I'm not sure disabling type checking based on unreachability is a good idea in general.

You can instead use a cfg'd block:

```rust
fn f() {
    do_stuff();
    #[cfg(unix)]
    {
        do_unix_stuf();
    }
}
```

**Comment by zacps** [comment]
Ah, I wasn't aware you could use the `cfg` attribute on blocks or statements. Closing.
