### ISSUE TITLE
MIR borrowck error message talks about "cannot move out of borrowed_content" (instead of "borrowed content")

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#46018]
https://github.com/rust-lang/rust/blob/88a28ff6028cf197ed6b4185d8cd4887f05e3e07/src/librustc_mir/borrow_check.rs#L79-L102

This appears e.g. in
```Rust
struct S;
fn main() {
    let a = &mut S;
    let b = *a;
}
```

and also in the test src/test/compile-fail/borrowck/borrowck-for-loop-correct-cmt-for-pattern.rs

**Comment by anrdh** [comment]
I can take care of this!

**Comment by ritiek** [comment]
This issue can be closed now.
