### ISSUE TITLE
Add an error for inline assembly which are non-volatile without any outputs

### ISSUE THREAD

**Issue by Zoxc** [rust-lang/rust#46026]
https://github.com/rust-lang/rust/pull/45920 turned up some usages of inline assembly which have no outputs. LLVM will just remove such inline assembly as they can never be used. We should make this an error.

**Comment by parched** [comment]
Alternatively, do what GCC does and add volatile automatically if there are no outputs.

**Comment by sunfishcode** [comment]
It's worth considering an error though; inline asm is uncommon and extraordinarily unsafe, conditions which generally favor explicitness over implicitness.
