### ISSUE TITLE
Tracking issue for calling standard library `const fn`s

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#46038]
The functions below in the standard library are `const fn` with individual feature gates for calling them in constant expressions. This issue is tracking the stabilization of such calls.

CC https://github.com/rust-lang/rust/issues/24111, the super-set feature which also includes defining new `const fn` items.

* `std::sync::Once::new`
* `core::cell::Cell::new`
* `core::cell::RefCell::new`
* `core::cell::UnsafeCell::new`
* `core::sync::AtomicBool::new`
* `core::sync::AtomicPtr::new`
* `core::sync::Atomic$IntegerType::new`
* `core::mem::size_of`
* `core::mem::align_of`
* `core::ptr::null`
* `core::ptr::null_mut`
* `<$IntegerType>::max_value`
* `<$IntegerType>::min_value`

Items in `core::` are also re-exported in `std::`.

**Comment by SimonSapin** [comment]
Feature gates are:

* `const_once_new`
* `const_cell_new`
* `const_refcell_new`
* `const_unsafe_cell_new`
* `const_size_of`
* `const_align_of`
* `const_ptr_null`
* `const_ptr_null_mut`
* `const_min_value`
* `const_max_value`
* `const_atomic_bool_new`
* `const_atomic_ptr_new`
* `const_atomic_i8_new`
* `const_atomic_u8_new`
* `const_atomic_i16_new`
* `const_atomic_u16_new`
* `const_atomic_i32_new`
* `const_atomic_u32_new`
* `const_atomic_i64_new`
* `const_atomic_u64_new`
* `const_atomic_isize_new`
* `const_atomic_usize_new`

**Comment by aturon** [comment]
Kicking off stabilization discussion for the const-ness of these functions in `std`. 

@rfcbot fcp merge

**Comment by chabapok** [comment]
How to about mark std::time::Duration::{from_millis, new, from_secs, from_micros} as const_fn?

**Comment by sfackler** [comment]
new can panic so it can't be const.

**Comment by durka** [comment]
@sfackler sure it can, the same way an indexing expression can be const.

**Comment by sfackler** [comment]
@durka How?

```rust
#![feature(const_fn)]

const fn foo(a: i32) {
    if a > 10 {
        panic!();
    }
}

fn main() {}
```

```
error[E0019]: constant function contains unimplemented expression type
 --> src/main.rs:4:5
  |
4 | /     if a > 10 {
5 | |         panic!();
6 | |     }
  | |_____^

error: aborting due to previous error
```

```rust
#![feature(const_fn)]

const fn foo(a: i32) {
    panic!();
}

fn main() {}
```

```
error[E0015]: calls in constant functions are limited to constant functions, struct and enum constructors
 --> src/main.rs:4:5
  |
4 |     panic!();
  |     ^^^^^^^^^
  |
  = note: this error originates in a macro outside of the current crate

error: aborting due to previous error
```

**Comment by eddyb** [comment]
I think this is "what is allowed right now" vs "what we could allow" (i.e. miri evaluates panics just fine).

**Comment by durka** [comment]
Yeah sorry, I just meant that *in theory* we could translate panics to
compile errors.

**Comment by SimonSapin** [comment]
There are many more `fn`s that could be made `const` once miri lands, and we should definitely consider them then. This issue is specifically about those that are already `const`, and stabilizing calls to them Very Soon<sup>®</sup>.

**Comment by SimonSapin** [comment]
I’ve submitted https://github.com/rust-lang/rust/pull/46287

**Comment by solutiontracking** [comment]
This post is great and helpful. I like it very much. This is surprising. I am really surprised. I hope you continue to make such good content in the future. If you want to find anything for Saudi Arabia Tracking Solutions Company, please visit my website: [Tracking Solutions](https://tracking.me/).
