### ISSUE TITLE
[NLL] false edges on infinite loops

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#46036]
The NLL RFC specifies false edges on infinite loops, so that we get errors in some cases. This is a  somewhat disputed clause (see https://github.com/nikomatsakis/nll-rfc/issues/35) that we may change, but it makes sense for now. I'm filing this so we don't forget about it.

**Comment by nikomatsakis** [comment]
So @mikhail-m1 added the notion of "false edges" in https://github.com/rust-lang/rust/pull/45384. This seems to be roughly what is needed here. We would want to edit the code that generates a `loop` construct:

https://github.com/rust-lang/rust/blob/3e49ada7528bf664b2ccc8516a9ef7d21849a70b/src/librustc_mir/build/expr/into.rs#L149-L204

and modify the graph in the case where condition is `None`:

https://github.com/rust-lang/rust/blob/3e49ada7528bf664b2ccc8516a9ef7d21849a70b/src/librustc_mir/build/expr/into.rs#L191

so that we create a FalseEdges that "breaks out".

**Comment by nikomatsakis** [comment]
Added some mentoring instructions to this NLL issue. Can elaborate as needed!

cc nll folks:

@davidtwco
@chrisvittal
@pnkfelix
@spastorino
@nashenas88
@gaurikholkar
@qmx
@Pulkit07
@ritiek

**Comment by Pulkit07** [comment]
I am trying to fix this one. I have already a kind of patch ready, need to dump MIR and see if it's doing the right thing.

**Comment by nikomatsakis** [comment]
@Pulkit07 nice :)

**Comment by nikomatsakis** [comment]
@Pulkit07 woah, core dumped?! When do you get the error, when bootstrapping?

**Comment by Pulkit07** [comment]
@nikomatsakis I am getting this error when running tests like src/test/run-pass/auto-loop.rs, src/test/run-pass/break.rs and many others.

**Comment by nikomatsakis** [comment]
@Pulkit07 even if you don't have time to continue working, it'd be helpful if you could post the diff somewhere of how far you got

**Comment by nikomatsakis** [comment]
From gitter, here is the diff https://bpaste.net/show/ac4eab0ead8e

**Comment by bobtwinkles** [comment]
So playing with implementing this I've run in to a stumbling block. It seems like `TerminatorKind::FalseEdges` is mostly intended for use where control flow could sort-of follow the false edge in "normal" execution; the motivating example being things being moved in match arm guards. However in the situation mentioned here, control flow truly follows the false edge in "exceptional" circumstances (panics). The trouble is that there are a number of analysis passes that don't handle this and I'm not sure how to get that knowledge in to them. The first one I've run in to is MIR typeck:

```rust
fn oh_no1() -> i32 {
    loop {
         return 1;
    }
    //  we abort here since the fake edge means MIR typeck tries to assert that () == i32
}
```

**Comment by nikomatsakis** [comment]
@bobtwinkles 

Ah, very good point!  You are correct that this control flow is supposed to be like a "false unwind".

My instructions were wrong in this respect. We want the false edge not to "break out" but rather to go to an unwinding target. Basically, where we *would* unwind to, if we were unwinding. The method to get such a block is `diverge_cleanup`, iirc:

https://github.com/rust-lang/rust/blob/3e49ada7528bf664b2ccc8516a9ef7d21849a70b/src/librustc_mir/build/scope.rs#L715-L722

I'm not sure whether we will have to further modify `FalseEdges` to distinguish between a "false unwinding" edge and a "false normal" edge. If so, we can probably just add a boolean flag or something like that.

**Comment by nikomatsakis** [comment]
Here is a test case that @bobtwinkles and I discussed on IRC:

https://play.rust-lang.org/?gist=f9b57ba12faa3e9bc8e4a4d523d58736&version=nightly

Right now, it ICEs, but it also ought to be reporting an error if this is all working correctly.
