### ISSUE TITLE
Windows missing dll no error message

### ISSUE THREAD

**Issue by Yanpas** [rust-lang/rust#46047]
I have a rust project which uses openssl crate, which depends on two openssl dlls: libssl-1_1-x64 and libcrypto-1_1-x64. If they are not available to executable - then executable silently exits with exit status -1073741515. C/Cpp apps ususally display that some symbol could not be found.

**Comment by retep998** [comment]
This is a consequence of running command line applications from the command line. Error dialogs regarding missing DLLs are silenced in that case and there's not a lot Rust can do because DLL imports are resolved before any Rust code ever runs.

**Comment by Yanpas** [comment]
Yes, seems to be default behavior on windows.

Steps to reproduce with C:

File `main.c`:
```
#include <stdio.h>
int foo();
int main() {
	foo();
	puts("aaa");
}
```

File `lib.c`:
```
__declspec(dllexport) int foo() {
	return 1;
}
```

Run following commands:
```
vcvarsall x64
cl /LD lib.c
cl main.c /link lib.lib
main.exe
echo %errorlevel% ; will print 0
move lib.dll lib1.dll
echo %errorlevel% ; will print non zero number
```

So yes, there is no warning by default :(

**Comment by bjorn3** [comment]
Given that this is expected behavior of Windows and there is not a lot rustc can do, should this be closed?

**Comment by ChrisDenton** [comment]
Probably. I guess `cargo run` could somehow have an option to enable fatal diagnostic dialogues. But it would be a bad default because scripts would hang until the `ok` button is clicked... and there might not even be anyone there to click that button.

**Comment by bjorn3** [comment]
Yeah, toggling that option on a CI machine would basically deadlock.
