### ISSUE TITLE
liballoc_jemalloc nallocx should be ReadOnly

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#46046]
`nallocx` is a `[[pure]]` function in the GCC sense, and should have the LLVM ReadOnly attribute. I've been looking for a way to apply LLVM attributes to functions in Rust without much luck (another interesting one is `ReadNone`, GCC's `const` attribute). 

Is there a way to do this?

**Comment by rkruppe** [comment]
Clang doesn't appear to add the `readnone` attribute to `malloc`, so I am skeptical whether it would be sound for us to add it to a similar allocation function.

**Comment by gnzlbg** [comment]
> Clang doesn't appear to add the readnone attribute to malloc

That's because `malloc` is not pure. As I mentioned, however, `nallocx` is.

**Comment by rkruppe** [comment]
Oh, I misunderstood what nallocx does, disregard me.

**Comment by gnzlbg** [comment]
The quick and dirty way would be to add two attributes, `#[llvm_readonly]` and `#[llvm_readnone]` behind two feature gates for internal use in core and std. 

A more useful thing to do would be to add some `#[c_attributes(attr...)]` attribute that only works with C-FFI (which is unsafe anyways) and that recognizes the C attributes that we currently don't expose in Rust (e.g. `gcc::const`, `gcc::pure`, ...) so that we can propagate these attributes to the Rust side when doing FFI.

**Comment by workingjubilee** [comment]
liballoc_jemalloc is no longer a core component of the Rust runtime, instead being used as a library by the Rust compiler.
