### ISSUE TITLE
std::ops documentation should discuss higher ranked trait bounds

### ISSUE THREAD

**Issue by hdevalence** [rust-lang/rust#46067]
The `std::ops` traits are defined to take `T` rather than `&T`.  This means that for "medium-sized" structs (by this I mean: large enough that copies are expensive, but not so large that they should be boxed, such as finite field elements, group elements, etc.), naively implementing the `ops` traits for `T` rather than for `&T` can cause excessive copies and hurt performance.

The docs mention that

> For example, for a user-defined type T which is supposed to support addition, it is probably a good idea to have both T and &T implement the traits Add<T> and Add<&T> so that generic code can be written without unnecessary cloning.

but don't describe how to actually do this, which requires using HRTBs:

```
impl<'a, 'b> Add<&'b ExtendedPoint> for &'a ExtendedPoint {
    /* ... */
}
```

This syntax isn't intuitive, and there's no mention that "HRTBs" are required to actually implement the `std::ops` traits for `&T`.

I think it would be good to mention "higher ranked trait bounds" in the `std::ops` documentation, since, for better or for worse, they're apparently required to implement the traits properly.

**Comment by kennytm** [comment]
There are no HRTBs in `impl<'a, 'b> Add<&'b ExtendedPoint> for &'a ExtendedPoint`, these are just regular trait bounds...

**Comment by hdevalence** [comment]
@kennytm oops, you're right, I gave a bad example, sorry. I can edit the description if that helps.

The thing I was thinking of is that in order to write a function which is generic over one of these types, I had to write
```
where T: /* ... */, for<'a> &'a T: Neg<Output=T>
```
which is a HRTB.
