### ISSUE TITLE
Searching "&" and "&mut" in stdlib api docs should show "reference (primitive)"

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#46075]
If you don't recall or know the name of the reference primitive (like, uh, I did earlier), searching on https://doc.rust-lang.org/std/ for "&", "&m", "&mu", and "&mut" should show the result "reference (primitive)" as the first result.

Likewise for `[]` and `[;]` for slices and arrays, and `()` and `(,)` and `(,,)` and etc. for tuples. And probably others.

**Comment by GuillaumeGomez** [comment]
Like said on IRC, it'll be complicated and we'll require a strong and huge update of the search functionalities.
