### ISSUE TITLE
Display installation instructions for OSs other than the one detected

### ISSUE THREAD

**Issue by TomasHubelbauer** [rust-lang/rust#46085]
On https://www.rust-lang.org/en-US/install.html, please add a link that would expand the installation instructions for other platforms that the one the JavaScript logic detected to be currently used.

I am a Windows user experimenting with Rust using WSL.

**Comment by nagisa** [comment]
The link, pointed at https://www.rust-lang.org/en-US/other-installers.html, is available at the bottom of the page you’ve linked. Among the auxiliary information, it has instructions on how to install rustup on both Unix and Windows, as well as direct download links for rustup-init for people who’d rather not run arbitrary shell scripts.

Furthermore, the issues pertaining to the website belong on the https://github.com/rust-lang/rust-www repository, so closing. If the already present link is not enough, or isn’t discoverable easily enough, please fill the issue there. Thanks!
