### ISSUE TITLE
Method to turn std::vec::IntoIter back into a Vec

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#46084]
This would be needed for improving the ergonomics of the [`sorted()`](https://docs.rs/itertools/0.7.2/itertools/trait.Itertools.html#method.sorted) iterator adapter in https://github.com/bluss/rust-itertools/issues/238. The current implementation returns a Vec, which forces the user to use `into_iter()` in the case that they want to continue with the iterator chain.

```rust
// need a second into_iter(), which normally does not happen in iterator chains
iter.sorted().into_iter().map(...)
```

It would be more convenient if `sorted()` could return a `std::vec::IntoIter` which the user can convert efficiently back into a Vec if that's what they need.

```rust
// seamlessly continue the chain
iter.sorted().map(...)

// done, get a vec
iter.sorted().into_vec()
```

@bluss

**Comment by bluss** [comment]
You know what, it kind of already exists, but is not documented.

It's this specialization of FromIterator for Vec:

https://github.com/rust-lang/rust/blob/d8d5b6180f56e4aaddc9492b891f85f9ca4a3c64/src/liballoc/vec.rs#L1856-L1874

I believe a method `.into_vec()` would still help the interface here. (It has been discussed before, maybe `.into_vec()` should be a special case of `collect()` that all iterators have.)

**Comment by kennytm** [comment]
I've untagged `T-libs` since it seems the only problem is documentation, which in should advertise that `collect()` is optimized for `IntoIter`. 

The `into_vec()` method was once proposed in #40051, and is now tracked in the internals thread https://internals.rust-lang.org/t/add-iterator-into-vec/4845.

**Comment by steveklabnik** [comment]
Given the discussion in #51156, I'm going to close this for now; we don't want to make these kinds of guarantees until specialization lands, and I would prefer to not speculate in docs, and instead wait until that happens. Thanks!
