### ISSUE TITLE
Arch-dependent partitioning in sort_unstable

### ISSUE THREAD

**Issue by stjepang** [rust-lang/rust#46080]
I want to benchmark the implementation of `sort_unstable` with and without an optimization called *branchless partitioning*. On some architectures it improves performance (e.g. my x86-64 Intel i7) and on others it degrades performance (e.g. my ARM v7 Raspberry Pi). I want to test it on as many architectures as possible and then conditionally turn it on or off.

I personally don't have access to a variety of different machines to test this. Would it be possible to run my benchmarks on different architectures on Rust's testing infrastructure? The benchmark could be a single `.rs` file that prints two numbers on the screen (time in seconds to sort 10M integers with and without branchless partitioning).

cc @alexcrichton

**Comment by kennytm** [comment]
The Rust CI just runs its tests on Docker (non x86 architectures are tested through qemu), so unfortunately the regular testing infrastructure isn't going to help.

**Comment by stjepang** [comment]
Here's the benchmark program:
https://gist.github.com/stjepang/3c0303f1d31784705659bd10e07627d5

Running: `rustc -O a.rs && ./a`
The program will print two numbers.

If someone has a non-x86-64 machine (I'm interested even in 32-bit x86), it'd be very grateful if you could compile and run the program, then paste the output. :)

**Comment by stjepang** [comment]
I've just noticed that things are not so simple on ARM architectures:
* When sorting integers, classic partitioning is faster.
* When sorting tuples of integers (either by one key or multiple keys), branchless partitioning is faster. 

I'll have to investigate further. Closing until I figure what's going on here.
