### ISSUE TITLE
Case insensitive link in documentation

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rust#46105]
Hello.
There's an issue for the links of the rust doc since links are case insensitive:
For instance, [this link](http://gtk-rs.org/docs/gdk/enums/key/constant.A.html) opens the same page as [this one](http://gtk-rs.org/docs/gdk/enums/key/constant.a.html).
Thanks to fix this issue.

**Comment by ollie27** [comment]
This might be a dupe of #25879.

**Comment by antoyo** [comment]
Looks like it is.
Closing.
