### ISSUE TITLE
Segmentation fault after doing matrix multiplication and memory shuffling for 45 minutes.

### ISSUE THREAD

**Issue by OmnipotentEntity** [rust-lang/rust#46133]
$ time cargo run --release parameters_strict.json core.json reflector.json > out.txt
        Finished release [optimized] target(s) in 0.0 secs
         Running `/home/omnipotententity/college/NRE4802/HW07/multigroup/target/release/multigroup parameters_strict.json core.json reflector.json`
    [2]    6562 segmentation fault  cargo run --release parameters_strict.json core.json reflector.json > out.txt
    cargo run --release parameters_strict.json core.json reflector.json > out.txt  4948.06s user 60.50s system 188% cpu 44:22.04 total

[multigroup.zip](https://github.com/rust-lang/rust/files/1488956/multigroup.zip)

**Comment by OmnipotentEntity** [comment]
Note that this might wind up being a problem in ndarray.  I don't know if ndarray does any unsafe operations.

**Comment by lukaslueg** [comment]
Without any more information about where the crash occurs, I'd suggest this problem is not unlikely to be caused by a hardware fault: Running something for 45min under full load will cause a faulty memory module to do it's worst if such a problem exists at all.

Maybe you can produce a backtrace?

**Comment by nagisa** [comment]
I tried to build the linked code, but it seems to be platform-dependent or something, as I got linker errors related to LAPACK referenced from ndarray.

@OmnipotentEntity do you know if perhaps your application was nearing completion at the time it failed? Does the program also fail if you reduce the problem space? Increase it? As @lukaslueg said, this could as well be a genuine issue with your hardware, so anything you could do to remove the possibility of this happening, would help greatly.

**Comment by OmnipotentEntity** [comment]
@nagisa The code had finished inverting the matrix.  Which moves it into a phase of continually reallocating memory to store larger and larger arrays as history moves forward.  It had not finished the first 100 iterations yet, which is the first status report.  I will attempt to reproduce on a different computer and see if I cannot produce a backtrace.

**Comment by sfackler** [comment]
Running the program in a debugger or taking a core dump is probably the best way to see what's going on.

**Comment by OmnipotentEntity** [comment]
After testing it, the issue seems to be both:

a) related to an OOM condition
b) occurs within OpenBLAS, so not even Rust code (Fortran)

So I'm closing this bug as invalid.  Thanks for the help in debugging it.
