### ISSUE TITLE
Suggest adding undeclared lifetime parameters to struct 

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rust#46135]
The following code:
```rust
struct Foo {
    x: &'a u8,
}
```

Generates this error:
```
error[E0261]: use of undeclared lifetime name `'a`
 --> src/main.rs:2:9
  |
2 |     x: &'a u8,
  |         ^^ undeclared lifetime

error: aborting due to previous error

error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

It'd be nice to provide a suggestion to add a lifetime parameter to the struct definition.

[Originally suggested here](https://github.com/rust-lang/rust/pull/46051#discussion_r152103504).

**Comment by estebank** [comment]
In the following code: https://github.com/rust-lang/rust/blob/5a2465e2b44ecdd3b5d835c0abe29e9a4c9dcfe4/src/librustc/middle/resolve_lifetime.rs#L1096-L1099

suggest adding the undeclared lifetime to the appropriate parent scope(s) (`fn` or `impl` blocks).

Bonus points to perform fuzzy search of the undeclared lifetime against [all the parent binders](https://github.com/rust-lang/rust/blob/5a2465e2b44ecdd3b5d835c0abe29e9a4c9dcfe4/src/librustc/middle/resolve_lifetime.rs#L1096-L1099) to provide typo suggestion.

**Comment by theindigamer** [comment]
I can work on this. :)

**Comment by estebank** [comment]
@theindigamer feel free to reach out in [gitter](https://gitter.im/rust-impl-period/WG-compiler-errors), [internals](internals.rust-lang.org), IRC or here if you need any help!

**Comment by theindigamer** [comment]
Thinking about using lifetime parameters that haven't been initialized generically (as opposed to purely in the context of struct definitions), the two simplest cases are

1. If inside a struct definition, suggest adding the lifetime parameter after the struct's name.
2. If inside a free-standing function, suggest adding the lifetime parameter after the function's name.

A slightly more complex case is:

3. If inside a function inside an `impl`, depending on the situation, add the lifetime parameter after the function's name or after the `impl`... - I'm not sure what heuristic should be used here for the suggestion. It might make more sense to either add the parameter to either the `fn` or to the `impl`.

One could create more complicated cases by arbitrarily nesting `fn` and `impl` (a `fn` can contain a `struct` and an `impl`, and an `impl` can contain a `fn`). I'm not entirely sure if we could cook up a case where the lifetime _must_ be introduced in some arbitrary ancestor (not just the parent or grandparent), but maybe that is just my lack of imagination.

Another minor issue is that (ideally) we should "unify" errors in the sense that
```
impl Foo<'a> {
    fn x(&self) -> &'a u8
}
```
will give two errors
```
error[E0261]: use of undeclared lifetime name `'a`
 --> foo.rs:5:10
  |
5 | impl Foo<'a> {
  |          ^^ undeclared lifetime

error[E0261]: use of undeclared lifetime name `'a`
 --> foo.rs:6:21
  |
6 |     fn x(&self) -> &'a str { self.x }
  |                     ^^ undeclared lifetime

error: aborting due to 2 previous errors
```
but it should give only one suggestion, which is replace `impl` with `impl<'a>`. What would be a good approach for doing so?

**Comment by estebank** [comment]
You have adequately expressed the nuance when encountering nested scopes.

For the [case where you have nested `impl`s/`fn`s/`struct`s](https://play.rust-lang.org/?gist=c5389d01d582fabdb8cf7539d23f6ff4&version=nightly) I would provide a label to all the places where the lifetime could be declared:

```rust
struct X;

impl X {
    fn bar(bar_arg: &'a usize) {
        fn foo(foo_arg: &'a usize) {
            struct Y {
                y: &'a usize,
            }
        }
    }
}
```
```
error[E0261]: use of undeclared lifetime name `'a`
 --> src/main.rs:4:22
  |
3 | impl X {
  | ------ if you mean to declare lifetime `'a` in the `impl`, use `impl<'a> X<'a>`
4 |     fn bar(bar_arg: &'a usize) {
  |     ------           ^^ undeclared lifetime
  |     |
  |     if you meant to declare lifetime `'a` in the `fn`, use `fn bar<'a>`

error[E0261]: use of undeclared lifetime name `'a`
 --> src/main.rs:5:26
  |
5 |         fn foo(foo_arg: &'a usize) {
  |            ---              ^^ undeclared lifetime
  |            |
  |            help: declare lifetime `'a`: `foo<'a>`

error[E0261]: use of undeclared lifetime name `'a`
 --> src/main.rs:7:21
  |
6 |            struct Y {
  |                   - help: declare lifetime `'a`: `Y<'a>`
7 |                 y: &'a usize,
  |                     ^^ undeclared lifetime

error: aborting due to 3 previous errors
```

For the code example you provided, what I would do is to still emit the first error, recommend the suggestion to add the undeclared lifetime to the impl but accept it at the parser level as a valid lifetime binding. This way the second error won't be emitted (unless the `'a` binding is removed, then it will trigger), but the compilation won't be successful due to the first error. In the end the output would look something like:

```
error[E0261]: use of undeclared lifetime name `'a`
 --> foo.rs:5:10
  |
5 | impl Foo<'a> {
  | ----     ^^ undeclared lifetime
  | |
  | help: declare lifetime `'a` here: `impl<'a>`
```

**Comment by theindigamer** [comment]
>   | ------ if you mean to declare lifetime `'a` in the `impl`, use `impl<'a> X<'a>

Do you mean `impl<'a> X` here, since `X` doesn't have a lifetime parameter in the example? Also, I'm slightly surprised that you need to declare the lifetime in 3 places and (for example) [this](https://play.rust-lang.org/?gist=6183c33dde8874563b9d203f5e62dc07&version=nightly) doesn't compile.
```
struct X;

impl<'a> X {
    fn bar(bar_arg: &'a usize) {
        fn foo(foo_arg: &'a usize) {
            struct Y<'a> {
                y: &'a usize,
            }
        }
    }
}

fn main() {}
```
Are lifetimes parameters only allowed to be used in the children and not in further descendants? That makes things much simpler.

> accept it at the parser level as a valid lifetime binding

Got it. Just to make sure that I'm understanding correctly, the way to do it would be to call `self.insert_lifetime` with the appropriate arguments, correct?

**Comment by estebank** [comment]
> Do you mean impl<'a> X here, since X doesn't have a lifetime parameter in the example? 
You're right.

> Are lifetimes parameters only allowed to be used in the children and not in further descendants? That makes things much simpler.

I believe lifetimes only get passed from `impl`s to a nested `fn`s, but not from an `fn` to a nested one or [between nested `impl`s](https://play.rust-lang.org/?gist=b6756fd193a834c4045242d7b20bc531&version=stable).

> Just to make sure that I'm understanding correctly, the way to do it would be to call self.insert_lifetime with the appropriate arguments, correct?

I believe that is the case.

**Comment by steveklabnik** [comment]
Triage: this error is the same today.

**Comment by estebank** [comment]
I believe https://github.com/rust-lang/rust/pull/68267 partially addresses this.
