### ISSUE TITLE
Missing "unnecessary parentheses" warning

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#46137]
This program compiles without warnings:

```
fn main() {
    use std::ops::Range;
    fn foo(r1: Range<u32>, r2: Range<u32>) {
        for _ in r1 {}
        for _ in r2 {}
    }
    foo((0 .. 10), (0 .. 10)); // ***
    foo(0 .. 10, 0 .. 10);
}
```

I expected a "unnecessary parentheses" warning on the first call to foo() because #[warn(unused_parens)] is on by default.

**Comment by zackmdavis** [comment]
This is because we currently don't check for unused parens in call arguments:

https://github.com/rust-lang/rust/blob/16992930835ce3376a4aaed42307726e1fc78e45/src/librustc_lint/unused.rs#L294-L306

(notice: no `ast::ExprKind::Call` or `::MethodCall` in the match).

So another example would be:

```rust
fn add_one(n: usize) -> usize {
    n + 1
}

fn main() {
    add_one((2));
}
```
