### ISSUE TITLE
can not get all windows file_attribute 

### ISSUE THREAD

**Issue by yorkart** [rust-lang/rust#46147]
On the windows platform, I want to get the file attribute `nFileIndexHigh` , `nFileIndexLow`, `dwVolumeSerialNumber` .

with the source code in std::sys::windows::fs.rs
```rust 
    pub fn file_attr(&self) -> io::Result<FileAttr> {
        unsafe {
            let mut info: c::BY_HANDLE_FILE_INFORMATION = mem::zeroed();
            cvt(c::GetFileInformationByHandle(self.handle.raw(),
                                              &mut info))?;
            let mut attr = FileAttr {
                attributes: info.dwFileAttributes,
                creation_time: info.ftCreationTime,
                last_access_time: info.ftLastAccessTime,
                last_write_time: info.ftLastWriteTime,
                file_size: ((info.nFileSizeHigh as u64) << 32) | (info.nFileSizeLow as u64),
                reparse_tag: 0,
            };
            if attr.is_reparse_point() {
                let mut b = [0; c::MAXIMUM_REPARSE_DATA_BUFFER_SIZE];
                if let Ok((_, buf)) = self.reparse_point(&mut b) {
                    attr.reparse_tag = buf.ReparseTag;
                }
            }
            Ok(attr)
        }
    }
```
None of these attributes are available.

Whether can complete these attributes?

**Comment by retep998** [comment]
You can use `AsRawHandle::as_raw_handle` to get the raw handle from a `File`. You can then use the `GetFileInformationByHandleEx` function from [winapi](https://github.com/retep998/winapi-rs) to access all the information you desire.

**Comment by steveklabnik** [comment]
Given that there's a way to do this today, and no other comments in the (almost) two years since this was posted, I'm going to give this a close. Thanks!
