### ISSUE TITLE
Rustdoc: searching for "try_" doesn't show `try_send` and `try_recv`

### ISSUE THREAD

**Issue by stjepang** [rust-lang/rust#46151]
After typing "try_" into the search box, the results don't show methods `try_send` and `try_recv` from mpsc channels: https://doc.rust-lang.org/nightly/std/?search=try_

In fact, I don't think any of the presented results contain "try_" as substring anywhere. This is a bit odd.

**Comment by kennytm** [comment]
Duplicate of #46021.
