### ISSUE TITLE
The `-Z external-macro-backtrace` message will appear in the stable channel

### ISSUE THREAD

**Issue by kennytm** [rust-lang/rust#46167]
Since #45545 is merged, when an error happens in an external macro, rustc will suggest the user to supply the unstable flag `-Z external-macro-backtrace` to see the detailed backtrace:

```
error[E0282]: type annotations needed
  --> $DIR/cannot_infer_local_or_vec.rs:12:13
   |
12 |     let x = vec![];
   |         -   ^^^^^^ cannot infer type for `T`
   |         |
   |         consider giving `x` a type
   |
   = note: this error originates in a macro outside of the current crate (run with -Z external-macro-backtrace for more info)

error: aborting due to previous error
```

The problem is that `-Z` flags cannot be used in beta/stable, so the suggestion will be wrong. The question would be:

* Should we explicitly specify the flag is only available in nightly, e.g. `(in nightly, run with -Z external-macro-backtrace for more info)`
* Or should we just hide the message in the stable channel?
    * If we do so, how should we manage the affected UI test files?

See https://github.com/rust-lang/rust/pull/45545#issuecomment-346100450 for detail.

cc @durka

**Comment by steveklabnik** [comment]
We talked about this at the docs team meeting today; there are a variety of opinons, nobody feels super strongly.

However, there is sort of a precendent here with unstable features:

```text
C:\Users\steve\tmp\foo [master +4 ~0 -0 !]> cargo +stable build
   Compiling vs v0.0.1 (file:///C:/Users/steve/tmp/foo)
error: const fn is unstable (see issue #24111)
 --> src\lib.rs:1:1
  |
1 | / pub const fn foo() {
2 | | }
  | |_^

error: aborting due to previous error

error: Could not compile `vs`.

To learn more, run the command again with --verbose.
C:\Users\steve\tmp\foo [master +4 ~0 -0 !]> cargo +nightly build
   Compiling vs v0.0.1 (file:///C:/Users/steve/tmp/foo)
error: const fn is unstable (see issue #24111)
 --> src\lib.rs:1:1
  |
1 | / pub const fn foo() {
2 | | }
  | |_^
  |
  = help: add #![feature(const_fn)] to the crate attributes to enable

error: aborting due to previous error

error: Could not compile `vs`.

To learn more, run the command again with --verbose.
```

Note that stable doesn't show the help, but nightly does. Could we do something like that? Then it'd be consistent.

**Comment by durka** [comment]
I prefer the other approach (and would support changing the general `#![feature]` message to be consistent) for the reason explained in my [PR](https://github.com/rust-lang/rust/pull/46168).
