### ISSUE TITLE
Tracking issue for Box::leak

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#46179]
`#![feature(box_leak)]`

Implemented in #45881.

**Comment by Centril** [comment]
Dumping this link here for future reference: https://github.com/search?utf8=%E2%9C%93&q=leak+extension%3A.rs+language%3ARust&type=Code&ref=advsearch&l=Rust&l=

**Comment by Centril** [comment]
Closing since `Box::leak` is stable in nightly and will make its way to stable in 1.26.0.

**Comment by Gankro** [comment]
I was confused why this was allowed to stabilize, but it appears that [the bug that made this API unsound](https://github.com/rust-lang/rfcs/pull/1233#issuecomment-129096708) was fixed?

**Comment by Centril** [comment]
@Gankro  https://play.rust-lang.org/?gist=66d0329787975630e4f0cc62da61ed46&version=stable&mode=debug

The `dupe` mechanism doesn't work anymore at least.

Should we escalate this to a new issue with P-high?

**Comment by Gankro** [comment]
Nope, just leaving a historical note for anyone else who was confused. Although if anyone knows when this was fixed (and if a test was added?) that would be good to note.
