### ISSUE TITLE
target_feature requires embedded LLVM copy to be usable

### ISSUE THREAD

**Issue by semarie** [rust-lang/rust#46181]
It seems that `target_feature` requires the embedded LLVM copy to populate the available target_features.

`target_features()` in `src/librustc_trans/llvm_util.rs` iterates on whitelisted lists of features, and check for each if the feature is available, using `llvm::LLVMRustHasFeature()`.

The function comes from `src/rustllvm/PassWrapper.cpp`, and will return always `false` if `LLVM_RUSTLLVM` isn't defined. So if the binded LLVM isn't the embedded copy.

I found it when building rustc 1.22 (prestable) as `run-pass/sse2` failed. But firefox-57 depends on `simd` crate and `simd` uses `target_feature`: it makes firefox unbuildable in such situation.

As for distro, it is really a common thing to avoid embedded copy of code, it is really annoying.

**Comment by semarie** [comment]
cc @alexcrichton @nagisa

**Comment by semarie** [comment]
the error I have while building stock firefox-57 on openbsd with rustc 1.22:

```
  --> /data/semarie/repos/openbsd/ports/pobj/firefox-57.0/firefox-57.0/third_party/rust/simd/src/common.rs:17:10
   |
17 | use x86::sse2::common;
   |          ^^^^ Could not find `sse2` in `x86`
```

**Comment by ranma42** [comment]
The limitation was introduced in https://github.com/rust-lang/rust/commit/881a7246606cb6ced8ba63a8d58b7e54fed90b7c

**Comment by cuviper** [comment]
> But firefox-57 depends on simd crate and simd uses target_feature:

Isn't `simd` a nightly-only crate?  How can Firefox be using it?  It's present in `third_party/rust/simd`, but I think that's only as a vendored *optional* dependency for crates like regex.
(It does not appear to be used in Fedora's build of Firefox 57, at least...)

Anyway, AFAIK `MCSubtargetInfo::getFeatureTable()` and `getCPUTable()` are currently the only API changes in rust-lang/llvm.  This wasn't a big deal when they were only informational, used for `rustc --print target-features --print target-cpus`.  But it's more painful if these now affect actual code use.  Have these APIs been proposed upstream to LLVM?

**Comment by semarie** [comment]
it seems the issue was already present with rust-1.21.0: freebsd already saw it: [freebsd bug 223300](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=223300)

at openbsd, rust-1.21.0 was compiled with embedded LLVM. this one with system LLVM. so I only saw it now.

about firefox, it seems that firefox explicitely enable the build with simd for performance reason. see [firefox 1261841](https://bugzilla.mozilla.org/show_bug.cgi?id=1261841)

**Comment by semarie** [comment]
firefox enable nightly features for simd: [config/rules.mk#875](https://dxr.mozilla.org/mozilla-central/source/config/rules.mk#875)

**Comment by cuviper** [comment]
Then Firefox is cheating -- but you still have the option to build it without simd, it seems.

**Comment by semarie** [comment]
with #49428, the problem should be solved. thanks.
