### ISSUE TITLE
target/doc/cargo is almost empty

### ISSUE THREAD

**Issue by behnam** [rust-lang/rust#46195]
We started shipping cargo docs in <https://github.com/rust-lang/rust/pull/45692>, but looks like a problem with the build system is resulting in mdbook generating an empty book, instead of using the source files.

The nightly output is here: <https://doc.rust-lang.org/nightly/cargo/>

**Comment by behnam** [comment]
By the way, would be great to backport the solution to beta, as that one is also broken: https://doc.rust-lang.org/beta/cargo/

**Comment by steveklabnik** [comment]
Ugh, I triple checked this when doing the PR in the first place. I wonder if anything else has changed with the build....

**Comment by steveklabnik** [comment]
Okay so, I just built from scratch and it's absolutely generating the right files. So maybe this is an issue with the infra? Something not getting copied over to doc.rust-lang.org?

@rust-lang/infra

**Comment by alexcrichton** [comment]
@steveklabnik how'd you build the book? Was it maybe not included in the default `./x.py doc`?

**Comment by steveklabnik** [comment]
I... lost it in my shell history, dang. I am pretty sure I did `python x.py doc --stage=1`.

**Comment by steveklabnik** [comment]
```
> rm -r -Fo .\build\x86_64-pc-windows-msvc\doc\
> python x.py doc --stage=1
<nsip>
Rustbook (x86_64-pc-windows-msvc) - rustdoc
Cargo Book (x86_64-pc-windows-msvc) - cargo
Build completed successfully in 0:34:40
> ls .\build\x86_64-pc-windows-msvc\doc\cargo\getting-started\


    Directory: C:\Users\steve\src\rs\build\x86_64-pc-windows-msvc\doc\cargo\getting-started


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       11/29/2017   4:53 PM           9364 first-steps.html
-a----       11/29/2017   4:53 PM           7695 index.html
-a----       11/29/2017   4:53 PM           9683 installation.html

```

So, yep.
