### ISSUE TITLE
Can I replace the backend of compiler?

### ISSUE THREAD

**Issue by 3442853561** [rust-lang/rust#46198]
How do I get the abstract syntax tree?

**Comment by zackmdavis** [comment]
`rustc -Z ast-json my_file.rs` on a nightly build might be what you want?

**Comment by 3442853561** [comment]
@zackmdavis Thank you

**Comment by steveklabnik** [comment]
Questions like this are best posted on https://internals.rust-lang.org/, we try to keep the tracker for bugs only.
