### ISSUE TITLE
Matching on a reference to an enum... issues arising for newbies

### ISSUE THREAD

**Issue by Andrew-Webb** [rust-lang/rust#46208]
A few issues raised by this [SO question](https://stackoverflow.com/questions/36590549/matching-on-a-reference-to-an-enum), certainly for a newbie like me.

1. As the OP says: "It seems like every introductory document for Rust's enum types explains how to match on an enum object that you own.  But what if you do not own the enum object and you just have a reference to it that you want to match against?"  Well, quite!  This had me scratching my head for while, and led me to this SO question.

2. _Does_ the syntax have to be different?  Can the compiler help here?

3. What I've found and noted on SO is that the [idiomatic answer](https://stackoverflow.com/a/36592628/98689) causes an error pertaining to a missing `ref` in one of the arms to be placed on the line containing the `match` keyword.  This isn't helpful as it doesn't identify the errant arm.  The unaccepted and presumably non-idiomatic [answer](https://stackoverflow.com/a/36590693/98689):-

```
match self {
    &Animal::Cat(ref c) => f.write_str("c"),
    &Animal::Dog => f.write_str("d"),
}
```

is better because if the `ref` is omitted from the Cat arm, the compiler will put the error _on that arm_.

**Comment by vitalyd** [comment]
https://github.com/rust-lang/rust-roadmap/issues/24 should make this newbie friendly.

**Comment by sinkuu** [comment]
> What I've found and noted on SO is that the idiomatic answer causes an error pertaining to a missing ref in one of the arms to be placed on the line containing the match keyword.

Error span is on `match`'s line, but the arm missing `ref` seems to be pointed out in "hint" (a `-` is underlining `c`).

```
error[E0507]: cannot move out of borrowed content
  --> src/main.rs:11:15
   |
11 |         match *self {
   |               ^^^^^ cannot move out of borrowed content
12 |             Animal::Cat(c) => f.write_str("c"),
   |                         - hint: to prevent move, use `ref c` or `ref mut c`
```

**Comment by Andrew-Webb** [comment]
@sinkuu, that's true and thanks for pointing that out.  That hint wasn't apparent when I saw the error in Visual Studio Code, as reported by the RLS.  So it's a good thing to run `cargo build` to look at the more detailed error, but I still reckon that the 

```
match self {
    &Animal::Cat(ref c) => f.write_str("c"),
    &Animal::Dog => f.write_str("d"),
}
```

syntax is more helpful right now.
