### ISSUE TITLE
Bootstrap bug

### ISSUE THREAD

**Issue by aristarh2704** [rust-lang/rust#46217]
Bootstraping rustc on cygwin failed, because cygwin use another pathes, than windows.
Cargo cann't build project. It's need fix getting abspath on cygwin.

**Comment by steveklabnik** [comment]
Hi there! It has been a long time, and there's few details in this bug. I'm going to give it a close, but if you're still seeing this issue, please open a new bug with the exact commands you're trying, error messages, and other context. Thanks!
