### ISSUE TITLE
[confusing error message] iterate over str

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#46216]
Given:

```rust
fn main() {
    for c in "foobarbaz" {
        println!("{}", c);
    }
}
```

Rust produces ([playground](https://play.rust-lang.org/?gist=832480c20a7bde6e5371b07610e22358&version=stable)):

```shell
error[E0277]: the trait bound `&str: std::iter::Iterator` is not satisfied
 --> src/main.rs:2:5
  |
2 | /     for c in "foobarbaz" {
3 | |         println!("{}", c);
4 | |     }
  | |_____^ `&str` is not an iterator; maybe try calling `.iter()` or a similar method
  |
  = help: the trait `std::iter::Iterator` is not implemented for `&str`
  = note: required by `std::iter::IntoIterator::into_iter`
```

The suggestion says `iter` or a similar method, but `&str` doesn't have an `.iter()` method (that's why it says "or a similar method").

I don't think this is good enough.

It should scan the methods of `str` that return something that implements `Iterator` (or can be auto-deref to something that implements it) and suggest those. In this case, `chars()`, `bytes()`,... The error message should look more like this:

```shell
error[E0277]: the trait bound `&str: std::iter::Iterator` is not satisfied
 --> src/main.rs:2:5
  |
2 | /     for c in "foobarbaz" {
3 | |         println!("{}", c);
4 | |     }
  | |_____^ `&str` is not an iterator
  |
  = help: the trait `std::iter::Iterator` is not implemented for `&str`
  = note: required by `std::iter::IntoIterator::into_iter`

The following methods of `&str` return an `Iterator`:
  - `chars`
  - `bytes`
  - ... 
```

**Comment by GuillaumeGomez** [comment]
Sounds like an extension of the very controversial methods suggestion. But why not? If other people agree on it, I can add it.

**Comment by zackmdavis** [comment]
(Given that [`for` loops automatically invoke `.into_iter()`](https://doc.rust-lang.org/std/iter/index.html#for-loops-and-intoiterator), it's not clear that we should _ever_ recommend `.iter()` here. (That is, most of the time this "maybe try calling `.iter()` or a similar method" message appears, `.iter()` won't exist, because if it did, the type likely already implements `IntoIterator` too and we wouldn't be in this situation.))

**Comment by zackmdavis** [comment]
The message [comes from `rustc_on_unimplemented`](https://github.com/rust-lang/rust/blob/bbd7932a/src/libcore/iter/iterator.rs#L31-L32), so this would seem to be dependent on #44755.

**Comment by est31** [comment]
I would like such a message

**Comment by estebank** [comment]
```
error[E0277]: the trait bound `&str: std::iter::Iterator` is not satisfied
 --> src/main.rs:2:14
  |
2 |     for c in "foobarbaz" {
  |              ^^^^^^^^^^^ `&str` is not an iterator; try calling `.chars()` or `.bytes()`
  |
  = help: the trait `std::iter::Iterator` is not implemented for `&str`
  = note: required by `std::iter::IntoIterator::into_iter`
```
