### ISSUE TITLE
Cargo does not understand the absolute manifest path

### ISSUE THREAD

**Issue by aristarh2704** [rust-lang/rust#46212]
Cargo build failed, if --manifest-path is absolute path:

$ cargo build --manifest-path /tmp/Cargo.toml
error: manifest path `/tmp/Cargo.toml` does not exist 

While if path is relative, this error does not occur.
My system is i686-pc-windows-gnu.

**Comment by sfackler** [comment]
This should be filed on https://github.com/rust-lang/cargo.
