### ISSUE TITLE
Only allow companies/individuals on `Friends of Rust` which share how they use Rust exactly

### ISSUE THREAD

**Issue by kud1ing** [rust-lang/rust#46235]
There is at least one company on https://www.rust-lang.org/en-US/friends.html where there is no evidence that the company or their developers have used Rust at all: no hint which crates they use, no questions asked in forums how to program in Rust, how to use crates, no known contributions to Rust oder Rust crates - basically only "we use Rust, i promise".

Such entries do neither serve the Rust commmunity, nor people considering to use Rust.

CC @steveklabnik

**Comment by steveklabnik** [comment]
Could you re-file this against https://github.com/rust-lang/rust-www please

**Comment by kud1ing** [comment]
Of course, sorry.
