### ISSUE TITLE
The documented patterns for some compiler builtin macros are subtly incorrect

### ISSUE THREAD

**Issue by ExpHP** [rust-lang/rust#46242]
Example: The macro **`env`** is [documented as](https://doc.rust-lang.org/std/macro.env.html)

```rust
macro_rules! env {
    ($name:expr) => { ... };
}
``` 

when in reality, the following call is legal ([playground](https://play.rust-lang.org/?gist=14ba8df486de80ad63e621d6e353d731&version=stable)):

```rust
let e = env!("PATH",); // <- Note: Trailing comma
```

I believe this is because [the definition in std is just a fake stub](https://github.com/rust-lang/rust/blob/5f44c653cff61d0f55f53e07a188f755c7acddd1/src/libstd/macros.rs#L349-L351). `concat!` and `concat_idents!` (**edit:** also `format_args!`) are in a similar boat (they also support trailing commas in places where the documented pattern suggests they would not).

In all fairness this is not a big deal, and even has the conceivable *benefit* that the documentation is cleaner without such laser precision.  I just thought it was worth making an issue for.

**Comment by steveklabnik** [comment]
> this is not a big deal

it's all good! These should be correct. Happy to take PRs.

**Comment by ExpHP** [comment]
closing since fix was merged
