### ISSUE TITLE
region-liveness-drop-no-may-dangle.rs compilation failure on MIR borrowck

### ISSUE THREAD

**Issue by KiChjang** [rust-lang/rust#46267]
Compiling with -Zborrowck-mir does not reveal the problem, but compiling with -Znll does:

```
error[E0597]: borrowed value does not live long enough (Mir)
  --> /home/keith/Workspace/rust/src/test/mir-opt/nll/region-liveness-drop-no-may-dangle.rs:26:51
   |
25 |     let mut v = [1, 2, 3];
   |         ----- temporary value created here
26 |     let p: Wrap<& /* R1 */ usize> = Wrap { value: &v[0] };
   |                                                   ^^^^^ temporary value dropped here while still borrowed
   |
   = note: consider using a `let` binding to increase its lifetime
```

@arielb1 said that this is due to us having an incorrect MIR borrowck before, and this should really throw a compilation error as seen.

Temporarily disabling this test in order to land my patch at #46100.

cc @nikomatsakis @arielb1 @pnkfelix

**Comment by KiChjang** [comment]
Possibly related to #45537.

**Comment by nikomatsakis** [comment]
@arielb1 can you elaborate on why you think that this test ought to report a compilation error? I don't understand why that is true.

(Among other things, the [code does compile today](https://play.rust-lang.org/?gist=3b468781e740306b99fdc628b56168bd&version=nightly) -- i.e., without NLL etc.)

**Comment by arielb1** [comment]
@nikomatsakis 

The test is not supposed to cause a compilation error. The *bug* is that the test fails to compile with `-Z nll`.

**Comment by nikomatsakis** [comment]
Fixed

**Comment by pnkfelix** [comment]
Wait a minute: does this test work or not? Has it been reenabled on master yet? Is there a latent bug in NLL still?

**Comment by matthewjasper** [comment]
The test was reenabled in #46320.

**Comment by pnkfelix** [comment]
Thanks @matthewjasper sorry for the noise,
