### ISSUE TITLE
Debug impl of Any could be improved

### ISSUE THREAD

**Issue by mzabaluev** [rust-lang/rust#46261]
The `Debug` impl of `Any` is currently very simple, it always returns `"Any"`:

```rust
use std::any::Any;

/// I don't care if this downcasts to a string,
/// it's all "Any" to me.
fn print_any(something: &Any) {
    println!("{:?}", something);
}

fn main() {
    print_any(&String::from("Hello"));
}
```

This shows up in panic messages when e.g. `unwrap()` is called on a `thread::Result` of a panicked thread. The implementation could do what the default panic hook already does and try to downcast the reference to `&'static str` and `String` (and maybe also `Cow<'static, str>`, though that might be very unusual) and, if successful, include the contents into the output or simply delegate to the string's `Debug`.

**Comment by bluss** [comment]
panic! and assert! produce (usually) &str and String, so those would be good to cover.

**Comment by mzabaluev** [comment]
I could create a pull request. What format does the audience prefer? Delegate to the strings' `Debug`, or should `Any` get a mention in the output? `Box` delegates, and I think `Any` should, to.

**Comment by mzabaluev** [comment]
One problem is that `String` is an allocating container defined in liballoc, so it can't be known to the impls in libcore without some low-level hacking. A `Debug` implementation that only downcasts to static strings would leave out any dynamically formatted panic messages and would look more inconsistent than it does now.

**Comment by mzabaluev** [comment]
So perhaps, the `String` downcasting protocol could be defined in libcore to be filled in by the implementation in std or stubs in no_std, similar to how it's done with panicking. Basically, it's one callback for checking against a type id, and another for obtaining the string slice from an `Any` pointer.

**Comment by abonander** [comment]
More discussion here: https://github.com/rust-lang/rfcs/issues/1389

**Comment by mzabaluev** [comment]
@abonander Thank you, I failed to search in the RFC issues.
The powers that be can close this Rust issue now, or maybe keep it around as the tracking issue for an eventual RFC.

**Comment by abonander** [comment]
If we're just talking about changing the internals of an impl, I don't think it needs an RFC. I think most people would be happy with it printing the value if the internal type is `String` or `&str`.

**Comment by mzabaluev** [comment]
The RFC-qualifying issue is that, as libcore does not know anything about owned types, it would need a special-case hook for what liballoc, or conceivably another library in the program's runtime stack, would supply as the typecheck and debug interface for `String`. The `Debug` impl that only prints static panic values would be a glass half empty.

**Comment by abonander** [comment]
I can't think of a way that wouldn't be incredibly hacky or violate coherence. I think a specialized  `impl Debug for Box<Any>` which can downcast to `String` would be a good place to start, since both types are in `alloc`. This lifts the equivalent code out of the panic framework.

**Comment by Mark-Simulacrum** [comment]
I'm going to go ahead and close this as it seems like it's quite hard to do in practice (due to not having the relevant types around). A PR for this would be the best way to land changes here, and discussion can happen on internals.
