### ISSUE TITLE
Empty struct in empty vec: capacity == usize max

### ISSUE THREAD

**Issue by yakoshk** [rust-lang/rust#46279]
```
struct Foo {}
let mut vec: Vec<Foo> = Vec::new();
println!("{}", vec.capacity());
```
output: `18446744073709551615`

**Comment by bluss** [comment]
Hi @yakoshk, is there any reason this should be an issue? The `struct Foo` in this case has size zero, and it is expected that the Vec behaves like this with such elements. It uses no allocation and can store as many elements as fits in its capacity counter.

**Comment by mark-i-m** [comment]
To be clear, though, `vec.len()` should be 0 for an empty Vec, regardless of the type.

**Comment by bstrie** [comment]
@mark-i-im Was that perhaps a mistype? There's no mention to `vec.len()` here.

**Comment by mark-i-m** [comment]
@bstrie Yes, but I thought maybe there might have been confusion between `capacity` and `len`.
