### ISSUE TITLE
Wasm: #[no_mangle] for root level items in leaf crates

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#46294]
All the inline usages of Rust in js that I have seen have this `#[no_mangle]` attribute added to each function.

E.g. see [this example](https://github.com/killercup/wasm-experiments/tree/eb698eaa23f0676d63bfd3521e34c600316b5a20#easy-as-1-2-3) by @killercup , or [this](https://github.com/browserify/rustify/tree/632701d92a5a510da9cd344e3e4179e3f66cd542#usage) one by browserify.

I haven't coded any hybrid js+wasm yet, but to me it seems that having to specify the `#[no_mangle]` attribute in order to access wasm module exports via the [`exports` function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Module/exports) at their original name is a bit of a boilerplate.

So I wonder: can't we add a mode to rustc that allows you to omit the attribute?

Specifically, I would propose that there should be a `-Z root-no-mangle` (eventually -C) flag for rustc which automatically adds a `#[no_mangle]` attribute to any function marked `pub` that is in the root of the crate.

This flag could be added by cargo to the leaf crate, at least in cases where it compiles actual inline Rust. I'm not so sure about larger codebases that are not inlined.

A few points:

* If Rust wants to become the "systems language of the web", the `#[no_mangle]` attribute stands in the way.
* The Rust mangling system was designed with "Rust being used by Rust" in mind. For this, the system is perfect. It keeps the crates outside of each other's way. The only ones to spoil the fun are those native dependencies. Now "Rust being used by Javascript" is a novel use case and I think it deserves the adjustment in mangling patterns.
* Yes, this might cause weird linker errors, e.g. if you include a native C library and it defines a symbol of the same name, but I think this error will be experienced later on, and also, everything should be pure Rust xD.
* One can also think of scenarios where there is no leaf crate but instead js is using various functions from crates on crates.io directly. I think in these cases, there is no leaf crate and thus the flag won't be passed to any crate.
* Possibly one can extend this feature to work on modules as well, aka levelling up the entire public API of the leaf crate by one level. I don't know much about wasm yet to tell whether this makes any sense.

cc @alexcrichton

**Comment by fitzgen** [comment]
cc @rust-lang/wg-wasm

**Comment by koute** [comment]
I think this is a reasonable request for the very specific usecase of putting inline Rust in JavaScript, however I *probably* wouldn't want such a behavior by default for consistency with other targets. (And arguably there *could* be usecases where we'd want to export mangled Rust symbols, e.g. when wasm dynamic linking lands depending on how it would work.)

**Comment by est31** [comment]
Hmm now that we have powerful bindgen like tools I think this is obsolete.
