### ISSUE TITLE
Documentation for `usize::wrapping_sub` mentions undeclared variable

### ISSUE THREAD

**Issue by jeehoonkang** [rust-lang/rust#46308]
Here, "Computes `self - other`" should be "Computes `self - rhs`": https://github.com/rust-lang/rust/blob/dbeb5bf890211608bff5d28c3801c1a217a78d81/src/libcore/num/mod.rs#L644

Similarly for many other methods for `usize`.

**Comment by frewsxcv** [comment]
opened a fix for this: https://github.com/rust-lang/rust/pull/46473/files
