### ISSUE TITLE
Method push on Vec struct

### ISSUE THREAD

**Issue by abjrcode** [rust-lang/rust#46315]
I started learning Rust recently and I was checking the source code for reference so bear with me please.
[Isn't this a bug](https://github.com/rust-lang/rust/blob/master/src/liballoc/vec.rs#L971)?
We are casting the length which is defined as `usize` to `isize`? if not why so?

**Comment by bluss** [comment]
Hi, it's complicated but it should be explained in this RFC's text: https://github.com/rust-lang/rfcs/pull/1966 

I'll close this issue, there are other forums for more ongoing discussion. Feel free to report more bugs here.
