### ISSUE TITLE
Rustdoc doesn't seem to know about `target_feature`

### ISSUE THREAD

**Issue by hdevalence** [rust-lang/rust#46317]
I have a module declared as:

```
#[cfg(all(target_feature="avx2", feature="...", ...))]
pub mod avx2;
```

where ... are various conditions.  Removing the `target_feature` condition results in rustdoc documenting the module when the other conditions are met, but I can't get rustdoc to document the module when the `target_feature` condition is there.  I'm passing the feature to `cargo` as

```
RUSTFLAGS="-C target_feature=+avx2" cargo rustdoc --features "..." -- ...
```

Since the documentation appears exactly when the `target_feature` condition is missing, I suspect that Rustdoc doesn't know about `target_feature`?

**Comment by rkruppe** [comment]
cc #46189

**Comment by QuietMisdreavus** [comment]
Rustdoc gained the `-C`/`--codegen` flag in https://github.com/rust-lang/rust/pull/49956, though you'll need to pass it via `RUSTDOCFLAGS` or at the end of that `cargo rustdoc` invocation for it to apply.
