### ISSUE TITLE
rustbuild: implement per-stage target options

### ISSUE THREAD

**Issue by tamird** [rust-lang/rust#46318]
Currently, it is possible to specify e.g. "linker", "cc", and others per target, but it is not possible to specify which stage those options apply to.

This is mostly useful when options should not apply stage 0.

@alexcrichton

**Comment by tamird** [comment]
I forgot to mention: I'm happy to work on this, I'm just not sure where to plumb the necessary bits.

**Comment by Mark-Simulacrum** [comment]
I think the best way to integrate this would be to add sub-targets for each stage, so we'd have a section `[target.x86_64-unknown-linux-gnu.stage1]` or something like that.

My recommendation would be to implicitly create these from the base (non-stage specific) configurations in the config.toml when converting from `TomlTarget`.  I think you'll have to possibly implement some custom logic for deserialization, but I hope it's not necessary.

Once the configuration changes are implemented, I would expect us to have not a `target -> {cc, linker, etc.}` list but basically `target -> stage N -> {target, cc, ...}`. This would then be used wherever we today use the per-target configs.

I can possibly provide more detailed instructions, but it'll take me more time -- let me know if you want that, and I'd be happy to answer any questions you have.

**Comment by jyn514** [comment]
cc #112678, which is the same thing but for the `rust` section

**Comment by onur-ozkan** [comment]
Closing as duplicated with #112679
