### ISSUE TITLE
Loop label is mistaken for a lifetime in lexer error

### ISSUE THREAD

**Issue by martinhath** [rust-lang/rust#46311]
Consider the following code:
```rust
fn main() {
    'break: loop {
    }
}
```
The loop label is illegal, as it is a reserved keyword. The compiler recognizes this, but the error message claims `'break` to be a lifetime, and not a loop label:
```
   Compiling playground v0.0.1 (file:///playground)
error: lifetimes cannot use keyword names
 --> src/main.rs:2:6
  |
2 |     'break: loop {
  |      ^^^^^

error: aborting due to previous error

error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

I took a quick look in libsyntax, and it seems that the problem is that `'break` and `:` are two tokens, and that we don't figure out that it's a label instead of a lifetime until parsing. 

## Meta
This applies to stable, beta, nightly, and presumably master.

**Comment by AgustinCB** [comment]
I'm taking a look at this.

**Comment by AgustinCB** [comment]
Uhm, I'm a little bit blocked:

How should I do to distinguish whether it's a label or a lifetime?

So far, what I have done is checking if the next character is `:`, however that doesn't really work:

```
impl<'a, 'b: 'a, T: ?Sized+Unsize<U>, U: ?Sized> CoerceUnsized<&'a U> for &'b mut T {}
```

`'b:` there should be a lifetime and not a loop label. I'm thinking, should I parse the next token and check if it's a loop? If so, how do I do that without modifying the current state of the `StringReader`?
