### ISSUE TITLE
Regression: conflicting implementations of trait `std::convert::Into<std::boxed::Box<_>>` for type `Bow<'_, _>`

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#46328]
https://crates.io/crates/bow/1.0.3 contains this impl:

```rust
impl<'a, T: 'a + ToBox + ?Sized> Into<boxed::Box<T>> for Bow<'a, T> {
    fn into(self) -> boxed::Box<T> {
        self.into_box()
    }
}
```

It compiles on nightly-2017-11-27, but fails in nightly-2017-11-28 with:

```rust
error[E0119]: conflicting implementations of trait `std::convert::Into<std::boxed::Box<_>>` for type `Bow<'_, _>`:
   --> src/lib.rs:124:1
    |
124 | / impl<'a, T: 'a + ToBox + ?Sized> Into<boxed::Box<T>> for Bow<'a, T> {
125 | |     fn into(self) -> boxed::Box<T> {
126 | |         self.into_box()
127 | |     }
128 | | }
    | |_^
    |
    = note: conflicting implementation in crate `core`:
            - impl<T, U> std::convert::Into<U> for T
              where U: std::convert::From<T>;
```

Range between the two nighlies: https://github.com/rust-lang/rust/compare/827cb0d61...560a5da9f

https://github.com/rust-lang/rust/pull/44884/commits/c48650ec25d2e7e872912137e68496248743f1fe from https://github.com/rust-lang/rust/pull/44884 sounds maybe relevant. CC @arielb1

**Comment by arielb1** [comment]
That... was not supposed to be a part of this PR, but rather #46192. I'll revert.

OTOH, I think any crate can implement `From<Bow<TheirType>>` for their `TheirType` and cause a coherence conflict, so the new logic is correct.

**Comment by SimonSapin** [comment]
I don’t understand how this could be a conflict. The "source" type in the impl above is `Box<T>`, not `T`.

**Comment by arielb1** [comment]
@SimonSapin 

My bad, I meant
```Rust
impl From<Bow<TheirType>> for Box<TheirType>
```

**Comment by SimonSapin** [comment]
In that impl allowed in a crate defining neither `Bow` nor `Box`?

**Comment by SimonSapin** [comment]
Ariel says on IRC this is a real conflict and the new rustc behavior is meant to stay. The impl above is allowed because `Box` is `#[fundamental]`.

CC @clarcharr, author of this crate.

**Comment by arielb1** [comment]
I reverted the commit so I'll close this issue.
