### ISSUE TITLE
Confusing error when defining constant

### ISSUE THREAD

**Issue by archer884** [rust-lang/rust#46336]
The following error results when attempting to create a constant from some non-constant function:

    error[E0015]: calls in constants are limited to constant functions, struct and enum constructors

This may confuse rustaceans coming from languages where "constructors" are specially defined functions, since, in this case, it refers to `Foo { field: Expression }` rather than, say, `Foo::new()`.

Better phrasing may be `struct and enum literals`?

**Comment by steveklabnik** [comment]
SGTM

**Comment by krk** [comment]
This issue seems to be fulfilled by the merge.

**Comment by estebank** [comment]
@krk that PR wasn't merged. Picking it up and adding a test for it would be enough.
