### ISSUE TITLE
Can't create trait object whose referent is another trait object

### ISSUE THREAD

**Issue by jimblandy** [rust-lang/rust#46337]
I would expect the following code to compile:
```rust
trait T1 { fn f(&self); }
trait T2 { fn g(&self); }

struct S;

impl T1 for S {
    fn f(&self) {
        println!("<S as T1>::f");
    }
}

impl T2 for T1 {
    fn g(&self) {
        println!("<T1 as T2>::g");
        self.f();
    }
}

fn main() {
    let s = &S;

    let t1_object: &T1 = s;
    let t2_object: &T2 = t1_object;
}
```
Instead, Rust doesn't seem willing to carry out the conversion into a trait object:
```console
error[E0308]: mismatched types
  --> src/main.rs:23:26
   |
23 |     let t2_object: &T2 = t1_object;
   |                          ^^^^^^^^^ expected trait `T2`, found trait `T1`
   |
   = note: expected type `&T2`
              found type `&T1`

```
I would have expected this code to build a structure like this:
![image](https://user-images.githubusercontent.com/751272/33332587-7dba442a-d419-11e7-8d51-6b587e74607c.png)

CC @eddyb

**Comment by rkruppe** [comment]
This is because trait objects can't currently be upcasted, see #5665

**Comment by eddyb** [comment]
If you want the data pointer to point to a `&T1` instead of have the same data pointer, you need to coerce `&&T1` to `&T2`, not a `&T1`.

**Comment by vitalyd** [comment]
There’s some discussion of this in https://users.rust-lang.org/t/trait-objects-of-trait-objects/14077

@eddyb, I think the intention here is to keep the data ptr alone but change the vtbl pointer such that T2 method dispatch table is inserted (or rather, replaces T1).  I speculated in https://users.rust-lang.org/t/trait-objects-of-trait-objects/14077/19 why that’s troublesome, but it’s just a speculation.

**Comment by eddyb** [comment]
@vitalyd Sure, that's more common of a desire/harder of a problem, but it's not what's in the image.

Pointing to the location of the `t1_object` variable in memory is a `&&T1`. Either the image is misleading, or you literally have *a reference to a reference* (to a `S`).

**Comment by vitalyd** [comment]
@jimblandy can correct me if I'm wrong, but I believe he thought the code he wrote should, in fact, act as if he had written:
```rust
trait T1 { fn f(&self); }
trait T2 { fn g(&self); }

struct S;

impl T1 for S {
    fn f(&self) {
        println!("<S as T1>::f");
    }
}

impl<'a> T2 for &'a T1 {
    fn g(&self) {
        println!("<&T1 as T2>::g");
        self.f();
    }
}

fn main() {
    let s = &S;

    let t1_object: &T1 = s;
    let t2_object: &T2 = &t1_object;    
}
```
Note the `impl<'a> T2 for &'a T1`, which is what the image represents.  But I think he wanted `impl T2 for T1` to essentially act the same way (I don't think it can, at least presently, as I mentioned in that u.r.l.o comment).  @jimblandy, please correct me if that's wrong.

**Comment by jimblandy** [comment]
My original code was incorrect, and I was sloppy checking the diagram against it --- thanks for your patience. Indeed, it shows the creation of only one reference; making that work means the transition from `S` to `T1` to `T2` would require elaborate vtable synthesis, which isn't what I was looking for at all.

Trying to think this through I've run into a bunch of things I don't quite understand. Let me take a shot at restating this tomorrow.
