### ISSUE TITLE
Compiling with debuginfo causes incorrect output on wasm32-unknown-unknown target

### ISSUE THREAD

**Issue by Herschel** [rust-lang/rust#46339]
The following example will incorrectly return 1 instead of 10 when compiling with the `wasm32-unknown-unknown` target and `-C debuginfo=2`:

```
fn add_one(i: i32) -> i32 {
	i + 1
}

#[no_mangle]
pub fn run() -> i32 {
	add_one(9)
}
```

HTML:
```
<!DOCTYPE html>

<html>
	<head>
		<title>Test</title>
		<script>
			fetch('lib.wasm')
				.then(response => response.arrayBuffer())
				.then(bytes => WebAssembly.instantiate(bytes, {
					'env': {}
				}))
				.then(results => {
				    console.log(results.instance.exports.run());
				});
		</script>
	</head>
	<body>
	</body>
</html>
```

rustc command:
```
rustc lib.rs --crate-type cdylib --target wasm32-unknown-unknown -C debuginfo=2
```
Removing -C debuginfo=2 gives the correct output

rustc version:
```rustc 1.24.0-nightly (560a5da9f 2017-11-27)```

**Comment by alexcrichton** [comment]
This looks to be an LLVM bug fixed in LLVM 5, the upgrade to which is tracked by https://github.com/rust-lang/rust/issues/43370

**Comment by alexcrichton** [comment]
Upon more recent testing I believe this isn't actually fixed in LLVM 5 (an LLVM assertion still trips). To help consolidate though I'm going to close this in favor of https://github.com/rust-lang/rust/issues/46367 which I believe is the same issue.
