### ISSUE TITLE
Rename C-like Enum to Field-less enum

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#46348]
I'm trying to get the official name of "C-like enum" changed to "field-less enum" (or equivalently "enum without fields"). I've gone through a [bikeshedding process on IRLO](https://internals.rust-lang.org/t/proposal-bikeshed-rename-c-like-enumeration/6209), and we've discussed it in the docs meetings. We've got a couple PRs from @notriddle, but need lang-team approval. And also another PR for the nomicon and wherever else we mention C-like enums, which I can handle.

As such, requesting nomination from @rust-lang/lang team.

**Comment by QuietMisdreavus** [comment]
Turning that @rust-lang/lang into a full ping.

Here are the PRs in question:

* https://github.com/rust-lang-nursery/reference/pull/157
* https://github.com/rust-lang/book/pull/1017
* https://github.com/rust-lang/rust/pull/46187

**Comment by withoutboats** [comment]
Unless someone from the lang team posts an objection I think you should consider this fine from our end.

**Comment by nikomatsakis** [comment]
I agree it seems fine.

**Comment by Havvy** [comment]
This has been fixed everywhere except for the nomicon, which has its own PR. So closing this issue as fixed.
