### ISSUE TITLE
Declaring modules inside decl macros 2.0

### ISSUE THREAD

**Issue by valff** [rust-lang/rust#46342]
Not sure if it is a bug or confusing error messages. Consider the following code:
[Playground](https://play.rust-lang.org/?gist=ff756e4bb48142d5b39731d44e9c4dcc&version=nightly)

```rust
#![feature(decl_macro)]

macro impl_mod($name:ident) {
  pub mod $name {
    pub struct Bar;
  }
}

impl_mod!(foo);

use foo::Bar;

fn main() {}
```

Output:
```
error[E0432]: unresolved import `foo::Bar`
  --> src/main.rs:11:5
   |
11 | use foo::Bar;
   |     ^^^^^^^^ no `Bar` in `foo`. Did you mean to use `Bar`?

warning: unused import: `foo::Bar`
  --> src/main.rs:11:5
   |
11 | use foo::Bar;
   |     ^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default
```

What is confusing:
1. So is it unresolved or resolved and unused?
2. "no 'Bar'. did you mean 'Bar'?" - feels like a bug.
3. Path `foo` is accessible, why then `foo::Bar` not?

`rustc --version --verbose`:

```
rustc 1.24.0-nightly (560a5da9f 2017-11-27)
binary: rustc
commit-hash: 560a5da9f1cc7f67d2fc372925aef18c96c82629
commit-date: 2017-11-27
host: x86_64-unknown-linux-gnu
release: 1.24.0-nightly
LLVM version: 4.0
```

**Comment by petrochenkov** [comment]
>``unresolved import `foo::Bar` `` / ``no `Bar` in `foo` ``

Name `Bar` defined in the macro is protected by hygiene 2.0 and cannot be named from the outside, therefore the error. (Name `foo` is defined outside of the macro, so it can be used from outside of the macro as well.)

>Did you mean to use `Bar`?

This is a diagnostic bug, inaccessible names like `Bar` should be filtered away before giving advices.

>``unused import: `foo::Bar` ``

Diagnostic bug as well, erroneous imports should not be reported as unused.

**Comment by valff** [comment]
> Name Bar defined in the macro is protected by hygiene 2.0 and cannot be named from the outside, therefore the error.

Makes sense. But it still can be exported and named by crate consumers. Is it how intended? Maybe a separate bug?

**Comment by petrochenkov** [comment]
>But it still can be exported and named by crate consumers.

Do you mean `foo::Bar` is accessible from other crates?
Then it looks like a bug. `Bar` shouldn't be accessible anywhere outside of `macro impl_mod`.

**Comment by valff** [comment]
> Do you mean foo::Bar is accessible from other crates?
> Then it looks like a bug. Bar shouldn't be accessible anywhere outside of macro impl_mod.

Yes. Then here is a minimal example: https://github.com/valff/hygiene_bug

**Comment by petrochenkov** [comment]
I see.
IIRC, cross-crate hygiene (i.e. storing hygiene related data in metadata of compiled crates) isn't fully implemented yet.

**Comment by valff** [comment]
Ok, now it is clear for me. Thank you for your time!

**Comment by petrochenkov** [comment]
There are some legitimate issues reported here.

**Comment by fmease** [comment]
This no longer emits the incorrect suggestion *did you mean …?*:

```
error[E0432]: unresolved import `foo::Bar`
  --> src/main.rs:11:5
   |
11 | use foo::Bar;
   |     ^^^^^^^^ no `Bar` in `foo`

```

Therefore I consider this fixed unless you'd like to see a note explaining def-site hygiene?
Closing for now but feel free to raise objections and I can reopen it.
