### ISSUE TITLE
Beta regression: References to what's supposed to be static singleton don't pointer compare as equal on 1.23.0-beta.1

### ISSUE THREAD

**Issue by hsivonen** [rust-lang/rust#46371]
Steps to reproduce:

1. `git clone https://github.com/hsivonen/encoding_rs`
2. `cd encoding_rs`
3. `rustup default beta`
4. `cargo test --release`

Actual results:

```
failures:

---- test_labels_names::test_all_labels stdout ----
	thread 'test_labels_names::test_all_labels' panicked at 'assertion failed: `(left == right)`
  left: `Some(Encoding { windows-1252 })`,
 right: `Some(Encoding { windows-1252 })`', src/test_labels_names.rs:11:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- tests::test_label_resolution stdout ----
	thread 'tests::test_label_resolution' panicked at 'assertion failed: `(left == right)`
  left: `Some(Encoding { UTF-8 })`,
 right: `Some(Encoding { UTF-8 })`', src/lib.rs:4419:8
```

Note how left and right in both cases have the same debug stringification.

The [`eq` implementation](https://github.com/hsivonen/encoding_rs/blob/master/src/lib.rs#L2769) assumes that there is [one instance](https://github.com/hsivonen/encoding_rs/blob/master/src/lib.rs#L1181) of each encoding so it's OK to pointer compare them.

Various previous stable channel releases work. Nightly works. Beta works in debug mode. 1.23.0-beta.1 fails in release mode.

[encoding_rs issue](https://github.com/hsivonen/encoding_rs/issues/26), [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1421100#c8)

**Comment by nagisa** [comment]
Will probably be the codegen-units thing. Singleton statics should use linkonce/linkonce_odr linkage, although it is not entirely clear to me whether it is up to user to do so or up to us (the compiler).

cc @michaelwoerister @alexcrichton

**Comment by michaelwoerister** [comment]
Hm, statics should always have external linkage (we don't use `linkonce` or `linkonce_odr` anywhere these days). Maybe the symbol internalizer wrongly decides that it can make multiple internal copies?

**Comment by alexcrichton** [comment]
This may also be related to https://github.com/rust-lang/rust/issues/46239 and fixed by https://github.com/rust-lang/rust/pull/46253, the IR doesn't obviously contain multiple instances of the static here and there's no codegen units involved, so I'd be surprised if the collector came into this!

**Comment by rillian** [comment]
Being fixed by #46253 is possible; I can't reproduce with today's nightly rust. @michaelwoerister, can you make sure that gets into to the next beta, please?

**Comment by nagisa** [comment]
I don't think this was fixed by that PR.

**Comment by michaelwoerister** [comment]
@rillian I'll do a backport of #46253 tomorrow.

@nagisa Do you have an alternative theory?

**Comment by michaelwoerister** [comment]
I cannot reproduce this with the latest beta anymore. Could you give it a try, @hsivonen? 

Also, regarding the question why crater did not find this issue: it seems that crater does not do optimized builds and thus could not have run into this.

**Comment by pnkfelix** [comment]
Note that @arielb1 claimed that #46925 fixed this regression.

(Though, oddly enough, @michaelwoerister 's statement of being unable to reproduce *preceded* that PR landing...)

Anyway, without [triggering a beta `.3` release](https://github.com/rust-lang/rust/issues/46449#issuecomment-354501918) (that would, if I understand correctly, get the latest commit on the beta channel into `rustup`), it might be difficult for users to test out the latest beta...

**Comment by eddyb** [comment]
@pnkfelix There was a backport of #46253 before @arielb1 reverted the layout PR and the bugfix backports related to it, from beta.

**Comment by pnkfelix** [comment]
@eddyb so was @nagisa wrong when [they said](https://github.com/rust-lang/rust/issues/46371#issuecomment-349069720) that they thought #46253 would not fix this?

**Comment by nagisa** [comment]
Yeah, I *probably* was wrong. I didn’t look at the example closely enough before making the statement and forgot to edit it later on. Sorry.

**Comment by hsivonen** [comment]
> Could you give it a try, @hsivonen?

It seems that stable is 1.22.1 and beta is 1.24.0-beta.1. Those both work. Nightly works, too.

What should I tell rustup to test the latest 1.23?

**Comment by michaelwoerister** [comment]
> What should I tell rustup to test the latest 1.23?

Good question. @alexcrichton would know best, I guess?

**Comment by alexcrichton** [comment]
There's info on how to test it in the [prerelease announcement](https://internals.rust-lang.org/t/rust-1-23-0-prerelease-testing/6444), lemme know if it doesn't work though!

**Comment by hsivonen** [comment]
The 1.23.0 release candidate works.

Thank you!
