### ISSUE TITLE
file!() macro return absolute path in doc-test compile

### ISSUE THREAD

**Issue by la10736** [rust-lang/rust#46372]
[This a minimal example](https://github.com/la10736/doc_test_file_bug). Standard compilation resolve `file!()` macro as relative project path but doc-test compilation emit follow error:

```
error: couldn't read "/home/mdamico/temp/doc_test_file_bug/src/..//home/mdamico/temp/doc_test_file_bug/src/lib.rs.bis.rs": No such file or directory (os error 2)
 --> /home/mdamico/temp/doc_test_file_bug/src/lib.rs:1:1
  |
1 | include!(concat!("../", file!(), ".bis.rs"));
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
This behavior involve just `include!()` macro because when used in function or assignment works like as expected

```rust 
///
/// ```
/// assert_eq!("src/lib.rs", file!())
/// ```

/// ```
/// assert_eq!("src/lib.rs", doc_test_file_bug::path())
/// ```
pub fn path() -> &'static str {
    file!()
}

///
/// ```
/// assert_eq!("src/lib.rs", doc_test_file_bug::f)
/// ```
pub static f: &'static str = file!();
```

```
   Doc-tests doc_test_file_bug

running 3 tests
test src/lib.rs - path (line 6) ... ok
test src/lib.rs - f (line 14) ... ok
test src/lib.rs - path (line 2) ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

Now I should disable doc-test to use `file!()` for including some auto-generated code.

**Comment by la10736** [comment]
Sadly this bug is also present when we include an external crate that use `include!()` and `file!()` combo.

**Comment by steveklabnik** [comment]
Triage: this still fails to compile.

**Comment by Swatinem** [comment]
Out of curiousity, I tried the usecase with `cargo +nightly test -Z doctest-in-workspace` (See https://github.com/rust-lang/cargo/issues/9427), as I want to eventually turn that on by default soon, and the works fine with that flag. So assuming I can make that the default behavior after the next release, this should eventually work by 1.72, lets see about that timeline :-)
