### ISSUE TITLE
Turn off name mangling for wasm builds

### ISSUE THREAD

**Issue by jtgeibel** [rust-lang/rust#46389]
Recently I've been playing around with the `wasm32-unknown-unknown` target both locally and on the playground.  So far it has been awesome!

I was thinking that it would be great to see unmangled symbols in the wasm output on the playground.  From the wasm spec ([name section] and [name encoding]) symbol names are encoded in utf8.  Would it be possible to disable name mangling for wasm targets?  This is something I may be able to contribute if pointed in the right direction.

Also, what do you think it would take to enable local variable names in wasm output?

[name section]: https://webassembly.github.io/spec/appendix/custom.html#name-section
[name encoding]: https://webassembly.github.io/spec/binary/values.html#names

cc @shepmaster

**Comment by est31** [comment]
In general, name mangling/prefixing is important so that you don't have collisions. Otherwise this would be an error:

```rust
mod foo {
    fn bar() {}
}
fn bar() {}
```

Or take generic functions, etc.

Disabling mangling for all items (outside of places like the crate root #46294) is not really an option.

However, one could think about beautifying the mangled code such that you have nicer names like `foo::bar`.

**Comment by jtgeibel** [comment]
> However, one could think about beautifying the mangled code such that you have nicer names like `foo::bar`.

Yes, exactly!  I could use [rustc-demangle](https://github.com/alexcrichton/rustc-demangle) to demangle the symbols and they should still be unique.

Symbols appear to include a hash as well.  I'm not sure if there are any situations where the hash is needed for uniqueness.

**Comment by shepmaster** [comment]
The playground [recently started using rustc-demangle](https://github.com/integer32llc/rust-playground/commit/9c495af2ce660c2253e4ea97562f52559cf5a93f) to the assembly output.

One solution would be yet-another postprocessor that converts the WASM / WAST / WABT / WAT, applying the demangling. 

In my wishing world, I'd love for there to be a pure-Rust crate that the playground could replace wasm2wat with. This crate could have the option to demangle at the same time.

**Comment by alexcrichton** [comment]
@jtgeibel an interesting idea! I do think that it may be possible to relax the name mangling in rustc itself, although this would also I think ultimately depend on the linker story and whether LLVM is ready for something like this (not sure if there's accidental baked in assumptions today for example about symbol names). Worth a shot!

**Comment by jtgeibel** [comment]
I've run into an unexpected problem here.  At first I just ripped out most of the sanitation code at the bottom of https://github.com/rust-lang/rust/blob/d8a60c9611399b1b5c9c703b975af4724b432b0d/src/librustc_trans/back/symbol_names.rs#L339

The compiler is able to build itself and my example file when targeting x86_64-unknown-linux-gnu, but I was getting errors and left with `add.add0.rcgu.s` and `add.crate.metadata.rcgu.o` files when trying to target wasm32-unknown-unknown.  It looks like everything is working fine on the rust and llvm side but `s2wasm` is unable to parse the files.

So far I've determined that `<` and `>` are fine but `(`, `)`, and `,` are no good.

@shepmaster I might have a chance to look into something on the playground side in a day or two.  Or maybe `wasm-gc` could demangle symbols.

**Comment by alexcrichton** [comment]
@jtgeibel oh fascinating! Although not entirely surprising as well :)

Eventually we'll move away from `s2wasm` as we get `lld` support which mayfix this problem, but demangling as part of `wasm-gc` seems pretty reasonable actually! If you're curious that stage of parsing the debuginfo sections happens [here](https://github.com/alexcrichton/wasm-gc/blob/f02c07892172d482f87f726f8d9275055b76d573/src/main.rs#L717-L718)

**Comment by alexcrichton** [comment]
I'm going to close this because I believe this has been handled in the meantime with all the changes that have happened since this was first opened.

**Comment by pannous** [comment]
So how can one Turn off name mangling?

please reopen.
