### ISSUE TITLE
Log messages from other crates are not visible when running rustdoc

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#46383]
When invoking a locally-built `rustc` or `rustdoc` compiled with debug assertions, debug messages can be enabled by setting the environment variable `RUST_LOG=debug`.

When invoking `rustc` with `RUST_LOG=debug`, log message will be displayed from all internal crates (e.g. `librustc`, `libsynax`) as expected. However, when invoking `rustdoc` with RUST_LOG=`debug`, only messages from `librustdoc` are displayed, despite many other internal crates being used by `rustdoc`.

**Comment by Mark-Simulacrum** [comment]
I suspect the blame lies somewhere within rustc_driver, but I don't know for sure.
