### ISSUE TITLE
Test name filtering does not allow disambiguating tests with overlapping names

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust#46408]
Consider the following two tests:
```rust
#[test]
fn it_works() { /* ... */ }
#[test]
fn it_works_complexly() { /* ... */ }
```
There is currently no way to run *only* `it_works`, and *not* `it_works_complexly`:
```console
$ cargo t it_works
running 2 tests
test it_works ... ok
test it_works_more ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```
In Go, the filter is a regular expression, so one can use `go test 'it_works$'`, but this not work in Rust (because the test harness presumably just uses simple substring matching):
```console
$ cargo t 'it_works$'
running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 2 filtered out
```

**Comment by malbarbo** [comment]
Try `cargo t it_works -- --exact`.

**Comment by jonhoo** [comment]
Is that documented anywhere outside of `cargo test -- --help`?
I bet most users have never run that, and probably wouldn't even think to (like me :p).

Also, `--exact` is still a limited solution. It requires that I type out the entire test name, and means I can only run a single test this way. For example, I can't avoid running just the `complexly` test here:
```rust
#[test]
fn foo_works() { /* ... */ }
#[test]
fn foo_works_complexly() { /* ... */ }
#[test]
fn bar_works() { /* ... */ }
```

**Comment by cuviper** [comment]
You can also `--skip complexly`.  But I agree it would be nice to have more controls -- if not full regex, maybe just globbing?  Even just being able to specify multiple filters would help.

**Comment by jonhoo** [comment]
Both globbing and multiple filters seem like good solutions!

**Comment by jonhoo** [comment]
I might take a stab at implementing this. A couple of questions though:

 - Is using [`glob`](https://doc.rust-lang.org/glob/) inside of libtest fine?
 - Making this the default is *technically* a backwards-incompatible change (arguments that didn't previously match any tests, like `it*`, may now match tests). However, given that it will only make patterns that previously didn't match match (`?`, `*`, `[`, and `]` aren't allowed in test names) it is unlikely that anything relies on the current behaviour. How would we feel about making globbing the default?
 - Is globbing sufficient? It does address the original concerns outlined above as long as the glob is required to match the entire test name (which is how globs usually behave anyway), but is still more limited than full regexes.
 - Should `--exactly` apply only to the *next* pattern, or to *all* patterns?

Probably cc @rust-lang/tools and maybe @sfackler judging from #38181.

**Comment by jonhoo** [comment]
@cuviper see #46417 if you haven't already.

**Comment by steveklabnik** [comment]
Triage: no changes that I'm aware of.

**Comment by RalfJung** [comment]
> Both globbing and multiple filters seem like good solutions!

Multiple filters already work. You can do `cargo test -- filter1 filter2 --skip f3 --skip f4` to run all tests that contain either (`filter1` and neither `f3` nor `f4`) or (`filter2` and neither `f3` nor `f4`).

For more precise filtering, there's a regex feature request at https://github.com/rust-lang/rust/issues/53278.

**Comment by jonhoo** [comment]
In that case I suppose this issue can be closed, as the case from the original post can be achieved with
```
cargo test -- it_works --skip complexly
```
