### ISSUE TITLE
Move ascii::escape_default to core for no_std support

### ISSUE THREAD

**Issue by ameets** [rust-lang/rust#46409]
It sounds like AsciiExt's methods have been largely moved to individual types, which is great. Would it be possible to move `ascii::escape_default` (escaped version of `u8`) to core?

Reference: https://internals.rust-lang.org/t/std-ascii-in-core/6263/7

**Comment by Phlosioneer** [comment]
Triage: #48735 seems to have addressed this?

**Comment by SimonSapin** [comment]
Yes it has.
