### ISSUE TITLE
Confusing error relating to publicity of tuple struct fields (E0603)

### ISSUE THREAD

**Issue by Restioson** [rust-lang/rust#46407]
I was struggling with a bit of code I wrote:

```rust
// mod_a
pub struct Foo(u64);

// some_other_mod
fn bar() -> ::mod_a::Foo {
    ::mod_a::Foo(10)
}
```

The error I got was:
```
error[E0603]: tuple struct `Foo` is private
```

[Playground.](https://play.rust-lang.org/?gist=ed6ee29b9a8e0ab95b41b1e4edc19f45&version=nightly)

I was tearing my hair out about this -- *why do I get this error? It is public?!*. SuperCuber on the Rust discord helped me out by suggesting I make the *field* public, which solved my problem. 

However, this error is misleading -- it suggests that the struct itself is private, not the field. There should perhaps be a clarifying note suggesting that the field(s) of the struct might need to be made public. It is worth noting that this error changes when you add a `use ::A::Foo`: [playground](https://play.rust-lang.org/?gist=ff1d3f465d66970dc42904681f4b04c9&version=nightly.)
## Meta

Affects rust playground nightly, which I assume is using the latest version.

**Comment by petrochenkov** [comment]
Same as https://github.com/rust-lang/rust/issues/39703

**Comment by Restioson** [comment]
Right, closing.
