### ISSUE TITLE
Compiler panic when returning generator that yields reference

### ISSUE THREAD

**Issue by soro** [rust-lang/rust#46414]
Minimized it as much as possible. Happens when lifetime is elided and generator is returned from method in impl block.

rustc 1.23.0-nightly (e21df8020 2017-11-13) running on x86_64-apple-darwin

[playground example](https://play.rust-lang.org/?gist=1065b7ca7e6f9acbaa790efd43660d72&version=nightly)

**Comment by arielb1** [comment]
This is a duplicate of the impl trait lifetime elision bug, and has been fixed on nightly.
