### ISSUE TITLE
Create a new Rust IDE using Rust and Photon

### ISSUE THREAD

**Issue by Aliuken** [rust-lang/rust#46422]
Now that Mozilla has two great projects as Rust language and Photon Desing System, I think it would be interesting if Mozilla creates a new Rust IDE written in Rust (like Eclipse is written in Java and is used to program in Java) and using Photon UI design.
That would be good both for Rust (specially for its adoption, but also would make its specification to grow) and Photon and Mozilla would have total control over it.

**Comment by leodasvacas** [comment]
That sounds like a cool idea, but this issue tracker is not the best place to discuss it. The user's forum https://users.rust-lang.org/ is more adequate for this discussion.

**Comment by Mark-Simulacrum** [comment]
Yes, discussion on users or internals forums would be better.
