### ISSUE TITLE
Subpar diagnostics: unreachable_code lint fires before match arm coverage check

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#46426]
When you do `#![deny(unreachable_code)]` (which is implied by `#![deny(warnings)]`), the corresponding lint runs and aborts compilation before the match arm coverage check gets a chance to report.

This leads to somewhat confusing messages.
 * at least, they are confusing depending on what the user's mental model is of how `match` expressions should hypothetically behave if they were not forced to cover the domain of the input expression completely

Example:

```rust
#![deny(unreachable_code)]

fn main() {
    let v = vec![1, 2, 3];
    let mut i = v.iter().peekable();
    'label: while let Some(e1) = i.next() {
        
        match e1 {
            &1 => {
                continue 'label;
            }
        }
        println!("e1: {:?}", e1);
    }
}
```

yields the error message ([playpen](https://play.rust-lang.org/?gist=b87da6bf77ea3a48a51c75512dd0e42d&version=stable))

```
error: unreachable statement
  --> src/main.rs:13:9
   |
13 |         println!("e1: {:?}", e1);
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: lint level defined here
  --> src/main.rs:1:9
   |
1  | #![deny(unreachable_code)]
   |         ^^^^^^^^^^^^^^^^
   = note: this error originates in a macro outside of the current crate

error: aborting due to previous error
```

which, when I first look at the code, I think "that `println!` is clearly reachable", because in my head, execution is going to continue past the match expression after that first arm is not matched.

If I change the `deny` to `warn`, I get both the warning as above as well as an error about the non-exhaustive patterns in the match expression, saying that `&_` is not covered.

**Comment by estebank** [comment]
Current output:

```
error: unreachable statement
  --> src/main.rs:13:9
   |
8  | /         match e1 {
9  | |             &1 => {
10 | |                 continue 'label;
11 | |             }
12 | |         }
   | |_________- any code following this `match` expression is unreachable, as all arms diverge
13 |           println!("e1: {:?}", e1);
   |           ^^^^^^^^^^^^^^^^^^^^^^^^^ unreachable statement
   |
note: lint level defined here
  --> src/main.rs:1:9
   |
1  | #![deny(unreachable_code)]
   |         ^^^^^^^^^^^^^^^^
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```
