### ISSUE TITLE
Text from search results overlaps crate menu when scrolling horizontally

### ISSUE THREAD

**Issue by jdm** [rust-lang/rust#46434]
From https://doc.servo.org/servo/index.html?search=contains:
<img width="1552" alt="screen shot 2017-12-01 at 5 08 40 pm" src="https://user-images.githubusercontent.com/27658/33505663-4fd9c550-d6ba-11e7-8e4c-276a8c2fcdeb.png">

**Comment by GuillaumeGomez** [comment]
I can't reproduce this bug, either on firefox or chrome. Any additional information would be very useful in here.

**Comment by jdm** [comment]
I am using Firefox nightly with webrender enabled, so I'll see if those make a difference.
