### ISSUE TITLE
Skin maker BUG : SpinningWheel Alpha problem

### ISSUE THREAD

**Issue by MilosBaskic** [rust-lang/rust#46451]
I am not sure if it is intentional but the spinning wheel's Opacity/Alpha slider does not work.

If it is intentional please tell me, so I know not to wait for a fix, since its messing up my skin.

Best regards.

**Comment by sfackler** [comment]
This is the repository for the Rust programming language, not the Rust game. This should probably be filed over at http://jira.facepunch.com/projects/RUST/issues.
