### ISSUE TITLE
MIR borrowck: error does not know about free/named lifetimes

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#46472]
e.g.

```Rust
fn bar<'a>() -> &'a mut u32 {
    &mut 4
}
```

Gives the following errors for AST and MIR borrowck - the MIR error should be more like the AST error
```
error[E0597]: borrowed value does not live long enough (Ast)
 --> bar.rs:2:10
  |
2 |     &mut 4
  |          ^ does not live long enough
3 | }
  | - temporary value only lives until here
  |
note: borrowed value must be valid for the lifetime 'a as defined on the function body at 1:1...
 --> bar.rs:1:1
  |
1 | / fn bar<'a>() -> &'a mut u32 {
2 | |     &mut 4
3 | | }
  | |_^

error[E0597]: borrowed value does not live long enough (Mir)
 --> bar.rs:3:2
  |
2 |     &mut 4
  |          - temporary value created here
3 | }
  | -^ temporary value dropped here while still borrowed
  | |
  | temporary value needs to live until here
  |
  = note: consider using a `let` binding to increase its lifetime

error: aborting due to 2 previous errors
```

**Comment by nikomatsakis** [comment]
Some mentoring notes:

The error is issued here:

https://github.com/rust-lang/rust/blob/7b637b778db0ec1063662f731773dd7917790a66/src/librustc_mir/borrow_check/mod.rs#L2374-L2382

Note in particular the call to `span_label` at the end:

https://github.com/rust-lang/rust/blob/7b637b778db0ec1063662f731773dd7917790a66/src/librustc_mir/borrow_check/mod.rs#L2381

I think the first thing to add a new parameter to `report_borrowed_value_does_not_live_long_enough`:

https://github.com/rust-lang/rust/blob/7b637b778db0ec1063662f731773dd7917790a66/src/librustc_mir/borrow_check/mod.rs#L2363-L2368

It's going to need access to the borrow that does not live long enough. The callers ought to have a variable `borrow: &BorrowData` in scope, so we can pass that in.

In that case, we can match on `borrow.region`. If we have a `RegionKind::Free` or `RegionKind::EarlyBound`, that corresponds to a named lifetime on the fn, so we don't probably want to emit that call to `span_label` I mentioned earlier. Instead, we want to invoke `err.note`. It might be worth ripgrep'ing through `librustc_borrowck` to find the code that *it* uses to emit its message.

**Comment by Yoric** [comment]
I'm interested in handling this.

**Comment by Yoric** [comment]
Oh, closed? Ok, moving to something else.
