### ISSUE TITLE
Improving an error message: "cannot bind by-move into a pattern guard"

### ISSUE THREAD

**Issue by catamorphism** [rust-lang/rust#4649]
Based on an IRC conversation just now, I can think of two ways to improve this error message:

1. Because pattern guards use the "if" keyword, someone may have written one by accident. Then, if they see this error message, they're going to ask "what's a pattern guard"? The error could explain this (it's a little hard to figure out right now since the entire pattern gets underlined, not the guard).

2. Probably more importantly, the error should suggest what to do to fix it.

The error in question is in ```rustc::middle::check_match```.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#684
