### ISSUE TITLE
ICE: mir/lvalue.rs:433: using operand local _32 as lvalue

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rust#46496]
I'm building rust rev 37a7521ef93b2e2d7a4cd04df38929d841b8ffcc itself using rustc 1.24.0-nightly (1956d5535 2017-12-03).

While the revision I'm building is not the latest (and later ones do build fine), I'm building only stage1, so I think it exposes a bug in the latest nightly.

```sh
rustup default nightly
git checkout 37a7521ef93b2e2d7a4cd04df38929d841b8ffcc
git submodule update
python x.py build src/rustc --stage 1
```

> error: internal compiler error: src/librustc_trans/mir/lvalue.rs:433: using operand local _32 as lvalue

> note: the compiler unexpectedly panicked. this is a bug.

> note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

> note: rustc 1.23.0-dev running on x86_64-apple-darwin

> thread 'rustc' panicked at `Box<Any>`, src/librustc_errors/lib.rs:485:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.

> error: Could not compile `syntax`.

<details> Caused by:
  process didn't exit successfully: `/www/rust/build/bootstrap/debug/rustc --crate-name syntax src/libsyntax/lib.rs --error-format json --crate-type dylib --emit=dep-info,link -C prefer-dynamic -C debug-assertions=off -C overflow-checks=on -C metadata=ff2636296864da21 -C extra-filename=-ff2636296864da21 --out-dir /www/rust/build/x86_64-apple-darwin/stage1-rustc/x86_64-apple-darwin/debug/deps --target x86_64-apple-darwin -L dependency=/www/rust/build/x86_64-apple-darwin/stage1-rustc/x86_64-apple-darwin/debug/deps -L dependency=/www/rust/build/x86_64-apple-darwin/stage1-rustc/debug/deps --extern rustc_cratesio_shim=/www/rust/build/x86_64-apple-darwin/stage1-rustc/x86_64-apple-darwin/debug/deps/librustc_cratesio_shim-27cf8cc65c2a928b.dylib --extern syntax_pos=/www/rust/build/x86_64-apple-darwin/stage1-rustc/x86_64-apple-darwin/debug/deps/libsyntax_pos-ed683b9b9d7b12e9.dylib --extern rustc_data_structures=/www/rust/build/x86_64-apple-darwin/stage1-rustc/x86_64-apple-darwin/debug/deps/librustc_data_structures-bc49bc2a3ce181d9.dylib --extern serialize=/www/rust/build/x86_64-apple-darwin/stage1-rustc/x86_64-apple-darwin/debug/deps/libserialize-b84caf6b1b375ff4.dylib --extern serialize=/www/rust/build/x86_64-apple-darwin/stage1-rustc/x86_64-apple-darwin/debug/deps/libserialize-b84caf6b1b375ff4.rlib --extern rustc_errors=/www/rust/build/x86_64-apple-darwin/stage1-rustc/x86_64-apple-darwin/debug/deps/librustc_errors-a4af62e80c679f98.dylib --extern log=/www/rust/build/x86_64-apple-darwin/stage1-rustc/x86_64-apple-darwin/debug/deps/liblog-0731e78f7028f226.rlib --extern bitflags=/www/rust/build/x86_64-apple-darwin/stage1-rustc/x86_64-apple-darwin/debug/deps/libbitflags-575e997211942460.rlib` (exit code: 101)
thread 'main' panicked at 'command did not execute successfully: "/www/rust/build/x86_64-apple-darwin/stage0/bin/cargo" "build" "--target" "x86_64-apple-darwin" "-j" "8" "--features" " jemalloc llvm" "--manifest-path" "/www/rust/src/rustc/Cargo.toml" "--message-format" "json"
expected success, got: exit code: 101', src/bootstrap/compile.rs:882:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failed to run: /www/rust/build/bootstrap/debug/bootstrap build src/rustc --stage 1
</details>

**Comment by jyn514** [comment]
This has been fixed sometime in the last 4 years; I don't think we need to track down the exact cause.
