### ISSUE TITLE
Tracking issue for extra Duration methods

### ISSUE THREAD

**Issue by clarcharr** [rust-lang/rust#46507]
Right now, we have `from_secs`, `from_millis`, and `from_micros`, and also `as_secs` and `subsec_nanos`.

It makes sense to also add `from_nanos`, `subsec_micros`, and `subsec_millis`.

**Comment by clarcharr** [comment]
@sfackler this should be marked as a tracking issue now

**Comment by sfackler** [comment]
Done!

**Comment by SimonSapin** [comment]
Looks good to me to stabilize.

@rfcbot fcp merge

**Comment by axos88** [comment]
I feel like `subsec_*` methods have limited use. 
I find myself interested in converting the whole duration value to e.g. millis most of the time rather than interested in only the fractional part.
I would propose to add as_millis, as_micros, as_nanos, etc. conforming with the from_* methods.

**Comment by birkenfeld** [comment]
And similarly, for formatting/display purposes, `as_floating_secs` etc would be helpful.

**Comment by xfix** [comment]
I know it's late, but I wonder if it shouldn't use u128 and i128 instead.

**Comment by icefoxen** [comment]
@xfix I'm not involved in this decision but it appears that 2^64 seconds is about 42x the age of the universe.  So, `u64` is Probably Enough For Anyone.  :-P

**Comment by retep998** [comment]
Yeah but `from_nanos` is 2^64 nanoseconds, not seconds, which is only about 585 years. That's really short. A partially compatible change would be to make it take a generic type parameter of either `u128` or `u64` but that could have subtle inference changes.
