### ISSUE TITLE
Safe API for constructing enum from an integer

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust#46529]
Creating an enum from an integer the long way using match on the integer is an awful proposition. It's long, requires keeping it in sync with the enum, and is error-prone:

```rust
enum Color {
Red = 1,
Green = 2,
Blue = 3,
};

match num {
1 => Color::Blue,
2 => Color::Green,
3 => Color::Red,
}
```

Because Rust doesn't have a safe 1-liner, I've used seemingly-innocent `transmute` instead, which lead to [an awful bug](https://github.com/rust-lang/rust/issues/46458).

Rust really should have a built-in API that constructs a (field-less) enum from an integer. It could be `TryFrom` or something else that returns `Option<Enum>` (and of course `None` if the integer is not a valid value).

**Comment by mattico** [comment]
I agree that this would be nice to have in the standard library, but for now https://crates.io/crates/enum-primitive-derive works.

**Comment by Mark-Simulacrum** [comment]
Closing. If someone wants to pursue this, please follow the RFC process here https://github.com/rust-lang/rfcs#before-creating-an-rfc. The language itself is somewhat unlikely to offer something like this in the near term future, especially as crates can do so on their own (and quite well).

**Comment by partheseas** [comment]
For those that might still come across this issue in search of a way to do this, the crate that @mattico mentioned above seems to no longer be maintained. [num_enum](https://crates.io/crates/num_enum) seems to be the new go-to for this functionality.

    use num_enum::TryFromPrimitive;
    use std::convert::TryFrom;

    #[derive(Debug, TryFromPrimitive)]
    #[repr(usize)]
    enum ShirtSize {
        Small,
        Medium,
        Large,
        XLarge
    }

    fn buy_shirt(int_size: usize) {
        match ShirtSize::try_from(int_size) {
            Ok(size) => println!("Ordering a size {} shirt.", size),
            Err(_) => println!("We don't make those shirts!")
        }
    }

**Comment by Jimmy-Z** [comment]
It's appalling such a primitive function is left out to be implemented by an external crate.
https://xkcd.com/2347/

**Comment by sffc** [comment]
"Appalling" is an understatement, in my opinion.

`<rant>` Every other programming language that has enums, including C++ and Java, support mostly-transparent conversion between int and enum. *There **is** a well-defined conversion;* but Rust forces us to use unsafe code for it! Enums are an abstract concept that are mapped into ints when compiled into assembly code. Just like chars! A char is basically a repr(u32) enum with gaps. If one argues that int <-> enum is a problem to be solved by crates, then that leads to saying that chars and strings should be solved by crates, too! It's shocking, really, that Rust decided that UTF-8 was going to go into the core language, but not int <-> enum, which is *even more fundamental* of an operation than UTF-8. `</rant>`

**Comment by silverweed** [comment]
Is there still no convenient way of constructing a `repr(u*)/repr(i*)` enum from the underlying integer type? I would expect it to be possible to have a blanket `TryFrom` implementation that checks the validity of the input and returns the appropriate enum value. Am I missing something?

In my projects I usually fall back to `assert!(/* in range */)` + `transmute`, which is better than including a whole new crate just for that, but it doesn't feel right I have to resort to `unsafe` code for such a seemingly innocent task.
