### ISSUE TITLE
Move `Duration` type to libcore

### ISSUE THREAD

**Issue by clarcharr** [rust-lang/rust#46520]
Right now there isn't anything that requires keeping this type in libstd, and it may be useful for libraries that work with time in a `no_std` context. It makes sense to move this type to libcore.

**Comment by bstrie** [comment]
I thought that all types in libstd were there for a reason, is there a historical reason that this was left in? Should we audit libstd for other types that don't need to be there?

**Comment by clarcharr** [comment]
@bstrie everything in `libcore` is also in `libstd`, more or less. `libcore` is just a smaller version of `libstd` that doesn't rely on platform-specific behaviour at all.

I do think that `libstd` should be audited for types that can be moved to `libcore`; this is just one case of that.

**Comment by Mark-Simulacrum** [comment]
I think a PR for this would be reasonable. Marking as feature-accepted.
