### ISSUE TITLE
src in rust docs has blank left sidebar that overlaps code

### ISSUE THREAD

**Issue by retep998** [rust-lang/rust#46534]
![](https://i.imgur.com/oM1zkyG.png)

As of filing this issue, it exists on current nightly but not current beta.

cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Easy fix. I'll write it today or tomorrow.

**Comment by Havvy** [comment]
This is already fixed with #46502

**Comment by GuillaumeGomez** [comment]
Oh indeed!
