### ISSUE TITLE
pub statics are not exported in WASM

### ISSUE THREAD

**Issue by dylanede** [rust-lang/rust#46546]
If I have a crate like this:

```rust
#[no_mangle]
pub fn add_one(x: i32) -> i32 {
    x + 1
}

#[no_mangle]
pub static FOO: [u8; 15] = *b"Goodbye world!\0";
```

compiling this to WASM (with crate type cdylib) produces a module that contains an export for `add_one`, but not `FOO`. Is this something I'm doing wrong or is this meant to work?

I've tried the `-export-dynamics` linker flag. This adds lots of other symbols, but not `FOO`.

**Comment by alexcrichton** [comment]
Thanks for the report!

I think this may just not be supported by wasm right now? I think it may be able to export integers and such (which also doesn't appear to work) but AFAIK you can't export arbitrary chunks of memory just yet.

**Comment by alexcrichton** [comment]
A pretty huge amount has changed since this was first opened, and it's clear now that statics don't work as globals in wasm, so this is a construct that isn't supported in the wasm format.
