### ISSUE TITLE
incr.comp.: Load dep-graph in the background

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#46555]
The dependency graph is loaded at the earliest point possibly during the compilation session (after the crate disambiguator has been set):
https://github.com/rust-lang/rust/blob/bd7021fd57ad595711aaaaba03e0a058cf931056/src/librustc_driver/driver.rs#L654

However, it is only needed for the first time a few passes later:
https://github.com/rust-lang/rust/blob/bd7021fd57ad595711aaaaba03e0a058cf931056/src/librustc_driver/driver.rs#L890

This was intentional so that we have to possibility to load and decode it the graph on a background thread. One way to implement this is to make `rustc_incremental::load_dep_graph()` start a new thread and return the `thread::JoinHandle` and then only join that thread right before the dep-graph is actually needed.

**Comment by Yoric** [comment]
I'll try and do that.

**Comment by michaelwoerister** [comment]
@Yoric Cool, thank you!
