### ISSUE TITLE
Compiler complaining about try on Result

### ISSUE THREAD

**Issue by alanhkarp** [rust-lang/rust#46575]
I have a variable foo of type std::sync::mpsc::Receiver\<Qux\>.  When I do 
<pre> let bar = foo.recv()?;</pre> I get a compiler error "the `?` operator can only be used in a function that returns `Result`"

When I do
<pre>let bar = foo.recv();</pre> I get a compiler error where I use bar telling me that its type is Result.  For what it's worth, IntelliJ tells me the type of foo.recv() is Result.  I have many other places in my program where I don't have this problem with recv().  I'm running rustc 1.21.0 (3b72af97e 2017-10-09).

**Comment by sfackler** [comment]
What does the function you're calling recv in return?

**Comment by alanhkarp** [comment]
Here's a minimal subset of the actual code that shows the problem.

    fn listen(&self, status: LinkToPort, link_from: LinkFromPort) -> Result<JoinHandle<()>, Error> {
        let join_handle = ::std::thread::spawn( move || {
        loop {
            let packet = link_from.recv()?; 
            println!("{}", packet);
        }
        });
        Ok(join_handle)
    }

**Comment by sfackler** [comment]
The closure provided to `thread::spawn` doesn't return a `Result`.

**Comment by alanhkarp** [comment]
My bad.  It's a mistake I've made in other places, but not in a closure.  I
saw the Result on the function and never thought to look at the closure.
Lesson learned.


--------------
Alan Karp
