### ISSUE TITLE
Don't use `{{root}}` in diagnostics

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#46577]
E.g., ``` error[E0433]: failed to resolve. Could not find `foo` in `{{root}}` ```. I think this is only an issue when macros are involved. In this case, `{{root}}` is not helpful because it is not clear which crate rustc is looking in. It is also ugly. It would be better to say "the root of crate bar" or something similar.

**Comment by estebank** [comment]
The only test that produces `{{root}}` at the moment is

```
error[E0433]: failed to resolve: could not find `xcrate` in `{{root}}`
  --> $DIR/non-existent-2.rs:14:15
   |
LL |     let s = ::xcrate::S;
   |               ^^^^^^ could not find `xcrate` in `{{root}}`
```

**Comment by rylev** [comment]
This is no longer the case:
```
error[E0433]: failed to resolve: could not find `xcrate` in the list of imported crates
 --> src/main.rs:2:15
  |
2 |     let s = ::xcrate::S;
  |               ^^^^^^ could not find `xcrate` in the list of imported crates
```

Going to close as there currently no tests that include `{{root}}`. Feel free to reopen if there are any more cases where `{{root}}` is actually used.
