### ISSUE TITLE
must-compile-successfully ignored by ui tests

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#46587]
From what I can tell, ui tests that don't have any `//~ ERROR` annotations and have no stderr file are implicitly assumed to require successful compilation. We ought to reject such tests, and instead require an explicit `// must-compile-succesfully` comment.

Here are some mentoring instructions. The file that controls the test suite is [`runtest.rs`](https://github.com/rust-lang/rust/blob/ab79caa828cf955e658faa4386cf9e8e0a8c3e28/src/tools/compiletest/src/runtest.rs). UI tests in particular are controlled by `run_ui_test()`:

https://github.com/rust-lang/rust/blob/ab79caa828cf955e658faa4386cf9e8e0a8c3e28/src/tools/compiletest/src/runtest.rs#L2381-L2448

You can see that it begins with a call to `compile_test`, but it does not inspect the return value from that function. In contrast, `compile-fail` tests check and -- if compilation is successful -- they require that a `must_compile_successfully` comment is present:

https://github.com/rust-lang/rust/blob/ab79caa828cf955e658faa4386cf9e8e0a8c3e28/src/tools/compiletest/src/runtest.rs#L153-L163

We want to do something similar, but in the `run_ui_test` function. This will likely reveal existing tests that need a `// must-compile-successfully` comment.

**Comment by nikomatsakis** [comment]
cc @oli-obk, who did the awesome work towards respecting `//~ ERROR` annotations

**Comment by tommyip** [comment]
I can work on this!

**Comment by nikomatsakis** [comment]
@tommyip great =)

**Comment by tommyip** [comment]
@nikomatsakis  Ok so these are the tests that implicitly compiles, some of which contains the flag `run-pass`.
```
ui/check_match/issue-43253.rs
ui/codemap_tests/unicode_3.rs
ui/deprecated-macro_escape-inner.rs  // run-pass
ui/deprecated-macro_escape.rs  // run-pass
ui/deriving-meta-empty-trait-list.rs  // run-pass
ui/enum-size-variance.rs  // run-pass
ui/explain.rs
ui/hello_world/main.rs
ui/issue-19100.rs  // run-pass
ui/issue-43806.rs  // run-pass
ui/lint/command-line-lint-group-allow.rs
ui/lint/command-line-lint-group-warn.rs
ui/lint/not_found.rs
ui/lint/unreachable_pub-pub_crate.rs
ui/lint/unreachable_pub.rs
ui/lint/unused_parens_json_suggestion.rs
ui/macros/trace-macro.rs
ui/nll/closure-requirements/propagate-approximated-ref.rs
ui/nll/closure-requirements/propagate-approximated-shorter-to-static-no-bound.rs
ui/nll/closure-requirements/propagate-approximated-shorter-to-static-wrong-bound.rs
ui/nll/closure-requirements/propagate-approximated-val.rs
ui/nll/closure-requirements/propagate-despite-same-free-region.rs
ui/nll/maybe-initialized-drop-uninitialized.rs
ui/path-lookahead.rs  // run-pass
ui/print-fuel/print-fuel.rs
ui/print_type_sizes/anonymous.rs
ui/print_type_sizes/generics.rs
ui/print_type_sizes/multiple_types.rs
ui/print_type_sizes/niche-filling.rs
ui/print_type_sizes/no_duplicates.rs
ui/print_type_sizes/packed.rs
ui/print_type_sizes/padding.rs
ui/print_type_sizes/repr-align.rs
ui/print_type_sizes/uninhabited.rs
ui/print_type_sizes/variants.rs
ui/reachable/expr_andand.rs
ui/reachable/expr_oror.rs
ui/rfc_1940-must_use_on_functions/fn_must_use.rs
ui/span/macro-span-replacement.rs
ui/span/multispan-import-lint.rs
ui/span/unused-warning-point-at-signature.rs  // run-pass
ui/test-should-panic-attr.rs  // run-pass
```

Should we enforce `// must-compile-successfully` in the ones with the run-pass flag?

**Comment by oli-obk** [comment]
I think run-pass should imply the must-compile-successfully flag

**Comment by tommyip** [comment]
Oh actually I think we can just replace the run-pass flag?
```rust
    // The test must be compiled and run successfully. Only used in UI tests for
    // now.
    pub run_pass: bool,
```
