### ISSUE TITLE
Second edition book: missing info on Array initialization

### ISSUE THREAD

**Issue by nicktime** [rust-lang/rust#46594]
Not explained how to declare and initialize zero-filled buffers like it's done in the first edition:
`let a = [0; 20];`
PS Probably worth adding a link to "Array" section in "Reference".

**Comment by jedsmith** [comment]
It does show up in chapter 20:

https://doc.rust-lang.org/book/second-edition/ch20-01-single-threaded.html#reading-the-request

**Comment by steveklabnik** [comment]
Issues for the book should be filed over here please! https://github.com/rust-lang/book

**Comment by nicktime** [comment]
@steveklabnik https://www.rust-lang.org/en-US/contribute-docs.html says "Most in-tree documentation lives in the src/doc directory. These are all covered by the A-docs label on that issue tracker." And the URL points here https://github.com/rust-lang/rust/issues?q=is%3Aopen+is%3Aissue+label%3AA-docs

**Comment by steveklabnik** [comment]
Great. I'll file an issue on the website about that, thanks! The very first page of the book points to the right place.

> And it's not explained actually, it's just mentioned there like it was explained before, but it wasn't.

I didn't say it wouldn't be worth filing! We can't change the early chapters for version 2, but maybe for version 3.

**Comment by nicktime** [comment]
> I'll file an issue on the website 
Ok, thanks.

> I didn't say it wouldn't be worth filing!
Oh, ok, I'll post it to rust-lang/book then.
