### ISSUE TITLE
doc: Degraded usefulness of search results

### ISSUE THREAD

**Issue by panicbit** [rust-lang/rust#46595]
Compare these search results in `1.22.1` and `nightly (ad3543db3 2017-12-08)`:

![search](https://user-images.githubusercontent.com/628445/33793100-36f18094-dcb1-11e7-9bd3-2da8197553f0.png)
No results, even though there are trivial and useful matches.

![search2](https://user-images.githubusercontent.com/628445/33793132-c7fa8fe0-dcb1-11e7-8e4c-2797b4aa4e54.png)
Irrelevant results. Most relevant results are offscreen, two pages down.

**Comment by GuillaumeGomez** [comment]
That's problematic, indeed. I'll add another check for "starts_with" or something along the lines.
