### ISSUE TITLE
`panic_fmt` receiving bogus arguments in freestanding environment

### ISSUE THREAD

**Issue by Ketsuban** [rust-lang/rust#46600]
I came across this in a hobby OS where it caused a system fault, but I *think* I've pared it back about as much as it'll go to produce a one-file test case which produces a segfault.

```rust
#![feature(lang_items)]
#![no_main]
#![no_std]

extern crate libc;

use core::fmt::Write;

struct Writer;

impl core::fmt::Write for Writer {
    fn write_str(&mut self, s: &str) -> ::core::fmt::Result {
        unsafe {
            libc::puts(s.as_ptr() as *const libc::c_char);
        }
        Ok(())
    }
}

#[no_mangle]
pub extern "C" fn main(_argc: i32, _argv: *const *const u8) -> i32 {
    panic!("Hello, world!");
}

#[no_mangle]
pub extern "C" fn _Unwind_Resume() {}

#[lang = "panic_fmt"]
#[no_mangle]
pub fn panic_fmt(fmt: ::core::fmt::Arguments, file: &'static str, line: u32, col: u32) -> ! {
    Writer
        .write_fmt(format_args!(
            "PANIC in {} on line {}, column {}\n\0",
            file, line, col
        ))
        .unwrap();
    Writer.write_fmt(format_args!("    {}\n\0", fmt)).unwrap();
    loop {}
}
```

Compile this with `panic = "abort"` using a nightly compiler. Here's mine.

```
$ rustc --version --verbose
rustc 1.24.0-nightly (c8ddf2852 2017-12-07)
binary: rustc
commit-hash: c8ddf28527119a06a9f5da9bd34c97ae97afe531
commit-date: 2017-12-07
host: x86_64-unknown-linux-gnu
release: 1.24.0-nightly
LLVM version: 4.0
```

Here's the output I get.

```
$ target/debug/nostd_test
PANIC in  on line , column 

Segmentation fault (core dumped)
```

Here's what I expected.

```
$ target/debug/nostd_test
PANIC in main.rs on line 22, column 5
    Hello, world!
```

In my OS I do actually get output for `line` (4) and `col` (12), and `file` is printed if I use `{:#p}` (0x000000000000000c), whereas in my test case there's nothing at all.

**Comment by sfackler** [comment]
`panic_fmt` is declared `pub extern fn panic_fmt` in libstd: https://github.com/rust-lang/rust/blob/f861b6ee46465097eec266c160ac53e230df7cf0/src/libstd/panicking.rs#L492 so I think this is a calling convention problem?

**Comment by Ketsuban** [comment]
I could have sworn I'd tried that and ruled it out but I just did and it works, so this falls under "if you still can't get it to work, it's a combination you think you tried before but didn't". Thanks!
