### ISSUE TITLE
Bitflags pollute error message with its version of `ops::FnOnce`

### ISSUE THREAD

**Issue by EPashkin** [rust-lang/rust#46619]
When I run this code on playground
```rust
extern crate bitflags;

fn foo<F: FnOnce() + Send + 'static>(f: F) -> Box<FnOnce() + Send + 'static> {
    Box::new(f)
}

fn main() {
    let f = foo(|| println!("meh"));
    f();
}
```
I see expected result only on stable
```
error[E0161]: cannot move a value of type std::ops::FnOnce() + std::marker::Send: the size of std::ops::FnOnce() + std::marker::Send cannot be statically determined
 --> src/main.rs:9:5
  |
9 |     f();
  |     ^
```
On beta and nighlty I see
```
error[E0161]: cannot move a value of type bitflags::<unnamed>::ops::FnOnce() + bitflags::<unnamed>::marker::Send: the size of bitflags::<unnamed>::ops::FnOnce() + bitflags::<unnamed>::marker::Send cannot be statically determined
 --> src/main.rs:9:5
  |
9 |     f();
  |     ^
```

This bug repeated on my local machine on both stable and nightly:
rustc 1.22.1 (05e2e1c41 2017-11-22)
binary: rustc
commit-hash: 05e2e1c41414e8fc73d0f267ea8dab1a3eeeaa99
commit-date: 2017-11-22
host: x86_64-pc-windows-gnu
release: 1.22.1
LLVM version: 4.0

rustc 1.24.0-nightly (0a2e9ade8 2017-11-29)
binary: rustc
commit-hash: 0a2e9ade83ff253bb489c63a95b1f499c5e0916f
commit-date: 2017-11-29
host: x86_64-pc-windows-gnu
release: 1.24.0-nightly
LLVM version: 4.0

**Comment by sinkuu** [comment]
#46112?

**Comment by EPashkin** [comment]
Oh sorry, only difference that it also broken on 1.22.1
