### ISSUE TITLE
Diffs from UI tests are noisy when line numbers change

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#46643]
Here's a typical example: https://github.com/rust-lang/rust/pull/46640

One line added at the start of the test source (`// must-compile-successfully`) causes changes in all line numbers in the test's output.
```diff
 warning: unreachable pattern
-  --> $DIR/issue-43253.rs:37:9
+  --> $DIR/issue-43253.rs:39:9
    |
-37 |         9 => {},
+39 |         9 => {},
    |         ^
    |
 note: lint level defined here
-  --> $DIR/issue-43253.rs:12:9
+  --> $DIR/issue-43253.rs:14:9
    |
-12 | #![warn(unreachable_patterns)]
+14 | #![warn(unreachable_patterns)]
    |         ^^^^^^^^^^^^^^^^^^^^
 
 warning: unreachable pattern
-  --> $DIR/issue-43253.rs:43:9
+  --> $DIR/issue-43253.rs:45:9
    |
-43 |         8...9 => {},
+45 |         8...9 => {},
    |         ^^^^^
 
 warning: unreachable pattern
-  --> $DIR/issue-43253.rs:49:9
+  --> $DIR/issue-43253.rs:51:9
    |
-49 |         9...9 => {},
+51 |         9...9 => {},
    |         ^^^^^
```

There are probably tests in which specific values of line numbers are important, but maybe they can be replaced with some placeholder by default?

**Comment by oli-obk** [comment]
We could filter out line numbers, but then moving something across the line 9/10 border will still produce noise because of the additional indent

To make sure that tests where line numbers are important still can be tested we could have a flag that skips the filter step

**Comment by oli-obk** [comment]
Alternatively we could replace line numbers by line offsets to the previous diagnostic's line number.

**Comment by petrochenkov** [comment]
>moving something across the line 9/10 border will still produce noise because of the additional indent

Any line number can be replaced with a constant-width placeholder: `1` => `LL`, `12` => `LL`, `123` => `LL`, `$DIR/issue-43253.rs:39:9` => `$DIR/issue-43253.rs:LL:CC` and the replacement can be performed by rustc before (or during) diagnostics formatting under a debug option.

>To make sure that tests where line numbers are important still can be tested we could have a flag that skips the filter step

Yes, that's what I meant by "by default".

>Alternatively we could replace line numbers by line offsets to the previous diagnostic's line number.

This mostly solves the noise problem, but I suspect the resulting numbers will be more misleading than actually useful.

**Comment by kennytm** [comment]
We could introduce a flag (or the opposite of it)

```rust
// redact-line-numbers
```

then during the normalization step, it will replace all `\.rs:\d+:\d+` by `.rs:$L:$C` and all `^\d+\s+\|` by `$L |`. 

However, the line 9/10 problem still happens due to alignment:

```
error[E0322]: explicit impls for the `Sized` trait are not permitted
 --> src/main.rs:7:1
  |
7 | / impl Sized for u32 {
8 | | }
  | |_^ impl of 'Sized' not allowed

error[E0322]: explicit impls for the `Sized` trait are not permitted
  --> src/main.rs:9:1
   |
9  | / impl Sized for u64 {
10 | | }
   | |_^ impl of 'Sized' not allowed
```

Note the column position of the arrow `-->` and vertical bar for the error happening on line 7 and line 9. This can't be avoided unless we can instruct `rustc` to always reserve 3 digits in the gutter (or find some way to tell rustc to start counting from line 100).

**Comment by oli-obk** [comment]
I think the best solution would be the unstable compiler flag that does the replacement upfront.

**Comment by arielb1** [comment]
Don't we want to keep line numbers for at least the headers, to prevent confusion if error messages are reordered?
