### ISSUE TITLE
contributing to docs should point out that the book is separate

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#46656]
https://www.rust-lang.org/en-US/contribute-docs.html

> The Book is the primary documentation for Rust, maintained in the main repository. It has its own issue label, A-book and is continually being refined.

this is not true, as it's in its own repo

discovered in https://github.com/rust-lang/rust/issues/46594

**Comment by frewsxcv** [comment]
opened a pull request for this https://github.com/rust-lang/rust-www/pull/1061
