### ISSUE TITLE
Implement `zip_with` for Iterators

### ISSUE THREAD

**Issue by vbrandl** [rust-lang/rust#46654]
Hi,
In addition to the `zip` method for iterators, I think it would be great to have a `zip_with` method, that takes a function as parameter that gets applied to the iterator values.
From my understanding it is required for the `conservative_impl_trait` feature to become stable first but after that, the method might look like this:
```rust
fn zip_with<C, F, U>(self, combo: F, other: U) -> impl Iterator<Item = C>
where
    U: IntoIterator,
    F: Fn(Self::Item, U::Item) -> C,
{
    self.zip(other.into_iter()).map(move |(s, o)| {
        combo(s, o)
    })
}
```
I imagine zipping, than mapping to be a pretty common use case, so that method might be a pretty useful addition to the stdlib.

**Comment by leonardo-m** [comment]
This is nice, but it's easy to replace this with zip().map(). So I think there are iterators less easy to implement that should be added before this zip_with (like permutations, combinations, cartesian product, pairwise, sorted, etc).

**Comment by ExpHP** [comment]
Speaking as somebody who does an awful lot of zipping and mapping, and who often implements similar operations as the core of mathematical libraries, I'm almost certain that I have implemented more or less exactly this in the past.

And my experience from using it is that **`zip_map` simply doesn't pull its weight.**  Not in Rust.

It saves you from having to type the tuple parentheses inside your closure, sure... but for the most part, that's *it.*  It still has all the awkward asymmetry of `zip` (and frankly it's even *more* awkward).  You still need to use zip if you want to zip three iterators.  If you expect it will save you from lots of silly near-eta expansions like `.map(|(a, b)| f(a, b))`, I invite you to take a close look at your codebase and count how many times you've actually written `.map(|(a, b)| f(a, &b))` or `.map(|&(ref a, b)| f(a, b))`.

> From my understanding it is required for the `conservative_impl_trait` feature to become stable

[That](https://doc.rust-lang.org/std/iter/struct.Map.html) [hasn't](https://doc.rust-lang.org/std/iter/struct.Filter.html) [stopped](https://doc.rust-lang.org/std/iter/struct.Cloned.html) [the](https://doc.rust-lang.org/std/iter/struct.FilterMap.html) [stdlib](https://doc.rust-lang.org/std/iter/struct.Enumerate.html) [before](https://doc.rust-lang.org/std/iter/struct.Zip.html).

**Comment by ExpHP** [comment]
I am also not certain why you write the function as the first argument.  As I see it this increases the distance between the two things we're zipping together, and the function body can often be large.

Putting the function first seems reminiscent of functional languages like Haskell or ML, but those languages have the advantage of currying. **`zip = zipWith (,)`** is not going to be valid Rust any time soon... ;P

**Comment by Enselic** [comment]
Triage: This was closed in itertools as won't fix with a good [motivation](https://github.com/rust-itertools/itertools/pull/432#issuecomment-617360581), so let's also close this issue as won't fix.
