### ISSUE TITLE
assigning to immutable argument produces a confusing error

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#46659]
This program:

```rust
fn foo(_x: u32) {
    _x = 4;
}

fn main() {}
```

produces this error:

```
error[E0384]: re-assignment of immutable variable `_x`
 --> src/main.rs:2:5
  |
1 | fn foo(_x: u32) {
  |        -- first assignment to `_x`
2 |     _x = 4;
  |     ^^^^^^ re-assignment of immutable variable
```

I consider this a somewhat confusing error. I think it should rather be:

```
error[E0384]: assignment of immutable argument `_x`
 --> src/main.rs:2:5
  |
1 | fn foo(_x: u32) {
  |        -- `_x` not declared as `mut`
2 |     _x = 4;
  |     ^^^^^^ assignment of immutable argument `_x`
```

perhaps with a suggestion or something.

This error is issued by the borrow checker, so to do this right we should also modify the MIR-based borrow checker.

**Comment by nikomatsakis** [comment]
cc @estebank

**Comment by nikomatsakis** [comment]
Looks like this was fixed by https://github.com/rust-lang/rust/pull/47261

**Comment by estebank** [comment]
Only for MIR, that's why I didn't close the ticket, but if that's not a problem let's leave it closed.
