### ISSUE TITLE
Ensure that libstd is oom=panic clean

### ISSUE THREAD

**Issue by DemiMarie** [rust-lang/rust#46677]
We should ensure that libstd is `oom=panic` clean.  That means that if a panic occurs due to OOM, no resources are leaked and any data structures are left in a valid state (ideally, the state at function entry).  Furthermore, if a function can already return `Err` due to some other OS-level failure, such as too many open files, it should return `Err` on OOM as well.

**Comment by sfackler** [comment]
Are there any particular APIs that you're worried about?

**Comment by DemiMarie** [comment]
None in particular, except for the I/O libraries, which should catch OOM
and return error codes, and collections, which needs to make sure that on
OOM all data structures are left in a valid state.

**Comment by sfackler** [comment]
> except for the I/O libraries, which should catch OOM
> and return error codes

Why?

**Comment by DemiMarie** [comment]
@sfackler Because the main reason that OOM can’t just return errors everywhere is that it would be a horrific backwards-compatibility break.  Most system calls can already return `ENOMEM` or equivalent so that isn’t an issue.

**Comment by sfackler** [comment]
Why would not making a change break backwards compatibility?

**Comment by DemiMarie** [comment]
@sfackler `Vec::push` cannot suddenly be changed to return `Result` without breaking existing code, but most IO operations can already return `ENOMEM`.

**Comment by Enselic** [comment]
Triage: This would be a big change with consequences that are difficult to predict. By my estimation this needs to take the RFC route rather than the discussion-in-an-issue route. Closing for now.
