### ISSUE TITLE
ICE combining universal plus existential impl Trait

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#46685]
The following program [will ICE](https://play.rust-lang.org/?gist=39fc68c2d04a326be053d514eb5ca107&version=nightly):

```rust
#![feature(conservative_impl_trait)]
#![feature(universal_impl_trait)]

use std::fmt::Debug;

fn foo<'a>(x: &'a impl Debug) -> impl Into<&'a impl Debug> {
    x
}

fn main() { }
```

The problem derives from the fact that universal impl traits, during HIR lowering, do not generate entries in the `hir::Generics` structure -- they are synthesized after the fact, in the `ty::Generics`. This interferes with the `resolve_lifetime` code, which expects to use the HIR generics to determine the indices of things. 

I'm not sure the best fix here. The *easiest* fix is probably to count the number of universal impl traits and take them into account in `resolve_lifetime`. The *best* fix feels like it would be to actually insert the type parameters for universal impl trait instances into `hir::Generics`.

cc @cramertj @chrisvittal

**Comment by cramertj** [comment]
> The best fix feels like it would be to actually insert the type parameters for universal impl trait instances into hir::Generics

This actually might not be that hard-- you can probably re-use a lot of the code I set up for in-band lifetime bindings. You'd have to synthesize names for them, though, and make sure there aren't any conflicting names, plus the names can't escape into error messages.
