### ISSUE TITLE
figure out how to integrate constants and the MIR type checker

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#46702]
Currently the MIR type checker has some kind of hacky code to figure out what sorts of well-formedness constraints are present on a constant. The values of constants now are "post normalization" and don't give us ready access to what we need. As the comment from the code says:

```rust
                // FIXME(#46702) -- We need some way to get the predicates
                // associated with the "pre-evaluated" form of the
                // constant. For example, consider that the constant
                // may have associated constant projections (`<Foo as
                // Trait<'a, 'b>>::SOME_CONST`) that impose
                // constraints on `'a` and `'b`. These constraints
                // would be lost if we just look at the normalized
                // value.
```

**Comment by nikomatsakis** [comment]
I'm not really aware of any actual *problems* linked to this code, but I'll push it to the release milestone.

**Comment by pnkfelix** [comment]
visited for triage. @nikomatsakis believes this continues to be a potential issue of (potentially bad) interaction between miri integration and MIR/NLL. tagging as NLL-deferred

**Comment by pnkfelix** [comment]
Visited for T-compiler triage. I cannot imagine us blocking the release on this, given that there are not known bugs linked directly to this code...

I-nominating for discussion at next WG-compiler-nll meeting. Removing from Release milestone.

**Comment by pnkfelix** [comment]
unnominating. We'll get to this when we get to all the NLL-deferred issues, and right now its just clogging up T-compiler process.

**Comment by pnkfelix** [comment]
Re-triaging for #56754. Assuming NLL-sound for now. Tagging P-high based on that assumption. And nominating for discussion at tonight's A-NLL meeting, with the intent that *someone* get assigned to investigate this issue. (If no one is assigned by thursday, then please unnominate since I do not want this clogging up T-compiler again).

**Comment by pnkfelix** [comment]
discussed at A-NLL meeting. assigning to niko. removing I-nominated.

**Comment by oli-obk** [comment]
I have recently run into this code. I'm not sure I'm doing the right thing though: https://github.com/rust-lang/rust/pull/56723/files#r241086396

**Comment by matthewjasper** [comment]
It seems that the handling of type annotations takes care of the example in the comment. There are cases where types of constants are handled incorrectly:

```rust
// Compiles in both migrate mode and NLL mode.

fn main() {
    const FUN: fn(&'static ()) = |_| {};
    struct A;
    impl A {
        const MORE_FUN: fn(&'static ()) = |_| {};
    }

    let x = ();
    FUN(&x);
    A::MORE_FUN(&x);
}
```

**Comment by pnkfelix** [comment]
triage: no movement that I know of. But its assigned to @matthewjasper and I think that seems like a reasonable status for now. Only question is whether to keep this at P-high or downgrade to P-medium. Presumably the demo posted in the [previous comment](https://github.com/rust-lang/rust/issues/46702#issuecomment-451739979) is probably justification for leaving at P-high.
