### ISSUE TITLE
Convert &char to &str

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#46712]
This would have been useful in the u.r-l.o thread [*A `&’static str` version of `std::path::MAIN_SEPARATOR`?*](https://users.rust-lang.org/t/a-static-str-version-of-std-path-main-separator/14392/5?u=dtolnay).

Something like `as_str(&self)` or `impl AsRef<str> for char` may work.

**Comment by rkruppe** [comment]
That API can't exist (well, at least not without allocating and leaking, or having a homungous `static` table of strings) since `char` is not UTF-8 encoded.

**Comment by kennytm** [comment]
Such API could exist if it return `Option<&str>` and return `Some()` only when the character is in ASCII range. And I don't think this awkward API should be in std.

**Comment by dtolnay** [comment]
Thanks, I forgot that `char` is represented differently and this could only work for ASCII.
