### ISSUE TITLE
add `#![feature(nll)]` to supplement `-Znll`

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#46716]
As part of the NLL development, the plan is to allow people on nightly to "opt-in" to the new checker. My plan is to allow one of two things. Either you can use the `-Znll` compilation flag (as we do today) or you can use `#![feature(nll)]` in your code. 

I think it should work like this:

- `-Znll` implies `-Zborrowck=mir`. This is not true today and requires a small amount of tweaking. 
- `#![feature(nll)]` implies `-Znll`.

**Comment by pnkfelix** [comment]
(`-Z nll` should also imply `-Z two-phase-borrows`; that is, #46537 is part of the game plan here.)

**Comment by spastorino** [comment]
I'm working on this task, it's almost done. Just some things are taking ages because of compile times :(.

**Comment by pnkfelix** [comment]
This is probably resolved by #46862 (though I think we still want to have `#![feature(nll)]` imply `-Z two-phase-borrows`, and I don't think that PR included that).

**Comment by spastorino** [comment]
@pnkfelix it is included, it's this commit https://github.com/rust-lang/rust/pull/46862/commits/2019d69f6158be1f2108c12264b2beb94af0aafe

**Comment by pnkfelix** [comment]
ah great, then I'm closing this as finished.
