### ISSUE TITLE
E0046 with old format for fn items

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#46723]
Perhaps this has already been reported, but... Seeminly, for traits that are defined elsewhere, E0046 reports using the old style error message wrt. missing `fn` items.

With the following ([playground](https://play.rust-lang.org/?gist=e50708f310b46353762919ce39cc912c&version=nightly)):
```rust
use std::fmt::Debug;
struct Foo;
impl Debug for Foo {}

fn main() {}
```
I get:

```
error[E0046]: not all trait items implemented, missing: `fmt`
 --> src/main.rs:3:1
  |
3 | impl Debug for Foo {}
  | ^^^^^^^^^^^^^^^^^^^^^ missing `fmt` in implementation
  |
  = note: `fmt` from trait: `fn(&Self, &mut std::fmt::Formatter<'_>) -> std::result::Result<(), std::fmt::Error>`
`````
but I expected to see:

```
  |
3 | trait Debug { fn fmt(&self, f: &mut Formatter) -> Result<(), Error>; }
  |             --------- `fmt` from trait
4 | impl Debug for Foo {}
  | ^^^^^^^^^^^^^^^^^^^ missing `fmt` in implementation
```

**Comment by estebank** [comment]
This is because `fn fmt(...)` is coming from a different crate, which means `rustc` doesn't have access to its `span`. This is by design, the only thing you have left is signature (which we present as a `note`). This _might_ change in the future, but it is unlikely to happen soon.

**Comment by Centril** [comment]
Yeah, that was my intuition by I wasn't sure enough to assert it - but if at all possible it would be really cushy to have a consistent experience cross-crate =)

**Comment by estebank** [comment]
Current output:

```
error[E0046]: not all trait items implemented, missing: `fmt`
 --> src/main.rs:3:1
  |
3 | impl Debug for Foo {}
  | ^^^^^^^^^^^^^^^^^^ missing `fmt` in implementation
  |
  = help: implement the missing item: `fn fmt(&self, _: &mut std::fmt::Formatter<'_>) -> std::result::Result<(), std::fmt::Error> { unimplemented!() }`
```
