### ISSUE TITLE
rustdoc: Implementors of a trait is not const-evaled, thus showing `[T; 32 - 1 - 1 - 1 - 1 - 1 - 1 - 1]`

### ISSUE THREAD

**Issue by kennytm** [rust-lang/rust#46727]
Repro steps:

1. Go to https://doc.rust-lang.org/1.22.1/std/default/trait.Default.html or https://doc.rust-lang.org/nightly/std/default/trait.Default.html
2. Scroll down.
3. Notice the amusement.

![screenshot_2017-12-14 19 53 05_jfu5c0-fs8](https://user-images.githubusercontent.com/103023/33991251-e33f961e-e108-11e7-9263-f245fe77220d.png)

The array lengths are normal in 1.21.0, but it is not clear whether this is the effect of performing const evaluation or the macro generating these impl changed in the new version.

**Comment by xfix** [comment]
> The array lengths are normal in 1.21.0, but it is not clear whether this is the effect of performing const evaluation or the macro generating these impl changed in the new version.

The macro in question is the same for 2 years, as seen with blame. Here is a commit that introduced it: https://github.com/rust-lang/rust/commit/975a8ed312bbe262171b4c950c52cf992293bd55.

**Comment by kennytm** [comment]
Thanks for checking @xfix! Considering it's not due to change of generating macro, untagging `T-doc` and tagging `regression-from-stable-to-stable`.

**Comment by rkruppe** [comment]
Likely because array types now contain a constant expression instead of a fully evaluated `usize`. cc @eddyb

**Comment by rkruppe** [comment]
Offending rustdoc code:

https://github.com/rust-lang/rust/blob/master/src/librustdoc/clean/mod.rs#L2032

**Comment by eddyb** [comment]
We attempt to const-evaluate when we get the type from HIR:
https://github.com/rust-lang/rust/blob/75a02a919c5109c55c652dd6671553df6452be04/src/librustdoc/clean/mod.rs#L2029

But not from `Ty`:
https://github.com/rust-lang/rust/blob/75a02a919c5109c55c652dd6671553df6452be04/src/librustdoc/clean/mod.rs#L2155-L2156

So a few lines from the former should be copied to the latter.

**Comment by GuillaumeGomez** [comment]
Is anyone picking it up or should I wait a bit more before fixing it?

**Comment by detrumi** [comment]
This doesn't look too difficult, so I'll have a go at it.
