### ISSUE TITLE
Invalid type inference with Fn and Closures

### ISSUE THREAD

**Issue by oberien** [rust-lang/rust#46742]
The following code [compiles just fine](https://play.rust-lang.org/?gist=715873f570e8f5b008e5edc2ce7f947f&version=stable):

```rust
fn main() {
    let _: i32 = (match "" {
        "+" => ::std::ops::Add::add,
        "-" => ::std::ops::Sub::sub,
        "<" => |a,b| (a < b) as i32,
        _ => unimplemented!(),
    })(5, 5);
}
```

If we comment out the Sub-line, [a compilation error is thrown](https://play.rust-lang.org/?gist=27d101d4f4e544ea2955ab9cb7635b39&version=stable):

```rust
error[E0308]: match arms have incompatible types
 --> src/main.rs:2:18
  |
2 |       let _: i32 = (match "+" {
  |  __________________^
3 | |         "+" => ::std::ops::Add::add,
4 | |         //"-" => ::std::ops::Sub::sub,
5 | |         "<" => |a,b| (a < b) as i32,
6 | |         _ => unimplemented!(),
7 | |     })(5, 5);
  | |______^ expected fn item, found closure
  |
  = note: expected type `fn(_, _) -> <_ as std::ops::Add<_>>::Output {<_ as std::ops::Add<_>>::add}`
             found type `[closure@src/main.rs:5:16: 5:36]`
note: match arm with an incompatible type
 --> src/main.rs:5:16
  |
5 |         "<" => |a,b| (a < b) as i32,
  |                ^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

I previously submitted this issue in https://github.com/rust-lang/rust/issues/34511#issuecomment-351941692 , but @cramertj pointed out that this is not related to impl Trait. He also modified the example to the above code. Thus, I create this issue to move the discusson away from the impl Trait tracking issue.

/cc @eddyb @nikomatsakis

**Comment by eddyb** [comment]
What happens there is that closures can now be coerced to `fn` pointers, but not by this code:
https://github.com/rust-lang/rust/blob/84feab34e455722061bb55260eafd1eb02a538fa/src/librustc_typeck/check/coercion.rs#L807-L809

@nikomatsakis ^^ should we also produce function pointers from closures? Maybe at this point we should give up on the `TyFnDef` vs `TyClosure` distinction altogether.

**Comment by ldm0** [comment]
> Maybe at this point we should give up on the TyFnDef vs TyClosure distinction altogether.

BTW, cc @eddyb Do this make sense today?
