### ISSUE TITLE
impl Debug for Shared and Unique?

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#46755]
The `Shared` and `Unique` types have `#[allow(missing_debug_implementations)]`. Is there a reason for this? It seems that an impl like `write!(formatter, "Shared({:p})", self.as_ptr())` would be more useful.

CC @rust-lang/libs

**Comment by frewsxcv** [comment]
Opened a PR for this: https://github.com/rust-lang/rust/pull/46792
