### ISSUE TITLE
Matching on modulo failure.

### ISSUE THREAD

**Issue by hertz4** [rust-lang/rust#46759]
When matching on an unsigned modulus, I can cover all possible branches and still get a complaint.
```rust
fn thing(i: u8) -> &'static str {
    match i % 3 {
        0 => "Zero",
        1 => "One",
        2 => "Two",
    }
}
```
```
error[E0004]: non-exhaustive patterns: `_` not covered
 --> /tmp/modmatch.rs:2:11
  |
2 |     match i % 3 {
  |           ^^^^^ pattern `_` not covered
```
This is easily covered with `_ => unreachable!()`, possibly the most idiomatic use of said macro. I just wonder if it's possible for rust to be a bit smarter about this type of case.

**Comment by est31** [comment]
related issue: https://github.com/rust-lang/rfcs/issues/1550

**Comment by arielb1** [comment]
This should be an RFC - this is a more general version of rust-lang/rfcs#1550. IIRC we already rejected it several times so you might want to look at the history of this proposal before writing one.

Closing this issue because of that.
