### ISSUE TITLE
Rustdoc mistakes Enum with a module: pub use self::Enum::Variant

### ISSUE THREAD

**Issue by MaloJaffre** [rust-lang/rust#46766]
```rust
pub enum Enum{Variant}
pub use self::Enum::Variant;
```
Rustdoc renders the `use` with a broken link for `Enum`: 
`<a class="mod" href="./Enum/index.html">Enum</a>`
There is a correct one in Enums section:
`<a class="enum" href="enum.Enum.html" title='enum testt::Enum'>Enum</a>`

Note that the link for `Variant` is correct:
`<a class="enum" href="../testt/enum.Enum.html" title="enum testt::Enum">Variant</a>`

```
rustc 1.24.0-nightly (77efd6800 2017-12-15)
binary: rustc
commit-hash: 77efd6800c57ba83923dddbbabf03c7afa6a34a4
commit-date: 2017-12-15
host: x86_64-unknown-linux-gnu
release: 1.24.0-nightly
LLVM version: 4.0
```

**Comment by GuillaumeGomez** [comment]
Funny, will take a look asap.
