### ISSUE TITLE
wasm: support source maps for the unknown target

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#46765]
[Source maps](https://www.html5rocks.com/en/tutorials/developertools/sourcemaps/) are the analogon to debuginfo in the js world, including wasm. So we should generate them.

Emscripten apparently already is able to emit them, at least this example contains source maps: https://yurydelendik.github.io/old-man-sandbox/rust-wasm-hey/hey.html Maybe it's not upstreamed yet, idk.

I guess the bulk of this work would reside inside llvm, but I'm still filing a bug here to track support.

**Comment by brandf** [comment]
Is there any update, or workaround on this?  Rust+wasm is compelling for my scenarios, but without source maps, it's not a viable option.

**Comment by est31** [comment]
@brandf use the emscripten based backend. Other than that, no idea.

**Comment by est31** [comment]
Hrmmm did  #47883 fix this? Need to check...
