### ISSUE TITLE
repr(X) for invalid X silently accepted on non-type items

### ISSUE THREAD

**Issue by rkruppe** [rust-lang/rust#46770]
In the following program, the compiler only complains about `repr(blah)` on the struct, not on the function or static:

```rust
#[repr(blah)]
static FOO: u32 = 0;

#[repr(blah)]
fn foo() {}

#[repr(blah)]
struct Bar;
```

Using `repr(C)` instead reports an error for both.

**Comment by varkor** [comment]
If the struct declaration is commented out, the compiler complains about `repr(blah)` on the static variable and function too, so it's not silent so much as not reporting all the related errors at the same time.

**Comment by rkruppe** [comment]
You're right. I thought I had checked that but apparently not. Still odd (and makes writing compile-fail tests for this harder than necessary), but not a bug IMO.
