### ISSUE TITLE
rustdoc failed to pick up method summary comments in some cases

### ISSUE THREAD

**Issue by nodakai** [rust-lang/rust#46783]
https://doc.rust-lang.org/nightly/std/?search=max_value

`i8::max_value()`, `u8::max_value()` and a few others have summaries as given in the source code, but `i32::max_value()`, `u32::max_value()` and a few others somehow don't.

This is perplexing when we recall the `max_value()` method impls are generated by macros https://github.com/rust-lang/rust/blob/master/src/libcore/num/mod.rs#L100

**Comment by GuillaumeGomez** [comment]
cc @rust-lang/dev-tools 

I'll try to take a look in the next days.
