### ISSUE TITLE
Internal compiler error running `./src/ci/docker/run.sh`

### ISSUE THREAD

**Issue by ScottAbbey** [rust-lang/rust#46781]
I was attempting to run the ci/docker build.

I set up a machine with Ubuntu 14.04, installed docker and assorted build tools, cloned `rust-lang/rust` (master -> 35376587c802f3f142c63a443422184fd0ad40bd), and ran:

`./src/ci/docker/run.sh dist-x86_64-linux`

The build ran for some time then failed with the following internal compiler error.

Note that I originally had run this yesterday for `dist-x86_64-freebsd` and had the same or a very similar error that I did not save because I assumed I had done something wrong. I just tried a different one today.

I'm still not sure I'm doing this right so if I am just taking the wrong steps to run this let me know.  There is a considerable amount of additional log material I am leaving out that occurs before this point.

```

error: internal compiler error: /checkout/src/librustc/ty/context.rs:249: node unknown node (id=1) with HirId::owner DefId(0/0:0 ~ core[2633]) cannot be placed in TypeckTables with local_id_root DefId(0/0:1631 ~ core[2633]::panicking[0]::panic_fmt[0])

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.24.0-dev running on x86_64-unknown-linux-gnu

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:502:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `core`.

Caused by:
  process didn't exit successfully: `/checkout/obj/build/bootstrap/debug/rustc --crate-name core /checkout/src/libcore/lib.rs --error-format json --crate-type lib --emit=dep-info,link -C opt-level=2 -C metadata=c80c8268f013635d -C extra-filename=-c80c8268f013635d --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/release/deps` (exit code: 101)

```

**Comment by eddyb** [comment]
cc @nikomatsakis @michaelwoerister

**Comment by alexcrichton** [comment]
This is an ICE I've encountered many times before running this script and has to do with debug assertions being enabled in the compiler. I forget about when this started to appear but it's certainly not a new bug. You can work around this by setting `DEPLOY=1` in the environment before running the docker script.

**Comment by ScottAbbey** [comment]
Thank you for the suggested workaround.  After more thorough searching, I have found this is a duplicate of https://github.com/rust-lang/rust/issues/43982 so I will close.
