### ISSUE TITLE
Consider replacing the SVH with time-stamp/UUID

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#46810]
At the moment we are putting quite a bit of computational effort into calculating the SVH, which is a hash of HIR and is a supposed to be a reflection of a crates source code. If two crates have exactly the same SVH then they are the exact same version. At some point the SVH was supposed to signify binary compatibility but that never really worked. 

I think we should replace the SVH with a more simple concept, like a `BUILD_ID`. This could be a value that is truly unique for each build (e.g. just a UUID) or it could be a hash of `(commandline-args, source-file-time-stamps, upstream-crate-build-ids)`. The latter would be pretty much equivalent to the current SVH in terms of when it changes, but would be a bit harder to implement than the former.

Any objections to doing this?

cc @rust-lang/compiler @rust-lang/cargo

**Comment by matklad** [comment]
So the idea is to replace content-based digest with a time-based digest? I think there are cases where time may change while the content stays the same, especially in the interactive IDE setting. For example, the user may type something and hit undo, or they may switch a branch and then switch it back. So content based hashing seems more appropriate to me in theory.

**Comment by michaelwoerister** [comment]
> So the idea is to replace content-based digest with a time-based digest? 

Yes.

> I think there are cases where time may change while the content stays the same, especially in the interactive IDE setting. For example, the user may type something and hit undo, or they may switch a branch and then switch it back.

I think in practice there would only be a difference if no compilation (including `cargo check`) is triggered between making the change and then undoing it again. Would you say that that is the case often? I can imagine it happening for the "undo" case. 

> So content based hashing seems more appropriate to me in theory.

An alternative to the time-stamp based approach would be to just hash the source code.

**Comment by eddyb** [comment]
We already hash every source file in the codemap, so that for `Span`s coming from external crates, we can tell whether the original source file is unchanged on disk, so we can show snippets from it.

**Comment by matklad** [comment]
>Would you say that that is the case often? I can imagine it happening for the "undo" case.

I can only hypothesize here, but `including cargo check` is an important bit here. At the moment, when all IDE stuff bottoms out at running some sort of compilation to get safe analysis, I think it would be pretty rare. But I hope we'll kill cargo check one day, and in that future it would be totally reasonable to compile the code, switch branches, get highlights/errors for the new state, switch branch back, and run the tests **without** recompilation.


I don't really know the internal details here, but one possible optimization is to do both approaches, and recalculate hashes only when mtime changes.

**Comment by alexcrichton** [comment]
Something like a random uuid seems fine to me (or hashing source contents and/or modification times). I agree that the SVH hasn't really bought us much, and AFAIK no tool takes advantage of the possibility that you can recompile a crate and upstream crates won't need to be recompiled.

**Comment by michaelwoerister** [comment]
OK, I think switching to source code hashing is good compromise. It will reduce the runtime cost, it will reduce the complexity of the infrastructure in the compiler, and it is basically as stable as the SVH is now. I'll make a PR soon. Thanks for the input, everyone!

**Comment by joshtriplett** [comment]
One potential concern with using timestamps: not all filesystems have reliable, fine-grained timestamping. For instance, FAT filesystems have a 2-second granularity.

**Comment by michaelwoerister** [comment]
@joshtriplett Good point.

**Comment by tbu-** [comment]
This sounds like it could break reproducible builds.

**Comment by michaelwoerister** [comment]
Given all the anticipated and already encountered trouble (more complicated reproducible builds, unnecessary rebuilds, proc macro handling, etc), I'm closing this issue. Thanks for your feedback everyone!
