### ISSUE TITLE
ui tests should just show the stderr diff

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#46826]
Currently, when a UI test fails, it prints a sort of overwhelming amount of stuff:

https://github.com/rust-lang/rust/blob/a3c3245e911919e2d9c09ed0ab696b26f2517303/src/tools/compiletest/src/runtest.rs#L2712-L2722

I think what I would like is something like:

If the expected text is empty, just dump the actual (normalized) output, so people can copy-and-paste it if they want. 

Else, just print the diff. And probably it'd be nice to strip off the "prefix" and "suffix" of unchanged lines, and just show the parts that vary (we could imagine breaking things into hunks).

**Comment by nikomatsakis** [comment]
cc @oli-obk @petrochenkov -- two people who care about test suite I know, sorry if I'm forgetting to cc others =)

**Comment by durka** [comment]
> And probably it'd be nice to strip off the "prefix" and "suffix" of unchanged lines, and just show the parts that vary (we could imagine breaking things into hunks).

Sounds like reinventing features from existing diff libraries where there might be a crate that can do it nicely!

**Comment by omakk** [comment]
Hello!

I'm a Rust-learner and was wondering if I could pick up this issue?

**Comment by oli-obk** [comment]
@omakk great! Feel free to ping me on irc or ask any questions here.

I think an experimental implementation of using a diff crate would be the way to go as @durka suggested.

**Comment by ritiek** [comment]
@omakk If you're busy at the moment, do you mind if I take on this issue?

**Comment by omakk** [comment]
@ritiek Yes, go ahead! I unfortunately can not find the time to look at this. Apologies for the late update.

**Comment by petrochenkov** [comment]
>cc @petrochenkov

I never read these diffs, personally, just run `update-all-references.sh` immediately if there are errors.

**Comment by ritiek** [comment]
I suppose this can now be closed with #47185.
