### ISSUE TITLE
Doctests for alloc_system causes a (harmless) error

### ISSUE THREAD

**Issue by nodakai** [rust-lang/rust#46821]
Pick up any recent Travis logs:

* https://api.travis-ci.org/v3/job/317892277/log.txt

It says

```
   Doc-tests alloc_system
error: no #[default_lib_allocator] found but one is required; is libstd not linked?
```
which isn't cool.

Maybe there's something to improve with `[lib] test = false` in `Cargo.toml` ?

**Comment by alexcrichton** [comment]
This crate has long since been deleted, so I'm going to close this.
