### ISSUE TITLE
Nested use trees are not reachable

### ISSUE THREAD

**Issue by euclio** [rust-lang/rust#46823]
This causes an issue where the imports are not dumped in the save analysis data if it is configured to contain only reachable defs.

Steps to reproduce:

lib.rs:

```
#![crate_type = "lib"]

pub use private::*;

mod private {
    pub struct Struct1;
    pub struct Struct2;
}

pub use private2::{Struct3, Struct4};

mod private2 {
    pub struct Struct3;
    pub struct Struct4;
}
```

```
$ RUST_SAVE_ANALYSIS_CONFIG='{ "reachable_only": true, "full_docs": true, "pub_only": false, "distro_crate": false, "signatures": false, "borrow_data": false }' rustc -Zsave-analysis lib.rs
```

Notice that `pub use private::*;` will appear in the save analysis data, but neither import of `Struct3` or `Struct4`.

The relevant reachability testing is [here](https://github.com/rust-lang/rust/blob/b058dc0107b734b0a1a664ca0209366bb59eb3e9/src/librustc_save_analysis/dump_visitor.rs#L1248).

It seems to me that the `privacy_access_levels` query needs to be updated to consider the nested use tree as reachable?

cc @pietroalbini

**Comment by pietroalbini** [comment]
I'll look into this in a few hours.

**Comment by pietroalbini** [comment]
Sorry, I'm a bit busy these days, I'll try looking at this in the next few days.

**Comment by euclio** [comment]
No problem. I need to take a closer look because *using* the analysis data seemed to work as expected.

**Comment by pietroalbini** [comment]
Found the bug and fixed it locally. Tonight I'll add some tests and create a PR.
