### ISSUE TITLE
E0619 diagnostic occurs twice in rustc source

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#46837]
PR #46664 injected a second use of E0619.

This causes a warning at compile-time for `rustc_typeck`: 

```
   Compiling rustc_typeck v0.0.0 (file:///home/pnkfelix/Dev/Mozilla/rust-mirborrowck/src/librustc_typeck)
warning: diagnostic code E0619 already used
    --> /home/pnkfelix/Dev/Mozilla/rust-mirborrowck/src/librustc_typeck/check/mod.rs:4962:21
     |
4962 | /                     type_error_struct!(self.tcx.sess, sp, ty, E0619,
4963 | |                                        "the type of this value must be known in this context")
     | |______________________________________________________________________________________________^
     |
note: previous invocation
    --> /home/pnkfelix/Dev/Mozilla/rust-mirborrowck/src/librustc_typeck/check/method/probe.rs:328:25
     |
328  | /                         struct_span_warn!(self.tcx.sess, span, E0619,
329  | |                             "the type of this value must be known in this context")
     | |___________________________________________________________________________________^
     = note: this error originates in a macro outside of the current crate
```

**Comment by arielb1** [comment]
cc @mikeyhew - could you use a different error number for this soft warning?

**Comment by nodakai** [comment]
I'm sort of surprised to see when rustc caught the duplication it only raised a warning.

* https://github.com/rust-lang/rust/blob/master/src/libsyntax/diagnostics/plugin.rs#L69

Maybe a hard error?

**Comment by mikeyhew** [comment]
I remember getting this warning, and was going to deal with it but forgot. @arielb1 creating a separate error code would not be ideal, because it's the same error. When I change the warning to a future-compatibility lint though, I believe this will go away since it won't use an error code.

**Comment by arielb1** [comment]
Sure enough. Change it to a future-compat warning. Just don't bother everyone with a duplicate error code.

**Comment by mikeyhew** [comment]
@arielb1 I mean, I think it's the warning that's bothering people, not the fact that it's the same error code. The point was to exactly replicate the error, but make it a warning instead. Anyway, I'll change it to a future-compat lint. I'm just going to create a placeholder tracking issue for now, without explaining the reason for the lint, so that this issue gets resolved sooner.
