### ISSUE TITLE
Unions with uninhabited variants are considered uninhabited

### ISSUE THREAD

**Issue by gereeter** [rust-lang/rust#46845]
Uninhabited variants should ideally be irrelevant to the representation, just like in enums.

As a test, this prints out 0 instead of 8:
```rust
#![feature(never_type)]
use std::mem;

union Foo {
    a: u64,
    b: !
}

fn main() {
    println!("{}", mem::size_of::<Foo>());
}
```
This happens because rustc considers unions more like structs than enums, and the [test for uninhabitedness](https://github.com/rust-lang/rust/blob/b39c4bc12358078f77ddd01288b24252f757f37d/src/librustc/ty/layout.rs#L1361-L1364) sees a single variant with two fields, one of which is uninhabited.

I have a fix for this, but it's slightly easier to bundle it with some other changes I'm working on.

**Comment by durka** [comment]
This becomes a problem when making an array of unions:

```rust
#![allow(unused)]
use std::mem;

#[derive(Copy, Clone)]
enum Never {}

union Foo {
    a: u64,
    b: Never
}

fn main() {
    println!("{}", mem::size_of::<Foo>());
    
    let f = [Foo { a: 42 }, Foo { a: 10 }];
    println!("{:?}", unsafe { f[0].a });
}
```

The above code represents a regression (prints 42 on stable, garbage on beta/nightly).

**Comment by gereeter** [comment]
I didn't realize it was a regression to beta - in that case I'll put up an independent fix so that it can be backported if desired.

**Comment by gereeter** [comment]
Although I can't trigger it on the playground, you code is actually triggering an ICE for me:

```
error: internal compiler error: /checkout/src/librustc_trans/mir/place.rs:418: using operand local _19 as place

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.24.0-nightly (dc39c3169 2017-12-17) running on x86_64-unknown-linux-gnu
```

**Comment by arielb1** [comment]
cc @eddyb

**Comment by gereeter** [comment]
I put up a PR to fix this, but I'm still confused about the ICE (which I moved to #46855).
