### ISSUE TITLE
rustdoc: integrate a proper warning/error handler

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/rust#46844]
The current markdown rendering warnings are just a collection of `println!()` statements. It would be worthwhile to create a `rustc_errors::Handler` for rustdoc to properly emit errors from, so that these and others can be given proper formatting, and possibly even a mini lint system, or at least being able toggle specific errors between allow/warn/err.

**Comment by euclio** [comment]
I think this is fixed, no?

**Comment by QuietMisdreavus** [comment]
Indeed it is! We've started using a diagnostic emitter from `rustc_errors`, and all our errors and warnings go through that mechanism now. I'll close this.
