### ISSUE TITLE
src/test/compile-fail should have more files in subdirectories

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#46841]
Github refuses to list more than 1,000 files in a given directory listing.

As of this writing, its web interface reports that 1,260 entries are omitted from the printout for https://github.com/rust-lang/rust/tree/master/src/test/compile-fail

This has a simple fix: More subdirectories.

In particular, many of the tests even have a prefix that strongly implies a potential subdirectory to move that subset into; e.g. the associated-{const,item,type} tests could all go into `associated-item/`. LIkewise, the `E0nnn` test could all go into `diagnostics/`...

(This is a super easy change to make to the test suite, though I know that some people want to separately migrate more/all of the tests into the `ui/` subdirectory. I no longer object to the latter migration, but we'll still need to resolve *this* problem even when we do that migration.)

**Comment by varkor** [comment]
Update: [It was decided](https://github.com/rust-lang/rust/pull/46915#issuecomment-358691966) that a proper set of guidelines were needed for directories (and test names) first, before moving anything around.

**Comment by TheSirC** [comment]
Should this issue be closed ? Is there any work to be done ?

**Comment by varkor** [comment]
@TheSirC: as far as I'm aware, https://github.com/rust-lang/rust/issues/46841#issuecomment-358913471 is still relevant; it's just that no-one's got around to it yet.

cc @technicalguy

**Comment by technicalguy** [comment]
I think that is still the case. I certainly haven't got around to it (or anything). I think it would be good for someone with a bit more experience than me to suggest some guidelines and then we can work from there...

**Comment by TheSirC** [comment]
Thank you guys for your answer! I will wait for guidelines so.
