### ISSUE TITLE
ICE with match on non-const functions in constant definitions

### ISSUE THREAD

**Issue by K900** [rust-lang/rust#46843]
```rust
enum Thing { This, That }

fn non_const() -> Thing {
    Thing::This
}

pub const Q: i32 = match non_const() {
    Thing::This => 1,
    Thing::That => 0
};
```

```
error: internal compiler error: /checkout/src/librustc_mir/build/mod.rs:534: no terminator on block 10

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.24.0-nightly (0077d128d 2017-12-14) running on x86_64-unknown-linux-gnu

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:448:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

([playground](https://play.rust-lang.org/?gist=537f252c52447e25c6b072d469d5232a&version=nightly))

This ICEs on nightly/beta, but produces a correct error on stable.

Originally reported on Reddit [here](https://www.reddit.com/r/rust/comments/7kulgv/before_i_report_this_as_a_bug_let_me_ask_here/).

**Comment by eddyb** [comment]
cc @arielb1 @nikomatsakis Did anything change in pattern-matching between stable and beta?

**Comment by K900** [comment]
I'm bisecting as I'm writing this, but it's taking a while on my dual-core laptop :(

**Comment by eddyb** [comment]
cc @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
cc @est31 -- Is there a chance you could run bisect? We should really get playground to be capable of doing it...

**Comment by est31** [comment]
@Mark-Simulacrum not today, sorry. Maybe on friday...

**Comment by Deewiant** [comment]
I decided to bisect this myself and found 5b1cc1d810 (or #45821 as a whole) to be the cause, and created #46877 to fix it.
