### ISSUE TITLE
Immutable borrow seems to last too long - unclear compiler error

### ISSUE THREAD

**Issue by tonyfinn** [rust-lang/rust#46854]
I'm trying to make a lazily loaded map of textures while learning Rust. I have the following struct:

```rust
use std::collections::HashMap;
use std::path::Path;
use opengl_graphics::{ Texture, TextureSettings };

struct TextureCache {
    textures: HashMap<String, Texture>
}

impl TextureCache {
    fn new() -> TextureCache {
        TextureCache {
            textures: HashMap::new()
        }
    }
}
```

My first attempt at implementing lazy loading looked like this:

```rust
    fn get_texture_broken(&mut self, name: &str) -> &Texture {
        let name = name.to_string();
        {
            // Immutable borrow here
            if let Some(texture) = self.textures.get(&name) {
                return texture
            };
            // Immutable borrow should end here?
        }
        // Prevents mutable borrow here
        // But shouldn't it be out of scope?
        let textures = &mut self.textures;
        let tex = Texture::from_path(Path::new(&name), &TextureSettings::new()).unwrap();
        textures.insert(name.clone(), tex);
        textures.get(&name).unwrap()
        // Actually ends here
    }
```

From my understanding of Rust from [listing 4-1](https://doc.rust-lang.org/book/second-edition/ch04-01-what-is-ownership.html) and the example of [creating a new scope for mutable references](https://doc.rust-lang.org/book/second-edition/ch04-02-references-and-borrowing.html#mutable-references) in 4.2, the borrow should end after the inner scope, but in fact it lasts for the entire method.

The error message reported by the compiler is as follows:

```
error[E0502]: cannot borrow `self.textures` as mutable because it is also borrowed as immutable
  --> src\render\texture_cache.rs:34:29
   |
27 |             if let Some(texture) = self.textures.get(&name) {
   |                                    ------------- immutable borrow occurs here
...
34 |         let textures = &mut self.textures;
   |                             ^^^^^^^^^^^^^ mutable borrow occurs here
...
39 |     }
   |     - immutable borrow ends here
```

With help from #rust-beginners , an alternative implementation was found using std::collections::HashMap#entry but since this borrow seems to be breaking the normal rules as to how long it should live, it would be helpful if the compiler error would explain why it's outliving it's apparent scope. 

Rust version:

rustc 1.22.1 (05e2e1c41 2017-11-22)
binary: rustc
commit-hash: 05e2e1c41414e8fc73d0f267ea8dab1a3eeeaa99
commit-date: 2017-11-22
host: x86_64-pc-windows-msvc
release: 1.22.1
LLVM version: 4.0

**Comment by goodmanjonathan** [comment]
Non-lexical lifetimes (NLL) should allow this in the future [http://smallcultfollowing.com/babysteps/blog/2016/04/27/non-lexical-lifetimes-introduction/]. Right now, it's available on the nightly compiler using the options -Z borrowck=mir -Z nll.

**Comment by nikomatsakis** [comment]
Can you create a self-contained example? You could also try (on a nightly compiler) with `#![feature(nll)]` enabled in your `lib.rs` or `main.rs`.

**Comment by nikomatsakis** [comment]
But indeed this sounds like a classic pattern. The compiler is not wrong to act like it does, given the current type system, but the NLL extensions ought to make it accept this code.

**Comment by tonyfinn** [comment]
Complete example here: https://gist.github.com/tonyfinn/3703455ce6b3be0f880ba1efe1e9649c

I can confirm that this works by activing the NLL feature in the current nightly compiler:

rustc 1.25.0-nightly (b5392f545 2018-01-08)
binary: rustc
commit-hash: b5392f54503fdaf04df4b9578510b2baa944f4af
commit-date: 2018-01-08
host: x86_64-unknown-linux-gnu
release: 1.25.0-nightly
LLVM version: 4.0

**Comment by nikomatsakis** [comment]
Given that it's working with NLL enabled, I'm going to close the issue. Thanks!
