### ISSUE TITLE
Clarify confusing wording on Vec

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#46879]
Originally reported here: https://news.ycombinator.com/item?id=15969317

----

I don't understand the following sentence:

> ... it is strongly recommended that you only free memory allocated by a Vec by creating a new Vec and dropping it.

Could someone parse this for me? To me, it reads like "to free memory allocated by a Vec v, create a new Vec w and drop it (i.e., w)".

This is obviously not what it is intended. What's the role of the second Vec? Is this only in a context where v is empty but its memory not yet freed? If so, why wouldn't shrink_to_fit work in that case?

**Comment by rkruppe** [comment]
This refers to unsafe code that e.g. uses `Vec::with_capacity` to allocate memory, and then `mem::forget`s the `Vec` to use the buffer in different ways (e.g., passing it to C, or implement a custom data structure over the allocated memory).

**Comment by Manishearth** [comment]
https://github.com/rust-lang/rust/pull/46884
