### ISSUE TITLE
compiler code cleanup: replace metas: HashMap with IndexVec

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#46876]
While investigating the root cause(s) of #46112 and discussing (in the `#rustc` IRC chat room) the use of a hashmap mapping crate-numbers to crate-metadata, @eddyb [at some point exclaimed](https://botbot.me/mozilla/rustc/2017-12-19/?msg=94834353&page=1) "why is that not an `IndexVec`?"

One word: Legacy. Big time: the `metas` field has been a hashmap ever since `metadata::cstore` was introduced, 6.5 years ago in b23ecd47ceb7468d5132b9bf81d1d9c4e3fd1084 ([relevant line in diff](https://github.com/rust-lang/rust/commit/b23ecd47ceb7468d5132b9bf81d1d9c4e3fd1084#diff-b3412c376b0c44ca73fd5f1aa7db9193R5))

It should be a useful (and hopefully simple?) exercise to replace the hashmap that is [now there](https://github.com/rust-lang/rust/blob/970c613e4a785325469d4f694a16505d5deac17a/src/librustc_metadata/cstore.rs#L94) with an `IndexVec`.

**Comment by Eh2406** [comment]
So is it just replacing the type with? https://github.com/rust-lang/rust/blob/b3392f8ae4074de4de15befee871ad8b1523a2ed/src/librustc_data_structures/indexed_vec.rs#L328

If sow what is the equivalent for insert? https://github.com/rust-lang/rust/blob/970c613e4a785325469d4f694a16505d5deac17a/src/librustc_metadata/cstore.rs#L118

**Comment by arielb1** [comment]
@Eh2406 

Should be as simple as that

**Comment by Eh2406** [comment]
The only way I am seeing to add to an IndexVec is to push to the end at index == len
https://github.com/rust-lang/rust/blob/b3392f8ae4074de4de15befee871ad8b1523a2ed/src/librustc_data_structures/indexed_vec.rs#L385

But the hashmap uses the ability to insert at an arbitrary index:
https://github.com/rust-lang/rust/blob/970c613e4a785325469d4f694a16505d5deac17a/src/librustc_metadata/cstore.rs#L118

So I don't quite see how to make the conversion.

**Comment by pnkfelix** [comment]
@Eh2406 from my quick skimming, `fn set_crate_data` is only called from one place: `CrateLoader::register_crate`, here: https://github.com/rust-lang/rust/blob/691f022767aa5dec36635ab17bb767d5a80407db/src/librustc_metadata/creader.rs#L278

The `cnum` in that context is always the steadily incremented `next_crate_num`.

So I would suggest removing  `fn set_crate_data` entirely, and replacing it with a some method that indeed pushes to the end at index == len, as you state, since it seems that will have the same end effect.

**Comment by pnkfelix** [comment]
BTW if one really *did* need to support overwriting for arbitrary `cnum`s, that is easy too, as long as they already exist in the `IndexVec`, since `IndexVec` supports the `IndexMut` method that underlying `a[i] = b`: https://doc.rust-lang.org/std/ops/trait.IndexMut.html ; but I don't think we will need that in this case.

**Comment by arielb1** [comment]
@Eh2406 

Maybe you want an `IndexVec<CrateNum, Option<Rc<CrateMetadata>>>`?

**Comment by arielb1** [comment]
> The `cnum` in that context is always the steadily incremented `next_crate_num`.

That's not 100% correct. Crate numbers are assigned in preorder - if a crate (say `std`) has a dependency (say `core`), then `std` will get the earlier crate number, then `core` will be loaded, and only then will the metadata for `std` be assigned.

But it's ok to use an `IndexVec<CrateNum, Option<Rc<CrateMetadata>>>` to handle this.

**Comment by pnkfelix** [comment]
> That's not 100% correct. Crate numbers are assigned in preorder ...

You are right. I overlooked the fact that we 1. first increment the crate num (reserving the number, like for `std`) in your example, then 2. call `resolve_crate_deps` (which may recursively re-enter `register_crate`), before finally 3. calling `set_crate_data` at the end.

**Comment by Eh2406** [comment]
Ok, what is the best incantation to test this locally?

In the meantime I will open a pr.
