### ISSUE TITLE
Is an InlineAsm output a potential use that needs to activate a borrow?

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#46891]
I added the following FIXME recently: https://github.com/rust-lang/rust/blob/fb245e0/src/librustc_mir/dataflow/impls/borrows.rs#L543-L546

I'll gladly make a PR to change this or remove the fixme, but I don't know enough to decide what should happen.

cc @nikomatsakis maybe?

**Comment by nikomatsakis** [comment]
Probably it should activate. It'd be nice to make a test of course but I don't think I'm up to that from my phone. On Dec 20, 2017 15:00, scottmcm <notifications@github.com> wrote:I added the following FIXME recently: https://github.com/rust-lang/rust/blob/fb245e0/src/librustc_mir/dataflow/impls/borrows.rs#L543-L546
I'll gladly make a PR to change this or remove the fixme, but I don't know enough to decide what should happen.
cc @nikomatsakis maybe?

**Comment by nikomatsakis** [comment]
Given the more limited definition of two-phase borrows, I think it's impossible for such a use to activate a borrow?

**Comment by pnkfelix** [comment]
Re-triaging for #56754. NLL-sound. But since inline ASM is unstable, I'm tentatively tagging as P-medium; there's bigger fish for NLL to fry, IMO.

**Comment by nikomatsakis** [comment]
Discussing in NLL meeting. Closing as out of date.
