### ISSUE TITLE
Missing operator impls for &mut integers

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#46909]
This compiles:
```rust
fn main() {
    let mut a = 3;
    let mut b = 5;
    let r = &a;
    b += r;

    &1 + &2;
    !&3;
}
```

This doesn't compile:
```rust
fn main() {
    let mut a = 3;
    let mut b = 5;
    let r = &mut a;
    b += r; // Error.

    &mut 1 + &mut 2; // Error.
    !&mut 3; // Error.
}
```

Why is that so - is it simply an oversight, or was it intentional to omit implementing operators for mutable references to integers?

**Comment by inquisitivecrystal** [comment]
I'm going to close this. I've checked with the libs team and they've said that the current design is intentional. They might be open to the idea of changing it if someone wanted to do that, but it would take either further discussion or an RFC.
