### ISSUE TITLE
Spurious appveyor 32-bit test timeouts

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#46903]
The appveyor 32-bit MinGW test builders on appveyor are sometimes slower than expected and time out, which causes some of its builders to exceed the 3 hour limit (this had also happened I think in the start of December, if someone can bother digging up these PRs).

It appears that a "good" build (e.g. https://ci.appveyor.com/project/rust-lang/rust/build/1.0.5766) takes 150 minutes, while a "bad" build on the same code can exceed the 3 hour (180 minutes) limit.

It appears that in some cases (e.g. https://ci.appveyor.com/project/rust-lang/rust/build/1.0.5551) other builders also get close to the limit, but I haven't seen any of the *hitting* it yet. The reason appears to be that the 32-bit test builders (both MSVC and GNU) are the slowest, taking the "full" 150 minutes even on a good day.

I'm not that sure what the best solution is - eventually we could play with checkpoint/restart, but I would not want to do that on Windows first.

Maybe it's possible to investigate the cause of the slowness, or to bump the time limit, or to split the pc-windows-gnu builders (the latter would also speed up the cycle time).

However, the Windows 32-bit test builders being the slowest of our entire group seems to be a good cause to split them (this also makes some sense, because they spawn a lot of processes, which is slow on Windows).

Cases:

 - https://ci.appveyor.com/project/rust-lang/rust/build/1.0.5550 (#46144) - MSYS_BITS=32 test pc-windows-gnu, 2017-11-29
 - https://ci.appveyor.com/project/rust-lang/rust/build/1.0.5550 (#46366) - MSYS_BITS=32 test pc-windows-gnu, 2017-11-29
 - https://ci.appveyor.com/project/rust-lang/rust/build/1.0.5559 (#46370) - MSYS_BITS=32 test pc-windows-gnu, 2017-11-30
 - https://ci.appveyor.com/project/rust-lang/rust/build/1.0.5743 (#46802) - MSYS_BITS=32 test pc-windows-gnu, 2017-12-18
 - https://ci.appveyor.com/project/rust-lang/rust/build/1.0.5756 (#46733) - MSYS_BITS=32 test pc-windows-gnu, 2017-12-20
 - https://ci.appveyor.com/project/rust-lang/rust/build/1.0.5765 (#46752) - MSYS_BITS=32 test pc-windows-gnu, 2017-12-21

**Comment by alexcrichton** [comment]
Picking two random logs [good](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.5790/job/8msoy4cs6fofgh9t) [bad](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.5765/job/0fwx077ujdf9gnw1) the major difference seems to be that the good log finishes compiling the compiler at 01:01:30, whereas the bad log finishes at 01:21:05, a 20 minute delay from the original one. AFAIK no real extra work was done in the bad log. I believe that AppVeyor doesn't guarantee a constant level of performance (shared hosting and whatnot) so I think that we just get less CPU time during peak hours (or at least that's what I think).

In that sense I think the only real solution here is to do less work per job. That may mean cutting tests from 32-bit MinGW tests or sharding the builder.

**Comment by kennytm** [comment]
#46910 has caused about 40–50% increase in time spent on fulldeps tests. But it is not sufficient to explain the recent timeouts this week since that just means an additional 4 minutes at most.

**Comment by kennytm** [comment]
#47161 has landed but the error rate is still not decreasing 😢

**Comment by withoutboats** [comment]
Surely the size of the code base and test suite is growing over time, I think this is the expected result unless compiler speed is improving at a greater rate than the code base is growing (which seems unlikely).

**Comment by alexcrichton** [comment]
@withoutboats I agre yeah but there's been a severe uptick over the past ~200 builds which means our build time is increasing *way* faster than it was before, which seems worrisome..

**Comment by aidanhs** [comment]
As a data point, the trend for partitioned OSX builds over the same period is similar:

![osx_partitions](https://user-images.githubusercontent.com/1050652/35780949-1740c0f0-09db-11e8-8fe0-e368fc2d5aa2.png)

Although not smoothed, you can see that the time taken by `make all` has increased by ~20min across the graph.

**Comment by Aaron1011** [comment]
This seems to be another example: https://ci.appveyor.com/project/rust-lang/rust/build/1.0.6426/job/do1stdu2mywwkyf7 `MSYS_BITS=32, RUST_CONFIGURE_ARGS=--build=i686-pc-windows-gnu`

**Comment by Mark-Simulacrum** [comment]
Closing as fixed. We've had multiple successful builds on AppVeyor, the 32-bit MinGW builders are both now around 2 hours.
