### ISSUE TITLE
rustdoc: kbd style rules

### ISSUE THREAD

**Issue by hellow554** [rust-lang/rust#46900]
Hi everyone,

I documented a struct which uses keyboard commands during runtime to do something and I noticed that it looks not as nice as it could be, so I looked around and compared different kbd styles on the internet.
I compare here the github style (<kbd>A</kbd>), [Stackexchange](https://meta.superuser.com/questions/4788/css-for-the-new-kbd-style) and [Bootstrap (v4)](https://v4-alpha.getbootstrap.com/content/code/#user-input)

![compare](https://user-images.githubusercontent.com/921462/34246368-993bfd5c-e62e-11e7-87a5-c393a6559ec8.png)

Which of these styles do you prefer? I would go with the github style, because it's looks nice and clean without any padding. Maybe one could increase the font size.

I would also do a PR, but I wanted to discuss the style before I do that.

So, what are your thoughts? Do you have any different style in mind? To which elements should the rule apply? To all \<kbd\> tags or just tags inside a `docblock`?

**Comment by GuillaumeGomez** [comment]
What prevents you to add your own style in your crate doc? Because I'm not sure to understand why we'd want that...

**Comment by GuillaumeGomez** [comment]
cc @rust-lang/docs

**Comment by steveklabnik** [comment]
I also prefer the github style.

@GuillaumeGomez to me, this is a regular old HTML element; we should give it a decent style.

**Comment by QuietMisdreavus** [comment]
:+1: for the github style.

**Comment by frewsxcv** [comment]
github style looks most like a keyboard key to me, so i'd be favor of that too

**Comment by hellow554** [comment]
Thank you for your responses <3 what about the rule? Every \<kbd\> tag or just the ones inside a docblock ?

**Comment by QuietMisdreavus** [comment]
I'd say to make it every `<kbd>` tag, so we can also change the `?` help menu to use them as well.

**Comment by steveklabnik** [comment]
Agreed!

**Comment by GuillaumeGomez** [comment]
I extend a bit my statement: I'm opposed to this add because it'll be used in too few cases to be interesting to grow the CSS files (I could bet on maximum 5 people, which is just way too low). It doesn't bring anything useful enough to justify any new content. Please remember that new content means more maintenance.

Adding a CSS rule in your own doc crate is far easier and better for everyone in most cases.

cc @rust-lang/docs

**Comment by hellow554** [comment]
I may understand your concern, but do not share your opinion. 

A tag is just a tag, and kbd should be used to represent [input from a keyboard](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd) and for that it should be visualized as such. It's not about adding bloat to the css, but to give a nice visual hint to the reader, that this is a keyboard input.

**Comment by QuietMisdreavus** [comment]
I already mentioned a place where rustdoc can use a `<kbd>` style for itself - the help menu. Right now it's skinning `<dt>` to get it, but it can move to use `<kbd>` tags and get a better style for it if we add it.

**Comment by GuillaumeGomez** [comment]
If the PR does the switch (aka removing dt tag and style). Then it's good for me. As long as it's used by rustdoc, no problem.

**Comment by hellow554** [comment]
As said, sorry for the late response, christmas, new years eve, vacation, ...
Nethertheless, I stumble upon a problem:

![unbenannt](https://user-images.githubusercontent.com/921462/34933845-b9e58b46-f9d8-11e7-8309-1388a22f347d.PNG)
As you can see, the <kbd+</kbd>/<kbd>-</kbd> section looks a little bit weird, because it's not 1char wide, but 3.
How to deal with this? Align all of the other parts a little bit to the right? Any other recommendations?

**Comment by GuillaumeGomez** [comment]
> As said, sorry for the late response, christmas, new years eve, vacation, ...

Sure, no problem. Hope you enjoyed it. :)

> Nethertheless, I stumble upon a problem:

Try to move all "keys" a bit to the right so all the column seems centered. And add a bit of margin to the right of the "+/-" keys please.

**Comment by hellow554** [comment]
I had to change ths overall width of the #help box, because elsewise the last line would break. I changed the height to auto (can revert that, but I thought it looks nicer) and added inner padding to the dt section.

Which one do you like more? (center or right aligned)

![unbenannt](https://user-images.githubusercontent.com/921462/34948151-a30988f8-fa0c-11e7-8b1f-da30854228b7.png)

**Comment by steveklabnik** [comment]
I'm fine with either.

**Comment by GuillaumeGomez** [comment]
I have a slight preference for the second one.

What about @QuietMisdreavus?

**Comment by QuietMisdreavus** [comment]
I think i like the second one (the centered one) a little more.

**Comment by hellow554** [comment]
One could also split the + and - keys into different lines

    + Expand all sections
    + collaps all sections

And we wouldn't have the problem with different width of dt tags

**Comment by GuillaumeGomez** [comment]
@hellow554: Indeed, great suggestions!

**Comment by hellow554** [comment]
Last commit makes it looks like this, I hope you like it :)

![unbenannt](https://user-images.githubusercontent.com/921462/35052297-8d3f2176-fba7-11e7-856d-8ed64ed07c7a.png)

**Comment by GuillaumeGomez** [comment]
Yep, looks great! With this design: 👍

**Comment by GuillaumeGomez** [comment]
It got merged so it can get closed now.
