### ISSUE TITLE
Non-Lexical Lifetimes only work with some types

### ISSUE THREAD

**Issue by CryZe** [rust-lang/rust#46935]
This one is really weird. It's the same code, but one is a Vec<char> and one is a i32. The Vec one compiles, the i32 one doesn't:
```rust
fn vec() {
    let mut _x = vec!['c'];
    let _y = &_x;
    _x = Vec::new();
}

fn int()  {
    let mut _x = 5;
    let _y = &_x;
    _x = 7;
}
```
Error:
```
error[E0506]: cannot assign to `_x` because it is borrowed
  --> src\lib.rs:49:5
   |
48 |     let _y = &_x;
   |              --- borrow of `_x` occurs here
49 |     _x = 7;
   |     ^^^^^^ assignment to borrowed `_x` occurs here

```

**Comment by CryZe** [comment]
It looks like if the type of `_x` is either `&T`, `&mut T`, or `T: Drop` (or rather T that contains a Drop type somewhere) then NLL behaves just fine, but if you have a type that is not a reference and doesn't cause any calls to Drop, then it breaks.

**Comment by matthewjasper** [comment]
I think this is #46875. Delaying the assignment to `_x` makes this compile:

```rust
fn int1()  {
    let mut _x = 5;
    let _y = &_x;
    ();
    _x = 7;
}

fn int2()  {
    let mut _x = 5;
    let _y = &_x;
    _x = 1 + 2 + 4;
}
```
