### ISSUE TITLE
single_use_lifetimes should have suggestions

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#46944]
This is a new feature, we should be teaching it through error messages.

Currently we just say that a lifetime is single use but do not recommend how to fix it. It leads to confusions like https://github.com/rust-lang/rust/issues/46873

We should fix that.

**Comment by leonardo-m** [comment]
Yes, it was a mistake of mine then. A better error message will probably solve the problem. Thank you.

**Comment by leonardo-m** [comment]
I've added another comment in #46873

**Comment by zackmdavis** [comment]
This was fixed in #55432.
