### ISSUE TITLE
rustup self update does not work

### ISSUE THREAD

**Issue by elszben** [rust-lang/rust#46945]
rustup self update does not work anymore. I've tried to remove everything and reinstall everything rust related and the same thing happens. No idea what caused it.

C:\Users\laci\Downloads>rustup self update
info: checking for self-updates
error: could not create link from 'C:\Users\laci\.cargo\bin\rustup.exe' to 'C:\Users\laci\.cargo\bin\rustc.exe'
info: backtrace:

stack backtrace:
   0:   0x634c34 - <no info>
   1:   0x5919db - <no info>
   2:   0x591a66 - <no info>
   3:   0x57026e - <no info>
   4:   0x56ff51 - <no info>
   5:   0x42eec9 - <no info>
   6:   0x420ae3 - <no info>
   7:   0x439330 - <no info>
   8:   0x438aa5 - <no info>
   9:   0x9190fb - <no info>
  10:   0x9164ca - <no info>
  11:   0x43d72c - <no info>
  12:   0x4013e3 - <no info>
  13: 0x75b57c04 - BaseThreadInitThunk
  14: 0x77b5ad2f - RtlInitializeExceptionChain

C:\Users\laci\Downloads>

**Comment by kennytm** [comment]
Hi, what Windows version are you using?

(BTW rustup issues are better filed at https://github.com/rust-lang-nursery/rustup.rs/issues)

**Comment by elszben** [comment]
I'm using Windows 8.1.

Sorry about opening the issue here.

**Comment by DustinByfuglien** [comment]
Confirm.
I have this problem in Windows 7.

**Comment by meztez** [comment]
For some reason, rustup isnt able to remove the file already in the folder before doing the hardlink. I got it working by deleting them before running the self update. It gave link errors and a warning about rustfmt.

**Comment by Cristian-Malinescu** [comment]
I have same problem in Windows 10.

**Comment by joce** [comment]
@kennytm Should the issue be duplicated (link? ported over? (I'm unfamiliar with GH issue system)) to rustup or will it be taken care of here nonetheless?
(also yes, I have the same issue with Win10, Creator Update (version 1709))

**Comment by kennytm** [comment]
@joce It should better be copy-and-pasted to the rustup repo.

**Comment by lamogui** [comment]
got this here on windows 10

**Comment by matklad** [comment]
Hit this on CI. Looks like one workaround is to downgrade rustup. Here's an older version:

https://static.rust-lang.org/rustup/archive/1.7.0/i686-pc-windows-gnu/rustup-init.exe -FileName rustup-init.exe

**Comment by kennytm** [comment]
Closing in favor of rust-lang-nursery/rustup.rs#1316. Please follow that issue instead, thanks!
