### ISSUE TITLE
Add `x.py check --stage 1`

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust#46955]
When modifying the interface between platform-specific/non-platform-specific parts of the codebase, proper testing requires being able to build for every supported target, which is very impractical. Ideally `x.py` would support `cargo check` such that platform specific code could still be validated and type checked without needing the corresponding cross-compiling C toolchains.

This requires at least #44737 to be fixed to be useful.

**Comment by pietroalbini** [comment]
Does #47460 do everything you wanted?

**Comment by Diggsey** [comment]
I think it would need to be extended to support stage 1 to be useful for the case I outlined above.

**Comment by pickfire** [comment]
Is this fixed yet?

**Comment by jyn514** [comment]
> I think it would need to be extended to support stage 1 to be useful for the case I outlined above.

This is sort of a hack, but you can do this by
1. Building a stage1 compiler (`x.py build --stage 1 library/std`)
2. Adding a new git worktree (`git worktree add ../rust2`)
3. Setting the newly built compiler as stage 0 for the new worktree (`rustc = "/path/to/rust1/build/$TARGET/stage1/bin/rustc"`)
4. Running `x.py check` like normal.

I agree it would be great to support `x.py check --stage 1` or something like that.

**Comment by jyn514** [comment]
This was added in https://github.com/rust-lang/rust/pull/81064.
