### ISSUE TITLE
Build failure should print the command line that failed

### ISSUE THREAD

**Issue by catamorphism** [rust-lang/rust#4696]
Far too often, I've done something like:

`$ make check`
(wait)
`compile_and_link: x86_64-apple-darwin/test/coretest.stage2-x86_64-apple-darwin`
`*** build error of some sort...`

Then I want to run the command that failed by itself, but I don't have it; I can either remember what it is, or run `VERBOSE=1 make check` and wait. It would be nice if a build failure printed out just the command line that caused the last error. I could run with VERBOSE all the time, but that does get very verbose.

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by steveklabnik** [comment]
Triage: obsoleted by rustbuild, though rustbuild is not yet in place.

**Comment by alexcrichton** [comment]
Done!
