### ISSUE TITLE
link_section is not applied to global constants

### ISSUE THREAD

**Issue by mjbshaw** [rust-lang/rust#46968]
The `link_section` attribute doesn't get applied to global `const` values.

Consider the following program (which uses `static` instead of `const`, and correctly applies the `link_section` to `HELLO`):
```
#[link_section = ".data,__yes_this_is_a_custom_link_section"]
static HELLO: [u8; 6] = *b"hello\0";

extern {
  fn puts(_str: *const u8) -> i32;
}

fn main() {
  unsafe { puts(&HELLO as *const u8) };
}
```

As can be seen in the LLVM IR ([Playground link](https://play.rust-lang.org/?gist=0398978e1c26ae2a4fb09c949a710773&version=nightly)), `HELLO` is correctly given the custom section assignment:
```
@_ZN10playground5HELLO17h62136d8dd807037cE = internal constant [6 x i8] c"hello\00", section ".data,__yes_this_is_a_custom_link_section", align 1

; playground::main
; Function Attrs: nounwind uwtable
define internal void @_ZN10playground4main17h4b9f3b1aa6035d1eE() unnamed_addr #0 {
start:
  %0 = tail call i32 @puts(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @_ZN10playground5HELLO17h62136d8dd807037cE, i64 0, i64 0))
  ret void
}
```

But if we change `HELLO` to be a `const` instead of `static`:
```
#[link_section = ".data,__yes_this_is_a_custom_link_section"]
const HELLO: [u8; 6] = *b"hello\0";

extern {
  fn puts(_str: *const u8) -> i32;
}

fn main() {
  unsafe { puts(&HELLO as *const u8) };
}
```

Then the string no longer has the custom section applied ([Playground link](https://play.rust-lang.org/?gist=b6988e9d8aca98318b898d7f134a00af&version=nightly)):
```
@byte_str.0 = private unnamed_addr constant [6 x i8] c"hello\00", align 8

; playground::main
; Function Attrs: nounwind uwtable
define internal void @_ZN10playground4main17h4b9f3b1aa6035d1eE() unnamed_addr #0 {
start:
  %0 = tail call i32 @puts(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @byte_str.0, i64 0, i64 0))
  ret void
}
```

I think that Rust should propagate the link section to all instances of the string. That is, `@byte_str.0` (and any other duplicate instances of the `const`) should be defined as `@byte_str.0 = private unnamed_addr constant [6 x i8] c"hello\00", section ".data,__yes_this_is_a_custom_link_section", align 8`.

----

Meta info: I've tested this in both 1.22.1 and 1.24.0-nightly (2017-12-22 5165ee9e209e0e70d89946ccbb7e90b9c0c3a7ac). Both produce the same results.

**Comment by rkruppe** [comment]
As far as Rust-the-language is concerned, `const`s are entities that don't have any linkage behavior at all. Any *use* of a `const` is as if the value as written out as a literal at the use site, and the const itself doesn't have an address or symbol name at all. For example, `#[no_mangle] const X ...` reports "error: const items should never be #[no_mangle], consider instead using `pub static`". Likewise there should be an error about other linkage-related attributes on consts.

**Comment by mjbshaw** [comment]
Okay, well then it would make sense to disallow `link_section` on `const`. In my particular case I was really hoping to take advantage of the LLVM `unnamed_addr` attribute that gets applied to `const` Rust objects, but I can live without it and will use `static`.

**Comment by nagisa** [comment]
Inapplicable attributes don’t really get "disallowed", that applies for most of them, really.

The principle is that item checks for attributes relevant to itself, rather than all attributes checked against the item they apply to. There are multiple good reasons why it is implemented as such and I don’t see the behaviour changing.

That being said, I find it amusing that the attribute-not-used warning does not get output, as constants should not bother checking for `link_section` attribute at all.

**Comment by sfackler** [comment]
There's a set of attributes that attribute-not-used lint doesn't look at since they're used in trans but lints run before that.

**Comment by Enselic** [comment]
Triage: Closing as won't fix based on last two comments.
