### ISSUE TITLE
OsRng initialization fails under VMware Linux

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/rust#46970]
In trying to use binaries statically compiled for Linux x86_64 (namely, rg 0.7.1: https://github.com/BurntSushi/ripgrep/releases), I've found that rust cannot initialize the OS RNG, and `rg` crashes immediately (and reproducibly) on invocation with the following:

> thread 'main' panicked at 'failed to create an OS RNG: Error { repr: Os { code: 22, message: "Invalid argument" } }', /checkout/src/libcore/result.rs:906:4

Environment: `VMkernel vmware 6.0.0 #1 SMP Release build-3029758 Aug 31 2015 00:54:00 x86_64 x86_64 x86_64 ESXi`

**Comment by sfackler** [comment]
Can you use strace to figure out which system call is failing?

**Comment by mqudsi** [comment]
I'm not sure, it's an insanely minimal environment. Let me try.

**Comment by Enselic** [comment]
Triage: Can this still be reproduced? Do we really have reason to believe this is a rustc bug?

**Comment by Enselic** [comment]
Triage: Assuming not, so let's close.

**Comment by mqudsi** [comment]
Fair enough!
