### ISSUE TITLE
NLL: bad error message when converting anonymous lifetime to `'static`

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#46983]
UPDATE: [Mentoring instructions here.](https://github.com/rust-lang/rust/issues/46983#issuecomment-356626994)

----

Tested at 5165ee9e209e0e70d89946ccbb7e90b9c0c3a7ac and current playpen

```Rust
#![feature(nll)]

fn foo(x: &u32) -> &'static u32 {
    &*x
}

fn main() {}
```

Error message:

```
error: free region `` does not outlive free region `'static`
 --> src/main.rs:4:5
  |
4 |     &*x
  |     ^^^

error: aborting due to previous error
```

**Comment by nikomatsakis** [comment]
So, the NLL region checking errors currently uses the "nice region error" routines if it can:

https://github.com/rust-lang/rust/blob/27ede55414e01f13c6869a8763da207e544cc6ad/src/librustc_mir/borrow_check/nll/region_infer/mod.rs#L990-L996

If not, it fallback to this bad error message. This is the same basic strategy that the lexical region error reporting takes:

https://github.com/rust-lang/rust/blob/27ede55414e01f13c6869a8763da207e544cc6ad/src/librustc/infer/error_reporting/mod.rs#L303-L340

You'll note that the error message you get *without* `#![feature(nll)]` is not particularly good ([playground](https://play.rust-lang.org/?gist=c2ed7a059dd97bc2ade2e67e0672fe39&version=nightly)):

```
error[E0495]: cannot infer an appropriate lifetime for borrow expression due to conflicting requirements
 --> src/main.rs:2:5
  |
2 |     &*x
  |     ^^^
  |
note: first, the lifetime cannot outlive the anonymous lifetime #1 defined on the function body at 1:1...
 --> src/main.rs:1:1
  |
1 | / fn foo(x: &u32) -> &'static u32 {
2 | |     &*x
3 | | }
  | |_^
note: ...so that reference does not outlive borrowed content
 --> src/main.rs:2:5
  |
2 |     &*x
  |     ^^^
  = note: but, the lifetime must be valid for the static lifetime...
note: ...so that reference does not outlive borrowed content
 --> src/main.rs:2:5
  |
2 |     &*x
  |     ^^^
```

I think the ideal way to address this would be to make a "nice region error" that covers this case. Note that if we used a named lifetime like `'a`, we get a better error. For example:

```rust
#![feature(nll)]

fn foo<'a>(x: &u32) -> &'a u32 {
    &*x
}

fn main() {}
```

[gives](https://play.rust-lang.org/?gist=84b91bea2f1e5fb8866b35a8a4f929cd&version=nightly):

```
error[E0621]: explicit lifetime required in the type of `x`
 --> src/main.rs:4:5
  |
3 | fn foo<'a>(x: &u32) -> &'a u32 {
  |            - consider changing the type of `x` to `&'a u32`
4 |     &*x
  |     ^^^ lifetime `'a` required
```

I believe this error is produced by the `try_report_named_anon_conflict` method:

https://github.com/rust-lang/rust/blob/27ede55414e01f13c6869a8763da207e544cc6ad/src/librustc/infer/error_reporting/nice_region_error/named_anon_conflict.rs#L20-L120

The problem *here* is that the code is written to detect the case of one anonymous region and one region for which `is_named_region` is true. But `is_named_region` returns `false` for statics:

https://github.com/rust-lang/rust/blob/27ede55414e01f13c6869a8763da207e544cc6ad/src/librustc/infer/error_reporting/nice_region_error/util.rs#L202-L212

I *think* the simplest fix here would be to make that method return true for the `ReStatic` variant. Looking through the code, I don't see any reason that this would go wrong.

(Also, it appears that `is_named_region` is only used from `named_anon_conflict`; I think we should move the definition from `util.rs` to `named_anon_conflict.rs`.)

**Comment by davidtwco** [comment]
I'll tackle this one.

**Comment by pnkfelix** [comment]
Note in particular that I don't expect this to be fixed until the output at https://github.com/rust-lang/rust/blob/master/src/test/ui/underscore-lifetime/dyn-trait-underscore.nll.stderr has been made legible, but currently we emit:
> error: free region `` does not outlive free region `'static`

**Comment by davidtwco** [comment]
I'll look into this one (again).

**Comment by nikomatsakis** [comment]
@davidtwco and I had a discussion about how to fix this (and many other region errors besides) which is available here <https://youtu.be/Vj0FuKTVP94>.

**Comment by pnkfelix** [comment]
Okay we are declaring this now "fixed" because the output of `dyn-trait-underscope.rs` looks [like this](https://github.com/rust-lang/rust/blob/a1e6bcb2085cba3d5e549ba3b175f99487c21639/src/test/ui/underscore-lifetime/dyn-trait-underscore.nll.stderr#L28):

```
error: unsatisfied lifetime constraints
  --> $DIR/dyn-trait-underscore.rs:18:5
   |
LL | fn a<T>(items: &[T]) -> Box<dyn Iterator<Item=&T>> {
   |                - let's call the lifetime of this reference `'1`
LL |     //                      ^^^^^^^^^^^^^^^^^^^^^ bound *here* defaults to `'static`
LL |     Box::new(items.iter()) //~ ERROR cannot infer an appropriate lifetime
   |     ^^^^^^^^^^^^^^^^^^^^^^ cast requires that `'1` must outlive `'static`

```
