### ISSUE TITLE
Ambiguous documentation of line!() and column!()

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#46997]
The documentation of the [`line!()`](https://doc.rust-lang.org/std/macro.line.html) and [`column!()`](https://doc.rust-lang.org/std/macro.column.html) macros says:

> The returned line is not the invocation of the \`line!()\` macro itself, but rather the first macro invocation leading up to the invocation of the \`line!()\` macro.

I find "not the invocation of the \`line!\` macro itself" a bit misleading, because it is totally possible and expected for the return value to be the line of the invocation of the line macro itself when not being called from another macro. It may be clearer as "not necessarily the line of the \`line!\` invocation itself".

**Comment by steveklabnik** [comment]
This has been fixed.
