### ISSUE TITLE
Stage1 compilation hangs indefinitely on libcore (OS X)

### ISSUE THREAD

**Issue by shssoichiro** [rust-lang/rust#47008]
A few days ago, I was able to compile the compiler through stage1 in about 20 minutes (4-core Haswell i7 with hyperthreading on OS X High Sierra). Since rebasing against master, stage1 seems to hang at compiling libcore. It has currently been compiling stage1's libcore for 45 minutes, using 60% of one CPU core, and shows no signs of finishing. Nothing else on the machine is using a significant amount of CPU time, and there are more than 6GB free memory remaining. I've also verified that the CPU is not being throttled down.

I've bisected the responsible commit down to ccc91d7. Prior to this commit, stage1 libcore consistently compiles in under 1 minute.

**Comment by shssoichiro** [comment]
Update: I was not able to reproduce this on a Linux machine.

**Comment by Mark-Simulacrum** [comment]
Presumably this is no longer an issue (I believe I recently compiled libcore quite quickly on macOS). Closing as such, but we can definitely reopen if people are still hitting this!
