### ISSUE TITLE
Docs of `impl Index` for HashMap and BTreeMap should mention they panic for a non-existent key

### ISSUE THREAD

**Issue by nodakai** [rust-lang/rust#47011]
It's true that you can expect this behavior from the method signature, but this is too important a detail to leave out.

What was the rustdoc syntax to document a particular impl of a trait?

**Comment by kennytm** [comment]
You just write doc comments on the impl block as usual.

```rust
/// Doc comments
impl<Q, K, V> Index<Q> for BTreeMap<K, V> where /*something*/ {
    type Output = V;
    /// More doc comments
    fn index(&self, key: Q) -> &V { ... }
}
```
