### ISSUE TITLE
GNU toolchain on Windows can't build compiler plugins since nightly 2017-12-15.

### ISSUE THREAD

**Issue by Rantanen** [rust-lang/rust#47029]
```
PS C:\Dev\Projects\rust-plugin-test\src> rustup run nightly-2017-12-15-gnu rustc --version
rustc 1.24.0-nightly (0077d128d 2017-12-14)
```

lib.rs
```rust
#![feature(rustc_private)]
extern crate rustc_plugin;
```

Building the above file as a dylib (or alternatively using cargo and `plugin = true`) fails:

```
PS C:\Dev\Projects\rust-plugin-test\src> rustup run nightly-2017-12-15-gnu rustc lib.rs --crat
e-type dylib
error: linking with `gcc` failed: exit code: 1
  |
  = note: "gcc" "-Wl,--enable-long-section-names" "-fno-use-linker-plugin" ... // continues...
  = note: ld: cannot find -ldbghelp
```

The full error can be seen on AppVeyor for example:

https://ci.appveyor.com/project/Rantanen/intercom/build/129/job/0k9k54hkwk1f0sfw

The build works just fine on the previous nightly.

```
PS C:\Dev\Projects\rust-plugin-test\src> rustup run nightly-2017-12-14-gnu rustc --version
rustc 1.24.0-nightly (f8af59d95 2017-12-13)
PS C:\Dev\Projects\rust-plugin-test\src> rustup run nightly-2017-12-14-gnu rustc lib.rs --crat
e-type dylib
```
--------------------------------------------------------------------------

As far as I can tell, `dbghelp` is an MSVC dependency and should be omitted for the GNU toolchain.

**Comment by Rantanen** [comment]
I suspect the issue is a result of ea35192d7c3e64b8be7f694d0743d123b0c4563a, which added `backtrace` as a dependency to the `rustc` package. `backtrace` again depends on `dbghelp-sys`, which causes the linking issue I believe.

The standard library seems to use `dbghelp` through a `dlopen` instead of compile time linking: https://github.com/rust-lang/rust/blob/f1ea23e2cc72cafad1dc25a06c09ec2de8e323eb/src/libstd/sys/windows/backtrace/mod.rs#L51-L59

Wouldn't this approach work for `backtrace-rs` as well?

**Comment by retep998** [comment]
`dbghelp-sys` bundles `libdbghelp.a` so depending on it normally works. However when the precompiled version is distributed inside rustc internal crates, `libdbghelp.a` is not brought along, causing stuff to fail to link. The simplest solution on Rust's side is to simply add `libdbghelp.a` to the set of mingw import libraries that it bundles.

**Comment by mati865** [comment]
Presumably fixed by https://github.com/rust-lang/rust/pull/47280.
@Rantanen could you confirm?

**Comment by Rantanen** [comment]
Compiler plugins are now deprecated so this works even less now with the whole `rustc_plugin` being unavailable. I'm sure there's some way to get these working, but given the deprecation, I've got no motivation to figure that out. :)
