### ISSUE TITLE
llc crashes linking gfx-rs under emscripten 

### ISSUE THREAD

**Issue by kvark** [rust-lang/rust#47023]
Looks very similar to #37952 (cc @alexcrichton @s3bk):
>   Compiling gfx_app v0.8.0 (file:///home/kvark/Code/gfx)
*** Error in `/home/kvark/Code/ems/fastcomp/build/bin/llc': munmap_chunk(): invalid pointer: 0x0000000009984ab8 ***
error: linking with `emcc` failed: exit code: 1

Rust versions tested:
- "rustc 1.22.1 (05e2e1c41 2017-11-22)"
- "rustc 1.24.0-nightly (edbd7d232 2017-12-20)"

Repro steps:
```
git clone https://github.com/kvark/gfx -b emscripten
cd gfx
cargo build --example cube --target wasm32-unknown-emscripten
```
Full log: https://gist.github.com/kvark/6a0189727e67dbc950c4a140eae9646d

**Comment by nstoddard** [comment]
Does this also happen if you enable -O2 or above? I've seen something similar which went away when I enabled optimization. This might let you work around this issue until it's fixed.

**Comment by kvark** [comment]
@nstoddard you saved my day! Building with `--release` seems to work so far 👍 (as a workaround)

**Comment by alexcrichton** [comment]
A pretty huge amount has changed since this was first opened, so I'm going to close this as "pretty likely stale". If it reproduces still though feel free to reopen!
