### ISSUE TITLE
NLL ICE: unresolved type in dtorck

### ISSUE THREAD

**Issue by jedisct1** [rust-lang/rust#47022]
rustc version:
```
rustc 1.24.0-nightly (4a7c072fa 2017-12-25)
```

This is on macOS.

Enabling NLL triggers an ICE when trying to compile EdgeDNS (`nll` branch from https://github.com/jedisct1/edgedns):

```
error: internal compiler error: unresolved type in dtorck
```

This happens at link time.

**Comment by estebank** [comment]
https://github.com/rust-lang/rust/blob/master/src/librustc/ty/util.rs#L608-L611

**Comment by tbelaire** [comment]
I also get the same error with this code
https://gist.github.com/tbelaire/670ab192589311ba114b4b63d2cc681d

**Comment by tbelaire** [comment]
In particular, this line caused the ICE:

    let m = Array::from_iter(input.lines().flat_map(|l| l.as_bytes().iter().cloned()));

**Comment by vorner** [comment]
I get the same error, with a different snippet ‒ maybe it can help to cross-compare them and close on the cause.

I didn't manage to get a backtrace from rustc :-(

```rust
        fn convert(objects: Vec<LoadedObject>) -> (Vec<Body>, Vec<Graphic>) {
            objects
                .into_iter()
                .flat_map(|LoadedObject { bodies, color, .. }| {
                    bodies.into_iter()
                        .map(move |body| (body, Graphic { color: color.clone() }))
                })
                .unzip()
        }
```

Replacing the `flat_map` with `map(...).flatten()` helps (`flatten` from `itertools`).

**Comment by nikomatsakis** [comment]
I've also observed this error =) 

This is a [self-contained example](https://play.rust-lang.org/?gist=7660df2f083c27b7e32fc1f7abd8cb20&version=nightly) (based on @vorner's snippet) the seems to reproduce the problem:

```rust
#![feature(nll)]

struct LoadedObject {
    bodies: Vec<Body>,
    color: Color,
}

struct Body;

#[derive(Clone)]
struct Color;

struct Graphic {
    color: Color,
}

fn convert(objects: Vec<LoadedObject>) -> (Vec<Body>, Vec<Graphic>) {
    objects
        .into_iter()
        .flat_map(|LoadedObject { bodies, color, .. }| {
            bodies.into_iter().map(move |body| {
                (
                    body,
                    Graphic {
                        color: color.clone(),
                    },
                )
            })
        })
        .unzip()
}

fn main() {}
```

**Comment by tbelaire** [comment]
Dang, I'm getting some non-local effects with this, or something.

I had two branches which added different files and only really overlapped in main.rs and Cargo.toml (for adding deps).  Both compiled fine, but merging them caused this error to appear.

Getting rid of flat_maps seems to solve the problem though :/

**Comment by jedisct1** [comment]
@tbelaire I think this is due to incremental compilation. If you compile a project without NLL, and then add the NLL feature flag, it will compile just fine. It you `cargo clean` and rebuild it, it will fail.

**Comment by tbelaire** [comment]
Oh, that's interesting...
I'll have to play around with that once I'm home.

**Comment by nikomatsakis** [comment]
I'm digging in. I'll leave some notes here as I go.

Relevant part of the backtrace:

```
  11: rustc::ty::util::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::dtorck_constraint_for_ty
             at src/librustc/ty/util.rs:609
  12: rustc_mir::borrow_check::nll::type_check::liveness::generate
             at src/librustc_mir/borrow_check/nll/type_check/liveness.rs:192
             at src/librustc_mir/borrow_check/nll/type_check/liveness.rs:126
             at src/librustc_mir/borrow_check/nll/type_check/liveness.rs:51
  13: rustc_mir::borrow_check::nll::type_check::type_check::{{closure}}
             at src/librustc_mir/borrow_check/nll/type_check/mod.rs:116
  14: rustc_mir::borrow_check::nll::type_check::type_check_internal
             at src/librustc_mir/borrow_check/nll/type_check/mod.rs:150
  15: rustc_mir::borrow_check::nll::type_check::type_check
             at src/librustc_mir/borrow_check/nll/type_check/mod.rs:108
```

This is occurring in the liveness code.

**Comment by nikomatsakis** [comment]
Fix pending in https://github.com/rust-lang/rust/pull/47322
