### ISSUE TITLE
ManuallyDrop<T> where T: ?Sized

### ISSUE THREAD

**Issue by mikeyhew** [rust-lang/rust#47034]
`ManuallyDrop<T>` currently requires `T: Sized`. It would be nice if we could remove this restriction. I'm not sure how to do it with the current implementation using `union` though.

**Comment by jonas-schievink** [comment]
Doesn't seem possible until we get by-value DSTs

**Comment by mikeyhew** [comment]
@jonas-schievink care to explain why?

**Comment by jonas-schievink** [comment]
Ah, nevermind. It would just need to make `ManuallyDrop` unsized, too.

**Comment by mikeyhew** [comment]
The `new` and `into_inner` methods can keep could keep their `Sized` bounds, we just need to relax the `Sized` bound on the struct itself, and make sure `ManuallyDrop<T>: Unsize<ManuallyDrop<U>> where T: Unsize<U>, U: ?Sized`. Then the following code would be possible:

```rust
struct Foo<T>(ManuallyDrop<T>);

let foo = Box::new(Foo(ManuallyDrop::new(5i32))) as Box<Foo<::std::any::Any>;
```

**Comment by mikeyhew** [comment]
I guess this would be possible by allowing `union` types to be `?Sized` when there is only one variant. I was worried that would be unsound, but then I realized, the only way to create a DST `union` type would be from an unsize coercion, and then way you know what the erased `Sized` type is and can get the vtable/slice length then, just like any other unsize coercion.

**Comment by RalfJung** [comment]
See https://internals.rust-lang.org/t/pre-rfc-unions-drop-types-and-manuallydrop/8025
