### ISSUE TITLE
diagnostic for (x as uN << y) incorrectly describing the operator

### ISSUE THREAD

**Issue by whitequark** [rust-lang/rust#47045]
The diagnostic describes `<<` as a comparison operator, which is mildly confusing.
![screenshot_20171228_083437](https://user-images.githubusercontent.com/54771/34405226-01a36ec2-ebaa-11e7-84aa-985928d11d45.png)

**Comment by petrochenkov** [comment]
Fixed on nightly, with a test (https://github.com/rust-lang/rust/pull/45146).
