### ISSUE TITLE
Possibly change the ordering of integer-literal inference and method selection.

### ISSUE THREAD

**Issue by sanxiyn** [rust-lang/rust#4704]
```
fn sub(i: int) { for i.times {} }
fn main() {}
```

```
test.rs:1:17: 1:31 error: type `int` does not implement any method in scope named `times`
test.rs:1 fn sub(i: int) { for i.times {} }
                           ^~~~~~~~~~~~~~
error: aborting due to previous error
```

This works in master(2372d2c) but is broken in incoming(42b462e).

**Comment by nikomatsakis** [comment]
Fallback is back, but it happens late in the cycle, and hence you still need explicit annotation if you plan on invoking methods. This is how the RFC was written and it was no accident, I think we have no plans to change this. Closing bug.
