### ISSUE TITLE
What are the semantics of '#[thread_local] static ...' without 'mut'?

### ISSUE THREAD

**Issue by EdSchouten** [rust-lang/rust#47053]
**Background:**

I am currently working on porting Rust's libstd over to the CloudABI sandboxed runtime environment. I'm pretty close to getting it working and hope to send out a pull request in a couple of days.

As CloudABI's userspace <-> kernel ABI [is documented](https://github.com/NuxiNL/cloudabi) and [we generate Rust bindings automatically](https://docs.rs/cloudabi/0.0.1/), it's really attractive to implement libstd on top of kernel primitives as much as possible. libstd's locking primitives (mutexes, etc.) are simpler than the POSIX ones (no shared address space support, no configurable clocks, etc). This allows us to shrink condvars, mutexes and rwlocks to four bytes each.

The rwlocks implementation I wrote needs to keep track of the number of read locks acquired by the current thread [as follows](https://github.com/EdSchouten/rust/blob/3bcb9598b69d2b22c4cb31bc34226edfef686b31/src/libstd/sys/cloudabi/rwlock.rs#L22-L23):

```
#[thread_local]
static mut RDLOCKS_ACQUIRED: u32 = 0;
```

**The reason I'm filing this bug report:**

An earlier version of my code had this:

```
#[thread_local]
static RDLOCKS_ACQUIRED: u32 = 0;
```

This seemed to make the code build, but for some reason, this caused some weird behaviour, where this counter was not always incremented or decremented, causing assertions in my code to fail.

Is `#[thread_local] static` without `mut` supposed to do anything meaningful in the first place? If not, should we add a compiler warning/error for this?

**Comment by Amanieu** [comment]
I use atomic thread-local variables in my code when I need to communicate between a thread and a signal handler running on that thread.

**Comment by EdSchouten** [comment]
I suspect that that this is an issue with this code: https://github.com/rust-lang/rust/blob/cf3fefe97f23119562f824e74293420450a04f65/src/librustc/middle/mem_categorization.rs#L682-L687

By calling into `cat_rvalue_node()`, we ignore the `mutbl` argument. That function always uses`McDeclared`, even though `McImmutable` should be used instead.
