### ISSUE TITLE
Value borrowed in argument not unborrowed prior to parent function call

### ISSUE THREAD

**Issue by GavrielPlotke** [rust-lang/rust#47059]
A simple vector borrow to read a value, when done as an argument to a push to that vector fails compile
```
fn main() {
	let mut v = vec![1,1,2,4,5,10];
	let old = 3;    
	v.push(v[old]);        // Why does this fail the borrow checker?!
//	let v_next = v[old];   // When doing the argument calculation separately
//	v.push(v_next);        // compiles fine?!
	println!("Vector = {:?}", v);
}
```
I expect the above code to compile, but it fails (see below).
When I comment out the offending line, and uncomment the two lines below it (which are logically equivalent) it does compile and run correctly.
The compiler should be smart enough to see that all items temporarily borrowed in the computation of an argument are un-borrowed prior to the each subsequent argument, and prior to the execution of the parent function.
```
error[E0502]: cannot borrow `v` as immutable because it is also borrowed as mutable
 --> src/main.rs:4:9
  |
4 |     v.push(v[old]);        // Why does this fail the borrow checker?!
  |     -      ^     - mutable borrow ends here
  |     |      |
  |     |      immutable borrow occurs here
  |     mutable borrow occurs here
```

## Meta
On both stable and nightly on https://play.rust-lang.org/ as of 12/29/2017

**Comment by sfackler** [comment]
This is a known issue that will be fixed with the new non-lexical lifetimes work: https://github.com/rust-lang/rfcs/blob/master/text/2094-nll.md.

**Comment by durka** [comment]
You need to write `#![feature(nll)]` (and use nightly) to get the new borrow checking rules.

**Comment by nikomatsakis** [comment]
[builds now](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ade5b6c55c139c73994dd21ff9cd7eee) -- we already have tests for this, closing
