### ISSUE TITLE
AsciiExt::is_ascii_graphic documentation bug

### ISSUE THREAD

**Issue by mateon1** [rust-lang/rust#47067]
The documentation for https://doc.rust-lang.org/std/ascii/trait.AsciiExt.html#method.is_ascii_graphic is incorrect.

>Checks if the value is an ASCII graphic character: U+0021 '@' ... U+007E '~'. For strings, true if all characters in the string are **ASCII punctuation**.

This seems like an accidental copy-paste error from https://doc.rust-lang.org/std/ascii/trait.AsciiExt.html#method.is_ascii_punctuation

> Checks if the value is an ASCII punctuation character: U+0021 ... U+002F `! " # $ % & ' ( ) * + , - . /` U+003A ... U+0040 `: ; < = > ? @` U+005B ... U+0060 `[ \\ ] ^ _ \ ` U+007B ... U+007E ``{ | } ~` `` For strings, true if all characters in the string are ASCII punctuation.

Also, the `` ` `` quoting/escaping is inconsistent/broken for `is_ascii_punctuation`, and could be fixed, but that's a minor issue

**Comment by varkor** [comment]
The quoting issue [seems to be fixed](https://doc.rust-lang.org/nightly/std/ascii/trait.AsciiExt.html#method.is_ascii_graphic) in the nightly version of the docs.
