### ISSUE TITLE
`proc_macro::SourceFile::path()` returns a non-public type

### ISSUE THREAD

**Issue by mystor** [rust-lang/rust#47077]
This function currently returns a `syntax_pos::FileName`, which is not exported from the `proc_macro` crate. 

A good solution may be to export a `struct FileName(syntax_pos::FileName)` object which implements `Display`.

cc @jseyfried

**Comment by dtolnay** [comment]
Still a problem. [`proc_macro::SourceFile::path`](https://doc.rust-lang.org/nightly/proc_macro/struct.SourceFile.html#method.path)

**Comment by abonander** [comment]
Caused by https://github.com/rust-lang/rust/commit/d732da813bac73d2c81caddd06df3df3d9609e3d

**Comment by inquisitivecrystal** [comment]
I believe that this was fixed by #52552.
