### ISSUE TITLE
UI tests fail with useless diff when reference file has CR LF line endings

### ISSUE THREAD

**Issue by hanna-kruppe** [rust-lang/rust#47101]
I created a UI test on a windows machine. It failed with this message:

```
---- [ui] ui\issue-47094.rs stdout ----
        normalized stderr:
warning[E0566]: conflicting representation hints
  --> $DIR/issue-47094.rs:13:8
   |
13 | #[repr(C,u8)]
   |        ^ ^^

warning[E0566]: conflicting representation hints
  --> $DIR/issue-47094.rs:19:8
   |
19 | #[repr(C)]
   |        ^
20 | #[repr(u8)]
   |        ^^



expected stderr:
warning[E0566]: conflicting representation hints
  --> $DIR/issue-47094.rs:13:8
   |
13 | #[repr(C,u8)]
   |        ^ ^^

warning[E0566]: conflicting representation hints
  --> $DIR/issue-47094.rs:19:8
   |
19 | #[repr(C)]
   |        ^
20 | #[repr(u8)]
   |        ^^



diff of stderr:

 warning[E0566]: conflicting representation hints
   --> $DIR/issue-47094.rs:13:8
    |
 13 | #[repr(C,u8)]
    |        ^ ^^

 warning[E0566]: conflicting representation hints
   --> $DIR/issue-47094.rs:19:8
    |
 19 | #[repr(C)]
    |        ^
 20 | #[repr(u8)]
    |        ^^



The actual stderr differed from the expected stderr
```

Changing the line endings to LF in my editor fixed it.

**Comment by rkruppe** [comment]
Note: this would not be an issue if `update-{all-,}references.sh` were, well, not a shell script. Alas, it's not and so I am reduced to copying the expected stderr from the test failure. Admittedly, copying the `build/.../*.stderr` file (as the script does) would also avoid this error, but that's not *easier* than copying from the console output.

**Comment by nikomatsakis** [comment]
I've been wanting to rewrite the `update-references.sh` setup into something that is in pure Rust (or at least generally improve that workflow).

**Comment by Enselic** [comment]
Triage: Is this still a problem? There has been several CR LF fixes over the years. If this is still a problem, would you mind sharing the problematic test code please?
