### ISSUE TITLE
cleanup: remove field `is_import` from `def::Export`

### ISSUE THREAD

**Issue by jseyfried** [rust-lang/rust#47100]
Remove field `is_import` from `rustc::def::Export`.
The field is only used is `rustdoc` and can be [refactored away](https://github.com/rust-lang/rust/pull/47095/files#r159146038).

**Comment by Mark-Simulacrum** [comment]
@eddyb or @jseyfried This seems like a good candidate for an easy/mentor issue, perhaps one of you could provide what `!item.is_import` could be replaced with in rustdoc? The comment on the PR suggests `tcx.def_key(export.def.def_id()).parent`, but I'm not personally sure what one would *do* with that to determine whether the item is in an import statement or not.

**Comment by eddyb** [comment]
@Mark-Simulacrum You'd compare it with the `DefId` of the module you found the `Export` in.
That is, `is_import` signifies a re-export, where the definition is *somewhere else* than the module you're currently listing the `Export`s of.

**Comment by eddyb** [comment]
Depending on what is desired, the name of the original item might also be compared (because a reexport from the same module, aka `pub use self::foo as bar;`, is also possible).
