### ISSUE TITLE
String capacity is unnecessarily modified by File::read_to_string

### ISSUE THREAD

**Issue by Addisonbean** [rust-lang/rust#47114]
When using `File::read_to_string` or `BufReader::read_to_string`, the capacity of the string being written to will change, even if no change in capacity was necessary. For example:

```
use std::fs::File;
use std::io::{BufReader, Read};

fn with_buf_reader(filename: &str, capacity: usize) {
    let f = File::open(filename).unwrap();
    let mut buf = BufReader::new(f);
    let mut s = String::with_capacity(capacity);

    println!("Capacity before calling BufReader::read_to_string = {}", s.capacity());
    buf.read_to_string(&mut s).unwrap();
    println!("Capacity after calling BufReader::read_to_string = {}", s.capacity());
}

fn with_file(filename: &str, capacity: usize) {
    let mut f = File::open(filename).unwrap();
    let mut s = String::with_capacity(capacity);

    println!("Capacity before calling File::read_to_string = {}", s.capacity());
    f.read_to_string(&mut s).unwrap();
    println!("Capacity after calling File::read_to_string = {}", s.capacity());
}

fn main() {
    let filename = "test.txt";
    let capacity = 4;
    with_buf_reader(&filename, capacity);
    println!();
    with_file(&filename, capacity);
}
```

Assuming there is a file named `test.txt` containing the text `123` (no newline at the end), I would expect to this printed:

```
Capacity before calling BufReader::read_to_string = 4
Capacity after calling BufReader::read_to_string = 4

Capacity before calling File::read_to_string = 4
Capacity after calling File::read_to_string = 4
```

However, this is what actually happens:

```
Capacity before calling BufReader::read_to_string = 4
Capacity after calling BufReader::read_to_string = 32

Capacity before calling File::read_to_string = 4
Capacity after calling File::read_to_string = 32
```

Here's the version of `rustc` I am using:

```
$ rustc --version --verbose
rustc 1.22.1 (05e2e1c41 2017-11-22)
binary: rustc
commit-hash: 05e2e1c41414e8fc73d0f267ea8dab1a3eeeaa99
commit-date: 2017-11-22
host: x86_64-apple-darwin
release: 1.22.1
LLVM version: 4.0
```

**Comment by clarcharr** [comment]
This appears to be due to the `read_to_end` function which is internally used for both `Read::read_to_string` and `Read::read_to_end`.

**Comment by bluss** [comment]
@Addisonbean It's using the capacity of the String/Vec so that it can read directly into the String/Vec instead of having to buffer and copy the data one extra time. I think it doesn't do anything extra for a `BufRead`, that's indeed something it could learn to do .. but for an unbuffered `File`, IMO it's precisely the intention that the String or Vec you lend is going to be used as the buffer.

**Comment by steveklabnik** [comment]
Triage: it's not clear to me there's a bug here, but I'll let @rust-lang/libs decide.

**Comment by sfackler** [comment]
Yeah, this does not seem like a bug to me.

**Comment by Mark-Simulacrum** [comment]
Closing since we do not believe this to be a bug.
