### ISSUE TITLE
--emit=dep-info stdout support 

### ISSUE THREAD

**Issue by albizures** [rust-lang/rust#47112]
I'm working on the integration of wasm and rust into [parcel.js](https://github.com/parcel-bundler/parcel), and we want to use `--emit=dep-info` to watch the dependencies, but we are wondering if it's possible to send the output to the stdout instead of creating a file.

And btw is it doable to have a json output? this could help a bit the parsing of the dependencies from Node.

you can see our progress [here](https://github.com/parcel-bundler/parcel/issues/34) 

thanks!

**Comment by Enselic** [comment]
Triage: Closing as fixed by https://github.com/rust-lang/rust/pull/111626 which added regression tests.
