### ISSUE TITLE
unused_mut lint improvement: warn when variable only copied into closure

### ISSUE THREAD

**Issue by rphmeier** [rust-lang/rust#47128]
Minimal example of the lint failure to fire:
```
fn foo() -> bool {
    let mut res = false;
    
    let mut do_thing = move || res = true;
    do_thing();
    
    res
}
```

`foo` unconditionally returns false, but the top-level binding of `res` doesn't get an `unused_mut` warning.

**Comment by jakubadamw** [comment]
This is related to or even a duplicate of #37707.
