### ISSUE TITLE
Unused warning for type alias doesn't take into account inherent impls.

### ISSUE THREAD

**Issue by cristicbz** [rust-lang/rust#47131]
The following code ([playground](https://play.rust-lang.org/?gist=13d74fd3c77b3d2479edc7f2b509b9ef&version=stable)):
```rust
pub struct GenericFoo<T>(T);

type Foo = GenericFoo<u32>;

impl Foo {
    fn bar(self) -> u8 {
        0
    }
}

fn main() {    
    println!("{}", GenericFoo(0).bar());
}
```

results in the warning:

```
warning: type alias is never used: `Foo`
 --> src/main.rs:3:1
  |
3 | type Foo = GenericFoo<u32>;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(dead_code)] on by default
```

This is incorrect, since the `Foo` impl uses it (and it can be unwieldy to write it out otherwise).

**Comment by jsgf** [comment]
This looks like a similar case: type aliases used for trait bounds on inherent impl are not considered used: https://play.rust-lang.org/?gist=97ce92a3fe8f72c5c254878dfcfe3e21&version=nightly&mode=debug

**Comment by shepmaster** [comment]
Additional example:

```Rust
type Inner = Box<i32>;
struct Wrapper(Inner);

fn main() {
    Wrapper(Box::new(42));
}
```

```
warning: type alias is never used: `Inner`
 --> src/main.rs:4:1
  |
4 | type Inner = Box<i32>;
  | ^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(dead_code)] on by default
```

Rust 1.32.0

**Comment by Elrendio** [comment]
Hello,

I'm still having this issue on rustc 1.39.0 (4560ea788 2019-11-04), how can I know when this will be released ?

Thanks a lot !

**Comment by shepmaster** [comment]
> , how can I know when this will be released

Click on the PR that closed the issue:

![image](https://user-images.githubusercontent.com/174509/69166565-6fdde380-0ac1-11ea-9304-06e0988c2d67.png)

Click on the commits:

![image](https://user-images.githubusercontent.com/174509/69166653-96038380-0ac1-11ea-811b-262adebe0e1c.png)

Pick any of the commits, then look for the tagged version:

![image](https://user-images.githubusercontent.com/174509/69166719-b3d0e880-0ac1-11ea-8379-e73ad3b535ac.png)

**Comment by shepmaster** [comment]
> I'm still having this issue

Please provide a minimized example that demonstrates the problem.

**Comment by Elrendio** [comment]
> > I'm still having this issue
> 
> Please provide a minimized example that demonstrates the problem.

Here's a link to the playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=064177eade4f98748bacce0167eb354b

StructAlias is warned as never used yet used in the requirements of the AssociatedType of Trait2

**Comment by shepmaster** [comment]
Further reduced:

```rust
trait Trait<S> {}

type Alias = ();

trait Trait2 {
    type Type: Trait<Alias>;
}
```

```none
warning: type alias is never used: `Alias`
 --> src/lib.rs:3:1
  |
3 | type Alias = ();
  | ^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default
```

/cc @varkor — should we reopen or create a new issue?

**Comment by varkor** [comment]
This isn't the same as the original issue, so let's open a new one (there are already related issues, so it might be worth checking if this is already open elsewhere).

**Comment by Elrendio** [comment]
> This isn't the same as the original issue, so let's open a new one (there are already related issues, so it might be worth checking if this is already open elsewhere).

Do you think it's the same as #59333 ?

**Comment by varkor** [comment]
@Elrendio: that's the one I was thinking of, thanks. I've added your example there — I think they probably are the same bug (but if not, we can split out another issue then).
