### ISSUE TITLE
Never getting None from proc_macro::Span::join

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#47148]
This doesn't look right -- both sides of the comparison use `self.0.lo()`.

https://github.com/rust-lang/rust/blob/0f4ebf9f0a3196420e25cf1558b49ea3f38643c4/src/libproc_macro/lib.rs#L248-L252

Mentioning @abonander, mentioning #38356

**Comment by estebank** [comment]
the second lookup should probably be `other.0.lo()` ^_^
