### ISSUE TITLE
No warning for obsolete allocator syntax

### ISSUE THREAD

**Issue by bfops** [rust-lang/rust#47143]
The syntax for changing allocators (e.g. opting out of jemalloc) changed in a July nightly (see [#43277](https://github.com/rust-lang/rust/issues/43277) and [this discussion thread](https://users.rust-lang.org/t/upgrading-compiler-causes-application-to-hang-or-segfault-in-vec-push/14684). Users of the old syntax don't get any warning or build breakage, they just get silently changed back to the default allocator because the old syntax doesn't work anymore. It's difficult for users to track down why their program's behavior has suddenly changed without knowing about this syntax change. Case in point: the linked discussion thread is about a jemalloc-specific bug that resurfaced after this change landed, which took a reasonable chunk of time to understand.

**Comment by juleskers** [comment]
As I've raised in the thread linked by bfops, I believe we have a documentation problem here.
Usually when existing API's are deprecated (even unstable ones), we warn on the old version, for easier migration.

**Comment by SimonSapin** [comment]
We sometimes have deprecation warnings when unstable APIs change, but as far as I know it’s not a requirement and not always done. There is ~zero compatibility guarantee for unstable features between different Nightly versions.

This particular feature has just been stabilized, so I’ll close this. Up to date docs are at:

* https://doc.rust-lang.org/nightly/std/alloc/index.html
* https://doc.rust-lang.org/nightly/core/alloc/trait.GlobalAlloc.html.

If you’d like to discuss the meta policy around this or propose a change to it, I suggest opening a thread on https://internals.rust-lang.org/.
