### ISSUE TITLE
Changing a file in the middle of a build causes rustc to not pick up latest changes

### ISSUE THREAD

**Issue by bfops** [rust-lang/rust#47140]
If I change a file partway through a build then the final executable doesn't include that change. However, when I run `cargo build` again it thinks there have been no changes since the last build.

To have the build incorporate the most recent changes, I need to change the file again, build, change it back, and rebuild.

**Comment by nikomatsakis** [comment]
cc @alexcrichton

**Comment by nikomatsakis** [comment]
This is probably not, strictly speaking, a compiler bug, but rather a cargo bug?

**Comment by nikomatsakis** [comment]
(FWIW, I've also observed this behavior.)

**Comment by alexcrichton** [comment]
I believe this is probably https://github.com/rust-lang/cargo/issues/2426, so closing in favor of that.

**Comment by bfops** [comment]
Oh of course, no wonder I couldn't find an existing report - I was looking in the wrong place!
