### ISSUE TITLE
Performance regression from seemingly harmless changeset

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#47154]
https://github.com/rust-lang/rust/pull/46278 seems to have caused a noticeable performance regression:
http://perf.rust-lang.org/compare.html?start=d5f2745e7ccd247da50f0cb18318ac477e5bccbf&end=5deba220d4c42b5313d7e71731ce5e8698866684&stat=wall-time

It updates a few dependencies (e.g. flate2). Maybe they've become slower?

Anybody know what else this could be about, @rust-lang/compiler?

**Comment by alexcrichton** [comment]
My money would be on the update to log, it may be the case that 0.3.9 is slower than 0.4.0 because of the shims it introduces (just a hypothesis though). It should be very easy to convert to 0.4.0 though, just bumping cargo.toml requirements throughout the compiler

**Comment by MaloJaffre** [comment]
I am currently trying to fix this regression.

**Comment by andjo403** [comment]
was this not fixed with #47161 and #4891 so this can be closed now?

**Comment by michaelwoerister** [comment]
Yes, it was. Thanks for the hint, @andjo403!
