### ISSUE TITLE
Why is `SeekFrom` defined with 64-bit integers rather than machine-dependent ones?

### ISSUE THREAD

**Issue by sanmai-NL** [rust-lang/rust#47166]
[`SeekFrom`](https://doc.rust-lang.org/std/io/enum.SeekFrom.html)

Aren’t those addresses machine-dependent?

**Comment by est31** [comment]
You can have a 50 GB file on a 32 bit computer. If you had 32 bit integers, you couldn't seek around, at least not with absolute offsets. Other than that, I don't know.

**Comment by steveklabnik** [comment]
Some history time! https://github.com/rust-lang/rfcs/blob/master/text/0517-io-os-reform.md#seeking shows a trait that's the same as today's:

it also says

> the seek signature is refactored with more precise types:

What about that more precise types? well, let's look at Rust 0.11: https://doc.rust-lang.org/0.11.0/std/io/trait.Seek.html

```rust
pub trait Seek {
    fn tell(&self) -> IoResult<u64>;
    fn seek(&mut self, pos: i64, style: SeekStyle) -> IoResult<()>;
}
```

So, the old `pos` + [`SeekStyle`](https://doc.rust-lang.org/0.11.0/std/io/type.SeekStyle.html) got changed to `SeekFrom`, which includes the data as well as the direction to seek.

It seems that this is basically an oversight. However, remember that signed types have half their range. So, if you were on a 32 bit machine, and you were at the end of a huge memory structure, yet wanted to go back to the start, you'd need something bigger than an `isize`.

Anyway, we try to keep the issue tracker for bugs, and even if this is a bug, we cannot fix it thanks to backwards compatibility. More discussion on this should probably be on https://internals.rust-lang.org/, so I'm going to give it a close. Thanks!
