### ISSUE TITLE
stage0.txt: Shouldn't "dev: 1" be commented out for a stable release?

### ISSUE THREAD

**Issue by mneumann** [rust-lang/rust#47196]
At least according the the comments in stage0.txt.

https://github.com/rust-lang/rust/blob/766bd11c8a3c019ca53febdcd77b2215379dd67d/src/stage0.txt#L37

I am compiling rust 1.23.0 from 1.22.1, and it gives me the following errors:

```
Compiling core v0.0.0 (file:///data2/build/rust-1.23.0/rustc-1.23.0-src/src/libcore)
error: expected one of `)` or `,`, found `=`
    --> src/libcore/slice/mod.rs:1049:13
     |
1049 |         (0..=self.end).get(slice)
     |             ^ expected one of `)` or `,` here

error: expected one of `)` or `,`, found `=`
    --> src/libcore/slice/mod.rs:1054:13
     |
1054 |         (0..=self.end).get_mut(slice)
     |             ^ expected one of `)` or `,` here

error: expected one of `)` or `,`, found `=`
    --> src/libcore/slice/mod.rs:1059:13
     |
1059 |         (0..=self.end).get_unchecked(slice)
     |             ^ expected one of `)` or `,` here

error: expected one of `)` or `,`, found `=`
    --> src/libcore/slice/mod.rs:1064:13
     |
1064 |         (0..=self.end).get_unchecked_mut(slice)
     |             ^ expected one of `)` or `,` here

error: expected one of `)` or `,`, found `=`
    --> src/libcore/slice/mod.rs:1069:13
     |
1069 |         (0..=self.end).index(slice)
     |             ^ expected one of `)` or `,` here

error: expected one of `)` or `,`, found `=`
    --> src/libcore/slice/mod.rs:1074:13
     |
1074 |         (0..=self.end).index_mut(slice)
     |             ^ expected one of `)` or `,` here
```

**Comment by est31** [comment]
cc @alexcrichton

**Comment by alexcrichton** [comment]
I don't know about the errors you're seeing but yes the `dev` bit should be commented out. In doing so the date would need to change as well. Forgot to do it for this beta, I'm adding a check to make sure we don't forget again.

**Comment by mneumann** [comment]
@alexcrichton: hm, I tried to build 1.23.0 with stable 1.22.1, and I got these errors. I wonder if I need the -dev version of 1.22.1 instead to build 1.23.0. Hm, the version I use is not beta, it is stable, or am I missing something?

**Comment by alexcrichton** [comment]
The `dev` bit here is a bit of a misnomer, it should byte-for-byte be the same artifacts you'd get otherwise, they're just downloaded from the wrong location. For the compile errors it may mean that there's either a bug or it's misconfigured locally

**Comment by mneumann** [comment]
@alexcrichton : thanks for the explanation. the error I am seeing is because I had both ```--enable-local-rust``` AND ```--local-rust-root``` passed to ```configure``` and the first was taking precedence. Fixed by removing ```--local-rust-root```.
