### ISSUE TITLE
Provide readable changelogs.

### ISSUE THREAD

**Issue by bmusin** [rust-lang/rust#47207]
Hi. Could you please provide more readable changelogs with use cases?

It's not easy to
extract relevant snippet or command, if any, from pull request discussion
Being overly technical and dry, 
that discourages further adoption of otherwise, decent, compiler.

**Comment by LifeIsStrange** [comment]
+1

**Comment by durka** [comment]
There are release notes: https://github.com/rust-lang/rust/blob/master/RELEASES.md

**Comment by LifeIsStrange** [comment]
@durka Of course, but there are no releases notes for the beta and nightly releases, so the power users take the unstability and compatibility breakages of beta and nightly, without easily knowing what are the compatibility changes and without knowing what new features/improvments they can use...

So, logically, a side effect of making those releases notes would be to grow the beta/nightly user base, and so virtuously, increasing the number of bug reports, and thus the stability.
I think that's an easy p-high candidate to do.

**Comment by bltnkl** [comment]
@durka, changelogs is nice, but the code examples are missing.
For instance, it's not easy to undertstand how to use
https://github.com/rust-lang/rust/pull/45379 - impl FromIterator<()> for () - title isn't clear enough, how can one use it.

**Comment by jamessan** [comment]
> There are quite readable release notes

Although, an outdated version is included in the release.  The rust-1.23.0-src.tar.gz contains a RELEASES.md describing 1.22.0.

**Comment by steveklabnik** [comment]
I'm going to give this a close. @bmusin , I can appreciate that a CHANGELOG would be nice, but we already do release notes, and a blog post. We don't have the capacity to commit to yet another list of changes to Rust. 

I'm also not sure that a changelog would do what you want; code snippits are not a thing usually in the changelog.

If something is confusing to use, please open up one bug per thing; we can improve the docs individually, but a CHANGELOG isn't a commitment we can make at this time. Thanks for understanding.
