### ISSUE TITLE
File read_at, non-mutable platform independent version

### ISSUE THREAD

**Issue by PSeitz** [rust-lang/rust#47229]
I have multiple threads reading from a `std::fs::File` handle. The existing Read Trait for File is not so nice in this case because of the mutability`&mut File`. I created the non-mutable platform independent version from the plattform specific counterparts like below.
It would be nice to have this in the standard library.

```rust

#[cfg(any(windows))]
fn load_exact_bytes_at(buffer: &mut Vec<u8>, file: &File, offset: u64) {
    use std::os::windows::fs::FileExt;
    let mut data_read = 0;
    while data_read < buffer.len() {
        data_read += file.seek_read(buffer, offset).unwrap();
    }
}

#[cfg(any(unix))]
fn load_exact_bytes_at(buffer: &mut Vec<u8>, file: &File, offset: u64) {
    use std::os::unix::fs::FileExt;
    let mut data_read = 0;
    while data_read < buffer.len() {
        data_read += file.read_at(buffer, offset).unwrap();
    }
}
```

**Comment by ranma42** [comment]
Assuming that `seek_read` actually changes the current position of the file, I am afraid the missing `mut`ability on the `self` argument was overlooked.

**Comment by PSeitz** [comment]
@tbu-  mentions only WriteFile here: https://github.com/rust-lang/rust/pull/35704#issuecomment-242339887, but the `seek_write` version is not `&mut` https://doc.rust-lang.org/std/os/windows/fs/trait.FileExt.html#tymethod.seek_write

**Comment by rkruppe** [comment]
`&File` implements `Read` so reading from multiple threads is perfectly possible.

**Comment by PSeitz** [comment]
I know this is possible, but the unnecessary(?) mut complicates things (a lot in my case).

**Comment by tbu-** [comment]
Here's how to read from a immutable reference to a file:

```
use std::fs::File;
use std::io::Read;
use std::io;
fn read(mut file: &File) -> io::Result<()> {
    let mut buf = [0; 4];
    (&mut file).read(&mut buf)?;
    Ok(())
}
```

Your implementation of `load_exact_bytes_at` (and the write counterpart) is buggy if the operating system returns with a short read (write), or if the operating system returns an error.

**Comment by rkruppe** [comment]
@PSeitz Complicates how? You already have a `&File`. You just need to add a `mut` to the binding (the `file: &File` parameter or local) that you want to call the method on. No function signature or type change, no lifetime annotations change, etc., just a simple three letters for (at most) every `Read` method call. That doesn't seem like a significant burden, and especially not like one big enough to introduce a whole new API.

**Comment by PSeitz** [comment]
Okay, I thought a `&mut` was required. In this case, I don't understand how e.g. that snippet below works. Is this a race condition? Does Rust protect me from race conditions on a single file handle?

```rust

extern crate rayon;
use std::io::SeekFrom;
use std::io::prelude::*;
use std::fs::File;
use rayon::prelude::*;

fn main() {

    let file =  File::open("file").unwrap();
        
    [0,1].par_iter()
        .for_each(|p| {
            let mut bytes = vec![];
            bytes.resize(8, 0);
            load_bytes(&mut bytes, &file, *p as u64);
        });

}

fn load_bytes(buffer: &mut Vec<u8>, mut file: &File, offset: u64) {
    file.seek(SeekFrom::Start(offset)).unwrap();
    file.read_exact(buffer).unwrap();
}
```

**Comment by rkruppe** [comment]
A `&mut self` *is* required, but since the impl is for `&File`, the self parameter is a `&mut &File`.

> In this case, I don't understand how e.g. that snippet below works. Is this a race condition? Does Rust protect me from race conditions on a single file handle?

The file I/O is racy, yes. Rust does not provide guaranteed protection from "logical races", just from *data races*. The operating systems' I/O operations are data-race-free even when multiple threads work on the same file, but even a single I/O operation is rarely atomic (e.g., a read might get interrupted). Multiple separate operations (such as the `seek` and `read_exact` in your example) *can't* be atomic without external synchronization. Therefore, working on the same file from multiple threads is generally very wrong (unless there's other synchronization between the threads).

**Comment by PSeitz** [comment]
> Therefore, working on the same file from multiple threads is generally very wrong (unless there's other synchronization between the threads).

Do you mean file or std::fs::File? Do you refer to that read-only scenario?

I thought read-only with multiple file handles should be no problem.
Multiple threads with read and writes are of course bad without extra synchronization.

It would be nice if the API was designed, to protect from races on a single std::fs::File.

**Comment by rkruppe** [comment]
> Do you mean file or std::fs::File? Do you refer to that read-only scenario?

I meant the `std::fs::File` type.

> I thought read-only with multiple file handles should be no problem.

A `std::fs::File` object has a current read position, which is changed any time you read or seek.

>  Multiple threads with read and writes are of course bad without extra synchronization.

Yes (though again, just a race, not a data race).

> It would be nice if the API was designed, to protect from races on a single std::fs::File.

Maybe, but backwards compatibility prevents us from changing this.


---

Can this issue be closed now? It seems the proposed API is no longer needed. If you have any further *questions*, I'd direct you to http://users.rust-lang.org/ or other forums.
