### ISSUE TITLE
Stage1 compiler doesn't have error explanations

### ISSUE THREAD

**Issue by rkruppe** [rust-lang/rust#47249]
On x86_64-*-msvc, while running stage1 tests on clean checkout of 6828cf90146c7fefc4ba4f16dffe75f763f2d910, two tests (`ui/lint/use_suggestion_json.rs` and `ui/explain.rs`) fail because the stage1 compiler doesn't output long error explanations. 

Edit: Initially thought this only affected JSON output but `rustc +stage1 --explain` reports "error: no extended information for EXXXX".

**Comment by zackmdavis** [comment]
(Probably due to 8c9bf663d4a8074e4955d1ad3f85a3b82e946297)

**Comment by pnkfelix** [comment]
Should we move these two tests into the `ui-fulldeps/` directory? (If I recall correctly, the test directories with suffix `-fulldeps` are the ones that are only meant to work with stage > 1 compilers, which it sounds like this is an instance of, unless I misunderstand 8c9bf66 ...)

**Comment by rkruppe** [comment]
I don't fully understand the commit in question, but it doesn't look to me like this limitation of stage1 compilers is intended or unavoidable. If possible without unreasonable hacks, I would err on the side of fixing this rather than making stage1 compilers different in yet another way. cc @alexcrichton

**Comment by alexcrichton** [comment]
Yes this is a limitation of the current stage1 compiler, after the next bootstrap this limitation will go away. If someone's got a better idea for a fix though I'm all ears!

**Comment by rkruppe** [comment]
Ok, if the problem will fix itself in six weeks, we can just sit out.
