### ISSUE TITLE
Export cfg_if macro

### ISSUE THREAD

**Issue by MOZGIII** [rust-lang/rust#47257]
I was seeking a was to split files for platfrom-dependent code, and found uses of `cfg_if` in rust source tree.
However, that macro is not exported, so I can't use it in my app. Why is that and can we export it?

PS: I'm new to rust.
Using rust stable: rustc 1.23.0 (766bd11c8 2018-01-01)

**Comment by sfackler** [comment]
You can pull it in from crates.io: https://crates.io/crates/cfg-if

**Comment by MOZGIII** [comment]
That's good to know. I'll definetly be using that crate for now.
Still curious about the why it's not in a standard library. Could you please point me to the right place to ask this question if it's not appropriate here?

**Comment by Manishearth** [comment]
In general there's a very high bar for things being moved into the stdlib.
