### ISSUE TITLE
incr.comp.: Optimize DepGraph::try_mark_green()

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#47293]
`DepGraph::try_mark_green()` is a rather hot function, especially in compilation sessions that see a lot of re-use. It can probably be made faster by:
- [x] using an array instead of a hashmap for storing node colors,
- [ ] and maybe, by re-using the `current_deps` vector among recursive invocations or using a `SmallVec` (although such optimizations can easily backfire, so proper profiling is needed here).

**Comment by michaelwoerister** [comment]
https://github.com/rust-lang/rust/pull/48206 implements the first bullet point.

**Comment by gizmondo** [comment]
Should be closed per #50565?

**Comment by wesleywiser** [comment]
Indeed, thanks @gizmondo!
