### ISSUE TITLE
incr.comp.: Speed up result hashing and DepNode computation by caching certain stable hashes

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#47294]
Incremental compilation often spends quite a bit of time computing stable hashes of various things. Profiling shows that a large part of this time is spent hashing `AdtDef` and ~~`Substs`~~ `ty::Slice` values. In both cases it is likely that the same values are hashed over and over again. It's worth investigating whether doing some caching here, [as we do for macro expansion contexts](https://github.com/rust-lang/rust/blob/2e33c89ff1518359c4bd5fbed1571ea00cb3b146/src/librustc/ich/hcx.rs#L357-L380), is viable and brings speed ups.

**Comment by wesleywiser** [comment]
I'd like to take this. Is there a good test case I can use to measure the speedup?

**Comment by michaelwoerister** [comment]
Great, thank you @wesleywiser!

You should see speedups in all incremental builds. In debug builds they should be more pronounced. In builds with an empty cache the absolute compile time difference should be greater because those builds have to do the most result hashing. In builds with a full cache there should also be a speedup but it might be small. Result hashes are loaded from disk in this case but the compiler still needs to hash types when constructing DepNode UUIDs.

I also recommend that just do the implementation and, when it works, open a PR. Then we'll let @bors do a try-build and run that through [perf.rlo](http://perf.rust-lang.org/). That will give us a broader idea of the performance impact.

The two implementations that need updating are:
https://github.com/rust-lang/rust/blob/619ced057842a25f8700237a9c22a6f5c318a954/src/librustc/ich/impls_ty.rs#L23-L31
and:
https://github.com/rust-lang/rust/blob/619ced057842a25f8700237a9c22a6f5c318a954/src/librustc/ty/mod.rs#L1475-L1491

The nice thing about these interned data structures is we can use their memory address as hashmap key. I suggest you get the address like this:
```rust
impl<'gcx> HashStable<StableHashingContext<'gcx>> for AdtDef {
    fn hash_stable<W: StableHasherResult>(&self,
                                          hcx: &mut StableHashingContext<'gcx>,
                                          hasher: &mut StableHasher<W>) {
        let cache_key = self as *const AdtDef as usize;
        ...
    }
}
```
The rest should look very similar to the implementation for expansion contexts:
https://github.com/rust-lang/rust/blob/2e33c89ff1518359c4bd5fbed1571ea00cb3b146/src/librustc/ich/hcx.rs#L357-L380
Please cache the full `Fingerprint` though, not just half of it as in the implementation above.
