### ISSUE TITLE
failure to deduce exact vector capacity if vector filled via loop from constant vec

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#47296]
````rust
fn main() {
    let vec1 = vec![1, 2, 3, 4, 5, 6, 8, 9, 10, 11];
    let mut vec2 = Vec::new();
    for i in &vec1 {
        vec2.push(i);
    }
    println!("vec1 len {}", vec1.len()); // 10
    println!("vec1 cap {}", vec1.capacity()); // 10

    println!("vec2 len {}", vec2.len()); // 10
    println!("vec2 cap {}", vec2.capacity()); // 16
}
````
Playground: https://play.rust-lang.org/?gist=5127e3f31e4997a2a8947533f699d64e&version=nightly

There is no control flow inside the loop so imo rustc should be able to know that  vec2.capacity() = vec1.len() is sufficient, especially since vec1 is immutable.
Faux from ````##rust```` on freenode provided this example where rust was able to deduce optimal vec capacity:
````rust
fn main() {
    let vec1 = vec![1, 2, 3, 4, 5, 6, 8, 9, 10, 11];
    let vec2: Vec<usize> = vec1.iter().cloned().collect();
    println!("vec1 len {}", vec1.len()); // 10
    println!("vec1 cap {}", vec1.capacity()); // 10

    println!("vec2 len {}", vec2.len()); // 10
    println!("vec2 cap {}", vec2.capacity()); // 10
}
````
Playground: https://play.rust-lang.org/?gist=20a6d092f3ed2db4a85898599ccd423d&version=nightly
  
rustc 1.25.0-nightly (b5392f545 2018-01-08)

**Comment by Mark-Simulacrum** [comment]
That's not a deduction, that's an optimization in `FromIterator` for `Vec<T>`... I don't think this is really something that rustc will (ever) be able to do, but for now leaving open and marking as an LLVM bug.

**Comment by rkruppe** [comment]
The capacity is observable behavior (as the programs above show) so LLVM will never change it.

**Comment by Mark-Simulacrum** [comment]
Ah, that makes sense. Then I think I'm going to close since it's unlikely that there's anything in particular that we can do for this.
