### ISSUE TITLE
[partitioning] Don't create CGUs below a certain size

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#47318]
As a followup to #47316: Once we have a more accurate metric for CGU-size, we can also make sure to not sub-divide the program into smaller units than makes sense -- i.e. we don't want to have programs consisting of 16 one-function object files. We'd first have to find out concrete values for what is "too small" though. And I expect this to have little impact in practice. Consider it a mostly aesthetic improvement.

**Comment by michaelwoerister** [comment]
I have no data to back this up but this might allow to reduce our bootstrap time because it would affect most test cases? cc @rust-lang/infra

**Comment by aidanhs** [comment]
Just to re-state to make sure i understand: the intention would be to speed up bootstrap, while avoiding the test slowdown seen in https://github.com/rust-lang/rust/pull/44675#issuecomment-331581508 by ensuring multiple codegen units doesn't penalise many tiny compiles?

**Comment by michaelwoerister** [comment]
The hope would be that most test cases, which are usually small, would end up being compiled to just one codegen unit. As a result, compiling each test case would be faster because we are skipping unnecessary overhead that is introduced by splitting things into multiple CGUs.

This could be tested by making `compiletest` set `-Ccodegen-units=1` for `run-pass` for example. If that makes the test suite execute faster then the optimization proposed here could be tuned to do so too.

**Comment by aidanhs** [comment]
Sounds like the previous PR might be worth looking at again as low hanging fruit then, with this being a more robust solution.

**Comment by Mark-Simulacrum** [comment]
This seems to have been implemented: https://github.com/rust-lang/rust/blob/30dfb9e046aeb878db04332c74de76e52fb7db10/compiler/rustc_monomorphize/src/partitioning.rs#L385 in https://github.com/rust-lang/rust/pull/112448.
