### ISSUE TITLE
Experiment with sharing monomorphized code between crates

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#47317]
At the moment the compiler will re-instantiate generic code in every crate that uses it. That sounds like a lot of duplicated work. However, we don't have any actual numbers on how much duplicated work. There are a few things we could do:
* Instrument the compiler to count how many duplicated functions we have
* Prototype sharing of generic code and see how it affects compile times and binary sizes
* Wait for [MIR-only RLIBs](https://github.com/rust-lang/rust/issues/38913) to solve the problem naturally.

This could potentially be a big win for compile times but we won't know until we've collected some data.

Side node: Sharing monomorphized instances could negatively affect runtime performance when compiling without any form of LTO or when compiling with ThinLTO just for the current crate (as opposed to doing ThinLTO over the whole crate graph).

**Comment by brson** [comment]
https://github.com/rust-lang/rust/issues/47660 indicates a check box next to this task, but it is still open and doesn't indicate progress. Is this done?

**Comment by michaelwoerister** [comment]
This has been implemented in https://github.com/rust-lang/rust/pull/48779 and is enabled by default for optimization levels <= 2:
https://github.com/rust-lang/rust/blob/f694222887cf31f51e68927716c25736e62f037f/src/librustc/session/config.rs#L650-L664

https://github.com/rust-lang/rust/pull/50861 tested enabling it for optimized builds showed mixed results:
https://perf.rust-lang.org/compare.html?start=fd18d2537ddcffb24b3739393b085ed28dfc340e&end=b60bd5703773a04cd853519fdc2465dc9d45603d&stat=instructions%3Au

**Comment by brson** [comment]
Thanks @michaelwoerister
