### ISSUE TITLE
Make std available to proc macro root in phase 1

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#47314]
Following up on https://github.com/rust-lang/rust/issues/38356#issuecomment-354853399.

> Right now, the prelude is in scope at the definition site (unless the proc-macro crate is `#![no_implicit_prelude]`) and this is an accident (in some sense) due to the phase 0 vs phase 1 distinction as you point out.
>
> However, I think that phase 1 should implicitly contain `std` at the proc-macro root (so that you can always `quote!(use std::...);`) and the prelude for convenience/ergonomics and since these are already implicit in phase 0. There will be a PR to add `std` at the root in phase 1 soon.

The following procedural macro invocation should compile and print `None`.

```rust
#![feature(proc_macro)]

extern crate proc_macro;
use proc_macro::{quote, TokenStream};

#[proc_macro]
pub fn none(input: TokenStream) -> TokenStream {
    quote! {
        // Works currently, because `None` is in the prelude.
        //None::<$input>

        // Does not work, but should.
        std::option::Option::None::<$input>
    }
}
```

```rust
#![feature(proc_macro)]

extern crate mac;

fn main() {
    println!("{:?}", mac::none!(u8));
}
```

@jseyfried

**Comment by petrochenkov** [comment]
Another alternative (was decided somewhere in https://github.com/rust-lang/rfcs/pull/2126, but never put into the RFC text) is to add the name `std` into the libstd prelude.

This can be done either through old `$crate` (`pub use $crate as std;`), or new `crate` (`pub use crate as std;`), but not right now because there are some bugs.

**Comment by petrochenkov** [comment]
This is
- fixed on 2018 edition, `::std::foo` will certainly resolve to an extern crate named `std`
- mostly fixed on 2015 edition, `std::foo` will resolve to an extern crate named `std` unless it's shadowed by something also named `std`.
