### ISSUE TITLE
incr.comp.: Use a struct-of-arrays instead of an array-of-structs for SerializedDepGraph

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#47326]
This should improve memory consumption and cache locality a bit because we are wasting space on padding bytes at the moment. It should also enable us to bulk-persist parts or all of the graph to disk at once instead of dealing with each value separately.

**Comment by michaelwoerister** [comment]
Some more information: The thing that could be refactored here is the `nodes` field in `SerializedDepGraph`:
https://github.com/rust-lang/rust/blob/24e679c375da94b0f7db732c45c4c53724e8854d/src/librustc/dep_graph/serialized.rs#L23

At the moment it is an array of `(DepNode, Fingerprint)` but it could be turned into two arrays, one for `DepNode`, one for `Fingerprint`. 

Then the following step in `DepGraph::serialize()` would not be necessary:
https://github.com/rust-lang/rust/blob/24e679c375da94b0f7db732c45c4c53724e8854d/src/librustc/dep_graph/graph.rs#L479-L482

One could even try to not copy the arrays at all in `DepGraph::serialize()`. Instead one could use `std::mem::swap()` to exchange the data in `DepGraph` for empty arrays and then just move it into the returned `SerializedDepGraph`. This would leave the dep-graph in an invalid state though. Not sure if we access it again after serialization (some code might still read from it).

**Comment by wesleywiser** [comment]
I can take this.

**Comment by michaelwoerister** [comment]
Cool! Thanks, @wesleywiser!
