### ISSUE TITLE
proc_macro and no_std

### ISSUE THREAD

**Issue by nhynes** [rust-lang/rust#47342]
tl;dr: Trying to port serde to a `no_std` environment requires proc_macro to also be `no_std`. The straightforward approach of subbing out the `std` types in the compiler internals doesn't work.

The specific use case is Intel SGX via rust-sgx-sdk, which provides an  alternative `std`. `extern crate sgx_tstd as std;` doesn't work in the compiler for some reason. Is this a particularly unreasonable goal?

The most related issue I could find is https://github.com/rust-lang/rfcs/pull/1184 but it looks like there ended up being no easy way to inject `no_std` into everything!

**Comment by sfackler** [comment]
Isn't proc_macro only going to be used by the host for the compiler plugin?

**Comment by nhynes** [comment]
@sfackler that's a good point. I changed the dependency to vanilla `serde_derive` and it seemed to work. Thanks for your help!
