### ISSUE TITLE
Performance regression on pest in newest nightly

### ISSUE THREAD

**Issue by dragostis** [rust-lang/rust#47356]
Running the benchmark in  [`pest_grammars`](https://github.com/pest-parser/pest/tree/master/pest_grammars) on current nightly vs nightly `2017-12-04` yields 56% performance regression.

Current:
```
test data ... bench:      72,455 ns/iter (+/- 13,575)
```

`2017-12-04`:
```
test data ... bench:      46,380 ns/iter (+/- 1,352)
```

**Comment by alexcrichton** [comment]
I believe this is a result of https://github.com/rust-lang/rust/pull/46910 where LLVM's making a different inlining decision in the ThinLTO phases than it previously did when everything was in one codegen unit. That PR was merged [with prior knowledge](https://github.com/rust-lang/rust/issues/45320#issuecomment-337957101) that it would not yield a 100% across-the-board improvement in all cases. 

That being said, it's not clear why an inlining decision wasn't made here! The difference can be verified by adding:

```toml
[profile.bench]
codegen-units = 1
```

to the `Cargo.toml` at the root, and `cargo bench` should go back to what it previously was.

**Comment by nikomatsakis** [comment]
OK, based on @alexcrichton's analysis I'm going to close this issue as being an expected byproduct of enabling ThinLTO. @dragostis you might want to consider adding `#[inline]` to some of your hot methods; hopefully profiling could help you find which ones. Thanks for the report!
