### ISSUE TITLE
Shouldn't the "use of unstable library feature" error have an error number?

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/rust#47397]
I thought every error was supposed to have a number that one could look up in the [error index](https://doc.rust-lang.org/error-index.html), run `rustc --explain` with, etc... but if I run this code with stable rust 1.23.0:

```
fn testl() {
    ::std::u128::MAX;
}
```

I get: 

```
error: use of unstable library feature 'i128' (see issue #35118)
 --> src/lib.rs:2:5
  |
2 |     ::std::u128::MAX;
  |     ^^^^^^^^^^^^^^^^
```

Rather than `error[E0644]` or something.

Feel free to close if this was a deliberate decision.

**Comment by GuillaumeGomez** [comment]
Every error should have an error number! I'm adding it.
