### ISSUE TITLE
Symbolication info for inlined functions

### ISSUE THREAD

**Issue by michaeleiselsc** [rust-lang/rust#47403]
When I debug my iPhone app, I'll see stack traces with several Rust functions missing from the stack because they've been inlined and because, I imagine, Rust doesn't generate symbolication info for these functions. This makes debugging crashes from users in the wild much more difficult. Objective-C and C++ have symbolication info for inlined functions, so it seems doable for Rust as well.

Is there any existing way to symbolicate inlined functions? If not, +1 for this. Thanks!

**Comment by sfackler** [comment]
Are you compiling with debug info? Information about inlined functions is present there.

**Comment by michaeleiselsc** [comment]
Yes, here's the rustc command:
```
rustc --crate-name logger src/lib.rs --crate-type staticlib --emit=dep-info,link -C debuginfo=2 -C metadata=f737789f9be51d9b -C extra-filename=-... --out-dir ... -L dependency=... --extern ...
```

**Comment by sfackler** [comment]
Symbolicators that look at debuginfo should be able to resolve the inlined functions then.

**Comment by michaeleiselsc** [comment]
Ah my bad, yeah it turns out I had the settings wrong on the actual build being run
