### ISSUE TITLE
Integrate front::test and rustpkg into the syntax extension framework

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#4741]
Both `--test` and now `rustpkg` apply a type of syntax extension that is different from those in `ext`. These apply some global transformations, including replacing `main`, so they aren't applied by default. The test extension is actually a compiler pass that runs on all input, but  it only does anything when in the `test` configuration`--cfg test` (indirectly by `--test`). `rustpkg` is similar but driven by the `rustpkg` command. I imagine there will be others.

**Comment by steveklabnik** [comment]
Re-traige: it seems `rustc::front` is gone too, so I'm iving this a close.
