### ISSUE TITLE
The error message when a function returns the wrong type is not very clear

### ISSUE THREAD

**Issue by Prim3val** [rust-lang/rust#47411]
Take this simple example:

```
fn foo(bar: u64) -> u64 {
    6 as i64
}

fn main() {
    foo(6);
}
```
This produces the following error
``` -
-> src/main.rs:2:5
   |
 2 |     6 as i64
   |     ^^^^^^^^ expected u64, found i64
```

I don't think it's very clear, because the error message doesn't even mention the function we are in. In this simple example, anyone sees the problem, but I think the message could still be a bit clearer. I would suggest something like this:

``` -
-> src/main.rs:2:5
   |
 2 |     6 as i64
   |     ^^^^^^^^ expected u64, found i64
-> src/main.rs:2:5
  |
 2 |     6 as i64
   |     ^^^^^^^^ this value is returned by the function foo, which is expected to return an u64
```

**Comment by estebank** [comment]
What version of the compiler are you running? [Latest stable points at the return type as a terse explanation](https://play.rust-lang.org/?gist=e4c4c66470e4ad1673c8572e84f57863&version=stable):

```
error[E0308]: mismatched types
 --> src/main.rs:2:5
  |
1 | fn foo(bar: u64) -> u64 {
  |                     --- expected `u64` because of return type
2 |     6 as i64
  |     ^^^^^^^^ expected u64, found i64
```

That feature still needs some tweaking (as it gets triggered in at least one incorrect case), but how would you modify the current output to make it clearer?
