### ISSUE TITLE
Support trailing commas in lint_array

### ISSUE THREAD

**Issue by theotherphil** [rust-lang/rust#47428]
https://github.com/rust-lang-nursery/rust-clippy/pull/2350#discussion_r161404874

**Comment by kennytm** [comment]
Basically just change this macro to recognize and discard the trailing comma.

https://github.com/rust-lang/rust/blob/adc9d86363e0997f8378ea0260dfec3a9d09bcf0/src/librustc/lint/mod.rs#L98-L105

**Comment by durka** [comment]
That macro declaration is formatted in a weird way. But it should be enough to add `$(,)*` to the rule (unless accepting multiple trailing commas is undesired). I could mentor.

**Comment by mark-i-m** [comment]
How about this:
```rust
macro_rules! lint_array { 
    ($( $lint:expr ),*,) => { lint_array!( $( &$lint ),* ) };
    ($( $lint:expr ),*) => {{ 
         //static ARRAY: LintArray = &[ $( &$lint ),* ]; 
         //ARRAY 
    }} 
} 
```

**Comment by mark-i-m** [comment]
Out of curiosity, why doesn't rust allow trailing commas after `$(pat),*` automatically? Does it make it hard to write some macros? Alternately, why isn't there a `?` (optional) repetition specification (e.g. `$(pat)?` would be 0 or 1 times)?

**Comment by durka** [comment]
The extra rule is fine too. It's just more annoying (extra repetition). And
there's no technical reason not to support one-or-none patterns as far as
I'm aware.

**Comment by mark-i-m** [comment]
Made a PR :)
