### ISSUE TITLE
`termination_trait` feature doesn't allow implementing `Termination`

### ISSUE THREAD

**Issue by mystor** [rust-lang/rust#47430]
@ilianaw wrote this code snippet which reports an error complaining that the `#![feature(termination_trait)]` is required, despite the feature flag being present.

```rust
#![feature(termination_trait)]

use std::Termination;

struct Exit(i32);

impl Termination for Exit {
    fn report(self) -> i32 {
        self.0
    }
}

fn main() -> Exit {
    println!("Hello, world!");
    Exit(0)
}
```
https://play.rust-lang.org/?gist=61a56434dc46e785cb59bf7610233288&version=nightly

**Comment by scottmcm** [comment]
Looks like this can be closed now; it correctly talks about `termination_trait_lib`
```rust
error[E0658]: use of unstable library feature 'termination_trait_lib' (see issue #43301)
 --> src/main.rs:3:5
  |
3 | use std::process::Termination;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(termination_trait_lib)] to the crate attributes to enable
```
https://play.rust-lang.org/?gist=167e30345bb0ad15135cbdae8cf1215f&version=nightly
