### ISSUE TITLE
app_dirs crate no longer builds on nightly

### ISSUE THREAD

**Issue by jdm** [rust-lang/rust#47466]
```
   Compiling app_dirs v1.1.1
error[E0619]: the type of this value must be known in this context
  --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/app_dirs-1.1.1/src/imp/platform/macos.rs:10:40
   |
10 |         Ok(Component::RootDir.as_ref().into())
   |                                        ^^^^
error: aborting due to previous error
```
This is a regression from nightlies from a month ago.

**Comment by jdm** [comment]
This regressed between the 1/12 and 1/13 nightlies, so the range is 73ac5d6a8..51b0b3734.

**Comment by jdm** [comment]
I suspect https://github.com/rust-lang/rust/commit/e0855ff4a13ea79daa56d23a25f827fe86e8147b out of that range. cc @Diggsey

**Comment by jdm** [comment]
The relevant code is https://github.com/AndyBarron/app-dirs-rs/blob/ab58239b56fd5bbad8e47ce97051b74f6a68a066/src/imp/platform/macos.rs#L8-L10.

**Comment by Diggsey** [comment]
According to the stability guidelines, it is acceptable to change type inference in ways that may occasionally require new type annotations. However, if this has a wider impact than just one crate, it may be worth reverting - I don't feel qualified to make that assessment. cc @BurntSushi

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/48716.
