### ISSUE TITLE
pub(crate) fields of structs defined in lib.rs are not visible in main.rs

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rust#47473]
pub(crate) fields of structs defined in lib.rs are not visible in main.rs, when both lib.rs and main.rs files exist.
How to express that a symbol should be pub(crate) in lib.rs but also visible in main.rs?
For certain symbols, it makes sense to give main.rs the privilege to access them but not the wider public space.

**Comment by untitaker** [comment]
>How to express that a symbol should be pub(crate) in lib.rs but also visible in main.rs?

Please don't use the bugtracker for asking questions, rather use one of the channels referred to at https://www.rust-lang.org/en-US/community.html

**Comment by Boscop** [comment]
I mean, I asked, but the answer was, that there is currently no way to make something in lib.rs pub to main.rs without making it also pub to the outer space. So maybe there should be a way in the future?

**Comment by sfackler** [comment]
That's something more suited for https://github.com/rust-lang/rfcs.
