### ISSUE TITLE
Can we have a more C - Style programming for Rust

### ISSUE THREAD

**Issue by Raj2032** [rust-lang/rust#47477]
I think Rust is quite interesting but it is not like C - Style programming, which is quite confusing, especially when it comes to while, for loops and if statements. Even Java is close to C - Style programming.

Maybe there could be forked version of Rust.

**Comment by Cobrand** [comment]
If you have a proposal regarding the language itself, I suggest you do it in this repository: https://github.com/rust-lang/rfcs.

This repository is mainly a bugtracker for rustc (the rust compiler), the documentation, ... This kind of comment is out of scope for this repository.

**Comment by Raj2032** [comment]
Oh ok thanks for letting me know
