### ISSUE TITLE
`S { foo: val, ..Default::default() }` gives an error if the other fields aren't public

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rust#47472]
`S { foo: val, ..Default::default() }` gives an error if the other fields aren't public, but it should work (given `S: Default`).

**Comment by petrochenkov** [comment]
This is [unsound](https://github.com/rust-lang/rfcs/pull/736) because `Default::default()` is not consumed with current language rules.
This can work if `Default::default()` is consumed, but that would be a [breaking change](https://internals.rust-lang.org/t/proto-rfc-expanded-functional-record-update/3077/2) unless the syntax is changed to something else (e.g. `S { ..Default::default(), foo: val }`).

**Comment by zackmdavis** [comment]
A [more complete code sample](https://play.rust-lang.org/?gist=94bbb99a0ce375dc7a07777c2481e34a&version=stable):

```rust
mod my_module {
    #[derive(Default)]
    pub struct MyStruct {
        pub public_field: usize,
        private_field: bool,
        another_private_field: bool,
    }
}
 
use my_module::MyStruct;
 
fn main() {
    let s = MyStruct { public_field: 2, ..Default::default() };
}
```

Arguably not a bug insofar as we regard `..Default::default()` as mere syntactic sugar for `private_field: Default::default().private_field`?

**Comment by Boscop** [comment]
But why can't
```rust
let s = MyStruct { public_field: 2, ..Default::default() };
```
be syntactic sugar for
```rust
let mut s: S = Default::default();
s.public_field = 2;
let s = s;
```
Then this would also work:
```rust
let s: MyStruct = returning_mystruct();
let s = MyStruct { public_field: 2, ..s };
```
when only `public_field` is pub. 
IMO this **should** work..

It would at least be expected behavior for most people, and didn't we say that in 2018 we should make Rust more user-friendly / newbie-friendly? :)

**Comment by petrochenkov** [comment]
@Boscop 
Because it's a real breaking change, I made an experiment (see the link in https://github.com/rust-lang/rust/issues/47472#issuecomment-357815365).

**Comment by sfackler** [comment]
Reversing rust-lang/rfcs#736 requires an RFC.
