### ISSUE TITLE
Chain Iterator split function

### ISSUE THREAD

**Issue by josephDunne** [rust-lang/rust#47491]
I would like to submit a change to the Chain iterator module to enable better `FromIterator` specialisations.  Currently the `Chain` struct has two private fields `a` and `b` for the two chained iterators. Any implementor of `FromIterator` has no access to this individual iterators and so can not optimise the chain into two separate loops - one using the `FromIterator` trait and the second utilizing `Extend` for example. The compiler seems to struggle optimising a `from_iter` call if the iterator is a `iterator::Chain`

I would like to suggest a new trait called `ChainedIterator` that implements a split function. Implementors of `FromIterator` can then specialise on this trait to give the compiler more chance to optimise.

Will this require a RFC or can I just submit a pull request?

**Comment by rkruppe** [comment]
Can't the same (separate loop for each "chain component") be achieved in a more general way with the existing "inner iteration" methods like `for_each`?

**Comment by rkruppe** [comment]
cc @bluss

**Comment by bluss** [comment]
Well, try_from is now that most general internal iteration method. I can't quite see what general and more powerful trait we can expose along the lines of visiting the iterator in 1+ components.

I think this split is useful anyway, but it needs to be careful to not harm encapsulation. There has been alternative chain impls proposed that don't store the iterators after they are each exhausted for example.

**Comment by josephDunne** [comment]
I see so the suggestion is that all iterators must implement a correct try_fold and then my custom `FromIterator` should be implemented using `try_fold` that will work

**Comment by bluss** [comment]
Thanks :smile:

**Comment by rkruppe** [comment]
@josephDunne Just to be clear, there's a correct default implementation of try_fold, fold, for_each, etc. but many iterators can implement it in a more optimization-friendly manner. libstd iterators including Chain already have that implementation. So by using one of those methods you can already optimize your FromIterator implementation, without any need for specialization or custom iterator adaptors.

**Comment by josephDunne** [comment]
@rkruppe Thank you I will use try_fold

**Comment by bluss** [comment]
Std also uses the TrustedLen trait to improve its FromIterator for Vec, and that also benefits chain. If you need a size you can trust, it's a useful trait and could be pushed to stabilization if its open questions are fixed.
