### ISSUE TITLE
consider optimizing how NLL region inference works to use bit sets

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#47542]
Right now, the main loop of NLL region inference actually performs a lot of depth-first searches across the control-flow graph:

https://github.com/rust-lang/rust/blob/0f9c784751434c70ddd6719ccda6817c819126f9/src/librustc_mir/borrow_check/nll/region_infer/mod.rs#L468-L494

Basically, if we have a relation that `R1: R2 @ P`, then we do a depth-first search in the control-flow graph, starting at P; so long as the nodes we visit are members of R2, we add that node into R1 (if not already present). That code is in `dfs.rs`:

https://github.com/rust-lang/rust/blob/0f9c784751434c70ddd6719ccda6817c819126f9/src/librustc_mir/borrow_check/nll/region_infer/dfs.rs#L46-L89

(There is also a bit of special treatment around the exit from the CFG.)

This is pretty naive. I think what we should be doing is probably more like this:

1. Compute a reachability relation as a big `BitMatrix` (there exists code to do this already in `librustc_data_structures`).
    - If a point P can reach the end point, include the free regions in the reachability set. 
2. For a relation `R1: R2 @ P`, we can then intersect `reachable(P)` with `R2` to get "those members of R2 reachable from P".
   - Does this work? There might be some danger of R2 containing a point that is reachable from P, but not without leaving R2, and which hence should not be included?

Anyway, before we do a specific solution, though, it'd be great to have some specific benchmarks.

**Comment by nikomatsakis** [comment]
Hmm, so I suspect we can do *something* smart like this, but *just* replacing the DFS with a bit-set intersection certainly won't work. I don't have an actual Rust example where it goes wrong, but it seems clear that if you have `R1: R2 @ P` and `R2` has you can have things that are both reachable from P **and** contained within R2. It may be that it's better to just do a dirty list (#47602) and/or maybe use some caching (e.g., cache the bitset for `R2 @ P` for reuse).

**Comment by chrisvittal** [comment]
I'll take a look at this.

**Comment by nikomatsakis** [comment]
The [latest profiles](https://github.com/rust-lang/rust/issues/47879#issuecomment-367653652) seem to suggest that DFS is not just not expensive.
