### ISSUE TITLE
std::time::Instant doesn't have a Hash implementation

### ISSUE THREAD

**Issue by tecywiz121** [rust-lang/rust#47556]
`std::time::Instant` doesn't have a `Hash` implementation, but `std::time::Duration` does. Is this intentional?

I was looking at [the docs](https://doc.rust-lang.org/std/time/struct.Instant.html) for Version 1.23.0 (766bd11c8 2018-01-01).

**Comment by sfackler** [comment]
It implements Hash in beta: https://doc.rust-lang.org/beta/std/time/struct.Instant.html#impl-Hash.

**Comment by tecywiz121** [comment]
Woops, thanks!
