### ISSUE TITLE
WebAssembly FFI uses extern "C"

### ISSUE THREAD

**Issue by sdroege** [rust-lang/rust#47599]
While reading https://hacks.mozilla.org/2018/01/oxidizing-source-maps-with-rust-and-webassembly/ I noticed the following
> it is marked `extern "C"` so that it is publicly exported in the final .wasm file.

Shouldn't this be `extern "WASM"` or similar? The FFI interface is not the C one, but the WebAssembly one (or JavaScript?)

**Comment by fitzgen** [comment]
Discussion is also happening over at https://github.com/aturon/rust-wasm/issues/29

**Comment by alexcrichton** [comment]
This is now unlikely to change at this point, so I'm going to close this. We've chosen `"C"` for compatibility with mixing C/Rust in the same module.

**Comment by webmaster128** [comment]
Does this imply that a Wasm import cannot use [multiple return values](https://github.com/WebAssembly/multi-value)? Or is this a to-be-silenced linter issue?

--------

What I try to do is

```rust
extern {
    fn db_next(iterator_id: u32) -> (u32, u32);
}
```

which gets formatted to

```rust
extern "C" {
    fn db_next(iterator_id: u32) -> (u32, u32);
}
```

which clippy complains about:

```
warning: `extern` block uses type `(u32, u32)`, which is not FFI-safe
  --> packages/std/src/imports.rs:43:37
   |
43 |     fn db_next(iterator_id: u32) -> (u32, u32);
   |                                     ^^^^^^^^^^ not FFI-safe
   |
   = note: `#[warn(improper_ctypes)]` on by default
   = help: consider using a struct instead
   = note: tuples have unspecified layout
```
