### ISSUE TITLE
make revisions in the test harness show up as independent tests

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#47604]
So @spastorino recently hacked up a test to include two revisions, one of which enables NLL, by adding:

```rust
// revisions: lexical nll
#![cfg_attr(nll, feature(nll))]
```

This generates the following output:

```
running 1 test
test [run-pass] run-pass/generator/yield-subtype.rs ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 2883 filtered out
```

at which point the question is -- did both of those revisions really run successfully? 

Currently, if a test has N revisions, we run them all as part of its "main line". It'd be more reassuring if we made the revision part of the test name, so that you get output like:

```
running 2 tests
test [run-pass] run-pass/generator/yield-subtype.rs#nonlexical ... ok
test [run-pass] run-pass/generator/yield-subtype.rs#nll ... ok
```

The "early properties" of a test (which are gathered while we are assembling the list of tests) already contains the list of revisions:

https://github.com/rust-lang/rust/blob/5965b790142eff7a8546e947914e7a8e00c61575/src/tools/compiletest/src/header.rs#L29

Therefore, it should be a relatively simple thing to extend the `make_test` function to return not one test, but potentially many tests (one for each revision):

https://github.com/rust-lang/rust/blob/5965b790142eff7a8546e947914e7a8e00c61575/src/tools/compiletest/src/main.rs#L600

We would of course have to modify the test description to include which revision to run, and modify the `run` function, since that is the one that currently iterates over the list of revisions:

https://github.com/rust-lang/rust/blob/5965b790142eff7a8546e947914e7a8e00c61575/src/tools/compiletest/src/runtest.rs#L165-L178

But this shouldn't be a big change, I wouldn't think.

**Comment by nikomatsakis** [comment]
Tagging as E-mentor. I gave a few pointers in the description above, but of course happy to go into more detail.

**Comment by spejss** [comment]
Hi, can I work on this? I think I could manage to finish it in the next couple of days. I'll try my best :)

**Comment by totorigolo** [comment]
Can I take this one?

**Comment by spastorino** [comment]
@totorigolo I'd say yes, go ahead. In any case check with @nikomatsakis. This https://github.com/rust-lang/rust/pull/47605 is a very close attempt to implement the thing. Some tests were failing and I gave up because I didn't have any time. It's probably very close, I couldn't even check what the error is about, hehe.

**Comment by totorigolo** [comment]
Can you explain which tests were failing? I applied your changes and everything seems to be working.

**Comment by spastorino** [comment]
Run `RUST_BACKTRACE=full ./x.py test --incremental --stage 1 src/test/{ui,run-pass,compile-fail}`

**Comment by spastorino** [comment]
I remember seeing failures in CI, hmmm. Could it be that this PR is actually ok?.
@nikomatsakis should I open a new PR with the same changes against master and wait for the CI to run?.

**Comment by nikomatsakis** [comment]
@spastorino worth a try =)

**Comment by nikomatsakis** [comment]
@totorigolo did you ever give this a try?

**Comment by nikomatsakis** [comment]
cc @ehuss -- I think after your changes, we may be able to get this done! Want to give it a try?

**Comment by ehuss** [comment]
@nikomatsakis yea, although it looks a little tricky.  IIUC, incremental revisions are designed to be run in sequence, reusing the same directory.  Supporting that is resulting in a lot of special-case code (directory names, `init_incremental_test`, generating tests, etc.).  What do you think about changing incremental tests to use a new header called "steps"?  I think that would simplify things a lot.

**Comment by ehuss** [comment]
@nikomatsakis I tried a slightly different approach with just a few special cases for Incremental.  It works pretty well, however, I'm running into path-length problems on Windows.  I tried sending `\\?\` paths to rustc, but the Visual Studio linker still seemed to barf on it.  Do you know if it is possible to use long paths on Windows?  Otherwise, I'll try to think of ways to simplify and abbreviate...

**Comment by ehuss** [comment]
I put the paths on a diet and things seem to pass on Windows (at least on my system).  I have a patch here: https://github.com/ehuss/rust/commit/b558fa3711ae97d9faa1e701da44306044778613  The commit comment should explain generally what I did.  Let me know if you like the idea and you'd like me to post it as a PR.  I also had a few questions:

- Are there any tools (besides update-references) that depend on the directory layout of the test output?
- How do I enable wasm32-unknown-unknown?  How do I run the tests in `test/run-make`?
- Why was `canonicalize()` used in `stamp()`?  Was it for long Windows paths?  Why was it not used elsewhere?

**Comment by nikomatsakis** [comment]
@ehuss 

Sorry for dropping off the face of the earth. Trying to catch up on notifications!

>  IIUC, incremental revisions are designed to be run in sequence, reusing the same directory.

ah true, I forgot about that

>   What do you think about changing incremental tests to use a new header called "steps"?

👍 seems good

>  I have a patch here

will take a look!

**Comment by nikomatsakis** [comment]
@ehuss at first glance, that looks good to me. Maybe open the PR and i'll parse it more carefully.
