### ISSUE TITLE
Inconsistency between Display and IntoIterator for a TokenStream containing a module

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#47627]
The following crate reproduces the issue. Given an attribute macro on a mod item like `#[...] mod module;`, iterating over the tokens of the TokenStream produces `mod module;` but invoking to_string() on the TokenStream produces `mod module { /* the contents */ }`. I don't know which one is correct but they should be consistent.

@jseyfried 

---

#### `Cargo.toml`

```toml
[package]
name = "repro"
version = "0.0.0"
publish = false

[lib]
proc-macro = true
```

#### `src/main.rs`

```rust
#![feature(proc_macro)]

extern crate repro;

#[repro::print]
mod module;

fn main() {}
```

#### `src/module.rs`

```rust
pub struct S;
```

#### `src/lib.rs`

```rust
#![feature(proc_macro)]

extern crate proc_macro;
use proc_macro::TokenStream;

#[proc_macro_attribute]
pub fn print(_args: TokenStream, input: TokenStream) -> TokenStream {
    println!("{}", input);
    for tt in input {
        println!("{:?}", tt.kind);
    }
    TokenStream::empty()
}
```

#### Output

```
mod module {
    pub struct S;
}
Term(Term(mod))
Term(Term(module))
Op(';', Alone)
```

**Comment by alexcrichton** [comment]
I believe this is the same as https://github.com/rust-lang/rust/issues/48644 as @dtolnay [points out](https://github.com/rust-lang/rust/issues/48644#issuecomment-369746550), and I've got some [more explanation below that](https://github.com/rust-lang/rust/issues/48644#issuecomment-369803696).

For this, however, there's the question of which representation is correct? Is `mod module;` correct or `mod module { .. }` correct to pass to the procedural macro attribute? Or should we forbid attributes on modules altogether?

**Comment by CodeSandwich** [comment]
I think, that whatever it is, the effect of annotation of `mod module;` should be same as 'mod module { ... }`, that's what macro user would expect since in all the other uses both versions act perfectly same.

I also think, that annotation of modules is an important feature, but my opinion could be biased since I'm the author of a crate, which uses this.

**Comment by CodeSandwich** [comment]
Since `rustc 1.30.0-nightly (63d51e89a 2018-09-28)` the behavior is consistent, it's always `mod module;`. Is there any way to access the file module's content in proc macro?
