### ISSUE TITLE
LLVM error with trait objects

### ISSUE THREAD

**Issue by matthewjasper** [rust-lang/rust#47638]
The following code

```rust
fn id<'c, 'b>(f: &'c &'b Fn(&i32)) -> &'c &'b Fn(&'static i32) {
    f
}

fn main() {
    let f: &Fn(&i32) = &|x| {};
    id(&f);
}
```

gives the following error on beta (1.24) and nightly (1.25 2018-01-17). It compiles successfully on stable.
```text
Function return type does not match operand type of return inst!
  ret { %"core::ops::function::Fn<(&i32), Output=()>.0"*, {}* }* %3, !dbg !36
 { %"core::ops::function::Fn<(&i32), Output=()>"*, {}* }*LLVM ERROR: Broken function found, compilation aborted!
```

**Comment by dtolnay** [comment]
Mentioning @michaelwoerister @eddyb @nagisa who touched librustc_trans recently (disclaimer: I don't know if that's where this problem would come from but it sounds relevant).

**Comment by eddyb** [comment]
cc @pnkfelix @nikomatsakis Is this one of those "HRTB lifetimes in `rustc_trans` causes distinct LLVM types" bugs? It seems like there's two distinct types for the unsized pointee of `Fn(&i32)`.

**Comment by nikomatsakis** [comment]
triage: P-high

We need to figure this out.

**Comment by ritiek** [comment]
So, I was testing nightly toolchains and this has been a problem since:

```
$ rustc -vV
rustc 1.23.0-nightly (33374fa9d 2017-11-20)
binary: rustc
commit-hash: 33374fa9d09e2a790979b31e61100dfed4b44139
commit-date: 2017-11-20
host: x86_64-unknown-linux-gnu
release: 1.23.0-nightly
LLVM version: 4.0
```
The code compiles OK with previous day's nightly:
```
$ rustc -vV
rustc 1.23.0-nightly (5041b3bb3 2017-11-19)
binary: rustc
commit-hash: 5041b3bb3d953a14f32b15d1e41341c629acae12
commit-date: 2017-11-19
host: x86_64-unknown-linux-gnu
release: 1.23.0-nightly
LLVM version: 4.0
```

**Comment by dtolnay** [comment]
https://github.com/rust-lang/rust/compare/5041b3bb3d953a14f32b15d1e41341c629acae12...33374fa9d09e2a790979b31e61100dfed4b44139 then, almost certainly something in #45225. @eddyb

**Comment by eddyb** [comment]
@dtolnay I introduced it for this specific case, yeah, but it's a long-standing bug AFAICT (#36744).
We have some hacks when doing stores and calls, at least, but it's not ideal.
I'm hoping @nikomatsakis can confirm and knows of a better direction for #36744.

**Comment by nikomatsakis** [comment]
So I agree with @eddyb that it's the same bug. I think my preferred longer term fix is to change our rules around subtyping and higher-ranked regions -- but in the short term, I suspect we need some bit casts.

**Comment by eddyb** [comment]
This is *not* a new regression in its general case, only specifically trait objects outside of structs:
```rust
struct Newtype<T>(T);

fn id<'c, 'b>(f: &'c Newtype<&'b Fn(&i32)>) -> &'c Newtype<&'b Fn(&'static i32)> {
    f
}

fn main() {
    let f: &Fn(&i32) = &|x| {};
    id(&Newtype(f));
}
```
This fails with the LLVM error in 1.0 through 1.22, according to godbolt.
*Somehow*, #45225 (presumably) fixed that and introduced a different form of it.
