### ISSUE TITLE
Update CONTRIBUTING.md's build system docs

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#47642]
It seems likely that there are a number of tasks here, but the known one is that https://github.com/rust-lang/rust/pull/47460 needs to be added upon merge.

**Comment by pietroalbini** [comment]
Shouldn't the forge also be updated?

https://forge.rust-lang.org/x-py.html

**Comment by steveklabnik** [comment]
Triage: it's been a long while, and this ticket doesn't have specific criteria for closing. @Mark-Simulacrum do you think this one is done, or do you know specific tasks still needed to be completed?

**Comment by Mark-Simulacrum** [comment]
I'm going to say that we should close this and if there is more work to be done (as is plausible, at least) directly target it with specific issues/PRs.
