### ISSUE TITLE
std::io::Cursor::position behavior changed in the beta

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#47640]
Seems like the behavior of `std::io::Cursor::position` changed, because the test suite of [rmp](https://crates.io/crates/rmp) now fails on beta and nightly while working fine on stable ([crater log](http://cargobomb-reports.s3.amazonaws.com/1.23.0-1.24.0-beta.3/beta-2018-01-13/reg/rmp-0.8.7/log.txt)). One example of such an error:

```rust
#[test]
fn from_str32_read_str_len_eof() {
    let buf: &[u8] = &[0xdb, 0x00, 0x00, 0x00];
    let mut cur = Cursor::new(buf);

    read_str_len(&mut cur).err().unwrap();
    assert_eq!(4, cur.position());
}
```

```
---- func::decode::string::from_str32_read_str_len_eof stdout ----
        thread 'func::decode::string::from_str32_read_str_len_eof' panicked at 'assertion failed: `(left == right)`
  left: `4`,
 right: `1`', rmp/tests/func/decode/string.rs:120:5
```

My guess is this regression is related to #46485, which is the only pull request that changed the behavior for `Cursor<&[u8]>`.

cc @3Hren

**Comment by 3Hren** [comment]
Not sure it's the `Cursor`'s issue. The code is: https://github.com/3Hren/msgpack-rust/blob/master/rmp/src/decode/str.rs#L75

Seems like either `byteorder` can now read atomically, or `Read::read_exact` does the same. Both cases are valid, but forces me to rewrite test conditions.

**Comment by alexcrichton** [comment]
Ok! I'll bring this up with @rust-lang/libs team soon as well, but we're pretty likely to close this.

**Comment by alexcrichton** [comment]
The libs team discussed this today and concluded to close, but thanks regardless for the report @pietroalbini and the willingness to update @3Hren!
