### ISSUE TITLE
Improve error message for infinitely recursive impl Trait type

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rust#47659]
After https://github.com/rust-lang/rust/pull/47529, attempts to compile code which builds an infinitely recursive `impl Trait` type will error with "overflow evaluating the requirement `impl Quux`". This isn't super user-friendly, and should be improved.

**Comment by cramertj** [comment]
@ZerothLaw I'm not sure-- it's hard to know exactly what to report. You know that an overflow has occurred, but not that it is necessarily due to recursive use of `impl Trait`. [This is where the current overflow reporting is triggered](https://github.com/rust-lang/rust/pull/47529/files#diff-d78d7264a4b7f0f246355cec0c7e3298R304)-- we could add a suggestion hinting that this may be the result of attempting to build an infinitely recursive `impl Trait` type, but we don't know for sure that that is the cause. You could record the `DefId` of each `TyAnon` type encountered while folding recursively and then report a recursion error if you see a repeat `DefId`.

**Comment by ZerothLaw** [comment]
That's a good point. So before working on it, one should first figure out what the acceptable solution would be?

**Comment by estebank** [comment]
You can take inspiration from https://github.com/estebank/rust/blob/master/src/test/ui/lint-unconditional-recursion.stderr and https://github.com/estebank/rust/blob/master/src/test/ui/span/recursive-type-field.stderr

**Comment by alexreg** [comment]
@ZerothLaw Did you make any progress on this lately? I can maybe help give you more pointers, if needed.

**Comment by ZerothLaw** [comment]
I haven't made any attempt on this. Any suggestions?

**Comment by alexreg** [comment]
@ZerothLaw @cramertj provides a good approach in [his comment](https://github.com/rust-lang/rust/issues/47659#issuecomment-415094603). To be specific, you might want to start by:
* Add a new field to the `AssociatedTypeNormalizer` struct for storing already-seen types (values of `ty` parameter to `fold_ty`) that you're folding with. (I think @cramertj's suggestion of using the def-ids for the types would work in most cases, but may fail in some complex edge cases. Maybe he can chip in here.) A `HashSet` (`FxHashSet`?) may be the best type for this.
* At the top of the `fold_ty` function, check for the newly-encountered type in the set of already-seen types. If you find it, raise the error; if not, add the type to the set and continue.
* Model the error reporting on one of the examples @estebank gave in his above comment. Probably the [second one](https://github.com/estebank/rust/blob/master/src/test/ui/span/recursive-type-field.stderr) is a better prototype. [Here](https://github.com/rust-lang/rust/blob/e6c5cf923489f4aed6c9e36a170fab9b6179d8da/src/librustc/traits/error_reporting.rs#L1219-L1234) is the code for reporting it; I suggest creating a new method that's pretty similar to that one.
* Create a test for this issue under `src/tests/ui/issues/issue-47659` with an appropriate minimal reproducible case. Make sure you ["bless"](https://rust-lang-nursery.github.io/rustc-guide/tests/adding.html#bless) the test once everything is running.

The [rustc development guide](https://rust-lang-nursery.github.io/) is pretty handy if you're curious about how the compiler fits together, or what purpose a particular type or function serves, in many cases. Still, if you have any difficulties with the above, post back here, or hop onto the #compiler channel on Discord. Good luck!

**Comment by alexreg** [comment]
@ZerothLaw Had a chance to tackle the above yet, by chance?

**Comment by cramertj** [comment]
@alexreg This is covered by https://github.com/rust-lang/rust/pull/56074.
