### ISSUE TITLE
extend x.py so it is easy to pass custom -Z flags when building after stage 0

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#47658]
We'd like to start trying to bootstrap with `-Znll` enabled. From what I can tell, there is no easy way to do this at present: using `RUSTFLAGS=-Znll` will cause the flag to be passed to **all** stages, but the support for NLL in stage0 is not up to the task.

We could extend x.py to support `RUSTFLAGS_STAGE{0,1,2}` (which would get "copied into" the RUSTFLAGS environment when building stage 0, 1, or 2.

Or we could make some kind of flag.

It might also be nice to just support `RUSTFLAGS_NOT_STAGE0` since usually that's what you want.

Or maybe there's an existing solution here?

**Comment by Mark-Simulacrum** [comment]
So we can try to solve this generally (I know @eddyb has requested `RUSTFLAGS_STAGE_N` support before), which wouldn't be too hard. Alternatively, we can also make nll an option in config.toml. Which would we prefer? I'm open to either; once I hear back we can probably have an implementation up in a day at most I'd imagine.

**Comment by nikomatsakis** [comment]
@Mark-Simulacrum I think I prefer `RUSTFLAGS_STAGE_N`. I agree it's quite easy to do. I would probably prefer to have:

- `RUSTFLAGS_STAGE_0`
- `RUSTFLAGS_STAGE_1`
- `RUSTFLAGS_STAGE_2`
- `RUSTFLAGS_STAGE_1_OR_2` // i.e., not(stage0)

But what to call that final one I don't know. Maybe `RUSTFLAGS_BOOTSTRAP`? It seems like it is what you are going to want most of the time.

**Comment by eddyb** [comment]
`RUSTFLAGS_STAGE_NOT_0`

**Comment by Mark-Simulacrum** [comment]
Okay, I'll try and get an implementation of that up by the end of the week. I've assigned myself, but of course, if anyone wants to do this they are welcome too..
