### ISSUE TITLE
regression -- test fails after #46739 that succeeded before it

### ISSUE THREAD

**Issue by remexre** [rust-lang/rust#47674]
https://github.com/remexre/tri/commit/915303dc4d91329a5957181696314347df854f73

Note: to build this you need to set `DATABASE_URL=tri.db` in the environment, and run `diesel migration run` to create an initial database for `diesel_infer_schemas`. Yeah, I should stop using that.

Under `cargo test --release`, this code panics/SIGSEGVs (depending on the nightly) under nightlies after #46739 was merged (according to https://github.com/Mark-Simulacrum/bisect-rust). According to `sebk` on IRC, it looks like the stack is being overwritten, with the length of the string being set to a value in the "maybe this is signed overflow" range.

An executable for the test that fails as built by 97520ccb1 is at http://www-users.cs.umn.edu/~ringo025/tri-bug/tri-e74526a64d5fbc02

**Comment by alexcrichton** [comment]
Another recent segfault (https://github.com/rust-lang/rust/issues/47364) also pointes to the same PR using bisect-rust, thanks for the tip and the report @remexre!

**Comment by nikomatsakis** [comment]
Ought to be fixed by https://github.com/rust-lang/llvm/pull/102

**Comment by nikomatsakis** [comment]
triage: P-high

Let's check back in once rust-lang/llvm#102 lands.

**Comment by dotdash** [comment]
Works for me using `rustc 1.25.0-nightly (21882aad7 2018-01-28)` which contains the LLVM upgrade.
