### ISSUE TITLE
Write to a field of a moved value

### ISSUE THREAD

**Issue by sblackshear** [rust-lang/rust#47697]
In [this](https://play.rust-lang.org/?gist=c2e5e3eeb5871ef21835d484ded6dea1&version=stable) code, I am not allowed to read from `t.i` after `t` has been moved (as expected), but I *am* allowed to write to `t.i` (which is not expected). Shouldn't Rust stop me from writing to `t.i` if `t` is moved? It doesn't seem like a write to `t.i` can serve any useful purpose if a subsequent read of `t.i` always causes an error.

Note: the `Drop`-printing in the code snippet is only there to show that Rust doesn't appear to be allowing the write only because because it eliminates the dead store to `t.i`.

**Comment by scottmcm** [comment]
Is this https://github.com/rust-lang/rust/issues/21232?

**Comment by sfackler** [comment]
Yep, closing as a duplicate.
