### ISSUE TITLE
Rustdoc style/theme/color picker doesn't work on Firefox

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#47695]
A picture is worth a thousand words, so is this GIF a novel? (Chrome on left, Firefox 57.0.4 (64-bit) on right)
![ezgif com-crop](https://user-images.githubusercontent.com/5992217/35310755-f6882492-0080-11e8-8fec-fd14f3d3a845.gif)
(Windows 10 64-bit OS)

**Comment by CAD97** [comment]
(Just updated to Firefox 58.0 (64-bit), and behavior is the same)

FWIW, I love that rustdoc now offers a dark CSS theme. It's just annoying that I can't switch, because I got used to the main one. Also, I only noticed it because Firefox defaulted to showing me the dark theme, whereas when I opened it in Chrome to compare, it defaulted to the main theme.

**Comment by retep998** [comment]
cc @GuillaumeGomez

**Comment by Centril** [comment]
Works on Chrome for me too but not on Firefox 59.0b3 (64-bit) Developer Edition on Windows 10.

**Comment by ehuss** [comment]
I believe changing [this](https://github.com/rust-lang/rust/blob/a538fe7ce715c7bd27e2e05329c3d857b9ad92af/src/librustdoc/html/layout.rs#L77-L80) from a &lt;button&gt; to a &lt;div&gt; would fix the problem.

**Comment by GuillaumeGomez** [comment]
There is a [PR](https://github.com/rust-lang/rust/pull/47686) in progress. I think it'll fix your issue. I'll test on firefox when I have time.

**Comment by GuillaumeGomez** [comment]
I confirm that this PR fixes the behavior on firefox.
