### ISSUE TITLE
NLL: error from get-opts crate

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#47707]
In https://github.com/rust-lang/rust/issues/47596, @SimonSapin reported several NLL errors in dependencies of the servo crate. @lqd later minimized one of those errors into [this example](https://play.rust-lang.org/?gist=91237489cb7566627523b81dbb09d917&version=nightly):

```rust
#![feature(nll)]

enum SplitWithinState { A, B }

fn each_split_within() {
    let mut state = SplitWithinState::A;
    let mut closure = || { state = SplitWithinState::A };
    if let SplitWithinState::A = state {
    }
    closure();
}

fn main() {}
```

which yields:

```
error[E0503]: cannot use `state` because it was mutably borrowed
 --> src/main.rs:8:12
  |
7 |     let mut closure = || { state = SplitWithinState::A };
  |                       ---------------------------------- borrow of `state` occurs here
8 |     if let SplitWithinState::A = state {
  |            ^^^^^^^^^^^^^^^^^^^ use of borrowed `state`

error: aborting due to previous error
```

That said, at first glance, this looks like it might be a bug *fix* -- the `closure` is assigning to `state`, so it has a mutable borrow, and the `if let` is testing it. Pretty sure this is <https://github.com/rust-lang/rust/issues/45045>.

**Comment by nikomatsakis** [comment]
Going to close as duplicate of https://github.com/rust-lang/rust/issues/45045 (and hence NLL is acting correctly)

**Comment by SimonSapin** [comment]
Thanks for working out the details. It looks like this is already fixed in git upstream, filed https://github.com/rust-lang-nursery/getopts/pull/60

**Comment by SimonSapin** [comment]
… or not. https://github.com/rust-lang-nursery/getopts/pull/61
