### ISSUE TITLE
File::set_len uses an immutable reference to self

### ISSUE THREAD

**Issue by vitiral** [rust-lang/rust#47708]
I am creating a wrapper for the File type and came across an issue that I thought was odd.

- [File::set_len](https://doc.rust-lang.org/std/fs/struct.File.html#method.set_len)
- [File::set_permisions](https://doc.rust-lang.org/std/fs/struct.File.html#method.set_permisions)

Both of these methods take an _immutable_ reference (`&self`) to the File instead of a _mutable_ reference (`&mut self`).

I'm not so much concerned about _memory safety_ per se, as I assume that the operating system guarantees that operaions are memory safe, it is just that this is extremely unexpected. If I pass a function an immutable reference to a `File`, I wouldn't expect it to be able to truncate the file!

Obviously this is a breaking change so probably can't be changed -- however, I was thinking we could at least add docs explaining why the reference is immutable.

**Comment by vitiral** [comment]
I do wonder how much this would break people in the wild though. How many people are truncating or extending a file that they don't have a mutable reference to?

**Comment by ExpHP** [comment]
I do not think this is too odd considering the much more frequently-encountered *gotcha!* that `&File` implements `Read` and `Write`.  It's all fallout from the fact that [`mut` doesn't really mean "mutable"](http://smallcultfollowing.com/babysteps/blog/2014/05/13/focusing-on-ownership/).  I don't believe there is much that can be done here beyond documentation and education.

**Comment by vitiral** [comment]
I'm also not following this with my [`path_abs`]http://crates.io/crates/path_abs) crate to prevent any gotchas. Would love feedback if that is a bad idea!

**Comment by ExpHP** [comment]
> I'm also not following this with my path_abs crate to prevent any gotchas. Would love feedback if that is a bad idea!

I looked at the crate and didn't see any `&mut self` functions, so I'm not sure what you're referring to; but you should keep in mind multithreaded use cases.  `&File` needs to implement the things it does to enable things like e.g. writing to a File from inside a rayon ParallelIterator.

In your case, though, even if there were `&mut self` functions that did not strictly have to be `&mut`, it would be little more than a speedbump, since all of the objects in your crate are easily cloned (since they are really paths, and not `File`s).

**Comment by vitiral** [comment]
cool, thanks! 👍

**Comment by vitalyd** [comment]
The fact that `&File` can be mutated is a very common headscratcher for beginners, right after they’ve heard about Rust’s strict mutability rules.  The standard answer seems to be: Rust prevents data races for memory safety purposes, and not for modeling any extra semantics on top.  In other words, if the OS provides memory safe mutation over aliased file handles, Rust-the-language will happily allow it to occur in your code too.  Of course someone writing the `File` type could’ve made the design decision to not allow this footgun but now it’s a “policy” decision they’re making, and not purely memory safety.

The good news is one can define their own type and add extra semantics (eg prevent mutation unless you have a unique borrow).

**Comment by vitiral** [comment]
@ExpHP @vitalyd I've just released v0.3.0 and here is the docs related to this issue:

https://docs.rs/path_abs/0.3.0/path_abs/#differing-method-signatures

Would appreciate a review!

**Comment by bill-myers** [comment]
This is correct as-is.

The operations on File take a shared reference because OS kernels are designed so that file APIs on the same file description can be called simultaneously from multiple threads without issue.

Changing it would make it impossible to translate useful C code into Rust.

**Comment by alercah** [comment]
Thought: how about a general warning on the type in general, plus smaller notes saying "Note that this method can change the file via a shared reference."

**Comment by steveklabnik** [comment]
@alercah I like it, but I'd remove "shared"; the proper terms are "reference" and "mutable reference", even though sometimes people do say "shared reference" for `&T`, I try to keep things consistent. Alternatively, just say `&T` straight-up so there's even less confusion :)
