### ISSUE TITLE
[nll] compilation error from mozjs-0.1.10

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#47722]
In https://github.com/rust-lang/rust/issues/47596, @SimonSapin reported several NLL errors in dependencies of the servo crate. @lqd later minimized one of those errors into [this example](https://play.rust-lang.org/?gist=db23fce76e48bf866b0b8c2f80a50464&version=nightly):

```rust
#![feature(nll)]

struct AutoGCRooter {
    stackTop: *mut *mut AutoGCRooter,
}

impl AutoGCRooter {
    unsafe fn add_to_root_stack(&mut self) {
        *self.stackTop = self;
    }
}

fn main() {}
```

which yields:

```
error[E0506]: cannot assign to `*self.stackTop` because it is borrowed
 --> src/main.rs:9:9
  |
9 |         *self.stackTop = self;
  |         ^^^^^^^^^^^^^^^^^----
  |         |                |
  |         |                borrow of `*self.stackTop` occurs here
  |         assignment to borrowed `*self.stackTop` occurs here

error: aborting due to previous error
```

Removing feature(nll) makes the code work, so *probably* this is an NLL bug.

**Comment by Aaron1011** [comment]
I'd like to take a look at this.

**Comment by Aaron1011** [comment]
Explicitly casting `self` to `*mut AutoGCRooter` fixes the issue: https://play.rust-lang.org/?gist=15c060db3de0a3212c3ab2b2a3d32b30&version=nightly

```rust
#![feature(nll)]

struct AutoGCRooter {
    stackTop: *mut *mut AutoGCRooter,
}

impl AutoGCRooter {
    unsafe fn add_to_root_stack(&mut self) {
        *self.stackTop = self as *mut AutoGCRooter;
    }
}

fn main() {}
```

My guess is that there's an issue with the automatic coercion from `&mut self` to `*mut self`. I'll investigate further.

**Comment by Aaron1011** [comment]
It turns out you can remove one layer of indirection and still get the same error:

```rust
#![feature(nll)]

struct AutoGCRooter {
    stackTop: *mut AutoGCRooter,
}

impl AutoGCRooter {
    unsafe fn add_to_root_stack(&mut self) {
        self.stackTop = self;
    }
}

fn main() {}
```
