### ISSUE TITLE
#[link_name] is ignored on extern blocks

### ISSUE THREAD

**Issue by cuviper** [rust-lang/rust#47725]
```rust
fn main() {
    println!("{}", unsafe { foo() });
}

#[link_name = "foobar"]
extern "C" {
    fn foo() -> u32;
}
```

This fails to link with ``undefined reference to `foo'``, but it didn't even try to find any `foobar` library.

With `#[link(name = "foobar")]`, the error is the expected `ld: cannot find -lfoobar`.

There are a few places in `libstd` using `#[link_name = "m"] extern {...}`, so I wonder if those actually have any effect either.

**Comment by rkruppe** [comment]
AFAIK `link_name` is for individual extern items ([example](https://play.rust-lang.org/?gist=d808f895dfaac70261282ccd6e39fd09&version=stable)) and bears no relation to `#[link(name=...)]`. So this is "just" another case of not warning/erroring when an attribute is used in a position where it doesn't mean anything?

The fact that libstd got this wrong in some places is concerning, though 😅

**Comment by nagisa** [comment]
Surprised again that the unused attribute lint is not firing.

**Comment by cuviper** [comment]
Yeah, I think you're right that `#[link_name]` is simply not intended for this, so getting the lint to fire sounds like the right solution.

**Comment by alexcrichton** [comment]
This may have been the *ancient* method of what `#[link(name = "..")]` is today, any usage in the standard library should be subsubed by the `build.rs` script I believe.
