### ISSUE TITLE
rustdoc: theme switcher button in awkward locations on mobile

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/rust#47723]
When viewing docs on mobile, the "switch theme" button is placed into the top bar. However, this overlaps the crate version indicator on the crate root:

![image](https://user-images.githubusercontent.com/5217170/35358679-12d4e44a-011d-11e8-9bba-04b7e4991ace.png)

When the sidebar menu is opened, the button is instead placed into that sidebar menu, but can also overlap text there:

![image](https://user-images.githubusercontent.com/5217170/35358710-2a3dc1f6-011d-11e8-9403-213f5049efe7.png)

**Comment by GuillaumeGomez** [comment]
That's a funny one!
