### ISSUE TITLE
compiletest powerpc64 arch is useless

### ISSUE THREAD

**Issue by jcowgill** [rust-lang/rust#47737]
The `ARCH_TABLE` in compiletest contains a useless entry for powerpc64.
https://github.com/rust-lang/rust/blob/79b25c666fec/src/tools/compiletest/src/util.rs#L34

The only user of that table is `get_arch` which scans the table sequentially to see if a target contains an architecture in the table. Since `powerpc` is a substring of `powerpc64`, the entry for `powerpc64` will never match anything and is therefore useless.

This also means that all `ignore-powerpc64` headers in the testsuite currently do nothing. I also found a few `ignore-powerpc64le` headers which probably do nothing as well.

**Comment by debris** [comment]
What about `arm` and `arm64`? Aren't they also affected by the same issue?

https://github.com/rust-lang/rust/blob/79b25c666fecc908539087918131d6a56e669312/src/tools/compiletest/src/util.rs#L37-L38

**Comment by jcowgill** [comment]
Yes I think `arm64` is affected as well. I'm not sure why we need both `arm64` and `aarch64`.

**Comment by rkruppe** [comment]
It seems... ungreat for compiletest to ignore tests tagged `ignore-powerpc` on powerpc64 given that `powerpc` is apparently used as the name for the 32 bit architecture. Likewise for arm. #48732 seems to indicate all current tests that ignore "powerpc32" also ignore powerpc64, but if we ever have a test that should run on 64 bit PPC and not on 32 bit PPC, we'd be hosed.

I think the right fix here is to make compiletest stricter (i.e., only match entire `-`-separated triple components, not substrings).
