### ISSUE TITLE
Mediocre error message for f32/f64 ambiguity

### ISSUE THREAD

**Issue by nieksand** [rust-lang/rust#47759]
I have this code:
```
    let _ = |x: f64| x * 2.0.exp();
```
https://play.rust-lang.org/?gist=58e23173aec4b798d8021af0ead25bbd&version=nightly

I get this error message:
```
error[E0599]: no method named `exp` found for type `{float}` in the current scope
```

I can work around by:
```
    let _ = |x: f64| x * 2.0f64.exp();
```

The world would be a better place if:
* Type inference could just figure out 2.0 has to be f64 given the type on `x`
* Failing that, an error message indicating the problem is f32 vs f64 ambiguity rather than this mysterious `{float}` thing

**Comment by kennytm** [comment]
Note that type inference cannot figure out 2.0 is an f64 because this is perfectly valid.

```rust
struct Foo;
trait Wat {
    fn exp(self) -> Foo;
}
impl Wat for f32 {
    fn exp(self) -> Foo { Foo }
}
impl std::ops::Mul<Foo> for f64 {
    type Output = &'static str;
    fn mul(self, _: Foo) -> &'static str {
        "wat"
    }
}

fn main() {
    let _ = |x: f64| x * 2.0.exp();
    //let _ = |x: f64| x * 2.0f64.exp();
}
```

**Comment by nieksand** [comment]
Yipes.  Inference is definitely out.
