### ISSUE TITLE
Explain in `FromStr`s docs that you can't use a lifetime

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#47757]
Inspired by https://www.reddit.com/r/rust/comments/7syu6z/where_do_you_declare_a_lifetime_for_fromstrerr/, but i've seen it crop up a few times. We should put something in the docs.

**Comment by steveklabnik** [comment]
@GuillaumeGomez is there any particular reason you nominated this issue?

**Comment by RReverser** [comment]
I really wish this would be fixed by introducing a lifetime in `FromStr` trait instead. This would still allow to implement it for structures that don't borrow data, but would also enable it for structures that do.

This would be a breaking change though, so maybe in a new Rust edition?

**Comment by steveklabnik** [comment]
Editions cannot make that kind of change; the  stdlib cannot change signatures or remove anything.

**Comment by RReverser** [comment]
So there is no escape hatch for stdlib to fix already existing API issues like Rust editions fix syntactic ones?

**Comment by oli-obk** [comment]
Would it still be a breaking change if the lifetime "defaulted" to `'static`? Generics can already default to specific types (thus allowing libstd types to add more generic args). Seems like a reasonable extension to allow the same for lifetimes.

Anyway, this is is off topic, it should definitely be documented for now.

**Comment by RReverser** [comment]
@oli-obk Yeah I was thinking about it too, but didn't suggest because it also requires syntactic change.

**Comment by steveklabnik** [comment]
> Would it still be a breaking change if the lifetime "defaulted" to 'static?

How would this work? That would let you do this for `&'static str`s, but not other `&str`s, no?

**Comment by oli-obk** [comment]
> How would this work? That would let you do this for &'static strs, but not other &strs, no?

Note quite, i'm not talking about the input:

```rust
trait FromStr<'a = 'static> {
    fn from_str<'b>(s: &'b str) -> Self where 'a: 'b;
}

struct Foo<'b>(&'b str);
struct Bar(String);

impl FromStr for Bar {
    fn from_str(s: &str) -> Self {
        Bar(s.to_owned())
    }
}

impl<'c> FromStr<'c> for Foo<'c> {
    fn from_str(s: &'c) -> Self {
        Foo(s)
    }
}
```

Changing `fn from_str(s: &str) -> Self` to essentially `fn from_str<'b>(s: &'b str) -> Self where 'static: 'b;` should be backwards compatible

**Comment by steveklabnik** [comment]
> trait FromStr<'a = 'static> {

This isn't a language feature yet, I guess that's why I'm confused; I see now.
