### ISSUE TITLE
Rust allows &mut aliasing on static mut variables

### ISSUE THREAD

**Issue by archshift** [rust-lang/rust#47756]
[Simple example](https://play.rust-lang.org/?gist=552701026f2084154170bb7979a0c18e&version=stable):

```rust
static mut oops: u32 = 0u32;

pub fn main() {
    let a = unsafe { &mut oops };
    let b = unsafe { &mut oops };
    *a = 1;
    println!("{}", *b);
}
```

I would expect Rust to disallow this type of code, or at least warn about it, but it simply allows the programmer to shoot himself in the foot.

**Comment by scottmcm** [comment]
The fact that you can't do this without `unsafe` _is_ what I'd call warning about it.  You could consider the `unsafe` like "allowing the `cannot_prove_this_code_safe` lint".

`unsafe` can easily get you &mut aliasing on non-globals too:
```rust
pub fn main() {
    let mut foo = 4;
    let oops = &mut foo as *mut _;
    let a = unsafe { &mut* oops }; // very bad
    let b = unsafe { &mut* oops }; //  much UB
    *a = 1;
    println!("{}", *b);
}
```

**Comment by cuviper** [comment]
While it may feel like the borrow checker could catch this local case, `static mut` references could alias from afar too -- from calls in distant parts of the stack, or even from separate threads.

**Comment by archshift** [comment]
Unfortunately, this isn’t even documented in the rust book. [There’s a whole section](https://doc.rust-lang.org/book/first-edition/const-and-static.html) on mutability in statics but no mention of the relaxed checks on them: namely mutable aliasing and the lack of a `Sync` requirement.

**Comment by Centril** [comment]
Closing based on https://github.com/rust-lang/rust/issues/47756#issuecomment-360677505.
