### ISSUE TITLE
WASM/WebAssembly bug when compiling with opt-level=0

### ISSUE THREAD

**Issue by adiba** [rust-lang/rust#47776]
```rust
extern {
    fn log_i32(val: i32);
}

#[no_mangle]
pub fn run() {
    let s = "Tre".as_bytes();
    let len = s.len();
    unsafe {
        log_i32(len as i32);
    }
}
```
This should yield `3`. It however gives `0`  when compiling with the following command:
`rustc +nightly -C opt-level=0 --target wasm32-unknown-unknown --crate-type=cdylib src/main.rs`
Any `opt-level` above 0 is fine though. (eg `rustc +nightly -C opt-level=1 --target wasm32-unknown-unknown --crate-type=cdylib src/main.rs`)

The fat pointer of `s` contains the correct length in memory, just the `len` method returns the wrong value.
I only have access to the mangled `opt-level=0` WAT so I cannot investigate what WASM or LLVM-IR is doing there.

**Comment by alexcrichton** [comment]
I'm gona close this in favor of https://github.com/rust-lang/rust/issues/46367 as I believe it's the same issue as that, but thanks for the report!
