### ISSUE TITLE
Each usage of {:?} on usize appears to generate a separate adapater to core::fmt::Display

### ISSUE THREAD

**Issue by bholley** [rust-lang/rust#47785]
I've been working on removing Debug implementations from Firefox release builds to improve code size. One common culprit is assert_eq!(), which generally takes integers, but formats them with {:?}.

I first assumed that this would probably call straight into Display, or at the very least instantiate a single adapter. Unfortunately, we appear to end up with one adapter per callsite, because the adapters use relative jumps.

So we end up with tons of functions of the form: https://gist.github.com/bholley/b3b8b3a9df649334263338955c10f63d

Which are all identical, except for the offset in the jump instruction: https://gist.github.com/bholley/e2c4ceec5cc3bc38c2462f7cc4bfd242

I'm not sure if this is an LLVM bug or a rustc bug, but it sure seems sub-optimal.

CC @SimonSapin @nox @Manishearth @emilio

**Comment by kennytm** [comment]
I think this is related to https://internals.rust-lang.org/t/changing-core-fmt-for-speed/5154.

**Comment by bluss** [comment]
Have you managed to reproduce this in a relatively small program? How do we make an example where the adapter shows up more than once?

**Comment by bholley** [comment]
So I tried reproducing with [1], but it didn't work. I then had another look at the binary I've been analyzing, and it appears that I was mistaken about there being an adapter for every callsite. There are many adapters, but they seem to be spread through the code, at intervals of around 64k. Each instance is only referenced by code near to it, generally with an LEA.

So my guess is that LLVM is doing this to allow relative address loads with 16-bit operands. It still seems like we should avoid the adapters entirely, but that's probably better addressed in the issue that @kennytm mentioned.

So I'll go ahead and close this hear. Sorry for the noise.

[1] https://play.rust-lang.org/?gist=fbd0b57c6e86763072dd148bb629f7ce&version=stable

**Comment by bluss** [comment]
It could be beneficial to #[inline] the `Debug` impls for all the integer types -- since they just call the Display `fmt`?

**Comment by bholley** [comment]
That does seem worth doing, assuming it's not too hard.
