### ISSUE TITLE
The standard libary documentation renders some links as red, they feel like missing pages to me

### ISSUE THREAD

**Issue by timClicks** [rust-lang/rust#47801]
In the interests of improving the on-boarding experience for newcomers to Rust, I thought it would be worthwhile to share a personal anecdote of something that was a snag for my own learning.

Apparently I've been trained by Wikipedia/MediaWiki defaults to see red links and think they mean missing page. It took me an embarrassingly long time to realize that struct definitions are perfectly clickable. So for several months while learning Rust I eagerly waited for Rust's docs to be updated with info about their struct definitions.

I have no idea if this is a widespread phenomenon, but remarkably the cognitive dissonance still lingers. I'm also not certain if this warrants filing an issue. Feel free to mark as wontfix :)

**Comment by nagisa** [comment]
We certainly can change the colour to something else.

**Comment by nagisa** [comment]
Fixing this would involve changing [this](https://github.com/rust-lang/rust/blob/4cf26f8a133039bfeb5b9f684df9f547278db206/src/librustdoc/html/static/themes/main.css#L133) class (and the equivalent for the dark theme css) to some other colour.

**Comment by PramodBisht** [comment]
@nagisa I would like to take that up. Any suggestion what color I should use for both themes?.

**Comment by nagisa** [comment]
I’ve no opinions on the colour, other than that it should be distinct enough from the colours used for the other kinds of items.

**Comment by tinaun** [comment]
the color has always looked orange to me, perhaps make it slightly lighter?

**Comment by kennytm** [comment]
Changing the team from dev-tools/rustdoc to docs. This is more about a stylistic decision of the documentation.

**Comment by phansch** [comment]
fwiw, I picked up Rust ~2 months ago and initially had the same thought when reading Rust documentation with lots of red links 👍

**Comment by pickfire** [comment]
That orange does look nice to me though. But the more confusing parts to me is that some clickable parts are black (it takes me some time to figure out how to go to other crates doc or previous level of crates doc without pressing the previous tab button in browser).

As reference: https://doc.rust-lang.org/std/ops/struct.Range.html

- `std` and `ops` from the title (`std::ops::Range`) are clickable.
- `std::ops` in rectangle from the left navigation bar are clickable, not congruent with `Struct Range` in rectangle above it.

**Comment by steveklabnik** [comment]
I believe this was fixed by https://github.com/rust-lang/rust/pull/47806
