### ISSUE TITLE
unreachable_pub lint ignores nested re-exports

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#47816]
Playground: <https://play.rust-lang.org/?gist=d9e9fe07b83f07a3f9b908c0c7405a99&version=nightly>

```
#![deny(unreachable_pub)]

mod one {
    mod two {
        pub struct S;
    }
    pub use self::two::S;
}
pub use self::one::S;
```

```
error: unreachable `pub` item
 --> src/lib.rs:7:5
  |
7 |     pub use self::two::S;
  |     ---^^^^^^^^^^^^^^^^^^
  |     |
  |     help: consider restricting its visibility: `pub(crate)`
  |
note: lint level defined here
 --> src/lib.rs:1:32
  |
1 | #![crate_type = "lib"] #![deny(unreachable_pub)]
  |                                ^^^^^^^^^^^^^^^
  = help: or consider exporting it for use by other crates
```

-----

```
#![deny(unreachable_pub)]

mod one {
    mod two {
        pub struct S;
    }
    pub(crate) use self::two::S;
}
pub use self::one::S;
```

```
error[E0364]: `S` is private, and cannot be reexported
 --> src/lib.rs:9:9
  |
9 | pub use self::one::S;
  |         ^^^^^^^^^^^^
  |
note: consider marking `S` as `pub` in the imported module
 --> src/lib.rs:9:9
  |
9 | pub use self::one::S;
  |         ^^^^^^^^^^^^
```

-----

A single level of re-export works:

```
#![deny(unreachable_pub)]

mod one {
    pub struct S;
}
pub use self::one::S;
```

```
 Finished dev [unoptimized + debuginfo] target(s) in 0.27 secs
```

**Comment by zackmdavis** [comment]
After [inserting some logging statments](https://github.com/zackmdavis/rust/commit/ea6fb0fa7efaf62), it _looks_ like what's going on here is that `use` items within modules just don't get inserted into the [`AccessLevels` map](https://github.com/rust-lang/rust/blob/75af9df71b9eea84f281cf7de72c3e3cc2b02222/src/librustc/middle/privacy.rs#L38) that the [lint uses to](https://github.com/rust-lang/rust/blob/75af9df71b9eea84f281cf7de72c3e3cc2b02222/src/librustc_lint/builtin.rs#L1409) determine reachability (but crate-level `pub use`s do).

```
 INFO 2018-07-29T19:12:20Z: rustc_lint::builtin: ZMD checking item Use(path(self::two::S), Single) with id NodeId(9)
 INFO 2018-07-29T19:12:20Z: rustc_lint::builtin: ZMD debug access levels map is {NodeId(0): Public, NodeId(8): Exported, NodeId(13): Public, NodeId(12): Public, NodeId(6): Exported}
```

It seems like this behavior is intended?—librustc_privacy's `EmbargoVisitor::visit_item` [comments that reëxports are](https://github.com/rust-lang/rust/blob/75af9df71b9eea84f281cf7de72c3e3cc2b02222/src/librustc_privacy/lib.rs#L234-L235) `visit_mod`'s responsibility, but `visit_mod` looks at [`hir::def::Export`](https://github.com/rust-lang/rust/blob/75af9df71b9eea84f281cf7de72c3e3cc2b02222/src/librustc/hir/def.rs#L214-L224)s, which only stores information about the target, not the `pub use` item.

**Comment by zackmdavis** [comment]
↑ Unless someone understands how the reachability analysis needs to change, and given the increased prominence of this lint owing to the 2018 edition, we might want to quickly PR a change that declines to lint `use` statements (with a FIXME comment pointing to this issue), on the grounds that false-negatives (whose consequence is, at worst, slightly less idiomatic code) are less bad than false-positives (whose consequence is, at worst, undermining users' trust in the correctness of the compiler, causing them to abandon Rust, causing thousands or millions of lost [QALYs](https://en.wikipedia.org/wiki/Quality-adjusted_life_year) as our civilization continues to depend on memory-unsafe software).
