### ISSUE TITLE
Incorrect use of traits::SizedReturnType

### ISSUE THREAD

**Issue by Zoxc** [rust-lang/rust#47830]
https://github.com/rust-lang/rust/blob/771873c84137842c78cfc39625613b95867d21ef/src/librustc/infer/anon_types/mod.rs#L630

There is no `return` in sight here.

**Comment by kennytm** [comment]
`SizedReturnType` was introduced in #42850. Previously it was `ReturnType` introduced in #35091 (https://github.com/rust-lang/rust/commit/d92e594c3801a8066f95305c87e53a7ecfb24e9b#diff-1d1b0d29a2e8da97c6bfb6e364d920c7R1652)

**Comment by Enselic** [comment]
This issue can be closed because this was fixed in https://github.com/rust-lang/rust/commit/5b279c801635c2762c013c1d13a9bead3bcd9df4#diff-98923b31651a0150fc5eae47f5ceb44f716b521762db4e37cf9292dac7b3e040
