### ISSUE TITLE
throw away rustup-init.exe

### ISSUE THREAD

**Issue by lyrachord** [rust-lang/rust#47847]
Yes, it's complaining. Without it, no growth.

I downloaded rust msvc zip package. NO manual tells me the ENV.
Fine, run rustup-init.exe. It's dummy no customizer, it mess my c disk.
After hello, I try to find the rust install directoy, no result.

I think it's a big wrong.
I just hate the lnx console, my CmdEmu is great.
There are many people like me. We are members of the community. IAW we are god. You against your God, He?! (joking)
So the rustup-init.exe make people annoyance.
The fashion like D's zip and exe package. It's really stupy.

I try to find some useful information from issues, nothing.

Is there a clean package to the windows-lnx users?

**Comment by nagisa** [comment]
Standalone installers for rustc can be found on [this page](https://www.rust-lang.org/en-US/other-installers.html#standalone).

**Comment by lyrachord** [comment]
@nagisa Thanks, that's not my point. I downloaded the dummy zip from there before rustup-init.exe.

The key of this issue is to give a hint to PM, the management and the care for user are important, are they? If not, why is there a rust?  Just because of old school C/C++? Fine, If there is no care, may another rust called fr is come.

What Jack Ma says, If no change, I change you. Yes?

I hope the rust and its community are so brilliant.

Another point:
Who take linux naming to name of rust names? unknonw?
linux has error, rust inherit that?
Don't make brain stall.
Declaration By Exception, it's another important rule for management.

Someone label this issue to management category?

**Comment by jonas-schievink** [comment]
Rustup issues should be filed at https://github.com/rust-lang/rustup, but this one doesn't sound particularly actionable
