### ISSUE TITLE
Thin out rustc_codegen_llvm dependencies.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#47849]
I'm working on `rustc_mir` and `rustc_codegen_llvm` gets rebuilt even though it barely uses anything.
cc @oli-obk @michaelwoerister Can we do this long-term given #46882 and any other plans?

**Comment by oli-obk** [comment]
should be possible...

things left to do after #46882 

* rustc_mir::interpret::{read_target_uint, const_val_field};
* rustc_mir::monomorphize
    * Instance
    * resolve_drop_in_place
    * resolve_closure
    * item::*

**Comment by mati865** [comment]
Is it small enough?
https://github.com/rust-lang/rust/blob/38cd9489f75f4a4387296ee304e2287f7c32c211/src/librustc_codegen_llvm/Cargo.toml#L13-L18

**Comment by Mark-Simulacrum** [comment]
Cargo.toml is not the source of truth anymore -- sysroot dependencies will become relevant after https://github.com/rust-lang/rust/pull/61727, and those aren't listed in any one place. A number of crates are currently being pulled from the sysroot.

**Comment by eddyb** [comment]
This has been solved by #61062. #61727 will have more accurate tracking, but the dependencies are gone.
