### ISSUE TITLE
Surprising whitespace sensitivity in type parameters

### ISSUE THREAD

**Issue by matklad** [rust-lang/rust#47856]
Consider this code:

```Rust
struct Ok <T: Clone + = ()> { t: T }

struct Err<T: Clone +=  ()> { t: T }
```

The `Ok` struct compiles just right, but the `Err` one fails with 

```
error: expected one of `(`, `+`, `,`, `::`, `<`, `=`, or `>`, found `+=`
 --> main.rs:2:21
  |
2 | struct Err<T: Clone +=  ()> { t: T }
  |                     ^^ expected one of 7 possible tokens here

error: aborting due to previous error
```

I think this behavior is wrong: for tokens like `>>` or `||` use use "context sensitive" lexing.

**Comment by petrochenkov** [comment]
Yeah, "token splitting" (`&&` -> `& &` or `+=` -> `+ =`) is done very inconsistently.
It's not done automatically, but manually if the code author expects the split version to result in valid code sometimes. It looks like nobody expected `+ =` to be a fragment of valid code in this position.

**Comment by Crazycolorz5** [comment]
I assume no one would mind if I took a look at this.
