### ISSUE TITLE
Pretty-print mode to replace glob imports with a precise list of names

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#4786]
```
13:58 < bstrie> is there a pretty-print mode to replace a glob import with a
                precise list of names?
13:59 <@pcwalton> bstrie: no unfortunately
13:59 <@pcwalton> good idea though
```
So if I have a file with this:
```
use foo::*;
```
...and of all the things that `foo` provides, I only ever end up using `bar` and `baz`, then it should rewrite the import to:
```
use foo::{bar, baz};
```

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#617
