### ISSUE TITLE
failed to run './x.py build' on Ubunbu docker container based on s390x platform

### ISSUE THREAD

**Issue by amber-zhang** [rust-lang/rust#47871]
Hi,

As topic said, I failed to run './x.py build' on Ubunbu docker container based on s390x platform. Below is my platform info and the detailed error.

```
root@2005b3ffa5b1:/sovrin/rust# uname -a
Linux 2005b3ffa5b1 4.4.0-59.80.el7_2.ssc_k_1_0.8.s390x #1 SMP Mon Jul 31 15:55:57 EDT 2017 s390x s390x s390x GNU/Linux
root@2005b3ffa5b1:/sovrin/rust# uname -m
s390x
root@2005b3ffa5b1:/sovrin/rust# uname -s
Linux

root@2005b3ffa5b1:/sovrin/rust# ./x.py build
Updating submodules
Traceback (most recent call last):
  File "./x.py", line 20, in <module>
    bootstrap.main()
  File "/sovrin/rust/src/bootstrap/bootstrap.py", line 763, in main
    bootstrap()
  File "/sovrin/rust/src/bootstrap/bootstrap.py", line 737, in bootstrap
    build.update_submodules()
  File "/sovrin/rust/src/bootstrap/bootstrap.py", line 637, in update_submodules
    run(["git", "submodule", "-q", "sync"], cwd=self.rust_root, verbose=self.verbose)
  File "/sovrin/rust/src/bootstrap/bootstrap.py", line 143, in run
    ret = subprocess.Popen(args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by kennytm** [comment]
The error indicates you haven't installed `git`. 

You may also add

```toml
[build]
submodules = false
```

to the `config.toml` to prevent `x.py` from managing the submodules.

**Comment by amber-zhang** [comment]
@kennytm 
Thanks so much for your prompt reply! it works. It takes about 43 mins to finish the build

**Comment by kennytm** [comment]
@amber-zhang Great!

Since this is just a problem of missing dependency which works otherwise, I'm closing this issue.

**Comment by amber-zhang** [comment]
@kennytm Hi, although it build successfully, I fail to run cargo command with the error. I checked and found that ~/.cargo/bin directory doesn't exist

root@2005b3ffa5b1:/# cargo
bash: cargo: command not found
root@2005b3ffa5b1:/# rustc --version
rustc 1.25.0-dev

Below is my build process.
git clone  <rust master branch>
cd rust
./x.py build
./x.py install

**Comment by kennytm** [comment]
@amber-zhang You need to enable this option in `config.toml`:

```toml
[build]
# Enable a build of the extended rust tool set which is not only the compiler
# but also tools such as Cargo. This will also produce "combined installers"
# which are used to install Rust and Cargo together. This is disabled by
# default.
extended = true
```

**Comment by amber-zhang** [comment]
@kennytm 
Hi,  enable 'extended' as true and rerun './x.py build', get openssl version incompatible issue.  Then I download OpenSSL_1_0_2n from https://github.com/openssl/openssl/releases and compile it successfully,  'make install' said openssl libraries are put to /usr/local/ssl/lib directory. But when rerun './x.py build', still get same problem. Are openssl package not installed the location that rust seeks. Where should I copy them to? there are libcrypto.a and libssl.a under /usr/local/lib directory. Although I copy the new compiled openssl package to /usr/local/lib and run './x.py build' again, the same problem still happens.

installing libcrypto.a
installing libssl.a
cp libcrypto.pc /usr/local/ssl/lib/pkgconfig
chmod 644 /usr/local/ssl/lib/pkgconfig/libcrypto.pc
cp libssl.pc /usr/local/ssl/lib/pkgconfig
chmod 644 /usr/local/ssl/lib/pkgconfig/libssl.pc
cp openssl.pc /usr/local/ssl/lib/pkgconfig
chmod 644 /usr/local/ssl/lib/pkgconfig/openssl.pc


=====rust build error ==========
--- stderr
thread 'main' panicked at '

This crate is only compatible with OpenSSL 1.0.1, 1.0.2, and 1.1.0, or LibreSSL
2.5 and 2.6.0, but a different version of OpenSSL was found. The build is now
aborting due to this version mismatch.

', /root/.cargo/registry/src/github.com-eae4ba8cbf2ce1c7/openssl-sys-0.9.24/build.rs:486:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed


command did not execute successfully: "/sovrin/rust/build/s390x-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "s390x-unknown-linux-gnu" "-j" "4" "--release" "--manifest-path" "/sovrin/rust/src/tools/cargo/Cargo.toml"
expected success, got: exit code: 101


failed to run: /sovrin/rust/build/bootstrap/debug/bootstrap build
Build completed unsuccessfully in 0:00:12

**Comment by amber-zhang** [comment]
I have already deleted all customized openssl installation (build from source), and install openssl via apt-get install. Now the openssl version should meet Rust's requirement, but still get same error when running './x.py build'.

==========openssl version===============
root@2005b3ffa5b1:/sovrin/rust# openssl version
OpenSSL 1.0.2g  1 Mar 2016

==========rust build error ===============
Building stage2 tool cargo (s390x-unknown-linux-gnu)
   Compiling openssl-sys v0.9.24
error: failed to run custom build command for `openssl-sys v0.9.24`
process didn't exit successfully: `/sovrin/rust/build/s390x-unknown-linux-gnu/stage2-tools/release/build/openssl-sys-a7f4b291f1248a1d/build-script-build` (exit code: 101)
--- stdout

running: "cc" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-ffunction-sections" "-fdata-sections" "-fPIC" "-I" "/usr/local/include" "-Wall" "-Wextra" "-E" "/sovrin/rust/build/s390x-unknown-linux-gnu/stage2-tools/s390x-unknown-linux-gnu/release/build/openssl-sys-d699f3753fdbfeb1/out/expando.c"
exit code: 0
cargo:rustc-cfg=osslconf="OPENSSL_NO_SSL3_METHOD"
cargo:conf=OPENSSL_NO_SSL3_METHOD

--- stderr
thread 'main' panicked at '

This crate is only compatible with OpenSSL 1.0.1, 1.0.2, and 1.1.0, or LibreSSL
2.5 and 2.6.0, but a different version of OpenSSL was found. The build is now
aborting due to this version mismatch.

', /root/.cargo/registry/src/github.com-eae4ba8cbf2ce1c7/openssl-sys-0.9.24/build.rs:486:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.



command did not execute successfully: "/sovrin/rust/build/s390x-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "s390x-unknown-linux-gnu" "-j" "4" "--release" "--manifest-path" "/sovrin/rust/src/tools/cargo/Cargo.toml"
expected success, got: exit code: 101


failed to run: /sovrin/rust/build/bootstrap/debug/bootstrap build
Build completed unsuccessfully in 0:00:04

**Comment by amber-zhang** [comment]
@kennytm 

Hi, The build succeed finally.  I deleted all openssl files build from source packages, then run ./x.py clean, ./x.py check, ./x.py build, ./x.py install. Thanks so much for your help!

**Comment by amber-zhang** [comment]
@kennytm 
Hi, rust compilation doesn't succeed really. 'cargo command not found' still happens. I didn't know when the parameter 'extended' was reset back to false. When i changed it to true and compiled again, the following error still happens.

running: "cc" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-ffunction-sections" "-fdata-sections" "-fPIC" "-I" "/usr/local/include" "-Wall" "-Wextra" "-E" "/sovrin/rust/build/s390x-unknown-linux-gnu/stage2-tools/s390x-unknown-linux-gnu/release/build/openssl-sys-d699f3753fdbfeb1/out/expando.c"
exit code: 0
cargo:rustc-cfg=osslconf="OPENSSL_NO_SSL3_METHOD"
cargo:conf=OPENSSL_NO_SSL3_METHOD

--- stderr
thread 'main' panicked at '

This crate is only compatible with OpenSSL 1.0.1, 1.0.2, and 1.1.0, or LibreSSL
2.5 and 2.6.0, but a different version of OpenSSL was found. The build is now
aborting due to this version mismatch.

', /root/.cargo/registry/src/github.com-eae4ba8cbf2ce1c7/openssl-sys-0.9.24/build.rs:486:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed


command did not execute successfully: "/sovrin/rust/build/s390x-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "s390x-unknown-linux-gnu" "-j" "4" "--release" "--manifest-path" "/sovrin/rust/src/tools/cargo/Cargo.toml"
expected success, got: exit code: 101


failed to run: /sovrin/rust/build/bootstrap/debug/bootstrap build
Build completed unsuccessfully in 0:24:46

**Comment by kennytm** [comment]
@amber-zhang is the environment variable `OPENSSL_DIR` set?

**Comment by amber-zhang** [comment]
@kennytm 
After setting environment variable OPENSSL_DIR, the openssl version issue was solved.  But I met another compile issue when building cargo.

warning: build failed, waiting for other jobs to finish...
error: build failed


command did not execute successfully: “/rust/build/s390x-unknown-linux-gnu/stage0/bin/cargo” “build” “--target” “s390x-unknown-linux-gnu” “-j” “4" “--release” “--manifest-path” “/sovrin/rust/src/tools/clippy/Cargo.toml”
expected success, got: exit code: 101


Building stage2 tool rustfmt (s390x-unknown-linux-gnu)
  Compiling rustfmt-nightly v0.3.6 (file:///rust/src/tools/rustfmt)
   Finished release [optimized] target(s) in 7.32 secs
Building stage2 tool miri (s390x-unknown-linux-gnu)
  Compiling miri v0.1.0 (file:///rust/src/tools/miri)
  Compiling byteorder v1.2.1
error[E0464]: multiple matching crates for `log`
 --> tools/miri/miri/lib.rs:10:1
  |
10 | extern crate log;
  | ^^^^^^^^^^^^^^^^^
  |
  = note: candidates:
          crate `log`: /rust/build/s390x-unknown-linux-gnu/stage2/lib/rustlib/s390x-unknown-linux-gnu/lib/liblog-856b6eee55d0c75d.rlib
          crate `log`: /rust/build/s390x-unknown-linux-gnu/stage2/lib/rustlib/s390x-unknown-linux-gnu/lib/liblog-c6a9cea65d77b4ad.rlib

error[E0463]: can’t find crate for `log`
 --> tools/miri/miri/lib.rs:10:1
  |
10 | extern crate log;
  | ^^^^^^^^^^^^^^^^^ can’t find crate

error: aborting due to 2 previous errors

error: Could not compile `miri`.

To learn more, run the command again with --verbose.


command did not execute successfully: “/rust/build/s390x-unknown-linux-gnu/stage0/bin/cargo” “build” “--target” “s390x-unknown-linux-gnu” “-j” “4” “--release” “--manifest-path” “/rust/src/tools/miri/Cargo.toml”
expected success, got: exit code: 101
