### ISSUE TITLE
Unable to deduce associated type equality

### ISSUE THREAD

**Issue by brennie** [rust-lang/rust#47897]
I'm working with [combine](/marwes/combine) and rust nightly to make some parsers and I'm wondering why both of these examples are not equivalent:

The first example compiles successfully:

```rust
pub fn source<'a, I>() -> impl Parser<Input = I, Output = Source>
where
    I: RangeStream<Item = u8, Range = &'a [u8]>,
    I::Error: ParseError<u8, &'a [u8], I::Position>,
    <I::Error as ParseError<I::Item, I::Range, I::Position>>::StreamError: From<str::Utf8Error>
{
// ...
}
```
 whereas this one
```rust
pub fn source<'a, I>() -> impl Parser<Input = I, Output = Source>
where
    I: RangeStream<Item = u8, Range = &'a [u8]>,
    I::Error: ParseError<I::Item, I::Range, I::Position>,
    <I::Error as ParseError<I::Item, I::Range, I::Position>>::StreamError: From<str::Utf8Error>
{
// ...
}
```

produces this error:
```
error[E0277]: the trait bound `<I as combine::StreamOnce>::Error: combine::ParseError<u8, &'a [u8], <I as combine::StreamOnce>::Position>` is not satisfied
  --> src/parser.rs:57:1
   |
57 | / pub fn source<'a, I>() -> impl Parser<Input = I, Output = Source>
58 | | where
...  |
89 | |     )
90 | | }
   | |_^ the trait `combine::ParseError<u8, &'a [u8], <I as combine::StreamOnce>::Position>` is not implemented for `<I as combine::StreamOnce>::Error`
   |
   = help: consider adding a `where <I as combine::StreamOnce>::Error: combine::ParseError<u8, &'a [u8], <I as combine::StreamOnce>::Position>` bound

error[E0277]: the trait bound `<I as combine::StreamOnce>::Error: combine::ParseError<u8, &'a [u8], <I as combine::StreamOnce>::Position>` is not satisfied
  --> src/parser.rs:57:1
   |
57 | / pub fn source<'a, I>() -> impl Parser<Input = I, Output = Source>
58 | | where
...  |
89 | |     )
90 | | }
   | |_^ the trait `combine::ParseError<u8, &'a [u8], <I as combine::StreamOnce>::Position>` is not implemented for `<I as combine::StreamOnce>::Error`
```

AFAICT, the bounds: `I::Error: ParseError<u8, &'a [u8], I::Position>` and `I::Error: ParseError<I::Item, I::Range, I::Position>` **should** be identical since we know `I::Item = u8` and `I::Range = &'a [u8]`.

Is this a limitation of the compiler's inference, a bug, or something else?

**Comment by Marwes** [comment]
@brennie I believe this is https://github.com/rust-lang/rust/issues/43475 (and a few other issues linked from that post). I think this is planned to be fixed with the [trait system rewrite](https://paper.dropbox.com/doc/Trait-system-LCgNlSbM5cPOyEyWdoqzW) (lazy normalization) but I don't know what the timeline is for that :(.

**Comment by rkarp** [comment]
The oldest related issue seems to be #24159, which was even before Rust 1.0. I think fixing this should be a priority considering that many people have run into this over almost 3 years.

**Comment by jackh726** [comment]
I'm going to close this since it *may* be fixed already, but regardless doesn't have an MCVE. There *are* cases where we'll still run into these types of problems, but I know there are other issues covering more complex cases.
