### ISSUE TITLE
Rustdoc should not use the dark theme by default

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#47899]
We shouldn't move users' cheese like this.

**Comment by retep998** [comment]
It actually does default to the non-dark theme currently. When it had issues on firefox however, it did default to the dark theme, and that "choice" was saved to local storage. Try clearing your local storage and seeing what the default actually is.

**Comment by steveklabnik** [comment]
Yes; this was a bug that's since been fixed, and it should only appear if you happened to load this on this particular day.
