### ISSUE TITLE
bootstrap dist command is trying to run unix date command on a windows system

### ISSUE THREAD

**Issue by onur** [rust-lang/rust#47908]
This issue is currently blocking me to [upgrade rustc on docs.rs](https://github.com/onur/rust/pull/6).

When I try to run `python x.py dist`, bootstrap is failing with following output:

```
Dist rustc stage2 (i686-pc-windows-msvc)


failed to execute command: "date" "+%B %Y"
error: The system cannot find the file specified. (os error 2)


failed to run: c:\rust\build\bootstrap\debug\bootstrap --config debian\config-win32.toml dist
Build completed unsuccessfully in 0:01:24
```

Windows doesn't have a `date` executable. I tried to copy MSYS's date (along with all dependencies) to $PATH, it worked for `x86_64-pc-windows-msvc` but still failing on `i686-pc-windows-msvc`.

`date` command is being called in [src/bootstrap/dist.rs#L450-L451](https://github.com/rust-lang/rust/blob/560a2f4faf4828ba5f48fe2bd7709265c2f5354d/src/bootstrap/dist.rs#L450-L451). It should be fairly easy to replace this with `time` crate.

**Comment by penpalperson** [comment]
I'll take this!
