### ISSUE TITLE
Please provide standalone installers for sparc64-unknown-linux-gnu

### ISSUE THREAD

**Issue by glaubitz** [rust-lang/rust#47903]
With the progress made in the past months, the Rust compiler is now stable enough on Linux/sparc64 that it can be used to build projects like ```cargo``` and ```thundbird``` (version 58 with Rust code).

I would therefore like to ask to provide standalone installers for sparc64-unknown-linux-gnu on the download page "Other Installation Methods" (https://www.rust-lang.org/en-US/other-installers.html).

**Comment by jyn514** [comment]
See https://doc.rust-lang.org/nightly/rustc/target-tier-policy.html for the policy on adding new targets.

My understanding is the linux builders have a bit of spare capacity, so that shouldn't be a blocker if we cross-compile from linux to sparc.

**Comment by jyn514** [comment]
Hi @glaubitz, are you still interested in having a standalone installer? If not I'm planning to close this issue in the next month or so.

**Comment by thesamesam** [comment]
Yes, please. I'm currently having to build these manually for each Rust release in Gentoo.

**Comment by jyn514** [comment]
Got it. It looks like sparc64-linux-gnu is currently a tier 2 target: https://doc.rust-lang.org/nightly/rustc/platform-support.html?highlight=sparc64-unknown-linux#tier-2
but https://forge.rust-lang.org/infra/other-installation-methods.html#standalone-installers only lists "tier 2 targets with host tools" (i.e. targets that have `rustc` available, excluding targets that only have `std` available).

If you want to propose uplifting sparc64 to tier 2 with host tools, there's instructions at https://doc.rust-lang.org/nightly/rustc/target-tier-policy.html#tier-2-with-host-tools.

**Comment by jyn514** [comment]
Note that you can already download std for that target today, it just won't have the compiler available: https://static.rust-lang.org/dist/rust-1.67.0-x86_64-unknown-linux-gnu.tar.gz. Maybe we should list tier 2 targets on the standalone installer page? I'm not sure if you're expecting to have just std or to have rustc as well.

**Comment by Mark-Simulacrum** [comment]
I'm going to go ahead and close this. IMO we shouldn't track desire for uplifting targets; that should be initiated by people willing to be target maintainers (per the [policy](https://doc.rust-lang.org/nightly/rustc/target-tier-policy.html)). The Project doesn't have bandwidth to take that work on ourselves.

**Comment by glaubitz** [comment]
I was wondering: Since there are standalone installers available for `sparcv9-sun-solaris` nowadays, would it be possible to enable `sparc64-unknown-linux-gnu` now as well? Testing can be done in the GCC Compile Farm which has both Linux and Solaris instances on SPARC.

**Comment by jyn514** [comment]
@glaubitz I'm not aware of anything changing since https://github.com/rust-lang/rust/issues/47903#issuecomment-1891112303. Are you volunteering to be a target maintainer?
