### ISSUE TITLE
"cannot assign to `...` because it is borrowed" error can be circumvent in pattern-matching

### ISSUE THREAD

**Issue by thierry-martinez** [rust-lang/rust#47907]
The following code is accepted by the compiler (tested with rustc 1.23 and rustc 1.24.0-beta.8):

```
fn main() {
    let mut a = 0;
    let mut b = 1;
    let mut ref_a = &mut a;
    let (ref mut ref_ref_a, ()) = (ref_a, ());
    ref_a = &mut b;
}
```

However, assigning to `ref_a` should not be allowed while `ref_a` is borrowed by `ref_ref_a`. Indeed, the following code, which looks equivalent to the code above, is rejected by the compiler:

```
fn main() {
    let mut a = 0;
    let mut b = 1;
    let mut ref_a = &mut a;
    let ref mut ref_ref_a = ref_a;
    ref_a = &mut b;
}
```

```
error[E0506]: cannot assign to `ref_a` because it is borrowed
 --> src/main.rs:6:5
  |
5 |     let ref mut ref_ref_a = ref_a;
  |         ----------------- borrow of `ref_a` occurs here
6 |     ref_a = &mut b;
  |     ^^^^^^^^^^^^^^ assignment to borrowed `ref_a` occurs here
```

**Comment by dtolnay** [comment]
I believe this is the correct behavior. The `ref_a` is **moved** into `(ref_a, ())` and `ref_ref_a` refers to the moved value, not the original `ref_a`. After the line `ref_a = &mut b`, `ref_a` is `&1` but `ref_ref_a` is `&&0`. You can confirm that a move has happened because `ref_a` is inaccessible until reassigned.

```rust
fn main() {
    let mut a = 0;
    let mut b = 1;
    let mut ref_a = &mut a;
    let (ref mut ref_ref_a, ()) = (ref_a, ());
    println!("{}", ref_a); // use of moved value
    ref_a = &mut b;
}
```

**Comment by thierry-martinez** [comment]
Thank you for the explanation! I didn't realize that constructing the pair moved the value, indeed.
