### ISSUE TITLE
Unreachable patterns warning should not be emitted if there are enum variants under condition

### ISSUE THREAD

**Issue by vityafx** [rust-lang/rust#47905]
I have a big project with a lot of features. These features add enum variants to existing enum:

    enum A {
        A,
        #[cfg(feature = "feature_b")] B,
        #[cfg(feature = "feature_c")] C,
    }

In the code I use this `enum` I match **some** of its variants. For example, this code:

    fn test(a: A) -> u8 {
        match a {
            A::A => 1,
            _ => 0,
        }
    }

In this function I care only about `A` variant. So, by disabling features `feature_b` and `feature_c` this code leads to a "unreachable pattern" warning which, of course, both helpful and sensible. I'd simply add a warning disable attribute above the function but I have such code in many different places, so this is not a good solution. It is also bad because if I do this, I'd get rid of really helpful warnings about unreachable patterns. I'd suggest the compiler to check whether there are enum variants which are not visible and simply not emit a warning.

**Comment by oli-obk** [comment]
> the compiler to check whether there are enum variants which are not visible and simply not emit a warning.

That can't be done. These variants are not "not visible". They don't exist at all. That's what `cfg` does, it conditionally adds code. Without the `cfg` being triggered that code can contain errors and broken code without the compiler ever telling you about it.

You can write

```rust
match a {
    A::A => 1,
    #[cfg(feature = "feature_b")] A::B => 0,
    #[cfg(feature = "feature_c")] A::C => 0,
}
```

**Comment by vityafx** [comment]
Yes, I need to write this everywhere. This is not user friendly :) This is useless and noisy code. Also, I don't see why the compiler can't remember these variants before making optimizations and checks later? They don't exist only because of optimization stage I guess. So, what stops the compiler from remembering those before optimization? This would be useful for people and will not require useless code.

**Comment by vityafx** [comment]
Yes, I need to write this everywhere. This is not user friendly :) This is useless and noisy code. Also, I don't see why the compiler can't remember these variants before making optimizations and checks later? What stops the compiler from remembering these variants before doing `cfg(feature)` thing and remove from its memory after semantical analysis stage. This would be useful for people and will not require useless code.

Or, perhaps (I don't know how rustc is implemented), when the AST is being built, the parser does not add anything by checking features at this stage already?

**Comment by oli-obk** [comment]
> when the AST is being built, the parser does not add anything by checking features at this stage already

Yea, `cfg`s are processed before even name resolution happens. It's one of the first things done after parsing.

**Comment by vityafx** [comment]
Sad :( Okay, now I understand why it is impossible to do easily. So, I have nothing to do but to disable those warnings for a function scope? Maybe we can do this on a `match` itself?

**Comment by oli-obk** [comment]
There have been some issues around cfgs removing things forever. Maybe we could leave them in, but ignore them in all checks/visitors and only look for them where applicable?

**Comment by vityafx** [comment]
It is interesting to me, what issues exactly?:)

Sounds good to me.

**Comment by steveklabnik** [comment]
Triage: seems that this is not possible today, and doing so would be a big change, and no comments in two years. So I'm going to give this a close! Pursuing an RFC might be a good way to tackle this, if anyone wants to try to figure out how to add something like this into the language!
