### ISSUE TITLE
Investigate splitting 32bit windows tests

### ISSUE THREAD

**Issue by aidanhs** [rust-lang/rust#47911]
https://mozilla.logbot.info/rust-infra/20180130#c14213927-c14214012

It'd be good to get some notes on how this might be done in rustbuild.

A working implementation would be fine too :)

**Comment by aidanhs** [comment]
cc #46903

**Comment by Mark-Simulacrum** [comment]
I'll do my best to come up with some instructions this weekend. If someone is super interested and I haven't yet, ping me, because it'll help expedite matters.

**Comment by aidanhs** [comment]
Test splitting also useful for #48192 which is causing timeouts, though the root cause is different.

**Comment by alexcrichton** [comment]
This has been implemented on master and we'll continue doing so while we hit timeouts, so closing
