### ISSUE TITLE
Lifetime elision rules

### ISSUE THREAD

**Issue by sander2** [rust-lang/rust#47929]
Shouldn't lifetime elision be allowed in the code below? The book (second edition) says "If there is exactly one input lifetime parameter, that lifetime is assigned to all output lifetime parameters". Since the only input lifetime used is `'a`, it seems to me that elision should be allowed here.

```
fn test_lifetime_elision_1<'a>(a: &'a A, b: &'a A) -> &A { 
  a 
} 
struct A { } 
```

Edit: to be clear: this isn't allowed by the compiler. [playground link](https://play.rust-lang.org/?gist=029784a1820ef345282a633cff7d5e96&version=stable)

**Comment by Manishearth** [comment]
The description in the book is incorrect, it's "input lifetime", not "input lifetime parameter", i.e. it should have exactly one spot in which the lifetime parameter can fit.

That said, given that we elide `&'a T -> &T` already, it might be worth eliding here as well, cc @nikomatsakis

**Comment by sander2** [comment]
Hmm that explains why the example above refuses to compile. However, even with that description the behavior seems inconsistent. See the code below. All three functions have two input lifetimes, but one of them  compiles (`test_lifetime_elision_3`) while the other two don't. [Playground](https://play.rust-lang.org/?gist=ee7d13177dc93159187ce557d85911fc&version=stable)  
```
// one input lifetime parameter, two input lifetimes; elision disallowed
fn test_lifetime_elision_1<'a>(arg1: &'a A, arg2: &'a A) -> &A { 
  arg1
} 

// one input lifetime parameter, two input lifetimes; elision disallowed
fn test_lifetime_elision_2<'a> (arg1: C<'a>, arg2: C<'a>) -> C { 
  arg1
}

// one input lifetime parameter, two input lifetimes; elision allowed
fn test_lifetime_elision_3<'a> (arg1: B<'a, 'a>) -> B { 
  arg1
}

struct A { } 
struct B < 'a, 'b > { 
  a1 : & 'a A , 
  a2 : & 'b A , 
} 
struct C < 'a > { 
  a : & 'a A , 
}
```
.. So the actual rules seem to be more complex than the documentation suggests. Perhaps it would be nice indeed to support the first two cases as well, even if it's only to make the actual rules easier to understand.

**Comment by Manishearth** [comment]
Hmm, so it seems to me that the third one should not compile [according the the rules in the RFC](https://github.com/rust-lang/rfcs/blob/master/text/0141-lifetime-elision.md#the-rules). But we can't fix that without a backwards compatibility issue.

I'm curious as to why that works but the `&'a` example doesn't

**Comment by eddyb** [comment]
cc @nikomatsakis I actually expect the original example to compile, why don't we deduplicate there?

**Comment by eddyb** [comment]
Okay I found while the implementation behaves so oddly - the elided output lifetime (that is used for all output lifetime positions) *must* come from one input (i.e. argument) type but that input type can have many copies of that lifetime, i.e. `B<'a, 'a>` and `A<'a>` are treated the same.
IMO we should deduplicate across all inputs not just within each.

**Comment by Manishearth** [comment]
The deduplicate rules are also not in the original RFC; I'll open an amendment to fix that.

**Comment by Manishearth** [comment]
Fixed in https://github.com/rust-lang/rfcs/pull/2330

**Comment by Manishearth** [comment]
Oh, also, RFC amendment is at https://github.com/rust-lang/rfcs/pull/2330

Congratulations! You helped find:

 - a discrepancy between the implemented feature and the RFC
 - a bug in the implemented feature on top of the existing discrepancy

**Comment by nikomatsakis** [comment]
So, FWIW, I consider it a bug (in the spec, not the code) that that support `fn foo(&'a u32) -> &u32`. I'd prefer that if you give something a name, you use that name. 

I've been wanting to lint against this specific case.

That said, I guess we might as well do the wrong thing consistently.

**Comment by Manishearth** [comment]
Okay, so should we punt on the RFC amendment, or open a new RFC, or .. ?

**Comment by nikomatsakis** [comment]
@Manishearth to be clear, I think the change makes sense, within the existing framework. I'd just like to shift it (as part of the move the "in-band lifetimes" change). So the amendment seems fine.

**Comment by Manishearth** [comment]
Yeah, I got that, I just wasn't sure on how best to push this through the RFC process 😄 

Amendment sounds great.

**Comment by steveklabnik** [comment]
I'm going to close this bug; it seems that if anything is left to do, it belongs on the RFC repo, or the book repo. Thank you!
