### ISSUE TITLE
Dependency tracking README outdated?

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang/rust#47935]
I believe that https://rust-lang-nursery.github.io/rustc-guide/query.html is _more updated than_ https://github.com/rust-lang/rust/blob/master/src/librustc/dep_graph/README.md 

Is there anything in the latter that is missing in the former?

cc @michaelwoerister @nikomatsakis

**Comment by nikomatsakis** [comment]
I plan to do a sweep soon and remove the READMEs from the repo. I'm not sure how much of the material in that particular one is still relevant though.

**Comment by michaelwoerister** [comment]
The readme is largely outdated. The "Testing the dependency graph" and "Debugging the dependency graph" sections are still correct, I think, but the rest is probably just confusing at this point.

**Comment by nikomatsakis** [comment]
I opened https://github.com/rust-lang-nursery/rustc-guide/issues/87 to talk about moving that bit of content over.
