### ISSUE TITLE
Can't cast self to &Trait in a default method implementation

### ISSUE THREAD

**Issue by YaLTeR** [rust-lang/rust#47937]
[Playground](https://play.rust-lang.org/?gist=7e491773ee60fe53e118e6d41aa87ccb&version=stable)
```rust
// This works:
trait Trait {
    fn f(&self);
}

impl<T> Trait for T where T: Trait {
    fn f(&self) {
        let _ = self as &Trait;
    }
}

// But this doesn't:
trait Trait2 {
    fn f(&self) {
        let _ = self as &Trait2;
    }
}
```
The second one produces the following error:
```
   |
15 |         let _ = self as &Trait2;
   |                 ^^^^ `Self` does not have a constant size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `Self`
   = help: consider adding a `where Self: std::marker::Sized` bound
   = note: required for the cast to the object type `Trait2`
```
Adding `where Self: Sized` makes the trait not object-safe which is undesired (and should not be required, see the first example which works).

rustc 1.23.0 (766bd11c8 2018-01-01), same on Beta and Nightly.

This issue has been assigned to @Patryk27 via [this comment](https://github.com/rust-lang/rust/issues/47937#issuecomment-638813751).

**Comment by dtolnay** [comment]
I believe this is working correctly -- trait objects can only be made from `Sized` types. Your example which works implicitly has a `Self: Sized`. The example which does not work is equivalent to:

```rust
trait Trait {
    fn f(&self);
}

impl<T> Trait for T where T: ?Sized + Trait {
    fn f(&self) {
        let _ = self as &Trait;
    }
}
```

**Comment by YaLTeR** [comment]
But if you try adding a `where Self: Sized` constraint to the second example in the playground as the compiler suggests the included function which uses both traits as trait objects will refuse to compile due to the function call becoming not object-safe?

**Comment by dtolnay** [comment]
> the included function which uses both traits as trait objects will refuse to compile

You mean like this?

```rust
trait Trait2 where Self: Sized {
    fn f(&self) {
        let _ = self as &Trait2;
    }
}
```

I think the error is suggesting to add `where Self: Sized` to the method, since the method is what requires `Self: Sized` in order to build a trait object.

```rust
trait Trait2 {
    fn f(&self) where Self: Sized {
        let _ = self as &Trait2;
    }
}
```

The diagnostic could be clearer about precisely where `Self: Sized` would help.

**Comment by YaLTeR** [comment]
Yes, I was adding `where Self: Sized` to the method as you're showing. This is what happens then:
```rust
fn f(x: &Trait, y: &Trait2) {
    let _ = x.f();
    let _ = y.f();
}
```
=>
```
error: the `f` method cannot be invoked on a trait object
  --> src/main.rs:21:15
   |
21 |     let _ = y.f();
   |               ^
```

**Comment by estebank** [comment]
Triage: the original code produces a `Self: Sized` structured suggestion instead of a `help`, but that leads to the same error pointed out in the last comment above:

```
error[E0277]: the size for values of type `Self` cannot be known at compilation time
  --> src/main.rs:15:17
   |
14 |     fn f(&self) {
   |                - help: consider further restricting `Self`: `where Self: std::marker::Sized`
15 |         let _ = self as &Trait2;
   |                 ^^^^ doesn't have a size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `Self`
   = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
   = note: required for the cast to the object type `dyn Trait2`
```

The compiler should offer @dtolnay's explanation.

**Comment by Patryk27** [comment]
Current `beta` prints:
```
error[E0277]: the size for values of type `Self` cannot be known at compilation time
 --> src/lib.rs:3:17
  |
3 |         let _ = self as &Trait2;
  |                 ^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `std::marker::Sized` is not implemented for `Self`
  = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
  = note: required for the cast to the object type `dyn Trait2`
help: consider further restricting `Self`
  |
2 |     fn f(&self) where Self: std::marker::Sized {
  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
... so seems like there's nothing more to do here, right?
