### ISSUE TITLE
Searchbar in docs for std crate show entries which don't appear to exist

### ISSUE THREAD

**Issue by manpat** [rust-lang/rust#47934]
Searching for from_bool on both [https://doc.rust-lang.org/std/](https://doc.rust-lang.org/std/) and in my local docs (with `rustup doc`), shows results for functions on primitive types which when clicked, don't link to any functions.

![rustfrom_bool](https://user-images.githubusercontent.com/6134057/35692577-a94c2da0-0773-11e8-8c32-6e51c827327e.png)
![primtypefrom_bool](https://user-images.githubusercontent.com/6134057/35692668-d7b8647e-0773-11e8-880d-c955dd0c1c8f.png)

Following recommendations from rustc error messages, it appears to be that these functions have leaked in from the `compiler_builtins` crate somehow, but don't appear anywhere else in the documentation.

**Comment by ollie27** [comment]
This was fixed by #47675: https://doc.rust-lang.org/nightly/std/?search=from_bool

**Comment by steveklabnik** [comment]
Ah ha! Thanks for finding that, @ollie27 .

@manpat thank you for filing; I was the one that told you you should, and wasn't aware of this fix. I appreciate it, but since it's already been fixed, I'm going to give this a close.
