### ISSUE TITLE
Macro expansion fails when adding an extra surrounding

### ISSUE THREAD

**Issue by eduardosm** [rust-lang/rust#47940]
Considering this simple example:
```rust
macro_rules! test_macro {
    {$($key:expr => $value:tt),*} => {};
    ({$($key:expr => $value:tt),*}) => {};
}

fn test() {
    test_macro!{"a" => ("b")};
    test_macro!({"a" => ("b")});
}
```
The first invoation is accepted by the compiler, however, the second produces the following error:
```
error: expected one of `.`, `;`, `?`, `}`, or an operator, found `=>`
 --> failing_macro.rs:8:22
  |
8 |     test_macro!({"a" => ("b")});
  |                     -^^ unexpected token
  |                     |
  |                     expected one of `.`, `;`, `?`, `}`, or an operator here
```
Changing the type of delimiter (parenthesis, braces...) does not seem to change this behavior.

**Comment by dtolnay** [comment]
I think this is working as intended -- `{"a"` is a valid start to an $expr (for example `{"a".len()}` is such an $expr, as seen in the suggestion that it expected a `.` token) so the macro will begin to match the $key:expr in your first rule.

If you want the rule with the surrounding `{`...`}` to be matched when the input begins with `{`, you can move it before the first rule.

```rust
macro_rules! test_macro {
    ({$($key:expr => $value:tt),*}) => {};
    ($($key:expr => $value:tt),*) => {};
}

fn test() {
    test_macro!("a" => ("b"));
    test_macro!({"a" => ("b")});
}
```

**Comment by eduardosm** [comment]
I see your point. However, the outer delimiters of the first rule are  `{`...`}`, wheras the second invocation uses `(`...`)`. So, the second invocation shoudn't be trying to match the `$key:expr` of the first rule. I believe that a macro rule should be discarded if the outer delimiters do not match, without looking further ahead.

**Comment by dtolnay** [comment]
By design the outer delimiter is not significant, you can call any macro with any delimiter. All of the following are supported and stable.

```rust
vec![a, b, c]

vec!(a, b, c)

vec! {
    a,
    b,
    c,
}
```

**Comment by eduardosm** [comment]
I had thought that the outer delimiter actually mattered. Changing the order seems to work in this case. Thanks.

**Comment by dtolnay** [comment]
Great!
