### ISSUE TITLE
 LTO + >=O2 cripples panics

### ISSUE THREAD

**Issue by MageSlayer** [rust-lang/rust#47965]
Hi

I am trying to investigate LTO issue.
It appears when I build my project with opt-level = 2 (or 3) and lto = true.
For some reason panics stop working, I mean __rust_maybe_catch_panic is triggered but never returns.

I am under Linux x64 rust compiler nightly-2017-12-07.
Unfortunately I cannot reproduce it in isolation or on any later compiler (due to other regressions).

Any help?

**Comment by MageSlayer** [comment]
@alexcrichton 
Alex, you might be the person to discuss as I found your comments on
https://github.com/rust-lang/rust/pull/32900

**Comment by alexcrichton** [comment]
Ah sorry there's not much information to go on here so I'm not sure what's happening :(

You may want to try specifying `-Z thinlto=no` via `RUSTFLAGS` if you can, as I think this was around the time that ThinLTO was enabled.

**Comment by MageSlayer** [comment]
Nope, it does not help.
Looks like compiler somehow generates broken seh.
I can see in gdb that rust_eh_personality is called until some frame.

**Comment by MageSlayer** [comment]
Related to https://github.com/rust-lang/rust/issues/48088
Adding #[unwind] to all extern functions fixed the issue with LTO.
