### ISSUE TITLE
rustdoc: extract doc-comments to markdown files

### ISSUE THREAD

**Issue by ozkriff** [rust-lang/rust#47963]
Hi. Can I somehow tell `rustdoc` to extract doc-comments to separate `.md` files? I want to run [`markdownlint-cli`](https://github.com/igorshubovych/markdownlint-cli) on them.

**Comment by steveklabnik** [comment]
Not currently, no.

**Comment by Mark-Simulacrum** [comment]
I'm going to go ahead and close this as it seems unlikely that such a feature would be implemented in the current version of rustdoc. I believe @steveklabnik has been working on something similar to this already in the next rustdoc.

**Comment by steveklabnik** [comment]
*extremely* so, in fact...
