### ISSUE TITLE
Collections documentation could mention performance of BinaryHeap impl

### ISSUE THREAD

**Issue by Ryman** [rust-lang/rust#47976]
I can't seem to find anything similar to the docs outlined [here](https://doc.rust-lang.org/std/collections/index.html#performance) for [`BinaryHeap`](https://doc.rust-lang.org/std/collections/struct.BinaryHeap.html) so I'm left to assume it aligns with the usual bounds as mentioned on [wikipedia](https://en.wikipedia.org/wiki/Binary_heap). It would be good if that information was available either in the collection overview or in the docs for BinaryHeap itself.

**Comment by DevQps** [comment]
I hope to create a PR for this somewhere today, adding the performance (big O-notation) characteristics to the collection page.
