### ISSUE TITLE
Error compiling code using bitflags-1.0.1

### ISSUE THREAD

**Issue by bobtwinkles** [rust-lang/rust#47977]
This code based on [this code from the `bitflags` test suite](https://github.com/rust-lang-nursery/bitflags/blob/13e54b43c92c9ef170b6a6a122da82d8f5c0d283/src/lib.rs#L933-L948) fails to compile:
```rust
#![feature(nll)]
#[macro_use]
extern crate bitflags;

bitflags! {
    struct Flags: u32 {
        const A = 0b00000001;
        const B = 0b00000010;
        const C = 0b00000100;
    }
}

pub fn test_set_diff() {
    let mut m1 = Flags::empty();
    // set difference
    m1 -= m1;
}

fn main() {
}
```

[Playground link](https://play.rust-lang.org/?gist=fed4dd05a172fafd371c676eb2136e46&version=nightly).
Looking at the generated MIR, the problematic BB is here:
```
    bb1: {                              
        StorageLive(_3);                 // bb1[0]: scope 1 at src/main.rs:16:5: 16:7
        _3 = &mut _1;                    // bb1[1]: scope 1 at src/main.rs:16:5: 16:7
        StorageLive(_4);                 // bb1[2]: scope 1 at src/main.rs:16:11: 16:13
        _4 = _1;                         // bb1[3]: scope 1 at src/main.rs:16:11: 16:13
        _2 = const std::ops::SubAssign::sub_assign(move _3, move _4) -> bb2; // bb1[4]: scope 1 at src/main.rs:16:5: 16:13
                                         // ty::Const
                                         // + ty: for<'r> fn(&'r mut Flags, Flags) {<Flags as std::ops::SubAssign>::sub_assign}
                                         // + val: Function(DefId(2/0:904 ~ core[1cc2]::ops[0]::arith[0]::SubAssign[0]::sub_assign[0]), Slice([Flags, Flags]))
                                         // mir::Constant
                                         // + span: src/main.rs:16:5: 16:13
                                         // + ty: for<'r> fn(&'r mut Flags, Flags) {<Flags as std::ops::SubAssign>::sub_assign}
                                         // + literal: const std::ops::SubAssign::sub_assign
    }
```
We can see that this should work with two-phase borrows, and [indeed it does](https://play.rust-lang.org/?gist=43797617416d7d841b6297cebd5f88e8&version=nightly) so this might not be something that needs to be addressed separately if the intention is to stabilize two-phase borrows together with NLL.

**Comment by cuviper** [comment]
Neither of your playground links give me errors -- was this already fixed by a new nightly?

**Comment by bobtwinkles** [comment]
Huh, I could have sworn compilation fails on the playground but now I'm doubting my memory. I do know that building like so fails:
```
RUSTFLAGS=-Znll cargo +nightly test
   Compiling bitflags v1.0.1 (file:///home/bob_twinkles/Code/rust/bitflags)
error[E0503]: cannot use `m1` because it was mutably borrowed
   --> src/lib.rs:943:15
    |
943 |         m1 -= m1;
    |         --    ^^ use of borrowed `m1`
    |         |
    |         borrow of `m1` occurs here

error: aborting due to previous error

error: Could not compile `bitflags`.
```
So I think this is an error with the handling of `-Znll` rather than `#![feature(nll)]` or that behavior changed recently. Very strange.

**Comment by bobtwinkles** [comment]
OK, I think figured out why this happens. Two-phased borrows are only performed when either the `nll` feature or the `two-phase-borrow` debugging flag is passed: https://github.com/rust-lang/rust/blob/29c8276cee4a0eab7e0634ff25c6b47bd9f87c6c/src/librustc/session/mod.rs#L468-L470

Notably, this does not include situations where NLL is enabled via `-Znll`, since that information is stored in `debugging_opts.nll` rather than in `features.borrow().nll`. The fix would be pretty trivial: simply rewritting the body of `two_phased_borrows` like so should do it:
```rust
self.nll() || self.opts.debugging_opts.two_phase_borrow
```
However, this would mean that `-Znll` would imply `-Ztwo_phased_borrows` which might not be what we want; the intention may have been to allow independent debugging of these features (CC @nikomatsakis and @pnkfelix on that). If the change proposed above is desirable I can submit a PR, otherwise feel free to close this issue.

**Comment by bobtwinkles** [comment]
Apparently this is intended behavior, closing.
