### ISSUE TITLE
Derive for items defined inside a function receive incorrect span information

### ISSUE THREAD

**Issue by sgrif** [rust-lang/rust#47983]
Steps to reproduce (`rustc 1.25.0-nightly (56733bc9f 2018-02-01)`)

## src/main.rs

```
#![feature(proc_macro)]

extern crate repro;
use repro::AsChangeset;

fn main() {
    #[derive(AsChangeset)]
    #[table_name = "users"]
    struct UserForm {
        id: i32,
        name: String,
    }
}
```

## src/lib.rs

```
#![feature(proc_macro)]

extern crate proc_macro;
use proc_macro::TokenStream;

#[proc_macro_derive(AsChangeset, attributes(table_name))]
pub fn derive(input: TokenStream) -> TokenStream {
    for tt in input {
        println!("{:#?}", tt);
    }
    TokenStream::empty()
}
```

The `struct` token will have an incorrect span which points at the correct source code, but shows `<macro expansion>:1:1` instead of a file/line number when used. Every other token will have a useless span `Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }`

**Comment by sgrif** [comment]
There also appears to be a bug when one of these dummy spans is received. `Span::resolved_at` appears to do absolutely nothing.

**Comment by alexcrichton** [comment]
This is caused by https://github.com/rust-lang/rust/issues/43081, but I'm not precisely sure why yet
