### ISSUE TITLE
Make it clear that it's not the second call to Arc::from_raw that causes memory safety issues, but the first Drop

### ISSUE THREAD

**Issue by SoniEx2** [rust-lang/rust#47994]
It's not clear from the documentation of Arc::from_raw that it's not the second call to Arc::from_raw that is the issue, but the first Drop.

I'm not sure if this is documented anywhere, but it wouldn't make sense for it to work any other way.

(Can I rely on this behaviour?)

**Comment by bluss** [comment]
I would be careful to promise anything more. Each owned `Arc<T>` value in the program independently represents a strong count of +1 and a promise to drop the refcount (and potentially the T and the ArcBox), also during unwinding. It's not trivial to map out the number of possible memory safe operations on such a second `Arc<T>`, or the simultaneous first `Arc<T>` in the scenario (the first `Arc<T>` can "verify" that it is unique, and will do so in `get_mut`!).

**Comment by SoniEx2** [comment]
Ah, you're right, if you have multiple from_raw's, you just aren't allowed to let them drop.

**Comment by jonas-schievink** [comment]
From the comments, this doesn't seem like a guarantee we want to give for `Arc`, so closing.
