### ISSUE TITLE
Weird crashing

### ISSUE THREAD

**Issue by loverguy** [rust-lang/rust#48039]
Hi there! i just got a crashing problem it's look like a video card crashing
My pc's space: 
ram: 8gb
GPU: GTX 550 ti
CPU: Pentium Dual cpu E2220
OS: windows 7 64bit
Thanks in advance !

**Comment by loverguy** [comment]
edit:
[error.log](https://github.com/rust-lang/rust/files/1700159/error.log)
this the crash file

**Comment by qmx** [comment]
@loverguy that's the issue tracker for the Rust Programming Language, not the Rust Game :smile:

**Comment by steveklabnik** [comment]
Yes, this is the wrong place. Sorry @loverguy , I don't know where to file bugs against that Rust :)

**Comment by loverguy** [comment]
lol sorry
