### ISSUE TITLE
Potential memory leak in resize_default?

### ISSUE THREAD

**Issue by moonheart08** [rust-lang/rust#48034]
Take the following code (And don't tell me it's poorly written):
https://play.rust-lang.org/?gist=4bfa347235db877354f6705b072ef4ca&version=nightly
When ran, it uses about 33 MB.
Now take that same code, but double the size of the chunk (set CHUNK_SIZE to 128).
It's now using 10 times as much memory, at 300 MB.
This does not make any sense at all (at least to me) and looks a lot like a memory leak.

Sorry for the unprofessional bug report, i'm unsure if this is a bug or me being bad at basic math.

MULTIEDIT: Realised that the code i copied over broke a bit when put into that single file. Fixed.

**Comment by kennytm** [comment]
Your `World` contains `CHUNK_SIZE`<sup>2</sup> `Chunk`s and each `Chunk` contain `CHUNK_SIZE`<sup>2</sup> `Tile`s. Therefore when you double `CHUNK_SIZE`, the actual memory use will be scaled up by 2<sup>4</sup> = 16×, so the memory use is totally normal.

Perhaps you want to use `WORLD_SIZE` in the `impl Default for World` instead.

**Comment by moonheart08** [comment]
Wait
Oh my god. I'm dumb.
