### ISSUE TITLE
env! has a completely undocumented optional second argument for setting the error message

### ISSUE THREAD

**Issue by ExpHP** [rust-lang/rust#48044]
```rust
fn main() {
    env!(); //~ ERROR env! takes 1 or 2 arguments
}
```
*...or 2 arguments?* :neutral_face:

```rust
fn main() {
    env!("testestest", "eh??"); //~ ERROR eh??
}
```

**Comment by kennytm** [comment]
It was introduced by @sfackler in c3825c835197a97ff4f254802efde80335d3833b in Rust 0.8 (along with `option_env!`). The [relevant test case still exists today](https://github.com/rust-lang/rust/blob/master/src/test/compile-fail/extenv-not-defined-custom.rs). I can't find any 2-argument `env!` calls other than the test cases.

**Comment by ExpHP** [comment]
I guess the question is: Is removing this an option that is even on the table?  Or is the only option at this point to document it?

I wonder how reliable crater would be at finding usages?  It does seem to me that the place where this is most likely to be used is in a build script, and there certainly are crates on crates.io with build scripts, but I'd imagine that most have external system dependencies (would `crater` even test those?).

**Comment by sfackler** [comment]
Why would we want to go through the whole process of cratering and trying to figure out if it's okay to remove when we could just document it as a thing that exists?

**Comment by ExpHP** [comment]
I only tossed it out as a theoretical, i.e. "is removing it an option to even consider?"  In order for that to be the case, it would need to be feasible, and there would need to be motivation for it.

My remark was about feasibility, but you're right about the motivation. The feature clearly isn't hurting anybody, so there is no reason to remove it.
