### ISSUE TITLE
Provide a way to change path of common css/js paths in documentations

### ISSUE THREAD

**Issue by onur** [rust-lang/rust#48094]
I am asking this for docs.rs.

Currently docs.rs is leveraging browser cache by serving every common css/js file ("rustdoc.css", "main.css", "main.js", "normalize.css", "*.woff"]) from root of the docs.rs. Otherwise docs.rs would serve 60k different copies of this files since rustdoc is generating them for each crate. Docs.rs is only replacing this file paths in documentations to provide a better/faster browsing experience.

But unfortunately new theme picker did break this feature and causing me some trouble to [update rustc](https://github.com/onur/docs.rs/issues/171) on docs.rs since it's not compatible.

I did a small talk with @GuillaumeGomez (the guy behind theme picker). He came up with an idea of adding a `--replace` or `--url` argument to rustdoc so this files can be served from a desired path. For example running `rustdoc lib.rs --url main.css /main-1.24.css --url light.css /light-1.24.css` will replace this paths for the main.css and light.css.

This will make new theme picker compatible with docs.rs and also it will dramatically improve docs.rs by removing only necessary documentation change made by docs.rs.

**Comment by GuillaumeGomez** [comment]
The alternative with `--replace` with as follow:

```
rustdoc lib.rs --replace main.css ../../main-1.24.css
```

**Comment by GuillaumeGomez** [comment]
It could as well. I don't have preference in here.

**Comment by GuillaumeGomez** [comment]
Another idea: `--files-suffix="something` which generates `rustdoc-something.css`.

**Comment by GuillaumeGomez** [comment]
The best option for the moment seems to be the one proposed by @QuietMisdreavus. We just need confirmation from @onur now.

**Comment by onur** [comment]
@GuillaumeGomez `--files-suffix` might not work, I am not just adding a suffix to common files. I am also moving them to out of target/doc directory. @QuietMisdreavus idea is great, a hook would solve this problem for me.

**Comment by GuillaumeGomez** [comment]
Then I'll implement @QuietMisdreavus' solution.

**Comment by onur** [comment]
#48511 fixed this issue
