### ISSUE TITLE
unused_unsafe gives wrong reason

### ISSUE THREAD

**Issue by main--** [rust-lang/rust#48131]
```rust
pub unsafe fn outer() {
    fn inner() {
        unsafe { /* unnecessary */ }
    }
    
    inner()
}
```

```
warning: unnecessary `unsafe` block
 --> src/main.rs:3:9
  |
1 | pub unsafe fn outer() {
  | --------------------- because it's nested under this `unsafe` fn
2 |     fn inner() {
3 |         unsafe { /* unnecessary */ }
  |         ^^^^^^ unnecessary `unsafe` block
  |
  = note: #[warn(unused_unsafe)] on by default
```

The `unsafe` block is clearly unnecessary, but it being inside a safe function which is nested in an unsafe function is clearly not the reason. [Playpen](https://play.rust-lang.org/?gist=b5509132dc7f9994e151f39d2b1da387&version=nightly)

**Comment by ExpHP** [comment]
fix looks trivial, I think I got this

**Comment by ExpHP** [comment]
More specifically, I believe [`librustc_mir::transform::check_unsafety::is_enclosed`](https://github.com/rust-lang/rust/blob/5313e8728f028cb7914f3c9f02804158a5732b52/src/librustc_mir/transform/check_unsafety.rs#L380-L399) should return `None` as soon as it encounters a safe fn.
