### ISSUE TITLE
LLVM v6 release notes

### ISSUE THREAD

**Issue by ERnsTL** [rust-lang/rust#48142]
Greetings, as you probably already know, the LLVM project is working towards a v6.0 release right now.

The [in the pre-release notes](http://prereleases.llvm.org/6.0.0/rc2/docs/ReleaseNotes.html#zig-programming-language) also contains a paragraph for each major FOSS project using LLVM, among them the *D and Zig languages*.

I know that this git repo likely is not the right place for this subject.

Nonetheless, I want to reach the largest possible audience including those responsible for liaison with the LLVM project in order to realize and seize the opportunity to be listed and presented in the official release notes as a FOSS project using LLVM.

After all, this is a way to present Rust - free exposure, in effect.

Please forward to those responsible for liason with the LLVM project.

Greetings

**Comment by ishitatsuyuki** [comment]
Using the issue tracker is not that bad - but I think you can use https://internals.rust-lang.org/ next time.

**Comment by pietroalbini** [comment]
You should email the community team at community@rust-lang.org.
