### ISSUE TITLE
Turkish Translation

### ISSUE THREAD

**Issue by halokaya67** [rust-lang/rust#48150]
Hi there,
I'm from Turkey. I'm an English teacher in Turkey. I have a translation team which consist of 7 English teachers. And we will be rewarded for each of 1100 words translations from Github. And for that our translations have to be approved by the project after we pull request the translations we made. We can translate your whole project in Turkish if you give permission to us. So please give this project to us and you will see we won't let you down. After we fork the file we will translate and send you a pull request for you to check and approve our translation. I can assure you our work will be satisfying. Best regards.

**Comment by zackmdavis** [comment]
This is the repository for the Rust compiler, which doesn't seem to have any translations. You may want to compose a PR for [rust-lang/rust-www](https://github.com/rust-lang/rust-www) (the repository for the [Rust website](https://www.rust-lang.org/)), which has translations for 14 languages, but—crucially—not yet Turkish.

**Comment by cramertj** [comment]
[The book](https://github.com/rust-lang/book/issues?q=is%3Aopen+is%3Aissue+label%3ATranslations) also has a number of open issues regarding translation.

**Comment by nagisa** [comment]
Closing.

As people have already mentioned earlier, help translating the website and the book would be very appreciated. These projects have their own issue trackers and all planning should happen there.
