### ISSUE TITLE
Tracking issue for std::iter::repeat_with

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#48169]
This is the tracking issue for `std::iter::repeat_with`.
Currently in nightly, PR = #48156.

**Comment by Centril** [comment]
@SimonSapin Would stabilizing this be appropriate now?

**Comment by SimonSapin** [comment]
The `iterator_repeat_with` feature covers these APIs in `std::iter`:

```rust
pub fn repeat_with<A, F: FnMut() -> A>(repeater: F) -> RepeatWith<F> { /*…*/ }
pub struct RepeatWith<F> { /*…*/ }
impl<A, F: FnMut() -> A> Iterator for RepeatWith<F> { type Item = A; /* … */ }
impl<A, F: FnMut() -> A> DoubleEndedIterator for RepeatWith<F> { /*…*/ }
impl<A, F: FnMut() -> A> FusedIterator for RepeatWith<F> {}
unsafe impl<A, F: FnMut() -> A> TrustedLen for RepeatWith<F> {}
```

They’ve been in Nightly since February 15 and seem fine to me to stabilize.

@rfcbot fcp merge

**Comment by dtolnay** [comment]
@rfcbot concern DEI

The DoubleEndedIterator impl is somewhat surprising. I see this was brought up in https://github.com/rust-lang/rust/pull/48156#pullrequestreview-95740952 as well. While this has been in nightly has anyone observed use cases that benefit from having the DoubleEndedIterator impl?

**Comment by Centril** [comment]
@dtolnay I haven't; `DEI` for `RepeatWith` doesn't seem useful on its own; and given
`repeat_with(|| ..).zip(my_dei).rev()` you can reorder as `repeat_with(|| ..).zip(my_dei.rev())`. This also applies to `.chain(..)`. However, I think forcing the user to re-order might not be such a good thing from an ergonomics perspective. But... We can always get rid of the DEI impl now and re-add it if anyone asks for it.

**Comment by dtolnay** [comment]
I would accept this without a DoubleEndedIterator impl and then follow up when someone can explain their concrete use case for it.

**Comment by Centril** [comment]
@dtolnay Fair enough, sounds like a plan 👍.

**Comment by dtolnay** [comment]
@rfcbot resolved DEI

**Comment by Kimundi** [comment]
Removing the DEI impl seems like the best course of action, yeah.
