### ISSUE TITLE
Incremental builds occupy a lot of space. (19GB for a small sized project)

### ISSUE THREAD

**Issue by AlexEne** [rust-lang/rust#48172]
I originally posted this on the RLS bug tracker ( https://github.com/rust-lang-nursery/rls/issues/709 ) and it was suggested to open an issue here. 

These builds in the RLS subfolder generate a lot of files that eat up a high amount of disk space for the project I am working on. (19 GB) 
All this in ```target/rls/debug/incremental/```

For a project that's about a few thousand lines of code, it uses around 16GB of disk space. Now I am unsure of what generates this, I use RLS as part of visual studio code.
All the files are generated while I worked on my project today: (11 Feb 2018). Or they were at least modified today.

![rls_disk_space_usage](https://user-images.githubusercontent.com/5849037/36075968-c60683a0-0f4d-11e8-9872-12e1bd16bd69.PNG)

For reference this is the lines of code output for my project (not too big).
![loc](https://user-images.githubusercontent.com/5849037/36076061-5df32910-0f4f-11e8-86a9-e5cc72b21e7e.PNG)

If you want to reproduce the issue, I can give you access to my repo, or we can work something out.

**Comment by sfackler** [comment]
cc @michaelwoerister

**Comment by michaelwoerister** [comment]
For some reason session directory garbage collection seems to be broken here. There should only ever be a couple of those directories starting with `s-`.

As a quick workaround, you can just delete all of these directories while no `rustc` instance is running.

Has anybody observed this on platforms other than Windows?

**Comment by michaelwoerister** [comment]
@nrc, will a `rustc` invocation done by the RLS ever hit this line:
https://github.com/rust-lang/rust/blob/4d2d3fc5dadf894a8ad709a5860a549f2c0b1032/src/librustc_trans/lib.rs#L263

This call seems to in the wrong place anyway, since it is not trans-backend specific. I'll look into moving that to the correct spot.

**Comment by AlexEne** [comment]
Thanks for the help.

**Comment by kjeremy** [comment]
@michaelwoerister yes I see this on Ubuntu 16.04

**Comment by nrc** [comment]
@michaelwoerister we skip trans completely, so I would expect that it won't hit that. I have not verified though.

**Comment by michaelwoerister** [comment]
@nrc, I've taken a look yesterday and `--emit metadata` should also go through LLVM trans, so the RLS should hit the finalization if it compiles everything successfully. When there are errors, it may exit early though. https://github.com/rust-lang/rust/pull/48181 makes sure that we don't rely on successful builds for running the garbage collection. Let's see if that solves the problem.

**Comment by ishitatsuyuki** [comment]
Disagree that this is I-compilemem as this is disk space not RSS.

**Comment by michaelwoerister** [comment]
Do we know if #48181 has fixed this problem. Can somebody check with a nightly version of the RLS?

**Comment by AlexEne** [comment]
Looks fine now. target/debug/rls/incremental folder has just two other folders in it. build_script_build-idand dwarf_game-id. Thanks for fixing this.

**Comment by michaelwoerister** [comment]
Excellent, thanks for confirming, @AlexEne!
