### ISSUE TITLE
use sparse bitsets instead of dense ones for NLL results

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#48170]
As part of https://github.com/rust-lang/rust/issues/47879, it seems clear that using dense bitsets is going to be a problem for NLL sooner or later. We should move to a sparse set. I think that the `BTreeMap` idea sketched in https://github.com/rust-lang/rust/issues/47575 may be a good choice.

The NLL region representation is defined here:

https://github.com/rust-lang/rust/blob/16362c737fe740f630ada06349fa9004e2a51bb7/src/librustc_mir/borrow_check/nll/region_infer/values.rs#L186-L200

In particular, the field `matrix` uses a`BitMatrix`. The "rows" in the matrix are inference variables, and the columns are the [indices defined here](https://github.com/rust-lang/rust/blob/16362c737fe740f630ada06349fa9004e2a51bb7/src/librustc_mir/borrow_check/nll/region_infer/values.rs#L22-L29) (either cfg points or universal regions).

I think we should add a new type `SparseBitMatrix` that offers the same API as `BitMatrix`. It might be represented with a `Vec<SparseSet>`, per #47575, where `SparseSet` is a bit set represented [as sketched in this comment](https://github.com/rust-lang/rust/issues/47575#issuecomment-359016425). Or it might even just use a single `SparseSet` internally, where each bit is indexed by an index `I = (row * num_columns) + column`.

**Comment by nikomatsakis** [comment]
@spastorino indicated that they wanted to give this a try. @eddyb -- is your sparsebitmatrix stuff working out? Is current version on a branch somewhere?

**Comment by eddyb** [comment]
@nikomatsakis I never built a bit matrix out of it, I'm just using the `SparseBitSet` from #47575.
