### ISSUE TITLE
NLL / MIR-borrowck regression in atomic_refcell crate

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#48178]
On `nightly-2018-02-12` b8398d947, https://github.com/bholley/atomic_refcell builds with or without `RUSTFLAGS=-Znll` or `RUSTFLAGS=-Zborrowck=mir`.

On `nightly-2018-02-13` 16362c737, either flag causes the error below.

Commit range: https://github.com/rust-lang/rust/compare/b8398d947...16362c737

```rust
error[E0597]: `*orig.value` does not live long enough
   --> src/lib.rs:309:22
    |
309 |             value: f(orig.value),
    |                      ^^^^^^^^^^ borrowed value does not live long enough
...
312 |     }
    |     - borrowed value only lives until here
    |
    = note: borrowed value must be valid for lifetime '_#3r...
```

Reduced test case:

```rust
pub struct AtomicRefMut<'b, T: ?Sized + 'b> {
    value: &'b mut T,
    borrow: AtomicBorrowRefMut<'b>,
}

struct AtomicBorrowRefMut<'b> {
    borrow: &'b (),
}

impl<'b> Drop for AtomicBorrowRefMut<'b> {
    fn drop(&mut self) {}
}

impl<'b, T: ?Sized> AtomicRefMut<'b, T> {
    pub fn map<U: ?Sized, F>(orig: AtomicRefMut<'b, T>, f: F) -> AtomicRefMut<'b, U>
        where F: FnOnce(&mut T) -> &mut U
    {
        AtomicRefMut {
            value: f(orig.value),
            borrow: orig.borrow,
        }
    }
}
```

CC @nikomatsakis

**Comment by nikomatsakis** [comment]
I believe that this will be addressed by https://github.com/rust-lang/rust/pull/47917

**Comment by nikomatsakis** [comment]
cc @davidtwco -- can you quickly test?

**Comment by davidtwco** [comment]
@nikomatsakis seems to be working fine on #47917.

**Comment by nikomatsakis** [comment]
Working now: 

https://play.rust-lang.org/?gist=189add0e963a75cb406c5fadc3e0190e&version=nightly

Closing since I think that the tests from #47917 suffice.
