### ISSUE TITLE
Tracking issue for RFC #2175: or-patterns in if / while let expressions 

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#48215]
This is a tracking issue for the RFC "or-patterns in if / while let expressions" (rust-lang/rfcs#2175).

**Steps:**

- [ ] Implement the RFC (cc @rust-lang/compiler -- can anyone write up mentoring instructions?)
- [ ] Adjust documentation ([see instructions on forge][doc-guide])
- [ ] Stabilization PR ([see instructions on forge][stabilization-guide])

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Comment by zackmdavis** [comment]
This seems likely to be a rather straightforward change: currently [`parse_arm` calls `parse_pats`](https://github.com/rust-lang/rust/blob/3ec5a99aaa0084d97a9e845b34fdf03d1462c475/src/libsyntax/parse/parser.rs#L3399) to parse the `|`-separated patterns of a `match` arm, whereas [`parse_if_let_expr` just calls `parse_pat`](https://github.com/rust-lang/rust/blob/3ec5a99aaa0084d97a9e845b34fdf03d1462c475/src/libsyntax/parse/parser.rs#L3229).

I'd like to take this.

**Comment by zackmdavis** [comment]
Arguably we should retitle the issue and RFC to make it clear that the ultimately approved proposal [actually](https://github.com/rust-lang/rfcs/pull/2175#issuecomment-360895387) [includes](https://github.com/rust-lang/rfcs/commit/85f8cb04bfea7cd0b1a12cec3a5fb59244ce5512) `let` itself (in addition to `if let` and `while let`).

**Comment by zackmdavis** [comment]
> This seems likely to be a rather straightforward change: currently [...]

Er, this remark was terribly naïve: the change to the _parser_ might be that simple, but then the `IfLet` (_&c._) AST nodes have to hold a vector rather than a single pattern, and much of the code that handles them (_e.g._, HIR lowering) needs to change correspondingly.

**Comment by nikomatsakis** [comment]
@zackmdavis 

> Er, this remark was terribly naïve: the change to the parser might be that simple, but then the IfLet (&c.) AST nodes have to hold a vector rather than a single pattern, and much of the code that handles them (e.g., HIR lowering) needs to change correspondingly.

Sounds about right. but it should still be something that can be done purely in HIR lowering, right? I would think so.

**Comment by zackmdavis** [comment]
> something that can be done purely in HIR lowering, right?

[Visitors](https://github.com/zackmdavis/rust/blob/7618b6b3895f38e52872c98fbde6f37b0bcdb54d/src/libsyntax/visit.rs#L719-L720), [pretty-printing](https://github.com/zackmdavis/rust/blob/7618b6b3895f38e52872c98fbde6f37b0bcdb54d/src/libsyntax/print/pprust.rs#L1812), and [resolution](https://github.com/zackmdavis/rust/blob/7618b6b3895f38e52872c98fbde6f37b0bcdb54d/src/librustc_resolve/lib.rs#L2266-L2268) are also affected.

**Comment by nikomatsakis** [comment]
Sounds about right. I guess what I meant is "after HIR lowering, I wouldn't expect much other code to care"

**Comment by zackmdavis** [comment]
(I was actively working on this today, but would seem to have been pre-empted by #48490.)

**Comment by dtolnay** [comment]
Does optional leading vert need to be supported here for consistency with #44101?

```rust
if let
    | A(x)
    | B(x) = expr
{
    /* ... */
}
```

@mdinger

**Comment by mdinger** [comment]
@dtolnay 

I would argue yes because examining a large number of cases in that fashion would be advantageous over non-prepended verts (assuming you prefer the style). Maintaining consistency with `match` definitely is a benefit.

Additionally, I wouldn't expect many downsides to this. The main ones would be a complexity increase, dislike from people who disapprove of the style, and perhaps macro [particulars](https://github.com/rust-lang/rfcs/pull/1925#issuecomment-326717633) being more complicated.

**Comment by mdinger** [comment]
Also, the RFC grammar should be updated to reflect this change.

**Comment by Centril** [comment]
I concur with @mdinger, the intention of the RFC was to increase uniformity and consistency.

**Comment by Centril** [comment]
@petrochenkov The `let Ok(x) | Err(x) = foo;` part has not been implemented yet, right?

**Comment by petrochenkov** [comment]
@Centril 
No, `|` in `if let` and `while let` is simple desugaring, but `|` in `let` is pretty much equivalent to full https://github.com/rust-lang/rfcs/pull/1882 as I understand it.

>Does optional leading vert need to be supported here for consistency with #44101?

I didn't implement it only because it required an extra flag in AST for feature gating, now leading `|` is stable so it can be added trivially.

**Comment by Centril** [comment]
@petrochenkov So I forgot to say that `|` in `let` is only permitted at the top level with the RFC as written; it does not amount to full rust-lang/rfcs#1882, so the following would still be illegal with this RFC:
```rust
let (None | Some(_), None | Some(_)) = (None, None);
```

**Comment by Centril** [comment]
Update: https://github.com/rust-lang/rfcs/pull/2530 was accepted to extend this RFC to `for` loops and optional leading vert.

**Comment by Centril** [comment]
I'm closing this issue in favor of https://github.com/rust-lang/rust/issues/54883 to track all those changes since https://github.com/rust-lang/rfcs/pull/2535 subsumes RFC 2175.

**Comment by petrochenkov** [comment]
@Centril 
As I said in one of the previous comments, `let Ok(x) | Err(x)` is a complex feature equivalent to full https://github.com/rust-lang/rust/issues/54883, and the leading vert can be added in the stabilization PR or later, it's not a blocker.

My goal is to stabilize this occasionally useful feature now, and not delay its stabilization on larger implementation work required to support its extensions.

**Comment by Centril** [comment]
@petrochenkov being the new kid on the lang team block, I'm unsure as to whether we are OK with stabilizing parts of RFCs or whether we require them to come in units... In particular, @nikomatsakis noted in RFC 2175 that `let Ok(x) | Err(x) = ...` was a requirement to accept 2175... But the team is in agreement to go much further; so I don't know. I will defer to Niko here (or someone who has been in @rust-lang/lang longer than me...).

**Comment by Centril** [comment]
@petrochenkov could you write up a report per https://github.com/rust-lang/rust/issues/48215#issuecomment-435397697 in a new issue? I'll fcp merge that :)
I'd like the stabilization PR to include leading vert at least also.

**Comment by petrochenkov** [comment]
Ok, will do.

**Comment by Centril** [comment]
Proposed in https://github.com/rust-lang/rust/issues/48215.

**Comment by glaebhoerl** [comment]
@Centril You mean #56212 :stuck_out_tongue:

**Comment by Centril** [comment]
@glaebhoerl hihi =P // blames copy buffer
