### ISSUE TITLE
CString Documentation example does not compile

### ISSUE THREAD

**Issue by LivingInSyn** [rust-lang/rust#48218]
This is in regards to this example in the documentation:

https://doc.rust-lang.org/std/ffi/struct.CString.html#examples

Clicking 'Run' on brings you to the rust playground, where it fails to compile. It is missing the function ```my_printer```

Link to playground: [here](https://play.rust-lang.org/?code=%23!%5Ballow(unused)%5D%0Afn%20main()%20%7B%0Ause%20std%3A%3Affi%3A%3ACString%3B%0Ause%20std%3A%3Aos%3A%3Araw%3A%3Ac_char%3B%0A%0Aextern%20%7B%0A%20%20%20%20fn%20my_printer(s%3A%20*const%20c_char)%3B%0A%7D%0A%0A%2F%2F%20We%20are%20certain%20that%20our%20string%20doesn%27t%20have%200%20bytes%20in%20the%20middle%2C%0A%2F%2F%20so%20we%20can%20.unwrap()%0Alet%20c_to_print%20%3D%20CString%3A%3Anew(%22Hello%2C%20world!%22).unwrap()%3B%0Aunsafe%20%7B%0A%20%20%20%20my_printer(c_to_print.as_ptr())%3B%0A%7D%0A%7D%0A)

**Comment by steveklabnik** [comment]
I am not sure why this is not marked `ignore`, but certainly should be! thanks!

**Comment by LivingInSyn** [comment]
This also effects the three examples here:

https://doc.rust-lang.org/std/ffi/struct.CStr.html#examples

Should I file a separate issue?
