### ISSUE TITLE
Re-enable ThinLTO on CI

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#48222]
We previously disabled it on the dist bots, but this is currently untenable due to the length of time they run for. Should be relatively straightforward, we need to remove [this line](https://github.com/rust-lang/rust/blob/master/src/ci/run.sh#L49).

cc @kennytm @alexcrichton

**Comment by kennytm** [comment]
Do we need to reopen #45444 when this issue (#48222) is closed?

**Comment by Mark-Simulacrum** [comment]
I think we'll probably for now just take that perf hit on stable/beta releases but there's been some thought about disabling ThinLTO only for nightly, not stable/beta builds.
