### ISSUE TITLE
Cargo and some dependencies are compiled twice on CI

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#48223]
I noticed on the most recently timed out mipsel dist builder that Cargo, the library, was compiled twice. This is no small chunk of time!

Investigating it looks like a number of libraries were compiled at least twice, including: cargo, chrono, crates-io, docopt, env_logger, failure_derive, failure, num, serde_derive_internals, serde_derive, synstructure.

My guess is that the feature selection is changing for deeply nested crates like `syn` or `num` between top-level targets like the RLS and Cargo. We should make sure that the feature selection is the same so the dependencies can be shared, and then we should probably add a check to CI that Cargo isn't compiled twice.

**Comment by alexcrichton** [comment]
cc @Mark-Simulacrum, @kennytm

**Comment by ishitatsuyuki** [comment]
I think I brought up this before, and as a result you closed the issue at Cargo side.

**Comment by alexcrichton** [comment]
Cargo is working as intended, our CI is not

**Comment by ishitatsuyuki** [comment]
So this is https://github.com/rust-lang/cargo/issues/4048. I think this is definitely a feature worth implement in Cargo.

**Comment by alexcrichton** [comment]
I think this will be fixed with https://github.com/nrc/derive-new/pull/28 and https://github.com/rust-lang/rust/pull/48642

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rust-lang/rust/pull/48642
