### ISSUE TITLE
codegen-units=16 doubles compile times for Firefox

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#48233]
https://bugzilla.mozilla.org/show_bug.cgi?id=1436251

The other day I was experimenting with codegen-units, and realized that Firefox's build gets _really_ slow with codgen-units=16 (the default):

```
with codegen-units=1
real    20m35.218s
user    135m46.044s
sys     5m49.332s

with default codegen-units (16)
real    38m3.751s
user    156m53.384s
sys     6m22.100s
```

I wasn't able to reduce the testcase.

If you wish to do it, use nightly to build Firefox with the following mozconfig file:

```
ac_add_options --enable-debug
ac_add_options --enable-optimize
ac_add_options --enable-release
```

and revert this patch: https://hg.mozilla.org/mozilla-central/rev/fe90c7d53a7c

A useful bit of information may be that we pass `-Clto` only to the toplevel crate, i.e. we build with `cargo rustc -- -Clto`. I don't remember but it might have been only the last crate ("gkrust") taking forever to build (I can retest this if you wish) so it might be some pathological case with LTO.

cc @michaelwoerister

**Comment by matthiaskrgr** [comment]
Sounds like #48025

**Comment by Manishearth** [comment]
cc @alexcrichton does this sound like a dupe of https://github.com/rust-lang/rust/pull/48163 ?

I'm going to test with/without that PR soon.

**Comment by michaelwoerister** [comment]
Depending on what Rust version you are using, it might also be related to https://github.com/rust-lang/rust/issues/48226?

**Comment by michaelwoerister** [comment]
What's the compile time without the `ac_add_options --enable-debug`?

**Comment by Manishearth** [comment]
Will try and report back

**Comment by nikomatsakis** [comment]
Nominating for prioritization and discussion (presuming it's not resolved before then).

**Comment by nikomatsakis** [comment]
triage: P-medium

Marking as P-medium for now until we get some more heat from the FF folks. ;)

**Comment by nikomatsakis** [comment]
In particular, nobody is using CGU=16 yet, right? (But also, it's not entirely obvious to me that it would be desirable, given https://github.com/rust-lang/rust/issues/47745)

**Comment by Manishearth** [comment]
I tried it out again and it seems to be fixed.


CGU=16 is the default, yeah? So everyone is using it.

**Comment by michaelwoerister** [comment]
@Manishearth, I thought that FF is compiled with `codegen-units=4`?

**Comment by Manishearth** [comment]
Release mode uses the default.

**Comment by nikomatsakis** [comment]
Mmmmm, that might bump the priority somewhat. =)

**Comment by michaelwoerister** [comment]
> Release mode uses the default.

Is this with full LTO?

**Comment by Manishearth** [comment]
I'm not sure, eddyb said that LTO turns it off.

However, Firefox builds with LTO turned on only for the last crate.

**Comment by alexcrichton** [comment]
To clarify, rustc is using 16 codegen units by default in all modes, regardless of optimization level, LTO settings, etc. @Manishearth you mention this is fixed now though? If that's the case this was indeed likely fixed by https://github.com/rust-lang/rust/pull/48163

**Comment by Mark-Simulacrum** [comment]
Based on "I tried it out again and it seems to be fixed." from https://github.com/rust-lang/rust/issues/48233#issuecomment-367754651, I'm going to close this issue.
