### ISSUE TITLE
wasm32-unknown-unknown not compatible with --crate-type=lib

### ISSUE THREAD

**Issue by gurghet** [rust-lang/rust#48237]
I tried to run `rustc` on a file without a main and instead of generating a `wasm` file like expected I got an rlib.

The command I tried is
```bash
rustc +nightly --crate-type=lib --target wasm32-unknown-unknown -O hello.rs
```

**Comment by rkruppe** [comment]
This is intended, the `lib` (and `dylib`) crate types are solely for intermediate artifacts consumed by the same Rust compiler that produced them. The `staticlib` and `cdylib` crate types produce artifacts suitable for linking and other uses. I'm not sure if the wasm target supports them (I never used wasm) but `--crate-type=lib` producing an `.rlib` is certainly not a bug.
