### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by mark-summerfield** [rust-lang/rust#48241]
On page
https://www.rust-lang.org/en-US/contribute-libs.html
there's a link (in the second bullet point) to
http://libs.rs/
which doesn't seem to exist.

**Comment by steveklabnik** [comment]
Could you please file this against https://github.com/rust-lang/rust-www? thanks!

**Comment by mark-summerfield** [comment]
I've done an edit in https://github.com/rust-lang/rust-www/pull/1051 by replacing lib.rs with crates.io hope this is okay.
