### ISSUE TITLE
Can we have a bors build that *tests* building outside the rust root dir?

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#48269]
Supposedly we support bootstrapping rust from directories other than the root of the rust.git checkout.

At least, in the past we have *rejected* PR's based on the desirability for such support. See for example: https://github.com/rust-lang/rust/pull/42689#issuecomment-308899120

But bugs like #48268 nonetheless creep through.

I assert that if we had just *one* autobuild instance, on our fastest platform (linux?), that tested this scenario, then we could keep developers like me happy (as well as a number of other developers; I'll gather a list if I have to)

**Comment by Mark-Simulacrum** [comment]
This should effectively be done so long as we don't remove this commit: https://github.com/rust-lang/rust/pull/48252/commits/e78ecd2e70961e64040598a019febec44959f7dd. Most of our docker images (i.e., Travis) build out of tree in `obj` dir anyway so they all test building outside root dir. However, only a few pass paths to x.py invocations. Those should test this; I'm going to close as such.

I'm hoping to come up with a better approach to testing rustbuild soon, which will then include something for this too directly in rustbuild. However, for now, I think we can close this as fixed.
