### ISSUE TITLE
rustdoc doc for deprecated doesn't contain hint about what use instead

### ISSUE THREAD

**Issue by Dushistov** [rust-lang/rust#48271]
Look for example to [bindgen hide_type method](https://docs.rs/bindgen/0.33.1/bindgen/struct.Builder.html#method.hide_type)

It is deprecated, and in source code there is hint what should be used instead:

```Rust
/// Hide the given type from the generated bindings. Regular expressions are
    /// supported.
    #[deprecated = "Use blacklist_type instead"]
    pub fn hide_type<T: AsRef<str>>(self, arg: T) -> Builder {
        self.blacklist_type(arg)
    }
```

but in generated html documentation there is no hint about `Use blacklist_type instead`

**Comment by ollie27** [comment]
`#[deprecated = "Use blacklist_type instead"]` isn't the correct syntax for the `#[deprecated]` attribute. It should be `#[deprecated(note = "Use blacklist_type instead")]`. You can see it work: [unstable_rust](https://docs.rs/bindgen/0.33.1/bindgen/struct.Builder.html#method.unstable_rust) [src](https://docs.rs/bindgen/0.33.1/src/bindgen/lib.rs.html#1022).

This isn't a rustdoc issue. It's an issue with rustc that it doesn't reject `#[deprecated = "Use blacklist_type instead"]`.
