### ISSUE TITLE
It should be possible to dereference NonNull in unsafe blocks

### ISSUE THREAD

**Issue by joshlf** [rust-lang/rust#48277]
In porting some code from `*mut T` to `NonNull<T>`, I've been having to add a lot of `.as_ptr()` conversions in order to dereference (i.e., `*ptr` vs `*ptr.as_ptr()`). It'd be great it were possible to dereference `NonNull` directly when in unsafe blocks.

My guess is that this would require adding some sort of `UnsafeDeref`/`UnsafeDerefMut` traits and making the compiler know about them, so this is probably no simple task.

**Comment by Lokathor** [comment]
Absolutely, and raw pointers should also get the benefits of a Deref-like trait with deref-coercion magic. If you're already in an unsafe block you already accepted the risks.

**Comment by Lokathor** [comment]
I actually posted in that RFC, but here is good too if that gets things implemented and usable faster to do just this one small trait compared to the whole system that would be that rfc

**Comment by steveklabnik** [comment]
Triage: 

> My guess is that this would require adding some sort of UnsafeDeref/UnsafeDerefMut traits and making the compiler know about them, so this is probably no simple task.

Yep, and that puts this in RFC territory, so let's close this.

n.b.: I know that @withoutboats has also wished for more ergonomics around `NonNull`, and unsafe code in general, but would prefer to work on it in a holistic fashion.
