### ISSUE TITLE
Add Option::unwrap_unchecked

### ISSUE THREAD

**Issue by joshlf** [rust-lang/rust#48278]
Now that `NonNull` has been added and `Option<NonNull<T>>` is preferred over `*mut T`, if you have code that used to know that a `*mut T` was non-null and dereferenced it, you now know that your `Option<NonNull<T>>` is `Some` and can call `.unwrap()` on it. However, `.unwrap()` can incur runtime overhead that dereferencing `*mut T` never would. Since a lot of performance-critical code is written using raw pointers (and now, `NonNull`), this runtime overhead may be worth worrying about.

I propose, for these cases, to introduce an unsafe `unwrap_unchecked` method to `Option` that returns a `T` by simply assuming that the `Option` is currently `Some(T)`.

**Comment by kennytm** [comment]
There is already a package providing this function. https://crates.io/crates/unsafe_unwrap

**Comment by joshlf** [comment]
Ah good to know. I still think it could be useful in the stdlib, but it's definitely less of a concern with that crate.

**Comment by superriva** [comment]
My compare of default unwrap() and unsafe_unwrap():

```
$ git clone https://github.com/nvzqz/unsafe-unwrap-rs.git
$ cd unsafe-unwrap-rs
$ cargo build
$ cargo bench
```
The bench output:
```
test benches::bench_normal_unwrap_1000 ... bench:       2,112 ns/iter (+/- 709)
test benches::bench_unsafe_unwrap_1000 ... bench:         814 ns/iter (+/- 89)
```

Code compare:
```
// default unwrap()
impl<T> Option<T> {
    pub fn unwrap(self) -> T {
        match self {
            Some(val) => val,
            None => panic!("called `Option::unwrap()` on a `None` value"),
        }
  
    }
}
```
```
// unsafe_unwrap()
impl<T> UnsafeUnwrap<T> for Option<T> {
    #[inline]
    unsafe fn unsafe_unwrap(self) -> T {
     if let Some(x) = self { x } else { unreachable() }
    }
}
```
I tried to change code of unsafe_unwrap():
```
impl<T> UnsafeUnwrap<T> for Option<T> {
    #[inline]
    unsafe fn unsafe_unwrap(self) -> T {
     //if let Some(x) = self { x } else { unreachable() }
     if let Some(x) = self { x } else { panic!("PANIC") }
    }
}
```
New bench output:
```
test benches::bench_normal_unwrap_1000 ... bench:       2,111 ns/iter (+/- 56)
test benches::bench_unsafe_unwrap_1000 ... bench:       2,110 ns/iter (+/- 13)
```
So, panic! macro slows down default unwrap() in ~2.5 times!

**Comment by ojeda** [comment]
Available in nightly now. For `Result` too.
