### ISSUE TITLE
Invalid memory layout when switching from 1.23 to 1.24

### ISSUE THREAD

**Issue by baskerville** [rust-lang/rust#48280]
I've stumbled upon this issue while trying to run [Plato](https://github.com/baskerville/plato)'s *emulator* binary after having updated from 1.23 to 1.24.

- Running `cargo run --bin plato-emulator --features emulator` under 1.24 leads to undefined behavior because (see `src/font.rs`) the `face` attribute of a `Font`, a raw pointer to an `FtFace` structure  is filled with absurd values, for example, the `width` and `height` fields of the `(*(*face).glyph).metrics` structure look like pointers. A segmentation fault can be triggered just by printing `*(*face).glyph`.
- The same command runs smoothly under 1.23.

This seems puzzling to me, since the bindings and the *freetype* library (2.9) are the same in both cases.

The OS used is *macOS 10.12.6*.

If you want to reproduce you'll need to build the library in `src/wrapper`. The other required libraries are *djvulibre*, *mupdf*, *freetype*, *harfbuzz* and *sdl2*.

**Comment by est31** [comment]
@baskerville do you have a minimal example of the bug? Are you sure you aren't invoking UB?

**Comment by baskerville** [comment]
I was able to strip it down: [plato.zip](https://github.com/rust-lang/rust/files/1733563/plato.zip).


- `cargo +1.23.0 run` yields `25`.
- `cargo +nightly run` yields a *random* `u32`.

The only required libraries are *freetype2* 2.9 and *harfbuzz* 1.7.4.

**Comment by nagisa** [comment]
The FtGlyphSlot is not layout compatible with ft_glyphslot.

Namely, it looks like this:

```
#[repr(C)]
struct FtGlyphSlot {
    library: *mut FtLibrary,
    face: *mut FtFace,
    next: *mut FtGlyphSlot,
    reserved: libc::c_uint,
    generic: FtGeneric,

    metrics: FtGlyphMetrics,
    linear_hori_advance: FtFixed,
    linear_vert_advance: FtFixed,
    advance: FtVector,

    format: FtGlyphFormat,

    bitmap: FtBitmap,
    bitmap_left: libc::c_int,
    bitmap_top: libc::c_int,

    outline: FtOutline,

    num_subglyphs: libc::c_uint,
    subglyphs: FtSubGlyph,

    control_data: *mut libc::c_void,
    control_len: libc::c_long,

    lsb_delta: FtPos,
    rsb_delta: FtPos,

    other: *mut libc::c_void,

    internal: *mut FtSlotInternal,
}
```

and

```
enum FtSubGlyph {}
```

Note that the `subglyphs` field uses the empty `repr(Rust)` enum with unspecified layout by-value, which essentially invalidates any reliance on the layout of `FtGlyphSlot`.

Furthermore, `FtGlyphSlot::subglyphs` is a pointer, but in your Rust code it is not.

Changing the field to be a proper pointer makes code print `25`, which seems to be the expected value. Closing.
