### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by dbucci24** [rust-lang/rust#48289]
Hello, I would like to collaborate with the Spanish translation, is it already done or is it still missing?

**Comment by nagisa** [comment]
This is the repository for the Rust compiler, which does not have any strings to translate at the moment.

You may want to look at contributing to the [spanish translation of the website](https://github.com/rust-lang/rust-www/tree/master/es-ES), which seems to be incomplete still, or the [book](https://github.com/rust-lang/book/issues/661) (not sure if the translation of the book is complete, do ask on the linked issue).
