### ISSUE TITLE
Add non-panicking variants of pow for Integers

### ISSUE THREAD

**Issue by milesand** [rust-lang/rust#48291]
std (and core) does not include non-panicking variants of `pow`. As we already have such variants of other possibly-overflowing operations in the std, it may be a good idea to add such functionality for symmetry.

**Comment by sfackler** [comment]
It seems reasonable to take a PR adding `checked_pow`!

**Comment by frewsxcv** [comment]
relevant issue and pr:

* https://github.com/rust-lang/rust/issues/48320
* https://github.com/rust-lang/rust/pull/48321
