### ISSUE TITLE
concat constant println!() args at compiletime

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#48299]
Just an idea.
For
````rust
pub fn printtest() {
    println!("hello world");
}
````
we get
````asm
_ZN7example9printtest17h5d89ebc14efc990fE:
  push rbp
  mov rbp, rsp
  sub rsp, 48
  lea rax, [rip + .Lref.1]
  mov qword ptr [rbp - 48], rax
  mov qword ptr [rbp - 40], 1
  mov qword ptr [rbp - 32], 0
  lea rax, [rip + .Lref.2]
  mov qword ptr [rbp - 16], rax
  mov qword ptr [rbp - 8], 0
  lea rdi, [rbp - 48]
  call _ZN3std2io5stdio6_print17h0853ad73ee6dca9dE@PLT
  add rsp, 48
  pop rbp
  ret

str.0:
  .ascii "hello world\n"

.Lref.1:
  .quad str.0
  .quad 12

.Lref.2:
````

But for
````rust
pub fn printtest()  {
    println!("hello {}", "world");
}
````
we get
````asm
<&'a T as core::fmt::Display>::fmt:
  push rbp
  mov rbp, rsp
  mov rax, rsi
  mov rcx, qword ptr [rdi]
  mov rsi, qword ptr [rdi + 8]
  mov rdi, rcx
  mov rdx, rax
  pop rbp
  jmp <str as core::fmt::Display>::fmt@PLT

example::printtest:
  push rbp
  mov rbp, rsp
  sub rsp, 64
  lea rax, [rip + <&'a T as core::fmt::Display>::fmt]
  movq xmm0, rax
  lea rax, [rip + .Lref.4]
  movq xmm1, rax
  punpcklqdq xmm1, xmm0
  movdqa xmmword ptr [rbp - 64], xmm1
  lea rax, [rip + .Lref.2]
  mov qword ptr [rbp - 48], rax
  mov qword ptr [rbp - 40], 2
  lea rax, [rip + .Lref.5]
  mov qword ptr [rbp - 32], rax
  mov qword ptr [rbp - 24], 1
  lea rax, [rbp - 64]
  mov qword ptr [rbp - 16], rax
  mov qword ptr [rbp - 8], 1
  lea rdi, [rbp - 48]
  call std::io::stdio::_print@PLT
  add rsp, 64
  pop rbp
  ret

str.0:
  .ascii "hello "

str.1:
  .byte 10

.Lref.2:
  .quad str.0
  .quad 6
  .quad str.1
  .quad 1

str.3:
  .ascii "world"

.Lref.4:
  .quad str.3
  .quad 5

.Lref.5:
  .quad 1
  .quad 0
  .quad 3
  .zero 8
  .quad 3
  .zero 8
  .long 32
  .long 0
  .byte 3
  .zero 7
````
Don't they do the same essentially?
Maybe this is something miri will be able to solve?
EDIT: godbolt link: https://godbolt.org/g/UhfqUb

**Comment by sanmai-NL** [comment]
What will be cost-benefit ratio of optimizing for such code?

**Comment by nagisa** [comment]
This is not something that can be optimised at the time of macro expansion, because any particular implementation of `<str as core::fmt::Display>::fmt` must not be assumed. This is something that both miri and LLVM should be able to evaluate, but to LLVM this is not visible, because the implementation of `<str as core::fmt::Display>::fmt` only comes in at a linking time.

**Comment by abonander** [comment]
@nagisa If I'm reading this correctly, this would be an implementation change to `format_args!()` that would interpolate literals directly into the format string. It's definitely feasible.

**Comment by nagisa** [comment]
Rust *must* not assume any particular implementation of <str as
Display>::fmt. no_core crates – something that is likely to become stable
at some point – might want to implement this function some other way and it
would make for an observable difference in behaviour between compile-time
and runtime contexts. The minimum you would need to implement such change
would be an RFC mandating a particular output format for certain types, and
this is extremely weak motivation for such a heavy handed change.

**Comment by jonas-schievink** [comment]
This is almost certainly not going to be worth it – the only cases that could be optimized in the `format_args!` macro (while assuming specific implementations in libcore) use literals as formatting arguments, which is useless unless you're just testing out something, in which case it doesn't need to be fast.

As such, closing this issue.
