### ISSUE TITLE
`rustc` output hygiene wrt. stderr/stdout

### ISSUE THREAD

**Issue by sanmai-NL** [rust-lang/rust#48301]
`rustc` sometimes emits exclusively human-readable output on stdout. Moreover, it sometimes produces machine-readable output on stderr. It should be the other way around, and at least output writing should be principled.

When compiling a bin target `helloworld`:

On stdout:
```
bin: helloworld
```
This would interfere in parsing JSON messages (`--error-format json`), for example from Clippy. If only they weren’t mistakenly written on stderr, too ... It seems very simple to fix such little slip-ups, but I couldn’t track down the offending code for this instance.

Another sample of the same issue, from a different angle:
```sh
rustc --error-format json
```

Prints on std*err*:
```
{"message":"no input filename given","code":null,"level":"error","spans":[],"children":[],"rendered":"error: no input filename given\n\n"}
```

I propose, first, that we decide to guarantee that all JSON will ever be printed on stdout exclusively, and all the rest on stderr exclusively. Second, to implement this by making the appropriate fixes across `rustc`, Cargo and Clippy.

# Meta

rustc 1.25.0-nightly (3ec5a99aa 2018-02-14)

Related #36516

**Comment by Enselic** [comment]
Triage: Can you provide step by step instructions on how to get `bin: helloworld` on stdout please? I can't reproduce. This gives me nothing on stdout (except from the compiled program being run):
```console
$ echo 'fn main() { println!("hi"); }' | rustc +nightly -o main - && ./main
hi
```

**Comment by sanmai-NL** [comment]
Maybe it was `cargo build` output.

**Comment by Enselic** [comment]
Thank you for getting back to me.

In that case this issue should be reported against [cargo](https://github.com/rust-lang/cargo/issues) instead of here I think?

**Comment by Enselic** [comment]
Triage: Assuming yes, so let's close.
