### ISSUE TITLE
Strengthen/clarify "It is an error to..." wording

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#48311]
* [`UdpSocket::set_read_timeout`](https://doc.rust-lang.org/std/net/struct.UdpSocket.html#method.set_read_timeout)
* [`UdpSocket::set_write_timeout`](https://doc.rust-lang.org/std/net/struct.UdpSocket.html#method.set_write_timeout)
* [`TcpStream::connect_timeout`](https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.connect_timeout)
* [`TcpStream::set_read_timeout`](https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.set_read_timeout)
* [`TcpStream::set_write_timeout`](https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.set_write_timeout)
* [`UnixDatagram::set_read_timeout`](https://doc.rust-lang.org/std/os/unix/net/struct.UnixDatagram.html#method.set_read_timeout)
* [`UnixDatagram::set_write_timeout`](https://doc.rust-lang.org/std/os/unix/net/struct.UnixDatagram.html#method.set_write_timeout)
* [`UnixStream::set_read_timeout`](https://doc.rust-lang.org/std/os/unix/net/struct.UnixStream.html#method.set_read_timeout)
* [`UnixStream::set_write_timeout`](https://doc.rust-lang.org/std/os/unix/net/struct.UnixStream.html#method.set_write_timeout)

For all of the APIs above, the docs have a line with this wording:

> It is an error to pass the zero `Duration` to this method.

My initial thought is, what does "it is an error" mean? Does this mean the API will panic if `Some(Duration::from_secs(0))` is passed or will it just return an `Err`? The answer appears to be the latter.

Also since it's the latter, and we _don't_ have an explicit check for `Duration(0)` in our codebase, it means we're _relying_ on the behavior being the same across all platforms. Is this alright? Should/can we add an explicit check for `Duration(0)`? Should we add a test ensuring this is the behavior across all platforms?

Maybe I'm overthinking this...

**Comment by sfackler** [comment]
We do have an explicit check:

https://github.com/rust-lang/rust/blob/ff2a7c85757542f454934e00605355bbca7bc196/src/libstd/sys/unix/net.rs#L282-L285

https://github.com/rust-lang/rust/blob/ff2a7c85757542f454934e00605355bbca7bc196/src/libstd/sys/windows/net.rs#L261-L264

**Comment by frewsxcv** [comment]
@sfackler ah, i didn't see those. i just checked redox and it looks like [it doesn't have that conditional](https://github.com/rust-lang/rust/blob/1ad094d81c97b3d2dd8e980ccd1475a80647540d/src/libstd/sys/redox/net/tcp.rs#L130). seems like this is prone to happen again in the future, unless we had:

* an integration test suite for `std::net` things such that we could assert that an `Err` is returned in this scenario
* the conditionals were moved into the body of the top-level entry point of these APIs instead of the platform specific ones

**Comment by sfackler** [comment]
Yeah it seems reasonable to have tests to check for that error case.

**Comment by frewsxcv** [comment]
@sfackler for `TcpStream::set_read_timeout` for example, do you know if we have a way to test this method in our test suite? seems like it would require `TcpStream::connect` to be called, which seems like it would require a TCP listener running

**Comment by sfackler** [comment]
I'd just spawn off a listener in a background thread:

```rust
let listener = TcpListener::bind("127.0.0.1:0").unwrap();
let addr = listener.local_addr().unwrap();

thread::spawn(move || {
    for _ in listener.incoming() {}
});

let socket = TcpStream::connect(addr).unwrap();
match socket.set_read_timeout(Some(Duration::from_secs(0))) {
    Err(ref e) if e.kind() == io::ErrorKind::InvalidInput => {}
    _ => panic!("expected error"),
}
```

**Comment by frewsxcv** [comment]
This is done, as of https://github.com/rust-lang/rust/pull/48328 and https://github.com/rust-lang/rust/pull/48330
