### ISSUE TITLE
Trait method comments gets unescaped by pulldown rustdoc

### ISSUE THREAD

**Issue by Ogeon** [rust-lang/rust#48332]
It seems like documentation comments on trait methods get unescaped when they are shown as implemented traits. Something like `a\*b\*c\*` shows up as a\*b\*c\* in the trait documentation, but as a*b*c* when looking at a type that implements the trait. Adding double escapes makes it look bad on the trait page instead, and replacing `*` with `&#42;` doesn't help, since it gets reinterpreted as `*` anyway.

**Comment by Mark-Simulacrum** [comment]
This is not fixed, can be reproduced with this source, where the trait method on the struct's page will render incorrectly:

<img width="237" alt="image" src="https://user-images.githubusercontent.com/5047365/40887802-4c20a622-670b-11e8-98bd-85923cf77c5c.png">


```rust
pub trait Foo {
    /// Words a\*b\*c\* words
    fn foo() {
    }
}

pub struct A;

impl Foo for A {
}

fn main() {}
```
