### ISSUE TITLE
rustc/cargo should error out in a more useful way when there is nothing exported for a cdylib

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#48334]
I was testing the creation of a no-std dynamic library with cargo/rust, and that ended up failing with the cryptic:

```
error: linking with `cc` failed: exit code: 1
(...)
  = note: /usr/bin/ld:/tmp/rustc.UB8UtN8eI08q/list:4: syntax error in VERSION script
          collect2: error: ld returned 1 exit status
```

The error being about a temporary file that's long gone, that's not really easy to debug. strace was instructive, though:

```
write(3, "{\n  global:\n\n  local:\n    *;\n};\n", 32) = 32
```

is what was written to that file, and that was related to the fact that, since I started from an empty crate, I hadn't added any exported/public function yet. This doesn't fail in the non-no-std case because in that case, this is what is written out by the compiler:

```
write(3, "{\n  global:\n    rust_eh_personality;\n\n  local:\n    *;\n};\n", 57) = 57
```

Maybe `GccLinker::export_symbols` should error out with a nicer message if it has no exported symbols to write (since the cdylib will be useless anyways).

**Comment by retep998** [comment]
Technically a `cdylib` isn't useless without exported symbols, at least on certain platforms like Windows where `DllMain` can still execute code at certain times despite not being an exported function.

**Comment by nagisa** [comment]
Simple reproducer (compile with `rustc test.rs --crate-type=cdylib -Cpanic=abort`):

```rust
#![no_std]
#![crate_type="rlib"]

pub fn foo(x: &[u8; 255], y: u8) -> &[u8] {
    &x[..y as usize]
}

#[panic_handler]
fn on_panic_loop(_unused: &core::panic::PanicInfo) -> ! {
    loop {}
}  
```

**Comment by bjorn3** [comment]
The reproducer is now fixed. Rustc emits the following valid linker script:

```
{

  local:
    *;
};
```
