### ISSUE TITLE
fs::FileType and Metadata should document that is_file, is_dir, and is_symlink are mutually exclusive.

### ISSUE THREAD

**Issue by ExpHP** [rust-lang/rust#48345]
`fs::FileType` should document that `is_file()`, `is_dir()`, and `is_symlink()` are all mutually exclusive. (and that it may also be the case that none of them are true)

Why? Because `Path::is_file()` returns true for both files and symlinks to files, and this tends to make me paranoid that a `fs::FileType` will share similar characteristics and perhaps claim that both `x.is_file()` and `x.is_symlink()`.  The only way to convince myself that FileType's behavior is indeed sane is to write a little test program---*again.*

Surely I can't be alone in this.

**Comment by retep998** [comment]
`Path::is_file()` is calling `stat` not `lstat` (and equivalent on Windows), so if the path is a symlink, then it returns the results based on what the symlink points to, not the symlink itself. So `Path::is_file()` respects the same mutual exclusivity rules as `fs::FileType`.

**Comment by ExpHP** [comment]
Similar goes for `Metadata::{is_file,is_dir}`, which should document that these are always false for a `Metadata` obtained by calling `symlink_metadata` on a symlink.

**Comment by retep998** [comment]
Well you can always call `symlink_metadata` on something that is *not* a symlink, in which case `is_file` or `is_dir` could be true.
