### ISSUE TITLE
llvm test failing

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#48367]
What I did:
````bash
cd src/llvm
mkdir tests
cd tests
cmake ..
make check -j 4
````

What I got:
````
[100%] Running the LLVM regression tests
FAIL: LLVM-Unit :: Analysis/./AnalysisTests/TargetLibraryInfoTest.ValidProto (1062 of 23293)
******************** TEST 'LLVM-Unit :: Analysis/./AnalysisTests/TargetLibraryInfoTest.ValidProto' FAILED ********************
Note: Google Test filter = TargetLibraryInfoTest.ValidProto
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from TargetLibraryInfoTest
[ RUN      ] TargetLibraryInfoTest.ValidProto
/home/matthias/RUST/rust/src/llvm/unittests/Analysis/TargetLibraryInfoTest.cpp:529: Failure
Value of: isLibFunc(F, LF)
  Actual: false (__rust_alloc not found)
Expected: true
/home/matthias/RUST/rust/src/llvm/unittests/Analysis/TargetLibraryInfoTest.cpp:529: Failure
Value of: isLibFunc(F, LF)
  Actual: false (__rust_dealloc not found)
Expected: true
/home/matthias/RUST/rust/src/llvm/unittests/Analysis/TargetLibraryInfoTest.cpp:529: Failure
Value of: isLibFunc(F, LF)
  Actual: false (__rust_realloc not found)
Expected: true
[  FAILED  ] TargetLibraryInfoTest.ValidProto (16 ms)
[----------] 1 test from TargetLibraryInfoTest (16 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (16 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] TargetLibraryInfoTest.ValidProto

 1 FAILED TEST

********************
Testing Time: 1013.59s
********************
Failing Tests (1):
    LLVM-Unit :: Analysis/./AnalysisTests/TargetLibraryInfoTest.ValidProto

  Expected Passes    : 22601
  Expected Failures  : 145
  Unsupported Tests  : 546
  Unexpected Failures: 1
````
How bad is this?

LLVM repo  @ 9f81beaf32608fbe1fe0f2a82f974e800e9d8c62

**Comment by rkruppe** [comment]
Probably not bad. It seems to indicate https://github.com/rust-lang/llvm/commit/a782b9eb28ce0e433f6048239cbe8ebaa478ec3e messed up somehow but at worst that should result in some lost optimizations. Still worth checking out, cc @nagisa

**Comment by nagisa** [comment]
We have a test in-tree that ensures we trigger the optimisation with our allocation functions.

The test seems to be checking stuff against some hard-coded list of function names. I strongly suspect that adding the signatures for the rust allocation functions to the test would fix it.

**Comment by nagisa** [comment]
Namely [this](https://github.com/rust-lang/rust/blob/master/src/test/codegen/alloc-optimisation.rs).

**Comment by nagisa** [comment]
Adding the prototype for `__rust_alloc` to the test makes it not fail on `__rust_alloc` anymore. Since it is just a test failure for LLVM, I don’t think it matters enough to care enough about it.

Feel free to reopen if you feel differently.

**Comment by nagisa** [comment]
Note, I don’t believe we should bother adjusting the test either, given that the addition of rust-specific allocation symbols is likely to be one of those eternally-backported patches and making it harder to backport would impede LLVM upgrades.
