### ISSUE TITLE
The signature of Path::strip_prefix is bizarrely overconstrained

### ISSUE THREAD

**Issue by ExpHP** [rust-lang/rust#48390]
```rust
pub fn strip_prefix<'a, P: ?Sized>(
    &'a self, 
    base: &'a P  // <===  ???  a reference?
) -> Result<&'a Path, StripPrefixError> 
where P: AsRef<Path>, 
```

This can clearly be generalized to

```rust
pub fn strip_prefix<'a, P>(
    &'a self, 
    base: P
) -> Result<&'a Path, StripPrefixError> 
where P: AsRef<Path>, 
```

[Implementation.](https://github.com/rust-lang/rust/compare/rust-lang:27a046e...ExpHP:path-prefix)

(**Note:** Like many similar attempts to "generalize" function signatures, this is a potentially breaking change due to potential regressions in type inference)

**Comment by vitalyd** [comment]
This would be a breaking change since you can’t pass `?Sized` types anymore (and that’s likely the reason for having it a reference to begin with).  It’s debatable whether such impls exist for this case, but that would need to be answered first before considering this change IMO.

**Comment by ExpHP** [comment]
@vitalyd:  You've said a similar thing [before on users](https://users.rust-lang.org/t/std-io-read-pass-by-reference-or-not/13859), but I still don't see the argument.  

Looking back at the thread now I see you responded to my request for clarification:

> **vitalyd** [wrote](https://users.rust-lang.org/t/std-io-read-pass-by-reference-or-not/13859/10):
> The contrived example is if some code you don’t control gives you an `R: Read + ?Sized` based `&mut R` - say that’s all you have when they call into your code. Whether they should arrange things differently is a different question. But as I mentioned, that’s pretty contrived. Your assumption (fairly valid but not required) is that you’re starting with a place where you can form a `&mut R` yourself and pass that to a `fn<R: Read>(r: R)`.

But even with this clarification I cannot see the issue. It seems to me [I can call an `<R: Read>` function just fine](https://play.rust-lang.org/?gist=0a2c057ad8cacd54a16838fa37ef37de&version=stable) with a `&mut R where R: Read + ?Sized`.

```rust
fn foo<R: Read>(r: R) { }

fn bar<R: Read + ?Sized>(r: &mut R) { foo(r) }  // ok
```

**Comment by ExpHP** [comment]
Okay.  Wait.  I see *something*.  It's an insanely subtle distinction, but it's there:

**Only the `&mut R` form will implicitly reborrow.**

```
fn foo1<R: Read + ?Sized>(r: &mut R) { }
fn foo2<R: Read>(r: R) { }

fn bar<R: Read + ?Sized>(r: &mut R) { foo1(r); foo1(r); } // okay
fn bar<R: Read + ?Sized>(r: &mut R) { foo2(r); foo2(r); } // Error: `r` was moved
```

...but this doesn't apply to `strip_prefix`, which takes an immutable borrow.

**Comment by vitalyd** [comment]
Right - for the `Read` conversation in that thread, reborrowing would be one concern (this nicety doesn't apply in a fully generic context).

Thinking about the `strip_prefix` case a bit more, I'm failing to come up with anything that will break.  It _seems_ like removing `?Sized` could break some weird concoction, but I can't actually think of anything after all.  The thing that would spook me though, as we've touched on in the forum, is type inference gone bad.  Not sure about that one though.
