### ISSUE TITLE
unterminated raw string error should explain the raw-string format a bit

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#48395]
[Playground](https://play.rust-lang.org/?gist=26ef35bce10415e1b6a1cbb61bf9ee97&version=undefined):

```rust
fn foo(s: &str) { println!("{}", s) }
fn main() {
    foo(r#"
This is a raw string  
missing a # at the end
"
    );
}
```

produces

```shell
error: unterminated raw string
 --> src/main.rs:4:9
  |
4 |       foo(r#"
  |  _________^
5 | | This is a raw string  
6 | | missing a # at the end
7 | | "
8 | |     );
9 | | }
  | |_^

error: aborting due to previous error
```

that only mentions "unterminated raw-string". It would be more helpful if it would suggest adding a `#` after the last `"` to terminate the raw string.

**Comment by oli-obk** [comment]
How would one detect where the raw string ends? It might contain random `"` on the inside.

**Comment by gnzlbg** [comment]
> How would one detect where the raw string ends?

No idea, and good question. While suggesting exactly where to add `#` would be awesome, it would already be an improvement to add:

```shell
note: raw string must be terminated with a #:
#"  <--- raw string starts here
...
"#  <--- raw string ends here
```
