### ISSUE TITLE
Remove '&' mark!

### ISSUE THREAD

**Issue by navid9675** [rust-lang/rust#48398]
It could be much better and more readable (I guess!)  if you guys could remove '&' to indicate reference and use 'ref' or something more readable and easier to understand instead.

I have to apologize for my poor English; and I hope I could have delivered my intention.
Thanks.

**Comment by steveklabnik** [comment]
Hey @navid9675 ! Your english is fine.

We cannot make this kind of change, as it breaks backwards compatibility.
