### ISSUE TITLE
CONTRIBUTING.md should not recommend opening issues for feature requests in the RFC repo.

### ISSUE THREAD

**Issue by ordovicia** [rust-lang/rust#48393]
[`CONTRIBUTING.md`](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#feature-requests) currently recommends opening issues for feature requests in the RFC repo.

> Feature Requests
>
> To request a change to the way that the Rust language works, please open an issue in the RFCs repository rather than this one. New features and other significant language changes must go through the RFC process.

But [feature requests should be discussed in the internal forum, not in the issue tracker of the RFC repo](rust-lang/rfcs#2299).
So the `CONTRIBUTING.md` should be amended to guide contributors properly.

**Comment by klnusbaum** [comment]
I'll take a stab at this.

**Comment by Baelyk** [comment]
Hey @aturon, I noticed that you were the one who approved the PR so I thought I should mention you rather than just commenting (hope thats okay), but shouldn't this issue now be closed?
