### ISSUE TITLE
ICE involving box syntax for functions returning `never`

### ISSUE THREAD

**Issue by Ameobea** [rust-lang/rust#48408]
I've been encountering some compiler crashes involving the `box_syntax` feature.  I've come across a few different instances of this, but here's the most minimal version I can get it down to:

```rs
#![feature(box_syntax)]

fn main() {
    let _: Box<Fn(usize)> = box panic!();
}
```

I've stepped back through old nightly versions using `rustup`, and the earliest version that I can get it to run on is `nightly-2017-11-20`.

Here's the debug output from the compiler when the issue occurs:  https://ameo.link/u/bin/54g

**Comment by memoryruins** [comment]
No longer triggers an ICE; continues to cause a LLVM error on ``rustc 1.31.0-nightly (f99911a4a 2018-10-23)``
```rust
   Compiling playground v0.0.1 (/playground)
warning: unreachable expression
 --> src/main.rs:4:29
  |
4 |     let _: Box<Fn(usize)> = box panic!();
  |                             ^^^^^^^^^^^^
  |
  = note: #[warn(unreachable_code)] on by default

AddrSpaceCast result must be a pointer
  %4 = addrspacecast i8* %3 to { {}*, [3 x i64]* }, !dbg !915
LLVM ERROR: Broken function found, compilation aborted!
error: Could not compile `playground`.
```

**Comment by Ameobea** [comment]
`box_syntax` has been removed, and this doesn't occur when using `Box::new()`
