### ISSUE TITLE
Rustc build doesn't pass RUSTFLAGS "-L native=/path" to linker commands with -lffi

### ISSUE THREAD

**Issue by apaprocki** [rust-lang/rust#48409]
*Carried over from rust-lang/cargo#4452 per @alexcrichton*

I have `libffi` in a non-standard location. I set `RUSTFLAGS` to contain `-L native=/path` when building `rustc` itself. Cargo passes this `-L` path when compiling individual objects, but does not pass the `-L` path when attempting to link anything that also gets `-lffi` on the linker command line. The end result is that the link fails because `-lffi` can't be found.

**edit**: I worked around this by making a wrapper to `gcc` that passes the `-L` rule and passing it as the `--default-linker` option.

Example breakage, when `RUSTFLAGS` has `-L native=/path`:

> Build failed, waiting for other jobs to finish...
> error: Could not compile `pulldown-cmark`.
> 
> Caused by:
>   process didn't exit successfully: `/dev/shm/rustc-1.19.0-src/build/bootstrap/debug/rustc --crate-name build_script_build /dev/shm/rust-1.19/debian/cargo_home/registry/src/github.com-1ecc6299db9ec823/pulldown-cmark-0.0.14/build.rs --error-format json --crate-type bin --emit=dep-info,link -C opt-level=2 -C metadata=94247588bee65632 -C extra-filename=-94247588bee65632 --out-dir /dev/shm/rustc-1.19.0-src/build/x86_64-unknown-linux-gnu/stage1-rustc/release/build/pulldown-cmark-94247588bee65632 -L dependency=/dev/shm/rustc-1.19.0-src/build/x86_64-unknown-linux-gnu/stage1-rustc/release/deps --cap-lints allow` (exit code: 101)
> --- stderr
> error: linking with `gcc` failed: exit code: 1
>   |
>   = note: "gcc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/dev/shm/rustc-1.19.0-src/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/dev/shm/rustc-1.19.0-src/build/x86_64-unknown-linux-gnu/stage1-rustc/release/build/pulldown-cmark-94247588bee65632/build_script_build-94247588bee65632.0.o" "-o" "/dev/shm/rustc-1.19.0-src/build/x86_64-unknown-linux-gnu/stage1-rustc/release/build/pulldown-cmark-94247588bee65632/build_script_build-94247588bee65632" "-Wl,--gc-sections" "-pie" "-Wl,-O1" "-nodefaultlibs" "-L" "/dev/shm/rustc-1.19.0-src/build/x86_64-unknown-linux-gnu/stage1-rustc/release/deps" "-L" "/dev/shm/rustc-1.19.0-src/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" <a bunch of .rlib files> "-Wl,-Bdynamic" "-l" "ffi" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "ffi" "-l" "ffi" "-l" "ffi" "-l" "ffi" "-l" "ffi" "-l" "ffi" "-l" "gcc_s" "-l" "ffi" "-l" "ffi" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util" "-l" "ffi" "-l" "ffi"
>   = note: ld: cannot find -lffi
>           collect2: error: ld returned 1 exit status

**Comment by apaprocki** [comment]
(Even though that output was generated against rust 1.19, I verified the same thing happens with the current 1.24 release)

**Comment by cuviper** [comment]
This reminds me of #40717, where we found that `-lfoo` args are remembered by crates, but not `-Lpath`.

**Comment by jackh726** [comment]
I'm going to close this since there is no clear reproduction.
