### ISSUE TITLE
tracking issue for the Traits Working Group

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#48416]
### Introduction

The **Traits Working Group** is dedicated to all things "trait". In particular, the goal of the working group is to create and maintain the trait engine within the Rust compiler, as well as contributors ideas and insights to the language itself, when it comes to RFCs for traits. See [the announcement](https://internals.rust-lang.org/t/announcing-traits-working-group/6804) for more.

### Key facts

[z]: https://rust-lang.zulipchat.com/
[wg-traits]: https://rust-lang.zulipchat.com/#narrow/stream/144729-wg-traits

- Discussion takes place **on the [rust-lang Zulip][z]** in [the `#wg-traits` stream][wg-traits]
- Weekly triage meeting **Monday at 2:00pm Boston time** ([see in your timezone](http://www.thetimezoneconverter.com/?t=14:00&tz=Boston&)), takes place on Zulip
    - Notes in [this Dropbox Paper document](https://paper.dropbox.com/doc/WG-Traits-Planning-Meeting--ALDA5111ZliLv5zlSgbjvDS2Ag-oDfr6ct8xx63HSAOOmIZX)

### How to get involved

Drop in on the Zulip channel and introduce yourself. We're just starting up again after a long hiatus, so hopefully we'll have a bit more structure once we get our footing.

**Comment by lloydmeta** [comment]
I only have working knowledge of traits, but I'm keen to learn more and can put some time in on a weekly basis :)

**Comment by giannicic** [comment]
I'm interested in working on this. I just know the trait system at an higher level and I'd like to learn it more deeply.  I'll take a look at the posts to get a general idea of the things to do.

**Comment by JoeyEremondi** [comment]
I'm a PhD student working with Ron Garcia, extending some of [Jonatan Milewski's work](https://open.library.ubc.ca/cIRcle/collections/ubctheses/24/items/1.0220521). I've got a research project right now where I've got a declarative model of traits in a Rust-like language, along with associated type constructors and higher-ranked types, along with a verified inference algorithm. It's almost at a point where there's a draft worth sharing.

I'd love to be involved with this group. I've done some Rust programming, and I've got some previous experience with logic programming.

**Comment by autodidaddict** [comment]
Interested in contributing however ICan.

**Comment by Centril** [comment]
This sounds interesting. I'd love to contribute. Thus far, I haven't done more than write RFCs and such. I haven't made any contributions to the compiler itself (outside of the standard library) yet, so I'd love to learn. Count me in =)

**Comment by nikomatsakis** [comment]
Hey all! Glad to hear about the interest. Sorry I didn't get to many specifics today, will try to do so tomorrow and over the weekend.

**Comment by GeertVL** [comment]
@nikomatsakis  Posted it on the internals post but let you know it this way too.

**Comment by nikomatsakis** [comment]
cc @rust-lang/wg-traits -- I opened a thread on internals:

> First off, I want to apologize for the radio silence on this working group. It’s been harder than I anticipated to come up get a good crop of “start issues” and so forth. In general, I feel like we’re still trying to figure out the best way to get a “working group” up and going.Therefore, I thought, if I can’t figure this out on my own, why don’t we all start talking it out together? Hence this thread!

**Comment by nikomatsakis** [comment]
For those of you following this issue, we're trying to get this group up and going again! We plan to have a meeting (on Zulip, this time) this coming Monday.

**Comment by dhardy** [comment]
By my reckoning the meeting should be now?

**Comment by jackh726** [comment]
I'm going to go ahead and close this. wg-traits has it's own repo `rust-lang/wg-traits` where we can track things as needed.
