### ISSUE TITLE
🛠 improve canonicalization by using a hashing scheme

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#48417]
The canonicalization scheme created in https://github.com/rust-lang/rust/pull/48411 works by first folding types into a canonical form, which is then hashed and interned. This is not necessary, and it shows up in the profiles: we could augment the `TypeFolder` trait to have a method for hashing as it goes (e.g., a `hash_with` method, and some `hash_ty` / `hash_region` callbacks). Then we can begin by hashing the value-to-be-canonicalized, producing a hash (this would be a kind of "stable hash", hence big enough to be presumed unique). We would then look for an interned value with that hash and return it if found, avoiding all the folding. If no interned value is found, *then* we would fold and put the resulting value into the interning table. Ideally, this hash can then be kept for later, making the "stable hash" code quite cheap.

(This might actually not make things faster, of course, we would want to measure.)

**Comment by nikomatsakis** [comment]
That said, in all profiles I've looked at, canonicalization doesn't seem to be a hot spot.

**Comment by JaimeValdemoros** [comment]
I had an initial go at defining with `hash_with` method in a branch here: https://github.com/JaimeValdemoros/rust/tree/pre-canonicalization-hashing

**Comment by technicalguy** [comment]
@JaimeValdemoros Are you still working on this? If you make a pull request (even if it's not "finished" or "ready") then it will be much easier for everyone to see your code (rather than getting GitHub to diff your branch against rust/master directly).

**Comment by nikomatsakis** [comment]
I'm tagging this with WG-compiler-nll and NLL-performant since this is also an important issue for non-lexical lifetimes. canonicalization takes about 5% of NLL time.

**Comment by JaimeValdemoros** [comment]
Sorry about the delay - I'm still keen give this a shot! I've just made a PR here: https://github.com/rust-lang/rust/pull/51837 following @technicalguy's suggestion.

**Comment by nikomatsakis** [comment]
@JaimeValdemoros, @technicalguy -- think you two could [join the rust-lang Zulip](https://rust-lang.zulipchat.com)? I've created [a thread where we could chat about this](https://rust-lang.zulipchat.com/#narrow/stream/122657-wg-nll/topic/issue-48417-more-efficient-canonicalization).

**Comment by nikomatsakis** [comment]
Current measurements are showing canonicalization as 11% of NLL check, with the latest optimizations, so this is becoming increasingly relevant.

**Comment by technicalguy** [comment]
@nikomatsakis I think I have joined Zulip now...yet another chat application!

**Comment by nikomatsakis** [comment]
So, this is a big refactoring, and my measurements suggest that while it would help NLL, it would not make a huge difference. I'm going to remove this from the milestone.

**Comment by nikomatsakis** [comment]
Perhaps, in any case, this was a bit much too chew at once, I'm going to see if I can break it down into smaller steps.

**Comment by pwnorbitals** [comment]
@nikomatsakis is this issue still being worked on ? This sounds like a great refactoring

**Comment by technicalguy** [comment]
> is this issue still being worked on ?

I'm not currently working on it, for one, so go ahead if you're interested!

**Comment by jackh726** [comment]
Closing. This seems like a lot of work for maybe not so much gain. Plus, this can be achieved mostly through queries.
