### ISSUE TITLE
Consider using sccache to cache Rust code on CI builds

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#48412]
Currently, sccache is only used for caching C dependencies of the rust compiler. However, sccache has (experimental) support for [caching Rust builds](https://github.com/mozilla/sccache/blob/master/docs/Rust.md). Since any given pull request will usually only modify a few compiler crates, this has the potential to greatly reduce build times (helping to address issues such as https://github.com/rust-lang/rust/issues/46903).

At the moment, sscache doesn't appear to handle incremental compilation. It might be worthwhile to look into extending sscache to support caching incremental compilation output - though given the total number of jobs Rust runs on Appveyor and Travis CI, the amount of storage required could be prohibitive.

**Comment by ishitatsuyuki** [comment]
Significant amount of time is spent compiling stage1, and running compiler tests. Those are not going to be cached (since the codegen can change). In short, only stage0 builds may be cached.

**Comment by Mark-Simulacrum** [comment]
Even stage 0 builds are somewhat unlikely to be cached as it's pretty easy to invalidate it, and it's also something that we'd need to be very careful about to avoid false negatives due to not detecting dependency edges; all in all I don't think this is tenable.
