### ISSUE TITLE
Various functions taking a `TyCtxt` and a `Span` should be taking a `TyCtxtAt`

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#48425]
One example is the `is_sized` method on `Ty`. Internally it creates a `tcx.at(span)`, when it could simply be taking exactly that `TyCtxtAt` as an argument. In miri I had to write `ty.is_sized(tcx.tcx, param_env, tcx.span)` which just feels a little riddiculous (taking apart the `TyCtxtAt`, just to have the method construct it back).

There's probably many other similar methods and functions that should be taking a `TyCtxtAt`

**Comment by PramodBisht** [comment]
Can I take this one if no one is working on that and if its not very urgent to be fixed immediately?

**Comment by oli-obk** [comment]
@PramodBisht it's all yours!
