### ISSUE TITLE
is there a way of building rust offline?

### ISSUE THREAD

**Issue by thebunnyrules** [rust-lang/rust#48422]
Hi, I was wondering if there's anyway of building rust offline? have it download all it's sources in advance? The machine I'm building it on is offline.

**Comment by oli-obk** [comment]
Assuming you have a full recursive clone of the main repository, all you need is the correct compiler for stage0. You can set the `rustc` in `config.toml` to point to the manually downloaded one. You need to do the same for cargo.

**Comment by ishitatsuyuki** [comment]
Adding to what @oli-obk said, you also need vendored sources which is included in source tarballs (not from GitHub). They can be generated beforehand with cargo-vendor.

**Comment by steveklabnik** [comment]
Questions are best posted to users.rust-lang.org, though internals.rust-lang.org might be better for this specific question. We try to keep the issue tracker to bugs only, so I'm going to give this a close! Thanks.

**Comment by thebunnyrules** [comment]
thanks alot guys! I'll ask ask any further question on the forum.
