### ISSUE TITLE
Why iterator all() and any() accept closure?

### ISSUE THREAD

**Issue by buckle2000** [rust-lang/rust#48424]
IMO, `std::iter::Iterator::all` and `any` should not accept any argument. Currently, their functionality overlap with `map`.
Instead, `it.all(f)` should be `it.map(f).all()`; also, only implement `all` and `any` when `Iterator::Item` is `bool`.

**Comment by buckle2000** [comment]
```rust
fn main() {
    let v = vec!(true, false, true);
    let w = v.into_iter().all(|x|x);
    println!("{:?}", w);
}
```

**Comment by kennytm** [comment]
Given these two functions are stable, it's extremely unlikely we'll change these two functions.

**Comment by vitalyd** [comment]
C#’s `Any` and `All` also take a closure.  As do Java’s `Stream` analogs.

**Comment by sfackler** [comment]
As noted above, this isn't an actionable request.
