### ISSUE TITLE
 Error message when using inner static with type parameters is misleading

### ISSUE THREAD

**Issue by malbarbo** [rust-lang/rust#48427]
This code

```rust
fn x<T: Default>() {
    static a: T = T::default();
}
```

generates this error:

```text
error[E0401]: can't use type parameters from outer function; try using a local type parameter instead
 --> src/main.rs:2:15
  |
2 |     static a: T = T::default();
  |               ^ use of type variable from outer function

error[E0401]: can't use type parameters from outer function; try using a local type parameter instead
 --> src/main.rs:2:19
  |
2 |     static a: T = T::default();
  |                   ^^^^^^^^^^ use of type variable from outer function

error: aborting due to 2 previous errors
```

which is misleading because a local type parameter is being used.

The [original](https://github.com/rust-lang/rust/commit/0db50056aec603eadff2e7f2e8e6519824add552#diff-bcbfd0820dc70f27905e7d5f414b813e) message was different.

I have one question: why this is forbidden? There is an [issue](https://github.com/rust-lang/rust/issues/9186) with some discussion but I do not see why this is not possible.

Using static with type parameters is very useful, for example, defining thread local buffer for store temporary results (like in a sorting algorithm).

**Comment by oli-obk** [comment]
I think the big problem would be crate A instantiating static `a` by invoking crate B's `x` function. If then crate `C` also instantiates static `a` by invoking crate `B`'s `x` function, you end up with two different `a`. So if crate `D` depends on `A` and `C`, you'll get very weird behaviour. Might be solvable with MIR only rlibs, but it's generally really easy to get this wrong.

Note that you can get around this limitation by creating another trait bound on `T`:

```rust
trait Foo: 'static {
    fn singleton() -> &'static Self {
        unimplemented!()
    }
}

fn x<T: Default + Foo>() {
    let a = T::singleton();
}
```

Side-note: you won't be able to call `T::default()` in a static constructor anyway

**Comment by estebank** [comment]
[Current output](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=9c4009809837a908fc82496d3b6ffa80) is buggy (the spans pointing at `x` shouldn't be there at all):

```
error[E0401]: can't use generic parameters from outer function
 --> src/lib.rs:2:15
  |
1 | fn x<T: Default>() {
  |    - - type parameter from outer function
  |    |
  |    try adding a local generic parameter in this method instead
2 |     static a: T = T::default();
  |               ^ use of generic parameter from outer function

error[E0401]: can't use generic parameters from outer function
 --> src/lib.rs:2:19
  |
1 | fn x<T: Default>() {
  |    - - type parameter from outer function
  |    |
  |    try adding a local generic parameter in this method instead
2 |     static a: T = T::default();
  |                   ^^^^^^^^^^ use of generic parameter from outer function
```

Closing in lieu of newer ticket #57775, which has more conversation.
