### ISSUE TITLE
Struct Layout Optimization in Rust 1.18 regressed C ABI

### ISSUE THREAD

**Issue by CryZe** [rust-lang/rust#48433]
In addition to the general question raised by https://github.com/rust-lang/rust/issues/48426 of whether a pair of floats should use a LLVM vector in the Rust ABI, it seems like the C ABI regressed in Rust 1.18 in this regard too. Before Rust 1.18 it used to actually represent the repr(C) equivalent type as a LLVM vector, but since 1.18 the type gets passed as a double instead and then bitcast to the individual fields inside, completely disabling all the vectorization possible.

Code:
```rust
#[repr(C)]
pub struct Vec2 {
    pub x: f32,
    pub y: f32
}

#[no_mangle]
pub extern "C" fn add (a: Vec2, b: Vec2) -> Vec2 {
    Vec2 {
        x: a.x + b.x,
        y: a.y + b.y
    }
}
```

Rust 1.17:
```llvm
define <2 x float> @add(<2 x float>, <2 x float>) unnamed_addr #0
```
```asm
add:
  addps xmm0, xmm1
  ret
```

Rust 1.18:
```llvm
define double @add(double, double) unnamed_addr #0
```
```asm
add:
  movq rax, xmm0
  movd xmm0, eax
  shr rax, 32
  movd xmm2, eax
  movq rax, xmm1
  movd xmm1, eax
  shr rax, 32
  movd xmm3, eax
  addss xmm1, xmm0
  addss xmm3, xmm2
  movss dword ptr [rsp - 8], xmm1
  movss dword ptr [rsp - 4], xmm3
  movsd xmm0, qword ptr [rsp - 8]
  ret
```

Here's the code on Godbolt compiled with Rust 1.17 and 1.18: https://godbolt.org/g/1iu8n2

**Comment by eddyb** [comment]
Oh, *that*'s why `extern "C"` isn't that great! Note that ABI-wise these are equivalent, and choosing `<2 x float>` over `double` is a matter of heuristics (for `clang` too, e.g. if you use an `union`).

**Comment by Mark-Simulacrum** [comment]
Seems to be equivalent to https://github.com/rust-lang/rust/issues/48426, closing.
