### ISSUE TITLE
Server not starting - Rust Linux LGSM 

### ISSUE THREAD

**Issue by Achillesfm** [rust-lang/rust#48440]
done.
Initializing 10552 entity links
done.
Initializing 234 stability supports
done.
Initializing 9641 entity save caches
done.
Server.Ip = 177.54.156.199
Server.Ip.HostOrder = 2973146311
Couldn't initialize Steam Server (2973146311)
Server startup complete
EasyAntiCheat Scout Shutting Down
EasyAntiCheat Server Shutting Down

there is the log

**Comment by Mark-Simulacrum** [comment]
This is not the game, this is Rust the programming language. I'd presume that you need to file a report with the game developers.

**Comment by NewAmbition** [comment]
Although this may have been closed, there is no evidence leading towards what the issue may be (that I can see). I'm getting the same issue on my server from about 10h ago
