### ISSUE TITLE
Calling inherent method on a statically known associated type fails

### ISSUE THREAD

**Issue by jpernst** [rust-lang/rust#48451]
Given the code:

```rust
     struct Foo { }

impl Foo {
   fn baz() { }
}

fn main() {
    use std::ops::Deref;
    
    Foo::baz(); // OK
    <<Box<Foo> as Deref>::Target>::baz(); // Error
}
```

The following error is produced on both stable (1.24) and nightly.
```
error[E0599]: no function or associated item named `baz` found for type `Foo` in the current scope
  --> src/main.rs:11:5
   |
1  | struct Foo { }
   | ---------- function or associated item `baz` not found for this
...
11 |     <<Box<Foo> as Deref>::Target>::baz();
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `Foo`
```

The compiler is clearly able to deduce that `Foo` is the type in question, yet the inherent impl seems to be ignored. In other contexts, referring to a type in this way works correctly, such as using it as the type for a variable declaration.

While it's possible to just strip away the associated type since we know which type we want anyway, this code is a reduced example from a proc macro where that is more difficult to do.

This might be a dup of #37591, but it's hard to say from the outside.

**Comment by steveklabnik** [comment]
This example now compiles without error; closing!
