### ISSUE TITLE
Alloc methods should take layout by reference

### ISSUE THREAD

**Issue by joshlf** [rust-lang/rust#48458]
Currently, the methods of the `Alloc` trait that take a `Layout` take it by value. This is unnecessary, and makes clippy unhappy. Instead, they should take their `Layout` arguments by reference.

**Comment by nagisa** [comment]
I feel that Layout being passed by-value is very intended. It is 2-usize worth of data, which will usually be split over registers for the call and end up being more efficient than going through a reference.

**Comment by nagisa** [comment]
clippy warning about this seems like a false positive though.

**Comment by joshlf** [comment]
Fair enough. @Manishearth do you have thoughts on clippy's behavior here? Is this just one of those situations in which the right move is to silence clippy with an `allow(needless_pass_by_value)`?

**Comment by joshlf** [comment]
Doesn't look like it's `Copy`: https://doc.rust-lang.org/src/alloc/allocator.rs.html#46

**Comment by Manishearth** [comment]
That seems incorrect?

In this case the clippy lint is working as it should; taking non-copy types by-move isn't really good. If you're doing this for perf reasons slap on an allow.

**Comment by joshlf** [comment]
Incorrect in that `Layout` ought to be `Copy` or incorrect in that I shouldn't be complaining about it if clippy is in the right? :)

**Comment by Manishearth** [comment]
Layout should be Copy.

If it's not because it's considered a hazard (much like how Range isn't Copy) then it should be passed by reference because otherwise it gets consumed each time and needs explicit cloning.

**Comment by joshlf** [comment]
Also, IIRC, the reason that it's not `Copy` is that somebody (I believe it was @SimonSapin ?) wanted to leave the door open to having `Layout`s be able to contain a chain of other `Layout`s from which they were derived, which would preclude them from being `Copy`. As I see it:
- If we go that route, then `Layout`s are expensive to clone, and so *should* be passed by reference
- If we don't go that route, then `Layout`s should be `Copy`

**Comment by joshlf** [comment]
> Layout should be Copy.

I tend to agree.

**Comment by Manishearth** [comment]
Yeah, that reasoning makes sense. In that case these APIs _definitely_ should operate by-ref.

**Comment by Manishearth** [comment]
cc @Gankro

**Comment by SimonSapin** [comment]
@joshlf This is the first I hear of `Layout`s being (possibly) chained.

(FWIW I care less about the details of the `Alloc` trait than I care about stabilizing it within months rather than years.)

**Comment by vitalyd** [comment]
Hmm, I don't see a compelling reason to make `Layout` `Copy` *right now* and carry that contract.  The comment earlier about it being 2 words and thus splittable across registers can also looked at as:

- it might be a downside on register starved arch
- it might not matter if callee is inlined and compiler can shuffle the code as it sees fit

All that to say, I don't think how the optimizer is going to pass it around should be _the_ criteria to decide on `Copy` or not.

**Comment by joshlf** [comment]
@SimonSapin weird, I could have sworn that I'd brought this issue up before and that was the answer. I couldn't find it by Googling, though, so maybe I was just dreaming.

**Comment by SimonSapin** [comment]
@joshlf It’s quite possible that someone said that, but it wasn’t me so I can’t tell you about reasoning and such.

**Comment by SimonSapin** [comment]
I chatted with @pnkfelix about this today. It’s been several years now since the allocation APIs was considered as hypothetically enabling GC integration, but nothing concrete has happened in that space since. In particular, the idea was that users would *have* to go through the allocator to create a `Layout`, which could then contain allocator-specific data about the type being allocated.

But now we have a `Layout::from_size_align` constructor and it seems very unlikely that we’ll remove it, so at this point we can probably give up on that idea and make `Layout: Copy`. PR: https://github.com/rust-lang/rust/pull/50109
