### ISSUE TITLE
Tracking issue for `'_`

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#48469]
This is a sub-issue of https://github.com/rust-lang/rust/issues/44524, tracking the desire to stabilize `'_` (and the lints around its usage).

### Covered areas

The `'_` can be used anywhere that a region can be elided. It (typically) carries the same meaning as having no region at all. This section summarizes its usage, giving pointers to tests, and also listing known blocking issues.

- `fn foo(x: Ref<'_>)` -- fresh name
- `fn foo(&self) -> Ref<'_>` -- links to `self`
- `fn foo(&self) -> Box<dyn Debug + '_>` -- links to `self`, not quite the same as `Box<dyn Debug>`
    - **blocked** on https://github.com/rust-lang/rust/issues/48468
- `fn foo(&self) -> Box<impl Debug + '_>` -- links to `self`, not quite the same as `Box<impl Debug>`

Some areas where elision *ought* to be supported are not yet:

- `impl Foo for Ref<'_>` -- not yet implemented, this is #15872
- `where T: Trait<'_>` -- not yet implemented, this is https://github.com/rust-lang/rust/issues/45667
    - also, what semantics are desired here? Where is the binder?

There are also several linted scenarios to nudge the user in the right direction:

- Eliding parameters of a lifetime-parameterized struct (e.g., `Ref`) is deprecated, prefer `Ref<'_>`
    - `#[warn(elided_lifetime_in_path)]`
    - **blocked** on https://github.com/rust-lang/rust/issues/48385 -- triggers for `format!`
- Lifetime names used only once are deprecated:
    - `#[warn(single_use_lifetime)]`
    - **blocked** on https://github.com/rust-lang/rust/issues/44752 -- only partially impemented

### Changes or clarifications to the RFC

The behavior around `dyn Trait` is probably worth highlighting, since it is one case where `'_` differs from writing nothing at all.

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

I want to propose that we **stabilize** `'_`, with the semantics as given in the header of this post. Note however that there are some blocking issues that must be resolved (cited in the header) before stabilization can actually occur. But those don't need to block us making the **decision** to stabilize.

**Comment by steveklabnik** [comment]
was this closed by https://github.com/rust-lang/rust/pull/49458 ?

**Comment by nikomatsakis** [comment]
Seems like...yes.
