### ISSUE TITLE
behavior of `'_` around `dyn Trait` is wrong

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#48468]
Generally speaking, `'_` is equivalent to "eliding" a lifetime completely. That is, `&'_ T` and `&T` are equivalent, as are `Foo<'_>` and `Foo` (unfortunately). **However**, there are two cases where this is not true:

- `dyn Trait + '_` -- the object-lifetime-defaulting rules are different, and `'_` needs to interact with them (same for `Trait`, of course)
- `impl Trait + '_` -- same, but for different reasons

@cramertj pointed out that [our current behavior around `dyn Trait`](https://play.rust-lang.org/?gist=d2c04a086fd11e946c1d7308b5f92205&version=nightly) is not what we really want:

```rust
#![feature(dyn_trait)]
#![feature(underscore_lifetimes)]

// These two give the same error that the iterator must be valid for the 'static lifetime:
fn a<T>(items: &[T]) -> Box<dyn Iterator<Item=&T>> {
    Box::new(items.iter()) //~ ERROR cannot infer an appropriate lifetime
}

fn b<T>(items: &[T]) -> Box<dyn Iterator<Item=&T> + '_> {
    Box::new(items.iter()) // *Should* be OK, currently errors
}

// But this one works:
fn c<'a, T>(items: &'a [T]) -> Box<dyn Iterator<Item=&'a T> + 'a> {
    Box::new(items.iter()) // OK
}

fn main() { }
```

**Comment by ExpHP** [comment]
```rust
fn b<T>(items: &[T]) -> Box<dyn Iterator<Item=&T> + '_>;
```

I find this fascinating. Who would have predicted prior to implementation that introducing  `'_` would allow us to elide even more lifetimes?
