### ISSUE TITLE
Provide a way to build the compiler with --error-format=json

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#48475]
Preferably as a flag to ./x.py; preferably such that the output gets stored in the build dir.

We already run cargo with --message-format=json so we may need to differentiate somehow.

cc @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
If someone would like to implement this I'd be happy to write up mentoring instructions, otherwise I'll probably do it sometime soon.

**Comment by penpalperson** [comment]
@Mark-Simulacrum has been mentoring me on this - I'll submit a pull request soon!

**Comment by Mark-Simulacrum** [comment]
Opened https://github.com/rust-lang/rust/pull/48558 to fix the missed fact that we hide JSON output anyway
