### ISSUE TITLE
./x.py test should be able to run individual tests

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#48483]
Currently to run an individual test, you have to run `./x.py test src/test/run-pass --test-args foo.rs`. This isn't very obvious; it would be nice if `src/test` was special cased such that `./x.py test ./x.py test src/test/run-pass/foo.rs` works

Relevant code: https://github.com/rust-lang/rust/blob/master/src/bootstrap/test.rs

**Comment by Mark-Simulacrum** [comment]
I agree that it'd be nice, but I think this would require some refactoring in `compiletest` as well -- currently it only accepts filters by test name (which we could sort of do, but it'd be imprecise) but not quite more than that.

**Comment by Manishearth** [comment]
For the scope of this bug we can just transform `test src/test/run-pass/foo.rs` into `test src/test/run-pass --test-args foo.rs`. This may match multiple tests, but it's close enough. Adding a specific argument for this to compiletest would be the next step.

**Comment by christianpoveda** [comment]
I'd like to take care of this

**Comment by christianpoveda** [comment]
Sorry, I haven't been able to work on this. If anyone else wants to take it, feel free to do it

**Comment by collin5** [comment]
@christianpoveda No problem. Will give this a try as my first contribution.
