### ISSUE TITLE
thread 'rustc' panicked at 'other was less than the current instant'

### ISSUE THREAD

**Issue by plavcik** [rust-lang/rust#48514]
I created hello.rs file with copy of example on https://www.rust-lang.org/en-US/
then

rustc hello.rs 
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.20.0 running on x86_64-unknown-openbsd

thread 'rustc' panicked at 'other was less than the current instant', /usr/obj/ports/rust-1.20.0/rustc-1.20.0-src/src/libstd/sys/unix/time.rs:276:16
note: Run with `RUST_BACKTRACE=1` for a backtrace.

I'm on OpenBSD 6.2 amd64 with rust-1.20.0

**Comment by retep998** [comment]
This sounds like another case of faulty hardware/OS causing `Instant` to not actually be monotonic. This happened once before, but on Windows. https://github.com/rust-lang/rust/issues/47684

Could you provide details on what your exact CPU is?

**Comment by plavcik** [comment]
hw.machine=amd64
hw.model=Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
hw.ncpu=4
hw.byteorder=1234
hw.pagesize=4096
hw.vendor=LENOVO
hw.product=20GJ003QMC
hw.version=ThinkPad S2

**Comment by jonathanstrong** [comment]
In my experience, `Instant` is relatively easy to trigger a panic with. Perhaps a good solution would be to add to its public api so that failure can be handled. It would be very nice to have a `saturating_sub` fn, for instance.
