### ISSUE TITLE
🔬 refactor structure of `ty::Predicate`

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#48539]
The current `Predicate` conservatively assumes that **every  variant** may bind higher-ranked lifetimes:

https://github.com/rust-lang/rust/blob/322d7f7b97f1672bade31e1c43d5753e0e45a1a8/src/librustc/ty/mod.rs#L905-L941

This forces us to account for higher-ranked binders in a lot more places in the code than we really should have to. It would be nice to restructure `Predicate` to avoid that.

In the past, I tried two approaches. In one, I [separated out `Predicate` into `Predicate` and `PredicateAtom`](https://github.com/nikomatsakis/rust/blob/chalkify-universe-wip-predicate-atom/src/librustc/ty/mod.rs#L807-L843). In the other, [I introduced a `Poly` variant into `Predicate`](https://github.com/nikomatsakis/rust/blob/chalkify-universe-wip-predicate-poly/src/librustc/ty/mod.rs#L833-L866). In the latter case, this made the `Predicate` type recursive, so as an initial refactoring, I [converted `Predicate` to be a `&'tcx PredicateKind`, introducing indirection](https://github.com/nikomatsakis/rust/blob/chalkify-universe-wip-predicate-poly/src/librustc/ty/mod.rs#L820-L825).

It's been long enough that my memory is a bit dim, but I think that the second refactoring was done precisely because the first one turned out be rather intrusive. I am not sure just now which one I prefer, but I think we will want to do **one** of them sooner or later!

(NB. This will conflict with the work that @sgrif is doing in https://github.com/rust-lang/rust/issues/48536, though the conflicts ought to be possible to resolve.)

**Comment by nikomatsakis** [comment]
I think that the way to start here would be first to convert `Predicate` to be interned, so that it can have a recursive structure. The starting point would be to cherry-pick [this commit from my repo](https://github.com/nikomatsakis/rust/commit/99bbc5aa0653818d7287401096d8add7e43445b3). We would probably want to measure the performance of this, though. =)

**Comment by sgrif** [comment]
Given that this conflicts with what I'm already working on, I'd like to take this one.

**Comment by leodasvacas** [comment]
This was discussed in a WG-traits meeting. @nikomatsakis didn't remember why he originally wanted this and it seems less relevant with chalk, making it a low priority.

**Comment by nikomatsakis** [comment]
I'm going to close this issue altogether, since it seems like we are going more the route of building up a "parallel structure" for Chalk purposes.
