### ISSUE TITLE
Build error with -Wimplicit-fallthrough

### ISSUE THREAD

**Issue by sanxiyn** [rust-lang/rust#48543]
Forwarding https://forums.gentoo.org/viewtopic-t-1077612.html to here.

**Comment by sfackler** [comment]
It seems like this should probably be filed on https://github.com/WebAssembly/binaryen?

**Comment by petrochenkov** [comment]
https://github.com/rust-lang/rust/pull/48125 removes the `binaryen` submodule.

**Comment by sanxiyn** [comment]
binaryen removal landed, closing.
