### ISSUE TITLE
Spurious "does not live long enough" for closure coerced to fn pointer in static item (AST borrowck only)

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#48540]
The test case below is reduced from a [phf map](https://github.com/sfackler/rust-phf). 

rustc 1.26.0-nightly (28a1e4ffe 2018-02-24) with `-Z borrowck=mir`: OK

Without any `-Z` flag: error below, even though I believe the program to be valid. But maybe it’s not worth fixing if MIR-based borrow-checking will become the default soon? CC @nikomatsakis 

A work-around is to have the closure in an intermediate `const` item.

```rust
fn main() {}

struct Static<T: 'static>(&'static [T]);

static FOO: Static<fn(&u32) -> &u32> = Static(&[|x| x]);
```
```rust
error[E0597]: borrowed value does not live long enough
 --> a.rs:5:52
  |
5 | pub static FOO: Static<fn(&u32) -> &u32> = Static(&[|x| x]);
  |                                                    ^^^^^^^- temporary value only lives until here
  |                                                    |
  |                                                    temporary value does not live long enough
  |
  = note: borrowed value must be valid for the static lifetime...

error: aborting due to previous error
```
```rust
fn main() {}

struct Static<T: 'static>(&'static [T]);

static FOO: Static<fn(&u32) -> &u32> = Static(&[
    {
        const F: fn(&u32) -> &u32 = |x| x;  // work around
        F
    },
]);
```

**Comment by xftroxgpx** [comment]
Hey I learned something new, like: 
[adding](https://play.rust-lang.org/?gist=a40abe292b54e5527a8fe95d3020bff4&version=nightly) `#![feature(nll)]` is, apparently, equivalent to `-Z borrowck=mir` and to `-Z nll`

[NLL tracking issue](https://github.com/rust-lang/rust/issues/43234)

<details><summary>how to pass -Z flags with cargo</summary>

Thanks to durka42_ (on IRC) for telling me to how to pass those pesky -Z flags :D
eg. `cargo rustc -- -Z borrowck=mir`

`rustc -Z help`
</details>

**Comment by nikomatsakis** [comment]
It's actually equivalent to `-Zborrowck=mir -Znll -Ztwo-phase-borrows`, I think

**Comment by nikomatsakis** [comment]
@SimonSapin is this a regression, do you know?

**Comment by SimonSapin** [comment]
@nikomatsakis Not as far as I know. 1.24.0 stable gives the same error. Note that this is *fixed* by MIR-borrowck.

**Comment by nikomatsakis** [comment]
OK. In that case I am inclined to wait, yes.

**Comment by SimonSapin** [comment]
Adding the "fixed by NLL" label as an approximation of fixed by MIR borrowck
