### ISSUE TITLE
Allow to replace rust logo with another image?

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#48563]
I have a few options in mind:

 1. Add an option to fully replace the top-left image by the one provided by the user
 2. Add an option to add an extra small image which will be placed on bottom-right of the default rust image with a small size.

Would it be interesting to have such an option?

cc @rust-lang/docs

**Comment by sfackler** [comment]
Isn't that controlled by html_logo_url? https://github.com/rust-lang/rust/blob/master/src/libstd/lib.rs#L213

**Comment by GuillaumeGomez** [comment]
Potentially. Even crates that don't provide it have the image so maybe the mechanism already exists...

**Comment by steveklabnik** [comment]
Triage: not aware of any specific changes here, but yeah, I thought the logo url was this.
