### ISSUE TITLE
Tracking issue for RFC 2298, `?` repetition in macro rules

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#48591]
This is a tracking issue for RFC 2298 (rust-lang/rfcs#2298).

### Status

- [x] RFC accepted
- [x] Preliminary implementation started (https://github.com/rust-lang/rust/pull/47752)
- [x] Preliminary implementation available
- [ ] Stabilization proposed
- [ ] Stabilized

### Known bugs

None.

### Unresolved questions to be answered before stabilization

- Should the `?` Kleene operator accept a separator? Adding a separator is completely meaningless (since we don't accept trailing separators, and ? can accept "at most one" repetition), but allowing it is consistent with `+` and `*`. Currently, we allow a separator. We could also make it an error or lint.

**Comment by kennytm** [comment]
🤔 Duplicate of #48075?

**Comment by mark-i-m** [comment]
Yep it is a duplicate

**Comment by Centril** [comment]
Hmm... missed that tracking issue. I'll close that one since it is easier =)

**Comment by kennytm** [comment]
The issue number in https://github.com/rust-lang/rust/blob/29f5c699b11a6a148f097f82eaa05202f8799bbc/src/libsyntax/feature_gate.rs#L448 will need to be updated in this case...

**Comment by Centril** [comment]
Oh damn... Less work to fix the RFC I guess... reopening that one then. <such a mess> =P
