### ISSUE TITLE
CI: Make sure that we can bootstrap with cfg(parallel_queries).

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#48607]
For now a [docker image](https://github.com/rust-lang/rust/tree/master/src/ci/docker) that just builds with `cfg(parallel_queries)` (but without running tests) should be enough. 

cc @Zoxc

**Comment by Zoxc** [comment]
I would also like Travis PRs builds to run `x.py check` with `cfg(parallel_queries)` before doing the normal build without `cfg(parallel_queries)`.

**Comment by Zoxc** [comment]
cc @rust-lang/infra

**Comment by alexcrichton** [comment]
We unfortunately don't have a lot of spare cycles on CI right now, both in terms of overall capacity and extra time to run *more* tests on builders (we're already timing out all over the place). If this is "things are on fire we really need this" then this can be prioritized, but otherwise this probably won't happen for awhile.

**Comment by alexcrichton** [comment]
er, didn't mean to close

**Comment by michaelwoerister** [comment]
I think it would be great if we could at least make sure that stage 0 builds with `cfg(parallel_queries)`. Down the line we'll have to run test too but that's not so urgent.

**Comment by alexcrichton** [comment]
That may be easier to do so, yeah. We could probably do something like `RUSTFLAGS_STAGE0=...` on whatever builder executes the fastest today, such as [x86_64-gnu-debug](https://travis-ci.org/rust-lang/rust/jobs/352216962)

**Comment by Zoxc** [comment]
I'd be satisfied with running `x.py check` on some configuration which should take like 6 minutes (assuming it skips LLVM).

**Comment by Zoxc** [comment]
Running `x.py check` first would also serve to quickly reject PRs with compile errors. I'm not sure that matters for the bors queue, but it might help with PR builds.

**Comment by alexcrichton** [comment]
Oh yeah that could for sure work! The `check` build finishes so quickly we could just add a slew of extra builders on Travis. They can get scheduled in the cracks between other builds

**Comment by michaelwoerister** [comment]
That seems like a good first step.

**Comment by michaelwoerister** [comment]
The `./x.py check` approach was added in https://github.com/rust-lang/rust/pull/49120 and #50444 extends it a little.

**Comment by Mark-Simulacrum** [comment]
Closing as per the above. @aturon is taking over some of the parallel compiler review work though so I think as we move closer to making that stable we'll probably want to enable more builders and such but keeping this open doesn't seem too useful.
