### ISSUE TITLE
Auto-trait documentation section empty with manual auto-trait impls

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#48606]
With https://github.com/rust-lang/rust/pull/47833 merged, I expected to see auto-trait implementations in the nightly docs in a separate section. However, in case there are manual `impl`s, they are still shown in the "Trait Implementations" section. For example, <https://doc.rust-lang.org/nightly/std/cell/struct.Cell.html> has the impls for `Send` and `!Sync` in the "Trait Implementations" section, leaving the "Auto Trait Implementations" section entirely empty.

At the very least, this looks funny and probably the section header should not be shown if the section is empty. However, I actually think it'd make more sense to move manual impls of auto-traits into that section -- this way, the place to look for `Send` and `Sync` impls is always the same, instead of depending on the type like it does now.

**Comment by GuillaumeGomez** [comment]
I don't see this bug anymore so I'll close the issue. Don't hesitate to reopen it if you find it again.
