### ISSUE TITLE
Improve error message for "[E0599]: no method named ...." for Result, Option

### ISSUE THREAD

**Issue by insanitybit** [rust-lang/rust#48616]
I was helping a beginner with some Rust and they were tripping over this error message, as demonstrated here:

https://play.rust-lang.org/?gist=48d86baa9cad05b96839678ca7cbe960&version=stable
```rust
fn main() {
    Ok(5).to_string()
}
```

It would be great if in the case of a Result<T> or Option<T>, given a 'no method named' error, rustc checked the T type to see if *it* has that method (or derefs to have that method) and suggests pattern matching, or explains that a variant does actually implement the method.

This could possibly be generalized to any enum, but I think Result is the really big one, followed by Option.

**Comment by BGR360** [comment]
I like this idea, but I agree that special-casing it to just `Result` and `Option` would be cheap. 

To throw out some ideas for a more general diagnostic:
* (per @insanitybit 's suggestion) If the type is an enum and one or more of the variants has the method, then suggest pattern matching or if-let
* If the type is a struct and has one or more fields that have the method, then suggest using one of those fields
  * do we already do this?
* If the type has a generic argument that is substituted with a type that has the method, then mention it
  * e.g., `Option<T>` where `T: Display`
* If the type has a method that consumes `self` and returns another type that does have the method, then suggest calling that method

Thoughts @estebank @davidtwco @oli-obk ?

**Comment by davidtwco** [comment]
> * (per @insanitybit 's suggestion) If the type is an enum and one or more of the variants has the method, then suggest pattern matching or if-let
> * If the type is a struct and has one or more fields that have the method, then suggest using one of those fields
>   
>   * do we already do this?
> * If the type has a generic argument that is substituted with a type that has the method, then mention it
>   
>   * e.g., `Option<T>` where `T: Display`

I think this is broadly sensible, if there's a value of some enum variant or struct type with a single field (regardless of whether it was generic in the definition), we could add a help. 

> * If the type has a method that consumes `self` and returns another type that does have the method, then suggest calling that method
 
This might make sense but seems quite different from the others and is probably harder to implement, so maybe after the others?

**Comment by Dylan-DPC** [comment]
Current output:
```
error[[E0599]](https://doc.rust-lang.org/stable/error_codes/E0599.html): the method `to_string` exists for enum `Result<{integer}, _>`, but its trait bounds were not satisfied
 --> src/main.rs:3:11
  |
3 |     Ok(5).to_string()
  |           ^^^^^^^^^ method cannot be called on `Result<{integer}, _>` due to unsatisfied trait bounds
 --> /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:503:1
  |
  = note: doesn't satisfy `Result<{integer}, _>: ToString`
  |
  = note: doesn't satisfy `Result<{integer}, _>: std::fmt::Display`
  |
  = note: the following trait bounds were not satisfied:
          `Result<{integer}, _>: std::fmt::Display`
          which is required by `Result<{integer}, _>: ToString`
note: the method `to_string` exists on the type `{integer}`
 --> /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/string.rs:2503:5
help: consider using `Result::expect` to unwrap the `{integer}` value, panicking if the value is a `Result::Err`
  |
3 |     Ok(5).expect("REASON").to_string()
  |          +++++++++++++++++
  ```

**Comment by Dylan-DPC** [comment]
Looking at the error message again, this is resolved based on the original issue posted
