### ISSUE TITLE
Enum with assigned values does not get exported as enum

### ISSUE THREAD

**Issue by hmvp** [rust-lang/rust#48634]
I have an enum like:

```rust
#[allow(missing_debug_implementations, missing_copy_implementations, non_camel_case_types)]
#[repr(C)]
#[cfg_attr(test, derive(Copy, Clone, Debug))]
pub enum ErrorCode {
    ERROR_EMPTY_LIST = 0,
    ERROR_VALUE_UNKNOWN = -1,
    ERROR_WRONG_TYPE = -2,
    ERROR_VALUE_INVALID = -3,
    ERROR_CONTEXT_INVALID = -4
    ERROR_DEVICE_NOT_FOUND = -5,
    ERROR_GROUP_NOT_FOUND= -6,
    ERROR_FIELD_NOT_FOUND = -7,
}
```

which is not used directly so I export it though `export.include`

however it ends up as 
```C
typedef struct ErrorCode ErrorCode;
```

Which is quite useless

A similar enum where I don't set the enum values works as expected

**Comment by oli-obk** [comment]
Which tool are you using to generate that code and where are you specifying the `export.include`?

**Comment by hmvp** [comment]
Ugh I must have misplaced a tab. This is supposed to be filed for cbindgen... Don't know what happend here..
