### ISSUE TITLE
Documentation for `Clone` is inaccurate w/r/t large arrays (always?) not implementing `Clone`.

### ISSUE THREAD

**Issue by chordowl** [rust-lang/rust#48646]
Currently, the `Clone` docs state that `Clone` is not implemented for arrays with more than 32 elements: https://github.com/rust-lang/rust/blob/3eeb5a665e313c5b281820099e04d4c6c8188b46/src/libcore/clone.rs#L73-L89

This seems to be untrue, at least for the given example: [playground](https://play.rust-lang.org/?gist=1da18f79e3db80379adea8c67717eb7f&version=stable). This must've been the case [since at least 1.21.0](https://github.com/rust-lang/rust/blob/3eeb5a665e313c5b281820099e04d4c6c8188b46/RELEASES.md#libraries-3).

I would fix this myself, but unfortunately, from the PR linked in the changelog, I'm not quite sure in which circumstances `Clone` is now auto-implemented. I didn't just want to rip out the example without providing a new one that makes more sense for the current situation.

*Edit:* to prevent this from happening again, it might be nice to have an additional `compile_fail`-style example in the docs to show what doesn't work, so that doctests can catch it.

**Comment by steveklabnik** [comment]
I believe this is https://github.com/rust-lang/rust/issues/44490 ?

**Comment by steveklabnik** [comment]
Yes, this was changed at some point...

**Comment by steveklabnik** [comment]
Tagging as `E-hard` simply because we need to track down what the answer is; once that's done it will be `E-easy`.

**Comment by jonas-schievink** [comment]
Triage:
 
The [`Clone` docs](https://doc.rust-lang.org/std/clone/trait.Clone.html#additional-implementors) say:

> In addition to the implementors listed below, the following types also implement Clone:
> ...
> * Array types, for all sizes, if the item type also implements Clone (e.g., [i32; 123456])

The [array primitive docs](https://doc.rust-lang.org/std/primitive.array.html) say:

> Arrays of any size are Copy if the element type is Copy and Clone if the element type is Clone. This works because Copy and Clone traits are specially known to the compiler.

Closing as fixed.
