### ISSUE TITLE
Performance regression between 3/1 and 3/2

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/rust#48660]
Per https://github.com/rust-lang/rust/pull/47861#issuecomment-369842167.

**Comment by nikomatsakis** [comment]
This was caused by #47861, it seems. cc @sgrif. Rather surprising since we did measurements beforehand though!

**Comment by nikomatsakis** [comment]
I'm inclined to roll it back and try landing again after doing more investigation, though I'd not be opposed to doing some quick measurements to see if we can identify the problem.

**Comment by sgrif** [comment]
https://github.com/rust-lang/rust/pull/47861/commits/ccd92c2a4e5ed634bbbd6d3a5bd491c47b80f642 was meant to be removed from that PR, but somehow I accidentally re-added it. I'll see if I can cleanly just revert that one commit.
