### ISSUE TITLE
Type inference regression affecting app_dirs on MacOS

### ISSUE THREAD

**Issue by PlasmaPower** [rust-lang/rust#48668]
As seen in [this Travis build](https://travis-ci.org/PlasmaPower/ghcl/builds/347998640), `app_dirs` currently builds on stable but not beta because of a type inference regression.

**Comment by nikomatsakis** [comment]
The failure is a call to `into()`:

```
error[E0619]: the type of this value must be known in this context
  --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/app_dirs-1.1.1/src/imp/platform/macos.rs:10:40
   |
10 |         Ok(Component::RootDir.as_ref().into())
   |  
```

`as_ref` is not really meant to be used this kind of open-ended way, this is a common source of breakage -- that could be the problem.

cc @rust-lang/libs -- any new `AsRef` impls added recently?

**Comment by nikomatsakis** [comment]
Here is a [minimized test case](https://play.rust-lang.org/?gist=1124ace86322715d1e1e63aaba6d7c84&version=beta):

```rust
use std::path::Component;
use std::ffi::OsStr;

fn main() {
    let x: Box<OsStr> = Component::CurDir.as_ref().into();
}
```

**Comment by nikomatsakis** [comment]
Tagging as `T-compiler` for now since I don't immediately see what new impl could have caused this.

**Comment by sfackler** [comment]
Component implements `AsRef<Path>` in addition to the existing `AsRef<OsStr>` on beta.

**Comment by alexcrichton** [comment]
Switching relevant team to T-libs as this is almost for sure a T-libs issue rather than a T-compiler issue

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/48716.
