### ISSUE TITLE
diagnostics: "expected one of ...": check if they actually would fix the build

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#48692]
Just an idea I had while reading https://internals.rust-lang.org/t/compiler-diagnostics-improvement-wishlist/6886/

Let's say I have broken code like this
````rust
pub fn main() {
    let msg: String = String::from("hello world") // missing ";"
    println!("{}", msg);
}
````
The error message will be
````
error: expected one of `.`, `;`, `?`, or an operator, found `println`
 --> src/main.rs:3:5
  |
2 |     let msg: String = String::from("hello world") // missing ;
  |                                                  - expected one of `.`, `;`, `?`, or an operator here
3 |     println!("{}", msg);
  |     ^^^^^^^ unexpected token
````

As we can see, the compiler already suggests several characters.
I wonder if it made sense if the compiler could basically try all of them out on the suggested position (so 
```` let msg: String = String::from("hello world").````
```` let msg: String = String::from("hello world");````
```` let msg: String = String::from("hello world")?````
), notice that ";" actually resolves the build error and then especially promote filling in a ";".

In case of ````....String::from("hello world")?````, I actuall get
````
error: expected one of `.`, `;`, `?`, or an operator, found `}`
 --> src/main.rs:3:1
  |
2 |     let msg: String = String::from("hello world")? // missing ;
  |                                                   - expected one of `.`, `;`, `?`, or an operator here
3 | }
  | ^ unexpected token
````
which looks a bit silly since the "expected" operator is actually there.

**Comment by estebank** [comment]
The problem with that is the parser's lack of enough context at the time of encountering the incorrect token. We can perform some *minor* look aheads and attempts at parsing the code with the different expected tokens, but we're severely limited in how much we can can continue. That being said, _this case in particular_ might be possible to be handled.

**Comment by estebank** [comment]
Current output:

```
error: expected `;`, found `println`
 --> src/main.rs:2:50
  |
2 |     let msg: String = String::from("hello world") // missing ";"
  |                                                  ^ help: add `;` here
3 |     println!("{}", msg);
  |     ------- unexpected token
```
