### ISSUE TITLE
The Rust compiler bootstrap is vulnerable to trusting-trust attacks

### ISSUE THREAD

**Issue by devrandom** [rust-lang/rust#48707]
**Summary**: the Rust compiler requires the previous Rust compiler binary, making it vulnerable to persistent malware

Compiling a compiler with itself is convenient.  However, this flow results in the possibility that persistent malware is present and is injected into each version's compiler by the previous version.  This attack vector has been known since Ken Thompson's 1984 paper [Reflections on Trusting Trust](https://www.ece.cmu.edu/~ganger/712.fall02/papers/p761-thompson.pdf).  In fact, the attack has been seen [in the wild](https://www.wired.com/2009/08/induc/).

A method of counteracting this issue, [diverse double compilation](https://www.dwheeler.com/trusting-trust/) is available.  Unfortunately, it cannot be easily applied in this case. For one, the Rust compiler is not deterministic.  Also, the only other available compiler, [mrustc](https://github.com/thepowersgang/mrustc) is maintained by a single person and usually lags behind the latest Rust version.

To mitigate this issue, it would be best if the rust compiler could be completely bootstrapped from `gcc` and other mainstream build tools.

**Comment by sfackler** [comment]
Why do you trust gcc?

**Comment by devrandom** [comment]
It can be diverse-double-compiled, and its output is deterministic.

**Comment by jonas-schievink** [comment]
> To mitigate this issue, it would be best if the rust compiler could be completely bootstrapped from gcc and other mainstream build tools.

How would this be accomplished?

**Comment by est31** [comment]
A Rust frontend for GCC, especially one that can compile rustc successfully would be wonderful, not just to thwart the trusting trust attack, but also to help embedded developers.

If you want to verify yourself that the rust compiler doesn't contain a trusting trust attack, you can simply compile the latest version of Rust that mrustc supports, and then use the traditional rust bootstrap to get to the very latest Rust version. This is much much shorter and much easier to do than to start with the old ocaml rustboot compiler and then rebuild it countless times throughout rustc history.... also the ocaml compiler itself builds itself so you'd have to verify it too :). So the trusting trust situation has improved really well thanks to the introduction of mrustc.

Obviously it still can be improved but I think we better spend our time with making the rustc bootstrap more secure by e.g. having multiple instances compile rustc and report back whether they got the same result. Right now rustc bootstrap runs on the travis cloud (with full internet access!) and stuff like the signing keys are iirc not on an hsm but simply in encrypted travis storage. This is fine but can and should be improved, at least for stable releases which only happen very rarely.

**Comment by devrandom** [comment]
@est31 for this approach to be work, I believe a couple of things are required:

- `mrustc` needs to be kept up to date.  Would you say there are enough resources directed at it?
- the output of `rustc` should be deterministic, so that the resulting binaries can be compared

**Comment by est31** [comment]
IIRC @thepowersgang was able to regenerate rustc using mrustc so apparently rustc is deterministic enough for that. mrustc is a hobbyist project. Obviously you should direct more resources at it, but you should direct more resources to so many rust related things...

Even if mrustc isn't kept up to date it was already hugely beneficial like I've said above.

**Comment by devrandom** [comment]
mrustc is definitely very useful, especially for creating a trusted rustc binary.  However, this takes several hours.  Also, in my tests I saw large swathes of resulting binary changing between builds of rustc (even when using `diffoscope`), so this doesn't help validate the official binaries.  I understand that you can try to tighten the travis build system, but it's still a single point of failure.

The lack of deterministic output is also problematic when distributing compiled binaries for projects written in Rust, if one wishes multiple independent builds to be comparable.

The Debian project is aiming for 100% reproducible builds to eliminate these single points of failure - it would be good for any compiled language to assist in this.

**Comment by devrandom** [comment]
https://wiki.debian.org/ReproducibleBuilds

**Comment by est31** [comment]
Please share relevant details about issues with determinism in issue #34902 .

**Comment by Manishearth** [comment]
This is a known issue; the fix includes:

 - existing work on mrustc (it already can compile rustc, just doesn't pass the entire testsuite yet)
 - existing work on [a gcc frontend](https://users.rust-lang.org/t/rust-front-end-to-gcc/11601/6)
 - [reproducible builds](https://users.rust-lang.org/t/testing-out-reproducible-builds/9758)

The Rust project itself does not have the bandwidth to work on a completely different compiler.

**Comment by kapouer** [comment]
Does https://blog.antoyo.xyz/rustc_codegen_gcc-progress-report-10 means the missing piece is almost done ?
