### ISSUE TITLE
`extern crate` epoch lint for Path Clarity RFC (2126)

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#48719]
We need to add an epoch lint for [RFC 2126](https://github.com/rust-lang/rfcs/blob/master/text/2126-path-clarity.md)

It will lint `extern crate foobar;`, suggesting removal in root mods, and replacement with `use foobar;` in non-root mods.

This is blocked on the ability to elide extern crate in the first place.

**Comment by est31** [comment]
It is also blocked on a feature to force linkage of a crate, see this comment and the discussion afterwards: https://github.com/rust-lang/rust/issues/44660#issuecomment-370205734

**Comment by Manishearth** [comment]
cc @cramertj

**Comment by golddranks** [comment]
I think the lint should be by default off in cases with `macro_use`, such as:

```
#[macro_use] extern crate slog;
```

This is because of the ergonomic problems with `macro_rules!` macros and the new macro import system, expressed here: https://internals.rust-lang.org/t/help-stabilize-a-subset-of-macros-2-0/7252/18?u=golddranks

It's bewildering for the migrating users if a lint tells them not to use the `extern crate` syntax, but then finding out that many of the macros out there have downright bad ergonomics with the `use` import syntax.

**Comment by alexreg** [comment]
I don't think we want `extern crate` at all, really. If we want to import macros, we should have another means of doing it. Otherwise we have an inconsistency.

**Comment by est31** [comment]
@golddranks @alexreg I've discussed this a bit in the tracking issue for the macros import system: https://github.com/rust-lang/rust/issues/35896#issuecomment-342939775

**Comment by golddranks** [comment]
@est31 Thanks, you expressed the exact concern I had in a concise way.

**Comment by Manishearth** [comment]
Another thing this needs to lint is unlisted crates that are included in Cargo.toml that clash with existing modules.


I'm not quite sure on what the story needs to be here cc @rust-lang/lang

**Comment by est31** [comment]
Does it? I've thought one of the things the path clarity RFC was about was to have separate namespaces for top level modules and extern crates.

**Comment by Manishearth** [comment]
The current plan has changed a bit so I'm not sure if that is still true.

(If stuff does change it will probably be RFCd again, there's a bit of experimentation going on)

**Comment by est31** [comment]
Sigh I hope we won't discuss all of this crap all over again... I don't enjoy that but it is not me who wants to change things.

**Comment by aturon** [comment]
@est31 I've hidden your last comment, which I found hostile and unconstructive.

**Comment by Manishearth** [comment]
That's mostly the latest state of consensus, yeah. Some tweaks have been made iirc.

Everything has been implemented.
