### ISSUE TITLE
Unnecessary parentheses around argument lint

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#48717]
**This is likely going to be closed as expected breakage. This means those cc-ed below should probably aim to fix their crate and release a new point release.**

Due to https://github.com/rust-lang/rust/pull/46980.

 - [cargo 0.24.0](http://cargobomb-reports.s3.amazonaws.com/stable-1.24.0-beta-1.25.0-beta.2/beta-2018-02-20/reg/cargo-0.24.0/log.txt) cc @alexcrichton 
 - [alga 0.5.2](https://crates.io/crates/alga/0.5.2) (fixed on alga master, not yet released, cc @sebcrozet)
 - [fluxcap 0.0.5](http://cargobomb-reports.s3.amazonaws.com/stable-1.24.0-beta-1.25.0-beta.2/beta-2018-02-20/reg/fluxcap-0.0.5/log.txt) cc @rodolf0
 - [hdrhistogram 6.0.3](http://cargobomb-reports.s3.amazonaws.com/stable-1.24.0-beta-1.25.0-beta.2/beta-2018-02-20/reg/hdrhistogram-6.0.3/log.txt) cc @jonhoo
 - [hdrsample 6.0.2](http://cargobomb-reports.s3.amazonaws.com/stable-1.24.0-beta-1.25.0-beta.2/beta-2018-02-20/reg/hdrsample-6.0.2/log.txt) cc @jonhoo
 - [matrixgraph 0.1.0](http://cargobomb-reports.s3.amazonaws.com/stable-1.24.0-beta-1.25.0-beta.2/beta-2018-02-20/reg/matrixgraph-0.1.0/log.txt) cc @equescalculi
 - [nalgebra 0.13.1](http://cargobomb-reports.s3.amazonaws.com/stable-1.24.0-beta-1.25.0-beta.2/beta-2018-02-20/reg/nalgebra-0.13.1/log.txt) cc @sebcrozet
 - [ncollide_geometry 0.1.1](http://cargobomb-reports.s3.amazonaws.com/stable-1.24.0-beta-1.25.0-beta.2/beta-2018-02-20/reg/ncollide_geometry-0.1.1/log.txt) cc @sebcrozet 
 - [ncollide_queries 0.3.2](http://cargobomb-reports.s3.amazonaws.com/stable-1.24.0-beta-1.25.0-beta.2/beta-2018-02-20/reg/ncollide_queries-0.3.2/log.txt)  cc @sebcrozet 
 - [ncollide_queries 0.4.0](http://cargobomb-reports.s3.amazonaws.com/stable-1.24.0-beta-1.25.0-beta.2/beta-2018-02-20/reg/ncollide_queries-0.4.0/log.txt)  cc @sebcrozet 
 - [pipeline 0.5.0](http://cargobomb-reports.s3.amazonaws.com/stable-1.24.0-beta-1.25.0-beta.2/beta-2018-02-20/reg/pipeline-0.5.0/log.txt) cc @johannhof
 - [rust_sodium-sys 0.7.2](http://cargobomb-reports.s3.amazonaws.com/stable-1.24.0-beta-1.25.0-beta.2/beta-2018-02-20/reg/rust_sodium-sys-0.7.2/log.txt) cc @dirvine @Viv-Rajkumar

Estimated ecosystem breakage: 3603 versions (4.41% versions published), 551 crates (3.85% of crates). Though technically most/all of this will be fine because of cap lints.

**Comment by jonhoo** [comment]
`hdrsample` is a deprecated crate that has been entirely replaced by `hdrhistogram`. I don't know what the policy on such crates is? Some users are still using older versions of it under the old name, and I'd rather not have it be deleted. But it also seems unfortunate to have a crate on crates.io that doesn't compile... I'll issue a point release to the deprecated crate that fixes it, but it'd be unfortunate if I had to continue ensuring that it compiles in perpetuity.

**Comment by Mark-Simulacrum** [comment]
To be clear, this shouldn't cause downstream crates to not compile -- lint warnings are capped so that while people compiling hdrsample directly won't be able to do so, without code changes, everything should work for people depending on hdrsample.

**Comment by Mark-Simulacrum** [comment]
I'm going to go ahead and close this as we don't expect to have any further activity on the compiler's side.
