### ISSUE TITLE
json-job-dispatch-1.1.2 test fail regression

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#48713]
[json-job-dispatch 1.1.2](https://crates.io/crates/json-job-dispatch/1.1.2) fails tests on beta

```
Mar 01 17:33:46.483 INFO blam! ---- test::test_fail stdout ----
Mar 01 17:33:46.483 INFO blam! 	[INFO] setting up a director in /target/debug/deps/test_fail.yDJkCNo3lhQv
Mar 01 17:33:46.483 INFO blam! [DEBUG] adding handler 'accept'
Mar 01 17:33:46.483 INFO blam! [DEBUG] adding handler 'defer'
Mar 01 17:33:46.483 INFO blam! [DEBUG] adding handler 'reject'
Mar 01 17:33:46.483 INFO blam! [DEBUG] adding handler 'fail'
Mar 01 17:33:46.483 INFO blam! [DEBUG] adding handler 'restart'
Mar 01 17:33:46.483 INFO blam! [DEBUG] adding handler 'done'
Mar 01 17:33:46.483 INFO blam! [DEBUG] adding handler 'error'
Mar 01 17:33:46.484 INFO blam! [DEBUG] failed /target/debug/deps/test_fail.yDJkCNo3lhQv/0-fail.json: Custom { kind: Other, error: StringError("fail") }
Mar 01 17:33:46.484 INFO blam! [INFO] completed via 1-done.json
Mar 01 17:33:46.484 INFO blam! thread 'test::test_fail' panicked at 'assertion failed: `(left == right)`
Mar 01 17:33:46.484 INFO blam!   left: `["Custom { kind: Other, error: StringError(\"fail\") }\n"]`,
Mar 01 17:33:46.484 INFO blam!  right: `["Error { repr: Custom(Custom { kind: Other, error: StringError(\"fail\") }) }\n"]`', src/test.rs:116:5
```

full log: http://cargobomb-reports.s3.amazonaws.com/stable-1.24.0-beta-1.25.0-beta.2/beta-2018-02-20/reg/json-job-dispatch-1.1.2/log.txt

cc @bradking

**Comment by bradking** [comment]
Cc: @mathstuf

**Comment by mathstuf** [comment]
We're testing against the `Debug` output of `io::Error` when output via a `Box<Error>`. Did this change somewhere?

**Comment by mathstuf** [comment]
And should it be considered stable? I'm guessing we're also not robust against running under various values of `RUST_BACKTRACE`.

**Comment by mathstuf** [comment]
I'm seeing 52e074e40ee3eaf04415b2044c93bcfddad52f35 from #47120.

**Comment by mathstuf** [comment]
Fixed in `json-job-dispatch` [in this merge request](https://gitlab.kitware.com/utils/rust-json-job-dispatch/merge_requests/40).

**Comment by dtolnay** [comment]
Debug impls are intended for debugging so we make no guarantees about what they look like. This has been fixed in json-job-dispatch so I think we can close.
