### ISSUE TITLE
Component AsRef change causes beta regression

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#48716]
**This is probably going to be closed as expected breakage. This means those cc-ed below should probably aim to fix their crate and release a new point release.**

https://github.com/rust-lang/rust/pull/46985 added an impl of `AsRef<Path> for Component` which causes these crates to stop compiling:

 - [artifact-app 1.1.0-beta001](https://crates.io/crates/artifact-app/1.1.0-beta001) https://github.com/rust-lang/rust/issues/47466 cc @vitiral
 - [app_dirs 1.1.1](https://github.com/rust-lang/rust/issues/47466) (https://github.com/AndyBarron/app-dirs-rs/issues/28) https://github.com/rust-lang/rust/issues/47480 cc @AndyBarron
 - [gutenberg 0.0.7](https://crates.io/crates/gutenberg/0.0.7) [log](http://cargobomb-reports.s3.amazonaws.com/stable-1.24.0-beta-1.25.0-beta.2/beta-2018-02-20/reg/gutenberg-0.0.7/log.txt) cc @Keats
 - [rst_app 0.3.7](http://cargobomb-reports.s3.amazonaws.com/stable-1.24.0-beta-1.25.0-beta.2/beta-2018-02-20/reg/rst_app-0.3.7/log.txt) cc @vitiral
 - [second_law 0.2.2 and 0.3.1](http://cargobomb-reports.s3.amazonaws.com/stable-1.24.0-beta-1.25.0-beta.2/beta-2018-02-20/reg/second_law-0.3.1/log.txt) cc @nathanross
 - [tack-it-on 1.0.1](http://cargobomb-reports.s3.amazonaws.com/stable-1.24.0-beta-1.25.0-beta.2/beta-2018-02-20/reg/tack-it-on-1.0.1/log.txt) cc @ChrisWellsWood
 - [tango 0.6.2 and 0.8.1](http://cargobomb-reports.s3.amazonaws.com/stable-1.24.0-beta-1.25.0-beta.2/beta-2018-02-20/reg/tango-0.6.2/log.txt) cc @pnkfelix 
- [yabs 0.2.1](http://cargobomb-reports.s3.amazonaws.com/stable-1.24.0-beta-1.25.0-beta.2/beta-2018-02-20/reg/yabs-0.2.1/log.txt) cc @0X1A
 - [Redrield/kobalt-updater @ 6cd602b7ccf16336c8acc1c4d808b37152c648f7](http://cargobomb-reports.s3.amazonaws.com/stable-1.24.0-beta-1.25.0-beta.2/beta-2018-02-20/gh/Redrield.kobalt-updater.6cd602b7ccf16336c8acc1c4d808b37152c648f7/log.txt) cc @Redrield
 - [vitiral/artifact @ ed4d744c67d8a7ed41c202b0ac81e2ae2720b3fb](http://cargobomb-reports.s3.amazonaws.com/stable-1.24.0-beta-1.25.0-beta.2/beta-2018-02-20/gh/vitiral.artifact.ed4d744c67d8a7ed41c202b0ac81e2ae2720b3fb/log.txt) cc @vitiral 

Estimated ecosystem breakage: 143 versions (0.18% of versions published), 39 crates (0.27% of crates).

cc @rust-lang/libs

**Comment by PlasmaPower** [comment]
Unfortunately app_dirs is no longer maintained, with no good replacement that I can find.

**Comment by vitiral** [comment]
For crates that are no longer maintained what is the right course of action here? For instance `rst_app` is just the previous name of `artifact_app` so I have no intention of fixing it. Should I yank it?

**Comment by carols10cents** [comment]
@vitiral You could put `maintenance = { status = "deprecated" }` in the Cargo.toml of `rst_app`, and possibly mention that it was renamed to `artifact_app` in `rst_app`'s `description`.

**Comment by alexcrichton** [comment]
This was discussed during the libs triage meeting recently and we decided that we're not going to revert this, but if any crates need assistance updating we're more than happy to help!

**Comment by alexcrichton** [comment]
Closing due to previous comment

**Comment by PlasmaPower** [comment]
For anyone looking for a replacement, try `app_dirs2` or `directories`.

**Comment by pravic** [comment]
#46985 is in relnotes, but this issue wasn't mentioned at all despite of the compatibility breakage (not to mention promised compatability guaranties).

cc @steveklabnik
