### ISSUE TITLE
UnsafeCell::into_inner is safe regressions

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#48718]
**This is likely going to be closed as expected breakage. This means those cc-ed below should probably aim to fix their crate and release a new point release.**

Caused by https://github.com/rust-lang/rust/pull/47204.

 - [oncemutex 0.1.1](http://cargobomb-reports.s3.amazonaws.com/stable-1.24.0-beta-1.25.0-beta.2/beta-2018-02-20/reg/oncemutex-0.1.1/log.txt) cc @reem
 - [shared-mutex 0.3.1](http://cargobomb-reports.s3.amazonaws.com/stable-1.24.0-beta-1.25.0-beta.2/beta-2018-02-20/reg/shared-mutex-0.3.1/log.txt) cc @reem

Estimated breakage: 43 versions (0.05% versions); 11 crates (0.08% crates).

**Comment by sfackler** [comment]
Those are just lint failures so it won't prevent anyone from depending on those crates, fortunately.

**Comment by alexcrichton** [comment]
I'm going to close this as we don't typically back things out due to lint changes and otherwise the impact here looks relatively small
