### ISSUE TITLE
Tracking issue for the unreachable_pub compatibility lint

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#48721]
In Rust 2018, we will deprecate code that is `pub` but not crate-reachable, requiring `pub(crate)` instead.

If you see this warning, just replace the relevant line with `pub(crate)`

**Comment by zackmdavis** [comment]
Does this just mean that the unreachable-pub lint will become default-Warn (it's [currently default-Allow](https://github.com/rust-lang/rust/blob/259e4a67843d5fbe6761a5e442836d7109d72cbe/src/librustc_lint/builtin.rs#L1338-L1339)), or is something stronger intended?

Is stabilization of the `crate` visibility modifier (synonymous to `pub(crate)`) potentially relevant here? (The lint will [already suggest `crate` or `pub(crate)` depending](https://github.com/rust-lang/rust/blob/259e4a67843d5fbe6761a5e442836d7109d72cbe/src/librustc_lint/builtin.rs#L1359-L1363) on the `crate_visibility_modifier` feature flag, but if "non-crate-reachable code isn't `pub`" is something to teach/sell as part of "Rust 2018", maybe the new keyword use is, too.)

**Comment by zackmdavis** [comment]
There is one outstanding bug report for the lint: #47816

**Comment by Manishearth** [comment]
I'm not sure. I think it will be allow for now but may become warn later, regardless of the epoch you're on. @withoutboats  may know.


I filed this issue so the lint can be marked an epoch-related lint (you need a tracking issue), there's not much more to infer from that.

**Comment by withoutboats** [comment]
> I think it will be allow for now but may become warn later, regardless of the epoch you're on. @withoutboats may know.

We're not sure.

**Comment by Manishearth** [comment]
This lint isn't actually  a future compat lint, closing the tracking issue.
