### ISSUE TITLE
&str should have split_first

### ISSUE THREAD

**Issue by SoniEx2** [rust-lang/rust#48731]
string slices should have a split_first, just like array slices.

returns -> (char, &str)

**Comment by kennytm** [comment]
This function was called `slice_shift_char` but it was [removed](https://github.com/rust-lang/rust/issues/27754#issuecomment-195478632) because you could do this instead:

```rust
fn slice_shift_char(a: &str) -> Option<(char, &str)> {
    let mut chars = a.chars();
    chars.next().map(|c| (c, chars.as_str()))
}

fn main() {
    assert_eq!(slice_shift_char("hello"), Some(('h', "ello")));
    assert_eq!(slice_shift_char("ĺḿńóṕ"), Some(('ĺ', "ḿńóṕ")));
    assert_eq!(slice_shift_char(""), None);
}
```

**Comment by steveklabnik** [comment]
We don't keep bugs open for small feature requests for libraries like this; big things need an RFC, small things can be PR'd. Thanks!

**Comment by Stargateur** [comment]
> 
> 
> This function was called `slice_shift_char` but it was [removed](https://github.com/rust-lang/rust/issues/27754#issuecomment-195478632) because you could do this instead:
> 
> ```rust
> fn slice_shift_char(a: &str) -> Option<(char, &str)> {
>     let mut chars = a.chars();
>     chars.next().map(|c| (c, chars.as_str()))
> }
> 
> fn main() {
>     assert_eq!(slice_shift_char("hello"), Some(('h', "ello")));
>     assert_eq!(slice_shift_char("ĺḿńóṕ"), Some(('ĺ', "ḿńóṕ")));
>     assert_eq!(slice_shift_char(""), None);
> }
> ```

I don't feel it's a good reason. The same reasoning could be say about slice.

**Comment by kennytm** [comment]
There isn't a `slice` method in `str`

**Comment by Stargateur** [comment]
@kennytm One could say the same for slice `split_first()`:

```rust
fn slice_shift_slice(a: &[u8]) -> Option<(u8, &[u8])> {
    let mut iter = a.iter();
    iter.next().map(|&n| (n, iter.as_slice()))
}
```

**Comment by kennytm** [comment]
`slice::split_first` has been stabilized 1.5.0. We can't retroactively destabilize a std method now even if better alternative exists.

```rust
fn split_first<T>(a: &[T]) -> Option<(&T, &[T])> {
    match a {
        [head, tail @ ..] => Some((head, tail)),
        [] => None,
    }
}
```

Meanwhile `str::slice_shift_char` was considered redundant before 1.0.0 was released, so we could remove it without the stabilization guarantee.

I was just explaining the decision made ~&nbsp;2&nbsp;~ 5 years ago. If you would like to bring back `str::split_first_char`, quoting Steve above,

> small things can be PR'd. Thanks!

**Comment by Stargateur** [comment]
I know all that, I just explain your argument could work the same for have refused `split_first()`.
