### ISSUE TITLE
rustdoc -- sidebar doesn't work in function documentation

### ISSUE THREAD

**Issue by onur** [rust-lang/rust#48733]
Sidebar is entirely empty and getting an error in console:

TypeError: sidebar is undefined [main.js:1497:13](https://github.com/rust-lang/rust/blob/1e1bfc715f8dfe36a38d8fae36fcbe92e7463a3f/src/librustdoc/html/static/main.js#L1497)

![ss](https://user-images.githubusercontent.com/345828/36948179-c9a18ece-1fe7-11e8-822a-267306f07358.png)

**Comment by onur** [comment]
@steveklabnik 

Firefox 58, rustc 1.26.0-nightly (322d7f7b9 2018-02-25) and rustc 1.26.0-nightly (3b8bd530b0 2018-03-03) and my docs.rs build rustc 1.26.0-dev (5c1d29af0 2018-03-03)

This issue affects function documentation of any crate.

**Comment by GuillaumeGomez** [comment]
I think it comes from `<script defer="" src="sidebar-items.js"></script>`. Seems weird to have a path like this. I'll check what's wrong.
