### ISSUE TITLE
save-analysis: inferred crates are not included

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#48742]
save-analysis includes crates declared with `extern crate` or in the implicit prelude, but does not include those inferred from imports due to the new `extern crate` elision feature. I assume because `extern_crate` on the tcx does not include info for those crates (see https://github.com/rust-lang/rust/blob/master/src/librustc_save_analysis/lib.rs#L113).

This is the root cause for part of https://github.com/rust-lang-nursery/rls/issues/729

**Comment by nrc** [comment]
ping @petrochenkov @rust-lang/compiler - anyone got advice on how to address this issue?

**Comment by sinkuu** [comment]
https://github.com/rust-lang/rust/compare/master...sinkuu:save_analysis_implicit_extern
I'd like to make a PR unless @petrochenkov has already been working on this.

**Comment by petrochenkov** [comment]
@sinkuu 
Thanks for fixing this issue, I never got to it.
