### ISSUE TITLE
Rustc no longer builds for msvc 17

### ISSUE THREAD

**Issue by snf** [rust-lang/rust#48749]
It appears to be since this commit yesterday: https://github.com/rust-lang/rust/commit/d69b24805b5071e5ec9e62d2777a761723644144#diff-9a46b13a265be2ded97369dddf5037f5

@alexcrichton can you have a look at it?, discussing in IRC, it seems that changing the line 88 back from "build/bin" to only "bin" does the work.

**Comment by alexcrichton** [comment]
@snf can you provide more logs for this build?

**Comment by ollie27** [comment]
https://pastebin.mozilla.org/9079141 was the log posted on IRC. The issue is that when using MSBuild as the cmake generator `llvm-config.exe` is located in `llvm\bin\llvm-config.exe` and `llvm\build\Release\bin\llvm-config.exe` not `llvm\build\bin\llvm-config.exe`.

**Comment by retep998** [comment]
Also please never hardcode `/` in paths. That should be `dir.join("build").join("bin");` due to certain conditions where `/` is treated as a literal character and not a path separator, such as `\\?\` paths.

**Comment by alexcrichton** [comment]
Ah thanks @ollie27! Yes I can look into fixing this.
