### ISSUE TITLE
Using same label name in seemingly non-shadowing context generates warning

### ISSUE THREAD

**Issue by milesand** [rust-lang/rust#48764]
The following code:
```
fn main() {
    'a: loop {break;}
    'a: loop {break;}
}
```

generates the following warning:
```
warning: label name `'a` shadows a label name that is already in scope
 --> file_name.rs:3:5
  |
2 |     'a: loop {break;}
  |     -- first declared here
3 |     'a: loop {break;}
  |     ^^ lifetime 'a already in scope
```

As it is impossible to meaningfully use (as in `break 'a`) the `'a` of the first loop from the second loop, the warning seems rather redundant.

**Comment by petrochenkov** [comment]
This was supposed to be a future-proofing measure, see https://github.com/rust-lang/rust/pull/24162 / https://github.com/rust-lang/rust/issues/24278.
