### ISSUE TITLE
rustdoc book

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#48780]
Anchors go under the titlebar when clicked upon.

cc @rust-lang/docs

**Comment by Songbird0** [comment]
I wasn't able to reproduce the problem. Which anchors have this bug?

![anchortest](https://user-images.githubusercontent.com/13397428/37477221-623756cc-2877-11e8-8bdc-9cbc7df608c4.gif)

Firefox version: `61.0a1 (2018-03-14) (64 bits)`

**Comment by GuillaumeGomez** [comment]
That's because I fixed the bug in mdBook since I opened this issue. It can be closed. ;)
