### ISSUE TITLE
refactor the `BorrowckErrors` trait to take `fn(self)`

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#48783]
The [`BorrowckErrors` trait] is used to report errors from both HIR and MIR-based borrowck:

https://github.com/rust-lang/rust/blob/c9334404f06a188854af33835a0efe1e834e4ac4/src/librustc_mir/util/borrowck_errors.rs#L55

It contains various methods currently defined to take `&self`:

https://github.com/rust-lang/rust/blob/c9334404f06a188854af33835a0efe1e834e4ac4/src/librustc_mir/util/borrowck_errors.rs#L77-L84

However, it is implemented on the `TyCtxt` type:

https://github.com/rust-lang/rust/blob/c9334404f06a188854af33835a0efe1e834e4ac4/src/librustc_mir/util/borrowck_errors.rs#L494

This type is actually an alias for an `&`-reference, so that means that the final `self` winds up passing a double reference. This is not bad in and of itself, but @spastorino encountered in https://github.com/rust-lang/rust/pull/48682 that the current setup causes conflicts around the tcx when using an `&mut` self method. In particular, if you do something like this:

```rust
let err = self.tcx.cannot_use_while_mutably_borrowed(...);
..
```

this will borrow `&self.tcx` for as long as `err` is in use, preventing us from invoking other `&mut self` methods.

For now, we worked around this problem by storing the `tcx` into a local variable:

```rust
let tcx = self.tcx;
```

But if the methods were defined instead as `fn(self)`, then it would have worked fine the original way.

Making this transformation would involve a few changes though. First off, right now the returned `DiagnosticBuilder` values carry the lifetime of the incoming `&self` reference. We would want to change that to the lifetime of the `TyCtxt`, so we would need to modify the trait to carry a lifetime parameter:

```rust
/// This trait is expected to be implemented on a reference.
/// The `'r` is the lifetime of that reference.
trait BorrowckErrors<'cx> {
    ...
    fn cannot_use_when_mutably_borrowed(
        self, // changed to self
        span: Span,
        ...
    ) -> DiagnosticBuilder<'cx> {
        ... // as before
    }
    ...
}
```

Then it would be implememented for `TyCtxt` like:

```rust
impl<'cx, 'gcx, 'tcx> BorrowckErrors<'cx> for TyCtxt<'cx, 'gcx, 'tcx> { ... }
```

And we would have to modify the [other impl](https://github.com/rust-lang/rust/blob/c9334404f06a188854af33835a0efe1e834e4ac4/src/librustc_borrowck/borrowck/mod.rs#L256) like so:

```rust
impl<'a, b, 'tcx: 'b> BorrowckErrors<'a> for &'a BorrowckCtxt<'b, 'tcx> {
```

**Comment by nikomatsakis** [comment]
cc @rust-lang/wg-compiler-nll -- little refactoring issue related to NLL, contains mentoring instructions

**Comment by csmoe** [comment]
I'll try this.

**Comment by nikomatsakis** [comment]
@csmoe but of course! (I can also add you to the NLL WG)
