### ISSUE TITLE
inline asm jmp 'invalid operand for instruction'

### ISSUE THREAD

**Issue by aasosaa** [rust-lang/rust#48797]
Rust nightly version `2018-02-11` broke some inline assembly in code that previously worked. 
Specifically, the jmp instruction on x86_64 doesn't work as it has before.

A minimum example to reproduce is that 
```

fn foo(bytes: &[u8]) -> u32 {
    let result: u32;
    unsafe {
        asm!(
            "
           1:
	      jmp 1b

           "
            : "={ax}"(result)                         // Output register
            : "r"(bytes.as_ptr()), "r"(bytes.len())   // Input registers
            : "rax"                                        // Clobbered registers
            : "intel", "volatile"                     // Options (intel syntax, don't optimize out)
        );
    }
    result
}

```

now fails to compile with error:
`error: <inline asm>:5:2: error: invalid operand for instruction
        jmp 1b
`
The code snippet above compiles with `rust-nightly-x86_64-unknown-linux-gnu nightly 2018-02-10 `and earlier, but returns an error on `nightly 2018-02-11` and beyond. I tried looking through the commits that happened that day but couldn't find the exact source of the issue.

**Comment by parched** [comment]
The will have been the upgrade to LLVM 6.

**Comment by parched** [comment]
Try again once [the LLVM 6 fixes](https://github.com/rust-lang/rust/pull/48782) are in, but I can't see an obvious fix for this.

**Comment by paoloteti** [comment]
Your example compile without errors on `nightly 2018-03-05`

**Comment by aasosaa** [comment]
No I tried 2018-03-05 and it failed with same error. 

rust from `https://static.rust-lang.org/dist/2018-03-05/rust-nightly-x86_64-unknown-linux-gnu.tar.gz`

command:
```
LD_LIBRARY_PATH=path/rust_linux_x86_64/rustc/lib DYLD_LIBRARY_PATH=path/rust_linux_x86_64/rustc/lib HOST=x86_64-unknown-linux-gnu TARGET=x86_64-unknown-linux-gnu path/rust_linux_x86_64/rustc/bin/rustc src/lib.rs --crate-name crate_name --crate-type lib -L all=path/rust_linux_x86_64/rust-std-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib -C panic=abort

```

**Comment by paoloteti** [comment]
Yes sorry I was wrong, I mixed up open terminals. BTW this issue looks like: [https://bugs.llvm.org/show_bug.cgi?id=36144](https://bugs.llvm.org/show_bug.cgi?id=36144).

So you can't use `1` or `0` as local labels.  Changing label to `5:  jmp 5b` the issue disappear.

**Comment by aasosaa** [comment]
Great, thanks for finding that! Fixes the issue.
