### ISSUE TITLE
Provide a way to distinguish between "breakage" and "idiom" epoch lints?

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#48796]
Currently there's an `epoch_2018` lint group which contains (will contain) all the lints that relate to the 2018 epoch.

However, there are [two kinds of epoch lints](https://github.com/rust-lang/rust/issues/48790#issuecomment-370939250): There's the "this is going to break please fix" kind, and there's the "this is now idiomatic in the new epoch, try it!" kind. Most likely for the 2018 epoch the former will only be the keyword lint, and all the other lints will be idiom lints.

I wonder if we should be providing a lint group for just the "breaking change" lints as well, so that people can get code _working_ on the new epoch easily (running tons of lints increases the chance of cases where e.g. two lints try to modify the same area of code, so only one works -- we can't completely automate rustfix when there's a high concentration of lints).

Having lints in multiple groups is a bit broken in rustc IIRC so we may need to be careful about this.

On a related note, we may need a way to say `-Awarnings -Wepoch_2018` -- currently `-Awarnings` turns off all warnings period, and cannot be overridden (you can do `-Depoch_2018` to make those lints work)

cc @nikomatsakis

**Comment by nikomatsakis** [comment]
> Most likely for the 2018 epoch the former will only be the keyword lint

Nit: Also the https://github.com/rust-lang/rust/issues/46906 lint I suppose, maybe a few other minor things.

**Comment by Manishearth** [comment]
I decided to make bare_trait_object and unreachable_pub be regular lints -- we should put them under a separate lint group if we wish (rust2018_idioms perhaps). Thoughts?

The epoch lint functionality will be restricted to things like tyvar_behind_raw_pointer and keyword lints

**Comment by Manishearth** [comment]
https://github.com/rust-lang/rust/pull/48801
