### ISSUE TITLE
lint for `catch` used as identifier

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#48791]
In the new epoch, we would like to reserve the `catch` keyword for future use. Therefore, we should add a lint that `catch` is going to be a reserved keyword in the future.

**Comment by scottmcm** [comment]
Others that may or may not be part of this: https://internals.rust-lang.org/t/keywords-to-reserve-for-rust2018-epoch/6720

**Comment by nikomatsakis** [comment]
Yep, I plan to go through and vet that list, opening issues where appropriate.

**Comment by Centril** [comment]
Closing this and tracking a possible lint for `try` at https://github.com/rust-lang/rust/issues/50412
