### ISSUE TITLE
Tests should only be run for stages they are supported on

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#48800]
Some tests, for example `run-pass/discrim-explicit-23030.rs`, fail for `--stage 1` (i.e. require stage 2 to pass). This is confusing, as they are run regardless of the stage and there is no diagnostic message suggesting this is the case. There should either be a note for such tests that they are expected to fail on lower stages, or (preferably) they should not be run unless they are expected to succeed.

**Comment by oli-obk** [comment]
you can ignore them on stage1 by adding

```
// ignore-stage1
```

We can't detect this problem automatically I think, so just marking them with this comment should solve the issue.

We could of course still run all `// ignore-stage1` tests to find those that should not have the comment (anymore), but ignore it if they fail

**Comment by varkor** [comment]
Yeah, it'd be a good idea to go through all the tests and redetermine exactly which require the flag now, as they don't seem to be up-to-date.

**Comment by jonas-schievink** [comment]
Stage 1 tests are quite reliable now, so closing.
