### ISSUE TITLE
Converting "&'a &'b T" to "&'a T" in the presence of non-lexical lifetimes can be unsound

### ISSUE THREAD

**Issue by SelectricSimian** [rust-lang/rust#48803]
The following snippet should be rejected for allowing a value to be mutated while it is borrowed, but it is accepted on nightly when non-lexical lifetimes are enabled ([playground](https://play.rust-lang.org/?gist=270115299b6bbf2849930abe1e745f21&version=nightly)):

```rust
#![feature(nll)]

fn flatten<'a, 'b, T>(x: &'a &'b T) -> &'a T {
    x
}

fn main() {
    let mut x = "original";
    let y = &x;
    let z = &y;
    let w = flatten(z);
    x = "modified";
    println!("{}", w); // prints "modified"
}
```

**Comment by pnkfelix** [comment]
(assigning to @nikomatsakis to write up mentoring instructions, or potentially fix outright)

**Comment by nikomatsakis** [comment]
I discussed the problem with @spastorino in gitter the other day:

https://gitter.im/rust-impl-period/WG-compiler-nll?at=5ace0ee101a2b40f382ead12

**Comment by nikomatsakis** [comment]
As I pointed out in gitter, this is the point where we instantiate the late-bound regions in the signature:

https://github.com/rust-lang/rust/blob/ca26ef321c44358404ef788d315c4557eb015fb2/src/librustc_mir/borrow_check/nll/type_check/mod.rs#L890-L895

That variable `sig` will be a [`FnSig`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ty/struct.FnSig.html). Much like the [AST-based type checker code](https://github.com/rust-lang/rust/blob/ca26ef321c44358404ef788d315c4557eb015fb2/src/librustc_typeck/check/mod.rs#L2527-L2529), we need to iterate through the inputs and prove their types are well-formed. I imagine something like:

```rust
self.prove_predicates(
  sig.inputs().iter().map(|ty| ty::PredicateWellFormed(ty))
);
```
