### ISSUE TITLE
Failed to download and compile rand

### ISSUE THREAD

**Issue by Tripton** [rust-lang/rust#48817]
I tryed to follow the guessing game example of the online book "The Rust Programming Language".
It compiles until I add " rand = "0.4.0" " to the Cargo.toml.

I tried this code:
[dependencies]
rand = "0.4.0"

I expected to see this happen:
Download and compile rand

Instead, this happened:
error: internal compiler error: unexpected panic

rustc 1.24.1 (d3ae9a9e0 2018-02-27)
binary: rustc
commit-hash: d3ae9a9e08edf12de0ed82af57ba2a56c26496ea
commit-date: 2018-02-27
host: x86_64-pc-windows-msvc
release: 1.24.1
LLVM version: 4.0

**Comment by Tripton** [comment]
After deleting the "target" folder and the Cargo.lock it now works

**Comment by Centril** [comment]
Do you by any chance have the backtrace from the ICE so that the error can be reproduced?

**Comment by Centril** [comment]
Nominating with a suggestion to close since nothing has happened since 2018.
