### ISSUE TITLE
Collect CPU utilization statistics of CI builders

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#48828]
One of the easiest ways to make CI faster is to make things parallel and simply use the hardware we have available to us. Unfortunately though we don't have a lot of data about how parallel our build is. Are there steps we think are parallel but actually aren't? Are we pegged to one core for long durations when there's other work we could be doing?

The general idea here is that we'd spin up a daemon at the very start of the build which would sample CPU utilization every so often. This daemon would then update a file that's either displayed or uploaded at the end of the build.

Hopefully we could then use these logs to get a better view into how the builders are working during the build, diagnose non-parallel portions of the build, and implement fixes to use all the cpus we've got.

cc @rust-lang/infra

**Comment by matthiaskrgr** [comment]
I made script that will print ````top```` output into the travis log every 30 seconds [log](https://travis-ci.org/rust-lang/rust/builds/350827434) , [raw log](https://api.travis-ci.org/v3/job/350827435/log.txt) .

Some findings:

Cloning submodules jemalloc, libcompiler_buildtins and liblibc alone takes 30 seconds.

While building bootstrap, compiling serde_derive, serde_json and bootstrap crates seems to take 30 seconds (total build time: 47 seconds).

stage0:
Compiling tidy crate seems to take around 30 seconds.
Compiling rustc_errors takes at least 2 minutes, only one codegen-unit is used
Compiling syntax_ext takes 9 minutes, only one CGU used

stage0 codegen artifacts:
Compiling rustc_llvm takes 1,5 minutes, one CGU

During stage1, rustc_errors and syntax_ext builds are approximately as slow as during stage0, rustc_plugins 2 minutes, one CGU.

stage2:
rustdoc took 2 minutes to build, one CGU

compiletest suite=run-make mode=run-make: 
It looks like there is a single test that takes around 3 minutes to complete and has no parallelization.

Testing alloc stage1:
building liballoc takes around a minute

Testing syntax stage1:
building syntax takes 1.5 minutes, one CGU


Notes:
When the load average dropped towards 1, I assumed only one codegen unit was active.
The script was only applied to the default pullrequest travis-ci configuration.

**Comment by kennytm** [comment]
As shown in https://github.com/rust-lang/rust/pull/48480#issuecomment-372429268, the CPUs assigned to each job may have some performance difference:

* Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
* Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz

The clock-rate 2.4 GHz vs 2.5 GHz shouldn't make any noticeable difference though (this would at most slow down by 7.2 minutes out of 3 hours if everything is CPU-bound). It is not enough to explain the timeout in #48480.
