### ISSUE TITLE
Provide a way to get the value of a cfg

### ISSUE THREAD

**Issue by vext01** [rust-lang/rust#48823]
Hi,

I ran into the scenario today where my build script needs to communicate the path to a tool to the main rust build:

```
println!("cargo:rustc-cfg=sometool=\"{}/bin/ptxed\"", prefix);
```

But there's no way to get at the value of the configuration. `cfg!` always returns a `bool`!

I was expecting something like `cfg_val!(sometool)` to evaluate to the string value of the cfg.

I also found this:
https://stackoverflow.com/questions/43435072/how-to-obtain-the-value-of-a-configuration-flag

It provides a workaround using `#[include]`, but it's kinda crusty.
Thanks

**Comment by sfackler** [comment]
There's no such thing as the value of a cfg. You can have both `sometool = "foo"` and `sometool = "bar"` defined at the same time. This is how information about Cargo features are provided to crates for example.

If you want to provide a string like that from a build script to a binary, you can instead set it as a build-time environment variable:

```
println!("cargo:rustc-env=SOMETOOL=\"{}/bin/ptxed\"", prefix);
```

```rust
let sometool_path = env!("SOMETOOL");
```

**Comment by vext01** [comment]
I see. That wasn't quite what I expected, but I can live with using the env. Thanks
