### ISSUE TITLE
Keep balancing "split" AppVeyor jobs

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#48844]
@kennytm has done some [amazing analysis](https://github.com/rust-lang/rust/pull/48832#issuecomment-371425526) and it looks like our "split" appveyor jobs for 32-bit tests currently isn't very split but rather still somewhat imbalanced. We should shuffle around some more test suites to balance the load a bit more!

**Comment by alexcrichton** [comment]
cc @rust-lang/infra

**Comment by bjorn3** [comment]
Is this still relevant?

**Comment by Mark-Simulacrum** [comment]
I don't think we need an issue for continuing to balance things, but we do still have some split builders (typically ending in -1, -2).
