### ISSUE TITLE
Type-length limit on Iterator::flat_map nested 5 times and count

### ISSUE THREAD

**Issue by CodeSandwich** [rust-lang/rust#48845]
I've found an issue with type name length explosion when nesting `Iterator::flat_map`s ended with `count`, here's an [example](https://play.rust-lang.org/?gist=01a94651531861fbf7fcad29f14e0210&version=stable). It seems to be a regression, because the same code works on old `nightly-2017-07-07-x86_64-unknown-linux-gnu`.

**Comment by Dylan-DPC** [comment]
This code compiles file now, and there is nothing else mentioned in this issue so I am closing this.
