### ISSUE TITLE
`rustc --explain` message for E0221 out of date

### ISSUE THREAD

**Issue by yodaldevoid** [rust-lang/rust#48865]
The example code contained in the explain message of E0221 is far out of date. As someone who hasn't been around since the dawn of the language I cannot even understand how to convert it into today's syntax.

**Comment by JJJollyjim** [comment]
Hmm, I'm not sure what the issue is here: the example code compiles for me with no errors in a modern `rustc`. Which part of the syntax is out of date?

**Comment by yodaldevoid** [comment]
Looking at it again when it isn't 5 a.m. you are obviously right. I suppose I was more easily confused due to the formatting of `trait Bar : Foo {` and the fact that I did not know it was valid syntax to declare an ignored variable without doing any assignment, as seen with `let _: <Self as Bar>::A;`.
