### ISSUE TITLE
Any way to get details from a struct

### ISSUE THREAD

**Issue by NateLing** [rust-lang/rust#48861]
```rust
struct Demo{
    f1:&'static str,
    f2:i32
}
```
Qustions:

1. how to list all fields from a struct?
2. how to set a struct attribute value with string field name?

Demo example:
```rust
let mut d=Demo{f1:"abc",f2:1};
// just demo
d["f1"] = "efg";
// or
d("f2") ="efg";
```

**Comment by Centril** [comment]
This issue tracker is for tracking the development of the Rust language itself.
If you need help with learning the language, I recommend you to read:
+ https://doc.rust-lang.org/book/first-edition/structs.html
+ https://github.com/ctjhoa/rust-learning

If you have entry level questions, you can ask them at `#rust-beginners @ irc.mozilla.org`.

Regarding your questions:
> how to list all fields from a struct?

There is no language support for this; but you can create custom derive macros and macros in general to approximate this behavior. But I wouldn't recommend it.

> how to set a struct attribute value with string field name?

See the answer above.
