### ISSUE TITLE
add support for "test revisions" into `ui` tester

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#48878]
`ui` tests do not current support revisions. This blocks our goals to [migrate entirely over to unit tests](https://github.com/rust-lang/rust/issues/44844). We should fix it!

I imagine it working like this:

- For each test T with revisions R1..Rn, we would expect N stderr files:
  - `T.Ri.stderr`, where `Ri` is the current revision
- Comments on lines work as normal (`//[Ri]~ ERROR`)

However, it might be useful to permit tests to have a "fallback" `T.stderr` file, in which case the output is supposed to be the same for all revisions.  I am of mixed minds about this though: I don't know how often it would be useful, and I fear "dead stderr files" that are not used. Probably best not to have it.

**Comment by nikomatsakis** [comment]
### Mentoring instructions

Background material is covered in the rustc-guide:

- [Revisions](https://rust-lang-nursery.github.io/rustc-guide/tests/adding.html#revisions)
- [UI tests](https://rust-lang-nursery.github.io/rustc-guide/tests/adding.html#guide-to-the-ui-tests)

The actual revision mechanism is orthogonal to the kind of test, and already exists. In particular, we will parse out the revisions, and when running tests, wind up here:

https://github.com/rust-lang/rust/blob/fedce67cd21dc08ece5a484fe1a060346acac98a/src/tools/compiletest/src/runtest.rs#L165-L178

Note that the revision is stored in a field, `revision`:

https://github.com/rust-lang/rust/blob/fedce67cd21dc08ece5a484fe1a060346acac98a/src/tools/compiletest/src/runtest.rs#L185-L190

The UI test functionality is implemented starting here:

https://github.com/rust-lang/rust/blob/fedce67cd21dc08ece5a484fe1a060346acac98a/src/tools/compiletest/src/runtest.rs#L2492

You can see that it loads the expected stderr/stdout here:

https://github.com/rust-lang/rust/blob/fedce67cd21dc08ece5a484fe1a060346acac98a/src/tools/compiletest/src/runtest.rs#L2504-L2508

*not complete*

**Comment by nikomatsakis** [comment]
cc @petrochenkov @estebank

**Comment by nikomatsakis** [comment]
Huh, wait a minute. All the code kind of looks right -- are we *sure* they don't work? =)

**Comment by ehuss** [comment]
@nikomatsakis I can try to fix this if you'd like.  If I understand it correctly, there are roughly two things to fix:  
1. `compare_output(...)` needs to dump each revision of stdout/stderr with the correct filename.
2. `update-references.sh` needs to copy all revisions.

Is there a particular reason to convert that shell script to Rust?  Is that something you'd like done now, or would a simple tweak to glob all the appropriate paths be good enough?

Anything else you'd like done with this?

**Comment by nikomatsakis** [comment]
@ehuss 

> Is there a particular reason to convert that shell script to Rust? Is that something you'd like done now, or would a simple tweak to glob all the appropriate paths be good enough?

A simple tweak would be enough. The reason I had planned to convert to Rust was so that it would work on windows etc. But that's a fairly orthogonal task, and maybe it'd be better to step back and see if we can rethink the workflow anyway.

For example, I doubt I would keep it as a separate script, now that I think about it, but rather I would roll it into `x.py`, so that you write something like

```
./x.py bless 
```

or 

```
./x.py bless src/test/ui/foo.rs
```

**Comment by nikomatsakis** [comment]
@ehuss 

> I can try to fix this if you'd like

That'd be awesome, btw!

**Comment by ehuss** [comment]
> but rather I would roll it into x.py

OK, I'd be happy to work on it if you have a clear direction you want to go.  Perhaps you have ideas on other things it would cover?

I realize now I neglected to update the `.sh` script for `ui-fulldeps`.  It seemed odd that it was just copied.  Clippy also has its own copy of the script.  None of the `compile-fail-fulldeps` currently rely on revisions, though.

**Comment by nikomatsakis** [comment]
@ehuss 

> OK, I'd be happy to work on it if you have a clear direction you want to go. Perhaps you have ideas on other things it would cover?

Maybe we should open a follow-up issue and discuss there.

**Comment by nikomatsakis** [comment]
@ehuss filed https://github.com/rust-lang/rust/issues/49815, will add some more details shortly
