### ISSUE TITLE
Auto-traits implementations shouldn't appear if empty

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#48882]
https://doc.rust-lang.org/nightly/std/env/struct.Args.html

**Comment by clarcharr** [comment]
I'd argue that `!Send` and `!Sync` should show up in the auto traits section.

**Comment by GuillaumeGomez** [comment]
Hum no. It's a "manual" binding.

**Comment by clarcharr** [comment]
It depends on if you see it as "auto trait" implementations or auto "trait implementations"

**Comment by GuillaumeGomez** [comment]
There is nothing automatic in here so I don't see where the debate is. :-/
