### ISSUE TITLE
idea: consult git diff for better diagnostics / syntax errors

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#48911]
Just an idea: 

Let's say our code looks like this:
````rust
fn main() {
	{
		{
			{
				println!("Hello, world!");
		}
	}
}
````
The error message is not very helpful here, pointing to lines 1 and 8:
````
error: this file contains an un-closed delimiter
 --> src/main.rs:8:3
  |
8 | }
  |   ^
  |
help: did you mean to close this delimiter?
 --> src/main.rs:1:11
  |
1 | fn main() {
  |           ^

````

However, since cargo inits new repos as git repo, *maybe* we can utilize the repo diff and see which brace was added the last:
```` diff
 fn main() {
        {
                {
-                       println!("Hello, world!");
+                       {
+                               println!("Hello, world!");
                }
        }
 }
````
and give a better diagnostic:

````
error: this file contains an un-closed delimiter
 --> src/main.rs:8:3
  |
8 | }
  |   ^
  |
help: did you mean to close this delimiter?
 --> src/main.rs:4:12
  |
4 |                 {
  |                 ^
```

**Comment by zackmdavis** [comment]
Not worth the extra complexity, I would argue: teaching `rustc` to parse and interpret Git diffs would be just too large of dependency relative to the benefit of being able to provide a smarter error message in one particular case if the user happens to be using Git and the working tree has few enough changes from the last commit for us to be able to infer intent.

**Comment by Songbird0** [comment]
> [...] interpret Git diffs would be just too large of dependency relative to the benefit of being able to provide a smarter error message in one particular case if the user happens to be using Git and the working tree has few enough changes from the last commit for us to be able to infer intent.

Maybe add this feature as "optional" analytic process? Unless, of course, there aren't other scenarios where this may be useful.

**Comment by Ixrec** [comment]
For the specific case of curly brace matching errors, I think the indentation of the braces would be a far better heuristic for user intent than git history. The reason the opening brace on line 4 is "obviously" the unmatched one is because no other curly brace in the example has the same indentation. I'm not sure how to generalize that rule so it works on non-trivial examples, but it seems solvable.

(personally, it's not obvious to me that there are _any_ situations where rustc looking at git history could lead to a significantly better error message, much less enough situations to justify the dependency)

**Comment by tromey** [comment]
One related thing that gcc and clang do is notice conflict markers from `patch` and emit a nicer error in that situation, like:
```
test.c:3:1: error: version control conflict marker in file
```

**Comment by zackmdavis** [comment]
> notice conflict markers from patch and emit a nicer error in that situation 

(This is #32059.)

**Comment by estebank** [comment]
Closing as #53949 addresses the mismatched braces issue for reasonably formatted code (and there's already another ticket for version control conflict markers). We're unlikely to ever ship with an implementation of `git` in the compiler.
