### ISSUE TITLE
Rustdoc: Feeling lucky searches

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#48924]
An idea to improve rustdoc ergonomics: What if we had *"feeling lucky"* searches, so that if you visit:
https://doc.rust-lang.org/nightly/std/?search=phantomdata and you have just one search hit (or if you get two hits with `std::whatever::Whatever`, `core::whatever::Whatever`) it takes you directly to `PhantomData` in this case.

A possibly user interaction would be:

1. visit: https://doc.rust-lang.org/nightly/std/?search=phantomdata
2. there are just two results: `std::marker::PhantomData`, `core::marker::PhantomData`
3. you get redirected to: https://doc.rust-lang.org/nightly/std/marker/struct.PhantomData.html

This will allow a user to directly go to what they want if they do a search with Firefox such as `r PhantomData` (assuming that `r` is the keyword for rust documentation).

We could also have a special flag so that you search with `https://doc.rust-lang.org/nightly/std/?lucky&&search=phantomdata`

cc @steveklabnik, @QuietMisdreavus, @alercah

**Comment by GuillaumeGomez** [comment]
Like I already said, I don't agree with such a feature. If someone wants to share a search (for whatever reason), we don't want to force the redirection. With the special flag, what's the point to even provide the search and not just the element directly?

**Comment by Centril** [comment]
@GuillaumeGomez I thought you said you liked that on IRC ^,-

> If someone wants to share a search (for whatever reason), we don't want to force the redirection.

I agree.

> With the special flag, what's the point to even provide the search and not just the element directly?

I'm not sure what you mean here; can you elaborate?

The point is that if you are looking for a specific type or function but don't know the complete name or you do but don't know the complete path, you can get to the type / function directly without having to land on the search page first.

**Comment by GuillaumeGomez** [comment]
> > With the special flag, what's the point to even provide the search and not just the element directly?

> I'm not sure what you mean here; can you elaborate?

If you have the item in mind, just give it. If you're not sure about the name, make a search and then provide the url to the item. In case you provide the "lucky" url and a new item appeared, the other user you provided the url to won't arrive on the good page.
