### ISSUE TITLE
Missing index out of bounds error

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#48920]
The following example no longer throws a warning about indices being out of bounds, on master: 
```rust
fn main() {
    let a: [i32; 1] = [0; 1];
    a[1];
}
```
I expect a [`index out of bounds: the len is 1 but the index is 1` error](https://play.rust-lang.org/?gist=34c432d5968965257cc05db9c330d63f&version=nightly). I suspect this is due to https://github.com/rust-lang/rust/pull/46882.

cc @oli-obk

**Comment by oli-obk** [comment]
Yea, there's a FIXME  comment in `librustc_mir::transform:: const_prop` for this.

**Comment by varkor** [comment]
I imagine it was specific to the old implementation, but just a note that we want to make sure https://github.com/rust-lang/rust/issues/48900 doesn't reappear when this is reimplemented.

**Comment by steveklabnik** [comment]
This code still errors, but this case doesn't:

```rust
fn main() {
    let a = [1, 2, 3];
    let index = 10;
    let element = a[index];
    println!("element is {}", element);
}
```

is this expected?

**Comment by oli-obk** [comment]
yes. Constant propagation does not cross variables (for now). To do this correctly we'll need to detect loops and conditions. Without such a detection mechanism our current implemementation will do a few bogus things.

**Comment by paolieri** [comment]
Since rustc 1.61, the following code is not giving a compile-time error:

```
fn main() {
    let xs = [10, 20, 30];
    println!("{}", xs[10]);

    let _n = xs.len();
}
```

If I uncomment the last line, the compile-time error shows up.
Is this right? I would expect the compile-time error to show up in both cases (this is what happens for rustc < 1.61).
