### ISSUE TITLE
Some suggestion about the current rustdoc

### ISSUE THREAD

**Issue by chmnchiang** [rust-lang/rust#48935]
1. Currently, all the folds default to "unfold", so if I want to get a overall view I would have to manually fold all the folds, which I think the opposite is more reasonable: The folds is enabled by default, and let the user click for more details.

2. There are to many [src] floating on the right. Maybe show them only on hovered will be better.

**Comment by xftroxgpx** [comment]
> so if I want to get a overall view I would have to manually fold all the folds

Unless I'm misunderstanding something, you can click the "master folder" to collapse all folds:
before:
![screenshot_2018-03-11_23-02-23](https://user-images.githubusercontent.com/26243389/37258980-613c2922-2580-11e8-99a4-8a97497a8678.png)

after:
![screenshot_2018-03-11_23-02-31](https://user-images.githubusercontent.com/26243389/37258983-66258eba-2580-11e8-994b-86e415917556.png)

**Comment by GuillaumeGomez** [comment]
What's the problem with `[src]`?

**Comment by bobogei81123** [comment]
@xftroxgpx That's what I'm looking for, totally missed that. Thanks.

I think the current doc has the problem that it shows to much repeated but uninformative items at a first glance, which cause users hard to get an overview of the page. Take the second picture @xftroxgpx post as an example, at the first sight, those `pub fn` and `src` really stand out, which is probably not users are going to looking for. Something like what [ruby doc](http://ruby-doc.org/stdlib-2.5.0/libdoc/base64/rdoc/Base64.html#method-i-decode64) do, which shows link to source only when hover might be better.

Also I think another problem is that too many words are in bold font. For example, those `pub fn`s are much more conspicuous than the function names, which I believe the later are more important to the reader.

**Comment by jackh726** [comment]
Rustdoc has undergone quite a few updates over the years, and I'm not sure these are even relevant anymore. Closing.
