### ISSUE TITLE
Mutable References in static mut

### ISSUE THREAD

**Issue by oberien** [rust-lang/rust#48931]
The following code produces an error:
```rust
pub static mut S0: *mut u64 = &mut 0u64 as *mut u64;
```
```rust
error[E0017]: references in statics may only refer to immutable values
 --> src/main.rs:1:31
  |
1 | pub static mut S0: *mut u64 = &mut 0u64 as *mut u64;
  |                               ^^^^^^^^^ statics require immutable values
```
[E0017](https://doc.rust-lang.org/nightly/error-index.html#E0017) states:
> If you really want global mutable state, try using static mut or a global UnsafeCell.

This is confusing, because I already use a `static mut`.

Moreover, I can circumvent this issue by using a 1-array of the data instead of the data itself. This compiles perfectly fine:
```rust
pub static mut S1: *mut u64 = &mut [0u64; 1] as *mut _ as *mut u64;
```

**Comment by oli-obk** [comment]
cc @eddyb

**Comment by eddyb** [comment]
The array ("slice") case was left in for compatibility with `static mut FOO: &mut [T] = &mut [...];` (which was already allowed when the new const checking pass was added).

First off, the error is correctly nudging you in the direction of avoiding `static mut`. I would *really* love to get rid of it in a future epoch (as in, just don't parse the syntax anymore).
Typed wrappers let you consider undefined behavior mitigations, but for a long while you couldn't even use `UnsafeCell::new` in a constant context on stable.

Secondly, we *should* allow `&mut` in constants, but it may require an RFC? I'm not sure.
The fact that arrays are allowed suggests we should *just* allow `&mut` everywhere in a constant context. For non-`'static` lifetimes we *need to* anyway for mutable local state in CTFE.

The main usecase, ignoring `static mut`, would probably be `Mutex<&'static mut T>` or similar.
So you could put in a leaked `Box`, but *also* start with some global mutable allocation.
Or more cheaply, an `AtomicPtr<T>` wrapper that semantically holds an `Option<&'static mut T>`.

**Comment by oberien** [comment]
My use-case is writing ffi code. I'm writing a dynamic nginx module, where nginx requires me to have a static symbol defined, which is then read and mutated from within nginx. Without me using a `static mut` and specifying `&mut` everywhere, the compiler would (correctly) infer that the data can be placed in `.rodata`, which would result in segfaults.
I haven't tested if `UnsafeCell` will force the compiler to not put it in `.rodata`, but if not, we'll definitely need an alternative for `static mut`.

**Comment by eddyb** [comment]
@oberien The purpose of `UnsafeCell` is to inform the compiler that the contents are mutable and the *only* effect it has on codegen is to move `static`s from `.rodata` to `.data`.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this as it seems like there's not actually a bug here.

**Comment by tgross35** [comment]
Does anyone have a good example of what this looks like?

I currently have some sort of dummy type:

```rust
#[repr(transparent)]
struct UcWrap<T>(UnsafeCell<T>);

unsafe impl<T> Send for UcWrap<T> {}
unsafe impl<T> Sync for UcWrap<T> {}

static VAR: UcWrap<...> = ...
```

Because `UnsafeCell` isn't Sync. And then the constructor is marked `unsafe` for soundness - I think.

Is this what is intended, or is there a better (less clunky) pattern out there?
