### ISSUE TITLE
Possibly spurious type mismatch error

### ISSUE THREAD

**Issue by urschrei** [rust-lang/rust#48953]
I'm encountering a type mismatch that appears to be incorrect.
[I'm implementing a trait for all `Geo` types which implement `MapCoords`](https://github.com/urschrei/rust-geo/blob/transform/src/algorithm/reproject.rs#L7-L26). The trait involves calling the [`project`](https://github.com/georust/rust-proj/blob/dff87e342fc008e6fe18251b00d606fc8bedddc5/src/proj.rs#L57-L82) function imported from an external crate which, takes a `Point<T>` from `Geo`. However, this causes a type mismatch:

    error[E0308]: mismatched types
      --> src/algorithm/reproject.rs:22:62
       |
    22 |             let reprojected = source_proj.project(dest_proj, Point::new(x, y));
       |                                                              ^^^^^^^^^^^^^^^^ expected struct `geo::types::Point`, found struct `types::Point`
       |
       = note: expected type `geo::types::Point<_>`
                  found type `types::Point<T>`

    error: aborting due to previous error

### Steps to reproduce ###

[Clone my PR branch](https://github.com/urschrei/rust-geo/tree/transform), and compile with `cargo check --features "reprojection"`

rustc version: rustc 1.26.0-nightly (2789b067d 2018-03-06)

Note: I'm not sure that I've defined the trait bound correctly on `transform`, but the type mismatch error seems incorrect in any case.

**Comment by urschrei** [comment]
Things I've checked:
- version mismatches
    - `proj 0.3.0` depends on `geo ^0.7`; I'm developing against `geo` Master, which is `0.7.4`

**Comment by scurest** [comment]
The `geo` that you're developing on and the `geo` that `proj` depends on are different crates. Namely, the `geo` for `proj` is from the registry. You can check this in your `Cargo.lock`.

If you made them the same you'd get `error: cyclic package dependency`.
