### ISSUE TITLE
env_or_default macro

### ISSUE THREAD

**Issue by vbrandl** [rust-lang/rust#48952]
I find my self doing something like this quite often:

```Rust
const VERSION: Option<&'static str> = option_env!("CARGO_PKG_VERSION");

fn main() {
    println!("{}", VERSION.unwrap_or("unknown version"));
}
```

I think it would be nice to have a `env_or_default` macro that defaults to a fallback string at compile time if the environment variable cannot be found. I'm thinking of something like

```Rust
const VERSION: &str = env_or_default!("CARGO_PKG_VERSION", "unknown version");
```

I know the runtime cost isn't that high but if it can be done at compile time, it should be done.

**Comment by kennytm** [comment]
Alternatively we could just make `.unwrap_or()` a `const fn` to allow it being used in the `const` constructor.

```rust
const VERSION: &str = env!("CARGO_PKG_VERSION").unwrap_or("unknown version");
```

**Comment by ExpHP** [comment]
I don't think it is uncommon to require different semantics than just a default for `None`.  The majority of my env lookups usually treat the empty string as equivalent to an unset variable, because (a) they're easier to set in the shell, (b) an empty string is not a useful value for many types of things, such as integers, paths, or version numbers.

Having something like `LIBXYZ_DIR= cargo build` search the current directory is silly.

```rust
fn nonempty_env(name: &str) -> Option<String> {
    match env::var(name) {
        Ok("") | Err(env::VarError::NotPresent) => None
        opt => opt
    }
}

**Comment by matobet** [comment]
@hanna-kruppe now that https://github.com/rust-lang/rfcs/pull/2342 has been merged, can we make `.unwrap_or` const fn?

**Comment by hanna-kruppe** [comment]
I think so.

**Comment by TheButlah** [comment]
Saw https://github.com/rust-lang/rust/pull/76330, but it was closed because destructors cannot run in const contexts just yet

**Comment by frederikhors** [comment]
I'm new to Rust. I'm using rust 1.60.0.

I'm trying to use this code ([PLAYGROUND HERE][1]):

```rust
pub const VERSION: &'static str = option_env!("VERSION").unwrap_or_else(|| "dev");
```

but I'm getting this error:

```
the trait bound `[closure@src\constants.rs:4:81: 4:89]: ~const FnOnce<()>` is not satisfied
the trait `~const FnOnce<()>` is not implemented for `[closure@src\constants.rs:4:81: 4:89]`
wrap the `[closure@src\constants.rs:4:81: 4:89]` in a closure with no arguments: `|| { /* code */ }`rustcE0277
constants.rs(4, 66): the trait `FnOnce<()>` is implemented for `[closure@src\constants.rs:4:81: 4:89]`, but that implementation is not `const`
option.rs(797, 12): required by a bound in `Option::<T>::unwrap_or_else`
```

Can you help me understand what's wrong with it?


  [1]: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&code=pub%20const%20VERSION%3A%20%26%27static%20str%20%3D%20option_env!(%22VERSION%22).unwrap_or_else(%7C%7C%20%22dev%22)%3B%0A%0Afn%20main()%20%7B%0A%20%20%20%20println!(%22Hello%2C%20world!%22)%3B%0A%7D

**Comment by oli-obk** [comment]
The diagnostic should actually just tell you that the function is not a const fn. But we messed up a bit, so you get a different error first. You just can't do this yet that way, you have to match manually and implement the some and none arms of the match yourself.

**Comment by robertbastian** [comment]
I have a use case for this that's not covered by `unwrap_or`:

```rust
include!(core::option_env!("DATA_ROOT").unwrap_or("empty_data/mod.rs"));
```

This doesn't compile because `include!` requires a string literal. `env_or_default!` would evaluate to a string literal and thus be compatible with `include!`, `include_str!`, and `include_bytes!`.

**Comment by punkeel** [comment]
Tracking issue for `const fn unwrap_or`: #91930.

This issue also contains a nice workaround:
```rust
pub const VERSION: &str= match option_env!("VERSION") {
    Some(v) => v,
    None => "dev",
};
```

**Comment by WhyNotHugo** [comment]
Might I suggest closing this in favour of https://github.com/rust-lang/rust/issues/91930? It allows doing this with `unwrap_or`.

**Comment by robertbastian** [comment]
That does not cover the use case in my previous comment.

**Comment by WhyNotHugo** [comment]
Maybe it's best to adapt `include!` to accept any `&'static str`, and not just a string literal?

**Comment by robertbastian** [comment]
I assume `include!`s are resolved very early in the compiler, I highly doubt that `const` expressions will be evaluated at that point.

**Comment by robertbastian** [comment]
That doesn't work for includes
