### ISSUE TITLE
get read_exact() read in bytes

### ISSUE THREAD

**Issue by nifker** [rust-lang/rust#48979]
especially with binary data if you hit the eof you cant check how many bytes you really read into the array

**Comment by sfackler** [comment]
read_exact is designed for the case when you know you need exactly N bytes. If you need more control you can build something that makes sense for your use case on top of read.

**Comment by sfackler** [comment]
> this is only possible if the file contains only ascii chars

What does ASCII have to do with anything here?

> and for read() it returns 'some' bytes so you dont really know how many calls you need to fill the buffer.

Right - you loop over calls to read while you need more data.

> Another thing is the question does it read in blockwise? Otherwise it would be really slow.

The implementation of read_exact is here: https://github.com/rust-lang/rust/blob/master/src/libstd/io/mod.rs#L701-L716

**Comment by nifker** [comment]
you cant iterate through an array of binary data as a 0 as value doesnt mean its the end of the file this is only applicable for text

**Comment by sfackler** [comment]
`read` copies data into the buffer and returns the number of bytes read. An end of file is indicated by **returning zero**. There is no number that is either zero or comes from the file.

**Comment by Centril** [comment]
triage ping @sfackler

**Comment by sfackler** [comment]
Pong?

**Comment by Centril** [comment]
@nifker at the moment we are unsure exactly what you are asking or want... can you clarify the issue with an example of what you are trying to solve or where your problem is?

**Comment by nifker** [comment]
@sfackler hmmm what abou the fucking array which is pribably longer than the read data? And you initialized it probably as 0 and im still talking about read_exact().
And what about if the file contains a binary 0?
