### ISSUE TITLE
incr.comp.: Cache the specialization_graph query.

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#48987]
Computing the specialization graph for a trait involves looking at lots of things. The result of the query should be easily cacheable:

https://github.com/rust-lang/rust/blob/e65547d4fad0425d1db4f33a4d8134bf2cad939e/src/librustc/traits/specialize/specialization_graph.rs#L39-L66

**Comment by wesleywiser** [comment]
I'll take this.
