### ISSUE TITLE
Rustdoc text overlap

### ISSUE THREAD

**Issue by fintelia** [rust-lang/rust#49006]
In Firefox and Chrome, the documentation for [`OccupiedEntry`](https://doc.rust-lang.org/nightly/std/collections/hash_map/struct.OccupiedEntry.html) (and probably other types as well), it seems that rustdoc sometimes overlaps long trait impls with the stability version numbers:

![Firefox screen of issue](https://screenshotscdn.firefoxusercontent.com/images/2bab51d8-ebb4-4aba-92da-439f7b00ec2b.png)

**Comment by GuillaumeGomez** [comment]
Ah yes, it's actually pretty common. Still looking for a way to fix it.
