### ISSUE TITLE
Rename "epoch" to "edition"

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#49001]
We currently expose a -Zepoch=foo flag. It should be `-Zedition=foo`. Furthermore, all code and comments talking about epochs should use the word "edition".

(mentoring)

**Comment by klnusbaum** [comment]
I'll take a stab at this.

**Comment by klnusbaum** [comment]
Made some significant progress on this. Expecting to have a PR later tonight or by tomorrow

**Comment by Manishearth** [comment]
https://github.com/rust-lang/rust/pull/49035
