### ISSUE TITLE
Atomic docs aren't generic, which is both sad and bad

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#49018]
https://doc.rust-lang.org/nightly/std/sync/atomic/struct.AtomicU32.html

**Comment by Songbird0** [comment]
Hi,

What do you mean by "not generic"?

**Comment by sfackler** [comment]
The examples for all `Atomic*` types use `AtomicIsize`.

**Comment by Songbird0** [comment]
Ohw, I see.
