### ISSUE TITLE
Can't set breakpoints on rust_panic.

### ISSUE THREAD

**Issue by nical** [rust-lang/rust#49013]
When debugging a rust program, it is very useful to be able to set breakpoints on `rust_panic`, however this stopped working at some point. gdb cannot find a rust_panic symbol to break on.
Using `nm` I can see that there is a symbol `rust_panic.llvm.5A8AA348` in the debug binary I am currently looking at, with the 5A8AA348 part varying from computer to computer (I suppose it's related to the llvm or compiler version).

Setting a breakpoint on `rust_panic.llvm.5A8AA348` works, but it's quite awful to have to look for symbols every time a panic needs to be investigated.

Tested with:

 - rustc 1.23.0-nightly (827cb0d61 2017-11-26)
 - rustc 1.24.1 (d3ae9a9e0 2018-02-27)

~~Looks like it got fixed at some point before rustc 1.26.0-nightly (2789b067d 2018-03-06), but~~ it is currently broken on stable.

**Comment by nical** [comment]
Actually, rust_panic is still "mangled" in rustc stable 1.26.0.

**Comment by kvark** [comment]
Would be great to get this fixed!

**Comment by pnkfelix** [comment]
Odd, we have it marked as `no_mangle` here:

https://github.com/rust-lang/rust/blob/0b0d2edf79ceb3ab6dce1dcba9297af038fd6f0c/src/libstd/panicking.rs#L519-L522

**Comment by michaelwoerister** [comment]
This might be a side effect of ThinLTO which does some mangling of symbols. Maybe a `\0` prefix in the LLVM name could help here? (see https://llvm.org/docs/LangRef.html#identifiers)

cc @alexcrichton

**Comment by alexcrichton** [comment]
Yes `ThinLTO` is what manufactures the `rust_panic.llvm.5A8AA348` symbol and that's because it's not listed as `#[inline(never)]` I believe, I'll send a PR to fix that.

**Comment by alexcrichton** [comment]
https://github.com/rust-lang/rust/pull/54590

**Comment by lu-zero** [comment]
`rustc 1.31.0-nightly (2bd5993ca 2018-10-02)` seem to still have the problem at least on Linux.

**Comment by kvark** [comment]
FWIW, I disagree with `C-enhancement` tag. This is clearly a bug from my perspective. Being able to easily break on panic is a must have experience.

**Comment by petrochenkov** [comment]
It also would be nice to make `catch throw`/`catch catch` work with `panic`/`catch_unwind`.
I'm not sure how exactly our panics differ from C++ exceptions, but the aforementioned commands don't catch them in `gdb`.
cc @tromey

**Comment by tromey** [comment]
`catch throw` and friends work by hooking in to the unwinder.  The libstdc++ unwinder provides "sdt" probe points, but gdb will fall back to using the exported unwinder function names like `__cxa_throw`.  Extending this to Rust should not be too difficult, provided that the names are stable.  Another option is to follow the Ada lead and add rust-specific `catch` subcommands.  Perhaps this could even be done in the Rust-supplied gdb scripts without modifying gdb.

There is also a probe point in the libgcc unwinder that is used to implement the "next over throw" feature.  The idea is that if you `next` in gdb, a `throw` in the inferior should only cause a stop if it lands in the current frame or any older frame.  If Rust is using the libgcc unwinder on Linux then this should probably already work.  (I haven't tried it yet.)

Related is #21102.  I tend to think the Rust gdb scripts should set a breakpoint on an aborting panic, by default, but not on an unwinding panic.  I haven't looked into how to accomplish this.

**Comment by tromey** [comment]
This seems to be fixed.  Using stable (1.43.1) I see `rust_panic` in a simple debug executable:\
```$ nm memory|grep rust_panic$
000000000000c350 T rust_panic
```

**Comment by nical** [comment]
I can also see the symbol now.

**Comment by cpick** [comment]
See https://github.com/rust-lang/rust/issues/140821 for a bit of a regression.
