### ISSUE TITLE
for loop not execute warning, must use error

### ISSUE THREAD

**Issue by damody** [rust-lang/rust#49034]
https://play.rust-lang.org/?gist=3baa55960b4fd167d70a413d0f6fef92&version=stable
https://play.rust-lang.org/?gist=33831e35c8fad7cac6ebb151c8690c7f&version=stable

if rust is "safety" lang, when some code pass by compile, but just warning.
then people will think is vec push function is wrong, not for loop's problem!

**Comment by oli-obk** [comment]
IMO the overflowing literals lint should be deny by default.

**Comment by scottmcm** [comment]
I agree with @oli-obk, but when this has come up before (see https://github.com/rust-lang/rust/issues/47979#issuecomment-363120512) it was closed as needing an RFC, and I don't think anything has changed since then.
