### ISSUE TITLE
inner attribute syntax issue

### ISSUE THREAD

**Issue by liigo** [rust-lang/rust#49040]
```
#![allow(unused_variables)]; // note: a tailing semicolon here

fn main() {}
```

Stable & Nightly compiler error:

```
warning: this inner attribute syntax is deprecated. The new syntax is `#![foo]`, with a bang and no semicolon
 --> src/main.rs:1:1
  |
1 | #![allow(unused_variables)];
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I think I already use the "new syntax", except adding one more semicolon.
The compiler could simply suggest me removing the redundant semicolon.

**Comment by petrochenkov** [comment]
It already suggests it.
>The new syntax is `#![foo]`, with a bang **and no semicolon**

That said, the message can be improved by not mentioning deprecation (the old syntax was removed long time ago) and adding a suggestion/label pointing to the semicolon.
