### ISSUE TITLE
Suspected build time regression when removing unused bool.

### ISSUE THREAD

**Issue by glennw** [rust-lang/rust#49061]
In the WebRender repo, we have a PR that won't land due to rustc timeouts on travis-ci (https://github.com/servo/webrender/pull/2482).

Other PRs before and after this one have been landing without any timeout issues.

The PR in question has failed to merge 8 times, each time caused by a timeout (see https://travis-ci.org/servo/webrender/jobs/353937410#L1073 for the most recent log).

We're targeting the rustc version that is currently used by Gecko:

```
$ rustc --version
rustc 1.23.0 (766bd11c8 2018-01-01)
$ rustup --version
rustup 1.11.0 (e751ff9f8 2018-02-13)
$ cargo --version
cargo 0.24.0 (45043115c 2017-12-05)
```

**Comment by michaelwoerister** [comment]
Here is another report of infinite build times: https://github.com/rust-lang/rust/issues/49072 
Maybe related to MIRI const eval. 

cc @oli-obk @eddyb

**Comment by oli-obk** [comment]
A bunch of miri regressions have been fixed. If it is still slow after the next nightly, i'll investigate.

**Comment by glennw** [comment]
I didn't try it locally, but I gave it one more retry on CI today, and it merged. So I guess whatever PRs have landed in WebRender in the meantime were enough to stop this PR from timing out. Shall we close this, or is it still worth investigating further?

**Comment by oli-obk** [comment]
Let's close it, without a repro it's hard to investigate
