### ISSUE TITLE
Cannot type letter 's' into search box in Nightly Rust Doc [1.26.0-nightly (392645394 2018-03-15)]

### ISSUE THREAD

**Issue by OnlyLys** [rust-lang/rust#49075]
### Issue
The search box in the latest nightly std documentation does not allow the letter 's' to be entered into it.

Both the local copy available via `rustup doc` and the online one available at https://doc.rust-lang.org/nightly/std are affected. This problem happens on Chrome Beta, Firefox and Edge. 

### Note
The stable documentation [Version 1.24.1 (d3ae9a9e0 2018-02-27)] does not have this issue. Neither does the beta documentation [Version 1.25.0-beta.10 (de97991bd 2018-03-13)].

I also tested the previous nightly (nightly-2018-03-07) and at least for the local copy of the doc, **it did not have this issue**. Therefore it must be the latest nightly that broke the search box.

**Comment by mzji** [comment]
Looks like 9e0ccc5a479644bf35ffe04717d6e100fde74fcc is the culprit, @GuillaumeGomez ...

**Comment by mzji** [comment]
Temp fix: `/share/doc/rust/html/main.js` Line 243:
```diff
-        if (document.activeElement.tagName === "INPUT" &&
+        if (document.activeElement.tagName === "INPUT" ||
```
Then both `s` and `?` back to work.

**Comment by OnlyLys** [comment]
The thing is fixed in latest nightly (adf2135ad 2018-03-17). Thank you!

**Comment by GuillaumeGomez** [comment]
Oh damn, indeed!

**Comment by OnlyLys** [comment]
@mzji Yes that works! Thank you!

**Comment by GuillaumeGomez** [comment]
No, the fix breaks why it has been implemented first. It fixes this issue, but not why I made this change. I need to look further.

**Comment by GuillaumeGomez** [comment]
Ok, fix done. I'll make the PR this evening.
