### ISSUE TITLE
MinGW: Linking error while building `rustc_data_structures` - ld "cannot find -lsynchronization"

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#49080]
ping @Zoxc probably

Haven't investigated this myself yet, just posting here in case there's a known fix.

**Comment by Zoxc** [comment]
Do you have a log? How did you produce this?

**Comment by retep998** [comment]
Are you getting this error while building Rust itself? If so, your MinGW installation is missing `libsynchronization.a`.

**Comment by petrochenkov** [comment]
Ok, `libsynchronization.a` is indeed a part of mingw-w64 toolchain, but it's a relatively new part that first appeared in 6.3.0, but I use 6.2.0 due to [gdb bugs](https://github.com/rust-lang/rust/issues/40184) in newer versions.

It looks like `parking_lot` depends on this library, and `rustc_data_structures` now depends on `parking_lot` thus bumping version requirement for mingw-w64 toolchain to 6.3.0.

I guess I'll have to do [what our CI does](https://github.com/rust-lang/rust/blob/master/appveyor.yml#L127-L145) and use newer toolchain with gdb replaced with older version.
