### ISSUE TITLE
MIRI: Tried to cache DefId(_), but was already existing as AllocId(_)

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#49081]
The following crash occurs during incremental compilation of the rust-url crate:
https://travis-ci.org/rust-icci/rust-url/jobs/354013054#L1157-L1159

cc @oli-obk @eddyb

**Comment by oli-obk** [comment]
minimal repro:

```rust
pub static A: i32 = 42;
pub static B: &i32 = &A;
```

**Comment by michaelwoerister** [comment]
@oli-obk remarked on IRC that this might be temporarily worked around by not caching upstream constants.

**Comment by nikomatsakis** [comment]
triage: P-high

Regression.
