### ISSUE TITLE
ICE caching DefId

### ISSUE THREAD

**Issue by Michael-F-Bryan** [rust-lang/rust#49087]
I've encountered a really annoying ICE on the latest nightly which I can't seem to reliably reproduce. It *looks* like there's an issue when generating IDs where we're somehow creating duplicates.

```
error: internal compiler error: librustc/ty/context.rs:976: tried to cache DefId(0/0:39 ~ carlogs_analysis[b4ca]::run[0]::RS[0]::LOC[0]), but was already existing as AllocId(
    1
)
```

I first found it on a project at work on a Windows machine but Windows doesn't print backtraces, then when I jumped onto my Linux laptop I couldn't reproduce it. Now I'm hacking on a completely different project on a Linux laptop and have encountered the same thing. 

I've uploaded the full output to a gist: https://gist.github.com/Michael-F-Bryan/e8647e1e94d0754699c47dbadbe31ba7

---

Environment Info:

```
$ rustc --version
rustc 1.26.0-nightly (392645394 2018-03-15)
$ cargo --version
cargo 1.26.0-nightly (5f83bb404 2018-03-09)
```

**Comment by nikomatsakis** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/49081, I believe. Closing in favor of that.

**Comment by nikomatsakis** [comment]
(Thanks @Michael-F-Bryan !)

**Comment by Michael-F-Bryan** [comment]
Yep, it looks like a dupe. Thanks for getting to the issue so quickly @nikomatsakis!
