### ISSUE TITLE
`.into()` suggested in const context

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#49100]
```rust
const TEN: u8 = 10;
const ALSO_TEN: u16 = TEN;
```

The compiler suggests `.into()` instead of an `as`-cast:

```
error[E0308]: mismatched types
 --> src/main.rs:2:23
  |
2 | const ALSO_TEN: u16 = TEN;
  |                       ^^^ expected u16, found u8
help: you can cast an `u8` to `u16`, which will zero-extend the source value
  |
2 | const ALSO_TEN: u16 = TEN.into();
  |                       ^^^^^^^^^^
```

Normally I'm all about phasing out `as`, and we should somehow make `.into()` callable on consts, but right now it's suggesting invalid code.

cc @estebank (implemented #47247)

**Comment by oli-obk** [comment]
We have so many cases of these in clippy... we should figure out a way to generalize not producing lints or suggestions in certain contexts

**Comment by estebank** [comment]
I originally wrote the code to suggest `as` and then reworked it to use `into`. In that rework I just have forgotten to think about cases like this. One aware of the problem avoiding this is easy.

As for the generalization, I'd be surprised if we can come up with a way to avoid needing all this context when writing lints, sadly.

**Comment by oli-obk** [comment]
We can ask for the AST parent until we hit an item and then check for const or const fn. But I don't know how to nicely create an API for that
