### ISSUE TITLE
Cloxer / Trojan on https://www.rust-lang.org/en-US/install.html

### ISSUE THREAD

**Issue by mocsy** [rust-lang/rust#49110]
This link https://win.rustup.rs downloads a 4.5 MB file, which result in Windows Defender removing it immediately.
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fCloxer.D!cl&threatid=2147726003

This link https://win.rustup.rs/x86_64 at https://www.rustup.rs downloads a 5.6 MB file which doesn't have this problem.

**Comment by kennytm** [comment]
I've checked the 4.5 MiB file with VirusTotal and there are [2 false positives](https://www.virustotal.com/#/file/b33a82c54199a427172fec8957760ae7c9a7b7a13b0814bdddb4438e7f88e801/detection) as of 2018-03-16 02:29:36 UTC

* Baidu: `Win32.Trojan.WisdomEyes.16070401.9500.9996`
* McAfee-GW-Edition: `BehavesLike.Win32.Generic.rh`

Assuming "Microsoft" means Windows Defender, the report is "clean". Have you tried updating Windows Defender's Definitions?

There is also [1 false positive for the 5.6 MiB file](https://www.virustotal.com/#/file/7f14f767fb547e7b7548341892d0849c9d77eaada1f5e199b5e8c51f54cf06c0/detection) as of 2018-03-07 00:00:59 UTC, again does not include Microsoft:

* Baidu: `Win32.Trojan.WisdomEyes.16070401.9500.9976`

**Comment by stonebig** [comment]
version of May 2nd has still one alarm on VirusTotal... maybe Mozilla could sign the binary ?

 MD5                             | SHA-1                                    | SHA-256                                                          | Binary                          | Size              
---------------------------------|------------------------------------------|------------------------------------------------------------------|---------------------------------|-------------------
b1999dcec6cefd1125be70161795a75a | bf654eaa720a1ba1a4cfa1b0ab75d5c3ad809391 | f9a87198a4854d96b95ff9ccd3309772d7b89d2bf474bce4e6c6c3a0fe4d5e0d | rustup-init.exe                 |    5 689 856 Bytes
