### ISSUE TITLE
Bundled LLD not found on nighlty on FreeBSD

### ISSUE THREAD

**Issue by thefallenidealist** [rust-lang/rust#49144]
After updating to the newest nightly I was not able to build project for  `thumbv7em-none-eabi`
Downgrading to nightly toolchain from 2018-03-07 enables the building again.
After upgrading cargo and xargo, I was not able to build with any toolchain. The error message is:
```
error: intermittent IO error while iterating directory `/usr/home/johnny/.rustup/toolchains/nightly-x86_64-unknown-freebsd/lib/rustlib/x86_64-unknown-freebsd/bin`
caused by: IO error for operation on /usr/home/johnny/.rustup/toolchains/nightly-x86_64-unknown-freebsd/lib/rustlib/x86_64-unknown-freebsd/bin: No such file or directory (os error 2)
caused by: No such file or directory (os error 2)
```

<details>
  <summary>Full trace</summary>
<pre><code>
cd src/rust ; xargo build --target thumbv7em-none-eabi --verbose  
+ "rustc" "--print" "sysroot"
+ "rustc" "--print" "target-list"
error: intermittent IO error while iterating directory `/usr/home/johnny/.rustup/toolchains/nightly-x86_64-unknown-freebsd/lib/rustlib/x86_64-unknown-freebsd/bin`
caused by: IO error for operation on /usr/home/johnny/.rustup/toolchains/nightly-x86_64-unknown-freebsd/lib/rustlib/x86_64-unknown-freebsd/bin: No such file or directory (os error 2)
caused by: No such file or directory (os error 2)
stack backtrace:
   0:          0x108550e - backtrace::backtrace::trace::hafd23abf47c8ee7c
   1:          0x1083d13 - backtrace::capture::Backtrace::new::h75657deaf8e42834
   2:          0x1083742 - error_chain::make_backtrace::h6c228d047588bcde
   3:          0x10556a8 - xargo::util::cp_r::ha32daf9ea7208619
   4:          0x104d73c - xargo::sysroot::update::he19084a0917ca635
   5:          0x1053714 - xargo::main::h38c5bcdcc7b0da80
   6:          0x1050475 - std::rt::lang_start::{{closure}}::h3711db21e8d22f2c
   7:          0x1099747 - std::panicking::try::do_call::h95b40a6c554c0f67
   8:          0x10b546e - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
   9:          0x10913e5 - std::rt::lang_start_internal::h485a8bd8f9cfdaf4
  10:          0x10541bb - main
  11:          0x102e34f - _start
  12:        0x80134afff - <unknown>
gmake: *** [Makefile:60: rust] Error 1
</code></pre>
</details><br>

`rustc --version`
`rustc 1.26.0-nightly (adf2135ad 2018-03-17)`
`xargo --version`
`xargo 0.3.11 (58a5465 2018-03-17)`
`cargo 1.26.0-nightly (5f83bb404 2018-03-09)`
<br>

There is no bin folder:
`ls ~/.rustup/toolchains/nightly-x86_64-unknown-freebsd/lib/rustlib/x86_64-unknown-freebsd/`
`analysis         codegen-backends lib`
<br>

OS version:
`uname -sr`
`FreeBSD 11.1-RELEASE-p8`
<br>

Maybe 3rd party or system lld can be used?
```
/usr/local/llvm50/bin/ld.lld --version
LLD 5.0.1 (compatible with GNU linkers)
/usr/bin/ld.lld --version
LLD 4.0.0 (FreeBSD 297347) (compatible with GNU linkers)
```

Possible related to #48772

**Comment by Woyten** [comment]
Did you try to remove `~/.xargo`?

**Comment by thefallenidealist** [comment]
Removing `~/.xargo` has no effect.

**Comment by thefallenidealist** [comment]
Also, removing ~/.cargo and ~/.rustup and reinstalling all has no effect, the same error message is reported.

**Comment by thefallenidealist** [comment]
Workaround would be just to create missing folder with mkdir command and it will start working again.

Also, to update to newest nightly on FreeBSD:
remove ~/.cargo ~/.rustup and run script from https://rustup.rs/
```
% rustup show
Default host: x86_64-unknown-freebsd

nightly-x86_64-unknown-freebsd (default)
rustc 1.27.0-nightly (7360d6dd6 2018-04-15)

```
