### ISSUE TITLE
println! sometimes panics in drop methods - 2

### ISSUE THREAD

**Issue by DustinByfuglien** [rust-lang/rust#49143]
There was issue https://github.com/rust-lang/rust/issues/29488

I don't know is it possible to reopen it. And create a new that continues that discussion.

There is another case when applications panic while using drop/TLS/println:
```
struct Foo {}

impl Drop for Foo {
    fn drop(&mut self) {
        println!("drop begin");
    }
}


thread_local! {
    static FOO: Foo = Foo{};
}


fn main() {
    println!("main begin");
    FOO.with(|_| {});
}

```
This code output is:
```
main begin
thread '<unnamed>' panicked at 'cannot access stdout during shutdown', libcore\option.rs:916:5
```

My point of view is it also must be fixed in Rust language.

_rustc 1.26.0-nightly (adf2135ad 2018-03-17)_

**Comment by pietroalbini** [comment]
Closing this issue as a duplicate, but I have reopened the other one. Thank you!
