### ISSUE TITLE
Backticked Implied Shortcut Reference Links don't render correctly

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust#49164]
```Rust
pub struct Foo;

/// Reference to [Foo]. Code-styled reference to [`Foo`].
pub struct Bar;

```

renders as:

![](https://i.imgur.com/0Qiv2Iw.png)

`rustdoc 1.26.0-nightly (5508b2714 2018-03-18)`

Ref #43466 , https://github.com/rust-lang/rust/pull/48335#issuecomment-369147071

**Comment by GuillaumeGomez** [comment]
Working on it.
