### ISSUE TITLE
rustdoc: move `#[macro_use] extern crate` statements outside the generated main in doctests

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/rust#49174]
In https://github.com/rust-lang/rust/pull/48106 i moved plain `extern crate some_crate` statements outside the `fn main` that rustdoc generates, but i failed to take `#[macro_use]` attributes into account. Since one of the common reasons people would add the manual crate import is to import its macros, this makes the feature less useful.

(Mentoring instructions to follow...)

**Comment by QuietMisdreavus** [comment]
To make a PR for this, you can effectively follow the blueprint in https://github.com/rust-lang/rust/pull/48106. There's a conditional in `partition_source` in `src/librustdoc/test.rs` that checks for inner attributes and `extern crate` statements, so the change is as small as adding another condition to check for lines starting with `#[macro_use] extern crate` as well. You should also add another test to the grouping of unit tests at the bottom of the file to make sure it works.

If you run into issues in the error index like i did in the original PR, we can deal with it after the PR is put up. If you want to take this PR on, comment here or find me in `#rustdoc` on IRC!

**Comment by memoryleak47** [comment]
I'd like to try this one. :)

**Comment by QuietMisdreavus** [comment]
Great! Let me know if you run into any issues or want some help. :D
