### ISSUE TITLE
bootstrap: support building rustc with monolithic lto

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#49175]
I would like to be able to locally build rustc with monolithic lto enabled (````-C lto````) however it seems that using ````lto=true```` in ````src/Carto.toml```` does not have any effect.

```` RUSTFLAGS="-C lto" ./x.py build ```` fails as well

````
Building stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling std v0.0.0 (file:///home/matthias/RUST/rust_build/src/libstd)
error: cannot prefer dynamic linking when performing LTO
note: only 'staticlib', 'bin', and 'cdylib' outputs are supported with LTO
error: aborting due to previous error
error: Could not compile `std`.
````

Edit: related: #49180

**Comment by rkruppe** [comment]
rustc is primarily composed of dylibs, which as the error message states are incompatible with LTO. This is fundamentally impossible, at least until we get rid of the dylibs (they're currently required for compiler plugins and proc macros).

**Comment by matthiaskrgr** [comment]
Hmm so forcing everything to be linked statically is not possible at the moment, right?
// cc  https://github.com/rust-lang/rust/issues/39998

**Comment by sanxiyn** [comment]
Yes, it is not possible.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this as it's not feasible today and probably not something we'll want to do for quite some time if ever.

**Comment by matthiaskrgr** [comment]
@Mark-Simulacrum  uhm, #49180 says that it would desirable to bootstrap with monolithic lto

**Comment by Mark-Simulacrum** [comment]
True, but I don't think a dedicated issue will help move this along at this point -- I don't particularly care either way though.
