### ISSUE TITLE
Tracking issue for LLVM align attributes (-Z arg_align_attributes)

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#49185]
In theory we should be emitting LLVM `align <n>` attributes (https://llvm.org/docs/LangRef.html#attr-align) for references, since they're always aligned.

However, it turns out that these get inlined as `assume` calls, which (per the HACK comment in the code) block other optimizations, so they're currently disabled.

-Z flag was added in https://github.com/rust-lang/rust/pull/49122

**Comment by nikic** [comment]
This flag has already been removed quite a while ago in #57021, so closing this.
