### ISSUE TITLE
Low Level Socket API

### ISSUE THREAD

**Issue by asypost** [rust-lang/rust#49195]
There's no Low Level Socket API Found in current stdlib.Is it possible to provide access to it.

**Comment by killercup** [comment]
What are you looking for specifically? If it's Unix-specific, have a look at the [libc](https://docs.rs/libc) and [nix](https://docs.rs/libc) crates.

**Comment by retep998** [comment]
There's very little reason for Rust to offer this stuff in the standard library given doing FFI in Rust yourself is trivial. Just use `libc` or `nix` to get the raw low level stuff you need (and `winapi` on Windows).

**Comment by pietroalbini** [comment]
A whole new socket API would surely require a bit of design work to get it right, and [our internals forum](https://internals.rust-lang.org) is the best place to start working on that. Could you open a post there? Thanks!
