### ISSUE TITLE
Error message for mistyped enum variant isn't helpful

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang/rust#49192]
Where we would normally put "^^^ did you mean Up" under mistyped names, I noticed that we don't do that for enum variants.

Here's an example I just saw:

![image](https://user-images.githubusercontent.com/547158/37630567-335cf4ac-2c4a-11e8-8c13-a1b23a5f0194.png)

**Comment by GuillaumeGomez** [comment]
Taking a look.
