### ISSUE TITLE
All fixed-size array impls show up as `<unevaluated[]>`

### ISSUE THREAD

**Issue by Vurich** [rust-lang/rust#49208]
After https://github.com/rust-lang/rust/pull/46882, when a trait bound fails and the trait was implemented by fixed-size arrays, the compiler will display an error like:

```
   = help: the following implementations were found:
             <[T; <unevaluated[]>] as Trait>
             <[T; <unevaluated[]>] as Trait>
             <[T; <unevaluated[]>] as Trait>
             <[T; <unevaluated[]>] as Trait>
           and 31 others
```

Which is pretty unhelpful. A solution would be to evaluate these and/or to show evaluated bounds preferably.

**Comment by oli-obk** [comment]
I can't reproduce triggering an error with these messages, do you have an example? I need it for a regression test, the fix was indeed as simple

> to evaluate these and/or to show evaluated bounds preferably.

**Comment by Vurich** [comment]
It only appears if you explicitly disambiguate the trait, like `<[T; N] as Foo>::foo()`. [Playground link here](https://play.rust-lang.org/?gist=19ac245eb8f58692f9f4f18fe6976657&version=stable).

**Comment by estebank** [comment]
@oli-obk are you displaying these as `<[(); _] as Foo>`? I feel that'd be a reasonable output for this.

**Comment by oli-obk** [comment]
@estebank that would be a better fallback than `<unevaluated[]>`, but I'm currently trying to get at the actual value (though that triggers cycle errors atm when building libcore's array impls ^^)

**Comment by Vurich** [comment]
@estebank That's better in some ways, but kinda implies that `for<const T> [(); T]: Foo`
