### ISSUE TITLE
[ICE] "we never error on empty config files: Error { inner: ErrorInner { kind: Custom, line: None, col: 0, message: "missing field `blacklisted-names`", key: [] } }"

### ISSUE THREAD

**Issue by Eijebong** [rust-lang/rust#49207]
Happens when compiling diesel on nightly
https://travis-ci.org/diesel-rs/diesel/jobs/355827115#L499

**Comment by estebank** [comment]
It seems to be an incorrect assumption in [clippy](https://github.com/rust-lang-nursery/rust-clippy/blob/4edd140e57cce900fa930e1439bab469f5bbce46/clippy_lints/src/utils/conf.rs#L214-L219).

**Comment by Manishearth** [comment]
https://github.com/rust-lang-nursery/rust-clippy/issues/2560
