### ISSUE TITLE
mismatched types in rust nigthly (i686-pc-windows-gnu)

### ISSUE THREAD

**Issue by sailfish009** [rust-lang/rust#49226]
Hi i am trying to build simple win32 application. 

extern crate winapi; 
use winapi::shared::windef::HWND;
// use winapi::windef::HWND; // ^^^^^^ Could not find `windef` in `winapi`

here is error message :

```
error[E0308]: mismatched types
  --> src\main.rs:39:36
   |
39 |     return user32::DefWindowProcW( h_wnd, msg, w_param, l_param);
   |                                    ^^^^^ expected enum `winapi::windef::HWND__`, found enum `winapi::shared::windef::HWND__`
   |
   = note: expected type `*mut winapi::windef::HWND__`
              found type `*mut winapi::shared::windef::HWND__`
```

--

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-pc-msys/6.4.0/lto-wrapper.exe
Target: i686-pc-msys
Configured with: /msys_scripts/gcc/src/gcc-6.4.0/configure --build=i686-pc-msys --prefix=/usr --libexecdir=/usr/lib --enable-bootstrap --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --with-arch=i686 --with-tune=generic --disable-multilib --disable-sjlj-exceptions --enable-__cxa_atexit --with-dwarf2 --enable-languages=c,c++,fortran,lto --enable-graphite --enable-threads=posix --enable-libatomic --enable-libcilkrts --enable-libgomp --enable-libitm --enable-libquadmath --enable-libquadmath-support --disable-libssp --disable-win32-registry --disable-symvers --with-gnu-ld --with-gnu-as --disable-isl-version-check --enable-checking=release --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible
Thread model: posix
gcc version 6.4.0 (GCC)

$ rustc -vV
rustc 1.26.0-nightly (75af15ee6 2018-03-20)
binary: rustc
commit-hash: 75af15ee6ca0c12b699a17984b033363cd25e9c3
commit-date: 2018-03-20
host: i686-pc-windows-gnu
release: 1.26.0-nightly
LLVM version: 6.0

**Comment by retep998** [comment]
The error you are getting is due to `user32-sys` expecting a type from `winapi` 0.2 when your own code is using `winapi` 0.3. With `winapi` 0.3 you no longer need `user32-sys` and friends as all functions are defined directly inside `winapi` now. You can see `DefWindowProcW` directly in `winapi` [here](https://docs.rs/winapi/*/x86_64-pc-windows-msvc/winapi/um/winuser/fn.DefWindowProcW.html).

**Comment by sailfish009** [comment]
@retep998  thanks! it works.
