### ISSUE TITLE
Use of ptr::NonNull in FFI

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rust#49220]
I think it would be interesting to use `ptr::NonNull`  to explicitly document FFI arguments that aren't allowed to be `NULL`, so that e.g.:

```rust
extern "C" fn call_me_from_c(without_nulls: ptr::NonNull<c_char>)
```

could be an implementation for:

```c
void call_me_from_c(char *without_nulls) __attribute__((nonnull));
```

However, `ptr::NonNull` doesn't have `#[repr(transparent)]`, so I'm not sure if that is sound. Whether it's supposed to be used this way or not, it may be worth explicitly documenting it. Currently its docs don't say anything about FFI compatibility.

**Comment by mattico** [comment]
cc #27730

**Comment by RReverser** [comment]
`NonNull` has `repr(transparent)` now, so I assume this can be closed?
