### ISSUE TITLE
Please add a constructor for std::io::IntoInnerError

### ISSUE THREAD

**Issue by teythoon** [rust-lang/rust#49239]
Please add a constructor for `std::io::IntoInnerError` so that it can be used in objects similar to `std::io::BufWriter`.

I tried this code:

```
    pub fn into_inner(mut self)
        -> std::result::Result<W, io::IntoInnerError<PartialBodyFilter<W>>> {
        match self.flush() {
            Err(e) => Err(io::IntoInnerError(self, e)),
            Ok(()) => Ok(self.inner.take().unwrap())
        }
    }
```

I expected to see this happen: It works.  No code duplication.  Rainbows.  Unicorns.

Instead, this happened: The compiler did not let me create the object because the fields are private, and I ended up making a verbatim copy of io::IntoInnerError minus the attributes.
```
73 |             Err(e) => Err(io::IntoInnerError(self, e)),
   |                           ^^^^^^^^^^^^^^^^^^ did you mean `io::IntoInnerError { /* fields */ }`?
```
## Meta

`rustc --version --verbose`:

```% rustc --version --verbose
rustc 1.24.1
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.24.1
LLVM version: 4.0
```

**Comment by pietroalbini** [comment]
Thank you for this issue! I _think_ you can't do that because it would prevent any future modification of that type (without breaking backward compatibility), but a member of the libs team will surely explain that in more details.

**Comment by Mark-Simulacrum** [comment]
I don't personally think that we'd be interested in exposing constructors here as it both freezes our implementation and provides little to no downstream benefit (IntoInnerError has no complex logic or anything like that).
