### ISSUE TITLE
Update doc examples that use ? (Carrier) to use Termination

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#49233]
Blocked on https://github.com/rust-lang/rust/pull/49162

Example: https://github.com/rust-lang/rust/blob/c19264fa835a1eca86de4fd2e86a87b3919e57cf/src/libstd/fs.rs#L40-L49

Instead of:

```rust
use std::fs::File;
use std::io::prelude::*;

# fn foo() -> std::io::Result<()> {
let mut file = File::create("foo.txt")?;
file.write_all(b"Hello, world!")?;
# Ok(())
# }
```

We can now do:

```rust
use std::fs::File;
use std::io::Error;
use std::io::prelude::*;

fn main() -> Result<(), Error> {
    let mut file = File::create("foo.txt")?;
    file.write_all(b"Hello, world!")?;
    Ok(())
}
```

Which can be copied/pasted straight from the docs such that it will compile, unlike the old example

**Comment by steveklabnik** [comment]
Big 👍 from me

**Comment by GuillaumeGomez** [comment]
Seems a good idea to me as well.

**Comment by QuietMisdreavus** [comment]
I think this will be a good thing for combating the most common error of pasting the trimmed examples into `fn main()` without seeing or considering the `?`. Being able to have main return the error like that will greatly help cut down the boilerplate these currently have, and allow us to stop hiding most of the test.

**Comment by frewsxcv** [comment]
cool, i'll start working on this then 🤸‍♂️

**Comment by frewsxcv** [comment]
opened a pr for this: https://github.com/rust-lang/rust/pull/49357
