### ISSUE TITLE
Suggest adding ' for incorrect loop labels

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#49240]
```rust
fn main() {
    label: loop {}
	//     ^^^^ error: expected identifier, found keyword `loop`
}
```
In situations like these, a more helpful suggestion would be to change `label` to `'label`. I imagine this error could be special cased to look at the identifier and suggest something different for `loop`/`while`/`for`.

**Comment by ehuss** [comment]
This appears to be resolved by #81236.

```
error: malformed loop label
 --> src/main.rs:2:5
  |
2 |     label: loop {}
  |     ^^^^^ help: use the correct loop label format: `'label`
```
