### ISSUE TITLE
Better error message for `..` in struct patterns not in last position

### ISSUE THREAD

**Issue by Badel2** [rust-lang/rust#49257]
Since the `let P(.., y) = p;` syntax is allowed in unnamed patterns, people will try the same in named patterns, `let P { .., y } = p;`,and it won't work. Right now the error is
```
error: expected `}`, found `,`
   |
13 |     let Point { .., y } = a;
   |                   ^ expected `}`
```
followed by other errors about "pattern does not mention field x". Test code [playground link](https://play.rust-lang.org/?gist=507f4376c637ff7709c11925bc82b6c1&version=nightly)

```rust
struct Point { x: u8, y: u8 }
struct P(u8, u8);

fn main() {
    // Unnamed patterns allow `.., y`
    let p = P(0, 0);
    let P(x, ..) = p;
    let P(.., y) = p;
    
    // But named patterns don't
    let a = Point { x: 0, y: 0 };
    let Point { x, .. } = a; // works
    let Point { .., y } = a; // lots of errors
}
```

Adding a clear error message should be pretty easy, just check if there is a comma after `DotDot` and display a better error message "`..` must always be the last field, and it cannot have a trailing comma". Actually, I think this is the code that checks if `..` is followed by a `}`, so adding the `,` check should be pretty straight-forward:

https://github.com/rust-lang/rust/blob/c19264fa835a1eca86de4fd2e86a87b3919e57cf/src/libsyntax/parse/parser.rs#L3672-L3677

**Comment by Badel2** [comment]
An alternative would be allowing `..` anywhere in struct patterns, to keep it similar to tuple patterns, but that would probably need an RFC, right?

Anyway, if someone wants to work on this issue, go ahead, otherwise I will fix it when I have some free time.

**Comment by scottmcm** [comment]
I think that it should remain accepted only at the end, the same as in struct literals.  Tuple patterns need the flexibility, but struct patterns are named, so there's no reason to every have it anywhere but the end.

**Comment by ordovicia** [comment]
I'll take this.
