### ISSUE TITLE
error: failed to load source for a dependency on 'cc'

### ISSUE THREAD

**Issue by arbitrix** [rust-lang/rust#49269]
./x.py build && sudo ./x.py install

Doesn't work.

error: failed to load source for a dependency on 'cc'.

**Comment by sanxiyn** [comment]
It would be appreciated if you could provide more details, such as your environment. While it doesn't work for you, it works for many people.

**Comment by mceier** [comment]
I have the same problem on gentoo (using rust overlay and rust-9999 package, which builds rust from git). The build issue was introduced between todays rust version and "rustc 1.26.0-dev (24e679c37 2018-03-14)" - this is the last version I have installed.

Here's the error message from the log:

> running: /var/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /var/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/bootstrap/Cargo.toml --verbose --locked --frozen
> error: failed to load source for a dependency on `cc`
> 
> Caused by:
>   Unable to update registry `https://github.com/rust-lang/crates.io-index`
> 
> Caused by:
>   failed to update replaced source registry `https://github.com/rust-lang/crates.io-index`
> 
> Caused by:
>   failed to read root of directory source: /var/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/vendor
> 
> Caused by:
>   No such file or directory (os error 2)
> Traceback (most recent call last):
>   File "x.py", line 20, in <module>
>     bootstrap.main()
>   File "/var/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/bootstrap/bootstrap.py", line 800, in main
>     bootstrap(help_triggered)
>   File "/var/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/bootstrap/bootstrap.py", line 780, in bootstrap
>     build.build_bootstrap()
>   File "/var/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/bootstrap/bootstrap.py", line 606, in build_bootstrap
>     run(args, env=env, verbose=self.verbose)
>   File "/var/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/bootstrap/bootstrap.py", line 148, in run
>     raise RuntimeError(err)

'cc' - I guess it means, it can't find the C++ compiler - I don't have clang installed (though I have llvm-4, llvm-5 and llvm-6). I have gcc-7.3.0 and gcc-6.4.0. cc is gcc-7.3.0.

**Comment by ExpHP** [comment]
The `cc` in the error message is a bit of a red herring. It means the [`cc` crate](https://crates.io/crates/cc); it's searching for a vendored source of the crate and failing.

I don't know too much about the build process for a global install, but here's a [similar issue](https://github.com/rust-lang/rust/issues/40108) about the (older) Makefile-based build process, which apparently expects to find vendored sources when run with `sudo` (though a much nicer error is given there).  The circumstances here may be the same.

**Comment by Randl** [comment]
I found a relatively simple solution to this:
1. commented out the following line https://github.com/rust-lang/rust/blob/master/src/bootstrap/bootstrap.py#L791
2. run install with `sudo -H` instead of `sudo`.

**Comment by qknight** [comment]
@randl: you probably are refering to:
https://github.com/rust-lang/rust/blob/bc87c71d860d2b667a0981c059032240fd998955/src/bootstrap/bootstrap.py#L792

thanks for pointing out!
