### ISSUE TITLE
provide suggestions for typoed attributes

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#49270]
````rust
#[marco_use]
extern crate clap
````
It would be nice to have typo suggestions for mistyped attributes.
Maybe something like
````
 --> src/main.rs:1:1
  |
1 | #[marco_use]
  | ^^^^^^^^^^^^
  |
  = help: add #![feature(custom_attribute)] to the crate attributes to enable
  = help: you could try the attribute 'macro_use'
````

**Comment by abonander** [comment]
What attributes should this search for? Built-ins only? Imported proc-macro attributes?

**Comment by HeroicKatora** [comment]
A mechanism similar to the current suggestions for unscoped methods would suggest itself. With the added difficulty that of course macros are not available through explicit import (or the prelude), I would prefer have the compiler mention which instance of `#[macro_use]` but I don't think this is required in most instances.

The main issue I had with the current mechanism are that the warning becomes

```
error[E0658]: The attribute `tests` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
 --> src/lib.rs:1:1
  |
1 | #[tests]
  | ^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
```

where E0658 only refers to switching to nightly and adding additional feature gates. 

```
An unstable feature was used.

Erroneous code example:

[…]

If you're using a stable or a beta version of rustc, you won't be able to use
any unstable features. In order to do so, please switch to a nightly version of
rustc (by using rustup).
```

This particular explanation does not seem helpful in that situation and only creates more confusion. The offered description simply does not apply, no unstable feature has been used, else the compiler would suggest a concrete feature gate as well (right?).
