### ISSUE TITLE
mem::replace don't actually mutate the destination on Android

### ISSUE THREAD

**Issue by jdm** [rust-lang/rust#49282]
I have a [branch of Servo](https://github.com/jdm/servo/tree/layoutstuff) which crashes when run on Android because a [key use of mem::replace](https://github.com/jdm/servo/blob/layoutstuff/components/layout/inline.rs#L274-L283) does not actually cause the destination to change values. When I add `println!("{:?}", self.pending_line)` before and after the mem::replace, on desktop the values are updated as expected, but on Android the original value remains.

When I use either of the following instead:
```rust
self.pending_line = Line::new(self.floats.writing_mode, &self.minimum_metrics);
```
or
```rust
let mut new_line = Line::new(self.floats.writing_mode, &self.minimum_metrics);
mem::swap(&mut self.pending_line, &mut new_line);
```
then `self.pending` is updated as expected and Servo does not crash on Android.

**Comment by jdm** [comment]
The following also works:
```rust
        let line = mem::replace(&mut self.pending_line,
                             Line::new(self.floats.writing_mode, &self.minimum_metrics));
        let line = mem::replace(&mut self.pending_line,
                             Line::new(self.floats.writing_mode, &self.minimum_metrics));

```
(yes, performing the same operation twice)

**Comment by scottmcm** [comment]
Hmm, it looks like that type is pretty large (https://github.com/jdm/servo/blob/layoutstuff/components/layout/inline.rs#L221-L245) so will be hitting the simd path in swap (https://github.com/rust-lang/rust/blob/master/src/libcore/ptr.rs#L194-L227) that's currently disabled on some other platforms, so I wonder if the bug's in there somewhere...

**Comment by jonas-schievink** [comment]
Triage: Not sure if this is still an issue.

Updated libcore SIMD code:

https://github.com/rust-lang/rust/blob/8ce3f840ae9b735a66531996c32330f24b877cb0/src/libcore/ptr/mod.rs#L418-L465

**Comment by jdm** [comment]
Realistically I don't think there's any point to leaving this open. We never tried to make a minimal reproduction, and nobody else has stumbled across this issue in the intervening five years.

**Comment by scottmcm** [comment]
Agreed; the implementation of `replace` is also very different now after #83022

https://github.com/rust-lang/rust/blob/70adb4e5b4c8f8bde4ade0edcb0435ff7bf31281/library/core/src/mem/mod.rs#L908-L912
