### ISSUE TITLE
XID_Start / XID_Continue might not be quite right

### ISSUE THREAD

**Issue by graydon** [rust-lang/rust#4928]
http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1518.htm

The ISO JTC1/SC22/WG14 (C language) think that possibly UTR#31 didn't quite hit the nail on the head in terms of defining identifier syntax. They have a couple tweaks in mind. Consider following their lead.

**Comment by yongqli** [comment]
I would really like to see Unicode superscripts allowed, as subscripts already are. I would be willing to make a pull request to implement this.

**Comment by steveklabnik** [comment]
Triage: unicode identifiers are still feature gated, no changes.

**Comment by rurban** [comment]
XID_Start / XID_Continue has one small bug, and is not enough to get proper unicode identifiers safe. See also http://websec.github.io/unicode-security-guide/
You need to add mixed script protections (TR39 Restriction levels), normalize them (to NFC or NFKC_Casefold), and maybe disallow confusables.
A short overview is here: http://perl11.org/blog/unicode-identifiers.html

bug: U+3164 HANGUL FILLER and U+ffa0 are wrongly specified as ID_Continue. Disallow these.

**Comment by Centril** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/55467.

**Comment by SimonSapin** [comment]
@Centril, is this specific issue actually addressed in https://github.com/rust-lang/rfcs/pull/2457 or tracked in https://github.com/rust-lang/rust/issues/55467? As far as I can tell they specify unmodified `XID_Start` and `XID_Continue`.

**Comment by Centril** [comment]
@SimonSapin at least tracked in that issue to consolidate; tho I didn't read the issue description in detail.

**Comment by SimonSapin** [comment]
I’ve added this as a checkbox in Unresolved Questions in https://github.com/rust-lang/rust/issues/55467
