### ISSUE TITLE
`std_unicode::char::decode_utf16` should be in `core`

### ISSUE THREAD

**Issue by lfairy** [rust-lang/rust#49319]
The [`decode_utf16`](https://doc.rust-lang.org/std_unicode/char/fn.decode_utf16.html) function currently lives in the `std_unicode` crate. But, as far as I can tell, this function doesn't depend on any Unicode tables and has no reason to be in this crate.

I suggest moving this function (and its associated iterator) into the `core` crate. This will allow for decoding UTF-16 text under `#![no_std]` in stable Rust.

**Comment by SimonSapin** [comment]
I agree that there is no reason for this not to be in libcore. Feel free to submit a PR and ping me for review.

More generally I wonder if we can rely of various platforms’ linkers to remove unused tables, and if so if there’s any reason to keep `std_unicode` from `core` at all. But that doesn’t need to block moving `decode_utf16` specifically.

**Comment by SimonSapin** [comment]
https://github.com/rust-lang/rust/pull/49698 fixes this.
