### ISSUE TITLE
rustdoc: The short description of #[doc(cfg(target_feature = ...))] shouldn't spell out "target feature"

### ISSUE THREAD

**Issue by kennytm** [rust-lang/rust#49334]
* Repro: https://doc.rust-lang.org/nightly/core/arch/x86_64/index.html
* Discussion: https://twitter.com/QuietMisdreavus/status/977567670131359744

![The words "target feature" are redundant](https://user-images.githubusercontent.com/103023/37865771-4b57bff4-2fbc-11e8-9432-5354f1a92113.png)

rustdoc's short description of `#[doc(cfg(target_feature = ...))]` is showing something like \[x86-64 and target feature `avx`\]. The words "target feature" is unnecessary since usually it is clear what `avx` means from context, i.e. \[x86-64 and `avx`\] should be clear enough.

**Comment by QuietMisdreavus** [comment]
Notes to self:

The issue at hand is the fact that the "short text" is overridden when the condition is combined with others. The target features are supposed to only show "`avx`" when they're by themselves, as shown in the OP of https://github.com/rust-lang/rust/pull/48759. The offending snippet:

https://github.com/rust-lang/rust/blob/31ae4f9fde9b23100c26e5642030128a7e1444ef/src/librustdoc/clean/cfg.rs#L410-L419

The *easiest* way to fix this is to never print "target feature", even in the long form, but that text is still valuable there.
