### ISSUE TITLE
Trait "constructor" methods don't get coercions?

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#49356]
Working on #41414, I found [this error](https://play.rust-lang.org/?gist=0e82ff6c3213d770794f586e40e62d2b&version=nightly) that surprised me:
```rust
#![feature(try_trait)]
fn main() {
    let my_string = "hello".to_string();
    let _x: Result<&str, i32> = {
        std::ops::Try::from_ok(&my_string)
        //~^ type mismatch resolving `<std::result::Result<&str, i32> as std::ops::Try>::Ok == &std::string::String`
    };
}
```
I'd expected that it'd work, since the trait method is `-> Self`, and the result of the block is fully constrained, and writing it this way of course works:
```rust
<Result<&str, i32> as std::ops::Try>::from_ok(&my_string)
```

Of course, this may well just be a normal "mixing coercions and inference is annoying" case that people who understand inference wouldn't have expected to work :sweat_smile:

**Comment by cjgillot** [comment]
The diagnostic is now correctly normalized
```
error[E0271]: type mismatch resolving `<Result<&str, i32> as Try>::Output == &String`
 --> <source>:5:9
  |
5 |         std::ops::Try::from_output(&my_string)
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `str`, found struct `String`
  |
  = note: expected reference `&str`
             found reference `&String`
```
