### ISSUE TITLE
NLL breaks functions with intermingled lifetimes in return type when returned value is a (non-borrowed) associated type

### ISSUE THREAD

**Issue by daboross** [rust-lang/rust#49354]
Code which returns this kind of complicated expression involving two different lifetimes compiles under normal compilation conditions, but fails with `#![feature(nll)]`.

Minified example (courtesy of @matthewjasper).

```rust
#![feature(nll)]
trait Visitor<'de> {
    type Value;
}

impl<'a, 'de: 'a> Visitor<'de> for &'a () {
    type Value = ();
}

//error: free region `'a` does not outlive free region `'de`
fn visit_seq<'de: 'a, 'a>() -> <&'a () as Visitor<'de>>::Value {}
//                                                             ^^

fn main() {}
```

working playground: https://play.rust-lang.org/?gist=5f08095fda551daa89fadf0b8566989e&version=nightly
broken playground: https://play.rust-lang.org/?gist=a5d0d7619f610d94fe316c80b0f1dfbb&version=nightly

<details>
 <summary>Original post / serde_derive generated code example</summary>

The source code is anything like the following:

```rust
#![feature(nll)]
extern crate sede;
#[macro_use]
extern crate serde_derive;

#[derive(Deserialize)]
struct X<'a> {
    #[serde(borrow)]
    field: &'a [u8]
}
```

Pared down generated code:

```rust
#![feature(nll)]
extern crate serde;
pub struct X<'a> {
    pub field: &'a [u8],
}
impl<'de: 'a, 'a> serde::Deserialize<'de> for X<'a> {
    fn deserialize<__D>(__deserializer: __D) -> serde::export::Result<Self, __D::Error>
    where
        __D: serde::Deserializer<'de>,
    {
        struct __Visitor<'de: 'a, 'a> {
            marker: serde::export::PhantomData<X<'a>>,
            lifetime: serde::export::PhantomData<&'de ()>,
        }
        impl<'de: 'a, 'a> serde::de::Visitor<'de> for __Visitor<'de, 'a> {
            type Value = X<'a>;
            fn expecting(
                &self,
                formatter: &mut serde::export::Formatter,
            ) -> serde::export::fmt::Result {
                serde::export::Formatter::write_str(formatter, "struct X")
            }
            #[inline]
            fn visit_seq<__A>(
                self,
                mut __seq: __A,
            ) -> serde::export::Result<Self::Value, __A::Error>
            where
                __A: serde::de::SeqAccess<'de>,
            {
                let __field0 = match serde::de::SeqAccess::next_element::<&'a [u8]>(&mut __seq)? {
                    Some(__value) => __value,
                    None => {
                        return Err(serde::de::Error::invalid_length(
                            0usize,
                            &"tuple of 1 elements",
                        ));
                    }
                };
                Ok(X { field: __field0 })
            }
        }
        unimplemented!()
    }
}
fn main() {}
```

This code compiles without NLL enabled, but with NLL, fails with:

```
error: free region `'a` does not outlive free region `'de`
  --> src/main.rs:31:21
   |
31 |                 let __field0 = match serde::de::SeqAccess::next_element::<&'a [u8]>(&mut __seq)? {
   |                     ^^^^^^^^
```

Playground working: https://play.rust-lang.org/?gist=cb213e15287e06e85fb7a55412967b23&version=nightly

Playground failing: https://play.rust-lang.org/?gist=c4745b7f9e40f16bd7fe62f27d9c534b&version=nightly

</details>

**Comment by matthewjasper** [comment]
Minified.

```rust
trait Visitor<'de> {
    type Value;
}

impl<'a, 'de: 'a> Visitor<'de> for &'a () {
    type Value = ();
}

//error: free region `'a` does not outlive free region `'de`
fn visit_seq<'de: 'a, 'a>() -> <&'a () as Visitor<'de>>::Value {}
//                                                             ^^

fn main() {}
```

**Comment by daboross** [comment]
This was broken sometime in between nightly-2018-03-07 and nightly-2018-03-15.

There don't seem to be any nightly builds available between those two dates, so I'm not sure how to narrow it down further.

**Comment by davidtwco** [comment]
I'll take a go at this issue.

**Comment by davidtwco** [comment]
An update after a little bit of digging, I've bisected it down to 8c4ff22a2d745097197c659ef9e3b04b8ceeb070 (ie. the PR #48411).

**Comment by davidtwco** [comment]
An update on my progress with this: I've got the logging for the some recent commit near HEAD and a commit before the regression was introduced. 

#48411 was a pretty large change and there's no clear place (to my untrained eyes) where it might have introduced the regression. I'm struggling to make heads of tails of what exactly is happening. [I've got the logging in a gist](https://gist.github.com/davidtwco/17fa79954b4e4bb40633797087df281e).

**Comment by nikomatsakis** [comment]
@davidtwco ah indeed that is a big PR =) I guess it's not surprising that it has a bit of fallout. I imagine I'll have to dig a bit deeper. I wonder if we can find a more minimal example.

**Comment by nikomatsakis** [comment]
I wonder if https://github.com/rust-lang/rust/issues/49824 is related.

**Comment by davidtwco** [comment]
I'm going to unassign myself from this issue. Not got a lot of time over the next month or so and don't want this priority issue to be held up.
