### ISSUE TITLE
ICE: Region parameter out of range when substituting in region...

### ISSUE THREAD

**Issue by cynecx** [rust-lang/rust#49362]
```rust
#![feature(generic_associated_types)]

struct S;

trait Trait {
    type Associated<'a>;
}

impl Trait for S {
    type Associated<'a> = &'a ();
}

fn main() {}
```

```
error: internal compiler error: librustc/ty/subst.rs:439: Region parameter out of range when substituting in region 'a (root type=Some(TestIterItem<'a>)) (index=0)

thread 'rustc' panicked at 'Box<Any>', librustc_errors/lib.rs:488:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: aborting due to 2 previous errors
```

[Rust playground](https://play.rust-lang.org/?gist=755945d9d30e59068194aebe6b9fdf3a&version=nightly&mode=debug)

Probably related: https://github.com/rust-lang/rust/issues/47309

I can reproduce this with `rustc 1.26.0-nightly (f5631d9ac 2018-03-24)`.

**Comment by matthewjasper** [comment]
Generic associated types aren't implemented past syntax yet, so this is probably expected. cc #44265

**Comment by 0ndorio** [comment]
This does not only happen with generic associated lifetimes but with any generic associated type:

```rust
#![feature(generic_associated_types)]

pub trait MyTrait {
    type InternalType<A>;
}

pub struct TypeWithLifetime<A> {
    _dummy: A
}

pub struct MyStruct {}

impl MyTrait for MyStruct {
    type InternalType<A> = TypeWithLifetime<A>;
}
```

Rust playground: https://play.rust-lang.org/?gist=c36f51038511f3e6568b1b2c866f2ca3&version=nightly&mode=debug

Maybe its worth to disable the feature flag or add a compiler error warning if the flag is used, until the feature implementation progressed further.

**Comment by estebank** [comment]
Triage: still happens.

**Comment by hellow554** [comment]
Slightly reduced, no need for a new `struct S`, just use the unit type
```
#![feature(generic_associated_types)]

trait Trait {
    type Associated<'a>;
}

impl Trait for () {
    type Associated<'a> = &'a ();
}

fn main() {}
```

**Comment by estebank** [comment]
Closing in favor of #62521.

**Comment by hellow554** [comment]
@estebank although they are two different ICE messages?

> error: internal compiler error: Region parameter out of range when substituting in region 'a (root type=Some(&'a ())) (index=0)

vs

> error: internal compiler error: src/librustc_mir/borrow_check/nll/universal_regions.rs:764: cannot convert `ReEarlyBound(0, 'a)` to a region vid
