### ISSUE TITLE
Rustdoc doesn't render all `impl Trait` details

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#49373]
Given a function definition

```rust
pub fn timeout<'a>(&'a mut self, duration: Duration) -> impl Future<Item=(), Error=!> + 'a
```

then this is currently (`rustc 1.26.0-nightly (482a913fb 2018-03-25)`) rendered as

![impl-trait-doc](https://user-images.githubusercontent.com/81079/37897532-a8d1ed0a-30e6-11e8-9152-796512943a04.png)

There are two very important bits of information missing from this:

 * The associated types of the `Future` trait
 * The lifetime bound on the returned type

**Comment by Manishearth** [comment]
Hmm, I'm unable to reproduce this on the latest nightly -- can you provide a link to the complete code causing this?

(Will try the older nightly soon)

**Comment by Nemo157** [comment]
Ah, this also requires re-exporting from a facade crate. I can't show my original code, but here's a quick example that repros it: https://github.com/Nemo157/rust-lang-rust-issue-49373, in `inner/struct.Timer.html` it does show the details, but not in `temp/struct.Timer.html`.

**Comment by Manishearth** [comment]
https://github.com/rust-lang/rust/pull/49427
