### ISSUE TITLE
Term and getopt crates show in the standard library documentation

### ISSUE THREAD

**Issue by matthewjasper** [rust-lang/rust#49388]
These crates were added by #48588, but should probably be hidden. See https://doc.rust-lang.org/nightly/term/index.html.

**Comment by QuietMisdreavus** [comment]
@Mark-Simulacrum How do crates get included in the std docs? I thought other private dependencies were already being excluded.

**Comment by Mark-Simulacrum** [comment]
I don't see it being built locally so it's probably an old version of term, though I'm not certain. We'd have to figure out whether these are a recent-ish version and go from there, probably...

**Comment by Mark-Simulacrum** [comment]
Oh, these aren't from std's docs I think -- but rather tests' docs. I don't know if it's actually *too* much of a problem and am somewhat inclined to just leave it, but I suppose we could fix it if necessary. Should just be a matter of adding `-p test` to the invocation of Cargo here:https://github.com/rust-lang/rust/blob/master/src/bootstrap/doc.rs#L556

**Comment by ollie27** [comment]
This was triggered by #49193. The docs for `test` are currently only built when the compiler docs are enabled. The question is do we want the docs for the `test` crate included with the `std` docs or the compiler docs?

**Comment by GuillaumeGomez** [comment]
I just built the docs once again and didn't have the problem. I suppose the issue can therefore be closed.

**Comment by ollie27** [comment]
@GuillaumeGomez you need to enable the compiler docs to reproduce this.

**Comment by GuillaumeGomez** [comment]
You mean besides running `./x.py doc --stage 1`?

**Comment by ollie27** [comment]
Yeah, you need to have `compiler-docs = true` in your `config.toml`. Anyway I've submitted #49465 to fix this.

**Comment by ollie27** [comment]
Could this be reopened? It is clearly not fixed: https://doc.rust-lang.org/nightly/term/index.html. This could also do with a `regression-from-stable-to-beta` tag as it affects beta now: https://doc.rust-lang.org/beta/term/index.html.
