### ISSUE TITLE
NLL produces ungreat error messages with free regions

### ISSUE THREAD

**Issue by bobtwinkles** [rust-lang/rust#49397]
NLL produces the following ungreat diagnostic message:

```
error: free region `` does not outlive free region `'a`
   --> src/main.rs:124:17
    |
124 |             let a = self.img.sub_image();
    |                 ^
```
Note the completely unnamed free region. I'm not sure what a good solution to this is, but it's probably not what is produced right now =)

When compiling the code here https://play.rust-lang.org/?gist=b7d7c69a4eb38a108409bb34a0a6ae46&version=nightly

**Comment by bobtwinkles** [comment]
The unnamed region here is the automatic region created for the lifetime of the parameters.
Naming it as so:
```rust
 fn next<'b>(&'b mut self) -> Option<Self::Item> {
```
Produces the much better error message:
```
error: free region `'b` does not outlive free region `'gen_parent`
   --> src/main.rs:125:17
    |
125 |             let a = self.img.sub_image();
    |                 ^
```

**Comment by nikomatsakis** [comment]
@bobtwinkles yeah so the empty string comes from the fact that it's an anoymous region, but what worries me *more* is that we highlight such random code. This is particularly evident in #49493.

**Comment by nikomatsakis** [comment]
We have a lot of issues about this. I'm going to close this as a dup of #51027
