### ISSUE TITLE
better error message when `?` is applied to `collect()`

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#49391]
This code:

```rust
fn main() -> Result<(), ()> {
    vec![Ok(2)].into_iter().collect()?;
    Ok(())
}
```

gives a terrible error:

```
error[E0284]: type annotations required: cannot resolve `<_ as std::ops::Try>::Ok == _`
 --> src/main.rs:4:5
  |
4 |     vec![Ok(2)].into_iter().collect()?;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

The solution is to do `.collect::<Result<Vec<_>,_>>()?` ([playground](https://play.rust-lang.org/?gist=f196da11391554c650328e74c8e9368f&version=nightly))

**Comment by nikomatsakis** [comment]
I think that the way to fix this is -- first and foremost -- to remove E0284, which is basically the same as E0282 but with "less good" error reporting. To do that, we want to redirect this code:

https://github.com/rust-lang/rust/blob/097efa9a998d4f3a4aee3af126e8f8a9eba1ae07/src/librustc/traits/error_reporting.rs#L1264-L1273

so that it invokes the `need_type_info` fn:

https://github.com/rust-lang/rust/blob/097efa9a998d4f3a4aee3af126e8f8a9eba1ae07/src/librustc/infer/error_reporting/need_type_info.rs#L89

as it happens, other code from trait error reporting file already invokes `need_type_info`. For example, this arm lies just a small bit of code above:

https://github.com/rust-lang/rust/blob/097efa9a998d4f3a4aee3af126e8f8a9eba1ae07/src/librustc/traits/error_reporting.rs#L1243-L1249

so I think we just need to change [this hunk](https://github.com/rust-lang/rust/blob/097efa9a998d4f3a4aee3af126e8f8a9eba1ae07/src/librustc/traits/error_reporting.rs#L1265-L1273) to work the same way.

**Comment by nikomatsakis** [comment]
That said, my guess is that this won't fix the original example. To do that, we have to extend `need_type_info` to also make suggestions to use turbofish where appropriate. But it's a first step, and then we can go further!

**Comment by balajisivaraman** [comment]
@nikomatsakis, Following from IRC, I'll pick this one up and begin working on this. Thank you for the helpful tips. :-)

**Comment by balajisivaraman** [comment]
@ytausky, Unfortunately, I've not made much progress on this. (I'm still slowly working my way through the [Rustc Guide](https://github.com/rust-lang-nursery/rustc-guide).) You can pick it up if you'd like.

**Comment by fcofdez** [comment]
@ytausky are you still interested in this issue? If not, I would like to pick it up.

**Comment by saleemjaffer** [comment]
@ytausky I would like to give this a shot. I'm new to rust.

**Comment by estebank** [comment]
This code now compiles. @nikomatsakis do you have another example of this failing? Or should we close this?

**Comment by Mark-Simulacrum** [comment]
Going to proactively close, Niko can reopen if needed.

**Comment by estebank** [comment]
The case still repros, I was checking the wrong code.

**Comment by estebank** [comment]
Output with #65951:

```
error[E0284]: type annotations needed
 --> file12.rs:2:29
  |
2 |     vec![Ok(2)].into_iter().collect()?;
  |                             ^^^^^^^
  |                             |
  |                             cannot infer type
  |                             help: consider specifying the type argument in the method call: `collect::<B>`
  |
  = note: cannot resolve `<_ as std::ops::Try>::Ok == _`
```

**Comment by hwalinga** [comment]
Don't know if the compiler can be a bit more smarter about the error message on this case, but I stumbled upon here when I wrote (with `rdr` a buffered reader):

```
let lines: Vec<_> = rdr.lines().collect()?;
```

Giving the strange:

```
error[E0277]: the size for values of type `str` cannot be known at compilation time
```

From: https://stackoverflow.com/questions/67644464/why-can-you-not-use-question-mark-directly-on-collect-in-rust

**Comment by estebank** [comment]
@hwalinga could you file a new ticket with a link to a reproduction care on [the playground](https://play.rust-lang.org/)? A quick attempt at [reproducing the StackOverflow case yielded a "type annotations needed" error](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=1d134b93fad4d25c628103a6d671bc28) and following the suggestions for it leads you in the right direction, but I might be sinning of being overly familiar with what the compiler is trying to say.
