### ISSUE TITLE
lightweight submodule landing

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#49413]
The goal is to make landing submodule updates quicker and use fewer resources. The high level idea is that we would only run the tests for the updated submodule, not the entire bootstrap and test suite, e.g., to update the Cargo submodule we would only run `.x.py src/tools/cargo`. That makes landing submodule updates quicker and easier and lets us update more often. This is a little bit more complicated than it sounds.

Key parts of this work:
* [ ] tools and the compiler/libs should use different Cargo.lock files so that updating a submodule cannot break the compiler/libs.
* a concept of a submodule-only commit. This should probably be opt-in and explicit, so that tools like bisect can skip these commits (e.g., a keyword in the commit message). These should only update submodules and touch the 'tools' Cargo.lock.
*  when testing a submodule commit we should pull artefacts for `HEAD~1` rather than bootstrapping a toolchain
* [ ] the build system needs to be able to build and test submodules using these artefacts
* [ ] CI and build system (my understanding is vague here) knows only to run the subset of tests for these commits (and detect which tests to run).
* [ ] these commits do not create new artefacts
* [ ] the dist machinery should ignore these commits when producing a nightly (and I guess beta, stable)
* [ ] update tools such as perf/bisect which need artefacts to ignore these commits

cc @alexcrichton @Mark-Simulacrum could you add more detailed mentoring instructions please?

**Comment by iancormac84** [comment]
I'd like to help with this, please.

**Comment by Mark-Simulacrum** [comment]
I think the first step is to implement the first bullet point. I think what needs to happen there is that we need to exclude `src/tools/cargo` and `src/tools/rls` from the Cargo.toml in the root of the tree. After running x.py for cargo and rls, I would expect a lockfile to be created in the Cargo submodule (the RLS already has a lockfile). We would want to put up a PR to https://github.com/rust-lang/cargo to add that generated lockfile, and then include the submodule update alongside the Cargo.toml exclude change.

I think this first step is likely to cause other problems, but I can't think of anything immediate. Let's try and land it, and then I can try and come up with instructions for the other steps.

**Comment by ehuss** [comment]
@iancormac84 Are you still working on this?  If not, I can take a look.

@Mark-Simulacrum or @nrc  It seems like one of the original benefits of using a workspace is that rls would use the same version of cargo and rustfmt, and avoid compiling those twice.  If they don't share the same workspace, I don't see a clear way to do that.  Did you have in mind some alternative to using `patch` for RLS?

Long term are you thinking that submodules would still be updated manually through the normal means (PR and bors)?  Or is the intent that it would be automated somehow?

I did some preliminary testing, and just excluding cargo and rls from the workspace doesn't seem to break anything obvious.

**Comment by iancormac84** [comment]
I'm only now seeing the replies. Sorry about that. Yes, @ehuss you can take over.

**Comment by ehuss** [comment]
> Cargo and RLS share a workspace for the time being

I've been testing it and it seems to work ok.  The profiles have to be duplicated, but maybe later it can use [config profiles](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#config-profiles) or motivate some kind of nested workspace feature.

I think it would be helpful to have a clear understanding of the rules for organizing the packages.  In general I'm uncertain of the original reasoning for using a workspace.  I think at a minimum this new workspace would need to have rls, cargo, and rustfmt.  But should it also include other frequently updated submodules (like clippy)?  Or maybe clippy could be a standalone package (in no workspace)?  What about less often updated submodules like miri?  If we later need a third workspace, it might require reorganizing the directories.

**Comment by alexcrichton** [comment]
Some motivations for using a workspace are:

* Cut down on build time by sharing precompiled dependencies. For example compiling the RLS and compiling Cargo should only compile Cargo once
* When updating a dependency, there's only one location to update it. No need to propagate bugfixes to multiple locations.
* Ensure that we're using the same version of upstream crates to avoid issues where Cargo has a fixed curl-sys (for example) but rls accidentally has a buggy one.

Sorry I haven't been following this super closely, but I'd ideally prefer to stick to the "one workspace" if we can. There's not a huge amount of sharing between the compiler and various tools for dependencies, but I'd expect that to increase over time. The biggest "offenders" in terms of pulling in big crates from crates.io are rustdoc and the ones you mentioned (rls + cargo + rustfmt). 

One thing we could try to get away with is:

* Use two workspaces, one for the compiler and one for everything else
* Add a lint that crates.io deps are the same version in these two workspaces (aka 0.2.2 and 0.2.3 don't show up across the two workspaces).

I'm all for trying different strategies though, any amount of automation probably can't be worse than what we have today! (no automation)

**Comment by ehuss** [comment]
One idea I had would be to only allow these fast-track merges to happen if only entries for tools in the lock file were updated.  If any shared dependency between tools and the compiler changes, then it would run a regular build/test.  This would run under the expectation that tools don't change those shared dependencies often (I could look back and see if that assumption is true).

In general, I'm thinking of writing a tool that would do all the work for updating a submodule (running the git commands to prepare it, update the lockfile if necessary, prepare a nice commit message, optionally run tests locally, etc.).  Maybe I'll put that together and see if anyone else finds it useful.

**Comment by alexcrichton** [comment]
FWIW I'm very wary of testing *less* when we have tool changes. To start out I think it'd be great to have some automation, but tool updates tend to be the ones that wreak the most havoc in the test suite. Without actually doing a full build I think we'd run a very high risk of checking in a change that otherwise can't pass tests the next time. I think it's an easily separable step to later figure out if we can bootstrap less.

**Comment by ehuss** [comment]
@nrc How often do you think submodules should be updated?

**Comment by ehuss** [comment]
I'm not really sure how feasible it would be to have fully automated updates, even if the tools are in a separate workspace.  One concern I have is about running `cargo update`, and what kind of policy there would be for updating dependencies.  I imagine using a blanket `cargo update` to update everything all the time may not be desirable.  However, using `cargo update -p SPEC` can be unreliable and sometimes needs manual intervention.  Unless I'm misunderstanding the best way to update the lock file.

I put my tool to update submodules and create PRs here: https://github.com/ehuss/subup in case anyone's curious.   It's mostly functional for running it manually, but there's a long list of potential enhancements.

If you're interested, I can use the tool to post certain submodule updates weekly or so.  Since it's mostly automated, I can run tests locally, and perhaps the PRs could get rollup priority so they would mostly be free in terms of CI time.  (I'm not sure how difficult it is to create rollup PRs, they look like a lot of work to me.)

**Comment by jyn514** [comment]
Is this still something we want to do? @ehuss I think you normally do the cargo submodule updates - are they painful? Would they be helped by this issue?

I'm not too worried about the CI time itself, we land a *lot* of PRs and one more for cargo doesn't seem like a big deal.

**Comment by ehuss** [comment]
I'll go ahead and close this out.  In my original investigation (2018!), having different kinds of CI runs seemed too complex for what it was worth. I also tried to build tooling that would detect how updates to a tool could impact other parts of the workspace, and that also hit a dead end of complexity and risk.

Book updates are almost completely automated now, and ride the rollups, so they essentially take 0 resources.

Cargo updates are mostly automated now, though they require manually running a script and approving a PR. They ride the rollups about half the time, so they usually take 0 resources.

Some submodules almost never get updated (like rust-installer), so energy there probably isn't worth it.

Other submodules, like llvm, stdarch, and backtrace get manually updated by their respective maintainers. These I don't think can be made lighter-weight, and I haven't heard anyone complain about making those easier or lighter-weight.

All the other tools have been migrated to subtrees, or removed, which I think removes 90% of the reason for this issue.
