### ISSUE TITLE
Improve documentation for std::io::Seek

### ISSUE THREAD

**Issue by a-coostic** [rust-lang/rust#49414]
A note "seek beyond the end of a stream is allowed, but implementation defined" doesn't make it clear. Was it meant to be "... allowed, but implementation undefined" ?

**Comment by sfackler** [comment]
The term "implementation defined" means that each implementor of `Seek` gets to define how they interpret seeking past the end of a stream..

**Comment by steveklabnik** [comment]
This is a term of art; as such, I think we should leave it alone. We can't explain every term in every place, so I don't think there's anything to do here. Thanks @a-coostic !
