### ISSUE TITLE
Render documentation of lints

### ISSUE THREAD

**Issue by killercup** [rust-lang/rust#49416]
Each of the Clippy lints is documented and the clippy docs are index ([this one](https://rust-lang-nursery.github.io/rust-clippy/v0.0.189/index.html) for the current version) that allows people to easily discover these lints. We should make the rustc built-in lints discoverable in this way as well.

- [ ] Provide tooling to render documentation similar to the Clippy one for the rustc build-in lints
  - generate docs that live next to the error index?
- [ ] We should add documentation to each of the built-in lints
  - might be inspired by Clippy's style
  - provide reasoning and example

**Comment by GuillaumeGomez** [comment]
We should definitely have such a thing. (maybe even extended to other things like compiler options?)

I suggest to generate a markdown file which will then be converted into HTML by rustdoc. Taking a look at how clippy's generated its own file (if that's how it's done) would be a good idea too.

**Comment by GuillaumeGomez** [comment]
cc @steveklabnik

**Comment by steveklabnik** [comment]
Yes, this is done. New lints should get new docs; if any are missing, feel free to open one issue per lint.

**Comment by killercup** [comment]
[This book](https://rust-lang-nursery.github.io/rustc-guide/)? Where's the section on lints?
