### ISSUE TITLE
"Read more" shortening for trait impls chops off link references

### ISSUE THREAD

**Issue by clarfonthey** [rust-lang/rust#49430]
Here's an example: https://doc.rust-lang.org/nightly/std/option/enum.Option.html#impl-Hash

If you notice here, because rustdoc naïvely chops off all lines of the doc but the first, link references get lost. While this particular instance will be solved by autolinking, this doesn't work if you link to something in general.

**Comment by euclio** [comment]
This is also present in the Windows `CommandExt` impl for `std::process::Command`: https://doc.rust-lang.org/std/process/struct.Command.html
