### ISSUE TITLE
Tracking issue for `macros_in_extern` feature

### ISSUE THREAD

**Issue by abonander** [rust-lang/rust#49476]
This is a tracking issue for the `macros_in_extern`. This feature flag enables the usage of macro invocations in `extern {}` blocks:

```rust
macro_rules! emit_foreign_item(
    () => (fn read(fd: int, buf: *mut u8, size: usize) -> int;)
);

extern {
    emit_foreign_item!();
}
```

Declarative maco, proc-macro and proc-macro-attribute invocations are allowed as well. Macro defintions, however, are not.

This feature is unstable because it was recently implemented in #49350 without an RFC. It is considered a discrepancy in macro support and not a new feature. It should be completely backwards-compatible.

**Comment by abonander** [comment]
cc @petrochenkov, @nrc, @jseyfried

**Comment by dtolnay** [comment]
This leak / infinite alloc on invalid syntax needs to be fixed before stabilization: https://github.com/rust-lang/rust/issues/54441.
