### ISSUE TITLE
Rustdoc fails to show `where T: Sized`

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#49477]
https://doc.rust-lang.org/nightly/std/primitive.pointer.html#method.offset is documented as `pub unsafe fn offset(self, count: isize) -> *const T` inside the `impl<T> *const T where T: ?Sized`, but the source code for that method additionally has a `where T: Sized` clause which should be shown in docs.

**Comment by ollie27** [comment]
Duplicate of #24183

**Comment by SimonSapin** [comment]
Oops sorry.
