### ISSUE TITLE
In resolve, re-use ribs to avoid allocation

### ISSUE THREAD

**Issue by catamorphism** [rust-lang/rust#4948]
As per comment in ```resolve::Resolver```

**Comment by alexcrichton** [comment]
I believe resolve has changed quite a bit since this was opened, and I think it's best to track the implementation details of resolve inside of resolve itself to make sure they stay up to date.

**Comment by nagisa** [comment]
This issue is still relevant, that is, we still do allocations (pushes) and deallocations (pops). Maybe we should move from vector to some implementation of stack instead?
