### ISSUE TITLE
rustdoc: section anchor symbol can be difficult to click

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#49485]
Some of the section anchors that appear when you hover over an item can be difficult to click.  It seems to disappear when the mouse transitions over the spacing between the item and the symbol.

![demo](https://user-images.githubusercontent.com/43198/38105847-08732eba-3342-11e8-890a-a38ab32ba497.gif)

Tested on a variety of browsers, all seem to behave similarly.  

Rust 1.25 seems OK (there isn't as much spacing).  I only notice this on nightly (1.26.0-nightly (e5277c145 2018-03-28)).

**Comment by GuillaumeGomez** [comment]
There is already a PR to fix it [here](https://github.com/rust-lang/rust/pull/49510).

**Comment by kzys** [comment]
Resolving? #49510 has been merged.

**Comment by GuillaumeGomez** [comment]
Oh indeed!
