### ISSUE TITLE
std::fs::File functions panic on valid return type

### ISSUE THREAD

**Issue by jhpratt** [rust-lang/rust#49491]
The following code taken directly from documentation will not compile.

```rust
fn main() {
    use std::fs::File;
    use std::io::prelude::*;

    let mut file = File::create("foo.txt")?;
    file.write_all(b"Hello, world!")?;
}
```

The error message is as follows:

```
error[E0277]: the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
 --> example.rs:5:20
  |
5 |     let mut file = File::create("foo.txt")?;
  |                    ^^^^^^^^^^^^^^^^^^^^^^^^ cannot use the `?` operator in a function that returns `()`
  |
  = help: the trait `std::ops::Try` is not implemented for `()`
  = note: required by `std::ops::Try::from_error`

error[E0277]: the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
 --> example.rs:6:5
  |
6 |     file.write_all(b"Hello, world!")?;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot use the `?` operator in a function that returns `()`
  |
  = help: the trait `std::ops::Try` is not implemented for `()`
  = note: required by `std::ops::Try::from_error`

error: aborting due to 2 previous errors
```

[The documentation](https://doc.rust-lang.org/std/fs/struct.File.html#method.create) for `create()` indicates that the function does return `Result<File>`, but the compiler believes it returns `()`. [`write_all()` indicates](https://doc.rust-lang.org/std/fs/struct.File.html#write_all.v) it returns `Result<()>`.

Clearly, both functions implement `std::ops::Try` via `Result`, but an example as basic as this fails on that test.

**Version**

Fails on both stable and nightly.

`rustc --version`
→ `rustc 1.25.0 (84203cac6 2018-03-25)`
→ `rustc 1.26.0-nightly (e5277c145 2018-03-28)`

**Comment by mattico** [comment]
Notice the error message:

>cannot use the `?` operator **in** a function that returns `()`

`main` is a function that returns `()`, so you can't use the `?` operator inside of it.

This restriction is [changing soon](https://github.com/rust-lang/rust/issues/48453), but in the mean time I'd suggest using a different function:

```Rust
use std::fs::File;
use std::io::{self, prelude::*};

fn run() -> io::Result<File> {
    let mut file = File::create("foo.txt")?;
    file.write_all(b"Hello, world!")?;
    
    Ok(file)
}

fn main() {
    run().unwrap();
}
```

**Comment by jhpratt** [comment]
Ah, ok. English can be so finicky — a single word changes everything.

I certainly look forward to the issue you've linked to.

Thanks!

**Comment by mattico** [comment]
Yeah, I was confused when I read the error message too - and I've been speaking English for a while...

**Comment by jhpratt** [comment]
Oh, I'm a native speaker. That's probably _why_ I missed it.
