### ISSUE TITLE
Improve search_ribs in resolve

### ISSUE THREAD

**Issue by catamorphism** [rust-lang/rust#4950]
As per comment: don't use a while loop, and try caching.

**Comment by steveklabnik** [comment]
Update: this code is now in https://github.com/rust-lang/rust/blob/216f6645ef0c93776e9f350f29c02780fb7bf673/src/librustc_resolve/lib.rs#L1742-L1758 and the `for` loop has been fixed.

**Comment by gereeter** [comment]
`search_ribs` and the FIXME seem to both be gone. Should this be closed?

**Comment by alexcrichton** [comment]
Yay!
