### ISSUE TITLE
Touching files in rustllvm doesn't rebuild rustllvm

### ISSUE THREAD

**Issue by nox** [rust-lang/rust#49506]
The oldest problem of build tools, heh.

**Comment by Mark-Simulacrum** [comment]
This should work, as we emit the relevant things from librustc_llvm's build... are you perhaps expecting us to rebuild it separately, without librustc_llvm?

**Comment by Mark-Simulacrum** [comment]
Closing since we never got a reply to my previous comment and I'm pretty sure we do the right thing in librustc_llvm's build script.
