### ISSUE TITLE
Installing Visual Studio Build Tools

### ISSUE THREAD

**Issue by JoKalliauer** [rust-lang/rust#49519]
> The easiest way to acquire the build tools is by installing [Build Tools for Visual Studio 2017](https://www.visualstudio.com/downloads/) which provides only the Visual C++ build tools. 

I installed `Visual Studio Community 2017`, but I don't know what I have to choose to install `Build Tools for Visual Studio 2017`

![screenshot 2018-03-30 18 01 50](https://user-images.githubusercontent.com/15687581/38144453-08c88032-3445-11e8-8180-442fc39ce7c1.png)

**Comment by retep998** [comment]
Select `Desktopentwicklung mit C++`.

**Comment by JoKalliauer** [comment]
Thanks

**Comment by JoKalliauer** [comment]
@retep998 `Desktopentwicklung mit C++` needs 7,5GB. Is there a possibility to only install minimal components?
