### ISSUE TITLE
macro_rules macros should not be serialized through strings in crate metadata.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#49511]
`macro_rules` should use `TokenStream`s instead of being pretty-printed into a string and later re-parsed. This is required to get correct/precise hygiene information and original source spans.

For example, right now macros from `libstd` get `<std macros>` in their spans instead of the original source, and we hide printing any of that source because it looks much worse than the original, and those spans also don't capture any fine-grained information from macro-defining macros.

IIRC @ibabushkin started working on this (see https://github.com/rust-lang/rust/pull/43847) but I couldn't find a tracking issue.
cc @alexcrichton @jseyfried @Manishearth

**Comment by durka** [comment]
This should help with re-exported macro docs #26560 as well.

**Comment by nikomatsakis** [comment]
triage: P-medium

**Comment by nikomatsakis** [comment]
In case there is a decision to be made here, seems like clearly "yes", right? Otherwise, I'm not sure why this is nominated, so removing the tag.

**Comment by eddyb** [comment]
@nikomatsakis I think it was nominated to assign someone to it.

**Comment by ibabushkin** [comment]
Here is my last attempt at this: [branch](https://github.com/ibabushkin/rust/tree/cross-crate-expand), [previous PR](https://github.com/rust-lang/rust/pull/43847). I was unable to get this to a working state (due to lack of time, and strange issues).

**Comment by steveklabnik** [comment]
Triage: it's not clear to me where this lives in the compiler to see if it's something that has been fixed or not; does anyone know where to look? That would help future folks reading this ticket.

**Comment by petrochenkov** [comment]
https://github.com/rust-lang/rust/pull/66364 fixes this for `macro_rules` (they are no longer encoded as strings).

Even after https://github.com/rust-lang/rust/pull/66364 hygienic properties are still not encoded in metadata and are set heuristically on macro loading, that's one of the primary reasons why `Span::def_site` is not stabilized.

**Comment by eddyb** [comment]
I think merging #66364 should close this issue, because even though I said:
> This is required to get correct/precise hygiene information and original source spans.

I mean that this is a *prerequisite* to precise hygiene information, but that is a separate concern that affect all serialized `Span`s and should be tracked separately.
