### ISSUE TITLE
Can't use | as identifier

### ISSUE THREAD

**Issue by mocsy** [rust-lang/rust#49524]
I have this function:
fn | () {}
I get:
[rustc]
expected identifier, found `|`

I tried using #![feature(non_ascii_idents)] , but it din't help.

#![feature(non_ascii_idents)] works with this function:
fn नमस्ते (vec : &Vec<i64>) -> Vec<i64>{
    vec.clone()
}

So it's not a unicode issue.
Let me know how I can define a function named |.

**Comment by leonardo-m** [comment]
You can't, thankfully.

**Comment by zackmdavis** [comment]
As a workaround, maybe look for codepoints that happen to be [ID_Start](http://unicode.org/reports/tr31/) and have a vertical-bar-alike appearance?

```rust
#![feature(non_ascii_idents)]
#![allow(dead_code)]

fn ᥣ() {} // 0x1963 TAI LE LETTER A

fn main() {}
```

**Comment by Restioson** [comment]
| is taken for BitOr.

**Comment by Ixrec** [comment]
What did you want to do with a function named `|`?

**Comment by mocsy** [comment]
@leonardo-m challenge accepted
In C++ it's possible to overload an operator, and thus effectively redefine | as well.
I expect something similar should be possible in rust too.

@Restioson BitOr is a dyadic function, in otherword it has two parameters, a right hand side one and a left hand side one. I want to implement the monadic variant which has only a right hand side.
There is no conflict here. I also hope it's possible to overload the dyadic one as well, because in C++ it's possible.

Here is the playground:
https://play.rust-lang.org/?gist=dfaa0c4666992846d74c27f4239a0a80&version=nightly

**Comment by mocsy** [comment]
@zackmdavis Thank you!
