### ISSUE TITLE
Possibly merge resolve_definition_of_name_in_module with resolve_name_in_module

### ISSUE THREAD

**Issue by catamorphism** [rust-lang/rust#4952]
As per comment in the former function in resolve.

**Comment by tamird** [comment]
There's a whole host of duplication in `librustc_resolve/lib.rs`, but refactoring it would require lots of closure-passing. I'm not really sure it's appropriate to mark as E-easy :(

**Comment by BigBoneDaddy** [comment]
@tamird Well it depend on how good refactorer is with closure! I know to some people closure comes easier than easy but yes to others it is hard as rock!

**Comment by jseyfried** [comment]
This issue was fixed by [this PR](https://github.com/rust-lang/rust/pull/29530).

**Comment by nrc** [comment]
Fixed by #29530
