### ISSUE TITLE
Consider whether `?` should switch from `From::from` to `Into::into` for Rust 2018

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#49531]
Using `into` instead allows for more conversions to be defined, since it has different coherence rules, which all else being equal would be good.  But because of that, there are (per the [IRLO thread](https://internals.rust-lang.org/t/can-try-and-use-the-into-trait-instead-of-from/6714/12?u=scottmcm)) some uses that are inferable today with `from` but not `into`.

**Comment by varkor** [comment]
Rust 2018 has since been released, so I imagine this issue can now be closed?

**Comment by scottmcm** [comment]
This didn't happen in 2018, and https://github.com/rust-lang/rfcs/pull/3058 moved to a system where this is no longer easily doable on an edition boundary, so closing.
