### ISSUE TITLE
way to disable disable -frecord-gcc-switches

### ISSUE THREAD

**Issue by aep** [rust-lang/rust#49543]
A .GCC.command.line' section is being emitted, contributing to binary bloat.
There should be an option to turn that off.

When compiling hello world with no-std, this is easily exceeding the .text section in size.

**Comment by sfackler** [comment]
You could set your linker to a script that wraps gcc and adds `-fno-record-gcc-switches`.

**Comment by jonas-schievink** [comment]
The section doesn't seem to be created anymore, so closing
