### ISSUE TITLE
Replace macro impls in libstd/num/strconv.rs with generic impls

### ISSUE THREAD

**Issue by Kimundi** [rust-lang/rust#4955]
The impl macros in libstd/num/strconv.rs should get replaced by two generic impls for the not yet existing `Integral` and `Floating` traits once those traits exists, and once the compiler supports multiple generic impls against different traits.

**Comment by aturon** [comment]
@bjz do you still plan to work on this (and to hide `strconv` from the public API)?

**Comment by bjz** [comment]
Yes, I do, sorry for the delay.

**Comment by brson** [comment]
There are no numeric traits now and this won't happen.
