### ISSUE TITLE
Wrong link on website for 1.25.0 source code

### ISSUE THREAD

**Issue by infinity0** [rust-lang/rust#49557]
Sorry if this wasn't the best place to report this, but the link to the source code on https://www.rust-lang.org/en-US/other-installers.html is not correct. Near the bottom it points to

- https://static.rust-lang.org/dist/rustc-1.25-src.tar.gz
- https://static.rust-lang.org/dist/rustc-1.25-src.tar.gz.asc

but it should point to

- https://static.rust-lang.org/dist/rustc-1.25.0-src.tar.gz
- https://static.rust-lang.org/dist/rustc-1.25.0-src.tar.gz.asc

**Comment by Mark-Simulacrum** [comment]
Should be fixed by https://github.com/rust-lang/rust-www/pull/1079, though I haven't tested locally.

**Comment by Mark-Simulacrum** [comment]
Appears to be fixed.
