### ISSUE TITLE
rustdoc: Macros re-exported via use_extern_macro appear as a re-export

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#49554]
Most other items re-exported from an `extern crate` appear as if they're defined directly in the place they're re-exported from. For some reason macros are not currently treated the same way, they show up under the "Re-exports" heading and don't have their documentation summary shown. For `futures` this would be very useful for documenting the `async`/`await` macros in the facade.

[Example](https://nemo157.com/rustlang-rust-issue-49553/target/doc/proc_macro_re_export/index.html) ([code here](https://github.com/nemo157/rustlang-rust-issue-49553/)):

![screen shot 2018-04-01 at 11 49 53 am](https://user-images.githubusercontent.com/81079/38171900-d2e6dc20-35a2-11e8-942b-3fda89a74a12.png)

**Comment by QuietMisdreavus** [comment]
I *think* this should have been fixed with https://github.com/rust-lang/rust/pull/51011 (and later https://github.com/rust-lang/rust/pull/51611). However, now the proc-macro re-export may not appear? IIRC, rustdoc doesn't even try to document proc-macros. Can you try running docs for your demo crate with the latest nightly?

**Comment by Nemo157** [comment]
I've regenerated and pushed the docs to the link in the OP. The normal macro is fixed, but the proc-macro re-export has stayed the same (including #49553 messing up the link).

**Comment by QuietMisdreavus** [comment]
Aha! Thanks so much for making a test case like this, it'll really help for testing it. I'll close this in favor of https://github.com/rust-lang/rust/issues/49553, since that seems to describe the outstanding issue better.
