### ISSUE TITLE
Document additional use case for Iterator::inspect

### ISSUE THREAD

**Issue by nickbabcock** [rust-lang/rust#49564]
If you'd like to fix this bug, [here's how](https://github.com/rust-lang/rust/issues/49564#issuecomment-392548153).

---------------------

Currently iterator::inspect contains the following documentation:

> It's much more common for inspect() to be used as a debugging tool than to exist in your final code, but never say never.

Though I like the never say never wording, I think it might be helpful to document a use case where it's not used for debugging. I use `inspect` in daemon applications for that slurp in stdin lines and discard and log the lines that can't be parsed. Like so:

```rust
lines
.iter()
.map(|line| parse_line(line))
.inspect(|line| {
    // If we can't parse a line, yeah that sucks but it's bound to happen so discard
    // the line after it's logged for the attentive sysadmin
    if let Err(ref e) = *line {
        error!("Parsing error: {}", e);
    }
})
.flat_map(|x| x)
// etc
```

Maybe the documentation of inspect can be updated to something like:

> It's more common for inspect() to be used as a debugging tool than to exist in your final code, but applications may find it useful in certain situations as well. Say an application is reading stdin lines, it may be it helpful to log lines with errors before discarding them.

What do you think? Suggestions certainly wanted 😄

**Comment by scottmcm** [comment]
Well, another possibility (YMMV) would be to combine the inspect+flat_map into a filter_map:
```rust
lines
.iter()
.map(|line| parse_line(line))
.filter_map(|line| match line {
    Ok(x) => Some(x),
    Err(e) => { error!("Parsing error: {}", e); None },
})
// etc
```

FWIW it took me a second to remember that flat_map over a result does what it does, so I think I prefer the explicitness of the filter_map overall.

**Comment by nickbabcock** [comment]
Yeah, you can use `filter_map(Result::ok)` as well

```rust
lines
.iter()
.map(|line| parse_line(line))
.inspect(|line| {
    if let Err(ref e) = *line {
        error!("Parsing error: {}", e);
    }
})
.filter_map(Result::ok)
```

Sorry, I wasn't trying to draw attention to flat_map 😅

**Comment by steveklabnik** [comment]
I'm happy to mentor anyone who'd like to fix this bug! Here's how:

The documentation for this method lives here: https://github.com/rust-lang/rust/blob/5092c6b01acbff60935a5e6d84f83b6c73c1ca5e/src/libcore/iter/iterator.rs#L1174-L1211

Add the final example by @nickbabcock above below all of the other ones.

I'm happy to answer any more questions!

**Comment by nickbabcock** [comment]
I'll take it. I didn't know if there needed to be more discussion about the proposed use case.

If I don't figure things out, I'll come back here with question 😉
