### ISSUE TITLE
for loops are worse in Rust comapred to C-like syntax

### ISSUE THREAD

**Issue by Raj2032** [rust-lang/rust#49576]
Using for loops in Rust is a bit more confusing compared to C. For example:

C Syntax

for (int i = 0, x = 2; i < 20 && x < 15; i++, x += 2)
{
    printf("%d", i);
}

How would I translate this in Rust? I don't think you can. This is the biggest problem about Rust. It seems like a very interesting language to use but you can't even have two variables and have two set conditions etc like you could in a language that has C-like syntax.

Isn't it possible to implement this?

**Comment by scottmcm** [comment]
Well, with iterators that's
```rust
for (i, x) in (0..20).zip((0..15).step_by(2))
```
And note that, unlike in the C example, the two variables aren't forced to have the same type.

**Comment by Raj2032** [comment]
Sorry my bad for the lack of understanding.

what is .zip and how does the set_by(2) determine which variable to increment 2 by?

**Comment by scottmcm** [comment]
You might be interested in https://users.rust-lang.org; the issue tracker is not a support forum.

zip: https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.zip
step_by: https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.step_by

I'm going to close this issue as it's not a concrete problem.  If you have specific language design suggestions, consider starting a thread about them on https://internals.rust-lang.org
