### ISSUE TITLE
Entry::and_modify should use FnOnce

### ISSUE THREAD

**Issue by Zoxc** [rust-lang/rust#49581]
This should change to use FnOnce instead of FnMut before it lands on stable.
https://doc.rust-lang.org/std/collections/hash_map/enum.Entry.html#method.and_modify

cc @rust-lang/libs

**Comment by alexcrichton** [comment]
Labelling as a regression to ensure we keep track of this, although it's not technically a regression

**Comment by xfix** [comment]
Now that this is fixed, should it be marked as regression-from-stable-to-beta. It's technically not a regression, it's was marked as such for tracking purposes.

**Comment by alexcrichton** [comment]
Ah that tag is primarily used for open issue, once closed the tags on an issue are anyone's guess :)
