### ISSUE TITLE
Use --edition instead of -Zedition (stabilize edition flag, kind of)

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#49591]
Currently, Rust lets you specify the edition via `-Zunstable-options -Zedition`.

I'd like to stabilize the flag as `--edition`, such that non-nightly Rust can only pass down `--edition=2015`, but other versions can specify anything there.

**Comment by Manishearth** [comment]
@klnusbaum want to work on this? I suspect this would have been better to do _before_ https://github.com/rust-lang/cargo/issues/5214 landed, but I kinda forgot, sorry 😄


You may want to factor it out such that `Config` or `Session` has an `edition()` method that returns the edition, so that code like `sess.opts.debugging_options.edition` doesn't need to exist.

I'd like this to exist in a week or two, so if you don't have the time lmk and I'll just land it.

**Comment by klnusbaum** [comment]
Sure! I'd love to work on this. I'll try to take a wack at it sometime this week :)

**Comment by klnusbaum** [comment]
What are the files that I should be looking at here? `librustc/session/mod.rs` and `librustc/session/config.rs` seem like the places I need to start, but the macros in `config.rs` are a little crazy. Where does the rubber meet the road, i.e. where's the code that says "these options should be mapped to these fields on a struct" or something like that?

**Comment by Manishearth** [comment]
It uses getopts, I suspect you want to imitate what's done for the `pretty` option here.

The macros are for codegen/debugging options afaict, and we're moving this option _out_ of there.

**Comment by Manishearth** [comment]
@klnusbaum btw, you seem to be helping out a bunch with epoch/edition related stuff. You may want to join https://gitter.im/rust-lang/WG-epoch , and let me know if you want more interesting things to work on!

**Comment by klnusbaum** [comment]
I'm starting to understand this a little more. Hoping to have something by the end of the weekend.

**Comment by klnusbaum** [comment]
For reference, this was addressed with https://github.com/rust-lang/rust/pull/50080

**Comment by Manishearth** [comment]
Fixed by #50080

(For future reference, write "fixes #foo" in the PR body so it gets auto-closed. Or at least mention the issue so it gets cross linked)
