### ISSUE TITLE
🚀 create a query for the program clauses needed to solve a given goal

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#49600]
One of the key parts of the interface between the Chalk Solver and rustc is when the solver [requests the program clauses to solve a given goal](https://github.com/rust-lang-nursery/chalk/blob/6ab7717085360e6e8d1f2122186de4885341f6a5/chalk-engine/src/context/mod.rs#L179-L185):

```rust
    /// Returns the set of program clauses that might apply to
    /// `goal`. (This set can be over-approximated, naturally.)
    fn program_clauses(
        &self,
        environment: &I::Environment,
        goal: &I::DomainGoal,
    ) -> Vec<I::ProgramClause>;
```

In Rustc, this is our chance to do some queries and figure out the full set of clauses. This is building on the work in https://github.com/rust-lang/rust/issues/49177, where we create the lowering rules for a trait, item, etc (see also [the rustc guide coverage](https://rust-lang-nursery.github.io/rustc-guide/traits-lowering-rules.html)). 

The set of clauses is somewhat specific to the domain goal:

- `Implemented(P0: Trait<...>)`
  - come from the [header of `Trait`](https://rust-lang-nursery.github.io/rustc-guide/traits-lowering-rules.html#trait-header)
  - come from [each impl](https://rust-lang-nursery.github.io/rustc-guide/traits-lowering-rules.html#lowering-impls)
- `FromEnv(P0: Trait<..>)`
  - these come -- ultimately -- from the param environment
  - but because of [implied bounds rules](https://rust-lang-nursery.github.io/rustc-guide/traits-lowering-rules.html#implied-bounds) we need to combine with the rules from traits
  - we need to compute transitive closure of traits reachable from the env and combine their program clauses, or else iterate over "all traits" (which is actually not easy)
  - I have some code working towards this on my WIP branch for this issue
- ... the rest have to be written out :)

I'll probably keep iterating on this, but if somebody is keen to hack on it, I'd love to collaborate.

**Comment by scalexm** [comment]
Implemented in #55203 and #55649.
