### ISSUE TITLE
Remove $:meta matcher in decl macros

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#49629]
`$:meta` is intended for matching the content of attributes, as in the following:

```rust
#![feature(decl_macro)]

macro m(
    $(#[$m:meta])*
    struct $n:ident;
) {
    $(#[$m])*
    struct $n(usize);
}

m! {
    #[derive(Debug)]
    struct S;
}

fn main() {
    println!("{:?}", S(1));
}
```

According to https://github.com/rust-lang/rust/issues/34981#issuecomment-335973331 we intend to support arbitrary token streams inside of attributes rather than the limited grammar of `$:meta`. Let's have decl macros drop support for `$:meta` and encourage `#[$($meta:tt)*]` instead.

**Comment by eddyb** [comment]
The less fragment specifiers the better! We might even want to change the `macro_rules` `meta` to `ident` followed by any number of `tt`'s, just to keep things simple.

**Comment by dtolnay** [comment]
Changing `macro_rules`'s meta is tricky because it is currently allowed to be followed by tokens.

```rust
macro_rules! eddyb {
    ($m:meta $n:tt) => {}
}

eddyb!(a ~);
```

**Comment by eddyb** [comment]
So, the only generalization we can make are `ident = tt` and `ident(tt*)`?

**Comment by petrochenkov** [comment]
>we intend to support arbitrary token streams inside of attributes

I thought the idea was to support attribute invocations identical to bang macro invocations
```rust
a::b::c!(tt*)
a::b::c![tt*]
a::b::c!{tt*}

=>

#[a::b::c(tt*)]
#[a::b::c[tt*]]
#[a::b::c{tt*}]
```
\+ two "legacy" forms
```rust
#[a::b::c] // Maybe not so "legacy" with https://internals.rust-lang.org/t/idea-elide-parens-brackets-on-unparametrized-macros/6527
#[a::b::c = not_sure_what_exactly_but_probably_tt]
```
, but not arbitrary "token streams" (aka `tt*` without delimiters)
```
#[a::b::c e f + c ,,, ;_:] // Nope
```

In this case, I think, we can fit it into existing `meta` with all its following token rules.

**Comment by sgrif** [comment]
This seems like something that should get done for Rust 2018 -- Should this be nominated for more discussion?

**Comment by petrochenkov** [comment]
https://github.com/rust-lang/rust/pull/50120 restricted the attribute grammar to delimited token trees, so it's at least technically possible to keep `meta` as a matcher now.

**Comment by petrochenkov** [comment]
https://github.com/rust-lang/rust/pull/63674 supports the modern attribute syntax in `meta`.
