### ISSUE TITLE
Some macros are not well formatted

### ISSUE THREAD

**Issue by rleungx** [rust-lang/rust#49649]
There are some macros which are not well formatted in std, such as [writeln](https://doc.rust-lang.org/std/macro.writeln.html).

```
macro_rules! writeln {
    ( $ dst : expr ) => { ... };
    (
$ dst : expr , $ fmt : expr ) => { ... };
    (
$ dst : expr , $ fmt : expr , $ ( $ arg : tt ) * ) => { ... };
}
```

Another example is [unreachable](https://doc.rust-lang.org/std/macro.unreachable.html).

```
macro_rules! unreachable {
    (  ) => { ... };
    (
$ msg : expr ) => { ... };
    (
$ fmt : expr , $ ( $ arg : tt ) * ) => { ... };
}
```

**Comment by sinkuu** [comment]
If they are ones reexported from libcore, this is #26560.

**Comment by pietroalbini** [comment]
Duplicate of #26560
Thanks for reporting this!
