### ISSUE TITLE
Documentation is flickering on light theme

### ISSUE THREAD

**Issue by pravic** [rust-lang/rust#49648]
I have noticed it with nightly and now it is in stable documentation.

It looks like a dark theme has become the default now, but users of the light one now are experiencing some very annoying flickering on each page load: it starts to load in dark theme and then switches to the light one.

Funny enough, it only happens with Chrome-based browsers (the old good Opera does not have this issue). 

P.S. Firefox (Windows, Ubuntu) does not have such issue, too.

Is there a way to reduce such behavior? May be switch to the preferred theme a bit earlier? 

@rust-lang/docs

**Comment by GuillaumeGomez** [comment]
It's not supposed to. By default, it is the light one which is selected.

**Comment by pravic** [comment]
Am I the only one who can see it? I tried different browsers and VMs, same here.

I'll check with devtools, what's going on there.

**Comment by pravic** [comment]
Well. The problem was with an [unconditional theme switch](https://github.com/rust-lang/rust/blob/84203cac67e65ca8640b8392348411098c856985/src/librustdoc/html/static/storage.js#L35-L36), which was fixed in #48831. The current nightly works fine.

I doubt that that fix is possible to backport to the stable documentation, but may be at least in beta?

**Comment by steveklabnik** [comment]
Yeah, stable is impossible, but beta seems good.

**Comment by QuietMisdreavus** [comment]
As the fix PR was merged and backported (and a release has happened as well), i'm calling this issue fixed. Feel free to reopen if you disagree!

**Comment by pravic** [comment]
Yes, stable works good. Thanks!
