### ISSUE TITLE
Error in derived `PartialOrd` for structs based on types with incomparable elements. 

### ISSUE THREAD

**Issue by 0ndorio** [rust-lang/rust#49650]
If a type deriving `PartialOrd` wraps another type which contains incomparable elements - and therefore only defines an implementation of `PartialOrd` and not a `Ord` - the derived implementations of the `le` and `ge` functions are flawed. 

The leads to a state where the internal type returns false as result of the expressions `a <= b` and `b >= a` for two incomparable elements `a` and `b` while the wrapper returns true. [[playground](https://play.rust-lang.org/?gist=e5a683321648f0df437ec9c861197e87&version=stable)]

If we look into the attached output of  `cargo-expand` it becomes clear that both implementations ignore the the underlying type only implements `PartialOrd` and may contain incomparable elements which can't be checked by `(a < b) || !(b < a)` or `(a > b) || !(a > b)`.

*Expanded: Less or Equal*
```rust
    #[inline]
    fn le(&self, __arg_0: &StructWithoutOrd) -> bool {
        match *__arg_0 {
            StructWithoutOrd(ref __self_1_0) => match *self {
                StructWithoutOrd(ref __self_0_0) => {
                    (*__self_0_0) < (*__self_1_0) || !((*__self_1_0) < (*__self_0_0)) && true
                }   
            },  
        }   
    }
```

*Expanded: Greater or Equal*
```rust
    #[inline]
    fn ge(&self, __arg_0: &StructWithoutOrd) -> bool {
        match *__arg_0 {
            StructWithoutOrd(ref __self_1_0) => match *self {
                StructWithoutOrd(ref __self_0_0) => {
                    (*__self_0_0) > (*__self_1_0) || !((*__self_1_0) > (*__self_0_0)) && true
                }   
            },  
        }   
    }
```

**Comment by leodasvacas** [comment]
This is very weird because it's inconsistent with the behavior of `PartialOrd` for floats. This simplified case will print `false` :
```rust
#[derive(PartialOrd, PartialEq)]
struct MyFloat(f64);
fn main() {
    println!("{}", (0.0 / 0.0 >= 0.0) == (MyFloat(0.0 / 0.0) >= MyFloat(0.0)))
}
```
Which is highly inconsistent. This would be a difficult breaking change to make, perhaps not even worth fixing.

**Comment by eddyb** [comment]
Why are comparison operators used more than once? This could cause exponential cost, at worst (in the depth of the value), especially for recursive structures.

cc @Manishearth @alexcrichton

**Comment by Manishearth** [comment]
We should just forward to `.le()`, yes?

This isn't a breaking change, seems like a bug and it doesn't break compilation.

**Comment by 0ndorio** [comment]
I can understand that a fix in such deep integrated code almost automatically involves a breaking change but I would still argue that its actually logically wrong and therefore should be fixed. A potential alternative way could  be to add a new lint check which warns about using <= and => on types which only implement `PartialOrd` as the result of such a check may not lead to the expected result.

(A similar procedure was proposed by @oli-obk in rust-lang-nursery/rust-clippy#2626 for a related issue.)

**Comment by varkor** [comment]
@eddyb: you need both comparison operations per pair of values because there are three conditions (`<`, `>` or unrelated); as far as I can tell, you can't reuse any of the operations.

**Comment by eddyb** [comment]
@varkor Can't you use `parital_ord` recursively?

**Comment by varkor** [comment]
@eddyb: Oh, that's a good point. I'll update the PR to use `partial_cmp` instead.

**Comment by eddyb** [comment]
@varkor What do you mean, can't we rely on the `Ordering` chaining functionality?

**Comment by varkor** [comment]
https://github.com/rust-lang/rust/issues/49650#issuecomment-379467572 is addressed by #50011.

**Comment by leodasvacas** [comment]
This issue is not totally fixed, only the performance issues were (thanks, @varkor!). Could someone reopen?

**Comment by varkor** [comment]
@leodasvacas: https://github.com/rust-lang/rust/pull/49881 fixed this originally, and then https://github.com/rust-lang/rust/pull/50011 followed up on it to fix the inefficiency.

**Comment by leodasvacas** [comment]
@varkor Ah great, nevermind me then.
