### ISSUE TITLE
Derives can conflict with constants

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#49679]
```rust
// pub const __self_0: u8 = 1;
pub const __cmp: u8 = 1;

#[derive(PartialOrd, PartialEq)]
pub enum Foo {
    A(u8), B(u8)
}

fn main() {
}
```

([playpen](https://play.rust-lang.org/?gist=3dea1b6c666ad9b1678d47c731d052c6&version=stable))

With `__cmp` uncommented we get errors like:

```rust
error[E0308]: mismatched types
 --> src/main.rs:7:7
  |
7 |     A(u8), B(u8)
  |       ^^^ expected enum `std::option::Option`, found u8
  |
  = note: expected type `std::option::Option<std::cmp::Ordering>`
             found type `u8`

error[E0308]: match arms have incompatible types
 --> src/main.rs:7:7
  |
7 |     A(u8), B(u8)
  |       ^^^
  |       |
  |       expected enum `std::option::Option`, found u8
  |       match arm with an incompatible type
  |
  = note: expected type `std::option::Option<std::cmp::Ordering>`
             found type `u8`
```

With `__self_0` uncommented we get errors like:

```
error[E0530]: match bindings cannot shadow constants
 --> src/main.rs:7:7
  |
2 | pub const __self_0: u8 = 1;
  | --------------------------- a constant `__self_0` is defined here
...
7 |     A(u8), B(u8)
  |       ^^^ cannot be named the same as a constant
```

This is basically because they generate matches on variables named `__cmp` and `__self_#` and `__arg_#_#`, and rustc doesn't like it when you conflict those with constants.

**Comment by Manishearth** [comment]
I first noticed the `__cmp` one -- that comes from a match that does:

```rust
match cmp(...) {
   Equal => ...
   __cmp => __cmp
}
```

This could be rewritten to do `__cmp @ _ => __cmp` but that hits the shadow error. It can also be rewritten to bind the result of `cmp()` to a temporary, which should work.

However there's no way at all of fixing the `__self` stuff.

The reason we have the match bindings shadow error is https://github.com/rust-lang/rust/issues/33118#issuecomment-233962221, which we hopefully can fix? cc @petrochenkov

**Comment by eddyb** [comment]
Note the difference between [unhygienic old macros](https://play.rust-lang.org/?gist=ac574cf8465fa660f78d55f2ed03a204&version=nightly) and [hygienic new macros](https://play.rust-lang.org/?gist=bb351441be61e5985e2f47e0abbd27eb&version=nightly).

**Comment by jonas-schievink** [comment]
This appears to be fixed (the binding names are now different, but those still don't cause conflicts, presumably because they're gensym'd, or whatever our equivalent to that is)
