### ISSUE TITLE
[Feature request] Allow matching alternatives in macros

### ISSUE THREAD

**Issue by marmistrz** [rust-lang/rust#49687]
Motivation: this atrocious macro, which has over 80 lines, due to the fact that every alternative type has to be matched separately: https://github.com/servo/rust-mozjs/blob/5b79f789520d66a5391033bb78ac30b81e43d8b1/src/rust.rs#L1669-L1743

For example, it would be nice to be able to write: 

```
    (@inner $saved:tt <> ($($acc:expr,)*) <> $arg:ident: {Handle, MutableHandle, HandleObject, HandleValue}, $($rest:tt)*) => {
        wrap!(@inner $saved <> ($($acc,)* $arg.into(),) <> $($rest)*);
};
```

the intended meaning: match any of `Handle`, `MutableHandle`, `HandleObject`, `HandleValue`

**Comment by Aaronepower** [comment]
@marmistrz Thank you for this issue! Could you create a thread on [internals](http://internals.rust-lang.org/) for this feature request?
