### ISSUE TITLE
Some of the x86 SIMD intrinsics' arguments are misleading

### ISSUE THREAD

**Issue by octurion** [rust-lang/rust#49688]
In some cases, the arguments of some x86 SIMD intrinsic functions are misleading. For example:

- [`_mm_loadl_epi64`](https://doc.rust-lang.org/nightly/core/arch/x86/fn._mm_loadl_epi64.html) supposedly performs a 128-bit load (given that we're passing a pointer to `__m128i`. This is not true, however. The load is 64-bit and there are no alignment requirements whatsoever, so passing a `*const c_void` would be probably the better option.
- The same also applies to [`_mm_storel_epi64`](https://doc.rust-lang.org/nightly/core/arch/x86/fn._mm_storel_epi64.html).
- The [`_mm_load_si128`](https://doc.rust-lang.org/nightly/core/arch/x86/fn._mm_load_si128.html) and [`_mm_loadu_si128`](https://doc.rust-lang.org/nightly/core/arch/x86/fn._mm_loadu_si128.html) types require the passing of a pointer to `__m128i`, but I believe requiring a `*const c_void` would be better here.
- The same also applies to [`_mm_store_si128`](https://doc.rust-lang.org/nightly/core/arch/x86/fn._mm_store_si128.html) and [`_mm_storeu_si128`](https://doc.rust-lang.org/nightly/core/arch/x86/fn._mm_storeu_si128.html) (but a `*mut c_void` should be passed here instead).

These issues are not Rust-specific; the C intrinsics are also plagued with these issues. Since, however, it's impossible to change the signatures with respect to C (because that would be a breaking change), I believe fixing them on Rust side before they become stable will be worthwhile.

(FYI: Some of these examples were taken from https://fgiesen.wordpress.com/2016/04/03/sse-mind-the-gap/)

**Comment by steveklabnik** [comment]
> These issues are not Rust-specific; the C intrinsics are also plagued with these issues. Since, however, it's impossible to change the signatures with respect to C (because that would be a breaking change), I believe fixing them on Rust side before they become stable will be worthwhile.

This was long debated on the RFC thread, and the team decided that a 1-1 mapping at this level is the right thing to do.

**Comment by alexcrichton** [comment]
Thanks for the report! As @steveklabnik mentioned though it's [explicitly intended](https://github.com/rust-lang/rfcs/blob/master/text/2325-stable-simd.md#the-stdarch-module) that we exactly match C, so these signatures can't change in Rust either.
