### ISSUE TITLE
E0277 explanation when using optional chaining can be improved

### ISSUE THREAD

**Issue by learnopengles** [rust-lang/rust#49694]
For this error:

```
 error[E0277]: the trait bound `std::option::Option<&Symbol>: std::ops::FnOnce<()>` is not satisfied
    --> JackCompiler.rs:302:19
     |
 302 |         let b = a.or_else(self.subroutine_symbols.get(name));
     |                   ^^^^^^^ the trait `std::ops::FnOnce<()>` is not implemented for `std::option::Option<&Symbol>`
 
 error: aborting due to previous error
```

The compiler can suggest adding a closure here. I'm honestly not sure what the issue is myself and I find optional and result chaining very difficult to use in Rust as compared to a language like Swift. However, changing it to a closure by adding "|| " fixed the error for me.

**Comment by estebank** [comment]
The functions `Fn`:
https://github.com/rust-lang/rust/blob/fefe81605d6111faa8dbb3635ab2c51d59de740a/src/libcore/ops/function.rs#L70

`FnOnce`:
https://github.com/rust-lang/rust/blob/fefe81605d6111faa8dbb3635ab2c51d59de740a/src/libcore/ops/function.rs#L216

and `FnMut`:
https://github.com/rust-lang/rust/blob/fefe81605d6111faa8dbb3635ab2c51d59de740a/src/libcore/ops/function.rs#L143

need to have [a `#[rustc_on_unimplemented]` attribute added](https://github.com/rust-lang/rust/pull/50441/files), with a `note` suggesting the use of a closure and a short explanation of why the attempted code doesn't work.

**Comment by LuGuoHuas** [comment]
i'm a noob, but I would like to take this on if nobody else is working on that.

**Comment by LuGuoHuas** [comment]
Hello @estebank , I am sorry that I have not worked before, because this time is working overtime.Now I built the compiler and tried adding the #[rustc_on_unimplemented] property, but I have some questions.
How does (crate_local, label='xxxx', note='xxx') in #[rustc_on_unimplemented] work? Is there any relevant information? Because I use the method in the example, but it doesn't work. Thank you very much for your help.

**Comment by estebank** [comment]
Extended the documentation a bit in #53279.

**Comment by LuGuoHuas** [comment]
hi @estebank . i try first annotating with #[rustc_on_unimplemented(note="test")] , but it not work.

**Comment by estebank** [comment]
@LuGuoHuas I took a look to see what was needed and arrived at this https://github.com/rust-lang/rust/pull/53296
