### ISSUE TITLE
"error[E0507]: cannot move out of borrowed content" could suggest adding the Copy trait

### ISSUE THREAD

**Issue by learnopengles** [rust-lang/rust#49693]
For this error:

> error[E0507]: cannot move out of borrowed content
>    --> file.rs:302:35
>     |
> 302 |         let c = b.map(|entry| entry.symbol_kind);
>     |                                   ^^^^^ cannot move out of borrowed content
> 
> error: aborting due to previous error

The compiler could suggest adding #[derive(Copy, Clone)] to the relevant enum. The error message on its own does not offer enough insight on how to fix the problem, from a non-proficient user's POV.

**Comment by BGR360** [comment]
Looks like your wish has been granted since you posted the issue!

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7f8679202e795fab694431762f3830a7)

```rust
struct NotCopy;

struct ContainsNotCopy {
    inner: NotCopy
}

fn main() {
    let container = ContainsNotCopy { inner: NotCopy };
    
    let option = Some(&container);
    
    let _ = option.map(|c| c.inner);
}
```

```
error[E0507]: cannot move out of `c.inner` which is behind a shared reference
  --> src/main.rs:12:28
   |
12 |     let _ = option.map(|c| c.inner);
   |                            ^^^^^^^ move occurs because `c.inner` has type `NotCopy`, which does not implement the `Copy` trait
```

Can we close this?
