### ISSUE TITLE
ICE on nightly

### ISSUE THREAD

**Issue by sgrif** [rust-lang/rust#49703]
Seeing build failures on nightly for Diesel. https://travis-ci.org/diesel-rs/diesel/jobs/361834440

```
     Running `rustc --crate-name tests diesel_derives/tests/tests.rs --emit=dep-info,link -C debuginfo=2 --test --cfg 'feature="default"' --cfg 'feature="diesel"' --cfg 'feature="nightly"' --cfg 'feature="postgres"' --cfg 'feature="proc-macro2"' -C metadata=7c360c37303d8398 -C extra-filename=-7c360c37303d8398 --out-dir /home/travis/build/diesel-rs/diesel/target/debug/deps -C incremental=/home/travis/build/diesel-rs/diesel/target/debug/incremental -L dependency=/home/travis/build/diesel-rs/diesel/target/debug/deps --extern quote=/home/travis/build/diesel-rs/diesel/target/debug/deps/libquote-1c34cab3787b214f.rlib --extern cfg_if=/home/travis/build/diesel-rs/diesel/target/debug/deps/libcfg_if-a72f9f64d8714354.rlib --extern syn=/home/travis/build/diesel-rs/diesel/target/debug/deps/libsyn-16fe49c01092e19f.rlib --extern dotenv=/home/travis/build/diesel-rs/diesel/target/debug/deps/libdotenv-6349b3801e6c32f9.rlib --extern proc_macro2=/home/travis/build/diesel-rs/diesel/target/debug/deps/libproc_macro2-f01d9481ef684273.rlib --extern diesel=/home/travis/build/diesel-rs/diesel/target/debug/deps/libdiesel-6db6cf6fe78b3eac.rlib --extern diesel_derives=/home/travis/build/diesel-rs/diesel/target/debug/deps/libdiesel_derives-a9504ccc1f85aa42.so -L native=/usr/lib/x86_64-linux-gnu -L native=/home/travis/build/diesel-rs/diesel/target/debug/build/backtrace-sys-b3c3d3611301ce9a/out/.libs`
thread 'rustc' panicked at 'index out of bounds: the len is 213841 but the index is 213899', /checkout/src/libcore/slice/mod.rs:871:14
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.26.0-nightly (06fa27d7c 2018-04-01) running on x86_64-unknown-linux-gnu
note: compiler flags: -C debuginfo=2 -C incremental
note: some of the compiler flags provided by cargo are hidden
error: Could not compile `diesel_derives`.
```

**Comment by ExpHP** [comment]
I tried to reproduce this but evidently my local setup is too dissimilar from diesel's CI.  It looks suspiciously like #48923 though.

**Comment by ExpHP** [comment]
By the way, your most recent failure is a build failure due to the proc-macro feature update. You should try updating to proc-macro2 0.3, syn 0.13, and quote 0.5.

**Comment by sgrif** [comment]
> You should try updating to proc-macro2 0.3, syn 0.13, and quote 0.5.

You say that like it's so straightforward. ;) The last time we had to update syn it required rewriting the entire crate from scratch.

**Comment by ExpHP** [comment]
Oof, yes.  `syn 0.11 => syn 0.12` was *huuuuge beyond man's wildest fears,* because it had to redesign the entire AST to incorporate spans... and then I guess it also had to redesign everything else to make the new AST more comfortable to work with.

syn 0.12 => syn 0.13 does have breaking changes (there's no more `pub span` fields), but nothing nearly as drastic as last time.

**Comment by varkor** [comment]
https://github.com/rust-lang/rust/issues/48923 has been fixed now: is this still causing problems, or can we close this issue?

**Comment by estebank** [comment]
@sgrif could you point us to a commit sha for diesel to reproduce this case? I am tempted at closing this ticket given @varkor's comment above.

**Comment by sgrif** [comment]
33856d0e8be4cc845f5366e2133f0d760a047157

**Comment by estebank** [comment]
@sgrif I've tried running `cargo +devel test --features "sqlite"` on that SHA, but I get the following, among other errors

```
error[E0433]: failed to resolve: could not find `sqlite` in `diesel`
  --> /Users/ekuber/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.1.2/src/sql_types/mod.rs:37:48
   |
37 | #[derive(Debug, Clone, Copy, Default, QueryId, SqlType)]
   |                                                ^^^^^^^ could not find `sqlite` in `diesel`
```

I tried a couple of other things but I haven't managed to get the tests to run. I also noticed that some lints that used not to trigger now trigger in nightly. Could you try getting the test run on your end or supply some instructions on how to get them to run locally?

**Comment by Centril** [comment]
@sgrif Any thoughts re. ^--- ?
