### ISSUE TITLE
CI: Remove the concept of "Disabled builders"

### ISSUE THREAD

**Issue by kennytm** [rust-lang/rust#49700]
Disabled builders were introduced in #41864. These are Docker images which are explicitly prevented from being run from Travis. However,

1. Since we are going to explicitly list all images in `.travis.yml`, there seems no reason to introduce a `disabled/` folder
2. We may really want to run these images on Travis as a try-build.

Nowadays, Travis supports [conditional jobs](https://docs.travis-ci.com/user/conditional-builds-stages-jobs), so we could actually

1. Move those disabled builders back into the normal location
2. Revert specialization in `src/ci/docker/run.sh` about disabled images
3. Expose them to `.travis.yml` but disable them via conditions:

    ```yaml
        - env: IMAGE=aarch64-gnu
          if: type = disabled     # <- this condition is always false
    ```

The motivation is allowing check builders of tier-2/3 platforms (e.g. Redox, CloudABI, the embedded platforms etc) be run on demand.

**Comment by JohnTitor** [comment]
Triage: We're now on GHA and the config should be cleaned up, closing.
