### ISSUE TITLE
2-phase borrow activation ice

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#49736]
This program [ICEs](https://play.rust-lang.org/?gist=f4fcb7deaf342baf85db10c93da3dfc7&version=nightly):

```rust
#![feature(nll)]

struct Foo {
    
}

impl Foo {
    fn method(&mut self, foo: &mut Foo) {
    }
}

fn main() {
    let mut foo = Foo { };
    foo.method(&mut foo);
}
```

See also [this conversation between @pnkfelix and I on gitter](https://gitter.im/rust-impl-period/WG-compiler-nll?at=5ac743a701a2b40f382e87a7), which I believe to be relevant.

I'm refactoring some of this code, trying to explore the new NLL approach, so I will probably wind up fixing this.  But obviously we should have this as a test!

cc @bobtwinkles

**Comment by Robbepop** [comment]
Is this similar to this ICE?
https://github.com/rust-lang/rust/pull/49678/files
