### ISSUE TITLE
Unicode minus sign error message in literals

### ISSUE THREAD

**Issue by sunjay** [rust-lang/rust#49746]
This code: ([Playground Link](https://play.rust-lang.org/?gist=d41d999388694dcfa3644db08d5bebdf&version=stable))

```rust
fn main() {
    let x: f64 = 6.674e−11;
}
```

Looks pretty identical to this code:

```rust
fn main() {
    let x: f64 = 6.674e-11;
}
```

But the first one doesn't compile because I accidentally used a unicode minus sign (−) instead of a dash (-). This happened to me when I pasted a constant from Wikipedia.

```
error: expected at least one digit in exponent
 --> src/main.rs:2:24
  |
2 |     let x: f64 = 6.674e−11;
  |                        ^
```

We already produce an error about things like this in other cases. For example with an en space:

```rust
fn main() {
    let a = ();
}
```

We produce the following:
```
error: unknown start of token: \u{2002}
 --> src/main.rs:2:8
  |
2 |     let a = ();
  |        ^
  |
help: unicode character ' ' (En Space) looks like ' ' (Space), but it's not
 --> src/main.rs:2:8
  |
2 |     let a = ();
  |        ^

error: Could not compile `playground`.
```

Maybe we could do the same for the minus sign since it is a pretty confusing error to receive?

**Comment by Badel2** [comment]
The unicode minus sign is already on the list of similar characters:

https://github.com/rust-lang/rust/blob/8c2d7b2da322af89f310183cdca662a99ade6d22/src/libsyntax/parse/lexer/unicode_chars.rs#L53

However it looks like it doesn't work in this context.
