### ISSUE TITLE
Regression in cargo 1.26.0-nightly 2018-04-04:  `[target.'cfg(FLAG)'.dependencies] ` does not work anymore

### ISSUE THREAD

**Issue by PaulGrandperrin** [rust-lang/rust#49747]
The new revision of cargo included in rust nightly has a regression.
```
cargo 1.26.0-nightly (b70ab13b3 2018-04-04)
release: 1.26.0
commit-hash: b70ab13b31628e91b05961d55c07abf20ad49de6
commit-date: 2018-04-04
```
My crate [honggfuzz-rs](https://github.com/rust-fuzz/honggfuzz-rs) is tested on travis daily and today the compilation failed even though there wasn't any commit:
https://travis-ci.org/rust-fuzz/honggfuzz-rs/builds/363265565

I suspect the regression comes from this line in my cargo.toml:
```toml
[target.'cfg(fuzzing_debug)'.dependencies]
memmap = "0.6"
```
Code including `memmap` is only compiled when building with `--cfg fuzzing_debug` and until now, this crate was accordingly also only included when building with this flag.

It seems that this dependency is not understood anymore on the latest nightly.

I guess very few people/crates will be affected by this change/regression. For the record, I just want to state that I really don't care if it is decided that this functionality is not supported anymore.

**Comment by sfackler** [comment]
I think this is probably a regression in cargo, so it should be filed over at https://github.com/rust-lang/cargo.

**Comment by PaulGrandperrin** [comment]
Oh, my mistake, I thought I reported it on cargo!
I will do that now :-)
