### ISSUE TITLE
Stop hiding type declarations in docs

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust#49764]
This recent change: https://github.com/rust-lang/rust/commit/73b97c7e7c9cfac4dfa4804654b1db6ab687b589 means that in the latest documentation all of the type declarations are collapsed by default.

Personally, I find this incredibly irritating - this is the *API reference*, the type declaration is one of the most important pieces of information on the page, and in most cases it is not even large enough that collapsing it saves much space.

Example: https://doc.rust-lang.org/nightly/std/borrow/trait.Borrow.html

**Comment by GuillaumeGomez** [comment]
I added a [PR](https://github.com/rust-lang/rust/pull/49954) to allow you to change some behaviors. Also, please recall that your opinion is yours only, I made this change because people were complaining about the fact that it was **not** hidden by default, not because I just felt like it.

**Comment by Diggsey** [comment]
@GuillaumeGomez I realise that, but there's also no process for these kinds of changes, and so no way to object to them before they occur.

For every person who complained about them not being hidden there may well have been ten people who were very happy that it was. Based on the admittedly small sample size here it looks like 7:1 the other way. In the absence of overwhelming opinion one way or another the defaults should be left alone because consistency is more important!

**Comment by GuillaumeGomez** [comment]
That's why I added the settings. Like that, if more debates like this come up about a feature, we'll just add a setting for it and people will do whatever they want with it.
