### ISSUE TITLE
`if cfg!(..)` generate code for all branches

### ISSUE THREAD

**Issue by spaolacci** [rust-lang/rust#49763]
The following snippet will generate two compilation errors - for the two branches simultaneously-.

Not a big issue in practice, but this make `cfg!` less appropriate for e.g static exhaustiveness guards.
 
    if cfg!(target_pointer_width = "32") {
        compile_error!("is 32");
    } else {
        compile_error!("not 32");
    }

The below example however shows that `#[cfg]` has the expected behavior ([playground](https://play.rust-lang.org/?gist=9ffafd1ce4e8b971a571a4084fe874bf&version=stable))

    #[cfg(target_pointer_width = "32")]
    panic!("is 32"); // Won't panic.

    #[cfg(target_pointer_width = "32")]
    compile_error!("is 32"); // Will compile.

    if cfg!(target_pointer_width = "32") {
        compile_error!("is 32"); // XX: Won't compile.
    }
    
    // XX: Both branches will simultaneously fail to compile.
    if cfg!(target_pointer_width = "32") {
        compile_error!("is 32");
    } else {
        compile_error!("not 32");
    }
(playground's pointer size is `64`)

**Comment by sfackler** [comment]
`cfg!()` just turns into `true` or `false`. I don't think it's unreasonable to expect that this would work in the same way:

```rust
if true {
    compile_error!("hi");
} else {
    compile_error!("hi2");
}
```

**Comment by spaolacci** [comment]
I understand as well and it's clearly reasonable to have that expansion. The `cfg!` story (by opposition to `#[cfg]` is however less handy that it could probably be.

In that specific example, I was looking for a way to exhaustively dispatch on a configuration attribute (originally for some `simd` dispatch). Attributes being non-enumerable, static guards against unexpected values can be nice - at least I thought :).

Existing implementations aside, I think I was looking for a static

    match_cfg!(attribute) {
    a1 => {..},
    a2 => {..},
    _ => compile_error!(),
    }

Since everything is known at code generation time, it's not unreasonable to expect a compilation failure (but that match statement doesn't exist).

Maybe it's just a way to work around attributes being "open text" - not enums.

Is there a "canonical" way to guard against unexpected/forgotten attribute values currently? 

I definitely can cope with an extra standalone `#[cfg]` that inverse all the conditions that were already handled, but this is of course less handy.

Thanks.

**Comment by ishitatsuyuki** [comment]
What you described is basically C++17 constexpr ifs, but I'm not sure if it's highly demanded in Rust's type system.

**Comment by sfackler** [comment]
The cfg-if crate has what you're looking for I think: https://docs.rs/cfg-if/0.1.2/cfg_if/

**Comment by spaolacci** [comment]
Thanks Steven, this is indeed what I'm looking for.

I was somehow expecting `cfg_if` (or an hypothetical `match_if`) to be part of `std`, but using an external crate is definitely fine enough.

Closing the issue.
