### ISSUE TITLE
Search a substring instead of start of string for rustdoc

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rust#49762]
Hi.
Currently, if I search `key_press_event` rustdoc won't find `connect_key_press_event`, but `connect_key_press` will work.
It would be nice to be able to do substring search.
Thanks.

**Comment by Mark-Simulacrum** [comment]
cc @GuillaumeGomez -- I feel like this behavior is already implemented?

**Comment by GuillaumeGomez** [comment]
Not really or at least not completely. I'll need to make another pass on it.
