### ISSUE TITLE
Allow mod statement to reference generated rust modules

### ISSUE THREAD

**Issue by swiftcoder** [rust-lang/rust#49772]
Summary: Given a `build.rs` file that generates `src/foo.rs` (in the out directory), I should be able to declare `pub mod foo` from `src/main.rs` (not in the the out directory).

Today I can simulate this by using 
```
pub mod foo {
    include!(concat!(env!("OUT_DIR"), "/src/foo.rs"));
}
```
in `main.rs`, but this seems both non-intuitive, and seems to break intellisense for module `foo` in several rust-enabled IDEs.

I'm not sure whether this is an issue of `rustc` lacking support for collapsing multiple directory structures into one, or an issue of `cargo` not setting up the compiler inputs appropriately.

(for additional context, generated files are a constant presence at least in network protocols and serialisation, as popular tools like protobuf and cap'n proto rely on generated files to provide language-specific protocol implementations)

**Comment by Mark-Simulacrum** [comment]
I'm going to close this as I believe this is definitely going to require an RFC.
