### ISSUE TITLE
rustc warning on aarch64: '+fp' is not a recognized feature for this target (ignoring feature)

### ISSUE THREAD

**Issue by robsmith11** [rust-lang/rust#49790]
I've installed nightly for aarch64-unknown-linux-gnu using rustup on a device with a Snapdragon 625, and it works well, but every time rustc is called, it prints a warning message:
```
'+fp' is not a recognized feature for this target (ignoring feature)
```
I'm not sure what this feature is, but everything seems to be working fine.

**Comment by nagisa** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/49782. Thanks!
