### ISSUE TITLE
Warn or Error on errors in constants?

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#49791]
Before the miri merger, you were allowed to write `pub const FOO: usize = 0 - 1;` (producing just a warning), but using it either in this crate or another produced an error.

Since the miri merger, these kinds of constants have become hard errors (just like within statics).

This is of course a breaking change. So we need to decide whether to move back to the warning, or break this now. The warnings have existed for a very long time, but were never moved to `deny-by-default`

cc @rust-lang/lang 

related: https://github.com/rust-lang/rust/issues/47054

**Comment by nikomatsakis** [comment]
@oli-obk do we have some idea of the fallout here?

**Comment by pietroalbini** [comment]
This still needs a backport to beta.

**Comment by pietroalbini** [comment]
Backported to beta.
