### ISSUE TITLE
NLL: unexpected "free region `` does not outlive" error

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#49824]
In the test `borrowck/borrowck-describe-lvalue.rs`, when using NLL by default for MIR borrowck, I started getting the odd error "Free region does not outlive" error below:

```
    // Field from upvar nested
    {
        let mut x = 0;
           || {
               || { //[mir]~ ERROR free region `` does not outlive
                   let y = &mut x;
                   &mut x; //[ast]~ ERROR cannot borrow `**x` as mutable more than once at a time
                   //[mir]~^ ERROR cannot borrow `x` as mutable more than once at a time
                   *y = 1;
                   drop(y);
                }
           };
    }
```

Seems like a bug.

**Comment by nikomatsakis** [comment]
Context:

Closures desugar to a struct. Sometimes this struct will have requirements that are placed on its creator. It's the closure's job to infer those requirements. The creator then tries to check it they are met.

Example:

```rust
fn foo(mut x: Vec<&'a u32>, y: &'b u32) {
  let c = || {
    x.push(y);
  };
  c();
}
```

The closure here desugars to something like

```rust
let c = ClosureStruct { x: &mut x, y: &y };
c();
```

where

```rust
struct ClosureStruct<'x, 'y, 'a, 'b> {
  x: &'x mut Vec<&'a u32>,
  y: &'y &'b u32
}

impl FnOnce for ClosureStruct { .. }
```

In the course of type-checking that impl, we will check that `x.push(y)` statement. We will find that this type checks, but only if `'b: 'a`. These regions are declared *outside* the closure, so we will propagate them to our caller, who will check (and -- in the case of this example -- generate an error).

This is what the `CloureReturnRequirements` are all about:

https://github.com/rust-lang/rust/blob/6c537493d01694cc6e0a614dff12c475055aa2b4/src/librustc/mir/mod.rs#L2032-L2094

There are [lots of tests](https://github.com/rust-lang/rust/tree/6c537493d01694cc6e0a614dff12c475055aa2b4/src/test/ui/nll/closure-requirements) in `src/test/ui/nll` on this topic. Each makes use of a unit-testing feature that dumps out the closure return requirements for functions annotated with `#[rustc_regions]`:

https://github.com/rust-lang/rust/blob/6c537493d01694cc6e0a614dff12c475055aa2b4/src/test/ui/nll/closure-requirements/return-wrong-bound-region.rs#L19-L24

The closure in that function, for example, apparently defines no external requirements:

https://github.com/rust-lang/rust/blob/6c537493d01694cc6e0a614dff12c475055aa2b4/src/test/ui/nll/closure-requirements/return-wrong-bound-region.stderr#L13-L22

Anyway, the way to start here is to (a) create a minimized test and (b) dump out the region requirements and then perhaps (c) start trying to see where they are coming from.

**Comment by declanvk** [comment]
I've been experience something with the same error message, not sure if it is the same cause.

I would have sworn that code like this should work, but my understanding of rust is still incomplete. Any pointers would be appreciated. Error is on the line with `len`.

```rust
#[derive(Debug)]
pub struct IterMut<'a, E: 'a> {
    index_slice: &'a [u32],
    data_slice: &'a mut [E],
    ptr: usize,
}

impl<'a, E> Iterator for IterMut<'a, E> {
    type Item = (u32, &'a mut E);

    #[inline]
    fn next(&mut self) -> Option<Self::Item> {
        let len = self.index_slice.len(); // error: free region `` does not outlive free region `'a`
        if self.ptr >= len {
            None
        } else {
            let result = (self.index_slice[self.ptr], &mut self.data_slice[self.ptr]);
            self.ptr += 1;

            Some(result)
        }
    }
}
```

rustc: 1.27.0-nightly (ad610bed8 2018-04-11)
active toolchain: nightly-x86_64-unknown-linux-gnu

**Comment by spastorino** [comment]
My reduced test case is ...

```
#![feature(rustc_attrs)]
#![feature(nll)]

#[rustc_regions]
fn main() {
    let mut x = 0;
    || {
        || {
            let _y = &mut x;
        }
    };
}
```

If I borrow x immutable the issue does not trigger.

Dumping region requirements I get ...

```
[santiago@archlinux rust1 (master)]$ rustc +stage1 src/test/run-pass/issue-49824.rs
note: No external requirements
  --> src/test/run-pass/issue-49824.rs:18:9
   |
18 | /         || {
19 | |             let _y = &mut x;
20 | |         }
   | |_________^
   |
   = note: defining type: DefId(0/1:10 ~ issue_49824[317d]::main[0]::{{closure}}[0]::{{closure}}[0]) with closure substs [
               i16,
               extern "rust-call" fn(()),
               &mut i32
           ]

error: free region `` does not outlive free region `'_#1r`
  --> src/test/run-pass/issue-49824.rs:18:9
   |
18 | /         || {
19 | |             let _y = &mut x;
20 | |         }
   | |_________^

note: External requirements
  --> src/test/run-pass/issue-49824.rs:17:5
   |
17 | /     || {
18 | |         || {
19 | |             let _y = &mut x;
20 | |         }
21 | |     };
   | |_____^
   |
   = note: defining type: DefId(0/1:9 ~ issue_49824[317d]::main[0]::{{closure}}[0]) with closure substs [
               i16,
               extern "rust-call" fn(()) -> [closure@src/test/run-pass/issue-49824.rs:18:9: 20:10 x:&mut i32],
               &mut i32
           ]
   = note: number of external vids: 3
   = note: where '_#2r: '_#1r

note: No external requirements
  --> src/test/run-pass/issue-49824.rs:15:1
   |
15 | / fn main() {
16 | |     let mut x = 0;
17 | |     || {
18 | |         || {
...  |
21 | |     };
22 | | }
   | |_^
   |
   = note: defining type: DefId(0/0:3 ~ issue_49824[317d]::main[0]) with substs []

error: aborting due to previous error
```

**Comment by pnkfelix** [comment]
@spastorino by the way, in case you are not already aware of htis: If you pass the `-Z verbose` flag to `rustc`, the error messages will use the `fmt::Debug` formatters to render regions, which means instead of getting an empty string, we get:

```
error: free region `ReFree(DefId(0/1:9 ~ issue_49824_reduced[317d]::main[0]::{{closure}}[0]), BrEnv)` does not outlive free region `'_#1r`
```

(That is just general info that can sometimes be useful when staring at compiler output, not necessarily something that will solve *this* particular problem...)

**Comment by pnkfelix** [comment]
In particular, by adding `-Z verbose` when compiling your reduced test case (along with `-Z borrowck=mir` to enable NLL mode), I get this marginally more informative output:

```
% ./build/x86_64-unknown-linux-gnu/stage1/bin/rustc ../../issue-49824-reduced.rs  -Z borrowck=mir -Z verbose
note: No external requirements
  --> ../../issue-49824-reduced.rs:8:9
   |
8  | /         || {
9  | |             let _y = &mut x;
10 | |         }
   | |_________^
   |
   = note: defining type: DefId(0/1:10 ~ issue_49824_reduced[317d]::main[0]::{{closure}}[0]::{{closure}}[0]) with closure substs [
               i16,
               extern "rust-call" fn(()),
               &'_#1r mut i32
           ]

error: free region `ReFree(DefId(0/1:9 ~ issue_49824_reduced[317d]::main[0]::{{closure}}[0]), BrEnv)` does not outlive free region `'_#1r`
  --> ../../issue-49824-reduced.rs:8:9
   |
8  | /         || {
9  | |             let _y = &mut x;
10 | |         }
   | |_________^

note: External requirements
  --> ../../issue-49824-reduced.rs:7:5
   |
7  | /     || {
8  | |         || {
9  | |             let _y = &mut x;
10 | |         }
11 | |     };
   | |_____^
   |
   = note: defining type: DefId(0/1:9 ~ issue_49824_reduced[317d]::main[0]::{{closure}}[0]) with closure substs [
               i16,
               extern "rust-call" fn(()) -> [closure@../../issue-49824-reduced.rs:8:9: 10:10 x:&'_#1r mut i32],
               &'_#2r mut i32
           ]
   = note: number of external vids: 3
   = note: where '_#2r: '_#1r

note: No external requirements
  --> ../../issue-49824-reduced.rs:5:1
   |
5  | / fn main() {
6  | |     let mut x = 0;
7  | |     || {
8  | |         || {
...  |
11 | |     };
12 | | }
   | |_^
   |
   = note: defining type: DefId(0/0:3 ~ issue_49824_reduced[317d]::main[0]) with substs []

error: aborting due to previous error
```

**Comment by nikomatsakis** [comment]
@spastorino and I [discussed on gitter](https://gitter.im/rust-impl-period/WG-compiler-nll?at=5adf98a92dfcfffd2b2cb4d4)

**Comment by nikomatsakis** [comment]
Hmm, this might be a case where the check is actually working as intended, though the error message is not great. In particular, the outer closure is **returning the inner closure** -- the way the inference works, the inner closure is inferred to a `FnMut` that borrows `x` from its creator. The outer closure in turn borrows `x` from the top fn. But then the outer closer returns the inner one -- effectively giving away access to `x` after it has returned. Since it is an `FnMut` closure, however, it should not do that: it accesses `x` via an `&mut self` that is limited to the scope of the fn.

Either of these two variants works. If you use `move` on the inner closure, that forces both closures to be inferred to `FnOnce`:

```rust
#![feature(rustc_attrs)]
#![feature(nll)]

#[rustc_regions]
fn main() {
    let mut x = 0;
    || {
        move || {
            let _y = &mut x;
        }
    };
}
```

Or, if we do not return the closure:

```rust
#![feature(rustc_attrs)]
#![feature(nll)]

#[rustc_regions]
fn main() {
    let mut x = 0;
    || {
        || {
            let _y = &mut x;
        };
    };
}
```

I'm not sure which is more in the spirit of the original test. Probably the latter.

**Comment by nikomatsakis** [comment]
I'm not sure what's left to do here. I guess maybe alter the test case? It seems like NLL is generating the correct error.

**Comment by nikomatsakis** [comment]
Marking as a Preview 2 blocker just because it's so ridiculously simple. Let's get this done. I'll assign to myself.

**Comment by canselcik** [comment]
I am experiencing this while trying to work with tokio and futures. Let me know if there is anything I can do as a workaround or if you would like to see me elaborate on the rest of the code:

```
error: free region `` does not outlive free region `'static`
  --> examples/live.rs:74:13
   |
74 |             tokio::executor::spawn(task)
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

```rust
let server = listener
    .incoming()
    .map_err(|e| eprintln!("accept failed = {:?}", e))
    .for_each(move |sock| {
        let (reader, writer) = sock.split();
        let req: Vec<u8> = Vec::new();
        let task = io::read_exact(reader, req)
            .and_then(|(_res, rq)| {
                ...
                io::write_all(writer, RESPONSE_PREAMBLE)
            })
            .map(|(w, _e)| {
                ...
                let jpg: Box<[u8]> = wr.into_inner().unwrap().into_boxed_slice();
                io::write_all(w, jpg)
            })
            .then(|_| Ok(()));
        tokio::executor::spawn(task)
});
```

**Comment by nikomatsakis** [comment]
@canselcik Are you still seeing this error message? I would expect it to have changed somewhat, for one thing. From what I can tell -- at least in the original example -- this indicated a legitimate error in the test.

**Comment by nikomatsakis** [comment]
The  current error message from @spastorino's test case is:

```
error: unsatisfied lifetime constraints
  --> src/main.rs:7:9
   |
6  |         || {
   |    _____-
   |   |_____|
   |  ||
7  |  ||         || {
   |  ||_________^
8  | |||             let _y = &mut x;
9  | |||         }
   | |||_________^ free region requires that `'1` must outlive `'2`
10 |  ||     };
   |  ||     -
   |  ||_____|
   |  |______lifetime `'1` represents the closure body
   |         lifetime `'2` appears in return type
```

which needs work but is a lot better than the original =)

**Comment by pnkfelix** [comment]
this has gotten good enough that we think we just need to make sure it has a test somewhere.

**Comment by davidtwco** [comment]
Submitted #52793 with the test that is remaining for this issue.
