### ISSUE TITLE
x.py should not die if I set `RUSTFLAGS=--color=never` in the env

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#49838]
Right, now, if I do `RUSTFLAGS=--color=never x.py build`, I get:

```
Building stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/home/pnkfelix/Dev/Mozilla/issue27282/rust-27282/objdir-dbgopt/build/bootstrap/debug/rustc - --crate-name ___ --print=file-names --color=never --target x86_64-unknown-linux-gnu --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro` (exit code: 101)
--- stderr
error: Option 'color' given more than once
```
My initial inference here is that we are dying because `rustc` is getting multiple `--color=never` directives (and one is coming in implicitly via `RUSTFLAGS`

In my opinion, `rustc` should allow one  to pass `--color=never` multiple times. (Arguably other combinations of `--color` should also be allowed.)
 * Perhaps we should go even further and determine general precedence rules for mixing `RUSTFLAGS` input with command line input. But I digress.

But if we want to continue having `rustc` be strict about that, then `x.py` needs to be smarter about looking at the environment when it decides what arguments to pass to the `rustc` it invokes.

**Comment by Mark-Simulacrum** [comment]
This is also presumably and probably the case for a variety of other options that we currently pass to rustc in rustbuild; I agree that this feels like a rustc bug, but it should be somewhat easy to fix or patch over in rustbuild if we wanted to...

**Comment by jyn514** [comment]
bootstrap now has built-in support for `--color` (since https://github.com/rust-lang/rust/pull/79070) and RUSTFLAGS=--color fails for other reasons that are cargo related and not controlled by bootstrap:
```
error: cannot specify the `--color` option with `--json`
```
I'm going to close this since this specific issue is no longer relevant; if you think rustc should accept multiple flags that do the same thing I agree :) but I think that deserves an MCP rather than sitting in the issue tracker ignored.
