### ISSUE TITLE
Missing `impl<'a> PartialEq<&'a str> for OsString`

### ISSUE THREAD

**Issue by Kixunil** [rust-lang/rust#49854]
I've just got very surprised to find out that `my_os_string == "foo"` doesn't compile, but `my_os_string == *"foo"` does. After some investigation, I found that `impl<'a> PartialEq<&'a str> for OsString` is missing. Similar impl is present for `String` though.

I believe it'd be nice to implement it.

**Comment by csmoe** [comment]
`&OsStr` is to `OsString` as `&str` is to `String`, so check out `impl<'a, 'b> PartialEq<&'a OsStr> for OsString`, this implementation might meet your needs.

**Comment by Kixunil** [comment]
@csmoe I've soled my problem immediately. I filed issue because I think we could help others by implementing the trait.
