### ISSUE TITLE
implement a persistent self-balancing binary search tree

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#4987]
This will need to be a different implementation than `TreeMap` - an efficient persistent tree is a different beast.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#649
