### ISSUE TITLE
(Re-)Introduce ARMv7+NEON Android and GNU/Linux targets

### ISSUE THREAD

**Issue by hsivonen** [rust-lang/rust#49897]
Even though ARMv7 Android doesn't guarantee the presence of NEON, most devices have it and e.g. Firefox opts not to support ARMv7 devices that don't have it. (Notably the Tegra 2-based ones.)

To allow Rust code, including the standard library, to unconditionally use NEON in such a scenario, it would help a lot if upstream Rust supported an ARMv7+NEON Android target. (NEON support was [explicitly removed](https://github.com/rust-lang/rust/pull/38413) from `armv7-linux-androideabi`.

In order to test code on a system that has all the usual tooling, it's useful to have a corresponding GNU/Linux target, too. NEON was [explicitly removed](https://github.com/rust-lang/rust/pull/35814) from `armv7-unknown-linux-gnueabihf` and [also](https://github.com/rust-lang/rust/pull/48466) from `armv7-unknown-linux-musleabihf`.

Please add new `androideabi` and `gnueabihf` ARMv7 targets that have NEON enabled and a NEON-enabled standard library shipped via `rustup` so that `std::simd` ends up compiled with NEON enabled. (See the [issue about boolean reductions there](https://github.com/rust-lang-nursery/stdsimd/issues/362).)

How to name these is a total bikeshed, but as a starting point, I suggest `armv7neon-unknown-linux-gnueabihf` and `armv7neon-linux-androideabi`.

**Comment by gnzlbg** [comment]
Note that `aarch64` has the same issue, so it might be worth it to add the `aarch64neon-unknown-linux-gnu` and `aarch64neon-linux-android` targets as well.

**Comment by hsivonen** [comment]
I thought that ARMv8 guaranteed 128-bit SIMD support like x86_64 guarantees SSE2. Is that not the case?

**Comment by hsivonen** [comment]
It seems that Rust's `aarch64-unknown-linux-gnu` target feels eligible to generate `ldr     q0, [x0]` for loading an `u8x16` from memory.

[Programmer’s Guide for ARMv8-A](https://static.docs.arm.com/den0024/a/DEN0024A_v8_architecture_PG.pdf) says:

> Both floating-point and NEON are required in all standard ARMv8 implementations. However, implementations targeting specialized markets may support the following combinations:
>
> * No NEON or floating-point. 
> ...

I would hope that the Rust built-in `aarch64` targets were for "standard implementations" and not for "specialized markets", so if they fail to allow some NEON instructions, we should probably edit those targets in place instead of introducing `aarch64neon` variants. But, as noted, `aarch64` in Rust seems to allow 128-bit SIMD already.

**Comment by gnzlbg** [comment]
I just tried it on stdsimd and aarch64-unknown-linux-gnu does indeed have neon always enabled :)

**Comment by hsivonen** [comment]
These were added in #49902.
