### ISSUE TITLE
`#[deprecated]` has no effect on macros

### ISSUE THREAD

**Issue by sgrif** [rust-lang/rust#49912]
The following code compiles successfully with no warnings, when it should be producing a deprecation warning.

https://play.rust-lang.org/?gist=aa4c719a14da2bb5cf3ddf8c3066f452&version=stable

**Comment by abonander** [comment]
Some discussion here: https://github.com/rust-lang/rust/pull/48524#pullrequestreview-99458407

Deprecation and stability checking is actually done after macro expansion, so a complete solution would probably need to lift both of those into phase 2. or just have a separate implementation for macros like I did with stability checking in that PR.

cc @petrochenkov

**Comment by sgrif** [comment]
If nothing else, `#[deprecated]` should be giving an error when placed on an item where it has no effect.

**Comment by abonander** [comment]
The goal is to support deprecation on macros, it's just that all the infrastructure for deprecation is in a later phase so even a naive implementation would need to redo a lot of the support. We still need stability checking and deprecation after macro expansion as well.

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/62042
