### ISSUE TITLE
Add missing conversions from OsStr to Cow

### ISSUE THREAD

**Issue by pronebird** [rust-lang/rust#49927]
Hi,

Currently we have to use `Cow::Borrowed` manually when working with `OsStr`, such as each occurrence of `Cow<OsStr>` has to be explicitly used as `Cow::Borrowed(OsStr::new("..."))`. This creates a lot of noise in the platform relevant code.

Going through docs revealed that `Cow` implements a bunch of useful `From` traits that even covers `PathBuf` and it does in fact implement `PartialEq` for `Cow<OsStr>`  however there seem to be missing `From<OsString>` or `From<OsStr>` implementations which would greatly benefit the readability of our code.

Cheers,
Andrej

**Comment by Mark-Simulacrum** [comment]
Both requested impls now exist, closing.

```
impl<'a> From<OsString> for Cow<'a, OsStr>
impl<'a> From<&'a OsStr> for Cow<'a, OsStr>
```
