### ISSUE TITLE
[nll] prepare the differential dataflow crates for potential inclusion into rust-lang

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#49925]
There are a few potential problems with using the differential dataflow crates *as is* with rustc. First off, they use `getopts`, and for weird reasons that causes a conflict for us. But their use of `rustc` is only skin deep. So maybe we can prepare a PR that converts it into a cargo feature (that rustc opts out of).

Second, at least on the current master, there [is a git dependencies from differential-dataflow to timely](https://github.com/frankmcsherry/differential-dataflow/blob/25cee91f18d4b64e4fa05a86d45932e2d07537c4/Cargo.toml#L30). That can be fixed readily enough into a version dependency, I believe.

This is only "sort of" an issue of rustc -- it's really work that needs to be done on these crates:

https://github.com/frankmcsherry/timely-dataflow
https://github.com/frankmcsherry/differential-dataflow

I'll update with a few more details in a bit.

cc @frankmcsherry -- would you object to a few PRs in this direction?

**Comment by frankmcsherry** [comment]
I'm up for PRs, but:

1. The most common use of timely and differential at the moment is free-standing. We can add a feature that rips out docopt, but we'll probably want to retain it (or, something equivalent/better, if it has some specific issues that conflict with rustc) as the default.

2. The dependencies on other git repos vanish at crate upload time, but are in place because both projects evolve between versions. If there is a more tasteful way to do that other than me pushing a new version of timely, bumping the differential dependence to timely on crates.io, then pushing that to the repo for as long as it doesn't need to target the new timely, great!

**Comment by nikomatsakis** [comment]
@frankmcsherry 

> The most common use of timely and differential at the moment is free-standing.

I anticipated adding a cargo feature for getopts that is included in the "default" set of features. So people wouldn't have to ask for it, but rustc could opt out (with "no-default-features").

> The dependencies on other git repos vanish at crate upload time, but are in place because both projects evolve between versions.

I think you can have both a `version` and a `path` dependency to reflect this. But it doesn't really matter. My main goal is to use stuff from crates.io.

**Comment by nikomatsakis** [comment]
The other thing that I'd like to do at some point is to maybe tweak the API to help out with rustc's use case, which will tend to do lots of small, independent dataflows. But I think we need to figure out what that means -- one thing that would be convenient is dropping the `'static` bound on the `execute` function (or having a variant). This should be possible so long as `execute` is blocking.

(In particular it'd be nice to be able to pass in `&T` data.)

**Comment by qmx** [comment]
@frankmcsherry having git tags with the exact code that goes to crates.io would be quite helpful, as I spent some time trying to figure out how differential-dataflow was magically depending on a newer version of timely :)

**Comment by frankmcsherry** [comment]
@nikomatsakis We can talk through the passing in of `&T` data. If you just want to use it in the closure it should be fine, but if you want to use it in operator logic (e.g. in a `map`) it involves a fairly heavy modification to timely (the dataflow operators live as boxed trait objects, and the trait is not currently parametric in a lifetime).

**Comment by nikomatsakis** [comment]
> If you just want to use it in the closure it should be fin

At least that would be useful, so that I can walk various data structures to supply the initial inputs. It could also be useful for emitting output, but there are other solutions.

**Comment by qmx** [comment]
```
Dev-dependencies are not allowed to be optional: `getopts` 
```

this is going to be a fun one to figure out
