### ISSUE TITLE
No nightlies at 2018-04-13

### ISSUE THREAD

**Issue by alexbool** [rust-lang/rust#49929]
Executed today:
```
alexbool@alexbool-osx ~> rustup update nightly
info: syncing channel updates for 'nightly-x86_64-apple-darwin'

  nightly-x86_64-apple-darwin unchanged - rustc 1.27.0-nightly (ad610bed8 2018-04-11)

alexbool@alexbool-osx ~> rustup -vV
rustup 1.11.0 (e751ff9f8 2018-02-13)
```

**Comment by oli-obk** [comment]
That's normal. Nightlies only exist if rls builds successfully: https://rust-lang-nursery.github.io/rust-toolstate/

**Comment by alexbool** [comment]
I guess this is OK in terms “when there is no rls, there should be no nightlies”, but it’s still not OK in terms of “nightlies should be shipped every night provided there are commits to master branch of rust repo”. Correct me if I’m wrong.

**Comment by oli-obk** [comment]
I'm confused. That statement is correct, but it requires "nightlies should be shipped every night provided there are commits to master branch of rust repo", which isn't something that is guaranteed afaik. Do you have a link to something that states this? We should probably update it in that case

**Comment by Mark-Simulacrum** [comment]
I'm going to close this as non-actionable / expected behavior.
