### ISSUE TITLE
Regression in 1.26 with misplaced attributes

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#49934]
All the regressed crates have a misplaced `#[derive]` in the codebase (such as a `#[derive(Debug)]` above a variable declaration). In Rust 1.25 the compiler accepts the code, but in Rust 1.26 it throws an error _and then_ crashes.

* [bitlab](https://crates.io/crates/bitlab) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/bitlab-0.8.1/log.txt)) cc @kkayal
* [promise-rs](https://crates.io/crates/promise-rs) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/promise-rs-0.3.0/log.txt)) cc @stan-kondrat
* [serde_bencode](https://crates.io/crates/serde_bencode) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/serde_bencode-0.2.0/log.txt)) cc @toby
* [paulkramme/rustybrainfuck](https://github.com/paulkramme/rustybrainfuck) regressed from stable to beta ([build log](http://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/gh/paulkramme.rustybrainfuck.072942e1220da27ccc56b3bc04c7165bdf5cef0d/log.txt)) cc @paulkramme

Even if we keep the error (which could be turned into a warn-by-default lint) the ICE should be fixed.

**Comment by pietroalbini** [comment]
This also happens with misplaced attributes on functions:

* [chiisai](https://crates.io/crates/chiisai) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/chiisai-0.1.5/log.txt)) cc @mgattozzi
* [foundation](https://crates.io/crates/foundation) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/foundation-0.0.1/log.txt)) cc @mgattozzi
* [libimagentrylink](https://crates.io/crates/libimagentrylink) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/libimagentrylink-0.6.4/log.txt)) cc @matthiasbeyer
* [seq_io](https://crates.io/crates/seq_io) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/seq_io-0.2.3/log.txt)) cc @markschl

**Comment by Mark-Simulacrum** [comment]
cc @alexcrichton @dtolnay -- proc-macro related changes presumably

**Comment by mgattozzi** [comment]
I have a feeling I know where it's broken in one of my macros for chiisai based off the build log. I slapped an #[inline(always)] above a closure that gets passed to it in that macro. I'll need to confirm though. It's a non proc_macro just the regular macro_rules!

**Comment by alexcrichton** [comment]
My guess is that this isn't related to procedural macros but rather https://github.com/rust-lang/rust/pull/49291, cc @tejom and @petrochenkov

**Comment by tejom** [comment]
The change that effected inline and closures was brought up in issue #49632 

I don't mind making a change to make the original pull request a warning if that is preferred?

**Comment by tejom** [comment]
The ice with the derive check doesn't seem to be caused by #49291 

```rust
fn main() {
        #[derive(Debug)]
        let _a = 5;

        #[repr(always)]
        let _x = 12;
}
```

This compiles with stable. 
That pull request I made was in nightly on 2018-04-01, and that only has an error for the incorrect repr above `_x`
With nightly from 2018-04-10 The compiler crashed after showing an error about the incorrect derive.

**Comment by pietroalbini** [comment]
Did a bisect run, and #49124 is the source of the ICE. cc @petrochenkov @abonander

**Comment by abonander** [comment]
I saw this issue earlier and meant to comment that I was pretty sure it was my PR, so I could have saved you a bisect. However, I [haven't been able to build Rust for at least a week](https://github.com/rust-lang/rust/issues/49869) so I'm afraid I'm not much help.

**Comment by abonander** [comment]
Ironically I'm able to work on beta and not nightly.

However, compile-fail seems to eat the ICE because while I can reproduce it on master, I have to manually call the built rustc to get it because the compile-fail suite passes because it still produces the expected error.

**Comment by nikomatsakis** [comment]
triage: P-high

Has a pending fix.
