### ISSUE TITLE
Constant evaluation regression in beta 1.26

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#49930]
There were some constant evaluation failures in the beta crater run.

* [x] [ostn02_phf](https://crates.io/crates/ostn02_phf) regressed from stable to beta ([1.25 build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/1.25.0/reg/ostn02_phf-0.1.13/log.txt) - [1.26 build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/ostn02_phf-0.1.13/log.txt)) cc @urschrei
* [x] [out123-sys 0.2.1](https://crates.io/crates/out123-sys/0.2.1) regressed from stable to beta ([1.25 build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/1.25.0/reg/out123-sys-0.2.1/log.txt) - [1.26 build log](http://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/out123-sys-0.2.1/log.txt)) cc @IvanUkhov

The first crate is actually deprecated/abandoned, and the second regression only appears in an old version (the latest is version 0.5.0). cc @oli-obk

**Comment by oli-obk** [comment]
fixing the ostn02_phf case is simple, I thought I already did that, but apparently not. I'll remove the complexity check and make it a lint as discussed in https://github.com/rust-lang/rfcs/pull/2344#issuecomment-368246665

**Comment by pietroalbini** [comment]
`ostn02_phf` is being backported to beta in #50027

**Comment by urschrei** [comment]
Is that fix also being backported to nightly? `ostn02_phf` is indeed deprecated, but its replacement (`ostn15_phf`) has an [open issue](https://github.com/rust-lang/rust/issues/36799) which (as I just found out) is dependent on the fix – it currently only builds on stable macOS / Linux

**Comment by pietroalbini** [comment]
> Is that fix also being backported to nightly?

@urschrei that fix is already available in the nightly (master) branch, and the PR I linked backports it to beta. The only "problem" is, since Sunday no new nightlies were released because [rls is broken](https://rust-lang-nursery.github.io/rust-toolstate/). Once rls will be fixed new nightlies (with the fix) will be released.

**Comment by urschrei** [comment]
@pietroalbini Thanks!

**Comment by pietroalbini** [comment]
The `ostn02_phf` fix is backported to beta. What about `out123-sys` 0.2.1 @oli-obk?

**Comment by oli-obk** [comment]
nightly PR in progress: https://github.com/rust-lang/rust/pull/50072

still needs a `beta-accepted` stamp

**Comment by pietroalbini** [comment]
Backport PR: https://github.com/rust-lang/rust/pull/50248

**Comment by pietroalbini** [comment]
Backported to beta.
