### ISSUE TITLE
Regression in 1.26: Cargo.toml parsing of a crate fails

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#49946]
* [polylabel_cmd](https://crates.io/crates/polylabel_cmd) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/polylabel_cmd-0.0.28/log.txt)) cc @urschrei

```
error: failed to parse manifest at `/source/Cargo.toml`

Caused by:
  the target `polylabel` is a binary and can't have any crate-types set (currently "bin")
```

**Comment by Mark-Simulacrum** [comment]
cc @matklad @alexcrichton (possibly fixed since then, this is beta.2)

**Comment by pietroalbini** [comment]
That's still happening in beta.3 (latest one available in rustup):

```
pietro@january: ~/tmp/polylabel_cmd$ rustc +beta --version                               
rustc 1.26.0-beta.3 (8a75d2b50 2018-04-08)                                               
pietro@january: ~/tmp/polylabel_cmd$ cargo +beta build                                   
error: failed to parse manifest at `/home/pietro/tmp/polylabel_cmd/Cargo.toml`           
                                                                                         
Caused by:                                                                               
  the target `polylabel` is a binary and can't have any crate-types set (currently "bin")
pietro@january: ~/tmp/polylabel_cmd$                                                     
```

**Comment by alexcrichton** [comment]
Thanks for the diagnosis @matklad! Your conclusion sounds good to me

**Comment by urschrei** [comment]
Nbd for the crate either; I’ll push an update when I get a sec.

-- 
steph

**Comment by lukaslueg** [comment]
The grep in https://github.com/rust-lang/cargo/pull/5204 was done on a copy of crates.io that didnt yet have `polylabel_cmd` in it. A version from mid-march only finds `polylabel_cmd`.

**Comment by alexcrichton** [comment]
I'm going to close this due to @matklad's comment, but if there are any issues in updating crates please let us know!
