### ISSUE TITLE
Regression in 1.26: duplicate name `Bound`

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#49941]
There is a crate that regressed thanks to the introduction of `std::ops::Bound`.

* [gfx_scene](https://crates.io/crates/gfx_scene) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/gfx_scene-0.8.0/log.txt)) cc @kvark

**Comment by Mark-Simulacrum** [comment]
Hm, I thought we permitted overlapping glob imports, but perhaps that's not the case when they are used. cc @petrochenkov

**Comment by petrochenkov** [comment]
@Mark-Simulacrum 
Exactly. The conflict glob vs glob is not reported eagerly, but when the ambiguous name is actually used we have no other choice than to report an error.
This falls under "minor allowed breakage" IIRC.

**Comment by alexcrichton** [comment]
This was discussed during libs triage and given the limited impact here and the responses we've decided to not revert the renaming, so I'm gonna close this.
