### ISSUE TITLE
Inference regression in 1.26

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#49944]
There is an inference regression for a rust project.

* [jonhoo/rust-at-sunrise](https://github.com/jonhoo/rust-at-sunrise) regressed from stable to beta ([build log](http://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/gh/jonhoo.rust-at-sunrise.52fcbf516f1f051d8cacad852f4a800b264194fc/log.txt)) cc @jonhoo

**Comment by Mark-Simulacrum** [comment]
cc @nikomatsakis -- I think you wanted to at least be aware of these regressions. We'll probably be closing this though as it looks minimally impactful.

**Comment by nikomatsakis** [comment]
Hmm. Thanks. I'm not sure what would cause that off top of my head.

**Comment by pnkfelix** [comment]
visiting for triage.

@pietroalbini are you in a position to provide a standalone, minimized test case to speed up our ability to jump on this?

**Comment by pnkfelix** [comment]
triage: P-high 

(for now, since its a stable-to-beta regression, though @Mark-Simulacrum commented above that the impact may be "minimal" so who knows, it might get downgraded real soon...)

**Comment by pietroalbini** [comment]
Bisect points at #49163 (wut?), cc @SimonSapin

**Comment by SimonSapin** [comment]
I think this is business as usual when adding new impls. It is a minor change per https://github.com/rust-lang/rfcs/blob/master/text/1105-api-evolution.md#minor-change-implementing-any-non-fundamental-trait since the closure can be changed to `|d| {…}` to `|d: DateTime<Utc>| {…}` to fix this and still work in older versions.

**Comment by pietroalbini** [comment]
Since the crate is now fixed and the breakage was minor and expected, I'm closing this. Thanks to everyone involved on this!
