### ISSUE TITLE
Trait method `std::os::windows::fs::OpenOptionsExt::security_qos_flags()` returns a `&mut OpenOptions` instead of `&mut Self`

### ISSUE THREAD

**Issue by Ereski** [rust-lang/rust#49961]
https://doc.rust-lang.org/src/std/sys/windows/ext/fs.rs.html#279-281

There's no reason for that method to return a concrete type instead of `Self`. I am currently writing an `OpenOptions` wrapper and that method is preventing me from implementing `OpenOptionsExt` for the wrapper. However, the trait is already stable (even if most likely unimplemented outside `libstd`) so I'm not sure what's the proper way of changing this?

**Comment by Ereski** [comment]
@alexcrichton I see. However in this case (and a few others), the fact that they can't be implemented by external types means wrapper types can't act as drop-in replacements for `libstd` types in all cases, which is my intent.

Just to clarify, *all* extensions traits (`TypeExt` for some type?) are considered unstable to implement and stable to use?

**Comment by alexcrichton** [comment]
@Ereski yeah at this time the `*Ext` traits are intended to be internal implementation details of libstd (purely intended as a trait for one particular type).

**Comment by retep998** [comment]
I believe the current goal is to replace the extension traits with inherent methods directly on the types, but with the portability lint so you're still aware you're using platform specific methods.
