### ISSUE TITLE
"found possibly newer version of crate `std` which `cc` depends on" while building rustc

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#49979]
While working on std lately, I semi-regularly end up with an error like below. Unfortunately I don’t know the exact conditions to reproduce this. It possibly involves re-using a build directory after starting a new branch from a new position of git `upstream/master`.

This looks similar to https://github.com/rust-lang/rust/issues/44739, which was fixed in https://github.com/rust-lang/rust/pull/44792. Maybe something there regressed? CC @Mark-Simulacrum 

```rust
Building stage1 codegen artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu, llvm)
   Compiling rustc_llvm v0.0.0 (file:///home/simon/rust1/src/librustc_llvm)
error[E0460]: found possibly newer version of crate `std` which `cc` depends on
  --> librustc_llvm/build.rs:11:1
   |
11 | extern crate cc;
   | ^^^^^^^^^^^^^^^^
   |
   = note: perhaps that crate needs to be recompiled?
   = note: the following crate versions were found:
           crate `std`: /home/simon/rust1/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-bde80a95b5831673.rlib
           crate `std`: /home/simon/rust1/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-bde80a95b5831673.so
           crate `cc`: /home/simon/rust1/build/x86_64-unknown-linux-gnu/stage1-rustc/release/deps/libcc-5e2a255eead634fb.rlib

error: aborting due to previous error

For more information about this error, try `rustc --explain E0460`.
error: Could not compile `rustc_llvm`.
```

**Comment by petrochenkov** [comment]
Stuff like this is especially annoying during bisecting, you can't just checkout a commit and test.

**Comment by dsciarra** [comment]
I can confirm this error still happens. Restarting the build didn't help I had to first delete the generated libraries. @Mark-Simulacrum did the refactor of rustbuild already land?

**Comment by Mark-Simulacrum** [comment]
It's in progress; there's a PR open which I think might help with this or at least help make a future PR simpler (https://github.com/rust-lang/rust/pull/52036).

**Comment by guyuming76** [comment]
i am new to rust, i am brought here by search engine with the same error message.

i "fixed" the error with cargo clean.

![Screenshot_20220307_085003](https://user-images.githubusercontent.com/12045548/156950888-2ffe7ad0-8cf0-4283-a8e6-9c07e9b0de99.png)
