### ISSUE TITLE
How could I compile the Rust to JavaScript or asm.js?

### ISSUE THREAD

**Issue by 3442853561** [rust-lang/rust#49978]
There is a platform(WeChat Minigame) can not support the wasm.

**Comment by est31** [comment]
You have two options: first you can use the emscripten backend to compile Rust to asm.js. Second you can compile Rust to wasm (using either emscripten or the `unknown` backend) and then compile that [wasm to asm.js](https://github.com/WebAssembly/binaryen/blob/master/src/wasm2asm.h).

**Comment by 3442853561** [comment]
@est31 thanks
