### ISSUE TITLE
Incorrect niche filling if enum contains both i32 min and i32 max variants

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#49973]
```rust
#![allow(dead_code)]

#[derive(Debug)]
#[repr(i32)]
enum E {
    Min = -2147483648i32,
    Max = 2147483647i32,
}

fn main() {
    println!("{:?}", Some(E::Min));
}
```

Rust 1.23.0 correctly prints `Some(Min)`. Rust 1.24.0 incorrectly prints `None`.

Mentioning @eddyb because this sounds potentially relevant to #45225 or follow-on optimization.

(Discovered by @udoprog in #rust.)

**Comment by glandium** [comment]
Clearly from #45225 rather than a followup, as it's happening in nightly-2017-11-21 and not in nightly-2017-11-20.

**Comment by nox** [comment]
This is not specific to `i32` but to the enum using both signed extremums of its representation type:

```
#[derive(Debug)]
#[repr(i8)]
enum E {
    Min = -128i8,
    Max = 127i8,
}
```
