### ISSUE TITLE
Rustc doesn't know when libstd function implements ops::Try

### ISSUE THREAD

**Issue by ripread** [rust-lang/rust#49992]
When I compile and run this code

    fn main() {
        let temp = &env::current_dir();
        println("{:?}", temp);
    }

I get this output `Ok("/playground")` [link](https://play.rust-lang.org/?gist=57e0be34e383545b97ef42d0cadfed6f&version=stable)

When I add a `?` to the function call as seen in this code 

    fn main() {
        let temp = &env::current_dir()?;
        println("{:?}", temp);
    }

I get the this compile error `error[E0277]: the '?' operator can only be used in a function that returns 'Result' ...` [link](https://play.rust-lang.org/?gist=1c2acf9ae581ec12cef074030ac673a1&version=stable)

**Comment by sfackler** [comment]
The function `main` returns `()`, not a `Result`.

**Comment by ripread** [comment]
ah crap :'(
