### ISSUE TITLE
NLL: dropck_vec_cycle_checked.rs very slow to compile

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#49998]
As noted on https://github.com/rust-lang/rust/pull/49900#issuecomment-381582647 it appears that dropck_vec_cycle_checked.rs under `-Znll` requires more than an hour to compile (not yet clear how much time is *actually* required.)

Here is a reduced version of that test case that exhibits a 50x slowdown under `-Znll`. (Namely, it takes 0.163s to compile without `-Znll`, and takes 8.424s to compile with `-Znll`

```rust
// Reduced version of compile-fail/dropck_vec_cycle_checked.rs that
// still exhibits unacceptable time blow-up (but not to the point of
// being unrunnable).

use std::cell::Cell;

trait HasId { }
struct CheckId<T:HasId> { v: T }
impl<T:HasId> Drop for CheckId<T> { fn drop(&mut self) { } }
struct C<'a> { v: Vec<CheckId<Cell<Option<&'a C<'a>>>>> }
impl<'a> HasId for Cell<Option<&'a C<'a>>> { }
impl<'a> C<'a> { fn new() -> C<'a> { C { v: Vec::new() } } }

fn main() {
    let (mut c1, mut c2);
    c1 = C::new();
    c2 = C::new();

    c1.v[0].v.set(Some(&c2));
    //~^ ERROR `c2` does not live long enough

    c1.v[0].v.set(Some(&c2));
    //~^ ERROR `c2` does not live long enough
}
```

**Comment by pnkfelix** [comment]
It seems the problem, at least in this case, is this [line of code](https://github.com/rust-lang/rust/blob/8728c7a726f3e8854f5a80b474d1a8bacab10304/src/librustc_mir/borrow_check/nll/region_infer/values.rs#L266)

```rust
 if cause < **old_cause {
```

After some inspection with `gdb` and `perf`, my guess is that these [`region_infer::Cause`s](https://github.com/rust-lang/rust/blob/8728c7a726f3e8854f5a80b474d1a8bacab10304/src/librustc_mir/borrow_check/nll/region_infer/mod.rs#L104) can build up into (very?) long  linked-list chains. I would think that the automatically-derived `PartialOrd` implementation would only fall into bad performance if those long chains have matching prefixes, but I haven't actually confirmed that (i.e., is it possible that the derived `PartialOrd` does not short cut when an early point in the linked list is different? Does it *need* to reach the end for some reason?)

Anyway, from what I can tell this code is just trying to reduce the cause to something simpler, but maybe once we are looking at two instances of `Cause::Outlives` we should not be wasting time trying to figure out which one is "less" ?

So some experiments to try:

 1. Find out how *long* these chains actually are. Perhaps even store the length *in* the `Outlives` variant and use that as a way to eagerly exit the comparison when the two lengths are not the same. I haven't done this yet because I was more interested in trying the next experiment.
 2. Make a variant comparison method that does not recur, and instead just always returns false for two `Cause::Outlives`. I have implemented this and it seems to address the slow-down for this test case.

**Comment by pnkfelix** [comment]
A variation on outright skipping comparison when given two `Outlives`: always reduce the two inputs to `root_cause()` before comparing them. In my initial experiments, this seems like it yields a similar performance boost in error reporting to what I reported above, while I think it has a *smaller* (though still non-zero) impact on the actual errors we currently produce on the ui test suite.

**Comment by ishitatsuyuki** [comment]
Please revisit the status of this issue, as the PartialOrd bug is fixed.

**Comment by nikomatsakis** [comment]
Testing with nightly now, I see no difference at all between them.
