### ISSUE TITLE
Off by one error in str::index_mut (specifically) for RangeToInclusive (specifically)

### ISSUE THREAD

**Issue by ExpHP** [rust-lang/rust#50002]
Caught while fleshing out a much beefier test suite for SliceIndex, which I plan to submit as a PR.  (this Issue is here just in case that PR never happens).

https://github.com/rust-lang/rust/blob/1ef1563518d48ad9231b3ec3ac463d34d819ed28/src/libcore/str/mod.rs#L2107-L2115

The unicode character boundary check here should be looking at `self.end + 1`.  Better yet, the method could just delegate to `RangeTo` instead. (note: it can't delegate to `get_mut` here without NLL, which seems to be a leading factor as to how this function ended up this way)

**Comment by alexcrichton** [comment]
Not technically a regression but tagging it as such to ensure that we don't forget about it.

**Comment by ExpHP** [comment]
@alexcrichton my commit message accidentally closed this, which might defeat the purpose of the tag you added

**Comment by alexcrichton** [comment]
Oh that's ok, the tags on the PR take over now for backporting and that's how we'll track this.
