### ISSUE TITLE
Disk space requirement when building should be indicated in the readme

### ISSUE THREAD

**Issue by krk** [rust-lang/rust#50019]
Currently, around 54 GB is required for a default incremental build (`x.py build -i`). 

We may include some tips to decrease disk space requirements in the readme, potentially not building all LLVM targets etc.

**Comment by Mark-Simulacrum** [comment]
I see a 3.6 GB build locally with a fresh checkout and a single run of `./x.py build -i`. Could you clarify if that's the same as your configuration?

**Comment by krk** [comment]
I am building on Windows Subsystem for Linux as Windows build didn't work.

Fresh checkout + single run is correct. I am attaching a dir size report [1], please note that I ran `x.py test` for a single test since.
![image](https://user-images.githubusercontent.com/1447853/38891712-d293ca24-428d-11e8-9b74-e4bacc0ee4da.png)

[1] https://gist.github.com/krk/90ef18338975b27fc7c79a8439bbed40

**Comment by Mark-Simulacrum** [comment]
I'm afraid I cannot reproduce and as such am uncertain whether we can effectively document this; I also don't have access to a WSL environment so I can't test there either.

It would also be helpful to have a copy of your `config.toml`.

**Comment by krk** [comment]
Here is my `config.toml` https://gist.github.com/krk/73bd0f11bd1aecbf24617662f1d148e2

Inclusion of some kind of estimate could be helpful to first-time builders, even just giving a ball park. As examples, [Chromium ](https://chromium.googlesource.com/chromium/src/+/master/docs/windows_build_instructions.md#system-requirements) and [Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Windows_Prerequisites#Hardware_and_software_requirements) gives estimated disk space usages.

**Comment by Mark-Simulacrum** [comment]
So that's a non-standard configuration; I see ~30 GB locally with it.

I think it may be somewhat helpful to add a note that a debug configuration could be upwards of 30 GB, however a default configuration (with no configuration flags changed) you'll see about a 3.6 GB build. If you'd like to make a PR adding that, please go ahead! We should probably add it to the CONTRIBUTING file instead of the README, though.
