### ISSUE TITLE
x.py check doesn't take previous x.py build into account

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#50037]
After successfully running `x.py build`, we know `x.py check` is also going to succeed. It shouldn't then try re-checking `rustc`. (This should probably take into account the build on an incremental basis.)

Issue on cargo: https://github.com/rust-lang/cargo/issues/3501

**Comment by Mark-Simulacrum** [comment]
I'm going to close this since I don't think this is something that's feasible or wanted to fix on rustbuild's side. Of course, improvements to Cargo in this area are much appreciated. Thanks!
