### ISSUE TITLE
Make os::make_absolute logic available for arbitrary Paths

### ISSUE THREAD

**Issue by mitsuhiko** [rust-lang/rust#5003]
Especially in web applications (or other apps that do not use the current working directory of the operating system) it would be useful to be able to use make_absolute against an arbitrary path.  In Python that's provided by `os.path.join`.  Unfortunately that also comes with negative security aspects (if the right hand side is absolute).

I would propose a `Path::unsafe_join` function that works like the Python one.  As an extension it would also make sense to further improve how joining works for Windows.

Example implementation: https://gist.github.com/mitsuhiko/4974499

**Comment by l0kod** [comment]
cc #16507

**Comment by steveklabnik** [comment]
@alexcrichton how did this turn out with the Path RFC?

**Comment by alexcrichton** [comment]
We've removed `make_absolute` essentially and this would be an addition to the `Path` API (e.g. would require an RFC).

**Comment by l0kod** [comment]
Why does `make_absolute` was removed? It should be useful to be able to set a `Path` as *always absolute*.

Like said @mitsuhiko, the current `join` is [dangerous](https://github.com/rust-lang/rust/issues/16507#issuecomment-73804876) and should be replaced with something else (e.g. `splice`).

**Comment by l0kod** [comment]
Normalization for paths is motioned in #22500.

However there seems to be nothing about [unsafe join](https://github.com/rust-lang/rust/issues/16507).
Something like `AsPath::nest(&self, path: &AsPath) -> PathBuf` could be a safe alternative to `Path::join()` and `PathBuf::push()`.

**Comment by alexcrichton** [comment]
This function ended up being removed, so I'm going to close this in favor of a to-be-opened RFC issue to include this functionality.
