### ISSUE TITLE
Macro expansion cannot find variable in scope

### ISSUE THREAD

**Issue by akshaynanavati** [rust-lang/rust#50042]
Macro expansion cannot find variable in scope

I tried this code:

```
macro_rules! foo {
    (@inner foo) => {
        return bar;
    };
    (bar) => {
        fn f() -> String {
            let bar = "hello".to_string();
            foo!(@inner foo);
        }
    };
}

foo!(bar);

fn main() {
    f();
}

```

I expected to see this happen: I expected this to compile.

Instead, this happened: It did not compile with the following error message:

```
error[E0425]: cannot find value `bar` in this scope
  --> macro.rs:3:16
   |
3  |         return bar;
   |                ^^^ not found in this scope
...
13 | foo!(bar);
   | ---------- in this macro invocation
```

## Meta

`rustc --version --verbose`:

```
rustc 1.27.0-nightly (4b9b70c39 2018-04-09)
binary: rustc
commit-hash: 4b9b70c394e7f341b4016fce4cbf763d404b26f9
commit-date: 2018-04-09
host: x86_64-apple-darwin
release: 1.27.0-nightly
LLVM version: 6.0
```

Backtrace: When I compiled with `-Z unstable-options --pretty=expanded`, I get:

```
#![feature(prelude_import)]
#![no_std]
#[prelude_import]
use std::prelude::v1::*;
#[macro_use]
extern crate std;
macro_rules! foo(( @ inner foo ) => { return bar ; } ; ( bar ) => {
                 fn f (  ) -> String {
                 let bar = "hello" . to_string (  ) ; foo ! ( @ inner foo ) ;
                 } } ;);
fn f() -> String { let bar = "hello".to_string(); return bar; }


fn main() { f(); }
```

which on its own compiles, because `bar` is indeed in scope in the function `f`.

[Playground link to macro code](https://play.rust-lang.org/?gist=c118d578edd1da866f03fe69d1d81929&version=stable)

[Playground link to macro expansion which compiles](https://play.rust-lang.org/?gist=762f6dca25b7a9aae0f02450220612c3&version=stable)

**Comment by dtolnay** [comment]
I believe this is intentional and a consequence of "macro hygiene". Each invocation of `foo!` has its own instance of the identifier `bar` and unless a `bar` is passed from one invocation to the next, they will end up being different `bar`s.

More on hygiene:

- https://doc.rust-lang.org/book/first-edition/macros.html#hygiene
- https://danielkeep.github.io/quick-intro-to-macros.html#being-hygienic
