### ISSUE TITLE
Filtering file names with ends_with

### ISSUE THREAD

**Issue by msehnout** [rust-lang/rust#50059]
Let's say that I would like to have a list of all *.conf files from the "/etc" directory. The intuitive way to do this is by using `read_dir` and `filter` with `.path().ends_with(".conf")`, but it does not seem to work. Am I using the API wrong or is it a bug?

rustc 1.27.0-nightly (7360d6dd6 2018-04-15)

[Playground](https://play.rust-lang.org/?gist=e23c35a1f7af99ab3745b644cb5cd80b&version=undefined)
```rust
use std::fs;

fn main() {
    println!("Hello, world!");
    let files = fs::read_dir("/etc").unwrap();

    files
        .filter(move |n| {
            if let Ok(file) = n {
                println!("{:?}", file.path());
                println!("{:?}", file.path().ends_with("conf"));
                let i = format!("{:?}", file.path());
                println!("{}", i);
                println!("{:?}", i.ends_with("conf\""));
                //file.path().ends_with(".conf")
                //true
                false
            } else {
                false
            }
        })
        .for_each(|f| ());//println!("{:?}", f));
}
```

**Comment by kennytm** [comment]
Questions are better asked on https://users.rust-lang.org, thanks!
