### ISSUE TITLE
Compiler can suggest use of unstable feature in error message (underscore lifetime)

### ISSUE THREAD

**Issue by DanielKeep** [rust-lang/rust#50055]
In the StackOverflow question [“error: underscore lifetimes are unstable” when implementing From\<std::sync::PoisonError\>](https://stackoverflow.com/questions/49895886/error-underscore-lifetimes-are-unstable-when-implementing-fromstdsyncpoi/49896588?noredirect=1#), the compiler apparently suggested the user use `'_` for a reference lifetime.  I presume this is a hint which was written *prior* to `'_` becoming valid syntax to use.  This led to the user effectively being directed to solve a basic problem (no lifetime on a reference in an enum) with an unstable, nightly feature.

It might be wise to change the message to avoid confusion.

**Comment by estebank** [comment]
I believe we no longer suggest `'_` anywhere, but we do still use it in some output.

This ticket will be closed once we:

* When encountering `'_` in a definition, we provide a structured suggestion to add a named lifetime in the appropriate place
* When encountering a definition with a missing lifetime in an ADT definition we provide a structured suggestion to add a named lifetime

**Comment by estebank** [comment]
Current output for 

```rust
struct S<'_> {
    x: &'_ (),
}
```
is
```
error[E0637]: `'_` cannot be used here
 --> src/lib.rs:1:10
  |
1 | struct S<'_> {
  |          ^^ `'_` is a reserved lifetime name

error[E0106]: missing lifetime specifier
 --> src/lib.rs:2:9
  |
2 |     x: &'_ (),
  |         ^^ expected named lifetime parameter
  |
help: consider introducing a named lifetime parameter
  |
1 | struct S<'a, '_> {
2 |     x: &'a (),
  |
```

and for

```rust
struct X<'a> {
    y: &'a (),
}
struct S {
    x: X<'_>,
}
```
```
error[E0106]: missing lifetime specifier
 --> src/lib.rs:5:10
  |
5 |     x: X<'_>,
  |          ^^ expected named lifetime parameter
  |
help: consider introducing a named lifetime parameter
  |
4 | struct S<'a> {
5 |     x: X<'a>,
  |
```
