### ISSUE TITLE
Always implement `ExactSizeIterator` for `std::iter::Take`

### ISSUE THREAD

**Issue by pitdicker** [rust-lang/rust#50057]
Currently `std::iter::Take` only implements `ExactSizeIterator` if its parent iterator implements that. But `Take` knows how many elements it will return at most, so I think it makes sense if it would always implement `ExactSizeIterator`.

It would not be correct if the parent iterator produces less items, but this trait is only a best effort to help optimizations, right?

**Comment by Enet4** [comment]
`Take` already takes advantage of the given upper bound in [`size_hint`](https://doc.rust-lang.org/stable/src/core/iter/mod.rs.html#2302). However, implementing `ExactSizeIterator` requires the adaptor to know exactly which elements it contains, and not just an estimation.

**Comment by pitdicker** [comment]
Both thanks for the replies, I now understand the role of `ExactSizeIterator` a bit better!
