### ISSUE TITLE
rust 1.25 build issue - name of src/llvm/include/llvm/ADT/SmallVector.h collision with Solaris sys/regset.h

### ISSUE THREAD

**Issue by psumbera** [rust-lang/rust#50078]
There was not such problem with previous rust versions (last I built was 1.24.1).

The issue is that `src/llvm/include/llvm/ADT/SmallVector.h` uses CS and FS as variables and it collides with macros in Solaris `sys/regset.h`.

This is known issue. For reasons like this there is:

`rustc-1.25.0-src/src/llvm/include/llvm/Support/Solaris/sys/regset.h`

which does `#undef` for these.

For now I have resolved it via following:
```

--- a/src/llvm/include/llvm/ADT/SmallVector.h
+++ b/src/llvm/include/llvm/ADT/SmallVector.h
@@ -32,6 +32,9 @@
 #include <type_traits>
 #include <utility>

+#undef CS
+#undef FS
+
 namespace llvm {

 /// This is all the non-templated stuff common to all SmallVectors.
```

Any idea what changed in rust 1.25 against 1.24.1 which is causing this issue?

**Comment by Lapz** [comment]
I think the upgrade to llvm 6 could be the cause

**Comment by Enselic** [comment]
Triage: Would you mind clarifying what the Rust project can do here please? Isn't this purely an issue for the LLVM project?

**Comment by psumbera** [comment]
I think we can close the issue now. This is no longer problem.
