### ISSUE TITLE
Search anything that starts with 's' on docs.rs

### ISSUE THREAD

**Issue by ivanovaleksey** [rust-lang/rust#50074]
Hello, 

It seems I have noticed a bug on docs.rs.

I am not able to search anything that start with 'S'.
I guess it is because of
> Click or press ‘S’ to search, ‘?’ for more options…

So, when one presses 'S' search field takes a focus but consequent 'S' presses do nothing. 
It results in very inconvenient way to search without leading 'S' and to hope that autocomplete will help me.

I have opened [a topic](https://users.rust-lang.org/t/search-anything-that-starts-with-s-on-docs-rs/16949) on Rust Forum.
There are interesting points from others:

> It’s worth noting that this does not happen if you try searching sufficiently old docs. Here’s an example of sufficiently old docs that don’t exhibit this problem.

> Just tried. Also sometimes does not work when second is s.

I don't know where this issue should be filed.
Please, correct me if I am doing something wrong.

Thank you.

P. S.
I tried on macOS with:
- Chrome 65.0.3325.181
- Safari 11.0.3 (13604.5.6)

Also, it works fine on https://doc.rust-lang.org/std/

**Comment by nagisa** [comment]
This has been fixed by https://github.com/rust-lang/rust/pull/49152. You should fill an issue against [docs.rs](https://github.com/onur/docs.rs) and request them to upgrade.

**Comment by ivanovaleksey** [comment]
Thank you guys.
It turns out an issue has been already filed on docs.rs repository https://github.com/onur/docs.rs/issues/190
Also, this issue is a duplicate of https://github.com/rust-lang/rust/issues/49075
