### ISSUE TITLE
cfg_target_feature doesn't work for all supported rustc features

### ISSUE THREAD

**Issue by raphaelcohn** [rust-lang/rust#50077]
Viz,

`target_feature` does not work for `rdrnd` but does work for `avx2` (rustc `rustc 1.27.0-nightly (ac3c2288f 2018-04-18)`, Mac OS X El Capitan).

This is created with `cargo rustc -- -C target-feature=+avx2`

```rust
#[cfg(all(target_arch = "x86_64", target_feature = "avx2"))]
#[inline(always)]
pub fn generate_hyper_thread_safe_random_u64() -> u64
{
	println!("Hello World");
}
```

However, this is **NOT** created with `cargo rustc  -- -C target-feature=+rdrnd`
```rust
#[cfg(all(target_arch = "x86_64", target_feature = "rdrnd"))]
#[inline(always)]
pub fn generate_hyper_thread_safe_random_u64() -> u64
{
	println!("Hello World");
}
```

ie, changing `avx2` for `rdrnd` causes the function to not be compiled. ***Both `avx2` and `rdnrd` are present in`rustc --print target-features`***

**Comment by raphaelcohn** [comment]
Ah-ha! The code in `https://github.com/rust-lang/rust/blob/186db76159c57f4af442d8aa5e7c1a330ee0004b/src/librustc_trans/llvm_util.rs`, line 133 `("rdrand", None),` mis-labels `rdrnd` as `rdrand`.

So the list from rustc --print target-features diverges from that in that file. So it seems there's more than one source of truth.

Since `target_feature` is not yet stable, perhaps we could at least make the two lists match up?

Changing `#[cfg(all(target_arch = "x86_64", target_feature = "rdrnd"))]` to `#[cfg(all(target_arch = "x86_64", target_feature = "rdrand"))]` (`rdrnd` to `rdrand`) fixes things.

**Comment by newpavlov** [comment]
It was discussed [here](https://github.com/rust-lang-nursery/stdsimd/issues/325#issuecomment-366968146). In short `rdrnd` is name used by LLVM for compatibility with GCC, while `rdrand` is a vendor name. It was decided to use vendor names for `target_feature`, but looks like it didn't get translated to `rustc` options, which I think it should.

**Comment by newpavlov** [comment]
I think it should be closed in favor of #49653?

**Comment by raphaelcohn** [comment]
@newpavlov It seems a sensible place to consolidate it to.

**Comment by raphaelcohn** [comment]
Closing as it's no longer relevant.
