### ISSUE TITLE
rustdoc: provide option to turn intra-link resolution errors into proper errors

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/rust#50082]
When rendering docs for the standard library just now, i noticed some warnings come out of rustdoc. It would be prudent to make these force rustdoc to fail, so they would cause CI to fail. We did something similar during the Markdown transition with a temporary flag, `--deny-rendering-differences`, so i imagine it would work out the same.

**Comment by GuillaumeGomez** [comment]
Or to just add a `deny-warning` option (because more warnings will come!).

**Comment by GuillaumeGomez** [comment]
We have already a huge part merged into rustdoc (we needed it for ui tests). So I think at this point that we could just add the missing parts (which shouldn't be too numerous...).

**Comment by QuietMisdreavus** [comment]
With the warning having been converted to a full lint, could this issue be considered solved? Do we have command-line flags for allow/warn/deny/forbid yet?

**Comment by GuillaumeGomez** [comment]
No we don't. I'll add it as well.
