### ISSUE TITLE
Dropping a large vector of vectors is slow

### ISSUE THREAD

**Issue by rookboom** [rust-lang/rust#50091]
When allocating a large number of vectors, Rust takes a long time to deallocate all the memory when the variables are dropped. 

Below is a program that reproduces the problem:

```
use std::time::{Instant};

fn main() {
    let now = Instant::now();

    println!("Create token ranges"); 
    const NR_ELEMENTS: usize = 1000000;
    
    let mut token_ranges: Vec<Vec<(usize, usize)>> = Vec::with_capacity(NR_ELEMENTS);

    for _ in 0..NR_ELEMENTS {
        token_ranges.push(vec![(7, 7); 1000]); // dummy token ranges. in reality the 1000 is not fixed per document
    }           
    println!(
        "Finished creating token ranges after {} s",
        now.elapsed().as_secs());      

    drop(token_ranges);
    println!(
        "Finished dropping token ranges after {} s",
        now.elapsed().as_secs()); 
}
```

and the console output:

```
A:\temp\slow_exit [master +4 ~0 -0 !]> cargo run --release
   Compiling slow_exit v0.1.0 (file:///A:/temp/slow_exit)
    Finished release [optimized] target(s) in 1.0 secs
     Running `target\release\slow_exit.exe`
Create token ranges
Finished creating token ranges after 8 s
Finished dropping token ranges after 18 s
```

For context, I am trying to do text processing on about 1 million documents. 
Each document contains about 1000 tokens and I am storing the token ranges. 
I allocating a *Vec<Vec<(usize, usize)>>* in memory to store the token ranges for each document. 
*usize* is 64bits (8bytes) so each token range takes 16 bytes.
In total I allocate 16 * 1000 * 1 000 000 bytes just for the tokens. That is 16 GB.
Allocating this much memory takes about 8 seconds.
Dropping the variable adds an additional 10 seconds to free the memory. 

This seems slow? My expectation would be that dropping variables from the heap should be significantly faster than creating them on the heap?

**Comment by ishitatsuyuki** [comment]
This is how the allocator works. free() incurs a synchronization plus potentially a syscall returning the memory to OS. This is different from mark-and-sweep where such operations are just initially selling the pointer (the rest are deferred until the GC runs).

**Comment by Mark-Simulacrum** [comment]
Yes, I'm going to close this as expected behavior.
