### ISSUE TITLE
Raw string literal escape depth is technically limited

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#50111]
This is not entirely serious, because I can't imagine this plausibly happening in real-world code (generated or otherwise), but in Nightly (Stable has a higher threshold):
```rust
fn main() {
    r#[... repeat 2^16 times ...]#""#[... repeat 2^16 times ...]#;
}
```
fails to parse with:
```
error: expected one of `.`, `;`, `?`, `}`, or an operator, found `#`
 --> src/main.rs:3:65544
  |
3 |     r######...
  | 
```

This limit is not mentioned [in the reference](https://doc.rust-lang.org/reference/tokens.html#raw-string-literals).

I think we should document the maximum number of `#`s. We could also reduce the number permitted: 255 should be enough for anyone (https://github.com/rust-lang/rust/pull/49993#issuecomment-381630152).

Alternatively, we could ignore it as being a non-problem. Feel free just to close the issue 😄

**Comment by varkor** [comment]
On the other hand, this should make for a fairly straightforward beginner's contribution to the compiler: adding an error message for too many `#`s (and possibly reducing the maximum to 255).
(And ideally accompanying the change with a corresponding update to [the reference](https://github.com/rust-lang-nursery/reference/).)

If anyone wants to do this to get started, I'm happy to mentor it (assuming it hasn't been closed 😄).

**Comment by cmdd** [comment]
This seems like a nice first issue for a beginner like me to contribute to, so I'd be happy to tackle this one!

**Comment by varkor** [comment]
@cmdd: Great!

There are two places you'll need to modify in the parser for a custom error message:
https://github.com/rust-lang/rust/blob/52ed3d8761dc42e51429eb3bbf56a94d14fdd5c6/src/libsyntax/parse/lexer/mod.rs#L1439-L1446
(Which parses raw string literals.)
And:
https://github.com/rust-lang/rust/blob/52ed3d8761dc42e51429eb3bbf56a94d14fdd5c6/src/libsyntax/parse/lexer/mod.rs#L1669-L1676
(Which parses raw byte string literals.)

For both, `hash_count` can be `u8`, and then you'll want to check the `hash_count` does not exceed the maximum value. If it does, you want to raise an error (`fatal_span_` should work — there are examples in the same file) mentioning the limit.

Then you can lower the hash count field in the tokens themselves:
https://github.com/rust-lang/rust/blob/52ed3d8761dc42e51429eb3bbf56a94d14fdd5c6/src/libsyntax/parse/token.rs#L76-L78
You might need to update some other variables for this to type check (`./x.py check` is helpful here, and https://github.com/rust-lang/rust/commit/4d34bfd00a57f8a8bdb60ec3f908c5d4256f8a9a is a similar commit).

Finally, make a new UI test (in src/test/ui — there are lots of examples there) testing the new error. Let me know if you need any more pointers!

**Comment by eddyb** [comment]
I don't understand why those use `u16`, when `ast::Name` aka `Symbol` is an `u32` - unless the `u16` gets reordered first?

**Comment by varkor** [comment]
@eddyb: I'm not sure about `u32` vs `u16`, but it was recently changed from `usize` to `u16` by [this PR](https://github.com/rust-lang/rust/pull/49993) for space efficiency.

**Comment by eddyb** [comment]
I think https://github.com/rust-lang/rust/pull/49993#issuecomment-381778240 confirms my suspicions. I find it odd though, that @nnethercote relied on field reordering instead of putting the `u16` field first (although that would break more code).

**Comment by nnethercote** [comment]
@varkor: how did you find this -- from code inspection, or fuzzing, or something else?

@eddyb: why is it odd that I relied on field ordering? Is it not reliable?

**Comment by eddyb** [comment]
@nnethercote It was just not immediately obvious why `u32` "followed" by `u16` was useful size-wise, nor is there a comment about the packing being done, in the source.
Also, we have stricter conditions (that I can never remember) for enum field reordering, so if you want to enforce a specific layout, I'd suggest `#[repr(u16)]` (or `u8`) and placing the `u16`s first.

Also note that there are other limitations in the compiler, although most of them are `u32` aka 4Gi.

**Comment by varkor** [comment]
@nnethercote: I think I saw your PR and noticed that the limit was (slightly) more reachable.

@eddyb: yeah, that's not surprising. I decided to report as in the vein of https://github.com/rust-lang/rust/issues/40161 (in which the examples are also often unrealistic), but it's probably sensible just to ignore these in general.

**Comment by steveklabnik** [comment]
Removing T-doc; this is basically an "implementation defined" kind of thing, and if we were to guarantee any length here, that would go on the reference. Leaving the issue open because it's tracking the diagnostic aspect.
