### ISSUE TITLE
RUST_BACKTRACE does not work anymore?

### ISSUE THREAD

**Issue by pravic** [rust-lang/rust#50138]
I have noticed a backtrace absence on Windows for a while. Stable/Nightly - all the same.

Checked on:

stable-i686-pc-windows-msvc
stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc

update 1: `1.24.1` works fine. How come?
update 2: `CARGO_INCREMENTAL=0` has no effect on it.

Linux binaries work as expected, with respect of `0`, `1`, `full` values of the `RUST_BACKTRACE`. 

Windows binaries print exactly the same output regardless of environment variable (excluding note):

`RUST_BACKTRACE=0`:

> Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
 Running `target\debug\stacktrace.exe`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore\option.rs:335:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: process didn't exit successfully: `target\debug\stacktrace.exe` (exit code: 101)

`RUST_BACKTRACE=1`:

> Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
 Running `target\debug\stacktrace.exe`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore\option.rs:335:21
error: process didn't exit successfully: `target\debug\stacktrace.exe` (exit code: 101)

<details>
  <summary>Dummy code to reproduce</summary>

```rust
fn bar() {
  let some: Option<bool> = None;
  some.unwrap();
}

fn foo() {
  bar();
}

fn main() {
  foo(); foo();
}
```
</details>

**Comment by pravic** [comment]
Interesting. I found at least 2 tests regarding to `RUST_BACKTRACE`: 

https://github.com/rust-lang/rust/blob/master/src/test/run-pass/backtrace.rs
https://github.com/rust-lang/rust/blob/master/src/test/run-pass/backtrace-debuginfo.rs

They are not run on Windows?

**Comment by dylanede** [comment]
I'm also experiencing this.

**Comment by pravic** [comment]
Probably #47252 is a culprit. 

@alexcrichton I am not sure which team could look on this.

**Comment by pravic** [comment]
Well, sure:

[StackWalkEx](https://msdn.microsoft.com/en-us/library/windows/desktop/dn280332(v=vs.85).aspx) was introduced in [DbgHelp.dll 6.2](https://msdn.microsoft.com/en-us/library/windows/desktop/ms679294(v=vs.85).aspx).

Windows 7 SP1 has dbghelp 6.1.7601 by default. And it is not updated by VS / Tools / Debuggers / whatever.

So yes, this bug was introduced in #47252. And tests could not catch it, probably, because they are run on Windows 10 or something.

**Comment by pravic** [comment]
What was a point to use `StackWalkEx` over `StackWalk64`, since the former is different only by an additional flag and it [is not used](https://github.com/rust-lang/rust/pull/47252/files#diff-a8572a8a4ebb2d2608b89cdde342f3c4R91) anyway?

**Comment by pravic** [comment]
cc @Zoxc as the author of the change :hand:

**Comment by retep998** [comment]
So clearly the solution is to add the old `StackWalk64` code back but as a fallback in case `StackWalkEx` cannot be loaded.
