### ISSUE TITLE
println! panics when piped into something that closes stdin early

### ISSUE THREAD

**Issue by P-E-Meunier** [rust-lang/rust#50142]
After code using `println!` starts working, I don't think rustaceans should have to rewrite their code using finer error control.

`println!("Hello, world")` should not cause a panic when piped into anything. I believe the default behaviour should be to ignore errors, people wanting finer error control can still `writeln!` to stdout.

**Comment by varkor** [comment]
I think the panicking behaviour is undesirable too, but if it's something you want control over now, you can use [the `try_print` crate](https://crates.io/crates/try_print), which should do what you want.

**Comment by sfackler** [comment]
Duplicate of #46016.

**Comment by P-E-Meunier** [comment]
@sfackler: thanks! I couldn't find it, sorry for the noise.
