### ISSUE TITLE
Spurious LNK1104 error on `x86_64-msvc` in `nll` revision on run-pass tests

### ISSUE THREAD

**Issue by kennytm** [rust-lang/rust#50140]
Symptom: A run-pass test, or a UI test with a `// run-pass` header failed due to linker error LNK1104. The error message looks like `cannot open file C:\projects\**\*.stage2-x86_64-pc-windows-msvc.exe`. Interestingly, it only affects tests in the `nll` revision, if any.

Known instances:

* https://github.com/rust-lang/rust/pull/49939#issuecomment-381319518
* https://github.com/rust-lang/rust/pull/50076#issuecomment-383216387

**Comment by Enselic** [comment]
Triage: Has this been seen recently? If not I think we can close this issue as obsolete since it now is 5 years old.

**Comment by ChrisDenton** [comment]
I don't recall ever seeing it locally. And, yeah, I'd  agree that no comments in 5 years suggests it hasn't been happening in CI.

**Comment by kennytm** [comment]
Let's reopen if this actually happens again.
