### ISSUE TITLE
std::sync::Weak::strong_count

### ISSUE THREAD

**Issue by SoniEx2** [rust-lang/rust#50158]
I'd like to test if a `Weak` is done for without potentially incrementing an atomic refcount, because doing so is slow.

I want a faster alternative to `Weak.upgrade().is_some()`.

also currently have this in my code: https://play.rust-lang.org/?gist=339c2c518a2d42aee7e5a585133427eb&version=stable

```rust
// since Weaks are completely useless...
// this checks if the arc and weak point to the same value without attempting to upgrade the weak.
// this is "safer" than trying to get the strong count
fn compare_arc_weak<T>(arc: &Arc<T>, weak: &Weak<T>) -> bool {
    unsafe {
        // we assume arc and weak have same size and alignment as usize
        let arcusize: usize = mem::transmute_copy(arc);
        let weakusize: usize = mem::transmute_copy(weak);
        arcusize == weakusize
    }
}
```

**Comment by ishitatsuyuki** [comment]
Relying on such count is racy. You have to upgrade to ensure thread safety.

**Comment by SoniEx2** [comment]
You absolutely do not.

If the strong count is 0(?), then the weak is done for, and upgrade is always gonna be None.

**Comment by SoniEx2** [comment]
You can't get the strong count back up once it reaches 0. That's the whole point of Arc/Weak! Because once it's 0, it's dropped.

Unless you're saying there's a race condition in which you can turn a Weak into an uninitialized/dropped Arc!?

**Comment by ishitatsuyuki** [comment]
Well, that particular thing is correct.

However, with regards to this issue,

1. Obtaining the count directly encourage racy behaviour
2. The motivation is not clear.

**Comment by oli-obk** [comment]
Do you have an example of using the comparison? I'm curious about the use case

**Comment by Lymia** [comment]
https://github.com/rust-lang/rust/blob/e02868793bdb0e83d2ecee295bdc16f6b2e5a142/src/liballoc/rc.rs#L1228-L1237

This function is factually unnecessary for this use case.

**Comment by SoniEx2** [comment]
You're looking at the wrong Weak. Check the arc Weak, it's more expensive.

**Comment by RalfJung** [comment]
The question still stands: When do you ever think it is useful to know that, at some point in the past, the Weak was (not) valid? This is the best you can get.
It is true that once the Weak is invalid, it will stay invalid, but how is that useful information?

**Comment by SoniEx2** [comment]
I have no idea what exactly I was using it for, but I just want to be able to use "stupid" optimizations like compare Arc and Weak (which doesn't need to be an atomic operation) to avoid an atomic operation/refcount/optimize for inequality.

I think the usual use-case would involve checking if they're (not) the same and upgrading/cloning as needed.

(I feel like this might have something to do with an eventbus thing I was working on but idk)
