### ISSUE TITLE
Implement & use metadata on arguments in LLVM

### ISSUE THREAD

**Issue by hanna-kruppe** [rust-lang/rust#50156]
We use *metadata* attached to LLVM instructions to tell LLVM passes about the range of possible integers that a value can take on. This allows additional optimizations. For example, when loading from a `&NonZeroU32`, the LLVM IR looks like this:

```llvm
  %2 = load i32, i32* %1, align 4, !range !33
```

where `!33` refers to a module-level entry like this (usually located near the end of the module source code):

```llvm
!33 = !{i32 1, i32 0}
```

This tells LLVM that it's UB if the load returns anything that is not in the range ">= 1, < 0" (with wrap-around, i.e. it includes all values except 0). This allows `x.get() != 0` (where `x: &NonZeroU32`) to be optimized to `true`, for example.

Unfortunately LLVM does not have a way to attach this information to function arguments, which leads to missed optimizations (e.g. #49572, https://github.com/rust-lang/rust/pull/49420#issuecomment-376805721). Adding this capability has been [discussed before on llvm-dev](https://lists.llvm.org/pipermail/llvm-dev/2015-July/087923.html) and received positively, but was never actually implemented. If we want to use this in Rust, we're likely going to have to implement (& upstream) it outselves.

This issue tracks:

- [ ] Implementing metadata-on-arguments in LLVM ([mentoring instructions](https://github.com/rust-lang/rust/issues/50156#issuecomment-383389073))
- [ ] Upstreaming / backporting that LLVM patch
- [ ] Emitting range metadata on arguments from rustc

cc @nox @eddyb

**Comment by nox** [comment]
Nice! Thanks for filing this and being willing to mentor its implementation.

**Comment by rkruppe** [comment]
cc #50157 which is much easier but strongly related and complementary.

**Comment by nox** [comment]
@rkruppe Should the `Function` have a new `MDAttachmentMap *` field and handle memory allocation of the array itself, or should that go in a separate type?

**Comment by rkruppe** [comment]
I think in analogy with `Function::Arguments` it's fine to open-code that in `Function`.

**Comment by eddyb** [comment]
Would this change mean that attributes like `nonnull` would get replaced with metadata?
Actually, don't we *have* to use `!nonnull` for pointers and `!range` for integers?
So `nonnull` would become `!nonnull` (how? this should be backwards-compatible).

**Comment by rkruppe** [comment]
Yes, I believe this would obsolete some attributes on formal parameters. For argument values at specific call sites you'd still use attributes, but I don't think callsite annotations are useful for `nonnull` specifically. So yeah, `nonnull` probably becomes obsolete with this change.
