### ISSUE TITLE
Emit LLVM range metadata for call instructions

### ISSUE THREAD

**Issue by rkruppe** [rust-lang/rust#50157]
Adding `!range` to a call instruction to communicate the possible range of the return value (analogous to `!range` on loads) already works in LLVM today, we just need to use it. Fixes the test case in #49572 and we already have the information anyway, so it's a cheap and easy win. cc @eddyb

**Comment by nox** [comment]
I'll try to implement that.

**Comment by rkruppe** [comment]
@nox noticed that this can't actually help with `NonZeroU32::get` (#49572) because the return type there is plain old `u32` 🤦‍♂️ But it still helps functions that return fieldless enums, or more generally enums that get packed into a single scalar (but not scalar pairs).
