### ISSUE TITLE
implement "dynamic drop" semantics using flags on the stack rather than zeroing

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#5016]
(Tracking issue for [RFC 320](https://github.com/rust-lang/rfcs/pull/320).)

Original Description
----

The current liveness check has a concept of "alive" and "maybe dead", so I'll just describe this in terms of a hypothetical "move optimization pass" (although liveness can probably be extended with "surely dead").

### Hypothetical move optimization pass:

In each scope where they exist, all variables are given an associated boolean representing whether they were *certainly* moved from. Moving from a variable in a scope marks it as such for that scope. This can be bubbled up if and only if the variable is also moved from in every other branch.

If the compiler can bubble this up to the scope where the variable is declared, the drop glue can be omitted and all moves from that variable do not need to zero it.

This can probably be extended to fields too, but I'm not sure on what the semantics would be.

@nikomatsakis: does this look like something that would be reasonable to implement (probably as part of liveness)? It doesn't actually need to bubble it up to be useful - even if it only worked in a local scope, it would allow the destructor of the `save` variable in the TreeMap `split` and `skew` functions to be omitted (since it's moved from in the same scope where it's declared) and that would be a big performance win.

**Comment by pnkfelix** [comment]
cc https://github.com/rust-lang/rfcs/pull/320

**Comment by pnkfelix** [comment]
P-high, not 1.0 (but one can always hope!)

**Comment by dotdash** [comment]
Unless someone is already working on this, I'd like to give it a shot this weekend.

**Comment by pnkfelix** [comment]
@dotdash I do not think this is a mere weekend project.  Have you read the discussion on e.g. [RFC 320](https://github.com/rust-lang/rfcs/pull/320) ?

**Comment by dotdash** [comment]
@pnkfelix Oh, I don't expect to finish it over the weekend, but rather see if it's something that I could reasonably fit into my schedule at all. I hope to get _that_ part done over the weekend.

**Comment by pnkfelix** [comment]
For those interested, I have put up an internalspost describing some short term future proofing efforts, here:

  http://internals.rust-lang.org/t/attention-hackers-filling-drop/1715

**Comment by bluss** [comment]
Linking relevant PR: Replace zeroing-on-drop with filling-on-drop #23535

**Comment by Ticki** [comment]
What's the state of this?

**Comment by huonw** [comment]
I believe it is waiting for the MIR work in the compiler to shape up some more.

**Comment by wacossusca34** [comment]
Programmers should be able to mutate structure memory without possibly interfering with drop flags -- for a 'systems programming language', the current implementation does not make sense, nor is it very efficient.

Along with a few other people, I'm eager to use Rust -- but problems like this make the language less appealing.

**Comment by aldanor** [comment]
This issue is over three years old now and is still indeed is a pretty major pain when wrapping C libraries, effectively disallowing zero-copy conversions in a lot of cases and forcing one to jump through multiple ugly hoops.

**Comment by pnkfelix** [comment]
As noted by @huonw above, at this point the compiler team considers this work to be dependent on MIR. The compiler team has made some baby steps forward on dynamic drop flags, but it is not the highest priority item right now. (Examples of things of higher priority: MIR itself; incremental compilation.)

The real point is that I don't want the age of this issue to be interpreted as meaning that the Rust leam isn't ever going to do this. We have every intention of doing it. I feel silly even having to write that down, but I worry that if no one says anything, then people are going to get an incorrect impression from the comment history here.

**Comment by aldanor** [comment]
@pnkfelix Thanks for clarifying! Didn't mean to sound any negative, mostly just wondering if it's wise for library developers to assume this will land in some (finite) time and make their choices accordingly :)

**Comment by nikomatsakis** [comment]
I expect it to land this year.

**Comment by ticki** [comment]
:tada:

**Comment by sorear** [comment]
I have some code that spends a measurable amount of time checking for drop flags (there's an inner loop which drops an `Option<Box<...>>` which is virtually always `None`), and so I'm kind of wondering if we have a ticket for the other side of this, where we delete POST_DROP_U8 and stop generating code in drop methods to check for it.  Do we have a tracking ticket for that?

Incidentally, this ticket is currently the tracking issue for [the POST_DROP_U8 constant](https://doc.rust-lang.org/nightly/std/mem/constant.POST_DROP_U8.html); maybe that should be repointed now that this ticket is closed?
