### ISSUE TITLE
Soundness Hole: Aliasing and Mutating static references in safe Rust

### ISSUE THREAD

**Issue by CryZe** [rust-lang/rust#50162]
```rust
fn static_val() -> &'static mut u8 {
    let ref mut x = 0;
    x
}

fn main() {
    let ref1 = static_val();
    let ref2 = static_val();
    *ref1 = 20;
    *ref2 = 32;
    println!("{}", ref1);
}
```

The variable x is a mutable reference to a u8 that is promoted to a &'static mut u8. By calling that function multiple times, you can alias the mutable reference in safe Rust.

**Comment by memoryruins** [comment]
```rust
fn static_table() -> &'static mut [u8; 20] {
    let ref mut table = [0; 20];
    table
}

fn main() {
    let table = static_table();
    table[4] = 20;
    println!("{:?}", table);
}
```

The above returns different arrays of values depending on stable, beta, or release channel. Only in debug does ``table[4] = 20;`` set the index's value to 20.

**Comment by memoryruins** [comment]
Neither examples compile before 1.21.0.

**Comment by jonas-schievink** [comment]
looks like https://github.com/rust-lang/rust/issues/46557

**Comment by memoryruins** [comment]
It appears so. Enabling nll prevents it from compiling.

**Comment by CryZe** [comment]
Closing as it seems to be a duplicate
