### ISSUE TITLE
Sharing a variable on stack between threads

### ISSUE THREAD

**Issue by StrausMG** [rust-lang/rust#50165]
Hi! The problem can be easily observed in these questions:

1. https://stackoverflow.com/questions/49968530/is-using-an-arc-really-the-best-way-to-implement-a-counter-shared-between-thread

2. https://stackoverflow.com/questions/32750829/how-can-i-pass-a-reference-to-a-stack-variable-to-a-thread

I can't believe that Arc is the best that Rust can offer to achieve what the topic says. It's inconvenient, it's slow (Rust claims to have zero-cost abstractions, right?).

I'm not an expert, but I suppose, that the standard library lacks some primitives for solving such problems. Or there are some fundamental problems (I hope not).

**Comment by sfackler** [comment]
> it's slow (Rust claims to have zero-cost abstractions, right?).

Could you show some of the profiling you've done to establish that Arc reference counting is a limiting factor in the performance of what you're working on?

The second question you linked shows how to avoid using Arc to shared a variable between threads.

**Comment by StrausMG** [comment]
@sfackler well, I'm not working on any particular project. Alright, besides performance: the answer you've mentioned suggests two crates, both of which are not actively maintained. Anyway, got your point.
