### ISSUE TITLE
ICE (beta 2018-04-19) in cache: `thread 'rustc' panicked at 'index out of bounds: the len is 32457 but the index is 32459', /checkout/src/libcore/slice/mod.rs:871:14`

### ISSUE THREAD

**Issue by Ekleog** [rust-lang/rust#50169]
First, the backtrace:
```
thread 'rustc' panicked at 'index out of bounds: the len is 32457 but the index is 32459', /checkout/src/libcore/slice/mod.rs:871:14
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: core::ops::function::Fn::call
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::panicking::panic_bounds_check
  10: rustc::dep_graph::graph::DepGraph::with_task_impl
  11: rustc_errors::Handler::track_diagnostics
  12: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::cycle_check
  13: rustc::ty::maps::<impl rustc::ty::maps::queries::output_filenames<'tcx>>::force
  14: rustc::ty::maps::<impl rustc::ty::maps::queries::output_filenames<'tcx>>::try_get
  15: rustc::ty::maps::TyCtxtAt::output_filenames
  16: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::output_filenames
  17: rustc_trans::back::write::start_async_translation
  18: rustc_trans::base::trans_crate
  19: <rustc_trans::LlvmTransCrate as rustc_trans_utils::trans_crate::TransCrate>::trans_crate
  20: rustc::util::common::time
  21: rustc_driver::driver::phase_4_translate_to_llvm
  22: rustc_driver::driver::compile_input::{{closure}}
  23: <std::thread::local::LocalKey<T>>::with
  24: <std::thread::local::LocalKey<T>>::with
  25: rustc::ty::context::TyCtxt::create_and_enter
  26: rustc_driver::driver::compile_input
  27: rustc_driver::run_compiler_impl
  28: syntax::with_globals
```

The issue can be replicated by downloading [this archive](https://ekleog.org/rust-dump/VGSGp1Ui40r0gg3Vkx4Qsg.tgz), unpacking it in an empty directory, and running `cargo build` with rustc 1.26.0-beta.7 (842323097 2018-04-19). It reproduces only with this specific target directory, though it should continue to reproduce if you build several times.

If somehow you can't replicate the issue, you can install nix, run `nix-shell --pure shell.nix` with [this shell.nix](https://github.com/Ekleog/yuubind/blob/e824ec587bd7a49fa5d8f5cca5b90d3059c10e30/shell.nix), and inside this (really limited, as it contains basically only bash and cargo/rustc) shell run `cargo build`, this should place you in exactly the same build environment as mine. :)

**Comment by pietroalbini** [comment]
Uh, that's weird. Can't reproduce without the target directory, but with the target directory and that exact release (`beta-2018-04-20`) it does indeed crash. I can't reproduce with other releases though, because the target directory gets rebuilt. I'll try installing nix.

Marking as a regression from stable to beta just to be safe.

**Comment by pietroalbini** [comment]
Nope, can't reproduce this inside of the nix environment you provided. If you delete/move the target directory, does the ICE still happen?

**Comment by Ekleog** [comment]
No, it only crashes with the given target directory, I'd guess that's because it somehow became corrupted during the subsequent builds (my workaround has been to just rm it), sorry if it was unclear!

BTW, I've trimmed down the target directory, keeping only the `target/debug/incremental` subfolder, before pushing it online; I guess the bug lies in incremental rebuilds.

**Comment by Centril** [comment]
@Ekleog Can you still reproduce this?

**Comment by Ekleog** [comment]
I can no longer with the provided archive, though I do not know whether it is due to the bug being fixed or just to the cargo bump making cargo no longer use the corrupted incremental build directory.

Anyway, I guess this is fine to close :)
