### ISSUE TITLE
Rerast incremental compilation - already existing DepNode error

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rust#50178]
https://github.com/google/rerast/issues/17#issuecomment-383504608

[Rerast](https://github.com/google/rerast) (version 4928293ed19d3a3a8e5fd70aedd63a4526cdda79, because later commit disabled incremental compilation) panics:

<pre>
thread 'main' panicked at 'Forcing query with already existing DepNode.

query-key: ParamEnvAnd { param_env: ParamEnv { caller_bounds: Slice([]), reveal: UserFacing }, value: unsafe extern "rust-intrinsic" fn(*const std::os::raw::c_void) -> extern "system" fn(u32, i32, *mut i32) {std::intrinsics::transmute::<*const std::os::raw::c_void, extern "system" fn(u32, i32, *mut i32)>} }
dep-node: IsCopy(7cbec90d2168a3bd-88dbb5e68c554118)', librustc/ty/maps/mod.rs:97:1
stack backtrace:
[…] at libstd/panicking.rs:347
7: rustc::ty::maps::<impl rustc::ty::maps::queries::is_copy_raw<'tcx>>::force_with_lock
8: rustc::ty::maps::<impl rustc::ty::maps::queries::is_copy_raw<'tcx>>::try_get
9: rustc::ty::maps::TyCtxtAt::is_copy_raw
10: rustc::middle::mem_categorization::MemCategorizationContext::type_moves_by_default
11: rustc::middle::expr_use_visitor::ExprUseVisitor::consume_expr
12: rustc::middle::expr_use_visitor::ExprUseVisitor::walk_expr
13: rustc::middle::expr_use_visitor::ExprUseVisitor::walk_expr
14: rustc::middle::expr_use_visitor::ExprUseVisitor::walk_expr
15: <rustc_passes::rvalue_promotion::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_nested_body
16: rustc_passes::rvalue_promotion::rvalue_promotable_map
17: rustc::dep_graph::graph::DepGraph::with_task_impl
18: rustc::ty::context::tls::with_related_context
19: rustc::ty::maps::<impl rustc::ty::maps::queries::rvalue_promotable_map<'tcx>>::force_with_lock
20: rustc::ty::maps::<impl rustc::ty::maps::queries::rvalue_promotable_map<'tcx>>::try_get
21: rustc::ty::maps::TyCtxtAt::rvalue_promotable_map
22: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::rvalue_promotable_map
23: rustc_passes::rvalue_promotion::const_is_rvalue_promotable_to_static
24: rustc::dep_graph::graph::DepGraph::with_task_impl
25: rustc::ty::context::tls::with_related_context
26: rustc::ty::maps::<impl rustc::ty::maps::queries::const_is_rvalue_promotable_to_static<'tcx>>::force_with_lock
27: rustc::ty::maps::<impl rustc::ty::maps::queries::const_is_rvalue_promotable_to_static<'tcx>>::try_get
28: rustc::ty::maps::TyCtxtAt::const_is_rvalue_promotable_to_static
29: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::const_is_rvalue_promotable_to_static
30: rustc_passes::rvalue_promotion::check_crate
31: rustc::ty::context::tls::enter_context
32: std::thread::local::LocalKey::with
33: rustc::ty::context::TyCtxt::create_and_enter
34: rustc_driver::driver::compile_input
35: rustc_driver::run_compiler_impl
36: syntax::with_globals
37: rustc_driver::run_compiler
</pre> 

To reproduce:

```sh
cargo +nightly install --force --git https://github.com/google/rerast.git --rev 4928293ed19d3a3a8e5fd70aedd63a4526cdda79
git clone https://github.com/tomaka/glutin; 
cd glutin
git checkout a5a51e3ddcfd2677e757d89bb63d750b99fab7fc
```

make file `rule.rs` with:

```rust
fn rule1<T,E,X: From<E>>(r: Result<T,E>) -> Result<T,X> {
    replace!(try!(r) => r?);
    unreachable!()
}
```

run

```sh
cargo +nightly rerast --rules_file=rule.rs --force --verbose
```

**Comment by michaelwoerister** [comment]
Thanks for the detailed instructions! Unfortunatly (or fortunately?) I was not able to reproduce this with the latest nightly. Would you mind giving it another try?

**Comment by kornelski** [comment]
I can't reproduce it either.
