### ISSUE TITLE
rustc takes more memory to finish release compilation

### ISSUE THREAD

**Issue by BusyJay** [rust-lang/rust#50199]
Since `rustc 1.25.0-nightly (bacb5c58d 2018-01-26)`, it takes more memory to finish compilation in release mode. On my dev machine, which has 16GB memory, building pingcap/tikv in release mode often fails with OOM.
```
Out of memory: Kill process 12260 (rustc) score 212 or sacrifice child
Killed process 12260 (rustc) total-vm:4881248kB, anon-rss:3458380kB, file-rss:0kB, shmem-rss:0kB

error: Could not compile `tikv`.
warning: build failed, waiting for other jobs to finish...
```
There will be four rustc processes in the final step, and each of them will acquire 2GB+ memory. Hence finally out of memory.

**Comment by pietroalbini** [comment]
Have you tried tweaking the number of codegen units?

**Comment by Hoverbear** [comment]
I can confirm this on `rustc 1.27.0-nightly (ac3c2288f 2018-04-18)` running on Linux x86_84. I was seeing the processes take 3.4+GB.

**Comment by ishitatsuyuki** [comment]
Can you try different `opt-level` and check how the situation changes?

**Comment by alexcrichton** [comment]
Is this a project that compiles with stable? If so is there something we can check out and profile locally to try to bisect a regression to?

**Comment by BusyJay** [comment]
@alexcrichton No, it only compiles with nightly for now. I can verified that the issue has been exists since rustc 1.25.0-nightly (bacb5c58d 2018-01-26).

**Comment by BusyJay** [comment]
@ishitatsuyuki change `opt-level` from 3 to 2, 1 and 0 change nothing.

**Comment by Enselic** [comment]
Triage: Is this still a problem? Wanted to check since 5 years have passed and circumstances might have changed.

**Comment by Mark-Simulacrum** [comment]
I'm going to close as a nightly only reproducer that's quite old is not really practical for investigation at this point.
