### ISSUE TITLE
Support LibreSSL 2.7.2 in HardenedBSD 12-CURRENT/amd64

### ISSUE THREAD

**Issue by lattera** [rust-lang/rust#50190]
@sp1l updated LibreSSL in HardenedBSD 12-CURRENT to 2.7.2. It appears Rust uses a whitelist for crypto libraries that are known to work properly with Rust. Can LibreSSL 2.7.2 be added to the whitelist? I've never seen even a single line of Rust code, so I don't know what it would take to support LibreSSL 2.7.2 in Rust's codebase.

With Rust not supporting LibreSSL 2.7.2, firefox fails to build since firefox now depends on rust.

**Comment by lattera** [comment]
Relevant portion of the build log:

```
This crate is only compatible with OpenSSL 1.0.1, 1.0.2, and 1.1.0, or LibreSSL
2.5 and 2.6.0, but a different version of OpenSSL was found. The build is now
aborting due to this version mismatch.

', vendor/openssl-sys/build.rs:486:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I grepped for that error message in Rust's source tree and couldn't find it.

**Comment by lattera** [comment]
It looks like this is what I need: https://github.com/sfackler/rust-openssl/issues/883

**Comment by pietroalbini** [comment]
Thank you for reporting this! The `openssl` crate is a third-party crate, not maintained by the Rust developers. Also, seems like the crate author already fixed the issue in the latest release `;)`

Closing this issue.
