### ISSUE TITLE
NLL not sufficiently precise with loops?

### ISSUE THREAD

**Issue by Ekleog** [rust-lang/rust#50201]
I think the following code should compile with NLL enabled, but it doesn't:
```rust
fn foo() -> Vec<u8> {
    let mut v = vec![b'h', b'e', b'l'];
    for &c in v.iter() {
        if c == b'e' {
            return v
        }
    }
    Vec::new()
}
```
[(playground link)](https://play.rust-lang.org/?gist=3239b64b81fed269753b2e91bfb7a33c&version=nightly)

Indeed, it could drop the borrow just before the `return`.

Or maybe the current implementation of NLL only takes into account `match` and the like, and not yet loops? (the same appears to happen with trying to work around this with `loop { match iter.next() { ... } }`)

**Comment by Ekleog** [comment]
cc #43234

**Comment by matthewjasper** [comment]
Features are inner attributes, you need #**!**[feature(nll)].

**Comment by Ekleog** [comment]
Oh. Stupid me, I was sure I had put it correctly. Sorry for the noise!
