### ISSUE TITLE
Run tidy from x.py / bootstrap

### ISSUE THREAD

**Issue by Phlosioneer** [rust-lang/rust#50209]
Currently, we can run `.\x.py check` as a quick sanity check before uploading a PR. However, it doesn't run `tidy`. I'd like a command to do e.g. `.\x.py tidy`, or `.\x.py check --tidy` or something similar.

I'd implement this myself (and I tried poking around in the code) but I can't quite figure out how to invoke `tidy`.

**Comment by varkor** [comment]
If you're just looking for a way to invoke `tidy` on its own, you can run `./x.py test tidy`.

If you wanted to invoke `tidy` from `check`, you would want to copy some of the code from `src/bootstrap/test.rs` to `src/bootstrap/check.rs` regarding the `Tidy` struct, though I'm not sure whether this is something we want to combine or not (they arguably serve different purposes, but they're also used as part of the same workflow).

**Comment by Mark-Simulacrum** [comment]
We wouldn't want tidy inside check -- they serve different purposes. I'm going to close this as running `./x.py test src/tools/tidy` shouldn't be too difficult for the time being.

**Comment by Phlosioneer** [comment]
Ah cool, I didn't know we could run it like that. Thanks!
