### ISSUE TITLE
Tracking Issue: Duration::{as_nanos, as_micros, as_millis}

### ISSUE THREAD

**Issue by fintelia** [rust-lang/rust#50202]
Duration has historically lacked a way to get the actual number of nanoseconds it contained as a normal Rust type because u64 was of insufficient range, and f64 of insufficient precision. The u128 type solves both issues, so I propose adding an as_nanos function to expose the capability.

CC: #50167

**Comment by gbutler69** [comment]
I still don't understand by Duration is not allowed to be negative. It bugs me that the SystemTime difference returns a Result<Duration,Error> and returns and error if the time from is after the time to. To me, it should just return a negative Duration (Yes, the System Clock can go backwards). I find it odd that Duration does not support a negative amount.

**Comment by lnicola** [comment]
@gbutler69 I think it's about the way you think of `Duration`. If it's a span of time (like described in the documentation) or an interval, then it must be positive. If it's the distance between two time points, it's negative.

You're probably thinking of a distance instead of an interval. That's not necessarily a bad thing, but it's different from what the type is today, and it will never change due to compatibility concerns.

**Comment by gbutler69** [comment]
> If it's a span of time (like described in the documentation) or an interval, then it must be positive. If it's the distance between two time points, it's negative.

Here is what I take issue with:

```
let t1 = std:time:SystemTime.now();
// ....long running computation happening...
// System Clock Time changed back 5 hours (because it was wrong to begin with) outside the program
// ....long running computation completed...
let t2 = std:time:SystemTime.now();

let clock_time_between_events = t2.duration_since( t1 ); // returns an error instead of negative duration, so I must do...
let ( clock_time_between_events, neg_duration ) = match ( clock_time_between_events ) {
    Some(duration) => ( duration, false )
    _ => ( t1.duration_since( t2 ).unwrap(), true )
}
```

And....DING! DING! DING! .... But, you know what, now that I've typed out that code, I can't think of any justifiable reason I would actually want that, so, once again, the thoughtfulness of Rust shows itself. You and the designers of Duration were correct. Negative Duration doesn't make sense (even though it feels like it should).

**Comment by lnicola** [comment]
You can use https://doc.rust-lang.org/std/time/struct.Instant.html if you want to measure a duration.

**Comment by gbutler69** [comment]
> You can use https://doc.rust-lang.org/std/time/struct.Instant.html if you want to measure a duration.

Yes, I'm aware. I guess I think there should be another thing called TimeDifference (that can be neg/pos) and there should be methods on SystemTime that don't return Result<Duration,Error>, but, instead return TimeDifference. It could be as simple as:

```rust
struct TimeDifference {
   duration : Duration,
   is_negative : bool
}
```

**Comment by lnicola** [comment]
It can, but the return type of `duration_since` will never change, so it's up to you (or a crate) to implement that.

**Comment by fintelia** [comment]
@gbutler69 @lnicola This is the tracking issue for a feature that adds several specific methods to Duration, not a place to debate general concerns about the Duration type. Your discussion is probably better suited for the internals.rust-lang.org site.

**Comment by NatTuck** [comment]
Why can't as_millis return an i64?

**Comment by sfackler** [comment]
@NatTuck large durations won't fit into that type.

**Comment by fintelia** [comment]
@sfackler is there any reason not to move forward with stabilization on this? @rivertam correctly observes that it has been unstable for quite a while

**Comment by sfackler** [comment]
The stability of u128 was the blocker previously, but that's now no longer a problem.

@rfcbot fcp merge

**Comment by SimonSapin** [comment]
I couldn’t find all the details in this issue, grepping through the code shows that this tracking issue is for:

```rust
    pub fn as_millis(&self) -> u128 {…}
    pub fn as_micros(&self) -> u128 {…}
    pub fn as_nanos(&self) -> u128 {…}
```

**Comment by lnicola** [comment]
This may be a stupid question, but is `u128` available on all platforms that Rust supports?

**Comment by sfackler** [comment]
@lnicola Yep, it should be available on all platforms.

**Comment by sunjay** [comment]
Now that final comment period has ended, can these methods be stablized?

**Comment by SimonSapin** [comment]
Yes, the next step is a stabilization PR.
