### ISSUE TITLE
It would be nice if when RustDoc search finds only one result it goes there

### ISSUE THREAD

**Issue by gilescope** [rust-lang/rust#50216]
As a dev, 
it would be great if when I pasted in a type e.g. 'AngleBracketedGenericArguments' that returned exactly one result, 
then the rust doc website would go straight to the single result (E.g. https://docs.rs/syn/0.13.1/syn/struct.AngleBracketedGenericArguments.html )
rather than showing me a found list of one item (E.g.
https://docs.rs/syn/0.13.1/syn/struct.AngleBracketedGenericArguments.html?search=AngleBracketedGenericArguments )

(Loving the in-built search functionality btw! <3 )

(A-rustdoc, C-enhancement, T-dev-tools-rustdoc)

**Comment by Ixrec** [comment]
Personally, I wouldn't want opening a search link with only one result to auto-redirect, but I _would_ like pressing Enter in the search bar for a search with one result to auto-redirect. Is that a good enough compromise to avoid the need for a setting, or is that also controversial?

**Comment by gilescope** [comment]
Works for me. I have too many settings in my life already...

**Comment by GuillaumeGomez** [comment]
@Ixrec: Then press enter twice and you'll have the first result I suppose. I don't want to change the current behaviour. You have a search, you get results. There is only one result and you want to go to it without seeing the results page? Set your setting to such behaviour.
