### ISSUE TITLE
Impls of TryFrom

### ISSUE THREAD

**Issue by Kixunil** [rust-lang/rust#50212]
Here are some impls if `TryFrom` that I'd like to see. I checked against the [documentation](https://doc.rust-lang.org/std/convert/trait.TryFrom.html), not current git master. I'm sorry, if some are already resolved.

- [ ] `TryFrom<&str> for numeric types` (parsing)
- [ ] `TryFrom<String> for numeric types` (the benefit of this is that if you generically bound by `TryFrom<String>`, you may save allocation in case of `TryFrom<String> for String`
- [ ] `TryFrom<OsStr> for numeric types` (useful for parsing args_os or env_os)
- [ ]  `TryFrom<OsString> for numeric types`
- [ ] all above combinations for IP addresses
- [ ] probably many more I don't remember right now

**Comment by SimonSapin** [comment]
I was wondering whether these could be based on `FromStr`, but unfortunately trait coherence doesn’t allow it:

```rust
error[E0119]: conflicting implementations of trait `convert::TryFrom<&str>`:
   --> libcore/convert.rs:430:1
    |
421 | impl<T, U> TryFrom<U> for T where T: From<U> {
    | -------------------------------------------- first implementation here
...
430 | impl<'a, T> TryFrom<&'a str> for T where T: ::str::FromStr {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation

error: aborting due to previous error
```

Maybe something something specialization something.

**Comment by Kixunil** [comment]
Yeah, I specifically listed them separately. I know that `TryFrom` was previously implemented in terms of `FromStr` but that was later changed.

**Comment by Mark-Simulacrum** [comment]
I am personally against seeing the parsing functions implemented via TryFrom, parsing seems like too specific a desire to be met with such a generic trait as TryFrom.

I think refiling this as specific issues for each impl (or at least, group of impls) is then the right way to move forward here, though I'd personally be against all the impls suggested here. Closing in favor of specific issues (which can then be decided on individually).

**Comment by Kixunil** [comment]
While I don't see the reason (`FromStr` was previously supposed to be deprecated in favor of `TryFrom`!), I don't really care anymore as I made a [crate](https://crates.io/crates/parse_arg) for my specific use case.
