### ISSUE TITLE
Cannot type 's' on rustbyexample offline doc editable

### ISSUE THREAD

**Issue by iamsauravsharma** [rust-lang/rust#50221]
I can't type 's' on Rust By Example offline doc editable code area. Whenever i try to type 's' on offline doc it will open search bar since 's' is a short key for search bar. 
Search bar short key should be disabled when writing in editable code area or cursor is focused on editable code area of doc.

**Comment by GuillaumeGomez** [comment]
cc @steveklabnik

**Comment by steveklabnik** [comment]
This is a bug in the version of mdbook we shipped, and will be fixed as the trains go by.

Can you confirm that the nightly version works?

**Comment by iamsauravsharma** [comment]
Actually problem is in nightly version their is no problem in stable version since stable version doesn't have search bar functionality available in its docs.

**Comment by GuillaumeGomez** [comment]
I'm going to fix it in their repository then.

**Comment by steveklabnik** [comment]
I think we're also waiting on a new nightly to be produced to get the mdbook upgrade.
