### ISSUE TITLE
Accessing std::time::Instant internals

### ISSUE THREAD

**Issue by hetmankp** [rust-lang/rust#50241]
Currently it's difficult to test any code using `std::time::Instant` because of its opacity. While it's possible to do per project mocking I was wondering if there would be any interest in making testing easier by opening up the interface a bit. For example:

```rust
mod std::time {
    use sys::time;

    Instant {
        pub fn from_internal(internal: time::Instant) -> Instant;
        pub fn to_internal(self) -> time::Instant;
    }
}

mod std::sys::unix::time {
    Instant {
        pub fn from_internal(internal: u64) -> Instant;
        pub fn to_internal(self) -> u64;
    }
}
```

There may be other situations where access to the internals may be useful and although the above interfaces may discourage purity, they're unwieldy enough that I don't think abuse would be common.

**Comment by hellow554** [comment]
What is your usecase for that? Instant are mainly used to measure the difference between to instances (and then get a duration and do stuff).
If you want more I suggest you to use a crate (namely the [chrono crate](https://doc.rust-lang.org/std/time/struct.Duration.html#method.from_secs))

**Comment by hetmankp** [comment]
@hellow554 , when testing state machines that have time dependent transitions, the passage of time has to be controlled manually. That means being able to set and advance the internal value of `Instant`.

**Comment by hetmankp** [comment]
I should add that the above interface was just an example, I'm sure it can be done more idiomatically. I was also thinking that rather than exposing the exact internal representation of `std::sys::time::Instant`, the burden of writing tests across multiple platforms could be significantly reduced if instead we set it with a `time::Duration` (indicating the amount of time passed since machine startup):

```rust
mod std::sys::unix::time {
    use time::Duration;

    Instant {
        pub fn from_duration(duration: Duration) -> Instant;
        pub fn to_duration(self) -> Duration;
    }
}
```

**Comment by sfackler** [comment]
The only way you can interact with an `Instant` is to compute the duration from one to another. What is the difference between manually constructing one with a specific time since boot and a specific time since the time the test started?

**Comment by hetmankp** [comment]
@sfackler yes you're right. It shouldn't matter what the absolute value is for tests and it's already possible to control the relative values by adding `Duration`. I can't think of other practical situations where this feature request would actually be useful so I think this can be closed.
