### ISSUE TITLE
Create abstraction over paths for use in librustc_resolve

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#50258]
Currently, librustc_resolve passes around paths as `&[Ident]`.

Ideally, we'd have an abstraction over paths that:

 - contains this slice
 - contains a source node id for linting
 - contains a flag for whether or not the path is speculative -- sometimes we try to resolve paths not specified by the user to produce better error messages. We shouldn't be throwing errors for these.
 - eventually (out of scope for this change) -- contains a flag for whether or not the flag was originally a global path (`::foo`)

Currently the last two are kinda compressed into an `Option<NodeId>` argument to [`resolve_path`](https://github.com/rust-lang/rust/blob/7f3444e1baf0d335b4bf379f845dbc28cdd0509c/src/librustc_resolve/lib.rs#L3207) -- when it's speculative, the Option is None.

Having a `Path` abstraction would be nice.

**Comment by IsaacWoods** [comment]
If nobody is working on this, I'd like to give it a go to get my feet wet (never contributed to rustc tho)?

**Comment by TheSirC** [comment]
Is there anymore work to be done on that end ? @Aaronepower ? @IsaacWoods ? @Manishearth ?

**Comment by petrochenkov** [comment]
I'll go ahead an close this as not-an-issue.
Interfaces in librustc_resolve generally need to be rethought into something more systematic, especially after they changed a lot recently to accommodate new features, but simply grouping parameters of `resolve_path` into a struct won't move things into the right direction, but mostly bring unnecessary churn.
