### ISSUE TITLE
Spurious libtest.rmeta file generated

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#50289]
If I compile a simple program like:

```
fn main() {
    println!("Hello world");
}
```

Using:

`rustc --emit=metadata test.rs`

It generates an empty file titled "libtest.rmeta" since few Nightlies.

I am using:

```
rustc 1.27.0-nightly (7f3444e1b 2018-04-26)
binary: rustc
commit-hash: 7f3444e1baf0d335b4bf379f845dbc28cdd0509c
commit-date: 2018-04-26
host: x86_64-pc-windows-gnu
release: 1.27.0-nightly
LLVM version: 6.0
```

**Comment by ishitatsuyuki** [comment]
I think this is the intended behaviour. What do you expect otherwise?

**Comment by leonardo-m** [comment]
Can I use Rustc to just test the types of a program without generating extra files?

**Comment by Mark-Simulacrum** [comment]
I don't think we're inclined to support this sort of "check without emitting files" today so I'm going to go ahead and close. If someone wants this, I think a PR would not be too difficult to implement, maybe via `--emit=none` or something like that. Bikeshed on the naming, of course.
