### ISSUE TITLE
proc_macro_path_invoc feature gate should allow path-like invocation of bang macros

### ISSUE THREAD

**Issue by jcsoo** [rust-lang/rust#50285]
```
$ rustc --version
rustc 1.27.0-nightly (ac3c2288f 2018-04-18)
```
When #[feature(use_extern_macros)] is enabled, invoking bang macros using an explicit path triggers an error:
```
error[E0658]: paths of length greater than one in macro invocations are currently unstable
    --> /Users/jcsoo/bobbin-dev/bobbin-dev/mcu/bobbin-stm32/stm32f74x/src/irq.rs:1413:1
     |
1413 | ::bobbin_mcu::irq!(::dma::Dma2Stream7, IrqDma, Irq70);
     | ^^^^^^^^^^^^^^^^^
     |
     = help: add #![feature(proc_macro_path_invoc)] to the crate attributes to enable
```

Per discussion in https://github.com/rust-lang/rust/pull/50120#issuecomment-384981073, this type of invocation should be allowed.

**Comment by alexcrichton** [comment]
I believe this has [been fixed](https://github.com/rust-lang/rust/pull/50295)

**Comment by mark-i-m** [comment]
@alexcrichton Does this include things like `#[derive($crate::serde_serialize::Serialize)]`?

**Comment by petrochenkov** [comment]
@mark-i-m 
Multi-segment paths in attributes should still be gated with `proc_macro_path_invoc`, that includes `derive`.
