### ISSUE TITLE
Manual install on Linux x86_64 doesn't install into .../lib64

### ISSUE THREAD

**Issue by therealbstern** [rust-lang/rust#50292]
When installing on Linux x86_64 and using the installation script/tarball (i.e., not using `rustup`), Rust installs into `.../lib`, not `.../lib64`.  I believe `lib64` is more appropriate.  It's also what's in the default library search path in my distribution (Slackware).

I tried this code: `./install.sh`
```
# ls /usr/local/lib64
perl5
# ls /usr/local/lib
libarena-0ca7b9d43c18c972.so
[...]
libtest-d35c28f0ef54928a.so
rustlib
```
I expected to see this happen: Everything get installed into `/usr/local/lib64`

Instead, this happened: It was installed into `/usr/local/lib` instead.

## Meta

rustc 1.25.0 (84203cac6 2018-03-25)
binary: rustc
commit-hash: 84203cac67e65ca8640b8392348411098c856985
commit-date: 2018-03-25
host: x86_64-unknown-linux-gnu
release: 1.25.0
LLVM version: 6.0

(This was discovered while doing detective work for https://github.com/rust-lang/cargo/issues/5411.)

**Comment by joshtriplett** [comment]
Different distributions do this differently. Debian-based distributions put everything in lib directories, and separate them into architecture-specific subdirectories as part of multiarch to allow installing libraries for multiple architectures at the same time. Fedora uses lib for 32-bit, lib64 for 64-bit, and doesn't do multiarch.

I don't know if rust binaries *intend* to match the target distribution, or if they use the same install layout for all distributions.

**Comment by sfackler** [comment]
What do autoconf-based build systems do with respect to the default install directories?

**Comment by joshtriplett** [comment]
autoconf defaults to lib, and systems that want lib64 or similar tend to have a `config.site` file that configure reads to override the defaults, as well as setting the default search path for the compiler.

**Comment by oneforall2** [comment]
actually no .configure with --libdir=/usr/lib64 does that . But to get it to install to /usr/lib64 or /usr/local/lib64 it can be done with config.toml the lib path can be changed there . But when you try to do a local compile it is hard coded to look in /usr/lib which is extremely frustrating for a multilib(multiarch) . which by the way fedora does hence the lib for 32-bit, lib64 for 64-bit

**Comment by oneforall2** [comment]
@therealbstern  you could have grabbed the build script for rust from slackware current ;)

**Comment by sanxiyn** [comment]
Is there any bug here? It seems we match autoconf, which seems reasoanble to me.

**Comment by therealbstern** [comment]
I suppose so.
