### ISSUE TITLE
error message when unit test type does not implement `Termination` is ungreat

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#50291]
Edit: outstanding work is to change the span from pointing at the function body to point at the return type.

https://github.com/rust-lang/rust/pull/50272 adds a test for the case where a unit test returns a value  that does not implement `Termination`. The message currently talks about `main` and has an ugly multi-line span:

```
error[E0277]: `main` has invalid return type `std::result::Result<f32, std::num::ParseIntError>`
  --> $DIR/termination-trait-test-wrong-type.rs:18:1
   |
LL | / fn can_parse_zero_as_f32() -> Result<f32, ParseIntError> { //~ ERROR
LL | |     "0".parse()
LL | | }
   | |_^ `main` can only return types that implement `std::process::Termination`
   |
   = help: the trait `std::process::Termination` is not implemented for `std::result::Result<f32, std::num::ParseIntError>`
   = note: required by `__test::test::assert_test_result`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
```

**Comment by estebank** [comment]
As long as we have the method signature around when we emit E0277, it has a field with the span for the return type, which should be used for this instead, but this will probably require some special casing this in that (already quite hairy) diagnostic code. Extending `rustc_on_unimplemented` could be possible, but I would advice against doing so to avoid turning that attribute into a bigger monster than it already is.

```
error[E0277]: `main` has invalid return type `std::result::Result<f32, std::num::ParseIntError>`
  --> $DIR/termination-trait-test-wrong-type.rs:18:1
   |
LL | fn can_parse_zero_as_f32() -> Result<f32, ParseIntError> { //~ ERROR
   |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't implement `std::process::Termination`
   |
   = help: the trait `std::process::Termination` is not implemented for `std::result::Result<f32, std::num::ParseIntError>`
   = note: required by `__test::test::assert_test_result`
```

**Comment by shepmaster** [comment]
Chiming in that this confused me as I was preparing for a Rust training session, where I expect it would confuse the students even more.

**Comment by estebank** [comment]
CC https://github.com/rust-lang/rust/issues/60179

**Comment by azalutsky** [comment]
Just started learning Rust and came across this error while writing some tests- I absolutely agree "ungreat" is perfect word choice.

**Comment by GoldsteinE** [comment]
It could get even more confusing when using `Termination` trait as a bound:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3e4846799a8347bd969e5d5b841b157d

**Comment by fmease** [comment]
This issue is now (mostly) fixed on nightly by #103142 and should be closed I think. The error message is now correct but the span is still “ugly”. I've overlooked this issue and only closed its duplicate, namely #103052.

**Comment by estebank** [comment]
Actually, let's keep this open only for the span change :)

**Comment by necimye** [comment]
Just wrap the return type with a struct and implement the Termination trait for that wrapper struct
example
```

struct Complex(Box<dyn Fn(i32) -> i32>);
impl Termination for Complex {
    fn report(self) -> std::process::ExitCode {
        ExitCode::SUCCESS
    }
}
#[test]
#[allow(dead_code)]
fn returns_closure() -> Complex {
    Complex(Box::new(|x| x + 1))
}
```

**Comment by fmease** [comment]
@necimye Note that this GitHub issue is about the subpar error message given by the compiler which should be fixed and not about potential solutions for user code when facing this message.

@rustbot claim
