### ISSUE TITLE
improve `newtype_index!` macro

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#50337]
We have this [handy macro `newtype_index!`](https://github.com/rust-lang/rust/blob/9ff8ec8fdf02b6d8ba35373943e0c6de13597697/src/librustc_data_structures/indexed_vec.rs#L45) that creates a, well, newtype'd index:

```rust
newtype_index!(RegionAtLocationIndex { DEBUG_FORMAT = "RegionAtLocationIndex({})" });
```

However, I think it could be improved in four ways:

**First,** the syntax should change to include the keyword `struct` and `pub`. This would help with people trying to find the definition of the type. I'd probably switch to `{}` form at the same time, but that's not *necessary*:

```rust
newtype_index! {
  pub struct RegionAtLocationIndex { DEBUG_FORMAT = "RegionAtLocationIndex({})" }
}
```

**Second,** doing this would also allow us to support arbitrary visibilities. For example, I'd like to make `crate struct RegionAtLocationIndex`:

```rust
newtype_index! {
  crate struct RegionAtLocationIndex { DEBUG_FORMAT = "RegionAtLocationIndex({})" }
}
```

**Third,** we should change to incorporate `NonZero`. That is, the original example would [currently expands to something like](https://github.com/rust-lang/rust/blob/9ff8ec8fdf02b6d8ba35373943e0c6de13597697/src/librustc_data_structures/indexed_vec.rs#L76):

```rust
pub struct RegionAtLocationIndex(u32);
```

but I want it to expand to:

[`NonZero`]: https://doc.rust-lang.org/core/nonzero/struct.NonZero.html

```
pub struct RegionAtLocationIndex { non_zero: NonZero<u32> }
```

Of course, `0` is a valid index, so the [various initialization and accessor routines would have to add or subtract one](https://github.com/rust-lang/rust/blob/9ff8ec8fdf02b6d8ba35373943e0c6de13597697/src/librustc_data_structures/indexed_vec.rs#L78-L89) as appropriate. 

Using `NonZero` would mean that `Option<T>` would be represented still as a single u32.

Finally, **fourth**, as a convenience, it would be nice to define *inherent* (non-trait) methods, so that using these types did not require importing the `Idx` trait:

```rust
        impl $type {
            #[inline]
            fn new(value: usize) -> Self {..}
            #[inline]
            fn index(self) -> usize {..}
        }
```

cc @Nashenas88 @spastorino @sgrif

**Comment by sgrif** [comment]
FWIW I'd prefer we do `pub(crate) struct` instead of `crate struct`, so we continue to map to the corresponding Rust syntax. We should be able to just the vis matcher

**Comment by petrochenkov** [comment]
>`newtype_index!` macro

Oh, that thing stopping "Go To Definition" from working :smile:

**Comment by nikomatsakis** [comment]
@sgrif 

> FWIW I'd prefer we do pub(crate) struct instead of crate struct, so we continue to map to the corresponding Rust syntax. We should be able to just the vis matcher

`crate` *is* Rust syntax =)
