### ISSUE TITLE
Build fails if "make" is not gnu make

### ISSUE THREAD

**Issue by MartinHusemann** [rust-lang/rust#50341]
Trying to build locally on NetBSD. The bsd make has a -j option (with same semantic as gnu make), but the numeric argument is required. That is:
  gmake -j
works (unlimiting the number of parallel jobs), while
  make -j
does not. But
  make -j 6
works.

I think this is the issue I run into with the build, but I don't understand where the make invocation comes from. Tail of the build log (with x.py -v) is attached.
[rust-build.log](https://github.com/rust-lang/rust/files/1960465/rust-build.log)

**Comment by MartinHusemann** [comment]
So it happens here:

running: "./configure" "--prefix=/work/rust/build/build/x86_64-unknown-netbsd/stage2-tools/x86_64-unknown-netbsd/release/build/libz-sys-
94d96dac369e09ce/out"
Checking for shared library support...
Building shared library libz.so.1.2.11 with cc.
Checking for size_t... Yes.
Checking for off64_t... No.
Checking for fseeko... Yes.
Checking for strerror... Yes.
Checking for unistd.h... Yes.
Checking for stdarg.h... Yes.
Checking whether to use vs[n]printf() or s[n]printf()... using vs[n]printf().
Checking for vsnprintf() in stdio.h... Yes.
Checking for return value of vsnprintf()... Yes.
Checking for attribute(visibility) support... Yes.
running: "make" "libz.a"

and the make environment contains:

MAKEFLAGS=--jobserver-fds=10,11 -j --jobserver-auth=10,11 -j

which is what trigers the error.  I guess it comes from 

CARGO_MAKEFLAGS=--jobserver-fds=10,11 -j --jobserver-auth=10,11 -j

**Comment by pietroalbini** [comment]
cc @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
Hm, seems like possibly a fix for Cargo, not sure. I don't recall where CARGO_MAKEFLAGS is set (if it's even in one place) cc @alexcrichton

**Comment by jyn514** [comment]
@MartinHusemann are you still running into this issue?

**Comment by jyn514** [comment]
I'm going to close this as not a bootstrap issue, we don't set MAKEFLAGS to a jobserver argument so it must be a cargo bug if at all.
