### ISSUE TITLE
Confusing warn-unused-mut warnings since 1.27.0-nightly 2018-04-29

### ISSUE THREAD

**Issue by Robbepop** [rust-lang/rust#50343]
With the latest nightly (`rustc 1.27.0-nightly (66363b288 2018-04-29)`) I get confusing compile warnings about unused `mut` keywords where there are no `mut` keywords present.

The warnings do not happen on the previous nightly (`rustc 1.27.0-nightly (66363b288 2018-04-28)`) - so this might be a regression.

For further inspection the project where I receive those warnings can be found [here](https://github.com/Robbepop/stevia).

#### Some examples

```rust
warning: variable does not need to be mutable
   --> src/ast/visitor.rs:158:56
    |
158 |     fn visit_cond(&mut self, _cond: &expr::IfThenElse, _: VisitEvent) {}
    |                                                        ^ help: remove this `mut`
    |
    = note: #[warn(unused_mut)] on by default
```

```rust
warning: variable does not need to be mutable
   --> src/simplifier/simplifications/normalizer.rs:100:17
    |
100 |           .all(|(lhs, rhs)| {
    |                 ------^^^^
    |                 |
    |                 help: remove this `mut`
```

**Comment by ExpHP** [comment]
Bizarre; this must be where all the missing "unused `mut`" warnings from #50321 are running off to!

**Comment by nikomatsakis** [comment]
Just to confirm: this is specific to crates using `nll`, right?

**Comment by realcr** [comment]
This problem breaks our build. Some examples:

```bash
error: variable does not need to be mutable
   --> src/utils/async_mutex.rs:154:35
    |
154 |                         .map_err(|_| AsyncMutexError::AwakenerCanceled)?
    |                                   ^ help: remove this `mut`

...

error: variable does not need to be mutable
   --> src/timer.rs:153:19
    |
153 |             .map(|_| tm.create_client())
    |                   ^ help: remove this `mut`
    |
note: lint level defined here
   --> src/timer.rs:40:9
    |
40  | #![deny(warnings)]
    |         ^^^^^^^^
```

**Comment by KiChjang** [comment]
@realcr Same question ask Niko posted above -- does this only happen when you enable NLL?

**Comment by Robbepop** [comment]
In the case of my linked project `nll` is enabled but I cannot tell you if this bug is exclusive to `nll` enabled projects so I couldn't really answer niko's question.

**Comment by pietroalbini** [comment]
@KiChjang @nikomatsakis as far as I can see this only happens with NLL (or at least, this snippet emits the warning only with NLL enabled):

```
#![feature(nll)]

fn main() {
    vec![42].iter().map(|_| ()).count();
}

**Comment by nikomatsakis** [comment]
I guess that's a reduced test case?

**Comment by realcr** [comment]
@KiChjang : It's the first time I hear about NLL. It seems like my project does have NLL enabled.

```bash
$ ag "nll"
src/lib.rs
2:#![feature(nll)]
```
Interesting.

**Comment by nikomatsakis** [comment]
Some more test cases to check:

https://play.rust-lang.org/?gist=d3c7474ec8713a2274ba1686cbc63da4&version=nightly&mode=debug

https://play.rust-lang.org/?gist=f97057569a68e71f474bee73ad3a4c8f&version=nightly&mode=debug
