### ISSUE TITLE
Rustdoc: "Show type declaration" is misleading on traits

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#50347]
If we visit a page such as: https://doc.rust-lang.org/nightly/std/convert/trait.From.html
we will see "Show type declaration" when folding of the declaration is done.
However, `From` is a trait and not a type, so the documentation is potentially misleading or confusing.

I propose two alternatives to address this problem:

1. Remove "type" and only say "Show declaration"; This removes information when you actually land on the documentation of a type.

2. Say "Show trait declaration" instead when it is a trait.

**Comment by GuillaumeGomez** [comment]
I'll go for the first one!
