### ISSUE TITLE
change Rust installation path

### ISSUE THREAD

**Issue by Nocxy** [rust-lang/rust#50361]
Hi everyone,

I would like to know a way to change Rust's installation path. I'm a macOS user trying to tidy up his files. I would like to install everything in a folder named, e.g., "Rust installation folder" (well, let's be original...). Could anyonoe help me to do so?

Thanks in advance,
Nocxy

**Comment by pietroalbini** [comment]
Thanks for reporting this issue! This issue tracker is only for bugs of the compiler or enhancement requests though, not for support. You can post this on [users.rust-lang.org](https://users.rust-lang.org), our support forum `:)`

**Comment by Nocxy** [comment]
I have an issue: I have files all over the place and would like to know a way to get them all in the same place.

**Comment by retep998** [comment]
The environment variables `RUSTUP_HOME` and `CARGO_HOME` determine where rustup and cargo dump all their files.
