### ISSUE TITLE
libtest: provide a way to run *all* tests

### ISSUE THREAD

**Issue by vext01** [rust-lang/rust#50363]
I originally [raised this against Cargo](https://github.com/rust-lang/cargo/issues/5419), but I've since learned that this is to do with `libtest` inside Rust itself.

So we have:
```
cargo test
```

To run all but ignored tests. Then:
```
cargo test -- --ignored
```

To run only ignored tests.

But as far as I can see there is no way to run **all** tests in parallel short of:
```
cargo test & cargo test -- --ignored
```

Which isn't ideal for scripting and is not convenient.

How about?
```
cargo test -- --all
```

Cheers

**Comment by Emerentius** [comment]
Exercism depends a lot on ignored-by-default tests so this would be really useful. A short look over libtest makes me believe that this would be very easy to add. I'll try my hand at it.

**Comment by eddyb** [comment]
Reopening because I had to revert #53527 to land edition-critical #54116.

**Comment by corneliusroemer** [comment]
@Emerentius I came here because I'm just working through Excercism and don't want to uncomment all the ignored tests ;)
