### ISSUE TITLE
Cargo.lock isn’t encoded in unicode

### ISSUE THREAD

**Issue by fbruetting** [rust-lang/rust#50372]
`file -i` displays `charset=us-ascii` for Cargo.lock. Would be nice if Cargo also would stick to the unicode standard.

**Comment by jonas-schievink** [comment]
Rust programs use UTF-8 by default (unicode is not an encoding). Encoding an ASCII string as UTF-8 is a no-op since UTF-8 is backwards-compatible to ASCII, so `file` can't tell the difference.

**Comment by fbruetting** [comment]
Ok, I thought that the encoding is saved as meta information in the inode and `file` just displays that information.
