### ISSUE TITLE
"add_fetch" is needed in "sync::atomic"

### ISSUE THREAD

**Issue by solotzg** [rust-lang/rust#50388]
Method `add_fetch` is needed in `sync::atomic` to implement function like `__sync_add_and_fetch`

**Comment by kennytm** [comment]
You could write `add_fetch` in terms of `fetch_add` like this:

```rust
fn add_fetch(a: &AtomicUsize, b: usize, order: Ordering) -> usize {
    a.fetch_add(b, order) + b
}
```

**Comment by Mark-Simulacrum** [comment]
I personally feel like in most cases where I've used atomics this isn't too useful so doesn't carry its weight (atomics in std are currently the "lowest" primitives possible for the most part)
