### ISSUE TITLE
std::string::String should strip UTF BOM

### ISSUE THREAD

**Issue by hanyuwei70** [rust-lang/rust#50386]
When the BOM is presented in the input stream, `String` object should strip it and do not output BOM.

**Comment by alexcrichton** [comment]
I would agree, yeah, that this is likely an RFC topic rather than an issue or a PR

**Comment by SimonSapin** [comment]
It’s not clear what is being proposed. Which APIs exactly should strip?

And more importantly, why? I tend to think of these standard library API as low-level primitives, and feel that BOM removal would tend to belong more in a higher library that might for example also support multiple encodings and detect the presence of a BOM to help pick one. And even then, maybe not always. https://docs.rs/encoding_rs/0.7.2/encoding_rs/struct.Decoder.html#impl has different methods for different use cases, only some of them remove a BOM.

**Comment by BurntSushi** [comment]
I also agree this requires an RFC and side with @SimonSapin on this. I think we would need exceptional motivation to do this.

**Comment by steveklabnik** [comment]
Thanks all! @hanyuwei70 please pursue one of them if you think you can address these comments: https://github.com/rust-lang/rfcs
