### ISSUE TITLE
ICE: non-lifetime passed to :lifetime

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#50381]
This code crashes the compiler. However, the location of the error is pointed out, which is nice.

```rust
#![feature(macro_lifetime_matcher)]

macro_rules! m { ($x:lifetime) => { } }

m!(a);
```

```
error: internal compiler error: not a lifetime
 --> src/main.rs:5:8
  |
5 |     m!(a);
  |        ^

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:491:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: aborting due to previous error
```

cc #50380 @ricochet1k

**Comment by kennytm** [comment]
cc #34303.

**Comment by estebank** [comment]
The error [occurs during parsing a lifetime unconditionally](https://github.com/rust-lang/rust/blob/d40a0b3dc17acd585d3e41d08db6d516842cea96/src/libsyntax/parse/parser.rs#L2050-L2059), which is used during macro parsing: https://github.com/rust-lang/rust/blob/d40a0b3dc17acd585d3e41d08db6d516842cea96/src/libsyntax/ext/tt/macro_parser.rs#L838

I would modify the code above to preemptively use `check_lifetime()`, and if `false`, emit an appropriate diagnostic error.

**Comment by rleungx** [comment]
I'm interested in taking this issue.
