### ISSUE TITLE
Please put "see also" links at top, not at bottom.

### ISSUE THREAD

**Issue by ExpHP** [rust-lang/rust#50384]
I mean these:

https://doc.rust-lang.org/std/primitive.slice.html -- *See also the `std::slice` module*
https://doc.rust-lang.org/std/slice/index.html -- *See also the slice primitive type.*

These don't belong at the bottom; they aren't there "for further reading."  They're more like, *hey, is this what you were looking for?*

<sub>(and the answer is yes.  Yes it was.  Why do I keep accidentally landing on the std::slice page when I want to see the `[T]` docs.  Why why why.)</sub>

**Comment by steveklabnik** [comment]
We talked about this at the meeting today, and the general reaction was "I thought they were at the top already". Let's do it!

**Comment by ExpHP** [comment]
I'll put something together.  Grepping around, it also seems that `str (primitive)` hides its link to `std::str` in prose:

> This documentation describes a number of methods and trait implementations on the `str` type. For technical reasons, there is additional, separate documentation in the [`std::str`]() module as well.

*...technical reasons?*

**Comment by steveklabnik** [comment]
Thank you! Let's fix it to be consistent with the others.

> ...technical reasons?

Yeah, it's..... yeah. Anyway, let's drop all of this and just make it identical to the others.
