### ISSUE TITLE
Tracking issue for macro :lifetime matcher

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#50380]
This tracks the `macro_lifetime_matcher` feature which provides a `:lifetime` matcher for `macro_rules`.

- [x] Implemented in #46895.
- [ ] Stabilize?

**Comment by durka** [comment]
Found an [ICE](https://github.com/rust-lang/rust/issues/50381).

**Comment by petrochenkov** [comment]
@durka 
There's a tracking issue (https://github.com/rust-lang/rust/issues/34303) and it even completed FCP. Someone should send a stabilization PR.

**Comment by durka** [comment]
Oh, I'll do it then instead of updating the tracking issue number.
