### ISSUE TITLE
Hosted compiler docs outdated

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#50394]
The compiler docs hosted on docs.rust-lang.org seem to be outdated with respect to the latest available nightly.

**Comment by pietroalbini** [comment]
cc @rust-lang/infra

**Comment by kennytm** [comment]
The docs will be updated when a new nightly is released, which requires a working RLS first. RLS has recently been fixed by #50379, so I'd expect an update within a day.

**Comment by kennytm** [comment]
The compiler docs has been updated to `Version 1.27.0-nightly (8a37c75a3 2018-05-02)`. Thus closing.
